### ISSUE TITLE
Efficient DB locking mechanisms (global user inactivity, session lock, etc.)

### ISSUE THREAD

**Issue by anatoli26** [keepassxreboot/keepassxc#100]
The latest KeePassX version before the fork lacked the inactivity mechanisms available in KeePass.

First of all, the current "Lock database after inactivity of X" means the inactivity of KPX use, not the global user inactivity in the current desktop session, which makes it almost unusable (it locks too quickly if the app is not used, though the user is using the computer (e.g. with a 15 min timeout), but with a long timeout (e.g. 2hs) it makes no sense at all). 

So, here goes the list for adequate DB locking mechanisms (apart from 'Lock on KPXR inactivity' that is already implemented):
1. Lock on global desktop session inactivity
2. Lock on session lock/suspend (and other session suspension/termination events)
3. ~~Lock when minimizing main window~~ (already implemented in the latest commit)

Here are these and other KeePass security settings
![keepass-security](https://cloud.githubusercontent.com/assets/22968420/20459376/f3e8201a-ae9d-11e6-9a15-a8aa5ec46062.jpg)

_To give this issues a higher priority, I'm willing to contribute economically. Those who could implement all 3 features on the latest OS X and Gnome/logind (if you find a OS-independent mechanism, great! If not, I would prioritize these 2 OS/DE) please specify how much should be collected and I could contribute to the implementation on [bountysource.com](https://www.bountysource.com/) or your crowdfunding site of preference._

**Comment by Tamriel** [comment]
KeePassXC is minimized to the tray, locked. The browser is open, I type the global autotype shortcut. A popup asks for password to unlock, I enter it, the password is filled in the browser. KeePassXC is minimized to the tray, but now unlocked!
I would love the feature 'Unlock from autotype shall only unlock for that single autotype.'

**Comment by TheZ3ro** [comment]
@Tamriel 
Can you please open a new Issue? 
I was thinking that I fixed this in a previous PR but I was wrong.
Thanks

**Comment by phoerious** [comment]
Locking when minimizing the window is implemented in 2.1.0.
For locking when you lock your desktop session, please continue discussion in #134 or the corresponding PR #135.
