### ISSUE TITLE
Font size too small to be usable

### ISSUE THREAD

**Issue by zero-master** [keepassxreboot/keepassxc#1000]
Font size in Ubuntu is too small.

Here is a hack to fix this issue: http://www.vakuumverpackt.de/configurablesystemfontsformono/

It would be cool if you guys can make it configurable.

**Comment by adatum** [comment]
Are you sure you're using keepassxc? A key reason for its development was to avoid mono...

**Comment by pskraemer11** [comment]
I don't use mono, therefore installed keepassxc. But the problem remains: the font size is too small!
Not everybody has the eys of an eagle ...

**Comment by phoerious** [comment]
Which release are you using? PPA? Snap? AppImage?

**Comment by droidmonkey** [comment]
Also please stop posting to closed issues

**Comment by Seegras** [comment]
Archive of the above URL https://web.archive.org/web/20161025103319/http://www.vakuumverpackt.de/configurablesystemfontsformono/ But the patches are not accessible anymore. 

(I post this for other people that might search the very same issue; unrelated to keepassxc)

**Comment by droidmonkey** [comment]
Adjusting settings related to Mono will do nothing for KeePassXC. You need to adjust Qt variables, see our user guide: https://keepassxc.org/docs/KeePassXC_UserGuide#_command_line_options

Specifically `QT_SCALE_FACTOR [numeric]`
