### ISSUE TITLE
Yubikey hardware key no longer detected again under 2.7.4

### ISSUE THREAD

**Issue by ACH1980** [keepassxreboot/keepassxc#10002]
## Overview
I have the problem that when I try to add my YubiKey 5 NFC to a new database it says "no Hardwarekey found.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Plugin Yubikey
2. Open KeypassXC
3. Try to use Hardwarekey

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Hardwarekey shows up in KeepassXC

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Hardwarekey blinks up, but KeepassXC says "No Hardwarekey detected"

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.4
Revision: 63b2394

Qt 5.15.8
Diagnosemodus ist deaktiviert.

Betriebssystem: Debian GNU/Linux 12 (bookworm)
CPU-Architektur: x86_64
Kernel: linux 6.1.0-13-amd64

Aktivierte Erweiterungen:
- Auto-Type
- Browser-Integration
- SSH-Agent
- KeeShare
- YubiKey
- Secret-Service-Integration

Kryptographische Bibliotheken:
- Botan 2.19.3

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: XFCE
Windowing System: X11

Output of `ykman info`:

```(base) kanjiasdev@laptop1:~$ ykman info
Device type: YubiKey 5 NFC
Serial number: 20615830
Firmware version: 5.4.3
Form factor: Keychain (USB-A)
Enabled USB interfaces: OTP, FIDO, CCID
NFC transport is enabled.

Applications	USB    	NFC    
FIDO2       	Enabled	Enabled	
OTP         	Enabled	Enabled	
FIDO U2F    	Enabled	Enabled	
OATH        	Enabled	Enabled	
YubiHSM Auth	Enabled	Enabled	
OpenPGP     	Enabled	Enabled	
PIV         	Enabled	Enabled	
(base) kanjiasdev@laptop1:~$```

**Comment by droidmonkey** [comment]
That would indicate you did not configure a slot on the yubikey to use hmac challenge response. See here: https://keepassxc.org/docs/#faq-yubikey-howto

Also recommend updating to 2.7.6

**Comment by ACH1980** [comment]
I did set that up. Is it maybe unable to work with the PIN protection for that?

I've set a PIN for those Challenge&Respond app like for every Yubikey application else.

**Comment by droidmonkey** [comment]
That is not Challenge Response, there is no pin involved in challenge response.

**Comment by ACH1980** [comment]
Well it's not called PIN, right. It's called "static password", but basically for me it's like a PIN as I only used numeric chars for that. Apparently even ykman seems to have an issue with that. So I guess that could be the issue, right?

**Comment by droidmonkey** [comment]
You have not setup hmac challenge response. Watch this video: https://youtu.be/-9kWMU_H7iQ?feature=shared

**Comment by ACH1980** [comment]
Apparently I did set that up. I used cli because the personalization tool is deprecated - apparently I found out that I did not set a static password, but an access-code (that option is in the video as well, but it's unchecked)...
