### ISSUE TITLE
Document custom browser option

### ISSUE THREAD

**Issue by kavol** [keepassxreboot/keepassxc#10004]
I was exploring the possibility to integrate keepassxc with my favourite browser - Falkon.
I've found it mentioned in issue #1594 .
Cool, so there should be the possibility.
However, in reality, I failed miserably, because I don't know how to configure that.
The "Setup Browser Integration" chapter of the user guide does not describe the advanced options.
It does not even mention where to get the browser extension outside the official stores for the selected browsers which don't work with the alternatives, obviously.

**Comment by varjolintu** [comment]
Thanks for the wake up call :)

**Comment by kavol** [comment]
Thanks for adding the bits, but it still doesn't help my case. See issue #11252.

**Comment by varjolintu** [comment]
@kavol The [Troubleshooting Guide](https://github.com/keepassxreboot/keepassxc-browser/wiki/Troubleshooting-guide) that's linked to the document describes that in detail.
