### ISSUE TITLE
Auto-Type {CLEARFIELD} doesn't work with SQuirreL

### ISSUE THREAD

**Issue by pstueck** [keepassxreboot/keepassxc#10006]
Bug #6463 seems still to be a thing.
On 2.7.6 flatpak and the fields are still not cleared … at least with [SQuirreL](http://www.squirrelsql.org/) and on web server logins.  

  

KeePassXC - Version 2.7.6
Revision: dd21def
Distribution: Flatpak

Qt 5.15.10
Debugging mode is disabled.

Operating system: KDE Flatpak runtime
CPU architecture: x86_64
Kernel: linux 6.2.0-36-generic

Operating System: Linux (Ubuntu 22.04)
Desktop Env: Gnome resp. KDE from Flatpak runtime
Windowing System: X11

`Linux ******* 6.2.0-36-generic #37~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Mon Oct  9 15:34:04 UTC 2 x86_64 x86_64 x86_64 GNU/Linux`

_PS: didn’t expect such problems with a KeePass2-to-KeePassXC transition. :-(_

**Comment by droidmonkey** [comment]
Works fine in firefox, but doesn't work in SQuirreL.

You should also update to 2.7.6.

On Linux, {CLEARFIELD} is implemented as `CTRL + HOME, CTRL + SHIFT + END, BACKSPACE`

**Comment by pstueck** [comment]
So … maybe … the problem is related to keyboard layouts with “dead keys”? … when I changed my keyboard layout to one without dead keys, the ~`{CLEARFIELD}`~`^{HOME}^+{END}{BACKSPACE}` sequence did work … about 1 out of 5 tries.
_Back to `{CLEARFIELD}` resp. “dead keys” and I’m outta luck again._

In my experience, `{CLEARFIELD}` just does not work.
Just verified it on Chrome as well … works fine, if the fields are empty, but just does not clearing fields, if there is anything already in there. Also verified that the key sequence per se would work (manual typing in an affected field, *but* the `{CLEARFIELD}` sequence itself in the auto-type field does not work reliably either).
That said … I also keep getting “Modifier keys held by user” – which puzzles me, as all I did was …
* using my shortcut to invoke the auto-type
`Alt + Ctrl + Shift + V`
* select the required entry from the list
* hit `Enter`
Granted, the dialog does not happen every time, just every now and then (seems to be linked to initial delay and delay between keystrokes – with 100ms + 5ms I was completely outta luck … with 300ms and 25ms it seems to work most of times).

_For clarification: with “web server login” I was referring to that (nowadays hardly seen) direct logins via web server (which you could bypass with extended URLs like `http://user:pw@host/path`)._

I guess that’s just an oversight, right? You said …
> You should also update to 2.7.6.

but also I said …
> KeePassXC - Version 2.7.6

Regarding the lightning fast fix …
> Fixes #10006

Thanks! I will give it a try, as soon as a flatpak with the fix is available … can also verify that the `{HOME}+{END}{BACKSPACE}` sequence – used instead of `{CLEARFIELD}` – does work (although I kept getting “Modifier keys held by user” with only 300ms delay … with 500ms delay it’s working).
_I’m aware the new version won’t happen anytime soon – no worries._
