### ISSUE TITLE
Which entry exist in the keepassxc.ini file ?

### ISSUE THREAD

**Issue by Sicoval31** [keepassxreboot/keepassxc#10005]
Hi, 
we want to deploy KeppasXC on many windows computer.
It's semms no option are available to deploy by GPO ... so using some parameters trough the .ini files is a solution (not the best).

But ... what are all the entry (and the usecase) of the kepassXC.ini files ? Were can i find this ?
This files is not documented :(

Thanks

**Comment by droidmonkey** [comment]
You shouldn't need to adjust much of anything in the ini files, plus any user can make their own changes. Use the settings within the application to set the desired defaults and just copy the resulting ini file.
