### ISSUE TITLE
Crash: `zlib1.dll` missing after `LegacyWindows` install

### ISSUE THREAD

**Issue by inspector71** [keepassxreboot/keepassxc#10003]
## Overview
Microsoft Windows 7 Home Premium 6.1.7601 Service Pack 1 Build 7601

Cannot run, use the program. 

Crashes with the error:

`The program can't start because zlib1.dll is missing from your computer. Try reintalling the program to fix this problem`

## Steps to Reproduce
1. downloading and installing:

`KeePassXC-2.7.6-Win64-LegacyWindows.msi`

2. at the end of the install wizard, leave the box ticked to run the app immediately. 

## Expected Behavior
Program runs.

## Actual Behavior
Program crashes.

**Comment by droidmonkey** [comment]
Reinstall it, this seems to be happening randomly.

**Comment by inspector71** [comment]
Ran the installer again, Chose `Repair`, it worked!

... however, a password manager that is, with all due respect to the hard work of the developers and knowing that 'legacy' support is much appreciated for how fiddly it might be, this unreliable _is a scary thing_.

**Comment by inspector71** [comment]
Should this issue be immediately closed?

**Comment by droidmonkey** [comment]
Our program is not unreliable, this is just the installer. We did nothing different between 2.7.5 and 2.7.6 with the installer configuration, and this appears to happen randomly to some users all of a sudden. You aren't the first to report it. 

See #9773

**Comment by inspector71** [comment]
I guess it depends on what you define as 'our program'. If people can't
install and run it, there is no program. FWIW, maybe nothing, I was just
thinking this is a bug that would ideally be worked on.
