### ISSUE TITLE
Tools -> Password Generator not working in 2.8.0-snapshot

### ISSUE THREAD

**Issue by rpedrica** [keepassxreboot/keepassxc#10007]
## Overview
Selecting Tools -> Password Generator from the toolbar menu (or associated toolbar icon) just shows an empty screen.

## Steps to Reproduce
Select Tools menu
Select Password Generator menu item

## Expected Behavior
Show password generator

## Actual Behavior
Screen is empty

![keepassxc-pwdgen](https://github.com/keepassxreboot/keepassxc/assets/1016286/8ade5a73-cc4e-4495-820f-bbf31a72516f)

## Context
The password generator within a password entry works as per normal.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.8.0-snapshot
Build Type: Snapshot
Revision: 6f2354c

Qt 5.15.11
Debugging mode is disabled.

Operating system: Slackware 15.0 x86_64 (post 15.0 -current)
CPU architecture: x86_64
Kernel: linux 6.1.61

Enabled extensions:
- Auto-Type
- Browser Integration
- Passkeys
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.19.3

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: KDE
Windowing System: X11

**Comment by droidmonkey** [comment]
Update your snapshot
