### ISSUE TITLE
Asistente de IA de tipo automático para nuevas secuencias.

### ISSUE THREAD

**Issue by aldomach** [keepassxreboot/keepassxc#10019]
## Summary
It would be very useful to add a wizard with buttons to the autotype part so that you don't have to look for references and write with errors, when you click you write in the text box. I show you what I made for my particular use and am using for new posts.
It would also be nice to be able to save a history, so when I have another entry that uses the same sequence I can use it
![20231113-180512_keepass_autotype_gui](https://github.com/keepassxreboot/keepassxc/assets/43079355/27823948-4529-4e9a-a08f-aa51d14ec7fa)

**Comment by droidmonkey** [comment]
Thank you, however this is a duplicate request
