### ISSUE TITLE
copy of username/password not working

### ISSUE THREAD

**Issue by slartibart70** [keepassxreboot/keepassxc#10016]
keepassxc 2.7.6
Operating System: Fedora Linux 38
KDE Plasma Version: 5.27.9
KDE Frameworks Version: 5.111.0
Qt Version: 5.15.11
Kernel Version: 6.5.11-200.fc38.x86_64 (64-bit)
Graphics Platform: Wayland

Problem:
Copying username or passwords with shortcuts (Ctrl-B, Ctrl-C) or by using context-menus is not working any more
Same for copying urls, title or notes
(auto-fill in by e.g. browser-extension is working ok)

I can select the text in the forms, and copy by shortcut or context menu.
But, this seems like a regression, i really liked those copy-features :-) 

Oter shortcuts/context menu entries like edit (Ctrl-e), clone (Ctrl-k) etc are working as expected.

Any ideas?

**Comment by droidmonkey** [comment]
You need to figure out your Wayland environment because that is what is causing the problem. You are likely running KeePassXC using xwayland and copy/paste isn't working as a result. We use Qt to interface with the clipboard so there is no environment specific code in place on our end.

**Comment by droidmonkey** [comment]
I just tested this in Fedora 38, KDE, Wayland using KeePassXC as a Flatpak and it worked fine.

**Comment by slartibart70** [comment]
yes, you are right... this was running in xwayland unnoticed. Sorry.
Tested with wayland, all is fine
Anyway: thanks for the quick response!!!
