### ISSUE TITLE
The minimized window disappears after the first systray icon click

### ISSUE THREAD

**Issue by ferenczy** [keepassxreboot/keepassxc#10015]
## Overview
When I minimize the window to the system tray and try to restore it by clicking on the system tray icon, the window re-appears after the **first mouse click** and immediately disappears again. You can notice that the window itself and the window's task bar button appear for just a few milliseconds. After the **second click**, it successfully re-appears and stays open.

It's doing that consistently in 100% of cases. The only condition is that the **window has to be minimized using the minimize button**, when it's minimized by left-clicking on the system tray icon (when the window is open), the problem doesn't occur.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. In the _Settings_ > _General_ > _User Interface_, check the options:
    - _Show a system tray icon_
    - _Hide window to system tray when minimized_
2. Minimize the window to the system tray **using the window decoration minimize button**
3. Click on the system tray icon once using the left mouse button 
4. The window re-appears for a few milliseconds and disappears again
5. Click on the system tray icon once using the left mouse button
6. The window successfully re-appears

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
The window is restored from the system tray using a single left-mouse button click on the system tray icon like other applications.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
I have to click on the system tray icon twice to restore the window.

## Context
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.6
Revision: dd21def

[NOTE]: # ( Pick choices based on your environment )
Operating System: Ubuntu 22.04.3
Desktop Env: Xfce 4.16
System tray rendered using the Xfce panel's Status Tray plugin (built-in default)
Windowing System: X11

**Comment by droidmonkey** [comment]
I cannot reproduce this. Fedora Core 38, Xfce 4.18, status notifier plugin 0.2.2

KeePassXC 2.7.6 as Flatpak, Snap, and native install.

Check your window settings and any other ancillary settings, this does not appear to be a KeePassXC bug.

I can kind of replicate your observed behavior if I double click the tray icon, but that is expected behavior.

**Comment by ferenczy** [comment]
Thank you for checking it out! In my case it's the opposite - when I double click the icon, it's opened correctly, but still it's opened, closed and opened again.

I have also tried to check _Menu is primary action_ on the Tray Status plugin properties dialog. In that case, when I click the icon, a context menu is shown with the _Toggle window_ as the first item. But it behaves the same - the first time I click it, the window is opened and closed immediately. So I open the menu again, click the _Toggle window_ again and the window is properly opened.

Just a reminder that when the window is hidden by clicking on the systray icon, it works as expected for me.

I don't know what to look for. I have quite a fresh installation (maybe two weeks old) and it's quite default without any hacks. And all other applications that have a systray icon behave as expected (e.g. Guake, Double Commander, CopyQ, qBittorrent and all icons produced by KDocker).
