### ISSUE TITLE
Window snapping & tiling not working

### ISSUE THREAD

**Issue by DavidPesticcio** [keepassxreboot/keepassxc#10018]
## Overview
When dragging the KeePassXC window to the left or right edge to snap and tile the window, this works fine - all other directions fail to activate at all.

## Steps to Reproduce
1. Un-minimize KeePassXC
2. Drag title bar to left or right edge to snap and tile - all ok.
3. Try dragging title bar to top or bottom edge, or into any corner - nothing happens. :cry: 

## Expected Behaviour
KeePassXC window should snap and tile when title bar is dragged to top or bottom edge, or into any corner.

## Actual Behaviour
Only works for left and right edges. (All other apps behave as expected)

## Context
None

## Other Details
KeePassXC - Version 2.7.6
Revision: dd21def

Qt 5.15.3
Debugging mode is disabled.

Operating system: Linux Mint 21.1
CPU architecture: x86_64
Kernel: linux 5.15.0-88-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.19.1

Operating System: Linux
Desktop Env: Cinnamon
Windowing System: X11

**Comment by droidmonkey** [comment]
The snapping behavior is 100% controlled by the desktop environment (in this case Cinnamon). 

Have you tested other Qt-based apps?

**Comment by varjolintu** [comment]
How is your KeePassXC installed? I tested this with Fedora & Cinnamon, and installed KeePassXC directly from the repos (so now AppImage or Flatpak). Snapping worked normally from all sides.

**Comment by DavidPesticcio** [comment]
Hi both,

I installed it from the PPA @ https://launchpad.net/~phoerious

<details>
  <summary>$ apt show keepassxc</summary>

```
$ apt show keepassxc
Package: keepassxc
Version: 2.7.6-1ppa1~jammy1
Priority: optional
Section: utils
Maintainer: KeePassXC Team <team@keepassxc.org>
Installed-Size: 29.2 MB
Depends: libargon2-1 (>= 0~20171227), libbotan-2-19 (>= 2.19.1+dfsg), libc6 (>= 2.34), libgcc-s1 (>= 3.0), libminizip1 (>= 1.1), libpcsclite1 (>= 1.3.3), libqrencode4 (>= 3.2.0), libqt5concurrent5 (>= 5.6.0~rc), libqt5core5a (>= 5.15.1), libqt5dbus5 (>= 5.0.2), libqt5gui5 (>= 5.15.1) | libqt5gui5-gles (>= 5.15.1), libqt5network5 (>= 5.0.2), libqt5svg5 (>= 5.6.0~beta), libqt5widgets5 (>= 5.15.1), libqt5x11extras5 (>= 5.6.0), libreadline8 (>= 6.0), libstdc++6 (>= 5.2), libusb-1.0-0 (>= 2:1.0.8), libx11-6, libxtst6, libzxcvbn0 (>= 0.20150103), zlib1g (>= 1:1.1.4)
Conflicts: keepassxc-beta (<< 2.5.0)
Replaces: keepassxc-beta (<< 2.5.0)
Download-Size: 7,086 kB
APT-Manual-Installed: yes
APT-Sources: https://ppa.launchpadcontent.net/phoerious/keepassxc/ubuntu jammy/main amd64 Packages
Description: KeePass Cross-Platform Community Edition
 KeePassXC is a community fork of KeePassX, a native
 cross-platform port of KeePass Password Safe, with
 the goal to extend and improve it with new features
 and bugfixes to provide a feature-rich, fully
 cross-platform and modern open-source password manager.


$ keepassxc --version
KeePassXC 2.7.6
```
</details>

All other windows that I've tested behave as expected, including Joplin which is Node based and running in a container created by [distrobox](https://github.com/89luca89/distrobox) - although this is not true for when I run the same version of KeePassXC from within distrobox... :raised_eyebrow:   

Could I have changed some KeePassXC config that would affect this?


@droidmonkey - I tried the same test with the VirtualBox Graphical User Interface and it behaves as expected.
<details>
  <summary>VirtualBox Graphical User Interface Info</summary>

```
  VirtualBox Graphical User Interface
  Version 6.1.40 r154048 (Qt5.15.3)
  Copyright © 2022 Oracle Corporation and/or its affiliates. All rights reserved.
```
</details>

I also tested the native Bitwarden desktop app, which is also Node based like Joplin, and it displays the same behaviour as KeePassXC - :confused: 
<details>
  <summary>Bitwarden Info</summary>

```
  Version 2023.9.3
  Shell 25.9.1
  Renderer 114.0.5735.289
  Node 18.15.0
  Architecture x64
```
</details>


Interestingly, I tried the snapping with Scribus a DTP app, also Qt based, and it will do only left, right, and top to maximise - no corner or bottom edge options.

I also tried FreeCAD, which uses Qt and reports v5.15.2, and it will do all edges, including corners.

<details>
  <summary>FreeCAD Info</summary>

```
OS: Linux Mint 21.1 (X-Cinnamon/cinnamon)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.19.
Build type: Release
Python version: 3.10.2
Qt version: 5.15.2
Coin version: 4.0.0
OCC version: 7.5.1
Locale: English/United Kingdom (en_GB)
```
</details>

Also tried Calibre, Clementine, Strawberry, all Qt based, and they will do all edges, including corners. :thinking: 

I'm wondering if the Qt based app has to "request" or "state" these abilities from/to the DTE?

This may be helpful: [https://github.com/pedrolcl/winsnap/blob/main/snapwindow.cpp#L34](https://github.com/pedrolcl/winsnap/blob/main/snapwindow.cpp#L34)

**Comment by droidmonkey** [comment]
This isn't a KeePassXC problem (as evidenced by Bitwarden and other apps failing too). That window snapping demo is totally unnecessary as this is a feature implemented by the desktop environments NOT applications. 

There is no setting in Qt to disable or modify window snapping.

Recommend writing a bug report to Cinnamon, their snapping seems inconsistent and needs to be looked into.

**Comment by DavidPesticcio** [comment]
@droidmonkey - Completely ignoring the fact that other Qt apps mentioned above work fine, it also works fine with KeePassX and KeePass2 :confused:

**Comment by droidmonkey** [comment]
I didn't ignore that, it is obviously inconsistent and not app or architecture dependent. Plus @varjolintu tested it himself and it worked fine. We aren't going to invest any time in this issue.

**Comment by DavidPesticcio** [comment]
@varjolintu - Out of curiosity, what version of Cinnamon are you using?

**Comment by DavidPesticcio** [comment]
@droidmonkey / @varjolintu

FYI:

> This is probably because tiling into those locations would cause the window to be resized smaller than its minimum size (in one or both directions).
> 
> These minimums are set by the app's toolkit (Gtk or Qt), whatever widget size calculations turn up.
> 
> To check you can just manually resize these windows to see if either dimension might prevent tiling in these locations. If you can't manually resize it enough, then Cinnamon/muffin won't do it either.

https://github.com/linuxmint/cinnamon/issues/11925?notification_referrer_id=NT_kwDOAIlCirI4NDE3NDk2NjY1Ojg5OTU0NjY#issuecomment-1814961384
