### ISSUE TITLE
Unable update on Fedora 38

### ISSUE THREAD

**Issue by iovcho** [keepassxreboot/keepassxc#10014]
## Overview
Unable update via dnf on fedora 38

## Steps to Reproduce
1. dnf makecache
2.  dnf update -y

## Expected Behavior
Last metadata expiration check: 0:22:27 ago on 12.11.2023 (нд) 15:37:11.
Dependencies resolved.

 Problem 1: package qt5-qtwebengine-freeworld-5.15.12-4.fc38.x86_64 from @System requires qt5-qtbase(x86-64) = 5.15.10, but none of the providers can be installed
  - cannot install both qt5-qtbase-5.15.11-3.fc38.x86_64 from updates and qt5-qtbase-5.15.10-5.fc38.x86_64 from @System
  - cannot install the best update candidate for package qt5-qtwebengine-freeworld-5.15.12-4.fc38.x86_64
  - cannot install the best update candidate for package qt5-qtbase-5.15.10-5.fc38.x86_64
 Problem 2: problem with installed package qt5-qtwebengine-freeworld-5.15.12-4.fc38.x86_64
  - package qt5-qtwebengine-freeworld-5.15.12-4.fc38.x86_64 from @System requires qt5-qtbase(x86-64) = 5.15.10, but none of the providers can be installed
  - package qt5-qtwebengine-freeworld-5.15.12-4.fc38.x86_64 from rpmfusion-free-updates requires qt5-qtbase(x86-64) = 5.15.10, but none of the providers can be installed
  - cannot install both qt5-qtbase-5.15.11-3.fc38.x86_64 from updates and qt5-qtbase-5.15.10-5.fc38.x86_64 from @System
  - package keepassxc-2.7.6-3.fc38.x86_64 from updates requires qt5-qtbase(x86-64) = 5.15.11, but none of the providers can be installed
  - cannot install the best update candidate for package keepassxc-2.7.6-1.fc38.x86_64
============================================================================================================================================================================================================================================
 Package                                                   Architecture                                          Version                                                       Repository                                              Size
============================================================================================================================================================================================================================================
Skipping packages with conflicts:
(add '--best --allowerasing' to command line to force their upgrade):
 qt5-qtbase                                                x86_64                                                5.15.11-3.fc38                                                updates                                                3.6 M
Skipping packages with broken dependencies:
 keepassxc                                                 x86_64                                                2.7.6-3.fc38                                                  updates                                                7.3 M

Transaction Summary
============================================================================================================================================================================================================================================
Skip  2 Packages

Nothing to do.
Complete!

Current version keepassxc-2.7.6-1.fc38.x86_64
Try to update keepassxc-2.7.6-3.fc38.x86_64

**Comment by droidmonkey** [comment]
You need to fix your package manager source list. Looks like you aren't pulling from the right places. This has nothing to do with us.
