### ISSUE TITLE
Error while building with visual studio

### ISSUE THREAD

**Issue by hygjob** [keepassxreboot/keepassxc#10023]
## Overview
After making solution files, I got error when build solution about test related project - window os environment.

## Steps to Reproduce
My build environment is window 10(x64 machine) and compiler is visual studio 2022.

I use prebuilt binary as guided Recommended Option in https://github.com/keepassxreboot/keepassxc/wiki/Set-up-Build-Environment-on-Windows 

command as below for making visual studio 2022 solution file.

cmake -DWITH_XC_ALL=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=D:\vcpkg-export\scripts\buildsystems\vcpkg.cmake ..

Run visual studio 2022 and build, I got error about test related project.

## Expected Behavior
build without error 

## Actual Behavior
build with error

## Context
when I build with x64.
linker is specified as below so build error occured.
C:\Program Files (x86)\Windows Kits\10\Lib\10.0.22621.0\um\x86\winscard.lib

so after modified as below, I can build without error
=> C:\Program Files (x86)\Windows Kits\10\Lib\10.0.22621.0\um\x64\winscard.lib

There is something wrong for configuration file - linker specified about winscard.lib.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.6 develop branch - 2023.11.15 current code
Revision:  2.7.6 develop branch - 2023.11.15 current code

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 10(x64)

**Comment by droidmonkey** [comment]
You might need to explicitly specify the architecture you are building for in cmake. We also recommend using Ninja as the build tool, use "cmake -G Ninja"

**Comment by droidmonkey** [comment]
What is the exact error you get? You didn't provide that information. Paste the tail end of the build log.

**Comment by hygjob** [comment]
Link error was produced.

I don't know architecture option using cmake. So it seems to produce x86 link configuration as below.
C:\Program Files (x86)\Windows Kits\10\Lib\10.0.22621.0\um\x86\winscard.lib.

So, when using x64 build, it produces link error. 

I modified configuration linker as below using x64 winscard.lib, it builds well without link error. 
=> C:\Program Files (x86)\Windows Kits\10\Lib\10.0.22621.0\um\x64\winscard.lib

**Comment by droidmonkey** [comment]
Are you using the x64 version of the visual studio tools terminal? Unfortunately I can't help you with the information provided.

**Comment by hygjob** [comment]
OK. Thank you for your concerning.
