### ISSUE TITLE
MacOS : Double-clicking field content in edit window closes the window

### ISSUE THREAD

**Issue by barredespace** [keepassxreboot/keepassxc#10020]
## Overview
When I need to select, say, a user name or a password to edit it, I usually double-click it to replace it with a new one. But  the window closes unexpectedly. 

## Steps to Reproduce
1.  Create a new entry or open an existing one
2.  Double-click the password to select it
3.  The Edit window closes 

## Expected Behavior
The password should appear as selected and the next keystroke should wipe said password and replace it with whatever has been typed.

## Actual Behavior
1. The Edit window closes 
2. The countdown till pasteboard erasure starts
3. Nothing is copied to the pasteboard

## Context
This behavior occurs with every fields except Title and URL
This behavior occurs if settings > security > activate double-click to copy… is unchecked or is checked

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.6
Révision : dd21def

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS  12.7 (Monterey)
pasteboard managing utilities installed (Copy'Em Paste and Paste Queue)

**Comment by droidmonkey** [comment]
I can't replicate this at all on macOS 13 using KeePassXC 2.7.6. Uninstall or disable that clipboard manager and try again. It looks like something is intercepting your double click and injecting an enter and Cmd + C.

**Comment by barredespace** [comment]
I tried quitting both apps but still experience the same behavior.

**Comment by barredespace** [comment]
Hey ! Found the culprit : it was [PopClip](https://www.popclip.app), thanks for putting me on the right track. I'll see if I can disable it only with KeePassXC.
