### ISSUE TITLE
Autotype to terminal window does not work [ubuntu]

### ISSUE THREAD

**Issue by vgheo** [keepassxreboot/keepassxc#10028]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

Having setup an entry for openvpn cli client for usenname/password, autotype to openvpn running in a Gnome Terminal stopped working after some unspecified recent updates.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Setup an entry E with username/password
2. Open Terminal and start openvpn client
3. At the prompt, switch to KeepassXC, choose E > Autotype
4. When Dialog appears "Confirm Auto-Type" then click Yes
5. OBSERVED: nothing is typed in Terminal
EXPECTED:  username/password auto-typed

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.6
Revision: dd21def
Distribution: Snap

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux / Ubuntu 22.04
Desktop Env: Gnome
Windowing System: Wayland

**Comment by droidmonkey** [comment]
Your terminal is likely running as a wayland client and cannot receive Auto-Type.

**Comment by vgheo** [comment]
Confirmed - was running wayland.
Switching to Xorg restores functionality.

Thank you for the reply!
