### ISSUE TITLE
Entries in auto type search should be findable by including the directory name

### ISSUE THREAD

**Issue by julianbuettner** [keepassxreboot/keepassxc#10025]
## Summary
When triggering an auto type, there is a search function. The search term is only matched against entry names, not directories / paths. When knowing the directory name, it would be great if the search term is matched against it as well.

This could maybe implementet by mapping the entry name to the entry path plus entry name and then filter for search matching entries.

## Examples
I have an directory `Alpha` with an entry `Beta`. Then I would like to search for `Al Bet` and find it.

Or when managing many databases/servers which are divided into multiple directories, where each have similiar named entries.
Then searching for `server1 ssh` would be much nicer than (like I currently have to) search for `ssh` and scrolling
through the entries to find the one of directory `server1`.

## Context
N/A

**Comment by droidmonkey** [comment]
Use the search terms to narrow by group: https://keepassxc.org/docs/KeePassXC_UserGuide#_modifiers_and_fields

`g:server1 ssh`
