### ISSUE TITLE
What are these URLs keepass is accessing?

### ISSUE THREAD

**Issue by DeNohvo** [keepassxreboot/keepassxc#10035]
Ran keepassxc msi on VirusTotal and its reporting these URLs, since it should be 100% offline what is the purpose for these?

comodoca.com
ocsp.comodoca.com
ocsp.comodoca.com.cdn.cloudflare.net
ocsp.sectigo.com
ocsp.usertrust.com
sectigo.com
usertrust.com

104.18.14.101
104.18.15.101
8.8.8.8

https://www.virustotal.com/gui/file/14f0a77d934ae25075597fa65ee31c666a524133bf67d459891222ca85de1c2f

**Comment by droidmonkey** [comment]
That would be whatever process is checking the validity of the signing certificate on the installer.

**Comment by JonSnow88** [comment]
so this is to check the signing certificate and the IPs and URLs are not part of the application?

**Comment by DeNohvo** [comment]
> That would be whatever process is checking the validity of the signing certificate on the installer.

so this is to check the signing certificate and the IPs and URLs are not part of the installer or application?

**Comment by droidmonkey** [comment]
Correct, they have nothing to do with KeePassXC itself.
