### ISSUE TITLE
Nested references aren't working - only one reference layer is followed

### ISSUE THREAD

**Issue by petertirrell** [keepassxreboot/keepassxc#1003]
I ran into this behavior when trying out KeepassXC after opening an existing KeePass 2 database.  The functionality is working correctly for me in OG KeePass.

I have 3 entries in KP:
Entry1 with username and password.
Entry2 with username and {password reference to Entry1}
Entry3 with username and {password reference to Entry2}

If I fill the password from Entry 3, I get the raw {REF...} text instead of the actual password ultimately from Entry 1.

## Expected Behavior
I would expect that the password value from Entry 1 (the beginning of the reference chain) is used.

## Current Behavior
I get the actual reference text from Entry 2.

## Possible Solution
Follow any reference links until there are no more reference links?

## Steps to Reproduce (for bugs)
(By the way, I +1'd the bug for improving setting up references in the GUI, this was a bit tedious to reproduce)

I created an initial entry, "Notepad", with a username (testuser) and password (testpassword), with say UUID 1

I created a second entry "Notepad" with a username (testuser2) and password ({REF:P@I:1}) with UUID 2

I created a third entry "Notepad" with a username (testuser3) and password ({REF:P@I:2}).

When using autotype to enter the values into Notepad, selecting Entry 1 gave me testuser/testpassword.

Selecting Entry 2 gave me testuser2/testpassword.

Selecting Entry 3 gave me testuser3/{REF:P@I:1}

## Context
Granted, I could fix the reference so it is only a single layer.  I have a scenario where I have a test login and a dev login, and then ancillary websites that use the dev login credentials.  My passwords rotate, and I tend to keep the two login passwords the same.  So I maintain an entry for each system, but since I keep them the same I have the dev inheriting from the test login entry, and then the ancillary website entries inheriting from the dev login entry.  Maybe it's an edge case, but KeePass supported it?

## Debug Info
KeePassXC - Version 2.2.0
Revision: caa49a8ef3ee28ed478192389b21d61107b3b8e0

Libraries:
- Qt 5.9.0
- libgcrypt 1.7.7

Operating system: Windows 10 (10.0)
CPU architecture: x86_64
Kernel: winnt 10.0.14393

Enabled extensions:
- KeePassHTTP
- Auto-Type
- YubiKey

**Comment by droidmonkey** [comment]
This will greatly complicate dependency checks when entries are deleted.

**Comment by petertirrell** [comment]
That's a fair point.  Does KeePassXC check any referenced fields when deleting an entry?  I just checked the behavior of KeePass and it appears that if I delete Entry 1 (and fully delete it; initially it goes to a recycle bin which maintains the references), Entry 2 and Entry 3 start inserting the `REF` text instead.  So it appears that KeePass isn't maintaining any sort of referential integrity in the referenced fields downstream of a deleted entry.

As for an implementation idea, would it just be a matter of adding a recursive call to `resolvePlaceholder`  within itself to keep checking entries until a "non-reference" entry field was found?

**Comment by droidmonkey** [comment]
There's an open issue for the deletion reference check.

**Comment by TheZ3ro** [comment]
@petertirrell Yes, resolvePlaceholder need to be called until there are no more reference. I don't remember if we already have a warning when deleting Referenced-entry but I think it will be a nice addition, at least with 1-level dependency (the entry is directly referenced)

**Comment by frostasm** [comment]
In version 2.3.0 should work correctly #1078

**Comment by TheZ3ro** [comment]
Version 2.3.0 fixes this, closing
