### ISSUE TITLE
Extension doesn't work on Brave

### ISSUE THREAD

**Issue by sambit-142** [keepassxreboot/keepassxc#10033]
I'm using Ubuntu 22.04.3 LTS. installed brave from the Ubuntu Software (built-in app).
Completed set up of keeppassxc database on my machine and enabled the browsers (Firefox, Google Chrome, Brave). It works fine on Chrome but it's unable to connect to the extension on Brave.

I checked the path "/home/sambit/.config/BraveSoftware/Brave-Browser/NativeMessagingHosts" and found the file "org.keepassxc.keepassxc_browser.json" already present in that folder.

The error I get is: "Cannot connect to KeePassXC. Check that browser integration is enabled in KeePassXC settings."

I'm unaware what else can I do to make it work on Brave.

In terminal I checked which brave and got "/snap/bin/brave" and manually checked the executable inside bin and a folder named "brave" outside bin. but I didn't find the json file "org.keepassxc.keepassxc_browser.json" in there.

Do I have to use any path from that location in tools>settings>browser integration>advanced > use custom browser ... ?

**Comment by droidmonkey** [comment]
Brave as a snap is unable to use native messaging. Please install it using a Deb or ppa method.
