### ISSUE TITLE
Feature request: Minimize KeepassXC to System Tray after unlocking the database

### ISSUE THREAD

**Issue by scooty99** [keepassxreboot/keepassxc#10036]
## Summary
It would be good to have an option in the settings to minimize the app to the system tray (right bottom of the taskbar) after unlocking the database.
This helps to keep the task bar clean.
Currently the only option is to minimize the app but it still shows up in the task bar.

**Comment by droidmonkey** [comment]
Also enable the option to minimize to tray, its at the bottom of the options list

You can also not enable either option and use the keyboard shortcut Ctrl + Shift + M to send the app directly to the tray.
