### ISSUE TITLE
Main window is transparent when connecting remotly to machine without monitor.

### ISSUE THREAD

**Issue by bigretromike** [keepassxreboot/keepassxc#10034]
## Overview
When using computer and living it on while monitor is off (or unplugged) I use remote connection software to work on that pc. When I connect to it (windows11) the keepassxc windows is transparent - when its maximized it obscure the interaction with anything that is under it. 

## Steps to Reproduce
1. turn on computer so it post
2. turn off monitor/plug it off
3. connect to pc using example. rustdesk

## Expected Behavior
being able to see keepassxc

## Actual Behavior
Keepassxc is transparent - the mouse cursor changes were it suppose to be input text, but everything is transparent.

## Context
Similar issue is something with other software that use something (dont know what) to render the window. Currently the only software that has issue like this is keepassxc. Some pc do not post without monitor plugged in GPU. some need dummy monitor plug. Other act this way when monitor is off for long enough time. Probably something with render, gpu and library.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.6, 2.7.5...
Revision: stable

Operating System: Windows 11

**Comment by droidmonkey** [comment]
https://keepassxc.org/docs/KeePassXC_UserGuide#_screenshot_security

**Comment by bigretromike** [comment]
Oh wow, thank you @droidmonkey I didn't know it was a feature. Looks like Im using it even without knowing what it does under the hook. Thank you.
