### ISSUE TITLE
Keepassxc does not start on windows 10

### ISSUE THREAD

**Issue by Staubgeborener** [keepassxreboot/keepassxc#10049]
## Overview
I try to open the latest version of keepassxc on my windows 10 system. The keepassxc window does not open but I can see the process in task manager. Double clicking a keepass database in order to trigger the start of keepassxc does also nothing but creates a process which is visible in task manager. But no keepassxc window at all. Problem occurred with latest windows 10 cummulative update (i think). New installation of keepassxc didn't solve the issue.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. update windows 10 
2. download latest keepassxc 
3. no keepassxc window after start

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.6
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 10

**Comment by droidmonkey** [comment]
Are you accessing the windows 10 box remotely?  https://keepassxc.org/docs/KeePassXC_UserGuide#_screenshot_security

Also try resetting the settings by deleting `%LOCALAPPDATA%/KeePassXC/keepassxc.ini`

**Comment by Staubgeborener** [comment]
No i am using keepassxc local. No remote connections a t all, just sitting in front of my computer.

Still same issue after deleting keepassxc.ini - also there is no new keepassxc.ini file which is created by keepassxc if i try to start the program.

**Comment by droidmonkey** [comment]
Recommend reinstalling the msvc redistribution package. https://aka.ms/vs/17/release/vc_redist.x64.exe

**Comment by Staubgeborener** [comment]
This works, thanks! Before closing this issue: may you can explain the exact problem and behavior?

**Comment by droidmonkey** [comment]
Have no idea besides a corrupted install.

**Comment by julienbardi** [comment]
Solution works also for similar problem with KeePassXC 2.7.9 on Windows 11 Pro 23H2 👍

**Comment by gitname** [comment]
The same solution also works with KeePassXC 2.7.9 on Windows 11 Enterprise 22H2.

**Comment by evolverine** [comment]
Also worked for KeePass 2.7.9 on Windows 11 Home 23.H2

**Comment by marvinjuette** [comment]
Also worked for 2.7.9 on Windows 10 Pro 22H2

**Comment by rainpaper-bs** [comment]
Also worked for 2.7.9 on Windows Server 2019

**Comment by redpay** [comment]
Same problem with 2.7.9, after Windows 10 update, solution worked, thank you.

**Comment by zykure** [comment]
Same here with 2.7.9 on Windows 11 Pro 23H2 - reinstalling msvc from the link posted above fixed it.

It was pretty confusing that the application wasn't doing anything at all - no crash, no errors, no output in a terminal window, nothing at all. Glad I found this issue report though!

**Comment by ghost** [comment]
Confirmed working fix w/ v2.7.9 on W11 Pro for Workstations 23H2

**Comment by paskozdilar** [comment]
Solution worked with v2.7.9 on Windows 10 21H2 IIoT.

To prevent all future issues with vcredist libs, I recommend https://github.com/abbodi1406/vcredist

**Comment by Jedrzej94** [comment]
Just got here to say, that I freshly reinstalled my Windows 11 to 24H2, and also couldn't open the app without downloading redist libs. KeePassXC at version of v2.7.9

**Comment by itsdeborahm** [comment]
It also worked for me right now! On March 20, 2025. Thanks!!!

**Comment by cstrickjacke** [comment]
Just worked on Win11 now for me too.

**Comment by jfkmsp** [comment]
It also worked for me right now! 06-09-2025
