### ISSUE TITLE
browser extension: key exchange failed after firefox update, due to the AppArmor profile being overwritten

### ISSUE THREAD

**Issue by luk-brue** [keepassxreboot/keepassxc#10040]
## Overview

I updated firefox to version 120 and since then, the connection to KeePassXC has stopped working.

## Steps to Reproduce
1. Have an Ubuntu 23.04 machine
2. Uninstall the pre installed snap firefox
1. Install firefox from mozilla PPA, and add the PPA, and pin the PPA to give it priority over transitional firefox from Canonical
2.  get KeePassXC to work, with some steps I forgot until now (but it was a pain).
3. wait half a year, then install updates with `sudo apt upgrade` - this should update firefox from mozilla PPA
4. During installation, when asked whether to overwrite custom config file (which probably old me created earlier to make KeePassXC connection work, I am assuming): be stupid and say yes
5. Try to use the browser extension

## Expected Behavior

I expected KeePassXC to work with firefox even after the update.

## Actual Behavior

I get uninformative "Key exchange failed" errors. So I try to look deeper: This is the JavaScript Console Output for: when I open the extension and click the reload button:

```
KeePassXC-Browser: Connecting to native messaging host org.keepassxc.keepassxc_browser [client.js:363:13]
[Error ] KeePassXC-Browser - Failed to connect: Unknown error [global.js:145:13]
[Error client.js:382] KeePassXC-Browser - No content script available for this tab. [global.js:145:13]
[Error keepass.js:811] KeePassXC-Browser - 9: Schlüsselaustausch war nicht erfolgreich. [global.js:145:13]
[Error keepass.js:421] KeePassXC-Browser - No content script available for this tab. [global.js:145:13]
```

I tried following the Troubleshooting Guide for the extension. 

- [x] checked the `.json` file in native messaging config folder (in my case, I had to set it manually to `~/.mozilla/native-messaging-hosts`
- [x] tried to find `keepassxc-proxy` process and start it manually

This is where trouble starts: `keepassxc-proxy` is not running. I checked this with `ps -ef | grep keepass`, which returned only this which says that KeePassXC is running but not the proxy. 

```shell
$ ps -ef | grep keepass

7191    1774  0 22:58 ?        00:00:04 /usr/bin/keepassxc
8499    4330  0 23:28 pts/0    00:00:00 grep --color=auto keepass
```
I tried to start `keepassxc-proxy` manually and check if it is running but no success.

I go to the next step, use `strace` to listen to where firefox tries to start `keepassxc-proxy`. This is the output of clicking the reload button in the extension once:

```shell
$ sudo strace -f -p $(pgrep firefox) 2>&1 | grep keepass

[pid  3974] openat(AT_FDCWD, "/home/elbe/.mozilla/native-messaging-hosts/org.keepassxc.keepassxc_browser.json", O_RDONLY <unfinished ...>
[pid  3974] newfstatat(AT_FDCWD, "/usr/bin/keepassxc-proxy",  <unfinished ...>
[pid  3974] newfstatat(AT_FDCWD, "/usr/bin/keepassxc-proxy",  <unfinished ...>
[pid  3974] newfstatat(AT_FDCWD, "/usr/bin/keepassxc-proxy",  <unfinished ...>
[pid  3974] newfstatat(AT_FDCWD, "/usr/bin/keepassxc-proxy",  <unfinished ...>
[pid  3974] newfstatat(AT_FDCWD, "/usr/bin/keepassxc-proxy",  <unfinished ...>
[pid  4363] execve("/usr/bin/keepassxc-proxy", ["/usr/bin/keepassxc-proxy", "/home/elbe/.mozilla/native-messa"..., "keepassxc-browser@keepassxc.org"], 0x7f81d4264400 /* 69 vars */) = -1 EACCES (Keine Berechtigung)
```
Pay attention to the last line. There seems to be an access permissions issue ("Keine Berechtigung" means "Permission Denied" in English). As a guess, I looked up permissions for `keepassxc-proxy`, it only belongs to `root`. Is this normal?

```shell
$ ls -l /usr/bin/keepassxc-proxy
-rwxr-xr-x 1 root root 35208 Aug 16 01:11 /usr/bin/keepassxc-proxy
```
I do not know what that means. This is as far as I have come without being a programmer.

## Context

KeePassXC - Version 2.7.6
Revision: dd21def

OS: Ubuntu 23.04
CPU: x86_64
Kernel: linux 6.2.0-36-generic

**Comment by droidmonkey** [comment]
You need to disable or modify the apparmor profile being applied to Firefox. Read the extension troubleshooting guide for more information. 

https://github.com/keepassxreboot/keepassxc-browser/wiki/Troubleshooting-guide#6-apparmor-with-ubuntu

**Comment by luk-brue** [comment]
Thanks, I applied the suggested changes to my `/etc/apparmor.d/usr.bin.firefox` AppArmor profile. I am still experiencing same issues as before, even after reboot.

```shell
elbe@elbe-laptop:~$ sudo strace -f -p $(pgrep firefox) 2>&1 | grep keepass
[sudo] Passwort für elbe: 
[pid  3824] openat(AT_FDCWD, "/home/elbe/.mozilla/native-messaging-hosts/org.keepassxc.keepassxc_browser.json", O_RDONLY) = 120
[pid  3824] newfstatat(AT_FDCWD, "/usr/bin/keepassxc-proxy",  <unfinished ...>
[pid  3824] newfstatat(AT_FDCWD, "/usr/bin/keepassxc-proxy", {st_mode=S_IFREG|0755, st_size=35208, ...}, 0) = 0
[pid  3824] newfstatat(AT_FDCWD, "/usr/bin/keepassxc-proxy",  <unfinished ...>
[pid  3824] newfstatat(AT_FDCWD, "/usr/bin/keepassxc-proxy",  <unfinished ...>
[pid  3824] newfstatat(AT_FDCWD, "/usr/bin/keepassxc-proxy",  <unfinished ...>
[pid  4360] execve("/usr/bin/keepassxc-proxy", ["/usr/bin/keepassxc-proxy", "/home/elbe/.mozilla/native-messa"..., "keepassxc-browser@keepassxc.org"], 0x7f6f70468a00 /* 69 vars */) = -1 EACCES (Keine Berechtigung)
```

**Comment by droidmonkey** [comment]
Might be firejail?

https://github.com/keepassxreboot/keepassxc-browser/wiki/Troubleshooting-guide#linux-firejail

**Comment by luk-brue** [comment]
After disabling the AppArmor profile for firefox, everything is working! Thanks for bringing me on the right track. `sudo aa-disable /etc/apparmor.d/usr.bin.firefox`. Now I have to find out why the suggested changes in Troubleshooting are not working. Is there a specific place where I should put them in the profile? I just appended them at the end, inside the inner set of curly braces.

**Comment by luk-brue** [comment]
Ok, I figured it out. I had to place the additional rules in the outer set of curly braces. Finally it is working. Thank you so much.
