### ISSUE TITLE
Windows 23H2 cannnot open KeepassXC databases

### ISSUE THREAD

**Issue by LarsWies** [keepassxreboot/keepassxc#10047]
Hello,

is there any known problem about KeepassXC in relation to the Windows 23H2 Update? I heart that databases from KeepassXC cannot be openend on the new update. I'm thinking about updating my Windows to this version, but i need the software. So if you know anything about ist, i would be happy , if you would inform me.

Thanks a lot!!

**Comment by droidmonkey** [comment]
There is zero relation between windows updates and keepassxc. Update away.
