### ISSUE TITLE
Bypass of windows hello auth

### ISSUE THREAD

**Issue by neftalito** [keepassxreboot/keepassxc#10042]
## Overview
You can bypass the "double" authentication using windows hello

## Steps to Reproduce
1.  Enable quick unlock
2. Close the database
3. Submit your password
4. When the windows hello popup appears press escape
5. The database will be loaded with an error message saying that quick unlock is not enabled and that windows hello was cancelled or failed

## Expected Behavior
The database shouldn't be opened

## Actual Behavior
The database is opened

## Context
Windows 10, latest version (2.7.6), portable.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows/Linux/macOS
Desktop Env: Gnome/KDE/XFCE/Mate/Cinnamon
Windowing System: X11/Wayland

**Comment by droidmonkey** [comment]
> an error message saying that **quick unlock is not enabled** and that windows hello was cancelled or failed

**Comment by neftalito** [comment]
> > an error message saying that **quick unlock is not enabled** and that windows hello was cancelled or failed

Yeah but it *is* enabled

**Comment by droidmonkey** [comment]
Sigh, as a feature it is (which is why you see the windows hello dialog), but not for your database session when you cancel the dialog. It has not been enabled for use.

**Comment by JohnLGalt** [comment]
Seems like this pops up every month. Could making Quick Unlock via Win Hello be disabled on install, forcing the user to enable it with appropriate reading / messages, to get across more clearly what the feature actually does?

Yes, I know, people still won't read, but at least they have to manually enable it themselves first.

**Comment by droidmonkey** [comment]
That isn't a solution to the problem, the issues will change to "why doesn't windows hello work?"

The issue here is not that windows hello is appearing. It's that people think canceling it is by passing security when it's not

**Comment by JohnLGalt** [comment]
Well, if you say so. But I'd think it is a lot easier to point to a wiki article on how to enable it than to have a back and forth trying to get people to understand that it is not bypassing security for those who don't even use it because they cancel it lol.

j/s
