### ISSUE TITLE
Keepassxc-browser loosing connection when opening more databases

### ISSUE THREAD

**Issue by Massimo-B** [keepassxreboot/keepassxc#10046]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

When opening multiple databases, keepassxc-browser looses connection to its keepassxc database.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Open Keepassxc with the default database
2. Open browser with keeepassxc-browser, connected
3. open another database

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

keepassxc-browser should stay connected to its database which is still open and unlocked

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

The connection is lost and keepassxc-browser tries to use the new database which has no authenticated connection.

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.6

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: XFCE
Windowing System: X11

**Comment by Massimo-B** [comment]
Not sure if this is an issue of keepassxc or keepassxc-browser, however the ticket was already filed in
https://github.com/keepassxreboot/keepassxc-browser/issues/1659
so you might close this as duplicate...

**Comment by droidmonkey** [comment]
Use the setting in the browser settings tab to enable searching in all open databases. It is also possible that you are using a copy of the same database and need to reset the database uuid, do that in database settings,  browser tab. It is also possible you have duplicate named connections to the browser extension.
