### ISSUE TITLE
KeePassXC-2.7.6-x86_64.AppImage-do not open the links to the browser

### ISSUE THREAD

**Issue by masac** [keepassxreboot/keepassxc#10043]
KeePassXC-2.7.6-x86_64.AppImage -do not open the links to the browser.

Browser: Brave-[ 1.60.118 Chromium: 119.0.6045.163]

KeePassXC-2.7.6-x86_64.AppImage

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux mint 21.2
Desktop Env: Mate
Windowing System: X11/Wayland

**Comment by droidmonkey** [comment]
Duplicate issue. Recommend switching to flatpak
