### ISSUE TITLE
Automatic import from Firefox

### ISSUE THREAD

**Issue by wellloaded** [keepassxreboot/keepassxc#10053]
I did my googling before posting here, I can only find very old pages/messages related to this topic and they don't apply any more as far as I can tell.

I appreciate I can export to CSV from firefox and I can also import from CSV in KeePassXC however I was not successful setting up the right fields/columns mine despite. So two points really:

- Is it worthy having an import from Firefox (perhaps direct providing Firefox account and password) without having to relay on CSV
- The CSV import I personally find a bit fiddly especially setting the column names. Could this be revised? I'm not also clear what are the mandatory columns.

Thanks

**Comment by droidmonkey** [comment]
No we won't do a direct import from Firefox or any other browser. That just isn't a thing, we'd have to basically hack into the underlying password store file. 

Please explain more on how you couldn't get csv import to work for you. We don't have any mandatory fields.
