### ISSUE TITLE
Always defaults to light theme at startup

### ISSUE THREAD

**Issue by xplosionmind** [keepassxreboot/keepassxc#10058]
## Overview

I set KeePassXC to automatically launch at login, but it always opens with the light theme, even if the system theme is dark and the settings are set to follow the system theme. Indeed, if I close and reopen the app it has the right theme…

## Steps to Reproduce

1. Set the app to open at startup via GNOME Tweaks
2. Startup the device
3. KeePassXC opens in light theme

## Expected Behavior

Start up following the system theme

## Actual Behavior

Always opening with light theme at startup

## Context

KeePassXC - Version 2.7.6
Revision: dd21def

Qt 5.15.11
Debugging mode is disabled.

Operating system: Fedora Linux 39 (Workstation Edition)
CPU architecture: x86_64
Kernel: linux 6.5.12-300.fc39.x86_64

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.19.3

Operating System: Fedora 39, Linux 6.5.12-300.fc39.x86_64
Desktop Env: GNOME 45.1
Windowing System: Wayland

**Comment by phoerious** [comment]
This is almost certainly an issue with your system. Perhaps KeePassXC is started too early or the Gnome settings daemon is started too late.

**Comment by xplosionmind** [comment]
Thanks for the help, @phoerious! Do you have any ideas how I can debug this? Links to explanations are fine too.

**Comment by droidmonkey** [comment]
Create a short script that adds a delay (sleep 5s) before starting keepassxc, add that to the startup sequence.

**Comment by xplosionmind** [comment]
> Create a short script that adds a delay (sleep 5s) before starting keepassxc

Thanks for the suggestion, @droidmonkey! Actually, there is no need: there is the possibility of adding the `X-GNOME-Autostart-Delay` parameter to `$HOME/.config/autostart/org.keepassxc.KeePassXC.desktop`. I set it to `100`.

Still opening in light theme.

**Comment by droidmonkey** [comment]
Don't really have a recommendation besides a longer delay or just set the theme manually.

**Comment by droidmonkey** [comment]
I actually cannot replicate the problem, I have Fedora 39, Gnome 45.1, Wayland running in VirtualBox. Autostart with both the Flatpak and native installation work fine, no theming problems at all. 

Just to make sure I am covering all bases, ensure you actually have Dark Style enabled in Gnome:

![image](https://github.com/keepassxreboot/keepassxc/assets/2809491/011527a0-7b7c-4dcf-9a01-2aa0ecbc270e)

Could it be that you have two different versions of KeePassXC installed? One flatpak (or snap) and the other native? You could have one set to automatic and the other set to light theme (the autostart one).

**Comment by xplosionmind** [comment]
Thanks for your feedback @droidmonkey, I have updates. It seems that the problem is broader, and it does not concern only startup.

Now also the close button does not appear at startup:

![Screenshot from 2023-12-03 16-32-17](https://github.com/keepassxreboot/keepassxc/assets/42862428/4eb4619c-f62f-4bc0-8b34-8c0f2fd291e0)

Even after restarting the app, there is a weird problem with the window’s shadow:

![Screenshot from 2023-12-03 16-43-55](https://github.com/keepassxreboot/keepassxc/assets/42862428/cc3b6a32-f7c1-4645-ae03-d6d9ee9d0d71)

**Comment by droidmonkey** [comment]
The title bar and shadow effects are not in our control (we certainly don't request any special effects or buttons). That looks like a problem with Gnome directly. Make sure you don't have any plugins/extensions installed that would break the behavior of windows.

**Comment by xplosionmind** [comment]
Thank you for your explanation. I needed help for debugging this, but I figured it is a windowing problem to be reported in some other repository.

**Comment by muety** [comment]
Still facing this problem, any further ideas? 😃

**Comment by dani162** [comment]
`X-GNOME-Autostart-Delay` seems only to work in forked gnome version used by ubuntu, see https://discourse.gnome.org/t/is-there-a-way-to-delay-startup-of-certain-autostart-apps-in-gnome/29901

Manually adding a sleep inside Exec of the auto-start .desktop entry (on my system located at `~/.config/autostart/org.keepassxc.KeePassXC.desktop`) fixes the problem for me.
```ini
[Desktop Entry]
Name=KeePassXC
GenericName=Password Manager
# Delay autostart for detecting theme correctly 
# and valid window decerations (with close button)
Exec=bash -c "sleep 2 && keepassxc"
# Exec=keepassxc
TryExec=keepassxc
Icon=keepassxc
StartupWMClass=keepassxc
StartupNotify=true
Terminal=false
Type=Application
Version=1.0
Categories=Utility;Security;Qt;
MimeType=application/x-keepass2;
# Probably deprecated and does nothing
X-GNOME-Autostart-enabled=true
# Seems only work in ubuntu gnome fork
# https://discourse.gnome.org/t/is-there-a-way-to-delay-startup-of-certain-autostart-apps-in-gnome/29901
X-GNOME-Autostart-Delay=2
X-KDE-autostart-after=panel
X-LXQt-Need-Tray=true
```

Also i removed the write permissions of the desktop file, to prevent KeePassXC overwrite the desktop file each time i save KeePassXC settings.
```bash
chmod 444 ~/.config/autostart/org.keepassxc.KeePassXC.desktop
```
