### ISSUE TITLE
Swiping with finger does not work

### ISSUE THREAD

**Issue by vesajuvonenx** [keepassxreboot/keepassxc#10052]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
Windows 10 latest patches. MS Surface pro 7 touch screen device
Swiping with finger to scroll up or down the items does not work on database tree or item panel.
Very error prone to try to hit scrolling bar to scroll since it is very small and narrow.
9/10 times it will end up moving random item or group to new, wrong place/group and that is even not undoable action.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. 
2. 
3. 

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Scrolling should understand finger action on touch screen

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
explained in overview

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 10, touch screen device Surface pro 7

**Comment by droidmonkey** [comment]
This would be a qt concern, we have no special detection of mouse versus touch. Our app is not designed for touch as well, if it works great, others we aren't going to invest time fixing touch problems.
