### ISSUE TITLE
Can't input Chinese in tag input box

### ISSUE THREAD

**Issue by srdr0p** [keepassxreboot/keepassxc#10056]
## Steps to Reproduce
1.  Open a password edit window, place cursor to Tags input box
2. Switch IME to any Chinese or Japanese
3. Can't input Chinese text in Tags

## Expected Behavior
Generated a Chinese tag.

## Actual Behavior
[NOTE]: Not thing happened.

## Context
I can use Ctrl+V in Tags to input a Chinese tag.
English tags is nothing wrong.

KeePassXC - Version 2.7.6
Revision: dd21def

Qt 5.15.10
Debugging mode is disabled.

Operating system: Windows 10 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.19045

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey

Cryptographic libraries:
- Botan 2.19.3

**Comment by droidmonkey** [comment]
Duplicate issue report.

**Comment by droidmonkey** [comment]
https://github.com/keepassxreboot/keepassxc/issues/7488
