### ISSUE TITLE
[GNOME] Auto-type use Qwerty layout if on startup session

### ISSUE THREAD

**Issue by OlivierMary** [keepassxreboot/keepassxc#1005]
If I put keepassxc on startup of gnome the autotype (CTRL+ALT+A) is on qwerty layout.
If I stop keepassxc after that, restart it take my layout (fr/azerty)

## Expected Behavior
If on startup of gnome keepassxc take the good layout

## Current Behavior
Keepassxc take qwerty layout (only if lunch on startup)

## Possible Solution
Stop it, and restart it to take good layout. But not a solution.

## Steps to Reproduce (for bugs)
1. Put keepassxc on startup of gnome (with gnome-tweak-tool)
2. Logout Login
3. Test auto type

## Context
I just try to start keepassxc on start (with good config).

## Debug Info
KeePassXC - 2.2.0-2

Operating system: Archlinux
CPU architecture: 64
Kernel: 4.12.13-1

Enabled extensions:
- None

**Comment by droidmonkey** [comment]
This is likely because yiur keyboard settings are being established after keepassxc runs. Can you set a dependency or delay the start of xc somehow?

**Comment by jeroen7s** [comment]
create bash script that adds sleep 1 before launching keepassxc, and that that as startup? should be enough

**Comment by OlivierMary** [comment]
@droidmonkey Yes, I will try Gnome Xorg / Gnome Wayland to check, I know there are some problem with wayland.

@jeroen7s Yes I can but 1 sec is too few, when I launch it manually sometimes 15/20sec after login that not working

**Comment by OlivierMary** [comment]
Problem is only on gnome wayland.
