### ISSUE TITLE
"Credential is excluded" error when trying to register passkey on WordPress.com

### ISSUE THREAD

**Issue by dhasilva** [keepassxreboot/keepassxc#10050]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
When trying the new passkey feature to register a passkey on WordPress.com, a popup with the message "Error! Credential is excluded." is shown.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Create an account on https://wordpress.com
2. Go to https://wordpress.com/me/security/two-step
3. Add two-step verification
4. Now there will be a Security key field. Give it a name and click on `Register Key`
5. Error

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
I expected it to work much the same as it does with https://webauthn.io/

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
It fails with the error message:

![2023-11-22_19-33-40](https://github.com/keepassxreboot/keepassxc/assets/8486249/6e10f6e6-593d-4976-a8e5-935a80599f27)

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.8.0-snapshot
Build Type: Snapshot
Revision: a3717c7

Qt 5.15.3
Debugging mode is disabled.

Operating system: Pop!_OS 22.04 LTS
CPU architecture: x86_64
Kernel: linux 6.4.6-76060406-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- Passkeys
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.19.1

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: None (window manager, Herbstluftwm)
Windowing System: X11

**Comment by varjolintu** [comment]
This is possibly because `residentKey` is required (I'll verify this). There was another issue where the same error message is displayed in that situation. We need to add a separate error message for this (or add support for Resident Keys).

**Comment by droidmonkey** [comment]
Yes a clearer error message would be best. Technically we shouldn't be able to handle resident keys, but it would be interesting to see if that matters.

**Comment by varjolintu** [comment]
This is what WordPress returns when trying to register a security key:
```
{
    "challenge": "5VZDU4-kZ-Me1CGcJsKRT9jSMugAU01fozOfgIms023VGDmee_ndR01mzq-wAFkc7-_-tJQfCbSC9D........",
    "pubKeyCredParams": [
        {
            "type": "public-key",
            "alg": -7
        },
        {
            "type": "public-key",
            "alg": -257
        }
    ],
    "rp": {
        "name": "WordPress.com",
        "id": "wordpress.com"
    },
    "timeout": 60000,
    "excludeCredentials": [],
    "user": {
        "displayName": "redacted",
        "id": "NDA0NTAzMjd",
        "name": "redacted"
    }
}
```

They are not passing any values for `attestation` or `authenticatorSelection`, which is why the register is denied. In this case we could fallback to some default values, like `attestation: none` and `authenticatorSelection.userVerification: preferred`, but that could possibly create a key that's not compatible with the server.

For the error messages, there's one error message missing from the extension side, and the Passkey error numbers are not matching. I'm fixing that, plus adding a new error for Resident Key.

**Comment by droidmonkey** [comment]
I'm in favor of falling back to reasonable defaults if the request isn't fully formed. We could show a debug warning in that case if we need to troubleshoot in the future.

**Comment by varjolintu** [comment]
> I'm in favor of falling back to reasonable defaults if the request isn't fully formed. We could show a debug warning in that case if we need to troubleshoot in the future.

I'll just need to test if the defaults even work with Wordpress.

**Comment by droidmonkey** [comment]
I suppose if the server doesn't specify then they would (should) accept any value.

**Comment by varjolintu** [comment]
@dhasilva This problem is solved when the next extension version is released. I also noticed the Wordpress site does not detect login fields properly, so gotta fix that too before I make a release.

**Comment by dhasilva** [comment]
Thank you @varjolintu!

**Comment by varjolintu** [comment]
Fixed from the KeePassXC-Browser side: https://github.com/keepassxreboot/keepassxc-browser/pull/2038
