### ISSUE TITLE
Inline message widget should hide after a set period of time

### ISSUE THREAD

**Issue by droidmonkey** [keepassxreboot/keepassxc#1006]
## Expected Behavior

The inline message widget would automatically hide after being shown for XX seconds.

## Current Behavior

The inline message widget stays visible until the user clicks the close button. This can result in a persistent error being shown even after the conditions are cleared up.

## Possible Solution

Add a timer to the message widget to auto-hide the widget. Function calls to show the widget can override the timer if needed.

**Comment by frostasm** [comment]
@droidmonkey I will try to solve this issue, if you don't mind :)

**Comment by droidmonkey** [comment]
sure would love the help!
