### ISSUE TITLE
we recommend that the client view a single password only after the database master password or touch id authentication.

### ISSUE THREAD

**Issue by D0ngs3c** [keepassxreboot/keepassxc#10065]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )

we recommend that the client view a single password only after the database master password or touch id authentication.

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )

**Comment by droidmonkey** [comment]
That is not how keepass database work and we won't be implementing that feature
