### ISSUE TITLE
How to hide the kdbx file?

### ISSUE THREAD

**Issue by goldenbull** [keepassxreboot/keepassxc#10066]
## Summary

In some cases, we need to hide the kdbx file so that other people/gov/policeman will not know the existance of the kdbx file.

Simply renaming the file does not help because the magic numbers in file header

```C++
KeePass2.h
    constexpr quint32 SIGNATURE_1 = 0x9AA2D903;
    constexpr quint32 SIGNATURE_2 = 0xB54BFB67;
```

Veracrypt is a possible solution, especially the hidden volume and the "plausible deniability" method. The only disadvantage is the dependency of veracrypt and operation complexity.

Is it possible that keepass provides some obscurity ability? At least, is it possible to get rid of the magic numbers?

Here is a related discussion:

https://sourceforge.net/p/keepass/discussion/329220/thread/b96d8693/

**Comment by droidmonkey** [comment]
No, and you shouldn't bother trying. Security through obscurity is not how we do business.
