### ISSUE TITLE
After auto complete (Ctrl+Shift+V) KeePaassXC window are moved to window when autotype is made

### ISSUE THREAD

**Issue by ghost** [keepassxreboot/keepassxc#10078]
## Overview
[NOTE]: 
After KeePassXC made auto-type using Ctrl+Shift+V, KPXC window are moved to monitor/virtual desktop when autotype is made.

## Steps to Reproduce
[NOTE]:
1. Create few virtual desktops, and connect additional monitor or only use one with few virtual desktops.
2. Open KeePassXC database on first virtual desktop, and a application or website on another virtual desktop or additional monitor.
3. Type in fields for You want to make auto type, get back to KPXC window, select an entry You want to by filled with, and use Ctrl+Shift+V or PPM make autotype.

## Expected Behavior
[NOTE]: Entry should by filled, but KPXC main window should stay on original virtual desktop.

## Actual Behavior
[NOTE]: Entry is filled but KPXC main window are moved to virtual desktop or monitor where application window to we provide username/password are located.

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.6
Revision: dd21def
Distribution: Flatpak

[NOTE]: # ( Pick choices based on your environment )
KeePassXC is used on Fedora Linux 39 with X11. I use additional monitor to my notebook, and on notebook I have ten virtual desktops.
Operating System: Fedora Linux 39 Workstation
Desktop Env: Gnome 45.2
Windowing System: X11, but the same error probably also occurs on Wayland too.

**Comment by droidmonkey** [comment]
Hmmm we don't have any code that moves to another desktop window. That's actually a bug currently open. Make sure you don't have settings enabled in gnome that automatically move active windows to the current desktop or similar.

**Comment by ghost** [comment]
> Hmmm we don't have any code that moves to another desktop window. That's actually a bug currently open. Make sure you don't have settings enabled in gnome that automatically move active windows to the current desktop or similar.

I've tried reproduce this bug on KPXC installed from Fedora repo by dnf, and I don't have this problem.

So its a flatpak issue.

**Comment by droidmonkey** [comment]
Makes sense, should open a bug report with the desktop portal. 

https://github.com/flatpak/xdg-desktop-portal
