### ISSUE TITLE
Correct password not recognized any longer

### ISSUE THREAD

**Issue by Passnat** [keepassxreboot/keepassxc#10074]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
When entering my main password, I've got the same message as it were wrong. So, I can't open Kee pAss XC. I was using 2.6 version. I've update to 2.7.6, but the bug remains.
Any idea ?
Thanks
Passnat

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. 
2. 
3. 

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows/Linux/macOS
Desktop Env: Gnome/KDE/XFCE/Mate/Cinnamon
Windowing System: X11/Wayland

**Comment by droidmonkey** [comment]
You are not entering the correct password. You can also downgrade to 2.6.6 again, but that won't make a difference. I can assure you that databases work fine between 2.6.6 and 2.7.6.

**Comment by Passnat** [comment]
Hi! I've got an older version of my database on another external disk (with the same password). It opens properly. This is why I don't understand what happens. I  checked the password several times and I'm certain it' s correct.

**Comment by droidmonkey** [comment]
It's good you have a backup. Generally speaking keepass databases don't just stop working. By chance, are you using Google drive on windows?

**Comment by Passnat** [comment]
No, I don't use google drive. That's really weird. I've been using Keepass for years without any trouble.  The message says that HMAC may be invalid. I don't understand what it means.
Could I have been hacked ?

**Comment by droidmonkey** [comment]
Either you changed your database password or the file you are opening is corrupted some how. Corruption is incredibly unlikely.

**Comment by Passnat** [comment]
Hi!
As I didn't change the password, I 'd say the file is corrupted. Do you happen to what can corrupt a file ?

⁣Télécharger BlueMail pour Android ​

Le 3 déc. 2023, 20:25, à 20:25, Jonathan White ***@***.***> a écrit:

**Comment by droidmonkey** [comment]
Almost certainly has to do with your storage mechanism, are you using a USB thumbdrive?

**Comment by Passnat** [comment]
Yes. So, that could explain the problem.

⁣Télécharger BlueMail pour Android ​

Le 4 déc. 2023, 15:58, à 15:58, Jonathan White ***@***.***> a écrit:
