### ISSUE TITLE
Config option `Browser.Enabled = true` has no effect on first startup (or subsequent) when generated & linked by Nix

### ISSUE THREAD

**Issue by spikespaz** [keepassxreboot/keepassxc#10076]
**Edit:** This issue was originally opened as a feature request to solve Y of problem X. As it is apparent that this is an X/Y problem (on my part), I have updated the title. The message that follows may be misleading, so make sure to read the discussion for a clear understanding of the real problem at hand.

## Summary
Basically, in `~/.config/keepassxc/keepassxc.ini` we have 

```ini
[KeeShare]
Active="<?xml version=\"1.0\"?><KeeShare><Active/></KeeShare>\n"
Own="<?xml version=\"1.0\"?><KeeShare><PrivateKey>REDACTED</PrivateKey><PublicKey><Signer>jacob</Signer><Key>REDACTED</Key></PublicKey></KeeShare>\n"
```

I haven't looked into what's going on with the XML, I assume it's verbose configuration for the KeeShare service.

I don't really know why a boolean seems to be represented as XML for `Active`, perhaps this can be reduced to true/false? I do not know what other configuration can be there.

Regardless, we may need `KeeShare.ActiveConfigFile` and `KeeShare.OwnConfigFile` if both are sensitive. Perhaps we only need one. Or even `KeeShare.PrivateKeyFile` would work.

I need a way to store secrets in a separate file, and load them at runtime (as a systemd service with a path to my user's key "remembered").

## Examples

I currently have a Home Manager (NixOS) module that looks like this:

<spoiler><details>
<summary>
You don't need to read this code, it just generates <tt>~/.config/keepassxc/keepassxc.ini</tt>.
</summary>

```nix
# TODO maybe?
# <https://gist.github.com/dAnjou/b99f55de34b90246f381e71e3c8f9262>
# <https://github.com/keepassxreboot/keepassxc/issues/613>
{ config, lib, pkgs, ... }:
let
  inherit (lib) types;

  service = config.services.keepassxc;
  program = config.programs.keepassxc;

  iniFormat = pkgs.formats.ini { };
in {
  options = {
    services.keepassxc = {
      enable = lib.mkEnableOption "KeePassXC Service";

      package = lib.mkOption {
        type = types.package;
        description = lib.mdDoc ''
          Uses the program configuration's package by default.
        '';
        defaultText = lib.mdDoc ''
          {option}`config.programs.keepassxc.package`
        '';
      };
    };

    programs.keepassxc = {
      enable = lib.mkEnableOption (lib.mdDoc ''
        Whether to install KeePassXC.
      '');

      package = lib.mkPackageOption pkgs "keepassxc" { };

      settings = lib.mkOption {
        type = iniFormat.type;
        default = { };
        description = lib.mdDoc ''
          Settings to write in INI format to {file}`~/.config/keepassxc/keepassxc.ini`.

          Unfortunately, it is currently impossible to set `KeeShare.Active`
          and `KeeShare.Own` (properly) because this PRIVATE key would be world
          readable in the Nix store.
        '';
      };
    };
  };

  config = lib.mkMerge [
    (lib.mkIf program.enable { home.packages = [ program.package ]; })

    { services.keepassxc.package = lib.mkDefault program.package; }

    (lib.mkIf (program.enable && program.settings != { }) {
      xdg.configFile."keepassxc/keepassxc.ini".source =
        iniFormat.generate "keepassxc.ini" program.settings;
    })

    (lib.mkIf service.enable {
      systemd.user.services.keepassxc = {
        Unit = {
          Description = program.package.meta.description;
          After = [ "graphical-session.target" ];
        };
        Service = {
          Type = "simple";
          KillMode = "process";
          ExecStart = lib.getExe program.package;
          Restart = "on-failure";
          RestartSec = 5;
        };
        Install = { WantedBy = [ "graphical-session.target" ]; };
      };
    })
  ];
}
```
</details></spoiler>

And my declarative (managed) configuration of these options looks like this:

```nix
keepassxc = {
  imports = [ self.homeManagerModules.keepassxc ];

  programs.keepassxc = {
    enable = true;

    # KeePassXC doesn't play nice with
    # custom Qt themes, and default looks great.
    package = (pkgs.symlinkJoin {
      inherit (pkgs.keepassxc) name pname version meta;
      paths = [ pkgs.keepassxc ];
      nativeBuildInputs = [ pkgs.makeWrapper ];
      postBuild = ''
        wrapProgram $out/bin/keepassxc \
          --set QT_QPA_PLATFORMTHEME ""
      '';
    });

    settings = {
      General = {
        ConfigVersion = 2;
        UseAtomicSaves = true;
      };
      Browser = {
        Enabled = true;
        SearchInAllDatabases = true;
      };
      FdoSecrets = { Enabled = true; };
      GUI = {
        ApplicationTheme = "dark";
        ColorPasswords = true;
        MinimizeOnClose = true;
        MinimizeOnStartup = true;
        MinimizeToTray = true;
        MonospaceNotes = true;
        ShowTrayIcon = true;
        TrayIconAppearance = "monochrome-light";
      };
      PasswordGenerator = {
        AdditionalChars = "";
        ExcludedChars = "";
        Length = 22;
      };
      Security = let minutes = s: builtins.floor (s * 60);
      in {
        ClearClipboardTimeout = minutes 0.75;
        EnableCopyOnDoubleClick = true;
        IconDownloadFallback = true;
        LockDatabaseIdle = true;
        LockDatabaseIdleSeconds = minutes 10;
      };
    };
  };
};
```

## Context

I use NixOS, and like to make sure that every config option I set lasts for twenty years through multiple machine deployments if it can. Currently, I can't enable Firefox Browser Integration if I am to generate the rest of the settings through declarative tooling. This is because some of that tooling uses a centralized world-readable package store, where all sources, configuration, and packages are accessible to any user or malicious code.

Providing options to read this sensitive data from a file allows me to decrypt these secrets at logon of my user session.

**Comment by droidmonkey** [comment]
Just skip over the keeshare config items, they are meaningless. They get auto generated anyway. These will be removed in 2.8.0.

**Comment by spikespaz** [comment]
No, they're not meaningless. Browser integration doesn't work if they are missing.

**Comment by spikespaz** [comment]
The config file is read only because it is a link into the Nix store. So it can't be auto-generated and saved, so I hope it does not need to be saved.

It seems like this works:
1. Remove link: `~/.config/keepassxc/keepassxc.ini`
2. Open KeePassXC, enable browser integration, close completely.
3. Remove file `~/.config/keepassxc/keepass.ini`
4. Replace link.

Then, it seems, browser integration works. Any ideas why this may be?

When switching my Home Manager configuration on a fresh install, KeePassXC repeatedly complains that it can't save the settings file. I can't enable browser configuration. When I remove the generated `keepassxc.ini` and then set the option, the only contents of that file are the `KeeShare` settings. I assumed this was necessary for authenticating the WebExtension IPC.

**Comment by droidmonkey** [comment]
Wait, why are you initially talking about KeeShare and now Browser Integration? KeeShare settings, the XML you posted, have absolutely nothing to do with browser integration. 

Browser Integration requires two parts:
1. Enabled in KeePassXC 
2. Native Messaging json file deployed to the respective location for each browser.

**Comment by spikespaz** [comment]
The issue is as I have described. If `~/.config/keepassxc/keepassxc.ini` is a symbolic link to a file that has set `Browser.Enabled = true`, but that does not have `KeeShare.*` options, browser integration does not work. When I close and re-open settings, the two relevant checkboxes are unchecked, and there is a message at the top complaining about saving the file.

Even if the link is in-place before starting KeePassXC (with the settings in the original message) as a systemd service for the first time, browser integration does not work, and cannot be enabled, until the link is removed and a new config written by the program.

When I opened this issue, I thought maybe browser integration was dependent upon some KeeShare functionality (without being intimately familiar with the codebase, this makes sense) and tried including the `KeeShare` section in my generated configuration. Since this worked, I assumed I was correct and submitted the issue.

Earlier today, I have restored the symbolic link and browser integration continues to work. There is no mention of KeeShare anywhere in my generated config anymore.

I will update the issue title to reflect the question at hand.

**Comment by droidmonkey** [comment]
> until the link is removed and a new config written by the program

Is the link readable by KeePassXC? Sounds like the config file isn't even being loaded at all, and obviously we cannot write our own config file at that point because it's a link.

You should try using strace to figure out what the issue is with reading the link. 

Overall, you have overengineered the config and taken away core functionality of our program (the ability to control our own config). You'll run into a lot of other issues as well when you try to change the program configuration (eg, passwor generator rules). You are much better off just storing the config file in git or similar and writing it when you refresh your OS.

**Comment by spikespaz** [comment]
> Is the link readable by KeePassXC? Sounds like the config file isn't even being loaded at all, and obviously we cannot write our own config file at that point because it's a link.

Yes, it is read, because other settings appear to take affect. Dark mode and password generator length and alphabet for example.

> You should try using strace to figure out what the issue is with reading the link.

Could you please show an example?

> Overall, you have overengineered the config

Different `!=` over-engineered. I aim to make everything I can declaratively configured and immutable. I like to minimize state as much as possible. Changing something on multiple computers is as simple as committing a change, and grabbing it on the other devices. Just because I write extra code to accomplish my goal does not mean it is "over-engineered". I think just about every NixOS user would take issue with that adjective.

> and taken away core functionality of our program

Well, since the core functionality of your program is to manage passwords, and that capability hasn't been inhibited, I would disagree and say that I have only ruined the settings GUI. Which, I do not care for settings GUIs that insist on mutating state during normal operation of the program, in my mind, a program should only modify the main settings file when I tell it to (via the GUI which I don't like to use).

> You'll run into a lot of other issues as well when you try to change the program configuration

Well, it's a good thing that KeePassXC is (mostly) well-behaved according to my opinion, described above. Since I only intend to change program configuration *in code form*, and never expect "ad-hoc" changes to persist past end of runtime (because I am well aware that nearly everything is read-only) this does not disturb me in the slightest.

> You are much better off just storing the config file in git or similar and writing it when you refresh your OS.

You know, I never liked that solution. I had been uploading my "dotfiles" to Git repositories for years before I *explicitly searched for* a program with the capabilities that NixOS offers.

**Comment by 124C41p** [comment]
@spikespaz Using [this module](https://gist.github.com/piousdeer/b29c272eaeba398b864da6abf6cb5daa) you can tell home-manager to create mutable files at each activation. If home-manager is used implicitly as a NixOs module, these mutable files are even recreated at each reboot (this might be true in general, but I haven't tested it on other operating systems).

For example, my minimal keepassxc configuration using that module currently looks like this:

```nix
{ pkgs, ... }:

{
  home.packages = [
    pkgs.keepassxc
  ];

  home.file.".config/keepassxc/keepassxc.ini" = {
    mutable = true;
    force = true;
    text = ''
      [General]
      ConfigVersion=2

      [Browser]
      Enabled=true
      UpdateBinaryPath=false
    '';
  };
}
```

Could this possibly be a compromise in your use case?
