### ISSUE TITLE
[2.8.0-snapshot / MacOS] Touch ID / Quick unlock doesn't appear

### ISSUE THREAD

**Issue by rfaile313** [keepassxreboot/keepassxc#10070]
## Overview
[2.8.0-snapshot / MacOS]

 Touch ID / Quick unlock doesn't appear when locking the database

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Ensure quick database unlock/touch ID is enabled in settings.
2. Lock the database ( cmd + L ) 
3. Note it asks for a password instead of providing a touch ID button

## Expected Behavior

I expect to see an option to unlock the database with touch ID

## Actual Behavior

The box for password input appears

## Context

Its built from the latest "develop" branch on macos locally via brew

[NOTE]: # ( Paste debug info from Help → About here )

KeePassXC - Version 2.8.0-snapshot
Build Type: Snapshot
Revision: cc0530b

Qt 5.15.10
Debugging mode is disabled.

Operating system: macOS 14.1
CPU architecture: arm64
Kernel: darwin 23.1.0

Enabled extensions:
- Auto-Type
- Browser Integration
- Passkeys
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 3.2.0

Operating System: macOS

**Comment by droidmonkey** [comment]
TouchID requires applications to be signed and notorized, which our snapshots are not.

**Comment by rfaile313** [comment]
> TouchID requires applications to be signed and notorized, which our snapshots are not.

Oh! Today I learned -- thanks for clarifying!
