### ISSUE TITLE
KeePassXC installed with snap has no tray icon on KDE

### ISSUE THREAD

**Issue by GabrielCanaple** [keepassxreboot/keepassxc#10083]
## Overview
I installed KeePassXC on Debian with KDE, and I opted these parameters : 
- Show a system tray icon.
- Hide window to system tray when minimized.

The tray icon doesn't appear, but the zone where it is supposed to be on the tray is clickable and works fine. It is only about the icon, everything else is fine.

I tried changing the tray icon type without any success.
I tried changing the KDE theme without any success.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1.  Install KeepassXC with snap on a KDE desktop.
2. Opt these parameters : 
- Show a system tray icon.
- Hide window to system tray when minimized.
3. Minimize KeePassXC and see that the window is successfully hidden, that you can interact with the zone where it is supposed to be in the tray without any problem, but that the icon is hidden.

## Expected Behavior
An clickable icon is supposed to be in the tray.

## Actual Behavior
There is no icon, but you can still interact with the invisible tray icon.

## Context
I use wayland.
I don't think it's part of the problem though, it must have something to do with KDE not finding the path to the icon since everything else is working fine.

### KeePassXC config :
KeePassXC - Version 2.7.6
Revision: dd21def
Distribution: Snap

Qt 5.15.9
Debugging mode is disabled.

Operating system: Ubuntu Core 22
CPU architecture: x86_64
Kernel: linux 6.1.0-13-amd64

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.19.1

[NOTE]: # ( Pick choices based on your environment )
Operating System: Debian Linux
Desktop Env: KDE
Windowing System: Wayland

**Comment by GabrielCanaple** [comment]
Duplicate of keepassxc.png Linux path #7643.
Follow robertg042's answer to fix the problem.

**Comment by droidmonkey** [comment]
We recommend using the flatpak, it works much better.
