### ISSUE TITLE
Facilitate using multiple Firefox profiles

### ISSUE THREAD

**Issue by Dale2O** [keepassxreboot/keepassxc#10093]
I use Firefox with a variety of profiles.  It would be a blessing if keepassxc could record which profile I want to use for each site, with the ability to specify a default, and invoke Firefox with the -P argument  if a profile is specified.

Thank you for considering my suggestion.

**Comment by droidmonkey** [comment]
We are not going to support this feature (it's been requested before). If you want to open a specific entry in a specific profile you should define the url field using the `cmd://` syntax.
