### ISSUE TITLE
Database changes not being merged

### ISSUE THREAD

**Issue by tonyjonespdx** [keepassxreboot/keepassxc#10095]
I made a change to my database (cloud) using the Android App.

Database was simultaneously open on KeepassXC Windows 11 desktop (2.7.4).  Today on WindowsI noticed the entry was still the old entry.

Setting "Automatically reload the database when modified externally" is enabled.

So I tried to re-make the same change (I had previously made on Android) on Windows.  But when it tried to autosave I get the error "Writing the database failed:  Database has unmerged changes".   Manually saving causes same error.

Why was the external (Android change) not auto merged and how do I manually merge?

I ended up quitting the KeePass application (which required I discard) and restart. Now I see the change I made on Android.

**Comment by droidmonkey** [comment]
Not sure, could be a multitude of reasons. Not something we can reproduce though, unless it happens again? In the future you can do Database -> Merge from database and then choose the database file to pull in the latest changes.
