### ISSUE TITLE
System Error: VCRUNTIME140_1.dll was not found

### ISSUE THREAD

**Issue by FlippingBinary** [keepassxreboot/keepassxc#10090]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

This appears to be a regression of #7564, but I couldn't write a comment there because that issue was locked.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Download the [Windows 10 installation media creation tool](https://www.microsoft.com/en-us/software-download/windows10) from Microsoft.
2. Install Windows 10 Pro on an empty drive (installer indicated it was made in May 2023).
3. Check for Windows updates and reboot, repeating as necessary.
4. Go to [KeePassXC download](https://keepassxc.org/download/#windows) page and click Download for Windows, which provides version 2.7.6 as an `.msi`.
5. Install KeePassXC.
6. Open KeePassXC. 

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

KeePassXC launches in all its glory.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

A series of dialogs appear, all warning about missing dlls. The first is `System Error: VCRuntime140_1.dll was not found`.

KeePassXC fails to open.

## Context
[NOTE]: # ( Give us any additional information you may have. )

I resolved the problem on my machine using using [advice](https://github.com/keepassxreboot/keepassxc/issues/7564#issuecomment-1074842970) from @phoerious to download the latest [Visual C++ Redistributable](https://docs.microsoft.com/en-US/cpp/windows/latest-supported-vc-redist?view=msvc-170#visual-studio-2015-2017-2019-and-2022) from Microsoft.

**_However, since the Visual C++ Redistributables are managed separately and might have even been uninstalled, would it be possible for KeePassXC to check on every launch to see if they're installed before trying to use them so the error can be handled gracefully?_**

It looks like the easiest permanent fix would be to [check a few registry keys](https://stackoverflow.com/questions/46178559/how-to-detect-if-visual-c-2017-redistributable-is-installed) to see if they exist, but perhaps that wouldn't be so easy to implement in this case. I'm not very familiar with best practices for distributing Visual C++ programs or the architecture of KeePassXC.

Great software, by the way. I recommend this to people and want to make sure they don't get scared away on their first attempt.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.6
Revision: dd21def

Qt 5.15.10
Debugging mode is disabled.

Operating system: Windows 10 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.19045

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 2.19.3

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 10 Pro
Desktop Env: Windows 10 Pro
Windowing System: Windows 10 Pro

**Comment by droidmonkey** [comment]
We cannot check since our app doesn't even launch before that error appears. The error is owned by Microsoft and they really should be handling it better. We also invested countless hours trying to get the redistribution package installed along with keepassxc and its just not possible with MSI.

**Comment by droidmonkey** [comment]
We cannot check since our app doesn't even launch before that error appears. The error is owned by Microsoft and they really should be handling it better. We also invested countless hours trying to get the redistribution package installed along with keepassxc and its just not possible with MSI.

**Comment by black-backdoor** [comment]
Did you install the [MSVC Redistributable](https://aka.ms/vs/17/release/vc_redist.x64.exe) ? Its one of the requirements.
