### ISSUE TITLE
Auto-type with locked DB should bring to front the main window to unlock it

### ISSUE THREAD

**Issue by anatoli26** [keepassxreboot/keepassxc#101]
The latest KeePassX version before the fork has a problem of deficiently locking the DB and then the auto-type feature, when invoked with a key combination, just says that the DB is locked. So the user should click [OK] on the warning window, then bring the main KPX window to front (no key combination, so lot of mousing or alt-tabbing), unlock the DB, switch back to the window with the user/pass form, press the auto-type key combination and just there he/she gets the desired outcome.

For when the DB is locked, the desired behavior on auto-type invocation is to bringing the unlock-the-DB window that would disappear after successfully unlocking the DB and the normal window with the credentials selection should appear as it appears now when the DB is not locked.

This issue was already commented numerous times before, I don't know why it wasn't already fixed as it's a great annoyance and simple to implement.

There are 2 related issues: no key combination to bring the main window to front (#99) and deficient inactivity mechanism (#100).

_To give this issues a higher priority, I'm willing to contribute economically. Those who could implement it please specify how much should be collected and I could contribute to the implementation on [bountysource.com](https://www.bountysource.com/) or your crowdfunding site of preference._

**Comment by droidmonkey** [comment]
This has already been fixed and merged into develop!! Please search.

https://github.com/keepassxreboot/keepassxc/pull/89

**Comment by anatoli26** [comment]
Oh, great Jonathan! Didn't know you've already made such a great progress! Thanks!

Just compiled and tried the latest commit and found 2 issues, one related to this same issue: though the unlock screen appears, after unlocking the DB it disappears but the credentials window doesn't appear. Another one is with tray menu not working. I'll fill separate issues for each problem now.

**Comment by droidmonkey** [comment]
Great thanks! :smile:
