### ISSUE TITLE
Error messages referring to UUID are useless if one cannot search entries using UUID

### ISSUE THREAD

**Issue by sjvudp** [keepassxreboot/keepassxc#10104]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
Using my KeePass2 KDBX file with KeePassXC 2.7.6 (openSUSE Leap 15.5) I found error messages like the following in syslog:
```
keepassxc[10981]: Maximum depth of replacement has been reached. Entry uuid: {af7493be-9f19-5e4a-894b-6a129e27a05f}
keepassxc[10981]: Maximum depth of replacement has been reached. Entry uuid: {e6810519-51a6-d848-afb2-a3cd0f712976}
```

When I tried to examine those entires I realized that I cannot search entries by UUID.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Try to find an entry matching a (partial) UUID 

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
It should be possible.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
It's not possible.

## Context
[NOTE]: # ( Give us any additional information you may have. )
Important to resolve specific error messages found in syslog.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.6
Revision: dd21def

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: Gnome
Windowing System: X11/Wayland

**Comment by droidmonkey** [comment]
It's possible in 2.7.6: https://github.com/keepassxreboot/keepassxc/pull/9571
