### ISSUE TITLE
Unable to unlock database with known good credentials (password, key file and yubikey)

### ISSUE THREAD

**Issue by shutend** [keepassxreboot/keepassxc#10100]
## Overview
Pretty much the same issue: https://github.com/keepassxreboot/keepassxc/issues/9196
I'm reporting this to dig a little further.
Yesterday I was creating a new database with a password, a new key file and two different yubikeys (with the same secret keys). And I was swapping the yubikeys a lot because I was configuring both. The manager is configured to save after every change, but it needs to be the exactly same yubikey that unlocked the database for it to save, which resulted in several save attempts failing. Maybe that's the reason my database got corrupted?
At some point I couldn't unlock my database. But I unlocked one last time a backup I had. What I find odd is that this backup unlocked on the third try with the EXACT same credentials, without changing anything.
So I tried to remove the necessity for the key file and the hardware key from the database. I could save it, but I ended up corrupting the database for good, I guess.

## Expected Behavior
Unlock my database

## Actual Behavior
Error: "Error while reading the database: Invalid credentials were provided, please try again. If this reoccurs, then your database file may be corrupt. (HMAC mismatch)"

## Context
KeePassXC - Version 2.7.6
Revision: dd21def

Qt 5.15.10
Debugging mode is disabled.

Operating system: Windows 11 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.22631

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 2.19.3

**Comment by droidmonkey** [comment]
Corruption doesn't just happen, you likely set a different password or some combo of your three credentials. Repeat it again without so much confusion and we can reopen.
