### ISSUE TITLE
Documentation - KeePassXC MSI arguments

### ISSUE THREAD

**Issue by ggbce** [keepassxreboot/keepassxc#10102]
## Summary
KeePassXC is available in MSI packaqe for Windows, Windows Server and Windows Legacy computers. MSI allow to provide some arguments during a silent installation to make easier, faster and slipstream deployments !

For basics arguments coming from Windows Installer like "/qn /qb /norestart" etc it's not an issue. This information is wide avaiable from Microsoft directly. 

I search the specific arguments available for KeePassXC. During a GUI step by step (manual) installation we can choose personalized options like "Create desktop shortcut, Launch at startup, Accept EULA, Installation folder, Launch application after installation, ..."

Normally these kind of options should be available in MSI arguments to be able to reproduce in silent installation the same preferences we could set in a manual installation.

## Examples
What could be appreciated
KeePassXC-2.7.6-Win64.msi /qn /norestart /l*v "C:\Windows\TEMP\KeePass.log" /Shortcut=[0|1] /LauchedAtStartup=[0|1]

## Context
Useful to deploy on multiple assets using the same configuration and reflect the client preferences to use KeePassXC.

May be these arguments are already existing in your knowledge, but is not documented and hard to find. Please share the information in your documentation... Otherwise in next version it will very appreciated to compile the MSI with these capabilities.

**Comment by droidmonkey** [comment]
They are documented here: https://keepassxc.org/docs/KeePassXC_GettingStarted#_microsoft_windows

> The following options can be set when running the MSI in an unattended installation:

> LAUNCHAPPONEXIT – Launch KeePassXC after install (default ON)

> AUTOSTARTPROGRAM – KeePassXC will auto-start on login (default ON)

> INSTALLDESKTOPSHORTCUT – A desktop icon will be installed (default OFF)

> Example: msiexec.exe /q /i KeePassXC-Y.Y.Y-WinZZ.msi AUTOSTARTPROGRAM=0
