### ISSUE TITLE
Recent crash on Ventura, updated to latest version

### ISSUE THREAD

**Issue by ericlief** [keepassxreboot/keepassxc#10105]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

Yesterday crashed, updated to latest version today and just crashed will db was open and idle:

-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               KeePassXC [42825]
Path:                  /Applications/KeePassXC.app/Contents/MacOS/KeePassXC
Identifier:            org.keepassxc.keepassxc
Version:               2.7.6 ()
Code Type:             ARM-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2023-12-15 11:38:34.1571 -0600
OS Version:            macOS 13.6.1 (22G313)
Report Version:        12
Anonymous UUID:        755BE946-2FFE-478A-7C20-65A4A32AB5DA

Sleep/Wake UUID:       033FA27E-6B41-45A7-AB3E-6AE82C22CEE2

Time Awake Since Boot: 210000 seconds
Time Since Wake:       10537 seconds

System Integrity Protection: disabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000

Termination Reason:    Namespace SIGNAL, Code 6 Abort trap: 6
Terminating Process:   KeePassXC [42825]

Application Specific Information:
abort() called

Application Specific Backtrace 0:
0   CoreFoundation                      0x0000000190cbf0e4 __exceptionPreprocess + 176
1   libobjc.A.dylib                     0x00000001907ddfd0 objc_exception_throw + 60
2   CoreFoundation                      0x0000000190d6610c -[NSObject(NSObject) __retain_OA] + 0
3   CoreFoundation                      0x0000000190c27010 ___forwarding___ + 1600
4   CoreFoundation                      0x0000000190c26910 _CF_forwarding_prep_0 + 96
5   CoreFoundation                      0x0000000190c3b0f0 __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 148
6   CoreFoundation                      0x0000000190cd6e7c ___CFXRegistrationPost_block_invoke + 88
7   libdispatch.dylib                   0x00000001909b6874 _dispatch_call_block_and_release + 32
8   libdispatch.dylib                   0x00000001909b8400 _dispatch_client_callout + 20
9   libdispatch.dylib                   0x00000001909c6bf8 _dispatch_main_queue_drain + 928
10  libdispatch.dylib                   0x00000001909c6848 _dispatch_main_queue_callback_4CF + 44
11  CoreFoundation                      0x0000000190c87bc4 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 16
12  CoreFoundation                      0x0000000190c45344 __CFRunLoopRun + 1992
13  CoreFoundation                      0x0000000190c44428 CFRunLoopRunSpecific + 612
14  HIToolbox                           0x000000019a496df0 RunCurrentEventLoopInMode + 292
15  HIToolbox                           0x000000019a496c2c ReceiveNextEventCommon + 648
16  HIToolbox                           0x000000019a496984 _BlockUntilNextEventMatchingListInModeWithFilter + 76
17  AppKit                              0x0000000193e6b97c _DPSNextEvent + 636
18  AppKit                              0x0000000193e6ab18 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 716
19  AppKit                              0x0000000193e5ef7c -[NSApplication run] + 464
20  libqcocoa.dylib                     0x0000000108ee925c qt_plugin_instance + 200860
21  QtCore                              0x000000010673e9a4 _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE + 544
22  QtCore                              0x0000000106742a24 _ZN16QCoreApplication4execEv + 132
23  KeePassXC                           0x0000000104dcb368 KeePassXC + 45928
24  dyld                                0x000000019080ff28 start + 2236

Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	       0x190b30744 __pthread_kill + 8
1   libsystem_pthread.dylib       	       0x190b67c28 pthread_kill + 288
2   libsystem_c.dylib             	       0x190a75ae8 abort + 180
3   libc++abi.dylib               	       0x190b20b84 abort_message + 132
4   libc++abi.dylib               	       0x190b103d0 demangling_terminate_handler() + 348
5   libobjc.A.dylib               	       0x1907e6e58 _objc_terminate() + 144
6   libc++abi.dylib               	       0x190b1ff48 std::__terminate(void (*)()) + 16
7   libc++abi.dylib               	       0x190b1feec std::terminate() + 56
8   libdispatch.dylib             	       0x1909b8414 _dispatch_client_callout + 40
9   libdispatch.dylib             	       0x1909c6bf8 _dispatch_main_queue_drain + 928
10  libdispatch.dylib             	       0x1909c6848 _dispatch_main_queue_callback_4CF + 44
11  CoreFoundation                	       0x190c87bc4 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 16
12  CoreFoundation                	       0x190c45344 __CFRunLoopRun + 1992
13  CoreFoundation                	       0x190c44428 CFRunLoopRunSpecific + 612
14  HIToolbox                     	       0x19a496df0 RunCurrentEventLoopInMode + 292
15  HIToolbox                     	       0x19a496c2c ReceiveNextEventCommon + 648
16  HIToolbox                     	       0x19a496984 _BlockUntilNextEventMatchingListInModeWithFilter + 76
17  AppKit                        	       0x193e6b97c _DPSNextEvent + 636
18  AppKit                        	       0x193e6ab18 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 716
19  AppKit                        	       0x193e5ef7c -[NSApplication run] + 464
20  libqcocoa.dylib               	       0x108ee925c 0x108eac000 + 250460
21  QtCore                        	       0x10673e9a4 QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) + 544
22  QtCore                        	       0x106742a24 QCoreApplication::exec() + 132
23  KeePassXC                     	       0x104dcb368 0x104dc0000 + 45928
24  dyld                          	       0x19080ff28 start + 2236

Thread 1:: com.apple.CFSocket.private
0   libsystem_kernel.dylib        	       0x190b33010 __select + 8
1   CoreFoundation                	       0x190c700dc __CFSocketManager + 636
2   libsystem_pthread.dylib       	       0x190b67fa8 _pthread_start + 148
3   libsystem_pthread.dylib       	       0x190b62da0 thread_start + 8

Thread 2:: com.apple.NSEventThread
0   libsystem_kernel.dylib        	       0x190b27f34 mach_msg2_trap + 8
1   libsystem_kernel.dylib        	       0x190b3a260 mach_msg2_internal + 80
2   libsystem_kernel.dylib        	       0x190b30b98 mach_msg_overwrite + 604
3   libsystem_kernel.dylib        	       0x190b282b0 mach_msg + 24
4   CoreFoundation                	       0x190c46754 __CFRunLoopServiceMachPort + 160
5   CoreFoundation                	       0x190c45034 __CFRunLoopRun + 1208
6   CoreFoundation                	       0x190c44428 CFRunLoopRunSpecific + 612
7   AppKit                        	       0x193f95f54 _NSEventThread + 172
8   libsystem_pthread.dylib       	       0x190b67fa8 _pthread_start + 148
9   libsystem_pthread.dylib       	       0x190b62da0 thread_start + 8

Thread 3:: Thread (pooled)
0   libsystem_kernel.dylib        	       0x190b2b730 __psynch_cvwait + 8
1   libsystem_pthread.dylib       	       0x190b68574 _pthread_cond_wait + 1232
2   QtCore                        	       0x10659e5d0 0x106574000 + 173520
3   QtCore                        	       0x10659e284 0x106574000 + 172676
4   QtCore                        	       0x10659e1c4 QWaitCondition::wait(QMutex*, QDeadlineTimer) + 104
5   QtCore                        	       0x10659a524 0x106574000 + 156964
6   QtCore                        	       0x106595e44 0x106574000 + 138820
7   libsystem_pthread.dylib       	       0x190b67fa8 _pthread_start + 148
8   libsystem_pthread.dylib       	       0x190b62da0 thread_start + 8

Thread 4:
0   libsystem_pthread.dylib       	       0x190b62d8c start_wqthread + 0

Thread 5:
0   libsystem_pthread.dylib       	       0x190b62d8c start_wqthread + 0

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Just open
2. 
3. 

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.6
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
 OSX 13.6.1

**Comment by droidmonkey** [comment]
This didn't crash in keepassxc code

**Comment by ericlief** [comment]
I don;t follow. I rebooted and it seems ok, but the log shows termination of keepasxc

**Comment by droidmonkey** [comment]
The crash happened in macos code. I'm going to close this unless you can reliably reproduce the issue.
