### ISSUE TITLE
Keepasscx-cli doesn't support Umlaut (äöü) on Windows for Titel

### ISSUE THREAD

**Issue by JsBergbau** [keepassxreboot/keepassxc#10109]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Create database
2. execute `keepassxc-cli.exe add C:\Users\mine\testdb.kdbx TäöüT --username TäöüT`

## Expected Behavior
There should be the correct entry like when generated manually
![grafik](https://github.com/keepassxreboot/keepassxc/assets/37013344/100a7c3b-c419-40b6-960a-1a97380fefc6)

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
It will show strange symbols
![grafik](https://github.com/keepassxreboot/keepassxc/assets/37013344/d449a2de-0422-4a5c-b9dc-f9693ade2d84)
(this screenshot was only possible using an RDP connection, because KeepassXC prevents from making screenshots

## Context
[NOTE]: # ( Give us any additional information you may have. )
Windows 10
I've found this issue https://github.com/keepassxreboot/keepassxc/issues/2413 
It might be related
I already tried using chcp 1252, chcp 850, chcp 65001, but didn't help. Neither using powershell, nor running it from python via subprocess.run

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.6
Revision: dd21def

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows

**Comment by droidmonkey** [comment]
Using Windows 11, Powershell 7.3.10 and Command Prompt worked perfectly for me.

![image](https://github.com/keepassxreboot/keepassxc/assets/2809491/93d239ce-8a7a-4ddf-8243-2ce5f52807aa)

Unfortunately, this might be a limitation with your version of Windows 10, recommend upgrading.

You can also try installing Windows Terminal: https://www.microsoft.com/store/productId/9N0DX20HK701?ocid=pdpshare

**Comment by JsBergbau** [comment]
Thank you very much. Works with Windows 10 22H2 from normal cmd, doesn't work with 1809 LTSC (neither powershell nor cmd).
