### ISSUE TITLE
YubiKey not recognized in KeePassXC on Surface Laptop 5 without admin privileges

### ISSUE THREAD

**Issue by ErminMerdanovic** [keepassxreboot/keepassxc#10113]
## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Launch KeePassXC without administrative privileges.
2. Attempt to select the Hardware Key option.

## Expected Behavior
The Hardware Key is appearing

## Actual Behavior
The Hardware Key is not appearing.

## Context
When launching KeePassXC without administrative privileges on my Surface Laptop 5, the YubiKey is not visible in the dropdown list. However, when the application is launched with administrative privileges, the YubiKey becomes visible. This issue is specific to my Surface Book running Windows Hello and does not occur on my desktop PC.

KeePassXC - Version 2.7.6
Revision: dd21def

Operating System: Windows 11

**Comment by droidmonkey** [comment]
This isn't a keepassxc problem. You may have locked out the key to only allow admins to see the usb interface. Uncertain on how you did that on Windows though. You'll have to figure out why your key isn't visible to a standard user. 

This might be useful: https://windowsreport.com/enable-usb-ports-blocked-by-administrators/#:~:text=Unblock%20USB%20ports%20with%20Device%20Manager%201%20Press,Enable%20device%2C%20if%20the%20option%20is%20listed%20there.
