### ISSUE TITLE
Information about screen capture

### ISSUE THREAD

**Issue by alexserranogarcia** [keepassxreboot/keepassxc#10111]
Hello everyone,

I'd like to know how does KeePassXC achieve the funcionallity of blocking itself from being screen capture.

I am working on a personal project and would like to know how that could work, I've searched a lot but it's been impossible for me to gain any knowledge about this.

Can anyone help me know how this feature could be implemented in a Microsoft Word file, as an example?

Thank you

**Comment by droidmonkey** [comment]
You cannot implement it in Microsoft Word unless you are calling system libraries via a macro (maybe). Here is the code that achieves window hiding on Windows: https://github.com/keepassxreboot/keepassxc/blob/e355ac54b8600ea850f7f9f11af374c84ba144a0/src/gui/osutils/winutils/WinUtils.cpp#L64
