### ISSUE TITLE
Return Only Best Matching Credentials ignores Path (again, or still) 

### ISSUE THREAD

**Issue by Ordiel** [keepassxreboot/keepassxc#10115]
## Steps to Reproduce, Expected Behavior & Actual Behavior
See issue [4754](https://github.com/keepassxreboot/keepassxc/issues/4754)
KeePassXC - 2.7.6

Operating System: Linux (ubuntu)
Desktop Env: Gnome
Windowing System: Wayland

---
Even on this version, having enabled the `Return Only Best Matching Credentials` checkbox the path is _still_ being ignored when it comes to matching a password entry when multiple password entries share the same host yet having different path

**Comment by droidmonkey** [comment]
Unlikely broken as you describe, this is very well tested code. https://github.com/keepassxreboot/keepassxc/blob/develop/tests%2FTestBrowser.cpp#L181

Without further specific details there isn't proof of a problem.
