### ISSUE TITLE
Dropbox / Finder not detecting changes to kdbx files on MacOS

### ISSUE THREAD

**Issue by ivdorelian** [keepassxreboot/keepassxc#10118]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

KeePassXC 2.7.6 on MacOS 14.1.1 does not update the "Modified" file attribute when editing entries in a database that's saved in the Dropbox folder. This causes syncing issues with Dropbox not snyching the edited file. Closing and reopening the db file in KeePassXC shows the changes, so they are saved.

This seems to be a Finder-only or Dropbox-only issue, as an `ls -alh` in the same folder does show the change. 

Rebooting does nothing, I have a db file that I edit at least once a week and it shows modified in april of last year.

Directly write to database is enabled and backups are disabled.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Create a db file in the dropbox folder.
2. Edit it.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

Dropbox detects the changes and synchs the file. Finder shows the correct modified date.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

1. Dropbox does not detect changes to it and it does not synch it.
2. Find the file in the Dropbox app and click "Open in Finder", the file's Modified date has not changed. 

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.6
Revision: dd21def

Qt 5.15.10
Debugging mode is disabled.

Operating system: macOS 14.1
CPU architecture: arm64
Kernel: darwin 23.1.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 2.19.3

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS

**Comment by droidmonkey** [comment]
I have to ask some basic questions because this just doesn't make sense. 

Are you sure you are opening the correct database file?

Have you tried clearing your Dropbox cache and reloading everything? 

Have you tried not using direct write saving?

**Comment by droidmonkey** [comment]
I just setup Dropbox on the Mac test machine and it worked flawlessly with keepassxc. You'll have to figure out why it's not working for you unfortunately. Try reinstalling the Dropbox client.
