### ISSUE TITLE
Sort by descending Creation or Modified Date without Groups

### ISSUE THREAD

**Issue by DeeCentralize** [keepassxreboot/keepassxc#10116]
## Summary
Allow a View that visually eliminates Grouping by Folders and shows all entries by descending Mod or Create date. A Hot Key would be preferred to turn this on and off. A displayed count of all URLs would be nice. 

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )

## Context
I have hundred of folders into which new links are added weekly depending on topic. I wish to view all the links I've added in the last week or month to quickly retrieve a link of interest when compiling research. Having to pogo stick through folders to find the most recent research is time consuming.

**Comment by droidmonkey** [comment]
Use saved searches, everything you ask for already exists. The number of entries in a group or search are shown in the bottom right status bar.

**Comment by DeeCentralize** [comment]
Thanks for the tip, had not noticed the entry count. 

I've searched thru the help docs and can't find an example of a saved search that would allow me to list all 8,700 entries (in 1,000 Groups) by reverse chronological sort (newest at top) without any grouping. Would you be so kind as to provide a search query that could do that? 

Thanks for a great utility. Five-year user. Donated BTC last year to support your efforts.

**Comment by droidmonkey** [comment]
There is an existing (preset) saved search called "All Entries" in the lower left tags and searches box. Or you can just type in `*` as your search term. Use the headers to sort the results as you please.

**Comment by DeeCentralize** [comment]
Thank you! Works great. So obvious now.
