### ISSUE TITLE
Failure to manage ATTACHMENTS

### ISSUE THREAD

**Issue by Bepon-LIC** [keepassxreboot/keepassxc#10127]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
No Attachment management

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Voice opening
2. Advanced
3. Attachments
3. Only "Open" and "Save" buttons present
4. In the guide there are also "ADD" and "REMOVE"

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Restore missing buttons to manage attachments

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
It is not possible to manage attachments (insert new attachment, delete or modify existing attachment)

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Versione 2.7.6
Revisione: dd21def

Qt 5.15.10
La modalità debug è disabilitata.

Sistema operativo: Windows 11 Version 2009
Architettura CPU: x86_64
Kernel: winnt 10.0.22621

Estensioni abilitate:
- Completamento automatico
- Integrazione browser
- Agente SSH
- KeeShare
- YubiKey
- Sblocco rapido

Librerie crittografiche:
- Botan 2.19.3

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows
Desktop Env: Windows
Windowing System: 11 Version 2009

**Comment by droidmonkey** [comment]
Open the entry for editing.
