### ISSUE TITLE
Unnaturally large cursor, when running KeePassXC at sytsem startup 

### ISSUE THREAD

**Issue by piorkov** [keepassxreboot/keepassxc#10122]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
When I run KeePassXC automatically at system startup, when I hover over the program window, the cursor is unnaturally large.
The problem affects only the KeePassXC window - also all pop up windows (the problem does not occur for other programs that I run on startup) and after restarting the program the problem no longer occurs. 
![Screenshot from 2023-12-22 11-12-53](https://github.com/keepassxreboot/keepassxc/assets/80216952/ab07d0e5-d8d2-41a9-b9d7-64e6b9b290cf)

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Set KeePassXC to run automatically on startup in Gnome
2. Restart computer 

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Mouse cursor is normal

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Mouse cursor is large

## Context
[NOTE]: # ( Give us any additional information you may have. )
I have three monitors connected, each with a different resolution, but the scaling for all of them is set the same (100%)

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.6
Revision: dd21def

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: Gnome 42
Windowing System: X11

**Comment by droidmonkey** [comment]
See here: https://github.com/keepassxreboot/keepassxc/issues/9264#issuecomment-1861505670
