### ISSUE TITLE
main window froze after closing password generator 

### ISSUE THREAD

**Issue by Brbrbr1995** [keepassxreboot/keepassxc#10128]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
main window froze after closing password generator

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. click the password generator button (green key icon) in webpage
2. click X to close the password generator
3. main window freezz,click anywhere will make a dinggg sound,cant close window,had wo use taskmanager to end it

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
dont freeze the main window

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
main window freeze up

## Context
[NOTE]: # ( Give us any additional information you may have. )
windows 10 , chromiun ungoogled 120

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION
Revision: REVISION
KeePassXC - Version 2.7.6
Revision: dd21def

Qt 5.15.10
Debugging mode is disabled.

Operating system: Windows 10 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.19045

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 2.19.3

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows

**Comment by droidmonkey** [comment]
This is fixed for 2.8.0, for now use the close button in the dialog instead.
