### ISSUE TITLE
KeePassXC crashes, when I change "Highlight colour" in System Preferences/General (macOS Catalina v10.15.7) 

### ISSUE THREAD

**Issue by bienvecode** [keepassxreboot/keepassxc#10123]
## Steps to Reproduce
1. Open KeePassXC
2. Go to System Preferences/General
3. Change Highlight colour

## Expected Behavior
I hope the program continues to work.

## Actual Behavior
KeePassXC closes, crashes, when I change color.

## Context
KeePassXC - Version 2.7.6
Revision: dd21def

Qt 5.15.8
Debugging mode is disabled.

Operating system: macOS 10.15
CPU architecture: x86_64
Kernel: darwin 19.6.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 2.19.3

Operating System: macOS Catalina v10.15.7

**Comment by droidmonkey** [comment]
https://github.com/keepassxreboot/keepassxc/issues/9527
