### ISSUE TITLE
Windows Hello does not finish setup in windows 11

### ISSUE THREAD

**Issue by rdelpeso** [keepassxreboot/keepassxc#10125]
## Overview
Unable to setup Windows hello after fresh  install of windows 11.

![Screenshot 2023-12-23 221530](https://github.com/keepassxreboot/keepassxc/assets/1075376/aca2798a-ea8a-4149-9d59-cb06df4edbf8)

Any suggestions on how to get this to work? Is it a known bug? Or is it something that Windows has miss-configured by default and I have to do some extra work?

## Steps to Reproduce
1. Format PC
2. Install windows 11
3. Download KeepassXC latest version 2.7.6
4. Enable "Enable database quick unlock (Touch ID / Windows Hello)"
5. Open a KDBX database
6. Type correct master password
7. Type correct Windows Hello password (PIN)

## Expected Behavior
Quick Unblock should be setup and work

## Actual Behavior
Get error message "Windows Hello setup was canceled or failed. Quick unlock has not be enabled."

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.6
Revision: dd21def

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 11
Desktop Env: Windows
Windowing System: Windows

**Comment by droidmonkey** [comment]
Redo your windows hello enrollment within the windows settings.
