### ISSUE TITLE
Add KeePassXC to Product Hunt

### ISSUE THREAD

**Issue by quinncomendant** [keepassxreboot/keepassxc#1012]
KeePassXC is not listed in Product Hunt, but should be. I'd do it myself but I don't have a PH account.

![screen shot 2017-09-30 at 16 21 38](https://user-images.githubusercontent.com/6884276/31045183-90259b6a-a5fb-11e7-8bdd-7a2a83c30b18.png)

**Comment by droidmonkey** [comment]
I went to the site, didn't see anyway to submit something, left. If you have further insight that would be great, but it doesn't seem too interested in submissions to me.

**Comment by quinncomendant** [comment]
1. [create an account](https://www.producthunt.com/contributor)
2. [fulfill the requirements to become a contributor](https://help.producthunt.com/posting/how-can-i-get-access-to-postcomment) (takes 3 days – yeah, it's a pain)
3. post a new entry by clicking '+' in the header

ProductHunt is a popular database used to announce the release of a new software project. I'm sure someone associated with the KeePassXC already has a PD account and can submit on its behalf.

**Comment by phoerious** [comment]
Feel free to submit us. I didn't know about ProductHunt before I read this, but we are in a lot of other databases (e.g. alternative.to) without any of us having ever submitted KeePassXC there. So if you think, this is important, please go ahead.

**Comment by quinncomendant** [comment]
My PH account was approved, so I'm able to add projects; I'm adding KPXC now. One of the metadata is the twitter handles for the project maintainers. I found @Th3Zer0 and @reflinux – what are the others?

Quinn

**Comment by quinncomendant** [comment]
I've [added it](https://www.producthunt.com/posts/keepassxc). 

The project description is limited to 350 characters, so I took some liberty in editing the text copied from the website.

The project shows **MAKERS: There are no makers yet** because none of y'all have a PH account. I've added `@Th3Zer0` and `@reflinux` as makers (twitter or PH account name required); if you others want to be listed as “makers” send me your twitter names. But it's just a vanity thing. The website and github project are both linked, so people will still find you if they want to.

**Comment by phoerious** [comment]
Can't you rather add GitHub or Google+ accounts?

**Comment by quinncomendant** [comment]
On Tue, 03 Oct 2017 10:09:24 +0000 (UTC), Janek Bevendorff wrote:
> Can't you rather add GitHub or Google+ accounts?

Nope. The field where you add the "Maker" has this text: `Add the Product Hunt/Twitter username of one of the makers`

**Comment by droidmonkey** [comment]
Looks good 👍 

I got turned off by Product Hunter when they only allowed logins from Facebook, Twitter, and Angellist. I don't have an account on any of those platforms and have no interest.
