### ISSUE TITLE
Github TOTP doesn't match with generated TOTP code

### ISSUE THREAD

**Issue by feelingnothing** [keepassxreboot/keepassxc#10129]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
When I'm trying to setup github TOTP the code for verification doesn't match the expected

## Context
[NOTE]: # ( Give us any additional information you may have. )
![image](https://github.com/keepassxreboot/keepassxc/assets/47575622/a30dfd5d-906c-4da2-9f17-89af6cdc5d37)
There are the default settings for TOTP from github docs:
https://docs.github.com/en/authentication/securing-your-account-with-two-factor-authentication-2fa/configuring-two-factor-authentication

[NOTE]: # ( Paste debug info from Help → About here )
```
KeePassXC - Version 2.7.6
Revision: dd21def

Qt 5.15.10
Debugging mode is disabled.

Operating system: Windows 11 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.22621

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 2.19.3
```

**Comment by droidmonkey** [comment]
Synchronize your computer's time

Also https://github.com/keepassxreboot/keepassxc/issues/9897#issuecomment-1751061617

And #9869
