### ISSUE TITLE
KeepassXC in light mode after changing to oxygen theme

### ISSUE THREAD

**Issue by siggjen** [keepassxreboot/keepassxc#10139]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

I switched from Breeze dark to Oxygen theme in KDE and KeepassXC is in light mode which hurts my eyes. I can not select dark mode in the settings.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1.  Install Linux/KDE, Arch in my case
2. Set theme to Breeze dark and KeepassXC is in dark mode
3. Set theme to Oxygen and KeepassXC is in light mode. Oxygen is a dark theme.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
KeepassXC in dark mode

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
KeepassXC in light mode

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.6-2
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux/
Desktop Env: KDE
Windowing System: X11

**Comment by droidmonkey** [comment]
View -> Theme -> Dark

**Comment by siggjen** [comment]
I am sorry but there is no textmenu in KeepassXC. I know there is in Windows, but it doesn't appear for me.

**Comment by phoerious** [comment]
There is. If it's not shown, then your desktop environment is to blame. Perhaps you have the KDE global menu enabled?
