### ISSUE TITLE
[Discussion] Password manager for computer login?

### ISSUE THREAD

**Issue by adatum** [keepassxreboot/keepassxc#1013]
Does anyone use a password manager for their physical (non-remote) computer login? If so, how? When facing a computer's login screen, a password manager won't be available yet. Using another computer/smartphone to lookup the password and entering it manually is cumbersome. 

If not, that means the login password for a physical computer is one that doesn't benefit from a password manager, and is thus more vulnerable.

Sorry, this isn't an issue, and also not specific to keepassxc, but I think it's relevant to know what strategies users have come up with, if any.

**Comment by droidmonkey** [comment]
OS login terminals are inherently separated from userland apps (this is why you press ctrl+alt+del for windows). This is on purpose for very many good reasons. You're best bet to secure OS login is to use 2 factor auth such as a pki token or time based token.
