### ISSUE TITLE
[Regression] KeePassXC browser integration does not remember denied entries

### ISSUE THREAD

**Issue by duongdominhchau** [keepassxreboot/keepassxc#10132]
## Overview

Regression of https://github.com/keepassxreboot/keepassxc/issues/5765

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Create new entry with any username and password, set URL to `semantic-ui.com`
2. Visit <https://semantic-ui.com/examples/login.html>, it should prompt for access
3. Deny all and refresh
4. The same dialog pops up again

## Expected Behavior

Denied entries should not be shown again.

## Actual Behavior

Denied entries are still shown everytime I visit the site.

## Context

KeePassXC - Version 2.7.6
Revision: dd21def

Qt 5.15.10
Debugging mode is disabled.

Operating system: Windows 11 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.22621

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 2.19.3

Operating System: Windows

**Comment by droidmonkey** [comment]
Confirmed this is broken @varjolintu

**Comment by varjolintu** [comment]
I cannot reproduce this with 2.8.0.

**Comment by droidmonkey** [comment]
We may have fixed it?

**Comment by varjolintu** [comment]
> We may have fixed it?

https://github.com/keepassxreboot/keepassxc/pull/9607
