### ISSUE TITLE
Auto-type has stopped working on Ubuntu 22.04

### ISSUE THREAD

**Issue by shawn1thompson** [keepassxreboot/keepassxc#10133]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
What the title says. I'm not sure why it stopped. I hit the auto type key combo, the switch to Firefox is made and the entry field is highlighted, but nothing is typed.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Press key combo
2. Watch
3. Observe no input into field

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Auto type should input the username and password

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
As above

## Context
[NOTE]: # ( Give us any additional information you may have. )
Using KeepassXC Flatpak and Firefox from repositories, i.e., not Snap

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.6
Revision: dd21def

Qt 5.15.3
Debugging mode is disabled.

Operating system: Ubuntu 22.04.3 LTS
CPU architecture: x86_64
Kernel: linux 6.2.0-39-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.19.1

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: Gnome
Windowing System: Wayland

**Comment by droidmonkey** [comment]
Auto-Type is not supported on Wayland. Is Firefox running on X11 (via xwayland)? You should also make sure the window title isn't changing.

**Comment by shawn1thompson** [comment]
That must be the issue. Firefox is now running on Wayland. I forgot about that update. I guess I have a decision to make. Thanks.

**Comment by ralfberger** [comment]
*** EDIT ***
My solution is simple. I use Debian 12 and in the login screen I simply select X11 instead of Wayland. Then Auto-Type works correctly in Firefox 121
******

I have also just updated from Firefox 115 esr to 121 (Debian 12) and found that Auto-Type no longer works. With Firefox 115-esr under Debian 12 / Wayland I started KeepassXC with "keepassxc -platform xcb" and Auto-Type worked fine. Unfortunately, this no longer works under Firefox 121 either. Will there be a solution for this problem soon?  Would the installation of the browser plugin be a safe, functional solution?

Thanks and best regards

**Comment by droidmonkey** [comment]
The problem is not on our end, Firefox is running under wayland and you need to force it to run on x11 if you want to use Auto-Type

**Comment by shawn1thompson** [comment]
Are there plans to have KeepassXC work properly under Wayland? It seems Wayland is slowly replacing X11 though I'm not privy to related discussions.
Shawn Thompson <br>
<a href="https://contemplaridotlife.wordpress.com/2023/10/22/contacting-me/">Contact</a>

**Comment by droidmonkey** [comment]
Read through #2281

**Comment by GalaxySnail** [comment]
> Read through #2281

#2281 was locked; however, the information is outdated. Currently we have the global keyboard shortcut portal and [libei](https://gitlab.freedesktop.org/libinput/libei), which should be good enough for auto-type.

For enumerating windows, there is a [foreign toplevel list protocol](https://wayland.app/protocols/ext-foreign-toplevel-list-v1).

**Comment by droidmonkey** [comment]
Interesting, thank you, I'll add to the other thread
