### ISSUE TITLE
Build fails on Remove.cpp: possibly dangling reference to a temporary

### ISSUE THREAD

**Issue by dmaslenko** [keepassxreboot/keepassxc#10134]
## Overview
The compilation fails with error:
```shell
/home/dmytro/Desktop/github/fork/keepassxc/src/cli/Remove.cpp:39:11: error: possibly dangling reference to a temporary [-Werror=dangling-reference]
```

## Steps to Reproduce
1. `cd build`
2. `cmake -DWITH_XC_ALL=ON -DCMAKE_BUILD_TYPE=Debug -DWITH_TESTS=ON -DWITH_GUI_TESTS=ON ..` 
3. `make -j8`

## Expected Behavior
The build should not fail with above mentioned error.

## Actual Behavior
The build fails on the `Remove.cpp` compilation:
```shell
/home/dmytro/Desktop/github/fork/keepassxc/src/cli/Remove.cpp: In member function ‘virtual int Remove::executeWithDatabase(QSharedPointer<Database>, QSharedPointer<QCommandLineParser>)’:
/home/dmytro/Desktop/github/fork/keepassxc/src/cli/Remove.cpp:39:11: error: possibly dangling reference to a temporary [-Werror=dangling-reference]
   39 |     auto& entryPath = parser->positionalArguments().at(1);
      |           ^~~~~~~~~
/home/dmytro/Desktop/github/fork/keepassxc/src/cli/Remove.cpp:39:55: note: the temporary was destroyed at the end of the full expression ‘QCommandLineParser::positionalArguments() const().QStringList::<anonymous>.QList<QString>::at(1)’
   39 |     auto& entryPath = parser->positionalArguments().at(1);
      |                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~
```

## Context
- make `3.27.4`
- cmake `4.3`
- g++ `13.2.0`

The latest `develop` branch version.
Operating System: `Ubuntu 23.10 Mantic Minotaur (x86-64)`
Desktop Env: `Cinnamon 5.8.4`
Windowing System: `Wayland`

**Comment by droidmonkey** [comment]
This seems like an overzealous compiler warning, qt doesn't clean up after itself like that. I'd agree that the reference is dangling if the parser object would have been deleted, but it's still intact.  Simply removing the & after auto will fix the issue though.

**Comment by c4rlo** [comment]
This seems good to close. @droidmonkey
