### ISSUE TITLE
file picker not opening

### ISSUE THREAD

**Issue by Arbel-arad** [keepassxreboot/keepassxc#10140]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. install keepassxc / git on arch linux
2. click on "open database"

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
file picker opens and i can load my database.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
absolutely nothing.

## Context
[NOTE]: # ( Give us any additional information you may have. )
wayland compositor: hyprland
file manager: thunar
i tested with both the regular and -git packages, same result.
when i tried the appimage version it opened fine, but didn't seem to use thunar.
if i launch keepassxc from the terminal with a file specified it will open fine.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.8.0-snapshot
Build Type: Snapshot
Revision: 9e11923

Qt 5.15.11
Debugging mode is disabled.

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 6.6.8-zen1-1-zen

Enabled extensions:
- Auto-Type
- Browser Integration
- Passkeys
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 3.2.0

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: hyprland
Windowing System: Wayland

**Comment by droidmonkey** [comment]
Please file a bug with the arch maintainers, this isn't a keepassxc specific problem. Some combo of their release and your desktop env is not working. You can also use the flatpak version.
