### ISSUE TITLE
Extensions using a plugin interface

### ISSUE THREAD

**Issue by wsidl** [keepassxreboot/keepassxc#1014]
Although I just found this project today and so happy to find something properly cross-platform, but it's definitely missing something. I can say that what I'm asking for is a lot, but the payout is worth it. That is having a plugin interface with an API for other developers to create their own plugins for KeePassXC.

## Expected Behavior
Have instructions for creating a plugin package with an API Document and some examples. From the settings dialog, install the plugin either from a plugins repository or as a downloadable package.

## Current Behavior
Extensions are hidden and API not documented ("KeepassHTTP", "Yubikey", "Auto-Type").

## Possible Solution
So many ways this could work:
1. Using a standard set of shared libraries. Pros: faster and more efficient, easier to test. Cons: Sometimes can be riskier as you open up object types to outside architectures and not all languages support these libraries on all platforms.
2. Create a secured RPC API. Pros: Easier to implement and control of data types. Allows incorporating larger enterprise solutions into the application. Cons: Dealing with network interfaces for communication and still need external parsers for starting the extensions separately.

Any of these options would provide some debugging and exception handling to prevent poorly developed plugins from shutting down the application and potentially causing security risks through memory leaks.

## Context
Althought extensions are a part of the application, having this option for others not directly related to the project makes it easier for people to take on their own parts without directly requiring approval from the main contributors. This means feature requests pushed to plugins and less to distract from the focus of the project while still getting the value added.
I can already see a number of plugins that would be created that would be beyond the scope of this project, but small groups of users would definitely see the benefit (Custom formatted TOTP, enterprise-level incorporation, key-by-key database synchronization)

**Comment by droidmonkey** [comment]
Appreciate your enthusiasm for this but there is already an open issue for a plug-in interface. #734
