### ISSUE TITLE
Annoying application close

### ISSUE THREAD

**Issue by sprat** [keepassxreboot/keepassxc#10141]
## Overview

Annoying user experience: the application closes when I try to open it by clicking on the taskbar button.

I am using Xubuntu (Ubuntu with the XFCE display manager), I have configured the display manager task bar to appear at the bottom of the screen, and the KeepassXC application icon is always visible in the task bar.

When I click on the app icon, the contextual popup opens. But the "close" menu option happens to appear just under the mouse cursor, and sometimes a click is triggered on this item, closing the application. I've noticed that it's probably when I release the mouse button not fast enough, the click up event seems to trigger the menu option.

![step1](https://github.com/keepassxreboot/keepassxc/assets/577183/56858ebc-00cd-4925-a01c-b4cfa69ec6f0)
![step2](https://github.com/keepassxreboot/keepassxc/assets/577183/0b49e624-60e9-44af-9f47-1cdf185a43f5)

## Steps to Reproduce

Use XFCE, configure the task bar to appear at the bottom of the screen and make sure that the application appear in the taskbar.

Click DOWN on the app icon, but don't release the button too fast. Then release the button (without moving the mouse): the application closes!

## Expected Behavior

I would prefer the application not to close immediately without a warning :)

## Actual Behavior

The application close itself, as it is supposed to do, but it's very annoying because that's not what I wanted to do.

I am not sure how the problem can be solved, it seems to be an unexpected behavior of the display manager. However I've noticed that some other applications show their contextual menu with an offset from the taskbar (it does not superimpose with the task bar) and other ones happen to avoid having the close button right under the mouse, but another menu item instead (e.g. Settings).

## Context

KeePassXC - 2.6.6
Révision : 9c108b9

Operating System: Linux, Xubuntu 22.04
Desktop Env: XFCE
Windowing System: X11 probably

**Comment by droidmonkey** [comment]
This would be a bug with xfce itself, the menu shouldn't open over the taskbar. We don't control the position or behavior of the menu. Please route an issue with xfce to fix their menu behavior. 

Also, we are on version 2.7.6, please update. You can use flatpak to get the latest version and possibly even fix your issue.
