### ISSUE TITLE
build issue after git pull (tag 2.2.1)

### ISSUE THREAD

**Issue by affinityv** [keepassxreboot/keepassxc#1015]
FTBFS

## Expected Behavior
build Linux binary from source

## Current Behavior
Failed with error

## Steps to Reproduce (for bugs)
$ git pull      # already have clone of project
$  mkdir build
$ cd build
$ cmake -DWITH_XC_AUTOTYPE=ON -DWITH_XC_HTTP=ON -DWITH_XC_YUBIKEY=ON \
>     -DCMAKE_BUILD_TYPE=Release ..
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test WERROR_C_AVAILABLE
-- Performing Test WERROR_C_AVAILABLE - Success
-- Performing Test WERROR_CXX_AVAILABLE
-- Performing Test WERROR_CXX_AVAILABLE - Success
CMake Error at CMakeLists.txt:211 (find_package):
  By not providing "FindQt5LinguistTools.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "Qt5LinguistTools", but CMake did not find one.

  Could not find a package configuration file provided by "Qt5LinguistTools"
  (requested version 5.2) with any of the following names:

    Qt5LinguistToolsConfig.cmake
    qt5linguisttools-config.cmake

  Add the installation prefix of "Qt5LinguistTools" to CMAKE_PREFIX_PATH or
  set "Qt5LinguistTools_DIR" to a directory containing one of the above
  files.  If "Qt5LinguistTools" provides a separate development package or
  SDK, be sure it has been installed.

-- Configuring incomplete, errors occurred!
See also "/home/andrewm/git/keepassxc/build/CMakeFiles/CMakeOutput.log".

## Context
Cannot build

## Debug Info
KeePassXC - 2.2.1

Prior (current version details)
KeePassXC - Version 2.2.0
Libraries:
- Qt 5.9.0
- libgcrypt 1.6.1

Operating system: Linux Mint 18.2
CPU architecture: x86_64
Kernel: linux 4.11.0-14-generic

Enabled extensions:
- KeePassHTTP
- Auto-Type
- YubiKey

**Comment by magkopian** [comment]
Just wanted to say that I'm currently in the process of building the Debian binaries for the new release, and so far I have experienced no issues with the building process. So, whatever the issue is, it's most likely not related with the code base of the project itself.

@affinityv Have you tried downloading a fresh copy of the source code from the [releases page](https://github.com/keepassxreboot/keepassxc/releases) and then compiling it?

**Comment by droidmonkey** [comment]
Also master is perfectly fine in Travis. https://travis-ci.org/keepassxreboot/keepassxc/builds/281933176

**Comment by affinityv** [comment]
I just renamed my git repository directory and did a fresh git clone; then tried to compile and got the same problem.

**Comment by droidmonkey** [comment]
You are missing a package... namely the Qt5 Linguist Tools. Follow our environment setup guides.

https://github.com/keepassxreboot/keepassxc/wiki/Set-up-Build-Environment-on-Linux

**Comment by affinityv** [comment]
This link has different information for setting up the build environment.
https://github.com/keepassxreboot/keepassxc/wiki/Building-KeePassXC

I've got everything that isn't optional, has one of those changed to non-optional now?  Why are the two sets of instructions different?

**Comment by affinityv** [comment]
Okay, I've installed all those extra packages, please adjust the other link in my post above to ensure that ALL the required libraries are included; the two different build wiki areas do not agree.  I don't know if all of the newly installed libraries are all required or if I now have extra libraries that are really optional, but the build works now.  I would like to remove libraries that are optional and not required though.

KeePassXC - Version 2.2.1
Revision: 14e3d9d576c3d8f8bdcf31cd2c0c423b89a66ca9

Libraries:
- Qt 5.5.1
- libgcrypt 1.6.5

Operating system: Linux Mint 18.2
CPU architecture: x86_64
Kernel: linux 4.11.0-14-generic

Enabled extensions:
- Auto-Type

**Comment by droidmonkey** [comment]
Step 1 after the libraries discussion points to the link i posted. They are not out of alignment.

**Comment by affinityv** [comment]
No, that is not true; the first section at this link [1] shows what is required and what is optional and following that instruction gives a failure to build.  It is only after installing extra packages that the build worked.

[1] https://github.com/keepassxreboot/keepassxc/wiki/Building-KeePassXC

**Comment by droidmonkey** [comment]
Your specific issue was due to lack of qt5linguist tool which is provided by either qttools5-dev or qttools5-dev-tools. Qttools is listed under required libs.

Now granted, we should list the yubikey libs under optional as well.

**Comment by affinityv** [comment]
Those required libs were installed, extras were required as per the secondary link.  There was qt4-linguist installed, but that wasn't relevant.

**Comment by TheZ3ro** [comment]
The page you are linking [1] is a general-purpose page, dependencies are listed by "common" name (as you can see it's listed _Qt_). Various OS/distro have different names for packages listed there.
 
Then the second step in [1] is **Preparing the building environment** [2] that is linking to environment-specific guide like [3] (that @droidmonkey linked before) where dependencies are listed for each GNU/Linux distribution that we officially support with _proper_ package name.

To me seems that the wiki is right and there is no need to change anything.


[1] https://github.com/keepassxreboot/keepassxc/wiki/Building-KeePassXC
[2] https://github.com/keepassxreboot/keepassxc/wiki/Building-KeePassXC#preparing-the-building-environment
[3] https://github.com/keepassxreboot/keepassxc/wiki/Set-up-Build-Environment-on-Linux

**Comment by droidmonkey** [comment]
I'll make it a little clearer, but that flow will remain

**Comment by affinityv** [comment]
Thanks, that is much clearer now.

**Comment by affinityv** [comment]
... but, perhaps separate the options, Auto-Type and YubiKey?
Most people, I expect, would prefer at least Auto-Type, but if they don't have a Yubikey, then they won't need those libs.

Although, installing all libraries and excluding unwanted options with cmake might be okay too.
The README.MD has a different cmake options than what is shown on the building wiki page.  The README.MD has more details about how to exclude options, but nothing about where to install (DESTDIR).

**Comment by droidmonkey** [comment]
Technically DESTDIR is not preferred, i was considering replacing that with -DCMAKE_INSTALL_PREFIX=...

**Comment by affinityv** [comment]
@droidmonkey Okay, then "fix" the README.MD and other places?
