### ISSUE TITLE
UUID of parent items is moved to non-referenced cloned items

### ISSUE THREAD

**Issue by Mi1an** [keepassxreboot/keepassxc#10150]
## Overview
Cloned item with the action "Clone Entry" does contain UUID of the source item. The source item UUID is changed.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Create a random item. Let's call it "Parent Item".
2. Create a referenced child item by clicking on "Clone Entry" within the "Parent Item".
4. Check "Append ' - Clone' to title" + "Replace username and password with references" from "Clone Entry Options".
5. Create another child item (this time not referenced) by clicking on "Clone Entry" within the "Parent Item".
6. Check "Append ' - Clone' to title" from "Clone Entry Options".

## Expected Behavior
The expected behavior is that UUID of the "Parent Item" will not change after cloning non-referenced entry.

## Actual Behavior
The UUID on the "Parent Item" has changed. The UUID is moved to cloned non-referenced entry. The referenced entry created in the step 2. is now pointing to a cloned non-reference item instead of "Parent Item".

## Context
This behavior is not logical. If I have multiple referenced parent items and I want to clone them to create another referenced parent items the UUIDs are changed and the whole system of references is broken.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.6
Revision: dd21def

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows
Windowing System: 11

**Comment by droidmonkey** [comment]
That is definitely not how the code works, try your steps again I think you got confused.

**Comment by Mi1an** [comment]
You are right. I have tried it now multiple times and the behavior is correct. I must have been really confused because it happened 3 times.
