### ISSUE TITLE
Database file extension corrupted

### ISSUE THREAD

**Issue by StarMoonPlanet** [keepassxreboot/keepassxc#10153]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

Have been loading database files from icloud drive successfully for several months to keep them in sync across devices. However after restoring phone from backup, the files look corrupted. Instead of the standard .kdbx file, the extensions are gibberish like . lWQEyC (different for each database file)

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Move database to icloud drive
2. Backup phone and restore from backup using mac laptop/iphone
3. Database files are corrupted, and icloud archives files, while working, are 6+ months out of date

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Expect to be able to open the database files, or recover them somehow

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Can't open the files at all. Keepassxc doesn't recognise them as valid databases

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.6
Revision: dd21def

Qt 5.15.10
Debugging mode is disabled.

Operating system: macOS 14.1
CPU architecture: arm64
Kernel: darwin 23.1.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 2.19.3

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS

**Comment by droidmonkey** [comment]
Sounds like a problem with icloud or your backup methods. What you are seeing are the temporary files used in the middle of saving. However there will always be an actual kdbx file as well. This isn't a keepassxc issue, check your backups again.

**Comment by StarMoonPlanet** [comment]
Where would I find the kdbx files? I've checked multiple backups (both time machine and manual). The folder where I've been saving the kdbx files only contains those temporary files, and nothing else

**Comment by droidmonkey** [comment]
Unfortunately that would mean you were not backing up your kdbx files or that wasn't actually where you were saving them.

**Comment by StarMoonPlanet** [comment]
I mean, I understand that that's what it sounds like. But I have been using the kdbx files daily for 11 months. I checked they were saving correctly, and I was able to open them and add entries on ios & osx. It also doesn't really make any sense to me that keepassxc would save temporary files there, but not the database files. Like, they've obviously been saved somewhere - I know it was icloud drive, but if something changed it, then I should still be able to find them/recover them, no?

**Comment by droidmonkey** [comment]
You can try this https://support.apple.com/guide/icloud/recover-deleted-files-mmae56ea1ca5/icloud

We use a fail-safe saving method (also called atomic save) that writes your database to a temporary file then renames that to your actual kdbx file when done. This ensures no data loss in the event of a crash or power outage or whatever.

At the end of the day, storage of your kdbx file is your responsibility and it's impossible for us to know what occurred on your computer or icloud.
