### ISSUE TITLE
Allowing mass export without a password IS a security risk

### ISSUE THREAD

**Issue by andr222** [keepassxreboot/keepassxc#10157]
In terms of ease of use, how difficult is it for a user to enter the encryption password for mass export ?
Without requiring a password for mass export, how would keepassxc be more secure than a simple open encrypted openoffice/libreoffice file ?
What would be the security advantage of keeppassxc ?

Sure, there are workarounds for exporting, but why make it easier for crackers ?

**Comment by droidmonkey** [comment]
One major barrier, you need to unlock the database in the first place. Lock it when you aren't using it, we offer plenty of options. This is well discussed elsewhere in the issue board.
