### ISSUE TITLE
Warning no OTP found

### ISSUE THREAD

**Issue by theking2** [keepassxreboot/keepassxc#10158]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. logon to a totp protected site
2. auto enter un and pw
3. click Fill OTP in the otp screen

## Expected Behavior
the otp is entered

## Actual Behavior
a message appears WARNING! no TOTP found

## Context

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.6
Revision: ?

[NOTE]: # ( Pick choices based on your environment )
Operating System: Fedora
Desktop Env: Gnome
Windowing System: Wayland

**Comment by droidmonkey** [comment]
That would mean you didn't define a totp for the entry associated with that website. You'll have to provide way more info to convince me this is an actual problem on our end. I use totp all the time with the browser extension.

**Comment by theking2** [comment]
![image](https://github.com/keepassxreboot/keepassxc/assets/1612152/9e9a50a3-1120-42a1-a74d-43ad561cb2e1)


I did

**Comment by droidmonkey** [comment]
Check the url where the totp is being requested. Is it the same as the entry url? You may also have to refresh the page if you just added the totp at the same time as requesting it again.
