### ISSUE TITLE
TOTP not working

### ISSUE THREAD

**Issue by theking2** [keepassxreboot/keepassxc#10159]
Overview
Steps to Reproduce

    logon to a totp protected site
    auto enter un and pw
    click Fill OTP in the otp screen

Expected Behavior

the otp is entered
Actual Behavior

a message appears WARNING! no TOTP found
Context

KeePassXC - 2.7.6
Revision: ?

Operating System: Fedora
Desktop Env: Gnome
Windowing System: Wayland

the TOTP was configured:
![image](https://github.com/keepassxreboot/keepassxc/assets/1612152/c0676e52-0c59-4ac3-b0a7-9bf7554a0357)

**Comment by droidmonkey** [comment]
Why did you open a new issue?
