### ISSUE TITLE
need to use auto-type in pop-up windows

### ISSUE THREAD

**Issue by Ludwig54** [keepassxreboot/keepassxc#10152]
## Overview
I use Sophos VPN client to connect to the server and like to use Auto-Type to enter the login information including TOTP.
When I open the VPN client, a pop-up windows shows-up. Now I switch to KeepassXC in order to start the autotype. Unfortunately by switching to KeepassXC to start the autotype the Sophos pop-up window disappears.

## Steps to Reproduce
1. start Sophos VPN client from the taskbar
2. switch to KeypassXC Autotype
3. Logon pop-up-windows disappears and the autotype goes anywhere

## Expected Behavior
This scenario works fine in Keepass this by using this auto-type string:
{DELAY 5000}{USERNAME}{TAB}{PASSWORD}{KTOTP}{ENTER}

(Obviously the {KTOPT} has been changed to {TOPT} in KeepassXC)

1) start the autotype by waiting 5 seconds!!! 
2) In the meantime I start sophos vpn connect 
3) click into the username field
4) this was enough time to wait and after 5 seconds the autotype continues to enter the strings in username and password fields 

## Actual Behavior
KeePassXC doesn't seem to realize that the "active window" has changed AFTER autotype was invoked.

## Context
KeePassXC should use the field where the mouse is positioned although this is not the active window, when the autotype started.
(The Sophos-window opened within the 5 seconds delay AFTER the autotype was started.)

Again, in Keepass this process works fine without any problems.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.6
Revision: dd21def

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows10/11
Desktop Env: Windowing System: Sophos VPN client

**Comment by droidmonkey** [comment]
Use global Auto-Type shortcut when the vpn credential window is in focus: https://keepassxc.org/docs/KeePassXC_UserGuide#_performing_global_auto_type
