### ISSUE TITLE
Error when saving database, challenge-response prompt fails to find my yubikey, "Writing the database failed: Unable to calculate database key"

### ISSUE THREAD

**Issue by Opening-Button-8988** [keepassxreboot/keepassxc#10160]
## Overview
I get this error when saving my database. `Writing the database failed: Unable to calculate database key: General: Could not find interface for hardware key with serial number <serialnumber>. Please connect it to continue.` Despite the same yubikey used to unlock the db is connected. Issue goes away once I close the application and open the database again with the same key.

## Steps to Reproduce
1. Open db
2. Make changes to the database
3. Save database 

## Expected Behavior
Challenge-response prompt should recognize key.

## Actual Behavior
Produces error: `Writing the database failed: Unable to calculate database key: General: Could not find interface for hardware key with serial number <serialnumber>. Please connect it to continue.`

## Context
I've experienced this error about half a dozen times in the last two-ish weeks. Recently started making some changes to my db, keeping the db open for extended periods (over an hour), occasionally disconnecting yubikey (5 Nano) and connecting other yubikey (5 NFC, same challenge-response credentials used to unlock db) and onlykey (not used to unlock db). Database is stored locally on an external drive. 

I had "automatically save after every change" disabled. Alternative saving method was enabled but I normally keep it off; after several failed save attempts, prompt asked me to disable safe saves which I allow (still didn't solve the problem), which I think enables this option and I forget to disable it later. I could be wrong.

Even when I'm not having this problem, the serial key of my yubikeys are never shown in such logs as `dmesg`, even though I enabled the relevant settings in the yubikey personalisation tool (button at startup, usb descriptor, api call).

As far as I know, there is no way to save my changes when this happens, so I lose them. Please advise if there is any possible way to save db even when this occurs, even saving to CSV as a worst-case scenario.

I believe this issue might be related: https://github.com/keepassxreboot/keepassxc/issues/7845#issue-1198951919

KeePassXC - Version 2.7.6
Revision: dd21def
Downloaded from fedoraproject.org via dnf

Operating system: Fedora Linux 39 (Workstation Edition)
CPU architecture: x86_64
Kernel: linux 6.6.8-200.fc39.x86_64
Desktop Env: Gnome 45.2
Windowing System: Wayland

**Comment by droidmonkey** [comment]
You cannot swap yubikeys once the database it unlocked with a certain key. Doesn't matter if they are "the same" with a shared secret. Please confirm you are absolutely 100% using the same exact key when you see this error. Based on your description you are swapping keys, maybe even unknowingly.

**Comment by Opening-Button-8988** [comment]
> You cannot swap yubikeys once the database it unlocked with a certain key. Doesn't matter if they are "the same" with a shared secret. Please confirm you are absolutely 100% using the same exact key when you see this error. Based on your description you are swapping keys, maybe even unknowingly.

I'm aware of this. I put the same key back in. To be sure, I used both keys. Neither of them are being recognized. I am 100% certain, I would bet my life on it. I only have two yubikeys, so it's not like I'm confusing them for others that are lying around.

I also put them in various USB ports. I normally use a usb hub; I put the same yubikey in the same hub, in the same usb port. I also put it in the usb port directly on the PC.

**Comment by Opening-Button-8988** [comment]
@droidmonkey Still an active issue.

**Comment by droidmonkey** [comment]
There isn't much I can say to this without replicating it myself. We have plenty of people using yubikeys without issue so this may unfortunately be an issue specific to your computer or Linux configuration.

**Comment by Opening-Button-8988** [comment]
> There isn't much I can say to this without replicating it myself. We have plenty of people using yubikeys without issue so this may unfortunately be an issue specific to your computer or Linux configuration.

You said this exact same thing for #9375. I'm not doing anything weird on my computer. I don't think it would be appropriate to consider something non-reproducible if you don't actually try to reproduce it. This is actually a serious bug that prevents users from saving their progress, this ~~can~~ will lead to data loss.

If there's absolutely nothing you can do beyond attempting to reproduce my environment, I will see if I can identify the problem myself. Might take a while though.

**Comment by droidmonkey** [comment]
That's the nature of software, especially on Linux. There are a lot of variables and oftentimes the issue is not with the program experiencing the symptoms.

**Comment by smnkgv** [comment]
Same here. I cannot lock my database with either of my keys. MacOs 15.0 (24A335), keepassxc 2.7.9. Note: I have been doing that successfully for many months with no problems whatsoever.

**Comment by smnkgv** [comment]
Very unexpectedly, I found a working "fix": go to database -> database security, then in the "challenge-response" section, click on the "Change Challenge-Response" - it will force keepassxc to detect the key. Don't actually change the Challenge-Response; close the settings section, and try locking the DB.

**Comment by kalingibbons** [comment]
Same problem on Win 10 @droidmonkey . Thank God @smnkgv had a working fix. This was driving me crazy. I left my OnlyKey Duo plugged in and unlocked the entire time. Only reproducible if the database times out while an entry is open for editing.

KeePassXC - Version 2.7.9
Revision: 8f6dd13

Qt 5.15.11
Debugging mode is disabled.

Operating system: Windows 10 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.19045

Enabled extensions:
- Auto-Type
- Browser Integration
- Passkeys
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 3.1.1

**Comment by droidmonkey** [comment]
> Only reproducible if the database times out while an entry is open for editing.

Can you clarify this sentence please?

**Comment by kalingibbons** [comment]
Can do @droidmonkey 

Steps to reproduce (keeping the unlocked OnlyKey or other HMAC key in the USB port):

1. Within a KeepassXC database navigate to Tools -> Settings - [x] Lock database after inactivity of 30 sec
4. Type a dummy edit into the note field of any entry, but don't apply the edits for 31 seconds
5. Hit cancel when prompted to discard changes
6. Apply your changes then try to save

**Comment by droidmonkey** [comment]
I cannot replicate this on develop branch:

https://github.com/user-attachments/assets/4004f973-fa22-4e2d-8266-4a0b2594549b

**Comment by kalingibbons** [comment]
I tried it on my laptop and couldn't get it to reproduce when using my camera for Windows Hello quick unlock, but got it to happen again after having Win 11 forget my face in Windows Hello settings. Maybe it's related to using a PIN for quick-unlock?

I tested it some more, and need to add a step zero where you  unlock and then relock the database once before it occurs. I completely exited KeepassXC, then launched it and unlocked, hit the lock button with my mouse, and then went through the above steps using PIN quick unlock. I haven't switched the face recognition back on to try it again.

KeePassXC - Version 2.7.9
Revision: 8f6dd13

Qt 5.15.11
Debugging mode is disabled.

Operating system: Windows 11 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.22631

Enabled extensions:
- Auto-Type
- Browser Integration
- Passkeys
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 3.1.1

**Comment by droidmonkey** [comment]
Quick unlock has nothing to do with saving the database. That code is only ever executed on unlock. Also we have no idea if you are doing pin or face unlock, that is 100% on windows side. 

You should run a snapshot build to see if you can replicate: https://snapshot.keepassxc.org

**Comment by kalingibbons** [comment]
Cool, I was just trying to supply you with additional details from a user
perspective because this is your codebase, not mine.

Please try to replicate on your end with the updated instructions, using
the quick unlock of your choice, then contribute something useful to this
conversation. Perhaps you could piggy back off the quick-fix the other user
found, and make some conjectures about why the HMAC key seems to time out
and then needs refreshing in a settings menu?

Now hear me out, I know it's a suuuuuuper duuuper long shot and nigh
impossible that some other part of the codebase could have a trickle down
effect in saving the database, but could it be that the process of
unlocking and relocking the database (which does use these keys) somehow
affects subsequent save attempts (where the keys are once again required)?

**Comment by droidmonkey** [comment]
You can (please) help by trying the snapshot build to see if you can replicate on current code. I can't spend all day chasing ghosts.

**Comment by kalingibbons** [comment]
I should be able to do that, this week 👍🏻

**Comment by droidmonkey** [comment]
FWIW I tried with your step 0 and using pin quick unlock and couldn't reproduce any anomalous behavior.

**Comment by Opening-Button-8988** [comment]
I haven't had this issue for many months, on the same system. If I do end up getting it again I'll try to help out by reproducing it on the snapshot builds. Under normal usage (rarely make changes to the database and when I do its quick), this doesn't occur. But I was having the issue when I was making frequent changes or having database open for long periods of time. It might have also been happening when I had an OnlyKey and Yubikey inserted at the same time, might've mentioned that already.

**Comment by siddhpant** [comment]
I faced the issue after redirecting yubikey to a VM.

Steps would be something like:

- Create a VM in virt-manager GUI.
- Open the VM.
- Use the "Redirect USB" option to redirect the yubikey to it.
- Un-redirect the yubikey / close the VM.
- Try saving in keepassxc and see the error.
- Open a text editor and touch yubikey to verify the host is able to use it.

Restarting keepassxc doesn't work. I had to physically remove my yubikey and reattach it, then when I started keepassxc it showed up there.

**Comment by siddhpant** [comment]
This is reproducible with the above steps in the develop build I'm running.

**Comment by siddhpant** [comment]
I see `Hardware key USB error: Access denied (insufficient permissions)`

**Comment by siddhpant** [comment]
Hmmm so redirection -> unredirection causes some perm removal issue and the unredirection doesn't restoring perms causing this.

The fix seems to be checking whether uaccess is there and our user has the perms, and if not, generate an event which will recalculate perms it seems.

```
$ dev="/dev/bus/usb/008/009"  # Something

$ ykinfo -s
USB error: Access denied (insufficient permissions)

$ udevadm info -q property -n "$dev" | grep -E '^(TAGS|CURRENT_TAGS|ID_SECURITY_TOKEN|ID_SEAT)='
ID_SECURITY_TOKEN=1
TAGS=:systemd:uaccess:seat:security-device:
CURRENT_TAGS=:security-device:uaccess:seat:systemd:

$ getfacl "$dev"
getfacl: Removing leading '/' from absolute path names
# file: <dev>
# owner: root
# group: pcscd
user::rw-
group::rw-
mask::rw-
other::---

$ sudo udevadm trigger --action=change "$dev"
$ sudo udevadm settle

$ getfacl "$dev"
getfacl: Removing leading '/' from absolute path names
# file: <dev>
# owner: root
# group: pcscd
user::rw-
user:<MY USER>:rw-
group::rw-
mask::rw-
other::---

$ ykinfo -s
serial: <something>
```

Since generating event is privileged, keepassxc should show the correct error message in GUI and also probably remediation steps.
