### ISSUE TITLE
Keepass freezing after opening any database

### ISSUE THREAD

**Issue by csekrohu** [keepassxreboot/keepassxc#10167]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
Memory usage is increasing infiniatly.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1.  Start keepass
2. Create or open any db
3. 

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.4, 2.7.6
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows server 2019

**Comment by droidmonkey** [comment]
Did you set custom encryption settings? This isn't a problem reported by anyone else. Also try updating the MSVC support libraries: https://aka.ms/vs/17/release/vc_redist.x64.exe
