### ISSUE TITLE
KeePassXC crashes on Windows 10 when opening an existing database

### ISSUE THREAD

**Issue by jansoft** [keepassxreboot/keepassxc#10162]
## Overview
KeePassXC crashes when opening an existing database

## Steps to Reproduce
1. Open KeePassXC on Windows 10
2. Select 'Open existing database' and a file selection dialog is shown
3. Try to select a file or do nothing

## Expected Behavior
I can select a database file and open it.

## Actual Behavior
I get the following error message and the app closes.

---------------------------
Visual Studio Just-In-Time Debugger
---------------------------
An unhandled win32 exception occurred in [4644] KeePassXC.exe. Just-In-Time debugging this exception failed with the following error: No installed debugger has Just-In-Time debugging enabled. In Visual Studio, Just-In-Time debugging can be enabled from Tools/Options/Debugging/Just-In-Time.

Check the documentation index for 'Just-in-time debugging, errors' for more information.
---------------------------
OK   
---------------------------

## Context

Operating System: Windows 10

**Comment by droidmonkey** [comment]
Unfortunately, there is nothing we can do without more information. Try using a snapshot build to see if this is fixed already (https://snapshot.keepassxc.org). You can also try downgrading to an older version and try re-saving your database. If you can provide more context and try different options we can reopen.

**Comment by jansoft** [comment]
I installed the latest snapshot.
https://snapshot.keepassxc.org/latest/KeePassXC-2.8.0-snapshot-Win64.msi

Same behavior. I try to select a file and the application closes.

I will use another app and maybe try KeePassXC later this year again.

Kinds regards,
Jan Verhoeven.

Op ma 8 jan 2024 om 18:04 schreef Jonathan White ***@***.***>:

**Comment by ericinca** [comment]
Having a similar issue.  When I get the file selection dialog, it crashes after about one second.  I don't even have enough time to open a database.

Windows 10
KeePassXC 2.7.6 from the Microsoft store
