### ISSUE TITLE
Drop to background when copying to clipboard doesn't work

### ISSUE THREAD

**Issue by ep-dd** [keepassxreboot/keepassxc#10171]
## Overview
The Entry Management setting 'HIde window when copying to clipboard/Drop to background' minimizes the main window.

## Steps to Reproduce
1. Under Settings: Entry Management, select 'Hide window when copying to clipboard' and then 'Drop to background'
2. Select an entry and copy the username or password, using the toolbar buttons or the shortcut keys. Or use autotype.

## Expected Behavior
The KeepassXC window should drop to the background and focus should shift to the most recently active window, where you can either paste from the clipboard or see the autotype.

## Actual Behavior
The main window is minimized instead of dropping to the background. This happens in both Windows and MacOS.

## Context

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.6
Revision: dd21def

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 10, version 22H2
Operating System: macOS Ventura 13.6.3

**Comment by droidmonkey** [comment]
I cannot replicate this at all on either windows or Mac. This setting does not apply to Auto-Type, only copy to clipboard.
