### ISSUE TITLE
"Show passwords in color" should work anywhere they appear

### ISSUE THREAD

**Issue by JVimes** [keepassxreboot/keepassxc#10170]
## Summary

"Show passwords in color" seems to work only in Preview Panel. Suggest it work anywhere a password is visible, for example the entry add/edit views and main view.

## Context

I don't usually use Preview Panel.

**Comment by droidmonkey** [comment]
After experimenting with showing colors in edit fields, we decided against that. It doesn't work very well. There is another open issue to request viewing a password in larger font and colors as a popup window. That is what we would prefer as an option to the preview panel.

**Comment by JVimes** [comment]
@droidmonkey Thank you. You might change checkbox label to "Show passwords in color (Preview Panel)" or something like that.
