### ISSUE TITLE
keepassxc-proxy should live in /usr/libexec not /usr/bin

### ISSUE THREAD

**Issue by julian-klode** [keepassxreboot/keepassxc#10172]
I don't think the template is useful here, so here we go:

Essentially the thing is that /usr/bin is for applications used by the user, daemons like this proxy should live in libexec, either /usr/libexec/keepassxc-proxy directly or below /usr/libexec/keepassxc (or /usr/lib/keepassxc).

I don't know how much issues this creates, presumably the native messaging host needs updates to look in that path.

**Comment by julian-klode** [comment]
Actually keepassxc already uses /usr/lib/keepassxc (or `/usr/lib/x86_64-linux-gnu/keepassxc` here) this can also be the right path, but may be hard to find especially the multi-arch Debian paths, libexec is more modern.

**Comment by droidmonkey** [comment]
Proxy is not a daemon. It is run as a subprocess by the browser. If package maintainers think this is important to change they can do it as part of their packaging. I see absolutely no reason to make this change.
