### ISSUE TITLE
Advanced Settings Box Bug

### ISSUE THREAD

**Issue by ghost** [keepassxreboot/keepassxc#10174]
## Overview
Very minor bug, breaks nothing, but it exists.
Clicking on the security > advanced encryption and then clicking off still leaves the advanced settings box to be checked and not grayed out.

## Steps to Reproduce
1. Go to Security > Encryption Settings
2. Click on any other setting on the side
3. Advanced settings box is still able to be checked

## Expected Behavior
After clicking off of security from encryption settings, advanced settings box grays out again.

## Actual Behavior
Advanced settings box is able to be checked in other windows where the box is not required.

KeePassXC - Version 2.7.6
Revision: dd21def

Qt 5.15.10
Debugging mode is disabled.

Operating system: Windows 11 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.22631

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 2.19.3

Operating System: Windows

**Comment by droidmonkey** [comment]
This is removed for 2.8.0
