### ISSUE TITLE
"Error! No logins found" on some previously working sites after update to 2.7.6

### ISSUE THREAD

**Issue by Shuggaloaf** [keepassxreboot/keepassxc#10185]
## Overview
As the title states I am getting the error since updating. It doesn't happen on all sites but it's happening on more than just 1. 

The extact URL is listed in browser integration (and verified to not be mispelled). This has been working without issue and no changes have been made to any credentials. 

## Steps to Reproduce
For me, it's just try to login and get the error message.

## Context
One example to verify that exact URL exists:
<img src="https://github.com/keepassxreboot/keepassxc/assets/79543184/74077de6-d63e-41aa-a5d5-10ab21241187" width = "50%"/>

<img src="https://github.com/keepassxreboot/keepassxc/assets/79543184/630f32bc-45ac-4b8d-8a07-ed09d53d6a58"  width = "50%"/>

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.6
Revision: dd21def

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows10 64

**Comment by droidmonkey** [comment]
What version did you upgrade from?

**Comment by jjohnson1024** [comment]
I came here looking for this same thing. Things started breaking for me yesterday.

Looks related to a change in the browser extension: https://github.com/keepassxreboot/keepassxc-browser/issues/2076

**Comment by Shuggaloaf** [comment]
@droidmonkey Fairly certain it was 2.7.4

@jjohnson1024 I couldn't say for sure. The error message is different but I'm not versed enough in KPXC's operation to understand if they're related.

**Comment by varjolintu** [comment]
This is possibly affected by the change in the extension. It will be improved later.

**Comment by droidmonkey** [comment]
Yah likely that one, this is not a KeePassXC app problem, extension problem.

**Comment by Shuggaloaf** [comment]
> Yah likely that one, this is not a KeePassXC app problem, extension problem.

Can you clarify this a bit. Is the extension not the same devs? Is there another repo I would need to bring this error up in? A little more info with closing this issue would be appreciated.
