### ISSUE TITLE
Autotype not working for custom build

### ISSUE THREAD

**Issue by thommw** [keepassxreboot/keepassxc#10188]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
Autotype does not work in my custom build. I have build the app for macos with limited features and codesigned with my own developer certificate. 

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. open database
2. select in input field in browser
3. start autotype for any entry to send the username

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
It should switch focus back to the browser and autotype the username into the input field.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
It opens two dialogs, one fromKeppassXC and one system dialog. The Keepass dialog says:

_**KeePassXC requires the Accessibility permission in order to perform entry level Auto-Type. If you already granted permission, you may have to restart KeePassXC.**_

The Accessibility Access system dialog says:

**_"KeePassXC.app" would like to control this computer using accessibility features. Grant access to this application in Privacy & Security settings, located in System Settings._**

## Context
[NOTE]: # ( Give us any additional information you may have. )
I have granted the permission before, which it does not seem to recognize. Restarting the app results in the same warning dialogs. It only gives the warnings the first time you use the autotype feature after the app has started. For subsequent invocations of autotype nothing at all happens.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.6
Revision: dd21def

Qt 5.15.12
Debugging mode is disabled.

Operating system: macOS 14.1
CPU architecture: arm64
Kernel: darwin 23.1.0

Enabled extensions:
- Auto-Type
- Browser Integration
- Quick Unlock

Cryptographic libraries:
- Botan 2.19.3

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS
Desktop Env: 
Windowing System:

**Comment by droidmonkey** [comment]
You need to fully remove the permissions in the accessibility panel for KeePassXC,  then re add them manually. This is a macos bug they haven't fixed yet. The permissions get stuck on a particular instance of the app and won't transfer to a new one.
