### ISSUE TITLE
process keepassxc is hidden from executing user

### ISSUE THREAD

**Issue by moerkey** [keepassxreboot/keepassxc#10194]
> I found, that the most (but not all) contents of `/proc/<pid>` are owned by root, which explains the `Permission denied` errors. If i start any other regular user process its `/proc/<pid>` is owned by the user.

_Originally posted by @simonmarwitz in https://github.com/keepassxreboot/keepassxc/issues/9799#issuecomment-1696881244_

That is exactly my current question. Why is the process hidden by root or why is root owning the files in /proc/ProcessId? I am only able to see and kill the process on cli via root.

**Comment by droidmonkey** [comment]
We don't control any of that.  Refer to your system documentation.

**Comment by moerkey** [comment]
I am sorry but this answer is not very satisfying. I try it again. Under Linux Ubuntu 22.04 with Kernel 6.5.0-14-generic I start i.e. Firefox as an user and all files under /proc are owned by that user. That is the normal behaviour. But when I start keepassxc only 4 files are owned by that user. All other files are owned by root. I think you should know why this is the case.

```
user@host:~$ sudo ls -lh /proc/263202 | grep -v "root root"
total 0
dr-xr-xr-x  2 user user  0 Jan 14 19:26 attr
dr-xr-xr-x  2 user user  0 Jan 14 19:26 fdinfo
dr-xr-xr-x 44 user user  0 Jan 14 19:26 net
dr-xr-xr-x 10 user user  0 Jan 14 19:26 task
```

```
user@host:~$ sudo ls -lh /proc/263202 
total 0
-r--r--r--  1 root root  0 Jan 14 19:26 arch_status
dr-xr-xr-x  2 user user  0 Jan 14 19:26 attr
-rw-r--r--  1 root root  0 Jan 14 19:26 autogroup
-r--------  1 root root  0 Jan 14 19:26 auxv
-r--r--r--  1 root root  0 Jan 14 08:37 cgroup
--w-------  1 root root  0 Jan 14 19:26 clear_refs
-r--r--r--  1 root root  0 Jan 14 08:37 cmdline
-rw-r--r--  1 root root  0 Jan 14 19:26 comm
-rw-r--r--  1 root root  0 Jan 14 19:26 coredump_filter
-r--r--r--  1 root root  0 Jan 14 19:26 cpu_resctrl_groups
-r--r--r--  1 root root  0 Jan 14 19:26 cpuset
lrwxrwxrwx  1 root root  0 Jan 14 19:26 cwd -> /home/user
-r--------  1 root root  0 Jan 14 19:26 environ
lrwxrwxrwx  1 root root  0 Jan 14 08:37 exe -> /usr/bin/keepassxc
dr-x------  2 root root 39 Jan 14 08:45 fd
dr-xr-xr-x  2 user user  0 Jan 14 19:26 fdinfo
-rw-r--r--  1 root root  0 Jan 14 19:26 gid_map
-r--------  1 root root  0 Jan 14 19:26 io
-r--------  1 root root  0 Jan 14 19:26 ksm_merging_pages
-r--------  1 root root  0 Jan 14 19:26 ksm_stat
-r--r--r--  1 root root  0 Jan 14 19:26 limits
-rw-r--r--  1 root root  0 Jan 14 19:26 loginuid
dr-x------  2 root root  0 Jan 14 19:26 map_files
-r--r--r--  1 root root  0 Jan 14 19:26 maps
-rw-------  1 root root  0 Jan 14 19:26 mem
-r--r--r--  1 root root  0 Jan 14 19:26 mountinfo
-r--r--r--  1 root root  0 Jan 14 19:26 mounts
-r--------  1 root root  0 Jan 14 19:26 mountstats
dr-xr-xr-x 44 user user  0 Jan 14 19:26 net
dr-x--x--x  2 root root  0 Jan 14 19:26 ns
-r--r--r--  1 root root  0 Jan 14 19:26 numa_maps
-rw-r--r--  1 root root  0 Jan 14 19:26 oom_adj
-r--r--r--  1 root root  0 Jan 14 19:26 oom_score
-rw-r--r--  1 root root  0 Jan 14 19:26 oom_score_adj
-r--------  1 root root  0 Jan 14 19:26 pagemap
-r--------  1 root root  0 Jan 14 19:26 patch_state
-r--------  1 root root  0 Jan 14 19:26 personality
-rw-r--r--  1 root root  0 Jan 14 19:26 projid_map
lrwxrwxrwx  1 root root  0 Jan 14 08:37 root -> /
-rw-r--r--  1 root root  0 Jan 14 19:26 sched
-r--r--r--  1 root root  0 Jan 14 19:26 schedstat
-r--r--r--  1 root root  0 Jan 14 19:26 sessionid
-rw-r--r--  1 root root  0 Jan 14 19:26 setgroups
-r--r--r--  1 root root  0 Jan 14 19:26 smaps
-r--r--r--  1 root root  0 Jan 14 19:26 smaps_rollup
-r--------  1 root root  0 Jan 14 19:26 stack
-r--r--r--  1 root root  0 Jan 14 08:37 stat
-r--r--r--  1 root root  0 Jan 14 19:26 statm
-r--r--r--  1 root root  0 Jan 14 19:25 status
-r--------  1 root root  0 Jan 14 19:26 syscall
dr-xr-xr-x 10 user user  0 Jan 14 19:26 task
-rw-r--r--  1 root root  0 Jan 14 19:26 timens_offsets
-r--r--r--  1 root root  0 Jan 14 19:26 timers
-rw-rw-rw-  1 root root  0 Jan 14 19:26 timerslack_ns
-rw-r--r--  1 root root  0 Jan 14 19:26 uid_map
-r--r--r--  1 root root  0 Jan 14 19:26 wchan
```

**Comment by droidmonkey** [comment]
Probably because we disable core dumps. Why does this matter anyway? You can definitely kill the keepassxc process without being root.

**Comment by moerkey** [comment]
No, unfortunately I can not because the normal user can not see the process. The user has no access to the corresponding PID folder in /proc. I want to kill it without using sudo :)

```
user@host:~$ pidof keepassxc
user@host:~$ sudo pidof keepassxc
263202
user@host:~$ sudo ps aux | grep 263202
user      263202  0.0  0.9 996656 157024 ?       SLl  08:37   0:05 /usr/bin/keepassxc ...
user      302599  0.0  0.0   9568  2688 pts/0    S+   19:50   0:00 grep --color=auto 263202
user@host:~$ ls /proc/263202
ls: cannot access '/proc/263202': No such file or directory
user@host:~$ sudo ls /proc/263202
arch_status  comm		 fd		    loginuid	net	       patch_state  setgroups	  syscall
attr	     coredump_filter	 fdinfo		    map_files	ns	       personality  smaps	  task
autogroup    cpu_resctrl_groups  gid_map	    maps	numa_maps      projid_map   smaps_rollup  timens_offsets
auxv	     cpuset		 io		    mem		oom_adj        root	    stack	  timers
cgroup	     cwd		 ksm_merging_pages  mountinfo	oom_score      sched	    stat	  timerslack_ns
clear_refs   environ		 ksm_stat	    mounts	oom_score_adj  schedstat    statm	  uid_map
cmdline      exe		 limits		    mountstats	pagemap        sessionid    status	  wchan
```

**Comment by simonmarwitz** [comment]
As I was previously involved in the issue, I will share my current state here. I previously set up my system from scratch and I am now running Ubuntu 23.10. Everything works as expected and no need for flatpak or snap packages.
Also the mentioned command: `user@host:~$ pidof keepassxc` returns the pid for me. No need for sudo. Files unser `/proc/<pid>` are owned by user.

**Comment by moerkey** [comment]
Thank you very much. I have now tested it again myself on a fresh Ubuntu 22.04 and xUbuntu 22.04 and could not reproduce my problem. I.e. under normal circumstances the user can see the PID of KeePassXC and terminate the process via kill. I can't at the moment because /proc is mounted with hidepid=2. Actually I should be able to see the process anyway. But this only works with hidepid=0 (default). To summarize, it can be said that the deactivation of core dumps by KeePassXC (see above) in combination with hidepid does not work.

https://www.cyberciti.biz/faq/linux-hide-processes-from-other-users/

I solved it with gid: https://linux-audit.com/linux-system-hardening-adding-hidepid-to-proc/

**Comment by droidmonkey** [comment]
Sigh... hidepid=2 seems like an important bit of information you could have shared...

FWIW, we don't do anything special to hide core dumps, just setting the max dump size to 0. We also do some other hardening techniques that might be root cause of the difference in behavior.
