### ISSUE TITLE
kpxc 2.7.6 portable looses the settings

### ISSUE THREAD

**Issue by JeckPeppinger** [keepassxreboot/keepassxc#10191]
## Overview
kpx 2.7.6. does not remember the settings between boots on Windows 11.

## Steps to Reproduce
Install the PortableApps.com portable version of kpx.
Adjust the settings.
Reboot, and kpx does not remember the settings anymore.

## Expected Behavior
Settings should be remembered.
All worked well until the update from the previsous version to version 2.7.6.
Therefore assume this is a bug in keepassxc.

## Actual Behavior
Note, the issue is related to a reboot.
When quitting kpx and restarting it without reboot, the settings are remembered as should.
But when rebooting the system kpx seems to be completely fresh, not finding settings.

## Context
The automatic startup of kpx requires to switch on keepassxc in the Startup Applications via Windows settings.
The keepassxc setting "launch application on system startup" will not start keepassxc

KeePassXC - Version 2.7.6
Revision: dd21def

Qt 5.15.10
Debugging mode is disabled.

Operating system: Windows 11 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.22631

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 2.19.3

**Comment by droidmonkey** [comment]
We don't maintain the portable apps version. We offer a zip package that you can use for portable installs. Please file a bug with portable apps.
