### ISSUE TITLE
Cannot Open Database Stored on a Remote Server

### ISSUE THREAD

**Issue by S3ntago** [keepassxreboot/keepassxc#10193]
## Overview
Hello,

I wanted to open a Database that is stored on a remote server in my network and I cannot find any option to open Database using URL, this feature is available on KeePass2 Windows OS version but I cannot find it here with KeePassXC.

The only option available allow opening local database:
![image](https://github.com/keepassxreboot/keepassxc/assets/48615614/633042be-134a-41f4-a309-697a2eb90840)

This is the option I'm looking for same as the KeePass2 on Windows OS:
![image](https://github.com/keepassxreboot/keepassxc/assets/48615614/6ddc11dd-ee89-405b-a82a-32e8d0e09abb)

KeePassXC - 2.7.6

Operating System: macOS

**Comment by droidmonkey** [comment]
Follow #7222
