### ISSUE TITLE
Make KeePassXC function as a Background App.

### ISSUE THREAD

**Issue by LinuxBoy-96** [keepassxreboot/keepassxc#10192]
Make KeePassXC able to function as a background app, most likely mainly as a background app but without removing the option get the full window since it will be necessary to get all the features.

![Capture d’écran 2024-01-14 003645](https://github.com/keepassxreboot/keepassxc/assets/128245725/9b164a7e-ad86-4edd-bc6d-935730be2c40)
![Capture d’écran 2024-01-14 004120](https://github.com/keepassxreboot/keepassxc/assets/128245725/0dc4da26-771a-42a3-86ce-05e344de4895)

I personnaly often close open program by mistake and with KeePassXC, because of long passwords, this is really annoying.
I like my things to look clean and discrete; This can't be the case with a full size keepass open in my taskbar.

**Comment by droidmonkey** [comment]
Go to the application settings and scroll to the bottom. Enable tray icon and minimize to tray on close.
