### ISSUE TITLE
KeePassXC and Sticky Password

### ISSUE THREAD

**Issue by prince911** [keepassxreboot/keepassxc#10198]
![Screenshot 2024-01-15 024658](https://github.com/keepassxreboot/keepassxc/assets/24402355/1f239747-a770-4a67-a18f-cbe3ad01c4a0)
I want to use the KeePassXC , but the Sticky Password does not have a CSV option

I want to import passwords from XML, HTML, and TXT files to KeePassXC. Is this possible?

Thank for your understanding

**Comment by droidmonkey** [comment]
You'll have to export them as txt and convert to csv if you want to import. Otherwise copy/paste between programs.

**Comment by prince911** [comment]
i do that and no user and password show 
i change txt to csv mining change liter  and import csv nothing

**Comment by droidmonkey** [comment]
Changing the file extension won't help you, you have to actually create a CSV file from the text file. We do not provide support for this, please reference relevant articles on the internet to assist you.
