### ISSUE TITLE
No auto-type on Ubuntu 16.04 (with Auto-Type extension enabled)

### ISSUE THREAD

**Issue by qazip** [keepassxreboot/keepassxc#1019]
## Expected Behavior
I installed KeepassXC on Ubuntu 16.04 following the instructions in the read-me and used the default flags; Basically just copy pasted the commands. The Auto-Type tab in the settings menu does not exist, just "Basic Settings". 

## Debug Info
KeePassXC - Version 2.2.1
Revision: 2bce9c8add07226e9a05e9e0fd0e5e66b236d5b6

Libraries:
- Qt 5.5.1
- libgcrypt 1.6.5

Operating system: Ubuntu 16.04.3 LTS
CPU architecture: x86_64
Kernel: linux 4.11.0-14-generic

Enabled extensions:
- Auto-Type

**Comment by TheZ3ro** [comment]
Probably you are missing some dependency like `libxi libxtst`.

Have you followed this? https://github.com/keepassxreboot/keepassxc/wiki/Set-up-Build-Environment-on-Linux

**Comment by qazip** [comment]
Oh, sorry. I was missing some libraries indeed. My bad.
