### ISSUE TITLE
Long startup time

### ISSUE THREAD

**Issue by uivil** [keepassxreboot/keepassxc#10201]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
Keepassxc takes too much time to start. Why does it take a whopping 1.5 seconds to start such a simple UI?

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
time keepassxc

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
< 0.4sec

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
~1.5sec

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.6
Revision: dd21def

Qt 5.15.11
Debugging mode is disabled.

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 6.6.9-1-clear

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 3.2.0

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: None
Windowing System: X11

**Comment by droidmonkey** [comment]
Hard to say since that appears to be rather unique to your computer. You can try using a different distribution method like appimage or flatpak. 

1.5 seconds is hardly whopping...
