### ISSUE TITLE
Open Database feature on OS X

### ISSUE THREAD

**Issue by multiplexy** [keepassxreboot/keepassxc#1020]
Hello,

i used to keepassxc on Windows. nowadays i have started to use on Mac. But i cant find "open Database" feature on Mac version. my password file is on windows server. How can i connect windows server ?

**Comment by affinityv** [comment]
See this link [1], scroll down to the section for connecting from Mac OS X.

[1] http://www.techrepublic.com/blog/linux-and-open-source/how-do-i-connect-a-mac-os-x-machine-to-a-samba-share/

**Comment by phoerious** [comment]
It's in the global OS X menu.
