### ISSUE TITLE
Add expiration preset "Same as last time"

### ISSUE THREAD

**Issue by ntevenhere** [keepassxreboot/keepassxc#10204]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
After renewing a password it is common to want to set the same expiration duration as last time. 

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )
A menu item under the Presets menu like this:
`Repeat (5 months)`
(In the case the last expiration duration was 5 months)

## Context

Currently I have to write down the usual duration in the Notes for the entry so I can remember to set it again when it expires.
This button could also save time for setting non-preset durations, since you currently can't customize presets (#6800)

**Comment by droidmonkey** [comment]
See #6456, this will be implemented for 2.8.0
