### ISSUE TITLE
Purge temporary attachment files upon database lock

### ISSUE THREAD

**Issue by Roheed05** [keepassxreboot/keepassxc#10208]
Hello everyone, 

I think i have discovered an issue with KeePassXC. When you add an attachment to an entry, like a Microsoft Word file you want to securely store, KeePassXC opens the file and creates a copy, with random name in the Windows Temp folder to display it. When you close the file, it should be deleted from the system as usual. So far, so good.

However, if you have the file open and KeePassXC automatically closes the database in the background due to selected settings, the file is not deleted anymore and remains in the TEMP folder indefinitely. Upon reopening the attachment, another copy is created, and so on. Depending on the sensitivity of the file/Word document content, this behavior can be somewhat risky in my opinion. 

What do you think? 

Tested on latest KPXC version (V2.7.6) with Windows 10.

**Comment by droidmonkey** [comment]
The files are cleaned up when KeePassXC is closed. I do agree that should occur on database lock instead.

**Comment by Roheed05** [comment]
hello Droidmonkey, thank you for the fast answer! but i must contradict you. I tested before and KPXC didn't even delete the Files after i closed KPXC (right click, close app). EDIT:::: _Open an attachment, lock the database, Close the attachment, close KPXC and the file exist further...over days and restart the pc and so on_ 


![Unbenannt](https://github.com/keepassxreboot/keepassxc/assets/156905217/f075cfb2-b07b-45e2-9d0a-bf8db2f04360)

**Comment by Roheed05** [comment]
I use the Windows version....V2.7.6. testet on two sperate PC's. Same issue

Am Mi., 17. Jan. 2024 um 13:35 Uhr schrieb Jonathan White <
***@***.***>:
