### ISSUE TITLE
Why KeePassXC has much slower search than KeePassX?

### ISSUE THREAD

**Issue by mindey** [keepassxreboot/keepassxc#10212]
After I've moved to Debian 12, so I tried `KeePassXC`, and what I found is that my passwords database of 2K entries, became so slow to search, that it's annoying. First 3 characters are found fast, but I have to wait for a second to get to the 4th character, and in addition, I became unable to search with plain string. The literal text search does not return the results. For example, I have a record with title `"github:mindey"`, but entering something like "github:mindey", doesn't return it at all! Now I have to spend time to formulate query something like `+ t:"github:mindey"` instead of simply typing. It would be great to have the search work fast, as it did before in KeePassX.

Perhaps making the search work fast like it did before, is to have `Search Preferences` in the configuration, and `an option to default` to literal byte search, so that one wouldn't have to use the `+ t:"...search text..."` syntax to be able to just search for some string of bytes.

**Comment by droidmonkey** [comment]
Update to 2.7.6, this was fixed

https://github.com/keepassxreboot/keepassxc/pull/9398
