### ISSUE TITLE
Set Up TOTP... Clears out all Add entry fields.

### ISSUE THREAD

**Issue by encbar5** [keepassxreboot/keepassxc#10217]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
At the moment I am using KeePassXC primarily for TOTP. The intuitive workflow for me was to create a new Entry, give it a Title, and then add the TOTP to the entry. This does not work, however, because somehow setting up a TOTP deletes all of the information in the new Entry. So as a workaround I'm forced to create the TOTP first, and then fill out the Title.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Click Entries -> New Entry
2. Fill out as many fields as you want (Title, Username, Password, URL, Tags, Notes)
3. Click Entries-> TOTP -> Set up TOTP...
4. Input a secret key
5. Click OK

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
The Add entry form still contains all of the data I entered in Step 2 above.
When I click OK on the Add entry form, a new entry is created with all of the data and the TOTP.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
The Add entry form has all of the fields cleared out. All of the data I already entered is lost.
If I click OK, a new entry is created but the only data it has is the TOTP.

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.6
Revision: dd21def

[NOTE]: # ( Pick choices based on your environment )
Operating System: Arch Linux
Desktop Env: None (Sway)
Windowing System: Wayland

**Comment by droidmonkey** [comment]
This is a duplicate report, fixed for next release: https://github.com/keepassxreboot/keepassxc/pull/9874
