### ISSUE TITLE
Searching for `hp' will cause matching errors.

### ISSUE THREAD

**Issue by zhl111** [keepassxreboot/keepassxc#10214]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

I want to search for hp printers, but the search results show the website `https://www.52pojie.cn/index.php`, which is probably triggered by the `hp` at the end. But my title is `hp` but it cannot appear          

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. 
2. 
3. 

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.76
Revision: dd21def

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows/Linux/macOS
Desktop Env: Gnome/KDE/XFCE/Mate/Cinnamon
Windowing System: X11/Wayland

**Comment by droidmonkey** [comment]
Use `t:hp` to scope your search to just the title
