### ISSUE TITLE
Add keyboard shortcuts to copy password from Auto-Type dialog

### ISSUE THREAD

**Issue by bee-eater** [keepassxreboot/keepassxc#10213]
I'm anywhere in a program and I want to get a password from the database. I don't want it to "auto type" it, I just want to get it to my clipboard with minimal key presses / keyboard2mouse switches! In my case I dont want to touch the mouse in order to copy the password from an entry I looked up in AutoTye.

In my worflow it seems tedious to grip the mouse again after finding the correct auto type entry. I just want to copy the password via ENTER / some hotkey. 

Since enter is currently occupied to trigger the auto type, an option would be one possibility (Dropdown in settings)

Enter key function:
["AutoType", "Copy Username", "Copy Password"] ...

Alternatively, predefine a hotkey to copy the password. (Passwords for the other functions are already predefined!)
Some nice onehander like CTRL+S/D/F.

Another option would be to make those AutoType context menu hotkeys configurable in the settings.

All solutions would be great for me!

**Comment by droidmonkey** [comment]
Use Ctrl+2 in the Auto-Type selection dialog to type password. 1 types username, 3 types totp.

**Comment by bee-eater** [comment]
@droidmonkey No, Ctrl+2 TYPES the password!! I want to have it in my clipboard!
(I'm talking about the global dialog, if that makes any difference...)

**Comment by droidmonkey** [comment]
Oh right, I believe Ctrl+Shift+2 copies it. You should be able to see the keyboard shortcuts in the drop down menu or right click menu.

**Comment by bee-eater** [comment]
Sure, but there is none for copying user / password! I'll try with shift!

**Comment by droidmonkey** [comment]
Yah you're right, those shortcuts haven't been implemented

**Comment by MohammedNoureldin** [comment]
I miss this feature also. Actually also a shortcut to show the hidden application would also be nice, but probably it is out of scope of this issue.

**Comment by HalibutGitWiz** [comment]
I'm interested in this feature as well.

With some windows, when you open an autotype popup and select an entry, the origin window does not get focus back properly and you end up autotyping your login and password somewhere else (or nowhere, in the best case). I don't think there is much KeepassXC can do to actually fix this, it must be related to how these third party applications work. Or it may be related to whatever window manager one uses (XFCE on Linux, in my case). But that's not the point of this issue, anyway.

Being able to copy username / password from the autotype popup would make it much easier to get around this behavior when it occurs.

**Comment by bee-eater** [comment]
I stopped my evaluation of XC and I'm back using KeePass again. The main reason was not this issue, but also there is no good option to run an external app via the url field. E.g. I'm using it to open SAP with my account data. Difference: in using KeePass you only have to provide the ID of the entry in the shortcut call (as long as the DB is unlocked). For XC if I remember correctly you always have to provide the DB password with the call, even if the DB already is unlocked. That totally ruins the point of it imho, since I would have to either enter the PW every time, or store it in the shortcut...

**Comment by 0x90shell** [comment]
I would also like to see this implemented. It would be pretty useful as I find myself copying, via mouse, more often than you'd expect. GPG entry windows capturing the screen are an example where it's useful to copy a password.
