### ISSUE TITLE
Unstable build warning for v2.7.6

### ISSUE THREAD

**Issue by tredondo** [keepassxreboot/keepassxc#10215]
## Overview
I've just compiled from the [2.7.6 ZIP source](https://github.com/keepassxreboot/keepassxc/archive/refs/tags/2.7.6.zip) on ChromeOS, and when launching `build/src/keepassxc`, I got this warning:

> "WARNING: You are using an unstable build of KeePassXC! There is a high risk of corruption, maintain a backup of your databases. This version is not meant for production use."

## Steps to Reproduce
1. wget https://github.com/keepassxreboot/keepassxc/archive/refs/tags/2.7.6.zip
2. unzip
3. mkdir build && cd build
4. cmake -DWITH_XC_UPDATECHECK=OFF -DWITH_TESTS=OFF -DWITH_XC_NETWORKING=OFF ..
5. make
6. build/src/keepassxc

## Expected Behavior
No warning, since this is a stable release

## Context
Built on Chrome OS (Ubuntu distro)

KeePassXC - Version 2.7.6-snapshot
Build Type: Snapshot

Qt 5.15.8
Debugging mode is disabled.

Operating system: Debian GNU/Linux 12 (bookworm)
CPU architecture: x86_64
Kernel: linux 6.1.60-08594-g03a802b9a072

Enabled extensions:
- Auto-Type

Cryptographic libraries:
- Botan 2.19.3

**Comment by droidmonkey** [comment]
You only get a "stable" build by checking out the git repository to a specific tag. You can also force a stable build by adding a text file called `.version` to the base folder and adding the desired version number to that file (in this case 2.7.6). You can also add a `.gitrev` file with the git revision hash (this only appears in the about menu).

**Comment by tredondo** [comment]
Thank you, I added `.gitrev` with the contents `15ac8ac4f89226c3a22bf9d6724b8222b099b847` (note to others: a trailing EOL output by `echo` caused compilation to fail, so I had to remove that manually), but I still see the warning:

![Image](https://github.com/user-attachments/assets/6cb049dc-633a-4d30-b55a-c94980da553c)

Anyway, after seeing [this](https://github.com/keepassxreboot/keepassxc/issues/6538) I feel comfortable just dismissing the warning.
