### ISSUE TITLE
Allow non-local config to include local config options

### ISSUE THREAD

**Issue by sertonix** [keepassxreboot/keepassxc#10211]
## Summary
If options should be considered local or ["roaming"](https://github.com/keepassxreboot/keepassxc/blob/884386c924192902dc9500a58f9cbdfe22a0a4fd/src/core/Config.cpp#L37) is a personal preference. Allowing the non-local config file to include local config options (used like default values) users can decide where they prefer the configuration. I consider that only useful for advanced users or system admins so I think it is ok to not provide a GUI for that.

## Examples
`export KPXC_CONFIG=/etc/keepassxc/config.ini`
```ini
[General]
UseAtomicSaves=false
UseDirectWriteSaves=true
```

## Context
I need `UseDirectWriteSaves=true` for the saving to work properly (backups are handled externally). I don't want to write my local config to disk though since it contains unnecessary data.

**Comment by droidmonkey** [comment]
You can already decide where to put the two config files, we use straight qt settings and cannot do anything fancy. We won't be implementing this.
