### ISSUE TITLE
Error while reading  the database: invalid inner header size

### ISSUE THREAD

**Issue by sheeshman123321** [keepassxreboot/keepassxc#10226]
So, today. i wanted to add a new account that i created, i opened keepassxc and clicked on my database, i enter my passphrase that i am sure its 100% right, and then, i get "Error while reading the database: invalid inner header size" I sadly did not keep any backups. This is also on a usb if that might have anything to do with it.

## Steps to Reproduce
No steps... it just happened.

## Expected Behavior
Just open the database.

## Actual Behavior
"Error while reading the database: invalid inner header size"

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.6.6
Revision: 9c108b9

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux Mint
Desktop Env: Cinnamon
Windowing System: X11

**Comment by sheeshman123321** [comment]
To be honest i am not sure if i should've labeled it as bug.

**Comment by droidmonkey** [comment]
> This is also on a usb if that might have anything to do with it

This is 100% the reason, unfortunately you now have a corrupt database file and there is nothing we can do about it. USB storage is notorious for causing these types of issues. 

You should also update to 2.7.6 before you make a new database.

**Comment by sheeshman123321** [comment]
Should i make the new database on my ssd?
@droidmonkey

**Comment by sheeshman123321** [comment]
And like, really nothing? dam, is there anything that i can do?

**Comment by droidmonkey** [comment]
There is really nothing you can do, that error is just the first that indicates actual no joke corruption. Even if you could fix that one, the likelihood the rest of the database file is just as corrupt is incredibly high. That error means we cannot figure out the decryption key for your database because the header (first X bytes of the file) are wrong.

**Comment by sheeshman123321** [comment]
Well about my first question, where should i save my new database?

**Comment by droidmonkey** [comment]
SSD (internal) is perfectly fine. Keep backups. We ultimately recommend using a cloud based or personally hosted file sync service. They usually keep backups for you automatically.

**Comment by sheeshman123321** [comment]
still really sad i lost access to my database, i guess it was my mistake for not keeping a backup

**Comment by sheeshman123321** [comment]
i guess its also a refresh because my old database was filled with accounts that i no longer use

**Comment by sheeshman123321** [comment]
> There is really nothing you can do, that error is just the first that indicates actual no joke corruption. Even if you could fix that one, the likelihood the rest of the database file is just as corrupt is incredibly high. That error means we cannot figure out the decryption key for your database because the header (first X bytes of the file) are wrong.

You know what... i want to see this one, how can i fix it? or is it really complicated? i want to see if the entire database was corrupted.

**Comment by droidmonkey** [comment]
Really complicated, but you could run keepassxc in a  debugger and step through the opening process (not help with that though). You could also open the kdbx in a hex editor to see if there are obvious things wrong with it.

**Comment by sheeshman123321** [comment]
i dont really know into this hex stuff man, I am not sure if i see any problems with it,GHex was not able to open the file but Bless was able to open it.
