### ISSUE TITLE
Allow specifying custom install directory to MSI installer for Windows

### ISSUE THREAD

**Issue by r3c** [keepassxreboot/keepassxc#10220]
## Summary

Would it be possible for KeePassXC to support install directory override for unattended install to copy files somewhere else than default `%PROGRAMFILES%` directory?

This can usually be achieved by passing an `INSTALLDIR` property to MSI when invoking `msiexec`. I reviewed the list of available options from unattended install [in documentation](https://keepassxc.org/docs/KeePassXC_GettingStarted#_microsoft_windows) but didn't find one about install directory, and it seems `INSTALLDIR` isn't implemented. By looking at https://github.com/keepassxreboot/keepassxc/blob/develop/share/windows/wix-template.xml it seems passing `INSTALL_ROOT` does the trick but I don't know how reliable it is as it's not specified in documentation nor seems standard.

Thank you for your advice.

## Examples

```
msiexec /package KeePassXC-2.7.6-Win64.msi INSTALLDIR=D:\KeePassXC\
```

## Context

Installing to default directory on system drive may not be a suitable option for some configurations.

**Comment by droidmonkey** [comment]
Use INSTALL_ROOT. There is no real standard for WIX, that variable actually comes from cmake cpack.
