### ISSUE TITLE
run `cliphist wipe` to clear clipboard

### ISSUE THREAD

**Issue by 42willow** [keepassxreboot/keepassxc#10233]
https://github.com/sentriz/cliphist

KeePassXC does not clear the clipboard on systems running cliphist.

I didn't open this as a bug as this is a fairly niche clipboard manager, and this isn't really unintended behaviour.

**Comment by droidmonkey** [comment]
Likely related to #10048, if not then cliphist needs to implement the conventions for indicating an entry is "not to be stored in history". You can see that here: https://github.com/keepassxreboot/keepassxc/blob/884386c924192902dc9500a58f9cbdfe22a0a4fd/src/gui/Clipboard.cpp#L59
