### ISSUE TITLE
Opening an SSH session with PuTTY when KeePassXC is locked does not prompt to unlock the database to provide the SSH key

### ISSUE THREAD

**Issue by seud0nym** [keepassxreboot/keepassxc#10232]
## Overview
When using KeePass 2 with the KeeAgent plugin and KeePass is locked, the KeePass password entry or Windows Hello prompt is displayed and the SSH session waits until the database is open and it can obtain the key.

KeePassXC doesn't seem to know that a key has been requested and doesn't intercept the session to prompt for the database to be unlocked so that the key can be provided.

## Steps to Reproduce

1. Configure the SSH Key entry in KeePassXC to both Add key when opened/unlocked and Remove key when locked/closed.
2. Lock KeePassXC
3. Open an SSH session that would be authenticated via Pageant

## Expected Behavior

The SSH session should wait until KeePassXC has been unlocked and can provide the requested key.

## Actual Behavior

The SSH session either shows the remote session password prompt or fails if password authentication disabled.

## Context
KeePassXC - 2.7.6
Operating System: Windows

**Comment by droidmonkey** [comment]
We cannot do this, there is no mechanism for ssh-agent to "call back" to an application. You will have to unlock KeePassXC manually to use the ssh key.

**Comment by Topsii** [comment]
This [blogpost](https://peterbabic.dev/blog/make-ssh-prompt-password-keepassxc/) describes a way to achieve this. Also https://github.com/keepassxreboot/keepassxc/issues/2340#issuecomment-1025266812 mentions that blogpost. I clumsily ported the script from that blogpost to work under Windows for me.

I added the [ProxyCommand](https://dx13.co.uk/articles/2024/08/11/ssh-proxycommand/) setting to my ssh config:
```
ProxyCommand C:\Users\Tobias\.ssh\prompt-for-keepassxc.bat %h %p
```

I installed netcat.exe by installing [NMap ](https://nmap.org/) as suggested [here](https://superuser.com/questions/1283560/openssh-config-file-on-windows-proxycommand-not-working#answer-1451724).


This is the content of my `prompt-for-keepassxc.bat`:
```batch
@echo off

:Loop
ssh-add -l > nul 2>&1
if %errorlevel% equ 0 goto :LoopExit

echo "Waiting for agent. Please unlock the database." 1>&2
"C:\Program Files\KeePassXC\KeePassXC.exe" > nul 2>&1
waitfor /T 1 pause > nul 2>&1

goto :Loop
:LoopExit

ncat.exe %1 %2
```
