### ISSUE TITLE
KeepassXC Auto Unlock

### ISSUE THREAD

**Issue by betawhat** [keepassxreboot/keepassxc#10230]
## Overview
I'm looking for a way to open my Keepass database when I launch my computer.

## Steps to Reproduce
Enter the command: kwallet-query -r KeePassXC kdewallet | keepassxc --pw-stdin database.kdbx

## Expected Behavior
I thought it would open the database automatically with a single command, but you had to type in the password yourself.

## Actual Behavior
Keepass launches with the chosen database, but when you enter your login details nothing is entered.
When I type kwallet-query -r KeePassXC kdewallet it returns my password that I stored in KDEWalletManager.

## Context
I wanted to try to find a way to automatically unlock the database from the console.

Operating System: Linux (Kubuntu)
Desktop Env: KDE
Windowing System: X11

**Comment by BryanJacobs** [comment]
This isn't a bug so far as I can tell, and you can run `keepassxc-cli open --no-password --key-file /path/to/keyfile mydatabase.kdbx` to open a database (protected with a key file, not a password) from the command line without user input.

**Comment by droidmonkey** [comment]
Yah this is a duplicate, search the issues board there are solutions to this.
