### ISSUE TITLE
Request for an AppImage build for the KeepassXC CLI

### ISSUE THREAD

**Issue by ghost** [keepassxreboot/keepassxc#10234]
Hi there,

I'm reaching out to request that you consider producing an AppImage build for the KeepassXC CLI. As someone who frequently works on servers and headless environments, having a portable CLI build would be incredibly useful.

Currently, I have to go through the hassle of building KeepassXC from source in order to have a CLI build available, which can be time-consuming and error-prone. An AppImage would make it much easier to distribute and use the CLI build in a variety of environments.

I understand that producing an AppImage might require some additional work on your end, but I believe it would be a valuable addition to the project and greatly appreciated by users like me who rely on the CLI build.

Thanks for your consideration!

**Comment by droidmonkey** [comment]
Download our normal appimage and use command line variable `cli` to run the cli.

`./KeePassXC-2.7.6-x86_64.AppImage cli`

**Comment by guiohm** [comment]
I also need a standalone keepassxc-cli. Just tried `./KeePassXC-2.7.9-x86_64.AppImage cli` and I get:
```
keepassxc-cli: error while loading shared libraries: libGL.so.1: cannot open shared object file: No such file or directory
```
Ubuntu server 22.04

**Comment by droidmonkey** [comment]
Appimage is a pain, you'll have to install libGL separately.

**Comment by guiohm** [comment]
Indeed. I guess there's no simpler way. Adding 169Mo of libs...
```
# apt install libgl
The following NEW packages will be installed:
  libdrm-amdgpu1 libdrm-intel1 libdrm-nouveau2 libdrm-radeon1 libgl1 libgl1-amber-dri libgl1-mesa-dri libglapi-mesa libglvnd0 libglx-mesa0 libglx0 libllvm15 libpciaccess0 libx11-xcb1 libxcb-dri2-0 libxcb-dri3-0
  libxcb-glx0 libxcb-present0 libxcb-randr0 libxcb-shm0 libxcb-sync1 libxcb-xfixes0 libxfixes3 libxshmfence1 libxxf86vm1
0 upgraded, 25 newly installed, 0 to remove and 4 not upgraded.
Need to get 39.1 MB of archives.
After this operation, 169 MB of additional disk space will be used.
```
BTW, I also had to install libfuse2. So those are the 2 dependencies needed for running keepassxc-cli as an appimage on ubuntu server 22.04
