### ISSUE TITLE
KeepassXC does not see Yubikey while in VNC desktop environment

### ISSUE THREAD

**Issue by GitterDone221** [keepassxreboot/keepassxc#10239]
## Overview
I am running Ubuntu 22.04, and accessing desktop environment using VNC server (tigervnc server). The linux-box is on my desk. Yubikey is in USB slot. When accessing desktop environment using monitor, Yubikey works fine with KeypassXC. When accessing desktop environment using VNC server (from a laptop), KeypassXC does not see Yubikey. To be clear, the Yubikey is inserted in linux-box at all times. I use a Yubikey 5C. KeypassXC version 2.7.6. 

KeypassXC is installed directly via "apt install keypassxc" from Ubuntu PPA, not Snap. I also tried KeypassXC AppImage. Still while in VNC desktop environment the Yubikey is not detected by KeypassXC. However Yubikey is detected by gpg agent (gpg --card-status shows Yubikey details)

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Connect to Ubuntu 22.04 desktop via VNC connection
2. Open KeypassXC
3. Click refresh on Hardware Key - result "no hardware keys detected"

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Yubikey is visible by KeypassXC upon clicking refresh, while accessing Ubuntu desktop using VNC connection.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Yubikey is not visible by KeypassXC upon clicking refresh, when accessing Ubuntu desktop using VNC connection.

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.6
Revision: dd21def

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux Ubuntu 22.04
Desktop Env: Gnome over VNC
Windowing System: X11

**Comment by droidmonkey** [comment]
You may not have permissions setup for the remote X11 user (via VNC) to access raw USB inputs. I am shooting in the dark here, but this is certainly _not_ a KeePassXC problem. This smells like a permissions problem specifically with the VNC connection mechanism and access to system resources.

Can you access the yubikey using the yubikey manager tool? 
What is the output of `lsusb` while connected via VNC?

**Comment by GitterDone221** [comment]
Here are the outputs while connected via VNС

$ lsusb
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 005: ID 1050:0407 Yubico.com Yubikey 4/5 OTP+U2F+CCID
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

$ ykman info
Device type: YubiKey 5C NFC
Serial number: XXXXXXX
Firmware version: 5.4.3
Form factor: Keychain (USB-C)
Enabled USB interfaces: OTP, FIDO, CCID
NFC transport is disabled.

Applications	USB    	NFC     
FIDO2       	Enabled	Disabled	
OTP         	Enabled	Disabled	
FIDO U2F    	Enabled	Disabled	
OATH        	Enabled	Disabled	
YubiHSM Auth	Enabled	Disabled	
OpenPGP     	Enabled	Disabled	
PIV         	Enabled	Disabled

I will dig around for remote X11 configs to access raw USB inputs. Note that I can use the Yubikey for SSH logins  (OpenPGP), encrypt and decrypt applications, while in VNC, no problem. The issue is with KeypassXC not seeing the Yubikey.

**Comment by droidmonkey** [comment]
If you run keepassxc as root (using sudo) while connected via vnc, do you see the yubikey?

**Comment by GitterDone221** [comment]
If I run keepassxc as root (sudo keepassxc) while connected via VNC I can, indeed, see the Yubikey.

**Comment by droidmonkey** [comment]
That confirms the permission problem. Do you have the yubikey udev rules package installed?

https://packages.ubuntu.com/mantic/libyubikey-udev

**Comment by GitterDone221** [comment]
I do. 

$ sudo apt list libyubikey-udev
Listing... Done
libyubikey-udev/jammy,jammy,now 1.20.0-3 all [installed]

I can see the rules here:
/lib/udev/rules.d/69-yubikey.rules

Note, when running yubikey-personalization-gui unprivileged, it does not detect the key - does not show the serial number, and other yubikey particulars, however in privileged mode (sudo yubikey-personalization-gui) the tool does see the Yubikey. In contrast, running yubikey-manager-qt and yubioath-desktop both unpriviledged can see the Yubikey however FIDO2/U2F features are not accessible/editable .

**Comment by droidmonkey** [comment]
Unfortunately, I can only conclude you have a permissions issue somewhere regarding the way you connect via VNC that is not allowing full access  to the yubikey. This isn't something that is a problem with KeePassXC as demonstrated with the other yubikey programs.

**Comment by GitterDone221** [comment]
I fixed the issue by updating the udev rule for Yubikey as follows:

1. `sudo cp /usr/lib/udev/rules.d/69-yubikey.rules /etc/udev/rules.d/`
2. `sudo nano /etc/udev/rules.d/69-yubikey.rules`  

Edit rules to look like this:

```
ACTION!="add|change", GOTO="yubico_end"

# Udev rules for letting the console user access the Yubikey USB
# device node, needed for challenge/response to work correctly. <== this is the default rule 

ATTRS{idVendor}=="1050", ATTRS{idProduct}=="0010|0110|0111|0114|0116|0401|0403|0405|0407|0410", \
    ENV{ID_SECURITY_TOKEN}="1"

# Udev rules for ensuring appropriate permissions to Yubikey when in VNC <== this is the part that I added
ATTRS{idVendor}=="1050", ATTRS{idProduct}=="0407", TAG+="uaccess", GROUP="plugdev", MODE="0660"

```
4. Run: `sudo udevadm control -R`
6. Remove and insert Yubikey 
7. Launch KeePassXC

If key is not visible, you may need to restart your machine.

I got the idea for this fix by reading through these:
https://devicetests.com/fix-permission-denied-error-usb-devices-ubuntu
https://support.yubico.com/hc/en-us/articles/360013708900-Using-Your-YubiKey-with-Linux

**Comment by droidmonkey** [comment]
This might need to be pushed up to the package managers, might be fixed in later releases.
