### ISSUE TITLE
Instead of deleting an entry permanently inside a shared database, can the deleted entry be placed in the recycle bin of the original database?

### ISSUE THREAD

**Issue by oybekkamolov** [keepassxreboot/keepassxc#10248]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
When I delete an entry from inside a shared database, the entry gets deleted permanently. Is there anyway to place the entry in the recycle bin of the database that is doing the sharing? 

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )

- group "Accounts" is shared
- The name of the shared group is "Shared Accounts"
- User opens "Shared Accounts" and accidentally deletes an entry
- Instead of the entry getting deleted permanently, it gets stored in the Recycle Bin of the "Accounts" group

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
Some of the people that we share passwords with are not technically savvy. So, I want to be able to restore entries in case of accidental deletion.

**Comment by droidmonkey** [comment]
I just tested this and shared entries are properly moved to the recycle bin. Make sure the recycle bin is actually enabled in the user's database: 

![image](https://github.com/keepassxreboot/keepassxc/assets/2809491/12d4028c-dabf-4ab5-895a-5a3d349d9261)

**Comment by oybekkamolov** [comment]
Ah I did not notice that option. Thank you!

I think there might be a bug. After I delete an entry, the "Use recycle bin" checkbox keeps getting unchecked. Also, the recycle bin entries are showing up in the shared group.

**Comment by droidmonkey** [comment]
Technically entries are not deleted until they are actually deleted, there are plenty of keeshare "issues" that are actually how it was designed. On the roadmap for an overhaul...
https://github.com/keepassxreboot/keepassxc/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22feature%3A+KeeShare%22

https://github.com/keepassxreboot/keepassxc/issues/2798

**Comment by oybekkamolov** [comment]
[Video 1-30 at 18.26.webm](https://github.com/keepassxreboot/keepassxc/assets/156458748/eae1eef2-6998-4c9b-b614-ac6f0c5e3784)

What about the "Use Recycle Bin" checkbox getting unchecked?

**Comment by oybekkamolov** [comment]
![image](https://github.com/keepassxreboot/keepassxc/assets/156458748/8367ec1d-7eeb-4f21-9785-b5dd95f743e4)
Also, I just noticed 3 recycle bins were created

**Comment by droidmonkey** [comment]
You don't set the recycle bin on the share, you set it on the host database. You have "three" bins because the share created one and synced it then disabled it. See the issue I linked.
