### ISSUE TITLE
Unlock DB on Linux using face, with Howdy (PAM system login)

### ISSUE THREAD

**Issue by Zeit08** [keepassxreboot/keepassxc#10240]
## Summary
Being able to unlock KeePass on Linux Fedora GNOME using [Howdy](https://github.com/boltgolt/howdy)

I read on Howdy GitHub that IF KeepassXC login integrates with the central PAM system, Howdy (which is the software that enables face recognition unlocking with IR camera) will work automatically.

My question is: Can KeePassXC be integrated with the central PAM system? I assume it is a system for linux login management

**Comment by droidmonkey** [comment]
Generally speaking, PAM is for authentication and not for encryption. Read here for more details on why this isn't possible or desirable: https://github.com/keepassxreboot/keepassxc/issues/6055#issuecomment-1021682846

We have integrated PolKit into 2.8.0 which should allow you to use Howdy as an authentication mechanism for quick unlock.
