### ISSUE TITLE
2.2.1 AppImage gpg authenticity fails

### ISSUE THREAD

**Issue by schiorean** [keepassxreboot/keepassxc#1024]
I want to verify the authenticity of the 2.2.1 AppImage. I imported the keys as explained here https://keepassxc.org/verifying-signatures then downloaded the asc file and then I run

`gpg --verify keepassxc_master_signing_key.asc ./KeePassXC-2.2.1-x86_64.AppImage`

## Expected Behavior
gpg saying everything is ok

## Current Behavior
Instead, I get
`gpg: verify signatures failed: unexpected data`

## Steps to Reproduce (for bugs)
1. `gpg --keyserver pool.sks-keyservers.net --recv-keys 0xBF5A669F2272CF4324C1FDA8CFB4C2166397D0D2`
2. Download the asc file
3. Download the 2.2.1. appimage file
4. gpg --verify keepassxc_master_signing_key.asc KeePassXC-2.2.1-x86_64.AppImage

## Debug Info
KeePassXC - 2.2.1
Revision: 

Libraries:
- LIBS

Operating system: Ubuntu 16.04
CPU architecture: ARCH
Kernel: 4.10

Enabled extensions:
- EXTENSIONS

**Comment by phoerious** [comment]
You are trying to verify our master key and the AppImage. Instead, you need to import the master key first and then verify the AppImage signature file. The exact steps are described in our website.

**Comment by schiorean** [comment]
> The exact steps are described on our website.
I fail to see the steps. There's nowhere explained how you get the .sig file. Not clear at all.

**Comment by phoerious** [comment]
https://keepassxc.org/verifying-signatures

**Comment by phoerious** [comment]
You can download the signature files from the downloads page.

**Comment by schiorean** [comment]
> You can download the signature files from the downloads page.

For the life of me if I can find the .sig file on the downloads page... Am I blind or?

**Comment by phoerious** [comment]
Click on the Link that says "GPG Signature".

**Comment by phoerious** [comment]
I think we need to separate them better.
