### ISSUE TITLE
Please consider developing plugin for duckduckgo browser

### ISSUE THREAD

**Issue by vkuznet** [keepassxreboot/keepassxc#10249]
## Summary
With recent release of duckduckgo browser it would be useful to have ability to integrate keepass into that specific browser.

## Examples
We have browser extension for Chrome/Firefox/Edge and I wonder if it would be possible to integrate it with duckduckgo one.

## Context
With increasing privacy concern users may look at different alternatives for their browser needs and duckduckgo browser seems very appealing candidate. But unfortunately there is no keepassxc plugin for it.

**Comment by droidmonkey** [comment]
If they support WebExtensions then just use the chrome extension store. Otherwise we won't develop another extension.
