### ISSUE TITLE
Unable to perform auto-type in vmware console

### ISSUE THREAD

**Issue by arnault38** [keepassxreboot/keepassxc#10246]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Use auto type from KeepassXC to connect to the vmware web console (windows login screen)
2. no characters appear in the login fields, but changing the field with TAB and validating with ENTER is carried out correctly
3. it works from Keepass

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

normal auto type like keepass program

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

characters are not send to the web console or VMRC

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.6
Revision: dd21def

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 11

**Comment by droidmonkey** [comment]
Use the virtual keyboard feature. See the third image in this section: https://keepassxc.org/docs/KeePassXC_UserGuide#_performing_global_auto_type
