### ISSUE TITLE
cannot use keepassxc with https://portal.librus.pl/rodzina/synergia/loguj

### ISSUE THREAD

**Issue by kjonca** [keepassxreboot/keepassxc#10242]
I want to emphasize, that I am not sure if this is KeepassXC issue, and not site issue.

Recently I found that on page mentioned in title I cannot use keepassXC
## Steps to Reproduce
enter https://portal.librus.pl/rodzina/synergia/loguj
- notice that no passwords are proposed.
neither for https://api.librus.pl/ neither for https://portal.librus.pl
## Expected Behavior

[NOTE]: # ( Tell us what you expected to happen )
saved passwords should be proposed.

## Actual Behavior
No passwords proposed.

## Context
This stopped to work about month or 2 ago

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.6
Revision: dd21def

Qt 5.15.10
Debugging mode is disabled.

Operating system: Debian GNU/Linux trixie/sid
CPU architecture: x86_64
Kernel: linux 6.6.9-amd64

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.19.3

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows or   Linux

Desktop Env: XFCE and no DE (fvwm) and Windows.
Windowing System: X11 (I think)

**Comment by droidmonkey** [comment]
This will be fixed shortly once the latest version of the extension makes it way through the chrome/Firefox/edge addon store.
