### ISSUE TITLE
Multiple TOTP in desktop application

### ISSUE THREAD

**Issue by akissz** [keepassxreboot/keepassxc#10253]
I was going to include this as a bug because for me it is a bug but for other people maybe not. I imported some other database and some users had multiple 2fa/otp on purpose and it seems that Keepassxc does not support adding multiple entries similar to other password managers. Please add option to add multiple 2fa/otp onto the entries. I think a good location would be the advanced entry section. There would also need to be a location for a additional icon area to make the additional codes functional and since the graphics are horizontal maybe only add a second location or maybe make the additional ones only show if you right click in the menu. Any questions, let me know.

**Comment by droidmonkey** [comment]
We have decided on 1 totp per entry. We won't be doing anything different from that.
