### ISSUE TITLE
Changes to database on second device is not synced to first device if security key is pulled out

### ISSUE THREAD

**Issue by ptrxt** [keepassxreboot/keepassxc#10251]
## Overview
When changing an entry using mobile device and pulling out the yubikey from desktop to use on mobile, the database change is recognized on desktop but it fails to reload the database because the yubikey is pulled out. However the database is marked with a * indicating it is changed. If I press save now it will overwrite the changes made on mobile and write back the old entry.

## Steps to Reproduce
1. Unlock database on desktop - use password + yubikey
2. Unlock database on mobile
3. Change an entry on the mobile
4. Mobile asks for yubikey -> remove it from desktop and use it on mobile
5. Mobile saves the change to database
6. Desktop imediately notices the change, but fails to reload the database, as the yubikey was removed
7. Now desktop shows database is changed, but it contains the old value before changing on mobile. If I press save now, the latest change will be overwritten by the old value.
8. However, if I lock the database without saving it, and then unlock it, it will correctly reload it when I re-insert the yubikey.

## Expected Behavior
At step 7 desktop should request user to re-insert yubikey so it can reload the database.

## Actual Behavior
Desktop show red banner saying it failed to load database that was changed. Database is marked with * . Tempting to press save in this state, which will overwrite the change.

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.6
Revision: dd21def

Qt 5.15.10
Felsökningsläget är inaktiverat.

Operativsystem: Windows 10 Version 2009
Processorarkitektur: x86_64
Kärna: winnt 10.0.19045

Aktiverade tillägg:
- Autoskriv
- Webbläsarintegration
- SSH-tjänst
- KeeShare
- YubiKey
- Snabb upplåsning

Kryptografiska bibliotek:
- Botan 2.19.3

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows

**Comment by droidmonkey** [comment]
See #5290
