### ISSUE TITLE
Remember Deny All does not remember...

### ISSUE THREAD

**Issue by Oclair** [keepassxreboot/keepassxc#10258]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1.  Visit a website which has password url associations 
2.  Popup prompt appears with the logins I do not want to associate with this particular url  
3. I click Remember and Deny all
4. then I can access the saved logins I wish to have
5. close the browser or await the situation to need to re-login
6. Popup did not remember my choices for Denying All 

## Expected Behavior
[NOTE]: # It used to be possible that Remember and Deny All worked perfectly and logins which were not wished to be associated were so noted at a particular url

## Actual Behavior
[NOTE]: # as described above under Steps to Reproduce

## Context
[NOTE]: # KeepassYC 2.7.6 on Windows 10 and Mac OS14.3 using Firefox 122.0 with KeePassXC-Browser 1.8.12

[NOTE]: #
KeePassXC - Version 2.7.6
Revision: dd21def

[NOTE]: # 
Operating System: Windows 10 and Mac OS 14.3

**Comment by varjolintu** [comment]
It's aleady fixed: https://github.com/keepassxreboot/keepassxc/pull/9607
