### ISSUE TITLE
fingerprint on keepassxc

### ISSUE THREAD

**Issue by magister81** [keepassxreboot/keepassxc#10254]
Hello,

Even if I have set fingerprint login, I have to enter the long master password every time.

That's impossible and no advantage at all!

Where is the error? What do I have to set in windows 11 so that only the fingerprint is sufficient?

greatings
magister

**Comment by droidmonkey** [comment]
We are going to support "remembering quick unlock" in version 2.8.0. This is a duplicate request.

**Comment by magister81** [comment]
Thank you very much. When will this come?
