### ISSUE TITLE
Changing Highlight Color crashes KeePassXC on Mac

### ISSUE THREAD

**Issue by piajesse** [keepassxreboot/keepassxc#10262]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
I was playing around with highlight color and noticed KeePassXC kept crashing in the background

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Have KeePassXC open (don't even need to have a database unlocked)
2. Open System Settings
3. Go to "Appearance" 
4. Click on "Highlight color" and change the color
5. KeePassXC will crash

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.6
Revision: dd21def

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS 14.2.1

**Comment by droidmonkey** [comment]
Duplicate report
