### ISSUE TITLE
(Request) Seriously requesting KeePassXC to bring KeePassXC Authenticator for windows aka desktop version in 2024.

### ISSUE THREAD

**Issue by ghost** [keepassxreboot/keepassxc#10261]
(Request) Seriously requesting KeePassXC to bring KeePassXC Authenticator for windows aka desktop version in 2024.

I have and being Aegis Authenticator on mobile for many years (alongside KeePassXC, of course), and it has been the most dependent app and most recommended app to anybody around me looking for account protection via 2FA. Not a single fault to begin with.

Today, my phones randomly died. All of my logins are in the app itself. Now I cannot log in into any account on my Windows device without mobile, which obviously will be dead for some time.

I tried looking for KeePassXC Authenticator Windows EXE or MSI version and cannot find any.

So if your team can bring an app for desktop and laptop users, it will be beneficial since there are no open source FOSS 2FA apps for windows. All of us aren't dependent on mobile all the time for logins. Some of us have more personal data stored on Windows than mobiles.

🙏🙏🙏🙏🙏🙏

![chrome_SCccE5dEXF](https://github.com/keepassxreboot/keepassxc/assets/156216269/09409c3e-7d78-43da-945d-8d7bfc7e5357)

![chrome_nyVWyjv6Ci](https://github.com/keepassxreboot/keepassxc/assets/156216269/b44fb534-5673-4367-ae2e-ede5b4cd625e)

![chrome_LcaBUtXgGW](https://github.com/keepassxreboot/keepassxc/assets/156216269/69a77667-62a4-4726-811f-72f9bcc10592)

**Comment by droidmonkey** [comment]
We fully support totp, I have no idea what you are asking for here. https://keepassxc.org/docs/KeePassXC_UserGuide#_adding_totp_to_an_entry

**Comment by ghost** [comment]
> We fully support totp, I have no idea what you are asking for here. https://keepassxc.org/docs/KeePassXC_UserGuide#_adding_totp_to_an_entry

I am talking about 2FA which some sites and services like google account, Outlook email, twitter X asks to add when using email and password for account.

**Comment by droidmonkey** [comment]
Yes that is TOTP

**Comment by ghost** [comment]
> Yes that is TOTP

Guide me better as to how to add 2fa accounts in keepassxc apps like I did with aegis and 2fa authenticator and MS authenticator apps.

**Comment by droidmonkey** [comment]
I linked you to the documentation

**Comment by JohnLGalt** [comment]
> > We fully support totp, I have no idea what you are asking for here. https://keepassxc.org/docs/KeePassXC_UserGuide#_adding_totp_to_an_entry
> 
> I am talking about 2FA which some sites and services like google account, Outlook email, twitter X asks to add when using email and password for account.

It really is as easy as the documentation says. The only thing is that there is no capacity to scan a code, but any site that I've added, like all my Google accounts, all of my Microsoft accounts, all my Social Media, etc. have always had a method to **display code**, or something of that nature, and after getting the code, you simply enter it into the TOTP setup dialog box for that entry in your database.

I've been using KPXC as my TOTP provider for all accounts that allow for an app ever since I started using KPXC, and it has never failed me.

**Comment by ghost** [comment]
> > > We fully support totp, I have no idea what you are asking for here. https://keepassxc.org/docs/KeePassXC_UserGuide#_adding_totp_to_an_entry
> > 
> > 
> > I am talking about 2FA which some sites and services like google account, Outlook email, twitter X asks to add when using email and password for account.
> 
> It really is as easy as the documentation says. The only thing is that there is no capacity to scan a code, but any site that I've added, like all my Google accounts, all of my Microsoft accounts, all my Social Media, etc. have always had a method to **display code**, or something of that nature, and after getting the code, you simply enter it into the TOTP setup dialog box for that entry in your database.
> 
> I've been using KPXC as my TOTP provider for all accounts that allow for an app ever since I started using KPXC, and it has never failed me.

Ok, let's say it I add a code. Then what about time bound codes. Will any random code work since 2fa (2fa apps I use as mentioned before) shows time-limited codes that expires after a while.

I might be missing something to understand. 

I know that a website has login process of email and pass for years and now some sites and services have 2fa where you are asked for a code to be entered. I see these time codes which I am getting due to enabling 2fa from those apps and services.

**Comment by JohnLGalt** [comment]
When you're asked to scan a QR Code, there should be an option to get the specific code you need to manually add. That code and that code only will provide the correct TOTP when entered into the TOTP settings in KPXC.

In order to use a (TOTP) code for login purposes, you have to first set it up. That is where (usually) a QR Code is displayed. Underneath that, or off to the side, you'll see an option to 'get code' or 'view code' or 'manual entry' or something like that. Sometimes it is a button you have to click, and sometimes it is a hyperlink you have to click.

**Comment by ghost** [comment]
> When you're asked to scan a QR Code, there should be an option to get the specific code you need to manually add. That code and that code only will provide the correct TOTP when entered into the TOTP settings in KPXC.
> 
> In order to use a (TOTP) code for login purposes, you have to first set it up. That is where (usually) a QR Code is displayed. Underneath that, or off to the side, you'll see an option to 'get code' or 'view code' or 'manual entry' or something like that. Sometimes it is a button you have to click, and sometimes it is a hyperlink you have to click.

Setting up again those 2fa codes would be hassle like before. Isn't there any way to directly import from aegis or winauth or 2fa authenticator app backups (I have json and txt backups)?
