### ISSUE TITLE
Please add button for auto-type in the toolbar (as per KP2)

### ISSUE THREAD

**Issue by affinityv** [keepassxreboot/keepassxc#1026]
keepass2 has a button on the toolbar for auto-type, it would be good to have it for keepassxc too.

**Comment by Throne3d** [comment]
(Is this fixed in #1056?)

**Comment by TheZ3ro** [comment]
(yes it is, merged in develop, will be released in 2.3.0)

**Comment by affinityv** [comment]
No, it is actually done with 2.2.2 and it works perfectly.... or is it just my build from source?

**Comment by phoerious** [comment]
It's in 2.3.0. 2.2.2 is only a bugfix release.

**Comment by affinityv** [comment]
Okay, well it is working well in my build from develop branch of 2.2.2 ... so, it might really be 2.2.2+ (sort of).

KeePassXC - Version 2.2.2
Revision: d4343a5

**Comment by phoerious** [comment]
Yes, that's going to be 2.3.0.

**Comment by droidmonkey** [comment]
Side note, we should probably set the version number on develop to x.y.z-dev after we merge a release.
