### ISSUE TITLE
Manual builds of latest version targeting macOS 10.14 Mojave

### ISSUE THREAD

**Issue by jamesquilty** [keepassxreboot/keepassxc#10268]
I'm really liking KeePassXC, thanks for all your efforts! I like it so much that I'm running KeePassXC on several Macs, two of them running macOS 10.14 Mojave. It wasn't quite apparent to me, from reading the release notes and searching the issues, the reason why version 2.7.2 and later won't run on macOS 10.14? I was wondering whether it was caused by incompatible code (or dependencies) in 2.7.2 onward or whether all that's required is for me to build the current latest version 2.7.6 with the correct flags to target macOS 10.14?

**Comment by droidmonkey** [comment]
Qt dropped support for older macos. Use macports to obtain the latest version that is compatible with 10.14.
