### ISSUE TITLE
App in  on m1 Mac when changed colour accent in View

### ISSUE THREAD

**Issue by mturnaviotov** [keepassxreboot/keepassxc#10264]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Open Mac settings
2. Open Theme setting
3. Change a color accent under white/dark/auto theme selector

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Still stay and work as expected

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
KeePassX crashed

## Context
[NOTE]: # ( Give us any additional information you may have. )
Silicon Mac m1, Sonoma 14.3

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.6
Revision: dd21def

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS Sonoma 14.3, m1/silicon affected.
Not reproduced on Intel Mac

**Comment by droidmonkey** [comment]
The crash occurs if you change the highlight color, this is a duplicate report. This isn't a keepassxc crash though, it's in qt.
