### ISSUE TITLE
KeePassXC won’t autofill in Firefox and Mullvad browsers

### ISSUE THREAD

**Issue by LillianBoxfishTakesAWalk** [keepassxreboot/keepassxc#10265]

**Comment by droidmonkey** [comment]
You likely chose a shortcut key for auto-type that conflicts with one that Firefox uses. Use a different  key combo for KeePassXC auto-type. 

Post here again if you can elaborate on what you are doing exactly if not using auto-type.

**Comment by LillianBoxfishTakesAWalk** [comment]
You’re right. The problem was fixed when I chose a different shortcut key. Thanks!
