### ISSUE TITLE
Extra password for groups

### ISSUE THREAD

**Issue by smartassrobbie** [keepassxreboot/keepassxc#10270]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
Hi,

I was wondering if it was possible to be able to either use an individual password for each group? 

This would make it more secure and /or accessible by multiple users (almost)..

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )
None

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
It would make it possible to share only certain sections with certain people.

**Comment by droidmonkey** [comment]
https://keepassxc.org/docs/KeePassXC_UserGuide#_database_sharing_with_keeshare
