### ISSUE TITLE
KeepassXC looses focus when entering password

### ISSUE THREAD

**Issue by Luuk34** [keepassxreboot/keepassxc#10276]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. autostart keepassXC when starting windows
2. a password is needed for opening the database
3. when other auto started programs start, it is not possible to enter password, because halfway the focus is lost.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
I should be able to type my password without this program loosing it's focus

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
focus is lost.

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.6
Revision: dd21def

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 11

**Comment by droidmonkey** [comment]
This isn't possible because Windows is the thing moving focus around. You'll just need to be patient.
