### ISSUE TITLE
Problem with gpg --fetch-key instruction

### ISSUE THREAD

**Issue by affinityv** [keepassxreboot/keepassxc#1027]
Link [1] has an instruction to get gpg to fetch the GPG key, but there is a problem with that (with my gpg at least).

$ gpg --fetch-keys https://keepassxc.org/keepassxc_master_signing_key.asc
gpgkeys: protocol `https' not supported
gpg: no handler for keyserver scheme `https'
gpg: WARNING: unable to fetch URI https://keepassxc.org/keepassxc_master_signing_key.asc: keyserver error

gpg2 doesn't seem to give any errors, but it times out.

I also tried to use torsocks with gpg2, but it timed out too.

Suggest adjusting the information at the link to not show the gpg --fetch-keys method.

[1] https://keepassxc.org/verifying-signatures

**Comment by jonathancross** [comment]
Have you tried upgrading to a newer version of gpg?

    gpg --version
    gpg (GnuPG/MacGPG2) 2.2.0

Works fine for me in this recent version.
