### ISSUE TITLE
DRAFT: Small, unclickable dock icon on macOS

### ISSUE THREAD

**Issue by survellow** [keepassxreboot/keepassxc#10271]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

Sometimes the KeePassXC icon in the macOS dock shrinks too small to be clickable. 

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
I don't know yet what causes this problem, so I will keep looking at it. If anyone has a suggestion that I could try, please let me know. 

1. Open KeePassXC
2. Enable the following features: 
    - "Minimize window after unlocking database"
    - "Minimize instead of app exit"
    - "Hide window to system tray when minimized"
    - "Lock databases after inactivity of 240 sec"
3. Restart KeePassXC and login
4. Wait for the database to be locked again
5. Start Autotype or any programm accessing the database
6. Put in your credentials (at this point I am sometimes stuck with the problem)

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

KeePassXC should either be shown in the dock (with or without activity dot) or not.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

KeePassXC icon is displayed incorrectly, making the programm inaccessible from within the dock:
![Screenshot 2024-02-05 at 13 40 34](https://github.com/keepassxreboot/keepassxc/assets/59056368/00c62d95-1cb4-4516-b92c-f70b8349391c)

(The program is located in between the Terminal and Acrobat Reader icons)

## Context
[NOTE]: # ( Give us any additional information you may have. )

I only use the inactivity timeout because locking on suspend in combination with QuickUnlock (TouchID) doesn't work properly on macOS. I'm currently waiting for a fix of #8945. 

This problem could depend on the use of external monitors, as I use a Thunderbolt docking station with my MacBook. I do rarely have scaling issues with the macOS menu bar itself. So I don't know if this issue is related to KeePass or macOS, but it seems to be limited to that application.

[NOTE]: # ( Paste debug info from Help → About here )
```
KeePassXC - Version 2.7.6
Revision: dd21def

Qt 5.15.10
Debugging mode is disabled.

Operating system: macOS 14.3
CPU architecture: arm64
Kernel: darwin 23.3.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 2.19.3
```

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS
Desktop Env: Stock/Aqua
Windowing System: Quartz with Rectangle

**Comment by droidmonkey** [comment]
If anything this would be a macos bug, the OS should never show an icon that small so something is super buggy. It could be a strange interaction with Qt, but I know we do some icon manipulation on macOS because it's special.

**Comment by HUMORCE** [comment]
I meet same issue and came here by seaching "keepassxc dock icon". It goes back to normal after a reboot, and cannot reproduce for now.
