### ISSUE TITLE
AutoType doesn't recognize Thunderbird master key window on macOS

### ISSUE THREAD

**Issue by survellow** [keepassxreboot/keepassxc#10272]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

The master key entry window of Thunderbird is not recognized when trying to do AutoType.
![Screenshot 2024-02-05 at 14 00 24](https://github.com/keepassxreboot/keepassxc/assets/59056368/eebee3fa-a1d5-4ea9-a44a-23084a1f2c9d)

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Set master password in Thunderbird and close Thunderbird
2. Open Thunderbird and wait for the "Password Required" prompt
3. Launch global AutoType by using the assigned keyboard shortcut

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

KeePassXC should read the window title and match with entries that have "Password Required - Mozilla Thunderbird" in their AutoType configuration.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

KeePassXC reads the title of the window underneath the Thunderbird prompt (i. e. a Firefox window) or the desktop and lists the wrong keys. Therefore it is necessary to search for the password manually. AutoType then works without a problem.

## Context
[NOTE]: # ( Give us any additional information you may have. )

The key selection window of the AutoType feature instead shows either the keys for the program behind that window or, if there is no other program on the current desktop, a list of all my keys. 

[NOTE]: # ( Paste debug info from Help → About here )
```
KeePassXC - Version 2.7.6
Revision: dd21def

Qt 5.15.10
Debugging mode is disabled.

Operating system: macOS 14.3
CPU architecture: arm64
Kernel: darwin 23.3.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 2.19.3
```

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS
Desktop Env: Aqua/Stock
Windowing System: Quartz

**Comment by droidmonkey** [comment]
It is possible that thunderbird is hiding this window/dialog from us. It also looks like the window is not in focus. Be sure to click the title bar of the thunderbird window before attempting Auto-Type.

**Comment by survellow** [comment]
I checked again and the window seems to be in focus. If I focus another window, the close button is greyed out. 

Hiding could indeed be a problem. Is there any way to figure out, whether or not KeePassXC can see the window?

I use the same configuration on my Linux and Windows PCs without a problem, only on macOS I can't AutoType the master password.

**Comment by droidmonkey** [comment]
Honestly, you may have to open a bug report with Thunderbird/Mozilla.
