### ISSUE TITLE
Randomizer for non-password attributes

### ISSUE THREAD

**Issue by schichtnudelauflauf** [keepassxreboot/keepassxc#10284]
## Summary
Making the randomizer available for other fields than password. Templates for birthdate, name, SSN.
Sliders for various plausibility scales. Like is the date less than 100yo or inside the Unix epoch. Actual random characters in name or names from a list that "sound matching to a place". Can I have emoji in the name?

## Examples
No pic, am on phone.
Add the dice button to all the standard fields.
Have a name or birthdate mode for the randomizer.
A section in settings to make randomizer templates for custom fields.

## Context
Data leaks and neglectful companies, public offices where the sole access control is semi-public data like birthdate or SSN in Merighetto. But where the correctness of that datum isn't actually required.

German Fedi Thread
https://chaos.social/@isotopp/111894724652060162

**Comment by droidmonkey** [comment]
We won't implement that, it would be a lot of code for really nothing. Just mash the keyboard. Randomness doesn't matter if you are just fudging answers to questions.
