### ISSUE TITLE
Yubikey 5C Nano not detected on Ubuntu 23 even with unconfined app and udev installed. 

### ISSUE THREAD

**Issue by mikedlr** [keepassxreboot/keepassxc#10289]
## Overview

Yubikey not detected when apparently otherwise working - maybe due to need for custom reader? 

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1.  install keepassxc from deb (previously tried flatpak)
2.  install other yubikey related software such as libyubikey-udev
3. decrypt database with existing password
4.  Open Database-> Database Security
5. click Add Challenge-Response 
6.  note message in Actual Behavior below. 

## Expected Behavior

Harware key is identified and usable 

## Actual Behavior

Message "No hardware keys detected" visible in Hardware Key box of decryption dia

## Context
[NOTE]: # ( Give us any additional information you may have. )

* I have installed yubikey related software.
* udev rules are installed
* I am neither using snap nor flatpack
* I have a YubiKey 5C Nano
* The yubikey is identified by the _Yubikey Authenticator_ app, but only when "custom reader" is enabled. 

Package: keepassxc
Version: 2.7.4+dfsg.1-2
Priority: optional
Section: universe/utils
Origin: Ubuntu
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Julian Andres Klode <jak@debian.org>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 28.0 MB

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.6
Revision: dd21def
Distribution: Snap

Qt 5.15.9
Debugging mode is disabled.

Operating system: Ubuntu Core 22
CPU architecture: x86_64
Kernel: linux 6.5.0-17-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.19.1

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: Gnome
Windowing System: Wayland

**Comment by droidmonkey** [comment]
Did you setup the yubikey slot 1 or 2 for challenge response?

**Comment by mikedlr** [comment]
I have done

`ykpersonalize -2 -ochal-resp -ochal-hmac -ohmac-lt64 -a303132333435363738393a3b3c3d3e3f40414243`

though TBH if I hadn't I guess my expected message would be "Challenge Response not configured on HW Key" rather than "No hardware keys detected"

if I use the test vector the key responds correctly 

```
$ ykchalresp -2 'Sample #2'
0922d3405faa3d194f82a45830737d5cc6c75d24
```

**Comment by droidmonkey** [comment]
See https://github.com/keepassxreboot/keepassxc/issues/10260 and https://github.com/keepassxreboot/keepassxc/issues/10239#issuecomment-1915226252. Very unlikely this is a keepassxc problem. Most likely a udev rules or snap problem. Easy check is to run keepassxc as root and see if you can see the yubikey then. I'll reopen if you can't get it to work as root.

**Comment by droidmonkey** [comment]
> I am neither using snap nor flatpack

Looks like you are absolutely using snap...

![Screenshot_20240210_081934_GitHub.png](https://github.com/keepassxreboot/keepassxc/assets/2809491/43e0a0a8-099b-4b9b-a7a5-9ea367997fd4)

**Comment by mikedlr** [comment]
Ooops. Now I see the device. 

Sorry about that, I had explicitly removed the flatpak which I was using previously and I have no idea how I managed to install from the snap by accident.
