### ISSUE TITLE
Errors on security settings

### ISSUE THREAD

**Issue by jamm3r** [keepassxreboot/keepassxc#1028]
In version 2.2.1. for windows, after selecting the "Lock databases when session is locked or lid is closed" and applying / exiting the settings screeen, the setting is apparently not saved, and the flag is not present opening the settings screen again.

Moreover and indipendently: selecting and the "Use google as fallback" setting, in the same panel, also the "Lock databases when session is locked or lid is closed"  is applied.

## Steps to Reproduce (for bugs)
First error
1. Open Tools > Settings > Security
2. Select "Lock databases when session is locked or lid is closed" 
3. Apply / Ok
4. Open Tools > Settings > Security again

Second error
1. Open Tools > Settings > Security
2. Check  "Lock databases when session is locked or lid is closed" setting is disabled
3. Select "Use Google as fallback for downloading website icons"
4. Apply / Ok
5. Open Tools > Settings > Security again

## Debug Info
KeePassXC - Version 2.2.1
Revision: 2bce9c8add07226e9a05e9e0fd0e5e66b236d5b6

Libraries:
- Qt 5.9.1
- libgcrypt 1.8.1

Operating system: Windows 7 SP 1 (6.1)
CPU architecture: x86_64
Kernel: winnt 6.1.7601

Enabled extensions:
- KeePassHTTP
- Auto-Type
- YubiKey

**Comment by TheZ3ro** [comment]
Oh wow. This is a bug

**Comment by jamm3r** [comment]
After further tests, apparently the lock db setting (error n. 1) gets saved even if the flag is not displayed correctly

**Comment by TheZ3ro** [comment]
Can you compile and test #1029 ? Should be fixed

**Comment by jamm3r** [comment]
No, unfortunately I cannot compile right now, sorry.

**Comment by TheZ3ro** [comment]
Fixed in #1029
