### ISSUE TITLE
Auto-type triggers database re-lock even when option is disabled

### ISSUE THREAD

**Issue by starbuck3000** [keepassxreboot/keepassxc#10285]
## Overview
When option "Re-lock previously locked database after performing auto-type" is disabled, then the database is re-locked anyway after an auto-type.

## Steps to Reproduce
1. Unlock locked database
2. In settings -> general -> auto-type, enable "Re-lock previously locked database after performing auto-type"
3. In settings -> general -> auto-type, disable "Re-lock previously locked database after performing auto-type"
4. Go to password entry and trigger auto-type (ctrl+shift+v)
5. Entry is auto-typed

## Expected Behavior
6. Database should remain unlocked.

## Actual Behavior
6. Database is re-locked

## Context
This bug renders access to the OTP functionality cumbersome as everytime the auto-type sequence is triggered, the database gets locked. 

Note: a workaround is possible through the customization of the auto-type sequence (adding the TOTP entry in the sequence). But this only works if the desktop client maintains the master file: users who use another platform (e.g., mobile client) as master location for their database lose customization of the auto-type sequences every time they re-synchronize their database file to the desktop client.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.6
Revision: dd21def

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 10
Desktop Env: -
Windowing System: -

**Comment by droidmonkey** [comment]
Do you have lock on minimize enabled? The setting you reference is not related to the toolbar Auto-Type (Ctrl + Shift + V).
