### ISSUE TITLE
Auto-locking prevented by popup in edit mode

### ISSUE THREAD

**Issue by karalabe** [keepassxreboot/keepassxc#10288]
## Overview

While a key is being edited (or at least when a new key is being added/created), the database auto-lock is prevented by a popup that wants to cancel the edit.

## Steps to Reproduce

1. Start creating a new key, don't finish it
2. Leave your computer be
3. Database will not lock, a popup prevents it

## Expected Behavior

Whilst it is an interesting "data loss" scenario of locking the db while editing (i.e. I might lose my unsaved entry), it is arguable a lot more serious issue that my entire dataset remain unlocked indefinitely.

## Actual Behavior

Database remains unlocked forever.

```
KeePassXC - Version 2.7.6
Revision: dd21def

Qt 5.15.10
Debugging mode is disabled.

Operating system: macOS 14.2
CPU architecture: arm64
Kernel: darwin 23.2.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 2.19.3
```

**Comment by droidmonkey** [comment]
This is a duplicate report
