### ISSUE TITLE
Re-introduce regex url capability to KeePassXC.

### ISSUE THREAD

**Issue by calebsdaddy** [keepassxreboot/keepassxc#10291]
## Summary
Requesting regex be re-introduced as a feature for URL handling. The replacement for regex, "Browser Integration: Additional URLs" does not work as advertied. The below does not match as indicated as described in: 

https://github.com/keepassxreboot/keepassxc/issues/3718#issuecomment-547697702

My version is 2.7.6
```
https://sub1.domain.tld does NOT match with https://sub2.sub1.domain.tld
and
https://sub2.sub1.domain.tld does NOT match with https://host1.sub2.sub1.domain.tld
```
## Context
I manage THOUSANDS of devices, frequently via IPMI. I can and have verified regex would allow me to have a single entry that would work for all my IPMI devices, however it has been removed and no longer works. I have verified that OTHER password managers WILL do regex without issue.

On Oct 29, 2019, yan12125 wrote in https://github.com/keepassxreboot/keepassxc/pull/1769#issuecomment-544115834

> Now there is https://github.com/keepassxreboot/keepassxc/pull/3558 for multiple URLs in KeePassXC. In case anyone else is using my branch, here is a [patch](https://github.com/yan12125/keepassxc/commit/ba1e5bdc19addbb0bf4ae04218119c52871cf93b) to migrate from URL_ALT to officially-supported KP2A URLs. URL_REGEX attributes are dropped, though, as I don't use it in many entries and it's non-trivial to migrate them.

This is HIGHLY disrespectful. Just because a single user doesn't use them, doesn't mean a boatload of users would not. In addition, it is nowhere near trivial to migrate them considering I'd either need an entry for EVERY IPMI I access or one URL entry for over 2000 nodes I support and the current unusability of "Additional URLs".

**Comment by varjolintu** [comment]
https://github.com/keepassxreboot/keepassxc/pull/9835 ?

**Comment by droidmonkey** [comment]
This is a duplicate, and this means something else is happening:

>  https://sub1.domain.tld does NOT match with https://sub2.sub1.domain.tld and https://sub2.sub1.domain.tld does NOT match with https://host1.sub2.sub1.domain.tld 

This should absolutely work. Unless you enabled "Only return best matching credentials" but even then it should work. The website you are testing on might have an iframe that is using a different url. The extension gives you a notice on which domain it was trying to use to find credentials. 

For the record, we never had regex matching for urls. So nothing was removed.
