### ISSUE TITLE
Missing entry history under specific conditions

### ISSUE THREAD

**Issue by lin-xianming** [keepassxreboot/keepassxc#10296]
## Overview

When an entry is created and updated following the steps below, a history entry for the entry is not created.

## Steps to Reproduce

1.  Create a database with the following settings:
    - Database format KDBX 4
    - Encryption algorithm AES 256-bit
    - Key derivation function AES-KDF (KDBX 4)
    - No password
    - Has keyfile
    - Has challenge-response with Yubikey
3. Create an entry with an URL (favicon not already in database) and save it
4. Open the entry again, click on the download favicon button, and save it

## Expected Behavior

Favicon is updated and a history entry is created

## Actual Behavior

Favicon is updated and a history entry is not created

## Context

KeePassXC - Version 2.7.6
Revision: dd21def

Qt 5.15.10
Debugging mode is disabled.

Operating system: Windows 10 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.19045

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 2.19.3

**Comment by droidmonkey** [comment]
I couldn't reproduce this, tried 3 times all different ways to load an icon.

![image](https://github.com/keepassxreboot/keepassxc/assets/2809491/d56e4762-4948-4928-a746-af872563210c)

Try it again, if you can determine better steps I will re-open.

**Comment by lin-xianming** [comment]
Please create a new entry with no existing history and with URL with favicon not already in the database, as indicated in step 2. As well as save before and after downloading the favicon.

**Comment by droidmonkey** [comment]
I did exactly that many times, couldn't reproduce
