### ISSUE TITLE
QuickUnlock feature does not work on linux

### ISSUE THREAD

**Issue by antonio-antuan** [keepassxreboot/keepassxc#10292]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
I want to make QuickUnlock feature working on my laptop. fprint is configured and works fine in my terminal. As far as I understand, polkit service is running and registered in dbus:
```
➜  ~ sc-status polkit.service
● polkit.service - Authorization Manager
     Loaded: loaded (/usr/lib/systemd/system/polkit.service; static)
     Active: active (running) since Sun 2024-02-11 12:18:46 IST; 15min ago
...
➜  ~ qdbus --system|grep -i policy
 org.freedesktop.PolicyKit1
```
under settings->security I have "enable database quick unlock" checkbox set but disabled:
![image](https://github.com/keepassxreboot/keepassxc/assets/6426720/e00e3d33-e886-4c9d-8bce-325fd1ea61e4)

Also I tried to follow [this instruction](https://wiki.archlinux.org/title/fprint#Fingerprint_authentication_is_not_taking_effect_in_the_Polkit_agent.) and it does not help.
And I have never seen dialog to unlock db with my fingerprint.
What am I doing wrong?

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. 
2. 
3. 

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Quick Unlock feature works

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Quick Unlock feature does not work :)

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.6
Revision: dd21def

Qt 5.15.12
Debugging mode is disabled.

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 6.7.4-arch1-1

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 3.2.0

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux (archlinux)
Desktop Env: KDE Plasma 
Windowing System: X11

**Comment by droidmonkey** [comment]
This is only available if you are running a snapshot build. https://snapshot.keepassxc.org
