### ISSUE TITLE
only sub-groups

### ISSUE THREAD

**Issue by Lin0lion** [keepassxreboot/keepassxc#10297]
So, whenever I try and create a group it always makes me start creating a **sub-group** without even TELLING me that I'm going to make a sub-group, and for which group. To summarise this, I can only make a sub-group. #5671

**Comment by Lin0lion** [comment]
Oh, and I created a github account only to say this bug.

**Comment by droidmonkey** [comment]
Welcome, but your report doesn't sound like a problem at all. KeePass databases are designed to have one root group and every other group is a sub to that one.

**Comment by Lin0lion** [comment]
I have received your message. But, there's one thing I don't understand:Why
does one database have 1 group?! Please make it so that I can have more
groups! Naming a main group is pointless because you could just name the
database! Please change this.

Warm Regards

TheREALLin0lion
(CatalinBivol on *Scratch.mit.edu <http://Scratch.mit.edu>, *TheREALLin0lion
on *Opera GX, *Lin0lion on *Roblox* and *Minecraft*)

Did I go too far? Sorry.

**Comment by droidmonkey** [comment]
You can have as many groups as you want...

![image](https://github.com/keepassxreboot/keepassxc/assets/2809491/d2054c08-e456-4791-aca8-c2f07c456494)

**Comment by Lin0lion** [comment]
Now, I understand. I don't like this, but fine. I'll try to work with this.

I won't go too far like I did last time.

I only got a github account for this.
