### ISSUE TITLE
DB unlock on auto-type not bringing the credentials window

### ISSUE THREAD

**Issue by anatoli26** [keepassxreboot/keepassxc#103]
The #89 issue is almost complete, though on Ubuntu 16.04 (not tested on other platforms) the sequence is as follows:

DB is locked -> auto-type key combination -> Unlock the DB window appears -> Pass entered, DB is unlocked -> the unlock window disappears -> nothing more…

The sequence should be followed by the credentials selection window brought to front, as what appears on auto-type with the DB unlocked.

**Comment by anatoli26** [comment]
This issue is inconsistent. Sometimes the creds window appears, sometimes not. Can't reproduce it consistently. It looks like the time one spends typing the pass may somehow be related (i.e. if it takes long, the window appears, quick pass entry -> window not appearing), though not always.

It also could be a multi-user environment and running an instance under each user.

The second time I invoke the auto-type (i.e. when the DB is already unlocked, e.g. after unlocking it with the first request for auto-type), the creds window appears always. The problem is only when unlocking the DB with auto-type.

Right now I can start KPXR (DB locked), switch to another app, request auto-type and after unlocking the DB the creds window would appear about 50% of times (the tendency is the more I wait between closing and opening KPXR and the more I spend typing pass, the more are the chances the creds window will appear). Then I lock the DB, minimize the KPXR window, go to some app, request auto-type and after unlocking, 100% of times the creds window doesn't appear.

It also looks like it somehow depends on whether the window is in the background or minimized (to taskbar). Weird... Looks like some race condition.

**Comment by TheZ3ro** [comment]
Maybe you haven't an Entry that match the Window title you perform the Auto-Type.

Try the following step:

1. Set an Auto-type shortcut key sequence from settings (if you haven't set it yet)
2. Create a new database and save it somewhere
3. Add a new entry to the database with a custom title, user and password
4. Go in the Entry Autotype setting
5. Click on the **+** button on the bottom and set the window title to `//(.*)//`
6. Save the entry, save the database and lock it
7. **Check that this database is the first(or the only) in the database tab list**
7. Open your favourite GTK text editor (like gedit or mousepad)
8. Perform the Autotype

Now it should ask you to unlock the DB and then the window with your entry should ***always*** appear

**Comment by anatoli26** [comment]
@TheZ3ro, completed all the steps as you asked, the creds window (entry-list) hasn't appeared.

A new DB with 2 entries
![kpxr1](https://cloud.githubusercontent.com/assets/22968420/20471156/2800edbe-af8e-11e6-8618-21ea72525b75.png)

The auto-type options of one of the entries
![kpxr2](https://cloud.githubusercontent.com/assets/22968420/20471158/2ac478cc-af8e-11e6-99f8-38f7b9436887.png)

Auto-type key sequence pressed while in GEdit
![kpxr3](https://cloud.githubusercontent.com/assets/22968420/20471161/2f56fe00-af8e-11e6-9993-552500b022b1.png)

After entering the pass and hitting enter
![kpxr4](https://cloud.githubusercontent.com/assets/22968420/20471163/319fe0c8-af8e-11e6-97ca-9df1d9dc11e1.png)

I should also add that the creds window sometimes appears and sometimes not for the same app with the same DB opened, i.e. doesn't depend on the match. Though, even if no match, there appears a warning window saying that there was no matching entries found. Here what I observe is that NOTHING appears, but not always...

**Comment by zootboy** [comment]
I can confirm that this happens with 100% reproducibility on my setup - Arch Linux, Awesome WM, commit 72b81bf. Every time I trigger the auto-type with the DB locked, I get the password prompt but the auto-type is canceled. Auto-type works fine if the DB is already unlocked.

**Comment by phoerious** [comment]
Is your KeePassXC window visible or minimized when that happens? Also try minimizing to tray before unlocking and see if it works.

**Comment by zootboy** [comment]
Just tried it both ways. Neither one behaves correctly. The DB always unlocks, but the autotype confirmation window doesn't appear until I input the global hotkey a second time.

**Comment by anatoli26** [comment]
For me it sometimes works. I don't know why, but when Firefox asks for the master password the KPRC credentials window appears always, without exceptions. For other windows (e.g. terminal) it tends to appear on the first use but mostly never appears after that.

**Comment by phoerious** [comment]
Does this issue still occur with 2.1.2 or the develop branch?

**Comment by zootboy** [comment]
Yes, the issue is still present in 4061fc7.

**Comment by anatoli26** [comment]
I'm testing the 2.1.2 for a week already and this issue has not appeared yet.

**Comment by zootboy** [comment]
I tested 2.1.2, and the issue is present for me. I suspect it's some odd interaction with Awesome WM.

**Comment by axujen** [comment]
Same issue as the people above, archlinux and awesome wm with keepassxc version 2.1.2

The creds window only appears after unlock the database and repressing the autotype keybind.

**Comment by hifi** [comment]
No repro on Xfce. Focus follows mouse is enabled and the target window was under my cursor the whole time.

**Comment by anatoli26** [comment]
Just experienced the problem again. Restarted the machine, opened Firefox, it asked me for master pass, pressed the autotype key, KPRC showed the unlock window, entered the pass > enter, the window disappeared, no credentials shown.

Ubuntu 16.04 with latest updates, KPRC 2.1.2 Revision: b9279f73fa58d75e1ec88f734f3c77c0f015a348

**Comment by anatoli26** [comment]
For me it's a race condition. @phoerious, @TheZ3ro, could you please point me to the parts of the code responsible for the autotype functionality? I'll try to debug and further investigate what's going on.

**Comment by s-gurevich** [comment]
For me, the auto-fill containing unlocking the database never works. After the database is unlocked nothing happens anymore. Need to repeat auto-fill shortcut again.
The system is Ubuntu 18.10.
A fix would be strongly appreciated.

**Comment by droidmonkey** [comment]
This is no longer an issue

**Comment by anatoli26** [comment]
What's the commit that fixes the problem? Any possibility to port it to 2.2 branch? I'm stuck with 2.2.4 because of some crypto libs not available on Ubuntu 16.04 that are a requirement in 2.3+

**Comment by droidmonkey** [comment]
Use the appimage

**Comment by anatoli26** [comment]
mm... I build KPXC from sources. Anyway, could you please point to the commit fixing this bug? Thanks

**Comment by droidmonkey** [comment]
It just works, I am not sure what you need to know? If the database is locked and you trigger global auto-type, there is a dialog that pops up to unlock the database.

**Comment by anatoli26** [comment]
For me on 2.2.4 with Ubuntu 16.04 this is still a huge problem. When you said "This is no longer an issue" I thought you found the problem and fixed it so I thought maybe to back-port the solution to 2.2.4, that's why I'm asking.

Now I see you just can't reproduce the issue in your environment. I believe it would be more appropriate to ask for feedback from affected users before closing the issue, if you suspect that some version introduced some changes that may have solved the problem.

**Comment by droidmonkey** [comment]
We don't backport, this project does not have long term release concept.
