### ISSUE TITLE
Cannot save database

### ISSUE THREAD

**Issue by JKYiannis** [keepassxreboot/keepassxc#10307]
When I try to save database using as alternative saving method "Temporary file moved into place" I see the message "Writing the database failed: Destination file exists. Backup database located at C:/Users/yiann/AppData/Local/Temp/KeePassXC.pMOJWP".
When I try to save database using as alternative saving method "Directly write to database file (dangerous)" I see the message "Writing the database failed: Access is denied". 
In any case I cannot save the database.I use Windows 10. Could you help me please?
Thanks
Yiannis

**Comment by droidmonkey** [comment]
That would indicate you do not have write access to the database file. You must be able to delete and create files to use the first alternative save method and the ability to write to the file using the second. Fix your permissions and this will work.
