### ISSUE TITLE
Suggestion: Easy Migration from Authy Desktop (Windows) which is being EOL'd

### ISSUE THREAD

**Issue by markd89** [keepassxreboot/keepassxc#10301]
## Summary
Authy Desktop is being EOL'd in one month (March 15). All of those users have a choice to use Mobile or switch to something else if they don't want to use Mobile. 

It would be nice to have an easy migration, be that in software or just documentation. There are potentially MANY users who could use this.

https://support.authy.com/hc/en-us/articles/17592416719003-Business-customer-guide-End-of-Life-EOL-for-use-of-Authy-API-with-Twilio-Authy-Desktop-apps

https://www.techfinitive.com/authy-desktop-2fa-app-shuts-down-leaving-many-users-in-perilous-position

**Comment by droidmonkey** [comment]
We won't create a migration path from abandoned software. Just start now and copy your information to keepassxc. Otherwise if there is a csv export option you can use that.
