### ISSUE TITLE
Master password entered twice

### ISSUE THREAD

**Issue by valereandota** [keepassxreboot/keepassxc#10303]
## Overview
When opening a keyfile in KeypassXC, it says the password is wrong on the first attempt

## Steps to Reproduce

1. Open KeypassXC 
2. Enter Password
3. 

## Expected Behavior
Sign in on first attempt.

## Actual Behavior
First sign in attempt gives a popup that username or password is wrong.
Second login attempt within the same session is successfull (when the password entered is exactly the same)

## Context
No more context to provide

KeePassXC - Version 2.7.6
Revision: dd21def

Qt 5.15.10
Debugging mode is disabled.

Operating system: Windows 11 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.22631

Enabled extensions:
Auto-Type
Browser Integration
SSH Agent
KeeShare
YubiKey
Quick Unlock

Cryptographic libraries:
Botan 2.19.3

**Comment by droidmonkey** [comment]
Not sure what you are referring to, but keepassxc doesn't have username/password login. Please be more specific and we can reopen this.
