### ISSUE TITLE
Unlocking KeepassXC on Mac with any password but with TouchID (by design?)

### ISSUE THREAD

**Issue by shuther** [keepassxreboot/keepassxc#10315]
## Overview
DB can be unlocked using dummy password but with TouchID. User experience is confusing?

## Steps to Reproduce
1. Open KeepassXC with correct password on a Mac, with Enable TouchID quick unlock and lock database (not sure if important) options under Preferences/Security
2. Lock the database (i.e. lid is closed)
3. Type any password to unlock the database
4. Press the TouchID
5. Database is unlocked

## Expected Behavior
Password should not be requested if TouchID can be used to unlock the DB, or the button Unlock could have a sign that it accepts the touchID (logo to be added to the button)
Wrong password (not empty) should never unlock the DB; maybe removing it from the session memory enclave (so touchID can't be used afterwards) ?

## Actual Behavior
is it by design to allow TouchID?

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.6
Revision: dd21def

Qt 5.15.10
Debugging mode is disabled.

Operating system: macOS 14.3
CPU architecture: arm64
Kernel: darwin 23.3.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 2.19.3

Operating System: macOS

**Comment by phoerious** [comment]
That's a UI bug that sometime appears when you close the lid in between. Under normal circumstances, you should see only the fingerprint unlock button, not the password field.

**Comment by shuther** [comment]
I confirm that if within the browser, I click on the keepassxc extension, keepass wokes up with the unlock (touchId logo) on it.

**Comment by droidmonkey** [comment]
See #8945
