### ISSUE TITLE
KeePassXC Locks even though the feature is disabled

### ISSUE THREAD

**Issue by GenerallyDisjointed** [keepassxreboot/keepassxc#10317]
## Overview
I have disabled "Lock databases after inactivity of" and the database still locks

## Steps to Reproduce
Click Cog icon
Click Security icon
Untick "Lock databases after inactivity of"

## Expected Behavior
The database should not lock

## Actual Behavior
Database locks what seems to be about 5 minutes

## Context
Running Linux Mint v 21.3
KeePassXC v 2.7.6

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.6
Revision: dd21def
Distribution: AppImage

Qt 5.15.2
Debugging mode is disabled.

Operating system: Linux Mint 21.3
CPU architecture: x86_64
Kernel: linux 6.5.0-18-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.19.1

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: XFCE
Windowing System: X11

**Comment by droidmonkey** [comment]
Something else on your system is sending out a "lock" signal. See here for similar case: https://github.com/keepassxreboot/keepassxc/issues/10245#issuecomment-1946608586

There are many ways keepassxc can be locked. Uncheck the setting to lock on screen shutoff / screen saver to confirm. Then you can go hunt for why that signal is happening for you.

**Comment by GenerallyDisjointed** [comment]
Spot on! Can confirm it is a system security "feature", not a KeePassXC bug (for anyone else searching)

> Something else on your system is sending out a "lock" signal. See here for similar case: [#10245 (comment)](https://github.com/keepassxreboot/keepassxc/issues/10245#issuecomment-1946608586)
> 
> There are many ways keepassxc can be locked. Uncheck the setting to lock on screen shutoff / screen saver to confirm. Then you can go hunt for why that signal is happening for you.
