### ISSUE TITLE
Use pam_usb for database unlock

### ISSUE THREAD

**Issue by dvictori** [keepassxreboot/keepassxc#10313]
## Summary
I recently read about _pan_usb_ and how an ordinary removable media could be used for hardware authentication (https://github.com/mcdope/pam_usb). One common pet peeve I have with KeepassXC is having to type my long password every time the database is locked on my desktop. Would it be useful (and safe) to use _pam_usb_ and allow for the database to be unlocked if a specific USB key is inserted? That is, the unlock could be done using either a password or a ordinary removable media.

## Examples
The Keepass2Android allows for the database to be unlocked using either a typed password or your biometric identification. That way I don't have to type a long password. Not sure how they implement this but the database can be unlocked using two different methods. Of course, I can't use an ordinary removable media for Keepass2Android unlock...

## Context
Tiered of typing long passwords. Do not have a dedicated hardware key (like Yubico). Also, not sure how setting up a hardware key in KeepassXC (or any other hardware authentication method) would affect Keepass2Droid.

**Comment by droidmonkey** [comment]
PAM is an authentication module and not appropriate for local encryption schemes. However, we did merge support for polkit, which enables the use of fingerprints and other auth methods to allow quick unlock. That is being released at some point, but you can test it now using a snapshot build: https://snapshot.keepassxc.org 

https://github.com/keepassxreboot/keepassxc/pull/8983

**Comment by dvictori** [comment]
Thanks for the reply and explanation. Looking forward for the new release. And thanks for the great work on KeepassXC
