### ISSUE TITLE
Display bug in macOS 14 when switching monitors

### ISSUE THREAD

**Issue by robimac04** [keepassxreboot/keepassxc#10312]
## Overview
When at work, I use my MacBook in clamshell mode with two external displays (4k). When detaching the monitors and going back to my internal screen, KeePassXC is shown with stacked text:

![Screenshot](https://github.com/keepassxreboot/keepassxc/assets/19255328/60b316f6-f9fa-4f24-a866-dc72b0449432)

Then I can quit KeePassXC completely and reopen it again and everything shows up normally.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. use Mac in clamshell mode with external monitor
2. lock it and disconnect monitors
3. unlock Mac again with internal display and check KeePassXC font

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
KeePassXC and all content is shown correctly as it did before on the external monitor. Database names in tabs show up correctly.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
The text content is shown stacked (see screen shot). Text entry works fine, but also everything is shown stacked. Database names in tabs are not shown, since tabs are all spaced too small.

![Screenshot 2](https://github.com/keepassxreboot/keepassxc/assets/19255328/63bece43-d293-401c-97df-1e47c08692de)
![Screenshot 3](https://github.com/keepassxreboot/keepassxc/assets/19255328/465ad462-8109-4a2d-bdda-524bbc9bc089)

## Context
[NOTE]: # ( Give us any additional information you may have. )
- MacBook Pro 14" M1 Pro
- macOS 14.3.1 Sonoma
- external display is HiDPI (4K)

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.6
Revision: dd21def

Qt 5.15.10
Debugging mode is disabled.

Operating system: macOS 14.3
CPU architecture: arm64
Kernel: darwin 23.3.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 2.19.3

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS

**Comment by phoerious** [comment]
This is a Qt bug. Nobody knows why this happens and I haven't seen it in a while. In any case, we cannot fix it, only Qt can.
