### ISSUE TITLE
Clarification of FAQ answer about data compatibility

### ISSUE THREAD

**Issue by whateverusernameisnottaken** [keepassxreboot/keepassxc#10319]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

NOT NECESSARILY A BUG.
FAQ reads:
[Which password database formats are compatible with KeePassXC?](https://keepassxc.org/docs/#faq-format)
KeePassXC currently uses the KeePass 2.x (.kdbx) password database formats KDBX 3.1 and KDBX 4 as its native file formats. KDBX 2 files can be opened, but will be upgraded to a newer format. KeePass 1.x (.kdb) databases can be imported into a .kdbx file, but saving a .kdbx file as .kdb would be lossy, and saving to .kdb is not supported by KeePassXC.

I have no idea what this means. Two of my family members are using Keepass for Windows 2.x. Another family member is unable to open our .kdbx database in KeepassXC on her Mac. I don't know what (version) 3.1 and 4 means when Keepass is currently only in release 2.4.x. Could someone please clarify.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. 
2. 
3. 

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows/Linux/macOS
Desktop Env: Gnome/KDE/XFCE/Mate/Cinnamon
Windowing System: X11/Wayland

**Comment by droidmonkey** [comment]
If you are using the latest version of KeePass 2 for Windows then you are compatible with KeePassXC. If your family member cannot open the file then they are using the wrong password, key file, and/or hardware key -- or the file didn't transfer correctly. You don't have to know the difference between 3.1 and 4, you aren't using anything less than that.

**Comment by whateverusernameisnottaken** [comment]
Thanks very much for that. We'll keep testing and see what we did wrong or if it's just a wrong password.
