### ISSUE TITLE
Password generator is not good enough

### ISSUE THREAD

**Issue by theking2** [keepassxreboot/keepassxc#10329]
## Summary
must be at least 6 characters
must be fewer than 128 characters
must be different from email address
must include letters in mixed case and numbers
must include a character that is not a letter or number

## Examples
the password generator of keepassXC is not good enough for this website.

## Context
produce really good passwords

**Comment by droidmonkey** [comment]
seriously? Here, I just made 5 options for you using KeePassXC Password Generator:

FtV7Esj30jPVp$q
aJoV7S1Hy#zphFC
z#SMC9jFadOkhT9
LOY%DixczgGgQ9W
IxOThj42I1N##Dl

![image](https://github.com/keepassxreboot/keepassxc/assets/2809491/1578b0c6-f640-4386-9d4b-d53eb7d10079)
