### ISSUE TITLE
Various icons missing after compiling from source

### ISSUE THREAD

**Issue by r0ckarong** [keepassxreboot/keepassxc#1032]
## Expected Behavior
Following the compilation instructions from the Wiki should yield a fully usable application. The Snap package works fine but looks completely differently (for example much smaller window).

## Current Behavior
Various icons across the interface are missing and invisible. This breaks some workflows and is obviously not correct. The icons are not even replaced by placeholders or text but gone entirely. You can still hover over many buttons to see the tooltips but the actual button icon is invisible.

## Steps to Reproduce (for bugs)
1. Clone release/2.2.1 branch
2. Run instructions from Wiki with this cmake command:
```
cmake \                                 
    -DCMAKE_INSTALL_DATADIR="/usr/share/" -DWITH_XC_AUTOTYPE=ON -DWITH_XC_HTTP=ON -DWITH_XC_YUBIKEY=OFF -DWITH_TESTS=OFF -DWITH_ASAN=ON \
    -DCMAKE_BUILD_TYPE=Release ..
```
3. Launch resulting binary

## Debug Info
KeePassXC - Version 2.2.1
Revision: c8f5824554ad01def454d6a8a6d6dc0593ae2472

Libraries:
- Qt 5.7.1
- libgcrypt 1.7.6-beta

Operating system: Ubuntu 17.04
CPU architecture: x86_64
Kernel: linux 4.10.0-33-generic

Enabled extensions:
- KeePassHTTP
- Auto-Type

![screenshot from 2017-10-03 21-04-20](https://user-images.githubusercontent.com/4920542/31144435-0844b1da-a881-11e7-8d38-ce69f6bf27b2.png)
![screenshot from 2017-10-03 21-04-38](https://user-images.githubusercontent.com/4920542/31144438-084ca3fe-a881-11e7-9751-47db6975c205.png)

Compiled Build:
![compiled](https://user-images.githubusercontent.com/4920542/31144437-0847fe26-a881-11e7-84c9-9e60b9a4e152.png)

Snap Image:
![snap](https://user-images.githubusercontent.com/4920542/31144436-08473194-a881-11e7-842e-70513c242253.png)

**Comment by droidmonkey** [comment]
As a side note, we should get rid of all the boilerplate logic in the FilePath class regarding finding icons and instead use a combo of ```QIcon::fromTheme``` and ```QIcon::setThemeSearchPaths``` for non-linux builds.

http://doc.qt.io/qt-5/qicon.html#fromTheme

**Comment by phoerious** [comment]
I'd suspect you are starting the binary from the wrong CWD. If you compiled in debug mode, try starting it from the main directory. If you compiled in release mode, install it first and then start it from the install location.

**Comment by r0ckarong** [comment]
@phoerious I followed the instructions from the wiki. Clone, create a build folder, change to build folder, run cmake, run make -j8, install

Application is then installed into /usr/local/bin/keepassxc 

When I start this from that directory (or anywhere else), the icons are missing and the window is much larger than the Snap package. I don't see what I am doing wrong here.

**Comment by TheZ3ro** [comment]
Can you try executing this command? `ls /usr/share/keepassxc/icons/application/32x32/actions/*`

**Comment by r0ckarong** [comment]
```
ls -1 /usr/share/keepassxc/icons/application/32x32/actions/*
/usr/share/keepassxc/icons/application/32x32/actions/document-edit.png
/usr/share/keepassxc/icons/application/32x32/actions/document-properties.png
/usr/share/keepassxc/icons/application/32x32/actions/key-enter.png
/usr/share/keepassxc/icons/application/32x32/actions/view-history.png
```
Those are present.

**Comment by MichJB93** [comment]
getting the same thing on my windows 10 PC just upgraded today, and all system icons are missing

**Comment by droidmonkey** [comment]
how are you starting the application?

**Comment by r0ckarong** [comment]
@droidmonkey For me it doesn't matter. I can use the Gnome shell menu which relies on a desktop entry created during "make install" or run the binary directly from the installation directory as mentioned above (/usr/local/bin/keepassxc) both starts with missing icons.

**Comment by pmhahn** [comment]
While you are investigating this you can also remove share/icons/application/16x16/actions/message-close.png as it is sized 22x22
