### ISSUE TITLE
Add Export to JSON

### ISSUE THREAD

**Issue by gustavo-alberto** [keepassxreboot/keepassxc#10325]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
Export the database to a JSON file, making it easier to read by another application.
Let's say I wanted to import this JSON data into another application that reads and places the information in a specific layout for printing.
Exporting to HTML makes the final file with many pages, lots of white space, padding and non-configurable margins.

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )
In my case, I would develop a simple system to read this JSON and put it into a friendly print format with some configuration options.

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
The objective is to have a database that is simple to read and access, so that it can be treated however you want.

## Note
I know there is the option to export in XML, but for a web application that works natively with JavaScript, I believe that having a JSON base file makes communication much simpler.

**Comment by droidmonkey** [comment]
Let me tell you, after implementing two JSON importers from other password managers, it is not easy. KeePass databases are in XML. Exporting to JSON offers little advantage and would be a unique schema for our app apart from all other keepass apps. We won't spend time implementing this as a result.
