### ISSUE TITLE
Drag/Drop of group not working

### ISSUE THREAD

**Issue by Massimo-B** [keepassxreboot/keepassxc#10324]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
Drag/Drop of a group-tree does not work

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Open 2 databases
2. Drag a parent group with some sub groups from one database into the other one.
3. Drop the item on the other database above the root group

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
The new group tree should be copied to the other database and appear there below the root group.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Nothing happens.

## Context
[NOTE]: # ( Give us any additional information you may have. )
I tried all, dropping on the root group, dropping below, dropping on the item list etc.
The root group is highlighted when dragging above, but nothing happens on releasing the button.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.6
Revision: dd21def

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: XFCE
Windowing System: X11

**Comment by droidmonkey** [comment]
This works perfectly fine. Be sure you are dragging to the correct locations:


https://github.com/keepassxreboot/keepassxc/assets/2809491/b18e7b02-d7db-47d0-911a-5a6f11c62bf6

XFCE 4.18

**Comment by Massimo-B** [comment]
It's broken here, it sometimes works but sometimes not:

https://github.com/keepassxreboot/keepassxc/assets/3286728/12a28d60-3774-4cfd-b2c2-214b8cbae8b4

**Comment by droidmonkey** [comment]
That's very odd, is it only with that subfolder or any others? If you hold CTRL after dragging, does it work? Do you have any special settings applied to that folder, like disable search or auto type?

**Comment by phoerious** [comment]
Can you try whether the same thing happens we you remove non-ASCII characters from the group name?

**Comment by droidmonkey** [comment]
Group and entry moves are based on uuid, so the name shouldn't matter... but you never know.

**Comment by Massimo-B** [comment]
I retried: Moving a folder with "ä" in the name to a new database with root named "Foo" does fail.
Moving another folder without "ä" like "Firefox" to a new database works.
Moving a folder with "ä" in the name to a new database into that subfolder "Firefox" works.

I have now Foo->Firefox->...ä....

In that new database, moving the ...ä... folder back to the root folder "Foo" works.

I have now Foo->Firefox and Foo->...ä...

**Comment by Massimo-B** [comment]
Please re-open. I cannot.

**Comment by Massimo-B** [comment]
It's also sometimes failing when moving a folder tree without any `'ä'` characters inside, but only some `' - '` substring. But not with every subtree named like this, sometimes it works. I guess something in the tree breaks it.

**Comment by droidmonkey** [comment]
I still cannot replicate this problem with a group that includes unicode characters. Unfortunately I am not seeing any reason for the behavior you describe.

**Comment by Massimo-B** [comment]
I will try to create a minimal example DB file and upload that...

**Comment by droidmonkey** [comment]
That would be very helpful thank you

**Comment by Massimo-B** [comment]
I tried hard to reproduce, wasn't able to reproduce with 2 new databases NEWDB-01 and NEWDB-02.
While still having the issue when moving from my OLDDB-01 to OLDDB-02, I was able to move from OLDDB-01 to NEWDB-02 and back. Now moving from OLDDB-01 to OLDDB-02 also works and I can't reproduce the issue at all...
Let's close the ticket for now...
