### ISSUE TITLE
VCRuntime not found

### ISSUE THREAD

**Issue by bitshiftnetau** [keepassxreboot/keepassxc#10321]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # same issue as found here https://github.com/keepassxreboot/keepassxc/issues/7564 keep getting the vcruntime error on a fresh build of windows 11

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. install fresh build Windows 11 Pro version 10.0.22631 Build 22631
2. attempt installing keepassxc
3. proceed to have errors and install latest VC runtime, plus 2013 runtime
4. view errors 

## Expected Behavior
[NOTE]: # that it works 

## Actual Behavior
[NOTE]: # it doesn't even open

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION
Revision: REVISION

2.7.7-Win64

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows/Linux/macOS
Desktop Env: Gnome/KDE/XFCE/Mate/Cinnamon
Windowing System: X11/Wayland

![Screenshot 2024-02-22 181851](https://github.com/keepassxreboot/keepassxc/assets/26871600/efa01c5a-acf8-4292-b596-9da7cbca183b)

**Comment by droidmonkey** [comment]
Install the proper msvc runtime libraries.....

**Comment by bitshiftnetau** [comment]
I have, that is in step 2. 

I installed the latest ones, both x86 and x64, restarted, uninstalled KPX and installed, it did not work. I then did the same entire process with 2013 VC runtime

**Comment by bitshiftnetau** [comment]
Tested on another machine, worked fine. Something wrong with my machine.

**Comment by droidmonkey** [comment]
Install this one: https://aka.ms/vs/17/release/vc_redist.x64.exe

Anything else will not work.
