### ISSUE TITLE
Keeshare on a group subtree does not export groups

### ISSUE THREAD

**Issue by Massimo-B** [keepassxreboot/keepassxc#10323]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
Keeshare on a group subtree only exports plain list without the groups. I would expect the subtree to be exported. How does the Keehsare type "Sync" know which entry gets synced back to which group?

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Enable Keeshare on a group subtree
2. Set Type Synchronize
3. Choose a new file share.kdbx and set password

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
The new file should show the whole group subtree

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
It only shows plain list of passwords without any group

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.6
Revision: dd21def

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: XFCE
Windowing System: X11

**Comment by droidmonkey** [comment]
Duplicate

**Comment by Massimo-B** [comment]
This is duplicate of what?

**Comment by Massimo-B** [comment]
Hi, is there any news on this issue? This is an absolute blocker for using the Keeshare feature. Sharing a complete subtree of the database, the resulting shared database file looses all the folder-tree.

**Comment by droidmonkey** [comment]
This has been the case with keeshare since it was created. To solve this problem requires a complete rewrite to the feature.

**Comment by michaelk83** [comment]
> is there any news on this issue?

This is not going to be solved in a few weeks. There is a rework of KeeShare in progress AFAIK, but it's a big undertaking, which will take a while to finish. Probably not before 2.8.0. You can expect to wait a few more months, at least.

**Comment by Massimo-B** [comment]
To be honest I don't understand why the design forbids sharing a tree of items like it is, if it's really stored like a tree. But sure you know the internals far better.
I would be glad to see a rewrite of KeeShare.
I just found this feature very useful to be able to manage all content in one database while still being able to maintain shared subtrees in separate files with separate encryption passwords for sharing with others.

The workaround having linked databases does not fullfill the needs. It would encrypt with a different shared password and opening that shared subtree located in a separate file is also easy by double-clicking the kdbx:// hyperlink. But it still means opening a lot of separate databases and not being able to search in one monolithic database.

Currently the only workaround is, to copy-paste (by CTRL+drag/drop) all subfolders of that shared subtree manually to the other shared database.

**Comment by Massimo-B** [comment]
> Duplicate

Did you probably mean duplicate of #3045 ?

**Comment by droidmonkey** [comment]
Yes exactly that one

**Comment by Massimo-B** [comment]
> Probably not before 2.8.0. You can expect to wait a few more months, at least.

Is this feature and the rewrite actually part of the roadmap for 2.8.0?

**Comment by droidmonkey** [comment]
That's the plan
