### ISSUE TITLE
Automatically lock the database if Yubikey is removed.

### ISSUE THREAD

**Issue by savchenko** [keepassxreboot/keepassxc#10331]
## Summary
Automatically lock the database if Yubikey is removed.

## Examples
Add single integer parameter `X` to settings. 
KeePassXC will lock the database if Yubikey used to unlock the DB is not detected for `X` seconds and `X` is > 0.

## Context
Prevent DB staying unlocked indefinitely if hardware 2FA token is required to unlock it.

**Comment by droidmonkey** [comment]
#3616
