### ISSUE TITLE
Addition of features to help manage database size or otherwise cleanup database

### ISSUE THREAD

**Issue by sovamind** [keepassxreboot/keepassxc#10337]
## Summary
My Keepass database has gotten rather huge over the past decade (or two) and I was trying to figure out what was taking up all the space. Doing some searching online I found that other Keepass DB compatible applications provide utilities or features to help in cleaning up and managing your database size.  It would be great if we could get similar features added to KeepassXC.

## Examples
Some example features might be:
 - Display the size of each entry, in a table or format, that allows you to sort and find your largest entries
 - Ability to purge history on entries after a certain period or number of history revisions
 - Management of custom / fav icons that shows their size and number of entries using each one
 - Ability to report attachment size and review them, possibly even allowing images to be compressed or format to be changed
 - Find and remove duplicate entries
 - Other ideas?

## Context
When your database size gets larger it takes longer to sync between sources, is more likely to have conflicts during sync, takes longer to open and save, and generally performance suffers.  Right now the only way for people to clean up their database is manually going through entries or opening the database in another compatible application.

**Comment by sovamind** [comment]
Here is a FAQ from Keepass about database size and managing it: https://keepass.info/help/kb/faq.html#dblarge

**Comment by droidmonkey** [comment]
- Display the size of each entry, in a table or format, that allows you to sort and find your largest entries

Already possible, right click header in entry view and choose the size column to display. 

- Ability to purge history on entries after a certain period or number of history revisions

Already possible, go to Database -> Database Settings 

- Management of custom / fav icons that shows their size and number of entries using each one

Already possible, Database -> Database Settings -> click maintenance. You can purge unused icons from here. Icons are only stored once.

- Ability to report attachment size and review them, possibly even allowing images to be compressed or format to be changed

Not really necessary with the other options.

**Comment by sovamind** [comment]
Here is an article / tutorial from StrongBox on how to manage database size: https://strongboxsafe.com/updates/how-to-reduce-the-size-of-your-keepass-database/

**Comment by sovamind** [comment]
Good that some of this is already there, but even after purging history (max 10, max 2mb) and removing unused icons, it only saved 200k from my 20MB database.  I'm guessing that attachments of screenshots of recovery codes and TLS certificates are likely the culprit.  So, I disagree that a feature to help manage attachments is unnecessary.   I am (slowly) moving all my TLS certs to XQA databases, but that is a process, and I don't imagine that they are causing that much space to be taken up given their text nature.

**Comment by sovamind** [comment]
Trying to go through entries in the list view to find which are big isn't working great either. I have everything sorted into folders, many nested, and you have to click to go through each screen.  Being able to use the search box to search for entries over a certain size (like expired entries) would be a big help.

**Comment by droidmonkey** [comment]
> after purging history (max 10, max 2mb)

These are clearly not aggressive enough to handle your needs. Remember this is just purging _history items_ not the current data set. You may want to set the max size to something like 200 KB if database size is an important factor for you.

> Trying to go through entries in the list view to find which are big isn't working great either. I have everything sorted into folders, many nested, and you have to click to go through each screen.

Perfectly possible, you need to do a search first, we have a built-in one to handle this exact situation:


https://github.com/keepassxreboot/keepassxc/assets/2809491/7b49e3c8-f3c3-4fe2-b8c9-2d4ac5365dd4


As for your request to actually modify attachments, we are _not_ going to implement anything like that. Our program is not in the business of modifying your data and we are also not a file storage service.

**Comment by sovamind** [comment]
I do not see a way to do a search using size.  Or is it attribute?  Maybe you can give an example?

![image](https://github.com/keepassxreboot/keepassxc/assets/2078938/024c1436-d473-4111-ba37-0b5e86a4eae1)

**Comment by sovamind** [comment]
I'm also wondering if this feature request could stay open for longer than 24 hours so that others can comment and provide feedback.  Unless you speak for the entire team and are just saying no to the entire request/idea?

**Comment by droidmonkey** [comment]
I gave you numerous ways to accomplish your objectives. There is no need to search by size, just search and sort. Search for `*` to list all entries or use the built-in search choices. We don't want to keep adding features that duplicate existing capabilities or are not part of our core offering.
