### ISSUE TITLE
SHA-256 checksum mismatch (Windows executable installer)

### ISSUE THREAD

**Issue by knodderdachs** [keepassxreboot/keepassxc#1033]
Hi,

I downloaded the Windows executable installer from keepassxc.org and checked both the gpg signature and the sha-256 checksum (.digest).

The gpg signature is OK but the sha-256 checksum is different. I tried it yesterday and today. The checksum of the 32bit executable is correct.

Greetings
Torsten

**Comment by droidmonkey** [comment]
I must have made a clerical error. I will fix this

**Comment by droidmonkey** [comment]
I have corrected the problem. Sorry about that.
