### ISSUE TITLE
2.8.0-snapshot - Missing translations in Settings - Shortcuts

### ISSUE THREAD

**Issue by Stephan-P** [keepassxreboot/keepassxc#10335]
Missing translations in Settings - Shortcuts

I did export the latest .ts translation from Transifex, used QT-Linguist to release this into a .qm and copied the .qm into the translations folder. Also these three strings have been properly translated in Transifex Develop. So my guess is that these strings are not yet referenced with translations.

![image](https://github.com/keepassxreboot/keepassxc/assets/10008599/daaff639-e559-478e-92bd-06fa87425976)

**Debug info:**
KeePassXC - Version 2.8.0-snapshot
Build Type: Snapshot
Revision: a472ef8

Qt 5.15.12
Debugging mode is disabled.

Operating system: Windows 11 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.22631

Enabled extensions:
- Automatisch invullen
- Browserintegratie
- Passkeys
- SSH-agent
- KeeShare
- YubiKey
- Snel ontgrendelen

Cryptographic libraries:
- Botan 3.1.1

**Comment by droidmonkey** [comment]
These appear to be setup correctly in code: https://github.com/keepassxreboot/keepassxc/blob/develop/src%2Fgui%2FShortcutSettingsPage.cpp#L105

**Comment by Stephan-P** [comment]
Turkish is another language for which Transifex Develop shows 100% translation.
With UI language set to Turkish, the same three strings are presented in English.
![image](https://github.com/keepassxreboot/keepassxc/assets/10008599/471975e2-6e1b-4cc3-8c66-bc0d914571d1)

(Switching back to System default language now)

**Comment by Stephan-P** [comment]
Still in today's snapshot.
Missing translations in Settings - Shortcuts

After having updated Transifex Develop to 100% translated and reviewed, I performed an export of that .ts file, used QT-Linguist to release this into a .qm and copied the .qm into the KeePassXC\share\translations folder. 

Again, my guess is that these strings are not properly referenced to Transifex translations.

![image](https://github.com/keepassxreboot/keepassxc/assets/10008599/e8bf5a60-2b63-428c-bac8-d9defce1e39c)

Debug info:
KeePassXC - Version 2.8.0-snapshot
Build Type: Snapshot
Revision: 267928d

Qt 5.15.11
Debugging mode is disabled.

Operating system: Windows 11 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.22631

Enabled extensions:
- Automatisch invullen
- Browserintegratie
- Passkeys
- SSH-agent
- KeeShare
- YubiKey
- Snel ontgrendelen

Cryptographic libraries:
- Botan 3.1.1

**Comment by droidmonkey** [comment]
I'm working on it, can't figure out why qt doesn't pick these up
