### ISSUE TITLE
Auto-Type is not working with Firefox on Ubuntu

### ISSUE THREAD

**Issue by Aternus** [keepassxreboot/keepassxc#10338]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

Auto-Type is not working with Firefox on Ubuntu

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Install Firefox (either via snap or as a Deb package) and open a web page
2. Open KeePassXC and ensure there are credentials present for the web page
3. Press Auto-Type keyboard shortcut

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

Expected Auto-Type dialog to appear.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

Nothing happens.

## Context
[NOTE]: # ( Give us any additional information you may have. )

Tested Auto-Type with Google Chrome and it worked as expected.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.6
Revision: dd21def
Distribution: Snap

Qt 5.15.9
Debugging mode is disabled.

Operating system: Ubuntu Core 22
CPU architecture: x86_64
Kernel: linux 6.5.0-21-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.19.1

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: Gnome
Windowing System: Wayland

**Comment by droidmonkey** [comment]
You need to run Firefox using X11, not Wayland. Autotype is not supported on Wayland.

**Comment by Aternus** [comment]
Hey @droidmonkey , could you kindly explain what that means? I'm not familiar with how Ubuntu works internally and wondering how is it possible that it works perfectly with Google Chrome but doesn't with Firefox (on the same computer).

**Comment by droidmonkey** [comment]
Unfortunately it would take a lot to fully educate you on the matter, but there are excellent reading materials out there. This is also the same as https://github.com/keepassxreboot/keepassxc/issues/10133.

You have a choice:

1. Keep Firefox on Wayland and use the keepassxc browser integration instead
2. Switch off of Wayland entirely (on the login screen) and use X11 
3. Force Firefox to start using X11

I couldn't find the command line or config file options to do the third option, but with some searching you may be able to find them.

**Comment by Aternus** [comment]
Thanks for pointing me in the right direction @droidmonkey !

As it turns out, Firefox only has "wayland" and "xwayland" modes, "wayland" being default since version 121.
Switching to "xwayland" is very tricky since there are multiple ways that the system can launch the browser (shell/non-shell/GUI/mime/link).

After spending a couple of hours trying to figure out the solution for this, I thought about sharing it here for all the other folks who might need it.

# Switching to XWayland mode (X11)

1. Create (or edit) ~/.pem_environment
2. Add the following line: `MOZ_ENABLE_WAYLAND=0`
3. Make sure there is a new line at the end of the file (IMPORTANT)

The result should look something like this

```
MOZ_ENABLE_WAYLAND=0

```
4. Restart or logout/login
5. Verify that "Window Protocol" is "xwayland" by browsing to "about:support"

Note: You can check which windows are exposing X11 information by running `xwininfo` in the terminal and clicking on a window. If it displays something in the terminal it is X11 compatible.

**Comment by droidmonkey** [comment]
Awesome! Thanks for the share. It's unfortunate thru made this switch without really trying anyone.
