### ISSUE TITLE
With auto-save disabled, simple navigation is enough to flag the DB as needing to be saved

### ISSUE THREAD

**Issue by VerODyne** [keepassxreboot/keepassxc#10336]
## Overview

Expanding or collapsing folders, with no actual changes to entries, will mark the DB as changed and activate the flag to indicate the file should be saved.

## Steps to Reproduce
1. Go to settings and disable all auto-save options
2. Open a KDBX
3. Expand or collapse any folder

## Expected Behavior

After simple navigation (eg, expanding/collapsing folders), note that the DB name is now *flagged, and exiting will ask to Save/Discard.
Navigation should not 'dirty' the DB. Someone may have only wanted to look but not make changes, and shouldn't have to remember later whether there was a legit change pending or a non-data navigational shift.

## Actual Behavior

Any expand/collapse is considered a change, and the casual user will have to keep track if a long-held-open DB was *really* changed, or only navigationally (and thus safe to Discard).

## Context

KeePassXC - Version 2.7.6
Revision: dd21def

Qt 5.15.10
Debugging mode is disabled.

Operating system: Windows 10 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.19045

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 2.19.3

**Comment by droidmonkey** [comment]
Just save it. Why discard anything?  This is just how keepass databases work. The "state" of the groups is part of the database. 

See https://github.com/keepassxreboot/keepassxc/issues/9751

**Comment by VerODyne** [comment]
Just as a comment, KDBX files may maintain state, but I don't believe that's how old-school 'KeePass' works. Opening a KDBX will return to the last saved state, but expanding/collapsing folders will not force a write. Yes, if a save is selected, even though unnecessary, the state will be preserved. And re-ordering items will always prompt a save. 

As for "why discard anything?", it is borne out of paranoia. My comment has nothing to do with Yubikeys or multi-user. I may enter a KDBX on a Mon, for read-only purposes, and forget to exit. Then come Fri and the write flag is telling me something has changed. But I don't remember doing any such thing. Did a bit get flipped? Did someone access my machine illicitly? The alarm bells are going off.

I see from #9751, this closure is less about "not planned" and more about a setting change that will still approximate the desired behavior. This is acceptable, thanks.

**Comment by droidmonkey** [comment]
Your paranoia doesn't match your security posture. You should be locking your database often if that is a concern of yours (especially third party access).
