### ISSUE TITLE
Mozilla FireFox Multi-Account Containers Integration

### ISSUE THREAD

**Issue by influential-eliot** [keepassxreboot/keepassxc#10339]
## Summary
It would be great to start to build some integration with this amazing feature. 
 
Even if it is just for productivity purposes alone, the Multi-Account Containers (**_MAC_**) add-on for Mozilla browsers is astonishingly useful, and I think with the right KPXC integrations it could be even better.

## Examples
I've thought of a couple of potential ways this could be useful for starters, both of which would be implemented using an option to turn on the functionality in the KeePassXC database settings.

### Default Entry
This may be silly, but setting a default entry in either interface for a MAC then one would not have to scroll through potentially 10s/100s of entries to get to what's needed.

Yes, I know a good naming convention helps this, but having one surface to the top of the list could be immense for people that work with multiple accounts, regularly.
 
### MAC Pools
An extension of the above this would work more in the KeePassXC inteface and would basically allow for the defining of multiple 'Defaults' for given MACs.

This could be an additional sidebar option in the entry details when opened, or 

### Restrictive
KPXC DB entry can only be used for a **specific** MAC.

I don't actually have a use case for this, but I can see that it might be more useful for those performing hyper-secure work. 

Equally, though, folks could setup a MAC specific entry then a mirror for other containers, too.

## Context
I am a contractor, and I rely heavily on the MAC system to service multiple clients simultaneously.

It's very important to be able to easily pivot on request and immediately open a screen to (_for example_) a client's MS tenancy, or something.

Apologies if this is all a bit all over the place, but hopefully it's a spark of something. If not ... never mind, feel free to just close it without comment.

**Comment by droidmonkey** [comment]
Is this a native Firefox feature or a third party extension. I have no idea what this even is, link drop? Why would keepassxc have anything to do with this?

We restrict access to entries by url and require manual approvals (unless remembered) through the browser extension.

**Comment by JeanPluzo** [comment]
Hi,

MAC seems to be an [extension](https://addons.mozilla.org/en-US/firefox/addon/multi-account-containers/).
Extension seems pretty useful. Don't know if the integration is worth the time.

Regards,
J.

**Comment by droidmonkey** [comment]
Does seem useful, but I doubt there is even an integration point. Looks like the point of it is that no one but the user knows you are using MAC. I'm closing this since it just wouldn't be worth the time.
