### ISSUE TITLE
Keep password history

### ISSUE THREAD

**Issue by arabesc** [keepassxreboot/keepassxc#10345]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
It's important to keep history of newly generated and previously used passwords.

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
The new password can be copied and automatically cleared from the clipboard after some time - the new password will be lost.
The actual password can be accidentally overwritten - the actual password will be lost.
Sometimes it's important to have the previous password, e.g, to log into a cached domain account for which the current password has been updated.

**Comment by droidmonkey** [comment]
Password history (really entry history) is a core part of the program. Please refer to the user guide: https://keepassxc.org/docs/KeePassXC_UserGuide#_history

**Comment by arabesc** [comment]
- However, the core part doesn't import the history from 1Password where it's present. It's important, it's a rather significant loss.
- There is no history in the Password Generator. Just imagine: a new password is created, it's copied to clipboard, the Password Generator is closed, the new password is entered, clipboard is cleared by timeout - the new password is lost. Yep, it's a user's fault, but it can be quite troublesome.

**Comment by droidmonkey** [comment]
1Password doesn't export history

> There is no history in the Password Generator

This is 100% by design

**Comment by arabesc** [comment]
> _1Password doesn't export history_

I think the history is contained in OPVault, from which imports are supported by the core.
There's a related bug: [#5669](https://github.com/keepassxreboot/keepassxc/issues/5669)

**Comment by 1-61803** [comment]
I can confirm that on macOS Sonoma 14.0 importing in KeePassXC 2.7.9 OPVault files from 1Password 6.8.9 and 1Password 7.9.11 does not import their Password History.
Bug #5669 seems to still be valid then for versions 6 and 7.
