### ISSUE TITLE
HMAC Error

### ISSUE THREAD

**Issue by Corncoder49** [keepassxreboot/keepassxc#10340]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
After updating the app yesterday, I was no longer able to access the database. I get the following message: Error while reading the database: Invalid credentials were provided, please try again. If this reoccurs, then your database file may be corrupt. (HMAC mismatch)

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. 
2. 
3. 

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows/Linux/macOS
Desktop Env: Gnome/KDE/XFCE/Mate/Cinnamon
Windowing System: X11/Wayland

**Comment by droidmonkey** [comment]
You mistyped your password. Nothing we can do about that.

**Comment by Corncoder49** [comment]
That's the thing, I copied and pasted the password and verified it was the
same. It's weird.

**Comment by Corncoder49** [comment]
> You mistyped your password. Nothing we can do about that.

The password worked just before updating. I will just have to change all my passwords and always have a backup somewhere else.  Anyway, thanks

**Comment by JeanPluzo** [comment]
Hi,

if you're on windows and copying your pass from something like Excel or Word, you could have hidden characters in the paste process.
Copy your password to Notepad and copy it again from there. Or better yet, type your password.

Regards,
J.

**Comment by Corncoder49** [comment]
> Hi,
> 
> if you're on windows and copying your pass from something like Excel or Word, you could have hidden characters in the paste process. Copy your password to Notepad and copy it again from there. Or better yet, type your password.
> 
> Regards, J.

Ok. I will try that. Thanks

**Comment by Corncoder49** [comment]
> Hi,
> 
> if you're on windows and copying your pass from something like Excel or Word, you could have hidden characters in the paste process. Copy your password to Notepad and copy it again from there. Or better yet, type your password.
> 
> Regards, J.

You are a hero. You saved my day. Thank you very much. It worked. I typed it in. You live and learn

**Comment by droidmonkey** [comment]
Just going to say that if you are NOT typing your main password into KeePassXC then you are absolutely doing it wrong.
