### ISSUE TITLE
Windows Portable Download Link does not work

### ISSUE THREAD

**Issue by speendo** [keepassxreboot/keepassxc#1035]
Only a minor issue:

The download links:
https://github.com/keepassxreboot/keepassxc/releases/download/2.2.1/KeePassXC-2.2.1-Win64-Portable.zip
and
https://github.com/keepassxreboot/keepassxc/releases/download/2.2.1/KeePassXC-2.2.1-Win32-Portable.zip

that are mentioned here:
https://keepassxc.org/download#windows

do not work.

The links should probably point to:
https://github.com/keepassxreboot/keepassxc/releases/download/2.2.1/KeePassXC-2.2.1-Win64.zip
and
https://github.com/keepassxreboot/keepassxc/releases/download/2.2.1/KeePassXC-2.2.1-Win32.zip

**Comment by TheZ3ro** [comment]
Fixed. Thanks for the issue :)
