### ISSUE TITLE
[Enhancement] Add search for advanced "additional attributes"

### ISSUE THREAD

**Issue by ThiloteE** [keepassxreboot/keepassxc#10357]
## Summary
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
Have special syntax or toggle in search bar that allows to find text in "additional attributes" of "advanced".
Probably have another special "field".
"Attribute" does not work for this.

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )

Relevant fields in the UI:
![image](https://github.com/keepassxreboot/keepassxc/assets/73715071/e8a65f50-a286-4dde-8a52-319e2ce2817d)
![image](https://github.com/keepassxreboot/keepassxc/assets/73715071/c64eb54c-1423-4216-9a06-c2371e5d785e)

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )

- I have so many passwords and entries that I have to use the search bar to find entries in a fast way.
- I put something into "additional attributes" to avoid somebody looking at sensitive data when somebody looks over my shoulders or during a screen share
- I put something into "additional attributes" to avoid finding this specific content when using search.

This has following draw back:
- Sometimes I need to update similar content (e.g.  in "additional attributes" of multiple fields and I want to search for all entries with this specific "additional attribute". Doing such a search is currently not possible in KeePassXC 2.7.6.

Not sure, but maybe similar or related issue: https://github.com/keepassxreboot/keepassxc/issues/9152

**Comment by droidmonkey** [comment]
`attr:` searches both attribute keys AND values. I just tested it, works fine.

**Comment by ThiloteE** [comment]
I doesn't for me. Am I using the wrong syntax?

![image](https://github.com/keepassxreboot/keepassxc/assets/73715071/993f6530-8010-4dde-8d4b-8ec362da6552)

**Comment by droidmonkey** [comment]
Remove the space after the colon

**Comment by ThiloteE** [comment]
Uhh. You are right. Sorry for the noise!
Nice application btw! KeePassXC rules ;-)

**Comment by droidmonkey** [comment]
Thank you!

**Comment by soulstenance** [comment]
This is also extremely useful if you say, have a username for an account but also want to keep track of what email is tied to that account (especially if you use aliases for different accounts which I highly recommend). Very nice feature! Another option that would be nice is an option to just search all possible places where a searched item could show up.

**Comment by benjuade** [comment]
See https://github.com/keepassxreboot/keepassxc/issues/7967 if you want to search without the `attr:` key
