### ISSUE TITLE
Mouse cursor gets enlarged when it hovers over KeePassXC

### ISSUE THREAD

**Issue by K4LCIFER** [keepassxreboot/keepassxc#10359]
## Overview
When you hover the mouse cursor over KeePassXC it gets enlarged.

Normal size:

![image](https://github.com/keepassxreboot/keepassxc/assets/7829231/d2c04ae9-3c50-4e24-89e7-836159993ea1)

Giant size:

![image](https://github.com/keepassxreboot/keepassxc/assets/7829231/b8eb2eb3-5669-449c-943a-c51781c7f404)

## Steps to Reproduce
1. Open KeePassXC
2. Hover the mouse cursor over the window.
3. Observe that the mouse cursor gets enlarged.

## Expected Behavior
I would expect that the mouse cursor is unchanged when it hovers over the app.

## Actual Behavior
The mouse cursor gets enlarged.

## Context

This issue may be a duplicate of https://github.com/keepassxreboot/keepassxc/issues/9239.

This issue started happening immediately after I recently upgraded to KDE Plasma 6. Prior to the upgrade, it didn't happen. I suspect that there was some change to Qt that's making this happen, but I'm not sure. I have encountered it in other apps as well. Just in case this is an upstream issue, I have also opened up a bug report with KDE [here](https://bugs.kde.org/show_bug.cgi?id=482805).

KeePassXC - 2.7.6
Revision: dd21def

Operating System: Arch Linux, Kernel v6.7.8-arch1-1
Desktop Env: KDE Plasma v6.0.1
Windowing System: Wayland

**Comment by droidmonkey** [comment]
This is definitely not a KeePassXC issue, it is likely due to a conflict in your Qt environment variables or system settings.
