### ISSUE TITLE
Allow overriding of inactivity lock setting on a DB basis

### ISSUE THREAD

**Issue by sk33wiff** [keepassxreboot/keepassxc#10355]
## Summary
Add the option the override inactivity locking config value (Settings > Security > Lock Database after inactivity of) on a DB basis.

## Examples
Let's say I have "Settings > Security > Lock Database after inactivity of" set to 60 sec.

That suits all my password DBs usage, except for one which I would like to set a much higher value or disable it altogether. 

If this feature was available, I could then go to "Databases > Databases Settings > Security" and set a value for "Lock Database after inactivity of" specifically for this database I want a higher or no value at all for inactivity lock.  

## Context
I think this is relevant when using KeePassXC as an OTP manager along with other DBs which are used for different purposes.

**Comment by sk33wiff** [comment]
Being able to override these options would be nice too:
- Lock databases when session is locked or lid is closed
- Lock databases after minimizing the window

**Comment by droidmonkey** [comment]
Covered by #2224
