### ISSUE TITLE
Create a way to import a WIFI entry in the system

### ISSUE THREAD

**Issue by tobiasBora** [keepassxreboot/keepassxc#10358]
## Summary

Once we have a standard way to add wifi entries (see https://github.com/keepassxreboot/keepassxc/issues/8228), it would be cool to provide a way to create on the current system a wifi entry based (and also generate QR code, but this is already in https://github.com/keepassxreboot/keepassxc/issues/10000). I don't know much about windows, but in linux it should not be too hard to run an `nmcli` command to create the entry. It would be even cooler to be able to run this on all selected entries; it would be a very efficient way to recreate all wifi entries when using a new laptop etc.

During a first time we could focus on simple wifi entries (ssid/password). Later, it would be great to also support more complex wifi entries, for instance the one in eduroam where you need to enter a username, password, public key etc… that can be really tedious to configure otherwise.

Another related really cool feature would be to be able to do it the other way, i.e. import, again using nmcli, the parameters of existing wifi… but maybe for later.

## Examples

The interface could be as simple as right click (on one entry or selected entries) > create WIFI entry. Note that keepass2android already provides a template to add wifi entries, so we should certainly follow it.

## Context

I often need to re-enter already typed wifi entries. For instance, when you change computer, network manager would not recognize the old entries (I think because the name of the network interface is different), so you need to type again all wifi entries manually. Similarly, if you just connect with a different user, you need again to type all wifi entries that you want to share etc… really time consuming.

**Comment by droidmonkey** [comment]
We would not integrate with nmcli or anything like that. Use the `keepassxc-cli` tool and write a script to perform work like that. 

Special entry types are covered by #8228 and #863. Wifi specific entry has been requested in the past and we have rejected it since it is not specific enough to warrant its own category for a password manager. #4072

**Comment by tobiasBora** [comment]
> We would not integrate with nmcli or anything like that.

Why?

> write a script to perform work like that.

Well:
- a script is significanly less discoverable by users,
- is less practical (needs to reopen the database…)
- is less secure (what if the script keeps in memory the passphrase in a non-secure way?),
- is less interoperable (the way to represent wifi might be specific to this script and not compatible with other tools),
- is less accessible (you need to install yet another software),
- and unless it basically forks keepassxc, it requires significant efforts to create a nice GUI, for instance to select multiple elements at once based on their folder/tags/…

I can understand if this added a lot of complexity in keepassxc, but here it seems like it is just a quite basic loop + one command line to run… To me the benefits clearly overcome the drawbacks.

> Wifi specific entry has been requested in the past and we have rejected it since it is not specific enough

Well, you directly rejected it without a really fair discussion IMO… If wifi specific entries keep being asked, it might be because there is a need for it no?

> it is not specific enough to warrant its own category for a password manager.

The question is not about being specific or not, it is about being standardized to allow tools to perform actions on them in an interoperable way. Like a web page is not really specific (basically just a bunch of text with some errors), yet a protocol HTTP has been de. If every users uses its own way to represent a wifi entry (e.g. for eduroam right now I use comments!), there is no way other tools can be implemented.

**Comment by droidmonkey** [comment]
I am just being honest with you, we are not going to implement the requested feature and likely won't accept a PR for it either. It is outside the scope of a password manager to write entries into Network Manager. Further, this would be only applicable to Linux users. This is not a trivial request when you include all the GUI work, testing/debugging, and data standard requirements to support a wifi specific entry type.

**Comment by tobiasBora** [comment]
I'm not sure to see why the ssh agent that comes with keepassxc fits more in the context of a password manager but anyway. After all, storing passwords is not the main goal of a password manager, a simple encrypted file would do the same… to me the added value of a password manager is precisely to provide facilities to *use* these passwords, via browsers, via ssh, via network manager…

I completely understand why you may not want to implement it yourself, but no sure why you would refuse PR.

**Comment by droidmonkey** [comment]
Most PRs we receive are rather low code quality and require a ton of work to get right. 

I'm not trying to criticize your workflow, but why do you load every possible wifi configuration? Most people only have 1 or 2. That would not warrant a password manager having an _integration_. Autotype works great for that use case.

**Comment by tobiasBora** [comment]
> Most people only have 1 or 2. 

Well, I have 63 wifi connections. You go to visit a friend, you add a connection, you visit a parent, you add a connection, you go to visit a company/bar/train station/lab/ etc… I could of course certainly use keepassxc just to add the connection when I'm going to visit this place again… but, I would personally prefer to add in one go 63 connections the day I reinstall the computer rather than copy/pasting 63 times the connection password over the time. Personal taste maybe.

**Comment by michaelk83** [comment]
On Linux, Network Manager should be able to automatically save and restore its Wifi connections to KeePassXC via the Secret Service integration. If Network Manager doesn't support Secret Service yet, that should be taken up with them. I'm sure it's been requested before. You can search the closed issues here for mentions of Network Manager, and see if any of them have a link to a KDE issue.
