### ISSUE TITLE
KeePassXC shifts focus to last app (the browser) after launching it and while entering database password

### ISSUE THREAD

**Issue by heymarkreeves** [keepassxreboot/keepassxc#10363]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

When I open KeePassXC using Alfred on macOS Sonoma, it switches focus back to the browser's password field while I'm typing the password to unlock my KeePassXC database.

It occurs when I first launch KeePassXC after booting the computer and is incredibly awkward and frustrating. I'm accustomed to just Cmd+Tabbing to KeePassXC, doing a Cmd+F to find the account, and copying password's to my clipboard. I don't want browser integration.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Tab into a password field in a web browser. (I do not have  browser integration enabled.) 
2. Launch KeePassXC for the first time (it's not already open) by activating the Alfred HUD, typing KeePassXC, and hitting enter.
3. KeePassXC launches with the focus on the database password field, start typing the password.
4. KeePassXC switches focus back to the browser, and everything I've typed beyond the first two characters are entered into the password field in the browser.
5. Attempt to Cmd+Tab back to KeePassXC and it's at the end of the open apps, not "next to" the browser app where I can quickly return.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

As KeePassXC previously did, and as it seems to if it's already launched, I want to launch it, enter my database password if it's locked, do a Cmd+F for the account, Cmd+C to copy the password, and then Cmd+Tab back to the browser to paste it in. This automatic switch/focus completely breaks that workflow and risks me typing my database password into the browser password field.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

See steps to reproduce. KeePassXC switches focus back to the last app/the browser after launching and after I've started typing my database password.

## Context
[NOTE]: # ( Give us any additional information you may have. )

KeePassXC version is 2.7.6. I don't see any other updates available. This has been happening for a while, I think even before updating to macOS Sonoma.

I've been using KeePassXC for years. Thanks for maintaining it!

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.6
Revision: Revision: dd21def

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS

**Comment by droidmonkey** [comment]
I think you issue is with Alfred, not us. We don't switch focus unless you are performing Auto-Type or when copying a value to the clipboard and you have that option enabled.

Report back your results when you are NOT using Alfred. Closing otherwise.
