### ISSUE TITLE
Release preview 2.7.7 does not have binary assets for non-windows platforms

### ISSUE THREAD

**Issue by vraravam** [keepassxreboot/keepassxc#10367]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. The Releases page on GH for keepassxc does not show any artefacts for mac or linux
2. 
3. 

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
The Releases page on GH for keepassxc shows artefacts for mac, linux and windows

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
The Releases page on GH for keepassxc does not show any artefacts for mac or linux

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS
Desktop Env: 
Windowing System:

**Comment by droidmonkey** [comment]
Still PRE-release

**Comment by vraravam** [comment]
i am on the betas on macos and was hoping to test the pre-release for mac. Is that not planned?

**Comment by droidmonkey** [comment]
Be patient it will be up in a day
