### ISSUE TITLE
Allow newly created Passkeys to be added to an  existing entry

### ISSUE THREAD

**Issue by t4moxjc7** [keepassxreboot/keepassxc#10372]
## Summary
It would be useful if passkeys could be added to existing entries, rather than having to create separate entries.

Current workaround: exporting passkey from the new entry, importing that into the existing entry, then deleting the new entry.

## Examples
If you already have an account in the database (e.g. with password auth) and want to add passkey auth to it. 

## Context
Passkey support added v2.7.7.

**Comment by droidmonkey** [comment]
Easily done, select import passkey and choose an existing entry to import to.

**Comment by droidmonkey** [comment]
Sorry I misread. You want to use an existing entry at the point of Passkey creation. Good point, that is currently not possible. Nor is it possible to merge two entries (different issue) or directly migrate passkey data from one entry to another.

**Comment by varjolintu** [comment]
Maybe we could add a new button to the dialog that opens the Import Dialog instead (with a different title of course).

**Comment by droidmonkey** [comment]
That is what I was thinking too, could rename that dialog to "Choose Entry for Passkey" or something similar. Technically it is post-import.

**Comment by juvannx** [comment]
I think this merge should be done by browser extension. 
I don't think there is any other way to enter passkeys into keepassxc.
However, developing issue #2202 could also help a lot, once the passkey has been created you can merge with an existing item.
At the moment it's quite boring, after enabling the passkey on github I had to copy all the attributes of the existing item into new item

**Comment by varjolintu** [comment]
@juvannx The merge cannot be done in the extension side. See the linked PR in this issue for a solution.

**Comment by juvannx** [comment]
@varjolintu my fault, I described my suggestion in a wrong way, your PR does exactly what I wanted, I'll wait for version 2.7.8.
