### ISSUE TITLE
small font size

### ISSUE THREAD

**Issue by Cherkah** [keepassxreboot/keepassxc#10371]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
impossible to have kpxc size font corresponding to the general system font size. Even when scaling is enabled
A lot of sections from the Gui with text keep small font size ( buttons, labels, comboboxes, etc).

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
coherent font size with system font settings

## Context
[NOTE]: # ( Give us any additional information you may have. )
the system size font = 13 and scaling = 115%
but the keepassxc's font appears smaller:

![Copie d'écran_10 03 2024_15h14-1](https://github.com/keepassxreboot/keepassxc/assets/16431970/5ba53030-6a71-4f26-b20e-28dd289e1810)

![Copie d'écran_10 03 2024_15h14](https://github.com/keepassxreboot/keepassxc/assets/16431970/1ed5163e-7fc2-4b53-a4fe-ce8f4105d850)

i can observe this issue only for qt5 app 

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION 2.7.6
Revision: REVISION dd21def

```
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
...
QFont::fromString: Invalid description 'Noto Sans,13,-1,5,400,0,0,0,0,0,0,0,0,0,0,1'
QFont::fromString: Invalid description 'Noto Sans,13,-1,5,400,0,0,0,0,0,0,0,0,0,0,1'
QFont::fromString: Invalid description 'Hack,13,-1,5,400,0,0,0,0,0,0,0,0,0,0,1'
QFont::fromString: Invalid description 'Noto Sans,13,-1,5,400,0,0,0,0,0,0,0,0,0,0,1'
```

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux endeavouros
Desktop Env: KDE plasma 6
Windowing System: Wayland

**Comment by droidmonkey** [comment]
Try using the qt environment variables published in our user guide. Generally, qt doesn't support highly fractional scaling (1.15 in your case) on Linux. 

https://keepassxc.org/docs/KeePassXC_UserGuide#_command_line_options

**Comment by Cherkah** [comment]
ok
i corrected it by installing: plasma5-integration && kwayland-integration
i keep in mind your tips

resolved
