### ISSUE TITLE
Hide database file path

### ISSUE THREAD

**Issue by jumpinjellybeans** [keepassxreboot/keepassxc#10375]
Hello! Similar request to [Hide key file path _#5576](https://github.com/keepassxreboot/keepassxc/issues/5576)

For security reasons, could you provide an option to hide the database file path when unlocking the database?

Thx

**Comment by droidmonkey** [comment]
This wouldn't offer any security whatsoever, we only hide key file because it is actually part of your overall decryption key. Where your database is located is meaningless and frankly very easy to figure out anyway.

**Comment by jumpinjellybeans** [comment]
Do you understand what security is? Do you think clearly displaying where the database file is located helps with IT security? Even though security through obscurity alone might not be a strong defense, hiding files does add an extra layer of protection in making sensitive files less obvious. Why? Because it is harder for unauthorized users to identify, target, and swipe the whole file. Who cares about the decryption key when there's no database file, and it's likely some users will even store the key file in the same folder as the database file.

**Comment by jumpinjellybeans** [comment]
I'm curious now ... how do you store your database file since it's meaningless where it is located? Maybe your security is better than mine.

**Comment by droidmonkey** [comment]
I store it on my OneDrive because it is a secure service and the file is totally irrelevant without the credentials. That is the whole point of KeePass and KeePassXC.
