### ISSUE TITLE
Tell if a certain database was unlocked

### ISSUE THREAD

**Issue by br-olf** [keepassxreboot/keepassxc#10376]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )

I would really like to use keepassxc as secret service replacement. Therefore it would be awesome if I could figure out if a database was successfully decrypted so I can start applications that require the secret service functionality afterwards. 

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )

I start keepassxc with some command line flag so it opens a socket. When I read from that socket I get a list which databases are currently unlocked. 

Or using systemd I imagine the following process:
1. I log into my linux machine and my desktop starts
2. A systemd user service is triggered and starts keepassxc
3. I provide my database password and unlock the database
4. A systemd target is activated telling that the secret service is now available
5. Other systemd services start because the secret service target is now active

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
I'm using hyprland as a wayland compositor and I'd like to start element-desktop (matrix client) automatically at login. Currently I did not find a way to tell if my keepassxc is already running and has decrypted the respective database. Element behaves pretty silly and logs me out if it can't receive it's secret on time after start so I'm always getting logged out. Furthermore the login takes ages because it syncs all my groups and I lock myself out of my chats for at least 10 to 15 minutes every time that happens.

To be honest I don't care if it works like I described above at all I just want a way to safeguard myself from starting element-desktop without a running secret service.

**Comment by michaelk83** [comment]
Secret Service works via dbus, so you can use the dbus API to check if the service is available and running, and whether the relevant collection (Secret Service's equivalent of a database) has been unlocked or not. Usually you'd be looking for the `default` collection, which is what most apps would tend to use.
https://specifications.freedesktop.org/secret-service/latest/re02.html

You can also use `secret-tool` to probe the service, if you don't want to mess with dbus directly.

**Comment by droidmonkey** [comment]
We certainly won't implement an interface that tells if a _certain_ database is open, that leaks way too much information. Agree with @michaelk83, just query the secret service interface to know when it is available.

**Comment by br-olf** [comment]
@michaelk83 thanks for the idea with `secret-tool` that fixed my problem :+1:
