### ISSUE TITLE
Deleting History item causes crash in 2.7.7

### ISSUE THREAD

**Issue by dave0003** [keepassxreboot/keepassxc#10386]
## Overview
After upgrading from 2.7.6 to 2.7.7 on Debian Bookworm Flatpak, if I try to delete a History Item, keepassxc crashes and immediately exits.

## Steps to Reproduce
1. To reproduce, install 2.7.7 flatpak
2. Open an existing database that has history items
3. Try to delete one

## Expected Behavior
It should allow you to delete the item, save the database, etc.

## Actual Behavior
Instead, it crashes.

## Debug Info
KeePassXC - Version 2.7.7
Revision: 68e2dd8
Distribution: Flatpak

Qt 5.15.10
Debugging mode is disabled.

Operating system: KDE Flatpak runtime
CPU architecture: x86_64
Kernel: linux 6.1.0-18-amd64

Enabled extensions:
- Auto-Type
- Browser Integration
- Passkeys
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 3.3.0

**Comment by kery** [comment]
The same symptom occurs on Windows after upgrading to 2.7.7.

**Comment by droidmonkey** [comment]
Confirmed this crash is an invalid index crash. The culprit is this PR: https://github.com/keepassxreboot/keepassxc/pull/9947

Fixed it, will be part of 2.7.8

**Comment by Mushy-Snugglebites-badonkadonk** [comment]
Issue replicated on macOS 14.4.1
