### ISSUE TITLE
The text on the buttons is cut off when requesting a save

### ISSUE THREAD

**Issue by xboxones1** [keepassxreboot/keepassxc#10381]
## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Disable autosave
2. Make changes to the database
3. Close keepassxc

KeePassXC - 2.7.7
Operating System: Windows/Linux

**Comment by droidmonkey** [comment]
This is a bug with Qt on Linux. There is not much we can do to fix this problem

**Comment by xboxones1** [comment]
The text in Windows is also cropped a bit around the edges of the buttons

**Comment by michaelk83** [comment]
KPXC uses Qt on all OSes. Try adjusting the Qt scaling.
https://keepassxc.org/docs/KeePassXC_UserGuide#_command_line_options

**Comment by xboxones1** [comment]
This is not a scaling problem, the text looks the same at any value. The problem is only in these buttons, otherwise there are no problems.

**Comment by xboxones1** [comment]
@droidmonkey I've read up on this problem and as far as I understand it's not a bug. Need to resize the buttons. It's been looked at in more detail [here](https://stackoverflow.com/questions/51679073/how-to-make-qmessagebox-buttons-resized-to-fit-translated-text)

**Comment by droidmonkey** [comment]
> msgClose.layout()->setSizeConstraint(QLayout::SetMinimumSize);

This should be done by Qt, hence it is their bug. Sure we can do that ourselves (and we will, thank you for the share), but the UI framework should be handling overflow...

**Comment by xboxones1** [comment]
@droidmonkey Additionally, you need to change the base style as the size of dialogs and buttons is set there
https://github.com/keepassxreboot/keepassxc/blob/develop/src/gui/styles/base/basestyle.qss#L20-L22
I tested different values and came to the conclusion that this just needs to be removed, then the buttons scale correctly with the text.

**Comment by droidmonkey** [comment]
That doesn't make sense, ugh, I hate Qt styling

**Comment by xboxones1** [comment]
@droidmonkey without changing the base style, it doesn't work. Try building and see for yourself. This is also written about on [stackoverflow](https://stackoverflow.com/questions/51679073/how-to-make-qmessagebox-buttons-resized-to-fit-translated-text), the link was above. 

> My final solution includes answer as well as a stylesheet padding setting.

And See UPDATE 3

**Comment by droidmonkey** [comment]
This is still a qt bug...

**Comment by xboxones1** [comment]
I've seen them have the issue on bug reports. But they require sample code, without it they just close the ticket. I'm not a developer, I can't show them examples.

**Comment by xboxones1** [comment]
@droidmonkey You also need to delete these three lines
https://github.com/keepassxreboot/keepassxc/blob/develop/src/gui/styles/base/basestyle.qss#L20-L22
This setting prevents buttons and dialog from being scaled. Additionally, if you know how, you can center the message.

This is after removing these lines in the style settings, scales correctly.
![1](https://github.com/keepassxreboot/keepassxc/assets/91512529/41b350b3-0908-4762-9f17-e97d45b7a987)

**Comment by droidmonkey** [comment]
I will not remove those lines, we put that there for a reason, we want our dialogbox buttons to have a minimum width! Qt, however, treats that as license to squish the widget down to that minimum width without regard for the contents. That is a serious bug since there is _no way to set a minimum width otherwise_. 

Qt even considers this a feature, which is insane to me:
![image](https://github.com/keepassxreboot/keepassxc/assets/2809491/0e1cf8ef-3fb1-4c6d-8668-537015ea2456)

I added an attempt to wipe out the min-width setting if the QDialogBox is within a QMessageBox widget, see here: https://github.com/keepassxreboot/keepassxc/pull/10500/files#diff-dc3ecb5ff0e9757970323ce929d8a40fcaef9b80421087bab00147186dbb4abd

Can you test this PR for me?

**Comment by xboxones1** [comment]
After the fixes you've made, they will be minimum length anyway, and so you're just trimming the content of buttons and dialogs in other languages, the scaling won't work. 

I've tested your PR and it doesn't work. That's why I'm writing about the minimum width restriction.

**Comment by droidmonkey** [comment]
minimum length != minimum width. The min-width setting guarantees a button will be (in this case) at least 55px wide. So even if the text is "OK" it will be 55px wide. The widget should always be big enough to hold the contents unless some sort of overflow style is set, that is how CSS works.

Test it again if you haven't in the past day, I made a recent push.

**Comment by xboxones1** [comment]
I saw your new PR that's exactly what I've been testing. I built it before I wrote it

**Comment by droidmonkey** [comment]
I have another idea, just pushed, try it again

**Comment by xboxones1** [comment]
I was wrong about the length, I meant the width of course.

It's not working. 
![1](https://github.com/keepassxreboot/keepassxc/assets/91512529/63b283b4-fec4-4fd5-9e35-4773bb956f4b)

**Comment by droidmonkey** [comment]
OK, I replicated this on macOS, agree that doesn't work (I think cause the dialog is a child of MainWindow). Either way, I removed the min-width setting and nothing seems to be different in the application so I'll just remove it. Sorry about that, I should have tested just removing it to see if there were any poor effects in the first place.

**Comment by xboxones1** [comment]
The text is left-aligned to the icon. Will you be able to center it?

**Comment by droidmonkey** [comment]
Are you referring to the text within the message box? Why would it be centered, that wouldn't look good.

Also, we are programmatically enforcing an 80px min-width anyway:

![image](https://github.com/keepassxreboot/keepassxc/assets/2809491/64be4922-6e6a-4e7b-86cb-a408a2d1a711)

**Comment by xboxones1** [comment]
Yes the text in the message box, doesn't look good. 
![318189586-41b350b3-0908-4762-9f17-e97d45b7a987](https://github.com/keepassxreboot/keepassxc/assets/91512529/53e92398-9ea6-4366-8d1d-38183912a445)
