### ISSUE TITLE
Missing application menu with KDE and Wayland

### ISSUE THREAD

**Issue by kaikli** [keepassxreboot/keepassxc#10387]
## Overview
I'm missing the application menu for example to edit the database settings.
![image](https://github.com/keepassxreboot/keepassxc/assets/75146125/1f1185e9-d93d-4676-b90b-b52c96020d8f)

Normally this menu is located in the top left corner like in the following screenshot.
![image](https://github.com/keepassxreboot/keepassxc/assets/75146125/0ca9cba6-98d5-41e0-ae4a-d7c6e48e1e33)

[NOTE]:
KeePassXC - 2.7.6-3

[NOTE]:
Operating System: Arch Linux
Desktop Env: KDE 6.0.1
Windowing System: Wayland

**Comment by phoerious** [comment]
You have a global application menu widget somewhere.

**Comment by kaikli** [comment]
No, I have not. And even when I add one to my desktop it is empty.

**Comment by thomas725** [comment]
I have the same problem. Global Application menu widget is empty when switching to a KeepassXC window on a Plasma6 Wayland session.

Also minimizing to try doesn't work. hiding the window by clicking the tray icon only works if the window is currently active.
