### ISSUE TITLE
New bitwarden import function does not work for exported Organization Vaults

### ISSUE THREAD

**Issue by keenonkites** [keepassxreboot/keepassxc#10380]
## Overview
The new import function for Bitwarden JSON works properly for personal Vaults (encrypted or unencrypted json) but does not work for Organizational Vault, neither unencrypted nor encrypted.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. From Browser: export organizational vault to file (NOT Personal Vault), unencrypted
2. Import Database in KeepassXC
3. Choose Bitwarden (.json)
4. Choose previously exported json file (from organizational vault
5. Choose New or Existing DB (doesn't matter)
6. Dialogbox for import assistant shows 0 entries

## Expected Behavior
Finding and importing all entries from organizational vault export

## Actual Behavior
No entries are found, therefore nothing is imported

## Context
My assumption is that import assistant can only handle personal vaults due to different json formats/variables.
Personal Vault has:

- folders 
- items

Organizational Valut has:
- collections
- items

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION
Revision: 2.7.7

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS

**Comment by droidmonkey** [comment]
Please provide a sample json

**Comment by keenonkites** [comment]
Minimal sample json file from organizational vault. 

- Organization with only one member (user)
-  no special access rights set
- two top collections, each with one subcollection (nested)
- each of the four collections contains one user entry

[bitwarden_org_export_20240311123128.json](https://github.com/keepassxreboot/keepassxc/files/14557856/bitwarden_org_export_20240311123128.json)

**Comment by wexman** [comment]
I can confirm this problem, doesn't work for me either...

**Comment by wexman** [comment]
I have come up with a workaround: export from organizational vault, convert using the following jq expression and then import to keepassxc:

```
{
  "encrypted": .encrypted,
  "folders": .collections,
  "items": [.items[] | { "folderId": .collectionIds[0] } | del(.collectionIds)]
}
```

**Comment by theodejonge** [comment]
Can indeed be reproduced. Same issue here.

**Comment by keenonkites** [comment]
Confirmed proper working import today with 'proper' bitwarden organizational export (not just minimal test export)
Thanks for the useful enhancment.
