### ISSUE TITLE
Missing application menu with KDE and Wayland

### ISSUE THREAD

**Issue by kaikli** [keepassxreboot/keepassxc#10389]
## Overview
I'm missing the application menu for example to edit the database settings.
![image](https://github.com/keepassxreboot/keepassxc/assets/75146125/1f4a51ee-3b5f-4bb2-9623-16beb5ce8ad6)

Normally this menu is located in the top left corner like in the following screenshot.
![image](https://github.com/keepassxreboot/keepassxc/assets/75146125/53a3eb51-4fe5-43ad-8757-767f8486b456)

https://github.com/keepassxreboot/keepassxc/issues/10387 @phoerious 

> You have a global application menu widget somewhere.

No, I have not. And even if I add one to my desktop it is empty.

[NOTE]:
KeePassXC - 2.7.6-3

[NOTE]:
Operating System: Arch Linux
Desktop Env: KDE 6.0.1
Windowing System: Wayland

**Comment by phoerious** [comment]
Please stick with the old report instead of opening new ones.
This is a bug in KDE or your desktop configuration. There is nothing that we can do.

**Comment by kaikli** [comment]
Most of the time you are getting ignored when someone closes your issue directly and I cannot reopen the issue by myself.

Found this in my logs. I really don't know if this is a problem with kde or keepassxc and the error does not really explain anything.

> 11/03/2024 17:38	systemd	Started KeePassXC - Password Manager.
> 11/03/2024 17:38	kded6	org.kde.plasma.appmenu: Got an error
> 11/03/2024 17:38	kded6	org.kde.plasma.appmenu: Got an error
> 11/03/2024 17:38	kded6	Registering ":1.362/StatusNotifierItem" to system tray

**Comment by phoerious** [comment]
Looks related at least. You are using a DBus menu (global or in your window title bar, doesn't matter). This is between Kwin and Qt. There is nothing we can do.

**Comment by droidmonkey** [comment]
By definition you have a non-standard setup because no Linux distro places app menu in a drop down "hamburger menu" by default. Any fault with that setup is the responsibility of that app menu plugin. Please report this problem to them.

**Comment by kaikli** [comment]
> This is between Kwin and Qt. There is nothing we can do.

Maybe but keepassxc probably makes something different than every other application that I am using. I think it would just be nice to narrow the problem a little bit down.

> no Linux distro places app menu in a drop down "hamburger menu" by default

Any option that is possible to display a application menu does not work for me. And this is the builtin application menu titlebar button in kde.

Don't know why I did not see the error `keepassxc	qt.qpa.wayland: Wayland does not supportQWindow::requestActivate()` before. Maybe this relates to the problem?

> 12/03/2024 00:45	systemd	Started KeePassXC - Password Manager.
> 12/03/2024 00:45	kded6	org.kde.plasma.appmenu: Got an error
> 12/03/2024 00:45	kded6	org.kde.plasma.appmenu: Got an error
> 12/03/2024 00:45	kded6	Registering ":1.115/StatusNotifierItem" to system tray
> 12/03/2024 00:46	keepassxc	qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
> 12/03/2024 00:46	kded6	org.kde.plasma.appmenu: Got an error
> 12/03/2024 00:46	kded6	org.kde.plasma.appmenu: Got an error
> 12/03/2024 00:46	keepassxc	qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
> 12/03/2024 00:46	kwin_wayland	kwin_core: Could not find window with uuid "{6aeeec05-7e4e-40e7-ae07-507fb124142b}"
> 12/03/2024 00:46	keepassxc	qt.qpa.wayland: Wayland does not support QWindow::requestActivate()

**Comment by phoerious** [comment]
> By definition you have a non-standard setup because no Linux distro places app menu in a drop down "hamburger menu" by default. Any fault with that setup is the responsibility of that app menu plugin. Please report this problem to them.

It's not really non-standard. DBus menus are a thing and Qt supports them. But something's going wrong here outside our control. Qt thinks the DBus interface exists and is set up (which is why the menubar is hidden), but the window manager/desktop environment doesn't show the menu contents. Could it be that the rest of your environment is Qt6-based? Maybe that's incompatible with our Qt5 app.

**Comment by kaikli** [comment]
Yes, thank you. I found some other Qt5 application with the same behavior.

I have opened a bug for the KDE project.
https://bugs.kde.org/show_bug.cgi?id=483335

**Comment by meatspinner** [comment]
I'm having the same issue on Plasma 6 with X11, not even  pressing "alt" shows the menu bar. Weirdly, as opposed to OP, if I switch to Wayland the menu bar shows up.

Edit: I typed "CTRL+SHIFT+A" to disable "Always on Top", and the menu bar showed up again.

It seems that whenever "Always on Top" is enabled the menu bar disappears.

**Comment by droidmonkey** [comment]
Anything that hides the menu bar is 100% on your desktop environment (plasma 6).

**Comment by PapierFliegr** [comment]
For anyone running into the same issue on Plasma 6:
Check if you have `plasma5-integration` installed 
If not, install and reboot

**Comment by thomas725** [comment]
@PapierFliegr thank you for the hint. I didn't have it installed, but installing and rebooting sadly didn't fix the issue for me.
Whenever I bring the KeepassXC window to the foreground, I see this log entry spammed tens of times:
`plasmashell[1099]: org.kde.plasma.keyboardindicator: Unknown key Qt::Key_Alt`
Is this the cause?

UPDATE: I've solved the issue on my machine by removing the global menu widget from my panel and adding
the line `HideMenubar=false` to the `[GUI]` block in the file `~/.config/keepassxc/keepassxc.ini`
as suggested by user @linux_aarhus [here](https://forum.manjaro.org/t/qt5-keepassxc-on-plasma6-menu-missing-theme-broken-when-restarting/166398)

**Comment by pmetras** [comment]
Though I'm not under Linux/KDE, but I have exactly the same problem under Windows 11: no menu bar. It only shows temporarilly when pressing the [Alt] key.
I'm not sure it's a platform bug. It seems more related to Qt or KeePassXC.

**Comment by droidmonkey** [comment]
Press Alt to show the menubar, then go to View -> Show menubar

**Comment by pmetras** [comment]
I'm miles away from the Window computer and I can't take a screenshot, just to show that there is no "Show menubar" menu option under Win 11. I've seen this advice multiple time, but it's not applicable: this menu option does not exist. I've even changed the UI language, in case it was an untranslated menu option: nope. There's no "Show menubar"; only "Show preview panel" and "Show toolbar" as show something options.

**Comment by droidmonkey** [comment]
Then you aren't running 2.7.9. Either way this report is for KDE/Linux...
