### ISSUE TITLE
Global Auto-type never works at  first attempt after upgrade to 2.7.7

### ISSUE THREAD

**Issue by virgoparna** [keepassxreboot/keepassxc#10383]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
When using global auto-type shortcut to enter password, then it does not work, if database is locked. Instead original password entry window will be inactive. Selecting it again and then doing global auto-type again before database locking works.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. database must be locked
2. On active password prompt press global autotype shortcut 
3. Enter master password
4. Select entry
5. press enter to confirm

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Password is entered to that dialog

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Dialog window is inactive, nothing is entered. When selecting dialog again and pressing shortcut again password is filled correctly (if it is done before database is locked again).

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.7
Revision: 68e2dd8

Qt 5.15.11
Debugging mode is disabled.

Operating system: Windows 11 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.22631

Enabled extensions:
- Auto-Type
- Browser Integration
- Passkeys
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 3.1.1

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 11

**Comment by droidmonkey** [comment]
Yah the search is broken from an unlock state, not sure how that happened still investigating

**Comment by moya2162** [comment]
Confirmed issue myself. 2.7.7

For me it occurs on a desktop app that i have auto type set up on. I select the window, hotkey auto type, unlock db, then search window pops up rather than auto selecting my account based on setup.

**Comment by droidmonkey** [comment]
This was fixed for 2.7.8

**Comment by virgoparna** [comment]
Confirmed working in 2.7.8.
