### ISSUE TITLE
Browser Integration does not fallback when passkey is not present

### ISSUE THREAD

**Issue by scout-zz** [keepassxreboot/keepassxc#10393]
## Overview
Browser Integration does not fallback when passkey is not present

## Steps to Reproduce
1. Create an empty database
2. Open/reload that database using the Chrome Browser Integration
3. Go to: https://github.com/login
4. Click on "Sign in with a Passkey"

## Expected Behavior
Since I do not have a Passkey stored in KeepassXC for this site I would expect the fallback mechanism to cause Chrome's internal Passkey implementation to come up asking me to select a type of passkey

## Actual Behavior
1. After clicking on "Sign in with a Passkey" the Passkey browser integration shows: "Error! No logins found"
2. The login page spinner goes forever with the message "Waiting for input from browser interaction..."

## Context
Chrome's internal Passkey prompt comes up correctly if the browser integration plugin is disabled or the database is closed.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.7
KeePassXC-Browser - 1.9.0.1

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS

**Comment by scout-zz** [comment]
Additional context: In the plugin configuration both "Enable Passkeys" and "Enable Passkeys fallback" are enabled.

**Comment by varjolintu** [comment]
Already covered in here: https://github.com/keepassxreboot/keepassxc-browser/issues/2140
