### ISSUE TITLE
Password generator with sets of password requirements possibly as drop down list

### ISSUE THREAD

**Issue by thiemo-taken** [keepassxreboot/keepassxc#10390]
## Summary
Password generator with sets of password requirements, possibly as drop down list.

## Context
Applications can have very distinctive requirements for passwords with respect to length, allowed or required characters. While there is virtually a limited number of applications, there is an unlimited number of users having a very hard time in generating suitable passwords due to sh*tty documention on the applications. Oracle is, as time of writing, giving me pains.
It would be great if one could save password requirement sets (maybe as JSON file) and provide those to others, possibly with an upload download button. To select a set, a drop-down box seems to be feasible or just a file open/save dialogue. Apart from the actual requirement sets like character classes, min/max length etc. I also would store (possibly require) a name and a valid URL where the criterion can be read. Each time a set is selected, the length of the password is set to the maximum length of the selected requirements.

**Comment by thiemo-taken** [comment]
Oracle 23 has the information in https://docs.oracle.com/en/database/oracle/oracle-database/23/sqlrf/CREATE-USER.html#GUID-F0246961-558F-480B-AC0F-14B50134621C

**Comment by michaelk83** [comment]
#2628
