### ISSUE TITLE
Softwareupdate window frozen

### ISSUE THREAD

**Issue by tpk109** [keepassxreboot/keepassxc#10395]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. 
2. 
3. 

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows/Linux/macOS
Desktop Env: Gnome/KDE/XFCE/Mate/Cinnamon
Windowing System: X11/Wayland

**Comment by tpk109** [comment]
![Screenshot 2024-03-12 091000](https://github.com/keepassxreboot/keepassxc/assets/6112444/69f42290-56d0-416d-883b-b758ba6a7399)
After clicking something (the link to the update?) the window went blank but showed something like "));". Now I can't close it, not even in Task Manager.

**Comment by tpk109** [comment]
Version 2.7.4

**Comment by droidmonkey** [comment]
Recommend just uninstall 2.7.4 and install 2.7.7
