### ISSUE TITLE
Fetching the Favicon on a passkey entry gives wrong domain's icon.

### ISSUE THREAD

**Issue by ToxicMushroom** [keepassxreboot/keepassxc#10398]
## Overview
Fetching the Favicon on a passkey entry gives wrong domain's icon.
![image](https://github.com/keepassxreboot/keepassxc/assets/32853531/31660a63-ff71-4310-8991-ddf81f08e263)
Should use 
![image](https://github.com/keepassxreboot/keepassxc/assets/32853531/b415d1f9-02be-4d5d-8a3f-9a7ef244f266)

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. I registered a passkey for a subdomain of mine: `idm.melijn.com`.
2. I then clicked download favicon on the entry and it fetched the icon of `melijn.com`

## Expected Behavior
Fetches the icon of `idm.melijn.com`

## Actual Behavior
Fetches the icon of `melijn.com`

## Context
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.7
Revision: 68e2dd8

[NOTE]: # ( Pick choices based on your environment )
Operating System: Arch Linux
Desktop Env: Sway
Windowing System: Wayland

**Comment by droidmonkey** [comment]
Does the same happen for a non passkey entry? I suspect this is because you do not have a favicon.ico for your subdomain.

**Comment by ToxicMushroom** [comment]
Yes this also seems to have affected the normal entries now. Was the fetching algorithm changed in the new release 2.7.7 ? 
The favicon is set by the website using `<link rel="icon" href="/pkg/img/favicon.png">`

**Comment by droidmonkey** [comment]
Nothing was changed regarding favicon fetching. We don't pull favicon from the html. You need to provide it as favicon.ico or its available through duck duck go service.
