### ISSUE TITLE
Appimage - unable to fetch favicon

### ISSUE THREAD

**Issue by FlowXP** [keepassxreboot/keepassxc#10392]
Hello,
the Appimage version 2.7.7 of Keepass does not download favicons from any URL.
**Appimage v.2.7.5** was working fine.
The Windows and the  installed Ubuntu version 2.7.7 are working fine.

KeePassXC - Appimage 2.7.7

Operating System:  MX Linux 23.2
Desktop Env: KDE 5.27.5
Windowing System: X11

![Screenshot_20240311_214714](https://github.com/keepassxreboot/keepassxc/assets/6423705/abd9cee3-ca7d-4c66-872a-cff4c3da1647)

**Comment by phoerious** [comment]
Probably a mismatch in your OpenSSL version.

**Comment by droidmonkey** [comment]
We won't fix this issue as it's almost impossible to fix without embedding openssl to the appimage (not best practice). Recommend switching to flatpak for better performance and more modern experience.
