### ISSUE TITLE
2.7.7: Cursor doesn't focus on search field after database unlock

### ISSUE THREAD

**Issue by Caddode** [keepassxreboot/keepassxc#10405]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Start
2. Login
3. Nothing happens

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
In 2.7.6 
1. Start
2. Login
3. Cursor direcly in the Search Field

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
in 2.7.7. nothing happen

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION 2.7.7.
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 11 PRO
Desktop Env: Gnome/KDE/XFCE/Mate/Cinnamon
Windowing System: X11/Wayland

**Comment by ecables** [comment]
I came here because of this issue, after upgrading to 2.7.7, so +1 on getting this fixed.

**Comment by powerarmorpatch** [comment]
Same here. If you install KeePassXC as flatpak and looking to downgrade to 2.7.6 you may try:
```
flatpak update --commit=bee71bce744c659455c504dfb535464dec303fc9d33ff81197cdc9b3a7f4621b org.keepassxc.KeePassXC
```

Add `sudo` if KeePass is installed at system level.

**Comment by droidmonkey** [comment]
I cannot find where the fault is that introduced this bug, still looking.

**Comment by efojs** [comment]
There was a checkbox to enable it. But can't find it now.
I mean it was not enabled out of the box.
