### ISSUE TITLE
[Passkeys] Should not ask to update if new user handle

### ISSUE THREAD

**Issue by timcappalli** [keepassxreboot/keepassxc#10404]
## Overview

In WebAuthn, the user handle (e.g. user.id) identifies the unique user account. An authenticator should only have a single credential per user handle, and can have multiple user handles for the same relying party

## Steps to Reproduce

1. Use WebAuthn.io to create a passkey
2. Accept the prompt in KeePassXC to create it
3. Refresh WebAuthn.io and create a new passkey (this will have a new user handle)
4. KeePassXC will ask you if you want to update the existing passkey

<img width="686" alt="image" src="https://github.com/keepassxreboot/keepassxc/assets/6476604/15e3fd5c-34f2-4cfe-ac3d-707f3d3de20a">

## Expected Behavior

1. Use WebAuthn.io to create a passkey
2. Accept the prompt in KeePassXC to create a new passkey
3. Refresh WebAuthn.io and create a new passkey (this will have a new user handle)
4. Accept the prompt in KeePassXC to create a new passkey

## Actual Behavior

When the user handle (user.id) is different, it should be a fresh passkey creation prompt, not an update.

## Context

KeePassXC - Version 2.7.7
Revision: 68e2dd8

Qt 5.15.11
Debugging mode is disabled.

Operating system: macOS 14.4
CPU architecture: arm64
Kernel: darwin 23.4.0

Enabled extensions:
- Auto-Type
- Browser Integration
- Passkeys
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 3.1.1

**Comment by droidmonkey** [comment]
Technically, it's not a bug, more preference. We offer the ability to register a new entry on that same dialog. I prefer this dialog where there is a choice to overwrite (update) or create new.
