### ISSUE TITLE
References based on other fields than ID

### ISSUE THREAD

**Issue by mulmi** [keepassxreboot/keepassxc#1040]
In KeePass, you can reference other entries e.g. by their title, which is much more intuitive than using the long UUID.

## Expected Behavior
You should be able to enter {REF:U@T:Windows Account} into the user name field, and retrieve the user name from the entry titled "Windows Account".

## Current Behavior
The reference is placed as a verbatim in the user name / password fields.

## Context
I have a hard time figuring out dependencies between the individual entries when I have to check for UUID to find out which entry I referenced. It also makes debugging of misplaced references much harder.

## Debug Info

KeePassXC 2.2.1
Revision: 2bce9c8add07226e9a05e9e0fd0e5e66b236d5b6

Libraries:
- Qt 5.7.1
- libgcrypt 1.7.6-beta

Operating system: Ubuntu Core 16
CPU architecture: x86_64
Kernel: linux 4.10.0-35-generic

Enabled extensions:
- KeePassHTTP
- Auto-Type
- YubiKey

**Comment by mulmi** [comment]
If I find the time I will create a patch in my spare time. Is there anything I have to be aware of before contributing?

**Comment by TheZ3ro** [comment]
@mulmi you should read the [CONTRIBUTING.md](https://github.com/keepassxreboot/keepassxc/blob/develop/.github/CONTRIBUTING.md) doc, then you are ready

**Comment by frostasm** [comment]
@mulmi  how's it going? I can deal with this issue in my spare time.

**Comment by mulmi** [comment]
Sure, go on. I have not started yet. :)

@mulmi<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_mulmi&d=DwMCaQ&c=k6LEwkJiSX1kJxtgPu1uYQ&r=LkzBezQvw5XBY-NU0qkB828HRMEWyyAHDWW0hs6oihc&m=vkUnH6gsoxVgh4d15NgVTLfAh97SjwFWKa5Hqjk1kXc&s=0z8cle_xReXHpYBoAkk3hqon-9mNkE-IQqDBRrdBErw&e=> how's it going? I can deal with this issue in my spare time.

**Comment by Logout22** [comment]
@frostasm I started development now, I hope you are not too far yet. ;)
See https://github.com/Logout22/keepassxc

**Comment by frostasm** [comment]
@Logout22 I finished a few minutes ago :D 
https://github.com/frostasm/keepassxc/tree/implement-resolving-for-references-placeholders

**Comment by frostasm** [comment]
@Logout22 if you have the possibility, please test my changes. I will be glad of constructive criticism.

**Comment by Logout22** [comment]
Can you point me somewhere? I did not see a pull request and develop seems to contain the old behavior still.

**Comment by frostasm** [comment]
I plan to create pull request in the next hour or two. 
[diff from develop branch](https://github.com/keepassxreboot/keepassxc/compare/develop...frostasm:implement-resolving-for-references-placeholders?expand=1)

**Comment by Logout22** [comment]
@frostasm Great! I just pushed one more test and added the capability to resolved UUIDs (which is also legal, although probably not often used). I created a pull request: https://github.com/frostasm/keepassxc/pull/1
If you do not like it I won't mind.
