### ISSUE TITLE
Small translation issues

### ISSUE THREAD

**Issue by danielX337** [keepassxreboot/keepassxc#10409]
Hi,

please fix some small translation issues.

Running KeePassXC 2.7.7 under MacOS 14.4

In the first menu there are still some English entries, all of the other menu entries are correct translated / displayed in German.

Kind regards,
Daniel
![2024-03-12_19-09-01](https://github.com/keepassxreboot/keepassxc/assets/10390544/15c84734-9d5e-4217-9e46-b4e13cb8e01b)

**Comment by droidmonkey** [comment]
Translations are performed in Transifex per our contributing document. Please head over there to help contribute.
