### ISSUE TITLE
Delete in memo deletes post

### ISSUE THREAD

**Issue by MeTheLight** [keepassxreboot/keepassxc#10413]
I have clicked an post to access it and I have written something in the memo for that post and I thought in my mind I had 
open that post and I wanted to delete somehting in the memo which I forgot that i was not in edit mode and I pressed DEL key 
to delete the marked part of the memo text I wanted to remove, instead I did delete the hole post. 

This I did not realize until I was supposed to get the login details today and realized the hole post was not there it was totally gone. 
Now I thu could find the deleted post in the trashcan, but I did not get any warning when I did press the DELETE key which I thougth was removing the text not to delete the hole post. 

Solution:
Please Update the security so if I press Delete key and Im about to remove/delete the hole key post, then let the user know you are
about to delete the hole post. An setting for this could also be added if you feels it neccesserly

**Comment by droidmonkey** [comment]
We have a setting to confirm before sending to recycle bin, go to application settings to enable it.

**Comment by MeTheLight** [comment]
Yeah I did see that now, but yesterday I did not see it sry to say. And in my case of course that settings was checked so I did not get any warnings.
