### ISSUE TITLE
Allow users to insert multiple URLs for the same entry in the KeePassXC application

### ISSUE THREAD

**Issue by nbro** [keepassxreboot/keepassxc#10419]
## Summary

Other password managers I've used in the past allow us to insert multiple URLs for the same entry.

KeePassXC allows us to add additional URLs, but only if you have the browser integration/plugin. I don't see why this must be limited to this case or why we must do this in this way when the entry is not part of the browser group. I know we can add comments to each entry (where we can add the additional URLs), but I think it makes more sense to allow us to insert multiple URLs directly in the entry (like other password managers, like JumpCloud Password Manager), and not add them to the browser integration.

I'd assume this was already asked many times in the past, so feel free to close this or the others, if this is a duplicate.

**Comment by droidmonkey** [comment]
Use advanced attributes to store any number of urls if you aren't using the browser integration. You are just asking for a UI for it (which we have for browser integration). This is covered by other requests already so closing.

**Comment by nbro** [comment]
@droidmonkey Ok, but why can't you add the possibility to just add multiple URLs where the main URL is specified? Like I said, I can add the URLs even to the `Notes` section, so you missed the point.

**Comment by droidmonkey** [comment]
It's a UI problem, not a data problem. Other issues are requesting this capability

**Comment by nbro** [comment]
@droidmonkey Which other issues are specifically requesting this UI feature? Maybe it would be nice to link them, if you plan to solve them, i.e. add this feature.

**Comment by droidmonkey** [comment]
#8228 and #863
