### ISSUE TITLE
would there ever be an android version?

### ISSUE THREAD

**Issue by RakibRyan** [keepassxreboot/keepassxc#10418]

**Comment by Obrotuwa** [comment]
From https://keepassxc.org/docs/

> [Does KeePassXC work on mobile phones? If not, which app would you recommend?](https://keepassxc.org/docs/#faq-platform-mobile)
> We don't have our own mobile app, but you can have the same functionality on both Android and iOS!
> 
> For Android, we recommend [KeePassDX](https://play.google.com/store/apps/details?id=com.kunzisoft.keepass.free) and [KeePass2Android](https://play.google.com/store/apps/details?id=keepass2android.keepass2android).
> And for iOS, we suggest [Strongbox](https://itunes.apple.com/us/app/strongbox-password-safe/id897283731) and [KeePassium](https://apps.apple.com/us/app/keepassium-keepass-passwords/id1435127111).
> For KeePassXC, porting it properly to mobile platforms would require a full rewrite. You may be able to compile KeePassXC for the mobile OS of your choice, but it isn't at all optimized for mobile screen sizes and form factors, let alone multi-touch input. We also don't see any advantage in providing a mobile version of KeePassXC when there are already excellent options.

**Comment by droidmonkey** [comment]
The answer is simply no, two amazing options already
