### ISSUE TITLE
Yubico OTP support

### ISSUE THREAD

**Issue by gcstang** [keepassxreboot/keepassxc#1041]
Would love to see Yubico OTP support instead of or in addition to the CR support.

**Comment by TheZ3ro** [comment]
It's not possible, we already talked about this in various issues/PRs

**Comment by gcstang** [comment]
Ok, thank you for your response.  I did a quick search and didn't seen anything on it.

**Comment by TheZ3ro** [comment]
You can find here https://github.com/keepassxreboot/keepassxc/issues/798 and the discussion starting from here https://github.com/keepassxreboot/keepassxc/pull/127#issuecomment-310997339

**Comment by phoerious** [comment]
HOTP would actually be possible, but very unhandy and requires a lot of extra code. TOTP isn't possible by design.

**Comment by acannon828** [comment]
@phoerious can you elaborate on why this is?
