### ISSUE TITLE
On screen keyboard does not work

### ISSUE THREAD

**Issue by ssoufi-code** [keepassxreboot/keepassxc#10423]
## Overview
On Screen Keyboard is not working

## Steps to Reproduce
1. Turn on on screen keyboard
2. tap field
3. type password

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Enter a password

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
DOes not accept type

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.7
Revision: 68e2dd8
Distribution: Flatpak

Qt 5.15.10
Debugging mode is disabled.

Operating system: KDE Flatpak runtime
CPU architecture: x86_64
Kernel: linux 6.7.7-200.fc39.x86_64

Enabled extensions:
- Auto-Type
- Browser Integration
- Passkeys
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 3.3.0

[NOTE]: # ( Pick choices based on your environment )
Operating System: Fedora 39/Linux
Desktop Env: KDE/FLATHUB
Windowing System: Wayland

**Comment by ssoufi-code** [comment]
I just want to add, I also tested this on Fedora native KeepassXC version 2.7.6-6.fc39, and the same behavior existed here is the debug screen. 
KeePassXC - Version 2.7.6
Revision: dd21def

Qt 5.15.12
Debugging mode is disabled.

Operating system: Fedora Linux 39 (Workstation Edition)
CPU architecture: x86_64
Kernel: linux 6.7.7-200.fc39.x86_64

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.19.3

**Comment by droidmonkey** [comment]
This is likely because the keyboard is running on Wayland and keepassxc is running on X11. Please confirm this case.

**Comment by ssoufi-code** [comment]
I ran xlsclients and keepassxc is not running under xwayland for 2.7.6-6.fc39. I used flatseal to turn off the x11 backend for the Keepass 2.7.7 Flatpak  and I saw the same behavior.  So no, this isn't running under xwayland

**Comment by droidmonkey** [comment]
Does on screen keyboard work for other flatpaks you have? We have no affinity for keyboards so I strongly suspect this is outside of keepassxc.

**Comment by ssoufi-code** [comment]
Firefox does work with on screen keyboards on fedora native and flatpak, so yes it does work. I posted this first on the Fedora Repos Bugzilla and they said `This kind of bug is just one of the few common GNOME problems with KeepassXC. It has to be reported upstream` I hope this helps.

**Comment by droidmonkey** [comment]
> one of the few common GNOME problems with KeepassXC

Huh? You reported using KDE

Firefox is not a qt application so it isn't a good comparison. VLC is though.

**Comment by ssoufi-code** [comment]
> > one of the few common GNOME problems with KeepassXC
> 
> Huh? You reported using KDE
> 
> Firefox is not a qt application so it isn't a good comparison. VLC is though.

Apolgize for the confusion. I have 2 different versions, the Flatpak, and Fedora Native.  The Flatpak is using the KDE Flatpak runtime. But my Desktop is Gnome. I just checked VLC flathub and VLC fedora native, they don't work with on screen keyboards

**Comment by droidmonkey** [comment]
This is most definitely a bug in the KDE runtime or Qt, please report it over there. Sorry about this!
