### ISSUE TITLE
Searching for "Outlook" does not return (only) the outlook entries in the Mac and Windows application

### ISSUE THREAD

**Issue by nbro** [keepassxreboot/keepassxc#10421]
## Overview

If I search for `outlook` or `Outlook`, I don't get only the `Outlook` entries.

I have entries with titles like `Outlook (foo.bar@outlook.com)`, but the KeePassXC application does not return them or just them, it does not filter anything (it seems). This issue seems to occur only in this case. 

## Expected Behavior

Only the entries that contain `outlook` in the title are returned

## Actual Behavior

All entries or many other entries are returned

## Setup

KeePassXC - 2.7.7
Operating System: macOS and Windows 11

**Comment by nbro** [comment]
Never mind. It returns many other entries because many other entries contain usernames with `outlook`. 

Is there a way to search only in the `title` by default. I can search in the title using `title:outlook`, but it's too cumbersome to always type `title:`

**Comment by droidmonkey** [comment]
`t:outlook`

**Comment by nbro** [comment]
@droidmonkey Thanks for sharing this. But it still would be nice to set the default way to search. Why should it search by default in all columns, which seems to be the case?!

**Comment by droidmonkey** [comment]
For search to be overall useful, you want to default to broad and allow for refinement or specificity. A simple prefix to your search term allows that. You can save the search so you don't have to always type it in.

However you seem to always be looking for a specific entry, in which case use tags or move it to the root group for easy access.
