### ISSUE TITLE
Add button to copy password to an existing entry's password

### ISSUE THREAD

**Issue by nbro** [keepassxreboot/keepassxc#10431]
## Summary

Currently, in the entry's password field, we have 2 buttons on the right side: one to generate a new password and one to show the password. There should be a third one: copy the password. Right now, I have to select the password and do a `CMD + C` or `CTRL + C`. In the password generator, when you generate a new password, there's the button to copy the new password. I don't see why this button shouldn't also exist in an existing entry's password field.  I suppose this was asked many times in the past and if not I'd be very surprised.

**Comment by droidmonkey** [comment]
That is because it is in the toolbar.

![image](https://github.com/keepassxreboot/keepassxc/assets/2809491/ec2df7bb-3fa4-44f6-bff1-5a65bbfa057c)

**Comment by nbro** [comment]
@droidmonkey Ok, and can you actually move that button the the more meaningful and intuitive place, which is the bottom side of the password field?

**Comment by droidmonkey** [comment]
That work will be completed as part of #8228
