### ISSUE TITLE
Auto-Type sometimes goes into the wrong browser window on Mac

### ISSUE THREAD

**Issue by Helpstone** [keepassxreboot/keepassxc#10436]
## Overview
I like to use Auto-Type feature. Most times it does work fine. But under certain unkown conditions KeePassXC does select the wrong browser window to type into.

## Steps to Reproduce
1. Open more than one browser windows on Mac. I am using Safari
2. Place input cursor into login mask in one of the browser windows
3. Jump to KeePassXC by using <tab>
4. select appropriate password entry
5. type Shift-Command-V
6. Use "Cursor right" to select "yes"
7. hit Return

## Expected Behavior
The auto-type sequence should be executed in the last application window before switching to KeePassXC. This is the active application window as of step 2.

## Actual Behavior
Sometimes the auto-type sequence is executed in the correct app, but in a different window of this app (another Safari Window in my case).

The input either produces errors in this wrongly selected window or even worse it could send User and password to a public readable place

## Context
More than one Safari Window open. But I can not decide, what exact condition does trigger the problem

KeePassXC - 2.7.6
Revision: dd21def
Operating System: macOS

**Comment by droidmonkey** [comment]
Do you have any window or task switching managers installed that may interfere with switching windows? When you use the entry level auto type like you are, KeePassXC merely minimizes and the OS should raise the appropriate preiously focused window in the list. So this is not necessarily a bug in KeePassXC. 

I strongly recommend you switch from entry level auto type to global auto type. 

https://keepassxc.org/docs/KeePassXC_UserGuide#_performing_global_auto_type

**Comment by Helpstone** [comment]
No, I do not use any custom window manager or task switching manager.

For me it seems to be related with the special way, how MacOS does handle more than one window of the same app.

**Comment by droidmonkey** [comment]
Your best bet is to use global auto type then
