### ISSUE TITLE
Global auto-type shortcut when database is locked: previous window focus is lost with version 2.7.7

### ISSUE THREAD

**Issue by salsifis** [keepassxreboot/keepassxc#10430]
## Overview
This is a regression in version 2.7.7.
I use a global keyboard shortcut to perform auto-type. My Shortcut is Shift-Alt-Backspace.

This shortcut is useful when my database entries have window titles associated with an auto-type sequence.

## Steps to Reproduce
1. Open a Window that requires auto-type
2. Trigger the global auto-type shortcut
3. Enter the database password
4. See that all possible entries with auto-type appear in the entry selection dialog, instead of just one. If performing auto-type, it goes to another window.
5. Cancel auto-type, move focus back onto the window that requires auto-type, and trigger the global auto-type shortcut again before the database was locked
6. See that the entry selection dialog only displays relevant entries.

## Expected Behavior
Global auto-type shortcut memorizes the previous window when database unlock is required, as was the case in 2.7.6

## Environment
```
KeePassXC - Version 2.7.7
Revision: 68e2dd8

Qt 5.15.11
Debugging mode is disabled.

Operating system: Windows 10 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.19045

Enabled extensions:
- Auto-Type
- Browser Integration
- Passkeys
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 3.1.1
```

**Comment by droidmonkey** [comment]
Yes I observed this as well, going to fix
