### ISSUE TITLE
KeePassXC version 2.7.7 installs but will not run on macOS versions prior to macOS 11.0

### ISSUE THREAD

**Issue by smisenberg** [keepassxreboot/keepassxc#10444]
## Overview
When I install version 2.7.7 on macOS Catalina (10.15.7) the install completes but the app will not run.

## Steps to Reproduce
1. Machine is iMac running macOS 10.15.7 Catalina.  Machine runs KeePass 2.7.6 fine.
2. Download KeePassXC-2.7.7-x86_64.dmg 
3. Run this file and see it complete the install
4. Note that the drag-icon-to-install dialog shows a "do not enter" icon instead of the usual KeePassXC icon
5. Drag the icon to Applications. 
6. Get message, app already exists, so I say to keep both.
7. Run the KeePassXC 2.7.7 application

## Expected Behavior
KeePassXC 2.7.7 runs on my machine just as 2.7.6 had been.

Or else the documentation for KeePassXC should address versions of macOS prior to 11.0, say that 2.7.7 isn't supported and that 2.7.6 or earlier is required.

## Actual Behavior
When trying to run KeePassXC 2.7.7, an information box appears and says "You can't use this version of the application KeePassXC with this version of macOS. You have macOS 10.15.7. The application requires macOS 11.0 or later."
The dialog is telling me that I need a newer version of macOS.
When I OK the dialog, the KeePassXC application doesn't start.

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS Catalina 10.15.7

**Comment by droidmonkey** [comment]
Use a version from macports on older macos. Unfortunately, we can't keep supporting out of date operating systems.

**Comment by smisenberg** [comment]
Thanks for the fast response.
I understand, you have to draw the line somewhere.  I've worked in Software development.

But: wouldn't it make sense to say this in the documentation?

This way a user like me with an older OS would know that he/she couldn't go past 2.7.6 unless he/she upgraded macOS to 11.0 or greater.  

Could someone update the documentation to say this?   I would be willing to do this if I could know how.
As I said I have much experience in software development, documentation, and QA and I'm willing to help.

**Comment by sryze** [comment]
@droidmonkey Could you put a word about this into the release notes section on GitHub so that users of old Macs don't need to try many releases find a working one? Thanks.

**Comment by droidmonkey** [comment]
Done

![image](https://github.com/user-attachments/assets/1a79d97b-ad6b-42fc-b571-053a3978211e)

**Comment by phoerious** [comment]
Technically, 10 and earlier is wrong. The earliest it supports is some 10.x. I've updated the description.
