### ISSUE TITLE
KeePassXC Segmentation fault

### ISSUE THREAD

**Issue by melroy89** [keepassxreboot/keepassxc#10441]
## Overview

After a while Keepassxc just crashes (seg faults), no errors. It's just gone...

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Start keepassxc
2. Just wait....

## Expected Behavior

No crashes. 👍🏽 

## Actual Behavior

Randomly `Segmentation fault` after one or two hours (this is all the output I get):

```
$ keepassxc
Maximum depth of replacement has been reached. Entry uuid: {76df1859-541e-40d4-bc3f-47f9d542b537}
Maximum depth of replacement has been reached. Entry uuid: {82a094c5-7c5f-4e39-b5fc-84ab6aa7e743}
Maximum depth of replacement has been reached. Entry uuid: {fd5126c9-3903-4ee9-aa71-04b9f73b9d2a}
Maximum depth of replacement has been reached. Entry uuid: {1f0c4464-bacc-4964-a6b7-0827c5df9aa9}
Segmentation fault
```

When using `gdb`:

```
Thread 1 "keepassxc" received signal SIGSEGV, Segmentation fault.
0x00005555556c1e31 in ?? ()
```

## Context

I have no clue why it should seg fault. But it's very annoying, since I constantly need to start the app again.

KeePassXC - Version 2.7.7 (latest version at the moment of writing this)
Revision: 68e2dd8

Qt 5.15.3
Debugging mode is disabled.

Operating system: Linux Mint 21.3
CPU architecture: x86_64
Kernel: linux 6.5.0-25-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- Passkeys
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.19.1

Operating System: Linux Mint 21.3
Desktop Env: XFCE
Windowing System: X11

**Comment by melroy89** [comment]
Maybe related to: https://github.com/keepassxreboot/keepassxc/issues/10432 ? Unsure..

**Comment by droidmonkey** [comment]
Yes that's most likely the crash. I'll close this one unless you can produce a trace.
