### ISSUE TITLE
High CPU usage in background after most recent update

### ISSUE THREAD

**Issue by xzinkus** [keepassxreboot/keepassxc#10440]
## Overview
I'm noticing sustained high CPU usage from KeePassXC 2.7.7 on macOS after the most recent update (as a Homebrew cask). This occurs when the database is locked (with TouchID quick unlock available) and the app is in the background. 

## Steps to Reproduce
1. Use KeePassXC normally
2. Allow it to time out and lock
3. Wait

## Expected Behavior
Not sure what background tasks it needs to do, but it shouldn't be eating significant CPU cycles for extended time. Perhaps some settings (maybe in an Advanced tab?) around this would clarify what it's doing and allow tuning.

## Actual Behavior
Sporadic >80% CPU usage for sustained bursts >30s while locked.

KeePassXC - Version 2.7.7
Revision: 68e2dd8
Qt 5.15.11
Debugging mode is disabled.
Operating system: macOS 14.4
CPU architecture: arm64
Kernel: darwin 23.4.0

**Comment by xzinkus** [comment]
Also just want to thank the contributors here. Really appreciate the project and the sustained efforts from you all!

**Comment by droidmonkey** [comment]
Recommend a reinstall first. There is nothing that happens on a periodic basis, while keepassxc is locked. Are you using yubikey?

**Comment by xzinkus** [comment]
I am! I'm using a yubikey 5C nano, continuously plugged into the machine.

I'll try a reinstall, but I feel like the frequency varies (haven't measured it) so I'm not sure how soon I'll be able to confirm that that worked.

**Comment by droidmonkey** [comment]
If you unplug the yubikey, does the problem stop?

**Comment by xzinkus** [comment]
I haven't seen it since the reinstall. Can you mark this to be closed in, say, 24hrs if I don't come back confirming that the issue persisted? Thanks so much! Not sure why that would have fixed it, but hey, turn it off and back on again 😅

**Comment by droidmonkey** [comment]
No problem!

**Comment by xzinkus** [comment]
I just saw the issue again, but I was able to sample the process and it actually looks like it's a QT issue where some worker CPU-rendering threads get woken up and do... something.

**Comment by droidmonkey** [comment]
That has happened in the past

**Comment by xzinkus** [comment]
Thanks for the fast responses and again for this great project!
