### ISSUE TITLE
2.7.7 - this version remembers the location of the key, which it should not

### ISSUE THREAD

**Issue by adam3941875** [keepassxreboot/keepassxc#10448]
I apologise at once because I use a translator and am not very technical. 
As of this version, when I select a key it remembers the location of the key. This was not the case before - I had to enter the correct location myself. I did not change anything in the options. The option in the general settings section "remember database key file and hardware keys" is unchecked. It remembers the database all the time, in the previous version too. 
Sometimes he can't remember the location... I don't know... e.g. I changed the language then it forgets. 

KeePassXC - Version 2.7.7
Revision: 68e2dd8

Qt 5.15.11
Debugging mode is disabled.

Operating system: Windows 10 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.19045

Enabled extensions:
- Auto-Type
- Browser Integration
- Passkeys
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 3.1.1

**Comment by droidmonkey** [comment]
I cannot replicate this behavior at all. Try resetting your configuration file or checking the save key file setting, press ok, uncheck, press ok. I'll reopen if you can provide replication steps.

**Comment by adam3941875** [comment]
"> I cannot replicate this behavior at all. Try resetting your configuration file or checking the save key file setting, press ok, uncheck, press ok. I'll reopen if you can provide replication steps."
I don't know how to do this. Do you mean reset all settings i.e. restore them as default?

**Comment by droidmonkey** [comment]
yes

**Comment by adam3941875** [comment]
Does it make sense if I immediately set everything up the same way? 
I am trying different options... I checked the option "remember database key file and hardware keys" then unchecked again and the first time it doesn't remember, but every subsequent time it does - no matter if I close the database, the application or the PC.

**Comment by droidmonkey** [comment]
Once you uncheck the remember database key option, and press OK, all previous storage of key files is forgotten. We have a code guard in place that prevents new key files from being stored:

https://github.com/keepassxreboot/keepassxc/blob/514afebcc79cebebbcec38f3670a4b0ce0001de3/src/gui/DatabaseOpenWidget.cpp#L435-L437

Provide the _exact steps_ you are doing such that the problem manifests.

**Comment by adam3941875** [comment]
You don't have to show me any code because, as I wrote, I'm not very technical. 
I don't know how to do it - whatever I do it remembers the location of the key all the time, except occasionally when I change an option then once it forgets. In the previous version I had to manually enter the specific folder where the key was all the time. After the update it still remembers, and I haven't changed any options. Before the update, the remember key location option was unchecked and it still does, and it remembers it all the time. 
How do I show the steps of this problem....

**Comment by Lion066** [comment]
‌‌I have encountered the same problem. The key file should not be remembered.

**Comment by adam3941875** [comment]
@Lion176 thanks for the information. So I'm not the only one affected after all. @droidmonkey

**Comment by droidmonkey** [comment]
Without reproducible steps I cannot begin to debug this. The code that handles key remembering wasn't changed at all between 2.7.6 and 2.7.7.

**Comment by adam3941875** [comment]
But something must have changed since it still remembers the location from this version. Repeatedly, I just turn the option to remember the location on and off and it makes no difference.

**Comment by adam3941875** [comment]
@droidmonkey I would like to inform you that with version 2.7.8, the problem disappeared by itself. Just as it suddenly appeared in 2.7.7, it suddenly disappeared in 2.7.8.
@Lion176  Is it similar in your case?

**Comment by droidmonkey** [comment]
This was fixed for 2.7.8, I didn't tag this bug report on the fix, but another one

**Comment by adam3941875** [comment]
So was I right after all? I wrote how it happens, although not as cool as there because I am not so technical especially in a foreign language for me. 
Why did this error not occur at your place if you checked it as I understand on the same system?

**Comment by droidmonkey** [comment]
it was a slightly different problem, but related to what you wrote. I originally was thinking of something else when you wrote your report.

**Comment by adam3941875** [comment]
In any case, it is good that it has been fixed.
