### ISSUE TITLE
Wish I could minimize keepassxc to the system tray!

### ISSUE THREAD

**Issue by norcx** [keepassxreboot/keepassxc#10447]
It's very important to be able to minimize to the system tray, I often open a lot of programs, if you can't minimize to the system tray will look very confusing!

**Comment by varjolintu** [comment]
Are you having issues with one of these settings?
<img width="632" alt="Screenshot 2024-03-16 at 9 29 54" src="https://github.com/keepassxreboot/keepassxc/assets/24570482/a68426db-30e7-44e1-97e7-b12919b21a38">

**Comment by norcx** [comment]
> Are you having issues with one of these settings? <img alt="Screenshot 2024-03-16 at 9 29 54" width="632" src="https://private-user-images.githubusercontent.com/24570482/313385461-a68426db-30e7-44e1-97e7-b12919b21a38.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA1NzQ3MDYsIm5iZiI6MTcxMDU3NDQwNiwicGF0aCI6Ii8yNDU3MDQ4Mi8zMTMzODU0NjEtYTY4NDI2ZGItMzBlNy00NGUxLTk3ZTctYjEyOTE5YjIxYTM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE2VDA3MzMyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNjNDY1YzA4Mjc4MDUwYTdhOWRmZmE0MjgyMjlkYjVlNzQ3ZjBhYmIzNTUwYjFhYjliZDE0YTZkY2ZhNzlkNWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wHkFkfCoj8wdkKzj1Ww4QcTaQpezDDSvH6h_7KEHjrc">

Thank you so much. I've been looking for a long time. The translation in the Chinese language is the taskbar instead of the system tray.
