### ISSUE TITLE
Question: Why The Need For Minizip Now?

### ISSUE THREAD

**Issue by 0pLuS0** [keepassxreboot/keepassxc#10443]
Hi,

I didn't see any other place to make a post for this.

Why is there now a dependency requirement in 2.7.7 for minizip? What is wrong with just zip?

THANKS

**Comment by droidmonkey** [comment]
It is used for keeshare and has been for years.

**Comment by 0pLuS0** [comment]
> It is used for keeshare and has been for years.

I've been using KeePassXC since the project started, and in that time, I have been compiling it from soruce, and I use a build script and that has never changed.

It has never asked me before for minizip, and I have keeshare disabled.

These are the basic build cmds I use, see below ```-DWITH_XC_KEESHARE=${KEESHARE:-OFF}``` so this no longer works?

mkdir -p build
cd build
  export LDFLAGS="-ltermcap"
  cmake \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_INSTALL_MANDIR=/usr/man \
    -DCMAKE_BUILD_TYPE=Release \
    -DWITH_TESTS=OFF \
    -DWITH_XC_BROWSER=${BROWSER:-OFF} \
    -DWITH_XC_YUBIKEY=${YUBIKEY:-OFF} \
    -DWITH_XC_NETWORKING=${NETWORKING:-OFF} \
    -DWITH_XC_AUTOTYPE=${AUTOTYPE:-ON} \
    -DWITH_XC_DOCS=${DOCS:-ON} \
    -DWITH_XC_SSHAGENT=${SSHAGENT:-OFF} \
    ```-DWITH_XC_KEESHARE=${KEESHARE:-OFF} \```
    -DWITH_XC_FDOSECRETS=${FDOSECRETS:-OFF} \
    -DWITH_XC_UPDATECHECK=${UPDATECHECK:-OFF} \
    ..

  make -j12
  make install DESTDIR=$PKG

```THANKS```

**Comment by josephcsible** [comment]
I think I see the confusion now. It's not used just by the KeeShare code anymore. The new 1Password 1PUX file import code now uses it too.

**Comment by droidmonkey** [comment]
Yes that is correct

**Comment by 0pLuS0** [comment]
```1Password 1PUX file import``` what is this for, importing data bases? If this is correct, I don't use or need this.

I don't see any options in the CMakeLists so it can be disabled at compile time. Is there a compile time flag to disable these, if not can you please include one in the future?

THANKS

**Comment by droidmonkey** [comment]
No, we won't add a flag for this. Remove the import code and dependency if you don't want it.

**Comment by 0pLuS0** [comment]
I guess I'm confused, I assumed KeePassXC was a standalone password manager, I don't understand why the need to import databases from other apps is all, why this is being incorporated into KeePassXC?

THANKS

P.S. I hope maybe in time you'll add some compile time flags for it, it would be greatly appreciated, rather then digging through the code.

**Comment by 0pLuS0** [comment]
> No, we won't add a flag for this. Remove the import code and dependency if you don't want it.

Ok thanks
