### ISSUE TITLE
Failed to create passkey on PSN website

### ISSUE THREAD

**Issue by Yuzuriha-San** [keepassxreboot/keepassxc#10449]
Hi, Tried to create a passkey for my Sony PSN account without success. 

URL: https://my.account.sony.com
Sony error: A passkey couldn't be created for this device, or you canceled creating a passkey.
Keepassxc error: No supported algorithms were provided.

Browser: Firefox (Librewolf) 123.0.1-1
KeepassXC: 2.7.7
OS: Windows 11 22H2

**Comment by droidmonkey** [comment]
Already captured at https://github.com/keepassxreboot/keepassxc/issues/10374
