### ISSUE TITLE
DPI Scaling Issue in Submenus

### ISSUE THREAD

**Issue by samrg472** [keepassxreboot/keepassxc#10453]
## Overview
Some of the submenus are scaled incorrectly when the primary monitor has a different resolution and scale.

## Steps to Reproduce
1. Close KeepassXC completely
2. Open KeepassXC on a secondary monitor
3. Unlock the database and right click on an entry
4. Open any of the submenus "Copy Attribute", "TOTP", and "Tags"

## Expected Behavior
I expect the text to scale properly so that it doesn't overflow the visible menus.

## Actual Behavior
The text will overflow the visible menu because it is too large to fit the menu box. Sometimes it fixes itself, sometimes not. This issue never occurs on my primary monitor, only the secondary monitor.

Note: It seems in 2.7.7 that this issue occurs less often.

## Context
My primary monitor is a 4K display that is scaled to 150%, my second monitor is a 1080p display with 100% scaling.

KeePassXC - Version 2.7.7 (occurs in 2.7.6 as well)
Revision: 68e2dd8

Qt 5.15.12
Debugging mode is disabled.

Operating system: Windows 11 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.22631

Enabled extensions:
- Auto-Type
- Browser Integration
- Passkeys
- SSH Agent
- KeeShare
- YubiKey

Cryptographic libraries:
- Botan 3.3.0

**Comment by droidmonkey** [comment]
This would be a qt bug, please report it over at https://bugreports.qt.io
