### ISSUE TITLE
Only 1 slot is detected for Yubikey challenge-response

### ISSUE THREAD

**Issue by droidmonkey** [keepassxreboot/keepassxc#1045]
## Expected Behavior

Two or more slots are configured for HMAC Challenge-Response. Those slots are shown in the drop down selection in the unlock database dialog.

## Current Behavior

One slot is randomly shown.

## Possible Solution

Reimplement how the YubiKey::detect() function works.

## Steps to Reproduce (for bugs)

1. Configure a yubikey with more than 1 slot as HMAC Challenge-Response
2. Attempt to use this yubikey in KeePassXC

**Comment by onlykey** [comment]
Using the latest Linux app on Debian "apt install keepassxc" Both slots work correctly on this screen:
![image](https://user-images.githubusercontent.com/18121756/51205798-b593b380-18d4-11e9-8620-ca1c358e0b87.png)

But when you go to create a new database only slot 2 is visible/selectable in the drop down.
![image](https://user-images.githubusercontent.com/18121756/51205858-d65c0900-18d4-11e9-8d1c-34c62ec10535.png)

When you click refresh you see Slot 1 for half a second then it switches to Slot 2 in the field and Slot 1 isn't in the dropdown options.

I identified this issue while working on this - https://github.com/keepassxreboot/keepassxc/issues/2064

YubiKey 2 with both slots configured was used to reproduce the issue

**Comment by droidmonkey** [comment]
Good find, but please copy/paste this to a new issue. Subject of "YubiKey selection broken in New Database Wizard"
