### ISSUE TITLE
(HMAC mismatch)

### ISSUE THREAD

**Issue by dexzo3422** [keepassxreboot/keepassxc#10457]
## Overview
 (HMAC mismatch)
but I'm entering the correct password

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1.  I open the application
2. I enter the correct password
3. I get the error I described above (HMAC mismatch)
4. I read a similar article where they wrote to do a RAM test, but it didn’t help

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

I expected to be able to easily log into the application, copy the necessary data and continue with my work.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
When logging into the application, an error appears: Error while reading the database: Probably, the login data specified was incorrect.
Try entering the data again, if the error persists, the database file may be damaged. (HMAC mismatch)

A similar issue about HMAC mismatch did not help me, I did a ram test, no damage was found.

The database file was not copied or transferred anywhere, it was in the same archive where it was during installation

I haven’t updated keepasxc, I downloaded it a couple of weeks ago and I can’t get passwords from there anymore
## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION 2.7.6
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 10 Pro
Desktop Env: Gnome/KDE/XFCE/Mate/Cinnamon ??? idk what it is
Windowing System: 10 pro

**Comment by dexzo3422** [comment]
I accidentally pressed enter and the issue was published.

A similar issue about HMAC mismatch did not help me, I did a ram test, no damage was found.

Windows 10 Pro

I haven’t updated keepasxc, I downloaded it a couple of weeks ago and I can’t get passwords from there anymore

**Comment by droidmonkey** [comment]
You are not entering the correct password. That is the 99.9% likely scenario. Type it slowly, show the password while you are typing it. Unfortunately we cannot do anything to assist you regarding this problem.
