### ISSUE TITLE
Odd request for windows clock sync

### ISSUE THREAD

**Issue by seularts** [keepassxreboot/keepassxc#10464]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
Windows time sync using optional Atomic script fallback for correct TOTP sync.

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
I ran into this issue when I have debloated ( https://github.com/Sycnex/Windows10Debloater - using the iwr link in powershell ) my Windows 10 from various useless stuff that Microsoft injects in their products. Everything works alright, except for the clock that seems to somehow run out of sync, by around 1-2 min across a 2-3 month, in regards to the global time zone (even though the windows clock settings are set up to automatically update with time.nist.gov). To circumvent this I have downloaded the Atomic script ( https://www.worldtimeserver.com/atomic-clock/ ) so I can manually update the time when I need to uses one of the TOTP keys. What I would recommend is that you infuse the Atomic script as an optional backup for users who run in such a similar problem. I know this is a unique issue and that in my case it was self inflicted, but for atechnical users this might seem like KeePassXC might be at fault if this would happen to them.

A solution would be to add an extra button in the "Show TOTP" windows to force windows to sync using the script mentioned above.

**Comment by droidmonkey** [comment]
Hello, thank you for request but we won't be implementing this. Keeping the proper time is not the responsibility of keepassxc, plus you often need admin permissions to change time settings on an operating system. Recommend just re-enable the built in time sync and make your life easy.

**Comment by seularts** [comment]
I understand, thanks for the feedback.
