### ISSUE TITLE
KeePassXC 2.7.7: Not compatible with macOS versions below 11

### ISSUE THREAD

**Issue by v3DJG6GL** [keepassxreboot/keepassxc#10469]
## Overview
It seems as if KeePass XC is not compatible with macOS versions below 11.
There are no issues when installing KeePassXC 2.7.6 on the same computer.
Since I found no reference to this in the release notes, I thought that perhaps this increase in requirements was not intended...
<img width="808" alt="Bildschirmfoto 2024-03-11 um 18 43 18" src="https://github.com/keepassxreboot/keepassxc/assets/72495210/486a6a73-6f07-440a-ba24-6ae4e9ad9e94">

## Steps to Reproduce
1. Try to install KeePassXC on a Mac with macOS 10.15 or below.

## Expected Behavior
KeePassXC should be installable.

## Actual Behavior
KeePassXC is not installable.

## Context
macOS: 10.15.7
KeePass: 2.7.7

**Comment by phoerious** [comment]
10.15 wasn't supported either, but we tried to keep it compatible anyway, although without any guarantees. That was no longer possible for 2.7.7.

**Comment by v3DJG6GL** [comment]
> 10.15 wasn't supported either, but we tried to keep it compatible anyway, although without any guarantees. That was no longer possible for 2.7.7.

Perhaps it would be good to mention the minimum requirements on the download page - as is the case with Windows versions?

**Comment by phoerious** [comment]
We did that, but people complained anyway. We support the most recent macOS release and try to be compatible with whichever version Apple still supports, but without guarantees.

**Comment by droidmonkey** [comment]
I'll update the downloads page
