### ISSUE TITLE
Text is garbled after resume

### ISSUE THREAD

**Issue by gene-pavlovsky** [keepassxreboot/keepassxc#10468]
## Overview
After several days of occasionally using KeePassXC, putting the laptop to sleep at the end of the day, then resuming it the next morning, eventually opening KeePassXC results in all the text being garbled, all the characters are being displayed at the same position, not one after another.

## Steps to Reproduce
1. Use KeePassXC
2. Sleep the laptop in the evening
3. Resume the laptop in the morning

## Expected Behavior
Things keep working as usual

## Actual Behavior
Every now and then (this happens maybe once per two weeks on average), most of the text in the app is garbled - it looks like every character of each text is displayed at the position where just the first character should be.

To fix the problem, I have to restart KeePassXC.

## Context
I have two databases open usually.

KeePassXC - Version 2.7.6
Revision: dd21def

Qt 5.15.10
Debugging mode is disabled.

Operating system: macOS 14.4
CPU architecture: arm64
Kernel: darwin 23.4.0

![PXL_20240319_093100622](https://github.com/keepassxreboot/keepassxc/assets/2841193/cdc0f84e-e620-4203-bf40-e779e6ffd32e)
![PXL_20240319_093113378](https://github.com/keepassxreboot/keepassxc/assets/2841193/b28fe8ad-64a4-4b83-8565-4ff66b1d103c)

**Comment by droidmonkey** [comment]
This is a qt bug on macOS, also duplicate report.

**Comment by gene-pavlovsky** [comment]
@droidmonkey Do you have a link to the qt issue in their bug tracker? I guess just have to wait for it to get fixed?

**Comment by droidmonkey** [comment]
see #8758, we believe this will be fixed when we move to qt 6 for 2.8.0

**Comment by gene-pavlovsky** [comment]
Thanks! It's funny how both of us used the word "garbled" :D

**Comment by droidmonkey** [comment]
Pretty accurate lol

**Comment by gene-pavlovsky** [comment]
Yeah, it's just both me and the other reporter are non-native English speakers :) So my understanding is that you plan to update to qt6? And then the whole issue will go away.

**Comment by droidmonkey** [comment]
That is the plan, see #10267

**Comment by gene-pavlovsky** [comment]
Great, thank you!
