### ISSUE TITLE
Password entity window missing

### ISSUE THREAD

**Issue by antok87** [keepassxreboot/keepassxc#10460]
## Overview
The window displaying all the passwords is blank or gone.
When a folder is selected from the left hand side the selection highlight goes across the whole screen as if the entity window isn't there at all.
I have tried changing all View options but nothing has helped

![Screenshot 2024-03-18 at 9 06 04](https://github.com/keepassxreboot/keepassxc/assets/895304/5677076d-599e-4d4d-b35f-b54abf313cbf)
![Screenshot 2024-03-18 at 9 01 02](https://github.com/keepassxreboot/keepassxc/assets/895304/7dbe2796-dd26-4ccb-94f2-bf03055decaf)

## Steps to Reproduce
1. Open the Database
2. Select a folder

## Expected Behavior
All passwords in the select solder are displayed

## Actual Behavior
The password entity screen is blank or missing

## Context
This happened randomly some time after the info window to update appeared.
I did not update straight away but when this issue occurred I updated but it didn't help

KeePassXC - Version 2.7.7
Revision: 68e2dd8

Qt 5.15.11
Debugging mode is disabled.

Operating system: macOS 14.4
CPU architecture: arm64
Kernel: darwin 23.4.0

Enabled extensions:
- Auto-Type
- Browser Integration
- Passkeys
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 3.1.1

**Comment by michaelk83** [comment]
You probably expanded the sidebar to the full window width (the opposite of hiding it). Try dragging the separator from the right edge of the window.
Same as  #8206

**Comment by antok87** [comment]
> You probably expanded the sidebar to the full window width (the opposite of hiding it). Try dragging the separator from the right edge of the window. Same as #8206

😵 This was it, took a bit of random clicking and dragging to get it back 😆 not sure how I managed that in the first place.
Thanks!

I tried finding a `keepassxc.ini` but I don't know where it could be
