### ISSUE TITLE
Reload open database if file change detected and no unsaved local changes

### ISSUE THREAD

**Issue by genseirin** [keepassxreboot/keepassxc#10470]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
If a database is open, KeePassXC could regularly check if the file has a newer modification date since it was opened. If this is the case and if there are no local unsaved changes in the app, it should load the latest version from the file. This would reduce the risk of overwriting changes that were made in another instance. The user could be informed through an alert. Users who fear that a propagated modification could cause a loss of data can always use the history function.

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
It is quite common to store the database in the cloud. Synchronization happens automatically when changes are detected. If the same database is used by a team or if a user opens it on several devices and then changes are saved at different locations, however, it often results in conflicting copies.

Ideally the app would be able to merge changes, but that would be complicated and require manual interaction. The most straightforward way is to ensure that everyone is working on the latest copy. If this feature is used together with the setting to save after every change, the latest version should sufficiently fast propagate to all other instances.

**Comment by droidmonkey** [comment]
We already do this, however, not when editing an entry or group. That situation is a known bug. Conflicts will happen anyway, especially if your sync software is delayed in syncing for whatever reason. 

See #8545

**Comment by genseirin** [comment]
I experienced it on Windows 11, which would confirm the bug.
