### ISSUE TITLE
Database unlock page: hardware key checkbox is sometimes missing - unlock not possible

### ISSUE THREAD

**Issue by michaeltanner70** [keepassxreboot/keepassxc#10479]
## Overview
Sometimes it is not possible to unlock the database, because the hardware key will not show up belop the password field. Closing the database and reopening it does resolve the issue.

## Steps to Reproduce
1. difficult, as it not happens all the time

## Expected Behavior
if hardware key is connected, option should always be visible below password field

## Actual Behavior
only password field is visible sometimes, even when database require a hardware key and the key is connected

## Context
this was not the case with prior version, it came up with the new unlock page design

## Version
KeePassXC - 2.7.7
Revision: 68e2dd8
Operating System: Windows

**Comment by michaeltanner70** [comment]
used hardware key: Yubikey

**Comment by droidmonkey** [comment]
Use the refresh button below the right hand side of the password box.
