### ISSUE TITLE
macOS intel DMG is missing from 2.7.7 version

### ISSUE THREAD

**Issue by morewings** [keepassxreboot/keepassxc#10474]
## Overview
macOS intel DMG is missing from 2.7.7 version

## Expected Behavior
I want to update my KeePassXC

## Actual Behavior
I can't

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )

KeePassXC - Version 2.7.6
Revision: dd21def

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS 12.7.3

**Comment by phoerious** [comment]
Linked directly on the website like with any release before. https://github.com/keepassxreboot/keepassxc/releases/download/2.7.7/KeePassXC-2.7.7-x86_64.dmg

**Comment by morewings** [comment]
@phoerious now I see. But for some reason site was showing me only arm when I filed the issue.
