### ISSUE TITLE
macOS intel DMG is missing from 2.7.7 version (UPDATED)

### ISSUE THREAD

**Issue by morewings** [keepassxreboot/keepassxc#10487]
## Overview
macOS intel DMG is missing from 2.7.7 version

## Expected Behavior
I want to update my KeePassXC.

## Actual Behavior

I click check for updates in the menu.
I go to this page https://keepassxc.org/download/#macos 
The Intel mac bundle is missing. There is only arm build available.

## Context
I created other ticket with less details https://github.com/keepassxreboot/keepassxc/issues/10474 
The problem is the link provided by app is missing appropriate build for my system

KeePassXC - Version 2.7.6
Revision: dd21def

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS 12.7.3

**Comment by phoerious** [comment]
Click See more options -> KeePassXC for Intel Macs.
