### ISSUE TITLE
Passkeys do not work on some sites

### ISSUE THREAD

**Issue by lichwala** [keepassxreboot/keepassxc#10486]
## Overview
Passkeys support in KeePassXC works fine on some sites (eg. github.com, passkeys.io), but does not work at all on othersites (eg. vercel.com) - cannot register passkey on that site. Passkey is created at stored in KeePassXC databse, but the site returns error on registration, so such passkey cannot be then used to login.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Register a free account on vercel.com
2. Login on vercel.com using registered email/password
3. Go to: user avatar (top right corner of the page) -> Settings -> Authentication
4. Click "Passkey" -> "Continue" to start procedure of registering a new passkey
5. KeePassXC popup will appear asking to confirm registration of passkey for vercel.com - confirm (passkey is created and stored in KeePassXC database)
6. vercel.com shows error message that passkey registration failed: "Passkey registration could not be verified. Please try again."
7. "Retry" option does not help

## Expected Behavior
Successful registration of passkey for vercel.com site and successful login with passkey in the following steps.

## Actual Behavior
During passkey registration procedure (described above) in debug console there is "400 bad request" in final step, after which the site displays error message that passkey registration failed, so I guess there is some KeePassXC <-> vercel.com communication problem on the final authentication step.

## Context
Of course whole procedure of registering passkey is done after KeePassXC is properly installed, configured, DB created/opened, browser extension (for the latest version of Chrome) installed and passkeys support enabled in extension.
Similar procedure works fine for other sites (github, passkeys.io)
**This is NOT a problem with this particular site (vercel.com) - Proton Pass password manager with similar passkeys support works fine on all sites (including vercel.com).**

KeePassXC - 2.7.7
Revision: 68e2dd8
Qt 5.15.11

Operating System: Windows 10 Version 2009 x86_64
![image (4)](https://github.com/keepassxreboot/keepassxc/assets/1415188/bcb4dc89-549d-443b-a8ce-1a2949876c3a)
![New Project (1)](https://github.com/keepassxreboot/keepassxc/assets/1415188/d337b949-1529-472c-9d19-fbd322f67cd9)
![New Project](https://github.com/keepassxreboot/keepassxc/assets/1415188/267d8014-4bf4-4fcd-9a60-4327c26ed262)

Desktop Env: Windows 10 Pro

**Comment by droidmonkey** [comment]
Please use the pinned issue

**Comment by lichwala** [comment]
> Please use the pinned issue

What do you mean?
I've just submitted a bug in passkeys implementation, so why it was closed with "not planned" comment?

**Comment by droidmonkey** [comment]
https://github.com/keepassxreboot/keepassxc/issues/10374

We have a common issue thread tracking all sites that don't work

**Comment by lichwala** [comment]
OK, found it - thanks.
Just sent a comment - is that enough to have this site on the list?

**Comment by droidmonkey** [comment]
Yes that is fine
