### ISSUE TITLE
UI: Closing "Preview Panel" with "Close" button does not remove checkmark from "View > Show Preview Panel"

### ISSUE THREAD

**Issue by CsanaadB** [keepassxreboot/keepassxc#10488]
## Overview
Closing "Preview Panel" does not remove checkmark from "View > Show Preview Panel" if you close it by clicking on the "Close" button located on the panel itself.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. On the "Preview Panel" click on the "Close" button
![Screenshot from 2024-03-23 12-38-57](https://github.com/keepassxreboot/keepassxc/assets/4533851/fec06f98-f620-4480-b51c-9ccf7134bab9)
2. Trying to re-enable the "Preview Panel" from the "View" menu shows as it's still enabled
![Screenshot from 2024-03-23 12-39-17](https://github.com/keepassxreboot/keepassxc/assets/4533851/13986019-04af-4eb0-a875-82be1c233385) 

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Clicking on the "Close" button should remove the tick from "View > Show Preview Panel", so that the user can re-enable the "Preview Panel" from the "View" menu.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Re-enabling the "Preview Panel" requires a non-intuitive additional step of clicking on the "View > Show Preview Panel" so that the tick is removed there as well.

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.7
Revision: 68e2dd8

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: XFCE/Cinnamon
Windowing System: X11

**Comment by droidmonkey** [comment]
#1730 - thanks for reminding me to fix this though

**Comment by CsanaadB** [comment]
Sorry, this bug never occurred to me in the past and I tried looking it up in the issues. None of the open issues seemed to fit the bug at first glance, so I thought it was new.

Awesome project, thanks for your work!
