### ISSUE TITLE
Support for macOS password manager integration

### ISSUE THREAD

**Issue by AndreasIgelCC** [keepassxreboot/keepassxc#10480]
## Summary
Currently KeePassXC (version 2.7.7) does not support integration into macOS sonoma password manager (see https://support.apple.com/en-gb/guide/security/sec6319ac7b9/web). By that you need to install plugins for browsers and could not use the type-integration on other input fields

Feature-Request: KeepassXC should implement the Credential Provider extension in macOS and integrate that way even better into macOS.

## Examples
Screenshot from settings context:
![grafik](https://github.com/keepassxreboot/keepassxc/assets/2921976/df882f93-258c-4048-90d9-7bca76e04d9e)

## Context
macOS password manager seems to be a new feature in macOS Sonoma

**Comment by droidmonkey** [comment]
Are these the same? https://github.com/keepassxreboot/keepassxc/issues/6265

**Comment by atlantsecurity** [comment]
> Are these the same? #6265

Not the same.

**Comment by xannon-jamese** [comment]
@droidmonkey Yes, #6265 and #10480 are both requesting integration with [AutoFill](https://developer.apple.com/documentation/authenticationservices/ascredentialproviderviewcontroller).
