### ISSUE TITLE
New Linux Mint install of KeepassXC V2.7.7 will not import .kdbx database file saved from Keepass 2 V2.47

### ISSUE THREAD

**Issue by Advisorash** [keepassxreboot/keepassxc#10484]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
Linux Mint install of KeepassXC V2.7.7 will not open or import .kdbx database file saved from Keepass 2 V2.47
Tried removing and re-install with instructions at keepassxc.org/download/#linux, with same results.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Saved Keepass 2 database to .kdbx file in Linux Mint 21.3
2. Installed KeepassXC  2.7.7 in Linux Mint XFCE 21.3
3. Tried to open/import .kdbx database into KeepassXC

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Expected .kdbx database to import and open as happened OK with earlier versions

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
KeepassXC app opened OK, looked normal, menus worked.
First, selected KeepassXC Import function, but it did not list .kdbx as a file type to import, only .kdb and .csv (and some password vault file types which I don't have).
Tried again after renaming .kdbx file to .kdb, but that gave error message "Not a Keepass database".
Next, saved a .csv database from Keepass 2, and tried to import it to KeepassXC, but it gave error message "Failed to parse csv file".
Tried earlier working .kdbx files from previous operating systems, but results were the same.
So, .kdbx file is not corrupted.

## Context
[NOTE]: # ( Give us any additional information you may have. )
Earlier versions of KeepassXC worked OK in Windows and Linux Mint 18/19/20 when opening .kdbx and .csv files from Keepass 2, but now this new installation of KeepassXC 2.7.7 will not open/import them at all. 
I looked for earlier Linux versions of KeepassXC to go back to, but I can't find any online.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION 2.7.7
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux Mint 21.3
Desktop Env: XFCE
Windowing System: X11

**Comment by droidmonkey** [comment]
You just open a kdbx database, no import required.
