### ISSUE TITLE
TOTP - not giving correct code

### ISSUE THREAD

**Issue by neural-oD** [keepassxreboot/keepassxc#10497]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

OK, so using version 2.7.6 on Manjaro. 
When going into a google account, I've tried to put in the TOTP, and it's all of a sudden not allowing the generated code. 
This is strange, as I've used it before. 

## Steps I've tried 
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1.   I've checked my time on Manjaro, making sure it's connected to ntp
2. 
3. 

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
TOTP usually works

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
TOTP not working

## Context
[NOTE]: # ( Give us any additional information you may have. )
I've done updates, and this has only appeared since then.
I've also shut down keepassxc, and restarted it. This was after checking that my system time was correct.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.6
Revision: dd21def

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux  - Manjaro
Desktop Env: i3
Windowing System: X11

**Comment by droidmonkey** [comment]
Sync your computer time.  Otherwise your secret code is wrong. 99% it's your time.

**Comment by neural-oD** [comment]
Hi @droidmonkey  
As mentioned, I had checked my time.
Had actually run: 
`systemctl restart systemd-timesyncd`
But that did not help

Keep this as closed, I'm going to reboot the machine, and see if that helps for some reason though

**Comment by neural-oD** [comment]
Hi @droidmonkey 

Ok, this is definitely an issue.  Please reopen issue

Have restarted....still no joy....
Have restarted the systemd-timesyncd service, as above...still no joy

**Comment by droidmonkey** [comment]
I can 100% guarantee this isn't an issue with KeepassXC. You'll find plenty of other issues in the wasteland claiming the same thing as you, always a time problem.

**Comment by neural-oD** [comment]
Hi @droidmonkey 
Ok, I think I've gotten to the bottom of this. 
The TOTP, definitely wasn't working. However, I had a conflicted copy, on my database. Not sure, if I'd moved this or something, but when going through the conflicted copy, I used the totp from there, and it worked.

Thanks for your assistance
