### ISSUE TITLE
KeyPassXC crashes on closing databases macOS

### ISSUE THREAD

**Issue by ric91** [keepassxreboot/keepassxc#10494]
## Overview
KeepassXC 2.7.7 on macOS Sonoma 14.4. crashes with a segmentation fault when closing database(s) every time.

## Steps to Reproduce
1. open KeepassXC
2. open a database
3. close the database
4. crash error report will come up

## Expected Behavior
KeepassXC closes normal without error.

## Actual Behavior
macOS reports a segmantation fault when closing the database.

## Context
This will happen on my system with any database, even newly created ones.

Tested with a new user on macOS too, same error happens. So I assume user environment has no impact.

macOS crash report is attached.

KeePassXC - Version 2.7.7
Revision: 68e2dd8

Qt 5.15.11
Diagnosemodus ist deaktiviert.

Betriebssystem: macOS 14.4
CPU-Architektur: x86_64
Kernel: darwin 23.4.0

Aktivierte Erweiterungen:
- Auto-Type
- Browser-Integration
- Passkeys
- SSH-Agent
- KeeShare
- YubiKey
- Schnelle Entsperrung

Kryptographische Bibliotheken:
- Botan 3.1.1

Operating System: macOS Sonoma 14.4

[crashreport.txt](https://github.com/keepassxreboot/keepassxc/files/14735974/crashreport.txt)

**Comment by ric91** [comment]
I've tested on a second Mac, different system, same thing happens.

**Comment by droidmonkey** [comment]
This is fixed in a PR already, thank you for the report
