### ISSUE TITLE
MacOS 11 or above now required?

### ISSUE THREAD

**Issue by aleqx** [keepassxreboot/keepassxc#10495]
v2.7.7 now requires at least macOS 11 ... this is major change (the kind that would see the version number jump more than an increment in the 3rd tick). 

Was this intentional? If yes, would you consider compiling against more compatible libraries for wider compatibility given the scope of this software? A lot of people are running 10.x with no compelling reason to upgrade.

**Comment by droidmonkey** [comment]
Yes, you'll have to wait for macports to do a new build. 

10.15 is two years past EOL/EOS. The issue is the latslest version of Qt5 doesn't support.

**Comment by aleqx** [comment]
~~Actually it doesn't work on MacOS 11 Big Sur either.~~ You might want to add a note about (broken) compatibility in your release notes.

**Comment by droidmonkey** [comment]
Make sure you are downloading the right dmg for your cpu architecture.

**Comment by aleqx** [comment]
Wow, who knew that you need to install the correct file... That's what I get for coding instead of sleeping.

Thanks for the hard work with KeePassXC! I may contribute code myself (I'm switching away from another solution, I need at least a good converter, but I'd also like some features that KPXC doesn't have yet)

Do you have any plans for an Android version?

**Comment by droidmonkey** [comment]
For android use KeePassDX

**Comment by aleqx** [comment]
I'm already using KeePassDX, but the two have only partly overlapping feature set, e.g. DX has no sync awareness, but has custom fields that XC does't

I'm still surprised that after all these years, there is still no Keepass client that has a reliable integrated sync for, say, webdav, leaving it up to the user to fiddle with things like Syncthing, which ends up with so many conflicts.

(i'm aware there are some keepass clients that have sync, but they are either dead or not sufficiently actively developped to rely on with mission critical data)
