### ISSUE TITLE
App keeps crashing in standby-modus

### ISSUE THREAD

**Issue by AgentK3** [keepassxreboot/keepassxc#10496]
The Keepass XC keeps crashing, when the computer switches to stanby. The error message refers to the RAM. I will add the message later on.
The problem seemingly appeared in the current version.

---------------------------------------------
KeePassXC - Version 2.7.7
Revision: 68e2dd8

Qt 5.15.11
Diagnosemodus ist deaktiviert.

Betriebssystem: Windows 11 Version 2009
CPU-Architektur: x86_64
Kernel: winnt 10.0.22631

Aktivierte Erweiterungen:
- Auto-Type
- Browser-Integration
- Passkeys
- SSH-Agent
- KeeShare
- YubiKey
- Schnelle Entsperrung

Kryptographische Bibliotheken:
- Botan 3.1.1

**Comment by droidmonkey** [comment]
Fixed by #10458

If it happens frequently for you, recommend going back to 2.7.6 or locking your database before going to sleep. Sorry for the inconvenience
