### ISSUE TITLE
KeepassXC installtion fails on W11 QEMU/KVM VM running on openSUSE Tumbleweed

### ISSUE THREAD

**Issue by Budgie2** [keepassxreboot/keepassxc#10493]
## Overview
I am running openSUSE Tumbleweed on KDM desktop with Plasma6 X11 and have built a Windows 11 VM on QEMU/KVM.
When I try to install Keepassxc on this VM, the installation fails. 

1.   Downloaded installation and ran on windows VM
2.   Installation failed with several errors.
3.   Ran Repair and I get the same problems.  Difficult to cut and paste from VM to here but the problems include:-
4.   MSVCP140.dll missing
5.   VCRUNTIME140.dll missing
6.   VCRUNTIME140_1.dll missing

I had expected the installation to run without a hitch.  I do not have this problem with a Windows 10 VM on the same workstation.

I have had problems with W11 on VM, namely that I cannot get the Red Hat display adaptor driver to run as it is blocked by W11 because it cannot verify digital signature.

I mention this because the problems may be related.  Also although I am running with UEFI machine I do not have secure boot enabled.  This has never previously been an issue but the Windows 11 installation may be the problem.  I have always done the OS build with EFI boot but not secure boot as this is my preferred approach for openSUSE installations.

KeePassXC download version KeePassXC-2.7.7-Win64 is the installation download.

**Comment by droidmonkey** [comment]
Check out the pinned issues.

**Comment by Budgie2** [comment]
New here; how do I find the relevant pinned issue please?

**Comment by droidmonkey** [comment]
https://github.com/keepassxreboot/keepassxc/issues/7564
