### ISSUE TITLE
KeepassXc UI opens maximized and hides desktop task bar  (Cinnamon desktop)

### ISSUE THREAD

**Issue by stefcl** [keepassxreboot/keepassxc#1049]
Hello,
I am experiencing the following issue with KeepassXc under Cinnamon 3.4.6, I am not sure it's relevant but I am running a dual monitor setup.

About 50% of the time, when launching KeepassXC, its UI opens maximized in such a way that it covers my entire desktop (like pressing F11 under firefox). Application panels are covered and inaccessible, the usual window decoration, title bar and icons are absent.
When keepassUi is displaying, there is no way to interact with my desktop, the only things I can do are either close KeepassXC using the menu or press the keyboard win key to open the App launcher, this seems to be the only thing that can appear on top:
 
![image](https://user-images.githubusercontent.com/2216211/31314644-ade1b0a2-ac05-11e7-93d6-dc028743b543.png)

Switching between workspaces doesn't help, KeepassXC keeps eating the entire display on my primary monitor whatever I do. Also it does not obey keyboard shortcuts except alt-F4 (close).

Has anybody else experienced this problem?

## Debug Info
KeePassXC - Version 2.2.0
Revision: caa49a8ef3ee28ed478192389b21d61107b3b8e0

Libraries:
- Qt 5.9.1
- libgcrypt 1.8.1

Operating system: Manjaro Linux
CPU architecture: x86_64
Kernel: linux 4.12.14-1-MANJARO

Enabled extensions:
- KeePassHTTP
- Auto-Type
- YubiKey

**Comment by stefcl** [comment]
As a workaround, the following comment can recover the situation

`wmctrl -r KeePassXC -b  remove,fullscreen`

I am now wondering whether there is any specific code in KeepassXC for requesting fullscreen state or if my environment is causing this to happen somehow.

**Comment by droidmonkey** [comment]
no code in KeePassXC requests fullscreen from my reading.

**Comment by stefcl** [comment]
Thanks for checking,
I had a very quick look at the code, the Main windows constructor tries to restore the window state using `QWidget::restoreGeometry()`.

I assume that it uses this serialized value from the keepassxc.ini file

````
[GUI]
MainWindowGeometry=@ByteArray(\x1\xd9\xd0\xcb\0\x2\0\0\0\0\a\xe8\0\0\0Q\0\0\f\xdb\0\0\x3\xd4\0\0\a\xe8\0\0\0m\0\0\f\xdb\0\0\x3\xd4\0\0\0\x1\0\0\0\0\a\x80)
```` 
I can suppose that broken state information might have been written in this file at some point. Perhaps when I try to shutdown my computer and that DE starts killing tasks and fall apart. Who knows?

Nevertheless, QT docs suggests that their geometry system and X11 are not the best friends ever 
http://doc.qt.io/qt-5/application-windows.html#window-geometry

**Comment by stefcl** [comment]
Thanks for trying but it's probably not something you can reproduce. At 99% it has to do with the settings that were saved in the .ini file which, in turn, depended on the state of my window manager at that exact instant.

Except _perhaps_ adding a `restore default` entry under the `View` menu, there is probably nothing to do.

**Comment by stefcl** [comment]
It keeps happening to me on a regular basis, I can confirm that deleting the `MainWindowGeometry` entry from the INI file and then restarting the application solves it.

**Comment by frostasm** [comment]
how's it going? I can deal with this issue in my spare time.

**Comment by stefcl** [comment]
@Serhii
Are you talking about adding a *restore default* entry to the menu?

2017-10-28 21:47 GMT+02:00 Serhii Moroz <notifications@github.com>:

**Comment by frostasm** [comment]
@stefcl sorry, I mistakenly answered in this branch :(

**Comment by frostasm** [comment]
However I found one small bug. KeePassXC saves the geometry even when the main window is hidden. It creates a wrong behaviour on my DE (I use Mate). When the application starts, the main window always opens in the upper left corner of the monitor. Today I'll make some changes, maybe this will help

**Comment by stefcl** [comment]
Yes, I'll be happy to test as I am facing the aforementioned fullscreen issue almost all the time.
However, since GUI state parameters are auto-saved, I think it would hurt to also offer a clean way to restore the default state. I am not a Qt expert but it doesn't seem that hard (except for multi-platform testing of course).

**Comment by frostasm** [comment]
I`ll push small PR  #1146

**Comment by frostasm** [comment]
@stefcl can you test the develop branch?

**Comment by stefcl** [comment]
@frostasm 
Issue has been closed, so there is no point...

**Comment by frostasm** [comment]
@stefcl if you have the ability to check, please check the changes in the develop branch. The issue can be reopened if it will be necessary.

**Comment by TheZ3ro** [comment]
I've closed the issue since it should be fixed after #1146. If it's not we can reopen this or make a new one ;)

**Comment by Markkop** [comment]
This issue just happened with me and, as said by **stefcl**, removing the `MainWindowGeometry` line from `keepassxc.ini` solved it. This file can be found at `~/.config/keepassxc/`

**Comment by ramzinc** [comment]
> It keeps happening to me on a regular basis, I can confirm that deleting the `MainWindowGeometry` entry from the INI file and then restarting the application solves the problem.
> 
> I guess that settles it.

Thank you was facing this issue, the above workaround solved it for me too.
