### ISSUE TITLE
Latest update is not available in the Microsoft Store

### ISSUE THREAD

**Issue by Shousokon** [keepassxreboot/keepassxc#10501]
## Summary
The latest update cannot be installed from the microsoft store (https://apps.microsoft.com/detail/xp8k2l36vp0qmb?hl=en-US&gl=US)

**Comment by phoerious** [comment]
Please wait. Microsoft always take a long time to approve updates.

**Comment by droidmonkey** [comment]
I haven't pushed it out yet, this is my fault.

**Comment by Shousokon** [comment]
Hey @droidmonkey, is there any update on this issue? I still can't update my KeePassXC to the latest version cause the update isn't available on the ms app store.

**Comment by droidmonkey** [comment]
I submitted the update to the Microsoft Store, should be visible in a day or so. Just for your awareness, the Microsoft Store does not update "traditional" installed applications. You should update by downloading the MSI from our website as usual. https://keepassxc.org/download
