### ISSUE TITLE
Can unlocking use biometrics such as fingerprint recognition to unlock every time the computer is restarted.

### ISSUE THREAD

**Issue by norcx** [keepassxreboot/keepassxc#10508]
Thank you very much for your work, this is a very useful open source project. I think the security of this project could be improved:
Having to re-enter my password every time my computer reboots is bothersome and insecure. If someone wants to get my password, all they have to do is place a pinhole camera where I work. Would it be possible to add the option to log in with window hello every time the computer reboots. This is more secure. Because no one can get my fingerprints.

**Comment by phoerious** [comment]
Actually, it's less secure. This somebody only needs a glass that you touched etc. and unlike a password you can never change your fingerprint.
Nonetheless, there are requests here for fingerprint unlock already.
