### ISSUE TITLE
请问哪里有旧版的Chrome扩展下载

### ISSUE THREAD

**Issue by 258599** [keepassxreboot/keepassxc#10507]
Chrome 109.0.5414.120，在谷歌的应用商店安装不了，提示：下载时出错: Invalid manifest。安装其他扩展没问题，新版的Chrome可以正常安装KeePassXC-Browser

**Comment by varjolintu** [comment]
这可能是因为 Manifest V3。 Chrome 109 太旧了，无法支持该功能。/ This may be due to Manifest V3. Chrome 109 is too old to support this feature.

**Comment by 258599** [comment]
> 这可能是因为 Manifest V3。 Chrome 109 太旧了，无法支持该功能。/ This may be due to Manifest V3. Chrome 109 is too old to support this feature.

我找到了旧扩展的下载地址：https://github.com/keepassxreboot/keepassxc-browser/releases
1.8.12以后的版本都装不了，装好1.8.12版，可是链接不到数据库，在浏览器扩展里点连接没放应，KeePassXC都设置好了，以前都能用的，怪事

**Comment by varjolintu** [comment]
如果手动安装扩展，则需要将临时扩展 ID 添加到 JSON 脚本中。 请参阅 https://github.com/keepassxreboot/keepassxc-browser/wiki/Loading-the-extension-manually

---

If you install the extension manually, you need to add the temporary extension ID to the JSON script. See https://github.com/keepassxreboot/keepassxc-browser/wiki/Loading-the-extension-manually

**Comment by 258599** [comment]
> 如果手动安装扩展，则需要临时将扩展ID添加到JSON脚本中。请参阅https://github.com/keepassxreboot/keepassxc-browser/wiki/Loading-the-extension-manually
> 
> 如果手动安装扩展，则需要将临时扩展 ID 添加到 JSON 脚本中。请参阅https://github.com/keepassxreboot/keepassxc-browser/wiki/Loading-the-extension-manually

谢谢，我试一下
