### ISSUE TITLE
Custom Columns for convenient display and sorting of data like telephone numbers

### ISSUE THREAD

**Issue by GitHubinatrix** [keepassxreboot/keepassxc#10504]
## Summary
It would be beneficial if users could add unlimited number of custom columns because it would allow them for using KeePassXC in an extended and convenient way
 
## Examples
I invest in crypto currencies. To limit the risk of loosing my assets I created accounts on different sites, each with a unique e-mail and with 1 of my 2 phone numbers. Currently I can sort those crypto Entries in my KeePassXC database by their e-mail accounts [and thus see if I have not made a mistake of re-using the same e-mail] - but am unable to sort them by phone. If I could add a field for that data I would be able to see at a glance how many accounts have which number, because my goal is to have a 50-50 spread

This also goes for the country all those crypto exchanges are registered in: for security reasons I do not wish to use more than 2 platforms from one country - but the info about this am forced to keep either hidden [in the Notes field] or externally in entirely different kind of database [preferably an Excel file so that I could sort them alphabetically]

## Context
This improvement would allow to use KPXC for also other such "projects" requiring fields not predicted by creators and thus absent from the program

## Suggestion
If implemented, then an option to deleted such made-up by the user Column should require an extra confirmation in form of a pop-up box, informing user about loosing data stored potentially across multiple Entries

**Comment by droidmonkey** [comment]
#1493
