### ISSUE TITLE
[Followup] [Pickchars] By default, do not send `Tab` in Pickchars

### ISSUE THREAD

**Issue by pomianowski** [keepassxreboot/keepassxc#10503]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

This topic is already discussed in #7568 and I don't understand the closure.

Almost all banks in Poland implement the worst possible login method. You must choose a password of up to 30 characters, and then after entering the login (in separate window), you will see 30 fields, of which you must enter, for example, 5 _(5 characters of your permanent password, not captcha)_. After pressing each key, the focus automatically jumps to the next field.

Related to this is #6399 and #6398. Currently I need to have two entries. One for login, one for pickchars.

Every time I log into the bank, I use the hotkey and select the login entry, then wait for the page to change from login to password, then use the hotkey and select the password entry from pickchars. Every time I have to deselect clicking Tabs between letters.

![image](https://github.com/keepassxreboot/keepassxc/assets/13592821/00c3756c-e9c5-4866-a4bd-97e10616dcc9)

Some banks make an even bigger mess by asking you to enter your login, after entering the login a new page opens where you have to enter password and pickchars for your national identification number (something like insurance id).

![image](https://github.com/keepassxreboot/keepassxc/assets/13592821/dc8fbcef-87fe-4754-937f-f6f5f3c7affc)

## Expected Behavior

Available solutions:

 - The global option should allow you to choose whether pickchars should automatically send Tab.
 - An optional switch disables tabs for a given sequence, like `{NOTABS}{PICKCHARS}`
 - Remember the last checkbox state for Tab in the sequence

## Actual Behavior

I can't turn off the default option, so I have to change it every time. Deteriorated UX for the login option over which we have no influence.

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.7
Revision: [68e2dd8](https://github.com/keepassxreboot/keepassxc/commit/68e2dd8d22fdef79c72ad5902e026c698e2ff087)

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows & macOS

**Comment by pomianowski** [comment]
CC: @apawelec, @noisystuff, @michaelk83, @droidmonkey

**Comment by droidmonkey** [comment]
Thanks but we don't need another issue

**Comment by apawelec** [comment]
@droidmonkey At least please unlock comments in #7568

**Comment by droidmonkey** [comment]
Done
