### ISSUE TITLE
Add ability to use more than one connected Yubikey

### ISSUE THREAD

**Issue by droidmonkey** [keepassxreboot/keepassxc#1050]
## Expected Behavior

Multiple Yubikey's connected to the system would be polled and made available to KeePassXC.

Also, the YubiKey would only be "held" during active Challenge/Response actions.

## Current Behavior

Only the first connected Yubikey is used and the Yubikey is held open for the duration of KeePassXC running regardless of whether it is being used or not.

**Comment by knaggit** [comment]
I absolutely would appreciate this! Does it mean, it is possible to connect more than one key to a database in the case my key gets broken or even lost?

**Comment by TheZ3ro** [comment]
@knaggit no, this will allow to select which Yubikey use if there are more then 1 actually connected.

>  in the case my key gets broken or even lost?

You should backup your Yubikey CR secret in an offline storage

**Comment by bmachek** [comment]
I want to use 2 Yubikeys with different HMAC Secrets for 2 different databases.
1 for work, 1 for private use.

If I connect both Yubikeys via USB. Still only 1 is shown in the CR dropdown, even after hitting the reload button. Is this normal, or I am doing something wrong?

For now I constantly connect and disconnect the Yubikeys. Which kinda sucks. :-)

Version is 2.4.1, OS Win10 x64.

**Comment by droidmonkey** [comment]
@bmachek that is exactly the behavior this issue describes. It is still open, therefore no work has been done to fix it.
