### ISSUE TITLE
Text shifts to the left when the cursor hovers over the button

### ISSUE THREAD

**Issue by xboxones1** [keepassxreboot/keepassxc#10509]
## Overview
The text shifts to the left when the cursor is over the button. It is out of the general style and a bit annoying. 

![1](https://github.com/keepassxreboot/keepassxc/assets/91512529/67fe0718-7df7-4584-84a0-d06ea1757da2)
![2](https://github.com/keepassxreboot/keepassxc/assets/91512529/7380bad1-a584-4026-95ed-fb9ab61ff713)

## Expected Behavior
When focusing on the buttons, the text should not shift. 

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.7.

**Comment by droidmonkey** [comment]
It is unknown why that happens, I looked into it in the past. Qt styling is .... extremely messy.

It only happens when a button has an icon.

**Comment by xboxones1** [comment]
@droidmonkey Found what the problem is, it's hardcoded into the base style
https://github.com/keepassxreboot/keepassxc/blob/194409abd6f810bd4179d9aa072b8b9ac32919c5/src/gui/styles/base/BaseStyle.cpp#L2889C11-L2889C33
If you install 2 it looks better, see if it can be removed or fixed differently

**Comment by xboxones1** [comment]
@droidmonkey Found what the problem is, it's hardcoded into the base style
https://github.com/keepassxreboot/keepassxc/blob/194409abd6f810bd4179d9aa072b8b9ac32919c5/src/gui/styles/base/BaseStyle.cpp#L2889C11-L2889C33

If you install `int iconSpacing = 2;` it fixes the problem and looks much better. But if you look closely, the shift to the left is still about one pixel, but it is already the text with the icon. I think that the button without focus and with focus are centered differently, or it's some kind of click effect, qt has it. Look at this code at the link, there is setting of centering of text with icon when focusing on the button. 

![1](https://github.com/keepassxreboot/keepassxc/assets/91512529/13aca906-6edc-48af-826f-27a777f67ad5)

**Comment by xboxones1** [comment]
@droidmonkey In qt they don't consider it a [bug](https://bugreports.qt.io/browse/QTBUG-47347), but suggest using their own style, if I understood correctly. Or you can use buttons without icons, so it even looks better.
