### ISSUE TITLE
Edge plugin Cannot connect to KeePassXC

### ISSUE THREAD

**Issue by johnpadillait** [keepassxreboot/keepassxc#10514]
## Overview

installed plugin from edge store and try to conect the application.

try the same steps you provide form your website on chrome and its works with no issue wish what make belive that there is an issue with edge plugin.

the error is: Cannot connect to KeePassXC. Check that browser integration is enabled in KeePassXC settings.

Operating System: Windows 10

**Comment by droidmonkey** [comment]
You need to enable edge in keepassxc browser settings. You also might need to restart the browser. Although not always necessary. 

I can assure you the edge plugin and edge integration works great, I use it every day.

**Comment by johnpadillait** [comment]
Correct I dont that all of that and its works fine in chrome browser but
not on. Edge

thank you please advice

**Comment by droidmonkey** [comment]
Make sure you use a unique name when connecting the browser to the database. Otherwise, I don't have much else to say. The connection process is rather easy. Follow the steps: https://keepassxc.org/docs/KeePassXC_UserGuide#_setup_browser_integration

**Comment by johnpadillait** [comment]
agree it was easy to get other browsers to work - for some reason edge wont
do it for me.


john

**Comment by droidmonkey** [comment]
Can you please run through the relevant troubleshooting options for Edge: https://github.com/keepassxreboot/keepassxc-browser/wiki/Troubleshooting-guide
