### ISSUE TITLE
Random crashes - "..referenced memory at 0x0000000000000000. The memory could not be read."

### ISSUE THREAD

**Issue by timzuiddam** [keepassxreboot/keepassxc#10513]
## Overview
Crashes with the below error:
<img width="314" alt="image" src="https://github.com/keepassxreboot/keepassxc/assets/17024496/715d584c-8ec1-4fbc-8981-5cd5273c38ba">

## Steps to Reproduce
It happens randomly. Doing the exact same sequence on the same window after a restart of the application, did not result in the same. Happens at least on AutoType, but I think it happened on other occasions as well (like unlocking Windows after standby).

## Behavior
Error window title: Auto-Type - KeePassXC: Windows - Application Error
Text: The instruction at 0x00007FF793194EFD referenced memory at 0x0000000000000000. The memory could not be read.

## Context
I did not see this happen before updating to 2.7.7

KeePassXC - Version 2.7.7
Revision: 68e2dd8

Qt 5.15.11
Debugging mode is disabled.

Operating system: Windows 11 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.22631

Enabled extensions:
- Auto-Type
- Browser Integration
- Passkeys
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 3.1.1

**Comment by timzuiddam** [comment]
P.s.: Did not see this happen before updating to 2.7.7.

**Comment by droidmonkey** [comment]
Fixed by https://github.com/keepassxreboot/keepassxc/pull/10458
