### ISSUE TITLE
Unable to complete auto-entry on the onedrive login screen

### ISSUE THREAD

**Issue by Ausli** [keepassxreboot/keepassxc#10517]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
![屏幕截图 2024-03-29 235929](https://github.com/keepassxreboot/keepassxc/assets/70201547/41a271a2-0b46-438b-a268-b2b974488d60)

Unable to complete auto-entry on the onedrive login screen, my global shortcuts work, works in other windows, I think it's caused by the program not being able to get the focus of the screen
## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Open OneDrive
![屏幕截图 2024-03-30 001538](https://github.com/keepassxreboot/keepassxc/assets/70201547/4e672ab0-c2c1-4c20-944b-793feedc824e)
3. The above interface appears, note that you can use the automatic input here, enter your e-mail address and click login to enter the next interface
![屏幕截图 2024-03-29 235929](https://github.com/keepassxreboot/keepassxc/assets/70201547/41a271a2-0b46-438b-a268-b2b974488d60)
5. Enter the password interface, here can not be automatic input, you can keepassxc click on the automatic input button to return to the previous interface to enter automatically, but can not be completed through the global shortcuts for automatic input

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Complete automatic input through global shortcut keys in the password input interface

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
I press the auto-enter global shortcut on the password entry screen and nothing happens.

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.7

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows11

**Comment by droidmonkey** [comment]
This is Microsoft's fault, they do not focus on the password field when the window is focused. You need to setup your Auto-Type to one of the following:

 - `{DELAY 2000}{PASSWORD}{ENTER}` then click the password field manually in the 2 second delay period
 - `^{TAB}{PASSWORD}{ENTER}` this will press SHIFT+TAB then enter the password
