### ISSUE TITLE
Autotype results prefers a notes entry to a title

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [keepassxreboot/keepassxc#10519]
## Overview

In mutotype search results, an entry whose title starts with my search term precedes an entry that uses the search term only within its notes.

## Steps to Reproduce

1. Have a database entry entitled 'Reddit - New'.
2. Have another entry that contains 'Reddit' within its notes section.
3. Press the autotype hotkey.
4. Type 'reddit'.

## Expected Behavior

I expect to see as the first result the entry whose title starts with 'Reddit'.

## Actual Behavior
The first result is the entry that contains 'Reddit' (only) within its notes.

## Context

KeePassXC - Version 2.7.7
Revision: 68e2dd8

Qt 5.15.3
Debugging mode is disabled.

Operating system: Linux Mint 21.3
CPU architecture: x86_64
Kernel: linux 6.5.0-26-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- Passkeys
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.19.1

**Comment by droidmonkey** [comment]
We don't sort search results based on any criteria. Use the headers in the autotype dialog to sort the results. If you want just the entry with reddit in the title simply make your search `t:reddit`

**Comment by LinuxOnTheDesktop** [comment]
Thanks. Does a method of sorting imposed by clicking within a header _persist_?

EDIT (/addition): perhaps keePassXC _should_ implement the idea - the preferring of name to notes - that I mentioned.

**Comment by droidmonkey** [comment]
Persisting sort in the selection dialog is covered by another issue. I believe there is also another issue that requests search "relevance",  but that would be a massive code change and not likely to happen.

**Comment by LinuxOnTheDesktop** [comment]
> Persisting sort in the selection dialog is covered by another issue. I believe there is also another issue that requests search "relevance", but that would be a massive code change and not likely to happen.

I found these relevant issues: #2295; #9265; #508.

Cf. also, perhaps (unless there was user error here): #8555.

**Comment by droidmonkey** [comment]
Those are not related to the request you made above, these are:

https://github.com/keepassxreboot/keepassxc/issues/1684
https://github.com/keepassxreboot/keepassxc/issues/7877
