### ISSUE TITLE
Uppercase letter recognized as lower case letter with Onboard (virtual keyboard)

### ISSUE THREAD

**Issue by GameGourmet** [keepassxreboot/keepassxc#10511]
Hi there,

I'm not sure if the following problem is related to KeepassXC and/or Onboard (virtual keyboard) and/or gnome3/gtk3 or something else, so I'll post it here too.

Ubuntu 22.04.4 LTS (jammy)
Nividia (v535) proprietary driver from restricted
KeepassXC (v2.7.7-1) from ppa (I didn't test KepassXC from Ubuntus original source.)
Onboard (1.4.1-5build5) from universal

KepassXC ist set to (not sure if that makes a difference):
 - Autostart with operating system
 - Start minimized in taskbar with taskbar icon
 - Hide when minimized
 - Minimize instead of closing
 
Onboard ist set to autostart too.

Problem conditions to reproduce:
1: KeePassXC database password must begin with an uppercase letter (let's say letter "A"
2: Boot OS (Problem appears only one/first time after every os (re)boot)
3: Click on KeepassXC taskbar icon and click on show/hide window
4: KeepassXC program window appears and wants the password for opening the database
5: Click one the eye, so password will be shown
6: Open Onboard (virtual keyboard)
7: Left click in xkeepass database password text field
8: Right click on Onboards letter "A" (right clicking a letter in Onboard makes them uppercase)

Problem:
The expected letter "A" has been recognized as lowercase letter "a" in KeepassXC's database password textfield instead of uppercase "A". Try it a second time in the same OS-session and from now on every right click on an Onboards letter will appear as uppercase letter in KeepassXC as it should. This problem is kinda random, but the chances this happens to me feels like 80-90%.

This problem doesn't appear when clicking on "shift" and then on letter "A" on  Onboards virtual keyboard.

I tried a delay value of 100ms input delay in Onboard settings, but that doesn't solve the problem.

Maybe it's worth to mention the following observation:
Tested with five reboots. After each reboot I opened Firefox first. Then i clicked in it's searchbar/url texttfield and right clicked on Onboards letter "A". Everytime it was recognized correctly as uppercase letter "A". But hear me out :). Then i did steps 1-8 ... aaaaand KeepassXC immediately got the first  uppercase letter correct. It did so everytime in this "worth to mention"-test.

Well, I'll also report this on Onboard's issue forum, because i think it's best when this problem will be investigated from two angles.

**Comment by GameGourmet** [comment]
Don't find the edit button.
By saying "Then i did steps 1-8", i meant steps 3-8.

**Comment by droidmonkey** [comment]
> This problem doesn't appear when clicking on "shift" and then on letter "A" on Onboards virtual keyboard.

Seems like 100% a problem with Onboard. Is it that you just so happen to interact with keepassxc _first_ after login? Have you tried to replicate the sequence with any other application?

**Comment by GameGourmet** [comment]
> "Is it that you just so happen to interact with keepassxc first after login?"

Yes,... but when i run firefox first after boot and close firefox (without any further interaction inside firefox (no click in url textfield etc.)) and then do steps 3-8, the problem is still there in KeepassXC.

> "Have you tried to replicate the sequence with any other application?"

I'm also using a simple Textfile for passwords, which is encrypted with pzip(7zip?). Using the same password. The file then is opened in the text editor Gedit. Right clicked/uppercase letter always gets correctly send/recognized (first time after bootingt!) by Onboard/Gedit. Same for Firefox.

Just in case for the need to exchange with each other:
Onboard Bug Forum:
https://bugs.launchpad.net/onboard/+bug/2059358

**Comment by GameGourmet** [comment]
I forgot to mention that i'm using xorg/x11 NOT wayland.
This problem also happens in a fresh virtual machine with fresh ubuntu 22.04 (with xorg/x11) in virtual box. (Host for this test was Win10. In virtualbox I used VBox-Extensions + Guest Additions.)

Here is a video, showing the poblem.
https://www.file-upload.net/download-15290832/record.mp4.html

**Comment by GameGourmet** [comment]
Seems like KeepassXC really has nothing to do with this bug.
I played arround some more in a virtual machine, with different desktop managers and desktop enviroments and the search bar in KDE's plasma startmenu shows the same problem in combination with Onboard.

Sorry for the circumstances.
My bug report here can be closed/deleted.

**Comment by droidmonkey** [comment]
No problem, figured as much

**Comment by GameGourmet** [comment]
Sry, for my late response. It's a propblem on "Onboards" side.

Am Mo., 1. Apr. 2024 um 01:01 Uhr schrieb Jonathan White <
***@***.***>:
