### ISSUE TITLE
Cannot find file path for SSH key stored as an attachment to use in my SSH_Config for the IdentityFile parameter

### ISSUE THREAD

**Issue by www-jedi** [keepassxreboot/keepassxc#10512]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

Cannot find file path for SSH key stored as an attachment to use in my SSH_Config for the IdentityFile parameter

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. 
2. 
3. 

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

## Context
[NOTE]: # ( Give us any additional information you may have. )
I was hoping to use my SSH key stored in the database in my ssh config to login to remote servers, but I am not able to find any documentation supporting my use case. Once the SSH key is stored in the SSH Agent as an attachment. How do I call that key when using ssh -i? 

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.7
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: Mac

**Comment by droidmonkey** [comment]
You don't use ssh -i, the key material is loaded into ssh-agent (based on your configuration in keepassxc). In the ssh configuration file, you would reference the public key file, I believe. Searching for more.

**Comment by droidmonkey** [comment]
See here: https://github.com/keepassxreboot/keepassxc/issues/6925#issuecomment-921815370
