### ISSUE TITLE
GUI unusable when coming back from secondary monitor

### ISSUE THREAD

**Issue by diegonc** [keepassxreboot/keepassxc#10515]
## Overview
I'm running on Windows 11 in a two monitor setup with different scales[1] for each monitor. Whenever a close the lid of the laptop the KeepassXC window move to my secondary monitor (100% scale). Now if I open the lid of the laptop, the KeepassXC returns to the laptop main monitor (125% scale).

However, the usable space is restricted to a smaller area of the window and the text, icons and widgets are smaller than on the inital run (before closing the lid). The mouse pointer seems to be off, too

[1] [Scale](https://support.microsoft.com/en-us/windows/view-display-settings-in-windows-37f0e05e-98a9-474c-317a-e85422daa8bb#:~:text=If%20you%20want%20to%20change%20the%20size%20of%20your%20text%20and%20apps%2C%20choose%20an%20option%20from%20the%20drop%2Ddown%20menu%20next%20to%C2%A0Scale.)
## Steps to Reproduce
1.  Setup dual monitors: main monitor (laptop screen) with scale of 125% and secondary monitor with scale of 100% (external screen)
2.  Open KeepassXC on the main monitor
3. Close the laptop lid and check that the KeepassXC window moved to the secondary monitor (may need to be on power to prevent suspension)
4. Open the laptop lid and verify the GUI issues described in the overview

## Expected Behavior

The GUI should restore to the initial sizing after getting back from a smaller scale monitor.

> Sorry, I can't post screenshots as the window disappears when I try to capture it. 😕 

## Context

```
KeePassXC - Versión 2.7.7
Revisión: 68e2dd8

Qt 5.15.11
Modo de depurado deshabilitado.

Sistema operativo: Windows 11 Version 2009
Arquitectura de CPU: x86_64
Núcleo: winnt 10.0.22631

Extensiones habilitadas:
- Autoescritura
- Integración con navegadores
- Passkeys
- Agente SSH
- KeeShare
- YubiKey
- Desbloqueo rápido

Librerías criptográficas:
- Botan 3.1.1
```

Operating System: Windows 11

**Comment by droidmonkey** [comment]
Unfortunately, this is a qt bug. Hopefully this won't be an issue when we upgrade to qt6 for 2.8.0. Sorry for the inconvenience. One way to recover from this is to enable the system tray icon and minimize to system tray (or use ctrl+shift+m to go to tray) and then restore the window.

**Comment by diegonc** [comment]
I did the minimize to system tray trick but apparently didn't work for me 😢  I'll wait for Qt6.
Thanks!

**Comment by Sanfe** [comment]
I had relationated  behavior in Linux when I press the autofill key for unlock the database. It appear always in second monitor, regarding I config kde window properties, screen priority or I use kwin script. Any other apps make that.

I use arch with kde. Steam OS
