### ISSUE TITLE
Search field not focused after unlocking

### ISSUE THREAD

**Issue by thevoiceless** [keepassxreboot/keepassxc#10529]
## Overview
I used to be able to unlock KeePassXC and immediately start typing to search, confirmed by https://github.com/keepassxreboot/keepassxc/issues/847 / https://github.com/keepassxreboot/keepassxc/pull/887 

However, I'm not seeing the search field focused after unlocking my database. The normal keyboard shortcut to focus the search field DOES still work. The behavior does not change after restarting, hiding/showing the window, minimizing, etc.

I suspect this broke in 2.7.7

## Steps to Reproduce
1. Launch KeePassXC
2. Enter password to unlock the database

## Expected Behavior
Search field is focused and I can immediately start typing

## Actual Behavior
Search field is not focused

## Context
I see the expected behavior with 2.7.6 on Windows, but have not tried downgrading from 2.7.7 on macOS

KeePassXC - Version 2.7.7
Revision: 68e2dd8

Qt 5.15.11
Debugging mode is disabled.

Operating system: macOS 14.1
CPU architecture: arm64
Kernel: darwin 23.1.0

**Comment by droidmonkey** [comment]
https://github.com/keepassxreboot/keepassxc/pull/10459
