### ISSUE TITLE
Some Passwords deleted on startup

### ISSUE THREAD

**Issue by Asklios** [keepassxreboot/keepassxc#10528]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
When I load my database, it immediately switches to the light gray style it has when saving. Afterwards some (and always the same) entries are missing. When I do this on a copy, the opened file is slightly smaller afterwards. When I then export it as xml the entries are also missing. This happens on both of my Windows machines, when I open the same original database on my phone, the entries are there. 

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
Please help me with this question, I don't know what I can test or witch data would be helpful besides sharing my database witch is obviously not an option.
1. 
2. 
3. 

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Database entries are not supposed to get lost

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Database entries are missing

## Context
[NOTE]: # ( Give us any additional information you may have. )

KeePassXC - Version 2.7.7
Revision: 68e2dd8

Qt 5.15.11
Debugging mode is disabled.

Operating system: Windows 10 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.19045

Enabled extensions:
- Auto-Type
- Browser Integration
- Passkeys
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 3.1.1

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.7
Revision: 68e2dd8

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 10 Version 2009

**Comment by Asklios** [comment]
I can see all the passwords in Windows when I copy my database and merge the original with the copy while it is being decrypted. When I reopen the merged one, the passwords are deleted again.

**Comment by droidmonkey** [comment]
Are you using keeshare?

**Comment by Asklios** [comment]
Yes, I am using Keeshare but the affected passwords are not part of a shared folder.

**Comment by droidmonkey** [comment]
They probably were at some point and you have remnant deleted entry uuids being synced. Recommend you make a _copy_ of these entries which will change their uuid and then delete the originals. Make a copy by selecting the entries, drag them a little with the mouse, hold CTRL, then drop them (release mouse). You can also use the clone entry button, make sure not to use references.

**Comment by Asklios** [comment]
Thanks for your help @droidmonkey ! 

If anyone else has the same problem and finds this issue, entire folders can also be copied, which leads to a change in the uuid of all the entries. This was unfortunately necessary as I did not know how many entries were affected.

> Make a copy by selecting the entries, drag them a little with the mouse, hold CTRL, then drop them (release mouse). You can also use the clone entry button, make sure not to use references.

Dragging, holding CTRL and dropping is very helpful, as it does not append "-clone" to the name.

And remember to always make a backup of your database, I would have lost many passwords otherwise.

**Comment by droidmonkey** [comment]
Awesome! Glad to help. One of the quirks with working with keeshare unfortunately
