### ISSUE TITLE
用远程软件ToDesk远程电脑时候，KeePassXC窗口看不到

### ISSUE THREAD

**Issue by Cang-Cat** [keepassxreboot/keepassxc#10526]
## Overview
用远程软件ToDesk远程电脑时候，KeePassXC窗口看不到。

## Steps to Reproduce
1. 用远程工具ToDesk远程了安装了KeePassXC的电脑。
2. 打开KeePassXC，任务栏有任务，但是看不到软件窗口。

KeePassXC - VERSION
Revision: 2.7.7

Operating System: Windows11 专业版 23H2

**Comment by varjolintu** [comment]
English, please.

**Comment by droidmonkey** [comment]
"ToDesk supports encryption but KeePassXC does not"
