### ISSUE TITLE
[Bug] Backup Path Placeholders

### ISSUE THREAD

**Issue by LLKoder** [keepassxreboot/keepassxc#10521]
## Overview
Folder structure and file names are not created correctly when user type `backup/{TIME:yyyy}/{TIME:MM}/{TIME:dd}/{DB_FILENAME}-{TIME:yyyy-MM-dd-hh-mm-ss}.kdbx` in `Backup destination`

## Steps to Reproduce
See Overview.

## Expected Behavior
Get corrert path.

## Actual Behavior
Get incorrert path.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.7
Revision: 68e2dd8

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows/Linux
Desktop Env: Gnome/XFCE
Windowing System: X11/Wayland

**Comment by droidmonkey** [comment]
#10505
