### ISSUE TITLE
KeepassXC 2.77 Crashes, when two databases were open and one with a Yubikey is closed

### ISSUE THREAD

**Issue by Floesse** [keepassxreboot/keepassxc#10538]
## Overview
KeepassXC 2.77 Crashes, when two databases were open and one with a Yubikey is closed

## Steps to Reproduce
1. Open two databases one is protected with a key file and the other with a Yubikey challenge
2. Make changes to one or both databases
3. Close the tab for the database with the Yubikey, by clicking the X

## Expected Behavior
Tab closes and KeepassXC stays open with the first opened database

## Actual Behavior
KeepassXC crashes and produced a crash report

## Context
Termination Reason:    Namespace SIGNAL, Code 11 Segmentation fault: 11
Terminating Process:   exc handler [1593]

KeePassXC - Version 2.7.7
Revision: 68e2dd8

Qt 5.15.11
Diagnosemodus ist deaktiviert.

Betriebssystem: macOS 14.4.1
CPU-Architektur: arm64
Kernel: darwin 23.4.0

Aktivierte Erweiterungen:
- Auto-Type
- Browser-Integration
- Passkeys
- SSH-Agent
- KeeShare
- YubiKey
- Schnelle Entsperrung

Kryptographische Bibliotheken:
- Botan 3.1.1

Operating System: macOS

**Comment by phoerious** [comment]
Are you saving changes when the database is closed?

**Comment by Floesse** [comment]
No, changes are always saved immediately, the option to automatically save after every change is set.

**Comment by droidmonkey** [comment]
Probably this one that is fixed: https://github.com/keepassxreboot/keepassxc/pull/10458

**Comment by liamauve** [comment]
i have something similar happening. on apple silicon, I just drag and dropped the new 2.7.7 into application folder and overwrite the old 2.7.6... idk if that was the correct way to do it.

i have only 1 database open, nothing is changed/needed to save, if I click close database(command W) with the yubikey still connected, it would crash and os prompt for a crash report.

**Comment by Floesse** [comment]
Update: I retested with KeepassXC 2.7.8 and it stopped crashing.

KeePassXC - Version 2.7.8
Revision: f6757d3

Qt 5.15.11
Diagnosemodus ist deaktiviert.

Betriebssystem: macOS 14.4
CPU-Architektur: arm64
Kernel: darwin 23.4.0

Aktivierte Erweiterungen:
- Auto-Type
- Browser-Integration
- Passkeys
- SSH-Agent
- KeeShare
- YubiKey
- Schnelle Entsperrung

Kryptographische Bibliotheken:
- Botan 3.1.1
