### ISSUE TITLE
Alignment of Username / Password

### ISSUE THREAD

**Issue by Doc-Steve** [keepassxreboot/keepassxc#10536]
## Overview
Username and Password are not aligned horizontally in the preview panel. It seems like the password has always a leading space, which isn't the case. Maybe not a real bug, but can be misleading, because other fields are aligned.

## Steps to Reproduce
Select any entry and look at preview pane. User & password do not start at same point on x-axis.

## Version Info
KeePassXC - Version 2.7.7

Qt 5.15.12
Debugging mode is disabled.

Operating system: NixOS 23.11 (Tapir)
CPU architecture: x86_64
Kernel: linux 6.7.10

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.19.3

**Comment by droidmonkey** [comment]
They are as aligned as possible. Due to qt quirks and the need for different widgets for the two displays they will not be exact. A lot of effort was put in to make them as close as possible across all our deployment platforms.

**Comment by Doc-Steve** [comment]
I understand, thanks for the explanation.
