### ISSUE TITLE
Implement an option to skip the YubiKey challenge-response when modifying my database.

### ISSUE THREAD

**Issue by Tibood** [keepassxreboot/keepassxc#10531]
## Summary
The new feature introduces an option to skip the YubiKey challenge-response process when modifying the database.

## Examples
Add a menu in the 'Database Security' tab at the point of adding a YubiKey where we ask the user at what point they want the challenge to be performed (during opening, modification, deletion...).

## Context
It's important for me because often I can't leave my YubiKey on my machine's ports, and when I modify my database, it requires me to reinsert it for each modification even though I've already validated the challenge when opening my database (it's like sudo on Linux where you can, for a certain period, not be asked for the password after entering it once).

**Comment by droidmonkey** [comment]
https://github.com/keepassxreboot/keepassxc/issues/9089
