### ISSUE TITLE
Search field no longer has focus when db is opened

### ISSUE THREAD

**Issue by SerpicoSal** [keepassxreboot/keepassxc#10530]
## Overview
version 2.7.7 on linux (ubuntu 23.10 mantic) longer defaults keyboard focus to the "Search" text box after opening a DB.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Select a DB to open
2. Enter password
3. Type in search value (e.g. "t:github")

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
In KeePassXC v2.7.6 and older, after entering the correct password, the search field was immediately given focus which permitted a faster entry lookup.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
After successfully opening a db, no UI elements in KeePassXC have focus for keyboard interaction.
Pressing ctrl+F however works correctly to put the Search UI box in focus, it just is no longer the default behavior. 

## Context
[NOTE]: # ( Give us any additional information you may have. )
This is a NIT issue with a reasonable workaround.  I just need to retrain my instincts to press ctrl+F after my DB has been unlocked.  
I'm only reporting this issue as it was a noticeable change in v2.7.7 and may have been for a good reason that I'm unaware of. 

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.7
Revision: 68e2dd8

Qt 5.15.10
Debugging mode is disabled.

Operating system: Ubuntu 23.10
CPU architecture: x86_64
Kernel: linux 6.5.0-25-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- Passkeys
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.19.3

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: KDE Plasma 5
Windowing System: X11

**Comment by droidmonkey** [comment]
..... #10459

**Comment by SerpicoSal** [comment]
Thanks @droidmonkey, sorry that I didn't spot the duplicate issue before reporting.
