### ISSUE TITLE
Auto-Type does not work on macOS secondary screen

### ISSUE THREAD

**Issue by ruanyulin2017** [keepassxreboot/keepassxc#10532]
## Overview
My Macbook has two screens, when the application window on the secondary screen, the Auto-Type does work

## Steps to Reproduce
1. Move the application window to the secondary screen
2. Use the global Auto-Type shortcut keys to triggers Auto-Type on the window on the secondary screen
3. The password is not filled in the window on the secondary screen

## Expected Behavior
The password fill in the window on the secondary screen

## Actual Behavior
The password is not filled in the window on the secondary screen

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.7
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS 14.4

**Comment by droidmonkey** [comment]
Duplicate of https://github.com/keepassxreboot/keepassxc/issues/6762
