### ISSUE TITLE
Ambiguous clang version requirement in INSTALL.md

### ISSUE THREAD

**Issue by ryandesign** [keepassxreboot/keepassxc#10545]
## Overview
INSTALL.md says it requires "clang++ (>= 6.0)":

https://github.com/keepassxreboot/keepassxc/blob/194409abd6f810bd4179d9aa072b8b9ac32919c5/INSTALL.md?plain=1#L16

This is ambiguous because there are two different things called "clang": the one released by llvm.org and the one released by Apple as part of Xcode and the Xcode command line tools and they have different version numbering schemes.

## Steps to Reproduce
1. Read INSTALL.md

## Expected Behavior
Differentiation between the two different clangs

## Actual Behavior
Only one clang is mentioned and it does not say which one it refers to

## Context
llvm.org clang 6 is approximately equivalent to Apple clang 10.
Meanwhile Apple clang 6 is approximately equivalent to llvm.org clang 3.5.
See https://en.wikipedia.org/wiki/Xcode#Toolchain_versions

**Comment by droidmonkey** [comment]
The build tools are mainly for windows/mingw and Linux. There is only 1 supported version of xcode and xcode-clang 10 is very old and unsupported. Just use the latest. 

I see you are a macports contributor... did your comment here result from some stumbling block?
