### ISSUE TITLE
All entries are returned when autotype is invoked with database being locked - Version 2.7.7 

### ISSUE THREAD

**Issue by TheITguy21** [keepassxreboot/keepassxc#10548]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
Since I updated to version 2.7.7, all entries are returned when AutoType is invoked while the database is locked.
AutoType returns the proper matching entry only when database is not locked.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Lock your database 
2. Invoke autotype from somewhere (login webpage etc)
3. KeePassXC ask to unlock your database, unlock the database
4. The "Auto-Type" window opens but list all entries
5. Click Cancel on the "Auto-Type" window
6. Invoke autotype again
7. This time only the matching entry is returned as expected, as it used to be prior to version 2.7.7

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Invoke AutoType -> Unlock Database -> Only the matching entry should be returned in the "Auto-Type" window

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Invoke AutoType -> Unlock Database -> All the entries are returned in the "Auto-Type" window
You have to cancel and invoke autotype again, or unlock your database before invoking autotype. This is annoying 😅

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.7
Revision: 68e2dd8

Qt 5.15.11
Debugging mode is disabled.

Operating system: Windows 10 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.19045

Enabled extensions:
- Auto-Type
- Browser Integration
- Passkeys
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 3.1.1

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 10 Pro

**Comment by droidmonkey** [comment]
#10439
