### ISSUE TITLE
Add BCH option to donation page and I pledge to donate 1 BCH (worth USD 600 at the moment)

### ISSUE THREAD

**Issue by A60AB5450353F40E** [keepassxreboot/keepassxc#10541]
title

long time user, thanks for writing awesome software!

**Comment by phoerious** [comment]
What is it with all the crypto requests these days? I reckon we took down our BCH address at some point, because it started becoming a burden. Add 1 more and we may reconsider.

**Comment by A60AB5450353F40E** [comment]
some XMR guy posted on X about their request so I figured hey why not support the project I like using the coin I like

I'll pass the msg and try get 1 more commitment

**Comment by ShadowOfHarbringer** [comment]
> What is it with all the crypto requests these days? I reckon we took down our BCH address at some point, because it started becoming a burden. Add 1 more and we may reconsider.

A lot of power computer users use crypto, because it makes sense, especially a working not-a-joke crypto that can be used as money, like Bitcoin Cash (BCH)?

I also pledge to donate 1.337 BCH (about USD $802 right now).

**Comment by droidmonkey** [comment]
This is my BCH wallet: qprynwvfcwjdskz8zjaeh27tdqdlfccpqyddsvfry8

**Comment by A60AB5450353F40E** [comment]
> This is my BCH wallet: qprynwvfcwjdskz8zjaeh27tdqdlfccpqyddsvfry8

sent 1 BCH https://3xpl.com/bitcoin-cash/transaction/bf76056bae640ab0c0808ed5bdd85f6a0f3a609755794d0543138654d7e94ba0

btw, why was it "becoming a burden"? can just use some light wallet like [ElectronCash](https://github.com/Electron-Cash/Electron-Cash) or [cashonize](https://github.com/cashonize/wallet)

**Comment by phoerious** [comment]
Yes, and then one for every single crypto currency, no thanks.

I've replaced the SOL address with a BCH address on the website. https://keepassxc.org/donate/

**Comment by JettScythe** [comment]
Hell yea! Been using KeepassXC just a little longer than I've been in BCH. 

Sent some funds. Thanks for all your work 💚

**Comment by ShadowOfHarbringer** [comment]
> This is my BCH wallet: qprynwvfcwjdskz8zjaeh27tdqdlfccpqyddsvfry8

As promised:

https://3xpl.com/bitcoin-cash/transaction/5cf081617b18f708968a32e6d3c201d1ca6f46fcd8b49613f1bcc3385799105c

**Comment by droidmonkey** [comment]
Well, thank you kindly! Much appreciated for your support. Do you have a feature or bug you are interested in getting to completion?

**Comment by emergent-reasons** [comment]
This is great! Been using and promoting and teaching keepass (as keepassxc) for many years. Will include in regular OSS donations that I do.

**Comment by ShadowOfHarbringer** [comment]
> Well, thank you kindly! Much appreciated for your support. Do you have a feature or bug you are interested in getting to completion?

Yeah, actually this feature looks extremely useful and should not take that much work:

https://github.com/keepassxreboot/keepassxc/issues/10534

**Comment by droidmonkey** [comment]
I agree, I'll get on it

**Comment by emergent-reasons** [comment]
The only issues I ever had was 1st class support for 2fa and the fix for the search where it didn't work if the search box was hidden due to sizing. Both fixed long ago. Thanks for the great piece of software.
