### ISSUE TITLE
Passkeys: configure the category where to store them on creation

### ISSUE THREAD

**Issue by thePanz** [keepassxreboot/keepassxc#10547]
## Summary
Allow to define to which "Category" passkeys are stored when crated from the Browser.

## Examples & Context
When creating a new passkey from the browser, the entry is located under "Root > KeepassXD Browser passwords" (or similar, don't have the right one at the moment).

I would like to keep the passkeys together with the other passwords I manage under "Root > Browser" category

**Comment by varjolintu** [comment]
This is allowed by: https://github.com/keepassxreboot/keepassxc/pull/10408

**Comment by thePanz** [comment]
oh, nice! thanks @varjolintu ! :+1:
