### ISSUE TITLE
Auto-minimze does not work after bringing the window back using ALT+TAB

### ISSUE THREAD

**Issue by klaviartur** [keepassxreboot/keepassxc#10542]
## Overview
After automatic minimization of the window on auto-type or password-copying and bringing the window back to foreground using ALT+TAB, the window cannot automatically minimize again.

## Steps to Reproduce
1. open and unlock database
2. go to settings and activate "hide window on copy to clipboard" and select "minimize"
3. select any entry
4. trigger autotype or copy user name or copy password to minimize the window
5. press ALT+TAB or click on the window icon in the window switcher in the task bar to bring the window back to foreground
6. trigger autotype or copy user name or copy password again

## Expected Behavior
window minimizes again.

## Actual Behavior
window does not minimize.
user name or password are copied. auto-type types into the kepassxc window (password goes to search field).

## Context
The problem does not appear when the window is brought back by clicking the system tray icon instead of using ALT+TAB or the task bar.
In fact, when the window is brought to foreground using ALT+TAB and then the system tray icon is clicked, the window disappears instantly (rather than minimizing with a regular animation) and is then immediately brought back with a regular window restore animation. After that the application is in its initial state again and the error is reproducable once more as described above.

KeePassXC - 2.7.7
Revision: 68e2dd8
Qt 5.15.12

Operating System: Linux
Desktop Env: KDE Plasma
Windowing System: X11

**Comment by klaviartur** [comment]
apparently this will be fixed in 2.7.8 as of a comment by @droidmonkey 
Thx

**Comment by droidmonkey** [comment]
Sorry my comment was related to a completely different problem

**Comment by droidmonkey** [comment]
I cannot replicate this at all.

**Comment by klaviartur** [comment]
Very disappointing, but thanks a lot for trying. 👍

Maybe it's really just on my machine then …
