### ISSUE TITLE
crashes on a Dell Latitude 6510 

### ISSUE THREAD

**Issue by sebalis** [keepassxreboot/keepassxc#10554]
## Overview
I am running KeePassXC 2.7.7 under Arch Linux on an old Dell Latitude. Since a few weeks I’m seeing intermittend crashes of KeePassXC. After a crash I always find the same sequence of entries in the systemd journal:

> kernel: dell_wmi: Unknown key with type 0x0011 and code 0xffd0 pressed
> kernel: keepassxc[\*]: segfault at 10000000f ip \* sp \* error 4 in keepassxc[\*+\*] likely on CPU _ (core _, socket 0)
> kernel: Code: f3 0f 1e fa 53 48 8d 15 a4 7d fb ff 48 89 fb 48 83 ec 10 48 8b 76 58 64 48 8b 04 25 28 00 00 00 …

The asterisks represent changing numbers. The code bytes are always the same, and I have found them in the /usr/bin/keepassxc binary at offset 0x154bf0.

These unkown keys are of course a problem outside KeePassXC that I should investigate separately. I have tried and found sources saying that this keycode should be added to an ignore table in the dell_wmi driver. Also, these and/or similar messages are said (in the sources I found) to be related to presses of extra keys such as volume up/down. But I have not been able to produce keystrokes that lead to these messages on my system. I believe they tends to happen when the laptop switches its screen off when it’s not in use, but not every time.

In any case, speculation on the causes of those keystrokes is not very relevant here. I thought it worthwhile to report the problem here because KeePassXC is the only application that crashes in conjunction with these events. I can’t say for sure that these crashes happen every time this message on unknown keys appears in the syslog – there are occurrences of it not followed by a crash of KeePassXC but I can’t be sure if KeePassXC was running at those times. But every crash of KeePassXC is directly preceded by this unkown key message. So my reason for reporting this issue is that KeePassXC should not crash if an unknown keypress event occurs.

## Steps to Reproduce
1. Start KeePassXC
2. wait and realise that KeePassXC is no longer running – often this is after I return to the laptop after a break when the screen has switched off
3. find the above details in the systemd journal

KeePassXC - Version 2.7.7
Revision: 68e2dd8

Qt 5.15.13
Debugging mode is disabled.

Operating system: [Arch, initially Antergos]
CPU architecture: x86_64
Kernel: linux 6.7.9-arch1-1

Enabled extensions:
- Auto-Type
- Browser Integration
- Passkeys
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 3.3.0

**Comment by droidmonkey** [comment]
Almost certainly this fix: https://github.com/keepassxreboot/keepassxc/pull/10458

Without a stack trace I can only assume it is. A snapshot build will be pushed out soon so you can test it.
