### ISSUE TITLE
LastPass CSV Import Fails KeePassXC 2.7.7

### ISSUE THREAD

**Issue by OldDude1957** [keepassxreboot/keepassxc#10553]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # Importing a LastPass CSV file fails in 2.7.7.  No error message, just no info imported.  Work around - Uninstall 2.7.7, Install 2.7.6 and import CSV then update to 2.7.7.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Export CSV from LastPass
2. Import CSV into 2.7.7 
3. 

## Expected Behavior
[NOTE]: # In version 2.7.6 the CSV file imports (after setting field order)

## Actual Behavior
[NOTE]: # In version 2.7.7 the CSV fails to import (after setting field order manually or using first row has field names)

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION 2.7.7
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 10
Desktop Env: 
Windowing System:

**Comment by droidmonkey** [comment]
Make sure the title field is selected properly. #10433
