### ISSUE TITLE
Feature: Locking database linked to browser activity

### ISSUE THREAD

**Issue by Omnibrain007** [keepassxreboot/keepassxc#10556]
## Summary
On systems where using KeepassXC together with KeepassXC-browser mostly for browser passwords it would be nice to have an option to lock the database linked to browser activity.

##Features
- Option to link the locking of the database to the browser extension -> When closing browser then automatically logging the database.

- Optional inactivity timer linked to activity in the browser -> When not using the browser for x seconds then locking the database.

**Comment by varjolintu** [comment]
Duplicate of #310 ?

**Comment by droidmonkey** [comment]
Yes, that would be the preferred implementation.
