### ISSUE TITLE
User provided characters in password generation

### ISSUE THREAD

**Issue by elvati** [keepassxreboot/keepassxc#1055]
Several websites allow only a set of symbols in the password that is sometimes considerably smaller than any of the provided options in the password generator.  

## Expected Behavior

It would be useful to add an options for the user to provide a list of characters that should be considered in additions to the other set of characters available in the password generator tab.

## Current Behavior

Currently, only the "Special Characters"  and "Extended ASCII are available". When only a few characters are forbidden one can select the "Special Characters" options and generate a few password until one is valid. Otherwise the user is forced to use [a-z,A-Z,0-9] set.

## Debug Info

KeePassXC - Version 2.2.1
Revision: 2bce9c8add07226e9a05e9e0fd0e5e66b236d5b6

Libraries:
- Qt 5.9.1
- libgcrypt 1.8.1

Operating system: Windows 10 (10.0)
CPU architecture: x86_64
Kernel: winnt 10.0.15063

Enabled extensions:
- KeePassHTTP
- Auto-Type
- YubiKey

**Comment by droidmonkey** [comment]
This has been discussed in a previous issue.

**Comment by sts10** [comment]
Attempting to find previous issue that droidmonkey mention: both #820 and #858 seem similar?

**Comment by droidmonkey** [comment]
yah that's them

**Comment by elvati** [comment]
Thank you @sts10, 
I clearly didn't do my job when I looked for previous similar posts and this issue can be closed as duplicated. 
I don't think that adding options like granularity in the symbols, like the current version of keepass does (https://keepass.info/screenshots/keepass_2x/pwgen_big.png) impacts the usability. But that is a personal opinion, as I don't study UX.
