### ISSUE TITLE
Last used key file folder location not forgotten

### ISSUE THREAD

**Issue by Lakro** [keepassxreboot/keepassxc#10557]
## Overview

Concerns using databases with Password and key file:

Keepass remembers key file even if the setting remember database key files and security dongles (in German: "Datenbank-Schlüsseldateien und Sicherheits-Dongles merken") is  **NOT** checked

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )

1. Open the last Database you have used 
2. Open Menu Tools > Settings
3. Navigate to group "General"
4. Uncheck "Remember database key files and security dongles"
5. Make sure that "Remember previously used databases" is checked
6. Close Database
7. Reopen Database
8. Now: when you are in the login view and click on link "I have a key file" the File Manager opens nad offers the folder with the last used key file in it

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
With the settings decribed above:

When clicking on link "I have a key file" in the login view the File Manager should start with a default root folder like "User" oder "Documents"

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
With the settings decribed above:

When clicking on link "I have a key file" in the login view the File Manager shows the folder where the last used key file is in

## ADDITIONAL INFORMATION (Version and System)

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION 2.7.7  
Revision: REVISION 68e2dd8

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 10 pro - Version 22H2  
Using integrated standard Windows File Explorer without extensions

**Comment by sahriVoraus** [comment]
@Lakro as a quickfix I recommend to open the keepassxc.ini file at AppData\Local\KeePassXC\, remove the entry LastDir at [General] save it and then make the file write protected.
It is not a perfekt solution but better than nothing until this is fixed

**Comment by Lakro** [comment]
Thx for hint. A very good solution for the meantime :-)
