### ISSUE TITLE
KeePassXC 2.7.7 does not prompt for password when `--keyfile` flag is specified

### ISSUE THREAD

**Issue by samarlyka** [keepassxreboot/keepassxc#10552]
## Overview

I have tried specifying the keyfile location using the following command:

    keepassxc --keyfile /path/to/keyfile PasswordDB.kdbx

My database has both keyfile and password set up.

In **2.7.6**, the above command prompted KeePassXC for a password while keeping the keyfile location intact.
But in **2.7.7**, KeePassXC simply assumes the database doesn't have any password set and directly attempts to unlock the database (which failed).
After the failed attempt, KeePassXC removes the history of keyfile location I specified in the command line.
Then I have to specify the password and repick the keyfile again to unlock the database.

## Steps to Reproduce
1. Open a KeePassXC database encrypted using both password and keyfile from the command line, using the `--keyfile` flag
2. KeePassXC directly attempts to unlock the database (which failed)
3. The password input is field given, but the keyfile input field is missing, and the user must repick the keyfile again

## Expected Behavior
KeePassXC should prompt the user for Database password after specifying `--keyfile` flag when running from the terminal.

## Actual Behavior
KeePassXC **2.7.7** directly attempts to unlock the database and assumes the database is only keyfile-encrypted. When the database is both password- and keyfile encrypted, KeePassXC **2.7.7** simply fails to unlock and removes any keyfile location previously specified in the `--keyfile` flag. (Thus, the user is forced to repick the keyfile again, manually using the file selector dialog.)

## Context
N/A

## Debug info
KeePassXC - Version 2.7.7
Revision: 68e2dd8

Qt 5.15.13
Debugging mode is disabled.

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 6.8.2-arch2-1

Enabled extensions:
- Auto-Type
- Browser Integration
- Passkeys
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 3.3.0

## Computer environment
Operating System: Linux
Desktop Env: N/A (using i3-gaps without DE)
Windowing System: X11

**Comment by droidmonkey** [comment]
Concur this needs fixed
