### ISSUE TITLE
Warn about leading / trailing blanks

### ISSUE THREAD

**Issue by j-lakeman** [keepassxreboot/keepassxc#10569]
## Summary
Often when copying stuff from somewhere else e.g. websites or the terminal, there are additional blanks / tabs / line breaks that you don't want in your username or password field. IMHO KeePassXC should warn about it or cut the characters off upon pasting.

Nevertheless great application! Love it!

**Comment by qbast** [comment]
There is similar issue with more details: https://github.com/keepassxreboot/keepassxc/issues/11023

**Comment by droidmonkey** [comment]
Great point, this is a duplicate
