### ISSUE TITLE
2.7.7 Initial input focus no longer in search box.

### ISSUE THREAD

**Issue by poetnerd** [keepassxreboot/keepassxc#10567]
## Overview
I may be mis-remembering, but I'm pretty sure that KeepasXC, used to, by default set the input focus on the search box as soon as the database was unlocked.  In this way one could go directly from opening the database to searching for the relevant entry.

## Steps to Reproduce
1. Select a database and unlock it.

## Expected Behavior
Input focus should be in the search box.

## Actual Behavior
Input focus is elsewhere. Unclear where.

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.7
Revision: 68e2dd8

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS

Other Debug info:
Qt 5.15.11
Debugging mode is disabled.

Operating system: macOS 13.6
CPU architecture: arm64
Kernel: darwin 22.6.0

Enabled extensions:
- Auto-Type
- Browser Integration
- Passkeys
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 3.1.1

**Comment by droidmonkey** [comment]
Already fixed for next version
