### ISSUE TITLE
Auto-Type Window Association not used

### ISSUE THREAD

**Issue by Daedelos** [keepassxreboot/keepassxc#10579]
## Overview
Auto-Type into a Window (e.g Notepad) doesn't use the defined Window Association but uses the Inherited or Custom Auto-Type sequence.

KeePass2 Auto-Type works correctly with the same Database

## Steps to Reproduce

1. Select Auto-Type
2. Add a "Use custom Auto-Type sequence" - "custom - auto type{ENTER}"
3.  Add a "Window Association" Auto-Type using a Window title of "* - Notepad" and specific sequence of "window - auto type{ENTER}"
4.  Open Notepad
5.  Perform Auto-Type

## Expected Behavior
"window - auto type{ENTER}" to appear in the Notepad window

## Actual Behavior
 "custom - auto type{ENTER}" appears in the Notepad window

## Context
Using KeePass2 Auto-Type with the same database results in the correct behaviour

[NOTE]:
KeePassXC - Version 2.7.7
Revision: 68e2dd8

Qt 5.15.11
Debugging mode is disabled.

Operating system: Windows 11 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.22631

Enabled extensions:
- Auto-Type
- Browser Integration
- Passkeys
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 3.1.1

**Comment by droidmonkey** [comment]
To use window associations in KeePassXC, you need to use global auto-type. https://keepassxc.org/docs/KeePassXC_UserGuide#_performing_global_auto_type

**Comment by Daedelos** [comment]
Apologies, my misunderstanding. Thanks for the pointer.
