### ISSUE TITLE
Snap app crashes on launch on Ubuntu 16.04

### ISSUE THREAD

**Issue by rafaelrpinto** [keepassxreboot/keepassxc#1058]
The application was working fine, I'm not sure if a kernel update messed something up.
Now when I ran the application the following message is printed in the console and the process ends:

`udev_enumerate_scan failed`

[Looks like it happens with other apps too, so It may be a problem with the OS](https://forum.snapcraft.io/t/weird-udev-enumerate-error/2360/5)

If anyone knows a workaround would be nice :)

## Debug Info
KeePassXC - 2.2.1
Revision: 25

Operating system: Ubuntu 16.04
CPU architecture: 64
Kernel: 4.10.0-24

**Comment by rafaelrpinto** [comment]
Removing the snap package and installing the unofficial ubuntu .deb package solved the issue.

**Comment by droidmonkey** [comment]
looks like it's not a keepassxc issue

**Comment by raghur** [comment]
me too! esp just a week ago removed the .deb and installed the snap! and now this :(

**Comment by rodolfo912** [comment]
I have just given it a try and the snap package is running again on my machine.

**Comment by conz27** [comment]
+1 

I'm experiencing similar issues as described above following a kernel update on Ubuntu 16.04 running kernel version 4.4.0-97.

**Comment by droidmonkey** [comment]
This does not seem like anything that keepassxc is responsible for. There was a bad kernel update recently that broke all snap packages.

**Comment by conz27** [comment]
Thanks for the explanation @droidmonkey. I only meant to confirm the behaviour described above.

Is a potential workaround to re-install as a *.deb file if this is snap specific?

**Comment by rafaelrpinto** [comment]
@conz27 

.deb file works on 16.04.

https://github.com/magkopian/keepassxc-debian/releases

**Comment by conz27** [comment]
Thanks @rafaelrpinto! Confirmed, w/ YubiKey challenge-response support.

**Comment by sposmen** [comment]
Thanks... keepassxc_2.2.2-1_amd64_16.04_xenial.deb worked in kernel 4.10.0-37-generic

**Comment by conz27** [comment]
@rafaelrpinto, does it make sense to keep this issue open until the upstream fixes the broken snap packages? 

I understand that there isn't any code or work that can be done by the keepassxc project, but at the end of the day it's a user experience problem that affects your users. At the very least, someone can verify that everything starts working correctly once a new kernel update comes out with fix and officially confirm that this problem has been resolved. It also makes it easy for other users who encounter this problem to avoid opening duplicate issues.

**Comment by rafaelrpinto** [comment]
@conz27 
The snap package is working again.

Regarding if issues like this should stay open or not, this package is becoming pretty popular and with that all kinds of issues are opened (200+ now), so I guess the maintainers need to do what makes their life easier with the resources they have.

**Comment by droidmonkey** [comment]
We can get smart on label use for these types of issues.
