### ISSUE TITLE
KeePassXC crashes

### ISSUE THREAD

**Issue by helotbc** [keepassxreboot/keepassxc#10585]
## Overview
I launch KeePassXC using a shortcut. It operates normally. After not using for ~7hrs, it crashes.

## Steps to Reproduce
1. Launch KeePassXC
2. Wait 

## Expected Behavior
The expected behavior is that KeePassXC will run until quit by the user or system reboot.

## Actual Behavior
KeePassXC runs normally and quits randomly.

## Context
I have the following in the journalctl

Apr 13 12:42:50  org.keepassxc.KeePassXC.desktop[125614]: QSocketNotifier: Can only be used with threads started with QThread
Apr 13 12:42:50  systemd[10876]: Started app-gnome-org.keepassxc.KeePassXC-125614.scope - Application launched by gnome-shell.
Apr 13 12:42:50 org.keepassxc.KeePassXC.desktop[125614]: qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
Apr 13 12:42:50 org.keepassxc.KeePassXC.desktop[125614]: qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
Apr 13 18:25:55 org.keepassxc.KeePassXC.desktop[125614]: qt.qpa.wayland: Creating a fake screen in order for Qt not to crash
Apr 13 18:25:56 org.keepassxc.KeePassXC.desktop[125614]: qt.qpa.wayland: Creating a fake screen in order for Qt not to crash
Apr 13 19:06:14 org.keepassxc.KeePassXC.desktop[125614]: qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
Apr 13 19:48:20 kernel: keepassxc[125614]: segfault at 0 ip 0000612e7f9e0010 sp 00007ffc8bb35bb0 error 4 in keepassxc[612e7f8db000+3b4000] likely on CPU 15 (core 7, socket 0)
Apr 13 19:48:20 systemd[10876]: app-gnome-org.keepassxc.KeePassXC-125614.scope: Consumed 1.645s CPU time.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.7
Revision: 68e2dd8

[NOTE]: # ( Pick choices based on your environment )
Operating System: Ubuntu 23.10
Desktop Env: Gnome
Windowing System: Wayland

**Comment by droidmonkey** [comment]
This is likely fixed, or the same as #10415. Try a snapshot build: https://snapshot.keepassxc.org
