### ISSUE TITLE
Cannot import my database from prev version 

### ISSUE THREAD

**Issue by GDV373** [keepassxreboot/keepassxc#10588]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. 
2. 
3. 

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows/Linux/macOS
Desktop Env: Gnome/KDE/XFCE/Mate/Cinnamon
Windowing System: X11/Wayland

**Comment by droidmonkey** [comment]
You don't import a kdbx file, just open it.

**Comment by GDV373** [comment]
Yes sorry wrong choice of words. Updated and its now telling me wrong
password or corrupted

**Comment by droidmonkey** [comment]
That would indicate you are using the wrong credentials or your key file is not correct.

**Comment by GDV373** [comment]
Im sure the key file is correct as it loaded from the history i only have
1. And im sure about the password as well

**Comment by droidmonkey** [comment]
Then downgrade to the previous release and try again. Our releases are always compatible with existing kdbx versions.

**Comment by GDV373** [comment]
Yes it opened with vr 2.7.5
