### ISSUE TITLE
switching between dark mode & light mode doesn't work correctly

### ISSUE THREAD

**Issue by yeus** [keepassxreboot/keepassxc#10580]
## Overview

I am regularly switching between light & dark mode on my desktop depending on the time of the day (I use KDE, but I think this probably applies to all desktops). KeepassXC looks good when *launching* the app in the mode. But when I *switch* from dark mode to light mode or vice versa while keepassxc is already running, it messes it up.

here when switching it from light > dark:

![image](https://github.com/keepassxreboot/keepassxc/assets/736695/ce42ee76-871f-431b-9242-fa0b1a10247a)

and the same problem for dark > light:

![image](https://github.com/keepassxreboot/keepassxc/assets/736695/845db250-f18c-4d6a-b90d-e21ddedef525)

and this is what it actually should look like in light mode (when starting it in light mode instead of switching, I get this):

![image](https://github.com/keepassxreboot/keepassxc/assets/736695/e30ae638-7ddc-447a-9531-c74a95b3268e)

## Steps to Reproduce
1. start keepassxc
2. switch desktop from dark -> light mode or from light -> dark mode

## Expected Behavior

swtiching between modes should look the same as if starting it in a certain mode.

## Actual Behavior

dynamic dark/ight switching messes up the colors:

- icons don't change color
- background doesn't change color
- fonts don't change colors

## Context

- using it on KDE desktop

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.7

Qt 5.15.12
Debugging mode is disabled.

Operating system: NixOS 23.11 (Tapir)
CPU architecture: x86_64
Kernel: linux 6.1.82

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.19.3

Operating System: Linux
Desktop Env: KDE
Windowing System: X11/Wayland

**Comment by droidmonkey** [comment]
Looks like you are using the "custom" theme. The colors and presentation actually lie with Qt and your Desktop Environment in that theme mode. If you want fully functional theming you should use the built-in keepassxc themes.

**Comment by yeus** [comment]
thats right, I am using platform-native theme. switching it resolved the issue. Any recommendation what would need to be done for platform-native themes in order to make them work?

**Comment by droidmonkey** [comment]
You might need something like qt5ct or similar.

**Comment by phoerious** [comment]
It doesn't work. The additional themes you get with qt5ct are also non-native. The native platform theme is broken, at least on GTK platforms where it's basically just an emulation (but probably also on KDE, since we don't depend on kf5).
