### ISSUE TITLE
Keyboard autofocus on search field at startup broken in 2.7.7 (OsX and Linux)

### ISSUE THREAD

**Issue by akliouev** [keepassxreboot/keepassxc#10589]
Keyboard autofocus on search field at startup (previously issue #847 from 2017) stopped working with version 2.7.7
This is terrible for active users with large databases as requires a CTRL-F or a mouse point after unlocking to start searching the entries for the required one :-(
 
## Steps to Reproduce
1.  Open an existing database with lots of entries or create a new one with some entries
2.  Start typing the entry name you are looking for
3.  Realise that you are not typing into the search box. Type CTRL-F or click on the search box and type again

## Expected Behavior
The cursor should be in the search box right after the database is unlocked and your keystrokes after unlocking should go to the search box

## Actual Behavior
The cursor is SOMEWHERE else. Keystrokes after the database is unlocked are going SOMEWHERE

## Context
While not a show stopper it seriously de-streamlines the usability.

[NOTE]: #
KeePassXC - Version 2.7.7
Revision: 68e2dd8

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS Ventura 13.6.6 (same problem reported for Linux on reddit)
Desktop Env: macOS Ventura 13.6.6
Windowing System: macOS Ventura 13.6.6

**Comment by droidmonkey** [comment]
Already fixed for next release
