### ISSUE TITLE
Comfortable search

### ISSUE THREAD

**Issue by qwertz44** [keepassxreboot/keepassxc#10592]
## Summary
When opening a database it would be great if the cursor starts in the search field so you can type directly for searching an entry.

## Context
You have always to grab the mouse and klick into the field or press Strg+F to search after opening a database. I think most people are using the search function multiple times a day when working with large databases so it would be a bit more comfortable if the cursor would start in the search field - no need to click or press buttons.

**Comment by droidmonkey** [comment]
Fixed, this was a bug in 2.7.7
