### ISSUE TITLE
macOS Sonoma Auto-Type from menu works, shortcut does not

### ISSUE THREAD

**Issue by HUGHUSR** [keepassxreboot/keepassxc#10597]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
When using a shortcut, auto-type does nothing, but it works completely correctly when using the "Perform Auto-Type" from the menu on the selected item.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Highlight entry in KeePassXC
2. <SHORTCUT KEY COMBINATION>
3. Zilch happens

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Expect auto-type to happen, just like if I selected Preform Auto-Type from the menu.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Zilch happens.

If I have 'Always ask before performing Auto-Type' selected, I do not get a prompt. It appears the shortcut is ignored. I have tried about a dozen shortcuts, and none of them work!

## Context
[NOTE]: # ( Give us any additional information you may have. )

I have Accessibility and Screen Recording enabled.
I have no App Shortcuts in Keyboard Settings.

Auto-Type has never worked since I moved to an M2 MBP, and I am just now getting around to trying to debug it. I have narrowed it down to shortcuts not working for KeePassXC, and don't seem to have any other KeePassXC problems.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.7
Revision: 68e2dd8

Qt 5.15.11
Debugging mode is disabled.

Operating system: macOS 14.4
CPU architecture: arm64
Kernel: darwin 23.4.0

Enabled extensions:
- Auto-Type
- Browser Integration
- Passkeys
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 3.1.1

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS 14.4.1
Desktop Env: macOS
Windowing System: macOS

**Comment by droidmonkey** [comment]
Which keyboard shortcut are you referring to?

Recommend a read through our use guide for auto-type: https://keepassxc.org/docs/KeePassXC_UserGuide#_auto_type

**Comment by HUGHUSR** [comment]
The shortcut to which I refer is the Global Auto-Type.

I should also clarify that I am talking about Entry-Level Auto-Type.

_"Performing Entry-Level Auto-Type

You can quickly activate the default Auto-Type sequence for a particular entry using Entry-Level Auto-Type. For this operation, the KeePassXC window will be minimized and the Auto-Type sequence occurs in the previously selected window. You can perform Entry-Level Auto-Type from the toolbar icon (A), entry context menu (B), or by pressing Ctrl+Shift+V."_


Only, since I am a Mac, the default is CMD-SHIFT-V.

**Comment by HUGHUSR** [comment]
Uh, I should also note that step # 2 in the "Steps to Reproduce" should be "(Shortcut Key Combo)"

Don't know why it is blank.

**Comment by droidmonkey** [comment]
> The shortcut to which I refer is the Global Auto-Type.
> 
> I should also clarify that I am talking about Entry-Level Auto-Type.

Huh? To use global Auto-Type shortcut, you need to be focused on the application that will be receiving the input. NOT KeePassXC.

**Comment by HUGHUSR** [comment]
I am specifically talking about the Entry Level Auto-Type in this case. "Forever" before moving to an M2 Mac, I have always focused on the entry in the KeePass DB for which I wanted to Auto-Type, then hit the key combo CMD-Shift-V, and it AutoTyped the specified entry into the last selected window. Now, it does nothing, not even prompting "do you want to auto-type?" when that option is selected.

Likewise, if I select an app, and try to do a global auto-type, I get the same results.

The ONLY way I can autotype is to select the entry in the KeePass DB, then use the menu to select 'Perform Auto-Type'

(I tried to create a screenshot to show exactly what I was doing, but it appears that screenshot capture is disabled, as I only get a solid black screen capture -- no text.)

**Comment by droidmonkey** [comment]
Make sure you have NOT also set your global Auto-Type shortcut to Cmd-Shift-V

Autotype works fine on macOS so this is definitely something on your end.
