### ISSUE TITLE
keepassxc crashes

### ISSUE THREAD

**Issue by medvjed** [keepassxreboot/keepassxc#10599]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
keepassxc crashes when opening db (with windows pin)

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. difficult it is not consistent but at this moment a few times a day
2. database is locked, I type my windows pin
3. crash

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
not crash and open DB

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
The instruction at Ox00007FF744804EFD referenced memory at
OXOOOOOOOOOOOOOOOO. The memory could not be read.
Click on OK to terminate the program
Click on CANCEL to debug the program

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 10

**Comment by droidmonkey** [comment]
This is fixed already for upcoming 2.7.8
