### ISSUE TITLE
Auto-Saving every x minutes

### ISSUE THREAD

**Issue by Omnibrain007** [keepassxreboot/keepassxc#10590]
## Summary
It would be nice if there was an option to save the database every x minutes or at least to save open changes every x minutes

## Context
This would be a compromise of preventing data loss, between the two options of saving perhaps very often for every change and just saving very few times on locking the database.

**Comment by droidmonkey** [comment]
Will be in 2.8.0: https://github.com/keepassxreboot/keepassxc/pull/9100
