### ISSUE TITLE
Discussion: drop support for Windows

### ISSUE THREAD

**Issue by anatoli26** [keepassxreboot/keepassxc#106]
Hi project leads and everyone!

I'm really glad there's not just a new single maintainer for the project, but a team! Amazing, guys!

My suggestion here is to drop support for Windows for the following 3 reasons:
1. There's already the original version there, KeePass, great and shining. At this time, it totally outperforms KPX/R, so I believe there are just no users on Windows for KPXR (a poll may be completed here to confirm/reject this hypothesis).
2. Maintaining yet another OS, which is quite different in a lot of aspects with respect to the *nixes (OS X being a member of the family), drains a lot of resources.
3. Simpler code base (less #ifdefs and special conditions) reduces bugs, an important aspect especially for a security-related program.

I don't know your plans, guys, but if you really have enough resources to outperform the original KeePass on the 3 platforms (Linux, OS X and Windows) in the near future, that would be like... WOW! At the same time I'm not sure there's a lot more to add to the original.

What I believe is needed for KPXR is to migrate from KP the most important features (if possible, just copy-pasting the code with necessary adaptations, to save resources (and at the same time to have an opportunity to find bugs in KP), both projects are open-source), especially security and usability related (like OS (tray, shortcuts, session events, etc.) and browser integration), and make it stable enough for production.

So if your resources are somehow limited and you have to prioritize resolution of the issues and development of new features, I would suggest to drop support for Windows and concentrate the effort on *nixes.

Also, I would analyze the possibility and appropriateness of merging or at least collaborating with [MacPass](https://github.com/mstarke/MacPass) for the OS X part. Note: I never used it, but it looks promising, at least the UI and the project's goal in general.

**Comment by anatoli26** [comment]
Also, I would analyze the possibility and appropriateness of merging or at least collaborating with [MacPass](https://github.com/mstarke/MacPass) for the OS X part. Note: I never used it, but it looks promising, at least the UI and the project's goal in general.

**Comment by TheZ3ro** [comment]
I don't think is a good idea to drop Windows support.
I see the cross-platform feature as a power for out project.

> There's already the original version there, KeePass, great and shining. At this time, it totally outperforms KPX/R, so I believe there are just no users on Windows for KPXR (a poll may be completed here to confirm/reject this hypothesis).

An user that use KeePassXC on Linux will prefer the same on Windows/Mac because he knows how to use it (and he knows the source code. He trust the application he is using)
Yes, native (like Cocoa on Mac and Winform on Windows) is the best choice but Qt is very powerful.

> Maintaining yet another OS, which is quite different in a lot of aspects with respect to the *nixes (OS X being a member of the family), drains a lot of resources.

It don't really works like this, Qt does all the job. We need only some test to see if works but our code it's cross-platform by default.

> Simpler code base (less #ifdefs and special conditions) reduces bugs, an important aspect especially for a security-related program.

I've counted the #ifdefs for each platform used and this is the result:
7 --> `#ifdef Q_OS_WIN `
9 --> `#ifdef Q_OS_MAC`
1 --> `#ifdef Q_OS_UNIX`

We should drop MacOS instead.  :stuck_out_tongue_winking_eye:

> What I believe is needed for KPXR is to migrate from KP the most important features (if possible, just copy-pasting the code with necessary adaptations, to save resources (and at the same time to have an opportunity to find bugs in KP), both projects are open-source), especially security and usability related (like OS (tray, shortcuts, session events, etc.) and browser integration), and make it stable enough for production.

It's not possible to copy-paste the code.

**Remember** the team works on this project in the free time and it isn't paid to develop this, it's an hobby

I close the issue as Won't fix.

**Comment by anatoli26** [comment]
> KeePass audit: no critical security vulnerabilities found
> 
> We reported back in June 2016 that KeePass, a popular password manager, was getting a security audit by the European Commission's EU Free and Open Source Software Auditing project (EU-FOSSA).
> 
> EU-FOSSA is a pilot project to create a formal process for contributing software security reviews to open source communities.
> 
> The project created an inventory of open source solutions used by the Commission, published studies into the security practices of 14 open source communities, and reviewed two popular open source solutions.

http://www.ghacks.net/2016/11/22/keepass-audit-no-critical-security-vulnerabilities-found

Just wanted to share the news.

Maybe keep this issue open and change the title to something more of a general discussion about related topics and the future of the project, available for everyone to comment.
