### ISSUE TITLE
Missing translations in v2.8.0 rev 6481ecc

### ISSUE THREAD

**Issue by Stephan-P** [keepassxreboot/keepassxc#10606]
![Snipaste_2024-04-20_21-01-28](https://github.com/keepassxreboot/keepassxc/assets/10008599/9aeb85b6-bf2f-4c76-8f84-6a056f60f341)

![Snipaste_2024-04-20_21-04-20](https://github.com/keepassxreboot/keepassxc/assets/10008599/9979eed0-edc3-494c-8644-a4656e1dc4f9)

![Snipaste_2024-04-20_21-05-42](https://github.com/keepassxreboot/keepassxc/assets/10008599/d137c056-6483-41fb-bb15-9c40f410fb2d)

Plus an odd alignment of items:

![Snipaste_2024-04-20_21-09-25](https://github.com/keepassxreboot/keepassxc/assets/10008599/96b0e4b9-fa72-4228-bacb-cb75991cf6d1)

```
KeePassXC - Version 2.8.0-snapshot
Build Type: Snapshot
Revision: 6481ecc

Qt 5.15.11
Debugging mode is disabled.

Operating system: Windows 11 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.22631

Enabled extensions:
- Automatisch invullen
- Browserintegratie
- Passkeys
- SSH-agent
- KeeShare
- YubiKey
- Snel ontgrendelen

Cryptographic libraries:
- Botan 3.1.1

```

**Comment by droidmonkey** [comment]
We don't update translations on the develop branch often, that is done prior to a release. You can update them yourself using the release tool prior to building: `./release-tool i18n update`
