### ISSUE TITLE
Yubikey is not recognized unless running with admin privileges

### ISSUE THREAD

**Issue by b1ad3runn3r** [keepassxreboot/keepassxc#10607]
## Overview
Yubikey is not visible for KeepassXC unless it is launched with elevated privileges. It says: "Hardware keys not found" though it is inserted.

Yubikey Personalization Tool does not see the key but Yubikey Manager does (I guess it may be somehow connected with deprecated smartcard / pcsc / etc. API in Personalization Tool).

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Start KeePassXC without admin privileges
2. Try to unlock database
3. Yubikey is not visible 

## Expected Behavior
Yubikey should be able to be used

## Actual Behavior
It doesn't =(

## Context
KeePassXC - Версия 2.7.7
Ревизия: 68e2dd8

Qt 5.15.11
Режим отладки выключен.

Операционная система: Windows 11 Version 2009
Архитектура ЦП: x86_64
Ядро: winnt 10.0.22631

Включённые расширения:
- Автоввод
- Интеграция с браузером
- Passkeys
- SSH-агент
- KeeShare
- YubiKey
- Быстрая разблокировка

Криптографические библиотеки:
- Botan 3.1.1

**Comment by droidmonkey** [comment]
This isn't a keepassxc problem if it is visible with admin privileges. You will need to figure out why your yubikey isn't being made available to standard users for challenge response.
