### ISSUE TITLE
Cant connect to KeyPassXC remotely on network

### ISSUE THREAD

**Issue by ctp5150** [keepassxreboot/keepassxc#10604]
Hello, does anyone know how to configure keypassXC so that I can connect to it remotely from pcs on the network?

I installed and configured the browser intergration settings and it will work locally from a web browser on the server but remote machines do not show the connect button and I cant get it to connect.

Thank you,

**Comment by droidmonkey** [comment]
You cannot use keepassxc across the network like that. It must be installed on each machine you use it on. You share the kdbx database between computers.
