### ISSUE TITLE
Make implementation of Challenge-Response more compatible to Keepass 2

### ISSUE THREAD

**Issue by PhilippC** [keepassxreboot/keepassxc#1060]
As the author of Keepass2Android I was looking into [implementing the Challenge-Response functionality as in KeepassXC](https://github.com/PhilippC/keepass2android/issues/4). While I like the idea of using the Master seed as "challenge", I am not so happy with the implementation of Challenge-Response. To explain why, here is a short overview of the key generation in Keepass 2 (by Dominik Reichl) which is used by Keepass2Android as well:

Keepass2:
```
pbPassword = CryptoUtil.HashSha256(StrUtil.Utf8.GetBytes(strPassword))
pbKeyFile = LoadKeyFile(...)
pbCustomKey = challengeResponse //for example when using KeeChallenge Plugin in keepass 2
//CompositeKey concatenates the data of ALL IUserKey objects
pbAllData = pbPassword + pbKeyfile + pbCustomKey
pbRaw32 = CryptoUtil.HashSha256(pbAllData)
pUserKey32 = kdf.Transform(pbRaw32)
pbCmp = MasterSeed + pUserKey32
pbHmacKey64 = h.ComputeHash(pbCmp);
```

KeepassXC, with the naming conventions from Keepass 2
```
pbPassword = CryptoUtil.HashSha256(StrUtil.Utf8.GetBytes(strPassword))
pbKeyFile = LoadKeyFile(...)
//CompositeKey only concatenates password + keyfile but not challengeResponse
pbAllData = pbPassword + pbKeyFile
pUserKey32 = kdf.Transform(pbRaw32)
pbRaw32 = CryptoUtil.HashSha256(pbAllData)
//challengeResponse is added later, where no plugin can modify the computation in Keepass2
pbCmp = MasterSeed + challengeResponse + pUserKey32
pbHmacKey64 = h.ComputeHash(pbCmp);
```

In Keepass 2, it is very common for Plugins to add elements to the Composite Key. These elements are objects of `KcpCustomKey` or custom classes implementing the `IUserKey` interface. The data of all these elements are concatenated and transformed. When I added support for KeeOtp or KeeChallenge in Keepass2Android, I did exactly this, which was very simple.

In KeepassXC, the challengeRespose is not concatenated with password and (potentially) key file. Instead, it is prepended to the hashed and transformed key. This cannot be implemented for Keepass2 by a plugin, so the current KeepassXC implementation will not be usable for Keepass 2 users, and nobody can change this by developing a plugin. It also requires some pretty intrusive code changes if I want to implement this in Keepass2Android which I believe are not necessary if KeepassXC would offer (at least as an option or better as the default) to concat the challengeResponse to the pbAllData.

If I didn't miss any important reason to integrate the challengeResponse at this point in the processing, I suggest you make the key computation more compatible to other Keepass implementations. Please let me know what you think so I can plan further development on the feature for keepass2android.

**Comment by droidmonkey** [comment]
Yikes, this is not good. Fixing this will also require backwards compat for users who are currently using KeePassXC with Yubikey with an option to "fix" their encryption for portability.

**Comment by droidmonkey** [comment]
For the record, the offending code is located [here](https://github.com/keepassxreboot/keepassxc/blob/develop/src/format/KeePass2Reader.cpp#L111) down to line 125.

The main issue is challenge response keys are treated separately from normal keys in the [CompositeKey::rawKey()](https://github.com/keepassxreboot/keepassxc/blob/develop/src/keys/CompositeKey.cpp#L83) function which is called right before the key transformation occurs. We should also be performing the challenge-response and adding that data to the rawKey() return value and remove that from the offending code in KeePass2Reader.

**Comment by phoerious** [comment]
We do need to re-issue a challenge every time we save the database, no matter how we calculate the final key. Otherwise we lose any benefit we have from our implementation over the KeeChallenge implementation. The master seed changes every time, so does the challenge response.

I also don't like trying the old way first. There is really no way of knowing how the key was computed and trying several methods multiplies the time it takes to decrypt a database. My database takes about a second on my fastest computer, most slowest (my phone) about 5-10. Trying a different method first, would make it two seconds (and 10-20) for absolutely no security gain.

I'd rather suggest going the way VeraCrypt did. They have a checkbox "TrueCrypt" mode which allows me to open legacy TrueCrypt containers. We only need to do a better job at letting users know they have to check this box and not forget it every time or come here and complain their databases won't open anymore.

**Comment by phoerious** [comment]
Thinking about it, we could do it like that:

1. We add a tiny checkbox somewhere for activating legacy mode. When the user tries to open a database with their YubiKey, we show a dialog asking them if they want to enable legacy mode with an additional checkbox "don't bother me again". If the user chooses "yes", we check the box for them.

2. When saving a legacy database, we show another message, asking the user if they want to convert the database and informing them that the old format will be removed in the future.

3. A few versions down the road we remove support for the legacy format and add an FAQ entry telling users to temporarily use an older version for conversion if they habe a legacy database.

**Comment by TheZ3ro** [comment]
I think that's the best thing to do, but I will also consider fixing this for the KDBX4 format so every new (converted) database will use the new mode and not the legacy one

**Comment by phoerious** [comment]
KDBX4 is a completely new format, so there is no reason to implement legacy support for KDBX4 databases (although it would probably not even be extra code).

**Comment by droidmonkey** [comment]
its a natural and easy way to fix this issue to only support the keepass2 method of key transform in kdbx4.

**Comment by phoerious** [comment]
Could you check out https://github.com/keepassxreboot/keepassxc/pull/1230/commits/2b6f6f587cdb89e5c4354c93de097300d110d0cd please and give feedback if everything's alright with that implementation?

**Comment by phoerious** [comment]
Update: I re-implemented my fix to make it more compact and fix a few KDB(1) test issues. KeePassXC now uses the transform seed as a challenge instead of the master seed for KDBX4: https://github.com/keepassxreboot/keepassxc/pull/1230/commits/eb62e7deb8c2b940e784fd469f87c5c2c66010b3

**Comment by PhilippC** [comment]
glad to see the update on this! I don't have a Yubikey at hand for testing, but from the code it looks like I can make this work with Keepass2Android. 

Just one thing: You are testing for KDF == AES to decide how to calculate the master key. Is this actually the best way? You can have AES and still use kdbx4 (e.g. when using custom plugin data).

**Comment by droidmonkey** [comment]
AES KDF is perfectly valid in kdbx4. We may have to add an interlock to make sure we are never going backwards (ie kdbx4 -> kdbx3)

**Comment by phoerious** [comment]
That's not entirely true. If you select AES, then a KDBX3 is saved. And the user should have a way to go back in case they need the old format for compatibility and what not.
Also checking for AES in the transform method was the sleekest way to implement this, because the KDF is the only information available to that method. The CompositeKey class doesn't even hold a pointer to the database, so even if we save information about the format version there (which would make sense), the transform method wouldn't have access to that. We could pass the version as a parameter, but then every caller would need to have that available. In theory, this should be easy, but until we refactor the database saving and loading logic to be an atomic, self-contained class, it's not that trivial.

**Comment by phoerious** [comment]
I solved the problem. AES-KDF is now supported for KDBX4 and saving a KDBX4 database with AES-KDF doesn't convert it back to KDBX3 anymore. Please check out my latest commit on the KDBX4 branch.

**Comment by PhilippC** [comment]
I wanted to implement Challenge-Response in Keepass2Android finally, but unfortunately I am getting an invalid key. So I wanted to do a custom build of KeepassXC to add some debugging output for comparison of intermediate results. Unfortunately I am getting the same error as reported in 
https://github.com/keepassxreboot/keepassxc/issues/1185#issuecomment-354326971:

```
CMake Error at C:/msys64_3/mingw64/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find LibGPGError (missing: GPGERROR_LIBRARIES)
Call Stack (most recent call first):
  C:/msys64_3/mingw64/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindLibGPGError.cmake:23 (find_package_handle_standard_args)
  CMakeLists.txt:321 (find_package)

```

I have installed a clean MSys2 and followed the setup instructions for the build-environment. I also tried to install a few additional packages, so the output of pacman -Ss libgcrypt is now

```
$ pacman -Ss libgcrypt
mingw32/mingw-w64-i686-libgcrypt 1.8.2-1 [Installiert]
    General purpose cryptographic library based on the code from GnuPG (mingw-w64)
mingw32/mingw-w64-i686-libgpg-error 1.27-1 [Installiert]
    Support library for libgcrypt (mingw-w64)
mingw64/mingw-w64-x86_64-libgcrypt 1.8.2-1 [Installiert]
    General purpose cryptographic library based on the code from GnuPG (mingw-w64)
mingw64/mingw-w64-x86_64-libgpg-error 1.27-1 [Installiert]
    Support library for libgcrypt (mingw-w64)
msys/libgcrypt 1.8.1-1 (libraries) [Installiert]
    General purpose cryptographic library based on the code from GnuPG
msys/libgcrypt-devel 1.8.1-1 (development) [Installiert]
    Libgcrypt headers and libraries
msys/libgpg-error 1.27-1 (libraries) [Installiert]
    Support library for libgcrypt

```

Do you have any additional hint on how to solve this?

**Comment by phoerious** [comment]
Try deleting your build environment. If it still doesn't work, try setting CMAKE_LIBRARY_PATH to include the path to libgpg-error. You should probably also uninstall the msys/ packages, they might interfere with the mingw -w64-x86_64* packages. You also don't need any of the mingw -w64-i686-* packages if you only want to build for 64bit.

**Comment by PhilippC** [comment]
it turned out that cmake was selecting my Visual C++ compiler instead of gcc in msys. Build is now working.

**Comment by trevorbernard** [comment]
I'd be happy to test this integration. Has it been incorporated into PhilippC/keepass2android yet?

**Comment by PhilippC** [comment]
please see https://github.com/PhilippC/keepass2android/issues/4 for updates on this. Unfortunately I don't have lots of time these days to work on KP2A :-(

**Comment by droidmonkey** [comment]
@PhillippC do you have a branch or PR you are using? I am an Android programmer as well and can assist in debugging if you like.

**Comment by PhilippC** [comment]
I finally released a first version, see https://github.com/PhilippC/keepass2android/issues/4#issuecomment-401763890

**Comment by sinistersnare** [comment]
Hello, this issue was mentioned on the [KeePassXC FAQ](https://keepassxc.org/docs/#faq-platform-mobile). Is this resolved? If so, then the warning can be removed.

**Comment by PhilippC** [comment]
I would suggest to relax the warning stating that it works for kdbx4 databases with keepass2android.
