### ISSUE TITLE
[BUG] When having mutliple Databases opened KeepassXC asks twice in which one a new Passkey shall be stored

### ISSUE THREAD

**Issue by sahriVoraus** [keepassxreboot/keepassxc#10602]
## Overview
When you want to create a new Passkey with two databases opened at the same time the dialogs will look like this:
Select the Database
![Screenshot 2024-04-19 093644](https://github.com/keepassxreboot/keepassxc/assets/35914346/ec679e62-0d42-40d8-bc3c-5c7fab9c7094)
Register the Passkey
![Screenshot 2024-04-19 093652](https://github.com/keepassxreboot/keepassxc/assets/35914346/b1ca7ba0-b765-4faf-84f4-cf9752b46e30)
Again select the Database:
![Screenshot 2024-04-19 093701](https://github.com/keepassxreboot/keepassxc/assets/35914346/9f024353-e0e2-43ed-b4dd-da580e33a729)

[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. open two databases
2. connect both to the browser plugin
3. enable Browser settings like shown in context (The setting "Search in all databases" doesn't seem to affect the passkey behavior. When I have two databases opened I will always be asked in which one I want to search for the passkey or where to store it. Maybe another bug?)
4. add a new Passkey for example for https://www.passkeys.io/

## Expected Behavior
I expect to only get asked at the beginning

## Actual Behavior
You have to select the database twice

## Context
My KeepassXC Browser Integration settings:
![image](https://github.com/keepassxreboot/keepassxc/assets/35914346/46481eee-7557-416e-9695-74a2f8694bc1)

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.7
Revision: 68e2dd8

Qt 5.15.11
Diagnosemodus ist deaktiviert.

Betriebssystem: Windows 11 Version 2009
CPU-Architektur: x86_64
Kernel: winnt 10.0.22631

Aktivierte Erweiterungen:
- Auto-Type
- Browser-Integration
- Passkeys
- SSH-Agent
- KeeShare
- YubiKey
- Schnelle Entsperrung

Kryptographische Bibliotheken:
- Botan 3.1.1

**Comment by varjolintu** [comment]
A database selection is also asked when authenticating after register has been done. Fixing that too.
