### ISSUE TITLE
autotype problem

### ISSUE THREAD

**Issue by Owhenthesaints** [keepassxreboot/keepassxc#10611]
## Overview
Trying to use the autofill (ctrl+shift+v) does not autofill it just minimizes the current window

## Steps to Reproduce
1. install keepassxc through apt installer on ubuntu
2. open a database (that I created with keepass2)
3. try to ctrl+shift+v entry into a web login page

## Expected Behavior
A minimization of the window and an autofill of the entry values

## Actual Behavior
Just a minimization of the window

## Context
On keepass2 I had the same bug. Upon opening through terminal xith keepassxc I get : Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway. And when trying to autotype I do not get error message/warning.

When running keepass2 from terminal I get Failed to load module "canberra-gtk-module". Then when I try to autotype I get XGetWindowProperty[_NET_ACTIVE_WINDOW] failed (code=1)\n xdo_get_active_window reported an error.
Leading me to suspect that is where the error originates from.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.7
Revision: 68e2dd8

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: Gnome
Windowing System: X11

**Comment by droidmonkey** [comment]
You are using Wayland and not X11 as your base window manager. You can only use autotype with windows run under xwayland in this scenario. This means your browser is running under pure wayland.
