### ISSUE TITLE
0x00007FF699364EFD指令引用了0x0000000000000000内存，该内存不能 为 read.

### ISSUE THREAD

**Issue by thinkcodee** [keepassxreboot/keepassxc#10617]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

When I use automatic input, I use the shortcut Ctrl+` to open the KeepassXC panel. After unlocking it, the following error is reported: 0x00007FF699364EFD instruction references 0x000000000000000 memory, which cannot be read. It happens several times a day, don't know how to solve it?
![QQ截图20240423135238](https://github.com/keepassxreboot/keepassxc/assets/20852149/02efe665-90db-4844-a1a1-1e884f1af6a2)

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Unlocking the KeePassXC database allows for quick input instead of reporting errors as shown in the following figure

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
When I use automatic input, I use the shortcut `Ctrl+` `to open the KeepassXC panel. After unlocking it, the following error is reported: 
 `0x00007FF699364EFD instruction references 0x000000000000000 memory, which cannot be read. ` It happens several times a day, don't know how to solve it?

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION
Revision: 2.7.7

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows11

**Comment by droidmonkey** [comment]
This is fixed for 2.7.8 already, we will be releasing soon. You can use a snapshot build for now https://snapshot.keepassxc.org

**Comment by thinkcodee** [comment]
After updating to version 2.8.0 snapshot, I used it for a while and never reported that error again. Thank you very much.

**Comment by phoerious** [comment]
It's should also be fixed in the 2.7.8 stable version.
