### ISSUE TITLE
Window resize changes size of navigation sidebar

### ISSUE THREAD

**Issue by asdkant** [keepassxreboot/keepassxc#10613]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
When I resize the application's window, the size of the navigation sidebar on the left (the one showing the DB's folders) changes size proportional to the window. This may be done as a naive approach, but it's not good from a usability standpoint because what usually changes is the content on the main list (on the right side)

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Open a database
2. resize the window horizontally

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
The horizontal size of the left sidebar shoul stay constant

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
The horizontal size of the left sidebar changes proportional to the window.
Take for example GIMP or Dolphin: in both, if you resize the window the toolbars on the sides are not resized.

## Context
[NOTE]: # ( Give us any additional information you may have. )

See how when I resize the window the sidebar absolute size changes and longer folder names get truncated:
![image](https://github.com/keepassxreboot/keepassxc/assets/3915542/5e7db49c-76d1-45f4-9207-280c00183fac)

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.7
Revision: 68e2dd8

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: KDE (Plasma 6.0.4, KDE Framework 6.1.0, QA 6.7)
Windowing System: Wayland

**Comment by droidmonkey** [comment]
Related to this one I just closed in favor of your report: https://github.com/keepassxreboot/keepassxc/issues/6152

This is a known frustration and I agree needs to be corrected.

**Comment by 0xdeadbeer** [comment]
Commit changes: 
```patch
diff --git a/src/gui/DatabaseWidget.cpp b/src/gui/DatabaseWidget.cpp
index e38b943a..c4e24a34 100644
--- a/src/gui/DatabaseWidget.cpp
+++ b/src/gui/DatabaseWidget.cpp
@@ -138,8 +138,9 @@ DatabaseWidget::DatabaseWidget(QSharedPointer<Database> db, QWidget* parent)
     m_mainSplitter->setChildrenCollapsible(true);
     m_mainSplitter->addWidget(m_groupSplitter);
     m_mainSplitter->addWidget(rightHandSideWidget);
-    m_mainSplitter->setStretchFactor(0, 30);
-    m_mainSplitter->setStretchFactor(1, 70);
+    m_mainSplitter->setStretchFactor(0, 0);
+    m_mainSplitter->setStretchFactor(1, 100);
+    m_mainSplitter->setSizes({1, 1});
 
     m_previewSplitter->setOrientation(Qt::Vertical);
     m_previewSplitter->setChildrenCollapsible(true);

```

Tried to correct this behaviour by taking example [from the preview splitter](https://github.com/keepassxreboot/keepassxc/blob/develop/src/gui/DatabaseWidget.cpp#L173-L175) (since it looks to have the desired behaviour). Seems good to me now, thoughts?

**Comment by 0xdeadbeer** [comment]
I noticed similar behaviour with the tagsWidget when changing window's height. Perhaps we could fix that as well with a similar change..?  
```patch 
diff --git a/src/gui/DatabaseWidget.cpp b/src/gui/DatabaseWidget.cpp
index c4e24a34..5ef1549d 100644
--- a/src/gui/DatabaseWidget.cpp
+++ b/src/gui/DatabaseWidget.cpp
@@ -121,8 +121,9 @@ DatabaseWidget::DatabaseWidget(QSharedPointer<Database> db, QWidget* parent)
     m_groupSplitter->setChildrenCollapsible(true);
     m_groupSplitter->addWidget(m_groupView);
     m_groupSplitter->addWidget(tagsWidget);
-    m_groupSplitter->setStretchFactor(0, 70);
-    m_groupSplitter->setStretchFactor(1, 30);
+    m_groupSplitter->setStretchFactor(0, 100);
+    m_groupSplitter->setStretchFactor(1, 0);
+    m_groupSplitter->setSizes({1,1});
 
     auto rightHandSideWidget = new QWidget(m_mainSplitter);
     auto rightHandSideVBox = new QVBoxLayout();
```
