### ISSUE TITLE
2FA is wrong

### ISSUE THREAD

**Issue by Yakuza112v2** [keepassxreboot/keepassxc#10628]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

## Steps to Reproduce
When I display a 2FA, it is displayed incorrectly. The code is completely different from Google Auth. Even if I recreate it, your program changes the code.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.7
Revision: 68e2dd8

[NOTE]: # ( Pick choices based on your environment )
KeePassXC - Version 2.7.7
Revision: 68e2dd8

Operating system: Windows 10 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.19045

**Comment by droidmonkey** [comment]
Sync your computers time
