### ISSUE TITLE
Latest release not on Microsoft Store

### ISSUE THREAD

**Issue by AkechiShiro** [keepassxreboot/keepassxc#10622]
## Overview
Latest release should be on Microsoft Store deployed by a CI/CD I'd guess.

## Steps to Reproduce
1. Install and manage update via Microsoft Store on Windows.

## Expected Behavior
Should be up to date.

## Actual Behavior
Isn't up to date

## Context
Windows only environnement (Microsoft Store as a package manager)

Operating System: Windows

**Comment by droidmonkey** [comment]
It's up there. Microsoft store doesn't allow you to update non UWP apps though, you need to manually update.

**Comment by AkechiShiro** [comment]
Thanks maybe this should be documented or written in the description on the Store.

I saw Keepassxc told me he wanted to update but I thought that the update would come from the MS Store as it was how I installed it.

**Comment by AkechiShiro** [comment]
Is there any future plans to provide an UWP app ? @droidmonkey

**Comment by droidmonkey** [comment]
Yah I tried the UWP wrapper tool and it was OK, need to be fully tested and refined.

**Comment by AkechiShiro** [comment]
Is there anywhere where progress can be subscribed to or your just doing that on your side and will release when it is fully tested/refined.

**Comment by droidmonkey** [comment]
The latter, but it's not on my high priority list

**Comment by AkechiShiro** [comment]
Still thanks for the efforts, if I can help in any way for testing, feel free to let me know !
