### ISSUE TITLE
KeepassXC Unable to Recognize Canokey's FIDO2 HMAC-SHA1 Extension

### ISSUE THREAD

**Issue by cangkuai** [keepassxreboot/keepassxc#10629]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
When attempting to use Canokey as a hardware key with KeepassXC, it seems that KeepassXC is unable to recognize the FIDO2 HMAC-SHA1 extension implemented by Canokey.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1.Connect Canokey to the system.
2.Open KeepassXC.
3.Attempt to use Canokey as a hardware key for authentication.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
KeepassXC should recognize and successfully utilize Canokey as a hardware key for FIDO2 authentication, including the HMAC-SHA1 extension.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
KeepassXC does not seem to recognize Canokey as a valid hardware key for FIDO2 authentication, specifically the HMAC-SHA1 extension.

## Context
[NOTE]: # ( Give us any additional information you may have. )
canokeys document link is https://docs.canokeys.org/

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.7
Revision: 68e2dd8

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows

**Comment by cangkuai** [comment]
English is not my native language, so please excuse any mistakes in this report

**Comment by droidmonkey** [comment]
We don't support FIDO2 hmac. This is a feature request that is not implemented.
