### ISSUE TITLE
Possibility to move entries to another group

### ISSUE THREAD

**Issue by cschritt** [keepassxreboot/keepassxc#1062]
Currently it is not possible to move an entry from one group to another.

## Expected Behavior
As a user I want to be able to move an entry from on group to another. Either by a context menu function or via drag an drop.

## Current Behavior
There is no context entry and an attempt to drag an entry opens the edit dialogue.

## Debug Info
KeePassXC - 2.2.0
Revision: caa49a8ef3ee28ed478192389b21d61107b3b8e0

Libraries:
- Qt 5.9.1
- libgcrypt 1.8.1

**Comment by weslly** [comment]
Works fine for me. What OS are you using?

![2017-10-12 05_28_07](https://user-images.githubusercontent.com/107672/31486542-39c4bd16-af0e-11e7-9b5a-837fc07d6cc7.gif)

**Comment by cschritt** [comment]
I tested it on the following operating Systems:

Arch Linux 
Kernel 4.13.5
Cinnamon Desktop 3.4.6

Debian 8.9
Kernel 3.16.0
KDE 4.14.2

**Comment by TheZ3ro** [comment]
Tested on:

xUbuntu
Kernel 4.4.0
XFCE 4.12

Working just fine.

I think it's a Qt problem.
Working fine with Qt 5.5.1 and Qt 5.7 on xUbuntu above

**Comment by cschritt** [comment]
You're right it's working for me now, too. Don't know what changed or what I could have possibly done wrong :)

**Comment by gothchibJo** [comment]
> Works fine for me. What OS are you using?
> 
> ![2017-10-12 05_28_07](https://user-images.githubusercontent.com/107672/31486542-39c4bd16-af0e-11e7-9b5a-837fc07d6cc7.gif)

Drag and drop doesn't work on OS X Big Sur for an entry in the Root group.
v. 2.6.2

**Comment by phoerious** [comment]
It's a pinned issue: #5636
