### ISSUE TITLE
Keepass doesn't respect location of system buttons in title bar

### ISSUE THREAD

**Issue by gregoiregentil** [keepassxreboot/keepassxc#10631]
Linux Ubuntu 24.04, KeePassXC 2.7.6 installed via Ubuntu apt manager. If the OS has the Close/Minimize/Maximize buttons on left of window, KeePassXC doesn't respect such location and the buttons stay on right:

![Screenshot from 2024-04-27 12-23-12](https://github.com/keepassxreboot/keepassxc/assets/486156/0d3769a1-6df0-4e52-9c5e-69b5e901e63d)

Perhaps, I'm missing a setting somewhere?

On Ubuntu 20.04 with KeePassXC 2.4.3, it was working properly.

**Comment by droidmonkey** [comment]
You likely installed the snap version, we don't control button placement in the title bar. We recommend the flatpak or ppa.

**Comment by gregoiregentil** [comment]
No, it's installed via the default deb apt manager without snap. I don't use snap. It's a regression because it was working on Ubuntu 20.04 + KeepasXC 2.4.3 installed in the same conditions, via Ubuntu manager without snap.

You can browse the following link:
https://packages.ubuntu.com/noble/keepassxc

Screenshot of previous system:

![Screenshot from 2024-04-26 07-43-18](https://github.com/keepassxreboot/keepassxc/assets/486156/0d331b1d-1ea0-4ccb-b390-bd3d7f7b62f8)

**Comment by droidmonkey** [comment]
Like I said, we don't have any control over the title bar. You are likely running wayland for your desktop env and keepassxc is running under x11

**Comment by michaelk83** [comment]
Also, default Ubuntu is Gnome/GTK, and KeePassXC is Qt. Those may have separate settings for window decorations.
