### ISSUE TITLE
2.7.7 does not connect with browser extension in Firefox

### ISSUE THREAD

**Issue by noanli** [keepassxreboot/keepassxc#10630]
## Overview

After reloading via extension it isn't able to connect and there is no button for connecting or re-connecting. The connect button in extension settings does no result either.

## Steps to Reproduce
1. Install the below mentioned software
2. remove prior database connection
3. press reload in floating window or via extension settings

## Expected Behavior
A popup window for naming the connection.

## Actual Behavior
No popup for naming the connection.

## Context
I was on 2.6.6 via Deb repository and everything but the password generator still worked well so far. I upgraded to 2.7.7 via flatpak repository for hopefully having the password generator again.

If someone is interested in going into this I can easily reproduce the situation and add more details, as I already done it two times without luck.

I'm now back at 2.6.6 for having little patience without assistance to troubleshoot this. Re-connecting my database works well with this version.

KeePassXC 2.7.7
KeePassXC-Browser Version: 1.9.0.3
Firefox 124.0.2
Ubuntu 22.04.4 LTS
MATE 1.26.0

**Comment by droidmonkey** [comment]
Since you switched from native to flatpak, you need to go to application settings, browser tab, and re-enable Firefox integration (if not already checked). Then press ok.

**Comment by noanli** [comment]
> Since you switched from native to flatpak, you need to go to application settings, browser tab, and re-enable Firefox integration (if not already checked). Then press ok.

That's what I did right at the start. Did not help. I would not file a bug if it were that easy. But thanks for looking into this. If there's any way of debugging my issue via any console or logs, I'd love to add to KeePass this way. While I'm fine, if I'm the only one, ignoring the issue and hoping for some other update in my setup for making a then recent version work.

**Comment by droidmonkey** [comment]
I can assure you there isn't a bug here, this is always related to native messaging configuration. Also note that Firefox must be native installed or snap, flatpak Firefox doesn't support native messaging. We have an extensive troubleshooting guide: https://github.com/keepassxreboot/keepassxc-browser/wiki/Troubleshooting-guide

**Comment by droidmonkey** [comment]
This could also be an apparmor block from Firefox, you may have to allow the path to the flatpak binary.
