### ISSUE TITLE
Loop, loop and loop

### ISSUE THREAD

**Issue by LLKoder** [keepassxreboot/keepassxc#10633]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
In settings I use "Automatically save after every change".
I open two base (Base-1, Base-2).
Base-1 have KeyShare folder `ks` and one entry.
Base-2 have KeyShare folder `ks` only.
I edit one entry (not in `ks`) in Base-1. Click Save.
And what do I see? Forever loop of saving between two windows of KeePassXC.

It seems KeePassXC see the update date of base instead entry.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
See above.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Correct saving.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Incorrect saving. Forever loop of saving.

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.7
Revision: https://github.com/keepassxreboot/keepassxc/commit/68e2dd8d22fdef79c72ad5902e026c698e2ff087

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: Gnome/KDE/XFCE/Mate/Cinnamon
Windowing System: X11/Wayland

**Comment by droidmonkey** [comment]
#6526
