### ISSUE TITLE
bug after last update

### ISSUE THREAD

**Issue by ghost** [keepassxreboot/keepassxc#10639]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
Ever since the last update (to v. 2.7.7) waking my PC from sleep I receive error message and got logged off in application (in order to use the app, I have to log in again).

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Start KeePassXC and log in.
2. Put PC to sleep.
3. Wake the PC and there it is, the error message.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Make the app behave as before the last update, whereupon waking my PC made no error message appear and my login was still active, while all I had to do in order to use the app was entering my PIN code.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
already described

## Context
[NOTE]: # ( Give us any additional information you may have. )
there is no context, except all started after the last update

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Wersja 2.7.7
Rewizja: 68e2dd8

Qt 5.15.11
Tryb debugowania jest wyłączony.

System operacyjny: Windows 11 Version 2009
Architektura procesora: x86_64
Jądro: winnt 10.0.22631

Włączone rozszerzenia:
- Autowpisywanie
- Integracja z przeglądarką
- Klucze dostępu
- Agent SSH
- KeeShare
- YubiKey
- Szybkie odblokowanie

Biblioteki kryptograficzne:
- Botan 3.1.1

KeePassXC - VERSION 2.7.7
![keepassxc](https://github.com/keepassxreboot/keepassxc/assets/29859564/28820a10-0ca3-4158-b6a9-fd1e096bc009)

Revision: REVISION 

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 11 Pro (23H2)

**Comment by droidmonkey** [comment]
This is fixed for 2.7.8

**Comment by ghost** [comment]
this is great news, thanks!


niedz., 28 kwi 2024, 16:54 użytkownik Jonathan White <
***@***.***> napisał:
