### ISSUE TITLE
Crash when waking from sleep or prolonged screen lock

### ISSUE THREAD

**Issue by adam-kosseck** [keepassxreboot/keepassxc#10645]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

Since upgrading to 2.7.7 I've noticed KeepassXC crashing, usually when waking from sleep or unlocking the PC.  
I don't believe I ever saw this problem in prior versions.

The error reads: "KeePassXC: Windows - Application Error
The instruction at 0x0..... referenced memory at 0x0000000000000. The memory could not be read.  Click on OK to terminate the program"

So it sounds like a null pointer exception.

## Steps to Reproduce
1.  Start and unlock keepassXC
2.  Lock the computer, or put the computer to sleep
3.  Wake up the computer, the error message appears on the unlock screen before you enter credentials.

Note it doesn't happen every time, but I can reliably get it to crash at least once a day.

## Context
I have google drive installed, which provides windows explorer path mappings to my Google drive folder.
The database is stored in folder in the drive.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.7
Revision: 68e2dd8

Qt 5.15.11
Debugging mode is disabled.

Operating system: Windows 11 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.22631

Enabled extensions:
- Auto-Type
- Browser Integration
- Passkeys
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 3.1.1

**Comment by droidmonkey** [comment]
Fixed

**Comment by github-throwaway** [comment]
@adam-kosseck See #10599

**Comment by adam-kosseck** [comment]
Thank you for the clarification, next time I'll check the closed issues list before I post!

Is there an ETA for 2.7.8?
