### ISSUE TITLE
How to display URL and Notes in keepassxc for mac?

### ISSUE THREAD

**Issue by forsake** [keepassxreboot/keepassxc#1064]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Debug Info

KeePassXC - VERSION
Revision: REVISION

Libraries:
- LIBS

Operating system: OS
CPU architecture: ARCH
Kernel: KERNEL

Enabled extensions:
- EXTENSIONS

**Comment by phoerious** [comment]
I am not sure what you mean. You can view them on the edit entry screen.
User questions like that are also better asked on IRC.
