### ISSUE TITLE
[Potential bug] Windows Hello dialog can be easily skipped

### ISSUE THREAD

**Issue by kasamdor** [keepassxreboot/keepassxc#10646]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
Windows Hello dialog can be easily skipped by pressing Esc button.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Open KeePassXC and input a valid database passsword.
2. Press Esc after Windows Hello dialog appearance. 
> ![pic](https://github.com/keepassxreboot/keepassxc/assets/53122450/a8cf2da4-315e-44c8-817f-d98da1b2144f)
4. Done. We open database without any input at Windows Hello.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
We should not open database if Windows Hello check was not passed.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
We skip and ignore Windows Hello check having notification `Windows Hello setup was canceled or failed. Quick unlock has not been enabled.`

## Context
[NOTE]: # ( Give us any additional information you may have. )
I am not 100% sure that it is correct behaviour. It seems like bug. If Windows Hello dialog can be skipped so easily why we need use it at all - just disable it if database password is valid.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.7
Revision: 68e2dd8

[NOTE]: # ( Pick choices based on your environment )
Operating system: Windows 10 Version 2009

**Comment by droidmonkey** [comment]
Read the warning it's pretty clear

**Comment by kasamdor** [comment]
Thanks for your quick reply. I've read the warning, but also I did not understand motivation of asking user to pass trough additional check if the check is optional and can be skipped by any user. The check seems quite useless in such case. Of course, I may be wrong.

**Comment by droidmonkey** [comment]
It's not a check. It's how you setup quick unlock for use. If you cancel, then quick unlock won't be setup and enabled, as the warning says.
