### ISSUE TITLE
Notification of upcoming expirations

### ISSUE THREAD

**Issue by Pwe70** [keepassxreboot/keepassxc#10644]
Hello,

It would be great to add a feature to allow email notification, or dedicated "window warning" at startup, with the upcoming pwd expirations in X days, X could be defined on setup app.

Thanks in advance

Note: When we open the main window, it would be useful to set the focus on the "search bar"

Patrice

**Comment by phoerious** [comment]
KeePassXC cannot send emails without being connected to and authenticated with an email server.

**Comment by Pwe70** [comment]
Hi
Yes, I understand, but these settings could be implemented (management of SMTP server) in a new release.
Maybe it's too complicated to do, so a "warning window" on startup could also be useful.
Patrice

**Comment by droidmonkey** [comment]
This won't happen. We already show expiring entries on database unlock. Adjust the number of days in the application settings.
