### ISSUE TITLE
Hibernate and boot up - memory can't be read

### ISSUE THREAD

**Issue by wetxxx** [keepassxreboot/keepassxc#10655]
## Expected Behavior

When hibernate my PC and next day bring back I see this window since booting
## Current Behavior

Instrukcja [0x00007](tel:0900007)FF70 69FC4EFD odwołała się do pamięci adresem 0xO0000odd[00000000](tel:00000000). Pamięć nie może być read.
![Key](https://github.com/keepassxreboot/keepassxc-browser/assets/3983468/3fc97a02-1981-470d-bfbe-a7b32a2f83fc)

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Debug info
KeePassXC - 2.7.7
KeePassXC-Browser - 1.9.0.3
Operating system: Win64 Windows 11 Pro 22H2 22621.3527
Browser: Chrome/Chromium 124.0.0.0

**Comment by Josh68** [comment]
I am getting the same lately, Windows 11 Pro  (currently at 22H2 22621.3527, as in OP), KeePassXC v2.7.7 + Browser extension v1.9.0.3 (also as in OP). It's been happening for a while, only after sleep and wake. My search skills are failing, and I can't find anything in my logs.

**Comment by phoerious** [comment]
This will (very likely) be fixed with 2.7.8.
