### ISSUE TITLE
Disallow X Number of Consecutive Characters in Generated Passwords

### ISSUE THREAD

**Issue by LawsonJohnson** [keepassxreboot/keepassxc#10651]
## Summary
When generating a new password, add an option to disallow more than a certain number of consecutive characters in the generated password. Additionally, allow the number of consecutive characters allowed to be set as an integer between 0 and a sensible limit/maxint.

## Context
While I have absolutely no reason to ever want this feature, I'm encountering an increasing number of websites with this as a requirement (ex. no more than 2 characters of the same value in a row) and when using large passwords (eg. 64 character or higher) it is mildly annoying to deal with manually.

**Comment by droidmonkey** [comment]
This is an anti-pattern, and we won't support it. You'll have to manually edit the password or re-roll your generated password.
