### ISSUE TITLE
KeePassXC is mangling custom (XDG) URLs

### ISSUE THREAD

**Issue by cvpsmith** [keepassxreboot/keepassxc#10659]
## Overview

I'm running the latest KeePassXC 2.7.7 on Ubuntu 24.04.  My system is set up to handle some custom URLs via XDG.  For example, I have RustDesk installed, which in turn installs a custom XDG URL handler for rustdesk://<nine-digit number> (e.g. rustdesk://123456789).  The URL handler works just fine in Linux and in KeePass2.

For example, I can enter "xdg-open rustdesk://123456789" and it opens RustDesk to the proper location.  Same with KeePass2.  When I double-click on a link such as rustdesk://123456789, it opens in the proper location.  However, when I click the link in KeePassXC, it mangles it into a completely different number that resembles an IP address (11.98.160.135, to be exact).

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Use the Linux client.
2. Download and install the RustDesk app.
3. Set up a another machine with RustDesk.
4. Try connecting from the command-line with "xdg-open rustdesk://123456789" or whatever the code is.
5. Open KeePassXC and add the system and enter the link in the URL field.
6. Click the link.

## Expected Behavior
KeePassXC should open the URL using the application that the operating system has set up for the URL handler.

## Actual Behavior
KeePassXC opens it with a garbage number.

## Context
I installed KeePass2 just to test and it works fine there.  Other custom URL handlers are also likely affected.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.7
Revision: 68e2dd8

Qt 5.15.13
Debugging mode is disabled.

Operating system: Ubuntu 24.04 LTS
CPU architecture: x86_64
Kernel: linux 6.8.7-060807-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- Passkeys
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.19.3

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: Gnome
Windowing System: Wayland

**Comment by cvpsmith** [comment]
Not a huge problem.  I just discovered the "cmd://" URL handler and that solves my issue.

**Comment by droidmonkey** [comment]
The reason for this is because we pass the URL to Qt to resolve it as an "actual" URL. Qt interprets the string of numbers as a coded IP address.

https://github.com/keepassxreboot/keepassxc/blob/189688338201fa8b5c59083694bac2ec2ec432db/src/gui/DatabaseWidget.cpp#L972

After looking into this, there really isn't any fix on the Qt side as this happens even when not using `fromUserInput` (ie, direct QUrl construction). We don't want to implement a url construction on our side so the cmd:// work around stands for now.

**Comment by cvpsmith** [comment]
That's really unfortunate that Qt is implementing URLs in this manner.  It's misleading to the user because, if you right-click and copy, it correctly matches the user input, but the actual URL that gets passed is different.  This could be a very frustrating bug for the user!  So, I wonder if I should post a bug report to Qt?

**Comment by droidmonkey** [comment]
In all technicality, qt is not doing anything wrong. Rust Desk is not actually following the url standard. When a plain number is given as a `host` in a url, then it shall be interpreted as an ipv4 address. Rust Desk should be using something standard as the host like `userid` and put the number in the path (eg, `rustdesk://userid/123456789`). 

https://url.spec.whatwg.org/#host-parsing

See step 8

**Comment by droidmonkey** [comment]
Have you tried using this syntax?

`rustdesk://connection/new/123456789`

**Comment by cvpsmith** [comment]
Hey, that actually works!  Thank you!!!
