### ISSUE TITLE
KeepassXC 2.7.7 from Flathub crashes while in background (segfault at 0 ip XXXX error 4)

### ISSUE THREAD

**Issue by zapat3ro** [keepassxreboot/keepassxc#10652]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

I just installed Fedora Silverblue 40 a few days ago, and KeepassXC from Flathub is crashing after sitting idle in the background for a few seconds. It simply disappears from the desktop and I have to re-lauch it. It seems to not crash when a database is not loaded (locked).

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Open a keepass database (tried both a local file and a remote file through Nextcloud)
2. Load a password and shift over to a browser, sending KeepassXC to the background
3. After a few seconds (to a minute), KeepassXC is gone, with no error notification. Relaunching it works perfectly, but again disappears after a moment.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
KeepassXC should stay in the background (with database locked), until I need to use it again.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
KeepassXC crashes without notification.

## Context
[NOTE]: # ( Give us any additional information you may have. )
On the Logs app I get these two messages:

keepassxc[8895]: segfault at 0 ip 000055b7d75d5d88 sp 00007ffcdabefa70 error 4 in keepassxc[55b7d74f1000+2d3000] likely on CPU 6 (core 2, socket 0)

ANOM_ABEND auid=1000 uid=1000 gid=1000 ses=3 subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 pid=8895 comm="keepassxc" exe="/app/bin/keepassxc" sig=11 res=1

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.7
Revision: 68e2dd8

[NOTE]: # ( Pick choices based on your environment )
Operating System: Fedora Silverblue 40
Desktop Env: Gnome
Windowing System: Wayland

**Comment by droidmonkey** [comment]
Unfortunately that isn't enough information to troubleshoot, but this is likely the same crash we already fixed for upcoming 2.7.8.
