### ISSUE TITLE
Random crash on MacOS M1

### ISSUE THREAD

**Issue by db-az** [keepassxreboot/keepassxc#10657]
## Overview
Hello,

KeepassXC crashes randomly when I return to the window to retrieve a password.
Usually after putting my fingerprint on my Mac to open the database.
I didn't have this problem before, maybe an update?

In terms of display, I'm using compact mode, so I don't know if that has anything to do with the bug?

This is the MacOS error report :

  Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
  Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000000
  Exception Codes:       0x0000000000000001, 0x0000000000000000

  Termination Reason:    Namespace SIGNAL, Code 11 Segmentation fault: 11
  Terminating Process:   exc handler [5004]

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.7
Révision : 68e2dd8

Qt 5.15.11
Debug mode is disabled.

Operating system: macOS 14.4
CPU architecture: arm64
Kernel: darwin 23.4.0

Extensions enabled :
- Autocomplete
- Browser integration
- Access keys
- SSH agent
- KeeShare
- YubiKey
- Fast unlocking

Cryptographic libraries :
- Botan 3.1.1

**Comment by droidmonkey** [comment]
Fixed for 2.7.8

**Comment by db-az** [comment]
Hello, 
@droidmonkey great !, when 2.7.8 will be online ?
