### ISSUE TITLE
Crash on wakeup after suspend on windows

### ISSUE THREAD

**Issue by Kasi07** [keepassxreboot/keepassxc#10658]
## Overview
Sometimes after suspending my Laptop KeePassXC crashes when I wake up the Laptop again.

## Steps to Reproduce
1. Open Database
2. Suspend PC
3. Wake PC

## Expected Behavior
KeePassXC should have locked the database and stay in the background.

## Actual Behavior
KeePassXC crashes with 

![image](https://github.com/keepassxreboot/keepassxc/assets/63197565/c091822c-e331-42d9-9655-7d7f6ccfb26b)

Translation from German:
```
QTrayIconMessageWindow: Windows - Error in application

The statement in 0x00007FF6FEAF4EFD referred to memory at 0x0000000000000000. The read operation could not be performed in memory.

Click on "Ok" to exit the program.
```

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.7
Revision: 68e2dd8

Qt 5.15.11
Debugging mode is disabled.

Operating system: Windows 11 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.22621

Enabled extensions:
- Auto-Type
- Browser Integration
- Passkeys
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 3.1.1

**Comment by phoerious** [comment]
Should be fixed with 2.7.8, to be released this weekend.
