### ISSUE TITLE
"Lock databases when session is locked or lid is closed" setting isn't saved on Mac

### ISSUE THREAD

**Issue by tcgoetz** [keepassxreboot/keepassxc#1065]
The setting is not preserved. Other settings in the same pane are saved.

## Expected Behavior

The setting should be preserved.

## Current Behavior

The setting is not preserved.

## Steps to Reproduce (for bugs)
1. Enter Preferences
2. enter the Security preferences pane
3. check "Lock databases when session is locked or lid is closed"
4. click the "apply" button
5. click the "ok" button
6. enter the preferences again
7. enter the security pane of preferences
8. "Lock databases when session is locked or lid is closed" is not checked

## Context

My DB does not lock when I sleep or lock my laptop. The DB is available when I wake it up. It's a security issue.

## Debug Info

Libraries:
- LIBS

Operating system: OS
CPU architecture: ARCH
Kernel: KERNEL

Enabled extensions:
- EXTENSIONS

**Comment by TheZ3ro** [comment]
This is already fixed in 2.2.2 that will be released next week #1028
