### ISSUE TITLE
KeePassXC - ThievingFox can get access to the KeePassXC.exe database and get the access to the credentials

### ISSUE THREAD

**Issue by sarahdutt28** [keepassxreboot/keepassxc#10654]
Hello All,

We have come across this post where ThievingFox can get access to the KeePassXC.exe database and get the access to the credentials
https://www.kitploit.com/2024/04/thievingfox-remotely-retrieving.html

Do we have a way to address this vulnerability yet ?

Thanks

**Comment by phoerious** [comment]
The only way to protect yourself against DLL hijacking is to enforce code signatures on your PC. This is a Windows problem, not a KeePassXC problem.
