### ISSUE TITLE
Crash at 0x00007FF7DF134EFD accessing a null pointer on Resume from Hybernation

### ISSUE THREAD

**Issue by lasermangmx** [keepassxreboot/keepassxc#10666]
## Overview
Windows does report an violative read access from 0x00007FF7DF134EFD to nullptr, every time when resuming from hybernation (German "Ruhezustand").

## Steps to Reproduce
1. German Windows 11 pro / 64 bit, Ryzen 7 7xxxx, NVidia 4xxx
2. Logged in as user without M$ account (another user has an M$ account, but is not regulary used)
3. Installed KeePassXC - Version 2.7.7 / Revision: 68e2dd8
4. logged in to KeePassXC, minimized to task bar (not to tray)
5. Press Windows-Start Menu Icon, then the On/Off knob, then "Ruhezustand" (perhaps "Hybernate" in English?)
6. wait until PC goes entirely silent, all lights off
7. press power up knob to wake PC up again.
8. mouse click somewhere to bring the login prompt visible -> 
9. the given MessageBox appears.
10. (anyway, I can k(l)ick it away, do the login, restart KeePassXC, all fine ... untill next wakeup)

## Expected Behavior
Not crashing on Resume

## Actual Behavior
When resuming from hybernation (German "Ruhezustand"), KeePassXC crashes. Windows does report an violative read access.
A hardcopy of the MessageBox via ^C comes here:
```
---------------------------
KeePassXC: Windows - Fehler in Anwendung
---------------------------
Die Anweisung in 0x00007FF7DF134EFD verwies auf Arbeitsspeicher bei 0x0000000000000000. Der Vorgang read konnte im Arbeitsspeicher nicht durchgeführt werden.


Klicken Sie auf "OK", um das Programm zu beenden.
---------------------------
OK   
---------------------------
```

## Context
Hybernation Mode on Windows 11 / 64 bit
```
KeePassXC - Version 2.7.7
Revision: 68e2dd8

Qt 5.15.11
Diagnosemodus ist deaktiviert.

Betriebssystem: Windows 11 Version 2009
CPU-Architektur: x86_64
Kernel: winnt 10.0.22631

Aktivierte Erweiterungen:
- Auto-Type
- Browser-Integration
- Passkeys
- SSH-Agent
- KeeShare
- YubiKey
- Schnelle Entsperrung

Kryptographische Bibliotheken:
- Botan 3.1.1
```
OS details:
```
Betriebsystemname	Microsoft Windows 11 Pro
Version	10.0.22631 Build 22631
Systemhersteller	Gigabyte Technology Co., Ltd.
Systemmodell	X670 GAMING X AX V2
Systemtyp	x64-basierter PC
Prozessor	AMD Ryzen 7 7800X3D 8-Core Processor, 4201 MHz, 8 Kern(e), 16 logische(r) Prozessor(en)
BIOS-Version/-Datum	American Megatrends International, LLC. F21, 10.01.2024
SMBIOS-Version	3.6
Version des eingebetteten Controllers	255.255
BIOS-Modus	UEFI
BaseBoard-Hersteller	Gigabyte Technology Co., Ltd.
BaseBoard-Produkt	X670 GAMING X AX V2
BaseBoard-Version	x.x
Plattformrolle	Desktop
Sicherer Startzustand	Aus
Gebietsschema	Deutschland
Hardwareabstraktionsebene	Version = "10.0.22621.2506"
Installierter physischer Speicher (RAM)	64,0 GB
Gesamter physischer Speicher	63,1 GB
Verfügbarer physischer Speicher	48,8 GB
Gesamter virtueller Speicher	67,1 GB
Verfügbarer virtueller Speicher	49,6 GB
Größe der Auslagerungsdatei	4,00 GB
Auslagerungsdatei	C:\pagefile.sys
Kernel-DMA-Schutz	Aus
Virtualisierungsbasierte Sicherheit	Wird ausgeführt...
Virtualisierungsbasierte Sicherheit – erforderliche Sicherheitseigenschaften	
Virtualisierungsbasierte Sicherheit – verfügbare Sicherheitseigenschaften	Allgemeine Virtualisierungsunterstützung, DMA-Schutz, UEFI-Code Readonly, SMM Security Mitigations 1.0, Modusbasierte Ausführungssteuerung
Virtualisierungsbasierte Sicherheit – konfigurierte Dienste	Durch Hypervisor erzwungene Codeintegrität
Virtualisierungsbasierte Sicherheit – ausgeführte Dienste	Durch Hypervisor erzwungene Codeintegrität
Windows Defender-Anwendungssteuerungsrichtlinie	Erzwungen
Windows Defender-Anwendungssteuerungs-Richtlinie für den Benutzermodus	Überwachung
Unterstützung der Geräteverschlüsselung	Erweiterung zum Anzeigen erforderlich
```

**Comment by droidmonkey** [comment]
Fixed already for 2.7.8

**Comment by lasermangmx** [comment]
Uh, my KeePassXC just tells me, 2.7.7 is most recent version?
So does the [download page](https://keepassxc.org/download/#windows).

Edit:
Don't want to press anybody. Just pointing out that me and others perhaps are not able to see the fixed version. Am I just some minutes too early? This is okay, I'll download and verify it tomorrow then

**Comment by droidmonkey** [comment]
It's not released yet, tomorrow
