### ISSUE TITLE
Auto-Type doesn't filter entries when open after database unlocking

### ISSUE THREAD

**Issue by mih-kopylov** [keepassxreboot/keepassxc#10665]
## Overview

Auto-Type window shows all entries when it's open with a hotkey with a locked database.

## Steps to Reproduce
Prerequisites:
- have a database with a master key
- configure the application to have a global shortcut key for Auto-Type
- configure ethe application to use entry title to match windows for global Auto-Type
- have multiple entries in the database with associated windows (window title - sequence combination)

1. Open KeepassXC app, keep the database locked
2. Start some application that has a title associated with an entry in the database
3. Press Auto-Type hotkey
4. Enter the master key of the database

## Expected Behavior
The Auto-Type window is opened with the only entry associated with the window

## Actual Behavior
The Auto-Type window is opened with all the entries, like nothing matched the current application title.

## Additional Information

When pressing Auto-Type hotkey with the unlocked database, it shows the Auto-Type window with the only entry that matches the current window title.

The issue appeared after updating to 2.7.7. It works as expected in 2.7.6

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.7
Revision: 68e2dd8

Qt 5.15.11
Debugging mode is disabled.

Operating system: Windows 10 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.19045

Enabled extensions:
- Auto-Type
- Browser Integration
- Passkeys
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 3.1.1

Operating System: Windows 10

**Comment by droidmonkey** [comment]
Already fixed

**Comment by mih-kopylov** [comment]
2.7.7 is the latest version, where is it fixed?

**Comment by droidmonkey** [comment]
The next release

**Comment by mih-kopylov** [comment]
Is there another ticket that is duplicated by this one?

**Comment by droidmonkey** [comment]
Several.....

https://github.com/keepassxreboot/keepassxc/pull/10555
