### ISSUE TITLE
Autotype broken with 2.7.7. Rollback to 2.7.6 is OK. Regression ?

### ISSUE THREAD

**Issue by Korezze** [keepassxreboot/keepassxc#10664]
## Overview
Autotype broken with 2.7.7. Rollback to 2.7.6 is OK. Regression ?

## Steps to Reproduce
1.	Upgrade from 2.7.6 to 2.7.7 using existing database
2.	Open an internet site requesting classical  login/password
3.	Select login field
4.	Type autotype key
5.	Nothing is copied in login and  passwd fields
6.	Instead  a popup  appears and propose to search the entry in the whole database
7.	Search this entry, select it, click Enter :  nop again

## Expected Behavior
Like in 2.7.6 : after step 4, login and passwd should be automatically copied in related fields
Note : Desinstall 2.7.7 and reinstall 2.7.6 solve this issue. Reinstall then 2.7.7 and issue is back again.

## Actual Behavior
See "steps to reproduce"

## Context
Tested with 2 PC :

-	Windows 10 /  KeepassXC 2.7.6 = OK  and 2.7.7 = KO
-	Windows  11 / KeepassXC 2.7.6 = OK  and 2.7.7 = KO

**Comment by droidmonkey** [comment]
already fixed
