### ISSUE TITLE
KeepassXC 2.7.7 window stays front after Alt+Tab (to paste password to browser)

### ISSUE THREAD

**Issue by PTillman44** [keepassxreboot/keepassxc#10660]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem ) - When using Alt+Tab to switch from KeepassXC window to browser window, in order to paste username or password, KeepassXC remains as the front window. This prevents me from seeing the browser window behind KeepassXC and so I cannot paste until I click the browser window first and then click the entry field. 

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Open KeepassXC. Use Control+B to copy username.
2. Use Alt+Tab to naviaget from KeepassXC to Firefox browser window
3. Result - Browser window remains obscured by KeepassXC window, instead of bringing the browser window forward. 

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
I expect that using Alt+Tab will bring browser window in from of KeepassXC window, which would allow me to paste info in the correct entry field in the browser.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
See above.

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION
Revision: REVISION
KeePassXC - Version 2.7.7
Revision: 68e2dd8

Qt 5.15.11
Debugging mode is disabled.

Operating system: Windows 10 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.19045

Enabled extensions:
- Auto-Type
- Browser Integration
- Passkeys
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 3.1.1

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows/Linux/macOS
Desktop Env: Gnome/KDE/XFCE/Mate/Cinnamon
Windowing System: X11/Wayland

**Comment by droidmonkey** [comment]
View -> Always on Top (to deselect the feature)
