### ISSUE TITLE
Firefox reports virus warning when downloading version 2.7.8 

### ISSUE THREAD

**Issue by JohannesLipp** [keepassxreboot/keepassxc#10679]
## Overview
The download of `KeePassXC-2.7.8-Win64.msi` from https://keepassxc.org/download/ is blocked by Firefox due to security issues.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Use Firefox 125.0.3 (64-bit) on Windows
2. Go to https://keepassxc.org/download/ and click download
3. Wait for the download to finish. Firefox will show the security warning.

## Expected Behavior
Firefox downloads the update file and I can install it.

## Actual Behavior
Firefox shows a security warning:

![image](https://github.com/keepassxreboot/keepassxc/assets/15930331/fd944057-27b2-49ec-9abd-d531e36b5384)
![image](https://github.com/keepassxreboot/keepassxc/assets/15930331/d944ae4a-fd8a-4017-8c3d-b81d5c7011cf)

## Context

KeePassXC - 2.7.8
Operating System: Microsoft Windows 10 Home, 10.0.18363 Build 18363
Firefox 125.0.3 (64-bit)

**Comment by droidmonkey** [comment]
Report it as safe. There isn't anything we can do about this until the systems "learn" what is ok. 

> is blocked by Firefox due to security issues.

 It just says this isn't a common download, makes sense we literally just released it.

**Comment by JohannesLipp** [comment]
> It just says this isn't a common download, makes sense we literally just released it.

Thanks for the quick response. I am still wondering about this warning as I have never seen it before. Chrome also reports a "suspicious download". I will wait some time for these security warnings to go away before I run the file. Hope you understand. Thank you for the good work on Keepass!

**Comment by droidmonkey** [comment]
The warnings don't mean anything besides big corporations deciding to show warnings. We just shifted to a new code signing certificate because the last one expired. That's most likely what is prompting this. This isn't anything unusual in the open source world.

**Comment by JohannesLipp** [comment]
You were totally right: the warning does not appear anymore and I successfully installed the update. Thank you again for the great work on KeepassXC 🥳
