### ISSUE TITLE
keepassXC crash when locking windows

### ISSUE THREAD

**Issue by tchize** [keepassxreboot/keepassxc#10678]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
Since update to 2.7.7 (using winget install), keepassxc keeps on crashing when windows locks for a long period

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Open KeepassXC database
2. Lock computer (winkey + L)
3. Close laptop lid
4. Open laptop lid
5. There is a KeepassXC crash dialog on top of windows login screen

![image](https://github.com/keepassxreboot/keepassxc/assets/7933441/2b4a344b-aad5-4b49-9dc3-5c118e465e3f)
(It says "instruction at adress xxxx uses memory adress xxx, Memory state can not be read")

## Expected Behavior
KeepassXC locked when session was locked

## Actual Behavior
KeepassXC crashed because of a null pointer

## Context
I nearly never shutdown my keepassXC or laptop, always sleep mode.
KeepassXC is linked to opera browser which is always open too
Crash seems to happen at every sleep.

[NOTE]: # ( Paste debug info from Help → About here )

KeePassXC - Version 2.7.7
Revision: 68e2dd8

Qt 5.15.11
Debugging mode is disabled.

Operating system: Windows 11 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.22000

Enabled extensions:
- Auto-Type
- Browser Integration
- Passkeys
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 3.1.1

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 10

**Comment by phoerious** [comment]
Should be fixed in 2.7.8.
