### ISSUE TITLE
Direct Import Feature from Browser to KeePassXC

### ISSUE THREAD

**Issue by JPluess** [keepassxreboot/keepassxc#10671]
Hello KeePassXC Team,

I am writing to request a new feature that would greatly enhance the security and convenience for users who are transitioning from Firefox's built-in password manager to KeePassXC.

Feature Description:
I propose the development of an import option that would allow users to directly transfer their saved login credentials from Firefox or other Browsers to KeePassXC. This would bypass the current need to export passwords to a CSV file first, which poses a potential security risk even if the file is securely deleted afterward.

I maintain KeePassXC as a backup database for my passwords. I wish to periodically export from my browser to either overwrite or update the stored credentials in KeePassXC. A concern that arises during this process is the treatment of any passwords that may have been deleted from the browser; I would like an option to configure KeePassXC as the master source for password management, or align the browser as the primary source. Alternatively, create a new folder within the KeePassXC database for storing each new backup, organized by date.

Justification and Benefits:
- Security: By avoiding the creation of an unencrypted CSV file, we reduce the risk of sensitive data being accessed by unauthorized parties.
- Convenience: A direct import feature would simplify the migration process for users, making KeePassXC more accessible for those who are not tech-savvy.
- Privacy: This feature ensures that user data is handled in the most private manner possible, as it never needs to be unencrypted on the user's disk.

**Comment by droidmonkey** [comment]
There is no way to do this. The browser password manager is not accessible from an extension. 

In general, do not maintain two password managers. You either use the browser one or keepassxc. There is no such thing as syncing between the two and there never will be.

**Comment by JPluess** [comment]
Hey what if a python script in combination with selenium is used? This would omit the use of csv file.


```
import os
import json
import time
from selenium import webdriver
from selenium.webdriver.firefox.options import Options
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from tempfile import NamedTemporaryFile
from pynput.keyboard import Controller, Key

# Set up Firefox options for headless mode
options = Options()
options.headless = False  # Set to True if you want to run in headless mode

# Path to the Firefox WebDriver
geckodriver_path = '/path/to/geckodriver'

# Initialize WebDriver
driver = webdriver.Firefox(options=options, executable_path=geckodriver_path)
keyboard = Controller()

def enter_master_password(master_password):
    time.sleep(2)  # Wait for the master password prompt to appear
    for char in master_password:
        keyboard.press(char)
        keyboard.release(char)
    keyboard.press(Key.enter)
    keyboard.release(Key.enter)

def extract_firefox_passwords(master_password):
    passwords = []

    try:
        # Open Firefox and navigate to the logins page
        driver.get('about:logins')

        # Enter the master password if prompted
        if master_password:
            enter_master_password(master_password)

        # Wait until the page is fully loaded
        WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.CSS_SELECTOR, ".login-list-item")))

        # Extract the logins
        login_items = driver.find_elements(By.CSS_SELECTOR, ".login-list-item")
        for item in login_items:
            item.click()
            time.sleep(0.5)  # Wait for the details to load
            username = driver.find_element(By.CSS_SELECTOR, ".username-input").get_attribute("value")
            password = driver.find_element(By.CSS_SELECTOR, ".password-input").get_attribute("value")
            url = driver.find_element(By.CSS_SELECTOR, ".url-input").get_attribute("value")

            passwords.append({
                "url": url,
                "username": username,
                "password": password
            })
    except Exception as e:
        print(f"An error occurred during extraction: {e}")
    finally:
        driver.quit()

    return passwords

def import_to_keepassxc(passwords, db_path, db_password):
    try:
        # Create a temporary KeePassXC-compatible CSV file in memory
        with NamedTemporaryFile('w', delete=False) as temp_csv:
            temp_csv.write("Title,Username,Password,URL\n")
            for entry in passwords:
                temp_csv.write(f'{entry["url"]},{entry["username"]},{entry["password"]},{entry["url"]}\n')
            temp_csv_path = temp_csv.name

        # Command to import passwords into KeePassXC
        command = f"keepassxc-cli import {db_path} {temp_csv_path} --key-file {db_password}"
        os.system(command)

        # Clean up the temporary file
        os.remove(temp_csv_path)
    except Exception as e:
        print(f"An error occurred during import: {e}")

# Paths
db_path = '/path/to/your/keepassxc/database.kdbx'
db_password = '/path/to/your/keyfile'
master_password = 'your_firefox_master_password'  # Set your Firefox master password here

# Extract passwords from Firefox
passwords = extract_firefox_passwords(master_password)

# Import passwords into KeePassXC
import_to_keepassxc(passwords, db_path, db_password)
```

**Comment by droidmonkey** [comment]
Whatever you want to do
