### ISSUE TITLE
KeePassHTTP support for {TOTP} placeholder on custom fields

### ISSUE THREAD

**Issue by Generator** [keepassxreboot/keepassxc#1067]
## Expected Behavior

Adding {TOTP} on a new string field auto fill OTP code.

## Current Behavior

Not possible to use other placeholder on custom fields (KPH: ) like {TOTP}.

## Possible Solution

Allow placeholders as custom fields, like on original KeePassHTTP https://github.com/pfn/keepasshttp/pull/325

**Comment by frostasm** [comment]
@droidmonkey I'll try to fix this error today
