### ISSUE TITLE
Text inside a button changes its position upon hovering

### ISSUE THREAD

**Issue by ghost** [keepassxreboot/keepassxc#10674]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

https://github.com/keepassxreboot/keepassxc/assets/6960799/fe03b1d5-72cd-44fc-877e-f9d80fdf582a

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
Open welcome screen

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Text inside a button shouldn't change its position

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Text inside a button changes its position

## Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.8
Revision: f6757d3

Qt 5.15.11
Debugging mode is disabled.

Operating system: macOS 14.4
CPU architecture: arm64
Kernel: darwin 23.4.0

**Comment by xboxones1** [comment]
Duplicate https://github.com/keepassxreboot/keepassxc/issues/10509
