### ISSUE TITLE
Please update logo URL also in the release

### ISSUE THREAD

**Issue by jschleus** [keepassxreboot/keepassxc#10673]
## Overview
The README file of the current KeePassXC release 2.7.8 uses a stale logo URL.

## Steps to Reproduce
Call https://github.com/keepassxreboot/keepassxc/blob/2.7.8/README.md

## Expected Behavior
The project logo is shown correctly.

## Actual Behavior
Only a placeholder image is shown (since the logo cannot be downloaded).

## Context
Correct the used stale URL ("404 – Not Found) 
 https://keepassxc.org/images/keepassxc-logo.svg

to the probably now correct one (found in the "develop" branch)
  https://keepassxc.org/assets/img/keepassxc.svg

**Comment by droidmonkey** [comment]
done, thank you
