### ISSUE TITLE
Interface change? Hardware keys not supported anymore? Unable to unlock vault

### ISSUE THREAD

**Issue by grivanov** [keepassxreboot/keepassxc#10675]
## Overview
I just updated to the new version 2.78 on Windows Portable. I open the app to unlock my vault and notice the screen is changed. There is just one field for a password, the is no field to select a hardware key and a slot number as before. I entered my password, assuming that may be the hardware key will be requested on a second step but it was not - it just gave a HMAC mismatch error. As a result I cant open my vault.

## Some debug info
KeePassXC - Version 2.7.8
Revision: f6757d3

Qt 5.15.11
Debugging mode is disabled.

Operating system: Windows 10 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.19045

Enabled extensions:
- Auto-Type
- Browser Integration
- Passkeys
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 3.1.1

**Comment by phoerious** [comment]
This was changed in 2.7.7. Hardware keys are detected automatically and you will see a checkbox like so:
![image](https://github.com/keepassxreboot/keepassxc/assets/911270/f2b69354-4cbb-4127-b4e2-588113903bc8)

If the checkbox doesn't appear on its own, click the reload button to the right.

**Comment by grivanov** [comment]
Okay, turned out my hardware key wasn't properly detected by Windows. Just tried with a backup one and is showed. By the way, in my case I wasn't seeing the checkbox regarding hardware keys at all. It was just the password field and "I have a key file".

I also checked with the Docs before posting here and there is the old screenshot of the interface. Perhaps should be updated:
https://keepassxc.org/docs/KeePassXC_GettingStarted#_opening_an_existing_database

**Comment by phoerious** [comment]
The checkbox appears only if a key is plugged in.
