### ISSUE TITLE
Windows Defender SmartScreen blocks Setup of Version 2.7.8

### ISSUE THREAD

**Issue by jakieu** [keepassxreboot/keepassxc#10672]
![2024-05-06 13_58_57-Downloads](https://github.com/keepassxreboot/keepassxc/assets/8632220/05073f2e-7d61-42bf-93f6-52fb8c73d025)

Windows Defender blocks Version 2.7.8 Win64 (KeePassXC-2.7.8-Win64.msi). Setup of Version 2.7.7 doesn't have this problem. Is it safe to continue?

**Comment by droidmonkey** [comment]
Yes of course, Microsoft being dumb as usual

**Comment by droidmonkey** [comment]
This is the first release with our new signing cert because the old one expired

**Comment by jakieu** [comment]
Thank you for the clarification. 👍🏻

**Comment by psyciknz** [comment]
Do one of the dev want to report it as safe with microsoft?  as they might lend more weight to the report than is just users do it.

**Comment by droidmonkey** [comment]
They don't care if you are a dev or a random person. How do they even know you are a dev? The more reports of trust, the better.

**Comment by senpos** [comment]
Firefox on Windows 10 shows this message:
![image](https://github.com/keepassxreboot/keepassxc/assets/9695470/11fe578c-2662-437c-84c2-e01df89eb8fd)

My guess is that it takes information from SmartScreen, while it is not stated anywhere in the interface.

**Comment by phoerious** [comment]
I would guess that there is some learning algorithm behind SmartScreen that flags the virginity of our certificate. I hope this will settle once more people have downloaded and used the new release and that it will not pop up again for future releases.
