### ISSUE TITLE
Double-click on filtered list item exits search instead of opening entry edit

### ISSUE THREAD

**Issue by woj-tek** [keepassxreboot/keepassxc#10677]
## Overview
When searching for an entry and trying to edit it via double-click search/filter is exited instead of entry being edited (selection is retained so I can edit it but still)

## Steps to Reproduce
1. go to Search (cmd+F)
2. type something to filter the list
3. double-click on one of the filtered out items

## Expected Behavior
Edit screen should be opened

## Actual Behavior
text from search filed is removed instead of entry edit screen opened.

## Context
KeePassXC - Version 2.7.8
Revision: f6757d3

Qt 5.15.11
Debugging mode is disabled.

Operating system: macOS 14.4
CPU architecture: arm64
Kernel: darwin 23.4.0

Enabled extensions:
- Auto-Type
- Browser Integration
- Passkeys
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 3.1.1

~~~~

I searched for similar issues ("dubleclick" and "double-click search" keywords) and this seemed to be most relevant https://github.com/keepassxreboot/keepassxc/issues/8610 but it's about something different.

**Comment by droidmonkey** [comment]
You need to double click on the entry title, not the group. Double clicking on the group opens the group and selects the entry in it. This is by design.

**Comment by woj-tek** [comment]
OMG, indeed it works! I removed group from search result just to avoid the issue (maybe group could be disabled by default? Or maybe organise filtering by selecting group in the left-hand tree instead of adding column?)
