### ISSUE TITLE
ProtonPass export (.csv or .json) empty

### ISSUE THREAD

**Issue by Asturgeek** [keepassxreboot/keepassxc#10682]
KeepassXC 2.7.7 (Fedora repo) and 2.7.8 (appimage) import database from ProtonPass are empty, without content.
I try with .csv and .json import, same issue

Operating System: Fedora 40 Woprkstation
Desktop Env: Gnome 46
Windowing System: Wayland

Thanks

**Comment by droidmonkey** [comment]
Make sure you have a title column selected. Without providing a sample csv file or screenshots then there is nothing we can do here.
