### ISSUE TITLE
Expand productivity of search bar | Find items when a part of the searchstring is in a higher-level folder name

### ISSUE THREAD

**Issue by Manuel1948** [keepassxreboot/keepassxc#10685]
For example:

I have this structure:

Customers
.....THUU
..........Users
..........SMB
..........Certificates
.....HHTG
..........Users
..........Certificates

Now i would like to find an entry in Customers/THUU/Users/SMB with the user "veeam", which also exists in other folders/customers.
In Keepass 2.x I would type the following in the search bar: THUU veeam
And I get my results, because the full path to the entry is also searched/screened.

But KeePassXC doesn't find an entry, because the entry is not directly in the THUU folder, instead it is in a sub(sub)folder of it.

This greatly reduces the productivity of the search.

**Comment by Manuel1948** [comment]
Maybe this co-relates a bit to issue #9574

**Comment by droidmonkey** [comment]
Use the group filter, `g:THUU`. Read the user guide for more information on search.

**Comment by Manuel1948** [comment]
> Use the group filter, `g:THUU`. Read the user guide for more information on search.

This is also not working because the group filter only finds direct children.

**Comment by droidmonkey** [comment]
use wildcards: `g:*/THUU/* u:veam`

**Comment by Manuel1948** [comment]
> use wildcards: `g:*/THUU/* u:veam`

okay thank you this is working - seems like the search function is inconveniant and unlogical.
Inconveniant, because it takes more time to enter the complex string, than to simply scroll to the folder.

too bad

**Comment by droidmonkey** [comment]
we search for entries not groups. The way we handle it is far more robust than keepass2. If you want you can save the search with the group as a prefix and recall it whenever you want. Thanks.
