### ISSUE TITLE
Copy function from database view does not work after 2.7.8 Flatpak update

### ISSUE THREAD

**Issue by EAbuVrwV** [keepassxreboot/keepassxc#10683]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

The copy functions from the database viewing panel do not work after the latest Flatpak update. Example: 

Ctrl + B = copy username field
Ctrl + C = copy password field
Ctrl + U = copy URL field

OR

Right click + copy

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Open a previously-existing database in Flatpak v 2.7.8
2. Attempt to use the Ctrl + copy shortcuts, or right click + copy.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

The fields should copy to clipboard as in the previous version.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

The fields do not copy.

## Context
[NOTE]: # ( Give us any additional information you may have. )

The update automatically wiped my application settings and reset clear clipboard to 1 second, and also turned on the double click to copy setting, so originally I thought one of these was the issue. But even after moving clear clipboard to 60 - 120 seconds and turning off double click to copy, it doesn't resolve. The only way to copy is to actually open the individual entry and copy directly from the field.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.8
Revision: f6757d3
Distribution: Flatpak

Qt 5.15.10
Debugging mode is disabled.

Operating system: KDE Flatpak runtime
CPU architecture: x86_64
Kernel: linux 6.8.0-76060800daily20240311-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- Passkeys
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 3.3.0

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux Mint 21.2
Desktop Env: Cinnamon 5.8.4
Windowing System: Unsure

**Comment by phoerious** [comment]
Something about the Flatpak release is fundamentally broken and we're investigating. We have reverted the Flatpak to 2.7.7 in the meantime.

**Comment by droidmonkey** [comment]
If 2.7.7 reversion also exhibits the same failures, then we know it's a fundamental flatpak problem.

**Comment by EAbuVrwV** [comment]
Reverted to 2.7.7 and issue was fixed.

**Comment by droidmonkey** [comment]
Did you revert or update?

**Comment by EAbuVrwV** [comment]
I guess technically update. Used this command:

sudo flatpak update --commit=c51b64dad185bf2f156dea9e6805fd646473f5ddbbd5ae4194687118add2e9fe org.keepassxc.KeePassXC

Then set 2.7.8 to ignore in my update manager.

**Comment by droidmonkey** [comment]
Do it without the commit flag, I pushed 2.7.7 again but it's a rebuild not the original

**Comment by CodeShakingSheep** [comment]
> Something about the Flatpak release is fundamentally broken and we're investigating. We have reverted the Flatpak to 2.7.7 in the meantime.

Just want to add that additionally I have the weird behavior that all my usernames are being masked but the passwords not (they are in clear text), see screenshot.

![image](https://github.com/keepassxreboot/keepassxc/assets/19874562/39727be5-025c-4050-a492-260aac2584df)

**Comment by phoerious** [comment]
The settings are all messed up and randomly shuffled. This is a plausible side effect of that.

**Comment by EAbuVrwV** [comment]
> Do it without the commit flag, I pushed 2.7.7 again but it's a rebuild not the original

Sorry, I'm not following. If I run sudo flatpak update org.keepassxc.KeePassXC it updates to 2.7.8 again and reintroduces the bug.

**Comment by droidmonkey** [comment]
Interesting looks like the reversion didn't take then

**Comment by droidmonkey** [comment]
Fixed in https://github.com/flathub/org.keepassxc.KeePassXC/pull/128
