### ISSUE TITLE
password database's folder started acting weird after update to latest version 

### ISSUE THREAD

**Issue by bombames** [keepassxreboot/keepassxc#10680]
## Overview
after the latest update, the folder in which my password database has been stored in up to this point started acting weird.
The database I've been using disappeared and can't be viewed (I suspect it's still there and can't be viewed)
Despite having the same permissions as other folders at the same location (some of which I can make new databases in), trying to do anything, including copying my backup back into the folder, gives me "cannot do this operation" style errors (for copying the backup into the folder, the error reads "Error opening file “/run/user/1000/doc/8d285b01/passwordManager”: No such file or directory")

## Steps to Reproduce
1. have a previous version (I do not remember for sure which version I've been using, however I'm fairly confident it was 2.7.6)
2. have a database, mine was in /run/user/1000/doc/8d285b01, the default location
3. have keepassxc auto-update
4. I'm unaware if there and what are any additional requirements to reproduce the conditions

## Expected Behavior
for the database to remain and stored folder to keep behaving normally

## Actual Behavior
database deleted and folder seemingly locked up

## Context
[NOTE]: # ( Give us any additional information you may have. )

KeePassXC - Version 2.7.8
Revision: f6757d3
Distribution: Snap

Qt 5.15.11
Debugging mode is disabled.

Operating system: Ubuntu 20.04.6 LTS
CPU architecture: x86_64
Kernel: linux 5.15.0-105-generic

**Comment by droidmonkey** [comment]
> have a database, mine was in /run/user/1000/doc/8d285b01, the default location

What? That is not a default location for anything. You should store your database in your home directory. 

You essentially stored your database in a temporary folder. Nothing we can do about that unfortunately.

**Comment by bombames** [comment]
No a default location for anything? I'm confused. Every time I make a new database, it defaults to /run/user/1000/doc/[something]. 
moreover, in case I save a database anywhere in my home directory,  that database's path under "recent databases" and the path written under "Unlock KeePassXC Database" all point to that /run/user/1000/doc/[something] folder.
If it's a KeePassXC temp folder, shouldn't KeePassXC NOT point there everywhere? Is it to mask the real location of the file or something like that?

**Comment by droidmonkey** [comment]
You must have something very odd setup for your snaps. We generally don't recommend snaps for reasons like this, not a good platform. 

Did you manually find your old database? Recommend backing it up outside of the snap app.

**Comment by bombames** [comment]
I already had a copy I'm keeping up to date on my phone plus another backup on an external drive, plus I found in another arbitrary location ($HOME/snap/keepassxc/[4 numbers]) the database from the day I backed it up. Recovering the database wasn't the issue, just this weird behavior that could easily lead to someone losing their entire thing.

Would you recommend removing it from snap and build it manually?

**Comment by droidmonkey** [comment]
If you can yes, snaps are bad. Flatpak is our preferred but that had some issues lately too

**Comment by bombames** [comment]
ok, will do. Thank you very much
