### ISSUE TITLE
Browser integration: KeePassXC asks for permission unnecessarily, defeating purpose

### ISSUE THREAD

**Issue by benbucksch** [keepassxreboot/keepassxc#10698]
## Overview
When I navigate to a login page in the browser, KeePassXC does not fill out the login form, but opens a popup - in another window - asking whether access is permitted. This is unnecessary and makes the usage of the password fill practically impossible.

## Environment
* Linux, Ubuntu
* Firefox
* KeePassXC desktop + KeePassXC Firefox extension

## Steps to Reproduce
1. Import Firefox passwords in KeePassXC, including the URLs where the passwords apply.
2. Go to a login page in Firefox for which you have a password stored.
3. Firefox automatically fills out the username and password, as expected

## Actual Behavior
4. KeePassXC pops up a new dialog window, above the KeePassXC main window (in a different place), asking whether I allow accessing this password on this site (That's the bug - Problem 1)
5. I need to press Allow or Deny.
6. In the browser page, I get a banner from the KeePassXC browser extension, whether I want to store that password that Firefox filled in. That question is pointless, because KeePassXC already has that password stored (from step 1).  (Problem 2) I constantly get popups for every login page, which is completely useless and annoying.

## Expected Behavior
* KeePassXC compares the URL of the login page with the domain URL in the password database. If the login page is the same URL or a subpage of the URL in the password database, the password is filled out automatically, without any further questions asked.
* No popups, neither from the browser extension, nor from KeePassXC - if the password has been stored for this domain.

## Context
In KeePassXC desktop, Settings, Browser-Integration, there are settings. I have the default for most settings. I expect it to work with the defaults.

[x] Activate browser integration
[x] Compare URL scheme
[x]  Return only the most fitting logins
Advanced: (There is a big orange **Warning** at the top to **not** change these settings unless necessary, so I am heeding that warning by not changing them, because I am not clear on their effects.)
[ ] *Never ask before accessing login data* (*This seems to be relevant to this bug*, but it's unclear what it does. Does it disable the URL comparisons? If this fixes the bug *and* is safe to use, then it should be enabled by default.)
[ ] Never ask before updating the login data
[ ] Do not ask about HTTP Basic Auth
[x] Update native messaging manifest at startup (whatever that may be)

## Debug info
KeePassXC - Version 2.7.7
Revision: 68e2dd8
Distribution: AppImage
Qt 5.15.2

Extensions:
- Auto-Type
- Browser-Integration
- Passkeys
- SSH-Agent
- KeeShare
- YubiKey
- Secret-Service-Integration

**Comment by droidmonkey** [comment]
This is a core part of our security model. You can disable this in the application settings -> browser page. Or check the remember your choice checkbox.

**Comment by benbucksch** [comment]
Sorry, but I don't understand this response.
* If this is a core part of the security model, then I *cannot* disable it.
* If I am supposed to disable it to make the application actually usable, then the security model cannot rely on that dialog.

I've suggested how the security can be ensured without annoying the user with constant popups - by comparing the URLs. That's how Firefox does it, so it can definitely be made secure. Could you please respond to that suggestion and the concerns mentioned above?

**Comment by droidmonkey** [comment]
The security model is to keep control over credential sharing within keepassxc application unless explicitly authorized by the user. The pop up is a means to offer that control. If you don't care about that and only want to rely on url matching, then disable the setting. In other words, what you are asking for already exists as a feature.

**Comment by benbucksch** [comment]
Hi droidmonkey, I'm glad to hear that the existing pref does what is requested here. Thank you for your response.

When you say "security model", then that implies that it's inherently insecure without that check. I was trying to say that Firefox is secure, but doesn't need that manual confirmation, so either KeePassXC is lacking a security check, or the popup is simply an additional check that is *not* strictly necessary for security, but some users might prefer to have that additional control.

That's fair enough. However:
* I think that the still-secure and non-annoying model of Firefox (check URL, but don't pop up) should be the default, if usability is of any concern at all. These popups happen all the time during normal browsing and this is extremely annoying and leads to "[confirmation fatigue](https://www.pingidentity.com/en/resources/blog/post/why-security-fatigue-huge-cybersecurity-risk.html)", which is known to be actively *detrimental* to security. It's of course up you as the one of the KeePassXC maintainers to decide that. I can only give my 2 cents opinion and security expertise.
* It was *not* clear that the URL checks still happened when I enable that preference. The UI wording for the preference suggests to me that it is actively dangerous to enable. In fact, there's an explicit **Warning** above the preference. If enabling this checkbox is the fix for this problem, could you then please:
  * Move it to the normal preferences, so that it's more accessible and so that the "Warning" above does not apply to this?
  * Describe clearer what it does and which checks are still in place (URL comparison), so that the user can make an more informed decision? As it is, it's not clear at all what it does and which dangers it poses or doesn't pose.

**Comment by varjolintu** [comment]
@benbucksch We are doing URL matching with the option enabled or disabled, and it *is* necessary for security. The dialog appears after URL matching has been made. It is meant to protect users against a possible fraudulent application that has somehow got access to the keys that allows the extension to access your database. So far I haven't heard that this has happened, but it's a good practice to ask confirmation to access one or multiple credentials before the password is sent to the extension side.

As said before, you can disable this check globally, or per-entry by selecting the Remember option in the confirmation dialog.

**Comment by benbucksch** [comment]
hi @varjolintu Thanks for explaining the threat model. That wasn't clear at all before.

Personally, I am not concerned about rogue applications on the same machine, for a simple reason: Any local app can: a) read local files, including the KeePass database, b) install keyboard listeners, therefore capturing the KeePass passwords as I enter it in KeePassXC. Consequently, it's pointless to protect against local applications, on desktop OSes. This is an accepted security boundary/limitation in security circles - once the attacker runs a local executable, the game is over.

As such, I still maintain that the check is - on a purely factual basis - not worth the burden that it places on the user, and that it leads to confirmation fatigue and is therefore detrimental to security.

However, could you please at least adapt the preference wording, to clarify the threat model, as mentioned in my last comment?

**Comment by phoerious** [comment]
Sorry, but we're not going to change this. The prompt is to let you know that a website (or some other application) has requested a password. This transparency is important, but if you trust the websites, you can disable it per-entry or globally. The default is on and it will stay on.

**Comment by droidmonkey** [comment]
I don't agree with your proposed wording, but the label could be adjusted to be slightly clearer.

As a security practicioner you would also agree that even though the "game is over" you shouldn't just expose your program to the threat without any protection. Your assertions sound far more passionate and personal than based in security methods. 

I concur with dialog fatigue, but we offer  mechanisms to reduce that. I much prefer to see the access dialog because then I know when two things are true: I'm on a website that has a matching url in my database and keepassxc has detected a place to fill those credentials. I rarely ever have those two things happen on casual browsing.

**Comment by benbucksch** [comment]
> I rarely ever have those two things happen on casual browsing.

Maybe that's the difference. I have logins for many websites that I visit, but I am not always logged in. Many websites have login prompts on their home page, triggering it. That happens very often, esp. after I restarted the browser with clean cookie jars (every website where I have a login will trigger it) or when I use [cookie containers](https://addons.mozilla.org/de/firefox/addon/multi-account-containers/).

> I don't agree with your proposed wording

I haven't proposed any yet :-) I'm not able to, because I still don't understand a *realistic* scenario where enabling the preference would pose a threat. That's what I'm trying to find out. That scenario should be part of the preference wording, so that the user can make an informed decision.

**Comment by varjolintu** [comment]
You can also try disabling setting "Automatically retrieve credentials" from the extension. Then the credentials are only retrieved when you are trying to use the Username Icon or fill credentials otherwise. Maybe it could suit better to your workflow.
