### ISSUE TITLE
search field no longer selected at start-up

### ISSUE THREAD

**Issue by ajay-gh** [keepassxreboot/keepassxc#10696]
[NOTE]: # ( Give a BRIEF summary about your problem )
Until recently, in all older versions, when keepassXC was started, and as soon as the database was opened:
the search field / search term was selected and highlighted - waiting for input.
With version 2.7.7. this is no longer the case, and it sucks (forgive me !).

## Steps to Reproduce
obvious

## Expected Behavior
obvious

## Actual Behavior
the user needs several point&clicks before he can search for an entry in the database

## Context
happened at last update

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION 2.7.7.
Revision: REVISION 68e2dd8

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS

**Comment by droidmonkey** [comment]
Update to 2.7.8.....
