### ISSUE TITLE
Autotype icon is missing in 2.7.8

### ISSUE THREAD

**Issue by DutchPete** [keepassxreboot/keepassxc#10694]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
In 2.7.7 the autotype icon (the small keyboard pic) was still there.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Open KeepassXC
2. 
3. 

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
I expected the icon to still be there, it is a big time saver.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
In 2.7.8 the autotype icon (the small keyboard pic) is not there anymore. In *View* there is no option for it, and in the *Settings* there used to be a section for it, but not anymore. I cannot do any autotype anymore — bad 👎 👎

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION 2.7.8
Revision: REVISION f6757d3

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux - Ubuntu 22.04
Desktop Env: Gnome
Windowing System: Wayland

Enabled extensions:
- Auto-Type
- Browser Integration
- Passkeys
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

**Comment by phoerious** [comment]
You are using Wayland. There is no Auto-Type in Wayland (never has been). You have to switch back to X11 if you want to use Auto-Type.

**Comment by DutchPete** [comment]
I can assure you that I have been using Wayland ONLY, I don't even know how to switch to X11, and in 2.7.7 autotype WAS there.

Why is there no autotype for Wayland? Is it being worked on, or is it not possible to implement?

**Comment by phoerious** [comment]
There has never been Auto-Type on Wayland. If it worked before, then you were running KeePassXC in XWayland. That works, but you can only Auto-Type into other XWayland windows.

Wayland makes it near-impossible to implement Auto-Type at the moment.

**Comment by DutchPete** [comment]
Sorry to persist with this issue, but it is important to me.

Ubuntu 22.04 has XWayland installed natively, that is why, as per your assertion, autotype was working with KeepassXC 2.7.7 — I was using 2.7.7 with Ubuntu 22.04.

However, something HAS changed with 2.7.8 as it does not use XWayland anymore. Is this a bug?

**Comment by phoerious** [comment]
It's not up to us how you start your programs. If you want to start it as an X application, you have to set QT_QPA_PLATFORM=xcb.

**Comment by DutchPete** [comment]
OK, clear. So, if I understand you well,when X11/Xorg will be deprecated in the future (it is no longer being developed as the focus is Wayland), from then on autotype will no longer be a feature of KeepassXC.

**Comment by phoerious** [comment]
That's up to the Wayland people. If they decide to keep things as they are, then there will be no more Auto-Type on Linux. Wayland has never matured past the alpha stage in 15 years. Perhaps things will speed up now that distros start switching to it, but as of now it's incomplete at best.

**Comment by cloutierjo** [comment]
As it's impossible to comment on the original thread [here](https://github.com/keepassxreboot/keepassxc/issues/2281)

It appear that all upstream requirement have been solved since then. Furthermore, someone apparently create a third party client for bitwarden that does support autotype on wayland. So I guess this is now completely possible https://github.com/quexten/goldwarden

**Comment by droidmonkey** [comment]
Interesting, they are using libportal RemoteDesktop interface: https://flatpak.github.io/xdg-desktop-portal/docs/doc-org.freedesktop.portal.RemoteDesktop.html
