### ISSUE TITLE
Chrome blocks the download of keepassxc 2.7.8

### ISSUE THREAD

**Issue by EricPE69** [keepassxreboot/keepassxc#10691]
## Overview
Chrome prevents me to download keepassxc, 2.7.8, only with the message "This program is not frequently downloaded and may be dangerous"

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows/Linux/macOS
Desktop Env: Gnome/KDE/XFCE/Mate/Cinnamon
Windowing System: X11/Wayland

**Comment by droidmonkey** [comment]
See pinned issue
