### ISSUE TITLE
Appimage: Key exchange not successful with browser extension

### ISSUE THREAD

**Issue by mariomadproductions** [keepassxreboot/keepassxc#10693]
## Overview
With the AppImage, but not the Ubuntu PPA, the browser extension reports "key exchange not successful" when trying to connect to the AppImage KeePassXC. The KeePassXC window does try to grab attention, but upon checking it, there is no pop-up or anything.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Download and install the Ubuntu PPA, then run that install of KeePassXC, then close it
2. Download and run the AppImage
2. Try to connect the chromium extension to the AppImage KeePassXC

## Expected Behavior
It works the same as the Ubuntu PPA

## Actual Behavior
It says "key exchange not successful" and KeePassXC window tries to grab attention but doesn't display anything

## Context
Debug info from help>about:
```
KeePassXC - Version 2.7.8
Revision: f6757d3
Distribution: AppImage

Qt 5.15.2
Debugging mode is disabled.

Operating system: Linux Mint 20.3
CPU architecture: x86_64
Kernel: linux 5.4.0-177-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- Passkeys
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.19.1
```

**Comment by droidmonkey** [comment]
You need to reestablish your native messaging configurations when switching between PPA and Appimage (and vice versa).

**Comment by mariomadproductions** [comment]
> You need to reestablish your native messaging configurations when switching between PPA and Appimage (and vice versa).

Sorry for my ignorance, but how do you do that?

**Comment by droidmonkey** [comment]
https://keepassxc.org/docs/KeePassXC_UserGuide#_setup_browser_integration
