### ISSUE TITLE
Windows installation needs 24fabc in version 2.7.8

### ISSUE THREAD

**Issue by haldi4803** [keepassxreboot/keepassxc#10699]
## Overview
Installing the Windows version from your Homepages needs the "24fabc.msi" to install.
This is verifired by publisher DroidMonkey Apps LLC so that should be Safe right?

![image](https://github.com/keepassxreboot/keepassxc/assets/17104473/84347ef0-e360-4457-b02a-d5a4f170b813)

Couldn't find anything related to that in the Web.

## Steps to Reproduce
1. Download Windows Version 2.7.8 from your own Homepage.
2. https://keepassxc.org/download/#windows
3.  install, then this pops up.

**Comment by droidmonkey** [comment]
The installer name in the box is just an artifact of MSI installers. The blue box means the signing certificate is valid and trusted. That is all that matters.

**Comment by haldi4803** [comment]
Ahhh i see, this is random at every install... sorry
![image](https://github.com/keepassxreboot/keepassxc/assets/17104473/6e3f1413-4c57-4908-bc16-617a11052a66)
