### ISSUE TITLE
Right click menu may be broken sometimes 

### ISSUE THREAD

**Issue by BenK885** [keepassxreboot/keepassxc#10692]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
Importing a simple csv file does not create password entries.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Import CSV
2. Choose mapping
3. Import into existing file or new file

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
new password entries to be created

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
only an empty sub-entryfolder is created. no password entries created.
and right mouse clicks are not registered anymore until closing and opening the app again

## Context
[NOTE]: # ( Give us any additional information you may have. )
Checked with multiple csv-files from firefox password exports and even simple ones with only one entry
checked with Versions 2.7.7 and 2.7.8 on macOS Sonoma 14.3.1, Windows 11 ARM, Windows 10 64-bit. 

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.7 + 2.7.8
Revisions: 68e2dd8 (2.7.7) + f6757d3 (2.7.8)

[NOTE]: # ( Pick choices based on your environment )
Operating Systems: Windows 10 x64 + Windows 11 ARM + macOS Sonoma 14.3.1

**Comment by droidmonkey** [comment]
This isn't broken in 2.7.8, make sure you have chosen a title column. 

> and right mouse clicks are not registered anymore until closing and opening the app again

Huh?

**Comment by BenK885** [comment]
> This isn't broken in 2.7.8, make sure you have chosen a title column.

I have chosen a title column.

> > and right mouse clicks are not registered anymore until closing and opening the app again
> 
> Huh?

Yes, clicking the right mouse button inside the app on any existing item doesn't do anything after the "failed import".

I have this behaviour on three different machines, with different csv files.

**Comment by BenK885** [comment]
Ok. I now realised, only when not mapping a title field during import, no entires are created.
It seems that the title field may not stay empty.

**Comment by droidmonkey** [comment]
See #10433
