### ISSUE TITLE
Compiling OPUXReader.cpp fails w/ mz_compat.h

### ISSUE THREAD

**Issue by emrecio** [keepassxreboot/keepassxc#10707]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # Attempting to compile v2.7.8 on RockyLinux fails with one file, OPUXReader.cpp due to a call to minizip? (make -k continues to compile the rest of the project without problems).

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. mkdir build
2. cd build
3. cmake -DWITH_XC_AUTOTYPE=ON -DWITH_XC_YUBIKEY=ON -DWITH_XC_BROWSER=ON -DWITH_XC_NETWORKING=ON -DWITH_XC_SSHAGENT=ON -DWITH_XC_FDOSECRETS=ON -DWITH_XC_KEESHARE=OFF -DWITH_XC_BROWSER_PASSKEYS=ON -DWITH_CCACHE=ON ..
4. make

## Expected Behavior
[NOTE]: # compiled to completion

## Actual Behavior
[NOTE]: # See the error reported below
```
[ 13%] Building CXX object src/CMakeFiles/keepassx_core.dir/format/OPUXReader.cpp.o
/usr/local/src/keepassxc-2.7.8/src/format/OPUXReader.cpp: In function ‘QByteArray {anonymous}::extractFile(unzFile, QString)’:
/usr/local/src/keepassxc-2.7.8/src/format/OPUXReader.cpp:39:52: error: invalid conversion from ‘int’ to ‘unzFileNameComparer’ {aka ‘int (*)(void*, const char*, const char*)’} [-fpermissive]
         if (unzLocateFile(uf, filename.toLatin1(), 2) != UNZ_OK) {
                                                    ^
In file included from /usr/include/minizip/unzip.h:11,
                 from /usr/local/src/keepassxc-2.7.8/src/format/OPUXReader.cpp:33:
/usr/include/minizip/mz_compat.h:290:87: note:   initializing argument 3 of ‘int unzLocateFile(unzFile, const char*, unzFileNameComparer)’
 ZEXPORT int     unzLocateFile(unzFile file, const char *filename, unzFileNameComparer filename_compare_func);
                                                                   ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~
make[2]: *** [src/CMakeFiles/keepassx_core.dir/build.make:1100: src/CMakeFiles/keepassx_core.dir/format/OPUXReader.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:632: src/CMakeFiles/keepassx_core.dir/all] Error 2
make: *** [Makefile:146: all] Error 2
```

## Context
[NOTE]: # ( Give us any additional information you may have. )
rpm -qf /usr/include/minizip/mz_compat.h                                                                  
minizip-devel-2.8.9-2.el8.x86_64

[NOTE]: # ( Paste debug info from Help → About here )
keepassxc-2.7.8
Revision: source 

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux (Rocky Linux 8.9)
Desktop Env: KDE
Windowing System: X11

**Comment by droidmonkey** [comment]
Minizip 2.8.9 is ancient, 5 years old. You should try to use the minizip from zlib if possible or a much newer version of minizip-ng

You probably need this package instead: https://rockylinux.pkgs.org/9/rockylinux-devel-x86_64/minizip-compat-1.2.11-40.el9.x86_64.rpm.html

**Comment by emrecio** [comment]
FYI, in case it helps anyone else out there, removed the old packages, and used the following packages from zlib (as noted above) worked for me on RockyLinux 8.9 using epel repo. 
- minizip1.2.x86_64 
- minizip1.2-devel.x86_64
