### ISSUE TITLE
Clipboard clears in 1 second with 2.7.8 version from Flathub

### ISSUE THREAD

**Issue by mwshook** [keepassxreboot/keepassxc#10701]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
This is a regression when I upgraded to 2.7.8 from Flathub
When I click a toolbar button or use a keyboard shortcut to copy something, the clipboard clears in 1 second.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Hit ctrl+c (or the copy password toolbar button).
2. OR try to copy the username as above.
3. 

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
1. The password will stay in the clipboard for the number of seconds selected in Settings
2. OR the password will go to the clipboard if "Clear the clipboard after" is unchecked

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
1. The password will stay in the clipboard for 1 second. There is a 1 second progress bar in the lower right.
2.  OR the password doesn't go in the clipboard at all.

## Context
[NOTE]: # ( Give us any additional information you may have. )
I think a workaround is to close the database (and maybe restart the app). I found the value in settings had changed to 1. So I set it to 30 with the database closed. Then I opened the database and the password stayed in the clipboard for the expected 30 seconds. But expected behavior would be the ability to change this setting with the database open.

This bug doesn't seem to happen in the Appimage 2.7.8. It's possible it happened in Flatpak 2.7.7 and I didn't run into the above scenario.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.8
Revision: f6757d3
Distribution: Flatpak

Qt 5.15.10
Debugging mode is disabled.

Operating system: KDE Flatpak runtime
CPU architecture: x86_64
Kernel: linux 6.8.7-200.fc39.x86_64

Enabled extensions:
- Auto-Type
- Browser Integration
- Passkeys
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 3.3.0

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: Gnome
Windowing System: Wayland

**Comment by droidmonkey** [comment]
This was a brief issue with the flatpak release, update again
