### ISSUE TITLE
Window looks ugly after last update

### ISSUE THREAD

**Issue by mcgiany** [keepassxreboot/keepassxc#10705]
```
KeePassXC - Version 2.7.8
Revision: f6757d3
Distribution: Snap

Qt 5.15.11
Debugging mode is disabled.

Operating system: Ubuntu Core 22
CPU architecture: x86_64
Kernel: linux 6.5.0-28-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- Passkeys
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.19.1
```

![image](https://github.com/keepassxreboot/keepassxc/assets/14090031/8a58fa26-1503-4397-93b0-5645cdd9780c)

After last update window looks ugly. It doesnt match the ubuntu theme and mouse cursor is white and big.

**Comment by phoerious** [comment]
This has nothing to do with the update. That has been our default theme since version 2.6.0. You can switch back to Classic if you want. The cursor size is a problem with your Qt configuration.

**Comment by mcgiany** [comment]
Sorry, but i didn't change anything since i started using keepassxc and the behavior changed just after the update. So it cannot be problem with the Qt configuration.

**Comment by droidmonkey** [comment]
What is ugly about your screenshot?

**Comment by InterferencePattern** [comment]
The same happened to me, on Ubuntu the Automatic theme now has a title bar that doesn't match the rest of the system. Using the `View > Theme > Classic (Platform-native)` option no longer uses Dark Mode as the rest of my desktop does.

This isn't a functionality regression, but a regression nonetheless.

**Comment by droidmonkey** [comment]
We don't control the title bar color

**Comment by InterferencePattern** [comment]
@mcgiany, try installing from PPA instead of Snap. It's not mentioned on the [website](https://keepassxc.org/download/#), but apparently Snap isn't really supported by the team anymore. It's still listed as Official ("Other Official Linux Packages") but maybe they'll remove that endorsement and call it "Unofficial" or something.

**Comment by InterferencePattern** [comment]
> We don't control the title bar color

Not being an expert in GUIs, I had to do some research to understand what's going on here.

The UI for KeepassXC was built with Qt, while most Ubuntu applications use GTK+, which leads to this incongruity between KeepassXC and other applications on your system. Besides icons being different, Qt isn't using dark mode by default, even when Ubuntu's system is set to use dark mode.

https://wiki.archlinux.org/title/Uniform_look_for_Qt_and_GTK_applications

@mcgiany You'll have to theme Qt to look like Adwaita, the default GTK+ theme.
