### ISSUE TITLE
Edit autotype: APPLY always selects first entry

### ISSUE THREAD

**Issue by mdollinger** [keepassxreboot/keepassxc#10703]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Select an entry with several autotype entries
2. Modify any entry, but not the first one - eg. edit the last entry
3. Click on APPLY

## Expected Behavior

The same autotype entry is still selected

## Actual Behavior

The *first" autotype entry is selected

## Context
As a user I expect a stable UI.
When after activating a modification I always need to select the desired autotype entry again, this is unstable and annoying.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.7
Revision: 68e2dd8

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 10 Enterprise Build 19045.4291
Windowing System: X11/Wayland

**Comment by droidmonkey** [comment]
Update to 2.7.8, I cannot replicate this.


https://github.com/keepassxreboot/keepassxc/assets/2809491/e10b8804-5cfd-4529-a2dc-610ae84281cf

**Comment by mdollinger** [comment]
I can replicate this.Unfortunately I cannot make a screenshot, because the window is hidden as soon I open my screenshot tool. Is there a setting to keep it visible?

Yahoo Mail: Suchen, organisieren, erobern 
 
  Am Mi., Mai 8, 2024 at 13:27 schrieb Jonathan ***@***.***>:   


Update to 2.7.8, I cannot replicate this.

https://github.com/keepassxreboot/keepassxc/assets/2809491/e10b8804-5cfd-4529-a2dc-610ae84281cf

**Comment by droidmonkey** [comment]
View -> Allow Screencapture

Are you updated to 2.7.8?
