### ISSUE TITLE
Usb remove requested on launch (v2.7.7)

### ISSUE THREAD

**Issue by redy01** [keepassxreboot/keepassxc#10710]
## Overview
Since version 2.7.7 there is some issue during application start - regarding yubikey
I've got a rule attached to Yubikey running "lock screen" when my the device is disconnected from PC and this rule is triggered when I start the app or if I click refresh hw_key button during unlock database screen.
Anyway my Yubikey is not recognized by the app.

## Steps to Reproduce
1. Run application
or
1. Click to refresh hardware keys

## Expected Behavior
Will not behave like usb was pulled from port

## Actual Behavior
Application behave like Yubikey was removed from port what trigger other action depended on key status

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.7
Revision: 

LOG when action triggered:
```
systemd-udevd[214994]: No events are queued, removing /run/udev/queue.
systemd-udevd[214994]: event11: Device is queued (SEQNUM=11416, ACTION=remove)
systemd-udevd[214994]: event11: Device ready for processing (SEQNUM=11416, ACTION=remove)
systemd-udevd[214994]: event11: sd-device-monitor(manager): Passed 282 byte to netlink monitor.
(udev-worker)[348098]: event11: Processing device (SEQNUM=11416, ACTION=remove)
(udev-worker)[348098]: event11: Removing watch handle -1.
(udev-worker)[348098]: event11: /etc/udev/rules.d/90-yubikey-screen-lock.rules:1 RUN '/usr/local/bin/yubilock'
(udev-worker)[348098]: event11: No reference left for '/dev/input/by-id/usb-Yubico_YubiKey_OTP+FIDO+CCID-event-kbd', removing
(udev-worker)[348098]: event11: No reference left for '/dev/input/by-path/pci-0000:00:14.0-usb-0:7:1.0-event-kbd', removing
(udev-worker)[348098]: event11: No reference left for '/dev/input/by-path/pci-0000:00:14.0-usbv2-0:7:1.0-event-kbd', removing
(udev-worker)[348098]: event11: Running command "/usr/local/bin/yubilock"
(udev-worker)[348098]: event11: Starting '/usr/local/bin/yubilock'
(udev-worker)[348098]: Successfully forked off '(spawn)' as PID 348100.
```
from dmesg there is only input action
```
input: Yubico YubiKey OTP+FIDO+CCID as /devices/pci0000:00/0000:00:14.0/usb3/3-7/3-7:1.0/0003:1050:0407.0066/input/input98
hid-generic 0003:1050:0407.0066: input,hidraw4: USB HID v1.10 Keyboard [Yubico YubiKey OTP+FIDO+CCID] on usb-0000:00:14.0-7/input0
```

rule 90-yubikey-screen-lock.rules
`ACTION=="remove", ENV{ID_VENDOR_ID}=="1050", ENV{ID_MODEL_ID}="0407", RUN+="/usr/local/bin/yubilock"`

## System
Operating System: Linux
Desktop Env: Gnome
Windowing System: Wayland

KeePassXC - Version 2.7.7
Revision: 68e2dd8

Qt 5.15.13
Debugging mode is disabled.

Operating system: Fedora Linux 40 (Workstation Edition)
CPU architecture: x86_64
Kernel: linux 6.8.8-300.fc40.x86_64

Enabled extensions:
- Auto-Type
- Browser Integration
- Passkeys
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.19.3

**Comment by phoerious** [comment]
See #10077.
