### ISSUE TITLE
Passkeys: Remove passkey from entry

### ISSUE THREAD

**Issue by darkdragon-001** [keepassxreboot/keepassxc#10715]
## Overview
There should be an option to remove a passkey from an entry but keep the entry with the remaining attributes.

## Steps to Reproduce
1. Register passkey to existing entry
2. Right click on the entry and look for an option to remove the passkey again

## Expected Behavior
There should be an option to remove the passkey from the selected entry.

## Actual Behavior
I couldn't find an option to remove the passkey from the selected entry.

## Context
KeePassXC - Version 2.7.8
Revision: f6757d3
Distribution: Flatpak

Operating System: Linux
Desktop Env: Gnome
Windowing System: Wayland

**Comment by droidmonkey** [comment]
Good idea, but you can achieve that by editing the entry, go to advanced tab, and delete all passkey attributes.

**Comment by darkdragon-001** [comment]
@droidmonkey I don't see any additional entriea in the advanced tab. Only an added tag "Passkey" but nothing else changed after adding the passkey. It works for authentication though, so it must be stored somewhere.

**Comment by droidmonkey** [comment]
You'll only see them when editing an entry

**Comment by itsvrl** [comment]
This is a great feature request!

**Comment by darkdragon-001** [comment]
> You'll only see them when editing an entry

This works, thanks for the workaround.

**Comment by darkdragon-001** [comment]
Would still be great to have a right-click context menu like for TOTP for passkeys (delete, export, import, ...).

**Comment by itsvrl** [comment]
Totally agree here!
