### ISSUE TITLE
Keepassxc segfaults randomly after running for a while in Gnome/Arch

### ISSUE THREAD

**Issue by kareliot** [keepassxreboot/keepassxc#10711]
## Overview
Keepassxc segfaults (seemingly randomly and without apparent cause) after running successfully for a while.
I start keepass when I need it for the first time after booting and then let it run in the background. After a while, when I want to access it again via the firefox-plugin, I see that it is no longer running. The log shows segfault messages.

`Mai 07 11:48:38 philap systemd[1885]: app-gnome-org.keepassxc.KeePassXC-17297.scope: Consumed 1.634s CPU time.
Mai 07 13:48:11 philap kernel: keepassxc[23884]: segfault at 2 ip 00005ceac25d1007 sp 00007ffcab869160 error 4 in keepassxc[5ceac24e7000+2f9000] likely on CPU 15 (core 7, socket 0)
Mai 07 13:58:02 philap kernel: keepassxc[24645]: segfault at 2 ip 000064f311ab5007 sp 00007ffc52db2b00 error 4 in keepassxc[64f3119cb000+2f9000] likely on CPU 11 (core 5, socket 0)
Mai 07 13:58:02 philap systemd[1885]: app-gnome-org.keepassxc.KeePassXC-24645.scope: Consumed 1.062s CPU time.
Mai 07 19:42:26 philap kernel: keepassxc[38278]: segfault at 2 ip 00005d805d02d007 sp 00007ffce6c41a30 error 4 in keepassxc[5d805cf43000+2f9000] likely on CPU 0 (core 0, socket 0)
Mai 07 19:42:26 philap systemd[1885]: app-gnome-org.keepassxc.KeePassXC-38278.scope: Consumed 1.653s CPU time.
Mai 08 10:39:22 philap kernel: keepassxc[46305]: segfault at c1 ip 00006190acbb4007 sp 00007fff441e1a60 error 4 in keepassxc[6190acaca000+2f9000] likely on CPU 1 (core 0, socket 0)
`

## Steps to Reproduce
1.  start keepassxc and use it normally
2.  let it run in the background
3. at some point it segfaults (usually after a several minutes or even hours after last using it)

## Expected Behavior
keep running in the background

## Actual Behavior
segfaulting

## Context
it is a relative fresh install of arch and the problem seems to have been there from the beginning

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.7
Revision: 68e2dd8

Qt 5.15.13
Diagnosemodus ist deaktiviert.

Betriebssystem: Arch Linux
CPU-Architektur: x86_64
Kernel: linux 6.8.9-arch1-1

Aktivierte Erweiterungen:
- Auto-Type
- Browser-Integration
- Passkeys
- SSH-Agent
- KeeShare
- YubiKey
- Secret-Service-Integration

Kryptographische Bibliotheken:
- Botan 3.4.0

[NOTE]: # ( Pick choices based on your environment )
Operating System:  Arch Linux
Desktop Env: Gnome
Windowing System: Wayland

**Comment by phoerious** [comment]
Upgrade to 2.7.8.

**Comment by Janhouse** [comment]
Still randomly segfaults in version 2.11.x
