### ISSUE TITLE
KeePassXC hangs when key file not present.

### ISSUE THREAD

**Issue by faxotherapy** [keepassxreboot/keepassxc#10728]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

KP hangs when key file is not present at KeePassXC launch.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Use KP with key file enabled.
2. Quit KP and make key file unavailable.
3. Launch KP (KP will hangs until key file is present)

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

KP loads normally even though no key file.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

I thought KP will stop looking for the key file after a few secs. If key file not present, why persisting hanging.
In fact, this bug has been present since long ago, rolling onto any further KP release.

## Context
[NOTE]: # ( Give us any additional information you may have. )
Key File is hosted on the network.
MacOS 12.7.1 (Monterey)

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.7
Revision: Revision: 68e2dd8

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS
Desktop Env:
Windowing System:

**Comment by droidmonkey** [comment]
Update to 2.7.8
