### ISSUE TITLE
Adjustable font size in Preview Pane in Windows version

### ISSUE THREAD

**Issue by blakestoneZZX** [keepassxreboot/keepassxc#10729]
## Summary
Is there a way to adjust the font size in the Preview Pane of the Windows version of KeePassXC? I'd like to do this without modifying my system's fonts in any way. A setting in the "Settings" would work just fine.

## Context
Font is currently too small on large monitors

**Comment by droidmonkey** [comment]
Not yet, but this is already tracked by an open request.
