### ISSUE TITLE
"Weak password" warning incorrectly shown after adding (or removing) a key file from database

### ISSUE THREAD

**Issue by ghost** [keepassxreboot/keepassxc#10723]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
I set up a new database file for testing purposes initially without using a key file. My master password was generated with KeePassXC using 10 random words from the default word list to ensure very strong entropy. Later I decide to create and add a key file to the database, and when I went to save changes and click "OK" at the bottom I get an incorrect prompt saying my master password is too weak, which I know is false.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. From menu at the top of the application: go to Database > Database Security
2. Add a key file if one does not already exist and save changes, Removing a key file and saving changes also triggers this bug.

Additional information that may help in reproducing:
- Encryption Algorithm was set to ChaCha20 during database creation phase, all other settings were left at default values.
- Master password was generated from within KeePassXC's default word list, the master password only contains words, no symbols (besides spaces separating the words), no numbers. 10 words in length.
- The key file was generated using KeePassXC.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
If the master password is known to be -without a doubt- very strong then there is not supposed to be a "weak password" prompt when saving changes after adding or removing a key file from the database.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
After adding or removing a key file from the database and saving changes, a prompt incorrectly shows up saying my password is weak.

## Context
[NOTE]: # ( Give us any additional information you may have. )
![KeePassXC_OqnP0GPcif](https://github.com/keepassxreboot/keepassxc/assets/153876500/74f6bdc3-760b-4981-96ad-f32c868b5928)

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.8
Revision: f6757d3

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 11 Home - (23H2, OS Build 22631.3527)

**Comment by 0xdeadbeer** [comment]
A few of my additional findings: 
 - it does not matter what encryption algorithm you used 
 - nor what kind of password you have, whether you generated it or not 

I suspect that it comes down to this: https://github.com/keepassxreboot/keepassxc/blob/da90319d2d04e5226d2363454c80a3c6cfe132e2/src/gui/dbsettings/DatabaseSettingsWidgetDatabaseKey.cpp#L181-L205

To my surprise, `m_passwordEditWidget->isEmpty()` does not return `true` if the user hasn't clicked on "Change Password" button in the Database Security Settings.. an additional check with `m_passwordEditWidget->visiblePage() == KeyComponentWidget::Page::Edit` is I hope enough to safe-guard it..? Like so: 
```diff
diff --git a/src/gui/dbsettings/DatabaseSettingsWidgetDatabaseKey.cpp b/src/gui/dbsettings/DatabaseSettingsWidgetDatabaseKey.cpp
index 1de8e6a9..0c26bccb 100644
--- a/src/gui/dbsettings/DatabaseSettingsWidgetDatabaseKey.cpp
+++ b/src/gui/dbsettings/DatabaseSettingsWidgetDatabaseKey.cpp
@@ -178,7 +178,8 @@ bool DatabaseSettingsWidgetDatabaseKey::save()
     }
 
     // Show warning if database password is weak
-    if (!m_passwordEditWidget->isEmpty()
+    bool isNewPasswordDirty = !m_passwordEditWidget->isEmpty() && m_passwordEditWidget->visiblePage() == KeyComponentWidget::Page::Edit;
+    if (isNewPasswordDirty
         && m_passwordEditWidget->getPasswordQuality() < PasswordHealth::Quality::Good) {
         auto dialogResult = MessageBox::warning(this,
                                                 tr("Weak password"),
@@ -195,7 +196,7 @@ bool DatabaseSettingsWidgetDatabaseKey::save()
     // If enforced in the config file, deny users from continuing with a weak password
     auto minQuality =
         static_cast<PasswordHealth::Quality>(config()->get(Config::Security_DatabasePasswordMinimumQuality).toInt());
-    if (!m_passwordEditWidget->isEmpty() && m_passwordEditWidget->getPasswordQuality() < minQuality) {
+    if (isNewPasswordDirty && m_passwordEditWidget->getPasswordQuality() < minQuality) {
         MessageBox::critical(this,
                              tr("Weak password"),
                              tr("You must enter a stronger password to protect your database."),
```

**Comment by droidmonkey** [comment]
That code won't compile. simply call isVisible() on the password widget.

**Comment by 0xdeadbeer** [comment]
Strange, it compiles on my machine..? Anyhow, after some checking to me it seems that calling `m_passwordEditWidget->isVisible()` at that point in time returns `true` even if the user does not click on "Change Password"..? Even weirder is the fact that the visible property seems to be false at that point when inspected through Gamma Ray.. `->isVisible()` still returns `true` though.. will look further into the source code the coming days
