### ISSUE TITLE
please add voidlinux on the list

### ISSUE THREAD

**Issue by icf20** [keepassxreboot/keepassxc#1073]
`sudo xbps-install keepasscx`

here is the template 
https://github.com/voidlinux/void-packages/blob/master/srcpkgs/keepassxc/template

**Comment by droidmonkey** [comment]
Please provide more info on your original post or i will close this issue.

**Comment by phoerious** [comment]
I assume this is targeted at our website.

**Comment by icf20** [comment]
@droidmonkey 
here
![image](https://user-images.githubusercontent.com/17784575/31590168-0c1a6360-b20c-11e7-9a69-6227a6b028dd.png)

**Comment by droidmonkey** [comment]
thanks for expanding on your request

**Comment by phoerious** [comment]
The Screenshot has weird broken fonts. I wonder what browser that might be. 🤔

**Comment by icf20** [comment]
@phoerious firefox, simply font awesome and font-linux are remote fonts so they are blocked and system fonts are used

**Comment by phoerious** [comment]
Web fonts: yes, remote web fonts: no. They are located on our own server.
