### ISSUE TITLE
Signing issue via homebrew

### ISSUE THREAD

**Issue by Anhsirkz** [keepassxreboot/keepassxc#10737]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
KeePassXC cannot be launched because the binary seems not to be signed.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )

1. Install brew cask via 
''brew install --cask keepassxc''

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
KeepassXC should launch normally as expected

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Xprotect UI agent claims the following:
"KeePassXC.app" can't be opened because Apple cannot check it for malicious software. This software needs to be updated. Contact the developer for more information.

## Context
[NOTE]: # ( Give us any additional information you may have. )
There seems to be a signing issue around MacOS for the KeePassXC binary. MacOS Sonoma.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - KeePassXC-2.7.8-arm64.dmg
Revision: 

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS, Sonoma
Desktop Env: -
Windowing System: -

**Comment by phoerious** [comment]
The binary we ship is absolutely signed. You can check via `codesign -vv /Applications/KeePassXC.app`
