### ISSUE TITLE
Password is not copied when other text is selected in KeePassXC

### ISSUE THREAD

**Issue by Natan-Gorecki** [keepassxreboot/keepassxc#10734]
## Overview
![image](https://github.com/keepassxreboot/keepassxc/assets/52935895/c387ae4a-cc2b-46a3-ac0f-5a9c465fda3c)
Looks like with selected text "Copy username" and "Copy URL" buttons works correctly, but not "Copy password" button.

## Steps to Reproduce
For the attached screenshot:
1. Select _Description_ from **Notes**.
2. Click "Copy password" button.

## Expected Behavior
The password value is copied (here "Password").

## Actual Behavior
The selected text is copied (here "Description").

## Context
```
KeePassXC - Version 2.7.8
Revision: f6757d3

Qt 5.15.11
Debugging mode is disabled.

Operating system: Windows 10 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.19045

Enabled extensions:
- Auto-Type
- Browser Integration
- Passkeys
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 3.1.1
```

**Comment by tatarmb4s** [comment]
I have the same issue, I can not copy any kind of passwords from Keepass since yesturday. I have even updated to the latest version. I can not even copy the debug info, none of the copy methods works in the app. I can only use the auto typer.

### App version
```
KeePassXC - Version 2.7.8
Revision: f6757d3

Qt 5.15.11
Debugging mode is disabled.

Operating system: Windows 11 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.19045

Enabled extensions:
- Auto-Type
- Browser Integration
- Passkeys
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 3.1.1
 ```

**Comment by tatarmb4s** [comment]
Update: Tested Version 2.7.7 on the same system using the same extensions, and still no copy. The 2.7.6 works.

**Comment by iodar** [comment]
# Summary

Same here on linux as well. It seems to be a cross platform issue.

## Debug Information

```
KeePassXC - Version 2.7.8
Revision: f6757d3
Distribution: Flatpak

Qt 5.15.10
Debugging mode is disabled.

Operating system: KDE Flatpak runtime
CPU architecture: x86_64
Kernel: linux 6.1.0-21-amd64

Enabled extensions:
- Auto-Type
- Browser Integration
- Passkeys
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 3.3.0
```

## System Information

```
OS: Debian GNU/Linux 12 (bookworm) x86_64 
Host: ThinkPad 
Kernel: 6.1.0-21-amd64 
Shell: bash 5.2.15 
Resolution: 1920x1080 
DE: Plasma 5.27.5 
WM: kwin 
CPU: Intel i5-8365U (8) @ 4.100GHz 
GPU: Intel WhiskeyLake-U GT2 [UHD Graphics 620] 
Memory: 4490MiB / 39736MiB 
```

## Workaround

* Install version `2.7.4` from PPA repository using `apt-get`
