### ISSUE TITLE
Add tool for find similar and duplicated passwords

### ISSUE THREAD

**Issue by djhtml** [keepassxreboot/keepassxc#10733]
## Summary
Please add a tool, that can find:
 - Similar passwords (clusters).
 - Duplicated passwords.
 - Can list all passwords sorted by quality (bits, instead of 3 colours).

## Examples
Original KeePass have these tools. (Find / Duplicate passwords, etc.)

## Context
Handy tool(s) to progress password quality.

**Comment by droidmonkey** [comment]
Look at Database -> Database Reports. Everything except is there. You can show all 4 levels of password quality in the main entry view. Showing raw entropy bits is not useful. 

There are a couple of other issues asking for improvements to these tools, so I consider this a duplicate.

**Comment by djhtml** [comment]
Thank you Jonathan, I missed that menu.
