### ISSUE TITLE
Return entry sorting + add KeePass drag+drop entries in window to sort

### ISSUE THREAD

**Issue by SdoggaMan** [keepassxreboot/keepassxc#10744]
## Summary
In 2.7.7 and prior, you could sort entries in folders by holding down CTRL + ALT and using the arrow keys (this is already worse than just one key in KeePass, but so be it if it's necessary)
I'd like to see this return to 2.7.8 as CTRL+ALT and CTRL+SHIFT now only shift the keyboard cursor. SHIFT+ALT select in that direction. 

Additionally I'd like to be able to drag to rearrange entries in the list, just like you can do with folders. 

Entries also now auto-shift to the bottom of an unsorted list when edited, whereas I would similarly like them to remain in their position in the list. 

## Examples
2.7.7 & prior, and KeePass - you can arrange your entries as you like via keyboard (both) and mouse (KeePass)
2.7.8 - you can only select entries. 

## Context
Using the keyboard is strenuous as you can only adjust one entry at a time, one space at a time. You also cannot select multiple entries, then shift those - so those who like their entries in a static list, unsorted by a column, struggle a bit to do so. Being able to easily drag + drop, AND keyboard adjust, brings much greater user customisation and findability, and helps with list-style folders or users accessing entries by rote (for example, knowing exactly where to go in the list to get Contoso.com's Microsoft login.

**Comment by droidmonkey** [comment]
You have the listed sorted by modified time. Click the header until the sort arrow disappears. Drag sorting want enabled due to various qt issues we ran into, unfortunately. 

If you select multiple entries you can move them all up and down at the same time using the keyboard shortcuts.

**Comment by SdoggaMan** [comment]
Then that's a behaviour that's changed since 2.7.7 because it's not something I adjusted myself. 

I'd still much prefer mouse movement, keyboard adjusting is tedious and adjusting multiple, separate, entries into different locations can take minutes, not seconds, and is far easier to screw up.

**Comment by droidmonkey** [comment]
Nothing changed in this regard between 2.7.7 and 2.7.8.

**Comment by SdoggaMan** [comment]
It wouldn't be the first time an update to KPXC has altered the current setup; for example every update resets the layout for me back to 'attachments / TOTP / title / username / URL / Notes' where I have it as 'title / username / password / URL / notes'. 

Anyway regardless, aware of personal preference, but I do feel greater sorting usability would save a lot of time and headache. I believe KP2 has the ability to drag sort so would like that here. Cheers!

**Comment by droidmonkey** [comment]
Do you have your ~/.cache mounted to RAM? Sounds like your settings are being reset which definitely doesn't happen just because of an update.

**Comment by SdoggaMan** [comment]
My KPXC is set up however it comes OOB, aside from general settings in the program - definitely nothing that shifts around page files or cache location. About the only thing different is that I think I installed KPXC via winget. 

it's also worth remembering that newer DRAM-less systems running recent 13/14th Gen stuff has dynamic memory, which could shift cache locations around between memory and RAM - it's a feature designed to bypass the need for a DRAM cache on the SSD, yes, but could possibly have an effect here. Probably not, but just spitballing - could be relevant. As I said though aside from that, stock standard. I don't even have any plugins, just the Firefox browser extension. 

My DBs are in OneDrive - but that's not likely to affect the _program's_ caching, only the file itself, right?

**Comment by droidmonkey** [comment]
I assumed you were on Linux. On windows those settings are stored in %APPDATALOCAL%/KeePassXC/

**Comment by SdoggaMan** [comment]
Haven't touched them, and everything in there looks nominal.
