### ISSUE TITLE
KeePassXC 2.7.8 does not open images

### ISSUE THREAD

**Issue by nlime** [keepassxreboot/keepassxc#10741]
## 
Does not open images jpg

## Expected Behavior

version 2.7.1 opens

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.8

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux Mint
Desktop Env: XFCE4
Windowing System: X11

**Comment by droidmonkey** [comment]
You need to define the default handler for jpg images with your desktop environment.
