### ISSUE TITLE
Smaller font for passwords on macOS

### ISSUE THREAD

**Issue by MrChocolatine** [keepassxreboot/keepassxc#10740]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

When generating a password, when creating a new entry or when using directly the Password Generator, the font of the passwords being generated is smaller than before. It is less readable.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Create a new entry
1. In the Password field, click the icon "Password Generator"
1. Show the password randomly generated
1. Font is smaller than before

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

Font has the same size as before, which would be more readable.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

Font is smaller than before, which is less readable.

## Context
[NOTE]: # ( Give us any additional information you may have. )

I updated KeePassXC to v2.7.8 the 9 May 2024.
Before that date I was on v2.7.7 and the font was perfect.

**Comment by droidmonkey** [comment]
Absolutely no changes to font sizing were made between 2.7.7 and 2.7.8. Either way, we don't have different font sizes between elements, so this is actually impossible. There is no code that exists that causes the font to be sized differently. Sorry, but I can't assist further without a screenshot demonstrating what you see.

**Comment by droidmonkey** [comment]
This is a duplicate, #10739

**Comment by MrChocolatine** [comment]
> This is a duplicate, #10739

I could not find it when I searched for a similar ticket.

**Comment by droidmonkey** [comment]
Just got opened, you didn't miss it 😄

Actually I'll link this report to that PR
