### ISSUE TITLE
Custom icon delete

### ISSUE THREAD

**Issue by carlkapo** [keepassxreboot/keepassxc#10749]
## Overview
KepassXC
Cannot locate how to delete a custom icon [added in error or no longer used}

## Steps to Reproduce
simply goto any edit or add process  that calls the icon window.

## Expected Behavior
the icon will be deleted

## Actual Behavior
nothing - when delete key pressed

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 278
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows
Desktop 
Windowing System: X10

**Comment by droidmonkey** [comment]
Hi, this is covered in our user guide: https://keepassxc.org/docs/KeePassXC_UserGuide#_database_maintenance
