### ISSUE TITLE
KeePassXC is invisible when using DisplayLink Manager

### ISSUE THREAD

**Issue by darkodidak1** [keepassxreboot/keepassxc#10753]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. macOS Sonoma 14.5
2. DisplayLink Manager 1.10.1
3. KeePassXC is invisible

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
I expect to see KeePassXC, everything else is visible, only KeePass XC is not working

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
KeePassXC is invisible, it's clickable, but it's not visible (GUI)

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.8

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS Sonoma 14.5

**Comment by droidmonkey** [comment]
https://keepassxc.org/docs/KeePassXC_UserGuide#_screenshot_security

**Comment by MTWTF24** [comment]
@droidmonkey   Why did this behavior appear only after updating to Sonoma 14.5? It was working out-of-the-box with 14.4.

**Comment by darkodidak1** [comment]
@MTWTF24 true!

**Comment by phoerious** [comment]
Must be something that changed in macOS or DisplayLink.

**Comment by droidmonkey** [comment]
I dunno, ask apple. We just tell them to hide our window from other applications
