### ISSUE TITLE
Invalid inner-header-id size on Linux Mint and NC-WebDAV

### ISSUE THREAD

**Issue by thekk1** [keepassxreboot/keepassxc#10751]
## Overview
[NOTE]: Opening a Database with Linux Mint and WebDAV mount (davs://) on Nextcloud it's currently impossible.
First time happened weeks ago and had no time to review so the exact versions of all involved software is unknown.
It has worked the last about 2 years without any issue. Opening the database from local file system works properly.

## Steps to Reproduce
[NOTE]: 
1. Mount a Nextcloud Share with davs:// protocol in Linux Mint Nemo file browser.
2. Try to open and unlock the database from the mount.
3. Get the error message.

## Expected Behavior
[NOTE]: The database just should open properly.

## Actual Behavior
[NOTE]: 
Got the error message :"Invalid inner-header-id size."
![image](https://github.com/keepassxreboot/keepassxc/assets/16156402/5895ac9f-d73a-417d-9eab-3603cd04b49c)

## Context
[NOTE]: See Overview

[NOTE]: # ( Paste debug info from Help → About here )
![image](https://github.com/keepassxreboot/keepassxc/assets/16156402/434fee96-0b6c-466b-80e6-73c9258aba30)

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux Mint 21.3 (first time happened on 21.2)
Desktop Env: Cinnamon
Windowing System: X11

**Comment by droidmonkey** [comment]
Means your database file itself is corrupt or the download is not completing successfully. Not a keepassxc issue though.

**Comment by thekk1** [comment]
> Means your database file itself is corrupt or the download is not completing successfully. Not a keepassxc issue though.

As I said: 
> Opening the database from local file system works properly

This mean, it is exactly the database that does not work over dav. It is downloaded over the mounted share where KeePassXC does not work. Creating new databases for testing show exactly the same issue.
But sure, it's not a KeePassXC issue...
Good job, detective.

**Comment by droidmonkey** [comment]
Uh yah it's not our issue, it's your DAV

**Comment by thekk1** [comment]
> Uh yah it's not our issue, it's your DAV

Sure. Valid argument, nothing to add.

**Comment by urzparat** [comment]
> Uh yah it's not our issue, it's your DAV

@droidmonkey Well I have the exact same issue but only with a database which is also secured by a hardware key. Could you give me advice how one could debug this problem? I mean when I generate a checksum of the webdav file its the same as if I test the file after a download. So I assume there is something funky happening in the file handler of KeePassXC.

@thekk1 I think this has something to do with the latest apache2 update: https://metadata.ftp-master.debian.org/changelogs//main/a/apache2/apache2_2.4.59-1~deb12u1_changelog
I have the problem exactly since April 18, the day after the mentioned update was installed on the NextCloud server (it was released on April 16 see https://tracker.debian.org/pkg/apache2). Can you confirm this?

**Comment by thekk1** [comment]
> > Uh yah it's not our issue, it's your DAV
> 
> @thekk1 I think this has something to do with the latest apache2 update: https://metadata.ftp-master.debian.org/changelogs//main/a/apache2/apache2_2.4.59-1~deb12u1_changelog I have the problem exactly since April 18, the day after the mentioned update was installed on the NextCloud server (it was released on April 16 see https://tracker.debian.org/pkg/apache2). Can you confirm this?

I can confirm that we have the same apache version in use but after downgrading to 2.4.57-2 the problem remains.

**Comment by urzparat** [comment]
That's interesting. Unfortunately I can't downgrade to confirm this. I assume you don't got any more clues about whats failing?
