### ISSUE TITLE
MacOS Sonoma 14.5: KeepassXC window invisible when using DisplayLink

### ISSUE THREAD

**Issue by fbaquero** [keepassxreboot/keepassxc#10757]
# Issue Description
After updating to MacOS Sonoma 14.5, KeepassXC no longer functions properly. When attempting to open the application, the database unlock window fails to display, and the application appears to freeze, leaving the user unable to interact with it.

## Steps to Reproduce the Issue
1 Update the operating system to MacOS Sonoma 14.5.
2 Attempt to open KeepassXC.
3 Notice that the database unlock window fails to display, and the application appears to freeze.

## Expected Behavior
After updating to MacOS Sonoma 14.5, KeepassXC is expected to function properly, including the ability to display the database unlock window and allow the user to interact with the application smoothly.

## Current Behavior
After the update, KeepassXC does not display the database unlock window and appears to freeze, preventing effective user interaction with the application.

## System Configuration
Operating System: MacOS Sonoma 14.5
KeepassXC Version: 2.7.8

## Steps Taken to Resolve the Issue
Restarting the application.
Restarting the operating system.
Reinstalling KeepassXC.

## Additional Details
This issue occurred after updating to MacOS Sonoma 14.5. Prior to this update, KeepassXC was functioning correctly.

**Comment by configdump** [comment]
Facing same problem when external displays connected with Display link manager after mac upgrade to the above version(Mac: 14.5, Keepassxc: 2.7.8). 
When external displays are not connected, works as expected. Looks like QT compatibility issues.

**Comment by phoerious** [comment]
Something changed in the way DisplayLink works in Sonoma. You have to disable screenshot protection or move the window to a native display in order to see it. https://keepassxc.org/docs/KeePassXC_UserGuide#_screenshot_security

**Comment by varjolintu** [comment]
Mac Mini with a single external display doesn't have this issue.

**Comment by phoerious** [comment]
I suppose DisplayLink now counts as a screen recording or something. You don't need it for running a single display, obviously, unless you are connecting to a cheap dock.

**Comment by fbaquero** [comment]
Ok. Thanks. I confirm that the problem appears only when any extra monitor is connected.

A temporary solution may be to create a startup script (in case, like me, you had it configured to start automatically at boot):

### Step-by-Step Guide to Create and Configure the Script

1. **Open AppleScript Editor:**
   - Open the `Script Editor` application on your Mac (you can find it via Spotlight).

2. **Write the Script:**
   - Write the following script in the editor:
     ```applescript
     do shell script "/Applications/KeePassXC.app/Contents/MacOS/KeePassXC --allow-screencapture &>/dev/null &"
     ```
   - The `&>/dev/null &` at the end ensures that any output generated by the command is redirected to `/dev/null` (i.e., discarded) and that the command runs in the background, allowing the AppleScript to close immediately after starting KeePassXC.

3. **Save the Script as an Application:**
   - Save the script by selecting `File` -> `Export`.
   - In `File Format`, select `Application`.
   - Give it a name (e.g., `Start KeePassXC`) and save it in a convenient location, such as your `Applications` folder.

4. **Set the Script to Start Automatically:**
   - Open `System Preferences` -> `Users & Groups`.
   - Select your user and then click on the `Login Items` tab.
   - Add the application you just created (`Start KeePassXC`) to the list of startup items.

5. **Disable the Automatic Startup Option in KeePassXC:**
   - Open KeePassXC the usual way (without the script) to access the preferences.
   - Go to the `KeePassXC` menu in the top menu bar and select `Preferences`.
   - In the preferences, find and uncheck the option `Start at login` or `Launch KeePassXC at system startup`.
   - Save the changes.

### Process Summary

1. Create the script in AppleScript and save it as an application.
2. Set the script to run automatically at login.
3. Disable the automatic startup option in KeePassXC’s preferences.

By following these steps, KeePassXC will start with the `--allow-screencapture` flag when you log in, and the AppleScript will close automatically after launching KeePassXC.

**Comment by droidmonkey** [comment]
Everyone needs to file a bug with Apple because this is abnormal behavior.

**Comment by CDSeal** [comment]
Updating to DisplayLink Manager v1.10.2 (Build 14) helped here.

**Comment by 06Bine09** [comment]
I found a workaround for this issue - when you open KeePassXC you see an empty menu bar on top. You can click on the menu bar items even if they are invisible. When you click on the menu bar items the menu item list unfolds which you should be able to see. You can then navigate to the "View" menu bar item and click on "enable screen capture" in the menu item list of the "View" menu bar item. This is something I need to do after every restart of my mac but it works.

**Comment by askrix** [comment]
> Updating to DisplayLink Manager v1.10.2 (Build 14) helped here.

I confirm! This solution worked for me as well! Thanks for sharing ❤️

**Comment by 3nt3** [comment]
> I found a workaround for this issue - when you open KeePassXC you see an empty menu bar on top. You can click on the menu bar items even if they are invisible. When you click on the menu bar items the menu item list unfolds which you should be able to see. You can then navigate to the "View" menu bar item and click on "enable screen capture" in the menu item list of the "View" menu bar item. This is something I need to do after every restart of my mac but it works.

lmao

**Comment by gw3437** [comment]
> I suppose DisplayLink now counts as a screen recording or something. You don't need it for running a single display, obviously, unless you are connecting to a cheap dock.

Displaylink counts as screensharing. Microsoft has been able to block "protected" information (like encrypted emails and data marked for internal use only) from screenshots and screenshares - I suspected Apple did something similar wtih their latest update.  

FYI, Macbook Airs (m2 at least) don't support 2 external monitors and the only solution is a displaylink dock.

**Comment by phoerious** [comment]
M2 does support two external displays. It's only the first-generation M1 and the 13" M2 MacBook that need DisplayPort.

**Comment by gw3437** [comment]
> M2 does support two external displays. It's only the first-generation M1 and the 13" M2 MacBook that need DisplayPort.

I'm on an M2 Air, didn't have that experience. (This was the whole reason why I got a Displaylink dock, to workaround this limitation.) 

Do you have a source?
MacWorld seems to agree with me:

While the M1 and M2 MacBooks natively support just one monitor, the M1 and M2 Mac Mini does natively support up to two external monitors—one via the HDMI port and a second via USB-C. But the M1 and M2 models of the MacBook Air and MacBook Pro (plus the M3 MacBook Pro) support only a single external display over Thunderbolt.

The latest M3 MacBook Air models (13- and 15-inch) are the first to support more than one external display—as long as you close the laptop’s lid to allow for the second external display. 

https://www.macworld.com/article/675869/how-to-connect-two-or-more-external-displays-to-apple-silicon-m1-macs.html

**Comment by phoerious** [comment]
The 14" M2 MBP supports two displays. It's only the old 13" form factor MBPs (M1 and M2) that don't (I know both from first-hand experience). Dunno what's up with Airs, though.

**Comment by gw3437** [comment]
Yes, that's correct. the Pro's do support 2 external. The Airs, for reasons
unknown to me, did not. My 5 year old Dell could run 2 externals and the
Air M2 runs circles around it.

Silly Apple.

**Comment by gxgl** [comment]
I use M1 with new Sequoia OS v15.0 (just updated few moments ago) and Display Link v1.10.3 (updated few days ago) and experienced the same issue and I have used the steps presented here https://github.com/keepassxreboot/keepassxc/issues/10757#issuecomment-2111947199 to mitigate it.

On Sonoma v14.7 (also updated today, before Sequoia) I didn't had any issue like this.

Anyway.. Always having the "Allow screen capture" option active is not best from security perspective, but for now it works :) 

Also I am not sure the problem relies on MacOS itself then in Display Link drivers, which, to be honest, are not the best, but this what we have at the moment. Also can be a mix of both :) 


Thank for the solutions and workarounds, guys!

All the best,
George

**Comment by droidmonkey** [comment]
Yup at the end of the day this is 100% on Apple to solve. They offer no way to say "no apps except Apple apps". It's allow or deny.

**Comment by tudan110** [comment]
I also had this problem after updating to the latest version of MacOS Sequoia 15.0, Keepassxc version is 2.7.9. After I updated to Display Link v1.10.3 and restarted the computer, it works fine (and not before restarting)

我更新到最新版本的 MacOS Sequoia 15.0后也遇到了这个问题，Keepassxc 版本是 2.7.9。我更新到 Display Link v1.10.3，并重启电脑后，就可以正常使用了（没重启之前也不行）

**Comment by CDSeal** [comment]
I updated now, too, and it does **not** work (DisplayLink v1.10.3). KeePassXC is shown without problems on the internal display of my Macbook Pro, but if I move it to another display, it vanishes unless "enable screen capture" is active.

The problem is that if it starts on a DisplayLink display, the menu is unavailable, too, so you can only either start KeePassX with the command line option as @fbaquero said or blindly use the menu as @06Bine09 described.

**Comment by droidmonkey** [comment]
Did you reboot?

**Comment by CDSeal** [comment]
Yes.

**Comment by droidmonkey** [comment]
Unfortunately there is nothing we can do about this. Please file a bug or support ticket with apple.

**Comment by yangchi** [comment]
Hmm. I have a guess about why it works for some people but also doesn't work for some people.
I happened to be replacing my displaylink dock recently as well as upgraded to Sequoia. I have two external monitors. One thing I noticed is that my old DisplayLink dock would use DisplayLink screen sharing to drive both my two external monitors, while the new dock only drive one of them as such, the other external monitor seems to be directly/natively driven by the Macbook itself. I have no idea how it works and if i'm even describing it accurately.
But with the new dock, i can see Keepassxc on the monitor that's not driven by DL, on Sequoia. But if i drag KeepassXC's window to the other monitor, it becomes invisible as expected.
I think this is very similar to how people can still see it on the built-in display. As long as DL sharing isn't involved then you can see the window.
So if keepass is visible to you in Sequoia, maybe check if you are even using DL to drive that monitor.

**Comment by junmacarambon** [comment]
This is my short fix, in View, enable Allow Screen Capture.

![Screen Shot 2024-10-01 at 00 06 33 AM](https://github.com/user-attachments/assets/bede88fd-727b-4e38-963c-d32d5c941d79)

**Comment by VGerris** [comment]
I have the same issue on MacOS 15.1, dl 1.11.0 build 28. Workaround doesn't help, saw the update window once that seemed to be drawn over. I have no such issue with any other application. Please re-open the bug.

**Comment by droidmonkey** [comment]
It's not a bug on our end. You either enable or disable screenshot security. There are no exceptions. Apple needs to allow display link to override this security feature. Any app hiding their window from other apps will be equally affected.

**Comment by neshanjo** [comment]
> I updated now, too, and it does **not** work (DisplayLink v1.10.3). KeePassXC is shown without problems on the internal display of my Macbook Pro, but if I move it to another display, it vanishes unless "enable screen capture" is active.
> 
> The problem is that if it starts on a DisplayLink display, the menu is unavailable, too, so you can only either start KeePassX with the command line option as @fbaquero said or blindly use the menu as @06Bine09 described.

The menu is not displayed, but you can nevertheless click right to the Apple Icon in the menu bar and then the menu items are shown. Then move mouse right to where the "View" text should be, select "Allow screen capture", move window to internal display, deselect it and enter passwordn. This is my workaround that does not allow capturing my password input.

**Comment by droidmonkey** [comment]
You can also add `--allow-screencapture` as a launch parameter of KeePassXC.

**Comment by VGerris** [comment]
> > I updated now, too, and it does **not** work (DisplayLink v1.10.3). KeePassXC is shown without problems on the internal display of my Macbook Pro, but if I move it to another display, it vanishes unless "enable screen capture" is active.
> > The problem is that if it starts on a DisplayLink display, the menu is unavailable, too, so you can only either start KeePassX with the command line option as @fbaquero said or blindly use the menu as @06Bine09 described.
> 
> The menu is not displayed, but you can nevertheless click right to the Apple Icon in the menu bar and then the menu items are shown. Then move mouse right to where the "View" text should be, select "Allow screen capture", move window to internal display, deselect it and enter passwordn. This is my workaround that does not allow capturing my password input.

In my case, I do not see any menu items when moving. I understand now that this is a security feature, because the displaylink driver is basically recording the screen - which is perhaps something they could build in a different way, but I may be wrong.

I would suggest for the sake of having the app being usuable on devices that are recorded to have the option Allow Screen Capture on at start with a warning to move it to a screen for example, or even better, to only prevent watching the secrets, although I can imagine that can be quite the development effort. Thank you all for clearing things up, I did now disconnect the dock, enable option, put it on internal screen and it keeps starting there now, so it's ok. Which makes me think of another workaround, which would be for the app to try and find a screen to start on that is not recorded.

**Comment by RickyRomeroAZ** [comment]
> It's not a bug on our end. You either enable or disable screenshot security. There are no exceptions. Apple needs to allow display link to override this security feature. Any app hiding their window from other apps will be equally affected.

Can you please show some kind of warning saying that screen capture is active, preventing KeePassXC from displaying? I just wasted an hour trying to figure this out and it's plainly obvious I'm not the only one having problems with it.

![Image](https://github.com/user-attachments/assets/fac7ab6a-06d8-4da4-bd59-cbf07a4dc2ab)

**Comment by droidmonkey** [comment]
I wish it were that easy

**Comment by apos** [comment]
> Updating to DisplayLink Manager v1.10.2 (Build 14) helped here.

I have 1.11.0 (Build 28) - does not work.

Using tips above helped: 

- Dock -> right click KeepassXC icon -> Option -> Choose the primary desktop (non display link devce) 
   => shows app on this display 
- #issuecomment-2383616968 and here:#issuecomment-2126459706 
  => Within "Hidden"-Menu -> View -> Allow Screen Capture

Drove me crazy today having a teams session with urgent needed passwords ...

Cheers and thanks for the heip. 
Axel

P.S.: from a security point of view I think it is Ok to hinder an app to mirror a password safe. But the apple password app does not show this behaviour.

**Comment by randohinn** [comment]
1.12 exhibits this as well. As Apple/DisplayLink does seem to break this with every other version. Perhaps still consider adding a config option?

**Comment by sahinM** [comment]
I have now again the problem with v1.12 as well same as @randohinn.
For me also as stated in [this](https://github.com/keepassxreboot/keepassxc/issues/10757#issuecomment-2110851235) comment, enabling the screen capture solves it temporarily

**Comment by nkarkare** [comment]
I recently updated to Sequoia 15.6 and started facing this problem. [Solution](https://github.com/keepassxreboot/keepassxc/issues/10757#issuecomment-2111947199) given by @fbaquero works well. Thanks!

**Comment by CDSeal** [comment]
With the new version 13.0.0 of DisplayLink Manager, it works as intended again. \o/ (At least on MacOS 15.6)

**Comment by CDSeal** [comment]
Just to add that here, too: It stopped working again later, but there's been a new option in DisplayLink for a while: It's called "Enhance video conferencing apps / Auto-detect video call overlays". If that is activated, the KeePassXC window is shown on DisplayLink screens without problems.

This setting had prohibitive performance problems at first, but meanwhile works without problems at least on my 2021 MacBook Pro (M1 Pro). (Currently using DisplayLink 15.1.0.)
