### ISSUE TITLE
Hitting the F6 keyboard shortcut a second time should focus back to the database list from the seach bar

### ISSUE THREAD

**Issue by AlexandreBonneau** [keepassxreboot/keepassxc#10750]
## Summary
Since #9163 was merged, you can now access the search bar with F6, which is great and mimicks other application.

However, it would be even better to be able to toggle the focus from the search bar to the previously focused entry in the database (or select the very first one in the list if the database element(s) were not selected when first hitting F6).

I know you can hit F6 to focus on the search field, then hit up or down arrow to get back the focus on the database list, but if we want to mimick other applications, I think hitting F6 again should set the focus back to its previous state.

**Comment by droidmonkey** [comment]
Press down arrow or F2 to focus entries. I very much dislike keyboard shortcuts that switch meanings
