### ISSUE TITLE
Missing unified toolbar on macOS

### ISSUE THREAD

**Issue by adolfogc** [keepassxreboot/keepassxc#1075]
I don't think this is a regression but maybe a Qt issue.

## Expected Behavior

Current macOS builds should have the unified toolbar look, as modified by PR #361:

![Expected Screenshot](https://cloud.githubusercontent.com/assets/911270/23482425/558de490-fecf-11e6-9000-c97b2cb37eb9.png)

## Current Behavior
No unified toolbar:

![Current Behaviour Screenshot](https://cdn.pbrd.co/images/GP6tI2O.png)

## Possible Solution
Use QtMacExtras's QMacToolBar class instead?

References:
- https://stackoverflow.com/questions/16681965/combine-toolbar-and-title-bar-in-qt
- http://doc.qt.io/qt-5/qmactoolbar.html 

## Steps to Reproduce (for bugs)
1. Run a recent KeePassXC build in macOS.

## Context
This is a minor issue.

## Debug Info
KeePassXC - Version 2.2.1
Revision: 2bce9c8add07226e9a05e9e0fd0e5e66b236d5b6

Libraries:
- Qt 5.9.1
- libgcrypt 1.8.1

Operating system: macOS High Sierra (10.13)
CPU architecture: x86_64
Kernel: darwin 17.0.0

Enabled extensions:
- KeePassHTTP
- Auto-Type
- YubiKey

**Comment by weslly** [comment]
Seems to be happening only with macOS High Sierra (10.13). Maybe it's a Qt bug?

**Comment by davegradwell** [comment]
See also "QMainWindow::setUnifiedTitleAndToolBarOnMac broken on High Sierra": https://bugreports.qt.io/browse/QTBUG-63444
-> It's fixed in 5.9.3.

**Comment by adolfogc** [comment]
I've tested building it with the newly available Qt 5.9.3 from HomeBrew, it solves this issue.

**Comment by weslly** [comment]
Nice! Works for me too with Qt 5.9.3
