### ISSUE TITLE
MX Linux 23.2 after updating to 2.7.8. the browser settings are gone

### ISSUE THREAD

**Issue by Bub-0815** [keepassxreboot/keepassxc#10758]
## Overview
[![KeepassXC 2 7 8](https://github.com/keepassxreboot/keepassxc/assets/56425914/987cd695-2f9a-4370-884d-797de8d1d858)

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. i start KeepassXC, share the database, but the browser won't connect, the settings are just not there in KeepassXC anymore, so i have to copy everything manually into the browser.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.8
Revision: f6757d3

Qt 5.15.8
Diagnostic mode is disabled.

Operating system: Debian GNU/Linux 12 (bookworm)
CPU architecture: x86_64
Kernel: linux 6.1.0-21-amd64

Activated extensions:
- Auto-Type

Cryptographic libraries:
- Botan 2.19.3

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: XFCE
Windowing System: X11

**Comment by droidmonkey** [comment]
Post a bugreport to debian

**Comment by michaelk83** [comment]
Looks related to #10725 , but this is on bookworm?? Is this from backports?

**Comment by RedSnt** [comment]
There's a[ whole video](https://www.youtube.com/watch?v=9AV1Q-JfHpI) about this. Apparently the debian maintainer decided to strip out functionality. Which isn't great for those of us on Linux MX that uses browser integration with keepassxc.  

As the issue @michaelk83 points to, the solution is to install the keepassxc-full package. Bit annoying, but not the worst compromise.

**Comment by Bub-0815** [comment]
I have now solved the "problem" by using the AppImage. I find it totally wrong that a programmer from debian simply deletes the functions. Thanks for the tips here :-)
