### ISSUE TITLE
Master Password Deletes Itself

### ISSUE THREAD

**Issue by cyberXarmenta** [keepassxreboot/keepassxc#10773]
I have been noticing that when I open my existing database and put in my credentials, my master password will delete itself as i'm still typing it. This has been happening for a while. First I thought it was my keyboard doing this since I do have a key not functioning properly for a while as well, and I've been trying to resolve that issue.... But even when I enter in my master password using my laptops keyboard, without having the one with the key issue plugged in, I still see the same issue. I'll type in my password very slowly to catch it delete itself, and it'll happen randomly too. So I know i'm not accidentally pressing a combination of keys to delete. 

And yes, it is currently have the latest update installed, but this has been happening even before the update.

**Comment by phoerious** [comment]
#10695

**Comment by cyberXarmenta** [comment]
Thank you. Sorry about the duplicate.
