### ISSUE TITLE
The "clear search" icon shows up dark on dark theme (KDE)

### ISSUE THREAD

**Issue by AfroThundr3007730** [keepassxreboot/keepassxc#10772]
## Overview
![image](https://github.com/keepassxreboot/keepassxc/assets/7613032/14fb0196-62d3-48b7-9e38-751c14c6e72a)

This has been an issue for a long time, spanning several KeePassXC and Fedora versions. I figured I may as well report it now.

KeePassXC 2.7.8
Fedora 40 (KDE Plasma 6)

**Comment by droidmonkey** [comment]
Duplicate #5593
