### ISSUE TITLE
Entries lost in particular date range

### ISSUE THREAD

**Issue by ruleset** [keepassxreboot/keepassxc#10776]
### Discussed in https://github.com/keepassxreboot/keepassxc/discussions/10743

<div type='discussions-op-text'>

<sup>Originally posted by **ruleset** May 12, 2024</sup>
I had some data loss happen. I wonder if anyone might have insight as to how my process led to the loss? 
What methods might I try to recover the lost entries?
Has anyone seen a similar gap appear?

All keepassxc entries in "mydb" modified between 2024-03-25 and 2024-05-03 were gone upon opening a daily-use database. Entries with later and earlier mod times survive.

**Dates of entries, sorted by Modified descending.**
...
2024-05-05
~~2024-05-05~~
2024-05-04
2024-05-03
2024-03-25
2024-03-25
2024-03-21
...

## Sequence of Events

I don't know how to reproduce the outcome, so I will describe what happened

- before: 
  - the usual backup filename pair: mydb.kdbx and mydb.kdbx
  - the db lived on a removable drive that remains attached always
  - upgraded to 2.7.7 from 2.7.5. Kept old app, renamed KeePassXC-2-7-5-intel.app
  - had recently moved all entries into Root group. Workaround for "I'm not seeing all the entries, because some group was selected in hidden sidebar".
- between 3/25 and 5/03: there were many adds and edits of pre-existing entries.
- May 2 or 3
  - day: connected to a new wifi network
  - KeepassXC was running with dbs in tabs. the affected db may have been unlocked.
  - computer experienced total power failure. came unplugged, and battery failed.
  - 1 entry edited that night survived (the 5/3 bound)
- May 4
  - travel. connected to unsecured WIFI (i know!), with VPN/kill switch
  - open database
  - noticed the gap in entries
  - ensured that no search filters were active
  - examined mydb.old.kdbx and surrounding files. missing entries not found

- mitigation: changed backup filename scheme to {FILE}-{DATE}.kdbx

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

Expected the five weeks of entries to persist, or
that backup mydb.old.kdbx would contain some of the missing entries or
that loss would be "to date" (March 25 - current) or
that loss would be total.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
A specific date range was lost.

## Context
[NOTE]: # ( Give us any additional information you may have. )

During the timeframe described, the browser extension was reconnected.
It had reported 
  KeePassXC-Browser has encountered an error:

  Cannot connect to KeePassXC. Check that browser integration is enabled in KeePassXC settings. 
Months earlier, browser integration was working.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION
Revision: REVISION

## upgraded app debug info:

```text
KeePassXC - Version 2.7.7
Revision: 68e2dd8

Qt 5.15.11
Debugging mode is disabled.

Operating system: macOS 11.7
CPU architecture: x86_64
Kernel: darwin 20.6.0

Enabled extensions:
- Auto-Type
- Browser Integration
- Passkeys
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 3.1.1
```
## debug info, prior version:

```text
KeePassXC - Version 2.7.5
Revision: 9d0537b

Qt 5.15.8
Debugging mode is disabled.

Operating system: macOS 11.7
CPU architecture: x86_64
Kernel: darwin 20.6.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 2.19.3
```

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS
</div>

**Comment by ruleset** [comment]
Pilot error.

Work done in that date range was saved in a different filename.
Maybe because the original filename was a string with no extension, it got saved as the default name, Passwords.kdbx ?

When filename `foo` is opened, the app Tab is named "Passwords".

**Comment by droidmonkey** [comment]
You can set the name of your database (what is shown in the tab) from the database settings. Database -> Database Settings
