### ISSUE TITLE
integrated synchronization

### ISSUE THREAD

**Issue by west378** [keepassxreboot/keepassxc#10786]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( integrated database synchronization between different sources)

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )

## Context
[NOTE]: # To bring the different versions of the entries in the various or several databases up to the same status.
It should be possible, to synchronize the different versions of the databases in a uniform manner, preferably also automatically and time-controlled. I store my databases in several different locations to have at least one backup in case of loss.

**Comment by phoerious** [comment]
See #1775
