### ISSUE TITLE
First character of login is not automaticcaly entered with AutoType

### ISSUE THREAD

**Issue by solsticedhiver** [keepassxreboot/keepassxc#10782]
Using keepassxc 2.7.8 on archlinux (with own compiled package), when I use AutoType via a global keyboard shortcut, the **first** character of the login is not entered and this fails the login.
For example, with *login* **test** and *password* **passwd**, what is entered in the input field is 'est' and 'passwd'

However, when trying it a second time, this works fine.

on wayland, gnome shell 46.1, with:
```
$ echo $QT_QPA_PLATFORM 
xcb
$ echo $QT_WAYLAND_DECORATION 
adwaita
```

This **is not a website issue**,because this is also happening, in a basic auth http dialog.

this began to happen with 2.7.7, may be after a gnome upgrade.

**Comment by droidmonkey** [comment]
Definitely not a keepassxc issue, per say. Nothing related to auto-type keyboard was changed with 2.7.8. Recommend just increasing the initial delay before typing begins. Application settings -> auto-type tab.

**Comment by solsticedhiver** [comment]
First, I said this is happening with 2.7.7, and also 2.7.8. Not that it appears with 2.7.8

And increasing whatever dealy (first delay before autotype, or autotype dealy) does not change anything
I keep on increasing the dely, and I stil have the problem

**Comment by droidmonkey** [comment]
I guarantee this isnt a systemic problem with our app, it is very likely a local issue withour your environment.
