### ISSUE TITLE
It is not possible to select a keyfile with the Brazilian Portuguese software in version 2.7.8.

### ISSUE THREAD

**Issue by rafaelazvdo** [keepassxreboot/keepassxc#10788]
When clicking on the "I have a keyfile" button, simply nothing happens, both in Windows and Linux, the file explorer window does not open to be able to go to the file -key. This occurs in version 2.7.8, with the program configured for Brazilian Portuguese, or configured to use the system language that is in pt-br.

**Comment by droidmonkey** [comment]
This is a translator error, needs to be fixed on transifex.com. However we are going to move the HTML outside of the translation for the next release, this is a duplicate report. You'll have to use another language at first to select your key file and then move back to your language when done.

**Comment by michaelk83** [comment]
> we are going to move the HTML outside of the translation for the next release, this is a duplicate report

@droidmonkey [The original report](https://github.com/keepassxreboot/keepassxc/issues/10721) is closed and marked "not reproducible". I don't think there is an open iusse for this.

**Comment by phoerious** [comment]
It's fixed on Transifex and will be rolled out with the next release.
