### ISSUE TITLE
Context Menu on Wrong Display

### ISSUE THREAD

**Issue by sdgvdh** [keepassxreboot/keepassxc#10781]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. right click on database entry
2. 
3. 

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
context menu shows on left screen.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

context menu shows on right screen.

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )

The problem does not always occur

KeePassXC - VERSION 2.7.8
Revision: REVISION

Operating System: Windows 11

**Comment by JohnLGalt** [comment]
It would help troubleshooting this issue a lot better if you referred to them as primary and secondary display, versus just left and right.

Some make the left primary - some, like me, make the right primary.

**Comment by droidmonkey** [comment]
Qt issue, move the window away from the edge of the screen

**Comment by JohnLGalt** [comment]
Lol! I totally forgot about that - and you're right, 100% reproducible on my part too.
