### ISSUE TITLE
Add description / colour label to lock screen

### ISSUE THREAD

**Issue by techninja1008** [keepassxreboot/keepassxc#10783]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )

It would be very useful to visually distinguish different databases whilst locked, by having a combination of a short description ("lock screen summary") to state what the purpose is as well as a color label ("lock screen color") to visually distinguish different vaults at a glance.

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )

Some basic GIMP visual mockups:

![ex1](https://github.com/keepassxreboot/keepassxc/assets/4208789/d9f3e75b-a36f-4070-acfc-8960db5622e6)
![ex2](https://github.com/keepassxreboot/keepassxc/assets/4208789/a7000ceb-dbbb-4599-bb12-5314bf56be18)

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )

Often when typing a long, secure password for a vault, it can be a nuisance when you type one for a different vault than the one you're unlocking (you've opened the wrong one, you're distracted etc) especially when you think you may have just typed it wrong. Providing a visual cue as well as a description helps for this, and is also generally useful for giving a slightly more meaningful description of the vault than what can fit safely in a file name.

Obviously, users need to consider that this feature would necessarily have to store the summary and color outside of the encryption layer of the vault, and the configuration UI would need to make this abundantly clear. Furthermore, an unencrypted description might not be appropriate for some users, who would prefer to use the existing "description" field. I believe that this still presents a useful improvement in UX for those who find it appropriate for their security model.

If this sort of feature is acceptable, I'm happy to investigate contributing it myself given a high-level overview of how you would want it implemented.

**Comment by droidmonkey** [comment]
Hmmmmmm. We have introduced an unencrypted UUID as part of quick unlock handling. We could "convert that into a color", but honestly I don't see this as useful in general. I think an unencrypted database name/summary would be fine and easy to introduce.

**Comment by techninja1008** [comment]
Sorry if I wasn’t clear - I was proposing the color to be a user configurable property. My motivation for it was from an accessibility standpoint: both I and a lot of the people close to me struggle with dyslexia, so having different colors makes it significantly easier to tell what we’re opening at-a-glance, without having to engage the part of the brain that deals with reading and understanding the text.
