### ISSUE TITLE
Auto-Type not working for Adobe Acrobat "Certificates" password

### ISSUE THREAD

**Issue by 7eventech77** [keepassxreboot/keepassxc#10792]
## Overview
KeePassXC Auto-Type is not working in Adobe Acrobat for the “Certificate” option when digitally signing with a certificate.
## Steps to Reproduce
1.  Open Adobe Acrobat
2. Create a new Blank document
3. Click on aqua colored tool “Certificates”
4. Click on “Digitally Sign” option.
5. Drag and highlight area for signature
6. Option to select digital ID pops up
7. Click “Continue”
8. Field for password for certificate pops up but when pressing keys for Auto-Type, nothing pops up and no password fills.
 
![image](https://github.com/keepassxreboot/keepassxc/assets/142606643/0333b1c2-85ed-4b41-9584-56827dc830dd)

## Expected Behavior
Auto-Type to automatically fill in password when field for certificate password opens.

## Actual Behavior
Auto-Type does not fill in password and search box for passwords does not appear either.

## Context
Auto-Type works for filling in password for password protected document but not this.
Adobe Acrobat window is configured correctly for Auto-Type.

###Environment Information
KeePassXC - Version 2.7.8
Revision: f6757d3

Qt 5.15.11
Debugging mode is disabled.

Operating system: Windows 10 Version 2009 (Actually 21H2, not sure why it is not reporting correctly)
CPU architecture: x86_64
Kernel: winnt 10.0.19044

Enabled extensions:
- Auto-Type
- Browser Integration
- Passkeys
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 3.1.1

**Comment by droidmonkey** [comment]
Seems like the keys could be getting filtered by the program. See comment in your other issue.
