### ISSUE TITLE
Auto-Type autofill does not work on Drake Tax Timeout box

### ISSUE THREAD

**Issue by 7eventech77** [keepassxreboot/keepassxc#10793]
## Overview
Drake Tax (All years) Auto-Type autofill works on main screen when first starting but does not work when the “Timeout” window appears and locks the program. 

## Steps to Reproduce
1.	Open up Drake Tax and login using Auto-Type
2.	Wait until timeout box appears by not using program
3.	Try using Auto-Type and it does not automatically fill in password like it does when first opening
 
![image](https://github.com/keepassxreboot/keepassxc/assets/142606643/19e06271-1a90-4c6c-ab53-b2ca1ad74b2b)

## Expected Behavior
Auto-Type automatically fills in password in Timeout password box like it does for first opening the program

## Actual Behavior
Auto-Type does not automatically fill in password for Timeout box password field like it does for first opening the program.

## Context
Only one entry is added for each Drake Tax year so search box should not appear.

## Environment
KeePassXC - Version 2.7.8
Revision: f6757d3

Qt 5.15.11
Debugging mode is disabled.

Operating system: Windows 10 Version 2009 (Actually 21H2, not sure why it is reporting incorrectly)
CPU architecture: x86_64
Kernel: winnt 10.0.19044

Enabled extensions:
- Auto-Type
- Browser Integration
- Passkeys
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 3.1.1

**Comment by droidmonkey** [comment]
Application specific problems like this are not keepassxc problems. If nothing happens when you press the correct key combo then that's on the Application very likely filtering those key presses from the operating system.
