### ISSUE TITLE
AutoType Sequence `%p` should send `[ALT]+p` but send `3p`

### ISSUE THREAD

**Issue by lennybacon** [keepassxreboot/keepassxc#10791]
## Steps to Reproduce
1. Create an entry with the AutoType matching `Add to Archive` and the Sequence `%p`
2. Use application that reacts on `[ALT]+p`. I use the 7zip *Add to archive*.
3. Select the entry to be auto typed

## Expected Behavior

The key combination `[ALT]+p`  is send.

## Actual Behavior
The previously selected textbox now has the content `3p`

## Context
- Windows 11 
- KeePassXC 2.7.8
- United States-International Keyboard

KeePassXC - Version 2.7.8
Revision: f6757d3

Qt 5.15.11
Debugging mode is disabled.

Operating system: Windows 10 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.19045

Enabled extensions:
- Auto-Type
- Browser Integration
- Passkeys
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 3.1.1

Operating System: Windows
Desktop Env: n/a
Windowing System: n/a

**Comment by droidmonkey** [comment]
Does this occur with a non-international keyboard layout?

**Comment by lennybacon** [comment]
United States-International Keyboard is current. I‘ll try to check another one tomorrow at work.

**Comment by droidmonkey** [comment]
Confirmed this is a bug, and I fixed it, will be in 2.7.9

**Comment by lennybacon** [comment]
Respect for the fast response and fix!
