### ISSUE TITLE
TOTP Value wrong

### ISSUE THREAD

**Issue by xstable** [keepassxreboot/keepassxc#10799]
## Overview
I have authy 2fa and KeepassXC. For  some accounts I have setup TOTP and it work in the past (means, TOTP was synchron)

But now I found, that KeepassXC shows the wrong TOTP digits, while authy still show the right ones. 
With KeepassXC TOTP I can not login into those accounts anymore, with TOTP of AUTHY it work (as it ever has in the past).

## Context
I double checked again the TOTP-Setup and the entered KEY are exactly the one I use in authy:
(Following one is only an example, no real key, but the issue appears with the real keys!)
- MMQ55QZACFSKCL7KDXP7L54A37XVMALL is the `decrypted-Key` I have in authy... I copy that and paste it to TOTP-Setup
![image](https://github.com/keepassxreboot/keepassxc/assets/1778068/f3a6d6e6-486e-4741-9578-ac1423daaa7d)

But the TOTP-Digits differ from each other: 

![image](https://github.com/keepassxreboot/keepassxc/assets/1778068/081355c9-99e7-4fba-ba42-5837b800d1f8)

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.7
Revision: 68e2dd8

Qt 5.15.13
Diagnosemodus ist deaktiviert.

Betriebssystem: Manjaro Linux
CPU-Architektur: x86_64
Kernel: linux 6.6.30-2-MANJARO

Aktivierte Erweiterungen:
- Auto-Type
- Browser-Integration
- Passkeys
- SSH-Agent
- KeeShare
- YubiKey
- Secret-Service-Integration

Kryptographische Bibliotheken:
- Botan 3.4.0

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux (Manjaro)
Desktop Env: KDE
Windowing System: X11

**Comment by droidmonkey** [comment]
Sync your computer time

**Comment by xstable** [comment]
@droidmonkey it's in sync, it's exactly in sync wtih: https://time.is/de/

**Comment by droidmonkey** [comment]
Then your secret value is wrong. However I guarantee it's your computer time.

**Comment by xstable** [comment]
Ok, it was apparently in sync, but seems not 100% in sync. Now I have activate "automated time adjustment" in KDE and it work again.
Thanks.
