### ISSUE TITLE
Considering the proximity of the options after right click above an entry, users may inadvertently delete instead of cloning or adding new entries

### ISSUE THREAD

**Issue by ejantunes** [keepassxreboot/keepassxc#10798]
## Overview
Considering the proximity of the options after right click above an entry, users may inadvertently delete an entry instead of cloning or adding new entries.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Right Clck above an entry
2. Inadvertently miss the clone entry action and hit the delete entry action

## Expected Behavior
I expected a confirmation message box to confirm the delete entry action

## Actual Behavior
No confirmation message box to confirm the delete entry action, so the entry gets inadvertently deleted

## Context
Personally, I use a lot the clone option as I don't have to rewrite the username, which if often my personal or professional e-mail.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.7
Revision: 68e2dd8

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows

**Comment by phoerious** [comment]
There is a confirmation box before an entry is actually deleted. If you don't see one, the entry is simply moved to the recycle bin. That may be annoying if you misclicked, but I don't think it's enough reason to move the action elsewhere.

**Comment by ejantunes** [comment]
Yes, you are right: the entry was simply moved to the recycle bin... 

I'll close this issue.
