### ISSUE TITLE
Add a scrollbar in the AddEntry window when on "small" screen

### ISSUE THREAD

**Issue by TheZ3ro** [keepassxreboot/keepassxc#108]
## Expected Behavior

Visualize the UI correctly when Adding/Editin an Entry with the PasswordGenerator opened.

## Current Behavior

When Adding/Editing an Entry, if you open the PasswordGenerator the window height goes > 768 pixel so on 1360x768 screen resolution the bottom button aren't visualized correctly.
This resolution is very common on laptop and notebook.

## Possible Solution

Add a scrollbar to the window or make the Notes textarea smaller

## Steps to Reproduce (for bugs)

1. Use a resolution smaller or equal to 1360x768
2. Try to add a new entry
3. Open the PasswordGenerator

**Comment by vsvyatski** [comment]
I think I've resolved this with my pull request [\# 514](https://github.com/keepassxreboot/keepassxc/pull/514)

**Comment by TheZ3ro** [comment]
Closing, thanks @vsvyatski
