### ISSUE TITLE
HardwareKeyProgress Visible Even if No Hardware Key Is Found

### ISSUE THREAD

**Issue by 0xdeadbeer** [keepassxreboot/keepassxc#10806]
## Overview
Hardware key progress bar is visible even if no hardware keys are found (inside DatabaseOpenWidget)

![issue](https://github.com/keepassxreboot/keepassxc/assets/64986162/7b76f85d-db6c-46e6-ad37-4df09fe90708)

The object is set to visible from inside `DatabaseOpenWidget::pollHardwareKey`. I wonder if this bar has a real purpose in code because grep and Qt Creator do not seem to reveal much - besides calls that simply hide or show the bar..?

![question](https://github.com/keepassxreboot/keepassxc/assets/64986162/29cb8869-9a9e-4a56-baaa-8f54a412a507)

## Steps to Reproduce
1. Open KeePassXC (with no hardware keys) 
2. Open the lock screen for any database

## Context
KeePassXC - Version 2.8.0-snapshot
Build Type: Snapshot
Revision: da90319

Qt 5.15.13
Debugging mode is enabled.

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 6.8.7-arch1-1

Enabled extensions:
- Auto-Type

Cryptographic libraries:
- Botan 3.4.0

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: XFCE
Windowing System: X11

**Comment by droidmonkey** [comment]
It just shows that a search for a device is being made
