### ISSUE TITLE
KeepassXC shows wrong TOTP

### ISSUE THREAD

**Issue by NickWick13** [keepassxreboot/keepassxc#10807]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # TOTP has changed and is no longer the same as on my phone

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Configure/Add TOTP to a post from mobile app using the secret key
2. Save it and then choose to show TOTP
3. It doesn't show the same TOTP as the mobile app and the TOTP shown in KeepassXC doesn't work anymore. Weirdly it worked before but then it stopped working.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
TOTP on KeepassXC and the mobile app to show the same code and both would work.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
KeepassXC does not show the same TOTP as the mobile app and the TOTP shown in KeepassXC no longer works. Only the TOTP on the mobile app works. Weirdly it worked right after I had added it to KeepassXC but then it stopped working. I have checked that the secret key in KeepassXC is the same as in the mobile app.

## Context
[NOTE]: # ( Give us any additional information you may have. )
I am using Debian GNU/Linux 12 (bookworm) and using KeepassXC that comes with Debian. 

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.4
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: Gnome
Windowing System: Wayland

**Comment by droidmonkey** [comment]
Sync your computer time

**Comment by NickWick13** [comment]
@droidmonkey What do you mean? It is already synced?

**Comment by droidmonkey** [comment]
It definitely isn't, you are at least 30 seconds off

**Comment by NickWick13** [comment]
@droidmonkey You are right, it was set manually and after I synced it worked. Thank you!
