### ISSUE TITLE
chromium .csv import generates blank database

### ISSUE THREAD

**Issue by kerblness2** [keepassxreboot/keepassxc#10805]
## Overview
When I attempt to import a .csv file of passwords generated by Chrome (and Vivaldi) KeepassXC does recognize the .csv, its header line, and all valid fields, and generates a correct preview prior to creating a database. When I attempt to finalize the creation of the database, KeepassXC only generates a blank database file. 

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1.  export passwords stored in a chromium browser to .csv (most recent versions of Chrome, Vivaldi for me)
2.  attempt the .csv based database import in KeepassXC 2.7.8 for Windows
3.  confirm and complete the import to a kdbx database

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
I expected to see my passwords imported to a .kdbx database under a list of sub-files containing their entries

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
a blank .kdbx database was generated - no contents of the .csv were present

## Context
[NOTE]: # ( Give us any additional information you may have. )
tested on both Windows 10 and 11, same behavior
no other password managers were present on either system I attempted to import on
the .csv files were not open in any other program at time of import (confirmed with filelocksmith)

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.8
Revision: f6757d3

Qt 5.15.11
Debugging mode is disabled.

Operating system: Windows 11 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.22621

Enabled extensions:
- Auto-Type
- Browser Integration
- Passkeys
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 3.1.1

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows

**Comment by droidmonkey** [comment]
Make sure you select a title column mapping. This is already reported.
