### ISSUE TITLE
Keepass stoped working in my macos (M1, Sonoma 14.5). 

### ISSUE THREAD

**Issue by aacevessimplus** [keepassxreboot/keepassxc#10808]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

I installed executables for lastest version 2.7.8 and the previous 2 versions. 

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Isntall executable. Everything seems fine
2. When running, none of the menu displays. Only the apple shows up. 
3. Still can clic where the options should be, adn they are, but most functions do not work. 
4. Installed it from srouce code. Everything looks ok. 

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

Executable be working.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

Menues do not show up properly. Nothing "important" works. 

## Context
[NOTE]: # ( Give us any additional information you may have. )

After installing source code, I get this errors while testing:

91% tests passed, 4 tests failed out of 44

Total Test time (real) =  29.49 sec

The following tests FAILED:
	 18 - testautotype (Subprocess aborted)
	 41 - testcli (SIGTRAP)
	 42 - testgui (Subprocess killed)
	 44 - testguibrowser (Subprocess killed)
Errors while running CTest
make: *** [test] Error 8

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION 2.7.8 (same thing for 2.7.7 and 2.7.6)
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating macOS
Desktop Env: Sonoma 14.5
Windowing System: ?

**Comment by droidmonkey** [comment]
https://github.com/keepassxreboot/keepassxc/issues/10757#issuecomment-2126342637
