### ISSUE TITLE
KeePassXC crashes on screen unlock.

### ISSUE THREAD

**Issue by izbushka** [keepassxreboot/keepassxc#10803]
## Overview
Sometimes  (several times a day) keepassxc crashes (segfault) on screen unlock. It happens not all the time, it almost never crashes while trying to catch a crash locking/unlocking the screen. Maybe it depends on it uptime or last usage time, I haven't found a pattern.

## Steps to Reproduce

1.  Unlock the database
2.  Lock the screen or wait for it to be locked by timeout.
3. Unlock the screen.

## Expected Behavior
KeePassXC keeps runing.

## Actual Behavior
KeePassXC crashes with segfault.
Strace [keepass.strace.txt](https://github.com/keepassxreboot/keepassxc/files/15429910/keepass.strace.txt)

KeePassXC - Version 2.7.7
Revision: 68e2dd8

Qt 5.15.13
Debugging mode is disabled.

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 6.8.9-arch1-2
X-Server: xorg-server 21.1.13-1
WM: xfce

Enabled extensions:
- Auto-Type
- Browser Integration
- Passkeys
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 3.4.0

**Comment by droidmonkey** [comment]
Update to 2.7.8....
