### ISSUE TITLE
Last opened databases are not reloaded, even if set it that way in settings

### ISSUE THREAD

**Issue by xstable** [keepassxreboot/keepassxc#10815]
## Overview
Sinse a week or two I have the issue, that if I open KeepassXC, I always see this login-screen: 

![image](https://github.com/keepassxreboot/keepassxc/assets/1778068/0bf485a5-5ae0-45df-8da3-6c357052b47b)

So I have to open each of the databases manually every day.
Previous behavior was another one. If I open KeepassXC, I see all three Databases (each in a single tab), ready to enter the Password.

This happen, even if I have setup it in another way... means I have set it up to remember the three most recently opened databases (that seems to work) but also to open the recently opened database.

Do I miss something to configure or is that a known bug of the current KeepassXC-Build?

[NOTE]: #
KeePassXC - Version 2.7.7
Revision: 68e2dd8

Qt 5.15.13
Diagnosemodus ist deaktiviert.

Betriebssystem: Manjaro Linux
CPU-Architektur: x86_64
Kernel: linux 6.6.30-2-MANJARO

Aktivierte Erweiterungen:
- Auto-Type
- Browser-Integration
- Passkeys
- SSH-Agent
- KeeShare
- YubiKey
- Secret-Service-Integration

Kryptographische Bibliotheken:
- Botan 3.4.0

**Comment by droidmonkey** [comment]
Do you have this setting enabled?

![image](https://github.com/keepassxreboot/keepassxc/assets/2809491/02b54a6a-0a81-4216-b7bc-2bd749748fd2)

Also recommend opening your databases, then exiting fully (Database menu -> Quit) once to lock in the open state of the databases.

**Comment by xstable** [comment]
Yes, I have the tick in "Load previously open databases on startup". 
I've done it with "open all db's" and go to Quit... that seems to do the trick (for now). 

I will see how it act after a reboot, but I think it may be the solution at least. 
Thx.

**Comment by droidmonkey** [comment]
It's likely when you reboot last time it didn't give keepassxc the chance to write the config file before being force closed.
