### ISSUE TITLE
keepassxc-full does not recognize browser extension

### ISSUE THREAD

**Issue by andrewufrank** [keepassxreboot/keepassxc#10816]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
a new installed (debian 13) keepassxc-full 2.7.7 does not find the browser extension 1.9.0.5

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. open keeypass
2. open firefox, go to manage extension, restart keepassxc-browser
3. error message: KeePassXC-Browser has encountered an error:

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen ) connect and show the green sign in the browser

## Actual Behavior
[NOTE]: # ( Tell us what actually happens ) error as above

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.7
Revision: 68e2dd8

Qt 5.15.10
Debugging mode is disabled.

Operating system: Debian GNU/Linux trixie/sid
CPU architecture: x86_64
Kernel: linux 6.7.12-amd64

Enabled extensions:
- Auto-Type
- Browser Integration
- Passkeys
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.19.4

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows/Linux/macOS linux debian 13 trixie 
Desktop Env: Gnome/KDE/XFCE/Mate/Cinnamon Mate
Windowing System: X11/Wayland

**Comment by droidmonkey** [comment]
Write a bug report to Debian, then install `keepassxc-full`
