### ISSUE TITLE
AppImage: cannot run: "error while loading shared libraries: libusb-1.0.so.0: cannot open shared object file: No such file or directory"

### ISSUE THREAD

**Issue by vitaly-zdanevich** [keepassxreboot/keepassxc#10812]
$ ./KeePassXC-2.7.8-x86_64.AppImage -h
keepassxc: error while loading shared libraries: libusb-1.0.so.0: cannot open shared object file: No such file or directory

**Comment by phoerious** [comment]
Please don't delete the issue template. That makes it very hard to help you.
If you are running Ubuntu, try installing `libusb-1.0-0`.

**Comment by vitaly-zdanevich** [comment]
But the purpose of AppImage is to have dependencies inside.

**Comment by phoerious** [comment]
Not all base dependencies can or should be packaged. See https://github.com/AppImageCommunity/pkg2appimage/issues/378

**Comment by vitaly-zdanevich** [comment]
Hm, many people do not need a USB functionality, what about creating a smaller AppImage without USB?

**Comment by vitaly-zdanevich** [comment]
> If you are running Ubuntu

I am on Gentoo Linux.

**Comment by phoerious** [comment]
libusb should be preinstalled on most systems, that's why it's not packaged.

**Comment by droidmonkey** [comment]
At the end of the day, if you want a fully contained deployment use Flatpak. Appimage, despite perceptions, is absolutely not that. And this isn't a keepassxc problem.
