### ISSUE TITLE
Search doesn't search by folders name (groups)

### ISSUE THREAD

**Issue by Yszty** [keepassxreboot/keepassxc#10825]
Hello, 
search doesnt search by folders name (groups). Its should be configurable in settings. 
Best regards

**Comment by droidmonkey** [comment]
Use the `g:` prefix as documented in the user guide

**Comment by Yszty** [comment]
LOL, sorry for wasting Your time, and thanks for help. Using `g:` works like a charm
For posterity: https://keepassxc.org/docs/KeePassXC_UserGuide#_searching_the_database
