### ISSUE TITLE
QuickUnlock feature is broken in KeepassXC 2.7.8 (Touch ID / Windows Hello availability detection looks broken)

### ISSUE THREAD

**Issue by achernyakevich-sc** [keepassxreboot/keepassxc#10829]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

I have Windows 10, Windows Hello configured and actively used with fingerprints scanner. I used portable version of KeepassXC 2.7.7 and had no problem with QuickUnlock functionality (after first time entering master password and confirmation of it by fingerprint I could unlock database by fingerprints).

After migration to KeepassXC 2.7.8 (config of 2.7.7 kept) QuickUnlock looks broken as after entering master password for the first time no window to confirm fingerprints appeared. Additionally `Tools`->`Settings`->`Security` shows `Enable database quick unlock (Touch ID / Windows Hello)` is ticked and disabled (it could mean that KeepassXC could not detect Touch ID / Windows Hello).

Rollback to KeepassXC 2.7.7 using the same config resolve the issue.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

1. Correct detection availability of the Touch ID / Windows Hello and correspondingly availability of the QuickUnlock functionality.
2. If Touch ID / Windows Hello is not detected then `Tools`->`Settings`->`Security` shows `Enable database quick unlock (Touch ID / Windows Hello)` should be disabled but unticked (it is just UX improvement that could prevent user misleading).

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

Touch ID / Windows Hello is not detected and QuickUnlock functionality is not available.

## Context
[NOTE]: # ( Give us any additional information you may have. )

The same problem for KeepassXC 2.7.8 I experienced on macOS (MacBook Pro, Ventura).

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.8
Revision: f6757d3

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows/macOS

**Comment by droidmonkey** [comment]
Make sure you are not using the legacy windows version. Quick unlock works fine on windows.

**Comment by achernyakevich-sc** [comment]
> Make sure you are not using the legacy windows version. Quick unlock works fine on windows.

@droidmonkey 

Looks like you are slightly kidding. :)

I use Windows 10 and installed latest updates - it is supported by Microsoft. macOS Ventura on other my laptop is not legacy and supported by Apple (I would ever say that Ventura is more stable than Sonoma). In our company people do not switch to 2.7.8 because it frustrate them by broken QuickUnlock feature.

It is obvious that if on the same stations 2.7.7 works well and 2.7.8 has functionality broken then it is more like a bug - as everybody expects that you use SemVer (Semantic Versioning) and software updates by third number in a version means _bugfixes only and no breaking changes_.

I know what is Open Source Software and participate in several projects. It is uneasy, money free, moved forward by volunteers... But, please, could be so kind to pay more attention to the problem, reopen this issue and maybe fix it. I would be glad to provide detailed information from my side if it will be required.

**Comment by droidmonkey** [comment]
We offer two different downloads for windows, one is a legacy build for windows 7 and below:

![Screenshot_20240530_054244_GitHub.png](https://github.com/keepassxreboot/keepassxc/assets/2809491/7887055f-8aae-4223-8749-44a138f247fd)

That one doesn't support quick unlock. 

We also made no code changes to quick unlock in 2.7.8 and it's working fine for everyone else.

**Comment by achernyakevich-sc** [comment]
@droidmonkey I would like to thank you a lot for your help and detailed explanation.

It helped us to find what is the problem and how it appeared on our side. Now it is resolved. In few words: our system engineer responsible for the tracking updates of KeepassXC accidentally downloaded the LegacyWindows build from the https://keepassxc.org/download/ and uploaded it to our internal mirror (local version is renamed). Now we have fixed this process so problem reason will not repeat. :)

Thank you once again.
