### ISSUE TITLE
2.7.8 window to key file not opening

### ISSUE THREAD

**Issue by sandrovisky** [keepassxreboot/keepassxc#10832]
## Overview
i format my pc just now, and after install the last version, 2.7.8, and select my database, the option to chose a key file is not working. after click, not hapens. it was needed remove that version and install a the 2.7.7 to open my database. i guess that now the field for choose a file is showing because 2.7.7 could open that field, maybe the  2.7.8 will start with this field already showing, but i not will test this, srry

my language is pt_BR

![image](https://github.com/keepassxreboot/keepassxc/assets/72823705/9e7aa8d9-137a-4cde-8259-b4df40a3c01f)
![image](https://github.com/keepassxreboot/keepassxc/assets/72823705/b6fc425c-89a9-4531-9cd2-164de85ab6fb)

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. install the 2.7.8 from a fresh windows without previous keepass installed
2.  choose the databse file
3.  click in 'i have a key file'

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
the windows to choose keyfile should open

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
nothing hapens, and a cant open my database

## Context
[NOTE]: # ( Give us any additional information you may have. )
windows new instalation.

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows

**Comment by phoerious** [comment]
See #10721
