### ISSUE TITLE
Database Merge work only in one direction

### ISSUE THREAD

**Issue by reneb1972** [keepassxreboot/keepassxc#10839]
Hello,

I use 2 Operating systems with one database that is saved on share .
I add an entry with windows keepass app and save the database.
Now I open keepass xc with Mac and I merge the file --> the entry is available in the keepass xc on Mac.

Now I add an entry with keepass xc on Mac and save the file.
I merge the database with the file on the share --> Database was not changed during the merge.

KeePassXC - 2.7.8
Operating System: macOS Sonoma

**Comment by droidmonkey** [comment]
Duplicate, search for file sync

**Comment by reneb1972** [comment]
@droidmonkey : sorry, what should I do?
I am new here and I search for help.

**Comment by droidmonkey** [comment]
Your request is a duplicate of https://github.com/keepassxreboot/keepassxc/issues/2937

To do this today, open both databases you want to sync. Merge B into A, then switch to B and merge A into B.
