### ISSUE TITLE
KeepassXC cannot run on new Windows 10 Pro installations  -   MSVCP140.dll and VCRUNTIME140.dll was not found.

### ISSUE THREAD

**Issue by wcaseymc** [keepassxreboot/keepassxc#10838]
## Overview
New installation of Windows 10 Pro.  First updated everything in Windows, then installed KeepassXC.  When I try to run KeepassXC, I get 3 "KeepassXC.exe System Error".
1.  The code execution cannot proceed because MSVCP140.dll was not found.  Reinstalling the program may fix this problem.
2.  The code execution cannot proceed because VCRUNTIME140.dll was not found.
3.  The code execution cannot proceed because VCRUNTIME140_1.dll was not found.

## Steps to Reproduce
On band new Windows 10 Pro install, completely updated.  All other apps working fine.
1. install KeepassXC for Windows 10
2. Run KeepassXC

## Expected Behavior
Expected to work like before.

## Actual Behavior
Gives errors, then quits.

## Context
I have tried updating to reinstall the Microsoft Visual C++ Redistributables, even though every other app on the computer works fine.  This has no effect.

[NOTE]:
This is the second fresh install of Windows 10 Pro that I have tried and gotten the same result.  KeepassXC will not run on Windows 10 Pro new installations.

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows/Linux/macOS
Desktop Env: Gnome/KDE/XFCE/Mate/Cinnamon
Windowing System: X11/Wayland

**Comment by droidmonkey** [comment]
![Screenshot_20240601_001909_Edge.png](https://github.com/keepassxreboot/keepassxc/assets/2809491/bde21292-4d40-48a8-8b57-7c6962c40288)

https://aka.ms/vs/17/release/vc_redist.x64.exe

**Comment by markusd112** [comment]
Isn't it possible to add the MSVC redistributables in the KeepassXC installer? I struggled into this issue too on a brandnew win11 installation.

**Comment by TechLoom** [comment]
> Isn't it possible to add the MSVC redistributables in the KeepassXC installer? I struggled into this issue too on a brandnew win11 installation.

That, or when the error fires off, inform the end user of the issue with a link, and/or an option to auto download and install.

**Comment by H-Sapien** [comment]
TechLoom <-- you would hope so, wouldn't you - that the required, indeed necessary, dlls would be included in the installation package?
Imagine the planning meetings: 'Oh, you have to finish installing your operating system before you can run our program'.
Think of Steve 'It just works' Jobs' fury at seeing an installation like this.
'Everything' tells me that I have 67 msvcp140.dll copies on my system drive already, for instance, so it's done. (None of them are available to KeePassXC, obviously, unfortunately.)
+1

**Comment by phoerious** [comment]
Believe it or not: we've tried bundling them, but the MSI bundling toolkit doesn't allow it.
