### ISSUE TITLE
Additional "attributes" a.k.a. variables in KeePassXC

### ISSUE THREAD

**Issue by nlime** [keepassxreboot/keepassxc#10833]
## Overview

good answer - insufficient documentation IMHO
additional "attributes" a.k.a. variables in KeePassXC

if you need more additional "attributes" a.k.a. variables to use in your vast and complicated auto-type sequences in KeePassXC:

1.    define all necessary variables in the area Advanced Entry Options Additional Attributes Here you define key - value pairs.
2.    use them whenever you like with the Entry Placeholder {S:<ATTRIBUTE_NAME>} Value for the given attribute (case sensitive)
3.     like this example :
4.     test  testvalue
5.     Later call : {S:test}
6.     where you like. It populates the value : testvalue 
7.     The question is why doesn't it work?
8. {S:The VARIABLE} is just in the automatic input sequences, it does not work.
{USERNAME}{S:TEST}{PASSWORD} does not work

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.1

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: XFCE4
Windowing System: X11

**Comment by droidmonkey** [comment]
{S:VARIABLE} only applies to auto-type sequences, not entry references.

**Comment by nlime** [comment]
> {S:VARIABLE} only applies to auto-type sequences, not entry references.

{S:The VARIABLE} is just in the automatic input sequences, it does not work.
{USERNAME}{S:TEST}{PASSWORD} does not work

**Comment by droidmonkey** [comment]
If your advanced variable is named `Test` then `TEST` won't work. Case matters.

**Comment by nlime** [comment]
> If your advanced variable is named `Test` then `TEST` won't work. Case matters.

it's not called test, it's an example.
