### ISSUE TITLE
Starting/opening KeePassXC on Plasma6 locks the screen if u2f device is connected

### ISSUE THREAD

**Issue by kastl-ars** [keepassxreboot/keepassxc#10836]
## Overview
openSUSE Tumbleweed with u2f and fprintd configured to unlock the Plasma6 lock screen. Session is running in Wayland, not X11.

If the u2f device is connected, as soon as KeePassXC is started (e.g. automatically on log in) or opened from the tray, the screen locks.
If I remove the u2f device, this does not happen.

This only happens with KeePassXC. So opening the bug report here, as it does not seem to be a general issue with e.g. Plasma6.

This is annoying, so I would really like to solve this riddle. I can only reproduce this on one of two machines, but I do not find the reason why. The settings __should__ be identical, but somewhere there must be a difference.

If anyone has any ideas, this would highly be appreciated.

Kind Regards,
Johannes

## Steps to Reproduce

1. Configure pam to use u2f for unlocking the plasma lock screen by adding this in `/etc/pam.d/kde`
   ```
   auth     sufficient     pam_u2f.so      openasuser authfile=.config/Yubico/u2f_keys
   ``` 
1. After a reboot and log in, start KeePassXC or open it from the tray. The screen locks.
2. Log in again and then remove the u2f device
3. Start KeePassXC or open it from the tray. The screen does not lock. 

## Expected Behavior
The screen should not lock, even if the u2f device is connected.

## Context
KeePassXC - VERSION
`keepassxc-2.7.8-1.1.x86_64`

Operating System: Linux (openSUSE Tumbleweed)
Desktop Env: KDE (Plasma6)
Windowing System: Wayland

**Comment by phoerious** [comment]
This is most likely the same problem as #10077.

**Comment by kastl-ars** [comment]
> This is most likely the same problem as #10077.

Yes, looks like it from first glance. Sorry, must have missed that one...
