### ISSUE TITLE
My Database password changed somehow by Database Settings automatically

### ISSUE THREAD

**Issue by linuxtopia** [keepassxreboot/keepassxc#10848]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

I think the title of the issue/bug is obvious to get what happened. Unfortunately I lost the password due to auto assigned password by KeepassXC. I had just want to change my database name, changed and then clicked ok a popup appeared about weak password notice but never typed to password section. Even clicking on "Cancel" that process gone and my password changed somehow automatically!

Thanks to my local backup I recovered my database but because of this annoying issue I had to shred my cloud backup in cryptomator vault. But now when I try to reproduce it just ask "continue without password". Hovering-clicking Security/Password has a serious risk to loose credentials for other users too.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Database
2. Database Settings 
3. Misclick Security > Password section
4. General
5. Database Metada
6. Change Database Name
7. Click OK

![image](https://github.com/keepassxreboot/keepassxc/assets/19939134/c386fa81-d067-4471-820d-8071683ce3fa)

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
There MUST be check mark against mistype/misclick on Security tab for password changing against this kind of losses.

![image](https://github.com/keepassxreboot/keepassxc/assets/19939134/db464089-c88a-4b63-ab2d-ddbe536a40f2)

For just visiting Security tab and password section that activates password changing then KeepassXC assumes that you want to / changed it then tries to save over your password.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.8
Revision: f6757d3

Qt 5.15.8
Debugging mode is disabled.

Operating system: openSUSE Leap 15.5
CPU architecture: x86_64
Kernel: linux 5.14.21-150500.55.65-default

Enabled extensions:
- Auto-Type
- Browser Integration
- Passkeys
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.19.3

[NOTE]: # ( Pick choices based on your environment )
Operating System:
Linux-  openSUSE Leap 15.5
Desktop Env: KDE
Windowing System: X11

**Comment by droidmonkey** [comment]
Fixed for 2.7.9: #10821

**Comment by droidmonkey** [comment]
FWIW, we won't show the view you screencapped unless you actively click on the button "Change Password"

![image](https://github.com/keepassxreboot/keepassxc/assets/2809491/afc33193-a828-42ef-a4af-7e2641d0fc15)

> due to auto assigned password by KeepassXC

We don't do that

**Comment by linuxtopia** [comment]
I thought a bug caused it. Great to see an enhancement on this issue with new version. Keep it up guys XC is the best client for Keepass.

Thanks
