### ISSUE TITLE
Access confirmation request lists totally different entries

### ISSUE THREAD

**Issue by ygrange** [keepassxreboot/keepassxc#1084]
I get asked to confirm access to passwords for websites that aren't in my database

## Expected Behavior
Nothing should happen here

## Current Behavior
I get a popup asking me to confirm acces to my passwords for this website. It lists a bunch of entries from which I could get the password. This list does not contain the website I visit (it isn't present in the DB) just added and in fact contains several entries of my data base. Those seem to be the same three for most sites I visit.

## Steps to Reproduce (for bugs)
1. Go to a website that doesn't have an entry

## Debug Info
KeePassXC - Version 2.2.1
Revision: 2bce9c8add07226e9a05e9e0fd0e5e66b236d5b6

Libraries:
- Qt 5.9.1
- libgcrypt 1.8.1

Operating system: macOS Sierra (10.12)
CPU architecture: x86_64
Kernel: darwin 16.7.0

Enabled extensions:
- KeePassHTTP
- Auto-Type
- YubiKey

**Comment by droidmonkey** [comment]
Known issue fixed in 2.2.2 being released tomorrow.
