### ISSUE TITLE
[Windows] Graphic bug after changing display scale

### ISSUE THREAD

**Issue by ghost** [keepassxreboot/keepassxc#10850]
## Steps to Reproduce
1. Lock the database
2. Change your screen scale from 100% to e.g. 125% or 150%, or vice-versa
3. The sign in screen to KeePassXC has now duplicated its input fields and fields are stacked on each other.

## Expected Behavior
I don't expect it to duplicate elements on the "sign in" screen to my KeePassXC database, after changing screen scaling settings.

## Actual Behavior
It duplicates the elements on the "sign in screen" (meaning, duplicated input fields and buttons). It's a graphic bug that occurs after changing screen resolution scaling on Windows 10.

## Context
I had my Windows laptop on 150% scale settings and locked it. I then plugged it in to a monitor and changed the scaling to 100%. When I opened my KeePassXC (which auto-locked when the computer locked), the elements (buttons, input fields) had duplicated and overlapped each other. I had to restart KeePassXC to fix the issue.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.8
Revision: f6757d3

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 10
Desktop Env: N/A
Windowing System: N/A

**Comment by droidmonkey** [comment]
This is a Qt problem that happens sometimes. Unfortunately nothing we can do to fix it before upgrading to Qt6 with 2.8.0
