### ISSUE TITLE
auto-select of the search field after opening keepassxc

### ISSUE THREAD

**Issue by damnms** [keepassxreboot/keepassxc#10855]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
When i open keepassxc and enter the password, the cursor was automatically in the search field. Now its somewhere else, but not in the search field. So i have to click first in the search field. Thats a bit annoying.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. open keepassxc
2. enter the password
3. search for an entry

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
the typed keys should be in the search bar

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
nothing happens

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.7
Revision: 68e2dd8

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux Debian testing
Desktop Env: xfce
Windowing System: X11

**Comment by droidmonkey** [comment]
Update to 2.7.8.
