### ISSUE TITLE
Minimum Qt version?

### ISSUE THREAD

**Issue by c4rlo** [keepassxreboot/keepassxc#10859]
What is the project's minimum required Qt version at this point? It would be nice to state this somewhere for reference.

As I said in my original PR description for #7783, I've been assuming 5.9.5 as the minimum version, as that was stated in INSTALL.md at the time; but as of #10088, it no longer mentions a minimum version requirement. Instead, we now have:

https://github.com/keepassxreboot/keepassxc/blob/c81e4e1208d8b84f1933270af370ab52c94821e0/vcpkg.json#L37-L40

But also:

https://github.com/keepassxreboot/keepassxc/blob/c81e4e1208d8b84f1933270af370ab52c94821e0/CMakeLists.txt#L515-L517

(Currently, my #7783 includes a commit to change the above to require 5.9.5.)

I ask because there are a bunch of `QT_VERSION_CHECK`s in the code (including some new ones in #7783), some of which could potentially be deleted now, depending on the minimum Qt version we want to impose. I'd be happy to submit a PR for that cleanup, if I knew which Qt version to target. (Of course, we eventually want to migrate to Qt 6, in #10267, but that might be a while yet I imagine.)

**Comment by droidmonkey** [comment]
We are bumping it to 5.12 then 6.6 (I think that's the current lts)

**Comment by barracuda156** [comment]
What was the last version to support Qt4 by the way?

**Comment by droidmonkey** [comment]
Not keepassxc

**Comment by barracuda156** [comment]
> Not keepassxc

That’s unfortunate. I will see if Qt4-based build can be fixed, at least in a minimal config.

**Comment by droidmonkey** [comment]
Qt-4 has been end of life for almost a decade

KeePassX (the predecessor to this project) is built for Qt-4

**Comment by barracuda156** [comment]
@droidmonkey Yeah, I know that the legacy app was for Qt4. Unfortunately, Qt5+ is broken for some platforms, while Qt4, regardless of EOL status, works perfectly fine.

**Comment by phoerious** [comment]
The minimum supported Qt version is always the one that comes with the lowest Ubuntu version for which we ship PPA packages.
