### ISSUE TITLE
Keyfile

### ISSUE THREAD

**Issue by git-pull-git** [keepassxreboot/keepassxc#10851]
## Overview
Im using a keyfile for my keepass db, I read on the keepass [docs](https://keepass.info/help/base/keys.html), that I could use any file I wanted, so I choose a random static "system" file so I dont have to backup my keyfile ~20.5kb

![image](https://github.com/keepassxreboot/keepassxc/assets/171478089/4b57f917-078f-422e-a7cd-010730ccbd9b)

## Expected Behavior
No error

## Actual Behavior
![image](https://github.com/keepassxreboot/keepassxc/assets/171478089/b36248c0-fe79-4d62-8337-5bd6df9c31ae)
when I change the keyfile from a generated key to the one mentioned above I got this error, however the keyfile I choose is much longer that the one that keepassXC generates.
Does this mean that my keyfile isn't working properly because its not formatted as a keyfile, or is this just a bug?

KeePassXC - 2.7.8

Operating System: Windows

I also have a question about keepassXC, but I am not sure where to ask it
Can I separately store website favicons so I can have a much smaller DB file?

**Comment by droidmonkey** [comment]
We have that bug fixed for upcoming 2.7.9.

HOWEVER, you should ABSOLUTLEY NOT use a system file for your key file. Those can change at any moment due to system updates and are not random data. Just generate a key file using our generator.

**Comment by git-pull-git** [comment]
> We have that bug fixed for upcoming 2.7.9.
> 
> HOWEVER, you should ABSOLUTLEY NOT use a system file for your key file. Those can change at any moment due to system updates and are not random data. Just generate a key file using our generator.
> 
> And no you cannot store icons outside the kdbx file.

Thanks for the response, the system file is static and wont change, I dont want to give to much away haha

I recognized your username from this video that I watched a few weeks ago :0
https://youtu.be/9AV1Q-JfHpI

**Comment by droidmonkey** [comment]
Big caution to you, bit good luck. If you don't directly control the state of the file then don't use it.

**Comment by git-pull-git** [comment]
Oh ok, I will just use the built in keygen in that case, thank you for making keepassXC, I love it :) will donate

**Comment by droidmonkey** [comment]
Great, and thank you. Just trying to avoid some major heart ache later if your static assumption doesn't hold true.
