### ISSUE TITLE
Build test fails on opensuse 15.4: 40 - testpasskeys (Failed)

### ISSUE THREAD

**Issue by drankinatty** [keepassxreboot/keepassxc#10854]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. opensuse 15.4, gcc 7.5.0, cmake 3.20.4
2.  source rpm from http://download.opensuse.org/repositories/home:/redwil:/15.4/15.4/src/keepassxc-2.7.8-Virt.150400.1.1.src.rpm
3. build from srpm (e.g. `rpmbuild -ba keepassxc.spec`)

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

I expected the build to complete and all tests to pass as they have up though 2.7.6 on the local machine where I've build 3 versions since 2.6.6.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

Build completes fine, but `testpasskeys` test Failed, e.g.

```none
********* Start testing of TestPasskeys *********
Config: Using QtTest library 5.15.2, Qt 5.15.2 (x86_64-little_endian-lp64 shared (dynamic) release build; by GCC 7.5.0), opensuse-leap 15.4
PASS   : TestPasskeys::initTestCase()
PASS   : TestPasskeys::testBase64WithHexStrings()
PASS   : TestPasskeys::testDecodeResponseData()
FAIL!  : TestPasskeys::testLoadingECPrivateKeyFromPem() Compared values are not the same
   Actual   (browserMessageBuilder()->getBase64FromArray(signature))                                                     : "MEQCIDV_nMQ2U8S49Il-kFPdyeyZQtC_mWFPgCMuUDXhS_ocAiBONs5q5ik1FasXuKTbREenn6xZF2IdwcdtU2q0gdtiew"
   Expected (QString("MEYCIQCpbDaYJ4b2ofqWBxfRNbH3XCpsyao7Iui5lVuJRU9HIQIhAPl5moNZgJu5zmurkKK_P900Ct6wd3ahVIqCEqTeeRdE")): "MEYCIQCpbDaYJ4b2ofqWBxfRNbH3XCpsyao7Iui5lVuJRU9HIQIhAPl5moNZgJu5zmurkKK_P900Ct6wd3ahVIqCEqTeeRdE"
   Loc: [/home/david/rpmbuild/BUILD/keepassxc-2.7.8/tests/TestPasskeys.cpp(218)]
PASS   : TestPasskeys::testLoadingRSAPrivateKeyFromPem()
PASS   : TestPasskeys::testCreatingAttestationObjectWithEC()
PASS   : TestPasskeys::testCreatingAttestationObjectWithRSA()
PASS   : TestPasskeys::testRegister()
FAIL!  : TestPasskeys::testGet() Compared values are not the same
   Actual   (response["signature"].toString())                                                                          : "MEUCIEq6vdVILOwfXAlQKQBExyPINF5PR2oJA3r71UZBbiyEAiEA-GEpcouqAXvv_icdwoxRQouP8MKZ3sdxAVfjahPfAWw"
   Expected (QString("MEUCIHFv0lOOGGloi_XoH5s3QDSs__8yAp9ZTMEjNiacMpOxAiEA04LAfO6TE7j12XNxd3zHQpn4kZN82jQFPntPiPBSD5c")): "MEUCIHFv0lOOGGloi_XoH5s3QDSs__8yAp9ZTMEjNiacMpOxAiEA04LAfO6TE7j12XNxd3zHQpn4kZN82jQFPntPiPBSD5c"
   Loc: [/home/david/rpmbuild/BUILD/keepassxc-2.7.8/tests/TestPasskeys.cpp(448)]
PASS   : TestPasskeys::testExtensions()
PASS   : TestPasskeys::testParseFlags()
PASS   : TestPasskeys::testSetFlags()
QWARN  : TestPasskeys::testEntry() QObject::connect(MainWindow, BrowserService): invalid nullptr parameter
QWARN  : TestPasskeys::testEntry() QObject::connect(MainWindow, BrowserService): invalid nullptr parameter
QWARN  : TestPasskeys::testEntry() QObject::connect(MainWindow, BrowserService): invalid nullptr parameter
PASS   : TestPasskeys::testEntry()
PASS   : TestPasskeys::testIsDomain()
PASS   : TestPasskeys::testRegistrableDomainSuffix()
PASS   : TestPasskeys::testRpIdValidation()
PASS   : TestPasskeys::testParseAttestation()
PASS   : TestPasskeys::testParseCredentialTypes()
PASS   : TestPasskeys::testIsAuthenticatorSelectionValid()
PASS   : TestPasskeys::testIsResidentKeyRequired()
PASS   : TestPasskeys::testIsUserVerificationRequired()
PASS   : TestPasskeys::testAllowLocalhostWithPasskeys()
PASS   : TestPasskeys::cleanupTestCase()
Totals: 21 passed, 2 failed, 0 skipped, 0 blacklisted, 33ms
********* Finished testing of TestPasskeys *********

      Start 41: testurltools
38/41 Test #41: testurltools .....................   Passed    0.03 sec
39/41 Test #12: testmodified .....................   Passed    9.87 sec
40/41 Test #18: testautotype .....................   Passed   12.23 sec
41/41 Test  #4: testkdbx4 ........................   Passed   16.39 sec

98% tests passed, 1 tests failed out of 41

Total Test time (real) =  16.40 sec

The following tests FAILED:
         40 - testpasskeys (Failed)
Errors while running CTest
error: Bad exit status from /var/tmp/rpm-tmp.5bME4E (%check)


RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.5bME4E (%check)
```

## Context
[NOTE]: # ( Give us any additional information you may have. )

That's pretty much it. Building on a local opensuse 15 4 install where I've previously built 2.6.6, 2.7.1 and 2.7.6 without issue.

**build options**

```none
%cmake \
  -DKEEPASSXC_BUILD_TYPE="Release" \
  -DWITH_XC_UPDATECHECK=OFF        \
  -DWITH_XC_ALL=ON -DWITH_XC_KEESHARE_SECURE=ON
```

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION
Revision: REVISION

Source and signature verified:

```none
-rw-r--r-- 1 david david  9764860 May  6 05:53 keepassxc-2.7.8-src.tar.xz
-rw-r--r-- 1 david david      488 May  6 05:53 keepassxc-2.7.8-src.tar.xz.sig
```

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: KDE
Windowing System: X11

**Comment by droidmonkey** [comment]
You need to update your botan library. I also don't trust a repos source code delivery, so you should also build directly from our source code.

**Comment by drankinatty** [comment]
Let me try that! 

(side note) Oddly, the `keepassxc-cli` doesn't seem impacted, but using the GUI to generate TOTP codes does. 

I'll report back after botan update.

**Comment by droidmonkey** [comment]
Are you by chance using Botan2? Might be a difference in signature encoding between Botan2 and Botan3. 

```
#ifdef WITH_XC_BOTAN3
            Botan::PK_Signer signer(
                privateKey, *randomGen()->getRng(), "EMSA1(SHA-256)", Botan::Signature_Format::DerSequence);
#else
            Botan::PK_Signer signer(privateKey, *randomGen()->getRng(), "EMSA1(SHA-256)", Botan::DER_SEQUENCE);
#endif
```

**Comment by drankinatty** [comment]
I had botan 2.18 libraries installed (`libbotan` and `libbotan-devel`) the way openSUSE splits them up. I updated to 2.19, and the build went fine:

```none
Wrote: /home/david/rpmbuild/SRPMS/keepassxc-2.7.8-Virt.150400.1.1.src.rpm
Wrote: /home/david/rpmbuild/RPMS/x86_64/keepassxc-2.7.8-Virt.150400.1.1.x86_64.rpm
Wrote: /home/david/rpmbuild/RPMS/noarch/keepassxc-lang-2.7.8-Virt.150400.1.1.noarch.rpm
```

This caught me by complete surprise. I had even opened a support request with Archlinux gitlab support because the TOTP I was getting from keepassxc 2.7.6 just stopped working a few weeks ago. I'm glad I decided to build 2.7.8 that uncovered this issue. The GUI and CLI were giving 2 different TOTPs -- I'm still not sure I have my head wrapped completely around how that can happen.

But the upgrade of the botan libraries from 2.18 to 2.19 solved this build issue. 

This bug can be closed unless you would like more info which I'm happy to provide. Either way, thank you for your help!

**WAIT, GUI and CLI still giving different TOTP??**

Here is the bizarre part. With 2.7.6 and now with the fresh 2.7.8 with the GUI, I get the following TOTP (times the same to the second):

```none
176393
```
Now from the CLI, I get a completely different TOTP, e.g.

```none
$ keepassxc-cli show -t ~/.config/xxxxx.kdbx -k ~/.config/xxxxx.key "/Internet Sites/accounts/GitLab - Archlinux"
Enter password to unlock /home/david/.config/xxxxx.kdbx:
103475
```

The CLI TOTP is correct, the GUI generated one is not.

What other lib could be messing this up?

**Comment by droidmonkey** [comment]
are you sure you are pulling the same entry? could also be that your CLI environment has the wrong time zone specified.

**Comment by drankinatty** [comment]
Oh yes, I'm very sure I'm pulling the same entry, same database, I've watched the countdown and tried this 10 times. This is really odd. I only have one `"GitLab - Archlinux"` entry in the database, so there is no chance the CLI and GUI are using different entries. Really strange. And this just started a few weeks to a month ago.

I've also tested with a backup of the database (byte-for-byte identical) same results there. I've done this stuff for more than 2 decades and this one I don't have an explanation for? What else makes sense to check?

Now I have NOT rebooted since changing `libbotan` -- so if that is cached/held in memory that may be it. Give me a sec.

**Comment by droidmonkey** [comment]
Botan isn't involved in TOTP generation, only two ingredients to that cake: Secret Code and Time. You must have a disparity in the time of your CLI environment and the time of your desktop. Check your environment variables.

**Comment by drankinatty** [comment]
Hmmm... I couldn't think of a better test than a terminal and xclock, but time is the same:

![desktop-time-crop](https://github.com/keepassxreboot/keepassxc/assets/9997638/4ad500aa-960f-44d2-89fb-38380cca8f2f)

Glad to know it's a 2-part recipe, but how could I be screwing it up? Any environment var in particular? LOCALE and zoneinfo are correct.

**Comment by droidmonkey** [comment]
hmmm I am at a loss, it is the same code between GUI and CLI

**Comment by drankinatty** [comment]
Well, "the game is afoot" as Sherlock Holmes would say. I'll tear things apart here. Let's go ahead and close this build bug as that is fixed. This openSUSE 15.4 install needs to be wiped and moved to Tumbleweed, but I've avoided the 2 days of config tweaks and re-setup of build environments, etc.. until now.

Thanks again for the discussion and help.
