### ISSUE TITLE
Ubuntu 24.04 font issue

### ISSUE THREAD

**Issue by AlkalineJaunt** [keepassxreboot/keepassxc#10856]
## Current Behavior
Post ubuntu upgrade 23.10 -> 24.04 keepassxc fonts used in menus, dialogs, buttons, etc. have changed to some sort of monospaced thing. See pic.

I have googled my arse off, but I can't find a solution to this. I bet it's some unrelated old file/setting that's surfaced from deep in ~/.config or ~/.cache but I have no idea what it might be.

## Debug info

Installed from:
Types: deb
URIs: https://ppa.launchpadcontent.net/phoerious/keepassxc/ubuntu/
Suites: noble
Components: main

KeePassXC - Version 2.7.8
Revision: f6757d3

Qt 5.15.13
Debugging mode is disabled.

Operating system: Ubuntu 24.04 LTS
CPU architecture: x86_64
Kernel: linux 6.8.0-31-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- Passkeys
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.19.3

![image](https://github.com/keepassxreboot/keepassxc-browser/assets/1776123/aa8a3e1e-e889-4dfc-9855-74abfbca5879)

**Comment by droidmonkey** [comment]
You have some sort of qt variable set or perhaps qt5ct. You should dump your environment variables and look there. Also recommend switching to flatpak.

Looks like you also have the icon with text mode turned on for toolbar. You can change that in application settings.

**Comment by AlkalineJaunt** [comment]
A few more notes in case someone else ends up here:
### Solution
On your advice I found `QT_QPA_PLATFORMTHEME=qt5ct` in my environment.

qt5ct was installed, apparently as a recommended package for Strawberry music player.

qt5ct installs `/etc/X11/Xsession.d/99qt5ct` which does `export QT_QPA_PLATFORMTHEME=qt5ct`

Looking at qt5ct in the GUI, for the first time that I can recall, I see it was showing the font as `noto color emoji` with no obvious way to reset it to something sane. dpkg-reconfigure didn't fix it, so I purged it, and all is good in the world again.
### Kudos
You guys are on the ball! 15 minutes from posting an issue, until you give me a good solution! (Including assigning the issue to the correct project. :man_facepalming:, sorry about that.)  I've been pulling my hair out for two days trying to find my problem.

P.S. I like the words with the icons. Pictures are nearly meaningless to me for some reason.

**Comment by droidmonkey** [comment]
Hah welcome! Qt5ct used to be great, until it wasn't.
