### ISSUE TITLE
Passkey on https://login.microsoft.com 

### ISSUE THREAD

**Issue by aantnn** [keepassxreboot/keepassxc#10869]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
Keepassxc passkeys does not wok on https://login.microsoft.com/consumers/fido/create?mkt=en-US
![keepassxc](https://github.com/keepassxreboot/keepassxc/assets/15718969/fd0623d3-14ce-42f0-95fd-9ec2ee102621)

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Go to https://login.microsoft.com/consumers/fido/create?mkt=en-US

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
KeepassXc should register passkey

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Firefox on Linux ask to plug security device instead. 
KeepassXc popup won't show up

## Context
[NOTE]: # ( Give us any additional information you may have. )
Github/Gitlab/Gmail passkeys work as intended
Also I have trouble with https://demo.yubico.com/webauthn-developers
"message": "'getPublicKeyAlgorithm' called on an object that does not implement interface AuthenticatorAttestationResponse."

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.8
Revision: f6757d3
Distribution: Flatpak

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux (Fedora 40)
Desktop Env: KDE
Windowing System: Wayland

**Comment by droidmonkey** [comment]
Look at the pinned issues
