### ISSUE TITLE
Tray icon's Toggle window command doesn't open the KeePassXC window the first time it's clicked (Gnome)

### ISSUE THREAD

**Issue by jirpok** [keepassxreboot/keepassxc#10860]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
I always have to click the Toggle window command twice to open the KeePassXC window when it's running in Gnome tray. The first click does nothing, only the second click opens the window, meaning I have to click four times instead of twice.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Have KeePassXC minmized in Gnome tray.
2. Click the icon and select Toggle window.
3. Repeat to actually open the window.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Open the window the first time the Toggle window command is clicked.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
See above.

## Context
[NOTE]: # ( Give us any additional information you may have. )
```
GNOME Shell 42.9
```

```
➜  ~ lsb_release -a                                                                                          
Distributor ID: Pop
Description:    Pop!_OS 22.04 LTS
Release:        22.04
Codename:       jammy
```

[NOTE]: # ( Paste debug info from Help → About here )
```
KeePassXC - Version 2.7.8
Revision: f6757d3

Qt 5.15.3
Debugging mode is disabled.

Operating system: Pop!_OS 22.04 LTS
CPU architecture: x86_64
Kernel: linux 6.8.0-76060800daily20240311-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- Passkeys
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.19.1
```

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: Gnome
Windowing System: X11

**Comment by droidmonkey** [comment]
#10700
