### ISSUE TITLE
KeepassXC shows transparant window when starting on Mac Air M3 Sonoma 14.5

### ISSUE THREAD

**Issue by ghost** [keepassxreboot/keepassxc#10862]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Start Mac M3. Install latest version KeepassXC
2. Open KeepassXC
3. Notice that the application is active (dot on icon in dock)
4. Startup window KeepassXC not shown
5. When using Mac OS Stagemanager notice that a transparant window appears with text. The text indicates that this should be KeepassXC window
6. However Keepass losing screen is not presented
7. 

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Starting KeepassXC should show separate window with the login part

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Transparant window and login screen not visible.
However application is started

## Context
[NOTE]: # ( Give us any additional information you may have. )
Behavior appears for some weeks on Mac OS Sonoma 14.5 on en Mac Air M3

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.8
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows/Linux/macOS
Desktop Env: Gnome/KDE/XFCE/Mate/Cinnamon
Windowing System: X11/Wayland

**Comment by droidmonkey** [comment]
https://github.com/keepassxreboot/keepassxc/issues/10757#issuecomment-2126342637
