### ISSUE TITLE
Unable to auto-type to "Windows security" window

### ISSUE THREAD

**Issue by Hakun1n** [keepassxreboot/keepassxc#10861]
## Overview
Unable to "capture" Windows security window for auto-type

## Steps to Reproduce
1. Try to connect to remote server via RDP
2. Get "Enter your credentials" window (see first attached screenshot)
3. Auto-type does not work, KeePassXC cannot "capture" the window title it is not present in drop-down list either (under auto-type windows associations)

Note:
Storing the credentials in Windows vault does not help with active GPO preventing usage of stored credentials (Corporate enforced policy)
With saved credentials user gets the Windows security logon prompt saying "The server's authentication policy does not allow connection requests using saved credentials." (see second attached screenshot)

## Expected Behavior
Be able to auto-type to the windows security windows/prompts? 

## Actual Behavior
![image](https://github.com/keepassxreboot/keepassxc/assets/12685294/c2a92c5d-4234-4138-aeb1-8bb49c5d4a4f)
![image](https://github.com/keepassxreboot/keepassxc/assets/12685294/e1b67db4-2164-47fb-906f-9e972bfaf512)
++ Then getting manual selection list instead
![image](https://github.com/keepassxreboot/keepassxc/assets/12685294/867bb49b-1ebc-476e-a1ec-363790456799)

## Context
Corporate env, forced GPO.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.8
Revision: f6757d3

Qt 5.15.11
Debugging mode is disabled.

Operating system: Windows 10 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.19045

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 10

**Comment by droidmonkey** [comment]
Nothing much we can do there. If it isn't in the list then it's likely an admin elevated prompt or specifically told to be hidden. If the actual typing works, then just search for the correct entry.

**Comment by 0x6d61726b** [comment]
I have exactly the same issue and I am wondering if a fix is possible.
I know that it works with KeePass without admin privileges ...
![screenshot](https://github.com/user-attachments/assets/c835e54d-5ae4-4294-9505-94a71c744626)

**Comment by ThomasClaudinger** [comment]
I have the same problem with the Window Security prompt in Microsoft Edge. I am logging in to a website in Microsoft Edge that authenticate this way. The credentials needed for the website are different from my Microsoft account, so I have to type different username and password.

I see the windows in KeePass auto-type, but when I activate auto-type it doesn't type anything.

Did you find a fix for this?

<img width="495" height="517" alt="Image" src="https://github.com/user-attachments/assets/d6a308e8-c027-4518-aabb-dd0010bfedff" />

<img width="1188" height="713" alt="Image" src="https://github.com/user-attachments/assets/69303b56-689c-4d0e-8b63-ee1b9ec4e506" />

**Comment by phoerious** [comment]
That is KeePass2, not KeePassXC (different product). Most likely the same problem as #12956, though.
