### ISSUE TITLE
Title bar's close button not visible on Wayland (dark theme)

### ISSUE THREAD

**Issue by fwiep** [keepassxreboot/keepassxc#10871]
## Overview
Using KeePassXC in dark theme with GNOME 46 under Wayland, the title bar's Close button (X) is not present. Furthermore, the title bar is rendered in light mode. See 
![keepassxc-titlebar-wayland](https://github.com/keepassxreboot/keepassxc/assets/25373881/8cc67654-6555-4e20-a99f-d130d686134c)

Using GNOME 46 under X11, the button is present and functional. Furthermore, the title bar is rendered dark. See 
![keepassxc-titlebar-x11](https://github.com/keepassxreboot/keepassxc/assets/25373881/cefa3022-dd3c-4fcd-9e5c-eef9ffc3279a)

## Steps to Reproduce
1. Configure a running KeePassXC to use Dark theme.
2. Log off
3. Log in to GNOME session with Wayland
4. Start KeePassXC
5. Observe the light window title bar, having no buttons at all

## Expected Behavior
Both on X11 and Wayland, the window's title bar should have a "Close" button, and be rendered in the chosen theme.

## Actual Behavior
On Wayland, the "Close"-button is not present. The window's title bar is rendered in a light theme.

## Context
The theme rendering is probably already being discussed in #9892 . But the missing Close-button, I did not find in any existing issue.

KeePassXC - Version 2.7.8
Revision: f6757d3

Qt 5.15.13
Debugging mode is disabled.

Operating system: Fedora Linux 40 (Workstation Edition)
CPU architecture: x86_64
Kernel: linux 6.8.11-300.fc40.x86_64

Enabled extensions:
- Auto-Type
- Browser Integration
- Passkeys
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.19.3

Operating system: Fedora Workstation 40 GNU/Linux
Desktop environment: Gnome 46
Windowing system: Wayland

Thanks for looking in to this,
FWieP

**Comment by droidmonkey** [comment]
We don't control the title bar, that is on your compositor, ie gnome

**Comment by beedaddy** [comment]
I can confirm the issue. KeePassXC is the only application here with this issue. (Fedora 40 with GNOME/Wayland)

**Comment by algatern** [comment]
I also experience this issue on Fedora 41 and KeePassXC is the only app with this issue.

As a temporary solution, this small script will fix the issue, but only lasts for the current login session.
`gsettings set org.gnome.desktop.wm.preferences button-layout 'appmenu' && gsettings set org.gnome.desktop.wm.preferences button-layout 'appmenu:close'`

Maybe this gives some insight into the nature of the problem.

**Comment by dani162** [comment]
By any chance the KeePassXC is already started minimized on startup?
I got exactly the same problem, and delaying the start a little bit fixed the problem for me.

<img width="642" height="169" alt="Image" src="https://github.com/user-attachments/assets/a26709ba-dc0f-49a8-8a8d-9c7920b4ab30" />

See https://github.com/keepassxreboot/keepassxc/issues/10058#issuecomment-3365600230
