### ISSUE TITLE
Mouse click wont work

### ISSUE THREAD

**Issue by SweetyA4u** [keepassxreboot/keepassxc#10870]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

Hello, I am new here on github, I dont know if I should erase this text or wrote between **. The issue with keepassXC last version is that when I try to use right click on mouse to do new entry under database, it doesnt work, click wont work, so I was forced to close program then was able to make other subcategory entry. Sometimes work, but also sometimes right click didnt work at all till a reset program again.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. In Root try to click right to make other entry
2. Didnt work so I close program
3. I start again and was able to do new entry, righ click was working

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

Maybe to fix this problem in the futhure :)

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 8.1
Desktop Env:
Windowing System:

**Comment by droidmonkey** [comment]
Not a bug on our end, we don't support windows 8.1

**Comment by SweetyA4u** [comment]
@droidmonkey Okay, sorry :( Can you explain me please, if I wrote right in the post message? I am new here, dont want to break rules, thank you!

**Comment by droidmonkey** [comment]
Right click works fine on all platforms. We also don't directly control that behavior, would probably be a qt thing. Make sure you are using the legacy windows installer.
