### ISSUE TITLE
Error!No logins found. https://…

### ISSUE THREAD

**Issue by bdepaco67** [keepassxreboot/keepassxc#10873]
## Overview
Hello, every time I tried to log, no matter the page, I always get the error: Error!No logins found. https://…

## Steps to Reproduce

1. Try lo fill password to log
2. 
3. 

## Expected Behavior
To worl

## Actual Behavior
Error: Error!No logins found. https://…

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.8
Revision: f6757d3

Qt 5.15.11
Debugging mode is disabled.

Operating system: macOS 14.5
CPU architecture: x86_64
Kernel: darwin 23.5.0

Enabled extensions:
- Auto-Type
- Browser Integration
- Passkeys
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 3.1.1

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS

**Comment by droidmonkey** [comment]
Add an entry with the url you masked out of the error message. Read the user guide for how to use the browser extension.

**Comment by bdepaco67** [comment]
Solved, lot of thanks Jonathan.
Best Regards
Bruno.
