### ISSUE TITLE
Tray Icons & Tray Menu are 'wrong/old' and out of place on autostart

### ISSUE THREAD

**Issue by MPE2016** [keepassxreboot/keepassxc#10878]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
If I autostart Keepassxc  the tray icon is wrong and the menu is old and out of place. See Screenrecording. TO be honest I'm not even 100% that this is caused by Keepassxc but I have to start somewhere. 

[Schermopname van 2024-06-10 12-30-52.webm](https://github.com/keepassxreboot/keepassxc/assets/15818884/66cc48ee-017a-458e-a3f7-4e00ef42c874)

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Use autostart option in options menu
2. Log in 

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
I expected the tray icon and menu to be using the latest icon and the menu in the right place.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Tray Icon is old and menu is old and in the wrong place.

## Context
[NOTE]: # ( Give us any additional information you may have. )
Keepassxc 2.7.8

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.8

[NOTE]: # ( Pick choices based on your environment )
Operating System: Manjaro Linux 24.0.1-240529
Desktop Env: Gnome
Windowing System: Wayland

**Comment by droidmonkey** [comment]
This is 100% a gnome problem. Please redirect to them.
