### ISSUE TITLE
Error while reading the database: HMAC mismatch - PW correct

### ISSUE THREAD

**Issue by alespool** [keepassxreboot/keepassxc#10889]
## Overview
![image](https://github.com/keepassxreboot/keepassxc/assets/68588737/fd81e617-6fb9-4cbc-ad1a-ff316a66c24e)

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Open KeePassXC
2. Insert PW
3. Get error in screenshot

## Expected Behavior
Hello, I am not an expert here and I saw some users already reported similar issues so sorry if this is repeated. I have this database, and I try to insert the password which I am 100% confident I am inputting correctly because I have it written down. But it doesn't open the vault, still. I get this error, and I am afraid the database has been corrupted.

How can I solve this? Are there any other programs I can try to open this database with, maybe to cross-check if the password really is wrong? 

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.8
Revision: f6757d3

Qt 5.15.13
Debugging mode is disabled.

Operating system: Fedora Linux 40 (KDE Plasma)
CPU architecture: x86_64
Kernel: linux 6.8.11-300.fc40.x86_64

Enabled extensions:
- Auto-Type
- Browser Integration
- Passkeys
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.19.3

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: KDE
Windowing System: Wayland

**Comment by droidmonkey** [comment]
>  I am 100% confident I am inputting correctly because I have it written down

You either wrote it down wrong or are reading it wrong (like using a zero instead of O). If you are using non ascii characters (like letters with umluts), then you have to type them with the password visible (qt bug).

**Comment by alespool** [comment]
@droidmonkey hey, no I tried like you said with visible characters but I am still blocked out. Is there any way to recover the data? I know with the original KeePass there was something with headers and recovery, not sure with KeePassXC

**Comment by alespool** [comment]
I searched around, found on KeePass' original website it mentions recovery: 

![image](https://github.com/keepassxreboot/keepassxc/assets/68588737/3a2c65e6-edf4-4373-95a3-ba40a44bfbbc)

Does this work with KeePassXC as well? I tried to open my file with a Hex editor, and the first lines of the header were the same as those shown in the screenshot.

**Comment by droidmonkey** [comment]
If you don't know your password then there is nothing that can be done. You can keep trying variants.

**Comment by alespool** [comment]
I'm politely trying to solve my issue, I already told you I know the password is right. Just say you don't know.

**Comment by droidmonkey** [comment]
You do not have your password right, otherwise you wouldn't be posting here. I'm not being flippant, just the reality of the situation. 

Let's just say your database is precisely corrupted to show this error, which is extremely unlikely. Even in that case there is no recovery possible due to your encryption parameters being totally wrong.

**Comment by Arthur-Zestco** [comment]
Please excuse the necrobump - I came to this issues section totally convinced that a software issue (recent update) was causing my HMAC Error. I had rebooted, reinstalled a previous version, and after listening to the developer repeat 'typing the password wrong' so many times I _finally_ realised that I had a different keyboard layout selected on my PC. Yes I was typing the password right, but the keyboard was reading it wrongly! After setting the keyboard layout, I was magically back into my key safe. Thanks for your hard work @droidmonkey

**Comment by droidmonkey** [comment]
That'll do it, lol
