### ISSUE TITLE
Global Auto-type when minimized to tray in Windows + Yubikey: no prompt to touch the key (appears stalled)

### ISSUE THREAD

**Issue by arigit** [keepassxreboot/keepassxc#1088]
Starting with KeepassXC on Windows minimized to tray and locked. I use keepassxc with Yubikey challenge/response, configured to wait for a "touch" before responding.

Then invoking auto-type with ctrl-alt-a, keepassxc displays a password prompt
The prompt includes the Challenge/response option selected, and the yubikey detected, all as expected.

After entering the password and hitting enter, windows displays the circular throbber and keepassXC appears stalled, there is no prompt anywhere asking to touch the key.

After touching the key, all proceeds as normal. 

## Expected Behavior
There should be a prompt somewhere (inline / blue ribbon message?) asking to touch the key, same as what happens when opening up keepassxc for the first time.
"Please touch the button in your YubiKey!"

## Current Behavior
After invoking auto-type and entering the password, keepassXC appears to stall forever 

## Possible Solution
add an inline prompt in a blue ribbon prompting to touch the key, as is done when keepassxc is first invoked.
Message: "Please touch the button in your YubiKey!"

## Steps to Reproduce (for bugs)
1. On windows 7 64bits, start keepassXC, open your yubikey-protected database, and then minimize keepasXC to tray ensuring it's locked
2. then invoke global autotype (ctrl alt a)
3.In the prompt, enter the correct password and hit enter
4.... see the windows throbber spinning, and nothing happens.
Now if you touch your yubikey, the DB will open normally

## Context
N/A

## Debug Info
KeePassXC - Version 2.2.1
Revision: 2bce9c8add07226e9a05e9e0fd0e5e66b236d5b6

Libraries:
- Qt 5.9.1
- libgcrypt 1.8.1

Operating system: Windows 7 SP 1 (6.1)
CPU architecture: x86_64
Kernel: winnt 6.1.7601

Enabled extensions:
- KeePassHTTP
- Auto-Type
- YubiKey

**Comment by phoerious** [comment]
The message widget is part of the KeePassXC main window, but not part of the stand-alone unlock dialog resulting in said behavior.
