### ISSUE TITLE
Invisible Window during the usage of DisplayLink Manager

### ISSUE THREAD

**Issue by antoniorodriguezmoreno** [keepassxreboot/keepassxc#10886]
## Overview
[NOTE]: # ( Give a BRIEF summary about your problem )

When running DisplayLink Manager 1.10.0 and starting KeePass the window is invisible and the UI can not be used.

Note: This issue does not appear on other screens that are connected without the usage of the DisplayLink Manager and the standard Notebook screen.
Also this issue does not appear if keepass is started with the `--allow-screencapture` parameter.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Start DisplayLink Manager and connect to the screens
2. open KeepassXC without any additional parameter

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Window of KeePass is visible

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Window of KeePass is invisible

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.8
Revision: f6757d3

Qt 5.15.11
Debugging mode is disabled.

Operating system: macOS 14.5
CPU architecture: arm64
Kernel: darwin 23.5.0

Enabled extensions:
- Auto-Type
- Browser Integration
- Passkeys
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 3.1.1

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS
Desktop Env: Aqua

**Comment by varjolintu** [comment]
Just start KeePassXC with the `--allow-screencapture` every time?

**Comment by michaelk83** [comment]
#10757

**Comment by droidmonkey** [comment]
Specifically https://github.com/keepassxreboot/keepassxc/issues/10757#issuecomment-2126342637
