### ISSUE TITLE
Add a way to change which entry from keyring is allowed to a program

### ISSUE THREAD

**Issue by siddhpant** [keepassxreboot/keepassxc#10885]
Evolution asks for a key (the first key in the table, it is without a label) which isn't the evolution entry, so I had to use "Allow All and Future" to get Evolution to work.

I'd like to limit its access to the evolution entry but there seems to be no way of modifying the access, there is only reset button.

Version: `keepassxc-full 2.7.7+dfsg.1-3 (Debian Testing)`

**Comment by droidmonkey** [comment]
Please send a bug to evolution since they aren't implementing the secret service protocol correctly.

**Comment by siddhpant** [comment]
Sure, but the request is more general. This was just an immediate example.

**Comment by droidmonkey** [comment]
Perhaps I don't understand your problem, please rephrase it and include screenshots.

**Comment by siddhpant** [comment]
In the following table:

![image](https://github.com/keepassxreboot/keepassxc/assets/25429745/2a861fd0-fce4-4a88-97c0-50d8cb0681d8)

The keys which have been authorized should also be shown, and a way to remove permission for some keys if multiple are allowed.

Well, okay, I agree the last one is a stretch. But it not showing which keys I authorized is not quite ideal since it already knows about it. Maybe I should create a new issue?

(And it seems like Evolution stuff was red herring by my stupidity, but still a way to see which is allowed and remove perms would be great.)

**Comment by droidmonkey** [comment]
This authorizations only apply for the time keepassxc is running. This is a temporary table.

**Comment by siddhpant** [comment]
I know. I don't see how that is related. Also, if someone is using keepassxc as a secret service, it's unlikely they will ever close it, so it's as temporary as a reboot.

**Comment by droidmonkey** [comment]
But if you authorized a specific PID combo, why would you unauthorize it? Why not just not click "remember"?

**Comment by siddhpant** [comment]
Well, there is an existing functionality to show authorised apps and remove authorisation, so I was simply meaning to show which key is authorised or add function over it.

But yeah, you are right this is kinda a stretch.

Thanks for taking your time out!
