### ISSUE TITLE
AutoType omits full stop / period characters (U+002E . FULL STOP)

### ISSUE THREAD

**Issue by vgambier** [keepassxreboot/keepassxc#10883]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
AutoType feature cannot type the period character (U+002E . FULL STOP)
Unlike what I initially suspected, this does NOT appear to be related to the various reports of keyboard layouts messing with KeepassXC. The period gets completely omitted, not replaced, and no other characters that I tested had any sort of issue. This bug is quite cumbersome because pretty much all email addresses have a period in them so AutoType gets a lot of logins wrong.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Create a dummy entry that includes a period in either the username or the password or both.
2. Add a global shortcut for AutoType to enable the feature
3. Hit the shortcut in any text area
4. Look at the output

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
The username/password gets autotyped with the period, e.g.: `user@example.org`

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
The username/password gets autotyped without the period, e.g.: `user@exampleorg`

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.8
Revision: f6757d3
Distribution: Flatpak

Qt 5.15.10
Debugging mode is disabled.

Operating system: KDE Flatpak runtime
CPU architecture: x86_64
Kernel: linux 6.9.3-arch1-1

Enabled extensions:
- Auto-Type
- Browser Integration
- Passkeys
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 3.3.0

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux (Arch Linux x86_64)
Desktop Env: Gnome (GNOME 46.2)
Windowing System: X11

**Comment by droidmonkey** [comment]
What keyboard layout are you using, this is 100% related to that

**Comment by vgambier** [comment]
I'm using French AZERTY (AFNOR)

```
$ cat /etc/vconsole.conf 
KEYMAP=fr
XKBLAYOUT=fr
XKBVARIANT=afnor
```

```
$ localectl status
System Locale: LANG=en_US.UTF-8
               LC_NUMERIC=fr_FR.UTF-8
               LC_TIME=fr_FR.UTF-8
               LC_MONETARY=fr_FR.UTF-8
               LC_PAPER=fr_FR.UTF-8
               LC_MEASUREMENT=fr_FR.UTF-8
    VC Keymap: fr
   X11 Layout: fr
  X11 Variant: afnor
```

I have 3 layouts enabled:
![image](https://github.com/keepassxreboot/keepassxc/assets/38285114/71e12545-8bdd-4c78-8d2d-f99a2c11fd90)

**Comment by droidmonkey** [comment]
You will have to switch to the English layout when using auto-type. This issue is documented in other reports.

**Comment by vgambier** [comment]
That does indeed fix the issue. I did try switching between the two French layouts earlier, but I guess I never tried with the English one. The reports I read were things like "azerty" being typed as "qwerty" - mine literally only affects the full stop character, so I'm confused, because I don't see how any layout could cause this.

Thanks for the help. Is this a new issue? Auto-Type was working perfectly with the same layout on my previous OS. And I'm surprised it only affects full stops. Will this issue remain forever or is there some interest in addressing it?

**Comment by vgambier** [comment]
Ok, I found #9564. For future reference, I can confirm this only occurs when numlock is turned on.

**Comment by droidmonkey** [comment]
Oh great. Yes that was a real doozy

**Comment by wismill** [comment]
@droidmonkey This issue ought to be fixed though. I wrote [some guidance](https://github.com/keepassxreboot/keepassxc/issues/9564#issuecomment-1635861680) a year ago.

**Comment by bcag2** [comment]
Same issue under my laptop under Ubuntu 24.04 with keepassxc v2.7.6 (not snap or flatpak), with french BÉPO keyboard (french dvorak). And same workaround, turn off numlock.
