### ISSUE TITLE
Opening KeePassXC triggers udev REMOVE event on YubiKey

### ISSUE THREAD

**Issue by robin-checkmk** [keepassxreboot/keepassxc#10888]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
Starting with KeePassXC 2.7.8, whenever I open KeePassXC, it triggers an udev REMOVE event.
I have set up my system, so that when I remove my YubiKey, it locks the screen.
Hence, opening KeePassXC licks my session.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Configure your system as outlined in "Context".
2. Start KeePassXC.
3. See locked screen.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Nothing should happen.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
YubiKey gets removed and reconnected.

## Context
[NOTE]: # ( Give us any additional information you may have. )
Config:
```
# cat /etc/udev/rules.d/80-yubikey-lockscreen.rules
ACTION=="remove", ATTRS{idVendor}=="1050", RUN+="/bin/sh -c '/bin/loginctl lock-sessions'"
```
Log:
```
Jun 12 13:16:50 localhost /usr/libexec/gdm-x-session[20607]: (II) event21 - Yubico YubiKey OTP+FIDO+CCID: device removed
```

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.8
Revision: f6757d3

[NOTE]: # ( Pick choices based on your environment )
Operating System: Ubuntu 22.04
Desktop Env: Gnome
Windowing System: X11

**Comment by droidmonkey** [comment]
https://github.com/keepassxreboot/keepassxc/issues/10077#issuecomment-2047444637

**Comment by robin-checkmk** [comment]
I searched and missed. :see_no_evil: Thanks for linking!

**Comment by phoerious** [comment]
This has come up quite often now. I think one should consider submitting a big report to distort to fix their default rule files.

**Comment by thorian93** [comment]
I am not sure, I follow: Who should fix which rules?

**Comment by droidmonkey** [comment]
Whomever is supplying these yubikey rules to lock the screen on remove. They are not correct in that they are too broadly triggered even when merely using the yubikey.

**Comment by thorian93** [comment]
Ah! Gotcha! Well, I have seen several guides, but I will follow up with the ones I can find again. :+1:
