### ISSUE TITLE
Add support for WebDAV

### ISSUE THREAD

**Issue by PYCHBI** [keepassxreboot/keepassxc#10897]
## Summary
I want to put my vault file in a webdav server that can be used for multi-terminal synchronization.
Although now I can enter the URL of the WebDAV server directly from Windows Explorer, it often doesn't work.

## Context
Both the Android APP (Keepass2Android) and the official software on Windows support opening the password vault in webdav, so I hope the XC version will add this feature as well.

**Comment by droidmonkey** [comment]
Remote database support using standard external tools is added for 2.8.0
