### ISSUE TITLE
text inspector

### ISSUE THREAD

**Issue by icf20** [keepassxreboot/keepassxc#10894]
## Summary
my idea is

1 have a new thing in tools menu called text inspector

2 in this new tool you can copy paste text

3 you run the tool

4 the tools checks the text for matches of password or usernames from my database 

5 if it finds any matches it replaces that in the text with something like "removed" 

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )

## Context
why? i think many have f up by posting up logs or configs files with usernames password or api keys in github or any backup system

while this is not perfect if i add API keys like passwords make config backup safer

this also can be used for any type of logs, where u can put IP's in the username and get them removed

**Comment by droidmonkey** [comment]
This is far outside our scope and likely not useful at the scale and integration that would be required to make it useful. Invest in a good secrets detector and hook it up to your git hooks.
