### ISSUE TITLE
Enhancing the Clarity of Shared Entries with KeeShare

### ISSUE THREAD

**Issue by PoisonFrog** [keepassxreboot/keepassxc#10895]
Currently, there are a few caveats with KeeShare that may cause it to not work as expected. The user guide states:
> shared entries moved outside of a shared group are still synchronized

> the merge algorithm is location independent, therefore it does not matter if entries are moved outside of an import group. These entries will be updated nonetheless.

Let's say I'm synchronizing entries with other people under the "Shared" group, but for some reason there is an entry I don't want to share anymore and I move it out of the "Shared" group to a non-shared group and I change the password, most people would expect that entry to no longer be synchronized. However, while the new password won't be exported, the entry that was moved can still be changed by others. If someone else modifies it on their end, their changes will overwrite mine. This behavior is unexpected, and users will only be aware of it if they read the user guide carefully.

### My proposal

I think it would be helpful if KeePassXC added the small shared icon it uses for groups under KeeShare to entries that were moved out of a shared group but are still being shared. This way users would be more aware of the situation.

**Comment by droidmonkey** [comment]
We are refactoring keeshare for 2.8.0 to behave in the expected manner. Lots of issues on here regarding the changes needed.
