### ISSUE TITLE
Documentation missing coverage option

### ISSUE THREAD

**Issue by seatedscribe** [keepassxreboot/keepassxc#1089]
Building on a Linux Mint 18.2.
While coverage packages (gcov, lcov) are correctly reported on the _Generating test coverage statistics_ they are missing in the _Set up Build Environment on Linux_, under the paragraph _Install the optional dependencies_ where only Auto-Type and Yubikey are mentioned. I think one should find all the package dependencies in the same page so as to copy/paste the installation commands for his OS easily.

**Comment by droidmonkey** [comment]
I added the necessary commands directly to the test coverage wiki, where it belongs.
