### ISSUE TITLE
Browser extension - Does not work with Tor or Firefox

### ISSUE THREAD

**Issue by techrivertree** [keepassxreboot/keepassxc#10908]
## Overview
I have the KeepassXC browser extension on both TOR and Firefox. Both browsers have the extension enabled.
In my database, under browser integration, both TOR and Firefox are enabled. Also, under database settings, there no connected databases.

ETA: I added the browser extension to Brave, worked first time.

Neither browser extension will connect to my database. 

## Steps to Reproduce
1. Install Firefox and TOR, install keepassxc browser extension
2. Open up your database, enable browser extension
3. Your database should not connect to the browser extension

## Expected Behavior
The browser extension should connect to the database

## Actual Behavior
Nothing, the extension wont connect to my database

## Context
KeePassXC - unknown
KeePassXC-Browser - 1.9.0.5
Operating system: Linux x86_64
Browser: Mozilla Firefox 115.0 (TOR)

KeePassXC - Version 2.6.6
Revision: 9c108b9

Qt 5.15.3
Debugging mode is disabled.

Operating system: Zorin OS 17.1
CPU architecture: x86_64
Kernel: linux 6.5.0-35-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- libgcrypt 1.9.4

Operating System: Linux (Ubuntu (ZorinOS distro)
Desktop Env: Gnome
Windowing System: Wayland

**Comment by droidmonkey** [comment]
Sounds like you didn't connect the extension to your database. Please follow the directions if that is the case: https://keepassxc.org/docs/KeePassXC_UserGuide#_setup_browser_integration

Otherwise, head over to the troubleshooting guide or search the issue board. Plenty of examples of all the pitfalls with Linux and browsers. https://github.com/keepassxreboot/keepassxc-browser/wiki/Troubleshooting-guide

**Comment by techrivertree** [comment]
I read over all of that. Still does not connect.

**Comment by droidmonkey** [comment]
Ok, then what did your strace output produce?

**Comment by techrivertree** [comment]
I uninstalled the extension and installed via flatpack. Version went from 2.6.6 to 2.7.8. Still cannot connect

though it works first time with Brave.

Please excuse my noob knowledge, what is a "strace output"?

**Comment by droidmonkey** [comment]
You didn't follow the troubleshooting guide if you are asking that question

**Comment by techrivertree** [comment]
On firefox I went to "about:debugging" but there was no option to "Enable add-on debugging".

Since the browser extension works great with Brave, my KeepassXC install is good.

I did inspect the browser extension, here is the browserAction.js

![Screenshot from 2024-06-17 21-27-12](https://github.com/keepassxreboot/keepassxc/assets/69227859/d8521cd3-863d-48aa-a7ea-b7ed761f292d)


![Screenshot from 2024-06-17 21-26-10](https://github.com/keepassxreboot/keepassxc/assets/69227859/e2a486dc-20a2-4403-b38c-9b06823f54d4)
