### ISSUE TITLE
The tag editor cannot directly input Chinese characters

### ISSUE THREAD

**Issue by benzBrake** [keepassxreboot/keepassxc#10909]
## Overview
When modifying a login entry, I tried to add a Chinese label, but the characters entered through the sogou pinyin input method could not be entered into the label input box.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Modify a login entry
2. Locate the tags input box
3. Try to add chinese label through sogou pinyin input method

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
The Chinese characters I input can be added to the label input box

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
The entered Chinese characters cannot be added to the label input box

## Context
[NOTE]: # ( Give us any additional information you may have. )
Chinese must be input using an input method. [Sogou Pinyin input](https://shurufa.sogou.com/) method is used by many people in China.
Currently I can input chinese in some where else, and copy the characters to label input box, it works

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.8
Revision: f6757d3

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows
Desktop Env: 
Windowing System:

**Comment by droidmonkey** [comment]
Duplicate report
