### ISSUE TITLE
Keepassxc window fails to open from tray (sometimes)

### ISSUE THREAD

**Issue by pwilliamson19** [keepassxreboot/keepassxc#10902]
## Overview
When I click on the tray icon the Keepassxc window fails to appear - nothing visible happens. If I click 3 times in total (ie 2 additional clicks) in the tray icon the window opens successfully. It happens occasionally but I have not worked out exactly how to reproduce it. It seems very inconsistent. Yesterday it was happening a lot - today much less.

## Steps to Reproduce
Minimise window to tray.
Click on tray icon
Do some work in Keepassxc
Minimise to tray.
Click on tray icon. Sometimes 1 click will open the window, sometimes it needs 3 clicks.

## Expected Behavior
Window should open every time with a single click

## Actual Behavior
Sometimes needs 3 clicks to open window,
It never fails completely to open the window - it always appears after max of 3 clicks
This is an irritation but it is infuriating at times, especially if I'm in the middle of doing something complicated.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2..6.6 system package.
 Also happened with a more recent Flathub version when I tried it some time ago - can't remember the version 

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux Mint 21.3
Desktop Env: Cinnamon 6.0.4

**Comment by droidmonkey** [comment]
This isn't something broken on our end. Did it start happening recently?

**Comment by pwilliamson19** [comment]
As far as I can remember it's always been like this. It certainly isn't recent. It doesn't happen with any other windows which are minimised either to the main panel or the task bar.

**Comment by droidmonkey** [comment]
I cannot replicate this at all using Mint 21.3 and Cinnamon 6.0.4, using AppImage KeePassXC (which shouldn't matter here).


https://github.com/keepassxreboot/keepassxc/assets/2809491/e6eab922-1be7-4f40-b52b-d901e3a693f1

**Comment by hramrach** [comment]
There is possibility the window is shown on another desktop, and then to show it it needs to be hidden first - see the discussion in #10700 That would, however, require 2 clicks, not 3.
