### ISSUE TITLE
{CLEARFIELD} not working on Windows 11 either (with SQuirreL)

### ISSUE THREAD

**Issue by pstueck** [keepassxreboot/keepassxc#10916]
## Overview
See also #10006 &hellip; that was not a sole Linux issue.
Also, I can verify that SQuirreL definitely does not like anything like `Ctrl-Home`/`Ctrl-Shift-End` (for the login dialog) &hellip; just the control-free keys will work.
On the other hand, `Ctrl-A` is working fine.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
Please see #10006 &hellip; besides being Windows 11 now, it's all the same

## App/System information
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.8
Revision: f6757d3

Qt 5.15.11
Debugging mode is disabled.

Operating system: Windows 11 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.22631

Enabled extensions:
- Auto-Type
- Browser Integration
- Passkeys
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 3.1.1

[NOTE]: # ( Pick choices based on your environment )
Operating System: Microsoft Windows 11 Pro
Version: 10.0.22631 Build 22631

**Comment by droidmonkey** [comment]
CTRL + A doesn't work everywhere for windows. We can't win. Just use `^a{DELETE}` instead of clearfield

**Comment by pstueck** [comment]
Weeeeelll &hellip; personally prefer `{HOME}+{END}`, especially as `^a` seems not toooooo reliably working everywhere either.

As you said &hellip; one cannot win everywhere 😢
