### ISSUE TITLE
Add Security Column to entries

### ISSUE THREAD

**Issue by ju2wheels** [keepassxreboot/keepassxc#1091]
I would like to be able to see/track at a glance which entries I have enabled 2FA on and also which type of 2FA (SMS, Authenticator, Email, or Security Key (ie Yubikey)). Having a column in addition to just the entry name, username, and URL for this would be extremely useful as 2FA becomes more common place.

## Expected Behavior
I would like a security column on entry view.

## Current Behavior
The best we can currently do is track this via entry notes but its not readily viewable in a single view for all entries.

## Context
2FA is becoming more common place, and tracking which accounts use which type of 2FA so you know whether you need your phone, email, or security key before hand is useful.

**Comment by affinityv** [comment]
Why not just choose a "special" icon for the entry?  That would be a simple and quick solution.

**Comment by droidmonkey** [comment]
Interesting idea

**Comment by ju2wheels** [comment]
@affinityv how would you choose a single icon for an entry that supports more than one 2FA type (my Gmail for example supports SMS, Authenticator, AND Yubikey... simultaneously). A single icon wouldnt suffice, but a column whose contents can clearly list these in some way, be it by text or icon is better.

**Comment by affinityv** [comment]
You could have multiple custom icons, choose one for each entry that suits.  Extra columns is also a very good idea though, but you can probably achieve your goal just with the use of icons.

**Comment by sts10** [comment]
I had been thinking it'd be nice to have a "Password Quality" column that, for each entry, provides a colored dot of the entry's password strength (red for "poor", light green for "good", dark green for "excellent", etc.). I think it would kind of work towards a basic password audit feature (context: I have hundreds of entries, need to quickly find weak passwords-- likely the ones that did not generate randomly using KeePass, for whatever reason). And wouldn't require any extra work from the user.

Maybe this proposed "Security Column" could include an indicator of "Password Quality", via color or some other creative means?

**Comment by TheZ3ro** [comment]
@sts10 Your proposal is duplicate of #551 

This issue is for adding a label for 2FA type, manually set by the user acting just like a reminder

**Comment by sts10** [comment]
Ah my bad. Happy to see it's on the list for 2.3.0!

**Comment by droidmonkey** [comment]
This was added to 2.4.0 with a TOTP column.

**Comment by ju2wheels** [comment]
@droidmonkey I just tried out 2.4.1 with the TOTP column and unless im missing something isnt that a bit different than what this ticket was talking about? The TOTP column is strictly to support generating TOTP from within KeepassXC whereas this request was for a column strictly related to security where we can track if the account record uses/requires/supports 2FA SMS, 2FA Email, 2FA TOTP, 2FA recovery codes, 2FA U2F, or 2FA Phone Call.

I guess Ill have to replicate this with Attributes but it would have been nice to have a dedicated column at a glance.

**Comment by droidmonkey** [comment]
I misunderstood your original request. My recommendation is to simply add which 2FA you are using in the entry's title. You could also place it in the beginning of the entry's notes and show the notes column.
