### ISSUE TITLE
UI layout bug in Database Settings>Security>Encryption settings

### ISSUE THREAD

**Issue by bytequill** [keepassxreboot/keepassxc#10922]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Open a database in the (Windows) app
2. Open the settings of tthe database an navigate to: Security>Encryption settings

## Expected Behavior
No scrollbar to be present

## Actual Behavior
A scrollbar appears in an odd place breaking up existing UI elements. The scrollbar is also non-functional and does not serve any apparent function

## Context
![The bug in my environment](https://github.com/keepassxreboot/keepassxc/assets/155390357/8df724b2-85cb-412c-91fc-bfe6820dbef4)

KeePassXC - Version 2.7.8
Revision: f6757d3

Operating System: Windows

**Comment by droidmonkey** [comment]
That is a qt anomaly that we don't control, unfortunately. This is a bug with the overall ui framework that sometimes happens.
