### ISSUE TITLE
Application is Crashing after the installation with latest version 2.7.9 in windows 10 and 11

### ISSUE THREAD

**Issue by metaad** [keepassxreboot/keepassxc#10926]
# Discription
During the fresh installation and updating from the old release on windows 10 and 11. The latest application is not launching.

## Steps to Reproduce
# 
1.Download the application from this link https://github.com/keepassxreboot/keepassxc/releases/download/2.7.9/KeePassXC-2.7.9-Win64.msi 
2. Installed the application in GUI mode.
3. Application get installed.
4. When trying to launch the application then the application starts in task manager but get terminated in few seconds. 

### Application is getting terminated as soon as its get launched.

KeePassXC - 2.7.9 with the file name "KeePassXC-2.7.9-Win64.msi" is having the issue 

Operating System: Windows10  and Windows 11

**Comment by Airwolf1544** [comment]
Hi,
also reported here: https://github.com/keepassxreboot/keepassxc/issues/10925
Simply update VC Redist.

**Comment by metaad** [comment]
thanks

**Comment by metaad** [comment]
thanks for your response
