### ISSUE TITLE
longshot: share encrypted archive per bluetooth

### ISSUE THREAD

**Issue by jonnytest1** [keepassxreboot/keepassxc#10920]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
for work we get credentials for wifi - which i usually just put into my keepass database
but without wifi i cant download the db on the laptop

=> so the idea would be to share it per bluetooth to the laptop from my smartphone

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )
--

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
--

**Comment by droidmonkey** [comment]
You can do that directly with the operating system.

**Comment by jonnytest1** [comment]
how do i access a file that only exists in the app cache ?

**Comment by droidmonkey** [comment]
I have no idea what you are referring to. There are plenty of tutorials online on how to sync files using Bluetooth.
