### ISSUE TITLE
Testsuite failure on debian 11

### ISSUE THREAD

**Issue by darix** [keepassxreboot/keepassxc#10923]
https://build.opensuse.org/package/live_build_log/security:keepassxc/keepassxc/Debian_11/x86_64

works on debian 12 and other distros

https://build.opensuse.org/package/show/security:keepassxc/keepassxc

**Comment by droidmonkey** [comment]
The version of Botan on Debian 11 produces different signatures then more recent versions. We are bumping the minimum required version for 2.8.0.

**Comment by darix** [comment]
so I should disable the debian 11 builds then? i guess when you bump the requires to 2.8.0?

though isnt it more a type thingie of qstring vs normal string? from a quick glance the strings itself look the same

ah no the output is just confusing.

**Comment by droidmonkey** [comment]
No this is a botan issue. I was trying to find the previous post about it but failed.
