### ISSUE TITLE
Standard "OK"/"Cancel"/"Apply" button text without translation

### ISSUE THREAD

**Issue by bovirus** [keepassxreboot/keepassxc#1093]
In many window appear the standard button

OK
Apply
Cancel

in English without translation.
Please add it to the language file or use the standard QT resource to translate them.

**Comment by phoerious** [comment]
I noticed that, too. I actually have no idea why they are not being translated.  KeePassXC loads the qt_* locales, which at least used to contain those strings. But also loading the newer qtbase_* locales seems to have no effect.

**Comment by bovirus** [comment]
I checked ion other QT projects that you have to modify the source to load addition translation resources by standard qt language files (like for OK/Apply/Cancel button text).
I will check and I will post the info for that.

**Comment by bovirus** [comment]
@phoerious 
Info

http://doc.qt.io/qt-5/internationalization.html

https://wiki.qt.io/How_to_create_a_multi_language_application

http://doc.qt.io/qt-5/qtranslator.html

**Comment by phoerious** [comment]
I know those resources and we do that already.

**Comment by bovirus** [comment]
It's quite strange because other projects based on Qt (ex. DVDFab) translated also OK/Cancel/Discard/ etc,.

Probably depend how to open the window and the text button.

**Comment by chuinul** [comment]
Qt translations should be loaded by:
```C++
bool Translator::installQtTranslator(const QString& language)
{
    ...
    if (qtTranslator->load(QString("%1/qtbase_%2").arg(QLibraryInfo::location(QLibraryInfo::TranslationsPath), language))) {
    ...
}
```

On my system (Linux Mint 18.3), I had to install the extra package qttranslations5-l10n for the translation files to be created in `/usr/share/qt5/translations/`. Now, the standard OK/Cancel/Apply buttons are properly translated.

**Comment by bovirus** [comment]
@chuinul 

Thanks.

@phoerious 

could you please try to implement it? Thanks.

**Comment by phoerious** [comment]
It's not a problem with missing packages. I have the same problem on my Arch system and I definitely have all the packages installed. The locale files exist, but the buttons are still untranslated when I choose a language other than English. This must be a Qt bug.

**Comment by chuinul** [comment]
Well, on my desktop, the executable comes from the AppImage. It is statically linked. Whether I have that package (`qttranslations5-l10n`) installed or not has no effect.

However, when I build within a VM (and dynamically link), installing the missing package fixes the issue (see screenshots below). I suppose that it remains true when installing keepassxc from the ppa. But I cannot test since it crashes on my machine (because of a Qt bug we discussed once on freenode).

![image](https://user-images.githubusercontent.com/25458217/34178389-4671efaa-e507-11e7-9748-653383913ff3.png)

![image](https://user-images.githubusercontent.com/25458217/34178445-8838b5cc-e507-11e7-942d-727fd5b42a09.png)

**Comment by phoerious** [comment]
I tested it on Windows, seems to work fine there. I know I had problems with it on my Arch workstation, though. Perhaps it's a packaging problem after all.

**Comment by phoerious** [comment]
Okay, another insight. It only works on Windows when I build it from source. The packaged release is missing stuff again.

**Comment by phoerious** [comment]
I found the problem. We only try to load qtbase translations from the default location. On Linux there may actually be translations if the correct packages are installed, but on other systems that's probably not the case. I created a PR to bundle qtbase translations for systems that don't have them installed anyway.

**Comment by bovirus** [comment]
@phoerious 

I tested the version 2.2.4 but the problem is in place.
Will be the problem fix in next release?

**Comment by TheZ3ro** [comment]
@bovirus Yes, this has been merged with #1307 that is targeted to release v2.3.0

**Comment by xesarni** [comment]
@TheZ3ro It hasn't been fixed in the Windows version of 2.3.0.

**Comment by phoerious** [comment]
Which language are you referring to? I checked the ZIP release and it contains all available qtbase translations.

**Comment by xesarni** [comment]
I guess all languages. qtbase files are present indeed but somehow they aren't used.

**Comment by bovirus** [comment]
@phoerious

Is not enough to have KeePAssXC languages and qt-base languages.

You should load both language, but by default qt-sdk load one file at time.

Then you should use qt source code and call for open window (like OK/Apply/cancel) in specifc mode.
