### ISSUE TITLE
Update do not function

### ISSUE THREAD

**Issue by tmoellmann** [keepassxreboot/keepassxc#10939]
Did Update KeePassXC from 2.7.8 to 2.7.9. After, KeePassXC didn't start anymore. I installed it on an Win 11 Pro 23H2 Build 22631.3737

**Comment by phoerious** [comment]
#10925

**Comment by tmoellmann** [comment]
Hi, installing [KeePassXC-2.8.0-snapshot-Win64.msi](https://snapshot.keepassxc.org/latest/KeePassXC-2.8.0-snapshot-Win64.msi) will work. I can start KeePassXC 2.8.0

KeePassXC - Version 2.8.0-snapshot
Build-Typ: Snapshot
Revision: f4b91c1

Qt 5.15.11
Diagnosemodus ist deaktiviert.

Betriebssystem: Windows 11 Version 2009
CPU-Architektur: x86_64
Kernel: winnt 10.0.22631

Aktivierte Erweiterungen:
- Auto-Type
- Browser-Integration
- Passkeys
- SSH-Agent
- KeeShare
- YubiKey
- Schnelle Entsperrung

Kryptographische Bibliotheken:
- Botan 3.1.1

Perhaps, this will help you. If you have a stable version, please tell me. Thanks!

**Comment by droidmonkey** [comment]
@tmoellmann https://github.com/keepassxreboot/keepassxc/issues/10925#issuecomment-2179741873
