### ISSUE TITLE
copy password to clipboard with single click

### ISSUE THREAD

**Issue by foss-** [keepassxreboot/keepassxc#10930]
## Summary
Copying a password from KeePassXC is currently confusing. This proposes to make the process more intuitive and less frustrating by allow to copy the password to clipboard with a simply single click on the password.

## Examples
1Password 7 does the following

1. select entry from list -> details view shows entry details
2. single click on `username`, `password` or any field except for `Notes` will copy field content to clipboard
3. after the single click an overlay bar is shown for 3 seconds informing the user that `Copied to clipboard`

This is simple and straight forward. Would love to see this in KeePassXC.

see also: https://github.com/keepassxreboot/keepassxc/issues/10929

**Comment by droidmonkey** [comment]
Quite literally there is a button on the toolbar that does exactly what you ask. We also don't want to make using clipboard _too easy_ since it is the least secure way of using our application.

**Comment by foss-** [comment]
Hmm. This argument is odd, especially in light of https://github.com/keepassxreboot/keepassxc/issues/10929, where instead of copying some text from the notes field, the password ends up in clipboard.

Wondering if allowing to at least copy username field via single click would make sense.
