### ISSUE TITLE
global search and automatic sizing of results

### ISSUE THREAD

**Issue by coltEli** [keepassxreboot/keepassxc#10933]
First, thank you for making this program, it is making my transition away from windows a little easier.  However, coming from the windows keepass I find search to be cumbersome.

My db is a filthy mess, so when searching for string "cloud" I would like the ability to return global results equivalent to:
t:cloud | u:cloud | p:cloud | url:cloud | n:cloud | attr:cloud | attach:cloud |g:cloud. 
Just give it to me.

As to not disturb functionality for existing users, in settings there could be a checkbox for each column to include in global search (with t prechecked to keep existing functionality). 

Also, could the search table functions "fit to window" or "fit to contents" have radio button functionality. That way the selected method could automatically be called on window resize & after each search query. It is annoying to have to manually resize the table or use the right click menu to manually call these functions after each search. 

Thanks for your time.

**Comment by droidmonkey** [comment]
Welcome! Might I recommend investing an hour or so to cleanup your database entries? That is the only way to fully restore sanity 😄

Your request is captured already here: https://github.com/keepassxreboot/keepassxc/issues/7967 and https://github.com/keepassxreboot/keepassxc/issues/7945

There are many other requests for search enhancement, you can find them using the "feature: search" label.
