### ISSUE TITLE
Ref value in Passkeys not shown

### ISSUE THREAD

**Issue by litcc** [keepassxreboot/keepassxc#10931]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )

Here the username field of passkey does not take the value of the reference.

It should look like in the example

![image](https://github.com/keepassxreboot/keepassxc/assets/13202561/db8ba4e5-f1c1-4423-9fb3-9951d9b66125)

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )

![image](https://github.com/keepassxreboot/keepassxc/assets/13202561/c82d18e9-0517-49a6-8aef-1ae435ea80ad)

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )

**Comment by varjolintu** [comment]
Actually this field should refer to `KPEX_PASSKEY_USERNAME` attribute and ignore the entry's actual username setting. If the entry has a different username than the attribute (situation where an entry also contains a passkey), incorrect username will be shown in the list.
