### ISSUE TITLE
and/or configuration for database unlock

### ISSUE THREAD

**Issue by Landless-Victory** [keepassxreboot/keepassxc#10935]
## Summary
Would like the ability to and/or the unlock configuration

## Examples
Forgot your OnlyKey but you know your password and have your encrypted passkey? No problem!

## Context
I do a lot of remote support at work where I can't pass my Onlykey through. It would be able to select what factors I can provide at the time (minimum 2) rather than specifically the factors I set up initially all at once.

**Comment by droidmonkey** [comment]
Duplicate of several other requests, please search
