### ISSUE TITLE
hidden keyfile input has gone

### ISSUE THREAD

**Issue by bits-fritz** [keepassxreboot/keepassxc#10944]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

Hidden input of keyfile path has gone with version 2.7.9 
(at least could not find a preference option to get it back)

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. open keepassxc - open database
2. try to enter path for secret keyfile via keyboard (with hidden chars)
3. only link for file picker appears wich let everyone see the path you select (for example when sharing your desktop at beamer, video conference etc..
4. search preference for altering the behaviour fails

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

joice for either entering the path via keyboard or selecting via file picker should appear as did up to version 2.7.8

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

only file picker possible to enter secret keyfile

## Context
[NOTE]: # ( Give us any additional information you may have. )

This makes it impossible to keep the path of the secret keyfile secret in certain environments.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.9
Revision: 8f6dd13

Qt 5.15.14
Diagnosemodus ist deaktiviert.

Betriebssystem: Arch Linux
CPU-Architektur: x86_64
Kernel: linux 6.9.5-arch1-1

Aktivierte Erweiterungen:
- Auto-Type
- Browser-Integration
- Passkeys
- SSH-Agent
- KeeShare
- YubiKey
- Secret-Service-Integration

Kryptographische Bibliotheken:
- Botan 3.4.0

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: XFCE
Windowing System: X11

**Comment by phoerious** [comment]
The name and location of the key file isn't secret and the security of your database should not depend on it. But if you let KeePassXC remember the key file, it'll show up as **** next time if you have the option to mask the path enabled.
