### ISSUE TITLE
macOS: Password text cursor blinks on startup without focus

### ISSUE THREAD

**Issue by MonkeyBars3k** [keepassxreboot/keepassxc#10946]
## Overview
It's poor UX to have a blinking cursor when any field does not actually have focus and can't be typed into. macOS (and probably other OS) convention dictates no text cursor at all. This is also a security problem since user may mistakenly type KPXC database password into another window which does have focus.

## Steps to Reproduce
1. Open a database
2. Close KeePassXC
3. Click into another window's form field
4. Reopen KeePassXC

## Expected Behavior
KeePassXC opens without any cursor in the password field

## Actual Behavior
KeePassXC opens with a blinking cursor in the password field

## Context
macOS 12.7.5

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.4
Revision: 34a78f0

Qt 5.15.2
Debugging mode is disabled.

Operating system: macOS 12.7
CPU architecture: x86_64
Kernel: darwin 21.6.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
- libgcrypt 1.9.1

**Comment by droidmonkey** [comment]
You are running an extremely old version of keepassxc

**Comment by MonkeyBars3k** [comment]
Oops! Sorry about that.

But latest version solves this issue by stealing focus. Is there a way to prevent that?

**Comment by droidmonkey** [comment]
Minimize on startup? I really don't understand your problem to be honest.

**Comment by MonkeyBars3k** [comment]
Stealing focus is generally considered insecure and inconvenient as one may be in the middle of typing in another window.

**Comment by droidmonkey** [comment]
You can prevent that behavior right now by enabling minimize on startup. We have an open issue already to remove the focus on start behavior.
