### ISSUE TITLE
Ability to set the UI Font Size via Settings in macOS

### ISSUE THREAD

**Issue by notDavid** [keepassxreboot/keepassxc#10941]
## Summary
Add the ability to set the GUI Font Size via KeePassXC Settings in macOS

## Context
I read about `QT_SCALE_FACTOR` in the [Docs](https://keepassxc.org/docs/KeePassXC_UserGuide#_command_line_options) and tried just about anything to set the font size, including [this](https://github.com/keepassxreboot/keepassxc/issues/6822#issuecomment-1902228813), but nothing seems to work.
I can not, for the life of me, figure out how to increase the small font size in macOS, on my Macbook.

Please consider providing an option via the GUI to set the font size. Or, if there is another "uncomplicated" way, please add it to the documentation.

Thank you!

**Comment by droidmonkey** [comment]
Duplicate
