### ISSUE TITLE
Showing incorrect TOTP strings compared to gopass on the same machine with same token

### ISSUE THREAD

**Issue by kode54** [keepassxreboot/keepassxc#10949]
## Overview
KeepassXC 2.7.9 is returning incorrect TOTP tokens for one of my password entries, I haven't checked any others recently. Gopass manages to return the correct TOTP tokens every time, using the same exact token string.

## Steps to Reproduce
1. Import a SHA-1 6 digit token from other databases.
2. Attempt to generate TOTP token.

## Expected Behavior
Token should match Gopass, which is returning correct tokens.

## Actual Behavior
KeepassXC returns incorrect tokens, every time.

## Context
The token is in this format:

```
otpauth://totp/Site%20Name:username?secret=blah&digits=6&algorithm=SHA1&issuer=Site%20Name&period=30
```

KeePassXC - Version 2.7.9
Revision: 8f6dd13

Qt 5.15.14
Debugging mode is disabled.

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 6.9.5-1-cachyos

Enabled extensions:
- Auto-Type
- Browser Integration
- Passkeys
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 3.4.0

Operating System: Linux
Desktop Env: KDE
Windowing System: Wayland

**Comment by droidmonkey** [comment]
Sync your computer time

**Comment by kode54** [comment]
My time is synced, I already stated that it worked with a different program on the same computer.

**Comment by droidmonkey** [comment]
The other program pulls time directly from the internet. Sync your time.

**Comment by kode54** [comment]
My time is synced within 0.001s according to time.is. Maybe it drifted by two whole minutes before whenever it must have synced, since it seems to be working now. I guess this machine's clock is totally broken.

**Comment by droidmonkey** [comment]
You are welcome, I guess...
