### ISSUE TITLE
KeepassXC doesn't start after upgrade to version 2.7.9

### ISSUE THREAD

**Issue by krehberger** [keepassxreboot/keepassxc#10943]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
After upgrade to the newest version 2.7.9 KeepassXC doesn't start anymore.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1.  Start KeepassXC with a double klick.
2. 
3. 

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
KeepassXC Login screen should be shown for enterning login information

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
No login screen occurs.

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.9 - Windows 64
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 11

**Comment by digihash** [comment]
I have the same problem on Windows 11

**Comment by droidmonkey** [comment]
https://github.com/keepassxreboot/keepassxc/issues/10925#issuecomment-2179741873
