### ISSUE TITLE
Keybindings are ignored in GNOME 46

### ISSUE THREAD

**Issue by ghost** [keepassxreboot/keepassxc#10945]
## Overview
In GNOME 46.2, most keybindings are outright ignored by KeePassXC. That's strange because `<C-b>`, `<C-c>`, and `<C-,>` work, but others such as `<C-t>`, `<C-S-t>`, and `<C-S-,>` do not. I have tried both the Flatpak and package manager versions.

Could this issue be caused by Qt's `text-input-v3`? When I set the environment variable `QT_WAYLAND_TEXT_INPUT_PROTOCOL=zwp_text_input_v2`, the keybinds start to work again..

## Context
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.8
Revision: f6757d3

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: Gnome 46.2
Windowing System: Wayland

**Comment by droidmonkey** [comment]
What is C-t, etc?

> Could this issue be caused by Qt's text-input-v3? When I set the environment variable QT_WAYLAND_TEXT_INPUT_PROTOCOL=zwp_text_input_v2, the keybinds start to work again.

If that fixes it, then this has nothing to do with keepassxc. Report to upstream or Qt.
