### ISSUE TITLE
Add Clipboard Copy Placeholder to KeePassXC Auto-Type

### ISSUE THREAD

**Issue by TheButterbrotMan** [keepassxreboot/keepassxc#10948]
## Summary
The proposed feature is to enhance KeePassXC's Auto-Type functionality by introducing a new placeholder that allows copying specific entry fields (such as TOTP or password) to the clipboard as part of the Auto-Type sequence. This would be implemented using a syntax like `{clipboard:fieldname}`, for example, `{clipboard:totp}` to copy the TOTP code to the clipboard.

## Examples
A mock-up of how this feature might look in the Auto-Type sequence editor:

```
{USERNAME}{TAB}{PASSWORD}{ENTER}{clipboard:totp}
```

This sequence would:
1. Enter the username
2. Tab to the next field
3. Enter the password
4. Press Enter
6. Copy the TOTP code to the clipboard (without entering it)

## Context
This feature is important for several reasons:

1. Reliability: Often, pasting TOTP codes through Auto-Type doesn't work correctly on some websites or applications. Having the code in the clipboard allows for manual pasting, which can be more reliable.

2. Convenience: It's more convenient to have the TOTP code automatically copied to the clipboard after the login process, ready to be pasted when needed.

3. Flexibility: This feature would allow users to choose whether to auto-type the TOTP or just have it ready in the clipboard, depending on the specific site or application requirements.

4. Consistency with mobile apps: Other KeePass apps, particularly on iOS, already offer this functionality. Adding this feature to KeePassXC would provide a more consistent experience across different platforms and devices.

5. Time-saving: By automatically copying the TOTP to the clipboard, users can save time and reduce the risk of errors that might occur when manually copying the code.

This feature would be particularly useful for websites or applications where Auto-Type of TOTP codes is unreliable or not supported, allowing users to quickly paste the code manually after the automatic login process.

**Comment by droidmonkey** [comment]
This was explicitly not added. We offer the ability to copy username/password/totp from the auto-type selection dialog. You can search the issues board for reasoning on why.
