### ISSUE TITLE
Add new option: Open URL + Auto Complete regarding this URL

### ISSUE THREAD

**Issue by bovirus** [keepassxreboot/keepassxc#1094]
Now we have

**_Open URL
Auto Complete_**

that require to open an URL and in the same time auto complete require two steps.

Please add an option

**_Open URL+Auto Complete about this url_**

to have a the feature with only one operation (Roboform do this in one step).

Thanks.

**Comment by phoerious** [comment]
This is very hard if not impossible to do as it requires feedback from the browser when the page has finished loading and it also needs to focus the correct input field first. Robofrom can do that, because it registers a browser extension. KeePassXC doesn't. I don't think we can implement this.
