### ISSUE TITLE
Version KeePassXC-2.7.9-Win64.msi

### ISSUE THREAD

**Issue by rjl77027** [keepassxreboot/keepassxc#10959]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Attempted to install v.2.7.9, appears to install without issues
2. Will not launch: Regular or Admin mode
3. Uninstalled and re-installed v.2.7.8 and it works fine

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Expected it to start up without issue

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Appears to attempt to launch but does not. I checked Task Manager and it is not running as an App or Background Task

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION v.2.7.9
Revision: REVISION - not sure

[NOTE]: # ( Pick choices based on your environment )
*** Operating System: Windows 11 Pro

**Comment by sdfsdfsdsdcs** [comment]
same problem

**Comment by Bhin2340** [comment]
Same problem & symptoms, using Windows 10.

**Comment by droidmonkey** [comment]
https://github.com/keepassxreboot/keepassxc/issues/10925
