### ISSUE TITLE
Empty DB when using 2.7.9

### ISSUE THREAD

**Issue by cortobass** [keepassxreboot/keepassxc#10952]
When I open my DB with 2.7.9 (after solving the crash under Win11 by installing VC_redist.x64) my DB is completely empty. I can see only the two default entries. And I checked more than once that I was using the proper file (and it's the right password that's required to open it).
After reverting to 2.7.8, I can see all my entries again.

**Comment by varjolintu** [comment]
See https://github.com/keepassxreboot/keepassxc/issues/10927.
