### ISSUE TITLE
Unlock additional databases from Global Auto-Type window Pop-up in browsers

### ISSUE THREAD

**Issue by Hidigoudi** [keepassxreboot/keepassxc#10957]
## Summary
When 2 or more databases are opened and locked at startup, the Global Auto-Type shortcut in the browser triggers the window pop-up to unlock the first selected database, it works as expected for me. However, for the others still locked databases, I need to go in the main software window to unlock them.

It is the same behavior on Windows 10 22H2 and Debian 12 systems.

## Examples
I imagine an additional select field (or tab) at top in the Auto-Type window pop-up to select which opened database you want use and potentially unlock it if it is required.

## Context
For people that use "Minimize window at application startup" feature + have more than 1 database and don't want open the main software window, it is not possible to unlock it from the Global Auto-Type window pop-up which is quite annoying.

It should be possible to unlock all locked databases (not only the first selected one) from browsers.

**Comment by droidmonkey** [comment]
https://github.com/keepassxreboot/keepassxc/issues/10108
