### ISSUE TITLE
Passkeys Right-click export

### ISSUE THREAD

**Issue by darkdragon-001** [keepassxreboot/keepassxc#10958]
## Summary
It would be great to add an "Export Passkey" option to the right-click menu on an entry with an existing passkey next to the already existing "Import Passkey" and "Delete Passkey" (#10715). It might make sense to group the three entries like it's done for TOTP.

## Examples
_None_

## Context
I mostly operate directly on specific entries as I have a sizable password database.

**Comment by droidmonkey** [comment]
Since exporting a passkey is a sensitive topic we won't be moving that feature to the right click menu.
