### ISSUE TITLE
KeePassXC .exe file won't open.

### ISSUE THREAD

**Issue by asdhgfaiusdgfjkhgbasf** [keepassxreboot/keepassxc#10950]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
KeePassXC .exe file won't open when I double click on it. I also can't open it by clicking on my passwords file.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Start the computer.
2. Double click on the .exe file or on the desktop shortcup.
3. Nothing.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
I expected KeePassXC to open.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
The circle spins around a bit like it wants to open but then it doesn't.

## Context
[NOTE]: # ( Give us any additional information you may have. )
It's a Windows 11 computer.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - V2.7.9
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows
Desktop Env: Windows
Windowing System: Desktop Window Manager

**Comment by asdhgfaiusdgfjkhgbasf** [comment]
You can see a video of me trying to open it [here](https://youtu.be/bJiBwjFLJwU).

**Comment by droidmonkey** [comment]
https://github.com/keepassxreboot/keepassxc/issues/10925#issuecomment-2179741873

**Comment by asdhgfaiusdgfjkhgbasf** [comment]
Thanks for the help!
