### ISSUE TITLE
2.7.9 release not available in microsoft store

### ISSUE THREAD

**Issue by boogieshafer** [keepassxreboot/keepassxc#10954]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

seems like the version available in the microsoft store is still the 2.7.8 release

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. search for keepassxc in microsoft store
2. version available is currently 2.7.8

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
given that 2.7.9 has been released for a few days now an the blog post announcing its release even mentions it being available on the microsoft store, i would expect that version to the one available there

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.9

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows

**Comment by boogieshafer** [comment]
![Screenshot 2024-06-22 085312](https://github.com/keepassxreboot/keepassxc/assets/714141/07a311d4-da87-457a-8660-48aeab1a603e)

**Comment by droidmonkey** [comment]
It'll get there thank you

**Comment by boogieshafer** [comment]
still not seeing it in the store. how about closing once it actually shows up?

**Comment by boogieshafer** [comment]
reference: https://apps.microsoft.com/detail/xp8k2l36vp0qmb?hl=en-US&gl=US

**Comment by droidmonkey** [comment]
It's still in review, we don't control that timeline.
