### ISSUE TITLE
Green Bar in Database Password Field (compiled on Linux)

### ISSUE THREAD

**Issue by bfm59** [keepassxreboot/keepassxc#10964]
## Overview
Version 2.7.9, compiled with varying options on Linux Mint 21.3.  A green bar appears in the database password field, either momentarily or persistently (cases A and B below).  I do not know whether this is intended behavior or a bug, and if the latter whether it is anything more than cosmetic.

##############################################################################################

**A. Green Bar Flashes Momentarily**
~/Downloads/keepassxc-2.7.9 $ mkdir build && cd build

~/Downloads/keepassxc-2.7.9/build $ uname -a
Linux hostname 5.15.0-112-generic #122-Ubuntu SMP Thu May 23 07:48:21 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

~/Downloads/keepassxc-2.7.9/build $ cmake -DWITH_XC_AUTOTYPE=ON -DWITH_XC_BROWSER=ON -DWITH_XC_BROWSER_PASSKEYS=ON -DWITH_XC_FDOSECRETS=ON -DWITH_XC_NETWORKING=ON -DWITH_XC_SSHAGENT=ON -DWITH_XC_YUBIKEY=ON -DCMAKE_BUILD_TYPE=Release -DWITH_GUI_TESTS=ON -DCMAKE_VERBOSE_MAKEFILE=ON ..

-- Found Git HEAD Revision: 8f6dd13

-- Setting up build for KeePassXC v2.7.9

-- Including translations...

-- Using asciidoctor: /usr/bin/asciidoctor
-- Enabled features:
 * Auto-Type, Automatic password typing
 * Networking, Compile KeePassXC with network access code (e.g. for downloading website icons)
 * KeePassXC-Browser, Browser integration with KeePassXC-Browser
 * Passkeys, Passkeys support for browser integration
 * SSHAgent, SSH agent integration compatible with KeeAgent
 * YubiKey, YubiKey HMAC-SHA1 challenge-response
 * UpdateCheck, Automatic update checking
 * FdoSecrets, Implement freedesktop.org Secret Storage Spec server side API.

-- Disabled features:
 * KeeShare, Sharing integration with KeeShare

-- Configuring done
-- Generating done
-- Build files have been written to: /home/xxxxxx/Downloads/keepassxc-2.7.9/build

~/Downloads/keepassxc-2.7.9/build $ make -j 10

~/Downloads/keepassxc-2.7.9/build $ ./src/keepassxc

KeePassXC - Version 2.7.9
Revision: 8f6dd13

Qt 5.15.3
Debugging mode is disabled.

Operating system: Linux Mint 21.3
CPU architecture: x86_64
Kernel: linux 5.15.0-112-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- Passkeys
- SSH Agent
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.19.1

This results, when the KeePassXC window appears and the database is selected, in a green bar flashing momentarily in the Database "Enter Password" field and then quickly disappearing.

=========================================================================================
**B.  Green Bar Persists**

Exactly the same as above except that in the cmake command all of the ONs are changed to OFF:

~/Downloads/keepassxc-2.7.9/build $ cmake -DWITH_XC_AUTOTYPE=OFF -DWITH_XC_BROWSER=OFF -DWITH_XC_BROWSER_PASSKEYS=OFF -DWITH_XC_FDOSECRETS=OFF -DWITH_XC_NETWORKING=OFF -DWITH_XC_SSHAGENT=OFF -DWITH_XC_YUBIKEY=OFF -DCMAKE_BUILD_TYPE=Release -DWITH_GUI_TESTS=OFF -DCMAKE_VERBOSE_MAKEFILE=OFF ..
-- Disabling WITH_XC_UPDATECHECK because WITH_XC_NETWORKING is disabled
-- Found Git HEAD Revision: 8f6dd13

-- Setting up build for KeePassXC v2.7.9

-- Including translations...

-- Using asciidoctor: /usr/bin/asciidoctor
-- Enabled features:

-- Disabled features:
 * Auto-Type, Automatic password typing
 * Networking, Compile KeePassXC with network access code (e.g. for downloading website icons)
 * KeePassXC-Browser, Browser integration with KeePassXC-Browser
 * Passkeys, Passkeys support for browser integration
 * SSHAgent, SSH agent integration compatible with KeeAgent
 * KeeShare, Sharing integration with KeeShare
 * YubiKey, YubiKey HMAC-SHA1 challenge-response
 * UpdateCheck, Automatic update checking
 * FdoSecrets, Implement freedesktop.org Secret Storage Spec server side API.

-- Configuring done
-- Generating done
-- Build files have been written to: /home/brian/Downloads/keepassxc-2.7.9/build

~/Downloads/keepassxc-2.7.9/build $ make -j 10

~/Downloads/keepassxc-2.7.9/build $ ./src/keepassxc

KeePassXC - Version 2.7.9
Revision: 8f6dd13

Qt 5.15.3
Debugging mode is disabled.

Operating system: Linux Mint 21.3
CPU architecture: x86_64
Kernel: linux 5.15.0-112-generic

Enabled extensions: None

Cryptographic libraries:
- Botan 2.19.1

This results, when the KeePassXC window appears and the database is selected, in a green bar appearing and persisting in the Database "Enter Password" field and then quickly disappearing.  See screenshot.

## Expected Behavior
I am assuming that no green bar should appear in the database password field, either momentarily or persistently.

## Actual Behavior
The options provided through cmake appear to have an effect on whether a green bar appears, momentarily or persistently.
![PersistentGreenBar](https://github.com/keepassxreboot/keepassxc/assets/48263236/636e470a-52b8-461d-be98-7090f9ef2f40)

## Context
I noticed similar behavior in version 2.7.8.  The following options, inexplicably to me and found empirically, prevented the appearance of the green bar in 2.7.8.
cmake -DWITH_XC_AUTOTYPE=OFF -DWITH_XC_BROWSER=ON -DWITH_XC_BROWSER_PASSKEYS=ON -DWITH_XC_FDOSECRETS=OFF -DWITH_XC_NETWORKING=OFF -DWITH_XC_SSHAGENT=OFF -DWITH_XC_YUBIKEY=ON -DCMAKE_BUILD_TYPE=Release -DWITH_GUI_TESTS=OFF -DCMAKE_VERBOSE_MAKEFILE=OFF ..

In version 2.7.9, I have not been able to make the green bar consistently not appear.

[NOTE]: # ( Pick choices based on your environment )
Linux Mint 21.3, XFCE, X11

**Comment by droidmonkey** [comment]
That is the indicator that hardware keys are attempting to be discovered. 

We are making yubikey a mandatory feature, so this issue with it being always visible will resolve itself as a result.
