### ISSUE TITLE
update 2.7.9  is crasing in win10 pro

### ISSUE THREAD

**Issue by sdfsdfsdsdcs** [keepassxreboot/keepassxc#10960]
today i update to 2.7.9 and it crashing in background and no information is popup.
operating system : win 10 pro.

**Comment by StarPepe** [comment]
I've got the exact same problem, I cannot launch the application after updating.
Downgrading to 2.7.8 fixes it.

**Comment by Morc001** [comment]
See https://github.com/keepassxreboot/keepassxc/issues/10925 for solution.

**Comment by droidmonkey** [comment]
https://github.com/keepassxreboot/keepassxc/issues/10925
