### ISSUE TITLE
Cannot open database files located under symlink / \Device\Volume mount point anymore

### ISSUE THREAD

**Issue by b1t-hunter** [keepassxreboot/keepassxc#10977]
## Overview

I am using Cryptomator for sharing my kdbx with multiple machines. On Windows, Cryptomator uses symbolic links to mount the encrypted container into the filesystem. I could previously access this file without problems with KeePassXC (2.7.8), but it stopped working in the newest version (2.7.9), telling me that the selected path is not safe to use.

I get an error (in German) when I want to select the symlink leading into my container with kdbx file.

![Error](https://github.com/keepassxreboot/keepassxc/assets/100193865/3810c1d4-ec46-40cd-8bce-35dd68d936d3)

This roughly translates to: 

```
Selected path is not available:

Cannot access path at D:\XYZ.

The selected path cannot be followed, because it contains a non-trustworthy mount point.
```

I have other symlinks on my system that can be followed without problems. So, I assume the problem is not in the symlink, but the actual mount point that Cryptomator provides and the symlink is pointing to. It has the form of "\Device\Volume{SOME-GUID}\".

## Steps to Reproduce

1. Put the kdbx file into an FS-mounted share of Cryptomator.
2. Select the "Open Database" and try to locate your file.
3. When trying to enter the container over the symlink, the error occurs.

## Expected Behavior

As in earlier versions, you should be able to select databases in Cryptomator shares, i.e., files in an "anonymously" mounted drive.

## Actual Behavior

An error occurs, telling me that the source is not trusted.

## Context

KeePassXC - Version 2.7.9
Revision: 8f6dd13
Operating System: Windows 11

**Comment by b1t-hunter** [comment]
I reverted back to the previous version and it started working again.

**Comment by droidmonkey** [comment]
This is a windows issue. You will need to either install KeePassXC or place the portable version in the same network share. This isn't on our side.

**Comment by droidmonkey** [comment]
See https://github.com/keepassxreboot/keepassxc/issues/9937

**Comment by b1t-hunter** [comment]
This worked in the previous version, though, without installing KeePassXC on the share.

**Comment by droidmonkey** [comment]
It's not an error from keepassxc, is all I can offer. That is a Microsoft error.
