### ISSUE TITLE
autostarted keepassxc is without buttons in window header

### ISSUE THREAD

**Issue by lev741** [keepassxreboot/keepassxc#10976]
## Overview
If keepass starts automatically when the computer starts using autostart, then when it opens, the buttons in the window header (maximize, minimize, close) are not visible or available.
If it is started afterwards from the program list (it hasn't been autostarted before), the buttons are visible and work.

## Steps to Reproduce
1. Set autostart and restart Gnome
2. 
3. 

## Expected Behavior
Buttons in the window header visible when using autostart

## Actual Behavior
Buttons in the window header aren`t visible when using autostart

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Verze 2.7.9

Revize: 8f6dd13

Qt 5.15.14
Ladící režim je vypnutý.

Operační systém: Fedora Linux 40 (Workstation Edition)
Architektura procesoru: x86_64
Jádro systému: linux 6.9.5-200.fc40.x86_64

Zapnutá rozšíření:
- Automatické vyplňování
- Napojení na webový prohlížeč
- Passkeys
- SSH agent
- KeeShare
- YubiKey
- Zapnout napojení na Secret Service

Kryptografické knihovny:
- Botan 2.19.3

[NOTE]: # ( Pick choices based on your environment )
I see it on Fedora 39, Gnome 45, Wayland too.

**Comment by phoerious** [comment]
That's a problem with your desktop/windowing system. We don't control that.
