### ISSUE TITLE
keepassxc 2.7.9, no entries listed when keepassxc.ini exists.

### ISSUE THREAD

**Issue by eAlex79** [keepassxreboot/keepassxc#10970]
## Overview
arch linux, fully updated. keepassxc opens database without issue, but does not list any entries. If .cache/keepassxc/keepassxc.ini is removed the application does show entries normally. Restarting the app reintroduces the issue. Previous version 2.7.8-3 does not show this behaviour.

## Steps to Reproduce
1. open keepassxc window
2. open database, enjoy the ability to use your passwords
3. restart keepassxc application
4. enjoy passwordless happyness ;)

## Expected Behavior
app should show entries normally

## Actual Behavior
app does not list any entries if keepassxc.ini from previous run is present

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.9
Revision: 8f6dd13

Qt 5.15.14
Diagnosemodus ist deaktiviert.

Betriebssystem: Arch Linux
CPU-Architektur: x86_64
Kernel: linux 6.9.6-zen1-1-zen

Aktivierte Erweiterungen:
- Auto-Type
- Browser-Integration
- Passkeys
- SSH-Agent
- KeeShare
- YubiKey
- Secret-Service-Integration

Kryptographische Bibliotheken:
- Botan 3.4.0

[NOTE]:
Operating System: Linux (arch)
Desktop Env: KDE
Windowing System: Wayland

**Comment by phoerious** [comment]
Do you have a screenshot? I cannot reproduce any of that.

**Comment by droidmonkey** [comment]
https://github.com/keepassxreboot/keepassxc/issues/10927
