### ISSUE TITLE
2.7.9 do not start Win 10

### ISSUE THREAD

**Issue by VitaliyAT** [keepassxreboot/keepassxc#10973]
## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Install, reinstall, uninstall reboot install again
2. Try run
3. Nothing running

## Expected Behavior
[NOTE]: Must run when I run it

## Actual Behavior
[NOTE]: I am tring update and it's not work. Back to 2.7.8 and it work OK

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.9
Revision: Can't - ciuse it not running

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 10

**Comment by dvschuetz** [comment]
This is the same issue like [https://github.com/keepassxreboot/keepassxc/issues/10925](https://github.com/keepassxreboot/keepassxc/issues/10925)
The Visual C++ redistributable package is too old.
You need to download it from [https://aka.ms/vs/17/release/vc_redist.x64.exe](https://aka.ms/vs/17/release/vc_redist.x64.exe).

I could reproduce it: 
- VCredist 2015-2022 x64 version 14.32.31326 of 2023 does not run KeePassXC 2.7.9, but 2.7.8 and older
- VCredist 2015-2022 x64 version 14.40.33810.0 (downloaded 24.06.2024) does run KeePassXC 2.7.9

**Comment by AngusYu** [comment]
> This is the same issue like #10925 The Visual C++ redistributable package is too old. You need to download it from https://aka.ms/vs/17/release/vc_redist.x64.exe.
> 
> I could reproduce it:
> 
> * VCredist 2015-2022 x64 version 14.32.31326 of 2023 does not run KeePassXC 2.7.9, but 2.7.8 and older
> * VCredist 2015-2022 x64 version 14.40.33810.0 (downloaded 24.06.2024) does run KeePassXC 2.7.9

Problem solved, thanks for that.

**Comment by andrewintw** [comment]
I have the same problem, 2.7.9 cannot be started on WIN11

After I upgraded from KeePassXC-2.7.8-Win64.msi to KeePassXC-2.7.9-Win64.msi, the program could not be started normally, and no error message even appeared. However, it can be executed normally after downgrading to KeePassXC-2.7.8. Runs on WIN11.

**Comment by phoerious** [comment]
Reinstall MSVC.

**Comment by Hoerli1337** [comment]
Must be due to the stupid new update from M$.
I had the same problem.

**Comment by mirtelo** [comment]
Hi,

https://developercommunity.visualstudio.com/t/Access-violation-in-_Thrd_yield-after-up/10664660#T-N10668856

**Comment by Nilpo** [comment]
What's the solution if you ARE running the latest version of Visual C++ Redistributable?

I just installed both VC++ 14.42.34438 and KeePassXC-2.7.10-Win64 on a clean install of Windows 10 Pro 22H2 Build 19045.5371.

It launched the first time and I used it for several hours yesterday. Today, it won't launch.

Edit: Just realized this issue was for 2.7.9, but it appears to be the same cause with 2.7.10.

**Comment by droidmonkey** [comment]
Its definitely not the same cause. You would never have been able to start it. If the app truly doesn't start then you should look in the windows event viewer to see if there is a clue. You should also make sure your endpoint protection software isn't killing us.

**Comment by skyrl69** [comment]
We're in 2025 and same problem just happened to me with newest version 2.7.10 !
I just installed VC REDIST 2022 and it works fine now, thanks @dvschuetz 
Would it be nice if KeepassKC at least may display a message informing the user installed VC redist is not up-to-date ??
