### ISSUE TITLE
macOS alert shows a confusing message

### ISSUE THREAD

**Issue by kesara** [keepassxreboot/keepassxc#10975]
## Overview

Setting KeePassXC to launch at startup on macOS creates a confusing alert.
The alert that states

> Software from "Janek Bevendroff" added items that can run in the background.
> ...

This can be confusing since users have to look up the "about" screen to identify that's one of the maintainers.

## Steps to Reproduce

1. Go to preferences.
2. Enable "Automatically launch KeePassXC at system startup

## Expected Behavior

macOS notifications should have an identifiable name like KeePassXC or similar.

## Actual Behavior

macOS produces the following notification with the name of one of the maintainers:

<img width="314" alt="Screenshot 2024-06-25 at 19 02 21" src="https://github.com/keepassxreboot/keepassxc/assets/1027692/5d920d65-fff8-420e-b997-922c5998be59">

## Context
macOS: Sonoma 14.5
KeePassXC - 2.9.5
Revision: 8f6dd13

Operating System: macOS
Desktop Env: 
Windowing System:

**Comment by kesara** [comment]
macOS settings -> General -> Login Items

Show Janek Bevendroff's name as well.

<img width="472" alt="Screenshot 2024-06-25 at 19 19 40" src="https://github.com/keepassxreboot/keepassxc/assets/1027692/844ce848-7552-4a21-a947-ed445d2c42e9">

**Comment by phoerious** [comment]
That's a macOS problem. They use the name on the developer certificate instead of the app name. Nothing we can do about that, unfortunately.

**Comment by kesara** [comment]
It looks like the Apple organization account might solve this issue [^1].
But I have no idea how feasible that is.
Thanks!

[^1]: https://developer.apple.com/support/enrollment/

**Comment by phoerious** [comment]
We have no legal entity status.
