### ISSUE TITLE
KeePassXC Installer should check VCredist Version

### ISSUE THREAD

**Issue by dvschuetz** [keepassxreboot/keepassxc#10974]
## Summary
On installing, the KeePassXC installer should check, whether the Visual C++ redistributable library **is actual enough** for the current KeePassXC version.

## Actual Behaviour
The KeePassXC Installer checks, whether VC redist x64 is installed or not. (If not, ... I don't remember whether it just gives a message or leads to download VCredist.x64.) But if an older VCredist.x64 version is present, e.g. version 14.32.31326 of 2023, KeePassXC 2.7.9 will install, but not start and crash silently.  

## Examples
Bug [#10925](https://github.com/keepassxreboot/keepassxc/issues/10925)
Bug [#10973](https://github.com/keepassxreboot/keepassxc/issues/10973)

## Context
Any computers with Windows 10 or 11 which installed KeePassXC the first time more than a year ago

**Comment by droidmonkey** [comment]
Yes, can add but vcredist are supposed to be backwards compatible... this is ultimately a Microsoft bug

**Comment by droidmonkey** [comment]
FWIW, a minimum version detection wound not have prevented or alerted people to this. For all we knew we were fully compatible with all versions of the msvc redist. Microsoft made no mention of an incompatibility and we didn't use any new api's between releases.

**Comment by rharmonson** [comment]
Not a complaint, but sharing my experience.

Just finished a fresh install of Windows 11 23H2 and all updates. KeePassXC 2.7.9 installs without issue, however, on launching, errors with three dialogs stating missing vcruntime140.dll and once for vcruntime140_1.dll.

Installed VC_redist.x64.exe and good to go.

Awesome application. Thank you.

**Comment by droidmonkey** [comment]
Please share your experience with Microsoft, they need to deploy the vc redist with their operating system to make things better. We are looking at options, but MSI cannot install an MSI (which the vc redist is despite the exe suffix), another Microsoft limitation...

**Comment by rharmonson** [comment]
I agree. I will create a support ticket, but in my experience, Microsoft does not care unless you are a large commercial customer.

**Comment by mirtelo** [comment]
https://developercommunity.visualstudio.com/t/Access-violation-in-_Thrd_yield-after-up/10664660#T-N10668856

**Comment by rharmonson** [comment]
> https://developercommunity.visualstudio.com/t/Access-violation-in-_Thrd_yield-after-up/10664660#T-N10668856

Notice how they just put it on third party developers. 

M$=A$$HAT$.

**Comment by PhoenixIV** [comment]
Is this fixed in 2.7.10 ?

I just did a clean install  of Windows 11 and still received the "msvcp140.dll missing" error after installing and starting 2.7.10

There was no warning during installation.

Also:

In the pull request it was asked if you can make the link clickable. Answer: Unfortunately not.
-> Maybe you can add a second button instead or make it a regular "page" in the installer?

**Comment by droidmonkey** [comment]
This was removed from the 2.7.10 installer because it was broken and prevented some people from installing.

**Comment by PhoenixIV** [comment]
Thanks!

Re-open this ticket or is there a new one?

**Comment by droidmonkey** [comment]
I am not reintroducing the check

**Comment by PhoenixIV** [comment]
Too bad. The error message you get without VC++R is not suited for non technical people.

As it says missing `msvcp140.dll` I was wondering of you can just check the existance of the file.

**Comment by droidmonkey** [comment]
We will be fixing this with 2.8.0 since I am planning to shift to MSIX
