### ISSUE TITLE
Window resize/redraw issue after monitors wake up from sleep.

### ISSUE THREAD

**Issue by sbotnickusgs** [keepassxreboot/keepassxc#10972]
## Overview
KeepassXC window does not redraw/resize properly after monitors wake up from sleep.

## Steps to Reproduce
Open KeepassXC in a window, in my case, a window less than full screen.
Allow monitors to go to sleep.
Wake monitors.

## Expected Behavior
Window redraws/restores to correct size on monitor wake, controls work without restarting app.

## Actual Behavior
Window redraws like or similar to attached photo, minus the about window, I opened that.
Buttons sometimes show and are floating in the undrawn area, they do not work.
Resizing the window does not seem to change or restore normal behaviour, app must be closed and restarted to resume normal operation.
The attached image is an external photo, screen snipping tool and print screen do not capture the Keepass window.

## Context
This is intermittent and in a multi-monitor environment, in this case, two monitors. It also does not matter if the monitor is an external USB unit or both are running on the system GPU. I cannot recall if I have had this experience in a single monitor environment on another Windows system.  Other windows are also moved around/resized when monitors are awakened but are redrawn/resized correctly.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.8
Revision: f6757d3

Qt 5.15.11
Debugging mode is disabled.

Enabled extensions:
- Auto-Type
- Browser Integration
- Passkeys
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 3.1.1

[NOTE]: # ( Pick choices based on your environment )
Operating system: Windows 10 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.19045
![20240624-keepassxc-windows-redraw-bug](https://github.com/keepassxreboot/keepassxc/assets/85366267/37720b21-3ff9-43e6-8125-3336850fc61e)

**Comment by droidmonkey** [comment]
This is a qt problem already reported, should be fixed when we move to qt6.
