### ISSUE TITLE
I get the wrong password for Office with the 2-account authentication. 

### ISSUE THREAD

**Issue by SH899** [keepassxreboot/keepassxc#10986]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. I get the wrong password for Office with the 2-account authentication. 
2. 
3. 

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows/Linux/macOS
Desktop Env: Gnome/KDE/XFCE/Mate/Cinnamon
Windowing System: X11/Wayland

**Comment by droidmonkey** [comment]
Sync your computer time

**Comment by SH899** [comment]
12:45

**Comment by SH899** [comment]
> Sync your computer time

what do u mean?

**Comment by droidmonkey** [comment]
https://www.bing.com/search?q=sync+computer+time+windows

**Comment by SH899** [comment]
what should i do after that? can i give u access to my computer?

**Comment by droidmonkey** [comment]
https://keepassxc.org/docs/KeePassXC_UserGuide#_adding_totp_to_an_entry

> can i give u access to my computer?

No, and I don't recommend asking or allowing that for anyone else.

**Comment by SH899** [comment]
> https://keepassxc.org/docs/KeePassXC_UserGuide#_adding_totp_to_an_entry
> 
> > can i give u access to my computer?
> 
> No, and I don't recommend asking or allowing that for anyone else.

The problem is, I get this displayed in Office365: 

Enter code
Enter the code that is displayed in the Authenticator app on your mobile device
You have not entered the expected verification code. Please try again.

-> I don't understand how I can retrieve the code from KeePass? it was actually linked to Root / Office, so the code must be correct....

**Comment by droidmonkey** [comment]
If the code worked in the past then you still have a time problem.
