### ISSUE TITLE
Allow Capture whitelist

### ISSUE THREAD

**Issue by Myrkie** [keepassxreboot/keepassxc#10984]
## Summary
It would be a large quality of life improvement to have a user-defined list that will be allowed to capture keepassxc and bypass the "allow capture" setting

## Examples
A new column will be added under the "Security category" that will allow for either selecting a single program or a list of programs that will be allowed to see keepassxc window content even with "Allow Capture" disabled

## Context
Im a frequent VR user so for me to see my desktop while within VR I have to use an overlay program that uses windows capture, since this is just a screen capture I am unable to see my database and this can also end up "eating" inputs if you are unaware keepassxc has popped up and you will be left completely unaware.

**Comment by droidmonkey** [comment]
This isn't possible with operating system api. It's all or nothing.
