### ISSUE TITLE
I get the wrong password for Office with the 2-account authentication.

### ISSUE THREAD

**Issue by SH899** [keepassxreboot/keepassxc#10989]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. I get the wrong password for Office with the 2-account authentication.
2. 
3. 

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows/Linux/macOS
Desktop Env: Gnome/KDE/XFCE/Mate/Cinnamon
Windowing System: X11/Wayland

**Comment by droidmonkey** [comment]
Do not open duplicate issue, I told you what to do already and you provide literally zero details anyway.

**Comment by SH899** [comment]
I have now synchronized the time and date.

Unfortunately, I get the wrong code displayed on KeePass in Office for the 2 account authentication.

**Comment by droidmonkey** [comment]
Then you used the wrong secret key

**Comment by droidmonkey** [comment]
https://keepassxc.org/docs/KeePassXC_UserGuide#_adding_totp_to_an_entry
