### ISSUE TITLE
If entered a wrong passwort the height of the password field shrinks. 

### ISSUE THREAD

**Issue by haferkraft** [keepassxreboot/keepassxc#10987]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
If entered a wrong passwort the height of the password field shrinks. 
This happens when the windowed KeePassXC app is below a certain height
![2024-06-27 10_09_01-Clipboard](https://github.com/keepassxreboot/keepassxc/assets/173997043/d6ec0fbf-99c3-48d6-b967-3b69aad463a4)

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Start KeePassXC . 
2. Resize the App window height to 650 pixel or lower
3. enter a wrong password for a databaes
4. the error popup squeezes rest of content, also the password field

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
the height of the password field should always be fixed to fit the current character size in line

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
the height of the password field shrinks worst case to a single line

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.8
Revision: f6757d3

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 11 Version 2009
Desktop Env: Win
Windowing System: Win

**Comment by droidmonkey** [comment]
Duplicate report
