### ISSUE TITLE
2.7.9 missing dll

### ISSUE THREAD

**Issue by jookk** [keepassxreboot/keepassxc#10980]
## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. installed new msi update
2. start keepassxc failed with error

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Launch the app

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
After update I launched keepassxc. I have only popup with error shown in screenshot. Missing 
![obrázok](https://github.com/keepassxreboot/keepassxc/assets/11217085/c4be7769-c670-40a2-88c2-bbb94f92f45d)

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.9
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 11

**Comment by phoerious** [comment]
Something's wrong with your installation. Try reinstalling everything. This is not MSVC missing (see #10925), but reinstall that as well, just in case.
