### ISSUE TITLE
KeePassXC doesn't open

### ISSUE THREAD

**Issue by ITS-AW-01** [keepassxreboot/keepassxc#10982]
Hello.

KeePassXC doesn't work properly regardless version in Windows 11. The process runs in Task Manager and it appears in Windows task bar, but nothing happens when I click on the app icon. Pointing on the KeePassXC icon in task bar shows little preview window and it's black. Reinstalling MSVC doesn't solve problem. Previous versions of KeePassXC don't work too. Reinstalling KeePassXC does not help.

Please help.

**Comment by droidmonkey** [comment]
https://keepassxc.org/docs/KeePassXC_UserGuide#_screenshot_security
