### ISSUE TITLE
2.7.9 does not start on Windows 11

### ISSUE THREAD

**Issue by wolframklaeger** [keepassxreboot/keepassxc#10983]
Installed as usual, "on top" of the previously installed version 2.7.8, whatever I do, I cannot launch 2.7.9

Had to uninstall 2.7.9 and re-install 2.7.8. This works again. Unfortunately without my settings.

No matter, if I reboot once or twice, before, after or inbetween.

**Comment by droidmonkey** [comment]
https://github.com/keepassxreboot/keepassxc/issues/10925
