### ISSUE TITLE
Regexp to create passwords by mask

### ISSUE THREAD

**Issue by airosa-id** [keepassxreboot/keepassxc#10990]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: I propose adding a feature to the password generator that creates passwords based on a regexp pattern, with the ability to select a complexity level that is not lower than specified in a separate field.

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )

## Context
[NOTE]: Sometimes it is necessary to create multiple passwords of a certain length, with specific sets of characters and complexity. It would be convenient to set a template once, press a button, and get a generated password.

**Comment by droidmonkey** [comment]
We are not adding any more features to the password generator. Thank you for the suggestion though.
