### ISSUE TITLE
Insert question "really want to delete?" for delete button

### ISSUE THREAD

**Issue by sam-bay** [keepassxreboot/keepassxc#10997]
## Summary
Can you include a confirmation step for the delete entry button?

## Examples
Currently an entry is directly deleted if the button is clicked.
Due the the similarity of the add entry and delete button can be clicked by accident.
Either add a thrash symbol here to make it more clear that the user is deleting or make a different color.
The second confirmation for deletion should however be added in any case.

## Context
User might accidentally delete a valid entry which might cause some inconvenience for them.

**Comment by droidmonkey** [comment]
We already have this. If your recycle bin is enabled on a database, then it moves the entry to the bin without confirmation but can be easily restored. You can enable confirmation of recycle bin movement in the application settings.
