### ISSUE TITLE
Search and Tags Box Cannot Be Closed In View

### ISSUE THREAD

**Issue by KitchM** [keepassxreboot/keepassxc#10999]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
I just upgraded my OS and found that the program has the Search and Tags box in the bottom left hand, but it cannot be closed under view.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Search for close option under View menu
2. 
3. 

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Should be able to close the pane.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION 2.7.4
Revision: REVISION 63b2394

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows/Linux/macOS Debian 12
Desktop Env: Gnome/KDE/XFCE/Mate/Cinnamon Xfce 4.18
Windowing System: X11/Wayland X11

**Comment by droidmonkey** [comment]
Drag it down

**Comment by KitchM** [comment]
Just drag it down until it disappears?  Oh, okay.  Thanks.
