### ISSUE TITLE
Compact Mode Seemingly Does Not Change Anything

### ISSUE THREAD

**Issue by KitchM** [keepassxreboot/keepassxc#10998]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
Compact Mode does not seem to do anything.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Select View>Compact Mode
2. Reboot program
3. 
4. 

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
I should have seen some change in the display.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION 2.7.4
Revision: REVISION 63b2394

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows/Linux/macOS Debian 12
Desktop Env: Gnome/KDE/XFCE/Mate/Cinnamon Xfce 4.18
Windowing System: X11/Wayland X11

**Comment by droidmonkey** [comment]
https://keepassxc.org/docs/KeePassXC_UserGuide#_application_settings

See here for what it does

**Comment by KitchM** [comment]
Ah, thank you.  Way too subtle for me. ;)
