### ISSUE TITLE
Database file corrupted

### ISSUE THREAD

**Issue by janithmalshan** [keepassxreboot/keepassxc#11007]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # I had 2 db files and one of them has been corrupted. I am not sure about the reason. Somehow it shows 0kb.
I suspect this happens due to low storage. 

**Error while reading the database: Failed to read database file.**

This is the error message shows in the FE

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. 
2. 
3. 

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows10
Desktop Env: 
Windowing System:

**Comment by janithmalshan** [comment]
Error while reading the database: Failed to read database file.

This is the error message shows in the FE

**Comment by droidmonkey** [comment]
Sorry, but there is nothing we can do about that. Load a backup if you have one. Are you using a USB thumb drive?  We don't recommend if you are.

**Comment by janithmalshan** [comment]
No problem, I had a backup.
But you can try to find the issue by testing with low storage.

**Comment by droidmonkey** [comment]
If you have safe saves enabled then it won't be a problem as the temp file will fail to save properly before overwriting your main file.
