### ISSUE TITLE
Roll/Unroll group option for private view of records

### ISSUE THREAD

**Issue by whonion** [keepassxreboot/keepassxc#11009]
## Summary
Greetings, developer!
Could you please add an option in database/KeepassXC settings to hide default main category on database load ? Also so that it is not revealed when searching for records for more privacy ?

## Examples
![KeepassXC](https://github.com/keepassxreboot/keepassxc/assets/47848969/aeb82fe9-eb10-4483-8f07-39d021242dfa)

## Context
This option is useful if there are third parties who can see the database structure.

**Comment by droidmonkey** [comment]
You can collapse the group folder and that state will be saved, I guess that is what you mean. What you are asking for provides zero protection from physical access. If people are observing your session then there is nothing we can do to prevent them from observing your session.

**Comment by whonion** [comment]
I meant that when I find a record via search and navigate to it, then the group is expanded, but I need only the found record to open, while not showing the entire location of the record and all the other subgroups.
But KeepassXC does that

**Comment by droidmonkey** [comment]
Don't double click on the group name in the search results, that goes to the group. Double click the entry title instead.
