### ISSUE TITLE
Display Link is not a "real" screen capture

### ISSUE THREAD

**Issue by Zordid** [keepassxreboot/keepassxc#11002]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
I updated to Mac OS Sonomia 14.5 today and after a restart, my KeePass XC window was not showing anymore.
I immediately suspected something with Display Link Manager, but the way this shows is awkward and wrong. The window is mainly just completely gone - without any chance to even interact with any settings at all. So many users will face this issue and not understand what they should do if the window happens to be on the second screen. You cannot move it, you cannot access any settings.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Use Display Link Manager for second screen
2. Use KeePass XC 2.7.9
3.  Your window won't show on second screen

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
It's ok to protect users from screen capture - but NOT by hiding the window. You might e.g. overlay the window with an explanation and an easy way to "fix" this.
But the best way would be to "know" Display Link as not being a real screen capture...

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Window is gone

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.9
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS

**Comment by droidmonkey** [comment]
https://github.com/keepassxreboot/keepassxc/issues/10757#issuecomment-2126342637
