### ISSUE TITLE
Keep up support of Snap until other Linux installation methods are improved

### ISSUE THREAD

**Issue by buehren** [keepassxreboot/keepassxc#11008]
## Summary
I suppose to keep releasing new versions of KeePassXC as Snap - at least until Flatpak supports native messaging and browser integration works.

Also, AppImage should not be the most prominent download option for Linux/Ubuntu IMHO. Otherwise it needs much better instructions (see below).

## Context
As a user of Ubuntu (the most used desktop Linux?), I want to install KeePassXC...
* in a secure way
* with automatic updates
* with support for Firefox integration (KeePassXC-Browser) with the default Firefox snap installation

I currently do not see a satisfactory installation method:

* *AppImage*
  * Making the downloaded file executable is a first obstacle that many users cannot take.
  * When trying to run the AppImage from the file browser, nothing happened.
  * Starting from the command line shows the problem: `dlopen(): error loading libfuse.so.2`.
  * Can the AppImage easily be added as icon in the Gnome sidebar and to start automatically, for example? (I did not try further this time but I remember that this did not work out of the box the last time I tried. It was also not easy to find how to make this work.)
  * Does the AppImage installation work with KeePassXC-Browser?
  * AppImages do not update automatically as all other applications (at least when I tried last time).
  * *In my opinion most users will be lost in this process.*
As this is the most prominent option in the Linux download page, most Linux/Ubuntu users are sent to this rough path that only few can complete. If I was in search of a password manager, I would look elsewhere now...

* *Flatpak*
  * As it seems, flatpak does not support native messaging yet
https://github.com/flatpak/xdg-desktop-portal/pull/705
  * So KeePassXC cannot be used comfortably with the browser integration (KeePassXC-Browser) with this installation method.
  * Flatpak is also not installed by default on Ubuntu. *Maybe a link to installations instructions would help.*

* *Ubuntu PPA*
  * The mentioned usability issues (icon, autostart, updates, Firefox integration) should be fine with this installation method.
  * What is currently holding me back from this: I would like the most secure option for my password manager, and I believe that the containerized installations are best in that regard. (Or not?)

* *Snap*
  * Installation is a bit rough because of the required helper script, but all other usability issues are fine. Browser integration with the default Firefox snap also works.
  * Unfortunately KeePassXC updates are no longer distributed as snap (or maybe they are with a delay?)

**Comment by droidmonkey** [comment]
Concur with you that AppImage is garbage, its a fake containerized download, the only redeeming quality is that it doesn't force you to ship every support binary under the sun like Snap and Flatpak do (ie, Qt5).

Your remarks on Flatpak are plain wrong. KeePassXC Flatpak supports browser integration flawlessly. Browsers as flatpak AND snap (except Firefox) do not support native messaging, but that isn't something we can control. 

The Firefox snap actually pre-deployed/authorized to use the xdg-desktop-portal to get native messaging to work, there is nothing more to that story than that. Snaps and flatpaks both use the xdg-desktop-portal.

Installing flatpak on Ubuntu is about this easy: `sudo apt install flatpak`

The snap update for 2.7.9 is in manual review right now waiting for the snap overlords to approve our ability to write the native messaging files directly to the respective directories in the home folder instead of using the helper script. Your love of snaps is misplaced, imo, but you are welcome to try flatpak. You probably should try it before posting false information though.

**Comment by buehren** [comment]
I like KeePassXC, and I think it is a pity that it is hard to get it working in Ubuntu. That is why I spend some time here and try to provide a user's point of view. 

I also understand that there are technical difficulties and of course someone has to spend time working on improvements, so not everything that one wishes for can be done.

> Concur with you that AppImage is garbage

I wonder why it is the most prominent installation method in the Linux download page. In my opinion this makes it hard and for many users even impossible to make it run.

> Installing flatpak on Ubuntu is about this easy: `sudo apt install flatpak`

Maybe this should also be mentioned in the installation instructions (or linked to flatpak's instructions).

> The snap update for 2.7.9 is in manual review right now waiting for the snap overlords to approve our ability to write the native messaging files directly to the respective directories in the home folder instead of using the helper script.

Good to hear that! Hope that it will be approved. 👍

Is it planned to continue supporting snap? Then I suggest to remove the message on https://snapcraft.io/keepassxc: *"NOTE: KeePassXC no longer supports this distribution method."*

This and the not-yet-available latest version made me think that it is not supported.

> Your love of snaps is misplaced, imo

I do not love it - but as the other options failed as described (for me), and this is the default in the most used Linux distribution, I think it should be supported. (And that seems to be the case 👍, contrary to what is written on https://snapcraft.io/keepassxc )

> you are welcome to try flatpak. You probably should try it before posting false information though.

I did, and it did not work. Now I tried again:

In Firefox I get *"Cannot connect to KeePassXC"*, and after clicking the reload button: *"Key exchange was not successful"*. Another click on reload brings KeePassXC window to the foreground (or even starts KeePassXC), but nothing else seems to happen.
Removing the connected database from the KeePassXC-Browser add-on, restarting KeePassXC (flatpak) and Firefox (snap) did not help.

The flatpak installation has updated `~/.mozilla/native-messaging-hosts/org.keepassxc.keepassxc_browser.json`.
But the browser integration settings page shows this text: *"Browsers installed as snaps are currently not supported"*.

Is the KeePassXC Flatpak supposed to work with the default Firefox installation in Ubuntu, i.e., with Firefox installed as Snap? (IMO this default is used by most people whether we like Snap or not.)

**Comment by droidmonkey** [comment]
It is possible that Firefox installed as a snap does not work with KeePassXC installed as a flatpak. This would have more to do with the firefox snap sandbox restrictions than anything else.

If you are on our website to _download_ KeePassXC, then AppImage is truly the only option. The others are not downloaded from our website, they are installed through command line or store offerings. I have asked the other leads if they are willing to promote Flatpak method over Appimage.

We do not support bug reports against the Snap installation method. Troubleshooting snaps is a huge pain in the butt that consumes literal hours of time. That doesn't mean we won't keep it up to date.

**Comment by igorpupkinable** [comment]
> In Firefox I get _"Cannot connect to KeePassXC"_, and after clicking the reload button: _"Key exchange was not successful"_. Another click on reload brings KeePassXC window to the foreground (or even starts KeePassXC), but nothing else seems to happen. Removing the connected database from the KeePassXC-Browser add-on, restarting KeePassXC (flatpak) and Firefox (snap) did not help.

This is still an issue, but switching from Snap to another installation method and working around default Firefox Snap installation seems more like swimming against the tide. Hopefully v2.7.9 snap will be promoted to Stable someday.

**Comment by droidmonkey** [comment]
Some recent version of the Firefox Snap broke native messaging support

**Comment by phoerious** [comment]
> I wonder why it is the most prominent installation method in the Linux download page. In my opinion this makes it hard and for many users even impossible to make it run.

Besides being the only one we actually offer to download from the website, it is actually the easiest to run, contrary to what you wrote. Marking a file as executable is not a big hurdle and after that it works on almost any distribution out of the box, without advanced commandline foo and without root access. If you are seeing problems with fuse, then that's on your system, not on us. AppImages have some nasty issues with theming and OpenSSL, which are extremely ugly and unfortunately almost unfixable, but none of them pertain to usability. There's even an updater daemon that keeps all your AppImages updated automatically.

**Comment by buehren** [comment]
> it is actually the easiest to run, contrary to what you wrote.

I gave the AppImage download another try on Ubuntu 24.04.

* KeePassXC can run after making the `.AppImage` file executable. 
  This time, it did not complain about `libfuse.so.2` (maybe that was fixed, or it was installed by something else.)

* But I cannot easily add an icon to the start menu of Ubuntu 24.04 / Gnome.
  That can be done by downloading an icon file and creating a `.desktop` file manually (which I did), or probably - according to [docs.appimage.org](https://docs.appimage.org/user-guide/run-appimages.html) - by installing `appimaged` or `AppImageLauncher` (but the latter was last released in 2020?).
  -> I guess that many Linux users will be lost in this process and might look for an alternative to KeePassXC, unfortunately.

* By default, Firefox is installed as Snap in Ubuntu (whether we like that or not).
   The Firefox Snap works with the KeePassXC Snap, but unfortunately that is not regularly updated.
   Unfortunately, the Firefox Snap does not work with the KeePassXC AppImage: 
   https://github.com/keepassxreboot/keepassxc-browser/issues/1828
  I did not get it to work either and reverted to the KeePassXC Snap (not the latest version, unfortunately).
  -> It would probably work with installing Firefox in another way, but I dislike that a "helper" tool (a very nice and helpful one, though!) would force me to divert from the default installation method of an important and security-relevant application. Maybe I am not the only one.

I still do not see how the AppImage distribution method is easy to use, at least for Ubuntu users. So I still think it would be nice to keep up the support of Snap for such distros.

But as stated on the KeePassXC Snap page, they seem to be difficult to maintain. Not a nice situation for great open-source software like this. :-(

**Comment by Hasshu** [comment]
FWIW, according to [secureblue FAQ](https://secureblue.dev/faq#appimage), "AppImages depend on the suid-root, deprecated, unmaintained fuse2 interface". If AppImage is to be kept as an option, putting a warning in the download section might be a good idea.

**Comment by droidmonkey** [comment]
Use flatpak

**Comment by Hasshu** [comment]
> Use flatpak

I [sure do](https://github.com/keepassxreboot/keepassxc/issues/1524#issuecomment-966971646). :P
