### ISSUE TITLE
Win 11 Pro version 2.7.9 KeepassXC not starting

### ISSUE THREAD

**Issue by Baloo9753** [keepassxreboot/keepassxc#11006]
Win 11 Pro version 2.7.9 KeepassXC not starting

Had to reinstall 2.7.8 to use KeePassXC

Win 11 Pro - Lastest Patch Level

Kind Regards
Werner

**Comment by Baloo9753** [comment]
...and yes, reinstalled the MSVC Redist also, buit it did not help - also reboots an clean install of KeePassXC could not help to start it ...

**Comment by xarlydon** [comment]
I also have problems with the latest version. When I open KeePassXC it doesn't show me any account, the screen appears empty even though I have my password list open.
I also have Windows 11 Pro

**Comment by droidmonkey** [comment]
@xarlydon https://github.com/keepassxreboot/keepassxc/issues/10927

@Baloo9753 install the latest version of msvc redist: https://aka.ms/vs/17/release/vc_redist.x64.exe

**Comment by xarlydon** [comment]
> @xarlydon #10927
> 
> @Baloo9753 install the latest version of msvc redist: https://aka.ms/vs/17/release/vc_redist.x64.exe

It still doesn't work even installing what you told me about :(

EDIT: I just installed the previous version 2.7.8 and it works perfectly.

**Comment by droidmonkey** [comment]
@xarlydon look at the linked issue I put next to your name.

**Comment by Baloo9753** [comment]
> @xarlydon #10927
> 
> @Baloo9753 install the latest version of msvc redist: https://aka.ms/vs/17/release/vc_redist.x64.exe

Please read my first call - the latest version IS already installed ... twice, but it does not help - no process starting for KeePassXC

**Comment by droidmonkey** [comment]
Can't do anything else without more information. You'd be the absolute first person to not be solved with install the latest msvc redist...

let's start with an output of which version of msvc you do have installed...

**Comment by Baloo9753** [comment]
Hello,

after uninstall and dele the msvc Files - power cycling the computer I installed the lastest msvc you pointed to and then 2.7.8 first and then updated to 2.7.9 it's working ... first time I had this kind of problem wit KeePass ..
Thank you
Kind regards
Werner

**Comment by xarlydon** [comment]
> @xarlydon look at the linked issue I put next to your name.

Sorry, I had not seen this comment. Indeed, it was hidden in the left panel. Sorry for the inconvenience and thanks for the quick replies.
Regards.
