### ISSUE TITLE
Protect  content while adding "Additional Attributes"

### ISSUE THREAD

**Issue by toxynoid** [keepassxreboot/keepassxc#11004]
## Summary
Please protect  content when adding "Additional Attributes" exactly like the "Password" content.

## Context
The feature would make adding sensitive data into "Additional Attributes" more secure.

**Comment by droidmonkey** [comment]
Thank you, but that doesn't make sense. You can't determine what it is you are writing in there unless you see it. If you are concerned about shoulder surfing then wait until that is not possible. There is no protection we can provide for physical threats.

**Comment by toxynoid** [comment]
So it would make sense to remove this protection from the password field as well?

**Comment by toxynoid** [comment]
Sorry for being cynical, I couldn't resist.
