### ISSUE TITLE
api-ms-win-core-console-I2-1-0.dll is missing

### ISSUE THREAD

**Issue by LAwindsurfer** [keepassxreboot/keepassxc#11011]
* I was running KeePassXC probably version 2.6.6 on a Window7 machine. 
    Win7pro, Versiohn 6.1, build 7601, service pack 1 
* Received message that new version was available. "software update" says 
    KeePassXC 2.7.9 is now available  you (I) have 2.6.6    
* It suggests that I download new version from
        https://keepassxc.org/download/
* After downloading and installing, I could not start KeePassXC.  I get the error message
         "api-ms-win-core-console-I2-1-0.dll" is missing 
* There are several sites offering to let me download missing dll's, but I'm wary that they may introduce nasty code. 
some were flagged by Norton Symantec as DANGEROUS
* I tried again downloading "KeePassXC-2.7.9-Win64.msi" , as well as restarting machine, but continued to have 
           "api-ms-win-core-console-I2-1-0.dll" is missing  issue
* To get KeePassXC running, I deleted KeePassXC from my machine and installed older version 2.6.6
  **If newer is incompatible with my machine, why do I keep receiving suggestions to update to KeePassXC 2.7.9** 
* I suspect the KeePassXC file thinks I'm running Win10 even though "winver" says Win7pro

**Comment by mpas97** [comment]
If you are using older than Windows 10/11 you have to download the legacy version of keepassxc, https://github.com/keepassxreboot/keepassxc/releases/download/2.7.9/KeePassXC-2.7.9-Win64-LegacyWindows.msi
