### ISSUE TITLE
Mount/unmount attachment as ramdisk

### ISSUE THREAD

**Issue by darkdragon-001** [keepassxreboot/keepassxc#11012]
## Summary
The "Open" feature for attachments seems to already support creating a ramdisk for an attachment and open a specific application.
For some workflows it is not possible to open an application with a path to a secret but explicitly set a file path for an operation. Therefore, it would be great if there would be an additional "Mount"/"Unmount" button. Might even be good enough to mount it to some arbitrary location and just copy the path to clipboard when mounted successfully.

## Examples
Using an "open file" dialog for a secret in a running app.

## Context
Currently, I have to manually save and delete the file and I have to manually take care that I don't accidentally specify a location included in my automatic backup.

**Comment by droidmonkey** [comment]
You must be root to do this and we won't be adding complexity to our attachment process.
