### ISSUE TITLE
keepassxc prompts to create a new database when a program tries to modify/access keyring entry.

### ISSUE THREAD

**Issue by siddhpant** [keepassxreboot/keepassxc#11015]
## Overview

When a program tries to modify (or maybe even access? I don't remember all the times it happened) an entry, keepassxc prompts to create a new database.

It does not happen always, so I don't know the reproduction steps.

It seems to happen when keepassxc is minimised to tray and I have the other tab opened (multiple dbs are opened). I fix this by opening and switching to the tab. (or maybe the tab is a red-herring)

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.7
Revision: 68e2dd8

[NOTE]: # ( Pick choices based on your environment )
Operating System: Debian testing
Desktop Env: Gnome
Windowing System: Wayland

**Comment by droidmonkey** [comment]
This is normal behavior if you set KeePassXC as the secret service provider and you have not designated a default collection. You need to either disable KeePassXC as a provider or you need to establish a default collection in an existing database. 

For reference the dbus call that does this is:

```
<method name="CreateCollection">
    <arg type="o" direction="out"/>
    <arg name="properties" type="a{sv}" direction="in"/>
    <annotation name="org.qtproject.QtDBus.QtTypeName.In0" value="QVariantMap"/>
    <arg name="alias" type="s" direction="in"/>
    <arg name="prompt" type="o" direction="out"/>
</method>
```

**Comment by siddhpant** [comment]
How do I establish a default collection?

**Comment by droidmonkey** [comment]
Application settings -> FDO Secrets tab

**Comment by siddhpant** [comment]
I see no such setting. Is it added in a newer version?

I just see "Exposed database groups", which lists the databases with `None` besides all except the keyring db (as expected).

**Comment by siddhpant** [comment]
This is due to issue mentioned in #8479 and #8611.

**Comment by droidmonkey** [comment]
Yes those would be the more relevant issue threads. I forgot you are using multiple databases.

**Comment by Lgmrszd** [comment]
I am having similar issue (not sure if its worth opening new issue): I have two databases, one with SecretService integration enabled and second one that automatically unlocks first one (Reason to this is that I use hardware key for convenience and I want to keep password as an option). Whenever I have both databases closed and application is requesting a secret, it first prompts me to unlock databases. After I do so (unlock second one with hardware key -> it unlocks first one with AutoOpen entry), application is able to gather its secrets but shortly after I receive 12 prompts to create a new database.

> Application settings -> FDO Secrets tab

I tried to check this but there's no such setting. On Secret Service Integration tab, only first database has a group exposed.
