### ISSUE TITLE
Mouse Click stops Autotype

### ISSUE THREAD

**Issue by zimbo86** [keepassxreboot/keepassxc#11018]
## Overview
I use Auto-Type to paste passwords into vsphere console sessions (where copy+paste is disallowed).
Using Keepass Legacy this was never an Issue, Autotype format is {DELAY 1000}{PASSWORD}
In the 1s delay i just click the password field where i want KeePass to type.
With KeePassXC nothing happens here

## Steps to Reproduce
1.  Change Auto-type sequence to {DELAY 1000}{PASSWORD}
2.  Choose auto-type from menu or press ctrl alt v
3.  Click Keepass Banner OK
4. Focus the Window, where the Auto-Type should happen (mostly with mouse)
5. No Auto-Type happens

## Expected Behavior
1. Press Ctr alt V
2. Focus windows where auto-type should happen
3. auto-type happens

KeePassXC - 2.7.9

Operating System: Windows 11

**Comment by droidmonkey** [comment]
Does the window title change? Are you trigger on one window and activating another? 

An easy fix to this would be to increase the initial typing delay in the application auto-type settings.

**Comment by zimbo86** [comment]
Thanks, I disabled all these title settings and it works like in keepass non-XC.

![image](https://github.com/keepassxreboot/keepassxc/assets/69269000/bcb5aed7-674b-48fe-8289-0416263eca20)
