### ISSUE TITLE
build fails on Linux Mint 18.2C

### ISSUE THREAD

**Issue by meckli** [keepassxreboot/keepassxc#1101]
Hi,
I cloned the repository as discribed, created /build in /src and changed into it. Then started to build with
`cmake -DWITH_TESTS=OFF ..`which stopped with error
## Expected Behavior
build should run without failure

## Current Behavior
build fails:

```
~/Downloads/keepassxc/keepassxc/src/build $ cmake -DWITH_TESTS=OFF ..
CMake Error at CMakeLists.txt:21 (include):
  include could not find load file:

    GetGitRevisionDescription


CMake Error at CMakeLists.txt:22 (get_git_head_revision):
  Unknown CMake command "get_git_head_revision".


CMake Warning (dev) in CMakeLists.txt:
  No cmake_minimum_required command is present.  A line of code such as

    cmake_minimum_required(VERSION 3.5)

  should be added at the top of the file.  The version specified may be lower
  if you wish to support older CMake versions for this project.  For more
  information run "cmake --help-policy CMP0000".
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring incomplete, errors occurred!
```

## Possible Solution
add the files missing

## Steps to Reproduce (for bugs)
see above

## Context
although I'm not used to building from source I tried it in the discribed way as I couldn't find an official .deb, a ppa or up-to-date version in the mint repos. Only keepassX can be found there.

## Debug Info
Operating system: OS Linux Mint 18.2 Desktop: Cinnamon 3.4.6
CPU architecture: ARCH Quad core Intel Core i7-4702HQ (-HT-MCP-) cache: 6144 KB
Kernel: KERNEL 4.11.0-14-generic x86_64 (64 bit)

Any help is very appreciated. Thanks in advance.

**Comment by TheZ3ro** [comment]
You have an old version of cmake on your system. Try to update it

Anyway you can run the AppImage on every GNU/linux distribution just fine, or try the unofficial deb package

**Comment by phoerious** [comment]
We have `cmake_minimum_required(VERSION 3.1.0)` in the main CMakeLists.txt file. The file your build is apparently missing is inside the cmake folder. Make sure you are building from the correct directory and not from src.

**Comment by meckli** [comment]
Alright, I started again in /cmake and it went through without errors. This worked without updating cmake-version. Next step was the following:
`~/Downloads/keepassxc/keepassxc/cmake $ cmake -j8
CMake Error: The source directory "~/Downloads/keepassxc/keepassxc/cmake/-j8" does not exist.
`
There's no directory "-j8" at all.

Now I'm looking for the executable file (keepassxc). Is there one which I can start without install.

**Comment by phoerious** [comment]
-j8 is a parameter for make, not cmake. You need to follow the build instructions more closely. Or simply download the AppImage from our downloads page.

**Comment by meckli** [comment]
Thanks a lot for your advice. You're right, I am buggy, not your code. I took the AppImage now and everything works fine. I really appreciate what you are doing. Goodnight.
