### ISSUE TITLE
KeePassXC 2.7.9 only starting as administrator but not as user

### ISSUE THREAD

**Issue by r1v4n** [keepassxreboot/keepassxc#11017]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. 
2. 
3. 

## Expected Behavior
KeePass starting when launched as user

## Actual Behavior
KeePass not starting when launched as user, only when starting as administrator

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.9
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 10
Desktop Env: 
Windowing System:

**Comment by droidmonkey** [comment]
Reinstall the MSVC redistributable: https://aka.ms/vs/17/release/vc_redist.x64.exe

And/or if you are access remotely: https://keepassxc.org/docs/KeePassXC_UserGuide#_screenshot_security
