### ISSUE TITLE
Updating over Microsoft Store doesn't work

### ISSUE THREAD

**Issue by DIYColin** [keepassxreboot/keepassxc#11026]
## Overview
After the release of a new version of KeePassXC Microsoft Store doesn't know that you need to update.

## Steps to Reproduce
1. Install KeePassXC in Microsoft Store
2. Wait for new KeePassXC Release
3. Open KeePassXC in Microsoft Store
4. No Update is displayed, it just shows that KeePassXC is installed

## Expected Behavior
KeePassXC new version pop-up should contain a link to KeePassXC in Microsoft Store, at least if it was installed over the Store.
KeePassXC installed out of Microsoft Store should be display a "Update" button in Microsoft Store if a new version is available.
This would enable autoupdating of KeePassXC if enabled in Microsoft Store.

## Actual Behavior
KeePassXC notifies about new version and directs to web page. Link on web page opens Microsoft Store, which just shows that KeePassXC is installed. You then have to uninstall KeePassXC via the system apps. After that reinstall over Microsoft Store with the new version works.

## Context
Issue is existing at least since version 2.7.6.

Current Version:
KeePassXC - Version 2.7.9
Revision: 8f6dd13

Qt 5.15.11
Diagnosemodus ist deaktiviert.

Betriebssystem: Windows 11 Version 2009
CPU-Architektur: x86_64
Kernel: winnt 10.0.22631

Aktivierte Erweiterungen:
- Auto-Type
- Browser-Integration
- Passkeys
- SSH-Agent
- KeeShare
- YubiKey
- Schnelle Entsperrung

Kryptographische Bibliotheken:
- Botan 3.1.1

**Comment by droidmonkey** [comment]
You cannot update "native" applications through the Microsoft store. Fresh installs only unless you are a UWP app.
