### ISSUE TITLE
Improve snap package trust by becoming a star developer

### ISSUE THREAD

**Issue by HendrikSchrieber** [keepassxreboot/keepassxc#11029]
## Summary
Please apply as a "Star Developer" for publishing the snap package. This helps users to verify that the snap actually comes from a trusted source which is important especially in a security-critical area like password management. Although I think the "Star Developer" concept is not a perfect solution it is better than nothing.

## Context
There already has been an issue to get a verified developer account for publishing the snap package: https://github.com/keepassxreboot/keepassxc/issues/4325. Ubuntu now provides a way for individual developers to become "Star Developers" to improve trust when installing packages from the snap store: https://forum.snapcraft.io/t/star-developers/30714.

**Comment by droidmonkey** [comment]
Nothing about that post speaks to security or even ownership of a project. I'm not interested in a popularity contest.
