### ISSUE TITLE
Use the Coverity Scan service with Travis CI?

### ISSUE THREAD

**Issue by adolfogc** [keepassxreboot/keepassxc#1102]
I am wondering if you're planning on using Coverity Scan. I saw that [KeepassX uses it](https://scan.coverity.com/projects/keepassx).

From their FAQ:

>**What is Coverity Scan?**
>Coverity Scan is a service by which Synopsys provides the results of analysis on open source coding projects to open source code developers that have registered their products with Coverity Scan.
>Synopsys, the development testing leader, is the trusted standard for companies that need to protect their brands and bottom lines from software failures. Coverity Scan is powered by Coverity® Quality Advisor. Coverity Quality Advisor surfaces defects identified by the Coverity Static Analysis Verification Engine (Coverity SAVE®) for fast and easy remediation.
>Synopsys offers the results of the analysis completed by Coverity Quality Advisor on registered projects at no charge to registered open source developers.

Source: https://scan.coverity.com/faq

Other revelant links:
- https://scan.coverity.com/travis_ci
- https://en.wikipedia.org/wiki/Coverity

**Comment by phoerious** [comment]
Not planned, but I think we should. @keepassxreboot/core-developers opinions?

**Comment by droidmonkey** [comment]
Totally down with this

**Comment by phoerious** [comment]
I submitted a build yesterday, waiting for project approval.

**Comment by TheZ3ro** [comment]
@phoerious let us know when it will be ready :wink:

**Comment by adolfogc** [comment]
@keepassxreboot/core-developers Results are ready: https://scan.coverity.com/projects/keepassxreboot-keepassxc

**Comment by phoerious** [comment]
I know. We already had a look at them. Nothing too severe.

**Comment by droidmonkey** [comment]
It doesn't recognize Q_UNUSED

**Comment by adolfogc** [comment]
Glad to hear only minor issues were found. What do you guys think is the best way of using this service with Travis CI? I was thinking on two possibilities:
- merge into the suggested `coverity_scan` branch every week or so?
- merge into the suggested `coverity_scan` branch before distributing a new release?
