### ISSUE TITLE
KeePassXC crashes ever since v2.7.6, terminal server, dfs

### ISSUE THREAD

**Issue by amelsburner** [keepassxreboot/keepassxc#11027]
## Overview
We have KeePassXC in our company on a distributed file system (dfs) and provide it via terminal servers on a published desktop. Everythings works fine with versions up to 2.7.5., but all versions thereafter, starting from version 2.7.6., crash and freeze as soon as the user opens the application, or when they open a database or add an entry within the database.

## Expected Behavior
I excpect the application to run as normal as it did up to v2.7.5

## Actual Behavior
The application freezes and then crashes. The entry the user may have made isn't safed.

## Context
No more information, it's the portable version of 2.7.6 to 2.7.8

KeePassXC - 2.7.6. and following

**Comment by droidmonkey** [comment]
Unfortunately you'll have to debug this situation on your side, there is no way we can replicate your environment. This is obviously not happening in any standard deployment situation. 

As a shot in the dark, recommend installing the latest MSVC redistributable package: https://aka.ms/vs/17/release/vc_redist.x64.exe

You can also try using the "legacy windows" release instead, but note windows hello is unsupported. https://github.com/keepassxreboot/keepassxc/releases/download/2.7.9/KeePassXC-2.7.9-Win64-LegacyWindows.zip

If you come back with more tangible information we can look to see if this is something on our end or the support libraries.

**Comment by amelsburner** [comment]
I tested the early pre-release version 2.8.0 and everything runs smoothly again. So, i will wait for the version upgrade.

**Comment by droidmonkey** [comment]
No, you need to update the msvc libraries. I haven't updated the CI msvc scaffolding yet, but once I do you won't work again
