### ISSUE TITLE
2.8.0-snapshot - Empty taskbar icon

### ISSUE THREAD

**Issue by Stephan-P** [keepassxreboot/keepassxc#11025]
The latest 2.8.0 snapshot (2024-07-02 13:15) displays an empty icon on the taskbar

![image](https://github.com/keepassxreboot/keepassxc/assets/10008599/ff39dcae-bcc7-4800-bd64-bfee0b9df5bc)

Debug information:
KeePassXC - Version 2.8.0-snapshot
Build Type: Snapshot
Revision: afe634d

Qt 5.15.11
Debugging mode is disabled.

Operating system: Windows 11 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.22631

Enabled extensions:
- Automatisch invullen
- Browserintegratie
- Passkeys
- SSH-agent
- KeeShare
- YubiKey
- Snel ontgrendelen

Cryptographic libraries:
- Botan 3.1.1

**Comment by droidmonkey** [comment]
hmmm good find! I got a little overzealous in moving resource files around the CMakeLists.txt in the GUI/Core separation PR. Easy fix.

**Comment by Stephan-P** [comment]
fix confirmed in 
KeePassXC - Version 2.8.0-snapshot
Build Type: Snapshot
Revision: 3c5f49d
