### ISSUE TITLE
Import function disables context-menu

### ISSUE THREAD

**Issue by XpPlayer845** [keepassxreboot/keepassxc#11037]
## Overview
After a successful import of entries from a .CSV file into an existing database all right-click context menus don't work any more.

## Steps to Reproduce
1. Open an existing database
2. Open the Database > Import... window
3. Perform a successful data-import into the existing (and open) database
4. Right-click doesn't open a context-menu any more (on Groups, Entries, ect.)
5. Closing & re-opening the database fixes the issue

## Expected Behavior
Context menus for right-click on Groups/Entries

## Actual Behavior
After the import context-menus stop working.

## Context
KeePassXC - Version 2.7.9
Revision: 8f6dd13

Operating System: Windows 10 - 22H2
CPU-Architecture: x86_64
Kernel: winnt 10.0.19045

Active extensions:
- Auto-Type
- Browser-Integration
- Passkeys
- SSH-Agent
- KeeShare
- YubiKey
- Fast unlock

**Comment by droidmonkey** [comment]
Confirmed, but preliminary debugging yielded no obvious reason. The signal is properly emitted when a right click is issued but it doesn't call the slot. There is no obvious reason why these get disconnected after an import operation.

FWIW, an easy reset for this situation (prior to a fix) is to open a second database, then switch back to the previous tab. Switching tabs resets the connections.

**Comment by droidmonkey** [comment]
Ugh found the cause, I really hate the QObject::disconnect function.

https://github.com/keepassxreboot/keepassxc/blob/afe634d4f2a0f32e96ea720289262a4be90afc0f/src/gui/wizard/ImportWizardPageSelect.cpp#L130

You don't even need to go through with an import to break the context menu, just opening the import dialog is enough.
