### ISSUE TITLE
Improve password complexity ratings explanations

### ISSUE THREAD

**Issue by ardz** [keepassxreboot/keepassxc#11034]
## Summary
KeePassXC sometimes reports long and complex passwords as weak when using the EFF large wordlist, even if they include special characters and have high complexity. This feature request aims to clarify and improve the password strength evaluation criteria to ensure genuinely strong passwords are not mistakenly rated as weak.

## Examples
- Detailed explanations within KeePassXC on why certain passwords are rated as weak, especially when using the EFF wordlist.
- Combined evaluation approach that considers both wordlist checks and traditional strength metrics (length, complexity, randomness).
- User-configurable settings to adjust the weight of wordlist checks versus complexity checks in the evaluation.
- Visual indicators or tooltips explaining which aspects of the password contributed to the weak rating (e.g., common words, insufficient length, lack of complexity).

## Context
ensures that users receive accurate feedback on the strength of their passwords. Inaccurate weak ratings for complex passwords can lead to confusion and frustration. By improving the evaluation criteria and providing clear explanations, KeePassXC can help users create truly secure passwords and enhance overall trust in the application's security features.

![keepasswtf](https://github.com/keepassxreboot/keepassxc/assets/6310248/87a4c967-8add-4567-b742-67875a992ac2)

**Comment by droidmonkey** [comment]
Passphrase is very different from passwords. Passphrase entropy / quality is calculated solely on the number of words chosen and the size of the word list. If you want to measure a password strength then copy that string over to the password tab.

Also, take screenshots by using View -> Allow Screencapture.

**Comment by droidmonkey** [comment]
Also see existing issue here: https://github.com/keepassxreboot/keepassxc/issues/10176

**Comment by ardz** [comment]
Thanks for the explanation. However, I believe there is some potential for UX improvement here. It is somewhat confusing that passphrases are treated differently from passwords, especially since both options are accessed via the "Password Generator" drop-down menu.

I assumed that selecting "passphrase" would generate "word-based passwords" similar to the concept popularised by the "correct horse battery staple" example ([xkcd comic #936](https://www.xkcd.com/936/)). In this instance, it's unclear what the specific difference is between a passphrase and a password within KeePassXC.

Providing clearer distinctions and explanations in the interface could help users understand how each type is evaluated and why certain passphrases might be rated as weak.

**Comment by droidmonkey** [comment]
We have robust documentation around this topic area: https://keepassxc.org/docs/KeePassXC_UserGuide#_password_generator
