### ISSUE TITLE
Tor Integration Does Not Work

### ISSUE THREAD

**Issue by KitchM** [keepassxreboot/keepassxc#11038]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
Browser integration for Tor does not work.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Install KeePassXC from appimage
2. Install Tor
3. Configure browser integration for Firefox and Tor
4. Install plugin in both browsers
5. Find it integrated with Firefox but not Tor

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Should be integrated.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
The Tor directory never gets the ./Downloads/tor-browser/Browser/TorBrowser/Data/Browser/.mozilla/native-messaging-hosts/ created or filled with anything.

## Context
[NOTE]: # ( Give us any additional information you may have. )
Tried to copy and finish directory structure and contents from firefox's .mozilla, but did not help.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.9
Revision: 8f6dd13
Distribution: AppImage

Qt 5.15.2
Debugging mode is disabled.

Operating system: Debian GNU/Linux 12 (bookworm)
DE: Xfce 4.18
CPU architecture: x86_64
Kernel: linux 6.1.0-22-amd64

Enabled extensions:
- Auto-Type
- Browser Integration
- Passkeys
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.19.1

**Comment by KitchM** [comment]
A nice person, varjolintu, tried to help me for an hour, but to no avail.  See the comments in the Element site.

**Comment by KitchM** [comment]
When I select Toolbar>Extensions icon>KeePassXC-Browser, I get a popup that states:
Are you a first time user? Please check our Getting Started Guide.
[Getting Started Guide - Setup Browser Integration](https://keepassxc.org/docs/KeePassXC_GettingStarted.html#_setup_browser_integration)

KeePassXC-Browser has encountered an error:
Message encryption failed. Is KeePassXC running?

Then I get a reload button.  It does not work to make connection.

**Comment by KitchM** [comment]
An interesting thing happens when I am working on this.  I start Tor and get a popup window that is entitled Desktop Integration - AppImage Launcher.  There are two long buttons at the bottom but there is no other text.  If I select the left one, it closes.  If I select the right one, another comes up entitled Warning – AppimageLauncher.  The left button has a red circle with an X, and right is a green circle.  I have no idea what they are about.  AppImage messages always display just fine at any other time with any other program associations.  There are some serious programming flaws here and it all points to KeePassXC.

Just to make things interesting, I got this message when going to KeePassXC>Tools>Settings>Browser Integration:
Error: The installed proxy executable is missing from the expected location: /home/xxxxx/Applications/KeePassXC-2.7.9-x86_64_09d5556e85a42ea0d6c4cf4fde417c0c.AppImage
Please set a custom proxy location in the advanced settings or reinstall the application.

**Comment by droidmonkey** [comment]
It works flawlessly, I just tested this without a single problem.

1. Download Tor and KeePassXC, unzip tor into Downloads folder:
![image](https://github.com/keepassxreboot/keepassxc/assets/2809491/3c58f9ca-6945-43d2-b6b0-b17f473008c0)

2. Open Tor and install the KeePassXC extension, ensure you check the box to allow it to be used in private tabs:
![image](https://github.com/keepassxreboot/keepassxc/assets/2809491/0bf89d08-1998-419d-b74f-4dec2b1580fd)

3. Open KeePassXC and setup the browser integration for advanced browser:
![image](https://github.com/keepassxreboot/keepassxc/assets/2809491/bae9da5a-71c9-4fd0-9f66-99fa8b26b887)

`~/Downloads/tor-browser/Browser/TorBrowser/Data/Browser/.mozilla/native-messaging-hosts/`

4. Go back to Tor and press _Reload_ on the extension and then _Reconnect_:
![image](https://github.com/keepassxreboot/keepassxc/assets/2809491/1bd64022-8718-4e97-9275-73087ad1f093)

5. Enter a unique id for the browser, press ok, then navigate to the website you want to log into.

**Comment by varjolintu** [comment]
So.. if you just launch the AppImage directly from terminal/shell, it works with the browser integration? Without the AppImageLauncher.

**Comment by KitchM** [comment]
Download which versions?

**Comment by KitchM** [comment]
Between your number 3 and 4, this happened:
![Screenshot_2024-07-07_17-34-01 - Tor with appimage popup 1](https://github.com/keepassxreboot/keepassxc/assets/371308/9e28752a-d7da-4d92-94d6-9fc4bb14f0bc)

**Comment by droidmonkey** [comment]
You must have AppImageLauncher installed and configured to "run" *.appimage files. I have no idea what that is and it isn't needed here. Just simply set the downloaded appimage as executable and open it.

https://github.com/TheAssassin/AppImageLauncher/issues/552

AppImageLauncher appears to be unmaintained, last update was in 2020.

**Comment by KitchM** [comment]
Do you think it has something to do with these:
![Screenshot_2024-07-07_18-06-00 - AppImageLauncher Settings first screen](https://github.com/keepassxreboot/keepassxc/assets/371308/29588952-29f1-4559-9b13-2f94227dd0d0)
![Screenshot_2024-07-07_18-06-51 - AppImageLauncher Settings second screen](https://github.com/keepassxreboot/keepassxc/assets/371308/10b49323-e416-4938-b86b-f5d63035b1c2)

**Comment by KitchM** [comment]
I uninstalled the launcher app, and downloaded, made executable and ran KeePassXC.  I ran Tor again and this popped up:
![Screenshot_2024-07-07_18-18-20 - KeePassXC key association request message](https://github.com/keepassxreboot/keepassxc/assets/371308/45d7f3b7-4369-4132-8dc9-9c40581198e9)
As I don't know what that means, there is no explanation and Firefox did not need it, I'm reluctant to fiddle with it.

**Comment by droidmonkey** [comment]
That is the connection request dialog, enter a name for the connection like `tor` and you are done. KeePassXC is then connected to Tor.

**Comment by KitchM** [comment]
Well, what do you know.  Its working!!!  I think I'll write those steps down.

Thank you very much for the good directions with those pictures.  Kudos!

**Comment by KitchM** [comment]
@droidmonkey  So I created a document for this, and I'd like to send it to you.  Please let me know how is best.

**Comment by droidmonkey** [comment]
team [at] keepassxc.org
