### ISSUE TITLE
Browser integration unable to connect with elevated KeepassXC

### ISSUE THREAD

**Issue by shdeb** [keepassxreboot/keepassxc#11033]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
As in the title; 

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
0. be logged in as a standard user
1. Run keepassxc.exe as administrator
2. open browser (firefox my case) with the keepass-browser extension installed
3. open extension page (popup) click reload.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
There should be successful communication between keepassxc-proxy.exe and keepassxc.exe

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
extension says `Key exchange was not successful.` (which is generic message, happens whenever it is unable to connect)
I have checked keepassxc-proxy.exe is running/restarting each time reload is pressed on the extension popup page.

I have verified the same is working when keepassxc.exe is run as standard user.

## Context
[NOTE]: # ( Give us any additional information you may have. )
KeePassXC folder has .portable file.

NativeMessagingHosts registry points to 
`C:/Users/_StandardUser_/AppData/Local/KeePassXC/org.keepassxc.keepassxc_browser_tor-browser.json`
it doesnot work even when it points to
`C:/Users/_AdminUser_/AppData/Local/KeePassXC/org.keepassxc.keepassxc_browser_tor-browser.json`
both json have the same path to keepassxc-proxy.exe (it is launching both times but no communication)

-------
[NOTE]: # ( Paste debug info from Help → About here )
-- debug info
KeePassXC - Version 2.7.8
Revision: f6757d3

Qt 5.15.11
Debugging mode is disabled.

Operating system: Windows 11
CPU architecture: x86_64

Enabled extensions:
- Auto-Type
- Browser Integration
- Passkeys
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 3.1.1

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows
Desktop Env: DWM
Windowing System: DWM

**Comment by shdeb** [comment]
How does the keepassxc-proxy.exe and keepassxc.exe communicate if it is client-server it should work even if one is eleveted

**Comment by droidmonkey** [comment]
Do not run keepassxc as administrator

**Comment by shdeb** [comment]
wanted to run as elevated in a standard env, as this #3460 is not implemented.

**Comment by shdeb** [comment]
will this work if i use the installed version, running as admin?

**Comment by droidmonkey** [comment]
Do not run keepassxc as administrator, and no it won't work and it will never work

**Comment by shdeb** [comment]
ok thanks.

**Comment by droidmonkey** [comment]
Just as an aside, the secure desktop feature does not work by elevating the process to admin. It basically creates an isolated event space (a new, isolated desktop process) that captures key presses and such. However, it is somewhat trivial to bypass if your computer is already infected with malware. 

Running a program as an administrator and allowing a non-privileged process to interact with it is the exact opposite of what you want. Generally speaking, you only ever want to run something as admin for the shortest time possible when needed.

**Comment by shdeb** [comment]
my goal was to isolate the keepassxc.exe from other standard processes, so i thought i can elevate it so that none of other standard processes can affect it, may be only authorized processes like keepassxc-proxy.exe can communicate with it.
i guess it was bit of a reach...
