### ISSUE TITLE
snap fails to open database on FAT flash drive under Ubuntu 17.10

### ISSUE THREAD

**Issue by J3RN** [keepassxreboot/keepassxc#1103]
## Expected Behavior

To be able to open a password database that lives on my flash drive.

## Current Behavior

Using the version of KeePassXC from the snap (AppImage works as expected) on Ubuntu 17.10 (snap works as expected on Debian sid), I get "Unable to open the database. Permission denied" when I try to open a password database from my flash drive (formatted as FAT—don't know if that's relevant) that is symlinked into my home folder. The snap only shows "home" under `/`, so I have to symlink the password database into my home folder to even attempt to open it. Copying the password database file from my flash drive to my home folder allows KeePassXC to open it.

## Possible Solution

I know snaps do some sort of sandboxing, but I have no clue how it works, unfortunately. That may be relevant.

## Steps to Reproduce (for bugs)
1. Format a flash drive as FAT.
1. Create a KeePass password database on said flash drive.
2. Under Ubuntu 17.10, run `sudo snap install keepassxc`
3. Open KeePassXC and attempt to open the password database on the flash drive.

## Context

I was previously running Debian sid, and was using KeePassXC from the snap. Everything worked—I could browse out to my flash drive and open the database. I just installed Ubuntu 17.10 an hour or so ago, and ran into this issue. Also worth noting is that the AppImage allows me to browse out to my flash drive whereas the snap does not.

## Debug Info

KeePassXC - Version 2.2.2

Libraries:
- Qt 5.6.2
- libgcrypt 1.6.6

Operating system: Ubuntu 17.10
CPU architecture: x86_64
Kernel: linux 4.13.0-16-generic

Enabled extensions:
- KeePassHTTP
- Auto-Type
- YubiKey

**Comment by droidmonkey** [comment]
https://keepassxc.org/docs#faq-appsnap-homedir

You might have to scroll up a little to see the FAQ answer.
