### ISSUE TITLE
Hidden data

### ISSUE THREAD

**Issue by MrCroller** [keepassxreboot/keepassxc#11031]
## Overview
The first time you enter the database, it does not display data

## Steps to Reproduce
1. Quit the application or run it for the first time
2. Unlock the database

## Expected Behavior
I'd like to see my notes.

## Actual Behavior
Blank screen with no entries or anything

## Context
What helps me is to open the unlock window of the DB. It is not even necessary to unlock it. Then I switch back and all data is returned

KeePassXC - Version 2.7.9
Revision: 8f6dd13

Qt 5.15.11
Debugging mode is disabled.

Operating system: Windows 11 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.22631

Enabled extensions:
- Auto Input
- Browser integration
- Passkeys
- SSH agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 3.1.1

**Comment by droidmonkey** [comment]
https://github.com/keepassxreboot/keepassxc/issues/10927#issuecomment-2180333104

A fix is in the works as well, but once you do the dragging you are fixed
