### ISSUE TITLE
Second url overwrite

### ISSUE THREAD

**Issue by AP2020C** [keepassxreboot/keepassxc#11030]
## Summary
I can add url overwriting by double clicking. 
However sometimes I need to open that url in another browser. 
I would like to be able to add an item to the context menu to open a second url in another browser.

## Examples
Some sites have the login page hidden under many clicks, so in the url field of my entries I put the main domain, and in the url override field I set to open the login page in a certain browser.
However sometimes I need to open the login page of the same site in a different browser.
So I would like to add an item to the context menu that launches a second url overwrite.

Another useful thing would be to have a list of url fields and to have a list of url(s) items in the context menu that open in a certain browser (or copy) the various url fields.

## Context
Some sites have the login page hidden under many clicks, and I need open it in different browsers.

**Comment by droidmonkey** [comment]
#5108
