### ISSUE TITLE
Unlock database without GUI for freedesktop secret service

### ISSUE THREAD

**Issue by sudoAlphaX** [keepassxreboot/keepassxc#11036]
## Summary
It would be helpful to be able to unlock the database from cli to allow access to secrets in keyring (for git, github-cli, etc). Currently, it either prompts a password prompt in a connected GUI display or it gives an error.

## Examples
User: tries to access secrets in keyring, using a tool such as git, from the cli.
System: prompts a dialog box to enter the keyring password to unlock keepassxc database, like the one with pinentry-curses or pinentry-cli (gnupg passphrase dialog box)

## Context
I feel that this is an important feature for a user to access keyring when the GUI isn't available, in cases like a SSH session.

**Comment by droidmonkey** [comment]
This would essentially require keepassxc to run as a daemon. I am fairly certain this won't ever happen since that is the opposite of how we operate today. You can do what you ask using the keepassxc-cli instead of the secret service API.

**Comment by sudoAlphaX** [comment]
Thank you for your reply. I understand that keepassxc will have no plans to be running as a daemon.


> You can do what you ask using the keepassxc-cli

Can you please give me an example on how to accomplish this task using keepassxc-cli?

**Comment by droidmonkey** [comment]
You can read the manpage which describes the interface quite nicely. I cannot know your specific situation.

**Comment by sudoAlphaX** [comment]
Well, i just found out that by providing the flag `-platform offscreen` and using `--pw-stdin` to provide password from stdin, i can unlock keepassxc client "headless-ly".
I can leave that open in one tmux window and use my tools (like git, gh, rclone, etc) which utilize secret service integration without any issues.
