### ISSUE TITLE
Copy button or right click to copy items in Advanced section

### ISSUE THREAD

**Issue by SheikYahbouti** [keepassxreboot/keepassxc#11045]
## Summary
Keepass original offers a copy function to copy (via right click) either the name or the value of any items added to the Advanced tab of an entry. KeepassXP should too.

## Examples

![KeePass_hz2QMrFFny](https://github.com/keepassxreboot/keepassxc/assets/97067434/15946455-ad61-4053-96da-c6c286fa8656)

## Context
Useful for credit card numbers, VIN numbers, etc.

**Comment by droidmonkey** [comment]
You do this from the preview panel (simply double click) or from the right click context menu on an entry in the entry view.
