### ISSUE TITLE
TOTP does not work with Google Authenticator

### ISSUE THREAD

**Issue by alasalamont** [keepassxreboot/keepassxc#11042]
## Overview
+ KeePassXC version: 2.7.9
+ Operating System: Windows 11

## Steps to Reproduce
1. Google Authenticator shows the QR code, choose `Can't scan it`, it will show 32-digit-key instead
2. From KeePassXC, paste this secret key in setup TOTP
3. From Google Authenticator app, paste this secret key 
4. Compare between KeePassXC and Google Authenticator app. The code shows differently

**Comment by droidmonkey** [comment]
Sync your computer time
