### ISSUE TITLE
All of my password entries disapeared

### ISSUE THREAD

**Issue by KingKDot** [keepassxreboot/keepassxc#11048]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
Not too sure what happened but all of a sudden all of my entries are gone. I believe they're still there just hidden or something similar. When going on sites with the extension it will still fill passwords.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
I honestly have no idea how I even did it.

## Expected Behavior
I expected to be able to see all of my passwords like usual

## Actual Behavior
Everything is blank and the only option I get when I right click is to add an entry.

## Context
My passwords seem to be safe but I'm unable to access them. I've already restarted my pc and redownloaded the UI.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.9
Revision: 8f6dd13

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows

**Comment by droidmonkey** [comment]
https://github.com/keepassxreboot/keepassxc/issues/10927#issuecomment-2180333104
