### ISSUE TITLE
 KeepassXC Not Remembering Database on restart of app (Reopening #8032)

### ISSUE THREAD

**Issue by ghost** [keepassxreboot/keepassxc#11049]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
KeePass should load "previously opened database on startup", but does not. Version is 2.6.6

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Install KeePass on a fresh Linux Mint 21.3 system
2. I used a previously created database.
3. I changed the settings to start with system and load previously used db.
4. opening with terminal instead gives no relevent info.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Prompt me for the password of the previously used database, not make me find it from the list.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Already stated

## Context
[NOTE]: # ( Give us any additional information you may have. )
I already have. I already deleted .cache in home directory.

[NOTE]: # ( Paste debug info from Help → About here )
Version is 2.6.6 from Linux Mint 21.3 apt repository

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux x64 (traditional AMD laptop, not ARM)
Desktop Env: Cinnamon
Windowing System: Not known

**Comment by ghost** [comment]
sudo apt purge keepassxc fixed the problem, but there is still a bug somewhere. (I also deleted the ini in .cache again.)

**Comment by droidmonkey** [comment]
We are on version 2.7.9

**Comment by skersdaniel** [comment]
Wonderful that you're on 2.7.9. Thank you for your work, but it's doubtful it's been fixed from that time.

**Comment by skersdaniel** [comment]
Ok, I looked at the release history, yes, Linux Mint's apt repository for this project is long out of date. (2021)
