### ISSUE TITLE
"Lock database after inactivity" is on although it should not be

### ISSUE THREAD

**Issue by andkopp** [keepassxreboot/keepassxc#11040]
## Overview
The database locks itself after 10 seconds inactivity. This behavior first occurred after upgrading to KeePassXC 2.7.9 (probably from 2.7.8). I didn't activate this feature - and the Applications Settings UI also does not show it active.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Open KeePassXC.
2. Unlock database.
3. Wait 10 seconds.
4. Database locks itself automatically.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
1. Open KeePassXC.
2. Unlock database.
3. Wait 10 seconds.
4. Nothing happens. The database is still unlocked.

## Context
- Under `Application Settings / Preferences > Security > Timeouts` the checkbox `Lock database after inactivity of (10 sec)` is **not active**. 
- `keepassxc.ini` contains `LockDatabaseIdleSeconds=10`. The line existed before and still exists after the upgrade to 2.7.9.

KeePassXC - Version 2.7.9
Revision: 8f6dd13

Operating System: macOS

**Comment by andkopp** [comment]
I have found a **workaround** to get the expected behavior:
- Set the checkbox `Lock database after inactivity of (10 sec)`. Then the following line is added to the keepassxc.ini: `LockDatabaseIdle=true`. This parameter didn't exist before.
- Reset the checkbox `Lock database after inactivity of (10 sec)`. The parameter is set to `LockDatabaseIdle=false`.

**Comment by droidmonkey** [comment]
There were no changes to that code for a few years, certainly not between 2.7.8 and 2.7.9. The default value of the LockDatabaseIdle is _false_ so if it is not in the ini then it is false and unchecked. I also cannot reproduce this at all.

**Comment by WGH-** [comment]
I also had this problem when upgrading from 2.7.7 to 2.7.8. Autolocking was off in the settings, but KeePassXC still locked itself automatically after 240 seconds (the grayed out value in the disabled input).

Neither `LockDatabaseIdle` nor `LockDatabaseIdleSeconds` existed in `~/.config/keepassxc/keepassxc.ini` file.

Toggling the setting in  the interface fixed this. `LockDatabaseIdle=false` appeared in the ini file, and KeePassXC no longer locks itself.

(What's also weird is that I upgraded the package more than month ago, but only noticed the issue today. Perhaps, I never restarted KeePassXC until I rebooted the system, I dunno)

KeePassXC 2.7.8, Gentoo Linux. No distro-specific patches

**Comment by andkopp** [comment]
Yesterday, I had this issue **once** again although `LockDatabaseIdle=false` was set. Toggling the setting in the interface seems to have fixed it for this session. I tried to reproduce it (no cursor movement, moving KeePassXC in the background), but I could not.

The device (Macbook Pro 16" 2016) is _always on_. I close and lock the device quite often which also locks KeePassXC (`LockDatabaseScreenLock=true` is set). I am using KeePassXC everyday so maybe this issue is rather rare, at least as long as `LockDatabaseIdle=false` is set.
