### ISSUE TITLE
Can not open database in other apps...

### ISSUE THREAD

**Issue by aconetwork** [keepassxreboot/keepassxc#11046]
## Overview
New or existing database works inside `KeepassXC` but then this same database on `Keepass2Android 1.10-pre` gives me `The file header is corrupted`, `KPass 2.3.2` gives me also an error . A month ago same database saved then worked normally on both `KeepassXC` and `Keepass2Android`. I also tried each one by one combo not successful:

- AES, TwoFish, ChaCha20 
- Argon2d, Argon2id, AES-KDF

## Steps to Reproduce
1. Create new database or save existing one with `KeepassXC 2.7.7` or `2.7.9` (FlatPak).
2. Open it in `Keepass2Android` or `KPass`.

## Expected Behavior
Opens up database to edit and view the data.

## Actual Behavior
`Keepass2Android` gives me `The file header is corrupted`.

## Debug
KeePassXC - Version 2.7.9
Revision: 8f6dd13
Distribution: Flatpak

Qt 5.15.10
Debugging mode is disabled.

Operating system: KDE Flatpak runtime
CPU architecture: x86_64
Kernel: linux 5.15.0-113-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- Passkeys
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 3.3.0

Operating System: Linux Mint 21.3 x86_64
Desktop Env: Cinnamon
Operating System: Android 12, MIUI 13.0.6

**Comment by droidmonkey** [comment]
You should file bugs with those apps. More likely however, you have failed to properly sync the files around.
