### ISSUE TITLE
Right click and edit

### ISSUE THREAD

**Issue by xelukali** [keepassxreboot/keepassxc#11052]
Greetings, I am a windows 10 pro user and I just downloaded your programme. I created my database and transferred the passwords in my current browser to this database. However, after being open for a while, right click on the folders in the database section does not work (mini pop-up window does not come with options such as delete group, edit group, etc.).

**Comment by droidmonkey** [comment]
Hello, this has been reported and a fix is on the way. It'll work if you don't open the import wizard.  https://github.com/keepassxreboot/keepassxc/issues/11037

To fix it now, simply lock and unlock your database.
