### ISSUE TITLE
Datenbank zeigt keinen Inhalt, bei Öffnen, wenn Schlüsseldatei verwendet wird

### ISSUE THREAD

**Issue by Manuel3190** [keepassxreboot/keepassxc#11053]
Ich nutze mein KeePassXC über einen NAS Speicher, welcher per SMB mit meinem Windows11 verbunden ist.
Inklusive einer Schlüsseldatei, die liegt lokal am Windows 11 Gerät. (logischerweise)

Das Problem:
Wenn der PC in Standby geht und danach entsperrt wird, ist es immer so das KeePass den Inhalt der Datenbank nicht anzeigt.
Erst nach dem Suchen nach Einträgen wird der gesuchte Inhalt aufgelistet nicht aber alle Passwörter der Datenbank.
Danach muss das ganze KeePass geschlossen werden und erneut geöffnet werden, um den Inhalt wieder normal anzeigen zu können.

Meine Vermutung: Die Schlüsseldatei ist schuld.

Nutze in der Firma auch KeePassXC aber ohne Schlüsseldatei, dort gibt es keine Probleme mit der Anzeige.

Hat da jemand Erfahrung oder vl einen Rat wie man den Fehler umgehen kann?

In den Einstellungen habe ich schon gesucht, ich habe dazu nichts Spezielles gefunden.

Danke für eure hilfe ;)

**Comment by droidmonkey** [comment]
https://github.com/keepassxreboot/keepassxc/issues/10927#issuecomment-2180333104
