### ISSUE TITLE
Auto-type list sort on usage stats

### ISSUE THREAD

**Issue by tall-r** [keepassxreboot/keepassxc#11058]
## Summary
[TIP]:  # Please add functionally to auto-type dialog to sort sequences based on usage statistics.
[NOTE]: # Move on top most recent sequences in Auto-type dialog. If I use some type sequence often then others then move it on top   of the list proposed type sequences.

**Comment by tall-r** [comment]
For some windows I have more then 10 different type-sequences. It will be useful if most recently used sequences will be on top of the list.

**Comment by droidmonkey** [comment]
We don't track usage of sequences, nor store that information. We won't add that because it would be a largely unnecessary overhead. You can add a comment to each window sequence using `{c:comment here}`

**Comment by tall-r** [comment]
I'm sorry but how comment in type sequence will help me?

**Comment by droidmonkey** [comment]
Put a comment on your most used sequence so it's easier to find. You can also sort by the sequence column and the comment could be made to sort on top or bottom.
