### ISSUE TITLE
A bit broken symbols in the UI after upgrade

### ISSUE THREAD

**Issue by gonchik** [keepassxreboot/keepassxc#11057]
## Overview
Version
1. on version 2.7.9 
2. MacOS m1 - Sonoma 14.5 (23F79)
After updating from 2.7.5 to 2.7.9.

UI is a bit broken. 

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1.  update from version 2.7.5 to 2.7.9
2. Open KeepassX
3. choose your DB

## Expected Behavior
Correct visualisation of folders and UI elements

## Actual Behavior
looks like some issue with fonts 

## Context

**Comment by phoerious** [comment]
This is an extremely vague description. Do you have a screenshot (need to disable screen capture protection first)?

**Comment by gonchik** [comment]
@phoerious  yeap, I put a screenshot, but that screenshot included in the comment sensitive information. 


But After reinstalling the keepassx it is fixed. 
with following steps: 
`rm -rf /Applications/KeePassXC.app/Contents/*`

and after installing back a new version, it works well.

**Comment by gonchik** [comment]
Let's close for now as Can't reproduce it.
