### ISSUE TITLE
Not obvious how to enter Preferences on Mac

### ISSUE THREAD

**Issue by bhavers** [keepassxreboot/keepassxc#1105]
## Expected and Current Behavior

With KeePassXC on Mac there is no direct visual clue on how to open the preferences Window. It is only possible to open Preferences by from the menu bar at the top of the screen. I understand this is standard Mac behavior, but being new to Mac this confused me quite a lot. Only when i maximized the window i understood how i could enter Preferences (as the menu bar seems integrated with the app window).

## Possible Solution

I propose to put a Preferences button on the toolbar. There is more than enough space.

## Debug Info

KeePassXC - 2.2.1

Operating system: MacOS Sierra
CPU architecture: Intel

**Comment by TheZ3ro** [comment]
IDK, if we place it in the toolbar then all users will complain against it being in the toolbar since it's already in the menubar (that is the standard behavior in almost every platform)

**Comment by phoerious** [comment]
I think, this is a WONTFIX. I don't like yet another button in the toolbar. macOS has a global toolbar, that's just how the platform works.
