### ISSUE TITLE
KeepassXC Won't Open

### ISSUE THREAD

**Issue by GittinURKnowledge** [keepassxreboot/keepassxc#11059]
## Overview
When opening the application, an error is thrown:

Faulting application name: KeePassXC.exe, version: 2.7.9.0, time stamp: 0x6673531d
Faulting module name: MSVCP140.dll, version: 14.29.30133.0, time stamp: 0x60ff28cc
Exception code: 0xc0000005
Fault offset: 0x0000000000013020
Faulting process id: 0x0x19F0
Faulting application start time: 0x0x1DAD2D4570A920A
Faulting application path: C:\Program Files\KeePassXC\KeePassXC.exe
Faulting module path: C:\Windows\SYSTEM32\MSVCP140.dll
Report Id: de5ff0ca-e4d0-48e4-9758-c6fcdfc8753b
Faulting package full name: 
Faulting package-relative application ID: 

I checked the modified dates on the MSVCP140.dll and nothing has changed on that file since 2021.

I've stopped antivirus, uninstalled Keepass, rebooted, kill a/v again, reinstalled and still nothing - same error as above.

## Steps to Reproduce
1. Launch the application - doesn't matter how (task bar, file system, start menu) 

## Expected Behavior
App opens

## Actual Behavior
Nothing happens

## Context
Installed these Windows updates this morning:
KB5040442
KB5039895
KB5040711
KB5041080

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.9

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows

**Comment by phoerious** [comment]
#10925
