### ISSUE TITLE
Unable to open KeepassXC 2.7.9

### ISSUE THREAD

**Issue by kalfilla** [keepassxreboot/keepassxc#11056]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
After install latest 2.7.9 version I was unable to open KeepassXC

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Install 2.7.9
2. try to open, nothing happends
3. 

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Open latest keepassXC

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
 I rolled back to 2.7.8

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.9

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows

**Comment by kropkrop** [comment]
Yes, same issue here. It worked for a while but this morning it did not open anymore. Neither automatically at windows startup nor manually. Also reinstallation didn't fix it, only rolling back to 2.7.8 did. Maybe a Win update issue?

**Comment by droidmonkey** [comment]
https://github.com/keepassxreboot/keepassxc/issues/10925
