### ISSUE TITLE
Database appears empty since update to 2.7.9

### ISSUE THREAD

**Issue by mathieulawnik** [keepassxreboot/keepassxc#11066]
## Overview
My keepass database appears empty since updating KeepassXC to version 2.7.9. The database is not corrupted; the "regular" Keepass app opens the database correctly.

## Steps to Reproduce
1. Open a database created with KeepassXC < 2.7.9

## Expected Behavior
Entries are shown.

## Actual Behavior
Entries are not visible (status bar says "0 entries").

## Context
The database is locked with a password and a key file. The format is KDBX4. The statistics page reports the correct number of password / groups inside the database. This seems to be just an UI bug ?

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.9

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 11

**Comment by phoerious** [comment]
#10927
