### ISSUE TITLE
No network folders

### ISSUE THREAD

**Issue by YamadaHideki** [keepassxreboot/keepassxc#11067]
In fedora 40, kde plasma, there is no 1st network folder when selecting database. On Windows there is a selection. The program is installed from Fedora repository.
![image](https://github.com/user-attachments/assets/f398b981-4f31-499e-9601-502c7c8ab0da)

**Comment by droidmonkey** [comment]
If you installed as a snap, then you need to allow access to media plug. Otherwise this isn't a keepassxc issue and you need to make your network devices available for use to applications. You can probably find information on Fedora forums or blogs.

**Comment by YamadaHideki** [comment]
> If you installed as a snap, then you need to allow access to media plug. Otherwise this isn't a keepassxc issue and you need to make your network devices available for use to applications. You can probably find information on Fedora forums or blogs.

Ty, i will try
