### ISSUE TITLE
Chinese characters are garbled when exported/imported

### ISSUE THREAD

**Issue by bestv5** [keepassxreboot/keepassxc#11060]
1.导出密码库到csv文件时，中文会乱码。
2导入时，中文同样会乱码

1. When exporting the password library to a csv file, Chinese characters will be garbled.

2 When importing, Chinese characters will also be garbled

**Comment by qbast** [comment]
What operating system do you use?  I created a password entry with your text as username and password, then exported it to csv file.

I got expected output:
```
"Group","Title","Username","Password","URL","Notes","TOTP","Icon","Last Modified","Created"
"1Password/Login","test - bug","导出密码库到csv文件时","，中文会乱码。","","","","0","2024-10-07T19:42:25Z","2024-10-07T19:42:12Z"
```
Then I reimported this CSV as a new database and it did not create any garbled characters.


I am using Kubuntu 24.04

**Comment by droidmonkey** [comment]
I cannot replicate this either

**Comment by bestv5** [comment]
win10 pro 21h2





来自阿里邮箱Android客户端------------------------------------------------------------------
***@***.***>
日　期：2024年10月08日 03:50:04
***@***.***>
***@***.***>; ***@***.***>
主　题：Re: [keepassxreboot/keepassxc] Chinese characters are garbled when exported/imported (Issue #11060)

What operating system do you use? I created a password entry with your text as username and password, then exported it to csv file.
I got expected output:
"Group","Title","Username","Password","URL","Notes","TOTP","Icon","Last Modified","Created"
"1Password/Login","test - bug","导出密码库到csv文件时","，中文会乱码。","","","","0","2024-10-07T19:42:25Z","2024-10-07T19:42:12Z"

Then I reimported this CSV as a new database and it did not create any garbled characters.
I am using Kubuntu 24.04
