### ISSUE TITLE
Changelog is not maintained

### ISSUE THREAD

**Issue by C0rn3j** [keepassxreboot/keepassxc#1106]
https://github.com/keepassxreboot/keepassxc/issues/499

Basically the same issue as this one again, perhaps add maintaining the changelog to the release process? ^^

**Comment by phoerious** [comment]
It is maintained. Just the Wiki page isn't really.

**Comment by C0rn3j** [comment]
Oh I see.

Wouldn't it be better to just have the wiki page link to the CHANGELOG file then?

**Comment by phoerious** [comment]
The original idea was to add some more information about what kind of change this is by using star and lock emoji. But it's not really maintained. Maintained are the CHANGELOG file and the AppStream description file. You'll also find a copy in our release announcements in our blog and as part of the release merge commit message on master.

**Comment by lurch** [comment]
I hope you don't mind me commenting on a very old closed issue, but it seems like things have got out of sync again?

- The website at https://keepassxc.org/ says the latest release is 2.5.3

- https://keepassxc.org/project/ has a "full KeePassXC changelog" link to https://github.com/keepassxreboot/keepassxc/wiki/KeePassXC-Changelog but the newest entry in there is only 2.4.3

- https://github.com/keepassxreboot/keepassxc/blob/develop/CHANGELOG.md agrees that the latest (released) version is 2.5.3


I'm totally new to KeePassXC, so I've no idea whether the "correct fix" would be to update the wiki page, or if it'd be better to just link https://keepassxc.org/project/ directly to https://github.com/keepassxreboot/keepassxc/blob/develop/CHANGELOG.md ?

(I've been a long-time KeePassX 0.4 user, but it seems the time has finally come to switch to a better-maintained project! :grinning: )

**Comment by droidmonkey** [comment]
Its more appropriate to link to the changelog of the master branch

**Comment by lurch** [comment]
Ah, I didn't even notice there were multiple branches! :laughing: 
I just found https://github.com/keepassxreboot/keepassxc/blob/master/CHANGELOG.md (which also agrees that the latest release is 2.5.3, and doesn't mention any unreleased features).

So, who's responsible for updating the https://keepassxc.org/ website? :wink: 
Also, for the benefit of anybody following an outdated link, does it make sense for https://github.com/keepassxreboot/keepassxc/wiki/KeePassXC-Changelog to be edited to instead direct the reader to https://github.com/keepassxreboot/keepassxc/blob/master/CHANGELOG.md ?

Should / could this issue be re-opened until the website (and/or wiki) is updated?

**Comment by droidmonkey** [comment]
Done
