### ISSUE TITLE
keepass injects ampersand character into the password, mostly at beginning

### ISSUE THREAD

**Issue by chkloos** [keepassxreboot/keepassxc#11061]
## Overview
* If password begins with some characters (e.g. c, f, 1, but not a, b, d, e - just some examples), then Keepass adds an Ampersand `&` in front.
* Sometimes also inside of the string, e.g. the password `gak` becomes `ga&k`. Here problems with different characters? Logic unclear.
* Independent from editing in the "hidden mode" (where only points are shown), or in the "password visible mode"
* Happens in the password generator text field too, and also in the database password field (see steps)

## Steps to Reproduce
* Type `c`  into the empty password field, or paste `c` into the password field. When typed this single character, Keepass already adds `&` in front, resulting in `&c`.
* Close, open again, Ampersand is still there
* Copy the password into clipboard, the Ampersand is contained too
* Try to delete the leading ampersand (put cursor at beginning, type delete button) adds it immediately again
* Create a new fresh database. It already happens when being asked to type a password for this database into the two password text fields

## Context
* KDE/Plasma X11 ; qt6ct-style (but changed to a different didn't help)
* The bug is not new, I already have it for some time (as far as I can remember at least a year)
* German localization
    * switched in the keepass settings to "English (United States)"
    * behavior has changed: `c` character works, but now `b` produces this behaviour
    * switched back to German, now old behaviour again
    * by the way: no errors/warnings on the console which can be related to this problem, except these font errors

```
QFont::fromString: Invalid description 'Hack,10,-1,5,400,0,0,0,0,0,0,0,0,0,0,1'
QFont::fromString: Invalid description 'Noto Sans,9,-1,5,400,0,0,0,0,0,0,0,0,0,0,1'
KeePassXC - Version 2.7.9
Revision: 8f6dd13

Qt 5.15.14
Debugging mode is disabled.

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 6.9.7-arch1-1

Enabled extensions:
- Auto-Type
- Browser Integration
- Passkeys
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 3.4.0
```

Note: because of the font error I tried to switch the monospace font, but didn't help. Now, I got the additional error line regarding the font called "Hack". At beginning, I only got the one line regarding "Noto Sans".

**Comment by droidmonkey** [comment]
This is the tracking issue for auto-type keyboard layout problems: https://github.com/keepassxreboot/keepassxc/issues/7881

**Comment by chkloos** [comment]
nope (please excuse me)

* Switched to US keyboard layout without deadkeys, did not solve the issue
* Note, that the pasting from clipboard (means: without typing) leads to the same problem, and removing the ampersand does not work too.
* Also neither talking about autotype (since it happens when editing the password text field, not when extracting it using autotype), nor that arbitrary characters are added (since it's always an ampersand character that makes the fun)

Addendum: with "pasting from clipboard" I mean: copy&paste from somewhere else into the keepass password text field, and not autotype from keepass to some other application, If copy&paste from keepass to somewhere else (still not autotype), the ampersand is contained in the string too.

**Comment by droidmonkey** [comment]
If this is impacting copy paste as well then this is 100% on your system and not us. You might have something interfering with typing in general

**Comment by chkloos** [comment]
1. We are in Keepass inside of a password dialog
2. The password text field is empty
3. I set the cursor to the empty password text field, and type `c`
4. Keepass shows two characters. Two dots, or if I make the password visible: `&c`

Now somebody may say: that's a display error, because I use X11 instead of Wayland. To go ahead of this class of possibilities, I did some additional steps:

5. copy the password from Keepass
6. paste it somewhere else
7. the pasted text (somewhere else): `&c`
8. Proves: it wasn't a display error, the ampersand is really part of the string

Now may read only the last steps, and would say: that's a clipboard error, 100% on my system. Then we would go back to step 1.

And of course, somebody may say, this is thing with the keyboard layout, or the localization, or I should create a new database from scratch, and I should run it from console to see output... then see first post.

**Comment by droidmonkey** [comment]
If you have password hidden then you cannot use dead keys, that is a qt problem. 

Otherwise, if the password is visible and you type and wrong things come out then that is 100% your system configuration. Find me anyone else with the problem you describe, never heard this before.

**Comment by Logarithmus** [comment]
I'm having the same problem on 2.7.9 KeePassXC GUI on Void Linux. When I try to create database, I can't do that, because this stupid ampersand & character is automatically inserted randomly and so password and confirm password fields don't match! I'm forced to use this "wonderful" program at work

**Comment by droidmonkey** [comment]
Does anyone else at your work experience this problem?

**Comment by Logarithmus** [comment]
@droidmonkey they mostly use mac or windows so no.
By the way, I was able to create database by CLI and then use it in GUI and it works. But it's a workaround, not a fix

**Comment by droidmonkey** [comment]
Is there only one text field that ambersands appear?

**Comment by Logarithmus** [comment]
@droidmonkey well, it also appears in other password fields. For example, if I try to create new password entry manually in GUI instead of using browser extension. This annoying & appears and so the wrong password is being saved. And I tried pressing the "eye" icon, and then pasting password or typing it from scratch, same effect, annoying & appears at seemingly random place

**Comment by Logarithmus** [comment]
@droidmonkey I could record a video on new dummy password database showing this problem, or try using a debugger, but unfortunately I'm short on time, and with browser extension it kinda works... So not a blocker for my work anymore fortunately

**Comment by droidmonkey** [comment]
This is definitely a weird Qt bug, something on Linux desktop environment is triggering it on password fields.

**Comment by chkloos** [comment]
For me it turned out, that it happens in conjunction with QtCurve. Without QtCurve everything is fine.

**~/.config/kdeglobals**
```
[General]
widgetStyle=QtCurve
```
(may also be activated in environment variables.)

However, this issue is only for Keepass Password text fields, and nowhere else. Therefore, something in Keepass is special too.

Because of this issue, I don't use QtCurve anymore.

**Comment by Logarithmus** [comment]
@chkloos huge thanks, looks like uninstalling `qtcurve` solved the issue!
