### ISSUE TITLE
app does not open (windows 10)

### ISSUE THREAD

**Issue by wotography** [keepassxreboot/keepassxc#11076]
## Overview
after update to 2.7.9 on windows, keepassxc will not open.

## Context
First I updated from the version prior. then i uninstalled the app and installed it again. still, the application does not open. Tas manager tells me for a second keepassxc is open, but then it quits imediatly.

KeePassXC - 2.7.9 installer
Revision: I dont know - REVISION

Operating System: Windows 10Pro 22H2
Desktop Env: I dont know - Gnome/KDE/XFCE/Mate/Cinnamon
Windowing System: I dont know - X11/Wayland

**Comment by droidmonkey** [comment]
#10925
