### ISSUE TITLE
Lost The Ability to See Groups

### ISSUE THREAD

**Issue by rex-invoca** [keepassxreboot/keepassxc#11074]
## Overview

No Groups pane or Tags pane.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Simply open KeepassXC then enter the password for the database

## Expected Behavior

I expect to see the groups pane at left, passwords pane at right, tags pane at lower left, and preview pane at lower-right.

## Actual Behavior

I cannot see any groups in my Keepass database.   I only have two windows, one on top where the passwords are listed, and the preview window at bottom. I've tried resetting to defaults, to no avail.  The Tags window is missing as well. The tags are still present in the actual Password entries.  I am not in compact mode.

If I create a new group to test, and add a password to that group, I am "locked" into that group ie. I cannot see any passwords not in that group until I restart the app.  There is no way to back out of the group.

## Context

It possibly seems reminiscent of:

https://github.com/keepassxreboot/keepassxc/issues/7438

I don't use any programs other than KeepassXC, but I DO, however, have my .kdbx file shared via SAMBA to a Windows machine, and I do sometimes open it from that machine.  I've been doing this for years, though, without issue.  Before now.

FWIW, I nuked everything in  ~/Library/Application Support/Keep*

[NOTE]: # ( Paste debug info from Help → About here )

KeePassXC - Version 2.7.7
Revision: 68e2dd8

Qt 5.15.11
Debugging mode is disabled.

Operating system: macOS 14.4
CPU architecture: x86_64
Kernel: darwin 23.4.0

Enabled extensions:
- Auto-Type
- Browser Integration
- Passkeys
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 3.1.1

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS

**Comment by droidmonkey** [comment]
#10927

**Comment by d3rb3rt** [comment]
Hi @rex-invoca,

I had the same problem, turned out the groups panel was just minified.

It's really hard to notice, but when you move your mouse slowly towards the left edge of your entry pane, a resizing icon should appear just at the very end. Click and pull it to the right, and your groups are visible again.

Hope that helps

**Comment by bobblkabb** [comment]
Works, thank you! Barely visible on dark theme and even then it's hard to drag and shift.

**Comment by jimtuttle** [comment]
> Hi @rex-invoca,
> 
> I had the same problem, turned out the groups panel was just minified.
> 
> It's really hard to notice, but when you move your mouse slowly towards the left edge of your entry pane, a resizing icon should appear just at the very end. Click and pull it to the right, and your groups are visible again.
> 
> Hope that helps

Thanks so much!

**Comment by RCG-RCorrales** [comment]
> Hi @rex-invoca,
> 
> I had the same problem, turned out the groups panel was just minified.
> 
> It's really hard to notice, but when you move your mouse slowly towards the left edge of your entry pane, a resizing icon should appear just at the very end. Click and pull it to the right, and your groups are visible again.
> 
> Hope that helps

Oh shit! This fixed it for me too. Perhaps it's a UI glitch

**Comment by RandomlyHuman** [comment]
Muchas gracias, me ocurría lo mismo.

**Comment by SebDieBln** [comment]
Yes, fixed it for me, too.

**Comment by Fernando-A-Rocha** [comment]
> It's really hard to notice, but when you move your mouse slowly towards the left edge of your entry pane, a resizing icon should appear just at the very end. Click and pull it to the right, and your groups are visible again.


Wow thanks, this worked! I dragged the groups panel on the left to increase it in width and I can see it fully again!
