### ISSUE TITLE
Autotype does not work on macos sequoia beta 5

### ISSUE THREAD

**Issue by vraravam** [keepassxreboot/keepassxc#11078]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Create a keepass password store
2. Enable global auto-type (I have `Cmd+Opt+Ctrl+v`)
3. Open a browser to some page with a login screen
4. Type `Cmd+Opt+Ctrl+v` key combo

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
The auto-type choices window shows up with whatever's applicable for that url

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
![WhatsApp Image 2024-07-18 at 11 54 01 AM](https://github.com/user-attachments/assets/6b04186d-009d-474b-a382-04f549506f4c)

## Context
[NOTE]: # ( Give us any additional information you may have. )
Running Macos Sequoia beta 5 where the preferences screens have been revamped.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.9
Revision: 8f6dd13

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS sequoia
Desktop Env: 
Windowing System:

**Comment by varjolintu** [comment]
Did you add the permissions to macOS settings?

**Comment by vraravam** [comment]
I had all permissions set when I was on Ventura. Now, im running macos sequoia beta 5. Whatever permissions that I could think of (for eg screen recording), I have given to KeepassXC and restarted both the app, and rebooted the OS. No change in behavior.
<img width="714" alt="Screenshot 2024-07-19 at 9 49 41 PM" src="https://github.com/user-attachments/assets/c20246a5-a94f-4907-a43d-71e727dca00b">

**Comment by droidmonkey** [comment]
Please submit a bug to apple

**Comment by vraravam** [comment]
@droidmonkey  - just so as to clear up my understanding, the screenshot from my previous comment is the only permission that KeepassXC needs?

**Comment by droidmonkey** [comment]
We need screen recorder and accessibility. This could be one of three things:

1. The test within keepassxc for whether the permission is granted is no longer valid under Sequoia. This would mean the message dialog is a false positive (maybe).

2. Sequoia no longer allows certain apps to obtain these permissions. 

3. There is an actual bug in Sequoia preventing use of these valid permissions.

**Comment by vraravam** [comment]
thanks for the explanation @droidmonkey 
My suspicion is either of the first 2 points.
I am able to do screen sharing in Arc for teams meetings, etc. (and based on my earlier understanding, "screensharing" required the same permissions under "screen recording"). As seen in the 2nd screenshot, this functionality works for/in Arc. But, keepassxc seems to throw up that dialog.
I have anyways raised a bug with apple via the feedback assistant. Hoping to get this solved since usability is really messed up right now. (I am able to initiate auto-type from the icon in the keepassxc's ribbon bar, but am unable to trigger it when I'm on the browser in the login screen of any website itself).

**Comment by vraravam** [comment]
Closing since this functionality is now working
