### ISSUE TITLE
after installing keepassxc through snap on Ubuntu 17.10, keepassxc is nowhere to be seen

### ISSUE THREAD

**Issue by pierrrrrrre** [keepassxreboot/keepassxc#1107]
## Expected Behavior
When installing keepassxc using the method described on the website (`snap install keepassxc`), I can access keepassxc on my Ubuntu 17.10 desktop.

## Current Behavior
After install, the program cannot be launched and doesn't appear in the graphical dash.

## Steps to reproduce
Install keepassxc using `snap install keepassxc`.

```
% snap list
Name       Version    Rev   Developer       Notes         
core       16-2.28.1  3017  canonical       core          
keepassxc  2.2.2      26    keepassxreboot  -      

% keepassxc
zsh: command not found: keepassxc

% keepassxc.cli
zsh: command not found: keepassxc.cli
```

And I cannot find it in the dash either...

## Debug Info

KeePassXC - 2.2.2
Revision: 26

Operating system: Ubuntu 17.10
CPU architecture: Intel i5-5470
Kernel: 4.13.0-16-generic #19-Ubuntu

**Comment by droidmonkey** [comment]
It is very likely that your path does not contain /snap/bin

**Comment by amast09** [comment]
I just ran into this, if you run the following command it should add it to your launcher,

```
ln -s /var/lib/snapd/desktop/applications/keepassxc_keepassxc.desktop .local/share/applications/keepassxc.desktop
```

thanks!

**Comment by droidmonkey** [comment]
@amast09 i am not sure how linking to the desktop file fixes command not found. Either way, performing that linking should be completely unnecessary if snapd properly setup the paths for desktop files to include installed snaps.

**Comment by amast09** [comment]
I agree, for the time being it added the launcher item for me to use

**Comment by amast09** [comment]
Actually, after doing a restart of my machine the snap desktop shortcut was created correctly so I removed the redundant symlink desktop shortcut I created
