### ISSUE TITLE
Problems getting x64 installers working

### ISSUE THREAD

**Issue by ghost** [keepassxreboot/keepassxc#11073]
I have a unpleasant suprise with the latest versions of keepassxc on this tiny laptop
It has win11 x64 installed but whatever i do keepassxc does not work.
Previously i found somewhere version 2.7.5 (x86) which got me back into my passwords
But when i searched it yesterday google did not come up again with the x86 version only the freaking x86/x64 which does not work
It installs the x64 what does not work
I tried starting it at least a million times and actually reinstalled the whole W11 home from scratch ...  result still nada 
I had i to find today a x86 version which i finally found a 2.4.3 version as the 2.7.5 version disappeared to get it installed
The x86/x64 version installs but whatever i do the program fails to start 
( there is as far as i know no option to force it to install x86 when it find a x64 os) 

Now how or why a 3 day old new laptop with a i3 cpu refuses to start keepassxc it simply does nothing when i click to open it
Now I have access again to my login data but this was for me a shocking nasty experience as i rely heavily on this program for my passwords, gotta mention the ages old interface which makes finding stuff a pain (2.4.3)
As soon as my broken big pc comes back i instant am back in the latest version but for now i am BAFFLED that it fails
No error messages / no logs nothing it simply refuses to start

**Comment by droidmonkey** [comment]
https://github.com/keepassxreboot/keepassxc/issues/10925
