### ISSUE TITLE
macOS ui is broken

### ISSUE THREAD

**Issue by b1nhack** [keepassxreboot/keepassxc#11077]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

![](https://github.com/user-attachments/assets/daa0b78d-83f6-4b12-b31e-ffa2bb040062)

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )

Database Security Settings -> Encryption Settings

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

There is a vertical bar, and part of the functional interface is completely smudged.

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.9
Revision: 8f6dd13

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS

**Comment by droidmonkey** [comment]
Unfortunately this is a qt error that we cannot solve. It is sporadic in appearance and something internal to qt code. We are hoping upgrading to qt6 in the future resolves this problem.
