### ISSUE TITLE
Writing the database failed: Unknown error - version 2.7.9 Flatpak

### ISSUE THREAD

**Issue by kasunch** [keepassxreboot/keepassxc#11075]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

Today, I came across this weird problem when I am try saving the database.
I get the error "Writing the database failed: Unknown error".
No file is saved.

## Steps to Reproduce
1. Start the application as usual
2. Open a database file
3. Try to save the database into a different location

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
There should be no errors when saving the database file.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Initially, I thought that the file hosting client I use (MEGA) causes this problem.
However, I get the same error when I try to save the database into a difference location.

Moreover, there is another error at the application startup "Access error for config file \<Flatpak config file folder\>/keepassxc.ini".

I see no such errors with the same release version distributed with appimage.

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.9
Revision: 8f6dd13
Distribution: Flatpak

Qt 5.15.10
Debugging mode is disabled.

Operating system: KDE Flatpak runtime
CPU architecture: x86_64
Kernel: linux 6.8.0-38-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- Passkeys
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 3.3.0

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: Gnome
Windowing System: Wayland

**Comment by droidmonkey** [comment]
You likely restricted permissions some how to your flatpak install. Remove the flatpak entirely and try to install it again. This is a permissions issue on your end unfortunately.

**Comment by kasunch** [comment]
I wiped the entire Flatpak installation and reinstalled. This seems to fix the problem. Not sure why this happened in the first place. Thanks for the help.
