### ISSUE TITLE
no automatic fill in since 2.7.9

### ISSUE THREAD

**Issue by brainbarry** [keepassxreboot/keepassxc#11071]
## Overview

after the update to 2.7.9 the automatic fill in is not working at all.

it says always: Error Fehler. Keine Anmeldungen gefunden. https.....

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

with 2.78 all was ok.

[NOTE]: # ( Paste debug info from Help → About here )

KeePassXC - Version 2.7.9
Revision: 8f6dd13

Qt 5.15.11
Diagnosemodus ist deaktiviert.

Betriebssystem: Windows 10 Version 2009
CPU-Architektur: x86_64
Kernel: winnt 10.0.19045

Aktivierte Erweiterungen:
- Auto-Type
- Browser-Integration
- Passkeys
- SSH-Agent
- KeeShare
- YubiKey
- Schnelle Entsperrung

Kryptographische Bibliotheken:
- Botan 3.1.1

**Comment by brainbarry** [comment]
I use Firefox 128 with extension 1.9.1.1

**Comment by droidmonkey** [comment]
That error means the website you are on doesn't match any entries you have. Adjust your url for the desired entry that corresponds with the url in the error message.

**Comment by brainbarry** [comment]
of course its design url in keepassxc.
for example: keepassxc says there is no match in "https://signin.ebay.de"
but exact these line is in the url field of keepassxc: "https://signin.ebay.de"
And these happens with all urls. They are all exactly written as needed.
It worked with 2.78 with design database and urls.

**Comment by droidmonkey** [comment]
Nothing changed with browser integration between 2.7.8 and 2.7.9. Make sure you didn't disable browser integration in your group settings. Also make sure if you have more than one database open that you have the desired one to pull from in focus.

**Comment by brainbarry** [comment]
![integration](https://github.com/user-attachments/assets/577adcb6-5af8-4cde-a136-c532cd389a12)

I have only one database.

**Comment by brainbarry** [comment]
now its solved, there was a mistake in the connection in firefox extension.
I deleted the connection and made it new. 
Now its working.
