### ISSUE TITLE
Database appears blank but autofill/search works as expected

### ISSUE THREAD

**Issue by Mnky313** [keepassxreboot/keepassxc#11083]
## Steps to Reproduce
There's not really a set of steps to reproduce, it seems to happen randomly when unlocking the database. Once it happens it stays until I clear app data/re-install.

(Using the flatpak version)

## Expected Behavior
Database showed all entries sorted into folders

## Actual Behavior
Database appears blank but data is still there as autofill/search works.
![image](https://github.com/user-attachments/assets/2ee6cc37-b9da-4618-bff0-43dc0b12a61a)

Searching for records works as expected:
![image](https://github.com/user-attachments/assets/efedbbce-8c1c-4136-8f9b-66b78d8ebd4e)

## Context
Noticed this happening on both of my machines but sometimes it works fine for weeks and other times it happens quickly after a reinstall. I have it set to run on startup as well as always minimize (when closing, when unlocking).

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.9
Revision: 8f6dd13
Distribution: Flatpak

Qt 5.15.10
Debugging mode is disabled.

Operating system: KDE Flatpak runtime
CPU architecture: x86_64
Kernel: linux 6.9.9-arch1-1

Enabled extensions:
- Auto-Type
- Browser Integration
- Passkeys
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 3.3.0

[NOTE]: # ( Pick choices based on your environment )
Operating System: Arch Linux (6.9.9-arch1-1)
Desktop Env: Hyprland
Windowing System: Wayland

**Comment by varjolintu** [comment]
The tree section on the left seems to be hidden.

**Comment by Mnky313** [comment]
> The tree section on the left seems to be hidden.

Am I missing some way of showing it? Right clicking the titlebars and showing all the categories doesn't change it, same with resetting it to defaults.

**Comment by varjolintu** [comment]
https://github.com/keepassxreboot/keepassxc/issues/10927#issuecomment-2180333104
