### ISSUE TITLE
Hide Menubar changes hotkey behavior like copy, new entry and alike

### ISSUE THREAD

**Issue by Carlisle96** [keepassxreboot/keepassxc#11089]
## Overview
Hiding the Menubar changes the behavior of hotkeys unexpectedly.

## Steps to Reproduce
1. View -> Uncheck "Show Menubar"
2. Press Ctrl+N or Ctrl+C to copy a password ( or any other hotkey specified in the Menubar )

## Expected Behavior
When I press Ctrl+N i expect to add a new entry
When I press Ctrl+C i expect to copy the password of the entry

## Actual Behavior
Pressing Ctrl+N -> Nothing happens
Pressing Ctrl+C copies the field i currently hover over

## Context
Everything works fine with Menubar is shown. 
Broken Behavior occours when Menubar is hidden.

## System Information
KeePassXC - Version 2.7.9
Revision: 8f6dd13

Qt 5.15.14
Debugging mode is disabled.

Operating system: Fedora Linux 40 (Forty)
CPU architecture: x86_64
Kernel: linux 6.9.9-200.fc40.x86_64

Enabled extensions:
- Auto-Type
- Browser Integration
- Passkeys
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.19.4

Desktop Env: XMonad
Windowing System: X11

**Comment by droidmonkey** [comment]
Do you have the toolbar hidden as well?

**Comment by Carlisle96** [comment]
> Do you have the toolbar hidden as well?

Yes, however showing only the menubar and keeping the toolbar hidden is a workaround.

**Comment by droidmonkey** [comment]
This is kind of "by design" from a Qt perspective because when controls with shortcuts on them are hidden they cannot be activated. There really isn't much we can do about this without completely circumventing all the capabilities that our UI framework provides. As such, this won't be worked on.
