### ISSUE TITLE
Allow more than 30 days limit for showing expired entries on unlock

### ISSUE THREAD

**Issue by graham-walker** [keepassxreboot/keepassxc#11084]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
In KeePassXC 2.7.9 it is possible to enable the option "On database unlock, show entries that will expire within X days". However, the option does not allow you to specify a number greater than 30 days.

It is currently possible to search the database for entries expiring in greater than 30 days (for example `is:expired-60`), however it is not currently possible to do so on database unlock through this option.

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )
(not possible in 2.7.9)
![example](https://github.com/user-attachments/assets/93fc6f37-a789-45ef-abbb-78d5c1a10fbf)

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
I have databases I infrequently access. It would be helpful to be able to set a greater number of days so I do not miss when passwords in those databases will be expiring. Preferably the option would be uncapped or allow a sufficiently high number (365) of days.

**Comment by droidmonkey** [comment]
Just save a search with your desired number and use it when you need it. Even 30 days is excessively long for this feature. The point is to not annoy you (too much).

**Comment by graham-walker** [comment]
While saving the search is useful, it does not accomplish what I am looking to do, which is viewing expiring entries more than 30 days in the future **on database unlock**. I checked the KeePassXC user guide and I'm not aware of a way to run a saved search on database unlock. Perhaps this issue can be repurposed into "Run user saved search on database unlock"?

**Comment by droidmonkey** [comment]
I acknowledge your request but am not going to incorporate that into the code. Thank you for the suggestion.

**Comment by graham-walker** [comment]
I want to try reexplaining my use case in hopes it will better clarify why I believe this feature is needed.

From the user guide on expired entries, I believe the definition of expired entries you are using refers to entries whose passwords will expire but the account remains intact, which explains why a 30 days cap is more than sufficient.

However, I am using expired entries to mark when accounts will be deleted due to inactivity, which would render them permanently inaccessible. Because I am not accessing these accounts frequently the option to set greater than 30 days would be very useful in warning me when I am at risk of losing access to an account.

Having these expiring entries available in one place in KeePassXC would be far more convenient than receiving a dismissable email alert for every expiring account.

Having these expiring entries automatically available at unlock would be helpful to prevent not checking due to negligence.

Since the default for the option is 3 days (and that would not change) I do not see any downside to allowing the user to set the option to a number greater than 30 days if they have a use case like this one.

**Comment by droidmonkey** [comment]
You can achieve this today by manually editing the `keepassxc.ini` file located in ~/.config/keepassxc, %APPDATA%/keepassxc, or ~/Library/Application Support/KeePassXC depending on your operating system.

Adjust the line: `ShowExpiredEntriesOnDatabaseUnlockOffsetDays=90`
Then restart KeePassXC

Note this will reset to 30 days if you press OK on the application settings.
