### ISSUE TITLE
Password is unexpectedly removed when editing database credentials

### ISSUE THREAD

**Issue by blinskey** [keepassxreboot/keepassxc#11096]
## Overview

The Database Credentials interface behaves in an unexpected manner for databases protected by a password. The interface indicates that the existing password will persist, but the password is cleared when the OK button is clicked.

## Steps to Reproduce

1. Create a new database, protected by a password.
2. Open the database.
3. In the menu bar, click on Database > Database Security to open the database credentials menu.
4. Observe that the Password section shows options to change or remove the password:

<img width="912" alt="Screenshot 2024-07-22 at 14 23 40" src="https://github.com/user-attachments/assets/2f664d76-ff20-4cf1-b400-b324f68d74bc">

5. Click on the OK button.
6. Observe that a dialog appears warning that you have not set a password:

<img width="532" alt="Screenshot 2024-07-22 at 14 23 48" src="https://github.com/user-attachments/assets/7fe088a2-e6c8-4cca-bb8e-4b7b2c2643bc">

## Expected Behavior

I expected the password to persist unchanged when viewing the Database Credentials UI and clicking OK without making any changes.

## Actual Behavior

If the user clicks "Continue without password" in the warning dialog, the password is removed from the database if another form of protection is set, or an error dialog is displayed if no other encryption keys are configured.

## Context

I encountered this bug while attempting to add a key file to a database already protected by a password. I had to click on Change Password and re-enter the password in order to preserve it alongside the newly added key.

Note that this behavior does not occur for key files. If a database is protected by only a key file, the Database Credentials UI will display Change and Remove buttons for the key file. If you click OK without making any changes, the existing key persists. I expected the same behavior for passwords.

KeePassXC - Version 2.7.9
Revision: 8f6dd13

Qt 5.15.11
Debugging mode is disabled.

Operating system: macOS 14.5
CPU architecture: arm64
Kernel: darwin 23.5.0

Enabled extensions:
- Auto-Type
- Browser Integration
- Passkeys
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 3.1.1

**Comment by droidmonkey** [comment]
Duplicate report

**Comment by blinskey** [comment]
Could you by any chance point me to the existing issue for this bug? I searched before filling this bug and was unable to find it.

**Comment by blinskey** [comment]
Never mind, it’s #10996. I didn’t think to search the closed issues.
