### ISSUE TITLE
macOS Sequoia 15 Beta 3 - Displaylink issue

### ISSUE THREAD

**Issue by burnziii** [keepassxreboot/keepassxc#11094]
## Overview
[NOTE]: # KeepassXC not shown with Displaylink on macOS Sequoia 15 Beta 3

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Open KeepassXC
2. KeepassXC only shows content after enabling screen sharing 

## Expected Behavior
[NOTE]: # KeepassXC shows content like normal.

## Actual Behavior
[NOTE]: # KeepassXC shows no content until screen sharing is allowed within menu.

## Context
[NOTE]: # macOS Sequoia 15 Beta 3 with DisplayLink adapter, not sure if it works fine without DisplayLink, maybe it is a general issue with the window system within macOS Sequoia 15 Beta 3.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.9
Revision: 8f6dd13

Qt 5.15.11
Diagnosemodus ist deaktiviert.

Betriebssystem: macOS 15.0
CPU-Architektur: arm64
Kernel: darwin 24.0.0

Aktivierte Erweiterungen:
- Auto-Type
- Browser-Integration
- Passkeys
- SSH-Agent
- KeeShare
- YubiKey
- Schnelle Entsperrung

Kryptographische Bibliotheken:
- Botan 3.1.1

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS

**Comment by burnziii** [comment]
Maybe it is related to https://github.com/keepassxreboot/keepassxc/issues/10757

**Comment by droidmonkey** [comment]
File a bug with macos, this isn't our issue
