### ISSUE TITLE
Losing entries in import keeshare file trough /run/user/523314/gvfs

### ISSUE THREAD

**Issue by Ogaba** [keepassxreboot/keepassxc#11098]
We have keeshare files used by more than 10 people in our team.

When someone import one of theses keeshare using inapproriate gvfsd-fuse path, it introduces problem after, specially losing entries.

My guess is that it is related to .xdp files created in the path, were the keeshares are located.
No clues found on Internet, so I open this issue for the keepassxc dev team.

When accessing files by a cifs mount like "Dossier_Partage/IP_centre", everything works as a charm, but not when using gvfsd-fuse paths, see it in action :

I'm using a ubuntu desktop 20.04 LTS distribution, here are my mount points :

```
me@my_server:~$ cat /etc/mtab
//IP_centre/echanges /home/me/Dossier_Partage/IP_centre_echanges cifs rw,relatime,vers=1.0,cache=strict,username=me,domain=my_domain,uid=0,noforceuid,gid=3100035,forcegid,addr=IP_centre,file_mode=0770,dir_mode=0770,soft,nounix,serverino,mapposix,nobrl,rsize=61440,wsize=65536,bsize=1048576,echo_interval=60,actimeo=1 0 0
tmpfs /run/user/523314 tmpfs rw,nosuid,nodev,relatime,size=704080k,mode=700,uid=523314,gid=3100035,inode64 0 0
gvfsd-fuse /run/user/523314/gvfs fuse.gvfsd-fuse rw,nosuid,nodev,relatime,user_id=523314,group_id=3100035 0 0

me@my_server:~$ ll Dossier_Partage/IP_centre/Keypass/
total 3737
drwxrwx--- 2 root domain users     0 Jul 22 17:34 ./
drwxrwx--- 2 root domain users     0 Jul 23 09:05 ../
-rwxrwx--- 1 root domain users  9724 Jul 18 15:58 .xdp_essai.kdbx.share.004AR2*

me@my_server:~/Documents$ cp -p ~/Dossier_Partage/IP_centre/Keypass/.xdp_essai.kdbx.share.004AR2 .

me@my_server:~/Documents$ file .xdp_essai.kdbx.share.004AR2
.xdp_essai.kdbx.share.004AR2: Zip archive data, at least v4.5 to extract

me@my_server:~/Documents$ unzip .xdp_essai.kdbx.share.004AR2
Archive:  .xdp_essai.kdbx.share.004AR2
  inflating: container.share.signature  
  inflating: container.share.kdbx    

  
me@my_server:~/Documents$ cat container.share.signature
<?xml version="1.0"?><KeeShare><Signature>rsa|<RSA CODE></Signature><Certificate><Signer><MY AD LOGIN></Signer><Key><MY KEY></Key></Certificate></KeeShare>
```

-> this shows me, I'm the guy how create (import) this keeshare, and later it's now delete entries for me and other people of my team, why ?

**Comment by Ogaba** [comment]
``<?xml version="1.0"?><KeeShare><Signature>rsa|<RSA CODE></Signature><Certificate><Signer><MY AD LOGIN></Signer><Key><MY KEY></Key></Certificate></KeeShare>``

**Comment by droidmonkey** [comment]
Unfortunately I have no idea what you are trying to say here

**Comment by Ogaba** [comment]
Ok I've modified my issue to clarify the context, please ask me questions if necessary, thanks

**Comment by droidmonkey** [comment]
gvfsd-fuse is a really poor interface. Just use CIFS like you said. There is nothing we can do about this. I recommend filing a bug report with gvfsd-fuse project as they need to figure out how to provide a more resilient interface.

Alternatively, you can enable "Direct Write Saves" from the application settings which work with gvfsd-fuse.

![image](https://github.com/user-attachments/assets/a0e4e355-3d34-43c9-a864-4b22f8e96bfe)

**Comment by Ogaba** [comment]
Thanks for your help, appreciated. As the option is marked as "dangerous", we don't enable it, stay with CIFS :-)
