### ISSUE TITLE
Rework entry attributes user interface

### ISSUE THREAD

**Issue by phoerious** [keepassxreboot/keepassxc#111]
The user interface for editing attributes is quite badly designed. There is hardly enough space for attribute names longer than 7 characters and the attribute name list can't be resized. See screenshot:

![keepassxc-attributes](https://cloud.githubusercontent.com/assets/911270/20573147/c26b4422-b1ae-11e6-9a15-d74d55dfc285.png)

## Expected Behavior
There should be more space by default (who needs so much space for the value text field anyway?) and the attribute name panel on the left should be horizontally resizable.

This issue may also apply generally to the vertical tab bars at the very left and in the settings. Those are not editable, but the issue might (possibly?) occur when texts become longer due to different locales. I haven't tested that, though. The width seems to scale with different font sizes, at least.

**Comment by TheZ3ro** [comment]
This is also linked/related to https://github.com/keepassxreboot/keepassxc/issues/45 (Display some Additional Attribute as Password)

**Comment by droidmonkey** [comment]
Specifically my proposed implementation of the protected attribute display: https://github.com/keepassxreboot/keepassxc/issues/45#issuecomment-255478598
