### ISSUE TITLE
Bug: Shortcut to copy TOTP stops working when hiding menu bar

### ISSUE THREAD

**Issue by tinyoverflow** [keepassxreboot/keepassxc#11104]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
When using the shortcuts to copy data from an entry, such as `CTRL+C`, `CTRL+B` and `CTRL+T`, at least the `CTRL+T` one stops working when hiding the menu bar via it's toggle option inside the View menu.

## Steps to Reproduce
1. Create an entry with TOTP configured.
2. Go to "View" and disable "Show menu bar".
3. Select the previously created entry and press "CTRL+T".
4. It doesn't work.

Funny thing is:
5. Press `Alt`, then `Escape` to show the menu bar.
6. Menu bar is visible.
7. Select the previously created entry and press "CTRL+T".
8. TOTP code will be copied.

## Expected Behavior
I expect the TOTP to be copied with it's shortcut whether or not I have the menu bar enabled.

## Actual Behavior
The TOTP code cannot be copied with it's shortcut when the menu bar is disab

## Context
KeePassXC: 2.7.9
Revision: 8f6dd13
Distribution: Flatpak

Operating System: Linux Mint
Desktop Env: Cinnamon
Windowing System: X11

**Comment by droidmonkey** [comment]
See #11089
