### ISSUE TITLE
Linux & Wayland & Flatpak - cursor gets changed back to default when hovering over keepassxc

### ISSUE THREAD

**Issue by JacekP1** [keepassxreboot/keepassxc#11108]
## Overview
I changed my cursor theme in KDE. I installed Keepass from flathub. 
When I hover my mouse over keepass the cursor gets changed back into the deafult.

I'm attaching a screen recording that shows the issue.
[Screencast_20240726_191836.webm](https://github.com/user-attachments/assets/60b9fe6d-ce60-46e7-8a5b-194b03d7f7c4)

Notably this does not happen on X11.

## Steps to Reproduce
1. Install keepass froom flathub
2. Run wayland
3. Change your cursor theme
4. Open keepass and hover your mouse over it

## Expected Behavior
Cursor should not change

## Actual Behavior
Cursor changes back to default.

## Context
This issue is not exclusive to KeepassXC, seems to also affect some other flatpaks.
Under wayland does keepass run with xWayland? Although this does not happen on x11.

Additional info on reddit, including a user-side fix:
https://www.reddit.com/r/flatpak/comments/rxnyh7/flatpak_app_changing_cursor_theme_and_size_is/

## About keepassXC
KeePassXC - Version 2.7.9
Revision: 8f6dd13
Distribution: Flatpak

Qt 5.15.10
Debugging mode is disabled.

Operating system: KDE Flatpak runtime
CPU architecture: x86_64
Kernel: linux 6.9.9-200.fc40.x86_64

Enabled extensions:
- Auto-Type
- Browser Integration
- Passkeys
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 3.3.0

## About system
Operating System: Linux
Desktop Env: KDE
Windowing System: Wayland

**Comment by droidmonkey** [comment]
Send a bug report in to KDE this isn't a keepassxc bug
