### ISSUE TITLE
Database Health Check Improvement: URL Status

### ISSUE THREAD

**Issue by danielcberman** [keepassxreboot/keepassxc#11103]
## Summary
It would be awesome to have a means to verify if the URL saved in a password entry had anything **other** than a 200 Status OK. This might be another column under Database Reports > Health Check or perhaps somewhere else.

## Examples
Something similar to the password strength column under Database Reports > Health Check. Yellow would stand for has returned Status 404 or 403's in the past but is currently live. Red could stand for returning a status of 404. The reason field could also include the actual status returned from the website.

## Context
This would enable users to see if a particular website had gone offline, and seek out alternatives, and/or simply remove invalid credentials and thus keep their databases cleaner.

**Comment by droidmonkey** [comment]
I'm not seeing the utility of this. If you don't know the website is offline, then that means you aren't using it regularly. If it is offline, then there's not much to do about it. Also often times defunct websites have their urls scooped up by squatters who host a default page anyway. 

For all these reasons, we won't be implementing this.
