### ISSUE TITLE
Snap 2.7.8 latest/edge fails to update since 2024-07-25

### ISSUE THREAD

**Issue by lnksz** [keepassxreboot/keepassxc#11107]
## Overview

Since yesterday's push to snap's latest/edge, the snap fails to update with error message:

```
# snap refresh
error: cannot perform the following tasks:
- Mount snap "keepassxc" (1831) (installation not allowed by "browser-native-messaging" plug rule of interface "personal-files")
```

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. you have installed kepassxc from snap latest/edge on Ubuntu 22.04
2. try snap refresh after 2024-07-26

## Expected Behavior

keepassxc snap updates without errors

## Actual Behavior

update fails with 
```
# snap refresh
error: cannot perform the following tasks:
- Mount snap "keepassxc" (1831) (installation not allowed by "browser-native-messaging" plug rule of interface "personal-files")
```

## Context

Noticed during routine morning updates.
Strange that snap shows version `2.7.8` but the app itself shows `2.8.0`.

snap changes show errors since 25.07
```
snap changes
ID   Status  Spawn                    Ready                    Summary
542  Done    yesterday at 16:00 CEST  yesterday at 16:00 CEST  Pre-download "keepassxc" for auto-refresh
543  Done    yesterday at 16:00 CEST  yesterday at 16:01 CEST  Auto-refresh snap "kf6-core22"
544  Error   yesterday at 16:42 CEST  yesterday at 16:42 CEST  Auto-refresh snap "keepassxc"
545  Error   today at 09:47 CEST      today at 09:47 CEST      Refresh "keepassxc" snap
```

KeePassXC - Version 2.8.0
Revision: a6ea307
Distribution: Snap

Qt 5.15.11
Debugging mode is disabled.

Operating system: Ubuntu Core 22
CPU architecture: x86_64
Kernel: linux 6.5.0-45-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- Passkeys
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.19.1

Operating System: Linux, Ubuntu 22.04
Desktop Env: Gnome
Windowing System: X11

**Comment by lnksz** [comment]
Have seen in the snap description:
```
description: |
  NOTE: KeePassXC no longer supports this distribution method. Snaps have a lot of bugs across
  distros and are difficult for us to maintain a satisfactory experience. We recommend switching to
  the flatpak distribution instead. https://flathub.org/apps/details/org.keepassxc.KeePassXC

  KeePassXC is an application for people with extremely high demands on secure
  personal data management. It has a light interface, is cross-platform and
  published under the terms of the GNU General Public License.

  For known issues with the Snap install:
  https://github.com/keepassxreboot/keepassxc/issues?q=is%3Aissue+is%3Aopen+label%3A%22distribution%
  3A+Snap%22+
```

Will switch to flat

**Comment by droidmonkey** [comment]
@JGCarroll do you have any clues for this? Also looks like Ubuntu approved the personal files request!

**Comment by JGCarroll** [comment]
At a guess, I'm thinking this is a very rare timing mishap between the snap being downloaded in the background but also the assertion (signed key the store generates) being stale, I.E they've successfuly acquired the snap but the assertion doesn't actually state it can use that permission.

So I imagine most people won't hit this, but the catch all fix here would be to go on the store, request a new build, and promote it to latest/edge. This will trigger a new revision, a new revision will have new assertions, and it'll bring everyone to a consistent state if for whatever reason they aren't already.

But basically it comes down to unfortunate timing for the edge channel users where the snap will have been available slightly before the modified assertion to it, I'd not expect a repeat nor for this to effect users in stable.

**Comment by lnksz** [comment]
respect for such a quick response!

**Comment by droidmonkey** [comment]
Closing for now
