### ISSUE TITLE
Multilanguage Installer feedbacks and proposals

### ISSUE THREAD

**Issue by bovirus** [keepassxreboot/keepassxc#1110]
@phoerious 

Hi.

You are using NSIS to create the installer.

I can provide the update of Italian language for NSIS.
I became the translator for update Italian language for NSIS.
 
Please localize the icon description (ex. **_Uninstall KeepassXC_**).
The Italian translation is **_Disinstalla KeepassXC_**.

Please don't use version in the program group name. 
Ex now is KeePassXC v. 2.2.2. Should be always **KeePassXC**.

**Comment by phoerious** [comment]
Our NSIS installer is automatically generated by CPack. With a bit of Googling I found that it may be possible to override the NSIS templates which CPack uses. We should at least enable the language selection dialog somehow. @droidmonkey Care to check?

**Comment by droidmonkey** [comment]
Yah i want to override them anyway because of stupid things like putting the version number in the start menu folder name. There is no other way to change that.
