### ISSUE TITLE
setting ShowTrayIcon to true will cause the interface of keepassxc to be hidden & break.

### ISSUE THREAD

**Issue by beastr45** [keepassxreboot/keepassxc#11109]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. setting show tray icon to true in user config will make the interface of keepassxc bug out and not render. the app becomes unusable as you cannot navigate your password directories.

setting:
[GUI]
ShowTrayIcon=true

Without this option enabled if 
{
[GUI]
MinimizeOnClose=true
MinimizeOnStartup=true
MinimizeToTray=true
}
are set keepassxc will not respect close events and it seems like cinnamon just minimizes it. In my personal window manager the window becomes impossible to close.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
pretty severe bug on my end tbh. The expected behavior would be to actually be able to use the interface if this setting is enabled.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Interface skips rendering, blank white screen with menu buttons on top.

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.9
Revision: 8f6dd13

Qt 5.15.14
Debugging mode is disabled.

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 6.9.10-arch1-1

Enabled extensions:
- Auto-Type
- Browser Integration
- Passkeys
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 3.5.0

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: Cinnamon 
Windowing System: X11

**Comment by beastr45** [comment]
This bug is a regression bug, It seems as if only version of keepassxc 2.7.9  has this issue. The latest package I tested where this bug wasnt present was keepassxc version 2.7.8-2 of the arch build.

**Comment by droidmonkey** [comment]
File a bug with arch, this isn't on us. No changes were made to this functionality between 2.7.8 and 2.7.9

**Comment by beastr45** [comment]
> File a bug with arch, this isn't on us. No changes were made to this functionality between 2.7.8 and 2.7.9

Have you actually tested this on another linux distro besides arch using cinnamon? Because I understand there might be an issue with packaging but its very possible another change can cause something seemingly unrelated to break.

**Comment by beastr45** [comment]
> File a bug with arch, this isn't on us. No changes were made to this functionality between 2.7.8 and 2.7.9

Ok so My suspicions were right and this is still broken even when building from source. I seriously doubt this is an issue with arch. Im sure more testing in a virtual machine with other packages could help. I don't think that a bug in a dependency is likely to blame considering that it is a regression issue. The only dependency upgrade between broken and working versions seems to be botan. which is a crypto library.
There is also a slight error in the bug report due to a slight misunderstanding of the bug. The bug dosen't actually hide the whole interface it just hides the menu where you can navigate groups. The bug automatically focuses the root group and since my root folder was empty it appeared that the whole interface was gone when it was just the navigation menu to the left.
Keep in mind this isnt a nitpick its breaking functionality. Since this is very serious ux bug I would recommend reopening the bug and trying to re-create it in Linux and Windows.

**Comment by droidmonkey** [comment]
Next time post a screenshot. This is a pinned issue: https://github.com/keepassxreboot/keepassxc/issues/10927#issuecomment-2180333104

Also fixed for next release
