### ISSUE TITLE
Cannot override navigator.credentials (Firefox add-on)

### ISSUE THREAD

**Issue by ygoe** [keepassxreboot/keepassxc#11114]
## Overview
The Firefox browser console shows this message on every loading of any page:

> Cannot override navigator.credentials:  TypeError: undefined is not a non-null object

![grafik](https://github.com/user-attachments/assets/bc4ca556-ff30-43e1-a338-924b0d0f9230)

## Steps to Reproduce
1. Install the browser add-on
2. Enable passkey support
3. Open the F12 console on any page

## Expected Behavior
Nothing

## Actual Behavior
The log message

## Context
KeePassXC - Firefox add-on 1.9.1.1
Operating System: Windows

From viewing the linked source code, I guess that a null check is missing there.

![grafik](https://github.com/user-attachments/assets/a8544071-7245-4548-851a-6169ecb6f5ad)

**Comment by droidmonkey** [comment]
Nothing wrong here, it's in a try/catch block, this is expected behavior if navigator.credentials cannot be overridden

**Comment by ygoe** [comment]
Well, that's a log message I don't want to see. It's distracting me from my own log messages. Can it be hidden somewhere else? Maybe push it down to debug level. Or remove it completely because who needs it anyway?

**Comment by droidmonkey** [comment]
@varjolintu can we make this a debug message in the extension?

**Comment by varjolintu** [comment]
> @varjolintu can we make this a debug message in the extension?

Needs some extra work, but it could be possible.

**Comment by ygoe** [comment]
Just replace `console.log` with `console.debug`. Easy.

**Comment by varjolintu** [comment]
> Just replace `console.log` with `console.debug`. Easy.

We meant the _Enable Debug Messaging_ feature in the extension. It only writes logs when the option is enabled.
