### ISSUE TITLE
KeePassXC Feature Request - QR Code Generator

### ISSUE THREAD

**Issue by taylor-p-mason** [keepassxreboot/keepassxc#11116]
![2024-07-29 001931](https://github.com/user-attachments/assets/37a724e6-7b50-4a5d-9532-62cb48a6f373)

When you need to login on another device like a smartphone, attempting to do so with a **strong password** is nearly impossible. 

If KeePassXC includes the ability to generate a (png) QR Code for the Strong Password, then the SmartPhone could scan and apply, without needing to type difficult characters like; fÁ卡ÄkúAïdÓá£Ñ±µ¶õ¦hjoáu$^íoahSÇ戴±ãÙ´RÜUû卡úfv¤óí¬i99戴¬ÜÀÍÛL°2

It's the same issue with "key files", nearly impossible to type on any keyboard, and even if you did, it's takes so long with a big file of several thousand characters.  The QR Code conveniently help resolve these issues.

**Comment by droidmonkey** [comment]
#675
