### ISSUE TITLE
Downloads page - what links work for Linux Mint 17.x and ubuntu 14.04?

### ISSUE THREAD

**Issue by phd21** [keepassxreboot/keepassxc#1111]
Dear KeePassXC developers,

First, thank you for providing this excellent updated application. 

Secondly, I use two Linux Mint systems: 
- I have no problems installing and using this in my Linux Mint KDE 18.x system based on Ubuntu 16.04.

- Problem Issue - my other system is Linux Mint 17.3 based upon Ubuntu 14.04 Trusty. Fortunately I found an AppImage file "KeePassXC-2.2.0-x86_64.AppImage" in my backups which installs and works perfectly. But, I do not see any links on your Downloads page to previous AppImage files for users of Linux Mint 17.3 based upon Ubuntu 14.04 Trusty or easy to install ".deb" files for this. Am I missing something?  This OS version is still supported until 2019. FYI: I cannot get "snap" to install and work properly on this OS version.

KeePassX works well, but KeePassXC is a major improvement IMHO.

Best regards to all of you,
Phil
phd21

**Comment by phoerious** [comment]
I was waiting for this! 😄 
We updated our build system to a newer base (CentOS 7), while our previous builds were created on Ubuntu 14.04. That means it won't run on some old legacy systems. Ubuntu 14.04 is end-of-life and therefore unsupported by Canonical, so I you have three options:

- upgrade your system (sometimes not possible, but highly recommended)
- use an older AppImage, you can find all releases here: https://github.com/keepassxreboot/keepassxc/releases
- compile KeePassXC yourself (not too hard if you follow the steps on our wiki)

**Comment by phd21** [comment]
Hello phoerious and KeePassXC people,

Thank you for your prompt reply and for that Link which does have the AppImage files including the one for Linux Mint 17.x based upon Ubuntu 14.04 Trusty. I hope you keep this archive.

What about providing a PPA? I was reading somewhere that you have one, but when I went to check on that, it seemed empty?

Best regards, 
Phil
phd21

**Comment by phoerious** [comment]
We don't have a PPA, but I found this one today: https://launchpad.net/~dupondje/+archive/ubuntu/keepassxc. It does not provide packages for Trusty, though.

We will keep old versions on the releases page, but unless many more people report issues, new releases AppImage won't support Trusty. The last AppImage built on that platform was 2.2.1.

**Comment by phoerious** [comment]
I uploaded a new 2.2.2 build which runs on Trusty. You can download it from our downloads page on the website or our GitHub releases page: https://github.com/keepassxreboot/keepassxc/releases/tag/2.2.2

**Comment by phd21** [comment]
Hi phoerious,

Thank you very much for providing a current version of KeePassXC for Linux Mint 17.x based on Ubuntu 14.04 Trusty. I downloaded the AppImage from your link and it works, yeah. Out of curiosity, are there Linux ".deb" files too?

Best regards,
Phil 
phd21

**Comment by phoerious** [comment]
Only unofficial ones at the moment. They are linked on our downloads page.
