### ISSUE TITLE
Botan, Ubuntu 24.04 LTS, KeepassXC 2.7.9 Illegal Instruction

### ISSUE THREAD

**Issue by m1st0** [keepassxreboot/keepassxc#11119]
## Overview
KeePassXC crashes on illegal instruction with installed dependency libbotan-2.

## Steps to Reproduce
1. Run `sudo apt install keepassxc` to get keepassxc and related dependencies
2. Run `keepassxc` from command line to see errors
4. Run `journalctl -xe` to see if system saw what happened
5. Further investigation by building from source code with libbotan-2-dev, and running keepassxc from git tag 2.7.9 did not help.
6. Using `sudo snap install keepassxc` instead also does not help but is likely a very different issue.

## Expected Behavior
KeepassXC to launch GUI (as it did yesterday)

## Actual Behavior
- Running `keepassxc` from command line shows: `Illegal instruction (core dumped)`
- Command line `journalctl -xe` reports `traps: keepassxc[20537] trap invalid opcode ip:75b1acad50c7 sp:7fff11d81d80 error:0 in libbotan-2.so.19.19.3[2d50c7,75b1ac8b4000+2e0000]`

## Context
- KeePassXC - 2.7.9
- Operating System: Ubuntu 24.04 LTS, custom kernel 6.10.2
- Desktop Env: KDE 5.27.11
- Windowing System: Wayland
- DEB Package: keepassxc/noble 2.7.9-1ppa1~noble1 amd64 [installed]
- DEB Package: libbotan-2-19/noble,noble,now 2.19.3+dfsg-1ubuntu2 amd64 [installed,automatic]
- Kernel: 6.10.2

**Comment by m1st0** [comment]
After restarting in kernel 6.8.0-39, the issue disappears.  The error occurs with kernel 6.10.2.  Unsure if I should close this, but after a future upgrade people may lose KeepassXC.

**Comment by droidmonkey** [comment]
This would have nothing to do with keepassxc, unfortunately. I bug should be opened with ubuntu on this.
