### ISSUE TITLE
Tag grouping/Tag folders , extended tag-system

### ISSUE THREAD

**Issue by ledgeri** [keepassxreboot/keepassxc#11117]
Maybe a #10584 alternative ,or _just a tags-extension_ (Low priority)

## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )

 
New tag-type, or management of tags, what is a dropdown menu or a folder tree.
The user can fill the elements of it or drag the already made tags into tag-folders. All elements are searchable individaully (as current), or the whole group too (parentfolder is a tag also), so the` !taggroup` or `!tag-mother-folder` format is usable as an other search term to filter results (_**has no tag from this group** in one step_).

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )

Entry A (has tag: "password weak")
Entry B (has tag: "Password entropy 280")
Entry C (has no pasword tag attached)
Entry D (has tag: "no need to set")

Tag-folder structure:

 Tag root
 - "**Pw state**" ( folder&tag)
 - - "**Password checked**"  (folder&tag)
 - - - "password weak"-tag
 - - - "Password entropy 280"-tag
 - - - _more tags_
 - - - _more folders_
 - - "no need to set" -tag

`tag:"password weak"`  search's result is Entry A // `!tag:"password weak"` search result's is Entry B,C,D (current)
`tag:"Password checked"` search's result is Entry A and B //` !tag:"Password checked"` search's result is Entry C D
`tag:"Pw state"` search's result is Entry A, B, D // `!tag:"Pw state"` search's result is Entry C (**_C is found in one step/click_**)

Currently, if i would like to find C i would have to list all the "Pw state" included tags (with the `!` modifier), or set them as in my exaple (below) to be able to find C-like entries.

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
My usage example:
I use tags to mark e.g. if an account has a ToS-mentioned "termination due inactivity" period (checking it once was enough, but when those expire, i want reference) . Usually it is 3-6-12-18-24-36 months.
In the current system, i have 6 tags just for _by time_( and there are other things what an expiring entry can indicate). If for some reason i have missed tagging a new entry for expiry, there is no easy way to check if an entry has none of the above mentioned "expiration" tags to find it. If i search for one, or exclude one, all other "tos-inactivity-period-is"-kind of result are show up.  I could list all of the related tags, but that is not so efficient with "many-many, related tags".

Also an issue: now all tags are in alhanumeric order, without an above mentioned strucrure. I had to make all of my tag-names start with a two digit number to be able to find what i want, easily, and have enough category (6 main groups,17 total currently to me), to have every option ( e.g. i wanted to group the "password strenght, and "2fa-level". Those would be far away in the base list, but this way i can set 01-password-strength (and variations of it) and 02-2fa-level  (and variations of it) and they follow each other in every listing) Visualy, logically easier to oversee.
With the above mentioned system the management would be easier!

**Comment by droidmonkey** [comment]
Thank you for the suggestion, but tags have no structure and will not have structure. If you want structure, that is what groups are for.

**Comment by ledgeri** [comment]
Ok.
