### ISSUE TITLE
KeepassXC Portable should not require additional components to run (MSVC redist on Windows)

### ISSUE THREAD

**Issue by TheRegistrar** [keepassxreboot/keepassxc#11112]
## Overview
The purpose of a portable app is to be carried around and used on whichever computer is available. As such, it cannot rely on optional components and should be available on a PC where only the OS and maybe device drivers are installed.
Furthermore, a portable app can be run without admin privileges, but if prerequisites must be installed this becomes impossible.
Finally, a password manager should rely on as little external code as possible, in order to maximize availability and avoid lockout.

## Steps to Reproduce
1. Install Windows 10 or 11
2. Download the portable version of KeepassXC
3. Try to run it and get a missing DLL error

## Expected Behavior
The portable app should run when launched on a supported OS

## Actual Behavior
The app complains about missing components

## Context
KeePassXC - VERSION 2.7.0+ Portable
Revision: idk

Operating System: Windows

**Comment by droidmonkey** [comment]
Use the legacy windows version: 

https://github.com/keepassxreboot/keepassxc/releases/download/2.7.9/KeePassXC-2.7.9-Win64-LegacyWindows.zip
