### ISSUE TITLE
Autotype in wayland and enable remote interaction

### ISSUE THREAD

**Issue by Grejdy** [keepassxreboot/keepassxc#11118]
Autotype on Linux requires the (deprecated) X11 environment and keepass does not offer it in the now common wayland. Moreover, now the system requires to enable remote interaction to execute autotype and the whole process looks like "autotype -> enable remote interaction -> confirm -> delete what autotype managed to write before the system stopped it -> autotype again" and it's slowly getting easier not to use autotype. Couldn't something be done about this (both)?

**Comment by droidmonkey** [comment]
#2281
