### ISSUE TITLE
Confirm Auto-type should show Title of previus Window 

### ISSUE THREAD

**Issue by Yankes** [keepassxreboot/keepassxc#11127]
It very easy to get distracted and mistaken what was previous active window.

With windows Title show in confirm dialog we could easy avoid some confusions that could
happens some times if person did couple things at once.
like for example login at same time to ssh and making conversation in some chat in web browser.
It would be very bad if because some distraction I would send ssh credential to some public chat.

Under Windows system it could probably even grab current web browser tab title as task bar show it too.

Alterative could Auto-type have restrictions on windows that could accept inputs? like
"ssh can be typed to terminal and not web browser".

**Comment by droidmonkey** [comment]
This is a duplicate request #10084
