### ISSUE TITLE
KeepassXC - HTTP: does not respect the BestMatchOnly setting

### ISSUE THREAD

**Issue by prometheanfire** [keepassxreboot/keepassxc#1112]
Currently the setting is a noop

https://github.com/keepassxreboot/keepassxc/blob/139658b5c33a39d261a5f3b0ba89c6b93a4a38f9/src/http/HttpSettings.h#L32

## Expected Behavior
Setting uses a deterministic sort on the returned list by best match, only returning the 'top' best match.

## Current Behavior
Setting is a noop, doing nothing

## Possible Solution
Implement the sort function

## Steps to Reproduce (for bugs)
1. enable BestMatchOnly in the HTTP settings
2. Run a browser plugin (KeePassHttp-Connector on Firefox 57 for me).
3. Try to log into a site with that has multiple entries in KeepassXC (different ports in my case)
4. See that multiple entries are returned

## Context
Finish the http plugin

## Debug Info
Version Built/tested: 4c2bc56d2ea89d4c36b378082de15964a9355741

Operating system: Gentoo
CPU architecture: amd64
Kernel: 4.9.58

Enabled extensions:
- http

**Comment by phoerious** [comment]
I'm not sure if this will be fixed for KeePassHTTP, but we should definitely keep it in mind for its successor implementation.

**Comment by mrrsm** [comment]
I have this same issue.  I have noticed that the correct entry is always the last one in the list returned though.  If @prometheanfire can confirm he sees the same result I can put in PR to fix this.

**Comment by prometheanfire** [comment]
It is at the bottom, but I don't know why.  If it can be explained why the correct option is always last then that'd work, otherwise we don't want this to be wrong or it could start submitting the wrong passwords to sites that should not have them.

**Comment by mrrsm** [comment]
From what I gathered reading through the EntrySearcher code it is how it gets sorted by default. The only part which does leave some room for ambiguity is the optional search that the HTTP request can add however that is currently a TODO item and can just be ran after there is only 1 item in the list if it is returning best match only.

I have been running a build locally over the weekend with this patch and it seems to have worked great for me.  I am going to give it a bit more testing and make a PR with my changes if it works well for the next day or two.

**Comment by mrrsm** [comment]
I found some issues with my implementation. I need to do some more work trying to be smarter on the matching.  I have a use case where there are multiple entries for a domain with the exact same url and don't want it only returning the last one. It should return all that match that url.

**Comment by varjolintu** [comment]
I could give this a spin now when I have some time.
