### ISSUE TITLE
Intellij Keepass Database Passwords view corruption

### ISSUE THREAD

**Issue by FairyTail2000** [keepassxreboot/keepassxc#11121]
## Overview
When saving passwords using the kdbx format with Intellij/Jetbrains IDE's, after setting a Master Password, you can view this database using KeepassXC. However upon viewing these Passwords you can see these Passwords are corrupted, the IDE can still use them and putting the Database into another Program like https://app.keeweb.info/ you can see the passwords like they should

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Create a database connection with a password in Intellij
2. Set the Master Passwords in the settings
3. Use KeepassXC and the Password to open the Database

## Expected Behavior
Clear Text Passwords visible after clicking the view button

## Actual Behavior
Corrupted Passwords like: "��"բ�����", the clear text would be Password123

## Context
If needed I can provide a sample database. I have already contacted Jetbrains Support for this issue, which confirmed this issue and confirmed that other software is still able to open the db with no problems

KeePassXC - Version 2.7.9
Revision: 8f6dd13
Operating System: Windows 11 2009
Desktop Env: /
Windowing System: /

**Comment by FairyTail2000** [comment]
I also have a sample database provided by Jetbrains: https://drive.google.com/file/d/1crM23BuLsAyvzGgQ8jmN40T_UVFG0wh9/view?usp=sharing

The password should be "zzz"

**Comment by droidmonkey** [comment]
This was a bug with intellij plugin

**Comment by FairyTail2000** [comment]
Thank you for your response, if this is a bug with the intellij plugin, why is only KeepassXC affected? @droidmonkey

**Comment by droidmonkey** [comment]
KeeWeb is unmaintained and doesn't adhere to the kdbx specification. Neither does the intellij plugin for kdbx. They do not perform inner stream encryption of passwords which is a requirement per kdbx.

**Comment by droidmonkey** [comment]
Also see https://youtrack.jetbrains.com/issue/IJPL-4174/Connecting-to-existing-KeePass-database-overwrites-all-existing-passwords-with-no-obvious-way-to-recover-them

**Comment by FairyTail2000** [comment]
> KeeWeb is unmaintained and doesn't adhere to the kdbx specification. Neither does the intellij plugin for kdbx. They do not perform inner stream encryption of passwords which is a requirement per kdbx.

That's the reply I was looking for thank you. Regarding the youtrack issue, that's seperate issue unconnected to this. As seen in my reproduction steps, overwriting an excisting database is not necessary. Thank you for your Time, I will try to bring this up with Jetbrains

**Comment by phoerious** [comment]
I left a hint below the issue. Maybe someone will care to fix it.
