### ISSUE TITLE
Move/Copy Toolbar Visibility Setting to Application Settings

### ISSUE THREAD

**Issue by CloverAn** [keepassxreboot/keepassxc#11120]
The menu bar for tools such as Help and Open at the top of the software is hidden. How can I open it?

**Comment by droidmonkey** [comment]
Press Alt

**Comment by CloverAn** [comment]
So concealed

**Comment by droidmonkey** [comment]
You must have hidden the menu bar from the view menu, it's not hidden by default.

**Comment by CloverAn** [comment]
You're right, but I just clicked on it this time, just an attempt. I think there should be a view setting inside the settings @droidmonkey
