### ISSUE TITLE
[MSVC] KeePassXC failed to runtest 'testautotype'

### ISSUE THREAD

**Issue by Zhaojun-Liu** [keepassxreboot/keepassxc#11126]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
Hi: I use msvc to build KeePassXC, and now it failed to run test case 'testautotype', can you please take a look? Thanks.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. git clone https://github.com/keepassxreboot/keepassxc C:\gitP\keepassxreboot\keepassxc 
2. vcpkg.exe install --recurse argon2 botan zlib qt5-base qt5-svg qt5-translations minizip libqrencode readline --triplet x64-windows
3. mkdir C:\gitP\keepassxreboot\keepassxc\build_amd64 & cd C:\gitP\keepassxreboot\keepassxc\build_amd64
4. gem install asciidoctor
5. cmake -G "Visual Studio 17 2022" -A x64 -DCMAKE_SYSTEM_VERSION=10.0.22621.0 -DCMAKE_TOOLCHAIN_FILE=C:\gitP\Microsoft\vcpkg\scripts\buildsystems\vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows ..
6. msbuild /m /p:Platform=x64 /p:Configuration=Release KeePassXC.sln /t:Rebuild 
7. ctest --build-config Release --output-on-failure

Note: the commit of KeePassXC I used is e48ef80
## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
run tests passed.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
The following tests FAILED:
	 16 - testautotype (Failed)
Errors while running CTest

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - e48ef80
Revision: e48ef80

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows Server 2022 Datecenter 21H2

**Comment by droidmonkey** [comment]
Our tests run fine in CI. Run the testautotype program independently to see the test output. Paste that here and will reopen if this is an actual issue on our end.

**Comment by Zhaojun-Liu** [comment]
> Our tests run fine in CI. Run the testautotype program independently to see the test output. Paste that here and will reopen if this is an actual issue on our end.

@droidmonkey the test output for running the testautotype program independently as follows:
![image](https://github.com/user-attachments/assets/2ca5255c-73fd-4e94-9872-53c9816c4625)

**Comment by droidmonkey** [comment]
Looks like the test can't find or load the auto-type library. Make sure you have built the `keepassxc-autotype-test` cmake target.

**Comment by Zhaojun-Liu** [comment]
> Looks like the test can't find or load the auto-type library. Make sure you have built the `keepassxc-autotype-test` cmake target.

How should I check if I have built the `keepassxc-autotype-test` cmake target?  Could you give me some tips? Thanks so much. Did I install too few qt packages? My installation command is : vcpkg.exe install --recurse argon2 botan zlib **qt5-base qt5-svg qt5-translations** minizip libqrencode readline --triplet x64-windows

**Comment by droidmonkey** [comment]
It should be built automatically, it's impossible to tell why this is happening in your case unfortunately. Although we do not build using msbuild, instead we use ninja. So change your cmake command to be `cmake -G Ninja ....` and use `
cmake --build . -- -j $Env:NUMBER_OF_PROCESSORS`

**Comment by Zhaojun-Liu** [comment]
> It should be built automatically, it's impossible to tell why this is happening in your case unfortunately. Although we do not build using msbuild, instead we use ninja. So change your cmake command to be `cmake -G Ninja ....` and use ` cmake --build . -- -j $Env:NUMBER_OF_PROCESSORS`

The full build and test process is very time consuming, so I am only getting back to you now. Based on what you said, using Ninja, test case 16 - testautotype does pass. Thank you for the info, I will disable the test temporarily on my side.
