### ISSUE TITLE
Item Expired Problem

### ISSUE THREAD

**Issue by emptylight370** [keepassxreboot/keepassxc#11125]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
Auto input will show expired item when selected "Not show expired item in auto input".
Show all expired item when selected "Show items will expired in 3 days when unlock the database".

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Create a kdbx4 database.
2. Add some items.
3. Select some items to expired now.
4. Use auto input and see expired items.
5. Lock and unlock database to show expired items(not always happen).

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Expired item will not show in auto input panel,
and not show when unlock database when showing items will expired in 3 days.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Expired items appear in auto input panel neither select "not show expired items in auto input" or not.
(Not always) show expired items when unlock database.

## Context
[NOTE]: # ( Give us any additional information you may have. )
The problem in auto input panel is still there, and the problem in unlock database might be fixed.
Some part is translated by translation tool, might have some problems.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 版本 2.7.9
修订版本：8f6dd13

Qt 5.15.11
已禁用调试模式。(disabled debug mode)

操作系统：Windows 11 Version 2009
CPU 架构：x86_64
内核：winnt 10.0.22635

已启用的扩展：
- 自动输入(auto input)
- 浏览器集成(Browser integration)
- 通行密钥(passkey)
- SSH 代理(ssh agent)
- KeeShare
- YubiKey
- 快速解锁(quick unlock)

密码学公共库：
- Botan 3.1.1

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows

**Comment by droidmonkey** [comment]
Hide expired only applies when the auto-type dialog has a valid window title match. Otherwise you are doing a full database search within the dialog.

The "Show expired entries on unlock" only applies to the first unlock of the database when opening the program. Subsequent unlocks will not show the expired entries to avoid annoyance.
