### ISSUE TITLE
Render SVG icons in a container that provides currentColor consistent with selected theme.

### ISSUE THREAD

**Issue by 0x143** [keepassxreboot/keepassxc#11136]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )

It is possible to leverage large collections of icons from sources like [Bootstrap icons](https://github.com/twbs/icons/tree/main/icons).  These usually use `fill="currentColor"` property. For example `alarm.svg` from Bootstrap icons:

```
<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-alarm" viewBox="0 0 16 16">
  <path d="M8.5 5.5a.5.5 0 0 0-1 0v3.362l-1.429 2.38a.5.5 0 1 0 .858.515l1.5-2.5A.5.5 0 0 0 8.5 9z"/>
  <path d="M6.5 0a.5.5 0 0 0 0 1H7v1.07a7.001 7.001 0 0 0-3.273 12.474l-.602.602a.5.5 0 0 0 .707.708l.746-.746A6.97 6.97 0 0 0 8 16a6.97 6.97 0 0 0 3.422-.892l.746.746a.5.5 0 0 0 .707-.708l-.601-.602A7.001 7.001 0 0 0 9 2.07V1h.5a.5.5 0 0 0 0-1zm1.038 3.018a6 6 0 0 1 .924 0 6 6 0 1 1-.924 0M0 3.5c0 .753.333 1.429.86 1.887A8.04 8.04 0 0 1 4.387 1.86 2.5 2.5 0 0 0 0 3.5M13.5 1c-.753 0-1.429.333-1.887.86a8.04 8.04 0 0 1 3.527 3.527A2.5 2.5 0 0 0 13.5 1"/>
</svg>
```

These look pretty well in light mode:

![light](https://github.com/user-attachments/assets/d3921b33-5dc9-43b9-8778-7b651d2a618d)

But not so much in the dark mode

![dark](https://github.com/user-attachments/assets/558b638f-9e6e-45f7-8b41-8ad1e144e26f)

That's probably because they are not aware of the context and always default to black.  

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )

If it `currentColor` consistent with the color for the accompanying text was available for the icon,  it would enable import of large sets of high quality icons, without need of duplicating them with fixed color for selected themes.

**Comment by droidmonkey** [comment]
Icons are rendered to png immediately on load, we won't tinker with the svg itself. This is a kdbx limitation, we would prefer to keep it as an svg. As such there is no good solution for this problem unfortunately. You'll have to bulk edit the svgs prior to upload to set a specific color.
