### ISSUE TITLE
How can I set up to boot without a password？

### ISSUE THREAD

**Issue by CloverAn** [keepassxreboot/keepassxc#11133]
## Summary
Actually, I'm a personal computer who still has very good security. I want my computer to be able to start without me having to enter a password every time I turn it on and the software starts by default, so that it allows me to quickly get a password through a browser plugin, or add a new password. He should allow me to set it up myself.

## Examples
Allow me to set the duration of the autostart, maybe a week, a month, or a long time. Because I don't want the first thing I need to do every time I turn on the computer is to open the program and enter the password, even though I don't need to use it at the moment. Because he is self-starting, so I enter the password again to make the self-starting meaningless.

## Context
I'm a very lazy person and I'll use a lazier approach to make me more comfortable. If I have high requirements for his security, I will set his security myself, which is more flexible. Of course, the default should be a higher security setting, which I have no problem with.

**Comment by droidmonkey** [comment]
Uhhh ok, there is an issue open to remember quick unlock across reboots / application starts. That's the closet you'll get to this from us.
