### ISSUE TITLE
Mobile browser extension to enable keepasses on mobile

### ISSUE THREAD

**Issue by jangroeschel** [keepassxreboot/keepassxc#11139]
Would be great to have a Firefox mobile browser extension for KeePass XC to enable keepasses to be used on mobile.

I'm running into the issue where signing in with keepasses works great on my laptop but using it with mobile is not possible because the browser extension pulls in the keypass information.

If there's another way to do this please let me know and feel free to ignore this request.

**Comment by droidmonkey** [comment]
Use keepassdx

**Comment by reetp** [comment]
>> Would be great to have a Firefox mobile browser extension for KeePass XC to enable keepasses to be used on mobile.

> Use keepassdx

Tried but just a total pain with remote databases.

Not perfect, but Keepass2Android which makes remote database access much easier as it allows multiple different storage types.

(Zero affiliation)

I'd use DX if it had the same flexibility....
