### ISSUE TITLE
Provide breadcrumbs with internal links

### ISSUE THREAD

**Issue by Matze202** [keepassxreboot/keepassxc#11130]
## Summary
Provide breadcrumbs with links so that you can navigate more easily by search and in longer lists

## Examples
/ ROOT / linked crumb / linked next crumb / etc / target folder, possibly also linked for security

## Context
For really large databases, I unfortunately still miss breadcrumb navigation, which allows me to jump from the search to the corresponding folder of the find or, in very large folders, to jump more quickly to higher-level folders in order to reach other areas of the subfolders more quickly.

**Comment by droidmonkey** [comment]
Just double click the folder name in the search results to go to that folder. This is a duplicate request as well.

**Comment by Matze202** [comment]
> Just double click the folder name in the search results to go to that folder. This is a duplicate request as well.

Thanks for the tip, but my suggestion was more about the breadcrumbs, where you could navigate more quickly to parent folders in long folder lists.

**Comment by droidmonkey** [comment]
Yah that's a duplicate of another request
