### ISSUE TITLE
The database slows down when moving a column

### ISSUE THREAD

**Issue by YanEx13** [keepassxreboot/keepassxc#11131]
## Overview:

Slows down the movement of a column in any database. During this, interaction with the program becomes impossible until the movement is completed. This happens both in KeepassXC Flatpak and in Native (RPM). This problem does not exist on Windows 10 (on the same computer). 
Video: https://github.com/user-attachments/assets/a1a7283f-6b6f-4d2d-afc6-2d84314fcef6

## Debug info:

KeePassXC - Version 2.7.9
Revision: 8f6dd13
Distribution: Flatpak

Qt 5.15.10
Debugging mode is disabled.

Operating system: KDE Flatpak runtime
CPU architecture: x86_64
Kernel: linux 6.9.12-200.fc40.x86_64

Enabled extensions:
- Auto-Type
- Browser Integration
- Passkeys
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 3.3.0

## About the system:

Operating System: Fedora Linux 40
KDE Plasma Version: 6.1.3
KDE Frameworks Version: 6.4.0
Qt Version: 6.7.2
Kernel Version: 6.9.12-200.fc40.x86_64 (64-bit)
Graphics Platform: Wayland
Processors: 12 × 11th Gen Intel® Core™ i5-11400H @ 2.70GHz
Memory: 15.3 ГиБ of RAM
Graphics Processor: Mesa Intel® UHD Graphics
dGPU: Nvidia RTX 3060 Mobile
Manufacturer: HP
Product Name: Victus by HP Laptop

**Comment by droidmonkey** [comment]
Cannot replicate in a 2-cpu 8GB RAM VirtualBox machine:


https://github.com/user-attachments/assets/5e7376d8-4e35-4607-b4a5-bc92f57d1a6f

This update will address some unnecessary overhead in resizing columns anyway: #11014
