### ISSUE TITLE
[Minor Issue] HMAC-SHA1 Challenge-Reponse link has moved

### ISSUE THREAD

**Issue by BeanBagKing** [keepassxreboot/keepassxc#11142]
## Overview
The link under Database -> Database Security -> Security -> Challenge-Reponse with the text "HMAC-SHA1 Challenge-Reponse" has moved or been deleted from yubico.com. It now forwards to the developers landing site.

## Steps to Reproduce

1. Find the link in the location described above
2. Right click the and select "Copy Link Location"
3. Paste the link location into a text editor. The result is: https://www.yubico.com/products/services-software/challenge-response/
4. Visit this link, note that you are immediately redirected to https://developers.yubico.com/

The last observed time this page was active appears to be Jan 2021
http://web.archive.org/web/20210117060007/https://www.yubico.com/products/services-software/challenge-response/
The next index of that page by archive.org, on May 2021, redirects to the developers landing page.

## Expected Behavior
Send the user to a page either explaining the challenge-reponse functionality of Yubikey or a guide on how to set it up. I'm not sure what this would be, but two suggestions may be:

2) https://keepassxc.org/docs/#faq-yubikey-howto - I think this is the better option as it quickly describes to the user what they should do.

1) https://docs.yubico.com/yesdk/users-manual/application-otp/challenge-response.html - This document may be overwhelming to someone new to Yubikey and/or KeepassXC, but has more technical depth.

## Actual Behavior
User is redirected to a landing page that doesn't have anything to do with Challenge-Reponse

## Context
This is a minor issue I realize, but something I did notice and wanted to document for improvement.

## ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.9
Revision: 8f6dd13

Qt 5.15.11
Debugging mode is disabled.

Operating system: Windows 11 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.22631

Enabled extensions:
- Auto-Type
- Browser Integration
- Passkeys
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 3.1.

**Comment by droidmonkey** [comment]
I agree with changing the link to our own controlled pages where we can out link to yubico and other vendors.

**Comment by BeanBagKing** [comment]
I didn't notice this earlier, but the YouTube video linked is 7 years old, and the Yubikey Personalization Tool reviewed there is no longer under development/is replaced by the Yubikey Manager. It still works, but if there's a more up to date video out, that may be better.

**Comment by droidmonkey** [comment]
Yubico does a terrible job with challenge/response instructions.
