### ISSUE TITLE
AppImage 2.2.2 is looking for libsystemd.so

### ISSUE THREAD

**Issue by mockey** [keepassxreboot/keepassxc#1114]
## Expected Behavior
AppImage should start (as the versions before 2.2.2 did)?

## Current Behavior
AppImage aborts with an error message:
`keepassxc: error while loading shared libraries: libsystemd.so.0: cannot open shared object file: No such file or directory`

## Possible Solution
Install libsystemd? Is it really needed? It's not installed by default on Linux Mint 17.3 (Ubuntu 14.04).

## Steps to Reproduce (for bugs)
1. Download AppImage 2.2.2
2. Try to start it

## Context
Cannot start the AppImage 2.2.2 in Linux Mint 17.3

## Debug Info
KeePassXC - 2.2.2
Revision: ?

Libraries:
- LIBS

Operating system: Linux Mint 17.3 (Ubuntu 14.04)
CPU architecture: x86_64
Kernel: 3.19.0-32-generic

Enabled extensions:
- EXTENSIONS

**Comment by affinityv** [comment]
Whatever you do, developers, PLEASE, PLEASE do not rely upon users having systemd.

**Comment by phoerious** [comment]
We explicitly blacklisted libsystemd at some point, because it was producing issues when bundled.
I can try if bundling libsystemd works with our new build system. But then I'm also not sure if it will run on 14.04 anyway, because glibc might be too new.

**Comment by TheZ3ro** [comment]
I'm pretty curious in why AppImage requires libsystemd?

**Comment by phoerious** [comment]
Because one of the bundled libs does, likely one of the larger ones.

**Comment by phoerious** [comment]
I managed to get a working build with Ubuntu 14.04, which also detects YubiKeys, but it required a few more patches which I'll post against 2.2.3.

**Comment by phoerious** [comment]
I uploaded a new 2.2.2-2 build which runs on Trusty. You can download it from our downloads page on the website or our GitHub releases page: https://github.com/keepassxreboot/keepassxc/releases/tag/2.2.2

**Comment by mockey** [comment]
Thanks, it runs without libsystemd now. So 2.2.3 will support YubiKey on Trusty?

**Comment by phoerious** [comment]
2.2.2-2 does support Yubikeys already. It only has a bug that shows it twice, which will be fixed in 2.2.3. Meanwhile, our new PPA also has a working version.

**Comment by mockey** [comment]
Great, will try the PPA with Trusty (I remember the Debian package was Xenial only).
