### ISSUE TITLE
Crashes on wayland when using multiple displays with different scale factors

### ISSUE THREAD

**Issue by CrfzdPQM6** [keepassxreboot/keepassxc#11147]
## Overview
I have two displays with different scale factors, running sway. One app on one display triggers a permission-dialog to access keepassxc SecretService on the other display. When I move arrow focus to the dialog, keepassxc dies.

## Steps to Reproduce
1) Have two displays on wayland with different scale factors
2) Have an app on one display trigger a keepassxc dialog on the other (e.g. access SecretService)
3) Move focus from the other app to the keepassxc dialog

## Expected Behavior
Focus moves

## Actual Behavior
Keepassxc dies with message:
```
-> keepassxc
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
wl_surface#112: error 2: Buffer size (622x1127) is not divisible by scale (2)
```

## Context
This problem goes away if the scale factor or all the displays is 1.0

There is lots of discussion of this scale factor issue for other applications e.g.
https://bugzilla.mozilla.org/show_bug.cgi?id=1795851
https://github.com/hyprwm/Hyprland/issues/509
https://github.com/wez/wezterm/issues/2445

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.9

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: Sway
Windowing System: Wayland

**Comment by droidmonkey** [comment]
This isn't a keepassxc bug

You might be able to avoid the issue by using one of the Qt environment variables we point out in our documentation: https://keepassxc.org/docs/KeePassXC_UserGuide#_command_line_options
