### ISSUE TITLE
Document AppArmor profile fix in more obvious location

### ISSUE THREAD

**Issue by Amaylia** [keepassxreboot/keepassxc#11140]
## Summary
I recently switched from Keepass to KeepassXC on KDE Neon (Thank you, by the way, it's so nice to have a password vault with so many great features and that integrates well with my desktop 🙂)  and ran into an issue getting KeepassXC to connect with the KeepassXC-Browser extension in Firefox.  After debugging for a while, I saw in my logs that AppArmor was preventing Firefox from running the keepassxc-proxy executable.

**From /var/log/syslog:**
```shell
kernel: [388863.310626] audit: type=1400 audit(1722958446.462:133650): apparmor="DENIED" operation="exec" class="file" profile="firefox" name="/usr/bin/keepassxc-proxy" pid=425469 comm=444F4D20576F726B6572 requested_mask="x" denied_mask="x" fsuid=1000 ouid=0
``` 

## Examples

I did a little bit of research and I think the proper way to deal with this is to add an override entry into `/etc/apparmor.d/local/usr.bin.firefox`.  I'm not sure if this will work on distributions other than KDE Neon, and also, I'm using the Mozilla Team PPA for Firefox rather than the snap / flatpak version so this may be an issue that only affects a very small number of people, but, in case anyone else runs into it, what fixed it for me was adding  the following entry:

**/etc/apparmor.d/local/usr.bin.firefox**
```
/usr/bin/keepassxc-proxy Uxr,
```

This gives Firefox read and "unconfined" execute permission for `/usr/bin/keepassxc-proxy`.  In this context, unconfined, I think, is a special profile that doesn't have any restrictions. There is probably a better way to do this, but I don't know AppArmor very well, and I'm a little worried about trying to create a profile for keepassxc-proxy when I don't understand all of what it does and if some change down the road might break it.

But! After adding the above entry and running `sudo apparmor_parser -r /etc/apparmor.d/usr.bin.firefox` to rebuild and replace the current Firefox profile, KeepassXC-Browser was able to connect to the KeepassXC application and I no longer see AppArmor warnings in my log files!

## Context

I think most Ubuntu derivatives use AppArmor, but I'm not sure how many distributions ship with a Firefox AppArmor profile, mine does, and rather than disable the whole profile, this just pokes a new hole for KeepassXC-Browser to communicate with the proxy application.

## Conclusion

I'm not sure if your team wants to support it, or if this would be best added to the troubleshooting guide, but I wanted to share what I did to fix it for myself.  Please let me know if you'd like me to help in some way, and thank you for your time reading this and your time working on this project.  I deeply appreciate it!

**Comment by droidmonkey** [comment]
Hello and thanks for the kind words. This is well documented in our browser extension troubleshooting guide but clearly not accessible or obvious enough: https://github.com/keepassxreboot/keepassxc-browser/wiki/Troubleshooting-guide#6-apparmor-with-ubuntu

**Comment by Amaylia** [comment]
I'm sorry, this was my failure...

I think where I went off track was that it wasn't obvious to me at first that AppArmor was behind the problem, and I think by that time, I had stopped looking at the troubleshooting guide.  I should have gone back to it to check for the solution after I figured out it was AppArmor.

Thank you for taking the time to reply, and for being nice about my failure. 🙂

**Comment by Amaylia** [comment]
I don't know if this helps or not, but this command helped me identify it was AppArmor:
```shell
sudo journalctl -t audit | grep 'apparmor="DENIED"' | grep "$(which keepassxc-proxy)"
``` 
Which output a bunch of lines like this:
```
Aug 06 11:12:35 artemis audit[424575]: AVC apparmor="DENIED" operation="exec" class="file" profile="firefox" name="/usr/bin/keepassxc-proxy" pid=424575 comm=444F4D20576F726B6572 requested_mask="x" denied_mask="x" fsuid=1000 ouid=0
Aug 06 11:24:56 artemis audit[425064]: AVC apparmor="DENIED" operation="exec" class="file" profile="firefox" name="/usr/bin/keepassxc-proxy" pid=425064 comm=444F4D20576F726B6572 requested_mask="x" denied_mask="x" fsuid=1000 ouid=0
Aug 06 11:25:15 artemis audit[425097]: AVC apparmor="DENIED" operation="exec" class="file" profile="firefox" name="/usr/bin/keepassxc-proxy" pid=425097 comm=444F4D20576F726B6572 requested_mask="x" denied_mask="x" fsuid=1000 ouid=0
Aug 06 11:34:06 artemis audit[425469]: AVC apparmor="DENIED" operation="exec" class="file" profile="firefox" name="/usr/bin/keepassxc-proxy" pid=425469 comm=444F4D20576F726B6572 requested_mask="x" denied_mask="x" fsuid=1000 ouid=0
```

**Comment by droidmonkey** [comment]
Great we can add that to the troubleshooting guide 
@varjolintu

**Comment by varjolintu** [comment]
Did that. Closing the issue. Thanks!
