### ISSUE TITLE
Setting "allow screenshot" should not be in "View" menu

### ISSUE THREAD

**Issue by mdollinger** [keepassxreboot/keepassxc#11143]
## Overview
Can you please move the checkbox "Allow Screen Capture" from menu "View" to "Settings"?

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Ask a user to change the "Allow Screen Capture" flag
2. Watch, whether the user would first search in menu "View" or in the settings 

## Expected Behavior
The "Allow Screen Capture" flag should be located in the "Settings", probably section "Security".

## Actual Behavior
The "Allow Screen Capture" flag is currently located in menu "View", where no user would intuitively expect it.
<img width="442" alt="Screenshot_2024_08_08__09_28_37" src="https://github.com/user-attachments/assets/8598cb82-ac82-4e8a-bc27-a8e18748cf56">

## Context
The "Allow Screen Capture" flag definitely has the nature of a "setting".

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION 2.7.9

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows

**Comment by droidmonkey** [comment]
It is a temporary setting that resets on app close, it is where it is for a reason.

**Comment by mdollinger** [comment]
This is a valid aspect from technical point of view.
However, I am a user.
For me it is a flag to influence the apps behavior.
This is why i expect it under "Settings" (and others probably as well).

When there is a functionality to set this settings value back for security reasons, it would be a nice move to explain it to the user, eg. in brackets or in a mouseOver ...
