### ISSUE TITLE
KeepassXC does not start at all

### ISSUE THREAD

**Issue by vampyren** [keepassxreboot/keepassxc#11141]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
Application does not start at all!

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. click on the icon in taskbar
2. nothing opens
3. 
Also tried the real .exe file from "C:\Program Files\KeePassXC\KeePassXC.exe"

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
KeepassXC opens as usual

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
No window or anything

## Context
[NOTE]: # ( Give us any additional information you may have. )
Not much more to say....
Only thing i installed yesterday was DaVinci Resolve. This should not have anything to do with KeepassXC.

Also i can see in taskmanager this process running: keepassxc-proxy.exe
![image](https://github.com/user-attachments/assets/567bd3f6-f4b7-46e9-9e2d-34edf6154d11)

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.9
Revision: not sure as i can't start the app

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 11 x64

**Comment by phoerious** [comment]
#10925

**Comment by vampyren** [comment]
> #10925

Thank you! Reinstalling the MSVC redistributable package: https://aka.ms/vs/17/release/vc_redist.x64.exe  solved the issue for me.
