### ISSUE TITLE
Solution posted for issue 10925 not permanent - returns after reboot

### ISSUE THREAD

**Issue by NotGovernor** [keepassxreboot/keepassxc#11146]
Might want to reopen this one? (Issue: 10925)

Reinstalling the redistributable resolved the issue.... until a reboot a couple of weeks later... Some error again. Reinstalling fixes it again -- though we'd probably prefer not to have people have to do that after every reboot?

**Comment by droidmonkey** [comment]
Check your system cause that is not the behavior for anyone else at all.
