### ISSUE TITLE
Upgrade Fedora 39 to 40, switch from X11 to Wayland: KeePassXC windows open in left half instead of right half desktop window

### ISSUE THREAD

**Issue by kkarsten62** [keepassxreboot/keepassxc#11158]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
I upgrade from Fedora 39 to Fedora 40 and also then from X11 to Wayland.

In Fedora 39/X11 I always place the KeePassXC window in the half right part of the desktop screen.
When restarted KeePassXC the KeePassXC window was then always in the right part of the desktop screen.

Now with Fedora 40/Wayland it's position is always on the left half of the desktop screen. A previous position will be ignored. 

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Start KeePassXC
2. Position KeePassXC window in the right half of the desktop screen
3. Close KeePassXC
4. Reopen KeePassXC
5. ==> KeePassXC window is in the left part of the desktop screen, previous position will be ignored

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
KeePassXC window should in previous position as before with Fedora39/X11

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.9 (official Fedora version)
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: Fedora 40
Windowing System: Wayland

**Comment by droidmonkey** [comment]
This appears to be a Wayland protocol "feature" or a bug in Plasma. I can reproduce the same behavior in both KeePassXC and every other app I tested including KWrite and Gnome Text Editor. Although my apps end up centered in the screen and not moving from right to left. Either way, this isn't a KeePassXC issue.
