### ISSUE TITLE
2.7.9: Adding Challenge/Response reports no password, and removes the existing one

### ISSUE THREAD

**Issue by jdghub** [keepassxreboot/keepassxc#11150]
## Overview
I use KeePassXC to add YubiKey challenge-response security to an existing KeePass 2.x database protected with a password.

When I select the YubiKey and click OK in KeePassXC 2.7.8 it warns of a "weak password", but it does add the additional security.

When I do the same in 2.7.9 KeePassXC warns "No password set", and if I continue despite the warning it adds the challenge response but removes the existing password.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Open KeePass 2x DB with password security only.
2. Select Database > Database Security...
3. Click Add additional password > Add challenge-response
4. Plug in YubiKey if not already done and click refresh button as required
5. Click OK

## Expected Behavior
KeePassXC should now prompt "Present or touch your YubiKey to continue..." and when you do that it should add the challenge-response security, retaining the existing password.

## Actual Behavior
KeePassXC 2.7.9 warns:
> No password set
> WARNING! You have not set a password. Using a database without a password is strongly discouraged!
> Are you sure you want to continue without a password?

If you continue the challenge-response security is added, but the existing password is removed, and the next time you open the database you will have to enter no password while presenting the YubiKey.

## Context
This works as expected with 2.7.8 (though with a weak password warning, for a password that KeePass gives 108bits for a quality score)

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.9
Revision: 8f6dd13

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 11

**Comment by droidmonkey** [comment]
Duplicate, we have a fix lined up

**Comment by jdghub** [comment]
Thanks. I did search for an open "challenge" issue before posting but found none.
