### ISSUE TITLE
Resizing columns very laggy

### ISSUE THREAD

**Issue by revsuine** [keepassxreboot/keepassxc#11165]
## Overview

When I drag the column dividers inside a database, it causes the whole of KeePassXC to freeze up for a while until the columns resize. See the video:

https://github.com/user-attachments/assets/848db11f-cc0f-4fe3-8c58-c52f1dfaa642

## Steps to Reproduce

1. Open a KeePassXC database
2. Drag the columns to resize
3. See the freezing/lagging behaviour and how long it takes for the column size to catch up with your resizing

## Expected Behavior

Columns follow mouse cursor with low latency when holding down to drag to resize columns

## Actual Behavior

Significant delay in columns resizing, whole app freezes up when you try to resize with the mouse

## Context

`keepassxc --debug-info`:

```
KeePassXC - Version 2.7.9
Revision: 8f6dd13

Qt 5.15.14
Debugging mode is disabled.

Operating system: Artix Linux
CPU architecture: x86_64
Kernel: linux 6.10.3-hardened1-1-hardened

Enabled extensions:
- Auto-Type
- Browser Integration
- Passkeys
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 3.5.0
```

Using the [River](https://codeberg.org/river/river) Wayland compositor.

I've tried running KeePassXC from the terminal to see if there's any terminal output while this is happening, but didn't see anything whilst resizing. However, when I first start up KeePassXC, this is output on the terminal:

```
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
```

Otherwise there is no output, including while I was demonstrating in that video recording.

**Comment by droidmonkey** [comment]
This isn't a bug in keepassxc code: 

https://github.com/keepassxreboot/keepassxc/issues/11131#issuecomment-2267554964
