### ISSUE TITLE
KeePassXC is invisible on connected display

### ISSUE THREAD

**Issue by danielplaskur** [keepassxreboot/keepassxc#11162]
## Overview
I am experiencing an issue when trying to open KeePassXC or move KeePassXC to another display connected via the dock station. In the previous version, this was possible. However, now when I drag KeePassXC with the mouse to another display, it becomes invisible.
![image](https://github.com/user-attachments/assets/f56e4003-62c3-4e5a-b6b6-fea55e5746e5)

## Steps to Reproduce
1. Open KeePassXC
2. Drag it to another connected display
3. KeePassXC  is invisible.

## Expected Behavior
KeePassXC should not be invisible on another connected displays.

## Actual Behavior
KeePassXC is invisible on connected displays.

KeePassXC - Version 2.7.9
Revision: 8f6dd13

Qt 5.15.11
Debugging mode is disabled.

Operating system: macOS 14.5
CPU architecture: arm64
Kernel: darwin 23.5.0

Enabled extensions:
- Auto-Type
- Browser Integration
- Passkeys
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 3.1.1

**Comment by phoerious** [comment]
https://keepassxc.org/docs/KeePassXC_UserGuide#_screenshot_security

**Comment by droidmonkey** [comment]
https://github.com/keepassxreboot/keepassxc/issues/10757#issuecomment-2126342637
