### ISSUE TITLE
Issue with Circumflex Accent Input in Hidden Passwords on macOS Sonoma 14.6.1 using KeePass 2.7.9

### ISSUE THREAD

**Issue by Mike-Le-S** [keepassxreboot/keepassxc#11168]
Overview
When entering a password to open the database on macOS Sonoma 14.6.1 with KeePass 2.7.9, if the password contains a circumflex accent, the accent does not appear correctly when the password is hidden.

Steps to Reproduce
Open KeePass 2.7.9 on macOS Sonoma 14.6.1.
Enter a password containing a circumflex accent (e.g., "ê") to unlock a database while the password is hidden.
Observe the behavior of the accent.
Expected Behavior
The circumflex accent should appear correctly when typing the password, regardless of whether it is hidden or visible.

Actual Behavior
When the password is hidden, the circumflex accent does not display correctly (e.g., "ê" is shown as "e"). However, if I press the button to reveal the password, I can type the accent correctly.

Context
This issue occurs specifically when the password is hidden. It is reproducible every time under the mentioned conditions.

KeePassXC - 2.7.9

**Comment by droidmonkey** [comment]
This is a qt bug unfortunately. We recommend not using a password with accent characters
