### ISSUE TITLE
mullvad-browser integration / support

### ISSUE THREAD

**Issue by PhilBrk8** [keepassxreboot/keepassxc#11169]
## Overview:
I tried to set keepass up with the mullvad-browser, which is currently not working.

Since firefox, tor, and even librewolf are mentioned seperately in
https://github.com/keepassxreboot/keepassxc-browser/wiki/Troubleshooting-guide
i suppose the firefox-fork-tor-collaboration: mullvad-browser might need a seperate support from within keepassXC.

## Description / How to reproduce:
OS: Fedora WS 40
keepassxc --version  --> KeePassXC 2.7.9
installed keepassXC-browser extension in the mullvad-browser via the keepassxc_browser-1.9.2.xpi file I downloaded from firefox

copied the org.keepassxc.keepassxc_browser.json 
from ~ /.mozilla/native-messaging-hosts 
to ~ /.mullvad-browser/native-messaging-hosts
(~ /.mullvad-browser being the default config location)

with the content:
{
    "allowed_extensions": [
        "keepassxc-browser@keepassxc.org"
    ],
    "description": "KeePassXC integration with native messaging support",
    "name": "org.keepassxc.keepassxc_browser",
    "path": "/usr/bin/keepassxc-proxy",
    "type": "stdio"
}

and also:
![image](https://github.com/user-attachments/assets/6be5662e-0f7b-4aba-a892-b3be5de764fe)
did not change that the database can not be connected to the mullvad-browser.

## Context
Since the mullvad-browser gains more and more traction (especially since googles manifest V3 deadline is now being enforced and people are looking for chromium alternatives) and even librewolf and tor are handled seperately it might be nice to also integrate/support this browser in keepassXC

**Comment by droidmonkey** [comment]
See here: https://github.com/keepassxreboot/keepassxc-browser/issues/2002

At least back when that issue was filed Mullvad was doing dumb things that causes native messaging to fail. This isn't a keepassxc problem.

**Comment by PhilBrk8** [comment]
Sorry, I even searched for mullvad-browser, but nothing came up.
Would not have posted this otherwise.
