### ISSUE TITLE
Screen resize doesn't resize app

### ISSUE THREAD

**Issue by gemal** [keepassxreboot/keepassxc#11167]
## Overview
When I undock and the dock my laptop keepassxc doesn't resize

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. have keepassxc on large screen
2. undock to smaller screen
3. dock laptop
4. the app appears on large screen but looks zoomed
5. to fix I have to move it to the smaller screen and then back to large screen and eveything is OK
6. only this app does htis

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
keepassxc resizes to match screen

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
doesn't resize

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.9
Revision: 8f6dd13

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows
Windowing System: windows 11

**Comment by droidmonkey** [comment]
This is a qt limitation that will be resolved when we move to qt6.
