### ISSUE TITLE
Automated login user fails when selected user, with {USERNAME}{TAB}{PASSWORD}{TOTP}{TAB}{ENTER}; yet manual login works

### ISSUE THREAD

**Issue by dev4openid** [keepassxreboot/keepassxc#11163]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

I am a newbie to OPNSense.   The latest version: 24.7.1 
I set up my root account with PWD and set the OTP server as per the instructions.
It seems there is a gap in the GUI/functionality presentation, that is to say: In which field does one capture the TOTP?
So far I have established that, at the login, if one enters the username and then the password together with the OTP (this is done manually) it works! And if I use Ctl-Shift-V for autotype it refers back to last browser tab (where the OPNSense login is) and that works.
I have setup KeepassXC autotype fields as follows:   {USERNAME}{TAB}{PASSWORD}{TOTP}{TAB}{ENTER}
I am running ntpd on my Ubuntu w/station to ensure synchronous timing to ensure the TOTP is valid. 
When I am at the OPNSense login and trigger the KeepassXC plugin (i.e. the green icon) and select the same root account, the login fails.
Rinse and repeat manually and it works.  
There might be a bug in KeepassXC or the KeepassXC extension.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
![Screenshot from 2024-08-13 20-22-49](https://github.com/user-attachments/assets/6dfcdb6c-c0e0-4ad8-842e-4d1b1fea85fa)

1. At login, select root
2. The username root is auto entered
3. The password is auto entered (assuming the concatenation of PWD and TOTP)

## Expected Behaviour
[NOTE]: # ( Tell us what you expected to happen )

The login of root is successful

## Actual Behaviour
[NOTE]: # ( Tell us what actually happens )

The login of root fails (and the screen reverts to the above start image awaiting user selection)

## Context
[NOTE]: # ( Give us any additional information you may have. )

As per the overview, works manually but fails automatically

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.9
Revision: 8f6dd13

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux  (Ubuntu 24.04)
Desktop Env: Gnome
Windowing System: Wayland

**Comment by droidmonkey** [comment]
You are using browser integration not auto-type. Please review our user guide to get you going with auto-type: https://keepassxc.org/docs/KeePassXC_UserGuide#_auto_type

**Comment by dev4openid** [comment]
@droidmonkey,
as per my statement: I can execute the autotype functionality by invoking the Ctl-Shift-V.
That is not the issue.
It is that, as per the image, when one uses the dropdown on a page and selects the entry (in my case root for OPNsense login); the selection populates but does not carry the TOTP (meaning combine the PWD+TOTP) and the login fails.
It seems the plugin does not bring this into the PWD field.
Other than the autotype (which works), is there some other config I have to setup in order to get the PWD field to PWD+TOTP?
If so, looking through the doc does not explain it clearly. Maybe I missed it?

**Comment by droidmonkey** [comment]
We don't support concatonating fields with the browser extension. Your only option is auto-type

**Comment by dev4openid** [comment]
Thanks.
Seems like it.  Having to "hack" around the problem from a User's POW is not great.  Not easy to convince user adoption.

Perhaps......in the near future something will turn up.
