### ISSUE TITLE
2.7.9 Windows and Linux Keeshare multiple Sync Issues 

### ISSUE THREAD

**Issue by gwaitsi** [keepassxreboot/keepassxc#11173]
## Overview
- I have two users with their own DBs on dropbox
- I have a third DB on dropbox which is shared as a Group under Root on both
- one user is on a windows 10 machine the other user is on a ubuntu 24.04 machine
- subgroups created under the shared group no longer works (bug previously fixed i believe)
- creation of entries on either machine works in both directions, but deletion of an entry on works machine where the deletion occured. 
- 
## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. win10 with 2.7.9 and user1 dropbox account, usr1_db + (shared_db with edit permissions)
2. ubuntu with 2.7.9 and user2 dropbox account usr2_db + (shared_db with edit permission)
3. on win machine, create win_test (entry), create win_test (group), create win_test/win_group_test (entry)
4. on linux machine, create linux_test (entry), create linux_test (group), create linux_test/linux_group_test (entry)
5. 

## Expected Behavior
1. we should under shared_db, both win_test/linux_test (entries), both win_test/linux_test(child groups), both win_group_test/linux_group_test (entries und child groups) 

2. delete entry on win machine, should delete on linux machine and vis-versa

## Actual Behavior
1. win machine: we see under shared_db group: win_test/linux_test/linux_group_test(entries), win_test (child group), win_group_test(entry under child group)
    - child group is not created on linux machine
1. linux machine: we see under shared_db group: win_test/win_group_test/linux_test(entries), linux_test (child group), linux_group_test(entry under child group)
   - child group is not created on win machine

2. win machine: delete win_group_test (entry), win_test(child group), win_test(entry) 
     - win entries remain on linux machine
2. linux machine: delete linux_group_test(entry), linux_test(child group), linux_test(entry)
     - linux entries remain on win machine

## Context
if "use alternative saving method" is selected, it doesn't sync at all.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.9
Revision: 8f6dd13

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 10 v 2009 kernel 10.0.19045 / Kubuntu 24.04 Kernel: linux 6.8.0-40-generic
Desktop Env: Plasma 5.27.11
Windowing System: Wayland

**Comment by droidmonkey** [comment]
Hello there are numerous issues listed already for keeshare. It is being overhauled for the next major release. Closing due to duplicates.
