### ISSUE TITLE
When text in the Notes field is focused and selected, standard copy (⌘-C) should copy the text, not the password

### ISSUE THREAD

**Issue by brad2014** [keepassxreboot/keepassxc#11172]
## Overview
Previously, if I selected some text in the Notes field of an entry and hit the copy keyboard accelerator (on mac, ⌘-C), it copied the text. Now in 2.7.9, it copies *the password*. If I (muscle memory) select  some Notes text and copy/paste it onto a web page using the keyboard shortcut, I've just compromised my password!  

This is a usability issue that affects security.  Everywhere on my machine, "Select text -> Type ⌘-C" is standard for copying that text.  Copying a secret instead creates a dangerous usability foot-gun (which I've discharged repeatedly). 

## Steps to Reproduce

1.  Click on an entry, to display its notes.
2.  Select a word in the notes.
3.  Hit the standard copy accelerator (e.g. on mac,  ⌘-C)
4. Paste into some other window or web page.

## Expected Behavior
Revert to previous behavior:
1. If an entry as a whole (e.g. in the list) is selected, then ⌘-C copies the secret.
2. If a piece of text is selected and focused, then ⌘-C should not copy the secret.  It should copy the text.

## Other Notes
1. This used to work.
2. The context menu over the Notes field (right click) contains a "copy" menu item that works correctly (it copies the selected text). 
3. Inadvertently copying Notes text and pasting it, when I meant to paste a password is easily correctible. But inadvertently copying a password and pasting it on a web page results in password compromise (we'd insist on revoking and changing the password).  

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION
Revision: 2.7.9

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS
Desktop Env: macOS
Windowing System: MacOS

**Comment by droidmonkey** [comment]
This is fixed for the next release
