### ISSUE TITLE
keepassxc invisible on current openSUSE tumbleweed with KDE 6.1

### ISSUE THREAD

**Issue by thommierother** [keepassxreboot/keepassxc#11171]
## Overview
Fresh install of openSUSE tumbleweed with keepassxc 2.7.9. The keepassxc starts on the shell but is invisible in the KDE GUI. 

## Steps to Reproduce
1. install current openSUSE tumbleweed
2. install keepassxc 2.7.9 (package from suse rpm repo)
3. start keepassxc on the shell

## Expected Behavior
visible application

## Actual Behavior
application is starting, but invisible

thommie@locutus:~> ps -aux | grep keepassxc
thommie     4437  0.0  0.3 409024 106452 pts/4   SLl+ 18:04   0:00 keepassxc

## Context

Only error messages visible at startup are

thommie@locutus:~> keepassxc
kf.i18n: KLocalizedString: Using an empty domain, fix the code. msgid: "Save All" msgid_plural: "" msgctxt: "@action:button"
kf.i18n: KLocalizedString: Using an empty domain, fix the code. msgid: "&Yes" msgid_plural: "" msgctxt: "@action:button"
kf.i18n: KLocalizedString: Using an empty domain, fix the code. msgid: "Yes to All" msgid_plural: "" msgctxt: "@action:button"
kf.i18n: KLocalizedString: Using an empty domain, fix the code. msgid: "&No" msgid_plural: "" msgctxt: "@action:button"
kf.i18n: KLocalizedString: Using an empty domain, fix the code. msgid: "No to All" msgid_plural: "" msgctxt: "@action:button"
kf.i18n: KLocalizedString: Using an empty domain, fix the code. msgid: "Abort" msgid_plural: "" msgctxt: "@action:button"
kf.i18n: KLocalizedString: Using an empty domain, fix the code. msgid: "Retry" msgid_plural: "" msgctxt: "@action:button"
kf.i18n: KLocalizedString: Using an empty domain, fix the code. msgid: "Ignore" msgid_plural: "" msgctxt: "@action:button"

KeePassXC - 2.7.9
Revision: -2.1 (from openSUSE)
NOTE: The flatpak package available from flathub through the Discover software manager shows the same issue

See bug entry at https://bugzilla.suse.com/show_bug.cgi?id=1229022 for reference
X11 and wayland sessions show the same behaviour.

Environment:
Operating System: openSUSE Tumbleweed 20240816
KDE Plasma Version: 6.1.4
KDE Frameworks Version: 6.5.0
Qt Version: 6.7.2
Kernel Version: 6.10.4-1-default (64-bit)
Graphics Platform: X11
Processors: 8 × Intel® Core™ i7-4790K CPU @ 4.00GHz
Memory: 31.3 GiB of RAM
Graphics Processor: NVIDIA GeForce GTX 1650/PCIe/SSE2

**Comment by droidmonkey** [comment]
Based on your suse report, this isn't a keepassxc specific problem. There isn't anything on the Linux side that would make our program invisible. The only thing that would be similar is if you enabled:

- system tray icon
- minimize to system tray
- minimize on startup

And if the system tray was non existent. 

Proceed with the plasma debugging and come back if there is a definitive lead to keepassxc code. 

Also, we don't use KLocalizedString, that would be on the qt / plasma side. Those strings are all standard button strings.

**Comment by thommierother** [comment]
Thanks for the info, I added this to the SUSE report, further debugging should be done on their side.

**Comment by droidmonkey** [comment]
@thommierother I cannot replicate using Suse Tumbleweed live CD in a VirtualBox environment:

![image](https://github.com/user-attachments/assets/be786bff-32b1-4d5e-8c46-6dc7c722ad32)

**Comment by thommierother** [comment]
Yes, I know, I have this issue on one particular machine which now has been completely re-installed from scratch but still shows the same behaviour. We need some ideas from SUSE/KDE geeks how to debug this further - I have nearly no knowledge about the internals of QT/KDE unfortunately ...

**Comment by thommierother** [comment]
We are still struggling with this error on openSUSE Tumbleweed:
https://bugzilla.suse.com/show_bug.cgi?id=1229022

New attempts to get debugging info were unsuccessful, see the comments 7-16. The application still remains invisible (and therefore unusable) after startup. The only errors we see are the "kf.i18n: KLocalizedString: Using an empty domain, fix the code." messages on startup. Note that openSUSE Tumbleweed already uses KDE 6.1 with qt 6.7.2 but the libs from qt 5.15.14 are also present. I would be happy for some ideas how to get this debugged and fixed finally ...

**Comment by droidmonkey** [comment]
Qt has some env vars you can play with: https://keepassxc.org/docs/KeePassXC_UserGuide#_command_line_options
