### ISSUE TITLE
Adding challenge-response with nitrokey 3 removes master password from database

### ISSUE THREAD

**Issue by useross** [keepassxreboot/keepassxc#11174]
## Overview
Adding the challenge-respons with a nitrokey 3 removes the current master passwort by default from the database. A warning is displayed showing that the database is not protected by a password. The password has not been removed manually. 

Doing the same operation with a yubikey, adds the challenge-response to the existing password. I am very sure that this is the expected behavior. Should also work with nitrokey 3.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Generate a keepass database with a password
2. connect a nitrokey 3 (use nitrokey app 2 software to initialize the HMAC)
3. Add the challenge-response to the keepass database using this nitrokey
4. when pressing OK, there is a warning that there is no database password. But the password has not been removed manually

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
The challenge-response should be added to the database, so you need two things at login: password and nitrokey.
Note that this behavior (as expected) is working for yubikeys so far.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Adding the challenge-response with a nitrokey removes the database master password.

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.9
Revision: 8f6dd13

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: Gnome
Windowing System: Wayland

**Comment by droidmonkey** [comment]
Fixed for next release, unfortunately with 2.7.9 you have to set the password again and add the hardware key at the same time.
