### ISSUE TITLE
Use one entry for multiple sites by having multiple URL fields

### ISSUE THREAD

**Issue by LetItGlow** [keepassxreboot/keepassxc#11179]
Hello there.

I am using KeepassXC for a while and during some password maintainance, I came across a couple of odd entries.
I have 3 entries for the very same webpage. We are gonna call this "Triangle-Enix" for now.

All of those entries point to a different URL, but still use the same user/password.
If I would update my password on the service side of "Triangle-Enix", I would have to update all those 3 entries manually, because "update" in the browser extension would just update the entry for that particular URL.

The new proposed feature(s) I had in mind would be either:

1. to be able to add multiple URL to one entry.
2. Have entries have a string macro to another entry in the same DB. 

The latter option would be something like (if the main entry is called "Triangle-Enix", the others can refer to that by `{{Triangle-Enix:username}}` and `{{Triangle-Enix:password}}` for the fields respectively.
However, I am aware of the cons of the "macro" method:
1. I doubt, if adding string macros to a password manager is a good idea.
2. If the name of the referred entry is changed, it will just break or return blanks.

So, back to the first method: 
The benefits of adding multiple URL to one entry:
If the username or password is changed for THAT entry, there will still be one entry and the creds will be used across the defined URLs.
This also saves clutter inside the manager by not having 3 Million entries.
I also tried setting a * wildcard (for example `https://*.triangle-enix.com` ) , but KeepassXC doesn't let me.

If this already exists, please tell me how to use it.

**Comment by mpas97** [comment]
Yes, you can already add multiple URLs to an entry: https://keepassxc.org/docs/KeePassXC_UserGuide#_advanced_usage
The wildcard feature is just being implemented: https://github.com/keepassxreboot/keepassxc/pull/9835

**Comment by droidmonkey** [comment]
You can also clone an entry and reference the username and password of another one.
