### ISSUE TITLE
keepassXC 2.7.9 crashes in Win10 22H2 with exception code 0xc0000005

### ISSUE THREAD

**Issue by larshaendler** [keepassxreboot/keepassxc#11178]
## Overview
Updated my KeepassXC to current version 2.7.9 (KeePassXC-2.7.9-Win64.msi) on my Win10 (22H2) and it wont start anymore. I checked the Windows 10 event log shows exception code 0xc0000005 in MSVCP140.dll. 

## Steps to Reproduce
1. Updated to 2.7.9 (KeePassXC-2.7.9-Win64.msi) on my Win10 Home 22H2 machine
2. KeypassXC wont start

## Expected Behavior
normal application start

## Actual Behavior
KeypassXC wont start neither with desktop shortcut nor with executing it directly via KeePassXC.exe from the programs folder. Windows event log shows a big red Application Error every time I try to start KeepassXC. 

I uninstalled 2.7.9 and reinstalled 2.7.5 release (KeePassXC-2.7.5-Win64.msi), then everything works just fine. Installing 2.7.9 again brings the same error. 

## Context
Windows Event log shows this. Sorry, it is a German Windows 10:

Name der fehlerhaften Anwendung: KeePassXC.exe, Version: 2.7.9.0, Zeitstempel: 0x6673531d
Name des fehlerhaften Moduls: MSVCP140.dll, Version: 14.36.32532.0, Zeitstempel: 0x04a30cf0
Ausnahmecode: 0xc0000005
Fehleroffset: 0x0000000000012f58
[...]
Pfad der fehlerhaften Anwendung: C:\Program Files\KeePassXC\KeePassXC.exe
Pfad des fehlerhaften Moduls: C:\WINDOWS\SYSTEM32\MSVCP140.dll

These 6 line are identical every time I tried to start 2.7.9. There seems to be a problem with MSVCP140.dll. 

## Misc
KeePassXC - 2.7.9
KeePassXC-2.7.9-Win64.msi
Operating System: Win10 Home (22H2)

**Comment by mpas97** [comment]
This is known: https://github.com/keepassxreboot/keepassxc/issues/10925
See the first line, you need to reinstall MSVC
