### ISSUE TITLE
Option to View Group Panel Missing

### ISSUE THREAD

**Issue by MUTOAD** [keepassxreboot/keepassxc#11184]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
The view menu no longer has an option to view or hide the group panel after upgrading to version 2.7.9. After upgrading to the latest version, the group panel is not being displayed and the option to toggle its display is not being presented in the View menu.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Upgraded KeepassXC to version 2.7.9 from prior version
2. Group panel is missing from UI
3. No menu item is presented in the View menu to have the UI display the panel

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
View menu should provide a menu option to toggle the display of the Group Panel

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Group Panel is not displayed and the UI does not provide a way to show it.

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.9
Revision: 8f6dd13

Qt 5.15.11
Debugging mode is disabled.

Operating system: Windows 11 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.22631

Enabled extensions:
- Auto-Type
- Browser Integration
- Passkeys
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 3.1.1

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 11

**Comment by droidmonkey** [comment]
Just drag from the left of the window
