### ISSUE TITLE
KeePassXC-2.7.9-Win64.msi wont run

### ISSUE THREAD

**Issue by Hodgy75** [keepassxreboot/keepassxc#11182]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
downloaded 2.7.9 Win64 installer to upgrade to latest version, running Windows 11. Installs but doesn't run. Uninstalled 2.7.9 and ran 2.7.8 installer, everything runs fine.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. run 2.7.9 installer (no option to run as admin or just user - only intall, repair & uninstall)
2. run app from start menu, nothing happens
3. 

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
keepass runs

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
keepass doesn't run

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION 2.7.9
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows
Desktop Env:
Windowing System:

**Comment by droidmonkey** [comment]
https://github.com/keepassxreboot/keepassxc/issues/10925
