### ISSUE TITLE
Allow delete plugin-related data for multiple entries

### ISSUE THREAD

**Issue by bitrate16** [keepassxreboot/keepassxc#11185]
## Summary
KeePassXC Browser extemsion relies on "KeePassXC-Browser Settings" plugin entry and I can not figure out how to clear this "Always Allow" for all database records. The feature request is to add ability to clear/patch/delete/whatever multiple or all entries to delete all previous Always Allow/Deny selectors

## Context
Periodically clearing excessive accesses to passwords that I've already forgot about, in order to prevent leaking on malformed sites/extensions/etc with valid working keepassxc daemon

**Comment by varjolintu** [comment]
Maybe this could be added to Database Reports -> Browser Statistics.

**Comment by droidmonkey** [comment]
My thought exactly
