### ISSUE TITLE
use the same credential in more than one entry

### ISSUE THREAD

**Issue by potenti** [keepassxreboot/keepassxc#11186]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # use the same credential in more than one entry, and edit more than one at a time.
Reason for using AD, where you change the password every month on several sites

## Examples
[NOTE]: # in atached

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )

**Comment by droidmonkey** [comment]
Use entry clone. https://keepassxc.org/docs/KeePassXC_UserGuide#_clone_an_entry

**Comment by potenti** [comment]
@droidmonkey That's not what you sent, I'll send an example, this example is from within the SecureCRT application, where I can save several ssh sessions and select the credential I want, then if I need to change the credential I just change it in the credential registration and it changes it for all ssh sessions that have the credential registered.

![WhatsApp Image 2024-08-21 at 08 47 23](https://github.com/user-attachments/assets/03662798-66ee-45ef-b53c-e0c6af44705a)

![WhatsApp Image 2024-08-21 at 08 51 11](https://github.com/user-attachments/assets/2e7eb364-bcf6-48c4-95ed-e3461b43c14b)

**Comment by droidmonkey** [comment]
Ummm no, you requested to use the SAME credential in more than one entry, thus you need to use entry clone with referencing username/password. Thank you.

**Comment by potenti** [comment]
It would be a useful feature, but more for people using Active Directory users, But thanks anyway

**Comment by potenti** [comment]
I have several +300 sessions, where the Active Directory user is used and the credential is changed every 1 month, in this case how would I change all 300 at once? It would be more interesting if it were something similar to the evidence sent.

**Comment by potenti** [comment]
![WhatsApp Image 2024-08-21 at 09 09 01](https://github.com/user-attachments/assets/fbc09a05-ac44-4b98-909b-335596916624)

**Comment by droidmonkey** [comment]
When you reference the main entry you just change the password ONCE in the main entry. The others just pull from there. Read the documentation I linked you...
