### ISSUE TITLE
Intune Win32 store app auto update url

### ISSUE THREAD

**Issue by schirrmie** [keepassxreboot/keepassxc#11189]
## Overview
Hey,
we distribute KeePassCX over Microsoft Intune as a Win32 Store App. We have some issue with the auto update of the app.
In the microsoft documentation https://learn.microsoft.com/en-us/mem/intune/apps/store-apps-microsoft#microsoft-store-win32-apps they say:
"
Third party vendors or publishers that add Win32 apps to the Microsoft Store are responsible for hosting their own content in their respective infrastructure. If your devices are behind a firewall, please reach out to application owner to understand and confirm network requirements.
"

Of course we have a firewall but we don't know the URL for access. Do anybody know the cdn url of keepassxc to do the right firewall rules?

**Comment by droidmonkey** [comment]
This is the current full-path URL: https://store.dmapps.us/KeePassXC-2.7.9-Win64.msi

This is hosted on Cloudflare's R2 service (it's a CDN)

**Comment by schirrmie** [comment]
Thank you very much, we will try it!
