### ISSUE TITLE
2.7.9 silent crash on Win10 - work around for portable installations

### ISSUE THREAD

**Issue by realHenningLorenzen** [keepassxreboot/keepassxc#11188]
On #10925:

> ## SOLUTION
> Reinstall the MSVC redistributable package: https://aka.ms/vs/17/release/vc_redist.x64.exe

_Originally posted by @droidmonkey in https://github.com/keepassxreboot/keepassxc/issues/10925#issuecomment-2191398305_

I am using the portable edition.

Reinstalling the MSVC runtime is not practical for me because I lack the necessary privileges on my machine.

I chose to install the 'legacy' build which seems to work fine for me as well.

**Comment by droidmonkey** [comment]
Pester your IT staff to update the system. Not much we can do about it.
