### ISSUE TITLE
Copy and Pasting Password into MatLab Installer gives "wrong password" error

### ISSUE THREAD

**Issue by 3fishes** [keepassxreboot/keepassxc#1118]
As stated in the title, when copying the password from KeePasXC and pasting it into the password field of the MatLab installer, the installer gives an "incorrect password" error.  However, if I am to copy the password from KeePassXC, and paste it into TextEdit, then copy it from TextEdit and paste from there in to MatLab, everything works fine.  

In my mind, both of these copy commands should be copying exactly the same sequence of characters, and then pasting the exact same sequence of characters, so pasting the password into a temporary location should do nothing.  Not to mention that pasting it to a temporary location is pretty insecure, as it sits there displayed in plaintext until you delete it!

It is remotely possible that this is an issue with the MatLab installer, but I find that unlikely.

## Expected Behavior
1. Copy password from KeePassXC (Using cmd-c, the right click menu, or even editing the entry, clicking the eye to show the password, and copying it from there)
2. Paste password in to MatLab installer.
3. MatLab installer accepts the password as correct and continues

## Current Behavior
1. Copy password from KeePassXC 
2. Paste password in to MatLab installer.
3. MatLab reports incorrect password

## Possible Solution
In my mind, as possible reason for this is: whatever KeePassXC is putting into the mac clipboard with its copy command is not the same as what is put into the clipboard when the user copies from TextEdit.  Maybe some characters use a different encoding scheme, or there is junk data at the beginning or the end of the copied data.  Can the mac clipboard be viewed byte by byte?

A (bad) workaround is this:
1. Copy password from KeePassXC
2. Paste password into TextEdit (It's now shown in plaintext!)
3. Copy password from TextEdit
4. Paste password into MatLab

## Steps to Reproduce (for bugs)
1. Copy password from KeePassXC 
2. Paste password in to MatLab installer.
3. Observe that MatLab reports incorrect password

## Context
This is the most basic usage of KeePassXC.  Save passwords, copy them in to password fields.  It really shouldn't ever have an error doing this.

## Debug Info
KeePassXC - Version 2.2.0
Revision: caa49a8ef3ee28ed478192389b21d61107b3b8e0

Libraries:
- Qt 5.9.0
- libgcrypt 1.7.7

Operating system: macOS Sierra (10.12)
CPU architecture: x86_64
Kernel: darwin 16.7.0

Enabled extensions:
- KeePassHTTP
- Auto-Type
- YubiKey

**Comment by 3fishes** [comment]
I have updated to 2.2.2.  Issue persists.
Interestingly enough, the issue does *not* occur when performing Auto-Type!
This further points to my idea that is has something to do with the clipboard.

**Comment by slindsen** [comment]
I have the same problem while copy & pasting password into Android Studio (Keystore passwords). If I paste the password into TextEdit and copy it again, then everything works fine. But directly it doesn't work with 2.2.2.

**Comment by weslly** [comment]
Probably related to #720

**Comment by droidmonkey** [comment]
I bet this is fixed with that latest pr
