### ISSUE TITLE
Cannot connect to KeepassXC-browser with Microsoft Edge Beta (Linux)

### ISSUE THREAD

**Issue by tsoernes** [keepassxreboot/keepassxc#11183]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
I cannot connect to KeepassXC-browser with Microsoft Edge Beta (Linux)

"
KeePassXC-Browser has encountered an error:

Cannot connect to KeePassXC. Check that browser integration is enabled in KeePassXC settings.
"

I have enabled browser integration and "Edge" in settings.
I have tried setting custom browser configuration location to `~/.config/microsoft-edge-beta`
## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. 
2. 
3. 

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux Fedora 40
Desktop Env: KDE
Windowing System: Wayland

**Comment by droidmonkey** [comment]
Use the custom browser option

https://keepassxc.org/docs/KeePassXC_UserGuide#_advanced_usage

See advanced browser settings

**Comment by tsoernes** [comment]
![keepassxc](https://github.com/user-attachments/assets/8068bf85-5aec-4817-9cbb-885723464ea5)
@droidmonkey  I'm not getting it to work.

**Comment by droidmonkey** [comment]
You need to add `/NativeMessagingHosts` to the path after what you already have there
