### ISSUE TITLE
no working Auto-Type on https://www.fielmann.de/signin/ (have tried several Auto-Type strings…)

### ISSUE THREAD

**Issue by zWhdmB5T** [keepassxreboot/keepassxc#11180]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
no working Auto-Type on https://www.fielmann.de/signin/ (have tried several Auto-Type strings…)

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. have tried several Auto-Type strings on https://www.fielmann.de/signin/
- Standard
- `{USERNAME}{TAB}{PASSWORD}{ENTER}`
- `{USERNAME}{TAB}{RIGHT}{DELAY 1000}{PASSWORD}{DELAY 1000}{TAB}{SPACE}`
- have tried some other strings…

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
successful login

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
no login, window returns — other sites of my bookmarks do work properly (with Auto-Type)

## Context
[NOTE]: # ( Give us any additional information you may have. )
Mozilla Firefox 129.0.1

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.9
Revision: 8f6dd13

[NOTE]: # ( Pick choices based on your environment )
Operating System: openSUSE Leap 15.6
Desktop Env: Xfce 4.18
Windowing System: X11

**Comment by droidmonkey** [comment]
Works fine:


https://github.com/user-attachments/assets/c2d9df06-eab5-4ffa-9a3d-5cc834b807a4

**Comment by zWhdmB5T** [comment]
@droidmonkey 

> Works fine:

??? Really? Are you actually logged in? This essential step is NOT shown in your video.

Of course, Auto-Type _itself_ works at my side! But I am not logged in! The origin window returns… When I copy and paste username and password manually, then I get logged in. (So, username and password are correct and regular login at my side works.)

(Well, of course I meant Auto-Type WITH a successful login… What do you think why I explicitly mentioned different Auto-Type strings?)

**Comment by droidmonkey** [comment]
I don't have an actual account for this website, but that doesn't appear to be a problem based on what was typed. We don't and can't fix problems with emulated typing on specific websites.

**Comment by zWhdmB5T** [comment]
Well, I wonder _why_ it does not work…

To repeat: the Auto-Type _itself_ works. But then, there is no successful login but return to the origin window.

This is why I have tried different strings… And tags like `{DELAY n}` or `{RIGHT}`…

I have many items in my KeePass. And many are connected with Auto-Type and do work. Some of them have a non-standard Auto-Type, but an individual Auto-Type. But they do work.

But on this site, there's no login using Auto-Type. Just when doing it manually.

**Comment by zWhdmB5T** [comment]
@droidmonkey 

Yes! I have a solution for my side. :-) 

- password before:
```
`b,p'|Ech[":s%4StC5NKgf>X(V_2dm,
```
- password now: using lowercase letters, uppercase letters and digits only (no special characters, like before), length of string = 32

But I wonder why Auto-Type did not work before. Manually entering username and password (that password) worked. So, the server itself accepted the password. I guess something went wrong with Auto-Type and special characters…

**Comment by droidmonkey** [comment]
This might be related to some international keyboard issues we have on linux auto-type (documented in other issues). Glad you could figure it out though!

**Comment by zWhdmB5T** [comment]
@droidmonkey 

Idea…

The "password generator" dialogue in the GUI of KeePassXC does offer several categories like lowercase letters (harmless), uppercase letters (harmless), digits (harmless) and some categories of different special characters (could be harmful due to the point you mentioned).

What about a specific category of special characters that are "proven" to be harmless (due to the point you mentioned). It should consist of as many special characters as possible but all "proven" to be harmless. This is to satisfy the need when a server asks (when creating a password) for even special characters.

**Comment by droidmonkey** [comment]
Since those characters vary by site and language that would be somewhat impossible to get "right". You can always manually remove or replace problematic characters in the generated password or add ones you don't want to appear to the "do not select from" control (show advanced settings in password generator).

**Comment by zWhdmB5T** [comment]
@droidmonkey 

Thank you!
