### ISSUE TITLE
AppImage version will not connect with Browser Integrating on Chromium, but will on Firefox

### ISSUE THREAD

**Issue by delinuxco** [keepassxreboot/keepassxc#11194]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
KeePassXC will not connect to KeePassXC-browser on Chromium, but it will on Firefox. Did not try Chrome.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Install AppImage 2.7.9
2. Enable Browser integration in KeePassXC settings
3. Add KeePassXC-Browser  extension in Chromium 

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
   KeePassXC-Broswer should connect to KeePassXC database

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
   No databases found. But if KeePassXC Binary package installed, integration works fine.

## Context
[NOTE]: # ( Give us any additional information you may have. )
   Everytime Chromium is started, KeePassXC main window opens, regardless if locked or not.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC.AppImage - 2.7.9
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux Mint - LMDE6
Desktop Env: Cinnamon
Windowing System: X11

**Comment by droidmonkey** [comment]
We have a robust troubleshooting guide, please go through that to try and discover what the problem is: 

https://github.com/keepassxreboot/keepassxc-browser/wiki/Troubleshooting-guide
