### ISSUE TITLE
Possible Bug in Entry > Auto-Type for KeePassXC 2.8.0?

### ISSUE THREAD

**Issue by taylor-p-mason** [keepassxreboot/keepassxc#11195]
When visiting this site to login, **https://www.sellingplatformconnect.amadeus.com/login** using **KeePassXC 2.8.0** on **Windows 11 23H2**, isn't filling in the advance attribute (string field) assigned to it when using the auto-type option as expected. 

![2024-08-24001377](https://github.com/user-attachments/assets/d2b26d80-6cc4-4217-9f21-20d6ec2e816c)

Note in the above screenshot, the credentials are not genuine and used only as an example. KeePassXC should be able to fill these fields for the "username, office ID (as an attribute) and the password" using Auto-Type, right? 

Here are the steps I applied;

1) I made an Entry with the title, username and password.

2) In Entry > Advance - I add the attribute (as the office ID - it's just a number like LON755886) as clear text. 

3) In Entry > Auto-Type - I add to "Window Associations" - Amadeus Selling Platform Connect — Mozilla Firefox.

4) Then I used a specific sequence for this association as; 

`{TAB}{USERNAME}{TAB}{TAB}{S:OfficeID}{TAB}{PASSWORD}{ENTER}`

but, only the username and password get filled in, never the office ID (attribute) into the string field using auto-type. 

I also used the KeePassXC browser extension icon to select the username, string field and password and confirmed, but this too didn't fill in the string field for the missing attribute needed. After investing lots of time on this, reading the manual, I still couldn't get this to work. So, unless there is another way to do this, it would seem the the function isn't working as expected and there is a bug? 

![2024-08-25 002040](https://github.com/user-attachments/assets/9f8c426a-9fe0-4b3b-b758-7d03a9697ff5)

Here is another website: **https://qweb.zucchetti.com/SuiteQWeb/ActionLogin.do** for KeePassXC to login, that has even more fields to fill in. If anyone can explain or show a working example of how to fill in all the fields using KeePassXC 280, I would appreciate the help, but at the moment still think this is a bug, because it's not working as expected.

**Comment by droidmonkey** [comment]
Make sure your advanced attribute is actually named `OfficeID` exactly. Case Matters. Works fine for me when tested:


https://github.com/user-attachments/assets/a9f8cb2b-a353-4762-85ef-f985324d4bba

**Comment by taylor-p-mason** [comment]
Thank you so much Jonathan White for the video! :-) 

At first, I wasn't sure if you were testing on **v2.8.0**, or on Windows 11 **23H2**, or using **Firefox**, not that it matters, but thinking why I am still experiencing the difficulty is all? Then I found an old ENTRY leftover from a previous KeePass database that got imported into KeePassXC, that displayed under the Entry > Advance section, the attribute in both panes here, in the left and right sides. 

That is when I discovered, the second right pane side, needs the attribute name to also be inserted there too. Once I did that, everything worked. Can you imagine? So close, so simple like that! Jeeeeeeez! I almost had it. 

However, when I started filling in more new Auto-Type attributes for larger login forms, where you need 3 string fields, when adding these attributes, only one of them will display in the right side pane, although if you click on the left side on each different attribute it does then display only for that attribute item when selected. Is this action correct, or should these attributes be displayed for all of them on the right side pane here at all times? What is the purpose of hiding the additional attributes when there is more than one inserted am I thinking? 

So, if anyone else is trying to use the Auto-Type feature and was experiencing some difficulties like me, I think if your video had also included the ADVANCE section where you insert the attribute/s, in both the left and right panes, this would had improved your answer back to me, and perhaps many more end users of KeePassXC for greater clarification. As that would had saved me here, first thing upon sight. WTF, why didn't I include the attribute in the second right side pane - that would had surely struck out in my thoughts after seeing this ...   

I don't know why I had missed this step, I guess I didn't understand the purpose of having a second pane to the right for. For some reason I had just assumed, when inserting the attribute, that would had been sufficient, enough, done! Funny me, right? 

Hopefully, if anyone else is reading this, for the sake of getting their Auto-Type working in KeePassXC, don't give up for goodness sake, keep trying! It really does work after all! Amazing that it is too! ;-)

**Comment by droidmonkey** [comment]
Hi there glad you got it to work. We do have excellent documentation that would help you as well: https://keepassxc.org/docs/KeePassXC_UserGuide#_additional_attributes
