### ISSUE TITLE
Autotype Not Working With VMware Horizon Client Version 2312.1

### ISSUE THREAD

**Issue by thesilas** [keepassxreboot/keepassxc#11209]
## Overview
In Windows, using VMware Horizon Client version 2312.1, the autotype feature does not function on the VMware Horizon Client login screen. It works correctly after the main authentication when logging into a host, but it fails to automatically input the username and password when logging into the VMware Horizon Server.

## Steps to Reproduce
1. Open the VMware Horizon Client
2. Clock on a Server to initiate the connection
3. Press the autotype shortcut during the login screen

## Expected Behavior
The credentials from the database are filled in, and the login is successfully performed.

## Actual Behavior
Nothing is typed into the username and password fields.

## Context
This issue did not occur with a previous version of VMware Horizon Client. I checked if the security context of the VMware Horizon Client had changed, as I have experienced a similar issue with another login screen after an update, where the new version was running under the system context and KeePass under the user context. However, both VMware Horizon Client and KeePass are running under the user context.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.7
Revision: 68e2dd8

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 11 Version 2009
Desktop Env: n/a
Windowing System: n/a

**Comment by droidmonkey** [comment]
If this used to work and the only thing that changed was VMware horizon client, then this isn't a keepassxc bug. We also offer "Virtual Keyboard" mode in windows, which you can use by adding `{Mode: Virtual}` to the beginning of your typing sequence. Closing this as there doesn't appear to be an action on our end right now. 

You should also update to 2.7.9. There were some fixes to autotype behavior.
