### ISSUE TITLE
App will show white panel after minimize

### ISSUE THREAD

**Issue by emptylight370** [keepassxreboot/keepassxc#11202]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
When I left the app display as a normal window and move to another window to do something, my KeepassXC will reach the time limit and auto lock the database. After auto lock, I move back to keepassXC will see a white panel.
After unlock database and minimize the window and reopen the window, keepassXC will show a white panel.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
One way to reproduce
1. Unlock database
2. Copy password or open edit panel(just do something)
3. Turn to another app and leave keepassXC and database open
4. Wait until database lock or just a while(I'm not sure)
5. Return to keepassXC and see the white screen

Another way to reproduce(looks like another issue)
1. Unlock database
2. Minimize the window(no lock when minimize)
3. Reopen the window

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Display unlock database screen and wait for next unlock.
Or if database still open, show normal database view.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Display a white panel, but the buttons can be selected. Just can't see nothing. And browser extensions and auto-type window works bad at this time.

## Context
[NOTE]: # ( Give us any additional information you may have. )
Here is a white panel screenshot.
![Clip_2024-08-27_19-42-29](https://github.com/user-attachments/assets/8b908e48-75d2-4b65-aa52-761a607b42af)
![Clip_2024-08-27_19-43-34](https://github.com/user-attachments/assets/2b32ca1e-dc93-43aa-a3ef-99112e4ca205)
I use 2.7.9 at first, but after this problem happened, I tired to install latest MSVC REDIST, but useless. Then I tried the latest debug version 2.8.0-snapshot(252274), the problem still exists.
If close keepassXC now, it will totally exit, and needs restart the app.

It looks like other issues, but I found them after I finish this issue, so sorry for reporting an extra issue.
I list them here: #10165 ,(I thought it looks like 9181 at first, but later I found it different)

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 版本 2.8.0-snapshot
构建类型：Snapshot
修订版本：48d0f2b

Qt 5.15.11
已禁用调试模式。

操作系统：Windows 11 Version 2009
CPU 架构：x86_64
内核：winnt 10.0.22635

已启用的扩展：
- 自动输入
- 浏览器集成
- Passkey
- SSH 代理
- KeeShare
- YubiKey
- 快速解锁

密码学公共库：
- Botan 3.1.1

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows

**Comment by droidmonkey** [comment]
That window doesn't look like windows 11, are you running some crazy theme software? This does not appear to be a problem with keepassxc code.

**Comment by emptylight370** [comment]
It's a Windows theme modify application, after disable and uninstall it the problem still exists.
![Clip_2024-08-27_23-01-33](https://github.com/user-attachments/assets/2ed99e08-6883-4fad-901d-16b50e769a2c)

**Comment by emptylight370** [comment]
I change my system from dark mode to light mode, then reproduce the problem.

**Comment by emptylight370** [comment]
Should I check the problem with Qt? I have other Qt app on my computer and they work well.

**Comment by emptylight370** [comment]
Sorry, I think I find the problem. It's caused by an app, "myDockFinder". It's newly installed these day, 和 it have a minimize animation(preform like macOS). When minimize keepassXC(to it's dock), it will show the animation, then recover keepassXC will show the animation again. Then keepassXC will become white. After disable the animation, the problem disappeared. I will report the problem to myDockFinder developer.
Additional information. I checked "minimize to tray" option. So keepassXC should close window when minimize, but the app stop it. So I think it might be the cause. I just try to uncheck the option and show the animation, and keepassXC didn't become white.
