### ISSUE TITLE
Favorite for KDE Plasma menu shortcut for KeepassXC sometimes working, sometimes not

### ISSUE THREAD

**Issue by trancephorm** [keepassxreboot/keepassxc#11204]
## Overview
Favorite for KDE Plasma menu shortcut for KeepassXC sometimes working, sometimes not

## Steps to Reproduce
1.  Install KeepassXC snap version in Ubuntu 24.04, KDE Plasma 5
2. Put the shortcut in Favorites

## Expected Behavior
Favorite should launch KeepassXC always

## Actual Behavior
Works only sometimes

[NOTE]: # ( Paste debug info from Help → About here )
Doubt there is any debug for this, because it's system related.

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: KDE
Windowing System: X11

**Comment by droidmonkey** [comment]
This wouldn't be a keepassxc problem, per say. You'll have to debug why the shortcut doesn't launch the program requested. Unless keepassxc is already running within the system tray.

**Comment by trancephorm** [comment]
Tested it a bit more. Sometimes it's working, sometimes not, completely erratic, tried to find some KDE logs related to it, it's hard... I would debug it somehow if I knew how.

**Comment by qbast** [comment]
Does it happen only for keepassxc ? I noticed something like that on other applications (I am also running Plasma 5 on Kubuntu 24.04) . It happens on random - I try to start an app and startup icon just 'blinks' for a split second and vanishes. Second attempt to run the same app succeeds. I have no way of reproducing it reliably, but I have a hunch that it might have something to do with snap.

**Comment by droidmonkey** [comment]
There is no way for us to do anything about this. I cannot reproduce it at all on plasma 6.

**Comment by trancephorm** [comment]
I've noticed Favorite icon sometimes is not working with lot of apps, especially it's the case with Telegram. I guess something gets broken when app gets updated, but the difference with Telegram and KeepassXC is that former is not fixing itself (you have to delete Favorite and reinstate it again), and the latter somehow fixes the favorite in the unsuccessful launching attempt. Will report more if I find something out.

**Comment by qbast** [comment]
@droidmonkey it might be plasma 5 specific. I also don't think I have seen it  ever happening on 6.  On plasma 5 random apps not starting was an inconsistent, but ongoing problem, on 6 it just stopped happening.

**Comment by trancephorm** [comment]
I've noticed Favorite icon sometimes is not working with lot of apps, especially it's the case with Telegram. I guess something gets broken when app gets updated, but the difference with Telegram and KeepassXC is that former is not fixing itself (you have to delete Favorite and reinstate it again), and the latter somehow fixes the favorite in the unsuccessful launching attempt. Will report more if I find something out.
