### ISSUE TITLE
[feature]

### ISSUE THREAD

**Issue by bigalgeorge** [keepassxreboot/keepassxc#1120]
Features requests:
(1)  Tools/Settings/General/Basic Settings [x] Enter/Double-Click =  Open URL (of highlighted entry instead/as well as Ctrl-U In application mainform)
(2) Ability to quick search and go to url from Tray Icon
(3) History of previous urls from Tray with max_entries (history number) defined in General/Basic Settings. EG Click Tray shows previous searched items to Max_Entries and click on opens in new tab clicked item url.
(4) Lastpass style form entries eg credit cards fill. Assume this would be fairly difficult to implement.

KeePassXC - 2.2.2

Operating system: Linux/Mint
CPU architecture: ARCH
Kernel: KERNEL

Enabled extensions:
- EXTENSIONS

**Comment by GuilloOme** [comment]
@bigalgeorge, you should close this one and open 4 issues (one for each of your request), this way it will be easier to track the discussion about it. Please, also take some time to develop your idea.

**Comment by bigalgeorge** [comment]
I submitted this one as a compilation, it should be separate to make it clearer.
