### ISSUE TITLE
Keepass on MacOS using dual extended screen mode, no window is visible

### ISSUE THREAD

**Issue by chkratzer** [keepassxreboot/keepassxc#11211]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
Keepass on MacOS using dual screen with Instant view is not opening the window

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Start Keepass
2. No window is visible and no popup asking for credentials
3. 

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
I expect to have at least the credentials popup and then Keepass window

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
When Keepass is started no window is visible. On the top bar only the apple is visible, but menu. When I go with the mouse where the menus should be I can the menu topic. What ever the menu position selected to popup or window are visible.

## Context
[NOTE]: # ( Give us any additional information you may have. )
I've a MacBook Pro M3 with 18G of RAM.
Screens are 2 Dell U2410 connected using HDMI plug
Between the MacBook and the screens there a Hyper device (Device HUB 2xHDMI, 1xETH, USB-A and USB-C)  
MacOS Instantview (V3.21 R01) to manage the extend monitor mode. In single screen or recopy mode, Keepass is displying his window correctly ans as expected. Only in extendend mode, it is not opening.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.9
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS 14.6.1

**Comment by droidmonkey** [comment]
This is likely related to some of the bugs macOS introduced to Display Link. Basically they are incorrectly treating this as a remote connection which causes our screenshot security to kick in. There is really nothing we can do about this. 

You can disable screenshot security by following our user guide: https://keepassxc.org/docs/KeePassXC_UserGuide#_screenshot_security

**Comment by chkratzer** [comment]
Thank you
