### ISSUE TITLE
when creating DB, don't make typed password visible

### ISSUE THREAD

**Issue by ChristianS99** [keepassxreboot/keepassxc#11212]
## Summary
When creating a new database, the password prompt by default shows the password and it must be hidden by clicking on eye icon.
Since this is contrary to all other programs I use, it was (for me) very surprising, that the typed password is visible by default.
IMHO, it would be better, not to show typed pw by default, but hide it, and only show it when clicking on eye icon.

## Examples
NA

## Context
It's different from all other programs, where the pw is not visible and only shown, when something is clicked.
Typing pw and seeing it on screen afterwards was very surprising...

**Comment by droidmonkey** [comment]
~~That is definitely not the current behavior. Make sure you are running version 2.7.9~~

**Comment by ChristianS99** [comment]
that's the behaviour with current develop branch:
```
KeePassXC - Version 2.8.0-snapshot
Build-Typ: Snapshot
Revision: 48d0f2b

Qt 5.15.14
Diagnosemodus ist deaktiviert.

Betriebssystem: Gentoo Linux
CPU-Architektur: x86_64
Kernel: linux 6.10.3-gentoo-dist

Aktivierte Erweiterungen:
- Auto-Type

Kryptographische Bibliotheken:
- Botan 3.2.0
```
which i just tried, and previously I tried with 2.7.9:
```
KeePassXC - Version 2.7.9
Revision: 8f6dd13

Qt 5.15.14
Diagnosemodus ist deaktiviert.

Betriebssystem: Gentoo Linux
CPU-Architektur: x86_64
Kernel: linux 6.10.3-gentoo-dist

Aktivierte Erweiterungen:
- Browser-Integration
- Passkeys
- SSH-Agent
- KeeShare
- YubiKey
- Secret-Service-Integration

Kryptographische Bibliotheken:
- Botan 3.2.0
```

both builds have this behaviour. I started both with `--config foo` where foo is not existend, so (I hope) the default config is used to exclude local config changes.

**Comment by droidmonkey** [comment]
My mistake, the password is actually visible by default in the new-password dialog.
