### ISSUE TITLE
Hangs as soon as the database is opened and an entry is clicked on

### ISSUE THREAD

**Issue by MCSmurf** [keepassxreboot/keepassxc#11215]
## Overview
I have installed KeePassXC on two Windows PCs and use different databases.

- On computer A I can open, edit and save all databases 1-3
- On computer B I can open, edit and save databases 2+3
   - but as soon as I open database 1 and either select an entry with a mouse click or search for an entry in the search field, KeePassXC hangs up completely. 
   - In the search window, KeePassXC even hangs after I have entered the first letter.

Database 1 can be opened on computer B with KeePass original without any problems

I have already uninstalled and reinstalled KeePassXC on computer B - without success.
I have also reinstalled the MSVC redistributable package on computer B.

[NOTE]: #
KeePassXC - 2.7.9 on both systems
Revision: 8f6dd13

[NOTE]: #
Operating System: Windows
Windowing System: 
computer A -> Win11
computer  B -> Win10 Pro

**Comment by droidmonkey** [comment]
Something like this has been reported several times. Unfortunately, without reproducible steps there is absolutely nothing we can do to fix it without stumbling onto the potential problem. Check your Database 1 for recursive references (Entry A references Entry B that references Entry A). 

Here is a search of related issues: https://github.com/keepassxreboot/keepassxc/issues?q=sort%3Aupdated-desc+is%3Aissue+hang+open
