### ISSUE TITLE
Repository

### ISSUE THREAD

**Issue by Philippe734** [keepassxreboot/keepassxc#1121]
Please, provide KeepassXC in the Ubuntu repository, or Debian repository, or at least through a PPA on Launchpad. This flavor of Keepass is the only one to be native app and often up to date release for Linux.

**Comment by TheZ3ro** [comment]
There are unofficial .deb package and an unofficial PPA.

We are testing our official PPA that will be available soon

For Ubuntu/Debian repository, it's up to them.

**Comment by phoerious** [comment]
A package has been submitted to Debian, but seems to be in review still.
As @TheZ3ro said, we are building a PPA right now. You can already try it if you want: https://launchpad.net/~phoerious/+archive/ubuntu/keepassxc
Note that right now YubiKey does not work on Trusty.

**Comment by magkopian** [comment]
@phoerious I see that a reference about the official PPA has already been added on the website of the project, does that mean that the PPA is now ready? I'm asking because I'd like to reference it as the currently recommended way of installing KeePassXC for Ubuntu on my README.

**Comment by phoerious** [comment]
Yes, it's ready.

**Comment by Philippe734** [comment]
The release from this ppa works fine on my Ubuntu 14.04 ! Thanks a lot !

**Comment by AzureRaptor** [comment]
I also want to express my appreciation for this PPA.  While yes, there is a .deb, and yes, one can subscribe to email updates to receive notifications when it is updated, that's really quite inconvenient and backward; whereas an apt-get update etc. script runs on my box as a cron job.  So this is really wonderful for me, and I strongly suspect it's a boon for a great many others as well.  Thank you very much.

**Comment by phoerious** [comment]
The Trusty build now also ships current versions of libyubikey and libykpers-1, so that Yubikeys work as well.

**Comment by vdcbb** [comment]
Can we expect KeePassXC to be included in Ubuntu 18.04 repository? There's little chance of me using it if it's not in the official repo.

**Comment by phoerious** [comment]
It's in Debian testing. Import Freeze for Bionic is in March, so possibly yes.

**Comment by udopt** [comment]
This suggests that KeePassXC will be in Ubuntu 18.04: https://packages.ubuntu.com/bionic/keepassxc

**Comment by phoerious** [comment]
Yes, it's been there for a while.
