### ISSUE TITLE
Please add a regular match to the url or extend the recognition of the *.

### ISSUE THREAD

**Issue by SwartzBushnell** [keepassxreboot/keepassxc#11219]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )

I've searched Issues and there's nothing related to regular matching, but there's something about matching with *, so I'm guessing if regular matching is harder to implement? Then please consider expanding the scope of * matches

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )
For example, the website comic*. * matches comic123.com or comic.org or comic-123-abc.com
![image](https://github.com/user-attachments/assets/1df03d01-b2b4-4a75-86e2-6b99a702e74f)

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )

Some sites provide unblocked URLs for users in regions/countries with strict web censorship and automatically update new URLs according to the rules after detecting that the previous URL has been blocked.

**Comment by droidmonkey** [comment]
Duplicate request

https://github.com/keepassxreboot/keepassxc/pull/9835

**Comment by SwartzBushnell** [comment]
I've read https://github.com/keepassxreboot/keepassxc/pull/9835  so are you saying that I have to download the original branch and compile it myself, or wait for the 2.8 release version to get to where I want to be?


Thanks for all the work you guys put in.

**Comment by droidmonkey** [comment]
Once we merge it, you can run a snapshot build
