### ISSUE TITLE
KeepassXC browser plugin does not work properly on macOS Intel

### ISSUE THREAD

**Issue by vkuznet** [keepassxreboot/keepassxc#11227]
## Overview
Starting 2.7.9 upgrade the KeePassXC browser plugin (tried Chrome and FIrefox) does not work properly on macOS Intel (but it works correctly on ARM macs).

## Steps to Reproduce
When using a browser plugin first time we need to connect to a database.
1.  Connect to a database (you'll be prompt to give new session name)
2. Visit some site and it will properly find Login/Password for it
3. After some period of time visit another site (sometimes on 2,3, and so on) and plugin will stop working.

I found that if I open browser keepass settings page and visit "Connected databases" I still see proper entry for itentifier and so on. Deleting this entry and hitting connect button again restore the functionality.

I tried multiple browsers, e.g. Chrome, Brave, Firefox, and I can confirm that the behavior remain across all of them. Moreover, I tested it with another laptop which has ARM chip and it is not an issue. But on Intel laptop it is present and persistent. The re-installing keepass, and its plugins does not solve the problem. And, as far as I can tell the issue starts appearing only on recent release(s), the current one we're using is 2.7.9

## Expected Behavior
Keepass should keep proper connection to a database.

## Actual Behavior
After some period of time (seems like some cache expiration) I see that plugin stop working on Intel based macs. It is not the case of ARM based macs. Such behavior is consistent across browsers and after re-installation of keepassXC and its plugins. The only solution is visit plugin page and manually delete existing record. Then connect to a database again. After connection is re-established it starts working again but then after some period of time it will lost it.

## Context
The behavior start appearing after recent upgrade, mostly likely to 2.7.9, but I'm not 100% sure if 2.7.8 was working since I only noticed it recently (after the upgrade).

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS
Desktop Env: macOS Intel
Windowing System: macOS

**Comment by droidmonkey** [comment]
Can you provide more specific reproduction criteria? How long before it stops working? Are there any console log messages in the browser? Does the "reload" button appear in the extension popup? Is your system doing a periodic clean of the temporary files folder where the connection socket is placed?

**Comment by varjolintu** [comment]
Downgrading to 2.7.8 makes it work again?

**Comment by schulm** [comment]
Just had the same issue on my m1 mac after a chrome update, I reinstalled the plugin, didn't worked, then I restarted chrome and got it working.

**Comment by vkuznet** [comment]
> Can you provide more specific reproduction criteria? How long before it stops working? Are there any console log messages in the browser? Does the "reload" button appear in the extension popup? Is your system doing a periodic clean of the temporary files folder where the connection socket is placed?

The issue appears after visiting 2-3 sites where login credentials are required. It is not related to time but rather to number of sites. The reload button appears just fine. There is nothing special about macOS, it performs its regular tasks based on OS settings. The console logging in browser does not reveal anything specific.

That said, I followed @schulm suggestion and restarted the browser (for sanity purpose I also rebooted the computer) and it seems the issue disappear. My conclusion is that there were some caching content within browser (plugin) which was cleaned up.

I gave a system a shot at different time, i.e. I tried several times after few hours of inactivity of KeePassXC and checked at least dozens of sites. Now everything seems to be working. Therefore, I'll close the ticket and if issue will pop-up again I'll re-open a ticket with new findings.

Thanks everyone for suggestions.
