### ISSUE TITLE
lates version 2.7.9 doesn't run on latest Win 11 

### ISSUE THREAD

**Issue by kemoc** [keepassxreboot/keepassxc#11228]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )

[NOTE]: # ( Give a BRIEF summary about your problem )
Application doesn't start, nothing after double click on the icon, even when App was removed and installed again

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Install App and run after installation or double click on the App
2. 
3. 

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Opened App window

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
nothing happen when open the App

## Context
[NOTE]: # ( Give us any additional information you may have. )
windows 11 with all updates (up to updates 2024.08), Lenovo Laptop Legion 7 2023 year,  CPU Intel mobile, Graphics Nvidia geforce RTX Mobile. I had to back to KeePassXC version 2.7.7 (2.7.8 not tested by me)

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.9
Revision: REVISION - latest downloaded from official site

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 11
Desktop Env: --
Windowing -- Windows explorer

**Comment by kemoc** [comment]
Windows version 23H2

**Comment by droidmonkey** [comment]
You need to install MSVC Redistributable... https://aka.ms/vs/17/release/vc_redist.x64.exe
