### ISSUE TITLE
Allow search for passwd

### ISSUE THREAD

**Issue by digimeas** [keepassxreboot/keepassxc#11226]
Hi! I like KeePassXC! Thanks

When informed of a data breach, email/passwd are reported but not always the site that was breached

I have a LOT of entries using my email, but can't search for the (unique, gobbledygook) passwd to figure out which site matches

Thanks and good luck
Doug

**Comment by droidmonkey** [comment]
https://keepassxc.org/docs/KeePassXC_UserGuide#_searching_the_database

**Comment by digimeas** [comment]
Should have known .Thank you!
