### ISSUE TITLE
Password practising feature

### ISSUE THREAD

**Issue by Nofficial24** [keepassxreboot/keepassxc#11225]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
It is about a practicing function for passwords to no forget them.

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )
Three new fields in the main page of an entry:
- a tick box for opting in this feature; it enables the next field
- a dropdown box for chosing an intervall, "sporadically" or "regulary"
- a dropdown for chosing an interval with options depending what was chosen above:
  - regulary: "every 30 minutes", "every 1 hour", "every 4 hours"
  - sporadically: "one a day", "one a week", "once a month"

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
Dear development team,

this request is about a feature that may seem absurd in the first place but could make sense in the every-day-use of KeePassXC.

It is about a practicing function for passwords to no forget them.

There are a few passwords in our life that we cannot easily copy-paste or read from the db - at least not in every situation - like the user authentication on a local OS for example, when the db is not available.
This may be a secondary device that is not used very often, much less than the one with the KeePass db for example.
Or think of a company user that was forced by policy to change that password. He or she could let KeePassXC ask for the password every 30 minutes on the first days.

It would be cool if one could configure specific entries on the database to sporadically or regulary ask for passwords while KeePassXC is running.

I was inspired by a function of the signal messenger that regulary asks the user for the encryption PIN for the same reason (and it is very effective).

But I know that this feature is not a top-priority thing because password managers are mainly a thing for copy-pasting secrets. Nevertheless, I think KeePassXC would be the right place for this because KPXC stores the information that is necessary for doing it.
And, as the term "password manager" says, it is about managing passwords and therefore perhaps also about not forgetting them.

Whether you are going to implement this or not, I want to thank you for your great work on KeePassXC!

**Comment by michaelk83** [comment]
> when the db is not available

What I do is I sync my DB to Google drive, so I can always access it from my phone, and look up any password that I need that can't be entered automatically. Then all I need to remember is the DB main passphrase, which you'll still need to remember anyway with this feature (plus my phone password, which I use all the time, so no issue there for me).

Strong random passwords are impossible to memorize anyway. If you need to remember a password, then if possible, you should use a pass*phrase* instead.

**Comment by Nofficial24** [comment]
Hello Michael,

thank you for you opinion to my request.

If one has the possibility to sync the db (which is someting that I do too) you are right. But there are cases where the user cannot do this (company restrictions, less technical affine people, ...). My secondary device argument was not the best example. And yes, there are lots of possibilities to manage the availability of the database.

But my request is more about training those passwords or passphrases (which one perhaps does not remember exactly and thus important ones should be trained to) that you rarely type but you really want to know on a longer term (muscular memory).
Or those you have renewed and the training function should help you to memorize them faster.

Like most things it is a matter of opinion if some passwords or secrets should generally be memorized and if a password manager like KeePassXC is the right tool to help you manage this. Personally I would answer to both points with yes. But of course it depends on the developers opinion.

**Comment by droidmonkey** [comment]
Hello there, thank you for the suggestion and praise for the application. Unfortunately, we find this suggestion to be outside the scope of our program and the antithesis of our design goals. The point of using KeePassXC is to _not remember_ your passwords. By including a feature that helps you remember them, that defeats our purpose. This also would be a rather annoying, self opt-in, feature that I do not foresee being popular at all. The time to code this, test it, and keep it maintained is not worth the potential number of users who would find it useful.

What I recommend is to use passphrases, perhaps with a mnemonic pattern, so you can memorize more readily. For passwords that _must be memorized_ outside of KeePassXC, you can also use a hardware device like a yubikey to setup a typing of that password. You can also write it down and store it in a secure location in case you forget.
