### ISSUE TITLE
Regression AppImage KeePassXC-2.2.2-2-x86_64 no desktop integration

### ISSUE THREAD

**Issue by mauron85** [keepassxreboot/keepassxc#1122]
It seems that KeePassXC-2.2.2-2-x86_64.AppImage doesn't offer to integrate into system as previous version KeePassXC-2.2.1-x86_64.AppImage.

## Expected Behavior
When AppImage is executed (usually for first time or until `KeePassXC_no_desktopintegration` file is not present in user home directory)

![image](https://user-images.githubusercontent.com/359450/31993074-6452e0da-b97c-11e7-8c47-b7a06b1df1ac.png)

## Current Behavior
This is dialog is not present in KeePassXC-2.2.1-x86_64.AppImage anymore.

## Debug Info

KeePassXC - 2.2.2
Revision: 2

Operating system: Ubuntu 16.04
CPU architecture: x64
Kernel: 4.10.0-37-generic

Enabled extensions:
- not relevant

**Comment by phoerious** [comment]
This is already fixed, and will be back in 2.2.3.
