### ISSUE TITLE
Unlock database visual bug that lasts for 1 second

### ISSUE THREAD

**Issue by GaucovyAero** [keepassxreboot/keepassxc#11235]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
When starting KeePassXC, the password prompt seems to visually duplicate itself like 3 times, then the duplicates disappear.

![image](https://github.com/user-attachments/assets/a5de6499-9e76-4233-b148-a282aa1bc761)

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Open KeePassXC and look carefully.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
The password prompt should not have any visual bugs no matter what time they last.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
If I first start up KeePassXC, or put it into a the scratchpad and grab it back or change workspaces and change back, the password prompt seems to duplicate itself like 3 times and after 1 second, the duplicates disappear.

## Context
[NOTE]: # ( Give us any additional information you may have. )
This issue is not specific to Wayland or using a tiling WM/WC

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.9
Revision: 8f6dd13

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env (Wayland compositor): Sway, TTY login
Windowing System: Wayland

**Comment by droidmonkey** [comment]
It's the indicator showing we are looking for hardware keys

**Comment by GaucovyAero** [comment]
please consider redesigning it, but thanks for the info, it makes a lot more sense now
