### ISSUE TITLE
Copy shortcuts (CTRL+B, C, T, U) not working when the menubar AND the toolbar are hidden

### ISSUE THREAD

**Issue by Jilano** [keepassxreboot/keepassxc#11237]
## Overview
When the menubar and the toolbar are hidden at the same time, all the copy shortcuts (CTRL + B, C, T, U, etc.) do not work.
****

## Steps to Reproduce
1. Click on View
2. Untick **Show Menubar**
3. Untick **Show Toolbar**
4. Click on an entry
5. Press CTRL + B for example

## Expected Behavior
The desired data (username, password, URL, etc.) should be in the clipboard, and an indicator should appear at the bottom right corner of the window with the remaining time before said clipboard is cleared.

## Actual Behavior
When the menubar and the toolbar are not displayed, nothing happen. Whatever was left copied inside the clipboard will appear, but nothing from the selected entry in KeepassXC.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.9
Revision: 8f6dd13

Qt 5.15.11
Debugging mode is disabled.

Operating system: Windows 10 LTSC Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.19044

**Comment by droidmonkey** [comment]
That is "by design" with qt, there is nothing we can do about it. When the action is hidden (toolbar button, menu bar) then it won't get triggered. Hiding those elements essentially says "I'm not using it"
