### ISSUE TITLE
[Remote Sync] Hardcoded wait timeout does not allow enough time

### ISSUE THREAD

**Issue by ItsOnlyBinary** [keepassxreboot/keepassxc#11234]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )

The remote sync code has a hard coded 10 second wait time before killing the process. This is not long enough when the command is talking to a slower server which is performing multiple steps (protocol negotiation + database lookups + response time)

Please expose a configuration option for waitForFinished [here](https://github.com/keepassxreboot/keepassxc/blob/c8fc25ea5cef255816c1316e0e4810cc64d50e6e/src/gui/remote/RemoteHandler.cpp#L70) and [here](https://github.com/keepassxreboot/keepassxc/blob/c8fc25ea5cef255816c1316e0e4810cc64d50e6e/src/gui/remote/RemoteHandler.cpp#L121)

With this increased it is possible to sync with NextCloud using curl.

> As a side note wishlist, it would be really nice if there was options to auto sync at login and save. (so I don't forget to sync)

@t-h-e You have my thanks and appreciation for adding the one feature, holding me back from switching over. :)

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )

Example commands for syncing with NextCloud using a directory shared with a password:

download:
```
curl --silent --user SHARE_ID:SHARE_PASSWORD -H "X-Requested-With: XMLHttpRequests" -H "X-Method-Override: GET" --output {TEMP_DATABASE} https://cloud.example.com/public.php/webdav/Example.kdbx
```

upload: 
```
curl --silent --user SHARE_ID:SHARE_PASSWORD -H "X-Requested-With: XMLHttpRequests" -H "X-Method-Override: PUT" --upload-file {TEMP_DATABASE} https://cloud.example.com/public.php/webdav/Example.kdbx
```

**Comment by t-h-e** [comment]
I already knew that a hardcoded timeout is not a good idea 😅
I'm going to make it configurable, but don't expect any progress before end of October due to other obligations.

**Comment by ItsOnlyBinary** [comment]
:) no rush for me, I managed to build it with hardcoded 60 seconds (was a fun journey as it seems the docs for windows are a little outdated). Unfortunately I do not know c++ enough to actually create a pr to add the option.
