### ISSUE TITLE
v2.7.9 - Shortcut key for Hide Passwords still not implemented

### ISSUE THREAD

**Issue by Lysrin** [keepassxreboot/keepassxc#11233]
## Overview
In the View menu there is the option to Hide Usernames (Ctrl+Shift+B) and Hide Passwords (Ctrl+Shift+C). The shortcut key combo for Hide Usernames works as expected. The one for Hide Passwords does nothing. This has been missing in several versions at this point.

## Steps to Reproduce
1. Press the Ctrl+Shift+C shortcut key combo.
2. Nothing happens - Passwords remain in their current state, either hidden or displayed.

## Expected Behavior
Pressing Ctrl+Shift+C should toggle between hiding passwords and showing passwords, functioning the same as the shortcut key combo for Hide Usernames.

## Actual Behavior
Pressing the Ctrl+Shift+C has no effect.

## Context
Clicking the View -> Hide Passwords menu options with the mouse works as expected. So the functionality is implemented, just not the indicated shortcut key combo.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.9

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows
Desktop Env: N/A
Windowing System: N/A

**Comment by droidmonkey** [comment]
https://github.com/keepassxreboot/keepassxc/blob/c8fc25ea5cef255816c1316e0e4810cc64d50e6e/src/gui/MainWindow.ui#L1318

Not sure why it wouldn't be working

**Comment by xboxones1** [comment]
It works for me. 
Tested on Linux and Windows

![shortcut](https://github.com/user-attachments/assets/03b22a5d-40a4-4c7a-a381-80c59acb9f41)

**Comment by Lysrin** [comment]
@xboxones1 Really? Okay then. Weird. I've tried upgrades and fresh installs. And the username one works fine for me. Curious. Thanks for testing. Clearly something weird on my end if others cannot reproduce the behaviour.

**Comment by droidmonkey** [comment]
A clipboard manager program may be intercepting it as a global hotkey. Or screencaptue software.  Just shooting in the dark.

**Comment by Lysrin** [comment]
Well, I don't have anything different installed on Windows 11. And the username one works fine, so it's odd for sure. I'll poke around though and see if there's anything I can find to explain it.

Nice to know I'm "special" :)
