### ISSUE TITLE
Fedora 40 - cannot connect database on Brave/Firefox (flatpak/flathub)

### ISSUE THREAD

**Issue by SynapseScribe** [keepassxreboot/keepassxc#11236]
## Overview
Cannot link keepassxc with brave or firefox downloaded from gnome software store (via flatpak from flathub)

## Steps to Reproduce
install brave or firefox
install extension  keepassXC-browser 1.9.3
attempt connect via reload button in extension or via connect button in extension settings (under connected databases)
nothing happens

## Expected Behavior
db connects to browser

## Actual Behavior
nothing happens

## Context
in keepassxc, browser integration is enabled and checked for: chrome, chromium, brave and firefox

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.9
Revision: 8f6dd13
Distribution: Flatpak
Qt 5.15.14

[NOTE]: # ( Pick choices based on your environment )
Operating system: Fedora Linux 40 (Forty)
CPU architecture: x86_64
Kernel: linux 6.10.6-200.fc40.x86_64
Desktop Env: Gnome
Windowing System: Wayland

**Comment by droidmonkey** [comment]
Follow the browser extension troubleshooting guide please. Could be many reasons, all of them related to crazy Linux.

**Comment by SynapseScribe** [comment]
it's out of the box fedora.. why close though

**Comment by droidmonkey** [comment]
https://github.com/keepassxreboot/keepassxc-browser/wiki/Troubleshooting-guide

You likely need to adjust the app armor settings which is covered in the troubleshooting guide start there

**Comment by SynapseScribe** [comment]
fedora doesn't have apparmor

**Comment by droidmonkey** [comment]
Just FYI, I tested this in Fedora 40 with Firefox and it worked fine. I did have to "Refresh my browser" which basically reset my profile, reinstalled the extension, and it worked great.

**Comment by SynapseScribe** [comment]
thank you for testing it on your side as well. did you have rpm or flatpak firefox or other kind of installation?

**Comment by droidmonkey** [comment]
RPM, flatpak Firefox won't work

**Comment by SynapseScribe** [comment]
yes, the issue i opened is for flatpak. so does this mean it will never work for flatpak? the common user installs browser from gnome store which in case of brave for example, falls to flatpak. is there any plan to support flatpak versions in the future as well?

**Comment by droidmonkey** [comment]
Not our call, that is up to flatpak devs and mozilla
