### ISSUE TITLE
Allow Screen Capture

### ISSUE THREAD

**Issue by Saydix** [keepassxreboot/keepassxc#11230]
## Overview
The "allow screen capture" button does not save its state after restarting the application. This makes it very difficult when using NVIDIA shadowplay/instant replay

## Steps to Reproduce
1. Turn on allow screenshots
2. Restart keepassXc app
3. 

## Expected Behavior
I would like this feature not to turn off when restarting the application. Or there was a button in the settings to enable the "allow screenshots" state forever

## Actual Behavior
-

## Context
-

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.9
Revision: 8f6dd13

Qt 5.15.11
Debugging mode is disabled.

Operating system: Windows 10 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.19045

Enabled extensions:
- Auto-Type
- Browser Integration
- Passkeys
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 3.1.1

**Comment by Saydix** [comment]
I've found some issues related to my "problem", but it doesn't seem to be a bug :(
But is there a way to change the behavior of this state? So that I can allow recording forever? 
Or perhaps this can be done without stopping the recording, by closing/hide the window from the recorder, in any case, so that the recording does not stop
Or does it reduce the security of using the manager?

**Comment by varjolintu** [comment]
Start KeePassXC with `--allow-screencapture`.

**Comment by Digioso** [comment]
I'd like to re-open this. Why not make the choice permanent?
I enabled the "Start KeepassXC with my PC" option. There's no way to add parameters.

**Comment by droidmonkey** [comment]
This is a security design choice we have made, there are already work arounds. You can create a shortcut to launch with parameters instead of launching at startup if that's what you need. You can also manually edit the startup script / registry entry if you desire.

**Comment by fapable** [comment]
Hello, what would be the workaround on macos?

Also I find it to be a very limiting thought process to, just because there is a workaround that works for some people, to close the issue. I, too, would like to see an option within the settings of the application to allow screen recording. This will make the app more usable for more people, compared to having to edit the startup script/registry.

**Comment by droidmonkey** [comment]
You have a couple of options if you launch keepassxc from the dock, although we don't recommend modifying the app package. You can also just create a launch script that you open from your desktop. Lastly, in all technicality the app isn't inaccessible, you can maneuver to the top menu bar and click to access the menus and find the view menu and then allow screencapture. 

https://superuser.com/a/271697
