### ISSUE TITLE
Entered password isn't cleared when the screen is locked

### ISSUE THREAD

**Issue by savchenko** [keepassxreboot/keepassxc#11243]
## Overview
When user enters their password and does _not_ unlock the database, the password field is not cleared after the screen is locked.

## Steps to Reproduce
1. Enter something in the password field:
   ![image](https://github.com/user-attachments/assets/38335407-b66c-474c-bfa7-407c5e4c43d5)
3. Lock the screen
4. Unlock the screen

## Expected Behavior
The field is cleared.

## Actual Behavior
The field stays as-is.

## Context
If we are locking database with the screen lock, it would make sense to clear any typed passwords as well. Probably applies to the passwords in the clipboard as well.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.4
Revision: 63b2394

Qt 5.15.8
Debugging mode is disabled.

Operating system: Debian GNU/Linux 12 (bookworm)
CPU architecture: x86_64
Kernel: linux 6.1.0-25-amd64

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.19.3

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: KDE
Windowing System: Wayland

**Comment by droidmonkey** [comment]
Update to 2.7.9
