### ISSUE TITLE
How can i change my master passworrd? Idiot-safe and very precisly instructions are very welcome, 

### ISSUE THREAD

**Issue by GameGourmet** [keepassxreboot/keepassxc#11244]
Ubuntu 22.04

**Comment by droidmonkey** [comment]
Database Menu -> Database Security

**Comment by GameGourmet** [comment]
Thank you very much.
I researched a lot in google,  followed  many sites, many FAQ,  but there was none solutiion to my question.

Thank you very much.

**Comment by GameGourmet** [comment]
problem solved. topic can be closed.

**Comment by droidmonkey** [comment]
We have a rather robust user guide... https://keepassxc.org/docs/KeePassXC_UserGuide#_database_settings

**Comment by GameGourmet** [comment]
looks interesting, but i prefer to spend my time with other things.
Kepassxc was already hard enough to install.
Especially making it work with my web-browser.
 
My initial question  should be  part of an FAQ in my opinion.

Anyway, thank you very much.
