### ISSUE TITLE
qwindows.dll missing from portable release 2.7.9

### ISSUE THREAD

**Issue by UniTrader** [keepassxreboot/keepassxc#11241]
## Overview
As stated in the Title. i have just put the portable Version of Keepassxc 2.7.9 on my Password USB Key, and when i tested it i couldnt launch it, because "qt platform plugin was not found"

## Steps to Reproduce
1.  extract KeePassXC-2.7.9-Win64.zip onto USB Stick
2.  Launch it from USB (Tested on an almost-fresh virtual system with almost nothing installed)

## Expected Behavior
Starts without error

## Actual Behavior
It will Exit with stated error message

## Context
I could fix this for myself by downloading KeePassXC-2.7.0-Win64.zip and putting the qwindows.dll from there into the same folder in the newer release.

[NOTE]: # ( Paste debug info from Help → About here )
(Copied from launching after using my workaround)

KeePassXC - Version 2.7.9
Revision: 8f6dd13

Qt 5.15.11
Debugging mode is disabled.

Operating system: Windows 11 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.22621

Enabled extensions:
- Auto-Type
- Browser Integration
- Passkeys
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 3.1.1

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 11

**Comment by droidmonkey** [comment]
Ummm nope and easily disproved, count your kids again please

![image](https://github.com/user-attachments/assets/2feed76e-31b3-485c-b8bc-5fe00ac27966)
