### ISSUE TITLE
Auto-Type under Windows 11 not able to type into newly opened window

### ISSUE THREAD

**Issue by gitflo** [keepassxreboot/keepassxc#11248]
## Overview
Auto-Type is not able to type into a window that opened after an Auto-Type sequence has started.

## Steps to Reproduce
Example sequence: #r{DELAY 1000}cmd.exe

## Expected Behavior
Run window opens, and after 1 second, Keepass will type cmd.exe into it.

## Actual Behavior
Run window opens, and that was it.

## Context
KeePassXC 2.7.9
Operating System: Windows 11
Tested on:
Windows 11 Enterprise 22H2 Build 22621.4037
Windows 11 Enterprise 23H2 Build 22631.4037

This used to work like a charm (and still works) on Windows 10, but on Windows 11, the Run window opens, but nothing will be typed.

If you open the Run window manually, a triggered Auto-Type sequence will type in its text there – unless that sequence would result in another new window opening.

**Comment by droidmonkey** [comment]
This is by design and won't be changed. Auto-type detects if the focused window title changes. You cannot use auto-type across multiple windows.
