### ISSUE TITLE
Password sharing between entries

### ISSUE THREAD

**Issue by Massimo-B** [keepassxreboot/keepassxc#11251]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
2 entries with different URL and different username should share the same password.

## Context
[NOTE]: # ( Show us a picture or mock-up of your proposal )
I have an entry with a big single-sign-on username/password `foobar@localnet/mypassword`, used for many URLs. But one misconfigured server requires a different username without the `@localnet`, just `foobar`, but sharing the same password.

Currently with KeePassXC - Version 2.7.9 I need to have 2 separate entries with the same password. Is it possible to share the password somehow? Because every forced password change (due to dubious password policies) needs to update both entries.

**Comment by droidmonkey** [comment]
Use field reference: https://keepassxc.org/docs/KeePassXC_UserGuide#_entry_cross_reference

To make it easy, start with cloning the main entry then adjusting from there: https://keepassxc.org/docs/KeePassXC_UserGuide#_clone_an_entry

**Comment by Massimo-B** [comment]
Great. Is that XC-specific or Keepass-compatible, when working with different clients such as Keepass2Android?

**Comment by droidmonkey** [comment]
Keepass compatible

**Comment by Massimo-B** [comment]
I just tried in KeepassXC and can't get it working. In a new entry I have set as password:
`{REF:P@T:single}`
OR also via UUID:
`{REF:P@U:6d1d5b5459c646a3af2bbcc1652260c1}`

The referenced entry has the title "Foobar.de Domain Single Sign On". But the new entry doesn't get a password from the reference. In the Password column I see `Ref:` and I tried Contextmenu->Copy Password
But nothing gets copied.

**Comment by droidmonkey** [comment]
Use the clone feature and check the box for references. 

UUID would be: `{REF:P@I:......}`

You used `@U`

**Comment by Massimo-B** [comment]
I see. Thanks.
`{REF:P@I:6d1d5b5459c646a3af2bbcc1652260c1} ` works
`{REF:P@T:Foobar.de Domain Single Sign On}` works
`{REF:P@T:Single}` does not work
`{REF:P@T:*Single*}` does not work
Ok, the title must be complete, no pattern. From <SEARCH_IN> I thought of searching for a substring...

Works now for me.
