### ISSUE TITLE
Database display error.

### ISSUE THREAD

**Issue by kjmxgyq** [keepassxreboot/keepassxc#11254]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem. )
When I turn on KeepassXC, the database appears blank.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. The first thing I used to do when I started my laptop was to open KeeePass XC and let it reside in the background. My database address is located on a cloud synchronized web disk.
2. After I typed in the password, the database went blank.
3. I used Task Manager to end it from the background, then reopened the database and still nothing. It may resume after occasional restarts

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
The contents stored in the database are displayed normally

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
The database content is not displayed properly

## Context
[NOTE]: # ( Give us any additional information you may have. )
Is it because of the network proxy

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC -2.7.9
Revision:8f6dd13

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows
Desktop Env: Cinnamon
Windowing System: X11

**Comment by droidmonkey** [comment]
https://github.com/keepassxreboot/keepassxc/issues/10927#issuecomment-2180333104
