### ISSUE TITLE
More Advanced Database Merging

### ISSUE THREAD

**Issue by Qwerty-Space** [keepassxreboot/keepassxc#11256]
## Summary
I think it would be invaluable to see the results of a database merge in the GUI app before committing to it.

## Examples
Forgive me for not providing a picture, but I'll describe it as best I can.

After selecting the merge option and entering the db password, a window appears with a list of entries colour coded red for delete, orange for overwrite, green for new.  There could even be a column in the list to show delete, overwrite, new. etc.

Alternatively, it could show two columns similar to GitHub's diff view.

In this merge window, we should be able to select entries to exclude from the merge, for example if the information for a specific entry is incorrect in the database you're merging from, but ither enrtries are correct.

For each entry you can double click to open it to see the difference between both databases.  This will also show what elements of the entry will be updated, or removed.  Perhaps these attributes can be excluded as well.

## Context
There have been at multiple occasions where I've had a sync conflict, and ended up losing a TOTP code or a new password due to the merges.  Even with the more verbose information of the cli utility, it's not clear exactly what the difference is.  

Fortunately, in most of these cases I've had multiple backups per device (thank you syncthing), but it's still frustrating to try to resolve when I can't see an detailed diff of the two databases.

If you have anymore questions, please do ask!  I'm sorry if this is a duplicate.

**Comment by droidmonkey** [comment]
https://github.com/keepassxreboot/keepassxc/pull/10173

In the works 

Regarding "losing" information, a merge pushes the original data into the entry history as long as you have history enabled for the database. You can always restore or view that history item.

**Comment by Qwerty-Space** [comment]
> #10173
> 
> In the works
> 
> Regarding "losing" information, a merge pushes the original data into the entry history as long as you have history enabled for the database. You can always restore or view that history item.

Thanks for the info!
