### ISSUE TITLE
Cannot open URLs and attachments from AppImage in Linux

### ISSUE THREAD

**Issue by nohing** [keepassxreboot/keepassxc#11250]
## Overview
Again, in Linux, with this new version 2.7.9, the opening of URL's and attachments from AppImage is not working. And even if you click on "Report a Bug", it does not work.
We, Linux users, still have to use the old version 2.7.1 because is the only one that works.
Why does 2.7.1 work and the others do not?
Please, please, can you solve this problem? 
Is it possible that there is no one, among all the people who collaborate on the KeePassXC project, capable of solving this problem?

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. 
2. 
3. 

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.9
Revision: 8f6dd13
Distribution: AppImage

Qt 5.15.2
Debugging mode is disabled.

Operating system: Linux Mint 21.3
CPU architecture: x86_64
Kernel: linux 5.15.0-119-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- Passkeys
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.19.1

**Comment by droidmonkey** [comment]
Please stop reporting this issue over and over again. Use Flatpak and you'll be much happier.

![image](https://github.com/user-attachments/assets/59e49063-5c92-4551-8296-f535793a735e)

**Comment by droidmonkey** [comment]
A fix was attempted in #10624, but you need to have xdg-open installed on your system.

https://github.com/keepassxreboot/keepassxc/pull/10624/files
