### ISSUE TITLE
Lost dark mode

### ISSUE THREAD

**Issue by torx-bit** [keepassxreboot/keepassxc#11258]
Keepassxc went from  dark mode to a  white background with no input or changes by me. 
No other programs were affected.

KeePassXC - Version 2.4.3
Revision: 5d6ef0c

OS: Linux Mint XFCE

**Comment by droidmonkey** [comment]
2.4.3 is an extremely old version. Update or change the theme in the application settings

**Comment by torx-bit** [comment]
Thanks, It resolved itself.  No more "strange behavior".  Will upgrade tho.
