### ISSUE TITLE
[Feature Request] expediate search method

### ISSUE THREAD

**Issue by bigalgeorge** [keepassxreboot/keepassxc#1125]
Mainform Search + Open URL is the most important function and current shortcut Open URL is a tad too long.
EG Search brings up a list of results which _then_ requires highlighting, _then_ Ctrl+U
The following method shortens method:
Tools/Settings/General/Basic Settings "[x] Enter or Double-Click =  Open URL" (of highlighted entry instead/as well as Ctrl-U In application mainform)

KeePassXC - 2.2.2
Revision: REVISION

Operating system: Debian/Linux Mint
CPU architecture: ARCH
Kernel: KERNEL

**Comment by phoerious** [comment]
I'm not entirely certain that I understand what it is you want. You can already double click the URL field to open it.

**Comment by bigalgeorge** [comment]
Perfect; regret omission on my behalf.

**Comment by droidmonkey** [comment]
There is no need to add the [feature request] to title. That's what labels are for.

**Comment by bigalgeorge** [comment]
Actually, to make the Search method even better would be (current action) as you type in the Search Field a list of found items rolls up as the filter increases. EG say you type 2 letters there may be several found items in the list, but by the time you've typed 4 letters the top item in list thats highlighted will be the one you want. (desired action) At that stage in the search box user _can press [enter] and it goes to selected list url_

**Comment by droidmonkey** [comment]
Closing in favor of #1317
