### ISSUE TITLE
App doesn't start minimized in KDE Plasma

### ISSUE THREAD

**Issue by DavutHaxor** [keepassxreboot/keepassxc#11259]
## Overview

App doesn't start minimized since a week or so.

## Steps to Reproduce
1. Boot the computer.
2. Wait for KeepassXC to appear

## Expected Behavior
It should start minimized

## Actual Behavior
It doesn't start minimized

Debug info: https://gist.githubusercontent.com/DavutHaxor/f4c7ea9f190f5fba235e782829a9f04f/raw/6aa0a3f05927ad49722719693d648ebf6009f4aa/debug%2520info%2520keepassxc
KeePassXC - 2.7.9
Revision: 8f6dd13

Operating System: Linux
Desktop Env: KDE
Windowing System: Wayland

**Comment by DavutHaxor** [comment]
In addition, keepassxc config in ~/.config/keepassxc is correct. 
![image](https://github.com/user-attachments/assets/14874676-f2f1-4c5d-94d6-e892fa50bd37)

**Comment by droidmonkey** [comment]
> since a week or so

You are likely starting keepassxc twice, the second time will bring the program to the front.  Check your startup sequence.

**Comment by DavutHaxor** [comment]
![image](https://github.com/user-attachments/assets/5383cbca-bdcb-4f5e-b625-6a70fdeddd66)
Well actually there was one entry at autostart and after disabling the in-app settings only 1 instance starts + no entry at autostart at all. Weird.

**Comment by droidmonkey** [comment]
I'd call that _linux weird_ but Windows has five ways to auto start applications as well

**Comment by michaelk83** [comment]
KDE also has its session manager. It will automatically restart on login whatever was running when the previous KDE session was shut down.
