### ISSUE TITLE
Document custom browser option - another try

### ISSUE THREAD

**Issue by kavol** [keepassxreboot/keepassxc#11252]
## Summary
I've already reported this as the issue #10004 - this was closed as resolved but it is not and I do not see an option to reopen it so reporting this as new. What was not fixed - originally speaking about the user guide:

**It does not even mention where to get the browser extension outside the official stores for the selected browsers which don't work with the alternatives, obviously.**

**Comment by varjolintu** [comment]
The [Troubleshooting Guide](https://github.com/keepassxreboot/keepassxc-browser/wiki/Troubleshooting-guide) that's linked to the document already describes this in detail.

The GitHub [releases page](https://github.com/keepassxreboot/keepassxc-browser/releases) has the zip files for Chromium based and Firefox versions, obviously. Loading the extension manually is described in https://github.com/keepassxreboot/keepassxc-browser/wiki/Loading-the-extension-manually

**Comment by kavol** [comment]
> The [Troubleshooting Guide](https://github.com/keepassxreboot/keepassxc-browser/wiki/Troubleshooting-guide) that's linked to the document already describes this in detail.

Please, could you be more specific where exactly this is described within that document?

> The GitHub [releases page](https://github.com/keepassxreboot/keepassxc-browser/releases) has the zip files for Chromium based and Firefox versions, obviously. Loading the extension manually is described in https://github.com/keepassxreboot/keepassxc-browser/wiki/Loading-the-extension-manually

Cool ... then -

1) The method/link to that page is not mentioned in any of these places:

https://keepassxc.org/docs/KeePassXC_GettingStarted#_install_the_browser_extension
https://keepassxc.org/docs/KeePassXC_UserGuide#_install_the_browser_extension
https://github.com/keepassxreboot/keepassxc-browser/wiki/Troubleshooting-guide

2) Why is the page named "loading" while all other documents refer to "install"? How are users looking for "installation" supposed to find this (with generic search, not knowing where to navigate which might be obvious to you but not for others - while I'm reading the README displayed below the code, I haven't even noticed the link "wiki" in the top bar ...)?

3) This doesn't help with other browsers than Firefox and Chrome anyways ...

**Comment by varjolintu** [comment]
> Please, could you be more specific where exactly this is described within that document?
> 

https://github.com/keepassxreboot/keepassxc-browser/wiki/Troubleshooting-guide#find-the-native-messaging-configuration-path-with-strace

The manual installation is out of scope from the normal installation because it's mostly for developers. And the page is labeled as "loading" because that is how temporary extensions are labeled in the browsers. _Load Temporary Add-on_  in Firefox and _Load unpacked_ in Chrome . So technically it's not an install, but a temporary way to load the extension.
