### ISSUE TITLE
Mac - View pane doesn't show folders (only password entries) and doesn't allow to browse between folders

### ISSUE THREAD

**Issue by bassqualle** [keepassxreboot/keepassxc#11268]
## Overview
My database contains a hierarchical folder structure. If I open the database the standard view shows the entries of the last group opened  I believe(or the most top (root). All the groups are missing in the view. It is possible to search for the entries and find them in the search results. But like this, it isn't possible to maintain the database (i.e. move entries between folders, create new folders etc).
On Windows the view shows the passwort entries plus the groups correctly.

## Steps to Reproduce
1.  Start KeePassXC and open the database

## Expected Behavior
View allows to browse existing groups and shows containing password entries

## Actual Behavior
Contained folders are missing in the initial view
View doesn't allow to browse existing groups

[NOTE]: 
Operating System: macOS 11.7.10 BigSur
KeePassXC - 2.7.9 (installed via Homebrew cask)

**Comment by droidmonkey** [comment]
https://github.com/keepassxreboot/keepassxc/issues/10927

**Comment by bassqualle** [comment]
Thanks, highly appreciated. Waiting for release 2.7.10 coming out then.

**Comment by droidmonkey** [comment]
Don't need to wait just do this https://github.com/keepassxreboot/keepassxc/issues/10927#issuecomment-2180333104
