### ISSUE TITLE
Tray symbol shows locked for auto-opend databases

### ISSUE THREAD

**Issue by jo-so** [keepassxreboot/keepassxc#11263]
## Overview

I have a database that references another one in the URL field. This automatically opens the other database when unlocking the first one. But the tray symbol still shows the database is locked.

I have enabled the option »hide window when database unlocked« enabled.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Start KPXC
2. unlock the main database
3. the tray symbol shows the lock, but both databases are unlocked
4. switch to the tab with other database and the symbol becomes green

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

The symbol should reflect the state of the databases.

## Context

```
KeePassXC - Version 2.8.0-snapshot
Build-Typ: Snapshot
Revision: c1a66a8b

Qt 5.15.13
Diagnosemodus ist deaktiviert.

Betriebssystem: Debian GNU/Linux trixie/sid
CPU-Architektur: x86_64
Kernel: linux 6.11-rc5-amd64

Aktivierte Erweiterungen:
- Auto-Type
- Browser-Integration
- SSH-Agent
- Secret-Service-Integration

Kryptographische Bibliotheken:
- Botan 2.19.5
```

Operating System: Linux
Desktop Env: Gnome
Windowing System: Wayland

**Comment by droidmonkey** [comment]
The tray icon will show unlocked if there are any databases unlocked. Does it not show unlocked when your primary database is opened?

**Comment by jo-so** [comment]
No, it doesn't

![grafik](https://github.com/user-attachments/assets/e661f79e-d203-4972-9355-f5430f68e53d)

**Comment by droidmonkey** [comment]
Ummm couple things, I cannot get a tray icon to show up at all on the latest Gnome/Wayland. I also cannot reproduce this on any other operating system. Unfortunately there is nothing we are going to do here, the tray icon code hasn't been touched in years.

**Comment by jo-so** [comment]
At least, Debian ships and Ubuntu installs [gnome-shell-extension-appindicator](https://packages.ubuntu.com/noble/gnome-shell-extension-appindicator) which shows the tray icon.

**Comment by droidmonkey** [comment]
I cannot replicate this using gnome-shell-extension-appindicator.

![image](https://github.com/user-attachments/assets/59418932-1bfa-4d49-8fd3-3bcb1bb2ad1e)
