### ISSUE TITLE
KPXC doesn't remember the »allow access« decision for libsecret (anymore)

### ISSUE THREAD

**Issue by jo-so** [keepassxreboot/keepassxc#11262]
## Overview

Recently, I've upgraded my Ubuntu and got a new keepassxc version: 2.6.6+dfsg.1-1 to 2.7.9+dfsg1-1. (I'm using keepassxc-full). Now, applications using the libsecret storage always bring up the dialogue asking me if I want to allow or decline the access. The »remember« checkbox does not save this decision as it was with 2.6.6.

This behaviour changed with 9a8a5a00063c91f0df556066ad85944bcc369382.

## Steps to Reproduce

1. Build with `-DWITH_XC_FDOSECRETS=ON`
2. Create a database and enable *Secret service integration* in database settings
3. Store a secret with `echo data |secret-tool store --label=lbl attr val`
4. Retrieve the secret `secret-tool lookup attr val` and select the checkbox »remember«
5. Call `secret-tool lookup attr val` and you get prompted again

## Expected Behaviour

The decision should be remembered, because some apps (e.g. chat apps) access the secret very often.

## Actual Behavior

The dialogue comes up every time.

```
KeePassXC - Version 2.8.0-snapshot
Build-Typ: Snapshot
Revision: c1a66a8b

Qt 5.15.13
Diagnosemodus ist deaktiviert.

Betriebssystem: Debian GNU/Linux trixie/sid
CPU-Architektur: x86_64
Kernel: linux 6.11-rc5-amd64

Aktivierte Erweiterungen:
- Auto-Type
- Browser-Integration
- SSH-Agent
- Secret-Service-Integration

Kryptographische Bibliotheken:
- Botan 2.19.5
```

Operating System: Linux
Desktop Env: Gnome
Windowing System: Wayland

**Comment by droidmonkey** [comment]
Post your client details here: https://github.com/keepassxreboot/keepassxc/issues/8784
