### ISSUE TITLE
MAJOR Security flaw, password is showing in cleartext when inserting TOTP.

### ISSUE THREAD

**Issue by chla-conscia** [keepassxreboot/keepassxc#11265]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. right-click input field in browser
2. choose KeePassXC-Browser
3. Fill TOTP

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Only show and fill in the TOTP

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Showing Entrys password before inserting the TOTP.
Also showing the password for a brief second after sending the TOTP. 

## Context
[NOTE]: # ( Give us any additional information you may have. )
MAJOR security flaw when password is showing in cleartext

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.9
Revision: 8f6dd13

Qt 5.15.11
Debugging mode is disabled.

Operating system: macOS 14.6
CPU architecture: arm64
Kernel: darwin 23.6.0

Enabled extensions:
- Auto-Type
- Browser Integration
- Passkeys
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 3.1.1

Browser:
- Release v1.69.168 (Sep 11, 2024)
  - KeePassXC integration for modern web browsers. 
    Version 1.9.3

![totp](https://github.com/user-attachments/assets/82761460-5db8-40e6-b15c-e2abd3f55835)

**Comment by droidmonkey** [comment]
Uhhhh no that doesn't happen. Perhaps this website is all messed up. We certainly have nothing to do with the part where you submit the totp to the website (ie, click verify).
