### ISSUE TITLE
[Feature Request] Expand Tray Icon functionality - Search and History items

### ISSUE THREAD

**Issue by bigalgeorge** [keepassxreboot/keepassxc#1126]
Ability to quick search and go to url from Tray Icon.
EG click tray icon brings up a search box with modal results after Enter or [OK] pressed.
Also from tray a History of previous urls from Tray with max_entries (history number) defined in General/Basic Settings. EG Click Tray shows previous searched items to Max_Entries and click on opens in new tab clicked item url.
If History is implemented, it could be also included on Mainform next to Search, as a dropdown listbox; action on click or enter goto url.

KeePassXC - 2.2.2
Revision: REVISION

Operating system: Debian/Linux Mint
CPU architecture: ARCH
Kernel: KERNEL

**Comment by droidmonkey** [comment]
Added to #149, closing
