### ISSUE TITLE
Keepassxc flatpak doesn't run MESA: error: Failed to query drm device.

### ISSUE THREAD

**Issue by Emily511511** [keepassxreboot/keepassxc#11272]
After installing the flatpak on Flathub, it doesn't run at all, and fails silently without flashing a window or anything.

Here is the output of the terminal logs:

> MESA: error: Failed to query drm device.
> glx: failed to create dri3 screen
> failed to load driver: iris
> failed to open /dev/dri/card1: No such file or directory
> failed to load driver: iris

**Comment by phoerious** [comment]
This is nothing we can fix. Please get help from your Linux distribution.
