### ISSUE TITLE
Touch ID failure on Mac OSX when more than 1 fingerprint is added to touch ID

### ISSUE THREAD

**Issue by lukethethird** [keepassxreboot/keepassxc#11270]
## Overview
Touch ID will not acknowledge  a second touch ID on OSX 12.7.6

## Steps to Reproduce

1. enable TouchID on MAC OSX  
2. record 2 touch ID's 
3. Only the first one will unlock KeyPassXC

## Expected Behavior
Expect both touch ID's to unlock as they do for al other apps on this mac

## Actual Behavior
[NOTE]: # Will not unlock

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # 

KeePassXC - Version 2.7.9
Revision: 8f6dd13

Qt 5.15.11
Debugging mode is disabled.

Operating system: macOS 12.7
CPU architecture: arm64
Kernel: darwin 21.6.0

Enabled extensions:
- Auto-Type
- Browser Integration
- Passkeys
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 3.1.1

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS
Desktop Env: 
Windowing System:

**Comment by droidmonkey** [comment]
Hello, we don't control the behavior of Touch ID itself. That is provided by macOS. If Touch ID doesn't recognize your second fingerprint, then you'll need to re-enroll. If it does recognize but disallow access, then you need to ensure you have enabled "Autofill passwords" on the Touc ID settings. It is possible that Touch ID will not allow a different fingerprint than the one used to log in to authorize access to secrets. Again, this is a macOS thing, not KeePassXC. Thank you!
