### ISSUE TITLE
Show current TOTP in database

### ISSUE THREAD

**Issue by S5NC** [keepassxreboot/keepassxc#11278]
A selectable current TOTP field in the database viewer is more convenient for my use case than entering the shortcut combination or clicking.

**Comment by droidmonkey** [comment]
It's in the preview panel, top right. There is a setting in Application Settings -> Security tab to enable showing it by default.

**Comment by S5NC** [comment]
> It's in the preview panel, top right. There is a setting in Application Settings -> Security tab to enable showing it by default.

I hadn't seen it, the OTP is at the bottom right, top right of the preview panel, very small
