### ISSUE TITLE
Search by password age

### ISSUE THREAD

**Issue by nevaran** [keepassxreboot/keepassxc#11276]
## Summary
I could not find anything relating to such a feature so I will be suggesting this since it is a pretty important thing to have for large databases.

## Examples
Searching for `age:2y` would show all passwords that are 2 years or older, `age:10w` would be 10 weeks or older, `age:350d` is 350 days or older, etc.

## Context
The database I work on constantly gets added on and edited every week by at least one entry added and a few edited, which makes it difficult to get password refreshes depending on the need. For example I have login credentials that the service can be easily accessed by random individuals, be it coworkers or just random civilians; I need to be able to refresh a password depending if it was older than X Y Z time or simply just have a quick search when refreshing every password, instead of having to rummage through the history (if i havent deleted it) and check if i have changed it recently - since the entry disappears in a search result after changing the value for the search pattern, like the weak passwords search.

**Comment by droidmonkey** [comment]
#8020
