### ISSUE TITLE
Minimisation of main window forces TOTP popup minimisation

### ISSUE THREAD

**Issue by S5NC** [keepassxreboot/keepassxc#11279]
KeePassXC - Version 2.7.9 Revision: 8f6dd13
Ubuntu 24.04

### Steps to reproduce
1. Open database 
2. View TOTP
3. Minimise main window

### Expected Behavior
Only the main window is minimised. If lock on minimise is enabled, this makes sense. If not, minimising the main window to move the small TOTP popup window to a convenient location for copying or comparing the code is desirable.

### Actual Behavior
The TOTP popup window is also minimised

**Comment by droidmonkey** [comment]
This must be a Linux only thing because you cannot minimize the KeePassXC window on Windows or macOS when the TOTP modal dialog is showing.

**Comment by qbast** [comment]
It seems to be Wayland specific thing. I tested in on Kubuntu 24.04 - on X11/Plasma session it works as expected: main window minimises, TOTP window stays. However on Wayland/Plasm session both windows minimise.

Also starting keepassxc as  `QT_QPA_PLATFORM=xcb keepassxc`  restores the old behaviour .

Looking at this bug report https://bugs.kde.org/show_bug.cgi?id=401950 , at least in KWin miminizing both windows is explicitly enforced and treated as correct behaviour.

**Comment by droidmonkey** [comment]
This will be a non-fix then. We cannot change compositor behavior.
