### ISSUE TITLE
Wrong content in clippoard with cmd-C

### ISSUE THREAD

**Issue by kordan** [keepassxreboot/keepassxc#11274]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
I have a record in my instance of keepass with the credential to get ssh access to a server.
In the "User name" field I have the name of the profile to get access. (in this case it is useless)
In the "Password" field I have the password to get access.
In the note I wrote: ssh myuser@myserver

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. I open my instance of keepass
2. I select my record
3. I highlight the text in the note
4. in the keyboard I push cmd-C

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
What I expect is to have in the clipboard the highlight text (ssh myuser@myserver)

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
What I get in the clipboard is the content of the field "Password"

## Context
[NOTE]: # ( Give us any additional information you may have. )
In the previous version this issue was not present.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION: 2.7.9
Revision: REVISION: 8f6dd13

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS

**Comment by droidmonkey** [comment]
This was a qt macos bug fixed for the next releae
