### ISSUE TITLE
Allow database without password/encryption

### ISSUE THREAD

**Issue by S5NC** [keepassxreboot/keepassxc#11277]
I would like to open my database without additional authentication, currently if I try to remove the password a popup appears stating "You must add at least one encryption key to secure your database!", despite accepting the strong discouragement warning.

The database is already stored securely.

I prefer not entering "1234" for the sake of having a password.

**Comment by droidmonkey** [comment]
Then you don't need a database, use notepad

**Comment by S5NC** [comment]
> Then you don't need a database, use notepad

Notepad cannot generate TOTP and be organised

**Comment by S5NC** [comment]
> Then you don't need a database, use notepad

Any change of mind?

**Comment by droidmonkey** [comment]
No

**Comment by S5NC** [comment]
> No

Implementing a restriction on passwords because most use-cases work fine with it is not a good design philosophy as it reduces flexibility. Why force databases to have a password? Please allow an empty password, and automatically try an empty password string on database load (or check if a flag in the database is set, then try the empty string)

**Comment by droidmonkey** [comment]
We don't force using a password, we force using at least one protection method. Password OR key file OR yubikey, is the minimum requirements.

**Comment by S5NC** [comment]
> We don't force using a password, we force using at least one protection method. Password OR key file OR yubikey, is the minimum requirements.

I understand why this is good for 99.9% of users, that having compromised KeePassXC databases makes the project look bad, and that checking for full-disk encryption is too intrusive and likely too complicated, so I guess I'll just have to cope 😃 Or you could make it super duper clear it's a bad idea to not set any password - after all there is already a lack of strong password warning but it gets disregarded by the requirement. I only need the database for organisation, not security from my OS.

**Comment by r-1104239IvanSmorodynov** [comment]
Dude is toxic af, gotta touch the grass
