### ISSUE TITLE
KeepassXC should respect URL paths for reverse proxy setups

### ISSUE THREAD

**Issue by sebschlicht** [keepassxreboot/keepassxc#11275]
## Disclaimer
I don't know if this feature request belongs to KeepassXC or the browser extension.
My sincere apologies if I'm at the wrong place here - let me know and I'll take it elsewhere.

## Expected Behavior
When querying KeepassXC entries for an URL, I expect KeepassXC to not only match the subdomain of the URL but also its path.

When browsing `mydomain.com/service-a` with the following three KeepassXC entries in my database

1. mydomain.com/service-a
2. mydomain.com/service-b
3. mydomain.com/

I expect KeepassXC to consider variant 1 the best fit and (1) make it the first suggestion or (2) leave out entries with equal subdomain but mismatching path.

This is especially important when working with services behind reverse proxies.

## Current Behavior
Currently KeepassXC shows all three variants, sorted alphabetically by name.

## Possible Solution
1. sort entries with matching paths up higher than those with merely matching subdomains
2. entirely hide entries with mismatching paths, given at least one entry's path matches

## Debug info
KeePassXC - 2.7.6 (snap)
KeePassXC-Browser - 1.9.3
Operating system: Linux
Browser: Firefox (snap)

**Comment by droidmonkey** [comment]
You need to enable the setting "return best matching entries" which is in the application settings, browser tab

**Comment by sebschlicht** [comment]
Oh shoot. Yeah, works like a charm. Awesome, thank you!

May I suggest renaming this option from `return only best-matching credentials` to `respect path when matching URL `.
While the tooltip is clear to me now, I definitely read it before and still didn't tick it.
