### ISSUE TITLE
KeePassXC 2.7.9 not starting under macOS 15.0

### ISSUE THREAD

**Issue by dotressel** [keepassxreboot/keepassxc#11280]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Upgrade to macOS 15.0
2. Try and start KeePassXC

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

KeePassXC window opening

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

Some process seems to start (the context menus in the top bar are there), but the GUI is not showing up

## Context
[NOTE]: # ( Give us any additional information you may have. )
Reinstallation does not fix the issue

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC 2.7.9

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS 15.0

**Comment by droidmonkey** [comment]
Are you using an external display using display link or similar tech?

**Comment by dotressel** [comment]
Yes I do use Display Link and an external display and that actually seems to be the issue. When disconnecting my external display keepass reappears.

**Comment by phoerious** [comment]
You have to disable screenshot protection then. That's a macOS/DisplayLink limitation.

**Comment by droidmonkey** [comment]
https://keepassxc.org/docs/KeePassXC_UserGuide#_screenshot_security

**Comment by dotressel** [comment]
Okay interesting, still wondering why it worked before upgrading, when I was already using Displaylink alongside keepassxc without disabling screenshot protection.

**Comment by Joustie** [comment]
Same here

**Comment by sebastianrothe** [comment]
I don't even see the menubar from KeePassXC

**Comment by droidmonkey** [comment]
You are using displaylink or remote desktop viewer and we are blocking screencapture. You can click around on the menubar to see the drop down menus, find the one with "allow screencapture" in it.
