### ISSUE TITLE
Command for 'Hide Passwords' not working on the preview panel!

### ISSUE THREAD

**Issue by Dominiquini** [keepassxreboot/keepassxc#11287]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
The command (or screenshot Ctrl+Shift+C) for unhide passwords is not working right on the preview panel! While I'm able to unhide passwordss on the main window (password column), in the preview panel I need to click on the yey button to unhide.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Open a database
2. Select a entry
3. Visualize the preview
4. Unhide all passwords (Uncheck View -> Hide Passwords)
5. The password on the preview windows remains hidden

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
The passwrod's field need to be showing by default, like the username field!

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
I need to manually unhide the password field on the preview window!

## Context
[NOTE]: # ( Give us any additional information you may have. )
The logic for the password's field and username's field should be equal; on the main window or on the preview window!
I was able to change this behavious on the (Security Settings -> Hide passwords in the entry preview panel), but either way, the behaviour is different for the username and the password!
I think that both fields should have the same behaviour, even if this settings should be removed!

## App Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.9
Revision: 8f6dd13

Qt 5.15.15
Debugging mode is disabled.

Operating system: CachyOS
CPU architecture: x86_64
Kernel: linux 6.10.5-1-cachyos

Enabled extensions:
- Auto-Type
- Browser Integration
- Passkeys
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 3.5.0

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux (Cachy OS)
Desktop Env: KDE
Windowing System: X11

**Comment by droidmonkey** [comment]
Application Settings -> Security tab -> Hide passwords in the entry preview panel

**Comment by Dominiquini** [comment]
> Application Settings -> Security tab -> Hide passwords in the entry preview panel

I know that option! I indicate that... The problem is if I uncheck the 'Hide passwords in the entry preview panel' on the security tab, the password on the preview panel is visible, even when I select 'Hide Passwords Ctrl+Shift+C' on the view menu!
I think the password should behave like the username both on the main window or the preview panel and the option on the security panel should be removed!
Of course this is just a suggestion. Feel free to disregard...
Thanks.

**Comment by droidmonkey** [comment]
It is slightly confusing. The view menu option is meant for the entry list only (it used to be accessed from right-clicking the entry list header). We do want two separate settings though as I suspect most people want the entry list to hide passwords while showing the current select entry's password only.

**Comment by Dominiquini** [comment]
> It is slightly confusing. The view menu option is meant for the entry list only (it used to be accessed from right-clicking the entry list header). We do want two separate settings though as I suspect most people want the entry list to hide passwords while showing the current select entry's password only.

Is that the 'Hide Usernames Ctrl+Shift+B' option, under the 'View' menu toggle the visibility of the usernames from the entry list and the preview panel. I just think the two options should behave similarly!

Thanks.

**Comment by sebma** [comment]
It is confusing indeed : I had to go to the `View->Hide passwords` menu item : 

<img width="235" height="332" alt="Image" src="https://github.com/user-attachments/assets/9b531ae4-d86e-4567-8d34-98cf848afd5a" />

in order to re-hide passwords in the entry preview panel although the `Hide passwords in the entry preview panel` option was already checked : 

<img width="437" height="207" alt="Image" src="https://github.com/user-attachments/assets/3779eba9-3c86-4c5c-817d-0a313ae01ba9" />

I must have typed `Ctrl+Shift+C` (instead of `Ctrl+C`) accidentally in the past.

**Comment by sebma** [comment]
@droidmonkey Hi, I was about to open an issue when I found this.

Can you please pin this (and maybe change to the title to something like `ATTENTION : Passwords not hidden on the preview panel!`) so us people don't open useless issues for this subject ?
