### ISSUE TITLE
URL scheme does not work with RealVNC - case sensitivity issue?

### ISSUE THREAD

**Issue by Mathiasw** [keepassxreboot/keepassxc#11286]
## Overview

I want to use the URL scheme from RealVNC shown here: https://help.realvnc.com/hc/en-us/articles/6449870411037-Can-I-launch-RealVNC-Viewer-from-a-link-on-a-web-page-or-program-using-URIs

I have determined that the URI needed is: com.realvnc.vncviewer.connect://Asxxxx-xxxxx-xxxxxx

If I enter the URI com.realvnc.vncviewer.connect://Asxxxx-xxxxx-xxxxxx directly into Safari, I get the pop-up shown below and I can connect:

![image](https://github.com/user-attachments/assets/9a50eefd-379c-4391-853f-19da3a4cdae9)

However, If I enter the URI into KeePassXC and then click on it in KeePassXC, I get the pop-ups shown below and I cannot connect:

![image](https://github.com/user-attachments/assets/a41ceb04-eb14-4d9a-928a-f2db7fd2967d)

![image](https://github.com/user-attachments/assets/c84cf986-7e64-435a-a73f-93c32eead56f)

I think the issue is that the server ID Asxxxx-xxxxx-xxxxxx is case sensitive for RealVNC, and this is being lost.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Get a server ID from RealVNC at: https://help.realvnc.com/hc/en-us/articles/6449870411037-Can-I-launch-RealVNC-Viewer-from-a-link-on-a-web-page-or-program-using-URIs
2. Test the URI in Safari  
3. Enter the server ID into KeepassXC and test there.

## Expected Behavior

I expect to be able to connect to the remote server.

## Actual Behavior

I get a message saying that the remote server "no such host is known", and also the CASE of the remote server name has all be changed to lower case.

## Context

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.9
Revision: 8f6dd13

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS

**Comment by droidmonkey** [comment]
Interesting, this appears to be a "bug" in Qt's `QUrl::fromUserInput(...)`. Likely because the host part of a URL is not case sensitive, but it shouldn't be changing the input like that... consider a Unicode url...

Further testing indicates that it is impossible to have mixed case in a Qt QUrl host field. This is unfortunately going to be a "won't fix" as a result.

**Comment by Mathiasw** [comment]
I tried encoding the URL as:

com.realvnc.vncviewer.connect://%41s<snip>

But even though %41 is a capital 'A', it was still passed as lower case to realvnc (as were all the other capital letters) and it didn't work.

But thanks for your prompt response and suggestion, anyhow.
