### ISSUE TITLE
Updates resets column settings

### ISSUE THREAD

**Issue by TheRoarkster** [keepassxreboot/keepassxc#11285]
## Overview
Every update to the app causes the column settings to reset.  Preferably, the updates would not effect each user's column settings.

## Steps to Reproduce
1. Install KeePassXC (on a linux machine)
2. Adjust column settings to not display attachments or "Has TOTP"
3. Update KeePassXC via normal update channels

## Expected Behavior
Respect column settings across updates.  So if you set the columns to not display Attachments and Has TOTP, it does not do so after an update.

## Actual Behavior
Each update, the column settings are reset to showing Attachments, Has TOTP, Title, Username, URL, Notes, Modified.

## Context
This has actually been the default occurrence for years.  

## Debug info from Help  
```
KeePassXC - Version 2.7.9
Revision: 8f6dd13

Qt 5.15.14
Debugging mode is disabled.

Operating system: Manjaro Linux
CPU architecture: x86_64
Kernel: linux 6.10.6-10-MANJARO

Enabled extensions:
- Auto-Type
- Browser Integration
- Passkeys
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 3.5.0
```

## Environment
```
Host: manjaro-imac 
Kernel: 6.10.6-10-MANJARO 
arch: x86_64 bits: 64
Desktop: GNOME v: 46.4 
Distro: Manjaro Linux
X11
```

**Comment by droidmonkey** [comment]
Updates won't affect column settings. However, if your user `~./cache` directory is mounted to a RAM disk then your settings for window size and columns and recent databases will reset on reboot. You can adjust where that is stored using env var or command line flags. https://keepassxc.org/docs/KeePassXC_UserGuide#_command_line_options

**Comment by TheRoarkster** [comment]
Thanks @droidmonkey, but my `~/.cache` is not on a RAM disk, and this happens every update. Is there perhaps a different cause?

**Comment by droidmonkey** [comment]
Perhaps your package manager is wiping the config file. We certainly do not and have not changed those settings in over 5 years

**Comment by TheRoarkster** [comment]
Thanks.  That could be it.  I'll try to move it.  Appreciate the help.
