### ISSUE TITLE
Not Updating via Mint SoftwareManager 

### ISSUE THREAD

**Issue by zendodeb** [keepassxreboot/keepassxc#11283]
## Overview
Installed KeePassXC via Linux Mint SoftwareManager. Installed version 2.7.6 It has NOT update since install 

## Steps to Reproduce

If I bring up the SoftwareManager, and query the KeePassXC version, it still has 2.7.6 listed as the current version

## Expected Behavior

I would expect the packages to be updated - or at least that I be notified. Is this not a supported means of installing KeyPassXC?

## Actual Behavior

Nothing happens. 

## Context

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.6
Revision: dd21def

Qt 5.15.13
Debugging mode is disabled.

Operating system: Linux Mint 22
CPU architecture: x86_64
Kernel: linux 6.8.0-45-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.19.3

Operating System: Linux Mint 22 Cinnamon 
Desktop Env: Cinnamon
Windowing System: X11/Wayland (???)

**Comment by varjolintu** [comment]
The version depends on the Mint repository. If you want the latest KeePassXC, your options are the official [PPA](https://launchpad.net/~phoerious/+archive/ubuntu/keepassxc), Flatpak or AppImage.
