### ISSUE TITLE
Trigger an export to second database with KeeShare

### ISSUE THREAD

**Issue by Sick-Andrew** [keepassxreboot/keepassxc#11282]
## Summary
I set up KeeShare and exported one group (with its entries) from db1.kdbx to db2.kdbx.
Then I noticed that exports are only triggered when changes are made in db1.
In my understanding the "parent" db1 is the main frame for the "child" database through KeeShare.
But unless you add/edit an entry in db1, no export is pushed to db2.
This leads to the situation that, if somebody in the "child" db2 makes changes to the entries, they just stay like that until something happens in the parent db1. 
I had the situation that a relative accidentally deleted an entry in the db2.kdbx. The entry remained gone for almost 2 weeks because I had nothing to update in db1.kdbx and my relatives thought the deleted entry simply never existed. Literally nobody noticed the change made in db2.kdbx.

Which options have not solved the problem?

- Synchronizing: is not an option as I want to keep that db2 without change merge in cases of accidents
- Set db2.kdbx to "import" as it imports ALL groups and entries from db1.kdbx, not just that one specified group for export.

## Context
It would be amazing to have a trigger in KeePassXC like this when KeeShare is launched.

- Access db1.kdbx
- Either upon opening or closing db1.kdbx: shared entries are moved/overwritten to db2.kdbx without the need to make a change in db1.kdbx

**Comment by droidmonkey** [comment]
See #https://github.com/keepassxreboot/keepassxc/issues/6160

As the setting implies, export doesn't care about the _current state of db2.kdbx_. You will always overwrite the state of db2.kdbx with the setting of export. It is actually a somewhat dangerous setting if not paired with an explicit _import_ on your relative's side. I absolutely recommend they setup their side to _import_ or your side to _sync_. A setting of import would have prevented the deleted entry from being saved to the db2.kdbx.

**Comment by Sick-Andrew** [comment]
Thanks. Hopefully this can be done in v2.8. 😊
