### ISSUE TITLE
Docker Image Qt version

### ISSUE THREAD

**Issue by qwchang** [keepassxreboot/keepassxc#11289]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
CMake requires Qt version 5.12.0 or higher, but the Docker image being used provides only Qt version 5.9.x. This results in a build failure due to the Qt version mismatch.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Set up a Docker container with the provided Docker image.
2. Run the build process using CMake.
3. CMake reports an error regarding the Qt version.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
CMake should detect and use a Qt version that is 5.12.0 or higher, allowing the build process to complete successfully without any errors.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
CMake throws an error during configuration, stating that Qt 5.12.0 or higher is required, but the provided Docker image only contains Qt version 5.9.x.

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.9
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows
Desktop Env: N/A (Docker-based environment)
Windowing System: N/A (Headless/Docker)

**Comment by droidmonkey** [comment]
We have set the docker image to the lowest supported Ubuntu version. If you want / need a higher Qt version you will have to update the Dockerfile on your side.
