### ISSUE TITLE
[Feature Request] Form Fill

### ISSUE THREAD

**Issue by bigalgeorge** [keepassxreboot/keepassxc#1128]
Web Form entries eg credit cards fill. 
Idea: Form Fill brings up a menu of Headers with predefined fields which if the header is selected, are entered into corresponding fields on the current Web Tab form.
Im not sure if this is possible, with current UI or not but its not too clear. This is a powerful and very useful feature used by competitor password apps. Most likely would need its UI to be part of the Web Addon.

KeePassXC - 2.2.2
Revision: REVISION

Operating system: Debian/Linux Mint
CPU architecture: ARCH
Kernel: KERNEL

**Comment by droidmonkey** [comment]
This is more associated with the browser plugin, please open an issue on [keepassxreboot/keepassxc-browser](/keepassxreboot/keepassxc-browser)
