### ISSUE TITLE
Auto-Type option accessible on AppImage 2.7.9 but not on `dnf` repository version

### ISSUE THREAD

**Issue by reneas** [keepassxreboot/keepassxc#11297]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
The Auto-Type option is nowhere to be found when installing KeePassXC through `sudo dnf install keepassxc-2.7.9-1.fc40.x86_64 `
When using the AppImage version everything is fine

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1.  Install and start KeePassXC
2.  Open options
3.  Don't see "Auto-Type" tab in general options

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
1.  Install and start KeePassXC
2.  Open options
3.  See "Auto-Type" tab in general options

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
The option is missing
![grafik](https://github.com/user-attachments/assets/0b7fba5a-a49f-4519-9136-caaaa8c7d50a)

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.9
Revision: 8f6dd13

Qt 5.15.14
Diagnosemodus ist deaktiviert.

Betriebssystem: Nobara Linux 40 (KDE Plasma)
CPU-Architektur: x86_64
Kernel: linux 6.11.0-200.fsync.fc40.x86_64

Aktivierte Erweiterungen:
- Auto-Type
- Browser-Integration
- Passkeys
- SSH-Agent
- KeeShare
- YubiKey
- Secret-Service-Integration

Kryptographische Bibliotheken:
- Botan 2.19.5

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env:KDE
Windowing System: Wayland

**Comment by droidmonkey** [comment]
[#2281 ](https://github.com/keepassxreboot/keepassxc/issues/2281#issuecomment-2373689932)
