### ISSUE TITLE
(NIST) Password Compliance indicators

### ISSUE THREAD

**Issue by novoid** [keepassxreboot/keepassxc#11295]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )

There are some general password guideline standards. One of the most prominently linked is by NIST (see bottom).

Such standards contain objectively measurable rules such as:

- minimum passphrase length
- complexity requirements
- character sets proposed
- and so forth.

Wouldn't it be peachy to have some sort of feature where I may check the compliance of my passwords according to that (and maybe other) standards?

Of course, this would be some sort of growing list of standards over time since the 2017 NIST requirements are widely used while the 2024/2025 NIST requirements are being published already.

Bonus solution: make it part of the KeePassXC settings/configuration so that I may decide which rules apply in my case: I select my own password minimum length, complexity, ... (with some presets such as NIST 2017)

What I'd rather not prefer: show the compliance only in the edit view of one single credential. -> No overview, no possibility to identify weak passwords among my long list of credentials, ...

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )

Either
(1) I may configure an additional column like "NIST 2017 password guideline compliance" in the pane that shows the credential list and search results ("Title", "Username", ...) or
(2) a menu entry that generates an additional on-the-fly summary of all my entries which I may sort according to their folders or compliance indicators.

Both solutions would show indicators such as:

- green/percentage/"yes": credential is compliant with selected standard
- yellow/percentage/"partly": credential is somewhat/partly compliant with selected standard
- red/percentage/"no": credential is not compliant with selected standard

The workflow I can imagine would be like:

1. Somehow chose a password guideline standard from a given list of standards (interactively or in the KeePassXC settings/configuration)
2. Somehow get a list of my credentials where I quickly get an overview which passwords do follow the selected standard (or not)
3. I may find some non compliant credentials actionable so that I switch to a compliant password instead.

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )

NIST password guidelines 2017: https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-63b.pdf

NIST password guidelines - public draft 2024: https://csrc.nist.gov/pubs/sp/800/63/b/4/2pd + Background article: https://scytale.ai/resources/2024-nist-password-guidelines-enhancing-security-practices/

**Comment by droidmonkey** [comment]
Database menu -> Database Reports

We don't evaluate against set standards because they are generally useless. We evaluate based on actual entropy calculations based on zxcvbn evaluation which takes those and MANY other factors into account. 

General rule: 14+ character random password = uncrackable

**Comment by novoid** [comment]
@droidmonkey Oh, I totally get your comment with respect to practical security aspects.

However, there are people and organizations that need to check or prove some compliance aspects in addition to that. For that, such tests would be really helpful and could push KeePassXC even more. At least I would have a good argument for pushing KeePassXC in my organization just because of this compliance-check.

Besides: I'd be cautious with words like "uncrackable". What passwords can be cracked depends on oh so many things.

Furthermore: I'd not just use the "completed" status but also a label like "won't fix", "declined" or similar for declined feature requests as this request is far from completed, it was declined.

YMMV.

Thanks for your time!

**Comment by droidmonkey** [comment]
> I'd not just use the "completed" status

Just a silly github feature...

> check or prove some compliance aspects

That is not appropriate for our software. We cannot and will not guarantee any compliance adherence. If you need compliance, at the enterprise level, you should use enterprise certified software. 

> What passwords can be cracked depends on oh so many things

Which is why my qualifiers of 14+ characters and randomized were included. Which is also how you get Good or Excellent ratings on your passwords entropy.

**Comment by novoid** [comment]
> > I'd not just use the "completed" status
> 
> Just a silly github feature...

I know. :pensive: 

That's why many projects did develop that workaround with the labels.

> > check or prove some compliance aspects
> 
> That is not appropriate for our software. We cannot and will not guarantee any compliance adherence. If you need compliance, at the enterprise level, you should use enterprise certified software.

OK, I have to accept that decision although I'm a bit irritated because KeePassXC is used in many companies I was working for. YMMV.

> > What passwords can be cracked depends on oh so many things
> 
> Which is why my qualifiers of 14+ characters and randomized were included. Which is also how you get Good or Excellent ratings on your passwords entropy.

Sorry, I don't want to be rude but password strength is a complicated thing. For example, it also depends on the hardware used to crack the hashed (and salted) credential. In a couple of years, somebody could read your statement and think that 14+ random characters are not being able to crack while this might absolutely be in reach for strong players in the market or breakthroughs in conceptual attacks on the algorithms used.

Therefore, I try to avoid such absolute statements and use phrases like "reasonable secure at the moment" or similar.

My personal approach is the xkcd method with random 5+ words as long as there is a chance I might have to enter the password manually - maybe even on a mobile device :vomiting_face: . Works great with the KeePassXC passphrase generator and some dictionaries.

If it requires a very good level of security and I don't have to enter the passphrase manually, I tend to go for 30-50 random characters - more or less limited by the password-length-processing ability of services, not my password management. After all, it's KeePassXC that does the typing for me. :wink: 


Have a great day and again - thanks for your time and effort for KeePassXC! It's one of the corner stones of my setup for many years and many security-related people I know or work with. You'd be surprised to know which important credentials are managed by your software. :bow:

**Comment by droidmonkey** [comment]
Just a note, the NIST publications you linked are meant for authenticator services and not necessarily standards for passwords. Appendix A discusses password strength but doesn't set any hard and fast standards or minimums. So not sure if you realized that or not, but that's the situation. 

PS- the 2017 NIST standard seems to be happy with randomized 8+ character passwords 🫣

**Comment by novoid** [comment]
True. Thanks for clarification.

However, when it comes to password policies and compliance rules, many organizations take the NIST recommendations as a guideline.

And yes, the current draft is a very welcomed update to the 2017 standard.
