### ISSUE TITLE
otp code non valid

### ISSUE THREAD

**Issue by Sol-alt** [keepassxreboot/keepassxc#11294]
Hi,
I installed the same database (saved on google drive) on 4 PCs. The problem is that the codes generated for the accounts are all different and only the code generated by 1 pc is correct. Is it possible to synchronize OTP codes on all PCs at the same time?

Thank you

## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. 
2. 
3. 

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows/Linux/macOS
Desktop Env: Gnome/KDE/XFCE/Mate/Cinnamon
Windowing System: X11/Wayland

**Comment by droidmonkey** [comment]
Sync your time on each computer.

**Comment by Sol-alt** [comment]
> Sync your time on each computer.

Do you mean the time on windows? How can I make sure they all update at the same time? Could you explain me? 

Thank you very much

**Comment by droidmonkey** [comment]
https://winbuzzer.com/2022/04/19/how-to-sync-your-clock-time-with-an-internet-time-server-in-windows-11-xcxwbt/

**Comment by Sol-alt** [comment]
I followed the steps but the issue still remain. Every PC shows different codes and only 1 pc works fine.

**Comment by droidmonkey** [comment]
You will need to figure out how to synchronize your computers' time. That is the problem, it is not with KeePassXC. Please use Google to find resources for your specific systems. You can set the time roughly manually as well, but even 30 seconds off will cause TOTP to fail.

**Comment by untitled9074** [comment]
@droidmonkey thank you so much! 

For others who might be in a similar situation as I was in today: it appears Windows 11 updates time once a week, if you have a Windows machine that you only use occasionally you might end in a situation when your system clock is minutes off, then your TOPT codes produced from a valid DB by a valid app will be useless. Syncing to the time server fixed the issue for me.
