### ISSUE TITLE
"passwords" (UUID 005) from 1passwords get not imported 

### ISSUE THREAD

**Issue by KrisKind75** [keepassxreboot/keepassxc#11298]
## Overview

CategoryUIID 001, which are "logins" in 1password, are stored like this in the JSON export from 1password:
```JSON
{

"categoryUuid": "001",
"details": {
"htmlForm": {},
"loginFields": [
  {
  "value": "xxxxxxxxxxxxxxx",
  "id": "",
  "name": "password",
  "fieldType": "P",
  "designation": "password"
}]
},
```
while 005 "passwords" are stored like this:
```JSON
{
"categoryUuid": "005",
"details": {
"loginFields": [],
"sections": [],
"passwordHistory": [],
"password": "xxxxxxxxxxxxxxxx"
},
},
```
005 items gets imported, but without the actual password, probably due to the different structure in the JSON Export. I have several hundreds of these...

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Make a new password in 1password
2. Export 1pux file
3. Import into KeePassXC
4. Compare the 2 passwords

## Expected Behavior

I expect the passwords to be the same

## Actual Behavior

The item gets imported, but the actual password is missing.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC for windows - VERSION 2.79
1Password for Windows 8.10.45 (81045002)

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 11

**Comment by droidmonkey** [comment]
So kind of 1Password to properly document their obfuscated export format...

**Comment by KrisKind75** [comment]
Yeah, nothing mentioned here: https://support.1password.com/1pux-format/.
