### ISSUE TITLE
Wayland - no automatic tab in general parameter

### ISSUE THREAD

**Issue by mchenier2** [keepassxreboot/keepassxc#11307]
![KeepassWayland](https://github.com/user-attachments/assets/35da6f50-db54-469e-953c-de13bdcecae8)
![KeepassxcX11](https://github.com/user-attachments/assets/6a471ce8-d9d1-4de6-a03b-1a7f4af499ff)
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. 
2. 
3. 

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows/Linux/macOS
Desktop Env: Gnome/KDE/XFCE/Mate/Cinnamon
Windowing System: X11/Wayland

**Comment by droidmonkey** [comment]
Autotype is not supported when running under wayland. Please search the issues you'll find lots of discussion.

**Comment by mchenier2** [comment]
Thank you.
