### ISSUE TITLE
Layout Has Been Hidden

### ISSUE THREAD

**Issue by 510208** [keepassxreboot/keepassxc#11304]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
My KeePassXC's Groups, Tags and Preview layout likely hidden...

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Launch my KeePassXC
Just this, I haven't do anything on it(Maybe...If I probably do, please remind me.)

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Display like this:
![image](https://github.com/user-attachments/assets/4f8c469d-f300-4041-9fc8-6f11c2a20462)

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Display like this(I am using Chinese):
![image](https://github.com/user-attachments/assets/b90719e3-7384-4a46-b822-58a1cc43bb71)

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.9
Revision: 8f6dd13

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows
Desktop Env: Windows
Windowing System: Windows

**Comment by droidmonkey** [comment]
https://github.com/keepassxreboot/keepassxc/issues/10927#issuecomment-2180333104
