### ISSUE TITLE
UI won't load after inputting password

### ISSUE THREAD

**Issue by DavidKutu** [keepassxreboot/keepassxc#11309]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
After unlocking a database, the UI doesn't load. By UI, I mean everything below the menu bar, it just shows nothing. The workaround is to lock and close the database, and open it again. It works the second time.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Wake PC up from sleep (DB is selected, and locked)
2. Open KeePassXC
3. Input password

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
KeePassXC opens database as usual, showing groups and passwords.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
The UI remains blank.

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.9
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 11

**Comment by droidmonkey** [comment]
https://github.com/keepassxreboot/keepassxc/issues/10927
