### ISSUE TITLE
AutoType disappears if allow screen capture is not enabled with display link

### ISSUE THREAD

**Issue by fberlakovich** [keepassxreboot/keepassxc#11301]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
I have 2 external screens and the builtin screen, but I work exclusively on the external screens. Screen 1 is my main screen. Screen 2 is connected via display link, which for whatever reason uses screen sharing to drive the second screen (I had to grant it screen capture permissions). When the AutoType window opens on screen 2, it becomes invisible but remains open.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Trigger AutoType on a screen connected via display link

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
The AutoType window should appear or, at least, an error message indicating that AutoType is not possible on a captured screen without allowing screen capturing.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
The AutoType window appears, I can see it, but as soon as I move the mouse or press any key it disappears. This leaves KeepassXC in a state where it thinks the AutoType window is still open and I cannot use AutoType a second time anymore (on any screen) until I reopen KeepassXC. 

## Context
[NOTE]: # ( Give us any additional information you may have. )

The reason seems to be that "Allow Screen Capture" was unticked and as mentioned above, Display Link Manager uses screen capture. When I enable the option, everything works as expected. However, it took me a while to figure this out and the user experience of the window simply disappearing is suboptimal.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.9

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS

**Comment by droidmonkey** [comment]
https://github.com/keepassxreboot/keepassxc/issues/10757
