### ISSUE TITLE
Auto-Authenticate with passkey

### ISSUE THREAD

**Issue by PAStheLoD** [keepassxreboot/keepassxc#11308]
## Summary

Add configurability for passkeys to allow easier login. The user should be able to setup things so the application does not ask for confirmation if there's only one eligible passkey.

## Examples
Ideally there would be a global setting, and then the user should be able to override it for each entry and group. (Like Auto-Type.)

## Context

The "information leak" potential of passkeys are significantly reduced compared to passwords (due to the nature of the WebAuth protocol, the actual secret never leaves the app), so in case of an accidental/unintended "authentication" the impact is limited. (Signed challenge is transmitted to a TLS authenticated site, Relying Party ID must match the origin of the site.)

The browser extension could help making sure that the authentication request is coming from the currently visible and focused tab. (As far as I understand the WebExtensions API has the functionality to query the active tab the "tabs" permission.)

For added security this could be constrained to a specific full URL (not just domain/origin matching). 

Thanks for considering!

**Comment by droidmonkey** [comment]
Hello there, please see #10406

Requesting passkey approval is a requirement in the spec and we won't deviate from that as much as possible.
