### ISSUE TITLE
Change the same password for same user on different servers

### ISSUE THREAD

**Issue by AlessandrodeBertucci** [keepassxreboot/keepassxc#11302]
Hi, I have the same user to manage a cluster of 50 servers: this user has the same password on all 50 management sites.
In my KeePassXC I have registered all 50 URLs with user and password (for login on individual servers).
Every month,  I  proceed with password change.
Is there a way to change the password of this user for all its occurrences?
Do I have to do the password change manually, one at a time?
Does anyone else have the same need as me?

Thanks.

**Comment by droidmonkey** [comment]
https://keepassxc.org/docs/KeePassXC_UserGuide#_clone_an_entry

**Comment by AlessandrodeBertucci** [comment]
Hi @droidmonkey,
thanks for replying so fast.
I don't understand: how the Clone function could help in my case?
Could you explain better, please.
Thanks.
