### ISSUE TITLE
Main database empty until I open a backup in another tab

### ISSUE THREAD

**Issue by imralav** [keepassxreboot/keepassxc#11319]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

When I open my main database file, I see empty tab with nothing inside. Not even the main folder on the left is present.
Then, I open a backup file of the same database file, it opens properly in another tab. And then suddenly, the previous tab with main database is all fine, everything is there.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )

1. Load main database file
2. Notice how it's empty, nothing is listed
3. Load backup database file (with the ".old" suffix in the filename)
4. Notice how backup is loaded properly, everything is listed
5. Come back to previous tab with main database file
6. Notice how it is now visible, as if everything was fine

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

I want to see the main database file immediately, without the need to load another one.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

## Context
[NOTE]: # ( Give us any additional information you may have. )

It started happening after I updated to 2.7.9. I don't remember the previous version, but it was all fine then.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Wersja 2.7.9
Rewizja: 8f6dd13

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 10

**Comment by michaelk83** [comment]
Probably #10927
