### ISSUE TITLE
opening an attachment fails if there is no default viewer for it in the OS

### ISSUE THREAD

**Issue by FlorinAndrei** [keepassxreboot/keepassxc#11312]
## Overview
I have an attachment called `file.local` in an entry. I go to Advanced / Attachments, select the file, click Open.
Nothing happens.
This is because the OS has no handler defined for `.local` files.
Would be nice if the app had an option to define a default file viewer, like Sublime Text.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.9
Revision: 8f6dd13

Qt 5.15.11
Debugging mode is disabled.

Operating system: macOS 14.6
CPU architecture: arm64
Kernel: darwin 23.6.0

Enabled extensions:
- Auto-Type
- Browser Integration
- Passkeys
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 3.1.1

**Comment by FlorinAndrei** [comment]
Alternatively, if no handler is defined, at least gray out the Open button.

**Comment by droidmonkey** [comment]
There is no way for us to determine if there is a default viewer without a ton of unnecessary code. See #3383
