### ISSUE TITLE
Search in open entry within the Notes field

### ISSUE THREAD

**Issue by arigit** [keepassxreboot/keepassxc#11314]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
Currently keepassxc has a great full-database search function that is able to find entries matching a string.
What is missing is the ability to search within the Notes field of an Entry that is already open. While most entries normally have very short notes associated to them, there are use cases (see context) where the KeepassXC DB entry may have long, multipage notes that would hugely benefit of the ability to search. 

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )
When openin an entry, a button called "Search within Note" could be shown right below the Notes box, or to the right of the "Preset" (expiry) button.

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
Use case: some of my entries have long notes (several pages of notes) associated to them, for example, an entry called "Project XY Confidential Data", and some confidential data related to the project, e.g. design principles or whatever. 
Another one: in an Car Insurance entry, the Notes field could be used to store details about a policy. Etc- this idea extends quite rapidly to all kinds of entries.
It would be great to have a "Search in Note of Open Entry" function implemented such that a string / regex can be searched within the Notes filed

**Comment by droidmonkey** [comment]
Duplicate request. #4864
