### ISSUE TITLE
Window bar is light on Gnome, Debian 13/trixie

### ISSUE THREAD

**Issue by maurerle** [keepassxreboot/keepassxc#11318]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

## Steps to Reproduce
The Title bar or window bar stays light, even when activating Dark mode.

![image](https://github.com/user-attachments/assets/fd4c3d75-5937-4bf7-959c-40ab1658e8b3)

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Window bar should follow dark theme correctly

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Window bar stays light even though dark mode is selected (screenshot)

## Context
[NOTE]: # ( Give us any additional information you may have. )
It does not matter if one is switching from light to dark during having keepassxc open or opening it with system dark mode enabled.
It even is the case when dark mode is selected in keepassxc.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.9
Revision: 8f6dd13

Qt 5.15.13
Debugging mode is disabled.

Operating system: Debian GNU/Linux trixie/sid
CPU architecture: x86_64
Kernel: linux 6.10.11-amd64

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: Gnome
Windowing System: Wayland

**Comment by droidmonkey** [comment]
Please share your concerns with GNOME. We do not style the window border / title bar. 

https://github.com/keepassxreboot/keepassxc/issues/8050#issuecomment-1126720822

**Comment by seb-maillard** [comment]
Hey @maurerle ! FYI switching `Theme` to `Dark` and restarting KeepassXC [did the trick](8050#issuecomment-2395474097) for me.

**Comment by mentonin** [comment]
I think this should be looked into again: titlebar is dark when keepassxc theme set to "dark" and white when keepassxc theme set to "auto" (on a dark OS theme), so I believe keepassxc has is, indeed, influencing its window border/titlebar
