### ISSUE TITLE
Auto-Type can't be used in Ubuntu (24.02) when running the Wayland compositor. 

### ISSUE THREAD

**Issue by Habbut** [keepassxreboot/keepassxc#11311]
## Overview
Auto-Type can't be used in Ubuntu (22.04/24.02) when running the Wayland compositor. 

## Steps to Reproduce
The actual 24.04. LTS Version of Ubuntu is running. All updates are installed.
1) Wayland Compositor is the default WIndow-Manager in Gnome. Global Auto-Type refuses to work.
2) Switching to X11 by configurating /etc/gdm3/custom.conf works. Global Auto-Type is working.

## Expected Behavior
Auto-Type will work in (X)Wayland as it does when running X11.

## Actual Behavior
When running Wayland, setting QT_QPA_PLATFORM=xcb or start KeePassXC with the -platform xcb command-line flag does not help. 

## Context
qt6-wayland is installed

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.9
Revision: 8f6dd13

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux Ubuntu LTS 24.04
Desktop Env: Gnome
Windowing System: X11/Wayland

**Comment by droidmonkey** [comment]
Please search, plenty of issues discussing this thank you.
