### ISSUE TITLE
Invalid Application ID and other AppStream Appdata Issues

### ISSUE THREAD

**Issue by AsavarTzeth** [keepassxreboot/keepassxc#1131]
## Expected Behavior

Files should validate against the relaxed, or less strict, validation tests and not require downstream patching in order to be usable everywhere.

As part of this issue I will provide a pull request that fixes these issues, as well as some other minor ones.

## Current Behavior

The id is not compliant with the [AppStream specification](https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-id-generic).

Specifically the section that states:
*"The ID must follow a reverse-DNS scheme, consisting of __{tld}.{vendor}.{product}__, for example __org.kde.Gwenview__ or __com.hugski.ColorHug2__."*.

In addition to this the `<icon>` fails to validate with `appstream-util validate-relaxed`. It appears it is not allowed with desktop appdata. Personally I have never seen it used in this context.

While [Section 2.1.3. XML Specification](https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-icon) contradicts this, [Section 2.2. Desktop Applications](https://www.freedesktop.org/software/appstream/docs/sect-Metadata-Application.html) and [4.1. For GUI application upstream maintainers](https://www.freedesktop.org/software/appstream/docs/chap-Quickstart.html#sect-Quickstart-DesktopApps) never mention this tag and the latest validation tools does fail with this tag. It is possible this is an error in the documentation or left overd from older versions of the specification.

There are many more minor validation failures, but those are optional and not required for compliance. Therefore I won't bring it up in this issue.

## Possible Solution

Changing the id to `org.keepassxc.KeePassXC` and renaming the appropriate files based on that. Also removing the incorrect `<icon>` tag.

This will ensure that the most forgiving validation tests do not fail, making the appdata file usable everywhere.

## Steps to Reproduce

Flathub uses `appstream-util` for validation. Passing `appstream-util validate-relax org.keepassxc.appdata.xml`, is a [requirement for Flathub](https://github.com/flathub/flathub/wiki/Review-Guidelines#desktop-integration) (and `flatpak-builder` itself). Currently this fails:

```
org.keepassxc.appdata.xml: FAILED:
• tag-invalid           : <icon> not allowed in desktop appdata
• tag-invalid           : stock icon is not valid [keepassxc]
Validation of files failed
```

Running `appstream-util validate` reveals a lot more issues, but I won't focus on that in this issue. For now I am interested in this passing the minimum requirements since that is a relatively quick and simple fix.

You can also run `appstreamcli validate org.keepassxc.appdata.xml`. Passing this is a [optional requirement for AppImageHub](https://github.com/AppImage/appimage.github.io#checklist-for-submitting-your-own-appimage).

```
W - org.keepassxc.appdata.xml:org.keepassxc:4
    The component ID is not a reverse domain-name. Please update the ID and that of 
    the accompanying .desktop file to follow the latest version of the Desktop-Entry 
    and AppStream specifications and avoid future issues.

Validation failed: warnings: 1, pedantic: 14
```

Relevant to the context bellow is also this output from `flatpak-builder`, used with an updated and [improved manifest](https://github.com/AsavarTzeth/flathub/blob/org.keepassxc.KeePassXC/org.keepassxc.KeePassXC.json).

```
org.keepassxc:                     AppData problem: markup-invalid : <id> does not have correct extension for kind
org.keepassxc:                     AppData problem: tag-invalid : <icon> not allowed in desktop appdata
org.keepassxc:                     AppData problem: tag-invalid : stock icon is not valid [keepassxc]
Error loading AppData file: AppData file /app/share/appdata/org.keepassxc.KeePassXC.appdata.xml was not valid
Error: ERROR: appstream-compose failed: Barnprocess avslutades med kod 1
```

*Note that in this case I make `flatpak-builder` rename the appdata file so that it complies with the spec. The file `org.keepassxc.KeePassXC.appdata.xml` is your current appdata (as of 2.2.2 release).*

## Context

I am working on adding KeePassXC to Flathub. Some of the issues with the appdata and id are blockers for this. Solving this would enable me to finish this work immediately without patching downstream, which will likely be questioned by the Flathub reviewers.

As you might or might not be aware, your [existing flatpak](https://github.com/keepassxreboot/keepassxc-packaging/blob/master/flatpak/org.keepassxc.App.json) manifest uses `org.keepassxc.App` as the id. If you don't like the longer `org.keepassxc.KeePassXC` id that I choose, that is an alternative solution. What matters is that **{product}** is part of the id and that the id is the same everywhere (appdata, desktop entry, dbus id...).

**Comment by phoerious** [comment]
Please use org.keepassxc.KeePassXC. However, changing that also requires changes in other parts of our build and deployment pipeline. Most notable parts are the CMakeLists.txt fies, our AppImage recipe and Snapcraft file.

**Comment by AsavarTzeth** [comment]
I am well aware of that. I used grep to verify that every instance of `org.keepassxc` was changed. I did not however change anything outside this repo.

**Comment by phoerious** [comment]
It's insidebthe Repo (AppImage-Recipe.sh), but it's assembled from a variable name, so grep won't find it.
