### ISSUE TITLE
Only AutoOpen database for fqdn

### ISSUE THREAD

**Issue by beedaddy** [keepassxreboot/keepassxc#11329]
## Summary
Currently, it is possible to auto-open a database. You can also specify one or more hostnames where this should happen (IfDevice). Sometimes you might also specify the domain where this should happen. For example, if you have to machines with the same hostname in different locations/domains. myhost.aaa.bbb should auto-open the database, but myhost.xxx.yyy should not.

## Examples
IfDevice could accept FQDN names, so that it is clear which host should auto-open the database. Alternatively, an attribute like IfDomain could do this.

## Context
I have indeed two machines with the same hostname, but only one of them (specific domain) shall auto-open the database.

**Comment by droidmonkey** [comment]
Hello, thank you for the suggestion, but we aren't going to make changes to this interface.
