### ISSUE TITLE
Window doesn't snap vertically in GNOME 47

### ISSUE THREAD

**Issue by saccarosium** [keepassxreboot/keepassxc#11328]
## Overview

After updating to Gnome 47 vertical window snapping doesn't seem to work

## Steps to Reproduce

1. Open KeepassXC from gnome shell
2. Hit either: Super + Left/Right 
3. Try to move to the edge the window

## Expected Behavior

Window should snap vertically occupying half of the screen.

[Screencast From 2024-10-08 10-27-35.webm](https://github.com/user-attachments/assets/1432b85f-9096-4895-a209-d93ccb1ddd6f)

## Actual Behavior

Window stay the same.

[Screencast From 2024-10-08 10-32-33.webm](https://github.com/user-attachments/assets/880520cf-3542-4a5a-8b94-1bc18b255a47)

## Context

KeePassXC - Version 2.7.9
Revision: 8f6dd13
Distribution: Flatpak

Operating System: Arch Linux
Kernel: 6.11.1
Desktop Env: Gnome
Windowing System: Wayland

I've run both graphically and through flatpak run.

Running directly with flatpak gave me this error (unrelated in my opinion):
```
qt.qpa.qgnomeplatform: Could not find color scheme  ""
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
```

**Comment by droidmonkey** [comment]
Likely similar issue to this https://github.com/keepassxreboot/keepassxc/issues/10018#issuecomment-1816792708

**Comment by droidmonkey** [comment]
Yes this is exactly because your screen size is too small to allow KeePassXC to be resized to half the screen. I replicated this in VirtualBox and snapping worked fine when the virtual screen was big enough.
