### ISSUE TITLE
Unable to fetch MS Edge browser's favicon

### ISSUE THREAD

**Issue by pa-0** [keepassxreboot/keepassxc#11322]
### Overview
Cannot download the favicon for Microsoft Edge.

### Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Paste 'https://edgestatic.azureedge.net/welcome/static/favicon.png' into the `favicon URL` field
2. Click <kbd>Download favicon</kbd> 
3. Error: `Unable to fetch favicon`

### Expected Behavior
The Edge favicon is downloaded and added to the library.

### Actual Behavior
KeepassXC returns an error

### Context

```console
KeePassXC - Version 2.7.9
Revision: 8f6dd13

Qt 5.15.11
Debugging mode is disabled.

Operating system: Windows 11 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.22631

Enabled extensions:
- Auto-Type
- Browser Integration
- Passkeys
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 3.1.1
```

Operating System: Win 11 Enterprise

**Comment by droidmonkey** [comment]
Icon doesn't exist: https://edgestatic.azureedge.net/favicon.png

We pull from the base domain not from a link to an image. 

For your case, you can simply download the icon in your browser then import it into keepassxc from the icons selection screen.

**Comment by pa-0** [comment]
Ahh, I swear it was here yesterday.  Thanks sorry for wasting your time.

**Comment by pa-0** [comment]
Actually the link you posted is not the same as the link I posted.

https://edgestatic.azureedge.net/welcome/static/favicon.png

**Comment by droidmonkey** [comment]
we don't care what the _path of the link_ is. We don't pull an image, we check the base domain
