### ISSUE TITLE
TOTP bogus codes

### ISSUE THREAD

**Issue by robertolopezlopez** [keepassxreboot/keepassxc#11320]
## Steps to Reproduce
1. Set up TOTP for a website. Let's say: cloudflare.
2. Enter the secret key from cloudflare into KeepassXC, accept and save database.
3. Try to validate it using the TOTP code from KeePassXC: cloudflare tells me that it is not valid.

## Expected Behavior
KeePassXC should give valid TOTP codes.

## Actual Behavior
Cloudflare tells me that the code is not valid.

## Context
* I have seen this error on cloudflare.com and allegro.pl.
* After I have set up TOTP on KeepassXC, I open the kdbx file with other password managers:
  * Gnome Secrets (https://gitlab.gnome.org/World/secrets) it gives me the same not valid codes.
  * KeePassDX on Android gives me valid codes.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.9
Revision: keepassxc 2.7.9-3

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux Arch
Desktop Env: XFCE
Windowing System: x.org

**Comment by droidmonkey** [comment]
Sync your computer's time.

**Comment by robertolopezlopez** [comment]
:laughing: fine, today I have just learned that TOTP and NTP are related

Thank you, @droidmonkey !
