### ISSUE TITLE
Auto-type removes the dot from the username or password

### ISSUE THREAD

**Issue by isparnid** [keepassxreboot/keepassxc#11331]
## Overview
The username or password may contain a dot such as "firstname.lastname" and "P@ss.Word".
When I use Auto-type to automatically fill in the Username and Password fields, the dot is removed  and they become "firstnamelastname" and "P@ssWord".

Bug appeared since upgrading from Ubuntu 22.04 LTS to 24.04 LTS in August

## Context
OS Ubuntu 24.04 / X11/Gnome shell 46.0
KeePassXC - 2.7.9

[NOTE]:  just an idea, is it possible that introduction of the TR() function in src/autotype/xcb/AutoTypeXCB.cpp line 29-30 provoque this ?

**Comment by droidmonkey** [comment]
https://github.com/keepassxreboot/keepassxc/issues/10883
