### ISSUE TITLE
New entry is not saved when clicking Apply

### ISSUE THREAD

**Issue by smrqdt** [keepassxreboot/keepassxc#1133]
## Expected Behavior

When creating a new entry, the entry should be saved after clicking on Apply. The should be a new entry in the database, even when I leave the entry afterwards pressing Escape/clicking Cancel.

## Current Behavior

There is no new entry, all information entered is lost.

## Possible Solution

Create a new entry when after clicking Apply if the entry did not exist before. 

Alternatively (or additionally) there should at least be either a warning or a undo function (like an auto-save in trash) for leaving an unsaved new entry.  

## Steps to Reproduce (for bugs)

1. Open New Entry
2. enter some data
3. hit apply
4. leave through clicking Cancel or pressing Escape

## Context

After clicking apply I expect the entry to be saved. I lost new entries multiple times because I though apply would save them. I left the dialog open for some reasons, and later thought I could leave the dialog through pressing Escape (which is kind of a reflex when I do not expect to lose any data).

## Debug Info

KeePassXC - Version 2.2.2
Revision: 6d46717

Libraries:
- Qt 5.9.2
- libgcrypt 1.8.1

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 4.9.56-1-lts

Enabled extensions:
- KeePassHTTP
- Auto-Type
- YubiKey

**Comment by TheZ3ro** [comment]
The apply button gave us so much trouble

**Comment by droidmonkey** [comment]
Hmm, I remember testing this case when I first coded it in. I wonder if this is a regression.

**Comment by nemesisdesign** [comment]
I just bumped on this issue.. KeepassXC 2.3.0 on elementaryos.

**Comment by droidmonkey** [comment]
That is not possible, there is a specific test case that I added to make sure this issue did not regress.
