### ISSUE TITLE
KeePassXC 2.7.8 has stopped to work

### ISSUE THREAD

**Issue by podlom** [keepassxreboot/keepassxc#11336]
I'm working on Ubuntu 24.04.1 LTS. After recent update to version 2.7.8 my KeePassXC has stopped to work. I can't open existing database. I can't import database. I can't create a new database (it doesn't saved).

## Steps to Reproduce
1. Open  KeePassXC  2.7.8 on Ubuntu Linux 24.04.1 LTS.
2. Databases can't be selected, imported or created. 

## Expected Behavior
Last used database should open.

## Actual Behavior
No database opened. Can't open, import or save newly created database.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Версія 2.7.8
Ревізія: f6757d3
Дистрибутив: Snap

Qt 5.15.11
Режим налагодження вимкнено.

Операційна система: Ubuntu Core 22
Архітектура ЦП: x86_64
Ядро: linux 6.8.0-45-generic

Увімкнені розширення:
- Автозаповнення
- Інтеграція з браузером
- Passkeys
- Посередник SSH
- KeeShare
- YubiKey
- Сполучення зі «Службою таємниць».

Шифрувальні бібліотеки:
- Botan 2.19.1

**Comment by droidmonkey** [comment]
Unfortunately, this issue doesn't make much sense to me. Since you are using the snap, where did you save your database? Is it that you cannot find your database file or the literal functions on the app are broken? We recommend the flatpak release instead of snap.

**Comment by Readf0x** [comment]
I have a similar issue, the file chooser will not open. On NixOS unstable, rev c31898adf5a8ed202ce5bea9f347b1c6871f32d1

**Comment by droidmonkey** [comment]
These aren't issues with our program. These are desktop integration issues which lie with snap interface or qt.

**Comment by Readf0x** [comment]
> These aren't issues with our program. These are desktop integration issues which lie with snap interface or qt.

Yeah, my issue was with the freedesktop portal config. For some reason, KeepassXC specifically did not respect individual implementation overrides, so it was trying to use hyprland's desktop portal instead of kde's. I fixed it by just using defining kde as a fallback option instead of doing individual impl. overrides.

**Comment by droidmonkey** [comment]
Closing due to lack of response. Please post with answers to the questions so we can attempt to help.
