### ISSUE TITLE
Can't copy anything from notes

### ISSUE THREAD

**Issue by ShadSterling** [keepassxreboot/keepassxc#11334]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
Since the last update I can't copy anything from the notes on an entry.  This has been critical functionality for me, for security questions, CVV codes, accounts with multiple passwords, and so on.

I often get into situations where something else is being difficult and I have to re-copy and re-paste the same non-password secret text over and over, such as credit card CVV into an online store that has some issues with its checkout process.  Now that you've made ⌘C ignore the selected text my habit of using ⌘⇥,⌘C,⌘⇥,⌘V to get the selected non-password secret from the notes ends up pasting passwords in places where passwords really shouldn't go, such as the password to log in to my bank going to a much less trusted online store

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Select any text in an entry's notes
2. ⌘C to copy that text to the clipboard
3. switch to wherever that text is needed
4. paste your password where the selected text is needed

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
The same behavior as always, and as every other app, copy the text I told you to copy

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
You copy the password that I intentionally did not select

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.9
Revision: 8f6dd13
(There is no Help → About; this is from KeePassXC → About KeePassXC → Debug Info)

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS Sequoia 15.0
Desktop Env: 
Windowing System:

**Comment by michaelk83** [comment]
Copy behavior was changed in #10853. As a workaround, try right-clicking the text selection (or whatever the macOS equivalent is), then Copy from the popup menu.

There was historically a problem with Copy, since the keyboard shortcut was assigned to copy password.

**Comment by droidmonkey** [comment]
https://github.com/keepassxreboot/keepassxc/pull/10966 fixed for next release
