### ISSUE TITLE
Shift + Scroll for horizontal scrolling

### ISSUE THREAD

**Issue by suther** [keepassxreboot/keepassxc#11337]
Would be very handy to have the functionality to scroll the main-screen left & right by holding the SHIFT-Key on Keyboard and using the Scroll from Mouse. 

That's a common functionality in any browsers and would improve the UX a lot.

![image](https://github.com/user-attachments/assets/b92206a2-418d-444f-aba4-1eb4ed504f5d)

**Comment by droidmonkey** [comment]
Qt implements this as `Alt + Scroll`
