### ISSUE TITLE
Win 11 KeepassXC run but no window pop up

### ISSUE THREAD

**Issue by Dual-Boot** [keepassxreboot/keepassxc#11339]
## Overview

Win 11 KeepassXC run but not window pop up

## Steps to Reproduce
1. install KeepassXC latest version on Windows 11
2. launch KeepassXC

## Expected Behavior
KeepassXC should open his own window application

## Actual Behavior
No window application appears
KeepassXC is present in task bar
I can not close the application until I use the Windows Task Manager and kill the process

## Context
Windows 11 up to date
EDR : BitDefender Gravity Zone
Workstation in a domain

KeePassXC - 2.7.9
Revision: latest on 09/10/2024 just download on the offical site

**Comment by varjolintu** [comment]
Probably your issue is the first pinned one: https://github.com/keepassxreboot/keepassxc/issues/10925

**Comment by michaelk83** [comment]
> KeepassXC is present in task bar

Sounds more like [screenshot security](https://keepassxc.org/docs/KeePassXC_UserGuide#_screenshot_security) on remote access.
