### ISSUE TITLE
Hidden Menubar and hidden Toolbar: Save impossible by shortcut key

### ISSUE THREAD

**Issue by teigaff** [keepassxreboot/keepassxc#11330]
## Overview
has problems with disabled menubar and toolbar. Saving by shortcut key is not possible.

## Steps to Reproduce
1. Menu bar | View | Show Menubar | Untick
2. Change an entry
3. Save database with keys: CTLR + S
4. Database is still not saved. Indicated by a star next to database filename in window

## Expected Behavior
Should be saved by key stroke whatever view I selected

## Workaround
I've to press the ALT key, then ESC, then the menubar is visible (why?). Then it is possible to save with key combo.

## Context
Version 2.7.9 in dark mode and in compact mode. Disabled Menubar and disabled Toolbar.

[NOTE]: #
KeePassXC - Version 2.7.9
Revision: 8f6dd13

[NOTE]: #
Operating System: Windows 10 22H2

**Comment by droidmonkey** [comment]
This is a qt limitation.  When you hide the actions you can't invoke them through keyboard shortcuts. This is by design generally speaking. Also a duplicate report.
