### ISSUE TITLE
Regarding the issue of errors in the Chinese translation of Keepssxc software

### ISSUE THREAD

**Issue by 14285758241** [keepassxreboot/keepassxc#11347]
Regarding the Keepassxc software, for Chinese language translation files, please click on the "Add New Entry", "Edit Entry", "Copy Username", "Copy Password", and "Copy URL" buttons on the software homepage panel. When the mouse moves over the button, the English introduction is displayed. We hope the translator can make changes and adjustments. Thank you very much for your hard work!

**Comment by droidmonkey** [comment]
Hello, that is done over at https://transifex.com/keepassxc/keepassxc
