### ISSUE TITLE
browser integration with multiple databases

### ISSUE THREAD

**Issue by IT-Dino** [keepassxreboot/keepassxc#11343]
## Summary
[NOTE]: At least under Debian and Brave with several databases, the automatic filling in of the access data only works if the correct tab (database) is active in keepassXC. A search “over all” would be desirable

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )

**Comment by droidmonkey** [comment]
Within keepassxc, go to application settings -> browser section -> checkbox for search within all open databases
