### ISSUE TITLE
Showing the next TOTP code in the last 5 seconds of the current

### ISSUE THREAD

**Issue by RomainPastureau** [keepassxreboot/keepassxc#11340]
## Summary
Hi! A cool feature that some Auth apps have is to show both the current TOTP code, and in little, below, the next code in the last 5 seconds of validity of the current code. This allows to start typing the next TOTP code when we know we wont have time to type in the current one.

## Examples
![TOTP](https://github.com/user-attachments/assets/65101ea3-69ce-4794-9efe-96671e0e09a7)

Thank you :)

**Comment by droidmonkey** [comment]
Thank you for the suggestion but we are not going to further complicate the totp presentation.
