### ISSUE TITLE
Can't copy text from preview note window

### ISSUE THREAD

**Issue by emoriver** [keepassxreboot/keepassxc#11348]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Copy text from note preview window
2. Paste elsewhere
3. Empty

## Expected Behavior
[NOTE]: Normal operation (as previous version)

KeePassXC - Versione 2.7.9
Revisione: 8f6dd13

Qt 5.15.11
La modalità debug è disabilitata.

Sistema operativo: macOS 12.7
Architettura CPU: x86_64
Kernel: darwin 21.6.0

Estensioni abilitate:
- Completamento automatico
- Integrazione browser
- Passkey
- Agente SSH
- KeeShare
- YubiKey
- Sblocco rapido

Librerie crittografia:
- Botan 3.1.1

**Comment by droidmonkey** [comment]
Fixed for next release
