### ISSUE TITLE
When navigating away from an active notes window and returning there is a prompt to save changes

### ISSUE THREAD

**Issue by Jayd603** [keepassxreboot/keepassxc#11345]
## Steps to Reproduce

1. View a note
2. Navigate away from keepass
3. Return and try to cancel out of the note

## Expected Behavior

Notes/edit entry window closes without prompt because it was not modified

## Actual Behavior

User is prompted if they would like to save changes even though there were none

KeePassXC - 2.7.9

Operating System: Ubuntu Linux 24.04 or 22.04

**Comment by droidmonkey** [comment]
What do you mean "view a note"?

**Comment by Jayd603** [comment]
> What do you mean "view a note"?

I mean when I double click on an entry and click on the eyeball icon to view a note.

So I guess that is technically editing an entry but no changes are made.  I use this method because of how many notes I keep and viewing them is easier when in edit mode when I have a ton of notes for something.

**Comment by droidmonkey** [comment]
Ok so you have "hide notes" enabled

**Comment by Jayd603** [comment]
> Ok so you have "hide notes" enabled

I do , but I just tested with hide notes disabled and it does the same thing so I don't believe it is related

**Comment by droidmonkey** [comment]
Is this happening on just one entry or every entry?

**Comment by Jayd603** [comment]
every

**Comment by droidmonkey** [comment]
I cannot replicate this at all. Can you take a video of the behavior?

**Comment by Jayd603** [comment]
[Screencast from 2024-10-10 21-25-40.webm](https://github.com/user-attachments/assets/7fcc7e2f-4d2f-4737-ae0a-49799c120ca1)

I am merely clicking on the notes box, i am not using the keyboard or modifying anything.  I do notice that if I don't click on the notes box at all, i don't get prompted.  ...but i have many pages of notes so it requires me to interact with the notes box to scroll pages or highlight and copy text frequently.   So I get prompted to save changes when none were actually made.

**Comment by Jayd603** [comment]
I also just noticed it takes two clicks to initially show a note in edit mode.  Bug or feature?

**Comment by droidmonkey** [comment]
I see the bug with the double click, that is an issue

**Comment by Jayd603** [comment]
The video shows what's happening.  I will test on my laptop too.   I am editing a note and changing nothing, but the act of highlighting something or moving the cursor within the text box makes keepass think it was modified.  So it prompts me to save changes.   This only happens after moving to another app window and returning to keepass.   ..or copying something from a keepass note and pasting it into a text editor etc.    That's probably the best way for you to try to recreate it.   copy some content from a keepass note while editing, paste it in a text editor, return to keepass and hit cancel, it should prompt you to save changes.

**Comment by droidmonkey** [comment]
I tried every possible way to replicate and cannot.

**Comment by Jayd603** [comment]
This is wild, so far I cannot reproduce it on my laptop.   Hmmmm

**Comment by Jayd603** [comment]
I figured it out, more so anyway, it works fine when I use the AppImage on both systems.  The desktop machine had the Ubuntu PPA version.   You would need to use that version.

**Comment by droidmonkey** [comment]
Can you confirm if you have any "Plugin Data" in the Properties tab of the entry?

**Comment by droidmonkey** [comment]
You may have something installed on the desktop machine that is typing stuff or cause some form of modification to occur when you click a textbox. That is the only explanation. PPA vs AppImage is not relevant unless there is a fundamental Qt bug at play here. Closing since this is clearly not a KeePassXC code issue.

**Comment by Jayd603** [comment]
Why be so quick to close this.   The Ubuntu PPA uses a different version of Qt ? why? Is it including a different version from the OS? Aren't they supposed to be the same?  Is the Ubuntu PPA an entirely different build?  Who maintains it.  If something is typing into textboxes why is the AppImage immune.   I run super clean machines so i doubt I have anything that sneaky on here.  I could install the PPA version on my laptop to see, which is an entirely fresh Ubuntu install.

**Comment by Jayd603** [comment]
I'm going to run the AppImage instead , I was just reporting the bug to help.   Perhaps it is a Qt bug

**Comment by droidmonkey** [comment]
there are too many permutations on Linux to make this worth "debugging". If it was an issue with our code then it wouldn't matter how you run/install keepassxc.

**Comment by Jayd603** [comment]
> there are too many permutations on Linux to make this worth "debugging". If it was an issue with our code then it wouldn't matter how you run/install keepassxc.

Ok I get that, part of what I do is DevOps and people come to me with help for some weird Linux distro and I tell them the same thing.   Ubuntu is probably the largest linux distro tho, is the PPA official from you or is someone else maintaining that?  Maybe just delist from the site and keep source/debian packages and AppImages only. idk

**Comment by droidmonkey** [comment]
The PPA is official from our other lead developer, I am just speculating on the Qt version

**Comment by droidmonkey** [comment]
I just installed the ppa version on Ubuntu 24 and couldn't replicate

Watching your video again, it looks like the Apply key gets activated when you switch windows, I assume by pressing ALT + TAB. I suspect you are actually typing a TAB into the notes when you do that for some reason. I couldn't replicate that behavior but that certainly looks like what is happening.

**Comment by Jayd603** [comment]
I actually was able to re-create it with my laptop with a fresh ubuntu 24 install using the PPA install.   I'm not using any keyboard actions at all.   All mouse or track pad in case of my laptop.  I open to edit note, copy something from it, switch windows to paste, go back and it thinks something was modified.  So, there is SOMETHING going on here and I don't think it's just me.  Not a big deal, great app and thanks for looking into it.  If I figure out why this is happening I will update this ticket/issue

**Comment by Jayd603** [comment]
Loaded up the PPA in Ubuntu 24.04 on virtualbox, same thing.   It's a bug some place, not necessarily with your code.

the vbox install is as bare as it gets

**Comment by Jayd603** [comment]
I know you are sick of this one but I had this happen once on your AppImage as well.   It took a lot of cutting pasting and messing around outside of Keepass, when I came back it prompted me despite no changes.  I also checked the "modified" line under properties for the entry and it was from earlier in the day so it did not record any modification I assume.

Just letting you know.
