### ISSUE TITLE
keepassxc.ini not included in 2.2.2 portable release

### ISSUE THREAD

**Issue by Maxime-J** [keepassxreboot/keepassxc#1134]
## Expected Behavior
keepassxc.ini should be included in portable releases so that the config is saved in the application directory.
It was like that before 2.2.2.

## Current Behavior
Because keepassxc.ini isn't present, the ini file is created outside the application directory.

**Comment by droidmonkey** [comment]
Yikes, this is my mistake. I will update the zip files tomorrow.

**Comment by phoerious** [comment]
Please add it as a new 2.2.2-2 binary as we did with the AppImage already. Otherwise we may break download scripts that have cached the check sums.

**Comment by droidmonkey** [comment]
I have updated the zip downloads (and added the -2)
