### ISSUE TITLE
GUI & layout issue in the preview panel

### ISSUE THREAD

**Issue by yan12125** [keepassxreboot/keepassxc#1135]
## Expected Behavior
The preview panel looks all the good

## Current Behavior
Some GUI & layout issues:
* Text truncated vertically (see the screenshot below)
* Font size mismatch between URL and other fields (see the screenshot below)
* When I hover around the URL field of the preview panel, the cursor is always a hand. IMO there's no need to change the cursor when the URL is empty
* I can't resize the preview panel. Only able to hide/show it. The cursor is changed when hovering around the border of the preview panel, but its size remains during dragging.

A screenshot:
![default](https://user-images.githubusercontent.com/1937689/32092197-fcec57c8-bb29-11e7-9ebc-a6105f226185.png)

## Possible Solution
Sorry, I'm not good at GUI stuffs.
I'm using Qt 5.10.0 beta 1. Maybe I can find time to build Qt 5.10.0 beta 2 and see if those are fixed.

## Steps to Reproduce (for bugs)
1. Create a database
2. Add an entry with an URL
3. Check the preview panel

## Context
I'm trying out that useful feature :)

## Debug Info
KeePassXC - version 2.2.2
Revision: 5718f3d, with my own patch [multiple-urls](https://github.com/yan12125/keepassxc/commit/9cf27efef9d41a2d3b2f27d59c6afe9a4bd1f74b)

Libraries:
- Qt 5.10.0 (5.10.0 beta 1 from [Arch Linux/KDE-Unstable](https://www.archlinux.org/packages/kde-unstable/x86_64/qt5-base/))
- libgcrypt 1.8.1

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 4.13.9-1-ARCH

Enabled extensions:
- KeePassHTTP
- Auto-Type
- YubiKey

Desktop environment: LXQt + KDE Breeze theme

Update: text truncation and font size mismatch are gone if I remove LXQt's theme plugin.

**Comment by TheZ3ro** [comment]
Can you try with Qt5.9 ?

**Comment by yan12125** [comment]
The panel presents similar issues with Qt 5.9.2.

Apparently this is because I use 18 as the default font size for Qt applications. (see the lxqt-qtplugin section in updated steps to reproduce). I managed to "fix" text truncation and font size mismatch by changing some lines:
```Diff
diff --git a/src/gui/DetailsWidget.ui b/src/gui/DetailsWidget.ui
index fb31409f..a4e897a5 100644
--- a/src/gui/DetailsWidget.ui
+++ b/src/gui/DetailsWidget.ui
@@ -7,7 +7,7 @@
     <x>0</x>
     <y>0</y>
     <width>630</width>
-    <height>200</height>
+    <height>300</height>
    </rect>
   </property>
   <property name="sizePolicy">
@@ -19,7 +19,7 @@
   <property name="maximumSize">
    <size>
     <width>16777215</width>
-    <height>200</height>
+    <height>300</height>
    </size>
   </property>
   <layout class="QVBoxLayout" name="verticalLayout_3">
@@ -228,7 +228,6 @@
              </property>
              <property name="font">
               <font>
-               <pointsize>9</pointsize>
                <weight>75</weight>
                <bold>true</bold>
               </font>
```

A screenshot with this change:
![image](https://user-images.githubusercontent.com/1937689/32110086-3d09e2fa-bb69-11e7-9b51-7ad3be738dc9.png)

**Comment by TheZ3ro** [comment]
Are you using an HighDPI screen?

**Comment by yan12125** [comment]
I believe not. Here are relevant info:
```
$ xdpyinfo | grep -B 2 resolution
screen #0:
  dimensions:    1920x1080 pixels (483x272 millimeters)
  resolution:    101x101 dots per inch

$ export | grep QT_
LXQT_SESSION_CONFIG=session
QT_IM_MODULE=fcitx
QT_PLATFORM_PLUGIN=lxqt
QT_QPA_PLATFORMTHEME=lxqt
```
I'm not quite sure how High DPI is configured in the kernel or X or Qt. Please tell me if you need more info.

**Comment by TheZ3ro** [comment]
If I set height to 300 this is what happen on my PC
![istantanea_2017-10-28_12-17-58](https://user-images.githubusercontent.com/686894/32133529-108ebafe-bbda-11e7-8277-82e8f5acb518.png)

Also in this comment https://github.com/keepassxreboot/keepassxc/pull/879#issuecomment-332670496 @droidmonkey can see the panel fine.

I think it's an HighDPI problem but I don't have a solution for it ATM

**Comment by frostasm** [comment]
@TheZ3ro I think it should be possible for the user to change the height of the panel. 
In the current implementation, on large monitors, we have too much empty space:  

![image](https://user-images.githubusercontent.com/3104366/32135327-bf5f683c-bc05-11e7-9a9c-2289ad5817e3.png)

**Comment by TheZ3ro** [comment]
I know. The fact is that we have to keep the layout nice on small monitors too.
If I set the panel size to 300 it takes more than half the default window size (un-maximized)

We can try using the `layoutStretch` but I don't know if it fixes the problem .

Any ideas are welcome

**Comment by frostasm** [comment]
@TheZ3ro I will try experimenting today with this problem ;)
