### ISSUE TITLE
How to solve the problem that the vpack package does not include dependencies when compiling VS2022 on windows10

### ISSUE THREAD

**Issue by code-horse** [keepassxreboot/keepassxc#11359]
## Summary
[TIP]: # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
The compilation and packaging commands are as follows
mkdir build
cd build
cmake -DWITH_XC_ALL=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=C:\vcpkg\scripts\buildsystems\vcpkg.cmake ..
cmake --build . --config Release
cpack

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )
The package has no dependencies, but all files are in the ./src/Release directory

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
Unable to package

Please help me, do I need to modify a certain configuration or how to do it, thank you.

**Comment by droidmonkey** [comment]
You need to add this to your cmake command run: `-DX_VCPKG_APPLOCAL_DEPS_INSTALL=ON`

You can also use the release-tool.ps1 to orchestrate a build/package effort: 
`./release-tool.ps1 -Build -Version 2.7.10 -Snapshot -Vcpkg "C:\vcpkg"`

**Comment by code-horse** [comment]
Thankyou
