### ISSUE TITLE
Ubuntu 24.04 upgrade leaves tray icon "elided"

### ISSUE THREAD

**Issue by b0bh00d** [keepassxreboot/keepassxc#11350]
## Overview
I recently upgrade my Ubuntu 22.04 LTS to 24.04.  When complete, the tray icon for KeePassXC now shows what I can only describe as an "elide" instead of the tray icon I had under 22.04.  I am in the process of upgrading numerous machines besides this one, and they are all resulting in the same behavior.  (Is this _supposed_ to be the new icon?)

## Steps to Reproduce
1. Upgrade Ubuntu 22.04 to 24.x with KeePassXC installed
2. 
3. 

## Expected Behavior
The tray icon would be the same as it was under Ubuntu 22.04

## Actual Behavior
The tray icon is literally "..." now.

## Context
![Screenshot from 2024-10-11 13-53-40](https://github.com/user-attachments/assets/3bb3777c-a8f2-4389-93e6-a5af3fc26eb4)

KeePassXC - Version 2.7.8
Revision: f6757d3
Distribution: Snap

Qt 5.15.11
Debugging mode is disabled.

Operating system: Ubuntu Core 22
CPU architecture: x86_64
Kernel: linux 6.8.0-45-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- Passkeys
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.19.1

Operating System: Linux (Ubuntu)
Desktop Env: Gnome (46)
Windowing System: X11

**Comment by droidmonkey** [comment]
That's not from us, you'll have to write a bug to gnome
