### ISSUE TITLE
Add filtering by custom attribute fields in list of entries.

### ISSUE THREAD

**Issue by ashed** [keepassxreboot/keepassxc#11366]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
Each entry must contain tab with custom attribute name.
Add filtering by custom attribute fields in list of entries.

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )

![KeePassXC-custom-attributes-2024-10-15-12-30-25](https://github.com/user-attachments/assets/bcfda13c-45a7-454a-8f2e-aeffec46330a)

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
Additional fields are need when adding a complicated entry. Filtering by these attribute fields is more reasonable than not filtering at all.

**Comment by droidmonkey** [comment]
Duplicate
