### ISSUE TITLE
KeePass starts from system start even if box not checked. 

### ISSUE THREAD

**Issue by trudK45** [keepassxreboot/keepassxc#11364]
## Overview
As the title says it's not possible to prevent keePass from starting from system start.

## Steps to Reproduce
1) Shut down PC
2) Start PC

## Expected Behavior
I am expecting KeePass not to start.

## Actual Behavior
KeePass starts.

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.6
Revision: dd21def

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 10
Desktop Env: ?
Windowing System: Windows

**Comment by droidmonkey** [comment]
There are many ways for an application to start on startup. You'll have to check them all. We implement the way from the registry, unchecking the setting removes the registry entry.

**Comment by droidmonkey** [comment]
See more here: https://www.howtogeek.com/74523/how-to-disable-startup-programs-in-windows/

**Comment by trudK45** [comment]
Ok, think I fixed it. Tanks droidmonkey,
