### ISSUE TITLE
OTP auxillary file for Android NFC use?

### ISSUE THREAD

**Issue by andmib** [keepassxreboot/keepassxc#1136]
This is more of a feature question, but I'm not sure how to mark it as such in the title.

How difficult would it be to allow KeepassXC to output an OTP auxillary file like some plugins do for KeePass (i.e. a .xml file). AFAIK, these files are necessary for utilizing challenge-response via NFC in the most popular KeePass apps on Android.

**Comment by phoerious** [comment]
This is probably a WONTFIX. our challenge response implementation is different for a reason and therefore incompatible. But KeePass2 Android might support our approach in the future. See #1060.
