### ISSUE TITLE
Quick Unlock expiration, configurable

### ISSUE THREAD

**Issue by DanEble** [keepassxreboot/keepassxc#11362]
## Summary
Configure a duration after which Quick Unlock is automatically canceled.  This is not an inactivity timer, but rather a forced fallback to normal unlock every so often.

## Context
I have two databases, one with less-sensitive secrets that I use frequently and protect with my login password, and another with more-sensitive secrets that I use less frequently and protect with a different password.  Quick Unlock is very convenient for the former; however, for the latter, it would be helpful to be forced to recall the password from time to time.  The timeout that I have in mind for my personal use is between 1 and 7 days.

**Comment by droidmonkey** [comment]
Duplicate request. We have chosen to not implement this until "remember quick unlock" is implemented.

**Comment by DanEble** [comment]
Thanks.  Is there a ticket I can follow for that?  I searched open tickets tagged "feature: QuickUnlock" and none stood out to me.

**Comment by droidmonkey** [comment]
https://github.com/keepassxreboot/keepassxc/issues/8013

It was missing the label, which i just added
