### ISSUE TITLE
Unable to start Keepass on Windows desktop

### ISSUE THREAD

**Issue by AltusForm** [keepassxreboot/keepassxc#11370]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
I'm unable to start keepass on a windows desktop

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Click on KeepassXC
2. Nothing happen
3. 

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
KeepassXC starts

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Nothing

## Context
[NOTE]: # ( Give us any additional information you may have. )
I tried 3 installation + 1 more download and installation. Computer being restarted each time. Windows 10.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION 2.7.9
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows
Windowing System: X10

**Comment by droidmonkey** [comment]
https://github.com/keepassxreboot/keepassxc/issues/10925

**Comment by AltusForm** [comment]
Thanks @droidmonkey, working properly
