### ISSUE TITLE
Pouvoir imprimer un document

### ISSUE THREAD

**Issue by alain-pouc** [keepassxreboot/keepassxc#11375]
Bonjour

Dans KeepassXC, il est possible d'exporter en CSV, XML et HTML

J'utilise KEEPASS mais j'aime bien avoir de temps à autre une liste propre et nette au format papier. Je connais les procédures d'exportations mais ce n'est pas forcément l'idéal.

CSV : on peut obltenir un fichier EXCEl que l'on détruit pas la suite mais il est juste facile d'obtenir une lite en tableau imprimable bien sur mais ce n'est pas l'idéal.

XML : très dfficiel de faire des impressions avec ce format

HTML : possibilité de reprendre par un traitement de texte ... mais il est impossible de faire une mise en page correcte pour un tas de raisons.

.... il va de soit que quand j'imprime je fais une destruction du fichier d'impression après l'impression.

Serait il possible d'imaginer un menu d'impression au format PDF par exemple ?

Merci

Cordialement

-‐--------‐--

Good morning

In KeepassXC it is possible to export to CSV, XML and HTML

I use KEEPASS but I like to have a clean, crisp list in paper format every now and then. I know the export procedures but it is not necessarily ideal.

CSV: we can obtain an EXCEI file that we do not destroy afterwards but it is just easy to obtain a lite printable table of course but this is not ideal.

XML: very difficult to print with this format

HTML: possibility of resuming by a word processor... but it is impossible to make a correct layout for a lot of reasons..... 

it goes without saying that when I print I destroy the print file after printing.Would it be possible to imagine a print menu in PDF format for example?

**Comment by droidmonkey** [comment]
Hello, we are not adding any more export formats. We added HTML for the purposes of printing. If you want a table view, you use CSV. You are free to format it how you please prior to printing.

**Comment by michaelk83** [comment]
> Would it be possible to imagine a print menu in PDF format for example?

You can print to PDF independently of KeePassXC.
https://www.howtogeek.com/666835/how-to-print-to-pdf-on-windows-10/
https://askubuntu.com/questions/81817/how-to-install-a-pdf-printer
