### ISSUE TITLE
I can't install the MSVC Redistributable on my computer

### ISSUE THREAD

**Issue by davidleongz** [keepassxreboot/keepassxc#11374]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
I can't install the MSVC Redistributable on my computer, has anyone had this issue?

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Install KeePassXC-2.7.9-Win64
2. 
3. 

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Open de program

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
I can't open the program

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows/Linux/macOS
Desktop Env: Gnome/KDE/XFCE/Mate/Cinnamon
Windowing System: X11/Wayland

**Comment by droidmonkey** [comment]
It's available here: https://aka.ms/vs/17/release/vc_redist.x64.exe

**Comment by davidleongz** [comment]
> It's available here: https://aka.ms/vs/17/release/vc_redist.x64.exe

My computer won't let me install the program, and my question is if anyone knows why I can't install it. My issue is not about finding where the executable file is

**Comment by phoerious** [comment]
You need to install it with admin rights.

**Comment by davidleongz** [comment]
I have this message, and I don't know why. I'm running it with administrator rights
![image](https://github.com/user-attachments/assets/f3e00f74-26b3-4ccd-9fdf-6889ff7fe336)

**Comment by phoerious** [comment]
Are you running ARM or so?

**Comment by davidleongz** [comment]
No, I'm running it on Windows 11 with System Type x64
