### ISSUE TITLE
KepePassXC Snapshot crashes when trying to show a history element of an entry

### ISSUE THREAD

**Issue by sahriVoraus** [keepassxreboot/keepassxc#11371]
## Overview
Program crashes when trying to show a history element. Seems to happen for every element so far and I tested it with two databases

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. open entry
2. navigate to history
3. double click on any history entry or click on button "Show"

## Expected Behavior
Entry is shown

## Actual Behavior
KeePassXC crashes

## Context

KeePassXC - Version 2.8.0-snapshot
Build Type: Snapshot
Revision: 4f8c204

Qt 5.15.11
Debugging mode is disabled.

Operating system: Windows 11 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.22631

Enabled extensions:
- Auto-Type
- Browser Integration
- Passkeys
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 3.1.1

**Comment by droidmonkey** [comment]
Ooof good catch, this is another ASSERT hit and we are missing this as a unit test as well clearly.
