### ISSUE TITLE
Add the ability to delete custom favicon entries

### ISSUE THREAD

**Issue by Tritonet** [keepassxreboot/keepassxc#11377]
Personally, I have not been able to find where to delete custom favicons.

## Summary
The ability to add custom favicons is a great feature for visually identifying entries quickly in the database. However, there is currently no option to remove these custom favicons once added. I would like to request a feature to delete custom favicon entries to keep the database clean and avoid retaining incorrect or outdated icons.

## Examples
A mock-up could illustrate the favicon section of an entry with a new "Delete" button next to the custom favicon field. If the deleted favicon is associated with a database entry, it should display a default icon.

## Context
As someone who frequently updates or corrects entries in the KeePassXC database, I often upload custom favicons to quickly identify them. However, without the ability to remove outdated or incorrect favicons, these icons remain stored unnecessarily, cluttering the database and sometimes causing confusion. The ability to delete these custom favicons would help maintain a cleaner, more organized database.

Thank you in advance for considering the implementation of this new feature in one of the upcoming updates.

**Comment by droidmonkey** [comment]
https://keepassxc.org/docs/KeePassXC_UserGuide#_database_maintenance
