### ISSUE TITLE
AutoType is not working - mac + chrome

### ISSUE THREAD

**Issue by mbn18** [keepassxreboot/keepassxc#11376]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. create record for: `https://start.telebank.co.il/login/#/LOGIN_PAGE`
2. Add attribute name `CODE`
3. Use custom auto-type sequence -> `{USERNAME}{TAB}{PASSWORD}{TAB}{S:CODE}{ENTER}`

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

Expect all fields to be filled with proper information

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

Only the first two fields are filled like the sequence is: `{USERNAME}{TAB}{PASSWORD}{ENTER}`

## Context
[NOTE]: # ( Give us any additional information you may have. )

I played with the sequence like changing to `{S:CODE}{TAB}{PASSWORD}{TAB}{S:CODE}{ENTER}`
Reopened the chrome browser or KeepassXC itself.
Tried to call auto fill directly from `KeepassXC` and from the browser.
Nothing changes.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.9
Revision: 8f6dd13

Qt 5.15.11
Debugging mode is disabled.

Operating system: macOS 15.0
CPU architecture: arm64
Kernel: darwin 24.0.0

Enabled extensions:
- Auto-Type
- Browser Integration
- Passkeys
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 3.1.1

Chrome integration version: 1.9.3

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS - Sequoia 15.0.1

**Comment by droidmonkey** [comment]
Are you using actual auto-type or the browser extension? It's a common mistake, so I have to ask.

**Comment by droidmonkey** [comment]
This works absolutely fine for me.
