### ISSUE TITLE
[macOS] Application exits when the window is closed

### ISSUE THREAD

**Issue by mortie** [keepassxreboot/keepassxc#11388]
## Overview

This has been reported before (https://github.com/keepassxreboot/keepassxc/issues/869), but that issue is closed, yet the problem remains (or maybe it has been re-introduced since 2017).

On macOS, closing an applicaton's window is supposed to keep the application running. Cmd+W is supposed to close the window, cmd+Q is supposed to close the application. These are universal rules which pretty much every Mac application follows, and any application which doesn't very clearly stands out.

In KeePassXC 2.7.9, these rules are not followed:

* Cmd+W closes the database instead of the window
* Closing the window with the "x" button in the top left exits the application instead of closing the window

Both are problems, but this issue primarily concerns the latter.

This problem is significant because browser integration does not work while the program is not running. Following Mac conventions, it ought to be possible to close the window but keep the application running and serve the browser plug-in.

Minimizing the window is not the same as closing the window, because when minimizing the window, the window still exists and takes up space in the dock.

## Steps to Reproduce

1. Open KeePassXC 2.7.9 on macOS
2. Click the X button in the top left corner

## Expected Behavior

The window closes, but the application keeps running in the background

## Actual Behavior

The application exits

## Context

KeePassXC - 2.7.9
Revision: 8f6dd13

Operating System: macOS

**Comment by droidmonkey** [comment]
Hi, we have settings that enable the behavior you desire. In order to keep our application running in the background to serve browser, while also not taking up dock space, you need to enable the tray icon. You can then also decide if pressing the X button minimizes to tray or closes the application. This allows for both behaviors for people who prefer one or the other.

**Comment by droidmonkey** [comment]
Also for cmd+w: https://github.com/keepassxreboot/keepassxc/issues/6837

**Comment by mortie** [comment]
I'm happy to see that KeePassXC can be configured to work properly, however I am disappointed that the buggy behavior remains the default.

**Comment by droidmonkey** [comment]
It's consistent for us across all three platforms.

**Comment by mortie** [comment]
Yes that's the problem
