### ISSUE TITLE
All My Groups Were Gone

### ISSUE THREAD

**Issue by theskydivingnerd** [keepassxreboot/keepassxc#11386]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

This IS A BUG !!!  Please do not close this as user error.

Had been using KeePassXC for several months.
Today I opened it and only the Entries window was visible showing only the entries for the Root group.
I initally thought all my subgroups and entries had somehow been deleted or the database was corrupt.

I found bug report 11074 and was able to resize the Groups, Tags and Preview partitions.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. The only thing different from all the previous times I opened KeePassXC is that the night before I changed my settings by selecting "Minimize window on application startup" and "Automatically launch KeePassXC at system startup".  However, keeping these things selected and restarting the application did not reproduce the problem.  (I have not tried restarting my system yet.)
2. 
3. 

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Expected to see all partitions as they had all been visible when opening the application prior to today.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Only root group entries were visible as the Entries partition was the only partition visible.

## Context
[NOTE]: # ( Give us any additional information you may have. )
I am planning on using KeePassXC to demonstrate the benefits of using a password manager to a spring semester class of lifelong learners.  As most only have limited sophistication with using computers, if they were to encounter an issue like this they would not know how to search for and find a resolution to it.  Perhaps a "Restore default layout" selection under the View menu (in addition to fixing the bug) in case they inadvertantly resize a partition to the point where it is no longer visible would be very beneficial.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION 2.7.9
Revision: REVISION 8f6dd13

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows/Linux/macOS  Windows 10 Vresion 2009
Desktop Env: Gnome/KDE/XFCE/Mate/Cinnamon
Windowing System: X11/Wayland

**Comment by droidmonkey** [comment]
This has been fixed for the next release. https://github.com/keepassxreboot/keepassxc/issues/10927 and #11014
