### ISSUE TITLE
Mainform UI

### ISSUE THREAD

**Issue by bigalgeorge** [keepassxreboot/keepassxc#1138]
Basic Settings:
[x] Confirm prompt (eg delete entry)

**Comment by phoerious** [comment]
Would you care to elaborate more?

**Comment by bigalgeorge** [comment]
Expert users dont want the confirm delete dialog - its the same as the old windows settings or caja settings; removes the dialog shown here:
![screenshot](https://user-images.githubusercontent.com/6935387/32964217-57864838-cc37-11e7-9d56-f2938e78826b.png)
