### ISSUE TITLE
Added Additional Attributes in “Advanced” Show Up Only after Reopening the DB

### ISSUE THREAD

**Issue by moontan** [keepassxreboot/keepassxc#11380]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

Note: I just came across this for the first time, so I am uncertain as for how reproduceable this is.
After setting up TOTP for one entry, it is impossible to add more additional attributes in the “advanced” section.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Create an entry.
2. Set up TOTP for the entry. (I did so via the context menu right-clicking on the list item in the app's opening view)
3. Open the entry and pick “Advanced” in its side bar.
4. Click on the “Add” button.
5. Watch the OTP entry get deselected but not much else happen.
6. Close and reopen your database.
7. Open the previously created entry and go to “Advanced”
8. Watch the additional attributes finally get displayed in the list.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
I expected a new additional attribute to show up under the OTP entry instantly, rather than after reopening the DB.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
The only entry in the additional attributes list gets deselected. Nothing else happens then until I close and reopen the DB. Only then will the added attributes appear.

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION 2.7.9
Revision: REVISION 8f6dd13

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS 15.0.1
Desktop Env: 
Windowing System:

**Comment by droidmonkey** [comment]
You'll have to supply a video showing this behavior because I cannot replicate it at all. The code for attributes and TOTP has not changed in many years.

https://github.com/user-attachments/assets/304829b1-0588-4367-bc6f-cc235d7333a6

**Comment by moontan** [comment]
Sorry for the late reply, the notification email for your response went to my spam box for some reason. So … the issue occurred two times that I witnessed with my own eyes, the first of which I didn't think it was worth opening an issue for. I'll see what I can do regarding the video, and try reproducing it in an empty dummy db, but if it turns out to be file-specific, meaning that it can only be reproduced in the one particular database that I had open, I'll need to take some time and think of ways to scramble my personal data before sharing this content.
