### ISSUE TITLE
Search shortcut (ctrl+f) doesn't work on keyboard layout different from English

### ISSUE THREAD

**Issue by lansman** [keepassxreboot/keepassxc#11382]
## Overview
Search shortcut (ctrl+f) doesn't work on keyboard layout different from English

## Steps to Reproduce
1. Open KeePassXC Window
2. Switch your keyboard to some layout different from EN (RU for example)
3. Press ctrl+f (cmd+f on mac)

## Expected Behavior
Focus should switch to the Search field above, as it happens on EN layout

## Actual Behavior
Focus doesn't switch, it remains wherever it was

## BTW
Other shortcuts (copy username ctrl+b, copy password ctrl+c) work fine

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION 2.7.9

Operating System: macOS

**Comment by droidmonkey** [comment]
We use Qt's definition for the "find" shortcut which may be platform and language specific. 2.8.0 will let you remap keys so this is already completed from development perspective. 

https://github.com/keepassxreboot/keepassxc/blob/95bae8377c88f46fda565e09fee25d7ba684fe9e/src/gui/MainWindow.cpp#L115

**Comment by lansman** [comment]
@droidmonkey cmd+f works in both layouts in all programs on my Mac without issue. 
For example, QBittorrent is written on QT too and both layouts work just fine.

Could you add a second layout on your pc and test it?

**Comment by droidmonkey** [comment]
You can also press F3 to focus search. I'm not disputing it's broken, just that we already implemented a fix/workaround.

**Comment by lansman** [comment]
I've downloaded a KeepassXC for Windows, and both shortcuts work fine there.
There is some mac-specific problem here.

F3 works, thank you for workaround.

I hope remap feature will allow adding another shortcut for search without breaking existing EN one.

**Comment by droidmonkey** [comment]
It's likely a qt bug in that case
