### ISSUE TITLE
[call for donations] - search in Notes field

### ISSUE THREAD

**Issue by wwwurst** [keepassxreboot/keepassxc#11387]
## Summary
I am well aware that this topic has been discussed and rejected several times, and lots of arguments for it have already been made. I will try a fresh approach here.

Typing a search string into the search field will return all entries in which this string was found (even if it was only found in the Notes section). But currently there is no way to locate the hit(s) in the Notes, which becomes a nuisance when a lot of text is stored there.

## Proposal
I would be willing to commit to a donation of €10.- even for the most rudimentary functional extension of the search function: to have an option (off by default) to highlight the search hits inside the Notes field. I'd up it to €15.- for additonal "next/previous hit" buttons.

## Request
To fellow users: please reply with your donation pledges in case you're as desparate for this functionality as I am.
To the author: please keep this open for a while (two weeks?) to judge the feedback. From the previous discussions, I could never make out why you are so adamantly dismissing such requests - maybe an explanation would make us finally shut up for good...

thanks for this great piece of software!

**Comment by droidmonkey** [comment]
Thank you, but we don't do donations for specific features

#4864
