### ISSUE TITLE
JPEG XL support for icons

### ISSUE THREAD

**Issue by DancingEmptier667** [keepassxreboot/keepassxc#11390]
## Summary
Add support for using .jxl images for icons.

## Examples
.jxl images are small in size with minimal loss in quality. This can be a great option for use as icons.

## Context
JXL is a modern, up-and-coming format that lacks software support. The more programs like KeePassXC add support for the format, the more attractive it will become to the end-user.

**Comment by phoerious** [comment]
This is a wontfix for us. We rely on Qt to provide support for image formats. If Qt(6) decide to add support for it, KeePassXC will get it automatically. If not, then KeePassXC won't have it either.

**Comment by droidmonkey** [comment]
Not sure why yet another image format is needed tbh, especially for icons. Either way icons are stored as png internally so the starting format is irrelevant.
