### ISSUE TITLE
database locking icon is wrong

### ISSUE THREAD

**Issue by ticmaisdev** [keepassxreboot/keepassxc#11396]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

database locking icon is wrong

![image](https://github.com/user-attachments/assets/2f1b052d-746c-4d5f-ac3d-91af433c728a)

I'm pretty sure "copy password" button has gotten "lock database" button's icon.

**Comment by droidmonkey** [comment]
Holy wow that's an old KeePassXC. You need to update.
