### ISSUE TITLE
Minimizing options don't seem to work on qt-wayland?

### ISSUE THREAD

**Issue by tpaniaki** [keepassxreboot/keepassxc#11391]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

I'm using Qtile on wayland and would like to enjoy the option to start keepassxc minimized. However, all minimizing options don't work.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Qtile / wayland
2. Check in settings you'd like the app to be opened minimized.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
The app starts minimized (background process). 

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
The GUI is not minimized.

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )

KeePassXC - Version 2.7.9
Revision: 8f6dd13

Qt 5.15.15
Debugging mode is disabled.

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 6.11.4-arch1-1

Enabled extensions:
- Auto-Type
- Browser Integration
- Passkeys
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: None
Windowing System: Wayland

**Comment by droidmonkey** [comment]
Do any qt apps minimize properly?

**Comment by tpaniaki** [comment]
I don't have a qt app offering to minimize itself at a certain point. 

Ideally, an argument such as` --background`  (`keepassxc --background`) would be useful for picky non-DE users.

**Comment by droidmonkey** [comment]
I don't know much about qtile, but I installed it and replicated the behavior. However, I don't think this is on us and I suspect you either need to adjust the qtile config to enable minimized windows on startup or simply enable the tray icon which allows this to work right away. We won't be making any code adjustments here.

See also #4507

**Comment by funnes** [comment]
I can reproduce this on sway. The `--minimized` argument also does not seem to do anything.

edit: it works after enabling the tray icon in the settings.
