### ISSUE TITLE
Display Username and Email Together in Entry View

### ISSUE THREAD

**Issue by 8ullyMaguire** [keepassxreboot/keepassxc#11392]
Currently, KeePassXC displays the username in the main entry view, but I often store the email address in the notes section. I sometimes forget that I've stored the email there since I can't see the content of the notes by default. This can be inconvenient when I need to quickly identify which email address is associated with a particular account, such as when receiving verification codes or other messages from websites. For accounts that use email to log in, I simply save the email as the username.

**Feature Request:**
Add an "Email" field to the main entry view, alongside the existing Username field.

**Optional:**
- Provide an option in the settings to toggle the visibility of this Email field in the main entry view.
- If an email address is detected in the notes section, automatically populate this new Email field.

Alternatively, consider adding a setting to show the notes by default, allowing users to quickly see whether they've written the email address there.

As a workaround, I've thought about writing the email in the title or include it in parentheses alongside the username. Or, in Security, deactivate "Hide entry notes by default".

**Comment by droidmonkey** [comment]
Notes are shown by default. You can also search notes using `n:admin@email.com`

To show the notes column again, right click the entry view header and select notes. 

This duplicates entry layout templates
