### ISSUE TITLE
Install KeepassXC browser extention on chrome offline

### ISSUE THREAD

**Issue by azntuan86** [keepassxreboot/keepassxc#11395]
## Summary
We need to use for one of our project your application extension for chrome.

## Context
We need to install it offline as there is no internet on the location where we need to deploy this application, do you have any procedure to install it offline?

**Comment by droidmonkey** [comment]
Same as any other extension, but the catch is you need to add the custom chrome extension id to the json configuration file for native messaging. 

https://developer.chrome.com/docs/extensions/how-to/distribute/install-extensions

See structure of json files here: https://github.com/keepassxreboot/keepassxc-browser/wiki/Native-messaging-script-files

**Comment by azntuan86** [comment]
Hello,

 

Thank you, I'll try it now.

As it's a windows client, it's only the regedit method to be use right?

 

Kind Regards,

 

Tuan-Anh Vuong

IT Team

Zetes Belgium

____________________________________

ZETES BE- Rue de Strasbourg 3, 1130 Brussels

Tel: +32 2 728 37 11 --- Fax: +32 2 728 37 19

Direct: +32 2 702 41 76

VAT BE0408425626 --- Email:  ***@***.***> ***@***.***

____________________________________

 <http://www.zetes.be/> WWW.ZETES.BE | ALWAYS A GOOD ID 

  <http://www.facebook.com/pages/Zetes/131228870275240>
<http://twitter.com/#!/ZetesIndustries>
<http://www.linkedin.com/groups?gid=3772653>
<http://www.youtube.com/user/ZetesGroup> 

# Do not print this e-mail unless absolutely necessary #

Use our new support system: send an email with your helpdesk requests to
***@***.***> ***@***.*** or connect to
<https://sdp.zetes.com/> https://sdp.zetes.com/

 

 

From: Jonathan White ***@***.***> 
Sent: 22 October 2024 15:03
To: keepassxreboot/keepassxc ***@***.***>
Cc: Tuan Anh Vuong ***@***.***>; Author
***@***.***>
Subject: Re: [keepassxreboot/keepassxc] Install KeepassXC browser extention
on chrome offline (Issue #11395)

 

	
You don't often get email from ***@***.***
***@***.***> . Learn why this is important
<https://aka.ms/LearnAboutSenderIdentification>  

	

CAUTION: This email originated from outside of the organization. 
Do not click links or open attachments unless you recognize the sender and
you expect to receive them.
When in doubt, please report to CSIRT via the Report Message > Phishing
button. 

 

Same as any other extension, but the catch is you need to add the custom
chrome extension id to the json configuration file for native messaging.

https://developer.chrome.com/docs/extensions/how-to/distribute/install-exten
sions
<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdeveloper
.chrome.com%2Fdocs%2Fextensions%2Fhow-to%2Fdistribute%2Finstall-extensions&d
ata=05%7C02%7Ctuananh.vuong%40be.zetes.com%7Ce39da4801eed4bb60d3e08dcf299e29
c%7Cf92badf4a21b4ddbbae600e040c26fb8%7C0%7C0%7C638651989972725114%7CUnknown%
7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn
0%3D%7C4000%7C%7C%7C&sdata=3mhlYPcpCIveL9nuxGLnrSUS7ZilKzrtBWWfztP1YG0%3D&re
served=0> 

See structure of json files here:
https://github.com/keepassxreboot/keepassxc-browser/wiki/Native-messaging-sc
ript-files
<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.co
m%2Fkeepassxreboot%2Fkeepassxc-browser%2Fwiki%2FNative-messaging-script-file
s&data=05%7C02%7Ctuananh.vuong%40be.zetes.com%7Ce39da4801eed4bb60d3e08dcf299
e29c%7Cf92badf4a21b4ddbbae600e040c26fb8%7C0%7C0%7C638651989972765993%7CUnkno
wn%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI
6Mn0%3D%7C4000%7C%7C%7C&sdata=VHKgZHl53darc%2BLev6YEFppnqaeLhXN3ccdYcgjP11o%
3D&reserved=0> 

-
Reply to this email directly, view it on GitHub
<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.co
m%2Fkeepassxreboot%2Fkeepassxc%2Fissues%2F11395%23issuecomment-2429228777&da
ta=05%7C02%7Ctuananh.vuong%40be.zetes.com%7Ce39da4801eed4bb60d3e08dcf299e29c
%7Cf92badf4a21b4ddbbae600e040c26fb8%7C0%7C0%7C638651989972805284%7CUnknown%7
CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0
%3D%7C4000%7C%7C%7C&sdata=K77UMKl8C8qaPZrGUZqkUDm1T3pZL1SJX6yNyGdnmLg%3D&res
erved=0> , or unsubscribe.
You are receiving this because you authored the thread.
<https://github.com/notifications/beacon/BMKQEB7YM37WJRTL63GIOL3Z4ZEI7A5CNFS
M6AAAAABQMNOYLWWGG33NNVSW45C7OR4XAZNMJFZXG5LFINXW23LFNZ2KUY3PNVWWK3TUL5UWJTU
QZMLOS.gif> Message ID:
***@***.***
***@***.***> >

**Comment by droidmonkey** [comment]
You won't need to touch the registry. The registry points to a json file in your profile: %APPDATA%/KeePassXC
