### ISSUE TITLE
Snap version outdated

### ISSUE THREAD

**Issue by milux** [keepassxreboot/keepassxc#11397]
## Summary
The most recent version (2.7.9) of KeePassXC is not available via the "stable" channel when installed via snap.
For some reason, the latest release is however available on the "beta" channel.
Could you please bump the "stable" channel accordingly?
Unless, of course, there is some non-obvious reason (bug?) preventing the latest release to be promoted to the "stable" channel.

Kind regards and thanks for your great work. (:

**Comment by droidmonkey** [comment]
The snap people need to manually approve the release and they haven't. I've frankly given up on snap
