### ISSUE TITLE
Donate - how?

### ISSUE THREAD

**Issue by bigalgeorge** [keepassxreboot/keepassxc#1140]
When I follow from [https://keepassxc.org/](https://keepassxc.org/) [Donate Flattr] 
[https://flattr.com/submit/auto?fid=x7yqz0&url=https%3A%2F%2Fkeepassxc.org](https://flattr.com/submit/auto?fid=x7yqz0&url=https%3A%2F%2Fkeepassxc.org)
to contribute small amount, it takes me to a login and developers resource. Is this the intention - you dont want financial contributions?
Even a Paypal link would be fine for any donors.

**Comment by phoerious** [comment]
We have a PayPal link on our Website now. Please go to https://keepassxc.org/donate.

**Comment by bigalgeorge** [comment]
Hmm, I wouldnt donate to this pseudo Paypal account. Its certainly nothing like I am used to
[https://imgur.com/Dr8opeB](https://imgur.com/Dr8opeB)

**Comment by phoerious** [comment]
We are not an organization or legal entity, so we have to use our names as individuals.

**Comment by bigalgeorge** [comment]
and got Asian script across page. Are you sure this is a trustworthy link; I suggest you make it standardised otherwise it wont be used.

**Comment by phoerious** [comment]
Must be a bug, for me it's English. The link points to PayPal. Check the TLS certificate.

**Comment by bigalgeorge** [comment]
No what Im insisting is because others do not know about the language select see below it gets from bad to worse when I actually click an unknown button:
https://imgur.com/Xi0vgEj[https://imgur.com/Xi0vgEj](url)

**Comment by bigalgeorge** [comment]
As a retired author, I found I hardly got many donations for my freeware but over the years it pays for the odd beer or two!

**Comment by phoerious** [comment]
Well, I can't do anything about that. I suppose PayPal detected your browser or IP address as Japanese somehow. This is not a third-party website, but actually PayPal (paypal.me is PayPal's send-me-money domain).

**Comment by bigalgeorge** [comment]
OK thats pretty odd after using both browsers with same results. Suggest you get a mate in another country to check it too. I changed the language in 1st screen but seconds screen always comes up Jappo. Lets know if anyone else confirms this. ANYONE WANT TO DONATE?

**Comment by phoerious** [comment]
Tested it with proxies in various countries and except for a Swedish server, always got the correct language.
And BTW I have already received money through this link several times. You can check it's TLS certificate to confirm that it belongs to PayPal.

**Comment by TheZ3ro** [comment]
Using my a VPN it's English. Using my main connection is Italian (i'm italian). Using my phone is English.

**Comment by bigalgeorge** [comment]
After change language on phone it worked OK but on desktop with both browsers it didnt; kept  going to Jap screen for payment.

**Comment by phoerious** [comment]
I received your donation. Much appreciated, thanks!
