### ISSUE TITLE
Keep auto-type window open when using a right click action

### ISSUE THREAD

**Issue by s-h-a-d-o-w** [keepassxreboot/keepassxc#11402]
## Summary
As the title says - it would be great if doing anything from the right click menu wouldn't close the window.

## Context
At the moment, any action taken anywhere in the window immediately closes it, requiring using the hotkey twice when dealing with websites that have multi-step logins.
Aside from reducing annoyance with multi-step logins, I believe that this would also match intuitive expectations better. While I expected it to close when clicking the button at the bottom or choosing something from the dropdown there, as well as double clicking an item, I was surprised that it also closes on right click actions.

**Comment by droidmonkey** [comment]
Unlikely to implement this as that will infuriate other users that expect the window to go away (myself included). I do not want to introduce _yet another option_ either. Your best bet is to define a custom auto-type sequence for often used forms. Multi-step logins can be taken care of with delays between actions for the most part. Also, we implemented the "select the last used entry within XX seconds" to alleviate the pain of finding it again.
