### ISSUE TITLE
AnyDesk not displaying KeePassXC window

### ISSUE THREAD

**Issue by ev-nut** [keepassxreboot/keepassxc#11403]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

BRIEFLY: Using KeePassXC via AnyDesk results in display problems on local AnyDesk client.

At first glance it sounds like an AnyDesk fault, but practically every other operation I am doing on the Remote -- across a variety of apps -- shows no issue and performs as expected.  Is this possibly a PRIVACY or SECURITY FEATURE of KeePassXC to not display content accessed remotely ?

DETAILS:

Logging from LOCAL into a REMOTE desktop -- both Win11 -- using AnyDesk 8.1.0.  Behaves as expected until I launch KeePassXC on the Remote (version 2.7.8).  The main window does not show up on the client (local), but does show on the Remote.  Interestingly, putting local & remote into the s  ame room and watching my actions done on local on the remote's monitor ... to find the version of KeePassXC ... I moved the cursor to the the Help field in the menu bar, and suddenly the SUB-Menu is displayed on the local -- meaning I was able to select the About option without looking at the remote's monitor.  However, although the expected Help-About window popped up on the Remote ... it was not being displayed on the local !

The **_tool-tips_** (OpenDatabase, SaveDatabase, LockDatabase, etc) also display on the local, but not the resulting window when clicking on those actions.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1.  Already described above.  See above for description of steps I performed.
2. 
3. 

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

Like all other apps launched on the Remote behaving properly and being displayed on the local.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

KeePassSC 2.7.8 does not show on the local client using AnyDesk.

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows/Linux/macOS
Desktop Env: Gnome/KDE/XFCE/Mate/Cinnamon
Windowing System: X11/Wayland

Win11 Pro (x86) on Remote, Win11 Home on Snapdragon (ARM64) on local.

**Comment by droidmonkey** [comment]
https://keepassxc.org/docs/KeePassXC_UserGuide#_screenshot_security

**Comment by ev-nut** [comment]
> https://keepassxc.org/docs/KeePassXC_UserGuide#_screenshot_security

Thank you ... makes sense :-)
