### ISSUE TITLE
I am unable to open the database after changing the password.

### ISSUE THREAD

**Issue by Vasef-Stack** [keepassxreboot/keepassxc#11411]
I am unable to open the database after changing the password. I enter both the password and the key file correctly, but it gives error.
I checked everything, everything is absolutely correct
If the ability to change the password does not work properly and causes file corruption, remove this malicious feature.

Error message displays: "Error while reading the database: Invalid credentials were provided, please try again.
If this reoccurs, then your database file may be corrupt. (HMAC mismatch)"

What should I do now?

system: win11
KeePassXC 2.7.8

**Comment by droidmonkey** [comment]
Try your old password or also try removing the key file from the unlock dialog in case you accidently removed that when you changed your password. This feature works fine so there is a 99.9% chance you typed it wrong when you changed it or when you went to unlock.

If you have a backup or version history of your database file you can go back to the old password version. If you enabled database backup on save then you can open the xxxx.kdbx.old file.
