### ISSUE TITLE
KeepassXC 2.7.9 is always on top with macOS Sequoia

### ISSUE THREAD

**Issue by iteixido** [keepassxreboot/keepassxc#11412]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
On MacOS, with the options:
- Minimize instead of app exit
- Show a system tray icon
- Hide window to system tray when minimized

The app always stays on top of other windows. For example, I can't switch to other applications with cmd + tab. I have to close the app.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
Enable the options:
- Minimize instead of app exit
- Show a system tray icon
- Hide window to system tray when minimized

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.9

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS Sequoia

**Comment by droidmonkey** [comment]
You probably enabled always on top, go to view menu and turn it off. Those settings don't have anything to do with your observation

**Comment by iteixido** [comment]
OMG! That is. Thank you and sorry for the inconvenience.
