### ISSUE TITLE
Share with group (folder)/subgroups (subfolder)

### ISSUE THREAD

**Issue by RonnyB1978** [keepassxreboot/keepassxc#11423]
## Summary
It would be nice, when KeeSHARE works also with subgroups
![Folder+Subfolder](https://github.com/user-attachments/assets/55f8dbaa-c083-4f95-94c4-3d621118f0ec)
![Shared_database](https://github.com/user-attachments/assets/b52dce0c-caa7-455e-a4f4-fe4cb1f90d81)

## Examples
To have a bit more structure, I have a group for my wife. I would like to share this group, which works well, BUT no entry has a group any more. What do I mean?
MY DATABASE
Group
Wife (I want to share with synchronisation)
-> Window
Entry 1
Entry 2
-> NAS
-> Synology
Entry 3
-> Home Assistant
Entry 4
-> Webshops
and so on.

Now create a new separate database:

-> Root
-> Wife (synchronisation is on)
here are ALL entries (143 entries) without structure, without subgroups

When I create subfolders in the new database, the synchronisation does not work. The entries in the subfolder of MY DATABASE are gone, and all entries are in the main synchronisation folder WIFE.

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )

A little structure in the database is important to me. It would be nice if this structure (folders AND subfolders) could also be synchronised. That way it's easier to keep track and new, changed entries are synchronised and I don't have to work with export/import AND at the same time with another folder synchronisation for the entries that my wife WRITES NEW.
In my opinion, this would contribute to a better user experience.

**Comment by droidmonkey** [comment]
Duplicate issue
