### ISSUE TITLE
If menu gets disabled it can not be restored

### ISSUE THREAD

**Issue by MegaV0lt** [keepassxreboot/keepassxc#11438]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
If menu gets disabled via menu view it can not be restored anymore

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. open keepassxc
2. select view
3. disable menubar

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Having access to menu via right click on empty space. Or have a hotkey to re enable meubar

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
After disabling menubar there is no option to re enable it. (Except via resettig to default)

## Context
[NOTE]: # ( Give us any additional information you may have. )
![Menü_034](https://github.com/user-attachments/assets/51010b4f-575b-4a76-b73e-1d1b3cc54d7d)

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.9
Revision: 8f6dd13

Qt 5.15.13
Diagnosemodus ist deaktiviert.

Betriebssystem: Linux Mint 22
CPU-Architektur: x86_64
Kernel: linux 6.8.0-48-generic

Aktivierte Erweiterungen:
- Auto-Type
- Browser-Integration
- Passkeys
- SSH-Agent
- KeeShare
- YubiKey
- Secret-Service-Integration

Kryptographische Bibliotheken:
- Botan 2.19.3

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: Cinnamon
Windowing System: X11

**Comment by droidmonkey** [comment]
Press alt. This had also been corrected for next release
