### ISSUE TITLE
after X failed attempt, (a) Delete Database file (b) delay another try after x mins

### ISSUE THREAD

**Issue by ck0099** [keepassxreboot/keepassxc#11436]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
Just incase your macbook get stolen, you will feel safe the hacker will never break the database?
Potential Protection Mechanism - after X failed attempt of password:
(a) Delete Database file 
or
(b) delay another try after x mins, and consecutively make the delay longer.

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )
- KeePassXC installed on macbook.
- Key file is also stored on macbook.
- Hacker use bruteforce app (can be simply created with python) to hack the password.

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )

**Comment by ck0099** [comment]
Dear Sir, I thought this is a very good security features that, just incase macbook got stolen, you don't need to worry that the database gets bruteforce hack?

**Comment by michaelk83** [comment]
It's trivial to circumvent by just copying the database file before trying to unlock. The protection against bruteforce is to use a strong passphrase.
