### ISSUE TITLE
Libby App Passkey Creation

### ISSUE THREAD

**Issue by Hiallthejetbrains** [keepassxreboot/keepassxc#11439]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Sign into libby.
2. Attempt to create a passkey
3. Accept the passkey in XC
4. Observe failure in libby

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
The passkey would be successfully created and operational

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Libby tells you that the creation fails, and when you try to use the key, it fails.

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.9
Revision: 8f6dd13

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS
Desktop Env: Unknown
Windowing System: Unknown

**Comment by droidmonkey** [comment]
What is Libby and how are you accessing it?

**Comment by Hiallthejetbrains** [comment]
Libby is an online book platform, that I am using on Firefox, at libbyapp.com

**Comment by varjolintu** [comment]
Normally these sites are reported to https://github.com/keepassxreboot/keepassxc/issues/10374.

How do you even create an account (or passkey) to that site? I couldn't find anything relevant.

**Comment by droidmonkey** [comment]
I don't see any way to actually log into this site. It only asks for your library card number and locality. Report full details to the linked issue above which is tracking passkey problems on certain sites. Include screenshots.
