### ISSUE TITLE
Crash when creating a new database

### ISSUE THREAD

**Issue by hifi** [keepassxreboot/keepassxc#1143]
When creating a new database with develop HEAD, KeePassXC always crashes.

Bisected to:
```
eb6582266533a979a753327b7f222867b7d146c3 is the first bad commit
commit eb6582266533a979a753327b7f222867b7d146c3
Author: thez3ro <io@thezero.org>
Date:   Wed Sep 27 19:18:13 2017 +0200

    layout update

```

Ping @TheZ3ro

## Steps to Reproduce (for bugs)

1. Start KeePassXC
2. Create new database
3. Will crash immediately

## Debug Info

KeePassXC - Version 2.2.2
Revision: eb65822

Libraries:
- Qt 5.7.1
- libgcrypt 1.7.8

Operating system: Fedora 26 (Twenty Six)
CPU architecture: x86_64
Kernel: linux 4.13.5-200.fc26.x86_64

Enabled extensions: None

**Comment by TheZ3ro** [comment]
Are you sure it's that specific commit?

**Comment by frostasm** [comment]
I can reproduce the issue also on the develop branch

**Comment by TheZ3ro** [comment]
Yup, I've detected the flaw. I will patch this tonight or tomorrow

**Comment by droidmonkey** [comment]
Please add a gui test that creates a new database

**Comment by TheZ3ro** [comment]
Yup I was already thinking about it. Strange that we don't already have them
