### ISSUE TITLE
KeePassXC Browser Integration is not working with Edge on the 2.7.9 version

### ISSUE THREAD

**Issue by darkodidak1** [keepassxreboot/keepassxc#11440]
## Overview

macOS Sonoma 14.7.1 with the latest Edge installed

KeePassXC Browser Integration is not working with Edge on the 2.7.9 version.
After downgrading to 2.7.7, it started to work normally.

## Steps to Reproduce
1. Update KeePassXC to 2.7.9 
2. Browser integration with Edge stopped working
3. Downgrade to 2.7.7
4. Browser Integration with Edge started to work

## Expected Behavior
I expect it to work on 2.7.9

## Actual Behavior
It actually stop to work on the latest version on KeePassXC.

## Context
I suppose its a bug on the latest version.

/Applications/KeePassXC.app/Contents/MacOS/KeePassXC --debug-info
KeePassXC - Version 2.7.9
Revision: 8f6dd13

Qt 5.15.11
Debugging mode is disabled.

Operating system: macOS 14.7
CPU architecture: arm64
Kernel: darwin 23.6.0

Enabled extensions:
- Auto-Type
- Browser Integration
- Passkeys
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 3.1.1

Operating System: macOS

**Comment by droidmonkey** [comment]
Close edge fully and reinstall 2.7.9. If you leave the browser open when you upgrade keepassxc on macos, sometimes it fails because the proxy service is still running.

**Comment by darkodidak1** [comment]
I can confirm that this workaround works, thank you droidmonkey!
