### ISSUE TITLE
KeePassXC-Browser: Change banner location

### ISSUE THREAD

**Issue by 40417256** [keepassxreboot/keepassxc#11444]
## Summary
Ability to select where the banner is displayed. Because the web page has a custom field right above the confirm button.

Add an option to select where the banner is shown, top or bottom of the page

## Examples
![Screenshot from 2024-11-07 11-35-19](https://github.com/user-attachments/assets/7a5eac1c-30d0-4a0b-a103-ef932abd6074)

## Context
Cannot save custom field because another custom field is over the confirm button.

**Comment by varjolintu** [comment]
You can already do that by dragging the banner.
