### ISSUE TITLE
Create export without passwords (and usernames)

### ISSUE THREAD

**Issue by abelbabel** [keepassxreboot/keepassxc#11442]
Hi,

when handling multiple password databases, it might be handy to have/get an overview over all entries in all databases. Therefore export function could be enhanced to allow exporting the database to some unencrypted format, BUT without the secrets (and usernames) (or other way round: only with title and group). In the end also the structure should be visible and of course the entries represented by their titles, so that on can easily determine where to look up certain secrets.

Regards
abelbabel

**Comment by droidmonkey** [comment]
This won't be implemented. If you want to see all your entries use the "All entries" search in the lower left panel.

**Comment by abelbabel** [comment]
Found a good solution:

in cli use `ls -R` and grab the list


Sorry for the noise!
