### ISSUE TITLE
Auto-type stopped working

### ISSUE THREAD

**Issue by croftab** [keepassxreboot/keepassxc#11457]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
Auto-type stopped working about one month ago.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
Setup or use an existing entry in keepassxc.
Follow the instructions steps to enable Global Auto-Type and the steps to enable use with a Wayland compositor on Linux.
Either:
Type the Auto-Type hotkey with the cursor focus on the username login form of a website.
OR
Click the Perform Auto-Type toolbar button in keepassxc directly after focusing the cursor on the username login form of a website.

## Expected Behavior
The username/password combination should be auto-typed if the window matches or the select entry form should be displayed.

## Actual Behavior
Nothing happens.

## Context
This had been working for some time. A recent update appears to have broken the functionality.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.9
Revision: 8f6dd13
Distribution: Flatpak

Qt 5.15.10
Debugging mode is disabled.

Operating system: KDE Flatpak runtime
CPU architecture: x86_64
Kernel: linux 6.11.5-amd64

Enabled extensions:
- Auto-Type
- Browser Integration
- Passkeys
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 3.3.0

[NOTE]: # ( Pick choices based on your environment )
Operating System: Debian Testing
Desktop Env: Gnome 47
Windowing System: Wayland

**Comment by droidmonkey** [comment]
Auto-type is not supported on Wayland, yet. It will be supported in version 2.8.0. You are running keepassxc on X11 through XWayland, but that will NOT let you autotype into wayland native windows.
