### ISSUE TITLE
Searches and tags view

### ISSUE THREAD

**Issue by Jaz-z** [keepassxreboot/keepassxc#11456]
## Summary
Just upgraded to Kubuntu OS 24.01 KeepassXC upgraded as well it seems ...

The interface view has a new search feature that I cannot hide and it takes up space from the left column.
When I change the window size to small it does not become smaller than a certain size because of that search panel and also a large section of the left column is covered by the search panel.

My keepassXC database is quite big with many entries and that useful little search window is in the way.
So I suggest to provide it in a different way - three options come to my mind:
1- in a top menu as search options.
2- as drop down menu in the search field - although this takes up space in the width - so top menu is better.
3- A hide option so one can hide the current  search panel on the side and just see the data entries on the left side.

[NOTE]: # ( Show us a picture or mock-up of your proposal )

![keepassxcSuggestioni](https://github.com/user-attachments/assets/6af89f0b-a562-4808-9cf6-9916036676c5)

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
the database is big, I have many windows open and it is better for me to see the data entries on the left column instead of having a little panel there that I may not be using most of the time.

**Comment by droidmonkey** [comment]
Please paruse the user guide to see how this adds value to your every day experience. Especially with the introduction of tags and the ability to save commonly used search queries per database. 

You can easily hide it by dragging down from the top of the Searches and Tags area.
