### ISSUE TITLE
Crashes DE session after restarting Keepassxc when used as a secret service

### ISSUE THREAD

**Issue by siddhpant** [keepassxreboot/keepassxc#11452]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Use keepassxc as secret service on GNOME Wayland.
2. Have keepassxc running.
3. Quit it (from icon for example).
4. Start keepassxc again.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
1. keepassxc restarts.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
1. Session crashes, lost all work, and I'm back to login page.

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.9
Revision: 8f6dd13
(keepassxc-full 2.7.9+dfsg1-1)

[NOTE]: # ( Pick choices based on your environment )
Operating System: Debian Testing
Desktop Env: Gnome
Windowing System: Wayland

**Comment by droidmonkey** [comment]
This sounds like a bug with gnome 

You are also rubbing a testing distro, please report this to debian maintainers

**Comment by vanous** [comment]
Just to add here should this help anyone when trying to see what is causing it: it seems that 2.4.3 is the last version of keepassxc which did not bring the wayland session down.
