### ISSUE TITLE
Pasting into an Linux VM on Hyper-Visor running on Windows.

### ISSUE THREAD

**Issue by gabs247** [keepassxreboot/keepassxc#11458]
## Overview
When I am trying to Auto Type into a Linux VM (Ubuntu) on Hyper Visor running on Windows 11, it spits out rubbish. I just recently switched from KeePass Windows app which worked fine for this.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Open a Linux VM on Hyper Visor
2. Go to Entries menu, then Perform Auto-Type
3. Hit Username or Password and you only see a few random characters, doesn't resemble either of what I wanted

## Expected Behavior
Expected to see the Username or Password typed into the fields, as per on the official KeePass app for Windows.

## Actual Behavior
Seeing nothing or rubbish characters printed.

## Context
I tried a Windows VM on Hyper Visor, seemed to work fine, so it's just the Ubuntu one for some reason.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.9
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows

**Comment by droidmonkey** [comment]
Use Virtual Keyboard mode. https://keepassxc.org/docs/KeePassXC_UserGuide#_performing_global_auto_type
