### ISSUE TITLE
Unable to add attachments from hidden folders on Ubuntu/Linux

### ISSUE THREAD

**Issue by spirgiuz** [keepassxreboot/keepassxc#11466]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
I want to attach a file to an entry, but the file is in a hidden ubuntu directory (starts with a .). The file picker doesn't show hidden directories by default, there's no button in the file picker to show hidden files/directories and you can't enter the path manually in the file picker either so there's no way to attach or open a database that starts with a dot.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Make a file or folder that starts with a .
2. Press "Open database..."
3. Try to open that file

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
For there either to be a button for toggling whether to show hidden files or a way to manually enter a path in the picker.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
There's no way to choose a hidden file in the file picker so the only workaround is to move the file and/or rename it first before attaching.

## Context
[NOTE]: # ( Give us any additional information you may have. )
My use case is attaching a file, but seems like the same problem appears if you make your database file hidden and try to open it, since the same file picker is used.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.9
Revision: 8f6dd13

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux (Ubuntu 24.04)
Desktop Env: Gnome
Windowing System: Wayland

**Comment by droidmonkey** [comment]
This is a limitation of Snaps and there is nothing we can do about it. If you want to access "hidden" folders you will have to use the apt installed version, ppa, appimage, or flatpak. 

If you are already using a non-snap, then you just need to press Ctrl+H in the file picker dialog to show/hide hidden folders. This is a Gnome thing, not a KeePassXC thing.

**Comment by spirgiuz** [comment]
Thank you, I was using the ppa version, ctrl+h didn't work but I googled and found that I had to right click a file and the context menu had an option to show hidden files.
