### ISSUE TITLE
Inactive/disabled entries

### ISSUE THREAD

**Issue by 1over137** [keepassxreboot/keepassxc#11461]
## Summary
It would be useful to be able to turn off some entries so they do not show up on e.g. browser extension. Many people have extra accounts that should be remembered but not used with any regularity.

## Examples
Add a "active" field in the database, a context menu button that would toggle it, and it  would simply not show up on browser autofill.

**Comment by droidmonkey** [comment]
Edit the entry, go to browser tab, select the option that hides the entry from the browser integration. You can do this at the group level as well. 

https://keepassxc.org/docs/KeePassXC_UserGuide#_advanced_usage
