### ISSUE TITLE
Missing Menubar in Ubuntu 24.04

### ISSUE THREAD

**Issue by Dexus** [keepassxreboot/keepassxc#11463]
## Overview
The Menubar is gone on kubuntu 24.04.01

## Steps to Reproduce
Updated 22.04 to 24.04 and updated to latest KeepassXC via PPA

## Expected Behavior
I would like to get my Menubar back

## Actual Behavior
![Screenshot_20241112_113816](https://github.com/user-attachments/assets/a9a2a0eb-4972-4743-bdfc-9a75856790ef)

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: KDE
Windowing System: Wayland

**Comment by droidmonkey** [comment]
Press alt. Then go to the view menu and enable it again.

**Comment by Dexus** [comment]
@droidmonkey it's not working :( There will not open any menu or option to enable it.

**Comment by droidmonkey** [comment]
Go to the application settings and scroll to the bottom and press "reset settings"

If you still don't see it, then that means global menubar has been enabled for your KDE and the menubar would be shown by KDE and not the individual app. That would impact almost all apps though.

**Comment by Dexus** [comment]
ok kde need to disable the application menu service... thats wired...
