### ISSUE TITLE
Browser access request never shown once remember option was activated

### ISSUE THREAD

**Issue by tprosche** [keepassxreboot/keepassxc#11479]
## Overview
The remember option in the browser access request - dialog cannot be undone.

## Steps to Reproduce
1. Open the login page of a service.
2. Via the KeePassXC browser extension in Firefox the KeePassXC application finds the login page in the database and opens the dialog for browser access request.
3. Check the "Remember" check box and press "Allow Selected" button.

## Expected Behavior
There is no way to undo the remember option. Not in the browser extension nor in the app itself.

## Actual Behavior
Open the login page of the service of step-1 above always fill in the credentials without access query.

## Context
KeePassXC - 2.7.9
Revision: 8f6dd13
Operating System: Windows 10 Pro 22H2
Desktop Env: -/-
Windowing System: -/-

**Comment by droidmonkey** [comment]
That's kind of the point. But if you must undo it, then go to the entry in question in keepassxc, press enter or double click to edit it, go to properties tab, select the browser custom data and press remove.

Another issue is tracking a way to do this from the browser tab instead.

**Comment by tprosche** [comment]
Thanks for the explanation how to remove the auto fill-in.
I searched the user guide, but there was no hint that the remember option can be undone via the property page.

**Comment by domalex** [comment]
I have exact the same issue. I cannot find the settings to withdraw a previously "Allow Selected" and "Remember" decision for an entry. @droidmonkey following your does not lead to the desired setting: under the properties tab of an entry is no entry "browser custom data" which could be removed.

**Comment by droidmonkey** [comment]
Than the entry you are looking at doesn't have saved browser configuration settings.
