### ISSUE TITLE
Top most tabs are not showing up in linux (appimage)

### ISSUE THREAD

**Issue by aurora-1-2-3** [keepassxreboot/keepassxc#11477]
## Overview
The tabs the should be above the icons are not there
![image](https://github.com/user-attachments/assets/58dbf205-7dea-4017-90bc-e837562a50ff)

## Steps to Reproduce
Just open an appimage

## Expected Behavior
I expect these tabs to appear
![image](https://github.com/user-attachments/assets/e659a91d-1366-4ade-9e77-6f5143bc123a)

## Actual Behavior
No tabs :(
![image](https://github.com/user-attachments/assets/58dbf205-7dea-4017-90bc-e837562a50ff)

## Context
Most advance options are in these tabs, e.g: export as *.xml

"[NOTE]: # ( Paste debug info from Help → About here )" cant even get that T_T

KeePassXC - 2.7.9
Revision: REVISION

Operating System: Linux (Nobara 40)
Desktop Env: KDE

**Comment by droidmonkey** [comment]
Disable global application toolbar in KDE

**Comment by aurora-1-2-3** [comment]
Um, I am getting trouble turning it off. Sorry I am a bit new to Linux, so I don't know much

**Comment by droidmonkey** [comment]
You'll have to consult your OS manual. But this might help:

> have a look at the System Settings:
In System Settings -> Workspace -> Startup and Shutdown -> Background Services, uncheck the "Application menus daemon" then log out and back into Plasma again

https://forum.kde.org/viewtopic.php%3Ff=17&t=167547.html

**Comment by aurora-1-2-3** [comment]
got it thanks
