### ISSUE TITLE
Searchs and Tags disappears on application crash; favicons implicated

### ISSUE THREAD

**Issue by JBSedich** [keepassxreboot/keepassxc#11474]
## Overview
Searches and Tags UI element can be disappeared, most likely because of a crash when performing a favicon download on all entries

I suppose the crash itself is part of the bug report too.

## Steps to Reproduce

1. Take a large-ish database and choose "all entries" under Searches and Tags
2. Select all, right click and download favicons for all entries
3. KeepassXC hangs and terminates
4. Re-open KeepassXC.
5. Searches and Tags is now absent

At least, this these are the steps that I believe led to me not having it there anymore.

## Expected Behavior
Searches and Tags is present. No crash on favicon download

## Actual Behavior
Searches and Tags is absent. Yes crash on favicon download

## Context
I am totally new to this software so if there is a simpler explanation please delete this.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.9
Revision: 8f6dd13

Qt 5.15.11
Debugging mode is disabled.

Operating system: Windows 11 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.22631

Enabled extensions:
- Auto-Type
- Browser Integration
- Passkeys
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 3.1.1

**Comment by droidmonkey** [comment]
Weird,  but you can easily just drag it back up. Hover over the bottom of the groups panel until you see the resize cursor,  click and drag up

**Comment by droidmonkey** [comment]
I cannot replicate the crash, can you replicate it yourself?
