### ISSUE TITLE
Use AWS Secrets Manager as sync service

### ISSUE THREAD

**Issue by yarons** [keepassxreboot/keepassxc#11478]
## Summary
Use the AWS Secrets Manager API to store and retrieve password and other types of secrets

## Examples
It's more of a backend feature, I'm not sure a screenshot it necessary in this case

## Context
It can help a team keep and share secrets in a secure manner with their AWS account.

**Comment by droidmonkey** [comment]
Generally speaking, we do not integrate with external services. If you want to setup a sync with AWS (or any other service) then use the CLI tools for that service in conjunction with keepassxc-cli.
