### ISSUE TITLE
Application scaling not working on modern Laptops

### ISSUE THREAD

**Issue by forReason** [keepassxreboot/keepassxc#11473]
## Overview
![Screenshot from 2024-11-15 19-35-43](https://github.com/user-attachments/assets/ff177e2e-5354-4a7e-8e2b-a374e6484ece)
As you may see in the screenshot above, the text of the application becomes very tiny on small, high resolution displays (Laptops).
You can see the comparison to my browser text as well. The scaling seems to be hardcoded and does not respect the system settings under accessibility of ubuntu and there is no setting within the application itself which I could overwrite the text size with.
The example is taken on a relatively big 16'' 2,5k screen (188dpi) laptop. On even smaller oLed screens the issue will worsen in the future, as display resolutions rise.

## Steps to Reproduce
1. Set "Large text in accessibility settings" & set larger font using gnome tweaks (as gnome has trouble with 4k screens as well)
![Screenshot from 2024-11-15 19-40-23](https://github.com/user-attachments/assets/72431312-6b94-4f41-a312-3aa2832b9edb)
2. Start the application on a 4k screen, on a laptop

## Expected Behavior
Application scales texts & icons according to system settings
or: Application has fixed units such as "cm" programmed rather than relative units such as pixles, so the scaling is correct
or: Application contains setting/menu option to scale text:
![Screenshot from 2024-11-15 19-44-44](https://github.com/user-attachments/assets/57d29826-649c-4311-a0eb-83b80f7813ff)

## Actual Behavior
Text is too small

## Context
- Specifically on high resolution, small size displays

## Debug info:
KeePassXC - Version 2.7.8
Revision: f6757d3
Distribution: Snap

Qt 5.15.11
Debugging mode is disabled.

Operating system: Ubuntu Core 22
CPU architecture: x86_64
Kernel: linux 6.11.0-061100-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- Passkeys
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.19.1

## System info:
Display resolution:
2560x1600 - 16''

Operating System: Ubuntu 24.04.1
Desktop Env: Gnome
Windowing System: (i think gnome is wayland)

**Comment by droidmonkey** [comment]
Recommend switching to the flatpak release, snaps have poor integration (as witnessed). You can try to overcome this on snaps by setting the appropriate Qt environment variables, as documented here: https://keepassxc.org/docs/KeePassXC_UserGuide#_command_line_options

Since you "tweaked" your scale factor to 1.5, Qt on Linux will generally round down. So the environment variables would be useful for you to set it to 2.
