### ISSUE TITLE
Provide MSI-based installer on Windows

### ISSUE THREAD

**Issue by smarsching** [keepassxreboot/keepassxc#1148]
At the moment, there are two kinds of Windows builds: The “portable“ distribution, which is simply a ZIP archive, and the EXE installer, which is based on the Nullsoft Installer. Neither of the two is particularly well-suited for automatic deployment. Fur such scenarios, it would be desirable to have a Windows Installer (MSI) package.

I have some experience with the WiX toolset and would be willing to invest some time into this issue. In the past, I have created a MSI package of KeePassX, which should be a good starting point for making a MSI package for KeePassXC. So far, this MSI-package is based on the portable ZIP distribution, but building the MSI involves several manual steps.

Unfortunately, I do not understand yet how the build system for KeePassXC works. In particular, I did not find the code that is currently responsible for building the Windows packages. If you could give me some pointers, I would have a look into how WiX can be integrated into that workflow.

**Comment by droidmonkey** [comment]
The zip and exe are "built" using cpack which is part of cmake. It looks like there is a WiX plugin for cpack you could use: https://cmake.org/cmake/help/v3.10/module/CPackWIX.html

Any installer build that requires manual steps is a non starter.

**Comment by smarsching** [comment]
Thanks for pointing me in the right direction. I already thought that you are using CPack, but I did not see the configuration because I initially looked in the wrong `CMakeLists.txt` (in the root instead of in the `src` directory).

It took me some time to get the build environment on Windows working, but now I can build the ZIP and the NSIS package and I will try to add the configuration for WiX.

**Comment by droidmonkey** [comment]
You can use one of the command line switches for the release tool to also build WIX.

**Comment by smarsching** [comment]
@droidmonkey Sure, I saw that it is possible to set the `CPACK_GENERATORS` environment variable in order to include the MSI packages in the build. However, this means that at the moment, one has to setup a build environment with all the dependencies and then build KeePassXC oneself, just to get the MSI packages. This does not sound like less work than unpacking the .exe installer and manually build the MSI from the contents.

I thought the idea behind including the MSI packages as part of the build process was to make them available along with the other downloads, so that anyone needing them can simply download them instead of the .exe installer.

**Comment by droidmonkey** [comment]
Yah that's what I meant, I will make a WIX installer available for 2.3.2

**Comment by smarsching** [comment]
Great, thanks for your answer.

**Comment by phoerious** [comment]
2.2.3 has an MSI installer.
