### ISSUE TITLE
KeePassXC Not Displaying on External Monitors

### ISSUE THREAD

**Issue by adnanrahin** [keepassxreboot/keepassxc#11485]
#### *![Image](https://github.com/user-attachments/assets/130b5505-f35e-433b-8b4a-a4809d4182f4)
*Overview**
KeePassXC fails to display correctly when external monitors are connected. The application appears only on the MacBook's built-in display and disappears or becomes inaccessible when attempting to move it to an external monitor. This issue started after upgrading to macOS Sequoia 15.1.1.

---

#### **Steps to Reproduce**
1. Connect one or more external monitors to the MacBook.
2. Open KeePassXC.
3. Attempt to view or move the KeePassXC window to an external monitor.

When I do Show All Window, this is what I got. 
![Image](https://github.com/user-attachments/assets/1614bf5c-76b2-4d43-9009-68c8d78f7e1f)

---

#### **Expected Behavior**
KeePassXC should display on external monitors and allow users
 to move the application window between monitors without disappearing.

---

#### **Actual Behavior**
- KeePassXC only appears on the MacBook's built-in display.
- The application disappears when attempting to move the window to an external monitor.
- This behavior persists regardless of whether the MacBook lid is open or closed.

---

#### **Context**
- **KeePassXC Version**: 2.7.9
- **Revision**: [Provide revision number, if available]
- **Operating System**: macOS Sequoia 15.1.1
- **Desktop Environment**: macOS built-in desktop
- **Windowing System**: Metal (or relevant macOS rendering system)

---

#### **Additional Information**
- Issue occurs with all tested external monitors.
- Works correctly when external monitors are disconnected.
- Attempted troubleshooting steps:
  - Dragging the window manually between monitors.
  - Testing with MacBook lid open and closed.
  - Issue persists regardless of display arrangement.

**Comment by droidmonkey** [comment]
Lots of duplicates here: https://github.com/keepassxreboot/keepassxc/issues?q=is%3Aissue%20state%3Aclosed%20displaylink

https://keepassxc.org/docs/KeePassXC_UserGuide#_screenshot_security

**Comment by adnanrahin** [comment]
Thanks for @droidmonkey your response. 
Seems like this issue coming from latest macOS, I have downgraded mine.
I have seen this issue with some streaming services like Netflix.

**Comment by droidmonkey** [comment]
For some reason, they didn't exclude Display Link from being classified as a remote desktop viewer
