### ISSUE TITLE
[Windows] Displayed Columns Randomly Reset visible/layout

### ISSUE THREAD

**Issue by SdoggaMan** [keepassxreboot/keepassxc#11480]
## Overview
In Windows running the latest version of KeePassXC, when opening a database, the displayed columns and their width/position will reset seemingly at random. 

Advice has been given before to reset the settings (Tools > Settings > Reset settings to default...) to rebuild the config, but this has not resolved the issue. I'm not sure what causes it to reoccur other than it seems to happen when opening a database. 

I have the password column shown so I can easily double-click for entry when the autofill plugin fails (which is frequent) and the TOTP/Group columns hidden as KPXC is kept to split-screen so as to maximise on visibility. 

## Steps to Reproduce
1. Open a database
^ It's possible it does this when not cleanly closed, but I've been quitting the program of late before rebooting the system and getting the same result. it's inconsistent. 

## Expected Behavior
Columns stay visible/hidden, and sized/positioned where they are left in relation to other columns.

## Actual Behavior
Default layout is applied on loading a database. 

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.9
Revision: 8f6dd13

Qt 5.15.11
Debugging mode is disabled.

Operating system: Windows 10 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.19045

Enabled extensions:
- Auto-Type
- Browser Integration
- Passkeys
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 3.1.1

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows

**Comment by droidmonkey** [comment]
Please try running a snapshot build from https://snapshot.keepassxc.org 

There were major code changes around this and it's likely a non problem for the next release.

**Comment by lev741** [comment]
I see the same behavior. 
Only when checked "Start with minimized window"
(I is reverse translation of the configuration name because I am running non english version)

**Comment by droidmonkey** [comment]
I cannot reproduce this at all. I enabled minimize on startup and hid the TOTP and showed the Password columns. Exited app. Started, it was minimized, unminimized and logged in, TOTP still hidden and Password column shown. Without reproduction this cannot be solved. Recommend resetting your settings or manually removing `%LOCALAPPDATA%/KeePassXC/keepassxc.ini`
