### ISSUE TITLE
Add option to require biometrics input for added security

### ISSUE THREAD

**Issue by samthesamman** [keepassxreboot/keepassxc#11488]
## Summary
Please add an option to require biometric input to unlock DB. This way if someone is able to steal your DB and bruteforce, or if they somehow gain remote access to your computer, they won't be able to access the DB.

## Examples
N/A

## Context
Added security in case DB file becomes compromised.

**Comment by droidmonkey** [comment]
If someone can successfully brute force your database then they can also brute force your biometric. Biometrics are also only used for authentication, not encryption. Further, this isn't part of the kdbx standard and biometrics are not transferable between devices. All this to say, this won't be implemented.
