### ISSUE TITLE
remove from clipboard

### ISSUE THREAD

**Issue by dietmarczekay** [keepassxreboot/keepassxc#11486]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. make password visible
2. mark the complete password
3. right mouse click to copy to clipboard

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
the counter should start to remove from clipboard

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
counter did not start

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.9
Revision: 8f6dd13

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: KDE
Windowing System: Wayland

**Comment by droidmonkey** [comment]
Right click copy bypasses our code, use Ctrl+C or click the copy password toolbar icon
