### ISSUE TITLE
Additional Attributes for Entries can`t be named in CamelCase

### ISSUE THREAD

**Issue by TobSchwa94** [keepassxreboot/keepassxc#11490]
## Steps to Reproduce
1. Create an additional attribute in the extended tab (renaming also not working)
2. Set the name to CamelCaseValue -> Example: "CamelCaseExample"
3. Try to save the name

## Expected Behavior
CamelCase-name is saved.

## Actual Behavior
The attribute name is reset to blank.

KeePassXC - VERSION: 2.7.9
Revision: REVISION: 8f6dd13

Operating System: Windows (Not tested for other OS)
Windowing System: 11

**Comment by phoerious** [comment]
I cannot reproduce this and I also wouldn't know why camel case should be handled any differently from other capitalisations. Do you have a screen recording of this happening on your machine?

**Comment by TobSchwa94** [comment]
Okay, I also cant reproduce it right now. Maybe it was a temporary bug. Sorry for the false alert. The ticket can be closed.
