### ISSUE TITLE
Checksum in History List

### ISSUE THREAD

**Issue by newhinton** [keepassxreboot/keepassxc#11493]
## Summary
It would be of benefit if the history-list would show a checksum for each history entry as an additional column.

This way, a quick glance allows the user to decide if two entries have diverged.

## Examples
Just a simple additional text-colum.

## Context

Sometimes Databases can become out of sync when a user is using an external sync mechanism between multiple devices.
In those cases it is nessessary to compare entries and merge them back together.

**Comment by droidmonkey** [comment]
I don't see how this can be useful? If the "divergent database" is actually the same db just different save points, all you need to do is merge between the two. Merging only takes last modified time into account, the older entry gets pushed into history and the newer one becomes current. Checksum means nothing to merge, so showing that won't actually tell you how a merge operation would proceed (also what data are we including in the checksum?).

**Comment by droidmonkey** [comment]
I don't see how this can be useful? If the "divergent database" is actually the same db just different save points, all you need to do is merge between the two. Merging only takes last modified time into account, the older entry gets pushed into history and the newer one becomes current. Checksum means nothing to merge, so showing that won't actually tell you how a merge operation would proceed (also what data are we including in the checksum?).

**Comment by newhinton** [comment]
Maybe i was doing it wrong, but this was my approach:

Naming:
A: Main Copy
B: Older Copy, the conflicting file

1. I found out one of my devices had a conflict from over a month ago
2. Opening both databases sidebyside showed some changes were in both, most in A and some in B.
3. Find the last entry that is in both by ordering by last modified
4. Check each item from the diversion to newest
5. In each item, compare the history with the other's copy


In the last step, my workflow would improve if there was a hash of the specific version. I can just check if they are identical, and then skip that item. (In theory, if the timestamp was excluded, that would even work if the entry had changed at a different date with the same content)

Then, if there is a checksum that does not match, that particular entry needs to be examined closely, and likely transferred.

Does this make sense or is there a different way to do this?

**Comment by droidmonkey** [comment]
I don't understand why the entry history matters in this case. The latest values of the entry are all that matter between Database A and B. If you modified Entry A and Entry B independently then you have to decide which (A or B) has the correct _current values_. The history is quite irrelevant.

I am going to close this since it will most likely not be implemented and doesn't actually solve the problem with merging history items between two databases.

**Comment by newhinton** [comment]
It is less about finding which one matters to me, but which ones i can discard outright because they have not changed.

If i have two history entries with both: "changed passwords" the checksum tells me if they are the same change without opening the entry.


> I am going to close this

Sure!

**Comment by droidmonkey** [comment]
If they haven't changed then the modified date of entry B should be much earlier than the modified date of the entry A and it's history. Either way, the current version that loses out in a merge operation (because modified date is older) will be the _first history item_ in the winning version.
