### ISSUE TITLE
KeePassXC Will Not Start (AppCrash) on both Windows 11 23H2 and 24H2

### ISSUE THREAD

**Issue by TESTER-sec** [keepassxreboot/keepassxc#11492]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Clean install either Windows 11 23H2 or 24H2
2. Install either system install or portable edition of KeePassXC from any official source (e.g. Microsoft Store, KeePassXC)
3. Attempt to launch KeePassXC
4. KeePassXC will not launch (AppCrash)

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Installed or portable version of KeePassXC for Windows will launch on Windows 11 23H2 and 24H2

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Installed or portable version of KeePassXC for Windows does not launch (AppCrash) on Windows 11 23H2 and 24H2

## Context
[NOTE]: # ( Give us any additional information you may have. )

![Image](https://github.com/user-attachments/assets/21d0f762-2d8e-4084-b090-d63bce1c1248)

Version=1
EventType=APPCRASH
EventTime=133768752172101407
ReportType=2
Consent=1
UploadTime=133768752175374460
ReportStatus=268435456
ReportIdentifier=7a27e40f-165b-41ed-819e-2566962e5823
IntegratorReportIdentifier=a53adf0a-fbef-4a6e-8c36-f11ce0ee2b34
Wow64Host=34404
NsAppName=KeePassXC.exe
OriginalFilename=KeePassXC
AppSessionGuid=0000436c-0001-0004-c75b-12abf83ddb01
TargetAppId=W:0000ea1abb59319fd5cc59bf58e0caabb82900000904!000018b0a6a0942a66dc6ee6a30cb00673d9ae493004!KeePassXC.exe
TargetAppVer=2024//06//19:21:52:29!53d50c!KeePassXC.exe
BootId=4294967295
TargetAsId=579
IsFatal=1
Response.BucketId=df8040a3466a7ff78d902dd0c89ea048
Response.BucketTable=4
Response.LegacyBucketId=2130252998488531016
Response.type=4
Sig[0].Name=Application Name
Sig[0].Value=KeePassXC.exe
Sig[1].Name=Application Version
Sig[1].Value=2.7.9.0
Sig[2].Name=Application Timestamp
Sig[2].Value=6673531d
Sig[3].Name=Fault Module Name
Sig[3].Value=MSVCP140.dll
Sig[4].Name=Fault Module Version
Sig[4].Value=14.24.28127.4
Sig[5].Name=Fault Module Timestamp
Sig[5].Value=5d8e68d7
Sig[6].Name=Exception Code
Sig[6].Value=c0000005
Sig[7].Name=Exception Offset
Sig[7].Value=0000000000012590
DynamicSig[1].Name=OS Version
DynamicSig[1].Value=10.0.26100.2.0.0.256.48
DynamicSig[2].Name=Locale ID
DynamicSig[2].Value=1033
DynamicSig[22].Name=Additional Information 1
DynamicSig[22].Value=b534
DynamicSig[23].Name=Additional Information 2
DynamicSig[23].Value=b534e1b59a2668852104c22a5a4b7945
DynamicSig[24].Name=Additional Information 3
DynamicSig[24].Value=5954
DynamicSig[25].Name=Additional Information 4
DynamicSig[25].Value=59548250d42693509b0653aa71b06727
UI[2]=C:\Program Files\KeePassXC\KeePassXC.exe
LoadedModule[0]=C:\Program Files\KeePassXC\KeePassXC.exe
LoadedModule[1]=C:\WINDOWS\SYSTEM32\ntdll.dll
LoadedModule[2]=C:\WINDOWS\System32\KERNEL32.DLL
LoadedModule[3]=C:\WINDOWS\System32\KERNELBASE.dll
LoadedModule[4]=C:\WINDOWS\System32\SETUPAPI.dll
LoadedModule[5]=C:\WINDOWS\System32\msvcrt.dll
LoadedModule[6]=C:\WINDOWS\System32\WS2_32.dll
LoadedModule[7]=C:\WINDOWS\System32\RPCRT4.dll
LoadedModule[8]=C:\WINDOWS\System32\USER32.dll
LoadedModule[9]=C:\WINDOWS\System32\win32u.dll
LoadedModule[10]=C:\WINDOWS\System32\GDI32.dll
LoadedModule[11]=C:\Program Files\KeePassXC\qrencode.dll
LoadedModule[12]=C:\Program Files\KeePassXC\Qt5Svg.dll
LoadedModule[13]=C:\WINDOWS\System32\gdi32full.dll
LoadedModule[14]=C:\Program Files\KeePassXC\Qt5Concurrent.dll
LoadedModule[15]=C:\WINDOWS\System32\msvcp_win.dll
LoadedModule[16]=C:\WINDOWS\System32\ucrtbase.dll
LoadedModule[17]=C:\WINDOWS\System32\shcore.dll
LoadedModule[18]=C:\Program Files\KeePassXC\argon2.dll
LoadedModule[19]=C:\WINDOWS\SYSTEM32\WinSCard.dll
LoadedModule[20]=C:\WINDOWS\System32\OLEAUT32.dll
LoadedModule[21]=C:\WINDOWS\SYSTEM32\HID.DLL
LoadedModule[22]=C:\WINDOWS\System32\combase.dll
LoadedModule[23]=C:\Program Files\KeePassXC\Qt5Network.dll
LoadedModule[24]=C:\WINDOWS\System32\ADVAPI32.dll
LoadedModule[25]=C:\WINDOWS\System32\sechost.dll
LoadedModule[26]=C:\WINDOWS\System32\CRYPT32.dll
LoadedModule[27]=C:\WINDOWS\System32\ole32.dll
LoadedModule[28]=C:\Program Files\KeePassXC\Qt5Widgets.dll
LoadedModule[29]=C:\Program Files\KeePassXC\Qt5Gui.dll
LoadedModule[30]=C:\WINDOWS\System32\SHELL32.dll
LoadedModule[31]=C:\Program Files\KeePassXC\Qt5Core.dll
LoadedModule[32]=C:\Program Files\KeePassXC\zlib1.dll
LoadedModule[33]=C:\Program Files\KeePassXC\botan-3.dll
LoadedModule[34]=C:\Program Files\KeePassXC\minizip.dll
LoadedModule[35]=C:\WINDOWS\SYSTEM32\WTSAPI32.dll
LoadedModule[36]=C:\WINDOWS\SYSTEM32\ntmarta.dll
LoadedModule[37]=C:\WINDOWS\SYSTEM32\VCRUNTIME140.dll
LoadedModule[38]=C:\WINDOWS\SYSTEM32\VCRUNTIME140_1.dll
LoadedModule[39]=C:\WINDOWS\SYSTEM32\MSVCP140.dll
LoadedModule[40]=C:\WINDOWS\SYSTEM32\IPHLPAPI.DLL
LoadedModule[41]=C:\WINDOWS\SYSTEM32\DNSAPI.dll
LoadedModule[42]=C:\Program Files\KeePassXC\libssl-3-x64.dll
LoadedModule[43]=C:\WINDOWS\SYSTEM32\dwmapi.dll
LoadedModule[44]=C:\WINDOWS\SYSTEM32\UxTheme.dll
LoadedModule[45]=C:\WINDOWS\SYSTEM32\dxgi.dll
LoadedModule[46]=C:\WINDOWS\SYSTEM32\MSVCP140_1.dll
LoadedModule[47]=C:\Program Files\KeePassXC\libcrypto-3-x64.dll
LoadedModule[48]=C:\WINDOWS\SYSTEM32\d3d11.dll
LoadedModule[49]=C:\Program Files\KeePassXC\libpng16.dll
LoadedModule[50]=C:\Program Files\KeePassXC\harfbuzz.dll
LoadedModule[51]=C:\WINDOWS\SYSTEM32\MPR.dll
LoadedModule[52]=C:\WINDOWS\SYSTEM32\USERENV.dll
LoadedModule[53]=C:\WINDOWS\SYSTEM32\VERSION.dll
LoadedModule[54]=C:\Program Files\KeePassXC\double-conversion.dll
LoadedModule[55]=C:\Program Files\KeePassXC\pcre2-16.dll
LoadedModule[56]=C:\Program Files\KeePassXC\zstd.dll
LoadedModule[57]=C:\WINDOWS\SYSTEM32\NETAPI32.dll
LoadedModule[58]=C:\WINDOWS\SYSTEM32\WINMM.dll
LoadedModule[59]=C:\WINDOWS\SYSTEM32\bcrypt.dll
LoadedModule[60]=C:\Program Files\KeePassXC\freetype.dll
LoadedModule[61]=C:\WINDOWS\SYSTEM32\SRVCLI.DLL
LoadedModule[62]=C:\WINDOWS\SYSTEM32\NETUTILS.DLL
LoadedModule[63]=C:\Program Files\KeePassXC\bz2.dll
LoadedModule[64]=C:\Program Files\KeePassXC\brotlidec.dll
LoadedModule[65]=C:\WINDOWS\SYSTEM32\CRYPTBASE.DLL
LoadedModule[66]=C:\Program Files\KeePassXC\brotlicommon.dll
LoadedModule[67]=C:\WINDOWS\System32\IMM32.DLL
LoadedModule[68]=C:\WINDOWS\SYSTEM32\directxdatabasehelper.dll
LoadedModule[69]=C:\WINDOWS\SYSTEM32\kernel.appcore.dll
LoadedModule[70]=C:\WINDOWS\System32\bcryptPrimitives.dll
LoadedModule[71]=C:\WINDOWS\System32\NSI.dll
LoadedModule[72]=C:\WINDOWS\SYSTEM32\profapi.dll
LoadedModule[73]=C:\Program Files\KeePassXC\plugins\platforms\qwindows.dll
LoadedModule[74]=C:\WINDOWS\SYSTEM32\windows.storage.dll
LoadedModule[75]=C:\WINDOWS\System32\shlwapi.dll
LoadedModule[76]=C:\WINDOWS\SYSTEM32\powrprof.dll
LoadedModule[77]=C:\WINDOWS\SYSTEM32\UMPDC.dll
LoadedModule[78]=C:\Program Files\KeePassXC\plugins\styles\qwindowsvistastyle.dll
State[0].Key=Transport.DoneStage1
State[0].Value=1
OsInfo[0].Key=vermaj
OsInfo[0].Value=10
OsInfo[1].Key=vermin
OsInfo[1].Value=0
OsInfo[2].Key=verbld
OsInfo[2].Value=26100
OsInfo[3].Key=ubr
OsInfo[3].Value=2314
OsInfo[4].Key=versp
OsInfo[4].Value=0
OsInfo[5].Key=arch
OsInfo[5].Value=9
OsInfo[6].Key=lcid
OsInfo[6].Value=1033
OsInfo[7].Key=geoid
OsInfo[7].Value=244
OsInfo[8].Key=sku
OsInfo[8].Value=48
OsInfo[9].Key=domain
OsInfo[9].Value=0
OsInfo[10].Key=prodsuite
OsInfo[10].Value=256
OsInfo[11].Key=ntprodtype
OsInfo[11].Value=1
OsInfo[12].Key=platid
OsInfo[12].Value=10
OsInfo[13].Key=sr
OsInfo[13].Value=0
OsInfo[14].Key=tmsi
OsInfo[14].Value=222945032
OsInfo[15].Key=osinsty
OsInfo[15].Value=3
OsInfo[16].Key=iever
OsInfo[16].Value=11.1882.26100.0-11.0.1000
OsInfo[17].Key=portos
OsInfo[17].Value=0
OsInfo[18].Key=ram
OsInfo[18].Value=32439
OsInfo[19].Key=svolsz
OsInfo[19].Value=456
OsInfo[20].Key=wimbt
OsInfo[20].Value=0
OsInfo[21].Key=blddt
OsInfo[21].Value=240331
OsInfo[22].Key=bldtm
OsInfo[22].Value=1435
OsInfo[23].Key=bldbrch
OsInfo[23].Value=ge_release
OsInfo[24].Key=bldchk
OsInfo[24].Value=0
OsInfo[25].Key=wpvermaj
OsInfo[25].Value=0
OsInfo[26].Key=wpvermin
OsInfo[26].Value=0
OsInfo[27].Key=wpbuildmaj
OsInfo[27].Value=0
OsInfo[28].Key=wpbuildmin
OsInfo[28].Value=0
OsInfo[29].Key=osver
OsInfo[29].Value=10.0.26100.2314.amd64fre.ge_release.240331-1435
OsInfo[30].Key=buildflightid
OsInfo[30].Value=1131a982-95fc-467d-bc55-aebbd6d0452b
OsInfo[31].Key=edition
OsInfo[31].Value=Professional
OsInfo[32].Key=ring
OsInfo[32].Value=Retail
OsInfo[33].Key=flightbranch
OsInfo[34].Key=expid
OsInfo[34].Value=MD:283BAEF,ME:3036FD6,FX:131B697B,ME:3037091,FX:132CC94F,ME:3038C64,FX:1335985E,ME:3038CEC,FX:133BD3C6
OsInfo[35].Key=fconid
OsInfo[35].Value=18299130,0,2,0;19193777,0,2,0;19194273,0,2,0;19194309,0,2,0;19638787,0,2,0;23531064,2,2,0;23562335,2,2,0;23563673,2,2,0;23877894,1,2,0;26742989,0,1,0;32862274,0,2,0;34853379,0,2,0;35681102,0,1,0;36803287,0,2,0;36803295,0,2,0;36803303,0,2,0;38142198,0,2,0;38277973,0,1,0;38859191,0,2,0;39145991,0,2,0;39146010,0,2,0;39281392,0,2,0;39448330,1,2,0;40025975,0,1,0;40616880,0,1,0;40733296,0,2,0;40883769,0,1,0;40981503,0,1,0;41135193,0,1,0;41137130,0,1,0;41249924,0,2,0;41267076,0,2,0;41313221,0,2,0;41342175,0,1,0;41655236,0,2,0;41744267,0,2,0;41772259,0,2,0;42052423,0,2,0;42092123,0,2,0;42105254,0,2,0;42187503,0,1,0;42235377,0,2,0;42287267,0,2,0;42607764,0,2,0;42921948,0,2,0;42922989,0,2,0;42963857,0,2,0;42969627,0,1,0;43133808,1,2,0;43169616,0,1,0;43203978,0,2,0;43231896,0,2,0;43283184,0,1,0;43572857,0,2,0;43584642,0,2,0;43695740,0,2,0;43698028,0,2,0;43729363,0,2,1;43772553,0,1,0;43844371,0,1,0;43866633,0,2,0;43978769,0,1,0;43995105,0,2,0;43995122,0,2,0;43998261,0,2,0;44030954,0,1,0;44325080,0,1,0;44470355,0,2,0;44521793,0,1,0;44533041,0,0,0;44552141,0,1,0;44774051,0,2,0;44776738,0,2,0;44860385,0,2,0;45009259,0,1,0;45113694,0,2,0;45185354,0,2,0;45187531,0,2,0;45233992,0,2,0;45286373,0,1,0;45732051,0,2,0;45786062,0,2,0;45786681,0,2,0;45796396,0,2,0;45825686,0,1,0;45991456,0,1,0;46009617,0,2,0;46094352,0,2,0;46111200,0,2,0;46251949,0,2,0;46457961,0,1,0;46511169,0,2,0;46541070,0,2,0;46551074,0,1,0;46551941,0,2,0;46557400,0,1,0;46559584,1,2,0;46560585,1,2,0;46591190,0,2,0;46604216,0,2,0;46619189,0,2,0;46624394,0,2,1;46656382,0,2,0;46701147,0,2,0;46715659,0,2,0;46717502,0,2,0;46817969,0,2,0;46982417,0,2,0;46984166,0,2,1;47115450,0,1,0;47134595,0,1,0;47205155,0,2,0;47268464,2,2,0;47270778,0,2,0;47370305,0,2,1;47381523,0,2,0;47402621,0,2,0;47410248,0,1,0;47526873,1,2,0;47557358,0,2,0;47681899,0,1,0;47916854,0,1,0;47921515,0,2,0;47921574,0,2,0;47924308,0,1,0;47942561,0,2,0;47973375,0,1,0;47991031,0,2,1;48042498,0,2,0;48057519,0,2,0;48082515,0,2,0;48126879,0,2,0;48128028,0,2,0;48130544,0,2,0;48281163,0,2,0;48296377,0,1,0;48433541,0,2,0;48433706,0,2,0;48433719,0,1,0;48455785,0,2,1;48468527,0,2,0;48468541,0,2,0;48503047,0,2,0;48522261,0,2,0;48531596,0,2,0;48540091,0,2,0;48635704,0,2,0;48660958,0,2,0;48662857,0,2,0;48780814,0,2,0;48797684,0,2,1;48818825,0,2,0;48969045,0,2,0;49006888,0,1,0;49068236,0,1,0;49084341,0,1,0;49106743,0,2,1;49175271,0,2,1;49199869,0,0,0;49204591,0,1,1;49239926,0,1,1;49287050,0,2,0;49292347,0,2,0;49309588,0,1,1;49336997,0,2,0;49408394,0,1,0;49577493,0,1,1;49615603,0,1,1;49666144,0,1,0;49676912,0,2,1;49689210,0,1,0;49822061,0,1,0;49918560,0,1,0;50039410,0,2,0;50047324,0,2,0;50174317,1,2,0;50174338,0,1,0;50177077,0,2,0;50219409,0,1,0;50219413,0,1,0;50223223,0,2,1;50288426,0,1,0;50480279,0,1,0;50556886,0,2,0;50557073,0,2,0;50564196,0,2,1;50564332,0,2,1;50565209,0,0,1;50569047,0,2,0;50692135,0,1,0;50762615,0,1,1;50942734,0,2,0;51578581,0,1,0;51849637,0,2,0;51850502,2,2,0;51878334,0,2,0;51880512,0,1,0;51944598,0,1,0;52087985,0,1,0;52330548,0,2,0;52443941,0,1,0;52454678,0,1,0;52538889,0,2,0;52800232,0,1,0;52873407,0,0,0;52896431,0,2,0;53058215,0,1,0;53100365,0,1,0;53536518,0,1,0;53615505,0,2,0;54237951,0,1,0;54237969,0,1,0;54237977,0,1,0;54237988,0,1,0;54237993,0,1,0;54238000,0,1,0
OsInfo[36].Key=containerid
OsInfo[37].Key=containertype
OsInfo[38].Key=edu
OsInfo[38].Value=0
OsInfo[39].Key=servicinginprogress
OsInfo[39].Value=0
OsInfo[40].Key=featureupdatependingreboot
OsInfo[40].Value=0
FriendlyEventName=Stopped working
ConsentKey=APPCRASH
AppName=KeePassXC
AppPath=C:\Program Files\KeePassXC\KeePassXC.exe
NsPartner=windows
NsGroup=windows8
ApplicationIdentity=17636767C3912B0ABE1616160BEDF6AD
MetadataHash=-640226376

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.9
Revision: Whatever is the last Revision available for download\install from official sources (e.g. Microsoft Store or KeePassXC website)

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 11 23H2 or 24H2

**Comment by droidmonkey** [comment]
Install latest version of the vc redistributable. https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170#visual-studio-2015-2017-2019-and-2022

**Comment by TESTER-sec** [comment]
Perhaps have KeePassXC provide a notification that a vital VC Redistributable is missing from the system?

**Comment by TESTER-sec** [comment]
> Install latest version of the vc redistributable. https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170#visual-studio-2015-2017-2019-and-2022

Thank You! Very much appreciated.

**Comment by droidmonkey** [comment]
https://github.com/keepassxreboot/keepassxc/pull/11469
