### ISSUE TITLE
Password generator - add maximum occurrence limiter to advanced settings

### ISSUE THREAD

**Issue by cfoegen-gvboces** [keepassxreboot/keepassxc#11494]
## Summary
Some websites require password to have "no more than _n_ repeating characters" in the password. 
(For context, many website _actually_ mean no more than _n_ **occurrences** of characters in a password.) 

Adding a "No more than ___ occurrences of any character" under the **Advanced** settings of the password generator would be very helpful for these situations. 

This would especially save time and increase (user) security by discouraging password(s) from being copied from/to KeePassXC to search for + edit out characters over the threshold in other software. 

## Context
Many of the websites I run into this issue with are government websites, and often pair this restriction with forced password changes every 30 days or so. 

These restriction combine to cause users (like me) to eventually manually edit generated password to fit the requirements, which is a time consuming process that causes quite a bit of frustration when the password is lengthy. 

## Examples
This would be an **Advanced** feature in the password generator, as it _does_ decrease the generated password quality. 
One way this feature could potentially work without causing too much of a decrease in generated password quality, would be to automatically check each generated password to verify it fits the requirements and automatically regenerate until one is found. 
There are a couple issues I see with this, however: 
 
1. Password generation time could increase by a significant amount 
2. This setting, paired with user-restricted character + length settings, could result in an impossible to generate password 

A warning / flag could mitigate 1, and a timeout could mitigate 2, although I'm sure there are better solutions for this which would not cause these issues in the first place. 

I do understand that this may be a difficult feature to add, and may affect a small number of users, but I also know those users (like me) would greatly appreciate this functionality. 

Thank you!  I truly appreciate your time and efforts to make KeePassXC as robust and reliable as it is.

**Comment by droidmonkey** [comment]
I appreciate your situation having been forced through these byzantine password requirements in the past. However, we have actively decided not to introduce any more counter-productive features to the password generator. This requirement to restrict repeating (or even worse occurring) letters is the single most harmful restriction. Eliminating repetition _significantly_ reduces the search space for passwords and that situation is made worse the longer the password is. The hard truth is that systems implementing these policies are likely vulnerable to a whole manner of attacks that render passwords useless to begin with.

My recommendation is to just manually apply the known restrictions to the generated password directly and move on with life. NIST formally changed the requirements to eliminate these dumb rules and its only a matter of time before they are expunged from systems.

**Comment by cfoegen-gvboces** [comment]
Thank you for taking the time to explain! 
I suppose in the grand scheme of things when it comes to security, if it _can_ be abused, it will be. 
In the mean time, I will continue to work around their requirements, and hope the day comes soon when all of these rules _are_ removed. 

Thank you, again!
