### ISSUE TITLE
Not so much an issue...

### ISSUE THREAD

**Issue by mbrockman1** [keepassxreboot/keepassxc#1149]
Just want to say the contributors and core team behind KeePassXC is amazing! Keep up the great work! The program is really amazing, I have been recommending it like crazy, and would be willing to donate/lend a hand with a custom iOS/Android app if it is possible to be done in Python/Kivy. All in all, thank you so much, I am extremely appreciative of such a great community and program!

**Comment by droidmonkey** [comment]
Thank you so much for the kind words!

**Comment by phoerious** [comment]
Thanks a 😉
