### ISSUE TITLE
Option for fuzzy search

### ISSUE THREAD

**Issue by wnhrt** [keepassxreboot/keepassxc#11499]
## Summary

The option for a kind of 'fuzzy search' (aka approximate string matching) in
- the main search bar
- the auto-type search bar

## Examples

If following entries are given

1. Example Work Account
2. Example Private Account

entering the search string "exw" should show only entry number 1.

or

1. title: "Service X" username: "admin"
2. title: "Service X" username: "user"

entering the search string "sxu" should show only entry number 2.

## Context

For some cases I got similar entries, like multiple accounts for the same service.
When searching for a single entry I have to type the whole name, use the arrow keys or switch to mouse to select a lower one, if it is not the first hit.
This feature would make searching for a single entry a little easier.

**Comment by droidmonkey** [comment]
We have full support for regex in searching, use the * prefix. We also support wildcards naturally (*, ?, |).

Your example would look like:

`*title:ex.* w` or `title:ex* w`
