### ISSUE TITLE
Important design issue / Bug?

### ISSUE THREAD

**Issue by VirrigaAsta** [keepassxreboot/keepassxc#11495]
Important design issue / Bug

This issue pertains to the toolbar.

The post deletion button in the database is positioned next to the copy username key, leading to three instances of inadvertent post deletion.

Consider relocating, removing, or implementing confirmation for this button.

Although I've maintained backups and avoided major problems, such accidental removals could be detrimental to users without backups.

Apart from this am I very happy with your software.

**Comment by droidmonkey** [comment]
By default, deleting actually just moves the entry to your database recycle bin. There is _always_ confirmation prior to permanent deletion. You can enable recycle bin confirmation in the application settings.
