### ISSUE TITLE
Keepassxc is distorted and no longer accepts input / output after the computer is woken up from power saving mode in combination with multi-monitor setup and windows 11

### ISSUE THREAD

**Issue by bitfim** [keepassxreboot/keepassxc#11496]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

The title says it already, but here is a little more context:

I have a Laptop with a TB4 dock and a external display. I use the internal display and the external display on a daily basis. The internal display is 3820x2400 with a scaling of 175%. The external display is 7680x2160 (yes thats correct) and the scaling is at 125%.

I switch the laptop to power-saving mode every evening and wake it up in the morning. When I activate power saving mode, Keepass XC is located on the external display. When I take the laptop out of power-saving mode in the morning and after I have logged in, Keepass is still on the external monitor thanks to the the improved window management of Windows 11. 

But here is the problem: After taking the laptop out of power saving mode and logging in, the graphical user interface of keepass xc no longer responds to inputs and outputs. Also, the gui of keepass xc is a bit distorted, which means, that the sizes of the buttons in the menu bar, the sizes of the folder tree on the left side and and everything else looks like that the whole GUI is to big. It looks like the gui is 175% scaling even though its located on the display with 125% scaling.

I think this happens, because all windows on the external display will be moved to the internal display during the power saving process. I think thats because the external display is not available right after waking up the laptop again, so all windows are located on the internal display for a short time. The dock and monitor needs some time to reinitialize and after this is done, win11 window management moves all windows back to the external screen. 

I can solve this issue with a workaround: I manually move the Keepass XC window to the internal monitor and back to the external monitor. This changes the size of the keepass gui back to the correct scaling. After this action, keepass responds to inputs/outputs again and the GUI is scaled at 125% again. 

## Steps to Reproduce
[NOTE]: # 
1. Place the keepass xc window on the external monitor
2. Switch the laptop in the power saving mode in the evenig
3. Turn on the laptop in the morning and login
4. try to use keepass while its on the external monitor and notice, that its not accepting any inputs or outputs while the gui is a bit distorted
5. move the keepass window to the internal display and back to the external display solves this issue

## Expected Behavior
I would expect, that Keepass XC responds to inputs / outputs after power saving mode, with the correct scaling of the display where the keepass window resides.

## Actual Behavior
See above.

## Context
Laptop: Lenovo P16s Gen2, connect via TB4-cable to:
Dock: Lenovo TB4 Dock (40B0), connected via DP1.4 to:
External Display: Samsung Neo G9 G95NC 

Note:
KeePassXC - Version 2.7.9
Revision: 8f6dd13

Operating System: Windows 11 Enterprise 23H2

**Comment by droidmonkey** [comment]
Hello there, unfortunately this is a problem with Qt and not much (or anything) we can do about it. Scaling the UI is handled by Qt and not by our program. You can fiddle with the Qt environment variables that might better force a certain scale per monitor. Those are shown in our documentation: https://keepassxc.org/docs/KeePassXC_UserGuide#_command_line_options

Specifically QT_SCREEN_SCALE_FACTORS. 

Hopefully, when we update to Qt6, this will not be a problem anymore.

**Comment by bitfim** [comment]
So, you cant just implement a workaround for Qt5 which simply triggers what i do in the described manual workaround? Like moving the windows to the internal screen and back? Or read whats the scale on the screen where keepass resides and apply it after the program was moved from one screen to another?

And how should someone apply a start parameter to a running program? 

When will you update to Qt6 ?

Thanks

**Comment by droidmonkey** [comment]
Qt6 is planned for 2.8.0 release.
