### ISSUE TITLE
Add ability to restrict items to the browser extension based on connection ID

### ISSUE THREAD

**Issue by adityarsuryavamshi** [keepassxreboot/keepassxc#11505]
## Summary

I'm unaware if this is already possible, but I have glanced through the docs and explored the UI but couldn't find a way to achieve this.       
A user might have multiple browsers and in the browsers that support it have multiple profiles. KeepassXC differentiates between these with different connection ids, but currently there is no way to limit certain logins to appear only on certain connection ids.        
Please note that this is different from restricting items or subtrees from being used through browser extensions as a whole, but rather limiting specific items to appear through only through extensions in certain profiles.

## Examples

Firefox and chrome allow users to create profiles for any number of use cases. One of the common reason to create them is to separate work and personal sessions for example. These profiles are completely isolated (depending on the implementation, but afaik they are on Chrome and Firefox)  including the extensions and their associated datas.         
This feature would allow for this isolation to flow down further into the password manager, by creating and limiting work login items to be used only in work profile, personal login items to be used only in personal profile and so on.

## Context

The context in mentioned in the example. But to add further, a user might have multiple logins to a same service and it's not ideal if all the logins for the same service show up in every profile, especially when a browser profile might be configured with different set of expectations.

## Workarounds / Current State

I believe this can currently be achieved by having completely different databases for each browser profile. Though I haven't tested it myself, but looking at the docs it seems like it is possible, but is not ideal. It places unnecessary restriction on how I like to organize my passwords and adds additional requirement on me to remember multiple passwords for the databases.

I tried looking into the plugin data to see if I can add connection id to the entry and use that somehow in the extension, but the plugin data is read-only. Moreover this feature should be built into keepassxc and not in any area controlled by the extension, since keepassxc should be the one controlling access based on the connection ids, rather than the filtering happening on the extension (client) side.

**Comment by droidmonkey** [comment]
First make sure you are running version 2.7.9.

Then, create different groups/subgroups for each browser profile you would like to restrict to. Then edit each group and choose the browser connection name you want to restrict to.

![Image](https://github.com/user-attachments/assets/29c6a3b0-5bdc-4284-b1da-4c5ce7aadd1c)

**Comment by droidmonkey** [comment]
Oops sorry this is an upcoming feature in 2.7.10. 

https://github.com/keepassxreboot/keepassxc/pull/9852
