### ISSUE TITLE
Email field

### ISSUE THREAD

**Issue by ghost** [keepassxreboot/keepassxc#11503]
## Summary
Accounts typically have email requirements on top of a username. Logins often shift between wanting you to login with your email and password or username and password. Despite this common practice keepassxc lacks an email field in the normal entry section. This means you have to tuck emails in the notes section or do something like "myusrname | me@thatdoughmain.cat" in the username entry which breaks the quick copy. 

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )

![Image](https://github.com/user-attachments/assets/26c6efe1-b8e5-40c4-a674-bf37d6caf5a8)

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
Nothing unique about it...if you right click an entry to select credentials you have copy username, password, url, attributes but nothing for email which is more than not what you need rather than the username for the account. That said using the username for the email then leaves you having to stuff the actual user name in the notes or in the same field in a way that doesn't allow a quick copy paste and requires you to edit the entry to get the whole field where you can select either the email or the username depending on what a site requires.

**Comment by phoerious** [comment]
You can add a custom field in the advanced section.

**Comment by ghost** [comment]
Can you make that permanent for all entries moving forward? Will it have the drop down like the user name section for quick select if there is repeated use of a single one?

**Comment by phoerious** [comment]
There is no autocomplete of custom fields at the moment, but you can use them for browser copy/paste, autofill and Auto-Type.

**Comment by ghost** [comment]
Which is in part why I am adding the feature request, email shouldn't be custom. It should be a default on all entries with the drop down like on Username. It's far too common to need that to not have a default entry for it.

**Comment by phoerious** [comment]
That will be covered by #8228, so I'll close this as a duplicate.

**Comment by ghost** [comment]
Sorry for the duplicate, I searched before posting but language often misses things.
