### ISSUE TITLE
Segmentation fault when attempting to unlock the database via dbus on ScreenSaver signal

### ISSUE THREAD

**Issue by fertkir** [keepassxreboot/keepassxc#11512]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
I use a script which [automatically unlocks a database](https://github.com/keepassxreboot/keepassxc/discussions/5879#discussioncomment-3549429).
I cannot say for sure whether the issue happened on screen turning off, or turning on, but most probably on turning on.
When the screen turns on, [this signal is received from dbus](https://github.com/fertkir/utils/blob/main/keepassxc-unlocker/keepassxc-unlocker#L101) by my script and then the script [sends a dbus message to unlock a database](https://github.com/fertkir/utils/blob/main/keepassxc-unlocker/keepassxc-unlocker#L80).
After that KeePassXC isn't running any more.

I reproduced the issue in gdb and got the following log:
```
Thread 346 "Thread (pooled)" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffe2bfd6c0 (LWP 777)]
0x00005555556e9642 in Database::setKey (this=0x555556b02b60, key=..., updateChangedTime=updateChangedTime@entry=false, updateTransformSalt=updateTransformSalt@entry=false, transformKey=transformKey@entry=true) at /run/build/keepassxc/src/core/Database.cpp:863
863	        m_data.transformedDatabaseKey->setRawKey(transformedDatabaseKey);
```
I cannot say myself what can be wrong [on this line](https://github.com/keepassxreboot/keepassxc/blob/develop/src/core/Database.cpp#L859).

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. [Install and configure the keepassxc-unlocker script](https://github.com/fertkir/utils/blob/main/keepassxc-unlocker/README.md#installation).
2. KeePassXC database must be open.
3. Wait for Gnome turn off the screen on being idle.
4. Press any button to wake the Gnome up.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
KeePassXC should be running and a database should be unlocked.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
KeePassXC exits on SIGSEGV.

## Context
[NOTE]: # ( Give us any additional information you may have. )
Previously used the native package of KeePassXC on Fedora and experienced the same issue.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.9
Revision: 8f6dd13
Distribution: Flatpak

Qt 5.15.15
Debugging mode is disabled.

Operating system: KDE Flatpak runtime
CPU architecture: x86_64
Kernel: linux 6.11.8-300.fc41.x86_64

Enabled extensions:
- Auto-Type
- Browser Integration
- Passkeys
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 3.3.0

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: Gnome
Windowing System: Wayland

**Comment by droidmonkey** [comment]
I think you are maybe calling your script more than once in succession and we do not have a guard in place to prevent multiple simultaneous unlocks. So when the first one finishes the unlock, the second one runs into a crash because the underlying database instance is replaced with the unlocked one.

**Comment by droidmonkey** [comment]
Yup I just replicated the crash by doing exactly that (called dbus-send twice in a row).

**Comment by fertkir** [comment]
Apparently, I have to limit the number of dbus-send calls somehow. Thank you!
