### ISSUE TITLE
Auto-Type partially fails on Ubuntu

### ISSUE THREAD

**Issue by MichaeI-GH** [keepassxreboot/keepassxc#11510]
## Overview
Basically the title

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Select the desired entry
2. Press the keybinding or menu-entry for auto-type 

## Expected Behavior
The window closes & KeepassXC (KpXC) pastes username (un) & password (pw) into the previously selected window 

## Actual Behavior
The window only closes & nothing else happens (only un or pw has the same behaviour)  

## Context
Running on Ubuntu 24.04.1 LTS, haven't tried on Win or other Distros

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.8
Revision: (unsure)

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: Gnome
Windowing System: Wayland

Let me know if you need any further info!

**Comment by droidmonkey** [comment]
Auto-type is not supported on Wayland, yet. You are likely running keepassxc on x11 through xwayland and will only be able to Auto-type into other x11 windows.
