### ISSUE TITLE
Import via UI and show entries side-by-side

### ISSUE THREAD

**Issue by 2019-05-10** [keepassxreboot/keepassxc#11525]
## Summary
I've got several versions of a kdbx file, due to it being in use on different machines.
Thus it happens that the same account is stored in parallel, but with slight modifications (e.g. trailing /).
Trying to consolidate those files by importing leads to the same account being there multiple times since I don't have control about what is imported and how. 

Thus a UI that shows similar/conflicting entries side-by-side, and allowing to select what to import would be helpful.

**Comment by droidmonkey** [comment]
Use database merge feature, not import. 

See here for upcoming improvements already in the pipeline: https://github.com/keepassxreboot/keepassxc/pull/10173
