### ISSUE TITLE
Allow selecting separator character when exporting csv

### ISSUE THREAD

**Issue by ocp4711** [keepassxreboot/keepassxc#11522]
## Overview
This is between a bug report and a feature request: the comma is not suitable to separate data when exporting to csv. This works, but the exported data my be mangled.

## Expected Behavior
The data in csv export should be separated by a symbol that cannot be part of a password or note, ideally a "tab" character.

## Actual Behavior
The separator "comma" leads to unwanted separations e.g. of passwords that contain commas. 

## Context
KeePassXC 2.7.9
Operating System: Windows10

**Comment by matj1** [comment]
Aren't the commas in text fields escaped? I haven't tested it, but it seems that tabs can be in passwords or notes if they are copied there.

**Comment by ocp4711** [comment]
No, they are not escaped. They are in between quotation marks, but a separation routine as e.g. in Excel doesn't care about that.

**Comment by droidmonkey** [comment]
We should be writing fields wrapped in a text delimiter (eg, "). That is the real fix, not using an awkward character as a separator. 

We do wrap on quotes, so if excel is ignoring that then they are ignoring valid csv syntax. I did note that the new excel csv import tool is completely useless now.

**Comment by droidmonkey** [comment]
Actually reopening to glob onto my future export wizard work

**Comment by matj1** [comment]
> We should be writing fields wrapped in a text delimiter (eg, ").

What is a point of using an extra text delimiter in CSV? If no delimiter is used, if the separator is in a text field, it needs to be escaped. With text fields wrapped in delimiters, If the delimiter is in the text field, it needs to be escaped, which is similar but more complex.

**Comment by droidmonkey** [comment]
Well for one, multiline text, and also for this circumstance where you want to ignore separator character. CSV doesn't have a spec but it does have norms. Separator (comma) and delimeter (double quote) are the "standard". I mean it is called Comma Separated Values...

**Comment by ocp4711** [comment]
You are right, and even Excel knows this and deals with it. I just didn't look properly, the real problem in my case were CR-LF characters in the notes area. But this is not a bug, I have to apologize!

**Comment by matj1** [comment]
> Well for one, multiline text…

Correct me if I'm wrong here; this is my takeaway from this conversation: A text delimiter is used so there are ever needed only two characters to escape: the delimiter and the escape character. If someone would extend CSV to allow more complex structure needing more structural characters, the text fields would not change. But, without text delimiters, it is needed to escape the escape character and every structural character, which are comma, line break and other structural characters in a mentioned extension.

<details>

<summary>Examples of what I mean</summary>

With `"` as a text delimiter and `\` to escape:
```
"comma in a text field: → , ←"
"line break in a text field: → 
 ←"
"quotation mark in a text field: → \" ←"
"backslash in a text field: → \\ ←"
```

With no text delimiter and `\` to escape:
```
comma in a text field: → \, ←
line break in a text field: → \
 ←
quotation mark in a text field: → " ←
backslash in a text field: → \\ ←
```

</details>

> I mean it is called Comma Separated Values...

I have no idea how the name “Comma Separated Values” relates to text delimiters. Please, explain that.

**Comment by droidmonkey** [comment]
With respect @matj1 , you kind of hijacked this issue. It was originally about separators and not delimiters.

CSV generally does escaping by doubling the character, so escaping a double quote delimiter would actually look like:

`"Text with ""quotes"""`
