### ISSUE TITLE
missing German translation for some tooltips

### ISSUE THREAD

**Issue by HaraldHoe** [keepassxreboot/keepassxc#11528]
In the toolbar some tooltips are not translated to German.
See framed entries in the screenshot.

KeePassXC - VERSION: 2.7.9

![Image](https://github.com/user-attachments/assets/be2e8038-7403-4862-917a-fb9bdbd9a474)

Best regards,
Harald

**Comment by droidmonkey** [comment]
Head on over to https://transifex.com/keepassxc/keepassxc to provide translations. These are likely already completed and will be part of the next release though.
