### ISSUE TITLE
In browser check _all_ databases for an account w/o the need to switch focus in UI

### ISSUE THREAD

**Issue by 2019-05-10** [keepassxreboot/keepassxc#11526]
## Summary
To keep scopes apart I use different databases that are open at the same time.
Say, private P, family F, business B.
All three are open at the same time.

When I need to login in browser, I need to ensure that database containing that account has focus in UI.
If another DB has focus, the browser plugin does not find the account. I need to open the UI, switch the focus and try again in browser.

Confusingly, though, when I need to *create* a new account, the browser plugin asks into which DB I want to store it and offers its subcategories.   
So, it is able to read all open DBs at the same time, and thus should be able to check for a matching account in all DBs as well.

**Comment by droidmonkey** [comment]
Enable "search all open databases" from the browser settings page.
