### ISSUE TITLE
The window closes immediately or is just black.

### ISSUE THREAD

**Issue by matj1** [keepassxreboot/keepassxc#11523]
## Overview
The window of KeePassXC immediately closes or shows only black when I open it instead of the password prompt. This began happening on all 2 of my PCs at similar times recently.

## Steps to Reproduce
1. Have KeePassXC set to minimize to tray after opening.
2. Click the tray icon and the button to show the window.
3. Behold.

## Expected Behavior
I would see the password prompt to unlock the database and otherwise use the program normally.

## Actual Behavior
Usually, the window closes immediately. Sometimes, the window is there but just black. When I hovered the mouse pointer over where the password field would be, it changed to a vertical line, so I guess that the prompt was there, but, when I tried to input the password, it did nothing.

<details>

<summary>Screenshot of the black window</summary>

![The black window](https://github.com/user-attachments/assets/5654044c-e614-4e16-bba5-85560444b13f)

</details>

## Context
KeePassXC - Version 2.7.9
Revision: 8f6dd13

Qt 5.15.16
Debugging mode is disabled.

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 6.12.1-arch1-1

Enabled extensions:
- Auto-Type
- Browser Integration
- Passkeys
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 3.6.1
----
Operating System: Arch Linux
Desktop Env: Gnome
Windowing System: Wayland

**Comment by droidmonkey** [comment]
Did you do updates recently on both pc's?

**Comment by matj1** [comment]
I expect that the error started happening after an update, but I can't check that, so I did not state that in the original post.

**Comment by phoerious** [comment]
I suspect a graphics driver issue. Please try with the AppImage.

**Comment by matj1** [comment]
The AppImage does the same thing. It seems like a problem with Wayland because It works for me on X11.

**Comment by droidmonkey** [comment]
Closing since this is a system issue. If you are running keepassxc on X11 while on Wayland than the fault could be with xwayland. If you are running Wayland native than it's likely a driver or compositor issue.

**Comment by matj1** [comment]
@phoerious How would AppImage affect a graphics driver issue?

**Comment by phoerious** [comment]
Most likely, it wouldn't, that's the point. But there could be differences due to different Qt versions.
