### ISSUE TITLE
Scaling issues with higher resolution screens present

### ISSUE THREAD

**Issue by EmilEmilchen** [keepassxreboot/keepassxc#11524]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Install any KeePassXC version under Wayland with a high resolution screen
2. Open KeePassXC
3. 

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
KeePassXC looks normal, like on a 1080p screen.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
KeePassXC looks like this, note the small icons at the top:
![Image](https://github.com/user-attachments/assets/a4353927-0a09-41d7-aa29-c9d859f8268f)
Note that I'm using the latest pre-release version here but the problem also occurs in the latest stable release
Some text is not fully visible:
![Image](https://github.com/user-attachments/assets/8ebe0fcc-7b89-4eac-a2dc-63c1be7f6f0a)
And so on:
![Image](https://github.com/user-attachments/assets/9e78c0b0-f965-482f-8643-95a648261921)

## Context
[NOTE]: # ( Give us any additional information you may have. )
This only happens when a 4k screen is present, it doesn't have to be the one KeePassXC is open(ed) on. When I disable or unplug the 4k screen and just use a 1080p screen when starting KeePassXC it looks fine: 
![Image](https://github.com/user-attachments/assets/4e473515-c2fc-42e4-8da6-1299719e84b9)
Weird thing to me is that some parts of the GUI look just fine, e.g. icons are wrong though.
And this also happens when I'm just using the 4k screen.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.8.0-snapshot **ALSO HAPPENS IN STABLE**
Build Type: Snapshot
Revision: 9a63e80

Qt 5.15.16
Debugging mode is disabled.

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 6.12.1-arch1-1

Enabled extensions:
- Auto-Type
- Browser Integration
- Passkeys
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 3.6.1

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux (arch)
Desktop Env: KDE
Windowing System: Wayland

**Comment by droidmonkey** [comment]
You will likely need to define Qt environment variables that specify your screen scaling ratios. Such as QT_SCREEN_SCALE_FACTORS. This is a common problem on Linux and Qt, especially with non-whole number scales. 

See our documentation here: https://keepassxc.org/docs/KeePassXC_UserGuide#_command_line_options

Closing unless you can specify something that is specific to keepassxc behavior.
