### ISSUE TITLE
KeepPass Main Application only reacts once to Browser Extension "open Database" request

### ISSUE THREAD

**Issue by LetItGlow** [keepassxreboot/keepassxc#11536]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

When using the Browser Extension to unlock the DB, the Main Program Window to unlock the DB only gets opened once.
KeepassXC has to be restarted OR the DB opened manually, before the next prompt of the extension can appear.
KeepassXC does not crash.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Start KeepassXC and let it sit in the Systray.
2. Open Chrome/Firefox/any supported browser, which has the Browser Extension installed.
3. Click the Extension
4. Click the blue button to open your DB
5. KeepassXC Main Window pops up.
6. Immediately close that window with [X], so it returns back to the systray.
7. Click the blue button in the Browser Extension again, as in Step 3 & 4.
8. Nothing happens. <- issue
9. Unlock your DB manually (temporary workaround)
10. Lock it again
11. The extension button (or any other interaction) is able to prompt another unlock.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

Get prompted to open the Database again, when the Main window was closed **before** the DB was unlocked.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

Nothing. KeepassXC  won't respond to additional Extension "open DB" requests.
When this issue is in effect, KeepassXC webpage interaction is entirely broken; cannot login, unless manual intervention. 

## Context
[NOTE]: # ( Give us any additional information you may have. )

(No idea what to write here, window go poof, no worky)

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.9
Revision: 8f6dd13

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows
Desktop Env: Windows
Windowing System: Windows

**Comment by droidmonkey** [comment]
Never experienced this before. Do you have always on top enabled?

**Comment by varjolintu** [comment]
https://github.com/keepassxreboot/keepassxc/pull/11435 Try the snapshot build?

**Comment by LetItGlow** [comment]
> Never experienced this before. Do you have always on top enabled?

Not that I am aware of. I can put another window over KC, so no. 
I was already checking, if the Main window is buried under another. nothing.

**Comment by LetItGlow** [comment]
> [#11435](https://github.com/keepassxreboot/keepassxc/pull/11435) Try the snapshot build?

I tested this issue now with the KPXC snapshot:

KeePassXC - Version 2.8.0-snapshot
Build-Typ: Snapshot
Revision: 9a63e80

Works normally. The issue is not there.

**Comment by droidmonkey** [comment]
Looks like we fixed the problem, it will be part of the 2.7.10 release.
