### ISSUE TITLE
KeeShare deletes an entry from the database from which it was imported

### ISSUE THREAD

**Issue by dev-deeper** [keepassxreboot/keepassxc#11534]
## Overview
If you have two databases with two groups each (one for export and one for import), then after an entry is completely deleted in the database that imports the entry, it is also deleted in the database that exported the entry.

## Steps to Reproduce
![Image](https://github.com/user-attachments/assets/23d73b4c-fb7a-45e0-8e62-be37a86370f4)

1. Create databases "db_A.kdbx" and "db_B.kdbx".
2. Create 2 groups in each database named “import” and “export”.
3. Save databases.
4. For db_A “export” group set KeeShare settings as follows:
   - Type: “Export”
   - Path: ”./db_A_export.kdbx.share”
   Save the db_A database. “db_A_export.kdbx.share” created at this point.
5. For db_B “export” group:
   - Type: “Export”
   - Path: ”./db_B_export.kdbx.share”
   Save the db_B database. “db_B_export.kdbx.share” created at this point.
6. For db_A “import” group:
   - Type: “Import”
   - Path: ”./db_B_export.kdbx.share”
   Save the db_A database.
7. For db_B “import” group:
   - Type: “Import”
   - Path: ”./db_A_export.kdbx.share”
   Save the db_B database.
8. In the db_A “export” group create entry “entry_A” and save database. After that, “entry_A” appeared in “import” group of db_B.
9. In the db_B “import” group delete “entry_A”. Now “entry_A” moved to Recycle Bin. Go to Recycle Bin and delete “entry_A” for good.
10. Save the db_B database.
11. At this point, “entry_A” has completely disappeared in db_A.

## Expected Behavior
The entry remains in the parent database in which it was created.

_or, in the worst case, "is moved to Recycle Bin" or "marked as deleted in the export group"._

## Actual Behavior
The entry has completely disappeared from the database in which it was created. The entry is not in the Recycle Bin or anywhere else.

## Context
Me and my friend have two personal databases and we want to share some entries with each other. We can't use KeeShare in "Synchronize" mode because of 
1) we don't have permanent assess to shared folder or cloud, so we use a third-party point-to-point synchronization tool [via local directory]
2) in "Synchronize" mode shared file is updated every time you save database. So when we update our personal databases at the same time, the shared database is overwritten on each side and future syncs fail due to the shared database modified time conflict.

So I decided to use separated Import/Export groups. It works perfectly and as expected up to the point described above: when a database imports an entry and after deleting it on the importing side, the entry disappears on the exported side as well.

I expected that, If a database imports an entry in KeeShare "Import" mode, it should not be able to delete that entry in the parent database.

Apparently it might have something to do with UUIDs and writing changes via imported files, I'm not exactly sure how it works under the hood.

## Technical details
KeePassXC - Version 2.7.9
Revision: 8f6dd13

Qt 5.15.11
Debugging mode is disabled.

Operating system: Windows 11 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.22631

Enabled extensions:
- Auto-Type
- Browser Integration
- Passkeys
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 3.1.1

Operating System: Windows 11 23H2

**Comment by droidmonkey** [comment]
I appreciate the work put into this post but we are well aware. Please see https://github.com/keepassxreboot/keepassxc/issues/6477
