### ISSUE TITLE
Subgroups not included in Keeshare

### ISSUE THREAD

**Issue by wol-win** [keepassxreboot/keepassxc#11537]
## Overview
Keeshare Funtionality is supposed to share every credential within a selected shareable group including subgroups as per user documentation.
Subgroups are currently not shared, though.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Create a group with two or more subgroups
2. Create in each group at least one credential set
3. Share the group on the top level
4. Open the shared database file separately, the subgroups won't appear

## Expected Behavior
all groups and subgroups with the corresponding credentials should appear in the shared database

## Actual Behavior
Open the shared database file separately, the subgroups won't appear

## Context
n/a

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.9
Revision: 8f6dd13

Qt 5.15.11
Diagnosemodus ist deaktiviert.

Betriebssystem: Windows 11 Version 2009
CPU-Architektur: x86_64
Kernel: winnt 10.0.26100

Aktivierte Erweiterungen:
- Auto-Type
- Browser-Integration
- Passkeys
- SSH-Agent
- KeeShare
- YubiKey
- Schnelle Entsperrung

Kryptographische Bibliotheken:
- Botan 3.1.1

[NOTE]: # ( Pick choices based on your environment )
see above

**Comment by droidmonkey** [comment]
#3045

**Comment by wol-win** [comment]
Then at least the documentation should be updated, accordingly as it reads:

"Sharing Credentials
If you checked Allow export in the Sharing settings you can now share a group of passwords. Sharing is always defined on a particular group. If you enable sharing on a group, every entry under this group, and its children, are shared. If you enable sharing on the root node, every password inside your database gets shared!"

**Comment by droidmonkey** [comment]
Every _entry_. Read the whole sharing section, there is a very clear discussion on this quirk.

**Comment by wol-win** [comment]
Sorry - the documentation is clear, if I share the root, every password in my database will be shared, hence also all in groups, thus groups are shared, too.

The same is a conclusion of ChatGPT, too.

The documentation of KeepassXC read "Sharing Credentials
If you checked Allow export in the Sharing settings you can now share a group of passwords. Sharing is always defined on a particular group. If you enable sharing on a group, every entry under this group, and its children, are shared. If you enable sharing on the root node, every password inside your database gets shared!" Are groups now shared, too?

ChatGPT:
The statement you quoted from the KeePassXC documentation indicates that sharing is applied to groups. Specifically:

Sharing at the group level: If sharing is enabled for a particular group, all password entries within that group (including subgroups or "children") are shared.
Sharing at the root level: If sharing is enabled for the root node, all entries in the database are shared.
Thus, groups themselves are effectively shared in the sense that their contents (password entries and child groups) become accessible when sharing is enabled. If you were asking whether the structure or definition of groups (such as group names or hierarchy) is also shared, the documentation implies that this is likely included, as sharing applies to all contents of the specified group or root node.

If you want to confirm exactly what "sharing" includes (e.g., metadata like group names or other structural information), it would be a good idea to review further details in the settings or test the feature in a secure environment.

So, documentation is misleading, and needs update.

**Comment by droidmonkey** [comment]
![Screenshot_20241205_191300_Edge.png](https://github.com/user-attachments/assets/b4e12d40-01c5-49cd-be22-b69a701764a0)
