### ISSUE TITLE
Text labels on the database buttons should no longer move when hovering over them

### ISSUE THREAD

**Issue by 4jNsY6fCVqZv** [keepassxreboot/keepassxc#11541]
https://github.com/user-attachments/assets/05ef13fb-afe1-4711-b5cd-6ad6859648ff

I use the latest Flatpak version in Fedora Workstation 41.

**Comment by droidmonkey** [comment]
Already reported and fixed, thank you

**Comment by 4jNsY6fCVqZv** [comment]
@droidmonkey Thank you, the fix will be released with version 2.8?

**Comment by droidmonkey** [comment]
2.7.10
