### ISSUE TITLE
Do not empty the start window with last opened files (stored on NAS)

### ISSUE THREAD

**Issue by Etamuk** [keepassxreboot/keepassxc#11546]
**Problem:**
I am using three different databases, two of them are stored on my local NAS. Because macOS often loses the connection to my NAS almost every night, I have to remount the NAS by clicking on the volume icon in finder. This I have to to before I open KeePassXC. Sometimes I forget to remount the NAS and when then I open KeePassXC, the start screen of KeePassXC shows an error message (way of "cannot find the files...") and the files stored on the NAS were removed from the start window.
In KeePassXC -> _Preferences_ -> _General_ I set to remember the last uses files.

**My wish:**
After opening KeePassXC without connection the the NAS the start window does remove the files which are not available. 
After that I have to reopen the files every time.
I wish KeePassXC would remember the files in the start window (shown as tabs) and the three tabs with the last opened files would stay. The possibility to see the last opened files as tabs is fine because I regularly switch between the databases. 

Using  an local Mac with macOS 15.1.1 and KeePassXC 2.7.9

Thank you for your time to read this.
Kind regards

**Comment by droidmonkey** [comment]
Duplicate request to #9539
