### ISSUE TITLE
Autotype with custom keyboard shortcut doesn't start autotype (MacOS)

### ISSUE THREAD

**Issue by cramsvik** [keepassxreboot/keepassxc#11547]
## Overview
Custom keyboard shortcut for Autotype does not start autotype. Not sure if standard shortcut works, as some other software on my Mac already uses that. When starting autotype using the mouse menus it works as expected. The mouse menu shows the default key sequence even if a custom sequence is defined.

## Steps to Reproduce
1. Edit settings and set custom global auto-type shortcut
2. Try starting Autotype using the custom keyboard shortcut

## Expected Behavior
Expect autotype to start by asking if I want to autotype into the previously open window.

## Actual Behavior
Nothing seems to happen at all. No question to confirm, no autotype.

## Context
Screenshots didn't work (KeePassXC is "invisible"), but I managed to capture the mouse menu showing the shortcut default even if settings says " ^ +  SHIFT + A ".

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.9
Revision: 8f6dd13

Qt 5.15.11
Debugging mode is disabled.

Operating system: macOS 14.5
CPU architecture: x86_64
Kernel: darwin 23.5.0

Enabled extensions:
- Auto-Type
- Browser Integration
- Passkeys
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 3.1.1

**Comment by droidmonkey** [comment]
Global Auto-Type is for when you are _not_ in the keepassxc window. You can read about the difference in our user guide: https://keepassxc.org/docs/KeePassXC_UserGuide#_auto_type
