### ISSUE TITLE
need to open some keepass 2.53 database

### ISSUE THREAD

**Issue by dominix** [keepassxreboot/keepassxc#11554]
I am not able to open some database made with keepass 2.53.
which version should be the more compliant with keepaas 2.53 that can use on a Macintosh ?
thanks for your feedback.

**Comment by phoerious** [comment]
The current version is compatible. We need more information about your problem in order to help you.

**Comment by droidmonkey** [comment]
Are you using any plugins?

**Comment by dominix** [comment]
thank you everyone. I have installed last version of Keepassxc (with brew) use default config and try to open a database.kdbx provided  by an ancient maintainer  but when I enter the provided password I got the message:
"error while reading the database invalid credential were provided please try again, if this reocur then your database may be corrupt".
the provider told me that only 2.53 version of keepass can be used.
I'm stuck here. no plugin for my side.

**Comment by droidmonkey** [comment]
Unfortunately there is nothing we can do. Please download KeePass 2.53 to confirm the database actually works.
