### ISSUE TITLE
Add Support for the Ecosia Browser

### ISSUE THREAD

**Issue by stadler** [keepassxreboot/keepassxc#11556]
## Summary
Currently KeepassXC seems not to support the [Ecosia Browser](https://www.ecosia.org/browser).
The KeepassXC Browser Extension can be installed in Ecosia, as it is Chromium based, but it seems that the KeepassXC App itself does not allow for it to be connected. It allows various Browsers like Vivaldi, Brave or Tor Browser, but not Ecosia.

It would be nice if it would also allow Ecosia or at least extend the documentation to add other custom browsers.

I would expect:
* the KeepassXC Settings to contain a new entry for Ecosia in the Browser-Integration Section
* the KeepassXC Browser Extension to find the Database when clicking on Connect in the Connected Databases Section

## Context
I would have loved to switch to the Ecosia Browser. But unfortunately this will not happen if there is no support for KeepassXC.
So many unplanted trees. 😢

**Comment by droidmonkey** [comment]
We support custom browsers on Linux and macOS. Windows usually works by the browser re using chrome or mozilla registry entries. See our troubleshooting guide for more info: https://github.com/keepassxreboot/keepassxc-browser/wiki/Troubleshooting-guide
