### ISSUE TITLE
More Technical Documentation

### ISSUE THREAD

**Issue by Doodeletion** [keepassxreboot/keepassxc#11559]
Is there a more technical documentation than the user guide? I was looking for more details on the encryption/decryption process.

**Comment by droidmonkey** [comment]
https://keepass.info/help/kb/kdbx.html

This is the best we have right now

**Comment by Doodeletion** [comment]
Thanks for the quick reply!
Is opening an issue for asking questions on specific features (e.g. browser integration, yubikey support) fine or should issues only be opened for bug reports and feature requests?

**Comment by droidmonkey** [comment]
Use the discussions feature on github

**Comment by Doodeletion** [comment]
Wow, I totally forgot about that github feature. Thanks!
