### ISSUE TITLE
Searchbar in textfield in Notes area of an entry

### ISSUE THREAD

**Issue by svargh** [keepassxreboot/keepassxc#11558]
## Summary
I paste huge sensitive text file into KeePassXC Notes area for some entries 
I want to search for text within that area. 

Similar to firefox when pressing Ctrl+F, 
then a searchbar shows up, then jumping to the occurrences and also highlighting is possible.

Currently, I have to copy , then paste the text in an editor, then search for the text.
Sometimes I forget to clear clipboard.

The current global search is not sufficient, it finds the entry. But I do not know where exactly the occurrence is

## Examples

![Image](https://github.com/user-attachments/assets/aa105b5b-e4a6-4501-bb45-f4154837a7e5)

## Context
Note is used  mostly Markdown/Plain text files containing instructions for the team how to proceed and how
to use the data in the entry

**Comment by droidmonkey** [comment]
This is a duplicate request
