### ISSUE TITLE
HaveIBeenPwned Support?

### ISSUE THREAD

**Issue by agnosticlines** [keepassxreboot/keepassxc#1155]
I saw an earlier feature request for the HIBP password list, which I don't think is a good idea. But would it be possible to have "Have I Been Pwned" integration into the password manager? With maybe a right click option to check for account compromise?

There's already a plugin for Keybase 2 that exists to do this. Would be cool to see it in this project.

**Comment by TheZ3ro** [comment]
Duplicate/Related to #551

**Comment by evolverine** [comment]
Was this truly a duplicate of #551? The way I understand @agnosticlines's request (and it might be wrong) is that it checks the emails for existing breaches. I'd definitely like to see something like that.

**Comment by droidmonkey** [comment]
We aren't implementing any other HIBP features.
