### ISSUE TITLE
Implement support for hybrid transport of passkeys (CTAP2)

### ISSUE THREAD

**Issue by afontenot** [keepassxreboot/keepassxc#11569]
Issue relevant to this feature request:

1. Passkeys are single-factor login credentials. A user may have created a passkey for one device (like a phone) on a website that mandates the use of passkeys (using biometric identification on the device, for example).
2. Once the passkey login is enabled, the device with the passkey is the only device able to login to the account. The user wants to add a passkey to her desktop machine, on which KeepassXC is installed.
3. In order to do this, the user must be able to activate a passkey on her desktop, which is not able to log into the site. Sites using passkeys may support [hybrid transports](https://fidoalliance.org/specs/fido-v2.2-rd-20241003/fido-client-to-authenticator-protocol-v2.2-rd-20241003.pdf#__WKANCHOR_8w) for activating additional passkeys.
4. Unfortunately, KeepassXC currently only supports adding passkeys through the browser extension, i.e. on a site that the user is already logged into.

As a result, the user has to purchase a FIDO2 USB key which can be activated on the phone, in order to access the passkey from her desktop. (The above describes a real situation [encountered by a user of research.gov](https://www.research.gov/research-web/content/rgovsignin), a National Science Foundation site.)

Proposal:

KeepassXC implements support for the fido:/ hybrid transport mechanism described in the specification. This would involve communicating with devices via BLE (for proof of device proximity) - most laptops now have the Bluetooth hardware required for this to work. Support for decoding QR codes would be an optional component - initially, support for copy/pasted fido:/ links would be sufficient.

**Comment by droidmonkey** [comment]
In your example, you would just register a second passkey with the service through keepassxc. 

To use your passkey on the phone, you would bypass the keepassxc passkey dialog and use the native tools of windows or macos to use the blue tooth method.

**Comment by afontenot** [comment]
> To use your passkey on the phone, you would bypass the keepassxc passkey dialog and use the native tools of windows or macos to use the blue tooth method.

I see - is this supposed to be something automatically triggered by the browser? I'd be interested in seeing a table of browser / platform support for this. The (real) user situation I described was Firefox + Linux.

Edit: sorry for overlapping edits. Looks like the relevant search term is "cross device authentication", and Firefox doesn't support this unless the platform supports platform authentication. Supposedly Chrome does support this, but testing Chromium + Linux on research.gov doesn't show the option for CDA, possibly indicating that research.gov doesn't support this option.

**Comment by droidmonkey** [comment]
Yup, cross device authentication. That's not something keepassxc will support. Going to close this as a result. Thank you!

**Comment by afontenot** [comment]
Fine with closing, but just for clarification, the request wasn't that KeepassXC support CDA, but that it support hybrid transport for adding passkey credentials to devices without CDA support. Cheers

**Comment by droidmonkey** [comment]
CTAP is in draft, it isn't ready for any implementation. Also this isn't something implementated by a third-party authenticator like us (right now), it's implemented by the application requesting authentication (ie, the browser or operating system) and an OS authenticator (your phone).

> This protocol is intended to be used in scenarios where a user interacts with a Relying Party (a website or native app) on some platform (e.g., a PC) which prompts the user to interact with a roaming authenticator (e.g., a smartphone).

**Comment by benjuade** [comment]
> Fine with closing, but just for clarification, the request wasn't that KeepassXC support CDA, but that it support hybrid transport for adding passkey credentials to devices without CDA support. Cheers

@afontenot it seems that KeepassDX (the android app) will support something like this in the future: https://github.com/Kunzisoft/KeePassDX/issues/1421#issuecomment-3092629336
