### ISSUE TITLE
[Feature Request] Jump from entry to its group

### ISSUE THREAD

**Issue by lonix1** [keepassxreboot/keepassxc#11560]
## Summary
Feature to navigate from entry to its containing group.

## Examples
When right-clicking an entry, the context menu should show "Focus on containing group".

OR

When an entry is selected, the bottom panel shows a breadcrumb widget of its location. Maybe that can be changed to a button, which if clicked, would jump to that group.

## Context
I often search for some entry. Once found, I need to locate its group. That isn't easy.

**Comment by droidmonkey** [comment]
This is already a feature when searching. Double click the group name in the group column to jump to it. If you don't see a group column when searching then you hid it and need to right click the top header and show it again. 

Clicking the text labels in the entry preview panel is already a requested feature.

**Comment by lonix1** [comment]
> Double click the group name in the group column to jump to it

Weird UX but doesn't matter - it works!

Thanks.
