### ISSUE TITLE
Triangle is larger when entries are collapsed

### ISSUE THREAD

**Issue by NickWick13** [keepassxreboot/keepassxc#11568]
The triangle is larger when the sidebar entries are collapsed, compared to when they are expanded. I am using KeepassXC 2.7.4.

![Image](https://github.com/user-attachments/assets/800151f0-9519-41aa-ba39-e3d2fd9eaa53)
![Image](https://github.com/user-attachments/assets/21b5c770-5c2d-4ff8-9a2e-efcb7fa6642f)

**Comment by droidmonkey** [comment]
I've attempted to fix this but couldn't and won't be investing more time into it. Thank you for reporting, though.

**Comment by xboxones1** [comment]
@droidmonkey, This is easy to fix, [here](https://github.com/keepassxreboot/keepassxc/blob/f2ed4e38409ddc3ae208c57f0015e9c2de9e87de/src/gui/styles/base/BaseStyle.cpp#L1032) set the value to 1.0

**Comment by droidmonkey** [comment]
Can you add that to your style pr?

**Comment by xboxones1** [comment]
ok, I'll add to my pr
