### ISSUE TITLE
when setting up TOTP, all other entries get an empty otp attribute and other custom attributes behave weirdly as well

### ISSUE THREAD

**Issue by quantenzitrone** [keepassxreboot/keepassxc#11579]
At first this is just a UI bug, but when opening an entry and saving it, it potentally leads to data loss.

## steps to reproduce

1. create a new database
    - idk if any settings matter but i am able to reprudce it on the default settings
2. create 2 entries in the database
    - give them distinguishable titles e.g. "1" and "2"
    - give each of them an `Additional attribute` e.g. "test" with distinguishable values e.g. "1" and "2"
3. open entry "1" and `setup TOTP`
    - value of the TOTP doesn't matter ("aaaa aaaa aaaa" works)
4. from here, the `Additional attributes` should be glitched out
    - open entry "2", but don't save (click on `Cancel` to close the entry)
      - has an empty "otp" attribute 
      - the "test" attribute stil has the value to "2"
    - open entry "1", don't save again
      - otp attribute should be as expected
      - "test" has changed to "2"
5. quit KeepassXC and open it again, with the same database
    - the visual glitch is gone:
      - entry "1" has working otp attribute and test=1
      - entry "2" has no otp attribute and test=2

If, instead of clicking on "Cancel", any entry is saved or values of attributes are changed back, to what they are supposed to be, or emtpy otp attributes are attempted to be removed, the values in the database change, potentially losing some data. I for example lost a TOTP i just created, because i tried to remove an empty otp attribute and probably other stuff, i'm not sure what i did exactly. The also don't fully understand the behavior of which values are glitched in which way. I could regenerate the TOTP fortunately, so nothing bad happened.

## Debug Info

KeePassXC - Version 2.7.9

Qt 5.15.15
Debugging mode is disabled.

Operating system: NixOS 25.05 (Warbler)
CPU architecture: x86_64
Kernel: linux 6.12.3

Enabled extensions:
- Auto-Type
- Browser Integration
- Passkeys
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 3.6.1

## screenshots

![entry 1](https://github.com/user-attachments/assets/5a3698e2-f0c3-45d4-b0e3-2586046421a0)
entry 1 with attribute test=1

![entry 2](https://github.com/user-attachments/assets/374ec54a-ca95-4e9f-a71a-eacfdf93cae7)
entry 2 with attribute test=2

![Image](https://github.com/user-attachments/assets/6c0cead2-4fe6-4d8f-b41e-aeeb34040084)
adding TOTP to entry 1

![Image](https://github.com/user-attachments/assets/d6c5370d-8255-49aa-aabf-2a285ceddb09)
entry 2 has empty otp attribute

![Image](https://github.com/user-attachments/assets/795e2bc2-79fe-456a-96d9-09dbeacdc85d)
entry 2 has attribute test=1

![Image](https://github.com/user-attachments/assets/c51b3b5e-adc9-476f-a183-67c286ec7012)
after quitting and reopening, visual glitch is gone
(entry 2 has test=2 and no otp attribute)

**Comment by droidmonkey** [comment]
Please include a screenshot

**Comment by quantenzitrone** [comment]
i added some screenshots, they don't show much more than i described in the steps to reproduce tho...
hope it helps anyway

**Comment by droidmonkey** [comment]
This will no longer be possible with 2.7.10, setting up TOTP while editing an entry is disabled (for this and other reasons). As a result this issue is completed and closed since a fix is already in place in the code base pending release.
