### ISSUE TITLE
Clipboard is not cleared after timeout

### ISSUE THREAD

**Issue by Racer84** [keepassxreboot/keepassxc#11577]
Although the "Clear clipboard after" option set I still can paste password after timeout is elapsed.

**Comment by Racer84** [comment]
I run Ubuntu 24.04.1 LTS. KeePassXC debug info:

```
KeePassXC - Version 2.7.8
Revision: f6757d3
Distribution: Snap

Qt 5.15.11
Debugging mode is disabled.

Operating system: Ubuntu Core 22
CPU architecture: x86_64
Kernel: linux 6.8.0-49-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- Passkeys
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.19.1

```

**Comment by droidmonkey** [comment]
You are running wayland (most likely) and clearing clipboard from snap and Gnome desktop environment is not supported in that deployment mode as of right now. You can try installing `wl-clipboard` which might resolve the problem.

**Comment by Racer84** [comment]
I'm running xorg, not wayland.

**Comment by droidmonkey** [comment]
There should not be a problem in that case.

**Comment by Racer84** [comment]
But there is. Looks like gpaste2 interferes. Meanwhile I've switched to apt version of KeePassXC - problem remains.

**Comment by droidmonkey** [comment]
Please direct your concern to gpaste2, they aren't honoring clearing or password mime data.
