### ISSUE TITLE
Use Secure Desktop for password entry!!!

### ISSUE THREAD

**Issue by billionaireevgenii** [keepassxreboot/keepassxc#11573]
Hello, dear developer!
Please make a setting in the program as it is implemented in “VeraCrypt” (Use Secure Desktop for password entry). 
In VeraCrypt we were able to make password entry secure. 
Do the same in KeePassXC
This is a very important setting that gives security to password entry and sensitive data, which will prevent spies from seeing!!!! 
Please add it to the program.
Thank you in advance!
![Image](https://github.com/user-attachments/assets/773679f8-bc1c-44c5-95f4-6f4f9625f2a0)
![Image](https://github.com/user-attachments/assets/f3c570e5-b6db-49ad-b5ce-7326f2a20b60)

**Comment by michaelk83** [comment]
@billionaireevgenii this has been discussed at length in #3460 .
Re-posting the same duplicate issue multiple times, even as a different username, will not change the result.

**Comment by droidmonkey** [comment]
Don't feed the spam bot
