### ISSUE TITLE
Feature Request: Add option "I have a hardware key" instead of displaying list of hardware keys

### ISSUE THREAD

**Issue by HUGHUSR** [keepassxreboot/keepassxc#11572]
Feature Request

I like the "I have a keyfile" selection change that was made a few versions back. I would like to see a configuration option to do the same for hardware keys, instead of displaying a list of hardware keys. Reason: Don't give someone who obtains access to your device a clue that there is a hardware key available for KeePassXC to use.

This is how I'd like to see this work:

There would be an application-wide option of "Do Not List Hardware Keys", which if enabled, would not show the list of hardware keys detected. If the "Do Not List Hardware Keys" is selected, regardless of whether there is or is not a hardware key detected, KeePassXC would always display a prompt of "I have a hardware key"--just like the "I have a keyfile" selection currently is always displayed.

The "Do Not List Hardware Keys" option should have a sub-option of either "List Hardware Keys" or "Prompt for Key Serial#", such that when "I have a hardware key" is selected, then either the available hardware keys are listed (current behavior) or the user is prompted to enter the hardware key serial number (enter the number, NOT select from a list!).

This feature would add some obscurity to whether a hardware key is available for use by KeePassXC. (I use Yubikey Nanos plugged into USB-C cables, obscured among the snake-pit of cables emanating from my 4 nested docks and two external displays, and I'd challenge someone to even notice their existence without having to inspect every cable accessible to my MBP. Thus, I'd like to be able to obscure my YubiKeys existence even more by not having KeePassXC announce their presence to the world.

Thanks in advance for considering this request!

**Comment by droidmonkey** [comment]
Disable remembering keys in the application settings, already a feature. 

Anyway, if I have access to a collection of your hardware keys I'm going to plug them in and try them out anyway so this really doesn't offer any additional security or protection at all.
