### ISSUE TITLE
Increase master password security against brute force

### ISSUE THREAD

**Issue by MacGitty** [keepassxreboot/keepassxc#11571]
To enhance security, implement the following delays for incorrect master password attempts:
Second wrong attempt: 1-minute delay before retry.
Third wrong attempt: 5-minute delay before retry.
Fourth and more wrong attempts: 10-minute delay before retry.  

This enhanced security feature can be ideally enabled/disabled as option (of course only when the database is opened ;-))

**Comment by droidmonkey** [comment]
Security for guessing attacks is provided by Argon2 KDF. Increase the "time" requirement in the database settings if you need/want additional protection.
