### ISSUE TITLE
The cli `-d` option for `--dryrun` is not recognized

### ISSUE THREAD

**Issue by pintert3** [keepassxreboot/keepassxc#11570]
I tried running a dry-run for the `merge` command for two databases, but the `-d` option wasn't recognized whereas the long option `--dry-run` was yet they should both work, according to the man page.
First command that failed:

```bash
keepassxc-cli merge -ds kees.kdbx kees2.kdbx
```
Second that worked:

```bash
keepassxc-cli merge --dry-run -s kees.kdbx kees2.kdbx
```

**Comment by droidmonkey** [comment]
We corrected the documentation for next release

**Comment by droidmonkey** [comment]
We corrected the documentation for next release
