### ISSUE TITLE
Enable global auto-type to have wildcard style matching

### ISSUE THREAD

**Issue by 02browns** [keepassxreboot/keepassxc#11576]
### Overview
When using global auto-type the URL has to match exactly or the window title has to have the words in the exact order for it to be a valid suggestion in the auto-type window. As some websites have very specific login URLs or window titles it would be useful to be able to have a global setting for wildcard matching to keep things neat and streamlined when adding new entries or if websites make small changes, not having to edit an entry to get it to work.

Adding a window association for an entry with wildcard asterisks (`*ptcgp*` for example) does make it work how i'd like, but i'd prefer to not have an additional config step when adding every single entry in the database. So would it be possible to add an option for global auto-type to match entries as if they have wildcards for whole words and URL suffixes?

For example:
- The entry title "**PTCGP Tracker - Pokemon**" would match with the window title "**PTCGP Tracker - The Ultimate Companion for Pokémon TCG Pocket Players**".
- And the URL "**https://ptcgp-tracker.com/**" would match with "**https://ptcgp-tracker.com/user/login?_gl=1*1p2hdc9*_up*MQ..*_ga*MTg3NjYzNTE0Mi4xNzM0NTI0MTM2*_ga_V7H8BXCWSQ*MTczNDUyNDEzNS4xLjAuMTczNDUyNDEzNS4wLjAuMA..**"

### Context
Using KeepassXC 2.7.9 on Windows 10

**Comment by droidmonkey** [comment]
We already match (roughly) to your examples. Your first example is not a match, you would need to remove the "- Pokemon" suffix since that is not in the window title.

Here is the code we use:

```
auto windowMatchesTitle = [&](const QString& entryTitle) {
    return !entryTitle.isEmpty() && windowTitle.contains(entryTitle, Qt::CaseInsensitive);
};

auto windowMatchesUrl = [&](const QString& entryUrl) {
    if (!entryUrl.isEmpty() && windowTitle.contains(entryUrl, Qt::CaseInsensitive)) {
        return true;
    }

    QUrl url(entryUrl);
    if (url.isValid() && !url.host().isEmpty()) {
        return windowTitle.contains(url.host(), Qt::CaseInsensitive);
    }

    return false;
};
```

We already do `* title *` for window title by using "contains". We also already match the hostname of the url using the same `* urlhost *`.
