### ISSUE TITLE
Password Syntax Coloring

### ISSUE THREAD

**Issue by enigmafyv** [keepassxreboot/keepassxc#11585]
### Have you searched for an existing feature request?

- [x] Yes, I tried searching

### Brief Summary

I'm making the move from Bitwarden to KeePassXC and am a new user.  So far, I like what I see, but one feature of Bitwarden, which I'm surprised hasn't been implemented in any other software a long time ago is syntax coloring for the different character types in the password field.  

### Example

This helps the user understand whether similar characters, such as an l (el) or 1 (one), or a O (oh) and 0 (zero), are being used.  It coloring alpha characters separate from numeric, separate from special symbols and so on.  See Bitwarden for example.

### Context

This helps prevent accidental mistyping of the wrong letter or number.

**Comment by droidmonkey** [comment]
Go to application settings, scroll to bottom, enable "Show passwords in color"

**Comment by enigmafyv** [comment]
OK, thanks, but in its current state, it's a bit flawed.  I did enable this, but it wasn't apparent on the one password I looked at since I only looked at this on only one of my passwords after enabling it and I initially couldn't see the difference between the green and blue.  Is there a way to change the colors used so they contrast more?  This would definitely be an accessibility (color blind) issue and I'm not color blind, but whoowee, the green and blue are almost identical on a dark interface.

The other problem with this is, syntax coloring is not available in the field you're typing the password in when its revealed.  I have to save and reveal the password on the main window to see if my entry was entered correctly.  If not then I have to edit the entry again to update it.  Having to take so many steps just to confirm is a bit of an inconvenience.

Just to clarify, numbers are blue and uppercase letters are green, and they're VERY close in color in the dark theme.

**Comment by droidmonkey** [comment]
This is the implementation we settled with. There is unlikely to be much more effort put in besides offering the ability to view the password in a pop up window, very large font, and color. That is already tracked in a different feature request.

**Comment by droidmonkey** [comment]
Looks like the feature request I was thinking of was closed, I reopened it for consideration: https://github.com/keepassxreboot/keepassxc/issues/7006
