### ISSUE TITLE
GPG Agent: Does not remove ssh key from agent

### ISSUE THREAD

**Issue by halacs** [keepassxreboot/keepassxc#11589]
### Have you searched for an existing issue?

- [x] Yes, I tried searching and reviewed the pinned issues

### Brief Summary

* KeepassXC: 2.7.9
* OS: Ubuntu 23.04.1 LTS
* UI: Cinnamon 6.0.4
* gpg: gpg (GnuPG) 2.4.4
* ssh: OpenSSH_9.6p1 Ubuntu-3ubuntu13.5, OpenSSL 3.0.13 30 Jan 2024

Keepassxc adds ssh key to my agent but unable to remove it. There is no error message, just `ssh-add -L` command still shows all ssh keys even that one was expected to be removed.

Neither `ssh-add -D`  command can remove it and key survive system reboot and exiting from keepassxc.

To remove that ssh key, I had to follow instructions found at https://unix.stackexchange.com/questions/185393/gpg-agent-doesnt-remove-my-ssh-key-from-the-keyring :

```
Yes, it seems that ssh -d is broken with gpg's agent. Here is a workaround using a different command.

Run the gpg-connect-agent command from the commandline to connect to the agent. Then, from the prompts there, enter this command to list the ssh keys

KEYINFO --ssh-list --ssh-fpr

You should see something like:

S KEYINFO 3365433C34421CC53B52C9A82169FD2328CF610B D - - - P df:a2:36:8d:ad:88:b3:cc:00:96:10:d4:c9:2c:e0:df - S
OK

Now, to remove the from the agent:

DELETE_KEY 3365433C34421CC53B52C9A82169FD2328CF610B

It will say:

OK

Now, quit with the BYE command:

    BYE OK closing connection

Now, verify with ssh-add -l and you will see that it is gone for real.
```

### Steps to Reproduce

1. create entry, attach ssh private key
2. configure entry to use attached file as ssh key
3. save entry and click on "Add to agent" button. Check if ssh key shows the new key with `ssh-add -L`
4. click on "Remove from agent" button. `ssh-add -L` still shows that key in the output
5. interact with `gpg-connect-agent` cli tool to remove key

### Expected Versus Actual Behavior

After click on the `Remove from agent` button, key should not be visible in the output of `ssh-add -L` command.

### KeePassXC Debug Information

```Text

```

### Operating System

Linux

### Linux Desktop Environment

Mate / Cinnamon

### Linux Windowing System

X11

**Comment by droidmonkey** [comment]
> Neither ssh-add -D command can remove it and key survive system reboot and exiting from keepassxc.

> Yes, it seems that ssh -d is broken with gpg's agent

> As with most things GPG, ssh credentials are cached inside the .gnupg directory, specifically in ~/.gnupg/sshcontrol

This isn't a KeePassXC problem then. You will need to use an ssh-agent that isn't broken or doing things you don't desire.

**Comment by halacs** [comment]
I use YubiKey for SSH authentication with GPG, unfortunately, that's why I use gpg-agent. I don't know any other agent could fit to my needs because of this. Thank you for your quick response and Merry Christmas!

**Comment by droidmonkey** [comment]
You can use another agent and set XDG_SSH_AGENT to point to a different daemon file for comms between KeePassXC and the agent (maybe). For awareness, KeePassXC just sends 'standard' ssh-agent messages to the daemon file which get picked up by the agent for execution. We do not implement our own agent or make CLI calls.

It is possible that GPG is just storing the key fingerprint (public portion) and the private key is not actually present on the ssh-agent once you remove it. Have you tried using the key after reboot or removal from KeePassXC's side? If the key doesn't work or prompts for a file then that means the private key is not being stored external to KeePassXC.

**Comment by halacs** [comment]
`Have you tried using the key after reboot or removal from KeePassXC's side?`

Yes, I tried it and I could log in with it via SSH so both private and public key is present it seems.

**Comment by droidmonkey** [comment]
That's an unfortunate behavior of gpg agent
