### ISSUE TITLE
Preview panel crops group icon if larger than 16x16

### ISSUE THREAD

**Issue by Generator** [keepassxreboot/keepassxc#1158]
## Expected Behavior

Show a resized group icon to fit preview panel

## Current Behavior

Group icons larger than 16x16 get cropped in preview panel

## Possible Solution

~~Always resize group icon to 16x16~~
Pull request https://github.com/keepassxreboot/keepassxc/pull/1142

## Steps to Reproduce (for bugs)

1. Create a new group
2. Add an icon larger than 16x16

## Context

Group with icon an icon 32x32
![shot_icon_32x32](https://user-images.githubusercontent.com/44146/32254901-ed96bb2c-be9b-11e7-9ba7-a0ba077ccf5f.png)

Entry with icon larger than 16x16 are shown correctly
![shot_icon_128x128](https://user-images.githubusercontent.com/44146/32254921-060fbcc6-be9c-11e7-8ae3-4354e6852bef.png)

## Debug Info

KeePassXC - Version 2.2.2
Revision: e100ba8

Libraries:
- Qt 5.9.2
- libgcrypt 1.8.1

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 4.13.10-1-ck-core2

Enabled extensions:
- KeePassHTTP
- Auto-Type
- YubiKey

**Comment by Generator** [comment]
Using the patch https://github.com/keepassxreboot/keepassxc/pull/1142 fixes the issue
![shot_icon_128x128-fixed](https://user-images.githubusercontent.com/44146/32255329-f6f28752-be9e-11e7-9af0-4bf09341d4fa.png)

**Comment by TheZ3ro** [comment]
Seems that I fixed the entry icon but not the group icon when developing the preview panel
