### ISSUE TITLE
Menu becomes temporarily unavailable when viewing DB settings before immediately opening App settings

### ISSUE THREAD

**Issue by enigmafyv** [keepassxreboot/keepassxc#11586]
### Have you searched for an existing issue?

- [x] Yes, I tried searching and reviewed the pinned issues

### Brief Summary

While viewing the database settings and the app settings, I pressed the gear (cog) settings button a few times which toggled between the two settings windows.  If I was last on the app settings and I cancelled the screen from the lower right 'Cancel' button, it would go back to the DB settings, but the text and button menus would become unavailable (disabled) to some extent.   I would have to click the gear another time to re-open the app settings and cancel again and this would make the menu active once again.   With the combination of moving between the DB settings and the app (which disables the menus), by clicking the gear settings button, this puts the menu is an odd state.

CAUSE: By opening the App settings, this is what throws the menu into a semi-disabled state, but by opening the DB settings before opening App Settings, it locks the menu into a semi-disabled state until you re-open and close the app settings for a subsequent time.

### Steps to Reproduce

To Break
1. File (menu) > Database Settings (or press CTRL+SHIFT+,)
2. Click settings (gear) button under text menu (or press CTRL+,) to open App settings
3. Cancel App settings with the Cancel button in bottom right (or press ESC)
4. Cancel DB settings with Cancel button in bottom right (or press ESC)
Menu becomes semi-disabled <<< HERE IS WHERE THE INTERFACE BREAKS/MISBEHAVES

To Fix: Open and close app settings once more
1. Click settings (gear) button under text menu (or press CTRL+,)
2. Cancel App settings with Cancel button in bottom right (or press ESC)
Menu becomes available once again

### Expected Versus Actual Behavior

Expected: When exiting any settings, the menu should become available.
Actual: See above

### KeePassXC Debug Information

```Text
KeePassXC - Version 2.7.9
Revision: 8f6dd13

Qt 5.15.11
Debugging mode is disabled.

Operating system: Windows 11 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.22631

Enabled extensions:
- Auto-Type
- Browser Integration
- Passkeys
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 3.1.1
```

### Operating System

Windows

### Linux Desktop Environment

None

### Linux Windowing System

None

**Comment by droidmonkey** [comment]
This is already fixed for our next release: https://github.com/keepassxreboot/keepassxc/pull/11047

You can try it out from https://snapshot.keepassxc.org
