### ISSUE TITLE
Passkeys stills how up after being denied

### ISSUE THREAD

**Issue by lajawi** [keepassxreboot/keepassxc#11596]
### Have you searched for an existing issue?

- [x] Yes, I tried searching and reviewed the pinned issues

### Brief Summary

Passkeys still open up, even though I explicitly denied a passkey for a website.

### Steps to Reproduce

1. Find or create a passkey for a website in your database (e.g. Github)
2. Explicitly deny it for aforementioned website
   - When newly created, try logging in, it should ask for permission to use the credentials, deny it
   - If you choose a previously created one, go into it's properties, and remove the entry `KeePassXC-Browser Settings`
4. Try logging in with passkey: the window for passkey still shows up

### Expected

Passkeys that have been denied shouldn't show up. If no allowed passkeys are available, it should fall back to Windows' default passkey window.

### Actual Behaviour

KeePass XC' passkey window still shows up, with the previously denied passkey.

### KeePassXC Debug Information

```Text
### Client (Windows 11)

KeePassXC - Version 2.7.9
Revision: 8f6dd13

Qt 5.15.11
Debugging mode is disabled.

Operating system: Windows 11 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.22631

Enabled extensions:
- Auto-Type
- Browser Integration
- Passkeys
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 3.1.1

### Browser extension (Firefox)

KeePassXC - 2.7.9
KeePassXC-Browser - 1.9.5
Operating system: Win64
Browser: Mozilla Firefox 133.0
```

### Operating System

Windows

### Linux Desktop Environment

None

### Linux Windowing System

None

**Comment by droidmonkey** [comment]
Denied as in you cancel the passkey dialog?

**Comment by varjolintu** [comment]
Need better steps to reproduce this. I'm not sure what "deny" means here. You can deny an entry from KeePassXC side, or "deny" a site in the extension settings etc.

**Comment by lajawi** [comment]
> I'm not sure what "deny" means here

I'm referring to the `KeePassXC - Browser Access Request` window, and denying or disabling the passkey for the site from there. If you already allowed it, you'll need to edit the passkey, go to properties, and remove the entry called `KeePassXC-Browser Settings`, then reload the site, and then you'll see the aforementioned window.

**Comment by varjolintu** [comment]
I do not see the passkeys confirmation window if I deny (and remember) the option in the confirmation dialog. If I delete those settings, of course the dialog will still appear.

The only thing I discovered was that if I manually enter the username I previously registered, and try to authenticate that, KeePassXC then shows the confirmation window. Is this the dialog you mean?

**Comment by lajawi** [comment]
@varjolintu, it took me a while to find, here's an image of the popup I meant when talking about denying. When pressing `Deny All` or `Disable for this site` if the passkey shows up in this popup, the passkey can still be used for the site, which, in my eyes, it shouldn't because I explicitly denied it from being used for this site.

![Image](https://github.com/user-attachments/assets/96312c8f-32fe-4aee-bb15-d5fad900bedd)

**Comment by varjolintu** [comment]
For me that dialog does not appear if I choose "Deny All" (and remember it) or press "Disable for this site". I can still authenticate with the passkey if I manually write the username and then try to login with a passkey. That's the only bug I can find here.

**Comment by lajawi** [comment]
For me, even if I press either `Disable for this site` or `Deny All` with `Remember` turned on, KeePassXC' passkey window still shows up with the denied passkey.

**Comment by droidmonkey** [comment]
Do you have the passkey stored in a different entry than the one you denied? I don't think we show the allow/deny dialog for passkey-only entries.

**Comment by lajawi** [comment]
No, I specifically denied the passkey entry.

**Comment by droidmonkey** [comment]
Cannot replicate your findings:

https://github.com/user-attachments/assets/d65a3fa4-601a-4cb9-aada-e332533d2354

**Comment by lajawi** [comment]
> Cannot replicate your findings:
> 2024-12-26_10-01-26.mp4

In your attachement, I noticed you used the checkbox `Hide this entry from the browser extension` in `Browser Integration > General`. I was not aware of that setting, and tried setting the `KeePassXC-Browser Settings` under `Properties > Plugin Data` to `{"Allow":[],"Deny":["github.com"],"Realm":""}`, instead of the usual `{"Allow":["github.com"],"Deny":[],Realm":""}`.

This solved it.

**Comment by droidmonkey** [comment]
Yes so this is a UX quirk in my opinion. The Allow/Deny dialog is specifically for _password transfer to the browser_ and has nothing to do with the passkeys interface. If you want to deny access to a passkey you either need to scrub the url from the passkey fields (ie, break matching) or use the checkbox I pointed out. You can also deny access at the group level as well.

@varjolintu I truly don't think this is a bug, but we may want to document this divergence a little better.

**Comment by lajawi** [comment]
> The Allow/Deny dialog is specifically for _password transfer to the browser_ and has nothing to do with the passkeys interface

To me, they do feel quite similar, because both the normal passwords and passkeys are mainly used in the browser. If I deny access to a certain entry in my database, it shouldn't show up (or at least, it would make sense), no matter if it is a password or passkey entry.

**Comment by droidmonkey** [comment]
I disagree with this because passwords and passkeys are very very different in regards to information passed to the browser. The reason we have allow/deny for password access is because your secrets are then transmitted to the browser and subsequently the website you are visiting. We have pretty good protection from phishing, but nothing is foolproof.

With passkeys, your actual credential (private key) is NEVER passed to the browser, and is therefore much more secure to use. We offer the alternative of denying access to the entry (or group) entirely, but ultimately the whole point of storing passkeys in KeePassXC is to use them with the browser.
