### ISSUE TITLE
Enable modification of toolbar - removal of "Delete Selected Entries"

### ISSUE THREAD

**Issue by OSSfriend** [keepassxreboot/keepassxc#11606]
### Have you searched for an existing feature request?

- [x] Yes, I tried searching

### Brief Summary

Dear all,

I appreciate your efforts. Thank you very much for KeePassXC!

I have installed KeePassXC on my dads pc. Unfortunately, he mixes up "+" and "x" in the toolbar from time to time. Therefore I would like to hide/remove the button "Delete Selected Entries" from the toolbar.

I could not find a way to modify the toolbar. Could you help?

Kind Regards

**Comment by droidmonkey** [comment]
We changed the X to a trash can icon for our next release. We have decided to not put in the extra code for custom toolbar. Thank you for the suggestions though. 

You can also enable "Confirm before moving entry to recycle bin" in the application settings which will always show a prompt when you click the delete button. 

You can see the new toolbar here: https://github.com/keepassxreboot/keepassxc/pull/11047

**Comment by njwgh** [comment]
A solution has been proposed:
https://github.com/keepassxreboot/keepassxc/issues/12544
