### ISSUE TITLE
Multiple custom browser configurations

### ISSUE THREAD

**Issue by omnicortex** [keepassxreboot/keepassxc#11601]
### Have you searched for an existing feature request?

- [x] Yes, I tried searching

### Brief Summary

Currently, only one custom browser can be configured.  I would like to configure more than one custom browsers.

### Context

I normally use more than one browsers.  Currently I use Thorium and Zen Browser,  both require custom configurations.  Right now I can use KeePassXC with only one of them.

**Comment by droidmonkey** [comment]
We are not going to support the request, sorry. You can manually copy the configuration json file into each browsers folder.

**Comment by omnicortex** [comment]
@droidmonkey Would you give me more details how to do this?  Where is the `json` file and where should I copy it to?

**Comment by droidmonkey** [comment]
If you setup a custom browser in keepassxc then that's where the json file is located. Otherwise you'll have to consult your browsers documentation
