### ISSUE TITLE
passphrase could be a backdoor for yubikey or multiple yubikeys can be used

### ISSUE THREAD

**Issue by maxadamo** [keepassxreboot/keepassxc#1160]
YubiKey is known to be very robust, unless you step on it with your car. 

## Expected Behavior
Either yubikey and passphrase should be mutually exclusive, or there should be an option to use a second yubikey as a backup. 
LastPass has an option to add several yubikey: if one gets lost, damaged, or you simply don't have it with you, you use the other or you use the passphrase.

## Current Behavior
Passphrase and Yubikey, are not mutually exclusive

## Possible Solution
either let passphrase be mutually exclusive, or store more yubikeys that can be used in mutually exclusive way. 

## Steps to Reproduce (for bugs)
1. you loose your yubikey
2. you have lost all your passwords

## Context
YubiKey is known to be very robust, unless you step on it with your car. 

## Debug Info
KeePassXC - 2.2.2
Revision: n/a

Operating system: ANY
CPU architecture: ANY
Kernel: ANY

Enabled extensions:
- n/a

**Comment by TheZ3ro** [comment]
KeePass works in a different way than LastPass.
In KeePass the yubikey challenge is directly used in the masterkey actually improving the security of your database (it's how 2FA works, if you can login with only one of them you have a 1FA with 2 keys)

Also read this part of the FAQ [What happens if I break my YubiKey? Can I create backup keys?](https://keepassxc.org/docs#faq-yubikey-broken-yubikey)

**Comment by maxadamo** [comment]
Thanks for your answer. I didn't notice the I could reprogram the 2nd slot for the passive secret. 
Well, I know that LastPass works differently, but in theory, you could have two different secrets opening the same database. 
EXAMPLE: encrypted partition on Linux has 8 slots, to configure up to 8 secrets, and if you configure them all, you can decrypt the volume with one of these secrets.... but you don't need them all at once :) 
HAVING SAID THAT, thanks for your support. Your answer was indeed very helpful!
