### ISSUE TITLE
Login mainform auto-close on complete

### ISSUE THREAD

**Issue by bigalgeorge** [keepassxreboot/keepassxc#1161]
Trivial but when settings/minimize window on app start=unchecked, when user fills in login the mainform should minimize by default IMHO. Or you could add a setting; [x] Minimize after initial login

**Comment by phoerious** [comment]
I don't quite understand what your problem is. When that option is disabled, there is no reason why KeePassXC should automatically hide its window.

**Comment by bigalgeorge** [comment]
Its a minor UI change, but fixes an additional login step each time see video.
[Kazam_screencast_00001.mp4.zip](https://github.com/keepassxreboot/keepassxc/files/1483476/Kazam_screencast_00001.mp4.zip)
