### ISSUE TITLE
Code formatting

### ISSUE THREAD

**Issue by louib** [keepassxreboot/keepassxc#1168]
We now have a `clang-format` file that I think is pretty conform to the coding style that is manually enforced in the project. How would @keepassxreboot/core-developers feel about enforcing the format during CI?

That would probably require an initial formatting, which is the main problem I can see. It would involve pretty much all the files in the project, but then again it's something we've done in the past (for example for the copyright headers). After that, we could verify the code format directly from travis, and add `clang-format` as a cmake integration, so that contributors can format their code easily.

The initial formatting could be done before the next minor release (2.3.0), to avoid conflicts when backporting / upporting it could cause.

**Comment by droidmonkey** [comment]
I have found that there are no code checking services that support clang-format. These services are far more useful then a brute force check during CI. Can we convert (or add) to something else for format checking?

**Comment by adolfogc** [comment]
Here is a series of blog posts from the MongoDB team describing something similar:
- [Succeeding With ClangFormat, Part 1: Pitfalls And Planning](https://engineering.mongodb.com/post/succeeding-with-clangformat-part-1-pitfalls-and-planning/)
- [Succeeding With ClangFormat, Part 2: The Big Reformat](https://engineering.mongodb.com/post/succeeding-with-clangformat-part-2-the-big-reformat/)
- [Succeeding With ClangFormat, Part 3: Persisting The Change](https://engineering.mongodb.com/post/succeeding-with-clangformat-part-3-persisting-the-change)

**Comment by adolfogc** [comment]
Another tool that may be useful is [Clang-Tidy](https://clang.llvm.org/extra/clang-tidy/).
[Here](https://github.com/adolfogc/keepassxc/tree/apply-clang-tidy
) is a branch I made in which some of the code is refactored using some of Clang-Tidy's checkers (see the last 8 commits).

Example of how to use Clang-Tidy:
```
mkdir build && cd build
cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DWITH_XC_AUTOTYPE=ON -DWITH_XC_HTTP=ON -DWITH_XC_YUBIKEY=ON -DWITH_GUI_TESTS=ON ..
./run-clang-tidy.py -header-filter='.*' -checks='-*,modernize-use-nullptr' -fix
```

Reference: [*Clang-Tidy, part 1: Modernize your source code using C++11/C++14*](https://www.kdab.com/clang-tidy-part-1-modernize-source-code-using-c11c14/)

**Comment by louib** [comment]
@adolfogc thanks for the links! I just saw that the recent version of `clang-tidy` have the `-format-style` option, which allows to reuse the format style used for `clang-format`. If we can reuse the same style for both `clang-format` and `clang-tidy`, and use `clang-tidy` for style diagnostics, I think we would have a pretty complete solution for enforcing the styling convention for the project. I did not try the `-format-style` option yet though.

**Comment by adolfogc** [comment]
@louib Cool! I tried and it works fine.

In the example below, braces are added and the `clang-format` is also applied:
```bash
clang-tidy ../src/core/Base32.cpp -fix -checks="-*,readability-braces-around-statements" -format-style=file -p .
```
