### ISSUE TITLE
KeepassXC gpg verification with sig file output question

### ISSUE THREAD

**Issue by captainraccoon2** [keepassxreboot/keepassxc#1172]
Hi,

I downloaded the KeepassXC `.AppImage` file and was verifying it using first the `.DIGEST` file and then `.sig` file. While I was verifying the download using the `.sig` file I noticed something strange as I did not get the same results as displayed. **After importing the gpg keys and verifying the downloaded file I got the following output:** 

```
gpg2 --verify --keyid-format long KeePassXC-2.2.2-2-x86_64.AppImage.sig
gpg: assuming signed data in 'KeePassXC-2.2.2-2-x86_64.AppImage'
gpg: Signature made Tue 24 Oct 2017 09:15:18 AM PDT
gpg:                using RSA key B7A66F03B59076A8
gpg: Good signature from "KeePassXC Release <release@keepassxc.org>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: BF5A 669F 2272 CF43 24C1  FDA8 CFB4 C216 6397 D0D2
     Subkey fingerprint: C1E4 CBA3 AD78 D3AF D894  F9E0 B7A6 6F03 B590 76A8 
```

**Here's the output displayed on your guy's "[verify signatures page](https://keepassxc.org/verifying-signatures)"**:

```
$ gpg --verify KeePassXC-$VERSION-x86_64.AppImage.sig
gpg: assuming signed data in 'KeePassXC-$VERSION-x86_64.AppImage'
gpg: Signature made Fri 17 Feb 2017 05:20:55 PM CET
gpg:                using RSA key C1E4CBA3AD78D3AFD894F9E0B7A66F03B59076A8
gpg: Good signature from "KeePassXC Release <release@keepassxc.org>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: BF5A 669F 2272 CF43 24C1  FDA8 CFB4 C216 6397 D0D2
     Subkey fingerprint: C1E4 CBA3 AD78 D3AF D894  F9E0 B7A6 6F03 B590 76A8


```

It says that the signature was **"good"** when I verified the file I downloaded. I just curious about one thing why is your key id output a lot longer at **"using RSA key C1E4CBA3AD78D3AFD894F9E0B7A66F03B59076A8"** and mine only shows one sub key id "**using RSA key B7A66F03B59076A8**"? How do I get the same output as yours? Thanks!

By the way my gpg version is gpg (GnuPG) 1.4.20

**Comment by TheZ3ro** [comment]
This is because you are using long keyID but in the verify page we are using the full fingerprint.

If you look closely, the long keyID in your output it's exactly the same as the last 16 char in the fingerprint 

The part that really matters is
```
gpg: Good signature from "KeePassXC Release <release@keepassxc.org>" [unknown]
[...]
Primary key fingerprint: BF5A 669F 2272 CF43 24C1  FDA8 CFB4 C216 6397 D0D2
```
