### ISSUE TITLE
chromeIPass keeps getting disconnected

### ISSUE THREAD

**Issue by predmijat** [keepassxreboot/keepassxc#1173]
## Expected Behavior
It should not disconnect every now and then

## Current Behavior
At least once per day chromelPass says that there's no connection with KeePassXC. I press "Connect", name the connection (there already is KeePassHttp Settings in my KeePassXC), save the database, and then refresh the web page.

## Debug Info

KeePassXC - v2.2.0
Revision: caa49a8ef3ee28ed478192389b21d61107b3b8e0

Operating system: macOS

One thing that may be relevant is that I have more than one database opened, but I have selected "search all databases" in advanced options in Browser Integration.

**Comment by varjolintu** [comment]
Try [KeePassHTTP-Connector](https://chrome.google.com/webstore/detail/keepasshttp-connector/dafgdjggglmmknipkhngniifhplpcldb) instead.

**Comment by predmijat** [comment]
Just got the same thing with KeePassHTTP-Connector (should I open a new issue?) ...
<img width="372" alt="screen shot 2017-11-11 at 10 15 16 am" src="https://user-images.githubusercontent.com/8684411/32688026-6559a2ca-c6c9-11e7-96ea-64260578308b.png">
