### ISSUE TITLE
Security issues with KeepassXC

### ISSUE THREAD

**Issue by anshulbajpai** [keepassxreboot/keepassxc#1176]
There are two issues at the moment which I can see.

1. First Issue - If my database is locked, and I am on a webpage in a browser and hit global-auto-type shortcut then the KeePassXC unlock dialog is presented and I can see a blinking cursor in the password field in the unlock dialog. But when I start typing the database password, the actual typing happens on the original webpage in the browser. Basically, the context of the cursor is not switched to the unlock dialog and my password can be seen in clear text on the webpage which is a **security issue**. 
To avoid this happening, I have to manually click on the password field in the unlock dialog and then start typing the database password. 

![image](https://user-images.githubusercontent.com/291429/32603815-0984f44a-c543-11e7-98ef-cda35c6480ee.png)

2. Second issue - This issue is related to the previous issue. When I manually click on the password field in the unlock dialog and successfully unlock my database, I then see an alert dialog which says "Couldn't find an entry that matches the window title: secrets - KeePassXC". Basically, KeepassXC assumes that I am trying to find an entry for KeePassXC itself which is very weird to me. But then if without pressing "OK" on that alert, if I close the lid of my MAC or make my MAC sleep, the next time when I open my MAC, the database is still unlocked which is again a **security issue**. I managed to come across this when I opened my laptop in the morning and I could see my database is still open and there is an alert dialog which is still visible. 

![image](https://user-images.githubusercontent.com/291429/32603691-8ae22c7a-c542-11e7-8c66-b30671715b3a.png)

I'll appreciate if both these security issues can be taken care of.

Operating system: MAC-OS High Sierra
CPU architecture: x86_64
Kernel: XNU

**Comment by phoerious** [comment]
Your first problem is a Mac bug. See #1023.
The other one is probably because you accidentally hit the global autotype shortcut on your KeePassXC window.

**Comment by droidmonkey** [comment]
The staying unlocked when an alert dialog is visible is already an open issue.

**Comment by phoerious** [comment]
Closing this in favor of the existing reports.
