### ISSUE TITLE
Redesign of Custom Fields (Suggestion)

### ISSUE THREAD

**Issue by nemonein** [keepassxreboot/keepassxc#1177]
Thank you for your great effort.

It might be related with the issue #863 .
I'm using [mSecure 4](https://www.msecure.com/), not the online version(mSecure5), but the offline version which works similarly like Keepassxc.

Keepassxc can add custom fields(Additional attributes), but those attributes can be reached only 'Advanced' tab, not the main screen('Entry'), which is somewhat annoying to edit/see the entries.
mSecure can add custom fields as well, but added fields become the part of main attributes(fields), so it is accessible in the main screen.

With this feature enabled, #863's template also possible.
Added fields have to a part of Groups(or have to be assigned to Groups). For example, 'Credit card' group has fields 'Card Number', 'Expiry Date', 'PIN number', 'Card Holder's Name', etc, and 'Bank Account' group has 'Name', 'Account No.', 'Password', etc, and so on.

I don't know I made myself clear, but I hope you to understand.

**Comment by droidmonkey** [comment]
Closed in favor of #863
