### ISSUE TITLE
Unsaved changes in the entry view silently get discarded if escape is pressed

### ISSUE THREAD

**Issue by ydnax** [keepassxreboot/keepassxc#1181]
Pressing escape in an entry view after changing the entry or viewing a newly created (unsaved) entry silently discards all changes instead of asking the user weather they want to save the information.

## Expected Behavior
Keepassxc asks if the user wants to discard the unsaved changes.

## Current Behavior
Pressing escape simply closes the entry view thus discarding all changes if apply was not clicked before.

## Possible Solution
I think a simple Discard/Safe/Cancel dialogue would do the trick.

## Steps to Reproduce (for bugs)
1. Open an existing database or new one
2. Create a new entry or edit an existing one
3. Press escape
4. Changes are discarded without any further prompt

## Context
I've lost several new entries and changes to existing entries by pressing escape before clicking apply. 

## Debug 
KeePassXC - Version 2.2.2
Revision: 6d46717

Libraries:
- Qt 5.9.2
- libgcrypt 1.8.1

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 4.13.11-1-ARCH

Enabled extensions:
- KeePassHTTP
- Auto-Type
- YubiKey

**Comment by frostasm** [comment]
"Discard/Safe/Cancel dialogue" should also appear when we activate the "Cancel" button?

**Comment by droidmonkey** [comment]
I think the distinction here is pressing cancel and hitting the escape key. Actively pressing cancel is pretty obvious you intended to do that.

**Comment by frostasm** [comment]
@droidmonkey I checked the code and found that "Escape" action uses the "Cancel" button to perform the "Cancel" action (see code in **DialogyWidget::keyPressEvent** function). If you do not mind, I'll add a dialog with the questions displayed when the user clicks the "Cancel" button.

**Comment by droidmonkey** [comment]
Sure we can try it out

**Comment by frostasm** [comment]
@droidmonkey @TheZ3ro @phoerious can I use new connect syntax?
```cpp
connect(sender, &Sender::valueChanged, 
            receiver, &Receiver::updateValue);
```

**Comment by phoerious** [comment]
If it is supported by Qt 5.2, yes. Travis will frown at you if it's not. I know that lambdas are not supported, not sure about function pointers.

**Comment by frostasm** [comment]
I'll check and let you know :)

**Comment by frostasm** [comment]
I compiled sources with qt 5.2.1 and all works fine

**Comment by droidmonkey** [comment]
Is this opposed to using the SIGNAL and SLOT keywords?

**Comment by frostasm** [comment]
@droidmonkey yes
[qt wiki](https://wiki.qt.io/New_Signal_Slot_Syntax)  
[Signals and Slots in Qt5](https://woboq.com/blog/new-signals-slots-syntax-in-qt5.html)

**Comment by frostasm** [comment]
I started working on solving this problem.

**Comment by droidmonkey** [comment]
Oh wow new signal slot syntax is awesome, we need to convert to that, namespace would go a long way to clarifying code.

**Comment by frostasm** [comment]
@keepassxreboot/core-developers I have one more question. 

What kind of dialogue we need to show when activated the "Cancel" action?

It is necessary to determine the following things:

- Separate dialogs for new and changed entries?
- Message
- Buttons
- Default button

An example of a possible implementation: 
![image](https://user-images.githubusercontent.com/3104366/33121743-587a472c-cf7e-11e7-9049-c03bb101ca91.png)

New entry: 
![image](https://user-images.githubusercontent.com/3104366/33122070-cd9e7172-cf7e-11e7-837b-c9e2e1825ebb.png)


Changed entry: 
![image](https://user-images.githubusercontent.com/3104366/33122035-bfa2553e-cf7e-11e7-8ddd-2027f432ebf9.png)



Related links: 
[Designing a prompt for saving changes](https://ux.stackexchange.com/questions/65280/designing-a-prompt-for-saving-changes) 
[Should I use Yes/No or Ok/Cancel on my message box?](https://ux.stackexchange.com/questions/9946/should-i-use-yes-no-or-ok-cancel-on-my-message-box)

**Comment by phoerious** [comment]
Default button should either be Save or Cancel. I think Cancel would be safer, but from a power user perspective, Save would be more useful.

If you drop the word "new" from the first dialog, it should be generic enough for both cases. But I'd also be fine with different dialogs.

**Comment by droidmonkey** [comment]
Different dialogs for the same "purpose" are confusing. Merge dialogs into one as much as possible. Also reduces code.
