### ISSUE TITLE
Segmentation fault running 2.2.2 AppImage

### ISSUE THREAD

**Issue by garywill** [keepassxreboot/keepassxc#1182]
$ sha256sum KeePassXC-2.2.2-x86_64.AppImage
    439fc7d053861a9c266b72a5924063efed31d3d2752ae901c454c74ba0a9a149  KeePassXC-2.2.2-x86_64.AppImage

    $ cat KeePassXC-2.2.2-x86_64.AppImage.DIGEST 
    439fc7d053861a9c266b72a5924063efed31d3d2752ae901c454c74ba0a9a149  KeePassXC-2.2.2-x86_64.AppImage

    $ uname -a
    Linux  4.4.79-18.26-default #1 SMP Thu Aug 10 20:30:05 UTC 2017 () x86_64 x86_64 x86_64 GNU/Linux

    $ lsb_release -a
    LSB Version:	core-5.0-amd64:core-5.0-noarch:desktop-5.0-amd64:desktop-5.0-noarch:imaging-5.0-amd64:imaging-5.0-noarch:languages-5.0-amd64:languages-5.0-noarch
    Distributor ID:	openSUSE project
    Description:	openSUSE Leap 42.2
    Release:	42.2
    Codename:	n/a

    $ ./KeePassXC-2.2.2-x86_64.AppImage 
    Segmentation fault

running 2.1.0  fine

**Comment by phoerious** [comment]
Are you using the 2.2.2 or 2.2.2-2 AppImage?

**Comment by garywill** [comment]
2.2.2-2 runs fine
