### ISSUE TITLE
How to uninstall on Ubuntu?

### ISSUE THREAD

**Issue by csbenz** [keepassxreboot/keepassxc#1189]
I installed from ppa and want to uninstall keepassxc. Tried using ppa-purge and apt-add-repository but cannot unistall the app.
Any idea how to uninstall?

**Comment by magkopian** [comment]
Have you uninstalled the package itself before removing the repository?

**Comment by TheZ3ro** [comment]
`sudo apt remove keepassxc`

**Comment by csbenz** [comment]
@magkopian @TheZ3ro 
Yes, and I get 'Unable to locate package keepassxc'.
What else can I try?

**Comment by TheZ3ro** [comment]
Run the following command and report the output
`dpkg -s keepassxc`
`dpkg -S keepassxc`
`locate keepassxc`

Are you sure you have keepassxc installed?

**Comment by csbenz** [comment]
I managed to uninstall it thanks for your help, I think I had first removed the repository.
