### ISSUE TITLE
UI sluggish on macOS

### ISSUE THREAD

**Issue by Doridian** [keepassxreboot/keepassxc#1194]
On my Macbook Pro, it seems the UI is very slow to respond and work with.
Typing in the search and even scrolling has noticeable performance problems.

## Expected Behavior
Just like on Windows, I would expect it to be fluid and fast to use

## Current Behavior
Right now, it feels like I get about 5fps while KeePassXC skyrockets to 1 full core of CPU use when I scroll through my passwords

## Steps to Reproduce (for bugs)
1. Launch KeePassXC on macOS with a moderately sized DB (a few hundred entries maybe)
2. Try scrolling in the "Root" folder with all passwords or using search
3. See CPU usage spike and app lag around at 5fps

## Context
Trying to use KeePassXC normally, searching through my passwords, just want it to feel snappy.

## Debug Info
KeePassXC - Version 2.2.2
Revision: 6d46717

Libraries:
- Qt 5.9.1
- libgcrypt 1.8.1

Operating system: macOS High Sierra (10.13)
CPU architecture: x86_64
Kernel: darwin 17.2.0

Enabled extensions:
- KeePassHTTP
- Auto-Type
- YubiKey

**Comment by phoerious** [comment]
I would expect the problem somewhere beyond our own code. Has anybody else seen such problems?

**Comment by adolfogc** [comment]
I'm unable to reproduce this problem with my personal database. I also have many entries on mine, not sure how many though. I'm using:

```
KeePassXC - Version 2.2.2
Revision: 6d46717

Libraries:
- Qt 5.9.1
- libgcrypt 1.8.1

Operating system: macOS High Sierra (10.13)
CPU architecture: x86_64
Kernel: darwin 17.2.0

Enabled extensions:
- KeePassHTTP
- Auto-Type
- YubiKey
```

**Comment by weslly** [comment]
I can't reproduce this either on my personal database.

**Comment by Doridian** [comment]
Ok, I have further narrowed it down.
It happens due to the fact I use my Macbook's retina display in the rightmost "more space" setting (Looks like 1920x1200) and of course have the KeePass window appropriately sized (rather big).
If I swap to default scaling and make the window smaller, then it does not lag.

This is a UI profile of when it does lag. What is weird that switching to my dedicated AMD GPU does not make it better at all, and only KeePassXC (mis)behaves like that. Might be that I have  no other Qt-based apps and it is a Qt problem.

<img width="1341" alt="screen shot 2017-11-19 at 18 37 44" src="https://user-images.githubusercontent.com/631409/32993467-cebd382c-cd58-11e7-9c4e-8b165be3d0e0.png">
