### ISSUE TITLE
Alert users when using Debug builds

### ISSUE THREAD

**Issue by TheZ3ro** [keepassxreboot/keepassxc#1197]
## Context

Due to how we fixed #1137, if users are using debug build they are affected with possible infoleak and other things.
We are discussing to provide nightly builds for testing purposes and those needs to be debug build to have more information about errors/segfault/etc.

(see https://copr.fedorainfracloud.org/coprs/hifi/keepassxc-nightly/)

## Possible Solution

Users should get a big warning when opening KeePassXC debug build. Like:

**Warning: These builds enable debug symbols and also some debug messages that may expose sensitive information. Use with caution.**

**Comment by phoerious** [comment]
Why don't we just kick that debug message altogether?
