### ISSUE TITLE
SSH Agent: Error about unsupported (old) key format is ambiguous

### ISSUE THREAD

**Issue by hifi** [keepassxreboot/keepassxc#1198]
Only "modern" keys are supported, those are OpenSSH keys that have a header of `-----BEGIN OPENSSH PRIVATE KEY-----`. The key file encodes both the public and private key including the public key comment.

## Expected Behavior
More obvious way to guide the user to convert their key into the new format.

## Current Behavior
Error message: "This is not an OpenSSH key, only modern keys are supported"

## Possible Solution
Needs discussion.

## Context
Early testers don't know what these new keys are and how to convert.

**Comment by grimpy** [comment]
Didn't even know a new format exists it's not the default. To generate key with new format use `ssh-keygen -o`

**Comment by hifi** [comment]
@grimpy You can also convert old keys with `ssh-keygen -o -p -f id_rsa`, it's just a file format change.

**Comment by hifi** [comment]
This was fixed by #1450 and #1463.
