### ISSUE TITLE
Remove GetGitRevisionDescription dependency

### ISSUE THREAD

**Issue by droidmonkey** [keepassxreboot/keepassxc#12]
The sole purpose of this being here is to pull the hash of the last commit in the repo to display in the about dialog.

**Comment by rockihack** [comment]
Why do you want to remove the hash from the about dialog?

**Comment by droidmonkey** [comment]
The hash means absolutely nothing to anyone. It is not a security feature, and it doesn't even link to the commit on GitHub. It just shows a hash.

**Comment by TheZ3ro** [comment]
I think the hash is usefull if someone have manually compiled KeePassXC and want to fill an Issue (so we can track changes and bugs from that commit)

**Comment by samrocketman** [comment]
And for debugging purposes to know the exact build reporters use.

**Comment by TheZ3ro** [comment]
I think we can leave this as it's now, @droidmonkey ?

**Comment by droidmonkey** [comment]
Yah I'll close it.
