### ISSUE TITLE
[Feature Request] Run script on clipboard clearing

### ISSUE THREAD

**Issue by Hexawolf** [keepassxreboot/keepassxc#1201]
Personally I don't use any kind of clipboard manager, but as far as I know if you're messing with clipboard too much, password can be leaked. For example, by being saved to disk by clipboard manager (xfce4-clipman does that). Running scripts on clipboard clearing would be a good idea if you have some custom magic setup that requires additional actions to wipe out password from memory.

This issue can partially solve #926 but actually it's a more generic request rather than just a duplicate issue.

## Expected Behavior
Password successfully deleted from clipboard manager as well as the buffer itself.

## Current Behavior
Password is stored in clipboard manager and written to disk, usually unencrypted

## Debug Info
KeePassXC - Version 2.2.2
Revision: 6d46717

Libraries:
- Qt 5.9.2
- libgcrypt 1.8.1

Operating system: Linux
CPU architecture: x86_64
Kernel: linux 4.13.13-1-hardened

Enabled extensions:
- KeePassHTTP
- Auto-Type
- YubiKey

**Comment by phoerious** [comment]
I'm not entirely convinced that running third-party scripts to clear the clipboard is a good idea. I'd rather suggest you disable your clipboard manager or use Auto-Type.

**Comment by Hexawolf** [comment]
Taking *all* control over clipboard from user isn't a good idea as well.

**Comment by TheZ3ro** [comment]
Executing external script/commands isn't a good solution neither

**Comment by droidmonkey** [comment]
This will not be implemented.
