### ISSUE TITLE
[Feature Request] CSV import with created and modifed dates

### ISSUE THREAD

**Issue by mikeziri** [keepassxreboot/keepassxc#1208]
Hi,

I'm coming from 1password and just exported a csv file with all my data. 
two fields I'm interesting in importing in keepassxc are the created and modified dates for each entry so I wouldn't lose history.

would love to be able to have two new column selectors to identify them on the import window.

thank you,

**Comment by mkasberg** [comment]
I've been interested in digging into the codebase a little bit and trying to contribute something... Maybe I'll take a stab at this. I'll update here if I make any progress.

**Comment by njfox** [comment]
This feature should depend on #1305 since there currently aren’t last modified and created date fields in the entry view table, correct?

**Comment by droidmonkey** [comment]
That is just for display purposes. The fields exist in the backend

**Comment by phoerious** [comment]
Resolved in #1359.
