### ISSUE TITLE
Database Merge Gui Test Doesn't Use Action Properly

### ISSUE THREAD

**Issue by droidmonkey** [keepassxreboot/keepassxc#121]
## Expected Behavior

The database merge test should be using the action to ensure no regressions.

**Comment by phoerious** [comment]
What's the status on this? Since it has the "bug" label I haven't postponed it to 2.1.0 yet.

**Comment by droidmonkey** [comment]
I don't understand what the problem was anymore, closing for now since this will likely be overcome by the file sync work anyway.
