### ISSUE TITLE
KeePassHTTP should resolve reference to username

### ISSUE THREAD

**Issue by mabhub** [keepassxreboot/keepassxc#1211]
## Expected Behavior

`HTTP Confirm Access Dialog` list should display : `<entry title> - <entry refered_username>` as when username is not a reference to another one.

## Current Behavior

Instead of displaying username, dialog is displaying the raw reference.

![image](https://user-images.githubusercontent.com/1846633/33095741-0265f724-cf05-11e7-82a8-51597754fa85.png)

## Possible Solution

Wrap `entry->username()` from `src/http/AccessControlDialog.cpp#L47` with a method resolving the reference (if it is).

## Debug Info

KeePassXC - Version 2.2.0
Revision: 8a7de4408d47fefd1b4545fa1d5a3e1c8b2f6964

Libraries:
- Qt 5.5.1
- libgcrypt 1.6.5

Operating system: Ubuntu 16.04.3 LTS
CPU architecture: x86_64
Kernel: linux 4.6.0-040600-generic

Enabled extensions:
- KeePassHTTP
- Auto-Type

**Comment by frostasm** [comment]
I will try to correct  the wrong behavior prior to release 2.3.0 :)
