### ISSUE TITLE
Ctl-U stopped working for newbie [Solved]

### ISSUE THREAD

**Issue by richb-hanover** [keepassxreboot/keepassxc#1214]
Using KeePassXC 2.2.2 on Win10. Just installed today, and I'm new to the program, so I may be doing something wrong. Here's what I remember:

I also installed KeePassHTTP on my Chrome browser, and did the Connect... stunt to make them talk.

I then double-clicked a URL in the window, and MS Edge opened to that URL. I went to Chrome, changed it to be the default browser, and now double-clicking URLs, or using Ctl-U elicits no response.

## Expected Behavior

I expected a double-click on a URL to open the default browser (now Chrome) and allow me to Ctl-Shift-U to type user/pass. (This works fine for me on macOS...)

## Current Behavior

Double-clicking URL or Ctl-U doesn't appear to do anything.

## Steps to Reproduce (for bugs)

1. See above
2.
3.
4.

## Debug Info

KeePassXC - VERSION
Revision: REVISION

Libraries:
- LIBS

Operating system: OS
CPU architecture: ARCH
Kernel: KERNEL

Enabled extensions:
- EXTENSIONS

**Comment by droidmonkey** [comment]
In windows 10 you need to set the default browser in the control panel settings, did you do that?

**Comment by richb-hanover** [comment]
Yes, I had set Chrome to be the default browser in the Default Apps section of Settings (on Win10). Here's additional info: 

1. This failure mode seems to be specific to Chrome: Ctl+U (or choosing Open URL by right-clicking on an entry) works if the default browser is set to either Firefox or Edge - the designated browser opens to the expected page. Changing back to Chrome gives no reaction. 

2. This works fine (changing default browser) on another new computer that came with Win10 installed. The new computer is a 64-bit processor, with 64-bit KeePassXC; the one that doesn't work is a 32-bit machine (& 32-bit KeePassXC) that had been upgraded from Win7. (Don't know if this is a red herring...)

What other info could I provide? Thanks.

**Comment by droidmonkey** [comment]
Its likely your chrome installation on the 32 bit machine, it might not have the hooks properly registered. Try reinstalling chrome.

**Comment by richb-hanover** [comment]
Bingo! Re-installing Chrome seems to have solved it. Thanks!
