### ISSUE TITLE
Add setting to start on login

### ISSUE THREAD

**Issue by droidmonkey** [keepassxreboot/keepassxc#1218]
## Expected Behavior

There is a setting that easily adds KeePassXC to the startup application list. Also add this to the Windows installer.

## Current Behavior

There is no such setting, you must manually add it to auto start on login.

## Context

On Windows, this can be accomplished by adding KeePassXC to the startup registry or programs folder.

On Linux, this can be accomplished by adding a basic launcher to ```~/.config/autostart```

On MacOs, this can be accomplished by following [this guide](https://developer.apple.com/library/content/documentation/MacOSX/Conceptual/BPSystemStartup/Chapters/CreatingLaunchdJobs.html#//apple_ref/doc/uid/10000172i-SW7-BCIEDDBJ).

**Comment by yan12125** [comment]
```hasLaunchOnStartup_private``` and ```setLaunchOnStartup_private``` functions from utility_{mac,unix,win}.cpp in https://github.com/owncloud/client/tree/master/src/common look like good references.
(owncloud is also a Qt5 application; aforementioned codes are licensed under LGPL 2.1+)

**Comment by mat-m** [comment]
I installed the Flathub package on Linux Mint 19, and I have the autostart. I want to disable it and I don't know how (no file in `~/.config/autostart`) !?

**Comment by droidmonkey** [comment]
We do not maintain the flathub package, please see the author of that.

**Comment by droidmonkey** [comment]
Oh, this is an entirely different issue. The browser extension uses native messaging to communicate with KeePassXC. If an instance of KeePassXC is not running when the extension loads than it will start one. I do agree that it shouldn't start unless you interact with the plugin though. Again, different issue.
