### ISSUE TITLE
CLI can't be automated easily?

### ISSUE THREAD

**Issue by jD91mZM2** [keepassxreboot/keepassxc#1221]
When using the CLI, it prints unecessary info like `Insert password to lock ...`.  
Sure, that's very nice of you. But then again, automated scripts have to somehow filter out that output.  
How about you either remove it, or print it to STDERR (so you can pipe that to /dev/null)?

**Comment by RealOrangeOne** [comment]
An alternative which would keep the useful messages would be to add a `--quiet` flag for scripting use which suppresses these kinds of outputs

**Comment by louib** [comment]
@jD91mZM2 we already have issue https://github.com/keepassxreboot/keepassxc/issues/831 to track this. I will be closing this one.
