### ISSUE TITLE
Generate Usernames & Memorizeable Passwords

### ISSUE THREAD

**Issue by knaggit** [keepassxreboot/keepassxc#1222]
Hi everyone,
I am an network engineer and using KeepassXC everyday. One of my "administration tasks" is to create users for our company issues credentials. Therefore it would be great having an option to generate usernames like "puuk3928" to ensure you are not able to trace back which person it is in the system or from external. Above that it would be also nice having related to the generated usernames an option generate passwords which are memorizable like the password generator does in the macOS keychain. 

## Expected Behavior
When I create an entry in a database, I can randomize a username (for security reasons) like I do with passwords.
When I generate a password, there is an option for having a memorizable password like "card$fifteen34"

**Comment by droidmonkey** [comment]
You could use the passphrase generator and just pull a couple random words from the phrase

**Comment by phoerious** [comment]
I suppose those usernames should meet a few constraints, such as: start with four characters, end with four numbers, don't use two consonants in a row. So using a word list doesn't help much.

**Comment by louib** [comment]
@knaggit maybe you could use the CLI to automate that? I'm not sure if we support the passphrase generator when adding entries, but it wouldn't be that hard to add. Otherwise you can also generate the usernames and passwords yourself and use `keepassxc-cli` to "commit" the changes to the database.
