### ISSUE TITLE
Add column for entries: last modify date / creation date

### ISSUE THREAD

**Issue by szyb** [keepassxreboot/keepassxc#1233]
Would you please consider (if possible) to add last modify date / creation date to all grids? I would like to know when the password have been changed or created.
This would be very useful to make sure that password database is synchronized well. I'm using personal cloud to store the database and sometimes I have conflicts. To solve them it would be very useful to have those dates to identify latest entries in database.

edit: it would be also useful to have a grid with all entries (regardless origin folder of the entry)

**Comment by droidmonkey** [comment]
This is covered under #849.
