### ISSUE TITLE
Database already opened

### ISSUE THREAD

**Issue by esat7** [keepassxreboot/keepassxc#1240]
When I try to access my KeePassXC database from another machine, I get a message saying the Database is already opened. What should I do? I know this is a super simple question, but I didn't want to mess anything up. Should I hit Yes since I know I'm not editing it on another machine?

**Comment by droidmonkey** [comment]
This is because of the lock file. It is relatively safe to click "ignore and open anyway" as long as you don't simultaneously edit the database.

**Comment by esat7** [comment]
Thanks for the confirmation!

**Comment by Matvei27** [comment]
I get this when opening on the same machine. I noticed there is no lockfile in the directory with my database. How do I make one so that this stops appearing?

**Comment by phoerious** [comment]
It's probably because KeePassXC failed to create one. The lock file has been removed for 2.3.0. See #1231

**Comment by Matvei27** [comment]
Then why am I still getting this notification? How can I turn it off?

**Comment by phoerious** [comment]
2.3.0 hasn't been released yet.
