### ISSUE TITLE
Add a shortcut to minimize to tray

### ISSUE THREAD

**Issue by mhham** [keepassxreboot/keepassxc#1241]
The global shortcut issue to open keepassxc from tray (#99) was solved thanks to the single instance (#510). Hence calling keepassxc from the command line, which can be configured as a global shortcut, opens the gui from tray.

However, we still lack the ability to minimize the Gui to tray using a shortcut (that does not need to be global, since the gui is opened).

## Expected Behavior
Basically, adding a shortcut to minimize to tray.

## Current Behavior
There is no shortcut to minimize to tray. A workaround is to set keepassxc not to quit when the window is closed, and use the WM shortcut to close the window.

## Debug Info
KeePassXC - Version 2.2.2
Revision: 6d46717

Libraries:
- Qt 5.9.2
- libgcrypt 1.8.1

Operating system: Manjaro Linux
CPU architecture: x86_64
Kernel: linux 4.14.2-1-MANJARO

Enabled extensions:
- KeePassHTTP
- Auto-Type
- YubiKey

**Comment by droidmonkey** [comment]
This is already available as CTRL+M

**Comment by droidmonkey** [comment]
Better placed in documentation, which we need to work on.

**Comment by adamency** [comment]
@droidmonkey The keyboard shortcut for what is specifically asked in the title, i.e. minimizing **to Tray** is `Ctrl+Shift+M` (called "*Hide Window*" in Keepassxc Docs).

Not `Ctrl+M` which minimizes the window to the taskbar, which is not the same thing.

**Comment by droidmonkey** [comment]
Dude this is 5 years old.
