### ISSUE TITLE
allow KeePassHTTP connection on all opened databases (tabs)

### ISSUE THREAD

**Issue by monkeydri** [keepassxreboot/keepassxc#1244]
I use 2 different chrome profiles (each has its own chromeipass extension) that correspond to 2 different keepass databases.

Each extension is connected to one database.
I have both databases opened in one single KeepassXC instance.
This works well, each chrome profile connects only to the correct database and has no access to the other.

**But this works only as long as the database is the currently selected tab. Once I select the other tab the chrome profile loses access to the database via KeepassHTTPplugin**

*Note : I also tried to run 2 instances of KeepassXC, each with a single database opened and each running its own KeePassHTTP server (on 2 different ports), however this felt hacky (and quite annoying for example if I change a setting I have to change it on both instances) and did not work well, sometimes one of the chrome profile could not connect to KeePassHTTP anymore.*

KeepassXC 2.2.2
Ubuntu 17.10
Chrome 62.0.3202.94
Chromeipass 2.8.1 or fork KeePassHttp-Connector 1.0.8

**Comment by droidmonkey** [comment]
This doesn't seem like the correct option. You should be pointing both chrome browsers to the same keepassxc instance and the entry finder should go through each open database to find a potential match.

**Comment by monkeydri** [comment]
Hi @droidmonkey, I also tried using the single instance option but the problem is then that only the database in the current tab is allowed access via KeepassHTTPplugin.

I updated the issue because I could not delete this one.

**Comment by droidmonkey** [comment]
Ok yes that is a bug then

**Comment by PF93mc8y7erq92qTmTjJBysALa** [comment]
KeePassHTTP was removed. As of 2.4.0 it is no longer part of KeePassXC. See #1752.
