### ISSUE TITLE
Verifying Windows Package

### ISSUE THREAD

**Issue by jasubhai** [keepassxreboot/keepassxc#1246]
I am a newbie. Please could I request a bit more detailed guide on how to verify the downloaded package in windows. The cmds on the 'Verify Signature' page seem to be for Linux - I could be wrong. 

Thanks,

**Comment by droidmonkey** [comment]
The installer is verified with authenticode signature. You'll see a signed by DroidMonkey Apps, LLC when you go to install and a blue background in the dialog box.

**Comment by TheZ3ro** [comment]
Alternatively you can use Gpg4Win and Kleopatra to check the gpg signature

**Comment by jasubhai** [comment]
Thanks.
 

Sent: Friday, December 01, 2017 at 12:56 AM

**Comment by jasubhai** [comment]
Thanks.
 

Sent: Thursday, November 30, 2017 at 8:13 PM
