### ISSUE TITLE
SSH Agent shows error on any entry with attachments

### ISSUE THREAD

**Issue by weslly** [keepassxreboot/keepassxc#1247]
![image](https://user-images.githubusercontent.com/107672/33463187-2eb1d1b6-d623-11e7-83e8-5390b94d282a.png)

## Expected Behavior
SSH Agent should show the "Invalid key file" error only when trying to set an invalid private key.

## Current Behavior
SSH Agent complains when opening any entry with attachments that aren't a valid SSH key file, even if they weren't set at the private key setting.

**Comment by weslly** [comment]
@hifi Can I assign this to you?

**Comment by hifi** [comment]
@weslly Yes, please. I'd be interested to know if PR #1224 fixes this.

**Comment by weslly** [comment]
@hifi Seems like github only would let me assign the issue if you had opened it :(

>I'd be interested to know if PR #1224 fixes this.

I just tested and it does. We can close this when #1224 gets merged.

**Comment by hifi** [comment]
@weslly ping, #1224 was merged so this can be closed.
