### ISSUE TITLE
share/icons/application/16x16/actions/message-close.png is 22x22, not 16x16

### ISSUE THREAD

**Issue by julian-klode** [keepassxreboot/keepassxc#1251]
## Expected Behavior
share/icons/application/16x16/actions/message-close.png should be 16x16

## Current Behavior
share/icons/application/16x16/actions/message-close.png is 22x22

## Context
Causes warnings in Debian's lintian tool: https://lintian.debian.org/maintainer/jak@debian.org.html#keepassxc

**Comment by droidmonkey** [comment]
merged into develop
