### ISSUE TITLE
Downloaded favicons are wrong

### ISSUE THREAD

**Issue by RicardoCapricciosa** [keepassxreboot/keepassxc#1255]
Whenever I click on "download favicon" A favicon is downloaded, but displayed is a favicon which is already in the library, also the new favicon is not assigned to the entry. I'm not 100% sure but it seems that this behavior starts after a certain amout of custom icons is present in the database.

## Expected Behavior
The actual downloaded favicon should be displayed and not some which is already present

## Current Behavior
For example there are Icons 1, 2, ..., 50 already present in the database. Now for the 51th entry when I click download favicon there will be a 51th icon, but it's the same as Icon 25. For the 52th icon, the icon 26 is shown and so on.

## Steps to Reproduce (for bugs)
I will try to reproduce it, but it takes time to first create a lot of entries with custom icons in the db

## Context
![screen shot 2017-12-06 at 14 45 52](https://user-images.githubusercontent.com/11453387/33664725-ed12a62e-da94-11e7-9bf6-3f4a7b49fd24.png)

## Debug Info

KeePassXC - 2.2.2
Revision: REVISION

Libraries:
- LIBS

Operating system: MacOS 10.13.1
CPU architecture: x64
Kernel: ?

Enabled extensions:
- EXTENSIONS

**Comment by jmriego** [comment]
I have exactly the same issue. I'm also using the OSX version of KeePassXC. Both 2.2.2 and the latest version have this issue. This also makes impossible to download favicons for some reason

**Comment by phoerious** [comment]
Please test again with 2.3 if the problem persists.

**Comment by RicardoCapricciosa** [comment]
Yes, the problem persists with version 2.3.

**Comment by AJJLagerweij** [comment]
A similar problem here :-(, 
I tried downloading the favicon for a couple of websites (for example from https://accounts.google.com and https://fahrkarten.bahn.de) and ended up with the wrong favicon every time. The symbol I ended up with had nothing to do with the website that I wanted.
I use keepassxc version 2.3.1

**Comment by phoerious** [comment]
Please upgrade to 2.3.3.

**Comment by AJJLagerweij** [comment]
I am aware that that exist, I however use Ubuntu 18.04 and the package is still in 2.3.1 version.
I can get the 2.3.3 over snap, that however does not allow the use of the browser plug-in.
Therefore I'm stuck on version 2.3.1, is there any work around?

**Comment by RicardoCapricciosa** [comment]
Problem persists in 2.3.3 on Mac OS X, a favicon is downloaded but then another favicon is displayed, one which already is in the list of custom favicons

**Comment by phoerious** [comment]
You can use our PPA, which provides 2.3.3.

**Comment by AJJLagerweij** [comment]
Thanks I have done so, however the same problem remains. When I call upon the favicons I does load an icon. The icon however is not related to the website I want. It seems to only load icons that it already has or one from an other website that is in my database as well.

**Comment by droidmonkey** [comment]
I could not replicate this issue even after loading over 100 icons.

**Comment by RicardoCapricciosa** [comment]
I think it only happens with downloaded favicons. Not just manually added icons. I still have this problem. Maybe it's Mac OS X only?

What kind of icons did you use in trying to reproduce?

**Comment by droidmonkey** [comment]
The same function is called to add the icon to the database and display no matter how you add them. Sometimes websites return an icon that is slightly different than the one in the database so the duplication check fails and it adds what appears to be a new icon.
