### ISSUE TITLE
Failed to open connection to "session" message bus:

### ISSUE THREAD

**Issue by NYCJacob** [keepassxreboot/keepassxc#1262]
When entering ctrl-u on a url in keepassxc nothing happens in the browser and my terminal where keepass is running shows the following message each time I hit ctrl-u
Failed to open connection to "session" message bus: /usr/bin/dbus-launch terminated abnormally without any error message

## Expected Behavior

The url should open in my default browser

## Current Behavior

In the terminal the following message is displayed:
Failed to open connection to "session" message bus: /usr/bin/dbus-launch terminated abnormally without any error message

## Steps to Reproduce (for bugs)

1.  Ubuntu 16.06
2.  snapd-xdg-open was installed
3.  
4.

## Context

This basically prevents me from using the program :(
## Debug Info

KeePassXC - Version 2.2.2
Revision: 6d46717
Distribution: Snap

Libraries:
- Qt 5.7.1
- libgcrypt 1.7.6-beta

Operating system: Ubuntu Core 16
CPU architecture: x86_64
Kernel: linux 4.13.0-041300rc4-generic

Enabled extensions:
- KeePassHTTP
- Auto-Type
- YubiKey

**Comment by droidmonkey** [comment]
Does the non-snap version work for you?

**Comment by NYCJacob** [comment]
Just tried the .app image and it does work, actually.

**Comment by NYCJacob** [comment]
maybe this should be a new issue, but still can't get keepass to work :(
have firefox-dev as default, launching from keepass entry opens new firefox session with an empty tab- not the url from keepass.  I think this is a FF issue because the same thing happens when  I click a lick in a text document.     I then set Chrome as defaul and it crashes Chrome each time.

**Comment by droidmonkey** [comment]
Looks like snapd silently integrated the xdg-open command..... I have removed it from the snap in release 30, please test again. Worked for me in ubuntu 17.04 without the snapd-xdg-open package installed.

**Comment by phoerious** [comment]
Can you remove the FAQ entry then?

**Comment by phoerious** [comment]
NVM, you did that already.
