### ISSUE TITLE
No option for favicon download

### ISSUE THREAD

**Issue by whitebyte** [keepassxreboot/keepassxc#1263]
Suddenly after the update I no longer see an option for download favicon from URL. This button is replaced with "Add custom icon" one, which prompt for local image.

## Debug Info
KeePassXC - Version 2.2.2
Revision: 6d46717

Libraries:
- Qt 5.7.1
- libgcrypt 1.8.1

Operating system: Calculate/Linux (Gentoo derivative)
CPU architecture: x86_64
Kernel: linux 4.9.65-calculate

Enabled extensions:
- Auto-Type

**Comment by TheZ3ro** [comment]
How do you installed keepassxc?
Seems that the XC_HTTP plugin is disabled

**Comment by whitebyte** [comment]
> How did you installed keepassxc?

From Gentoo repo using portage.

> Seems that the XC_HTTP plugin is disabled

Seems so, but I don't clearly understand the purpose of it. What should it do with favicons?

**Comment by TheZ3ro** [comment]
Every network operation in keepassxc needs XC_HTTP, seems that the Gentoo repo maintainer decided to compile keepassxc without network support

**Comment by phoerious** [comment]
Needs to be fixed by package maintainer.

**Comment by whitebyte** [comment]
Indeed, after recompiling with `http` user flag enabled it woks as expected, thank you for clarification. BTW I don't see any documentation on http plugin and on KeePassXC's plugins in general, does it exists?

**Comment by phoerious** [comment]
It's documented in the README.

**Comment by whitebyte** [comment]
Unfortunately I don't see anything related in the readme, and there is only short mention in the wiki, in the `build` section. It says that by default only `autotype` plugin is enabled, so it seems that Gentoo build just respects defaults. Should absense of `http`  be reported downstream or is it expected behavior?

**Comment by TheZ3ro** [comment]
By default means when you (manually) compile it.
Every distributor then chose for itself, our official builds have `http` included
