### ISSUE TITLE
Three Authentication Fields

### ISSUE THREAD

**Issue by esat7** [keepassxreboot/keepassxc#1265]
I need to add entries for three authentication fields, not just the password and username fields. Is this possible? I haven't figured out how to add a new field in the interface.

**Comment by phoerious** [comment]
I don't quite understand what you are trying to do. Can you explain more, please?

**Comment by esat7** [comment]
I have three fields I need to auto-fill to access an account and need to add one before the Username or Password so it gets auto-filled. I’m wanting to know if this is possible. The field order is: ID, Username, Password.

**Comment by TheZ3ro** [comment]
@esat7 in the entry page, on the left, select the Advanced add there the ID, then follow this for the autotype https://github.com/keepassxreboot/keepassxc/wiki/Autotype-Custom-Sequence

**Comment by esat7** [comment]
So, the result should look like this?

![attribute](https://user-images.githubusercontent.com/26190797/33786190-1bffd5a4-dc36-11e7-946c-943e8313344b.jpg)
![typesequence](https://user-images.githubusercontent.com/26190797/33786197-20460d54-dc36-11e7-9ec9-e7ede449df17.jpg)

The reason I ask is this does not work for me currently.

**Comment by droidmonkey** [comment]
Custom Attributes

If you define Custom Attributes in your Entry, the Autotype will be able to access them with the Attribute name as an Action preceded by S: (case Sensitive).

For example: I define a new custom attribute named PIN with value 12345. Now I can Autotype it with the action {S:PIN}.

NOTE: Custom Attribute name are CaseSensitive
