### ISSUE TITLE
There is no support to enter unicode characters in keepassxc (linux)

### ISSUE THREAD

**Issue by nemoinis** [keepassxreboot/keepassxc#1266]
## Expected Behavior
I am used to entering unicode characters using ctrl-shift-u followed by the character's unicode index. For example ctrl-shift-u-25cf produces ● a black circle (yes, you could have a password made entirely of black bullets... if you have 10 minutes to type it in!)
See [https://en.wikipedia.org/wiki/Unicode_input#In_X11_(Linux_and_Unix_variants)](https://en.wikipedia.org/wiki/Unicode_input#In_X11_(Linux_and_Unix_variants)) for more details on that.

## Current Behavior
This does not work in keepassxc, probably because of this Qt bug:
[https://bugreports.qt.io/browse/QTBUG-8](https://bugreports.qt.io/browse/QTBUG-8), which does not look like it will get fixed anytime soon.

For a password manager, being cut off from the vast majority of available characters is not cool.

## Possible Solution
I don't have a suggested solution. A workaround is to use any GTK app, type the input there then cut/paste/middle-click it back into keepassxc while muttering...

A second workaround, which only works for A SMALL SUBSET of characters, is to use your system's compose key (e.g., use composekey+shift+" then u to get ü ).

The proper solution is to add unicode input support to keepassxc.

## Steps to Reproduce (for bugs)

in any field of a keepassxc entry, hold ctrl-shift, type u2666 then let go of ctrl-shift. You should get a ♦ black diamond. But you get nothing...

**Comment by TheZ3ro** [comment]
We can't really do much about it if Qt doesn't support.

Use `charmap` to get the character you want and copy-paste it in keepassxc
