### ISSUE TITLE
Keepassxc whit amdgpu-pro 17.40 libdrm_amdgpu.so crash

### ISSUE THREAD

**Issue by kolszak** [keepassxreboot/keepassxc#1268]
When install amdgpu-pro 17.40, keepassxc crash at start.
## Expected Behavior
Keepassxc should run on AMD linux driver installed. 

## Current Behavior
Run keepassxc on terminal tell:
screen 0 does not appear to be DRI2 capable
screen 0 does not appear to be DRI2 capable
dmesg:
[94969.485359] keepassxc[27110]: segfault at 18 ip 00007f1f71bf99ad sp 00007ffc29354820 error 4 in libdrm_amdgpu.so.1.0.0[7f1f71bf2000+d000]

## Steps to Reproduce (for bugs)

1. Install ubuntu 16.04 
2. Install amdgpu-pro on supported platrofm (me Dell Precision M3510, W5130 ATI card)
3. Run keepassxc 
4.

## Debug Info

KeePassXC - 2.2.2 from repo to ubuntu 16.04
Revision:  2.2.2-1~xenial1
(kepassxc not started, even keepassxc -v or -h)
md5sum of binary /usr/bin/keepasxc cb0aabd1c9ba89676d6c0c7d4247f961

Libraries:
- amdgpu-pro driver 17.40 - 492261

Operating system: Ubuntu 16.04.3 
CPU architecture: amd64
Kernel:  4.13.0-16-generic #19~16.04.3-Ubuntu

**Comment by TheZ3ro** [comment]
Seems a Qt problem to me
