### ISSUE TITLE
Cloned entries: Refs should be lower case. Breaks autotype/keepasshttp

### ISSUE THREAD

**Issue by pkill-9** [keepassxreboot/keepassxc#1269]
When I clone an entry, the UUID is in upper case, eg "{REF:U@I:8B45B432F16158A7B7730530E704B0F5}"

The username ref doesn't link for both autotype and KeePassHTTP.

However, If I manually copy/paste the (lower case) UUID from the original entry, the refs work.

## Expected Behavior
In cloned entries, the UUID should be lower case

## Current Behavior
In cloned entries the UUID is upper case

## Steps to Reproduce (for bugs)
1. Create an entry
2. Clone it
3. Autotype and KeePassHTTP don't work with the cloned entry

## Debug Info

KeePassXC - Version 2.2.2
Revision: 1bc2d58

Libraries:
- Qt 5.7.1
- libgcrypt 1.7.6-beta

Operating system: Ubuntu 17.04
CPU architecture: x86_64
Kernel: linux 4.10.0-42-generic

Enabled extensions:
- KeePassHTTP
- Auto-Type

**Comment by pkill-9** [comment]
Another way of looking at this is that refs shouldn't be case sensitive, perhaps.

Making refs case insensitive would mean that existing cloned entries would stop being broken. For that reason I think this would be the best solution

**Comment by cyphar** [comment]
I believe that #1280 includes a fix for this, and it works by making UUID matching case-insensitive (like it was in previous releases).
