### ISSUE TITLE
Version 2.2.3 is a Pre-release ?

### ISSUE THREAD

**Issue by kyrios123** [keepassxreboot/keepassxc#1270]
I see version 2.2.3 is tagged but labelled as Pre-release.
Before Pre-releases versions were suffixed with `-alpha` or `-beta`, so this is a little confusing and I would like to know if this will be followed by a "stable" release or if it was mistakenly labelled as Pre-release ?

**Comment by TheZ3ro** [comment]
Fixed, it was done by mistake

**Comment by kyrios123** [comment]
There is now a 2.2.4 with the same changelog as 2.2.3 and both are set to Pre-release ???
It's pretty obvious that 2.2.4 replaces 2.2.3 and that it should be flagged as release, so I don't open another issue but still I drop a line here to let you know @TheZ3ro @phoerious 

Thanks for maintaining this very useful application ! 😃

**Comment by phoerious** [comment]
2.2.4 will be marked as a normal release once I publish the announcement. I was only waiting for the Windows builds.

**Comment by phoerious** [comment]
Done. Release is out.

**Comment by kyrios123** [comment]
thanks 👍
