### ISSUE TITLE
Debian Stretch and missing text on snap version

### ISSUE THREAD

**Issue by ilmaisin** [keepassxreboot/keepassxc#1271]
## Expected Behavior

I should see the text in the menus.

## Current Behavior

The text is missing. Also, when I browse menus, the following line gets repeatedly printed to the console:

`QFont::setPointSizeF: Point size <= 0 (-0.750000), must be greater than 0`

## Steps to Reproduce (for bugs)

1. Install snapd on Debian Stretch
2. Install KeePassXC
3. Run KeePassXC

## Context

On Ubuntu 16.04, everything seems to work fine. Also, the AppImage works correctly on Debian as well.

## Debug Info

Unable to get this data because text is missing.

When installing the snap, it outputs: `keepassxc 2.2.3 from 'keepassxreboot' installed`

Operating system: Debian Stretch
CPU architecture: amd64
Kernel: `Linux debian9-vm 4.9.0-3-amd64 #1 SMP Debian 4.9.30-2+deb9u5 (2017-09-19) x86_64 GNU/Linux`

Enabled extensions:

**Comment by droidmonkey** [comment]
What version of snapd are you using on Debian

**Comment by ilmaisin** [comment]
It's 2.29.4.2, the one that came with Debian Stretch

**Comment by steckerhalter** [comment]
Experiencing this as well on Debian Stretch.

**Comment by alexkay** [comment]
Seeing this as well. Stock Debian 9, snapd v2.21. Not only the menu is missing, all text labels are textless, including file/dir names in the open file dialog and all buttons. Also seeing this when running from shell:

```
Qt: Session management error: None of the authentication protocols specified are supported
```

**Comment by BruOp** [comment]
I'm seeing the same thing with Fedora 26, GNOME 3.24.2, snap v2.30-1.fc26. 
```
Qt: Session management error: None of the authentication protocols specified are supported
QFont::setPointSizeF: Point size <= 0 (-0.750000), must be greater than 0
```

**Comment by mttkrb** [comment]
Same problem on Fedora 27 with kepassxc 2.3.0.
`Qt: Session management error: None of the authentication protocols specified are supported
QFont::setPointSizeF: Point size <= 0 (-0.750000), must be greater than 0`

`$ snap --version
snap    2.30-1.fc27
snapd   2.30-1.fc27
series  16
fedora  27
kernel  4.15.4-300.fc27.x86_64`

**Comment by droidmonkey** [comment]
Ugh can't it show where that point size call is being made

**Comment by mttkrb** [comment]
The point size call is beeing made when the mouse is over a button without text.

**Comment by mttkrb** [comment]
Maybe is it the same problem like this?
https://forums.virtualbox.org/viewtopic.php?f=7&t=80414

**Comment by droidmonkey** [comment]
Link is broken :persevere:

**Comment by vmeurisse** [comment]
After debugging a bit, I managed to fix it locally. The issues is caused by missing links in the home dir.

Version 2.3.0 with the bug:
```console
$ ls -lA ~/snap/keepassxc/33/.local/share
total 4.0K
drwxr-xr-x 1 user user  14 2018-03-03 14:48 glib-2.0/
drwxr-xr-x 1 user user 192 2018-03-03 14:49 icons/
drwxr-xr-x 1 user user 348 2018-03-03 14:48 mime/
lrwxrwxrwx 1 user user  35 2018-03-03 14:48 themes -> /snap/keepassxc/33/usr/share/themes/
```
Version 2.2.4 without the bug:
```console
$ ls -lA ~/snap/keepassxc/26/.local/share
total 16K
lrwxrwxrwx 1 user user  39 2018-03-03 14:58 fontconfig -> /snap/keepassxc/26/usr/share/fontconfig
lrwxrwxrwx 1 user user  34 2018-03-03 14:58 fonts -> /snap/keepassxc/26/usr/share/fonts/
lrwxrwxrwx 1 user user  36 2018-03-03 14:58 fonts-* -> /snap/keepassxc/26/usr/share/fonts-*
drwxr-xr-x 1 user user  14 2018-03-03 14:59 glib-2.0/
drwxr-xr-x 1 user user 220 2018-03-03 14:59 icons/
drwxr-xr-x 1 user user 348 2018-03-03 14:59 mime/
lrwxrwxrwx 1 user user  35 2018-03-03 14:58 themes -> /snap/keepassxc/26/usr/share/themes/
```

After recreating the missing links, the fonts show up correctly
```console
$ ln -s /snap/keepassxc/33/usr/share/fontconfig ~/snap/keepassxc/33/.local/share/fontconfig && ln -s '/snap/keepassxc/33/usr/share/fonts-*' ~/snap/keepassxc/33/.local/share/'fonts-*' && ln -s /snap/keepassxc/33/usr/share/fonts ~/snap/keepassxc/33/.local/share/fonts
```

**Comment by mttkrb** [comment]
Perfect.  After adding the missing links it works.

**Comment by droidmonkey** [comment]
I spent a couple hours looking into this and can reproduce on Debian Stretch. I tried removing some of the extra packages we include in our Qt5 desktop support library for snaps to no avail. I believe this is something wrong with the desktop-launch script that builds the directories in the .local/share folder. For whatever reason, our snap is not completing this build out correctly on Debian.

**Comment by mikefedyk** [comment]
I can reproduce the problem on Fedora 27 Plasma as well.

**Comment by mttkrb** [comment]
With the actual Fedora Updates I have to create following links:
`ln -s /snap/keepassxc/37/usr/share/fontconfig ~/snap/keepassxc/37/.local/share/fontconfig && ln -s '/snap/keepassxc/37/usr/share/fonts-*' ~/snap/keepassxc/37/.local/share/'fonts-*' && ln -s /snap/keepassxc/37/usr/share/fonts ~/snap/keepassxc/37/.local/share/fonts`

**Comment by aspyct** [comment]
I'm also having (and solve) this issue on Debian Stretch, but it seems it is yet again slightly different. I didn't have the `fontconfig` file/folder nor the `fonts-*".

After linking the fonts, everything seems fine.
```ln -s /snap/keepassxc/current/usr/share/fonts ~/snap/keepassxc/current/.local/share/fonts```
(where `current` is 37)

**Comment by roben** [comment]
`ln -s /snap/keepassxc/current/usr/share/fonts ~/snap/keepassxc/current/.local/share/fonts`
worked for me, too. Thanks!  (Debian stretch)

**Comment by droidmonkey** [comment]
Please see if this still persists with the latest snap build posted.

**Comment by ilmaisin** [comment]
Now the text seems to be fine.
