### ISSUE TITLE
Useless (huge) notification when importing passwords/saving database

### ISSUE THREAD

**Issue by rugk** [keepassxreboot/keepassxc#1275]
When importing passwords GNOME from a CSV shows me a huge notification for one second or so.

## Expected Behavior

Do not show it.

## Current Behavior

It shows a really big notification (likely the passed icon is a big too big…, respectively the size not limited). It disappears too fast to make a screenshot of it, unfortunately.

## Possible Solution

Just remove it. IMHO it is useless anyway, because you have a main window where you can show all status information, if necessary. (And as far as I see, it is not necessary, as hundreds of passwords were imported in less than one second here.)
So there is no reason to display a system notification, especially not if the process takes less than a second.

## Steps to Reproduce (for bugs)

1. Import CSV with hundreds of passwords.

## Debug Info

KeePassXC - Version 2.2.2
Revision: 6d46717

Bibliotheken:
- Qt 5.9.2
- libgcrypt 1.8.1

Betriebssystem: Fedora 27 (Workstation Edition)
CPU-Architektur: x86_64
Kernel: linux 4.14.3-300.fc27.x86_64

Aktivierte Erweiterungen:
- KeePassHTTP
- Auto-Type
- YubiKey

GNOME: 3.26

**Comment by rugk** [comment]
Same when the database is saved.

**Comment by droidmonkey** [comment]
Are you referring to the notice banner that shows just below the toolbar icons?

**Comment by rugk** [comment]
No it's a system notification. It's also shown less than a second when KeePassHTTP request gets in and you have this setting "to show a notification when requests get in" is enabled.

**Comment by droidmonkey** [comment]
We don't have any notifications that don't make you hit OK or similar to dismiss. There would never be a case where a popup notification would occur that is self dismissing after one second.

**Comment by rugk** [comment]
Ah, I think I found the issue. It is basically GNOME's "KeePassXC is ready", which notifies you when a new window opens, but is still in the background, so you can open it.

So okay, you may not be able to fix that. (unless you have an idea?) But you could still tackle the issue of a too big icon. I think it uses the 256x256px for that. Don't you have smaller icons (or SVGs?) included?

**Comment by droidmonkey** [comment]
We have all sizes of icons, this seems like a gnome issue... They need to restrict the icon size.

**Comment by rugk** [comment]
I've never seen that for any other application. I ask the Fedora package maintainer, maybe they can spot the issue here.

https://bugzilla.redhat.com/show_bug.cgi?id=1525697

**Comment by seatedscribe** [comment]
Maybe you can upload a short video with the issue catched?

**Comment by rugk** [comment]
Well… it's still very fast that thing. I can try though… Remind me if I forget it.

**Comment by rugk** [comment]
I got a screenshot here:
![](https://bugzilla.redhat.com/attachment.cgi?id=1368462)

**Comment by droidmonkey** [comment]
Great thanks, that is definitely not one of our notifications. We'll watch the bug report to see what happens.

**Comment by rugk** [comment]
Fixed by distro update.
