### ISSUE TITLE
Add Quick Unlock Feature

### ISSUE THREAD

**Issue by Jackenmen** [keepassxreboot/keepassxc#1278]
## Expected Behavior
I want Quick Unlock feature, like you can have in Keepass2Android or in plugin for original KeePass - KeePassQuickUnlock.

## Context
I'm tired of having to type full password after some time of inactivity, but I don't want to disable it completely. I really like Quick Unlock feature on my phone,

**Comment by TheZ3ro** [comment]
Duplicate of #488
