### ISSUE TITLE
Slow down auto-type

### ISSUE THREAD

**Issue by citral** [keepassxreboot/keepassxc#128]
Auto-type can enter characters too fast, leading to failed auto-types.

## Expected Behavior
The option to configure the auto-type speed.

## Current Behavior
Auto-type goes too fast leading to broken input. See also this bug report: https://dev.keepassx.org/issues/152.

## Possible Solution
A solution is described in the bug report (https://dev.keepassx.org/issues/152). It appears that this PR is also aimed at the same problem: https://github.com/keepassx/keepassx/pull/182.

## Your Environment
* Operating System and version: Linux, X11.

**Comment by droidmonkey** [comment]
This has already been implemented on the develop branch and will be part of the v2.1.0 release: https://github.com/keepassxreboot/keepassxc/wiki/Autotype-Custom-Sequence#delayn

**Comment by tvld** [comment]
If I read that post correctly, I should add {DELAY=2} or so for EVERY password entry?

 Should I really need to change **all my 500 entries** to slow down autotype? (Inherit does not work, as many of my entries have a custom entry...). Is there not a simple global DEALAY ?

**Comment by droidmonkey** [comment]
Im not sure what your exact needs are, but there was a minor change for v2.2.0 for linux that adds a 25ms delay between key presses for ALL auto typing.

**Comment by tvld** [comment]
25ms is excellent. 

Myself i figured i needed 20ms,  so 25ms seems almost spot on.

Thank you :)

**Comment by adatum** [comment]
Is the 25ms delay configurable on v2.2.0? I liked the behavior on v2.1.4 especially on long passwords that are, say, 128 characters long (thus 3.2 seconds just to enter the password, in addition to the username).
