### ISSUE TITLE
Snap: Cursor does not respect scaling factor

### ISSUE THREAD

**Issue by M-Pixel** [keepassxreboot/keepassxc#1282]
## Expected Behavior
My 2x scaling factor makes all UI elements including the cursor 2x bigger.

## Current Behavior
My 2x scaling factor makes all UI elements except for the cursor 2x bigger. The cursor is extremely tiny on my screen, very hard to see, when it is over the KeePassXC snap's window (it returns to normal 2x size as soon as it leaves the window)

## Steps to Reproduce (for bugs)
1. Install the snap on OpenSUSE
2. Set UI scale to 2 through KDE settings
3. Open KeePassXC, hover over the window with your cursor

## Context
This is an accessibility issue.

## Debug Info
KeePassXC - Version 2.2.2
Revision: 6d46717
Distribution: Snap

Libraries:
- Qt 5.7.1
- libgcrypt 1.7.6-beta

Operating system: openSUSE Leap 42.3
CPU architecture: x86_64
Kernel: linux 4.4.103-2.g70b1a87-default

Enabled extensions:
- KeePassHTTP
- Auto-Type
- YubiKey

**Comment by phoerious** [comment]
This is probably a Snap issue and not under out control.

**Comment by M-Pixel** [comment]
Ah, you're probably right - I just confirmed that it's the same with Krita.
