### ISSUE TITLE
Feature Request: Show statistics about the database

### ISSUE THREAD

**Issue by bryceml** [keepassxreboot/keepassxc#1283]
I think it would be cool if there was something in a menu you could click to show statistics about the database, like:

Total passwords
Total Unique passwords
Average length of password use between changes
Total / Unique usernames
Average / Min / Max password lengths and complexities
Oldest Password

I think it would be useful.

**Comment by TheZ3ro** [comment]
Duplicate of #551, please use that Issue, I'm closing this one
