### ISSUE TITLE
Power-Button from the computer shotdown the system immediately

### ISSUE THREAD

**Issue by user240** [keepassxreboot/keepassxc#1285]
## Expected Behavior

Show the systems shotdown dialog to choose an action.

## Current Behavior

Shotdown the system immediately!

## Steps to Reproduce (for bugs)

1. Detected for Ubuntu 14.04 *.deb package and AppImage (Ubuntu 16.04 not affected)
2. The setting "Show a system tray icon" is SET
3. The setting "Hide window to system tray instead of app exit" is UNSET
4. Press the Power-Button from the computer

## Debug Info

KeePassXC - Version 2.2.4
Revision: 4723f66

Libraries:
- Qt 5.2.1
- libgcrypt 1.6.1

Enabled extensions:
- KeePassHTTP
- Auto-Type
- YubiKey

**Comment by TheZ3ro** [comment]
I don't think this is caused by KeePassXC :thinking:
