### ISSUE TITLE
Hotkeys not working if the toolbar isn't visible with Ubuntu 14.04 trusty (works with 16.04)

### ISSUE THREAD

**Issue by user240** [keepassxreboot/keepassxc#1286]
## Current Behavior

I installed the latest 

> keepassxc_2.2.4-0ppa1~trusty1_amd64.deb

(and also tested with "keepassxc_2.2.2-1~trusty3_amd64.deb")
from
https://launchpad.net/~phoerious/+archive/ubuntu/keepassxc/+packages

If the toolbar is not visible (Menu "View", "Show toolbar" not checked) all Hotkeys won't work.
The hotkey ctrl+q never works.

## Possible Solution

use AppImage from https://keepassxc.org/download#linux

## Debug Info

KeePassXC - Version 2.2.4
Revision: 4723f66

Bibliotheken:
- Qt 5.2.1
- libgcrypt 1.6.1

Aktivierte Erweiterungen:
- KeePassHTTP
- Auto-Type
- YubiKey

**Comment by droidmonkey** [comment]
This is a Qt "feature" and cannot be changed.
