### ISSUE TITLE
Pushing the Power-Button from the computer closes the window but doesn't quit the program with Ubuntu 14.04 trusty (works with 16.04)

### ISSUE THREAD

**Issue by user240** [keepassxreboot/keepassxc#1287]
## Expected Behavior

KeePassXC should close

## Current Behavior

Pushing the "Power-Button" from the computer closes the programs window but doesn't quit the program/process. KeePassXC must be terminated by system-monitor (taskman) before it could be started again.

## Steps to Reproduce (for bugs)

1. The setting "Show a system tray icon" is UNSET
2. Press the Power-Button from the computer
3. keepassxc process is still running
4. KeePassXC couldn't be started again

## Debug Info
KeePassXC - Version 2.2.4
Revision: 4723f66

Bibliotheken:
- Qt 5.2.1
- libgcrypt 1.6.1

Aktivierte Erweiterungen:
- KeePassHTTP
- Auto-Type
- YubiKey

**Comment by phoerious** [comment]
Is this related to #856?
