### ISSUE TITLE
Trayicon not working with Ubuntu 14.04 trusty (works with 16.04)

### ISSUE THREAD

**Issue by user240** [keepassxreboot/keepassxc#1288]
## Expected Behavior

If the setting "Show a system tray icon" is SET,
the trayicon should be visible next to the clock.

## Current Behavior

Doesn't work / is not showing / is not visible

## Debug Info

KeePassXC - Version 2.2.4
Revision: 4723f66

Bibliotheken:
- Qt 5.2.1
- libgcrypt 1.6.1

Aktivierte Erweiterungen:
- KeePassHTTP
- Auto-Type
- YubiKey

**Comment by phoerious** [comment]
I am pretty sure that is another Unity bug. :-\

**Comment by phoerious** [comment]
You cannot compile KeePassXC with Qt4.
