### ISSUE TITLE
Add sortable last-modified column to entry list view

### ISSUE THREAD

**Issue by TheZ3ro** [keepassxreboot/keepassxc#129]
Add sortable last-modified column to entry list view 
https://github.com/keepassx/keepassx/pull/192

From KeePassX Pull Request

**Comment by droidmonkey** [comment]
This is a nice solution but it doesn't solve the root problem which is not being able to customize the view in any way. This would be a great feature to bring to the app in the future.

**Comment by Thynix** [comment]
Aside from the test failure and a few minor comments that PR looks good to me.

**Comment by TheZ3ro** [comment]
Sub-issue of #17

**Comment by jab416171** [comment]
@Thynix it looks like it's just a matter of updating that one line of that one test. I can take care of that and submit a pull request against this repository with the same diff as keepassx/keepassx#192 if that's all it takes?

**Comment by Thynix** [comment]
@jab416171 I'm hardly in a position of authority here but that sounds good to me.

**Comment by jab416171** [comment]
Oh right, maybe I should be asking @TheZ3ro and @droidmonkey.

**Comment by droidmonkey** [comment]
My thoughts on this were to wait until we redo the whole display of entries. I want it to be more extensible and less hard coded then it currently​ is.

**Comment by fonic** [comment]
Covered by #849

**Comment by droidmonkey** [comment]
Closing in favor of the above issue.
