### ISSUE TITLE
Widen searches to include additional attributes

### ISSUE THREAD

**Issue by JosephHatfield** [keepassxreboot/keepassxc#1290]
## Expected Behavior
When searching for text entered in the Search... field, any text stored as an additional attribute would also be searched for matches.

## Current Behavior
Searches currently do not include matches found in any additional attributes

## Context
Adding this feature would allow users to search for all entries that have been set up to use TOTP by searching for "TOTP". Currently, a note has to manually be added to the entry to accomplish this.

## Debug Info
KeePassXC - Version 2.2.4
Revision: 4723f66

Libraries:
- Qt 5.9.2
- libgcrypt 1.8.1

Operating system: Windows 10 (10.0)
CPU architecture: x86_64
Kernel: winnt 10.0.16299

Enabled extensions:
- KeePassHTTP
- Auto-Type
- YubiKey

**Comment by frostasm** [comment]
I can make the necessary changes.

**Comment by in-in** [comment]
I really miss this feature 😟

I use a lot of additional attributes to organize my data. And I was surprised that I do not have the ability to search in these attributes.

At the same time, the search in the note fields works, but the use of this field is not suitable for data organization
![18060501](https://user-images.githubusercontent.com/8797432/40971684-10aa85aa-68c7-11e8-8c2d-3e3ff53f9996.png)

**Comment by droidmonkey** [comment]
This is already covered under #239 and actually is a duplicate issue. My advanced search PR implements this feature.
