### ISSUE TITLE
Wrong keyboard layout under Wayland

### ISSUE THREAD

**Issue by tribut** [keepassxreboot/keepassxc#1293]
When run under Wayland (Ubuntu 17.10, _GNOME_ session), the keyboard layout seems to be wrong, possibly the default English one. When I type `ö` in the _Enter master key_ prompt, it results in `;`. This does not happen with any other application I use. Without Wayland (_GNOME on X_ session), it works as expected.

I am using the AppImage release of KeepassXC.

This may be related to #1005, but this is not about auto-type, so I opened a new issue.

## Expected Behavior
Always use the configured keyboard layout.

## Current Behavior
Uses the wrong layout when inside Wayland.

## Debug Info
KeePassXC - Version 2.2.4

Libraries:
- Qt 5.9.2
- libgcrypt 1.6.1

Operating system: Ubuntu 17.10
CPU architecture: x86_64
Kernel: linux 4.13.0-19-generic

Enabled extensions:
- KeePassHTTP
- Auto-Type
- YubiKey

**Comment by ArchangeGabriel** [comment]
You’re hit by the (current) lack of support for compose input method (necessary for a lot of non-ASCII chars) in QtWayland. This will be solved with Qt 5.11, in some months.

**Comment by tribut** [comment]
Oh, I see. Thanks for the response.

Just to clarify: I am only pressing a single button. There is no dead keys or compose key involved at all.

**Comment by ArchangeGabriel** [comment]
Oh. Then it might be a different issue. But I wouldn’t be surprised that it would be on Qt side nevertheless.

**Comment by tribut** [comment]
One more thing:

I wasn't sure if I had maybe changed something on my end, but after testing the older AppImage I can now confirm that it does **not** happen with KeepassXC **2.2.2** (Qt 5.6.2). It only started when upgrading to 2.2.4.

**Comment by MisterY** [comment]
I thought this was only related to the AppImage version but, unfortunately, I'm getting the same results when installing the RPM package of 2.4.1 from openSuse. :(
