### ISSUE TITLE
Gmail autofill choosing wrong links/fields

### ISSUE THREAD

**Issue by ghost** [keepassxreboot/keepassxc#1295]
Due to google putting "forgot password" and "more options" links before the "next" button which takes you to the password entry field the autofill puts my username in correctly then selects and opens the next link (forgot password) as it takes two "tabs" to get to the password button stupidly. How can I set it to bypass those two links?

**Comment by droidmonkey** [comment]
Put in {TAB}{TAB}

**Comment by hap124** [comment]
@droidmonkey thanks for that. I didn't see that info on the docs page, but I did obviously miss the wiki link where autotype features are better explained.
