### ISSUE TITLE
Different size of the icons in Ubuntu 16.04

### ISSUE THREAD

**Issue by bullet64** [keepassxreboot/keepassxc#1296]
Look @ my screenshot.
![bildschirmfoto vom 2017-12-16 12-37-28](https://user-images.githubusercontent.com/10364233/34070074-e775d8a4-e25e-11e7-8d96-5ab462039dd7.png)

I am using an 4K-Monitor and use scaling factor 1.75

## Expected Behavior

Same size for all icon's

## Debug Info

KeePassXC - Version 2.2.4
Revision: 4723f66

Bibliotheken:
- Qt 5.5.1
- libgcrypt 1.6.5

Betriebssystem: Ubuntu 16.04.3 LTS
CPU-Architektur: x86_64
Kernel: linux 4.10.0-42-generic

Aktivierte Erweiterungen:
- KeePassHTTP
- Auto-Type
- YubiKey

**Comment by droidmonkey** [comment]
I believe the qt version on Ubuntu 16.04 does not respect scaling appropriately. Then snap is also broken right now due the same reason (built on 16.04).

**Comment by bullet64** [comment]
Correct. In my VirtualBox i run Ubuntu 18.04 to test KeePassXC. KeePassXC is using Qt 5.9.2 and Icon's are all okay.
Thank you. You can close this issue.
