### ISSUE TITLE
The main window dosn't keep the window position on the screen

### ISSUE THREAD

**Issue by user240** [keepassxreboot/keepassxc#1299]
## Expected Behavior

The window should keep the last position where it was visible.

## Current Behavior

The window moves 28px topwards everytime you minimize and restore it. This is annoying because I placed the window on the lower screen edge.

## Possible Solution

You can wirte-protect your keepassxc.ini file (for Linux: ~/.config/keepassxc/keepassxc.ini)

## Steps to Reproduce (for bugs)

1. Place the KeePassXC window to the lower screen edge or elsewhere except the top
2. Minimize and restore the KeePassXC window

## Debug Info

KeePassXC - Version 2.2.4
Revision: 4723f66

Bibliotheken:
- Qt 5.2.1
- libgcrypt 1.6.1

Aktivierte Erweiterungen:
- KeePassHTTP
- Auto-Type
- YubiKey

**Comment by phoerious** [comment]
We don't Position the window. That's more likely a problem of your window manager.

**Comment by user240** [comment]
But KeePassXC saves the window size and position to the keepassxc.ini file and loads it from there when restoring or open the window... As I described above: if you write-protect your keepassxc.ini file, the window keeps it's position!

keepassxc.ini file:
[GUI]
MainWindowGeometry=@ByteArray(....)

This behaviour comes from "keepassx" source code, I used it for many years...

**Comment by TheZ3ro** [comment]
Yup @user240 is right but I think Qt get the wrong position from your DE and when restore it mess up. It's a Qt or DE problem upstream
