### ISSUE TITLE
[Question] How do I create a new group parallel to 'General'?

### ISSUE THREAD

**Issue by Bestulo** [keepassxreboot/keepassxc#1300]
I've been using KeePassXC for a few days and I've been trying all the time to create a new group parallel to General, but I haven't been able to, so I just put all my groups, regardless of category, inside General.

![image](https://user-images.githubusercontent.com/23301025/34088314-f81a421e-e37e-11e7-9d8d-5fcff53c4a52.png)

I thought it would be easier to find this but now I feel like I'm overlooking some button somewhere. Could I get some help with this one?

**Comment by phoerious** [comment]
General is your root group. There can only be one root group.

**Comment by Besatnias** [comment]
What's the point of having it be a group then?

**Comment by Besatnias** [comment]
I think the solution would be to hide the root group and to have other seemingly 'root' groups with groups inside, but they're just groups to categorize stuff. I don't know how possible this is.

**Comment by TheZ3ro** [comment]
> Would enabling multiple root groups conflict with keepass?

I think yes

We can't hide root group because then we won't have a nice interface to change the root's properties.
Maybe a viable solution can be to give root a special default-icon. 
But it's not a real solution, (((and IMHO this it's not a real issue neither)))

**Comment by droidmonkey** [comment]
After messing with keepass a little I have come to the conclusion that this can't be changed since there can only be one root group and it is a full fledged group.

**Comment by phoerious** [comment]
So it's a WONTFIX/CANTFIX then.
