### ISSUE TITLE
Update building instructions

### ISSUE THREAD

**Issue by andschwa** [keepassxreboot/keepassxc#1301]
I was following the build instructions found in the wiki for macOS, and found that this line should be updated:

> `-DCMAKE_PREFIX_PATH=/usr/local/Cellar/qt5/5.9.0_1/lib/cmake`

> `-DCMAKE_PREFIX_PATH=/usr/local/Cellar/qt5/5.10.0/lib/cmake`

The home brew Qt version updated (and it worked just fine).

**Comment by phoerious** [comment]
Done.
