### ISSUE TITLE
autotype tab back

### ISSUE THREAD

**Issue by jonazc** [keepassxreboot/keepassxc#1302]
Is it possible to tab backwards with autotype somehow? Because, for example in [Adminer](https://adminer.diphda.uberspace.de/), the second form field is auto focused, but sometimes you need to change also the first field (server). One can of course select it manually before performing the autotype, but it would be nice to automate this completely.

Just I didn't find a way to tab back to the first field. I tried `{CAPSLOCK}{TAB}{CAPSLOCK}` but that didn't work :)

**Comment by Generator** [comment]
Try with +{TAB},  '+' is the keystroke for Shift.  

You  can see all the keystrokes here [Auto-Type Keystroke Sequences](https://keepass.info/help/base/autotype.html#autoseq)

**Comment by jonazc** [comment]
thanks, I will try that, I was looking here: https://github.com/keepassxreboot/keepassxc/wiki/Autotype-Custom-Sequence but the + wasn't mentioned there.

**Comment by TheZ3ro** [comment]
Yes, `+` is not implemented, see #977

**Comment by jonazc** [comment]
so, to refer to the original issue here it means, that it is not possible with keepassxc?

**Comment by TheZ3ro** [comment]
No, atm it's not possible
