### ISSUE TITLE
Mixed Languages Presented in Various Dialogues

### ISSUE THREAD

**Issue by ipetts** [keepassxreboot/keepassxc#1304]
Mixed language is presented in various dialogues - Ubuntu 17.10 KDE.

## Expected Behavior

Dialogues should all be the same language.

## Steps to Reproduce (for bugs)

Ubuntu 17.10 KDE Edition

```
System Settings > Regional Settings > Language > Preferred Language: American English
                                      Formats > Region: Australia
```
Start KeepassXC and observe the various dialogues.

## Welcome Screen
![screenshot_20171219_192017](https://user-images.githubusercontent.com/9004251/34148573-e6223436-e4f5-11e7-8afa-b806ab467c41.png)

## Open Database
![screenshot_20171219_192237](https://user-images.githubusercontent.com/9004251/34148574-e658ddec-e4f5-11e7-8885-4f023178bc95.png)

## Main Screen (Unlocked)
![screenshot_20171219_192342](https://user-images.githubusercontent.com/9004251/34148575-e691e42a-e4f5-11e7-80aa-491c48336f2d.png)

## Settings
![screenshot_20171219_192451](https://user-images.githubusercontent.com/9004251/34148577-e6c8e40c-e4f5-11e7-8c92-1d63ba8df5c7.png)

## Debug Info

KeePassXC - Version 2.2.4
Revision: 4723f66

Biblioteker:
- Qt 5.9.1
- libgcrypt 1.7.8

Operativsystem: Ubuntu 17.10
CPU-arkitektur: x86_64
Kerne: linux 4.13.0-19-generic

Aktiverede udvidelser:
- KeePassHTTP
- Auto-Type
- YubiKey

KeePassXC - 2.2.4
Revision: 4723f66

Operating system: Linux Ubuntu 17.10 (Kubuntu)
CPU architecture: x86_64
Kernel: 4.13.0-19-generic

Enabled extensions:
- KeePassHTTP
- Auto-Type
- YubiKey

**Comment by phoerious** [comment]
You have selected a language in KeePassXC whose translation isn't complete. Feel free to contribute here to fix this problem: https://www.transifex.com/keepassxc/keepassxc/dashboard/

**Comment by ipetts** [comment]
My selected language in KDE is American English. Is there a program setting that I'm missing?

**Comment by phoerious** [comment]
KeePassXC has its own language setting.

**Comment by ipetts** [comment]
Okay, thanks phoerious. I have located the setting and it was set to Danish for some reason.

Sorry to waste your time.

**Comment by phoerious** [comment]
;-)
