### ISSUE TITLE
KeePassXC installed as snap, prevent laptop from going to sleep, when you close the lid

### ISSUE THREAD

**Issue by user240** [keepassxreboot/keepassxc#1309]
## Expected Behavior

laptop will go to sleep when you close the lid

## Current Behavior

doesn't go to sleep

## Steps to Reproduce (for bugs)

1. Install KeePassXC as snap on laptop
2. run KeePassXC
3. close the lid

**Comment by phoerious** [comment]
Duplicate of #856 (most likely).
