### ISSUE TITLE
Browser integration failing on Win7 x64, reason unknown

### ISSUE THREAD

**Issue by rmenessec** [keepassxreboot/keepassxc#1311]
## Expected Behavior
I'm unable to connect to KeePassXC' KeePassHTTP service with Chrome or Firefox on Windows 7 SP1 x64. I could use some help troubleshooting.

## Current Behavior
Browser extensions time out when attempting to contact the KeePassXC HTTP service.

## Steps to Reproduce (for bugs)
Install KeePassXC, Firefox, Chromium, and browser integration extensions on Windows 7 SP1 x64 with all current official updates.

## Context
I'm trying to complete a migration from LastPass to KeePassXC on my primary (only) Windows machine. I've performed a great deal of basic troubleshooting: disabled Windows Firewall, tried changing the port KeePassHTTP is using, tried using netsh to perform IPv4 and Winsock "resets", and so on. I returned the Windows hosts file to the default content. I verified that KeePassXC really did bind the port (visible in netstat). I've tried using telnet to connect to the port. I can't tell if it's working; I get no data back.

The only "security" software I have installed is Microsoft Security Essentials (now integrated as "Defender" in Windows 8+).

The most frustrating part is that I had all of the browser integration working fine about three months ago, before I started migrating away from LastPass. I installed KeePassXC and the browser extensions, created an empty new database in KeePassXC, and created a single test entry. I tried revoking the original browser extension authorizations; the extensions still act as though they can't reach the server. Neither will return the KeePassHTTP version (now).

I've done a lot of research to see if there's such a thing as a Registry setting or Group Policy setting that would prevent two processes from communicating via localhost sockets, and I've searched for other people having any variation of this problem, and I've come up empty.

The only thing I can recall doing to the machine in the last few months, besides continuing to install new patches from Windows Update, is installing some games—which I've uninstalled to no effect.

I don't run any services on the machine, like a web server or an SSH server, so I don't really have anything to compare with.

## Debug Info
KeePassXC - Version 2.2.0
Revision: caa49a8ef3ee28ed478192389b21d61107b3b8e0

Libraries:
- Qt 5.9.0
- libgcrypt 1.7.7

Operating system: Windows 7 SP 1 (6.1)
CPU architecture: x86_64
Kernel: winnt 6.1.7601

Enabled extensions:
- KeePassHTTP
- Auto-Type
- YubiKey

**Comment by rmenessec** [comment]
ETA: I did have Wireshark and Npcap installed—I did it eight or so months ago—so I uninstalled both Wireshark and Npcap just in case Npcap was somehow eating localhost-to-localhost packets. Nothing changed.

**Comment by phoerious** [comment]
Dumb question: are you using KeePassHTTP-Connector or keepassxc-browser? The latter won't work without additional patches to KeePassXC.

**Comment by rmenessec** [comment]
@phoerious  The former. Sorry, I thought I included this information.

As mentioned above, though, this setup was working previously. All of it. Firefox and Chrome both. I haven't switched extensions since I set everything up; I just replaced the test database with my actual login data from LastPass.

**Comment by droidmonkey** [comment]
Did you try cleaning out the http plugin settings? You should have the plugin "forget" all previous databases. Also, double check that the http plugin is enabled in the keepassxc settings. Lastly, check to make sure it isn't your firewall by temporarily disabling it and trying to connect.

**Comment by rmenessec** [comment]
@droidmonkey I tried all of those. Either this is a so-simple-I'll-smack-myself problem, or it's a d@mned hard one. I'm going to reformat the original text and post below so it's clear what steps I've taken.

**Comment by rmenessec** [comment]
# Troubleshooting I've already tried

**NOTE 1:** Everything works fine on my Linux machines.
**NOTE 2:** _**This worked on my Windows machine three months ago.**_

- Firefox _and_ Chromium
- Definitely using the correct extensions
- Extensions are configured correctly
- Extensions were authorized correctly in KeePassXC
- Revoked authorization in KeePassXC--extensions are **not** asking for new authorization
- Windows Firewall _completely_ disabled
- _No other security software installed or enabled!_
- Tried changing the port KeePassXC listens on
- Tried changing the port the extensions are connecting to
- Verified KeePassXC really is listening on the default port (or any configured port)
- Had Npcap installed; uninstalled it
- "Microsoft Loopback Device" driver is not installed
- Had VirtualBox installed; uninstalled it
- Reset every interface _AND_ the Winsock catalog with netsh
- The Windows hosts file is fine!
- Tried disabling IPv6; no effect
- Changed extension hostname definitions from "localhost" to "127.0.0.1"; no change

**Comment by rmenessec** [comment]
@phoerious @droidmonkey 

What really worries me is that I can't connect to KeePassXC via telnet. If I telnet (from an Admin-priv local CMD.EXE) to the default port, it connects, but I don't get anything back.

I'm not familiar with the KeePassHTTP setup. What would you expect to get back from a KeePassHTTP service? I've tried sending "GET /" and pressing Enter a lot and various gobbledygook. I'm not getting a single byte back.

Telnet is acting like it's not really connected to the KeePassHTTP service. I should get _something_ back, right?

If there's anyone on the team with significant Windows experience, and they're not looking at this, can you pull them in? I'm thinking that this is a Windows-specific problem. Maybe I changed a Registry setting sometime in the last three months, and I'm forgetting about it.

If I leave Npcap and Wireshark installed, and capture localhost traffic, what I actually see—I don't know if it's accurate at all—is attempted TCP handshakes on KeePassXC' listening port and RSTs coming back. Telnet doesn't act like it caught an RST; it remains connected.

**Comment by rmenessec** [comment]
ETA: If no one comes up with anything nifty to try in the next couple of days, I may try to [capture the machine state for VirtualBox](https://www.virtualbox.org/wiki/Migrate_Windows), then take this as a pressing reason to finally reinstall my workstation cleanly with Windows 10.

**Comment by phoerious** [comment]
You can find the protocol specification here: https://github.com/pfn/keepasshttp/blob/master/README.md

I can't look into the issue right now, but I'll see what I can do over the next days.

**Comment by phoerious** [comment]
BTW if telnet doesn't time our or gives you a connection refused error, chances are that KeePassXC is actually listening and the problem might be the browser or browser plugin.

**Comment by rmenessec** [comment]
@phoerious 
> BTW if telnet doesn't time our or gives you a connection refused error, chances are that KeePassXC is actually listening and the problem might be the browser or browser plugin.

KeePassXC has definitely been able to bind its configured port. That much I can see with netstat.

What has me worried specifically is that one of the games I installed (re: OP) had to be refunded because it just did not work. Since it was a standard closed-source, commercial thing, it had no real troubleshooting tools... but the little video output it did produce showed what looked like an [id Tech](https://en.wikipedia.org/wiki/Id_Tech)-type game engine producing console output—I could only see it for a few seconds. Around the end of the visible scroll, I believe it said something about listening for a connection from a game client; I think the game interface. That's where it always timed out and exited after a few seconds.

That particular game did have a _vast_ number of known issues, so that's not conclusive, but it would explain a lot if some (all?) 3rd-party software is having trouble making loopback socket connections.

Can you (anyone) recommend a quick way to install some kind of unprivileged server / service and corresponding client so I can test the general ability to make loopback TCP socket connections work? I'm aware of Cygwin, but it looks like a lot of effort, and I don't know if fiddling with non-native code is going to produce valid results.

If I can prove whether or not [unprivileged] TCP loopback is broken, either it'll narrow my search considerably or I'll be able to rule something out. This is the only real idea I've got; everything else I've chased has been a dead end.

**Comment by droidmonkey** [comment]
Just to be complete, try following these steps as well to reset some more stuff:

**Comment by rmenessec** [comment]
> Just to be complete, try following these steps as well to reset some more stuff: https://kb.wisc.edu/page.php?id=6653#7vista

^^ Troubleshooting I've already tried
