### ISSUE TITLE
Grey out Apply button once clicked by user

### ISSUE THREAD

**Issue by grenzor** [keepassxreboot/keepassxc#1313]
## Expected Behavior

Once the apply button is clicked it should be greyed out. Only when the user has made a change and not clicked apply yet should it be clickable.

## Current Behavior

Once the apply button is clicked it is still clickable which can be confusing to the user whether or not applied changes have taken effect.

**Comment by archderwelt** [comment]
Yes, confusing. Not sure whether changes have been saved to disc or not. So plz, grey out the save btn after save or if no changes made.

**Comment by dwilches** [comment]
Hi,
Can I get this issue assigned?
Thanks.

**Comment by droidmonkey** [comment]
You got it. Only core devs can be assigned so I'll just assign myself
