### ISSUE TITLE
Add an option to unlock database with kwallet

### ISSUE THREAD

**Issue by dstrelnikov** [keepassxreboot/keepassxc#1321]
Please, consider a possibility to add an option of password less database unlocking using kwallet (part of KDE).

Now I'm use this trick:
```
kwallet-query -f 'Passwords' -r 'KPDB' kdewallet | keepassxc --pw-stdin ~/passwd.kdbx
```

**Comment by droidmonkey** [comment]
Seems like you have it working already, what further integration is needed?

**Comment by dstrelnikov** [comment]
It would be nice to have a transparent integration with kwallet/gnome-keyring/osx-keychain/etc.

For example, an optionn for automatically save passwords for databases in a kwallet.

**Comment by phoerious** [comment]
Related to #440

**Comment by livier** [comment]
Had the same hope, 
but did not understand what dstrelnikov did, Where to put or use his trick.
Did not find it in a doc too.

**Comment by phoerious** [comment]
you have to enter it on the command line on Linux or macOS. On Windows, it won't work.

**Comment by secretmango** [comment]
How does the command work? It opens the app and inserts "There is no passwort set!" or something. I cant find the option in KDEWallet to set the passoword for the app

**Comment by michaelk83** [comment]
> `kwallet-query -f 'Passwords' -r 'KPDB' kdewallet | keepassxc --pw-stdin ~/passwd.kdbx`
> How does the command work?

It reads (`-r`) a password named "KPDB" from the folder (`-f`) named "Passwords" inside the wallet named "kdewallet", and passes it to KeePassXC to unlock the database file at `~/passwd.kdbx`. You'll need to create that entry in KWallet manually, and save the KeePassXC password in there. You can adjust the names as you wish, as long as you adjust the command to match. You'll also need to adjust the KeePass database path and file name to match what you have.

I have to say, I don't recommend this solution. Your KeePass database security will be reduced to whatever security level you have with KWallet.

**Comment by secretmango** [comment]
> > `kwallet-query -f 'Passwords' -r 'KPDB' kdewallet | keepassxc --pw-stdin ~/passwd.kdbx`
> > How does the command work?
> 
> It reads (`-r`) a password named "KPDB" from the folder (`-f`) named "Passwords" inside the wallet named "kdewallet", and passes it to KeePassXC to unlock the database file at `~/passwd.kdbx`. You'll need to create that entry in KWallet manually, and save the KeePassXC password in there. You can adjust the names as you wish, as long as you adjust the command to match. You'll also need to adjust the KeePass database path and file name to match what you have.
> 
> I have to say, I don't recommend this solution. Your KeePass database security will be reduced to whatever security level you have with KWallet.

thanks! Okay that was pretty self-explanatory, but how do I create an entry manually? I wasnt able to find anything in the wikis about this, seems to be only invoked by apps, which cant really be, there must be a solution.

Using LUKS, the strength of the KWallet is not so much of a problem I guess, its more about being able to have a really strong password, to sync it securely

**Comment by michaelk83** [comment]
You'll need to open the wallet in KWalletManager. If it just shows you an empty wallet with no folders, you may need to create a new wallet, because it should have at least a "Form Data" and "Passwords" folders by default. Expand the "Passwords" folder, right-click "Passwords" under that, and click "New". (The UI is really bad, but that's what there is.)

Even with LUKS, the security is at least reduced to the strength of the LUKS/KWallet password. So you either need a strong password of KeePassXC, or a strong password for LUKS/KWallet. Then there's the question of encryption quality and possible other vulnerabilities (though I expect LUKS *should* be ok on that front; and I suppose it's easier to copy a single kdbx or wallet file than to remove or clone your whole hard drive).

If you have the means, consider getting a YubiKey iinstead. Then you can use a weak memorized password combined with the strong hardware key.

**Comment by secretmango** [comment]
For anyone looking for an easy guide:

You just need to 
1. open Kwalletmanager
2. if there is none, create a folder called "Passwords"
3. Create an entry named "Keepass" (or anything, change the command then), store your password in that entry.

example for Flatpak:
```
kwallet-query -r Keepass kdewallet | /usr/bin/flatpak run --branch=stable --arch=x86_64 --command=keepassxc --file-forwarding org.keepassxc.KeePassXC --pw-stdin /path/to/vault.kdbx
```

example for regular app:

```
kwallet-query -r Keepass kdewallet | keepassxc --pw-stdin /path/to/vault.kdbx
```

The security of Kwallet is questionable though.

**Comment by livier** [comment]
Here is  solution to use kwallet to pass the password to keepssxc .... 

But is there a solution to use keepassxc instead ok kwallet, for any use ?

**Comment by M43R** [comment]
> Here is solution to use kwallet to pass the password to keepssxc ....
> 
> But is there a solution to use keepassxc instead ok kwallet, for any use ?

https://forum.manjaro.org/t/replace-kwallet-with-keepassxc-as-keyring/159188/8
