### ISSUE TITLE
keepassxc 2.2.2 stopped starting

### ISSUE THREAD

**Issue by martiGIT** [keepassxreboot/keepassxc#1324]
Hi there,

I run keepassxc with debian 9 testing (buster, previously upgraded from stretch) and recently keepassxv stopped starting. When running from console I get:
`qt.svg: link SVGCleanerId_0 hasn't been detected!
`
I tried to strace and got a lot of:
`recvmsg(6, {msg_namelen=0}, 0)          = -1 EAGAIN (Resource temporarily unavailable)
`
I have upgraded to 2.2.4 and this did not change anything. 

I tried to run keepassxc as root (also with sudo), and it works well

**Comment by phoerious** [comment]
This is a Qt problem. Can you try if the AppImage works?

**Comment by martiGIT** [comment]
thanks for feedback, this does not work too:
`
$ ./KeePassXC-2.2.4-x86_64.AppImage 
zenity, kdialog, Xdialog missing. Skipping /tmp/.mount_KeePasFmMIWq/usr/bin//keepassxc_env.wrapper.
`
im running XFCE 4.12

**Comment by phoerious** [comment]
You (or Debian) managed to mess up your system somehow. Qt is trying to open a socket but doesn't have permission to do so. Unfortunately, it's hard to impossible to debug without further information about which socket it as.
As a starter, I would try clearing out files in /tmp and /var/tmp and reboot your system (to also clear /run etc.).

**Comment by martiGIT** [comment]
tried that, and in fact tmp files are successfully created:
```
$ sudo lsof |grep keepass |grep tmp
keepassxc 1937                     m   15wW     REG               0,39       18      31390 /tmp/keepassxc-m.lock
keepassxc 1937                     m   16u     unix 0xffff9aeb2b535400      0t0      31393 /tmp/wWIuuA/s type=STREAM
QXcbEvent 1937 1938                m   15wW     REG               0,39       18      31390 /tmp/keepassxc-m.lock
gmain     1937 1939                m   15wW     REG               0,39       18      31390 /tmp/keepassxc-m.lock
gdbus     1937 1940                m   15wW     REG               0,39       18      31390 /tmp/keepassxc-m.lock
QDBusConn 1937 1941                m   15wW     REG               0,39       18      31390 /tmp/keepassxc-m.lock
```
also permissions seems to be proper
```
$ ls -al /tmp/keepassxc-m.*
-rw-r--r-- 1 m m 18 Dec 26 20:25 /tmp/keepassxc-m.lock
srwx------ 1 m m  0 Dec 26 20:25 /tmp/keepassxc-m.socket
```

**Comment by TheZ3ro** [comment]
The `zenity, kdialog, Xdialog missing. Skipping ...` error is caused by AppImage, not by KeePassXC.
See [1][2]


[1] https://discuss.pixls.us/t/appimage-needs-testing/5434/2
[2] https://github.com/probonopd/linuxdeployqt/issues/34#issuecomment-255515868

**Comment by martiGIT** [comment]
I have removed keepassxc.ini from .config dir, and keepassxc started without problem

**Comment by TheZ3ro** [comment]
Probably some problem with the Main window geometry, who knows

**Comment by martiGIT** [comment]
possibly, I have just diff'ed ini files and got this differences:
broken:
```MainWindowGeometry=@ByteArray(\x1\xd9\xd0\xcb\0\x2\0\0\0\0\x2\xb4\0\0\0\x1f\0\0\x5\xfe\0\0\x2\x82\0\0\x2\xb4\0\0\0\x1f\0\0\x5\xfe\0\0\x2\x82\0\0\0\0\0\0\0\0\a\x80)```
new one: 
```MainWindowGeometry=@ByteArray(\x1\xd9\xd0\xcb\0\x2\0\0\0\0\x2\xf9\0\0\x1/\0\0\x6\x1a\0\0\x3\xa5\0\0\x2\xfa\0\0\x1I\0\0\x6\x19\0\0\x3\xa0\0\0\0\0\0\0\0\0\a\x80)```

**Comment by jD91mZM2** [comment]
This happened to me when changing my home folder. Deleting the keepassxc.ini file also fixed the problem.

**Comment by TheZ3ro** [comment]
I just tested this and using a broken geometry won't crash KeePassXC (at least on GNU/Linux with X11 and XFCE)

I tested the geometry provided above by @martiGIT and various geometry with deleted pieces of the byte array. None crashed KeePassXC

**Comment by jD91mZM2** [comment]
[My old/new diff](https://gist.github.com/jD91mZM2/1bec9ba77c8a30cfa6d3d7808315b4ab)

Perhaps
```
LastOpenedDatabases=@Invalid()
```
is related?
