### ISSUE TITLE
Can't open preferences

### ISSUE THREAD

**Issue by woj-tek** [keepassxreboot/keepassxc#1332]
I'm new to KeePassXC.
I was just trying to set it up when I run into a weird problem. While having app open I opened preferences (mac: `cmd` + `,` -- but there is also an entry in the menu). First time it worked, I enabled a try icon, accepted and afterwards each time I want to open preferences again I get a different screen with items like: "Name of the database", "Description of the database", "Algorithm" etc

## Expected Behavior
The shortcut should open preference pane.

## Current Behavior
It opens databases preferences instead of application preferences (just a guess)

## Steps to Reproduce (for bugs)
1. Hit "preferences" in "KeePassXC" menu

## Debug Info
KeePassXC - Versión 2.2.4
Revisión: 4723f66

Librerías:
- Qt 5.9.1
- libgcrypt 1.8.1

Sistema operativo: macOS High Sierra (10.13)
Arquitectura de CPU: x86_64
Núcleo: darwin 17.3.0

Extensiones habilitadas:
- KeePassHTTP
- Auto-Type
- YubiKey

**Comment by droidmonkey** [comment]
Its in the menu, Tools -> Settings

**Comment by woj-tek** [comment]
In Tools I only have:
* Block database (cmd+L)
* password generator.

(vide https://www.dropbox.com/s/f3gxt43x1gk56l9/Captura%20de%20pantalla%202017-12-28%2014.37.24.png?dl=0)

Usually, preference item on mac is in the "App menu" and the item is there (https://www.dropbox.com/s/g7jhpkcvu1mjxmw/Captura%20de%20pantalla%202017-12-28%2014.37.08.png?dl=0) but selecting it doesn't open preferences but the window I mentioned before.
What's more - it worked first (and only) time.

(Sorry for spanish in the screenshots but it takes OS language and can't access preferences now to change it)

**Comment by droidmonkey** [comment]
No problem on the language, your description is great. This is actually an issue, i have no idea why mac is doing this.

**Comment by woj-tek** [comment]
Hmm, I'm very, very new to KeePassXC but - is there some loge there? Any way to debug this? Simple restarting of the app doesn't work. 

I've played a bit with the issue and I think I got some clue.
Given, that this shortcut/menu entry opens database properties instead of app settings I decided to create new database - unfortunately problem continued. But this revealed database tabs! So I used cmd+w (close tab/close document/close database). I closed all of them and then correct preference pane started to show up.

Maybe this is by design (if DB is open show database properties) but it's a bit confusing so at least should be renamed if it's intentional.

**Comment by droidmonkey** [comment]
That certainly is not the design at all. You should be able to open the database properties independent of the application settings. I think this is MacOS thinking its so smart and shadowing the app properties link when the database is open. This is very clearly a mac issue.

**Comment by woj-tek** [comment]
Hmmm, haven't run into same issue in any other mac (or universal app, including QT based) with multiple documents (similar concept as here) that would open per-document properties instead of whole app properties. This feels like some binding issue with the shortcuts.

I've tried googling a bit but nothing remotely similar showed up.

**Comment by droidmonkey** [comment]
So looks like this is a known "feature" of MacOS: https://stackoverflow.com/questions/38880724/qt-configure-menu-item-doesnt-appear-on-tools-menu-on-mac

We can overcome this by setting those menu items to QAction::NoRole

**Comment by TheZ3ro** [comment]
Ping @weslly

**Comment by weslly** [comment]
I can reproduce this when setting the language to spanish, but it doesn't seem to happen with other languages.

**Comment by droidmonkey** [comment]
Take a look at the PR I just posted, I think this is contextual movement and some translations don't trigger it (perhaps including english)

**Comment by weslly** [comment]
#1335 solves the issue

**Comment by woj-tek** [comment]
If I may - having the `Preferences` in the application menu is actually desired (virtually all application have that item there and pinning it to `Tools` could be quite counterintuitive for mac users)

**Comment by weslly** [comment]
@woj-tek this was the behavior before #483, @droidmonkey's pr only added the `NoRole` flag to the database settings.

**Comment by woj-tek** [comment]
Ah, great!
