### ISSUE TITLE
Tab key no longer switches between views

### ISSUE THREAD

**Issue by asfethan** [keepassxreboot/keepassxc#1333]
## Expected Behavior

When I press Tab key focus switches from groups tree view to items view and back after another Tab key press.

## Current Behavior

With recent update I can no longer use keyboard-only navigation because Tab key doesn't switch focus from groups tree view to items listed in currently focused group. Switching back from selected item to groups tree works as usual.

## Possible Solution

Some Qt stuff voodoo?

## Steps to Reproduce (for bugs)

1. Open database with multiple groups and subgroups
2. Navigate with arrows to group from witch you want password for some item
3. Press Tab to switch focus from group list to item list
4. Nothing happens

## Context

Quick keyboard-only navigation. 

## Debug Info

KeePassXC - 2.2.2
Revision: 6d46717

Libraries:
- N/A

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: 4.14

Enabled extensions:
- N/A

**Comment by lenormf** [comment]
I can confirm, it's pretty annoying.

**Comment by lenormf** [comment]
Thanks a lot!
