### ISSUE TITLE
Feature Request - Store (add) existing browser login and password information not already in KeePassXC database.

### ISSUE THREAD

**Issue by phd21** [keepassxreboot/keepassxc#1339]
Hi Everyone involved with KeePassXC,

First, thank you for this excellent application.

Feature Request - Store (add) existing browser login and password information not already in KeePassXC database.

While in Firefox 57 Quantum, I already have stored logins and passwords, apparently some of which were not in my KeePassXC database. It would be awesome in any browser to have "keepasshttp-connector" or KeePassXC automatically detect that a wesbite login was not in KeePass but stored in the browser and automatically save it (or ask) to my KeePass database. It would be really nice to do that with the entire browser's stored logins and passwords, like an import option. Especially since Firefox 57 no longer has an option to export passwords, but this would be a great option for all browsers.

I am currently using Linux Mint KDE 18.2 based on Ubuntu 16.04 and Linux Mint KDE 17.3 based on Ubuntu 14.04 with current browsers Firefox 57, Slimjet, Chrome, Opera, Brave, etc... with current versions of KeePassXC and "keepasshttp-connector".

Thanks!

Best regards to you and yours,
Phil
phd21

**Comment by hifi** [comment]
There was a Firefox extension pre-Quantum to do that but the new WebExtension API does not have such functionality.

I understand that it would be really handy but the best bet would be to find out how you can *export* them from your browser manually rather than through an automation.

**Comment by phoerious** [comment]
As I understand, this cannot be solved, so I'll close this as WONTFIX (CANTFIX).
