### ISSUE TITLE
 Lock database when OS is locked

### ISSUE THREAD

**Issue by rockdreamer** [keepassxreboot/keepassxc#134]
## Expected Behavior
When a user closes the lid of his laptop, or if the session is locked due to inactivity or because the user locks it himself, the currently open database is closed.

## Current Behavior
Currently, if the user closes the lid of his laptop, the database remains open causing a possible infromation leak.

## Context
Original issue: https://dev.keepassx.org/issues/399

**Comment by droidmonkey** [comment]
This was closed in #545
