### ISSUE TITLE
Global auto-type breaks the email on https://www.tumblr.com/login if the email contains the letter 'l'

### ISSUE THREAD

**Issue by rootkea** [keepassxreboot/keepassxc#1341]
## Expected Behavior
When activated a global auto-type through shortcut key sequence "foobar@gmail.com" should get inserted into email field at https://www.tumblr.com/login

## Current Behavior
Currently, "foobar@gmail.com" gets broken at letter 'l' and thus the email field gets "foobar@gmai" and password field contains ".com" (apparently 'l' gets used as ENTER)

## Steps to Reproduce (for bugs)
1. Set Global auto-type shortcut
2. Add entry with title "Tumblr", email "foobar@gmail.com"
3. Set custom auto-type sequence to be {USERNAME}
4. Open "https://www.tumblr.com/login" in browser
5. Activate global auto-type sequence using global auto-type shortcut

## Debug Info
KeePassXC - Version 2.2.4

Libraries:
- Qt 5.9.2
- libgcrypt 1.6.1

Operating system: Debian GNU/Linux 9 (stretch)
CPU architecture: x86_64
Kernel: linux 4.9.0-4-amd64

Enabled extensions:
- KeePassHTTP
- Auto-Type
- YubiKey

PS - Right clicking on entry and selecting "Perform Auto-Type" works as expected though! i.e. email field gets complete "foobar@gmail.com".

**Comment by rootkea** [comment]
Can anybody confirm/verify the bug at their end?

**Comment by hifi** [comment]
No repro here. Tested sequence `{USERNAME}{ENTER}{DELAY 500}{PASSWORD}` and it worked fine for me.

**Comment by rootkea** [comment]
May be it's my setup then. (I don't know what exactly)
Anyways, I changed global shortcut key to `Alt-x` as apparently `Shift` is also causing issues.

**Comment by markhewett** [comment]
I've seen issues on macOS with auto-type breaking if I keep certain keys held down - see #1306 - so maybe this is something similar?

**Comment by rootkea** [comment]
@markhewett 
> I've seen issues on macOS with auto-type breaking if I keep certain keys held down - see #1306 - so maybe this is something similar?

No. #1306 is an issue which arises if you keep the key pressed. But here I press the global shortcut (Ctrl-Alt-A) then *release* all keys. A pop-up appears. Select desired entry. And then the auto-complete happens in the desired window. This is all while the key(s) have been already released.

With further discussion with @hifi on #keepassxc channel helped me ravel more details. If a shortcut is changed to Alt-A everything goes fine.

It looks like Tumblr cashes(!?) the key sequence and then interprets 'l' as Ctrl(cached) + 'l' = Form Feed (from ASCII)

But it still bugs me if the issue is at Tumblr's end then why @hifi couldn't reproduce it?

Meanwhile I've changed my shortcut to Alt-X and the issue is no more there! (Since Ctrl is missing)

**Comment by hamoid** [comment]
Same issue here. Up-to-date archlinux, dvorak keyboard, no Desktop environment. Using `setxkbmap -option "caps:ctrl_modifier" -option "compose:ralt" -option "eurosign:5" -layout us -variant dvp`

I reduced the typing speed very much, and still same issue. It seems to tab when reaching a lowercase L.

**Comment by droidmonkey** [comment]
As discussed this is a "feature" of tumblr caching the ctrl key for eternity.
