### ISSUE TITLE
KeePassXC installed as snap, unable to access YubiKey for Challenge Response

### ISSUE THREAD

**Issue by MAHDTech** [keepassxreboot/keepassxc#1342]
KeePassXC installed as snap is unable to access YubiKey for Challenge Response.

## Expected Behavior
KeePassXC should detect the connected YubiKey

## Current Behavior
 the challenge response box remains greyed out.

## Possible Solution
I'm not real familiar with snaps yet, but looks like it might need an interface added to the snapcraft.yaml in order to access HID devices on the system as I see raw-usb is already added.

[Snap Interfaces](https://docs.snapcraft.io/reference/interfaces)

## Steps to Reproduce (for bugs)
1. snap install keepassxc
2. plugin yubikey
3. open keepassxc snap
4. observe no yubikey detected

## Context
No Challenge Response, means you cannot open a database using it.

## Other
On the same system (Ubuntu) I have installed KeePassXC from .deb packages and access to the YubiKey is working correctly.

## System Details
Operating system: Ubuntu 17.10
CPU architecture: AMD64
Kernel: 4.12

## Enabled extensions:
- None

**Comment by droidmonkey** [comment]
Did you follow our faq? https://keepassxc.org/docs#faq-appsnap-yubikey

**Comment by MAHDTech** [comment]
Yep, forgot to add I ran this command as step 1.5:

`sudo snap connect keepassxc:raw-usb core:raw-usb`

Then plugged in the YubiKey as step 2.

I have also tried hitting refresh, unplugging and replugging etc. The refresh works in the .deb but I can't get it to work on the snap.

Is there some other additional isolation going on I need to change?

**Comment by droidmonkey** [comment]
I have not tested yubikey in snaps lately, they could have broken something. The snap ecosystem is far from stable.

**Comment by jeukel** [comment]
Hi. I guess is the same (accessing devices outside the sandbox) I would like to access my db which is on a usb stick but can't since the snap has no access to devices.

**Comment by droidmonkey** [comment]
Read the FAQ please.

https://keepassxc.org/docs/#faq-appsnap-homedir

**Comment by droidmonkey** [comment]
Thanks for the tip I will look into this, probably missing a stage package in the snap.

**Comment by droidmonkey** [comment]
I could not get this to work without installing the libykpers on the host side. I confirmed that the snap was loading the libykpers from the snap libraries...

**Comment by jpc2769** [comment]
I am having the same issue, except that I installed with the Ubuntu distribution, not snap. Will this solution work for me too even though it is for snap?

**Comment by jpc2769** [comment]
So I tried following the one relevant entry in the faq, it said to run this in the terminal:

`sudo snap connect keepassxc:raw-usb core:raw-usb`

When I do that, this is the output that I get:

`error: snap "keepassxc" has no plug named "raw-usb"`

I installed keepassxc from the Ubuntu repositories, not from snap (whatever that is), so I have no idea what this means or if it is even relevant to my issue.

**Comment by droidmonkey** [comment]
The snap is if you install KeePassXC from the Ubuntu Store. It is probably better that you are running the repository app instead of the snap. Does your yubikey show up at all in the database unlock dialog?

**Comment by jpc2769** [comment]
I'm not sure what the "database unlock dialog" is; when I open Keepassxc, there are three checkboxes: password, key file, and challenge response. Next to "challenge response," there is a button marked "refresh". Until this morning, I would plug my yubikey into a usb port, click the "refresh" button next to "challenge response", then click "ok" and I would be prompted to touch the button on the yubikey; when I did, the database would open.

Now, the "challenge response" item is grayed out, and clicking on refresh does absolutely nothing.

**Comment by droidmonkey** [comment]
That indicates that your Yubikey is not being detected by the program (and perhaps the OS). Again, I think this is a direct result of upgrading to Ubuntu 18.04. Can you try using the Yubikey personalization tool to debug why your Yubikey is not detected?

https://www.yubico.com/products/services-software/download/yubikey-personalization-tools/

**Comment by jpc2769** [comment]
I opened that program, tried using the "challenge response tester," but the "perform" button is non-responsive. If there is something else I should check, please tell me what to do.

**Comment by jpc2769** [comment]
It does not appear to be physically broke, and it does light up briefly when I plug it in. How would I have done that (wiped it) exactly?

**Comment by jpc2769** [comment]
I tested the yubikey on this site: https://demo.yubico.com/?tab=one-factor and it worked.

**Comment by lindhe** [comment]
+1 on installing `libykpers-1-1` to make it work on Ubuntu 18.04
