### ISSUE TITLE
Access error for config file

### ISSUE THREAD

**Issue by janmach71** [keepassxreboot/keepassxc#1345]
When opening Tools -> Settings I can see red error:

Access error for config file /home/jan/snap/keepassxc/28/.config/keepassxc/keepassxc.ini

And changes in settings are not saved. It does not make much sense, as ls gives the following result:

ls -lla /home/jan/snap/keepassxc/28/.config/keepassxc/keepassxc.ini
-rw-rw-r-- 1 jan jan 559 pro 18 23:15 /home/jan/snap/keepassxc/28/.config/keepassxc/keepassxc.ini

and I'm also able to modify the file with nano editor. 

## Expected Behavior
No error message and settings is saved.

## Current Behavior
Error message and settings is lost.

## Steps to Reproduce (for bugs)
1. fresh install of keepassx
2. Tools -> Settings

## Debug Info
KeePassXC - Version 2.2.4
Revision: 4723f66
Distribution: Snap

Libraries:
- Qt 5.5.1
- libgcrypt 1.6.5

Operating system: Ubuntu Core 16
CPU architecture: x86_64
Kernel: linux 4.13.0-19-generic

Enabled extensions:
- KeePassHTTP
- Auto-Type
- YubiKey

**Comment by BNoronha1** [comment]
Hi, did you find a solution to this problem? Could you please tell me? Thanks

**Comment by WalterMccan** [comment]
Not sure why this issue was closed without any explanation. It still happens if you install different versions of KeePassXC. e.g. snap and regular or flatpack package.

**Comment by droidmonkey** [comment]
I cannot reproduce this issue at all. What do you mean by your last sentence regarding different versions being installed. KeePassXC Snap package stores settings data in ```/home/[user]/snap/current/.config/keepassxc/keepassxc.ini```. Natively installed KeePassXC stores settings data in ```/home/[user]/.config/keepassxc/keepassxc.ini. I don't know how flatpak's store their data, we do not maintain that package.
