### ISSUE TITLE
TOTP copy/past doesn't work

### ISSUE THREAD

**Issue by Shorty365** [keepassxreboot/keepassxc#1349]
Copy pasting a TOPT code does't work as expected. It pastes an empty string.

## Expected Behavior
Copy of the than valid time-code and paste this code in Firefox or whatever application.

## Current Behavior
It either does not copy the valid sting or pastes an empty string. Also Keepassxc crashes occasionally on this copy-action.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Debug Info

KeePassXC - VERSION
Revision: REVISION

Libraries:
- LIBS

Operating system: Kubuntu 16.04 (all patched up)
CPU architecture: AMD64
Kernel: 4.10.0-42

Keepasscx 2.2.4
Firefox 57.0.3

Enabled extensions:
- EXTENSIONS

**Comment by TheZ3ro** [comment]
How are you copying the TOTP code?

**Comment by Shorty365** [comment]
Yes, I'm copying the TOTP code. I use right-click on the account, select "Timed one-time-password" and then "Copy TOTP". Pasting (ctrl-v) results in an empty string or some older string from the Clipboard.

**Comment by weslly** [comment]
@Shorty365 by default, the clipboard is cleared after 10 seconds. You can disable or increase this time at the settings.

**Comment by Shorty365** [comment]
Changed setting to 30 seconds and now it works for me. Probably I was not fast enough to perfom the copy and paste withing 10 seconds. Ticket can be closed.
