### ISSUE TITLE
"_FORTIFY_SOURCE" redefined

### ISSUE THREAD

**Issue by calmarc** [keepassxreboot/keepassxc#1350]
command-line>:0:0: error: "_FORTIFY_SOURCE" redefined [-Werror]  
 built-in>: note: this is the location of the previous definition

(on make)
http://www.calmar.ws/tmp/062-Wed-screen.png
gcc --version
gcc (Gentoo 6.4.0 p1.1) 6.4.0

**Comment by calmarc** [comment]
oh.. how can I close that - sorry

**Comment by TheZ3ro** [comment]
Seems an easy thing to fix, i'm making a patch

**Comment by TheZ3ro** [comment]
@calmarc can you test compiling the [hotfix/undef_fortify](https://github.com/keepassxreboot/keepassxc/tree/hotfix/undef_fortify) branch?

**Comment by calmarc** [comment]
Yep, works. Thanks a lot TheZ3ro ;)
(just added your patch manually so)
