### ISSUE TITLE
Missing Required Lib in Build Environments for Building with new Native MEssaging Browser Extension

### ISSUE THREAD

**Issue by iceman73** [keepassxreboot/keepassxc#1353]
Just need to add an additional required Lib if using the Browser option. Add a section to each build environment like you did for Yubi-Key compilation.

## Expected Behavior
Build Environment Wikis to include the dependency for libsodium if compiling in native messaging for web browser addons

## Current Behavior
Does not show you need this dependency

## Possible Solution
**For windows mysys build environment:**
Install needed Browser extension libraries if using native messaging
This command will install libsodium
pacman -Sy mingw-w64-x86_64-libsodium

**For Linux**
On Debian/Ubuntu:
sudo apt-get install libsodium18

On Fedora/RHEL/CentOS:
sudo yum install libsodium

On Arch Linux:
pacman -Sy mingw-w64-x86_64-libsodium

**Mac OS X**
brew install libsodium

**Comment by phoerious** [comment]
We just merged native messaging, so wikis isn't up to date yet, but I updated it.
The Linux packages aren't quite right. You actually need the dev packages (libsodium-dev for Debian, libsodium-devel for Fedora) and the Arch package is just libsodium.

**Comment by iceman73** [comment]
Thankyou guys
