### ISSUE TITLE
Unable to open database with pw-stdin

### ISSUE THREAD

**Issue by Generator** [keepassxreboot/keepassxc#1358]
## Expected Behavior

`secret-tool lookup name keepass | keepassxc --pw-stdin --keyfile /path/to/keyfile /path/to/database.kdbx` should open database from command line

## Current Behavior

Using pw-stdin from command line KeePassXC opens without any database/keyfile selected and the open database dialog becomes unusable 
![captura de ecra_2018-01-06_16-35-34](https://user-images.githubusercontent.com/44146/34641823-ce4aa2d4-f301-11e7-955c-3c7d249f32f0.png)

## Possible Solution

The issue looks to be in ffddcb5060cead637345947cc23b8b9b0f0ab6bf
Builds before that pull request work without issues with pw-stdin

## Steps to Reproduce (for bugs)

1. Use a develop build
2. Open database with pw-stdin echo "DBpassword" | keepassxc --pw-stdin --keyfile /path/to/keyfile /path/to/database.kdbx

## Debug Info

KeePassXC - Version 2.2.4
Revision: 5fe1840

Libraries:
- Qt 5.10.0
- libgcrypt 1.8.2

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 4.14.7-pf

Enabled extensions:
- KeePassHTTP
- Auto-Type
- YubiKey
- SSH Agent
- Native messaging browser extension

**Comment by daxcore** [comment]
Line 149 of master branch is missing in develop, so --pw-stdin doesn't work.

https://github.com/keepassxreboot/keepassxc/blob/master/src/main.cpp#L149

**Comment by martin9959** [comment]
seems to also affect 2.3.0 stable (Ubuntu package), a regression to 2.2.4 stable.

**Comment by TheZ3ro** [comment]
I can reproduce this
