### ISSUE TITLE
Add tag-based organization, if possible!

### ISSUE THREAD

**Issue by MathiasSM** [keepassxreboot/keepassxc#1361]
Organizing into folders is fine, and might be enough for most use cases. But it would be really cool to be able to use tags to classify entries. I've seen some other Keepass managers do it, although I don't see in the Keepass "standard".

## Expected Behavior
To be able to classify the entry for my gmail account both into "Personal" and into "Work" categories/folders.

## Current Behavior
One can only put an entry into a single folder or copy it into several (denormalizing is baaaad).

## Possible Solution
Implement a tag system and let users use that instead or along with the folder system (simple to start, but all tag system can be improved with better search or even hierarchical tags). To be able to add tags to entries and see a list of tags somewhere else, select one and see associated entries, should be quite enough for a start. 

## Context
Some people, if not most, that use password managers use them to handle tens or even hundreds of entries. Obviously not only for passwords but for security-critical info like credit cards and the like. Organizing all those entries into a folder structure is many enough for most users, o when the number of passwords is low, but being able to associate a single password to many categories should prove itself useful when a rigid classification is not always easy or even possible.

## Debug Info
KeePassXC - Version 2.2.4
Revision: 4723f66

Libraries:
- Qt 5.9.1
- libgcrypt 1.8.1

Operating system: macOS Sierra (10.12)
CPU architecture: x86_64
Kernel: darwin 16.7.0

Enabled extensions:
- KeePassHTTP
- Auto-Type
- YubiKey

**Comment by yan12125** [comment]
Looks like the same as #508?
