### ISSUE TITLE
keepassxc --version should work even if KeepassXC is running

### ISSUE THREAD

**Issue by anlutro** [keepassxreboot/keepassxc#1362]
I've installed KeepassXC using an AppImage on Debian 9/Stretch. I've got a script which conditionally upgrades KeepassXC if the version isn't the most recent one, but it fails if KeepassXC is already running:

```
$ keepassxc --version
desktop-file-validate is missing. Skipping /tmp/.mount_keepas2xaITR/usr/bin//keepassxc_env.wrapper.
Another instance of KeePassXC is already running.
```

**Comment by cdancette** [comment]
@anlutro You can use `keepassxc-cli --version`` instead of `keepassxc --version`, which is the command designed to be used as a cli (I think `keepassxc` is only designed to run the GUI)

**Comment by anlutro** [comment]
I don't have `keepassxc-cli` as I'm using the appimage.

**Comment by cdancette** [comment]
Ok my bad. I'm not sure about how appimages work, but it seems you can try `keepassxc cli --version` and it will run the `keepassxc-cli` command (see https://github.com/keepassxreboot/keepassxc/blob/develop/AppImage-Recipe.sh#L90)

**Comment by cdancette** [comment]
I just tried the appimage on my system (ubuntu 18.04) and `keepassxc cli --version` works. 

Also `keepassxc --version` doesn't raise the error you have (but it does focus on the GUI)

**Comment by anlutro** [comment]
`keepassxc cli --version` does indeed work. I still think `--version` should work without the `cli` part though, but if for some reason that's difficult to implement feel free to close the issue.

I also can't explain why you wouldn't get the "Another instance of KeePassXC is already running." message.

**Comment by TheZ3ro** [comment]
pretty easy task, if someone wants to hop-in
