### ISSUE TITLE
Suggestion: Improve UI on generating new passwords

### ISSUE THREAD

**Issue by TeemuKoivisto** [keepassxreboot/keepassxc#1363]
# Problem

Often times it has happened to me when I have generated a new password I have absent-mindedly clicked 'Ok' without first clicking 'Accept' for the new password. (Granted I have been using KeePassX but it seems that the functionality is the same in KeePassXC)

This has caused me to require password resets for accounts to which I have changed passwords but forgot to click accept. Most annoyingly for some accounts I have had ask my superior to reset it for me.

# Solution

Turn password generation into its own modal. This way user has to either accept the generated password or dismiss the modal without accepting. Either way they can't just click 'Ok' and lose their generated password.

Or maybe disable 'Ok' button when the password generation is open. That would then also require a cancel/reject button for the password generation. So maybe it would better to replace the 'Cancel' and 'Ok' buttons with the password generation buttons so it's obvious that the newly generated password has to be either accepted or rejected.

But these are just my suggestions and anything that would fix the issue of being able to click 'Ok' without actually saving the password changes would be much appreciated. Before somebody tells me that this is not an issue and that I should just 'learn how to use it' well I had this problem when I first started using it and still, after 6 months, I do the same mistake again so I think it's an issue and not just my own stupidity.

**Comment by sts10** [comment]
While we're discussing this, I'd like to cautiously throw out a related issue I've been thinking about.

When I'm changing a password, I often need access to _both_ the old and new passwords at the same time. For example, a form asks for your old password, and then your new password twice. Theoretically, I can paste my old password into the first text box, then generate a new password, apply it, and then paste that into the two other text boxes. But! Sometimes this form will reject my new password for whatever reason (too short, too long, wrong character mix, etc.) I'm taken back to a cleared form and now my old password is no longer available. 

Now, yes, I can go into History and then, with the latest entry highlighted, hit the "Show" or "Restore" buttons to recover my old password. But I find this to be a bit of a stressful procedure, especially for a new user. As a workaround, I usually paste my old password into the "Notes" text field, then generate a new password. 

I'm not sure what a slick solution to this workflow would be, and I certainly wouldn't want to add clutter to the UI. And if no one else has this pain point feel free to dismiss this. But I thought I'd raise it in case somebody has an idea for solving both of these issues in one go.

**Comment by hifi** [comment]
I've also noticed that I have done this more than once. Preventing the user from accidentally discarding a generated password would be nice.

**Comment by TheZ3ro** [comment]
I will try to make a patch for this in the upcoming 2.3.0 version

**Comment by droidmonkey** [comment]
Merged in 2.3.0
