### ISSUE TITLE
Segmentation fault on start

### ISSUE THREAD

**Issue by erikheinz** [keepassxreboot/keepassxc#1364]
## Expected Behavior
normal program start

## Current Behavior
Segmentation fault, no error message
same with `keepassxc-cli`
`keepassxc --help` works without segfault
`keepassxc-cli  --help` does not work

## Steps to Reproduce (for bugs)
Simply start `keepassxc`. Probably reproducible on my system only.

## Debug Info
KeePassXC - 2.2.4 (current checkout from GIT)

Libraries:
qt-5.10.0
libgcrypt-1.6.4
libstdc++ from gcc-6.4.0
glibc-2.24
... lots of others (see strace output)

Operating system: Linux
CPU architecture: x86_64
Kernel: 4.9.74

Enabled extensions:
none

## Additional info
My system is a homegrown Linux based on Gnome 3 and a reasonably current Xorg. Most (but not all) libraries are more or less up-to-date. 
The segfault happens with the current git version of keepassxc as well as with the 2.2.4 release or the 2.1 git version of keepassx. Older keepassx releases work, but only with Qt4.  Since nobody except me seems to have this problem, it probably is triggered by some  peculiarity of my installation. Nevertheless there should be no segfault. I don't have this problem with other applications, but don't use Qt so much either.

What can I do to realistically do to track down the problem? strace output is attached.

Thank you in advance.
Erik

[strace.txt](https://github.com/keepassxreboot/keepassxc/files/1612109/strace.txt)

**Comment by droidmonkey** [comment]
You probably have a qt issue

**Comment by erikheinz** [comment]
FeatherPad runs fine, as well as some other Qt applications.
Might still be a Qt issue, though. I will try to find out where exactly the segfault happens. This will take some time.

**Comment by erikheinz** [comment]
So this becomes really strange. 

In the first instance, I could locate a segfault somewhere inside Crypto::init() and the kernel blamed libgcrypt for this. So I updated libgcrypt. Result: still segfault.
But now the segfault happens in MainWindow.cpp, MainWindow::MainWindow() when m_ui->setupUi(this) is called. So probably somewhere deep inside Qt. 
I don't think, howewer, that this is a Qt issue. I did a complete rollback to Qt-5.9.3 and the problem was still there.
Next try: the kernel says, the segfault happens inside libX11. I updated libX11. Still the same.
I updated EVERY single shared library that keepassxc is linked with to the most current version. Still the same.

Now I am at a loss. Any suggestions?

**Comment by phoerious** [comment]
Can you try our AppImage? That one ships its own libraries and we can rule out a few causes.

**Comment by erikheinz** [comment]
The AppImage works. No problem at all. So at least I cann access my database.
Thank you

**Comment by phoerious** [comment]
So it's most likely a library issue then

**Comment by erikheinz** [comment]
Finally, some success. Using catchsegv, I found the segfault happens when loading the plugin 
libkeepassx-autotype-xcb.so. So I tried -DWITH_XC_AUTOTYPE=OFF. Voilà - segfault is gone.

Backtrace:
/usr/X11R7/lib64/libX11.so.6(XInternAtom+0x1a)[0x7f76a6af48f0]
/usr/qt/lib64/keepassxc/libkeepassx-autotype-xcb.so(+0x518c)[0x7f768f5f818c]
/usr/qt/lib64/keepassxc/libkeepassx-autotype-xcb.so(qt_plugin_instance+0x91)[0x7f768f5f8ff9]
/usr/qt/lib64/libQt5Core.so.5(_ZN13QPluginLoader8instanceEv+0x5b)[0x7f76ab0de797]
keepassxc(+0xaf855)[0x55a02a835855]
keepassxc(+0xafaa1)[0x55a02a835aa1]
keepassxc(+0xafb34)[0x55a02a835b34]
keepassxc(+0x801b4)[0x55a02a8061b4]
keepassxc(+0x4aac6)[0x55a02a7d0ac6]
keepassxc(+0x4751c)[0x55a02a7cd51c]
keepassxc(+0x3ec20)[0x55a02a7c4c20]
/lib64/libc.so.6(__libc_start_main+0xf0)[0x7f76aa57b560]
keepassxc(_start+0x2a)[0x55a02a7c680a]

**Comment by droidmonkey** [comment]
What version of X11 do you have installed?

**Comment by erikheinz** [comment]
My pathnames have some local flavor :-). As long as it is consistent, this should be no problem.
The X11 is a vanilla Xorg from ftp.freedesktop.org. The X server is at version 1.19.3. Most client libraries are up to date.
