### ISSUE TITLE
KeepassXC - high cpu usage on linux

### ISSUE THREAD

**Issue by sa1** [keepassxreboot/keepassxc#1365]
https://github.com/keepassxreboot/keepassxc/blob/6476b6b1f07a8ed9d594aad07d746526f6b80384/src/browser/NativeMessagingBase.cpp#L75

Polling for messages on stdin seems to take up high cpu on linux.

Attaching strace to keepassxc shows this cycle of syscalls on repeat:

```
epoll_create(5)                       = 33
epoll_ctl(33, EPOLL_CTL_ADD, 0, {EPOLLIN, {u32=0, u64=94794223190016}}) = 0
epoll_pwait(33, [{EPOLLHUP, {u32=0, u64=94794223190016}}], 1, 5000, NULL, 8) = 1
close(33)                               = 0
poll([{fd=0, events=POLLIN}, {fd=6, events=POLLIN}, {fd=7, events=POLLIN}, {fd=11, events=POLLIN}, {fd=13, events=POLLIN}, {fd=22, events=POLLIN}, {fd=23, events=POLLIN}, {fd=31, events=POLLIN}], 8, 0) = 1 ([{fd=0, revents=POLLHUP}])
```

Haven't ruled out other causes of CPU usage, but I didn't see it before I enabled native messaging, and this seems to be the most likely cause.

**Comment by varjolintu** [comment]
I'll investigate the issue. Does this happen when just starting KeePassXC or did you do something specific?

**Comment by sa1** [comment]
It happens right after starting. I didn't do anything specific, and seemed
to happen even with the Firefox extension not running (i.e there shouldn't
be messages on stdin).
