### ISSUE TITLE
new feature: copy password and user name button for each entry

### ISSUE THREAD

**Issue by wojtekbogusz** [keepassxreboot/keepassxc#1369]
it would be really helpful to have two buttons to copy password and another button to copy username on the end of the line of each item in keepassxc database. say even a small buttons [P] and [U] would help. this would decrease number of clicks needed to copy password or user name to the clipboard. once you click on the button specific password or username would be copied to the clipboard.
you could allow people to switch this option (having the buttons visible) on/off in settings.

**Comment by weslly** [comment]
There are already buttons in the toolbar for this. 

![image](https://user-images.githubusercontent.com/107672/34770249-94f5b2ec-f5e7-11e7-9abb-be00864211ee.png)

**Comment by droidmonkey** [comment]
Or simply press CTRL+C to copy password of selected entry and CTRL+B to copy username.

**Comment by droidmonkey** [comment]
Or simply press CTRL+C to copy password of selected entry and CTRL+B to copy username.

**Comment by wojtekbogusz** [comment]
thanks. i am asking about something different.. in order to use the buttons you mention weslly one needs to click on the item and then click on the button - which is two clicks with moging the mouse between them. i am proposing to have button/link for each entry/item in the database list. or alternatively to do like it was in keepassx 0.4, when you could have a password column and double clicking on the specific password field ('*****') copy it's content to the clipboard and double clicking on specific username copy this username to the clipboard. this (for me) significantly improves way of working with the program. also clicking on the item with the mouse and then pressing ctrl-c is less ergonomic for me then double clicking or clicking the button/link in the item row..

**Comment by weslly** [comment]
>alternatively to do like it was in keepassx 0.4, when you could have a password column and double clicking on the specific password field ('*****') copy it's content to the clipboard and double clicking on specific username copy this username to the clipboard

@wojtekbogusz there's a PR for this: https://github.com/keepassxreboot/keepassxc/pull/1305

**Comment by phoerious** [comment]
For usernames and passwords that is already working.

**Comment by wojtekbogusz** [comment]
@weslly thank you this is great.
@phoerious which version you mean? in my 2.2.4 it does not work.
