### ISSUE TITLE
Fix tests cases under Windows and OSX

### ISSUE THREAD

**Issue by droidmonkey** [keepassxreboot/keepassxc#137]
GUI tests fail when run under windows and OSX.

## Expected Behavior

All tests pass.

## Current Behavior

The following GUI tests fail on Windows and OSX:
```
TestGui::testAutoreloadDatabase
Compared values are not the same
   Actual   (m_db->rootGroup()->findChildByName("General")->entries().size()): 0
   Expected (1)                                                              : 1
```
The following GUI tests fail on Windows:

```
TestGui::testSave
Compared values are not the same
   Actual   (m_tabWidget->tabText(m_tabWidget->currentIndex())): "Save*"
   Expected (QString("Save"))                                  : "Save"

TestGui::testDatabaseSettings
Compared values are not the same
   Actual   (((m_tabWidget->tabText(m_tabWidget->currentIndex())))): "testgui.q12980*"
   Expected (QString("Save*"))                                     : "Save*"
```

**Comment by dannysu** [comment]
I sync'ed my fork with upstream, re-built and re-ran `make test` on Windows and experienced one failure. But not the same as what's fixed with #138.

This time the error is in `testDeleteEntry`:
```
FAIL!  : TestGui::testDeleteEntry() Compared values are not the same
   Actual   (groupView->currentGroup()->name())     : "NewDatabase"
   Expected (m_db->metadata()->recycleBin()->name()): "Recycle Bin"
C:/Users/Danny/keepassxc/tests/gui/TestGui.cpp(519) : failure location
```

I re-ran `testgui` several more times and the failure seems to be intermittent. Sometimes everything passes, sometimes `testDeleteEntry` fails. Maybe the arbitrary waits are messing things up.

**Comment by droidmonkey** [comment]
Sometimes GUI tests can fail if you are not focused on the window while the tests run.... or if you cause the focus to change in the middle of the test for some reason. I have never personally witnessed this failure.

**Comment by phoerious** [comment]
Do you consider this grave enough that it needs fixing for 2.1.0 or can this also go into 2.2.0?

I also have on GUI test failing for me all the time on Arch.

```
FAIL!  : TestGui::testDeleteEntry() Compared values are not the same
   Actual   (groupView->currentGroup()->name())     : "NewDatabase"
   Expected (m_db->metadata()->recycleBin()->name()): "Recycle Bin"
   Loc: [/home/janek/keepassxc/tests/gui/TestGui.cpp(519)]
QDEBUG : TestGui::testDeleteEntry() XmbTextListToTextProperty result code -2
```

**Comment by droidmonkey** [comment]
I think the gui tests as a whole need to be looked at again in 2.2.0. As long as travis works I am OK for 2.1.0

**Comment by phoerious** [comment]
Alright, postponing to 2.2.0 then.

**Comment by droidmonkey** [comment]
@phoerious is the failing TestGui::testDeleteEntry() still a problem on Arch? I do not get this failure on Windows.

**Comment by phoerious** [comment]
Not anymore, no. I'm not sure why it works now, but I strongly believe that it was somehow a race condition between creating the recycle bin and checking in the GUI if it's there. What I don't know is why I could reproduce it reliably in all runs. I also think to recall that I was able to work around it by adding a QtApplication::processEvents() call in between. But now it seems to work as is.

**Comment by droidmonkey** [comment]
Yah i remember that. Closing this issue then.
