### ISSUE TITLE
Symbolic links not visiable.

### ISSUE THREAD

**Issue by bjwest** [keepassxreboot/keepassxc#1371]
Symbolically linked files or directories are not shown in the KeePassXC file manager.

## Expected Behavior
When trying to open or create a database, the file manager should show and allow navigating to or selecting symbolically linked files and directories.

## Current Behavior
When trying to open an existing file or create a new one, symbolic links are not shown in the file manager.

## Possible Solution
Fix the file manager code to recognize symbolic links.

## Steps to Reproduce (for bugs)
1. Start KeePassXC.
2. Select any option that opens the file manager.
3. Notice that there are no symbolically linked files or directories listed in the file manager.

## Context
My Documents directory is stored on a separate hard drive and linked to my home directory.  With my password file stored in a directory under Documents, I cannot open it in KeePassXC.

Upon second run, the following was displayed in the terminal:

/home/johnny/Documents was removed, reassigning DOCUMENTS to homedir
/home/johnny/Videos was removed, reassigning VIDEOS to homedir

Both Documents and Videos are symbolically linked directories.  I have several others but KeePassXC seemed to ignore them altogether.

While I try KeePassXC, I'll move my passwords file to a non sym-linked location, but this is not an acceptable solution for the long run.  I shouldn't have to modify my system layout, and doing so breaks or degrades other aspects of my system.

## Debug Info
KeePassXC - 2.2.4
Revision: 4723f66

Libraries:
- Qt 5.7.1
- libgcrypt 1.7.6-beta

Operating system: OS
Operating system: Ubuntu Core 16
CPU architecture: x86_64
Kernel: linux 4.13.0-25-generic

Enabled extensions:
- KeePassHTTP
- Auto-Type
- YubiKey

**Comment by bjwest** [comment]
OK, this seems to be a SNAP issue.  I'm kind of new to SNAP and is seems SNAP apps can't see symbolic links outside of their SNAP 'home', but can see normal files and directories?  I just compiled the latest source and all is working fine now.

**Comment by phoerious** [comment]
We have an FAQ entry about that issue.

**Comment by Stef-33560** [comment]
Hi

> We have an FAQ entry about that issue.
Mmhhh. Where ? 

Thanks
