### ISSUE TITLE
Lock file made before database even opened

### ISSUE THREAD

**Issue by tremby** [keepassxreboot/keepassxc#1372]
Why is a lock file made before the database is even opened? I see no lock file before starting keepassxc, and then immediately after starting in, before the database has been opened, I see a lock file.

It'd be better in my eyes if the program was in a read-only state (with no lock) until I actually want to edit/add/save something, but at least not locking the database before it's even open would be a good start.

----

KeePassXC - Version 2.2.2
Revision: 6d46717

Libraries:
- Qt 5.5.1
- libgcrypt 1.6.5

Operating system: Ubuntu 16.04.3 LTS
CPU architecture: x86_64
Kernel: linux 4.4.0-103-generic

Enabled extensions:
- KeePassHTTP
- Auto-Type
- YubiKey

**Comment by phoerious** [comment]
The lock file has been removed for 2.3.0. See #1231
