### ISSUE TITLE
Feature request: option for custom password generator commands

### ISSUE THREAD

**Issue by hi2u** [keepassxreboot/keepassxc#1373]
I have a command line script that I use to generate random passwords using a passphrase format that I like.  For example, let's call this CLI script `/usr/local/bin/mygeneratorscript`

Currently, when creating a new KeePassXC entry: I manually run the command in a terminal, then copy and paste one of the generated passwords from my custom script into my new KeePassXC entry.

It would be awesome if KeePassXC had an option in the settings labelled something like "Custom password generator command", with a text field that I would enter `/usr/local/bin/mygeneratorscript` into.

Assuming the user has entered a custom password command into the options... when generating a new KeePassXC entry and using the password generator, (in addition to the existing "Password" and "Passphrase" tabs), a new tab would appear labelled "Custom command" (or similar).  

Clicking the "Generate" button on this tab would execute my command line script and insert the script's stdout output into the "Password" field (same behaviour as the internal generators).

As you can already do currently on the Password/Passphrase tabs - the user can keep clicking generate if they don't like generated password and want to generate new ones.

I see that there are currently a number of issues requesting new features be added to KeePassXC's internal Password/Passphrase generators... a custom script option would likely keep most people happy, as they'd be able to use any format they like without having to ask the devs to add new format options to KeePassXC itself.

**Comment by droidmonkey** [comment]
This is an interesting idea, but a super specific use case. What about the current password/phrase generator doesn't work for you?

**Comment by TheZ3ro** [comment]
I think that this is a little out of scope. Also I don't really like the idea of executing external commands and parsing theirs input.

The KeePassXC password generator is developed to generate secure random password, you can't really trust enough external programs on that.

**Comment by hi2u** [comment]
@droidmonkey Stuff like using upper/lowercase letters, numbers, punctuation in passphrases etc (along with words).  Also putting those things in specific places, rather than randomly.  Basically my current generator script generates passwords which keep most password complexity requirements happy on all sites.  And the additional complexity over words-only passphrases makes them a bit more secure too.

@TheZ3ro It is a bit of a niche feature.  But most users using it would understand the risks I think.  I understand when programmers want to prevent less-tech-savvy users from making security mistakes. 
 But I think the target audience here wouldn't need their hands held as much.

**Comment by phoerious** [comment]
> Stuff like using upper/lowercase letters, numbers, punctuation in passphrases etc (along with words).

You mean like adding the bloody required special character to your long and already secure diceware password? I do that by just inserting one by hand.

**Comment by droidmonkey** [comment]
Sounds like you are creating passwords for government sites /s (although maybe true)

**Comment by droidmonkey** [comment]
This will not be implemented.
