### ISSUE TITLE
Chromebook support

### ISSUE THREAD

**Issue by noorbertt** [keepassxreboot/keepassxc#1382]
I got a Chromebook and I looking for a password manager. There is any plan for Chromebook OS support in the near future?

**Comment by weslly** [comment]
>There is any plan for Chromebook OS support in the near future?

No

AFAIK Chrome OS is based on Linux but everything is heavily sandboxed and locked down, so the closest you could have is either a [Keepass compatible android app](https://gastarbeiten.wordpress.com/2017/01/26/using-keepass-under-chromeos-readwrite-with-android-app-keepassdroid/) or [KeeWeb](https://keeweb.info/).
