### ISSUE TITLE
Ampersand in database name not sanitized for tab

### ISSUE THREAD

**Issue by M-Pixel** [keepassxreboot/keepassxc#1389]
## Expected Behavior
When I enter "This & That" as the **name** of a database, and have multiple databases open, "This & That" will appear in the database's tab.

## Current Behavior
When I enter "This & That" as the **name** of a database, and have multiple databases open "This _That" will appear in the database's tab.

When I enter "This && That" (wild guess) as the **name** of a database, and have multiple databases open, "This & That" appears in the database's tab, but "T&his && That" appears in the window title, and other databases' window titles also start showing a "&" prefix.

## Debug Info
KeePassXC - Version 2.2.4
Revision: 4723f66

Libraries:
- Qt 5.6.2
- libgcrypt 1.6.1

Operating system: openSUSE Leap 42.3
CPU architecture: x86_64
Kernel: linux 4.4.107-2.g30f32ac-default

Enabled extensions:
- KeePassHTTP
- Auto-Type
- YubiKey

Installed via Zypper

**Comment by phoerious** [comment]
There is also a whole other level of problems with ampersands and multiple tabs here, because KDE tends to insert some on its own which are then read back and put in the window title. We need to refractor the complete database tab handling, but that won't happen before 2.4.
