### ISSUE TITLE
Support/document compatible alternatives to YubiKey

### ISSUE THREAD

**Issue by rugk** [keepassxreboot/keepassxc#1391]
E.g. there is the open-software/hardware Nitrokey, which also supports HOTP passwords (that is, HMAC-SHA1 as you state in your FAQ).

Don't know whether the application needs to be adjusted for that, or it can also be used interchangeably.

See https://www.nitrokey.com/documentation/applications#a:web-login-with-one-time-passwords-otp,-2fa

**Comment by droidmonkey** [comment]
This was discussed in #255
