### ISSUE TITLE
DB not editable by linux after opened with mac

### ISSUE THREAD

**Issue by baboco** [keepassxreboot/keepassxc#1395]
I'm sharing a newly created DB over a common file server (sharing with AFP).
One client is a Linux system the other is a Mac.
I first noticed this issue with KPXC 2.2.2 on mac.

## Expected Behavior
After closing the DB on the mac client, the linux client should be able to edit it.

## Current Behavior
After opening and closing the DB on the mac-client, the DB only opens in _read only_ mode on the linux client (all data can be read but non changed/added without creating a new DB-file)

### Scenario 1
1. Create a new DB on the linux client with a passphrase.
2. (Add an entry and) save it in a shared location.
3. Close the DB on the linux client
4. Open the DB on the mac client
5. (Add an entry and) save it.
6. Close The DB on the mac client
7. Open the DB on the linux client

### Screnario 2
1. Create a new DB on the mac client (with a passphrase).
2. (Add an entry and) save it in a shared location.
3. Close the DB on the mac client
4. Open the DB on the linux client

## Context
* I confirmed (`$ls -lah`) that there was no lock file present after closing the DB on both clients.
* I used this in a testing environment - no one else interfered, no data is lost.
* It is possible to add a new entry on the mac client (and view it on the linux client)

### Linux Client
KeePassXC - Version 2.2.4
Revision: 4723f66

Libraries:
- Qt 5.5.1
- libgcrypt 1.6.5

Operating system: Ubuntu 16.04.3 LTS
CPU architecture: x86_64
Kernel: linux 4.10.0-42-generic

Enabled extensions:
- KeePassHTTP
- Auto-Type
- YubiKey

### Mac Client
KeePassXC - Version 2.2.4
Revision: 4723f66

Bibliotheken:
- Qt 5.9.1
- libgcrypt 1.8.1

Betriebssystem: macOS High Sierra (10.13)
CPU-Architektur: x86_64
Kernel: darwin 17.3.0

Aktivierte Erweiterungen:
- KeePassHTTP
- Auto-Type
- YubiKey

**Comment by phoerious** [comment]
With editing you mean, you can open it, but it's marked as read-only? Or do mean you can't open it at all?

**Comment by baboco** [comment]
@phoerious yes, I clarified the text above.

**Comment by phoerious** [comment]
Can you verify that the hash sum of the database stays the same before and after opening it on macOS (use shasum)?
Also does the Linux client have write access to the shared folder, i.e. can it create new files there?

**Comment by baboco** [comment]
@phoerious 
I did the following:
1. Created a DB with the linux client and saved it to the shared folder
2. `$ shasum Passwords.kdbx 
2ba9819d2c8c9806541ac2e1989ae0bbe84b4d48  Passwords.kdbx`
3. closed the DB on the linux client
4. opend the DB on the mac client
5. closed the DB on the mac (without saving)
6. `$ shasum Passwords.kdbx 
2ba9819d2c8c9806541ac2e1989ae0bbe84b4d48  Passwords.kdbx` (note that it's the same)'
7. opened it on the linux client -> error persists

**Comment by baboco** [comment]
Forget about the mac thing.
I just did the same as above without steps 4. to 6. and the error occured again.

Thanks for your time - this seems to be an other problem
