### ISSUE TITLE
Menu bar not available after reopening window

### ISSUE THREAD

**Issue by simon5738** [keepassxreboot/keepassxc#1400]
The menu bar does not appear after closing to tray and reopening the window via the launcher. When using the tray icon the menubar appears.

## Expected Behavior
I expected the menu bar (Database, Entries, Groups, View, Tools, Help) to be available.

## Steps to Reproduce (for bugs)

1. Open Program. 
2. Enable setting:  Show a system tray icon - Hide window to system tray instead of app exit.
3. "Close" app to tray.
4. Reopen via launcher.

## Debug Info
KeePassXC - Version 2.2.4
Revision: 4723f66
Distribution: Snap

Libraries:
- Qt 5.7.1
- libgcrypt 1.7.6-beta

Operating system: Ubuntu Core 16
CPU architecture: x86_64
Kernel: linux 4.13.0-26-generic

Enabled extensions:
- KeePassHTTP
- Auto-Type
- YubiKey

**Comment by phoerious** [comment]
It's a Unity bug We are shipping a fix for it already, I wonder why it doesn't work for you. Can you try the AppImage instead, please?

**Comment by simon5738** [comment]
That seems to solve the problem. Thanks! Do you need/want to look further into this?

**Comment by phoerious** [comment]
I don't think its worth the time wasting too much time on it. I know the reason for it and we ship a fix. I'm not too eager to put effort into finding out why its not being applied under certain circumstances. Especially not since Unity is pretty dead anyway.
