### ISSUE TITLE
Could NOT find Argon2 (missing: ARGON2_LIBRARIES ARGON2_INCLUDE_DIR)

### ISSUE THREAD

**Issue by lbkvu** [keepassxreboot/keepassxc#1401]
When build from latest source, doing cmake fails and display the error

## Expected Behavior

Should be built successfully

## Current Behavior

Error: Could NOT find Argon2 (missing: ARGON2_LIBRARIES ARGON2_INCLUDE_DIR)

## Steps to Reproduce (for bugs)

1. Get the latest source
2. Clear everything in **build** directory, then run
`cmake -DCMAKE_OSX_ARCHITECTURES=x86_64 -DCMAKE_BUILD_TYPE=Release -DWITH_XC_AUTOTYPE=ON -DWITH_XC_HTTP=ON -DCMAKE_PREFIX_PATH=/usr/local/Cellar/qt5/5.10.0/lib/cmake ..`
3. Error:
```
-- Using macdeployqt: /usr/local/opt/qt5/bin/macdeployqt
CMake Error at /usr/local/Cellar/cmake/3.10.1/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find Argon2 (missing: ARGON2_LIBRARIES ARGON2_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.10.1/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindArgon2.cmake:34 (find_package_handle_standard_args)
  CMakeLists.txt:265 (find_package)


-- Configuring incomplete, errors occurred!
```

## Debug Info

Qt version: 5.10.0

**Comment by arichiardi** [comment]
Can confirm this is an issue on `master` on Ubuntu `16.04`. The library in included in newer Ubuntus.

**Comment by lbkvu** [comment]
I'm building on Mac OS. How can I install this library in Mac?

**Comment by arichiardi** [comment]
I compiled it from here: https://github.com/P-H-C/phc-winner-argon2

**Comment by lbkvu** [comment]
Problem solved after installing Argon2 library.

**Comment by TheZ3ro** [comment]
@arichiardi on `master`? Or you mean `develop` ?

**Comment by arichiardi** [comment]
Sorry yeah :smile:
