### ISSUE TITLE
Unlock KPXC databases on login

### ISSUE THREAD

**Issue by david-libremone** [keepassxreboot/keepassxc#1405]
**User story:** I have configured my GNU/Linux desktop to unlock my system keyring on login. I want to open KPXC files without being prompted for a passphrase, so I don't have to worry about passphrases unnecessarily.

This is a specific scenario to be tested after implementing #1404 

## Expected Behavior

**Manually opening a file**
* Configure desktop to unlock system keyring on login
* Store unlock passphrase in system keyring (see #1404)
* Log in (keyring unlocked)
* Double-click passphrase-protected KPXC file
* KPXC file opens

**Programmatic access**
* Configure desktop to unlock system keyring on login
* Store unlock passphrase in system keyring (see #1404)
* Log in (keyring unlocked)
* Start KPXC plugin (for example, browser integration)
* KPXC data immediately accessible via plugin (no passphrase required)

**Comment by Generator** [comment]
That can be done with pw-stdin. 
Example of database password stored on libsecret
`secret-tool lookup name keepass | keepassxc --pw-stdin --keyfile /path/to/keyfile /path/to/database.kdbx`
No passphrase or keyfile prompted.

**Comment by sojusnik** [comment]
@Generator A step-by-step approach is described [here](https://github.com/keepassxreboot/keepassxc/issues/1267).

**Comment by droidmonkey** [comment]
As mentioned this is already possible using existing features.

**Comment by gozzilli** [comment]
If it's useful this seems to work for me on macos:
```security find-generic-password -s pw-keepassxc -w | /Applications/KeePassXC.app/Contents/MacOS/KeePassXC --pw-stdin /Users/davide/Personal/SynologyDrive/DZHome2.kdbx```
after having added a new password called `pw-keepassxc` to the `login` Keychain.
