### ISSUE TITLE
Argon2 library not found when building from source

### ISSUE THREAD

**Issue by nick96** [keepassxreboot/keepassxc#1409]
## Current Behavior

When I try to build keepassxc from the development branch, I get the following error:
```
CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find Argon2 (missing: ARGON2_LIBRARIES ARGON2_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindArgon2.cmake:34 (find_package_handle_standard_args)
  CMakeLists.txt:272 (find_package)
```

## Steps to Reproduce (for bugs)

1. git pull https://github.com/keepassxreboot/keepassxc
2. cd keepassxc
3. mkdir build
4. cd build
5. cmake -DWITH_TESTS=OFF ..

## Debug Info
Operating system: Fedora
CPU architecture: x86_64
Kernel: 4.14.13

Enabled extensions:
None

**Comment by phoerious** [comment]
libargon2 has been made a requirement with the merge of KDBX4. See our updated set-up instructions in the wiki: https://github.com/keepassxreboot/keepassxc/wiki/Set-up-Build-Environment-on-Linux
