### ISSUE TITLE
KeePassXC-cli add command

### ISSUE THREAD

**Issue by kskewes** [keepassxreboot/keepassxc#1418]
## Current Behavior ##
Accessing database remotely via SSH works great for retrieving passwords. 
keepassxc-cli seems stable and reliable. 

## Desired Behavior ##
I would also like to add new entries to an existing database. 
This is mentioned in #681 
" add entry manipulation commands (add, rm, edit, etc)"
Did I miss relevant follow up commentary?

## Expected Behavior ##
For example:
1) Define some attributes on command line:
```
:~$ keepassxc-cli add <database> <groupname> <entryname> <username> <url>
Insert password to unlock <database>
Successful
Insert password to add to <entryname> (if required)
...
Confirm password to add to <entryname> (if required)
<groupname> <entryname> added. 
```

2) Alternative interactive flow:
```
:~$ keepassxc-cli add <database> interactive
Insert password to unlock <database>
Successful
Insert Title (if required)
...
Insert username (if required)
...
Insert password (if required)
...
...
```
3) Stretch ability to go back a level to make a correction would be neat (or an edit ability). 
eg:
```:~$ keepassxc-cli add <database> interactive
Insert password to unlock <database>
Successful
Insert Title (if required)
<example title>
Insert username (if required, type ** to go up a level)
**
Insert Title (if required)
<corrected example title>
Insert username (if required, type ** to go up a level)
...
```
4) Edit ability. 
The logic in 3 above could form basis of an interactive edit entry feature. 

## KeepPass has existing support ##
See details here: https://keepass.info/help/v2_dev/scr_sc_index.html#addentry
However I think it's more secure to require the password separately at this stage, this sentiment seems shared in other issues. 
Declaring all of the variables on command line may be a stretch. 

## Debug Info ##
`$ keepassxc-cli -v
2.2.4`
Debian sid

**Comment by TheZ3ro** [comment]
This is already supported in `develop` branch (merged with #919), will be integrated in version 2.3.0
