### ISSUE TITLE
Auto-Type types password in username field

### ISSUE THREAD

**Issue by Wurzelmann** [keepassxreboot/keepassxc#1426]
## Expected Behavior

When using auto-type it should "type" my username in the username box and my password in the password box.

## Current Behavior

On some websites (e.g. a Kallithea instance) keepassxc types my password in the username box and ignores the password box. The same entry works with keepass2 and mono, just keepassxc doesn't get it right.

## Steps to Reproduce (for bugs)

1. open my firm's Kallithea instance
2. look for the corresponding login saved in keepassxc
3. perform auto-type via context menu from keepassxc
4. keepassxc submits my password into the username box

## Context

I tried to show my colleague keepassxc and it revealed my password to him, not cool... :-)

## Debug Info

KeePassXC - Version 2.2.4
Revision: 4723f66

Libraries:
- Qt 5.10.0
- libgcrypt 1.8.2

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 4.14.15-1-ARCH

Enabled extensions:
- KeePassHTTP
- Auto-Type
- YubiKey

**Comment by phoerious** [comment]
KeePassXC doesn't know anything about username and password fields. All it does is type the username where ever the focus is, type a tab character and then the password + Enter. My assumption is that you had focused something else, so it typed the username on something that's not an input field and then tabbed to the username field.
Also without more information about the affected website, we cannot help.

**Comment by Wurzelmann** [comment]
Thanks for the answer and information, but when using autotype from the KeePassXC window, it is impossible to have the desired login form in focus, because it is on KeePassXC or did I misunderstand you?

For clarification: I'm not talking about the global autotype hotkey, but the built-in autotype option in KeePassXC itself (see attached screenshot).

![screenshot_2018-01-25_12-33-54_autotype_cropped](https://user-images.githubusercontent.com/12230892/35386406-39b4418c-01cc-11e8-8d63-3f63bd3d923c.png)

**Comment by phoerious** [comment]
Same thing for both. Auto-Type types into whatever field had the focus before KeePassXC.

**Comment by Wurzelmann** [comment]
I see. I tested this again and you're right. The focus on my previous tests had been on the browser window itself, but not on the username field. Now it works perfectly. Thank you very much, I misunderstood autotype's function and that was the main problem here.

Closed.

**Comment by phoerious** [comment]
With great power comes great responsibility. :wink:

Auto-Type can be dangerous if you are not careful.

**Comment by Wurzelmann** [comment]
I wonder if this behaviour is a sane default though...

**Comment by phoerious** [comment]
It's the only way Auto-Type can be implemented.

**Comment by Wurzelmann** [comment]
Okay, thanks for letting me know. :-)
