### ISSUE TITLE
Pre-release or screenshots of 2.3 for translations

### ISSUE THREAD

**Issue by Nikcco** [keepassxreboot/keepassxc#1427]
Hi good people! :)

I read on the blog that you were looking for translators for the upcoming 2.3 release, but I can't find any pre-release of KeePassXC 2.3. Translating without knowing the context of the text-strings will often lead to mediocre or bad translations. Please provide either a pre-release or screenshots.

**Comment by phoerious** [comment]
We will release a beta soon. Until then you need to translate to your bet knowledge (or guess) or build a custom version yourself. After the beta has been released, there will be enough time to fix inaccurate translations.

**Comment by Nikcco** [comment]
Would it be very complicated for a non-programmer to build a custom a custom version of 2.3? If not, could you either please tell me how or maybe there is some instructions available somewhere that you can point me to? Thanks!

**Comment by phoerious** [comment]
It's not very complicated at least not on most Linux systems, but ymmw.
We have a guide in our wiki: https://github.com/keepassxreboot/keepassxc/wiki/Set-up-Build-Environment-on-Linux (for other platforms look in the sidebar).

**Comment by Nikcco** [comment]
Thank you, I will check it out.
