### ISSUE TITLE
Always have to type in Master password? 

### ISSUE THREAD

**Issue by Zack9f6** [keepassxreboot/keepassxc#1429]
I am using KeepassXC on Ubuntu 16.04

Everytime I reboot I have to launch keepassxc and I am always prompted to type my master password.  

Is this normal?  I dont want to have to type my password each and every day (This is my home Desktop) 

And is this option available on KeePass (the one with Mono) ?

**Comment by TheZ3ro** [comment]
Yes, it's normal. That's how it's supposed to work
