### ISSUE TITLE
Print for backups

### ISSUE THREAD

**Issue by SVilgelm** [keepassxreboot/keepassxc#1434]
It would be great to be able to print one or several items for backup purposes.

An users should be able to select one or many items and print those items, including additional attributes.

**Comment by TheZ3ro** [comment]
Already discussed in #876 

You can export your DB as CSV and print it without KeePassXC support

**Comment by SVilgelm** [comment]
@TheZ3ro exported csv doesn't contain additional attributes

**Comment by TheZ3ro** [comment]
@SVilgelm I forgot that, you are right. We should add a feature to export additional attributes to csv export then

**Comment by micressor** [comment]
I understand the argument (CSV export is available). But a direct printout would prevent users from having to export their password database to the (possibly) non-encrypted hard disk.

From this point of view, I see a real benefit in making paper backups.

**Comment by droidmonkey** [comment]
Printing guarantees you are exporting the non-encrypted data to the notoriously bad print driver and spool.

**Comment by wolframroesler** [comment]
Printing the CSV file isn't an option for me; it doesn't contain the attributes (well, that could be fixed easily), and it's rather ugly. Imagine having to search for one particular password in 20 pages of CSV print-out.

I'm working on an alternative solution, HTML export, which contains the same data as CSV export (albeit with attributes), formatted nicely and intended to be printed using the web browser. Don't use it if you don't trust your web browser, printer driver, or printer (as stated by @droidmonkey above). Details in #3277, my code is here: https://github.com/wolframroesler/keepassxc/tree/feature/htmlexport
Feedback is welcome.
