### ISSUE TITLE
TOTP and KeePassHttp-Connector attributes should be exported

### ISSUE THREAD

**Issue by andschwa** [keepassxreboot/keepassxc#1437]
When exporting to CSV, issue #854 demonstrates that additional attributes for entries are not included. The summary of the discussion is that exporting all additional attributes would lead to O(n^2) sized export, as each unique attribute of an entry (row) would cause a new column to be added for all entries, and this obviously does not scale well.

However, there are several non-unique additional attributes that are often found in KeePassXC entries: those created by the built-in TOTP support and KeePassHttp-Connector integration. The common additional attributes are:

* `TOTP Seed`: containing the actual seed for generating TOTP codes, which is information as critical as the entry's password
* `TOTP Settings`: containing information on the code generator's settings for the entry; also important, but can be found again
* `KeePassHttp Settings`: containing manually-generated information the connector extension uses to whitelist/blacklist sites for auto-fill, very annoying information to lose

Adding these three attributes would add exactly three columns to the CSV export, which is a reasonable addition. Furthermore, the TOTP seed information is __critical__. If the user is (for some reason) using CSV as a backup (or an export), the current (and unexpected) behavior where the seed is not included could cause real, irreversible damage. Not including the seed is also causing a sort of "vendor lock-in", because it is not currently feasible to export the TOTP seed information without manually checking each and every entry.

Therefore I think that it is in the best interest of the users to include at least the seed (and most likely the other two fields above) in the CSV export.

Note: there are also attributes of the form `KPH: String field #n`; however, I believe these to be out-of-scope for now, as they are `n` in number, causing a similar scaling problem.

**Comment by PF93mc8y7erq92qTmTjJBysALa** [comment]
Still relevant for TOTP. KeePassHTTP however was removed and as of 2.4.0 it is no longer part of KeePassXC. See #1752.

**Comment by Senk0n** [comment]
Still relevant for TOTP.. Especially when there are too many TOTPs to carry manually.
