### ISSUE TITLE
Clarification needed on YubiKey Challenge/Resonse

### ISSUE THREAD

**Issue by 64b2b6d12b** [keepassxreboot/keepassxc#1438]
It would be good to have a section of the website FAQ which talks about the way the database is locked using YubiKey Challenge/Response.

From the FAQ: 

> KeePassXC generates a challenge and uses the YubiKey's response to this challenge to enhance the encryption key of your database. So in a sense, it makes your password stronger, but technically it doesn't qualify as a separate second factor, since the expected response doesn't change every time you try to decrypt your database. It does, however, change every time you save your database.

I would like to know why the response changes every time you save the database.

**Comment by droidmonkey** [comment]
A new seed is generated on every save.

**Comment by 64b2b6d12b** [comment]
Thankyou for clarifying @droidmonkey , do you see any value of adding this to the FAQ?

**Comment by droidmonkey** [comment]
Perhaps, we can add a little bit more about our database security features in general.
