### ISSUE TITLE
appimage incompatible with ibus/mozc

### ISSUE THREAD

**Issue by otyu** [keepassxreboot/keepassxc#1439]
Running KeepassXC 2.2.4 via appimage on Debian GNU/Linux 9 (stretch).
On text fields, the input is not compatible with the ibus input method with mozc (Japanese input).

For comparison, the 2.2.4 installation from the deb package is successful with respect to inputing text in japanese with ibus/mozc. [Furthermore, both deb and appimage are incompatible with ibus compose rules with the file `.Xcompose`. This was also reported in the closed issue #833, marked as an upstream Qt issue.]

## Expected Behavior

The appimage should be compatible with ibus/mozc.

## Current Behavior

The appimage is not compatible with ibus/mozc. Activating the mozc input method with "hiragana" characters yields only "alphabet" characters in text input fields.

## Steps to Reproduce (for bugs)

1. Run the appimage
2. On an input field, try to input japanese characters via ibus/mozc

## Context

Such compatibility is important for users which specifically need japanese input,
as well as probably others which rely on different input methods via ibus.

## Debug Info

KeePassXC - Version 2.2.4

Libraries:
- Qt 5.9.2
- libgcrypt 1.6.1

Operating system: Debian GNU/Linux 9 (stretch)
CPU architecture: x86_64
Kernel: linux 4.14.0-0.bpo.3-amd64

Enabled extensions:
- KeePassHTTP
- Auto-Type
- YubiKey

**Comment by phoerious** [comment]
The AppImage ships its own Qt version which has no plugins for ibus. To support it, we'd need to bundle ibus as well, but then we'd also need to bundle fcitx and what not.

**Comment by yan12125** [comment]
ibus plugin is part of [qtbase](https://github.com/qt/qtbase/tree/5.10/src/plugins/platforminputcontexts/ibus). For example, on Arch Linux the relevant file is /usr/lib/qt/plugins/platforminputcontexts/libibusplatforminputcontextplugin.so.

**Comment by phoerious** [comment]
It's a plugin. It may be bundled with qtbase, but it's still a plugin and we would need to bundle it with the AppImage.

**Comment by phoerious** [comment]
I bundled the ibus plugin with #1534. Please test the upcoming 2.3 release if it works for you.
