### ISSUE TITLE
Saving database resets the current folder to Root

### ISSUE THREAD

**Issue by knu** [keepassxreboot/keepassxc#144]
If you edit an entry and hit Control+S to save the database, the current focus gets moved to the first entry in the Root folder.

## Expected Behavior
The current focus (folder or entry) should stay so you can keep working there.

KeePassX 2.0.3 does not change the current entry or folder.

## Current Behavior
The focus will be moved to the first entry in the Root folder.

## Steps to Reproduce (for bugs)
1. Set focus on an entry that is not at the top, not in the Root folder 
2. Hit Control+S to save the database
3. The focus will be moved to the first entry in the Root folder

## Your Environment
* KeePassXC from the latest develop branch (ff6d78244bdb5b70839b211eb57827ce2c1f31d6)
* Qt 5.6.2: 
* Apple LLVM version 8.0.0 (clang-800.0.42.1)
* macOS 10.11.6

**Comment by TheZ3ro** [comment]
Can you please report the revision hash form the About Window in KeePassXC ? Just to know what commit is been used.

**Comment by knu** [comment]
@TheZ3ro Sure, it's ff6d78244bdb5b70839b211eb57827ce2c1f31d6 and that's the latest as of writing. (I've added the hash to the description above)

**Comment by dannysu** [comment]
I wanted to fix this too but haven't got a good minimal repro case.
I believe it has something to do with the auto-reload.

**Comment by louib** [comment]
@knu should be fixed in the latest version of the develop branch.
