### ISSUE TITLE
Open Database Files from a Flash Drive

### ISSUE THREAD

**Issue by YosefuJoe1** [keepassxreboot/keepassxc#1440]
## Expected Behavior

When I look in the /media folder i should see My /joe folder and then the list of external media
## Current Behavior

When i go to the /media folder, it's empty
## Possible Solution

add an option to see flash drives.

## Context

I have to drag the database files to my desktop whenever i want to use it, huge pain in the neck.
## Debug Info

KeePassXC - Version 2.2.4
Revision: 4723f66
Distribution: Snap

Libraries:
- Qt 5.7.1
- libgcrypt 1.7.6-beta

Operating system: Ubuntu Core 16
CPU architecture: x86_64
Kernel: linux 4.13.0-32-generic

Enabled extensions:
- KeePassHTTP
- Auto-Type
- YubiKey
Kernel: KERNEL

Enabled extensions:
- EXTENSIONS

**Comment by phoerious** [comment]
This is in our FAQ: https://keepassxc.org/docs/#faq-appsnap-homedir
It's a security "feature" of Snaps, nothing we can do about it.
