### ISSUE TITLE
After TOTP is set up in an entry, nothing gets added to its history

### ISSUE THREAD

**Issue by GUiHKX** [keepassxreboot/keepassxc#1445]
## Expected Behavior
KPXC should add new data to an entry's "History" tab, indicating that said entry has been modified.

## Current Behavior
Nothing gets added to the "History" tab, even though the entry has been obviously modified.

## Steps to Reproduce (for bugs)

1. Create e new entry and save it
2. Right click that entry, go to `Time-based one-time password` > `Set up TOTP...`
3. Type anything in the `Key` field and hit `Ok`
4. Go to the `History` tab of that entry, there will be nothing at all

## Debug Info
```
KeePassXC - Version 2.3.0-snapshot
Build Type: Snapshot
Revision: fc556d1

Libraries:
- Qt 5.10.0
- libgcrypt 1.8.2

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 4.14.15-1-ARCH

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey
```

**Comment by phoerious** [comment]
Thanks for the report. I pushed a fix.
