### ISSUE TITLE
Wrong path in view/edit when opening entry via search results

### ISSUE THREAD

**Issue by sandebert** [keepassxreboot/keepassxc#1447]
## Expected Behavior

Whenever I have the view/edit view open, I expect to see the path to the entry as the bold headline.

## Current Behavior

If I get to the view/edit view via search, the first segment of the path is always the marked item in the list to the left, meaning the view/edit shows an erroneous path.

## Possible Solution

It's simple to understand why this happened, because in all normal non-search cases it's perfectly fine to grab the selected item in the leftmost list and use that as the first part of the path. But that fails when arriving to the entry from search. So I propose not relying on what's selected in the leftmost list and instead use the actual data for the entry.

## Steps to Reproduce (for bugs)

1. Make sure you have a root folder **Good** and a root folder **Bad**.
2. Make sure you have the entry **Doggy** in the **Good** folder
3. Search for **Doggy** to populate the result list
4. Select **Bad** in the list and double click the search result **Doggy**
5. We want **Good > Doggy**, but we get **Bad > Doggy** as headline in the view/edit view

## Context

It caused me severe confusion for the better part of a minute.

## Debug Info

KeePassXC - 2.2.4
Revision: 4723f66

Libraries:
- Qt 5.7.1
- libgcrypt 1.7.6-beta

Operating system: Debian GNU/Linux 9 (stretch)
CPU architecture: x86_64
Kernel: linux 4.9.0-4-amd64

Enabled extensions:
- KeePassHTTP
- Auto-Type
- YubiKey

**Comment by jcyktor** [comment]
Should this issue be closed? It looks like the fix was merged back in February.

**Comment by droidmonkey** [comment]
Good catch!
