### ISSUE TITLE
Crash on opening entry after deleting custom icon

### ISSUE THREAD

**Issue by r0ckarong** [keepassxreboot/keepassxc#1448]
## Expected Behavior
Manually download new custom favicon for existing entry with older icon. Delete older custom icon. Confirm dialog. Assign new icon to current entry. 
Open other entry with previously assigned custom icon. Change icon to new icon. Save.

## Current Behavior
Downloaded the new custom icon, deleted the old icon. Confirmed the dialog that other entries were using that icon. Assigned new custom icon to the currenty entry. Saved entry. 

Double clicked on another entry that used to have the old icon. Crash.

## Steps to Reproduce (for bugs)
1. Open entry with existing custom favicon
2. Download custom favicon (different than the one assigned)
3. Delete old favicon from list
4. Confirm dialog about removing favicon for other entries
5. Assign new favicon
6. Save entry
7. Attempt to open different entry that had the now deleted favicon

I can not reproduce this by merely assigning a "fresh" custom favicon and removing it. I don't want to mess around with my DB too much for testing this atm. Will create a different DB later if that helps.

## Context
Creates app crash and potential data loss if database is not saved before crash.

## Debug Info

Attached as kpxc.txt macOS segfault report.

```
KeePassXC - Version 2.2.3
Revision: cf94610

Libraries:
- Qt 5.10.0
- libgcrypt 1.8.1

Operating system: macOS Sierra (10.12)
CPU architecture: x86_64
Kernel: darwin 16.7.0

Enabled extensions:
- KeePassHTTP
- Auto-Type
```

[kpxc.txt](https://github.com/keepassxreboot/keepassxc/files/1689414/kpxc.txt)

**Comment by phoerious** [comment]
I cannot reproduce your crash on my Linux system with 2.2.4.
