### ISSUE TITLE
[Website] Link to checksum verification instructions is an endless redirect

### ISSUE THREAD

**Issue by r0ckarong** [keepassxreboot/keepassxc#1449]
When I click on the link to to the verification instructions on the download page I get forwarded to the same page but with `/verifying-signatures/` added. You can repeat this infinitely and will end up with a URL looking like this:

`https://keepassxc.org/download/verifying-signatures/verifying-signatures/verifying-signatures/verifying-signatures/verifying-signatures/verifying-signatures/[...]`

Not sure where this pointed before but this way is broken.

**Comment by phoerious** [comment]
This is due to our webserver not respecting `AcceptPathInfo Off`. /verifying-signatures/verifying-signatures/ should give a 404, but unfortunately, it does't. I couldn't really find a way to change it. You shouldn't be redirected endlessly, though. If that happens, please clear your cache and try again.

**Comment by r0ckarong** [comment]
What I meant by redirecting endlessly is that it will load (seemingly) the same page when you click on the link and you can just keep doing that until you figure out that the URL is changing but you're not going anywhere. It's not an automatic redirect.

Fix looks good but needs to be rolled out to the server.

**Comment by phoerious** [comment]
It's automatically deployed upon merge.
The fact that you can construct these URLs has the reason explained above. If you know a fix other than AcceptPathInfo Off, please tell me.
