### ISSUE TITLE
Request URL when downloading entry icon

### ISSUE THREAD

**Issue by Toj** [keepassxreboot/keepassxc#1459]
Right now in order to have keepassxc download a website's favicon, you need to have an entry with the correct URL in the URL field, which causes a 3rd button to appear at the bottom of the Icon tab>Use a custom icon field which attempts to download the favicon from the URL you set when clicked.

If you want to easily get a favicon for a 'Group' on the left panel (not an entry which is inside a group), it isn't this easy as there is no 'URL' field to enter a URL, so there is no way to get a 'Download favicon' button. Your only option is to upload an icon manually, or the way I did it was to create a temporary dummy 'entry' for the website and then downloaded the favicon with that, which added the favicon to the library which lets it become selectable globally as an icon.

I was thinking of a lot of ways this could be solved, and the best one I could think of was to always have that 'Download favicon' button shown and enabled - but if it's pressed when there is nothing set as a URL (such as a blank 'entry' or any 'group'), something comes up that says something along those lines, and offers you a URL prompt where you can enter the URL there manually.

![suggestion](https://user-images.githubusercontent.com/35183025/35829989-91d63200-0abc-11e8-9044-d73531e724d9.png)

This would not only make it easier to set icons for Groups, but also let you easily download favicons for entries which you may not want to set a URL for; currently you'd enter the URL in the URL field, go to icon>download favicon and then delete the URL.

Since the button would now always be visible, this would also benefit new users who may not know the favicon downloading feature exists.

**Comment by droidmonkey** [comment]
With the new download icon button right next to the URL entry, this issue is obsolete.

![image](https://user-images.githubusercontent.com/2809491/52177138-bf4d6000-278a-11e9-9a27-54138130eb49.png)
