### ISSUE TITLE
Timeout or not connected to KeePassXC

### ISSUE THREAD

**Issue by jicho** [keepassxreboot/keepassxc#1466]
Hi,

I've installed the latest KeePassCX in combination with KeePassXC-Browser in Chrome. Both on Linux Mint 18.2

As soon as I click on the KeePassXC-browser icon I get the message:
```
KeePassXC-Browser has encountered an error:
Timeout or not connected to KeePassXC
```

KeePassCX is locked at the moment, I did activate the KeePassHTTP Server. When I look at the open ports on my system I see that KeePassXC is listening at the default port (19455). Can someone help me with figuring out why the plugin can't connect with KeePassXC? I would love to start using the Chrome plugin :)

**Comment by phoerious** [comment]
KeePassXC-Browser needs the 2.3 development branch. For 2.2 you need to use KeePassHttp-Connector.

**Comment by jicho** [comment]
Ah okay, thanks for the quick response!
