### ISSUE TITLE
Keepassxc locks yubikey 2 ; requires removal of yk after unlocking a db

### ISSUE THREAD

**Issue by patricktruebe** [keepassxreboot/keepassxc#1468]
The Challenge-Response-Screening of a locked database leads to a locked Yubikey 2 (2.4.2 fw)

My problem is not fixed by #961 

## Expected Behavior
1) Plug your Yubikey into USB
2) Start keepassxc
3) Unlock your database
4) Use your yubikey (Slot 1; static password) in any other application

## Steps to Reproduce (for bugs)
1) Plug your Yubikey into USB
2) Start keepassxc
3) Unlock your database
4) Yubikey is locked; LED is on; blinks on button push; LED is off and nothing happens
5) Remove and re-insert Yubikey
6) Use slot 1 in any other application (until a locked database screen is presented again)

## Debug Info
KeePassXC - Version 2.2.4
Revision: 4723f66

Libraries:
- Qt 5.9.4
- libgcrypt 1.8.2

Operating system: Fedora 27 (Workstation Edition)
CPU architecture: x86_64
Kernel: linux 4.14.16-300.fc27.x86_64

Enabled extensions:
- KeePassHTTP
- Auto-Type
- YubiKey

**Comment by sainaen** [comment]
This sounds like the same problem as in #1215.

**Comment by patricktruebe** [comment]
@sainaen yes agreed. Seems like the same bug to me.
