### ISSUE TITLE
mac OS dmg download seems corrupt

### ISSUE THREAD

**Issue by Winter84** [keepassxreboot/keepassxc#1469]
## Current Behavior

I have downloaded the macOS dmg (v 2.2.4-2) twice. Each time when I try to open it I get the message that it cannot be opened because it is a "corrupt image".

## Debug Info

KeePassXC - VERSION v2.2.4-2
Revision: REVISION

Operating system: OS X 10.10.5

**Comment by phoerious** [comment]
Duplicate of #1344

**Comment by Winter84** [comment]
If I understand #1344 correctly, this means that the issue has been closed with a decision not to resolve it. Is that right?

**Comment by phoerious** [comment]
The patch has been merged, but we didn't release a 2.2.5 for it and since the first 2.3 beta will be released very soon, we probably won't release another 2.2 patch.

**Comment by Winter84** [comment]
Thank you. I'll wait for 2.3.
