### ISSUE TITLE
Missing Argon2 Library on Mint 18 (Based on Xenial)

### ISSUE THREAD

**Issue by njfox** [keepassxreboot/keepassxc#1472]
I've been unable to build the develop branch from source on my Mint 18.2 machine for awhile now as there is no argon2 package available, even in the custom APT repo for some reason:

```
$ cat /etc/apt/sources.list.d/phoerious-keepassxc-xenial.list 
deb http://ppa.launchpad.net/phoerious/keepassxc/ubuntu xenial main
deb-src http://ppa.launchpad.net/phoerious/keepassxc/ubuntu xenial main

$ sudo apt-get install libargon2-0-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package libargon2-0-dev
$ sudo apt-get install argon2
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package argon2
```
Here is the error from cmake:

```
CMake Error at /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find Argon2 (missing: ARGON2_LIBRARIES ARGON2_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindArgon2.cmake:34 (find_package_handle_standard_args)
  CMakeLists.txt:296 (find_package)


-- Configuring incomplete, errors occurred!

```

I've also made sure to update the package list with `sudo apt-get update`. Is there anything I'm missing here?

**Comment by seatedscribe** [comment]
I had the same problem, see [#1417](https://github.com/keepassxreboot/keepassxc/issues/1417). Unfortunately that issue has not been reopened, thoug.
I installed argon2 directly from github. Remeber to delete CMake cache.
@phoerious can you please update the wiki with my considerations made there (and a step on deleting cache as well)? It seems nevertheless that somehow the custom PPA failed to provide argon2 package. Should we investigate? I am available for testing out.

**Comment by seatedscribe** [comment]
I had the same problem, see [#1417](https://github.com/keepassxreboot/keepassxc/issues/1417). Unfortunately that issue has not been reopened, thoug.
I installed argon2 directly from github. Remeber to delete CMake cache.
See also [#1472](https://github.com/keepassxreboot/keepassxc/issues/1472)

**Comment by phoerious** [comment]
The PPA only provides argon2 for Trusty. I'll upload a version for Xenial as soon as we get the beta out.

**Comment by phoerious** [comment]
PPA now provides argon2 for Xenial.

**Comment by njfox** [comment]
I've installed the argon2 package from the PPA on Xenial but I'm getting the following CMake error:

```
CMake Error at /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find Argon2 (missing: ARGON2_LIBRARIES ARGON2_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindArgon2.cmake:34 (find_package_handle_standard_args)
  CMakeLists.txt:323 (find_package)


-- Configuring incomplete, errors occurred!
```
Do I need to set environment variables pointing to the library or pass extra CMake options to build this?

**Comment by arichiardi** [comment]
I found that you need to pass the paths to `cmake` by `-D`. Not env vars. Afk now so I don't have an example, hopefully is clear.
