### ISSUE TITLE
Provide more filesystem info for database in window

### ISSUE THREAD

**Issue by sdowdy** [keepassxreboot/keepassxc#1474]
KeePassXC Version: 2.2.4

I keep my DBs on USB stick, and have a canonical source, but multiple "copies" that i keep at work or alternate locations (both for failure-recovery and for ensuring i don't forget the canonical stick when i am in different places).  I will regularly copy the kdbx files from the canonical USB, where i modify the database, to the copies so they remain reasonably current.
If i have both the canonical USB and a copy in use on the same machine (either because i have a long-running keepassxc session and have pulled the USB, but forgot to close the DB, or am viewing changes, etc..) it can be unclear what database is in use, because they have the same name on all media and all the tabs look identical.  It would be great if the FULL filesystem path to the DB were displayed in the Window Title, near the search gadget, or even if it were displayed in
  Database->Database Settings  panel
or anywhere else that makes sense in the UI.

I realize that there are tooltips on the tabs that do report this on hover, but a static display in the UI would be greatly appreciated.
thanks,
--stephen

**Comment by droidmonkey** [comment]
Requested in #2034
