### ISSUE TITLE
unable to save changes to entries

### ISSUE THREAD

**Issue by veremchook** [keepassxreboot/keepassxc#1475]
## Expected Behavior

My .kdbx file was created under KeePass version 2.38 (or possibly slightly older) under Windows 7.
It uses a strong master password to access.
When I open the file under keepassxc in Ubuntu I would expect all read and write to work.

## Current Behavior

I can open the file in Ubuntu and read everything.
In the main view I can e.g. clone and delete entries.
The save button is active and changes are written.

When I go into editing of any entry I can still view content and make changes but unable to save them.
Most options are greyed out and I'm only given two options when closing an edited entry:
"Close without Saving" or "Cancel"

## Possible Solution

N/A

## Steps to Reproduce (for bugs)

1. Create a .kdbx file under KeePass v 2.38 in Windows and populate with some entries.
2. Open the file under KeepassXC in Ubuntu.
3. Open an entry for viewing / editing.
4. Make a change and try to save it.

## Context

All changes save fine in Ubuntu when I edit with keepass2 2.32+dfsg-1.
I can see them when re-opening under Windows and with KeepassXC.

## Debug Info

KeePassXC - 2.2.4
Revision: 0ppa1~xenial1 

Libraries:

Do you mean my versions of all of the following:

apt-cache depends keepassxc
keepassxc
  Depends: libc6
  Depends: libgcrypt20
  Depends: libqt5core5a
  Depends: libqt5dbus5
  Depends: libqt5gui5
  Depends: libqt5gui5-gles
  Depends: libqt5network5
  Depends: libqt5widgets5
  Depends: libqt5x11extras5
  Depends: libstdc++6
  Depends: libx11-6
  Depends: libxi6
  Depends: libxtst6
  Depends: libykpers-1-1
  Depends: zlib1g

?

Operating system: Ubuntu 16.04 LTS
CPU architecture: amd64
Kernel: 4.4.0-112-generic

Enabled extensions:
N/A

**Comment by droidmonkey** [comment]
Are you using the snap? Please copy/paste the debug text in the about dialog (last tab)

**Comment by veremchook** [comment]
Do you mean this?

https://docs.snapcraft.io/snaps/

Sounds like quite some hassle and unfortunately I don't think I currently have time for it :(

I'm not desperate as legacy Keepass2 is still working fine for me.

But I understand it doesn't have bright future...

**Comment by hifi** [comment]
He meant that when you have KeePassXC running, open the about dialog from Help -> About and then paste the text from "Debug Info" tab (it has a Copy to clipboard button).

**Comment by veremchook** [comment]
OK, I can definitely do that :)
Here you go:

```
KeePassXC - Version 2.2.4
Revision: 4723f66

Libraries:
- Qt 5.5.1
- libgcrypt 1.6.5

Operating system: Ubuntu 16.04.3 LTS
CPU architecture: x86_64
Kernel: linux 4.4.0-112-generic

Enabled extensions:
- KeePassHTTP
- Auto-Type
- YubiKey
```

**Comment by wifon** [comment]
I have similiar problem, yet somehow different. I have a kdbx2 database, I can't "save" it (save button is grayed out), but "save as" to a new file option work without any problem.

```
KeePassXC - Version 2.3.0
Revision: 4c0ed74

Libraries:
- Qt 5.10.1
- libgcrypt 1.8.2

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 4.15.6-1-ARCH

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey
```

**Comment by TheZ3ro** [comment]
@wifon if you have autosave enabled in the global Settings, every edit you make to an entry is automatically saved (so no need to re-save and the Save icon is gray)

**Comment by wifon** [comment]
Oh, I wasn't aware of such feature after I've switched from original keepassx
Thank you.

**Comment by cyberpunkspace** [comment]
i had the same, but it was the autosave that greyed it out. Thanks for the info.
