### ISSUE TITLE
Partial username entry using global auto-type

### ISSUE THREAD

**Issue by nathanmiddleton** [keepassxreboot/keepassxc#1481]
## Expected Behavior

When using global auto-type the username/password should be typed in their entirety.

## Current Behavior

Currently when pressing the established global auto-type hotkey only part or none of the username will be added to the username box.

## Steps to Reproduce (for bugs)

1. Open web-browser
2. Navigate to login page
3. Insert cursor in username field
4. Press global auto-type shortcut

## Context

This issue seems to affect Windows 10 with Edge browser. I don't have any other software with which this usage is a requirement. It happens in whole or in part on every use case within the browser.

## Debug Info

KeePassXC - Version 2.2.4
Revision: 4723f66

Libraries:
- Qt 5.9.2
- libgcrypt 1.8.1

Operating system: Windows 10 (10.0)
CPU architecture: x86_64
Kernel: winnt 10.0.16299

Enabled extensions:
- KeePassHTTP
- Auto-Type
- YubiKey

**Comment by TheZ3ro** [comment]
Do you have some special characters in your username?
What is the layout of your keyboard in your operative system?

**Comment by weslly** [comment]
Have you tried increasing the auto-type delay at settings?

**Comment by nathanmiddleton** [comment]
@weslly yes the auto-type feature is set to 999, the maximum amount allowed, cuts off the username.

@TheZ3ro If "@" is considered a "special character" these days. Yes, I suppose. Although, that character types fine, it stops at random points. It also is random for the same login, whether asking me to open the database or not.

Just using a US English keyboard layout in Windows.

**Comment by droidmonkey** [comment]
Does this only happen to one entry or one page?

**Comment by hifi** [comment]
Is this related to the modifiers of your global shortcut? What if you set your shortcut to a single non-modifier key for testing (like a function key)?

**Comment by uzsolt** [comment]
Same here. The autotype doesn't type at (@) character but type "v" (AltGr+V = @).
Increased the delay 100ms, doesn't work.
Global hotkey: Alt+Shift+X - doesn't work. Alt+X - doesn't work.
Version is 2.4.0 on FreeBSD.

**Comment by droidmonkey** [comment]
I'm going to close this issue. The inability to type @ is another issue entirely and documented elsewhere.
