### ISSUE TITLE
Better error message in keepassxc-cli

### ISSUE THREAD

**Issue by azzamsa** [keepassxreboot/keepassxc#1484]
It will be nice if keepassxc-cli have better error message in wrong cli operation.
I keep trying 
- `keepassxc-cli passname passdbfile`
- `keepassxc-cli subgrup/passname passdbfile`
- `keepassxc-cli root/subgrup/passname passdbfile`

I don't realize that I don't put the argument in order, because keepassxc said 'file passname does not exists', it does not say that my argument order is wrong nor say that 'passname' is not passdb file.

## Expected Behavior

Better error message in wrong argument order (or any other cli operation)

## Current Behavior

Simple error massage

## Possible Solution

Make better error message.

## Steps to Reproduce (for bugs)

1. `keepassxc-cli passname passdbfile`

## Debug Info

KeePassXC - Version 2.2.4
Revision: 4723f66

Libraries:
- Qt 5.7.1
- libgcrypt 1.7.6-beta

Operating system: Debian GNU/Linux 9 (stretch)
CPU architecture: x86_64
Kernel: linux 4.9.0-4-amd64

Enabled extensions:
- KeePassHTTP
- Auto-Type
- YubiKey

**Comment by mkasberg** [comment]
The current behavior looks pretty good to me, very typical for a cli interface. What is the proposed change?

Current behavior:
```
$ keepassxc-cli --version
2.2.4

$ keepassxc-cli foo ~/Passwords.kbdx 
Invalid command foo.
Usage: keepassxc-cli [options] command
KeePassXC command line interface.

Available commands:
  clip		Copy a password to the clipboard.
  extract	Extract and print the content of a database.
  entropy-meter	Calculate password entropy.
  list		List database entries.
  merge		Merge two databases.
  show		Show a password.

Options:
  -h, --help     Displays this help.
  -v, --version  Displays version information.

Arguments:
  command        Name of the command to execute.

$ keepassxc-cli foo/bar ~/Passwords.kbdx 
Invalid command foo/bar.
Usage: keepassxc-cli [options] command
KeePassXC command line interface.

Available commands:
  clip		Copy a password to the clipboard.
  extract	Extract and print the content of a database.
  entropy-meter	Calculate password entropy.
  list		List database entries.
  merge		Merge two databases.
  show		Show a password.

Options:
  -h, --help     Displays this help.
  -v, --version  Displays version information.

Arguments:
  command        Name of the command to execute.
```

**Comment by louib** [comment]
@azzamsa thanks for the feedback. I believe https://github.com/keepassxreboot/keepassxc/pull/2465 will make it clear that the problem is with the first argument (the database file).

**Comment by azzamsa** [comment]
Thank you for [this](https://github.com/keepassxreboot/keepassxc/pull/2465/files).

Thanks :)
