### ISSUE TITLE
Ability to add other columns to main window

### ISSUE THREAD

**Issue by cxWoNSUUt** [keepassxreboot/keepassxc#1487]
Would be nice if there were the functionality to add other columns to the main window, such as the number of history items, when the item was created/modified last etc. A lot of applications have the ability to right click on existing columns, and then you can add any others that you want.

## Expected Behavior
When right-clicking any existing column, display a context menu that allows selecting/adding any desired columns

## Current Behavior
Current behaviour does not exist

## Steps to Reproduce (for bugs)
N/A

## Context
Currently, to see some of the info I discussed above, you have to double-click the item, then go into history. Would be good to get all this info at a single glance. Would help also in seeing how many passwords are old and need to be changed

## Debug Info

KeePassXC - 2.2.4

Operating system: Windows
CPU architecture: x86_64
Kernel:

**Comment by phoerious** [comment]
This is implemented and will be available in 2.3.
