### ISSUE TITLE
Focus selected folder after search

### ISSUE THREAD

**Issue by edrush** [keepassxreboot/keepassxc#1501]
(this might be an improvement)
## Expected Behavior
After doing a search, I'd like to see the contents of a folder that I select in my tree directly instead of having to press "Esc"/cancel search first.

## Current Behavior
I search for something, use that entry, then later I select a folder but the search result list remains in the main window.

## Possible Solution
Directly list contents of a folder on select.

## Steps to Reproduce (for bugs)

n/a

## Context
I'd like to improve my work's flow.

## Debug Info

KeePassXC - Version 2.2.4
Revision: 4723f66

Bibliotheken:
- Qt 5.9.1
- libgcrypt 1.8.1

Betriebssystem: macOS High Sierra (10.13)
CPU-Architektur: x86_64
Kernel: darwin 17.4.0

Aktivierte Erweiterungen:
- KeePassHTTP
- Auto-Type
- YubiKey

**Comment by 0xpr03** [comment]
+1 I've one entry which is kind of unsearchable / I just know where it is. And when I've searched something and click on a folder afterwards, the results remain empty. The original keepass (and keepassx?) just displayed the content of the folder, resetting the search field. I'm in favor of that behavior.

**Comment by droidmonkey** [comment]
Im going to roll this into my enhanced search pr being posted tonight.
