### ISSUE TITLE
Sanitize newline while c&p into input fields

### ISSUE THREAD

**Issue by xf-** [keepassxreboot/keepassxc#1502]
## Expected Behavior

Remove newline

## Current Behavior

Output in listing include newlines.

## Possible Solution

Clean all \n \r and maybe other control chars to avoid broken UI. 

## Steps to Reproduce (for bugs)

1. c&p text like a URL form a Mail into keepass including a line break
2. Save entry
3. List view is "broken"

## Context

Avoid a broken UI

## Debug Info

KeePassXC - Version 2.2.4
Revision: 4723f66

Libraries:
- Qt 5.10.1
- libgcrypt 1.8.2

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 4.15.3-2-ARCH

Enabled extensions:
- KeePassHTTP
- Auto-Type
- YubiKey

![image](https://user-images.githubusercontent.com/1295633/36435198-4a6b00a2-1661-11e8-9f62-7b8b9e2db337.png)

**Comment by phoerious** [comment]
Fixed in #1528
