### ISSUE TITLE
A way to select view/noview notes on main window when selecting entries

### ISSUE THREAD

**Issue by luuuciano** [keepassxreboot/keepassxc#1503]
In many entries I have a lot of information located in the entry notes**... I find very useful to be able to see notes on main window, when selecting entries (keepass 2.28 show it that way)...
Something like:

----------------------|
|group |entry       |
|group |entry       |
|group |entry       |
|group |------------|
|group |notes      |
|          | notes     |
----------------------|

Operating system: gnuLinux Debian

** as a way to group information in one entry... and to not have a LOT of entries for the same "resource", or whatever

**Comment by phoerious** [comment]
I think what you are looking for are additional table columns or a preview panel. This is already implemented and will be released with 2.3.
