### ISSUE TITLE
Two english language

### ISSUE THREAD

**Issue by OlivierMary** [keepassxreboot/keepassxc#1506]
Two english language in properties, one isn't english:
![screenshot_20180221_213852](https://user-images.githubusercontent.com/4348675/36504295-4e7bcc22-1750-11e8-8a95-8f4e0c1e0a74.png)

## Expected Behavior

English is english :)
## Current Behavior

English is not english
## Possible Solution

Take the other line of english language
## Steps to Reproduce (for bugs)

1. Change language to English (second line for me)
2. Restart
3. Go to About screen

## Debug Info

KeePassXC - Phiên bản  2.3.0-snapshot
Build Type: Snapshot
Revision: 0237b21

Thư viện:
- Qt 5.10.1
- libgcrypt 1.8.2

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 4.15.3-2-ARCH

Phần mở rộng đã bật:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by phoerious** [comment]
This is already fixed. I pulled in translations from Transifex and some guy apparently started translating the en_US translation into Vietnamese. I reverted the incorrectly translated strings and marked en_US as reviewed, so it doesn't happen again.
