### ISSUE TITLE
How to out of date?

### ISSUE THREAD

**Issue by mantuko** [keepassxreboot/keepassxc#1509]
I'm trying to connect KeePassXC to the browser extension. In the howto there's a screenshot of the settings page. The interface shown there doesn't match with mine. KeePassXC and it's browser extension are both up to date. And after all I've read i should see a different UI there.

I enclosed a screenshot of my settings dialogue showing settins for the KeePassHTTP server instead of the KeePass browser integration as shown in the howto.

What am I missing?

KeePassXC version 2.2.4
KeePassXC-Browser version 0.6.0
OS Windows 10

[screenshot](https://cachecatcher.com/owncloud/index.php/s/PjapOhFfZYKCWsb)

**Comment by phoerious** [comment]
You need KeePassXC 2.3 beta for it to work.
