### ISSUE TITLE
macOS Unable to set up Global auto-type shortcut 

### ISSUE THREAD

**Issue by jjuris** [keepassxreboot/keepassxc#1515]
Hello there 

I just received brand new MacBook Pro from my employer. My first step was installing keepassxc, unfortunately I am not able to set up global auto type shortcut, therefore I am not able to use auto type. According to the information on the web, FAQ etc it should be able to use autotype on all major platforms. 

Thanks with help, I love KeepassXC

## Expected Behavior
I would like to set up global auto type shortcut

## Current Behavior
I am not able to setup global auto type shortcut

## Possible Solution
I am ok with editing conf file

## Context
It may be caused by the fact that computer is part of "Apple domain" and there are applied some security settings on this system. 

## Debug Info
KeePassXC - Version 2.2.4
Revision: 4723f66

Libraries:
- Qt 5.9.1
- libgcrypt 1.8.1

Operating system: macOS High Sierra (10.13)
CPU architecture: x86_64
Kernel: darwin 17.3.0

Enabled extensions:
- KeePassHTTP
- Auto-Type
- YubiKey

**Comment by weslly** [comment]
Have you tried checking if you have a conflicting global shortcut? 
https://support.apple.com/kb/PH25490?locale=en_US&viewlocale=en_US

**Comment by jjuris** [comment]
Hi

Problem is solved. I got stuck because I would expect the place where you define AutoType shortcut would let me know "hey man its time to input your shortcut now" by highlighting input field for example.
 
Maybe it would be great to include this behaviour of shortcut field in the software. I do not close it now, so you can consider it if is worth implementing or not, ok ?

Anyway thanks for help it led me to the solution. 

Jozef

**Comment by jjuris** [comment]
I just checked it on windows and this field is not highlighted after click on it either. The most probabl  same on linux , I will check it later, when i get into office later today

**Comment by jjuris** [comment]
@weslly I am talking about field highlighting man, not about its presence in options :) Look at screenshot what I mean
![fieldhighlight](https://user-images.githubusercontent.com/3681629/36583884-b932b9b8-1877-11e8-88f2-fcde4f5c5849.jpg)

**Comment by weslly** [comment]
Fixed in #1517
