### ISSUE TITLE
macOS can not connect database in KeepassXC Browser extension (Firefox)

### ISSUE THREAD

**Issue by r0ckarong** [keepassxreboot/keepassxc#1518]
## Expected Behavior
I would expect to be able to set up a database connection to an opened database and use the extension.

## Current Behavior
I turn on the new browser extension support in the 2.3 Beta application. Then I install the KeepassXC Browser extension into Firefox and try to establish a connection. The window asking me to define a name for the database settings never shows up and no connection is ever established. 

I can not use the browser extension to fill data fields.

## Steps to Reproduce (for bugs)
1. Install 2.3.0-Beta1 on macOS Sierra
2. Install KeepassXC-Browser Extension in Firefox 58.0.2
3. Disable Legacy Browser Support
4. Disable Legacy Browser Extension
5. Enable Browser Support for new extension
6. Try to establish connection

## Context
The browser extension never establishes a connection with the app and does not work.

## Debug Info
KeePassXC - Version 2.3.0-beta1
Build Type: PreRelease
Revision: 10bd73c

Libraries:
- Qt 5.9.3
- libgcrypt 1.8.2

Operating system: macOS Sierra (10.12)
CPU architecture: x86_64
Kernel: darwin 16.7.0

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

#INFO From Extension About
 KeePassXC-Browser Version: 0.6.0

KeePassXC Version: unknown

**Comment by varjolintu** [comment]
Could you debug the extension and see if there's any error messages in the console? Also, can you look if keepassxc-proxy is up and running?

**Comment by mortenbendtsen** [comment]
I have experianced the same issue.

**Comment by varjolintu** [comment]
To debug the extension, go to `about:debugging` and toggle the `Enable add-on debugging` checkbox. Then you can find the KeePassXC-Browser extension and click `Debug` under it. That should open a separate window where you can view the console.

**Comment by r0ckarong** [comment]
Will do that later. How do I verify that the proxy is running?

**Comment by varjolintu** [comment]
Use the Activity Monitor application to see running processes.

**Comment by nscuro** [comment]
It seems that the keepassxc-proxy binary cannot be launched, attempting to do it manually results in:
```sh
➜  ~ /Applications/KeePassXC.app/Contents/MacOS/keepassxc-proxy
dyld: Library not loaded: /usr/local/Cellar/qt/5.9.3/lib/QtNetwork.framework/Versions/5/QtNetwork
  Referenced from: /Applications/KeePassXC.app/Contents/MacOS/keepassxc-proxy
  Reason: image not found
[1]    7150 abort      /Applications/KeePassXC.app/Contents/MacOS/keepassxc-proxy
```

I don't have any Qt libraries installed, so I guess this is a linking issue in the build process?

The libraries are definitely present in the app container though, see
```sh
➜  ~ ls /Applications/KeePassXC.app/Contents/Frameworks
QtConcurrent.framework   QtNetwork.framework      libargon2.1.dylib        libsodium.23.dylib
QtCore.framework         QtPrintSupport.framework libgcrypt.20.dylib       libykpers-1.1.dylib
QtGui.framework          QtSvg.framework          libgpg-error.0.dylib     libyubikey.0.dylib
QtMacExtras.framework    QtWidgets.framework      libjson-c.2.dylib
```

**Comment by varjolintu** [comment]
This explains a lot. I made a custom commands to makefiles that link all Qt libraries to the ones inside the .app package. For some reason I cannot find those commands in the sources anymore. I'll search them and commit them again. Thanks for finding this one!

**Comment by varjolintu** [comment]
Currently src/proxy/CMakeLists.txt points to `/usr/local/opt/qt/lib/`. Maybe the one building macOS binaries could make a symbolic link to that location from `/usr/local/Cellar/qt/5.9.3/lib/` before building the package? The linkage can be checked with `otool -L /Applications/KeePassXC.app/Contents/MacOS/keepassxc-proxy`

**Comment by nscuro** [comment]
Can confirm that the [suggested commands](https://github.com/keepassxreboot/keepassxc/issues/1518#issuecomment-368235888) fix the issue.

**Comment by r0ckarong** [comment]
Can also confirm, I get the same error in the extension debugging session.

Ran the commands and now it works.

**Comment by varjolintu** [comment]
Great news! Now I know what to fix. Thanks guys :)

**Comment by phoerious** [comment]
I didn't realize the CMakeLists.txt hardcodes the path to Qt. This should not be the case. /usr/local/opt/qt only works with the upstream Qt distribution, not with Homebrew.
