### ISSUE TITLE
KeePassXC does not open recently used database

### ISSUE THREAD

**Issue by ovalseven8** [keepassxreboot/keepassxc#1519]
When I open KeePassXC, the last recently used database is not loaded automatically.

However, in my settings the option is enabled, so everything should work. What do I do wrong?

## Debug Info

KeePassXC 2.2.4
Operating system: Arch Linux

**Comment by phoerious** [comment]
This has been fixed in 2.3.0-beta1.

**Comment by ovalseven8** [comment]
It still does not work with the new 2.3.0 version.

**Comment by phoerious** [comment]
There are two settings. One for remembering recent databases and one for loading the last database.
