### ISSUE TITLE
KeePassXC proxy prevents uninstall/install

### ISSUE THREAD

**Issue by droidmonkey** [keepassxreboot/keepassxc#1521]
## Expected Behavior

When I uninstall the application, all associated executables are terminated to ensure a complete process.

## Current Behavior

When you uninstall 2.3.0-beta1 it does not terminate keepassxc-proxy.exe locking up the exe's and Qt dll's.

## Possible Solution

Explicitly terminate the executables in the uninstaller (NSIS/WIX).

## Steps to Reproduce (for bugs)

1. Install KeePassXC 2.3.0-beta1 on Windows
2. Enable keepassxc-browser plugin and set it up with a browser
3. Have the browser running, ensure keepassxc-proxy.exe is started
4. Uninstall KeePassXC 2.3.0-beta1

## Debug Info

KeePassXC - 2.3.0-beta1
Windows

**Comment by phoerious** [comment]
Fixed in #1523
