### ISSUE TITLE
Appimage does not work on ubuntu 16.04 xenial

### ISSUE THREAD

**Issue by raghur** [keepassxreboot/keepassxc#1522]
## Current Behavior
Get a dialog box when running `./KeePassXC-2.3.0-beta1-x86_64.AppImage` and then it exits

```
Fatal error while testing the cryptographic functions.
GCRY_CIPHER_CHACHA20 not found.
```

Operating system: KDE Neon user edition 5.12.2
CPU architecture: amd64
Kernel: 4.11.0-14-generic

**Comment by phoerious** [comment]
Fixed in 8dad78194fcd1885 and I uploaded a new AppImage build.
