### ISSUE TITLE
libsodium in ppa breaks mpv

### ISSUE THREAD

**Issue by Jusix** [keepassxreboot/keepassxc#1532]
## Expected Behavior
ppa lib upgrade should not break other system apps.

## Current Behavior
The upgrade of libsodium to version 1.0.16-0ppa3~xenial1 in ppa:phoerious/keepassxc has broken mpv media player.

## Possible Solution
Downgrade libsodium to version 1.0.8-5 from the offical Ubuntu repo.

## Steps to Reproduce (for bugs)
1. Install keepassxc from ppa:phoerious.
2. Install mpv from Ubuntu repo.
3. Try to start mpv
4. "mpv: error while loading shared libraries: libsodium.so.18: cannot open shared object file: No such file or directory"

## Context
-

## Debug Info
KeePassXC - 2.2.4-0ppa1~xenial1

Libraries:
- libsodium=1.0.16-0ppa3~xenial1

Operating system: Ubuntu 16.04.3
CPU architecture: x86-64
Kernel: 4.13.0-36-generic

**Comment by phoerious** [comment]
libsodium18 isn't installed by us anymore. We install libsodium23. You can install libsodium18 from the Ubuntu repository in parallel.
