### ISSUE TITLE
Single-instance mode breaks opening KDBX files by double click

### ISSUE THREAD

**Issue by phoerious** [keepassxreboot/keepassxc#1533]
When a KeePassXC instance is running and the user double-clicks a KDBX file to open it, the existing KeePassXC instance will be activated, but the file won't be opened.

## Expected Behavior

Double-clicking a file should open it in KeePassXC, even if an instance is already running.

## Current Behavior

KeePassXC is activated, but file doesn't open. Dragging it into the KeePassXC window works.

## Possible Solution

Pass file name to running instance before exiting.

## Steps to Reproduce (for bugs)

1. Open KeePassXC (compiled in Release mode)
2. Double-click a KDBX file to open it

## Debug Info

KeePassXC - Version 2.3.0-preview
Build Type: PreRelease
Revision: 10bd73c

Libraries:
- Qt 5.9.1
- libgcrypt 1.7.8

Operating system: Ubuntu 17.10
CPU architecture: x86_64
Kernel: linux 4.13.0-36-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by nemoinis** [comment]
This is probably another manifestation: specifying a database name on the command line does not prompt for password/keyfile either. e.g.,
    $ keepassxc /path/to/my/database
just starts keepassxc as if /path/to/my/database had not been given.
This happens whether Single-instance mode is on or not.

**Comment by phoerious** [comment]
Turns out, this is the same issue as #1358.
