### ISSUE TITLE
Add a way to toggle keepassxc window from the command line

### ISSUE THREAD

**Issue by IvanMalison** [keepassxreboot/keepassxc#154]
Does something like this exist?

**Comment by TheZ3ro** [comment]
Toggle the visibility? there is this opened issue https://github.com/keepassxreboot/keepassxc/issues/99
But it's for KeyShortcut instead of CLI option

**Comment by droidmonkey** [comment]
Please do not file questions as issues.

**Comment by IvanMalison** [comment]
This is not a question. I'm asking for a feature in this issue.

**Comment by droidmonkey** [comment]
#99 requests this feature.

For the record, your original issue text was in the form of a one line question. You edited your original text AFTER my post, gave me a thumbs down, then said you were asking for a feature....

**Comment by IvanMalison** [comment]
@droidmonkey The title of the question is clearly not a question. I changed the text, because you apparently did not like that, but the fact remains that the issue was not, as you put it, merely a question. Also, #99 does not really request this feature until I mentioned it explicitly, that issue asks for a keyboard shortcut which is obviously not the same thing...

**Comment by droidmonkey** [comment]
I was a little annoyed due to ignoring both our contribution guidelines and the issue template we have in place. Your request will make it into this software thanks to your comments in 99, but please follow our setup in the future for additional issues or feature requests.
