### ISSUE TITLE
Allow password-less auto-open from within another database

### ISSUE THREAD

**Issue by pquerner** [keepassxreboot/keepassxc#1541]
## Expected Behavior
Passworded keepassfile is opened without password prompt.

## Current Behavior
kdbx file is opened, but prompted for a password.

## Possible Solution
Use password from "master". 

## Steps to Reproduce (for bugs)
1. Use 2.3.0-beta1
2. Create master and slave test databases
3. URL = file://fullpathtoslave.kdbx
4. Password = password used as test. (I tried "1" and "test")

## Context
#477 was the issue
#1053 was the PR

## Debug Info

KeePassXC - Version 2.3.0-beta1 (Portable)
Build-Typ: PreRelease
Revision: 69283e8

Bibliotheken:
- Qt 5.10.1
- libgcrypt 1.8.2

Betriebssystem: Windows 10 (10.0)
CPU-Architektur: x86_64
Kernel: winnt 10.0.16299

Aktivierte Erweiterungen:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by TheZ3ro** [comment]
Related to https://github.com/keepassxreboot/keepassxc/issues/1259#issuecomment-368851295
