### ISSUE TITLE
Battle.net Authentificator

### ISSUE THREAD

**Issue by o1o1o1o1o1** [keepassxreboot/keepassxc#1547]
Since the new version supports steam which is a very cool feature i have the question if you can add support for the battle.net authentificator too so i can finally stop using winauth.

**Comment by tycho** [comment]
Battle.net just uses the normal TOTP algorithm with an 8-digit code instead of 6-digit. So when adding it, just use the "Code size" set to "8 digits" and it should just work.

**Comment by jleclanche** [comment]
What @tycho said.

You can use my python-bna library to generate the authenticator and get the seed:

https://github.com/jleclanche/python-bna

```
pip install bna

bna --new
bna --otpauth-url
```

Take the secret from there and add it into keepassxc, 8 digits output. That's your seed.

Update: For newer versions of bna, use these two commands instead:

```
bna new
bna show-url
```

**Comment by o1o1o1o1o1** [comment]
thanks i never thought that it was so easy
