### ISSUE TITLE
Unsupported Legacy Key File Format ?

### ISSUE THREAD

**Issue by repsorp** [keepassxreboot/keepassxc#1549]
This message when opening KeePassXC 2.3.0 :

![kesspassxc](https://user-images.githubusercontent.com/6297032/36779153-5c0c3f60-1c6f-11e8-848b-90d812290106.png)

What would be the best way to generate a new supported key file ?

Operating system: Ubuntu 16.04

**Comment by phoerious** [comment]
You can go to Database/Change Master Key and then click on "Generate new key file" or simply use any other file with enough random or pseudo random data that only you own and nobody else.

**Comment by rominf** [comment]
I want to reopen this. This is not a bug, but a usability feature. Normal users care only about passwords, not about infrastructure. IMHO, the new key file should be generated automatically in place without any confirmation, because for a normal user it should be a black box and "it just works".

**Comment by RealOrangeOne** [comment]
Most people choose not to sync the key in the same way they sync their database. I personally sync my database with Nextcloud, but manually install my key onto each device, which works very well for me. I spent some of this weekend upgrading to 2.3, and wrote up some documentation on it, including generating a new key: https://theorangeone.net/posts/keepassxc-2.3-migration/#new-key-files

**Comment by TheZ3ro** [comment]
I agree with @phoerious, users must have infrastructure/organization in place before using keyfiles otherwise they will lose access to their passwords' database

**Comment by affinityv** [comment]
Why can't the "original" key files co-exist?  I like the possibility to not tie down my database to a single software base; I cam from KP2 on Winblows, will the new key and current database work in Windows, or am I locked in to KPXC only now?

**Comment by TheZ3ro** [comment]
Nope, the new keyfile is supported in KP2 as well

**Comment by droidmonkey** [comment]
The new key works everywhere

**Comment by affinityv** [comment]
Okay, great.  I thought that a file, any file or even multiple files could already be a "key file"; but the "legacy" xml version does things differently because it has a special format?
