### ISSUE TITLE
Mention libraries changes into changelog

### ISSUE THREAD

**Issue by Germano0** [keepassxreboot/keepassxc#1551]
Hi, I am one of the Fedora KeepassXC maintainers.
KeepassXC is the best password manager we have on our Linux distribution, main hub of the user security, so we know how important is to package it as best we can.
Today version 2.3.0 has been released, but in the [changelog](https://github.com/keepassxreboot/keepassxc/releases/tag/2.3.0), despite all changes have been listed, the new and changed dependencies have not been mentioned.
Could you please explicitly add them in a separate list? A good example is [darktable release changelogs, section changed dependencies](https://github.com/darktable-org/darktable/releases/tag/release-2.4.0)
Thank you

**Comment by phoerious** [comment]
There is a list of required packages on our website: https://keepassxc.org/project/#requirements

Run time dependencies are:
- Qt5 (5.2 or newer, 5.3 or newer for compiling browser integration): qtbase and qttools5
- libgcrypt (1.7 or newer)
- libargon2
- zlib
- libxi, libxtst, qtx11extras (optional, for Auto-Type on X11/Linux)
- libyubikey, libykpers-1 (optional, for YubiKey support)
- libsodium (optional, for Browser Integration support)
- libcurl4 (optional, for downloading website favicons)

Additional compile time dependencies are:
- make
- cmake (3.1 or newer)
- g++ (4.7 or newer) or clang++ (3.0 or newer)
- headers for all runtime dependencies (*-dev or *-devel packages)
