### ISSUE TITLE
Sorting by password could potentially leak information, even if password is hidden.

### ISSUE THREAD

**Issue by siraben** [keepassxreboot/keepassxc#1553]
## Expected Behavior
The sorting behavior should be non-existent or use the title of the entry as the thing to be sorted.

## Current Behavior
When in an unlocked database, click the column header labelled "Password". One would see the passwords sorted alphabetically. This could potential leak information about their contents.

## Possible Solution
Disable sorting by password.

## Debug Info
KeePassXC - Version 2.3.0
Revision: 4c0ed74

Libraries:
- Qt 5.9.3
- libgcrypt 1.8.2

Operating system: macOS High Sierra (10.13)
CPU architecture: x86_64
Kernel: darwin 17.4.0

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by droidmonkey** [comment]
Are you concerned with an unauthorized third party sorting your passwords? If so then you should also be concerned with them double clicking on the password field itself to copy to clipboard and paste into an email to themselves. What you describe is not leaking anything, imo.

**Comment by phoerious** [comment]
I think this is pretty much a non-issue. As explained before, the only one who can sort by password is you and you can freely decide not to do it if you are worried about shoulder surfing.

**Comment by TheZ3ro** [comment]
Also in the case you take a screenshot of your unlocked database the only information you get is that an entry's password starts with a letter <= of another entry's password.
This information is pretty useless by itself.

The only case where you learn something useful is if you know at least 1 from the database. The best case is knowing the password above and below the target password.
Then you can reduce the search space for a brute-force attack.

But this is already a very remote and unlikely case.
