### ISSUE TITLE
Crash when selecting another group in the tree on the left.

### ISSUE THREAD

**Issue by Faust30000** [keepassxreboot/keepassxc#1554]
When using version 2.3.0, this error is constantly observed. There is a main group in the tree of groups, and there are children in it. If you click on one of the child groups, the application closes. We have to open it again.

KeePassXC - Версия 2.3.0
Ревизия: 4c0ed74

Библиотеки:
- Qt 5.5.1
- libgcrypt 1.8.1

Операционная система: Linux Mint 18.3
Архитектура CPU: x86_64
Ядро: linux 4.13.0-36-generic

Включенные расширения:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by phoerious** [comment]
This is probably the same as #1254 and #335, which is a bug in Qt 5.5 and was only fixed in 5.6.
Please use the AppImage if it keeps happening.
