### ISSUE TITLE
After Update to 2.3.0 master-password removed

### ISSUE THREAD

**Issue by bullet64** [keepassxreboot/keepassxc#1563]
After update to version 2.3.0 i got "Wrong key or database is corrupt. (HMAC mismatch)" I am using an YubiKey.
After some testing i recognize that DB don't have any password!???

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Debug Info

KeePassXC - Version 2.3.0
Revision: 4c0ed74

Libraries:
- Qt 5.5.1
- libgcrypt 1.8.1

Operating system: Linux Mint 18.3
CPU architecture: x86_64
Kernel: linux 4.10.0-42-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by phoerious** [comment]
Did you change some master key settings and accidentally forgot to tick the password box?

**Comment by bullet64** [comment]
No, only step was update to 2.3.0.

**Comment by phoerious** [comment]
Were you using a YubiKey?

**Comment by bullet64** [comment]
I am using KeePassXC for long time. My Database is only locked with an YubiKey (Challenge Response on second Slot).

After Update i became the error message with ticked "Challenge Respond". Then i found that when i opened DB with nothing ticked it works. DB is without password.

I don't know why!?? But it's ok when i the only person with this problem. I put an new password on my DB and all is fine.

Thanks for your work!

**Comment by TheZ3ro** [comment]
Ok we found out the problem, a fix will be available in the next 2.3.1 version. Sorry for the inconvenience.

You should set a master-password or *downgrade the database to KDBX3.1 again* in the meantime.

**Comment by phoerious** [comment]
Actually, the other way round. Upgrade to KDBX 4 explicitly and re-add your YubiKey.
We do, however, not recommend using a password-less database.

**Comment by phoerious** [comment]
Fix merged.

**Comment by bullet64** [comment]
Fine that you solved the problem. Thanks!!

**Comment by phoerious** [comment]
If you upgrade to KDBX4 manually (best use Argon2), you should just be able to continue using your database as you did before, though I suggest setting a password nonetheless.
