### ISSUE TITLE
Failed dependency (libsodium23) on update of keepassxc on Ubuntu 16.04

### ISSUE THREAD

**Issue by MelissaRice** [keepassxreboot/keepassxc#1571]
During a routine software update using the Ubuntu software updater on Ubuntu 16.04, a failed dependency was reported involving libsodium23 which prevented keepassxc from updating properly.

The update presumably came from the repository:
 http://ppa.launchpad.net/phoerious/keepassxc/ubuntu xenial 

During the process of trying to correct this I tried:

**$ sudo apt-get autoremove**
```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
You might want to run 'apt-get -f install' to correct these.
The following packages have unmet dependencies:
 keepassxc : Depends: libsodium23 but it is not installed
E: Unmet dependencies. Try using -f.
```

and

**sudo apt-get -f install**
```
The following additional packages will be installed:
  libsodium23
The following NEW packages will be installed:
  libsodium23
0 upgraded, 1 newly installed, 0 to remove and 15 not upgraded.
1 not fully installed or removed.
Need to get 0 B/436 kB of archives.
After this operation, 1,999 kB of additional disk space will be used.
Do you want to continue? [Y/n] y
(Reading database ... 338801 files and directories currently installed.)
Preparing to unpack .../libsodium23_1.0.16-0ppa3~xenial1_amd64.deb ...
Unpacking libsodium23:amd64 (1.0.16-0ppa3~xenial1) ...
dpkg: error processing archive /var/cache/apt/archives/libsodium23_1.0.16-0ppa3~xenial1_amd64.deb (--unpack):
 trying to overwrite '/usr/lib/x86_64-linux-gnu/libsodium.so.23.1.0', which is also in package libsodium18:amd64 1.0.16-0ppa1~xenial1
dpkg-deb: error: subprocess paste was killed by signal (Broken pipe)
Processing triggers for libc-bin (2.23-0ubuntu10) ...
Errors were encountered while processing:
 /var/cache/apt/archives/libsodium23_1.0.16-0ppa3~xenial1_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

Can you please suggest a short term workaround or fix for this so I can still run some version of keypassxc but not have broken packages in my package manager? It's interfering with my ability to update other packages. Thanks very much!

KeePassXC - Version 2.3.0
Revision: 4c0ed74

Libraries:
- Qt 5.5.1
- libgcrypt 1.8.1

Operating system: Ubuntu 16.04.4 LTS
CPU architecture: x86_64
Kernel: linux 4.13.0-36-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by TheRealFlamepanther** [comment]
Encountering the same problem. It's possible to manually remove libsodium 18 and install libsodium 23, but this triggers uninstallation of gstreamer--obviously not desirable for most desktop users.

**Comment by MelissaRice** [comment]
A number of things depend on libsodium18 so I don't want to break a bunch of other stuff while attempting to fix this:

**apt-cache rdepends libsodium18**
```
libsodium18
Reverse Depends:
  libsodium-dbg
  python3-libnacl
  python-libnacl
  python3-nacl
  python-nacl
  netsniff-ng
  libzmq5
  libsodium-dev
  dnscrypt-proxy
  fastd
  dnsdist

```

**Comment by droidmonkey** [comment]
Your best bet is to use the snap or appimage.

**Comment by MelissaRice** [comment]
Thanks droidmonkey. I installed the snap version which worked fine. I was finally able to fix the package manager after uninstalling the offending version of keepassxc. That solves my current problem. Thanks everyone!

**Comment by phoerious** [comment]
Actually, this is just Ubuntu failing to downgrade libsodium18 to the Ubuntu-provided version while trying to install our libsodium23.

It's a duplicate of #1545, please apply the solution suggested there.
