### ISSUE TITLE
Correct file open ordering regression

### ISSUE THREAD

**Issue by droidmonkey** [keepassxreboot/keepassxc#1572]
## Expected Behavior

Files should be opened in the last order they were closed in.

## Current Behavior

The fix merged by #774 was overwritten by #1258 

## Possible Solution

Revert the regression

**Comment by TheZ3ro** [comment]
What about saving the configuration in reverse order instead of reversing it at opening?

**Comment by michaellass** [comment]
I think that's a valid strategy as well. I'm currently creating a pull request with such a change.
