### ISSUE TITLE
Attempting to download the favicon of a particular website disables the button permanently for all entries

### ISSUE THREAD

**Issue by N3pp** [keepassxreboot/keepassxc#1573]
## Expected Behavior
If a favicon download can't be completed for a determined period of time, it should be terminated and an error message should be displayed.

## Current Behavior
When I click "Download favicon", nothing happens and the button stays grayed out permanently for all entries until I restart KeePassXC. After the bug occurs, the "X" button doesn't actually close the program, KeePassXC keeps running in the background so I have to kill the process from the task manager in order to restart it (single instance option is enabled).

The bug only occurs for one particular website and it happens every time I try, whether the "Use Google as fallback for downloading website icons" option is enabled or not. I can download the websites favicon (https://www.gittigidiyor.com/favicon.ico) and add it to the entry manually without problem.

## Steps to Reproduce (for bugs)
1. Create a new entry for "https://www.gittigidiyor.com/".
2. Click "Download favicon" button.

## Debug Info
KeePassXC - Version 2.3.0
Revision: 4c0ed74

Libraries:
- Qt 5.10.1
- libgcrypt 1.8.2

Operating system: Windows 10 (10.0)
CPU architecture: x86_64
Kernel: winnt 10.0.16299

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by ente76** [comment]
I confirm this bug. Tested url: https://opentable.com. I will edit this post if I find more.

KeePassXC - Version 2.3.0
Revision: 4c0ed74

Libraries:
- Qt 5.10.1
- libgcrypt 1.8.2

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 4.15.6-1-zen

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by phoerious** [comment]
It's a problem in libcurl. The call to curl_easy_perform() simply doesn't return and the application hangs. I haven't been able to find out why, but I can reproduce it with both Windows builds and Linux builds in WSL. I'll try to debug more on native Linux tomorrow.

**Comment by droidmonkey** [comment]
Can we implement a timeout on the asynctask? I believe curl also has a timeout but I thought I implemented that attribute.

**Comment by phoerious** [comment]
The curl timeout is set, but it's not triggered, because it's curl itself that hangs, not the website. The curl command line utility works, surprisingly.

**Comment by phoerious** [comment]
I submitted a patch which fixes the problem.
