### ISSUE TITLE
Add documentation about database migration to KDBX 4

### ISSUE THREAD

**Issue by CorePoint** [keepassxreboot/keepassxc#1577]
It's not really clear how to go about migrating to KDBX 4.

Do you just change the Key Derivation Function to one of the ones only available with KDBX 4, or do you create a new database and import your entries?
I could find out by trying, but i think it would be good to have documentation about that, maybe in the FAQ.

Also thank you for this fork and thank you to all the contributers. I and many others appreciate your efforts!

**Comment by phoerious** [comment]
Yes, just change the KDF.

**Comment by TheZ3ro** [comment]
We should add this to the FAQ

**Comment by CorePoint** [comment]
So do you want to have this under the general section of the FAQ?
I could add it and make a PR.

**Comment by CorePoint** [comment]
Alright, thanks for the quick responses.
