### ISSUE TITLE
Problem installing KeePassXC 2.3.0 via PPA on Ubuntu 16.04 and derivatives

### ISSUE THREAD

**Issue by vsvyatski** [keepassxreboot/keepassxc#1578]
## Expected Behavior
When KeePassXC is installed or updated from a previous version via the official PPA, the process should go smoothly (i.e. the installation should succeed).

## Current Behavior
It complains about inability to install libsodium23 because there is already libsodium18 in the system. As a result the installation fails. These 2 libraries conflict with each other. The latter cannot really be purged because libzmq5 depends on it (one could try to purge that one, but the chain may continue and in the end the user can get to the broken system).

## Possible Solution
According to [Launchpad](https://launchpad.net/ubuntu/+source/libsodium) libsodium23 is a part of Bionic Beaver which hasn't even been released yet. Ubuntu 16.04 and 17.10 are still using libsodium18. Isn't it a bit early to stick with libsodium23? No common user is normally sitting on some pre-released software. If libsodium23 is an absolute mandatory for KeePassXC 2.3.0 you should not add this version to the PPA and leave 2.2.4 there at least until Bionic Beaver is released.

## Steps to Reproduce (for bugs)
1. Add an official PPA of KeePassXC to your system if it is not there yet.
2. Install KeePassXC 2.3.0 from the PPA (or update from 2.2.4)
3. You will notice the problem with libsodium23 really soon. The error message states something like:
```
dpkg: error processing archive /var/cache/apt/archives/libsodium23_1.0.16-0ppa3~xenial1_amd64.deb (--unpack):
 trying to overwrite '/usr/lib/x86_64-linux-gnu/libsodium.so.23.1.0', which is also in package libsodium18:amd64 1.0.16-0ppa1~xenial1
```

## Context
Correct me if I'm wrong, but I believe that Ubuntu Xenial (16.04 LTS) is still supported (and so is 17.10). I had KeePassXC 2.2.4 working quite smoothly but then the update to v2.3.0 was suggested to me. I tried to update, but not really successfully because of libsodium23.

## Debug Info
I tried to update from 2.2.4 to 2.3.0 using the official PPA but quite unsuccessfully. I cannot provide you with the info from Help > About, because my installation is broken.

Operating system: Linux Mint 18.3 KDE Edition (derived from Ubuntu 16.04 LTS)
CPU architecture: amd64
Kernel: 4.13.0-36-generic

**Comment by RealOrangeOne** [comment]
See https://github.com/keepassxreboot/keepassxc/issues/1545
