### ISSUE TITLE
Can't open KeepassXC: GCRY_CIPHER_SALSA20 not found.

### ISSUE THREAD

**Issue by rask** [keepassxreboot/keepassxc#1580]
I installed KeepassXC using the Ubuntu/Linux instructions (PPA) provided on the KeepassXC website. After installation when I attempt to open the application I receive an error (both when using Launcher and when attempting with terminal `keepassxc` calls):

> Fatal error while testing cryptographic functions. GCRY_CIPHER_SALSA20 not found.

When opening via terminal an additional message states:

> Crypto::checkAlgorithms: GCRY_CIPHER_SALSA20 not found.

I am on Ubuntu 14.04 Trusty.

## Expected Behavior
KeepassXC should open normally.

## Current Behavior
See errors above. KeepassXC does not open.

## Steps to Reproduce (for bugs)
1. Use Ubuntu 14.04 (64bit)
2. Install KeepassXC using instructions from website (`sudo add-apt-repository ppa:phoerious/keepassxc && sudo apt-get update && sudo apt-get install keepassxc`)
3. Attempt to launch KeepassXC either via GUI Launcher or via Gnome Terminal.

## Context
Would like to open KeepassXC to manage my secrets.

## Debug Info
KeePassXC - `2.3.0-0ppa1~trusty1`
Libraries: (Please tell me how to check the libraries)

Operating system: Ubuntu 14.04
CPU architecture: 64bit
Kernel: 4.4

Enabled extensions: What extensions?

**Comment by seatedscribe** [comment]
I must confirm this is a "regression" I had myself and is really simple to solve. After having updated my system with newest PPA provided, this popped up again.

As stated in my previous reply [here](https://github.com/keepassxreboot/keepassxc/issues/1417#issuecomment-362944704) in order to have KXC up and running you need to perform a couple commands (as root) to update the run-time linker.
Since the new PPA introduces a different /opt path, my previous proposed wiki modification needs to be updated accordingly. I will post it here (just in case @phoerious wanted to put it in the official wiki page and avoid further issue reports :smiley:) :

**------ start of wiki code ------**
You also need to update library bindings in order for the program to start correctly OS-wide:

**[as root]**

- `echo "/opt/keepassxc-libs/lib/x86_64-linux-gnu" > /etc/ld.so.conf.d/gcrypt20-18.conf`
- `ldconfig`
- `ldconfig -p |grep libgcrypt `should give something like this:
   libgcrypt.so.20 (libc6,x86-64) => /opt/keepassxc-libs/lib/x86_64-linux-gnu/libgcrypt.so.2
   libgcrypt.so.20 (libc6,x86-64) => /lib/x86_64-linux-gnu/libgcrypt.so.20
   libgcrypt.so (libc6,x86-64) => /opt/keepassxc-libs/lib/x86_64-linux-gnu/libgcrypt.so
   libgcrypt.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libgcrypt.so

**------ end of wiki code ------**

**Comment by phoerious** [comment]
It *should* work without those changes, since the keepassxc binary has explicit rpaths set.

**Comment by seatedscribe** [comment]
Maybe because you need to update CMAKE_INCLUDE_PATH and CMAKE_LIBRARY_PATH to the new /opt/keepassxc-libs directory?

**Comment by seatedscribe** [comment]
Yes, just recompiled and can confirm that the ldconfig part is unneeded - as long as the paths are consistent.

**Comment by seatedscribe** [comment]
By the way,
which is the stable branch that can be installed in the system? It seems that the yellow warning is present in each one so far...

**Comment by phoerious** [comment]
The keepassxc package from the PPA should not show a warning.

**Comment by seatedscribe** [comment]
> Yes, just recompiled and can confirm that the ldconfig part is unneeded - as long as the paths are consistent.

Er, well, not so fast. executable in the build directory works fine, but the system-installed not.
It seems that rpaths are cut when doing `make install` (thus making ldconfig steps needed again -- sorry for the confusion)

> Installing: /usr/local/bin/keepassxc
-- Set runtime path of "/usr/local/bin/keepassxc" to ""
-- Installing: /usr/local/lib/x86_64-linux-gnu/keepassxc/libkeepassx-autotype-xcb.so
-- Set runtime path of "/usr/local/lib/x86_64-linux-gnu/keepassxc/libkeepassx-autotype-xcb.so" to ""
-- Installing: /usr/local/bin/keepassxc-cli
-- Set runtime path of "/usr/local/bin/keepassxc-cli" to ""

**Comment by phoerious** [comment]
The package from the PPA should have rpaths set. I just confirmed it by installing it on Xenial.

**Comment by rask** [comment]
I have the following installed: `libgcrypt20:amd64` (from base repos) and `libgcrypt20-18:amd64` (from KeepassXC repo). Additionally there are some `libgcrypt11` packages installed. Would having both `libgcrypt20` packages installed introduce issues similar to what I'm experiencing?

The base repo version is 1.6.1 and KeepassXC repo version is 1.8.1.

This data is from `dpkg -l | grep gcrypt`.

Following the `ldconfig` steps provided by @seatedscribe did not fix the issue for me.

**Comment by phoerious** [comment]
It will load the first one. libgcrypt11 is too old, but can be installed alongside libgcrypt20 (it's a dependency of many Trusty packages). The upstream libgrcrypt20 version, however, is too old as well. That's why we ship our own version in /opt/keeassxc-libs.

You can try starting `keepassxc` like so:
```
LD_LIBRARY_PATH="/opt/keepassxc-libs/lib/x86_64-linux-gnu" keepassxc
```

or set LD_LIBRARY_PATH as a global environment variable.

**Comment by phoerious** [comment]
BTW I tested the keepassxc package from the PPA in a Trusty machine and it works without modifications.

**Comment by rask** [comment]
Okay, I'll try and see whether that suggestion works, maybe even try removing the base repo package and see what happens. Will return with results later.

**Comment by rask** [comment]
I removed and purged the upstream `libgcrypt20` (not `-18`) but still received errors about SALSA20 not being available. I checked with `ldd $(which keepassxc)` and noticed that KeepassXC is attempting to load the `libgcrypt11` libraries instead of `20-18`. Is this normal? I tried removing KeepassXC and reinstalling it in case it had some faulty dependencies configured from before but no change, still keeps loading the `11` version.

I'm not that comfortable removing `libgcrypt11` as so many Trusty packages seem to depend on it.

`ldd $(which keepassxc) | grep gcrypt`:

    libgcrypt.so.11 => /lib/x86_64-linux-gnu/libgcrypt.so.11 (0x00007f4a04778000)

`ldconfig -p | grep gcrypt`:

    libgcrypt.so.20 (libc6,x86-64) => /opt/keepassxc-libs/lib/x86_64-linux-gnu/libgcrypt.so.20
    libgcrypt.so.20 (libc6,x86-64) => /usr/local/lib/libgcrypt.so.20
    libgcrypt.so.11 (libc6,x86-64) => /lib/x86_64-linux-gnu/libgcrypt.so.11
    libgcrypt.so.11 (libc6) => /lib/i386-linux-gnu/libgcrypt.so.11
    libgcrypt.so (libc6,x86-64) => /usr/local/lib/libgcrypt.so
    libgcrypt.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libgcrypt.so

`apt-cache rdepends libgcrypt11` returns many pages worth of packages, already removed some of those that I do not use anymore but so many basic tools and so on depend on it.

When I check `apt-cache rdepends libgcrypt20-18` I get a list as follows:

    libgcrypt20-18
    Reverse Depends:
      libgcrypt20-18:i386
      libgcrypt20-18:i386
      keepassxc-beta
      libgcrypt20-18-dev
      keepassxc

Running with `LD_LIBRARY_PATH` set as such:

    LD_LIBRARY_PATH="/opt/keepassxc-libs/lib/x86_64-linux-gnu" keepassxc

Results in the same error of SALSA20 not found.

**Comment by rask** [comment]
I installed 2.3.0 from the Ubuntu PPA on my other computer now and otherwise it works but I can't find the settings view for browser connectivity (will create a separate issue about this if I can't get it working).

Same Ubuntu 14.04 version but different PC, and of course a bit different package and software setup.

`ldconfig -p | grep gcrypt`:

    libgcrypt.so.20 (libc6,x86-64) => /lib/x86_64-linux-gnu/libgcrypt.so.20
    libgcrypt.so.11 (libc6,x86-64) => /lib/x86_64-linux-gnu/libgcrypt.so.11

`ldd $(which keepassxc) | grep gcrypt`:

    libgcrypt.so.20 => /opt/keepassxc-libs/lib/x86_64-linux-gnu/libgcrypt.so.20 (0x00007fe41e7f0000)

`apt-cache rdepends libgcrypt20-18` returns the same as the other Ubuntu PC which I posted earlier.

`dpkg -l | grep libgcrypt`:

    ii  libgcrypt11:amd64     1.5.3-2ubuntu4.5        amd64  LGPL Crypto library - runtime library
    ii  libgcrypt20:amd64     1.6.1-2ubuntu1.14.04.1  amd64  LGPL Crypto library - runtime library
    ii  libgcrypt20-18:amd64  1.8.1-0ppa2~trusty1     amd64  LGPL Crypto library - runtime library

So, on this other Ubuntu 14.04 system the `20`, `20-18`, and `11` versions of the library can coexist without breaking anything.

**Comment by phoerious** [comment]
Browser is not supported on Trusty. Use the AppImage if you need it.

**Comment by rask** [comment]
Ah OK. I presume in the wake of all my issues I will wait until I can manage to get either 17.10 or 18.04 installed and install KeepassXC in there. Trusty is getting old for desktop usage in anycase.

I will return if I manage to get this working on the other PC so I can share the steps I took. Might be something really small that I'm missing.

Thanks!
