### ISSUE TITLE
TOTP: Italian string for Steam option is wrongly translated

### ISSUE THREAD

**Issue by lucavallerini** [keepassxreboot/keepassxc#1581]
I was trying to set TOTP for a Steam entry in my DB. I had a bit of a problem to do it because I couldn't find the appropriate setting. Then I spotted the second option in the TOTP dialog and I wondered what it meant. Finally I realized that "Steam" was translated ("vapore") and that it is in fact the correct option to set TOTP for a Steam entry.

![totp_dialog](https://user-images.githubusercontent.com/2808166/36841364-6231122e-1d48-11e8-9c74-cd9311b76d8d.png)

## Expected Behavior
The string should be: "Impostazioni del token di Steam".

## Current Behavior
The string for the second option is currently: "Impostazioni del token di vapore". "Steam" has been translated. It should be kept untranslated.

## Possible Solution
Change the translation to "Impostazioni del token di Steam".

## Steps to Reproduce (for bugs)
Try to add a TOTP for an entry. The second option on the dialog window is wrongly translated in Italian.

## Debug Info
KeePassXC - Version 2.3.0
Revision: 4c0ed74
Distribution: AppImage

Libraries:
- Qt 5.9.4
- libgcrypt 1.8.1

Operating system: Fedora 27 (Twenty Seven)
CPU architecture: x86_64
Kernel: linux 4.15.4-300.fc27.x86_64

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by phoerious** [comment]
Please head over to Transifex and correct the problem: https://www.transifex.com/keepassxc/keepassxc
Translations are not managed in the source repository.

Thanks!

**Comment by lucavallerini** [comment]
Done.

**Comment by phoerious** [comment]
Thanks!
