### ISSUE TITLE
Cannot open DB in Ubuntu 16.04 - KeepassXC 2.3.0 (installed via PPA)

### ISSUE THREAD

**Issue by qazip** [keepassxreboot/keepassxc#1582]
Whenever I try to open my DB, after writing my password and choosing my keyfile (2FA), nothing happens. It just keeps on loading but the DB never gets opened. 

Here is the output I get:

```
(keepassxc:8): GConf-WARNING **: Client failed to connect to the D-BUS daemon:
Failed to connect to socket /tmp/dbus-n6IQBulSDz: Connection refused
qt5ct: D-Bus system tray: no
libGL error: failed to open drm device: No such file or directory
libGL error: failed to load driver: i965
```

## Debug Info
KeePassXC - Version 2.3.0
Revision: 4c0ed74

Libraries:
- Qt 5.5.1
- libgcrypt 1.8.1

Operating system: Linux 4.4.0-116-generic
CPU architecture: x86_64
Kernel: linux 4.4.0-116-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by droidmonkey** [comment]
Please use the snap.

**Comment by qazip** [comment]
@droidmonkey , why?

**Comment by phoerious** [comment]
You may also try the AppImage instead.

**Comment by qazip** [comment]
I am really confused here. Are you aware of this bug? Are you going to fix it?

The first thing I get, after reporting it, is "Use the snap". And the second comment is "or the Appimage".

**Comment by phoerious** [comment]
This sounds like a deployment or possibly a Qt bug. Please try if it works with the AppImage, which ships its own libraries.

**Comment by qazip** [comment]
@phoerious, it works with snap. But I don't like snap so I went back to keepassX for the time being.

**Comment by phoerious** [comment]
Most likely a problem with your Qt installation then. 
The AppImage integrates a little better than the Snap IMHO.

**Comment by TheZ3ro** [comment]
I have your same setup (other than an updated kernel) and my database doesn't have a keyfile and I cannot reproduce.

Anyway you have a problem with DBus, check if it's working correctly `service dbus status`.
Also a `dmesg` or `error.log` could be useful.

Another thing, DBus sets some env variables to run. Try restarting your env or using another user

**Comment by qazip** [comment]
Ok, it works now. Reinstalling seems to have fixed the problem, somewhy? I'll close this.
