### ISSUE TITLE
Can't type a caret (^) in password field with a german keyboard on ubuntu

### ISSUE THREAD

**Issue by konstin** [keepassxreboot/keepassxc#1583]
In keepassx, I could enter enter a caret as character in password for my kdbx file by pressing the associated key once. With keepassxc, I can't enter a caret no matter how often I press that key.

## Expected Behavior
I can type a caret by pressing the associated key once or twice.

## Current Behavior
I can't type a caret. 

## Steps to Reproduce
1. Select the German keyboard layout
1. Open keepassxc
2. Select any kdbx file
3. Try to type a caret in the password field by pressing the associated key (It is normally right below the esc-key)

## Debug Info
KeePassXC 2.3.0, installed as snap

Operating system: Ubuntu 17.10
CPU architecture: x86-64bit
Kernel: 4.13.0-32-generic

**Comment by droidmonkey** [comment]
This is likely due to the snap not recognizing that you have a German keyboard layout.

**Comment by phoerious** [comment]
Can you try the AppImage or even better the PPA version?

**Comment by konstin** [comment]
I've tried the ppa version and it works indeed. This is weird as any other key I've tried works as expected for a German keyboard.

**Comment by droidmonkey** [comment]
I do not think there is anything we can do about this since other special characters work. My recommendation is to remove the caret character from your password.
