### ISSUE TITLE
Changing the name of database file renders it unable to be opened with YubiKey

### ISSUE THREAD

**Issue by L0rdBootysniffer** [keepassxreboot/keepassxc#1584]
I made a test file with random characters for trying out 2.3.0. I then manually moved my passwords into that database file for permanent usage. Afterwards, I changed the filename to passwords.kdbx, and now I cannot unlock it with my YubiKey. I get "Unable to open the database. Wrong key or database file is corrupt. (HMAC mismatch)"

## Expected Behavior
I expected the YubiKey to work on the database because I only changed the filename.

## Current Behavior
I changed the filename this morning to passwords.kdbx, and now I cannot unlock it with my YubiKey. I get "Unable to open the database. Wrong key or database file is corrupt. (HMAC mismatch)"

## Steps to Reproduce (for bugs)
1. Create KDBX4 database file with YubiKey authentication
2. Make some changes to it
3. Save it
4. Rename the file to something else

## Debug Info
KeePassXC - Version 2.3.0
Revision: 4c0ed74

Libraries:
- Qt 5.10.1
- libgcrypt 1.8.2

Operating system: Windows 10 (10.0)
CPU architecture: x86_64
Kernel: winnt 10.0.16299

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by phoerious** [comment]
Renaming the file has no effect on its contents. You probably forgot to tick the challenge response checkbox on the unlock dialog (which isn't ticked automatically anymore after a rename).

**Comment by L0rdBootysniffer** [comment]
I definitely ticked the challenge response checkbox. This happens after it tells me to touch my YubiKey, and the YubiKey itself is displaying in the Challenge Response drop menu.

**Comment by phoerious** [comment]
It has nothing to do with renaming the file. If anything goes wrong, it's got to do making changes to the file itself.

Were you using KDBX 3 or KDBX 4? If you were using KDBX 3, could you please open the file in a Hex editor and paste the first 12 bytes here? They should either be

```
d903 9aa2 fb67 b54b 0001 0003
````
or
````
d903 9aa2 fb67 b54b 0000 0004
```

**Comment by L0rdBootysniffer** [comment]
You know how this works since you're a developer. I'm just simply stating my experience. The file is supposed to be KDBX4 since I'm using Argon2. I'll open the file in a hex editor here shortly when I get a chance.

**Comment by phoerious** [comment]
Can you try opening the database without the YubiKey, please?

**Comment by L0rdBootysniffer** [comment]
That worked.

**Comment by phoerious** [comment]
Okay, we are having two bugs here. First: your database was probably upgraded automatically to KDBX 4 the first time you saved it in KeePassXC 2.3, although it shouldn't have (you may have changed to Argon2 voluntarily later on). That one's addressed in #1568.
The other bug is that an automatic upgrade stripped the YubiKey from the database. I'll investigate.

**Comment by L0rdBootysniffer** [comment]
Thank you for the help and explanation. I appreciate it!

**Comment by phoerious** [comment]
Thank *you* for reporting this problem. That's quite a bug.
