### ISSUE TITLE
Right click context menu doesn't show keyboard shortcuts anymore

### ISSUE THREAD

**Issue by N3pp** [keepassxreboot/keepassxc#1588]
## Expected Behavior
I expected right click context menu to show keyboard shortcuts like it used to do in 2.2.4.

## Current Behavior
Keyboard shortcuts are not shown in the right click context menu in 2.3.0, only in the "Entries" dropdown at the top.

## Context
To be honest I'm not sure if this change is intended or not, but I didn't see anything about it in #1305 or anywhere else.

## Debug Info
KeePassXC - Version 2.3.0
Revision: 4c0ed74

Libraries:
- Qt 5.10.1
- libgcrypt 1.8.2

Operating system: Windows 10 (10.0)
CPU architecture: x86_64
Kernel: winnt 10.0.16299

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by ichaushev** [comment]
It would be good if we were to get some clarification on whether this is a bug or intended. Version 2.3.4 is still affected. I personally don't see a reason to hide the shortcuts from the context menu and really miss them.

**Comment by droidmonkey** [comment]
This one slipped by me. I never noticed the shortcuts gone, that was not intentional.
