### ISSUE TITLE
Search by password

### ISSUE THREAD

**Issue by tkolo** [keepassxreboot/keepassxc#1589]
I'd be handy to have the ability to search the database by password rather than title.

## Context
My use case is as follows: I've acciedentaly pasted one of my passwords in a wrong window, effectively leaking it. It was a password from a pre-password manager era and as such it was re-used in a few places. Now I'd like to find them and reset my password there.

**Comment by TheZ3ro** [comment]
Duplicate of (already discussed) #937 

Also if #239 get's implemented it will fix this as well
