### ISSUE TITLE
Unable to open existing or new databases using yubikey 4 challenge response

### ISSUE THREAD

**Issue by spotty-dog** [keepassxreboot/keepassxc#1590]
After not touching my KPXC database for a few weeks, I tried to use it this week and was unable to open it. I use the password in combination with HMAC challenge response from slot 2 of a Yubikey 4 (firmware version 4.3.7). The error I get is:

"Unable to open the database. Wrong key or database file is corrupt."

I've got two separate backups of the file and they both fail with the same result.

I've restored the state of the Yubikey by re-entering the 20 byte code used to setup the HMAC challenge-response (previously written down in a safe place) . This has not made any difference and I'm still locked out. I've verified this restoration process works with alternate values, bring the key back from an altered state works fine with other test databases (when I've been able to open them, more to come on that).

Having run out of ideas for my original database, I tried reproducing the situation with new databases. Although it doesn't happen every time, I've had several occurrences where it has failed. Just basic creation of a new database, adding a key, save, close and the re-open KPXC leaves me locked out with the same error from above.

Whilst not very scientific, I get the feeling that double clicking on the database to open it makes the likelyhood of it being locked out much higher. As an aside, IMHO the UI around file selection is very confusing, particulary the use of a checkbox next to the file and password. It seems to me these would always be required so there's no need to require a checkbox? Plus when you double click it puts the file name in a label abover the text boxes and leaves the file box blank which seems unusual. Anwyay, I digress.....

## Steps to Reproduce (for bugs)
1 Open KPXC v2.3.0 on Linux Mint 18.2.
2.Create new database secured with password and Challenge Response
3.Add an entry
4.Save database
5. Close database
6. Attempt to open database, fail with error "Unable to open the database.
Wrong key or database file is corrupt."

## Context
I had issues with the upgrade as apt-get reported it was unable to update libsodium.so.23.1.0. That library was already present but I wanted to try the upgrade so I removed the original using apt-get and installed the update to KPXC.

I'm pretty sure the issue with my original database was there before the upgrade but I couldn't say 100% sure.

After reading some other issues on here, I checked my original database with a hex viewer and it looks like this:

"03 d9 a2 9a 67 fb 4b b5-01 00 03 00"

Which I believe means it hasn't been auto upgraded. I tried it without the yubikey too and that didn't work.

## Debug Info
KeePassXC - Version 2.3.0
Revision: 4c0ed74

Libraries:
- Qt 5.5.1
- libgcrypt 1.8.1

Operating system: Linux Mint 18.2
CPU architecture: x86_64
Kernel: linux 4.8.0-53-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by phoerious** [comment]
This is probably a different issue. Your database is indeed KDBX 3 and the error message also indicates that.
