### ISSUE TITLE
SSH Agent doesn't work with PuTTY (Windows)

### ISSUE THREAD

**Issue by domrim** [keepassxreboot/keepassxc#1593]
On Windows PuTTY isn't able to communicate with the SSH-Agent from KeePassXC.
I don't really know why, sourcetree for example works.
If you need some more analyse data, just tell me what you need ;)

**Comment by hifi** [comment]
You need to use Pageant in conjunction with KeePassXC. The SSH Agent implementation acts as a client for Pageant.

**Comment by domrim** [comment]
oh, thank you for helping!

**Comment by domrim** [comment]
I have now a problem with my keys on Windows, i'm having two keys, one ed25519 and one ecdsa-sha2-nistp521. The ecdsa key gets added correctly, after i converted the key with puttygen to the openssh-format but the ed25519 key fails with the error message "Agent refused this identity". Is this a bug in pageant or in keepassxc?

**Comment by ds77** [comment]
Do you have "Require user confirmation when this key is used" or "Remove key from agent after..." options enabled for this key? Pageant does not support SSH2_AGENTC_ADD_ID_CONSTRAINED request used for this.
