### ISSUE TITLE
Add Custom Browser option

### ISSUE THREAD

**Issue by plague-doctor** [keepassxreboot/keepassxc#1594]
## Expected Behavior
KeePassXC should copy `org.keepassxc.keepassxc_browser.json` to `~/.waterfox/native-messaging-hosts` for Waterfox.

## Current Behavior
KeePassXC creates the above mentioned file in `~/.mozilla/native-messaging-hosts` and user needs to copy/symlink the file manually into `~/.waterfox/native-messaging-hosts/`.

## Possible Solution
Add another Browser to the supported browsers list.

Operating system: LINUX

**Comment by phoerious** [comment]
I've never heard of Waterfox before. I don't think we can/should add every niche browser. I would expect users who know that these browsers exist to be technical enough to also add the manifest file manually. Maybe we could document that somewhere.

**Comment by plague-doctor** [comment]
How about adding the `Custom browser` field, where the user could specify the location and the browser (Firefox, Chromium, etc), so the KeePassXC would save the right file to?

**Comment by phoerious** [comment]
The user would need to specify the config file location, because that one's different for every browser.

**Comment by plague-doctor** [comment]
What is the default config file location for Firefox? (Maybe I've got this wrong, and that's why my Waterfox has issues...)

**Comment by phoerious** [comment]
Depends on the platform. On Linux, it's .mozilla.

**Comment by plague-doctor** [comment]
So yes, user would need to specify config file location and a browser.
The `Custom browser` would very nicely cover any niche forks of popular browsers.

**Comment by Generator** [comment]
`Custom browser` could be useful also to non-firefox/chromium forks, browsers like [Falkon](https://qupzilla.com/), [Midori](http://www.midori-browser.org/) or other browser with their own plugins

**Comment by dCo3lh0** [comment]
thanks for the tip plague-doctor. Now is working fine.

**Comment by varjolintu** [comment]
`Custom browser` options would be nice indeed.

**Comment by varjolintu** [comment]
The problem with this option is that the native messaging script files differ between Firefox and Chromium based browsers. There should be an extra option for this too and it makes it a bit ugly.

**Comment by damufo** [comment]
Please, add support for waterfox

**Comment by varjolintu** [comment]
@damufo Read the issue description. You have to copy the file manually or make a symbolic link.

**Comment by damufo** [comment]
@varjolintu
Apologies, the solution work fine.
Very thanks.

**Comment by varjolintu** [comment]
Added a pull request for this feature: https://github.com/keepassxreboot/keepassxc/pull/4148
