### ISSUE TITLE
Crash after reediting entry in large database

### ISSUE THREAD

**Issue by therealmarv** [keepassxreboot/keepassxc#1596]
## Expected Behavior
KeepassXC should work normally and allow me to save the new reedited entry

## Current Behavior
KeepassXC crashes. The same happened also with the last 2.2.x versions.
Please see my macOS crash report here also: https://gist.github.com/therealmarv/e1afee0bd9a0350d1d82d9ac87e754fe

## Possible Solution
For me it seems an error on saving, it feels like the DB is not entirely saved and I edit an entry and KeepassXC gots confused.

## Steps to Reproduce (for bugs)
I could not reproduce it on a new kdbx file, only on my old one.
Requirement: Have a big Keepass DB (I have a 6MB big file)
1. Add a new entry and generate a 25 words long password without special characters
2. Save DB
3. As fast as possible: edit password of this new entry again and add some special characters like `#-+$`
4. KeepassXC first freezes a littlebit and then crashes. The new edited password is lost.

## Context
Some times I create a password without special characters first and then want to make it more secure with certain special characters by editing the password manually.

## Debug Info
KeePassXC - 2.3.0
Revision: 4c0ed74
Crash report: https://gist.github.com/therealmarv/e1afee0bd9a0350d1d82d9ac87e754fe

Libraries:
- Qt 5.9.3
- libgcrypt 1.8.2

Operating system: macOS 10.13.3
CPU architecture: x64
Kernel: Darwin Kernel Version 17.4.0

Enabled extensions (but I don't use them at all):
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by droidmonkey** [comment]
This crash actually occurs due to an access error on the attributes map (the password re-edit is a red herring). Without any further information it might be impossible to figure out the true fault. Can you try recreating the entry that crashes in the new database?

**Comment by julian-klode** [comment]
I can reproduce this just by opening the entry and clicking OK in a loop, on an entry I generated solely for debugging, and without any changes.

Basically positioning my mouse where the OK button is, the keyboard on the entry, and then pressing OK and clicking in a loop, which gets really fast.

**Comment by julian-klode** [comment]
(that's on Ubuntu 18.04 and to-be-18.10)

**Comment by therealmarv** [comment]
So this issue is fixed?
I still have this issue but it is not easy reproducible (and I do not want to share my private keyfile for sure). The good thing is that my keypass db was never corrupted after the crash.

**Comment by droidmonkey** [comment]
Will be addressed by #3353
