### ISSUE TITLE
Support KeePassXC-Browser in Snaps

### ISSUE THREAD

**Issue by freelock** [keepassxreboot/keepassxc#1598]
With the new KeePassXC 2.3.0, my snap install automatically updates, and warns me about KeePassHTTP, provides a nice link to the migration guide to change to KeePassXC-Browser.

However, when I follow the first step on these instructions, I get the warning:

> We're sorry, but KeePassXC-Browser is not supported for Snap releases at the moment.

## Expected Behavior

Support KeePassXC-Browser.

## Steps to Reproduce (for bugs)

1. Open Tools -> Settings
2. Click "Browser Integration"
3. See "not supported" message.

## Context

I wasn't aware of this change -- which seems like a great addition -- but searching the issue queue, I'm not finding any issue for it. Is this the right place?

I basically want to subscribe to an issue so I know when this feature is complete!

## Debug Info

KeePassXC - Version 2.3.0
Revision: 4c0ed74
Distribution: Snap

Libraries:
- Qt 5.7.1
- libgcrypt 1.7.6-beta

Operating system: Ubuntu Core 16
CPU architecture: x86_64
Kernel: linux 4.4.0-116-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by phoerious** [comment]
We're having difficulties connecting Snaps through native messaging with the browser extension and haven't been able to find a solution yet. If you require KeePassXC-Browser, please use the AppImage or the version from the PPA.

**Comment by hackel** [comment]
Please do not remove KeePassHTTP support until this critical issue is resolved.  It looks like it may require writing a snap interface just for keepassxc-proxy.

Hopefully browsers will add dbus support to their Native Messaging API to avoid this whole mess.  Could something like [systemd-bus-proxyd](http://man7.org/linux/man-pages/man8/systemd-bus-proxyd.8.html) be used to do this?

**Comment by droidmonkey** [comment]
To be clear, the browser feature works just fine with snaps. However, you cannot install the native messaging json file from the KeePassXC snap due to sandboxing. My idea to solve this is to have snap users download a separate script executed outside the snap env that will install the necessary native messaging json files for your browser.

**Comment by droidmonkey** [comment]
I haven't worked on it yet, but its in the pipeline.

**Comment by alexanderadam** [comment]
Is the [Snap helper script](https://raw.githubusercontent.com/keepassxreboot/keepassxc/master/utils/keepassxc-snap-helper.sh) properly documented? It would be great if Snap could be detected and KeePassXC would show a hint that's very present.

Also is this related to issues like [405](https://github.com/keepassxreboot/keepassxc-browser/issues/405), [2930](https://github.com/keepassxreboot/keepassxc/issues/2930), [4353](https://github.com/keepassxreboot/keepassxc/issues/4353), [2890](https://github.com/keepassxreboot/keepassxc/issues/2890) or [3741](https://github.com/keepassxreboot/keepassxc/issues/3741)?

And it's basically the same issue with Flatpak ([29](https://github.com/flathub/org.keepassxc.KeePassXC/issues/29), [92](https://github.com/xhorak/firefox-devedition-flatpak/issues/92), [2656](https://github.com/keepassxreboot/keepassxc/issues/2656), [1621763](https://bugzilla.mozilla.org/show_bug.cgi?id=1621763)), isn't it?

**Comment by erik78se** [comment]
Does the snap version still require this hack? I'm trying to get the browser integration to work, but I'm not sure what the path is or if I should just stop using the snap version?

**Comment by droidmonkey** [comment]
Yes this is still required and the Browser Plugin settings page tells you what to do. You can also just go to our downloads page and grab the script: https://keepassxc.org/download/

**Comment by siddolo** [comment]
Why was this issue marked as fixed? browser snaps are not yet supported

```
askBrowserSnap() {
    if (whiptail --title "Snap Choice" --defaultno \
            --yesno "Is this browser installed as a snap (usually NO)?" 8 60); then
        # BASE_DIR="$1"
        whiptail --title "Snap Choice" --msgbox "Sorry, browsers installed as snaps are not supported at this time" 8 50
        exit 0
    fi
}
```

**Comment by droidmonkey** [comment]
It is impossible to support native messaging when a browser is running as a sandboxed snap. This is a limitation in snapd not keepassxc. That is also not what this issue is about.
