### ISSUE TITLE
Unable to install keepassxc on Ubuntu 16.04.4

### ISSUE THREAD

**Issue by tominglis** [keepassxreboot/keepassxc#1599]
I had keepassxc installed on my Ubuntu 16.04.4 system using the ppa.

When you released the new 2.3.0 version yesterday and I tried to update, it didn't work.

It complains that the version of libsodium23 it would install tries to install a file over a file alread installed by an existing package libsodium18, which I've checked is being used by a number of important pieces of software I have installed like flowblade, handbrake-gtk, and openshot.

I am not able to get past this issue so have had to remove keepassxc and revert to keepassx. :-(

**Comment by phoerious** [comment]
Please apply the solution in https://github.com/keepassxreboot/keepassxc/issues/1545#issuecomment-369163954
