### ISSUE TITLE
Error near the end of build process "no LC_RPATH load command with path"

### ISSUE THREAD

**Issue by lbkvu** [keepassxreboot/keepassxc#1601]
## Expected Behavior

Build successfully without error

## Current Behavior

Near the end of the build process, the following error appears:
CPack: Create package using DragNDrop
CPack: Install projects
CPack: - Run preinstall target for: KeePassXC
CPack: - Install project: KeePassXC
CPack: -   Install component: Runtime
**error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/install_name_tool: no LC_RPATH load command with path: /usr/local/lib found in: /Users/william/Documents/project/keepassxc/build/_CPack_Packages/OSX/DragNDrop/KeePassXC-2.3.0/ALL_IN_ONE/./KeePassXC.app/Contents/MacOS/KeePassXC (for architecture x86_64), required for specified option "-delete_rpath /usr/local/lib"
CPack: -   Install component: Unspecified**
CPack: Create package
CPack: - package: /Users/william/Documents/project/keepassxc/build/KeePassXC-2.3.0.dmg generated.
## Steps to Reproduce (for bugs)

1. Get the latest source code from repo
2. Run the following cmake
cmake -DCMAKE_OSX_ARCHITECTURES=x86_64 -DCMAKE_BUILD_TYPE=Release -DKEEPASSXC_BUILD_TYPE=Release -DWITH_XC_AUTOTYPE=ON -DWITH_XC_NETWORKING=ON -DWITH_XC_BROWSER=ON -DWITH_XC_SSHAGENT=ON -DCMAKE_PREFIX_PATH=/usr/local/Cellar/qt5/5.10.0_1/lib/cmake ..
3. Run the following make
make -j8 package
4. The above error appears

## Debug Info

KeePassXC - VERSION: 2.3.0

Operating system : Mac OS 10.13.3
CPU architecture: Darwin MacbookPro 17.4.0 Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64

**Comment by phoerious** [comment]
Make sure you have the Xcode command line tools installed.

**Comment by lbkvu** [comment]
I've already had it
```
xcode-select -p
/Applications/Xcode.app/Contents/Developer
```

**Comment by romanwue** [comment]
What is the solution?

**Comment by droidmonkey** [comment]
You need the install_name_tool in your LC_RPATH

**Comment by romanwue** [comment]
And where do I need to set the LC_RPATH? I have a default Xcode installation, default Qt and CMake installation

**Comment by droidmonkey** [comment]
After you upgrade to Catalina you need to install the tools again. This isn't a problem with KeePassXC build process.

**Comment by romanwue** [comment]
Is the LC_RPATH an environment variable? how should it look like?

**Comment by droidmonkey** [comment]
I don't know anything about it, that's just the error msg.

**Comment by wgrand** [comment]
Like @romanwue, I am using a default Qt and CMake installation. I am on macOS Monterrey. @droidmonkey said to look at `LC_RPATH`, but because we are using default configurations, we shouldn't have to modify `LC_RPATH` manually. Instead of reinstalling xcode build tools, I called `sudo xcode-select --reset` to reset the paths, and the problem went away.

**Comment by joytry1** [comment]
Set env `DYLD_LIBRARY_PATH` is work for me

**Comment by davidbitton** [comment]
> Set env `DYLD_LIBRARY_PATH` is work for me

What value did you use?

**Comment by Ashwin-Balaje** [comment]
I set it using this command, using the library folder of VulkanSDK, which I was using for the project:
`export DYLD_LIBRARY_PATH=/path/to/your/library/directory:$DYLD_LIBRARY_PATH`
