### ISSUE TITLE
Version 2.3.0 64-bit fails to run on Windows 10

### ISSUE THREAD

**Issue by syxolk** [keepassxreboot/keepassxc#1602]
Just upgraded KeepassXC from version 2.2.4 to 2.3.0 on my Windows 10 and it crashed before any application window starts to show up. I noticed that this only occurs for the 2.3.0 64-bit version.

However, I noticed the following versions are working:
- KeepassXC version 2.2.4 64-bit
- KeepassXC version 2.3.0 32-bit

## Expected Behavior

Application window shows up and is running.

## Current Behavior

KeepassXC fails to start and shows these two message boxes:

![image](https://user-images.githubusercontent.com/6666063/36918747-2f03aee8-1e5b-11e8-9861-8c881c369f93.png)
![image](https://user-images.githubusercontent.com/6666063/36918823-6b8e83e2-1e5b-11e8-8d29-217425a0814a.png)

There is no additional output when run in Powershell.

## Possible Solution

Which version of the Visual C++  Runtime Library is required?

## Steps to Reproduce (for bugs)

1. Install `KeePassXC-2.3.0-Win64.exe` on Windows 10
2. Run KeePassXC
3. Two error messages should pop up.

## Debug Info

**This is the working 32-bit version:**

KeePassXC - Version 2.3.0
Revision: 4c0ed74

Libraries:
- Qt 5.10.1
- libgcrypt 1.8.2

Operating system: Windows 10 (10.0)
CPU architecture: x86_64
Kernel: winnt 10.0.16299

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by hifi** [comment]
I can confirm this on Windows 10 Pro 64-bit.

**Comment by hifi** [comment]
Ok, so here's what I have now: if you delete this file: `imageformats/qsvg.dll` it works for me, can you confirm @syxolk if it also fixes it for you?

Not everyone can reproduce this issue so I wonder what our systems have in common? This is a fairly stock Windows 10 Pro 64-bit as a KVM virtual machine spun up with libvirt.

**Comment by phoerious** [comment]
I can reproduce it when I add Qt5Svg.dll to my installation. Weird that this issue occurs on your systems, because that file is not part of the Windows distribution.
I suggest we remove the qsvg.dll image format for now and fix this in 2.4. The plugin cannot work without Qt5Svg.dll anyway.

**Comment by syxolk** [comment]
@hifi Yes, deleting `imageformats/qsvg.dll` works for me. Thanks!

@phoerious Thanks for fixing it 👍

**Comment by john3voltas** [comment]
I stand confused. Is this supposed to be fixed on the current 2.3.1? Or will it only be fixed on 2.4.x and the current workaround is still to delete qsvg.dll?
I'm asking because I'm on 2.3.1 and I'm still experiencing this issue.

**Comment by droidmonkey** [comment]
@john3voltas you are experiencing a separate issue. I recommend a complete uninstall and install.

**Comment by john3voltas** [comment]
@droidmonkey I am sorry to say but on 1 of my 2 installs of KeepassXC, I am still getting errors after uninstall/reinstall. My Windows 7 box got fixed by uninstalling/reinstalling but my Windows 10 VM still complains about it.
Taken from my VM's event viewer:

> Application popup: Auto-Type - KeePassXC: Windows - Application Error : The instruction at 0x0000000066767002 referenced memory at 0x000000000000000C. The memory could not be written.

I think this symptom is similar to the one that was reported in the first post.
Can you please comment?
Thanks in advance.
Cheers

**Comment by droidmonkey** [comment]
The crash with autotype was also fixed in 2.3.1, am I right @phoerious? This may be a new issue with Win10 in a VM.

**Comment by john3voltas** [comment]
Actually, from what I've been able to understand, KeepPassXC only crashes when I trigger an autotype.
The autotype works but some 15 seconds later KeePassXC crashes with the error message that I posted before.
Is this the bug you were asking @phoerious if it had been fixed in 2.3.1?
TIA
Cheers

**Comment by phoerious** [comment]
The Auto-Type crash is fixed in 2.3.2 (not yet released).

**Comment by john3voltas** [comment]
Ahh...ok, thanks everybody.
