### ISSUE TITLE
Doesn't Work With Current Firefox Version ESR

### ISSUE THREAD

**Issue by KitchM** [keepassxreboot/keepassxc#1604]
Cannot find the browser add-on.

KeePassXC - Version 2.3.0
Revision: 4c0ed74

Libraries:
    Qt 5.2.1
    libgcrypt 1.8.1

Operating system: Xubuntu 14.04
CPU architecture: AMD 64-bit
Kernel: Latest

**Comment by varjolintu** [comment]
Duplicate issue with https://github.com/keepassxreboot/keepassxc-browser/issues/26.
