### ISSUE TITLE
Can't Find Database

### ISSUE THREAD

**Issue by KitchM** [keepassxreboot/keepassxc#1605]
Under:
"Connected Databases
The following KeePassXC databases are connected to KeePassXC-Browser."
nothing happens when selecting  "Connect".

This is particularly odd since the database is currently open.

I should not even have to select the "Connect" button; it should have seen it anyway.  But in lieu of that, it should allow a person to search for the database.  That doesn't work either.

KeePassXC - Version 2.3.0
Revision: 4c0ed74

Libraries:
- Qt 5.2.1
- libgcrypt 1.8.1

Enabled extensions:
- Auto-Type
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

Operating system: Xubuntu 14.04
CPU architecture: AMD 64-bit
Kernel: Latest

**Comment by varjolintu** [comment]
Does the popup have any messages? Settings page always has the Connect button visible.

**Comment by Generator** [comment]
This is the same issue as #1606, KeePassXC wasn't build with `Browser Integration`
