### ISSUE TITLE
KeePassXC Key derivation may cause incompatibility with other ports

### ISSUE THREAD

**Issue by Generator** [keepassxreboot/keepassxc#1617]
KeePassXC key derivation may cause some incompatibles with other KeePass ports, making impossible to open.

## Expected Behavior

Database created or modified settings should work with any KeePass 2.x

## Current Behavior

Different database configurations changed with KeePassXC makes it incompatible with KeeWeb (probably some other ports)
See KeeWeb [#883](https://github.com/keeweb/keeweb/issues/883)

## Steps to Reproduce (for bugs)

1. Create or modify a database encryption settings 
2. Open the created/modified database with (KDBX 4 compatible) unofficial KeePass port (e.g. [KeeWeb](https://github.com/keeweb/keeweb) <=1.6.3)

## Context

Trying to open a database in other devices with different or no KeePass port installed (web client), but incompatibility make it impossible.

## Debug Info
KeePassXC - Version 2.3.0
Revision: 4c0ed74

Libraries:
- Qt 5.10.1
- libgcrypt 1.8.2

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 4.14.23-1-lts

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by droidmonkey** [comment]
Our key derivation function is exactly the same as KeePass 2.x

**Comment by TheZ3ro** [comment]
I've just tried the following:

KDBX3.1 converted to KDBX4(Argon2 + ChaCha20) with KeePassXC (Settings: 10 transformation round, 20MB memory, 4 Threads. recommended after 1-second delay benchmark)

KeePass opens the file just fine
KeeWeb from browser at beta.keeweb.info fails with Quota Exceeded

Changed KDBX4 settings from KeePass to 419 iteration, 1MB, 2 Threads (recommended after 1-second delay benchmark :smile: )

KeePassXC opens fine
KeeWeb from browser at beta.keeweb.info fails with Quota Exceeded

**Comment by Generator** [comment]
Weird, using the same settings defined with KeePass2 i have no issues, but if defined with KeePassXC creates incompatibility

**Comment by TheZ3ro** [comment]
Are you using the same KDBX from the KeeWeb issue?
Can you upload a KeePassXC-failing KDBX?

**Comment by Generator** [comment]
Yes, it's the same settings, same issue. 
Only works with KeeWeb if i change the encrypt settings with KeePass2
[issued-database.kdbx.tar.gz](https://github.com/keepassxreboot/keepassxc/files/1777838/issued-database.kdbx.tar.gz)
Password: keeweb

**Comment by droidmonkey** [comment]
I can't reproduce your issue at all. I changed AES params, changed to Argon2, etc. Opened every time in keeweb.

**Comment by TheZ3ro** [comment]
Downloaded the database, opened with KeePass 2.38, changed KDF to Argon2: 2 iteration, 1MB, 2 Thread (default settings) saved.
KeePassXC open the file without problems, KeeWeb opens.

If I try with my previous db, set to the same settings, KeeWeb fails.

Anyway KeePass always open it, no matter what so I think it's a KeeWeb issue

**Comment by phoerious** [comment]
Quota exceeded most likely means that you are running out of memory or processing is taking too long. Or native implementation is just a lot faster than KeeWeb and Argon2 ist designed to be memory hard. So you having trouble opening it in KeeWeb if you benchmarked it to 1 second in KeePassXC, is to be expected. KeePass 2 is also a lot slower than KeePassXC.
