### ISSUE TITLE
Why numeric characters are not allowed at syntax checking for auto-typin?

### ISSUE THREAD

**Issue by cougar-b** [keepassxreboot/keepassxc#1630]
Is there any reason why numeric characters are not included in the regexp pattern ```normalCommands``` at ```AutoType::checkSyntax()``` ?

I'm referring the source code: https://github.com/keepassxreboot/keepassxc/blob/develop/src/autotype/AutoType.cpp#L655

## Expected Behavior (Why I am asking this)
I wanted fill the form with auto-typing which have a card number field as 3 separated input fields.
So I created custom attributes that named 'CardNumber1', 'CardNumber2' and 'CardNumber3'
with Auto-Type sequence ```{S:CardNumber1}{TAB}{S:CardNumber2}{TAB}{S:CardNumber3}{ENTER}```.

## Current Behavior
With the above configuration if I launch auto-typing the following error message will be shown:
```The syntax of your Auto-Type statement is incorrect```

## Debug Info
KeePassXC - 2.3.0

KeePassXC - Version 2.3.0
Revision: a06e85f

Libraries:
- Qt 5.10.1
- libgcrypt 1.8.2

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 4.15.6-1-ARCH

Enabled extensions:
- Auto-Type
- SSH Agent
- YubiKey

**Comment by TheZ3ro** [comment]
Fixed in #1626
It will be available in version 2.3.1

**Comment by cougar-b** [comment]
Oops, my bad!
You've already changed the code.
Thank you for the working :+1:

**Comment by TheZ3ro** [comment]
No problem :smile: just wait for the next release `2.3.1` and sorry about the regression
