### ISSUE TITLE
Search behaves unexpectedly when switching tabs

### ISSUE THREAD

**Issue by macau23** [keepassxreboot/keepassxc#1631]
KeePassCX behaves very strangely with search, but it wasn't until this morning that it occurred to me what it does differently.

If I search for a string, and then switch to another folder within KPXC, the search is sticky - it doesn't clear. This leads to the strange situation several times a week of wondering where my passwords have gone :)

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Debug Info

KeePassXC - 2.3.0
Revision: REVISION

Libraries:
- LIBS

Operating system: OS
CPU architecture: ARCH
Kernel: KERNEL

Enabled extensions:
- EXTENSIONS

**Comment by droidmonkey** [comment]
Folder or tab?

**Comment by LingMan** [comment]
Folder at least for me.
Current Behaviour:
* Search for something.
* Switch to a different folder
* The search results are still displayed

Expected Behaviour:
* Search for something.
* Switch to a different folder
* The contents of the folder that was switched to is displayed

**Comment by droidmonkey** [comment]
This is a duplicate of another issue.

**Comment by macau23** [comment]
Do you have the issue number? I found #1317

2.3.2 behaves the same as 2.3.1

**Comment by droidmonkey** [comment]
It is fixed in a PR I submitted for 2.4, #1797
