### ISSUE TITLE
KeePassXC Browser extension for Microsoft Edge browser?

### ISSUE THREAD

**Issue by Stephan-P** [keepassxreboot/keepassxc#1633]
Are there plans to also create a KeePassXC Browser extension for the Microsoft Edge browser?

## Desired Behavior
Ability to use KeePassXC in combination with the Edge browser

**Comment by RealOrangeOne** [comment]
This would probably be better raised at https://github.com/keepassxreboot/keepassxc-browser

**Comment by Stephan-P** [comment]
Apologies. Done
