### ISSUE TITLE
No way to permanently hide preview pane

### ISSUE THREAD

**Issue by jkugler** [keepassxreboot/keepassxc#1648]
In the latest version, if I click the Red "X" on the preview pane, it goes away...until I click on another entry. Then it comes back. I can find no config option to make sure it never displays. If I want to view the information in the entry, I can open it (edit it).

## Expected Behavior
There should be a config option to say "never display preview pane." Or, but in a positive way "Display preview pane when clicking on an entry."

## Current Behavior
The preview pane comes up every time I click on an entry.

## Possible Solution
See "expected behavior."

## Steps to Reproduce (for bugs)
N/A

## Context
N/A

## Debug Info

KeePassXC - 2.3.0
Revision: 4c0ed74

Libraries:
- Qt 5.6.1
- libgcrypt 1.8.1

Operating system: Ubuntu 16.04.4 LTS
CPU architecture: x86_64
Kernel: linux 4.4.0-112-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by Hexawolf** [comment]
See "Hide the Details View" under the Entry Management section. I believe that's what you are looking for.

**Comment by jkugler** [comment]
Siiigh. I went through the options so many times. I don't know why that didn't click. Thanks!

**Comment by MojtabaFaal** [comment]
> See "Hide the Details View" under the Entry Management section. I believe that's what you are looking for.

Hi
Why did you delete the settings?
I do not want to use "preview panel"
What should I do ?
