### ISSUE TITLE
Keepass doesn't work in ppa version and snap 2.3.0

### ISSUE THREAD

**Issue by p92canca** [keepassxreboot/keepassxc#1650]
I can't open database in snap, because I can't select it. The ppa version I can't install it because the  library libsodium23 have some problem
## Current Behavior

The ppa version I can install but I can't open it

## Steps to Reproduce (for bugs)

1. Remove keepassxc and try to install again the version ppa
2.
3.
4.

## Debug Info

KeePassXC - 2.3.0
Revision: REVISION

Libraries:
- LIBS
libsodium23

Operating system: KDE Neon
CPU architecture: amd64
Kernel: 4.14

Enabled extensions:
- EXTENSIONS
no

**Comment by droidmonkey** [comment]
Where is your database stored? Snaps are weird read our faq

**Comment by p92canca** [comment]
My database is stored in local but in other disk /media/data. After  
install a unistall some dependencies finally I could make it work. But  
in snap for me it was imposible because I couldn't choose the database
Jonathan White <notifications@github.com> escribió:

> Where is your database stored? Snaps are weird read our faq
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/keepassxreboot/keepassxc/issues/1650#issuecomment-370576217



Alberto Cañete

**Comment by phoerious** [comment]
See FAQ https://keepassxc.org/docs/#faq-appsnap-homedir

**Comment by p92canca** [comment]
Ok I understand, but I want to synchronize my database with dropbox,  
for this I have the database in other folder

Janek Bevendorff <notifications@github.com> escribió:

> See FAQ https://keepassxc.org/docs/#faq-appsnap-homedir
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/keepassxreboot/keepassxc/issues/1650#issuecomment-372965717



Alberto Cañete

**Comment by phoerious** [comment]
Snaps are very restricted. Use the AppImage or PPA version if you need to access arbitrary files outside your home directory

**Comment by p92canca** [comment]
Ok, thanks for all. Regards,
Janek Bevendorff <notifications@github.com> escribió:

> Snaps are very restricted. Use the AppImage or PPA version if you  
> need to access arbitrary files outside your home directory
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/keepassxreboot/keepassxc/issues/1650#issuecomment-372974315



Alberto Cañete
