### ISSUE TITLE
Create KPH: {TOTP} on TOTP setup

### ISSUE THREAD

**Issue by Generator** [keepassxreboot/keepassxc#1652]
When setting up TOTP also create `KPH: {TOTP}` attribute for current entry.

## Expected Behavior

When a new entry is created, and user set up TOTP secret `KPH: {TOTP}` should be also created for that entry, so it can be easily accessed by the browser extension.

## Current Behavior

KeePassXC-Browser "Fill TOTP"  (or other browser extension) is not documented ([only this comment](https://github.com/keepassxreboot/keepassxc-browser/issues/28#issuecomment-369494014)), and setting up TOTP to work with browser extensions can be hard for new users.

## Context

Every time i setup a new TOTP secret need to manualy create the attribute `KPH: {TOTP}` with value `{TOTP}`

## Debug Info
KeePassXC - Version 2.3.0
Revision: 4c0ed74

Libraries:
- Qt 5.10.1
- libgcrypt 1.8.2

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 4.14.23-1-lts

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by varjolintu** [comment]
Btw, this was documented in the original migration guide (but removed for some reason). I would also like to add to the documentation some tutorial about how to use the custom string fields with the browser extension.

**Comment by weslly** [comment]
@varjolintu Wouldn't it be better to just get the TOTP code directly from keepassxc-browser instead of having to add that attribute? If it is set by default on entries with TOTP, I don't see a point on having an additional attribute for this purpose.

**Comment by varjolintu** [comment]
@weslly It is? I didn't even know that. I'll do a fix right away then.

**Comment by weslly** [comment]
@varjolintu no, I mean, creating it on setup like OP suggested.

**Comment by varjolintu** [comment]
@weslly Sorry. Tired eyes.

**Comment by droidmonkey** [comment]
We shouldn't create additional attributes if there exists one already
