### ISSUE TITLE
Support u2f devices as a form of challenge response (Request for Improvement)

### ISSUE THREAD

**Issue by AdrianKoshka** [keepassxreboot/keepassxc#1654]
From reading some documentation, it seems you can use yubico devices to fulfil the challenge response mechanism of keepassxc. I was wondering if this could be done but with devices that **only** perform u2f authentication (example pictured below). These devices work by generating public/private keypairs. The private key stays on the device, while the public key is given to the application.

![u2f-dongle](https://core-electronics.com.au/media/catalog/product/cache/1/image/650x650/fe1bcd18654db18f328c2faaaf3c690a/3/3/3363-02.jpg) 
## Expected Behavior

When you create a databse / change the master key, and select challenge response as the method, any u2f device plugged in should show up as an option.
## Current Behavior

You can not use u2f devices for challenge response.
## Possible Solution

Add u2f as a form of challenge response.

## Debug Info

KeePassXC - Version 2.2.4
Revision: 4723f66

Libraries:
- Qt 5.9.4
- libgcrypt 1.8.2

Operating system: Fedora 27 (Twenty Seven)
CPU architecture: x86_64
Kernel: linux 4.15.6-300.fc27.x86_64

Enabled extensions:
- KeePassHTTP
- Auto-Type
- YubiKey

**Comment by phoerious** [comment]
No, this is not possible. See https://keepassxc.org/docs/#faq-yubikey-why-hmac-sha1

**Comment by AdrianKoshka** [comment]
Ah, thanks.
