### ISSUE TITLE
Crash on Edit Screen when Database is changed exernally

### ISSUE THREAD

**Issue by mstarke** [keepassxreboot/keepassxc#1658]
Crash in edit view when database is merged on external changes

## Expected Behavior

No crash

## Current Behavior

Crash

## Steps to Reproduce (for bugs)

1. Enable Automatically reload database when modified externally option in General Settings.
1. Open database in KeePassXC
1. Open database in another application
1. Got to Edit Entry/Edit Group View in KeePassXC
1. Change database and save database in other application
1. Change to KeePassXC and hit Ok or Cancel

## Debug Info
KeePassXC - Version 2.3.0
Revision: 4c0ed74

Libraries:
- Qt 5.9.3
- libgcrypt 1.8.2

Operating system: macOS Sierra (10.12)
CPU architecture: x86_64
Kernel: darwin 16.7.0

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by droidmonkey** [comment]
Cannot reproduce, although the edit dialog is not updated if you edited the same entry that is open when the changes are reloaded.
