### ISSUE TITLE
Use username and pasword link (reference) to other entry.

### ISSUE THREAD

**Issue by milankni** [keepassxreboot/keepassxc#166]
I prefer to have a separate entry for e.g. wiki.archlinux.org, aur.archlinux.org, bbs.archlinux.org in KeePass db so that I can get directly to where I want from KeePassXC.

However, these sites share the same username and password.It would be good if a single entry can be cloned to a copy, which would still use the original username and password entry, so that the user does not have to maintain multiple entries in case of password change. (Like KeePass does use referencing.)

A workaround is a single entry for URL "https://archlinux.org", but the the action "Open URL" does not take me to where I want (wiki, aur, bbs, ...). With Arch Linux website, this is not a major trouble - there are links on the main page. However, for other sites (like my employer's Citrix Gateway, Web email, etc.), this may not be true and the user has to use other means outside of KeePassXC (manual entry, bookmarks).

## Your Environment
* KeePassXC 2.0.3
* Operating System and version: Arch Linux 64 bit.

**Comment by TheZ3ro** [comment]
Issue duplicate here https://github.com/keepassxreboot/keepassxc/issues/75
