### ISSUE TITLE
Corrupt passwords

### ISSUE THREAD

**Issue by murrayju** [keepassxreboot/keepassxc#1661]
When I open my password database in keepassxc, the password fields are filled with gibberish (though all other data appears to be intact):
**-- IMAGE REMOVED --**

Opening the exact same kdbx file works correctly in keepass2, keepass2android, and macpass. I confirmed that this problem occurs on windows, mac, and linux, going back at least several versions (tried 2.2.1 - 2.3.0).

I suspect that this problem is due to some particular state of my database, since this was working for months and just broke yesterday.

To make matters worse, making any modifications in keepassxc and saving the database results in the same corruption showing up permanently in all other clients (like keepass2). Good thing I keep rolling backups..

## Expected Behavior
Database that loads in keepass2 should load the same in keepassxc.

## Current Behavior
Passwords are corrupted in keepassxc.

## Steps to Reproduce
For obvious reasons, I can't share my database... Is there some other way to debug this?

## Context
I use several different clients/machines, and sync using resilio. The last modification (to password data) was made by keepass2android, but this was to an outdated copy of the db, so this resulted in keepass2 (on windows) doing a merge (I use [local <-> master sync](https://keepass.info/help/kb/trigger_examples.html#dbsync)). After that, keepassxc had this issue.

## Debug Info
```
KeePassXC - Version 2.3.0
Revision: 4c0ed74
Distribution: Snap

Libraries:
- Qt 5.7.1
- libgcrypt 1.7.6-beta

Operating system: Ubuntu Core 16
CPU architecture: x86_64
Kernel: linux 4.13.0-36-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey
```

**Comment by phoerious** [comment]
Same as #1646.

**Comment by murrayju** [comment]
Confirmed that upgrading the database to kdbx v4 (by changing the encryption to Argon2) is a viable workaround. Thanks!
