### ISSUE TITLE
"Automatically save after every change" should be enabled by default

### ISSUE THREAD

**Issue by kneitinger** [keepassxreboot/keepassxc#1663]
I believe that having "Automatically save after every change" be enable by default is the more reasonable decision. 

## Context
Over the years I've recommended keepass(xc) to dozens of people. On all of those occasions, the person obviously loves keepassxc, but, on a high number of those occassions, the person ends up generating a bunch of random passwords and changes them in their corresponding services, only to close keepassxc and lose all of them, forcing them to waste a lot of time resetting passwords. This issue is even more likely to happen to users since keepassxc (_rightfully!_) does not prompt for confirmation to close the application.

I feel as though, since the history of every entry is saved upon modification, that there is no downside to enabling autosave by default to prevent situations like I described. I also believe it will greatly improve folks' first impressions of keepassxc.

## Current Behavior
"Automatically save after every change" is disabled by default.

**Comment by kneitinger** [comment]
My apologies.  I started to browse the source to find the setting and noticed the behavior was changed to this a month ago.

https://github.com/keepassxreboot/keepassxc/blame/develop/src/core/Config.cpp#L127

**Comment by CoeJoder** [comment]
Unconventional, weird feature.  Should prompt if unsaved changes instead of autosave.  For example, sometimes a generated password does not satisfy the requirements of the host and you will need to get access to the previous password, but that isn't possible when the old password was automatically overwritten.  Luckily I have backups I can pull from, but this was unexpected.

**Comment by droidmonkey** [comment]
Holy necropost batman. Every entry has a history that saves old passwords if you need to retrieve them. Make sure that isn't disabled in your database settings. https://keepassxc.org/docs/KeePassXC_UserGuide#_history
