### ISSUE TITLE
Encryption settings on database creation

### ISSUE THREAD

**Issue by Generator** [keepassxreboot/keepassxc#1669]
Creating a new database users should be able to choose encryption settings like in KeePass2

## Expected Behavior

When creating a new database a new dialog or advanced settings tab with database encryption settings with recommended settings  pre-selected.

## Current Behavior

When creating a new database there's no encryption settings or any note to notice the user about database encryption settings. New users may not be aware of these options.

## Debug Info

KeePassXC - Version 2.3.1
Revision: 2fcaeea

Libraries:
- Qt 5.10.1
- libgcrypt 1.8.2

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 4.14.23-1-lts

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by phoerious** [comment]
A new database creation dialog is planned.
