### ISSUE TITLE
Drag and drop entries between databases

### ISSUE THREAD

**Issue by r0ckarong** [keepassxreboot/keepassxc#1670]
## Expected Behavior
 As described in #927 I would expect to drag an entry to another opened database and holding Ctrl on release would copy the entry instead of moving it.

## Current Behavior
No matter which modifier button I hold the entry is moved and not copied. There seems to be no way for me to simply copy an entry to another database.

## Steps to Reproduce (for bugs)
1. Open two databases
2. Drag an entry to the second database, Hold the (left) Ctrl key and release the mouse button.

## Context
I can not copy entries between databases without manually transferring all attributes.

## Debug Info
KeePassXC - Version 2.3.1
Revision: 2fcaeea

Libraries:
- Qt 5.9.3
- libgcrypt 1.8.2

Operating system: macOS Sierra (10.12)
CPU architecture: x86_64
Kernel: darwin 16.7.0

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by droidmonkey** [comment]
This is not an implemented feature. I also think this is a duplicate.

**Comment by r0ckarong** [comment]
@droidmonkey Apparently in 2.2.0 this was possible at least on Linux systems (see the screencap from #927).

**Comment by weslly** [comment]
@r0ckarong I just tested and it works fine, but you need to use <kbd>Option</kbd> instead of <kbd>Control</kbd> to copy the entry.

![kapture 2018-03-08 at 7 06 09](https://user-images.githubusercontent.com/107672/37145295-49fdb52a-229f-11e8-909a-0284224beb73.gif)

**Comment by sokratis1988** [comment]
Is it still working on macOS?

**Comment by LintaoAmons** [comment]
> Is it still working on macOS?

Yes, I just tried. 

But one thing you need to pay attention is you have to hold the `option` key and drag the item to one group icon, for example the `Root`.
