### ISSUE TITLE
Updating KeePassXC should restart keepassxc_proxy on Linux/macOS

### ISSUE THREAD

**Issue by phoerious** [keepassxreboot/keepassxc#1672]
## Expected Behavior

Updating KeePassXC should kill any running proxy instance.

## Current Behavior

Running instances continue to run and the browser extension thinks I'm on an old KeePassXC build, even if the actual application is up-to-date.

## Possible Solution

Kill proxy when KeePassXC exits / starts

## Debug Info

KeePassXC - Version 2.3.1
Revision: 2fcaeea

Libraries:
- Qt 5.9.1
- libgcrypt 1.7.8

Operating system: Ubuntu 17.10
CPU architecture: x86_64
Kernel: linux 4.13.0-31-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by droidmonkey** [comment]
This actually does happen because the proxy is killed when the connection to the socket is closed.
