### ISSUE TITLE
KeePassXC-Browser not spawning KeePassXC

### ISSUE THREAD

**Issue by zapme** [keepassxreboot/keepassxc#1674]
## Expected Behavior
KeePassXC starts automatically when a browser with KeePassXC-Browser is started (and KeePassXC is properly configured).

## Current Behavior
KeePassXC does not automatically start.  If started manually, no prompt for key association appears.

## Possible Solution
As per the migration guide to KeePassXC-Browser "To allow your browser to access KeePassXC, you need to tell it where to find the KeePassXC program file. Luckily, KeePassXC does this automatically for you."

This does not appear to work, and a preference or setting to locate KeePassXC is not evident.  Add a setting to select the application manually for times when auto-location of the program file fails, and as a mechanism to confirm the location of the program file.

## Steps to Reproduce (for bugs)
1.  For OSX, install KeePassXC
2. Attempt to use KeePassXC-Browser

## Context
Attempting to follow the migration instructions to move from KeePassHTTP to KeePassXC-Browser.  
 Functionality continues by enabling the legacy, to be deprecated, KeePassHTTP.

## Debug Info
KeePassXC - Version 2.3.1
Revision: 2fcaeea

Libraries:
- Qt 5.9.3
- libgcrypt 1.8.2

Operating system: macOS High Sierra (10.13)
CPU architecture: x86_64
Kernel: darwin 17.4.0

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by phoerious** [comment]
You need to start KeePassXC manually, so it can do the browser configuration for you. Also if you want your browser to start KeePassXC next time, you need to disable the proxy (see last section of the migration guide). I recommend the proxy method, though.
