### ISSUE TITLE
2.3.1 crashes on macOS Sierra

### ISSUE THREAD

**Issue by MarkusPlank** [keepassxreboot/keepassxc#1685]
2.3.1 crashes on macOS Sierra

## Expected Behavior

Want to add a new database entry, should be added by clicking "ok" or "Apply"

## Current Behavior

When adding a new Database entry and click on "Apply" or "OK", KeePassXC crashes in 1 of 10 times.

## Steps to Reproduce (for bugs)

1. for testing purposes, i only filled in the "Title" and a "Username", no password.
2. did the same for 7 entries, then it crashed again.
3.
4.

## Debug Info
KeePassXC - Version 2.3.1
Revision: 2fcaeea

Bibliotheken:
- Qt 5.9.3
- libgcrypt 1.8.2

Betriebssystem: macOS Sierra (10.12)
CPU-Architektur: x86_64
Kernel: darwin 16.7.0

Aktivierte Erweiterungen:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by weslly** [comment]
I tried adding more than 50 entries but can't reproduce this. Does this happen on previous versions?

**Comment by ligyxy** [comment]
I can't reproduce this either
