### ISSUE TITLE
Can't install on Ubuntu 18.04 from PPA

### ISSUE THREAD

**Issue by SystemZ** [keepassxreboot/keepassxc#1687]
KeepassXC can't be installed on a Ubuntu 18.04 daily build from 07.03.2018.

When installing, there is an unmet dependency with libcurl version.

## Steps to Reproduce

```bash
add-apt-repository ppa:phoerious/keepassxc -y
apt-get update
apt-get install keepassxc -y
```

```plain
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 keepassxc : Depends: libcurl3 (>= 7.16.2) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

```

**Comment by seevee** [comment]
Same problem here. I did `apt install libcurl3` which resolved this and allowed me to `apt install keepassxc`, but uninstalled `libcurl4`, `curl`, and two DE-specific packages depending on curl.

**Comment by phoerious** [comment]
Looks like bionic replaces the libcurl3 package with libcurl4.

**Comment by phoerious** [comment]
I re-uploaded the build to Launchpad. It now depends on libcurl4. Packages should be available shortly.

**Comment by sneurlax** [comment]
Hmm, having this issue on Debian 9 Stretch... `libcurl4 ... is not installable`
