### ISSUE TITLE
Chrome Canary won't register in KeepassXC 2.3.+ (fix inside)

### ISSUE THREAD

**Issue by cybik** [keepassxreboot/keepassxc#1688]
## Steps to repro
1. Install Chrome Canary
1. Install https://chrome.google.com/webstore/detail/keepassxc-browser/oboonakemofpalcgghocfoadofidjkkk
1. Use KeepassXC 2.3.x
1. Try to connect the app to the Browser

## Expected Behavior
It will allow the user to authorize the browser.

## Current Behavior
It won't allow the user to authorize the browser.

### Manual solution
`cp -r ~/Library/Application\ Support/Google/Chrome/NativeMessagingHosts ~/Library/Application\ Support/Google/Chrome\ Canary/`
### Code solution
Untested, "demo" fix available here: https://github.com/cybik/keepassxc/commit/1f54a7b3056cda4c3ec64bf7cff87b110c8a5af1

## General Info
KeePassXC fork - 2.3.1+
keepassxc-browser - as deployed on Chrome Extension Store

Operating system: Mac OSX
Browser: Chrome Canary
Proxy used: YES

**Comment by TheZ3ro** [comment]
This can easily fall into Custom Browser #1594
