### ISSUE TITLE
No go with Chromium from "woolyss" and flakey KeePassXC-Browser

### ISSUE THREAD

**Issue by RecycledElectron** [keepassxreboot/keepassxc#1690]
Alright, since the release of KeePassXC 2.3.0/.1 the suggested KeePassXC-Browser extension (1.0.1) simply keeps on refusing to connect with KeePassXC with the Chromium build from http://chromium.woolyss.com/

OS: Windows 8.1 (up-to-date) Pro x64
Browser: Chromium 65.0.3325.146 64-Bit stable ("all codecs" running via "chrlauncher" out of %LocalAppData%\Chromium (http://chromium.woolyss.com/f/chrlauncher-win64-stable-codecs-sync.zip) to have an auto-updater to keep Chromium up-to-date)

While "Chromium" is enabled in the browser integration settings of KeePassXC the KeePassXC-Browser extension just keeps on returning "Timeout or not connected" and doesn't even offer a "Connect" to setup a new connection.

I am also using KeePassXC (AppImage version) / KeePassXC-Browser in Antergos Linux/KDE with the distro-provided version of Chromium ... the interaction between the browser-extension and KeePassXC is insanely flakey (and that's a very polite assessment). When I try to sign into my, for example, Google account I require multiple attempts until the browser extension finally decides to play ball and fill in the login credentials.

Since the issues with the interaction between your KeePassXC-Browser extension and KeePassXC are annoying to the Nth degree I switched back to the "soon to be deprecated because it obviously works just too well" KeePassHttp browser extension where the interaction between the browser extension and KeePassXC at least works reliably.

I would really look forward to a fixed version where that newfangled "KeePassXC-Browser" thing works at least as reliable as KeePassHttp does for the time being.

If you need any more information feel free to leave me a reply telling me what bits and pieces of info you actually need me to provide.

**Comment by droidmonkey** [comment]
We are constantly updating the performance of the browser extension and native messaging backend. The http plugin is stable, but not secure. The http plugin isn't going anywhere until we release v2.4 which is likely 6 months from now.
