### ISSUE TITLE
Password stays visible while unlocking database if password visibility was toggled

### ISSUE THREAD

**Issue by maxwell-edison** [keepassxreboot/keepassxc#1692]
When opening a KeePass database one has the option to toggle password visibility by clicking on the eye button, however while KeePassXC is working on opening the database, the interface becomes unresponsive. This means that if the password was set to visible and the database is being unlocked, the password will stay visible until the opening procedure completes without the ability of the user to hide it. When using a high number of rounds this means that the password could stay exposed for a potentially very long time, increasing the possibility of it being shoulder-surfed or otherwise captured.

## Expected Behavior
While unlocking a KeePass database, password visibility should be always set to off.

## Current Behavior
When unlocking a KeePass database, if the password was set to visible, it stays visible.

**Comment by hifi** [comment]
A fix has been merged into the next patch release 2.3.2.
