### ISSUE TITLE
Wiki page requires an update (Using-DBus-with-KeePassXC)

### ISSUE THREAD

**Issue by AsavarTzeth** [keepassxreboot/keepassxc#1694]
The following wiki page [Using-DBus-with-KeePassXC](https://github.com/keepassxreboot/keepassxc/wiki/Using-DBus-with-KeePassXC) require updates.

## Expected Behavior
Wiki contains up to date instructions.

## Current Behavior
Wiki mentions incorrect instructions, prior to using the correct dbus id.

## Possible Solution
Update the wiki to use the correct id `org.keepassxc.KeePassXC`

## Steps to Reproduce (for bugs)

For an example I will lock the database according to the wiki. Although all instructions require changes.

    qdbus org.keepassxc.MainWindow /keepassxc org.keepassxc.MainWindow.lockAllDatabases

This does not work.

Lock it, using the correct id:

    qdbus org.keepassxc.MainWindow /keepassxc org.keepassxc.KeePassXC.MainWindow.lockAllDatabases

This does work.

## Context
A user tried to debug another potential issue but this came up. It really is just a simple case of documentation not being updated with the application.

## Debug Info
KeePassXC - 2.3.1
Revision: 2fcaeea

**Comment by phoerious** [comment]
Fixed. Thanks for the reminder.

**Comment by juppees** [comment]
The syntax seems to have changed back:
`qdbus org.keepassxc.KeePassXC.MainWindow /keepassxc 
method void org.keepassxc.MainWindow.appExit()
method void org.keepassxc.MainWindow.closeAllDatabases()
method void org.keepassxc.MainWindow.lockAllDatabases()
method void org.keepassxc.MainWindow.openDatabase(QString fileName)
method void org.keepassxc.MainWindow.openDatabase(QString fileName, QString pw)
method void org.keepassxc.MainWindow.openDatabase(QString fileName, QString pw, QString keyFile)`

`keepassxc -v
keepassxc 2.3.4
`
