### ISSUE TITLE
keepassxc-cli not distributed on Mac

### ISSUE THREAD

**Issue by danielepolencic** [keepassxreboot/keepassxc#1697]
I really like the idea of using KeepassXC from the command line. I had [a look at the docs](https://keepassxc.org/docs/) and I searched through the issues in this repo, but I couldn't find any reference on how to use the cli on Mac. I tried to look inside the app folder on my mac, but there's no binary for the cli.

I'm sure I'm missing something obvious.

## Debug Info
KeePassXC - Version 2.3.1
Revision: 2fcaeea

Libraries:
- Qt 5.9.3
- libgcrypt 1.8.2

Operating system: macOS Sierra (10.12)
CPU architecture: x86_64
Kernel: darwin 16.7.0

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by droidmonkey** [comment]
Should be as simple as ```keepassxc-cli```. There is a help docs printout on how to use it.

**Comment by weslly** [comment]
>There is a help docs printout on how to use it.

and `man keepassxc-cli`

**Comment by danielepolencic** [comment]
@droidmonkey @weslly thanks for looking into this.

The problem is... I can’t locate the cli. It’s not in the DMG or inside the application’s folder. Has anyone tried the cli on a Mac? Should I compile the project locally to use the cli?

The documentation has some clues if you’re using the appimage, but none for how to use it on a Mac.

**Comment by varjolintu** [comment]
AFAIK you have to download the sources and compile it by yourself. Btw, we could use the same kind of trick with keepassxc-cli I used with keepassxc-proxy. It's automatically put inside the application package on macOS.

**Comment by TheZ3ro** [comment]
It should be in the dmg package, maybe this is a distribution problem? @phoerious

**Comment by phoerious** [comment]
It should be packaged with the DM, but I just checked and, indeed, it seems to be missing. I'll see if I can fix it.

**Comment by motoshun** [comment]
@phoerious Do you know if this was resolved? I see milepost v2.3.2, but the issue is open and the v2.3.3 dmg doesn't seem to solve the issue.

**Comment by ligyxy** [comment]
I am seeing this issue again with KeePassXC 2.4.0, installed through brew cask.
It returns "command not found: keepassxc-cli" in terminal.

**Comment by droidmonkey** [comment]
ping @vraravam

**Comment by vraravam** [comment]
ack @droidmonkey .

The PR for installing via homebrew was only changed to bump the new version number and the SHA. Was this cli tool introduced recently? I haven't used it before - so, i did not check post-install.

**Comment by droidmonkey** [comment]
We added it to the DMG file. You probably have to symlink to it (not sure).

**Comment by varjolintu** [comment]
It should be found from `/Applications/KeePassXC.app/Contents/MacOS/keepassxc-cli`. Symlink to that binary.

**Comment by vraravam** [comment]
@varjolintu - thanks for the heads up. I have submitted two new PRs for this: [stable version](https://github.com/Homebrew/homebrew-cask/pull/60885) and [beta version](https://github.com/Homebrew/homebrew-cask-versions/pull/7144)

**Comment by fievelk** [comment]
Just to be more explicit, this is the solution that worked for me:
1. Find the current CLI executable:
    ```sh
    $ find 2>/dev/null / -name "keepassxc-cli"
    ```
    This will return the path to the cli executable. In my case, this path was `/System/Volumes/Data/Applications/KeePassXC.app/Contents/MacOS/keepassxc-cli`.

2. Create a symbolic link to the executable inside of `/usr/local/bin`:
    ```console
    $ ln -s /System/Volumes/Data/Applications/KeePassXC.app/Contents/MacOS/keepassxc-cli /usr/local/bin/
    ```
    `/usr/local/bin` should already be in the $PATH env variable, so you should already be able to run the executable from terminal with `keepassxc-cli`.

**Comment by Drew-Daniels** [comment]
For anyone who uses [`fd`](https://github.com/sharkdp/fd):

```bash
fd --search-path / --ignore keepassxc-cli
```
