### ISSUE TITLE
Enable configurable columns in the entries grid

### ISSUE THREAD

**Issue by t4777sd** [keepassxreboot/keepassxc#17]
There is no way to change the data shown in the password grid. I had view the last edited passwords and I had to download KeePass in order to view the last modified column and sort by it. It was impossible in KeepassX

**Comment by danielj-at-jumbo** [comment]
Related to #129

**Comment by ConcurrentHashMap** [comment]
👍 Please implement this. I always use the notes column in KeePass. It would nice to have at least notes, last changed and password column like in the original KeePass.

**Comment by Udo017** [comment]
Please make possibility to choose width column's are shown and copy the value by double click on the column.

**Comment by fonic** [comment]
Will be covered by #849

**Comment by droidmonkey** [comment]
Closing in favor of above issue.
