### ISSUE TITLE
UI Redesign

### ISSUE THREAD

**Issue by droidmonkey** [keepassxreboot/keepassxc#1705]
Tracking issue for UI Redesign efforts. Summary of tasks:

* Improve icon set
* Fix font sizes across platforms
* Download favicon for all entries
* Improve error messages
* Implement QMacToolbar
* Sort groups alphabetically
* Redesign unlock screen (#835)
* Redesign key change dialog (#1952)

Replaces #1443

**Comment by MisterY** [comment]
Thanks for all the effort in developing this application!
Please make "Download favicon for all entries" configurable. It is a nice feature, being able to download a favicon, but might unneccessarily increase a database size if there are many records.
In some cases, especially for shared databases, it might be preferrable to not download any icons automatically.
Not that you mention that this will happen automatically for all entries but I'd just like to add +1 for the configuration option. Cheers

**Comment by droidmonkey** [comment]
It's not planned to be fully automatic, you have to select the action from the database menu.

**Comment by MisterY** [comment]
Sorry if I'm nitpicking, @pjc123, but you can't be using this on Android?

**Comment by pjc123** [comment]
@MisterY.  Sure, I am using keepassxc on Android (The keepassxc database anyway)...with the Keepass2Android app.  There are other apps as well.

**Comment by blowsie** [comment]
Another suggestion:

In KeePass 2, clicking on a root folder in the tree would show all entries, providing a nice way to be able to sort / review all entries instead of having to click through each individual folder/group

**Comment by phoerious** [comment]
That's kind of inconsistent, though, isn't it?

**Comment by blowsie** [comment]
Well, it KeePass 2 its a consistent behaviour, The sub folders are broken out into groups when you are viewing its parent.

For me personally this view is preferred for the reasons mentioned above.

**Comment by droidmonkey** [comment]
Closing this as most bullet points have been implemented as of 2.5.0.
