### ISSUE TITLE
Enhance installation process

### ISSUE THREAD

**Issue by droidmonkey** [keepassxreboot/keepassxc#1707]
Epic to track enhancements to the installation process.

* Start on login
* Check for updates
* Multilingual installers
* Migrate to windeployqt and linuxdeployqt

**Comment by TheZ3ro** [comment]
Multilanguage installer is tracked in #1110

---

For the automatic updater:
It should use the github API to get the latest release, and then compare the executable version to `tag_name` from JSON object
https://api.github.com/repos/keepassxreboot/keepassxc/releases/latest

Also a note on `draft` and `prerelease` properties.
In the assets object there are all the download available. If we want to make this automatic it should the platform should download its release binaries, check shasum (maybe check PGP signature) and install.

The `body` attribute also have the release note but I think a link to the github release should suffice

**Comment by phoerious** [comment]
windeployqt and linuxdeployqt are done. Is the rest still an issue?

**Comment by droidmonkey** [comment]
Start on login still pends. Will open new issue for it.
