### ISSUE TITLE
Installer claims I have the version I'm installing

### ISSUE THREAD

**Issue by jsoref** [keepassxreboot/keepassxc#1708]
![image](https://user-images.githubusercontent.com/2119212/37259358-8e161e14-255b-11e8-97cc-501ef800ace8.png)
![image](https://user-images.githubusercontent.com/2119212/37259377-b6448934-255b-11e8-9dd8-ed7ed34e97b6.png)

## Expected Behavior
Show the actual installed version

## Current Behavior
Installer dialog claims pending version is already installed

## Steps to Reproduce (for bugs)
1. Have 2.2.0 installed
2. Download 2.3.1
3. Run the installer

## Debug Info
KeePassXC - Version 2.2.0
Revision: caa49a8ef3ee28ed478192389b21d61107b3b8e0

Libraries:
- Qt 5.9.0
- libgcrypt 1.7.7

Operating system: Windows 10 (10.0)
CPU architecture: x86_64
Kernel: winnt 10.0.16299

Enabled extensions:
- KeePassHTTP
- Auto-Type
- YubiKey

---
KeePassXC - Version 2.3.1
Revision: 2fcaeea

Libraries:
- Qt 5.10.1
- libgcrypt 1.8.2

Operating system: Windows 10 (10.0)
CPU architecture: x86_64
Kernel: winnt 10.0.16299

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by droidmonkey** [comment]
Known issue, its just a name issue.
