### ISSUE TITLE
Recognize when database has changed on disk

### ISSUE THREAD

**Issue by jsoref** [keepassxreboot/keepassxc#171]
We use a version control system to manage our primary database.

1. Open database in KeePass
1. Update database on disk using VCS

## Expected Behavior
* If the database is clean, and we update the database on disk, it'd be wonderful if keepass automatically updated the in memory version.
* if the database is dirty and the database updates on disk, it'd be wonderful if keepass provided a notification and made it easy for us to work past this problem

## Current Behavior
You're going to clobber your changes which isn't stellar. And then you have to figure out how to reconcile.

**Comment by phoerious** [comment]
Automatic reload of databases is already implemented. Please check out the current develop branch and see it works for you the way you imagine it.

**Comment by phoerious** [comment]
I assume your issue is fixed with 2.1.0. If not, please reopen or create a new issue report.
