### ISSUE TITLE
Windows build: toolbar icons microscopic on 12" 4K display

### ISSUE THREAD

**Issue by tycho** [keepassxreboot/keepassxc#1710]
## Expected Behavior
I would expect the toolbar icons to be recognizable and scaled properly.

## Current Behavior
Well, just take a look:

![image](https://user-images.githubusercontent.com/29616/37262813-83fbb892-2562-11e8-923c-db6aa6a5f8c1.png)

## Possible Solution
Probably need higher resolution icons so that it can use those.

## Steps to Reproduce (for bugs)
1. Run KeePassXC on Windows at 4K.
2. Observe the tiny icons.

## Context
It only affects me on one device, a laptop with a 12" 4K display.

## Debug Info
KeePassXC - Version 2.3.1
Revision: 2fcaeea

Libraries:
- Qt 5.10.1
- libgcrypt 1.8.2

Operating system: Windows 10 (10.0)
CPU architecture: x86_64
Kernel: winnt 10.0.16299

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by tycho** [comment]
Same problem with the Attachments icon in the entry list header.

**Comment by tycho** [comment]
This setting has a dramatic positive impact on the readability of the whole thing:
![image](https://user-images.githubusercontent.com/29616/37263110-cc2e9a02-2563-11e8-89d7-44a9afc1cdf5.png)


As you can see:
![image](https://user-images.githubusercontent.com/29616/37263028-8a8f6388-2563-11e8-8edd-74cf353bb0a5.png)

**Comment by ArchangeGabriel** [comment]
This looks like #548 and https://github.com/keepassxreboot/keepassxc/issues/1291#issuecomment-352079847

**Comment by tycho** [comment]
I wonder if we can tell Windows to use the "system (enhanced)" scaling via the embedded .manifest? If we could, that'd be a stopgap for Windows until high DPI icons exist.
