### ISSUE TITLE
KeePassXC crashes when using Argon2 key derivation function

### ISSUE THREAD

**Issue by rjurga** [keepassxreboot/keepassxc#1711]
## Expected Behavior
* Ability to open a database with a key file using Argon2.
* Ability to change a key file from AES-KDF to Argon2 through the Database Settings menu.

## Current Behavior
* Opening a database using an Argon2 key file crashes KeePassXC. If launched through the terminal, the following output is displayed: `Illegal instruction`.
* When using a database using an AES-KDF key file and trying to change it to Argon2, it crashes with the same error. When trying to open that database again, an error message notifying that it is corrupted appears.

## Steps to Reproduce (for bugs)
1. Select a database (with or without password) and its Argon2 key file in the `Enter master key` menu.
2. It crashes when clicking `OK`.

## Context
The crash happens on a fully updated Solus with vanilla KeePassXC settings (no settings changed since installation). I have three computers with Solus, and the crash only happens on one of them. On the other computers I am able to convert the same databases that crash with no issues, or open a database with a key file using Argon2. I am trying to think of what the difference between the Solus installations are, and the only thing I can think of is locale and keyboard layout (both of which are French on the computer with crashes). I am not sure if it is relevant. Also not sure where to find crash logs, if anyone lets me know I will share them.

## Debug Info
KeePassXC - Version 2.3.1
Revision: 2fcaeea

Libraries:
- Qt 5.10.0
- libgcrypt 1.8.1

Operating system: Solus 3.99
CPU architecture: x86_64
Kernel: linux 4.15.7-60.current

Enabled extensions:
- Auto-Type
- Browser Integration
- YubiKey

**Comment by hifi** [comment]
Is this an AppImage or Snap install?

**Comment by rjurga** [comment]
No it's not a Snap, it's the package provided by Solus. It is packaged from the release tarball taken from here on Github.

The CPU is an [Intel Core i7-2670QM](https://ark.intel.com/products/53469/Intel-Core-i7-2670QM-Processor-6M-Cache-up-to-3_10-GHz) (the computer is a Dell XPS laptop, from 2011 I believe).

**Comment by hifi** [comment]
Likely an issue with the Solus argon2 package not overriding the default optimization level:

https://github.com/Alexpux/MINGW-packages/commit/0282e73677b96ebe9eaae00a99035913471b9063

Can you please confirm with your distribution that they do not build with the default settings? This will affect any program that depends on argon2 on the system you have this issue with.

**Comment by rjurga** [comment]
Thanks a lot, I [reported](https://dev.solus-project.com/T6009) it to Solus developers.

**Comment by hifi** [comment]
Closing, very fast response from the Solus packagers!

**Comment by intika** [comment]
i had the same issue but for some reason i was missing the package Argon2 i had lib64Argon2 and lib64Argon2-devel but not argon2 ... after adding it, it solved the problem, i think may be the package is not in the dependency list any way i will open a bug on my disto ;) thanks for your work be the way

**Comment by htgoebel** [comment]
I had a similar issue: Opening a database failed even without a Argon2 key file. Updating/reinstalling lib64argon2_1 solved the issue.
