### ISSUE TITLE
KeePassXC-Browser: Don't understand how to save a password from within the browser

### ISSUE THREAD

**Issue by jbruggem** [keepassxreboot/keepassxc#1712]
## Summary

Whether on a new website or on a website where I already have credentials, I can't seem to update or add any password in KeePassXC from within the browser.

I hope my report is clear enough. Many thanks to the awesome contributors of this project! It's awesome :)

## Expected Behavior

When logging in with new credentials, I expected to be offered the choice to save them to my KeepassXC database. I expected to be able to click "yes, save them" in my browser and directly after to see them appear in KeepassXC.

## Current Behavior

There was a notification hinting at the fact that it could save my credentials (which I did not understand really well) and the KeePassXC-Browser icon became red and was blinking (but hidden by the notification, so not visible at first). I tried clicking on the blinking icon and nothing happened.

## Possible Solution

I'm not sure if this is working as intended or a bug, or even if my use case is a supported feature; therefore if it's not a bug there's an issue with the UX on this: 
- the KeePassXC notification gets in the way
- I don't understand the meaning of the blinking icon 
- an explicit button "save credentials for USERNAME on WEBSITE" seems necessary.

## Steps to Reproduce (for bugs)

1. go on a new website
2. create an account
3. Log out/log in again
4. the aforementioned situation happens.

## Context

I want to be able to automatically save credentials to KeePassXC whenever I'm browsing.

## Debug Info

Firefox 58.0.2

KeePassXC - Version 2.3.1
Revision: 2fcaeea

Libraries:
- Qt 5.9.1
- libgcrypt 1.7.8

Operating system: Ubuntu 17.10
CPU architecture: x86_64
Kernel: linux 4.13.0-36-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

Libraries:
- LIBS

Operating system: OS
CPU architecture: ARCH
Kernel: KERNEL

Enabled extensions:
- EXTENSIONS

**Comment by varjolintu** [comment]
You can turn off the notifications if that's annoying to you. In the next browser extension release there's a separate button where you can disable only the notification for new/modified credentials.

When the icon blinks red it means new or modified credentials are detected. You can increase the `Blink Time` from the settings if it's too short. While clicking the icon when it's blinking you will have a dialog where you can either add a new credentials or modify an existing one.

**Comment by jbruggem** [comment]
Hi varjolintu,

thanks for your quick reply. I've just tested on my work machine (similar config), and indeed I get the behaviour you described.

I believe that on my personal machine I did manage to click on the blinking icon on time without having the dialog open; but I'll try again to be sure (and provide a video if it's the case).

**Comment by Thomas830** [comment]
Same problem here, I can't create or update an entry from browser extension.
`Error 5: Timeout or not connected to KeePassXCWhen I click on new I got the following message in the debugger`

The base is open and well connected .

Browser: Firefox Nightly 61

**Comment by varjolintu** [comment]
@Thomas830 Please provide some debug logs and see if there's any additional error messages.

**Comment by varjolintu** [comment]
Usually this means the proxy is closed just after it started. So it's a strange error. Can you run it manually?

**Comment by Thomas830** [comment]
I'd be happy to if I knew how to do that

**Comment by varjolintu** [comment]
@Thomas830 From the shell or command prompt, depending on the OS.

**Comment by Thomas830** [comment]
Duh yes of course sorry

So I kept KeepassXC running in GUI as usual and I launched keepassxc-proxy through my shell: Same issue

**Comment by varjolintu** [comment]
@Thomas830 Can you make sure keepassxc-proxy is running before you press New, and if it's running after pressing it (and the saving fails)?

**Comment by Thomas830** [comment]
Yes it was running the whole time.

**Comment by Thomas830** [comment]
Isn't it because I run FF Nightly instead of regular Firefox ?

**Comment by varjolintu** [comment]
You can try if it makes a difference. Sometimes Nightly has some changes that break something in native messaging.

**Comment by Frederick888** [comment]
I'm also experiencing this issue but the connection between my browser plugin and keepassxc seems just fine.

But for example when I'm signing into my WordPress, after submitting the form the browser icon will immediately start blinking and there will be a notification telling to me to click the icon so that the credentials can be saved/updated. However when I click the icon, there would be only one "redetect credential fields" button.

However, if I click submit, then hit ESC right away to keep me on the login page, I can normally use the browser icon to save/update my credentials.

It seems that the most stable workaround currently is to manually right click the input boxes at the login page to trigger the behaviour.

I'm using Firefox 60.0b10 with Plasma.

**Comment by varjolintu** [comment]
@Frederick888 Does it help if you increase the value of `Redirect Allowance` in the settings page?

**Comment by N0153** [comment]
I have the same problem. Unfortunately @Frederick888 workaround doesn't work for me.
Following you'll find some details:

KeePassXC - Version 2.3.3
Revision: 0a155d8

Libraries:
- Qt 5.10.1
- libgcrypt 1.8.2

Operating system: Windows 10 (10.0)
CPU architecture: x86_64
Kernel: winnt 10.0.17134

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

I'm using Firefox Developer Edition 62.0b2 (64 bit).

I don't see any error messages in the browser console. Is there a directory where I can find some log files?

**Comment by varjolintu** [comment]
@N0153 Do you have 1.1.7 installed? See this thread: https://github.com/keepassxreboot/keepassxc-browser/issues/211.

Also, if everything works with Firefox stable, then there's nothing we can do.
