### ISSUE TITLE
Keepassxc should minimize/close window after unlock from the Browser

### ISSUE THREAD

**Issue by apollo13** [keepassxreboot/keepassxc#1715]
## Expected Behavior

Clicking "reopen database" in the browser extension and providing the correct passphrase should remove keepassxc from the foreground

## Current Behavior

Currently keepassxc stays open after unlocking the database

## Possible Solution

I understand that moving the keepassxc application itself to the background might be hard to impossible. Maybe it would be a good idea to use a dialog that can be closed/deleted after unlocking the db.

## Debug Info

KeePassXC - Version 2.3.1
Revision: 2fcaeea

Libraries:
- Qt 5.9.2
- libgcrypt 1.8.1

Operating system: Debian GNU/Linux buster/sid
CPU architecture: x86_64
Kernel: linux 4.15.0-1-amd64

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by droidmonkey** [comment]
Implemented in 2.3.2

**Comment by Lalarian** [comment]
Hello!

I am using keepassXC 2.3.4 from the current AppImage and it still has this problem: I enter password and the main window stays open.

**Comment by droidmonkey** [comment]
@Lalarian please open a new issue with your full context details (including steps to reproduce).

**Comment by Lalarian** [comment]
OK, thank you.

**Comment by 2martens** [comment]
How can this behaviour be turned off? I find this auto-minimizing very annoying as I have to manually make it full-size again and again.

**Comment by varjolintu** [comment]
@2martens There's no option for that at this point. What's your OS?

**Comment by Lalarian** [comment]
Depends on the Situation I'd say, There's the option to enable/disable auto minimizing on copying passwords or usernames to clipboard.

**Comment by 2martens** [comment]
I use LinuxMint and use KeePassXC not only for browser but for other purposes as well. It is tedious to always maximize it again. Previously, I had it on an extra workspace and whenever I needed a password I just switched to the workspace, entered the passphrase and then retrieved the desired password. Now, an additional step is added.
