### ISSUE TITLE
Warning that the used password file format may not be supported in the future

### ISSUE THREAD

**Issue by helmbold** [keepassxreboot/keepassxc#1716]
When I open keepassxc, I get a warning that the used file format may not be supported in the future. I've read and update the database according to this [FAQ](https://keepassxc.org/docs/#faq-security-kdbx4). 

## Expected Behavior
The database should be opened without a warning.

## Current Behavior

After entering the password to unlock the database, I get the following error:

![keepassxc](https://user-images.githubusercontent.com/5079980/37305977-85c11904-2636-11e8-8f70-37a33b41e5d1.png)

## Possible Solution

If the database file format is not up to date, keepassxc should suggest to update it and guide the user to do so. Having to search the FAQs is not that user friendly and I know a lot of people who would simply abandon the program if it would no longer accept an old file format, because they wouldn't be able to upgrade it (or not interested in).

## Steps to Reproduce (for bugs)

1. Select password database, secured with key file and password.
2. Enter password.

## Context

Database settings:

![keepassxc2](https://user-images.githubusercontent.com/5079980/37306082-da0d7a02-2636-11e8-8dbd-37145688b9a1.png)

## Debug Info
KeePassXC - Version 2.3.1
Revision: 2fcaeea

Bibliotheken:
- Qt 5.10.1
- libgcrypt 1.8.2

Betriebssystem: Windows 10 (10.0)
CPU-Architektur: x86_64
Kernel: winnt 10.0.16299

Aktivierte Erweiterungen:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by phoerious** [comment]
It's about the key file, not about the database file. Just generate a new key file and you're good.
