### ISSUE TITLE
writing database failed - access denied

### ISSUE THREAD

**Issue by battlmonstr** [keepassxreboot/keepassxc#1717]
After editing and saving a database it produces an error message banner on top saying:
"Writing the database failed. Access is denied.".

This happens when you try to save a modified database (maybe 1 out of 10 times).
If auto-save is enabled, it happens more often (feels like 1 out of 3 times).

Related issues:
https://github.com/keepassxreboot/keepassxc/issues/1422
https://github.com/keepassxreboot/keepassxc/issues/197

## Expected Behavior
No banner, the save should succeed.

## Current Behavior
Error banner, the file stays unsaved.
After retrying it usually succeeds.

## Steps to Reproduce (for bugs)
1. Open a database.
2. Edit an entry.
3. Save.
4. Repeat from step 2.

## Context

I have no Google Drive or Dropbox. The database is saved on my main SSD drive at "c:\Users\Daniel\Temp\". All the other software works properly, the drive works fine otherwise.

## Debug Info
KeePassXC - Version 2.3.1
Revision: 2fcaeea

Libraries:
- Qt 5.10.1
- libgcrypt 1.8.2

Operating system: Windows 7 SP 1 (6.1)
CPU architecture: i386
Kernel: winnt 6.1.7601

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by battlmonstr** [comment]
![capture](https://user-images.githubusercontent.com/11477595/37314164-f6a1532a-2652-11e8-8970-0630df988bc5.PNG)

**Comment by droidmonkey** [comment]
Are you storing it in Dropbox or Drive? If so, and this really persists, disable safe saves in settings.

**Comment by battlmonstr** [comment]
No, please read the "Context" section.

I was working with the kdbx database today, and noticed that this error sometimes happens much after the editing was done, i.e. if there's a big pause between steps 2 and 3.

Tell me if I can provide some more debug info, because it happens with me quite frequently.

**Comment by droidmonkey** [comment]
Sorry missed the context section. Does the db misbehave when placed anywhere else on that drive? A procmon (from sysutils) output for keepassxc when you fail to save properly would probably be helpful.

**Comment by battlmonstr** [comment]
I'm not sure what happened, but it fixed itself somehow on my side.
I have started testing today, and the first time I edit and save - the error happened again.
Then I made a lot of tries, and it happened just once, this is what I saw
 in the Process Monitor:

![capture](https://user-images.githubusercontent.com/11477595/37400783-49a4918e-2786-11e8-94a7-5051d1d4f7b7.PNG)

Before this ACCESS DENIED error there's a SearchIndexer.exe doing something. That process normally indexes files for windows search functionality. I was sure that I have excluded this path from indexing, so I went to Control Panel - Indexing Options - Advanced and click "Rebuild".

After that I can't reproduce the problem anymore, even with "Automatically save after every change" enabled. If it was a race condition between SearchIndexer and KeePassXC, then maybe I was unlucky yesterday, or maybe I'm lucky now.

So I'm closing this issue, until it starts reproducable again.

P.S. Is this "Safely save" option related to this temporary file "dan2-test.kdbx.dECBOV" appearing near the database? How "safe" it is to disable it if the file is inside Dropbox? Am I risking to get an error while saving, or will the file change be not detected by Dropbox, or somehow be corrupted (like a partial upload happen)?

**Comment by phoerious** [comment]
If you are in Windows and using KeePassXC in a Dropbox folder, turning safe saving off is your only choice. This setting exists for exactly that purpose.

**Comment by phoerious** [comment]
If you are on Windows, a file syncing service gives you access errors and turning off safe saving fixes it, then that's your workaround right there. There isn't much else we can do, unfortunately.

**Comment by samizzo** [comment]
Thanks, yeah, I know it’s not your fault. I was just wondering why it doesn’t actually look like anything is locking the file. It just seems a bit weird.

**Comment by phoerious** [comment]
The file won't be locked persistently. But we don't know when the lock is released.

**Comment by samizzo** [comment]
The conflicting lock should show up in procmon though, surely?

**Comment by bs27975** [comment]
Not trying to pile on here. Just started getting this error, still investigating. No dropbox or file sync service involved.
- this has been working well in the past. Both on direct computer, and on simultaneous laptop accessing this remote file via windows networking [C$, admin share, non-Administrator (administration) account]. Simultaneous as in both computer and laptop have keepass kdbx file 'open' at same time - not that both are being asked to save file at same time. [I am only able to operate one of the keyboards at a time! :-) ]
- not looking for any further action here, until I investigate further, except ...

Running out of disk space (windows complaining when browser cache gets too big), I moved %TEMP% to another drive and made a junction to it. e.g. 'mklink /j C:\Users\...\AppData\Local\Temp T:\C_drive_Underlay\Users\...\AppData\Local\Temp
- unsubstantiated theorizing, pending further investigation ... perhaps the move operation from %TEMP% back to source is failing. The DOS move command not liking it when you cross drives.

(Please) Could:
- a more refined error message be returned in cases where: %TEMP% version creation failed, vs; %TEMP% version move failed, vs; rename subsequent to move failed. 'Access denied' being insufficient to chase down the problem. e.g. Windows read-only file share from laptop would presumably result in the same error message.
- a test case be added to whatever regimen for this directory junction use case be added to the acceptance testing.
[Assuming such a post-build auto-sanity check  element is currently in place.]
