### ISSUE TITLE
Allow ssh keys (for ssh agent) to be associate with specific hosts

### ISSUE THREAD

**Issue by mulcahys** [keepassxreboot/keepassxc#1721]
This is a feature request. Consider extending the ssh-agent support to load specific ssh keys only on specific hosts.

## Expected Behavior

e.g. if I open the same keepassxc file on host A and host B, I may only want to load ssh-key foo on host A and ssh-key blah on host B, even though they're both in the same file.

## Current Behavior

At the moment all keys flagged for use in the ssh-agent will be loaded on all hosts.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Debug Info

KeePassXC - VERSION
Revision: REVISION

Libraries:
- LIBS

Operating system: OS
CPU architecture: ARCH
Kernel: KERNEL

Enabled extensions:
- EXTENSIONS

**Comment by hifi** [comment]
How would you determine what the "host" is? The hostname of the system?

**Comment by hifi** [comment]
FYI I opened an issue for KeeAgent as well (https://github.com/dlech/KeeAgent/issues/215) as this will require coordination with them if implemented in a compatible manner.

**Comment by mulcahys** [comment]
@hifi I think hostname should work. I was initially thinking fqdn but really I don't think this feature needs to be that discriminating. At a user-level, being able to tie keys to hostnames should be sufficient.

**Comment by haakobja** [comment]
If this feature is not implemented yet, maybe it would be an idea to check out the new ssh-add functionality coming in OpenSSH 8.9?

From https://www.openssh.com/agent-restrict.html: 
> OpenSSH 8.9 will include an experimental set of agent restrictions that meet the above requirements, though with some caveats (discussed below). These are built around some two simple agent protocol extensions and a small modification to the public key authentication protocol.
> 
> These extensions allow the user to add destination constraints to keys they add to a ssh-agent and have ssh enforce them. For example, this command:
> 
> $ ssh-add -h "perseus@cetus.example.org" \
>           -h "scylla.example.org" \
>           -h "scylla.example.org>medea@charybdis.example.org" \
>           ~/.ssh/id_ed25519
> Adds a key that can only be used for authentication in the following circumstances:
> 
> From the origin host to scylla.example.org as any user.
> From the origin host to cetus.example.org as user perseus.
> Through scylla.example.org to host charybdis.example.org as user medea.

**Comment by hifi** [comment]
@haakobja That looks like a wonderful feature! We'll definitely add support for that.

This needs to be coordinated with the KeeAgent author so we use the same format.

**Comment by swtrse** [comment]
> If this feature is not implemented yet, maybe it would be an idea to check out the new ssh-add functionality coming in OpenSSH 8.9?

@haakobja That is a good input unfortunately this is not enough since this does not include the most used options "authorized_keys".

What is urgently needed is some way to filter keys for the authorized_keys file to prevent the "Too many authentication failures" error at logintime.

**Comment by Okeanos** [comment]
> > If this feature is not implemented yet, maybe it would be an idea to check out the new ssh-add functionality coming in OpenSSH 8.9?
> 
> @haakobja That is a good input unfortunately this is not enough since this does not include the most used options "authorized_keys".
> 
> What is urgently needed is some way to filter keys for the authorized_keys file to prevent the "Too many authentication failures" error at logintime.

But there is a way to do so with OpenSSH and it very much works with KeePassXC already:

```ssh_config
Host forgejo.org
  IdentityFile ~/.ssh/id_forgejo_rsa.pub
  IdentitiesOnly yes

Host github.com
  IdentityFile ~/.ssh/id_github_ed25519.pub
  IdentitiesOnly yes

#Host *
# do this with `*` host if you want to present only explicitly specified keys
# at all times instead of only in case it has been defined in a more particular rule
#  IdentitiesOnly yes 
```

See the OpenSSH manual on [IdentitiesOnly](https://man.openbsd.org/ssh_config#IdentitiesOnly)

> IdentitiesOnly
> […]
> You can also specify a public key file to use the corresponding private key that is loaded in [ssh-agent(1)](https://man.openbsd.org/ssh-agent.1) when the private key file is not present locally.
> […]

This requires storing the public parts of the KeePassXC managed SSH keys on disk at the specified locations (for each key you want this to work with) but will prevent ssh from presenting arbitrary key pairs to the specified hosts.

KeePassXC may be able to make this user friendlier (in the future) by e.g. automatically putting the public keys by name into a user-specified location at runtime (they are public after all!) but it's still on you to configure your SSH client correctly.

**Comment by droidmonkey** [comment]
Was gonna reply with this. We won't add this as a feature though, that is a lot of coding for something that already exists and is well defined.

**Comment by Okeanos** [comment]
Just as an addendum: my solution still has KeePassXC load ALL keys to the local ssh-agent. The original request was to prevent that. I simply answered a downstream question that restricts ssh from using available keys arbitrarily.

**Comment by droidmonkey** [comment]
Understood, but we still won't implement this feature, it is very niche

**Comment by remus-selea** [comment]
Thumbs up for this feature—even though I see it’s closed. It’s such a hassle to manually add the right SSH key each time, since I don’t want all of them loading automatically on every device.

**Comment by droidmonkey** [comment]
I recommend separate databases for your computer specific ssh keys and using auto open with computer name filtering: https://keepassxc.org/docs/KeePassXC_UserGuide#_automatic_database_opening
