### ISSUE TITLE
when searching, search password field too

### ISSUE THREAD

**Issue by grrrrr** [keepassxreboot/keepassxc#1728]
Feature request:  With the original version of Keepass, you had the option of doing a deep search which included the password field.

I would like to suggest that KeepassXC gets the ability to include the password field when searching.

This can be useful when you are trying to locate entries that may have used the same password and you want to quickly change them to unique passwords instead.

## Expected Behavior
When using the search field, when you enter a known password, bring back all entries with the password set

## Current Behavior
Currently if you search for a known password in keepass, no results are returned.

## Context

Having come from a keepass db that is over 10 years old and many hundreds of passwords, having to check each entry individually to see if it has a reused password is very time consuming.   Having the ability to search the passwords would greatly speed this up.

## Debug Info
KeePassXC - Version 2.3.1
Revision: 2fcaeea

Libraries:
- Qt 5.7.1
- libgcrypt 1.7.6-beta

Operating system: Debian GNU/Linux 9 (stretch)
CPU architecture: x86_64
Kernel: linux 4.9.56-21.pvops.qubes.x86_64

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by RealOrangeOne** [comment]
Likely related to #937 (and thus #551)

**Comment by droidmonkey** [comment]
Covered under the password analyzer
