### ISSUE TITLE
Verification files fails

### ISSUE THREAD

**Issue by falconisup** [keepassxreboot/keepassxc#1729]
## Expected Behavior
Files must be certified. As the guide says : you should always verify that your download matches the signature that is published alongside the release package. 

## Current Behavior
The Kleopatra test showed:  "The data could'nt not be verified ".
This is repeated with each file I loaded.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Debug Info

KeePassXC - VERSION 2.3.1
Revision: REVISION

Libraries:
- LIBS

Operating system: win 8.1 x64
CPU architecture: x64
Kernel: KERNEL

Enabled extensions:
- EXTENSIONS
![keepassxc cert-1](https://user-images.githubusercontent.com/37378125/37427885-8495da46-27c2-11e8-9779-68ea4130c686.png)
![Uploading KeepassXC cert-1.png…]()

![keepassxc cert-exe-x64](https://user-images.githubusercontent.com/37378125/37429864-786069fc-27c8-11e8-96d6-22d925daacb7.png)
![keepassxc cert-x32](https://user-images.githubusercontent.com/37378125/37429870-7b5cc74a-27c8-11e8-9878-7268fb75719d.png)

**Comment by droidmonkey** [comment]
You need to trust our key.
