### ISSUE TITLE
Artifacts or some of that kind around keepasxc icon in tray.

### ISSUE THREAD

**Issue by Niroday** [keepassxreboot/keepassxc#1733]
As for me the problem appears in 2-3 out of 10 starts of keepassxc. 

## Expected Behavior
Icon without artifacts around it.

## Current Behavior
https://i.imgur.com/DBi7zMa.png

## Possible Solution
Don't know.

## Steps to Reproduce (for bugs)
Turn on option "Minimize window at application startup".

## Context
...

## Debug Info
KeePassXC - Version 2.3.1
Revision: 2fcaeea

Libraries:
- Qt 5.10.1
- libgcrypt 1.8.2

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 4.15.8-1-ARCH

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

WM: i3 (w/o DE).
Bar: i3blocks with built-in tray (the problem appears as well with trayer, stalonetray and xmobar).

P.S. If "enabled" in debug info means turned on, it's not correct. All of the extensions except Auto-type are disabled.

**Comment by droidmonkey** [comment]
Your example image is very hard to tell what artifacts are from its small size and imgur and what are from the error you are reporting.

**Comment by Niroday** [comment]
This is a normal state:
![normal](https://user-images.githubusercontent.com/36510085/37470610-ec856778-2878-11e8-8c10-08668379abbe.png)
And these are with artifacts:
![bug2](https://user-images.githubusercontent.com/36510085/37470614-ef5b4bd4-2878-11e8-860a-c51d4c3ae7d8.png)
![bug1](https://user-images.githubusercontent.com/36510085/37470620-f1335bae-2878-11e8-9c87-ab9fa789a6fb.png)
No, i have never experienced anything similar with other tray icons.

**Comment by droidmonkey** [comment]
This doesn't seem like anything that keepassxc is doing to cause this. Do they appear randomly or when you lock/unlock the database?

In image 2 the horizontal lines clearly go behind the icon which leads me to believe noise/corrup data is being "painted" before the keepassxc icon is painted.

**Comment by Niroday** [comment]
They appear when i start keepass, when i restart i3 and when locked and unlocked icons swap. I have 4  more apps with tray icons (claws-mail, pidgin, gajim, gtk-recordmydesktop) and none of them behave like keeppass icon.

**Comment by TheZ3ro** [comment]
maybe a qt bug with i3? Are claws-mail, pidgin, gajim all gtk application?

**Comment by Niroday** [comment]
I got your point. I just installed a few qt apps (qbittorrent, clementine, notepadqq). None of the apps tray icons has similar artifcats.

**Comment by Niroday** [comment]
I removed all svg and svgz icons that could be related to keepass but still no result...

**Comment by Niroday** [comment]
I was wrong. After several restarts i found this:
![qt-bug](https://user-images.githubusercontent.com/36510085/37557285-42206e4e-2a13-11e8-87ce-5141fcc825c2.png)
Now i can't blame keepass...  I'm sorry i wasted your time.

**Comment by droidmonkey** [comment]
No problem, recommend you open an issue with I3
