### ISSUE TITLE
KeePassXC starts with elevated privileges after installation

### ISSUE THREAD

**Issue by rugk** [keepassxreboot/keepassxc#1735]
## Expected Behavior

KeePassXC should not start with admin privileges, ever.

## Current Behavior

It starts with admin privileges once after the installation.

## Possible Solution

AFAIK a privilege drop is hard to accomplish in Windows. You may just have to remove the checkbox to start KeePassXC after the installation.

## Steps to Reproduce (for bugs)

1. Install KeePassXC.
2. At the end of the installer leave the "Start KeePassXC checkbox checked."

## Context

Applications should not use elevated privileges when not necessary. This is a potential security risk, if e.g. a vulnerability in KeePassXC is found.

## Debug Info

KeePassXC - Version 2.3.1
Revision: 2fcaeea

Bibliotheken:
- Qt 5.10.1
- libgcrypt 1.8.2

Betriebssystem: Windows 10 (10.0)
CPU-Architektur: x86_64
Kernel: winnt 10.0.14393

Aktivierte Erweiterungen:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by droidmonkey** [comment]
Good catch

**Comment by phoerious** [comment]
I always tend to not use those checkboxes in installers, because I never know if it won't just launch the application privileged. I wish Windows had a proper installation facility like any other sane platform instead of people creating their own executable installers.

**Comment by rugk** [comment]
AFAIK these boxes _always_ launch the applications privileges, as the installer is usually privileged. (So a solution could also be that the installer only runs with user privileges and only requests admin privileges for the actions where this is needed)

On windows for "proper installations" you may create a MSI.

**Comment by TheZ3ro** [comment]
We already support MSI (https://github.com/keepassxreboot/keepassxc/pull/1153). For the next version we should ditch the crappy NSIS and distribute an official MSI installer instead.
