### ISSUE TITLE
Enable ASLR for keepassxc-proxy

### ISSUE THREAD

**Issue by rugk** [keepassxreboot/keepassxc#1736]
On Windows, this is not yet enabled:

![grafik](https://user-images.githubusercontent.com/11966684/37512269-eebbfb2c-2901-11e8-8252-a448e4f1c9c8.png)

**Comment by tycho** [comment]
I think we should probably enable it for all binaries. I think the flags to add to LDFLAGS are:
* `-Wl,--dynamicbase`, ASLR for 32-bit binaries
* `-Wl,--high-entropy-va` ASLR for 64-bit binaries
* `-Wl,--nxcompat`, compatible with DEP

**Comment by tycho** [comment]
I just checked my builds and they all look like they have it enabled even without those extra linker flags actually. Did you try Process Hacker with `Hacker>Show details for all processes`? That would allow it to see those security features.

**Comment by rugk** [comment]
Yes, I've started Process Hacker as admin. And I see that KeePassXC has DEP and ASLR enabled, and (just confirmed again) keepassxc-proxy only DEP, not ASLR.

**Comment by rugk** [comment]
So make a PR?

**Comment by tycho** [comment]
I'd like to hear from whoever built the release binaries first. See if they can shed some light on what happened.

**Comment by droidmonkey** [comment]
We haven't released 2.3.2 yet

**Comment by tycho** [comment]
I'm not talking about 2.3.2. I mean in the 2.3.1 builds. My MSYS2 does it by default, why doesn't yours?

**Comment by tycho** [comment]
Okay, talked on IRC and figured this out. The changes to add `--high-entropy-va` and friends are already in the tree and on track for 2.3.2 release, but I didn't find them on a "git grep" earlier for whatever reason.
