### ISSUE TITLE
Auto-Type username REF not working as part of field

### ISSUE THREAD

**Issue by funkyHat** [keepassxreboot/keepassxc#1738]
## Expected Behavior
Usernames with embedded references should be supported by AutoType
<img width="675" alt="screen shot 2018-03-16 at 11 09 03" src="https://user-images.githubusercontent.com/65657/37517869-c01d729c-290a-11e8-8f83-28d1c356200c.png">

## Current Behavior
When copying the username directly (⌘B or context menu) the reference is replaced correctly.
However when using auto-type (⌘V) `ad\{REF:U@I:75ABFCEC20CB976472AC79E7044D28F9}` is typed

## Steps to Reproduce (for bugs)

1. create a clone of an entry, making sure that "Replace username and password with references" is ticked
2. edit the username by prepending characters *before* the reference
3. attempt to use auto-type (⌘V to type the entry) (could just be into a text editor)
4. observe `{REF:U...` typed instead of the expected username

## Context

Re-use username info in entries where the username is partly made up from another entry's username

## Workaround
For the time being I have adjusted the Auto-Type sequence instead of the username, but the different field processing behaviour between ⌘B and ⌘V still seems like a bug to me

## Debug Info

KeePassXC - Version 2.3.0
Revision: 4c0ed74

Libraries:
- Qt 5.9.3
- libgcrypt 1.8.2

Operating system: macOS High Sierra (10.13)
CPU architecture: x86_64
Kernel: darwin 17.4.0

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by TheZ3ro** [comment]
This is fixed in version 2.3.1, please update
