### ISSUE TITLE
Use ASLR and DEP for KeePassXC

### ISSUE THREAD

**Issue by rugk** [keepassxreboot/keepassxc#1739]
You do not currently seem to use it:

![](https://user-images.githubusercontent.com/11966684/37512228-d33065a0-2901-11e8-994b-a136d064b134.png)

Please enable it, as that is a basic security feature.

**Comment by TheZ3ro** [comment]
We do have ASLR and DEP enabled since https://github.com/keepassxreboot/keepassxc/pull/371

**Comment by rugk** [comment]
Actually, not. Can you recheck please? I am not aware that Process Hacker would display wrong results there.

If you want to check it by yourself: https://processhacker.sourceforge.io/

**Comment by droidmonkey** [comment]
Yes it is enabled, you have to run process hacker as administrator.

**Comment by TheZ3ro** [comment]
Maybe the compiled binary was in debug mode and not in release mode? :thinking: 
@rugk do you compiled it yourself?

**Comment by rugk** [comment]
No
