### ISSUE TITLE
Password text converted to symbols

### ISSUE THREAD

**Issue by xguse** [keepassxreboot/keepassxc#1740]
I searched the issue but didn't see anything very similar to what I am seeing.

## Expected Behavior

- When viewing/copying a password the original text should be used. 

## Current Behavior

- When viewing/copying a password the text seems to be of the correct length but the characters have all been replaced by symbols.
- Attempting to repair the database returns claim that there is nothing to do.
- Newly created entries work as expected

![](https://i.imgur.com/0YXyzop.png)

## Possible Solution

No idea.

## Steps to Reproduce (for bugs)

1. Successfully unlock db with password and key file.
2. Navigate to pre-existing entry.
3. Die inside.
4. Profit?

## Context

- I recently installed a dev version of keepassxc by mistake.
- I uninstalled that and updated the stable version (original goal) as soon as I realized this from the helpful orange banner (thanks for that).
  - It continued to work correctly for a day or so since then however.
- I rebooted my system for the first time in a while before going home last night (keepassxc was working afaik) and signed in this morning for the first time since (now its NOT working).
- I host the db on dropbox.
- My phone's version still seems to work correctly (keepass2android).
  - I worry that this is because it may be using a cached version of the db however.
- I tried to open the db on regular keepassx but it failed to validate.
  - I suspect that has something to do with the new key file type perhaps?

## Debug Info

__NOTE:__ 
- The info below suggests that I have both the new AND old browser integration enabled. 
- I do not: I just checked to be sure that it is NOT checked.
- The new integration IS enabled however.

```
KeePassXC - Version 2.3.0
Revision: 4c0ed74

Libraries:
- Qt 5.10.1
- libgcrypt 1.8.2

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 4.15.7-1-ARCH

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey
```

**Comment by droidmonkey** [comment]
Are you using an alternative keyboard layout?

**Comment by xguse** [comment]
not knowingly

**Comment by TheZ3ro** [comment]
I think this is a problem with 2.3.0, please use 2.3.1.
The entries are not correctly decrypted, see https://twitter.com/KeePassXC/status/973710931908849664

**Comment by xguse** [comment]
Ohhhh no... (Unless you save them)

**Comment by xguse** [comment]
Thank goodness for Dropbox version history. I mean I have my own back ups but have only been doing these every month. Will be changing that. But Dropbox has the version directly before I saved my "test" new entry while trying to debug this issue.

Also... Followed the Twitter account and turned on notifications. Glad to know of its existence.

Thanks for your help. Restoring the DB and using 2.3.1 solved this issue.

Marking closed.

**Comment by TheZ3ro** [comment]
Sorry for the inconvenience, and always backup.

**Comment by droidmonkey** [comment]
Phew glad everything worked out

**Comment by phoerious** [comment]
In theory, this should be recoverable even after saving by double decryption as long as UTF-8 decoding doesn't destroy any non-unicode characters
