### ISSUE TITLE
KeePassXC-Browser has encountered an error still

### ISSUE THREAD

**Issue by KitchM** [keepassxreboot/keepassxc#1742]
From number 1606;
Okay, I found the appimage version and downloaded it. I made it executable. I changed the shortcut to use it. I opened it and it worked fine.

Next I opened Firefox Quantum Version 59.0 and got the same message. I removed the add-on. Then I searched for the current add-on and installed it. Then I tried again and got the same message: "KeePassXC-Browser has encountered an error: Timeout or not connected to KeePassXC"

I then opened Settings, and selected the Connected Databases tab. There were none found, so I selected to Connect, hoping that it would allow me to search for the correct one, but that doesn't work either.

One would assume that the database that is recognized by the main program (and is open) would be seen by the browser add-on.

**Comment by Larry3460** [comment]
+1

**Comment by varjolintu** [comment]
Check [this guide](https://github.com/keepassxreboot/keepassxc/issues/1559#issuecomment-369508900) for troubleshooting. Please report any progress in this issue.
