### ISSUE TITLE
Changelog entry missing one of the biggest item: Qt5

### ISSUE THREAD

**Issue by ArchangeGabriel** [keepassxreboot/keepassxc#175]
Kudos on release 2.1.0!

However, the changelog lacks a big item, when compared with keepassx 2.0.3 release, namely the switch to Qt5. ;)

**Comment by phoerious** [comment]
KeePassX already made the switch to Qt5 before KeePassXC was born. ;-)

**Comment by ArchangeGabriel** [comment]
Yes, but in the develop branch and thus that change had never been released. keepassx is the last package on my whole system to still depend on Qt4. ;)

I see that you did release it in your -http version of 2.0.3, but maybe a note should be added for people like me coming from keepassx that you included this change.

Anyway, I found it really quickly while looking at the INSTALL.md file and the wiki, so it’s not a big issue at all, but I still think it is worth noting. :)

**Comment by phoerious** [comment]
I hope you're not mad when I close this. :-)

**Comment by ArchangeGabriel** [comment]
No problem. I’m just happy to remove qt4 from my system. ;)
