### ISSUE TITLE
Reveal button shows entry attributes' content but there is no Unreveal

### ISSUE THREAD

**Issue by dwilches** [keepassxreboot/keepassxc#1750]
When editing an entry, in the Advanced tab, you can select an Attribute that has Protected content, and you can see its content with the "Reveal" button, but there is no "Unreveal" button to hide the content.

There are two workarounds I mention below, but not sure if you consider providing the solution below is a better option than the workarounds.

## Possible Solution
We can convert the "Reveal" button to "Unreveal" once you have revealed the content of a hidden attribute. Clicking the "Unreveal" button hides the content and the button reverts back to "Reveal".

## Context
There are two workarounds:
 * Clicking twice the "Protected" checkbox does the trick, but modifies the entry. 
 * Clicking on another attribute and coming back also hides the content

## Debug Info
KeePassXC - Version 2.3.1-snapshot
Build Type: Snapshot
Revision: 871602e

Libraries:
- Qt 5.9.1
- libgcrypt 1.7.8

Operating system: Ubuntu 17.10
CPU architecture: x86_64
Kernel: linux 4.13.0-37-generic

Enabled extensions:
- Auto-Type

**Comment by marcbone** [comment]
also when I have a protected attribute and press reveal, I can modify the attribute. From the name I thought it would only show the content without the possibility to change it (by accident). I think it should be renamed to something like "Hide" or "Mark as Hidden".

**Comment by ba32107** [comment]
Opened https://github.com/keepassxreboot/keepassxc/pull/3877 for this.
@marcbone, I did not change the checkbox to say "Mark as Hidden", because the hidden text makes the functionality clear:
![image](https://user-images.githubusercontent.com/26036493/68998116-ed2d0c80-08a5-11ea-807b-a207dcc65f9d.png)
