### ISSUE TITLE
deniable encryption, hidden volume, steganography

### ISSUE THREAD

**Issue by hex-m** [keepassxreboot/keepassxc#1751]
This issue requests a way to help people protect their secrets from somebody who is able to pressure them.

## Expected Behavior
KeePassXC should empower users by helping them to hide sensitive information in an inconspicuous way.

## Current Behavior
Everyone who knows that somebody uses KeePassXC knows that she has most/all her credentials in one place. This can be used against her (by family, criminal, government) by forcing her to open her password database. (see [rubber-hose cryptoanalysis](https://en.wikipedia.org/wiki/Rubber-hose_cryptanalysis))

This means a user can actually be less secure (e.g. from a bullying partner) by using a password safe than by (re-)using weak passwords that she can remember. She can be force to divulge all credentials instead of only the ones the attacker knows about. As password managers (luckily) become more widespread we should to think about this.

## Possible Solution
Implement "hidden volumes" to enable an invisible Database inside of a Database. This concept was implemented by [VeraCrypt](https://www.veracrypt.fr/en/Hidden%20Volume.html), [pol](https://github.com/bwesterb/pol) and [LibreCrypt](https://github.com/t-d-k/librecrypt).

## Context
As this would need changes to the file format it is relevant that there is an open ticket in the [Keepass Bugtracker](https://sourceforge.net/p/keepass/feature-requests/841/).

**Comment by droidmonkey** [comment]
As you mentioned it's already implemented by other programs. Just use those to create a shadow volume where you place your database. We will not be implementing this in KeePassXC.

**Comment by hex-m** [comment]
Thank you for the answer.

> it's already implemented by other programs.

Deniability becomes much harder when you use "that one tool that's known for supporting hidden containers". Therefore it would be nice to have it in a more widespread application.

> store your database anywhere and split it up however you like

Yes this could be implemented manually but that's cumbersome and error-prone. Tools should help to make security easy.

> I don't see the reason for this complexity.

I tried to explain (and link) the reasons I see. If they make sense depends on the threat/adversary model you want to support of course.

> We will not be implementing this in KeePassXC.

Too bad.

**Comment by droidmonkey** [comment]
`Deniability becomes much harder when you use "that one tool that's known for supporting hidden containers". Therefore it would be nice to have it in a more widespread application.`

If KeePassXC implements it, then we would become well known to having hidden encryption.

The other issue with multiple tools implementing something that is non-standard is every tool does it differently, perhaps not as secure. I can fire up VeraCrypt in about 1 minute, navigate to the hidden partition, launch KeePassXC, and with the portable mode (use the zip distribution) can launch and unlock my database in another 10 seconds.

**Comment by TheZ3ro** [comment]
I read a comment about this suggesting the use of keyfiles.

A keyfile can be just a random file, a photo, a song, whatever you want, that together with your password will unlock the KDBX.
If you select a wrong keyfile the KDBX won't open but KeePassXC (KeePass or every other application) will not be able to tell if the keyfile is wrong or simply if the database is corrupt.

Use a random keyfile and tell that the database got corrupted

**Comment by hex-m** [comment]
@TheZ3ro thank you for the suggestion. This would also work with typing a wrong password. The question is how plausible that deniability would be.
