### ISSUE TITLE
Storing database on a private Keybase.io mount in Windows 7

### ISSUE THREAD

**Issue by rask** [keepassxreboot/keepassxc#1753]
## Expected Behavior

3. Install Keybase.io and KeepassXC on Windows 7
4. Try to open a database in KeepassXC
5. I select a database from my Keybase.io private file share (on K: drive) and it opens normally in read-write mode.

## Current Behavior

1. Install Keybase.io and KeepassXC on Windows 7
2. Open KeepassXC
3. No Keybase K: drive can be found so the KeepassXC database on it is not accessible.

## Context

I need to use my database on multiple systems:

- My home PC Windows 7
- My home office Ubuntu 17.10
- My work office Ubuntu 17.10

Currently, the Keybase.io filesystem for database storage works great on the Ubuntu systems (files are accessible on `/keybase/private/...`, but now I can't seem to get it working on the Windows machine.

The Keybase K: drive itself works and is browsable inside Windows Explorer and appears inside My Computer just fine. When I try to browse for a database file inside KeepassXC the drive is not visible anywhere. When I installed the Keybase.io filesystem (KBFS) on Windows I saw something about Dokan, so I guess that is used for KBFS.

You can read more about KBFS here: https://github.com/keybase/kbfs

## Debug Info
KeePassXC - 2.3.1

Operating system: Windows 7
CPU architecture: 64 bit

Enabled extensions:
- None

---

EDIT: Created an issue at KBFS as well in case they know of anything that helps to get this working: https://github.com/keybase/kbfs/issues/1521

**Comment by TheZ3ro** [comment]
When opening files we use a standard Qt [QFileDialog](https://github.com/keepassxreboot/keepassxc/blob/bff80dfc707cd41b80c75a3cb2ef2653341f0a1a/src/gui/FileDialog.cpp#L38)

Can you try if other Qt application can open files from the K drive?

**Comment by rask** [comment]
I'll have to see if I have any other Qt apps on my Windows. Feel free to suggest any in case you know of ones that are easy to remove afterward. :)

**Comment by rask** [comment]
OMFG. Should've known this will happen. After a few reboots, the KBFS drive just magically appeared into the KeepassXC GUI and I could open the database on it normally.

So I guess this can be closed. Damn Windows being Windows. :D
