### ISSUE TITLE
Autotype on another computer

### ISSUE THREAD

**Issue by zonfromron** [keepassxreboot/keepassxc#1755]
(For some reason my (new) account was flagged so I have to re-post this, sorry!)

Is it in any way possible to connect two computers together via USB, and have keepassxc running on computer A (offline), doing the autotype on computer B? This way the database is never at risk as computer A is offline ALWAYS.

Alternatively, is it possible to do something similar via keepass proxy?

**Comment by droidmonkey** [comment]
Your best bet is to use the proxy through an ssh link. But you will likely have to modify the proxy to get that to work.

**Comment by zonfromron** [comment]
Note that this is not for use with keepassxc-browser, I need to autotype in other applications (not just the browser).

**Comment by zonfromron** [comment]
Yes, an auto-type server is exactly what is needed. Yubikey 4 is not sufficient since it has a maximum length restriction on the password and is cumbersome to use as this. 

Is it possible to fund development of such a function? Or are you not at all interested in developing it?

**Comment by TheZ3ro** [comment]
IMHO this will be a niche feature, and also not very trivial to implement.

**Comment by SkyWheel** [comment]
You might need something like "Pastilda".
