### ISSUE TITLE
Show zxcvbn crack time estimation

### ISSUE THREAD

**Issue by graingert** [keepassxreboot/keepassxc#1757]
The entropy value isn't very easy to understand in terms of real world value. Weak/Poor/Good do not really describe what they mean.

## Expected Behavior
The password field would include the entropy and the estimated crack time

## Current Behavior
The password field only shows the entropy, which is difficult to relate to a real world value.

## Possible Solution
Include the estimated crack time next to the entropy value.

## Context
Currently trying to set a password policy that keeps users informed. Setting a entropy value is difficult to explain to all users.

Libraries:
- zxcvbn

Operating system: GNU
CPU architecture: any
Kernel: Linux

Enabled extensions:
- None

**Comment by TheZ3ro** [comment]
But so, we should display cracktime with a cracking-station cracking "power" or with a desktop one?

I agree cracktime is more user-friendly then entropy, but still is not a very useful information. 
Using a desktop hashing power most of relatively bad passwords will show high cracking time, on the other hand using an high hashing power will show bad cracking time for relatively good passwords.

Note: For cracking power I mean hash-per-second computation power

**Comment by graingert** [comment]
zxcvbn comes with four reasonable defaults

**Comment by TheZ3ro** [comment]
Currently we are using https://github.com/tsyrogit/zxcvbn-c (the C version of zxcvbn) and I don't see any default or even mention to crack time, so I think we need to do it in keepassxc itself

**Comment by graingert** [comment]
I was thinking of the reference JS library

**Comment by TheZ3ro** [comment]
I will look into it and see what I can do, anyway added this issue to the wishlist

**Comment by droidmonkey** [comment]
There are way more variables at play when it comes to crack time, entropy being only one of them. It may be easier for an uninformed end user to comprehend crack time, but it is a false pretense. As @TheZ3ro mentioned, these assumptions would have to be disclosed somehow to make the number mean anything.
