### ISSUE TITLE
AutoType problems with a delay

### ISSUE THREAD

**Issue by Penn452** [keepassxreboot/keepassxc#1758]
When signing in to Hotmail or Gmail, it is necessary to first enter one's user address, hit enter, wait until the next page comes up, then enter one's password, and hit enter.

To log in I have the following AutoType code for my Gmail account:

{USERNAME}{ENTER}{PAUSE 4000}{PASSWORD}{ENTER}

This is supposed to enter my username, hit enter, wait 4 seconds for the next page to come up, then enter my password and log me in.

Instead of this happening, AutoType enters my username and password in one long string in the first field which is supposed to be only for the username.

For example, suppose my Gmail address is bozo@gmail.com and my password is PASSWORD. What KeePassXC enters into the email address field on Gmail is the following:

bozo@gmail.comPASSWORD

Then it hits enter, and Gmail then brings up a page saying the email address I entered is invalid. KeePassXC does not enter anything in the second page that comes up, being finished typing as soon as it enters the combined username/password string and pressing Enter.

This requires me to use the clipboard instead to copy my password to, which I'd rather not do, and makes the entire process of logging in to my email much less automatic than it should be.

I apologize if this has already been reported.

**Comment by droidmonkey** [comment]
Use {DELAY 4000}

**Comment by TheZ3ro** [comment]
`PAUSE` is not a valid keyword in KeePassXC (https://github.com/keepassxreboot/keepassxc/wiki/Autotype-Custom-Sequence) and in KeePass neither (https://keepass.info/help/base/autotype.html)

Use `DELAY` instead of `PAUSE` like @droidmonkey said :+1:

**Comment by Penn452** [comment]
Thank you so much gentlemen. I should have just read the manual. I feel a little stupid now but at least it's working. :)

KeePassXC is a very fine product.
