### ISSUE TITLE
"Lock database on lock session" can be cancelled out after resume if changes have been made

### ISSUE THREAD

**Issue by r0ckarong** [keepassxreboot/keepassxc#1760]
## Expected Behavior
I'm not sure that the security concept here makes sense.
I have KPXC set to lock the DB when I lock my screen session. When unsaved changes to the DB have occured (typically permissions from the browser extension), the DB is NOT saved on these changes but will ask for confirmation AFTER unlocking the session since the dialog is triggered by the session lock. It does not prevent the lock, so the user never sees this dialog until they resume the session. This means I can simply cancel out of the save dialog and have full access to the PW database. This means an attacker just somehow has to circumvent the session password to gain full access to my unlocked database.

I've only tested this on Linux so far but since this is a basic process I would think it applies to all platforms.

## Current Behavior
I would expect the dialog after session resume not to allow cancellation but only discarding changes (potential loss of data) or saving (potentially saving an unwanted state). Maybe it needs a third behavior configurable as a default.

## Possible Solution
Ideally there would be a conflict resolution tool that stores a changed DB that was forced to lock by session lock and allows the user to review without exposing either of the databases to remain unlocked.

## Steps to Reproduce (for bugs)
1. Open database
2. Connect database to browser extension
3. Modify credential permissions for an item
4. Activate "Lock database when session is locked or lid is closed"
5. Lock session/close lid
6. Unlock session
7. Cancel the dialog
8. Access (still) unlocked database

## Debug Info
KeePassXC - Version 2.3.1
Revision: 2fcaeea

Libraries:
- Qt 5.9.1
- libgcrypt 1.7.8

Operating system: Ubuntu 17.10
CPU architecture: x86_64
Kernel: linux 4.13.0-36-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- YubiKey

**Comment by droidmonkey** [comment]
This is a duplicate.
