### ISSUE TITLE
SSH key generation

### ISSUE THREAD

**Issue by Mirokko** [keepassxreboot/keepassxc#1761]
Add "Generate SSH key" button. This will resolve (partly) issues with key formats.

## Expected Behavior

Add button "Generate key" between Private key label and Attachment option, which allows user to generate new key. It will generate attachment.
![image](https://user-images.githubusercontent.com/11059471/37645792-7fca038a-2c30-11e8-9f2a-c8212e6bd477.png)

## Possible Solution

As an alternative, you can add third option to "Private key" section, which launch little wizard with some fields like "Comment", "Format type", etc...

## Context

In real world ill be using these keys to connect to servers (one for each server), so having option to generate right inside program is a plus for me.

**Comment by hifi** [comment]
The problem with that is that it's a highly security critical operation to generate keys and I wouldn't want to be responsible if our method is bad in any possible way.

If we decide to go deeper into SSH integration this may become reasonable but right now I can't promise anything.

**Comment by ToKaTpoHb** [comment]
We cant just use ssh-keygen on linux?

**Comment by hifi** [comment]
@ToKaTpoHb That would only work on Linux or macOS and would require wrapping an external program in odd ways. Windows users would be left out and that's a big target audience.

**Comment by ToKaTpoHb** [comment]
Yes but, untill we go deeper into SSH integration?..

**Comment by njfox** [comment]
> The problem with that is that it's a highly security critical operation to generate keys and I wouldn't want to be responsible if our method is bad in any possible way.

Is it more security critical than generating any of my other passwords? As far as implementing it, there are probably libraries out there already to do the heavy lifting (openssl seems to be able to generate a key with just a few lines of code) but I’m not sure how much that would complicate dependencies.

**Comment by ToKaTpoHb** [comment]
@hifi we have [libssh](https://www.libssh.org/features/), so why we couldnt use it? Looks like it could generate a keypairs, supports rsa and ed25519...

**Comment by hifi** [comment]
Since KeeShare was added to KeePassXC, generating an RSA key already exists in the code base. We can expose this to generate SSH keys if it is deemed secure enough.

**Comment by mmaridev** [comment]
Would be very useful. Otherwise I need to generate outside, import as attachment and shred the generated key with ssh-keygen.

**Comment by hifi** [comment]
I have a commit in my personal 2.7.0 feature branch for key generation for RSA, ECDSA and Ed25519 keys. It will be PR'd once #6209 lands and a PR for #4334 is merged as well at it depends on a small refactor in that.

The reason why I changed my mind about this is that replacing gcrypt with Botan in #6209 will give us simple interfaces to generate all supported key types which will offload all cryptographic operations to a single and suitable library which is used for everything else in KeePassXC as well.

If someone wants to test the early work (please don't use the generated keys for anything yet) I have all of the changes in this branch: https://github.com/hifi/keepassxc/commits/feature/openssh-sk-botan

**Comment by Okeanos** [comment]
@hifi is there any chance your PR for GUI SSH key generation will make the 2.8.0 release? I have been watching this (and the PR) for quite a while and I am very much looking forward to this because it would make using SSH for non technically inclined folks WAY easier.
