### ISSUE TITLE
Allow for 7-digit TOTP codes

### ISSUE THREAD

**Issue by gergesh** [keepassxreboot/keepassxc#1762]
Codes used by Authy partners (such as Coinbase and HumbleBundle) use 7 digits for their 2fa codes. These are currently not supported by the program.

## Expected Behavior
In the set up menu for a totp code, have an option to use seven digits.

## Current Behavior
The only options are six and eight digits.

## Debug Info
KeePassXC - Version 2.3.1
Revision: 2fcaeea

Libraries:
- Qt 5.10.1
- libgcrypt 1.8.2

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 4.15.9-1-ARCH

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by CueHD** [comment]
To get the correct 7 digit TOTP code simply ignore the first digit displayed from the 8 digit code.

**Comment by weslly** [comment]
Last time I checked, it wasn't possible to export Authy's TOTP seed, and I'm not even sure they use the same algorithm (RFC6238), but both Humble Bundle and Coinbase also use google authenticator (RFC6238) as an alternative method for TOTP, so I'm closing this one.

**Comment by CueHD** [comment]
For exporting Authy seeds
https://gist.github.com/JacobJohansen/5f688d45049be440b8ee87cc5e854b75

**Comment by gergesh** [comment]
Also, they do use the RFC6238 algorithm for generating their keys, only they do so with a 10-second interval.

**Comment by Lantizia** [comment]
Is this best left closed?
I've just used the method CueHD linked to and got myself a otpauth:// like the below (seed is randomised for security obviously)...

otpauth://totp/Uphold?secret=3425654562564842548644285248154281425814518645218642518645216854&issuer=Uphold&digits=7&period=10

I've tried what CueHD said in his first post about just setting it to 8 digits and ignoring the first digit but I just get this on KeePassXC 2.3.4 (p.s. I've set it to time step 20 sec because that is what I witness the official Authy app actually doing - changing code every 20 seconds - even though &period=10)...

![image](https://user-images.githubusercontent.com/10448369/48907194-a78a5f00-ee5e-11e8-8dba-9ebe96908097.png)
![image](https://user-images.githubusercontent.com/10448369/48907236-bcff8900-ee5e-11e8-83d6-91436d30a28f.png)

I've tried this with 10 secs too, no luck - same problem as above.

So it'd be sure nice to have this work with the 7 digits that Authy seems to use.

If we can get this re-opened as a feature request?

**Comment by droidmonkey** [comment]
This will work in v2.4.0. You can try it using the latest snapshot: https://snapshot.keepassxc.org

**Comment by Lantizia** [comment]
Nuh uh it seems - Just backed up my database and ran the 2.4.0 latest AppImage build against it...

![image](https://user-images.githubusercontent.com/10448369/48909222-993f4180-ee64-11e8-8171-0253784c70c9.png)

Again tested with both 10sec and 20sec

I chose 8 digits again - despite it actually being 7 digits... just leaving it on default did the same screenshot as above too.

**Comment by Lantizia** [comment]
Actually just re-read your post and ran the seed through base32 (like such... - again randomised seed data for security)...

```
stevenm@ic-dvpl044:~$ printf 3425654562564842548644285248154281425814518645218642518645216854 | base32
GM2DENJWGU2DKNRSGU3DIOBUGI2TIOBWGQ2DEOBVGI2DQMJVGQZDQMJUGI2TQMJUGUYTQNRUGUZDCOBWGQZDKMJYGY2DKMRRGY4DKNA=
```

Although it does generate an 8 digit code - the last 7 digits (or even the first 7 digits) are not the same as the 7 digits the official Authy app shows.

**Comment by droidmonkey** [comment]
They claim to follow RFC 6238, but 7 digit tokens are NOT STANDARD.

https://www.twilio.com/docs/authy/api/one-time-passwords

I attempted to look for documentation on how the 7 digits are chosen, but coudn't find it. Unless someone can post that here this will remain closed.

**Comment by weslly** [comment]
@Lantizia the method from CueHD only works correctly for default 6-digit codes. You can try this:
1. Add `console.log("SECRET:" + i.secretSeed);` before the `console.groupEnd();` line
2. Convert the code to base32 using this python snippet:

```
import base64, binascii
print(base64.b32encode(binascii.unhexlify('SECRET HERE')))
```

You will also need to use 10sec instead of 20.

**Comment by Lantizia** [comment]
@weslly well following that idea I ended up with an i.secretSeed being shown on console looking like this... (i.e. the format looks like this - not the actual data)...

`1a2b3cd45ef6789ab01c234de567f890`

Then running it through that python I get...

`DIVTZVC66Z4JVMA4ENG6KZ7YSA======`

I'm not sure if this should go in to KeePassXC with or without the equal signs.  But ultimately I've tried with and also without... on 10sec and 20sec, on 6 digits and on 8 digits and nothing seems to resemble what Authy generated.

@weslly is this at all meant to work with 7-digit codes like @CueHD said previously to just use 8 digits and ignore the first one?

**Comment by Lantizia** [comment]
![image](https://user-images.githubusercontent.com/10448369/49136631-172a9f00-f2e2-11e8-931b-438717b0cd56.png)

Bingo

**Comment by Lantizia** [comment]
That is using the "DIVTZVC66Z4JVMA4ENG6KZ7YSA======" style seed from my last post - but without the equals signs... also using TOTP Settings of '10;7'

The only thing that doesn't quite right now ... is authy is counting down using 20 seconds (whilst KeePassXC is using 10) - and most of the time the codes don't match - but every now and then you get the same code.

Any thoughts?

Either way '10;7' works just fine - perhaps this option (i.e. 7 digits) should be on the UI?

**Comment by droidmonkey** [comment]
After reading the authy documentation its not odd at all. They will accept codes up to 1 minute after they "expire" and even up to 30 seconds BEFORE they are valid. Why they chose a 10 second refresh and still accept up to 1.5 minutes of codes is beyond me. Security theatre, likely to apease a Govt contract that required 10 second refresh.
