### ISSUE TITLE
Allow copying/pasting of *entries* (entire records)

### ISSUE THREAD

**Issue by macau23** [keepassxreboot/keepassxc#1764]
It would help if I could copy/paste and even drag and drop entire entries/records between different keepassxc datafiles.

## Expected Behavior
I'd like to do this using drag and drop or copy/paste.

## Current Behavior
I can't (or I can't find it).

Edit: there is a merge option under Database> Merge...

**Comment by droidmonkey** [comment]
Duplicate of #172
