### ISSUE TITLE
Build Error on Ubuntu 16.04

### ISSUE THREAD

**Issue by njfox** [keepassxreboot/keepassxc#1767]
Release 2.3.1 and `develop` are failing to build on Mint 18/Ubuntu 16 with the following error:

```
/home/nick/software/keepassxc-2.3.1/src/crypto/SymmetricCipherGcrypt.cpp: In static member function ‘static int SymmetricCipherGcrypt::gcryptAlgo(SymmetricCipher::Algorithm)’:
/home/nick/software/keepassxc-2.3.1/src/crypto/SymmetricCipherGcrypt.cpp:53:16: error: ‘GCRY_CIPHER_CHACHA20’ was not declared in this scope
         return GCRY_CIPHER_CHACHA20;
                ^
/home/nick/software/keepassxc-2.3.1/src/crypto/Crypto.cpp: In static member function ‘static bool Crypto::checkAlgorithms()’:
/home/nick/software/keepassxc-2.3.1/src/crypto/Crypto.cpp:98:31: error: ‘GCRY_CIPHER_CHACHA20’ was not declared in this scope
     if (gcry_cipher_algo_info(GCRY_CIPHER_CHACHA20, GCRYCTL_TEST_ALGO, nullptr, nullptr) != 0) {
```

libgcrypt is installed from @phoerious ' repo and added to the environment per the wiki instructions:

```
$ export
declare -x CINNAMON_VERSION="3.4.6"
declare -x CMAKE_INCLUDE_PATH="/opt/libgcrypt20-18/include:/opt/gpg-error-127/include"
declare -x CMAKE_LIBRARY_PATH="/opt/libgcrypt20-18/lib/x86_64-linux-gnu:/opt/gpg-error-127/lib/x86_64-linux-gnu"

```

Any ideas on how to troubleshoot?

**Comment by phoerious** [comment]
You also need to set include and linker paths for the compiler, i.e., CPATH and LIBRARY_PATH or -I and -L compiler flags.

**Comment by njfox** [comment]
Would someone mind updating the wiki with these (more detailed) instructions? I’ve been having a similar issue with libargon from the PPA and I eventually gave up and built argon from source to work around it. It looks like others had some issues with argon as well.

**Comment by anatoli26** [comment]
Same problem here. The issue is that the latest version depends on libgrypt 1.7.0+ (though the documentation says 1.6.0) and on Ubuntu 16.04 only 1.6.7 is installed and it doesn't include CIPHER_CHACHA20. And it's mostly impossible to update libgcrypt to a higher version manually (i.e. building from sources) as some core packages like systemd depend on its dependency: libgpg-error (i.e. libgcrypt 1.7.8 depends on libgpg-error 1.27 and systemd depends on libgpg-error 1.21).

If I understand it correctly, the functionality in KPXC that depends on CIPHER_CHACHA20 is not required for normal operation, so maybe there could be a cmake option to disable it as for now the latest version is unbuildable on the latest Ubuntu LTS (16.04).

**Comment by anatoli26** [comment]
In my case with libargon2 built from their repo and everything libgrypt-related (libgcrypt20-dev, libgcrypt20, libgpg-error-dev and libgpg-error0) taken and manually installed on top of 16.04 from 17.10 (artful), KPXC built successfully.

But then, after restoring the libgrypt-related packages to their previous state, KPXC refused to start complaining that CIPHER_CHACHA20 is not available, i.e. the libgcrypt 1.7.x run-time package (without '-dev') is also needed and it should be resolvable by ldd. And you can check what depends in your system on libgrypt package by `apt-cache rdepends --installed libgcrypt20`

**Comment by njfox** [comment]
> everything libgcrypt-related (libgcrypt20-dev, libgcrypt20, libgpg-error-dev and libgpg-error0) taken and manually installed on top of 16.04 from 17.10 (artful), KPXC built and ran successfully.

Did you pass any extra arguments when building beyond exporting the gcrypt env vars as shown in the wiki? Would you mind pasting `cmake` and `make` commands you ran so I can troubleshoot my build environment?

**Comment by njfox** [comment]
Strange, that definitely doesn’t work on my machine with the PPA version of libgcrypt. @phoerious could there be some sort of issue with libgcrypt for Xenial in the PPA or have you confirmed it’s working as expected?

**Comment by DeckerSU** [comment]
Sorry for opening the issue, but i had a same problem with build on Ubuntu 16.04.6 and wrote a small [script](https://gist.github.com/DeckerSU/b64267000ae2b9daed4178aecd2948d9) which should help to build in same cases. It doesn't use PPA, just download `libgcrypt` and `libgpg-error` from `ftp.gnupg.org` with signatures verification and build. Also, gist contains comment how to build with other version of Qt (different from 5.5.1) on Ubuntu 16.x . Result of my build:
```
KeePassXC - Version 2.5.0-snapshot
Build Type: Snapshot
Revision: a07ea12

Qt 5.12.0
Debugging mode is disabled.

Operating system: Ubuntu 16.04.6 LTS
CPU architecture: x86_64
Kernel: linux 4.4.0-161-generic

Enabled extensions: None

Cryptographic libraries:
 libgcrypt 1.7.6
```
Hope this will help somebody.

**Comment by zaharcelac** [comment]
> Sorry for opening the issue, but i had a same problem with build on Ubuntu 16.04.6 and wrote a small [script](https://gist.github.com/DeckerSU/b64267000ae2b9daed4178aecd2948d9) which should help to build in same cases. It doesn't use PPA, just download `libgcrypt` and `libgpg-error` from `ftp.gnupg.org` with signatures verification and build. Also, gist contains comment how to build with other version of Qt (different from 5.5.1) on Ubuntu 16.x . Result of my build:
...
> Hope this will help somebody.

Thanks! Was able to build 2.5.3 with your script.

```
KeePassXC - Version 2.5.3

Revision: f8c962b

Qt 5.5.1
Debugging mode is disabled.

Operating system: Ubuntu 16.04.6 LTS
CPU architecture: x86_64
Kernel: linux 4.15.0-88-generic

Enabled extensions: None

Cryptographic libraries:
 libgcrypt 1.7.6
```
