### ISSUE TITLE
Generate invalid TOTP code

### ISSUE THREAD

**Issue by smonv** [keepassxreboot/keepassxc#1772]
I tried to create TOTP for 2FA on some sites like discord, slack but the code generated by keepassxc always invalid.

## Expected Behavior
It should generate valid TOTP code with default settings

## Current Behavior
Generate invalid TOTP code with default settings (Default RFC 6238)

## Steps to Reproduce (for bugs)
1. Setup TOTP with time-based key generated by Discord or Slack
2. Copy TOTP code generated by keepassxc and paste to given site
3.
4.

## Context
I have to disable 2FA from Discord, Slack and various sites. On some site like google, github, the first code was invalid but the second code valid.

## Debug Info
KeePassXC - 2.3.1
Revision: REVISION

Libraries:
- qt - 5.10.1
- libgcrypt - 1.8.2

Operating system: ArchLinux
CPU architecture: x86_64
Kernel: 4.15.11

Enable extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- YubiKey

**Comment by droidmonkey** [comment]
Your system time is likely not correct.

**Comment by smonv** [comment]
@droidmonkey Thank you for help. After investigate, I found my machine not sync time correctly with ntp. After enable systemd-timesyncd.service, everything back to normal.

**Comment by droidmonkey** [comment]
No problem at all!
