### ISSUE TITLE
Icons are rough and "pixly"

### ISSUE THREAD

**Issue by klarani** [keepassxreboot/keepassxc#1774]
The icons in the MacOS version just went very pixled today, out of nowhere. 
It was not like that before. Is it only on my computer?

<img width="472" alt="screen shot 2018-03-23 at 15 16 03" src="https://user-images.githubusercontent.com/7469066/37835430-6ef529ea-2eb0-11e8-8b08-c7f011a7bbf8.png">

## Design-contribution wanted?

I work with UX and design and I would like to contribute with some simplifications to the interface. How can I do that in the best way? :)

---
## Debug Info

KeePassXC - Version 2.3.1
Revision: 2fcaeea

Libraries:
- Qt 5.9.3
- libgcrypt 1.8.2

Operating system: macOS Sierra (10.12)
CPU architecture: x86_64
Kernel: darwin 16.7.0

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by phoerious** [comment]
They are not pixly, they are just not blurry anymore, because we don't scale them up anymore.
We are planning replacing all icons with better ones in 2.4 (see #1705), so bear with us.
