### ISSUE TITLE
KeepassXC 2.3.1 crashed kdbx-Database file from KeePass 2

### ISSUE THREAD

**Issue by MisterT87** [keepassxreboot/keepassxc#1777]
Hey Guys,

I coming from the Windows side, also my database was created within WIndows and with KeePass 2.3.8 (kdbx file format).
Most of the time I opened the database file (over Webdav) with my KeePass (Windows) and KeePass2Android (Phone) at the same time.

Normally on my linux OS I mount (automatically) my Webdav space with davfs2 and fstab.

I told KeePassXC to save the database automatically after each change and only close the database if desktop will be locked - nothing more.

Today I changed 1 entry (database was saved auto), finished my other work on this machine and rebooted my machine without closing the database manually or closing KeePassXC.
As I was on my Windows machine, tried to Open up my database file (with KeePass 2.3.8) and cant open the database: Header mismatch...
I watched my Webdav folder: and the database file has 0 bytes (before it was: 87KB).

After it: I wasnt able to open the database file - not with my KeePass from the windows side, KeePassXC or KeePass2Android.

I can exclude: It has nothing to do with davfs2 related stuff or with my webdav folder - Only the database file was corrupt, other files working fine until now.

Note: I didnt lost my database file anyway - was able to reproduce the complete database out of my phone from cache !

## Debug Info
KeePassXC - 2.3.1
Revision: -

Operating system: Linux Mint 18.3
CPU architecture: x86_64
Kernel: 4.10

Enabled extensions:
Nothing (as far as i know)

Info: I am Windows now - I can only post this info
I Installed KeePassXC from official Ubuntu PPA: https://launchpad.net/~phoerious/+archive/ubuntu/keepassxc

**Comment by MisterT87** [comment]
however, maybe its davfs2 - seemed to be wrong mount routine in new kernel ?

Give me some time to test - If I will find a solution its possible to add to FAQ for people who also use webdav mountings for keepassxc

**Comment by droidmonkey** [comment]
Did you disable safe saves?

**Comment by MisterT87** [comment]
Yup was enabled - I now disabled it

But I think that was not the problem: I tested the following on my webdav folder (without loaded keepass database) ->

mounted my webdav folder / created a simple text file and remounted webdav folder: boom, 0byte text file (before remount: 7bytes)
If I copied a file directly onto my webdav folder (same directory - to create a file copy) the created file copy was instant 0byte files.

Testing around with "use_locks 0" in davfs config...

**Comment by droidmonkey** [comment]
I dont recommend that you disable safe saves, was just wondering if you did. Looks like this is not a KPXC issue though.
