### ISSUE TITLE
does XC automatically record login info for websites as does Robocop (windows)

### ISSUE THREAD

**Issue by danostg** [keepassxreboot/keepassxc#1778]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Debug Info

KeePassXC - VERSION
Revision: REVISION

Libraries:
- LIBS

Operating system: OS
CPU architecture: ARCH
Kernel: KERNEL

Enabled extensions:
- EXTENSIONS

**Comment by phoerious** [comment]
Care to elaborate what you mean?

**Comment by danostg** [comment]
It would be very helpful to have a LInux program that when going to a new website and loggin in, Robocop captures all relevant data, the website name, address, log in name, log in password and asks to accept all that and record that login, or amend the name, then records all that so that the next time we go to that site, roboform opens to that site automatically and we then can select to login automatically, edit the login, past the info to the website, and log in at the touch of just one key.  Is there something in Linux that does all that automatic stuff for us automatically, like roboform?

**Comment by danostg** [comment]
It would be very helpful to have a LInux program that when going to a new website and loggin in, Robocop captures all relevant data, the website name, address, log in name, log in password and asks to accept all that and record that login, or amend the name, then records all that so that the next time we go to that site, roboform opens to that site automatically and we then can select to login automatically, edit the login, past the info to the website, and log in at the touch of just one key. Is there something in Linux that does all that automatic stuff for us automatically, like roboform?

**Comment by muchqs** [comment]
You mean Roboform? That would be so helpful. In fact I've been trying to find a replacement for Roboform that's as convenient, but so far haven't found any (for Windows)...

**Comment by droidmonkey** [comment]
Sounds like it would be better if roboform could use keepassxc as the backend for storing the captured credentials
