### ISSUE TITLE
Snap version does not have permission to open db in a folder I own

### ISSUE THREAD

**Issue by WillemHobers** [keepassxreboot/keepassxc#1779]
I had keepassx installed in xubuntu 18.04; this is the snap-version. It worked well. Until I moved the folder containing its database to a folder which I have mounted through sftab.
There was no way to get to that folder through keepass.
So I installed the deb-version.
That did allow me to open the db from the new location.
 
## Expected Behavior
I should be able to open the db.

## Current Behavior
I get a permission denied message when trying to open the folder.

## Possible Solution
installing the deb-version

## Steps to Reproduce (for bugs)
Try to move to a folder which is mounted through fstab on another partition.

## Debug Info

KeePassXC - 2.3.1
Revision: REVISION

Libraries:
- LIBS

Operating system: Linux Xubuntu-18-04 4.15.0-12-generic #13-Ubuntu SMP Thu Mar 8 06:24:47 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

CPU architecture: ARCH
Kernel: KERNEL

Enabled extensions:
- EXTENSIONS

**Comment by droidmonkey** [comment]
Read the faq.
