### ISSUE TITLE
Cannot connect to chromeIPass

### ISSUE THREAD

**Issue by ligyxy** [keepassxreboot/keepassxc#178]
In chromeIPass, it returns "Is KeePassHttp installed and is KeePass running?"

![screen shot 2017-01-23 at 11 34 52 am](https://cloud.githubusercontent.com/assets/2060045/22212796/fd11dec0-e15f-11e6-80d4-40b317297820.png)

I am also using another forked keepassx version https://github.com/keithbennett/keepassx , it works well with chromeIPass.

Also, I don't see http options on 2.1.0, is it normal?

**Comment by RealOrangeOne** [comment]
Duplicate of #177
