### ISSUE TITLE
keepassxc-cli is not supplied with OSX build

### ISSUE THREAD

**Issue by samm-git** [keepassxreboot/keepassxc#1782]
I would like to have ability to use keepassxc-cli on the OSX. However, it seems that it is not installed/compiled on OSX, so it is not possible w/o compilation from source.

## Expected Behavior
keepassxc-cli in the `/Applications/KeePassXC.app/Contents/MacOS` folder

## Current Behavior
```
$ ls
KeePassXC	keepassxc-proxy
```

## Possible Solution
Add keepassxc-cli to the OSX installer

## Context
I think having CLI interface for the OSX user will help to anyone looking for automation with keepassxc

Operating system: OSX
CPU architecture: amd64
Kernel: Darwin

**Comment by louib** [comment]
Thanks for reporting!

The issue of `keepassxc-cli` not being present in the `dmg` was already raised in https://github.com/keepassxreboot/keepassxc/issues/1697.
