### ISSUE TITLE
Support for DES-EDE3-CBC?

### ISSUE THREAD

**Issue by derekjc** [keepassxreboot/keepassxc#1783]
I'm trying to use a 3rd party platform generated ssh private key. When I select the key, I briefly see the following message:
-----------------------------
Unknown cipher: DES-EDE3-CBC
-----------------------------

## Expected Behavior
It should be able to open DES-EDE3-CBC keys

## Current Behavior
Throws an error mentioned above

## Context
Trying to store a ssh private key so that I can use it with ssh-agent.

## Debug Info

KeePassXC - 2.3.1
Revision: 2fcaeea

Libraries:
- Qt 5.5.1
- libgcrypt 1.8.1

Operating system: Ubuntu 16.04.4 LTS
CPU architecture: x86_64
Kernel: linux 4.13.0-37-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by phoerious** [comment]
You should really get rid of that key and crest a new on. Or convert it to a stronger cipher. We won't support legacy cryptography

**Comment by Kleidersack** [comment]
Unfirtunately this is the default-format for puttygen. Please at least provide the infomration how to generate the key with a proper encryption in the error message.

**Comment by phoerious** [comment]
Don't use PuTTYgen, use KiTTY.

**Comment by nithinphilips** [comment]
In case someone else runs into the same issue, it appears that the DES-EDE3-CBC is the cipher used by PUTTYgen for password protecting the key. The key itself may still be good and readable by KeePassXC.

I used PuTTYgen to clear the password and re-export (Conversions -> Export OpenSSH key) the key. The new file worked without issues in KeePassXC.

Remember to delete the unprotected key after adding it to KeePassXC.

**Comment by phoerious** [comment]
Do not use 3DES keys.

**Comment by michaelkebe** [comment]
Use puttygens Conversions -> Export OpenSSH key (force new file format).

**Comment by DaaNMaGeDDoN** [comment]
For those that are like me and are on Linux, the puttygen command parameter you are looking for is `-O private-openssh-new`, without the -new part keepassxc will throw the error it doesnt recognize the cipher. No need to remove the passphrase, you can put that in the password field of the keepassxc entry, maybe for safety even change it with a random one and only store that on the keepassxc entry. 
Now i can finally remove the (passphrase protected) file from any places i have stored it on. Thanks for the inspiration so i finally found what was the cause and solution!

@phoerious in the scenario like mine where i know i probably a machine that has that key authorized and i know that is probably the only key that is authorized, isnt there is a very good reason to at least store that key somewhere safe? Failing to import leaves the only option to have that keyfile outside keepassxc. Less secure, imho. Your repeated "dont use CBC" dont help with importing the key. I already knew, i just need to make sure that if i find such a host in the future i have that key somewhere, somewhere safe in keepassxc. Goes without saying i will not check the box to automatically load it into the agent. So my question: fair enough, we should not use it, but why repeat that? Is that an answer to the question: how to import legacy cbc keys into keepassxc? What are we missing? How is kitty the answer? Am i wrong for using kde Konsole or having used putty in the past? The fact you keep repeating yourself makes me think there is more to it than "dont use cbc!!!", please elaborate.

**Comment by droidmonkey** [comment]
This is over 7 years old. You really should not be using 3DES, it's broken due to very short key lengths.https://www.encryptionconsulting.com/why-3des-or-triple-des-is-officially-being-retired/
