### ISSUE TITLE
All passwords in database were corrupted

### ISSUE THREAD

**Issue by fcremo** [keepassxreboot/keepassxc#1784]
I opened with KeepassXC 2.3.0-snapshot a .kdbx database created and last updated with Keepass 2.38, added an entry and saved.
When I reopened the database all the passwords except the one of the entry I just added decrypt to garbage, by Keepass and KeepassXC.
Fortunately I had a recent backup

## Expected Behavior
KeepassXC should not corrupt the database

## Current Behavior
KeepassXC corrupted my password database

## Steps to Reproduce (for bugs)
I tried to reproduce the bug but didn't manage to do it.
What I did was
1) Create a database using keepass
2) Open the database with keepassxc and add an entry
3) The database got corrupted

## Debug Info
KeePassXC - Version 2.3.0-snapshot
Build Type: Snapshot
Revision: 3f7f1aa

Libraries:
- Qt 5.10.1
- libgcrypt 1.8.2

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 4.15.12-1-ARCH

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by phoerious** [comment]
Please upgrade to 2.3.1. It's a display bug that has already been fixed.

**Comment by TheZ3ro** [comment]
Duplicate of #1661
