### ISSUE TITLE
Bad line wrapping on macOS with legacy key format warning

### ISSUE THREAD

**Issue by jsoref** [keepassxreboot/keepassxc#1788]
## Expected Behavior
Don't include manual line wrapping, so it should render like this:

> You are using a legacy key file format which
> may become unsupported in the future.
> 
> Please consider generating a new key file.

## Current Behavior
Line wrapping:
![image](https://user-images.githubusercontent.com/2119212/38040423-7cd13916-327d-11e8-8732-e794e8bbda68.png)

> You are using a legacy key file format which
> may become
> unsupported in the future.
> 
> Please consider generating a new key file.

## Possible Solution

Text should be stored like this:
> You are using a legacy key file format which may become unsupported in the future.
> 
> Please consider generating a new key file.

## Steps to Reproduce (for bugs)
1. Try to open a `.kdbx` using a `.key` with a "legacy" format...

## Debug Info
KeePassXC - Version 2.3.1
Revision: 2fcaeea

Libraries:
- Qt 5.9.3
- libgcrypt 1.8.2

Operating system: macOS High Sierra (10.13)
CPU architecture: x86_64
Kernel: darwin 17.4.0

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by phoerious** [comment]
When we don't add a line wrap there, other platforms don't break it at all or only break before the last word.
