### ISSUE TITLE
Make libmicrohttpd optional when using WITH_XC_HTTP=OFF

### ISSUE THREAD

**Issue by klemens** [keepassxreboot/keepassxc#179]
As `libmicrohttpd` is only used for the http feature (and is not linked otherwise), it should not be required unless `WITH_XC_HTTP=ON`.

I don't know if this is the correct solution, but wrapping the `find_package(LibMicroHTTPD REQUIRED)` inside a `if(WITH_XC_HTTP)` fixes this problem for me.

## Your Environment
* KeePassXC: 2.1.0
* cmake: 3.7.1
* OS: Arch Linux

**Comment by phoerious** [comment]
If I remember, correctly, @droidmonkey wanted to get rid of that dependency in favor of QNetworkAccessManager.

**Comment by phoerious** [comment]
I added a commit to my KeePassHTTP hotfix branch that removes the dependency when building with WITH_XC_HTTP=Off. This will go into 2.1.1.

**Comment by droidmonkey** [comment]
This is correct, I have the full intention of removing the libmicrohttpd dependency in my next round of coding. I will keep this PR's goal in mind and make sure the QtNetworking is not required unless compiled in.
