### ISSUE TITLE
Not possible to configure which password file to save keepassxc-browser passwords to?

### ISSUE THREAD

**Issue by macau23** [keepassxreboot/keepassxc#1791]
I have two password files open in KeepassXC, and I can save passwords and read passwords. I have the "Search in all opened databases" option enabled, but I cannot see how I choose which database KeepassXC saves passwords to which come from KeepassXC-Browser.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Debug Info

KeePassXC - VERSION
Revision: REVISION

Libraries:
- LIBS

Operating system: OS
CPU architecture: ARCH
Kernel: KERNEL

Enabled extensions:
- EXTENSIONS

**Comment by varjolintu** [comment]
The passwords are saved to the activated tab with opened database. Currently there's no way to select the database through any option when saving new credentials.

**Comment by macau23** [comment]
I better be careful not to switch tab then :)

**Comment by macau23** [comment]
The tab-order that the databases are shown with seems to be random too.

**Comment by varjolintu** [comment]
We can try to make this feature to KeePassXC 2.4.0. There's still some time left :)
