### ISSUE TITLE
Store secure notes [New Feature]

### ISSUE THREAD

**Issue by lordraiden** [keepassxreboot/keepassxc#1794]
First of all this is a new feature request but I don't know how to label the post or even if I can, sorry.

I would like to have a different type of entry where you can store long texts, not just passwords, It would be a good way to store software licenses, recovery codes and stuff like that. Right now I can use the password field but it doesnt feel right.
Maybe the Notes field could have an option to hide the text or something. Last pass has this feature and it request your password again if you want to see it.

**Comment by droidmonkey** [comment]
There is already an open issue to hide notes by default. You can use the attributes in the advanced options of an entry or even the attachments.
