### ISSUE TITLE
doesn't detect Google login fields?

### ISSUE THREAD

**Issue by muchqs** [keepassxreboot/keepassxc#1796]
Doesn't detect Google (Gmail etc) login fields (win10, Vivaldi)

## Expected Behavior

Browser extension should show login infos?

## Current Behavior

Doesn't show any login info when I click on the extension button, only says it's successfully connected to database.

But if I right click on the login box (username), and choose "keepassxc-browser" -> "Fill User + pass", then a popup shows and says multiple logins detected and then the logins show up when I click on the extension button.

## Possible Solution

KeePass 2 with Keepass Helper extension works fine using the HTTP method, it detects all logins when I click on the login field. 

## Steps to Reproduce (for bugs)

1. mail.google.com
2. click on login field
3. no login shown
4.

## Context

I would like it to behave more like KeePass 2 or Roboform.
Take Gmail for example:
1. Click on login field
2. click on extension button, shows a list of logins
3. choose a login
4. auto-fills the login field and click Next
5. click on password field
6. choose a login from extension button
7. auto-fills the password field and submit
The above steps work fine with Keepass 2 with "keepasshelper" extension but doesn't work with KeePassXC and its new extension.

## Debug Info

KeePassXC - 2.3.1
Revision: 2fcaeea

Libraries:
- Qt 5.10.1
- libgcrypt 1.8.2

Operating system: Windows 10 (10.0)
CPU architecture: x86_64
Kernel: winnt 10.0.14393

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP) (I don't have this checked in Settings?)
- SSH Agent
- YubiKey

Also browser is Vivaldi v1.14.1077.60 (Stable channel)

**Comment by droidmonkey** [comment]
This is already reported under the keepassxc-browser issues (different repository).
