### ISSUE TITLE
[Feature Request] Human-readable password generation

### ISSUE THREAD

**Issue by RealOrangeOne** [keepassxreboot/keepassxc#180]
Instead of completely random password, generate more human-readable, pronounceable passwords

## Expected Behavior
option when generating passwords for a 'pronounceable' flag, swapping out length for number of words, and possibly adding additional characters to the end that arent words for extra complexity?

## Current Behavior
No such option exists

## Possible Solution
Adding the flag?
I dont know of an implementation, not a C++ dev, but possibly something hooking in to the system dictionary to pick some random words?

## Context
Alterative password managers allow creating of these passwords. This makes entering password into other machines much easier, as whole words are far easier to memorise. 

##### Possible Examples:
`correct-horse-battery-staple` (oldie but a goodie)
`galaxy-quarry-scalp-pledge-yaw-poach-pabst-lift-typic-oxide`
`syrup-gamut-nimbus-lase-posse-hansel-pus-hate-eaten-idaho-)8$FH` (note the extra chars on the end?)

**Comment by TheZ3ro** [comment]
Duplicate of https://github.com/keepassxreboot/keepassxc/issues/21

**Comment by RealOrangeOne** [comment]
Is infact duplicate. Closing

**Comment by phoerious** [comment]
Thanks for the suggestion, though.
