### ISSUE TITLE
SSH agent not removing key on database close

### ISSUE THREAD

**Issue by nez-nix** [keepassxreboot/keepassxc#1804]
I'm using KeepassXC on Fedora 27 KDE.

The options state "Remove key from agent when database is closed/locked".

The SSH agent integration is working and I have KeepassXC unlocking one of my existing SSH keys when my database is unlocked.
The problem is, when I lock the database the SSH key is still unlocked in ssh-agent. If I completely quit KeepassXC then the key is removed from ssh-agent but the option states that it should also lock on closing the database.

**Comment by hifi** [comment]
How do you lock the database? With a timeout, key combination, clicking on the lock button? There's a known bug *closing* a database does not remove a key but locking should always work.

Are you using GNOME Keyring? What's in the environment variable *SSH_AUTH_SOCK*?

**Comment by nez-nix** [comment]
You're right. If I close the database it doesn't remove the key, but clicking on the padlock does.
I'm using the latest version of KDE that ships with Fedora 27, so I don't know if there are any GNOME Keyring components in use, but my SSH_AUTH_SOCK is this:
SSH_AUTH_SOCK=/tmp/ssh-1YseGctKe26Q/agent.1579

I will try and remember to use the padlock until the bug is fixed. Cheers.

**Comment by hifi** [comment]
You are indeed hitting issue #1199. You can subscribe to it to get notified once a proper fix lands.

You are also not using GNOME Keyring but the stock OpenSSH ssh-agent with that socket path so all is good on that front.

**Comment by nez-nix** [comment]
Subscribed to #1199  Thanks!!
