### ISSUE TITLE
KeePassXc-Browser does not recognize an open instance of KeePassXC

### ISSUE THREAD

**Issue by powerriegel** [keepassxreboot/keepassxc#1805]
On my Firefox Quantum 59.0.2 64bit on Ubuntu 16.04.4, KeePassXC-Browser does never recognize the opened and unlocked KeePassXC Window. I always need to click on reload to make in working. 

## Expected Behavior
It should check every few seconds. 

## Current Behavior
One must click the reload button to continue. 

## Possible Solution
don't know. 

## Steps to Reproduce (for bugs)
1. Go to preferences > Browser Integration > General
2. Enable Firefox and click ok (just to be sure it is enabled)
3. Open and unlock your kdbx file
4. In Firefox, go to a page you want to log in
5. KeePassXC-Browser won't recognize the open and unlocked database

## Debug Info
KeePassXC - Version 2.3.1
Revision: 2fcaeea

Bibliotheken:
- Qt 5.5.1
- libgcrypt 1.8.1

Betriebssystem: Ubuntu 16.04.4 LTS
CPU-Architektur: x86_64
Kernel: linux 4.13.0-37-generic

Aktivierte Erweiterungen:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

KeePassXC-Browser Version: 1.0.1

**Comment by varjolintu** [comment]
This might happen because the connection can not be established on-the-fly. If you activate the Browser Integration support in KeePassXC the browser extension must restart the native messaging pipe. This is why you must click the Reload button.

**Comment by einhander** [comment]
I have the same behavior  on my debian testing system.

**Comment by varjolintu** [comment]
Is keepassxc-proxy process running? Or does it quit after this error happens?

**Comment by einhander** [comment]
> Is keepassxc-proxy process running?

No

> does it quit after this error happens?

It seems to quit after some time.
Is a log of keepassxc-proxy process available?

**Comment by varjolintu** [comment]
Sorry, no. You'd need to debug the Unix domain socket and see what happens, or compile a debug version of the proxy and attaching it to a debugger.

**Comment by einhander** [comment]
That should  I do to  debug the Unix domain socket?

**Comment by varjolintu** [comment]
@powerriegel Do you use an AppImage, snap or something similar?

**Comment by powerriegel** [comment]
No, I use the PPA. Appimages does not work on 16.04.

**Comment by varjolintu** [comment]
Thanks. I'll test the 16.04 and PPA myself.

**Comment by varjolintu** [comment]
Yes, KeePassXC needs to be open before the extension can connect to it. If KeePassXC is closed and reopened the extension need to be reconnect manually. At this point there's no way to detect this automatically and I really don't like to implement any polling methods to the extension.

**Comment by powerriegel** [comment]
Ok, I will try to use autostart and minimize it. It is neccessary to have the db unlocked?

**Comment by varjolintu** [comment]
Yes. You cannot get credentials from a locked database, which is quite logical..

**Comment by seboss666** [comment]
Hello,
I'm encountering the same kind of problem here. Using Manjaro XFCE up-to-date, KeepassXC 2.3.1 and Firefox Plugin 1.1.0. I'm using the freshly released Firefox 60, but it was the same yesterday with 59.0.2.

In fact, the proxy seems to close just by switching to another tab, or just by loosing window focus. We constantly needs to manually reloads and even sometimes it's not enough, the proxy stays alive until we click the button to get to the generator. I'm still not sur how I can dig further with my current technical level :(

**Comment by varjolintu** [comment]
@seboss666 Upgrade to KeePassXC 2.3.3 and see if the error still persists.

**Comment by droidmonkey** [comment]
If anything this is a extension issue and if it persists needs to be reported over in the [keepassxc-browser](/keepassxreboot/keepassxc-browser) repo.
