### ISSUE TITLE
Open unlock dialog a global modal popup on Gnome

### ISSUE THREAD

**Issue by janvlug** [keepassxreboot/keepassxc#1806]
When unlocking KeepassXC, a popup window appears to enter the unlock password. However, this popup window is not globally modal. This is a risk as when you are looking to your keyboard when entering your complex password, because in the meanwhile another applications could have gotten the focus (e.g. a chat application).

## Expected Behavior
When the unlock window appears, all other applications are inaccessible, to protect you from entering the master unlock password somewhere else.

## Current Behavior
When the unlock window appears, you can still select other applications for entering text.

## Possible Solution
I suggest to make the unlock window a globally modal popup on Gnome. Probably it would be good to make this behaviour optional as I assume that not all users would like this.

**Comment by janvlug** [comment]
I was thinking of the standard Gnome 'Authentication required' system wide modal pop up window that you for example get when you try to access a system crash report in abrt.

**Comment by hifi** [comment]
This only affects the global auto-type unlock window and not when unlocking a database from within the main window. A generic secure desktop solution would need to cover both.
