### ISSUE TITLE
Keepassxc with Firejail (fixed)

### ISSUE THREAD

**Issue by Jarfr** [keepassxreboot/keepassxc#1807]
Hi , issue with firejail , when i write my password to open my .kdbx , keepassxc freez 

So if i want open it i must do : firejail --noprofile keepassxc , so it's not a keepassxc problem but a firejail profile , that happen to the march update . 

My keepassxc.profile : 
```
# Firejail profile for keepassxc
# This file is overwritten after every install/update
# Persistent local customizations
include /etc/firejail/keepassxc.local
# Persistent global definitions
include /etc/firejail/globals.local

blacklist /run/user/*/bus

noblacklist ${HOME}/*.kdb
noblacklist ${HOME}/*.kdbx
noblacklist ${HOME}/.config/keepassxc
noblacklist ${HOME}/.keepassxc
include /etc/firejail/disable-common.inc
include /etc/firejail/disable-devel.inc
include /etc/firejail/disable-passwdmgr.inc
include /etc/firejail/disable-programs.inc

include /etc/firejail/whitelist-var-common.inc

caps.drop all
net none
no3d
nodvd
nogroups
nonewprivs
noroot
nosound
notv
novideo
protocol unix
seccomp
shell none
private-bin keepassxc
private-dev
private-etc fonts,ld.so.cache,machine-id
private-tmp

memory-deny-write-execute
noexec ${HOME}
noexec /tmp
```

If someone have firejail profile with good parameters , i take it ^^

Thx 

Operating system: Parrot gnu/linux
CPU architecture: x86_64
Kernel: 4.14.0

**Comment by Hocceruser** [comment]
Please note that `firejail --noprofile keepassxc` is almost equal to `keepassxc`.

Could it be that this issue is equal to https://github.com/netblue30/firejail/issues/1791? If yes, you can just try https://github.com/netblue30/firejail/blob/master/etc/keepassxc.profile as this issue is already fixed.

**Comment by Jarfr** [comment]
Thx Hocceuser , i take this profile :  https://github.com/netblue30/firejail/blob/master/etc/keepassxc.profile but not working for me , so i 've some change : 
i comment  : nodbus and add (like your link profile) noblacklist ${HOME}/.mozilla
and my first problem come from : #memory-deny-write-execute , i keep it comment and now it work .
I post my keepassxc.profile if someone want it : 

# Firejail profile for keepassxc
# This file is overwritten after every install/update
# Persistent local customizations
include /etc/firejail/keepassxc.local
# Persistent global definitions
include /etc/firejail/globals.local

noblacklist ${HOME}/*.kdb
noblacklist ${HOME}/*.kdbx
noblacklist ${HOME}/.config/keepassxc
noblacklist ${HOME}/.keepassxc
# 2.2.4 needs this path when compiled with "Native messaging browser extension"
noblacklist ${HOME}/.mozilla

blacklist /run/user/*/bus

include /etc/firejail/disable-common.inc
include /etc/firejail/disable-devel.inc
include /etc/firejail/disable-passwdmgr.inc
include /etc/firejail/disable-programs.inc

include /etc/firejail/whitelist-var-common.inc

caps.drop all
machine-id
net none
no3d
nodvd
nogroups
nonewprivs
noroot
nosound
notv
novideo
protocol unix
seccomp
shell none

private-bin keepassxc
private-dev
private-etc fonts,ld.so.cache,machine-id
private-tmp

# 2.2.4 crashes on database open
#memory-deny-write-execute
noexec ${HOME}
noexec /tmp# 

Thx for help

**Comment by Hocceruser** [comment]
Well, maybe you should tell the firejail guys that nodbus didn't work for you? You could open an issue or directly do a pull request (https://github.com/netblue30/firejail/edit/master/etc/keepassxc.profile) (I do not know which one they prefer)

**Comment by Jarfr** [comment]
Look , on man firejail web site , i don't see "nodbus" ...: https://firejail.wordpress.com/features-3/man-firejail-profile/
On shell with nodbus : 
Reading profile /etc/firejail/keepassxc.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-devel.inc
Reading profile /etc/firejail/disable-passwdmgr.inc
Reading profile /etc/firejail/disable-programs.inc
Reading profile /etc/firejail/whitelist-var-common.inc
Error: line 29 in /etc/firejail/keepassxc.profile is invalid
 nodbus is "invalid" so no work .
