### ISSUE TITLE
Can't run OS X DMG binary on OS X 10.10.5

### ISSUE THREAD

**Issue by sts10** [keepassxreboot/keepassxc#181]
The [download page](https://keepassxreboot.github.io/download#mac) says the OS X binary package will work for OS X 10.7 and above. I'm running 10.10.5; however when attempting to run the program I get the following alert:

```
You can’t use this version of the application “KeePassXC” with this version of OS X.
You have OS X 10.10.5. The application requires OS X 10.12 or later.
```

## Expected Behavior
Thought I could run program from binary with OS X 10.10.5

## Current Behavior
Program giving an error in the form of an alert quoted above, then program does not run. 

## Possible Solution
Suppose I could upgrade to OS X 10.12 and try again, but I'm filing this issue because either (a) I'm an idiot and doing something stupid or (b) the [download page](https://keepassxreboot.github.io/download#mac) should be changed to reflect that users need OS X 10.12 or higher to run use the binary. 

## Steps to Reproduce (for bugs)
1. Be running OS X 10.10.5
2. Download the DMG file from the KeePassXC downloads page
3. Drag application to Application folder as instructed
4. Double click the KeePassXC icon in Applications 
#
## Your Environment
* KeePassXC version/commit used: DMG downloaded says KeepassXC version is 2.1.0
* Operating System and version: OS X 10.10.5

**Comment by TheZ3ro** [comment]
I'm looking into this. Probably I've forget something when building the DMG file.

**Comment by daohoangson** [comment]
I'm running 10.11.6 and it also doesn't run.

**Comment by DarwinAwardWinner** [comment]
Could this be the cause? http://stackoverflow.com/questions/39310079/mac-app-package-backwards-compatibility-error-you-cant-use-this-version-of-t

**Comment by PercussiveRepair** [comment]
Same issue. I'm running 10.11.6.

**Comment by naure** [comment]
As a workaround, you can run it from the terminal, which does not check the OS version:

     /Applications/KeePassXC.app/Contents/MacOS/KeePassXC &

**Comment by TheZ3ro** [comment]
Can you guys try this DMG ?
[KeePassXC-2.1.0.dmg.zip](https://github.com/keepassxreboot/keepassxc/files/729804/KeePassXC-2.1.0.dmg.zip)

**Comment by koichirose** [comment]
@TheZ3ro can confirm this zip works on 10.11.6
Thank you

**Comment by PercussiveRepair** [comment]
Works for me too

**Comment by TheZ3ro** [comment]
Ok fine, I will insert this on the website. Closing this issue

**Comment by dessalines** [comment]
Where is this download available on the website? I can't find it on the mac osx downloads page.

**Comment by sts10** [comment]
It's not _super_ clear: on [this page](https://keepassxc.org/download/#mac), click the link that says "Binary bundle for macOS 10.10 and later"

Wonder if it'd be more clear to just make a big ole "Download for macOS" button, rather than use the technical "Binary bundle" term.
