### ISSUE TITLE
Bug  "{PASSWORD}" in notes shows actual password in cleartext after 2.2.4 to 2.3.1 upgrade.

### ISSUE THREAD

**Issue by zaphod627** [keepassxreboot/keepassxc#1812]
In my notes from 2.2.4 I had "{USERNAME}{TAB}{PASSWORD}{TAB}{PASSWORD}" for quick copy and paste along with other misc notes. After upgrading to 2.3.1 "{USERNAME}" was replaced with actual username and {PASSWORD} was replaced with actual password IN CLEARTEXT in both the notes tab and the new notes area above. This seems like a bug to me, can anyone confirm if this is desired behavior.

Obviously I can take those out of my notes but I just thought I should report it as this is the best password manager I have used. Thanks for your great work.

## Expected Behavior
Do not change notes of "{PASSWORD}" or "{USERNAME}" as actual password and username in cleartext.

## Steps to Reproduce (for bugs)
Save in notes in 2.2.4 "{USERNAME}{TAB}{PASSWORD}{TAB}{PASSWORD}" then open in 2.3.1, at least on my system.

## Debug Info
2.2.4 upgrade to 2.3.1 both self compiled

Libraries:
qt-5.9.4
libgcrypt-1.8.2

Operating system: Slackware Linux
CPU architecture: x86_64
Kernel: 4.15.15 

Enabled extensions:
autotype

**Comment by droidmonkey** [comment]
I agree this is not desirable behavior

**Comment by TheZ3ro** [comment]
We already have the function to filter passwords from URLs, we just need to apply it when displaying all the fields.

This code need to be refactored along with the entry-reference code.
Right now it's just an undocumented mess
