### ISSUE TITLE
Auto-type dialog showing multiple options when only one is configured

### ISSUE THREAD

**Issue by sergeevabc** [keepassxreboot/keepassxc#1813]
KeepassXC 2.3.1, Windows 7 x64

---

There is an entry for mail provider with login, password, URL.

Website of mail provider is processed by default sequence, autotype works fine and without popup.

Also, there are two custom sequences in this entry for desktop mail client:
- window title “Mail Server Password Required - imap.████.██”, {PASSWORD}{ENTER}
- window title “Outgoing server (SMTP) Password Required - smtp.████.██”, {PASSWORD}{ENTER}

Keepass autotypes them without popup as well, whereas KeepassXC unexpectedly invites to choose.

![](https://pli.io/DS9Ap.png)

**Comment by TheZ3ro** [comment]
This is the only entry that expose 2 sequences? Can you make a screenshot of the autotype tab of that specific entry?
If the entry is exposing 2 different sequence this is the correct behavior but it really doesn't seem to be the case.

**Comment by sergeevabc** [comment]
If I specify one custom sequence per window title, popup is not expected. (That is, popup is expected when there are _more than one_ sequences that refer to the _same_ window title.)

> Can you make a screenshot of the autotype tab of that specific entry?

Actually I made a text copy above, but if you insist on getting a graphical one… here it is.

![](https://pli.io/DiWlZ.png)

**Comment by TheZ3ro** [comment]
I saw the text above but I was suspecting that maybe something was missing.

This seems indeed a bug, I will try to reproduce it since I can't understand what is causing it just by your report. (I need to see the actual entry data in the kdbx)

**Comment by sergeevabc** [comment]
@TheZ3ro, are you available via ICQ, IRC, Jabber, Telegram, Tox?
If not, then drop me a mail to 0f3ae5d6@beconfidential.com and I could provide you with kdbx.

**Comment by TheZ3ro** [comment]
If you have confidential data in the kdbx there is no need to send it to me, otherwise you got a mail from thezero@posteo.net

I will redact both email addresses in this issue after it

**Comment by droidmonkey** [comment]
Please provide a simple test case that reproduces this error. For example, create a sample database with one entry in it that points to your desktop mail client with the same scenario, fake password, fake username. If it replicates, post your steps here, otherwise this will be closed.

**Comment by sergeevabc** [comment]
The database to reproduce the error was provided by e-mail 203 days ago.
@TheZ3ro, do you have it?

**Comment by droidmonkey** [comment]
Please send it to team@keepassxc.org. You can encrypt the message using our PGP key: http://pool.sks-keyservers.net/pks/lookup?op=get&search=0x105D8D57BB9746BD

**Comment by sergeevabc** [comment]
Database: https://app.box.com/file/338266264251
Password: TheZeroLostDB

![](https://pli.io/2CjJWl.png)

![](https://pli.io/2CjIm7.png)

1. Load email-popup.kdbx
2. Open https://imap.vivaldi.net/ in browser (e.g. Palemoon with [Keepass Helper][1] extension)
3. Use KeepassXC auto-type — _user_ and _password_ are filled-in without popup as expected

Repeat the steps with Thunderbird/Fossamail e-mail client. 
Again, be sure to install Keepass Helper extension which adds hostname in window’s title.

![](https://pli.io/2CjDkY.png)

![](https://pli.io/2Cju1M.png)

![](https://pli.io/2CjrMH.png)

Since entry contains different sequences for IMAP and SMTP, the following popup is not expected.

![](https://pli.io/2CMsm8.png)

[1]: https://addons.mozilla.org/en-US/firefox/addon/keepass-helper/

**Comment by droidmonkey** [comment]
Cannot access that file.

**Comment by sergeevabc** [comment]
There are [other addons][1] at Mozilla which could add hostname in window’s title.

Alas, your answer is not a solution as it breaks the work-flow learned from Keepass which is

![](https://pli.io/2CwKhU.png)

Let’s set KeepassXC like that.

![](https://pli.io/2Cw1Vq.png)

And try again

![](https://pli.io/2CjIm7.png)

With these settings I expect no popus but
* default Auto-type sequence for a window with _https://imap.vivaldi.net/_ in its title
* custom sequence for title _Mail Server Password Required - imap.vivaldi.net_
* custom sequence for title _Outgoing server (SMTP) Password Required - smtp.vivaldi.net_

[1]: https://addons.mozilla.org/en-US/firefox/search/?platform=windows&q=url%20in%20title

**Comment by droidmonkey** [comment]
I made a bad screenshot. In my text I recommended UNCHECKING the URL setting.

**Comment by sergeevabc** [comment]
That’s the point: unchecking URL setting is not an option as it breaks the work-flow.
```
* DOES NOT WORK THEN ---> default auto-type sequence for a window with https://imap.vivaldi.net/webmail/ in its title
* custom sequence for title Mail Server Password Required - imap.vivaldi.net
* custom sequence for title Outgoing server (SMTP) Password Required - smtp.vivaldi.net
```

**Comment by droidmonkey** [comment]
Why not add another window for the browser window name like you did for the Thunderbird windows?

**Comment by sergeevabc** [comment]
> Why not add another window for the browser window name like you did for the Thunderbird windows?
That is URL field for. URL field match is expected to use default sequence. And if some custom title match, then custom sequence is expected without popup, because displaying popup with both default and custom sequences for custom title is totally irrelevant.

> You can't have it both ways…
There is some kind of miscommunication here. Open the database in **Keepass** with the following settings and see for yourself that everything I ask for is possible for years.

![](https://pli.io/2CwKhU.png)
