### ISSUE TITLE
Feature Request: Custom Scripted attributes

### ISSUE THREAD

**Issue by faximilie** [keepassxreboot/keepassxc#1816]
Provide a method of retrieving custom attribute information from scripts.

Example of use: gathering 2FA codes from a hardware source through scripts

## Possible Solution
Call script with STDIN providing the context of the entry (Username, URL, Title, etc) and retrieve the STDOUT and use it.

## Context
This would be really helpful to automate login to certain websites, and allow 2FA to be retrieved from an external source without keeping them in the database file, incase it's compromised.

It would also provide an extendable pseudo script hook system.

Personally I'd like to be able to use 2FA codes from a hardware key, and gather other data from other sources. I'm sure someone else will come up with nice methods of extending keepassxc with this.

I understand there could be security issues with this approach.

**Comment by droidmonkey** [comment]
By 2FA do you mean TOTP or a fixed value?

**Comment by TheZ3ro** [comment]
I don't really like executing external processes from my password manager TBH

**Comment by faximilie** [comment]
@droidmonkey I mean TOTP or HOTP. Or really any arbitrary information that could be scripted in.

As for @TheZ3ro's concern, I'm sure it would be implemented optionally. Not to mention that I'm sure it would not provide any increased risk from malicious code then there already is, if properly implemented.

I personally would like my password manager to be able to use arbitrary dynamic data.

**Comment by TheZ3ro** [comment]
One thing is to use arbitrary dynamic data safely and another thing is executing custom scripts that directly receive data from the password manager. I'm ok with the first one but skeptic on the second one.

We already closed other proposal about executing custom scripts #1373 #1201 and from what I'm aware KeePass doesn't support thing like this (without an external plugins) or any other password manager

**Comment by droidmonkey** [comment]
@louib can you get totp code from CLI?

**Comment by louib** [comment]
@droidmonkey yep, you can get the seed with the `show` command.
```
keepassxc-cli show ~/database.kdbx entry1 -a "TOTP Seed"
h6al 5qfx eh72 kfsn nmu4 kkv4 qfmx xpdg
```

@faximilie would that solve your problem?

**Comment by yan12125** [comment]
Sounds similar to pkcs#11 modules for ssh-agent?
