### ISSUE TITLE
Support for Homebrew Cask

### ISSUE THREAD

**Issue by gophercall** [keepassxreboot/keepassxc#182]
Would be great to support installation Homebrew Cask (https://caskroom.github.io/).

A lot of FOSS software is easily installable from Homebrew Cask.

**Comment by vitorgalvao** [comment]
KeePassXC is now in homebrew-cask, thanks to @joschi (https://github.com/caskroom/homebrew-cask/pull/29341).

**Comment by TheZ3ro** [comment]
Nice, closing.
