### ISSUE TITLE
Browser integration: multiple URLs

### ISSUE THREAD

**Issue by Thulium-Drake** [keepassxreboot/keepassxc#1821]
## Expected Behavior

Allow for multiple specifications for URLs on which the use of a credential is allowed.
## Current Behavior

You can only set 1 url (or wildcard) on a credential, even if the systems on those urls share a common authentication source (e.g. LDAP)
## Possible Solution

I think the best implementation for this would be the same as how one would 'describe' Auto-Type sequences and windows, like so:

URL: https://auth.example.com
URL-1: https://auth.examplesotherdomain.com
URL-2: https://somehost (which would be in the local network's search domain)

(P.S. for those who might not know, https://*.example.com is a valid URL ;-), but that doesn't allow for mulitple domains or the single word DNS names)
## Context

I'm trying to migrate from all auto-type to a more integrated solution and this is stopping me from doing so :-)
## Debug Info

KeePassXC - Version 2.3.1
Revision: 2fcaeea

Libraries:
- Qt 5.7.1
- libgcrypt 1.7.6-beta

Operating system: Debian GNU/Linux 9 (stretch)
CPU architecture: x86_64
Kernel: linux 4.9.0-6-amd64

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by varjolintu** [comment]
See this https://github.com/keepassxreboot/keepassxc/pull/1769. When it's merged I will do any necessary changes to the browser integration side.

**Comment by Thulium-Drake** [comment]
Thanks for the prompt reply! That does indeed seem to accomodate this usecase quite well!

**Comment by droidmonkey** [comment]
Duplicate of #398

**Comment by Thulium-Drake** [comment]
Hi Guys,

Thanks for integrating this feature! From what I can see in 2.3.4 this works like a charm!

**Comment by twwd** [comment]
How does it work?

**Comment by droidmonkey** [comment]
This is an issue, not a code contribution.

**Comment by twwd** [comment]
I know that this is just an issue but @Thulium-Drake wrote:
> Thanks for integrating this feature! From what I can see in 2.3.4 this works like a charm!
The method described in the linked PR #1769 doesn't work (the PR is closed anyways) and I couldn't find any information in the changelog of version 2.3.4. So I want to know how it works for @Thulium-Drake.

**Comment by Thulium-Drake** [comment]
@twwd 

I have something like this:
```
https://login.example.com|https://login.otherexample.net 
```

Set as the URL for an entry and the browser plugin picks up on it.

**Comment by brainplot** [comment]
> ```
> https://login.example.com|https://login.otherexample.net 
> ```

@Thulium-Drake Is that really it's supposed to work or are you basically injecting regex syntax?

**Comment by Thulium-Drake** [comment]
This is how I'm using it at the moment, but I'm not sure what it will do underwater :-)

**Comment by AlexanderAmelkin** [comment]
> I have something like this:
> `https://login.example.com|https://login.otherexample.net`
> Set as the URL for an entry and the browser plugin picks up on it.

This definitely does NOT work for me with KeepassXC 2.5.1 and KeepassXC-Browser 1.5.3.
The extension just can't find the record at all.

**Comment by varjolintu** [comment]
@AlexanderAmelkin That worked becase of an earlier bug. Anyone, do *not* use it.

**Comment by YogSottot** [comment]
> This definitely does NOT work for me with KeepassXC 2.5.1
@AlexanderAmelkin You should use this  
https://github.com/keepassxreboot/keepassxc/pull/3558

**Comment by AlexanderAmelkin** [comment]
@YogSottot, thank you so much! It doesn't fully work for me as expected (described there), but it solves the problem.

**Comment by fourstepper** [comment]
Is there a way to use regex with the URLs?

**Comment by varjolintu** [comment]
@fourstepper At this point, no.

**Comment by fourstepper** [comment]
thanks for the swift reply - that's not a big deal

**Comment by Jorricks** [comment]
> @twwd
> 
> I have something like this:
> 
> ```
> https://login.example.com|https://login.otherexample.net 
> ```
> 
> Set as the URL for an entry and the browser plugin picks up on it.

Marked is as a 👎 as that was not the recommended method. Can you maybe mention that on your post as well :)? (Then I'll thumb up again)

**Comment by JohnLGalt** [comment]
You want a comment from **_over 2 years ago_** to be edited *now*, after the feature has been properly implemented into KPXC?

**Comment by Jorricks** [comment]
Alright alright. Maybe that is expecting a bit to much 😅 it's just that I was trying that method and couldn't get it to work. Guess I should have scrolled down.
