### ISSUE TITLE
Keep temporary copy of previous password

### ISSUE THREAD

**Issue by PyBonnetainNesterenko** [keepassxreboot/keepassxc#1823]
## Expected Behavior

When changing password in KeepassXC, a copy of the previous password should be kept to allow management of password change failures on target system.

## Current Behavior

Classical password change process : connect to target with current password, request password change, copy/paste current password, generate new password with KeepassXC, copy/paste new password, confirm.

If, for any reason (bug, stupid password composition rules on target, pebkac, anything) the change procedure fails, KeepassXC will have stored the newly generated password, but the target will need the previous one. The user could be locked out of his account.

## Possible Solution
Some kind of 'backup' group that will hold previous passwords for a short time (till closing KeepassXC ? with a user-configurable delay ?).
Avoid keeping old passwords for too long (especially user-chosen ones) is a must.

**Comment by TheZ3ro** [comment]
Every entry in the database already have the history of all changes made to it. Check out the History tab when editing an entry.
