### ISSUE TITLE
Feature request - Port to iOS

### ISSUE THREAD

**Issue by dmgm** [keepassxreboot/keepassxc#1824]
I love that keepassxc is cross platform, I use it on all my computers. I just wish I could take it with me and use it on my iphone. Any plan to port it?

**Comment by weslly** [comment]
There are no plans to make mobile versions, but you can open your database file on iOS using [MiniKeePass](https://itunes.apple.com/app/id451661808) or [KeePass Touch](https://itunes.apple.com/us/app/keepass-touch/id966759076?mt=8).

**Comment by TCB13** [comment]
@dmgm you also have [Strongbox ](https://strongboxsafe.com) for iOS.
