### ISSUE TITLE
Auto-Type add support for {T-CONV:/Text/Type/} and {T-REPLACE-RX:/.../.../} syntax

### ISSUE THREAD

**Issue by webwake** [keepassxreboot/keepassxc#1825]
Add support for {T-CONV:/Text/Type/} syntax for encoding pieces in URLs and other contexts.

This is to mimic the KeePass 2 specification (https://keepass.info/help/base/placeholders.html)

This is useful if you need to encode a user name, password or other field in a URL http://example.com/login?username={T-CONV:/{USERNAME}/Uri/}&password={T-CONV:/{PASSWORD}/Uri/}

**Comment by webwake** [comment]
I added more detail to the description, but ultimately i am looking to mimic KeePass 2 behavior in terms of that placeholder command

**Comment by ArgusMagnus** [comment]
I tried to use `{T-Conv:/{USERNAME}/Base64/}` with the latest snapshot build (2022-01-08 23:52) but it does not seem to work.

 Im trying to pass a base64-encoded value to a powershell script via the URL field:
`cmd://cmd /C "start powershell -ExecutionPolicy ByPass -File ^"{DB_DIR}\scripts\Test.ps1^" -Base64 {T-CONV:/{USERNAME}/Base64/}"`

But the script receives the literal value `{T-CONV:/{USERNAME}/Base64/}`

It would be really great if that worked to help with windows cmd/batch parameter quoting/escaping nightmare

**Comment by droidmonkey** [comment]
This feature is only available when using Auto-Type.  It is not a fill in replacement option, or reference field. For your purposes here you should just convert the username to base64 manually and store it as a advanced field (Username_Base64). Then you can reference it with {S:Username_Base64}
