### ISSUE TITLE
SSH Agent problem with .pem key, not working key

### ISSUE THREAD

**Issue by Jaxmetalmax** [keepassxreboot/keepassxc#1826]
When adding an entry with .pem key for SSH agent it loads to agent, but when trying to connect shows errors and can't connect, it's a key from AWS

## Expected Behavior
As other keys should be loaded and work well, this problem just happen with .pem keys from AWS other RSA keys generated from my PC works fine.

## Current Behavior
When loaded keys from agent can't connect, adding verbosity to ssh shows this:

debug2: key: admin (0x55c9ca413230), agent
debug2: key: /mnt/veracrypt2/mykey.pem ((nil)), explicit
debug3: send packet: type 5
debug3: receive packet: type 6
debug2: service_accept: ssh-userauth
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug3: send packet: type 50
debug3: receive packet: type 51
debug1: Authentications that can continue: publickey
debug3: start over, passed a different list publickey

both:

debug2: key: admin (0x55c9ca413230), agent
debug2: key: /mnt/veracrypt2/mykey.pem ((nil)), explicit

both are the same key, the one on /mnt is not mounted but configured on .ssh/config

When closed or locked KeePassXC and loaded the .pem key  works fine

## Steps to Reproduce (for bugs)
1.create an entry on database
2.add from attachments a .pem key
3.load keys from keepassxc on agent
4.connect to host using that key loaded from keepassxc on agent

## Debug Info
KeePassXC - Versión 2.3.1
Revisión: 2fcaeea

Librerías:
- Qt 5.10.1
- libgcrypt 1.8.2

Sistema operativo: Manjaro Linux
Arquitectura de CPU: x86_64
Núcleo: linux 4.14.31-1-MANJARO

Extensiones habilitadas:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by hifi** [comment]
If you have an explicit key configured for ssh it will not try to use a key from the agent at all regardless if it can load the key from disk or not. It may work if you have configured a public key only so that it picks the right private key from the running agent but I have not tested this.

This is unlikely a bug in KeePassXC.

**Comment by Jaxmetalmax** [comment]
![captura de pantalla de 2018-04-09 11-09-31](https://user-images.githubusercontent.com/1606476/38511927-f49b7408-3be6-11e8-9fc3-98ad94e42819.png)

I already removed from config, and can see the key loaded on agent from KeePassXC and whent trying to connect doesn't connect 

debug2: key: admin (0x55bcc6cdd050), agent
.
.
.
Received disconnect from x.x.x.x port 22:2: Too many authentication failures for admin from x.x.x.x port 60428 ssh2
Disconnected from x.x.x.x port 22

but when I close Keepassxc and the agent unloads the keys, and then I load the key by hand then it works fine, so it's not a problem from agent, or server.

**Comment by hifi** [comment]
How many keys you have loaded in the agent with KeePassXC on? If it's sending the server more keys than authentications are allowed it might not ever offer the real key but all other keys first.

**Comment by Jaxmetalmax** [comment]
I have 7 keys loaded in agent, and YES that was the problem, I removed one entry, saved and reloaded, and let me connect. Thanks! I had to increase max auth tries on server even is not a good practice, I couldn't find a way to specify one key from agent, with IdentitiesOnly config I need to have the keyfile on my computer, and that's what I was trying to avoid.

**Comment by hifi** [comment]
Glad that helped.

Could you try to have only the public key as your `IdentityFile`? That way you can load all keys to the agent and it would offer only the listed one I think. This avoids having private keys on your disk. I have not tested so if it works please report back.

**Comment by Jaxmetalmax** [comment]
Yep, that did the trick, I just leaved the public key and added as IdentityFile on config, thanks!

**Comment by kdex** [comment]
@hifi Interesting. That works, though I can't find any documentation on setting `IdentityFile` to a public key. Is this behavior actually intended? What does it do exactly?
