### ISSUE TITLE
[Feature Request] Search Password Entries by Title on Startup

### ISSUE THREAD

**Issue by FrankieBetanco** [keepassxreboot/keepassxc#1827]
## Expected Behavior

After startup and login to a database, it would be nice to automatically enter the search bar when you start typing, rather than having to manually click the search bar. 
## Current Behavior

Currently, on Macintosh, upon selecting a database, entering one's password, and opening the database, in order to search through database entries by title, you must manually click the search bar in order to search through the database. 

## Context

Having to manually click the search bar generally slows me down, as a I use a number of command line applications, and not having to switch from a keyboard to mouse and back would make the application faster and easier to use.

## Debug Info

KeePassXC - 2.2.4
Revision: 4723f66

Libraries:
- Qt 5.9.1
- libgcrypt 1.8.1

Operating system: macOS High Sierra (10.13)
CPU architecture: x86_64
Kernel: darwin 17.4.0

Enabled extensions:
- KeePassHTTP
- Auto-Type
- YubiKey

**Comment by TheZ3ro** [comment]
Please update to the last version of KeePassXC, this feature is already implemented
