### ISSUE TITLE
KeepassXC: Cannot save file! (Cannot save the native messaging script file)

### ISSUE THREAD

**Issue by RaSpirit** [keepassxreboot/keepassxc#1828]
When I try to save settings I always get the error `Cannot save the native messaging script file`. 

I've tried to remove `~/.config/keepassxc/keepassxc.ini` to reset settings, but it did not help.

## Expected Behavior
Settings are being saved without errors.

## Current Behavior
Clicking apply in settings window causes the error to happen

## Possible Solution
Don't know

## Steps to Reproduce (for bugs)
1. Run the app as a usual user (non-root)
2. Go to `Tools`->`Settings`
3. Click `Apply`
4. Error alert appears 5 times (when `OK` is clicked, it appears again 4 times)

## Context
I'm unable to configure KeepassXC for my needs. It still works fine when is running as root. Tried AppImage and PPA installed versions.

## Debug Info
KeePassXC - Version 2.3.1
Revision: 2fcaeea
Distribution: AppImage

Libraries:
- Qt 5.9.4
- libgcrypt 1.8.1

Operating system: Linux Mint 18.3
CPU architecture: x86_64
Kernel: linux 4.13.0-38-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by varjolintu** [comment]
Please check the permissions of the configuration folders. Maybe you have sudoed them back to root?

Locations to check are:
```
    Chrome: ~/.config/google-chrome/NativeMessagingHosts
    Chromium ~/.config/chromium/NativeMessagingHosts
    Firefox: ~/.mozilla/native-messaging-hosts
    Vivaldi: ~/.config/vivaldi/NativeMessagingHosts
```

**Comment by RaSpirit** [comment]
@varjolintu Thanks for quick response. Actually, yes it happened to FF and Chromium locations. I've fixed owner and group for the files and it works fine now.

Maybe it makes sense to put a note in some documentation section related to native messaging usage for troubleshooting this issue.

Thanks for the great work.

**Comment by varjolintu** [comment]
Glad you got it fixed.

There are some documentation but it needs an update. A [troubleshooting guide](https://github.com/keepassxreboot/keepassxc-browser/wiki/Troubleshooting-guide) already exists though.

**Comment by RaSpirit** [comment]
@varjolintu sorry did not find it

**Comment by varjolintu** [comment]
I'll add the link to the official migration guide.

**Comment by Blinkenn** [comment]
installed this from LMDE Software Manager and it wouldn't save a file anywhere.

**Comment by droidmonkey** [comment]
@Blinkenn are you referring to a kdbx database file or the native messaging hosts file?

**Comment by Blinkenn** [comment]
kdbx file, oops.

**Comment by droidmonkey** [comment]
Please open a new issue with as much information as possible. Be very specific about where you are trying to save the file and what steps you have taken.
