### ISSUE TITLE
OS X El Capitan support?

### ISSUE THREAD

**Issue by epeli** [keepassxreboot/keepassxc#183]
Hi, I'm stuck on OS X El Capitan on my work machine for now. Is possible add support for it or does KeePassXC have some hard dependency on Sierra?

**Comment by metachris** [comment]
Same here! The download page says "OS X >= 10.7", but the app itself wants at least OS X 10.12.

**Comment by TheZ3ro** [comment]
Please don't open duplicate Issue #181 and don't delete the intended Issue template

**Comment by sjoerger** [comment]
I'm still having this issue with 2.1.1 using the "Binary package (without KeePassHTTP)" download link.

**Comment by phoerious** [comment]
I've had people running it on < 10.12. I have no idea why it's not working for you.

**Comment by sjoerger** [comment]
Apologies I should have provided more detail in my original comment.

I have 2.1.1 running on 10.11.6 but not from /Applications unless I use the previously mentioned terminal workaround. Launching the app from ~/Applications I can skip the workaround.

**Comment by phoerious** [comment]
I hate this operating system.

**Comment by sjoerger** [comment]
Let me know if I can provide any sort of debug output and what you need.

**Comment by phoerious** [comment]
Alright, could you try this build? https://drive.google.com/open?id=0B87E3fJWeu3vZVhWMGs0cjZVaFE
Signature: https://drive.google.com/open?id=0B87E3fJWeu3vRnd1LU12a0ZjRms

**Comment by sjoerger** [comment]
Still fails to open from /Applications. And this build also fails with the libmicrohttpd issue.

<img width="775" alt="keepassxc-test-screenshot" src="https://cloud.githubusercontent.com/assets/1896155/22905079/ebec3d44-f20c-11e6-8e00-dd25a3f0c2e8.png">

**Comment by phoerious** [comment]
Okay, give me time to redownload Xcode. I guess I have to download the 10.7 SDK or something.
If in the meantime you know any other bad OS X jokes, keep 'em coming. M(

**Comment by phoerious** [comment]
@sjoerger I updated the links above. Can you please try again?

**Comment by sjoerger** [comment]
I'm beginning to suspect an issue with this particular Mac but I have no idea what it would be. I have two Mac's running 10.11.6; one is able to launch the app with no compatibility error and another is not. Of course it crashes on both due to the library issue.

**Comment by phoerious** [comment]
Does the other Mac also run the official release from our website without complaining about compatibility?

**Comment by sjoerger** [comment]
I will have to double check when I get home from work.

**Comment by sjoerger** [comment]
Apologies for the delay. On my 2nd Mac running 10.11.6 I am able to launch version 2.1.1 from /Applications without issue. This is the version signed on Sat Feb 11 14:28:19 2017 EST.

**Comment by phoerious** [comment]
I also had someone else test it on an old Mac. Seems like this is a problem with your specific machine.

**Comment by tilllt** [comment]
I couldn't get the binary version to run, as well on osx el capitan. After I compiled my own (with the help of the people here) it works fine though.

**Comment by sjoerger** [comment]
Sadly I found that simply rebooting the Mac that wouldn't launch the app from /Applications solved my problem. Clearly something was stuck somewhere. The newly released 2.1.2 version works fine as well.
