### ISSUE TITLE
Allow importing CSV files into currently open database

### ISSUE THREAD

**Issue by jeroenev** [keepassxreboot/keepassxc#1832]
I have a  CSV file from bitwarden which i would like to import into my current keepassxc vault

## Expected Behavior
it imports the entries from the CSV into my current vault

## Current Behavior
it asks me to create a new db with password/keyfile

## Possible Solution
change it so it imports my data into my currently opened vault

## Steps to Reproduce (for bugs)
1. click import csv in the menu
2. it asks to make a new vault, put in credentials
3. you map the fields from the csv to keepass
4. have new (unsaved) vault with the imported entries

## Debug Info
KeePassXC - 2.3.1

Operating system: Ubuntu Gnome 16.01
CPU architecture: x64
Kernel: 4.13.0-38-generic

**Comment by seatedscribe** [comment]
Currently KXC supports merge (Database->Merge from KeePassXC database). So you can import to a new database, save it after acknowledging its contents, and then merging with your vault.

Having a separate step for CSV import instead of an import&merge aims towards a clear understanding of what actually is acquired. Yes, the burden is on the user, who has to verify and choose in case of same entries with different values before merging, but otherwise there is the possibility of overwriting what should remain the same.

**Comment by droidmonkey** [comment]
We might want to add a drop-down selection to enable direct import to an open database. Default would be to create a new database.

**Comment by theerror** [comment]
Well, the best way would be ask user, where (the group) he want's import. If he select root - then there will be overwrite as he having some reason why he act like that. If want merge and check, lets make possible to select folder (or create new one) where all passwords will be imported. 

Making merging, without possibility to control, where new data will be merged it's not good anyway.

**Comment by MountainX** [comment]
> new DB during importing is unexpected behaviour

I agree with that, although I have gotten used to it now. 

A drop-down selection to enable direct import to an open database would be useful for me too.

**Comment by jzacsh** [comment]
Just to clarify: the _current_ merge behavior is that one _cannot_ force all imported data to go into a new subgroup right? (that's the potential conflict mentioned by theerror in their comment above?). If so - _eek_ - is there a way to merge while keeping the new incoming data separate (eg: in a subgroup called `importFooBar`?) or we're waiting for this bug as a proper "import _into_ open db" to solve that?

**Comment by droidmonkey** [comment]
You can import csv to kdbx then drag and drop the root group to the other database.

**Comment by madprogramer** [comment]
(bump)

**Comment by OUSS0012** [comment]
I can't import csv file to keepassRC, i can import it but i think the file is not compatible

**Comment by toraritte** [comment]
This and https://github.com/keepassxreboot/keepassxc/issues/2032 would be very helpful. Just imported all my passwords from chrome, merged the resulting new database with my master database - and now there are 272 new groups in the root. Tried to fix this by (1) selecting "All Entries" under "Searches and Tags" sub-window, (2) manually selecting the newly imported credentials, and (3) dragged all of them to a new group. Now I have 272 new groups in root that are empty:)

This is inconvenient, but I wouldn't switch from keepassxc for all the money in the world. Thank you for all your hard work!

**Comment by droidmonkey** [comment]
If you don't want the groups just deselect that column in the import dialog

**Comment by toraritte** [comment]
Yeah, that's my fault too, I was to hasty, but thanks for the tip! Anyway, fixed my mess by importing the database into Keepass2Android, selected the unneeded groups, and deleted them.
