### ISSUE TITLE
Sudden change in displayed date formats.

### ISSUE THREAD

**Issue by belisama** [keepassxreboot/keepassxc#1835]
For the month I've been using KeepassXC (since 2.3.1 was released), dates were displayed as %m %d %y %H:%M (ie, 04/11/18 11:09). That's how it was when I launched it this morning. Mid-morning, I went to use it and the dates had changed to %e %b %Y %H:%M:%S (ie, 4 Apr 2018 11:09:00). There doesn't appear to be a preference for setting date format, so I have no idea why it suddenly changed.

## Expected Behavior
The date format should stay constant unless the user actively changes a setting or config file or something.

## Current Behavior
The date changed suddenly, randomly, and without any user input.

## Possible Solution
Without knowing the cause, I'm hard pressed to offer a solution.

## Steps to Reproduce (for bugs)
I can't get the date format back to where it was, so I've no way to reproduce the bug.

## Context
1. I just don't like the current date format. The original way looked better and was easier to work with.
2. A password vault has an extremely high bar for data integrity. Having things change without warning or explanation doesn't give the users reassurance that said bar is being met.

## Debug Info
KeePassXC - Version 2.3.1
Revision: 2fcaeea
Distribution: Snap

Libraries:
- Qt 5.7.1
- libgcrypt 1.7.6-beta

Operating system: Ubuntu Core 16
CPU architecture: x86_64
Kernel: linux 4.13.0-36-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by droidmonkey** [comment]
This very likely has nothing to do with us. You probably either had a system update or otherwise that changed the way dates are displayed on your system. Does your clock also show time/dates this way? We obviously didn't change anything.

**Comment by belisama** [comment]
Problem found and fixed. It was a system change made *yesterday* that KeepassXC just didn't react to until today (???).
