### ISSUE TITLE
Feature request: Search hotkey

### ISSUE THREAD

**Issue by mkeedlinger** [keepassxreboot/keepassxc#1837]
Add an option to have a hotkey bring your focus to the search bar.

Simple addition, but really helpful because I use a hotkey to switch to the KeepassXC window, and then I would like to just press another hotkey, search for what I need and get back to whatever I'm doing.

Thanks for considering!

And thanks for the hard work, KeepassXC is great!

**Comment by droidmonkey** [comment]
Already exists,  CTRL+F

**Comment by mkeedlinger** [comment]
Probably should have searched harder 🤷‍♂️

Thanks!
