### ISSUE TITLE
Unnecessary https:// was added on the URL field

### ISSUE THREAD

**Issue by yanderemoe** [keepassxreboot/keepassxc#1838]
## Expected Behavior
When there is no schema added in the URL field, (eg. 123.117.0.1:22), there shouldn't be a https:// when displaying it.

## Current Behavior
It displays an extra https:// in front of the URL.
![field_editing](https://user-images.githubusercontent.com/25140626/38652724-39990878-3dd5-11e8-886c-daa60e8a1b7a.png)

![displaying](https://user-images.githubusercontent.com/25140626/38652732-3e7bdf46-3dd5-11e8-8f68-8d31b9a2a3de.png)

## Possible Solution
Don't add https:// or http:// in the front of the URL.

## Steps to Reproduce (for bugs)
1. Add an entry with "123.117.0.1:22" typed into the URL field
2. View the entry in the list

## Context
Just looks annoying and always wrongfully click into that and opens webpage.

## Debug Info
KeePassXC - Version 2.3.1
Revision: 2fcaeea

Libraries:
- Qt 5.10.1
- libgcrypt 1.8.2

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 4.15.15-1-ARCH

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by droidmonkey** [comment]
This will be fixed by #1768
