### ISSUE TITLE
Group names should not take presedence over titles when searching

### ISSUE THREAD

**Issue by gustavnikolaj** [keepassxreboot/keepassxc#184]
## Expected Behavior

Given a database with the following groups:

```
 . Root
 |-- AWS
 `-- Mail Accounts
```

And the following password entries:

```
Title: MyCompany Server 1
Group: Root > AWS
```

```
Title: MyCompany CRM
Group: Root
```

```
Title: MyCompany Mail
Group: Root > Mail Accounts
```

When searching for `mycompany` in the search field in the application I would expect the following result order:

Group | Title |
--- | ---
Root | MyCompany CRM
Mail Accounts | MyCompany Mail
AWS | MyCompany Server 1

## Current Behavior

The actual sort order is:

Group | Title |
--- | ---
AWS | MyCompany Server 1
Mail Accounts | MyCompany Mail
Root | MyCompany CRM

## Possible Solution

Searching seems to only search in the titles of entries, and then sort by Groups.

Searching for `mycompany` matches all three results where as neither `root mycompany` nor `mycompany root` yields any results.

I have a few wishes to changes in the search UX:

1. Results from the Root group should take presedence over any other results.
2. Searches should not be done exclusively in the titles, but also on the group names. It seems that the current search is a fuzzy match on the title - my ideal would be to have it fuzzy on the title and the group name.

Given my example entries described above I want the following cases to match the following results:

Search query | result (or first result if multiple results | Works as expected
--- | --- | ---
my crm | MyCompany CRM | yes
aws my | MyCompany Server 1 | no (no results)
my | MyCompany CRM | no (wrong sort order)

## Steps to Reproduce (for bugs)
The expected scenario outline above describes how to reproduce this in detail. I attached a demo database ([example.kdbx.zip](https://github.com/keepassxreboot/keepassxc/files/726075/example.kdbx.zip)) with the example entries and groups already created. The password is `123456` and there is no key file. I had to make a zip file as GitHub would let me upload a `kdbx` file.

1. Open `example.kdbx`
2. Log in with password `123456`
3. Press CTRL+F (or CMD+F on macOS)
4. enter `mycompany`

## Context

I use groups to structure my password entries so that related entries are combined. The top level is used for the most commonly used ones that do not fit into one of the categories.

Searching is how I primarily interact with passwords in my daily use of the password manager.

The passwords stored in the Root group is what I'm trying to find 99% of the time. 

## Your Environment

* KeePassXC version/commit used: Revision: b6f754c29a7cf3a2365fea4487395a9f9741055c
* Qt version: 5.6.1
* Compiler (e.g. Clang++3.6.0): Installed through snap on Ubuntu
* Operating System and version: Ubuntu 16.04.1 LTS

**Comment by phoerious** [comment]
Searches are scoped to your currently selected group as of #118. So when you select a subgroup, you won't find entries outside of it. Searching for group names is implemented in #168 and will be in 2.2.0. Searching for group name and entry name at the same time is not possible at the moment.

**Comment by gustavnikolaj** [comment]
> Searches are scoped to your currently selected group as of #118. So when you select a subgroup, you won't find entries outside of it. 

The problem is that when searching from the Root group (which is most of the time for me) I get the automatic sorting based on group which is very unlikely to actually give me the most interesting result.

I would really like to use keepassxc instead of Keepass2 running in wine on my linux setup, but this behavior is a show stopper for me. My normal workflow is:

1. bring up keepass with a global shortcut
2. ctrl+f to focus search
3. type into the search field until my desired result is at the top
4. copy
5. alt-tab back

> Searching for group name and entry name at the same time is not possible at the moment. 

This is a large usability problem in my opinion. I have things in my password database that I wouldn't be able to get to with searching. If you have two similarly named entries in different groups, you will only be able to find one of them.

Entry Title | Entry Group
--- | ---
foo | Root
foo | Root/A-Group
foo | Root/B-Group

I wrote a dmenu-based read-only frontend for keepass ([keepass-dmenu](https://github.com/gustavnikolaj/keepass-dmenu)) based on node.js. My solution was to concatenate the groupname to the title, and do a search on top of that. Given the examples in the table above it would leave me with the following entries to search through in dmenu:

- foo (Root)
- foo (A-Group)
- foo (B-Group)

**Comment by phoerious** [comment]
Your use case is about the same as mine (but I also heavily use autotype). I never had issue with the order in which results are presented. But maybe I just don't have enough entries with the same name. I agree that results should be sorted properly by name. I'll have a look into it.

**Comment by gustavnikolaj** [comment]
The most important thing to me is the group sort order. Given the following group hierachy:

```
 . Root
 |-- AWS
 `-- Mail Accounts
```

Sorting should be done on the fully qualified name and not just the base name. Currently it seems that the sort order of the groups are just alphabetically, yielding:

- AWS
- Mail Accounts
- Root

... for the above examples. A sort order based on the full name would be much more appropriate:

- Root
- Root.AWS
- Root.Mail Accounts

Is that possible?

**Comment by gustavnikolaj** [comment]
The use case for searching on both title and group name is probably more of an edge case, I'll give you that. But after using it just for a few hours I've already hit it a few times :-)

**Comment by TheZ3ro** [comment]
I'm testing this on latest develop version and this seems strange.
Obviously I think the expected behavior when searching in Root is show Root's items first. You can search in specific group by selecting the group so doesn't make sense to show them first.

When testing this I've seen the following behavior:
- Enter the first letter (for example "M" for "MyCompany" in @gustavnikolaj example)
- Root group is first then groups are alphabetically sorted
- Enter the second letter (e.g "y")
- Root group will be alphabetically ordered and isn't first anymore.

I think it's a bug. I will look more into the code

**Comment by TheZ3ro** [comment]
Postponing for next release

**Comment by droidmonkey** [comment]
Closing in favor of #808
