### ISSUE TITLE
KeepassXC uses the application icon for the tray with Numix icon theme

### ISSUE THREAD

**Issue by sojusnik** [keepassxreboot/keepassxc#1840]
## Expected Behavior
Even if the [Numix icon theme](https://github.com/numixproject/numix-icon-theme) is installed, the tray icon should use the specific icons, not the application one, as described [here](https://github.com/numixproject/numix-icon-theme/issues/1289).

## Current Behavior
If the [Numix icon theme](https://github.com/numixproject/numix-icon-theme) is used under Ubuntu 17.10, then the Keepassxc tray icon always looks like the app icon, as described [here](https://github.com/numixproject/numix-icon-theme/issues/1289).

## Debug Info
KeePassXC - Version 2.3.1
Revision: 2fcaeea

Bibliotheken:
- Qt 5.9.1
- libgcrypt 1.7.8

Betriebssystem: Ubuntu 17.10
CPU-Architektur: x86_64
Kernel: linux 4.13.0-38-generic

Aktivierte Erweiterungen:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by droidmonkey** [comment]
What is meant by specific icons?

**Comment by sojusnik** [comment]
By "specific icons" I mean those icons that are specifically designed for the system tray, as shown [here](https://i.imgur.com/YpIrf6Z.png).

**Comment by sojusnik** [comment]
@TheZ3ro You seem to be right.

**Comment by Veazer** [comment]
@TheZ3ro  I've done some icon creation and I would be willing to create them. Unfortunately I have zero experience with git, but I can hand them off to someone else or whatever you suggest.

**Comment by Stunkymonkey** [comment]
since it got removed from last release: are there any plans to fix this?

**Comment by droidmonkey** [comment]
We are no longer allowing themes to change our icons, so yes the next release standardizes behavior across all platforms.

**Comment by Stunkymonkey** [comment]
so this means icon-themes (e.g. numix) will not be able to change the icon right?

**Comment by droidmonkey** [comment]
That is correct.

**Comment by mrmeszaros** [comment]
@droidmonkey could You please give a reasoning why icon theming will be dropped?
Just to clarify for me and those to come in the future.

**Comment by droidmonkey** [comment]
Standardizes the look and feel of our application across platforms.
