### ISSUE TITLE
Show countdown for clipboard clearing

### ISSUE THREAD

**Issue by rodmur** [keepassxreboot/keepassxc#1843]
This would be an enhancement request. A feature the old Keepass application had that I like was a little timer or countdown clock indicator that showed you how much time before the copy buffer was going to be cleared. It would be nice if Keepassxc had something like that.

## Expected Behavior

This change/improvement, it's fairly well described above. Just some small indication how much time is left for the copy buffer is cleared. I think this would be useful, especially for new users. 

## Current Behavior

There is no countdown clock feature, that I know of.

## Possible Solution

Provide an option to turn on a countdown clock. I imagine some people may find it annoying. 

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

Some people can be confused when they can't copy and paste their password anymore. They might forget there is a time in which the copy buffer will be cleared.

## Debug Info

KeePassXC - ALL
Revision: ANY

**Comment by tromlet** [comment]
I also greatly miss this feature of original KeePass.

**Comment by akontsevich** [comment]
Propose to change the title **"Show countdown progress bar for clipboard clearing"**.

**Comment by droidmonkey** [comment]
That is how it will be implemented, perhaps with a timer as well

**Comment by DaniW42** [comment]
I just moved from KeePass to KeePassXC and was missing "something". How is this even possible to not have this feature?

**Comment by tromlet** [comment]
> I just moved from KeePass to KeePassXC and was missing "something". How is this even possible to not have this feature?

...they haven't coded it in yet?

**Comment by DaniW42** [comment]
Well, I can not see any option to activate/display it...
