### ISSUE TITLE
Missing SSH Entry

### ISSUE THREAD

**Issue by TheFinestSurgeon** [keepassxreboot/keepassxc#1844]
## Expected Behavior
In settings their should be 5 options

- General
- Security
- Browser Integration
- Legacy Browser Integration
- SSH Agent

## Current Behavior

- General
- Security
- Browser Integration

## Steps to Reproduce (for bugs)
All Steps Reproduced in A VM

1. Install Solus Bungie
2. Apply all Updates
3. Download KeepassXC from software center
4. Go To Options

## Context
I Would love to use the SSH Agent feature

## Debug Info

doctor@doctor ~ $ ssh-agent
SSH_AUTH_SOCK=/tmp/ssh-k45BTSnX6aZ5/agent.2233; export SSH_AUTH_SOCK;
SSH_AGENT_PID=2237; export SSH_AGENT_PID;
echo Agent pid 2237;
doctor@doctor ~ $ echo $SSH_AUTH_SOCK
/home/doctor/.cache/keyring-5NXFHZ/ssh

--------------

KeePassXC - VERSION
Revision: REVISION

Libraries:
- LIBS

Operating system: OS
CPU architecture: ARCH
Kernel: KERNEL

Enabled extensions:
KeePassXC - Version 2.3.1
Revision: 2fcaeea

Libraries:
- Qt 5.10.0
- libgcrypt 1.8.2

Operating system: Solus 3.999
CPU architecture: x86_64
Kernel: linux 4.15.17-64.current

Enabled extensions:
- Auto-Type
- Browser Integration
- YubiKey

**Comment by TheZ3ro** [comment]
> Enabled extensions:
>
>    Auto-Type
>    Browser Integration
>    YubiKey

It seems that the SSH extension is not enabled at compile time, this issue is downstream in Solus package distribution.
