### ISSUE TITLE
Firefox Plugin does not seem to work

### ISSUE THREAD

**Issue by horror-vacui** [keepassxreboot/keepassxc#1845]
## Expected Behavior
username/password fill-in after clicking in the fields.

## Current Behavior
I find no ways for filling the username/password in Firefox. No key or lock icon in the username/password fields, nothing in the drop down list for right mouse click, what I have seen before. The Browser senses that there is an open KeePass database, but I can not use it. 

I have not used KeePass on this system before, so I am not sure migration is the good word, but I followed https://keepassxc.org/docs/keepassxc-browser-migration/. I got there from the FAQ. I got no error message. What is strange for me is that there was no confirmation window, like it was for the non cross-platform KeePass to copy a displayed string to another window.

## Steps to Reproduce (for bugs)
I can not not to reproduce. It was the first install on my machine.

## Debug Info
KeePassXC - Version 2.3.1
Revision: 2fcaeea

Libraries:
- Qt 5.5.1
- libgcrypt 1.8.1

Operating system: Ubuntu 16.04.4 LTS
CPU architecture: x86_64
Kernel: linux 4.13.0-38-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

Firefox 59.0.2 (64-bit)
Plugin: KeePassXC-Browser 1.0.1

## Troubleshooting:
The "org.keepassxc.keepassxc_browser.json" file is in its place. 
```
    {
        "allowed_extensions": [
            "keepassxc-browser@keepassxc.org"
        ],
        "description": "KeePassXC integration with native messaging support",
        "name": "org.keepassxc.keepassxc_browser",
        "path": "/usr/bin/keepassxc-proxy",
        "type": "stdio"
    }
```
The keepassxc-proxy is running according to ps: 
```/usr/bin/keepassxc-proxy /home/zoltan/.mozilla/native-messaging-hosts/org.keepassxc.keepassxc_browser.json keepassxc-browser@keepassxc.org``` 

Add-on debugging said: ```Error 7: Cannot encrypt message or public key not found. Is native messaging or support for your browser enabled in KeePassXC?```
In KeePassXC the "Enable KeePassXC browser integration" is checked in the Application Setting/Browser Integration.

I do not know how to proceed.

**Comment by horror-vacui** [comment]
After going away and making some dinner it works now. Without restarting or any other act. It seems very strange, but KeePass Integration seems to work now.

On the other hand the plugin error is still there `Error 7: Cannot encrypt message or public key not found. Is native messaging or support for your browser enabled in KeePassXC? keepass.js:954:5`.

**Comment by varjolintu** [comment]
Could you debug the extension and see if there's any messages? See [step 4](https://github.com/keepassxreboot/keepassxc-browser/wiki/Troubleshooting-guide).

**Comment by MisterY** [comment]
The only similar thing I notice is after locking the computer (and database), the plugin does not detect the unlock. Clicking the blue button (re-connect and re-detect the fields) usually fixes it. You can also try that and see if anything changes.

**Comment by horror-vacui** [comment]
@varjolintu  The error text what I included in the end is from step 4. I am not a web-developer, but the rest seemed OK to me.

**Comment by varjolintu** [comment]
@horror-vacui There must be still something missing. That error is not seen without a reason.

**Comment by horror-vacui** [comment]
I have looked again into the extension debugging. The following line was seen below the plugin name:
`Reading manifest: Error processing version_name: An unexpected property was found in the WebExtension manifest.`

I never used javascript, and I write code very rarely and my codes are usually much simpler. It does not worth for me to understand the code modify and test it. All I can help to make this software better is to report the errors and request features I think would be useful. Below is my console output. Although I selected only KeePass for debug, there are lines, what I feel does not belong to it. 

```
Connecting to native messaging host org.keepassxc.keepassxc_browser  keepass.js:870:5
Error 7: Cannot encrypt message or public key not found. Is native messaging or support for your browser enabled in KeePassXC?  keepass.js:954:5
Connecting to native messaging host org.keepassxc.keepassxc_browser  keepass.js:870:5
Server public key: WfjBgCEPYl9mQrRZSZl6oRfLXYY5JML82wfYuv1At1w=  keepass.js:620:17
Error 15: No logins found keepass.js:954:5
Error: Nonce compare failed keepass.js:938:9
Error 1: Database not opened keepass.js:954:5
https://mail.google.com/mail/u/0/#inbox/**************** : Unable to run script because scripts are blocked internally.  (unknown)
Error: Promised response from onMessage listener at @moz-extension://cdff3886-d249-4911-a54e-fc116a4a211f/background/init.js:77:1 went out of scope  undefined
Error: badger.getFrameData(...) is null  undefined
Content Security Policy: Ignoring ‘x-frame-options’ because of ‘frame-ancestors’ directive. (unknown)
Content Security Policy: Directive ‘child-src’ has been deprecated. Please use directive ‘worker-src’ to control workers, or directive ‘frame-src’ to control frames respectively. (unknown)
Content Security Policy: The page’s settings blocked the loading of a resource at self (“script-src”). Source: (function (NAVIGATOR, OBJECT) {

    OBJ....  1845:1
Content Security Policy: The page’s settings blocked the loading of a resource at self (“script-src”). Source: (function (ERROR) {

    const V8_STACK_....  1845:1
Content Security Policy: The page’s settings blocked the loading of a resource at self (“script-src”). Source: (function (NAVIGATOR, OBJECT) {

    OBJ....  Troubleshooting-guide:1
Content Security Policy: The page’s settings blocked the loading of a resource at self (“script-src”). Source: (function (ERROR) {

    const V8_STACK_....  Troubleshooting-guide:1
Attempt to set a forbidden header was denied: Connection  4205232061-lcs_client_bin.js:114:385
```

**Comment by varjolintu** [comment]
These messages mean that you have the connection to KeePassXC but your database is closed. Does this error still happen when you have your database open and it's connected?

Those other errors are because of Privacy Badger (I assume).

**Comment by horror-vacui** [comment]
Now I do not have any error or warning related to KeePass. It looks like a false alarm.

I guess previously the connection between the plugin and the database was closed, although my KeePassXC database was open. Also the key icon in my browser was green, not indicating that I have to reconnect it with the database. This also seems to be a little bug or at least some unintuitive behaviour, what tricked me.

**Comment by varjolintu** [comment]
I'll have to check the icon behaviour. There's some fixes coming already.

**Comment by droidmonkey** [comment]
Since this seems resolved and is on the plugin side for any remaining concerns I am closing this issue. If you continue to experience issues with the plugin please report over in the keepassxc-browser repo.
