### ISSUE TITLE
KeepassXC not detecting username / password for Twitch TV

### ISSUE THREAD

**Issue by jcosentino** [keepassxreboot/keepassxc#1848]
I have a password saved in KeepassXC for twitch.tv, however, the credentials are not detected and I have to manually copy and paste data from KeepassXC in order to log in.

Website in question:
https://www.twitch.tv

When you go to the website in question, click login on the top right and try the keepassxc keyboard combination Alt+Shift+U, or right click on the username box and go to KeePassXC-Browser and select Fill User + Pass. This should fill the fields. Neither option works.
I tried to customize which fields correspond with username and with password to no avail.
I also checked the URL that Keepassxc checks and it follows https://www.twitch.tv

KeePassXC - 2.3.1
Revision: 2fcaeea
KeePassXC-Browser - 1.0.1

Libraries:
- Qt 5.10.1
- libgcrypt 1.8.2

Operating system: Windows 10 16299.371
CPU architecture: x86_64

Enabled extensions:
- KeePassXC-Browser
(disabled the others)

**Comment by varjolintu** [comment]
For me the fields are automatically detected without any problems, so cannot reproduce this.

**Comment by jcosentino** [comment]
I am still experiencing this on Chrome and Firefox. I made a new profile in Firefox and could not detect Twitch. May I reopen this?

**Comment by droidmonkey** [comment]
Try using the "select credential fields" feature.

**Comment by jcosentino** [comment]
I did that and selected the username and password fields. Still not detecting anything.

**Comment by jcosentino** [comment]
I created a new Arch Linux clone and tried my database with a brand new Firefox stock setup and got Keepassxc setup. Websites work, but not Twitch. I even created a new database to get linked up with keepassxc browser and still experience the same issue.

**Comment by droidmonkey** [comment]
Recommend copy/paste the login page url from twitch into the url field of your database entry. This is likely the issue, especially if twitch does something like redirect to login.twitch.tv

**Comment by jcosentino** [comment]
That didn't work either. I'm stumped on this one 🤔

**Comment by varjolintu** [comment]
@jcosentino Could you debug the extension and see if there's any messages? You can do it from the extensions page (enable debugging) and check also the web page itself using right mouse button and select Inspect from the context menu. This should show any error messages from the content script.

**Comment by jcosentino** [comment]
Here is my log:
```
Error 15: No logins found  keepass.js:964:5
Error: Nonce compare failed keepass.js:948:9
Error 14: No URL provided  keepass.js:964:5
Error: Nonce compare failed keepass.js:948:9
Error 14: No URL provided  keepass.js:964:5      
```
I tried to detect my credentials using the keyboard shortcut, then I used the right-click context option.

**Comment by jcosentino** [comment]
I'm dropping by to let everyone know that it works for me in version 2.3.4.
