### ISSUE TITLE
Lock databases after inactivity not working

### ISSUE THREAD

**Issue by ioparaskev** [keepassxreboot/keepassxc#1849]
## Expected Behavior

`Lock databases after inactivity of` should keep working ;P
## Current Behavior

Selecting the autolock when inactive for X seconds does not seem to work anymore

## Debug Info

KeePassXC - Version 2.3.1
Revision: 2fcaeea

Libraries:
- Qt 5.9.4
- libgcrypt 1.8.2

Operating system: Fedora 27 (Workstation Edition)
CPU architecture: x86_64
Kernel: linux 4.15.15-300.fc27.x86_64

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by TheZ3ro** [comment]
We need more info, I can't reproduce this on XFCE/Ubuntu

**Comment by ioparaskev** [comment]
Nevermind I seemed to have ignored the basic rule before error reporting. The `try turning it off and on again`; in this case reinstalling.
Reinstalled and now works fine. I guess there was an issue due to my upgrade from fedora 26->27
