### ISSUE TITLE
Show/hide expired entries on auto-type

### ISSUE THREAD

**Issue by MisterY** [keepassxreboot/keepassxc#1855]
## Expected Behavior
The expired entries are not offered for selection in auto-type selector window.
I would hope for a switch in the settings that would filter-out the expired entries from the view below.

## Current Behavior
When pressing the hotkey to auto-type credentials in any application, the window with multiple options open in cases when multiple entries match the active application.
This window contains both - currently valid and expired entries.

## Possible Solution
Add a switch in the settings that guides this behaviour so that users can configure it according to their preferences.

## Steps to Reproduce (for bugs)
Open an application that requires login (i.e. browser page). Press a pre-defined keyboard shortcut to perform auto-type, making sure that there are multiple entries that match this application/page. At least one of those entries should be expired.

## Context
The expired entries are useful to have as a history or backup replacement in some cases. However, they should not appear in the auto-type window as they are not considered active any more.

## Debug Info
KeePassXC - Version 2.3.1
Revision: 2fcaeea

Libraries:
- Qt 5.10.1
- libgcrypt 1.8.2

Operating system: Windows 10 (10.0)
CPU architecture: x86_64
Kernel: winnt 10.0.14393

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by selurvedu** [comment]
I would like to see this feature implemented as well.

**Comment by zoom-into** [comment]
I have been looking for such a filter feature for a long time as well. An implementation would be much appreciated.

**Comment by MisterY** [comment]
Thank you, guys!
