### ISSUE TITLE
What is the license of this project?

### ISSUE THREAD

**Issue by konklone** [keepassxreboot/keepassxc#1857]
Can a user opt to make use of any of the licenses listed in the root of the repository, and apply it to the entire contents? Or are there guidelines somewhere associated with which licenses apply to what?

**Comment by droidmonkey** [comment]
See https://github.com/keepassxreboot/keepassxc/blob/develop/COPYING

**Comment by randomstability** [comment]
@droidmonkey - I was wondering if your team could share anything about the process/code used to produce your license attribution.  I like it and think we could use it.

**Comment by droidmonkey** [comment]
Nothing fancy, we just hand jam it in there. When a new external resource is added to the project we update the COPYING within the PR and add  the appopriate license to the root directory if not already present.

**Comment by TheZ3ro** [comment]
Yes, unfortunately it's a fully manual process
