### ISSUE TITLE
Feature Request: Forget Selected "Key File" 

### ISSUE THREAD

**Issue by jpompilio** [keepassxreboot/keepassxc#1859]
OVERVIEW:

When utilized, "Key Files" provide an additional level of security by requiring the user to select the correct file to be used in conjunction with the Master Key to gain access to the password database.

CURRENT SCENARIO:

When the program starts or a new database is selected, the previously selected "Key File" is remembered and is presented to the user.  A user only has to type the password to gain access to the password database.

RECOMMENDATION:

Do not store this information.  Require users of a "Key File" to select the appropriate file each time they require access, just as they need to type their password each time.  When utilized, remembering the "Key File" provides adversaries with a portion of the information they need in order to gain access.

**Comment by sts10** [comment]
You can have KeePassXC not remember the location of your key files. Go to Settings > General > Basic Settings > and uncheck "Remember last key files and security dongles"
