### ISSUE TITLE
Trying to build in mac (not expert)

### ISSUE THREAD

**Issue by abacao** [keepassxreboot/keepassxc#186]
Hi,

Tryed to make a build using macOS Sierra and my approach was this:

1st - https://github.com/keepassxreboot/keepassxc/wiki/Building-Environment-on-MacOS
2nd - git clone
3rd - cmake . -DWITH_TESTS=OFF -DWITH_XC_HTTP=On

Output:
CMake Error at CMakeLists.txt:163 (find_package):
  By not providing "FindQt5Core.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Qt5Core", but
  CMake did not find one.

  Could not find a package configuration file provided by "Qt5Core"
  (requested version 5.2) with any of the following names:

    Qt5CoreConfig.cmake
    qt5core-config.cmake

  Add the installation prefix of "Qt5Core" to CMAKE_PREFIX_PATH or set
  "Qt5Core_DIR" to a directory containing one of the above files.  If
  "Qt5Core" provides a separate development package or SDK, be sure it has
  been installed.

-- Configuring incomplete, errors occurred!

Can someone fix the way of building?

Thanks

**Comment by TheZ3ro** [comment]
You can find the complete guide on the wiki in page [wiki/Building-Environment-on-MacOS](https://github.com/keepassxreboot/keepassxc/wiki/Building-Environment-on-MacOS) and [wiki/Install-Instruction-from-Source](https://github.com/keepassxreboot/keepassxc/wiki/Install-Instruction-from-Source)

But I will encourage you to wait for the upcoming 2.1.1 release that will have a dmg with KeePassHTTP enabled (after it will be fixed and secured.)

**Comment by phoerious** [comment]
Can  I close this?

**Comment by abacao** [comment]
You can, TY

**Comment by Ken-B** [comment]
@abacao you need to add `-DCMAKE_PREFIX_PATH=/usr/local/Cellar/qt5/5.8.0` to the `cmake` command (or just wait for the next release ;)

**Comment by abacao** [comment]
Ty. I will try and let you know. Thanks
