### ISSUE TITLE
Feature Request:  import from Buttercup (.bcup) password format

### ISSUE THREAD

**Issue by sunjam** [keepassxreboot/keepassxc#1861]
[Buttercup](https://buttercup.pw) is a newer open source password manager, which includes[ basic kdbx import](https://github.com/buttercup/buttercup-importer).  It would be useful to support buttercup **.BCUP** format for importing back into Keepass.  [Here is a link to their API documentation.](https://github.com/buttercup/buttercup-core/blob/master/API.md)

**Comment by droidmonkey** [comment]
I dont understand the use case. If a user moves to buttercup why would they move back to keepass?

**Comment by sunjam** [comment]
This is in case they are moving from Buttercup to Keepass.

**Comment by droidmonkey** [comment]
I don't think this is ever going to be a thing. The best bet is for the buttercup user to export their data as csv and import into keepass.

**Comment by ghost** [comment]
> I don't think this is ever going to be a thing. The best bet is for the buttercup user to export their data as csv and import into keepass.

I tried to do this but the data was misformed.
