### ISSUE TITLE
Show number entries per directory in status bar

### ISSUE THREAD

**Issue by micressor** [keepassxreboot/keepassxc#1863]
## Steps to Reproduce (for bugs)
1. Click on a directory
2. At the bottom of the KeePassXC window there is no information about the number of entries in the directory.

## Debug Info
KeePassXC - 2.3.1
Revision: 2fcaeea
Kernel: linux 4.9.0-6-amd64
OS: Debian 9 (stretch)

**Comment by TheZ3ro** [comment]
I like this proposal.

**Comment by mikperk** [comment]
Will this feature ever be integrated?

**Comment by JGKle** [comment]
Also wondering if this will ever be added? Been close to 4yrs now?

**Comment by cweiske** [comment]
Isn't this the same as #3963 which was solved by #8435?

**Comment by droidmonkey** [comment]
Yes this is a duplicate
