### ISSUE TITLE
A password provided by Auto-Typing is trimmed

### ISSUE THREAD

**Issue by Rivriet** [keepassxreboot/keepassxc#1864]
It seems that the password field is fulfilled with trimmed value when I execute Auto-Typing using global auto-typing hot key. The problem exist on password fields only. However, when I'm visiting website with form which lets show unmasked password and check this option, then execute auto-typing, I see my whole valid password and I able to log in. But when I do above mentioned things without choosing the "show me a password" option, my password is trimmed (ex. I noticed that on https://mail.protonmail.com/login page the first character of it is removed). I've tested my database on KeepassXC Windows version - it works fine. Unfortunately not on the Ubuntu version. What is more interesting, I've installed KeePassX and auto-typing function works as a charm there.

## Debug Info

KeePassXC - 2.3.1
Revision: 2fcaeea
Libraries:
- Qt 5.7.1
- libgcrypt 1.7.6-beta

Operating system: Ubuntu Core 16 (Ubuntu 18.04)
CPU architecture: x86_64
Kernel: 4.15.0-15-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by droidmonkey** [comment]
Try increasing the autotyping delay in the settings

**Comment by Rivriet** [comment]
I tried it by increasing time up to 800 ms and it doesn't help.

**Comment by Rivriet** [comment]
@droidmonkey - any other ideas? Do you need more information/logs?

**Comment by droidmonkey** [comment]
I don't have a clue, I'll have to try it myself in the debugger.

**Comment by weeix** [comment]
I can randomly reproduce a similar issue on macOS as well. Will try to increase Auto-Type delay as @droidmonkey suggest. Thanks.

![ezgif com-optimize](https://user-images.githubusercontent.com/6592791/39297730-74e93ef8-496e-11e8-8f48-167511a18cbb.gif)

**Comment by droidmonkey** [comment]
Ahhhh yes this is a known issue if you home down the Ctrl or alt keys. Perhaps we need to delay typing until the shortcut is released.

**Comment by droidmonkey** [comment]
I'll see if I can sneak a fix into 2.3.3
