### ISSUE TITLE
Idea: Cleanup broken URL links

### ISSUE THREAD

**Issue by ftorto** [keepassxreboot/keepassxc#1865]
It could be interesting to have an option that focus on entries having broken URL links
This could help to cleanup a 10 years old database.

## Expected Behavior
In the menu, click on a button `detect broken links`.  
This acts as a filter showing/marking URL that returns a HTTP CODE `4xx` or `5xx`

## Current Behavior
Currently, to have this result, we have to test every link one by one which can be time consuming

## Possible Solution
* "Tag" broken links to be able to filter them
* Get these entries directly as a result

## Steps to Reproduce (for bugs)
*na*

## Context
Old database containing many many old passwords that need to be refresh

## Debug Info
*na*

**Comment by droidmonkey** [comment]
We won't be implementing a feature for "broken links" but the new browser report in 2.7.0 let's you quickly see all your URL's in a database.
