### ISSUE TITLE
KeePassXC-Browser Timeout

### ISSUE THREAD

**Issue by emeygret** [keepassxreboot/keepassxc#1866]
Hi,

I Install KeePassXC-Browser and KeePassXC, KeePassXC-Browser always says "Timeout or not connected" If I clic on reload connection, it is ok but don't have time to use it, new timeout happen.

in keepassxc Browser Integration checked for Firefox and Google Chrome
I have new entry "KeePasXC-Browser-Setting with Public key for Firefox and Chrome, so connection seems to be ok.

When I am on website with credential, I have to clic on reload and then I can select the credential but most of time I have a new timeout and I have to do this several times and sometime it is working :)

I have the same behavior with Google Chrome
org.keepassxc.keepassxc_browser.json seems to be ok
keepass-proxy is launched when I clic on reload or connect
If I try with proxy disabled, when I clic on reload or connect, KeePassXC is launched but I don't have time to unlock the database, keepassxc was closed, it don't seems to crash, just it is closed. 

I would like to debug but "Go to the extension page, check Developer mode" I don't find Developer mode? "Extension Page" is it the KeePassXC-Browser Setting page in the browser? 

if I can help more say me what can I do!

## Debug Info
KeePassXC - 2.3.1
KeePassXC-Browser - 1.0.1
Firefox - 59.0.2
Chrome - 66.0.3359.117

Operating system: Windows 10 Pro 1709 - 16299.371
CPU architecture: AMD64

Enabled extensions:
- KeePassXC-Browser

**Comment by droidmonkey** [comment]
This issue exists over in the keepassxc-browser repo.
