### ISSUE TITLE
Connects to the Internet 

### ISSUE THREAD

**Issue by balibebas** [keepassxreboot/keepassxc#1867]
Is this feature automatic or off-by default? One of the best parts of KeePassX was that it didn’t try calling out to the Web. Any Web communication is a potential attack vector.

**Comment by jhabdas** [comment]
From the `README`:

> The KeePassHTTP protocol is not a highly secure protocol. It has a certain flaw which could allow an attacker to decrypt your passwords should they manage to impersonate the web browser extension from a remote address.

**Comment by droidmonkey** [comment]
@balibebas we only connect to sites when you ask us to. For example, when downloading a favicon, we will connect to the site that you put in the URL field to try and obtain one. Other then that, we do not connect to anything else. Even the KeePassHTTP protocol, which is entirely optional and can be disabled in settings, only connects to localhost.
