### ISSUE TITLE
Discussion: Update on Collaborating with KeePassX?

### ISSUE THREAD

**Issue by ghost** [keepassxreboot/keepassxc#1868]
More than a year has passed since #43 was originally opened. Has there been any word from the KeePassX project maintainer regarding their thoughts on this fork? I'm also curious what the [Tails](https://tails.boum.org) team thinks about the direction this project has taken over the last year given they integrate KeePassX into their live OS.

**Comment by droidmonkey** [comment]
At this point, we have definitely solidified our placement as an alternative KeePass client independent of (but based on) KeePassX. We are a first class package in the Ubuntu Bionic release coming out this month. It no longer makes sense to back port to KeePassX.

With that said, I still see a lot of value in KeePassX as a lower feature, non-networked version. Unfortunately, several key features (kdbx4, yubikey, etc) are not incorporated and at this point would be a gigantic effort to do so. A better path would be to build a stripped down version of KeePassXC (ie without networking) and brand it as KeePassX.
