### ISSUE TITLE
Add option to rename/unhide the lockfile

### ISSUE THREAD

**Issue by toabi** [keepassxreboot/keepassxc#187]
## Expected Behavior

To prevent data loss because of parallel editing the lockfile is created next to the DB. This is useful. 

This works well in a multiuser environment when everybody accesses the shared db on a network location.

Some of our users also have sync software to mirror the files to their local harddisk. But this sync software usually skips hidden files.

## Current Behavior

Compared to the old keepassx, this file is now hidden so it won't be synced.

## Possible Solution

Add an option to modify the lock-filename or add checkbox to not make it hidden. Although this is problematic because every user would have to create this setting. It would be better to have it stored in the db itself or a file which is stored next to the db.

## Context

We are using KeePass files for groups of multiple people, where the db is stored on a NAS and people access it directly via SMB/AFP or sync it (in this case Synology CloudStation).

## Your Environment
* macOS
* Synology CloudStation

**Comment by deknos** [comment]
We use this feature, too in a heterogenous work environment (linux and windows desktop) and share our passwords in keepassxc. This would be very important.

**Comment by droidmonkey** [comment]
Seems very easy to implement. Here is my question: would you guys value the ability to open the database read-only from the start? Then a lock file would only be created and displayed if opened in read/write mode.

**Comment by droidmonkey** [comment]
Closing in favor of #1002
