### ISSUE TITLE
file permissions are changed when database is saved in "unsafe" mode on  Linux

### ISSUE THREAD

**Issue by PeRap** [keepassxreboot/keepassxc#1871]
On Linux I see the following:

When the checkbox "Safely save database files (may be incompatible with Dropbox, etc)" is checked everything works like expected, file permissions remain as set before.

But when unchecked, the database file permissions are changed to "600" each time the database is saved.

In my case I have permissions set to 660 to allow group members to read and write the database. 
I observed this behaviour while playing around with the configuration options. Re-enabling the option is fine for me. However, this should be checked.

Debug Info:
KeePassXC - Version 2.3.1
Revision: 2fcaeea
Libraries:
- Qt 5.10.1
- libgcrypt 1.8.2

Operating system: Manjaro Linux
CPU architecture: x86_64
Kernel: linux 4.14.34-1-MANJARO

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by droidmonkey** [comment]
This is because unsafe saves actually create a new file. Although it might be good to reapply the existing access restrictions. I'll add this to the stack.

**Comment by droidmonkey** [comment]
This is caused by Qt temporary file class forcing 0600 permissions on file creation. A more recent issue better captures the issue.
