### ISSUE TITLE
Request : Support unicode with Linux shortcuts

### ISSUE THREAD

**Issue by ChameleonScales** [keepassxreboot/keepassxc#1872]
I'd like the app to support unicode characters typed with Linux shortcuts (Ctrl+Shift+U+number)
Currently when I try to type one in a field like the password field to enter in my database, it doesn't type anything. I have to open a notepad and type it there, then copy-paste.

## Debug info :
KeePassXC - Version 2.3.1
Revision: 2fcaeea

Libraries:
- Qt 5.5.1
- libgcrypt 1.8.1

Operating system: Linux Mint 18.2
CPU architecture: x86_64
Kernel: linux 4.13.0-39-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by ChameleonScales** [comment]
So I found out that this missing feature is due to the fact that this application is based on Qt. I don't know if a workaround would be possible to develop (it seems [some Qt apps have found a way](https://github.com/telegramdesktop/tdesktop/issues/1288#issuecomment-155413062) but I can't confirm it) but it would be really useful, as this KeePassXC is all about passwords and strong passwords are a lot about character diversity.

**Comment by droidmonkey** [comment]
Based on [this comment](https://github.com/telegramdesktop/tdesktop/issues/1288#issuecomment-157534711) and the last one, it does not seem like there is a work around at all. Either it is an "ibus" configuration issue (have no idea what that is) or you need to use GTK+ since these "Linux Shortcuts" are actually GTK+ shortcuts. This is not going to be implemented in KeePassXC at this time.

**Comment by ChameleonScales** [comment]
How about making a GTK version of KeePassXC ?

**Comment by ChameleonScales** [comment]
Thanks.
I've tried a workaround by assigning an xdotool command to a keyboard shortcut but it doesn't work well at all and there's apparently no better workaround.
Since then I've tried bitwarden and it seems to fit my needs better while also not having this issue, so I think I'll use it instead.
