### ISSUE TITLE
Ctrl-(Shift-)Tab doesn't work right after unlocking a database

### ISSUE THREAD

**Issue by l0b0** [keepassxreboot/keepassxc#1876]
In some very specific cases changing the tab with the keyboard doesn't work.

## Steps to reproduce
1. Open at least two databases
2. (Close and reopen KeePassXC - I'm not sure if this is needed)
3. Unlock one database
4. Press <kbd>Ctrl-Tab</kbd> or <kbd>Ctrl-Shift-Tab</kbd>

## Expected behaviour
KeePassXC should navigate to the next or previous tab.

## Actual behaviour
Nothing happens.

## Workaround
Doing any of the following seems to "unstick" navigation:

- Lock the databases using <kbd>Ctrl-l</kbd>.
- Click on an entry in the now open database.
- Click on another tab.

## Context
These keyboard shortcuts are really useful.

## Debug Info
KeePassXC - Version 2.3.1
Revision: 2fcaeea

Libraries:
- Qt 5.10.1
- libgcrypt 1.8.2

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 4.16.3-1-ARCH

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by droidmonkey** [comment]
This happens right after unlock of the database. Once you select an entry the keyboard shortcut works again.

**Comment by droidmonkey** [comment]
The reason this does not work is because the search field is focused after unlocking the database. I am going to try to register CTRL+[SHIFT]+TAB as an application global shortcut that will switch tabs no matter what the focus.

**Comment by droidmonkey** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [#1876 (CTRL+[SHIFT]+Tab doesn't switch db's)](https://trello.com/c/8rwaOHgl/2-1876-ctrlshifttab-doesnt-switch-dbs)

**Comment by droidmonkey** [comment]
This was corrected in #2402
