### ISSUE TITLE
 Hyphen interpreted as tilde in compose key sequences

### ISSUE THREAD

**Issue by l0b0** [keepassxreboot/keepassxc#1877]
## Steps to Reproduce
1. Focus any text field (search, title, etc.)
2. Press the compose key, then <kbd>a</kbd>, then <kbd>-</kbd> (hyphen)

## Expected Behavior
The character “[ā](https://www.compart.com/en/unicode/U+0101)” (Latin Small Letter A With Macron) should appear.

## Current Behavior
The character “[ã](https://www.compart.com/en/unicode/U+00E3)” (Latin Small Letter A With Tilde) appears. I observe the same behaviour with <kbd>n</kbd> and <kbd>o</kbd>. There may be other compose key mismatches, but I haven't done a thorough check.

## Context
I have tested this compose key in urxvt, Firefox, Pidgin and Thunderbird, and all of them produce the correct character “ā”. This could lead to a mismatch between usernames, passwords and URLs as entered in KeePassXC and as used elsewhere.

## Debug Info
KeePassXC - Version 2.3.1
Revision: 2fcaeea

Libraries:
- Qt 5.10.1
- libgcrypt 1.8.2

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 4.16.3-1-ARCH

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by davidaparicio** [comment]
I have the same issue with KeePassXC 2.5.4/US International keyboard layout, on Mac OS.
The composition doesn't work on hidden input, but works in clear plain text..

![image](https://i.imgur.com/Rf1R2Ld.png)

**Comment by droidmonkey** [comment]
@davidaparicio that is a known Qt bug.

**Comment by l0b0** [comment]
@droidmonkey Do you have a link to the bug? It would help immensely to close this ASAP.

**Comment by droidmonkey** [comment]
https://bugreports.qt.io/browse/QTBUG-73363

**Comment by picajoso** [comment]
Yep, this isn't solved, as I've explained on [#7224](https://github.com/keepassxreboot/keepassxc/issues/7224).
