### ISSUE TITLE
Support for HMACOTP

### ISSUE THREAD

**Issue by p-b--** [keepassxreboot/keepassxc#1878]
I haven't been able to find this in the documentation or any other issues -- does KeePassXC support the HMACOTP placeholder?

Based on searching in the Entry header file it appears that it doesn't, but I wasn't sure if I was reading that correctly.

https://github.com/keepassxreboot/keepassxc/blob/dd246f1ff06a2c0bacf28a43e2b0abf46d0494d9/src/core/Entry.h#L158-L180

**Comment by droidmonkey** [comment]
What is that? Do you have a reference

**Comment by p-b--** [comment]
https://keepass.info/help/base/placeholders.html#hmacotp

> The {HMACOTP} placeholder generates a HMAC-based one-time password as specified in RFC 4226. The shared secret can be specified using one of the following entry string fields: HmacOtp-Secret (the UTF-8 representation of the value is the secret), HmacOtp-Secret-Hex (secret as hex string), HmacOtp-Secret-Base32 (secret as Base32 string) or HmacOtp-Secret-Base64 (secret as Base64 string). The counter is stored in decimal form in the HmacOtp-Counter field.

**Comment by weslly** [comment]
Wouldn't be very hard to implement as the algorithm is very similar to TOTP, but I have yet to see any service actually using count-based HOTP instead of TOTP or some other proprietary OTP methods, so I'm not sure if there's actual real-life use cases to justify adding this feature.

**Comment by p-b--** [comment]
Duo supports both TOTP and HOTP tokens, I've used HOTP due to the fact that resyncing TOTP is not well supported in the Duo platform.

https://duo.com/docs/administration-devices#importing-third-party-hardware-tokens

> 
Duo also works with third-party one-time password (OTP) hardware tokens, such as YubiKey OTP or any other SHA-1 OATH HOTP-compatible tokens. **TOTP tokens are not recommended for use with Duo, as full support for TOTP token drift and TOTP resync is not available.**

**Comment by rugk** [comment]
Just a question: Is this issue about adding HOTP support for *entries* in the KeePassXC save?
Or is it about unlocking your database with a HOTP token from a hardware key?

**Comment by p-b--** [comment]
This issue is for the former.

**Comment by cornercase** [comment]
I use a VPN service that uses HOTP and it would be great to be able to generate the codes in KeePassXC.

**Comment by dekked** [comment]
My bank also uses HOTP. I have hacked away their app and extracting my seed, now I am just missing support in KeepassXC :)

**Comment by dekked** [comment]
My bank also uses HOTP. I have hacked away their app and extracting my seed, now I am just missing support in KeepassXC :)

**Comment by adia** [comment]
I'm using a "DocuSign Signature Appliance" which needs HOTP - OTPClient works fine:
https://github.com/paolostivanin/OTPClient
Of course KeepassXC support would be nice!
