### ISSUE TITLE
Missing digest (SHA-256) for KeePassXC-2.1.0.dmg

### ISSUE THREAD

**Issue by joschi** [keepassxreboot/keepassxc#188]
It looks like the SHA-256 digest for the `KeePassXC-2.1.0.dmg` file in the [2.1.0 release](https://github.com/keepassxreboot/keepassxc/releases/tag/2.1.0) is missing.

It would be great if you could add it, so that people could verify their downloads with another method than the GnuPG signature.

**Comment by TheZ3ro** [comment]
I was pretty sure I uploaded that. 
Now it should be online.

PS: Remember that verifying the digest only prove the Integrity of the file. You can prove Integrity AND Authenticity only with the PGP signature.

**Comment by joschi** [comment]
The digest is now available in the GitHub release tab. Thanks!

> PS: Remember that verifying the digest only prove the Integrity of the file. You can prove Integrity AND Authenticity only with the PGP signature.

I know, that particular digest was only needed for the Homebrew Cask (#182).
