### ISSUE TITLE
[snap] KeePassXC should auto-connect removable-media

### ISSUE THREAD

**Issue by Ads20000** [keepassxreboot/keepassxc#1886]
## Expected Behavior

KeePassXC should recognize my USB stick out-of-the-box.

## Current Behavior

KeePassXC had `raw-usb` connected but that didn't seem to be enough? KeePassXC failed to access my USB stick until I had run `snap connect keepassxc:removable-media removable-media`. This isn't particularly user-friendly (especially since no software-centre is able to connect interfaces yet, so this can only be done via Terminal). 

## Possible Solution

KeePassXC should auto-connect to `removable-media`. KeePassXC can request the auto-connection [here](https://forum.snapcraft.io/c/store). Once requested (and explained why it's needed), people from snappy with vote on the proposal and, if the vote passes, the auto-connection will be put in place and any new snap install of KeePassXC will have removable media like USB sticks working out-of-the-box.

## Steps to Reproduce (for bugs)

1. Insert a USB stick to your computer
2. Navigate to /media in your file manager, observe that the USB stick is recognized there
3. `snap install keepassxc`
4. Click 'Create new database'
5. Navigate to /media
6. Observe that the USB stick isn't there

## Context

I'm trying to save passwords to a USB stick which will allow me to have them off my computer and means I'll be able to access them even if my SSD dies for whatever reason.

## Debug Info

KeePassXC - Version 2.3.1
Revision: 2fcaeea
Distribution: Snap

Libraries:
- Qt 5.7.1
- libgcrypt 1.7.6-beta

Operating system: Ubuntu Core 16
CPU architecture: x86_64
Kernel: linux 4.15.0-20-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

Libraries:
- LIBS

Operating system: OS
CPU architecture: ARCH
Kernel: KERNEL

Enabled extensions:
- EXTENSIONS

```
$ snap info core
tracking:  beta
refreshed: 2018-04-29T19:29:48+01:00
installed:   16-2.32.6 (4571) 90MB core
```

**Comment by droidmonkey** [comment]
Take it up with the snap folks, this is the only solution.

**Comment by Ads20000** [comment]
[Request not granted](https://forum.snapcraft.io/t/auto-connecting-the-removable-media-interface-for-keepassxc/5207/4?u=ads20000). There should be a feature grown in GNOME Software (and hopefully other software centres) at some point that allows for the interfaces to be connected in that, which would help the user experience here :)

**Comment by droidmonkey** [comment]
I do wish the snap folks build a GUI around the interfaces at some point and adding it to the settings for the OS. That would go a long way to making this more discoverable and user friendly. Another good option would be to have a system like Android where the app asks the user to grant it permission (this is actually done at the core snap level) and if granted it would connect the interface.
