### ISSUE TITLE
[Feature Request] Sync through Webdav url

### ISSUE THREAD

**Issue by navdeepio** [keepassxreboot/keepassxc#1889]

**Comment by droidmonkey** [comment]
This is already possible if you mount the webdav. We are not integrating external network protocols at this time.

**Comment by WebOscar** [comment]
Sorry, but we have mounted the webdav url and it doesn't sync at all. This is very annoying because it only saves the changes of the user who last changed the database.

**Comment by droidmonkey** [comment]
That is a separate bug regarding detecting changes in network shares on linux.
