### ISSUE TITLE
Unable to open attachments in Flatpak

### ISSUE THREAD

**Issue by dermirt** [keepassxreboot/keepassxc#1891]
I can not open any attachment in my KeepassXC. Within KeepassX it is possible.

## Expected Behavior
Double-click an attachment of an entry should open it.

## Current Behavior
Double-clicking the attachment of an entry leads to nothing happening.
Within Entry edit mode - Advanced - Open attachment leads to "Unable to open attachments: ... Cant open file ..."

## Steps to Reproduce (for bugs)
Way A:
1. Choose entry with attached file
2. Check attachments tab
3. Double click attachment

Way B:
1. Double click entry with attached file (Edit entry mode)
2. Go to advanced
3. Choose attachment
4. Click "Open"

## Context
Opening attachment.

## Debug Info
KeePassXC - Version 2.3.1
Revision: 2fcaeea
Distribution: Flatpak

Libraries:
- Qt 5.10.1
- libgcrypt 1.7.3

Operating system: Linux 4.9.0-6-amd64
CPU architecture: x86_64
Kernel: linux 4.9.0-6-amd64

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by droidmonkey** [comment]
Are you using keepassx as a flatpak as well? Likely a flatpak issue if not.

**Comment by dermirt** [comment]
I installed KeepassX via apt-get. So building it manually should fix the issue?

**Comment by droidmonkey** [comment]
Yah they likely need to add a plug or whatever interface to dbus so that the open command can be issued. I had to do the same for snaps. I'll leave this open for tracking until the flatpak is fixed. NOTE: we are not the owners of the flatpak distribution.

**Comment by AsavarTzeth** [comment]
First of, I have verified that you indeed cannot open an attachment from within KeePassXC, if it is installed as a Flatpak.

This could certainly be solved by allowing access to the user home, similar to what you do with plugs. However poking holes in the sandbox is not the correct long-term solution.

Since snaps is now [also adopting](https://github.com/flatpak/xdg-desktop-portal/pull/155) [xdg-desktop-portal](https://github.com/flatpak/xdg-desktop-portal), you really should try to make the application work with this as much as possible. This already works for most actions, like opening a database file, or adding attachments.

I am no expert on Qt, nor C++, but I will assist in anyway I can.

**Comment by droidmonkey** [comment]
Snaps and Flatpak are completely different implementations. Poking holes in the sandbox is the only way to get an isolated instance to talk to the rest of the system (ie issue the "open this file" command). 

Hard coding paths is not a good idea at all. We ask Qt for the temporary file directory, Flatpak should be returning the proper tmp directory to use.

**Comment by confidentidiot** [comment]
I just wanted to confirm that I am having the same issue as @dermirt .  I am running version 2.3.3 on Ubuntu 16.04 and had installed via `snap`.  If there is anything I can do to help troubleshoot or test a possible solution (I am not a developer, unfortunately), please let me know.

**Comment by droidmonkey** [comment]
Noted, I confirmed this does not work in snaps either. This will take a bit of digging.

**Comment by cnegrisanu** [comment]
Same issue here. I cannot open Attachments.

KeePassXC - Version 2.3.3
Revision: 0a155d8
Distribution: Snap

Libraries:
- Qt 5.7.1
- libgcrypt 1.7.6-beta

Operating system: Ubuntu Core 16
CPU architecture: x86_64
Kernel: linux 4.15.0-22-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by droidmonkey** [comment]
This needs to be reported over in the Flatpak repository: https://github.com/flathub/org.keepassxc.KeePassXC

**Comment by Mpic** [comment]
Opening attachments does not work on Windows either...
