### ISSUE TITLE
Auto-fill one-time passwords (Feature Request)

### ISSUE THREAD

**Issue by schnappijedi** [keepassxreboot/keepassxc#1892]
Would it be possible to autofill one-time passwords when using the KeePassXC-Browser addon?

One time passwords provide great extra security especially when logging in from public machines and from brute forcing a login. On non-public machines once a KeePass database is opened autofilling one-time passwords already in the database doesn't really deduct from security as the information is already available in the opened database (but currently must be entered manually).

**Comment by varjolintu** [comment]
At this point this is not possible. Entering a OTP needs an user interaction.

**Comment by droidmonkey** [comment]
I thought this was implemented through #1850

**Comment by varjolintu** [comment]
@droidmonkey No it wasn't. That PR that changed the TOTP transfer to work without any additional attributes. I think the request was that TOTP could be filled automatically from the browser extension.

**Comment by schnappijedi** [comment]
@droidmonkey @varjolintu Do you think this might this become a feature in the future or is it literally not possible/ needs to be requested in another place/ repository?

**Comment by droidmonkey** [comment]
To auto fill we would need to properly detect an OTP form field on the website. I am not sure they are as standardized as username/password fields.

**Comment by varjolintu** [comment]
There isn't a standard for this. That's why I didn't even try to implement it but decided to stay with manual filling. However, those TOTP fields will be filled if you choose own credential fields for the site, use the TOTP input field as a string field and add `KPH: {TOTP}` attribute with value `{TOTP}` to the entry.

**Comment by droidmonkey** [comment]
Should add that to an FAQ
