### ISSUE TITLE
Auto Type Does Not Work in SecureCRT 7.0.1

### ISSUE THREAD

**Issue by kraigrepp** [keepassxreboot/keepassxc#1896]
Auto type does not work on a Mac in SecureCRT.  The auto type box pops up and it types text in but it types in all A's.  I have tested this on multiple Mac's and they all have the same behavior.  Auto type works in all my other applications.  

KeepassXc 2.3.1

**Comment by weslly** [comment]
Related: https://github.com/keepassxreboot/keepassxc/issues/1833#issuecomment-380293983
