### ISSUE TITLE
Use pop-up unlock dialog for browser extension

### ISSUE THREAD

**Issue by rob-01** [keepassxreboot/keepassxc#1897]
I'd like to request the feature of unlocking the keepassxc database inside the browser or in a separate pop-up window. 

I use a window manager (i3wm) that doesn't show the minimize button on windows, so I restrict keepassxc to one workspace and no pop-ups. This requires a lot of switching back and forth between workspaces since I have enabled a fairly frequent autolock setting. I'd like the database password entry to pop-up somewhere in the workspace I'm currently working in.

**Comment by varjolintu** [comment]
I have a test branch of a feature that uses the same popup window with AutoType feature. Does that popup work with you with i3wm? If so, I might finish the feature and make it to a PR.

**Comment by rob-01** [comment]
@varjolintu If you're referring to the dropdown pop-up that shows after clicking in a username field inside the browser, then yes that works in i3.
What would the workflow be? I imagine something like 1-click username field box in browser, 2-type password, 3-press enter key, and 4-continue as usual. I'm sure whatever you've created is better than what I have, so adding your PR would be much appreciated!

**Comment by varjolintu** [comment]
I'm also using i3 as my default WM so I'll make a few tests in the next few days :)

I was referring to the unlock popup AutoType launches when database is locked.

**Comment by rob-01** [comment]
Ok, great thanks! I'm now able to get the autotype popup working for me, so yes, integration with that would work.

**Comment by varjolintu** [comment]
Same here. The popup works great. I'm making a PR for this soon.

**Comment by droidmonkey** [comment]
This is working as of 2.4.0

**Comment by varjolintu** [comment]
Except it's not using the same dialog as Auto-Type yet.

**Comment by droidmonkey** [comment]
Implemented in 2.6.0
