### ISSUE TITLE
Field references are only resolved one level down

### ISSUE THREAD

**Issue by dovecode** [keepassxreboot/keepassxc#1898]
When autotyping, any field reference is only resolved to one level. If a field references another field that in itself is a reference, the verbatim reference is inserted, not the ultimate field value.

## Expected Behavior

When a field is a reference to another field, the reference resolution should continue recursively until a non-reference field value is encountered.

## Current Behavior

If a field references another field, that other field's value is inserted when autotyping, even if the referenced field is another reference.

## Possible Solution

The logic that determines that a field is a reference and looks up the referenced should recursively apply the same logic to the new field.

## Steps to Reproduce (for bugs)

1. Create a new password entry, "entry 1", with Username "user" and Password "password".
2. Clone "entry 1", checking the **Replace username and password with references** option. Name the new entry "entry 2"
3. Clone "entry 2", again checking the **Replace username and password with references** option. Name the new entry "entry 3"
4. Open a blank text editor (Notepad/TextEdit)
5. Switch to KeePassXC select "entry 3" use the **Perform Auto-Type** option (Command+V or Ctrl+V)
6. Notice that references are inserted, instead of "username password"

## Context

My company has many systems that use the same passwords, some with the same user name, others with variations of the user name. I use references to manage these, such that the master password is only stored once. The management of thee entries would be simpler if I could have two levels of references working.

## Debug Info

KeePassXC - Version 2.2.4
Revision: 4723f66

Libraries:
- Qt 5.9.1
- libgcrypt 1.8.1

Operating system: macOS High Sierra (10.13)
CPU architecture: x86_64
Kernel: darwin 17.4.0

Enabled extensions:
- KeePassHTTP
- Auto-Type
- YubiKey

**Comment by droidmonkey** [comment]
You need to update to 2.3.0
