### ISSUE TITLE
KeePassXC 2.3.1 on Linux freeze while trying to open database

### ISSUE THREAD

**Issue by aquaritus** [keepassxreboot/keepassxc#1899]
After upgrading on Version 2.3.1 on ParrotSec Linux via the package manager, the program freezes when I try to open my Database. I have to force quit the program, as it doesn't react to inputs.
I can still open the database under Windows and with the following 
AppImage Version: "KeePassXC - Version 2.2.2"

## Expected Behavior
KeePassXC 2.3.1 opens the Datbase an doesn't freeze

## Current Behavior
When I try to open my database the programm freezes an doesn't react to inputs.

## Debug Info
KeePassXC - Version 2.3.1
Revision: 2fcaeea

Libraries:
- Qt 5.9.2
- libgcrypt 1.8.2

Operating system: Parrot GNU/Linux 4.0-beta
CPU architecture: x86_64
Kernel: linux 4.15.0-parrot17-amd64

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by droidmonkey** [comment]
Can you use the appimage version?

**Comment by aquaritus** [comment]
Yes. The AppImage version works.

**Comment by aquaritus** [comment]
It seems like there is a problem with ParrotSec. Using the same version on ubuntu works perfectly fine.

**Comment by droidmonkey** [comment]
I'd love to diagnose this but I couldn't get ParrotSec to install on VirtualBox...

**Comment by PalinuroSec** [comment]
sorry for the late answer here on guthub

we spotted the bug some months ago.
it was caused by the firejail sandbox system because it denied the execution permissions on write access memory sections.
we were forced to temporarily disable the memory protection, but now keepassxc works properly
