### ISSUE TITLE
Beta version in PPA conflicts with PlayOnLinux due to libcurl3

### ISSUE THREAD

**Issue by leethax666** [keepassxreboot/keepassxc#1902]
Installing PlayOnLinux from the PPA removed keepassxc-beta due to a conflicting dependency with libcurl3. Attempting to install keepassxc-beta afterwards doesn't work due to that library.

**Comment by droidmonkey** [comment]
Which PPA are you referring too

**Comment by leethax666** [comment]
This one from the KeepassXC website: https://launchpad.net/~phoerious/+archive/ubuntu/keepassxc

**Comment by phoerious** [comment]
keepassxc-beta is not an up-to-date version. Install the normal keepassxc package.

**Comment by leethax666** [comment]
that works, thanks
