### ISSUE TITLE
Allow user to change number of key transformation rounds during database creation

### ISSUE THREAD

**Issue by phoerious** [keepassxreboot/keepassxc#191]
KeePassXC allows the user to modify the number of key transformation rounds. This is a tradeoff between security and decryption speed. High numbers induce a constant delay when opening a database but also harden the master key significantly against bruteforce and dictionary attacks.

## Expected Behavior

Users should be able and encouraged to set an appropriate number of transformation rounds when creating a new database or changing the master password, preferably using the automatic benchmarking functionality. The feature should be usable and understandable even by novice users.

## Current Behavior

This setting is currently quite hidden and many users probably don't know about it.

**Comment by louib** [comment]
It's also not really clear what the `Benchmark` button does. I guess it sets the number of rounds so that it takes  ~1s for the key derivation, but it's not necessarily obvious. Maybe we could have default options like 1s and 2s for example.

**Comment by phoerious** [comment]
I agree. However, setting it to some time value is not a solution because your PC may be faster or slower than mine. When it says "1s" it may falsely suggest, that an attacker always needs 1 second, even on a large GPU cluster. I would rather provide a couple of presets like "medium, high, very high and extremely high security" as well as some option to set it to the best your PC has to offer without making unlocking too slow.

**Comment by louib** [comment]
@phoerious what about merging the ChangeKeyWidget and the DatabaseSettingsWidget? This way, during database creation, we could specify all the database settings (database name, default username, transformation rounds) as well as the key.

**Comment by phoerious** [comment]
Sounds like a sane choice to me.

**Comment by louib** [comment]
The other option would be to move the rounds settings out of `DatabaseSettings` and into `ChangeMasterKeyWidget`.

**Comment by phoerious** [comment]
I think we should merge both somehow. Having two places to change such things doesn't really make sense. But we can't always display everything. Maybe show the rounds setting when changing the master password and show the other options as "Additional database settings" only when changing the master password, not when initially creating a new DB?

**Comment by louib** [comment]
With TwoFish now available we might also want to add the algorithm choice in the database creation.

**Comment by phoerious** [comment]
Probably, yes.

**Comment by louib** [comment]
Then what about a settings page divided in sections
- Encryption
  * master key / key file
  * encryption algo
  * transformation rounds
- General settings
  * database name
  * database description
- Advanced settings (collapsed by default)
  * recycle bin, etc...

This way we could hide the advanced settings when creating but not when modifying, and the database rounds / encryption options would be present when creating a new database.

**Comment by phoerious** [comment]
Yeah, I was thinking about something like that. Maybe also hide the advanced settings altogether until the user clicks a checkbox "Show advanced settings".

**Comment by TheZ3ro** [comment]
Guys remember that the new KDBX4 format will add more db configuration (ChaCha20 and Argon2)

**Comment by phoerious** [comment]
Which makes it more important to have a sane strategy to manager and present those advanced settings to the user.

**Comment by TheZ3ro** [comment]
Yes. But take a look at it so we don't need to rewrite everything when implementing it. :wink:

**Comment by noraj1337** [comment]
Supporting AES Twofish will allow to support Twofish Database generating from KeePass.

It is a very common problem : a user create a Twofish database on KeePass 2 under Windows and then go to Linux and want to open the same database with KeePassX/KeePassXC but can't because it only support AES Rijndael.

**Comment by phoerious** [comment]
Twofish support is already implemented and will be part of 2.2.0. If you need it now, you can compile the develop branch.

**Comment by noraj1337** [comment]
@phoerious : Thanks, that's good to know. I don't need it, I'm patiently waiting for KDBX4 support. Is there a release date for KDBX4 or is it too early? And does KeePassXC has a roadmap page?

**Comment by srwareham** [comment]
Would it be fair to rename this issue "Add additional settings during initial database creation?" After loading up version 2.3, I wanted to make a new database using KDBX4 but found the 'create->edit' process unintuitive. After a bit of digging, it looks like this issue covers such an improvement and a new one need not be created--does that seem correct?

**Comment by phoerious** [comment]
We do plan to give the database creation workflow a little love for 2.4..
