### ISSUE TITLE
macOS Sierra: Password text box font size, at "View/Edit entry" window,  is too small

### ISSUE THREAD

**Issue by andreoliv** [keepassxreboot/keepassxc#1917]
(Issue noted on macOS Sierra - 10.12.6 and KeePassXC - Version 2.3.1) The font size for the password text at the "View/Edit entry" window, is much smaller than the username text's font size. There is no way to adjust the Password's font size in preference settings. The reason may be related to different font type on username text box and password text box.

## Expected Behavior

There should be a way to change password's font size for "View/Edit entry" window.

## Current Behavior

Currently there is no way to change password's text box font size. Although there is a workaround, which is setting the environment variable QT_SCALE_FACTOR to 1.25 on .bash_profile (export QT_SCALE_FACTOR=1.25), it only works if the user calls the app from the terminal (/Applications/KeePassXC.app/Contents/MacOS/KeePassXC) and QT_SCALE_FACTOR changes the font size on every text related to any control at each and every single application's window.

## Possible Solution

Allow the user to set, specifically,  the password's text box font size in preference settings.

## Context

Making the password text box content more legible.

## Debug Info

KeePassXC - Version 2.3.1
Revision: 2fcaeea

Libraries:
- Qt 5.9.3
- libgcrypt 1.8.2

Operating System: macOS Sierra - 10.12.6
CPU architecture: x86_64
Kernel: darwin 16.7.0

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by andreoliv** [comment]
Adding a Screenshot, which if viewed at any browser will show it bigger than the real KeepassXC "View/Edit entry" GUI window on macOS: 
<img width="970" alt="screen shot 2018-05-07 at 13 11 32" src="https://user-images.githubusercontent.com/3373653/39706893-12bcc35a-5213-11e8-841c-1344948188c4.png">

**Comment by droidmonkey** [comment]
The password field uses monospace font (also notes field so you'll see it there too). You should change your monospace font in the settings to fix this.

**Comment by andreoliv** [comment]
> You should change your monospace font in the settings to fix this.

Unlike linux (Debian, Mint on cinnamon or Ubuntu), there is no such settings on mac OSX or macOS Sierra (10.12.6). Generally each application tends to offer its own text font size settings. There is the "Font Book" application in which you can manage the installed and the "to be" installed fonts, regarding the system's fonts.

![linuxmintfonts_dlg_window](https://user-images.githubusercontent.com/3373653/39771797-a866e01c-52f3-11e8-8ad2-6d490d66f6f9.png)

Although it's possible to hack and customize any macOS system's font in general, it's something I would avoid at all costs.

**Comment by droidmonkey** [comment]
I am not a Mac user. Does any other Mac user see the same behavior?

**Comment by michaelblyons** [comment]
I concur that the password font is small, and I don't see anywhere in-app to change them. I wasn't sure if "in the settings" in

> The password field uses monospace font (also notes field so you'll see it there too). You should change your monospace font in the settings to fix this.

was supposed to be in-app or somewhere OS-level.

**Comment by droidmonkey** [comment]
Is this still a problem?

**Comment by michaelblyons** [comment]
I just checked 2.4.0. It seems very similar to the original screenshot. I'd categorize this issue as "minor," but I have decent eyesight. 🤷‍♂️

**Comment by droidmonkey** [comment]
I'll leave this open, we may have to implement a custom stylesheet on macOS that increases the font size. It looks like the macOS monospace font runs smaller than the regular font.

**Comment by andkopp** [comment]
I think that with the current MacOS Catalina (10.15.1) and KeePassXC 2.5.1 the issue got worse. The size is even more different. It affects both the password field in the entries but also the password field for unlocking the database.

<img width="359" alt="entry" src="https://user-images.githubusercontent.com/10760101/69561443-ac23af00-0fad-11ea-81c0-cec9da31bac3.png">

**Comment by bheimbaugh** [comment]
Same here: The password font is not only too small to read but also does not appear to be monospaced or use slashed 0's (to distinguish from O's). It really needs to be configurable. 

![Screen Shot 2019-12-07 at 11 17 03 AM](https://user-images.githubusercontent.com/39772599/70378172-23790d00-18e3-11ea-999b-0292a70a4f23.png)

KeePassXC - Version 2.5.1
Revision: 0fd8836

Qt 5.13.1
Debugging mode is disabled.

Operating system: macOS 10.15
CPU architecture: x86_64
Kernel: darwin 19.0.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
 libgcrypt 1.8.5

**Comment by phoerious** [comment]
That is not a monospace font. What on Earth is going on there?
