### ISSUE TITLE
Browser extension for Firefox hides login prompt for HTTP Authentication

### ISSUE THREAD

**Issue by multiwebinc** [keepassxreboot/keepassxc#1919]
## Expected Behavior

When visiting a website using HTTP authentication (i.e. it sends the `WWW-Authenticate` header) I would expect the username/password dialog to pop up. Either clicking on the keepassxc browser extension and selecting the appropriate entry or manually entering a username and password should allow me to log in.

## Current Behavior

When visiting a website in Firefox that is using HTTP authentication, a keepassxc alert pops up saying that multiple entries match (at least for me, where this is true), however the actual prompt for the username/password for manual entry is not displayed. The tab shows a "loading" icon and you have to click on the keepassxc icon in the browser to select the correct user (which, in my case, was hidden by the pop-up saying multiple entries matched). There is no way to manually enter in the username and password different from the entries in the KeepassXC database. I tested it on Chrome and it works as expected.

Operating system: Linux
CPU architecture: AMD64
Kernel: 4.15.0-20

**Comment by droidmonkey** [comment]
This should be filed under the browser extension repo [keepassxreboot/keepassxc-browser](/keepassxreboot/keepassxc-browser)
