### ISSUE TITLE
Trying to Enable Browser Intergration Cause App to Crash

### ISSUE THREAD

**Issue by WulftheNordicRanger** [keepassxreboot/keepassxc#1922]
When I try to enable browser integration the app crashes when I apply or ok the app crashes

 Expected Behavior
Browser integration is enabled 

Current Behavior
App crashes and browser integration is not enabled

 Steps to Reproduce 
1. Click box to enable browser integration
2. Click apply or ok

Debug Info
KeePassXC - Version 2.3.2
Revision: 2bb72eb

Libraries:
- Qt 5.5.1
- libgcrypt 1.8.1

Operating system: Linux Mint 18.3
CPU architecture: x86_64
Kernel: linux 4.13.0-36-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by varjolintu** [comment]
Found the issue. In the meantime you can edit `.config/keepassxc/keepassxc.ini` and change `Enabled` to true under `[Browser]`.

**Comment by WulftheNordicRanger** [comment]
Thanks

**Comment by phoerious** [comment]
You need to set it to false, not true.

**Comment by hughwilliams94** [comment]
Sorry I misunderstood the workaround I thought this would allow the use of the browser integration not just enable the app to open again, sorry. I  did not have the setting enabled initially but would like to be able to use it.

**Comment by phoerious** [comment]
You can use browser integration if you disable the use of a proxy (either in the settings or via UseCustomProxy=false). In that case, however, the browser will try to open a new KeePassXC instance.

**Comment by hughwilliams94** [comment]
I currently have UseCustomProxy set to false in keepass.ini but setting enabled to true still crashes KeepassXC

**Comment by phoerious** [comment]
Sorry, my bad. It's not the custom proxy option, but the option to use a proxy which you need to disable.

**Comment by hughwilliams94** [comment]
Hmmm, disabling that does help resolve the error but there now seems to be no communication between the extension and KeePassXC even if I point the custom proxy location at keepassxc-proxy.exe

**Comment by Syping** [comment]
I had enabled Browser Integration in the last version and my KeePassXC doesn't start at all after upgrade: ![Crash Result](https://i.imgur.com/EsUx2jz.png "Crash Result")
It says it have Memory Access Issue similar to the Screenshot above in English. After Downgrade to last version it works fine again. It might be a good idea to take down the Installer because the issue will affect a lot of people.

**Comment by hughwilliams94** [comment]
I've also downgraded in order to keep the browser integration

**Comment by phoerious** [comment]
@hughwilliams94 When you disable the proxy, your browser will start a new KeePassXC instance. That means that you need to quit any running instance and then click "Reload" in the browser.

**Comment by phoerious** [comment]
Setting SupportBrowserProxy=false should work around it. But downgrading for now is a solution, too.

**Comment by WulftheNordicRanger** [comment]
Updating to version 2.3.3 seems to have fixed it

**Comment by varjolintu** [comment]
@hughwilliams94 I will check it out.

**Comment by varjolintu** [comment]
@hughwilliams94 I installed 2.3.3 and uninstalled the old version as suggested. Everything worked. Then disabled all the browsers from the settings and disabled the whole browser integration. Restarted KeePassXC and enabled the browser support again (tried what the browser extension said before, and it was timeout, so no connection). Still worked.

If you do the same steps, does it help?

**Comment by hughwilliams94** [comment]
Yes these steps fixed it, I think I just tried too many different combinations. Win7 64 portable works with browser integration now. Thanks for your help and the speedy fix everybody!

**Comment by joserprieto** [comment]
I got the same error, but in a different action.

I have a Keepass db, and move groups one into others; the first, works; second, make KeePassXC crashes.

```bash
$ keepassxc
QObject::startTimer: Timers cannot have negative intervals
Violación de segmento
```
```bash
$ keepassxc -v
keepassxc 2.3.3

$ qmake -v
QMake version 3.0
Using Qt version 5.5.1 in /usr/lib/x86_64-linux-gnu

$ lsb_release --all
LSB Version:	core-9.20160110ubuntu0.2-amd64:core-9.20160110ubuntu0.2-noarch:security-9.20160110ubuntu0.2-amd64:security-9.20160110ubuntu0.2-noarch
Distributor ID:	LinuxMint
Description:	Linux Mint 18.1 Serena
Release:	18.1
Codename:	serena
```
~/.config/keepassxc/keepassxc.ini

```ini
[General]
AutoReloadOnChange=true
AutoSaveAfterEveryChange=false
AutoSaveOnExit=false
AutoTypeDelay=25
AutoTypeEntryTitleMatch=true
AutoTypeEntryURLMatch=true
AutoTypeStartDelay=500
BackupBeforeSave=false
GlobalAutoTypeKey=0
GlobalAutoTypeModifiers=0
IgnoreGroupExpansion=true
LastChallengeResponse=@Variant(\0\0\0\x1c\0\0\0\0)
LastDatabases=/home/joserprieto/documents/keys.kdbx
LastDir=/home/joserprieto/documents
LastKeyFiles=@Variant(\0\0\0\x1c\0\0\0\0)
MinimizeOnCopy=false
OpenPreviousDatabasesOnStartup=true
RememberLastDatabases=true
RememberLastKeyFiles=true
SSHAgent=false
ShowToolbar=true
SingleInstance=true
UseAtomicSaves=true
UseGroupIconOnEntryCreation=true

[Browser]
AlwaysAllowAccess=false
AlwaysAllowUpdate=false
BestMatchOnly=false
CustomProxyLocation=false
Enabled=false
MatchUrlScheme=true
SearchInAllDatabases=false
ShowNotification=true
SortByUsername=false
SupportBrowserProxy=true
SupportKphFields=true
UnlockDatabase=true
UpdateBinaryPath=false
UseCustomProxy=false

[GUI]
DarkTrayIcon=false
HideDetailsView=false
Language=system
MinimizeOnClose=false
MinimizeOnStartup=false
MinimizeToTray=false
ShowTrayIcon=false

[Http]
AlwaysAllowAccess=false
AlwaysAllowUpdate=false
BestMatchOnly=false
Enabled=false
MatchUrlScheme=true
Port=19455
SearchInAllDatabases=false
ShowNotification=true
SortByUsername=false
SupportKphFields=true
UnlockDatabase=true
generator\EASCII=false
generator\EnsureEvery=true
generator\ExcludeAlike=true
generator\Length=16
generator\LowerCase=true
generator\Numbers=true
generator\SpecialChars=false
generator\UpperCase=true

[generator]
EASCII=false
EnsureEvery=true
ExcludeAlike=true
Length=16
LowerCase=true
Numbers=true
SpecialChars=false
Type=0
UpperCase=true
WordCount=6
WordList=eff_large.wordlist
WordSeparator=" "

[security]
IconDownloadFallbackToGoogle=false
autotypeask=true
clearclipboard=true
clearclipboardtimeout=10
hidenotes=false
hidepassworddetails=true
lockdatabaseidle=false
lockdatabaseidlesec=240
lockdatabaseminimize=false
lockdatabasescreenlock=true
passwordscleartext=false
passwordsrepeat=false
relockautotype=false
```

**Comment by phoerious** [comment]
It's a crash, but the problem is a totally different one. Mint 18.1 is based on Ubuntu 16.04, which comes with Qt 5.5. Qt versions prior to 5.6 have a bug that causes an application to crash in the situation you described. Please upgrade your system to a newer version or use our AppImage instead. See #335.

**Comment by livier** [comment]
Same kind of error as  joserprieto

$ keepassxc
QObject::startTimer: Timers cannot have negative intervals


$ qmake -v
qmake: could not exec '/usr/lib/x86_64-linux-gnu/qt4/bin/qmake': No such file or directory

$ lsb_release --all
No LSB modules are available.
Distributor ID: neon
Description:    KDE neon User Edition 5.13
Release:        16.04
Codename:       xenial

~/.config/keepassxc/

[General]
AutoReloadOnChange=true
AutoSaveAfterEveryChange=true
AutoSaveOnExit=false
AutoTypeDelay=25
AutoTypeEntryTitleMatch=true
AutoTypeEntryURLMatch=true
AutoTypeStartDelay=500
BackupBeforeSave=false
GlobalAutoTypeKey=0
GlobalAutoTypeModifiers=0
IgnoreGroupExpansion=true
LastChallengeResponse=@Variant(\0\0\0\x1c\0\0\0\0)
LastDatabases=/home/blablabla/keepass_Xavier.kdbx
LastDir=/home/xavier
LastKeyFiles=@Variant(\0\0\0\x1c\0\0\0\0)
LastOpenedDatabases=/home/blablabla/keepass_Xavier.kdbx
MinimizeOnCopy=false
OpenPreviousDatabasesOnStartup=true
RememberLastDatabases=true
RememberLastKeyFiles=true
SSHAgent=false
ShowToolbar=true
SingleInstance=true
UseAtomicSaves=true
UseGroupIconOnEntryCreation=true

[Browser]
AlwaysAllowAccess=false
AlwaysAllowUpdate=false
BestMatchOnly=false
CustomProxyLocation=
Enabled=true
MatchUrlScheme=true
SearchInAllDatabases=false
ShowNotification=true
SortByUsername=false
SupportBrowserProxy=true
SupportKphFields=true
UnlockDatabase=true
UpdateBinaryPath=false
UseCustomProxy=false

[GUI]
DarkTrayIcon=true
DetailSplitterState=218, 240
EntryListColumnSizes=150, 150, 390
EntrySearchColumnSizes=@Invalid()
HideDetailsView=false
HidePasswords=true
HideUsernames=false
Language=system
ListViewState=@ByteArray(\0\0\0\xff\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\x1\x1\0\0\0\0\0\0\0\0\0\0\0\f\x1\0\0\0\0\x1\0\0\0\0\0\0\0\x64\0\0\x4\x94\0\0\0\f\x1\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x64\0\0\0\x18\0\0\0\x81\0\0\0\0\0\0\0\f\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\xf8\0\0\0\x1\0\0\0\0\0\0\0\x64\0\0\0\x1\0\0\0\0\0\0\0\x64\0\0\0\x1\0\0\0\0\0\0\0\x64\0\0\0\x1\0\0\0\0\0\0\0\x64\0\0\0\x1\0\0\0\0\0\0\0\x64\0\0\0\x1\0\0\0\0\0\0\0\x64\0\0\0\x1\0\0\0\0\0\0\0\x64\0\0\0\x1\0\0\0\0\0\0\0\x64\0\0\0\x1\0\0\0\0\0\0\0\x18\0\0\0\x1\0\0\0\x2\0\0\0\x64\0\0\0\x1\0\0\0\0\0\0\x3\xe8\x1\0\0\0\x64)
MainWindowGeometry=@ByteArray(\x1\xd9\xd0\xcb\0\x2\0\0\xff\xff\xff\xfc\0\0\0Z\0\0\x3\x1b\0\0\x2\xb1\0\0\0\0\0\0\0s\0\0\x3\x17\0\0\x2\xad\0\0\0\x1\0\0\0\0\x5\xa0)
MinimizeOnClose=true
MinimizeOnStartup=true
MinimizeToTray=true
SearchViewState=@ByteArray(\0\0\0\xff\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x5\x97\0\0\0\f\x1\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x64\0\0\0\x18\0\0\0\x81\0\0\0\0\0\0\0\f\0\0\0\xa2\0\0\0\x1\0\0\0\0\0\0\0\xa2\0\0\0\x1\0\0\0\0\0\0\0\x64\0\0\0\x1\0\0\0\0\0\0\0\x64\0\0\0\x1\0\0\0\0\0\0\x1\x1b\0\0\0\x1\0\0\0\0\0\0\0\x64\0\0\0\x1\0\0\0\0\0\0\0\x64\0\0\0\x1\0\0\0\0\0\0\0\x64\0\0\0\x1\0\0\0\0\0\0\0\x64\0\0\0\x1\0\0\0\0\0\0\0\x64\0\0\0\x1\0\0\0\0\0\0\0\x18\0\0\0\x1\0\0\0\x2\0\0\0\x64\0\0\0\x1\0\0\0\0\0\0\x3\xe8\x1\0\0\0\x64)
ShowTrayIcon=true
SplitterState=317, 881

[Http]
AlwaysAllowAccess=false
AlwaysAllowUpdate=false
BestMatchOnly=false
DeprecationNoticeShown=2
Enabled=false
MatchUrlScheme=true
Port=19455
SearchInAllDatabases=false
ShowNotification=true
SortByUsername=true
SupportKphFields=true
UnlockDatabase=true
generator\EASCII=false
generator\EnsureEvery=true
generator\ExcludeAlike=true
generator\Length=16
generator\LowerCase=true
generator\Numbers=true
generator\SpecialChars=false
generator\UpperCase=true

[generator]
EASCII=false
EnsureEvery=true
ExcludeAlike=true
Length=20
LowerCase=true
Numbers=true
SpecialChars=true
Type=0
UpperCase=true
WordCount=8
WordList=eff_large.wordlist
WordSeparator=" "

[security]
IconDownloadFallbackToGoogle=false
autotypeask=true
clearclipboard=true
clearclipboardtimeout=20
hidenotes=false
hidepassworddetails=true
lockdatabaseidle=false
lockdatabaseidlesec=300
lockdatabaseminimize=false
lockdatabasescreenlock=true
passwordscleartext=false
passwordsrepeat=false
relockautotype=false

**Comment by hughwilliams94** [comment]
@livier, see comment above from @phoerious.
