### ISSUE TITLE
Windows 10: keepassxc uses the wrong language

### ISSUE THREAD

**Issue by macau23** [keepassxreboot/keepassxc#1924]
I have keepassxc set to the default system language. The problem is, that in Windows this is perhaps not so simple.

There is a "Windows display language" set to English, and all my windows and prompts are in English. When I open the control panel, the labels are in English, when I open a menu in a system application the text is in English.

Then there are "Languages", of which you can enter as many as you like. They are sorted alphabetically. I have Deutsch and English.

Then there is a "Country or region" which is my country (this is hopefully irrelevant).

Then I have one or more keyboard settings (this is hopefully irrelevant).

## Expected Behavior
I expect keepassxc to use the "Windows display language", i.e. English.

## Current Behavior
It is using German, so I guess the Country or region setting, or the first option under the Language setting is being used.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Debug Info

KeePassXC - 2.3.2
Revision: REVISION

Libraries:
- LIBS

Operating system: Windows 10
CPU architecture: x86_64
Kernel: KERNEL

Enabled extensions:
- EXTENSIONS

**Comment by hifi** [comment]
We use `QLocale::system().name()` as the source for the system language which is documented as "Returns a QLocale object initialized to the system locale.".

One alternative would be to prefer the first item returned from `QLocale::uiLanguages()` but it may need converting to an actual locale which may not be trivial.

**Comment by macau23** [comment]
Do you want to lookup the system locale, or the preferred UI language? (isn't that `QLocale::uiLanguages()` ?)

**Comment by phoerious** [comment]
I would prefer the system locale. At least that makes the most sense to me. If Windows has a different setting for the display language, which is independent of the locale setting, I'm not really sure if it's our job to respect that. I'm not really sure what the locale setting is supposed to be for if not the language. Region, number format and currency settings are generally independent of that.

**Comment by macau23** [comment]
There is a system locale, a user locale, an input locale, and a display language.

**Comment by macau23** [comment]
> why you would want to have another language setting on top of that if you can already set a locale override.

Because I can't configure that.

In Windows 10, I can set my country or region, then the languages that I can understand. There is no order for the languages I can understand. Then I can set a display language, which I have set to English.

**Comment by phoerious** [comment]
So the problem appears to be that: you set a locale, which brings its defaults, and then you can configure a deviant language setting. My Linux system does it the other way round: I can configure a locale and then change region, number format, date and time settings. In the latter case, the locale is a good indicator for the language, in the former it's not.
I don't have a Windows system to test it right now, but I think you could also do it the other way round as an immediate fix of the issue.

**Comment by macau23** [comment]
I'm not sure I would say it's a problem, but that is the way it works :)

On my Linux box it makes more sense.

**Comment by droidmonkey** [comment]
Im not sure what the big deal is. Just change the language using the pull down in the settings menu.

**Comment by macau23** [comment]
There is no big deal. I was just reporting that by default, keepassxc displays in a different language to all my other applications.

**Comment by janlimpens** [comment]
Since the last version KeePassXC uses the language of the country I am in, not the language of my system's UI. It is the only application that acts this way and did not do so in the past. This started happening on macOs Mojave and still is the same in Catalina. KPXC 2.4.3.
I cannot find any setting to change this. Also, on Catalina, it usually is possible to set a specific application's language to something - this is not possible for KeePassXC.

**Comment by droidmonkey** [comment]
You can set your language from within the KeePassXC settings.

**Comment by janlimpens** [comment]
@droidmonkey , thanks, it really was there! Odd, though, that the picked "default" language is different from all other applications on the system. It seems the bug/feature is still there.
I did not find this setting, because with a trackpad active, macOS hides scrollbars by default and there is no indication, that you need to scroll downs the general section to find the setting. UI wise ought to be considered, IMHO.

**Comment by droidmonkey** [comment]
I can't speak for Mac's desire to hide scroll bars, but there language issue is corrected for the next release. There is a bug in Qt's implementation of the language choice when multiple languages are defined.
