### ISSUE TITLE
Add reveal button for protected attributes in preview pane

### ISSUE THREAD

**Issue by smrqdt** [keepassxreboot/keepassxc#1930]
Currently the details pane is pretty useless for accessing passwords and protected attributes. Meanwhile the only ways to access passwords are showing all passwords in the entry list (which risks revealing a lot of passwords if someone is watching) or opening the edit window where one could easily modify the entry by accident, also this needs some more clicks. To access protected attributes the edit window is actually the only way to reveal these.

A way to reveal a single password or protected attribute through the preview pane would be great. I’m thinking of a small button next to each protected element to reveal or unreveal its content.

I also could imagine that some other actions for each protected (or unprotected) field could be useful too: a way to copy the field without revealing (which is currently only possible for passwords) and a way to autotype just a single field with a specified delay. (If this is going too far for this Issue I can create a new one for that feature) 

Alternatively these could be context options for each field, but imho three small icon buttons next to each field would not hurt the interface.

**Comment by droidmonkey** [comment]
The reveal password button was added to 2.4.0, down scoping this issue to protected attributes.

**Comment by fade2gray** [comment]
> The reveal password button was added to 2.4.0, down scoping this issue to protected attributes.

I am using 2.4.1 but don't see any way to reveal protected attributes except when editing them.

Am I missing something?

<a href='https://photos.google.com/share/AF1QipP04pV1yqbg8EEkqnbbzGRZ5q38bRaxQsGDEVY-O7fPfLgamaHrU4KS0-lpMQ0dEw?key=MjVlWlNTRmR6aFMtSmpfeHBiSU9GWUkwTHpYQ1NR&source=ctrlq.org'><img src='https://lh3.googleusercontent.com/PGxfYYhAFoYKos4wOl1CGhY3ffd0bTyCK4m-v_33HL-0MAnMtTVyMP7hjzTmnudXORwmtFmcg28Iyo-OhmPXDHvhJTVTKCqu16hnO21dmfqbHJg5LFzEvSMtfdA-f96NDiPQx5aX-A=w2400' /></a>

**Comment by droidmonkey** [comment]
Not missing anything, it wasn't implemented yet.

**Comment by fade2gray** [comment]
Sorry, I inferred from "The reveal password button was added to 2.4.0" that it had already been implicated.

**Comment by DJCrashdummy** [comment]
i use the additional attributes to store some additional PINs, APIs etc.... and its driving me crazy that i always have to open the entry, choose the correct "tab", have to reveal the value and only then i can view/copy it.

because of this, other people at our company save PINs, APIs etc. within the notes-field which is a real **security issue** because this PINs, APIs etc. have serious permissions... :frowning_face: and beside that i can't use the PINs for an autotype-sequence (without reworking half the entry).

*the option to hide the notes in KeePassXC >=2.5 is interesting, but still doesn't solve this security issue because it is on the behalf of the user. ...and you guess right, none of them hides the notes by default.*

**Comment by droidmonkey** [comment]
There is absolutely no difference in security between notes and attributes m

**Comment by DJCrashdummy** [comment]
> There is absolutely no difference in security between notes and attributes [...]

regarding the encryption of course not, but from the UX point of view very well!

...and that's what i'm talking about: it's a big security issue, if a 4-digit-PIN for the corresponding app is readable for all people around as soon as someone clicks on the entry to e.g. just open the link.
so please add the possibility to reveal (and maybe even copy) protected attributes in the preview to help stopping the dangerous habit of storing secret/sensitive information at the notes.

i know there is no difference from the technical point of view, it is a handling/convenience thing!
hardly anyone with no deeper sense for security (which is sadly the vast majority of "normal" users), is willing to regularly take the "long route" to get a PIN out of a protected additional attribute.

**Comment by DJCrashdummy** [comment]
for now i'll try to get secret/sensitive information into additional attributes and just don't "protect" them as a workaround...
it isn't perfect and defeats the purpose of the "protected attributes", but at least they aren't revealed immediately. :expressionless:

**Comment by loeffelpan** [comment]
Will this be implemented in 2.7.0 or moved again?
I would really appreciate to have this feature.
