### ISSUE TITLE
Initial set up and build (Windows 10) - fatal error from windres.exe 

### ISSUE THREAD

**Issue by shaneknysh** [keepassxreboot/keepassxc#1934]
## Expected Behavior
make completes successfully

## Current Behavior
make throws fatal error

## Steps to Reproduce (for bugs)
1. I've gone through the initial setup as per - https://github.com/keepassxreboot/keepassxc/wiki/Set-up-Build-Environment-on-Windows
I originally tried to build without the YubiKey plugin but the instrsctions to add a compiler directive did not work.

2. I'm working through the build steps as per - https://github.com/keepassxreboot/keepassxc/wiki/Building-KeePassXC
3. On step `make -j8 package` I receive the error 
```
C:/Projects/open-source/keepassxc/share/windows/icon.rc:1:0: fatal error: when writing output to : Invalid argument
 IDI_ICON1    ICON    DISCARDABLE    "keepassxc.ico"

compilation terminated.
C:\tools\msys64\mingw64\bin\windres.exe: can't open file `loaded': No such file or directory
C:\tools\msys64\mingw64\bin\windres.exe: preprocessing failed.
make[2]: *** [src/CMakeFiles/KeePassXC.dir/build.make:76: src/CMakeFiles/KeePassXC.dir/__/share/windows/icon.rc.obj] Error 1
make[1]: *** [CMakeFiles/Makefile2:185: src/CMakeFiles/KeePassXC.dir/all] Error 2
```
complete gist of make output here - https://gist.github.com/shaneknysh/d8bacf960ade9f7e624719e9a0247d11

## Debug Info

KeePassXC - VERSION
Revision: REVISION

Libraries:
- libyubikey
- libykpers

Operating system: Windows 10
CPU architecture: x64
Kernel: KERNEL

Enabled extensions:
- all

**Comment by droidmonkey** [comment]
I've never seen that before. What happens if you use ```mingw32-make``` instead?

**Comment by shaneknysh** [comment]
If I back up to the step to setup libykpers the library is setup without error but then when I try the build
```
cmake -DWITH_XC_ALL=ON -DCMAKE_BUILD_TYPE=Release ..
```
I get
```
bash: cmake: command not found
```

None of the 32 bit tools where installed based on the 
```
pacman -S mingw-w64-$(uname -m)-qt5 \
    mingw-w64-$(uname -m)-libgcrypt mingw-w64-$(uname -m)-zlib \
    mingw-w64-$(uname -m)-argon2 mingw-w64-$(uname -m)-libsodium
```

**Comment by shaneknysh** [comment]
If I try 
```
mingw32-make -j8 package
```
I get 
```
bash: mingw32-make: command not found
```

**Comment by droidmonkey** [comment]
I do recommend using the release tool to build (skip down a section). This seems like a tooling issue though, I dont think your MSYS environment is valid.

**Comment by shaneknysh** [comment]
I will give that a try and report my results.

**Comment by droidmonkey** [comment]
any update?

**Comment by shaneknysh** [comment]
I will be trying again late tonight or tomorrow.

**Comment by shaneknysh** [comment]
Still no luck. 

```
HEAD is now at 0a155d89 Release 2.3.3
[ INFO ] Creating output directory...
[ INFO ] Creating source tarball...
xz: /c/Projects/open-source/keepassxc/release/keepassxc-2.3.3-src.tar.xz: File exists
[ INFO ] Cleaning existing build directory...
[ INFO ] Creating build directory...
[ INFO ] Configuring sources...
[ INFO ] Configuring build...
./release-tool: line 676: cmake: command not found
[ INFO ] Compiling and packaging sources...
./release-tool: line 680: mingw32-make: command not found
./release-tool: line 684: cpack: command not found
mv: cannot stat './KeePassXC-*.*': No such file or directory
[ INFO ] Checking out original branch...
[ INFO ] Leaving source directory...
[ INFO ] All done!
```

Same results for msys mingw64 or mingw32.

**Comment by shaneknysh** [comment]
Got it working!

I had to do some extra steps and skip some steps. I will update the steps I took tomorrow.

**Comment by phoerious** [comment]
mingw32-make is is provided by a separate package. cpack should come with cmake, however.

**Comment by shaneknysh** [comment]
I can submit updates to the build page wiki but here are the additional steps and missed steps I used to get my environment running. I'm not certain it would be paticularly useful as this seems to be an edge case specific to something in my environment. 

My notes in **_bold italic_**

### Install the build environment

* Download MSYS2 64bit: http://msys2.github.io/ <br/>Do not follow the install procedures, just install
* Start MSYS2 shell
* Update the system packages: `pacman --needed -Sy bash pacman pacman-mirrors msys2-runtime`<br/>You may see a conflict with catgets and libcatgets - if you do select 'y' to remove catgets and libcatgets.
* Restart MSYS2 shell
* Update all packages: `pacman -Syu` <br/>If tells you to close the shell, close and reupdate the package (until you are done)

### Install the C++ toolchain

This command will install the MinGW-W GCC compiler, CMake and Binutils

Open an MSYS2 shell:
**_don't use the line continuation_**
```
pacman -S git make mingw-w64-$(uname -m)-gcc mingw-w64-$(uname -m)-binutils mingw-w64-$(uname -m)-cmake
```

### Install the required dependencies

This command will install `qt5` `libgcrypt` and `zlib`

Open an MSYS2 shell:
**_don't use the line continuation_**
```
pacman -S mingw-w64-$(uname -m)-qt5 mingw-w64-$(uname -m)-libgcrypt mingw-w64-$(uname -m)-zlib mingw-w64-$(uname -m)-argon2 mingw-w64-$(uname -m)-libsodium
```
**_weird step I don't understand_**
Close the MSYS2 shell and open a new MSYS shell and run the command again. The second time the command will take considerably longer. I do not see any error message in the first run but the output is truncated after zlib is installed.
**_I also tried to run_**
```
pacman -S mingw-w64-$(uname -m)-qt5 mingw-w64-$(uname -m)-libgcrypt mingw-w64-$(uname -m)-zlib
```
**_and then_**
```
pacman -S mingw-w64-$(uname -m)-argon2 mingw-w64-$(uname -m)-libsodium
```
**_but I stil had to run both commands twice. This makes zero sense to me. I can not find what  in my environment is causing the install to fail the first time and what running it the second time does to correct this error. If I get more time I may start again from scratch and run each install package one at a time. Or try them in a different order._**

**_additional step. I thought this was the solution but without running the dependancies install twice this does not fix my environment by itself._**
Run this command to install make manually
```
pacman -S mingw-w64-$(uname -m)-make
```

#### Compile libyubikey
Run these commands in order to build libyubikey:
**_added install tar_**
```
pacman -S tar
wget https://developers.yubico.com/yubico-c/Releases/libyubikey-1.13.tar.gz
tar xf libyubikey-*.tar.gz
cd libyubikey-*
./configure
make -j8
make install
```

I still see 1 error when building - 
```
./release-tool: line 684: /mingw64/bin/cpack: Permission denied
mv: cannot stat './KeePassXC-*.*': No such file or directory
```
but I believe this is my Avast scanning cpack.exe long enough for the command to fail.
 
Finally, I think thus issue can be closed - I just have zero idea how to document 
a) what is the root cause and 
2) what is the 'correct' solution.
