### ISSUE TITLE
KeePassXC-Browser is "causing Firefox to slow down" message

### ISSUE THREAD

**Issue by jcosentino** [keepassxreboot/keepassxc#1939]
I am logged onto Facebook and Twitter, and as the feeds grow, I get a message that KeePassXC-Browser is "causing Firefox to slow down." This causes a problem because these pages do lock up constantly since the new updates.

KeePassXC - 2.3.3
Revision: 0a155d8
KeePassXC-Browser - 1.1.2

Libraries:
    Qt 5.10.1
    libgcrypt 1.8.2

Operating system: Windows 10 (1803)
CPU architecture: x86_64
Kernel: winnt 10.0.17134

Enabled extensions:
    KeePassXC-Browser
    (disabled the others)

Screenshot:
https://i.imgur.com/WbS0oiu.png

Sites where I've noticed this:
Facebook, Twitter

**Comment by droidmonkey** [comment]
Disable the plugin, there are significant issues with the current version. This is already reported in [keepassxc-browser#146](https://github.com/keepassxreboot/keepassxc-browser/issues/146)

**Comment by phoerious** [comment]
A fixed version has been released.

**Comment by pchampin** [comment]
Starting today (I think), the same problem occurred to me. I'm using version 1.6.4 (15-06-2020) of the extension.

Note that the problem exists even when KeePassXC is not running, so this seems to be the extension itself.
