### ISSUE TITLE
keypassxc proxy/extension possibly causing crashes

### ISSUE THREAD

**Issue by Savassan611** [keepassxreboot/keepassxc#1941]
## Current Behavior
so i have been using keepass for a couple months, working great. But something happened last night and im not sure what.

I started playing games today like usual and kept getting crashes. I figured out it was a memory error, but i have 16gigs so i was confused. I used the HP Omen to realize im using 5gigs idle on load and it slowly climbs to 16gigs then my computer crashes.

Thats when i realized- I have hundreds if not thousands of keepassxc-proxy.exe (https://gyazo.com/4a5f744ebc11c2ae17a8e41afe340ca3) and hundreds of Console Window Host running in the background and it just kept replicating itself. its now happening on both my computers. I uninstalled keepassxc from my desktop (where i discovered the issue) and i dropped to 5gigs idle but then continued to cimb but slower (I system restored my computer) I only have a couple programs shared between both desktop and laptop. Now im on my laptop and i see i also have the same issue. But this time i kept the basic program and just uninstalled the extension. I no longer am getting hundreds of both programs in the background. I contacted HP support and they said it was something with google or an extension. So im thinking it might be an issue with the extension. Tho why it started happening today after using it for a couple months im not sure.

## Possible Solution
On my desktop i had both program and extension installed. Constant duplication.

On my laptop i had both installed but i didnt have the extension synced. No duplication, but the moment i synced the extension with the program, my memory started to fill up.

Operating system:  Windows 10

Enabled extensions:
- EXTENSIONS

forget the name of it- it was the extension linked in keepasssc reddit subthread.

**Comment by varjolintu** [comment]
Duplicate issue https://github.com/keepassxreboot/keepassxc/issues/1765. New release of the extension is coming soon.
