### ISSUE TITLE
vivaldi addon doesnt connect to database

### ISSUE THREAD

**Issue by pickausername1111** [keepassxreboot/keepassxc#1943]
vivaldi addon doesnt connect to database

## Expected Behavior
I wanted to connect the extension Keepassxc browser with the program Keepassxc, but does not appear (as described in the FAQ) a window in which you can specify the path
Bowser vivaldi as a standalone installaton
Keepass XC installed as a portable version
Integration for this browser has been activated

## Current Behavior
no connection between Keepassxc and the extension possible

## Possible Solution
extension does not work on a standalone installation

## Steps to Reproduce (for bugs)
reproducible at any time

## Context
save my passwords in Keepass

## Debug Info
KeePassXC - Version 2.3.1
Revision: 2fcaeea

Bibliotheken:
- Qt 5.10.1
- libgcrypt 1.8.2

Betriebssystem: Windows 7 SP 1 (6.1)
CPU-Architektur: x86_64
Kernel: winnt 6.1.7601

Aktivierte Erweiterungen:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

Enabled extensions:
KeePassXC-Browser Version: 1.1.2
KeePassXC Version: unknown

**Comment by varjolintu** [comment]
Enable Chrome/Chromium from KeePassXC settings and try again. For some reason Vivaldi has changed to use those settings instead.

**Comment by Dracooooo** [comment]
Same issue on windows 10 with keepassxc 2.3.1. It works fine with Firefox though.

KeePassXC-Browser Version: 1.1.3

KeePassXC Version: unknown

**Comment by KingHawkk** [comment]
I had the exact same issue and was looking for a solution when I found this ticket. Doing what varjolintu said solved the issue for me.

Standalone KeePassXC 2.3.3
Standalone Vivaldi 1.15.1147.36 
KeePassXC-Browser 1.1.3
