### ISSUE TITLE
KeepassXC-proxy.exe loads way too many copies

### ISSUE THREAD

**Issue by gameguy95** [keepassxreboot/keepassxc#1944]
I looked in task manager and KeepassXC-proxy.exe loads what appears to easily be over 80 processes

## Expected Behavior
One or two instances of KeepassXC-proxy.exe should probably be enough, right?

## Current Behavior
Task manager is filled with dozens of instances of KeepassXC-proxy.exe, as the picture below should show, which continues to grow even after killing all of them. The only way I was able to stop it from growing was to rename the KeepassXC-proxy.exe file to KeepassXC-proxy.exe.bak and then run `taskkill /IM keepassxc* /F` on the windows command line. 
![image](https://user-images.githubusercontent.com/15315644/39911650-00d7ee44-54b1-11e8-8cb9-d9749373802c.png)

## Steps to Reproduce (for bugs)
I don't recall having this problem before this morning, when I installed the latest release version and replaced KeepassHttpConnector with the new official KeepassXC-Browser addon. 

## Debug Info
KeePassXC - Version 2.3.3
Revision: 0a155d8

Libraries:
- Qt 5.10.1
- libgcrypt 1.8.2

Operating system: Windows 10 (10.0)
CPU architecture: x86_64
Kernel: winnt 10.0.16299

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by phoerious** [comment]
Duplicate of #1765
