### ISSUE TITLE
Kill running KeePassXC instance via Windows installer

### ISSUE THREAD

**Issue by phoerious** [keepassxreboot/keepassxc#1945]
## Expected Behavior

The Windows installer should either kill a running instance of KeePassXC or ask the user to do it before continuing with the installation. 

## Current Behavior

The installer kills the proxy, but not the main program. IIRC, we have a taskkill command for that in the installer config, but it's not working. On the contrary, it seems that it may sometimes cause KeePassXC to hang in the background causing the installer to fail without any apparent reason. I haven't had that myself (for me it just doesn't work), but I got a repeated report of that behavior.

## Possible Solution

Maybe kill it with /f or use the KillProc or NsProcess NSIS plugins.

**Comment by droidmonkey** [comment]
I want to ditch the nsis installer entirely in 2.4. we should fix this in wix

**Comment by droidmonkey** [comment]
This is implemented in the WiX installer.
