### ISSUE TITLE
MacOS High Sierra: SSH Agent connection failed 

### ISSUE THREAD

**Issue by drew-kun** [keepassxreboot/keepassxc#1946]
Getting following message while unlocking (and locking) database: 'Agent connection failed'

## Expected Behavior

To make keepassxc pass my ssh keys to macos' ssh-agent

## Current Behavior

Seeing the 'Agent connection failed' Warning message (see screenshot below)

## Steps to Reproduce (for bugs)

I have done the following:

1. Added SSH-key entry
![db_ssh_key](https://user-images.githubusercontent.com/10493450/39945326-efb50296-551e-11e8-9be3-5e16f6d2f5c7.png)

2. Enabled SSH-agent in Properties
![db_ssh-a](https://user-images.githubusercontent.com/10493450/39945334-f5d6a846-551e-11e8-8c49-444a54c0a6be.png)

3. Restarted KeepassXC
4. Unlocked db
5. Got the following error/warning:
![untitled copy](https://user-images.githubusercontent.com/10493450/39944760-aed57172-551c-11e8-8111-8ab02977f7e9.png)

## Context

Trying to use KeepassXC(which stores my ssh-keys) to pass keys to Mac's SSH-Agent.

## Debug Info

KeePassXC - Version 2.3.1
Revision: 2fcaeea

Libraries:
- Qt 5.9.3
- libgcrypt 1.8.2

Operating system: macOS High Sierra (10.13)
CPU architecture: x86_64
Kernel: darwin 17.5.0

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by hifi** [comment]
Does `ssh-agent -l` work in the Terminal app? What's the output of `env | fgrep SSH_AUTH_SOCK`?

**Comment by hifi** [comment]
After you get that sorted out (`ssh-add -l` doesn't complain) KeePassXC should work just fine as well. I'm not familiar with MacOS so I can't help you with that, sorry.

From what I had been testing it "just worked" with OS X before without any fiddling.

**Comment by drew-kun** [comment]
Yeah... I've read the [KeepassXC documentation](https://keepassxc.org/docs/#faq-ssh-agent-how) and it doesn't say anything about that.. what is says is: ` On macOS, ssh-agent is running by default and no further setup is required. ` That's why I've opened this issue...

**Comment by drew-kun** [comment]
Btw, do I understand this correctly: once it works, I can remove all my keys from `~/.ssh` so they only live in my kepassxc database and only available through the ssh-agent while database is opened? Is it correct?

**Comment by hifi** [comment]
Yes, it works exactly like that if you enable the options for the entries that they are added on unlock and removed on lock.

The agent should work out-of-box. It's possible Apple changed something with the High Sierra update or that there's something odd with your install of it. Testing with `ssh-add` is the best way to ensure the agent is actually working first.

**Comment by drew-kun** [comment]
I also see that keepassxc provides the option to set the ssh key as `External file` instead of `Attachment`... for example like this:
![untitled](https://user-images.githubusercontent.com/10493450/39962259-1dda1db6-55fe-11e8-8810-7780e4df381c.png)

What's the point of it then? What would be the use case example?

**Comment by hifi** [comment]
You can have a passphrase protected key that only has the passphrase stored in your KeePassXC database in the password field of the entry. KeePassXC will then decrypt a key first when reading it from your disk when adding it to an agent.

It may provide additional security as in the case of a database compromise you would also need to obtain the key files to gain access to systems.

**Comment by drew-kun** [comment]
I do not understand what exactly should be sorted out here.. What `ssh-agent -l` is supposed to show? man pages for `ssh-agent` says that it doesn't even have `-l` argument... Although if I run:
```
$ ssh-add -l
The agent has no identities.
```

If I manually do: 
```
$ ssh-add id_rsa
Enter passphrase for id_rsa:
Identity added: id_rsa (id_rsa)
Certificate added: id_rsa-cert.pub (mydomain.local-user)

ssh-add -l
4096 SHA256:NWNiMsn34Ga4K/cLgV0x354V6B6P8+oat6etwFVifl4 id_rsa (RSA)
4096 SHA256:NWNiMsn34Ga4K/cLgV0x354V6B6P8+oat6etwFVifl4 id_rsa (RSA-CERT)
```
But keepassxc still says: `Agent connection failed`

**Comment by hifi** [comment]
What I meant by that is to check that the agent is actually running and working.

It should be running without manually starting it when you boot your system. If you can just open up the Terminal app and `ssh-add -l` shows "The agent has no identities." then it should also work with KeePassXC. If you had to manually start it then it isn't properly configured.

If the agent *is* running and working immediately after booting up in Terminal and KeePassXC says "Agent connection failed" then there may be an issue with High Sierra but then it'd be nice to confirm it with another High Sierra system if it's specific to your install or not.

**Comment by drew-kun** [comment]
Oh I see... It appears to me that the agent is running on boot as expected, but the KeePassXC says "Agent connection failed"... Just checked on another mac - same issue. Can It be somehow related to the fact that ssh-agent on mac is different. For example to make keys being added to ssh-agent on mac I need some MacOS-only statements in `~/.ssh/config`:
```
Host *
        UseKeychain yes
        AddKeysToAgent yes
```
Otherwise the keys are not added to agent even though it's automatically running on boot.
These statements do not exist on Linux.

**Comment by weslly** [comment]
I'm using both High Sierra and kpxc ssh agent but never had this issue. It could be because I still haven't upgraded to 10.13.4, but I doubt it.

**Comment by drew-kun** [comment]
@yan12125, tried to run `/Applications/KeePassXC.app/Contents/MacOS/keepassxc`. Same thing(((

**Comment by drew-kun** [comment]
Well, after outage last night all my machines were rebooted and now work as expected on both mac machines... It's strange, but seems like for Mac restart of the KeepassXC application is not enough and the system reboot is required in order to make ssh-agent connection work. Please correct me if I am wrong.

**Comment by drew-kun** [comment]
Well now KeepassXC adds keys to ssh-agent. Although there is still an issue.

Database locked:
```
$ ssh-add -l
$
```
Database unlocked:
```
$ ssh-add -l
4096 SHA256:OLw0swsx2/CQeq3PjfoR3UdCK0RwL52t7frV1WyX7fk  (RSA)
...
$ 
```
All good so far... Now I try to `git push` some changes to test repo and getting ssh-agent error:
```
$ git push                                       
sign_and_send_pubkey: signing failed: agent refused operation
no such identity: /Users/drew/.ssh/id_ed25519: No such file or directory
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
$
```
But when I manually add the key all works:
```
$ ssh-add ~/.ssh/id_rsa-github
Enter passphrase for /Users/drew/.ssh/id_rsa-github:
Identity added: /Users/drew/.ssh/id_rsa-github (/Users/drew/.ssh/id_rsa-github)

$ ssh-add -l
4096 SHA256:OLw0swsx2/CQeq3PjfoR3UdCK0RwL52t7frV1WyX7fk /Users/me/.ssh/id_rsa (RSA)
...
$  git push
Counting objects: 4, done.
Delta compression using up to 12 threads.
Compressing objects: 100% (4/4), done.
Writing objects: 100% (4/4), 971 bytes | 971.00 KiB/s, done.
Total 4 (delta 2), reused 0 (delta 0)
remote: Resolving deltas: 100% (2/2), completed with 2 local objects.
To github.com:drew-kun/gpgbackup.git
   9b9f75a..d308885  master -> master
```
What is the difference? What am I doing wrong?

**Comment by drew-kun** [comment]
Well, I think I have fixed it installing [ssh-askpass](https://github.com/theseal/ssh-askpass).

My fault - I just thought this is optional. [Documentation](https://keepassxc.org/docs/#faq-ssh-agent-openssh) says:

```
If you are using confirm-on-use option for your keys, ssh-agent needs to have a "ssh-askpass" program available.
```

Will leave it here just in case anyone as inattentive as me run into the same issue.

If getting the following error:
```
sign_and_send_pubkey: signing failed: agent refused operation
...
git@github.com: Permission denied (publickey).
```

Do on MacOS:
```
$ brew tap theseal/ssh-askpass
$ brew install ssh-askpass
$ brew services start ssh-askpass
$ sudo reboot
```

**Comment by killerdejavu** [comment]
> Oh I see... It appears to me that the agent is running on boot as expected, but the KeePassXC says "Agent connection failed"... Just checked on another mac - same issue. Can It be somehow related to the fact that the connection to ssh-agent on mac is different. For example to make keys being added to agent on mac I need some MacOS-only statements in `~/.ssh/config`:
> 
> ```
> Host *
>         UseKeychain yes
>         AddKeysToAgent yes
> ```
> Otherwise the keys are not added to ssh-agent even though it's automatically running on boot.
> These statements do not exist on Linux.

@drew-kun  You saved my day!
