### ISSUE TITLE
First click on tray icon after boot does not restore the window

### ISSUE THREAD

**Issue by Frederick888** [keepassxreboot/keepassxc#1947]
If I turn on "Minimise window at application startup", the first click on the tray icon opens the main window but it's minimised to task bar.

## Expected Behavior

Clicking the tray icon always restores the window and brings it to the front.

## Current Behavior

The main window is minimised to task bar after the first click. Clicks from the second time work normally.

## Steps to Reproduce (for bugs)

1. Turn on "Minimise window at application startup"
2. Reboot or re-login
3. Click tray icon

## Debug Info

KeePassXC - Version 2.3.3
Revision: 0a155d8

Libraries:
- Qt 5.10.1
- libgcrypt 1.8.2

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 4.16.8-1-ARCH

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

Desktop:
- Plasma 5.12.5

PS: This is different from #1595.

**Comment by shartrec** [comment]
I'm using Linux(Fedora 30)/Gnome/Wayland and had this behaviour in Fedora 28, but it has steadily got worse. In Fedora 30, I don't get an Icon in after minimising and can only reopen KeepassXc from terminal by invoking from command line, sometimes need to do this twice. Running application by clicking icon in Gnome Shell no longer reopens window (it did a while back).

Workaround is not to minimise to an icon.

**Comment by droidmonkey** [comment]
I think I fixed this with #3112
