### ISSUE TITLE
Autoremove custom favicons not used by any entries

### ISSUE THREAD

**Issue by ghost** [keepassxreboot/keepassxc#1950]
It would be great to have a tool in the database settings that will autoremove all the custom favicons not being used by any existing entries.

## Expected Behavior
In database settings: have a setting that allows you to autoremove all custom favicons that aren't being used by any current entries. A button that when clicked, prompts you with "This will purge/autoremove all custom favicons not used by existing entries. Are you sure you want to do this?" to which the use can select yes or no. 

## Current Behavior
You have to delete custom favicons one by one, using the view/edit entry function.

**Comment by droidmonkey** [comment]
Duplicate of #2110
