### ISSUE TITLE
SSH Agent integration does not work with snap build

### ISSUE THREAD

**Issue by hifi** [keepassxreboot/keepassxc#1951]
Agent socket can be read from the environment but access to it is currently denied by AppArmor. Both real ssh-agent socket and GNOME Keyring socket are blocked.

```
= AppArmor =
Time: May 13 11:19:36
Log: apparmor="DENIED" operation="connect" profile="snap.keepassxc.keepassxc" name="/run/user/1000/keyring/ssh" pid=433 comm="keepassxc" requested_mask="wr" denied_mask="wr" fsuid=1000 ouid=1000
File: /run/user/1000/keyring/ssh (write)
Suggestions:
* adjust program to use $SNAP_DATA
* adjust program to use run/shm/snap.$SNAP_NAME.*
```
There may be a flag for `snapcraft.yaml` that loosens the sandbox enough but I can't currently get a working build going of the snap on my system.

**Comment by hifi** [comment]
Anyone who may find this and just wants it to work. You can manually disable the snap sandbox completely by installing KeePassXC like this:

`sudo snap install --classic keepassxc`

This would make it behave more like any other application installed from the distribution packages. Caveat emptor.

There's an upstream thread discussing a plug for ssh-agent but it doesn't look good: https://forum.snapcraft.io/t/ssh-agent-plug-request/1250

**Comment by sysbes** [comment]
> Anyone who may find this and just wants it to work. You can manually disable the snap sandbox completely by installing KeePassXC like this:
> 
> `sudo snap install --classic keepassxc`
> 
> This would make it behave more like any other application installed from the distribution packages. Caveat emptor.
> 
> There's an upstream thread discussing a plug for ssh-agent but it doesn't look good: https://forum.snapcraft.io/t/ssh-agent-plug-request/1250

Does't work on Ubuntu 18.10

**Comment by hifi** [comment]
Indeed, that does not seem to work anymore even on 18.04, I get this warning during install:

```
Warning: flag --classic ignored for strictly confined snap keepassxc
```

However, the snap can be put into development mode which has the same effect:

```
sudo snap install --devmode keepassxc
```

You need to first remove the snap to be able to reinstall it. Tested the agent integration works on 18.04 again with that.

**Comment by droidmonkey** [comment]
Oops I missed this one, need to do a program-wide search for places we try to use temporary folders and such and fix them for snaps.

SNAP_COMMON = /home/[user]/snap/[snapname]/common/
SNAP_DATA = /home/[user]/snap/[snapname]/current/

**Comment by rwese** [comment]
## fixing the apparmor profile

I ran into the same issue, but since I am new to apparmor and snap I am unsure if this hack is proper.

In File: `/var/lib/snapd/apparmor/profiles/snap.keepassxc.keepassxc`
I added: `owner /run/user/[0-9]*/keyring/ssh   rw,` 

Now it looks like this:
```
<snip>
profile "snap.keepassxc.keepassxc" (attach_disconnected,mediate_deleted) {
  #include <abstractions/base>
  #include <abstractions/consoles>
  #include <abstractions/openssl>

    owner /run/user/[0-9]*/keyring/ssh   rw,  # <<<<<<<<<<<<<<<<<
<snip>
```
after a `sudo service apparmor reload` it works.

I hope that helps, if I can do more please let me know.

**Comment by droidmonkey** [comment]
That change probably won't survive a snap update.

**Comment by rwese** [comment]
@droidmonkey I thought as much and still reading up on snap & apparmor.

**Comment by hifi** [comment]
I noticed the snap build does not work with ssh-agent socket in the standard path of `$TMPDIR/ssh-XXXXXXXXXX/agent.<ppid>` regardless of the sandbox settings.

This happens because snaps have a namespaced `/tmp` that is unique for every running snap application and appears empty for KeePassXC.

So if you want to use the snap build of KeePassXC, make sure your ssh-agent socket path is some path visible inside the snap like in `/run/user` and you have instealled with `--devmode`. This is the default behavior of ssh-agent started by GNOME Keyring.

Any snap users who want this to work out-of-box without `--devmode` and a custom socket path need to raise their concern with upstream snap developers to add ssh-agent plug for snap.

**Comment by droidmonkey** [comment]
We are not going to expend time to fix this, use the flatpak verison.
