### ISSUE TITLE
Auto-type leads to unexpected/inconvenient position in alt-tab window switcher

### ISSUE THREAD

**Issue by tomellor** [keepassxreboot/keepassxc#1953]
Frequently I find the need to go back to KeepassXC immediately or shortly after using auto-type. The current behavior of positioning to the end of the window list in the window switcher is inconvenient for this need and I think quite unexpected. Worth noting the Keepass project [dealt with this](https://sourceforge.net/p/keepass/feature-requests/1258/) long back

## Expected Behavior
Use auto-type, then press alt-tab and KeepassXC is **next** window.

## Current Behavior
Use auto-type, then press alt-tab and KeepassXC is **last** window.

## Possible Solution
Configuration option under Settings->General-Auto-type, radio button for position KeepassXC next or last in window quick switching. I can see why people would want it to "get out of the way" so I don't know what the default should be.

**Comment by phoerious** [comment]
I would suppose Windows. I think, this qualifies for "wishlist".

**Comment by tomellor** [comment]
This has been happening for me on at least Fedora 26/27 and Windows 10. Do you guys not experience this?

In reviewing this on my Windows 10 machine I realized I have the "hide to tray when minimized" option enabled, I'm not sure what the default is for these options but I'm assuming that's it because I haven't really gone into settings much. Correct me if I'm wrong. I tried to reinstall but that doesn't appear to reset options and I don't see a factory reset option for the config.

Anyway, if minimize to tray is enabled then in Windows 10 KeepassXC disappears off the alt-tab list completely which I guess makes sense and I can see being a Windows-ism more than a Qt thing. I turned that option off and switched on "hide to tray instead of app exit". Now on auto-type KeepassXC is preserved as the next item in the alt-tab list and it's still nice to drop the thing to tray instead of taking up taskbar space.

So hey maybe this isn't an issue after all, though I might argue that if the minimize to tray option is default then maybe it shouldn't be because that UX is pretty bad if you need to rapidly sign into several sites without browser integration. More of a papercut than a wishlist to me. Not sure about Fedora and GNOME but I'll review that tonight.

**Comment by phoerious** [comment]
Minimize to tray is off by default. I see how this behaviour may be inconvenient, but it's not a bug and for sure not one with high priority. I haven't even noticed it myself.
