### ISSUE TITLE
Prompt boxes activate the main window in macOS

### ISSUE THREAD

**Issue by Frederick888** [keepassxreboot/keepassxc#1954]
Clicking on a prompt box, e.g. one that confirms a password update, restores the main window in macOS. This issue does not influence KDE Plasma.
## Expected Behavior

Users should be able to directly click the Yes/No button.
## Current Behavior

Currently a second click is needed as the first click only restores the main window.
## Steps to Reproduce (for bugs)

1. Launch browser and enter a new password for any saved credentials
2. Click "Update" in browser
3. Click anywhere of the prompt box from KeePassXC

## Context

It requires a second click on the prompt boxes to accept/reject a change, which is inconsistent with the behaviour under Linux (KDE Plasma) and troublesome.
## Debug Info

KeePassXC - Version 2.3.3
Revision: 0a155d8

Libraries:
- Qt 5.9.3
- libgcrypt 1.8.2

Operating system: macOS High Sierra (10.13)
CPU architecture: x86_64
Kernel: darwin 17.5.0

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by varjolintu** [comment]
When #1904 is merged we can use the same native raise method for popup dialogs. Meanwhile there's no workaround for this.
