### ISSUE TITLE
Problems connecting with KeepassXC Browser

### ISSUE THREAD

**Issue by yorodm** [keepassxreboot/keepassxc#1956]
After upgrading from 2.3.0 to 2.3.3 browser integration with Firefox is not working anymore

KeePassXC - 2.3.3
Revision: REVISION

Operating system: Windows
CPU architecture: 64 bits

**Comment by varjolintu** [comment]
Duplicate issue https://github.com/keepassxreboot/keepassxc/issues/1559.

You can try to disable and enable the support for your browser and see if it helps. It not, please write to the linked issue thread.
