### ISSUE TITLE
Crashes several times a day while minimized (Windows 10)

### ISSUE THREAD

**Issue by jkraemer** [keepassxreboot/keepassxc#1959]
## Expected Behavior

It shouldn't crash :)

## Current Behavior

I'm using this since a couple days now and unfortunately 3 or 4 times a day the program crashes with an error like this while it is minimized to the tray:

![keepassxc_crash](https://user-images.githubusercontent.com/19400/40091211-f7248c18-58e8-11e8-9e21-f10884a05c46.PNG)

Always happens when I wasn't actually using it (despite the window being titled AutoType it happens not the moment I do AutoType). Happy to provide more information. Is there any logfile / command line switch to generate one so one might get an idea what it's doing when it crashes?

## Debug Info
KeePassXC - 2.3.1
Revision: 2fcaeea

Libraries:
- Qt 5.10.1
- libgcrypt 1.8.2

Operating system: Windows 10 (10.0)
CPU architecture: x86_64
Kernel: winnt 10.0.17134

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by phoerious** [comment]
This is indeed a duplicate of #1561 and fixed in 2.3.2.
