### ISSUE TITLE
Windows - keepassxc ssh agent - "Agent connection failed" when adding key.

### ISSUE THREAD

**Issue by madhartigan** [keepassxreboot/keepassxc#1962]
## Expected Behavior
When clicking the "Add to agent" button, the key should be added to the currently running pageant.exe

## Current Behavior
Add to agent function fails to connect to pageant.exe

## Steps to Reproduce (for bugs)

1.  Start Pageant.exe
2. Start Keepassxc, create new entry and add ed25519 key to database as an attachment.
3. Click "Add to agent button"
4.

## Context
Attempting to enable auto-login functionality provided by pageant to kitty.exe

## Debug Info
KeePassXC - Version 2.3.3
Revision: 0a155d8

Libraries:
- Qt 5.10.1
- libgcrypt 1.8.2

Operating system: Windows 10 (10.0)
CPU architecture: x86_64
Kernel: winnt 10.0.17134

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey
![kpxc-agent failed](https://user-images.githubusercontent.com/320639/40098916-ccf42396-58ab-11e8-9e1a-4b0d8c4cf9a9.PNG)

**Comment by hifi** [comment]
Can you please check your Pageant version? Do RSA keys work?

**Comment by madhartigan** [comment]
Pageant version is 0.70.0.0 (Release 0.70)|

I generated a 4096 bit RSA key with no password.  Same result when trying to add to Pageant.  "Agent connection failed."

**Comment by hifi** [comment]
Are both of the programs running as the same user? Neither of them was started elevated as the Administrator?

**Comment by madhartigan** [comment]
Both are running as the same user from what I can tell.  The windows installation is fresh from 5/13 and my account was the only one created.  I launch both Pageant and Keepassxc directly, without right-clicking and selecting "Run as Administrator".  Neither of them have had their compatibility properties changed to "Run as Administrator."  So, if they're executing as Administrator, it's happening without my knowledge.

**Comment by hifi** [comment]
I've been trying to reproduce this issue on Windows 10 Pro 1709 and only once I got the "Agent protocol error" message but then was unable to repeat. I kept switching between the portable versions of KeePassXC from the GitHub releases page.

Could you try an older portable release like 2.3.1 and see if you get different results? I'd like to get to the bottom of this and the next thing I'm going to do is upgrade Windows to 1803 but that may take a while.

**Comment by madhartigan** [comment]
I've attached images of what I'm seeing.

Pageant does not show any keys loaded.  

What is unusual is the other image I've posted.  That error is new.  Previously, it only said "Agent refused this identity."

Another thing I wanted to ask is whether Pageant *requires* ppk files for they keys.  My keys are not ppk files.  They are standard Open_SSH id_ed25519 and id_ed25519.pub files.  Could that be causing the issue?


![pageant](https://user-images.githubusercontent.com/320639/40189715-15c8822c-59cb-11e8-9e70-2cd6c79695fb.PNG)
![loaderror](https://user-images.githubusercontent.com/320639/40189722-19b71f92-59cb-11e8-9da0-7800e83c8e0d.PNG)

**Comment by hifi** [comment]
Glad it worked! If you happen to hit the original issue again it would be interesting to find out what combination of programs will cause it. My original hunch was it had something to do with the bitness of them (32 vs 64) but couldn't repro with 32 bit portable KeePassXC and 64 bit Pageant.

The KiTTY webpage says this: "In order to use KiTTY with Pageant (another very useful soft from PuTTY team) just rename **kitty.exe** to **putty.exe**."
