### ISSUE TITLE
Search for entries by UUID

### ISSUE THREAD

**Issue by ftorto** [keepassxreboot/keepassxc#1963]
The way to answer my 2 following use cases is a bit complicated and I think look for **REF**erences directly from the search box could help : 
- I want to know what is the original entry pointed by the reference of my current entry
- I want to find all the entries referencing my current entry

## Expected Behavior
- Paste the reference to check in searchbox
- Entries depending on this reference **AND** entry matching this reference are displayed in results

## Current Behavior
Currently, to know what is the original entry, I change `{REF:U@I:<reference_id>}` by `{REF:T@I:<reference_id>}` (note the `U` changed to `T`) as detailed in #433 and try to find the corresponding entry
The second usecase can't be done

## Possible Solution
Searchbox could be the easy way to implement but UX could be improved with right-click (as suggested in #433 too for a similar behaviour: copy the ref to clipboard)

## Context
Context already detailed in summary above

**Comment by TheZ3ro** [comment]
For the first point: "I want to know what is the original entry pointed by the reference of my current entry" should be nice to have an entry UUID option in the search engine, ping @droidmonkey 

For the second one: "I want to find all the entries referencing my current entry" it's more complicated and I think will need some time to develop

**Comment by droidmonkey** [comment]
This would be better implemented as a GUI element. I have an idea for a "meta" database class that contains dynamically computed relationship and other information about the database after it is opened and/or changed.

**Comment by Felixoid** [comment]
Hello. Is there some progress?

**Comment by nniesen** [comment]
In KeePass2, I can click on the `{REF:...}` to navigate to the source. I make extensive use of refs, especially with SSO/OAuth systems, so its useful for me to be able to navigate to the source of the ref. I like that you show the resolved value of the ref but would like some means to navigate to it. I think this would negate the need for the search but would need to confirm with the OP.

**Comment by gaensler** [comment]
Any news on this topic? I worked a lot with building databases with references lately and found the two mentioned features very useful:

Search entries by UUID - maybe showing both the entry with that UUID and entries using that UUID as reference would be confusing. I think there should be some kind of search-flag "don't) resolve in references", so you can toggle if references should be resolved during searching or not. This would make the search-behaviour more precise.

Copy UUID from right-click-menu would save a lot of clicks!
Or maybe add an "copy attribute as reference" sub-menu to the right-click-menu like the existing "copy attribute" one.

I think does are actually two separate features for the whole reference thing... If this get's more attention i would open a request for the right-click-menu thing.

**Comment by metal450** [comment]
I've spent the past several hours trying to figure out which entry is being referenced by another, & finally found my way here.  Is there still no way to do this?  With many hundreds of entries, going through & looking at each entry's UUID via its properties is pretty agonizing... :/

**Comment by droidmonkey** [comment]
You could export the xml of the database using keepassxc-cli and search the xml for the uuid

**Comment by metal450** [comment]
Thanks, I'll give that workaround a try for now.

Still do think it'd be nice to be able to directly search for UUID in the search box tho, I've had this issue a handful of times in the past as well.

**Comment by droidmonkey** [comment]
This will be fully addressed in 2.7.0

**Comment by metal450** [comment]
Excellent! :)

**Comment by shibe2** [comment]
@droidmonkey I have KeePassXC 2.7.1, and I can't figure out how to search for UUID.

**Comment by aceArt-GmbH** [comment]
UUID search implemented in #9571 ;)

**Comment by jhnielsen** [comment]
> @droidmonkey I have KeePassXC 2.7.1, and I can't figure out how to search for UUID.

Make sure to use the correct search string format: `uuid:"<uuid>"`.

You can find an explanation by clicking the ` ?` symbol in the search pane.

**Comment by JustJinxed** [comment]
So, how would one go about looking for entries that use a particular uuid reference? Ex: I have a good 10 stackexchange websites with various domains, but I forget which ones they are and wanted to add a note to them. I can't seem to narrow down which entries that use a particular uuid - the search only returns the source, not the clones.

**Comment by droidmonkey** [comment]
Wouldn't the url be different for each one? BTW, we stiletto multiple urls in the browser settings of the entry. You may be able to get away with one entry now.

**Comment by JustJinxed** [comment]
Oh heck, didn't even realize that got added under "Browser Integration" thx, that solves so many problems.
