### ISSUE TITLE
Add ability to set default username for groups

### ISSUE THREAD

**Issue by carestad** [keepassxreboot/keepassxc#1965]
A database can have a default username that is pre-filled when adding entries, but I'm really missing the ability to override this per groups.

For instance, most of my entries are personal and private, but some of them are work related. I would like work related ones to pre-fill my work email when adding entries to that group.

**Comment by TheZ3ro** [comment]
The default username is a database option according to the original KDBX specification. https://github.com/keepassxreboot/keepassxc-specs/blob/master/kdbx-xml/rfc.txt#L311

Maybe we can do something for per-group default username using CustomData

**Comment by mstarke** [comment]
KDBX has the concept of user templates. You can set a group to be the template group and use those for creating new entries. This does not allow for group based settings but you could add templates for each group but those then have to be selected manually on creation

**Comment by droidmonkey** [comment]
This is overtaken by the username auto-complete
