### ISSUE TITLE
Speichern von Daten in einer Datenbank im Netzwerk nicht möglich

### ISSUE THREAD

**Issue by Simlock** [keepassxreboot/keepassxc#1966]
Ich habe eine Datenbank im Netzwerk angelegt (FritzBox NAS USB-Stick am Router angeschlossen). Es ist allerdings nicht möglich, Daten in der Datenbank abzulegen. Ich bekomme immer die Fehlermeldung, "Schreiben der Datenbank fehlgeschlagen. Zugriff verweigert". Zuvor habe ich KeePass verwendet. Damit hatte ich dieses Problem nicht.
Betriebssystem Windows 10 64bit, KeePassXC 2.3.3

I have created a database in the network (FritzBox NAS USB-stick connected to the router). However, it is not possible Store data in the database. I always get the error message, "Writing the database failed. Access denied." Previously I used KeePass, so I did not have this problem. 
Operation system Windows 10 64bit, KeePassXC 2.3.3
(Translated with Google Translate)

**Comment by mistabob** [comment]
Die Freigabe der FritzBox ist nur per SMB 1.0 Protokoll erreichbar. Falls du mit einer aktuellen Win10 Version auf die SMB Freigabe der FritzBox zugreifen willst, musst du erst SMB 1.0 über "Programme und Features" -> "Windows-Features aktivieren/deaktivieren" -> "Unterstützung für die SMB 1.0/CIFS-Dateifreigabe" -> "SMB 1.0/CIFS-Client" installieren/aktivieren.

**Comment by Simlock** [comment]
SMB 1.0/CIFS-Client war schon aktiviert. Ich habe auch sonst keine Probleme mit anderen Programmen auf die FritzBox zuzugreifen. Nur KeePassXC kommt mit der Meldung "Zugriff verweigert". Nehme ich jetzt KeePass, funktioniert der Zugriff auf die .kdbx ohne Probleme.

**Comment by phoerious** [comment]
Issue is most likely related to #803. Closing this one here.
