### ISSUE TITLE
KeePassXC HTTP Confirm Access dialogue appears twice

### ISSUE THREAD

**Issue by hackel** [keepassxreboot/keepassxc#1970]
## Expected Behavior
When a KeePassHTTP client requests passwords for a site, the permission approval dialogue should only appear once.

## Current Behavior
I'm connecting to KeePassXC using KeePassHttp-Connector 1.0.11 on Firefox 61.  When I navigate to a site which has a stored password, the "KeePassXC HTTP Confirm Access" dialogue appears twice, in the same position (on top of each other).  I can approve it once, and dismiss the other, or dismiss both, in which case these two dialogues continue popping up on each page I navigate to on that site (that has a password field).

I'm not sure if the fault lies with the extension or KeePassXC.  I realize it may not be worth fixing in any case since the legacy KeePassHTTP integration is going away, but unfortunately I still cannot use the new KeepassXC-Browser integration with the snap package.  Incidentally, this behaviour does not occur on Chromium with the chromeIPass extension.  

## Debug Info
KeePassXC - Version 2.3.3
Revision: 0a155d8
Distribution: Snap

Libraries:
- Qt 5.7.1
- libgcrypt 1.7.6-beta

Operating system: Ubuntu Core 16
CPU architecture: x86_64
Kernel: linux 4.15.0-20-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by varjolintu** [comment]
This is a old bug in the HTTP handling in KeePassXC. The fix is easy to made but it's unsure if we are going to release any bug fixes or upgrades to the HTTP side anymore.

**Comment by droidmonkey** [comment]
Unfortunately, HTTP plugin is deprecated and will be removed in 2.4. no bug fixes are being made.
