### ISSUE TITLE
[Ubuntu Budgie] Keepass won't minimize to tray

### ISSUE THREAD

**Issue by papaZuhl** [keepassxreboot/keepassxc#1974]
## Expected Behavior

Using the setting to minimize KeePassXC to tray instead of shutting it down, I would expect an Icon to show up somwhere in my tray which I can use to open KeePassXC again.

## Current Behavior

KeePassXC will minimize and hide itself without shutting down, however there is no icon in my tray, which I can click to open KeePassXC again

## Possible Solution

I got it working by starting KeePassXC as root. However I would prefer not to have to do this.

## Steps to Reproduce (for bugs)

1. Install Ubuntu Budgie
2. Install KeePassXC
3. Enable minimize to tray instead of shutdown
4. No icon is visible in the tray

## Context

This is mostly just a personal preference, since I do not like to have many active windows. 

## Debug Info

KeePassXC - 2.3.1

Operating system: Ubuntu Budgie
CPU architecture: amd64
Kernel: Linux version 4.15.0-20-generic

Enabled extensions:
- none

**Comment by phoerious** [comment]
I've never heard of Ubuntu Budgie before.
Tray icons work on all supported platforms. You should take this to the Budgie developers, since we cannot fix it for you.
