### ISSUE TITLE
Search in all opened databases is not working

### ISSUE THREAD

**Issue by salvatorecordiano** [keepassxreboot/keepassxc#1976]
After upgrading KeePassXC to version 2.3.3 I'm not able to access to credentials stored on all opened databases using KeePassXC-Browser 1.1.3 for Chrome.

I have encountered this problem also on Ubuntu Linux after KeePassXC upgrade.

## Expected Behavior
I'm connected to main database and I'm able to access to credentials stored on all opened databases.

## Current Behavior
I'm connected to main database and I'm not able to access to credentials stored on all opened databases. I'm able to use only the main database.

## Debug Info
KeePassXC - Version 2.3.3
Revision: 0a155d8

Libraries:
- Qt 5.9.3
- libgcrypt 1.8.2

Operating system: OS X El Capitan (10.11)
CPU architecture: x86_64
Kernel: darwin 15.6.0

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by droidmonkey** [comment]
You need to register each of the databases with the plugin. This was a bug (and rather bad) to troll databases not authorized to communicate with the browser plugin.
