### ISSUE TITLE
Time out or not connected error on 2.3.3. under Windows 10

### ISSUE THREAD

**Issue by Larry3460** [keepassxreboot/keepassxc#1977]
Hello, this is the issue I'm facing :

## Current Behavior
Having KeePassXC-browser extension under Firefox Quantum 60.0.1 64 bits, where 2.3.1 was working perfectly I enconter the issue "Timeout or not connected to KeePassXC"
Still the "Reload" button doesn't work and, when I got to settingsd, ther are no connected databases found.

## Possible Solution
I've alresady checked the registry at HKEY_CURRENT_USER\Software\Mozilla\NativeMessagingHosts\org.keepassxc.keepassxc_browser and the value in it "C:\Applications portables\KeePassXC-2.3.3-Win64\org.keepassxc.keepassxc_browser_firefox.json" seems correct.

What to do, now ?
Any help welcome.

**Comment by Larry3460** [comment]
Hi,
There are two .json sripts in this path : 'org.keepassxc.keepassxc_browser_firefox.json' and 'org.keepassxc.keepassxc_browser_chrome.json'
Please, find their content here above : 


`{
    "allowed_extensions": [
        "keepassxc-browser@keepassxc.org"
    ],
    "description": "KeePassXC integration with native messaging support",
    "name": "org.keepassxc.keepassxc_browser",
    "path": "C:\\Applications portables\\KeePassXC-2.3.3-Win64\\keepassxc-proxy.exe",
    "type": "stdio"
}


`{
    "allowed_origins": [
        "chrome-extension://iopaggbpplllidnfmcghoonnokmjoicf/",
        "chrome-extension://oboonakemofpalcgghocfoadofidjkkk/"
    ],
    "description": "KeePassXC integration with native messaging support",
    "name": "org.keepassxc.keepassxc_browser",
    "path": "C:\\Applications portables\\KeePassXC-2.3.3-Win64\\keepassxc-proxy.exe",
    "type": "stdio"
}
`

**Comment by threeflappp** [comment]
@Larry3460 can you show us the browser integration settings? Also see if keepassxc-proxy.exe is running.

I had this issue after I updated to 2.3.3 as well. Keepassxc-proxy just wouldn't start no matter what I do (use custom proxy location, manually run it, etc). Then I remembered that I still have a copy of version 2.3.1 on a flash drive. I ran that version and it worked as expected, then I went back to 2.3.3 again and it worked...

**Comment by Larry3460** [comment]
I tried a new installation of KeePassXC-2.3.3-Win64-Portable, after carefully removing the previous one. This time no more .json files.
I don't understand how they disappeared and I don't know how to get them back. I thought they were provided by the portable .zip archive.

**Comment by varjolintu** [comment]
Those .json files are created and deleted dynamically, not bundled in the .zip archive.

**Comment by droidmonkey** [comment]
This might be because the portable version carries it's own config file and the specific browsers are disabled in that config which might cause the app to remove the plugin json on launch.

**Comment by threeflappp** [comment]
I was able to finally fix my problem. It was an issue with the registry after all. This doesn't get updated with new versions (minor inconvenience for using portable version). I thought "Update native messaging manifest files at startup" option handles this but it only changes the content of the json and not the registry value that points to its location.

@Larry3460 I tried portable version in the exact same location as yours and it worked for me. Here are a couple of things I could think of for you to try: 

- Make sure browser integration is enabled for json file to be created.
- Make sure the registry value at 
`\HKEY_CURRENT_USER\Software\Mozilla\NativeMessagingHosts\org.keepassxc.keepassxc_browser`
contains the full path to the json file.
- Try to manually start keepassxc-proxy.exe and see if you encounter any errors.

**Comment by varjolintu** [comment]
We need to test if the registry entry gets updated with portable versions too, not just the JSON content.

**Comment by Larry3460** [comment]
Hello all and thanks for your answsers.
@varjolintu and @droidmonkey  I still don't have any .json file created dinamically. I found, in the path the keepassxc.ini file and here attached is his browser section : 

> [Browser]
> Enabled=true
> ShowNotification=true
> BestMatchOnly=false
> UnlockDatabase=true
> MatchUrlScheme=true
> SortByUsername=false
> SupportBrowserProxy=true
> UseCustomProxy=false
> CustomProxyLocation=
> UpdateBinaryPath=false
> AlwaysAllowAccess=false
> AlwaysAllowUpdate=false
> SearchInAllDatabases=false
> SupportKphFields=true

**Comment by varjolintu** [comment]
@Larry3460 Could you check if the JSON file exists in your user's hidden AppData folder under your user account?

**Comment by Larry3460** [comment]
@varjolintu I recovered my two .json files, not in my users folder, but manually running keepassxc-proxy.exe.
However, my problem remains unsolved.
I ckecked the paths in the .json files : 

>  "path": "C:\\Applications portables\\KeePassXC-2.3.3-Win64\\KeePassXC.exe",
and
>     "path": "C:\\Applications portables\\KeePassXC-2.3.3-Win64\\KeePassXC.exe",
I checked also the Registry entries : 

- in Ordinateur\HKEY_CURRENT_USER\Software\Mozilla\NativeMessagingHosts\org.keepassxc.keepassxc_browser : 

> C:\Applications portables\KeePassXC-2.3.3-Win64\org.keepassxc.keepassxc_browser_firefox.json

- in Ordinateur\HKEY_CURRENT_USER\Software\Google\Chrome\NativeMessagingHosts\org.keepassxc.keepassxc_browser

> C:\Applications portables\KeePassXC-2.3.1-Win64\org.keepassxc.keepassxc_browser_chrome.json

**Comment by varjolintu** [comment]
@Larry3460 I made some testing with the portable version of KeePassXC 2.3.3. If you had any previous version installed with some browser support enabled, the registry keys are pointing to AppData. When starting the portable version afterwards enabling support for Firefox (I just chose to use it for testing) creates the JSON scripts to the portable folder but doesn't update the registry entries (because they already exists).

Then I disabled the support for Firefox and the registry entries were deleted. Enabling the support again writes correct path to the registry entry. After that everything works fine.

I'll make a fix to the binary path updating. It should also update the registry entries even if they already exists. But the method I described above is a workaround.

**Comment by Larry3460** [comment]
@varjolintu I tried your workaround but, when I disabled the support for Firefox 
[https://up.security-x.fr/file.php?h=R0d22a8e9686281284a7cb099579c23a6](url)
The registry entries remained : 
[https://up.security-x.fr/file.php?h=Re1d9f1c5054548518781318da5fbc635](url)
So this workaround looks like not matching for me.

**Comment by Larry3460** [comment]
Maybe I should mention that I was using the old version of KeePassHTTP before going to KeePassXC-browser...
So it's really weird: after a few minutes, without touching any settings KeepassXC-broswer started working. He asked for the connection to the database and everything started working on his own.
I still do not understand why ... but it works it's essential!
Thanks to the whole team.

**Comment by varjolintu** [comment]
@Larry3460 Maybe you forgot to refresh the regedit? If the disable/enable workaround wouldn't have worked, then I'd suggested removing the registry entries manually.

Closing the issue. If any problems related to this appears please comment to this issue and we'll reopen it.

**Comment by Larry3460** [comment]
It looks like I sang victoria too early. The issue came back as mysteriously as it was gone.
I cannot get back the registry entries that I deleted manually.
In the settings of the Firefox extension, I have my database that appears connected, but I still have the error and the "reload" button is ineffective.
[https://up.security-x.fr/file.php?h=Ree38b657b8c4d217f35254b7d9afeede](url)
I do not know what to do.

**Comment by varjolintu** [comment]
@Larry3460 If the registry entries won't come back have you also tried to delete all .json scripts so KeePassXC could generate both scripts and registry entries from a clean slate?

**Comment by Larry3460** [comment]
@varjolintu I just tried but it changed nothing : The .json desn't come back and registry entries either.
Even when I lanch manually keepassxc-proxy.exe and keepassxc-cli.exe.

**Comment by varjolintu** [comment]
@Larry3460 Those executables don't handle the scripts or registry. Only KeePassXC does that through the browser integration settings.

**Comment by Larry3460** [comment]
@varjolintu so there's something wrong, for me, with KeePassXC.

**Comment by varjolintu** [comment]
@Larry3460 Do you have a normal KeePassXC installation somewhere or have you always used just the portable version?

**Comment by Larry3460** [comment]
@varjolintu Because the portable version of KeePassXC was not working, I tried to install the normal version, but after a while I removed it through IObit uninstaller. So I think it was a clean uninstall.

**Comment by Larry3460** [comment]
@varjolintu For your information, I reinstalled the old KeePass HTTP plugin and everything works fine with it, even though the database entries are still missing.
