### ISSUE TITLE
Keepassxc stopped working on Centos 7

### ISSUE THREAD

**Issue by pjc123** [keepassxreboot/keepassxc#1979]
## Expected Behavior

Clicking on Keepassxc in the Centos Start menu under Accessories should start the program.

## Current Behavior

Keepassxc does not load / start.  This used to work.

If I try running it from the terminal I get the following response:
$ keepassxc
Existing single-instance lock file is invalid. Launching new instance.
keepassxc: symbol lookup error: /lib64/libgcrypt.so.20: undefined symbol: gpgrt_lock_lock

## Debug Info

KeePassXC - VERSION 2.3.3

## System Info
Operating system: Centos 7.5
(More details = Centos-release-7-5.1804.el7.centos.2.x86_64)

Kernel = 3.10.0-862.2.3.el7.x86_64

**Comment by pjc123** [comment]
MORE INFORMATION:

1) I am also working with the Centos folks on this.  The error appears related to the libgpg-error package.  I can't run YUM to update any of my packages because of this.  It fails with the following message:

`
Resolving Dependencies
--> Running transaction check
---> Package libgpg-error.x86_64 0:1.12-3.el7 will be updated
---> Package libgpg-error.x86_64 0:1.29-1.el7.centos will be an update
--> Finished Dependency Resolution
Error:  Multilib version problems found. This often means that the root
       cause is something else and multilib version checking is just
       pointing out that there is a problem. Eg.:

         1. You have an upgrade for libgpg-error which is missing some
            dependency that another package requires. Yum is trying to
            solve this by installing an older version of libgpg-error of the
            different architecture. If you exclude the bad architecture
            yum will tell you what the root cause is (which package
            requires what). You can try redoing the upgrade with
            --exclude libgpg-error.otherarch ... this should give you an error
            message showing the root cause of the problem.

         2. You have multiple architectures of libgpg-error installed, but
            yum can only see an upgrade for one of those architectures.
            If you don't want/need both architectures anymore then you
            can remove the one with the missing update and everything
            will work.

         3. You have duplicate versions of libgpg-error installed already.
            You can use "yum check" to get yum show these errors.

       ...you can also use --setopt=protected_multilib=false to remove
       this checking, however this is almost never the correct thing to
       do as something else is very likely to go wrong (often causing
       much more problems).

       Protected multilib versions: libgpg-error-1.29-1.el7.centos.x86_64 != libgpg-error-1.12-3.el7.i686
`

2) It looks as if the KeepassXC version of the file conflicts with the Centos version as shown here, although I don't know how to fix it:

`
yum list libgpg-error --noplugins --showdupli
google-chrome 3/3
Installed Packages
libgpg-error.i686                1.12-3.el7 @base
libgpg-error.x86_64              1.12-3.el7 @anaconda
Available Packages
libgpg-error.i686                1.12-3.el7 base
libgpg-error.x86_64              1.12-3.el7 base
libgpg-error.x86_64              1.13-1.el7.centos bugzy-keepassxc
libgpg-error.x86_64              1.29-1.el7.centos bugzy-keepassxc
`

**Comment by pjc123** [comment]
OK.  The Centos folks basically told me to get rid of the KeepassXC program because it is not playing nice with Centos.  Oh well.  

SO, QUESTION:  Assuming they will not cause the same issue, can I use keepass or keepassx to open the database file created with keepassxc, or do I risk corruption?

**Comment by droidmonkey** [comment]
Just use the appimage version of KeePassXC from our download page.

**Comment by pjc123** [comment]
@droidmonkey.  Thanks, the AppImage did the trick.  Also, removing the bugzy version fixed the libgpg-error version conflict and YUM is working again.

**Comment by jpdonnell** [comment]
On Oracle  7.5 : I get the same errotr

keepassxc: symbol lookup error: /lib64/libgcrypt.so.20: undefined symbol: gpgrt_lock_lock
