### ISSUE TITLE
Option to permanently delete entries

### ISSUE THREAD

**Issue by mattvchandler** [keepassxreboot/keepassxc#198]
## Expected Behavior
When deleting an entry, I would like an option to permanently delete it, bypassing the recycle bin.

## Current Behavior
To permanently delete an entry, I must send it to the recycle bin, open the recycle bin, and then delete the entry again

## Possible Solution
There should be either an option to either disable the recycle bin, or an option to delete an entry without putting it in the recycle bin

## Context
I have no need to keep deleted entries. If I do accidentally delete one that I still need, I can close the program without saving, or restore a backup of the db file. The recycle bin adds a pointless (at least to me) second step to deletion.

## Your Environment
* KeePassXC version/commit used: 42c0815cdaa652bcdf25b90a2a4a20b2981a39b2
* Qt version: N/A
* Compiler: N/A
* Operating System and version:  N/A

**Comment by louib** [comment]
There is already a `Use recycle bin` option in the Database settings, which is turned on by default. However, there is no option to bypass the recycle bin on a per entry basis.

**Comment by mattvchandler** [comment]
Ah. I didn't look in the DB settings. Thanks!

**Comment by ghost** [comment]
> There is already a `Use recycle bin` option in the Database settings, which is turned on by default. However, there is no option to bypass the recycle bin on a per entry basis.

Have you considered adding a hotkey, for instance Shift + Del ?
