### ISSUE TITLE
Auto-Type doesn't detect Pinentry Mac window

### ISSUE THREAD

**Issue by Couto** [keepassxreboot/keepassxc#1982]
When using the Global Auto-type shortcut on a Pinentry Mac dialog, KeepassXC always display and error saying "Couldn't find an entry that matches the window title:". 

This is also reflected when trying to add a new Auto-Type window association, the Pinentry Mac doesn't appear on the list of available windows.

![pinentry mac](https://user-images.githubusercontent.com/165314/40317710-2ab009ba-5d1a-11e8-8024-b71ffd325c28.png)

My database was migrated from macpass, and this feature used to work fine.

## Expected Behavior
KeepassXC should fill in the password in the PIN dialog

## Current Behavior
KeepassXC states that it could not find an entry that matches the window title, and fallsback to the next window:

![screen shot 2018-05-21 at 17 13 40](https://user-images.githubusercontent.com/165314/40317788-665d26be-5d1a-11e8-8e44-f96494d6fab8.png)

## Steps to Reproduce (for bugs)
0. Use Pinentry mac to unlock a GPG key
1. force an action that requires to use the private key (e.g.: sign a commit in a git repository)
2. type the global Auto-type shortcut while the cursor is on the PIN field

## Debug Info
KeePassXC - Version 2.3.3
Revision: 0a155d8

Libraries:
- Qt 5.9.3
- libgcrypt 1.8.2

Operating system: macOS Sierra (10.12)
CPU architecture: x86_64
Kernel: darwin 16.7.0

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by Couto** [comment]
I can provide more information if needed, but at the moment, I'm not quite sure I know what's the relevant information to share.

**Comment by mstarke** [comment]
Is Pinentry displaying an Icon in the Dock or does it only reside inside the Menubar?

**Comment by mstarke** [comment]
I just took a look at the source of Pinentry and it is indeed only displayed in the menu bar since the ```LSUIElement``` key is set to ```true``` in the ```Info.plist```.

My guess is the code for getting the active window title is not working for windows of those kinds of apps:
https://github.com/keepassxreboot/keepassxc/blob/8a0aae775af2758ec675ecf7fc4d62150e83a09d/src/autotype/mac/AutoTypeMac.cpp#L93

The solution might be to use ```::CGWindowListCopyWindowInfo(0, kCGNullWindowID);``` to get all known windows but this needs additional filtering since many windows inside this list aren't of interest to KeePassXC.

**Comment by ChristopherSchultz** [comment]
This happens to me (misidentified window) when just logging-into GitHub's website:

0. Lock your KeePassXC database
1. Go to https://github.com/ (and logout if necessary)
2. Click "sign in"
3. Press the global hotkey for auto-fill

Result:
1. KeePassXC opens a separate dialog requesting the database password (while showing the main KeePassXC window separately, also with a password-field prominently displayed)
2. After entering the password and pressing enter, a dialog is shown with this error:
    Couldn't find an entry that matches the window title:
    
    keepass - KeePassXC

Expected: KeePassXC auto-fills the web browser window's form

Note: if the database is already unlocked, the auto-type global hotkey is working as expected.

**Comment by ChristopherSchultz** [comment]
Possibly related to issue #947.

**Comment by ChristopherSchultz** [comment]
Possibly related to issue #1216

**Comment by Couto** [comment]
I'm closing this issue in order to clean up my Issues box. 
Feel free to open again if it's relevant.
