### ISSUE TITLE
Documentation for keepassxc-cli not readily available

### ISSUE THREAD

**Issue by linuxrichard** [keepassxreboot/keepassxc#1983]
There is nothing on the website indicating keepassxc-cli's existence.
Although there is a manpage in one(?) of the packages, there is nothing on the website and nothing for the Windows package other than the keepassxc-cli.exe -?
This is a very useful package and it is sad that it is hidden away in this way. I had even started at looking at building this myself because I didn't know it existed!

I suggest that the website have a page or section added that:
- highlights that keepassxc-cli exists
- explains its purpose
- provides the syntax (extract from the manpage?)

**Comment by droidmonkey** [comment]
@louib you're up to bat for this one :grin:

**Comment by phoerious** [comment]
Closing this in favour of https://github.com/keepassxreboot/keepassxreboot.github.io/issues/41
