### ISSUE TITLE
SSH Agent: Integrate with OpenSSH for Windows

### ISSUE THREAD

**Issue by hifi** [keepassxreboot/keepassxc#1984]
Windows 10 1803 "Spring Update" brought OpenSSH 7.6p as a standard system utility. This includes the *ssh-agent* service.

## Possible Solution
The agent protocol is exactly the same but some security context or something else is blocking *QLocalSocket* to directly connect to the named pipe. More work is needed.

## Context
Pageant is currently the dominant agent for Windows but OpenSSH will slowly claim that space now that it comes with Windows.

**Comment by hifi** [comment]
So it appears the *QLocalSocket* approach would work just fine except the call to `createWindowsDACL()` tightens security too much.

Reading the [OpenSSH for Windows source](https://github.com/PowerShell/openssh-portable/blob/latestw_all/contrib/win32/win32compat/ssh-agent/agent.c#L242)  it appears the service process would need at least *PROCESS_QUERY_INFORMATION* and *PROCESS_DUP_HANDLE* privileges.

The original commit that added this hardening was d0ebaff7b4aeedbe1898fd38a9921ddc64dda99b, @rockihack do you happen to have any idea what needs to be added that the connection to ssh-agent service would work without compromising security? Thanks!

**Comment by rockihack** [comment]
@hifi I tried to grant only minimal access rights, same as for protected processes.
see: https://msdn.microsoft.com/en-us/library/windows/desktop/ms684880(v=vs.85).aspx#Protected_Processes

If this really causes the problem then adding a special DACL entry for the "NT SERVICE\SSHD" user account might work.

**Comment by hifi** [comment]
What did work is add the privileges I said for *LocalSystem* account which is the one running the agent. The SSHD user is not used for the agent AFAIK. Once I figure out how to expose this with the Pageant support I'm going to open a PR against 2.4.0.

Thanks for your input!
