### ISSUE TITLE
Drag and Drop

### ISSUE THREAD

**Issue by DavidLeigh** [keepassxreboot/keepassxc#1987]
I am using Ubuntu 16.04 LTS with current to two-days ago updates.  I installed KeePassXC from the Canonical Repository which is, apparently, the "snap" version.  My former installation of KeePass2 allowed me to drag-n-drop the username and/or password into the appropriate location on a web page, and WITHOUT placing it into the copy buffer.  That was pretty cool.  I understand that using AutoType will do something similar, but Janek asked me to post this as a potential change her on GitHub and that the is may be a Gt installation issue.  Thank you for keeping KeePass alive. Dave...

**Comment by MegaV0lt** [comment]
Using Linux. Also would like to see the Drag&Drop-Feature

**Comment by ChristopherSchultz** [comment]
Ping. I just grabbed 2.5.0 (thanks!) and was sad to see this wasn't a part of the release. Can I ship a case of beer to someone to implement this? I'd volunteer to help, but you don't want me writing C++/GTK code.

**Comment by droidmonkey** [comment]
I tested drag and drop and found it to work out of the box. I believe I fixed some issues with it in 2.5.0. Specifically which fields can you not drag and drop?

**Comment by ChristopherSchultz** [comment]
Good question. If it clarifies things, I'm on MacOS Mojave.

Steps-to-reproduce:
1. Unlock the database, search for some entry
2. From the search results screen (or even with no search result), attempt to drag e.g. username field to some text field in another window e.g. browser or even just Terminal CLI

Result: Drag operation pulls the whole entry line from the table and drops it onto the target application, which vetos the drop-operation.
Expected (hoped?): Drag operation pulls only the specific field grabbed (e.g. position the mouse pointer over the "username" field and begin dragging) and drops it as text onto the target

I observe the same behavior with the password field: the whole entry line is dragged.

I tried drag/drop in the editing window (editing an entry?) and no drag-and-drop works at all. Selecting text and trying to drag just resets the text-selection. Maybe I'm misunderstanding what you are saying about the editing window. I'm only really interested in the use-case above, though.

**Comment by heurbar** [comment]
Another vote for feature to drag and drop username, password and url fields from a KeePassXC entry to appropriate fields in a web browser login page.   This is the one KeePass2 feature that I really miss in KeePassXC.

Yes, the autotype feature can be used.  For security reasons I just prefer to drag-and-drop instead of auto completing the login fields.

Appears new NIST guidelines recommend website implement drag-and-drop on login forms for user authentication.

**Comment by tredondo** [comment]
On KDE, I find that I can drag and drop text *into* KeePassXC, but not *from* KeepassXC into the browser. I think this is a pretty important feature because I would like to use generate KeePassXC passwords, and drag&drop them into browsers during signup forms.
