### ISSUE TITLE
Impossible to open database. This is not a 

### ISSUE THREAD

**Issue by paddaone** [keepassxreboot/keepassxc#1989]
<HI. Borrowed a macbook pro laptop (high sierra os) from a friend to replace temporarily my KDE 18.04 desktop for 3 days. Had my kdbx file on dropbox. Installed keepassxc on mac and opened db. No problem. Back to KDE, impossible to open file as "it is not a keepass database". Works fine on macbook, not on KDE (not a keepass file) nor on my android (wrong signature or corrupted). Had an export.csv file made from the mac. Tried to recreate the db by importing it in kde but all garble with utf8 selected or any other caracters. >

## Debug Info

KeePassXC - 2.3.1

Operating system: KDE 18.04LTS
CPU architecture: 64
Kernel: 4.15.0-22

Enabled extensions:
NONE

**Comment by hifi** [comment]
It would be helpful if you could reproduce this issue with a test database that doesn't contain your actual credentials. There could be any number of things happening when you transferred your real database and unless you can reproduce it reliably it is highly unlikely it can be resolved on our end.
