### ISSUE TITLE
Crash clicking generate with all character ranges disabled

### ISSUE THREAD

**Issue by jsoref** [keepassxreboot/keepassxc#199]
## Expected Behavior
Don't crash

## Current Behavior
Crashes

## Possible Solution
Disable generate when no ranges enabled

## Steps to Reproduce (for bugs)
1. Tap the die
2. turn off A-Z, a-z, 0-9, /*_...
3. Tap generate

## Your Environment
* KeePassXC 2.1
* macOS

**Comment by phoerious** [comment]
Resolved by PR #226.
