### ISSUE TITLE
CSV import not asking filename

### ISSUE THREAD

**Issue by fam4r** [keepassxreboot/keepassxc#1995]
## Expected Behavior
When importing a CSV file it should ask for filename, like for "New database" functionality.

## Current Behavior
After "Import CSV fields" view, clicking "OK", I'm getting following error in a red box:

> Writing the database failed.
Cannot create  for output

## Possible Solution
Before/After "Import CSV fields" view, it should ask database filename and path.

## Steps to Reproduce (for bugs)

1. Database > Import > Import CSV file...
2. Choose CSV file, then "Open"
3. Set master key etc., then "OK"
4. Complete configuration in "Import CSV fields" view, then "OK"
5. See error in red box

## Context
I was trying to import CSV file, error message was not clear:

> Writing the database failed.
Cannot create  for output

I was able to understand what to do (give the database a filename and path) only by opening `keepassxc` from command line and see a more detailed error output:

> QFile::remove: Empty or null file name
Empty filename passed to function

## Debug Info

KeePassXC - Version 2.3.3
Revision: 0a155d8

Libraries:
- Qt 5.10.1
- libgcrypt 1.8.2

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 4.16.10-1-ARCH

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by hifi** [comment]
I couldn't reproduce this with a simple test of using the import feature. When starting an import without any open database it starts creating a new unsaved database which I could save successfully.

**Comment by mcnelson** [comment]
Observing this behavior too. I get "Cannot create  for output" with two spaces between "create" and "for" as if it's trying to write a null filename. Before any save of the DB.

Strangely it does actually run the import, but incorrectly. The column mapping that I configure in the wizard is ignored. But I can save it after the wizard is done.

Using `keepassxc-2.3.3-1.fc28.src.rpm`

**Comment by gggomg** [comment]
Absolutely same error and same solution for me with last version on Windows 10 when importing .csv from Vivaldi browser. Thank you.

**Comment by rifkegribenes** [comment]
same error, KeePassXC 2.3.4, Mac OS 10.14 Mojave. any ideas for a workaround for this? is it possible to import a .csv into an existing database rather than create a new one?

**Comment by droidmonkey** [comment]
Please use the 2.4.0 snapshot where this is fixed: https://snapshot.keepassxc.org
