### ISSUE TITLE
Add support to FIDO & FIDO2 U2F on KeepassXC to allow logins on web site

### ISSUE THREAD

**Issue by JoaoPortugal** [keepassxreboot/keepassxc#1996]
It would be nice to add FIDO & FIDO2 U2F support also on software.

I understand it defeats part of the security it provides, but at least makes it harder for those that steal web site databases to login without it.

TOTP is nice... but the web site keeps the secret.. if someone has access to the database will be able to bypass the second-factor.

**Comment by droidmonkey** [comment]
Implementing FIDO in software totally nullifies the two factor component of it.

**Comment by JoaoPortugal** [comment]
Yes, but it allows everyone to have it working now!
Instead of using the much less secure TOTP that has it's secret in the server or even worse send the code to the phone over the total insecure public phone network. 
At least you help move the main risk from the server to the user land... in the server the user has absolutely no control, in is stuff he has some.

**Comment by phoerious** [comment]
FIDO keys also have a secret. It only happens to be factory-programmed, so you cannot change it. Having a software implementation of FIDO-U2F is in no way more secure than TOTP and I haven't seen a single website that supports U2F but not TOTP.

**Comment by vk5tu** [comment]
"Having a software implementation of FIDO-U2F is in no way more secure than TOTP" is not the complete story. TOTP transactions can be replayed, within 30s or so, long enough for a phishing website to authenticate with the real website. With U2F/WebAuthn transactions the phishing website can't predict the server's random challenge.

FIDO software implementations are permitted; attestation allows software implementations of the client to announce their zero security features. The bad news is that websites can refuse to enrol keys based upon the client's attestations of its security features.

Unlike TOTP the U2F/FIDO2 software-only implementation won't be on a different computer, and thus production servers should reject enrolment attempts of these software-only not-really-second-factor FIDO clients.

I hope that you can see that there's little value to users of keepassxc in having a software implementation of U2F/FIDO2, as the "I have no security features" attestation means that within a few years all major websites will reject such clients.

Really, just buy two FIDO2 USB+NFC keys. Servers will accept their "trusted platform" and "user present" attestations for the foreseeable future.

**Comment by giddie** [comment]
A software FIDO2 implementation is:
1. Still a second factor, so long as the database is secured with 2 factors. Just like TOTP.
2. More robust against loss than hardware keys.
3. Much cheaper than hardware keys
4. Essentially TOTP but better. Why would you not?
