### ISSUE TITLE
Add support to SQRL on KeepassXC to allow logins on web site

### ISSUE THREAD

**Issue by JoaoPortugal** [keepassxreboot/keepassxc#1997]
It would be nice to add support to the SQRL (Secure Quick Reliable Login) on software to make it easy to login on web sites that support this on the future.

This is supposed to substitute the use of username & password by this Ed25519 based public key login system... that will generate a different public key for each web site, and even for different accounts inside each account of the same web site.

This is somehow similar to FIDO but it uses Ed25519 not the NIST P256 curve so it should be more secure... and because of this it would be nice to support this also.

FIDO and SQRL can be used together if a web site owner wants it for extra security... so they can complement if one wants... say: banking, military, government, e-mail...

**Comment by droidmonkey** [comment]
Seems to be in draft. Are any websites supporting it?

**Comment by JoaoPortugal** [comment]
There is a demonstration page working for years now: https://www.grc.com/sqrl/demo.htm but since the author did not formally launched the protocol yet because he decided to make a Windows / Wine software to demonstrate it working... no one has made yet the necessary plugins do add to CMS's... otherwise I would be using it already for years.
The author should be launching the SQRL next month to public because he as finished the application, and is now finally happy.

**Comment by droidmonkey** [comment]
Yah... I don't think this is ever going to be a thing. This guy is a techno dinosaur and a one-man-band.

**Comment by aitorpazos** [comment]
At least it is better thought out that the Passkey thing that big tech is pushing for.
I do think it would be a great feature to have.

**Comment by JohnLGalt** [comment]
Only worth supporting if the website owners would implement it. Gibson did put a lot of research into it, but adoption is another thing. I've scrounged the web for sites that implemented it and it is almost nowhere.
