### ISSUE TITLE
[FEATURE] Hide the search results after a click in the "page tree"

### ISSUE THREAD

**Issue by SvenJuergens** [keepassxreboot/keepassxc#1999]
## Expected Behavior
After using the search, a click one a Group Icon on the left side should close the search result and let me see the content of the clicked GroupIcon

## Current Behavior
After using the search, a click one a Group Icon on the left side does not change the view, the search results are still open

## Possible Solution
--Pseudo Code ---
if( click on GroupIcon){
   (if searchResults open){
    close search Results
  }
 ...show content of CroupIcon
}

## Steps to Reproduce (for bugs)
1. Using Keepassxc 2.3.3 on a Mac OS
2. using search
3. click on an icon on the left side 

Operating system: MAC OS Sierra 10.12.6

**Comment by droidmonkey** [comment]
This is implemented in PR #1767
