### ISSUE TITLE
Auto-Type support for MacOS and Windows

### ISSUE THREAD

**Issue by TheZ3ro** [keepassxreboot/keepassxc#20]
KeePass support [Auto-Type](http://keepass.info/help/base/autotype.html) (Keyboard Injection) with [Two-Channel Obfuscation](http://keepass.info/help/v2/autotype_obfuscation.html) to bypass Keylogger and Clipboard-Spoofing.
KeePassX only support Copy-Paste of password.

**Comment by rockihack** [comment]
Keepassx supports autotype on linux (x11 window system) already.
You might be interested in my autotype implementations for windows [1] and mac os [2].

[1] https://github.com/keepassx/keepassx/pull/162
[2] https://github.com/keepassx/keepassx/pull/166

**Comment by TheZ3ro** [comment]
You are right but the Auto-Type in Linux works only on the sub-window (You can't select to witch app send the username/password)
Tell me if I'm wrong

And, it support Two-Channel Obfuscation?

**Comment by rockihack** [comment]
What do you mean by sub-window?
Autotype sends keypresses to the frontmost window.

No, it doesn't support "Two-Channel Obfuscation".
I think the assumption that keyloggers do not steal your clipboard is not true in most cases
and with keylogger + clipboard stealer it's trivial to circumvent the obfuscation.

**Comment by TheZ3ro** [comment]
> What do you mean by sub-window?
> Autotype sends keypresses to the frontmost window.

I mean the focused window except KeePassX (frontmost window)
It would be nice to select the Window where KeePassX will perform the auto-type

> No, it doesn't support "Two-Channel Obfuscation".
> I think the assumption that keyloggers do not steal your clipboard is not true in most cases
> and with keylogger + clipboard stealer it's trivial to circumvent the obfuscation.

Depends on the keylogger/clipoboard stealer, It will obstruct the attacker.
Anyway, It's a KeePass feature so it would be nice to have it in KeePassX
http://keepass.info/help/v2/autotype_obfuscation.html

**Comment by droidmonkey** [comment]
You can bind a hot-key to perform the autotype. When pressed it sends autotype of pre-registered entries to the current focused window. The user interface is not exactly intuitive to the new comer, but a short visual guide (wiki) could walk someone through it.

To perform autotype on the LAST selected window, simply select the window, then go to keepassx and open the entry you want to type, right click, "Perform Auto-Type".

You _must_ meet all the lib requirements in the readme in order to build keepassx with auto-type enabled.

**Comment by TheZ3ro** [comment]
On multiple-desktop environment, the last selected window is limited to the current window (on my XFCE this is the behaviour of the original keepassx fork).

I've compiled keepassx with all the library installed but I can't see the option "perform auto-type" when Right-clicking on a database entry.

For the visualguide/wiki  we can talk about that in the "future" issue #40

**Comment by rockihack** [comment]
Are you sure `libxtst-dev` is installed?

It is missing in the dependency list:
`
sudo apt-get install build-essential cmake libmicrohttpd-dev libxi-dev qtbase5-dev libqt5x11extras5-dev qttools5-dev qttools5-dev-tools libgcrypt20-dev zlib1g-dev
`

**Comment by TheZ3ro** [comment]
Changing the Issue to address this PRs https://github.com/keepassxreboot/keepassx/issues/20#issuecomment-251161145

**Comment by rockihack** [comment]
@TheZ3ro You probably want to merge my pull requests into a feature branch to test the build process and review the changes. If you got a problem write a comment here.

**Comment by TheZ3ro** [comment]
Sure!

I'm having some problem setting up the building environment on Windows, maybe you have some tip
https://groups.google.com/forum/#!topic/keepassx-reboot/yV__ujozMtI

**Comment by droidmonkey** [comment]
I believe this issue can be closed with the integration of PR #63

**Comment by TheZ3ro** [comment]
I'm closing this :wink:
