### ISSUE TITLE
Default folder for open dialog should be set to home directory

### ISSUE THREAD

**Issue by jsoref** [keepassxreboot/keepassxc#200]
## Expected Behavior
Default folder for open dialog should be set to home directory

## Current Behavior
Shows Macintosh HD

## Steps to Reproduce (for bugs)
1. Install KeePassXC.app (first time)
2. Open it
3. Tap the open button

## Your Environment
* KeePassXC 2.1
* macOS

**Comment by phoerious** [comment]
Is KeePassXC still using your disk root folder as default folder? For me it's showing the current working directory or the most recently used folder.

**Comment by jsoref** [comment]
Probably. Have you used a new profile, or trashed your preferences? I'm going to be installing it on another computer with a new account shortly, and I might try taking my preferences at some point...

**Comment by phoerious** [comment]
KeePassXC saves the last directory you used. Which folder is used depends mostly on your platform's file dialog.

**Comment by andrewduffey** [comment]
Saving the last directory used should not be done. The use case where this is not ideal is if you are using a keyfile to unlock your database. It defeats the whole purpose of locking the database.

**Comment by TheZ3ro** [comment]
@andrewduffey in the option you can disable "Remember last database" and "Remember last keyfile and security dongle used".

Anyway, you should store the keyfile on a different drive and never lock a database with *only* a keyfile.
It's pretty easy to find all keyfile on a drive and try them all to unlock a db.

**Comment by jsoref** [comment]
Note: I'm not trying to impact the behavior of *second run* (where a path could/couldn't be remembered). I'm only interested in the behavior of *first run* -- where the root of a computer is never the right answer.
