### ISSUE TITLE
Raspberry Pi build?

### ISSUE THREAD

**Issue by thearkadia** [keepassxreboot/keepassxc#2002]
Could we have a Raspberry Pi build? I'm starting to use a pi based computer as one of my primary devices so it'd be nice to be able to use KeePassXC on it

**Comment by hifi** [comment]
Raspbian has builds of KeePassXC for Raspberry Pi in their repos:

http://archive.raspbian.org/raspbian/pool/main/k/keepassxc/

That's likely only available if you run the testing version of Raspbian. Other distributions for the Pi may have it available as well.

**Comment by droidmonkey** [comment]
You can also use snaps on rasbian
