### ISSUE TITLE
Password input box not recognized as password input by ibus engines

### ISSUE THREAD

**Issue by rugk** [keepassxreboot/keepassxc#2004]
## Expected Behavior

Hide password.

## Current Behavior

![grafik](https://user-images.githubusercontent.com/11966684/40590628-1812c7f6-6202-11e8-942f-d7d8f45d30ab.png)

## Steps to Reproduce (for bugs)

1. Install and setup ibus-typing-booster.
2. Enter your password into the password input field when the database is locked.

## Context

See https://github.com/mike-fabian/ibus-typing-booster/issues/37 for the bug report at ibus-typing-booster and their information.

Most notably, it _does_ work as expected with KeePassX.

## Debug Info

KeePassXC - Version 2.3.3
Revision: 0a155d8

Bibliotheken:
- Qt 5.10.1
- libgcrypt 1.8.2

Betriebssystem: Fedora 28 (Workstation Edition)
CPU-Architektur: x86_64
Kernel: linux 4.16.11-300.fc28.x86_64

**Comment by droidmonkey** [comment]
This likely has nothing to do with us and everything to do with Qt5. The password fields are properly declared as such and the code that handles them has not changed since KeePassX.

**Comment by TheZ3ro** [comment]
We should report this upstream to the Qt folks

**Comment by rugk** [comment]
Okay, so if you do so, please link the issue.

**Comment by mike-fabian** [comment]
On Fedora 34, with these versions of keepassxc and qt5:

keepassxc-2.6.6-1.fc34.x86_64
qt5-qtbase-gui-5.15.2-15.fc34.x86_64

it works correctly, input methods are correctly disabled in the password entry field.
