### ISSUE TITLE
Broken theme with wayland backend

### ISSUE THREAD

**Issue by shoetten** [keepassxreboot/keepassxc#2006]
I'm running Gnome 3.28.2 with wayland. I upgraded Qt5 from 5.10.1 to 5.11.0, which causes a broken theme and all kinds of other UI glitches. Also copy / paste is broken, due to the wayland sandboxing.
I think this is caused because Qt 5.11 changed the default platform plugin from xcb to wayland.

If i run `keepassxc -platform xcb` everything works fine.

I'm sorry if this is a duplicate or an upstream bug, but i did not see this reported anywhere else and since other qt apps (like vlc) handle this fine, my first guess is that the bug somehow relates how KeepassXC handles wayland.

## Expected Behavior

![keepassxc-xorg](https://user-images.githubusercontent.com/1785212/40652647-55757234-6328-11e8-8a80-4de2ac08359d.png)

## Current Behavior

![keepassxc-wayland](https://user-images.githubusercontent.com/1785212/40652656-60ed2ba2-6328-11e8-9781-91506d434f6b.png)
![keepassxc-wayland small](https://user-images.githubusercontent.com/1785212/40811185-cb3180be-651f-11e8-9c88-02cc6dad8320.gif)

## Workaround

Run keepassxc with the `keepassxc -platform xcb` flag or downgrade qt to v5.10.1

Maybe a temporary solution would be to change the .desktop file to run keepassxc with the `-platform xcb` flag by default for now.

## Steps to Reproduce (for bugs)

1. Install Qt version 5.11
2. Start keepassxc

 \- OR -

1. Install Qt version 5.10
2. Run `keepassxc -platform wayland`

## Debug Info
KeePassXC - Version 2.3.3
Revision: 0a155d8

Libraries:
- Qt 5.11.0
- libgcrypt 1.8.2

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 4.16.11-1-ARCH

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by hifi** [comment]
That looks more like wrong/unexpected theme rather than broken.

**Comment by droidmonkey** [comment]
This is what the env var QT_QPA_PLATFORMTHEME is for. Recommend setting that to xcb.

**Comment by shoetten** [comment]
I updated the original post to include a short screencapture of the broken UI state.

**Comment by chrisberkhout** [comment]
For me this breaks clipboard functionality as well as the UI.

**Comment by janvlug** [comment]
See also:
https://github.com/keepassxreboot/keepassxc/issues/2973
https://bugzilla.redhat.com/show_bug.cgi?id=1825630
