### ISSUE TITLE
Switch between open databases

### ISSUE THREAD

**Issue by pquerner** [keepassxreboot/keepassxc#2008]
## Expected Behavior
Allow easier switches between open databases.

## Current Behavior
Is not a feature.

## Possible Solution
Add the feature.

## Context
Having open multiple databases (Tabs) in one keepassxc instance is nice, but it would be better if you would allow better switching through the open databases.

On Mac the default hotkey is CMD+1...0, which switches you to open tabs in the current program (which is in focus)

## Debug Info
KeePassXC - Version 2.3.3
Revision: 0a155d8

Libraries:
- Qt 5.9.3
- libgcrypt 1.8.2

Operating system: macOS High Sierra (10.13)
CPU architecture: x86_64
Kernel: darwin 17.5.0

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by pquerner** [comment]
Does that work on Windows? On Mac it doesnt.

**Comment by varjolintu** [comment]
For some reason CTRL+TAB has never worked on macOS.

**Comment by kmohrf** [comment]
it would be nice to have <kbd>Ctrl</kbd>+<kbd>PgUp</kbd> and <kbd>Ctrl</kbd>+<kbd>PgDn</kbd> implemented like most browsers, terminal emulators and others tools have. I didn’t know <kbd>Ctrl</kbd>+<kbd>Tab</kbd> was a thing but the other two keyboard shortcuts seem intuitive to me.

**Comment by droidmonkey** [comment]
This is nothing new, in fact we don't control that behavior at all. Qt handles the shortcut to switch tabs within the tab widget that we use.

**Comment by pquerner** [comment]
src: https://stackoverflow.com/a/45387865
```
void MainWindow::bootStrap()
{
    // create shortcut
    QShortcut *shortcut = new QShortcut(QKeySequence(Qt::CTRL + Qt::Key_Q), this);

    // connect its 'activated' signal to your function 'foo'
    QObject::connect(shortcut,    &QShortcut::activated,
                     this,        &MainWindow::foo);
}

// somewhere in the code, define the function 'foo'
void MainWindow::foo()
{
    qDebug() << "Ctrl+Q pressed.";
}
```

Maybe intercept CTRL+TAB (and CTRL+SHIFT+TAB) and set the focus manually?

**Comment by varjolintu** [comment]
Actually it's `Qt::Key_Meta` in macOS instead of `Qt::CTRL`. But it still doesn't work combined with `Qt::Key_Tab` even if set as a new shortcut.

**Comment by erikjoling** [comment]
I would expect CTRL + Page Up / Page Down to switch between database tabs. This is default behavior on KeePass 2.x (Windows). I think this is a basic convention as Firefox also uses this shortcut to switch between tabs.

**Comment by varjolintu** [comment]
@erikjoling Laptops rarely can use Page Up / Page Down as easily as Tab / Shift+Tab. Using Page Up / Down definitely shouldn't be the default shortcut. Firefox also uses Ctrl Tab / Ctrl Shift+Tab as default on all OS's.

**Comment by jerome-tgl** [comment]
The issue has been closed yet I'm still unable to switch tabs on KeppPassXC 2.4.3 running on MacOS. Pressing Ctrl/Cmd + Tab/PgUp/PgDn does nothing. Am I missing something?

**Comment by droidmonkey** [comment]
Just testing CMD+PGUP/PGDN on macOS 10.14 and it worked flawlessly.

**Comment by jerome-tgl** [comment]
> Just testing CMD+PGUP/PGDN on macOS 10.14 and it worked flawlessly.

You're right, my bad.

**Comment by erikjoling** [comment]
It doesn't work for me if the focus is in the search field. I have to tab out of it and then I can use CTRL + TAB (on linux elementaryOS)

**Comment by droidmonkey** [comment]
That must be a limitation of Linux keyboard shortcut handling because CTRL+TAB and CTRL+SHIFT+TAB are defined at the application level to switch tabs.

**Comment by erikjoling** [comment]
You're probably right :)

**Comment by dancojocaru2000** [comment]
Any idea wht Ctrl+Tab isn't possible on macOS? 

It seems very weird for the keyboard shortcut to be Ctrl + PgUp/PgDown, since apart from the [keyboard with numeric pad](https://www.apple.com/shop/product/MK2C3LL/A/magic-keyboard-with-touch-id-and-numeric-keypad-for-mac-models-with-apple-silicon-us-english) Macs don't even have PgUp/PgDown keys.

**Comment by varjolintu** [comment]
> Any idea wht Ctrl+Tab isn't possible on macOS?
> 
> It seems very weird for the keyboard shortcut to be Ctrl + PgUp/PgDown, since apart from the [keyboard with numeric pad](https://www.apple.com/shop/product/MK2C3LL/A/magic-keyboard-with-touch-id-and-numeric-keypad-for-mac-models-with-apple-silicon-us-english) Macs don't even have PgUp/PgDown keys.

It must be some Qt restriction. I've tried everything and still cannot get it to work.
