### ISSUE TITLE
Add a commandline interface

### ISSUE THREAD

**Issue by nabeelomer** [keepassxreboot/keepassxc#201]
For accessing passwords over SSH.

**Comment by TheZ3ro** [comment]
This can be an extension of `kdbx_extract` 
https://github.com/keepassxreboot/keepassxc/blob/develop/utils/kdbx-extract.cpp

**Comment by louib** [comment]
@nabeelomer what would be the minimum set of commands for your use-case? Would the set of commands supported by KeePass be enough?

http://keepass.info/help/v2_dev/scr_sc_index.html

**Comment by nabeelomer** [comment]
@louib The set supported by KeePass is enough, I just want to be able get my passwords over SSH, I don't even need to be able to write to the database.

**Comment by louib** [comment]
I'll close this one now that we have a first basic version of the CLI, that allows fetching passwords. New commands could be added as separate issues.
