### ISSUE TITLE
SEGFAULT on when selecting two groups

### ISSUE THREAD

**Issue by theScrabi** [keepassxreboot/keepassxc#2012]
Version 2.3.3 from the ubuntu PPA repository crashes on a linux mint 18.3 x64 if you select two groups. appimage and flatpack versions work.

## Expected Behavior
No Segfault

## Current Behavior
SEGFAULT

## Steps to Reproduce (for bugs)
1. Open keepassxc
2. click on a gropu
3. click on another group -> SEGFAULT

## Debug Info

KeePassXC - 2.3.3
Revision: 0ppa1~xenital1

Enabled extensions:
- keepassxc for firefox

**Comment by phoerious** [comment]
It's a know bug in Qt 5.5. Please use the Snap or our AppImage.

**Comment by theScrabi** [comment]
The problem with snap/flatpack/appimage is that I can not use them with the [keepassxc-browser plugin](https://addons.mozilla.org/en-US/firefox/addon/keepassxc-browser/?src=search). So far it did not work. Maybe I'm overseeing something here.

**Comment by phoerious** [comment]
Snap does not support KeePassXC-Browser, but the AppImage does.

**Comment by theScrabi** [comment]
ah right thank you :)
