### ISSUE TITLE
Include wordlists for different languages

### ISSUE THREAD

**Issue by juhi24** [keepassxreboot/keepassxc#2013]
Comprehensive word lists for several languages [are available](https://github.com/redacted/XKCD-password-generator#additional-languages) in compatible format. I hope some of those could be included out of the box for use with the passphrase generator.

## Expected Behavior
Word lists for several languages are available "out of the box" and ready to be selected in the passphrase generator.

## Current Behavior
Only one wordlist installed by default.

## Possible Solution
Review (check for too short words etc.) and include [word lists from xkcdpass](https://github.com/redacted/XKCD-password-generator#additional-languages). Most of those should be available under compatible licenses.

## Context
Brute force attacks become more difficult if not everyone uses the same wordlist. Passphrases are easier to remember in native language.

**Comment by phoerious** [comment]
We could ship multiple lists and show the one in the user's native language first.

**Comment by webafrancois** [comment]
I submit a new proper french words list in this post : 
https://github.com/redacted/XKCD-password-generator/issues/115
Because many mistakes and duplicates

**Comment by droidmonkey** [comment]
Duplicate (and would be handled by) #989
