### ISSUE TITLE
New entries not inheriting group icon

### ISSUE THREAD

**Issue by JoelleEmmily** [keepassxreboot/keepassxc#2016]
When adding new entry into a group with a defined icon, the new entry does not auto-inherent the group’s defined icon.

**Comment by hifi** [comment]
Confirmed KeePass 2 does indeed inherit custom group icon when creating entries. Sub-groups do not inherit the parent group icon.

This should be an easy to fix. Thank you for the report.

**Comment by kneitinger** [comment]
This appears to work on `develop` (tested on 2653250)

### Test steps
- Enable `Use group icon on entry creation` option in `Tools -> Settings -> General -> Entry Management` 
![2018-10-08_21-20-06](https://user-images.githubusercontent.com/5200550/46646725-9ef4f800-cb40-11e8-8f1b-847144524247.png)
- Created group "Icon Inherit Test" with console icon
- Created entries "Foo" and "Bar" without navigating to the "Icon" tab.
- Entries have console icon of parent group ![2018-10-08_21-19-53](https://user-images.githubusercontent.com/5200550/46646771-ed09fb80-cb40-11e8-8a2b-9873fc1105aa.png)

**Comment by droidmonkey** [comment]
Yes, I think this was fixed inadvertently in a refactor.
