### ISSUE TITLE
Question about open anyway implies no means no to opening, but it isn't

### ISSUE THREAD

**Issue by jsoref** [keepassxreboot/keepassxc#202]
## Expected Behavior
File is locked by another application.
[Open for Modifications] or [Open Readonly]

## Current Behavior
The database you are trying to open is locked by another instance of KeePassXC.
Do you want to open it anyway? Alternatively the database is opened read-only.

## Steps to Reproduce (for bugs)
1. Open KeePassX.app
2. Open a database
3. Open KeePassXC.app
4. Open the same database

## Your Environment
* KeePassXC 2.1
* macOS

**Comment by phoerious** [comment]
This confuses me too.

**Comment by droidmonkey** [comment]
Suggested reword: "The database you are trying to open is locked by another instance of KeePassXC. Do you want to open it anyway in read-only mode?"

Yes -> Open in read-only mode
No -> Cancel the load and close the database tab

**Comment by phoerious** [comment]
Would be a solution, but it's still too indirect and takes longer mental processing on the user side. Putting the action directly in the button text would be better.

**Comment by droidmonkey** [comment]
OK so:

"The database you are trying to open is locked by another instance of KeePassXC."

1. Open in read-only mode
2. Cancel

**Comment by jsoref** [comment]
I think you can use "Open read-only"

**Comment by tobiasboyd** [comment]
I agree this has always been confusing, but isn't the problem that neither choice is what a user would typically expect from "no" ? It seems to me like the two buttons could actually be labeled 

* Open Read-only
* Open Normally

and also offer a go back / cancel

(though we might want to add some sort of warning about corruption to the dialog?)

**Comment by droidmonkey** [comment]
You definitely don't want to allow opening normally as that would allow two instances to modify the same file.
