### ISSUE TITLE
HotKey/Text Replacement

### ISSUE THREAD

**Issue by NicWow** [keepassxreboot/keepassxc#2024]
## Expected Behavior

A user would open an entry and add a hot key or text replacement for the password and username. It would work the same way as Auto-Fill and be opt-in only. This way users can enter passwords within apps, in un-supported browser, e.c.t.
You could also select use title, username, or other attribute with an added "*" or ** at the end so if I had an entry called "github" if I typed "github**" then it would execute the same thing as Auto-Fill does.
Of course this could all be customized by the user.

You could also import them with CSV

## Current Behavior

Currently it only has auto-fill and Browser Integration.

## Possible Solution

There are many open-source keyloggers, hot key, and Text Replacement software.
If you need help finding some then ask me in the comments.
I'm not a programmer so not sure about the execution.

## Context

I use TOR and with TOR you aren't supposed to add extensions for security and privacy purposes. This would help make it easier for TOR users.

I know I personally also only use a select few of my passwords on a daily basis so the list of text replacements and hot keys would be short.

**Comment by droidmonkey** [comment]
Im confused, why doesn't Auto-Type work for you? You can define any number of a typing sequence using all sorts of parameters.

**Comment by NicWow** [comment]
@droidmonkey Does it work with TOR?

**Comment by droidmonkey** [comment]
Ctrl+h might be a shortcut in the browser. Use a more complicated shortcut like ctrl+alt+h

**Comment by droidmonkey** [comment]
TOR support added with #2392
