### ISSUE TITLE
Feature: Use logo database for Icon

### ISSUE THREAD

**Issue by NicWow** [keepassxreboot/keepassxc#2025]
## Expected Behavior

Basically use a logo database for entry icons.
[Example Of This](https://instantlogosearch.com/)
It would check the entry URL and find the logo in the database that matched it.
This would be opt in for privacy reason since many users won't want to make a request for the image (unless it is pre-downloaded which is also an option). 
It would have have the option for using Tor and/or a proxy for looking up the images.

## Current Behavior

Not sure what it currently does for icons. It seems to just have some basic images.

## Possible Solution

Like I said in "expected behavior" it could use a platform like Instant Logo search 
I am not sure of the legal ramifications so you should talk to a lawyer before trying this.
You could also create your own database that is community lead.

The URL structure of searches for Instant Logo Search: 
https://instantlogosearch.com/?q={SearchKeyword]
(replace {SearchKeyword} with the search)

The URL structure for images seems to be:
instantlogosearch.ils.netdna-cdn.com/svg/instantlogosearch/{company-name}.svg

Example: [instantlogosearch.ils.netdna-cdn.com/svg/instantlogosearch/Coca-Cola.svg
](instantlogosearch.ils.netdna-cdn.com/svg/instantlogosearch/Coca-Cola.svg)

It could use several different things like Title and URL to find logo. It would look it up and suggest the most relevant option.

If it isn't right then the user could import an image by the URL and searching for the company in their web browser.

## Context

Would make it a **TON** easier to find passwords and would make the overall feel of the manager better.

**Comment by droidmonkey** [comment]
The current favicon downloader handles this when you input a url. With my new PR to load multiple icons at once you can very easily download a pack and load them into your database.
