### ISSUE TITLE
Wrong version detection when using Windows installer of v2.3.3

### ISSUE THREAD

**Issue by digihash** [keepassxreboot/keepassxc#2026]
## Expected Behavior
When I start the Windows installer on Windows 10 x64, a screen appears with the question if I want to uninstall the old version before uninstalling the new one. This dialog also shows which version is already installed which is for example "KeePassXC v2.3.1

## Current Behavior
The dialog opens, asking the same question as described above, but a wrong message is used about the current version: "KeePassXC v2.3.3 is already installed". But in my case KeePassXC v2.3.1 was still installed. 

## Possible Solution
The message should say something as follows: "KeePassXC v2.3.1 is currently installed. Do you want to uninstall the old version before installing the new one?"

## Steps to Reproduce (for bugs)
1. Have version 2.3.1 installed on your Windows machine (at least this was my case)
2. Download current v2.3.3 installer for  [https://github.com/keepassxreboot/keepassxc/releases/download/2.3.3/KeePassXC-2.3.3-Win64.exe](Windows x64)
3. Start the installer
4. See the wrong message

## Context
I tried this on my Windows 10 x64 system which had KeePassXC v2.3.1 installed.

## Debug Info
KeePassXC - v2.3.3 installer

Libraries:
- LIBS

Operating system: Windows 10 x64 build 16299
CPU architecture: Intel i7-7820HQ

**Comment by droidmonkey** [comment]
We are moving away from the NSIS installer in 2.4 so this will become a non-issue. Leaving open for reminder.

**Comment by digihash** [comment]
What are you moving to if I may ask?

**Comment by droidmonkey** [comment]
WiX, also known as MSI

**Comment by phoerious** [comment]
Side note: we do not detect the version. The version number just happens to be baked into the product name (for stupid technical reasons). So what the installer really wants to tell you is simply "KeePassXC is currently installed".

**Comment by droidmonkey** [comment]
There is a detected issue in the MSI installer (found via Orca tool) that the detectable version is equal to the current version and it should be less than to allow the MSI installer to do a "repair" install.
