### ISSUE TITLE
Browser intergration fails with osx 10..13.5

### ISSUE THREAD

**Issue by gshields** [keepassxreboot/keepassxc#2027]
## Steps to Reproduce (for bugs)

1. install on osx 10.13.5 with firefox 60.0.1 and chrome 67.0.3396.62
2. install with brew current keepassxc
3.enable browser integration
4. icon on menu bar, reboot and still do not have integration

## Debug Info

KeePassXC - VERSION
Revision: REVISION

Libraries:
- LIBS

Operating system: OS
CPU architecture: ARCH
Kernel: KERNEL

Enabled extensions:
- EXTENSIONS

**Comment by gshields** [comment]
Icon did appear, but message of:

KeePassHttp-Connector has encountered an error:

Unable to connect to KeePassHttp

**Comment by weslly** [comment]
Which KeepassXC version are you using?

**Comment by varjolintu** [comment]
Sounds like you are using the old browser extension (chromeipass or KeePassHTTP-Connector). You need to install [KeePassXC-Browser](https://chrome.google.com/webstore/detail/keepassxc-browser/oboonakemofpalcgghocfoadofidjkkk) instead. Older keepasshttp-based extension won't work with the new browser integration.

Also, please check that you are using KeePassXC 2.3.x, not 2.2.x.

**Comment by gshields** [comment]
I have 2.3.3. of the application and it is a documentation issue

I followed the FAQ of:
https://keepassxc.org/docs/#faq-browser-howto
Which leads to the help page to install the plugin of:
https://github.com/smorks/keepasshttp-connector/blob/master/documentation/KeePassHttp-Connector.md
points to the wrong plugin
https://chrome.google.com/webstore/detail/keepasshttp-connector/dafgdjggglmmknipkhngniifhplpcldb

The page should point to what you showed as the correct plugin which is:
https://chrome.google.com/webstore/detail/keepassxc-browser/oboonakemofpalcgghocfoadofidjkkk

Thanks for you help

**Comment by varjolintu** [comment]
The FAQ page already links to [https://keepassxc.org/docs/keepassxc-browser-migration/](https://keepassxc.org/docs/keepassxc-browser-migration/) which is the correct page for newer browser integration. This is mentioned right after the legacy browser integration text.
