### ISSUE TITLE
tray icon does not appear on ubuntu 18.04

### ISSUE THREAD

**Issue by uocxp** [keepassxreboot/keepassxc#2028]
i am using ubuntu 18.04 with gnome (3.28.1) and i checked the options in keepassxc to hide windows to system tray when minimized but the icon does not appear in the tray bar.

## Expected Behavior
program minimize and tray icon appears

## Current Behavior
tray icon does not appear

## Steps to Reproduce (for bugs)
on ubuntu 18.04 install keepassxc from the official repo and check the options to minimize to tray

## Debug Info
keepassxc 2.3.3

Operating system: Ubuntu 18.04
CPU architecture: x64
Kernel: 4.15.0-22-generic

Enabled extensions:
- firefox browser add-on

**Comment by TheZ3ro** [comment]
Why you closed this? It's fixed? What was the problem?

**Comment by uocxp** [comment]
The icon had the same color of the top bar so i though it was not there. I switched back to keepass2 i missed the feature "adding credentials from the browser add-on to the password-database" besides "keyboard-shorcut for hiding/unhiding usernames and passwords"
