### ISSUE TITLE
gpg-agent integration on MacOS (High Sierra)

### ISSUE THREAD

**Issue by drew-kun** [keepassxreboot/keepassxc#2029]
Hi! Its not an issue but question/feature_request.

The KeepassXC ssh-agent is an awesome feature.

But what if I have a kinda hybrid setup using the gpg-agent instead of an ssh-agent (to authenticate against some ssh hosts using my gpg-authentication subkeys, stored in my gpg keychain) and use some normal ssh keys to authenticate against a bunch of other ssh servers (like github, gitlab, bitbucket etc..)

My gpg-agent continuously stores all the gpg authentication subkeys. 

It would be nice to have the normal (non-gpg) ssh keys to be dynamically added from the KeepassXC database to gpg-agent(and removed from it when db is locked), the same way as it works with ssh-agent.

I have tested it on MacOS High Sierra and KPXC does not seem to add the keys if to gpg-agent when used instead of ssh-agent. Could it be considered as something possible in KeepassXC? Or is it just weird idea?

**Comment by hifi** [comment]
gpg-agent has support to emulate ssh-agent and it should be compatible with KeePassXC but if you have ssh-agent running and `SSH_AUTH_SOCK` environment variable points to ssh-agent the keys will be added to ssh-agent.

gpg-agent also needs some configuration to expose the ssh-agent functionality.

**Comment by drew-kun** [comment]
Well, so you saying that with correct configuration it should work as I have described..

Here is what I have done:

** ~/.gnupg/gpg-agent.conf** (Enabled the ssh-support for gpg-agent):
```
pinentry-program /usr/local/MacGPG2/libexec/pinentry-mac.app/Contents/MacOS/pinentry-mac
default-cache-ttl 600
max-cache-ttl 7200
enable-ssh-support
```

**~/.zshrc** (Pointed the ssh-agent to gpg-agent socket):
```
export "GPG_TTY=$(tty)"
export "SSH_AUTH_SOCK=${HOME}/.gnupg/S.gpg-agent.ssh"
```
So:
```
$ echo $SSH_AUTH_SOCK
/Users/drew/.gnupg/S.gpg-agent.ssh
```
**~/.gnupg/sshcontrol** (Specified gpg authentication subkeys to be added to gpg-agent)
```
2AA86DAECA0C5F723522BE664E36C806030BE66A
```

So it was instantly successfully added to gpg-agent:
```
# Before modifying ~/.gnupg/sshcontrol:
$ssh-add -l
The agent has no identities.

# After modifying ~/.gnupg/sshcontrol: 
$ ssh-add -l
256 SHA256:jOy+gonBde1luKT1/iVKzhKqs/kcZnLTqTdRqL8b7DbBes (none) (ED25519)
```

So all good, now the gpg-agent works as ssh-agent through `SSH_AUTH_SOCK`
I can even add non-gpg ssh keys manually:
```
$ ssh-add ~/.ssh/id_ed25519
Enter passphrase for /Users/drew/.ssh/id_ed25519:
Identity added: /Users/drew/.ssh/id_ed25519 (drew@localhost.localdomain)
Certificate added: /Users/drew/.ssh/id_ed25519-cert.pub (localhost.localdomain-drew)

$ ssh-add -l
256 SHA256:TdRqjOy+gonBuKT1/inLTqVKz/kde1lcZL8b7DbhKqs (none) (ED25519)
256 SHA256:GUvq6TdiBHgCsa1ODlezT9OP+4JQ/UZ8Odl9sX3okC3 drew@localhost.localdomain (ED25519)
```

So as I can see gpg-agent is running and emulating ssh-agent, but when I unlocked my KPXC db, then I have expected my github key to be added to ssh-agent (which is now gpg-agent). But it was not added. Any ideas why? Am I missing anything?

**Comment by drew-kun** [comment]
It appears to me that once I unlock KeePassXC db, then the system's native ssh-agent is being triggered to start and the keys are added to ssh-agent instead of gpg-agent... 
But `ssh-add -l` still refers to gpg-agent, because of `SSH_AUTH_SOCK=/Users/drew/.gnupg/S.gpg-agent.ssh` that's why I see no new keys from KeepassXC. And I don't know how to prove it or how to fix this behaviour :(

**Comment by hifi** [comment]
I believe when you start KeePassXC it's not using your `~/.zshrc` profile as the MacOS windowing system doesn't start as a sub-process of zsh. You would need to figure out how you can disable ssh-agent from starting up and adding a global environment variable that affects all processes, not just zsh.

**Comment by drew-kun** [comment]
No luck so far.. :(

Tried to set env vars in `/etc/profile`, but it's just ignored.

Tried with `launchd`:

```
$ launchctl setenv SSH_AUTH_SOCK ${HOME}/.gnupg/S.gpg-agent.ssh
$ launchctl getenv SSH_AUTH_SOCK
/Users/drew/.gnupg/S.gpg-agent.ssh
```
But then:
```
$ echo $SSH_AUTH_SOCK
/private/tmp/com.apple.launchd.IjNASGcnxM/Listeners
```
So it seems like the variable set with launchd is ignored...

**Comment by drew-kun** [comment]
Found this [2-years old question](https://superuser.com/questions/1120480/cant-change-ssh-auth-sock-with-launchctl-setenv) for absolutely same problem... Wonder if anyone have ever made it work on MacOS?

**Comment by drew-kun** [comment]
[Solution](https://stackoverflow.com/questions/135688/setting-environment-variables-in-os-x) which states that  "if you want to set variables that are available in all GUI apps, your only option is `/etc/launchd.conf`" is not supported anymore since Yosemite. Tried it - doesn't work.

[Solution](https://stackoverflow.com/questions/25385934/setting-environment-variables-via-launchd-conf-no-longer-works-in-os-x-yosemite) based on creating .plist with the same `launchctl` commands unfortunatly has the same results (which is kinda expected):

```
$ echo $SSH_AUTH_SOCK
/private/tmp/com.apple.launchd.ozshKTFr3V/Listeners
```
I am assuming that at least on MacOS High Sierra it is impossible to make KeePassXC add ssh keys from kdbx to gpg-agent...

**Comment by hifi** [comment]
There must be a way to completely prevent ssh-agent from starting. Something sets that SSH_AUTH_SOCK env variable and that something can be somehow disabled.

Have you tried to disable the agent somehow like this (found this somewhere, might not work in latest MacOS anymore):
```
launchctl unload /System/Library/LaunchAgents/org.openbsd.ssh-agent.plist
```

**Comment by drew-kun** [comment]
Yeah, did this...  To be precise:
```
launchctl unload /System/Library/LaunchAgents/com.openssh.ssh-agent.plist
```
And although, the plist is unloaded, once I start KeepassXC the ssh-agent runs again... But the plist is still unloaded. I even tried to rename it, to make sure it's not automatically loaded.

**Comment by drew-kun** [comment]
Well, I may be wrong, but it looks as if KeePassXC sets SSH_AUTH_SOCK and starts `ssh-agent` once I unlock database or once I lock it (if I kill ssh-agent when database is unlocked) in order to remove the keys. Does it sound like possible issue?

**Comment by drew-kun** [comment]
Tried something radical:
```
sudo mv /usr/bin/ssh-agent /usr/bin/ssh-agent_orig
```
KeepassXC hangs forever when trying to unlock db.

Just for fun I did the following:
```
ln -s /usr/local/bin/gpg-agent /usr/bin/ssh-agent
```
KeepassXC still hangs forever when trying to unlock db.

**Comment by drew-kun** [comment]
Just tried it on Kali and it works almost as expected although not exactly.. It uses `gpg-agent` and doesn't try to set `ssh-agent` which is cool, but when unlocking the KeepassXC database it asks (I guess through ??`pinentry`??) to enter the passphrases for each enabled key (which defeats the purpose of using keepassxc for this case).

Once I've typed the passphrase it adds the keys to gpg-agent, but once I lock the database, it doesn't remove the keys from the gpg-agent like it does with ssh-agent...

**Comment by hifi** [comment]
> Well, I may be wrong, but it looks as if KeePassXC sets SSH_AUTH_SOCK and starts ssh-agent once I unlock database or once I lock it (if I kill ssh-agent when database is unlocked) in order to remove the keys. Does it sound like possible issue?

Bear in mind if you remove the zsh profile overrides for SSH_AUTH_SOCK then ssh-add should behave exactly like KeePassXC. We don't start any agent, it's a MacOS trigger when the socket is first opened by an application or something along those lines.

**Comment by hifi** [comment]
I'm going to close this issue as gpg-agent is not fully ssh-agent compatible and there is nothing we can do about it. Adding upstream label for later reference.

Thanks.
