### ISSUE TITLE
shortcut to hide/unhide usernames and passwords

### ISSUE THREAD

**Issue by uocxp** [keepassxreboot/keepassxc#2031]
is there any shortcut to hide/unhide the usernames and passwords like in keepass2 ? 

## Debug Info
KeePassXC - Version 2.3.3
Revision: 0a155d8

Libraries:
- Qt 5.9.5
- libgcrypt 1.8.1

Operating system: Ubuntu 18.04 LTS
CPU architecture: x86_64
Kernel: linux 4.15.0-22-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

Libraries:
- LIBS

Operating system: OS
CPU architecture: ARCH
Kernel: KERNEL

**Comment by droidmonkey** [comment]
There is no way to hide usernames, but you can toggle password hiding in the settings.

**Comment by uocxp** [comment]
the options in settings (in security tab) are not working for me. neither unhiding passwords in preview pannel nor toggling passwords in klear text
![screenshot from 2018-06-05 15-17-54](https://user-images.githubusercontent.com/8387383/40978320-a5ec9430-68d3-11e8-8ad2-167c79a9995b.png)

**Comment by droidmonkey** [comment]
Do you mean that the passwords are not shown even with those settings in the screenshot?

**Comment by mmarsching** [comment]
> the options in settings (in security tab) are not working for me. neither unhiding passwords in preview pannel nor toggling passwords in klear text
> ![screenshot from 2018-06-05 15-17-54](https://user-images.githubusercontent.com/8387383/40978320-a5ec9430-68d3-11e8-8ad2-167c79a9995b.png)

I do not have this option as of version 2.4.3 - has it been removed? Is there any way to show the passwords in the listview?
