### ISSUE TITLE
Can't reconnect browser extension to KeepassXC

### ISSUE THREAD

**Issue by dpb657** [keepassxreboot/keepassxc#2033]
I somehow screwed up the connection between KeepassXC and the Chrome extension. I have remove KeepassXC and the extension but all I get is "Timeout or not connected to KeePassXC"  I have "the browser integration" turned on but nothing has fixed things.

KeePassXC - Version 2.3.3
Revision: 0a155d8

Libraries:
- Qt 5.10.1
- libgcrypt 1.8.2

Operating system: Windows 10 (10.0)
CPU architecture: x86_64
Kernel: winnt 10.0.17134

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

KeePassXC-Browser Version: 1.1.3

KeePassXC Version: unknown

**Comment by varjolintu** [comment]
Have you checked the [troubleshooting guide](https://github.com/keepassxreboot/keepassxc-browser/wiki/Troubleshooting-guide)? See if it helps to give some more info.

**Comment by dpb657** [comment]
My apologies, I somehow did not find that page when I was looking for helpful information last night. I will see if I can fix it with information from there when I get home.

Darryl Baker
Sr. System Administrator
Distributed Application Platform Services
Northwestern University
1800 Sherman Ave.
Suite 6-600 – Box #39
Evanston, IL  60201-3715
darryl.baker@northwestern.edu<mailto:darryl.baker@northwestern.edu>
(847) 467-6674
