### ISSUE TITLE
Wiki: How to debug

### ISSUE THREAD

**Issue by pquerner** [keepassxreboot/keepassxc#2035]
It would be great if a topic on how to debug this application could be written. I tried to do it with Qt Creator but failed to attach to the created app. 

If someone could point me to the right direction. I'm on a mac system at work but use Linux and Windows at home, which I'd be using then.

**Comment by varjolintu** [comment]
Simplest steps with Linux:
1) Make sure you have all the dependencies installed and you can compile the project without QtCreator. Also, install a debugger (e.g. `gdb`).
2) Open the `keepassxc/CMakeLists.txt` from QtCreator (it loads as a project). It should be Debug as default.
3) Go to Projects tab (buttons on the left panel) and check the options you want to use (WITH_XC_AUTOTYPE etc..)
4) From the menu select `Build -> Run CMake` and check if it succeeds.
5) Build the project and debug it normally.

With Windows you'll have to install QtCreator from MSYS2 and run it directly from the shell. The package should be `mingw-w64-x86_64-qt-creator`. Also, make sure you can compile the project without QtCreator so you'll have every dependency you need.

**Comment by green-nl** [comment]
Followed instructions from https://github.com/keepassxreboot/keepassxc/issues/2035#issuecomment-395407354 

First of all, *.ui files do not appear in Edit mode Projects view.

After opening ui-file via File System and trying to get to slots corresponding to some widget I've got the following error: 
> No documents matching "ui_CloneDialog.h" could be found.
> Rebuilding the project might help.
Rebuild does not help though...

Got projects view populated after adding ui-files as sources in `src/CMakeLists.txt`.

After adding sources as mentioned above, attempt to jump to a slot corresponding to a widget changes:
> The class containing "Ui::CloneDialog" could not be found in 
> /home/user/github/keepassxc/src/gui/CloneDialog.cpp.
> Please verify the #include-directives.
At the same time project builds OK.

Any ideas on what might bee wrong?

Just in case:
 * Qt Creator 4.5.2
 * Based on Qt 5.9.5 (GCC 7.3.0, 64 bit)
 * Ubuntu 18.04

**Comment by phoerious** [comment]
Do not add ui files to the sources. They are built by autouic. You need to rerun cmake and make to build them.

**Comment by kwah-gh** [comment]
@phoerious I know that they are build by autouic. As indicated (maybe not clear enough): if ui files are not mentioned explicitly as sources, Qt Creator does not recognize them as part of the project. So, why not add them?

Any suggestions on solving issue preventing jumping to widget slots from ui designer are welcome.

**Comment by droidmonkey** [comment]
I added that issue as a bug to QtCreator, I thought they fixed that issue already...
