### ISSUE TITLE
Add ability to save attachment from details panel

### ISSUE THREAD

**Issue by kampfq** [keepassxreboot/keepassxc#2039]
there is no way to download an attachement in the overview of an entry.

## Expected Behavior

when selecting an entry in the overview i'd like to extract an attachement. 

## Current Behavior

i can just double click the attachement to open it

## Possible Solution

provide similar actions than in in the detail view (edit entry, advanced, attachements). just open and download are relevant for this view.

## Steps to Reproduce (for bugs)
1. add an attachement to an entry
2. try to get it on your desktop or any other place outside keepassxc
<img width="594" alt="screen shot 2018-06-08 at 08 23 45" src="https://user-images.githubusercontent.com/7052906/41142716-f0e4bff6-6af6-11e8-9c5d-24f61f95fd50.png">

## Debug Info
KeePassXC - Version 2.3.1
Revision: 2fcaeea

Libraries:
- Qt 5.9.3
- libgcrypt 1.8.2

Operating system: macOS High Sierra (10.13)
CPU architecture: x86_64
Kernel: darwin 17.6.0

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by droidmonkey** [comment]
Good suggestion, should be simple to add a save icon in the far right.

**Comment by gucce** [comment]
Any progress on this? I recently switched from KeePassX to KeePassXC. This is an important feature to me, since I have certificate files stored in my KeePass file which I can't open now.
Is there any workaround to get download an attachment?

**Comment by droidmonkey** [comment]
Just double click the entry (or press enter) and go to the advanced tab on the left.

**Comment by phyber** [comment]
I have to look up this issue every time I need to save an attachment, since I need to do it so infrequently.

**Comment by ilogs-sepa** [comment]
Please simply add a "Save as..." Button.

**Comment by mobeigi** [comment]
Surprised this is not a feature already!

**Comment by nixpc** [comment]
I was about to suggest being able to save files / adding an attachment to KeePassXC. When looking if it already was suggested I found out that it was already a feature.

Currently it's hidden away in the advanced menu which I pretty much never have to look at. Definitely should make this feature more clear by adding an attachment tab (or simply make the advanced tab clickable even when there are no attachments).
