### ISSUE TITLE
Dark Mode on macOS 10.14 makes texts barely readable

### ISSUE THREAD

**Issue by neroniaky** [keepassxreboot/keepassxc#2040]
When using the macOS 10.14 "Dark Mode" it changes the background color to a dark grey, which makes it really hard to read most texts. (see attached screenshot)

<img width="790" alt="bildschirmfoto 2018-06-08 um 09 31 37" src="https://user-images.githubusercontent.com/11535793/41145243-c84424a2-6aff-11e8-8b03-c86142646dba.png">

## Expected Behavior

1. Either background color does not change, 
2. or the text color changes too

## Current Behavior
Background color changes but text color does not.

## Possible Solution
See expected behaviour.

## Debug Info
KeePassXC - Version 2.3.3
Revision: 0a155d8

Bibliotheken:
- Qt 5.9.3
- libgcrypt 1.8.2

Betriebssystem: macOS 10.14
CPU-Architektur: x86_64
Kernel: darwin 18.0.0

Aktivierte Erweiterungen:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by phoerious** [comment]
I think this may need fixing on Qt's side.

**Comment by SVilgelm** [comment]
Ho did you enable dark mode for KeepassXC? I enabled dark mode on Mac, but KeepassXC is still in light. v2.3.4

**Comment by weslly** [comment]
@SVilgelm It needs to be compiled on Mojave.

**Comment by droidmonkey** [comment]
I read an article that Mojave wasn't "dark enough". Looks like you fixed that! /joke

**Comment by SVilgelm** [comment]
@weslly thanks

**Comment by neroniaky** [comment]
KeepassXC always uses the light mode now, so no problem with reading the text anymore. Closing.

P.S. Dark Mode would be a nice feature 😉 .

**Comment by michaellass** [comment]
> KeepassXC always uses the light mode now, so no problem with reading the text anymore. Closing.

I can't find any related change in the commit history. Can you give me a hint?

**Comment by weslly** [comment]
@michaellass the current version binaries weren't compiled under Mojave, so you won't see the broken dark mode unless you compile it yourself.

**Comment by zyv** [comment]
This issue is duplicated by #3193, which includes a workaround on how to disable broken dark mode support on Mojave.
