### ISSUE TITLE
Right-clicking on the KeePassXC icon in the Windows taskbar crashes the application.

### ISSUE THREAD

**Issue by ChurdCFG** [keepassxreboot/keepassxc#2041]
## Expected Behavior

Not sure if there's a context menu when you right click on the icon or not, but I would expect that either that menu pops up, or nothing at all happens (i.e., no crash).

## Current Behavior

Get the following memory error if I ever right-click on the KeePassXC icon:
<img src="https://user-images.githubusercontent.com/32141873/41155165-ee59384a-6aea-11e8-94af-da6a3be65dbd.png" width=50% height=50%>

## Steps to Reproduce (for bugs)

1. Open KeePassXC
2. Right-Click on the KeePassXC icon in the taskbar

## Context

I didn't see any other posts complaining about this error, so it may just be a unique configuration thing, but I figured I'd report the issue just in case.  If it helps, this is running on a Surface Pro 4 with 16GB RAM, and typically I have two KeePass databases open.  The top memory address changes depending on which tab I have selected, but the bottom address always stays the same (0x0000000000000008).

If there's any other logging information I can provide just let me know.

## Debug Info

KeePassXC - Version 2.3.3
Revision: 0a155d8

Libraries:
- Qt 5.10.1
- libgcrypt 1.8.2

Operating system: Windows 10 (10.0)
CPU architecture: x86_64
Kernel: winnt 10.0.17134

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by phoerious** [comment]
This is mysterious. I have never experience that crash.

**Comment by droidmonkey** [comment]
Does not occur for me at all
