### ISSUE TITLE
Add ability to jump to folder from search results

### ISSUE THREAD

**Issue by 3lp4dr1n0** [keepassxreboot/keepassxc#2043]
## Expected Behavior

You highlight an entry in the search result pane, the corresponding folder where the entry was found is highlighted as well in the left folder pane. 

## Current Behavior

In the search result pane, you can just see in which folder the highlighted entry is located but if you want to see which other entries are in that folder, or you just want to navigate to that folder, you need to manually navigate through all folders to get there. 

## Possible Solution

The folder is automatically selected when you click on an entry in the search results or you have the possibility either per keyboard shortcut or per right-click menu to jump to the corresponding folder where the entry lives in. 

## Context

keepass for windows do this automatically for instance. 

## Debug Info

KeePassXC - Version 2.3.3
Revision: 0a155d8

Bibliotheken:
- Qt 5.9.3
- libgcrypt 1.8.2

Betriebssystem: macOS High Sierra (10.13)
CPU-Architektur: x86_64
Kernel: darwin 17.6.0

Aktivierte Erweiterungen:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by droidmonkey** [comment]
Nice idea

**Comment by 3lp4dr1n0** [comment]
@droidmonkey will that feature be integrated in the software sometime? Without this feature, it is very hard to use the software for me with our big database. I need to spend a lot of time to find the folders I am searching for. 

Many thanks for your answer!

**Comment by droidmonkey** [comment]
Sure I will take a look at it for 2.4

**Comment by droidmonkey** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [#2043 - Right click entry -> Go to folder...](https://trello.com/c/lYN5kfu4/11-2043-right-click-entry-go-to-folder)

**Comment by droidmonkey** [comment]
I am implementing this by having it so when you double click the folder name in the search results it ends the search, takes you to that folder, and selects the corresponding entry.

**Comment by 3lp4dr1n0** [comment]
sounds great!
Am 15. Nov. 2018, 23:38 +0100 schrieb Jonathan White <notifications@github.com>:
