### ISSUE TITLE
How do I verify signatures via .digest file

### ISSUE THREAD

**Issue by I-hatethis** [keepassxreboot/keepassxc#2045]
shasum -a 256 -c /Users/name/Downloads/KeePassXC-2.3.3.dmg.DIGEST 
shasum: KeePassXC-2.3.3.dmg: 
KeePassXC-2.3.3.dmg: FAILED open or read
shasum: WARNING: 1 listed file could not be read

I have tried again and again to verify the .digest file but failed. Could you please tell me how to do it? I will soon verify the gpg signature but this is just annoying me. 

## Possible Solution
Maybe provide a video on how I can verify a .digest file not all the people that are downloading a password manager are computer nerds. Luckily I found a video on how to verify the pgp signature: https://youtu.be/x2dbrOGob8A and will be using that method soon. Also could you provide the MD5, SHA-1, and SHA-256 Hashes on your site so I could use those instead. I would rather a click put a simple shasum -a 256 command on terminal... Oh wow just figured out that turning the KeePassXC-2.3.3.dmg.DIGEST file into KeePassXC-2.3.3.dmg.txt and then go to terminal and run the command shasum -a 256 from terminal comparing the KeePassXC-2.3.3.dmg and then comparing the text file and it matched wow. Well I won't be doing all that gpg stuff then how annoying.

## Steps to Reproduce (for bugs)

1. Download the digest file
2. Go to this site https://keepassxc.org/verifying-signatures/
3. Get confused
4. Do this stupid command shasum -a 256 -c /Users/name/Downloads/KeePassXC-2.3.3.dmg.DIGEST 
shasum: KeePassXC-2.3.3.dmg: 
KeePassXC-2.3.3.dmg: FAILED open or read
shasum: WARNING: 1 listed file could not be read
5. Get even more confused

Solution: f that command
1. Change the KeePassXC-2.3.3.dmg.DIGEST into a KeePassXC-2.3.3.dmg.txt file and 
2. then run the command shasum -a 256 /Users/name/Downloads/KeePassXC-2.3.3.dmg get the SHA-256 hash and 
3. Finally compare the hash to the text file
## Context
 This issue has affected me by wasting enough time until I was able to find the answer myself and also forcing to make a Github  account with a cheap password. Fix this command shasum -a 256 -c /Users/name/Downloads/KeePassXC-2.3.3.dmg.DIGEST. It really annoys me how much time I wasted on this when I could have change the damn file to a .txt file and be done with it ughhhhh. I was trying to find a simple and fast way to verify to app but instead troubleshooted for several days.

Operating system: MacOS
CPU architecture: ?
Kernel: ?

Enabled extensions: ?

**Comment by I-hatethis** [comment]
Actually a better possible solution is to actually provide a good example on your site because this example: ("$ shasum -a 256 -c KeePassXC-$VERSION-x86_64.AppImage.DIGEST
KeePassXC-$VERSION-x86_64.AppImage: OK") does not explain anything. Instead give me a step by step procedure on how to do the basic integrity check just from example alone I had to do a bunch of research on how to find a hash and I learned to just type the shasum -a 256 command and then path to file(which is basically dragging the file onto the command line(in my case terminal). the example just created more confusion and didn't show that. And whats with this symbol "$" delete it it caused more confusion. Overall I wasted too much time on this and finally found out the the hashes match might check the gpg signature later if I actually have time.

Conclusion, improve the https://keepassxc.org/verifying-signatures/ website by giving alternate solutions to Basic integrity check like changing the .digest file into a .txt file. Showing step by step like how the website explained how to find the gpg signature it gave a okay explanation unlike the basic integrity check which gave a confusing example. But even though it gave a good explanation this video https://youtu.be/x2dbrOGob8A explained it better. The explanation of the gpg signature did have minor flaws like not linking to any gpg programs so I as the user could download and use it. Not really explaining what the gpg program is. 

Though I really got to wonder if I am one of the few users who actually downloaded the file got paranoid and tried to verify the signature. I am pretty sure most people would skip this step but I am one of the few that actually tried verifying the signature.

**Comment by phoerious** [comment]
The DIGEST file is just a text file containing the hashes. Compare them to the hash of the AppImage, not the hash of the DIGEST file.

**Comment by droidmonkey** [comment]
It is not our responsibility to train you on checksum digests and gpg signatures. As you found out, you can watch a video to give you an overview. The commands provided run perfectly fine if you put the right filename in.

**Comment by I-hatethis** [comment]
Yeah it just took me a while to figure it out. A long time. I am just still wondering why I got this error though: shasum -a 256 -c /Users/name/Downloads/KeePassXC-2.3.3.dmg.DIGEST
shasum: KeePassXC-2.3.3.dmg:
KeePassXC-2.3.3.dmg: FAILED open or read
shasum: WARNING: 1 listed file could not be read

Well whatever you closed it anyways

**Comment by droidmonkey** [comment]
Likely because you saved the digest file in a different directory than the dmg file.

**Comment by I-hatethis** [comment]
No I saved it in the same directory. The same downloads folder.

**Comment by I-hatethis** [comment]
Oh it worked, thanks.

**Comment by droidmonkey** [comment]
Ok I'll add that to the verification instructions to make sure to run the command in the same directory as the downloaded files

**Comment by droidmonkey** [comment]
I have added clarification to change directory and also put in verification instructions for WIndows: https://keepassxc.org/verifying-signatures/

**Comment by wavesurf432** [comment]
Incase it's of help at all, when changing directory, C:\Users\username\Downloads should have " around it. So to change to the Downloads folder in Powershell it would be: cd "C:\Users\username\Downloads" 

I was struggling with this till I realised that. Adding cd "C:\Users\username\Downloads" on https://keepassxc.org/verifying-signatures/ would help prevent any confusion.

Anyway, thanks for the great program!
