### ISSUE TITLE
OSX binary won't launch on 10.10 -- Dyld: code signature invalid for libsodium.23.dyLib

### ISSUE THREAD

**Issue by bjmuld** [keepassxreboot/keepassxc#2047]
OSX binary fails upon launch with details:

```
Dyld Error Message:
  Library not loaded: @executable_path/../Frameworks/libsodium.23.dylib
  Referenced from: /Applications/KeePassXC.app/Contents/MacOS/KeePassXC
  Reason: no suitable image found.  Did find:
	/Applications/KeePassXC.app/Contents/MacOS/../Frameworks/libsodium.23.dylib: code signature invalid for '/Applications/KeePassXC.app/Contents/MacOS/../Frameworks/libsodium.23.dylib'
```

## Expected Behavior
osx app should launch

## Possible Solution

code signing problem with the libsodium component.  see below:
https://stackoverflow.com/questions/41865537/how-does-apples-codesign-utility-decide-which-sha-algorithms-to-sign-a-shared

## Steps to Reproduce (for bugs)

1. Have OSX 10.10
2. Download keepassxc binary
3. attempt to launch binary

## Debug Info

KeePassXC - VERSION
Revision: REVISION

Libraries:

Operating system: OSX 10.10
CPU architecture: Amd64
Kernel: ?? ghost of steve jobs

Enabled extensions:

**Comment by yan12125** [comment]
Looks like a duplicate of https://github.com/keepassxreboot/keepassxc/issues/1671

**Comment by bjmuld** [comment]
you're right... closing
