### ISSUE TITLE
the checkboxes in Settings>Security don't align w/ the edit box/spin buttons

### ISSUE THREAD

**Issue by jsoref** [keepassxreboot/keepassxc#205]
## Expected Behavior
Buttons should align w/ edit boxes

## Current Behavior
Buttons don't align

## Steps to Reproduce (for bugs)
1. Open KeePassXC.app
2. Open Settings
3. Tap Security

## Your Environment
* KeePassXC 2.1
* macOS

**Comment by TheZ3ro** [comment]
Can you please provide a screenshot?

**Comment by agatti** [comment]
Same here, see the screenshot below (the top two entries):

<img width="957" alt="screen shot 2017-01-25 at 19 22 38" src="https://cloud.githubusercontent.com/assets/235740/22288842/accd9d70-e333-11e6-9151-b8856ece7469.png">

also a related issue occurs on the "general" section of the preferences screen (checkboxes in the middle of the screen and language selector that's right-aligned):

<img width="957" alt="screen shot 2017-01-25 at 19 23 42" src="https://cloud.githubusercontent.com/assets/235740/22288874/cf857932-e333-11e6-88fd-86c3bfc6be38.png">

**Comment by phoerious** [comment]
I plan to rework the settings UI completely for 2.2.0. It's really ugly at the moment.

**Comment by droidmonkey** [comment]
This seems to be unique to the Mac interface as Linux and Windows display properly

**Comment by phoerious** [comment]
Fixed in #340.
