### ISSUE TITLE
Also show MD5 fingerprints for SSH keys

### ISSUE THREAD

**Issue by yan12125** [keepassxreboot/keepassxc#2050]
## Expected Behavior
Both SHA256 and MD5 fingerprints are displayed

## Current Behavior
Only the SHA256 fingerprint is shown

## Possible Solution
1. Add an optional parameter `algo` to `OpenSSHKey::fingerprint()` to choose from SHA256 or MD5, where SHA256 is the default
2. Modify `EditEntryWidget` so that both SHA256 and MD5 fingerprints are displayed

## Steps to Reproduce (for bugs)
1. Setup an SSH key for an entry
2. Checkout it details in the SSH Agent page of that entry

## Context
Some websites (e.g., GitHub), displays the fingerprint for an SSH key in MD5 (sigh). It would be useful to check whether the key in KeePassXC is the same one as that on the website or not.

![default](https://user-images.githubusercontent.com/1937689/41405400-468b6b08-6ffc-11e8-8fca-7ea1f6964bda.png)

Of course I can fetch the raw public key from https://api.github.com/users/yan12125/keys - kind of inconvenient...

## Debug Info
KeePassXC - Version 2.3.3-snapshot
Build Type: Snapshot
修訂：f4f8be5

函式庫：
- Qt 5.11.0
- libgcrypt 1.8.3

作業系統：Arch Linux
處裡器架構：x86_64
核心：linux 4.17.0-1-ARCH

已啟用的擴充元件：
- Auto-Type
- Browser Integration
- SSH Agent

**Comment by hifi** [comment]
For the record for everyone who are facing this issue, you can do this when the keys are loaded to agent:
```
$ ssh-add -E md5 -l
```

**Comment by yan12125** [comment]
Thanks for the work! That's quite useful.
