### ISSUE TITLE
Lock mouse when autotyping 

### ISSUE THREAD

**Issue by grenzor** [keepassxreboot/keepassxc#2051]
## Expected Behavior

Once autotype is initiated mouse clicks/movements should be locked so the user can't interfere (with a override setting for the user to still be able to move their mouse if they want). 

## Current Behavior

If you autotype starts the user can still move the mouse and if they accidentally click anywhere like a unintended program, chat/IRC client, new tab etc. this can be bad as it can leak sensitive data like email, passwords etc.

## Possible Solution

AFAIK this is available in Keepass. Apparently on Windows, Keepass calls `BlockInput` to do this but you guys probably know best on what to do for each platform.

**Comment by hifi** [comment]
KeePassXC tries to detect if the focus changes and stops the sequence if it happens. However, it is known to miss it sometimes so it's not 100% reliable.

My general suggestion is to remove `{ENTER}` from the auto-type sequence as that will avoid the most immediate issue of submitting something accidentally (like a chat message).

**Comment by grenzor** [comment]
>KeePassXC tries to detect if the focus changes and stops the sequence if it happens

I noticed XC stopped typing once or twice but in my experience more often than not I've found that when I accidentally click away from the intended form (happens quite a bit due to absentmindedness) it still keeps typing. Address/search bar is another concern as you don't even need to have `{ENTER}` in your auto-type sequence as most browsers' setup will by default search as you type.

>My general suggestion is to remove {ENTER}

That could be ok for single page logins but nowadays there's increasing sites that are having multi page login for the input data like username, password, 2FA etc. It would be a pain to remove `{ENTER}` and manually click enter each time for these every time you login.

Honestly, I think a lock on the mouse clicks would be the least troublesome and more secure solution for the user.

**Comment by droidmonkey** [comment]
I do not think this is possible cross platform based on my research. Even the Windows call is a little dubious, I can't believe that API even exists!

**Comment by TheZ3ro** [comment]
@grenzor are you using the Perform Autotype feature (CTRL+V) or the Global Autotype one?
The latter prevents focus changes, the former does not.

**Comment by grenzor** [comment]
@TheZ3ro I'm using the Global autotype shortcut. I don't think it fully prevents focus changes since I've had it happen where XC still keeps typing (maybe this depends on the type of form/input area I accidentally click into?)

**Comment by TheZ3ro** [comment]
@grenzor If you change focus in the same window KeePassXC can't detect the focus change. 
One application can't detect focus change in another application's window, only the window manager can detect such an event.
We only detect if the window title change during autotype and really it's the only thing we can do easily and cross-platform. 

So there are 2 cases:
1) XC is still typing after the window changes -> it's a bug and must be resolved
2) XC is still typing after a focus change in the same window -> I agree it's bad but we can't do much against it

If I understand it right you are autotyping in a webpage login and then the focus goes to the url bar, so sadly we are in case 2.

*maybe* we can check out `BlockInput` and it's counterpart for macOS and X11/wayland but I'm not very confident

**Comment by droidmonkey** [comment]
We won't be implementing this
