### ISSUE TITLE
Key binding for autotype of password only

### ISSUE THREAD

**Issue by pbulteel** [keepassxreboot/keepassxc#2052]
## Expected Behavior
We can autotype username & password using by default ctrl-v. This can be changed on each entry to allow to autotype only password. However, for that same entry (multiple entries in fact) there are times when you want to only autotype the password. There's no keybinding for this. You either modify the entry to only autotype the password, or you have username + password.

It would be great to have the ability to autotype (not copy/paste) only the password.

## Current Behavior
There's only one keybinding for entering what's set as default autotype entries. New keybinding needed for only autotyping password. This is different from copy into memory since some sites and applications don't allow pasting of passwords - these don't offer the username field - hence autotyping username+password is not valid in that instance, but might be valid in other instances.

## Possible Solution
Additional keybinding - ctrl-p for password autotype

## Context
1. A remote desktop session where you login and enter the username and password - this then gets locked by screensaver and you should only enter the password to log back in.
2. A website where you have to enter the password in a separate page from where you entered the username and it doesn't accept pasting - example password change fields which don't allow pasting.
3. Application that prompts for a password but doesn't allow pasting.

**Comment by droidmonkey** [comment]
Prefer #2093 to track this feature.

**Comment by ashtonmoss115-alt** [comment]
Ashton113282
