### ISSUE TITLE
x86 AppImage release

### ISSUE THREAD

**Issue by nebulak** [keepassxreboot/keepassxc#2053]
Currently the website only provides a 64bit build for the AppImage.
Old netbooks only have 32 bit architecture. Iwould be nice to be able to easily install keepassxc with AppImage on older netbooks running GNU/Linux.

## Expected Behavior
There should be an 32 Bit AppImage release on the releases page.

## Current Behavior
No 32 Bit AppImage release on the releases page.

## Possible Solution
Build keepassxc for GNU/Linux 32 Bit, package it as an AppImage and upload it to the releases page.

## Steps to Reproduce (for bugs)
1. Go to https://github.com/keepassxreboot/keepassxc/releases
2. Find no AppImage release for 32 Bit

## Context
I am currently building a workstation setup tool for debian with ansible which installs privacy protecting applications and packages.
 I want to integrate keepassxc & the script should be able to run on 32 Bit & 64 Bit architecture.

Operating system: Debian stretch
CPU architecture: i386

**Comment by phoerious** [comment]
I doubt this will be used very much.

**Comment by nebulak** [comment]
Do you have the same opinion for x86-GNU/Linux binaries?
Otherwise this might be an alternative.

**Comment by phoerious** [comment]
Not sure what you mean. A 32-bit AppImage would be an x86 binary. I simply don't think it would be worth the effort. Some distributions still provide 32-bit builds, but I don't think an upstream 32-bit AppImage would we used very much. We have even thought about discontinuing the 32-bit Windows builds.
