### ISSUE TITLE
[Suggestion] Alternative login Digi-ID

### ISSUE THREAD

**Issue by Halmex** [keepassxreboot/keepassxc#2056]
Hi guys, just found out about Digi-ID https://www.digi-id.io/ and the first thing I thought of was how amazing it would be to unlock my KeepassXC-Database with it, this is the perfect application. 
The open source project Digi-ID is similar and theoretical compliant (no certification yet) to the new FIDO web authentication standard (going to be integrated in all major browser) for passwordless authentication. This means no need for a master password and all of its weaknesses (see ##Context).

## Expected Behavior
Add the new login option Digi-ID by displaying a QR-Code as a option on the KeepassXC-Loginscreen through which you can log in with the Digibyte-App.

## Possible Solution
For more information: https://www.digi-id.io/.
Github: https://github.com/digibyte/digiid-php
Telegram Developer Channel: https://web.telegram.org/#/im?p=@DigiByteDevelopers

## Context
A more secure way of protecting the Keepass-Passwort-Database from keyloggers and insecure masterpasswords with the nice addition that you theoretically haven't to remember any password anymore.

Maybe someone is interested.

**Comment by droidmonkey** [comment]
I read through the documentation and looked at the JS/PHP libraries... this does not seem aimed at applications. Looks like you need to have a listening connection to their server to receive the authentication. Even then, this would not work for master password decryption since they are really only authorizing access, not decryption.

**Comment by Halmex** [comment]
Wow that was fast. Thanks for the help, to bad this isn't possible.
