### ISSUE TITLE
Database settings checkbox don't align w/ edit boxes

### ISSUE THREAD

**Issue by jsoref** [keepassxreboot/keepassxc#206]
## Expected Behavior
Buttons should align w/ edit boxes

## Current Behavior
Buttons don't align

## Steps to Reproduce (for bugs)
1. Open KeePassXC.app
2. Open Database
3. Go to database settings

## Your Environment
* KeePassXC 2.1
* macOS

**Comment by TheZ3ro** [comment]
Can you please provide a screenshot?

**Comment by phoerious** [comment]
Fixed in #299.
