### ISSUE TITLE
Feature: auto-type token to wait for [matched] window title change; e.g. {change_title /my.bank.*verify/}

### ISSUE THREAD

**Issue by nmschulte** [keepassxreboot/keepassxc#2060]
Using `{delay n}` works decently well, but suffers requiring a generous timeout to compensate for different connections and service latencies.  It seems detecting a specific window title change or even a change/count at all would be useful to mitigate this.  An auto-type instruction of `{change_title /regexp/}` or similar should work, possibly with a configurable watchdog/timeout and relaxed/no pattern matching if that's too complex.

**Comment by TheZ3ro** [comment]
I can't understand your request, can you please make an usage example?

**Comment by grrttedwards** [comment]
I think what they're getting at is something along the lines of the behavior of `WinWaitActive` from AutoIt/AutoHotkey. i.e. 

> Pauses execution of the script until the requested window is active.


See [AutoHotkey docs](https://autohotkey.com/docs/commands/WinWaitActive.htm) or [AutoIt docs](https://www.autoitscript.com/autoit3/docs/functions/WinWaitActive.htm)

**Comment by TheZ3ro** [comment]
Like you said, many applications/pages don't change their titles between steps.
The solution when the "delay" is too much or it's not usable is to use 2 different autotype sequence and manually trigger the first one and then the second one.

Also the WAIT_TITLE solution you proposed can be dangerous if the user don't set a proper filter and personally I would like to avoid it if possible
