### ISSUE TITLE
Allow user to define automatic DB backup location and name

### ISSUE THREAD

**Issue by grenzor** [keepassxreboot/keepassxc#2062]
## Expected Behavior

Allow users to define location (for example this allows saving to a different drive and useful if the drive with the original DB file fails) and also a custom name for the backed up DB file.

## Current Behavior

Currently, there is an option to save a backup before saving - which saves to the same folder location as the original DB file with name as `db.old.kdbx`

**Comment by ratcashdev** [comment]
#2109 Please consider adding a configurable number of backups to keep, similarly how it is done in https://keepass.info/plugins.html#dbbackup

**Comment by grenzor** [comment]
@droidmonkey

It seems this feature is linked to the new KeeShare. Could you please tell me the easiest way to set up just the automatic backup location + custom name without using other Keeshare features?

**Comment by droidmonkey** [comment]
No, for keeshare we need to be explicit at this time

**Comment by grenzor** [comment]
Any particular reason for that?

**Comment by droidmonkey** [comment]
To differentiate a signed vs unsigned database. What is the purpose of removing or changing extensions anyway. You are not protecting yourself at all.
