### ISSUE TITLE
Auto Type: Window Title dropdown does not list all windows on macOS

### ISSUE THREAD

**Issue by whisdol** [keepassxreboot/keepassxc#2065]
## Expected Behavior
When editing an entry and trying to associate a specific window in the Auto-Type settings, the drop down list for "Window Title" lists all window titles of all windows.

## Current Behavior
When editing an entry and trying to associate a specific window in the Auto-Type settings, the drop down list for "Window Title" only lists window titles of windows on the current desktop (or only the KeePassXC window if it's maximized).

## Possible Solution
Check all desktops/maximized windows when listing window titles.

## Steps to Reproduce (for bugs)
1. Maximize KeePassXC (green plus icon)
2. Edit an entry, go to AutoType and add a new Window association
3. Open the dropdown for window titles

## Context
I usually use KeePassXC maximized to quickly switch to it with Ctrl + Arrow. When trying to add a new window association for Auto Type, I noticed that KeePassXC needs to be on the same desktop as the window I'm trying to associate.
Once the window is associated, AutoType works even when KeePassXC is on another desktop or maximized as the window/dialogue that should be filled.

## Debug Info
KeePassXC - Version 2.3.3
Revision: 0a155d8

Bibliotheken:
- Qt 5.9.3
- libgcrypt 1.8.2

Betriebssystem: macOS Sierra (10.12)
CPU-Architektur: x86_64
Kernel: darwin 16.7.0

Aktivierte Erweiterungen:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by ssbarnea** [comment]
While I realise this ticket was closed more than an year ago I find hard not to wonder if there was a regression.

It seems that the Windows title dropdown does show only the title of the keepass own window and I did not observe any request from the application for accessibility feature, something that AFAIK is needed in order to be able enumerate open Windows.

It was not even clear to me if the Window title must be a perfect match or if the first part is enough (aka startswith).

**Comment by droidmonkey** [comment]
You likely need to remove the accessibility and screen recording permissions for KeePassXC completely in the macOS settings. Then re add KeePassXC application to both. MacOS is notoriously buggy when updating applications and maintaining these permissions.

**Comment by dayyi** [comment]
> You likely need to remove the accessibility and screen recording permissions for KeePassXC completely in the macOS settings. Then re add KeePassXC application to both. MacOS is notoriously buggy when updating applications and maintaining these permissions.

Thanks, this solved my issue (same as @ssbarnea had)!

**Comment by dubois** [comment]
On macOS 15.7, KeepassXC 2.7.10, it looks like the permission request doesn't lead to both permissions being granted.

1. Quit KeepassXC
2. Remove Accessibility, Screen Recording from KeePassXC with tccutil or Preferences GUI
3. Launch KeepassXC
4. Trigger the permission request -- switch windows and hit the global auto-type keybinding
5. 2 dialogs pop up: the KeepassXC explanatory dialog, and a system dialog for "Accessibility Access".
6. Click "Open System Settings" on the system dialog: Keepass is in the app list, disabled. Enable it.
7. Hit "OK" on the KeepassXC dialog

There's never a system dialog regarding screen recording permissions; and KeepassXC is never added to the screen recording app list, not even as a disabled app. So, I suspect the reason this happens is that new users / new installs never get both required permissions unless the user manually adds them.

@droidmonkey maybe the explanatory dialog could warn about this misbehavior?

**Comment by droidmonkey** [comment]
MacOS screws up their permissions process every other OS update. Its nearly impossible to keep track of anymore. Very frustrating.

**Comment by DidierLoiseau** [comment]
I arrived here because the dropdown was only listing KeePassXC itself. I confirm I did not get a pop-up asking for the permission. Could it be because I installed it for my account only?

Anyway, after adding it in Privacy & Security > Screen & System Audio Recording, it works. So it seems to no longer be an accessibility permission.

I’m on macOS 15.7.3.
