### ISSUE TITLE
Sync issues working with Google Drive File Stream

### ISSUE THREAD

**Issue by thijskaspers** [keepassxreboot/keepassxc#2066]
Me and my collegue are working in the same .kdbx file using Google Drive File Stream and KeePassXC. I was hoping that when I add a new password, it would sync and then my collegue would get this password too, but we are getting endless errors with Google saying the file can't be saved or it will create new filenames with (1).kdbx and (1) (1).kdbx.

We need it to sync properly and also have the option to have the kdbx database open at the same time.

Does anyone get this to work properly? And if so, care to explain how? Thanks in advance!

**Comment by droidmonkey** [comment]
Turn off safe saves in the settings. Google jacked up their perfectly good sync tool and it performs just as terribly as dropbox now.

**Comment by thijskaspers** [comment]
@droidmonkey We both have 'safe saves' disabled in the settings. The problem is, I'm the owner of the database, sharing it with my collegue. When I change something, he will see it, but when he changes something, it will create a new file under the same name. After syncing I now see a new file with (1).kdbx filename. His changes are in that file, not in mine.

Hopefully the QSaveFile fix will solve it :)

**Comment by droidmonkey** [comment]
That sounds more like a Google Sync issue than anything else.

**Comment by mstarke** [comment]
There are reports for similar issues for MacPass and Google Drive Sync. The result is that changes aren't reflected in the file system and only happen after restarting the Sync tool. What's even worse is, that the metadata is updated but changes to the actual data are lost. This also is observable when using built-in applications and files located in Google Drive.

My guess is the mounted Volumen of the Drive is missing some low-level features that the OS relies on to work properly with file synchronisation.

**Comment by droidmonkey** [comment]
Going to close this since as several saving issues were corrected in 2.4.0. Unless this still persists for someone?
