### ISSUE TITLE
Connector for Git credential cache

### ISSUE THREAD

**Issue by ftorto** [keepassxreboot/keepassxc#2067]
## Expected Behavior

When I use git with several remotes, I have to fill my git password regularly (depedning on my `git config credential` configuration). 
According to [the git book](https://git-scm.com/book/en/v2/Git-Tools-Credential-Storage), It is possible to link to a *custom Credential cache*.

As it is done for `ssh-agent` (even if I never succeeded to use it properly :sad: ) Is it possible to have a similar behaviour ?

## Current Behavior

When Git asks for remote password, go to keepassXC, copy password, paste

## Possible Solution

Similar to `ssh-agent`

**Comment by hifi** [comment]
If you can use SSH connection with your git repositories (services like GitHub, Bitbucket and GitLab all support it for one) you can use the SSH Agent integration.

I don't think it's worth the hassle to add custom support for git when the SSH Agent integration already works for it.

**Comment by ftorto** [comment]
I understand your point of view. 
To give more information: I'm behind corporate proxy most of the time where SSH is forbidden. I don't think I'm the only one facing this issue. Maybe a quick poll could give stats ? :+1: :-1:

**Comment by droidmonkey** [comment]
You best bet is to use the CTRL-V shortcut from within KeePassXC to invoke autotype onto the previously selected window. There is no mechanism that exists to supply credentials to the https method of connecting with git

**Comment by droidmonkey** [comment]
This can be accomplished using the example Ruby script in the document you linked calling the keepassxc-cli interface to obtain the username and password for a particular url.

**Comment by TheZ3ro** [comment]
:+1: for the Ruby/keepassxc-cli interface
