### ISSUE TITLE
Copy does not function correctly in grid (grid row steals focus causing unexpected behavior)

### ISSUE THREAD

**Issue by GHLover** [keepassxreboot/keepassxc#2069]
## Expected Behavior
In the grid view there is a pane below that lists information when you have selected a row. When you click this pane and highlight data for example the "username" and press CTRL-C you would expect to have the username copied. After all, the info pane has focus and the text is highlighted so it should be copied.

What actually happens is that the password get's copied. Even though the grid row should no longer have focus it's settings cause a copy.

## Current Behavior
The current behavior is that the grid password is copied even if the grid does not have focus. The issue with this is that it causes people to paste the wrong data into potentially compromising fields.

## Possible Solution
When the info pane has focus the grid row should not steal keyboard inputs and cause copies, especially when text inside the info pane is highlighted.

## Steps to Reproduce (for bugs)
1. Highlight row in grid
2. In the info pane below select text such as user name. Any text will work though
3. Press CTRC-C to copy. The copied text will unexpectedly be the password and not the highlighted text.

## Context
It has caused me to paste the password into sensitive fields that should not be pasted into and thus putting my security at risk.

## Debug Info
Latest version for linux.

**Comment by droidmonkey** [comment]
This is a duplicate
