### ISSUE TITLE
Remove view>show tab bar

### ISSUE THREAD

**Issue by jsoref** [keepassxreboot/keepassxc#207]
## Current Behavior
Toggles useless bar

## Possible Solution
Remove it

## Steps to Reproduce (for bugs)
1. Open KeePassXC.app
2. View>Show tab bar

## Your Environment
* KeePassXC 2.1
* macOS

**Comment by TheZ3ro** [comment]
Tested on macOS 10.12. This is pretty nasty.

**Comment by phoerious** [comment]
Toolbar or tabbar?
I think the toolbar toggle is generally quite useless and the whole view menu can be removed because it's the only entry there.

**Comment by TheZ3ro** [comment]
On mac there is an option for toggoling the tab bar (it's different from the toolbar)
And also the toolbar option is useless i think, who want to hide that?

**Comment by jsoref** [comment]
Fwiw, the toolbar is useful for search (when search works); and it could be useful for random generator if it didn't crash.

But, this issue is about the tabbar option.

**Comment by TheZ3ro** [comment]
Yes, but I don't see the needs to hide the toolbar.

On macOS 10.12 the tabbar is like the titlebar but nastier. 
I will fix this for 2.2.0

**Comment by jsoref** [comment]
Oh. Yes, the toggle for the toolbar is moderately silly. But, that wasn't my issue. If someone cares, they can file their own issue :-)

**Comment by phoerious** [comment]
"Moderately silly". Made my day. 😆

**Comment by TheZ3ro** [comment]
Yes yes @jsoref I will fix the tab-bar (and also maybe the toolbar) :tongue:

**Comment by whodknee** [comment]
I like the option to disable the toolbar. Since I use keyboard shortcuts for everything I like not having the clutter.

**Comment by phoerious** [comment]
I knew it would break someone's workflow. Lol.

**Comment by TheZ3ro** [comment]
The toolbar is ok, tabbar is useless

**Comment by TheZ3ro** [comment]
So what about this? Can we remove the `View` menu?

**Comment by phoerious** [comment]
I have never used it in my life.

**Comment by jsoref** [comment]
Fwiw, `Enter Full Screen` ^⌘F is a fairly standard thing in a `View` menu (`Outlook.app`, `Firefox.app`, and `Google Chrome.app` all have it). What KeePassXC has is missing the accelerator which is unfortunate.

I personally can't imagine a reason for wanting to full screen keepass.
