### ISSUE TITLE
AutoType Not Finding Entry

### ISSUE THREAD

**Issue by SmoochiesBoss** [keepassxreboot/keepassxc#2070]
## Expected Behavior

Autotype should type the password into Quickbooks as per my autotype settings when the window matches.

**Snip** (dont post personal info)

## Current Behavior

KeepassXC can't find any entries. It says "Couldn't find an entry that matches the window title:" with the title of the modal dialog box/window.

## Possible Solution

Seems to be a consistent choke only when Quickbooks kicks up a modal dialog. When a modal is not up, the overall Quickbooks app container window is found (i.e., the subwindow title is disregarded by KeepassXC autotype). Changing the target window to the overall Quickbooks app container doesn't solve the problem.

## Steps to Reproduce (for bugs)

1.Do something to create a modal dialog in Quickbooks.
2.Use autotype keystroke.
3.
4.

## Context

I am attempting to migrate from KeePass and use this enter passwords for my online banking integration with my bookkeeping software. It works fine in KeePass.

## Debug Info

KeePassXC - Version 2.3.3
Revision: 0a155d8

Libraries:
- Qt 5.10.1
- libgcrypt 1.8.2

Operating system: Windows 10 (10.0)
CPU architecture: x86_64
Kernel: winnt 10.0.17134

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by TheZ3ro** [comment]
I don't know what Quickbooks is, care to post a screenshot of the window where you are performing autotype?

**Comment by SmoochiesBoss** [comment]
Quickbooks is the awful but most full featured and widely used small
business accounting software out there. Screenshot should be with the
original post.

E

**Comment by droidmonkey** [comment]
I removed the screenshot because it contained some potentially sensitive information.
