### ISSUE TITLE
Cannot acces files/folders in hidden folders

### ISSUE THREAD

**Issue by smiddy** [keepassxreboot/keepassxc#2072]
When I try to access any subfolder or files (e.g. my database from /home/USER/.keepassx/) from a hidden folder, it is not possible.

## Expected Behavior
Access hidden folders

## Current Behavior
* Enter the hidden folder, e.g. /home/USER/.keepassx/
* Nothing is visible

## Steps to Reproduce (for bugs)

1. Enter the hidden folder, e.g. /home/USER/.keepassx/
2. Nothing is visible

or

1. Locate your db in hidden directory, e.g. /home/USER/.keepassx/
2. NTry to open with context menu.
3. Error 'permission denied' occurs

## Context
I tried to open my database

## Debug Info
KeePassXC - Version 2.3.3
Revision: 0a155d8
Distribution: Snap

Libraries:
- Qt 5.7.1
- libgcrypt 1.7.6-beta

Operating system: Ubuntu Core 16
CPU architecture: x86_64
Kernel: linux 4.15.0-23-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by droidmonkey** [comment]
This is a hardline limitation of snaps and is in our FAQ.
