### ISSUE TITLE
Moving an entry via context menu

### ISSUE THREAD

**Issue by lindhe** [keepassxreboot/keepassxc#2074]
## Feature Suggestion 
It seems to me that the only way to move an entry from one folder to another is by drag-and-drop, which I find inconvenient. I would very much like to see a context menu item to move the entry ("Move >" and then a tree of folders to put it in).

Somewhat related to #834

## Debug Info
KeePassXC - Version 2.3.3
Revision: 0a155d8

Libraries:
- Qt 5.11.1
- libgcrypt 1.8.3

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 4.17.2-1-ARCH

**Comment by helloPiers** [comment]
This would be great, and would help where drag and drop is broken, ie on Mac (still not working on 2.6.3 despite closed #5636).

**Comment by droidmonkey** [comment]
It's a qt bug on macos, we have no control.

**Comment by helloPiers** [comment]
Thanks, yeah understood. (The feature in this issue would mitigate it - but obviously not a small/quick thing at all 😄.)

Just on the drag/drop, that ticket is closed noting Qt 5.15.2 would be in 2.6.3 but the "About" for 2.6.3 on my machine says Qt 5.15.1 still - is that something I have control over locally? Thanks

**Comment by droidmonkey** [comment]
Perhaps yes, ping @phoerious

**Comment by phoerious** [comment]
No, not really. Qt is bundled and signed with the rest of the application.

**Comment by droidmonkey** [comment]
Yah but brew has 5.15.2 available

**Comment by michaelk83** [comment]
Rather then a specialized "Move" command, maybe better Edit -> Cut/Copy/Paste on the entry and folder levels? Those can be linked to the usual Ctrl+X/C/V shortcuts, and work between databases as well as within one.
No need to store the entries' data in the clipboard. Just their path and some helper state.

**Comment by michaelk83** [comment]
To be more specific, the Cut/Copy/Paste should reuse the current drag-and-drop logic:
- Cut corresponds to drag-start event without `Ctrl` modifier.
- Copy corresponds to drag-start event with `Ctrl` modifier.
- Paste corresponds to drag-end event.

Minus the drag animation. Need to pull out that logic to where it can be reused, then hook context and main menu items to these actions.

**Comment by michaelk83** [comment]
Just found #172 , which is still open.
@droidmonkey , both this and #3796 can be closed as duplicates of #172. #6124 would also be covered by Copy/Paste, so can be closed. We can reuse the drag-and-drop logic, as I [noted above](https://github.com/keepassxreboot/keepassxc/issues/2074#issuecomment-829527810).

**Comment by droidmonkey** [comment]
Thanks for your enthusiasm. We still want a context menu and sure copy/cut/paste of some form as well. We got this covered and it's in the pipeline.

**Comment by droidmonkey** [comment]
I would rather focus on #172 then add a complex context menu to support this feature. As such, closing this one.
