### ISSUE TITLE
Incorrect work with auto-type when I use Russin and English layout!

### ISSUE THREAD

**Issue by MAPIIIAJI** [keepassxreboot/keepassxc#2079]
Hi all. First, sorry for my English. I have OS Linux Ubuntu 18.04 LTS with DE XFCE and I use Russian and English keyboard layout. When situation stand Russian layout and I use auto-type, English symbols interpret to Russian symbols. e.g. in login space have content "qwerty" when if use auto-type it is stand "йцукен"
KeepassXC Auto-type settings:
![aa](https://user-images.githubusercontent.com/35526267/42086107-98ac2aa2-7bab-11e8-84d0-5c18d6f77bac.jpg)
Thanks in advance.

**Comment by droidmonkey** [comment]
Closed in favor of #2246 and #2323
