### ISSUE TITLE
Autotype not working in Firefox 60+ on Linux

### ISSUE THREAD

**Issue by bernermic** [keepassxreboot/keepassxc#2081]
Since some time (maybe since updating to Firefox 60.0.x June 6.) I face the issue, that the autotype password to Firefox password fields is not working anymore (at least for most of my passwords).

## Expected Behavior

Opening login page - call to auto type fills out username & password automatically and submits the login call. Login is executed properly.

## Current Behavior

Opening the login page + call to auto type fills in the user, then the password and submits the form. Response is: "Invalid login or password". 
On checking what happens I found this:
**User** is typed in correctly, 
**Password** as in my tests I found out the first character of the password is not typed.

Further tests showed, that this happens after each TAB execution. Somehow this leads to character missing

Further tests again showed, that more characters where not typed. Example pattern tested was:

- Form with three input form fields.
- Pattern for auto type: **{USERNAME}**{TAB}**12**{TAB}**{PASSWORD}**
-- Elements should be: 
USERNAME="user"
12="12"
PASSWORD="password"
- Result in form was:
-- USERNAME=correct
-- 12=only character '2' was filled - one character was missing
-- PASSWORD="word"
So it is not allways just one character which is not typed.

## Steps to Reproduce (for bugs)

1. Firefox version 60.0.2
2. Keepassxc 2.3.3 (installed as Snap)
3. Ubuntu 18.04
4. Autotype password via default pattern: {USERNAME}{TAB}{PASSWORD}
5. verify what was typed as password

## Debug Info

KeePassXC - Version 2.3.3
Revision: 0a155d8
Distribution: Snap

Libraries:
- Qt 5.7.1
- libgcrypt 1.7.6-beta

Operating system: Ubuntu 18.04 - installed via Snap (Snap based on: Ubuntu Core 16)
CPU architecture: x86_64
Kernel: linux 4.15.0-23-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by droidmonkey** [comment]
I cannot reproduce this on the same setup (Ubuntu 18.04 w/ Snap build). What website are you trying to type into?

**Comment by bernermic** [comment]
Oh - thanks for this response. I did not think of such a test.
I'll try that and if it works I report it back to you.

**Comment by bernermic** [comment]
This workaround seems to work consistently for me now.  
I tested both DELAY in Autotype sequence and time 50 ms delay globally.

**Comment by jimbudarz** [comment]
Settings don't have a "pattern" option on the Auto-Type settings tab. Where are users supposed to change this?

**Comment by jimbudarz** [comment]
For future users who experience this bug, this is accomplished by:
1. Right click on "Root" folder (or another folder if you prefer to limit the pause to a subset of saved passwords.)
2. Click "Edit Group"
3. Under Auto-Type, select the radio button "Set default Auto-Type sequence" to {USERNAME}{TAB}{DELAY 1}{PASSWORD}{ENTER}
4. Apply changes.

**Comment by jimbudarz** [comment]
The problem persists for me after applying the suggested workaround. The current Root folder Auto-Type sequence is {USERNAME}{TAB}{DELAY 1}{PASSWORD}{ENTER} and I can confirm that the setting has been inherited by individual entries but there appears to be no delay- even with {DELAY 100} I get no perceptible time between entry of username and password. The example site where this doesn't work is reddit.com.

**Comment by droidmonkey** [comment]
This is because I gave bad advice, the DELAY keyword is actually in milliseconds, so using {DELAY 500} should be sufficient.

**Comment by jimbudarz** [comment]
Thanks @droidmonkey for sticking it out with me. Situation resolved.

**Comment by bernermic** [comment]
For me the DELAY 1 is working reproducable.
That is strange.

**Comment by mihaiile** [comment]
shouldn't the typing delay automatically be applied also for the {TAB}?
By default the application has a start delay of 500ms and typing delay of 25ms.
I would guess that the 25ms of delay should be applied not only after letters input but also for tab command.

**Comment by droidmonkey** [comment]
That is where I think the issue is, the delay is not applying correctly between actions. Perhaps we need to also increase the default delay after a tab event.

**Comment by ccoenen** [comment]
This should go in some kind of FAQ or known issues or workarounds. This bit me for quite a while. It's not easy to find this issue when you don't know that it is limited to firefox or ubuntu.

**Comment by ccoenen** [comment]
Another thing about this is: For a select few passwords, I actually override the auto type action. I am somewhat reluctant to insert the delay in each of them. I would prefer a more "general" fix of this issue.

**Comment by bremme** [comment]
I can confirm this bug as well. My Auto-Type logins stopped working a couple days ago. I'm on Debian Buster, KeepassXC 2.3.4 and Firefox 60.4. I changed the Auto-Type sequence on my root group to `{USERNAME}{TAB}{DELAY 100}{PASSWORD}{ENTER}` this seems to have solved my problems
