### ISSUE TITLE
Bad IV length for Chacha20 (with AES-KDFv3 -KDBXv3)

### ISSUE THREAD

**Issue by J-Jamet** [keepassxreboot/keepassxc#2082]
## Expected Behavior
Byte for EncryptionIV in the header 7 of a KDBXv3 file must be 12 bytes length and not 16 bytes for Chacha20 when AES-KDFv3 is selected.
https://keepass.info/help/kb/kdbx_4.html#chacha20

## Current Behavior
A database modified with Chacha20 and AES-KDFv3 can not be opened in an another KeePass application.

## Possible Solution
I do not know exactly how AES-KDFv3 is implemented, but it should currently take the default value of 16 bytes in length for the IV without making a condition for Chacha20 which must be 12 bytes for a save. 
Opening a database created with KeePass2 in Chacha20 and AES-KDF (KDBXv3 without taking care of KDFParameter) works well.

## Steps to Reproduce (for bugs)
1. Create a new database with KeePass XC
2. Change the algorithm to Chacha20 and KDF to AES-KDFv3
3. Try to opening the .kdbx file with KeePass2 -> Failed to opening Database corrupted
4. Try to opening the .kdbx file with KeePass DX -> Database can't be read (https://github.com/Kunzisoft/KeePassDX/issues/116)

## Context
It's a user of my Android KeePass DX application that could not open a modified database with KeePass XC. I investigated for a long time before seeing that the size of the generated IV was not the right one.

Nice application by the way, I'm inspired a lot of KeePass XC for my developments! :)

## Debug Info
KeePassXC - 2.3.3
Revision: 0a155d8

Libraries:
- Qt 5.5.1
- libgcrypt 1.8.1

Operating system: Ubuntu 16.04.4 LTS
CPU architecture: x86_64
Kernel: linux 4.13.0-45-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by droidmonkey** [comment]
I think you might be backwards, KDBX4 is claiming a 12-byte size, with KDBX3.x being 16-byte. From the linked documentation:

> Up to KDBX 3.1, the encryption IV stored in the KDBX header (field with ID 7, EncryptionIV) was always 16 bytes (128 bits) long. As of KDBX 4, the encryption IV length is retrieved from the cipher implementation and the KDBX header field stores an encryption IV of exactly this length. For ChaCha20, that is 12 bytes (96 bits).

**Comment by J-Jamet** [comment]
OK, thanks for the quick message, in this case I will just put a note to indicate to update the databases with this problem.
