### ISSUE TITLE
Remember last directory used for key file instead of last key file itself

### ISSUE THREAD

**Issue by Y0Mamma** [keepassxreboot/keepassxc#2085]
I use a key file that is in a certain directory with about about a 1000 other files. As it is now, it takes me several clicks just to get to that directory each time KeePassXC starts. This feature request is different than remembering the last key file selected. I don't want that.

Great work guys. I like KeePassXC much better than KeePass.

Operating system: Linux Mint 19
CPU architecture: 64 bit
Kernel: 4.15.0-23

**Comment by droidmonkey** [comment]
We specifically disabled this behavior since it can expose significant information to an attacker.

**Comment by Y0Mamma** [comment]
Yes, it could do that, but if it is an option, I can choose to take that risk.

**Comment by droidmonkey** [comment]
Implemented in 2.7.0
