### ISSUE TITLE
New Feature Request : Minimize after double clicking the User Name or Password field.

### ISSUE THREAD

**Issue by Y0Mamma** [keepassxreboot/keepassxc#2086]
Great work guys. I like KeePassXC much better than KeePass.

Operating system: Linux Mint 19
CPU architecture: 64 bit
Kernel: 4.15.0-23

**Comment by droidmonkey** [comment]
This is already possible, just turn on the setting "Minimize on copy to clipboard"

**Comment by Y0Mamma** [comment]
I am sorry. I don't know how I missed that setting but I did. Thank you.
