### ISSUE TITLE
Database login widget should not stretch on wide windows

### ISSUE THREAD

**Issue by Y0Mamma** [keepassxreboot/keepassxc#2087]
When KeePassXC starts, it remembers the window size from the last time it shut down. Once you are logged into your database, this is great, but is kind of ugly with the stretched out data entry fields, etc when you are first logging in to the database.

Great work guys. I like KeePassXC much better than KeePass.

Operating system: Linux Mint 19
CPU architecture: 64 bit
Kernel: 4.15.0-23

**Comment by Y0Mamma** [comment]
Attached PIcture 1 is how I run KeepassXC.
Attached PIcture 2 is how it looks when I login.
Attached Picture 3 is how the login screen would look better
It's just a cosmetic suggestion. 
Thanks for the great work. 
I was a database programmer for about 30 years (VFP) and I just now moved from Windows to Linux. 


![pict-1](https://user-images.githubusercontent.com/18182233/42196357-2d627018-7e43-11e8-92f8-ed6d6d997661.jpg)
![pict-2](https://user-images.githubusercontent.com/18182233/42196358-2d7b47fa-7e43-11e8-8b14-378972adbd11.jpg)
![pict-3](https://user-images.githubusercontent.com/18182233/42196359-2d8e7c76-7e43-11e8-9ba4-17ef6d14249c.jpg)

**Comment by droidmonkey** [comment]
Instead of changing the window size, the database login widget (the password, key file, etc) should have a maximum width and be centered so that it does not get stretched out on wide windows.

**Comment by droidmonkey** [comment]
This was fixed in #3287
