### ISSUE TITLE
Unable to open the database. No root group.

### ISSUE THREAD

**Issue by ghost** [keepassxreboot/keepassxc#2090]
Hi guys, ran into a pretty urgent issue I really need to be able to access this database and I believe it has been corrupted.

Running KeePassXC on macOS High Sierra, my kbdx and key file are stored on a USB and I run the application from my Mac. 

Everything was working fine, I use autosave on my KeePass, I quit  the application, then I ejected my USB, plugged it into my Samsung Note8 to use it with an Andriod KeePass app, however unplugged it before using the file with the app to charge my phone.

Now on my Macbook whenever I try to open the database I get the error "Unable to open the database. No root group." Attempting to repair the database via KeePassXC yields the same response.

Upon trying to open the database from the Andriod app 'KeePass2Andriod Offline', it yields the error "An error occured: Exception of type 'KeePassLib.Serialization.InvalidDataException' was thrown".

**Comment by droidmonkey** [comment]
The "no root group" message usually means the internal xml is corrupt, empty, or decryption failed mid stream. Is the db file unusually small?

**Comment by DT-E08** [comment]
The database size is 37KB, I'm unsure how much it was previously, but there was over 100 passwords in there.

**Comment by droidmonkey** [comment]
This might be another use case for a raw db dump tool. I'll look into this today, but I am not the Mac builder.

**Comment by caschi1** [comment]
I just got the same issue. Yesterday everything worked fine the whole day. KeepassXC is set to automatically save all changes and lock the database after a few seconds. At the end of the day I closed the application and shut down the computer before removing the USB-drive (it is a 4GB Datashur Stick). This morning KeepassXC refused to open one of my database. The error message was "no root group". Opening a backup copy worked without problems. Also opening a second database which was closed at the same time with the same procedure and is stored on the same USB drive also worked without any problems. Any ideas on how to fix and overcome this?

**Comment by phoerious** [comment]
Please check the file size of your database. I bet it's been truncated.

**Comment by Tima0112** [comment]
I got same problem. Database file store on Linux (ext4 partition). I tried restore database using testdisk, but it didn't help. I don't have backup and i don't know how restore it...

**Comment by droidmonkey** [comment]
There is nothing we can do. You can try extracting the database using the cli tool: `keepassxc-cli extract [db file]`

**Comment by gitfineon** [comment]
https://github.com/Kunzisoft/KeePassDX/issues/546#issuecomment-766096099
I have a similar issue. File size seems not to be truncated. 

`keepassxc-cli extract [db file]` changed to `keepassxc-cli export [db file]` in Release [2.5.0](https://github.com/keepassxreboot/keepassxc/commit/1ab8a9f42c065bd575490ad7f3fa43ce72a59d8a)
- CLI: Rename command `extract` to `export`. [[#3277](#3277)]

Not a password issue because wrong password results in different error message. Padding?

**Comment by Manamama** [comment]
I have the same problem, but only when accessing the passwords file via WebDav on KeepasXC. 
Once I either:
1. Copy it locally (download)
2. Use another manager: AuthPass or Keepass.exe
it works fine.
