### ISSUE TITLE
Browser Chrome extension shows main password as identifier

### ISSUE THREAD

**Issue by maczor** [keepassxreboot/keepassxc#2092]
Image says it all - in the blured position there is my main password!
It does not change after the database is open.
<img width="444" alt="screen shot 2018-07-05 at 09 33 35" src="https://user-images.githubusercontent.com/2714682/42309001-b4b73238-8037-11e8-8bf6-cb4b2805bd8b.png">

**Comment by droidmonkey** [comment]
Ummm that's what you typed in when you connected the database to the browser extension.

**Comment by matthieubrunet** [comment]
I have the same problem. I tried to disconnect db both in KeePassXC and in the browser extension. But when I connect myself again, it only ask for password, not for the name or identifier. Where can I type a new identifier ?
