### ISSUE TITLE
Support Username-Only and Password-Only Auto-Type keyboard shortcuts

### ISSUE THREAD

**Issue by SkyWheel** [keepassxreboot/keepassxc#2093]
Hi Team,
I've made several attempts to migrate from KeePass 2 to Keepassxc, but the absence of many various Auto-Type options stops me every time. It is the Keepass 2 killer feature for me.
I need auto-type a lot of long passwords in console emulators via RDP session,  and the default auto-type option {USERNAME}tab{PASSWORD} just doesn't work.

**Comment by TheZ3ro** [comment]
You can change the autotype sequence as you wish https://github.com/keepassxreboot/keepassxc/wiki/Autotype-Custom-Sequence

**Comment by SkyWheel** [comment]
I know this feature. But Keepass2 has it from the box.
I have close to 100 (one hundred) passwords stored in my Keepass2 database. To migrate to Keepassxc I need manually change each and every record for these 100 records?
Besides, I need multiple choice of auto-type options, exactly like in Keepass2. Every time change the behaviour of auto-type?

**Comment by SkyWheel** [comment]
OK, let's assume I will find time for changing auto-type option for all 100 passwords. What about multiple choices of auto-type at the same moment?

**Comment by TheZ3ro** [comment]
I can't understand what's the issue here. Do you want autotype to only type the password?

**Comment by SkyWheel** [comment]
@TheZ3ro,  it is not an issue in common sense. It is feature request. It would be nice if Keepassxc could do everything that Keepass2 can.
Use case: I'm logged via RDP to a remote Windows desktop, and now I need SSH using PuTTY from this Windows to another Linux machine. In this case there is need auto-type in separate auto-type for username and password for one entry.
Or another example: using terminal emulator in Linux machine, and after that using the same record for GUI.

**Comment by SkyWheel** [comment]
So, Keepass2 does easily allow to do that. Where Keepassxc requires in one case {USERNAME}TAB{PASSWORD}ENTER, and in another case separately {USERNAME}ENTER and {PASSWORD}ENTER. Sometimes there is need in just {PASSWORD} without ENTER.
Keepass2 allows configure usual auto-type on Ctrl-V, but separately has different auto-type options you don't need to configure explicitly.

**Comment by droidmonkey** [comment]
Ahhh, he's saying a "quick" autotype that is preconfiguring to just perform a username or password typing. Like pressing CTRL+ALT+V types only the password.

**Comment by SkyWheel** [comment]
Sorry guys for long response. I'll try to make it clearer.
- After Keepass2 default installation, you can find 8 options of different auto-types. You don't need to configure anything, they are already there. I'll make a screenshot

**Comment by SkyWheel** [comment]
![auto-type_options](https://user-images.githubusercontent.com/10903432/42792675-e1cd749a-89b9-11e8-9227-5e0059d44d11.png)
As you can see there are many auto-type options available. You don't need to reconfigure a record every time you need another auto-type option.. Hope it's more clearer now.

**Comment by Russe** [comment]
Would be a nice feature instead of adding several entries with different autotype actions for the same target.

**Comment by pbulteel** [comment]
Looks like what I requested - or expansion of https://github.com/keepassxreboot/keepassxc/issues/2052

**Comment by SkyWheel** [comment]
Yes, looks similar.
In Keepass2 it's in the Options, Interface, "show additional auto-type menu commands".
I'm still deferring migration from Keepass2 to Keepassxc due to absence of this important feature.

**Comment by gmish27** [comment]
Please provide this feature in this year. I've transitioned from KeePass2 and as mentioned it'd be too hectic to carry out changes for individual entries manually for a large database.

**Comment by JohnVeness** [comment]
Please can the title of this issue be changed to something like "Support Username-Only and Password-Only Auto-Type quick functions" or similar, as it's not just about keyboard shortcuts - the menu image as shown above:
![auto-type_options](https://user-images.githubusercontent.com/10903432/42792675-e1cd749a-89b9-11e8-9227-5e0059d44d11.png) 
would also be very desirable. There are many websites which have username and password on separate pages, and there are occasions, like when changing a password, when you sometimes want to type the old password only, even though most of the time you want to type both.

I wasn't aware of this feature in KeePass2, so this thread is very helpful for telling me about that, if nothing else!

**Comment by SkyWheel** [comment]
Hmmm... I see more and more requests similar to this one in regards to Auto-Type. Still nothing?

**Comment by cr1st1p** [comment]
Until this gets implemented, in case it helps others: on Linux, I'm using a global shortcut running the code referenced in https://gist.github.com/ethack/110f7f46272447828352768e6cd1c4cb

**Comment by ccoenen** [comment]
KeePass 2.42 added a password-only auto-type with [Ctrl]+[Alt]+[Shift]+[A], which I would like to see adopted in KeePassXC for consistency (and because it's a useful thing I need occasionally.

**Comment by ccoenen** [comment]
Another place, where this is useful: when changing passwords or while setting up accounts: you're usually asked to type your password twice. With this shortcut, this becomes as easy as
[Ctrl]+[Alt]+[Shift]+[A]
[Tab]
[Ctrl]+[Alt]+[Shift]+[A]

**Comment by SkyWheel** [comment]
Just installed fresh KeePassXC version (AppImage). Played around and deleted. The killer-feature is still not implemented 😢 Still staying with KeePass 2...

**Comment by SimonWpt** [comment]
I am missing the feature, too. There are several webpages, where you have to fill on the first page the username and on the next page the password. Keypass2 has the ability to fill via global auto-type only the password. This Hotkey is changeable.

References:
https://keepass.info/help/kb/keyb_shortcuts.html

**Comment by davidcava** [comment]
I am missing that too

**Comment by ccoenen** [comment]
Yet another thing that I (albeit less frequently) run into: services that b0rked their sign-in forms. Where the tab order is broken or where it varies for different ways of logging in.

I just logged into my phone company's internal site. And they broke Tab-Order, and with regular KeePass, I just needed to tab once more, hit <kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>Shift</kbd>+<kbd>A</kbd> and then enter - done.

Also, this is what sometimes happens when you fail to log in correctly for whatever reason: usually a login form comes back with blank password and prefilled username. Sweet! <kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>Shift</kbd>+<kbd>A</kbd>. Done.

**Comment by ccoenen** [comment]
Github asks you to verify your password when you do security critical things (for example: delete a repository). Hit <kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>Shift</kbd>+<kbd>A</kbd>. Done.

**Comment by randoogle** [comment]
I run into this quite a bit. Without getting into too many details, sometimes I need to get into a virtual machine that doesn't have it's network working yet. The only console I have access to, does not allow for copy-paste, an so I need to rely on auto-type to get the password in (but just the password).

Another instance where this comes in handy is when I RDP into a windows server and need to change my account password. Windows doesn't allow copy-paste here, and so I have to rely on auto-type. But again, they aren't asking for username+password, they are asking for old password + new password + new password.

I really miss the ability to do this in KeePassXC.

**Comment by droidmonkey** [comment]
Technically you can do this right now. Simply go to the Auto-Type tab when editing an entry. There you can define a custom default sequence for that entry. You can also add additional sequences for specific window titles. Therefore, for your example, you can define a password only sequence for the virtual machine window and when you use the Auto-Type button it will ask you which sequence you want to use.

**Comment by randoogle** [comment]
> Technically you can do this right now. Simply go to the Auto-Type tab when editing an entry. There you can define a custom default sequence for that entry. You can also add additional sequences for specific window titles. Therefore, for your example, you can define a password only sequence for the virtual machine window and when you use the Auto-Type button it will ask you which sequence you want to use.

I tried this, but the window-title thing didn't work for either case. Maybe I'm not doing it right. I added a window association with a different sequence (password only) and click OK. After clicking on the "perform auto-type" button, it just types the default sequence instead, I don't see any other options popping up.

**Comment by droidmonkey** [comment]
Only the global Auto-Type shortcut key pops up the selection dialog

**Comment by randoogle** [comment]
> Only the global Auto-Type shortcut key pops up the selection dialog

Ah, yes, it's not super straight-forward, but it works. Just have to go through a few global shortcuts till I found one that worked.

Thanks for the info.

**Comment by adityaduggal** [comment]
This feature is a must in keepasxc for many users like me who have been using keepass2 just because of this freedom the keepassxc is still not as good as keepass2.

**Comment by gilles007-** [comment]
I'm just trying keepassXC.
I need this functionnality too and i see that has been asked since 2 years now.

**Comment by kingsinger** [comment]
I'd agree. I use Keepass 2.0 on my PC, but I recently got a new Mac also, so I've been using KeepassXC with that machine. 
There are so many situations where you go to a site and it auto-populates your e-mail address. 

At that point, it would be great to be able to just hit a different keyboard short-cut and have KeepassXC auto-type in just the password. 

It's kind of unpredictable when this feature will be needed, and it's enough of an edge situation that it's not efficient to program that password only into the auto-type rules for each user account you have, especially if you have a lot of them, as many people do.

Hope this gets sorted out before too long. Seems like it's been hanging around for a while.

**Comment by Perry3D** [comment]
droidmonkey already added this feature to the next milestone 2.6.1. I think we can stop spamming this issue with comments.

**Comment by mekaneck** [comment]
> We have no desire to add more global hotkeys. 

Perhaps an alternative would be to allow the user to customize them if they decide they want them. Something like the following:
![auto-type](https://user-images.githubusercontent.com/48502913/104963220-abaf5a00-599f-11eb-9749-cf9648f069a9.png)

**Comment by droidmonkey** [comment]
Oh snap I like this

**Comment by qx9qx9** [comment]
As someone who was interested in switching from Keepass to KeepassXC just for proper dark mode I was looking for this password only shortcut. After discovering this shortcut didn't exist I figured out a work around for this. But it requires extra steps.

Go into settings under General -> Auto-Type and enable "Always ask before performing Auto-Type".
When you use the global auto-type shortcut this will always pop up the auto-type dialog box, you can then press enter to do the normal auto-type sequence, or you can press CTRL-1 for username only, or CTRL-2 for password only.

Just making this comment in case any one else is searching for a solution.
