### ISSUE TITLE
Downloading favicon usually leaves zombie dialog window, closing window crashes (segfault)  KeepassXC

### ISSUE THREAD

**Issue by acesabe** [keepassxreboot/keepassxc#2095]
## Issue outline
Happens 90% of the time, when using the download favicon feature, when clicking the Download favicon button, the resulting pop up progress dialog window remains open/visible (sometime 2 or three of them), see screenshot. Operation usually completes correctly and zombie windows can be moved out of the way and app continues to function as expected, however closing any of these windows will close/crash the app.

![image](https://user-images.githubusercontent.com/1364486/42378406-7d8b505a-8127-11e8-8dc8-f74fa32b22cf.png)

## Expected Behaviour
Pop up window should close automatically unless requires user input.

## Current Behaviour
Window remains zombified, crashing app if closed

## Steps to Reproduce (for bugs)
On occasion from the Icon tab just directly clicking the Download favicon button may complete the operation without issue, but not reliably
1. Got to edit entry > Icon tab
2. Click Use custom icon radio button (optional)
3. Click Download favicon button
4. Issue is seen 
(running from cli error segfault message is seen)

## Context
Issue been present for me for last couple of months 

## Debug Info
KeePassXC - Version 2.3.3
Revision: 0a155d8

Libraries:
- Qt 5.5.1
- libgcrypt 1.8.1

Operating system: Ubuntu 16.04.4 LTS
CPU architecture: x86_64
Kernel: linux 4.4.0-130-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

If any more relevant info/logs etc required, please point me to where and I will provide gladly!

[Edit]
Found a log I had taken previously that may be relevent:

`propsReply "An AppArmor policy prevents this sender from sending this message to this recipient; type=\"method_call\", sender=\":1.143\" (uid=1001 pid=26538 comm=\"keepassxc \") interface=\"org.freedesktop.DBus.Properties\" member=\"GetAll\" error name=\"(unset)\" requested_reply=\"0\" destination=\"org.freedesktop.NetworkManager\" (uid=0 pid=857 comm=\"/usr/sbin/NetworkManager --no-daemon \")"
nmReply "An AppArmor policy prevents this sender from sending this message to this recipient; type=\"method_call\", sender=\":1.143\" (uid=1001 pid=26538 comm=\"keepassxc \") interface=\"org.freedesktop.NetworkManager\" member=\"GetDevices\" error name=\"(unset)\" requested_reply=\"0\" destination=\"org.freedesktop.NetworkManager\" (uid=0 pid=857 comm=\"/usr/sbin/NetworkManager --no-daemon \")"
"Object path cannot be empty"
QObject::startTimer: Timers cannot have negative intervals
Segmentation fault`

**Comment by droidmonkey** [comment]
I fixed this for 2.3.4 already

**Comment by acesabe** [comment]
Missed #1936 ! Title description differs slightly but yes, is same bug. Great stuff, great feature, look forward to 2.3.4!
