### ISSUE TITLE
Add keyboard shortcut to search bar background text

### ISSUE THREAD

**Issue by apiraino** [keepassxreboot/keepassxc#2096]
Add in the `Entries` menu group a "Search password / item (CTRL+F)" item to let users know there's a shortcut to jump into the search form without using the mouse (I've discovered this shortcut by chance because of muscle memory).

## Expected Behavior
Add a "Search password (CTRL+F)" item in the `Entries` menu group

## Current Behavior
The CTRL+F shortcut works, the search feature too, but they're not "documented" in the menu

## Debug Info
KeePassXC - Version 2.3.3
Revision: 0a155d8

Libraries:
- Qt 5.9.5
- libgcrypt 1.8.1

Operating system: Ubuntu 18.04 LTS
CPU architecture: x86_64
Kernel: linux 4.15.0-24-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by erdii** [comment]
nice to see that there actually IS a search shortcut! 👍

**Comment by droidmonkey** [comment]
CTRL+F is the universal keyboard shortcut for search (aka find). I would support adding this to the search bar background text: "Search (CTRL+F)..."
