### ISSUE TITLE
No AppIndicator Icon in Ubuntu 18.04

### ISSUE THREAD

**Issue by tiotrom** [keepassxreboot/keepassxc#2097]
I have GNOME Shell 3.28.1 and tested with snap (2.3.3), flatpak (2.3.3), or apt (2.3.1+dfsg.1-1). Only the apt (2.3.1+dfsg.1-1) works to display the icon, the other ones do not. 

I tried extensions such as TopIcons Plus https://extensions.gnome.org/extension/1031/topicons/ but in vain.

**Comment by droidmonkey** [comment]
Are you referring to the notification tray icon?

**Comment by tiotrom** [comment]
Yes indeed. Screenshot only this https://user-images.githubusercontent.com/34804533/42411455-788110ec-81fc-11e8-8e83-0397150f6d5e.png to showcase there is no tray icon

**Comment by tiotrom** [comment]
Works with appimage btw. I just tested. Will stick with that for now but the above bug is still relevant for flatpak and snap.

**Comment by droidmonkey** [comment]
Technically Gnome is doing away with notification tray icons.

**Comment by tuxmouraille** [comment]
Hello,
Did you try to restart Gnome-Shell: Alt+F2 , type r + return.
I have a similar issue, no icon on logon, due to a bug of the Gnome-Shell's Ubuntu AppIndicator extension.

**Comment by tiotrom** [comment]
Yes of course I restarted the shell. Only the appimage works to display the app indicator.

**Comment by hifi** [comment]
This looks related although it works the other way around for this reporter:

https://bugzilla.redhat.com/show_bug.cgi?id=1601033

**Comment by tuxmouraille** [comment]
Hello,
I solved my problem by removing indicator-application and indicator-common.

**Comment by droidmonkey** [comment]
Awesome, thanks for reporting back
