### ISSUE TITLE
Not saving new entries and no password generator

### ISSUE THREAD

**Issue by tiotrom** [keepassxreboot/keepassxc#2099]
I am not sure if this is a lack of feature or a bug, but when I register on a website I would expect to have a password generator option from KeePassXC to generate a new password in the Tab (not open the app on my computer, generate password, copy and paste to the tab) + I would expect after I enter all details for registration the KeePassXC to save them, but it doesn't and not even asking to do so. I use Ubuntu 18.04 + KeePassXC appimage + KeePassXC-Browser. Everything else works just fine.

**Comment by droidmonkey** [comment]
This has already been reported over in the keepassxc-browser repository. Also please don't delete the issue template.

**Comment by tiotrom** [comment]
Ok thanks
