### ISSUE TITLE
Diceware-like passphrase generator

### ISSUE THREAD

**Issue by TheZ3ro** [keepassxreboot/keepassxc#21]
All the details in this PR for keepassx/keepassx https://github.com/keepassx/keepassx/pull/181

**Comment by droidmonkey** [comment]
Seems useful for edge cases, currently low priority.

**Comment by TheZ3ro** [comment]
Can't we just "port" the changes in the PR from keepassx?

**Comment by davad** [comment]
I'd love to see this feature implemented. There are a few accounts that I like remembering a password, and passphrases are a nice way to create a memorable, high-entropy password.

What can I do to help get this feature implemented?

**Comment by TheZ3ro** [comment]
I will start developing this in the next few days. Right now we are very busy fixing the 2.1.0 release

**Comment by davad** [comment]
@TheZ3ro If I have time before you get started, I'll see if I can rebase the PR from keepassx/keepassx#181

**Comment by TheZ3ro** [comment]
If you do rebase that PR please maintain the commit history/authorship (e.g. cherry-pick)

**Comment by phoerious** [comment]
For transferring old branches, git rebase --onto is usually the way to go.
But to be honest, I don't really like the user interface of that implementation over there.

**Comment by davad** [comment]
@phoerious It's not my favorite UI either, but we might as well use it as a starting point instead of beginning from scratch.

**Comment by TheZ3ro** [comment]
Yes, we can make the UI like the current generator

**Comment by davad** [comment]
@phoerious I did the rebase without `--onto`. It was actually a pretty clean diff. I think there were only two commits with conflicts, and just a few conflicting lines in each.

I haven't compiled it yet. I'm building the docker image right now to see what it looks like.

**Comment by t4777sd** [comment]
I think this is a GREAT feature. One question I have though is if we can specify the word list? For example, this is used a lot in cryptocurrency wallets. And, these wallets usually follow a standard where the words are selected from a predefined set: https://github.com/bitcoin/bips/blob/master/bip-0039/english.txt

So, using this extension, can we define the word-set that will be used when creating the phrased based password?

**Comment by TheZ3ro** [comment]
I think it should be an option. It's not hard to implement since the wordlist is loaded from file

**Comment by aswolf** [comment]
I have also been looking for a feature like this for a long time! I am looking forward to its incorporation into KeePassXC!
