### ISSUE TITLE
Snap: Open window with left click on tray icon

### ISSUE THREAD

**Issue by datamaan** [keepassxreboot/keepassxc#210]
## Current Behavior
If I left-click on the tray-icon, nothing happens.

## Suggested Behavior

It would be nice if a left-click on the tray-icon would open or toggle the main-window.

**Comment by phoerious** [comment]
Can you specify which platform you are on and which version you are using? I can't reproduce this behavior. For me, left-clicking the icon toggles the main window.

**Comment by datamaan** [comment]
I just noticed that this works fine when using the AppImage or compiling from source, but does not work with the snap package.

I installed via `sudo snap install keepassxc`

System: KDE neon 5.8 / Ubuntu 16.04
keepassxc version: 2.1.0

**Comment by phoerious** [comment]
Okay, thanks for the info. Can somebody confirm this?

**Comment by Gerii** [comment]
Yes, same here on Plasma 5/KDE neon. It also does not use the Breeze theme and mouse cursor, which makes it really ugly compared to 2.0.3-http installed via a deb package.

**Comment by phoerious** [comment]
The theming issue is a general problem with self-contained Linux binaries. The themes need to be shipped with the application or else it will use the default Qt look. We'll try to ship some nicer themes with the AppImage and Snap Package.

**Comment by droidmonkey** [comment]
I am really not impressed with the whole snap thing... it needs a lot of work.

**Comment by phoerious** [comment]
Also snaps are supposed to be cross-platform, but I can't even install it successfully on my Arch system.

BTW @droidmonkey I think you should replace the `[desktop-qt5]` in the snapcraft.yaml file with `[desktop-ubuntu-app-platform]` for better integration with the desktop. At least that's what https://insights.ubuntu.com/2016/11/17/how-to-create-snap-packages-on-qt-applications/ says.

**Comment by droidmonkey** [comment]
Interesting that was written AFTER the guidance I read (from October) that desktop-qt5 was the hot thing to use...

**Comment by phoerious** [comment]
Is this still an issue with the updated Snap package?

**Comment by droidmonkey** [comment]
This is no longer an issue as I have been able to use the tray icon with the new snap. Now, granted the tray icon itself is not showing up... different issue.

**Comment by schiorean** [comment]
> Now, granted the tray icon itself is not showing up... different issue.
I can confirm, Snap install it show the "empty" tray icon.
