### ISSUE TITLE
Fork + minor tweaks = Secure note/journal app

### ISSUE THREAD

**Issue by Emily7777** [keepassxreboot/keepassxc#2104]
There is a dearth of secure note taking / journal apps.  None I've reviewed do what is needed.

If KeepassXC added date-created & modified to the export, tags field, and a rich text editor, it would do everything needed.

If the team forked it, and added those features, doing so would leverage all the hard work you guys have put into it to capture a huge, hungry crowd that is not yet served by any existing software.

I know I'd send some Bitcoin that way to get such a fork.

**Comment by droidmonkey** [comment]
I was actually thinking of a similar fork. An app that also stored and displayed other useful mime types like pictures and audio. 

I was going to toy with some ideas when implementing the template feature.

**Comment by TheZ3ro** [comment]
Just a side-note: there are currently Secure note/journal app. Take a look at Turtl or StandardNote

**Comment by Emily7777** [comment]
Turtl doesn't allow exports.  It locks you in.  It doesn't allow offline note taking either.  

Standard allows offline note taking, but no exports either.

I'm learned the hard way, don't get locked into any solution.  And, I must be able to work offline.  If it can't export, and/or requires constant connection, it's a no-go regardless of other features it might have.

**Comment by droidmonkey** [comment]
What kind of export would you look for? XML, HTML?

**Comment by Emily7777** [comment]
Any commonly supported format that would allow me to easily move all data to another platform.

CVS seems to be commonly supported.  XML possibly.

Whatever format is chosen, ideally it would maintain rich text editing and image data with the entry.

**Comment by TheZ3ro** [comment]
CVS doesn't support images so you will have a zip with CVS text + images/attachments. 
XML with base64 data should do it (KeePassXC already does this)

I think we can do this pretty easily with Entry Templates and Markdown support in Notes

**Comment by Emily7777** [comment]
Add some import tools to move notes from other platforms and I'm sold.  Give me your Bitcoin address ;)

For imports, some support for XML, CVS, and possibly zipped folders containing TXT, RTF notes, with the import tool parsing the notes with file creation/modifaction meta data would be what I'd like to see.

**Comment by droidmonkey** [comment]
@Emily7777 this app seems like it would fit your needs: https://github.com/pbek/QOwnNotes

It includes support for AES-256 encryption and it operates on plain text files.

**Comment by metbril** [comment]
@Emily7777 I have added a feature request for TXT and RTF editing for feature parity with KeePass 2.x for Windows.

#2529

**Comment by droidmonkey** [comment]
Going to close this one since we do not plan to implement this as there are other options out there.
