### ISSUE TITLE
Selecting Second Group Crashes KeePassXC

### ISSUE THREAD

**Issue by linuxminty** [keepassxreboot/keepassxc#2105]
After opening KeePassXC, I can select one group (an entry listed in the left window pane) without problem, but when I try to select another group in the same window, KeePassXC crashes every time.

This is the output from /var/log/syslog: keepassxc[18195]: segfault at 11 ip 00007ff3ebf49ae8 sp 00007ffd225f1c90 error 4 in libQt5Core.so.5.5.1[7ff3ebcf9000+4c5000]

Another crash is produced consistently by typing a second character in the search box. Output from /var/log/syslog is: kernel: [67342.636585] keepassxc[17302]: segfault at 561900000011 ip 00007fb22959aae8 sp 00007ffd042d5850 error 4 in libQt5Core.so.5.5.1[7fb22934a000+4c5000]

My system: Linux Mint 18.3, Cinnamon desktop
                keepassxc_2.3.3-0ppa1~xenial1_amd64

**Comment by linuxminty** [comment]
Because this PPA installation of KeePassXC was so unstable, I removed it using Synaptic Manager and installed the flathub selection from Software Manager. The application now appears to be working as it should.

**Comment by phoerious** [comment]
This is a duplicate of #335. The bug is in the Qt version shipped with Ubuntu 16.04, which Mint 18.3 is based upon. Please use your AppImage instead.
