### ISSUE TITLE
Don't create duplicated icons

### ISSUE THREAD

**Issue by alexanderadam** [keepassxreboot/keepassxc#2106]
It would be nice to avoid duplicated icons in general (and making the database file smaller). This check should happen on general but if #1950 gets implemented it probably should be triggered within the cleanup process as well.

## Expected Behavior
No creation/integration of an icon that is already there. Maybe create a check via a checksum?

## Current Behavior
Well, I just saw that I have the same icon at least twice.

## Context

I love the favicon feature and it definitely helps visually to identify records. I would even like to have it fetched automatically when an URL is pasted or [added via browser extension](https://github.com/keepassxreboot/keepassxc-browser/issues/86) but that is probably another issue. :wink:

**Comment by droidmonkey** [comment]
I fixed the reason why this was happening in  #2011. Basically the icon was being stored in the database but compared to an icon if different size and determine it was different. I moved the scaling before the check for duplicate and it now works as intended.

**Comment by alexanderadam** [comment]
Awesome, thank you @droidmonkey!

1. Do you know when it will land in the Ubuntu PPA?

Do I interpret this correctly that [an alert message is triggered when someone tries to redownload a favicon](https://github.com/keepassxreboot/keepassxc/pull/2011/files#diff-26f55b824b03f947ce9777d4086c5f66R274)?

If so:
2. is the original selected afterwards? Because otherwise it may be difficult to find it if there are already a lot icons integrated, right? And if the user wants this icon it just makes sense to select it, regardless whether it is integrated already or not.
3. Is there any logic that removes duplicates in existing databases at the moment?

**Comment by droidmonkey** [comment]
This fix will be in 2.4, although i can port the fix for this exact issue into 2.3.4 pretty easily.

The duplicate icon that is in the db is selected. There is no way to clear duplicate icons automatically right now.

**Comment by alexanderadam** [comment]
@droidmonkey should I create another issue for that or can we simply use this issue here for the removal of duplicated icons?

And could you please answer 2 as well?

Thank you in advance!

**Comment by droidmonkey** [comment]
A new issue would be best. For #2, the duplicate icon already in the database is selected if you try to load it again.

**Comment by alexanderadam** [comment]
[done](https://github.com/keepassxreboot/keepassxc/issues/2110). Thank you!
