### ISSUE TITLE
KeePassXC only starts at 2nd attempt

### ISSUE THREAD

**Issue by toxpal** [keepassxreboot/keepassxc#2108]
KeePassXC 2.3.3 on antergos KDE (4.17.5-1-ARCH kernel, Qt version 5.11.1). For some reason, I can only launch program at 2nd attempt.

When system boots and I click program's icon, I see KeePassXC entry in task manager for about 3 seconds (but program itself is not launched) and then it auto-closes.

Clicking the icon again starts KeePassXC immediately and without any problems. If I close program (or reboot system) it's the same again - running program for the 1st time only displays a self-closing entry in task manager, and running program for the 2nd time works great,

Running via terminal I always get this error:

```
$ keepassxc
QObject::startTimer: Timers cannot have negative intervals 
```
...and then nothing happens. In other words, I can't launch program from terminal at all.

**Comment by vexillia** [comment]
+1 this time on Ubuntu 16.04 LTS.  I've removed a startup entry because of this: it's pointless at the moment.

**Comment by droidmonkey** [comment]
Are you use an appimage, snap, what?

**Comment by vexillia** [comment]
Deb file

**Comment by hifi** [comment]
For the record the timer warning does not prevent the application from starting and seems unrelated.

**Comment by droidmonkey** [comment]
I cannot reproduce this issue

**Comment by toxpal** [comment]
> For the record the timer warning does not prevent the application from starting and seems unrelated.

Thanks for your input. I'm new to Linux, so maybe it's a stupid question, but how do I start KeePassXC via terminal then? Typing **keepassxc** displays _QObject::startTimer: Timers cannot have negative intervals_ and nothing happens, even if I leave terminal running for minutes.

**Comment by hifi** [comment]
@toxpal You are starting it correctly. It appears that the program is running (it doesn't return you to the prompt) but the window is not displayed for any number of reasons.

**Comment by droidmonkey** [comment]
Im wondering if you enabled "Minimize on startup"

**Comment by vexillia** [comment]
I was using the "Minimize on startup" option.

**Comment by toxpal** [comment]
My bad, "Minimize on startup" option was enabled. Strange enough, that no icon would appear in notification area (even if it's enabled). Anyhow, the issue is now solved. Thank you all for your help!

**Comment by droidmonkey** [comment]
Awesome thanks!
