### ISSUE TITLE
Automatic removal of unused icons and bulk deletion of icons

### ISSUE THREAD

**Issue by alexanderadam** [keepassxreboot/keepassxc#2110]
This is basically [a follow-up of issue 2106 (as proposed from @droidmonkey)](https://github.com/keepassxreboot/keepassxc/issues/2106#issuecomment-404492626).

It would be nice to avoid duplicated icons in general (and making the database file smaller). This check should happen in general but if #1950 gets implemented it probably should be triggered within the cleanup process as well.

## Expected Behavior
Duplicated icons should be removed when the database is saved. Entries that use a duplicated icon will get the first integrated icon instead.

## Current Behavior
Well, I just saw that I have the same icon at least twice. [@droidmonkey implemented a check when trying to add a new icon](https://github.com/keepassxreboot/keepassxc/issues/2106#issuecomment-404197749) but this obviously doesn't help for existing databases or if someone uses additionally another Keepass client.

## Context

I love the favicon feature and it definitely helps visually to identify records. And this feature would help to avoid a useless increase of the database.

**Comment by droidmonkey** [comment]
For implementation, make it possible to select multiple icons in the UI for bulk deletion.

**Comment by alexanderadam** [comment]
> For implementation, make it possible to select multiple icons in the UI for bulk deletion.

Do you mean manual selection?
If so:
Why would it need any manual interaction? :thinking: 
I thought more of a _automatic_ detection of duplicated or unused icons.

**Comment by droidmonkey** [comment]
My comment was not related to the automated clearing capability.
