### ISSUE TITLE
FR: Show full path

### ISSUE THREAD

**Issue by gerroon** [keepassxreboot/keepassxc#2114]
Hi

It would be so nice if KeepassXC shows the full path to the file. It is hard to know where the file originated from especially on Linux, because it does not remember the last open path.

Maybe this stuff is disabled for security reasons but it would be nice if it is provided as some kind of setting.

thanks

**Comment by droidmonkey** [comment]
Which file are you talking about? Where doesn't it show the path (which screen)??

**Comment by gerroon** [comment]
Hi

Sorry, I should have been more articulate about it. I actually meant the currently opened .kbdx file in the app. There is no place that shows the actual location (on the storage) of the file, as far as I can tell.

**Comment by droidmonkey** [comment]
You can set a descriptive name for your database. Showing the filename typically takes a ton of space. Check out the database settings, you can even set that to the name of the database file if you want.

**Comment by ngleb** [comment]
I also encountered with a problem where I need to see a fullname of the file (and path as well) and there's no single place where I can see it.

I would prefer to be it in the title bar of the window.

I know I can set the descriptive filename, but it won't resovle my problem where the full path and filename were needed.

**Comment by TheZ3ro** [comment]
I think the titlebar is a good place for the fullpath as well.

Many other programs use the titlebar (like GIMP, eye-of-gnome, LibreOffice, etc)

**Comment by droidmonkey** [comment]
Tracked in #2034
