### ISSUE TITLE
Ungray "Save Database" button after a change

### ISSUE THREAD

**Issue by sgbirch** [keepassxreboot/keepassxc#2115]
## Expected Behavior

The normal convention for a save button is that it remains grey until the data in the app are
modified.  At that time the button becomes available to press.

## Steps to Reproduce (for bugs)

1. Observe that the Save button is grayed out
2. Make a change to the data
3. Observe that the save button is still gray

## Debug Info

2.3.3

Libraries:
- LIBS

Operating system: OSX (Apple Mac)
CPU architecture: ARCH
Kernel: KERNEL

Enabled extensions:
- EXTENSIONS

**Comment by droidmonkey** [comment]
You have autosave on.

**Comment by sgbirch** [comment]
(Blush)
