### ISSUE TITLE
[OSX 10.12] Global autotype hotkey issue

### ISSUE THREAD

**Issue by chimericdream** [keepassxreboot/keepassxc#212]
## Expected Behavior
Pressing the configured auto-type hotkey sequence should trigger auto-type in matching windows.

## Current Behavior
I set the global auto-type hotkey in the preferences, but when I press it, nothing happens.

## Steps to Reproduce (for bugs)
1. Set the shortcut
2. Use it

## Your Environment
* KeePassXC 2.1.0
* Qt 5.7.0
* OS X 10.12

**Comment by TheZ3ro** [comment]
Does the autotype sequence include the Shift key? If yes, I also have this bug, try with another sequence without Shift

**Comment by chimericdream** [comment]
I tried several combinations with and without Shift, Option, Command, and Control. None worked.

**Comment by rockihack** [comment]
Are you using Chrome? In this case the global hotkey doesn't work.
You can still trigger autotype from the gui. Select an entry and press `Cmd + V`.

**Comment by chimericdream** [comment]
Yep. Turns out that is the issue. Is there a workaround, or am I limited to triggering it from the gui when using it with Chrome?

Also, if this isn't a bug in KPXC I can close the issue.

**Comment by phoerious** [comment]
I don't quite understand. Can you elaborate a little more on what doesn't work in combination with Chrome? I'm using Chrome as well with autotype and it works perfectly.

**Comment by rockihack** [comment]
This issue is mac os specific. I don't know why but the global hotkey api doesn't work with chrome.

**Comment by phoerious** [comment]
Oh, right. I missed that.

**Comment by tofra** [comment]
I have the same issue. I hope a fix can be find soon so I can switch from Keepass 0.4.3 to this version.

**Comment by TheZ3ro** [comment]
Seems a bug in chrome to me, Isn't it?

**Comment by droidmonkey** [comment]
Yah this isn't a bug in KeePassXC. Likely Chrome is trapping all keyboard shortcuts to itself.

**Comment by tofra** [comment]
It works with Safari. Damn Chrome..

**Comment by thousandsofthem** [comment]
can confirm, same behavior. any thoughts how to proceed?

**Comment by rockihack** [comment]
I fixed Global Autotype in Google Chrome :)

https://github.com/rockihack/keepassx/commit/617adc4e11f7ed198058e394291b1ac3c30bb9ef

**Comment by phoerious** [comment]
Would you like to submit a PR for that?

**Comment by Ghosthree3** [comment]
Auto-type refuses to work here either on Linux, I had it set to Ctrl+Alt+Shift+A as I had in KeePassX but no good. I tried setting it to just Ctrl+A as well as trying it in a gedit titled with Google to try and provoke an easy match and see if its a browser issue (Pale Moon here) but it didn't work even then.

I know it's not directly related to the thread since I'm on Linux not OSX but I figure there's a good chance it's related.

**Comment by phoerious** [comment]
Could you create a new issue report for that, please? Also don't forget to tell us which binary package you are using etc. as I'm not able to reproduce it.
