### ISSUE TITLE
Liberapay is in trouble

### ISSUE THREAD

**Issue by his10** [keepassxreboot/keepassxc#2121]
In case you're not aware of it, you should withdraw your income from your Liberapay wallet as soon as possible: https://medium.com/liberapay-blog/liberapay-is-in-trouble-b58b40714d82

You do not want to ignore this: https://github.com/liberapay/liberapay.com/pull/1169#issuecomment-404459576

@droidmonkey @TheZ3ro

**Comment by droidmonkey** [comment]
Wow thanks for the heads up. I hope no one uses MongoPay in the future as a result of this ridiculous treatment.

**Comment by droidmonkey** [comment]
Awesome... So my withdrawal failed. Looks like €13 can be sucked into the vacuum...

**Comment by TheZ3ro** [comment]
Thanks for the heads up! Anyway seems that after the migration away from Mangopay the blocked money will be available again (?)

**Comment by droidmonkey** [comment]
It would be highly illegal for Mangopay to just get off with the funds. They could pull a PayPal and freeze the accounts per their terms of service if they suspect illicit activity. The whole process seems broken to me.
