### ISSUE TITLE
Error Install KeepassXC

### ISSUE THREAD

**Issue by kalengkerupuk** [keepassxreboot/keepassxc#2123]
I installed KeePassXC to replace KeePassX and it worked for the first time. It started crashing and couldn’t open anymore after a while. Uninstalled and reinstalled few times but still didn’t work.

OS: Yosemite 10.10.5
KeePassXC version: 2.3.3

![keepassxc_error](https://user-images.githubusercontent.com/41176006/42751805-2acab774-8916-11e8-9d7a-a923419f152f.png)

About us: 
We are 2 digital security trainers from Indonesia doing a UX workshop with 10 digital security training participants to look at some tools and collect feedback on user experience.

**Comment by droidmonkey** [comment]
You are using a very old version of OS X.

**Comment by kalengkerupuk** [comment]
Thank you for your response and recommendation!
