### ISSUE TITLE
Add [optional?] confirmation before "destructive" things like group deletion

### ISSUE THREAD

**Issue by alexanderadam** [keepassxreboot/keepassxc#2125]
I just deleted a whole group be accident because I "misclicked" somehow, wasn't even sure and just found out by looking into the Recycle bin.
It would be nice to have at least an optional confirmation dialogue to prevent those cases. There is a confirmation dialogue before the final deletion in the Recycle bin so maybe it would be possible to activate it for regular entries as well.

## Expected Behavior
Before clicking a confirmation dialogue should appear.

## Current Behavior
A deleted group just disappears. No other verbose information about this.

## Steps to Reproduce (for bugs)

1. Open context menu of an entry
2. Click on Delete Group

## Context
I described it already.

## Debug Info
KeePassXC - Version 2.3.3
Revision: 0a155d8

Libraries:
- Qt 5.9.1
- libgcrypt 1.7.8

Operating system: Ubuntu 17.10
CPU architecture: x86_64
Kernel: linux 4.13.0-46-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by droidmonkey** [comment]
Good idea

**Comment by Happyman0815** [comment]
Would be a good idea. At the moment, all you have to do is press delete button on your keyboard and your key/entry is gone. This is not good. At least make such a feature optional. My current workaround is not to automatically save the DB after changes.

**Comment by droidmonkey** [comment]
It goes to your recycle bin in the database by default.

![image](https://github.com/keepassxreboot/keepassxc/assets/2809491/59d3d852-6100-4390-a97c-3c02660f4c90)
