### ISSUE TITLE
Auto-type error

### ISSUE THREAD

**Issue by PurpleCodeCollective** [keepassxreboot/keepassxc#2127]
Hi team,
I could never perform auto-type. Tried it few times for Facebbok and Twitter using two different machine.

OS: El Capitan 10.11.6
Browser: Firefox Quantum 61.0.1
KeepassXC version: 2.3.3

OS: Wimdows 10
Browser: Firefox Quantum 61.0.1
KeepassXC version: 2.3.3

![keepass-auto](https://user-images.githubusercontent.com/41277861/42798431-eeb250e6-89bd-11e8-9f9a-8a1b61025aec.png)

**Comment by droidmonkey** [comment]
What doesn't work about it? You need to be more specific.
