### ISSUE TITLE
Restore From Systray Not Standard

### ISSUE THREAD

**Issue by KitchM** [keepassxreboot/keepassxc#2130]
## Expected Behavior
When I select the icon in the systray, it should restore program.

## Current Behavior
Selecting the program icon in the systray gives me a context menu instead of opening the program.

## Possible Solution
Just make the operation standard with other programs in the systray.  It must restore when selected.

## Steps to Reproduce (for bugs)
1. Minimize program to systray.
2. Select icon in systray.
3. See context menu instead of restoring program.
4.

## Context
Most users of the systray expect that, for right-handed mouse users, the left button will restore and the right button will open context menu.  Deviating from this expected and standardized behaviour causes loss of functionality and efficiency.

## Debug Info
KeePassXC - Version 2.3.1
Revision: 2fcaeea
Distribution: AppImage

Libraries:
- Qt 5.9.4
- libgcrypt 1.8.1

Operating system: Ubuntu 14.04.5 LTS
CPU architecture: x86_64
Kernel: linux 4.4.0-130-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

Thank you.

**Comment by hifi** [comment]
Works for me with 2.3.3 on Xfce. Clicking once with the left mouse button restores or minimizes/hides the window and right mouse button shows a context menu.

**Comment by phoerious** [comment]
I assume you are using Unity as your desktop environment? Unfortunately, this is Unity's fault. They had some questionable design decisions to trigger a right click even on both left and right click for tray icons. There is no way we can fix this. It should work as expected with any other desktop environment.

**Comment by apfelchips** [comment]
This is also a problem on macOS.

Since the current menu isn't very useful anyway, can't we just get rid of it and make the window restore by default?

**Comment by droidmonkey** [comment]
See #149
