### ISSUE TITLE
Add notice about Yubikey configuration

### ISSUE THREAD

**Issue by greaka** [keepassxreboot/keepassxc#2136]
## Expected Behavior
Program detects a plugged in yubikey

## Current Behavior
No yubikey is detected

## Steps to Reproduce (for bugs)
1. Open any database
2. Go to change master password
3. activate challenge response

## Context
I am using a yubikey 4c on an usb A 2.0 port via an adapter. The yubikey is working fine on every other service

## Debug Info
KeePassXC - Version 2.3.3
Revision: 0a155d8

Bibliotheken:
- Qt 5.10.1
- libgcrypt 1.8.2

Betriebssystem: Windows 10 (10.0)
CPU-Architektur: x86_64
Kernel: winnt 10.0.17134

Aktivierte Erweiterungen:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by droidmonkey** [comment]
"via an adapter" what do you mean by that? It could be that the Yubikey is being locked by another application as well.

**Comment by greaka** [comment]
I tried "everything". Closing every Program that is able to use this key (Except Windows itself for example).
I can hit reload and the loading indicator goes off for a couple of seconds but thats it. When i remove the key, the loading indicator doesnt even appear.
As I said, other Programs can use it, even almost simultaniously

**Comment by greaka** [comment]
The "via an adapter": usb A 2.0 port in notebook -> male 3.0 A to female 3.0 C adapter -> yubikey 4c

the adapter is a 1 to 1 bridge. no multiple inputs etc. It is almost as small as the key itself

**Comment by greaka** [comment]
If you wish, I can create you a video how I log in to github, google, windows, how I sign git commits with it. It is working. I have the yubico tools installed and also successfully configured my key with them

**Comment by droidmonkey** [comment]
I guess my next question is have you configured one of the slots in the Yubikey for challenge response?

**Comment by droidmonkey** [comment]
I think we should display a notice saying to configure the yubikey, I'm going to leave this open cause there is a discoverability issue here.

**Comment by phoerious** [comment]
The new database settings widget in my wizard PR already contains links to documentation about setting up your YubiKey properly

**Comment by droidmonkey** [comment]
Implemented in 2.4.0
