### ISSUE TITLE
Auto-Type typing wrong passwords on Ubuntu 18.04

### ISSUE THREAD

**Issue by powerriegel** [keepassxreboot/keepassxc#2137]
Im using latest KeepassXC on Ubuntu 18.04. I tried on different machines (work and home). Auto-Type (Ctrl-V) always fails because the password is not typed correctly. This worked perfectly a few months ago. I auto-type into Firefox 61.0.1.

## Expected Behavior
Password should be typed correctly

## Current Behavior
Password is wrong

## Debug Info
KeePassXC - Version 2.3.3
Revision: 0a155d8

Bibliotheken:
- Qt 5.9.5
- libgcrypt 1.8.1

Betriebssystem: Ubuntu 18.04 LTS
CPU-Architektur: x86_64
Kernel: linux 4.15.0-24-generic

Aktivierte Erweiterungen:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by droidmonkey** [comment]
Firefox bug, duplicate
