### ISSUE TITLE
Window title bar shows ampersand when switching between multiple databases (Linux)

### ISSUE THREAD

**Issue by groland11** [keepassxreboot/keepassxc#2146]
If you have multiple databases open, and you switch between them by clicking on the tabs, the window title bar shows an ampersand in the database name.

## Expected Behavior
Window title: "test.kdbx - KeePassXC"

## Current Behavior
Window title: "test.&kdbx - KeePassXC"
(the position of the ampersand seems to change every time you open a database)

## Possible Solution
Show the actual database name in window title bar

## Steps to Reproduce (for bugs)
1. Open several databases at the same time (test.kdbx, home.kdbx)
2. Change databases by clicking on tabs
3. Window title: "test.&kdbx - KeePassXC", "ho&me - KeePassXC"

## Context
Using KDE desktop on Ubuntu 18.04

## Debug Info
KeePassXC - Version 2.3.1
Revision: 2fcaeea

Libraries:
- Qt 5.9.5
- libgcrypt 1.8.1

Operating system: Ubuntu 18.04 LTS
CPU architecture: x86_64
Kernel: linux 4.15.0-23-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by hifi** [comment]
No repro on 18.04 with Xfce when using 2.3.1 from packages. That may be a KDE unique issue as I remember seeing it on Fedora 27 with KDE.

**Comment by droidmonkey** [comment]
This might be related to KDE wanting to automagically create keyboard hotkeys out of random crap.

**Comment by phoerious** [comment]
I think it is.
