### ISSUE TITLE
Proxy exits when encountering utf-8 characters

### ISSUE THREAD

**Issue by Pikrass** [keepassxreboot/keepassxc#2148]
## Expected Behavior
keepassxc-proxy should be able to communicate with keepassxc no matter the locale it is using.

## Current Behavior
If keepassxc is run under some locales (in my case, fr_FR.UTF-8), keepassxc-proxy exits whenever a user/pass field pair is encountered on a web page in the browser. The connection being broken, the browser plugin displays an error ("Timeout or not connected to keepassxc"). Reconnecting works, until the next webpage with login fields.

## Possible Solution
Using strace, I looked up the messages the proxy and keepassxc were exchanging. I noticed the proxy exited a short time after these calls:
```
read(5, "{\"action\":\"get-logins\",\"error\":\"Aucun identifiant trouv\303\251\",\"errorCode\":\"15\"}", 76) = 76
write(1, "K\0\0\0{\"action\":\"get-logins\",\"error\":\"Aucun identifiant trouv\303\251\",\"errorCode\":\"15\"}", 80) = 80
```

Note it doesn't crash. It exits with a zero return value.

So I thought it must have something to do with the utf-8 character in the error field (corresponding to an "é"). I fired up keepassxc with LANG=C, and the problem disappeared.

## Steps to Reproduce
1. Install and configure keepassxc and the firefox plugin as instructed in the docs
2. Run keepassxc with LANG=fr_FR.UTF-8
3. Connect the browser plugin
4. Navigate to a web page with a login form

## Debug Info
KeePassXC - Version 2.3.3
Revision: 0a155d8

Libraries:
- Qt 5.10.1
- libgcrypt 1.8.3

Operating system: Debian GNU/Linux buster/sid
CPU architecture: x86_64
Kernel: linux 4.17.0-1-amd64

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by varjolintu** [comment]
I thought this was already fixed.. I'll give it a look.

**Comment by varjolintu** [comment]
I set the locale to `fr_FR.UTF-8` and ran KeePassXC. It was in french like it should be. Then went to a page with no credentials. I got the error to KeePassXC-Browser without any problems.

I checked the strace too and I saw two identical messages to yours. Still, keepassxc-proxy didn't quit. So I cannot reproduce this. Can you provide any additional info from strace, if available.

Another option is to compile a debug version of keepassxc-proxy, set it as a custom proxy in KeePassXC and debug it.
