### ISSUE TITLE
Start building packages for Ubuntu 18.10

### ISSUE THREAD

**Issue by a-dma** [keepassxreboot/keepassxc#2149]
The next iteration of Ubuntu is going to be out in October, I know it's a bit early, but it would be awesome if you could start building packages for it in the PPA so that people can start testing.

**Comment by phoerious** [comment]
Thanks for the reminder. I'll do that for the next release.

**Comment by phoerious** [comment]
I have uploaded a 2.3.4 package for Cosmic to the PPA.
