### ISSUE TITLE
[Windows] Icons are not downloading

### ISSUE THREAD

**Issue by sanyarnd** [keepassxreboot/keepassxc#2151]
## Expected Behavior
Download site icon and add it to the list.

## Current Behavior
Download process ends up with error immediately (error balloon is raised in instance I click on download button) for most (99%) of the sites, even with google cache support. 
I was unable to reproduce such behaviour on Linux machine, issue is confirmed on multiples Windows 10 PC. 
All of testing computers I've used are members of the same network.

I am using the latest (2.3.3) x64 build available from the website.

**Comment by droidmonkey** [comment]
This is likely fixed in 2.3.4, there was a small bug in the download code.

**Comment by sanyarnd** [comment]
@droidmonkey Just tried 2.34, same issue.
There are modal popups with downloading progress (with queries to <site>/favicon.ico and google cache), but download status is stucked at 0%.

**Comment by droidmonkey** [comment]
This seems to be a Windows 10 issue, but it does not occur on my computer. This is being tracked by #2265

**Comment by droidmonkey** [comment]
I figured out why icons are not downloading, it is due to missing openssl on your system. Please download here and install: https://slproweb.com/download/Win64OpenSSL_Light-1_0_2p.exe

**Comment by sanyarnd** [comment]
@droidmonkey It seems working, but I have an extra dialog popup with download progress after the successful download.

Also, is there any way to include required .dll's to the bundle? Or at least revert changes back to when everything worked?

**Comment by droidmonkey** [comment]
I opened a new issue to track that: #2489
