### ISSUE TITLE
Java Support

### ISSUE THREAD

**Issue by genericgym** [keepassxreboot/keepassxc#2152]
**Feature Request:**

I am developing some java software and need to store some credentials. 

I am not sure if Java can access KeyPass, or not,  Maybe it can, but there is a lack of documentation?

So I am either asking for a simple JavaAPI or some documentation.

thanks
graham

**Comment by hifi** [comment]
Look into projects that implement the KeePass database file format in Java.

This looks fine: https://github.com/cternes/openkeepass

**Comment by genericgym** [comment]
Thanks for the suggestion. That library looks very nice.

But I am left with a question. The library requires you to pass the master password. But I am thinking of using it in a scenario where the database is already open (e.g. the user opened it themselves, or maybe they opened it at login).

I am really trying to use Java to connect to an already open database ...

**Comment by phoerious** [comment]
Providing a Java-API means that we have to bundle JNI which we will not do, so we cannot fix your problem. Sorry about that.

**Comment by hifi** [comment]
@genericgym You can, however, use the browser integration API to connect in a generic way to an open KeePassXC instance.

See https://github.com/keepassxreboot/keepassxc-browser/blob/develop/keepassxc-protocol.md
