### ISSUE TITLE
Feature Request: Unlock KeePass database on login

### ISSUE THREAD

**Issue by genericgym** [keepassxreboot/keepassxc#2153]
I use KDE. I would like to have my keepass database unlocked by my login (both the first time I login or at a sleep/hibernate), so that I don't have to type my master password into keepass again before I use the browser extension.

I realize this is a potential security issue, but an option for this would be very nice for those who are prepared to take that risk.

**Comment by hifi** [comment]
You can create a start script for KeePassXC where you pipe in your master password from a keyring. An example with KWallet can be seen in issue #1321.

**Comment by eadmaster** [comment]
for most users would be easier having an option in the GUI, below the "Enter Password..." dialog

**Comment by aurelienpierre** [comment]
> You can create a start script for KeePassXC where you pipe in your master password from a keyring. An example with KWallet can be seen in issue https://github.com/keepassxreboot/keepassxc/issues/1321.

You mean to store your master password in plain text inside a script ? So what is the point of even encrypting the whole password database then ?

Nonsensical.

**Comment by secretmango** [comment]
@aurelienpierre no it is not stored in a text file... Maybe read the linked comment first.

example for Flatpak:
```
kwallet-query -r Keepass kdewallet | /usr/bin/flatpak run --branch=stable --arch=x86_64 --command=keepassxc --file-forwarding org.keepassxc.KeePassXC --pw-stdin /path/to/vault.kdbx
```

example for regular app:

```
kwallet-query -r Keepass kdewallet | keepassxc --pw-stdin /path/to/vault.kdbx
```

You just need to 
1. open Kwalletmanager
2. if there is none, create a folder called "Passwords"
3. Create an entry named "Keepass" (or anything, change the command then), store your password in that entry.

The security of Kwallet is questionable though.
