### ISSUE TITLE
[Feature Request] Hide in the dock under mac os

### ISSUE THREAD

**Issue by MZLAKg2aGGFs8yi** [keepassxreboot/keepassxc#2154]
Currently the program is still in the dock after it is hidden, which is a waste because it can be accessed  from the small icon in the system tray. An option to hide it from the Mac dock would be useful.

**Comment by droidmonkey** [comment]
This is too vague. Please add more information or it will be closed.

**Comment by phoerious** [comment]
I think the problem mentioned here is that there is no Mac-style "hidden window" mode where the program is running in the background without an icon in the dock. This is a duplicate of #1334
