### ISSUE TITLE
Reset search on folder change

### ISSUE THREAD

**Issue by mtelgkamp** [keepassxreboot/keepassxc#2156]
## Expected Behavior
If I perform a search and afterwards click on a folder in the folder pane the contents of this folder should be shown.

## Current Behavior
I perform a search and click on a folder, but the search results are still shown.

## Possible Solution
Reset the search on folder change.

## Context
If I click on a folder in the folder pane I expect to see the folder content in the listview even if I performed a search before

**Comment by droidmonkey** [comment]
This is already fixed in 2.4 develop branch with the search engagements PR.

**Comment by mtelgkamp** [comment]
Sorry for the duplicate of #1501 fixed by #1797. I thought I had done a search. Thank you for the fix! Looking forward to version 2.4!
