### ISSUE TITLE
Unreadable Cyrillic (Russian) installation dialogue

### ISSUE THREAD

**Issue by GarwelGarwel** [keepassxreboot/keepassxc#2157]
## Expected Behavior
When running Windows x64 EXE install, a series of dialogue windows in OS language should guide the user through the installation process.

## Current Behavior
If your OS language is set to Russian, all Cyrillic characters are displayed as gibberish (perhaps from extended Latin character set). It is clearly an encoding issue.

## Possible Solution
Check that correct and consistent encoding is used in the installation dialogue windows and localization files. Or simply use Unicode everywhere.

## Steps to Reproduce (for bugs)

1. Under Windows 10 with Russian as the system language, download and run KeePassXC-2.3.3-Win64.exe
2. All the texts will be shown in wrong encoding (not actual Cyrillic letters)

## Context

There are several different charsets that encode Cyrillic letters in 8 bits: Win-1251, KOI-8R etc. as well as UTF. When encoding used by different systems is inconsistent, it leads to incorrect characters being displayed. In the app itself, things are handled correctly; it is only an issue with the install.

## Debug Info

KeePassXC - Version 2.3.3
Revision: 0a155d8

Libraries:
- Qt 5.10.1
- libgcrypt 1.8.2

Operating system: Windows 10 (10.0)
CPU architecture: x86_64
Kernel: winnt 10.0.16299

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by droidmonkey** [comment]
Can you try using the MSI installer? We are ditching the exe installer in the future.

**Comment by GarwelGarwel** [comment]
Well, I just clicked through the dialogues (they are standard anyway), so I'm fine. I tried the MSI installer and it doesn't look localized at all.
