### ISSUE TITLE
Make it clear that an extension is required for browser integration

### ISSUE THREAD

**Issue by xPaw** [keepassxreboot/keepassxc#2158]
Right now it's not very obvious, and you have to hunt down the extension link (either google it or looking in the faq on the site).

The way the settings page looks (enable checkboxes per browser) somewhat implies that it should just work, and there's no hint that an extension in the browser needs to be installed. I think it would be beneficial to have direct links to the extensions on the settings page.

**Comment by varjolintu** [comment]
Maybe we still have time to do this for 2.3.4. Thanks for the hint.
