### ISSUE TITLE
Delays > 10000 are quietly discarded

### ISSUE THREAD

**Issue by stloewen** [keepassxreboot/keepassxc#216]
The "safety-checks" in https://github.com/keepassxreboot/keepassxc/blob/develop/src/autotype/AutoType.cpp#L384 and https://github.com/keepassxreboot/keepassxc/blob/develop/src/autotype/AutoType.cpp#L388 don't really make sense to me.

## Expected Behavior
If I enter a autotype sequence with '{delay 10001}' I expect it to wait for 10001ms.
If I enter '{left 101}', I expect it to type left 101 times.

Alternatively there should be some sort of warning that these values are invalid.

## Current Behavior
Delays greater than 10000 and repetitions greater than 100 are silently ignored.

## Possible Solution

Remove the checks or show a warning when these values are entered.
Alternatively go the same way as in https://github.com/keepassxreboot/keepassxc/blob/develop/src/autotype/AutoType.cpp#L370 and enforce bounds for the values. Although I think this isn't a good solution either as it quietly disobeys the users instructions.

**Comment by droidmonkey** [comment]
I would recommend fixing this with a dialog warning.

**Comment by hitesh1157** [comment]
Can you tell me how to remove compilation error:
./AutoType.h:21:10: fatal error: 'QtCore/QObject' file not found

**Comment by hitesh1157** [comment]
Can somebody explain me the errors?
[keepassxc.txt](https://github.com/keepassxreboot/keepassxc/files/763514/keepassxc.txt)

**Comment by phoerious** [comment]
That's a crash stack trace. But without debug symbols and more information about when it occurred, it's quite useless.
Also I don't know what it has to do with this issue.

**Comment by hitesh1157** [comment]
How do I compile AutoType.cpp
