### ISSUE TITLE
Special window flags missing after restore from system tray

### ISSUE THREAD

**Issue by groland11** [keepassxreboot/keepassxc#2160]
After KeePassXC has been minimized to system tray, special Qt window flags which have been set previously, are missing. Window flags may be "Move to all desktops" (window is shown on all desktops) or "Keep above others" (Qt::WindowStaysOnTopHint).

## Expected Behavior
Window flags should be the same before and after minimize to system tray.

## Current Behavior
Window flags are cleared after minimize to system tray.

## Possible Solution
Store and restore window flags if minimized to system tray.

## Steps to Reproduce (for bugs)
1. Enable settings "Hide window to system tray when minimized" or "Hide window to system tray instead of app exit"
2. Set window flags by clicking on system menu in window title bar and chose one or more of the following (menu names may be different on desktops other than KDE):
    - "Move To Desktop -> All Desktops"
    - "More Actions -> Keep Above Others"
    - ...
3. Hide window to system tray by minimizing main window or exit app.
4. Restore window from system tray 
5. Window flags from step 2 are missing now

## Context
I am using KDE on Ubuntu 18.04 .

## Debug Info
KeePassXC - Version 2.3.1
Revision: 2fcaeea

Libraries:
- Qt 5.9.5
- libgcrypt 1.8.1

Operating system: Ubuntu 18.04.1 LTS
CPU architecture: x86_64
Kernel: linux 4.15.0-29-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by droidmonkey** [comment]
Isn't this the responsibility of the window manager (ie kde)? Can we even access these flags from qt?

**Comment by phoerious** [comment]
These are just bit flags. I haven't looked at the code, but I would assume we somehow forgot to OR the default flags onto the changed flags.

**Comment by droidmonkey** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [#2160 - check window flags are preserved on minimize to tray](https://trello.com/c/gxoApRuA/8-2160-check-window-flags-are-preserved-on-minimize-to-tray)

**Comment by droidmonkey** [comment]
Is this still a problem?
