### ISSUE TITLE
The encryption-algorithm-selector should state the encryption-mode

### ISSUE THREAD

**Issue by Florianjw** [keepassxreboot/keepassxc#2161]
## Expected Behavior

The encryption-algorithm-selector should state the encryption-mode next to the specific algorithm.

## Current Behavior

It doesn't.

## Possible Solution

Add the name of the mode to the drop-down-menu. For example “AES-CBC 256-bit”

## Context

The mode that is used with a block-cipher is literally as, if not more, important than the particular choice of the block-cipher (I'd rather trust Speck-OCB than AES-ECB, and this is from someone who has less trust in the NSA than the Chinese government).

Offering Twofish and Chacha20 clearly shows that that selector is meant for end-users who have at least some amount of competence and many of these people will really care more for the mode than the cipher.

**Comment by droidmonkey** [comment]
@phoerious do we want to add this information or just put it in the documentation?

**Comment by phoerious** [comment]
Too technical. Put a note somewhere in the documentation's nerd section.

**Comment by phoerious** [comment]
I don't think we will ever implement this. Documentation may be amended at some point, but we don't need to keep this issue open for that.
