### ISSUE TITLE
[Feature Request] Alow randomly generated usernames just like passwords

### ISSUE THREAD

**Issue by stephenjmcmahon** [keepassxreboot/keepassxc#2163]
If you're already using a password generator why use the same login across everything. Right now I'm just copying the password to the username then generating a new password

Apologies if already requested or if already implemented and I'm missing it somewhere

**Comment by droidmonkey** [comment]
That's the obvious and best way to do it without overly complicating the ui

**Comment by hifi** [comment]
Most websites and services use email addresses as the username. It would also be a huge trigger for bots and other spammers if the username looks generated.

**Comment by droidmonkey** [comment]
Closing this as the password generator can be used to generate these usernames.
