### ISSUE TITLE
Enable unprotected output of `keepassxc-cli extract`

### ISSUE THREAD

**Issue by RealOrangeOne** [keepassxreboot/keepassxc#2164]
Don't output protected values protected when extracting from CLI.

## Expected Behavior
Show plaintext values for protected fields.

## Current Behavior
Protected fields are output in hashed format.

## Possible Solution
Adding `--unprotected` to `keepassxc-cli extract`

## Context
This would enable better programmatic use of the CLI, and enable complete backups in plaintext.

**Comment by SohamG** [comment]
I believe this has been fixed in PR #2351 and hence should be marked closed. 

I'm looking to start contributing to keepassxc and happened to pick this as my first issue, took me some time to realize its been fixed

CC - @phoerious
