### ISSUE TITLE
Clicking "Download favicon" in 2.3.3 snap segfaults, if networking is disabled

### ISSUE THREAD

**Issue by oittaa** [keepassxreboot/keepassxc#2167]
I tested the behavior of 2.3.3 snap, when networking is disabled. The application starts without `network` and `network-bind` interfaces, but when I click `Download favicon` button in an entry, a blank download window pops up.
![screenshot from 2018-07-29 06-29-39](https://user-images.githubusercontent.com/8972248/43378738-58b440ae-93d1-11e8-89d4-76ec1cd1f8e4.png)
After closing that window the application segfaults.

I first reported this in an another thread: https://github.com/keepassxreboot/keepassxc/issues/298#issuecomment-408649803

## Expected Behavior

The `Download favicon` should be disabled or it should tell the user that networking is required for it to work.

## Current Behavior

A blank download window pops up and the application segfaults.

## Possible Solution

I don't know exactly how snaps work, but can a snap application detect, if the network access has been disabled? Removing `Download favicon` button should be trivial, if that's possible.

Checking the audit log reveals that the application tries to open network connections immediately as soon as it starts. It should have the information that networking is disabled anyway by the point anyone tries to click `Download favicon`.

## Steps to Reproduce (for bugs)

1. Install keepassxc snap.
2. Disconnect `network` and `network-bind` interfaces from keepassxc.
3. Start KeePassXC, open a database and add an entry with an URL.
4. From `Icon` page click `Download favicon`.

## Debug Info

KeePassXC - Version 2.3.3
Revision: 0a155d8
Distribution: Snap

Libraries:
- Qt 5.7.1
- libgcrypt 1.7.6-beta

Operating system: Ubuntu Core 16
CPU architecture: x86_64
Kernel: linux 4.4.0-131-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by droidmonkey** [comment]
This has been corrected already in 2.3.4
