### ISSUE TITLE
Feature suggestion: Bookmarking databases

### ISSUE THREAD

**Issue by philippelatulippe** [keepassxreboot/keepassxc#2168]
Hi! I'm a longtime KeepassX user switching to KeepassXC. I use multiple keepass databases and the feature I miss the most is being able to bookmark databases for quick access. Here's how that looked like in KeepassX.

<img width="317" alt="application menu for managing bookmarks" src="https://user-images.githubusercontent.com/188527/43391830-060b0718-93f2-11e8-9e12-907f48175e0d.png">

<img width="363" alt="Quick switching between databases on the home or unlock view" src="https://user-images.githubusercontent.com/188527/43391860-1d9ab752-93f2-11e8-82e7-cf665ac35951.png">

![bookmark manager](https://user-images.githubusercontent.com/188527/43391873-29aa86d0-93f2-11e8-970b-5c47152bf43c.png)

A database can be bookmarked and given a name, which would appear on the welcome screen, allowing one-click access to it.

A submenu under the "Database" application menu would allow the user to _Add a bookmark_ (opens the file picker), _Bookmark this database_, and open a bookmark manager.

The bookmark manager would let users reorder, rename and delete bookmarks.

If the user adds a bookmark, the welcome screen would display a list of bookmarks. Clicking an item in that list would present the unlock view.

Some people need to use multiple database for various reasons, such as sharing databases between coworkers, keeping more sensitive passwords in a separate database outside of dropbox, having a database with a shorter password for use on mobile devices.

**Comment by TheZ3ro** [comment]
This can be useful in the welcome screen along with the "recent database" list

**Comment by paulmoons** [comment]
A workaround I use is to keep all my keyfiles locked but available as tabs.. but this would be better. Maybe an optional setting to allow tabs to be locked to the tab bar so you can't accidentally delete them?

**Comment by paulmoons** [comment]
> There is a recent database list, how is this an improvement over that?

The list is hidden in the menus and (the tabs) can be easily closed by accident.

**Comment by droidmonkey** [comment]
Looking at the original post's screenshot looks like the bookmarks menu item is exactly where our recent database list is....
