### ISSUE TITLE
Add support for libsecret (DBus)

### ISSUE THREAD

**Issue by jo-so** [keepassxreboot/keepassxc#2170]
[Libsecret](https://wiki.gnome.org/Projects/Libsecret) is an abstraction layer implemented by *Gnome Keyring* and *Kwallet*. If *KeePassXC* would implement the server side interface of *libsecret* it would become a replacement for *Keyring* and *Kwallet* and it would open up support for tools like *git* and *pinentry* (used by *GPG*), because they support *libsecret*. Also *Chromium* seems to support *libsecret*.

**Comment by droidmonkey** [comment]
This is a duplicate
