### ISSUE TITLE
KeePassXC not work with VeraCrypt

### ISSUE THREAD

**Issue by MESWEB** [keepassxreboot/keepassxc#2172]
## Expected Behavior
KeePassXC don't see mounted folders

## Current Behavior
Empty folder

## Possible Solution
??

## Steps to Reproduce (for bugs)
1. Install Veracrypt
2. Mount Virtual Drive
3. Try open ./media/veracrypt1
4. KeePass see only media folder nothing more inside

## Context
Maybe integrate KeePassXC with VeraCrypt ??

## Debug Info

KeePassXC - 2.3.3
Revision: 0a155d8

Libraries:
- LIBS

Operating system: UBUNTU 16.04
CPU architecture: INTEL I7-5500U
Kernel: 4.15.0-29-generic

Enabled extensions:
- EXTENSIONS

**Comment by phoerious** [comment]
Are you using the Snap release? I yes, then it's a Snap limitation.

**Comment by MESWEB** [comment]
@phoerious So what's this mean? Other apps can read this folder.

**Comment by phoerious** [comment]
It means if tiu are using our Snap release, then it's a limitation we can't change. Use the AppImage or PPA release instead.
