### ISSUE TITLE
Pasting from X11 clipboard (middle mouse button) doesn't work

### ISSUE THREAD

**Issue by soquel** [keepassxreboot/keepassxc#2175]
When having text in X11 clipboard (not the window-manager clipboard) on Linux, it's not posssible to paste it into KeePassXC.

## Expected Behavior

The content from X11 clipboard gets pasted.

## Current Behavior

Nothing happens.

## Steps to Reproduce (for bugs)

Select text in X11, click middle mouse button in any text input field and observe it's not pasted.

## Context

Copying from a web page by selecting text with mouse.

## Debug Info

KeePassXC - Version 2.3.3
Revision: 0a155d8

Libraries:
- Qt 5.11.1
- libgcrypt 1.8.3

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 4.17.11-arch1

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by hifi** [comment]
Works for me. Can you test any other Qt5 application on your system to see if it affects all of them?
