### ISSUE TITLE
Helpppp****How do i use Yubikey to secure KeepassXC i want to configure the static password but i do not want it displayed when i click on the (eye icon on the right of the password field). I want it to imput the code instead of the password. **Helppp!!

### ISSUE THREAD

**Issue by wayvekid** [keepassxreboot/keepassxc#2177]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Debug Info

KeePassXC - VERSION
Revision: REVISION

Libraries:
- LIBS

Operating system: OS
CPU architecture: ARCH
Kernel: KERNEL

Enabled extensions:
- EXTENSIONS

**Comment by wayvekid** [comment]
Please help I'm a first time user of Yubikey and KeepassXC

**Comment by phoerious** [comment]
You plug it in and enable the challenge response checkbox on the master key change screen. I'm not entirely sure what your problem is.

**Comment by wayvekid** [comment]
I configured the challenge response. and a static password (which lets me enable the password i want to use for KeepassXC. I questions is is there a way for the password i used for my static password to generate random keys each time i try to log into KeepassXC instead of my password. The reason is if someone gets hold of my key, inserts it and the password is inserted they can click on the eye and my password will be displayed. It's there a way to see the encrypted hash instead and and if the excryption can change from time to time.

**Comment by phoerious** [comment]
No. The password is a password, not a random code. Why would it be entered into the field when you're not at your PC?

**Comment by wayvekid** [comment]
Just trying to think of other secured ways to use the Yubikey with KeepassXC. Thanks for the insight.

**Comment by phoerious** [comment]
I think you misunderstood the concept of encryption here. There is no way anyone can see your password unless you just entered it yourself.

**Comment by wayvekid** [comment]
Okay. But when you insert the key and you open a text file, click, and hold the yubikey for a few seconds it prints out the stored password. Maybe i configured it wrongly.

**Comment by phoerious** [comment]
That is the OTP feature of the Yubikey and works as expected (its always a different password). It is NOT the response to the challenge that opens your database.

**Comment by wayvekid** [comment]
Ohhh okay. Thanks. I will set that up and try it out. Thanks.

**Comment by nagromc** [comment]
@phoerious That's one patience :clap:
