### ISSUE TITLE
[Feature] Clear Search bar after x seconds

### ISSUE THREAD

**Issue by Gittyperson** [keepassxreboot/keepassxc#2178]
Such an option, would improve the workflow. A common scenario is to do a search, copy the password for example and minimise KPXC. After a while (set by the user), it would be great to have the search bar cleared (and the search results obviously) and active again, instantly ready for the next search.

**Comment by droidmonkey** [comment]
Good idea, and I agree.

**Comment by droidmonkey** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [#2178 - clear search after X seconds](https://trello.com/c/xO7ZSqpI/10-2178-clear-search-after-x-seconds)
