### ISSUE TITLE
Feature Request: QuickUnlock

### ISSUE THREAD

**Issue by ei-ke** [keepassxreboot/keepassxc#2179]
First let me say thank you for writing KeePassXC!

I think a QuickUnlock feature like [Keepass2Android](https://github.com/PhilippC/keepass2android/blob/master/src/keepass2android/QuickUnlock.cs) has would be a neat addition. Especially when you lock the DB when locking your screen it would be awesome to just enter the _n_ last or first keys of your master password when you return to your PC and after _n_ wrong tries the DB is locked.

Cheers,

Eike

**Comment by droidmonkey** [comment]
This is a duplicate and a very desirable feature, thank you.
