### ISSUE TITLE
[Feature] Option to disable sending {enter} after "Perform Auto-type (ctrl+v)"

### ISSUE THREAD

**Issue by ghost** [keepassxreboot/keepassxc#2181]
Would be nice to have this option for people that don't use global auto-type by matching titles, for many reasons.

I want to disable sending the enter key after the username and password because not only many forms don't work with the enter key but also I fear I might send my login on IRC by mistake.

**Comment by droidmonkey** [comment]
Would just removing {ENTER} from the root group fix this for you? Or do you use a combo of the last window used and global shortcut?

**Comment by whytho2000** [comment]
My root group is empty except for folders. Since I have like billions of entries across several folders I often just alt+tab > control+f > type entry name > ctrl+v. I just want to be able not to submit the form automatically in the last step.

**Comment by droidmonkey** [comment]
The AutoType settings placed on the root folder apply to all children folders and entries.
