### ISSUE TITLE
No agent running, cannot add identity.

### ISSUE THREAD

**Issue by stratacast** [keepassxreboot/keepassxc#2182]
## Expected Behavior

SSH agent will open and I can use the key agent built into KeePassXC
## Current Behavior

I get the error mentioned above:
`No agent running, cannot add identity.`
## Possible Solution

Could it be that KeePassXC is looking in some hardcoded spot that is majorly only Win/Mac/Linux compatible?

## Steps to Reproduce (for bugs)

1. Enable ssh keyagent
2. Restart KeePassXC

## Context

Because the key agent is not found, KeePassXC cannot automatically enter my password for my SSH keys that I have allowed access to. I have tried the binary available via pkg as well as compiled it from ports. Running `eval $(ssh-agent -s)` does provide a pid and it is owned by me.
## Debug Info

KeePassXC - 2.3.3
Revision: 0a155d8

Libraries:
- Qt 5.10.1
- libgcrypt 1.8.3

Operating system: FreeBSD 11.2-RELEASE r336744
CPU architecture: x86_64

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent

**Comment by hifi** [comment]
You need to have `eval $(ssh-agent -s)` in your X startup before your WM/DE is started so that the environment variables (namely *SSH_AUTH_SOCK*) is available to KeePassXC when it is started.

You can check this in a terminal with `env | fgrep SSH_` to see if they are set and make sure the socket file *SSH_AUTH_SOCK* actually exists and is owned by the running ssh-agent process.

**Comment by stratacast** [comment]
I'm assuming `eval $(ssh-agent -s)` is happening at startup because I do have /SSH_AGENT_PID/ and /SSH_AUTH_SOCK/ as set environment variables at start and the socket file is pointing to the proper process and the ownership permissions are correct

**Comment by hifi** [comment]
If `ssh-add` works from a terminal and starting up KeePassXC from the same terminal still results in 'No agent running' there's definitely something wrong.

**Comment by ConorIA** [comment]
Not sure if this will be of any help. I had this problem when using [Keychain](https://www.funtoo.org/Keychain). 

My workaround was to add the following file as `~/bin/keepassxc` (make sure it is in your `PATH`)

```
#!/bin/bash
eval $(keychain --agents ssh --eval --quiet)
/usr/bin/keepassxc %1
```

**Comment by rocketraman** [comment]
I have this problem when I migrated to plasma-session-wayland.

**Comment by thePanz** [comment]
I had the same problem, but following the guide here: https://wiki.archlinux.org/index.php/SSH_keys#Start_ssh-agent_with_systemd_user seems that it is working (need to reboot to make sure it is keeping the changes after a reboot)
