### ISSUE TITLE
Want ability to search only on one column (Title, mainly)

### ISSUE THREAD

**Issue by BillDietrich** [keepassxreboot/keepassxc#2187]
Search searches all fields of all records (Title, Username, etc).  I want the option to search only on values in one column, mainly the Title column.

**Comment by droidmonkey** [comment]
This is already implemented in a PR.

**Comment by BillDietrich** [comment]
What is a PR ?

**Comment by droidmonkey** [comment]
See #1797

**Comment by BillDietrich** [comment]
I'm using KeePassXC 2.3.1 on Linux.  Doesn't seem to be in that release.  Should I be filing this request somewhere else ?  Thanks.

**Comment by droidmonkey** [comment]
It will be in the next major release (once merged) v2.4
