### ISSUE TITLE
Suggestion: easier 2FA setting workflow

### ISSUE THREAD

**Issue by apiraino** [keepassxreboot/keepassxc#2188]
Not sure this has been already been discussed earlier: currently setting up 2FA is quite a manual and error prone procedure. Personally my workflow is:
1) Go to to a password entry with a 2FA already setup
2) Manually copy all keys
3) Go to the password entry that needs 2FA I want to setup
4) Manually paste the keys and data

## Expected Behavior
The user experience to setup 2FA for an entry should be easier

## Current Behavior
Currently adding TOTP settings to enable is a quite manual and error prone procedure

## Possible Solution
Could the free form fields replaced by a couple of static forms where at least you don't have to input the keys' names (`KPH: {TOTP}`, `TOTP Seed`, `TOTP Settings`).

## Debug Info
KeePassXC - Version 2.3.3
Revision: 0a155d8

Libraries:
- Qt 5.9.5
- libgcrypt 1.8.1

Operating system: Ubuntu 18.04.1 LTS
CPU architecture: x86_64
Kernel: linux 4.15.0-29-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by varjolintu** [comment]
FYI, `KPH: {TOTP}` is no longer needed with 2.3.3 unless you are using it with String Fields.

**Comment by weslly** [comment]
You don't need all these steps to setup 2FA. Right-click the entry and select this item:

![image](https://user-images.githubusercontent.com/107672/43806560-d080ca12-9a7a-11e8-8bc3-1a88b2a98ba0.png)

**Comment by apiraino** [comment]
@weslly thanks for the suggestion.

I think the documentation on how to setup TOTP integration ([currently here](https://github.com/varjolintu/keepassxc-browser/wiki/Connecting-the-database-with-keepassxc-browser)) should be moved to a more prominent place, for example updating both the Wikis of `keepassxc-browser` *and* `keepassxc`.

@varjolintu Would you consider a PR updating these? Also adding [this](https://github.com/keepassxreboot/keepassxc/issues/2188#issuecomment-411227529) suggestion.

**Comment by varjolintu** [comment]
@apiraino This is already under work: https://github.com/keepassxreboot/keepassxreboot.github.io/pull/43. But I totally missed the wiki. Thanks.
