### ISSUE TITLE
Network drives (NFS drives) are not recognized. Can not open files from network Drive

### ISSUE THREAD

**Issue by EricLehnen** [keepassxreboot/keepassxc#2190]
Network drives (NFS drives) are not recognized. Can not open files from network Drive

## Steps to Reproduce (for bugs)

1.please try to access the media folder for NFS shares
2.Mounts can not be opened
3.
4.

## Debug Info
KeePassXC - Version 2.3.3
Revision: 0a155d8
Distribution: Snap

Libraries:
- Qt 5.7.1
- libgcrypt 1.7.6-beta

Operating system: Ubuntu Core 16 -> Ubuntu 18.04.1
CPU architecture: x86_64
Kernel: linux 4.15.0-20-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by therobyouknow** [comment]
Issue https://github.com/keepassxreboot/keepassxc/issues/2260 appears to relate to the same problem, and it affects non-snap installations as well.

**Comment by therobyouknow** [comment]
As a workaround I would suggest using and sticking with 2.3.1+dfsg.1-1 which seems to work, at least, in my scenario whereby I wish to access a NTFS mount, and may well work for you.

**Comment by droidmonkey** [comment]
Please read FAQ: https://keepassxc.org/docs/#faq-appsnap-homedir
