### ISSUE TITLE
KeepassXC font view compared to KeepassX

### ISSUE THREAD

**Issue by ipeacocks** [keepassxreboot/keepassxc#2192]
I know this is because of Qt5 but why KeepassXC font is not so good compared to old KeepassX? Is it something wrong with antialiasing/hinting/whatever? Could someone explain or link to right answer? Is there any workaround?

![Image of keypasses](https://i.imgur.com/Fk7roSi.png)

**Comment by hifi** [comment]
Are you using the Snap of Flatpak? They may have different font rendering settings than your base system.

**Comment by droidmonkey** [comment]
I don't see any discernible difference. Perhaps it "looks" better in KeePassX because of the gray background?

![font](https://user-images.githubusercontent.com/2809491/43875368-247823e8-9b5e-11e8-95c8-b6d7793bc2de.png)

**Comment by ipeacocks** [comment]
@hifi I am using ppa.

**Comment by ipeacocks** [comment]
With next font settings in `qt5ct`, fonts are more or less fine:

![Image of qt5ct](http://i.imgur.com/u0VSEFx.png)

**Comment by phoerious** [comment]
You might also want to check if you have configured the correct subpixel layout http://www.lagom.nl/lcd-test/subpixel.php
