### ISSUE TITLE
Clear Search bar after switching to a category in a left sidebar

### ISSUE THREAD

**Issue by shurph** [keepassxreboot/keepassxc#2199]
For now if the Search bar isn't empty the main panel shows for user the search result even if user already switched to some category/folder in the left sidebar.

## Possible Solution
I think the fastest and logically correct solution may be to clear search bar and switch to normal view mode.

As another solution: show only entries which are situated in selected folder and fit search criteria (a little bit harder to implement for developers and a little bit harder to understand this behavior for users)

## Steps to Reproduce (for bugs)
1. Ctr+F
2. type some word into the search bar
3. choose folder in the left sidebar
4. you still see search results, not content of selected folder

## Debug Info

KeePassXC - 2.3.3
Revision: 0a155d8

**Comment by highend** [comment]
+1

Maybe for those, who wouldn't like this feature, make it optional via the settings dialog...

**Comment by Lanthanus** [comment]
I would definitely enjoy this feature. Coming from KeePass2 this really confused me on the first use of KeePassXC. This behavior (along with other features) would be a great improvement on usability. 
I also second @highend that making it optional would be nice.

**Comment by droidmonkey** [comment]
This is implemented in #1797

**Comment by highend** [comment]
While this is really a duplicate, where has this been implemented?
v2.3.4 does NOT reset the search field and show ONLY the contents of a category when clicking on a folder / category on the left side (and the search field still has content in it)

**Comment by droidmonkey** [comment]
I literally wrote above where it is implemented... implemented does not equal deployed.
