### ISSUE TITLE
Database Merge

### ISSUE THREAD

**Issue by TheZ3ro** [keepassxreboot/keepassxc#22]
Should be nice to be able to automatically merge 2 or more password databases.

Use case: You have a KeePassX database on your PC and a database on your Phone, you "sync" them with Syncthing, Dropbox, whatever and you will lose changes on PC or Phone version so you need to keep both databases aside. With the Merge feature, you open both database on KeePassX and merge them so now you have all password in 1 file.

**Comment by droidmonkey** [comment]
So the use case is you open two databases in the app then hit the "sync" button which will compare timestamps across entries and reconcile them into one database that you can then save.

Did I capture that correctly?

**Comment by TheZ3ro** [comment]
Yes, or maybe just opening 1 database, hit a "Merge" button and select another database file to compare to

**Comment by ImNtReal** [comment]
KeePass calls this Synchronize. For instance, I have one .kdbx file that I synchronize to multiple machines using NextCloud. I'll have that file open on each machine, and when a change is made, the new file is automatically copied across all the machines. In KeePassX, I have to close the database, and reopen it to see the change. In KeePass, I go to File -> Synchronize -> Synchronize with File, and select the file. It will then merge changes.

It would actually be even cooler if you set up a watch on the file, and merged it any time there was a change that KeePassX didn't make to the file. Truth be told, in my setup, since I have KeePassX set to auto-save on change, I wouldn't even need merging, I would just need the database be automatically reloaded when it changes outside the program.

**Comment by TheZ3ro** [comment]
So: 
 - Option to Merge current Database with another file
 - Option to Sync (on changes) from another file
 - Automatically Sync (on changes) from the opened database file

**Comment by ImNtReal** [comment]
I think it's really just:
- Option to Merge current database with a file (whether it's the current file or a different one)
- Automatically merge the current database when it changes

**Comment by TheZ3ro** [comment]
By Merge I mean, the user request to merge 2 file by clicking a button by demand
By Sync I mean, if user enable this option KeePassX will check for change and do the Merge

I think that 1st and 2nd (from my comment) are different behavior
The 3rd is like the 2nd but done automatically by KeePassX without user choice on the currently opened database file

It sounds good?

**Comment by TheZ3ro** [comment]
I was developing the Automatic merge of the current database file and I've learned that KeePassX put a lock on the file if it's open. It's a good idea to discard the lock (maybe only when the database is not used) and enable the auto update?

**Comment by droidmonkey** [comment]
Database merge was proposed by @monomon in [KeePassX PR #177](https://github.com/keepassx/keepassx/pull/177)

I intend to merge this code into a feature branch for further testing.

**Comment by TheZ3ro** [comment]
Current status
 - :white_check_mark:   Option to Merge current Database with another file
 -  Option to Sync (on changes) from another file
 -  :white_check_mark:  [https://github.com/keepassxreboot/keepassx/pull/33] Automatically Sync (on changes) from the opened database file

**Comment by monomon** [comment]
I would love to see this change in the reboot. It is kind of unfortunate that the original project is not active.
Indeed the change so far only merges another file into the currently open one. Watching files and syncing from a remote provider would be interesting, though.
tbh one of the reasons I use keepassx is that I do not want to store my database "in the cloud". But syncing securely p2p would be fine.

**Comment by TheZ3ro** [comment]
Almost any Cloud (Dropbox, GDrive) or Sync (Syncthing) provide a program that sync a folder on your pc with the cloud/remote version. You don't need to set the watch on the remote provider. Just watch the file that the program will sync.

**Comment by monomon** [comment]
Yeah sorry, wasn't clear enough but wasn't conflating the two :)
I meant them as separate use cases.
Watching a file synced from the cloud would be tricky, you could easily get unresolvable conflicts (assuming concurrent work on the same file). Would you do a deep merge of some sort then?

**Comment by TheZ3ro** [comment]
This is closed but there is still an Issue/Feature request to complete:

 * Option to Sync (on changes) from another file

**Comment by droidmonkey** [comment]
I think we incorrectly grouped three features into one issue. Can you open up a new issue to capture that feature? 

I'll be opening a PR for the autoreload feature this evening.

**Comment by TheZ3ro** [comment]
Done https://github.com/keepassxreboot/keepassxc/issues/90\

OT: Can you review the "Mac-Windows Autotype PullRequest" when you have spare time?
