### ISSUE TITLE
Expiration date of entry should count in days for months

### ISSUE THREAD

**Issue by L0g4n** [keepassxreboot/keepassxc#2201]
## Expected Behavior
When setting an expiration date for an entry (e.g. 3 months) it should count in days (1 month = 30 days) to set the expiration date.
Why is this a problem ? I created a GPG key with an expiration date in 3 months, I generated a keyphrase for it in keepassxc and set the expiration date with the template for 3 months. Now because GnuPG counts 3 months as 90 days I get an anomaly between the expiration date in keepassxc and the actual date set as expiration date in the gpg key, i.e. "more days in keepassxc".

## Current Behavior
Currently it just adds the number of months to the month position.

**Comment by droidmonkey** [comment]
I do not agree with gpg's use of date terms here, if true. 3 months != 90 days in any modern calendar, except for Jan + Feb + Mar in a non leap year.

**Comment by L0g4n** [comment]
I agree that is not a 100% correct way to do this, but the current implementation is not correct either. The correct way to do this is the to get the days of the month you are starting the interval in and add dem to the date and repeat this step you have "added enough months" to the date.

**Comment by droidmonkey** [comment]
Totally agree, I looked up the code and it is exactly the wrong way to add date/time together.

**Comment by L0g4n** [comment]
Can you give me a link to the specific part of the code ? Tried to look it up myself but I am not familar with the codebase.

**Comment by droidmonkey** [comment]
https://github.com/keepassxreboot/keepassxc/blob/develop/src/core/TimeDelta.cpp#L24

**Comment by droidmonkey** [comment]
Yah it is, but its unnecessary

**Comment by L0g4n** [comment]
Do you suggest just replacing function calls of this class (when it is even used) to direct QDateTime calls ?

**Comment by TheZ3ro** [comment]
The TimeDelta class also has 0 tests. It seems an utility class and it seems to perform date addition fine after a brief review but I will not bet on it.
