### ISSUE TITLE
Read only database when more than 1 User is logged in to the same database

### ISSUE THREAD

**Issue by SheelaCookie** [keepassxreboot/keepassxc#2205]
When more than 1 User is logged in to the same database ( Example person A & B ) person A cant create entries or move them to a diffrent folder, if user B is logged in at the same Time. This Bug only seems to happen with user A ( de-installing KeePassXC and installing it anew doesn´t help.) when user A, B, C and D are logged in, everyone except user A can change entries or create a new entry. If user A tries to create a new entry, she sees it for a second then it dissapears again into limbo. if user A tries to move a entry to a new folder, the entry will stay in the new folder for a few seconds, then it dissapears and pops up in the original folder.

## Expected Behavior
Multiple users should be able to use a database at the same time and create/ change entries.

## Current Behavior
User A and B are logged in to the same database, user B has no issues creating a new entry or changing a existing entry, while User A cant create a new entry or change an existing entry.

## Possible Solution
I have no idea, sorry.

## Steps to Reproduce (for bugs)
This is the first time this has happened in a few weeks, until now everything seemed to work just fine.
1. User A and B open the database ( who does it first does not matter )
2. User B can create a entry which user A sees in her database after a few seconds
3. User A tries to move the new entry to a new folder / create a new entry ->
4. it doesnt work. the moved entry hops back to the original folder / the new entry dissapears to never be seen again anywhere.

## Context
We are trying to use KeePassXC as a team to manage passwords, so it  would be great if  multiple users can use the same database at the same time.

## Debug Info
there were no error messages.
KeePassXC - 2.3.3
Revision: REVISION

Libraries:
- LIBS

Operating system: Windows 10
CPU architecture: ARCH
Kernel: KERNEL

Enabled extensions:
Browser extension

**Comment by droidmonkey** [comment]
How are you storing/sharing the shared database file?

Just for clarity, KeePassXC does not know if someone else is using the database file. In fact we don't touch the file itself except when opening and saving the database. So sharing a database is really at your own risk and ideally in a largely read only situation.

It could be that user B denied the merge operation that occurs when a change is detected in the underlying database file. If they did that, then the file may revert back to the original state which is what user a sees.
