### ISSUE TITLE
Feature Request: Master Password Generation

### ISSUE THREAD

**Issue by apollo22** [keepassxreboot/keepassxc#2206]
I think it would be nice to allow generating passwords from 2 input keys. This would allow regenerating some passwords even if you don't have your database file while having them saved next to your random generated passwords. 

Use case: generating a password from a url + a master password (different from database master password)

Exemple of this kind of password generation:
https://chriszarate.github.io/supergenpass/
https://masterpassword.app/how/

**Comment by droidmonkey** [comment]
I'm going to go with a hard no for this one. We discussed this before in an old issue. The methods used here are not secure and easily defeated by an attacker. Plus, as you linked, there are already solutions out there that can meet your needs.

**Comment by TheZ3ro** [comment]
https://tonyarcieri.com/4-fatal-flaws-in-deterministic-password-managers
https://www.ghacks.net/2016/11/07/deterministic-password-manager-issues/

discussed in #955

**Comment by apollo22** [comment]
Thanks for the links. I still believe it could be interesting but I respect your decision.
