### ISSUE TITLE
Chrome Extension: "target.className.includes is not a function" on highcharts

### ISSUE THREAD

**Issue by frank-eisen** [keepassxreboot/keepassxc#2207]
Hello,

the chrome extension causes a javascript error (see below) every mousemove event when hovering a highchart.js chart with annotations.
First I thought it is some kind of issue with svg, but other websites with included svg work fine.
It seems to be affected by highcharts' annotations, because the demo with only labels works fine [(https://www.highcharts.com/demo/line-labels)](https://www.highcharts.com/demo/line-labels), but with annotations not: [https://www.highcharts.com/demo/annotations](https://www.highcharts.com/demo/annotations)

Javascript error:
```
keepassxc-browser.js:1269
Uncaught TypeError: target.className.includes is not a function
    at Object.cipObserverHelper.ignoredElement (keepassxc-browser.js:1269)
    at Object.cipObserverHelper.handleObserverRemove (keepassxc-browser.js:1302)
    at MutationObserver.<anonymous> (keepassxc-browser.js:1347)

cipObserverHelper.ignoredElement @ keepassxc-browser.js:1269
cipObserverHelper.handleObserverRemove @ keepassxc-browser.js:1302
(anonymous) @ keepassxc-browser.js:1347
childList (async)
buildText @ highcharts.js:68
textSetter @ highcharts.js:59
p.textSetter @ highcharts.js:86
(anonymous) @ highcharts.js:43
a.objectEach @ highcharts.js:28
attr @ highcharts.js:42
refresh @ highcharts.js:188
runPointActions @ highcharts.js:201
onContainerMouseMove @ highcharts.js:209
c.onmousemove @ highcharts.js:210
```

## Expected Behavior
no javascript should occur when hovering highcharts

## Current Behavior
every mousemove event when hovering a highchart.js chart with annotations a javascript error occurs (see above).

## Possible Solution
Possibly it will help checking if `className.includes` exists, so change

`if (target.className && (target.className.includes('kpxc') || target.className.includes('ui-helper'))) {`

to this:

`if (target.className && typeof target.className.includes !== 'undefined' &&(target.className.includes('kpxc') || target.className.includes('ui-helper'))) {`

## Steps to Reproduce (for bugs)
1. open [https://www.highcharts.com/demo/annotations](https://www.highcharts.com/demo/annotations)
2. open developer tools
3. hover chart with your mouse

## Debug Info
KeePassXC - Version 2.3.3
Revision: 0a155d8

Bibliotheken:
- Qt 5.10.1
- libgcrypt 1.8.2

Betriebssystem: Windows 10 (10.0)
CPU-Architektur: x86_64
Kernel: winnt 10.0.17134

Aktivierte Erweiterungen:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by varjolintu** [comment]
I changed the existing PR that modifies this function to include the check you suggested.

**Comment by frank-eisen** [comment]
Thank you!

**Comment by jagtarsinghwork** [comment]
After making Build (npm run buid  && n serve -s build) My issue in not in build only on development time so you can manage accordingly,  this is temporary solution
