### ISSUE TITLE
Menus, icons and shortcuts doesn't work on ubuntu mate.

### ISSUE THREAD

**Issue by trialism** [keepassxreboot/keepassxc#2209]
Hi,

 The things I mentioned don't work on ubuntu mate. For example if I click on a menu then it won't open and instead it's just highlighted.

**Comment by trialism** [comment]
18.04

**Comment by trialism** [comment]
This affects keepassx too.

**Comment by droidmonkey** [comment]
I cannot replicate this issue. You may have a corrupt Qt installation.
