### ISSUE TITLE
Wrong TOTP when multiple auto-type

### ISSUE THREAD

**Issue by rderensy** [keepassxreboot/keepassxc#2210]
When you run the auto-type for a website and you wrote "{TOTP}" in the custom auto-type sequence: the second time you call that auto-type for the same website, the TOTP isn't updated.

Example:
I log into Twitter, I call auto-type, it writes my username and password, press enter and then write TOTP and press enter.
The problem is: if I instant logout of Twitter (or I cancel the auto-type my defocusing the window) and I want to recall auto-type for logging back, it keeps writing the first TOTP even if it has changed.

Concretely:
1. go to twitter.com
2. call auto-type
3. write username
4. write password
5. enter
6. TOTP (say it's 123456)
7. enter
8. logout
9. call auto-type
10. write username
11. write password
12. enter
13. TOTP

and **here**, the TOTP isn't good. It wrote 123456 (as the first one) whereas it has changed and it's now 654321.

## Debug Info

    KeePassXC - Version 2.3.3
    Revision: 0a155d8
    
    Libraries:
    - Qt 5.10.1
    - libgcrypt 1.8.2
    
    Operating system: Windows 10 (10.0)
    CPU architecture: x86_64
    Kernel: winnt 10.0.14393
    
    Enabled extensions:
    - Auto-Type
    - Browser Integration
    - Legacy Browser Integration (KeePassHTTP)
    - SSH Agent
    - YubiKey

**Comment by TheZ3ro** [comment]
Oh wow, nice find
