### ISSUE TITLE
KeepassXC systemtray function breaks systemtray

### ISSUE THREAD

**Issue by omega3** [keepassxreboot/keepassxc#2213]
I use Manjaro Linux Plasma KDE 5.13.4 QT 5.11.1

When I have "Show a system tray" set and I click on this icon KeepassXC hides in tray. This is expected behavior. Then I use systemtray option → elements → and choose always visible for KeepassXC icon. Then systemtray starts to misbihave. See bug screenshot below. When I hide KeepassXC to tray I can't use clipper or network manager because when I click on those systemtray icons the whole systemtray is activated. And all elements disappear from systemtray option. 

But then 
https://i.imgur.com/n6D3lv3.png
Bug:
https://i.imgur.com/DDf9kjF.png
https://i.imgur.com/JlKs6rq.png

## Expected Behavior
Regardless of whether KeepassXC is in systemtray or not I should be able to use other systemtray icons.
I don't know if this is KeepassXC bug or systemtray bug but I tested it with another program - Cherrytree and it works ok. It last untill next system reboot or I need to remove systemtray and add it again.

KeePassXC - Version 2.3.3
Revision: 0a155d8

Libraries:
- Qt 5.11.1
- libgcrypt 1.8.3

Operating system: Manjaro Linux
CPU architecture: x86_64
Kernel: linux 4.14.65-1-MANJARO

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by droidmonkey** [comment]
I doubt this bug is on us, we just call standard Qt functions for the system tray. This could be a bug in Qt 5.11 or the systray. My vote is on the systray.
