### ISSUE TITLE
Add {COPY:field} to Auto-Type tokens to copy named field to clipboard

### ISSUE THREAD

**Issue by lordloh** [keepassxreboot/keepassxc#2215]
## Expected Behavior
KeepassXC should (optionally) not minimize after auto type (discussed at https://sourceforge.net/p/keepass/discussion/329221/thread/fd0e9e5a/) The people at that time (2013) thought that there was no further need for Keepass after auto-type.

## Current Behavior
KeepassXC minimizes after autotype

## Possible Solution
Have a setting under Tools > settings > General > Basic

## Context
I often have to copy the TOPT after auto type. I would also love to be able to double click and copy TOTP like the user name and passwords, but can live with the rightclick > Time-based one time passwords > copy OTP or Show OTP, but the window minimizing all the time does gets irritating. Different users have different work flows and at times, I may have to have 3 to 4 logins within 10min. So, an option to prevent or enable minimize after auto-type may be useful for some users (like me).

## Debug Info
KeePassXC - Version 2.3.3
Revision: 0a155d8

Libraries:
- Qt 5.10.1
- libgcrypt 1.8.2

Operating system: Windows 10 (10.0)
CPU architecture: x86_64
Kernel: winnt 10.0.17134

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by TheZ3ro** [comment]
The fact is that you need to minimize KeePassXC in order to send keystrokes to the target application, after that you need to re-invoke the KeePassXC window.

This has some issue if you disable the auto-enter autotype shortcut (sending automatically `{ENTER}` after every autotype sequence.

The best thing is adding a shortcut to minimize/maximize the KeePassXC window.

Expected Behaviour:

1) Press Autotype shortcut
1) Autotype is performed
    1) Press enter if needed
1) Press Minimize/Maximize shortcut
1) Copy and paste TOTP

**Comment by lordloh** [comment]
Okay. So it is a limitation.

Are there reasons that makes a double click copy of OTP a bad idea? How about an option to put the TOTP (it it exists) into the clipboard on clicking auto-type?

**Comment by TheZ3ro** [comment]
I actually like your proposal and we should make an autotype sequence keyword for it.

Something like `{USERNAME}{TAB}{PASSWORD}{ENTER}{TO-CLIP:TOTP}`

`TO-CLIP` is the main token and after the `:` you can place any entry field (also custom field with typical syntax `S:field`)

**Comment by droidmonkey** [comment]
How about {COPY:<token>}

**Comment by TheZ3ro** [comment]
I like the `COPY` token

**Comment by lordloh** [comment]
Looks like this has turned into a new "Enhancement" request. Should a new issue be created?

**Comment by lordloh** [comment]
@TheZ3ro @droidmonkey  - This is too far ahead but, should you implement `{COPY:}`, do you propose to clear the clipboard as a part of `{COPY:}` or something like `{COPY:}{DELAY 30000}{CLEAR-CLIP}`?

**Comment by droidmonkey** [comment]
We would use the configured clipboard clearing time. It would be incumbent on the user to configure their autotype correctly to incorporate delays and such. We can keep this same issue to track the enhancement, I changed the title.

**Comment by Saroumane** [comment]
The  {COPY:field} is such a great idea !
Sometimes you found a website where the password field is unreachable by "TAB", so filling the clipboard with the password is a good way to mitigate the problem. (You still have to click on the field with the mouse and paste it, of course)

**Comment by BillDietrich** [comment]
> {USERNAME}{TAB}{PASSWORD}{ENTER}{TO-CLIP:TOTP}

That's the functionality I want (I don't care if it's TO-CLIP or COPY or whatever).

**Comment by droidmonkey** [comment]
We do support the {TOTP} placeholder

**Comment by BillDietrich** [comment]
Yes, but I want it into the clipboard because often the TOTP has to be put into next web page, some variable number of seconds later.

**Comment by droidmonkey** [comment]
You can also add {DELAY 2000}

**Comment by droidmonkey** [comment]
I decided not to implement this feature. The revamped Auto-Type select dialog now includes the ability Auto-Type or copy to clipboard the username, password, or totp of an entry. We do not encourage the use of the clipboard and embedding that into Auto-Type defeats the purpose of Auto-Type.

**Comment by jjt-2020** [comment]
Can be done by using the KeePassOTP plugin and this keystroke sequence: {CLIPBOARD-SET:/{KPOTP}/}
Shows red (invalid?), but works nonetheless.

**Comment by BillDietrich** [comment]
There is no way to use that plugin in KeePassXC, unless I am greatly mistaken.

If I try to use that keystroke sequence, I get "syntax error", and there is no way to get around that error and save the entry anyway.

I'm using KeePassXC 2.6.4

**Comment by BillDietrich** [comment]
> The revamped Auto-Type select dialog now includes the ability Auto-Type or copy to clipboard the username, password, or totp of an entry.

What is the "Auto-Type select dialog" ?  I don't see that in my copy of KeePassXC.  How do I copy TOTP to clipboard ?

**Comment by droidmonkey** [comment]
This is a future feature

**Comment by carstenjaksch** [comment]
@droidmonkey Some sites do not recognize TOTP typed by KeePassXC.

For example, the code gets inserted only in the first box at hosting.de login screen. Normally, when typing the TOTP, some JS automatically selects the next input box after each key press. That does not happen with auto-type.

<img width="498" alt="Bildschirmfoto 2022-08-19 um 12 39 32" src="https://user-images.githubusercontent.com/82714642/185601453-78dea1be-fde0-4ca0-82e3-c6ab33df0e34.png">

I beg you, please reconsider implementing a copy function.

**Comment by droidmonkey** [comment]
It is already implemented.... you have several options:
1. Copy TOTP from the Auto-Type selection dialog (can also press Ctrl + 3)
2. Add a {DELAY=500} to your typing sequence to slow the typing between characters 
3. Don't use Auto-Type at all and just copy the totp code from the entry view 
4. Use the browser extension.

**Comment by carstenjaksch** [comment]
Thank you for the quick response.

1. Copying from the selection dialog could be a workaround, but that defeats the purpose of auto-type: Automation.
2. {DELAY=500} does not work in that case, unfortunately.
3. Again: That would not be an automated solution, as I have to go to the KeePassXC window, maybe search for the entry, select it, copy the TOTP, go back to the browser and insert the code.
4. The browser extension works so far, but I see two disadvantages here: It is not available for Safari and I need to click three to five times (open KeePassXC tooltip, maybe select login, click on submit, click on the green TOTP button, maybe submit the code too). With auto-type, there were only the shortcut, maybe enter for the dialog (if displayed) and inserting the code.

A copy function for auto-type would be so much more convenient, in my opinion.

**Comment by droidmonkey** [comment]
> that defeats the purpose of auto-type: Automation

That is not the purpose of Auto-Type. It's purpose is to avoid using the clipboard. As a side benefit you can automate some actions through the keyboard if you wish to do so.

You can use a higher value than 500 in the delay, that was just an example.

**Comment by carstenjaksch** [comment]
A higher value makes no difference. I can watch how the TOTP numbers get deleted after being inserted one by one.

A workaround could be to use TAB between the TOTP numbers. Is that possible somehow?

**Comment by droidmonkey** [comment]
That is not possible. Since this website appears to be broken there is nothing we can do to fix this from an Auto-Type keyboard perspective.

**Comment by carstenjaksch** [comment]
You could add an option to automatically copy the TOTP, as most password managers offer. 🙂
