### ISSUE TITLE
View all entries? (Groups and ungrouped)

### ISSUE THREAD

**Issue by Gittyperson** [keepassxreboot/keepassxc#2217]
Hello everyone, I've created several groups to the database which in turn contain sub-groups. 4 "levels" in total: Root/Group1/G2/G3. I tried viewing all database entries at once but it seems it's not possible? This would help easily locating recently modified ones for example. I pressed space once as a test on the search bar and this seems to display everything. I counted all entries and the number verified although not sure if it's a reliable method to use.

It seems pressing on a group does not show entries contained in its sub-group(s). That's probably by design and they are considered independent "folders". I guess that's why pressing on Root shows nothing for me, because I have only added groups to the Root, and not individual entries.

It would be helpful if pressing on each group also displayed all entries of its sub-groups, and also pressing on Root to display everything in the database (all entries, all groups, all ungrouped).

Hope I'm not too confused here.   :blush:

**Comment by droidmonkey** [comment]
We treat folders just like a file system. Showing everything under them kind of defeats their purpose.

**Comment by TheZ3ro** [comment]
But searching for something like `*` or for example `title:*` should display the full database, what do you think?

**Comment by droidmonkey** [comment]
My PR for advanced search already does thag

**Comment by morgor** [comment]
The global view is useful.

**Comment by droidmonkey** [comment]
This will be available in the 2.4.0 release by simply searching for "*"
