### ISSUE TITLE
"man keepassxc-cli" and "keepassxc-cli -h" not in sync

### ISSUE THREAD

**Issue by liar666** [keepassxreboot/keepassxc#2219]
Just a quick note: documentation from man keepassxc-cli and keepassxc-cli -h are not in sync:

```
$  keepassxc-cli -h
add            Add a new entry to a database.
clip           Copy an entry's password to the clipboard.
diceware       Generate a new random diceware passphrase.
edit           Edit an entry.
estimate       Estimate the entropy of a password.
extract        Extract and print the content of a database.
generate       Generate a new random password.
locate         Find entries quickly.
ls             List database entries.
merge          Merge two databases.
rm             Remove an entry from the database.
show           Show an entry's information.
```

```
$ man keepassxc-cli
       clip [options] <database> <entry>
       ...
       extract <database>
       ...
       entropy-meter [-a pwd1 pwd2 ...]
       ...
       list [options] <database> [group]
       ...
       merge [options] <database1> <database2>
       ...
       show <database> <entry>

```
As can be seen manpage lacks many commands (add, rm...) and some commands have different names (and usage?) but seem to relate to the same functionality (estimate vs. entropy-meter, etc).
I don't know which one is right, but it would be great to resync the two documentations.

Maybe it is even possible to make a simple script that generates the man page from the commandline options' help texts, so that it does not happen again?

FYI:
```
$  keepassxc-cli -v
2.3.3
```

```
$ cat /etc/lsb-release
...
DISTRIB_DESCRIPTION="Linux Mint 18.1 Serena"
```

**Comment by louib** [comment]
@liar666 I don't think this has to do with a drift in the source code itself. As you can see, the doc from the manpage and the command line help [were both updated in the same PR](https://github.com/keepassxreboot/keepassxc/pull/1250/files). I think this has to do with the manpage not being installed after updating the app. How did you install the app?

**Comment by liar666** [comment]
Sorry for the late reply. I installed the app using apt-get using Linux Mint's default repositories...

**Comment by louib** [comment]
Can you run `locate keepassxc-cli.1`? Maybe you have multiple versions of the man page installed and the older one is prioritized.

**Comment by CassiusVonthill** [comment]
OS: Arch Linux
Keepassxc version: 2.3.4

Another small tidbit

Running `keepassxc-cli --help` outputs: `Usage: keepassxc-cli [options] command`
Whereas my actual usage shows me to use `keepassxc-cli command [options]`

Question: Are these docs official? They helped me when my commands weren't working earlier: https://www.mankier.com/1/keepassxc-cli

**Comment by droidmonkey** [comment]
No those docs are not hosted by us.

**Comment by SohamG** [comment]
Fixed the files in the pull request above ^^

Issue should be resolved the next time the PPA packages are built/updated
