### ISSUE TITLE
Release artifacts for 2.3.4?

### ISSUE THREAD

**Issue by ArchangeGabriel** [keepassxreboot/keepassxc#2226]
I only see the default assets under https://github.com/keepassxreboot/keepassxc/releases/tag/2.3.4. Are the other ones being produced or is there some issue?

**Comment by phoerious** [comment]
We have only tagged the release so far. The binaries will be created soonish.

**Comment by ArchangeGabriel** [comment]
OK, thanks. I’m only interested in the (signed) source tarball actually (I’m packaging for ArchLinux).

**Comment by ThePythonicCow** [comment]
@ArchangeGabriel  -- as I noted in the the following post, I think the tarballs (at least the one I downloaded from here, a few hours ago), are a few days behind what you get when you check out 2.3.4 from the git repository.

See further my post https://github.com/keepassxreboot/keepassxc/issues/1331#issuecomment-415171183

**Comment by droidmonkey** [comment]
I don't know what tarball you downloaded or where you got it from... if you download it from the release page you will get what is associated with the tag.

https://github.com/keepassxreboot/keepassxc/archive/2.3.4.tar.gz

**Comment by phoerious** [comment]
I guess he's referring to the signed tarball not being available yet. Only the standard Github archives are there.

**Comment by ArchangeGabriel** [comment]
@phoerious is right regarding me, but I think @droidmonkey was answering @ThePythonicCow. As I said in #1331, the problem is that the 2.3.4 release notes include changes that are only in the develop branch, while the tag is (correctly) on master.

**Comment by droidmonkey** [comment]
I see what happened. The 12-hour timeout was tagged with 2.3.4 milestone but merged into develop. Phoerious commented that we should also include it into 2.3.4 but that was never done. I'll remove it from the GitHub release notes.

**Comment by phoerious** [comment]
All 2.3.4 artifacts have been released.
