### ISSUE TITLE
no "Browser Integration" Icon in Settings - Ubuntu 14.04

### ISSUE THREAD

**Issue by GeoTimber** [keepassxreboot/keepassxc#2227]
I expected to see a "Browser Integration" icon under settings.

I only see "Legacy Browser Integration"

Ther fore can not connect with the "KeepassXc Browser Plugin" from Chrome.

Ubuntu 14.04
version 2.3.3 from PPA ppa:phoerious/keepassxc

**Comment by phoerious** [comment]
Ubuntu 14.04 has only Qt 5.2, but 5.3 is needed for KeePassXC-Browser. See https://keepassxc.org/docs/#faq-browser-trusty
