### ISSUE TITLE
Support for import encrypted andOTP backups

### ISSUE THREAD

**Issue by rodrigoswz** [keepassxreboot/keepassxc#2228]
[andOTP](https://github.com/andOTP/andOTP) is an amazing open-source 2FA app for Android that allows you to backup your data to an encrypted file. It would be great to be able to import this file to be accessed in KeePassXC!

Currently there is [OTPClient](https://github.com/paolostivanin/OTPClient) that allows accessing this file on a computer running linux, however on windows there is no other client. KeePassXC could be the best solution, besides linux users have a program two in one.

**Comment by droidmonkey** [comment]
Cool good idea

**Comment by f0o** [comment]
Any news regarding this? It would be awesome to be able to import andotp's .json.aes into keepassxc :)

**Comment by droidmonkey** [comment]
No and there aren't any plans to do this either.

**Comment by MembershipExcel** [comment]
So there no other way to easily get OTP in KeepassXC by import file ? 
We can only create them manually by importing the key ?

**Comment by droidmonkey** [comment]
You can import them via csv, but that's it besides copy/paste into the TOTP setup dialog. In csv you need to otpauth:// url string.

**Comment by MembershipExcel** [comment]
Could you be more specific ? 
Reading the QR code I get something like : 
otpauth://totp/NAMEPROVIDER?secret=xxxxxxxxxxxxxxxxxxxxxxxxxx&issuer=NAMEPROVIDER
Doing import data base and colonne1 in the TOTP colum I get the right code but no name or logo
I could probably do some rearrangement while making the CSV

Is there a way I could automatically add the right Icon ? URL Icon ?

**Comment by droidmonkey** [comment]
You need to fill out the rest of the fields on the csv

**Comment by spotlesscoder** [comment]
> No and there aren't any plans to do this either.

Does that mean there are no plans to support this at all or would you be accepting a PR in case someone else implements this?

**Comment by droidmonkey** [comment]
Where useful for some, this just isn't important enough to be a supported feature. There are external tools that you can use to assist with importing these things. A PR would likely be overly complicated given this is not a standard pathway for ANY import. andOTP is also unmaintained at this point.
