### ISSUE TITLE
Auto-type not working under Linux

### ISSUE THREAD

**Issue by Ghosthree3** [keepassxreboot/keepassxc#223]
## Expected Behavior
Pressing the configured auto-type hotkey sequence should trigger auto-type in matching windows.

## Current Behavior
I set the global auto-type hotkey in the preferences, but when I press it, nothing happens.

## Steps to Reproduce (for bugs)
1. Set the shortcut
2. Use it

Have tested with hotkey Ctrl+Alt+Shift+A and Ctrl+A in both windows Pale Moon and Gedit.

## Your Environment
* KeePassXC version/commit used: Using Revision: 8a3ac7a26e7d6e2355dc1eb4829bdce96ded2a27 from https://aur.archlinux.org/packages/keepassxc-git/
* Qt version (e.g. Qt 5.3): qt5-x11extras 5.7.1-1
* Compiler (e.g. Clang++3.6.0): See aur link.
* Operating System and version: Arch Linux 4.8.13-1

**Comment by rockihack** [comment]
Do you use a wayland compositor?

**Comment by Ghosthree3** [comment]
I am using i3wm.

**Comment by phoerious** [comment]
I can't reproduce it on KDE. Anyone else using i3 window manager who can confirm this?

**Comment by anders-larsson** [comment]
Hi,

I'm using i3wm and just built keepassxc based on 8a3ac7a26e7d6e2355dc1eb4829bdce96ded2a27 and auto-type works fine for me. Had to configure the hotkey combination in keepassxc. I suspect that keepassx and keepassxc does not share configuration file.
Hotkey combination used: Meta+Alt+P.

Qt version: 5.7.1
Compiler: gcc 5.4.0
Operating system: Gentoo Linux

**Comment by phoerious** [comment]
No, they don't. If this is your first KeePassXC start, you need to configure the shortcut first.

**Comment by Ghosthree3** [comment]
I configured KeePassXC from scratch as it didn't appear to have inherited any settings at all.

Tried Meta+Alt+P and that actually worked (???) so I retried some binds. Ctrl+A, Alt+A, Shift+A, and any combination of _two_ of them works now (I tried Ctrl+A on its own the other day so I don't know what the hell because I haven't closed or reopened it, I have done package updates though maybe something else fixed it) but my original bind of Ctrl+Alt+Shift+A still doesn't work. That's acceptable for now I suppose since at least I can use _something_. I'd really like it if you could use all three modifiers though.

**Comment by mdxe** [comment]
same issue on Ubuntu 16.10... all other keyboard shortcuts appear to work fine, but CTRL-V for performing the auto-type is broke... I have to right click on the entry and click "perform auto-type"

**Comment by TheZ3ro** [comment]
@mdxe do you have the focus on the KeePassXC window? CTRL-V is a shortcut already binded by OS's paste command

**Comment by Ghosthree3** [comment]
Since 'successfully' setting the bind I haven't had the issue recur even after a reboot so whatever the problem is it's actually that the bind fails it's that it fails to get set correctly for some reason.

**Comment by mdxe** [comment]
@TheZ3ro, yes I had the focus on the KeePassXC window and the correct entry when pressing CTRL-V.

**Comment by droidmonkey** [comment]
In general the use of CTRL+V as a global shortcut is not a very good idea. For one, many applications trap that key combo for themselves. This prevents KeePassXC from ever seeing it! For another, it is very easy to accidentally invoke that shortcut which could result in inadvertent spillage of data.

**Comment by mdxe** [comment]
It makes sense but I didn't change the keyboard shortcuts, maybe the default should be updated.

**Comment by phoerious** [comment]
KeePassXC uses Ctrl+V for autotyping, but only when it already has focus. For global autotype, you need to set a different shortcut. Don't use Ctrl+V for that.

**Comment by tdussmann** [comment]
Confusion between auto-type of selected entry and global (auto-select) auto-type aside, 
I also had troubles with the latter. First, I was not successful with setting ctrl+alt+shift+a as global auto-type shortcut. 
Second, it did not work at all once I had tried to bind to ctrl+alt+a instead. But now after a restart of KeePassXC it seems to work at last...
DE is Cinnamon on LinuxMint 18.1, using latest AutoImage

Unrelated "issue", but is a global "auto-type selected" hotkey planned for KeePassXC?

**Comment by Ghosthree3** [comment]
@tdussmann Keep trying to set the full hotkey, it will work eventually if you set it 'right'. I don't know what I did but after I finally managed to set ctrl+alt+shift+a 'correctly' it has continued to work for a week now. There's just something weird about setting the hotkey and sometimes it won't work.

**Comment by mdxe** [comment]
I set the global auto-type to CTRL+SHIFT+A and it works fine but the in-app auto-type CTRL+V still doesn't work...

**Comment by phoerious** [comment]
Any update on this? Is this still an issue?

**Comment by Ghosthree3** [comment]
I can still reproduce it yes (and now am struggling to fix it again).

**Comment by kaemitsu** [comment]
@phoerious I believe this has been fix in:
KeePassXC - Version 2.2.0 Revision: caa49a8ef3ee28ed478192389b21d61107b3b8e0 and Revision: 99e3af8ff71c401a4854af353667da58bc37299f.
However, for the program to successfully recognize the global Auto-Type shortcut, it has to be setup in the program's settings, and then the program needs to be closed and reopened for the changes to take effect.
