### ISSUE TITLE
"closing without saving" prompt when database was not modified and was on external storage unmounted without closing keepass

### ISSUE THREAD

**Issue by lucamp** [keepassxreboot/keepassxc#2230]
Hi,
My kbdx files resides on an external USB key.

## Current Behavior

Keepassxc in set to:
- automatically save after every change
- don't mark database as modified for non-data changes

"automatically reload the database when modified externally" is unchecked so the database is not shared at the same moment with other programs

In that case if I forgot to close keepassxc and dismount the external media, a prompt "files has changed, do you want to load the changes?" appears, Choosing "no" and closing without saving works (please remember that is set to "automatically save after every change")..

## Expected Behavior
In my opinion this leads to confusion as until there is no change made to the database keepassxc should just close right away

Sincerely
Luca

## Debug Info
KeePassXC - Version 2.3.4
Revision: 6fe821c

Libraries:
- Qt 5.7.1
- libgcrypt 1.7.6-beta

Operating system: Debian GNU/Linux 9 (stretch)
CPU architecture: x86_64
Kernel: linux 4.9.0-8-amd64

Enabled extensions:
- Auto-Type
- YubiKey

**these also appears but they are not enabled:**
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent

**Comment by droidmonkey** [comment]
The reason for this is there is a process watching the file for any external changes and when you remove the USB key that triggers a "change" to fire off. I agree that if the file is missing then this should not trigger a prompt.
