### ISSUE TITLE
New version always matches URL scheme

### ISSUE THREAD

**Issue by AdamPS** [keepassxreboot/keepassxc#2237]
My database has many http:// URLs for sites that are actually https://.  This is due to import of logins from a different tool that stored only a domain without URL scheme.

Everything has been working fine, but since upgrade to v2.3.4 I now get the popup "Error: No logins found" - even though I have unticked the "Match URL scheme" option in KeePassXC browser integration settings.

## Steps to Reproduce
1. Set browser integration setting "Match URL scheme" to false/unticked.
2. Create a database entry for http://example.com
3. Visit https://example.com and press AS+U

## Expected Behavior
KeePassXC will fill the login

## Current Behavior
Popup "Error: No logins found"

## Context
KeePassXC is totally broken in my scenario.  I have hundreds of entries so manually fixing each URL is not attractive.  Please can anyone advise me?
1. Is there any way to bulk fix all the URL schemes?  That would be a good solution for me?
2. OR Is it likely that you can fix this problem and create a new release of KeePassXC quite soon?
3. OR Is there a way I can go back to the old version?  I only see the latest version on https://keepassxc.org/download/.

Thanks!

## Debug Info
KeePassXC - Version 2.3.4
Revision: 6fe821c

Libraries:
- Qt 5.11.1
- libgcrypt 1.8.3

Operating system: Windows 7 SP 1 (6.1)
CPU architecture: x86_64
Kernel: winnt 6.1.7601

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by varjolintu** [comment]
With KeePassXC 2.3.4 the scheme matching is more strict. This means if your entry has an URL `https://example.com` it won't return any credentials to plain HTTP sites (meaning e.g. `http://example.com`).

**Comment by AdamPS** [comment]
Thanks for the explanation.  I guess that #2232 has become more important now that the scheme matching is more strict.  I have gone back to 2.3.3 for now.  In case anyone else finds this issue and wants to downgrade, note that you have to uninstall 2.3.4 to allow the installer for an earlier version to run.

**Comment by AdamPS** [comment]
I have found a way to bulk fix all the URL schemes.  Install the original KeePass 2 and use XML replace https://keepass.info/help/v2/xml_replace.html.  The second example is exactly this scenario.

**Comment by droidmonkey** [comment]
Cool
