### ISSUE TITLE
Keepassxc no longer recognizes my Yubikey after update to Ubuntu 18.04

### ISSUE THREAD

**Issue by jpc2769** [keepassxreboot/keepassxc#2239]
I was running an earlier version of Ubuntu, Keepassxc and Yubikey worked perfectly.

Yesterday I upgraded to Ubuntu 18.04, now when I try to open the database, I click on "refresh" next to challenge response, and nothing happens. This has crippled me, I cannot access any of my email, bank accounts, etc.

KeePassXC - Version 2.3.1
Revision: 2fcaeea

Libraries:
- Qt 5.9.5
- libgcrypt 1.8.1

Operating system: Ubuntu 18.04.1 LTS
CPU architecture: x86_64
Kernel: linux 4.15.0-33-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by droidmonkey** [comment]
See #1342

**Comment by jpc2769** [comment]
I didn't use snap, or even know what that is...

**Comment by droidmonkey** [comment]
I suspect this is related to your upgrade to 18.04

**Comment by jpc2769** [comment]
Can someone please help me? I am locked out of all my bank accounts, I cannot reset the passwords because I am also locked out of all my email accounts, and I have bills coming due that I cannot pay because I cannot log on to the electronic bill pay (paperless was a mistake).

I am desperate, please help!

**Comment by droidmonkey** [comment]
jpc, can you get on our IRC channel today? I can try to help you further but need real-time comms. Connect via this link: https://webchat.freenode.net/?channels=keepassxc-dev

**Comment by jpc2769** [comment]
Sure, that would be great! What time?

**Comment by droidmonkey** [comment]
Follow these instructions: https://freenode.net/kb/answer/registration

**Comment by jpc2769** [comment]
Sorry I had to go to a meeting, I am on now.

**Comment by jpc2769** [comment]
I had to log off and log back on again, I used my nickname and password, it still says "#keepassxc-dev Cannot join channel (+r) - you need to be identified with services"

**Comment by droidmonkey** [comment]
It worked for me as a test. You need to connect then issue the following command:

```/msg NickServ REGISTER [password] [email]```

than wait until you see this message:

```[nick] is now registered to [email], with the password [password].```

Now you can join the dev channel by using the command:

```/join #keepassxc-dev```

Let's do this tomorrow morning, I'll be on.

**Comment by jpc2769** [comment]
This turned out to be a problem with Ubuntu, the upgrade broke my ability to mount USB devices, and I guess that was interfering with the Yubikey being recognized as well. I ended up doing a wipe and reinstall of the operating system, now it seems to be working (fingers crossed).

**Comment by droidmonkey** [comment]
Yay! Thank goodness, I'm glad you can get in now. I recommend backing up the database without yubikey and store it somewhere safe offline.

**Comment by jpc2769** [comment]
Is there a way to set the database up so that I can use Yubikey OR a password to open it? I seem to remember trying to do that when I first installed KeepassXC, but that it was making m use both to open everytime.

**Comment by droidmonkey** [comment]
No, you cannot do that because it doesn't make any sense (also the way cryptography works). When you encrypt something, if you ever have a choice to NOT provide information, that means the encryption is weakened.

**Comment by jpc2769** [comment]
Makes sense. But I could create a duplicate database keyed to a password,
correct?

**Comment by droidmonkey** [comment]
Yes absolutely
