### ISSUE TITLE
Increase iteration for Keepass DB with several factors

### ISSUE THREAD

**Issue by ngabormini** [keepassxreboot/keepassxc#224]
Password manager passwords are the ones that humans need to memorize.

Please increase the iteration count for the encrypted DB that Keepass use, so if even a human will use an "easier" password, the bruteforcing should be extremely slow. 

IMHO users can wait for 1-2 seconds when opening the encrypted DB.

**Comment by phoerious** [comment]
Changes to the key transformation settings are planned for 2.2.0. See #191
