### ISSUE TITLE
gpg-agent does not seem to work with the agent integration

### ISSUE THREAD

**Issue by jorgheymans** [keepassxreboot/keepassxc#2243]
I'm on Ubuntu 16.04 LTS, trying to use keepassxc to manage my ssh keys. Ubuntu by default manages the keys using gpg-agent, which is started with enable-ssh-support. However, defining an entry with a key in the ssh-agent section, then pressing the add/remove button does not work. The key is not added. I ensured keepassxc is started with ssh-agent option enabled.  

When i then stop gpg-agent, and from a shell start ssh-agent and from that same shell keepassxc, then everything works. So I am wondering if anybody has tested the agent integration of keepassxc with gpg-agent instead of ssh-agent ? Is this something we can reasonably expect to work ?

## Expected Behavior
gpg-agent running with ssh support enabled should be able to accept keys from keepassxc

## Debug Info

KeePassXC - Version 2.3.4
Revision: 6fe821c

Libraries:
- Qt 5.5.1
- libgcrypt 1.8.1

Operating system: Ubuntu 16.04.5 LTS
CPU architecture: x86_64
Kernel: linux 4.4.0-134-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by jorgheymans** [comment]
right #2029 seems related and gives more info why gpg-agent with ssh support enabled is not the same as ssh-agent.

**Comment by droidmonkey** [comment]
So is this a duplicate?

**Comment by jorgheymans** [comment]
Even though I'm seeing this on Ubuntu this is the same issue it seems yes.
