### ISSUE TITLE
Auto type appends character to username

### ISSUE THREAD

**Issue by univrsal** [keepassxreboot/keepassxc#2245]
Autotype seems to have issues with steams login window, which results in it appending the letter "a" at the end of the username. This doesn't always happen, but when it does it usually does so repeatedly for multiple login attempts. 

## Expected Behavior
Autotype should select the steam window, type the username and then tab into the password field and finally login with enter.

## Current Behavior
Autotype focuses the window, types the username and appends the letter "a", which is not part of the username, then focuses the password field and proceeds to login (Which obviously fails due to the wrong username)

## Steps to Reproduce (for bugs)
![gif](https://user-images.githubusercontent.com/8353672/44591236-79dd3d80-a7bd-11e8-9689-daae782c4784.gif)
1. Open steam
2. Press global auto type hotkey
3. Select login info 

## Context
It's a little annoying to have to try multiple times to properly login to steam. I use a VPN which results in steam requesting my login info regularly even after saving it, so auto type is very useful for that.
The fact that it happens randomly is obviously problematic in finding the error, so I'm not expecting this to be of high priority or fixed at all (Maybe it's even an issue on my side), but I thought I'd at least report it.
I'm sure that it's not my keyboard, the character appended is always "a", in the preview it's uppercase but recently it's been lowercase. My global autotype hotkey is Ctrl + Alt + A, but even with other hotkeys it has happened (Still with the character "a").

## Debug Info
KeePassXC - Version 2.3.4
Revision: 6fe821c

Libraries:
- Qt 5.11.1
- libgcrypt 1.8.3

Operating system: Windows 10 (10.0)
CPU architecture: x86_64
Kernel: winnt 10.0.17134

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by droidmonkey** [comment]
It looks like your password isn't being typed at all in the preview. Does your password begin with "a"?

**Comment by univrsal** [comment]
It's being typed, I just added a black bar over it, since I didn't want to show how long my password is :P
And yeah it begins with an 'a', I guess that solves the mystery. I'll just use a delay then, thanks for the quick help!
