### ISSUE TITLE
Using Download Favicon Crashes

### ISSUE THREAD

**Issue by whodknee** [keepassxreboot/keepassxc#225]
## Steps to Reproduce (for bugs)

1. Create an entry with a website
2. Go to the Icon tab
3. Select download favicon
4. Select the newly downloaded favicon
5. Select OK

## Context

I was trying to update all of my passwords to use the favicons of the sites, but this bug made it very annoying to do so.

It doesn't seem to crash when selecting that favicon again after the first time.

## Your Environment

* KeePassXC version/commit used: v2.10
* Operating System and version: MacOS 10.12.1

**Comment by nougad** [comment]
Can confirm (v2.1.0, arch linux).

I think it happens when you click download and right after "OK" while the download is still in progress.

**Comment by whodknee** [comment]
Just tested after waiting 5 minutes before clicking OK. Still crashes.

**Comment by droidmonkey** [comment]
Interesting i tested this condition when i coded the feature (click ok while still downloading). Is it possible for either of you to run in debug mode and see where it is crashing. Could be Mac specific.

**Comment by whodknee** [comment]
I can. How do I run it in debug mode?

**Comment by phoerious** [comment]
cmake -DCMAKE_BUILD_TYPE=Debug.

But louib already fixed the issue in the release/2.1.1 branch. :-)

**Comment by louib** [comment]
@whodknee would be nice if you could test the release/2.1.1 branch and confirm that the bug if fixed on your end :)
