### ISSUE TITLE
Feature: Caps Lock

### ISSUE THREAD

**Issue by MAPIIIAJI** [keepassxreboot/keepassxc#2250]
Please add a trigger that will notify the enabled Caps Lock. This will be very healthy. Thank in advance.

**Comment by nadieenespecial** [comment]
Yes, please

**Comment by michaelblyons** [comment]
Also mentioned [here](https://github.com/keepassxreboot/keepassxc/issues/813#issuecomment-479909128). This will prevent heart attack when the login error message says "Database may be corrupted."

**Comment by droidmonkey** [comment]
This is very challenging to do (believe it or not)

**Comment by OLLI-S** [comment]
Many other password managers and also Windows 10 warn you when you have Caps-Lock turned on.

**Comment by phoerious** [comment]
Please see #3646.

**Comment by OLLI-S** [comment]
@phoerious Damn, I searched for "Caps" in the issues but did not find #3646.
Have overseen that at top of this issue there is "May be fixed by #3646"
Sorry...
