### ISSUE TITLE
Use Custom Icon multi-selector does not show correct number of icons

### ISSUE THREAD

**Issue by Sacha00Z** [keepassxreboot/keepassxc#2251]
When editing an entry (x), and after pressing "Download Favicon", a successful download completes. The list of custom icons only shows favicons 1 to favicons n-1. The last downloaded favicon n is excluded from the list.
If you then create a new entry (y), and press "Download Favicon", the favicon for entry x appears (instead of the favicon for entry y)
This has all the hallmarks of an array length calculation issue for the number of items to show in the "use custom icon" list.

## Expected Behavior

When I press "Download Favicon" the favicon for my current site should be displayed in the "custom icon" list.

## Current Behavior

When I press "Download Favicon" the favicon for my previously edited site is added to the end of the "custom icon" list.

## Possible Solution

This looks like a for loop needs to execute one more time.

## Steps to Reproduce (for bugs)

1. Edit an entry for google.com, go to "icon", and hit "Download Favicon"
2. Create a new entry for yahoo.com, go to "icon", and hit "Download Favicon"
3. Note that only the google favicon is available.
4.

## Context

I originally created my kdbx in KeePass and used a plugin to download favicons (can't remember which one). I have since migrated to KeePassXC. I run it on various Windows 10 machines, and also on Linux, synchronising via OneDrive.

## Debug Info

KeePassXC - Version 2.3.4
Revision: 6fe821c

Libraries:
- Qt 5.11.1
- libgcrypt 1.8.3

Operating system: Windows 10 (10.0)
CPU architecture: x86_64
Kernel: winnt 10.0.17134

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

Libraries:
- LIBS

Operating system: OS Windows 10
CPU architecture: ARCH x64
Kernel: KERNEL

Enabled extensions:
- EXTENSIONS

**Comment by droidmonkey** [comment]
Can you replicate this on a new database? I cannot at all, even after adding several hundred icons. Also, the code doesn't do any loops or counting, that is all handled by Qt.

**Comment by Sacha00Z** [comment]
Can't replicate it on a new database. Only seems to affect my old database (inherited from KeePass & 3rd party plugins)

**Comment by droidmonkey** [comment]
I bet the error was introduced by that plugin.

**Comment by droidmonkey** [comment]
Yes that is what I was referring too, you can try upgrading to kdbx4 to see if that clears up the issue, data is stored differently in the new version.

**Comment by Sacha00Z** [comment]
That didn't work, however, I have found a solution:
1. Create a new kdbx file
2. Copy over all entries from existing kdbx to new one
3. Try to download favicon
=> success. Functions as expected.

**Comment by droidmonkey** [comment]
I think I found a potential error point, if there are multiple icons with the same UUID, than only the last icon with that UUID will be in the icon map. However, there is a vector (Metadata::m_customIconsOrder) that keeps track of the icon's order when writing back to the XML. The UUID's get appended to that vector. So it is conceivable that the same icon will get written multiple times into the database.

The easiest fix would be to detect a UUID collision, issue a warning, and issue a new UUID to the conflicting icon.
