### ISSUE TITLE
Identifier [Locked] don't appear on tab in first start

### ISSUE THREAD

**Issue by MAPIIIAJI** [keepassxreboot/keepassxc#2252]
In some cases (was observed at the first start), if I have 2 DB (at least I have 2 bases :) ), identifier on db tab '[Locked]' don't appear.
This is opened DB
![asdf](https://user-images.githubusercontent.com/35526267/44827722-cc8b7f00-ac2d-11e8-9792-d9697193db9c.jpg)
In parallel, there is another base, but it is locked until now not open. But here the pointer that the database is locked 'locked' is not displayed.
![asdf1](https://user-images.githubusercontent.com/35526267/44827723-cc8b7f00-ac2d-11e8-9022-e349cbce023a.jpg)
This case occurs when the software is first started. During the operation this behavior was not observed
I use  KeePassXC 2.3.1

**Comment by droidmonkey** [comment]
Please update to 2.3.4 if you can, there were some enhancements made.

**Comment by MAPIIIAJI** [comment]
Unfortunately, the problem affects version 2.3.4

**Comment by phoerious** [comment]
This is a general issue in 2.3 and has been fixed in 2.4.
