### ISSUE TITLE
Map CTRL+SHIFT+M to minimize to tray icon (if enabled)

### ISSUE THREAD

**Issue by apfelchips** [keepassxreboot/keepassxc#2254]
## Expected Behavior
Pressing Ctrl+W should close/minimize to tray the KeepassXC window

## Current Behavior
Ctrl+W closes the Database, but keeps the window Open which goes against what most users expect to happen on the usual Window closing Shortcut.

## Possible Solution
- Remap Ctrl+W to close the current window / (minimize to tray as chosen in settings)
- Remap Locking/Closing the Database to Shift+Meta+L (comp. Meta+L to lock the Screen on Windows)

## Context
Give a more consistent UX when using shortcuts.

## Debug Info
KeePassXC - 2.3.4

Operating system: ALL
CPU architecture: ALL
Kernel: ALL

**Comment by apfelchips** [comment]
I've created a bug bounty on Bountysource for this:
https://www.bountysource.com/issues/62864169-remap-ctrl-w-to-close-window-instead-of-closing-the-db

**Comment by droidmonkey** [comment]
I appreciate your enthusiasm, but you are not the decider for what different keyboard shortcuts are mapped to. In almost all tabbed applications, CTRL+W closes the currently open tab (in our case database). CTRL+M minimizes to tray and CTRL+Q quits. This would be best implemented as CTRL+SHIFT+M.

**Comment by apfelchips** [comment]
Maybe make these shortcuts reassignable then. 
For me KeepassXC isn't really a tabbed application, especially if you only ever open one Database. Heck Ctrl+Tab doesn't even do what it's supposed to.

Coming from 1Password this one little shortcut drives me nuts.
Since on macOS Meta+M also doesn't minimize to tray but to a minimized window in the Dock.

**Comment by droidmonkey** [comment]
Well we are a tabbed application, even if you close all tabs the welcome screen comes up. CTRL+TAB being broken is captured in #1333.

**Comment by droidmonkey** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [#2254 - CTRL+SHIFT+M to minimize to tray](https://trello.com/c/sCrnOvSd/3-2254-ctrlshiftm-to-minimize-to-tray)

**Comment by rjekker** [comment]
I'd like to contribute to the discussion from a different viewpoint: I use the keyboard for almost anything and the fact that there seems to be no way to minimize keepass with a shortcut drives me crazy. I need to grab the mouse and find this little tray icon to minimize the window, which is not user-friendly at all.

**Comment by droidmonkey** [comment]
@rjekker what operating system are you using? I am not aware of many applications that have shortcuts to minimize. Most Linux window managers let you define custom keys to raise and lower windows.
