### ISSUE TITLE
When keepassxc is raised to the front when locked and triggered from the browser extension, it shall close afterwards

### ISSUE THREAD

**Issue by Tamriel** [keepassxreboot/keepassxc#2256]
## Current Behavior
- The database is minimized in the tray
- The database is locked
- Hitting alt + shift + u in the browser brings up the unlock dialog
- I login in the browser
- keepassxc stays open

## Expected Behavior
- keepassxc shall minimize itself back to the tray

## Debug Info
KeePassXC - Version 2.3.3
Revision: 0a155d8

Bibliotheken:
- Qt 5.11.1
- libgcrypt 1.8.3

Betriebssystem: Manjaro Linux
CPU-Architektur: x86_64
Kernel: linux 4.14.60-1-MANJARO

Aktivierte Erweiterungen:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by varjolintu** [comment]
I guess now the windows just stays in the background. Maybe it could be detected that if KeePassXC was in the tray, it would return back.

**Comment by Thulium-Drake** [comment]
I agree, the window is in a certain state, it should return to that same state.

In relation to this, is it possible for the plugin to 'trigger' this, instead of the finger gymnastics required to hit the shortcut?

A use case would be, one would browse to https://example.com and the plugin will popup the database if it's closed.

**Comment by Thulium-Drake** [comment]
Agreed, could it be made toggable in the plugin in an easy way?

Even without, if it also responds to ESC if you want to dismiss the popup, it's not much of an issue in my opinion.

**Comment by varjolintu** [comment]
That could be added as an option, which is not enabled by default.

**Comment by varjolintu** [comment]
@Tamriel I'm including this fix to #1904. It still needs some work. Only the macOS side is currently ready.
