### ISSUE TITLE
Rendering artifacts of the password input form [regression]

### ISSUE THREAD

**Issue by ruslo** [keepassxreboot/keepassxc#2257]
## Expected Behavior

Version 2.3.3 looks good:
![screen-2 3 3](https://user-images.githubusercontent.com/4346993/44943626-d77f1480-add1-11e8-9e68-dfdebb4c6ec8.png)

## Current Behavior

Version 2.3.4 has some artifact:
![screen-2 3 4](https://user-images.githubusercontent.com/4346993/44943635-19a85600-add2-11e8-8d1d-dbe0c4b0d902.png)
![image](https://user-images.githubusercontent.com/4346993/44943648-52e0c600-add2-11e8-8dfe-75f1e6f480b5.png)

## Possible Solution

Buggy Qt version (?) KeePassXC 2.3.3 use Qt 5.10.1 and KeePassXC 2.3.4 use Qt 5.11.1.

## Steps to Reproduce (for bugs)

1. Download/install 2.3.4
2. Start typing password

## Debug Info

KeePassXC - Version 2.3.4
Revision: 6fe821c

Libraries:
- Qt 5.11.1
- libgcrypt 1.8.3

Operating system: Windows 10 (10.0)
CPU architecture: x86_64
Kernel: winnt 10.0.17134

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by droidmonkey** [comment]
I noticed that too, doesn't affect anything, and not something we can fix in our project.
