### ISSUE TITLE
Set file open/save dialog to user's home directory for snaps

### ISSUE THREAD

**Issue by droidmonkey** [keepassxreboot/keepassxc#2259]
## Expected Behavior

The keepassxc snap build points to the user home directory when you open or save the database.

## Current Behavior

The snap container fakes the user's home directory to be ~/snap/keepassxc/current/

This is a volatile directory that changes based on the snap version and will be deleted without warning if keepassxc is uninstalled.

## Possible Solution

Fake it till we make it?

**Comment by Lin-Buo-Ren** [comment]
I'm not familiar with keepassxc, but I'm curious which path does it requires to access under the home directory?

It might be sane if we set the default save path to one of the XDG user dirs, like ~/Documents/KeePassXC

**Comment by droidmonkey** [comment]
No just ~ in general.

**Comment by Lin-Buo-Ren** [comment]
I've installed the snap and noticed that the `home` interface allows non hidden files access, so we probably could just set the `HOME` variable in a launcher script.

It should be possible to parse the user's actual HOME directory by using the `getent` command.

**Comment by droidmonkey** [comment]
This is no longer an issue with the latest snap.
