### ISSUE TITLE
Mounted NTFS folders not accessiblw from new file browser in 2.3.4 compared to 2.3.1+dfsg in standard ubuntu store install as well as snap

### ISSUE THREAD

**Issue by therobyouknow** [keepassxreboot/keepassxc#2260]
Installing version 2.3.4 from the Ubuntu Software store, I cannot browse to a .kbdx file that's in a mounted NTFS folder.

## Expected Behavior

Should be able to access the /localshare folder which is an NTFS mount, on the basis that to Ubuntu, this appears like any other folder in its filesystem and shouldn't be discriminated.

## Current Behavior

My NTFS folder is mounted in /etc/fstab like so:
UUID=FFFFFFFFFFFFFFFF /localshare ntfs-3g uid=1000,gid=1000,dmask=022,fmask=133 0 0
where FFFFFFFFFFFFFFFF is my uuid (not publicised here).

This folder/directory is accessible through the usual Ubuntu filer browser like others, and to all intents and purposes has the same behaviour.
However this /localshare folder does not show up in the file browser used in Keepassxc 2.3.4 (by the keepassxreboot developer) available from the Ubuntu Software store. Version 2.3.4 appears to use its own custom file browser. See screenshots.

Fortunately, the Ubuntu Software store lists another version of Keepassxc, 2.3.1+dfsg.1-1 (by the KeePassXC Team developer) and this version uses a different file browser, what appears to be native to Ubuntu's windowing system, and this is able to access the /localshare folder. See screenshots.

Both versions were installed via the Ubuntu Software store (and **not by snap** as had been advised in issue https://github.com/keepassxreboot/keepassxc/issues/2190 where mounting might be problematic with the snap version).

Note also the different developers for the 2 versions:  Keepassxc 2.3.4 (by the keepassxreboot developer) 2.3.1+dfsg.1-1 (by the KeePassXC Team developer) - this is a minor, side observation though.

## Possible Solution

Use version 2.3.1+dfsg.1-1 and ensure this is not upgraded in any general software updates whereby the apparent regression is introduced i.e. 2.3.4

Do a diff between versions 2.3.4 and 2.3.1+dfsg.1-1 to see what changes were introduced related to the file browser and in the fix for 2.3.4 i.e. 2.3.5, revert to the code used in 2.3.1+dfsg.1-1

## Steps to Reproduce (for bugs)

See screenshots

## Context

To be able to open my password file as I do in my Windows partition in my Ubuntu-Linux dual boot setup.

## Debug Info

KeePassXC - VERSION: versions 2.3.4 and 2.3.1+dfsg.1-1
Revision: REVISION: not specified

Libraries:
- LIBS: not specified

Operating system: OS: 18.04.1
![screenshot from 2018-09-01 21-20-10](https://user-images.githubusercontent.com/1080646/44949855-2b214a80-ae32-11e8-9a3b-e8736ba0309c.png)
![screenshot from 2018-09-01 21-21-03](https://user-images.githubusercontent.com/1080646/44949856-2b214a80-ae32-11e8-808b-ab491f1e7981.png)
![screenshot from 2018-09-01 21-21-15](https://user-images.githubusercontent.com/1080646/44949857-2b214a80-ae32-11e8-9f57-163e5c871599.png)
![screenshot from 2018-09-01 21-24-11](https://user-images.githubusercontent.com/1080646/44949858-2b214a80-ae32-11e8-8fe1-a9a51774cf7e.png)
![screenshot from 2018-09-01 21-24-31](https://user-images.githubusercontent.com/1080646/44949859-2bb9e100-ae32-11e8-92a8-b1bf0b4d486e.png)
![screenshot from 2018-09-01 21-25-55](https://user-images.githubusercontent.com/1080646/44949860-2bb9e100-ae32-11e8-862a-2d7908619b85.png)
![screenshot from 2018-09-01 21-26-43](https://user-images.githubusercontent.com/1080646/44949861-2bb9e100-ae32-11e8-82f6-b187a386518e.png)
![screenshot from 2018-09-01 21-27-09](https://user-images.githubusercontent.com/1080646/44949862-2bb9e100-ae32-11e8-84a4-4c1c515eded2.png)
![screenshot from 2018-09-01 21-27-20](https://user-images.githubusercontent.com/1080646/44949863-2c527780-ae32-11e8-9ae4-e94bbc5a0046.png)

 64bit LTS
CPU architecture: ARCH: amd64 - intel i7 quad core 64bit: Intel® Core™ i7-2600 CPU @ 3.40GHz × 8: Intel® Sandybridge Desktop 
GNOME: 3.28.2
Memory: 32Gb
Kernel: KERNEL
robdavisprojects@Workstation-U64:~$ uname -r
4.15.0-33-generic

Enabled extensions:
- EXTENSIONS: not specified

**Comment by droidmonkey** [comment]
This is because one is a snap distribution and one is the natively installed distribution. Please read our FAQ: https://keepassxc.org/docs/#faq-appsnap-homedir
