### ISSUE TITLE
Add WSL best practice

### ISSUE THREAD

**Issue by lusitania** [keepassxreboot/keepassxc#2261]
What is your recommended procedure to expose SSH and GPG keys in KeePassXC to WSL, i.e. Ubuntu Bionic?

I'd like to move from my current KeePass/KeeAgent/socat setup for WSL to KeePassXC but I'm struggling with the details and the lack of documentation/best practices. I thought of using Windows' native `ssh-agent` with [ssh-agent-wsl](https://github.com/rupor-github/ssh-agent-wsl) but I failed, see #2262.

## Debug Info
KeePassXC - Version 2.3.4
Revision: 6fe821c

Libraries:
- Qt 5.11.1
- libgcrypt 1.8.3

Operating system: Windows 10 (10.0)
CPU architecture: x86_64
Kernel: winnt 10.0.17134

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by hifi** [comment]
The native agent is probably the best route to go.

**Comment by h4de5** [comment]
@lusitania not sure if best practice - but it seems to work fine without the former socat solution.
i use keepassxc + putty pageant + [wsl-ssh-pageant](wsl-ssh-pageant)
keepass puts the key into pagent, and a task in the systray forwards it to wsl and windows ssh-agent - using this command on startup:

```wsl-ssh-pageant-amd64.exe --wsl ssh-agent.sock --systray --winssh ssh-pageant```

**Comment by lusitania** [comment]
Solved with #1984

**Comment by mxcd** [comment]
I experienced the same struggles and wrote a tool for forwarding the pageant identities to the WSL:
https://github.com/mxcd/PuttyAuthSock
