### ISSUE TITLE
Support native ssh-agent on Windows 10 1803

### ISSUE THREAD

**Issue by lusitania** [keepassxreboot/keepassxc#2262]
I understand that KeePassXC only utilises an external SSH agent, such as pageant. With [1803](https://blogs.msdn.microsoft.com/commandline/2018/03/07/windows10v1803/) Windows received native [SSH support](https://blogs.msdn.microsoft.com/powershell/2017/12/15/using-the-openssh-beta-in-windows-10-fall-creators-update-and-windows-server-1709/) and an `ssh-agent` that runs as a service. KeePassXC v.2.3.4 fails to recognise this service.

## Expected Behavior

Keys are loaded into into Windows' `ssh-agent`/_OpenSSH Authentication Agent_.

## Current Behavior

KeePassXC starts with:
> No agent running, cannot add identity.

## Steps to Reproduce (for bugs)

1. Update to Windows 10 1803 (17134.228)
2. `Start-Service ssh-agent` as admin
3. Start KeePassXC and have it load SSH keys

## Context

Run KeePassXC with Windows' built-in tools.

## Debug Info

KeePassXC - Version 2.3.4
Revision: 6fe821c

Libraries:
- Qt 5.11.1
- libgcrypt 1.8.3

Operating system: Windows 10 (10.0)
CPU architecture: x86_64
Kernel: winnt 10.0.17134

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by hifi** [comment]
This already exists as PR #1994.

**Comment by lusitania** [comment]
duplicates #1984 
thanks @hifi
