### ISSUE TITLE
recovery keys for OTP [feature]

### ISSUE THREAD

**Issue by Leptopoda** [keepassxreboot/keepassxc#2263]
## Expected Behavior
some services (e.g. GItHub) give you one time recovery/backup codes when 2FA/OTP is enabled

## Current Behavior
Currently the only option is to write them into the "Notes" sector but because those are one time you have to edit the entry every time to delete the current one

## Possible Solution
<-->

**Comment by droidmonkey** [comment]
This is handled by #1167

**Comment by RAnders00** [comment]
Sorry for reviving this old ticket, but the related PR is not related to this feature request? It's about generating a QR code from the stored secret, this feature request is for adding first-class support for storing recovery tokens handed out by services without having to use the Notes field. Can we reopen this?

Note: [KeePassOTP](https://github.com/Rookiestyle/KeePassOTP) stores the recovery codes in the attribute `KeePassOTP.RecoveryCodes`, maybe we should support this attribute as well.

**Comment by droidmonkey** [comment]
Why is that necessary? Notes is a great place to store them, or make your own attribute. This absolutely doesn't need a GUI feature.

**Comment by Leptopoda** [comment]
You are completely right. My idea was an extra field for storing secrets that can be marked as already used.
This is indeed a very old issue so you might be better of opening a new one. (as this one didn't ever gain any traction).
