### ISSUE TITLE
downloading favicon shows progress bar twice

### ISSUE THREAD

**Issue by muchqs** [keepassxreboot/keepassxc#2265]
When I click on the download favicon button, it either says failed to download or download instantly, but in either case a progress bar window then shows up and get stuck at 0% or 1% and doesn't go away on its own and I have to click cancel. Happening for every website.

**Comment by droidmonkey** [comment]
Please don't delete the issue template. Paste your debug info from the about dialog.

**Comment by alvarogmj** [comment]
This happens for me also

KeePassXC - Version 2.3.4
Revision: 6fe821c

Libraries:
- Qt 5.9.3
- libgcrypt 1.8.2

Operating system: OS X El Capitan (10.11)
CPU architecture: x86_64
Kernel: darwin 15.6.0

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by muchqs** [comment]
Do you have that "google as fall-back" option checked? I think that is causing this issue. But if i uncheck the option I can't download any icon. Every website just returns the error "unable to fetch icon".

**Comment by alvarogmj** [comment]
No, I don't have it checked, and the download works for me. I only get "unable to fetch icon" when the icon is not at /favicon.ico, I guess that is expected :)

**Comment by whisdol** [comment]
When the "Google as fallback" option is checked, I even get three popups:
![image](https://user-images.githubusercontent.com/5374166/45253290-30682300-b365-11e8-82ef-d87c5c38c89a.png)
The popups appear for me in this order for namecheap.com, where the favicon download fails:
1) Download progress from namecheap.com
2) Download progress from namecheap.com
3) Download progress from google.com
4) All popups are closed, an error message is displayed
5) Download progress from namecheap.com
6) Download progress from namecheap.com
7) Download progress from google.com

**Comment by Olfrix** [comment]
Same issue on my platform.

KeePassXC - Version 2.3.4
Revision: 6fe821c

Libraries:
- Qt 5.5.1
- libgcrypt 1.8.1

Operating system: Linux Mint 18.3
CPU architecture: x86_64
Kernel: linux 4.10.0-38-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by tlnagy** [comment]
As @Olfrix points out, this isn't isolated to windows. I can confirm this is occurring on Linux as well. Sometimes I get multiple popup windows, other times I get a Download Progress popup that is stuck at 1%. 

![image](https://user-images.githubusercontent.com/1661487/45383519-50475300-b5c0-11e8-9000-1a70e8e31466.png)

KeePassXC - Version 2.3.4
Revision: 2cc52a8
Distribution: Snap

Libraries:
- Qt 5.9.5
- libgcrypt 1.8.1

Operating system: Ubuntu Core 18
CPU architecture: x86_64
Kernel: linux 4.15.0-33-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by droidmonkey** [comment]
I thought I had fixed this when I also fixed the associated crash this caused. Unfortunately, looks like there is still a race condition that occurs. The dialogs should have an update timeout that autocloses them.

**Comment by kneitinger** [comment]
@droidmonkey it seems that `setMinimumDuration()` used in [the fix for the crash](https://github.com/keepassxreboot/keepassxc/pull/1980/files#diff-26f55b824b03f947ce9777d4086c5f66R48) only delays the time until the progress bar of the cancelled fetch appears.  If I increase it to `4000`, it appears after 4 seconds.
