### ISSUE TITLE
Autosave problem with two databases

### ISSUE THREAD

**Issue by mahasamoot** [keepassxreboot/keepassxc#2267]
## Expected Behavior

Autosave should save every change to every database.

## Current Behavior

Due to use of Megasync, I ended up with two databases.  I didn't notice the merge feature.  Some new entries were put in the "conflicting" database.  It turns out that database has never been updated--per file time stamp.  However, for some reason everything worked fine for a awhile.  Then due to some issues I was having I reinstalled Linux.  Prior to the clean install, I did a full backup of ~.  Post install I hand copied all the files that looked relevant.  Now I see that the DB has never been updated, and I'm missing some extremely important entries. 

## Possible Solution

Is it possible that I missed some important file when I copied them over?  The entries in question are extremely important and cannot be replaced by a simple email password reset.

## Steps to Reproduce (for bugs)

1.  Try following the steps above and see what happens.
2.
3.
4.

## Context

I've lost about a thousand dollars.

## Debug Info

KeePassXC - 2.3.4
Revision: 6fe821c

Libraries:
- Qt 5.11.1
- libgcrypt 1.8.3

Operating system: Antergos Linux (Arch) 
CPU architecture: x86_64
Kernel: Linux version 4.18.5-arch1-1-ARCH

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by droidmonkey** [comment]
Unfortunately your have too many sources of error. I can tell you that autosave works without question. Now, whether your cloud sync service, hard drive, or whatever is working correctly is another matter. 

Likely when you reinstalled Linux you wiped out your KeepassXC settings that disabled autosave. The program would still ask you to save if you made changes though.

**Comment by mahasamoot** [comment]
> Likely when you reinstalled Linux you wiped out your KeepassXC settings that disabled autosave. The program would still ask you to save if you made changes though.

I copied all the settings back into ~ from my local backup.  The problem happened before the reinstall, because the second DB was never saved.  However the problem wasn't apparent to me... perhaps I hadn't rebooted yet.  However, I was being very careful.  I had not one, but two backups of my data.  The cloud sync, and a local backup.  Yet the data is gone.  So "too many sources of error" was in fact, "too many chances to get it right."  Even if the cloud sync erroneously clobbered a newer version of the file from the backup, I would still have it in original copy of the local backup.  

Also if the file was corrupted by the hard drive, it wouldn't be missing entries would it.  It wouldn't open properly.

**Comment by droidmonkey** [comment]
> Due to use of Megasync, I ended up with two databases. 
Why? This is the start of your errors.

> Some new entries were put in the "conflicting" database.
I don't understand this, did you have Passwords.kdbx and Passwords(1).kdbx in your MegaSync? Were you editing the Passwords(1).kdbx instead of the original?

> Post install I hand copied all the files that looked relevant.
Does this include your database files?

You are asserting that autosave is broken for multiple files, but I know for a fact it isn't because I just tested it. What I am trying to tell you is that the fact you had your database across three different files and different services and were copying them back and forth is the most likely reason why you lost data. You MOST LIKELY copied an old passwords file overwriting the current one and boom you lost information.
