### ISSUE TITLE
Add support for so called *Smartcards*

### ISSUE THREAD

**Issue by kenokenobingo** [keepassxreboot/keepassxc#2268]
It would be a great addition for KeePassXC to support so called *Smartcards*. Personally, I’m interested in using the YubiKey on macOS and Linux.

**Comment by phoerious** [comment]
You can use a YubiKey already, just not as a smartcard. We won't implement smartcards directly, but are thinking about an OpenPGP option, which would also allow you to use smartcards.

**Comment by kenokenobingo** [comment]
Thanks. Ah, I didn’t know that, but will try it right away! And yes please, OpenPGP!

**Comment by droidmonkey** [comment]
The implementation of PKCS#11 support is tracked by #255
