### ISSUE TITLE
unable to set certain autotype key combinations

### ISSUE THREAD

**Issue by cericoda** [keepassxreboot/keepassxc#2270]
Seeing as I don't use the accented keys such as é when typing, I would expect to be able to set these as a keyboard shortcut.

However, what happens when I do so is that it's not available (comes up with a red background)

Screenshot:-
https://i.imgur.com/Enrc4Ch.png 

What I would personally like at this point is a link pointing to a document or discussion which shows me how to workaround this and re-enable the shortcut.

If it's not possible to work around it, then a link to an explanatory document or discussion would be useful too.

I had what seemed to me at the time to be a good search for this including pre-existing issues but was unable to find an answer to this.

I would just like to be able to do this on my personal computer where I don't use accented keyboard shortcuts. This worked fine on a previous computer.

KeePassXC - Version 2.3.3
Revision: 0a155d8

Libraries:
- Qt 5.10.1
- libgcrypt 1.8.2

Operating system: Windows 10 (10.0)
CPU architecture: x86_64
Kernel: winnt 10.0.17134

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by droidmonkey** [comment]
> This worked fine on a previous computer.

What are the details of this computer?

Are you using an English keyboard layout?

What key combo are you pressing to get that entry into the text box?

**Comment by droidmonkey** [comment]
can you update that one to 2.3.4 to see if the issue occurs?

**Comment by davejamesmiller** [comment]
I have the same issue in 2.3.4 with a UK keyboard - when I type `Ctrl-Alt-A` it displays `Ctrl+Alt+Á` in red.

I was able to set the key combination by switching to US layout, then after I switched back to UK the shortcut does work as expected.
