### ISSUE TITLE
Latest favicon download not showing

### ISSUE THREAD

**Issue by Jefftree** [keepassxreboot/keepassxc#2271]
After downloading a favicon via Edit -> Icon -> Download favicon, it doesn't show up in the custom icon list. However, after downloading an additional favicon, the previously downloaded favicon shows up. I feel like this is some kind of off by one bug where we're not showing all the downloaded favicons, and the latest downloaded icon is not shown.

## Debug Info
KeePassXC - Version 2.3.3
Revision: 0a155d8

Libraries:
- Qt 5.9.3
- libgcrypt 1.8.2

Operating system: macOS High Sierra (10.13)
CPU architecture: x86_64
Kernel: darwin 17.7.0

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by droidmonkey** [comment]
See #2251.
