### ISSUE TITLE
"Remove key from agent" fails on close in v2.3.4

### ISSUE THREAD

**Issue by lusitania** [keepassxreboot/keepassxc#2273]
Closing a database (ctrl-f4/ctrl-w) does not unload keys from pageant. Program termination works as expected and locking the database gives of
> Agent does not have this identity.

after clearing the keys.

## Expected Behavior

All keys are removed from an SSH agent after closing the database.

## Current Behavior

All keys remain in the agent after closing the database.

## Possible Solution

The keys are properly removed from the agent when I quit KeePassXC. I believe this feature worked in v2.3.3.

## Steps to Reproduce (for bugs)

1. Load a key into the agent. Ensure that "Remove key from agent" in the key's SSH settings is ticked.
2. Close the database with ctrl-w
3. Check pageant
4.

## Debug Info

KeePassXC - Version 2.3.4
Revision: 6fe821c

Libraries:
- Qt 5.11.1
- libgcrypt 1.8.3

Operating system: Windows 10 (10.0)
CPU architecture: x86_64
Kernel: winnt 10.0.17134

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by hifi** [comment]
I believe this is related to #2248 (where you found a workaround) and #1199, could you please confirm if they separately cover both issues described here so this could be closed? Thanks.

**Comment by lusitania** [comment]
Ah yes, this is indeed a duplicate of #1199.
