### ISSUE TITLE
Browser integration lookup without URL scheme broken in version 2.3.4

### ISSUE THREAD

**Issue by nileshgr** [keepassxreboot/keepassxc#2274]
In version 2.3.3 browser integration will lookup name for any website if the entry contains the final part of domain. It does not require scheme (I know there is a preference setting for same, which is disabled always in my case). But the same is not working in 2.3.4.

## Expected Behavior
Note: setting to match using url scheme is disabled

If I go to say twitter, I should be able to use the entry for http://twitter or https://twitter.

## Current Behavior
Version 2.3.3 - lookup works correctly
Version 2.3.4 - lookup does not work, irrespective of the scheme match setting. Without adding scheme in the entry it doesn't lookup.

## Steps to Reproduce (for bugs)
1. Create entry for a site with just the domain name, without scheme
2. Disable scheme match setting in browser integration setting
3. Go the site
4. Try to fill using Alt+Shift+U - no entry found

## Context
Entries in my database are without the scheme when I setup, I can't modify 100s of entries now!

## Debug Info

KeePassXC - 2.3.4 https://github.com/keepassxreboot/keepassxc/releases/download/2.3.4/KeePassXC-2.3.4-Win64.exe

Operating system: Windows 10
CPU architecture: x86_64

Enabled extensions:
- Browser integration

(other extensions not used)

**Comment by droidmonkey** [comment]
Duplicate
