### ISSUE TITLE
[Feature] Clear search and show folder on navigating through group tree

### ISSUE THREAD

**Issue by ArjenR** [keepassxreboot/keepassxc#2278]
Clear the search and search results and show group contents when the group is selected.

## Expected Behavior

A user performs a search and the search results are displayed. 

Upon selecting a group in the group tree, the search and search result are cleared and the contents of the 
selected group is shown. 

## Current Behavior

The user clicks a group and then has to manually clear the search to show the group contents.

## Context

I work a lot with different accounts for both myself and customers. Sometimes I need a specific one, a moment later I need the whole group. I then keep having to clear the search.

## Debug Info
KeePassXC - Version 2.3.4
Revision: 6fe821c

Libraries:
- Qt 5.11.1
- libgcrypt 1.8.3

Operating system: Windows 10 (10.0)
CPU architecture: x86_64
Kernel: winnt 10.0.17134

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by droidmonkey** [comment]
This is already implemented in #1797
