### ISSUE TITLE
What's that Nokia GPL exception?

### ISSUE THREAD

**Issue by rugk** [keepassxreboot/keepassxc#2282]
Uhh, what's [that](https://github.com/keepassxreboot/keepassxc/blob/develop/LICENSE.NOKIA-LGPL-EXCEPTION)?

As the last thing states:
> Furthermore, you are not required to apply this additional permission
to a modified version of the Library.

…you could just remove it, AFAIK. IANAL.

**Comment by droidmonkey** [comment]
You have to read the whole thing. This if a Qt exception to the normal LGPL license.

**Comment by rugk** [comment]
Still think that's not legal and GPL explicitly does not allow extensions or such stuff, but well… I know this is the wrong place to complain about.

**Comment by droidmonkey** [comment]
Please see here for more info: https://www1.qt.io/qt-licensing-terms/
