### ISSUE TITLE
Attachments stored in invalid temp location in Snap

### ISSUE THREAD

**Issue by tlnagy** [keepassxreboot/keepassxc#2283]
Snap version of `keepassxc 2.3.4` fails to open text file attachment. I can open this same text file attachment on macOS with `keepassxc 2.3.4`

## Expected Behavior

Should open text file in a separate program

## Current Behavior

All I get is an error message:

![screenshot from 2018-09-11 12-35-20](https://user-images.githubusercontent.com/1661487/45383145-30fbf600-b5bf-11e8-9ec4-9d4286b86440.png)

## Steps to Reproduce (for bugs)

1. Install keepassxc via snap
2. Attach a simple text file via add attachment
3. Open same text file

## Context

This feature is important for recovery codes

## Debug Info
KeePassXC - Version 2.3.4
Revision: 2cc52a8
Distribution: Snap

Libraries:
- Qt 5.9.5
- libgcrypt 1.8.1

Operating system: Ubuntu Core 18
CPU architecture: x86_64
Kernel: linux 4.15.0-33-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by droidmonkey** [comment]
I store recovery codes in notes. You can also use the attributes. But for the problem at hand, you have to connect the dbus interface to KeepassXC manually. ```sudo snap connect keepassxc:dbus core:dbus```

I believe there may also be an issue with where the temporary file is stored. I can't remember if that is a flatpak issue though.

**Comment by tlnagy** [comment]
```
~ ➜ sudo snap connect keepassxc:dbus core:dbus
error: snap "keepassxc" has no plug named "dbus"
```

It's just that generally recovery codes are offered as downloadable files so it can be nice to just attach that file instead of copying over into notes.

**Comment by droidmonkey** [comment]
Looks like the core18 companion snap has not added the xdg-open command to the "stable" branch yet. If you issue the following command this will update the core18 to the latest available version which includes xdg-open: ```sudo snap refresh --edge core18```

Unfortunately, this DOES NOT fix the attachments issue since the temporary file is indeed stored in an invalid location. Needs fixing in code.
