### ISSUE TITLE
Challenge-Response Authentication without Yubikey

### ISSUE THREAD

**Issue by gynet** [keepassxreboot/keepassxc#2287]
Hello, 

Thanks for adding the support with Yubikey. 

I am a super suspicious guy, I wonder what if my Yubikey is broken and the company is bankrupt, and I only have my key file copy, is there a way to unlock my db?  

Just curious, is it possible to have a challenge-Response authentication implementation without Yubikey,  input the response by manual? I just dont like the way to put eggs in one basket. 

Thanks,
gynet

**Comment by droidmonkey** [comment]
Please see https://github.com/keepassxreboot/keepassxc/issues/1734#issuecomment-416029033
