### ISSUE TITLE
Multiple (proliferation of )process

### ISSUE THREAD

**Issue by Dunkh4n** [keepassxreboot/keepassxc#2289]
Hi,

Every now and then, i look up my proccess just for the sake of it.
And every time it's been a while since my last complete reboot, i found a lot of cmd.exe with conhost.exe and keepassxc-proxy.exe as a child.. and i mean a lot, like 10 or more of it.
And i  have to terminate every one of them manually.. 
So, i was wondering if it's normal??

## Steps to Reproduce (for bugs)
1. just let your pc hibernate instead of complete shut off

## Debug Info

KeePassXC - 2.3.3
Revision: 0a155d8

Libraries:
- Qt 5.10.1
- libgcrypt 1.8.2

Operating system: Windows 10 (10.0)
CPU architecture: x86_64
Kernel: winnt 10.0.17134

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

https://imgur.com/a/3DmmI0P

**Comment by droidmonkey** [comment]
This was fixed in 2.3.4, please update
