### ISSUE TITLE
Debug build fails with clang++

### ISSUE THREAD

**Issue by brainplot** [keepassxreboot/keepassxc#2290]
I have one question.
I initially tried to pull off a `Debug` build using `clang++`, but it fails. I get the following error:
```cpp
/home/gianluca/pull-request/keepassxc/src/browser/BrowserService.cpp:572:57: error: 
      lambda capture 'priorities' is not used [-Werror,-Wunused-lambda-capture]
            std::sort(entries.begin(), entries.end(), [&priorities, &fie...
                                                        ^
1 error generated.
make[2]: *** [src/browser/CMakeFiles/keepassxcbrowser.dir/build.make:128: src/browser/CMakeFiles/keepassxcbrowser.dir/BrowserService.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:456: src/browser/CMakeFiles/keepassxcbrowser.dir/all] Error 2
make: *** [Makefile:141: all] Error
```
The same thing does not occur with a `Release` or `RelWithDebInfo` build, and doesn't occur at all if I compile the code using `g++`. Now, I'm not very familiar with the code base but an obvious solution to me would be to wrap `priorities` with the `Q_UNUSED()` macro. I tried that and indeed the code compiles just fine. Is there any reason why that change hasn't been made so far?

**Comment by droidmonkey** [comment]
I fixed this in my latest PR.
