### ISSUE TITLE
URL matching seems to be partially broken since v2.3.4

### ISSUE THREAD

**Issue by eugenesan** [keepassxreboot/keepassxc#2291]
Starting with version 2.3.4, URL matching fails in several cases where it was working fine for years.

Examples:
1. Entry with address 'aol.com' now doesn't match 'https://www.aol.com' in the browser.
2. Entry with address 'http://aol.com' now doesn't match 'https://www.aol.com' in the browser (URL matching is disabled in settings.

I would like to see the previous behavior restored, where:
1. URL scheme in the entry was optional
2. Subdomains were omittable and matching was based on shortest match

For years, I was storing addresses without URL scheme and subdomains.
Entry with address: "aol.com" would match addresses as:
1. http://www.aol.com
2. https://auth-1234.aol.com/user_1234.cgi
3. https://auth-1234.www.aol.com/cgi/user.cgi

The issue manifests itself using "Browser Integration" plugin connected to Chrome with KeePassXC-Browser v1.2.0.

Enviroment details:
KeePassXC - Version 2.3.4
Revision: 6fe821c

Libraries:
- Qt 5.5.1
- libgcrypt 1.8.1

Operating system: Ubuntu 16.04.5 LTS
CPU architecture: x86_64
Kernel: linux 4.15.0-34-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by droidmonkey** [comment]
Issue introduced with 2.3.4 and fixed by #2253
