### ISSUE TITLE
[Bug] On Linux database can't be accessed when on a memstick

### ISSUE THREAD

**Issue by thgreve** [keepassxreboot/keepassxc#2293]
A database located on a usb-memstick (the stick being correctly mounted and the file being accessible via Nautilus/Files under /media/CURRENT_USER/NAME_OF_VOLUME/xxx.kdbx) can not be opened with keepassxc under Linux (under Win7 it works).
Procedure:
Selecting menu Database|Open database ...
In the dialog 'Open database' navigating to /media
Then no further content (i.e. CURRENT_USER) is shown.

Debug Info

KeePassXC - Version 2.3.4
Revision: 2cc52a8
Distribution: Snap

Libraries:

    Qt 5.9.5
    libgcrypt 1.8.1

Operating system: Ubuntu Core 18
CPU architecture: x86_64
Kernel: linux 4.15.0-34-generic

Enabled extensions:

    Auto-Type
    Browser Integration
    Legacy Browser Integration (KeePassHTTP)
    SSH Agent
    YubiKey

**Comment by droidmonkey** [comment]
You need to explicitly type the path in. This is a known snap bug/issue.

**Comment by Lin-Buo-Ren** [comment]
I can properly access `/media/CURRENT_USER/NAME_OF_VOLUME`, is the snap connected to the `removable-media` interface?

![default](https://user-images.githubusercontent.com/13408130/47031052-abf99300-d1a1-11e8-939b-71d1c15a7c95.png)

Refer the following topic for more info: [Interface management - doc - snapcraft.io](https://forum.snapcraft.io/t/interface-management/6154)
