### ISSUE TITLE
Steam TOTP isn't written

### ISSUE THREAD

**Issue by rderensy** [keepassxreboot/keepassxc#2296]
When you use {TOTP} is the Steam auto-type sequence, it only writes login and password but the TOTP code is never written (probably because it includes letter?).

## Debug Info

    KeePassXC - Version 2.3.3
    Revision: 0a155d8
    
    Libraries:
    - Qt 5.10.1
    - libgcrypt 1.8.2
    
    Operating system: Windows 10 (10.0)
    CPU architecture: x86_64
    Kernel: winnt 10.0.14393
    
    Enabled extensions:
    - Auto-Type
    - Browser Integration
    - Legacy Browser Integration (KeePassHTTP)
    - SSH Agent
    - YubiKey

**Comment by droidmonkey** [comment]
Post your full AutoType sequence please

**Comment by rderensy** [comment]
{USERNAME}{TAB}{DELAY 50}{PASSWORD}{ENTER}{DELAY 2000}{TOTP}{ENTER}

Note that the "DELAY 50" is because it writes the first letter of the password before pressing "TAB"

**Comment by droidmonkey** [comment]
And the field is focused when you get to it? There are a lot of things that can go wrong with this setup. Also, I believe the steam login window and the TOTP window are totally different. This would break the AutoType sequence.

**Comment by rderensy** [comment]
Yes the field is focused but this is indeed a different window, I didn't know that broke the auto-type sequence

**Comment by droidmonkey** [comment]
You can create a second AutoType sequence for that TOTP window and just press the hotkey again. There is no other way around this.

**Comment by weslly** [comment]
@rderensy Can you try adding `{DELAY=70}` to the start of the autotype sequence?

**Comment by GUiHKX** [comment]
@weslly I'm not the OP, but I have the same problem and adding that did nothing for me. Like @droidmonkey said, the [auto-type sequence stops](https://github.com/keepassxreboot/keepassxc/blob/2.3.4/src/autotype/AutoType.cpp#L232-L236) once the Steam Guard window pops up and steals the focus from the Steam Login window.

KeePass has two options to better control such behavior:

![image](https://user-images.githubusercontent.com/626206/45820386-08f64c00-bcbd-11e8-97ce-f13c6082a31d.png)

I personally dislike having both options enabled, but I see how annoying it can be in some cases. I think having both options in KPXC would be awesome. Or, KXPC could have an option which would check if the current window title it's still in the window's list of an entry. If it's not, only then the auto-type sequence is cancelled. 

Having an option like that would fix this behavior and would only require adding both Steam Login and Steam Guard windows to the window's list, [like so](https://i.imgur.com/xXrKKnQ.png). (By the way, KeePass itself doesn't behave like this, so I have to keep both options disabled for Steam TOTP auto-typing to work.)

**Comment by droidmonkey** [comment]
I do not support the inclusion of those options, they create way more problems than solve. Just create two AutoType sequences. We have an open issue to create a global key shortcut that types the totp.

**Comment by TheZ3ro** [comment]
> KXPC could have an option which would check if the current window title it's still in the window's list of an entry. If it's not, only then the auto-type sequence is cancelled.

This seems a nice addition, maybe for the wishlist
