### ISSUE TITLE
[snap] symbol lookup error on Debian 9

### ISSUE THREAD

**Issue by Serenity597** [keepassxreboot/keepassxc#2298]
**## Expected Behavior**
I have freshly installed Debian 9,5 with last proposed and security updates (4.9.110-3+deb9u4). App should launch and work after installing it via snap.

**## Current Behavior**
when run $ keepassxc getting error:
keepassxc: symbol lookup error: /snap/keepassxc/49/usr/lib/x86_64-linux-gnu/libGL.so.1: undefined symbol: _glapi_tls_Current
## Possible Solution
Update library (?) or maybe fix symlink (?)

**## Steps to Reproduce**
1. Fresh installation from net iso, with added proposed and security updates
2. Proprietary nvidia drivers
3. X11
3. Installing snapd
4. installing keepassxc

**## Debug Info**
KeePassXC - 2.3.4 snap version
Revision: Last

Libraries:
libGL.so.1

Operating system: GNU/Linux Debian 4.9.110-3+deb9u4
CPU architecture: amd64
Kernel: 4.9.0.8

**Comment by droidmonkey** [comment]
This does not occur on Ubuntu and the file is certainly deployed with the snap itself. I suspect the snapd installation is at fault. This is probably just the first library that is attempted to be loaded and it fails.

**Comment by Serenity597** [comment]
Hi, yes you right, looks like some Qt based apps not working at all, some working with errors, but apps on electron, C++, and java just works fine..

**Comment by droidmonkey** [comment]
I saw some thread about Nvidia drivers messing up snap directory searching. Might be a common link there. Can you run using strace to see where it's looking for libraries?

**Comment by Serenity597** [comment]
Sorry, don't know where to find it, so uploaded to pastebin whole output: 
https://pastebin.com/dT24npgw

**Comment by Serenity597** [comment]
Can confirm bug with nvidia driver version 184.130, will report it to package maintainers, thanks for help.
Temporary solution: rollback to 184.111 or install 390.77 from backports.

**Comment by droidmonkey** [comment]
Cool, glad you found it
