### ISSUE TITLE
Display message when Autosave successfully completes

### ISSUE THREAD

**Issue by LucaMoschella** [keepassxreboot/keepassxc#2302]
## Expected Behavior
I'd like to have a feedback on the autosave feature.

Some ideas for a possible feedback:
- A message at the bottom of the window with the current status "Saved/Modifying" or similar.
- Changing the icon of the save button according to the status
- The save button is not grayed out, when clicked it displays a message "The database is up to date. Autosave feature on."

## Current Behavior
It silently saves the changes, without any option to know if the operation has been successful

**Comment by droidmonkey** [comment]
Not a bad idea!

**Comment by LucaMoschella** [comment]
Nice! Glad that you like it.

I particularly like the idea to change the icons, since it isn't intrusive.
I did some sketches with this template: https://game-icons.net/delapouite/originals/save.html

When the database is not up to date:
![save](https://user-images.githubusercontent.com/11019190/45695978-d59faa00-bb62-11e8-8f37-7b447356d237.png)

When it is up to date:
![save 1](https://user-images.githubusercontent.com/11019190/45695986-d89a9a80-bb62-11e8-97b4-fad02e8b23bb.png)

**Comment by wolframroesler** [comment]
Don't like it. Auto-save is something that I expect to just work. I don't care when it saves, I don't care if it saved successfully, I just want to know if saving failed and that's it. Being "set it and forget it" is what auto-save is all about.

**Comment by droidmonkey** [comment]
I agree 100% with your assessment. We will not be implementing this request.
