### ISSUE TITLE
URL Column Not Displaying ssh:// URLs

### ISSUE THREAD

**Issue by suwalski** [keepassxreboot/keepassxc#2303]
I have many URLs in my database in the format "ssh://user@172.16.5.5".

This isn't displaying correctly in the URL column on the main window. Shows up completely blank. It does display correctly in the details pane. Copying and visiting the URL also work.

## Debug Info
KeePassXC - Version 2.3.1
Revision: 2fcaeea

Libraries:
- Qt 5.9.5
- libgcrypt 1.8.1

Operating system: Ubuntu 18.04.1 LTS
CPU architecture: x86_64
Kernel: linux 4.15.0-34-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by droidmonkey** [comment]
This is fixed by #1489 which will be in v2.4
