### ISSUE TITLE
file:// URLs not opening with Cmd-U

### ISSUE THREAD

**Issue by pmhausen** [keepassxreboot/keepassxc#2304]
## Expected Behavior

If an entry contains a URL of the sort file://, then Cmd-U should open the local file with the default program registered with Mac OS for that particular file type.

## Current Behavior

Nothing seems to happen.

## Possible Solution

Sorry, but I don't have the slightest idea. This stopped working when I moved from my old Macbook Pro to a new one including an upgrade from Mac OS Sierra to High Sierra.

## Steps to Reproduce (for bugs)

1. Get a Mac with High Sierra installed.
2. Install KeePassXC 2.3.4
3. Create an entry like this: Title: Test, URL: file:///Users/pmh/Desktop/Test.txt - replace "pmh" with your user name. Create a text file named "Test.txt" on your desktop.
4. Highlight the entry, type Cmd-U

## Context

This is important for our team workflow. We have a central Nextcloud shared repository of .kdbx files. The passwords to these files every operator puts into his own personal keepass. To open a particular file, the established way is:
- unlock personal keepass
- select file
- Cmd-C, Cmd-U, Cmd-V, Enter

## Debug Info

KeePassXC - Version 2.3.4
Revision: 6fe821c

Bibliotheken:
- Qt 5.9.3
- libgcrypt 1.8.2

Betriebssystem: macOS High Sierra (10.13)
CPU-Architektur: x86_64
Kernel: darwin 17.7.0

Aktivierte Erweiterungen:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by varjolintu** [comment]
I can definitely reproduce it. Needs some debugging.
