### ISSUE TITLE
Feature: Functions for improving usability

### ISSUE THREAD

**Issue by MAPIIIAJI** [keepassxreboot/keepassxc#2306]
Hi everybody! First of all I want to express my gratitude for your product!
I'm using the version: 2.3.1
I would like to see the following functions:
1. Ability to sort folders, sub-folder and content records (by several criteria: by creation date, alphabet, by expiration date, etc.);
2. Copying packages and including the contents of folders and I would like to have all the settings that were used to create the records (including the settings of the generated passwords) were copied;
3. When cloning the record, to copy all the properties of the original record, including the characteristics of the generated password of the original record. What is meant? It means that if in the settings of the KeePassXC password was specified in the settings of the password generator: 10 characters (numbers + letters) and if the record was generated by specifying a password of 48 characters (letters, numbers, symbols) and if to clone the record, all characteristics of the password are taken from the settings of KeePassXC (10 characters (numbers + letters)), and not those that were used to generate the original password (48 characters (letters, numbers, symbols)). This is not convenient when you have a group of passwords with a certain password policy and at the same time records that are cloned have the same characteristics, at least I would like to see the inheritance of the characteristics of the original record (password). Therefore the question arises: Why not change the general settings of the password generator? Answer: If you have several password policies that will be divided into different folder groups (each with its own password policy), in such cases, it will be inconvenient to change the general settings of the password generator each time.
Thanks in advance.

Regards,
Jamshid

**Comment by droidmonkey** [comment]
1 - captured by #69 

2 - I do not understand what you mean by this one

3 - discussion captured by #2180

**Comment by MAPIIIAJI** [comment]
Ok, no problem!
