### ISSUE TITLE
Using a Keyfile on a token

### ISSUE THREAD

**Issue by starsoccer** [keepassxreboot/keepassxc#2308]
## Expected Behavior
Keypassxc should detect token file and prompt for token pin/password if applicable and then to select a keyfile.

## Current Behavior
Browse button is shown and you can only select a key file from a physical location not from a token.

## Possible Solution
Add a way to browse to a token and select a key file from said token.

**Comment by droidmonkey** [comment]
What do you mean by this? We support Yubikey hardware tokens using HMAC-SHA1

**Comment by starsoccer** [comment]
Sorry for the confusion, I mean in a similar why as truecrypt or veracrypt. "VeraCrypt can directly use keyfiles stored on a security token or smart card that complies with the PKCS #11 (2.0 or later) standard [23] and that allows the user to store a file (data object) on the token/card". Basically using veracrypt you can create a key file like keepassxc.

So basically I am requesting a way to use a keyfile that is stored on a security token or smart card as the key file to unlock a database.

Let me know if its still not clear what I mean.

**Comment by droidmonkey** [comment]
Ah yes, we already have an issue for PKCS#11 support

**Comment by starsoccer** [comment]
Okay thanks, I didn't realize thats what its called, The issue can be found here, https://github.com/keepassxreboot/keepassxc/issues/255, so I will close this.
