### ISSUE TITLE
Feature request: Do not show dots instead of the password when there is none.

### ISSUE THREAD

**Issue by jlemonde** [keepassxreboot/keepassxc#2310]
I sometimes use KeePassXC in order to store some ID numbers which do not have any password. In this case, it is kind of perturbing to see big dots at the place where there would be a password. I know it is possible to have an "empty" password in some places, so this feature should only be an option. But it could be a useful enhancement. Thanks!

**Comment by Jakob900** [comment]
Noticed this too  I use it to store a lot of contacts of just names and info in the notes section, and it would be nice to not have dots for the password field
