### ISSUE TITLE
KeePassXC does not detect file change in gocryptfs on Linux

### ISSUE THREAD

**Issue by NiceGuyIT** [keepassxreboot/keepassxc#2312]
I use [gocryptfs](https://github.com/rfjakob/gocryptfs) to encrypt directories and then sync them with [Syncthing](https://github.com/syncthing/syncthing). All three programs, KeePassXC, Syncthing and gocryptfs are cross platform and work on Linux, Mac and Windows. I primarily use Linux and that's what this bug report is for. Linux doesn't detect the database file changed when synced from other systems.

## Expected Behavior

If another system updates the database and syncs the database file to Linux, I expect KeePassXC to detect the change and reload the database per the "Automatically reload the database when modified externally" setting.

## Current Behavior

When the database is updated from another system and synced to Linux, KeePassXC doesn't detect the change.

## Possible Solution

Touching the file is sufficient for KeePassXC to notice the file change. gocryptfs uses go-fuse and perhaps go-fuse doesn't report the file change sufficiently for KeePassXC.

## Steps to Reproduce (for bugs)

1. Install [gocryptfs](https://github.com/rfjakob/gocryptfs).
2. Init a folder and mount the plain view with gocryptfs.
3. Install [Syncthing](https://github.com/syncthing/syncthing).
4. Sync the encrypted folder between multiple Linux systems.
5. Modify an entry in one system. It doesn't update in the other system.
6. Touch the file and watch the database update.

## Context

Not having this work as expected means possible data loss. Syncthing sees only encrypted data and thus always syncs the encrypted file. While Syncthing does detect file conflicts, I have noticed one or twice where an entry wasn't changed when I thought I changed it (on another system).

## Debug Info

KeePassXC - Version 2.3.4
Revision: 6fe821c

Libraries:
- Qt 5.9.4
- libgcrypt 1.8.2

Operating system: openSUSE Leap 15.0
CPU architecture: x86_64
Kernel: linux 4.12.14-lp150.12.16-default

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

gocryptfs:
gocryptfs v1.5; go-fuse v20170619-40-g291273c; 2018-07-12 go1.10.3

## Notes
I see gocryptfs has a new release. It may take a day or two before I can create a new build and test.

openSUSE Leap 15.0 has KeePassXC 2.3.3 but I know all bug reports need the latest version. The source RPM was downloaded from [openSUSE](https://software.opensuse.org/package/keepassxc) and while the tgz is the same as the one hosted on GitHub, some additional patches were included. The version above is the source compiled into an RPM and installed using Zypper. I should be able to build from master or other branches if needed for testing.

**Comment by droidmonkey** [comment]
Likely duplicate of #1799

**Comment by NiceGuyIT** [comment]
Thanks for the hint. That's the likely cause. The corresponding issue is rfjakob/gocryptfs#215 which links to a good read about [Fsnotify and FUSE](https://github.com/libfuse/libfuse/wiki/Fsnotify-and-FUSE).

> The only benefit is for channel tunneling

My benefit is keeping all my documents together. Moving the KeePassXC database outside of gocryptfs means creating another Syncthing directory. I didn't have a reason until now: data integrity. I confirmed that KeePassXC does not check if the file was modified _before_ writing the database, thus wiping out changes that were synced from other devices. The "regular checking" solution in #1799 will fix this.

I'm closing this since I now understand the root cause. Thanks for the help.

**Comment by droidmonkey** [comment]
I believe there is another issue to implement MD5 or similar hashing of the file itself to detect changes just before save.
