### ISSUE TITLE
Last file picker location is not getting reset if you don't close the program

### ISSUE THREAD

**Issue by ghost** [keepassxreboot/keepassxc#2314]
File picker shouldn't remember the last folder you visited after importing a key file

## Expected Behavior
When **Remember last key files and security dongles** is **disabled**, the file picker shouldn't remember the last folder you visited after importing a key file. The last position is only cleared if you close the program.

## Current Behavior
The ~~north~~ file picker remembers.

## Steps to Reproduce (for bugs)
1. Disable **Remember last key files and security dongles**
2. Unlock your database using a key file
3. Close your database (do not close the program)
4. Select a Key File by clicking on Browse
5. File picker is in the same directory you previously selected your last key file

## Debug Info
KeePassXC - Version 2.3.4
Revision: 6fe821c

Libraries:
- Qt 5.11.1
- libgcrypt 1.8.3

Operating system: Windows 10 (10.0)
CPU architecture: x86_64
Kernel: winnt 10.0.17134

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by kneitinger** [comment]
On the build I'm using, it not only remembers the directory, but before even going into the file selection window via browse, the full path to the keyfile is already populated, just with the checkbox unchecked.

KeePassXC - Version 2.4.0-snapshot
Build Type: Snapshot
Revision: 2653250

Libraries:
- Qt 5.11.2
- libgcrypt 1.8.3

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 4.18.12-arch1-1-ARCH

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- YubiKey
