### ISSUE TITLE
Appimage doesn't run inside firejail

### ISSUE THREAD

**Issue by jayma777** [keepassxreboot/keepassxc#2315]
## Expected Behavior
Ummm...   Run?

## Current Behavior
KeePassXC appimage dies with libsodium error.

$: ./KeePassXC-2.3.4-x86_64.AppImage 
Reading profile /etc/firejail/default.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-passwdmgr.inc
Reading profile /etc/firejail/disable-programs.inc

Note: you can use --noprofile to disable default.profile 

Parent pid 10862, child pid 10901
Warning: cleaning all supplementary groups
Child process initialized in 56.28 ms
**keepassxc: error while loading shared libraries: libsodium.so.23: cannot open shared object file: No such file or directory**

Parent is shutting down, bye...

## Steps to Reproduce (for bugs)
1.  Download AppImage from https://github.com/keepassxreboot/keepassxc/releases/download/2.3.4/KeePassXC-2.3.4-x86_64.AppImage
2.  Attempt to run App

## Context
*May be* relevant 
I'm running inside firejail. 
Removed Integrated appimage, installed from PPA, and it's now working.  Just reporting the missing lib as something to look into.

## Debug Info

KeePassXC - KeePassXC-2.3.4-x86_64.AppImage 
Revision: REVISION

Operating system: LinuxMint 18
CPU architecture: x86_64
Kernel:  4.13.0-43-generic

**Comment by droidmonkey** [comment]
libsodium.so.23 is certainly inside the appimage. You can check yourself if you add ".zip" to the end and open it up. Go to ```/usr/lib/x86_64-linux-gnu/``` within the zip file. The appimage runs perfectly fine on Ubuntu 18.04, no jail.

**Comment by droidmonkey** [comment]
OK, I installed firejail, read the instructions, and used the following command to run the KeePassXC appimage:

```firejail --appimage ~/KeePassXC-2.3.4-x86_64.AppImage```
