### ISSUE TITLE
Custom icons duplicated

### ISSUE THREAD

**Issue by louib** [keepassxreboot/keepassxc#232]
Custom icons for the same website are added multiple times.

## Expected Behavior
We should at least try to detect duplicates and not fetch the icon multiple times for the same website.

## Current Behavior
Custom icons for the same website are added multiple times.

![screen shot 2017-01-27 at 1 09 20 pm](https://cloud.githubusercontent.com/assets/3301383/22382006/dbec0be6-e491-11e6-93ca-03ba2fb06c70.png)

## Steps to Reproduce (for bugs)

1. Add entry with a website
2. Click `Download favicon` multiple times.

## Context
I was trying to reproduce https://github.com/keepassxreboot/keepassxc/issues/225

## Your Environment
* KeePassXC version/commit used: 6409661a9f164cf32a46c5cfc2bf877b97e23512
* Qt version: Qt 5.7.1 
* Operating System and version: MacOS 10.11.16

**Comment by droidmonkey** [comment]
Would you match the base url only? Some sites have different icons for sub domains.

**Comment by louib** [comment]
@droidmonkey this and making sure clicking multiple times `download` from within the window just fetches the icon 1 time.

**Comment by paolostivanin** [comment]
Maybe by comparing the checksum? I don't know if it is always the same.\
could be worth a try though :)

**Comment by droidmonkey** [comment]
That's a good idea although it would be best to precalculate and store the checksum/hash in the db somehow.

**Comment by paolostivanin** [comment]
Something like an hash table maybe?
```
{ 
   google.com:
      { icon: favicon.ico,
        cks: checksum
      },
   gmail.google.com:
      { icon: favicon.ico,
        cks: checksum
      },
}
```

**Comment by phoerious** [comment]
Why not use the icons themselves as keys? We could use a QHash map and
provide a qHash() implementation for icon data.

**Comment by paolostivanin** [comment]
Yep, good idea!
