### ISSUE TITLE
Improve the interface

### ISSUE THREAD

**Issue by tiotrom** [keepassxreboot/keepassxc#2321]
I would really love to see KeePassXC with a modern new look. Now it is super cluttered. We need a simple way of click and entry and copy password of username without right click and select that from a menu. And more intuitive icons and stuff like that. Look at https://keeweb.info/ - they have a great minimalist interface. 

Thank you for your work! And I hope to see KeePassXC in the future with a new interface. I am a webdesigner so if you wish I can create a design for you and you could implement it.

**Comment by droidmonkey** [comment]
thanks for dropping by, unfortunately our application is not meant to be minimal like KeeWeb. Also, you can easily copy attributes from the main view by double clicking them. For example,

**Comment by tiotrom** [comment]
I understand, thanks. I didn't know you can double click to copy username and password. That's very useful!
