### ISSUE TITLE
feature-request: More Export Possibilites

### ISSUE THREAD

**Issue by Gomez1111** [keepassxreboot/keepassxc#2324]
## Expected Behavior

Export Features: 
- Possibility to export trees to a new safe with a new password
- Possibilty to export the safe to other formats

## Current Behavior

- Trees couldn't be exported
- Only export to csv is possible

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Debug Info

KeePassXC - Version 2.3.4
Revision: 6fe821c

Bibliotheken:
- Qt 5.11.1
- libgcrypt 1.8.3

Betriebssystem: Windows 7 SP 1 (6.1)
CPU-Architektur: x86_64
Kernel: winnt 6.1.7601

Aktivierte Erweiterungen:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by droidmonkey** [comment]
Covered under #1940
