### ISSUE TITLE
Inconsistent naming in settings: "preview panel"/"details view"

### ISSUE THREAD

**Issue by kneitinger** [keepassxreboot/keepassxc#2327]
## Expected Behavior
The entry overview, beneath a database's entries in the main view should be named consistently throughout the application.

## Current Behavior
In `Tools->Settings->General->Entry Management`, this component is referred to as the "Details view".
In `Tools->Settings->General->Security->Convenience` this component is referred to as the "preview panel".  

## Possible Solution
One convention is chosen and used in both contexts, as well as any others I may have missed. I feel as though "entry details panel" and "entry preview panel" are both clear.

## Context
When I saw the "Hide the Details view" option in the Application Settings window, I was unsure what it did until I checked it, applied the settings, and left the settings menu.  This is mostly because I knew  the component in question as the "preview panel" from the "Hide passwords in the preview panel" option

## Debug Info

KeePassXC - Version 2.3.4
Revision: 6fe821c

Libraries:
- Qt 5.11.2
- libgcrypt 1.8.3

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 4.18.9-arch1-1-ARCH

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

(note: present in `develop` branch as well)

**Comment by droidmonkey** [comment]
Perhaps even "Entry Preview"

**Comment by TheZ3ro** [comment]
I will cast my vote for "preview panel" instead of "details view"

**Comment by kneitinger** [comment]
Are there any precautions around changing config file setting names?

It sounds like we're all in agreement over 'preview' being more clear that 'details', but the corresponding settings in the INI config both use 'details': `GUI/HideDetailsView` and `security/hidepassworddetails`.

Changing these would mean that the old values for these settings would not be read and the default value would be used.  Furthermore, I haven't had a chance to look at the code for writing out the config, or experiment with this behavior, but do old entries need to be manually removed?  As in, when the config is written, does it clear the file and write the current settings to the file, or does it change only modified settings?

**Comment by phoerious** [comment]
I believe it writes the whole file. Seeking to the positions and updating values doesn't work well, especially if the new values are longer or shorter.
But there is no reason to change the config directives. This is purely a UI issue and the backend code needn't be changed.
