### ISSUE TITLE
Unable to use auto-type to login into a few popular websites

### ISSUE THREAD

**Issue by sivaraam** [keepassxreboot/keepassxc#2330]
When I try to Auto-type using a shortcut, it works on some websites and it doesn't seem to work on others. To clarify, this doesn't seem to be a problem with the website itself. The username and password fields do get filled but I get an incorrect username/password combination error in most cases. When I manually copy and paste the username/password, I'm able to log-in. This happens in a few sites including but not limited to:
* [GitHub](https://github.com/)
* [GitLab](https://gitlab.com/)
* [Mozilla Bugzilla](https://bugzilla.mozilla.org/)
* [Ubuntu One](https://login.ubuntu.com/+login)

I'm a little uncomfortable with copying and pasting the login credentials.

## Expected Behavior
I'm able to log-in using Auto-type without having to copy and paste the credentials.

## Current Behavior
Using Auto-type to login seems to provide the incorrect credentials to the website in some way. I have to copy and paste the credentials to log-inn

## Steps to Reproduce (for bugs)
1. Visit [GitHub](https://github.com/) (ensure you're logged-out)
2. Tap on Sign-in
3. Use auto-type to enter the credentials

## Context
I'm trying to log-in using Auto-type.

## Debug Info
KeePassXC - Version 2.3.4
Revision: 6fe821c

Libraries:
- Qt 5.11.1
- libgcrypt 1.8.3

Operating system: Debian GNU/Linux buster/sid
CPU architecture: x86_64
Kernel: linux 4.17.0-3-amd64

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

Libraries:
- LIBS

Operating system: OS
CPU architecture: ARCH
Kernel: KERNEL

Enabled extensions:
- EXTENSIONS

**Comment by droidmonkey** [comment]
Have you tried using our browser plugin? AutoType is sketchy at best for websites.

**Comment by sivaraam** [comment]
> Have you tried using our browser plugin? AutoType is sketchy at best for websites.

I just tried it. It seems to be working correctly. Thanks for the pointer.
