### ISSUE TITLE
Feature: clear master password as part of automatic database lock process

### ISSUE THREAD

**Issue by nathansgreen** [keepassxreboot/keepassxc#2335]
I would like the master password field to be cleared when my session is locked or lid is closed or when the inactivity timeout is reached.

## Expected Behavior
I use the automatic database lock features to prevent disclosure of sensitive information. My master passwords are also sensitive information, but are not protected by the same features. The master passwords for all databases should be cleared as part of the automatic database lock process.

## Current Behavior
If the database is already opened, the password field will be blank when the session is unlocked, which is correct. But, I can enable showing the master password as clear text and put in my password and it remains visible across any session lock and unlock states. This happens for all databases. Even if the password is not shown as clear text, it remains entered in after the session is locked. Likewise, the password remains entered if databases are locked after minimizing the window.

## Possible Solution
Just iterate through the open database tabs and clear the password field during the automatic lock process.

## Steps to Reproduce (for bugs)

1. Enable the feature "Lock databases when session is locked or lid is closed."
2. Open a database.
3. Start entering a password.
4. Lock the session.
5. Unlock the session.
6. Observe the unchanged password value that was entered in step 3.

## Context
My work keeps me somewhat mobile and my laptop screen is often visible to others. I rely on automated processes to protect sensitive information. I'm also periodically interrupted when working with sensitive information. This is a case where I can run into trouble because I have been interrupted when entering master passwords. The current features do not fully protect the master password.

## Debug Info
KeePassXC - Version 2.3.4
Revision: 6fe821c

Libraries:
- Qt 5.9.3
- libgcrypt 1.8.2

Operating system: macOS High Sierra (10.13)
CPU architecture: x86_64
Kernel: darwin 17.7.0

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by droidmonkey** [comment]
Technically your database is already locked. What you really want is some form of timeout that automatically clears the unlock dialog. Also when the laptop lid or sleep is triggered. Would using the same timeout as the database lock work?

**Comment by nathansgreen** [comment]
If the database lock timeout is enabled, yes, I would expect it to reset the contents of the unlock dialog. But I don't use the lock timeout personally because I frequently lock and unlock my machine, and so I just rely on the automatic lock feature.

From what I can tell, the existing code just skips over any databases that are locked as it loops through the open database tabs. Adding an additional step in that loop to reset the unlock dialog doesn't seem like it would be too difficult. I would assume other unlock settings like remembering key files would also apply.

**Comment by TheZ3ro** [comment]
Locking a database should also reset the unlock dialog.

Locking by timeout [1] and locking by screenlock [2] both use the same function `MainWindow::lockDatabasesAfterInactivity()` that cycle all TabWidget databases and locks them.
Locking a TabWidget should reset the unlock dialog.

I think this is a bug in the TabWidget locking mechanism



----
**[1]** This line describes the behaviour for the timeout-locking https://github.com/keepassxreboot/keepassxc/blob/44c9469221400e396bbf51b30913f138ddbb5cb3/src/gui/MainWindow.cpp#L182

**[2]** This lines describes the behaviour for the screen-locking 
https://github.com/keepassxreboot/keepassxc/blob/44c9469221400e396bbf51b30913f138ddbb5cb3/src/gui/MainWindow.cpp#L332-L333
https://github.com/keepassxreboot/keepassxc/blob/44c9469221400e396bbf51b30913f138ddbb5cb3/src/gui/MainWindow.cpp#L1018-L1022

**Comment by nathansgreen** [comment]
It looks to me as though `lockDatabasesAfterInactivity` just delegates to `DatabaseTabWidget::lockDatabases()`, which skips over locked tabs:
```cpp
    for (int i = 0; i < count(); i++) {
        DatabaseWidget* dbWidget = static_cast<DatabaseWidget*>(widget(i));
        Database* db = databaseFromDatabaseWidget(dbWidget);

        if (dbWidget->currentMode() == DatabaseWidget::LockedMode || !dbWidget->dbHasKey()) {
            continue;
        }
```
