### ISSUE TITLE
Feature Request - Dark Theme

### ISSUE THREAD

**Issue by Mascall** [keepassxreboot/keepassxc#2338]
Hi sorry if this is in the wrong section, first time using GitHub and im sure this may have been asked previously...

I would like to request a Dark Theme option if possible for the Windows version of KeePassXC

Thanks

**Comment by tromlet** [comment]
Given that Mac OS X 10.14's magnum opus feature was, in fact, a dark theme... I would second this. It would be nice to see a nice dark theme for all platforms.

**Comment by droidmonkey** [comment]
Duplicate of #804. Qt needs to release 10.12 which will support Mojave dark theme...
