### ISSUE TITLE
CLI : import from XML format

### ISSUE THREAD

**Issue by vespian** [keepassxreboot/keepassxc#2341]
The CLI has an export option:
```
$ keepassxc-cli extract
Usage: keepassxc-cli extract [options] database
Extract and print the content of a database.

Options:
  -k, --key-file <path>  Key file of the database.

Arguments:
  database               Path of the database to extract.
```
but no import <!> Once the database is in XML format, I do not see a way to import it back :( What is more, the export option asks for password on STDOUT and prints database on STDOUT as well. This makes redirecting the output difficult.

## Expected Behavior
It would be great if:
* there was an XML import option, both CLI and UI is fine
* the export command had an option to name the file to which the export should be done.

**Comment by Sbgodin** [comment]
An option for a Yubikey would also be nice.

**Comment by louib** [comment]
This was implemented by https://github.com/keepassxreboot/keepassxc/pull/3572
