### ISSUE TITLE
Numpad keys as Auto-Type hotkey doesn't work

### ISSUE THREAD

**Issue by bloodcraw** [keepassxreboot/keepassxc#2350]
Setup **{LeftCtrl} + {LeftAlt} + {Numpad+}** as hotkey for Auto-Type will be mapped to **{LeftCtrl} + {LeftAlt} + {Letterside+}**.
Same for **{Numpad-}** **{Numpad/}** **{Numpad\*}** and possible more.

## Expected Behavior
The pressed key combination during setup should be the same you have to press for the actual use of the feature.

## Current Behavior
Pressing **{LeftCtrl} + {LeftAlt} + {Numpad+}** during setup results in **{LeftCtrl} + {LeftAlt} + {Letterside+}** as actual key combination.

## Possible Solution
Doing some keycode magic.

## Steps to Reproduce (for bugs)

1. open setup for Auto-Type
2. press **{LeftCtrl} {LeftAlt} {Numpad+}** as hotkey combination
3. save settings
4. open another programm e.g. notepad
5. press **{LeftCtrl} {LeftAlt} {Numpad+}**
6. nothing happens
7. press **{LeftCtrl} {LeftAlt} {Letterside+}**
8. expected Auto-Type behavior starts

## Context
I consider to switch from KeepassX to KeepassXC, but my preferred Auto-Type hotkey im used to doesn't work anymore.

## Debug Info

KeePassXC - Version 2.3.4
Revision: 6fe821c

Bibliotheken:
- Qt 5.11.1
- libgcrypt 1.8.3

Betriebssystem: Windows 10 (10.0)
CPU-Architektur: x86_64
Kernel: winnt 10.0.14393

Aktivierte Erweiterungen:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

Keyboard:
 - Model Logitech G19
 - Layout german

**Comment by droidmonkey** [comment]
I did not realize there was a distinction between letterpad and numberpad for the same symbol.

**Comment by droidmonkey** [comment]
Not going to implement these placeholders.
