### ISSUE TITLE
ssh agent: protocol error loading ed_25519 key

### ISSUE THREAD

**Issue by seatedscribe** [keepassxreboot/keepassxc#2354]
## Expected Behavior
1. configure ssh agent to load/unload a ssh-ed25519 key upon lock/unlock
2. after unlocking DB
 - no errors are displayed
 - `ssh-add -l` will display the key info
I'm on Linux, KXC latest snapshot  (see details below)

## Current Behavior
When unlocking I see the red banner on the top saying "Agent protocol error."
(same as when locking, by the way)
No key is loaded by background ssh-agent process

## Steps to Reproduce (for bugs)
1. configure ssh agent to load/unload a ssh-ed25519 key upon lock/unlock
2. unlock DB
3. notice the displayed error in the red banner
4. `ssh-add -l` will not display the key info

## Context
Trying to use ssh agent w/ 25519 keys, under Linux, as I am currently doing under Windows.
I confirm this issue is *not* present on Windows 10.
@hifi 

## Debug Info
KeePassXC - Version 2.4.0-snapshot
Build Type: Snapshot
Revision: 4ff63c2

Libraries:
- Qt 5.5.1
- libgcrypt 1.8.1

Operating system: Linux Mint 18.2
CPU architecture: x86_64
Kernel: linux 4.13.0-36-generic

Enabled extensions:
- Auto-Type
- SSH Agent

**Comment by hifi** [comment]
Are you using the OpenSSH agent on Linux? Where does the environment variable *SSH_AUTH_SOCK* point to?

**Comment by seatedscribe** [comment]
Yes, I use the default OpenSSH version delivered with Mint
`> echo $SSH_AUTH_SOCK`
`/run/user/1000/keyring/ssh`

**Comment by hifi** [comment]
That looks like a GNOME Keyring socket and it does not support ED25519 keys before version 3.27.92 and the version of Mint you have is older than latest.

Disable the SSH Agent feature of GNOME Keyring so that OpenSSH `ssh-agent` takes precedence.

**Comment by seatedscribe** [comment]
Well done, I think you catched the issue! I will try asap, and if I need to further investigate I will comment here. In the meantime I think you can close this.

Thanks!
