### ISSUE TITLE
Support multiple URLs per entry and add "insert reference" button(s)

### ISSUE THREAD

**Issue by notlinustorvalds** [keepassxreboot/keepassxc#2356]
I have elebenty bazillion login credentials to manage.  
...And I've got _at least_ two different browsers open at any one time.  
...And I have to float between computers **ALL 👏 THE 👏 ❕❔✖➗ING 👏 TIME**

**For login credentials,  I _adore_ keepassxc**.  I can thumbdrive it and the above scenario is totally manageable.  But I have two additional realities that make this a bit difficult

1. I've got elebenty bazillion bookmarks to manage.  
...And bookmark syncing _**SUCKS ROCKS**_
1. I have several sites that implement **Single Sign On** (SSO).  

## Proposed Solution
I would love it if keepassxc could give me multiple URL's on Entry page.  Not only could I use keepassxc as my password manager, I could also use it to store bookmarks.

...You know, for the elebenty bazillion sites that we developers and operations people have for reference.

### Current Workaround
I get around this two ways:

1. **I use Advanced > Additional Attributes**.   
  It's OK, but kind of a pain.
2. **I create multiple entries in a group and for Username, enter something like**
    > **"_`SEE FOO > BAR > (SSO)`_"**.
  
    This is also kind of a pain.  

### Suggested UI
Basically, this would involve adding three controls to the UI:

- A [+] button to add a URL
- A [-] button to remove a URL
- A new text field for a URL title.  Every URL has a context; e.g.:
    - Single Sign On for Company Foo
      - `https://webmail.url`  << Webmail
      - `https://wiki.url`  << Internal Wiki/HR page
      - `https://CRM.url` << CRM Software

##### Example A
&nbsp; &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Title: [ `...text field..........................................` ]  
&nbsp; Username: [ `...text field..........................................` ]  
&nbsp; &nbsp;Password: [ `...text field..........................................` ]  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Repeat: [ `...text field..........................................` ]  
[ ✓] Expires: [ `...datetime field....................` ] [ Presets v ]  
&nbsp; &nbsp; [➕] &nbsp; URL  [ `...text field for URL...` ]  [ `...text field for title...` ]  
[✓] &nbsp; &nbsp; Notes [ `...memo field..........................................` ]

##### Example B
&nbsp; &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Title: [ `...text field..........................................` ]  
&nbsp; Username: [ `...text field..........................................` ]  
&nbsp; &nbsp;Password: [ `...text field..........................................` ]  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Repeat: [ `...text field..........................................` ]  
[ ✓] Expires: [ `...datetime field....................` ] [ Presets v ]  
&nbsp; &nbsp; [➖] &nbsp; URL  [ `...text field for URL...` ]  [ `...text field for title...` ] 
&nbsp; &nbsp; [➖] &nbsp; URL  [ `...text field for URL...` ]  [ `...text field for title...` ] 
&nbsp; &nbsp; [➕] &nbsp; URL  [ `...text field for URL...` ]  [ `...text field for title...` ]  
[✓] &nbsp; &nbsp; Notes [ `...memo field..........................................` ]

**Comment by droidmonkey** [comment]
Please see #1769, I like your implementation idea. We are a little hamstrung on how this works because of the way KeePass itself handles URLs (ie, only one per entry). Therefore the implementation for this feature would necessitate using the attributes to store URL2, URL3, URL4, etc. I like your design because it keeps the attributes in the back end and lets the user just "make it work" for them.

We can store a URL title, but again that would be a custom attribute since KeePass does not support it.

**Comment by notlinustorvalds** [comment]
re: [https://github.com/keepassxreboot/keepassxc/issues/2356#issuecomment-427197444]()

Hmm... #1769 looks kinda like one of my workarounds.

How about this then?  
...Instead of multiple URL's, We get the same thing with a Username / Password link?  Essentially, you could have a single-sign on -- literally in that if you change the source, you change it for all linked entries -- but you get multiple entries (and notes, attributes, etc) for each URL.

Yeah, maybe it's not the cleanest bookmark manager -- but it's certainly doable.

If you like that more -- and SSO is really common -- I'd be happy to write up a new feature request.

##### Example:
&nbsp; &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Title: [ `...text field..........................................` ]  
&nbsp; Username: [ `...text field............................` ]  [ **Link UN/PW** ]  
&nbsp; &nbsp;Password: [ `...text field............................` ]  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Repeat: [ `...text field..........................................` ]  
[ ✓] Expires: [ `...datetime field....................` ] [ Presets v ]  
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; URL  [ `...text field for URL..................................` ]   
[✓] &nbsp; &nbsp; Notes [ `...memo field..........................................` ]

**Comment by droidmonkey** [comment]
I'm not sure I understand what you mean in your last post.

**Comment by droidmonkey** [comment]
I was going to point you towards cloning entries, but thought you were already using them 😑!

I like the idea of the insert reference (almost like a reverse clone operation).

**Comment by enboig** [comment]
I have the same problem. Using original keepass I had two solutions:
- I started duplicating entires, having an easy way to insert references is a good helper, but when updating a password you have to find the original one.
- I was using keepass+kee (AKA keefox), which allow to set more than one URL per entry, maybe you could check how they allowed that.

**Comment by droidmonkey** [comment]
This was deployed as part of 2.5.0
