### ISSUE TITLE
Feature Request: "Rearrange" functions of "Move Group One Up/Down"

### ISSUE THREAD

**Issue by sainokawara** [keepassxreboot/keepassxc#2359]
Although security and integrity have to be your first priority, there is one aesthetic function of Keepass that I would find useful in KeepassXC if it did not require too much code: The ability to "reorder" Groups.  The "Rearrange" functions of "Move Group One Up" or "Move Group One Down" would be adequate.  Of course, I would want the change to be "permanent".

**Comment by droidmonkey** [comment]
There is no need for a move group up/down option, simply drag and drop the groups to reorder them. We have an issue to track sorting groups alphabetically: #2044

**Comment by sainokawara** [comment]
Before I posted, I had tried that but it didn't work.  I now see that I have to first get a line separating two groups to move it between the groups or a box around a group to make it a subgroup.  Otherwise, it doesn't move!  And, it helps if you move it a little to the right so you can see these clearly.  My apologies for the post and this is a much superior solution than my suggestion.  As for sorting, I like the entries being in alphabetical order but prefer to order the groups myself.  But, I can see that some people may want the groups to function similarly.  Thank you for the information and the KeepassXC package.

**Comment by Anke** [comment]
Hi, I'm trying to change from Password Depot to KeePassXC. Importing > 1,300 records might have been more comfortable using xml, but as I read, hopefully that's coming. BTW I experienced RAM errors trying to import all records in one step.

Now I was looking for a way to rearrange my groups and, of course, I search the help file first - to no avail. I there any way (link) to help keep the help file (which is a pdf) up to date? (Drag&drop is just too easy to expect :-))

**Comment by droidmonkey** [comment]
There is a group sort feature now for alphabetical in 2.5.x
