### ISSUE TITLE
Properly escape HTML in message boxes

### ISSUE THREAD

**Issue by phoerious** [keepassxreboot/keepassxc#236]
When entry titles or other fields are used as part of a message box, the string should be properly escaped to prevent HTML evaluation. Right now, this is not always the case (such as the confirmation before moving an entry to the trash).

Since Qt does not allow <script> tags and the possible CSS subset is very limited, this is not a security issue, but it can produce weird effects when the string contains HTML elements.

## Expected Behavior

HTML tags should be properly escaped

## Possible Solution

All user-defined strings which are displayed in the user interface should be properly escaped using QString::toHtmlEscaped().

## Your Environment

* KeePassXC version/commit used: 2.1.0
* Qt version (e.g. Qt 5.3): 5.7
* Compiler (e.g. Clang++3.6.0): G++ 6.3
* Operating System and version: Arch Linux

**Comment by Throne3d** [comment]
Related: the "headline" when editing an entry isn't properly sanitized. (See [this screenshot](https://i.gyazo.com/9666e70f843ae98e898e6cd0bd3c8418.png).) Seems to use both `Group`s `name`s and `Entry`s' `entryTitle`s, by way of `EditEntryWidget::loadEntry`'s `parentName` parameter, called from (for example) `DatabaseWidget::switchToEntryEdit` and `DatabaseWidget::switchToHistoryView`. `QLabel`s should probably be similarly sanitized.

**Comment by phoerious** [comment]
Fixed by above-mentioned commits.
