### ISSUE TITLE
Update Last Accessed whenever entry is viewed or interacted with

### ISSUE THREAD

**Issue by 2tbwXj46BDbdNBRV79DS** [keepassxreboot/keepassxc#2368]
Similar to Accessed but for the Accessed column to be triggered you must view/edit the entry. 

A column that is dated when I copy either the username or copy the password would help me.

**Comment by droidmonkey** [comment]
There is a last accessed field, but it is updated at the same time as modified so it is meaningless. This is a good suggestion. What are the specific triggers you would expect would trigger a time update?

https://github.com/keepassxreboot/keepassxc/blob/develop/src/core/Entry.cpp#L90

**Comment by 2tbwXj46BDbdNBRV79DS** [comment]
Id say trigger when Password is copied/autotyped. Because sometime I copy the username(my email address) when filling out a forum (not login in my email.)

**Comment by CodingSpiderFox** [comment]
Also it should be updated if you double click the entry to edit it. While editing you also view the data.

**Comment by droidmonkey** [comment]
#2005
