### ISSUE TITLE
Show duplicate password entries

### ISSUE THREAD

**Issue by l0b0** [keepassxreboot/keepassxc#2369]
Some users may be using a password manager even if *some* of their passwords are duplicates. To help these figure out which passwords should be changed it would be good to have some way of showing entries with the same password.

## Expected Behavior

One very simple solution would be to make the search field match passwords as well as other content: if I copy a password to the search field it would show all entries with a matching password (or possibly password substring, to work with passwords with the same root.

Another way would be a separate entry in the "Tools" menu which would work kind of like a search filter, but which simply lists any entries which have the same password as any other entry.

## Context

I believe almost all of the passwords in my KeePass database are unique, but I have some really old entries in there. It would be good to make sure they are all unique.

**Comment by droidmonkey** [comment]
Hello, this is covered by #551, thank you for your post though.
