### ISSUE TITLE
Using cmd:// url breaks icon download and http plugin

### ISSUE THREAD

**Issue by droidmonkey** [keepassxreboot/keepassxc#238]
When the url entry is populated with cmd://{CMD_HERE} {URL_HERE} it breaks icon download and http plugin.

## Expected Behavior

When you download an icon or use the http plugin the url would be extracted from the url string, ignoring the cmd prefix.

## Current Behavior

The entire url entry is used.

## Possible Solution

Create a function that "hunts" for the actual url in the url entry using the http|s prefix as a clue. This substring would then be passed to the requesting functionality.

## Steps to Reproduce (for bugs)

1. Create an entry and assign the URL entry to: cmd://firefox https://www.google.com
2. Attempt to download the icon
3. Icon download will fail

## Your Environment

This happens in all environments

**Comment by TheZ3ro** [comment]
This should be fixed with #719. Closing
