### ISSUE TITLE
Remove version number build artefacts. 

### ISSUE THREAD

**Issue by kapad** [keepassxreboot/keepassxc#2380]
For builds that are under the tag of `latest` remove the version number from the file names because it makes it more difficult to download the builds via a script. (Basically, I need to update the script with every new version, or parse the download url from the github api). 

What I am doing right now is, 
```
wget -O $HOME/Applications/KeePassXC.AppImage \
  $(curl -s "https://api.github.com/repos/keepassxreboot/keepassxc/releases/latest" \
    | jq -r '.assets | .[] | select(.name | test("^KeePassXC.*AppImage$"; "s")) | .browser_download_url')
```

And what I would like to do is something like
```
wget "https://github.com/keepassxreboot/keepassxc/releases/download/latest/KeePassXC-x86_64.AppImage"
```

**Comment by phoerious** [comment]
Not sure what you mean. The AppImages only have SNAPSHOT in their name. We need to adjust this for the Windows builds, though.

**Comment by kapad** [comment]
Nope.. the link is `https://github.com/keepassxreboot/keepassxc/releases/download/2.3.4/KeePassXC-2.3.4-x86_64.AppImage`, so I need to do `wget "https://github.com/keepassxreboot/keepassxc/releases/download/2.3.4/KeePassXC-2.3.4-x86_64.AppImage"` to download the file. 

Now, when 2.3.4 is released, the script will need a change (to the url, which is itself auto generated by github from the release filename) to and the wget command would need to be updated to `wget "https://github.com/keepassxreboot/keepassxc/releases/download/2.3.4/KeePassXC-2.3.5-x86_64.AppImage"`

If however, the release file was simply named `KeePassXC-x86_64.AppImage` then the following `wget "https://github.com/keepassxreboot/keepassxc/releases/download/2.3.4/KeePassXC-x86_64.AppImage"` would always fetch the latest release.

**Comment by droidmonkey** [comment]
It does, and I am not in favor of that approach at all. I value version numbers in the download name because you know which is which on your system. Your script works fine as it is, there really isn't a problem here.

**Comment by RealOrangeOne** [comment]
Correct me if i'm wrong, but no matter what, you're going to need to bake the specific version of KeepassXC into the URL anyway. What difference does encoding it twice make? If GitHub supported URLs like `https://github.com/keepassxreboot/keepassxc/releases/download/latest/KeePassXC-x86_64.AppImage`, then I see your point. but it doesn't seem to. And having the release version number baked into the release also prevents accidental overriding of files.

`wget` supports specifying the output filename, so simply doing wget "https://github.com/keepassxreboot/keepassxc/releases/download/2.3.5/KeePassXC-2.3.5-x86_64.AppImage" -O "KeePassXC-x86_64.AppImage"` may solve your issue?

**Comment by kapad** [comment]
@droidmonkey yeah.. I figured that script will always work as long as the latest build artifacts are published to under the "latest" tag. 

It's just that it's not the most intuitive command to download, and most online instructions for KeePassXC have just the wget command, for eg. `wget "https://github.com/keepassxreboot/keepassxc/releases/download/2.3.4/KeePassXC-2.3.4-x86_64.AppImage"`. Now often, these urls are older and if someone reading the post doesn't bother to check on github, they'll be downloading an older version. 

Adding support for a download url for which I could do `wget "https://github.com/keepassxreboot/keepassxc/releases/download/latest/KeePassXC-x86_64.AppImage"` ensures that whenever I run that command, I always get the latest version of the software.

**Comment by droidmonkey** [comment]
I think a good compromise would be to add a redirect from our website (eg https://keepassxc.org/download/latest/appimage) which would be updated when a release is made.

**Comment by kapad** [comment]
Yes. That would definitely be better. Right now the URL on the website is
directly linked to the specific GitHub release.

**Comment by droidmonkey** [comment]
So I was feeling really nice this evening and created the URL's for you (and others):

https://keepassxc.org/downloads/appimage
https://keepassxc.org/downloads/appimage-sig
https://keepassxc.org/downloads/appimage-digest

The same pattern works with /win64, /win64portable, /win32, /win32portable, and /macos

**Comment by kapad** [comment]
```

**Comment by droidmonkey** [comment]
OK I got it to work, had to manually update the website.

**Comment by kapad** [comment]
Wow. Thanks. :)
