### ISSUE TITLE
Auto-Type in Firefox doesn't work with X.org as display server

### ISSUE THREAD

**Issue by Atalanttore** [keepassxreboot/keepassxc#2383]
Auto-Type in Firefox (60+) works with Wayland, but not with X.org as display server.

## Expected Behavior
Same behavior with Wayland and X.org.

## Current Behavior
Auto-Typing my credentials to a login field in Firefox works, but the login will fail when using X.org as display server. In contrast, Auto-Typing using Wayland as display server does work without any login problems.

## Problem cause
Maybe a problem with the KeePassHTTP extension.

## Steps to Reproduce (for bugs)
1. Start a desktop session with X.org as display server
2. Start Firefox
3. Start KeepassXC
4. Open your password database in KeepassXC
5. Choose the correct entry for your mail provider in KeepassXC
6. Goto the login field of your webmailer in Firefox
7. Make KeepassXC the active window
8. Press Ctrl+V

## Debug Info
KeePassXC - Version 2.3.4
Revision: 6fe821c

Libraries:
- Qt 5.9.5
- libgcrypt 1.8.1

Operating system: Ubuntu 18.04.1 LTS
CPU architecture: x86_64
Kernel: linux 4.15.0-36-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by kneitinger** [comment]
I am experiencing this as well on Firefox 62.0.3 (Arch, 64 bit, 4.18.12-arch1-1-ARCH). It happens on 2.3.4 as well as `develop` at 2653250

**Comment by droidmonkey** [comment]
Are we taking about auto-type or browser integration?

Why would pressing CTRL+V do anything useful after being back in Firefox? That shortcut only works when KeePassXC is the active window.

**Comment by kneitinger** [comment]
I was referring to auto-type global shortcut, I tested it on my work computer (same exact setup as home computer) and it worked perfectly.  Investigated some more, and turns out I had another instance of keepassxc open on my personal computer from testing something else, and it was interfering. So actually, I cannot replicate this on X.org with 60+ Firefox.

**Comment by Atalanttore** [comment]
> Why would pressing CTRL+V do anything useful after being back in Firefox? That shortcut only works when KeePassXC is the active window.

You're right. KeePassXC needs to be the active window and not Firefox.

**Comment by droidmonkey** [comment]
Does this mean you do not experience this issue now?

**Comment by Atalanttore** [comment]
No. KeePassXC works fine with Wayland, but not with X.org.

**Comment by droidmonkey** [comment]
Are you sure this is not reversed? Auto-Type works perfectly fine in X.org but it will NOT work with Wayland. Does auto-type work in any other application under your X.org?

**Comment by Atalanttore** [comment]
Yes. Auto-Type works perfectly fine on my machine with Wayland, but **not** with X.org.

**Comment by TeutonJon78** [comment]
Have you tried switching to the correct browser plugin for KeepassXC rather than the legacy one?
https://addons.mozilla.org/en-US/firefox/addon/keepassxc-browser/

**Comment by Atalanttore** [comment]
I've replaced KeePassHTTP by KeePassXC-Browser, but the problem hasn't changed.

**Comment by droidmonkey** [comment]
@Atalanttore Auto-Type has absolutely nothing to do with the browser plugin(s). And the browser plugin(s) have absolutely nothing to do with Wayland vs X.org. I really have no idea what is and is not working based on your report.

**Comment by droidmonkey** [comment]
What is your auto type shortcut? It might be conflicting with a keyboard shortcut that Firefox is using.

**Comment by Atalanttore** [comment]
@droidmonkey: My global Auto-Type keyboard shortcut is Ctrl+K.

**Comment by droidmonkey** [comment]
CTRL+K is focus search in Firefox: https://support.mozilla.org/en-US/kb/keyboard-shortcuts-perform-firefox-tasks-quickly#w_search

Change the keyboard shortcut (suggest CTRL+SHIFT+K), report back.

**Comment by Atalanttore** [comment]
@droidmonkey: I've changed the shortcut to Ctrl+Shift+K, but it still doesn't work. As mentioned above, letting KeePassXC paste the credentials into login form using Ctrl+V doesn't work as well.
