### ISSUE TITLE
Show total number of passwords in database?

### ISSUE THREAD

**Issue by torekk** [keepassxreboot/keepassxc#2386]
I know this would be more of a cosmetic/statistics feature and isn't really needed, but it'd be nice to see how many passwords you got in your database, or is there already an option for that which I just missed?

Edit: Apparently this was possible in KeePass, so I'm not sure why it was even removed/not added yet?
https://sourceforge.net/p/keepass/discussion/329221/thread/14add61e/

**Comment by droidmonkey** [comment]
Covered by #551
