### ISSUE TITLE
Detect changes to database file prior to save and prompt to merge

### ISSUE THREAD

**Issue by droidmonkey** [keepassxreboot/keepassxc#2389]
## Expected Behavior

If the underlying database file changes for whatever reason, KeePassXC should detect this and prompt to merge those changes prior to saving.

## Current Behavior

This works sometimes using the file watcher construct. However, it often fails for USB drives and network shares.

## Possible Solution

Store a hash of the database file when opening and after every save. Compare this hash to one developed just prior to saving and trigger actions if they differ.

## Steps to Reproduce (for bugs)

1. Create database, store on SMB share
2. Open database on another computer, make changes
3. Make changes on original computer, save
4. Data is lost

**Comment by liberodark** [comment]
very important feature, thank you for working on it ^^
Great job team
