### ISSUE TITLE
flathub / flatpak version 2.3.4

### ISSUE THREAD

**Issue by zz0rk** [keepassxreboot/keepassxc#2390]
When I try to open an attachment (i.e. PDF, PNG, etc.) the attachment fails to open in designated application. When I try to save the attachment I can't save to a location that I can access (i.e. Desktop, Documents, Downloads, etc.). When I try to save the attachment to a removable media location as per FAQ (Snap) it fails as well. This behavior is repeatable on different workstations running the same flatpak version.

Operating system: Debian GNU/Linux 9 (stretch) 64-bit
CPU architecture: Intel® Xeon(R) CPU W5590 @ 3.33GHz × 16 
Kernel: 4.9.0-8-amd64

Enabled extensions: None

**Comment by droidmonkey** [comment]
See #1524, we currently do not control the flatpak distribution.
