### ISSUE TITLE
Tor Browser Support for Windows

### ISSUE THREAD

**Issue by optimisticninja** [keepassxreboot/keepassxc#2392]
### Issues found
* In implementing Windows support - looks like native-messaging-hosts is a registry entry for FF and other browsers. Is this the approach we want for Windows? 
* Tor is self contained and portable on Windows and can be on other OSes. 
* We'd need to add a registry cleanup to uninstallation. And portable installs are not guaranteed to work.

### Resolution Ideas
* I believe I should at a UI component to point to the Tor Browser installation. If I can avoid registry I'd like to, no footprint is a good footprint. 
* I can run experiments to see if I can use the same approach I used in Linux with the Tor Browser .mozilla directory for native-messaging-hosts. This way would solve portable installations on all OSes. 

If it works is this agreeable?

The branch of interest is **in my fork**: `feature/tor-browser-windows-support`

EditEntryWidget::setupColorButton is where GDB reports the SEGFAULT. I'm very unfamiliar in Windows environments and don't know my way around without Valgrind.

_Originally posted by @optimisticninja in https://github.com/keepassxreboot/keepassxc/pull/2387#issuecomment-430489963_

See: My fork https://github.com/optimisticninja/keepassx @ [origin/feature/tor-browser-windows-support](https://github.com/optimisticninja/keepassxc/tree/feature/tor-browser-windows-support)

**Comment by optimisticninja** [comment]
Program received signal SIGSEGV, Segmentation fault.
__static_initialization_and_destruction_0 (__initialize_p=1, __priority=65535)
    at C:/msys64/home/MainUser/git/keepassxc/src/totp/totp.cpp:208

**Comment by varjolintu** [comment]
Windows needs a registry entry to the native messaging script file. The location can of course be inside of Tor Browser installation so it will be deleted automatically after uninstall.

I have debugged Windows builds with qtcreator installed from MSYS2 shell.

**Comment by optimisticninja** [comment]
> 
> 
> Windows needs a registry entry to the native messaging script file. The location can of course be inside of Tor Browser installation so it will be deleted automatically after uninstall.
> 
> I have debugged Windows builds with qtcreator installed from MSYS2 shell.

Thanks, I have added the registry entry in the HostInstaller.cpp on `feature/tor-browser-windows-support`, may have not merged into the Linux branch which I was testing last night - but I do remember it behaving the same way upon testing in the windows branch. If that registry subfolder doesn't exist - do I need to add code to create it? Sorry for my incognizance towards Windows. I grew up too poor for licenses :)

I'll get QTCreator up and running this evening and if this gets resolved add the UI components for portable. Very happy to be working with you guys, you have been incredibly helpful and prompt.

**Comment by kneitinger** [comment]
@optimisticninja I don't have any experience with the totp code, just the theory :slightly_smiling_face: 

I also don't have any experience developing on windows, but with that said, I've been meaning to get a windows dev setup going for testing keepassxc stuff, and would be happy to take a look this weekend!

If I have any questions that would clutter up this convo is it okay to email you at the address on your blog?

**Comment by droidmonkey** [comment]
@optimisticninja are you using GCC 8.2.x? There is a known bug with that version with secure memory. Downgrade to GCC 7.3.0 in MSYS2.
