### ISSUE TITLE
Update Windows build environment setup wiki

### ISSUE THREAD

**Issue by optimisticninja** [keepassxreboot/keepassxc#2393]
There is a missing dependency in the MSYS setup for compiling on Windows - wiki needs to be updated.

## Expected Behavior
Compiling keepassxc on a Windows host with the provided dependency setup fails to succeed on cpack with NSIS.

## Current Behavior
`make -j8 package` fails to create installer because of missing NSIS dependency.

## Possible Solution
Add the following to dependency installation wiki.

```bash
$ pacman -S mingw-w64-$(uname -m)-nsis
```

## Steps to Reproduce (for bugs)
1. Follow current wiki from a bland installation - everything will compile and fail to package.

## Context
Trying to contribute a cross-platform issue, had to stop work and debug what was going on in the failure.

## Debug Info
```bash
$ cpack -G NSIS
```
```
Platform/MINGW64_NT-6.1 to use this system, please send your config file to cmake@www.cmake.org so it can be added to cmake
CPack Error: CPack project name not specified
```

```bash
$ cpack -G NSIS64
```
```
Platform/MINGW64_NT-6.1 to use this system, please send your config file to cmake@www.cmake.org so it can be added to cmake
CPack Error: CPack project name not specified
```

Operating system: Windows 10 Enterprise Trial for Edge running in VirtualBox
CPU architecture: x86_64
Kernel: NT Hell

**Comment by droidmonkey** [comment]
It really should be updated to install the WiX platform since we are getting rid of the NSIS installer starting with 2.4.0.

**Comment by optimisticninja** [comment]
Thanks @droidmonkey :)

**Comment by droidmonkey** [comment]
Added instructions
