### ISSUE TITLE
SSH-Agent seems not working in 2.3.4 Ubuntu 18.04

### ISSUE THREAD

**Issue by ftorto** [keepassxreboot/keepassxc#2394]
## Expected Behavior

I'm expecting to have my ssh connection working with keepassxc

## Current Behavior

After opening and unlocking my database, I try to connect to a remote server that has accepted my key (before handling it with keepassxc). The server still asking me the password and don't care about any key

**details about my configuration is described in context part**

## Possible Solution

- unidentified bug?
- PEBKAC? (and I'm really sorry)
- Missing part in documentation?

## Steps to Reproduce (for bugs)

1. open keepassxc via the gnome launcher, unlock database, no warning displayed about any agent refusing my key
2. open terminal via shortcut ctrl+alt+t and try to ssh any server that has my key
3. server asking me password and don't use my key (stored in a keepassxc entry as attach)

## Context

- in keepassxc, the `Enable SSH agent` checkbox is ticked and I restarted keepassxc (and computer for other reasons)
- About the keepassxc entry:
  - My SSH entry has the private key in attachment, the passphrase of the key is the password of the entry, RSA 4096
  - `Add key to agent` when opened is checked
  - `Remove key when locked` is checked
  - other checkbox are unchecked
- `ssh-add -l` shows nothing (list keys handled by agent)
- starting keepassxc from terminal and trying `ssh-add -l` show nothing
- `ps` show only 1 agent started
- I installed `ssh-askpass`
- I don’t have red banner errors at start so I assume `ssh-agent` or `gpg-agent` is running and available.
- If I save my key manually from keepassxc entry on my computer, I’m able to connect via `ssh -i mykey myserver` without any issue (so the key is not corrupted), I need to enter the passphrase of the key (obviously).
- even if I’m not on an apple device, I followed [this blog](https://blog.valouille.fr/post/2018-03-27-how-to-use-keepass-xc-with-ssh-agent/) but still fail.
- I also followed the [FAQ](https://keepassxc.org/docs/#faq-ssh-agent-how)
- I didn't found any existing issue similar to mine

## Debug Info

KeePassXC - Version 2.3.4
Revision: 6fe821c

Libraries:
- Qt 5.9.5
- libgcrypt 1.8.1

Operating system: Ubuntu 18.04.1 LTS
CPU architecture: x86_64
Kernel: linux 4.15.0-36-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by DDzwiedziu** [comment]
I'm having an identical issue, but with an ED25519 key. And what is more surprising at my ex-work environment it was working, just I'm not sure if the key I used was RSA 2048.

**Comment by ftorto** [comment]
I tried to figured out how to get rid of this problem and I have a solution to propose.

First, I added this block to `~/.profile`
```
# SSH-AGENT START
export SSH_AUTH_SOCK=~/.ssh/ssh-agent.$HOSTNAME.sock
ssh-add -l 2>/dev/null >/dev/null
if [ $? -ge 2 ]; then
   ssh-agent -a "$SSH_AUTH_SOCK" >/dev/null
fi
# SSH-AGENT END
```

Then, I started keepassxc at startup with `startup application preferences` (hold `super` then, write `startup...` to bring

**Comment by ftorto** [comment]
I tried to figure out how to get rid of this problem and I have a solution to propose for Ubuntu.
The cause seems to be the ssh-agent is not shared between terminals and keepassxc.

First, I added this block to `~/.profile`
```
# SSH-AGENT START
export SSH_AUTH_SOCK=~/.ssh/ssh-agent.$HOSTNAME.sock
ssh-add -l 2>/dev/null >/dev/null
if [ $? -ge 2 ]; then
   ssh-agent -a "$SSH_AUTH_SOCK" >/dev/null
fi
# SSH-AGENT END
```

Then, I started keepassxc at startup with `startup application preferences` (hold `super` then, write `startup...` to start it
Add a new entry where the command line is:
`env SSH_AUTH_SOCK=${HOME}/.ssh/ssh-agent.${HOSTNAME}.sock /usr/bin/keepassxc`

Now reboot.
After next login, you'll have keepassxc started, sharing the same SSH_AUTH_SOCK as any other terminal so the `ssh-agent` works properly (adding/removing keys when unlocked/locked is ok)

**Comment by DDzwiedziu** [comment]
@ftorto you're on to something. Starting keepassxc from the console adds the key properly.
 I'll move my ssh-agent invocation from .zshrc to .profile and see if it helps.

**Comment by DDzwiedziu** [comment]
@ftorto you're on to something. Starting keepassxc from the console adds the key properly.
 I'll move my ssh-agent invocation from .zshrc to .profile and see if it helps.

**Comment by hifi** [comment]
`ssh-agent` should be started by the desktop environment on Ubuntu in a way the socket environment variable is exported to all child processes. It depends on the desktop environment how it is configured but having such thing in `.profile` is definitely a hack.

If you're only using a window manager, add `eval $(ssh-agent)` into your X startup script before the WM is started.

**Comment by ftorto** [comment]
@hifi is the `SSH_AUTH_SOCK` variable exported and available to all child processes with your idea (I'm not expert, maybe a dumb question) ?

**Comment by DDzwiedziu** [comment]
In my case it was the zsh antigen bundle for ssh. Just removing it fixed the issue.

**Comment by Aimmig** [comment]
Still having the same problem here on KDE. Which solution did work for you?

**Comment by DDzwiedziu** [comment]
If the question is for me then for me the part with the plasma env works.

**Comment by droidmonkey** [comment]
Closing this as I don't think it is an issue anymore
