### ISSUE TITLE
Add an alert to the favicon downloader when the link doesn't respect an http schema

### ISSUE THREAD

**Issue by TheZ3ro** [keepassxreboot/keepassxc#240]
## Expected Behavior

When an URL is saved in the form "www.example.com", alert user that the url doesn't have a valid protocol schema (like http or https)

## Current Behavior

When an URL is saved in the form "www.example.com", downloading the icon will result in a `Unable to download the icon` message.

### Related to #238

**Comment by kentala** [comment]
I would prefer this: if no schema is set in url, the app should attempt to download via https and if that fails via http.

**Comment by TheZ3ro** [comment]
@kentala I like your idea but the fact is that the input isn't always an URL so the flow should be:

  1.Try HTTPS
  2. if HTTPS fail, try HTTP
  3. if HTTP fail report error
