### ISSUE TITLE
CTRL+V after searching doesn't start autotype anymore

### ISSUE THREAD

**Issue by sqrt** [keepassxreboot/keepassxc#2403]
## Expected Behavior
In earlier versions, it was possible to search for an entry using the search bar, and directly start autotype when the respective entry is selected. This doesn't work in 2.3.4 anymore.

## Current Behavior
Instead, CTRL+V works as 'paste' and pastes the current clipboard content into the search field. 

## Possible Solution
I understand that using CTRL+V in a text input field can be expected to paste text. However, this change breaks accustomed user flow. A possible solution would be user-configurable shortcuts. See also https://xkcd.com/1172/ ;)

## Debug Info
KeePassXC - Version 2.3.4
Revision: 6fe821c

Libraries:
- Qt 5.11.1
- libgcrypt 1.8.3

Operating system: Fedora 29 (Twenty Nine)
CPU architecture: x86_64
Kernel: linux 4.18.14-300.fc29.x86_64

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by droidmonkey** [comment]
Press down arrow to focus on the found entry than CTRL+V. I am not in favor of breaking paste at all.

**Comment by phoerious** [comment]
I'm much in favour of changing the auto-type hotkey to something else. I have accidentally hit Ctrl+V so many times to find myself inadvertently auto-typing all over the place.

**Comment by droidmonkey** [comment]
Closing this as the shortcut is being changed to CTRL+SHIFT+V and the down arrow, select entry action is going to be the only acceptable solution in 2.4.0 and on.
