### ISSUE TITLE
Browser Integration should search all open databases for entries

### ISSUE THREAD

**Issue by imp1sh** [keepassxreboot/keepassxc#2409]
When I have two kdbx files open and the one I would like to use is in the background, Browser plugin does not work.

## Expected Behavior
It should not be necessary for me to bring the right tab in foreground in order for the autofill feature to work.

## Current Behavior
I have to bring KeepassXC in the foreground and then click the tab the designated password comes from, get back to firefox and then try again.

## Possible Solution
don't know

## Steps to Reproduce (for bugs)
1. Configure Firefox Browser Plugin
2. Open two different kdbx files. The one the password you need from send to the background, meaning have the other kdbx file tab activated.
3. Browse the designated website the password is needed for
4. Realize that the password won't be inserted
5. Go back to KeepassXC and hit the tab the password comes from
6. Go back to Browser and see that it now works.

## Debug Info
 I use Firefox 62.0.3 with  KeePassXC-Browser Version: 1.3.0 and KeePassXC Version: 2.3.4 under Linux.
Libraries:
- LIBS

Operating system: OS
CPU architecture: X86-64
Kernel: 4.18.14-200.fc28.x86_64
Distribution: Fedora 28

Enabled extensions:
- Browser Integration for Friefox

**Comment by imp1sh** [comment]
never saw this Advanced tab before, thank you.

**Comment by droidmonkey** [comment]
That is not the fix because that searches databases that are not setup for browser integration. When that setting is disabled, the browser service should still check each open database for the ones connected to the browser regardless of the currently selected database.

**Comment by varjolintu** [comment]
@droidmonkey It's already fixed. See https://github.com/keepassxreboot/keepassxc/pull/1810.

**Comment by rocketraman** [comment]
I have that advanced setting checked and yet my browser integration is not able to see entries in open + connected databases, but when the tab is not in the foreground. Not sure what I'm doing wrong...

**Comment by varjolintu** [comment]
@rockdreamer Can you test if the same happens with the latest snapshot release: https://snapshot.keepassxc.org/latest/

**Comment by rocketraman** [comment]
@varjolintu Yes it does.

**Comment by rocketraman** [comment]
@varjolintu Yes, it is still not working with the latest snapshot.

![image](https://user-images.githubusercontent.com/53049/65970006-c15be180-e433-11e9-8144-cb71dd36022c.png)

**Comment by varjolintu** [comment]
@rockdreamer I cannot reproduce it. Just tested it with the latest develop branch and 1.5.1.

**Comment by rocketraman** [comment]
@varjolintu BTW, its @rocketraman , not rockdreamer . They were connected. Just changing open tabs was sufficient to access the password in the database. However, I removed all the credentials from the browser plugin, and reconnected the databases, and now it works! Perhaps one of the recent migrations of the plugin or the database data borked the connection somehow.

Thanks for your help!

**Comment by varjolintu** [comment]
It can be possible that the connections needed to be re-established. Glad to hear it works.

**Comment by gaensler** [comment]
It's not working for me, if only the database without focus is connected to the Browser Plugin and the one focused is not connected.
From @droidmonkey's comment i read that this should  explicitly be possible
> That is not the fix because that searches databases that are not setup for browser integration. When that setting is disabled, the browser service should still check each open database for the ones connected to the browser regardless of the currently selected database.

To clarify my case:
- Database A is connected to Browser-Plugin and **not** focused in Client
- Database B is **not** connected to Browser-Plugin and focused in Client
- "No Logins found" when clicking username field icon 
- If Database A is focused the credentials are found and filled into Browser.

I also checked points from above conversation:
- Checked `Search in all opened databases for matching credentials` (which moved from the Advanced to the General tab)
- Both databases are unlocked in client
- refreshed database-connection after removing keys from both Browser Plugin and Database Settings

**Comment by varjolintu** [comment]
@gaensler This is already tracked in https://github.com/keepassxreboot/keepassxc/issues/5238
