### ISSUE TITLE
DB impossible to open with keepassxc-cli when using non-ASCII (UTF-8) chars in passphrase :(

### ISSUE THREAD

**Issue by liar666** [keepassxreboot/keepassxc#2413]
- create a brand new DB with KeepassXC GUI
- set a passphrase using an UTF8 char (e.g. É, È, Ç) entered with WinCompose (or: copy paste from: https://www.fileformat.info/info/unicode/char/00c9/index.htm)
- add a few groups/keys
- save & close

## Expected Behavior

- reopen the .kdbx file with keepassXC-cli
- type my password
- see/edit entries

## Current Behavior

- password is refused with message "Error while parsing the database: Wrong key or database file is corrupt."

## Debug Info
KeePassXC - 2.3.4

Operating system: Win7 + cmd.exe/Console2/git-bash + WinCompose
CPU architecture: intel core i5

**Comment by droidmonkey** [comment]
You listed several command prompts, did you try all three of those? Are they all setup to use UTF-8 encoding? We have had issues with the windows command prompt password prompt. I believe they are fixed in 2.4.0 though. Can you try the latest 2.4.0 snapshot? https://snapshot.keepassxc.org

**Comment by phoerious** [comment]
Kan you try calling the CLI like so?

```
LANG=en_US.UTF-8 keepassxc-cli [params]
```
We use a QTextStream, which uses the system's default encoding for anything. That may produce unexpected behaviour. In 2.4.0 I forced the password generator to use UTF-8 in all cases, so it doesn't show `????????` if the locale is set to C or some other single-byte encoding (which is the default at least on Windows). Perhaps we need to do the same thing for password prompts or everything else. Might be another good test case we should add to our test suite.

**Comment by liar666** [comment]
Hi,

@droidmonkey Yes, I've tried all these shells

@phoerious Yes this IS windows :) I've tried the provided command within git-bash, but it does not work... But the think is the password prompt in git-bash seems to be broken too: the password I type is displayed in clear text!!!!

to be followed...

**Comment by phoerious** [comment]
I'll test it when I get home.

**Comment by phoerious** [comment]
The mapping from cp1252 to UTF-8 appears to be bugged on Windows. I tried various methods, but I cannot get it to convert it correctly. `QString::fromUtf8()` always produces valid UTF-8 codes, but not the correct ones. Might as well be a Qt bug.

**Comment by phoerious** [comment]
I found the problem. When run from cmd or PowerShell, the input and output encoding is cp850, which is the DOS codepage, instead of cp1252 which is used for GUI applications. When run from a cygwin/Msys2 bash, the encoding is UTF-8, which isn't the system encoding reported by Qt either. And I thought we had the year 2018...
