### ISSUE TITLE
Global Auto-type shortcut breaks the system keyboard switching shortcut

### ISSUE THREAD

**Issue by vladipus** [keepassxreboot/keepassxc#2415]
Global shortcut breaks the system keyboard switching shortcut in Linux Mint 19.

## Expected Behavior
Not to break.

## Current Behavior
Breaks.

## Possible Solution
Use other means to set a keyboard shorcut. Allow for an original command line argument to launch the auto-typing.

## Steps to Reproduce (for bugs)
1. Launch the KeePassXC with a global auto-type shortcut set.
2. Wait for some time. Doesn't happen instantly.
3. Keyboard layout switching no longer works.

## Debug Info
KeePassXC - Version 2.3.4
Revision: 6fe821c

Libraries:
- Qt 5.9.5
- libgcrypt 1.8.1

Operating system: Linux Mint 19
CPU architecture: x86_64
Kernel: linux 4.15.0-36-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by droidmonkey** [comment]
What is the keyboard switching shortcut key pattern?
What is your auto-type shortcut key pattern?

Is this really related to #2246 ??
