### ISSUE TITLE
Database cleared after reboot

### ISSUE THREAD

**Issue by elroxar** [keepassxreboot/keepassxc#2416]
## Expected Behavior

I use KeepassXC 2.3.4 on a laptop with arch/windows dualboot. I have one shared drive which syncs with my own owncloud instance. For the last weeks and months everything worked fine. I was able to access the file from my windows and from my arch. 

## Current Behavior

Yesterday I switched back to Windows for the first time in maybe two weeks. After opening the database in Windows I was greeted by a empty window with instead of my entries and folder structure just one empty folder called 'root'. I then rebooted again to look at it in Arch and it was exactly the same though it worked fine before switching to windows. Additionally I have to say that Windows did some updates (I actually think this wasn't the cause). Anyway I checked my owncloud version log and it told me there were no older versions after that I checked my server backup and the latest file that is not just 'root' is from 16 days ago, probably around the last time I used Windows. I also looked for other files in that directory and found a file called corrupted.c.kdbx which is my database from 16 days ago. 

## Possible Solution

I do not have a solution besides using this two weeks old file and trying to figure out what entries I added in the last time and how I can change them. For the future I should do backups more regulary and check if the database is actually saved and saved correctly.

## Context

I actually can't notice anything unusual. The Arch/Windows dualboot worked pretty fine before. I have also processed Windows updates before without noticing any strange behaviour. What freaks me out is, that the databese seems to be corrupted since over two weeks though I had multiple reboots (no OS switching) in that time. 

## Debug Info

KeePassXC - Version 2.3.4
Revision: 6fe821c

Libraries:
- Qt 5.11.2
- libgcrypt 1.8.3

Operating system: Manjaro Linux
CPU architecture: x86_64
Kernel: linux 4.18.16-1-MANJARO

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by droidmonkey** [comment]
If you can unlock the database that does not point to corruption. This seems, on the surface, to be an unfortunate sync issue. The original database with nothing in it must have been synced across your devices. Why are there no versions earlier than 16 days ago? Check your owncloud setup.

**Comment by dxsh** [comment]
Windows 10 1809 update included a bug deleting users' documents around earlier this October. I'm not sure what your syncing mechanism looks like, though.

https://answers.microsoft.com/en-us/windows/forum/windows_10-update/windows-10-1809-update-deleted-all-files-from/ff608374-2686-4a08-a4c2-caa4caa6d4e1

**Comment by phoerious** [comment]
Unlikely, the database would have been locked and the OP is using Arch Linux, which usually doesn't get Windows updates. ;-)

**Comment by elroxar** [comment]
As I said I am using Manjaro alongside with Linux but anyhow I also don't think Windows Updates are the cause of my problem.

**Comment by elroxar** [comment]
> The original database with nothing in it must have been synced across your devices. 
The strange thing is that I have never had a folder called 'root'. From the beginning on I named it 'Master' and so I don't understand how this Version of the database (which never existed) can be synced.
>Why are there no versions earlier than 16 days ago?
I have daily backups for the last week and 4 more weekly backups. The empty database is in every backup younger than now 20 days.

**Comment by elroxar** [comment]
I found that my IntelliJ installation, which I set up to work with a keepass db just deleted the old db and wrote a new one instead of extending it. Thanks for all the help.
