### ISSUE TITLE
Keepassxc-Browser public keys in attributes not migrated to custom data

### ISSUE THREAD

**Issue by yan12125** [keepassxreboot/keepassxc#2417]
After upgrading from 2.4.0.r147 (cfa1eca24900089a369a43c3fb871f344c19395a) to 2.4.0.r148 (efdb43dc53ad701a84fcc0beef700e81a8953734), connections from KeePassXC to browsers are lost. The browser plugin prompts me to reconnect to my database.

## Expected Behavior
The browser plugin works as usual after upgrading.

## Current Behavior
Connections are lost; public keys are not recognized.

## Possible Solution
Also migrate public keys for browser plugins from attributes to custom data

## Steps to Reproduce (for bugs)
1. Install 2.3.4.r147 (cfa1eca24900089a369a43c3fb871f344c19395a)
2. Configure the browser plugin
3. Upgrading to 2.3.4.r148 (efdb43dc53ad701a84fcc0beef700e81a8953734)
4. Try to connect from browsers again

## Context
I use the browser plugin every day on 3 machines. It will be kind of annoyance to reconfigure KeePassXC on all of them.

## Debug Info
KeePassXC - Version 2.4.0-snapshot
Build Type: Snapshot
修訂： efdb43d

函式庫：
- Qt 5.12.0
- libgcrypt 1.8.3

作業系統：Arch Linux
處裡器架構：x86_64
核心：linux 4.18.16-arch1-1-ARCH

已啟用的擴充元件：
- Auto-Type
- Browser Integration
- SSH Agent
- YubiKey

**Comment by droidmonkey** [comment]
I tested it myself before merging the PR and it worked. I will perform another test.

**Comment by droidmonkey** [comment]
I cannot replicate this behavior. I created a test database on the previous 2.4.0 snapshot, linked it to my browser, then opened it on the latest develop, upgraded the settings, locked, unlocked, and I can still connect using the same key.

**Comment by yan12125** [comment]
I guess I find the cause. KeePassXC-Browser related settings in my database was created before https://github.com/keepassxreboot/keepassxc/commit/8ac909b0ebed0f0177f3191b1ff5ef7e0ffece58, so the entry containing public keys is called `keepassxc-browser Settings` (lower cases). Before https://github.com/keepassxreboot/keepassxc/commit/efdb43dc53ad701a84fcc0beef700e81a8953734, KeePassXC searches this entry using the UUID `de887cc3036343b8974b5911b8816224`, so the title of this entry doesn't matter. However, migration codes in https://github.com/keepassxreboot/keepassxc/commit/efdb43dc53ad701a84fcc0beef700e81a8953734 appears to [check entries with the title `KeePassXC-Browser Settings`](https://github.com/keepassxreboot/keepassxc/commit/efdb43dc53ad701a84fcc0beef700e81a8953734#diff-cecbde8a48603d0bd3d683cc8eec92c4R474) (upper cases), so the migration is not triggered.

I renamed the entry manually and restart KeePassXC. The migration works fine :)

**Comment by droidmonkey** [comment]
Ok so we need to make the detection case insensitive. Good catch!

**Comment by droidmonkey** [comment]
ping @varjolintu
