### ISSUE TITLE
Remote database

### ISSUE THREAD

**Issue by abasso** [keepassxreboot/keepassxc#242]
Feature request: Allow to open remote databases, for ex over ftp. This would require sync on save (if not already present).

**Comment by droidmonkey** [comment]
Unfortunately we have made the decision that we will not support other protocols outside of file system operations. If you want to use an FTP service, set it up within your file system as a mountable directory.

**Comment by abasso** [comment]
Fair enough, maybe would be a good idea to add a line in the readme that this is not happening, I guess a lot of people come here looking for a native replacement to keepass2 and if they don't find a feature they are going to ask, like i did :)

**Comment by phoerious** [comment]
Having specific FTP support would also be inconsistent. It's very common to put your password safe into our Dropbox, Google Drive or Nextcloud. Why would you do it differently for FTP (besides the fact that it is an obsolete protocol).

**Comment by droidmonkey** [comment]
Does KeePass2 support it natively or through a plugin?

**Comment by RealOrangeOne** [comment]
@droidmonkey Keepass2 supports either HTTP (inc webdav), or FTP without any plugins. I do agree with @phoerious that adding this is may not be necessary, as long as KeepassXC does some diffing on save if the output file has changed, rather than instantly overriding it (not sure if this is already a thing?)

**Comment by droidmonkey** [comment]
We use Qt's file watcher to notify when it had changed. If there are unsaved changes you get a second prompt to merge them in.
