### ISSUE TITLE
KeePassXC consistently exits after typing two letters into the search bar

### ISSUE THREAD

**Issue by ajvsol** [keepassxreboot/keepassxc#2420]
## Expected Behavior
Able to use the search feature immediately without the app closing.

## Current Behavior
App exits after typing the second letter in the search bar.

## Possible Solution
Unknown.

## Steps to Reproduce (for bugs)
1. Open KeePassXC-2.3.4.AppImage
2. Type in password to unlock database then try to use the search bar.
3. After typing in the second letter the app closes. Usually if I unlock the app and wait 10 mins without using the search bar then the search bar will be available for normal use until the next time I restart my computer.

## Context
I often restart my computer and having to wait 10 minutes after I've first opened KeePassXC to then start using the search feature is a complete hindrance to my workflow.

## Debug Info
KeePassXC - Version 2.3.4
Revision: 6fe821c
Distribution: AppImage

Libraries:
- Qt 5.9.4
- libgcrypt 1.8.1

Operating system: Ubuntu 18.04.1 LTS
CPU architecture: x86_64
Kernel: linux 4.15.0-38-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by droidmonkey** [comment]
I cannot replicate this. Does it matter what you type into search? Can you run the snapshot and see if it persists?

https://snapshot.keepassxc.org/latest

**Comment by neomodern** [comment]
Hello, I don't have this error when using the current snapshot. 

Weird thing about it I installed a brand new Ubuntu 18.04 LTS just a day ago and the release version has the error too, but the snapshot build doesn't.

**Comment by droidmonkey** [comment]
That is weird but good to hear
