### ISSUE TITLE
About Version differs from downloaded file name (2.3.4)

### ISSUE THREAD

**Issue by Teifun2** [keepassxreboot/keepassxc#2421]
The given version number in the about info box is no correlating with the version number of the file i am downloading.

## Expected Behavior
If the user downloads the version 2.3.4 of keepassxc from the official website the about info box of this application should then say 2.3.4.

## Current Behavior
If the i downloadd the version 2.3.4 of keepassxc from the official website the about info box of this application says 2.3.1. The same thing happens if i install the version with apt from the official ppa. The connected Chrome App also says the version of keepassxc is 2.3.1.

## Possible Solution
Either the wrong version was uploaded or the version number was not changed in this release

## Steps to Reproduce (for bugs)
1. Download the keepassxc 2.3.4 version from https://keepassxc.org/download/
2. Check the about info box and there it says 2.3.1

## Context
I have another problem with keepassxc. Now i am confused if i even have the most recent version and do not want to open a new issue as long as i'm unsure of that.

## Debug Info
KeePassXC - Version 2.3.1
Revision: 2fcaeea

Libraries:
- Qt 5.9.5
- libgcrypt 1.8.1

Operating system: Ubuntu 18.04.1 LTS
CPU architecture: x86_64
Kernel: linux 4.15.0-38-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by droidmonkey** [comment]
You are absolutely running 2.3.1, the 2.3.4 revision is 6fe821c. Which file did you download exactly?

**Comment by Teifun2** [comment]
I tried multiple sources (PPA and AppImage) 

AppImage File Name: 

KeePassXC-2.3.4-x86_64.AppImage
Running it with: ./KeePassXC-2.3.4-x86_64.AppImage


Apt install log: 
Get:1 http://ppa.launchpad.net/phoerious/keepassxc/ubuntu bionic/main amd64 keepassxc amd64 2.3.4-1ppa1~bionic1 [2'688 kB]
Fetched 2'688 kB in 3s (980 kB/s)      
(Reading database ... 226867 files and directories currently installed.)
Preparing to unpack .../keepassxc_2.3.4-1ppa1~bionic1_amd64.deb ...
Unpacking keepassxc (2.3.4-1ppa1~bionic1) over (2.3.1+dfsg.1-1) ...
Processing triggers for mime-support (3.60ubuntu1) ...
Processing triggers for desktop-file-utils (0.23-1ubuntu3.18.04.1) ...
Setting up keepassxc (2.3.4-1ppa1~bionic1) ...

Running with: keepassxc

**Comment by droidmonkey** [comment]
Yes, the default setting is to only allow one instance at a time running. The running instance will be brought to the front in that case. You are probably still running the old version.

**Comment by Teifun2** [comment]
Ok i found the problem. There was indeed still a process keepassxc running which i was not able to access. (after keepassxc was removed with apt). This instance was still connected to Chrome (I think, because there was another process of chrome related to keepassxc). Maybe chrome kept the instance alive?

After installing the keepassxc 2.3.4 and then starting it with the normal command it seems it just showed me the old instance which was still running. I dont know how this can happen.

**Comment by phoerious** [comment]
Glad you got it sorted out.
