### ISSUE TITLE
build from keepassxc-2.3.4-src.tar.xz archive fails in RHEL (3.10.0-862.14.4.el7.x86_64)

### ISSUE THREAD

**Issue by vasco65** [keepassxreboot/keepassxc#2423]
Downloaded the source and tried to compile it
-rw-rw-r--. 1 vasco vasco 4137176 Oct 26 15:46 keepassxc-2.3.4-src.tar.xz

```
$ cd ~/src
$ tar xf ~/Downloads/keepassxc-2.3.4-src.tar.xz
$ cd keepassxc-2.3.4
$ cd src
$ mkdir build
$ cd build
$ cmake -DWITH_XC_ALL=ON -DCMAKE_BUILD_TYPE=Release ..
```

## Current Behavior

cmake is producing an error, it looks like it is related to cmake version, but I think I have the correct version (nothing new is available on my repositories, if I need something new I'm out of luck)

```
$ cmake --version
cmake version 2.8.12.2
```

```
$ cmake -DWITH_XC_ALL=ON -DCMAKE_BUILD_TYPE=Release ..
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
CMake Error at CMakeLists.txt:21 (include):
  include could not find load file:

    GetGitRevisionDescription


CMake Error at CMakeLists.txt:22 (get_git_head_revision):
  Unknown CMake command "get_git_head_revision".


CMake Warning (dev) in CMakeLists.txt:
  No cmake_minimum_required command is present.  A line of code such as

    cmake_minimum_required(VERSION 2.8)

  should be added at the top of the file.  The version specified may be lower
  if you wish to support older CMake versions for this project.  For more
  information run "cmake --help-policy CMP0000".
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring incomplete, errors occurred!

See also "/home/ptiti034/src/keepassxc-2.3.4/src/build/CMakeFiles/CMakeOutput.log".
```

**Running cmake with -Wno-dev**

```
$ cmake -Wno-dev -DWITH_XC_ALL=ON -DCMAKE_BUILD_TYPE=Release ..
CMake Error at CMakeLists.txt:21 (include):
  include could not find load file:

    GetGitRevisionDescription


CMake Error at CMakeLists.txt:22 (get_git_head_revision):
  Unknown CMake command "get_git_head_revision".


-- Configuring incomplete, errors occurred!
See also "/home/ptiti034/src/keepassxc-2.3.4/src/build/CMakeFiles/CMakeOutput.log".
```

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Debug Info

[CMakeOutput.log](https://github.com/keepassxreboot/keepassxc/files/2520028/CMakeOutput.log)

KeePassXC - 2.3.4
Revision: REVISION

Libraries:
- LIBS

Operating system: RHEL 7.5
CPU architecture: x86_64
Kernel: 3.10.0-862.14.4.el7.x86_64

Enabled extensions:
- EXTENSIONS

**Comment by droidmonkey** [comment]
I believe you need to have git installed which adds this cmake command

**Comment by vasco65** [comment]
hummm, that's quite possible. I will give it a try, thank you.
But I wander if there is a way to compile without having to talk to github.

**Comment by phoerious** [comment]
Git, not GitHub.

**Comment by vasco65** [comment]
Not that, I just checked it a I do have git installed.

$ sudo yum info git

Installed Packages
Name        : git
Arch        : x86_64
Version     : 1.8.3.1
Release     : 14.el7_5
Size        : 22 M
Repo        : installed
From repo   : RHEL-75-x86_64-updates
Summary     : Fast Version Control System
URL         : http://git-scm.com/
License     : GPLv2
Description : Git is a fast, scalable, distributed revision control system with an
            : unusually rich command set that provides both high-level operations
            : and full access to internals.
            :
            : The git rpm installs the core tools with minimal dependencies.  To
            : install all git packages, including tools for integrating with other
            : SCMs, install the git-all meta-package.

Maybe some specific option is missing.

**Comment by phoerious** [comment]
As far as I remember, builds don't work with CMake older than 3.1. Versions as old as 2.8 have various problems which make them incompatible with our build scripts. Please try upgrading CMake.

**Comment by vasco65** [comment]
Ok, I'll have to wait then, I have to use what's on the repositories.
Thank you.

**Comment by phoerious** [comment]
You can use our AppImage.
