### ISSUE TITLE
New Database wizard almost completely unreadable with KDE (Breeze Dark)

### ISSUE THREAD

**Issue by brainplot** [keepassxreboot/keepassxc#2424]
The New Database wizard ignores the system's Qt theme. I'm using Archlinux, with KDE Plasma 5.14.2 (Breeze Dark theme).

Here's what the wizard looks like:

![keepassxc-no-click](https://user-images.githubusercontent.com/28014843/47583347-7306ae80-d957-11e8-85db-487589d3d449.png)

It's hard to see, but the first text field (i.e. "Database name") contains the word "Passwords", which is there by default. In fact, if I double click on it, I can see it:

![keepassxc-double-click](https://user-images.githubusercontent.com/28014843/47583413-af3a0f00-d957-11e8-829b-26dd72d59ae7.png)

Here are some more pictures:

![menu-1](https://user-images.githubusercontent.com/28014843/47583584-34bdbf00-d958-11e8-90ae-8cca3eea4062.png)
![menu-2](https://user-images.githubusercontent.com/28014843/47583625-4ef79d00-d958-11e8-877e-e930e1f51f1b.png)
![example-1](https://user-images.githubusercontent.com/28014843/47583756-aac22600-d958-11e8-9d43-3c578b7e5bc1.png)
![example-2](https://user-images.githubusercontent.com/28014843/47583757-ab5abc80-d958-11e8-82a8-cabd2dd0a4d2.png)

Though this section partially respects the system's theme:

![example-3](https://user-images.githubusercontent.com/28014843/47583758-ab5abc80-d958-11e8-872b-95e3154516d5.png)

## Debug Info
KeePassXC - Version 2.4.0-snapshot
Build Type: Snapshot
Revision: 7729570

Libraries:
- Qt 5.11.2
- libgcrypt 1.8.3

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 4.18.16-arch1-1-ARCH

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- YubiKey

**Comment by phoerious** [comment]
That's a bug in either Breeze or QWizard or both.

**Comment by brainplot** [comment]
I downloaded the wizard examples provided by Qt and tried to run all of them. They all look fine.

### First Example
![wizard-1](https://user-images.githubusercontent.com/28014843/47588655-317dff80-d967-11e8-8283-238d7423501e.png)
![wizard-2](https://user-images.githubusercontent.com/28014843/47588656-317dff80-d967-11e8-9f3f-723ffedf21bc.png)

### Second Example
![wizard-3](https://user-images.githubusercontent.com/28014843/47588704-4fe3fb00-d967-11e8-8bd7-b9de54ec1a4e.png)
![wizard-4](https://user-images.githubusercontent.com/28014843/47588705-507c9180-d967-11e8-8835-77400e6cf078.png)
![wizard-5](https://user-images.githubusercontent.com/28014843/47588706-507c9180-d967-11e8-81ec-17f97ab00c6c.png)

### Third Example
![wizard-6](https://user-images.githubusercontent.com/28014843/47588717-5e321700-d967-11e8-86ab-425665e9826c.png)
![wizard-7](https://user-images.githubusercontent.com/28014843/47588718-5e321700-d967-11e8-842d-78790b7b042b.png)
![wizard-8](https://user-images.githubusercontent.com/28014843/47588719-5e321700-d967-11e8-8474-3717c10bd5aa.png)

I don't think this is related to Breeze or Qt. I've got the source code of these three examples, if it can be useful somehow.

**Comment by phoerious** [comment]
The example you downloaded uses a different wizard style.
