### ISSUE TITLE
Minimize on startup ignored in gnome-shell (wayland session)

### ISSUE THREAD

**Issue by 4javier** [keepassxreboot/keepassxc#2432]
When launched after checking the minimize on startup option, window is shown anyway.

I'd expect the program to stay quiet into the taskbar.
It doesn't act different in anyway when the option is checked or not.

I was trying to launch the program on gnome login reading password by seahorse (gnome keyring manager) and keyfile both from cli. It works but I got this problem.

If I enable minimize in tray option, the program simply doesn't show up at all because gnome-shell lacks tray.

KeePassXC -2.3.4

Operating system: Arch Linux
CPU architecture: x86_64
Gnome shell 3.30.1

**Comment by droidmonkey** [comment]
This was fixed for 2.4 in #2402
