### ISSUE TITLE
Autologin database at startup

### ISSUE THREAD

**Issue by tiotrom** [keepassxreboot/keepassxc#2434]
So I have Linux with encrypted ssd and a normal user password. 2 password to add in order to boot my laptop. Now, I also have to input a 3rd for KeePassXC :D so I was wondering is there any way I can make it so KeePassXC opens up my database on startup? For me it is kinda annoying to do that everytime I open my laptop.

Also, I am trying to make people move from LastPass to KeePassXC but they are really annoyed at this too. They say they don't want complicated things like that, they want something that remembers passwords and they forget about it and just works.

I feel like this is a little thing that if 'fixed' would improve KeePassXC. Was this discussed before? Cheers!

**Comment by droidmonkey** [comment]
Discussed in #1405 and #1267
