### ISSUE TITLE
Startup autopass

### ISSUE THREAD

**Issue by Geniusssmit** [keepassxreboot/keepassxc#2442]
On keepass i was able to use script to add program on startup and autologin in my database

@echo off KeePass DB #1 without a keyfile
SET DATABASE="D:\save2\My google drive\MyKeePassFolder\MyMain.kdbx"
SET PASSWORD_ENC="____pass____"
START /min "" "D:\save2\KeePass Password Safe 2\KeePass.exe" %DATABASE% -pw-enc:%PASSWORD_ENC%

## Expected Behavior
Is there any equivalent in KeePassXC?

**Comment by droidmonkey** [comment]
Yes, --pw-stdin, but it is challenged on Windows. This will be fixed for 2.4

**Comment by Geniusssmit** [comment]
pls add this like option and startup in tray.
with keepass it's working but still only minimizes to taskbar not tray and that's annoying

**Comment by droidmonkey** [comment]
@Geniusssmit you can minimize to tray on startup if you enable:

* Minimize windows at application startup
* Show a system tray icon
* Hide window to system tray when minimized
