### ISSUE TITLE
"Auto-Type" feature not working

### ISSUE THREAD

**Issue by tromlet** [keepassxreboot/keepassxc#2448]
## Expected Behavior
When I clicked the "Perform Auto-Type" button on the top toolbar, I would switch to the last window in focus, and begin typing wherever I had left the mouse cursor in that window.

## Current Behavior
When I click the "Perform Auto-Type" button on the top toolbar, nothing really happens. Sometimes it switches to the last window in focus, but nothing seems to type almost ever - even when I can see my mouse cursor, it just sits there, blinking.

## Possible Solution
I recently upgraded to macOS Mojave (looking forward to that dark-themed Qt goodness), and the first time I launched KeePassXC after the upgrade _and tried to initiate an auto-type_, I got some prompt to set something in my keyboard settings in System Preferences. I don't know what it was exactly, I might've missed an important step and I don't remember what it was telling me to do, somehow I clicked past the windows and managed to close everything before I accomplished the prompt and now I can't get it back. :(

## Debug Info
KeePassXC - Version 2.3.4
Revision: 6fe821c

Libraries:
- Qt 5.9.3
- libgcrypt 1.8.2

Operating system: macOS 10.14
CPU architecture: x86_64
Kernel: darwin 18.0.0

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

Operating system: OS
CPU architecture: ARCH
Kernel: KERNEL

Enabled extensions:
- EXTENSIONS

**Comment by droidmonkey** [comment]
You have to enable KeePassXC in the accessibility settings.

**Comment by tromlet** [comment]
Bless you. 🙏
