### ISSUE TITLE
Yubikey support for keepassxc-cli

### ISSUE THREAD

**Issue by tsumare** [keepassxreboot/keepassxc#2451]
keepassxc-cli has no option to open a database which requires a Yubikey challenge.

## Expected Behavior
There is no way to use keepassxc-cli with a Yubikey protected database.

## Current Behavior
Only passwords and key files are accepted.

## Possible Solution
Add a commandline flag indicating what key or slot to use, which will enable Yubikey challenge/response authentication for the command line tool.

## Steps to Reproduce (for bugs)
Attempt to open a Yubikey protected database using keepassxc-cli

## Context
I am unable to use keepassxc-cli to handle merging or backup exports (which I would then GPG encrypt to an offline key) once a Yubikey is enabled.

## Debug Info
$ keepassxc-cli -v
2.3.4

Operating system: Ubuntu Xenial
CPU architecture: amd64
Kernel: 4.15.0-36-generic

Enabled extensions:
- No non-default plugins.

**Comment by louib** [comment]
This was implemented by https://github.com/keepassxreboot/keepassxc/pull/3416

**Comment by lostapathy** [comment]
Many thanks, all!
