### ISSUE TITLE
[Qt Bug] Diacritics work incorrectly when entering kdbx master database passwords

### ISSUE THREAD

**Issue by peio42** [keepassxreboot/keepassxc#2452]
Some diacritics, in particular the characters ^ ¨ or ` (from French keyboard), can't easily be used as a password characters when opening a kdbx database (at least on Mac OS).

## Expected Behavior
When the password is asked to open a kdbx database, the key '^' (optionaly + space) should give the character '^'. The same for combinations, for exemple '^' then 'e' should give 'ê', '^' + 'i' => 'î' and so on.

## Current Behavior
When the password is entered and not visible, the key '^' (optionaly + space) gives a space. For combinations, the character without the accent is given ('^' + 'e' => 'e').
However, the right character is given when typed while the field is visible, this is what I use as a workaround. But in general, I don't like to type passwords when they are visible on the screen...

## Steps to Reproduce (for bugs)
1. Install KeepassXC 2.3.4 (but also previous versions had the problem)
2. Try to open any kdbx database
3. In the master password field, type '^', '¨' or other diacritics (may require foreign layout keyboard)
4. Clic on the eye on the right of the field : The characters are incorrect
5. Try the same diacritics now, they should appear correctly

## Debug Info
KeePassXC - 2.3.4

Operating system: Mac OS (High Sierra or Mojave)
CPU architecture: Intel
Keyboard Layout: AZERTY (French)

**Comment by cybermidget** [comment]
Issue still affects KeePassXC 2.4.9 on MacOS Mojave, regardless of active keyboard layout

**Comment by karlhorky** [comment]
Also seeing this problem. Is this a particularly complex issue to fix?

**Comment by droidmonkey** [comment]
This is probably not our issue to fix, it is very likely a Qt issue.

**Comment by karlhorky** [comment]
Ah ok thanks for the info, I'll troll around upstream to see if I can find anything.

**Comment by droidmonkey** [comment]
Confirmed, it is tracked by this issue report: https://bugreports.qt.io/browse/QTBUG-73363

**Comment by karlhorky** [comment]
Ah nice searching, faster than me :) Yeah that looks pretty promising.

**Comment by karlhorky** [comment]
Created a Qt Account and voted for the issue.

**Comment by kafran** [comment]
I'm also facing this problem. I have two machines, one with Ubuntu 19.04 and another with Ubuntu 19.10.

On Ubuntu 19.04 I have KeePassXC-2.4.3-x86_64.AppImage which *does not have this problem*. 

On the machine with Ubuntu 19.04 I have KeePassXC-2.5.3-x86_64.AppImage on which I can't type characters like ~ or ^ and others.

This only happens when the password is hidden and the characters needs another key to be formed: `[~] + [space] = ~` or `[^] + [space] = ^` or `[~] + [a] = ã`, etc. But if I hit `[alt gr] + [~]` it works, the character ~ is printed on the hidden password.

**Comment by droidmonkey** [comment]
Its not KeePassXC......... Its a Qt bug

**Comment by robpower** [comment]
Confirmed on Ubuntu 20.04, QT 12.8. Referenced upstream.

**Comment by mikezeduke** [comment]
Up to Ubuntu 18.04.5, worked fine.  After **upgrading to** Ubuntu **20.04.1** and using keepassxc Version: **2.4.3**+dfsg.1-1build1, I experience problems with accents in the master password as described.

**Comment by The4thLaw** [comment]
To anyone wondering: the upstream issue was closed as "Won't Do" and it seems to be related to dead keys and ibus.
