### ISSUE TITLE
Support XML import/export

### ISSUE THREAD

**Issue by tsumare** [keepassxreboot/keepassxc#2458]
Please provide a method for exporting and importing full unencrypted copies of the database for external backup.

## Expected Behavior
Export or import the unencrypted XML database information.

## Current Behavior
`keepass-cli extract` will export this XML, but there is no equivalent import, and the GUI has neither option.  At this time it is necessary to restore such an XML using KeePass 2.0 (I have not confirmed compatibility), and impossible to produce it for the databases that may need it most (#2451).

Exporting and importing CSV files is possible, but discards all metadata including advanced attributes, which can contain critical information such as TOTP secrets or other user data.

## Possible Solution
Add an additional import and export format: KeePass XML.

## Steps to Reproduce (for bugs)
N/A

## Context
The lack of this feature prevents me from enabling YubiKey auth, as I am unable to make secondary backups (encrypted to an offline GPG key) to use if my Yubikey is lost or destroyed.  This would deny me access to my passwords (including online store and banking passwords) until I was able to receive another YubiKey and reprogram my HMAC key backup.

Having this feature would allow me to use my YubiKey for additional security and still know that I could still access the passwords if it was lost (after I got my backup GPG private key out of the safe).

## Debug Info
KeePassXC - Version 2.3.4
Revision: 6fe821c

Libraries:
- No nondefault libraries

Operating system: All
CPU architecture: All
Kernel: All

Enabled extensions:
- No nondefault extensions

**Comment by tsumare** [comment]
Looking again, I see that this is somewhat a duplicate of #2341 (though that refers only to the CLI).

**Comment by droidmonkey** [comment]
This would be rather trivial to implement (both export and import).

**Comment by phoerious** [comment]
XML export is possible via the CLI. We don't have an import at the moment.

**Comment by tsumare** [comment]
It seems that there is already XML import/export in the backend code:
https://github.com/keepassxreboot/keepassxc/blob/develop/src/format/KdbxXmlWriter.cpp
https://github.com/keepassxreboot/keepassxc/blob/develop/src/format/KdbxXmlReader.cpp

Perhaps "Unencrypted XML" can simply be added as a "Save As"/"Open" filetype?

**Comment by HenrikBengtsson** [comment]
Adding a related feature request: support for exporting a *single entry* to XML and importing from such a single-entry XML.

**Comment by AlFalahTaieb** [comment]
> XML export is possible via the CLI. We don't have an import at the moment.

Is there a way to export the databse in CSV ?( with the CLI )

**Comment by bmachek** [comment]
This would be great.
I agree there's a need for doing backups when using a hardware token.

**Comment by homonto** [comment]
yes, import from XLM please! ;-)

**Comment by jsachs** [comment]
@droidmonkey is this on the roadmap anytime soon? If not, do you know if anyone has taken a crack at it yet?

**Comment by droidmonkey** [comment]
On the roadmap, but not a priority
