### ISSUE TITLE
Can't input the tilde character (~) on the password field on macOS

### ISSUE THREAD

**Issue by jorgegarciadev** [keepassxreboot/keepassxc#246]
Can't input the tilde character ```~``` on the password field in the password field for opening the database on macOS Sierra. I've to click the eye icon and then type the password.

## Expected Behavior
Type the tilde character ```~``` on the password field.

## Current Behavior
Can't input the tilde character ```~``` on the password field

## Steps to Reproduce (for bugs)

1. Open KeepassXC on macOS Sierra
2. Type a password containing the character ```~```

## Context

Can't open the database if the password field is not changes to visible

## Your Environment

* KeePassXC version/commit used:  8a3ac7a26e7d6e2355dc1eb4829bdce96ded2a27
* Qt version (e.g. Qt 5.3): Qt 8.5
* Compiler (e.g. Clang++3.6.0): clang-800.0.42.1
* Operating System and version: macOS Sierra 10.12.3

**Comment by phoerious** [comment]
What keyboard map/layout are you using? I think this may have to do something with dead keys.

**Comment by jorgegarciadev** [comment]
Hi phoerious, It's Spanish ISO.

**Comment by phoerious** [comment]
Does it still occur when you change your keyboard layout to something without dead keys?

**Comment by jorgegarciadev** [comment]
No, changed to English US and now I can type the ``~``

**Comment by jorgegarciadev** [comment]
I have KeepassCX installed on Ubuntu 16.04 and there I can type it. And I can type the ```~``` on KeepassX.

**Comment by phoerious** [comment]
I guess this is a Qt bug. Probably not this one https://bugreports.qt.io/browse/QTBUG-33557 but something like it. We don't do anything special with the password input field.

**Comment by jorgegarciadev** [comment]
I've similar problems with programs that use Webkit. Well, I will change the password then.
Thank you @phoerious
