### ISSUE TITLE
Idea: Pixmap scaling on 4K.

### ISSUE THREAD

**Issue by Syping** [keepassxreboot/keepassxc#2468]
I have used Qt env values to scale my current KeePassXC 2.3.4 version, after downloading Source code i had same behaviour as before, i saw a issue about High DPI Pixmap so i tried to change the code a bit.

## Expected Behaviour

KeePassXC at main.cpp uses:
`QApplication::setAttribute(Qt::AA_UseHighDpiPixmaps);`

![Icons scaled](https://user-images.githubusercontent.com/9694335/48301399-cb0fea00-e4ed-11e8-8105-4cbed167563c.png)

## Current Behaviour

KeePassXC doesn't use the line at Expected Behaviour, so result are pixelated icons.

![Icons not scaled](https://user-images.githubusercontent.com/9694335/48301406-090d0e00-e4ee-11e8-8482-e6122e2fd69f.jpg)

## Possible Solution

Using the line included in Expected Behaviour.
Other things related to High PDI: It would be nice when KeePassXC download favicons they are different size than 16x16, best would be if KeePassXC store all sizes, or ask the user which size should be stored.
Seems like toolbar icons need some work too. Probably just copy them from Oxygen Icon Theme the matching size?

## Context

Using KeePassXC on 4K Display.

## Debug Info

KeePassXC - 2.3.4 (compiled master for example)

Operating system: Windows 10
CPU architecture: amd64
Kernel: 1703

**Comment by droidmonkey** [comment]
This is fixed already in upcoming 2.4 release.

**Comment by Syping** [comment]
Current scaling behaviour scale widgets etc. but not pixmaps. 
```
#if QT_VERSION >= QT_VERSION_CHECK(5, 6, 0)
    QApplication::setAttribute(Qt::AA_EnableHighDpiScaling);
#endif
```

I meant to include Pixmap scaling like that.
```
#if QT_VERSION >= QT_VERSION_CHECK(5, 6, 0)
    QApplication::setAttribute(Qt::AA_EnableHighDpiScaling);
    QApplication::setAttribute(Qt::AA_UseHighDpiPixmaps);
#endif
```

**Comment by phoerious** [comment]
I prefer crisp nearest neighbour scaling over blurry icons and we want to change the icons anyway.
