### ISSUE TITLE
Chrome's password manager collides with browser integration

### ISSUE THREAD

**Issue by zkab** [keepassxreboot/keepassxc#2471]
## Expected Behavior
Browser integration should work with Chrome

## Current Behavior
The generated password is not choosen but it takes the password that is stored in Chrome

## Context
Obviously I can't use browser integration

## Debug Info
KeePassXC - 2.3.4
Revision: 6fe821c

Libraries:
- LIBS
- Qt 5.9.5
- libgcrypt 1.8.1

Operating system: Ubuntu 18.04.1 LTS
CPU architecture: x86_64
Kernel: linux 4.15.0-38-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by varjolintu** [comment]
Is it necessary for you to use Chrome's own password manager and KeePassXC at the same time? I doubt those will work together well enough..

**Comment by varjolintu** [comment]
Possible related issue: https://github.com/keepassxreboot/keepassxc-browser/issues/229

**Comment by droidmonkey** [comment]
This is a browser plugin issue (if it is actually an issue), I have only experienced this occasionally and I doubt we can do anything about it.
