### ISSUE TITLE
Feature Request: Highlight used custom icon

### ISSUE THREAD

**Issue by AOne-T** [keepassxreboot/keepassxc#2472]
I think it would be helpful to highlight current custom icon in the list, because when you have 200+ of them - it is hard to find for another entry for the particular site.

**Comment by droidmonkey** [comment]
Please post a screenshot because it highlights the icon for me.

**Comment by AOne-T** [comment]
![screen 2018-11-12 17-40-59](https://user-images.githubusercontent.com/2842078/48354478-e5d78f80-e6a2-11e8-9f17-89a5d7693092.png)
![screen 2018-11-12 17-42-02](https://user-images.githubusercontent.com/2842078/48354483-e96b1680-e6a2-11e8-9cc3-28ec10b84ca6.png)
Also I use Ubuntu 18.04

**Comment by droidmonkey** [comment]
Does this happen with any other icon besides pluralsight? It looks like the icon is selected (it is darker on the interior) but the border doesn't show it. I do agree that the selection indication is very faint and hard to pick up when there are a ton of icons.

**Comment by AOne-T** [comment]
I checked randomly - all the same. I also noticed on the icons that I remember location what you were talking about. It is hard to find with it.
I also have checked on MacOS 10.14. It is a little bit helpful because it has the mark under the icon. But it needs time to find it.
![screen 2018-11-13 12-27-05](https://user-images.githubusercontent.com/2842078/48403966-3d780880-e740-11e8-9c7e-b97151270743.png)

**Comment by alexanderadam** [comment]
There is also no highlighting when the Icon already exists. It's just showing the message "Custom icon already exists". I would expect it to highlight the icon in that case as well.

**Comment by DJCrashdummy** [comment]
i'm afraid this highly depends on the DE, e.g. in MATE it behaves as it should... also the background is tinted. :expressionless:

**Comment by phoerious** [comment]
Should be fixed in #4410.
