### ISSUE TITLE
Autofill not working after MacOS Mojave Update

### ISSUE THREAD

**Issue by wolv-dev** [keepassxreboot/keepassxc#2473]
## Expected Behavior

1. Selecting entry in KeepassXC
2. Pressing CMD + V
3. Focus changes to the username field
4. the username/password enters automatically and will be sent

## Current Behavior

1. Selecting entry in KeepassXC
2. Pressing CMD + V
3. Focus changes to the username field
4. Nothing more happens

## Steps to Reproduce (for bugs)

1. Selecting entry in KeepassXC
2. Pressing CMD + V

## Debug Info

KeePassXC - Version 2.3.4
Revision: 6fe821c

LIBS:
- Qt 5.9.3
- libgcrypt 1.8.2

OS: macOS 10.14.1
CPU-Architectur: x86_64
Kernel: darwin 18.2.0

Activated Plugins:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by droidmonkey** [comment]
You need to add KeePassXC to the accessibility applications.

**Comment by wolv-dev** [comment]
Indeed! App was deleted from the list.
Thank you very much!
