### ISSUE TITLE
Unnecessary socket in /tmp?

### ISSUE THREAD

**Issue by pganssle** [keepassxreboot/keepassxc#2476]
When I was looking around in `/tmp` with KeepassXC open but the database locked, I noticed that `keepass` creates two files, `keepassxc-username.lock` and `keepassxc-username.socket`.

I'm guessing the latter is a unix domain socket, which I gather is related to the support for browser integration. I have specifically turned off browser integration because I am deeply suspicious of anything network-related touching my password store, but the socket is still created whenever KeePassXC is started.

I imagine that this socket is created at process open and only ever connected to if you need it, but out of an abundance of caution, I would prefer it if turning off browser integration prevented the creation of the socket entirely, or if there were a "never touch the network" mode for the paranoid among us.

## Steps to Reproduce (for bugs)
1. Open KeePassXC
2. `ls -l /tmp | grep keepassxc`

**Comment by droidmonkey** [comment]
I recommend using the snap if you can, you can't possibly use browser extension with it. What you are seeing the /tmp is the single instance socket. There is no networking involved with that (or with the browser service socket), its all local file system. 

https://github.com/keepassxreboot/keepassxc/blob/6fe821c30ec747e7fda0a8abe75d774d61a21054/src/gui/Application.cpp#L103-L126

**Comment by pganssle** [comment]
@droidmonkey I might quibble with the definition of "local file system" in this case, I think you have a server listening on a unix domain socket. From my understanding, that's not anything to do with the file system other than the domain socket being assigned a path there, it's inter-process communication using TCP that happens on the local machine with requests processed directly by the kernel.

I guess this application is broken down into a service and a UI that queries that service? 🤔

Not sure how I feel about that, but at least it seems like it *is* absolutely necessary without a major refactoring, so I'll close this issue. Thanks for the response @droidmonkey!

**Comment by droidmonkey** [comment]
You are correct regarding the use of a socket, but it is done through a file system pointer managed by the kernel (at least on *nix systems). I was a little too broad in my statement.

We are not communicating with a service. This is just a very portable (read cross-platform) and easy way to implement single instance. When another instance of KeePassXC is run, it first checks to see if it can create a socket. If it cannot, then it assumes there is already another running instance and sends a message to that instance through the socket. This message triggers the running instance to come to the foreground.

**Comment by phoerious** [comment]
This socket's got nothing to do with networking and is not a TCP socket.
