### ISSUE TITLE
Usage statistic (use count) about passwords

### ISSUE THREAD

**Issue by rugk** [keepassxreboot/keepassxc#2477]
## Expected Behavior

It would be great to see some generic stats for each password entry (optionally, of course). I mean you already have a history and have some stats, but one thing, which I like very much is missing:
* how much I used a password

So I can e.g. see what unused accounts I have and clean them up.
Or just see some stats on what accounts I login most often.
So obviously, I also want to sort my entries by that number.

A similar nice feature is e.g. that you can see how the "visit count" in browser histories.

## Current Behavior

I only have "last used", "created" and so on, but no counter. :cry: 

## Possible Solution

Probably just count the accesses and safe it as a custom field. So other KeePass implementations can also implement it then. :smile: 

You may probably not want to update the "last changed" date in this case, as it would obviously quite useless as it is always updated on access then.

## Context

I really like that feature in browsers. You can see unused websites/account or just check how many you use often or so.

**Comment by droidmonkey** [comment]
Covered under #551. Also you can do a search for a specific password using `pass:<password>` and see all entries that contain that (or a fragment of) password.
