### ISSUE TITLE
Windows Autotype

### ISSUE THREAD

**Issue by roccr** [keepassxreboot/keepassxc#248]
Can't use Autotype on Windows 7 64bit. No menu entry for it.

## Expected Behavior

Recording to the website there should be the autotype feature on every plattform. So it is on MacOS. The autotype extensions is listet aswell:

![grafik](https://cloud.githubusercontent.com/assets/11852470/22415671/89780e66-e6c9-11e6-8c79-4e9554c31e0d.png)

## Your Environment

* KeePassXC version/commit used: 2.1.0 (downloaded from the website)
* Qt version (e.g. Qt 5.3): 5.6.2
* Operating System and version: Windows 7 64bit German Keyboard Layout

**Comment by TheZ3ro** [comment]
In Settings there isn't the option to set an Autotype keyboard shortcut?

**Comment by roccr** [comment]
I'm afraid not as you can see in the screen shots of the Tools -> Settings Menu

![grafik](https://cloud.githubusercontent.com/assets/11852470/22416827/1a28b7c4-e6d1-11e6-9ac0-93a1aa1e5b54.png)

![grafik](https://cloud.githubusercontent.com/assets/11852470/22416832/226f02bc-e6d1-11e6-89b8-67ef3f3cb18d.png)

**Comment by phoerious** [comment]
This issue was fixed a while ago (see #208). Please re-download the binaries and try again.
