### ISSUE TITLE
Tray icon will not change if base locked from browser extension

### ISSUE THREAD

**Issue by e-pirate** [keepassxreboot/keepassxc#2480]
Tray icon will not change to "locked" (grey icon with a lock) and remain green as for unlocked state if base locking initiated from KeepAssXC-Browser extension. Icon changes if base locked from the KeepAssXC itself by pressing Ctrl-L or by timeout.

## Expected Behavior
Icon change to "locked" when base locked regardless of if it was locked from the program itself, or from browser extension.

## Current Behavior
Tray icon remain green "unlocked" if base locked from browser extension even if base is really locked.

## Steps to Reproduce (for bugs)
1. On unlocked base and connected browser extension, press "Lock database" red button with lock.
2. Database locks, but icon remains green like database is unlocked.

## Context
May make user think database is unlocked while in reality it is safe.

## Debug Info
KeePassXC - 2.3.4

Operating system: Gentoo Linux
CPU architecture: x86_64
Kernel: 4.14.78-gentoo

Enabled extensions:
KeePassXC-Browser - 2.3.4
Firefox - 60.0.3

**Comment by droidmonkey** [comment]
Confirmed! Good report, thank you.

**Comment by varjolintu** [comment]
I assume this is a situation where there is credentials found for the site? If you do this for an empty tab (for example) it works properly.

**Comment by droidmonkey** [comment]
This is also an issue on keepassxc side. The icon in the system tray remains green.

**Comment by e-pirate** [comment]
I've just tested with the tab, that does not have any associated credentials, not even an input fields. Unlocked DB on that tab from the extension and then locked it by pressing red button on the extension pop-up and no, icon remains green. It is clearly KeePassXC bug.

**Comment by varjolintu** [comment]
I can reproduce that yes. Is it intended behaviour that even if you change the tab to a locked database, the icon still stays green? If there are multiple databases open and you click the lock icon from the extension, only the active database is locked. But if you press the lock icon from KeePassXC it will lock all databases, and in that case the system tray icon change works as it should.

**Comment by e-pirate** [comment]
Not really. I have only one DB unlocked when I press red lock button in the extension window and the icon still remains green.

**Comment by varjolintu** [comment]
@e-pirate I was just wondering the intended behaviour of the tray icon. It stays also green if I have multiple databases in the tabs and only one of them is open (it doesn't have to be the active on).

**Comment by e-pirate** [comment]
In my case I had only one DB that was open before I locked it from extension and the icon remained green with no unlocked dbs at the point. IMHO, tray icon should turn grey in case all DBs are locked and remain green if one or more is open. This is pretty obvious, I suppose. The real question is what DBs should be locked when red lock button is pressed in extension? All opened DBs? Only current? I think user should decide what suits him more: an option mast me implemented in the KeePassXS browser integration settings. Something like a checkbox "Lock all databases". If checked, KeePassSX will lock all open databases on red lock button click, if not - only current. The checkbox should be checked by default.

**Comment by e-pirate** [comment]
Anyway, waiting for a fix. This thing is disturbing as hell. I have to wait for timeout or lock from the main process. Otherwise it make me feel naked only by the look of the icon :-)

**Comment by varjolintu** [comment]
https://github.com/keepassxreboot/keepassxc/pull/2491 fixed the issue.
