### ISSUE TITLE
Does not minimize at startup via autostart after fresh installation of arch/void with KDE

### ISSUE THREAD

**Issue by xtramon** [keepassxreboot/keepassxc#2481]
I installed arch/void as minimal as possibe and installed kde afterwards. when i put keepassxc in autostart it starts after login but not minimized.
the "minimize on startup" option is activated.
When i try it with a distro which comes with KDE preinstalled (tested it with Solus and Manjaro) it's working.

## Expected Behavior
should minimize on startup with autostart
## Current Behavior
starts after login but not minimized

## Possible Solution
i guess i miss a package somewhere but i don't know which

## Steps to Reproduce (for bugs)
1. install any distro whithout a DE
2. install KDE
3. install keepassxc and set "minimize on startup" option
4. put keepassxc into autostart
5. reboot and login.

Operating system: Arch/Void
CPU architecture: x86_64
Kernel: 4.19 / 4.18

**Comment by droidmonkey** [comment]
You probably need to add a delay at startup.

**Comment by cedricpim** [comment]
I am using Arch with i3, and I was starting keepassxc from the i3 configuration file. Even with the option "minimize on startup" set to true, it was still opening. After checking the suggestion from droidmonkey, I added a 5 second delay and it now starts minimized (as expected).

Not sure if it should be closed since it is more of a workaround, but it works for me, thanks :+1:

**Comment by droidmonkey** [comment]
Certainly we cannot overcome this from within KeePassXC itself. The delay or proper start ordering is the best bet. Going to close this.

**Comment by phoerious** [comment]
Do you have KeePassXC in your autostart and session restore on startup enabled? If yes, that's what's causing the problem. KeePassXC is started twice which causes the first instance to be brought to the foreground. It's a known issue with no obvious fix. I think this needs to be addressed in KDE. Their session restore is overall pretty flaky.

**Comment by cedricpim** [comment]
@phoerious not sure that's the case in my situation, since the sleep/delay fixed the issue. KeePassXC is only being started from i3. The current workaround works for me, but what is strange is that before the last update, it was working, but then I updated it and it changed its behaviour.
