### ISSUE TITLE
Crash on search or on selecting a group

### ISSUE THREAD

**Issue by AlexanderAmelkin** [keepassxreboot/keepassxc#2485]
## Expected Behavior

KeePassXC should not crash

## Current Behavior

When searching for an entry within a group, or when a group is clicked, KeePassXC 2.3.4 silently crashes.

## Possible Solution

No idea.

## Steps to Reproduce (for bugs)

I'm afraid this only happens with a certain group within my passwords file that I, for obvious reasons, cannot share. This does not happen with KeePass2Android or with an older KeePassXC 2.3.3 AppImage on Ubuntu 14.04.

1. Open a database from a webdav-mounted nextcloud folder using KeePassXC 2.3.4-0ppa1~trusty1 on Linux Mint 18.3 Sylvia with Cinnamon desktop.
2. Unlock the database using password
3. Select the group called 'Internet' or search for an entry located within that group.
4. Observe a silent crash.

Optionally run `keepassxc` from console, do the same and observe the following output:
```
$ keepassxc
QObject::startTimer: Timers cannot have negative intervals
Segmentation fault
```

## Debug Info

KeePassXC - Version 2.3.4
Revision: 6fe821c

Libraries:
- Qt 5.5.1
- libgcrypt 1.8.1

Operating system: Linux Mint 18.3
CPU Architecture: x86_64
Kernel: linux 4.10.0-42-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

## Additional debug info

See the attached `strace -f` log.
[keepass-strace.txt](https://github.com/keepassxreboot/keepassxc/files/2590684/keepass-strace.txt)

**Comment by droidmonkey** [comment]
Did you see the warning about crashes when you installed 2.3.4?

**Comment by AlexanderAmelkin** [comment]
Thanks. And no, I haven't seen the warning. I installed it using automatic package update from phoerious PPA for Ubuntu Xenial. Or maybe I was simply inattentive.

**Comment by droidmonkey** [comment]
Interesting, if you are using Phoerious PPA than you should not be using Qt 5
5.

**Comment by AlexanderAmelkin** [comment]
Why so? The PPA doesn't have any Qt packages and the dependensies are as follows:

```
$ sudo apt show keepassxc
Package: keepassxc
Version: 2.3.4-0ppa1~xenial1
Priority: optional
Section: utils
Maintainer: KeePassXC Team <team@keepassxc.org>
Installed-Size: 12,8 MB
Depends: libargon2-0, libc6 (>= 2.14), libgcrypt20-18 (>= 1.8.0-0), libqt5core5a (>= 5.5.0), libqt5dbus5 (>= 5.0.2), libqt5gui5 (>= 5.3.0) | libqt5gui5-gles (>= 5.3.0), libqt5network5 (>= 5.0.2), libqt5widgets5 (>= 5.4.0), libqt5x11extras5 (>= 5.1.0), libsodium23, libstdc++6 (>= 5.2), libx11-6, libxi6, libxtst6, libykpers-1-1 (>= 1.12.0), zlib1g (>= 1:1.1.4)
Conflicts: keepassxc-beta (<< 2.4.0)
Replaces: keepassxc-beta (<< 2.4.0)
Download-Size: 2 657 kB
APT-Manual-Installed: yes
APT-Sources: http://ppa.launchpad.net/phoerious/keepassxc/ubuntu xenial/main amd64 Packages
Description: KeePass Cross-Platform Community Edition
 KeePassXC is a community fork of KeePassX, a native
 cross-platform port of KeePass Password Safe, with
 the goal to extend and improve it with new features
 and bugfixes to provide a feature-rich, fully
 cross-platform and modern open-source password manager.
```

The default qt5 for Linux Mint 18.3 is 5.5.1.

**Comment by droidmonkey** [comment]
Ah I thought the PPA brought it's own qt as well.

**Comment by phoerious** [comment]
No, the PPA uses system libs. But the AppImage ships its own.

**Comment by AlexanderAmelkin** [comment]
I now use a snap package and it works without crashing. However on my Russian account with `/home/user/Desktop` called `/home/user/Рабочий стол` the following message appears on startup:

```
$ snap run keepassxc
/snap/keepassxc/49/bin/desktop-launch: line 161: $'\321\201\321\202\320\276\320\273': command not found
```
After that, it takes a loooooong time for KeepassXC to actually start, and then when navigating the entries I get this on console:

```
propsReply "An AppArmor policy prevents this sender from sending this message to this recipient; type=\"method_call\", sender=\":1.708\" (uid=1000 pid=27311 comm=\"keepassxc \") interface=\"org.freedesktop.DBus.Properties\" member=\"GetAll\" error name=\"(unset)\" requested_reply=\"0\" destination=\"org.freedesktop.NetworkManager\" (uid=0 pid=1110 comm=\"/usr/sbin/NetworkManager --no-daemon \")"
nmReply "An AppArmor policy prevents this sender from sending this message to this recipient; type=\"method_call\", sender=\":1.708\" (uid=1000 pid=27311 comm=\"keepassxc \") interface=\"org.freedesktop.NetworkManager\" member=\"GetDevices\" error name=\"(unset)\" requested_reply=\"0\" destination=\"org.freedesktop.NetworkManager\" (uid=0 pid=1110 comm=\"/usr/sbin/NetworkManager --no-daemon \")"
"Object path cannot be empty"
QObject::startTimer: Timers cannot have negative intervals
WARNING Qt AtSpiAdaptor: Accessible invalid:  QAccessibleInterface(0x5561368f1fd0 invalid) "/org/a11y/atspi/accessible/2147484697"
WARNING Qt AtSpiAdaptor: Accessible invalid:  QAccessibleInterface(0x556136933ac0 invalid) "/org/a11y/atspi/accessible/2147484714"
WARNING Qt AtSpiAdaptor: Accessible invalid:  QAccessibleInterface(0x556136af3960 invalid) "/org/a11y/atspi/accessible/2147484729"
WARNING Qt AtSpiAdaptor: Accessible invalid:  QAccessibleInterface(0x5561368f2d70 invalid) "/org/a11y/atspi/accessible/2147484750"
WARNING Qt AtSpiAdaptor: Accessible invalid:  QAccessibleInterface(0x556136934290 invalid) "/org/a11y/atspi/accessible/2147484765"
```

Also, the Firefox plugin doesn't work with the snap package. :(
