### ISSUE TITLE
RandomBackedGcrypt should probably use GCRY_VERY_STRONG_RANDOM

### ISSUE THREAD

**Issue by c4rlo** [keepassxreboot/keepassxc#2486]
`RandomBackendGcrypt::randomize()` calls `gcry_randomize(data, len, GCRY_STRONG_RANDOM)`.

According to the [gcrypt docs](https://www.gnupg.org/documentation/manuals/gcrypt/Quality-of-random-numbers.html):

* `GCRY_STRONG_RANDOM`: Use this level for session keys and similar purposes.
* `GCRY_VERY_STRONG_RANDOM`: Use this level for long term key material.

keepassxc seems to use `RandomBackedGcrypt` for all random-number generation, including for the IV used to encrypt the database and in the passphrase generator. Those things arguably fall under "long term key material".

So, shouldn't we be using `GCRY_VERY_STRONG_RANDOM` instead?

**Comment by c4rlo** [comment]
I just tried running the gcrypt [benchmark](https://github.com/gpg/libgcrypt/blob/master/tests/benchmark.c) (master branch), using a default build on Arch Linux running on an Intel Core i7-8750H.

Result: `GCRY_VERY_STRONG_RANDOM` is about 120 times slower than `GCRY_STRONG_RANDOM`.

Specifically, with VERY_STRONG it takes 1.2 milliseconds to generate 128 bytes of randomness; while with STRONG it only takes about 10 microseconds.

With these sort of times, `GCRY_VERY_STRONG_RANDOM` should be no problem as far as I can tell (unless keepassxc consumes much more randomness than I realize). Then again, it's just a single datapoint.

**Comment by droidmonkey** [comment]
That is very acceptable performance difference, especially if we decide to ship a FIPS compliant version of KPXC in the future.

**Comment by Bill-cpp** [comment]
As a KeePassXC user on Linux Mint 19.2, I'd definitely prefer GCRY_VERY_STRONG_RANDOM at least for creating my keyfile. The keyfile is the primary secret information protecting my entire database.

Regarding randomness of passwords for logon credentials, one could argue that GCRY_VERY_STRONG_RANDOM isn't necessary for protecting a New York Times subscription, but it would be another story for a Charles Schwab account holding a multi-million dollar portfolio.

**Comment by droidmonkey** [comment]
I enabled this on Windows and it causes tests to run forever. I implemented this on Linux and macOS only.
