### ISSUE TITLE
Document file formats

### ISSUE THREAD

**Issue by c4rlo** [keepassxreboot/keepassxc#2487]
There is currently a lack of documentation of the file formats used by keepassxc. I am thinking particularly of KDBX4, being the latest and greatest one.

This format is pretty complex, and is intricately tied to the security model. Having some thorough documentation of it, including the various crypto layers that are part of it, would be great in several ways:

1. It would provide an opportunity for interested parties to review it and spot any potential issues, both now and in the future as the format evolves.
1. It would make it easier to keep the implementation correct.
1. It will help others that wish to write tools to manipulate KDBX files.
1. It might also raise the profile of this project, since neither keepass nor keepassx currently have this documentation (in complete form) either.

I am aware of the following documents that go some way towards this:

* The [File Formats](https://keepass.info/help/base/importexport.html) page on keepass.info. Not much info.
* The [KDBX 4](https://keepass.info/help/kb/kdbx_4.html) page on keepass.info. Only has a diff of KDBX 3.1 vs KDBX 4.
* [This gist](https://gist.github.com/lgg/e6ccc6e212d18dd2ecd8a8c116fb1e45). No idea how complete or correct it is. Also lacks any info on the XML schema.

I would be happy to help out with this, but first wanted to see if anyone has thoughts, or knows of other existing documentation I may have missed.

**Comment by c4rlo** [comment]
I just found https://github.com/keepassxreboot/keepassxc-specs, which looks like a very promising work in progress. Closing this.

**Comment by phoerious** [comment]
Yes, I started to write some formal documentation. The project has stalled a bit, but I plan on finishing it some day.

**Comment by c4rlo** [comment]
Cool, let me know if there's anything I could help out with!
