### ISSUE TITLE
KeepassXC doesn't respect system theme (Debian 9 + XFCE)

### ISSUE THREAD

**Issue by zevilz** [keepassxreboot/keepassxc#2492]
KeepassXC doesn't respect system theme (Debian 9 + XFCE)

## Expected Behavior
KPXC respect the system theme in Debian 9 + XFCE, which in my case is [Vertex-Dark](https://github.com/horst3180/vertex-theme).

## Current Behavior
KPXC has a default theme.
![19-11-2018 13-05-19](https://user-images.githubusercontent.com/12094229/48762965-07053500-ecce-11e8-9317-dc82993f190f.png)

## Possible Solution
Tried:
1. Resave settings in qtconfig-qt4.
2. Start KPXC with `--style` option (`keepassxc --style Vertex-Dark`). Same result with others themes:
![19-11-2018 13-20-52](https://user-images.githubusercontent.com/12094229/48763196-809d2300-ecce-11e8-8fec-f21638d2843b.png)

## Steps to Reproduce
1. Install actual Debian 9 + XFCE.
2. Install qt4-qtconfig from repository.
3. Set GTK+ as DE style in qtconfig-qt4.
4. Install [Vertex Theme](https://github.com/horst3180/vertex-theme) with dependences.
5. Change system theme to Vertex Dark.
6. Install KPXC from backports (`deb http://ftp.debian.org/debian stretch-backports main`)

## Debug Info
KeePassXC - 2.3.4
Revision: 6fe821c

Lbbraries:
- Qt 5.7.1
- libgcrypt 1.7.6-beta

OS: Debian GNU/Linux 9 (stretch)
Arch: x86_64
kernel: linux 4.9.0-5-amd64

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by phoerious** [comment]
Looks good. I see no problem with the theme. 😄

Apparently you have two different versions, one which works and one which doesn't. Which is the working one?

**Comment by zevilz** [comment]
@phoerious 
See windows titles) On right - KeePassXC with default theme, on left - KeePassX with correct theme.

**Comment by phoerious** [comment]
Oh, I see. One is KeePassX. But yeah, KeePassXC is Qt5.

**Comment by droidmonkey** [comment]
Recommend following these instructions:

```
For Qt 5, it can be enabled by installing qt5-styleplugins and setting the following environment variable: QT_QPA_PLATFORMTHEME=gtk2
For full uniformity, make sure that the configured GTK+ theme supports both GTK+ 2 and GTK+ 3. If your preferred theme has inconsistent rendering after configuring Qt to use GTK+2, install gtk-theme-switch2 and choose a theme.
```

https://wiki.archlinux.org/index.php/Uniform_look_for_Qt_and_GTK_applications#QGtkStyle

**Comment by zevilz** [comment]
Solved)
I added
```
QT_QPA_PLATFORMTHEME=gtk2
QT_STYLE_OVERRIDE=gtk2
```
into `/etc/environment` and installed `qt5-gtk-platformtheme` and `qt5-style-plugins`.

**Comment by zevilz** [comment]
But now I see that font rendering is worse than in KeePassX with qt4.

**Comment by phoerious** [comment]
That depends on your font settings. Xfce requires you to do everything by hand that other DEs have already figured out for you.

**Comment by zevilz** [comment]
I choosed gtk2 style and generated font config (with same parameters as in system settings) in qt5ct. Then add in `/etc/environment`
`QT_QPA_PLATFORMTHEME=qt5ct`

Now I have correct theme in KPXC with correct fonts rendering) Thanks for help!
