### ISSUE TITLE
Prevent accidentally closing database with new password in open password generator

### ISSUE THREAD

**Issue by doits** [keepassxreboot/keepassxc#2494]
I just "lost" a password in the following way:

1. Create a new entry
2. Open the password generator
3. Generate a password in the generator and show it
4. Press `cmd+w` to close the database

The password was not yet applied to the entry. I used it to set something up and forgot that it was not yet applied. By closing the database with `cmd+w`the password was gone forever.

I know in fact this is a "user error" (I didn't explicitly apply the password), but still I think the app could help me a little bit in this case to not do this again.

## Expected Behavior

No password is lost, even if it is still in the generator.

## Current Behavior

Database is closed without a warning and the generated password is lost.

## Possible Solution

I see two ways:

1. Display a warning on `cmd+w` if there is a new password in the generator / the password generator is open and the password is different from the current entry's one (at least when the generator is displayed in context of an entry)
2. Apply the generator passwords instantly in case of a new entry. So at least for new entries the generated password will not be lost (because it displays a warning about unsaved changes on `cmd+w` if a new password was applied)

## Steps to Reproduce (for bugs)

1. Create a new entry
2. Open the password generator in context of the entry
3. Generate a password in the generator
4. Press `cmd+w` to close the database without applying the password

## Context

I wanted to generate a new password and use it instantly.

## Debug Info

KeePassXC - Version 2.3.4
Revision: 6fe821c

Bibliotheken:
- Qt 5.9.3
- libgcrypt 1.8.2

Betriebssystem: macOS 10.14
CPU-Architektur: x86_64
Kernel: darwin 18.2.0

Aktivierte Erweiterungen:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by doits** [comment]
Actually I just noticed that there is a warning in case of clicking "OK" with a new password in the password generator. This would be enough, too: to display the same warning in case of closing the database.

**Comment by droidmonkey** [comment]
Yes i think you hit an edge case that is not covered under the existing warning. Technically the close sequence should save the existing entry edit (another bug) prior to closing.

**Comment by phoerious** [comment]
This should be fixed with #2491.

**Comment by doits** [comment]
> Technically the close sequence should save the existing entry edit (another bug) prior to closing.

The thing is that the entry is not edited yet, since I didn't apply the new password. It looks like this:

<img width="867" alt="bildschirmfoto 2018-11-20 um 21 45 04" src="https://user-images.githubusercontent.com/148003/48801791-91b95480-ed0d-11e8-96ca-d4bdb17c7849.png">


- Clicking on "OK" asks whether to apply the generated password or not (👍)
- Clicking on "Abbrechen" closes the entry without applying (👍)
- Closing the database / `cmd+w` closes it without a question and the generated password is gone (👎)

> This should be fixed with #2491 

Sounds good! If there is any test build out there I'd test it, otherwise I have to wait for the next release.

**Comment by phoerious** [comment]
You can download a snapshot build from https://snapshot.keepassxc.org/ once it's merged. We do not have macOS snapshots up yet, however.

**Comment by droidmonkey** [comment]
Coming soon!

**Comment by phoerious** [comment]
I just tested it, with #2494 you will be presented with a confirmation dialogue if you hit Ctrl+W while editing an entry.
