### ISSUE TITLE
Support Password Manager API in macOS Mojave

### ISSUE THREAD

**Issue by rennefJ** [keepassxreboot/keepassxc#2496]
I would like to suggest a new feature for keepassxc in macOS:
Starting with macOS Mojave Apple has implemented a Password Manager API that allows third party applications to fill and suggest passwords for Apps and Websites in Safari.
1Password for macOS already supports this feature.
It would be great if keepassxc could also add support for this native way of handling passwords in macOS.

**Comment by varjolintu** [comment]
Some relevant info for developers:
https://developer.apple.com/documentation/authenticationservices

**Comment by varjolintu** [comment]
I couldn't find any info that the Password Manager API could be used in macOS side. But there's this feature which has been implemented in 1Password:
https://developer.apple.com/documentation/safariservices/safari_app_extensions

**Comment by lcges** [comment]
Any moves on the subject?

**Comment by droidmonkey** [comment]
No and not likely anytime soon

**Comment by lcges** [comment]
Too bad, it's very much missing in Safari. I will be observing the existing thread.

**Comment by droidmonkey** [comment]
Safari will have the browser extension starting with Big Sur

**Comment by rennefJ** [comment]
> Safari will have the browser extension starting with Big Sur
Thanks, I am looking forward to use the extension in Safari. 
One question though, why is this tied to Big Sur? Isn’t this only related to Safari 14, which is also available in Catalina?

**Comment by droidmonkey** [comment]
Dunno maybe

**Comment by varjolintu** [comment]
Safari 14 and WebExtensions are also available in Catalina.

**Comment by gagarine** [comment]
Can we re-open this issue?

It's great that their is now a Safari extension. Yet autofill feature is really great, I would love if KeepassXC could be a provider.

KeepassXC would have to implement this:

- https://developer.apple.com/documentation/authenticationservices/ascredentialproviderviewcontroller 
- https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_developer_authentication-services_autofill-credential-provider

**Comment by BetterB0y** [comment]
Any updates?
