### ISSUE TITLE
Drop to background (not minimized) when copying to clipboard

### ISSUE THREAD

**Issue by ba32107** [keepassxreboot/keepassxc#2498]
Hi,

I would really like an option for the KeePassXC window to drop to the background when copying the username and/or password. We already have an option to minimize it, but there should be another one to drop to the background (without minimizing).

This is an incredibly useful feature if you want to quickly log in on some webpages. You press CTRL+B, KeePass drops to background, CTRL+V into username field, ALT+TAB, CTRL+C for password, KP again drops to background, CTRL+V and you are done. Very quick. 

This is the only feature I miss from the Windows version.

Many thanks!
Balazs

**Comment by droidmonkey** [comment]
Is autotype or the browser extension not an option for your use case? They are more secure than copy/paste operations.

**Comment by ba32107** [comment]
For some websites the browser extension / autotype does not work for me. Also, sometimes the browser remembers the username, sometimes it doesn't, so there are a lot of occasions when I need to copy/paste.

**Comment by droidmonkey** [comment]
You have to make sure the URL is correct for the website, including http vs https. If the browser is remember your credentials than you need to disable that function. It is highly discouraged to use both KeePassXC and the internal browser password manager.

**Comment by ba32107** [comment]
I agree, I need to make sure all my URLs are properly set up. However I noticed that for some websites (e.g. Amazon) the password is requested on many different pages, and some of those appear on different subdomains. This makes it impossible to create an URL that works on every page (so I do need copy/paste from time to time).

**Comment by droidmonkey** [comment]
Are you using something other than amazon.com (ie amazon.co.uk)?

**Comment by ba32107** [comment]
Yes. Amazon is a good example, because it has 3 different domains (.com,.co.uk, .de) and the credentials are the same for all of them. The autotype only works on one (because I can only input one URL). I regularly search on all three domains of Amazon.

I had similar problems on other sites too, but I can't recall which ones.

**Comment by ba32107** [comment]
Great, thanks! That's very useful and good to know. 

Nevertheless, if this feature can be implemented, it would be great. Not a high priority of course.

**Comment by wohali** [comment]
Agree: this is high on my wishlist, too.

I also use KeePass to manage passwords in situations where I'm not in a browser, and autotype doesn't make sense to automate - generally, specific command line situations. Being able to un-tray KeePassXC, double-click on a password or Ctrl+T for a TOTP, and have it hide itself away again, is something I would appreciate on a daily basis.

**Comment by ba32107** [comment]
Hello,

I'd like to start contributing to this project and I would like to start by implementing this minor feature. If you have any concerns with this, please let me know.

I have a question regarding contributions. If I make a UI impacting change (such as this one), how do I handle translations? Should I just leave out the new string from the translation files? Or do I need to include the new string, leaving it in English?

**Comment by droidmonkey** [comment]
Don't worry about translations they are done in Transifex and merged prior to release.

**Comment by ba32107** [comment]
Okay, thanks. I'll open a PR once ready.
