### ISSUE TITLE
Database Refactor Consolidated Issues

### ISSUE THREAD

**Issue by droidmonkey** [keepassxreboot/keepassxc#2499]
Consolidated issues after the database refactor was merged in https://github.com/keepassxreboot/keepassxc/commit/d612cad09a4f1cd8ef9bf6be8bf90b75248ecfef

1. [x] Modified databases (showing * in title) can be closed without prompt for saving
2. [x] AutoOpen no longer works
3. [x] SSH key unloading does not work when tab is closed

**Comment by droidmonkey** [comment]
New issue... Preview panel does not update after a new group is selected.

**Comment by kneitinger** [comment]
I encountered that preview panel issue as well and talked about it a bit on #1730 

https://github.com/keepassxreboot/keepassxc/issues/1730#issuecomment-441940386

**Comment by varjolintu** [comment]
After https://github.com/keepassxreboot/keepassxc/commit/3c362ac82279123432f421df8c4a1bc71bb44b24 there's no way to focus the DatabaseOpenDialog's password input field on macOS. The focus stays at the KeePassXC main window.
