### ISSUE TITLE
keepassxc does not close window automatically after entering password.

### ISSUE THREAD

**Issue by Lalarian** [keepassxreboot/keepassxc#2500]
Hello! I have keepassxc in my autostart settings. So it opens a window after every boot.
I then enter the password, but the main window remains open.
## Expected Behavior

I think the main window should close after entering the database password.
## Current Behavior
The main window stays open.

## Possible Solution

In case someone wants the main window to stay open, there should be a checkfox for choosing that option in settings/general

## Context

Having to do the same procedure everytime the system booted is an annoyance. Of course there's sense in entering the password everytime, but why do I need to additionally close the window?

## Debug Info

KeePassXC - Version 2.3.4
Revision: 6fe821c
Distribution: AppImage

Bibliotheken:
- Qt 5.9.4
- libgcrypt 1.8.1

Betriebssystem: Ubuntu 18.04.1 LTS
CPU-Architektur: x86_64
Kernel: linux 4.15.0-39-generic

Aktivierte Erweiterungen:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey
Libraries:
- LIBS

Thank you!

**Comment by phoerious** [comment]
We do not have a concept of unlock at start. What you see is just the normal KeePassXC window and it would be unexpected behaviour if it always minimised after you unlock it. What should happen, however, is that if you enable "Minimise after application startup", KeePassXC should be minimised or hidden to they tray. I think that feature, on the other hand, is a bit broken in combination with my desktop environment. It does work if I start it manually, but when my desktop restores the previously opened windows after login, KeePassXC does not hide itself.

**Comment by ccoenen** [comment]
I am running ubuntu 18.4 as well. I have set KeePassXC to "Minimise after application startup". It starts in the background this way. When I need it for the first time, I enter my password. It works beautifully.

**Comment by phoerious** [comment]
That's your desktop environment restoring the windows of your previous session. If you close KeePassXC and restart it, it should start minimised.

**Comment by Lalarian** [comment]
OK, tried and you where right!
There seems to be an annoying bug in Xubuntu/xfce. I reset the session, cleared the session cache, but it will always open the same windows after booting, of tools not even in the Startup.

**Comment by phoerious** [comment]
I have the same on KDE. Session restore seems to generally be broken in Linux desktop environments. The only platform I have seen it working reliably on is macOS (and there it works perfectly as if it were just loading the previous session's RAM image). Restoring KDE apps on KDE works okay-ish, but pure Qt or Gtk apps restore very poorly. When I leave Inkscape documents open, I get as many Inkscape windows with empty documents as I left open, KeePassXC is restored but not minimised and Chrome isn't restored at all.
