### ISSUE TITLE
Docs unclear for first-time build and test

### ISSUE THREAD

**Issue by jzohrab** [keepassxreboot/keepassxc#2501]
## Expected Behavior
Build instructions for contributors (https://github.com/keepassxreboot/keepassxc/wiki/Building-KeePassXC) should have "first build, and ensure all tests pass", so that devs are guaranteed to write and run tests.  The tests should also succeed on first time build and run.

## Current Behavior
For macos (https://github.com/keepassxreboot/keepassxc/wiki/Building-KeePassXC#macos), I ran the build
```
cmake -DCMAKE_OSX_ARCHITECTURES=x86_64 \
  -DCMAKE_BUILD_TYPE=Release \
  -DWITH_XC_ALL=ON ..
```
and then saw the instructions for testing, so I tried
```
cmake -DCMAKE_OSX_ARCHITECTURES=x86_64 \
  -DCMAKE_BUILD_TYPE=Release \
  -DWITH_TESTS=ON -DWITH_GUI_TESTS=ON \
  -DWITH_XC_ALL=ON ..
```
`make test` then failed with various errors, eg
```
...
Unable to find executable: testguipixmaps
32/32 Test #32: testguipixmaps ...................***Not Run   0.00 sec
0% tests passed, 32 tests failed out of 32
...
```

I wasn't sure if I needed to build the full package with `make -j8 package`, or if the `MAKE_BUILD_TYPE` should be `Test` or something else.

The following appeared to work.
```
cmake -DCMAKE_OSX_ARCHITECTURES=x86_64 -DWITH_TESTS=ON -DWITH_GUI_TESTS=ON ..
make -j8 package
make test
```

Tests also popped up a gui and appeared to hang ... I waited and then provided some input.  Wasn't sure if that was correct or not.  Perhaps because of this, some tests failed:
```
94% tests passed, 2 tests failed out of 32

Total Test time (real) =  93.55 sec

The following tests FAILED:
	 30 - testcli (Failed)
	 31 - testgui (Child aborted)
Errors while running CTest
make: *** [test] Error 8
```

## Possible Solution
Explicitly spell out how the cmake should be written to build for tests.

## Context
As a potential new contributor to this project, having a smooth checkout/build/test reduces the friction, and lowers the barrier to entry.  It's hard enough to contribute as it is, given that it's a c++ project :-)

Cheers!

**Comment by droidmonkey** [comment]
On macOS, cli and gui tests are currently broken. I have a pending fix.

**Comment by jzohrab** [comment]
Thanks @droidmonkey.  Was what I wrote correct for building for test?  Section starting "The following appeared to work."  If yes, I can submit a PR for the documentation.

**Comment by droidmonkey** [comment]
This is more of a cmake issue. When you run "make test" it does not reload the cmake configuration. So when you added the test flags it was assuming the tests were already built. If you have ran just make again then make test you would be been successful. The documentation can be made clearer in the build step to say:

"If you would like to run tests after building, add ```-DWITH_TESTS=ON -DWITH_GUI_TESTS=ON``` to the cmake command"

**Comment by droidmonkey** [comment]
I made the change, thank you
