### ISSUE TITLE
Add hotkey shortcuts to popup menu

### ISSUE THREAD

**Issue by valnar1** [keepassxreboot/keepassxc#2509]
For those who are bot new to Keepass AND KeepassXC, it would be good to add the hotkeys to the context menus like in the original Keepass.  Example from Keepass attached.
![2018-11-25 09_40_04-](https://user-images.githubusercontent.com/30323282/48980454-00443c80-f097-11e8-8017-3e3bf218e383.jpg)

**Comment by droidmonkey** [comment]
Done already for upcoming 2.4
