### ISSUE TITLE
Error while loading shared libraries: libQt5Network.so.5

### ISSUE THREAD

**Issue by davmann** [keepassxreboot/keepassxc#2510]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( Do not include screenshots of your actual database! )

## Expected Behavior
[NOTE]: # ( If you're describing a bug, tell us what should happen )
[NOTE]: # ( If you're suggesting a change/improvement, tell us how it should work )
```
user@host:~$ sudo apt install keepassxc 
user@host:~$ keepassxc    (KeePassXC should open)
```

## Current Behavior
[NOTE]: # ( If describing a bug, tell us what happens instead of the expected behavior )
[NOTE]: # ( If suggesting a change/improvement, explain the difference from the current behavior )
```
user@host:~$ keepassxc 
keepassxc: error while loading shared libraries: libQt5Network.so.5: cannot open shared object file: No such file or directory
```

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug, )
[NOTE]: # ( or ideas how to implement the addition or change )

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1. Startup Ubuntu 18.04.1 (fresh install and fully upgraded)
2. Open terminal
3. `user@host:~$ keepassxc`

## Context
[NOTE]: # ( How has this issue affected you? What are you trying to accomplish? )
[NOTE]: # ( Providing context helps us come up with a solution that is most useful in the real world )
I tried also PPA with same result.
Snap worked but had no extensions for browsers

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION: 2.3.1+dfsg.1-1
Revision: REVISION

Libraries:
- LIBS
Those installed from Ubuntu and libqt5network5 5.9.5+dfsg-0ubuntu1

Operating system: OS
CPU intel i7: Ubuntu 18.04.1 AMD64
Kernel: 4.15.0-39-generic #42-Ubuntu SMP

Enabled extensions:
- EXTENSIONS
None

**Comment by droidmonkey** [comment]
Please see https://github.com/keepassxreboot/keepassxc/issues/2241
