### ISSUE TITLE
Import .1pif-Datei (1Password-Datenbank-Austauschdatei)

### ISSUE THREAD

**Issue by 99oU6g** [keepassxreboot/keepassxc#2513]
Momentan ist es nicht möglich, das proprietäre Dateiaustauschformat .1pif ('1Password Interchange Format' - im Grunde JSON-artig) von 1Password in KeePassXC zu importieren.

Für Keepass gibt es ein Import-Plugin (https://github.com/diimdeep/1P2KeePass), das aber die Rubrik 'Erzeugte Kennwörter' komplett ignoriert. Auch angehänge Dateien werden nicht importiert, manche Felder bleiben leer.
Buttercup (https://buttercup.pw) hat einen Importer im Repository (https://github.com/buttercup/buttercup-importer), der die Kennwörter importiert, aber das Feld 'Notizen' (bei Kennwörtern) unterschlägt. Die _Kategorie_ 'Notizen' wird hier jedoch komplett ignoriert (anders als bei 1P2KeePass). Viele Felder werden unterschlagen bzw. gekürzt.
Stewart C. Russell (https://github.com/scruss) hat 2013 ein Perl-Script veröffentlicht, das einiges besser, aber nicht alles gut macht: http://scruss.com/blog/2013/04/24/mac-to-linux-1password-to-keepassx/ und https://github.com/scruss/1pw2kpxxml .

Da 1Password nach wie vor einer der Platzhirsche in der Passwortverwaltung ist, wäre es meiner Ansicht nach ein großer und wichtiger Schritt, Wechselwilligen aus dieser 'Gated Community' einen leicht gangbaren Pfad zu eröffnen.
Die Gründe hierfür (und davon gibt es ja nicht wenige) kennt ihr.

**Comment by droidmonkey** [comment]
There is a PR open for this..... #2292

**Comment by moll** [comment]
Am I mistaken to say that the two issues you, @droidmonkey, mention are not for the 1Password Interchange Format? I've got a vault from 1Password 4 days (that still uses the [Agile Keychain](https://support.1password.com/cs/agile-keychain-design/) format on disk) that only seems to support 1PIF as an export that preserves attachments.

**Comment by droidmonkey** [comment]
See #9815, please don't necropost

**Comment by moll** [comment]
Ah, you call it "1PUX" as opposed to "1PIF" which the export file extension is. Thanks!

> please don't necropost

Fortunately this isn't a forum where issues pop to the top when commented on. :) I think it's beneficial for old issues to include references to new issues to help people follow the trail that happen to stumble upon this one. It was the only issue that comes up when searching for "1pif", for example.

**Comment by moll** [comment]
Actually, looking at it closer, the [1PUX](https://support.1password.com/1pux-format/) format https://github.com/keepassxreboot/keepassxc/pull/9815 refers to isn't the same as 1PIF which this issue deals with. I've not yet come across any official documentation on the latter, although there do seem to be all sorts of conversion scripts lying around (some of which this issue's author links to).

If 1Password 4 and before's 1PIF is something KeePassXC wants to support, perhaps it's relevant to reopen this issue.

Here's the translation of the author for us who don't speak German:

> Currently it is not possible to import 1Password's proprietary file interchange format .1pif ('1Password Interchange Format' - basically JSON-like) into KeePassXC.
> 
> There is an import plugin for Keepass (https://github.com/diimdeep/1P2KeePass), but it completely ignores the 'Generated passwords' section. Attached files are also not imported and some fields remain empty.
> Buttercup (https://buttercup.pw) has an importer in the repository (https://github.com/buttercup/buttercup-importer) that imports the passwords but omits the 'Notes' field (for passwords). However, the 'Notes' category is completely ignored here (unlike 1P2KeePass). Many fields are omitted or shortened.
> Stewart C. Russell (https://github.com/scruss) published a Perl script in 2013 that does some things better, but not everything well: http://scruss.com/blog/2013/04/24/mac -to-linux-1password-to-keepassx/ and https://github.com/scruss/1pw2kpxxml.
> 
> Since 1Password is still one of the top dogs in password management, I think it would be a big and important step to provide an easy path for people from this 'gated community' who want to change.
> You know the reasons for this (and there are quite a few of them).

Have a good weekend!

**Comment by droidmonkey** [comment]
1PIF is undocumented and not used anymore. Update your 1password to 6 or higher and export to 1pux
