### ISSUE TITLE
centralized config file suggestion

### ISSUE THREAD

**Issue by jacksnd1** [keepassxreboot/keepassxc#2514]
I am in the process of rolling KeepassXC out to all our users in the office.  We are aiming to have a relatively standardized layout for all end users. For example: Column order, database locking behavior, window size.  This can be very useful for helpdesk who can more easily talk an end user through an issue if the layout is as they expect.

At the moment you can copy a preprepared config file into each users `$HOME/.config/keepassxc` folder but management of this over many users becomes ungainly. It would be really great if there could be a global config file so that any user than logs into a computer would have keepassxc read from that and set the config options, somewhere like `/etc/keepassxc/` or an equivalent for other OS.

While not password managers both Firefox and Chrome have good examples of centralised management, even going so far as to let you decide which globaly set config options a user can change and which are locked

**Comment by droidmonkey** [comment]
This is also discussed in #1284 and #2189. There is the "--config <config-file>" command option, however it completely overwrites the config settings and would allow end-users to modify the "shared" config file (unless read-only, but this is untested).

**Comment by droidmonkey** [comment]
This will be part of #2189
