### ISSUE TITLE
Feature request: Automatically select parent group

### ISSUE THREAD

**Issue by marcochiesi** [keepassxreboot/keepassxc#2516]
Hey there,
I am evaluating switching from KeePass to KeePassXC, but at the moment there's a missing feature in KeePassXC which is essential for me. It's the ability to automatically (or at least quickly) selecting a group in the tree when performing a search and selecting an entry from the search results.

In KeePass, this behavior is controlled by the option _"When selecting an entry, automatically select its parent group, too"_ (under Options > Interface > Entry List).
Would it be possible to have the same on KeePassXC?

Alternatively, or additionally, would it be possible to be able to click on the group path in the entry preview to quickly select that group? In KeePass, the group of an entry is rendered as a link in the preview, and if you click on it, it opens that group.

**Comment by droidmonkey** [comment]
This is already implemented in the upcoming 2.4 version. You can double click the folder in search results and it will take you there.
