### ISSUE TITLE
Auto-Type strange behavior

### ISSUE THREAD

**Issue by brutsers** [keepassxreboot/keepassxc#252]
## Expected Behavior

Auto-Type would always type the requested data in the requested form.

## Current Behavior

Auto-Type is failing with certain settings not enabled/disabled.

## Steps to Reproduce (for bugs)

1. OS is Qubes 3.2 - AppVm is Fedora 24
2. Compile source KeePassXC from source with KeePassHTTP and Auto-Type enabled
3. Open Firefox and KeePassXC and by default the Auto-Type will not work
4. Change the global settings and enable the following:
- Show a system tray icon
- Hide window to system tray when minimized
5. Minimize the KeePassXC to system tray, then open it again
6. Perform the Auto-Type and it will work
7. The global Auto-Type shortcut will however still not work, have not found a way to get that working yet.

## Your Environment

* KeePassXC version/commit used: (can be found under Help -> About)
* Qt version (e.g. Qt 5.3): 
* Compiler (e.g. Clang++3.6.0): 
* Operating System and version: 
KeePassXC 2.1.0
Qt version 5.6.2-1
gcc (GCC) 6.3.1 20161221 (Red Hat 6.3.1-1)
Operating System Qubes 3.2 - AppVm Fedora 24

## References
Here you can find some discussions about probably the same issue, even one with a patch file to possibly fix the problem?

https://forum.keepassx.org/viewtopic.php?t=2033
https://dev.keepassx.org/issues/548

**Comment by phoerious** [comment]
Is still this an issue?
