### ISSUE TITLE
Auto-Type bug 

### ISSUE THREAD

**Issue by sergey-yabloncev** [keepassxreboot/keepassxc#2521]
Если использовать автоматический набор при русской раскладке, то текст копируется транслитерированный (английские символы в русской раскладке) и после чего перестает работать переключение раскладки с использованием горячих клавиш. 

В качестве горячей клавиши переключения языков установлен Caps Lock
(
If you use automatic dialing with the Russian layout, then the transliterated text (English characters in the Russian layout) is copied and then the layout switching with hot keys stops working.

Caps Lock is set as a hotkey for switching languages.
)

##
KeePassXC - Version 2.3.4
Revision: 6fe821c

Libraries:
- Qt 5.11.2
- libgcrypt 1.8.4

Operating system: Manjaro Linux
CPU architecture: x86_64
Kernel: linux 4.19.4-1-MANJARO

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by droidmonkey** [comment]
Duplicate of #2079
