### ISSUE TITLE
Dragging and dropping between databases immediately saves the DBs

### ISSUE THREAD

**Issue by bllngr** [keepassxreboot/keepassxc#2522]
## Expected Behavior
Although drag and drop does not seem to be implemented yet (see #127), dragging an item from one open database to another open database moves items between from the source to the target DB. I'd expect that both DBs are them marked as changed, indicated by a small '*' next to the filename.

## Current Behavior
Dropping the item on a different database moves the item, and thus removes it from the original database. Both DBs get saved immediately, giving the user no indication that they have been changed. Any unsaved changes are also saved, potentially causing data loss (since the original file will be overwritten).

## Possible Solution
Don't save the database, but indicate that it has been changed via the '*' next to the filename in the tab/titlebar. This enables the user to close the source database without saving, if they want to keep the item in both databases.

## Steps to Reproduce
1. Create two databases, with a few items each.
2. Open both DBs simultaneously. 
3. Drag a item from one DB, and drag it to the Root group of the other DB
4. Observe the indicator, the item being moved, and both DBs being saved immediately,

## Debug Info
KeePassXC - Version 2.3.4
Revision: 6fe821c

Bibliotheken:
- Qt 5.11.1
- libgcrypt 1.8.3

Betriebssystem: Windows 10 (10.0)
CPU-Architektur: x86_64
Kernel: winnt 10.0.17134

Aktivierte Erweiterungen:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

Libraries:
- LIBS

Operating system: OS
CPU architecture: ARCH
Kernel: KERNEL

**Comment by sqrt** [comment]
I just noticed that copy via drag & drop actually does work when pressing the CTRL button. The behaviour is the same, both databases get saved immediately without giving the user a chance to not save them.

**Comment by droidmonkey** [comment]
Do you have auto save database after every change enabled? This is the desired behavior if so.

**Comment by ezzra** [comment]
> I just noticed that copy via drag & drop actually does work when pressing the CTRL button

is that actually true for the ubuntu version? Does not work for me..

**Comment by phoerious** [comment]
It should be working across platforms, yes.

**Comment by droidmonkey** [comment]
This issue should be closed because it is not a problem as far as I am concerned in 2.4.0. Holding CTRL while Drag/Drop works everywhere I have tried (Win/Lin/Mac)
