### ISSUE TITLE
Bulk set multiple values as reference

### ISSUE THREAD

**Issue by rugk** [keepassxreboot/keepassxc#2527]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( Do not include screenshots of your actual database! )

I want to have a way to select multiple items in my database and mass-update them, so they reference the same username and password.

## Context
[NOTE]: # ( How has this issue affected you? What are you trying to accomplish? )
[NOTE]: # ( Providing context helps us come up with a solution that is most useful in the real world )

Stackexchange/Stackoverlow is an (in)famous example. I have the same login username + password for a multitude of different domains. (I don't actually know whether `https://*.stackexchange.com` would actually work and simplify the process.)

Obviously I need this, because I want to be able to start my login from any of the Stackexchange sites. When I go somewhere else, it uses some kind of OAuth mechanism/or shared cookies to get me logged in, but when I am not yet logged in, it has an input field on every site.

## Expected Behavior
[NOTE]: # ( If you're describing a bug, tell us what should happen )
[NOTE]: # ( If you're suggesting a change/improvement, tell us how it should work )

So now I want to do:
1. Search for it:
![grafik](https://user-images.githubusercontent.com/11966684/49342960-e3dd6c80-f661-11e8-9d67-abca12fae55e.png)
2. Select all items.
3. Right-click.
4. Choose something like "update to same reference".
5. Maybe let me select what to reference (username and/or password?) and what item to choose 
  Or (which may simplify usability and implementation): Just reference username & password always (when cloning you also have no choice) and keep the item I have right-clicked on as a plain-entry.

## Current Behavior
[NOTE]: # ( If describing a bug, tell us what happens instead of the expected behavior )
[NOTE]: # ( If suggesting a change/improvement, explain the difference from the current behavior )

I would have to copy the reference ID by hand or so…

**Comment by tomhundt** [comment]
+1 on the above use case....  I have a similar need to **set the icon for multiple entries**... Currently one can select a few entries, and right click, and choose _Download Favicon_.  But what if one wants to use an already-downloaded icon?  (My example: I have a bunch of WiFi networks that should really have a nice WiFi icon. Definitely non-downloadable.)

**Comment by droidmonkey** [comment]
You can apply an icon from the group down to child entries as of 2.5.0

**Comment by droidmonkey** [comment]
Duplicate request to bulk modify of entries.
