### ISSUE TITLE
Add support for in-app editing of attached TXT and RTF files.

### ISSUE THREAD

**Issue by metbril** [keepassxreboot/keepassxc#2529]
The "orginal"  KeePass application for Windows supports editing of attached .txt and .rtf files.

https://keepass.info/help/base/faq_tech.html#rtftext

It would be awesome if KeePassXC would also support this. This would enable me/us to use the application as a generic vault for secure notes.

More info here:

From: [How to Better Organize Secrets Using Keepass Password Manager](https://www.howtogeek.com/220673/HOW-TO-BETTER-ORGANIZE-SECRETS-USING-KEEPASS-PASSWORD-MANAGER/)

> You can insert any file as an attachment, be it a PDF document of receipt, text file, and even a screenshot. Later on if you want to view the attachment, then Keepass has its own internal viewer and it works with the data in main memory.
> 
> If the file format is not supported (e.g., PDF file), then Keepass extracts the attachment to a (EFS-encrypted) temporary file and opens it using the default application. After finishing viewing/editing, you can choose between importing or discarding any changes made to the temporary file. In any case, Keepass securely deletes the temporary file.
> 
> **Add Secure Notes in Keepass**
>
> Keepass allows you to safely store information that may not fit well in any other category or that you want to protect from prying eyes. Secure Notes is a great place to store information that is useful but not often used such as two-factor authentication recovery keys, vehicle identification numbers, insurance policy numbers, emergency or temporary contact numbers, and so on.
> 
> Create an entry in the “Notes group” and name it as Passport Application form. Add “File Number” in the custom field strings. In the file attachment section, click “Attach” and then select “Create Empty Attachment.” An RTF file will be created and is associated with that note. Since Keepass supports both .TXT and .RTF file, you can view/edit them internally.
> 
> For TXT files, the built-in editor supports standard operations like cut, copy, paste, undo, word-wrap, and more. For RTF files, additionally standard formatting commands are available: choosing font, font size, bold, italic, underline, text and background colors, and more.

**Comment by metbril** [comment]
Possibly related with #2400

**Comment by johnmhm** [comment]
Currently, the user guide states that: 

> When you try to open the attached file, KeePassXC extracts the attachment to a temporary file and opens it using the default application associated with the file type. After finishing viewing or editing the file, you can choose between importing or discarding the changes that you made to the temporary file. KeePassXC securely deletes the temporary file by overwriting it.

https://keepassxc.org/docs/KeePassXC_UserGuide.html#_attachments

I have not found that to be true. When opening an attachment from a KeepassXC entry, a temporary copy of the file is correctly opened in the associated editor, but upon editing and attempting to save, an error pops up stating that the file "is being used by another process." and prevents any changes to be imported as stated above. 

Windows 10.0.19041 Build 19041, KeepassXC 2.6.1
![Screenshot 2020-10-08 214358](https://user-images.githubusercontent.com/13797130/95505914-68604b00-09af-11eb-9075-5827d5c0eea9.png)

**Comment by phoerious** [comment]
The behaviour on Windows is buggy and needs to be fixed. Known issue.

**Comment by johnmhm** [comment]
@phoerious Do you know if there is an issue # for this I can follow?

**Comment by phoerious** [comment]
#2400
