### ISSUE TITLE
entropy-meter isn't installed on make install

### ISSUE THREAD

**Issue by TheZ3ro** [keepassxreboot/keepassxc#253]
## Expected Behavior

entropy-meter is available in /usr/bin folder

## Current Behavior

entropy-meter is not installed

**Comment by louib** [comment]
@TheZ3ro FYI, I intend to add entropy-meter as a command to `keepassxc-cli` so it is also available globally. How does that sound?

**Comment by TheZ3ro** [comment]
@louib sound cool to me! 

PS: now that you are in the team make new branch in keepassxc repo directly so I can contribute as well :smile: I want to make some changes to keepassxc-cli

**Comment by TheZ3ro** [comment]
entropy-meter will be part of keepassxc-cli. Closing as invalid
