### ISSUE TITLE
Upgrading from KeepassX 0.4.3 to KeepassXC 2.3.4

### ISSUE THREAD

**Issue by KiwiAllan** [keepassxreboot/keepassxc#2532]
Hi. I’m not certain that this is the right place to ask this question, so please point me elsewhere if necessary…

I’ve been using KeePassX 0.4.3 for some time on my MacBook Pro … it’s a super little program. Now I see KeePassXC seems to be the ongoing development, with 2.3.4 as the latest version. May I ask you what do I need to know to upgrade, please? 

e.g. Can I install 2.3.4 “over the top” of 0.4.3? Or do I need to start with a fresh install of 2.3.4? And if so, can I use the same database, or do I need to start a new database from scratch? Is there anything else I need to know for a smooth installation process?

I’m using macOS High Sierra (10.13.6) on my 2015 MacBook Pro. Thanks for any insights you can provide. Gratefully,

**Comment by droidmonkey** [comment]
You can install it "Side by side" with the original KeePassX and use the same exact database.

**Comment by phoerious** [comment]
You will have to import the kdb file however, which will be converted to a kdbx in the process.

**Comment by KiwiAllan** [comment]
Thanks for your prompt and very helpful comments. I'll be able to move ahead with using 2.3.4 much more confidently now.  Cheers and regards.
