### ISSUE TITLE
Create "Right-Click-Add-Date/Time-Stamp" in Notes

### ISSUE THREAD

**Issue by mem0uni** [keepassxreboot/keepassxc#2534]
## Current Behavior
When editing an entry, there is no way to add a date/time stamp to your notes easily. For my team, this is the #1 addition we wished the XC team would add to this program. 

## Possible Solution
Add the ability to "right-click" in the notes section of an entry and add a simple date/time stamp in the notes. 

## Context
We share many KeePassXC login and password notes between some systems. We store commonly accessed cloud device access methods in the entry notes in KeePassXC. When these details change, we always add the latest change to the top notes section.  It would be nice, just before we apply those changes, to add a date/time stamp. 

## Debug Info
KeePassXC - Version 2.3.4
Revision: 2cc52a8
Distribution: Snap

Libraries:
- Qt 5.9.5
- libgcrypt 1.8.1

Operating system: Ubuntu Core 18
CPU architecture: x86_64
Kernel: linux 4.15.0-39-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

Operating system: Linux
CPU architecture: x86_64
Kernel: 4.15.xx

Enabled extensions:
None

**Comment by droidmonkey** [comment]
Would a "post to notes" feature meet this need? For example, instead of free form notes it would be more like adding a comment that includes author and date/time stamp.

**Comment by mem0uni** [comment]
Sure, that would work. This morning I had an entry that contained what we thought were current change control notes, only to discover they had been made last year!!! I will normally create my note updates, open an xterm, issue a "date" command with arguments, and then copy/paste that into my notes then apply. If you create a "post to notes" feature, that would be great. It would make an already wonderful piece of software even better. For anyone reading this asking "Why would any of this matter?" just imagine an infrastructure with massive hybrid clouds systems in place and two dozen authentication systems controlling access. We have admins, engineers, service accounts, public/private keys, TLS keys, etc. in the mix. Storing all this with KeePassXC in the cloud makes the job a lot easier. (This is our chosen password keeper. There are many like it, but this one is ours.)   :)

**Comment by droidmonkey** [comment]
For the time being, the entry modified date/time may be an adequate sanity check.

**Comment by droidmonkey** [comment]
We won't be adding this capability, the described use case is not a use case KeePassXC supports. We absolutely do not recommend using KeePassXC in a massive multi-user fashion, that is not how it is intended to be used.
