### ISSUE TITLE
External Changes on Samba Share not recognized on Linux

### ISSUE THREAD

**Issue by jhit** [keepassxreboot/keepassxc#2536]
We work in a shared network environment with four users using one OSX, two Windows 10 and one Ubuntu 18.10 (me). Keepass databases are stored on a NAS that is accessible via Samba shares. We verified, that the KeepassXC instances on the Windows 10 machines properly detect external changes of the KeePass database (changes were made on Windows and Linux) while my instance on Ubuntu Linux does not. I played with the settings, disabled safe saving and auto-saving, but my KeepassXC never updated and always overwrites external changes without prompting or merging.

I tested this with current stable release 2.3.4 and with a custom compile from the develop branch. Both builds behave exactly the same. Fix from #1799 does not fix this issue on Samba shares.

## Expected Behavior
Like on Windows 10 systems, I expect KeepassXC to detect external changes of the database and do a reload of the database.

## Current Behavior
External changes are not detected when the database is located on a Samba share

## Steps to Reproduce
1. Put a kdbx file on a Samba share
2. Open the kdbx File on a Linux workstation and a Windows 10 Workstation
3. Change an entry on the Windows workstation. (notice the Linux workstation does not update)
4. Change a different entry on the Linux workstation and safe the kdbx file.
5. KeepassXC on the Windows workstation will reload the file and the changes there will disappear.

## Debug Info
KeePassXC - Version 2.3.4
Revision: 6fe821c

Libraries:
- Qt 5.11.1
- libgcrypt 1.8.3

Operating system: Ubuntu 18.10
CPU architecture: x86_64
Kernel: linux 4.18.0-11-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by jhit** [comment]
I did some Background research on this Issue and tested if changing Samba protocol Version in the fstab entry from ver. 2.1 to 1.0 would change anything but no. (See. https://askubuntu.com/a/995142/593177)
Seems that inotify with cifs is totally broken on Linux: https://stackoverflow.com/questions/8124617/getting-file-create-notifications-for-cifs-mount-in-linux/10107889#10107889.

So I guess going the inotify way here is not possible.

**Comment by jhit** [comment]
I checked if `smbnetfs` over FUSE can do the trick but unfortunately the aswer is NO.

**Comment by droidmonkey** [comment]
The only real possibility I see is a timed poll of the file and performing a hash of the file on each poll.

**Comment by jhit** [comment]
Why not simply check the timestamp? If It was changed just do the reload. If the file did not change one reload more or less will not hurt, but continuously hash the database would probably be a waste of CPU cycles.
Or maybe store a hash as a unencrypted file attribute for the kdbx file when it gets written and check that file attribute?

**Comment by droidmonkey** [comment]
Checking modified time would work although it can be unreliable. It is a good trigger to perform additional checks. I would have to check on storing the file hash in the header, I believe we can do that in KDBX4 because you can put arbitrary information in the header. KDBX3 is another story.

**Comment by jhit** [comment]
I'm fine with a KDBX4 only solution. I know Timestamp can be unreliable, but here it is only used to initiate a reload. I think for this it would be ok.

**Comment by jhit** [comment]
This is related to issue #2389 and might be solved together.

**Comment by JulienPalard** [comment]
It may be tightly related, or not, but I tried over sshfs and external changes are not spotted neither (the second user was overwriting the passwords entered by the first one, without any notice).

**Comment by wohali** [comment]
Just ran into this bug myself, which caused loss of data :(

Any ETA for resolution? Switching to e.g. NFS for mounting isn't really an option; NFS mounts over Wi-Fi are generally asking for trouble.

**Comment by dssouza-ti** [comment]
Hi everyone. Is it possible that this issue could also affect KeeShare? I tried to share a group between a few Linux and Windows PCs, and stored the file in a samba share, but I was unable to make it work in the linux PC, only the Windows PC could detect changes made and update the shared group.

**Comment by droidmonkey** [comment]
Yes keeshare uses the same change detection algorithm.
