### ISSUE TITLE
pw-enc cli parameter for Windows

### ISSUE THREAD

**Issue by hunhejj** [keepassxreboot/keepassxc#2537]
KeePass has a nice command line parameter called pw-enc

> The **-pw-enc:** parameter is similar to **-pw:**, but it requires the password to be encrypted. Encrypted passwords can be generated using the {PASSWORD_ENC} placeholder.

(https://keepass.info/help/base/cmdline.html)

> The {PASSWORD_ENC} placeholder is replaced by the password of the current entry in encrypted form. The password is encrypted using credentials of the current Windows user. The encrypted password should not be stored and only works for the current user.
>
>It is intended to be used in conjunction with the -pw-enc command line parameter (see the URL Field Capabilities page for an example how to define an URL to open an additional KeePass database). The placeholder cannot be used to transfer passwords to other applications (except KeePass), because the target applications don't know how to decrypt encrypted passwords generated by {PASSWORD_ENC}. 

(https://keepass.info/help/base/placeholders.html#passwordenc)

I really miss a this feature from KeePassXC. Is it possible to add something similar?

**Comment by droidmonkey** [comment]
I really don't see the point to that feature. It is marginally better than just passing your password to the application on launch. Any application running as your user would be able to decrypt your database password anyway if it intercepted it.

**Comment by droidmonkey** [comment]
For reference, this is the C# class used to encrypt/decrypt the password using the user's credentials:

https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.protecteddata?view=netframework-4.7.2

**Comment by JohnyWS** [comment]
@droidmonkey I have a usecase for this when working with shared database as described here: https://superuser.com/a/426207/104909 - am I missing something here, or would you not recommend that workflow?

(having a very secure password for the shared database, and then have that password stored in personal databases with own memorable passwords, and then a quick command to open the shared database with the strong password)

**Comment by droidmonkey** [comment]
That is a workaround to limitations of the original KeePass application. We have two methods to overcome this limitation is a much more secure way:

https://keepassxc.org/docs/KeePassXC_UserGuide.html#_database_sharing_with_keeshare

https://keepassxc.org/docs/KeePassXC_UserGuide.html#_automatic_database_opening

**Comment by JohnyWS** [comment]
That is *really* neat, thanks! :)
