### ISSUE TITLE
Login Autofill (extension)

### ISSUE THREAD

**Issue by th3g3ntl3m2n** [keepassxreboot/keepassxc#2543]
I have a password saved in KeepassXC for github.com, however, credentials are not detected.
I noticed that by changing the link in KeepassXC to https://github.com/login
Autofill works normally
Could it be fixed to detect by domain?
so anytime I visit https://github.com
It detects the login.
no need to go to https://github.com/login
You understand?

**Comment by th3g3ntl3m2n** [comment]
Yes, Browser Plugin

**Comment by th3g3ntl3m2n** [comment]
Is it possible to add a resource to the plugin, when I enter the github.com domain it asks to allow login (there is something similar) and regardless of the url it logs into the account without going to github.com/login?

I enter the site github.com the plugin does not detect the login fields, so I go in the software and put github.com/login and I go back to github.com/login and it works.
This feature would be excellent!
I am not native American, it may be confusing for you to understand, but I know you will understand.

**Comment by varjolintu** [comment]
What you are describing would possibly work with Auto-Type. It would be easier to just use the login page instead.

**Comment by droidmonkey** [comment]
I don't understand the problem or the requested solution. Unfortunately the translation is not good enough to get the details. Can you explain with pictures instead?
