### ISSUE TITLE
AutoType with locked database doesn't work

### ISSUE THREAD

**Issue by jeff-cook** [keepassxreboot/keepassxc#2547]
## Expected Behavior
When the database is locked, and the user triggers auto-type the vault should be requested to be unlocked, then auto-type should trigger on the app/tab name when the auto-type was triggered.

## Current Behavior
Currently when the database is locked, and the user triggers auto-type the vault is requested to be unlocked, then auto-type is triggered on the app/tab name when the database is unlocked. (which tends to be a KeePass title or even blank.) 

## Steps to Reproduce
1. Lock all open databases.
2. Trigger auto-type via keyboard combo.
3. Unlock database.

## Debug Info
KeePassXC - Version 2.3.4
Revision: 6fe821c

Libraries:
- Qt 5.9.3
- libgcrypt 1.8.2

Operating system: macOS 10.14
CPU architecture: x86_64
Kernel: darwin 18.2.0

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by droidmonkey** [comment]
This is a known issue and there is a fix already for 2.4

**Comment by jeff-cook** [comment]
I looked for it. What is the issue #?

**Comment by jeff-cook** [comment]
This doesn't really describe the issue I'm seeing, but it might be a side effect. I'll see if 2.4 resolves the issue. 

Thank you

**Comment by droidmonkey** [comment]
The code is the same for unlocking for the browser extension as for auto-type. So if you fix it for one it fixes the other.

**Comment by lindenstruth** [comment]
This apparently is still broken on macOS in version 2.4.1
The database is unlocked and auto-type is triggered, but no entry is being found. I have to trigger auto-type again for KeepassXC to find something.

**Comment by droidmonkey** [comment]
I agree, this should be open. There have been a lot of issues opened around this problem so there may be a duplicate somewhere.

**Comment by Joachim-42he** [comment]
Looks like it was fixed in 2.4.3

**Comment by droidmonkey** [comment]
I agree this is not an issue anymore
