### ISSUE TITLE
KeepassXC browser extension doesn't appear to recognise login fields after update to Firefox 64.0

### ISSUE THREAD

**Issue by Xubuntufan** [keepassxreboot/keepassxc#2548]
It seems that after updating Firefox to 64.0 (on Xubuntu Linux) KeepassXC browser extension no longer recognises the [previously recognised] login fields.

Clicking on 'redetect login fields' doesn't appear to solve the problem. 
I am running KeePassXC version: 2.3.4

**Comment by varjolintu** [comment]
Does this happen with all sites? Have you tried to create a new temporary profile in Firefox and see if the update has somehow messed up your default profile?

**Comment by droidmonkey** [comment]
Issue moved to [keepassxreboot/keepassxc-browser #352](https://github.com/keepassxreboot/keepassxc-browser/issues/352) via [**ZenHub**](https://www.zenhub.com/)
