### ISSUE TITLE
ISO feature to defragment the database

### ISSUE THREAD

**Issue by lsiden** [keepassxreboot/keepassxc#2549]
When I first began using KeepassXC, I added an image file to one of my entries.  My database went from 14K in size to 1.3M.  I removed the image, but the database is still 1.3M, even after empying the recycle bin.  

I'm sure there is a gaping hole of unused space in the file that can be eliminated to bring the file back to its original size of a few kilobytes, but I don't know how, other than exporting the DB to a CSV file and then import it again.

It would be cool if there were a way to eliminate unused space in order to keep the file size small when saving it.  I know that 1.3M hardly registers on modern storage mediums and networks, but small is still good when you want to save your file to a thumb drive or copy it to your phone.

If I didn't have a day job I'd poke around and see what kind of storage its using and whether there's a way to do that.

**Comment by droidmonkey** [comment]
There is no reason for defragmenting. If you go into the database settings there will be an option in there to limit the size of history. Move that down to whatever you please and the old image should be erased at that point.

**Comment by phoerious** [comment]
You can also go to the entry's history and delete old versions.
