### ISSUE TITLE
Editing the database prevents auto-locking

### ISSUE THREAD

**Issue by ianrrees** [keepassxreboot/keepassxc#2555]
On Linux with KDE, If the Database Settings are shown in KeePassXC, then the desktop is locked, the KeePass database is kept unlocked with the following popup displayed.  Selecting "Cancel" after waking up the computer will leave the database in an unlocked state.

![image](https://user-images.githubusercontent.com/5280982/50108097-4147ff00-0299-11e9-9e76-0e1a663bb6fe.png)

## Expected Behavior
I would expect the edition to be cancelled, and the database locked as usual.  A compromise might be to prevent the desktop from locking, and pop a modal dialog to the front that explains the reason for preventing the desktop from locking.

## Current Behavior
KeePass database is left unlocked, when the user might not expect it to be

## Steps to Reproduce
1. Open KeePassXC on Linux with KDE
2. Database -> Settings
3. Lock the KDE session
4. Log back in to KDE
5. Observe that KeePassXC now shows a popup containing "Can't lock the datbase as you are currently editing it..." plus Discard and Cancel buttons

## Context
This left my KeePassXC database unlocked, when I didn't expect it to be

## Debug Info
KeePassXC - Version 2.3.4
Revision: 6fe821c

Libraries:
- Qt 5.9.5
- libgcrypt 1.8.1

Operating system: Ubuntu 18.04.1 LTS
CPU architecture: x86_64
Kernel: linux 4.15.0-42-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey
Libraries:
- LIBS

Operating system: OS
CPU architecture: ARCH
Kernel: KERNEL

Enabled extensions:
None, AFAIK

**Comment by droidmonkey** [comment]
This is a duplicate

**Comment by ianrrees** [comment]
Ahh, yes, it's #721 .
