### ISSUE TITLE
Password Quality Column

### ISSUE THREAD

**Issue by Johnex** [keepassxreboot/keepassxc#2556]
Hi!
I would love to see a list option to show the quality of the password in bits, like the QualityColumn plugin does for Keepass 2.

**Comment by kneitinger** [comment]
Hi!  Thanks for the feature request, this appears to be a duplicate of #551 and [this comment which has an interesting suggestion to represent it more minimally with red, yellow, or green dots](https://github.com/keepassxreboot/keepassxc/issues/1091#issuecomment-338442407).

**Comment by Johnex** [comment]
I see yeah. I will keep this one open though since #551 was created in 2017 but still not completed 😃

**Comment by droidmonkey** [comment]
Keeping two issues open doesn't help. #551 is in our backlog, it'll get done.
