### ISSUE TITLE
Download favicons in higher resolution

### ISSUE THREAD

**Issue by livingsilver94** [keepassxreboot/keepassxc#2557]
Current favicon downloader algorithm just fetches, I think (I didn't take a look at the code), the bare favicon of a website, resulting in a very tiny image.
Programs like Firefox, Chromium or browsers in general show a hi-res icon of a website if available, which is desirable nowadays as hidpi are common, especially in smartphones. In fact, bare favicons in Keepass2Android look pixelated. To get a proof of what I'm saying, head to `about:home` in Firefox.
I did a quick search and stumbled upon [this algorithm](https://stackoverflow.com/a/22007642) to download better quality icons. Of course I'm not forcing you to do this, take it as a pure suggestion.

**Comment by droidmonkey** [comment]
Do you have the option enabled to use Google fallback to downloading favicons? We download the highest resolution available and downscale to 128x128.

**Comment by livingsilver94** [comment]
Actually, no. The word "fallback" made me think Google is used as a plan B to download icons, if enabled. Thanks for your tip.
Now, while I prefer to stay away from Google as much as I can, I know this method work and I'll use it. But does it guarantee that the _correct_ icon will be downloaded? The suggestion I provided does, as it fetches the icon directly from the owner website.

**Comment by droidmonkey** [comment]
The method you looked requires parsing html which we will not do. That is the reason for the "fallback". Btw, this was changed in 2.4 to use duckduckgo

**Comment by livingsilver94** [comment]
I have nothing more to say, then. Your statement is clear :smiley:
