### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by ajvsol** [keepassxreboot/keepassxc#2559]
It's been ~4 months since the last release and there has been over 200 commits since, so could we get a new one? I'm dealing with a persistent bug that has been fixed in the snapshot build but I'd rather not rely on an unstable release for managing my valuable data.

**Comment by jpyllman** [comment]
I do not know how hard it would be to move the real bugfixes into a 2.3.5 release if we still waiting for some features for 2.4??

**Comment by droidmonkey** [comment]
We had a little rout where our core team was inundated with real life work. Now that I am free (and hopefully Phoerious) the last few PR's will be merged. The key one for us is the group sharing. We are also strengthening the browser extension as 2.4 will drop support for the http extension. This release will not disappoint, but we are not keen on pushing software out the door that is not holistically ready.

**Comment by phoerious** [comment]
I also want to finish the new icon theme over the holidays. I think after that we're ready for feature freeze and a beta.

**Comment by affinityv** [comment]
Noway macau23 -- that is why there is so much bad software out there.  Let's not every have KPXC turn in to bad software by rushing releases when they are not ready.

**Comment by affinityv** [comment]
No way macau23 -- that is why there is so much bad software out there. Let's not every have KPXC turn in to bad software by rushing releases when they are not ready.

**Comment by affinityv** [comment]
No way macau23 -- that is why there is so much bad software out there. Let's not ever have KPXC turn in to bad software by rushing releases when they are not ready.

**Comment by homonto** [comment]
> No way macau23 -- that is why there is so much bad software out there. Let's not ever have KPXC turn in to bad software by rushing releases when they are not ready.

+1 for that
I am exploring now keepassXC due to complete mess with Enpass that happened after devs released 6.0 that is complete mess - both technically and financially
once I am super happy with keepassXC I will be willing to donate even but please: no mess ;-)

**Comment by macau23** [comment]
> @affinityv: Let's not ever have KPXC turn in to bad software by rushing releases when they are not ready.

Absolutely, but the project changed its release schedule which has made some users worry.

So how about:

~~Release early, release often!~~ Release often with fewer changes!

**Comment by mlippert** [comment]
Releases are work.

KeepassXC works great (thanks!). While I understand the frustration when you've run into a bug that will be fixed in the next release, overall I much prefer stability and infrequent releases. Less frequent releases minimizes the work on getting releases out, and lets that effort be spent on actual improvements.

The only thing I want to see is that the project is still active, and that's apparent to me every time I look at my github notifications. There is a ton of work being done on this project.

**Comment by affinityv** [comment]
> We soft-release every push to the develop branch to https://snapshot.keepassxc.org
> 
> Release early/often works great for no consequence media apps on a smartphone. It requires a store update model to be successful. Wouldn't you feel chapped if a failed "early release" corrupted your database? Even a subsequent update wouldn't help you.

Absolutely.  Even in the mobile world, I want stability first and foremost.
For a password manager, I want ABSOLUTE stability and safety.

**Comment by droidmonkey** [comment]
@homonto, see #488. TouchID requires the binary to be signed. We will do that for our official beta release.

**Comment by droidmonkey** [comment]
@phoerious needs to complete his icon changes or decide to push them to the next release.

**Comment by outdooracorn** [comment]
Guess this be closed now that [2.4 is out](https://github.com/keepassxreboot/keepassxc/releases/tag/2.4.0)?
