### ISSUE TITLE
Autotype - allow space key

### ISSUE THREAD

**Issue by shastry** [keepassxreboot/keepassxc#256]
On certain login pages, there's a need to toggle checkbox - usually with the space bar

## Expected Behavior
{SPACE} in autotype sequence should send space key press.

## Current Behavior
On macOS, there's no way to to this.
On Linux (Fedora 25), typing a literal space in the autotype sequence seems to work.

## Possible Solution
Make {SPACE} send the space key.

## Steps to Reproduce (for bugs)
Use {TAB}{TAB}{SPACE}, for example, on any page with a checkbox.

## Your Environment
* KeePassXC 2.1.0 official binary.
* Qt version: 5.7.0
* Operating System and version: macOS Sierra 10.12.3

**Comment by droidmonkey** [comment]
I endorse this, excellent suggestion

**Comment by TheZ3ro** [comment]
I'm surprised to know this isn't already implemented. I will look into this

**Comment by piyushgarg** [comment]
As a workaround you can use ' ' space char in the autotype for eg {PASSWORD} {ENTER}

**Comment by TheZ3ro** [comment]
{SPACE} should works now
