### ISSUE TITLE
KeepassXC + Yubikey compatability with Keepass + Yubikey

### ISSUE THREAD

**Issue by ludekvodicka** [keepassxreboot/keepassxc#2560]
I'm trying to access my KeePass DB protected with password + Yubikey challenge-response on my work OSX where I installed KeepassXC.

Unfortunately I'm getting invalid key / file corrupted messages no matter if I created DB on Windows and try to open it in OSX KeepassXC or vice versa.

Is there any way how to use both KeePass + Yubikey and KeePassXC + Yubikey?

## Steps to Reproduce
1. Create DB on Windows KeePass, protect it with passwod + Yubikey 4 challenge-response
2. Try to open DB on KeePassXC on OSX.

Note: I tried KeePassXC on windows with the same results. So OSX isn't important here. The problem seems to be in incompatibility between KeePass and KeePassXC Yubikey usage.

Thanks

**Comment by droidmonkey** [comment]
The two are not compatible because of different implementations of the Yubikey methods

**Comment by ludekvodicka** [comment]
Thanks for quick reply. It's pitty. 

is there any other way how to use Yubikey and both keepass versions?

**Comment by droidmonkey** [comment]
Not at this time, no. The KeeChallenge plugin would have to be modified to support our method. Why not use KeePassXC on all computers?

**Comment by ludekvodicka** [comment]
I'm using some other plugins. I have to check what KeePassXC is offering. If possible, I can migrate to KeePassXC completely ;-)
