### ISSUE TITLE
macOS Mojave: KeepassXC + Yubikey (each second time the Challenge Response field not active 

### ISSUE THREAD

**Issue by PeterWq** [keepassxreboot/keepassxc#2561]
After upgraded the OS to Mojave, keepassxc doesn't see the yubikee in 50% of times and need to reboot to work again (in rare cases even 2 reboots)

KeepassXC ver. 2.3.4

## Expected Behavior
KeepassXC should not need to reboot to work with yubikey challenge response

## Steps to Reproduce
1. Already occurs a few times in the last week. some time several times per day.
2. The KeepassXC stop displaying the yubikey in the Challenge Response field and the field is not active. This happens randomly, but today for example it happens 2 times already. 
Yubikey is working as I'm using for password input too and that is working each time I long touch the yubikey 

Operating system: macOS ver. 10.14.2
MacBook Pro (15-inch, 2017)
3.1 GHz Intel Core i7
16 GB 2133 MHz LPDDR3

Enabled extensions: no extensions

**Comment by droidmonkey** [comment]
I'll look into this today

**Comment by droidmonkey** [comment]
I could not replicate this issue with the 2.4.0-beta1 build. Can you both please try using this build which is signed and can be used for limited testing at this point?

https://keepassxc.org/download/#mac

**Comment by alborworld** [comment]
Thanks. I know, it's difficult to reproduce. I have installed the version
you proposed. I will let you know.

**Comment by PeterWq** [comment]
Hi Jonathan, 
I will test and report back, but could you provide the PGP signature file for the KeePassXC-2.4.0-beta1.dmg, please? The keepass is the home for all my passwords and trying to keep them safe.
Thanks

**Comment by droidmonkey** [comment]
I have posted an updated DMG and signature/digest for your use.

**Comment by PeterWq** [comment]
my feedback here:
1) the keepassxc beta  crashed one time (need to mention that it was open for quite long time about 1-1.5 hours);
2) the command + U (open the url in browser) is not working. It was working in previous version (it was opening the URL from the entry in the default browser).
3) it never failed to display the yubukey (challenge response )in the last 11 days so I will consider this issue fixed.

**Comment by droidmonkey** [comment]
Cmd+U moved to CMD+SHIFT+U

**Comment by PeterWq** [comment]
Hi Jonathan, 

Sorry to say but the above issue it still happens time to time on macOS Mojave (ver 10.14.3). Not so often as before but when it happens (last week happened 2-3 times per week, last 2 days once per day) it's right when you need to login and that is annoying. 
I noticed that  just leave the computer for some time (usually after the mac goes to sleep) and after  the challenge response is available or if you need right away you need to restart the laptop. It's not a huge problem to restart but when you have a few dozens of web pages and applications open that requires log in of some sort is quite a pain in the ass to get all of them back. 

Still using the KeePassXC 2.4.0-beta1 (the 2.4.0 is missing from the download page, waiting till next week to be added the signature by Janek)

**Comment by droidmonkey** [comment]
Let me know if the official 2.4.0 resolves it for you, we did some yubikey cleanups for the final build.

**Comment by PeterWq** [comment]
Installed the 2.4.0 on 03/25/2019 and using KeepassXC almost daily.
In 3 days (maybe 14-16 times used the password manager) and 2 times the Challenge Response field was not active (that means I was not able to open the KeepassXC without restarting the mac or just try later and hope it will work next time).

**Comment by PeterWq** [comment]
Hi Jonathan,
This issue is still reproducible on latest version (2.4.1).
It's rare but still happening time to time. 
Is there anything that could be done to help fix this annoying issue?

**Comment by droidmonkey** [comment]
It is very strange that you have to do a full restart to gain functionality again. I do not know why this would be happening to you.

**Comment by PeterWq** [comment]
> I also noticed this issue, which is becoming quite annoying, as I use KeepassXC + YubiKey for work.
> 
> I will really appreciate a quick solution to this. Thanks.

@alborworld
Do you still have this issue reproducible on your computer?
I'm using latest 2.4.3 version and still time to time it's reproducible.

@droidmonkey
I'm using sleep on my mac a lot, just closing the lid and after open it and using father, but I didn't noticed any pattern that will allow to reproduce each time. What I have noticed is that when this happens, the yubikey Personalization Tool could not detect my yubikey too (and I have tried with other 2 yubikeys that I have as backup) and display "Unknown error occurred". I have opened a ticket with yubico support too.
