### ISSUE TITLE
Reset auto-lock timer when application window is interacted with

### ISSUE THREAD

**Issue by gruffle7** [keepassxreboot/keepassxc#2566]
## Expected Behavior
[NOTE]: # ( If you're describing a bug, tell us what should happen )
[NOTE]: # ( If you're suggesting a change/improvement, tell us how it should work )
According to how keepass2 works with mono under Ubuntu, if you minimize the window and the timeout for the "auto lock database" expires, it will lock it, however if you click on the window and idle in the window, it will reset the timer, in other words it won't continue to auto-lock the database.  Unless the window idles in the minimized position or idles in the active window with no cursor click movement.

This should work the same with keepassXC.

## Current Behavior
[NOTE]: # ( If describing a bug, tell us what happens instead of the expected behavior )
[NOTE]: # ( If suggesting a change/improvement, explain the difference from the current behavior )
Currently i have noticed that it doesn't reset the timer for auto-locking the DB while clicking in the active window OR switching between groups, OR clicking inside the white space.  Any one of these SHOULD trigger a timer reset.  Currently what is the trigger for a timer reset?  If im wrong, please tell me.  However this is what i have noticed.

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1. Set a timer for auto-lock DB
2. Wait for the required amount of time while minimizing window and opening again.
3. DB locks regardless if the window gets maximized/opens from minimized position.

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.3.4

Operating system: Ubuntu 18.04
Kernel: 4.15

**Comment by darkwing1** [comment]
I think what he means is that **mouse movements** within the window should reset the timer.   Is this currently the case?  Because i havent tested it.

**Comment by droidmonkey** [comment]
I actually do not agree with this request as written.

**Comment by darkwing1** [comment]
No i dont agree with that either.  But IF the mouse _actually moves_ on the active window then dont lock. Else, lock if the mouse _does not move_ on the active window.  Can't you do that?  This is how keepass had it implemented i believe.

**Comment by droidmonkey** [comment]
I'm sure we can
