### ISSUE TITLE
Folder can only creat a subfolder

### ISSUE THREAD

**Issue by pjc123** [keepassxreboot/keepassxc#2567]
When I create a new entry in one specific folder it should have the key icon, not a folder icon, but it makes a folder icon.  Note that this only started happening in one folder.  All other folders are fine.  Deleting the Folder and recreating all items fixed the problem.  I don't know how to recreate the problem and this is the first time it happened in many months of use. Just posting in the event that others might come across this issue.

**Comment by droidmonkey** [comment]
This means the folder had the "use folder icon for new entries" setting enabled. It is not a bug, but a feature.

**Comment by pjc123** [comment]
Thanks.  I guess I somehow must have ticked that setting by accident.  Now I know if it happens again.

**Comment by droidmonkey** [comment]
Also you can always change the icon of an entry in the edit view.
