### ISSUE TITLE
Adding a copy TOTP button

### ISSUE THREAD

**Issue by rderensy** [keepassxreboot/keepassxc#2568]
Hi!

There should be a "copy TOTP" button like there are "copy username" and "copy password" buttons. It's not very convenient to right click on the entry and select "time-based one-time password" and then click on "copy TOTP".

**Comment by droidmonkey** [comment]
We added a TOTP column in 2.4 displays "Yes" if an entry has TOTP and can be double clicked to copy the current code to clipboard. I use this in the snapshot builds and is very convienent. At this time we do not want to add any more toolbar icons.

**Comment by phoerious** [comment]
I think, however, there should be a button in the preview panel. The TOTP column isn't so discoverable I would guess. Maybe make the displayed code there clickable.

**Comment by droidmonkey** [comment]
The preview panel has a little stopwatch icon next to the close icon if TOTP exists. It is a little hidden though

**Comment by Birch-san** [comment]
I agree that the mouse UX is arduous.

I usually select the entry (keyboard or mouse) then _use the keyboard shortcut Cmd+T_ to copy a TOTP to clipboard.

**Comment by Gustry** [comment]
> We added a TOTP column in 2.4 that displays "Yes" if an entry has TOTP and can be double clicked to copy the current code to clipboard.

Whaou, this saved my day ! Thanks, quite hidden but very useful!

Why not adding a small icon copy to clipboard next to the `yes`? (icon only) So it's more obvious there is an action possible in this cell.

**Comment by droidmonkey** [comment]
Adding an action to a cell is non-trivial (this is a technical Qt/C++ response). I am investigating a floating action bar for the selected row as an alternative. That is also non-trivial but more robust then each column getting an icon shoved in it.

**Comment by frederickjh** [comment]
Wow I just learned something new about KeePassXC. I normally have it in a half window. Never realized that there were more columns. I figured out you can just drag the TOTP column to the left so it is one of the visible columns when not full screen. The username and password fields can also be double clicked to copy their contents.

Is this information in the documentation?  If it isn't then it is more of an EasterEgg than a hidden feature.

**Comment by vuntz** [comment]
For the record, Ctrl+T does copy the TOTP.

**Comment by droidmonkey** [comment]
Also for the record, when you update to 2.6.0 the attachment column and totp column will be the first two in the view making it far easier to discover this feature.

**Comment by spikespaz** [comment]
I use KeePassXC on half my screen (tiling WM), so horizontal space is important. Needing to keep the "Has TOTP" column is therefore obnoxious.

I understand that the toolbar currently is aesthetically pleasing and this is why you do not want to add any more buttons, but perhaps this could be configurable. Just a list of checkboxes in the UI settings that enables/disables buttons from being visible. Keep the defaults to show what is already shown and everyone is happy.
