### ISSUE TITLE
Ability to prune old history

### ISSUE THREAD

**Issue by StephenWetzel** [keepassxreboot/keepassxc#2570]
## Expected Behavior
A function somewhere that will prune all history entries older than 30 days.

## Current Behavior
As far as I can tell, the only way to delete history entries currently is to go into each entry and look at its history individually.  This is quite slow, and error prone if you have a lot of entries.

## Possible Solution
A menu option somewhere that says "delete history older than 30 days" would work.  The ability to choose a custom period would be a bonus.

## Context
I recently discovered that KeepassXC keeps a history of every version of each entry.  This is a useful protection, but I'd like to be able to remove old history (older than 30 days).  Both to help keep the database size smaller, and so I don't have to worry about sensitive information in the history.

**Comment by phoerious** [comment]
There is a setting for that in the database settings. Old entries will be pruned automatically when the database is saved.

**Comment by liar666** [comment]
Hi,

I just discovered this "issue" of KeePass's `.kdbx` files keeping backups of old entries... Followed @phoerious proposed configuration. DID NOT work. I STILL see the backup entries!!!!

FYI, I very paranoid, so I somewhat "obfuscate" the passes I store in KeepPassXC, just in case someone sees my screen when I inadvertently click the "see/eye" button when I'm at work.

What I did:
- Typed `keepassxc-cli export mydb.kdbx | grep <old not obfuscated pass>`
- I've discovered I had forgotten to obfuscate a few entries.
- So I opened KeePassXC and obfuscated these entries
- Typed again `keepassxc-cli export mydb.kdbx | grep <old not obfuscated pass>`
- Still see the entries, search google for KeePass storing backup of entries 
- Discovered the present issue
- Went to change the set up as @phoerious proposed: configured #entries to 0 and max backup size to 0MB.
- Modified a little the DB & Saved it (in fact done automatically), as the DB is supposed to be pruned on Save action.
- Typed again `keepassxc-cli export mydb.kdbx | grep <old not obfuscated pass>`
- Old non-obfuscated password still appear....

Conclusion: there's a bug in the pruning of the history...

**Comment by droidmonkey** [comment]
Just uncheck the boxes next to the history settings. Either way your workflow is totally unnecessary and you are seriously wasting your time. If you have actual randomized passwords there is no way anyone can eavesdrop copy them by visual site.

**Comment by liar666** [comment]
Hi,
Thanks for the tips.
Just remember that not everyone as the same environment. When you're surrounded by geeks with GoogleGlasses and always-on-mobile-phone-or-cameras, however complex your password is, a few millisecond look at your screen is sufficient to get it.

**Comment by liar666** [comment]
Hi again,

Sorry I responded quite quickly... After testing more thoroughly, it seems that completely removing history is still not done even after unchecking the boxes:

![bug](https://user-images.githubusercontent.com/3216927/103090871-a6562e00-45f2-11eb-96e1-1150c18ab406.png)
![bug2](https://user-images.githubusercontent.com/3216927/103090875-a9511e80-45f2-11eb-9271-db8e1475d463.png)

+ Image1 shows that there is still some history for some entries, even after unchecking the boxes
+ Image2 shows 1) that boxes are unchecked 2) that memory value is *always* reset to 6291456 MiB, whatever value I enter + whatever the checkbox status is. Similarly "history items" is always reset to 10.

**Comment by phoerious** [comment]
You are holding it wrong. Unchecking the limits means no limit. You have to set the limit to 0.

**Comment by droidmonkey** [comment]
That is counter intuitive. Disabling history does not mean unlimited history.

**Comment by phoerious** [comment]
Maybe I'm mistaken. But I always set it to zero when I needed to get rid of it. That definitely works.

**Comment by NysNight** [comment]
Not gonna lie, this stuff is quite unintuitive. So my problem today was that an exported .csv that I then imported in KeePassXC had all it's usernames in the Title field and all the passwords in the Username field, passwords blank.

So I edited them all and then noticed the history still showed my passwords in clear-text...

Even just one button to clear the history, it would be really helpfull.

**Comment by droidmonkey** [comment]
When you imported the csv you failed to align the columns to the fields.
