### ISSUE TITLE
TouchID usage in newest build (2018-12-31 01:14)

### ISSUE THREAD

**Issue by kitzler-walli** [keepassxreboot/keepassxc#2571]
I just downloaded the newest build from your snapshot website and wanted to test the touchid feature but am not able to use it - probably I'm using it wrong.

## Expected Behavior
In the security settings of the app I unchecked the box for "Forget TouchID when session is locked" and now I would expect to be able to use TouchID after my computer locks.

## Current Behavior
After unlocking my mac I have to input my password again - using touchid is not possible.

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1. Uncheck "Forget TouchID when session is locked" in settings
2. Unlock your database
3. Lock your mac
4. Unlock your mac
5. Try to use Touchid to unlock database

Operating system: macOS Mojave

**Comment by homonto** [comment]
same here - even if the timeout expires you cannot unlock it with Touch ID - only full password helps

actually either Touch ID or PIN would be appreciated to fast unlock the db

**Comment by weslly** [comment]
I can reproduce this, but I'm not sure if it's because I'm testing with `LAPolicy.DeviceOwnerAuthentication` instead. I'll take a better look at it.

**Comment by homonto** [comment]
considering that master password should be looooong and haaard or even with keyfile PIN or TouchID is much appreciated ;-)
thank you

**Comment by MeCrazyJunkie** [comment]
I have touchId doesn't work at all. Installed from source 2019-01-12.

**Comment by weslly** [comment]
@droidmonkey Was this build code signed?

**Comment by droidmonkey** [comment]
No snapshots are not signed

**Comment by weslly** [comment]
@droidmonkey TouchID requires codesigning

**Comment by droidmonkey** [comment]
OK, well then this can be closed!

**Comment by MeCrazyJunkie** [comment]
How can I sign my build? Is Apple Developer Membership required?

**Comment by droidmonkey** [comment]
Yes you need to pay the $99 annual fee and be approved by Apple

**Comment by MeCrazyJunkie** [comment]
@weslly thank you, I'll try to do that
