### ISSUE TITLE
CLI export DB in CSV format

### ISSUE THREAD

**Issue by AlFalahTaieb** [keepassxreboot/keepassxc#2572]
## Expected Behavior
Should be able to export my databse through CLI to the CSV format.

## Current Behavior
Unable to export export database with CLI to CSV file.

## Possible Solution

Is there a way to add it ?

## Context
I'm creating a cron job i want to synchronize my Databse once a week and send it to my server on a CSV Format

**Comment by louib** [comment]
> Is there a way to add it ?

Sure there is. Would you be willing to work on that? if so, you could reuse the `extract` CLI command, or create a new `export` command.
