### ISSUE TITLE
Location of ini file in Windows system

### ISSUE THREAD

**Issue by chabis0815** [keepassxreboot/keepassxc#2574]
## Expected Behavior
INI file should be available for roaming users in Windows so that all data is found after re-login

## Current Behavior
INI file is located in "APPDATA\Local", which is not saved to network share

## Possible Solution
INI file should be saved in "APPDATA\Roaming"

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.3.4.0

Operating system: Windows 10
CPU architecture: x64

**Comment by chabis0815** [comment]
Thank you for your response!
Actually this is not an option for me, as the users can still start the program without that argument and would not be able to access their environment.
So I guess I have to wait ... ;-)

**Comment by phoerious** [comment]
We should split our configuration into system-specific things such as recently opened databases and the actual settings.

**Comment by opsi-archIT-KIT** [comment]
I would assume that splitting configuration file is not so easy to implement.

Why not change first the default of the location of "keepassxc.ini" from %LocalAppData% to %AppData% in windows packaging tool? I think this should be implemented quite fast.

And secondly implement splitting configuration.
