### ISSUE TITLE
Document how to use a backup of a secret key from YubiKey

### ISSUE THREAD

**Issue by ts-mk** [keepassxreboot/keepassxc#2577]
The FAQ mentions that...

> You should always make a copy of the HMAC secret that is stored on the YubiKey and keep it in a secure location. This can be an analog paper copy...

It's not exactly clear to me how the backup of the secret should be used even though I know how to use it to calculate an HMAC hash and I have already verified that I get the same result as in the Challenge-Response Tester tool of the YubiKey Personalization Tool. The problem can be summed up as:

1. How exactly KeePassXC uses YubiKey. What does it pass to it as the message?
2. How a calculated hash can be passed to KeePassXC.

It's obviously best to have another YubiKey and configure it with the backup secret just as the rest of the FAQ answer mentions but in an emergency situation when a spare YubiKey is not immediately available it would be great to have a documentation on how a calculated hash could be used to **access the database without YubiKey**.

**Comment by genepine** [comment]
Just comment.
I can write the same Challenge Response Credential to backup second Yubikey by official YubiKey Manager.
https://support.yubico.com/hc/en-us/articles/360013779759-Using-Your-YubiKey-with-KeePass
Step 5. Save Challenge Response Credential for master Yubikey to text file, and write same Challenge Response Credential  to Backup  second Yubikey by YubiKey Manager.

And I can open the same database Master/Backup Yubikey on KeePassXC 2.7.6

This procedure didn't work for me to create a Yubikey clone.
I think it would be a good idea to correct the example in the documentation if possible.
https://keepassxc.org/docs/#faq-yubikey-howto
and 
https://www.youtube.com/watch?v=r6Qe9Z-kOH0
