### ISSUE TITLE
snap, insufficient plugs, apparmor logs error

### ISSUE THREAD

**Issue by varmando** [keepassxreboot/keepassxc#258]
[ 4816.562182] audit: type=1400 audit(1486373800.010:1125): apparmor="DENIED" operation="create" profile="snap.keepassxc.keepassxc" pid=9794 comm=517420626561726572207468726561 family="netlink" sock_type="raw" protocol=0 requested_mask="create" denied_mask="create"

## Expected Behavior

no denied messages from apparmor

## Current Behavior

[ 4816.562182] audit: type=1400 audit(1486373800.010:1125): apparmor="DENIED" operation="create" profile="snap.keepassxc.keepassxc" pid=9794 comm=517420626561726572207468726561 family="netlink" sock_type="raw" protocol=0 requested_mask="create" denied_mask="create"

## Possible Solution

# /snap/bin/snappy-debug.security scanlog keepassxc
kernel.printk_ratelimit = 0
= AppArmor =
Time: Feb  6 11:47:10
Log: apparmor="DENIED" operation="create" profile="snap.keepassxc.keepassxc" pid=9794 comm=517420626561726572207468726561 family="netlink" sock_type="raw" protocol=0 requested_mask="create" denied_mask="create"
Suggestion:
* add 'network-control' to 'plugs'

## Steps to Reproduce (for bugs)

1. install keepassxc snap
2. observe syslog

## Your Environment

* KeePassXC version/commit used: (can be found under Help -> About)
2.1.0
* Qt version (e.g. Qt 5.3): 
* Compiler (e.g. Clang++3.6.0): 
* Operating System and version: 
ubuntu 16.10

**Comment by dev00** [comment]
This will (obviously) also break any support for chromeIPass and PassIFox since there is no listener. Disabling AppArmor is a bad idea and will not help since that will shutdown anything with snap.

**Comment by phoerious** [comment]
Missing network permissions breaks all network-related stuff I would guess. We haven't yet updated the Snap to the latest release, but we'll address this when we do.

**Comment by droidmonkey** [comment]
The correct snap plugs are "network" and "network-bind". I just published the 2.1.2 release snap on the ubuntu store, check it out!

**Comment by phoerious** [comment]
Should be fixed by #333.
