### ISSUE TITLE
Unable to open KDBX 4.0 database created by Strongbox

### ISSUE THREAD

**Issue by vinzf** [keepassxreboot/keepassxc#2581]
KeePassXC fails to open KDBX 4.0 database created by Strongbox.
It fails with error mesage "_Unsupported key derivation function (KDF) or invalid parameters_":

![image](https://user-images.githubusercontent.com/29705843/50724918-92f3e480-10f5-11e9-8469-05d9e558e5e8.png)

Here is a sample file using the password "1234"

[strongbox.kdbx.gz](https://github.com/keepassxreboot/keepassxc/files/2729534/strongbox.kdbx.gz)

Also see Strongbox issue https://github.com/mmcguill/Strongbox/issues/23

## Debug Info
KeePassXC - Version 2.3.4
Revision: 6fe821c

Libraries:
- Qt 5.9.3
- libgcrypt 1.8.2

Operating system: OS X El Capitan (10.11)
CPU architecture: x86_64
Kernel: darwin 15.6.0

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by droidmonkey** [comment]
This is not a KeePassXC issue. We implement Argon2 according to the KeePass2 specification and are fully compatible with KeePass2 databases.

**Comment by vinzf** [comment]
Perfect, thanks for checking/verifying 👍

**Comment by droidmonkey** [comment]
Can you tell me what you used for the three parameters in the sample kdbx you posted. Specifically threads, memory, and iterations.

**Comment by vinzf** [comment]
Unfortunately not, since Strongbox does not let the user modify these parameters.

![image](https://user-images.githubusercontent.com/29705843/50735132-bc6e4800-11a9-11e9-9ccd-a6776d5869ab.png)

I guess it uses the defaults defined in https://github.com/mmcguill/Strongbox/blob/master/model/keepass/Argon2KdfCipher.m
``` C
static const uint64_t kDefaultIterations = 2;
static const uint64_t kDefaultMemory = 1024 * 1024;
static const uint32_t kDefaultParallelism = 2;
```

@mmcguill should know ...

**Comment by mmcguill** [comment]
@vincf is correct, for new databases those are the defaults that will be used. I believe the issue is with Strongbox using 16 rather than 32 byte salt by default. I’ll get this change in in the next release.

**Comment by droidmonkey** [comment]
@mmcguill cheers thanks for looking into this. It's great to have all kdbx apps able to interoperate with each other. Also, I'll be skiing out at Park City next week, enjoy the fresh POW!

**Comment by mmcguill** [comment]
@droidmonkey Thanks a mill! Agreed, good to have this KDBX interoperability. I'm based here in Europe, but we're getting some nice fresh stuff in the Alps too!! Have a great one out there, enjoy the POWPOW!

**Comment by vinzf** [comment]
Just FYI: Keepass2Android (Version 1.06f) does not have any issues with this database created by Strongbox.

**Comment by vinzf** [comment]
I've  compiled the current develop branch and verified that the seed size 16 is what keeps KeePassXC from opening that file.

https://github.com/keepassxreboot/keepassxc/blob/develop/src/crypto/kdf/Kdf.cpp#L57

```C
bool Kdf::setSeed(const QByteArray& seed)
{
    if (seed.size() != m_seed.size()) {
        return false;
    }
    m_seed = seed;
    return true;
}
```

`m_seed` is 32 bytes (it was inititialized with `KDF_DEFAULT_SEED_SIZE` which is 32) whereas the Strongbox seed has 16 bytes.

However, after removing that size check the file opens perfectly fine in KeePassXC.

**Comment by droidmonkey** [comment]
This is where we fail due to the 16 byte seed: https://github.com/keepassxreboot/keepassxc/blob/develop/src/crypto/kdf/Kdf.cpp#L59

It checks to see if the supplied seed size is the same as the expected seed size (32 bytes). We could loosen this check, but technically it is against KDBX standards _AND_ less secure.

**Comment by vinzf** [comment]
Maybe it is best to loosen the check according to what is being done in the _official_ source from `KeePass-2.40-Source.zip` in `KeePassLib/Cryptography/KeyDerivation/Argon2Kdf.cs` line 105:

```cs
if((pbSalt.Length < MinSalt) || (pbSalt.Length > MaxSalt))
    throw new ArgumentOutOfRangeException("p.Salt");
```
These are defined in the same file at line 44
```cs
private const int MinSalt = 8;
private const int MaxSalt = int.MaxValue; // .NET limit; 2^32 - 1 in spec
```

**Comment by droidmonkey** [comment]
Huh, I am pretty sure that code is in error since it would accept a salt length of 4,294,967,295.

**Comment by vinzf** [comment]
Saw that too, better safe than sorry ;)

**Comment by droidmonkey** [comment]
No that is a big problem. Can definitely lead to memory over allocation.
