### ISSUE TITLE
Use reproducible builds

### ISSUE THREAD

**Issue by nagromc** [keepassxreboot/keepassxc#2582]
To have a complete chain of trust, a software should:
1. have signed tags, and maybe commits (the writing part) ;
2. use [reproducible builds](https://en.wikipedia.org/wiki/Reproducible_builds) (the compiling part) ;
3. provide digital signatures of the final builds like OpenPGP, Authenticode, etc. (the distribution part).

Steps `1.` and `3.` are completed; great!

But to complete this chain of trust, the project should also comply with step `2.` (the compiling part). If it's already done, there should be some documentation to let users verify it by themselves.

Notable projects already follow the recommendations given on https://reproducible-builds.org/ : Arch Linux, Bitcoin, Debian, FreeBSD, Fedora, OpenWRT, Tails, Tor, etc.

**Comment by droidmonkey** [comment]
We use the release-tool to build releases and it is absolutely reproducible on all platforms.

**Comment by phoerious** [comment]
Do we still have a build path constant in the code? I think that was the only problem we had with reproducible builds.
