### ISSUE TITLE
database not locked when session is locked?

### ISSUE THREAD

**Issue by muchqs** [keepassxreboot/keepassxc#2585]
## Expected Behavior
There is an option "lock databases when session is locked or lid is closed". I assumed the databases would be locked when I manually lock my Windows session.

## Current Behavior
When I manually lock my Windows sessions using Windows Key + L, the databases do not lock. I can come back to my PC, unlock the session, and can immediately use KeePassXC without unlocking the databases.

## Possible Solution
Databases should lock when locking Windows session.

## Steps to Reproduce
1. lock Windows session using WinKey+L.
2. unlock the session
3. databases are not locked

## Debug Info
KeePassXC - Version 2.3.4
Revision: 6fe821c

Libraries:
- Qt 5.11.1
- libgcrypt 1.8.3

Operating system: Windows 10 (10.0)
CPU architecture: x86_64
Kernel: winnt 10.0.17134

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by muchqs** [comment]
Usually I have it in the system tray, but I just tested with it open and it didn't lock.

**Comment by Freekers** [comment]
I suspect it's the same bug as I reported earlier here: https://github.com/keepassxreboot/keepassxc/issues/2379

**Comment by muchqs** [comment]
Certainly looks like the same issue. I'll wait for the next version
