### ISSUE TITLE
LastKeyFiles in keepassxc.ini causing: Unable to open the database. Wrong key or database file is corrupt. (macOS Mojave)

### ISSUE THREAD

**Issue by jwatt** [keepassxreboot/keepassxc#2586]
I've been unable to open my password database, getting the message:

```
  Unable to open the database.
  Wrong key or database file is corrupt.
```

After a lot of trial and error with backups it turns out that - very weirdly - if I rename the latest, broken .kdbx file, then I can open it. If I rename it back to the old name, it stops working again. I.e. file/directory permissions are unchanged. If I copy it instead of renaming it, `diff` shows the contents to be identical.

I then started looking for cached KeePassXC data that might cause this and tracked the issue down to the LastKeyFiles line in my keepassxc.ini. (This line is 340 characters long.) For whatever reason the value this line contains makes KeePassXC think the DB is corrupt when stored it its original location on the filesystem. Closing KeePassXC, deleting that line, then restarting KeePassXC gets things working again.

The bug occurs regardless of whether KeePassXC is opened by double clicking on my DB, or whether KeePassXC was already open and I opened the DB by navigating to it in KeePassXC using the "Browser" button.

## Debug Info

KeePassXC - Version 2.3.4
Revision: 6fe821c

Libraries:
- Qt 5.9.3
- libgcrypt 1.8.2

Operating system: macOS 10.14
CPU architecture: x86_64
Kernel: darwin 18.2.0

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by droidmonkey** [comment]
This is likely because you accidentally selected a keyfile for this file and now it "remembers" this and has the keyfile portion of the unlock dialog checked. Please check to see if the keyfile box is checked because that will cause the corruption message.
