### ISSUE TITLE
Need for KeepassXC to be started [at browser launch]

### ISSUE THREAD

**Issue by LeGast00n** [keepassxreboot/keepassxc#2587]
## Expected Behavior
Hi there,
I'm looking into KeepassXC for my Ubuntu 18.x workstation but I cannot make it painlessly work with the Firefox keepass-browser extension: the proxy is not launching KeepassXC, and anyway the principle of launching the app, then unlocking the DB before anything is painful.
Why not planning to make the functionality of KeepassXC available through a daemon or dynamic linking libraries? Unlocking could be sought ad-hoc when needed.
If I may point to a source for inspiration (with all credits and respect for your work), I find the user experience with 1Password a good benchmark.
krgds,
LA

**Comment by droidmonkey** [comment]
Requiring KeePassXC to be running separate from the browser is not going to change. If you are using the proxy method, than you have to run KeePassXC in the background. Unlocking the database is a core component to the KeePass security model and will not change. I am sorry, but perhaps KeeWeb or 1Password would be a better fit for you if you find this unacceptable.

**Comment by LeGast00n** [comment]
Hello, thanks for your reply. I did not mean there should not be preliminary DB unlocking. I'm saying that the way this is meant to be operated is not really seamless.
My understanding is: KeepassXC should be running "in the background". Which practically means, from what I can notice: launching KeepassXC manually (it's not starting automatically, unless one adds it to the apps to be started with the user session), unlock the DB from the KeepassXC window, connect the browser plugin then minimize the app window (which is what I understand stands for "running in the background" in your terminology). I understand that any subsequent plugin that would be willing to connect would require user to ensure the DB is unlocked prior to connecting.
As a comparison with the type of SW I mentioned, I open the browser, do not need to care for "connection" with something. When I need a password, I can operate the DB unlocking directly from the browser add-on. Whether there is something running "in the background" to perform this is none of a user consideration. When I need to perform advanced tasks on the DB, I can launch the application (i.e. in the "foreground").

**Comment by droidmonkey** [comment]
Correct, and our application's philosophy is that almost nothing happens in the browser except passing requested credentials for a particular site. There are a couple of extensions that let you open a KDBX file directly from within your browser (see https://subdavis.com/Tusk/).

As for KeePassXC, once you have connected the extension to your database they process is very seamless. The only added action you have to do is unlock the database. I do recommend starting KeePassXC on user login.
