### ISSUE TITLE
KeePassXC Database is not Saved When Using "save database as"

### ISSUE THREAD

**Issue by 0x1080** [keepassxreboot/keepassxc#2588]
When I click Database/"Save database as" in keepassXC, the program only saves to the temporary file in a folder located in  /run/user/1000/doc/ , which is deleted when the program is closed. It does not save the database to the location selected in the "save database as" dialog. Nothing is saved to the original file either, so you lose any new changes. 

## Expected Behavior
It saves the database to the name and path entered in the "save database as" dialog.

## Current Behavior
Nothing is saved and no new file is created outside of  /run/user/1000/doc/ (which can be automatically deleted)

## Steps to Reproduce
Open database, use "save database as."

KeePassXC - Version 2.3.4
Revision: 6fe821c
Distribution: Flatpak

Libraries:
- Qt 5.9.7
- libgcrypt 1.7.3

Operating system: Linux 4.15.0-20-generic
CPU architecture: x86_64
Kernel: linux 4.15.0-20-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by droidmonkey** [comment]
See https://github.com/keepassxreboot/keepassxc/issues/2578#issuecomment-451543081
