### ISSUE TITLE
Minimize main window after opening database

### ISSUE THREAD

**Issue by wohali** [keepassxreboot/keepassxc#2590]
## Expected Behavior
Another KeePass feature that I'd love to see in KeePassXC is the ability to minimize the main window after opening the database.

I don't use "minimize on startup" with KeePassXC because I want to type in my passphrase. But, once that's done, I'd like the window to minimize itself.

## Current Behavior
Currently I can either minimize on startup (and then manually select my DB and enter its passphrase) or I can start normally. Either way I must manually minimize after the DB is opened.

## Context
Reduce the number of clicks by one when interacting with KeePassXC. :wink: 

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug, )
[NOTE]: # ( or ideas how to implement the addition or change )

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1.
2.
3.

## Context
[NOTE]: # ( How has this issue affected you? What are you trying to accomplish? )
[NOTE]: # ( Providing context helps us come up with a solution that is most useful in the real world )

## Debug Info
KeePassXC - Version 2.3.4
Revision: 6fe821c

Libraries:
- Qt 5.7.1
- libgcrypt 1.8.4

Operating system: Debian GNU/Linux 9 (stretch)
CPU architecture: x86_64
Kernel: linux 4.18.0-0.bpo.3-amd64

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by varjolintu** [comment]
Please don't remove the issue template when making a new issue.

What is your OS and KeePassXC version?
