### ISSUE TITLE
[Feature] .appx file for windows

### ISSUE THREAD

**Issue by piu130** [keepassxreboot/keepassxc#2591]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( Do not include screenshots of your actual database! )

## Expected Behavior
[NOTE]: # ( If you're describing a bug, tell us what should happen )
[NOTE]: # ( If you're suggesting a change/improvement, tell us how it should work )
It would be nice to have a `.appx` file for windows to install it as an app. This would improve the installation, update and uninstall process and would make the app ready for the windows future.

## Current Behavior
[NOTE]: # ( If describing a bug, tell us what happens instead of the expected behavior )
[NOTE]: # ( If suggesting a change/improvement, explain the difference from the current behavior )
Currently there is only a `.exe` and `.msi` build.

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug, )
[NOTE]: # ( or ideas how to implement the addition or change )
There is something called [Desktop Bridge](https://docs.microsoft.com/en-us/windows/uwp/porting/desktop-to-uwp-root) to migrate 'older' installers. I don't know anything about the code base so I don't know if it would be hard to migrate the source or not.

**Comment by droidmonkey** [comment]
This is only possible if the application is built use UWP. We could add a UWP shim in place to make an appx, but it is not worth our effort at this time.

**Comment by piu130** [comment]
@droidmonkey With the Desktop Bridge you can port no UWP apps. [Here](https://docs.microsoft.com/en-us/windows/uwp/porting/desktop-to-uwp-prepare) are the requirements the current program must comply.

[Here](https://docs.microsoft.com/en-us/windows/uwp/porting/desktop-to-uwp-root#convert) are different ways to convert the program including [manual packaging](https://docs.microsoft.com/en-us/windows/uwp/porting/desktop-to-uwp-root#manual-packaging).

After conversion this would then also enable UWP features.

**Comment by droidmonkey** [comment]
It would be better for the original KeePass2 to be ported to UWP since its already written in C# using .NET.

For us this just takes effort away from everything else with almost no gain.
