### ISSUE TITLE
unable to open a database from a previous version

### ISSUE THREAD

**Issue by delfin27** [keepassxreboot/keepassxc#2592]
The app fails to open a database i had in a separate storage partition after a system upgrade (linux mint fresh install).

## Expected Behavior
If you decide to open a database you already have from a previous vresion, i expect it to open without any problem.

## Current Behavior
I chose a separate partition to storage my database but, when i tried to open it after a system upgrade, a warning poped up saying that the password was incorrect or the database was corrupt and, i am 100% sure that i haven't changed or mistyped the password. 
I thought it was an issue of incompatibility after the system upgrade (KeepassXC version 2.3.1) but, i could reproduce this behaviour with the same system specs and keepassxc version on a virtual machine. I created a new database in the host machine then, i moved it to the VM and the same warning poped up.
 
## Steps to Reproduce
1. First run of keepassxc
2. Open an existent database in a storage partition (autosaved by Keepassxc 2.3.1)
3. A warning pops up: unable to open the database: wrong password or corrupted database.

## Context
I'd really appreciate any idea on how to recover my passwords.
please.

## Debug Info
KeePassXC - Versión 2.3.4
Revisión: 6fe821c

Libreries:
- Qt 5.9.5
- libgcrypt 1.8.1

Operating System: Linux Mint 19.1
Arquitectura de CPU: x86_64
Núcleo: linux 4.15.0-43-generic

Extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by droidmonkey** [comment]
KeePassXC is capable of opening databases all the way back to version 2.0.0. There is no changes made between 2.3.1 and 2.3.4 that would impact opening the database. I cannot reproduce this issue.
