### ISSUE TITLE
Unable to open database in Snapshot build

### ISSUE THREAD

**Issue by srikargottipati** [keepassxreboot/keepassxc#2594]
I'm unable to open my KDBX database in the latest Snapshot release.

## Expected Behavior
I expect to open the database using the new Snapshot build

## Current Behavior
I get an error when I try to open the database using the 2.4.0 Snapshot build dd5665c. 

The error is **'Unable to open the database: Error while reading the database: Wrong key or database file is corrupt. (HMAC mismatch)'**

When I downgrade to a stable build 2.3.4, I am able to open the database again and work with it fine. Anyone else facing the same issue? Any help to fix it is appreciated.

P.S: I'm trying to use the snapshot build as there was an important commit that fixes a url match bug with the browser plugin that was introduced in 2.3.4. 

## Debug Info
KeePassXC - Version 2.4.0-snapshot
Build Type: Snapshot
Revision: dd5665c

Libraries:
- Qt 5.12.0
- libgcrypt 1.8.4

Operating system: Manjaro Linux
CPU architecture: x86_64
Kernel: linux 4.20.0-1-MANJARO

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- YubiKey

Enabled extensions:
- KeePassXC-Browser

**Comment by droidmonkey** [comment]
Do you use key file or Yubikey? Have you successfully opened your database in previous snapshot builds?

**Comment by srikargottipati** [comment]
> Do you use key file or Yubikey? Have you successfully opened your database in previous snapshot builds?

Use key file. I haven't tried any other snapshots builds. This is the snapshot that was built using the git from Arch AUR

**Comment by droidmonkey** [comment]
Are you using a password as well? Do you know if you are using KDBX4? Just trying to narrow in on the fault area.

**Comment by srikargottipati** [comment]
> Are you using a password as well? Do you know if you are using KDBX4? Just trying to narrow in on the fault area.

Yes, I'm using a password. I think I'm using KDBX4, as the encryption algorithm is ChaCha20 and derivative function is Argon2 in KeePass. Is there any other way to confirm that I could be missing?

**Comment by jopvanraaij** [comment]
I've the same issue with version 2.4.0. I use a combination of a password key file (generated in 2012) and a password.

# debug info

KeePassXC - Version 2.4.0

Libraries:
- Qt 5.11.3
- libgcrypt 1.8.4

Operating system: Fedora 29 (Workstation Edition)
CPU architecture: x86_64
Kernel: linux 5.0.4-200.fc29.x86_64

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (only unsigned sharing)
- YubiKey

**Comment by droidmonkey** [comment]
This ended up being an error in our base64 detection code. If your key file contained a '/' in the key it would reject. This has been fixed in the upcoming 2.4.1.

Closing this as a result.
