### ISSUE TITLE
Desktop notification when retrieving credentials using browser integration

### ISSUE THREAD

**Issue by piegamesde** [keepassxreboot/keepassxc#2595]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( Do not include screenshots of your actual database! )

## Expected Behavior
[NOTE]: # ( If you're describing a bug, tell us what should happen )
[NOTE]: # ( If you're suggesting a change/improvement, tell us how it should work )
When my browser retrieves any passwords for autofill, I'd like Keepass to send a desktop notification.

## Debug Info
KeePassXC - Version 2.3.4
Revision: 6fe821c

Libraries:
- Qt 5.12.0
- libgcrypt 1.8.4

Operating system: Antergos Linux
CPU architecture: x86_64
Kernel: linux 4.20.0-arch1-1-ARCH

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by mefromthepast** [comment]
I support this request.

**Comment by droidmonkey** [comment]
This is actually totally unnecessary. We have a confirmation popup already for entries that have not been explicitly approved for use. The browser extension also clearly displays when it has retrieved a credential that has been previously approved.
