### ISSUE TITLE
No option to change global autotype-sequence

### ISSUE THREAD

**Issue by datenheim** [keepassxreboot/keepassxc#2597]
Can't find an option to globally change the default autotype sequence.

If there are credentials stored in firefox and autotype is executed on the same page,
sometimes the password is entered twice - from firefox and also keepassxc.
If I change the sequence to {CLEARFIELD}{USERNAME}{TAB}{CLEARFIELD}{PASSWORD}{ENTER}
that problem completely disappears.

**Therefore an option to change the sequence globally would be great indeed!**

KeePassXC - Version 2.3.4
Revision: 6fe821c

Libraries:
- Qt 5.11.1
- libgcrypt 1.8.3

Operating system: Windows 7 SP 1 (6.1)
CPU architecture: x86_64
Kernel: winnt 6.1.7601

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by droidmonkey** [comment]
Just change the sequence in the root group.

**Comment by rpedrica** [comment]
I have the same issue but only certain sites where I've saved the login with Firefox - Keepassxc inputs the password twice in a row as follows:

<password><password>

... and of course the login then fails.

I tested this on www.later.com as an example; with browser creds saved, the login fails; removing the browser creds, the login works.

I've recently upgraded to keepassxc from keepassx where auto-type worked irrespective of whether the browser had saved creds for the site or not.

I've tested the previously mentioned sequence:

{CLEARFIELD}{USERNAME}{TAB}{CLEARFIELD}{PASSWORD}{ENTER}

and it works for me as well so changing that globally on root group. Will this be required going forward or will:

{USERNAME}{TAB}{PASSWORD}{ENTER}

... work in future for either case?

**Comment by droidmonkey** [comment]
Are you sure the {ENTER} isn't actually selecting the drop-down credentials presented by the browser? Auto-Type is literally the same as typing with your keyboard.

You might want to use our browser extension instead.

**Comment by datenheim** [comment]
Using the browser extension is only a partial fix since not all browsers are supported.

Having the chance to change the default sequence is browser and plugin agnostic which I consider the superior solution.

**Comment by datenheim** [comment]
Sorry. Now discovered where to set the default sequence for a group :(
Issue fixed.... thought is was a program setting.
