### ISSUE TITLE
Reattach tray icon to system tray

### ISSUE THREAD

**Issue by Mandragorian** [keepassxreboot/keepassxc#2598]
The tray icon of keepassxc does not reappear in the system tray if the system tray is restarted, while other applications have this behaviour

## Expected Behavior
If the tray icon is shown and the system tray is restarted, the tray icon should reappear in the tray.

## Current Behavior
The tray icon does not reappear, while keepassxc is still running in the background.

## Steps to Reproduce
I use i3-gaps window manager and I came across this behaviour doing this:
1. Start keepassxc, with the option of showing a tray icon
2. Restart the i3 session in place

## Context
I use i3-gaps as window manager, i3bar provides a status bar with a system tray. I assume that this is not "correct" behavior becauseI also use the nm-applet application, which displays a tray icon. The nm-applet icon stays on the system tray even after an in-place restart.

## Debug Info
KeePassXC - Version 2.3.4
Revision: 6fe821c

Libraries:
- Qt 5.12.0
- libgcrypt 1.8.4

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 4.20.0-arch1-1-ARCH

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by droidmonkey** [comment]
Definitely sounds like a Qt bug to me, especially since it doesn't occur in Qt 5
11 and below.

**Comment by txtsd** [comment]
I use tint2 and it happens in tint2's systray as well.
See: https://gitlab.com/o9000/tint2/issues/725

**Comment by txtsd** [comment]
Please upvote this issue on the Qt tracker: https://bugreports.qt.io/browse/QTBUG-73459

**Comment by droidmonkey** [comment]
Closing as this is not a KPXC bug.
