### ISSUE TITLE
[Linux] Crash when applying/OK edit to entry

### ISSUE THREAD

**Issue by iverik-no** [keepassxreboot/keepassxc#2599]
Experiencing crashes when editing > apply/ok an entry. Possibly related to using Enter key as OK (dunno, but that's what happened just now).

For the record, I've also experienced this on Mac OS.

## Expected Behavior
Not crashing.

## Current Behavior
Crashing when saving an edited entry. 
Inside and editing, then pressing Enter to apply --> Crash

## Steps to Reproduce
It's not something I've been able to consistently reproduce. Seems random.
1. Edit entry
2. Save edit (Apply / OK / Enter-key)
3. Crash

KeePassXC - Version 2.3.4
Revision: 6fe821c

Libraries:
- Qt 5.11.1
- libgcrypt 1.8.3

Operating system: Ubuntu 18.10
CPU architecture: x86_64
Kernel: linux 4.18.0-13-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by droidmonkey** [comment]
That is very relevant. This issue almost exclusive hits people with really old databases used in prior versions of KeePass2. My belief is that it is history related in that there are corrupt history items causing issues. You could try backing up your database, then set the history limit to 0 and save to clear out all entry history. After that, see if it still crashes.

**Comment by iverik-no** [comment]
I'll try that and report back.

**Comment by iverik-no** [comment]
Well, I just now had a crash, and that was an entry to which I was adding an attachement. 
I created the entry, added password and stuff, and saved. Then I reopened the entry > Advanced > Added an attachement, at which point it crashed.

I can say that many of the crashes I've had was on entries to which I was adding attachements. But not exclusively. 
For instance, I now also had a crash on my secondary database, which was made with KeePassXC mid March 2018. This entry was a basic title/username/password/url/notes entry, with no custom icons. No entries in this database have more than the basic fields in use (i.e. no attachements or custom icons).

**Comment by iverik-no** [comment]
I've been editing a whole bunch of old entries now, and had a bunch of crashes. Most (all) of them are of the basic variety. I.e. no attachements, though many had custom icons (from back when I used KeePass2).

**Comment by droidmonkey** [comment]
With so many crashes, can you try using our appimage snapshot of rhe develop branch? We might be chasing ghosts. https://snapshot.keepassxc.org/latest

**Comment by iverik-no** [comment]
Yeah, sure, I'll give it a go.

**Comment by iverik-no** [comment]
Ok, so I've been working with the snapshop for Linux (22.01.2019) for an hour, hour and a half now, and thus far I've not experienced any crashes. So it may seem that we were indeed chasing some ghost living in the 2.3.4 release.

I was promted with the following dialogue upon opening my database with the 2.4.0 snapshot appimage:

> Legacy browser integration settings have been detected.
> Do you want to upgrade the settings to the latest standard?
> This is necessary to maintain compatibility with the browser plugin.

If this refers to KeepassHTTP, I was not aware that this was active on my database (actually, I'm quite sure it wasn't).

___

I also gave the old install of Keepass 2.3.4 a run, with some rapid changes to entries (changing icons, hopping through usernames and passwords), which sent it to a crash within a few minutes. Not so with the snapshop.

**Comment by droidmonkey** [comment]
Good to hear! The "legacy browser settings" refers to moving the browser config from an entry into the database custom data. Once you do that you won't be able to connect to the browser plugin in 2.3.4 until you reconfigure it.

**Comment by droidmonkey** [comment]
The browser addon doesn't dictate where the settings are stored or accessed. I agree that perhaps the wording of the pop-up warning needs to be adjusted.

**Comment by iverik-no** [comment]
No, but it needs to know where to find the settings, and since they're now part of the database settings, it needs to be updated to know where to look, right? Which is why it currently doesnt work with the 2.4 snapshot?

It wouldn't hurt to have a second look at the pop-up before release, making a bit more explanation what is meant by Legacy settings here. Possibly referring to the changelog, or a separate short post on the website, could be nice.

Anyway, seems this one is some sort of solved, so just go ahead and put it on closed :)

**Comment by droidmonkey** [comment]
You are confusing the browser extension and KeePassXC application itself. Nevertheless, the wording on the warning popup does need to be massaged a little.

**Comment by abacao** [comment]
@droidmonkey this issue is happening to me in 2.5.1 in Linux using the deb version. Should I create a new issue?

**Comment by droidmonkey** [comment]
Sure, but only if you have a crash dump that points to the cause. Otherwise it doesn't help unfortunately.

**Comment by NytronX** [comment]
> Sure, but only if you have a crash dump that points to the cause. Otherwise it doesn't help unfortunately.

How do we do a crash dump? Googling this reveals no information on how to do it. My KeePassXC crashes like more often than not at the moment. Manjaro KDE Plasma, latest KeePassXC 2.5.1.

**Comment by droidmonkey** [comment]
Those Dropbox crashes are fixed in the upcoming 2.5.2
