### ISSUE TITLE
Debian / Ubuntu .deb packages missing

### ISSUE THREAD

**Issue by FlorinAndrei** [keepassxreboot/keepassxc#260]
What the title says. The lack of Ubuntu packages is a show-stopper for me.

Are there any plans to release binary .deb packages?

Thanks!

**Comment by phoerious** [comment]
We are working on getting KeePassXC into the Debian repositories from where they can go into the Ubuntu repositories. In the meantime you can use these unofficial DEBs: https://github.com/magkopian/keepassxc-debian/releases

**Comment by FlorinAndrei** [comment]
Perfect, thanks. Could you please add the link to that repo to the downloads page? Someone new to the project might be under the impression that there are no .deb packages available at all.

**Comment by phoerious** [comment]
I added a link to the download page.

**Comment by phoerious** [comment]
Actually, I think I'll close this in favor of #5. Let's not discuss the same things in several places.

**Comment by FlorinAndrei** [comment]
This is perfect, thank you.
