### ISSUE TITLE
Display warning when text cannot be copied to clipboard

### ISSUE THREAD

**Issue by JulienPalard** [keepassxreboot/keepassxc#2600]
## Current Behavior

Today my keepassxc was unable to put password in my X11 selection, (and the UI was not telling me so, only stderr, which I noticed only a bit later):

```
QXcbClipboard::setMimeData: Cannot set X11 selection owner
```

It worked the day before, and it worked again after a restart of the keepassxc process.

At least, I suggest an error message inside keepassxc like "Your password was **not** copied due to some error, don't try to paste it it won't work blah blah".

## Steps to Reproduce

At the moment, strictly no idea, I'm using keepassxc since like 10 days (was using keepassx before), and it's the first time it happen.

My usage is maybe a bit "specific":
- I'm having two databases (pro shared with coworkers, and perso, shared with ... nobody)
- Both are mounted via sshfs from two distinct mountpoints.
- I sometime (rarely but sometimes) start the keepassxc from INSIDE one of the mounted directory, in this case, it can happen that the mountpoint got killed (ssh lost) while the keepassxc process is still running in this "ghost" directory.

During the issue, the process WAS running from inside an sshfs mounted directory, which was *not* unmounted / lost (or re-mounted but I don't remember).

I typically keep my keepassxc process running for days so I don't really remember if it had connection interruptions or not, sorry.

## Debug Info
```
KeePassXC - Version 2.3.4
Revision: 6fe821c

Libraries:
- Qt 5.11.3
- libgcrypt 1.8.4

Operating system: Debian GNU/Linux buster/sid
CPU architecture: x86_64
Kernel: linux 4.18.0-2-amd64

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey
```

**Comment by droidmonkey** [comment]
I agree we should issue a notice if copy to clipboard fails. This likely has nothing to do with your storage or launching methods.

**Comment by JulienPalard** [comment]
> This likely has nothing to do with your storage or launching methods.

Probably but as I really have no clue what's causing it, I tried to be exhaustive, just in case someone can spot something relevant.

Still using keepassxc on two machines, every days, has not changed my workflow, and the bug did *not* came back.

Can it be due to an `apt upgrade`? I mean a change in an underlying library while the process is running?

**Comment by droidmonkey** [comment]
Yes that is the most likely cause.

**Comment by JulienPalard** [comment]
So it will be OK to me if not fixed :) let's just focus on displaying an error message when the copy has failed for any reason.

**Comment by steckhan** [comment]
same for me, if I run Rstudio on a high performance cluster this doesn't work.
instead gedit copy/paste works fine.
