### ISSUE TITLE
[Feature request] Multiple passwords within a site

### ISSUE THREAD

**Issue by kishaningithub** [keepassxreboot/keepassxc#2602]
In India, we have banks which have 3 passwords within the same login

1.  Internet banking password
2. Profile password
3. Transaction password

Eg: 
For State bank of India, if my login is **MySuperUserName** my passwords would be
1. Intenet banking  password - abcd@#$77722  (alpha numeric)
2. Profile password - cddfd$777  (alpha numeric)
2. Transaction password - 3324 (This is always numeric)

So i wish to be able to use multiple passwords inside the same website. I am very much open to discussions around this.

**Comment by varjolintu** [comment]
Are you using Auto-Type or the browser integration? Add the transaction password as an attribute to your entry. 

Auto-Type example:
Define a new custom attribute named PIN with value 12345. Now Auto-Type can access it with the action {S:PIN}.

In the browser integration:
Select `Choose custom login fields for this page` from the extension popup. Select the Transaction password field as a String Field after the username and password field (those can be skipped). Define a new custom attribute named `KPH: Passwd` with your numeric password as the value. Extension should fill the String Field automatically after that with your Transaction password.

**Comment by kishaningithub** [comment]
@varjolintu Thanks for your reply! I personally always use Auto-Type feature
Now the questions i have are
1. How secure is attribute storage compared to the password storage ?
2. Can sensitive information like Profile password and Transaction password be stored as attributes from a security point of view ?

**Comment by pabru** [comment]
I'm pretty sure that both would be saved in the Keepass database, which is already encrypted. I think that security for those extra attributes will be the same as for your passwords.

**Comment by droidmonkey** [comment]
I recommend using the entry cloning feature to support this situation.
