### ISSUE TITLE
"Automatically save after every change" not working in 2.4.0. KeepassXC asks for saving changes when locking or shutting down workstation, although automatic save is enabled

### ISSUE THREAD

**Issue by Lalarian** [keepassxreboot/keepassxc#2604]
## Expected Behavior
[NOTE]: # ( If you're describing a bug, tell us what should happen )
KeepassXC should save all changes immediately as checked in settings, so there are no changes left to save on shutdown.
![kpxc2](https://user-images.githubusercontent.com/5146616/51184214-e45d5a00-18d3-11e9-8100-2564bc063651.png)

## Current Behavior
I shutdown or lock my workstation. After login in again I get a window from KeepassXC, asking if changes should be saved before shutdown.
![kpxc1](https://user-images.githubusercontent.com/5146616/51184211-e0313c80-18d3-11e9-9701-c17379449a65.png)

## Possible Solution
Currently  KeepassXC 2.4.0 does not save changes automatically as enabled in settings, I think it's a bug, because this behaviour doesn't make sense and it was not like this with KeepassXC 2.3.4.

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1. Change any database entry from KeepassXC
2. Shutdown or Lock the system
3. Login again
4. See the window asking if changes should be saved.

## Context
This did not happen with KeepassXC 2.3.4

## Debug Info
KeePassXC - Version 2.4.0-snapshot
Build Type: Snapshot
Revision: b6eeaba

Bibliotheken:
- Qt 5.9.5
- libgcrypt 1.8.1

Betriebssystem: Ubuntu 18.04.1 LTS
CPU-Architektur: x86_64
Kernel: linux 4.15.0-43-generic

Aktivierte Erweiterungen:
- Auto-Type
- Browser Integration
- SSH Agent

**Comment by droidmonkey** [comment]
I believe I just fixed this with #2601

**Comment by droidmonkey** [comment]
I will add the fix to that PR

**Comment by droidmonkey** [comment]
Done!

**Comment by droidmonkey** [comment]
Oh, I read this as auto save on exit doesn't work. Let me investigate further.
