### ISSUE TITLE
Yubikey dependency is required, even for building with -DWITH_XC_YUBIKEY=OFF

### ISSUE THREAD

**Issue by Lalarian** [keepassxreboot/keepassxc#2605]
As the title says: I have not yubikey (like probably most users) but cmake insists on having all Yubikey dependencies installed

## Expected Behavior
When I issue the -DWITH_XC_YUBIKEY=OFF parameter, all yubikey requirements should be ignored

## Current Behavior
I state -DWITH_XC_YUBIKEY=OFF, but configure creation cancels:
`cmake -DCMAKE_VERBOSE_MAKEFILE=ON -DWITH_GUI_TESTS=ON -DWITH_XC_AUTOTYPE=ON -DWITH_XC_YUBIKEY=OFF -DWITH_XC_BROWSER=ON -DWITH_XC_NETWORKING=ON -DWITH_XC_SSHAGENT=ON -DWITH_TESTS=ON -DWITH_GUI_TESTS=ON -DWITH_DEV_BUILD=ON -DWITH_ASAN=ON -DWITH_COVERAGE=OFF ..
-- Setting up build for KeePassXC v2.4.0-snapshot

CMake Error at /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find YubiKey (missing: YUBIKEY_LIBRARIES YUBIKEY_INCLUDE_DIRS)
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindYubiKey.cmake:25 (find_package_handle_standard_args)
  CMakeLists.txt:354 (find_package)

-- Configuring incomplete, errors occurred!
`

## Possible Solution
Insert a check for the -DWITH_XC_YUBIKEY parameter and if this is set to OFF then ignore all yubikey only dependencies.

## Context
I don't need the yubikey features but still I have to work around this problem for building. It's especially annoying, because of the need for libykpers-1-1  and  libykpers-1-dev. This library isn't really intuitive to find for installation, as it doesn't fit into the name scheme "apt install libyubi*"

## Debug Info
Any version, any system.

**Comment by varjolintu** [comment]
What if you disable the tests?

**Comment by droidmonkey** [comment]
I cannot replicate this using a clean build directory. This is likely leftover from a previous cmake run where YUBIKEY was enabled.

**Comment by Lalarian** [comment]
Hello!

I just tried; It's working without yubikey dependencies, if I in addition to '-DWITH_XC_YUBIKEY=Off' I also disable all tests. But shouldn't -DWITH_XC_YUBIKEY  be sufficient?

**Comment by droidmonkey** [comment]
Did you try in a clean build directory?

**Comment by pahhur** [comment]
FMPOV:
Im not the OP, but I was just trying to compile a fresh clone on my Mint 19.1, 64b, today (Reason: see below in the PS2), and got into the same problem:

The cmake fails **without** the yubikey libs, and **with** WITH_XC_YUBIKEY set to OFF.

But the 

`cmake  -DWITH_XC_ALL=ON -DCMAKE_BUILD_TYPE=Release ..      `

also fails, if I have the yubi dev libs installed.

```
dpkg -l libyubikey*
..
ii  libyubikey-dev 1.13-2       amd64        Yubikey OTP library development f

```
Error message:

```
CMake Error at /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find YubiKey (missing: YUBIKEY_LIBRARIES YUBIKEY_INCLUDE_DIRS)
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)


```
So, are we on top supposed to specify YUBIKEY_LIBRARIES YUBIKEY_INCLUDE_DIRS
in terms of defines (-Dxxx) or environment variables?

dpkg -L reports

```
/usr/include/yubikey.h
/usr/lib/x86_64-linux-gnu/libyubikey.a
/usr/lib/x86_64-linux-gnu/libyubikey.so

```


so they are all in the platform's standard paths.

What are we supposed to do ?

---

PS1 It would be a good idea to write something about the solution to this in the INSTALL document ;)
PS2 The 2.3.4 versions on Linux and Windows **still** have the problem with the URL matching, which makes KeepassXC unusable, especially for non- experienced users like my father). Which of the multiple threads should be used for discussing about the URL matching?

**Comment by droidmonkey** [comment]
@pahhur did you go through the environment setup instructions available here: https://github.com/keepassxreboot/keepassxc/wiki/Set-up-Build-Environment-on-Linux

They are also linked in the INSTALL.MD file: https://github.com/keepassxreboot/keepassxc/blob/develop/INSTALL.md#prepare-the-building-environment

You need both libyubikey-dev and libykpers-1-dev

**Comment by pahhur** [comment]
Yes, that helped, although I expected to read something like that in the base dir ;)

**Comment by droidmonkey** [comment]
@Lalarian I cannot reproduce this issue in Windows, Ubuntu, or Debian.

**Comment by abuGit** [comment]
I am using Debian SID (5.16.0-6-amd64 #1 SMP PREEMPT Debian 5.16.18-1 (2022-03-29)) and I got the same error even I followed the set-up for linux guide. I had to make a build-dep upgrade ( don't know if keepass2 was necessary)

    sudo apt build-dep keepass2 keepassxc keepass2-plugin-keepasshttp

and all worked fine.

**Comment by phoerious** [comment]
KeePassXC has nothing to do with KeePass2 or any packages related to it. I don't know where you got those instructions from, but certainly not from our build guide, which is this one: https://github.com/keepassxreboot/keepassxc/wiki/Set-up-Build-Environment-on-Linux

**Comment by abuGit** [comment]
I compiled 2.71 and I followed the instructions (you mentioned on the previous post), and cmake failed witth the yubi lib missing error.

It seems that a lib was missing since after `sudo apt build-dep keepass2 keepassxc keepass2-plugin-keepasshttp` cmake worked and I was able to compile without a problem. 

For me it looks like a lib is missing. From my apt log following libs where installed and this should be the reason for the cmake fail: 

- libykpers-1-dev:amd64 (1.20.0-3)
- libnewtonso
- ft-json5.0-cil:amd64 (6.0.8+dfsg-1.1, automatic)
- libcurl4-gnutls-dev:amd64 (7.82.0-2)
- libykpers-1-1:amd64 (1.20.0-3, automatic)
- libzxcvbn0:amd64 (2.4+dfsg-2, automatic)
- libzxcvbn-dev:amd64 (2.4+dfsg-2)
-  libnewtonsoft-json-cil-dev:amd64 (6.0.8+dfsg-1.1)
-  libquazip5-dev:amd64 (0.9.1-2)

I know that keep2 has nothing to do with KeePassXC but that was my command I used for other reasons.

**Comment by droidmonkey** [comment]
2.7.x does not require the yubikey lib
