### ISSUE TITLE
Ability to link entries

### ISSUE THREAD

**Issue by MacNimrod** [keepassxreboot/keepassxc#2607]
## Expected Behavior
I would like to link entries, for example if I am using the Github Credentials to logon to some (Github) project which has it's own website, I'd like to be able to register that. That way I can see how I logged on, and also when I change my Github password I do not need to edit the entry for that projects website.

Also, more and more website require another account to notify in case of lost password etc.

## Current Behavior
Each entry has it's own username and password. So now, I leave the password field blank but have a note indicating how I logon.

## Possible Solution
Add a possibility to refer to another entry. 

## Steps to Reproduce
1. User navigates to know legitimate website;
2. User is required to logon and has the option to logon using Facebook credentials or Youtube credentials or website specific credentials;
3. User Starts KeePass;
4. User looks up the entry and sees s/he has used Youtube credentials;
5. User ticks the option to logon using Youtube credentials; 
6. User copies the username from the legitimate website
Since KeePass has linked the current entry to the Youtube entry, the username actually copied is from the Youtube entry;
7. User pastes the copied username into the username field
8. Repeated proces for the password
9. User successfully logs on to the website. 

## Context
It's just annoying this feature is missing now that more and more websites offer the option to logon using other credentials. Also there are more and more website that require a second account to email to in case of emergencies.

**Comment by droidmonkey** [comment]
This functionality already exists. You can clone entries and reference their username/password through the GUI dialog. Additional references are available following the KeePass2 documentation: https://keepass.info/help/base/fieldrefs.html
