### ISSUE TITLE
Search with Command+F not working - how about rearrange icons

### ISSUE THREAD

**Issue by richardk2016** [keepassxreboot/keepassxc#2613]
I have filed this bug 2 years ago. Its closed but the bug is still there.
https://github.com/keepassxreboot/keepassxc/issues/823

It seems that the main problem is that the search box is not visible when the app window is too narrow. How can I delete or rearrange the other icons in the toolbar? I don't need a single one of it. I only want to use the search wich command-f when the app window is narrow.  I am on MacOS. Can I delete a file or folder to get rid of the icons to make the search bar visible?

**Comment by droidmonkey** [comment]
This is addressed in 2.4 which prevents the window from sizing down too much to hide the search bar. Why not just make the window a tad bit wider?
