### ISSUE TITLE
After new key generation: Wrong key or database file is corrupt.

### ISSUE THREAD

**Issue by firmer** [keepassxreboot/keepassxc#2615]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( Do not include screenshots of your actual database! )
I am getting a "Wrong key or database file is corrupt." prompt after having generated a new key and trying to open the DB.

Using KeePassXC 2.3.1. on Ubuntu 18.04.1.
KeePass informed me "You are using a legacy key file format which may become unsupported in the future. Please consider generating a new key file."
I unlocked my DB, navigated to "Database -> change master key", put in the master password (no change), checked keyfile and put in a new filename for a key, hit the create button. A new key was created.

## Expected Behavior
[NOTE]: # ( If you're describing a bug, tell us what should happen )
[NOTE]: # ( If you're suggesting a change/improvement, tell us how it should work )
When using the new key and old master password KeePassXC should open the DB.

## Current Behavior
[NOTE]: # ( If describing a bug, tell us what happens instead of the expected behavior )
[NOTE]: # ( If suggesting a change/improvement, explain the difference from the current behavior )

After closing and reopening KeePassXC, the usual "Enter master key" dialogue appears. When entering the master password, selecting the new key file and hitting OK, a prompt appears saying: "Unable to open the database. Wrong key or database file is corrupt."

When entering the master password, (as a test) selecting the old key file and hitting OK, the old prompt "You are using a legacy key file format which may become unsupported in the future. Please consider generating a new key file." appears followed by "Unable to open the database. Wrong key or database file is corrupt."

## Context
I am trying to continue using KeePassXC and have no idea how. It seems like creating a new key has corrupted the DB?

P.S. I am no developer, just let me know if you need more details or info.

**Comment by droidmonkey** [comment]
Did you lose access to your database entirely at this point?

**Comment by firmer** [comment]
Unfortunately, yes. Any idea what to do or what happened?

**Comment by droidmonkey** [comment]
I tried replicating on the 2.4.0 develop branch and could not. I will try replicating on 2.3.1.

**Comment by droidmonkey** [comment]
There should be a "*.old.kdbx" file created which would have your original key file. Hopefully you did not disable "generate backups on save" setting.

**Comment by firmer** [comment]
Thanks a lot for pointing out these options. It didn't work with a blank password but with the password field unchecked! So I actually didn't have to touch the *.old.kdbx. Glad it worked. Thanks & keep up the great work!

**Comment by droidmonkey** [comment]
Cool, I think you may have accidentally unchecked the password field when you created your new key file. This UX is completely revamped for 2.4 to prevent these mistakes.
