### ISSUE TITLE
Creating mirrored entries from opposing groups

### ISSUE THREAD

**Issue by Kledsky** [keepassxreboot/keepassxc#2616]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( Do not include screenshots of your actual database! )

## Expected Behavior
[NOTE]: # ( If you're describing a bug, tell us what should happen )
[NOTE]: # ( If you're suggesting a change/improvement, tell us how it should work )

## Current Behavior
[NOTE]: # ( If describing a bug, tell us what happens instead of the expected behavior )
[NOTE]: # ( If suggesting a change/improvement, explain the difference from the current behavior )

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug, )
[NOTE]: # ( or ideas how to implement the addition or change )

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1.
2.
3.

## Context
[NOTE]: # ( How has this issue affected you? What are you trying to accomplish? )
[NOTE]: # ( Providing context helps us come up with a solution that is most useful in the real world )

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION
Revision: REVISION

Libraries:
- LIBS

Operating system: OS
CPU architecture: ARCH
Kernel: KERNEL

Enabled extensions:
- EXTENSIONS

Expected Behavior
Example: I have one group that is for email addresses that pertain to a specific type of context. For instance say I have an email acct. that I want to have within "Security/Encrypted Emails" group.

This email address would have an email account from say; Protonmail, Hushmail, or some configured mail that uses OpenPGP.

It makes logical sense then to put this email within the above group.

However - Say I also am using that same email as a login email to various websites I use. For instance say I have a group called "Email Accounts", used as a list of all my email accounts. Another group called "Web Login Emails" used for emails I use for logins for various sites.

The expected behaviour I would prefer (I love your program and am only seeing this as a helpful feature) would be that I go here -

0 Group > "Security/Encrypted Emails" > "Protonmail Email Acct. Credentials"

And I update the password for this entry to something new, it would be helpful if I could select a mirroring of this entry to all the other entries that it shows in. I understand we could simply do a search and manually update all of them one by one, but that is time consuming and leaves more room for error.
We could just leave the entry in one group section but that isn't really the goal, since one group isn't necessarily the only place it would be best suited, I believe all of them are.

So the expected behaviour would go as follows - I update the password in the above "Protonmail Email Acct. Credentials" and I have a check box for "mirrored entries". After clicking this checkbox I have the option to mirror the password field to the following other entries...

1 Group > "Email Accounts" > "Protonmail Email Acct. Credentials"

2 Group > "Website Logins" > "Protonmail.com Account Credentials"

3 Group > "Email Accounts" > "Old Yet Relevant Accts." > "Old Protonmail@thisisexample.com"

4 Group > "Network Logins" > "Server1" > "Old Protonmail@thisisexample.com" > "Old Protonmail Acct. Credentials"

5 Group > "Network Logins" > "Server12" > "Old Protonmail@thisisexample.com" > "Old Protonmail Acct. Credentials"

In the above examples, Group 0, 1 & 2 should all be mirrored. Any changes made to one of those accounts should carry over and be updated to the other accounts, since they all reflect the same login data.

Group 3, 4 and 5 should have their own separate mirroring, because they will be an older account yet an update from one should also be reflected in updates from others.

If you move forward with being able to create security within the password database so that certain users can only see certain entries, or certain databases are only allowed to be updated for specific people then this would create all the more reason where mirroring would be helpful and time saving. I hope this made sense... If you are having trouble understanding what I'm tyring to get at and would like some clarification you can email me at "timisbestaccountcreated@gmail.com".

Current Behavior

I may be wrong here (which would surprise me...) but the only way that I'm able to update multiple entries of the same username and passwords that have been placed within different groups is by doing a search and having all of them come up, and then updating them one by one. This is not only time consuming but brings in a much higher likelihood of errors.

Possible Solution

As I sort of stated above I think having a checkbox that says "mirror entry" that then gives you an option of what entry to either create for mirroring or to link for mirroring would allow the above idea to be implemented with ease and with logic.

Steps to Reproduce

Well the steps that I have to reproduce this problem is having multiple groups as I have above, that all pertain to certain functions of the username and passwords that are needed. These username and passwords could easily overlap and in my experience, often do. So to reproduce this problem is to find where you have to perform a search and update multiple "clones" that you've created. The clones do not auto update themselves though, mirroring would allow this to happen. If this isn't a good enough answer I could be more verbose, simply email me at the above address and I will do so.

Context

As of right now I create clones to try and find a solution to this problem. Like I state above though the clones do not replicate/mirror each other. Which requires me to have to do a search and then update them one by one, leaving room for error and is time consuming. A context that could help resolve this in the real world would be to create relationships within the backend of the database you have for the password structure and create the mirroring by use of field keys, if that makes sense. Essentially find a way to link multiple fields together by selecting a check box that then asks you what items to mirror.

Debug Info

I haven't added any of this because this isn't for a bug but for a feature request. If there is some of this entry that you need a little more info on or would like me to elaborate please let me know by emailing me at the above email. I really hope this made sense but I understand if it didn't. I would be more than happy to help clarify any parts that were difficult to understand. Thank you for your time and creating a wonderful product!

**Comment by droidmonkey** [comment]
Just create a clone of the original entry and reference the username/password when you do so. Then you can make a new password for that clone if you want and the username will always be the email address from the original entry. Then you can move that cloned entry to whatever group you want.

![image](https://user-images.githubusercontent.com/2809491/51407579-41524d80-1b2a-11e9-8e44-b22824859a97.png)

![image](https://user-images.githubusercontent.com/2809491/51407602-54fdb400-1b2a-11e9-8fb0-a919547dcf66.png)

![image](https://user-images.githubusercontent.com/2809491/51407616-63e46680-1b2a-11e9-85c6-ce37e248b1ca.png)
