### ISSUE TITLE
Show overall history of changes for entries

### ISSUE THREAD

**Issue by xGreenstar** [keepassxreboot/keepassxc#2621]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( Do not include screenshots of your actual database! )

## Expected Behavior
[NOTE]: # ( If you're describing a bug, tell us what should happen )
[NOTE]: # ( If you're suggesting a change/improvement, tell us how it should work )

Right now you can go into any individual entry and see the history of password changes.  

I would like to have a combined history.

**Comment by droidmonkey** [comment]
This would be good coupled with an undo/redo feature

**Comment by J-a-n-u-s** [comment]
As a temp work-around:

1) In search box type a common character like space " " (I had best luck with space. Asterisk worked well too on Linux but for some reason returned less results on mac. Maybe include a true capture wildcard / show all common across platforms like a checkbox)

2) Sort using the last modified column

3) Go into the entries' individual histories from there.

**Comment by Schrottfresse** [comment]
I'd like this feature, too.
