### ISSUE TITLE
Enforce code formatting

### ISSUE THREAD

**Issue by c4rlo** [keepassxreboot/keepassxc#2623]
## Expected Behavior

`make format` has no effect on the code base, since the code style should be enforced by CI.

## Current Behavior

```
$ cmake --build . --target format
[...]
$ git diff | wc -l
2508
```

## Possible Solution

1. Review and commit the result of building the `format` target.
2. Set up TeamCity to execute the `format` target and fail if that makes any changes.

## Steps to Reproduce

See above.

## Context

See #1168 and #1191 for previous discussion about this.

## Debug Info

N/A

**Comment by droidmonkey** [comment]
I believe you can also run: ```clang-format -i src/**/*.{cpp,h}```

**Comment by c4rlo** [comment]
Yes, but it won't do quite the same thing: the `format` [target](https://github.com/keepassxreboot/keepassxc/blob/develop/cmake/CLangFormat.cmake) has some extra logic to exclude various files.

**Comment by c4rlo** [comment]
CI still doesn't do `clang-format`. And once again, the code base has drifted off the intended style:

```
$ cmake --build . -t format
[...]
$ git diff --shortstat
 11 files changed, 16 insertions(+), 17 deletions(-)
```

Can we re-open this issue?

**Comment by droidmonkey** [comment]
I was going to enable that check today as a matter of fact
