### ISSUE TITLE
Suggestion: password strength indication for each entry

### ISSUE THREAD

**Issue by schadom** [keepassxreboot/keepassxc#2626]
It would be quite cool to have an additional row in main view which indicates the password strength. From an UI-perspective it could be designed similiar to the red to green bar for the password generator. Additional details (entropy, crack time, score from `zxcvbn-c`) could be shown on mouseover.

**Comment by droidmonkey** [comment]
I don't think this would be too helpful. This is already part of the proposal for the password analyzer (#551).
