### ISSUE TITLE
Auto-type does not allow references in syntax

### ISSUE THREAD

**Issue by droidmonkey** [keepassxreboot/keepassxc#2633]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( Do not include screenshots of your actual database! )

## Expected Behavior
[NOTE]: # ( If you're describing a bug, tell us what should happen )
[NOTE]: # ( If you're suggesting a change/improvement, tell us how it should work )
{REF:U@I:7243df20ad9ccfacfec853f715b59a5a} should be a valid auto-type command

## Current Behavior
[NOTE]: # ( If describing a bug, tell us what happens instead of the expected behavior )
[NOTE]: # ( If suggesting a change/improvement, explain the difference from the current behavior )
AutoType::checkSyntax(...) returns false since the REF entry does not conform to any of the available syntax checks even though it is valid.

Additionally, if auto-type verification fails, it does not let the user correct their mistake due to improper handling of the error in https://github.com/keepassxreboot/keepassxc/blob/cbf92598e214da5594e9c5c2d17b72820b89840b/src/gui/entry/EditEntryWidget.cpp#L934

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug, )
[NOTE]: # ( or ideas how to implement the addition or change )
Add REF syntax to the syntax checker and move ```AutoType::verifyAutoTypeSyntax(...)``` to ```EditEntryWidget::commitEntry()``` function.

**Comment by fstorz** [comment]
The expected behavior is already documented in the auto-type User-Guide but it seems that it is not implemented
https://keepassxc.org/docs/KeePassXC_UserGuide.html#_configure_auto_type_sequences
