### ISSUE TITLE
Optionally disable stream ciphers CHACHA20/SALSA20

### ISSUE THREAD

**Issue by ofalk** [keepassxreboot/keepassxc#2636]
## Summary
Add option to disable build of KDBX4 in order to be able to build with libgcrypt version without CHACHA20/SALSA20

## Desired Behavior
In order to build a recent version of KeepassXC in EPEL (CentOS/RHEL 7), I'd love to be able to disable building KDBX version 4 - or at least without the ciphers CHACHA20/SALSA20.

## Possible Solution
Cmake option to not use CHACHA20/SALSA20.

## Context
See behaviour.

I have a patch that is untested, but at least makes the build work fine.

**Comment by ofalk** [comment]
[keepassxc-2.3.4.with_kdbx4.patch.txt](https://github.com/keepassxreboot/keepassxc/files/2782982/keepassxc-2.3.4.with_kdbx4.patch.txt)

**Comment by droidmonkey** [comment]
Building without kdbx4 is a non starter. Disabling the alternate steam ciphers is the better alternative.

**Comment by ofalk** [comment]
Accepted. If we ifdef out the use of the mentioned stream ciphers (like in my patch), that's what is actually happening, isn't it? So, actually the option is incorrectly named/described - I'll also adjust the issue title now.

**Comment by droidmonkey** [comment]
We will need to do this for FIPS compliance in the future anyway so this is an overall positive change.

**Comment by ofalk** [comment]
Oh. That's great I've hit the right nail here :-)
In regards to the GUI, yes, as stated, I didn't really test it.
Of course, feel free to adapt it as it makes sense and I'd be happy to make sure it lands in EPEL in the end.

**Comment by droidmonkey** [comment]
This will not be done anymore. Moving to Botan makes this unnecessary.
