### ISSUE TITLE
Larger Icons

### ISSUE THREAD

**Issue by KitchM** [keepassxreboot/keepassxc#2639]
I find it difficult to view the tiny icons, making their significance wasted on the user.

It would be nice if there were a way to show them in larger size.

Thank you.

**Comment by droidmonkey** [comment]
Are you referring to the application icons or the icons that can be attached to entries?

**Comment by KitchM** [comment]
The icons on the left side tree view inside the open program.

**Comment by droidmonkey** [comment]
These?

![image](https://user-images.githubusercontent.com/2809491/51640769-697aeb80-1f32-11e9-9c31-eba392227270.png)

**Comment by Nuklon** [comment]
For me the top one and the icons below the menu bar (that where the new/open/save icons etc are), on high dpi screen I can barely see the icons. If it would be a little bigger (25% or something) it would be much better.

**Comment by bkvamme** [comment]
While on this matter, the icons are incredibly small on my Surface Pro 6 (2736 x 1824, 12.5in, 200% scaling). Text and UI looks and works fine, but the toolbar and group/entry icons in are very tiny (appears to be scaled at 100%). Still manage to hit the icons using a mouse, using the stylus/pen it is possible, but touch is impossible. I am not expecting this to be a touch friendly UI, but it would be nice to scale it up a bit. 

![image](https://user-images.githubusercontent.com/6065192/53301138-20cf8e80-3860-11e9-926d-2cb7cd548909.png)

![image](https://user-images.githubusercontent.com/6065192/53301152-3b096c80-3860-11e9-97fb-de200dac7053.png)

![20190224_182248](https://user-images.githubusercontent.com/6065192/53301275-ccc5a980-3861-11e9-87bc-33d13e652cce.jpg)

**Comment by phoerious** [comment]
Please try the 2.4.0 beta. It handles high-dpi screen better.

**Comment by bkvamme** [comment]
Excellent, thanks! Looks and works excellent now.

**Comment by droidmonkey** [comment]
Closing due to lack of feedback
