### ISSUE TITLE
Stop Closing Issues

### ISSUE THREAD

**Issue by KitchM** [keepassxreboot/keepassxc#2641]
It is a real pain when you people arbitrarily close issue without waiting for the responses.

Please stop doing that!

**Comment by droidmonkey** [comment]
Excuse me? This is our project and leaving issues open adds to management time. This is not a discussion board. If you want to have a discussion I recommend emailing us (team@keepassxc.org) or joining our IRC channel. FYI, you can keep replying to a closed issue.

**Comment by KitchM** [comment]
No, I cannot keep replying because any closed issue becomes inaccessible.  Did you not know that?

**Comment by KitchM** [comment]
Besides, you asked for input.  If you don't want it, then don't invite for it.

**Comment by droidmonkey** [comment]
![image](https://user-images.githubusercontent.com/2809491/51642532-98479080-1f37-11e9-8f98-0e73ae10f4a7.png)

**Comment by KitchM** [comment]
Again, you don't get it.  **I** logged in; where are **my** closed issues?  Or do I have to sort thru all of them?  My issues are listed at the top of the page in the black bar where it says "Issues".

**Comment by droidmonkey** [comment]
https://github.com/keepassxreboot/keepassxc/issues?q=is%3Aissue+is%3Aclosed+author%3AKitchM

We value all feedback, positive or negative. It is just incredibly difficult to keep up with the issues list if we keep everything open.

**Comment by KitchM** [comment]
Wait, it showed up now.  Must have been Unity.

**Comment by KitchM** [comment]
Sorry for being curt.  When one is too busy there is no time to waste on lack of intuitive design, and Github is sadly lacking.

I see now more of the problem I experienced.  First of all, when logging in to this forum, this is what I see:
![keepassxc github issues](https://user-images.githubusercontent.com/371308/51939592-db917b80-23dd-11e9-9e95-e2bb0cee8280.png)
Please note that the open and close numbers do not apply to me.  Do you see how that might be a problem?

However, after if I filter by author:KitchM, only then do I see mine.  That's a lot to remember from dozens of forums that use a more standard methodology.

I hope you understand my frustration in all this.  At least I now know how to find "closed" items here.

Thank you.

**Comment by droidmonkey** [comment]
Yah it is annoying that your name does not show up unless you are a project maintainer. That to me is a bug that GitHub needs to address (ie, place a "ME" under the author drop-down).

You can always save a bookmark to the page that filters the issues by you as author.
