### ISSUE TITLE
Database does not lock on switching user in macOS

### ISSUE THREAD

**Issue by HUGHUSR** [keepassxreboot/keepassxc#2642]
## Summary
If you have KeePass configured to "Lock databases when session is locked or lid is closed" in KeePassXC Security Preferences checked, then I would also expect KeePassXC to lock databases when a "SwitchUser" occurs. That does not happen. Instead, the databases are left open, as if the user was still the active user.

I believe this is a security situation equivalent to locking a session or putting the device to sleep.

## Expected Behavior
When a database is open, and a user does a "SwitchUser" (e.g., /System/Library/CoreServices/Menu\ Extras/User.menu/Contents/Resources/CGSession -suspend ) I would expect KeePass to lock all open databases.

## Current Behavior
Currently, databases are left open.

## Possible Solution
KeePassXC should detect when a SwitchUser occurs, and if the option to lock the databases on a SwitchUser is enabled, then the databases should be locked.

This problem should be fixed as it leaves the database open when the user is in a condition approximately equivalent to being in Sleep mode.

## Steps to Reproduce
1. Open a database in KeePassXC
2. In a terminal window, enter /System/Library/CoreServices/Menu\ Extras/User.menu/Contents/Resources/CGSession -suspend
3. Login to a different user
4. Do stuff as that other user
5. Either logout of that other user or enter the SwitchUser command, above
6. Login to the original user with the open KeePass database(s) and observe they are still open

## Context
I see this as a security issue for which there should be a KeePassXC Security Preference to lock databases when switching users (this should be a separate option than the "session is locked" option, because there are circumstances where you would want to leave the databases open as a matter of convenience, albeit insecure)

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Using MacOS 2.3.4

MacOS 10.12.6 (16G1510)
MacBook Pro (Retina, 15-inch, Mid 2014)

Enabled extensions:
- EXTENSIONS -- None

**Comment by droidmonkey** [comment]
Switching a user is equivalent to locking the screen. This might be related to #2585 which cannot be replicated with the 2.4.0 build.

**Comment by HUGHUSR** [comment]
If you have a 2.4.0 DMG for Mac, I will be glad to test this.
On 1/23/2019 at 6:42 PM, "Jonathan White"  wrote:

	Switching a user is equivalent to locking the screen. This might be
related to #2585 which cannot be replicated with the 2.4.0 build.

**Comment by droidmonkey** [comment]
Ok I'll dive into this today. Can you post the crash log?

**Comment by HUGHUSR** [comment]
Hum... I had attached it to the email, but I guess it did not get added to the bug report.

Bad GitHub!! Bad!!

Oh well, here it is now.

Uh, interesting... had to rename the file before GitHub would accept it!!

[KeePassXC_2019-01-23-221727_Me.crash.txt](https://github.com/keepassxreboot/keepassxc/files/2791969/KeePassXC_2019-01-23-221727_Me.crash.txt)

**Comment by droidmonkey** [comment]
I cannot replicate the crash when activating screensaver. I can replicate the non-locking situation.

**Comment by HUGHUSR** [comment]
100% reproducible on my end.
1) Open 2.4.0 version of KeePassXC in ~/Applications2) Create a new
Database taking all the default options and giving it a short
password3) Switch User4) Switch User back to user testing KeePassXC
2.4.0 (New DB is still open)5) Invoke screen saver6) Exit screen
saver7) KeePassXC has crashed
Since GitHub will not post attachments, I will login and attach the
latest dump
On 1/24/2019 at 10:20 AM, "Jonathan White"  wrote:

	I cannot replicate the crash when activating screensaver. I can
replicate the non-locking situation.

**Comment by HUGHUSR** [comment]
Latest crash dump
[KeePassXC_2019-01-24-114238_Me.crash.txt](https://github.com/keepassxreboot/keepassxc/files/2792692/KeePassXC_2019-01-24-114238_Me.crash.txt)

**Comment by HUGHUSR** [comment]
Ok -- I agree with that. But, should KeePassXC simply crash and burn
under those circumstances?
On 1/24/2019 at 12:00 PM, "Jonathan White"  wrote:

	OK, the problem is that you have a new database without a filename
(ie you never saved it to disk).

**Comment by HUGHUSR** [comment]
Behavior has changed in 2.4.1. See bug  #3090. The database now appears to close, but CPU utilization hits the sky.

**Comment by droidmonkey** [comment]
I will close this issue since it was corrected.

**Comment by droidmonkey** [comment]
This issue still persists.
