### ISSUE TITLE
Protect settings with password

### ISSUE THREAD

**Issue by eike-fokken** [keepassxreboot/keepassxc#2646]
[TIP]:  # ( Provide a general summary of the feature in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Summary
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
An attacker that has brief access to my computer with unlocked screen but locked database could go to settings and disable the automatic locking of the database, hoping that I later open the database, thinking it will lock itself afterwards, and briefly leave my computer.

## Desired Behavior
[NOTE]: # ( Tell us how the new feature should work, be specific )
It is not easily possible to change program settings.

## Possible Solution
[NOTE]: # ( Not required, but suggest ideas on how to implement the addition or change )
Add a password before the settings.

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
Its just paranoia.

**Comment by droidmonkey** [comment]
The only way this would work is if we encrypted the settings file itself and you had to enter a password just to even open KeePassXC. Given the fact that you gave access to your computer (willingly or not) to someone else is the problem here.

**Comment by eike-f** [comment]
I agree that it is a bad idea to do that. On the other hand I have the impression that if I have security settings I should be able to rely on them.

What do you think about providing a (possibly red) warning stating that settings have changed when opening a safe the first time after changing settings?
This is probably also hard to implement rigorously, as the information when a safe was opened the last time, would be equally easily forged.

**Comment by droidmonkey** [comment]
We have tossed around the idea of database specific security settings (ie they are stored in the encrypted database). Also we have an issue to implement enterprise settings via registry key or specific ini file.

**Comment by eike-f** [comment]
I like this idea of settings stored in the database very much.
