### ISSUE TITLE
Import only from format kb *1*, when KeePass proper has trouble exporting in that format?

### ISSUE THREAD

**Issue by CottonEaster** [keepassxreboot/keepassxc#2649]
I am considering moving from KeePass proper - run under Mono on Linux and natively on windows - to your program (though the lack of inbuilt syncing is a problem, since I'd rather not use a cloud provider and anyway such providers work dreadfully on Linux).

I find your program will import only the ancient version of 1 of keePass databases (well, as CVS, admittedly, which I am trying). I find also that my Linux KeePass cannot export to that format and that my Windows one claims to be able to, but then says it needs a plugin that . .  I cannot find on the Internet. It would be nice were you to spare your prospective users this kind of . . joy.

EDIT: and the CSV import has resulted in fields getting jumbled.
Further EDIT: oh, KeePassXC can read KeePass_2 files natively anyway. I feel this was not made sufficiently clear.

**Comment by droidmonkey** [comment]
I think it is pretty clear from the fact that we support kdbx files which are KeePass2 format. It is also stated on our website and readme.
