### ISSUE TITLE
Close database based on last access time

### ISSUE THREAD

**Issue by sebast889** [keepassxreboot/keepassxc#2651]
I don't if this belongs here or in the browser extension repo.

## Expected Behavior
I set option to close database after 5 minutes of inactivity. I use the browser extension to fill in credentials. Keepass should recognize this as activity and extend the inactivity time accordingly.

## Current Behavior

I set option to close database after 5 minutes of inactivity. I use the browser extension to fill in credentials. But even after <5 minutes the database will still close because Keepass doesn't recognize filling in credentials as activity. Inactivity seems only to mean the time I spend in the Keepass database window like clicking on entry or modifying it.

**Comment by droidmonkey** [comment]
I like this idea

**Comment by grrttedwards** [comment]
This is related to a major feature that I've been desiring from Keepass. It's been open in the Issues for a long time now: https://github.com/keepassxreboot/keepassxc/issues/310 .

In Keepass, there were two distinct timers, one for monitoring global system activity, and a separate one for monitoring Keepass activity. This made it such that while using the machine you could keep the database indefinitely unlocked, by having a short "global" activity timer, and a much longer activity timer for the application itself, which could trigger.

**Comment by UkeFan** [comment]
I have set 2 hours as Inactivity trigger time, but it closes after a few minutes not working with it. That's quite a pain for my fingers as I use longer pass phrases ));;
<img width="483" alt="grafik" src="https://user-images.githubusercontent.com/12803863/60333061-6d56e200-9998-11e9-8cea-b6285fe62cfd.png">

**Comment by UkeFan** [comment]
Any help? I have to re-login into my databse during one computer session several times - that's quite a pain due to the long pass phrase..

**Comment by droidmonkey** [comment]
@UkeFan your experience is not normal and not how the app behaves for others.

**Comment by UkeFan** [comment]
oh, so I deinstalled via "AppCleaner" App, installed again and BINGO: It works! Thanks for your hint @droidmonkey

**Comment by droidmonkey** [comment]
Great!

**Comment by droidmonkey** [comment]
We will not be implementing this as it poses a security risk. The browser extension constantly requests credentials when browsing websites and we do not know if they are actually used. This could also be abused by simply pulsing the browser extension connection to keep a database unlocked.
