### ISSUE TITLE
 Build fails on windows

### ISSUE THREAD

**Issue by glowcat** [keepassxreboot/keepassxc#2654]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
build complete on windows7.
I am trying on develop branch.
(A similar error has occurred in master)

## Current Behavior
[NOTE]: # ( Tell us what actually happens )

A build error occurs in windows build.
error is
<pre>
E:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.2.1/../../../../x86_64-w64-mingw32/bin/ld.exe: Cannot export argon2_error_message: symbol not found
E:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.2.1/../../../../x86_64-w64-mingw32/bin/ld.exe: Cannot export argon2_hash: symbol not foundE:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.2.1/../../../../x86_64-w64-mingw32/bin/ld.exe: Cannot export argon2_error_message: symbol not found
E:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.2.1/../../../../x86_64-w64-mingw32/bin/ld.exe: Cannot export argon2_hash: symbol not foundE:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.2.1/../../../../x86_64-w64-mingw32/bin/ld.exe: Cannot export argon2_error_message: symbol not found
E:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.2.1/../../../../x86_64-w64-mingw32/bin/ld.exe: Cannot export argon2_hash: symbol not foundE:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.2.1/../../../../x86_64-w64-mingw32/bin/ld.exe: Cannot export argon2_error_message: symbol not found
E:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.2.1/../../../../x86_64-w64-mingw32/bin/ld.exe: Cannot export argon2_hash: symbol not found
</pre>

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1.　Build an environment along the https://github.com/keepassxreboot/keepassxc/wiki/Set-up-Build-Environment-on-Windows
2.　Build with make as below ：
<pre>
mkdir build
cd build
cmake -G"MSYS Makefiles" -DWITH_XC_ALL=ON -DCMAKE_BUILD_TYPE=Release ..
make -j8 package
</pre>
3. A reported build error occurs

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )
Build on windows is not successful and we are in trouble. Is there a way to solve this problem?
Thank you for reading.

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.3.4
Revision: develop

Libraries:
- LIBS

Operating system: Windows7
CPU architecture: x86_64
Kernel: KERNEL

Enabled extensions:
- EXTENSIONS

**Comment by glowcat** [comment]
addtion: It shows where the error occurred
<pre>
[ 83%] Building CXX object tests/CMakeFiles/testkeepass2randomstream.dir/testkeepass2randomstream_autogen/mocs_compilation.cpp.obj
E:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.2.1/../../../../x86_64-w64-mingw32/bin/ld.exe: Cannot export argon2_error_message: symbol not found ...
</pre>

**Comment by droidmonkey** [comment]
Try using the following for your make command:
```mingw32-make -j8 package```

We might have to update those instructions.

**Comment by glowcat** [comment]
I appreciate your advice.
I tried but it seems that similar errors still occur. As a precaution, some of the errors are shown below.
<pre>
[ 82%] Linking CXX executable testkeepass2randomstream.exe
[ 83%] Linking CXX executable KeePassXC.exe
Scanning dependencies of target testbase32
[ 84%] Building CXX object tests/CMakeFiles/testbase32.dir/TestBase32.cpp.obj
E:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.2.1/../../../../x86_64-w64-mingw32/bin/ld.exe: Cannot export argon2_error_message: symbol not found
E:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.2.1/../../../../x86_64-w64-mingw32/bin/ld.exe: Cannot export argon2_hash: symbol not foundE:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.2.1/../../../../x86_64-w64-mingw32/bin/ld.exeE: Cannot export:/msys64 argon2_error_message: symbol not found
E:/msys64/mingw64/bin/mingw64/bin/../lib/gcc/x86_64/../lib-w64/gcc-mingw32/8.2.1/x86_64/..-w64/..-mingw32/../8.2.1/../../x86_64-w64/../../..-mingw32/bin/ld.exe/x86_64: Cannot-w64-mingw32/bin/ld.exe: Cannot export export argon2_error_message: symbol not found
E:/msys64 argon2_hash/mingw64/bin/../lib/gcc: symbol/x86_64 not-w64-mingw32/8.2.1 found/../../../../x86_64-w64-mingw32/bin/ld.exe: Cannot export argon2_hash: symbol not foundE:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.2.1/../../../../x86_64-w64-mingw32/bin/ld.exe: Cannot export argon2_error_message: symbol not found
E:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.2.1/../../../../x86_64-w64-mingw32/bin/ld.exe: Cannot export argon2_hash: symbol not foundE:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.2.1/../../../../x86_64-w64-mingw32/bin/ld.exe: Cannot export argon2_error_message: symbol not found
E:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.2.1/../../../../x86_64-w64-mingw32/bin/ld.exe: Cannot export argon2_hash: symbol not found[ 84%] Building CXX object tests/CMakeFiles/testbase32.dir/testbase32_autogen/mocs_compilation.cpp.obj
E:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.2.1/../../../../x86_64-w64-mingw32/bin/ld.exe: Cannot export argon2_error_message: symbol not found
E:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.2.1/../../../../x86_64-w64-mingw32/bin/ld.exe: Cannot export argon2_hash: symbol not found
</pre>

Is there anything else to prepare or to pay attention to?

**Comment by droidmonkey** [comment]
The error means you either do not have the libargon2 package installed (which should have been flagged by CMake) or the patching process is not working which translates libargon2 function names (argon2_error_message and argon2_hash) into (libargon2_argon2_error_message, libargon2_argon2_hash). This is not an error that occurs on Windows 10, but that should be irrelevant since we are using MSYS to build.

Although, just to be clear, are you using MSYS2 as your MinGW provider??

**Comment by glowcat** [comment]
Yes. I am using 64 bit of MSYS2.
I download it from the following site : http://www.msys2.org/

**Comment by glowcat** [comment]
addition, I am installing /mingw-w64-x86_64-argon2 20171227-3

**Comment by droidmonkey** [comment]
Can you try building 2.2.0 tag which does not have argon2? That will rule out of this is an argon2 issue or a general linker issue with your environment.

**Comment by glowcat** [comment]
> #include <QButtonGroup> to the affected files.

By making this change, we succeeded in building and packaging in 2.2.
However, trying to run will stop at startup.
The following warnings were issued at the time of build, but is there anything related to it
<pre>
[ 38%] Building CXX object src/CMakeFiles/keepassx_core.dir/gui/ChangeMasterKeyWidget.cpp.obj
In file included from I:/keepassxc/keepassxc/src/crypto/SymmetricCipher.h:25,
                 from I:/keepassxc/keepassxc/src/format/KeePass2RandomStream.h:23,
                 from I:/keepassxc/keepassxc/src/format/KeePass2Reader.cpp:29:
I:/keepassxc/keepassxc/src/crypto/SymmetricCipherBackend.h:32:71: warning: attribute ignored [-Wattributes]
     virtual bool processInPlace(QByteArray& data) Q_REQUIRED_RESULT = 0;
                                                                       ^
I:/keepassxc/keepassxc/src/crypto/SymmetricCipherBackend.h:32:71: note: an attribute that appertains to a type-specifier is ignored
I:/keepassxc/keepassxc/src/crypto/SymmetricCipherBackend.h:33:87: warning: attribute ignored [-Wattributes]
     virtual bool processInPlace(QByteArray& data, quint64 rounds) Q_REQUIRED_RESULT = 0;
                                                                                       ^
I:/keepassxc/keepassxc/src/crypto/SymmetricCipherBackend.h:33:87: note: an attribute that appertains to a type-specifier is ignored
In file included from I:/keepassxc/keepassxc/src/crypto/SymmetricCipher.h:25,
                 from I:/keepassxc/keepassxc/src/format/KeePass2RandomStream.h:23,
                 from I:/keepassxc/keepassxc/src/format/KeePass2XmlReader.cpp:28:
I:/keepassxc/keepassxc/src/crypto/SymmetricCipherBackend.h:32:71: warning: attribute ignored [-Wattributes]
     virtual bool processInPlace(QByteArray& data) Q_REQUIRED_RESULT = 0;
                                                                       ^
I:/keepassxc/keepassxc/src/crypto/SymmetricCipherBackend.h:32:71: note: an attribute that appertains to a type-specifier is ignored
I:/keepassxc/keepassxc/src/crypto/SymmetricCipherBackend.h:33:87: warning: attribute ignored [-Wattributes]
     virtual bool processInPlace(QByteArray& data, quint64 rounds) Q_REQUIRED_RESULT = 0;
                                                                                       ^
I:/keepassxc/keepassxc/src/crypto/SymmetricCipherBackend.h:33:87: note: an attribute that appertains to a type-specifier is ignored
In file included from I:/keepassxc/keepassxc/src/crypto/SymmetricCipher.h:25,
                 from I:/keepassxc/keepassxc/src/format/KeePass2RandomStream.h:23,
                 from I:/keepassxc/keepassxc/src/format/KeePass2XmlWriter.cpp:24:
I:/keepassxc/keepassxc/src/crypto/SymmetricCipherBackend.h:32:71: warning: attribute ignored [-Wattributes]
     virtual bool processInPlace(QByteArray& data) Q_REQUIRED_RESULT = 0;
                                                                       ^
I:/keepassxc/keepassxc/src/crypto/SymmetricCipherBackend.h:32:71: note: an attribute that appertains to a type-specifier is ignored
I:/keepassxc/keepassxc/src/crypto/SymmetricCipherBackend.h:33:87: warning: attribute ignored [-Wattributes]
     virtual bool processInPlace(QByteArray& data, quint64 rounds) Q_REQUIRED_RESULT = 0;
                                                                                       ^
I:/keepassxc/keepassxc/src/crypto/SymmetricCipherBackend.h:33:87: note: an attribute that appertains to a type-specifier is ignored
In file included from I:/keepassxc/keepassxc/src/crypto/SymmetricCipher.h:25,
                 from I:/keepassxc/keepassxc/src/format/KeePass2RandomStream.h:23,
                 from I:/keepassxc/keepassxc/src/format/KeePass2Writer.cpp:28:
I:/keepassxc/keepassxc/src/crypto/SymmetricCipherBackend.h:32:71: warning: attribute ignored [-Wattributes]
     virtual bool processInPlace(QByteArray& data) Q_REQUIRED_RESULT = 0;
                                                                       ^
I:/keepassxc/keepassxc/src/crypto/SymmetricCipherBackend.h:32:71: note: an attribute that appertains to a type-specifier is ignored
I:/keepassxc/keepassxc/src/crypto/SymmetricCipherBackend.h:33:87: warning: attribute ignored [-Wattributes]
     virtual bool processInPlace(QByteArray& data, quint64 rounds) Q_REQUIRED_RESULT = 0;
                                                                                       ^
I:/keepassxc/keepassxc/src/crypto/SymmetricCipherBackend.h:33:87: note: an attribute that appertains to a type-specifier is ignored
</pre>
Although there was a problem at startup as described above, at 2.2, I succeeded in building for the time being.
So is it likely that libargon 2 is related to the cause of 2.3.4 build failure?
It is confirmed that libargon 2 has been installed under mingw64 and libargon 2 _ patched.a is created in the build folder after executing cmake.

**Comment by glowcat** [comment]
A little more investigation found that in FindArgon2. cmake,
<pre>
argon2_hash=libargon2_argon2_hash
argon2_error_message=libargon2_argon2_error_message
</pre>
Converting and loading them into libargon2_patched.a, the process of calling them by the conversion process in src/crypto/argon/argon2.h seems to be running.
However at the time of make it seems that the original argon2_hash and argon2_error_message are symbol not found. Do you recognize something about the cause of such error?

* There seems to be no doubt that the cause is in these two functions. If you comment out and invalidate the place (Argon2Kdg.cpp) where these functions are called, the build will succeed.
(Apparently, the point where the problem function is used appears only within the Argon2 Kdf::transformKeyRaw function in Aragon2Kdf.cpp)

**Comment by droidmonkey** [comment]
Oh my... I just updated my MSYS2 packages today and saw that Argon2 package was recently updated (the date is misleading). This package update has broken our process.....

This pull request is the cause of the problems: https://github.com/Alexpux/MINGW-packages/pull/4817

**Comment by droidmonkey** [comment]
@glowcat for now you can download the -2 version of the argon2 package from here: https://drive.google.com/open?id=10U-MAp29Y1iNzzUyOP07dPJWDTAs4t31

Install using: ```pacman -U /path/to/file/mingw-w64-x86_64-argon2-20171227-2-any.pkg.tar.xz```

**Comment by glowcat** [comment]
Thank you for your advice and file presentation.
Replacing the argon2 library, the build and packaging were completed successfully.

However, I reported a little about the tag 2.2, but when I run the completed package (both the unpacked version and the installed version) it seems to crash on startup. Will not such a problem occur there?

Comparing the contents of the windows version of the package on https://keepassxc.org/download/#windows with the build package, the file names are almost the same, but the sizes are different.

The following file names are different:
windows package -> my build pakcage
libcudt61.dll -> libcudt62.dll 
libcuin61.dll ->  libcuin62.dll 
libcuuc61.dll ->  libcuuc62.dll 

Just to be sure, the list of packages in MSYS 2 here is shown below:
<pre>
bash
bash-completion
bsdcpio
bsdtar
bzip2
coreutils
curl
dash
dtc
file
filesystem
findutils
flex
gawk
gcc-libs
getent
git
grep
gzip
inetutils
info
less
libargp
lndir
make
mingw-w64-x86_64-argon2
mingw-w64-x86_64-binutils
mingw-w64-x86_64-cmake
mingw-w64-x86_64-gcc
mingw-w64-x86_64-gcc-ada
mingw-w64-x86_64-gcc-fortran
mingw-w64-x86_64-gcc-libgfortran
mingw-w64-x86_64-gcc-objc
mingw-w64-x86_64-gdb
mingw-w64-x86_64-libgcrypt
mingw-w64-x86_64-libmangle-git
mingw-w64-x86_64-libsodium
mingw-w64-x86_64-make
mingw-w64-x86_64-nsis
mingw-w64-x86_64-pkg-config
mingw-w64-x86_64-qrencode
mingw-w64-x86_64-qt5
mingw-w64-x86_64-tools-git
mingw-w64-x86_64-winstorecompat-git
mintty
msys2-keyring
msys2-launcher-git
msys2-runtime
ncurses
pacman
pacman-mirrors
pactoys-git
pax-git
pkgfile
rebase
sed
tftp-hpa
time
ttyrec
tzcode
unzip
util-linux
which
</pre>

I am pleased if you can help me a little more.

**Comment by droidmonkey** [comment]
You're just using more up to date libraries when you build it. Are you saying both the download version and the one you compiled (2.3.4) crash on start up?

**Comment by droidmonkey** [comment]
oh crap forgot to tell you about the other packages that need to be down-versioned. GCC 8.2.x has a known bug with security flags that causes crashes. We use almost every security flag to prevent hacking of the application. You have to downgrade to GCC 7.3.0. I have consolidated them for you in this link:

https://drive.google.com/file/d/1GMsnaCieDrVpbpT1yDzXw6N5ML_GpZnD/view?usp=sharing

**Comment by droidmonkey** [comment]
What are the dependencies

**Comment by glowcat** [comment]
It is displayed as follows: 
<pre>
pacman -U /i/keepassxc/mingw-w64-x86_64-gcc-7.3.0-2/mingw-w64-x86_64-gcc-ada-7.3.0-2-any.pkg.tar.xz

Warning: Downgrading package mingw-w64-x86_64-gcc-ada (8.2.1 + 20181214-1 => 7.3.0-2)
Resolving dependencies ...
Warning: Unable to resolve "mingw-w64-x86-64-gcc = 7.3.0 - 2", dependent on "mingw-w64-x86-64-gcc -ada"
:: The following package can not be updated because dependency can not be resolved:
      mingw-w64-x86-64-gcc-ada
</pre>

**Comment by glowcat** [comment]
When downgrading gcc (8.2 to 7.3), it seems to be difficult as it is because many packages depend on it.
Is there a way to downgrade safely?
Below is the current gcc dependency relationship displayed by pactree:
<pre>
mingw-w64-x86_64-gcc
├─mingw-w64-x86_64-binutils
│ ├─mingw-w64-x86_64-libiconv
│ └─mingw-w64-x86_64-zlib
│   └─mingw-w64-x86_64-bzip2
│     └─mingw-w64-x86_64-gcc-libs
│       ├─mingw-w64-x86_64-gmp
│       ├─mingw-w64-x86_64-mpc
│       │ └─mingw-w64-x86_64-mpfr
│       │   └─mingw-w64-x86_64-gmp
│       ├─mingw-w64-x86_64-mpfr
│       └─mingw-w64-x86_64-libwinpthread-git provides mingw-w64-x86_64-libwinpthread
read
├─mingw-w64-x86_64-crt-git provides mingw-w64-x86_64-crt
│ └─mingw-w64-x86_64-headers-git
├─mingw-w64-x86_64-headers-git provides mingw-w64-x86_64-headers
├─mingw-w64-x86_64-isl
├─mingw-w64-x86_64-libiconv
├─mingw-w64-x86_64-mpc
├─mingw-w64-x86_64-gcc-libs
├─mingw-w64-x86_64-windows-default-manifest
├─mingw-w64-x86_64-winpthreads-git provides mingw-w64-x86_64-winpthreads
│ ├─mingw-w64-x86_64-crt-git
│ └─mingw-w64-x86_64-libwinpthread-git
└─mingw-w64-x86_64-zlib
</pre>

When pacman - Rsc etc etc delete all dependency files, it seems that the necessary files will disappear, so we are hesitant to do it

**Comment by droidmonkey** [comment]
Ok great! I'll add that to the wiki instructions

**Comment by glowcat** [comment]
Sorry, There was a mistake in the procedure. Since gcc-libs also has a dependency relationship, it will delete it and install the related package again later.
Here is the procedure confirmed again here (it will be executed after setting the current windows environment setting)
As for argon 2, it seems that the build can be executed even if patch is not applied
<pre>
# In order to install gcc of the old version, once destroy the latest gcc environment
pacman -Rsc mingw-w64-x86_64-gcc 
pacman -Rsc mingw-w64-x86_64-gcc-libs

# Reinstall old version of gcc
pacman -U http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-gcc-libs-7.3.0-2-any.pkg.tar.xz
pacman -U http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-gcc-7.3.0-2-any.pkg.tar.xz
# Otherwise, reinstall the necessary options for gcc
pacman -U http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-gcc-libgfortran-7.3.0-2-any.pkg.tar.xz
pacman -U http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-gcc-fortran-7.3.0-2-any.pkg.tar.xz
pacman -U http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-gcc-ada-7.3.0-2-any.pkg.tar.xz
pacman -U http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-gcc-objc-7.3.0-2-any.pkg.tar.xz

# Reinstall each package deleted in gcc's latest environment
# (Since it is in the cache, it should not be re-downloaded)
pacman -S mingw-w64-$(uname -m)-binutils mingw-w64-$(uname -m)-cmake
pacman -S mingw-w64-$(uname -m)-qt5 mingw-w64-$(uname -m)-libgcrypt mingw-w64-$(uname -m)-zlib mingw-w64-$(uname -m)-argon2 mingw-w64-$(uname -m)-libsodium mingw-w64-$(uname -m)-qrencode
# Install necessary environment for package
pacman -S mingw-w64-$(uname -m)-nsis
</pre>
