### ISSUE TITLE
KeePassXC-Browser in flatpaked Firefox doesn't connect to flatpaked KeePassXC

### ISSUE THREAD

**Issue by nexfwall** [keepassxreboot/keepassxc#2656]
## Expected Behavior
KeePassXC-Browser in flatpaked Firefox connect to the database opened in flatpaked KeePassXC, and I can fill my passwords in forms easily.

## Current Behavior
KeePassXC-Browser in flatpaked Firefox doesn't connect to the database opened in flatpaked KeePassXC.

## Possible Solution
If flatpak allows to run extensions, maybe Proxy should packaged as an extension to KeePassXC flatpak? Just call org.keepassxc.KeePassXC.Proxy

## Steps to Reproduce
1. Download any of [these](https://firefox-flatpak.mojefedora.cz/)
2. Install KeePassXC-Browser extension
3. Install KeePassXC from flathub
4. Open database in KeePassXC
5. Try to connect to it from flatpaked Firefox

## Debug Info
KeePassXC - 2.3.4
Revision: 6fe821c
Distribution: Flatpak

Libraries:
- Qt 5.12.0
- libgcrypt 1.8.3

Operating system: Fedora Silverblue 29.20190124.0
CPU architecture: x86_64
Kernel: linux 4.20.3-200.fc29.x86_64

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

P.S. Flatpak gonna be a pain in your ass for one more time I guess. :slightly_smiling_face:

**Comment by varjolintu** [comment]
Check if this helps: https://github.com/keepassxreboot/keepassxc-browser/issues/297#issuecomment-429235866.

**Comment by kaymio** [comment]
I stumbled onto the same problem and found another bug report on the FF flatpak repo here on Github.

https://github.com/xhorak/firefox-devedition-flatpak/issues/92

Not sure how to reference it. It would be really great to get this working.

**Comment by droidmonkey** [comment]
Closing this as we have no control over the FireFox Flatpak.

**Comment by rugk** [comment]
FYI, for everyone following: I have found a working around involving some manual steps you need to do though for KeePassXC<->Firefox communication, if Firefox is flatpaked/sandboxed (works if KeePassXC is sandboxed or not). [Read the full write-up/tutorial here.](https://discourse.flathub.org/t/how-to-run-firefox-and-keepassxc-in-a-flatpak-and-get-the-keepassxc-browser-add-on-to-work/437?u=rugk)
