### ISSUE TITLE
KeeShare Consolidated Issues

### ISSUE THREAD

**Issue by droidmonkey** [keepassxreboot/keepassxc#2657]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )
Listing of issues found with KeeShare that need to be fixed prior to final release of 2.4.0:

- [x] Nested KeeShare settings should not apply to imported sub-folders (ie, do not recursively apply sharing; do not allow shared folders to define share settings)
- [x] There is no way to manually refresh a share
- [x] When viewing a share, place a persistent banner above the entry list
- [x] There is a floating scrollbar when viewing group settings
![image](https://user-images.githubusercontent.com/2809491/51883459-ece07680-2350-11e9-8cc3-3c2bd7866c9b.png)

- [x] Database settings for KeeShare are impossible to read
![image](https://user-images.githubusercontent.com/2809491/51883504-231df600-2351-11e9-84fe-7393efe62889.png)

- [x] Add button in group KeeShare settings to easily clear the form data

**Comment by droidmonkey** [comment]
QuaZip error messages are confusingly worded:

https://github.com/keepassxreboot/keepassxc/blob/8bfc53923445a7afe216503a0630c55f01037106/src/keeshare/ShareObserver.cpp#L658-L693

**Comment by mstarke** [comment]
The recycle-bin duplication is a problem of the merge algorithm and is nothing directly related to KeeShare. It is however a side effect. My suggestion would be to enhance the merge algorithm to handle recycle bin duplications in a better way

**Comment by ckieschnick** [comment]
@droidmonkey did you already make some progress on this ticket? I've got some time to spare this week, so I may be able to help with some issues.

**Comment by droidmonkey** [comment]
Besides the floating scrollbar, I have not worked on this one as I have been handling other matters leading up to the release.

**Comment by ckieschnick** [comment]
I've got the first small fixes ready (clear button and better error messages added as two separate pull requests for easier review). For the next issues we need to discuss some points.

* What do you mean with "imported subfolders"? Why do you want to prevent to share the keys with others (most simple way to circumvent the restriction is using copy or references to a unrelated shared folder).
* Do you mean "force import" or "force export" by manually refreshing a share or possibly both?
* Viewing a share means, that we open a share database (without signature)? To allow this functionality, we need to inject some sort of flag into the database on write (but I would not force the read to require this flag).
* I could not reproduce the issue neither on Win10 nor on Debian (Virtual Box) with Qt 5.11. Both elide the long labels in the middle like configured.

**Comment by droidmonkey** [comment]
> * What do you mean with "imported subfolders"?

This is not about sharing the keys, it is about nested sharing settings. There is a slightly larger problem with sharing in general in that we are using absolute directories which does not scale when moving across platforms or even users. You can also setup a recursive share where two shares are pointing at each other.

![image](https://user-images.githubusercontent.com/2809491/53364576-19b28a00-390d-11e9-9671-646cc3039490.png)

> * Do you mean "force import" or "force export" by manually refreshing a share or possibly both?

I mean both. However it appears that the import/export now occurs after pressing OK from the "Edit Group" dialog. This may be fixed already (I think the issue was the broken SIGNAL/SLOT that was fixed in the beta1).

> * Viewing a share means, that we open a share database (without signature)?

What I meant by "viewing a share" was when you are displaying a shared database's entries in the entry view. Basically we only have the little globe icon in the group list to indicate the status of the share. We should also place a persistent banner when viewing the contents of that share to indicate it's status. This would be in addition to / similar to the search results banner.

![image](https://user-images.githubusercontent.com/2809491/53364826-ab21fc00-390d-11e9-8e01-3e5cc3caa2d1.png)

> * I could not reproduce the issue neither on Win10 nor on Debian

It appears that you can resize the columns now, that is good. However the columns are not initially sized such that they contain the text that is in them.

**Comment by ckieschnick** [comment]
> It appears that you can resize the columns now, that is good. However the columns are not initially sized such that they contain the text that is in them.

I'm not sure if it provide any improvement to resize the columns initially since the size is depending on the translation and paths. The current setting with resize as `QHeaderView::Interactive` allows the user to expand the columns as needed.

> This may be fixed already (I think the issue was the broken SIGNAL/SLOT that was fixed in the beta1).

Sounds like the force button is not needed - when `autosafe` is disabled, I think its better to not allow the user to force a save since this would allow to export changed entries which will be lost when the changes to the database are discarded.

> This is not about sharing the keys, it is about nested sharing settings.

Currently I don't see any problem with nested groups with sharing enabled (even if we reference the same container). It certainly is a unwanted scenario when a user references the same container within a database multiple times, but due to the UUIDs there should be no problem with updates. A problem arises at the point when one wants to share structure (in this case we need to remove all reference settings from the shared groups since we do not want to give another any indication that we share something with somebody else).

**Comment by droidmonkey** [comment]
I am splitting hairs a little bit, I do not think the nested share settings needs to be addressed at this time.

**Comment by ckieschnick** [comment]
My previous post is not completely correct - referencing the same container multiple times from within the database does make a difference in an export scenario. In this case, the last group to export will overwrite all changes of others before which may be not that good considering that other instances may listen to the file changes (i.e. synchronizing using dropbox or similar). We can add a small check if the reference is already used within the database to notify the user about the conflict. I'm not sure, if this solution will prevent all cases - especially considering mounts and network files systems which may lead to referencing the same resource with multiple paths. But I don't think that this corner case is really something the application can solve.
I suggest adding the message when we detect, that a share container is used multiple times. Do we want to prevent exports in this case?

**Comment by droidmonkey** [comment]
Yes we want to avoid overwriting data, especially if it would be "unintentional"

**Comment by ckieschnick** [comment]
I implemented a naive check to prevent the overwrite issues. The ticket contains additional information and points we may need to discuss to determine if the implementation is sufficient.
