### ISSUE TITLE
expiration notifications

### ISSUE THREAD

**Issue by martian742** [keepassxreboot/keepassxc#2664]
## Summary
I would like to be warned a predefined time in advance of the future expiration of my entry.

## Desired Behavior
Any visual clue would do, but also, but not limited to - a group that contains a soon-to-expire entry inside would change icon so to immediately warn the user at the overview level (when I work with my keepass DB, I see the list of groups every day - a red folder icon would stand out for example - indicating expiration inside).

## Possible Solution
Mentioned in the previous section.

## Context
I want to track expiring accounts/passwords easily in keepassxc.
I also want to track expiring licenses in the same tool, I already use keepassxc as a trampoline to most activities including launching SSH and browser sessions so it gets a lot of eyeball time. :)

**Comment by unfgreen** [comment]
Perhaps adding Show Expired Entries under Tools.

**Comment by droidmonkey** [comment]
This is covered by #551
