### ISSUE TITLE
Disable "Perform Autotype" button by default.

### ISSUE THREAD

**Issue by Bretzky** [keepassxreboot/keepassxc#2665]
I just hit this button by accident, not even aware it existed, and it posted my email & password in irc.

**Comment by droidmonkey** [comment]
The button is still there in 2.4.0, but we changed the shortcut to CTRL+SHIFT+V to prevent accidentally activating it.

**Comment by Germano0** [comment]
Please do add an option to completely disable auto type. You don't have idea how many times I runned it by mistake either by pressing the wrong keyboard combo or clicking the wrong entry. It's definitely a "time bomb"
Moreover the "confirm before auto type" does not work https://github.com/keepassxreboot/keepassxc/issues/579

**Comment by ddombrowsky** [comment]
:+1: +1
This can be disabled per-entry, but cannot be disabled globally, afaik.  This is a bug.  I've had to change multiple passwords because C-v is right next to C-b.

**Comment by ddombrowsky** [comment]
changing the global shortcut key doesn't seem to do anything either :/

**Comment by droidmonkey** [comment]
If you don't want to use autotype at all you can delete the "default autotype sequence" in the root group to effectively disable the CTRL+V action. It will still switch windows, but nothing will type.

**Comment by ddombrowsky** [comment]
That would be an acceptable workaround, except it doesn't seem to work.  Changing it to blank will reset it back to "use default."  I can change it to a "space" however, which I will do now.
 
This is in 2.3.1, the version installed in ubuntu 18.04's packages.

**Comment by droidmonkey** [comment]
Good to know!

**Comment by ochilan** [comment]
What happens if you set "Auto-Type" to "Disabled" instead of "Inherit from parent group" in the Root group (instead of modifying the Auto-Type sequence)? The corresponding drop-down menu is also visible in the screenshot previously posted by droidmonkey. Once I set this option to Disabled, Auto-Type doesn't seem to do anything anymore, as I would expect. I agree though that this option is hidden pretty well.

**Comment by wolframroesler** [comment]
Considering that some people (including myself ;-) ) would like the old Ctrl-V auto-type back (#3018, #3051) or at least want the hotkey to be configurable (#2689, #3017), how about a new setting "Auto-type hotkey" with three options "Shift-Ctrl-V (recommended)", "Ctrl-V (not recommended)", and "None"?

**Comment by phoerious** [comment]
I think this issue is non-negotiable. There has been a handful of vocal people wanting the old hotkey back, but the vast majority has just moved on. If we implement customizable hotkeys one day, this might be included, but we will not implement hotkey customizations because of this.

**Comment by arcticoder** [comment]
You understand that control-shift-V is also the shortcut key used in Office for pasting unformatted text. That muscle-memory isn't going away for me anytime soon, and I'm pasting into keepassxc all the time. So this is not a worthwhile risk to take for me, I have to uninstall this program until it's resolved.

**Comment by droidmonkey** [comment]
This was obviated by the 2.7.0 Auto-Type overhaul. A warning is shown before performing entry level Auto-Type.

**Comment by rpgdev** [comment]
@droidmonkey now I'm in need of disabling this warning. Where can I disable it? It gets in the way of EVERYONE who actually wants to use the autotype _hotkey._
