### ISSUE TITLE
Add an "include" directive to keepassxc.ini

### ISSUE THREAD

**Issue by droidmonkey** [keepassxreboot/keepassxc#2666]
Even better: and an `include` directive in `~\.config\keepassxc.ini` like many softwares like [git](https://github.com/nagromc/dotfiles/blob/5407637e402b10b144d796fe5d8bc23bfe3b24de/git/gitconfig#L221), [fish](https://github.com/nagromc/dotfiles/blob/5407637e402b10b144d796fe5d8bc23bfe3b24de/fish/config.fish#L3), [tmux](https://github.com/nagromc/dotfiles/blob/5407637e402b10b144d796fe5d8bc23bfe3b24de/tmux/tmux.conf#L101), [vim](https://github.com/nagromc/dotfiles/blob/5407637e402b10b144d796fe5d8bc23bfe3b24de/vim/vimrc#L200-L203), or [ssh](https://www.mankier.com/5/ssh_config#Include).

Really handy for dotfiles repositories where we don't want to publish secret parts, or to manage specific cases by machines like here.

In my case, I would like to make a reference to a tracked `~\.config\keepassxc_common.ini` in my **not**-tracked `~\.config\keepassxc.ini`. In `~\.config\keepassxc_common.ini`, I would have a common configuration through my devices (like `[General] LastOpenedDatabases` or `[security] lockdatabaseidlesec`), but in `~\.config\keepassxc.ini`, I would have everything else (for instance, options related to GUI that changes all the time).

_Originally posted by @nagromc in https://github.com/keepassxreboot/keepassxc/issues/1284#issuecomment-366043054_

**Comment by droidmonkey** [comment]
Unfortunately this will not be possible due to the way Qt handles config files. We would have to roll our own config process. However, we now split Local and Roaming config files in 2.6.0 which should alleviate a lot of problems here. Additionally, allowing enterprise enforcement of settings could solve this problem as well.

**Comment by l0b0** [comment]
Where can I find out more about "Local and Roaming config files"? I can't seem to find anything via a search engine. There's #4665, but that changes 45 files.

**Comment by phoerious** [comment]
https://superuser.com/a/21462/554082

**Comment by l0b0** [comment]
Oh, OK, so it's not something applicable to Linux.

**Comment by droidmonkey** [comment]
It is applicable to Linux: roaming is in `~/.config/keepassxc` and local is in `~/.cache/keepassxc`
