### ISSUE TITLE
[PRE-RELEASE] TOTP no longer works with OTP settings from Keepass

### ISSUE THREAD

**Issue by zaptan** [keepassxreboot/keepassxc#2671]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
TOTP to continue to work as it did in 2.3.4 showing RFC6238 settings from older entries 

## Current Behavior
[NOTE]: # ( Tell us what actually happens )
TOTP gives 1 second 1 digit 'custom' codes.
when you go into the setup TOTP options, and set it to default RFC6283 it still shows your key, however when you click ok and then try and view the TOTP again it now shows 6 digits with 1 second time step, and setup now has a blank key and is back to 'use custom settings' 

I was able to clear all otp and TOTP attributes, save, close keepassXC completely, then when I went back to the entry I was able to set it up new and it worked. 

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )
ether always default to the RFC settings if no up to date settings are found, or migrate the otp:key= attribute to the current TOTP Seed and TOTP Settings attributes

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1. open any database with an entry made with keepass and a TOTP with KeeOtp plugin
2. attempt to interact with TOTP show/setup

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )
I have Entries with totp settings created in keepass with KeeOtp's setting otp:key= attribute. 
in KeepassXC 2.3.4 these entries work correctly. In 2.4 beta these entries now only give a code of one digit for one second, and any attempts to use setup TOTP do not work to fix the entry

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.4.0-beta1
Build Type: PreRelease
Revision: 42cfe01

Libraries:
- Qt 5.12.0
- libgcrypt 1.8.4

Operating system: Windows 10 (10.0)
CPU architecture: x86_64
Kernel: winnt 10.0.15063

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

**Comment by droidmonkey** [comment]
Please post what the value of TOTP_SETTINGS is from the advanced attributes.

**Comment by zaptan** [comment]
There are no TOTP_SETTINGS it only sets a name of 'otp' and a value of 'key=<key>' 
and this still worked in keepassxc 2.3.4

**Comment by droidmonkey** [comment]
gotcha, I will fix this
