### ISSUE TITLE
CMD + W doesn't close window

### ISSUE THREAD

**Issue by julianschacher** [keepassxreboot/keepassxc#2672]
[TIP]:  # ( Provide a general summary of the feature in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Summary
[NOTE]: # ( Provide a brief overview of what the new feature is all about )

The keyboard shortcut `CMD + W` is meant to close the front window on macOS (as described in this support article: <https://support.apple.com/en-us/HT201236>).
KeePassXC utilizes this shortcut for closing the current database - so it's basically doing what a browser does when pressing `CMD + W` (closing the current tab).
The problem is however that the shortcut doesn't close the front window, after it closed the last database.

## Desired Behavior
[NOTE]: # ( Tell us how the new feature should work, be specific )

KeePassXC should close the front window after closing the last database and pressing `CMD + W` again.

This video shows what I mean:
<https://drive.google.com/open?id=1sUZKQEDNdI9GqH2PzesPN4r6i_yBqqDr>

And here's a video of Safari:
<https://drive.google.com/open?id=1qBsAw2dR0k0RkXwSJchjY_1bIYy3Od63>

I don't think it should act like Safari entirely - showing the database selection window after closing the last database is fine.
It should close the front window after pressing `CMD + W` again tho.

## Possible Solution
[NOTE]: # ( Not required, but suggest ideas on how to implement the addition or change )

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )

All macOS applications close the front window when pressing `CMD + W` (or pressing it multiple times, when using a browser with multiple tabs open for example). 
Not having this behavior in KeePassXC always throws me off, since I have to use my mouse then to close the window.

**Comment by julianschacher** [comment]
This isn't really a feature request, but I felt it's too much to call it a bug. So please adjust the labels in a way that is most correct.

**Comment by ian-h-chamberlain** [comment]
To add to this feature request / UX change – personally, I would prefer the shortcut closes the window _without_ closing the database, as I prefer to leave my default database open (but the window closed) while I do other tasks. For macOS applications which leave some kind of background service running, I am used to being able to close windows without quitting the application (e.g. `cmd + q`) to leave the application running.

To this end, it would be nice to have a setting which determines what the `cmd + w` ( or `ctrl + w` on other OSes, assuming you want to maintain feature parity) actually does:

- Close current database, leaving the window open
- Close current window, leaving any databases open
- Close the current database, closing the window if it is the last open database

This is just a suggestion, but for me at least would be the ideal implementation.

**Comment by droidmonkey** [comment]
For others awareness, `cmd + Shift + m` directly minimizes to tray even if you don't have "Minimize to tray" setting enabled.

**Comment by phoerious** [comment]
Cmd+W closes the tab, which is consistent with any browser, really. I am not sure how this could be made more consistent with breaking consistency elsewhere.

**Comment by kujass** [comment]
Many users have only one database, so what's the point of using [CMD+W] for closing tabs that don't visually exist?
It's misleading. I'm closing my database 10-15 times a day because I can't change the binding for [CMD+W].

Btw. Thunderbird also is based on UI with tabs. And when I use the [CMD+W] shortcut, Thunderbird is nicely hiding in the macOS dock (luckily, not logging out from my email accounts 👍 ).

**Comment by droidmonkey** [comment]
Switching to #6837
