### ISSUE TITLE
Search in all opened databases breaks if one database is locked

### ISSUE THREAD

**Issue by zoehneto** [keepassxreboot/keepassxc#2675]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
I have a setup with multiple databases of which only one is used to fill sites with the browser integration (KeePassXC-Browser). To avoid the tab focus issue (browser integration doesn't work if the wrong database tab has focus) I enabled the `Search in all databases for matching credentials` option in the settings. This should enable me to use the browser integration as long as the correct database is unlocked, no matter how many other databases are open.

## Current Behavior
[NOTE]: # ( Tell us what actually happens )
This works unless another database (not the one with passwords for the browser) is locked. Having a locked database open in a tab breaks search across all databases.

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1. Enable KeePassXC browser integration
2. Enable `Search in all databases for matching credentials` in the `Advanced` tab
3. Open one database (db1.kdbx)
4. Connect to db1 using the KeePassXC-Browser extension
5. Open a second database (db2.kdbx) but do not unlock it by entering the password
6. The browser integration is now broken until you unlock db2

## Debug Info
KeePassXC - Version 2.3.4
Revision: 6fe821c

Libraries:
- Qt 5.12.0
- libgcrypt 1.8.4

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 4.20.5-arch1-1-ARCH

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by varjolintu** [comment]
This is a known isssue. The extension always receives the state of the current active database tab, not all tabs.

**Comment by droidmonkey** [comment]
@varjoulinto Is this still an issue?

**Comment by varjolintu** [comment]
@droidmonkey Shouldn't be. Just tested these things yesterday and I don't recall seeing this one. I had two connected databases and tried locking the other one and verified that credentials are received from the open one.
