### ISSUE TITLE
Two password boxes, simultaneously

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [keepassxreboot/keepassxc#2677]
## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

A single password request window.

## Current Behavior
[NOTE]: # ( Tell us what actually happens )

Two such windows - occasionally. Screenshot:
![image](https://user-images.githubusercontent.com/47056543/52185169-62968780-2814-11e9-9b80-7ace2b7d4e5c.png)

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )

## Steps to Reproduce
Unknown.

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )

## Debug Info
KeePassXC - Version 2.3.1
Revision: 2fcaeea

Libraries:
- Qt 5.9.5
- libgcrypt 1.8.1

Operating system: Linux Mint 19.1
CPU architecture: x86_64
Kernel: linux 4.20.3-042003-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

Enabled extensions:
- I have legacy browser integration turned off (even though it appears in the list above) but I do have the modern browser integration enabled, though I have not been able to discover how it works (but passwords do get filled in my browser by KeePassXC).

**Comment by droidmonkey** [comment]
Your theming is all messed up as well. The issue with the multiple login windows is corrected in 2.4.0.

**Comment by LinuxOnTheDesktop** [comment]
Theming: yes, I know and I've fixed it.

> corrected in 2.4.0.

Marvellous. Thank you.
