### ISSUE TITLE
invalid keyobard layout used when auto-typing

### ISSUE THREAD

**Issue by burzek** [keepassxreboot/keepassxc#2678]
When auto-typing is performed and multiple keyboard layouts are installed, invalid keyobard layout is used for typing.

Region: sk_SK
Keyboard layout: us_US (sk_SK installed too)
kubuntu 18.10

When us_US keyboard layout is set, 1234 is entered as !@#$.
When sk_SK keyobard layout is set, 1234 is entered as 1234

**Comment by droidmonkey** [comment]
Duplicate
