### ISSUE TITLE
Does changing the master-password change the keyfile also?

### ISSUE THREAD

**Issue by noMICROSOFTbuhtz** [keepassxreboot/keepassxc#2680]
I use master password and key-file with KeePassXC 2.3.4. on Debian stable.
When I modify the master password - does this modify the key file also?

E.g. do I have to update all key-files I store on some usb-sticks?

btw: Are this GitHub Issues really for such community/forum questions? I couldn't find another place for that.

**Comment by droidmonkey** [comment]
Please post normal questions on our IRC or email them to use at team@keepassxc.org

Password and Key File are mutually exclusive from each other.

**Comment by phoerious** [comment]
Preferably IRC. "Mutually exclusive" may not be the best expression. Orthogonal is perhaps more correct. You can use either of them or both, but they are independent of each other, so changing one has no effect on the other.

**Comment by noMICROSOFTbuhtz** [comment]
I would recommand to use a forum-like question and answer channel. That way q&a would be documented and question would be asked only one time.

**Comment by droidmonkey** [comment]
It's not a bad idea, similar to Discord
