### ISSUE TITLE
How to generate key file?

### ISSUE THREAD

**Issue by noMICROSOFTbuhtz** [keepassxreboot/keepassxc#2681]
I couldn't find help or wiki page about how to generate a key file.

There is a **generate** button in KeePassXC 2.3.4 on Debian stable. I simply give a file location and the key file is stored. No parameters like bit, algorithm or whatever is relevant for key generation (like I would setup with gpg).

Also I don't find informations if I am able to use extern (e.g. with gpg) generated key-files and which paramters I should use in that case.

**Comment by droidmonkey** [comment]
You did it correctly, that is *A* key file that is generated. You can use *ANY* file as a key file. But DO NOT use one that has the potential to change!

**Comment by RealOrangeOne** [comment]
The ideal way to do this is using the `openssl` command line:

    openssl rand -out keepass.key 4096

(Replace 4096 with however large you want the key file to be. Larger keys are _more secure_, but slower)

**Comment by phoerious** [comment]
The KeePassXC generation feature uses a strong RNG as well. There is no need to generate overly long key files, since the contents will be squashed into a 256 bit hash anyway.
