### ISSUE TITLE
[PRE-RELEASE] KeePassXC fails to resolve the entry reference if the referenced entry is in a different group

### ISSUE THREAD

**Issue by szymonbultrowicz** [keepassxreboot/keepassxc#2684]
## Expected Behavior
Username and password should be inferred correctly, no matter in which group the entry currently belongs to.

## Current Behavior
KeePassXC fails to resolve the entry reference if the referenced entry is in a different group. Inferred username and password are empty. It's also not possible to copy neither the username nor the password. It works fine for cloned entries within the same group.
![image](https://user-images.githubusercontent.com/9554528/52306884-6a336900-2999-11e9-8602-17b0f2a9317d.png)
![image](https://user-images.githubusercontent.com/9554528/52306891-715a7700-2999-11e9-91c6-72577669fc7c.png)
![image](https://user-images.githubusercontent.com/9554528/52306906-791a1b80-2999-11e9-9071-7c15cf40bb4f.png)
![image](https://user-images.githubusercontent.com/9554528/52306922-80412980-2999-11e9-8710-280c86dfeed1.png)

## Steps to Reproduce
1. Create a new group
2. Clone an entry with "Replace username and password with references" option
3. Move the cloned entry to a different group

## Context
Started to happen in the version 2.4.0-beta1. Works fine in 2.3.x

## Debug Info
KeePassXC - Version 2.4.0-beta1
Build Type: PreRelease
Revision: 42cfe01

Libraries:
- Qt 5.12.0
- libgcrypt 1.8.4

Operating system: macOS 10.14
CPU architecture: x86_64
Kernel: darwin 18.2.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (only unsigned sharing)
- YubiKey
- TouchID

**Comment by droidmonkey** [comment]
Good report, replicated.

Error is here:
https://github.com/keepassxreboot/keepassxc/blob/develop/src/core/Entry.cpp#L922

Instead of using m_group we should be using m_group->database()->rootGroup()
