### ISSUE TITLE
Document steps to reauthorize MacOS accessibility control for auto type

### ISSUE THREAD

**Issue by vraravam** [keepassxreboot/keepassxc#2685]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
I have a db from the previously released version of KeepassXC. When I open the db with that version, I am able to use autotype to open a url, and another key combo to autotype. 

## Current Behavior
[NOTE]: # ( Tell us what actually happens )
With the latest beta, (2.4.0-beta1), the key combo seems to have changed to open the url, but neither the menu, nor the key combo work to autotype the username/password.

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1.
2.
3.

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.4.0-beta1
Revision: 42cfe01

Libraries:
- LIBS

Operating system: Mac OS
CPU architecture: x86
Kernel: KERNEL

Enabled extensions:
- EXTENSIONS

**Comment by droidmonkey** [comment]
The keycombo to autotype was changed to CMD+SHIFT+V vice CMD+V to avoid accidental triggering. CMD+V is the universal shortcut for "PASTE" which can be confusing to new users.

![image](https://user-images.githubusercontent.com/2809491/52388641-5f420c80-2a5d-11e9-89f9-9b074bcad394.png)

I think this is what you mean?

**Comment by vraravam** [comment]
@droidmonkey - thanks - but, I have already mentioned that I tried both the [new] key combo, as well as the menu item - neither of which work in Mac OS Mojave. Of course the key combo being changed is something that I got hit with - but then discovered that with the hint in the pull down menu.

**Comment by vraravam** [comment]
Also - it would be a good idea to provide a facility to set our own key combo - coz, I have the following thoughts:
1) I have a clipboard palette with history - and that is set to Cmd+Shift+V  - many developers use something similar and so this clash is not something that I was expecting.
2) When focus is on the Keepass window, I think Cmd+V should not conflict. I think that is a training issue - but for those who use this password manager, I dont think I agree on that being "accidentally typed".

**Comment by droidmonkey** [comment]
The reason auto-type is not working is because you need to refresh your privacy authorization. Do this by removing KeePassXC from the privacy screen and re-adding. I believe this is caused by the fact that we switched code signing keys from @phoerious to mine.

![image](https://user-images.githubusercontent.com/2809491/52414969-c1c5f780-2ab3-11e9-963f-4cccba9c34d1.png)

**Comment by vraravam** [comment]
@droidmonkey - thanks, but that did not work either. I uninstalled the old version, removed the entry from the Privacy screenshot as you show above, then installed the beta, manually added `KeepassXC` to the list above, restarted KeepassXC, but when I press `Cmd+Shift+V`, the focus stays on the Keepass window - and, in the default autotype sequence, the `enter` keypress seems to trigger the "Edit" functionality within KeepassXC. I am using FF Nightly if that makes a difference, and its set as my default browser.

**Comment by droidmonkey** [comment]
Cmd+Shift+v requires you to focus on the window you want to autotype in just prior to focusing on KeePassXC. In my testing it worked flawlessly with both the in-app shortcut and the global shortcut.

**Comment by vraravam** [comment]
`Cmd+Shift+U` works to open the url in the browser, but immediately after that, focussing on KP and pressing `Cmd+Shift+V` does not switch back to the browser.

**Comment by droidmonkey** [comment]
Unfortunately I cannot replicate your situation. Perhaps it has something to do with nightly?

**Comment by vraravam** [comment]
thanks for the quick feedback @droidmonkey . what i dont understand is why the same thing works in non-beta KP with FF Nightly while beta-KP has this problem with the same FF nightly.

**Comment by weslly** [comment]
I just tested with beta1 and found no issues with autotype, but only after I added it manually to the privacy/accessibility permissions screen (usually it would at least ask to add it if it wasn't there already).

**Comment by TuxyKey** [comment]
KeeePassXC 2.3.4. OSX Mojave 10.14.3.
@droidmonkey your suggestion to remove the entery from "Security & Privacy" - Accessibility - apps allowed to control computer.. and then adding KeePassXC worked for me.. thanks.. i was all ready to go back to MacPass hahaha but love the SSH agent intergration and commandline interface.. keep up the great work.

**Comment by vraravam** [comment]
@droidmonkey - I think it must have been the order in which I was uninstalling/reinstalling KP and the unsetting/setting of the security and privacy pref pane. Once I followed the uninstall (using homebrew), remove the setting, reinstall the KP-beta using homebrew and then going to the Security and Privacy settings to enable - *then* things started working.

Thanks for following up! we can close this issue.
