### ISSUE TITLE
Crash on Right-click in System Tray

### ISSUE THREAD

**Issue by Platzkart** [keepassxreboot/keepassxc#2686]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Right-clicking icon in system tray should produce a context menu, from which I can select options like "Unlock database" and so on.

## Current Behavior
[NOTE]: # ( Tell us what actually happens )
Right-clicking icon in system tray immediately crashes KeepassXC, throwing up this error 
![image](https://user-images.githubusercontent.com/47435862/52449316-c2e83a80-2b2e-11e9-9040-9a50209aa629.png)
Reinstalling KeepassXC has not helped.

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1.Minimise KeepassXC to system tray.
2.Right-click the tray icon.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.3.4
Revision: 6fe821c

Libraries:
- Qt 5.11.1
- libgcrypt 1.8.3

Operating system: Windows 10 (10.0)
CPU architecture: x86_64
Kernel: winnt 10.0.17763

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by droidmonkey** [comment]
This is odd, never experienced this before. You can try using the 2.4.0-beta1, we are releasing beta2 soon.

**Comment by Platzkart** [comment]
> This is odd, never experienced this before. You can try using the 2.4.0-beta1, we are releasing beta2 soon.

Hi, thanks. Switching to the beta has resolved the issue, whatever was causing it!
