### ISSUE TITLE
Priority for logins on the same domain for filling passwords

### ISSUE THREAD

**Issue by muhlinux** [keepassxreboot/keepassxc#2688]
## Summary
Let me set a priority in the database for logins on the same domain for filling passwords.

I have 3 accounts on domain example.com.
Normally can fill Username and Password with `Alt+Shift+U ` with  KeePassXC-Browser. 
But it doesn't actually fill if you have more than one account, instead it will show the account names.

## Desired Behavior
Say I have account A, B, & C.
I set the priority to 1, 2 and 3 (In the KeePass entry, if none is specified set priority by date created )
Instead of showing the account names in the field, fill out the credentials every time I press Alt+Shift+U and cycle through the list of accounts. 

Example:
press `Alt+Shift+U` -> fill out 1st priority account credentials -> press ENTER -> login
or press `Alt+Shift+U` again -> fill out 2nd priority account credentials -> press ENTER -> login
etc.

## Context
The key here is the time saved, filling out the credentials one uses most frequently.

This is really just a polish feature to an already awesome program! 
Thank you to all the maintainers and collaborators contributing to KeePass! 
I love it and use it everyday.

**Comment by droidmonkey** [comment]
I believe the credentials are ordered alphabetically in the choices. Instead of adding another property to the entry just add 1, 2, 3 etc to the front of each entry title.

I agree pressing the fill keyboard shortcut multiple times should cycle between the available entries.

**Comment by varjolintu** [comment]
Or.. you can hit the keyboard shortcut once, press `Arrow Down` to select the next entry and press `Enter`.

In the current release the first item of the autocomplete menu is not activated, but that's a quick fix (for the devs: No jQuery PR already does this).

**Comment by droidmonkey** [comment]
Not needed anymore as there is a search in the extension.
