### ISSUE TITLE
Remembering database doesn't work

### ISSUE THREAD

**Issue by vlenzer** [keepassxreboot/keepassxc#269]
* KeePassXC version/commit used: 2.1.1
* Qt version: 5.8.0
* Operating System and version: Linux Mint 18.1 64-bit
* Used way to start program: AppImage & Deb Version

I can't get KeePassXC to remember my Database after closing the program, even though I checked the option in settings. In 2.1.0 it din't work either.

**Comment by phoerious** [comment]
How do you terminate KeePassXC? Does this only happen when it is forcefully shut down (e.g. when ending the session) or also when you exit cleanly via File->Quit?

**Comment by vlenzer** [comment]
Oh forgot to mention this. It happens when pressing X but also when closing
the program via file -> quit.


Am 08.02.2017 18:30 schrieb "Janek Bevendorff" <notifications@github.com>:

How do you terminate KeePassXC? Does this only happen when it is forcefully
shut down (e.g. when ending the session) or also when you exit cleanly via
File->Quit?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/keepassxreboot/keepassxc/issues/269#issuecomment-278400096>,
or mute the thread

**Comment by louib** [comment]
@vlenzer do you check the `Remember last databases` option or the `Load previous databases on startup` option? The first option will populate the `Recent Databases`, while the second will preserve the database tabs on startup.

**Comment by vlenzer** [comment]
@louib Yeah, everything is checked. I also unchecked the option, restarted the program, checked the option and restarted again and it doesn't work nevertheless.

**Comment by TheZ3ro** [comment]
Can you print here the content of `~/.config/keepassxc/keepassxc.ini` (just the LastDatabases, LastDir and LastOpenedDatabases are fine)

**Comment by vlenzer** [comment]
Can't find any  LastDatabases, LastDir or LastOpenedDatabases:

`[General]
LastOpenedDatabases=@Invalid()
ShowToolbar=true

[GUI]
EntryListColumnSizes=150, 150, 100
EntrySearchColumnSizes=@Invalid()
MainWindowGeometry=@ByteArray(\x1\xd9\xd0\xcb\0\x2\0\0\0\0\x1\x11\0\0\0>\0\0\x4\x30\0\0\x2\xed\0\0\x1\x11\0\0\0Y\0\0\x4\x30\0\0\x2\xed\0\0\0\0\0\0\0\0\x5V)
SplitterState=@Invalid()`

**Comment by phoerious** [comment]
If that is everything that's in this file, it also means that you haven't activated the option to remember your last database files. This should add this line in the `[General]` section to the file:

```
RememberLastDatabases=true
```

**Comment by vlenzer** [comment]
@phoerious That doesn't work either. But I noticed that also I can't change the language of KeePassXC. It seems as changing something in settings doesn't affect anything at all.

**Comment by jensihnow** [comment]
I've similar issue. It was working in 2.1.0 but it isn't in 2.1.1. 
I'm running KeePassXC on MacOS and the option is checked in settings.
Ususally I do have two database files "open" and if I close KeePassXC and restart they are no longer "open" and I need to select them using the history.

Where is the settings file located on MacOC?

**Comment by vlenzer** [comment]
With the difference, that my history is empty..

**Comment by phoerious** [comment]
@vlenzer That sounds more like KeePassXC is having problems writing to your config file. Can you check the permissions?

@jensihnow Not sure, need to look that up. On Linux it's ~/.config/keepassxc/keepassxc.ini. On Mac it will be something similar in whatever the default config directory is.

**Comment by vlenzer** [comment]
@phoerious 
`ls -l  ~/.config/keepassxc/keepassxc.ini
-rw-r--r-- 1 root root 351 Feb 14 10:10 /home/****/.config/keepassxc/keepassxc.ini
`

**Comment by vlenzer** [comment]
@TheZ3ro Oh, you are right! My bad..
But even with
` -rwxrwxrwx 1 *username* users `
I'm only to change settings when starting KeePassXC as root. This shouldn't be the solution, should it?

**Comment by phoerious** [comment]
Also check the permissions of the .config/keepassxc and folder.

**Comment by TheZ3ro** [comment]
Have you run the AppImage as root the first time? Maybe it has created the folder as root user

**Comment by vlenzer** [comment]
Also after changing the complete folder it still didn't work.
But after deleting the folder and installing the deb Version again it worked.

@TheZ3ro no, I don't think I started it as root. As far as I remember I just double clicked the file. 

Sorry for being such a noob! And thank you for your help!

**Comment by goodloop** [comment]
@phoerious seems I am facing the same problem here. and there are no ~/.config/keepassxc/keepassxc.ini file in my home directory.  My environment is macOS 10.12.3, and use keepassX before.
Any hint?

**Comment by bipox** [comment]
Same issue, I'm using linux (manjaro). Permissions of the .config are ok.

**Comment by louib** [comment]
@bipox @goodloop seems like this issue is still valid. We'll follow up with [this new issue](https://github.com/keepassxreboot/keepassxc/issues/430)

**Comment by pjbakker** [comment]
Same here.

I have:
~~~
OpenPreviousDatabaseOnStartup=true
RememberLastDatabase=true
~~~

And although it does populate the Reopen menu, it does not open the database on startup. (independent of how Keepassxc closed)

This is on Mac OS Sierra 10.12.4, using Keepassxc 2.1.4

**Comment by phoerious** [comment]
Fix has already been merged into develop.

**Comment by pjbakker** [comment]
@phoerious Thanks for the update. Any indication of when a new release will be made?

**Comment by phoerious** [comment]
No, but hopefully end of May or beginning of June.
