### ISSUE TITLE
Cannot convert KDBX 4 to KDBX 3.1 or KeePassXC 2.4.0 beta seems to auto convert to KDBX 4

### ISSUE THREAD

**Issue by guardiande** [keepassxreboot/keepassxc#2693]
## Expected Behavior
Opening and saving an existing database should stick with the original KDBX version.

## Current Behavior
It seems that under some circumstances (maybe updating the browser integration settings) KeePassXC changes the file format from KDBX 3.1 to KDBX 4. Even when changing the database settings to KDBX 3.1 it sticks with KDBX 4.

This is pretty annoying since many other KeePass programs cannot not handle KDBX 4.

## Possible Solution
None yet.

## Steps to Reproduce
1. Open a KDBX 3.1.
2. Change DB settings to KDBX 4.
3. Verify the file version (bytes 08-11) is 4.0
4. Change DB settings to KDBX 3.1.
5. Verify the file version (bytes 08-11) is 4.0

## Debug Info
KeePassXC - Version 2.4.0-beta1
Build Typ: PreRelease
Revision: 42cfe01

Libraries:
- Qt 5.12.0
- libgcrypt 1.8.4

Betriebssystem: macOS 10.14
CPU-Architektur: x86_64
Kernel: darwin 18.2.0

Aktivierte Erweiterungen:
- Auto-Type
- Browser-Integration
- SSH-Agent
- KeeShare (only unsigned sharing)
- YubiKey
- TouchID

**Comment by droidmonkey** [comment]
This is correct, there are certain conditions where it is impossible to down-convert to KDBX 3.1 without losing data. One of those conditions is using "custom data" which the browser integration does now starting with 2.4.0.

What other programs don't understand KDBX4? I was aware of a few, but they did not seem widely used. At this point KDBX 3.1 is deprecated.

**Comment by guardiande** [comment]
I'm using KyPass 3 on iOS. KeePassX also can't handle KDBX 4.

Is there a way to convert to KDBX 3.1 when I already have custom data?

**Comment by guardiande** [comment]
Ok, your custom data just cost me 8€ to upgrade to KyPass 4 that supports KDBX 4 ;-)

**Comment by phoerious** [comment]
I don't see KeePassX as a reason to stay with KDBX 3.1. KeePassXC can be seen as its successor as there has been no development to the program since we forked from it a bit over two years ago.

What we should do perhaps is disable the KDBX 3.1 selection when a downgrade is not possible to avoid confusion.

**Comment by guardiande** [comment]
No worries, I just tried KeePassX to debug the problem.

As there's a possibility to break compatability with some older programs it would be a good idea to warn before implicitly upgrading to KDBX 4.

**Comment by droidmonkey** [comment]
You could have gone with minikeepass for ios, its free :blush:

**Comment by guardiande** [comment]
Hmmm... tried that too. Did not work. 🤔https://github.com/MiniKeePass/MiniKeePass/issues/467

**Comment by droidmonkey** [comment]
Interesting! Minikeepass was the go to recommendation on IRC for folks with iOS. They need to update...

**Comment by jmou** [comment]
This just bit me as well. I am also using MiniKeePass; it appears to be the only open source client for iPhone (the selection of clients on iPhone is pretty disappointing...).

**Comment by jkhsjdhjs** [comment]
> This is correct, there are certain conditions where it is impossible to down-convert to KDBX 3.1 without losing data. One of those conditions is using "custom data" which the browser integration does now starting with 2.4.0.
Is it possible to remove all custom data from a database at once?

**Comment by phoerious** [comment]
No. And CustomData are not some kind of accident. They store important information such as your KeePassXC-Browser pairings.

**Comment by jkhsjdhjs** [comment]
Yes, I know. Just wanted to remove the custom data each time I export the DB to my iOS device, because I don‘t need the custom data there anyways.
