### ISSUE TITLE
Improve message dialog when locking database

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [keepassxreboot/keepassxc#2694]
&nbsp;&nbsp;&nbsp;&nbsp;After a while, the meaning of the following message (/question) became clear to me.

![image](https://user-images.githubusercontent.com/47056543/52600737-94cb6900-2e54-11e9-9687-d0edd71910af.png)

Clearly, though, the text is not ideal. For, first, the text seems to suggest that pressing 'cancel' would _either_ let me finish my changes _or_ would discard those changes, whereas choosing the other option would do . . what? (See what I mean?). Secondly, selecting 'cancel' to _save_ data is counter-intuitive.

&nbsp;&nbsp;&nbsp;&nbsp;I suggest the following text.

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Title: Problem locking database
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Message: The database has unsaved changes!
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Buttons: [1] abort lock; [2] save changes and lock; [3] DISCARD changes and lock

**Comment by droidmonkey** [comment]
This message is no longer a part of the build.
