### ISSUE TITLE
Don't require password repeat if password is visible

### ISSUE THREAD

**Issue by droidmonkey** [keepassxreboot/keepassxc#27]
This makes it annoying to show the password when you type it in and not consistent with KeePass usage.

**Comment by TheZ3ro** [comment]
:+1:

**Comment by TheZ3ro** [comment]
Maybe this is usefull https://github.com/keepassx/keepassx/pull/73

**Comment by TheZ3ro** [comment]
If this is not a problem I can fix this in #92 (You are assigned so I'm asking)

**Comment by droidmonkey** [comment]
Yes please do
