### ISSUE TITLE
Auto-type global default delay

### ISSUE THREAD

**Issue by mihaiile** [keepassxreboot/keepassxc#270]
I know that on keepassx using the pull request with auto-type delay you could set a **AutoTypeInterKeyDelay=** configuration under **[General]** secion in the .ini file.

How can we set a global/default delay for when there is no specific delay set in the template?
I do not want to edit ALL my passwords entries just to add {DELAY n} on each of them.

**Comment by mihaiile** [comment]
I just noted that you can set the template {DELAY=n} for the group, so it's a kind of solution I guess :)

**Comment by TheZ3ro** [comment]
Note that `{DELAY=n}` and `{DELAY n}` are 2 different things
