### ISSUE TITLE
Building for windows OS, not just on windows OS

### ISSUE THREAD

**Issue by travellers** [keepassxreboot/keepassxc#2700]
[TIP]:  # ( Provide a general summary of the feature in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Summary
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
The open source code are for Linux/Mac OS, not for windows OS.
That means we can not build and output .exe application.

## Desired Behavior
[NOTE]: # ( Tell us how the new feature should work, be specific )
Could you please provide the source code which can be built for windows OS?
Thanks!

## Possible Solution
[NOTE]: # ( Not required, but suggest ideas on how to implement the addition or change )

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )

**Comment by phoerious** [comment]
Please read our wiki for Windows build instructions: https://github.com/keepassxreboot/keepassxc/wiki/Set-up-Build-Environment-on-Windows
We do not maintain a separate Windows code base.
