### ISSUE TITLE
Verification failure?

### ISSUE THREAD

**Issue by e-sphaera** [keepassxreboot/keepassxc#2701]
Trying to verify the downloaded ZIP-file in Win10 with the correspondig signature I get back these syntax:

C:\Users\web\Downloads\KeePassXC>gpg --verify KeePassXC-*-Win64-Portable.zip.sig
gpg: die unterzeichneten Daten sind wohl in 'KeePassXC-2.3.4-Win64-portable.zip'
gpg: Signatur vom 08/23/18 20:54:04 Mitteleuropõische Sommerzeit mittels RSA-Schlüssel ID B59076A8
gpg: Signatur kann nicht geprüft werden: Kein öffentlicher Schlüssel

C:\Users\web\Downloads\KeePassXC>

Don't know what to do ...
Please help!
e-sphaera

**Comment by phoerious** [comment]
You need to import the public key before as described in our verification guide: https://keepassxc.org/verifying-signatures/
