### ISSUE TITLE
Auto-update keepassxc-proxy path in org.keepassxc.keepassxc_browser.json

### ISSUE THREAD

**Issue by bjornfor** [keepassxreboot/keepassxc#2706]
## Summary
I would like for KeePassXC to make sure that the path to keepassxc-proxy, as stored in ~/.mozilla/native-messaging-hosts/org.keepassxc.keepassxc_browser.json is correct on every startup. (Other platforms may have this state elsewhere, this example is for linux + firefox.)

## Desired Behavior
The keepassxc-proxy path stored in ~/.mozilla/native-messaging-hosts/org.keepassxc.keepassxc_browser.json should be a working/existing/correct path, always.

## Possible Solution
On startup, read the ~/.mozilla/native-messaging-hosts/org.keepassxc.keepassxc_browser.json file (and similar state files). Compare the file contents (specifically in this case, the keepassxc-proxy path) with the correct data. If the data is different, update the state file. Alternatively, just (over)write the file on startup.

## Context
I'm on NixOS, where a package's path change on every update (and rollback). Packages are installed in separate paths, there is no global /usr/bin/ where all binaries go. After a package update, the path to keepassxc-proxy in the JSON file is stale (so the old program would get called). And after running garbage collection, the browser plugin can no longer connect. Basically, the lack of this feature cause "Timeout or not connected to KeePassXC" after package updates. Workaround: go to "Tools -> Settings -> Browser Integration" and disable and then re-enable the feature. This writes a new file with correct contents.

**Comment by droidmonkey** [comment]
How does KeePassXC know where it's proxy application is if it constantly changes? The solution is not to overwrite the config file constantly. You probably need to provide a stable location for the proxy application under the browser settings advanced page. NixOS should be symlinking to the current active package location on update.

**Comment by droidmonkey** [comment]
You should read this: https://nixos.org/nix/manual/#fig-user-environments

The answer is in the verbiage.

**Comment by bjornfor** [comment]
> How does KeePassXC know where it's proxy application is if it constantly changes?

The correct path to the proxy is always baked into keepassxc package. (When keepassxc is updated, so is keepassxc-proxy.) That's how every time the JSON file is written, it will contain the correct keepassxc-proxy path. The problem is the file is only written once, and then never checked/updated again.

> You probably need to provide a stable location for the proxy application under the browser settings advanced page.

That's manual work. I prefer automation.

> NixOS should be symlinking to the current active package location on update.

Yes, there will be a (stable) symlink that can be used. But which one it is depends on how the package was installed (by admin or by unprivileged user). My guess is it will be more difficult for keepassxc to find out which symlink it was called from than to update the JSON when needed.

> You should read this: https://nixos.org/nix/manual/#fig-user-environments

Oh, yes, I'm familiar with that. But I'm looking for a fully automated solution. As in; i don't want to manually configure the keepassxc-proxy path on every system I use, if keepassxc can do it automatically.

Btw, I realize now that this problem can also be demonstrated on "normal" linux distros. Imagine you have installed keepassxc from distro package. keepassxc then writes some /usr/bin/keepassxc-proxy path to the JSON file in your $HOME. A bit later you build and install keepassxc from source, perhaps to /usr/local/bin. Now the JSON file still points to the distro package keepassxc-proxy binary, instead of the new one that was built from source. See the problem?

**Comment by droidmonkey** [comment]
Please try entering the path to the proxy application that uses the stable symlink in the settings:

![image](https://user-images.githubusercontent.com/2809491/52890985-c181c800-3155-11e9-8d85-e682be155150.png)

Every time you go through this settings dialog, KeePassXC will rewrite the proxy json.

**Comment by varjolintu** [comment]
From the settings image above, you can check the "Update native messaging manifest files at startup" should automatically update the JSON scripts. Have you tried it? The path is updated on KeePassXC startup.

**Comment by bjornfor** [comment]
> Please try entering the path to the proxy application that uses the stable symlink in the settings:

@droidmonkey: Yes, that's a possible solution (workaround). But I would like to eliminate manual configuration steps, when possible.

> From the settings image above, you can check the "Update native messaging manifest files at startup" should automatically update the JSON scripts. Have you tried it?

@varjolintu: I didn't know about it. I just tried it now. It works!

Why isn't this default? Is it because of the extra (and mostly unneeded) writes? My proposed solution in the first post was to only update the file when needed (i.e. when the state file is stale). If that was to be implemented, I guess this option could be default on? And perhaps even removed from the UI? (Because, why would you ever want to deliberately let the file go stale?)

**Comment by phoerious** [comment]
> Because, why would you ever want to deliberately let the file go stale?

You do not want KeePassXC to overwrite the file if you have made manual changes to it (e.g. because you are using a local development version of the browser extension).

**Comment by bjornfor** [comment]
>> Because, why would you ever want to deliberately let the file go stale?

> You do not want KeePassXC to overwrite the file if you have made manual changes to it (e.g. because you are using a local development version of the browser extension).

Ok. So then it is down to "who owns the file". Is it the app or the user/developer? IMHO, by default the app should own the file, and advanced users (developers) can enable an option to take ownership and edit/maintain the file themself.

Does that sound reasonable?

**Comment by bjornfor** [comment]
> Does that sound reasonable?

Hehe, sorry to answer this myself. But... basically the current behaviour means that I as an end user have to go to Advanced settings (where I'm being warned that making changes are dangerous!), to set an option to tell the app to _continue_ taking ownership of a file it created _in the first place_.

So yes, I think it's reasonable that that the app owns the file by default, making sure that the content is correct. :-)

**Comment by varjolintu** [comment]
The automatic update is enabled by default in 2.4.0.

**Comment by bjornfor** [comment]
Thanks!
