### ISSUE TITLE
Keyboard Shortcut for 'Cycle through opened tabs'

### ISSUE THREAD

**Issue by jonyhayama** [keepassxreboot/keepassxc#2712]
## Summary
Add some keyboard shortcuts for tabs

## Desired Behavior
Press CTRL + Tab: Cycle through opened tabs

## Context
I just think it's easier when you're working with more than one opened tab to be able do cycle through them with a shortcut (like you would on any browser)

**Comment by phoerious** [comment]
This is already possible and handled by the Qt framework.

**Comment by droidmonkey** [comment]
CTRL+TAB and CTRL+SHIFT+TAB were added in 2.4.0 in case your OS doesn't handle them
