### ISSUE TITLE
Browser plugin URL matching should match https by default

### ISSUE THREAD

**Issue by dsjstc** [keepassxreboot/keepassxc#2715]
## Summary
If the entry's URL field is a partial entry consisting of only a bare domain name, I would expect it to match the browser's fully qualified URL.

## Desired Behavior
Default to https instead of http in the pattern match, or better yet, completely remove the arbitrary assumption of a protocol.  I might want the entry to match all available protocols, which are not restricted to http and https.

## Possible Solution
Remove the restriction from the pattern match.

## Context
I have several hundred entries in my database.  Most of them have only the top-level domain name and have not specified a protocol, because they were manually entered or imported.  I'm gradually adding https://*/ to the beginning of them, but the requirement isn't intuitive.

**Comment by droidmonkey** [comment]
You can disable scheme matching in the browser plugin settings:

![image](https://user-images.githubusercontent.com/2809491/53043200-fba0e180-3455-11e9-8684-5b601aa11e21.png)

I do agree that the default match should be https instead of http

**Comment by dsjstc** [comment]
Good edit, I agree.

Also, thanks for the tip.  Been bothering me for months.  This time I stared blankly at the "auto-type" preferences for, a long time, at least a minute, before posting.

**Comment by varjolintu** [comment]
Included in 2.4.0.
