### ISSUE TITLE
Weird context menu position

### ISSUE THREAD

**Issue by MaxMatti** [keepassxreboot/keepassxc#2716]
## Expected Behavior
Context menus appear below to the right of the cursor if there's enough screen space

## Current Behavior
Context menus cram to the top of the screen

## Steps to Reproduce
Maybe use the same monitor arrangment as me?
Then open a context menu. Any context menu. Or even one of the menus at the top of the window.
**Edit:** Oh, and I forgot to mention that when only one monitor is connected, everything is fine.

## Context
Multi-Monitor-setup:

    $ xrandr --output DP3 --pos 1366x0 --output LVDS1 --pos 0x672
    $ xrandr --query                                             
    Screen 0: minimum 8 x 8, current 3926 x 1440, maximum 32767 x 32767
    LVDS1 connected primary 1366x768+0+672 (normal left inverted right x axis y axis) 310mm x 170mm
       1366x768      60.00*+
       1280x720      59.74  
       1024x768      60.00  
       1024x576      60.00    59.90    59.82  
       960x540       60.00    59.63    59.82  
       800x600       60.32    56.25  
       864x486       60.00    59.92    59.57  
       640x480       59.94  
       720x405       59.51    60.00    58.99  
       680x384       60.00  
       640x360       59.84    59.32    60.00  
    [...]
    DP3 connected 2560x1440+1366+0 (normal left inverted right x axis y axis) 600mm x 340mm
       2560x1440     59.95*+
       1920x1200     59.88  
       1920x1080     60.00    60.00    50.00    59.94    24.00    23.98  
       1920x1080i    60.00    50.00    59.94  
       1600x1200     60.00  
       1680x1050     59.95  
       1280x1024     75.02    60.02  
       1280x800      59.81  
       1152x864      75.00  
       1280x720      60.00    50.00    59.94  
       1024x768      75.03    60.00  
       800x600       75.00    60.32  
       720x576       50.00  
       720x480       60.00    59.94  
       640x480       75.00    60.00    59.94  
       720x400       70.08  
    [...]

![description see below](https://user-images.githubusercontent.com/1584478/53039844-6109c800-3480-11e9-946b-913eeb202db3.png)
Overview of my monitor setup, X marks roughly where I right-clicked.

![description see below](https://user-images.githubusercontent.com/1584478/53039874-71ba3e00-3480-11e9-8299-e27e2a2fd536.png)
Window menus appear in a weird position.

![description see below](https://user-images.githubusercontent.com/1584478/53039930-85fe3b00-3480-11e9-9200-a1c00bb6b595.png)
Context Menus are all crammed to the top of the screen, X marks roughly where I right-clicked.

## Debug Info
KeePassXC - Version 2.3.4
Revision: 6fe821c

Bibliotheken:
- Qt 5.12.1
- libgcrypt 1.8.4

Betriebssystem: Arch Linux
CPU-Architektur: x86_64
Kernel: linux 4.20.7-arch1-1-ARCH

Aktivierte Erweiterungen:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by phoerious** [comment]
I haven't seen it in this form before, but you may have fallen victim to this age-old Qt bug: https://bugreports.qt.io/browse/QTBUG-53813?attachmentViewMode=list

**Comment by droidmonkey** [comment]
This is definitely not a KeePassXC issue, but a Qt issue.

**Comment by phoerious** [comment]
Multi-Monitor on X is broken by design, bugs like that are not a rare event, unfortunately.
