### ISSUE TITLE
KeePassXC flashes on screen, then disappears when being opened after minimized

### ISSUE THREAD

**Issue by waynebloss** [keepassxreboot/keepassxc#2717]
## Expected Behavior
I expected the KeePassXC window to appear whenever activated.

## Current Behavior
Instead, the window flashes on the screen then disappears no matter how I activate it (by clicking the tray icon or by running `keepassxc` from a keyboard shortcut) if the window had been previously minimized.

## Possible Solution
I don't know. The window almost shows up when I activate it, but it disappears very quickly. Maybe don't programmatically minimize the window within 500ms of the time from when the window was activated?

## Steps to Reproduce
1. Start KeePassXC on Manjaro/Arch Linux with XFCE with the following settings: Start only a single instance. Show a system tray icon. Hide to tray when minimized. Hide to tray instead of exit.
2. Activate the window, then minimize it.
3. Activate the window again from the tray icon or by running `keepassxc` from a global keyboard shortcut.
4. Observe that the window flashes on the screen briefly, then disappears.

## Context
I'm not ever sure when I'll be able to activate KeePassXC with just one press of my keyboard shortcut or two. It's very annoying.

## Debug Info
KeePassXC - Version 2.3.4
Revision: 6fe821c

Libraries:
- Qt 5.12.0
- libgcrypt 1.8.4

Operating system: Manjaro Linux
CPU architecture: x86_64
Kernel: linux 4.19.20-1-MANJARO

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by droidmonkey** [comment]
I cannot replicate this under Ubuntu 18.04 running XFCE

**Comment by waynebloss** [comment]
I can reproduce it every time on any Manjaro workstation.

Is there some logging I can turn on to show more information?

If not, I suppose I can try running it in development to see what's going on. Haven't done C++ in a while though.

Thanks!

**Comment by s-h-a-d-o-w** [comment]
This just was a problem for me on Mint 20.2 Cinnamon.

Fixed it by changing `MinimizeOnStartup` to `false` in `~/config/keepassxc/keepassxc.ini`.

In lieu of a proper fix, it might be worth considering simply not offering this option on Linux?
(Although I'd like to note that once the app was started, minimizing to tray and opening it again works perfectly fine. So it seems like really just minimizing on startup breaks things.)
