### ISSUE TITLE
Minimize again after autotype

### ISSUE THREAD

**Issue by Joachim-42he** [keepassxreboot/keepassxc#2719]
## Summary
Keepassxc should be able to minimize again after an autotype if it was minimized before.

## Desired Behavior
If Keepassxc is minimized and the feature "always ask before autotype" (re-translated from German gui) is selected, the main window will pop-up if I activate autotype but will not minimize again. It should minimize after the autotype completes.

## Context
For me this is an integral part of the workflow. Keepassxc is a password database and should on ly be visible on the desktop when I am using it.

**Comment by droidmonkey** [comment]
Please post your debug information. What OS are you on? What version are you using?

If you are on MacOS, this has been fixed in 2.4.0

**Comment by gmk57** [comment]
Hello! I'm using KeePassXC 2.4.1 on macOS Sierra (10.12) and have this issue too.

**Comment by Joachim-42he** [comment]
KeePassXC - Version 2.4.1
Revision: 7bafe65

Qt 5.12.2
Debugging mode is disabled.

Operating system: macOS Mojave (10.14)
CPU architecture: x86_64
Kernel: darwin 18.5.0

Enabled extensions:
- Auto-Type
- Browser-Integration
- SSH-Agent
- KeeShare (only unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
 libgcrypt 1.8.4

**Comment by gmk57** [comment]
Interestingly, in my case it does minimize after pressing "Rerform Auto-Type" toolbar button or context menu, but does not minimize if I use Global Auto-Type shortcut.

**Comment by Joachim-42he** [comment]
This issue is still marked as "more info needed". What info that I couls supply, is still missing?

**Comment by droidmonkey** [comment]
OK I can reproduce your issue, thank you!

**Comment by baszoetekouw** [comment]
I'm also experiencing this issue.  Is there anything I can do to help debug this?

**Comment by droidmonkey** [comment]
A code fix and PR would be most helpful at this point in time
