### ISSUE TITLE
`timerfd` file descriptors leak

### ISSUE THREAD

**Issue by johanfleury** [keepassxreboot/keepassxc#2721]
From time to time, when I try to open my database, KeepassXC throws a "Too many
open files" error after entering my password and I'm not able to open the
database.

It seems that this is caused by a timerfd leak (see lsof output below).

## Steps to Reproduce

1. Open KeepassXC
2. Unlock you database and lock it back
3. Repeat the previous operation a large number of times (around 700 times?)
4. Observe (`lsof -p <KeepassXC PID>`) that a new file descriptor is opened on `timerfd` each time the database is locked
5. At some point KeepassXC will throw a "Too many open files" error

## Context

I'm pasting the Debug information of the last time it happened but I faced this
issue on Debian Sid (unstable) as well as Ubuntu 18.04 (bionic).

## Debug Info

KeePassXC - Version 2.3.1
Revision: 2fcaeea

Libraries:
- Qt 5.9.5
- libgcrypt 1.8.1

Operating system: Ubuntu 18.04.2 LTS
CPU architecture: x86_64
Kernel: linux 4.15.0-45-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

### `lsof` output

See [strace-output.txt](https://github.com/keepassxreboot/keepassxc/files/2890673/strace-output.txt).

### `ulimit` output

```
$ ulimit -Sn
1024
$ ulimit -Hn
1048576
```

### `pstree` output

```
$ pstree -splAac 8490
systemd,1 --system --deserialize 18
  `-keepassxc,8490
      |-{keepassxc},8492
      |-{keepassxc},8494
      |-{keepassxc},8495
      |-{keepassxc},8496
      |-{keepassxc},8501
      `-{keepassxc},8505
```

**Comment by droidmonkey** [comment]
I am not an expert in this arena, but it looks like we do not call ::close(fd) in the first return from:

https://github.com/keepassxreboot/keepassxc/blob/fa459b0d1e3f1576e7a31401100f440d03981985/src/browser/NativeMessagingBase.cpp#L77-L96

This function is called whenever the application receives a message from the browser proxy. So if this condition hits you will end up with a dangling file descriptor. This is the only place in the code (based on a quick review) where we continually create fd's.

**Comment by droidmonkey** [comment]
Related to #2643

**Comment by johanfleury** [comment]
I'm sorry, I couldn't find this issue before posting.

Regarding your comment, not sure if that helps but both the new and legacy browser integration are disabled (and were never enabled).

**Comment by johanfleury** [comment]
Ok so I `starce`d the keepassxc process and a call to `timerfd_create` is made every time the database is locked (either manually or automatically).

**Comment by droidmonkey** [comment]
That version of libykpers is pretty old. Can you try updating it?

https://github.com/Yubico/yubikey-personalization/releases

The function called (ykds_touch_level) is not called from KeePassXC and also does not call any libusb functions.

Are you even using a Yubikey with your database? Is the "press to activate" enabled on it?

**Comment by johanfleury** [comment]
> That version of libykpers is pretty old. Can you try updating it?

I'm using version [1.18.0 on Ubuntu bionic](https://packages.ubuntu.com/bionic/libykpers-1-1) and [version 1.19.0 on Debian sid](https://packages.debian.org/sid/libykpers-1-1). I'm facing the issue on both.

> Are you even using a Yubikey with your database? Is the "press to activate" enabled on it?

I'm not using a Yubikey with KeepassXC and the issue appears whether a Yubikey is connected or not.

**Comment by johanfleury** [comment]
I added a call to `YubiKey::deinit` in `YubiKey::detect` and it seems to work:

```cpp
diff --git a/src/keys/drivers/YubiKey.cpp b/src/keys/drivers/YubiKey.cpp
index 4b98a6e4..64fec475 100644
--- a/src/keys/drivers/YubiKey.cpp
+++ b/src/keys/drivers/YubiKey.cpp
@@ -136,6 +136,7 @@ void YubiKey::detect()
             // Wait between slots to let the yubikey settle
             Tools::sleep(150);
         }
+        deinit();
     }
 
     if (!found) {
```

Should I make a PR with that?

**Comment by droidmonkey** [comment]
Actually, we should call yk_release() here: https://github.com/keepassxreboot/keepassxc/blob/fa459b0d1e3f1576e7a31401100f440d03981985/src/keys/drivers/YubiKey.cpp#L72-L75

It seems that libusb-1.0 code in the yubikey library does a lot of cleanup whereas newer versions of libusb must cleanup themselves.

New: https://github.com/Yubico/yubikey-personalization/blob/29dafc4d211856da0b48d6269e8017e2493c6a11/ykcore/ykcore_libusb.c#L146-L149

Old: https://github.com/Yubico/yubikey-personalization/blob/29dafc4d211856da0b48d6269e8017e2493c6a11/ykcore/ykcore_libusb-1.0.c#L152-L162

**Comment by johanfleury** [comment]
Adding `yk_release` here seems to work:

```
diff --git a/src/keys/drivers/YubiKey.cpp b/src/keys/drivers/YubiKey.cpp                                                                                                                                           
index 884be354..32241dbb 100644
--- a/src/keys/drivers/YubiKey.cpp
+++ b/src/keys/drivers/YubiKey.cpp
@@ -77,6 +77,7 @@ bool YubiKey::init()
     // TODO: handle multiple attached hardware devices
     m_yk_void = static_cast<void*>(yk_open_first_key());
     if (m_yk == nullptr) {
+        yk_release();
         m_mutex.unlock();
         return false;
     }
```

Thanks for pointing this out to me.

Regarding `libusb`, I don't get your comment and I don't know the difference between the two files.

**Comment by droidmonkey** [comment]
I was shooting in the dark on libusb, but there is a stark difference between the two libusb files.

**Comment by johanfleury** [comment]
It should be fixed now :)
