### ISSUE TITLE
Not able to type in password field when restoring KeepassXC from tray

### ISSUE THREAD

**Issue by sebast889** [keepassxreboot/keepassxc#2727]
I am not able to type into the password field when restoring KeepassXC from tray. Usually I open KeepassXC use it for a while then it auto locks and is minimized to system tray. After some time usually few hours when I click tray icon to reopen from tray and try to unlock the database again many times it won't allow me to type in password (no characters get typed) or I have to press a random button multiple times until I see characters appear in the field. Sometimes characters won't ever appear in the field and I have to close and reopen KeepassXC just to have typing work again to unlock the database. 

It's a bug I've faced for a while now but I don't know what causes it or how to reproduce since it's not every time this happens and about half the time restoring from tray works without issue. Maybe others have also faced this issue.

KeepassXC 2.3.4
Windows 10

**Comment by droidmonkey** [comment]
Hm, I use win10 and tray kpxc all the time
 I have never experienced this before. Perhaps it will disappear when you upgrade to 2.4.0. The final release is likely next week.
