### ISSUE TITLE
Keepassxc doesn't send "ENTER"

### ISSUE THREAD

**Issue by RolfWithUbuntu** [keepassxreboot/keepassxc#2735]
The old version of Keepass(XC) was sending the following sequence to the internet site: 
{USERNAME}{TAB}{PASSWORD}{ENTER}.
Now, with the new browser integration the sending of {ENTER} is omitted, so one has to hit the Enter button with the mouse separately. That is very uncomfortable.
How can I set the automatic transmission of the enter key?

**Comment by droidmonkey** [comment]
The browser integration has nothing to do with autotype, which is what uses the {ENTER} sequence.
