### ISSUE TITLE
Flatpaked KeePassXC doesn't add SSH key to agent.

### ISSUE THREAD

**Issue by kaymio** [keepassxreboot/keepassxc#2736]
## Expected Behavior:
Follow this little [tutorial](https://blog.valouille.fr/post/2018-03-27-how-to-use-keepass-xc-with-ssh-agent/) to add a SSH key to the agent when "Add to agent" is clicked and the "apply" button has been hit, a green bar says something like "Entry successfully updated". The name of the key in the 'keybox' is updated with the name corresponding with the name in the file. Confirm that the key has been added with 
`ssh-add -l`
## Current Behavior
Repeat the same procedure and hit "apply", watch the green banner. After another click the banner vanishes and the name changes back to 'id_ed25519' where the real name should be printed. When checking the SSH agent it says that there are no keys in the list.

## Possible Solution
Supposedly the flatpak version is not able to make contact with the SSH agent.

## Context
Usually keychain is used by me to add keys but its quite annoying. As I've switched to KeePassXC for all my other passwords, I also wanted to use it for my SSH keys.  

## Debug

KeePassXC - Version 2.3.4
Revision: 6fe821c
Distribution: Flatpak

Librarys:
- Qt 5.12.1
- libgcrypt 1.8.4

OS: Linux 4.20.11-zen2-1-zen
CPU-Architecture: x86_64
Kernel: linux 4.20.11-zen2-1-zen

Activated extensions:
- Auto-Type
- Browser Integration
- SSH Agent

**Comment by droidmonkey** [comment]
Please report your issue over in the Flatpak repository: https://github.com/flathub/org.keepassxc.KeePassXC
