### ISSUE TITLE
Key file remembered after close

### ISSUE THREAD

**Issue by CISMaleScumLord** [keepassxreboot/keepassxc#2743]
## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

keepassxc version 2.3.4

When using a key file to access my passwords, keepassxc should forget about the key file once it has been closed.

## Current Behavior
[NOTE]: # ( Tell us what actually happens )

keepassxc pre-populates the key file on the unlock screen.

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )

key file should be treated the same as the password and be forgotten when screen is locked or program closed.

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1. Open keepassxc
2. Select correct key file, enter correct password and open database
3. Close keepassxc
4. Open keepassxc and see that the key file is remembered.

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )

This is insecure
## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION
Revision: REVISION

Libraries:
- LIBS

Operating system: OS
CPU architecture: ARCH
Kernel: KERNEL

Enabled extensions:
- EXTENSIONS

**Comment by phoerious** [comment]
That's a convenience feature. You can turn it off in the settings.

**Comment by CISMaleScumLord** [comment]
Honestly, I did look through the settings and it wasn't there before I posted this! It's still a bug though, it should be off by default.

**Comment by phoerious** [comment]
It certainly was there.I disagree that it should be turned off by default. Selecting the location of the key file every time is too cumbersome, so users would rather not use one. Key files tend to be quite easy to spot anyway, so you gain no protection from it, unless you use a JPEG or ZIP file etc., but then you can also simply turn this setting off.
