### ISSUE TITLE
Cloud integration with master keepass file

### ISSUE THREAD

**Issue by natemo4873** [keepassxreboot/keepassxc#2744]
[TIP]:  # ( Provide a general summary of the feature in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Summary
keepass2android has a feature where you can update a master key file database from any cloud based server. (google drive, dropbox etc.) Is there any way to implement such a feature with your application? Also, there is a quick unlock feature as shown in the screenshot I have attached.

## Desired Behavior
The ability to read and update any data on the fly through cloud based storage of master key file database. Also, quick unlock feature to quickly access password database if a user should decide that such a feature is safe for use. (both feature requests off by default to prevent security risks)

## Possible Solution
[NOTE]: # ( Not required, but suggest ideas on how to implement the addition or change )

## Context
These features are huge in my opinion. I am always checking my passwords for many different sites from multiple hardware configurations. As of right now, the easiest solution is to log into my droid phone and update passwords to my main database file located on google drive. Any changes made to the data base file located on google drive must be downloaded onto my mac in order to have the most recent passwords. The app I posted in the screen shot makes management of passwords soooo easy. Also the quick unlock feature within the android app also makes frequent access to the database file a breeze. I feel like i have found the best android app for keepass files, now I only wish I had a desktop variant for mac os that could do the same. By the way, I love keepassxc! It has been the best version I have found to date to manage keepass files.

<img width="710" alt="screen shot 2019-02-26 at 8 12 55 am" src="https://user-images.githubusercontent.com/48023049/53424118-d6edc200-399f-11e9-826c-336e3defd869.png">

**Comment by droidmonkey** [comment]
I store my database in Google Cloud and I have never had a single problem with it syncing between KeePass2Android and KeePassXC. Quick Unlock is already requested in a separate issue.

**Comment by natemo4873** [comment]
thanks for the swift reply. i was unaware it could be done via the os. interesting

**Comment by natemo4873** [comment]
now to figure that out, lol

**Comment by droidmonkey** [comment]
Which cloud service and OS are you using?

**Comment by natemo4873** [comment]
google drive and mac os 10.14.3

**Comment by natemo4873** [comment]
oh, now i feel dumb, lol
thank you for the insight!

**Comment by droidmonkey** [comment]
No problem!
