### ISSUE TITLE
[PRE-RELEASE] KeePassXC Snapshot (Feb 15) does not support macOS 10.13

### ISSUE THREAD

**Issue by whisdol** [keepassxreboot/keepassxc#2745]
## Expected Behavior
KeePassXC should start on macOS 10.13.

## Current Behavior
The application icon is greyed out and upon start, a popup tells me that KeePassXC required macOS 10.14 or newer.
![grafik](https://user-images.githubusercontent.com/5374166/53434726-84d88b00-39f7-11e9-91d8-45322905f6bf.png)

## Debug Info
KeePassXC - Snapshot from Februar 15th (build-21725)

Operating system: macOS High Sierra (10.13)
CPU-Architektur: x86_64
Kernel: darwin 17.7.0

**Comment by phoerious** [comment]
Unfortunately, both macOS and Qt throw obstacles in our path on that. I believe the incompatibility comes from using Qt >= 5.12, which enables support for Mojave's dark theme or a wrong target platform version. KeePassXC definitely runs on older macOS versions, but the compiled binary does not, unless recompiled on an older macOS. I don't think we can realistically maintain compatibility with 10.10, but 10.13 should still be supported. Need to check what's going on there.

**Comment by droidmonkey** [comment]
I wonder if this has to do with the entitlements added for touchid. I don't think this has anything to do with qt 5.12

**Comment by phoerious** [comment]
Qt 5.12 removed support for some older macOS version, but I think that was 10.11 or 10.12.

**Comment by varjolintu** [comment]
Running the KeePassXC binary from shell inside the .app works, but the dialog looks always unfocused. The only difference I found was looking the binary with `otool -L` and it only shows different current versions for the system frameworks when comparing to a binary that is compiled with High Sierra.

I hope we wouldn't have to compile a separate Mojave version for enabling the dark theme.

**Comment by whisdol** [comment]
2.4.0 stable supports macOS 10.13 again. Thanks!
