### ISSUE TITLE
Windows  - Default Path Options for "Open existing database" 

### ISSUE THREAD

**Issue by iluzek** [keepassxreboot/keepassxc#2750]
[TIP]:  # ( Provide a general summary of the feature in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Summary
KeePassXC offers the option to not remember password database file, however when using that option and selecting "Open existing database" from the main menu, the Open File Dialog window defaults to 'Windows Default location' which appears to be a User folder (%UserProfile%). 

This might not be the desired behaviour.
Simple selection in option could improve quality of life and accessibility for passwords.

[NOTE]: # ( Provide a brief overview of what the new feature is all about )

## Desired Behavior
The new feature should allow the user to specify the default directory that is being opened when searching for a 'database' and subsequently it would keep opening in that location whenever "Open existing database" button is pressed.

## Possible Solution

The new feature would allow the following to be accessed and changed in options:
Select the default opening directory between options:
-Default Windows/OS (This is what happens now)
-KeePassXC directory (This is what I expected to happen)
-CustomPathSpecifiedByUser (This would be an interesting addition and possibly beneficial that could either point into a misleading location or correct one)

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
This would be a huge quality of life improvement in the circumstances where the database is not 'advertised' and is hidden but not so hidden as to have to navigate many directories to get to the password location.

**Comment by phoerious** [comment]
KeePassXC directory only makes sense for a portable version, not if KeePassXC is installed on your system.

**Comment by iluzek** [comment]
> KeePassXC directory only makes sense for a portable version, not if KeePassXC is installed on your system.
I am indeed using a portable version. I assume you would discourage defaulting to the installation path although I am not sure if there would be any specific reason against it - which there very well might be.

**Comment by phoerious** [comment]
The reason against it is that your KDBX file is very likely to be located somewhere in your user folder, but certainly never in the KeePassXC installation folder.

**Comment by droidmonkey** [comment]
It does not make sense to be any other folder than the "Default User Folder" absent any additional information. If you are storing your database on the same thumb drive as the application itself, what value is there in disabling the remember last used databases option??

**Comment by iluzek** [comment]
> It does not make sense to be any other folder than the "Default User Folder" absent any additional information. If you are storing your database on the same thumb drive as the application itself, what value is there in disabling the remember last used databases option??

In my opinion, and I might be wrong, the choice between 'Showing the exact path to database' and 'being stuck with default user profile location' leave quite a few unexplored options as I mentioned before.
Again while I might not have the wholesome grasp on the matter 'hiding' database files as you do, surely creating fake password databases and hiding real password databases among misc files with a change of extension and attributes (date created/modified/accessed) among let's say library files for other software should be considered.

1. The previously mentioned possibility of misdirecting possible attempts at getting passwords also feel legitimate in my opinion, as a potential attacker might be satisfied with the fake location and fake database while ignoring easily accessible and hidden file.
2. On top of that, I could imagine some people having multiple databases that they access and they could be storing them in common directory which is most likely not User Profile location and every time they open it, it would require unnecessary user action.

Currently, even if I do use the option to hide the exact file location, I'd need to proceed on a lengthy process of getting to the said file. 


And while I do agree that this is quite a stretch and most likely not many people use this approach, I feel like option still should be there and the default behaviour of opening UserProfile location is inconvenient.

Again if all of this sounds ridiculous and you can offer me a legitimate and equivalent method of hiding passwords and making them more accessible I am very eager to hear it.

**Comment by droidmonkey** [comment]
Hiding a database file by changing the extension or creating multiple fake databases offers absolutely no protection over just having the database file itself. I could easily find your hidden database file by scanning the first few bytes of each file and comparing them against the KDBX specification. This is also called "security through obscurity" and is ineffective and frowned upon.

Using the default settings when creating a database, it is impossible to brute force a database open given a sufficiently long (>15 characters) password. 

Honestly the option to not remember previous databases is more a courtesy for people who prefer to not leave any traces at all. A middle ground option offers little to no benefit while adding complexity in code and UI.

**Comment by iluzek** [comment]
> Hiding a database file by changing the extension or creating multiple fake databases offers absolutely no protection over just having the database file itself. I could easily find your hidden database file by scanning the first few bytes of each file and comparing them against the KDBX specification. This is also called "security through obscurity" and is ineffective and frowned upon.
> 
> Using the default settings when creating a database, it is impossible to brute force a database open given a sufficiently long (>15 characters) password.
> 
> Honestly the option to not remember previous databases is more courtesy for people who prefer to not leave any traces at all. A middle ground option offers little to no benefit while adding complexity in code and UI.

Thanks for quick reply.  Thank you for elaborating on the idea behind the option to not remember previous databases. Considering your points I do agree that this would probably not be worth development time and increase in code complexity.

Despite the above acknowledgement the process described above which was labelled as 'security through obscurity' would potentially prevent an opportunistic theft which could be quite easy given direct path to the database being displayed. The fact that you can scan the bytes of files and 'easily' find the database does not mean that someone would have the time or even tools on them if an opportunity to steal database occurred (emergency leaving the computer without securing it etc)

Saying all that, I do acknowledge that people who would go to such lengths as to provide fake database (real database with fake passwords) and waste the time of the thief, would most likely like myself use very strong passwords which in turn could make it virtually impossible to brute force (for now) and in theory negate all the risk.

With all that said, I suppose this would be the end of the thread for this request, unless for some reason stance on "security through obscurity" is changed.

Thanks for taking time on this.
