### ISSUE TITLE
No "Use OpenSSH for Windows" checkbox on Windows

### ISSUE THREAD

**Issue by ThinkChaos** [keepassxreboot/keepassxc#2756]
## Expected Behavior
According to #1994, there should be a "Use OpenSSH for Windows instead of Pageant" checkbox in the SSH Agent settings.
I also check the develop branch and confirmed the checkbox still exists.

## Current Behavior
The checkbox is not present.

## Steps to Reproduce
1. Enable Windows 10's "OpenSSH Authentication Agent" (since 1803 "Spring Update")
2. Install the Windows build (tested w/ 2.3.4 and 2.4.0b2)
3. Enable SSH Agent in KeepassXC
4. Restart KeepassXC
5. Go back into the SSH Agent settings

## Debug Info
KeePassXC - Version 2.3.4
Revision: 6fe821c

Libraries:
- Qt 5.11.1
- libgcrypt 1.8.3

Operating system: Windows 10 (10.0)
CPU architecture: x86_64
Kernel: winnt 10.0.17763

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by droidmonkey** [comment]
This is available in 2.4.0, currently in beta2.
