### ISSUE TITLE
Add button to keep database temporarily unlocked

### ISSUE THREAD

**Issue by simgunz** [keepassxreboot/keepassxc#2759]
## Summary
Add a button to keep the database indefinitely unlocked overriding the auto-lock timer.

## Desired Behavior
Clicking the "temporary keep unlocked" button should override the auto-lock timer.

## Context
I set keepassxc to lock the database after 5 minutes of inactivity. Sometime though, I would like to keep the database unlocked for a whole hour because I am configuring a NAS or other things and I need to keep copying passwords maybe every 6-10 minutes, so that I end typing the master password 10 times in an hour.

**Comment by droidmonkey** [comment]
I actually like this idea, although I would call it "extended unlock" and wouldn't go with indefinite.

**Comment by simgunz** [comment]
That is indeed a better.

Two possible implementations:

## 1
- Click the button to add 5 minutes
- Click repeatedly to keep adding 5 minutes
- The button displays the minutes until locking (maybe with the numbers overlaid over the icon)

## 1
- Click the button
- A modal dialog opens to ask to input the number of minutes to keep the db unlocked
- The button displays the minutes until locking

**Comment by droidmonkey** [comment]
If you are continually interacting with KeePassXC every 5 minutes then the database won't lock anyway so option 1 is nullified. Option 2 is better as sort of a "manual override"

**Comment by simgunz** [comment]
What I meant for solution 1 is that you can click multiple times all at once (not every 5 minutes) to reach the amount of time you want instead of having to enter numbers in a modal dialog.

This option is probably quicker than option 2 if you want to keep it unlocked 30-60 minutes. In any case solution 2 is more general and probably better.

**Comment by outdooracorn** [comment]
With option 2 you could just have the input box default to 5/10mins (or another default configurable in the settings?). This would make it quick to add 5/10mins but easily add longer if required.

Option3: A dialog box pops up when the database is about to be locked (30s beforehand? configurable?) with the option to enter an extension similar to what's described for option 2.

**Comment by simgunz** [comment]
I like option 3. I would make it optional given that it is a little invasive, and I would also keep the button as in option 2.

**Comment by droidmonkey** [comment]
This adds complexity for little gain, will not be implementing this.
