### ISSUE TITLE
SSH Agent: Agent protocol error: prompt constraints are not supported

### ISSUE THREAD

**Issue by Jonny007-MKD** [keepassxreboot/keepassxc#2762]
When adding a key I get an Agent protocol error in KeePassXC. Looking into the journal I see the warning "gnome-keyring-daemon[984]: prompt constraints are not supported."

Unfortunately I could not find any information to this warning.

## Debug Info
gnome-keyring 3.20.0
KeePassXC - Version 2.3.4
Revision: 6fe821c

Libraries:
- Qt 5.7.1
- libgcrypt 1.7.6-beta

Operating system: LMDE 3 (cindy)
CPU architecture: x86_64
Kernel: linux 4.9.0-8-amd64

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by droidmonkey** [comment]
See https://bugs.launchpad.net/ubuntu/+source/gnome-keyring/+bug/209447

Looks like gnome keyring does not support constraints such as timeout and such. Uncheck those chrckboxes in the ssh agent settings for that entry

**Comment by Jonny007-MKD** [comment]
Thanks @droidmonkey, it was indeed the confirmation checkbox! I didn't know these are called constraints, so it's alright now.

**Comment by droidmonkey** [comment]
We should gracefully handle this and provide a better warning message. It is hard because every key repository does things differently, but if the key fails and "contrain" is in the error message we should point people to the solution.

**Comment by scollovati** [comment]
This issue seems to be happening also on windows 10.

**Comment by C0ffeeCode** [comment]
Would it be thinkable to give users a global, per-installation choice to ignore those settings, so one can use those on supported environments but ignore them on incompatible ones?
Also, more information would be nice on why there are problems.
