### ISSUE TITLE
KeePassXC Browser 1.3.2 connect button doesn't work.

### ISSUE THREAD

**Issue by blu28** [keepassxreboot/keepassxc#2765]
I just installed KeePassXC 2.3.4 on Windows 7, created a database with one entry, enabled browser support for Firefox. In FireFox I install KeePassXC Browser 1.3.2 from the Mozilla Add-on directory. The icon has a red x and says "timeout or not connected". Pressing settings-> Connected Databases, shows no databases connected, as expected. However, what is unexpected is that pressing the button that says "Connect" produces no effect at all. No dialog to choose a database, not error, no feedback to indicate I pressed except the UI standard color change, but nothing else.

**Comment by droidmonkey** [comment]
Did you restart Firefox after enabling the integration?

**Comment by blu28** [comment]
Yes.

**Comment by varjolintu** [comment]
If you have time, check the [Troubleshooting guide](https://github.com/keepassxreboot/keepassxc-browser/wiki/Troubleshooting-guide).

**Comment by pmury** [comment]
Same issue Ubuntu 18.04 LTS/latest Firefox. 
@varjolintu for some reason, there is no file ```~/.mozilla/native-messaging-hosts```. Can't understand in the Troubleshooting article what to do in this case.

**Comment by varjolintu** [comment]
@pmury And the KeePassXC Browser Integration settings doesn't create it when enabling support for Firefox?

**Comment by 1605200517** [comment]
@varjolintu thank you, now it's working for both browsers Chromium and Firefox on Ubuntu LTS 18.04.3.

Take-aways for others:
* enable **browser integration** in the main tool's settings :-)
* you have to **restart** browser - otherwise the button is not working.

**Comment by varjolintu** [comment]
@1605200517 Please ensure the extension is connected to KeePassXC before using the Connect button. You can check that via the extension icon popup.

We should probably disable the Connect button from the settings page when the extension is not connected.
