### ISSUE TITLE
Gracefully handle known error messages in SSH-Agent

### ISSUE THREAD

**Issue by droidmonkey** [keepassxreboot/keepassxc#2766]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
A helpful error message should be presented when known errors from pageant, gnome-keyring, or ssh-agent are returned. The affected keys / entries should also be easily opened from the error message itself.

## Current Behavior
[NOTE]: # ( Tell us what actually happens )
An often cryptic error message is presented to the user (see #2762 for example)

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )
Perform limited parsing of error strings returned by key storage applications to help assist the user in correcting the issue.

**Comment by hifi** [comment]
AFAIK the protocol has no error strings and the presented error was in the debug output of the agent itself in #2762. That's why it's hard to know *why* something failed, it just does.

https://tools.ietf.org/html/draft-miller-ssh-agent-02#section-4.1

**Comment by hifi** [comment]
Closing as we can't do much without any error messages from the protocol.
