### ISSUE TITLE
Random Password length

### ISSUE THREAD

**Issue by vis15** [keepassxreboot/keepassxc#2767]
## Summary
When generating a password have an option to randomize the password length. 

## Desired Behavior
In the password generating window have the option to make the password length between two values, and/or have a slider for the about to be variable.

## Context
Having the same password length for all passwords is not good for security. Thus have a variable password length would increase security greatly. Thank you.

**Comment by droidmonkey** [comment]
I do not agree that having passwords the same length is not good for security. 15 character passwords are _impossible_ to crack with current supercomputers.

**Comment by phoerious** [comment]
There is no security gain at all. A longer password is always more secure than a shorter password of unknown length and the length of the original password cannot be deduced from its hash value anyways.
