### ISSUE TITLE
KeePassXC 2.4.0beta2 cannot open database with Legacy Key File

### ISSUE THREAD

**Issue by George-Yanev** [keepassxreboot/keepassxc#2770]
Trying to open Database protected with Legacy Key File and password, generated following error message:
```
Unable to open the database:
Error while reading the database: Wrong key or database file is corrupt.
```
This is happening with the latest beta: 2.4.0beta2. It's working if using version 2.3.4. Tested on Window 10.

## Expected Behavior
To open the Database

## Current Behavior
```
Unable to open the database:
Error while reading the database: Wrong key or database file is corrupt.
```

## Possible Solution
Restore the previous behavior or Print that Legacy Key File are not supported.

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1. Install from Release KeePassXC 2.4.0beta2
2. Type your password and select your Key File
3. Click Open

## Debug Info
KeePassXC - Version 2.4.0-beta2
Build Type: PreRelease
Revision: 9bc20f0

Libraries:
- Qt 5.12.1
- libgcrypt 1.8.4

Operating system: Windows 10 (10.0)
CPU architecture: x86_64
Kernel: winnt 10.0.17763

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (only unsigned sharing)
- YubiKey

**Comment by droidmonkey** [comment]
What type of legacy key file do you have?

**Comment by droidmonkey** [comment]
I cannot replicate this using a "legacy" key file created using KeePass2. Are you sure both the password and keyfile checkboxes are checked in the unlock dialog?

**Comment by George-Yanev** [comment]
The Legacy Key File is in XML format.

```
<?xml version="1.0" encoding="UTF-8"?><KeyFile><Meta><Version>1.00</Version></Meta><Key><Data></Data></Key></KeyFile>
```

I've double check that both Password and Key File are checked. 

While opening the Database in KeePassXC version 2.3.4, following message is displayed.

```
You are using a legacy key file format which may become unsupported in the future.

Please consider generating a new key file.
```

**Comment by phoerious** [comment]
That's a warning, not an error.

**Comment by George-Yanev** [comment]
Agree, what I meant was that while working on 2.3.4 it's showing this warning message during the opening. 

I've manage to reproduce this behavior with clean Database doing following steps:

1. Create new database from KeePass 2.41 [KeePass](https://keepass.info/download.html). Make sure to create it with master key file in the XML format
2. Try to open it with 2.4.0beta2 **doesn't work**

It works with KeePass 2.41 and KeePassXC 2.3.4

**Comment by droidmonkey** [comment]
Like I said, I did just that and it works great

**Comment by George-Yanev** [comment]
Sorry for missing that piece of information.

I've created new Database with **new** Key file and there's no issue as you found out. It only happen if I use that specific Key file. It's line endings were Unix not Windows but changing them didn't help. Diff it with new Key file show the only difference to be in the Data field as expected.

Creating new Database from KeePassXC 2.4.0beta2 with that specific Key is working as well. Not sure what to test else.

**Comment by droidmonkey** [comment]
Strongly recommend you just upgrade your keyfile to a non-legacy version.

**Comment by francoism90** [comment]
Just to inform this happens on the 2.4.0 when not having a password and only using a key file.
In previous releases the password field would be kept unchecked. This time I need to manually deselect password on every start-up.

Is this the correct behavior? :)

**Comment by droidmonkey** [comment]
It was a change made to 2.4.0. After allowing passwordless databases we realize it was not a good change. Will be corrected in 2.4.1.

**Comment by francoism90** [comment]
@droidmonkey Thanks! Keep up the good work.

**Comment by herbdool** [comment]
I can confirm the issue @George-Yanev has. Database opens in 2.3.4 but not in 2.4.0, using a legacy key in both cases. When I generate a new key it opens in both.

**Comment by droidmonkey** [comment]
Closing in favor of #2863
