### ISSUE TITLE
[PRE-RELEASE] The about dialog can be resized and maximized

### ISSUE THREAD

**Issue by vsvyatski** [keepassxreboot/keepassxc#2771]
## Expected Behavior
Normally, the about dialog in the majority of computer programs is not resizable or maximizable. So, unless it is intended otherwise (I suspect it's just an overlook), I think KeePassXC should follow that pattern.

## Current Behavior
The about dialog of KeePassXC can be resized and maximized.

## Possible Solution
One just need to set `layoutSizeConstraint` to `SetFixedSize` in the Qt Designer. Also for Windows it's preferable to set the following hint `Qt::MSWindowsFixedSizeDialogHint)`. I could fix it myself and create a pull request for the release/2.4.0 branch (because this doesn't take much time), but I'm not sure whether the mentioned behavior is intended or not. 

## Steps to Reproduce
1. Choose _Help > About_ menu item.
2. Attempt to resize the about dialog: you will succeed. Also the dialog's title bar has "maximize" button on it which can maximize the window.

## Screenshot
![keepassxc-about](https://user-images.githubusercontent.com/11542782/53981274-3fb50700-4123-11e9-8cb5-f31019119689.png)

## Debug Info
KeePassXC - Version 2.4.0-snapshot
Build Type: Snapshot
Revision: 010d44e

Libraries:
- Qt 5.12.1
- libgcrypt 1.8.4

Operating system: Manjaro Linux
CPU architecture: x86_64
Kernel: linux 4.19.24-1-MANJARO

Enabled extensions:
- Auto-Type

**Comment by droidmonkey** [comment]
This is by design and not a bug.
