### ISSUE TITLE
Automatic password changes

### ISSUE THREAD

**Issue by janlimpens** [keepassxreboot/keepassxc#2772]
In my eyes, one of the greatest vulnerabilities of any password manager is, that the password file could be captured during synchronization between devices and the attacker then has all the time in the world to decrypt it. Not yet known vulnerabilities could come into play, passwords and key files could be captured, ... Even if that takes a lot of time, it is likely that most of the contained passwords have not changed.
The recoverable file is always a liability and I do not think this is ever going to change.

This is why I think its contents need to change on a regular basis, in an automated manner. So that, even if the file is captured and after some time, decrypted its contents have already become worthless.

So this is, what I would propose:
Every key should have another URL "password manager URL", that assumes a RESTFUL service that would enable kpxc to change a password. Kpxc would authenticate with user and password and then provide a new auto generated password and, on success, change the key in its database.

Even if such a URL does not exist almost anywhere, it would be simple to implement and its usage by kpxc would make such a demand more visible.

Issue "Change-password well-known URL" #2495 is similar, but this approach is more password manager centric, automated and generic. So I don't think this is a duplicate.

**Comment by phoerious** [comment]
The password file is encrypted with AES256. Unless you manage to break AES (extremely unlikely) or guess the password (just use a strong password), there is nothing you can do with the file as an attacker. Password manager do not keep your passwords safe by hiding the password file. They do it by means of encryption.

I also do not understand what your concept of this REST API is. Passwords belong to services. Unless you change it there, changing it somewhere in KeePassXC is in no way helpful and maintaining a service that changes passwords for you is entirely impractical and a huge attack vector of its own.

**Comment by droidmonkey** [comment]
So, if I have your database what is preventing me from just not connecting to the internet when I view it?

**Comment by janlimpens** [comment]
There are numerous ways to get to user's passwords other than cracking AES. Any stupid troian that installs a key logger can do this. I do not know where you read something about hiding password files, though.

It is obvious that the API belongs to the service, what I was suggesting was a way for KeypassXC to access such an API. Kp has all the necessary data to do this, so it would be the perfect client for such an operation.

But ok, case's closed.

**Comment by droidmonkey** [comment]
What API are you referring to? There is absolutely no single API that is common across websites for you to remotely change your password. A key logger on your computer is an entirely different attack than stealing your database file (your example).

**Comment by phoerious** [comment]
If you can snoop on the user's master password, you can also steal their password database.
