### ISSUE TITLE
[PRE-RELEASE] Opening database via dbus doesn't unlock already open DB

### ISSUE THREAD

**Issue by dakra** [keepassxreboot/keepassxc#2773]
I autostart my keepassxc instance minimized and on the released
version I can unlock the DB with dbus:
`qdbus org.keepassxc.KeePassXC.MainWindow /keepassxc
org.keepassxc.KeePassXC.MainWindow.openDatabase /path/to/database.kdbx passwd` 

And the if `database.kdbx` file is the same as already open but
locked DB in keepass it get's unlocked just like entering the
password in the main window.

On the master branch another tab is opened with the same DB.
It also doesn't activate my ssh key and in the tray icon
it still shows keepassxc as locked even though it isn't.

## Debug Info
KeePassXC - Version 2.4.0-snapshot
Build Type: Snapshot
Revision: 010d44e

Libraries:
- Qt 5.12.1
- libgcrypt 1.8.4

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 5.0.0-arch1-1-ARCH

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (only unsigned sharing)
- YubiKey

**Comment by droidmonkey** [comment]
Is the real problem that a NEW database tab is opened instead of using the existing database tab?

**Comment by dakra** [comment]
> Is the real problem that a NEW database tab is opened instead of
> using the existing database tab?\

I first that's the main problem but then I unchecked
"Load previous databases on startup" and
now after opening the file with dbus there's, of course,
only one DB open but in the tray, the icon is still
shown as locked even though the DB is unlocked
and my ssh agent also doesn't work.

It works well and as expected in the release version
of keepassxc.

**Comment by dakra** [comment]
https://github.com/keepassxreboot/keepassxc/issues/2828 was exactly my bug (just using command line instead of dbus) so https://github.com/keepassxreboot/keepassxc/pull/2830 fixed this issue too. :+1:
