### ISSUE TITLE
accounts.firefox.com Not working

### ISSUE THREAD

**Issue by noMICROSOFTbuhtz** [keepassxreboot/keepassxc#2777]
I have problems using the "KeePassXC-Browser" Firefox-AddOn (Debian unstable) on the **Firefox Accounts** login.

This is my login url.
https://accounts.firefox.com/oauth/signin?action=signin&scope=profile&state=c356a008d329bde8b4c78fa5c35531eccca40bfd50bc533c0014b9d660d74a6c%3AL2RlL3RodW5kZXJiaXJkLw&redirect_url=https%3A%2F%2Faddons.thunderbird.net%2Fapi%2Fv3%2Faccounts%2Fauthenticate%2F&client_id=25691f3bf98f8ea8

But KeePassXC doesn't recognize the fields. It also is not able to "redetect login fields" and to "manually choose login fields".

Does it depend on the website?

**Comment by droidmonkey** [comment]
Mozilla has blocked extensions on their webpages.
