### ISSUE TITLE
touch screen use causes application hang

### ISSUE THREAD

**Issue by Richard-Payne** [keepassxreboot/keepassxc#2778]
## Expected Behavior
Using a touch screen should behave similarly to using a mouse.

## Current Behavior
touching on the app causes the app to become unresponsive requiring it be killed

## Debug Info
KeePassXC - Version 2.3.4
Revision: 6fe821c
Distribution: AppImage

Libraries:
- Qt 5.9.4
- libgcrypt 1.8.1

Operating system: Ubuntu 16.04.6 LTS
CPU architecture: x86_64
Kernel: linux 4.4.0-142-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by droidmonkey** [comment]
This happens no matter where you touch?

**Comment by droidmonkey** [comment]
I cannot replicate this on Windows 10, it must be an issue with Ubuntu. I am guessing it is a bad interaction with Qt 5.9.

**Comment by Richard-Payne** [comment]
Is the Qt version a system thing or is it built into the application?  I am coming from Enpass and I know Enpass is a Qt app and has no such issues.

Done a bit more testing.  The unlock screen seems to be completely unaffected.  The main screen seems to be affected randomly.  The View/Edit Entry screen is also random but seems to be affected much more often.

I've downloaded the source and built the app.  If you can provide some guidance on debugging this, I'm happy to help.  I have little experience with c++ though.  More c# myself.

**Comment by droidmonkey** [comment]
Did you do your testing on the built app or the app image? You can also download the latest 2.4.0 beta 2 appimage which has a more up to date Qt

**Comment by Richard-Payne** [comment]
I tested on the appimage.  I only downloaded and build the code because I was curious to see how hard it would be to do fixes or improvements.

Just tested 2.4.0 and it seems a lot more stable.  I didn't manage to replicate the fault.  You're also fixed the HiDPI scaling!  

What's the time table for this release coming out of beta?

**Comment by droidmonkey** [comment]
This week

**Comment by Richard-Payne** [comment]
Cool.  Attach this bug to the release and consider it fixed.
