### ISSUE TITLE
Database has null bytes after setting up chrome integration

### ISSUE THREAD

**Issue by marcelbraun1985** [keepassxreboot/keepassxc#2780]
Hi,

My database has null bytes after first use with google drive. I was able to reproduce it. Here are the steps:

1. I use google-drive-ocamlfuse to mount the drive
2. open the database from google drive
3. i connected google chrome to keepass
4. close the database and now the database has null bytes.
5. it's not possible to open the database again.

Because of this behavoir i have to remove KeepassXC. Hope you fix it soon. I like it!

Thansk
Keepass

**Comment by droidmonkey** [comment]
Is the crux of the issue google-drive-ocamlfuse? Seems like the chrome integration is a red herring in this instance. Please perform more testing of the circumstances. Obviously this is not a widespread issue or we would be having a serious amount of complaints.

Also, please include all your debug information.

**Comment by droidmonkey** [comment]
Any status?
