### ISSUE TITLE
KeepassXC: Prove the authenticity of the downloaded file

### ISSUE THREAD

**Issue by novicegit1** [keepassxreboot/keepassxc#2783]
I'm brand new to coding terminology and technical data lingo - apologies in advance for any misunderstandings!

I researched password encryption applications on Reddit and decided I'd like to use KeepassXC to store all my online passwords.  

I wanted to verify the signature of the downloaded file as per KeepassXC website:
"By verifying the signatures of KeePassXC releases, you can prove the authenticity and integrity of the downloaded file. This guarantees that the file you just downloaded was originally created by the KeePassXC Team and that its contents haven't been tampered with on the way."

I tried to follow the [instructions](https://keepassxc.org/verifying-signatures/)

"The *.DIGEST file can be used to check your package downloaded correctly, with the following command:"

$ shasum -a 256 -c KeePassXC-*-x86_64.AppImage.DIGEST
KeePassXC-*-x86_64.AppImage: OK

I changed the Terminal directory to the download drive (where the file is located) and entered the above command, but it just says command not found.

What is happening here?  

If it's relevant, I'm using Macbook Pro Retina 2012, Mojave 10.4.2

Thank you in advance

**Comment by droidmonkey** [comment]
You need to have shasum installed on your computer. You will need to use Homebrew to get it. Please google that solution.

**Comment by novicegit1** [comment]
Thanks a million for this. I installed homebrew, then attempted to install shasum, but I saw a caveat, and then found a step to enter a script: [https://brewinstall.org/Install-md5sha1sum-on-Mac-with-Brew/](url) 

Then I reinstalled shasum:

==> Pouring md5sha1sum-0.9.5.mojave.bottle.2.tar.gz
🍺  /usr/local/Cellar/md5sha1sum/0.9.5: 8 files, 41.9KB
==> `brew cleanup` has not been run in 30 days, running now...
Pruned 0 symbolic links and 2 directories from /usr/local
==> Caveats
==> openssl
A CA file has been bootstrapped using certificates from the SystemRoots
keychain. To add additional certificates (e.g. the certificates added in
the System keychain), place .pem files in
  /usr/local/etc/openssl/certs

and run
  /usr/local/opt/openssl/bin/c_rehash

openssl is keg-only, which means it was not symlinked into /usr/local,
because Apple has deprecated use of OpenSSL in favor of its own TLS and crypto libraries.

If you need to have openssl first in your PATH run:
  echo 'export PATH="/usr/local/opt/openssl/bin:$PATH"' >> ~/.bash_profile

For compilers to find openssl you may need to set:
  export LDFLAGS="-L/usr/local/opt/openssl/lib"
  export CPPFLAGS="-I/usr/local/opt/openssl/include"

$ ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" < /dev/null 2> /dev/null
==> This script will install:
/usr/local/bin/brew
/usr/local/share/doc/homebrew
/usr/local/share/man/man1/brew.1
/usr/local/share/zsh/site-functions/_brew
/usr/local/etc/bash_completion.d/brew
/usr/local/Homebrew
==> Downloading and installing Homebrew...
HEAD is now at 0f07fe5c5 Merge pull request #5861 from Homebrew/dependabot/bundler/Library/Homebrew/concurrent-ruby-1.1.5
Already up-to-date.
==> Installation successful!

==> Homebrew has enabled anonymous aggregate formulae and cask analytics.
Read the analytics documentation (and how to opt-out) here:
  https://docs.brew.sh/Analytics

==> Homebrew is run entirely by unpaid volunteers. Please consider donating:
  https://github.com/Homebrew/brew#donations
==> Next steps:
- Run `brew help` to get started
- Further documentation: 
    https://docs.brew.sh

$ brew install md5sha1sum
Warning: md5sha1sum 0.9.5 is already installed and up-to-date
To reinstall 0.9.5, run `brew reinstall md5sha1sum`

$ brew reinstall md5sha1sum
==> Reinstalling md5sha1sum 
==> Downloading https://homebrew.bintray.com/bottles/md5sha1sum-0.9.5.mojave.bot
Already downloaded: /Users/Library/Caches/Homebrew/downloads/e78202d95c04c8671bc30e1f4bb53b5bf29578f5b7792e980334e5c619b0fba2--md5sha1sum-0.9.5.mojave.bottle.2.tar.gz
==> Pouring md5sha1sum-0.9.5.mojave.bottle.2.tar.gz
🍺  /usr/local/Cellar/md5sha1sum/0.9.5: 8 files, 41.9KB

Did this work correctly?  Thank you for your time.

**Comment by droidmonkey** [comment]
Looks installed to me based on 
```
Warning: md5sha1sum 0.9.5 is already installed and up-to-date
```

**Comment by novicegit1** [comment]
Thank you for your input droidmonkey.

I'm getting the same messages as I got in the beginning - command not found and no such file or directory:

$ KeePassXC-*-x86_64.AppImage: OK
-bash: KeePassXC-*-x86_64.AppImage:: command not found
$ shasum -a 256 -c KeePassXC-*-x86_64.AppImage.DIGEST
shasum: KeePassXC-*-x86_64.AppImage.DIGEST: No such file or directory
$  shasum -a 256 -c KeePassXC-*-x86_64.AppImage.DIGEST
shasum: KeePassXC-*-x86_64.AppImage.DIGEST: No such file or directory

I downloaded the two related sidecar files, the *.DIGEST and the *.sig that needed to be downloaded to the same directory in order for verification to succeed.

There doesn't seem to be any more instructions to this on the verifying signatures page on KeepassXC.  

Thanks in advance for your time.

**Comment by droidmonkey** [comment]
Sorry I totally misunderstood your original problem. The issue is the command we gave will absolutely fail on MacOS. You need to do the following:

```
shasum -a 256 -c KeePassXC-2.3.4.dmg.DIGEST

gpg --verify KeePassXC-2.3.4.dmg.sig
```

**Comment by novicegit1** [comment]
Thank you so much for this. I pasted both lines of that command together, and also tried separately (not sure which way is correct - I guessed together!), and I got command not found for the second line I think:

$ shasum -a 256 -c KeePassXC-2.3.4.dmg.DIGEST
KeePassXC-2.3.4.dmg: OK

$ gpg --verify KeePassXC-2.3.4.dmg.sig
-bash: gpg: command not found

$ shasum -a 256 -c KeePassXC-2.3.4.dmg.DIGEST
KeePassXC-2.3.4.dmg: OK
gpg --verify KeePassXC-2.3.4.dmg.sig
-bash: gpg: command not found

**Comment by droidmonkey** [comment]
The top line shows the hash of the file is correct (see "OK"). To run the second command you need to have gpg installed, again please use homebrew for this. You also need to add our public certificate as trusted. Those instructions are on the keepassxc.org website.
