### ISSUE TITLE
PPA builds for Ubuntu 19.04 Disco Dingo

### ISSUE THREAD

**Issue by a-dma** [keepassxreboot/keepassxc#2784]
Ubuntu 19.04 Disco Dingo is going to be released in a little over a month.

It would be nice if you could start building PPA packages for it so that people can start testing.

**Comment by Guite** [comment]
`keepassxc` in version `2.3.4+dfsg.1-1` seems to work fine on disco (tested only briefly yet though).

**Comment by droidmonkey** [comment]
Yah that needs to be updated to 2.4.0. I'll make sure it happens.

**Comment by droidmonkey** [comment]
@a-dma 2.4.0 is now released. Can we get this published into Disco Dingo?

**Comment by a-dma** [comment]
Congrats on the new version.
I'm not involved with Ubuntu so I can't help you with that. Besides, the freeze for Dingo happened a long time ago. I don't know how easy it is to get an updated version in at this point.

You can start building 2.4.0 for 19.04 on your PPA. I guess @phoerious is the one who can help there.

**Comment by phoerious** [comment]
Disco builds are up.
