### ISSUE TITLE
Option to close KeePassXC instead of locking the DB

### ISSUE THREAD

**Issue by jeruyyap** [keepassxreboot/keepassxc#2786]
## Summary
KeePass 2 has an option that when enabled causes the application to close when it would otherwise just lock the DB and the option applies to both the user locking the DB as well as locking by timeout.
It would be nice to have this option in KeePassXC as well.

## Desired Behavior
When the option is enabled, if KeePassXC would lock the DB due to the user locking it or the specified timeout, it would close the application instead.

## Context
This option would be convenient to some users who prefer to have their procedure for using KeePassXC to be as consistent as possible (starting with the application closed every time).

**Comment by droidmonkey** [comment]
I personally do not see the desire or need for this option. It seems like something that could confuse users who accidentally enable it and think the application is crashing.

**Comment by darren-harrison** [comment]
I second this request, and would find it very useful.
In my situation, my shortcut key to open the app doesn't do anything when the app is open but minimised, meaning rather than just hitting my shortcut keys, I have to go hunting for the app with my mouse.

**Comment by pmv800** [comment]
The option to close versus lock is nice for when your KeePass DB is in a shared cloud location like Dropbox.  Then other devices can edit the KeePass DB without worrying about it being locked.

**Comment by droidmonkey** [comment]
We dont lock the database file.

**Comment by droidmonkey** [comment]
Closing this because we are not going to implement this feature.

**Comment by pmv800** [comment]
Ok cool good to know. I guess I never looked for the lock file in my
Dropbox folder to confirm. It must have been from other KeePass products
that locked the database file. Thanks for the help and the great product.
