### ISSUE TITLE
"Automatically save after every change" should be default for new installs

### ISSUE THREAD

**Issue by jsha** [keepassxreboot/keepassxc#279]
Right now, changes are not saved unless the user explicitly saves them. This is dangerous because if the computer crashes or runs out of battery while the user has unsaved changes, the user will lose all their passwords.

## Expected Behavior
For existing installs, behavior should probably not change, so as not to surprise existing users. For new installs, the "Automatically save after every change" option should default to true.

## Current Behavior
"Automatically save after every change" defaults to false.

## Context
I've lost a number of passwords over the years to this problem, and I think it's a common one.

## Your Environment
* KeePassXC version/commit used: 2.1.1

**Comment by TheZ3ro** [comment]
Your call on this @keepassxreboot/core-developers ?

If we can decide shortly, we can include this in 2.2.0

**Comment by droidmonkey** [comment]
I am in favor of turning it on, but it will increase the conflicts with cloud storage solutions which lock files on sync.

**Comment by louib** [comment]
👍 for defaulting to true the autosave option. Maybe we might want to take another look at #197 before 2.2.0 though?

**Comment by phoerious** [comment]
Will be fixed with #1385
