### ISSUE TITLE
Cannot open files through KDE Google Drive

### ISSUE THREAD

**Issue by jyn514** [keepassxreboot/keepassxc#2792]
Opening files through KDE Google Drive integration doesn't work. I think this a KeepassXC problem because opening the same file through `Kate` works fine.

## Expected Behavior
1. Click 'Open existing database'
2. Navigate to 'Network' -> 'Google Drive' -> \<account name\> -> \<password file\>
3. Click 'Open'
4. Password database opens

## Current Behavior
1. Click 'Open existing database'
2. Navigate to 'Network' -> 'Google Drive' -> \<account name> -> \<password file>
3. Click 'Open'
4. Absolutely nothing happens. I get an error in the console saying
 ```
QXcbConnection: XCB error: 3 (BadWindow), sequence: 2523, resource id: 12582998, major code: 40 (TranslateCoords), minor code: 0
```

## Context
Opening the same file with 'Open With KeepassXC' in `dolphin` works fine without an error.

## Debug Info
KeePassXC - Version 2.3.1
Revision: 2fcaeea

Libraries:
- Qt 5.9.5
- libgcrypt 1.8.1

Operating system: Ubuntu 18.04.2 LTS
CPU architecture: x86_64
Kernel: linux 4.15.0-45-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by droidmonkey** [comment]
Seems like a Qt bug

**Comment by jyn514** [comment]
The appimage version does not have an option for `Network` at all.

**Comment by jyn514** [comment]
The problem is also present on the latest revision:

KeePassXC - Version 2.4.0-snapshot
Build Type: Snapshot
Revision: 0f1be60

**Comment by jyn514** [comment]
I think you're right this is a QT issue, I ran this with gdb and the last function called by keepassxc is https://github.com/keepassxreboot/keepassxc/blob/develop/src/gui/FileDialog.cpp#L40

**Comment by marco-parillo** [comment]
Could this be related to:
https://github.com/keepassxreboot/keepassxc/issues/2796
