### ISSUE TITLE
Minimizes to tray only once on copying to clipboard

### ISSUE THREAD

**Issue by kinoegit** [keepassxreboot/keepassxc#2793]
Thanks for your great work! I love Keepassxc. 
The option "Minimize to tray on copying to clipboard" used to run smoothly. 
I do not know what changed it, but now KpXc window minimizes to tray **only once**! Any further attempt to do either Ctrl+b or Ctrl+c (each with or without following Ctrl+v) leads to copy (and paste) but without the windows minimizing! Very strange.

Operating System: Arch Linux 
KDE Plasma Version: 5.15.3
KDE Frameworks Version: 5.56.0
Qt Version: 5.12.1
Kernel Version: 5.0.2-arch1-1-ARCH
OS Type: 64-bit

**Comment by droidmonkey** [comment]
Did KeePassXC update? You didn't include the version number. If KeePassXC didn't change then it wouldn't be us. It works flawlessly under Windows.

**Comment by kinoegit** [comment]
Oops, keepassxc version 2.3.4-1 
Also tried it with keepassxc-git 2.4.0.beta1.r13.gfa459b0d-1 with the same result

**Comment by kinoegit** [comment]
Unfortunately this issue was not fixed in keepassxc version 2.4.0-1

**Comment by kinoegit** [comment]
Also version 2.4.1-1 did not change behavior. Maybe it's an issue with Plasma, maybe a side effect of a certain config setting. I have no idea because it used to work and i'm not aware of a change that might cause this.

**Comment by droidmonkey** [comment]
Nothing in KeePassXC changed to cause this behavior. I have not seen this on any other platform, including Gnome.

**Comment by kinoegit** [comment]
Nevertheless it's still ongoing. This behavior does interfere even with autofill function in that it stops minimizing the window. So the first formular (user name) field is filled in as it should but to fill in the second (password) the window is remaining literally in the way. Meanwhile autofill keeps going on and one can watch it trying to uselessly fulfill its function.

**Comment by droidmonkey** [comment]
I cannot reproduce this at all.

**Comment by magum** [comment]
I have the same issue on version 2.5.4
In my case minimization became broken after several succesfull usages.
Moreover it became broken for both mimimization options: in tray or not in tray
I'm using KDE as well. And Manjaro (derivative of Arch Linux like issue creator)

 OS: Manjaro 20.0.2 Lysia
 Kernel: x86_64 Linux 5.6.15-1-MANJARO
 Packages: 1469
 Shell: zsh 5.8
 Resolution: 2560x1440
 DE: KDE 5.70.0 / Plasma 5.18.5
 WM: KWin
 GTK Theme: Breeze [GTK2/3]
 Icon Theme: breeze

**Comment by magum** [comment]
@kinoegit If this issue still actual for you, I created AUR package with patch.
https://aur.archlinux.org/packages/keepassxc-kde-fix/
You can try it. It helps for me on Manjaro
As I understand this fix doesn't work properly on another DEs. So it is not for upstream.

**Comment by droidmonkey** [comment]
This would point to an actual bug in your distro's KDE.

**Comment by magum** [comment]
> This would point to an actual bug in your desktop environment (KDE, KWin, etc).

Definitely yes

**Comment by kinoegit** [comment]
@magum thank you for your patch! At last KPxc returns to be the great handy software it used to be for me before that Qt bug got in the way.
