### ISSUE TITLE
KeeShare should respect relative paths

### ISSUE THREAD

**Issue by droidmonkey** [keepassxreboot/keepassxc#2799]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
When a share path is relative (eg. ```../../shared/db.kdbx```) then it should resolve an absolute path from the currently open database's location.

## Current Behavior
[NOTE]: # ( Tell us what actually happens )
Relative paths are not honored and do not work.

**Comment by ckieschnick** [comment]
I suggest to look at #2748 which may provide a more generic way to resolve this problem. To be honest, I'm not sure if it's what I would expect by giving relative paths - most applications use a relative path to the working directory - a path relative to the database location seems not that intuitive to me.

**Comment by droidmonkey** [comment]
It would be consistent with the way auto open is implemented

**Comment by ckieschnick** [comment]
> This is mainly a cross platform issue.

This is only true as long as the user doesn't *share* the source database itself (via dropbox, ... - sure, this may beat the original intention of keeshare, but it seems realistic to me). 
Do you mean the *open last used database(s)* feature on startup as *auto open*? I'm not sure if this is comparable. It seems to me, that this is also some kind of client setting and not shared over instances (part of the local settings?). Or is *auto open* another feature I'm currently not aware of?

**Comment by droidmonkey** [comment]
Auto open is another feature. You create a folder named "AutoOpen" and entries in that folder use their url to point to other database files. These are opened and unlocked when the parent database is unlocked. KeeShare largely obviates this feature.

**Comment by ckieschnick** [comment]
When I understand you correctly, you want to store a path for each platform and this path should be relative to the master database. 

Maybe we need to combine the two approaches - use database relative paths (as default and as symbol) which each KeePassXC client may resolve to a different location. This way, the share definition in the master database can be "interpreted" individually. To resolve the path, we may store the path within the KeePassXC client instance (as already suggested) or we need to put them into a map within the custom data, where each client/os can resolve the path request the path by itself (using some kind of unique id?).

**Comment by droidmonkey** [comment]
A path per platform that is stored in the custom data of the group would be perfectly fine!

**Comment by ckieschnick** [comment]
I've provided a bugfix for this ticket in pr #3029. 

I'll implement the platform switch the path to the share depending on the os as #2748 (but based on this bugfix).
