### ISSUE TITLE
KeePassHTTP: Connecting when database is closed sends a new pair request

### ISSUE THREAD

**Issue by phoerious** [keepassxreboot/keepassxc#28]
When the database is closed, clicking the Connect button in chromelPass results in a new pair request, even though "Request for unlocking the database if it is locked" in KeePassX settings is checked.

**Comment by Manko10** [comment]
I debugged this a little using Wireshark. When clicking on the chromelPass icon in the toolbar, a JSON request is sent:

{"RequestType":"test-associate","TriggerUnlock":false}

which is answered by KeePassX with an error 503 Service Unavailable.

Is there any protocol documentation somewhere? I wonder why chromelPass sends "TriggerUnlock": false. I would expect true there, but there is also no setting to change this behavior.

**Comment by nellistc** [comment]
Seems that for regular use, the original KeePassHttp plugin does not rely on the TriggerUnlock value being true. This appears to be an override for when the option in the plugin to unlock the database is not enabled.
