### ISSUE TITLE
Feature Request: SSH Agent support

### ISSUE THREAD

**Issue by nelsongraca** [keepassxreboot/keepassxc#280]
Support for SSH Agent integration.
Allow to use SSH Keys stored in entries as attachments and load them into a running agent/run its own when a database is opened.

At the moment I use keepass on windows and linux (using wine) and this plugin: http://lechnology.com/software/keeagent/ I would like to be able to switch to keepassxc but I need the agent feature for that.

I would provide help implementing but unfortunately it's outside of my knowledge.

**Comment by nelsongraca** [comment]
Only after creating this I noticed someone already requested the feature, closing it myself.

**Comment by daten-kieker** [comment]
For future reference: See https://github.com/keepassxreboot/keepassxc/issues/278
