### ISSUE TITLE
change shortcut to close windows instead of database on macOS-Version

### ISSUE THREAD

**Issue by sahneschnitte** [keepassxreboot/keepassxc#2800]
hi

i would like to see realized, that i could close the applicationwindow after opening the database  with the shortcut "command+w" instead ( to what it is signed now on macOS-Version ) closing the database.

1. because in general the window isn t needed most of the time.
2. the database itself can close through sleep/countdown/..

Thanks in advance and for the great work !

**Comment by droidmonkey** [comment]
Command+q exits the application. The current before of command+w is standard for tabbed window applications and will not be changed.

**Comment by sahneschnitte** [comment]
i dont  want to close the application- just the window. as the app stays active in the background, indicated through the taskbar symbol. so i just want to get rid of having to close the window ( not the application itself ) with the mouse..

**Comment by droidmonkey** [comment]
When the 2.4.0 MacOS release is ready you can use the CMD+SHIFT+M shortcut to hide to tray
