### ISSUE TITLE
macOS: Opening a database should use ${LastDir} not Finder default

### ISSUE THREAD

**Issue by HUGHUSR** [keepassxreboot/keepassxc#2803]
When opening a database on macOS, KeePassXC should remember the directory where it last opened a database (.ini file LastDir parameter). It does not. Instead, it opens the Finder dialog in Finder's default directory location (in my case, ~).

## Expected Behavior
Open dialog should open in the same directory from which the last database was opened.

## Current Behavior
Open dialog opens in the directory set as Finder's default directory.

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1.
2.
3.

## Context
I have about 2 dozen password databases. Instead of two mouse clicks to select a new database, I now have 7.

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION
Revision: REVISION

Libraries:
- LIBS

Operating system: OS
CPU architecture: ARCH
Kernel: KERNEL

Enabled extensions:
- EXTENSIONS

**Comment by droidmonkey** [comment]
Do you have "Remember Last Databases" enabled? If you do then it will remember the last used directory.

**Comment by HUGHUSR** [comment]
I DO have Remember Last Databases checked.It doesn’t USE the last
remembered directory.
If you look at the INI file, it has the LastDir variable set properly.
However, when I do an “Open Database” it always opens in my home
directory. I see this behavior across all the user accounts I have
defined on my Mac.
I don’t know if it has anything to do with it or not, but my kdbx
files are on a flash drive, mounted as /Volume//KDBX Files/
Here are some relevant settings from the INI file:> 
LastDatabases=/Volume//KDBX Files/aPass.kdbx, /Volume//KDBX
Files/bPass.kdbx
>  LastDir=/Volume//KDBX Files/
>  LastKeyFiles=@Invalid()
>  LastOpenedDatabases=/Volume//KDBX Files/bPass.kdbx
>  MinimizeOnCopy=false
>  OpenPreviousDatabasesOnStartup=true
>  RememberLastDatabases=true
>  RememberLastKeyFiles=false
On Mar 19, 2019, at 09:26 , Jonathan White  wrote:
	Do you have "Remember Last Databases" enabled? If you do then it will
remember the last used directory.

**Comment by droidmonkey** [comment]
Ok maybe this is broken on Mac

**Comment by HUGHUSR** [comment]
This has been fixed, apparently
