### ISSUE TITLE
Repair with 'Challenge Response' does not work

### ISSUE THREAD

**Issue by 2er0** [keepassxreboot/keepassxc#2804]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Expected Behavior
Repair of corrupted database works, also if 'Challenge Response' is used to secure the database.

## Current Behavior
The same message as with unlocking of the database appears. But the repair does not even request the press the button on the security token.
> Unable to open the database.
> Wrong key or database file is corrupt.

## Possible Solution
If 'Challenge Response' is activated the this press should be made and used for the repair of the database.

## Steps to Reproduce
1. Use a Nextcloud instance for syncing the database.
1. Use password and 'Challenge Response' for securing the database
1. Add multiple entries

## Context
I can't no longer access my new added passwords

## Debug Info
KeePassXC - Version 2.3.4
Revision: 6fe821c

Libraries:
- Qt 5.12.1
- libgcrypt 1.8.4

Operating system: Manjaro Linux
CPU architecture: x86_64
Kernel: linux 5.0.1-1-MANJARO

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by phoerious** [comment]
The repair feature really does nothing but fix an ancient KeePassX bug. I think we should remove it altogether, since it's only misleading.

**Comment by droidmonkey** [comment]
The repair feature is already removed in 2.4.0
