### ISSUE TITLE
Release link for v2.4.0 for macOS is not present

### ISSUE THREAD

**Issue by vraravam** [keepassxreboot/keepassxc#2807]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Expected Behavior
In the releases page, I expected to find a link to the download for a dmg file for macOS.

## Current Behavior
Link is not present for v2.4.0

## Possible Solution
Please add the link

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1.
2.
3.

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION
Revision: REVISION

Libraries:
- LIBS

Operating system: OS
CPU architecture: ARCH
Kernel: KERNEL

Enabled extensions:
- EXTENSIONS

**Comment by droidmonkey** [comment]
Need to wait for  @phoerious to sign the dmg

**Comment by vraravam** [comment]
@droidmonkey - any idea when @phoerious might be able to get this done?

**Comment by phoerious** [comment]
Unfortunately, I cannot do it right now, because I'm not at home until Monday, but I'll do it ASAP. Sorry for the mess, communication failure on our / my part.

**Comment by droidmonkey** [comment]
Oopsie, had no idea he was afk

**Comment by affinityv** [comment]
At this point these files are missing from the 2.4.0 release:

KeePassXC-2.4.0-Win32.exe
KeePassXC-2.4.0-Win32.exe.DIGEST
KeePassXC-2.4.0-Win32.exe.sig

KeePassXC-2.4.0-Win64.exe
KeePassXC-2.4.0-Win64.exe.DIGEST
KeePassXC-2.4.0-Win64.exe.sig

KeePassXC-2.4.0.dmg
KeePassXC-2.4.0.dmg.DIGEST
KeePassXC-2.4.0.dmg.sig

Given above posts, the dmg files will hopefully show up on Monday.

How about the exe files, will they be created going forward? Or will we just have the msi ones?

The 2.3.4 release also had zsync files, how about those?
(I don't know how useful they are to anybody)

Do people still require any 32 bit versions at all these days?

**Comment by droidmonkey** [comment]
exe releases have been abandoned from 2.4.0 and onward. We transitioned to WiX fully (ie, MSI).

**Comment by droidmonkey** [comment]
The zsync file is available, it allows for diff updates of appimage (I think??). I never personally used it.

**Comment by milkotodorov** [comment]
It would be nice if one can update the HomeBrew task in parallel with the new version

**Comment by vraravam** [comment]
@milkotodorov - I have a branch for a PR ready - once I get the url and SHA, I can verify and push the PR for the homebrew-cask repo.

**Comment by luixxiul** [comment]
Hi there,

> exe releases have been abandoned from 2.4.0 and onward. We transitioned to WiX fully (ie, MSI).

In my humble opinion, since that kind of change might be critical for some users, it should be noted in a blog post on the official site (which I assume will be published soon like the previous releases).

**Comment by droidmonkey** [comment]
The MSI (WiX) and EXE (NSIS) installers and functionally equivalent to 99% of users. MSI has the added benefit of being VERY easy for system administrator to perform silent installs across the enterprise.

The one caveat is you have to uninstall KeePassXC first to get rid of the exe installer configuration.

**Comment by phoerious** [comment]
The MSI installer also won't trigger as many Antivirus false positives as a self-extracting EXE does. I don't think we have had that problem for while, but in the beginning we had to send a sample for every release to Symantec for whitelisting. Perhaps we are relevant enough these days that they do that on their own now.

**Comment by thaedal** [comment]
I'm using KeePassXC on multiple platforms (Mac,Linux,Win,Android) with a shared file. I have upgraded the app to the new version on Windows machine over the weekend and it ask me to migrate browser settings to new location. This worked fine on Windows, but since I use the same on my Mac now when I try to use it with KeePassXC-Browser it is not configured at all. I had to re-add the browser but also now I have to confirm all the websites I've already remembered to allow to use with KeepassXC.

It would be usefull to have a notice that the once you migrate the browser settings this is not backwards compatible with other versions of KeePass.

**Comment by phoerious** [comment]
KeePassXC 2.4.0 DMS are up.

**Comment by vraravam** [comment]
Both `homebrew-cask` and `homebrew-cask-versions` have been updated to install `keepassxc-2.4.0`

**Comment by tohn** [comment]
Thanks @phoerious for signing! :)

> Need to wait for @phoerious to sign the dmg

I'm a bit concerned though about only one person being able to sign.. Maybe this should be doable (if possible?) by more people?

**Comment by phoerious** [comment]
We are all able to sign with our GPG keys. We also have two Apple IDs, but if droidmonkey signs the package, we will get a lot of reports about Auto-Type being broken, because the signature, although valid, changed.

**Comment by droidmonkey** [comment]
Code signing is in a terrible terrible state at the moment. It is 100% designed for corporation control of a single certificate. Any other model is simply broken, unfortunately.
