### ISSUE TITLE
KeePassXC 2.4.0 AppImage UI huge on Ubuntu 18.10

### ISSUE THREAD

**Issue by bungabunga** [keepassxreboot/keepassxc#2808]
Since updating AppImage to 2.4.0 the UI is huuuge. It take nearly all of the screen.

## Expected Behavior
Normal size (resolution) UI as in 2.3.4

## Current Behavior
Huge UI, problems with resolution.

## Debug Info
[NOTE]: KeePassXC - Version 2.4.0
Revision: c51752d
Distribution: AppImage

Libraries:
- Qt 5.10.1
- libgcrypt 1.8.1

Operating system: Ubuntu 18.10
CPU architecture: x86_64
Kernel: linux 4.18.0-16-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (only unsigned sharing)
- YubiKey
KeePassXC - 2.4.0

Libraries:
- LIBS

Operating system: Ubuntu 18.10
CPU architecture: Intel
Kernel: KERNEL 4.18.0.16.17

Enabled extensions:
- EXTENSIONS Browser extension

**Comment by droidmonkey** [comment]
Screenshot please. Are you running a 4k setup?

**Comment by bungabunga** [comment]
my resolution is 1920x1080. it's a laptop.

![xc](https://user-images.githubusercontent.com/2994878/54680123-51c27c80-4b09-11e9-9a85-5325b684c1a9.png)

**Comment by droidmonkey** [comment]
Are you using Wayland

**Comment by bungabunga** [comment]
i don't know. i use what is default on ubuntu 18.10. the UI looks normal if i use snap version, i don't know for the .deb, because it wasn't upgraded yet.

**Comment by droidmonkey** [comment]
Ok I'll check, this was built and tested on 18.04

**Comment by droidmonkey** [comment]
I cannot replicate on 18.10 running from live cd:

![image](https://user-images.githubusercontent.com/2809491/54688147-76abf500-4af3-11e9-9363-75cc9ad8a974.png)

**Comment by ctonsing** [comment]
Mine is also showing like this on Ubuntu 16.04:
![image](https://user-images.githubusercontent.com/36299292/54691293-45e3b400-4b23-11e9-8656-4a4381133274.png)

**Comment by popxunga** [comment]
Seeing the same with 2.4.0 Keepassxc appimage in RHEL 7.6 with gnome 3.28.3. 
Screen resolution is 1920x1080 (16:9).

![image](https://user-images.githubusercontent.com/37672088/54752334-9e738980-4bd5-11e9-8e04-fb2039dca4b0.png)

![image](https://user-images.githubusercontent.com/37672088/54752356-b21ef000-4bd5-11e9-8cee-fb90facc2019.png)

**Comment by coalwater** [comment]
Confirming the same issue with Archlinux, X11, i3
Wasn't a blocker but I had to downgrade for other reasons.

**Comment by droidmonkey** [comment]
I need more information from all of you.

1. What theme are you using?
2. Do you have qt5ct installed?
3. Do you have your desktop configured to be scaled (ie, 150%)?

**Comment by vanous** [comment]
Same issue here. Desktop is at 100%, no scaling. 

vanous@debthinkpad:~$ uname -a
Linux debthinkpad 5.0.0-trunk-amd64 #1 SMP Debian 5.0.1-1~exp1 (2019-03-12) x86_64 GNU/Linux
vanous@debthinkpad:~$ cat /etc/debian_version 
buster/sid

Theme adwaita

Gnome 3.30.2

**Comment by bungabunga** [comment]
- default theme.
- qt5ct not installed
- desktop not scaled (100%)

**Comment by droidmonkey** [comment]
Also need output of: ```env | grep QT_```

**Comment by bungabunga** [comment]
> QT_ACCESSIBILITY=1
QT_IM_MODULE=ibus

**Comment by popxunga** [comment]
> I need more information from all of you.
> 
>     1. What theme are you using?
> 
>     2. Do you have qt5ct installed?
> 
>     3. Do you have your desktop configured to be scaled (ie, 150%)?

Hi !
1. Adwaita.
2. No.
3. No.
Thanks.

**Comment by popxunga** [comment]
> Also need output of: `env | grep QT_`
QT_GRAPHICSSYSTEM_CHECKED=1
QT_IM_MODULE=xim

**Comment by vanous** [comment]
vanous@debthinkpad:~$ env | grep QT
QT_ACCESSIBILITY=1

setting QT_ACCESSIBILITY=0 didn't help.

**Comment by droidmonkey** [comment]
Interesting enough I installed qt5ct and that application is showing as enlarged whereas KeePassXC snap and appimage show normally. I even tried setting various High DPI settings and platform themes. I cannot get it to look like your screenshots.

Did you all download the fresh AppImage or use zsync?

**Comment by vanous** [comment]
i downloaded AppImage manually from here

https://github.com/keepassxreboot/keepassxc/releases/download/2.4.0/KeePassXC-2.4.0-x86_64.AppImage

**Comment by vanous** [comment]
qt5ct seems ok.., one info message there: 

![Screenshot from 2019-03-21 19-23-57](https://user-images.githubusercontent.com/3680926/54775944-51140e00-4c0f-11e9-803e-7958cfecf3f3.png)

**Comment by popxunga** [comment]
> Interesting enough I installed qt5ct and that application is showing as enlarged whereas KeePassXC snap and appimage show normally. I even tried setting various High DPI settings and platform themes. I cannot get it to look like your screenshots.
> 
> Did you all download the fresh AppImage or use zsync?
I've download it from [here](https://github.com/keepassxreboot/keepassxc/releases/download/2.4.0/KeePassXC-2.4.0-x86_64.AppImage)

> sha256sum KeePassXC-2.4.0-x86_64.AppImage shows:
559be14b9f24feb6bded010aef55dd7cb72b3cb081485c49a548bd614dba4324  KeePassXC-2.4.0-x86_64.AppImage
The checksum matches the published one [here](https://github.com/keepassxreboot/keepassxc/releases/download/2.4.0/KeePassXC-2.4.0-x86_64.AppImage.DIGEST)

**Comment by beanaroo** [comment]
I have the same problem.

- Arch / GNOME 3.32 / Wayland
- 2048 x 1152 / 100%

I installed `qt5-wayland` and all things look good when running:
```
$ QT_QPA_PLATFORM=wayland keepassxc
```

**Comment by coalwater** [comment]
Replying to your questions for my above comment: https://github.com/keepassxreboot/keepassxc/issues/2808#issuecomment-475288372

> 1. What theme are you using?

Apparently `Raleigh [GTK2/3]`

> 2. Do you have qt5ct installed?

No

> 3. Do you have your desktop configured to be scaled (ie, 150%)?

I have these 2 envrionment variables in my `.xinitrc`
```
export GDK_SCALE=2
export QT_SCALE_FACTOR=1.2
```
---
But also keep in mind that this change happens in the same X session if I do the upgrade, so regardless of the scaling, they relatively look different in scale

**Comment by droidmonkey** [comment]
I'm going to rebuild the AppImage and see what happens.

**Comment by phoerious** [comment]
May I express how disappointed I am of the state of HiDPI on the Linux desktop? This is starting to become a never-ending story.

**Comment by affinityv** [comment]
Look at the links from the following comment (and two below), it might help with your problem.
https://github.com/keepassxreboot/keepassxc/issues/2815#issuecomment-475668798

**Comment by bungabunga** [comment]
yes, this works for me!  \o/

but it seems to be a clumsy solution for a program aimed at general audience. can this solution be somehow incorporated into the application? hove come it worked fine until v2.4.0?

**Comment by droidmonkey** [comment]
2.4.0 enabled support for HiDPI.

**Comment by pstorch** [comment]
I got the 2.4.0 update via PPA today. I have two monitors (laptop + external). They have different DPI settings (obviously).

On the Laptopscreen it is too small:
![Screenshot from 2019-03-27 20-54-03](https://user-images.githubusercontent.com/5598124/55108081-17417c80-50d3-11e9-8d73-01b140d42de6.png)

On the external Monitor it is too big:
![Screenshot from 2019-03-27 20-54-24](https://user-images.githubusercontent.com/5598124/55108082-17417c80-50d3-11e9-871a-6414846e7467.png)

The settings in the .profile as menitoned in the linked comment above didn't help.

**Comment by phoerious** [comment]
You need to set it in .xprofile, otherwise your X session won't source it.

**Comment by dupondje** [comment]
I have the same issue, KeepassXC looks way to big for the resolution of my screen.
Running 3840x2160 and 150% scaling on Wayland.

But it seems like Qt just doesn't correctly support fractional scaling:
https://blog.qt.io/blog/2018/12/14/whats-new-wayland-platform-plugin-qt-5-12/

Maybe just disable the HiDPi support when running KeepassXC in Wayland?
Guess nobody on X11 has this issue?

In 2.3 it looked just fine, so won't hurt to drop it again on Wayland as it breaks more then it fixes currently.
Eventually you could add some setting to force disable/enable it.

**Comment by phoerious** [comment]
.desktop files are not created anymore, since desktop integration scripts were deprecated. Use appimaged instead.

**Comment by vanous** [comment]
Until `appimaged` is available in distros, this will be a regression... so i will keep my .desktop and the packaged appimage should ideally too...

```
~$ cat /etc/debian_version 
buster/sid
~$ apt search appimaged
Sorting... Done
Full Text Search... Done
```

**Comment by affinityv** [comment]
Does appimaged rely upon systemd?  I hope not, I have a sans systemd preference for all systems that I manage.

**Comment by plegrand1** [comment]
I had same problem and 
"Exec=env QT_AUTO_SCREEN_SCALE_FACTOR=0 /path/to/KeePassXC-2.4.0-x86_64.AppImage %U"
solved this

**Comment by droidmonkey** [comment]
Yes I closed all of the DPI issues. They are related to our added support of High DPI from Qt which unfortunately carries the baggage of having to setup your DPI environment on some platforms. Qt *should* be doing this automatically, but does not (yet?).

**Comment by krzkrzkrz** [comment]
Just sharing what works for me on Arch Linux with the Keepassxc AUR package installed. At `/usr/share/applications/org.keepassxc.KeePassXC.desktop`, I have:

```
Exec=env QT_SCREEN_SCALE_FACTORS=2 keepassxc %f
```

Hopefully, this helps somebody
