### ISSUE TITLE
KeePassXC 2.40 Wont Run Under Windows XP SP3

### ISSUE THREAD

**Issue by T3rM1nat0Rr** [keepassxreboot/keepassxc#2809]
## Expected Behavior
The program should launch

## Current Behavior
Program does not launch and produces the following error message:
"The procedure entry point RegisterPowerSettingNotification could not be located in the dynamic link library USER32.dll

## Possible Solution
Not applicable

## Steps to Reproduce
1. Install on KeePassXC-2.4.0-Win32.msi on WindowsXP Service Pack 3, or use the Portable version on the same system
2. Run KeePassXC.exe
3. Error message detailed above is displayed

## Context
Can not use the program. (Note: KeePass Password Safe 2 v2.41 itself DOES work on Wndows XP SP3)

## Debug Info
KeePassXC - 2.40
Revision: {44B58856-85E6-4946-ADAF-B5D3D8FF2ACF}

Libraries:
- LIBS

Operating system: Windows XP Service Pack 3
CPU architecture: Intel Core 2 Duo
Kernel: unknown

Enabled extensions:
unknown

**Comment by droidmonkey** [comment]
We do not support windows xp
