### ISSUE TITLE
KeePassXC 2.1.1 wants to install empty directories

### ISSUE THREAD

**Issue by tgurr** [keepassxreboot/keepassxc#281]
## Expected Behavior
Not trying to install empty directories.

## Current Behavior
!!! Attempted to install empty directory '/usr/share/icons/hicolor/16x16/actions'
!!! Attempted to install empty directory '/usr/share/icons/hicolor/22x22/actions'
!!! Attempted to install empty directory '/usr/share/icons/hicolor/22x22/status'

## Possible Solution
Remove the empty directories from the install call.

## Steps to Reproduce (for bugs)
1. Download
2. Build
3. Install

## Context
While packaging KeePassXC for Exherbo Linux I noticed that KeePassXC took that problem over from KeePassX where we already had to remove those emtpy directories to keep them from being installed.

## Your Environment
* KeePassXC version/commit used: 2.1.1
* Qt version (e.g. Qt 5.3): 5.8.0
* Compiler (e.g. Clang++3.6.0): 5.4.0
* Operating System and version: Exherbo Linux

**Comment by tgurr** [comment]
I've applied the patch from https://github.com/keepassxreboot/keepassxc/pull/282 and it works fine for me. Thanks!

**Comment by droidmonkey** [comment]
Resolved in #282
