### ISSUE TITLE
KeePassXC 2.4.0 doesn't compile under Debian Stretch

### ISSUE THREAD

**Issue by kairaven** [keepassxreboot/keepassxc#2811]
All dependencies are installed, used keepassx-2.4.0.tar.gz as source archive.

$ cmake .. -DWITH_TESTS=OFF -DWITH_XC_AUTOTYPE=ON -DWITH_XC_YUBIKEY=ON -DWITH_XC_HTTP=OFF -DWITH_XC_NETWORKING=OFF -DWITH_XC_BROWSER=OFF -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr/local

-- The C compiler identification is GNU 6.3.0
-- The CXX compiler identification is GNU 6.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Git HEAD Revision:
-- Setting up build for KeePassXC v2.4.0-snapshot
-- Performing Test WERROR_C_AVAILABLE
-- Performing Test WERROR_C_AVAILABLE - Success
-- Performing Test WERROR_CXX_AVAILABLE
-- Performing Test WERROR_CXX_AVAILABLE - Success
-- Found LibGPGError: /usr/local/lib/libgpg-error.so
-- Found Gcrypt: /usr/local/lib/libgcrypt.so (Required is at least version "1.7.0")
-- Found Argon2: /usr/lib/x86_64-linux-gnu/libargon2.so
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.8")
-- Found QREncode: /usr/lib/x86_64-linux-gnu/libqrencode.so
-- Found YubiKey: /usr/lib/x86_64-linux-gnu/libyubikey.so;/usr/lib/x86_64-linux-gnu/libykpers-1.so
-- Performing Test HAVE_PR_SET_DUMPABLE
-- Performing Test HAVE_PR_SET_DUMPABLE - Success
-- Performing Test HAVE_RLIMIT_CORE
-- Performing Test HAVE_RLIMIT_CORE - Success
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Looking for IceConnectionNumber in ICE
-- Looking for IceConnectionNumber in ICE - found
-- Found X11: /usr/lib/x86_64-linux-gnu/libX11.so
-- Including translations...
-- Enabled features:
 * Auto-Type, Automatic password typing
 * YubiKey, YubiKey HMAC-SHA1 challenge-response

-- Disabled features:
 * Networking, Compile KeePassXC with network access code (e.g. for downloading website icons)
 * KeePassXC-Browser, Browser integration with KeePassXC-Browser
 * SSHAgent, SSH agent integration compatible with KeeAgent
 * KeeShare, Sharing integration with KeeShare
 * KeeShare-Secure, Sharing integration with KeeShare with secure sources

-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    WITH_XC_HTTP

$ make -j4
/opt/git/keepassxc-2.4.0/src/gui/DatabaseWidget.cpp: In member function ‘void DatabaseWidget::search(const QString&)’:
/opt/git/keepassxc-2.4.0/src/gui/DatabaseWidget.cpp:1115:5: error: ‘m_shareLabel’ was not declared in this scope
     m_shareLabel->setVisible(false);
     ^~~~~~~~~~~~
[ 62%] Building CXX object src/CMakeFiles/keepassx_core.dir/gui/EntryPreviewWidget.cpp.o
[ 62%] Building CXX object src/CMakeFiles/keepassx_core.dir/gui/DialogyWidget.cpp.o
src/CMakeFiles/keepassx_core.dir/build.make:855: die Regel für Ziel „src/CMakeFiles/keepassx_core.dir/gui/DatabaseWidget.cpp.o“ scheiterte
make[2]: *** [src/CMakeFiles/keepassx_core.dir/gui/DatabaseWidget.cpp.o] Fehler 1
make[2]: *** Es wird auf noch nicht beendete Prozesse gewartet...
CMakeFiles/Makefile2:274: die Regel für Ziel „src/CMakeFiles/keepassx_core.dir/all“ scheiterte
make[1]: *** [src/CMakeFiles/keepassx_core.dir/all] Fehler 2
Makefile:129: die Regel für Ziel „all“ scheiterte
make: *** [all] Fehler 2

**Comment by droidmonkey** [comment]
Use -DWITH_XC_KEESHARE=ON. This issue will be fixed in 2.4.1.

**Comment by droidmonkey** [comment]
See #2810 for the fix

**Comment by kairaven** [comment]
Thank you for the info, builds without problems.

**Comment by wingsuit** [comment]
> Use -DWITH_XC_KEESHARE=ON. This issue will be fixed in 2.4.1.

Perfect thanks
