### ISSUE TITLE
Order of context menu options

### ISSUE THREAD

**Issue by anewuser** [keepassxreboot/keepassxc#2813]
KeePassXC 2.4.0 for Windows has changed the order of the context menu options. Instead of having the most used options at the top (`Copy username` and `password`), now it has `New Entry`, even when you're clicking on an existing entry. 

Please consider placing those two options at the top again or letting us customize the order.

**Comment by droidmonkey** [comment]
The context menu re-uses the main menu for entries. I do agree it does not make much sense to make a new entry when you are interacting with an existing entry. We should offer a different menu for the context menu or remove "New Entry" when interacting with a specific entry.

**Comment by mfc** [comment]
please see my recommendation for how context menu should be ordered for existing entries (with potentially removing "New Entry", as mentioned here):

https://github.com/keepassxreboot/keepassxc/issues/2942#issue-429281505
