### ISSUE TITLE
Attachment files corrupted / wrong size displayed

### ISSUE THREAD

**Issue by Mirodin** [keepassxreboot/keepassxc#2817]
First of all I really want to say thank you guys for this great peace of software. However today I found out that all my attachments were broken/corrupted. Since I use them quite seldom I did not notice anything since KeePassXC opens without complaint and works just as it should. Manually going back through all my backups I found that this must have happened between 2018-12-31 (last working snapshot of my system) and 2019-02-01 (first one with broken attachments). Right around this time my KeePassXC database shrunk from ~4.7MiB to ~98KiB. However since KeePassX did not complain about those attachments I did not notice until today that is why I can not give you any helpful informations, I am sorry...

However, when open one of those entries the attachment size shows complete random values: i.e. I have a 512 Bytes keyfile stored and the GUI claims it is 893.00 Bytes whilst one of my attached PDFs which originally had 463 KBytes now has 86 Bytes according to KeePassXC.

My system:

- Void Linux up to date
- KeePassXC 2.3.4

Again I am deeply sorry I can not give you any helpful debugging information but maybe you could add some checks so KeePassXC yells at its user if an attachment filesize does not match after opening/saving? I will be able to restore most of my attachments from my old backups since I use attachments rarely and did not change any since then.

**Comment by droidmonkey** [comment]
Were you using KeePassXC the entire time even before they were "ok"? Did you update your database to KDBX4?

**Comment by Mirodin** [comment]
Yes, I did not change anything in my setup since September last year, my database was KDBX by then already using Argon2 and AES 256.

**Comment by Mirodin** [comment]
Whilst checking out stuff I also saw yesterday that my Android-App KeePass DX can not open any database I saved after 2019-03-14. I have no idea if that is related but I created a bug report already, the [image I posted](https://github.com/Kunzisoft/KeePassDX/issues/240) might be useful since I thought it was an issue with their app.

**Comment by droidmonkey** [comment]
I find it very likely that this is caused by another app. I have not heard very much good things about KeePass DX. We recommend KeePass2Android.

**Comment by Mirodin** [comment]
> I have not heard very much good things about KeePass DX in terms of inter-operating with more advanced features of kdbx. We recommend KeePass2Android.

All right then, I will follow your advice since KeePassXC is way more important for me than mobile use. But the fact that KeePassXC did not complain whilst KeePassDroid and KeePass DX did still confuses me.

Thanks anyways.

**Comment by droidmonkey** [comment]
The error shown on the screenshot leads me to believe the mobile app encountered an unexpected XML token while parsing the stream. It doesn't say what that token is though. I do not find it odd that there are HUGE differences between the functionality of the mobile apps and our program. They are in entirely different languages and don't share any implementation details besides the KDBX format itself.

**Comment by Mirodin** [comment]
> don't share any implementation details besides the KDBX format itself

Well I did not know that but thought there was some common denominator but good to know. Will keep an eye on my mobile apps and see if they behave odd. Thank you for your help by figuring this out.
