### ISSUE TITLE
"Check for updates" popup steals the focus

### ISSUE THREAD

**Issue by KewlCat** [keepassxreboot/keepassxc#2819]
## Expected Behavior
I open a database, start typing my passphrase, type my passphrase entirely, validate and start using the password manager

## Current Behavior
I open a database, start typing my passphrase, get all my keypresses eaten after the third by the "Would you like KeePassXC to check for updates on startup?" popup.

## Possible Solution
Do not steal the focus from the "Password" field.
DO. NOT. USE. POPUPS.

## Steps to Reproduce
1. Upgrade to brand new v2.4.0 after having used v2.3.4 for months
2. Open a kdbx file
3. Start typing your passphrase because the focus is conveniently set on this fiedl when the application starts up
4. Try to be polite

## Context
Normal usage.

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - v2.4.0
Revision: the released one

Libraries:
- A LOT OF THEM

Operating system: Linux
CPU architecture: x86_64
Kernel: 4.14.irrelevant

Enabled extensions:
- Dunno

**Comment by droidmonkey** [comment]
This is a ONE-TIME pop-up. It does catch you sometimes though because there is a slight delay after startup.

**Comment by KewlCat** [comment]
Once upon a time you had a nice (i.e. non-intrusive) warning embedded above the Password field, IIRC it was used to say "this is not a release version, YMMV, etc." and I thought it would be better to use it for that, but you're right : it's never going to happen again, and I over-reacted.
Keep up the good work!

**Comment by droidmonkey** [comment]
I do agree it is very... how should I say.... tasteless to popup right when you open the program. We will look to improve this behavior.

**Comment by jovandeginste** [comment]
I noticed there were a few operations to optionally take after upgrading to 2.4.0 (from 2.3.4); perhaps a onetime post-password "you just upgraded, here are some new things" questionnaire would be more appropriate? You could even integrate the changelog since the previous version...

**Comment by jtrh** [comment]
This issue happened to me after upgrading to v2.4.0. However, I didn't arrive here to complain about the popup stealing focus. I just wanted to find out what the popup was about, because I accidentally closed it while typing my password.

I think the focus-stealing behavior increases the risk of the user accidentally closing the popup before having the chance to read it.
