### ISSUE TITLE
Autotype does not type anything

### ISSUE THREAD

**Issue by cramsvik** [keepassxreboot/keepassxc#2825]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Expected Behavior
When moving focus from a window (terminal, browser window, whatever) over to KeePassXC and then pressing CMD+V I would expect focus to be returned to the previous window and the autotype sequence should be performed.

## Current Behavior
When pressing CMD+V (or selecting autotype from popup menu) the focus goes back to the previous window, but nothing is typed.

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )

## Steps to Reproduce
1. Select a window (e.g. terminal with login prompt)
2. Set focus to KeePassXC
3. Select an entry from the list
4. Press CMD+V (or right click and select autotype

## Context
OSX Mojave 10.14.3
The current workaround is to manually copy/paste username and passwords separately, but in some cases (particularly on remote controlled servers) copy/paste isn't working, and then autotype has so far been the workaround to manually typing insanely long passwords. Without autotype logging in has become a lot more cumbersome.

[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )
Circumstances are not unique; everything worked fine in my previous version (2.2.2)

## Debug Info
KeePassXC - Version 2.3.4
Revision: 6fe821c

Libraries:
- Qt 5.9.3
- libgcrypt 1.8.2

Operating system: macOS 10.14
CPU architecture: x86_64
Kernel: darwin 18.2.0

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by varjolintu** [comment]
The keyboard shortcut is changed to Cmd+Shift+V.

**Comment by varjolintu** [comment]
For me both the application menu and the popup menu shows the correct keyboard shortcut. And sorry, I read incorrectly that you are using 2.4.0.

I tried the 2.3.4 also and it's working like it should with Cmd+V.

**Comment by droidmonkey** [comment]
You have to enable keepassxc to control your computer under the accessibility settings. MacOS should have asked you this the first time you tried to use autotype.

**Comment by cramsvik** [comment]
@varjolintu Yes, I tried some combos of global autotype, disabling the details of looking for specific windows, different key combos etc.

@droidmonkey Yes, I already checked that the setting were in fact on (and it was). After you mentioned it I tried disabling and then reenabling the setting, and lo and behold, that did the trick. Apparently the switch was only visually enabled/checked.
