### ISSUE TITLE
Help wanted: version issue 2.3.4 versus 2.4. KeepassXC versus Chrome plugin

### ISSUE THREAD

**Issue by dpb657** [keepassxreboot/keepassxc#2829]
The KeepassXC plugin for Chrome thinks there is a 2.4 version available. The newest on the KeepassXC website is 2.3.4. Who is right?

**Comment by affinityv** [comment]
That has 2.4.0 ????
Perhaps, just perhaps you might want to wait for 2.4.1 ....

https://keepassxc.org/download/

**Comment by affinityv** [comment]
Which OS are you using?  The MacOS files are expected to be signed Monday.... the website is showing 2.3.4 for MacOS

**Comment by dpb657** [comment]
Mac 10.14.3
[cid:image001.png@01D4DFFA.4465FE60]
[cid:image002.png@01D4DFFA.4465FE60]
Darryl Baker  (he/him/his)
Sr. System Administrator
Distributed Application Platform Services
Northwestern University
1800 Sherman Ave.
Suite 6-600 – Box #39
Evanston, IL  60201-3715
darryl.baker@northwestern.edu<mailto:darryl.baker@northwestern.edu>
(847) 467-6674

**Comment by dpb657** [comment]
Mac 10.14.3

cid:image001.png@01D4DFFA.4465FE60
cid:image002.png@01D4DFFA.4465FE60
