### ISSUE TITLE
Browser integration not possible after update to 2.4.0

### ISSUE THREAD

**Issue by zroug** [keepassxreboot/keepassxc#2831]
## Expected Behavior
For convenience and security there should be a way to auto fill passwords in the browser.

## Current Behavior
Version 2.4.0 removed support for KeePassHttp. There is support for another plugin that requires you to execute https://github.com/keepassxreboot/keepassxc/releases/download/2.4.0/keepassxc-snap-helper.sh. But that script fails with

> Sorry, browsers installed as snaps are not supported at this time.

That means that there is no way to auto fill passwords.

## Possible Solution
Keep KeePassHttp at least until the other plugin is supported or add support for this to the other plugin.

## Steps to Reproduce
1. Install Browser and KeepassXC `snap install firefox keepassxc`
2. Run the script https://github.com/keepassxreboot/keepassxc/releases/download/2.4.0/keepassxc-snap-helper.sh.
3. You will get the error mentioned above.

## Debug Info
KeePassXC - 2.4.0

Libraries:
- Qt 5.9.5
- libgcrypt 1.8.1

Operating system: Ubuntu Core 18
CPU architecture: x86_64
Kernel: linux 4.18.0-16-generic

**Comment by droidmonkey** [comment]
Sorry but it is not coming back. You can use autotype instead.

**Comment by zroug** [comment]
I don't think Autotype is a reasonable workaround. Autotype is much more cumbersome as you have to search the entries for each login and switch between applications. Also Autotype dosen't check that you enter the credentials for the correct website.

But there are other options. For example KeePassXC could be distributed as classic snap. The `--classic` option is exactly for these use cases where you want to package an application for which snappy doesn't support all use cases. Maybe there could be an extra channel for the classic version so it doesn't affect users that don't need this.

Currently it looks like there is no option to install the last working version of KeePassXC. I tried `snap install --revision=49 keepassxc` (the last working stable revision) but it says 'Access by specifying a revision is not allowed for this Snap.'.

**Comment by droidmonkey** [comment]
A couple things to note here:

1. We are revision 267 in the snap store, you can obtain the latest from here: https://snapcraft.io/keepassxc

2. I was able to get the browser integration to work in snaps and you will find instructions on how to do that in the application settings page.

**Comment by zroug** [comment]
This is about both, browser installed as snap and KeePassXC installed as snap.

You said that the browser integration works when the browser is installed as a snap and KeePassXC is installed as a native application. That means it also works when the browser is installed as a snap and KeePassXC is installed as a snap too but with `confinement` set to `classic`. You could provide a  additional channel with `confinement` set to `classic` so that users that want to install both as a snap can use this channel to enable the browser integration.

**Comment by droidmonkey** [comment]
I am not certain that the browser integration works with browsers installed as snaps. I have tested many different combinations and the ones that always seemed to fail were when the browser was installed as a snap.

**Comment by zroug** [comment]
I will test this when I have time.

**Comment by zroug** [comment]
As it turns out, having the browser as a snap and KeePassXC as a native application does not work. That also means that just setting confinement to classic will not work.

I my opinion that makes this issue even more important because I think having the browser installed as a snap will eventually become the default for Ubuntu. Therefore I dug a bit deeper and found a path that might work.

First of all it turns out that having KeePassXC installed as a snap and Firefox installed as a snap in `devmode` does work. That means there is nothing inherent to snaps that stops this from working, it is just the lack of proper permissions.

There are two issues that needs to be solved.

1. The snapped browser needs to be able access `keepassxc-proxy` and its dependencies. When `keepassxc-proxy` is compiled as a small static binary, that means it could be copied to a location that the browser can access. For example next to `org.keepassxc.keepassxc_browser.json` or into the users home directory. This could be done by the same script that creates `org.keepassxc.keepassxc_browser.json`, that is needed anyway.

2. `keepassxc-proxy` needs to communicate with `keepassxc`. I think the communication happens through a socket on the filesystem. When this location is changed to a path that can be accessed by both, the browser and KeePassXC, it should work. In the future there might be something similar to the content interface that is nicely applicable to this use case but for now some path in the users home directory could be used as a workaround.

By the way, I noticed that currently `$SNAP_COMMON/kpxc_server` is used as the socket path. Wouldn't it make more sense to use `$SNAP_USER_COMMON/kpxc_server` so KeePassXC can be used by multiple users on the same system?

**Comment by droidmonkey** [comment]
You are correct we should be using $SNAP_USER_COMMON.
