### ISSUE TITLE
Option to Automatically Select Key File, Then Log In

### ISSUE THREAD

**Issue by Y0Mamma** [keepassxreboot/keepassxc#2833]
[TIP]:  # ( Provide a general summary of the feature in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Summary
[NOTE]: # ( Provide a brief overview of what the new feature is all about )

## Desired Behavior
[NOTE]: # ( Tell us how the new feature should work, be specific )

## Possible Solution
[NOTE]: # ( Not required, but suggest ideas on how to implement the addition or change )

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )

**Comment by Y0Mamma** [comment]
First, let me say that KeePassXC is far and away the best password manager on the planet. Awesome work guys. 

I am using version 2.4.0. 

Currently, I have KeePassXC set to :
   A) Minimize window at application startup.
   B) Load the previous database.
   C) Remember the last key file.

It would be really nice if there was an option to take the next step and automatically log in to my database using the key file.

**Comment by droidmonkey** [comment]
Yes, you can specify a database and key file on the command line. ```keepassxc --key [key file] [database file]

**Comment by dacorsa** [comment]
and the password? how can specify the password? thanks

**Comment by droidmonkey** [comment]
Use ```--pw-stdin``` and pipe in the password. For windows that looks like ```echo [password]| keepassxc --keyfile [key file] [database file]```. Note the lack of space between the password and the pipe!

However, this is currently a little broken in 2.4.0. Fix is coming to 2.4.1.

**Comment by neodada** [comment]
@droidmonkey Is there documentation available for all commands? I tried but couldn't find.

**Comment by droidmonkey** [comment]
Yes here: https://github.com/keepassxreboot/keepassxc/blob/develop/docs/man/keepassxc.1.adoc

**Comment by neodada** [comment]
@droidmonkey There is no exit command available for windows?

**Comment by droidmonkey** [comment]
Not sure what you mean by that

**Comment by neodada** [comment]
> Not sure what you mean by that

Command to close KeepassXC instance (like official keepass has)
Keepassxc --exit
