### ISSUE TITLE
AppImage 2.4.0 does not check and populate application desktop shortcut anymore

### ISSUE THREAD

**Issue by priv** [keepassxreboot/keepassxc#2835]
## Expected Behavior
In past versions, keepassxc asked if we want to create application shortcut upon first start-up. If yes is selected, a shortcut will be created under ~/.local/share/applications

## Current Behavior
Nothing happens upon first startup

## Steps to Reproduce
1. Download AppImage and run

## Context
Cannot add to favorites anymore without handmade shortcut

## Debug Info
KeePassXC - Version 2.4.0
Revision: c51752d
Distribution: AppImage

Libraries:
- Qt 5.10.1
- libgcrypt 1.8.1

Operating system: Ubuntu 18.10
CPU architecture: x86_64
Kernel: linux 4.18.0-16-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (only unsigned sharing)
- YubiKey

**Comment by mat-m** [comment]
Also the icon is not shown in the taskbar (Linux Mint 19.1, based on Ubuntu 18.04, Cinnamon)

**Comment by phoerious** [comment]
This is intended. AppImages have deprecated shortcut creation on startup in favour of using appimaged.

**Comment by priv** [comment]
Thanks I never know there is appimaged.

**Comment by vanous** [comment]
Thank you for all the work, trully appreciate. Only as a feedback, let me say that after almost a year after this was filed, appimaged is still not part of Debian and the user friendliness of keepassxc installation remains low due to that. I know there is a snap but it is the sole intention of AppImage to be self contained.

**Comment by droidmonkey** [comment]
Recommend you direct your comment towards the AppImage team and/or Debian package maintainers. This would be a complaint levied against all AppImage use on Debian.
