### ISSUE TITLE
Entry options are greyed out when using arrow keys

### ISSUE THREAD

**Issue by JitterBugGitterHub** [keepassxreboot/keepassxc#2838]
## Current Behavior
[NOTE]: # ( Tell us what actually happens )
When selecting/highlighting an entry and opening the entry options (right-click context menu or in the toolbar), using the up-arrow or down-arrow key greys out all options, except for "New Entry".

Right-click context menu: [Before](https://pictshare.net/07oadu.jpg) / [After](https://pictshare.net/etukct.jpg)
Toolbar menu: [Before](https://pictshare.net/rnukrc.jpg) / [After](https://pictshare.net/x1b08g.jpg)

To restore the options I have to restart KeePassXC, re-opening the database does not work.

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1. Select/highlight entry
2. Open entry options via right-click or the toolbar
3. Press up-arrow or down-arrow key

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.4.0
Revision: c51752d

Libraries:
- Qt 5.12.1
- libgcrypt 1.8.4
Operating system: Windows 10 (10.0)
CPU architecture: x86_64
Kernel: winnt 10.0.17763

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

**Comment by droidmonkey** [comment]
Wow that is a crazy bug, good find!

**Comment by JitterBugGitterHub** [comment]
Hi,

although the problem is fixed for me in the right-click context menu, it still persists in the toolbar menu as described in the OP.

Here's my current debug info:

> KeePassXC - Version 2.4.2
> Revision: a775031
> 
> Qt 5.12.3
> Debugging mode is disabled.
> 
> Operating system: Windows 10 (10.0)
> CPU architecture: x86_64
> Kernel: winnt 10.0.18362
> 
> Enabled extensions:
> - Auto-Type
> - Browser Integration
> - SSH Agent
> - KeeShare (signed and unsigned sharing)
> - YubiKey
> 
> Cryptographic libraries:
>  libgcrypt 1.8.4
