### ISSUE TITLE
KeePass Database Forcefully Updated to KDBX 4 in 2.4.0

### ISSUE THREAD

**Issue by sindastra** [keepassxreboot/keepassxc#2839]
## Expected Behavior
Open KDBX 3.1 database with 2.4.0, save it and keep it in KDBX 3.1 format.

## Current Behavior
Open KDBX 3.1 database with 2.4.0 and it seems to upgrade to KDBX 4?
I keep going to the database settings and setting it back down to KDBX 3.1 but it keeps setting itself to KDBX 4?

## Steps to Reproduce
1. Open KDBX 3.1 with 2.4.0
2. Choose yes when migrating data
3. Seems to be on KDBX 4 now and can't be converted down to 3.1

## Context
I use MiniKeePass (iOS app) which cannot handle KDBX 4, so I require KDBX 3.1.

## Debug Info
KeePassXC - Version 2.4.0
Revision: c51752d

Libraries:
- Qt 5.12.1
- libgcrypt 1.8.4

Operating system: Windows 10 (10.0)
CPU architecture: x86_64
Kernel: winnt 10.0.17763

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

**Comment by phoerious** [comment]
Custom Data for groups end entries does not exist in 3.1, so your DB is auto-upgraded to 4.0. This is, although perhaps not obvious to the user, working as intended. Unless you have a very strong reason not to, I would urge you to stay with 4.0 as it offers better security and all major KeePass-compatible programs support it.

**Comment by sindastra** [comment]
> stay with 4.0 as it offers better security

@phoerious Could you elaborate please? Thank you!

**Comment by droidmonkey** [comment]
Please see https://keepass.info/help/kb/kdbx_4.html

**Comment by ligyxy** [comment]
Currently I don't find an app to open database file on iOS.
I have tried MiniKeePass and Strongbox while both of them don't support KDBX 4.
I am also unable to convert the database back to KDBX 3.1 either in KeePassXC 2.4.0.

If KDBX 4 is requited with latest KeePassXC, I am afraid there is no iOS app which is compatible to KeePassXC at this point.

**Comment by droidmonkey** [comment]
Wow I did not realize the terrible state that KeePass is in on iPhone. Minikeepass is effectively abandoned and the only thing left are ad/subscribe closed source apps. We really need to get in that flutter implantation.

**Comment by sindastra** [comment]
@ligyxy I had to look for alternatives on iOS since MiniKeePass doesn't support KDBX4. I switched to Strongbox which *does* support KDBX4 and I'm happy with Strongbox. Perhaps you tried an old version that didn't support KDBX4?

@droidmonkey Strongbox is open source and supports KDBX4. I am using it now. Can recommend.

Strongbox even supports the iOS auto fill feature! Great app IMO.

**Comment by ligyxy** [comment]
@sindastra Yep, I have re-download Strongbox and I can confirm that it works with KDBX4.

Btw, keepassium might be a better option than Strongbox, when it comes to UI design.

**Comment by droidmonkey** [comment]
@sindastra 	noted thanks.

**Comment by kamukhar** [comment]
This shouldn't be automatic.  There should be a confirmation stating the performing said function will require conversion to KDBX4, do you want to continue.  automatic upgrading has consequences.

**Comment by droidmonkey** [comment]
Wow, please don't necropost.
