### ISSUE TITLE
Automatically create new database on first run

### ISSUE THREAD

**Issue by jsha** [keepassxreboot/keepassxc#284]
When a user first downloads KeePassXC, they may not be familiar with the database model. They see a grey window that says "Welcome", along with the menu items: Database, Entries, Groups, View, Tools, and Help, plus a series of icons. Because none of these entries says anything about passwords, it's not clear what the next step is.

## Expected Behavior
On first run, immediately present the "New database" UI. Additionally:

 - Adjust the wording on "New database" so instead of "Change master key," it says "Choose a master password or key file," along with a short explanation of what this is for.

## Current Behavior

On first run, no database is automatically created.

## Context
I'm trying to provide advice on password managers for non-technical users, and the first run experience for KeePassXC is currently confusing for new users.

## Your Environment
* KeePassXC version: 2.1.1

**Comment by TheZ3ro** [comment]
There is already an Issue for the Welcome screen replacement https://github.com/keepassxreboot/keepassxc/issues/204
We should discuss which is the best way to solve this

**Comment by louib** [comment]
This is somewhat related to https://github.com/keepassxreboot/keepassxc/issues/204.

**Comment by jsha** [comment]
Closing this in preference for #204. Thanks for pointing it out!
