### ISSUE TITLE
Records to recently-used.xbel when Remember settings are disabled

### ISSUE THREAD

**Issue by SoAboutThat** [keepassxreboot/keepassxc#2841]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
When specifically disabling Remember last databases and Remember last key files, that those files will not be "remembered" as in recorded and stored.

## Current Behavior
[NOTE]: # ( Tell us what actually happens )
User is misled because KeePassXC does write the files to ~/local/.share/recently-used.xbel, creating a serious security risk.

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )
Don't write to recent files lists.

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1. Confirm you have the appropriate settings disabled. Toools-Settings->Remember  last databases (unchecked) -> Remember last key files  and security dongles (unchecked)
2. Open a kdbx file using a key file.
3. Close the pwd database, exit KPxc.
4. Navigate the file system to ~/local/.share
5. Open recently-used.xbel in any text editor.
You will now have all that is needed to compromise the password database.

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )

My brother noted I had started using KeePassXC after migrating from Kubuntu to straight Ubuntu. He bet me $5 he could break into my passwords within 60 seconds of me leaving the room. He won the bet. Graciously he showed me how.

If it is decided that this is not a bug, and needs no code correction, then it requires at least a clear warning to users that the application does in fact record the names and locations of these files even when the user thinks otherwise. I searched the web and this development area and can find nothing on how to prevent this at the operating system level and not any hint of concern about it in the actual KPxc community. So I must be missing something obvious, and when whatever that is is pointed out to me, my sincerest apologies, but, well, what?

No other applications write to this xbel file and its only entries are the ones left by access KeePassXC, specifically the kdbx file and the key file.

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.3.4
Revision: 6fe821c

Libraries:
- Qt 5.9.5
- libgcrypt 1.8.1

Operating system: Ubuntu 18.04.2 LTS
CPU architecture: x86_64
Kernel: linux 4.15.0-46-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey
(NOTE -- while those extensions show as enabled in the debug, they are not enabled in Application settings and I have never used them).

**Comment by droidmonkey** [comment]
First off, KeePassXC does NOT write to recent.xbel. That is a function of Kubuntu and I am not aware of a way to prevent that from happening. Secondly, knowing the location of the database should absolutely in no way whatsoever allow someone to get into your database.... UNLESS you did not use a secure password.

**Comment by droidmonkey** [comment]
Read here to disable the "xbel" file: https://askubuntu.com/questions/269858/how-do-i-prevent-the-file-recently-used-xbel-from-being-created

**Comment by SoAboutThat** [comment]
I can confirm that it is definitely not a KeepassXC issue, not restricted to the XC version, nor even to KeePass itself, as it affects Veracrypt and other security-related apps.  The issue is if a user thinks it is "safe" to use a key file alone and the OS tracking exposes exactly which file it is. The linked solutions are not universally working so the only real solutions are to use strong passwords and/or ensure keyfiles are on removable media.  Before mocking people who use keyfiles on internal media, if there wasn't an accessible record there would be no real problem with this strategy depending on the file chosen, necessarily being one in a mix of thousands. Regardless, it might behoove developers to alert their users that all variants of Ubuntu track their apts file usage and the risks therein.

**Comment by droidmonkey** [comment]
When you try to create a database without a password we explicitly warn that it is not a good idea.
