### ISSUE TITLE
Favicon download shouldn't require a URL schema

### ISSUE THREAD

**Issue by singalen** [keepassxreboot/keepassxc#2843]
## Summary
Favicon download shouldn't require an URL schema in URL field.

## Desired Behavior
Moreover, if a "Title" field looks like web site name (something.com, org, net, io, or whatever domain regex) and URL field is empty, it makes sense to try the "Title" field.

## Possible Solution
Use libcurl to fetch a file, or just try all of http, https and what else to fetch the favicon.

## Context
I often name Internet accounts after web site URLs. Typing the same again into URL field is unnecessary.

**Comment by droidmonkey** [comment]
We will not be searching the title for a url, that is why there is a url field.

**Comment by singalen** [comment]
AFAIK, the field was there long before "download favicon" function and keepassxc existed.

There are two schools of thought: "in order to work, the software should be used the way we designed it" and "we designed the software the way that it will generally just work for users who use the software in every way they can imagine".
The first is good when designing a resource-constrained software for machines, or a handful of fellow engineers. The second way is preferable when designing for the ease of use.

**Comment by kneitinger** [comment]
+1 to the scheme not being needed.  The QUrl class does require a scheme to make requests if I'm not mistaken, therefore I think the logic should be:
- If HTTPS, use HTTPS as scheme
- If HTTP (or no scheme), try HTTPS as scheme, but fallback to HTTP (should this be user configurable, like DDG fallback?)
- If scheme is anything else (ssh, file, ftp, etc), do not attempt download.
