### ISSUE TITLE
Passwords are no longer hidden in 2.4.0

### ISSUE THREAD

**Issue by ei-ke** [keepassxreboot/keepassxc#2845]
After updating to 2.4.0 on Arch Linux the passwords are not hidden in the columns though this option is enabled in the settings.
Also dis- and reenabling this setting doesn't change this beahvior.

The keepassxc.ini shows:
HidePasswords=false

Closing Keepass, changing this to true, and starting Keepass fixes this.

Greetings
Eike

**Comment by droidmonkey** [comment]
The column visibility is controlled by right clicking the field headers in the main view and selecting "hide passwords"

**Comment by ei-ke** [comment]
Okay, sorry for bothering you with this issue :)
