### ISSUE TITLE
Keepass 2.4.0 final cannot use database with preceeding . in filename

### ISSUE THREAD

**Issue by Lalarian** [keepassxreboot/keepassxc#2848]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Expected Behavior
After starting KeepassXC 2.4.0 final, I wanted to load the old database ".passwords.kdbx" that I have been using with 2.4.0 snapshots all the time, from the 'load previoulsy used databases' dialog that automatically appears on loading KeepassXC.

## Current Behavior
a) **After trying to load the '.passwords-kdbx' database from the ''load previoulsy used databases' dialog Keepassxc 2.4.0 throws an error like "Database file does not exist or isn't available."**

b) When I instead try opening the database file from the menu (database->open database), the load is actually working, although I have to type in the filename '.passwords.kdbx' manually because the file dialog doesn't support showing hidden files, and I also have to press Return after entering the filename, because the "Open" button of the file dialog won't activate.
**After the database was then loaded, the title bar of KeepassXC shows just 'passwords.kdbx' instead of '.passwords.kdbx'.**

c) So the . (full-stop) somehow get's lost during the processes of loading the database or applying the unlock password. Maybe this symptom points to a relation between both problems.

## Possible Solution
This did not happen with any of the snapshots I have been using for month. This behaviuor started first with 2.4.0 final. So I assume that there is a recent a change reponsible for this flaw.

Thank you for the attention :)

## Debug Info
[NOTE]: #KeePassXC - Version 2.4.0
Revision: c51752d
Distribution: AppImage

Libraries:
- Qt 5.10.1
- libgcrypt 1.8.1

Operating system: Ubuntu 18.04.2 LTS
CPU architecture: x86_64
Kernel: linux 4.15.0-46-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (only unsigned sharing)
- YubiKey

**Comment by droidmonkey** [comment]
I couldn't find any code that was changed since we started the 2.4.0 release branch that would have impacted loading of database files (specifically their name).

**Comment by kneitinger** [comment]
I am unable to reproduce this on Ubuntu 18.04 with the AppImage (identical Debug Info to yours), or on Arch with Debug Info 

KeePassXC - Version 2.4.0
Revision: c51752d

Libraries:
- Qt 5.12.2
- libgcrypt 1.8.4

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 5.0.2-arch1-1-ARCH

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (only unsigned sharing)
- YubiKey

Additionally, I am able to see my `.testdb.kdbx` in the dialog by right clicking and selecting "Show hidden files", both on Ubuntu and Arch.  Is there anything special about your file?  Symlink?

**Comment by droidmonkey** [comment]
@kneitinger where'd you get that crazy logo from??? 😮

**Comment by kneitinger** [comment]
@droidmonkey I seemed to have been using the Numix Circle theme since before I started using KeePassX(C), because initially I had no idea what you were talking about!

Here it is:
https://github.com/numixproject/numix-icon-theme-circle/blob/master/Numix-Circle/48/apps/keepassx.svg

**Comment by Lalarian** [comment]
> I am unable to reproduce this on Ubuntu 18.04 with the AppImage (identical Debug Info to yours), or on Arch with Debug Info:
> 
> KeePassXC - Version 2.4.0
> Revision: [c51752d](https://github.com/keepassxreboot/keepassxc/commit/c51752df3913329d6fc78563c54ddd6ebd994b0f)
> 
> Libraries:
> 
>     * Qt 5.12.2
> 
>     * libgcrypt 1.8.4
> 
> 
> Operating system: Arch Linux
> CPU architecture: x86_64
> Kernel: linux 5.0.2-arch1-1-ARCH
> 
> Enabled extensions:
> 
>     * Auto-Type
> 
>     * Browser Integration
> 
>     * SSH Agent
> 
>     * KeeShare (only unsigned sharing)
> 
>     * YubiKey
> 
> 
> Additionally, I am able to see my `.testdb.kdbx` in the file select dialog (Database -> Open Database...) by right clicking and selecting "Show hidden files", both on Ubuntu and Arch. Is there anything special about your file? Symlink? Where does the file live?
> 
> Edit:
> For clarification, we are talking about the Recent Databases list in this screenshot correct?
> ![2019-03-23_14-00-06](https://user-images.githubusercontent.com/5200550/54871688-b41fb500-4d75-11e9-8bcc-bf40f043846d.png)

It's the normal direct file, as /home/<username>/.passwords.kdbx, that I am using it for many months.
I still have the last snapshot installed and it's opening the file fine, while the final verison won't without the hickups I decribed above.

**Comment by droidmonkey** [comment]
I also cannot replicate this on Ubuntu 18.04 using the published 2.4.0 appimage.
