### ISSUE TITLE
Cannot open DB with empty password in KeePassXC 2.4.0

### ISSUE THREAD

**Issue by ArchangeGabriel** [keepassxreboot/keepassxc#2849]
## Expected Behavior

Trying to open a DB with an empty password should work.

## Current Behavior

The “corrupted DB/HMAC error” message appears, and the DB does not open.

## Possible Solution

Not really a solution, but downgrading to 2.3.4 works.

## Steps to Reproduce

1. Create a empty password DB (possibly in 2.3.4, haven’t tried in 2.4.0).
2. Try to open it in 2.4.

## Context

Empty password DB.

## Debug Info

KeePassXC - Version 2.4.0
Revision: c51752d

Libraries:
- Qt 5.12.2
- libgcrypt 1.8.4

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 5.0.0-arch1-1-ARCH

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (only unsigned sharing)
- YubiKey

**Comment by droidmonkey** [comment]
Uncheck the password checkbox

**Comment by ArchangeGabriel** [comment]
Oh, indeed. Did not expect such a thing, but it makes sense. Thanks!

**Comment by droidmonkey** [comment]
This will be streamlined in 2.4.1
