### ISSUE TITLE
Choose database path as part of New Database

### ISSUE THREAD

**Issue by jsha** [keepassxreboot/keepassxc#285]
Currently, when you create a database, it doesn't have a location. This leads to a bug where the "Automatically save after every change" setting gets ignored if you haven't already saved the database once.

## Expected Behavior
As part of the "New Database" interface, include a location field with a suitable default. When the user hits "OK," attempt to save an empty database to that location. If saving the database fails, prompt the user to choose another location before continuing.

## Current Behavior
Location is not set until user selects "Save" for the first time.

## Steps to Reproduce (for bugs)
1. Go to Tools > Settings > General and check the "Automatically save after every change" box.
2. Select New Database, set a password, and click OK.
3. Add a password to the database.
4. Notice that the title bar still has a "*" indicating that the database is not yet saved.

## Context
I'm trying to provide advice about password managers to non-technical users. In #279, I propose that "automatically save after every change" should become the default. This would make the auto-save experience nicer and less error-prone.

## Your Environment
* KeePassXC version: 2.1.1

**Comment by droidmonkey** [comment]
Great find!

Off-topic: Are you doing this work as a part of the EFF? If so we should discuss some best practices and UX enhancements that would be endorsed by the EFF. You can hop on our IRC channel if you like.

**Comment by jsha** [comment]
Also, as part of this change, I'd suggest changing the default name for a new database. Right now when you hit save, the default name is "New database.kdbx". A possible alternative: "KeePassXC passwords.kdbx".

> Are you doing this work as a part of the EFF?

Yep, trying to provide some feedback with the goal of improving the advice in our SSD guide. Followed up on IRC.

**Comment by phoerious** [comment]
What about "Passwords.kdbx" or "New password store.kdbx"? "KeePassXC passwords" could be misleading again.

**Comment by jsha** [comment]
I think Passwords.kdbx would be fine. "New password store.kdbx" has a similar problem to "New database.kdbx": usually someone will create the database and never rename it, so the filename, and all the UI that shows the filename, shows "New password store.kdbx", even after it's been around for years and is no longer "new".

**Comment by droidmonkey** [comment]
+1 for passwords.kdbx

**Comment by phoerious** [comment]
Please check out my PR #302
