### ISSUE TITLE
Re-allow entry keyboard shortcuts from search box

### ISSUE THREAD

**Issue by DuBistKomisch** [keepassxreboot/keepassxc#2850]
## Summary
This is explicitly broken in https://github.com/keepassxreboot/keepassxc/pull/2431:

>Entry specific toolbar and menu items are disabled unless the entry row has focus (prevents unintended actions)

I love all the other changes in this PR, but previously I could open KeePassXC, log in, ctrl+f and start typing, then start ctrl+b, ctrl+c etc without ever having to touch the mouse. Since upgrading to 2.4.0 this is no longer possible. Can't even seem to mash tab to make it work.

## Desired Behavior
Entry keyboard shortcuts should work on the highlighted entry in search results.

## Possible Solution
Something like whitelist the search box being focused in addition to the entry itself, instead of just blanket disabling everything. Or at least add an option to disable this new "safe" behaviour.

## Context
Used to work, broke my workflow! https://xkcd.com/1172/
Should generally be possible to use KeePassXC without needing the mouse.

**Comment by droidmonkey** [comment]
Press down arrow before your normal shortcuts.

**Comment by DuBistKomisch** [comment]
Yep, that seems to work I guess, thanks.
