### ISSUE TITLE
Adding YubiKey Challenge-Response to existing database causes cash

### ISSUE THREAD

**Issue by C0inZ** [keepassxreboot/keepassxc#2851]
Expected Behavior

After starting KeePassXC 2.4.0 final, I wanted to add YubiKey Challenge-Response to an existing database.

Current Behavior

I clicked on "add YubiKey Challenge Response" in the settings of KeePassXC under additional security features and then confirmed with "OK". After that I get the following error message: (in my case german):
"Die Anweisung in 0x0000000001258805 verwies auf Arbeitsspeicher bei 0x0000000000000008. Der Vorgang read konnte im Arbeitsspeicher nicht durchgeführt werden. Klicken Sie auf "OK", um das Programm zu beenden"
When confirming with "OK" the program closes immediately.

This reproducible error occurred for the first time in version 2.4.0 in the portable as well as in the installation version. Therefore I migrated back to version 2.3.4. There it works without problems

Debug Info

KeePassXC - Version 2.4.0
Revision: c51752d
Distribution - Windows

Libraries:
- Qt 5.12.1
- libgcrypt 1.8.4

Operating system: Windows 10 (10.0)
CPU architecture: x86_64
Kernel: winnt 10.0.17763

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

**Comment by droidmonkey** [comment]
There is a bug that i inadvertently introduced at the end of the beta. You have to unhide the password field and re-add your password as well. This is a duplicate issue a PR exists to fix this in 2.4.0.

**Comment by C0inZ** [comment]
Thank you, your approach describes the procedure to add challenge-response to versions <2.4.0. Also there you have to enter the password again into the empty password field.
