### ISSUE TITLE
Return and Backspace issues when NumLock is on

### ISSUE THREAD

**Issue by cloudranger** [keepassxreboot/keepassxc#2852]
When NumLock is on, the following keys do not work in certain situations:
1. Return key does not work when entering the master key to open a keepass file (enter on numeric keypad still works)
2. Backspace does not work in the notes field

NumLock should not impact either of these keys as they are not in the numeric keypad area, they are on the main keyboard.

----

KeePassXC - Version 2.3.4
Revision: 6fe821c

Libraries:
- Qt 5.9.5
- libgcrypt 1.8.1

Operating system: Ubuntu 18.04.2 LTS
CPU architecture: x86_64
Kernel: linux 4.15.0-38-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by droidmonkey** [comment]
Cannot reproduce.
