### ISSUE TITLE
UI: Data loss at leaving keepassxc details

### ISSUE THREAD

**Issue by ditbl** [keepassxreboot/keepassxc#2855]
Leaving details via ESC or close button will not ask for confirmation.
Save button is greyed out, does not work.
Situation: enter new data and pressing save button. Then leaving via ESC.
Result: entered data lost, no asking for confirmation.
Suggestion:
1. Make save button work as name says so.
2. Hinder data loss by confirmation question at leaving via ESC or close button.
Thank you for the great work, by the way!
My version is KeePassXC 2.3.4 on Manjaro.

**Comment by phoerious** [comment]
If the save button is disabled, it means you have autosave on, i.e. KeePassXC is saving automatically for you after every change

**Comment by ditbl** [comment]
Yes, I had enabled autosave. But the described behavior is independent of this.
For example: 
- go into details of entry
- change password via generator (press apply button in generator)
- save key is grey and does not work
- ESC or close button go back or close without confirmation question
---> data loss

**Comment by droidmonkey** [comment]
Can't replicate, I just did your steps and it showed:

![image](https://user-images.githubusercontent.com/2809491/54878951-d7943f80-4e09-11e9-8fce-18ec45d01887.png)

**Comment by ditbl** [comment]
My version is KeePassXC 2.3.4 on Manjaro.
Settings:
![Screenshot_20190324_135453_Settings](https://user-images.githubusercontent.com/43282653/54879707-691ca500-4e3c-11e9-9a5a-5f85a268ee39.jpg)

Opening sample entry, generating pw, apply:
![Screenshot_20190324_135555_edited_entry](https://user-images.githubusercontent.com/43282653/54879711-76d22a80-4e3c-11e9-8a36-ab7767315c5a.jpg)

Save button is still not usable.
At this moment I didnt press the Apply button (I am may be old-school, but it is deep in my habits, that the save button is for this purpose, so I forget about the apply button occasionally.)
ESC Button goes back to List without saving or asking. New pw lost, back to the one before.

**Comment by droidmonkey** [comment]
What I am trying to tell you is that in the most up to date version of KeePassXC there is a pop-up that notifies you of unsaved changes in the entry edit dialog. The save button is for the database, not the entry. No changes are actually made to the database until you hit apply or ok from this edit dialog.

I am closing because this is not an issue in the latest version.
