### ISSUE TITLE
Can not open KeepassXC since 23-3-19

### ISSUE THREAD

**Issue by cliffcoggin** [keepassxreboot/keepassxc#2856]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
KeepassXC should open when shortcut is clicked.

## Current Behavior
[NOTE]: # ( Tell us what actually happens )
Error message appears "Unable to open the database:
File /run/user/1000/doc/138ad1a8/Keepass.kdbx does not exist."

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )
I am told an update to KeepassXC appeared a few days ago which may be the cause of the problem.

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1.
2.
3.

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION
Revision: REVISION
KeePassXC - Version 2.4.0
Distribution: Flatpak

Libraries:
- Qt 5.12.2
- libgcrypt 1.8.4

Operating system: Linux 4.15.0-46-generic
CPU architecture: x86_64
Kernel: linux 4.15.0-46-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
Libraries:
- LIBS

Operating system: Linux Mint 18.3
CPU architecture: unknown
Kernel: 4.15.0-46-generic

Enabled extensions:
- EXTENSIONS

**Comment by phoerious** [comment]
This sounds like you are trying to open a temporary database which has since disappeared. You should be able to start KeePassXC normally, ignore the message and select your actual database.

**Comment by droidmonkey** [comment]
https://github.com/flathub/org.keepassxc.KeePassXC/issues/34
