### ISSUE TITLE
"QXcbConnection: Could not connect to display :0.0" when running KeePassXC 2.4.0 from snap

### ISSUE THREAD

**Issue by quickishfm** [keepassxreboot/keepassxc#2858]
I have installed KeepassXC 2.4.0 from snap `sudo snap install keepassxc` and try to run it - from desktop, nothing happens. Running from terminal reveals this error:

```
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
qt.qpa.screen: QXcbConnection: Could not connect to display :0.0
Could not connect to any X display.
```

Should Keepass not just open as it used to when I had it installed via apt? I removed it from apt and then also renamed the ~/.config/keepassxc folder, yet it still does not run.

I think this is a Qt problem as the stdout indicates, yet I am not running over SSH - I am running on my own computer as normal.

I use Xubuntu 18.10 64 bit.

**Comment by droidmonkey** [comment]
Are you running Wayland? If so, you will need to install [xwayland](https://packages.ubuntu.com/bionic/xwayland)

**Comment by quickishfm** [comment]
I am running X11, which is why I am confused with this. Also, if it helps, my DISPLAY env variable is set to `:0.0`.

**Comment by droidmonkey** [comment]
This is not a Qt issue, very likely a snap issue with your specific setup. Try installing and running the notepadqq snap as a test.

**Comment by quickishfm** [comment]
I have run `snap install notepadqq` and notepadqq successfully runs - no issues on the terminal, nor on the shortcut on the Xfce menu.

**Comment by quickishfm** [comment]
Somehow installing KeepassXC from snap now works - I believe installing notepadqq must have reinstalled something in snap, perhaps. Since it works I will close it, but be warned, I have no idea how it is fixed.

**Comment by droidmonkey** [comment]
That's the common theme with snaps...

**Comment by julien-montmartin** [comment]
Exact same KeePassXC issue here. First snap installed manually, doesn't run with same error. Installing **and uninstalling** Notepadqq solve the problem. Obviously, Notepaddqq install scripts (which run much longer than those of KeePassXC) do _something_ that KeePassXC should do too.
