### ISSUE TITLE
KeePassXC is unable to open database claiming the file does not exist even though it does

### ISSUE THREAD

**Issue by Jan-Zz** [keepassxreboot/keepassxc#2860]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

KeePassXC worked fine until a couple days ago: I use a master password for my database, have the last (and only) database location saved and when I open the program I just type the master password and it opens.

Since yesterday it doesn't open the database, displaying the error message 
`Unable to open the database:`
`File /run/user/1000/doc/bfc31ffd/Passwords_Linux.kdbx does not exist.`
...but the file **does** exist.

Things I've tried:

- I cleared the list of recently opened databases, restarted the program and clicked on `Open existing database` and chose the file I want to open (I have it saved in a different location than the above).

- Using another computer (with Windows/KeePass) I was able to open file normally and export the passwords to csv. I then imported the csv on my machine with KeePassXC, saved the file as .kdbx, and was able to open it afterwards ... **once**. Every subsequent time I tried to do this, it failed, showing the same error message as above.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
The database should be found because the file clearly exists and be opened on entering my master password.

## Current Behavior
[NOTE]: # ( Tell us what actually happens )
It shows the error message
`Unable to open the database:`
`File /run/user/1000/doc/bfc31ffd/Passwords_Linux.kdbx does not exist.`
I tried older versions of the database file from my backup, but no matter what file I try it shows the same error.

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.4.0
Distribution: Flatpak

Libraries:
- Qt 5.12.2
- libgcrypt 1.8.4

Operating system: Linux 4.15.0-46-generic
CPU architecture: x86_64
Kernel: linux 4.15.0-46-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

**Comment by droidmonkey** [comment]
OMG really, please search. There are already two issues regarding this exact situation.
