### ISSUE TITLE
Integrity verification instructions on website

### ISSUE THREAD

**Issue by alessiosacco** [keepassxreboot/keepassxc#2861]
After having downloaded the MSI installer from the website, I had seen the link to the procedure to verify the integrity of the download using the SHA256 digest. At [https://keepassxc.org/verifying-signatures](https://keepassxc.org/verifying-signatures) the instructions refer to a downloaded file that has .exe extension, which is not the case anymore.

What is shown right now:
`(Get-FileHash .\KeePassXC-*-Win64.exe).Hash -eq (Get-Content .\KeePassXC-*-Win64.exe.DIGEST).split(" ")[0].ToUpper()`

What should be shown:
`(Get-FileHash .\KeePassXC-*-Win64.msi).Hash -eq (Get-Content .\KeePassXC-*-Win64.msi.DIGEST).split(" ")[0].ToUpper()`

**Comment by droidmonkey** [comment]
Good catch, and fixed.

**Comment by MidgardWarrior** [comment]
I am getting the following error. I've never used this command so have no idea what could be wrong. I also cannot find anything on google that could indicate why this is. Am I doing something wrong or is there an issue? I am in the correct folder and have checked that the .msi file is in the folder. I'll still look for other solutions.

Get-Content : An object at the specified path .\KeePassXC-*-Win64.msi.DIGEST does not exist, or has been filtered by
the -Include or -Exclude parameter.
At line:1 char:50
+ ... n64.msi).Hash -eq (Get-Content .\KeePassXC-*-Win64.msi.DIGEST).split( ...
+                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (System.String[]:String[]) [Get-Content], Exception
    + FullyQualifiedErrorId : ItemNotFound,Microsoft.PowerShell.Commands.GetContentCommand

You cannot call a method on a null-valued expression.
At line:1 char:1
+ (Get-FileHash .\KeePassXC-*-Win64.msi).Hash -eq (Get-Content .\KeePas ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

**Comment by droidmonkey** [comment]
Remove the newline from the command. Or make sure you are running it in the same directory that contains the DIGEST and MSI file.

**Comment by wavesurf432** [comment]
Hello there, I've been having some trouble with the basic integrity check for Windows (https://keepassxc.org/verifying-signatures/).

I'm in the correct directory in Powershell and all the downloaded files are together, but whenever I enter:

(Get-FileHash .\KeePassXC-*-Win64.msi).Hash -eq (Get-Content .\KeePassXC-*-Win64.msi.DIGEST).split(" ")[0].ToUpper()


I get the error:

The term 'Get-FileHash' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:14
+ (Get-FileHash <<<<  .\KeePassXC-*-Win64.msi).Hash -eq (Get-Content .\KeePassXC-*-Win64.msi.DIGEST).split(" ")[0].ToUpper()
    + CategoryInfo          : ObjectNotFound: (Get-FileHash:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException


Any help is appreciated, thank you.

**Comment by droidmonkey** [comment]
Technically on Windows the msi is signed by DroidMonkey Apps, LLC so you don't need to do the integrity check. It's built in.

**Comment by wavesurf432** [comment]
> Technically on Windows the msi is signed by DroidMonkey Apps, LLC so you don't need to do the integrity check. It's built in. You'll see this when UAC asks you for permission during install.

Ah, I see, I see.

Thanks for the quick reply, much appreciated.
