### ISSUE TITLE
Opening KeePass 2.38 generated database not working

### ISSUE THREAD

**Issue by vpav** [keepassxreboot/keepassxc#2863]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )
KeePassXC fails to open databases that were generated with KeePass2 and use passphrases and keyfiles. I am not sure if this is the same issue as #2834 as I don't get any segfaults.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
KeePassXC should be able to open the database.

## Current Behavior
[NOTE]: # ( Tell us what actually happens )
When opening a kdbx database that was generated using KeePass 2.38 on a Windows 7 x64 system, opening fails. KeePassXC shows a wrong pw/corrupted db error message.
The respective database uses AES with AES-Key Derivation, GZip Compression.
The db is using both a passphrase and a keyfile.
The behaviour is reproducible, I can provide a test-db if required.

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1. Open Keepass 2.38
2. Generate a new DB using AES / AES-KDF / Gzip
3. select passphrase and generate a fresh keyfile
4. Open that database with KeePassXC 2.4.0

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )

## Debug Info
KeePassXC - Version 2.4.0
Revision: c51752d

Libraries:
- Qt 5.12.1
- libgcrypt 1.8.4

Operating system: Windows 7 SP 1 (6.1)
CPU architecture: x86_64
Kernel: winnt 6.1.7601

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

**Comment by droidmonkey** [comment]
Please provide a test database for our use. KeePass 2.38 is pretty old, you should update to 2.41.

**Comment by vpav** [comment]
Sure, db + keyfile is here: [testdb.zip](https://github.com/keepassxreboot/keepassxc/files/3000769/testdb.zip)

The passphrase for the db is **1testpassword!**

In the meantime I'll try open and save that db with KeePass 2.41

**Comment by vpav** [comment]
Ok, KeePass 2.38 vs 2.41 does not show different behaviour when opening with KeePassXC:
 
db + keyfile generated with 2.38, opened with 2.41, entry modified, saved ->  Unable to open
db + keyfile generated with 2.38, opened with 2.41, master password changed, saved -> Unable to open
db + keyfile generated with 2.41 -> Unable to open

All tests done with AES encryption, AES KDF and enabled GZip compression.

**Comment by zacharra** [comment]
I have the same issue, also happens when a database uses different encryption algorithms. One thing I noticed is that keyfiles generated with Keepass are simple XML textfiles, while keyfiles generated with KeePassXC are binary files. Maybe that has something to do with it?

**Comment by droidmonkey** [comment]
AH HAH! I found the issue. If the key file contains a '/' in the data section our check for Base64 fails which prevents loading the key.

**Comment by phoerious** [comment]
This can't possibly be a new bug, can it?

**Comment by droidmonkey** [comment]
No it was present in 2.3.x as well

**Comment by phoerious** [comment]
To anyone experiencing this, I recommend you just generate a new key file in 2.3.4, which will open in 2.4.0. Or you wait until the fix lands in 2.4.1, but there is really no reason to stick with legacy key files.

**Comment by evitalis** [comment]
Regenerating the keyfile seemed to work fine for me. On Windows I was using 2.3.4 and going to 2.4 which had the same issue.

**Comment by rickvek** [comment]
Made a keepasscx database on Mac,  cannot open it with keepass2android,  **Invalid composite key.**  Tried to open it with linux keepasscx, same cannot open it but different error (description):   
**Error while reading the database: Invalid credentials were provided, please try again.
If this reoccurs, then your database file may be corrupt. (HMAC mismatch)**
All versions are as the latest versions available of today ( fresh installations, 10-05-2020) .
Test database attached  x-special/nautilus-clipboard
copy
file:///home/rickvek/Downloads/Diverse/Passwords.kdbx

Password of database = "LetMeIn"
