### ISSUE TITLE
KeePassXC-Browser not working once apparmor for firefox enabled

### ISSUE THREAD

**Issue by Xubuntufan** [keepassxreboot/keepassxc#2864]
After enabling apparmor for firefox KeepassXC browser extension no longer works 

## Expected Behavior
KeepassXC should connect to KeepassXC browser extension in firefox (and chromium)

## Current Behavior
error message in firefox:
_KeePassXC-Browser has encountered an error:
Timeout or not connected to KeePassXC._ 

the same error does **not** happen in chromium. 

## Debug Info
KeePassXC - Version 2.4.0
Distribution: Flatpak

Libraries:
- Qt 5.12.2
- libgcrypt 1.8.4

Operating system: Linux 4.15.0-46-generic
CPU architecture: x86_64 
I am using xubuntu 18.04
Firefox 66.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

**apparmor relevant profiles enforce mode:** 

/usr/lib/firefox/firefox{,*[^s][^h]}
   /usr/lib/firefox/firefox{,*[^s][^h]}//browser_java
   /usr/lib/firefox/firefox{,*[^s][^h]}//browser_openjdk
   /usr/lib/firefox/firefox{,*[^s][^h]}//lsb_release
   /usr/lib/firefox/firefox{,*[^s][^h]}//sanitized_helper

**Comment by droidmonkey** [comment]
This seems obvious to me, you need to create an AppArmor exception for the native messaging communication from the Proxy (owner by Firefox process) to KeePassXC. This is not within the scope of the project, so closing.
