### ISSUE TITLE
Auto-Type ignoring specific sequence for window title

### ISSUE THREAD

**Issue by rizzipat** [keepassxreboot/keepassxc#2866]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

## Current Behavior
[NOTE]: # ( Tell us what actually happens )
Version 2.3.4/2.4.0
Autotype always use autotype sequence for entry and ignore specific sequence for Window Title

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION
Revision: REVISION

Libraries:
- LIBS

Operating system: OS
CPU architecture: ARCH
Kernel: KERNEL

Enabled extensions:
- EXTENSIONS

**Comment by rizzipat** [comment]
Version 2.3.4/2.4.0
Autotype always use autotype sequence for entry and ignore specific sequence for Window Title

**Comment by droidmonkey** [comment]
Post your debug info from the about menu.

**Comment by droidmonkey** [comment]
I could not replicate this using 2.4.0 on Windows.

**Comment by rizzipat** [comment]
In widows I have defined autotype with a Use specific sequence for this assocation set to (specific for windows association): {PASSWORD}{ENTER} but keepassxc always user {USERNAME}{TAB}{PASSWORD}{ENTER} that is the default sequence set by: Inherit default auto-type sequence from the group.

**Comment by droidmonkey** [comment]
![image](https://user-images.githubusercontent.com/2809491/54920861-b9e2db00-4eda-11e9-9c09-e78e44f8dd9e.png)

Are you changing (1) or (2) from the above image? I tested (2) and it works fine.

**Comment by rizzipat** [comment]
I have changed 2 in : {PASSWORD}{ENTER} but autocomplete always put username and password

**Comment by droidmonkey** [comment]
I suspect that you have not properly defined the window title to match with and you are actually pulling from another entry.

**Comment by rizzipat** [comment]
It's strange because If from keepassxc make autcomplete username and password are put in the correct widnow...

**Comment by phoerious** [comment]
Ctrl+Shift+V Auto-Type does not do any window matching.

**Comment by droidmonkey** [comment]
hah lol. Right, you need to edit (1) from the above image for CTRL+SHIFT+V auto-type.

**Comment by rizzipat** [comment]
Why not 2? Use specific sequence for this assocation? seems can be deffirent for each window association

**Comment by phoerious** [comment]
Ctrl+Shift+V types into whatever window is selected after KeePassXC is minimised. That's usually the previously selected window. Since you have selected the entry already, there is no need to further subselect. Only global Auto-Type matches based on window associations.

**Comment by rizzipat** [comment]
Ok thanks
