### ISSUE TITLE
Icon not showing up for the program itself, replaced by IcoFX 

### ISSUE THREAD

**Issue by Amnesiac9** [keepassxreboot/keepassxc#2868]
The icon for the program itself is not showing up, it has been taken over by a program called IcoFX.
 
Screenshots:
https://i.imgur.com/mI1xW44.png
https://i.imgur.com/iH57Q8f.png

## Expected Behavior
I assume the program is supposed to have it's own icon, similar to the one in the system tray.

## Current Behavior
The icon is replaced by a generic IcoFX icon.

## Steps to Reproduce
1. Have IcoFX installed
2. Install KeePassXC from 64bit .msi file
3. Notice that the icon is the generic IcoFx icon... O_o

## About Info
KeePassXC - Version 2.4.0
Revision: c51752d

Libraries:
- Qt 5.12.1
- libgcrypt 1.8.4

Operating system: Windows 10 (10.0)
CPU architecture: x86_64
Kernel: winnt 10.0.17763

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Operating system: Windows 10
CPU architecture: 64 bit i7-7600k
Kernel: Idk bro

**Comment by phoerious** [comment]
I think some thing's messed up on your system. We do ship an icon and I have no idea why IcoFX hijacked it. Perhaps try clearing your icon cache or so.

**Comment by Amnesiac9** [comment]
I'll try that, thanks. I couldn't reproduce on another PC so I closed the issue, I'll figure it out since it's my issue and not something wrong with keepass, sorry!

**Comment by sanyarnd** [comment]
I'd like to re-open this issue and following #3292 I have several thoughts:
@phoerious 
1. I can't see why KeepassXС is the only application experiencing this issue, doesn't make sense with dozens applications around. 
2. KeepassXC shortcut isn't "normal", you can't edit target, like on any other shortcut:
![изображение](https://user-images.githubusercontent.com/6544384/59833229-512ac380-934e-11e9-87cf-f751c1848cfe.png)
There is missing "Target Location" value and it might be the cause of the issue.
