### ISSUE TITLE
Publish deb file for 2.4.0 in official PPA

### ISSUE THREAD

**Issue by Najihel** [keepassxreboot/keepassxc#2869]
Hello,

Please could you publish deb file for 2.4.0 release in the PPA https://launchpad.net/~phoerious/+archive/ubuntu/keepassxc ?

Because of the migration of KeePassBrowser keys, the mapping in KeePassXC Browser doesn't work in 2.3.4.

Thanks

Cc @phoerious

**Comment by phoerious** [comment]
I am back from my vacation, so I'll do that today together with the macOS builds.

**Comment by brunob** [comment]
@phoerious have you noticed that some builds failed ? (amd64 + i386 for xenial & trusty)

**Comment by phoerious** [comment]
Xenial has issues with an old GCC version. Trusty will be unsupported.

**Comment by brunob** [comment]
@phoerious thx for the hint :)

**Comment by stdedos** [comment]
> Xenial has issues with an old GCC version. Trusty will be unsupported.

Could you elaborate what is the status with this?
Should `amd64 + i386 for xenial` users wait / try some other means / ... ?
