### ISSUE TITLE
Auto-type Global Hotkey issue in certain windows

### ISSUE THREAD

**Issue by humpalum** [keepassxreboot/keepassxc#2870]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
Keepassxc cant recognize the Autotype hotkey when in certain programms. I didn't have the problem in Debian Stretch, but now after switching to Buster. 
Most of the programms like firefox work just fine. In other ones, like the Terminal or Gedit it cant recognize the Hotkey.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
After hitting the Hotkey, Keepassxc should open the Autotype menu. 

## Current Behavior
[NOTE]: # ( Tell us what actually happens )
After hitting the Hotkey while the Terminal is open, nothing happens.

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1. Setup Hotkey for Autotype
2. Open Terminal Window
3. Hit Hotkey

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )
I guess it has something in common with Debian 10 or Gnome in Debian 10. I tested a few different Hotkey, but the main one i use is "Ctrl + K" which worked fine back when i was on Debian 9 .

These are some programms i tested the hotkey with:

- Terminal  :x:
- gedit  :x:
- evolution  :x:
- slack :heavy_check_mark:
- firefox :heavy_check_mark:
- libre office  :x:

## Debug Info
This is the Debug Info from the Flatpak Version. However, i tested the one from the repos aswell, which had the same outcome.
```
KeePassXC - Version 2.4.0
Distribution: Flatpak

Libraries:
- Qt 5.12.2
- libgcrypt 1.8.4

Operating system: Linux 4.19.0-2-amd64
CPU architecture: x86_64
Kernel: linux 4.19.0-2-amd64

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

```

**Comment by droidmonkey** [comment]
If the local window traps the hotkey than KeePassXC will never see it. I wager a guess that each of those applications is trapping the key combination. We highly, strongly, seriously recommend you make a hotkey combo like "CTRL+SHIFT+K" or "CTRL+ALT+K" because almost no application is going to trap that.

**Comment by humpalum** [comment]
I tried both of your versions. Both didn't work.
Even "Meta + Ctrl + Alt + Shift + K" doesn't work in the terminal.

I also tried other keys then "K" in the combination. It didn't work as well.

**Comment by droidmonkey** [comment]
Closing this as there is not much we can do.

**Comment by schlimmchen** [comment]
This is (somehow) related to Wayland. My global hotkey is `Ctrl + Shift + k`, which is *not* in use by the applications where Auto-Type is broken.

When starting a GNOME session on Wayland I observe the same behavior (Auto-Type working in Brave/Chromium, Firefox, Thunderbird, rdesktop, but not in gnome-terminal, LibreOffice, gedit).

With GNOME on Xorg the global hotkey is received by KeePassXC just fine in any application and Auto-Type can be used.

OS is Debian bullseye amd64. Same on Ubuntu 20.10.
