### ISSUE TITLE
Add ifDevice feature to Auto-Open

### ISSUE THREAD

**Issue by PhilippC** [keepassxreboot/keepassxc#2871]
## Summary
KeeAutoExec functionality has been updated for Keepass2 and Keepass2Android. I suggest that the KeepassXC implementation is updated also to keep best compatibility.

## Context
KeeAutoExec functionality has been added (https://github.com/keepassxreboot/keepassxc/issues/477), but KeeAutoExec has sinced received an update which I have requested and discussed with Dominic in https://sourceforge.net/p/keepass/discussion/329220/thread/509d35a111/?limit=250. (Note: I am the author of KP2A).

The main update is introducing support for an IfDevice field which allows to select which entries should be opened on which devices. This makes sense for local files and also provides good support for mobile apps where paths e.g. to Dropbox files look different. The feature is implemented in Keepass2Android's current beta (https://play.google.com/apps/testing/keepass2android.keepass2android) which will soon be released to stable.
Would be great if KeepassXC would support the IfDevice extension.

## Desired Behavior
If an AutoOpen entry has a field "IfDevice", this field should be respected. Otherwise I am expecting people to complain if they add child databases in Keepass2Android which have the IfDevice field set because they should be restricted to the Android device.

**Comment by droidmonkey** [comment]
Do you have the spec for this IfDevice setting? I cannot find it.

**Comment by PhilippC** [comment]
There is a readme file in https://keepass.info/extensions/v2/keeautoexec/KeeAutoExec-2.3.zip which says:

> **Computer/device ID check.** The custom entry string "IfDevice" (without the quotes) may contain a comma-separated list of computer/device IDs or negated computer/device IDs (with the prefix '!') on which the database is opened automatically. For example, if the string is "Pqr, Xyz", the database is opened automatically only on computers/devices called Pqr or Xyz. If the string is "!Pqr, !Xyz", the database is opened automatically on all computers/devices that are called neither Pqr nor Xyz. On Windows, the computer/NetBIOS name is used as ID; on Linux, the host name is used as ID; on Android, the Android device ID is used.

You can find my implementation on https://github.com/PhilippC/keepass2android/blob/434b7b756bc1166c2f588aecbe11328f110ec488/src/keepass2android/KeeAutoExec.cs#L162 as a reference.

Thanks for considering this!

**Comment by droidmonkey** [comment]
Ugh, another wonky advanced attribute. What is so wrong with using json?? (Not blaming you, just venting)

**Comment by pvalsecc** [comment]
@droidmonkey,
Sadly, the keepass.info documentation says `The custom entry string "IfDevice" (without the quotes) may contain`, but your code looks at `ifDevice`, without the uppercase on the first letter :-(
So this feature, as implemented, is not compatible with Keepass2Android, for example.
