### ISSUE TITLE
[Question] Keepassxc chrome extension: In memory password protection

### ISSUE THREAD

**Issue by dpb657** [keepassxreboot/keepassxc#2874]
[TIP]:  # Is the in memory copy of the password encrypted?
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Current Behavior
I locked my screen and left my computer for a time. Keepassxc is set to lock the datbase on a screen lock. When I came back to my computer I was able to unlock the page I was already on without unlocking the database. My questions are during the time I was away was that page's password in memory unencrypted? Why did the Chrome extension still have access to the password?

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.3.4
Revision: 6fe821c

Libraries:
- Qt 5.9.3
- libgcrypt 1.8.2

Operating system: macOS 10.14
CPU architecture: x86_64
Kernel: darwin 18.2.0

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

Keepassxc chrome extension:  1.3.2 Jan 11 2019

**Comment by droidmonkey** [comment]
This is corrected in the soon-to-be published extension.
