### ISSUE TITLE
Close application after

### ISSUE THREAD

**Issue by LIyoai** [keepassxreboot/keepassxc#2875]
I would like to have a "Close application after x sec".
Like "Clear clipboard" and "Lock database"

With this option the memory will be cleared.
(https://keepassxc.org/blog/2019-02-21-memory-security/)

I'm using KeePassXC 2.3.4 on Windows.

**Comment by droidmonkey** [comment]
Memory clearing will be implemented with #2805. I do not support a feature that exists the application as it is unnecessary.
