### ISSUE TITLE
Keepassxc autotype into parallels vm not working

### ISSUE THREAD

**Issue by Muratthi** [keepassxreboot/keepassxc#2876]
Hello,

I am using KeePassXC and I like it very much. The problem is when I try to use the auto type feature. KeePassXC is installed on the Mac and I am using windows 7 in parallels desktop vm. 
When I try to Autotype the username and the password into the Parallels VM it types but just the characters are just like 

aaaaaaaaaa  aaaaaaaaaaaaaaaaaaaa

Autotyping into a textile which is on the Mac is working like a charm. 

Any help would be appreciated. 

Thank you

**Comment by droidmonkey** [comment]
Duplicate issue: #1833

**Comment by droidmonkey** [comment]
Corrected in 2.7.0 with Virtual typing mode
