### ISSUE TITLE
Password is checked when unlocking the database

### ISSUE THREAD

**Issue by ligyxy** [keepassxreboot/keepassxc#2877]
## Expected Behavior
By checking "Rememver last key filed and security dongles", it should remember that I only use key file without password.

## Current Behavior
In KeePassXC 2.4.0, Password field is always checked on the unlocking page. Thus I have to uncheck it every time since I only use key file. This is also not how it behaves in previous versions.

## Possible Solution
N/A

## Steps to Reproduce
1. Set a database with key file only
2. Check "Rememver last key filed and security dongles"
3. Try to open the database

## Debug Info
KeePassXC - Version 2.4.0
Revision: c51752d

Libraries:
- Qt 5.12.2
- libgcrypt 1.8.4

Operating system: macOS Mojave (10.14)
CPU architecture: x86_64
Kernel: darwin 18.2.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (only unsigned sharing)
- YubiKey
- TouchID

**Comment by droidmonkey** [comment]
In general we should be smarter about the checkboxes. My proposal to fix this is:

1. Start with all checkboxes unchecked
2. If a password is entered, automatically check the password box
3. If a key is selected, automatically check the keyfile box
4. If a Yubikey is inserted _AND_ the user selects a challenge response slot, automatically check the yubikey box

**Comment by 0xpr03** [comment]
Same here with a YubiKey, I click on "refresh", so keepass sees my Stick after pluggin it in.
Then password and challenge-response are checked. You click on ok, keepass asks the yubikey (I accept on the key) and then errors out as I've not provided a valid password. This is kinda annoying and irritating. This worked on 2.2/3 before.

**Comment by 0xpr03** [comment]
Works pretty well, thank you!
