### ISSUE TITLE
Date is now localised since 2.4.0

### ISSUE THREAD

**Issue by danielepolencic** [keepassxreboot/keepassxc#2882]
## Expected Behavior
This is a breaking change from 2.3.
I have an entry for a credit card and its expiry. Before the update, the expire displayed the date as July 2021 at 23:59. Now the date is August 2021 6:59.
My timezone is SGT +8

## Current Behavior
[NOTE]: # ( Tell us what actually happens )
The expiry date is displayed as August 2021 6:59. instead of July 2021 23:59

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )
I didn't see this in the changelog, but perhaps I missed something.
A toggle in the settings with the timezone would be nice.

## Steps to Reproduce
1. Download 2.3 add an entry with expiry on the last day of the month
2. Download 2.4 and open the database. The entry has the wrong date
3.

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )
Kept entering the details wrong for my credit card.

## Debug Info
KeePassXC - Version 2.4.0
Revision: c51752d

Libraries:
- Qt 5.12.2
- libgcrypt 1.8.4

Operating system: macOS Mojave (10.14)
CPU architecture: x86_64
Kernel: darwin 18.2.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (only unsigned sharing)
- YubiKey
- TouchID

Enabled extensions:
- EXTENSIONS

**Comment by droidmonkey** [comment]
This is very likely an artifact from the Clock and TimeInfo classes that were introduced to support better merging / conflict detection. Expiry time uses TimeInfo to set its data. It does this using UTC time (which is correct).

Somehow all of my credit card entries with expirations of dd/mm/yyyy 23:59 all survived the transition. Recommend just resetting your expiry date. There is no code issue as far as I can tell.

**Comment by danielepolencic** [comment]
The date was entered in GMT. But now it's displayed localised in SGT.
How do I check the *real* date in the database?

**Comment by droidmonkey** [comment]
The real date is stored as UTC/GMT/Zulu (whatever you want to refer to it as). You can check this by dumping the XML of your database using the CLI. The date shown to the user is in local time.

**Comment by danielepolencic** [comment]
Can I set the date to always be displayed as UTC without changing the locale?

**Comment by droidmonkey** [comment]
Side note, KDBX 4 dictates storing datetime as a Base64 of the Unix time.

**Comment by droidmonkey** [comment]
We use the computer's locale when showing date/time. You cannot change it within the app.

**Comment by danielepolencic** [comment]
Ok, thanks for clarifying.
