### ISSUE TITLE
Autotype doesn't work on Mac with 2.4.0

### ISSUE THREAD

**Issue by danielepolencic** [keepassxreboot/keepassxc#2883]
## Expected Behavior
Command + V on a Mac focuses on the last open window and enters the autotype sequence

## Current Behavior
It doesn't work. Tried Command + Shift + V but it enters the values in KeePassXC itself.

## Possible Solution
Not sure if this is intentional.

## Steps to Reproduce
1. Select an entry
2. Press Command + V -> nothing happens
3. Press Command + Shift + V the username and password are typed inside the search box for KeePassXC

## Context
The above used to work in 2.3.x

## Debug Info
KeePassXC - Version 2.4.0
Revision: c51752d

Libraries:
- Qt 5.12.2
- libgcrypt 1.8.4

Operating system: macOS Mojave (10.14)
CPU architecture: x86_64
Kernel: darwin 18.2.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (only unsigned sharing)
- YubiKey
- TouchID

**Comment by droidmonkey** [comment]
I couldn't replicate this behavior. Here is my sequence:

1. Have "Notes" and KeePassXC open
2. Focus on "Notes" app for entering text
3. CMD+TAB to KeePassXC
4. Select entry I want to type
5. CMD+SHIFT+V -> switches back to Notes and types entry

Make sure you remove your fingers from the CMD+SHIFT keys relatively fast

**Comment by danielepolencic** [comment]
Cmd + Shift + V does work now 🤔 
I'm not sure why it didn't work before. The only thing I can think of is that the browser extension was given problems as well 🤷‍♂️
Anyway, please ignore this.

**Comment by lollyP** [comment]
This is indeed a bug, which seems to occur _on first use once the app has been opened_, only.

To reproduce the problem, open the app and attempt to autotype a password - the autotype will fail.

To workaround the problem, eg, cmd-tab to browser then cmd-tab back to the KeePassXC app, then reattempt autotype - the autotype will succeed.

**Comment by danielepolencic** [comment]
I can reproduce the above.

**Comment by pixel8383** [comment]
That's happening to me too (MacOS Mojave with KeepassXC 2.4.0).

**Comment by droidmonkey** [comment]
@pixel8383 if auto-type is not working _at all_ then that points to you needing to enable (or disable then enable again) the accessibility settings for KeePassXC to control your computer.

**Comment by rockihack** [comment]
`CMD+SHIFT+V` does not work initially because the `lastActiveApplication` property is nil.
It needs to receive `NSWorkspaceDidDeactivateApplicationNotification` atleast once to work as expected. You might test if `raiseLastActiveWindow` returns false and abort autotype in that case...

https://github.com/keepassxreboot/keepassxc/blob/c66f293f1eec26701de32c6eaa665a59c5e71b66/src/autotype/AutoType.cpp#L217

**Comment by vraravam** [comment]
I had the same problem. My guess is that the new version might have a different sign/key, such that macOS Mojave needs it to be re-authorized in the accessibility settings. Once that was done, it started working for me again. tx @droidmonkey!

**Comment by iryston** [comment]
That's happening to me too (MacOS High Sierra and MacOS Mojave with KeepassXC 2.4.0).
Shortcut "Command + Shift + V" enters the values in KeePassXC search input.
The button "Perform Auto-Type" works as expected.

**Comment by reagle** [comment]
I have this problem. Sometimes it works, sometimes nothing happens, sometimes it types the password into the `Search` box. Resetting accessibility doesn't seem to have done anything.

**Comment by reagle** [comment]
Plus, keepassxc often becomes unresponsive after this failure.

**Comment by sheadovas** [comment]
I have this problem also, btw I don't understand why the hotkey for this action is changed? I would like to change it back to <kbd>Cmd</kbd> + <kbd>V</kbd>..

**Comment by phoerious** [comment]
It's too dangerous next to Ctrl+C and Ctrl+V also has different semantics elsewhere.

**Comment by andreipoe** [comment]
I have Cmd+Shift+V bound to something else. Could we at least have an option to switch back to the old shortcut (Cmd+V)? I'm sure many of us have formed muscle memory by now.

**Comment by droidmonkey** [comment]
We will not be implementing an option. When we get around to custom keyboard shortcuts this will be possible.

**Comment by ritzmann** [comment]
> Plus, keepassxc often becomes unresponsive after this failure.

I think there is something more fundamental going on there. I have had 2.4 going unresponsive on macOS a couple of times now without auto-typing. I don't have a reproducible test case unfortunately, so haven't opened a dedicated issue.
