### ISSUE TITLE
TouchID on Mac is confusing

### ISSUE THREAD

**Issue by danielepolencic** [keepassxreboot/keepassxc#2884]
## Summary
The touchID flag on the main screen is confusing. I always tried to unlock the database using my finger, but it never works. It's unclear when it is activated or not.

## Desired Behavior
The tickbox should be part of the settings. Once enabled, one can unlock the database with a finger. This is consistent with other apps such as KyPass on iOS.

## Possible Solution
1. Move the tickbox to global settings.
2. If enabled, the database can be unlocked with the finger. No password needed.

## Context
It's hard to tell when TouchID is available.

**Comment by droidmonkey** [comment]
Please post comments on Touch ID to #2865
