### ISSUE TITLE
Keepass 2.4 browser integration: Opera

### ISSUE THREAD

**Issue by generic-user** [keepassxreboot/keepassxc#2885]
## Info
Hi, after updating to KeepassXC 2.4, the browser (Opera) integration stopped working. I tried disabling and re enabling. But it does not seem to work anymore.

![image](https://user-images.githubusercontent.com/1516035/54986384-d81c0a00-4fb2-11e9-96c4-18463b9903a4.png)

![image](https://user-images.githubusercontent.com/1516035/54986033-32689b00-4fb2-11e9-913e-d359c5122249.png)

## Debug and version:
```
KeePassXC - Version 2.4.0
Revision: c51752d

Libraries:
- Qt 5.12.1
- libgcrypt 1.8.4

Operating system: Windows 10 (10.0)
CPU architecture: x86_64
Kernel: winnt 10.0.16299

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
```
## What i expect
Was working fine with previous version: 2.3.4-Win64

Thanks for looking into this.

**Comment by varjolintu** [comment]
Is the extension connected to KeePassXC? If not, Connect does nothing.

**Comment by generic-user** [comment]
I thought the function of the "connect" button was to connect to the database. How do I force it to connect?

**Comment by varjolintu** [comment]
The popup doesn't connect automatically (yet). You have to make sure the popup has the Connect button visible. If it reads Reload (or Reconnect), you are not connected to KeePassXC.

**Comment by generic-user** [comment]
Thank, for some reason the connection failed.
After reinstalling the plugin, the connection popup  pupped up, and a connection was made.
