### ISSUE TITLE
xml key parsing error - invalid regexp 2.4.0

### ISSUE THREAD

**Issue by arturbac** [keepassxreboot/keepassxc#2886]
Change in regexp causing valid xml keys not to load in 2.4.0 and further parsing them as binary hash

regexp pattern definition from 2.4.0 - invalid
src/core/Tools.cpp

constexpr auto pattern = R"(^(?:[a-z0-9+]{4})*(?:[a-z0-9+]{3}=|[a-z0-9+]{2}==)?$)";
QRegExp regexp(pattern, Qt::CaseInsensitive, QRegExp::RegExp2);

and from 2.3.4 - working corectly
QRegExp regexp("^(?:[a-z0-9+/]{4})*(?:[a-z0-9+/]{3}=|[a-z0-9+/]{2}==)?$",
                   Qt::CaseInsensitive, QRegExp::RegExp2);

it looks like author of change from string to raw string  misinterpreted / as start of escape sequence \ and removed /.

**Comment by droidmonkey** [comment]
Already got a fix PR for 2.4.1, thanks.
