### ISSUE TITLE
Add compilation flag to disable updates check

### ISSUE THREAD

**Issue by Germano0** [keepassxreboot/keepassxc#2887]
## Summary
Add compilation flag to disable updates check

## Desired Behavior
As Fedora maintainer I don't want users to get popups of new updates since I am the only one that manages the updates in our platform

## Possible Solution
Add a compilation flag to disable updates check

**Comment by Polynomial-C** [comment]
+1 from me as Gentoo package maintainer for the same reason.

**Comment by droidmonkey** [comment]
I will fix this and move the popups into the message bar.

**Comment by droidmonkey** [comment]
Fixed in #2968
