### ISSUE TITLE
Tools: Delete icons which are not used

### ISSUE THREAD

**Issue by xopez** [keepassxreboot/keepassxc#2892]
## Summary
A function among the tools to delete unused icons to save disk space.

## Desired Behavior
A button/Menu button which deletes custom icons which are not in any entry.

## Possible Solution
I think it would be the best if it's under Tools → `Delete unused icons`

## Context
It shrinks the db a bit and you don't have to manually delete not needed icons.

**Comment by droidmonkey** [comment]
This is duplicate of #2110
