### ISSUE TITLE
Problems with multiple Keeshare imports in one database

### ISSUE THREAD

**Issue by alankeny** [keepassxreboot/keepassxc#2895]
One of my databases will not import correctly with Keeshare, but only while another database is imported.

## Expected Behavior
I usually have three databases open in KeepassXC: Home, Work1, and Work2.  I want to use Keeshare to create a new database that imports the three databases into top-level groups.  Each database should appear in its own top-level group called Home, Work1, and Work2.

## Current Behavior

When I import Home first everything shows up as I would expect under the Home group.  When I import either Work1 or Work2 next, the contents of the Home group disappears.  I know the data is still in the database, because I can open Home directly and see everything.

If I import Work1 or Work2 first, when I import Home, nothing shows up in the Home group.  Again I know the data is still there, because I can open Home directly and see everything..

## Possible Solution
Home, Work1, and Work2 are normally synchronized with the Nextcloud client, while the new database is not synchronized.  Stopping the Nextcloud client and setting up the new database from scratch did not change anything.

Copying all three databases into separate folders on my desktop and creating the new database also in a separate folder does appear to work.  Keeping all four databases in one folder results in an endless loop of importing as soon as the second Keeshare import is added to the new database.

For each test I removed all of the entries from Tools > Settings > Keeshare > Imported Certificates.  I answered "Always" as each Keeshare import was added.  I don't understand why the location of the database on the local file system impacts the import so much.  For reference here are the absolute file locations that result in the entries in the Home group disappearing when Work1 or Work2 are imported into their own top-level groups:

````
/home/myusername/Documents/Home/Keepass/Home.kdbx    # Synced in NextCloud
/home/myusername/Documents/Work1/Keepass/Work1.kdbx  # Synced in NextCloud
/home/myusername/Documents/Work2/Keepass/Work2.kdbx  # Synced in NextCloud
/home/myusername/Documents/Keepass/Passwords.kdbx    # Not Synced, Local Only
````

## Steps to Reproduce
See the current behavior.  The steps can occur in either order.  When another database is setup for import with Keeshare, the data from the Keeshare imported home database will not show up.

## Context
I tried using the synchronize option in Keeshare first, but I noticed that my Home database was getting blanked out.  I now believe that this happened after I imported Work1, and the Home database appeared to be empty.  I have not lost any data since I limited my testing to imports, but I eventually want to get Keeshare synchronization working with all three databases.

## Debug Info
KeePassXC - Version 2.4.0

Libraries:
- Qt 5.9.5
- libgcrypt 1.8.1

Operating system: Linux Mint 19.1
CPU architecture: x86_64
Kernel: linux 4.15.0-46-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (only unsigned sharing)
- YubiKey

**Comment by droidmonkey** [comment]
Ping @ckieschnick

**Comment by ckieschnick** [comment]
@alankeny I've got some ideas what causes this behavior, but I need some more context.

Do you "Import only" your shares, or do you use the "Synchronize" feature? 
Do you have the "Autosave" on every edit active? 

Currently I think it could be an interaction between the "Synchonize" feature with "Autosave" and the file watcher which is responsible to notify the plugin about shared files. So an import leads to an autosave leading to a new import. 

I'm not entirely sure about the vanishing entries in your groups. Do they have the same origin database (same UUID) and did you possibly delete those entries from Work1 or Work2?

**Comment by alankeny** [comment]
> Do you "Import only" your shares, or do you use the "Synchronize" feature?

To simplify the testing and avoid potential data loss, I am using the "Import only" option for now.

> Do you have the "Autosave" on every edit active?

Yes, the "Autosave" option is enabled.  I will run the tests again with this option disabled.

> Currently I think it could be an interaction between the "Synchonize" feature with "Autosave" and the file watcher which is responsible to notify the plugin about shared files. So an import leads to an autosave leading to a new import.

That would certainly explain the endless repeated imports I've seen.  Does the database format matter for Keeshare?  While checking some of the other settings, I noticed that my databases are using the key derivation function AES-KDF (KDBX 3.1) rather than the recommended Argon2 (KDBX 4).

> I'm not entirely sure about the vanishing entries in your groups. Do they have the same origin database (same UUID) and did you possibly delete those entries from Work1 or Work2?

I don't know where to check this.  Under each database's root group > edit group > properties, I found a Uuid.  All of these values are unique.  I haven't deleted anything from Work1 or Work2.  I've only been adding new groups to a new local database and setting each group to Keeshare import the databases from Work1 and Work2 into each new group.  When I close the new local database with the Keeshare groups, and open Work1 or Work2 directly, the root group and all of the entries are still there.  Let me know if I need to check the Uuids in a different location, or if you need any other information.

**Comment by ckieschnick** [comment]
Are you able to create a minimal setup with test databases which yields the same behavior? I tried the setup with "all in one folder" and it worked as I expected (I didn't set up Nextcloud).

I think about creating a build which logs more information about the KeeShare plugin (especially the merging/file watching part logging share sources and UUIDs) next week. Would you check the bug with this debug release?

**Comment by alankeny** [comment]
> Are you able to create a minimal setup with test databases which yields the same behavior? I tried the setup with "all in one folder" and it worked as I expected (I didn't set up Nextcloud).

All of my "all in one folder" testing has been away from Nextcloud.  I just tried to recreate the repeating import problem with three databases in one folder, and I wasn't able to.  That was with autosave enabled, because I wanted to see if the problem went away after I disabled autosave.  Since I wasn't able to recreate the problem, I'm not going to pursue this further until I can make it happen again reliably.

> I think about creating a build which logs more information about the KeeShare plugin (especially the merging/file watching part logging share sources and UUIDs) next week. Would you check the bug with this debug release?

I also created a new Password database without NextCloud running.  I created groups in the new database for each database I wanted to import as I described in my first post.  Home Keeshare imported OK.  When I Keeshare imported Work1, every entry in the Home group disappeared except the most recent one.  When I closed the Password database and opened Home and Work1 directly, all of the entries were visible.  Since I can still recreate this consistently, I'd like to check this with your debug release.  Just let me know what I need to do.

**Comment by ckieschnick** [comment]
@alankeny I've created a hotfix branch https://github.com/hicknhack-software/keepassxc/tree/hotfix/2895-diagnostic-release. Currently I've some trouble creating a build which you can use - but in case you are able to build yourself, you may check if the build fixes your problem. In case the problem still exists, please start KeePassXC in debug mode and have a look at the log messages. I'll try to provide a real build as soon as my other work allows me to do so.

**Comment by ckieschnick** [comment]
Finally I was able to create a build (https://github.com/hicknhack-software/keepassxc/releases/tag/2.4.0.dev.share.diagnostic) which I can share with you. I assume you used linux, therefore I created a zip (already with some fixes which may cause the strange behavior). Please start AppRun from console I try to reproduce the bug (when the error occurred, please provide the console messages).

**Comment by alankeny** [comment]
I'm using Linux, but my system is based on Ubuntu 18.04 LTS.  The AppRun is giving errors looking for shared libraries that are newer than the ones on my system.  For example I have libqrencode.so.3, but it's looking for libqrencode.so.4, and I have libargon2.so.0, but it's looking for libargon2.so.1.  Unfortunately I won't have time to build this myself for a few weeks, but I'll get to it as soon as I can.
