### ISSUE TITLE
From v2.4.0 requests to unlock already unlocked database

### ISSUE THREAD

**Issue by winterwolf** [keepassxreboot/keepassxc#2898]
## The Issue

There were no similar problems in the previous versions and after update to 2.4.0, when I start my keepass from autostart shell bash script like `keepassxc ~/passwords.kdbx --keyfile ~/passwords.key`, I have 2 issues:

1. It starts with 2 tabs opened - first tab ask me to enter password, second tab shows my database (so I have to close the first tab every time I start it, it doesn't make sense).

2. Icon in tray is gray, like database is blocked, but it is not. If I simply open settings menu and press ok button, without changing anything, the icon will update and become normal.

## Debug Info

KeePassXC - Version 2.4.0

Libraries:
- Qt 5.9.5
- libgcrypt 1.8.1

Operating system: Ubuntu 18.04.2 LTS
CPU architecture: x86_64
Kernel: linux 4.15.0-46-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (only unsigned sharing)
- YubiKey

**Comment by droidmonkey** [comment]
Duplicate and there is already a fix for 2.4.1 pending.
