### ISSUE TITLE
Jump to searchfield when KeepassXC becomes focus

### ISSUE THREAD

**Issue by MegaV0lt** [keepassxreboot/keepassxc#2900]
[TIP]:  # ( Provide a general summary of the feature in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Summary
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
Would be nice to have an option to activate the searchfield when KeepassXc becomes focus

## Desired Behavior
[NOTE]: # ( Tell us how the new feature should work, be specific )
for Examle: When i click the icon to bring the program to front the search should be active by default, so i just can start typing

## Possible Solution
[NOTE]: # ( Not required, but suggest ideas on how to implement the addition or change )
add an option in the config to set "Activate searchfield" when changed from minimized to focus

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
I come from KeePass2 (needs mono). there i can select that behavior and i like it.

**Comment by SVilgelm** [comment]
+1 for the option, but it should be default behavior. I want to keep the current behavior, because I can copy username (cmd+b), use cmt+tab to switch to another app, paste the username, use cmd+tab, copy password (cmd+c) and etc... But with yours behavior I will need to use a mouse or tab to copy a password, because the focus will be on the search field instead of an entry. So, only optional.

**Comment by MegaV0lt** [comment]
Well as i said it would be nice to have it as an option that users can activate in the settings.

**Comment by droidmonkey** [comment]
This is an ultra specific setting that not a lot of users would opt for. IMO it should not be implemented. We are already fast approach "settings creep". KeePass2 is very much in settings creep, I believe it has nearly 80-100 available settings without any additional plugins.

Unless there is a large support for this workflow, I am inclined to not implement it.

**Comment by h-h-h-h** [comment]
I'd use that setting.

@droidmonkey: If your worry for settings creep is only regarding an overwhelming GUI, KeePassXC could adopt a similar approach as Firefox with its `about:config` page for advanced settings.

**Comment by bac0n** [comment]
When typing in keepassxc and no input is focused should activate search, Tab should take you to first search result and single Esc clears search (like it is now) and double Esc clears search and goes back to previous focus.
