### ISSUE TITLE
Question: What are the grayed entries in the entries list?

### ISSUE THREAD

**Issue by stdedos** [keepassxreboot/keepassxc#2901]
_In the same way as https://github.com/keepassxreboot/keepassxc/issues/1724 was a question-issue_

I've noticed that there are some grayed entries (apologies, screenshot is too complicated to be "cleaned up"). They are not expired or anything obvious that comes to mind (I have an expired entry, which coincidentially is also grayed too).

I open KeePassXC from time to time, so I am not sure if this is one setting or another that I've configured myself or an "innate feature". _I have been trying to migrate from KeePass to KeePassXC (my main issue is no support for custom sorting --> just found the issue here https://github.com/keepassxreboot/keepassxc/issues/2295)_

Trying to Google-search the documentation doesn't help.

**Comment by phoerious** [comment]
They are probably references to other entries. Please have a look at their contents.

**Comment by stdedos** [comment]
They  _are indeed_ references. At least, _some of their fields reference another entry_.

What is the basis behind this?

There are some fields that are references only partially: One entry has a `username`, and the other one is `{ref:username}@domain.org`

**Comment by droidmonkey** [comment]
It's your database, you must have set this up at some point. I'm confused by your question.

**Comment by stdedos** [comment]
I am trying to understand why entries are grayed, and the reason behind it.

It is a KeePass DB I've loaded to KeePassXC, and the entries contain in one way or another references. However, some of them are partial references (e.g. {REF:username}@domain.com) - which means, they might not be entirely bound to their originating entry. Even if they are, however, there is no way to figure out what depends on what, since there is no "go to parent entry" functionality, or implicit tree-like grouping.
