### ISSUE TITLE
Main window tab order is broken

### ISSUE THREAD

**Issue by reagle** [keepassxreboot/keepassxc#2903]
## Expected Behavior

Previously, I'd type `super+f; amazon; tab` and I'd be at the first found entry for amazon. 

## Current Behavior

Now it requires three or four tabs for the cursor to be at the found entries.

## Debug Info

KeePassXC - Version 2.4.0
Revision: c51752d

Libraries:
- Qt 5.12.2
- libgcrypt 1.8.4

Operating system: macOS Mojave (10.14)
CPU architecture: x86_64
Kernel: darwin 18.5.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (only unsigned sharing)
- YubiKey
- TouchID

**Comment by reagle** [comment]
It looks like you are now supposed to use down arrow?

**Comment by droidmonkey** [comment]
Tab order is broken, down arrow was always the preferred method.

**Comment by reagle** [comment]
Okay, will close.
