### ISSUE TITLE
Safari browser integration

### ISSUE THREAD

**Issue by Pedrober** [keepassxreboot/keepassxc#2905]
KeePassXC for Mac OS has very limited functionality without Safari browser integration. Please put it in your roadmap.

## Desired Behavior
Automatic filling of passwords in Safafi.

**Comment by droidmonkey** [comment]
Not possible, Safari does not support the proper extension protocol.

**Comment by Pedrober** [comment]
I see. Anyhow, there was a plugin for KeePass (Passafari), years ago.

**Comment by georgesnow** [comment]
@Pedrober if you are interested I wrote an AppleScript originally for Macpass that can be used with Fastscripts for autofilling safari based on url. I modified it to work with strongbox (Mac keepass app). If this something you would find helpful I could try making 3rd one for use with keepassxc. 


https://github.com/georgesnow/MPSafariAF

**Comment by Pedrober** [comment]
Dear George,
Thank you very much for your message. Don’t worry. In the end, I moved to Enpass because it works with Safari…
Best wishes,
Manuel

**Comment by sfjeep** [comment]
_"KeePassXC for Mac OS has very limited functionality without Safari browser integration."_

KeePassXC works great on the Mac with Firefox, Chome, and Chromium for me. There **are** other browsers for macOS besides Safari.

**Comment by f1xmAn** [comment]
> _"KeePassXC for Mac OS has very limited functionality without Safari browser integration."_
> 
> KeePassXC works great on the Mac with Firefox, Chome, and Chromium for me. There **are** other browsers for macOS besides Safari.

Safari **is** highly convenient browser for macOS that should have integration with KeepPassXC.

**Comment by georgesnow** [comment]
I have started working on Safari extension using the newer specs by Apple. It is based on the old HTTP support. I had geared it originally towards MacPass’s plugin, but it would work with any application that uses HTTP spec. That would means also there is some possibility it could be modified to work with KPXC native messaging. 

It is not finished and it only has some basic javascript for filling/testing and the basic POST request for credentials. The handling of the encryption, multiple sites, etc ... has not been worked on or developed.

**Comment by lorenzodp** [comment]
> I have started working on Safari extension using the newer specs by Apple. It is based on the old HTTP support. I had geared it originally towards MacPass’s plugin, but it would work with any application that uses HTTP spec. That would means also there is some possibility it could be modified to work with KPXC native messaging.
> 
> It is not finished and it only has some basic javascript for filling/testing and the basic POST request for credentials. The handling of the encryption, multiple sites, etc ... has not been worked on or developed.

I do encourage you to go ahead, please! Safari is the best browser so far in my opinion, way more efficient and less battery consuming than the others. Making an app for OSX browsers I don't understand why Safari is not considered as one of them.

**Comment by danielnaaman** [comment]
I really hope to see something like this happening, even some sort of workaround just to make it work.

**Comment by droidmonkey** [comment]
Apple announced safari will support web extension in a future brain at WWDC. When it does we'll test our current extension and done.

**Comment by georgesnow** [comment]
Just as note i test the old Http legacy extension and it works.

**Comment by rps64** [comment]
@georgesnow which one?

**Comment by georgesnow** [comment]
@rps64 

https://github.com/smorks/keepasshttp-connector

**Comment by georgesnow** [comment]
forgot to. add I tried the newer keepassXC extension (native messaging) as well. It builds and loads, but I couldn't get it to connect to the KeePassXC app. I tried some basic troubleshooting with no luck.

**Comment by droidmonkey** [comment]
You will need to manually add the native messaging config file to get it to work.

**Comment by matthiasschroder** [comment]
Please note that it is not so much a question whether Safari is convenient or not, it is a sad fact that many Apple pages only work with Safari. So many people are forced to use Safari at least for part of their work, whether they like it or not. KeePassXC Safari integration would really help a lot.

**Comment by zestysoft** [comment]
@droidmonkey  Apparently web extensions are supported now?

`Safari web extensions are available in macOS 11 and later, and in macOS 10.14.6 or 10.15.6 with Safari 14 installed.`
Source: https://developer.apple.com/documentation/safariservices/safari_web_extensions

Or is "Safari web extensions" not the same as the "web extensions" you referred to?  They did have this qualifier:

```Important

You implement Safari web extensions as macOS app extensions to provide a safe and secure distribution and usage model. ```

I've noticed that uBlock Origin doesn't have support in Safari, and that the only ad blocker I could find works as a macOS app behind the scenes.

**Comment by droidmonkey** [comment]
This is tracked over on the browser extension issue board. We are working on the safari version now.

**Comment by zestysoft** [comment]
Is that this?
Support Password Manager API in macOS Mojave #2496
https://github.com/keepassxreboot/keepassxc/issues/2496

**Comment by droidmonkey** [comment]
No but that one also needs to be closed
