### ISSUE TITLE
Indeterminate order of databases when opening KeePassXC

### ISSUE THREAD

**Issue by jgindin** [keepassxreboot/keepassxc#2906]
## Expected Behavior
Every time I start KeePassXC, the tabs representing databases should be in the same order.

## Current Behavior
Each time I start KeePassXC, the tabs are not in the same order and a tab for a database which was *not* the most recently opened is selected. E.g., sometimes db1 is first and sometimes it is second. This is particularly bad when you don't notice, and can't figure out why your password isn't unlocking the database.

## Possible Solution
Always use the same order. This is what previous versions did.

## Steps to Reproduce
1. Have multiple databases which you have opened.
2. Start KeePassXC and notice the tab order.
3. Exit and restart KeePassXC -- chances are the tabs are in a different order and/or a different database is selected.

## Context
Frustrating to try and open a database, knowing the password is correct, only to figure out later that you're using the password for a different database.

## Debug Info
KeePassXC - Version 2.4.0

Libraries:
- Qt 5.11.1
- libgcrypt 1.8.3

Operating system: Ubuntu 18.10
CPU architecture: x86_64
Kernel: linux 4.18.0-16-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

**Comment by droidmonkey** [comment]
Fixed in 2.4.1
