### ISSUE TITLE
MSI GPG signing key expired

### ISSUE THREAD

**Issue by pedro7** [keepassxreboot/keepassxc#2907]
## Expected Behavior
I expected not to get:
> gpg: Note: This key has expired!

## Current Behavior

> $ gpg --verify *.sig
> gpg: assuming signed data in 'KeePassXC-2.4.0-Win64.msi'
> gpg: Signature made 19 de mar de 2019 23:15:42 HGMT
> gpg:                using RSA key C1E4CBA3AD78D3AFD894F9E0B7A66F03B59076A8
> gpg: Good signature from "KeePassXC Release <release@keepassxc.org>" [unknown]
> gpg: Note: This key has expired!
> Primary key fingerprint: BF5A 669F 2272 CF43 24C1  FDA8 CFB4 C216 6397 D0D2
>      Subkey fingerprint: C1E4 CBA3 AD78 D3AF D894  F9E0 B7A6 6F03 B590 76A8

## Possible Solution
New sig

## Steps to Reproduce
1. Download KeePassXC-2.4.0-Win64.msi.sig
2. Download KeePassXC-2.4.0-Win64.msi
3. run gpg --verify *.sig

## Context
My paranoia level had increased due to the release being not published on the front page for some time (or was published and the deleted). As such, minor quirks such as this one are relevant.

**Comment by phoerious** [comment]
Please refresh the public key from the key servers. They were updated in January.
