### ISSUE TITLE
Crash when starting [MacOS]

### ISSUE THREAD

**Issue by j0w0** [keepassxreboot/keepassxc#2908]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Expected Behavior
Application to open

## Current Behavior
Application crashes on boot

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )

## Steps to Reproduce
1. Download latest version
2. Open app

## Context
Running MacOS on El Capitan - 10.11.6

## Debug Info
Can't get, here's system crash error
Process:               KeePassXC [10523]
Path:                  /Volumes/VOLUME/KeePassXC.app/Contents/MacOS/KeePassXC
Identifier:            org.keepassx.keepassxc
Version:               ???
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           KeePassXC [10523]
User ID:               501

Date/Time:             2019-03-29 10:29:25.725 +0000
OS Version:            Mac OS X 10.11.6 (15G22010)
Report Version:        11
Anonymous UUID:       probably dont need this

Time Awake Since Boot: 2000 seconds

System Integrity Protection: disabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (Code Signature Invalid)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

kernel messages:

VM Regions Near 0x7fff7a5d20a8 (cr2):
    __LINKEDIT             00007fff6b10e000-00007fff6b123000 [   84K] r--/rwx SM=COW  /usr/lib/dyld
--> Submap                 00007fff70000000-00007fff80000000 [256.0M] r--/rwx SM=PRV  process-only VM submap
    unused shlib __DATA    00007fff77909000-00007fff7bead000 [ 69.6M] rw-/rw- SM=COW  system shared lib __DATA not used by this process

Thread 0 Crashed:
0   dyld                          	0x00007fff6b09b000 _dyld_start + 0

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x000000000000000d  rbx: 0x0000000000000000  rcx: 0x0000000000000000  rdx: 0x0000000000000000
  rdi: 0x0000000000000000  rsi: 0x0000000000000000  rbp: 0x0000000000000000  rsp: 0x00007fff54205c48
   r8: 0x0000000000000000   r9: 0x0000000000000000  r10: 0x0000000000000000  r11: 0x0000000000000000
  r12: 0x0000000000000000  r13: 0x0000000000000000  r14: 0x0000000000000000  r15: 0x0000000000000000
  rip: 0x00007fff6b09b000  rfl: 0x0000000000000201  cr2: 0x00007fff7a5d20a8
  
Logical CPU:     0
Error Code:      0x020000f4
Trap Number:     133

Binary Images:
    0x7fff6b09a000 -     0x7fff6b0d1a47  dyld (???) <6B9CD3BA-2D60-3629-A0CB-AB810F55E8DD> /usr/lib/dyld

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 1059
    thread_create: 201
    thread_set_state: 0

Libraries:
Unknown

Operating system: MacOS
CPU architecture: Intel
Kernel: MacOS 10.11.6?

Enabled extensions:
- Unknown

**Comment by j0w0** [comment]
2.3.4 opens and works fine, but 2.4.0 and up (betas) crash

**Comment by phoerious** [comment]
The 2.4 build needs macOS 10.12 or higher. If you want to use it on 10.11, you have to compile it yourself, unfortunately. We cannot support 10.11 and Mojave at the same time, since Qt does not support it. This was listed in our changelog.
