### ISSUE TITLE
A Way to Disable the Ctrl+v Shortcut

### ISSUE THREAD

**Issue by temporaryaccount** [keepassxreboot/keepassxc#2909]
I want a way to disable the Ctrl+v shortcut because sometimes I fat-finger Ctrl+b as Ctrl+v, and I don't want any automatic form pasting or submissions from KeePassXC's part. Thank you.

## Summary

A way to disable the Ctrl+v shortcut

**Comment by phoerious** [comment]
Ctrl+V has been remapped to Ctrl+Shift+V in 2.4.0. Please upgrade your installation.
