### ISSUE TITLE
KeePassXC Version 2.4.0 leaks memory on macOS

### ISSUE THREAD

**Issue by olmannisto** [keepassxreboot/keepassxc#2910]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
No memory leaks reported by 'leaks' tool

## Current Behavior
[NOTE]: # ( Tell us what actually happens )
leaks[2994]: Process 2975 is not debuggable.
Due to security restrictions, leaks cannot show memory contents of restricted processes.

Process:         KeePassXC [2975]
Path:            /Applications/KeePassXC.app/Contents/MacOS/KeePassXC
Load Address:    0x100716000
Identifier:      org.keepassx.keepassxc
Version:         2.4.0 (???)
Code Type:       X86-64
Parent Process:  ??? [1]

Date/Time:       2019-03-28 06:34:47.784 -0700
Launch Time:     2019-03-28 06:30:17.477 -0700
OS Version:      Mac OS X 10.14 (18A391)
Report Version:  7
Analysis Tool:   /usr/bin/leaks

Physical footprint:         40.9M
Physical footprint (peak):  289.4M
----

leaks Report Version: 4.0
Process 2975: 275639 nodes malloced for 29683 KB
Process 2975: 45 leaks for 4992 total leaked bytes.

    45 (4.88K) << TOTAL >>

      10 (2.34K) ROOT CYCLE: <FITNode 0x600003abb330> [112]
         3 (1.77K) _node + 64 --> ROOT CYCLE: <TPublishedFoldersNode 0x600002d5e100> [256]
            CYCLE BACK TO <FITNode 0x600003abb330> [112]
            1 (1.50K) ROOT CYCLE: <std::__1::__shared_ptr_emplace<std::__1::shared_ptr<TEnableObserverAdaptor<TNodeObserver, TCustomNode> > MakeShared<TEnableObserverAdaptor<TNodeObserver, TCustomNode> >()::MakeInstanceEnabler, std::__1::allocator<std::__1::shared_ptr<TEnableObserverAdaptor<TNodeObserver, TCustomNode> > MakeShared<TEnableObserverAdaptor<TNodeObserver, TCustomNode> >()::MakeInstanceEnabler> > 0x7fea2f118200> [1536]
            1 (16 bytes) 0x6000013e77a0 [16]
         4 (240 bytes) _node + 72 --> ROOT CYCLE: 0x6000031fee40 [80]
            2 (96 bytes) ROOT CYCLE: 0x6000013ea6e0 [16]
               1 (80 bytes) ROOT CYCLE: 0x6000031fee90 [80]
                  CYCLE BACK TO <FITNode 0x600003abb330> [112]
            1 (64 bytes) <std::__1::__shared_ptr_emplace<ExternalRegistration, std::__1::allocator<ExternalRegistration> > 0x6000008bd280> [64]
         2 (240 bytes) _node + 48 --> ROOT CYCLE: 0x6000028d1420 [224]
            CYCLE BACK TO <FITNode 0x600003abb330> [112]
            1 (16 bytes) 0x6000013eb220 [16]

      7 (640 bytes) ROOT CYCLE: <FITNode 0x600003abc460> [112]
         2 (272 bytes) _node + 48 --> ROOT CYCLE: 0x6000028c1c00 [224]
            CYCLE BACK TO <FITNode 0x600003abc460> [112]
            1 (48 bytes) 0x600001ea9d70 [48]
         4 (256 bytes) _node + 72 --> ROOT CYCLE: 0x6000032bed00 [80]
            2 (112 bytes) ROOT CYCLE: 0x600001726140 [32]
               1 (80 bytes) ROOT CYCLE: 0x6000032bed50 [80]
                  CYCLE BACK TO <FITNode 0x600003abc460> [112]
            1 (64 bytes) <std::__1::__shared_ptr_emplace<ExternalRegistration, std::__1::allocator<ExternalRegistration> > 0x6000008d8f00> [64]

      7 (608 bytes) ROOT CYCLE: <FITNode 0x600003ab4150> [112]
         4 (256 bytes) _node + 72 --> ROOT CYCLE: 0x6000031ea620 [80]
            2 (112 bytes) ROOT CYCLE: 0x600001726f60 [32]
               1 (80 bytes) ROOT CYCLE: 0x6000032cf570 [80]
                  CYCLE BACK TO <FITNode 0x600003ab4150> [112]
            1 (64 bytes) <std::__1::__shared_ptr_emplace<ExternalRegistration, std::__1::allocator<ExternalRegistration> > 0x6000008e9880> [64]
         2 (240 bytes) _node + 48 --> ROOT CYCLE: 0x6000028d47e0 [224]
            CYCLE BACK TO <FITNode 0x600003ab4150> [112]
            1 (16 bytes) 0x6000013eb100 [16]

      1 (64 bytes) ROOT LEAK: 0x600000870640 [64]
      1 (64 bytes) ROOT LEAK: 0x6000008709c0 [64]
      1 (64 bytes) ROOT LEAK: 0x600000870d40 [64]
      1 (64 bytes) ROOT LEAK: 0x600000871900 [64]
      1 (64 bytes) ROOT LEAK: 0x600000871c00 [64]
      1 (64 bytes) ROOT LEAK: 0x600000871f80 [64]
      1 (64 bytes) ROOT LEAK: 0x600000872880 [64]
      1 (64 bytes) ROOT LEAK: 0x6000008728c0 [64]
      1 (64 bytes) ROOT LEAK: 0x600000873080 [64]
      1 (64 bytes) ROOT LEAK: 0x600000873640 [64]
      1 (64 bytes) ROOT LEAK: 0x600000873ac0 [64]
      1 (64 bytes) ROOT LEAK: 0x600000875900 [64]
      1 (64 bytes) ROOT LEAK: 0x600000875c80 [64]
      1 (64 bytes) ROOT LEAK: 0x600000876740 [64]
      1 (64 bytes) ROOT LEAK: 0x600000876b80 [64]
      1 (64 bytes) ROOT LEAK: 0x600000876f00 [64]
      1 (64 bytes) ROOT LEAK: 0x600000877b00 [64]
      1 (64 bytes) ROOT LEAK: 0x600000877e40 [64]
      1 (64 bytes) ROOT LEAK: 0x600000878c00 [64]
      1 (64 bytes) ROOT LEAK: 0x60000087a580 [64]
      1 (64 bytes) ROOT LEAK: 0x60000087eb80 [64]

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1. Install keepassxc using Homebrew (https://brew.sh)
2. Open KeePassXC and create new database
3. Run 'leaks KeePassXC' from Terminal

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.4.0
Revision: c51752d

Libraries:
- Qt 5.12.2
- libgcrypt 1.8.4

Operating system: macOS Mojave (10.14)
CPU architecture: x86_64
Kernel: darwin 18.0.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (only unsigned sharing)
- YubiKey
- TouchID

**Comment by phoerious** [comment]
This leak report is not very helpful, because it shows nothing. It is also very likely that if anything is leaked at all, then its third-party libraries that leak on exit, which is totally normal. Please try again without KeePassXC's memory protection.

**Comment by olmannisto** [comment]
Process:         KeePassXC [7701]
Path:            /Users/USER/*/KeePassXC.app/Contents/MacOS/KeePassXC
Load Address:    0x103c42000
Identifier:      org.keepassx.keepassxc
Version:         2.4.0-snapshot (???)
Code Type:       X86-64
Parent Process:  bash [7353]

Date/Time:       2019-03-31 23:16:36.766 -0700
Launch Time:     2019-03-31 23:13:24.467 -0700
OS Version:      Mac OS X 10.14.5 (18F96h)
Report Version:  7
Analysis Tool:   /Applications/Xcode.app/Contents/Developer/usr/bin/leaks
Analysis Tool Version:  Xcode 10.2 (10E125)

Physical footprint:         44.4M
Physical footprint (peak):  292.7M
----

leaks Report Version: 4.0
Process 7701: 319727 nodes malloced for 32612 KB
Process 7701: 36 leaks for 4224 total leaked bytes.

    36 (4.12K) << TOTAL >>

      10 (2.34K) ROOT CYCLE: <std::__1::__shared_ptr_emplace<std::__1::shared_ptr<TEnableObserverAdaptor<TNodeObserver, TCustomNode> > MakeShared<TEnableObserverAdaptor<TNodeObserver, TCustomNode> >()::MakeInstanceEnabler, std::__1::allocator<std::__1::shared_ptr<TEnableObserverAdaptor<TNodeObserver, TCustomNode> > MakeShared<TEnableObserverAdaptor<TNodeObserver, TCustomNode> >()::MakeInstanceEnabler> > 0x7fc728add800> [1536]
         CYCLE BACK TO <std::__1::__shared_ptr_emplace<std::__1::shared_ptr<TEnableObserverAdaptor<TNodeObserver, TCustomNode> > MakeShared<TEnableObserverAdaptor<TNodeObserver, TCustomNode> >()::MakeInstanceEnabler, std::__1::allocator<std::__1::shared_ptr<TEnableObserverAdaptor<TNodeObserver, TCustomNode> > MakeShared<TEnableObserverAdaptor<TNodeObserver, TCustomNode> >()::MakeInstanceEnabler> > 0x7fc728add800> [1536]
         9 (864 bytes) ROOT CYCLE: <TPublishedFoldersNode 0x7fc72abb20a0> [256]
            CYCLE BACK TO <std::__1::__shared_ptr_emplace<std::__1::shared_ptr<TEnableObserverAdaptor<TNodeObserver, TCustomNode> > MakeShared<TEnableObserverAdaptor<TNodeObserver, TCustomNode> >()::MakeInstanceEnabler, std::__1::allocator<std::__1::shared_ptr<TEnableObserverAdaptor<TNodeObserver, TCustomNode> > MakeShared<TEnableObserverAdaptor<TNodeObserver, TCustomNode> >()::MakeInstanceEnabler> > 0x7fc728add800> [1536]
            7 (592 bytes) ROOT CYCLE: <FITNode 0x7fc72abb1e50> [112]
               4 (240 bytes) _node + 72 --> ROOT CYCLE: 0x7fc72abb2370 [80]
                  2 (96 bytes) ROOT CYCLE: 0x7fc72ac4b070 [16]
                     1 (80 bytes) ROOT CYCLE: 0x7fc72ac3f800 [80]
                  1 (64 bytes) <std::__1::__shared_ptr_emplace<ExternalRegistration, std::__1::allocator<ExternalRegistration> > 0x7fc72abb23c0> [64]
               2 (240 bytes) _node + 48 --> ROOT CYCLE: 0x7fc72abb1ec0 [224]
                  1 (16 bytes) 0x7fc72ac65580 [16]
            1 (16 bytes) 0x7fc72a598c10 [16]

      7 (608 bytes) ROOT CYCLE: <FITNode 0x7fc72ab32e00> [112]
         4 (256 bytes) _node + 72 --> ROOT CYCLE: 0x7fc72ab333c0 [80]
            2 (112 bytes) ROOT CYCLE: 0x7fc72ac5f6b0 [32]
               1 (80 bytes) ROOT CYCLE: 0x7fc72a8ea840 [80]
                  CYCLE BACK TO <FITNode 0x7fc72ab32e00> [112]
            1 (64 bytes) <std::__1::__shared_ptr_emplace<ExternalRegistration, std::__1::allocator<ExternalRegistration> > 0x7fc72ab32d00> [64]
         2 (240 bytes) _node + 48 --> ROOT CYCLE: 0x7fc72ab32e70 [224]
            CYCLE BACK TO <FITNode 0x7fc72ab32e00> [112]
            1 (16 bytes) 0x7fc72a8f94c0 [16]

      1 (64 bytes) ROOT LEAK: 0x7fc727dd01c0 [64]  length: 52  "/private/var/db/CVMS/cvmsCodeSignObjHLlnjtiOCucX3M9P"
      1 (64 bytes) ROOT LEAK: 0x7fc72ad28d40 [64]  length: 52  "/private/var/db/CVMS/cvmsCodeSignObjTMvNuJ1M5vOfQYnU"
      1 (64 bytes) ROOT LEAK: 0x7fc72ad74030 [64]  length: 52  "/private/var/db/CVMS/cvmsCodeSignObjD4f4CECQWVYJbr81"
      1 (64 bytes) ROOT LEAK: 0x7fc72adc2fe0 [64]  length: 52  "/private/var/db/CVMS/cvmsCodeSignObjrSUGhXRC1jA5fR0B"
      1 (64 bytes) ROOT LEAK: 0x7fc72ae3b940 [64]  length: 52  "/private/var/db/CVMS/cvmsCodeSignObjEWK1ZOddhHRrpkfq"
      1 (64 bytes) ROOT LEAK: 0x7fc72ae3f8d0 [64]  length: 52  "/private/var/db/CVMS/cvmsCodeSignObjakiq3F6ZM6Z78aVp"
      1 (64 bytes) ROOT LEAK: 0x7fc72ae3f9d0 [64]  length: 52  "/private/var/db/CVMS/cvmsCodeSignObjrFRwZHr59JiEiKHO"
      1 (64 bytes) ROOT LEAK: 0x7fc72ae6bf40 [64]  length: 52  "/private/var/db/CVMS/cvmsCodeSignObjS0GwuyGvIJdtEfX6"
      1 (64 bytes) ROOT LEAK: 0x7fc72ae6da60 [64]  length: 52  "/private/var/db/CVMS/cvmsCodeSignObjvUSwwva7tD6Ll4hh"
      1 (64 bytes) ROOT LEAK: 0x7fc72ae6f2a0 [64]  length: 52  "/private/var/db/CVMS/cvmsCodeSignObjS8i5oNTfnuPwlvmU"
      1 (64 bytes) ROOT LEAK: 0x7fc72ae8aae0 [64]  length: 52  "/private/var/db/CVMS/cvmsCodeSignObjTgJ2CFPRL0Zg006R"
      1 (64 bytes) ROOT LEAK: 0x7fc72ae8d9f0 [64]  length: 52  "/private/var/db/CVMS/cvmsCodeSignObjD52A7znZgunRGH7u"
      1 (64 bytes) ROOT LEAK: 0x7fc72ae8ee80 [64]  length: 52  "/private/var/db/CVMS/cvmsCodeSignObjT331k1acjqzLILzJ"
      1 (64 bytes) ROOT LEAK: 0x7fc72aea32c0 [64]  length: 52  "/private/var/db/CVMS/cvmsCodeSignObjybKwl6xgexRlgKTm"
      1 (64 bytes) ROOT LEAK: 0x7fc72aeaf250 [64]  length: 52  "/private/var/db/CVMS/cvmsCodeSignObjSczEvNqqckGKsNQz"
      1 (64 bytes) ROOT LEAK: 0x7fc72aec3b70 [64]  length: 52  "/private/var/db/CVMS/cvmsCodeSignObjq1P52u2U3TVz1h0x"
      1 (64 bytes) ROOT LEAK: 0x7fc72aec8630 [64]  length: 52  "/private/var/db/CVMS/cvmsCodeSignObjoRzEGaWh7Tps47Pv"
      1 (64 bytes) ROOT LEAK: 0x7fc72aec86c0 [64]  length: 52  "/private/var/db/CVMS/cvmsCodeSignObjJlX21wbCzzp5RS4i"
      1 (64 bytes) ROOT LEAK: 0x7fc72aed24d0 [64]  length: 52  "/private/var/db/CVMS/cvmsCodeSignObjyVHt81PoTinsdgTA"

**Comment by olmannisto** [comment]
On another computer immediately when I open KeePassXC, leaks reports:
Process 16200: 4625 leaks for 1271120 total leaked bytes.

And huge list similar to this:
56 (17.0K) ROOT LEAK: <SecTrust 0x7fcec2a89180> [144]
         31 (8.44K) 0x7fcec4020150 [64]
            30 (8.38K) 0x7fcebf6938b0 [48]
               28 (8.25K) <SecTrust 0x7fcec401f2b0> [144]
                  13 (5.12K) <NSArray 0x7fcebf607c10> [16]
                     12 (5.11K) __strong _object --> <SecCertificate 0x7fcec41a5ce0> [624]
                        6 (2.50K) <SecCertificate 0x7fcec41a6930> [592]
                           2 (1.53K) 0x7fcec41a5880 [32]
                              1 (1.50K) 0x7fcebe1b9400 [1536]
                           1 (320 bytes) <Security::CssmClient::CLImpl 0x7fcec41a6420> [320]
                           2 (80 bytes) 0x7fcec41a5fe0 [64]
                              1 (16 bytes) 0x7fcec4199cf0 [16]
                        1 (1.50K) <CFData 0x7fcebe1b7c00> [1536]
                        1 (144 bytes) <CFData 0x7fcec41a5af0> [144]
                        1 (144 bytes) <CFData 0x7fcec41a5f50> [144]
                        1 (128 bytes) 0x7fcec41a5b80 [128]
                        1 (96 bytes) <CFData 0x7fcec41a5420> [96]
                  7 (2.56K) <NSMutableArray 0x7fcec2a89900> [48]
                     6 (2.52K) <NSMutableArray (Storage) 0x7fcec2a58e50> [16]
                        5 (2.50K) <SecCertificate 0x7fcec010c000> [2048]
                           1 (144 bytes) <CFData 0x7fcec2a89990> [144]
                           1 (144 bytes) <CFData 0x7fcec2a89a20> [144]
                           1 (128 bytes) 0x7fcec2a89ab0 [128]
                           1 (96 bytes) <CFData 0x7fcec2a89930> [96]
                  3 (192 bytes) 0x7fcec2a7baf0 [64]
                     2 (128 bytes) 0x7fcec2a886a0 [48]
                        1 (80 bytes) 0x7fcec2a89710 [80]
                  1 (128 bytes) <OS_dispatch_queue 0x7fcec4020820> [128]
                  1 (80 bytes) 0x7fcec2a89310 [80]
                  1 (16 bytes) <NSArray 0x7fcebf60a970> [16]
                  1 (16 bytes) <NSDate 0x7fcec40208a0> [16]
               1 (80 bytes) 0x7fcec40207d0 [80]
         13 (5.14K) <NSArray 0x7fcec2a48350> [16]
            12 (5.12K) __strong _object --> <SecCertificate 0x7fcec41a5060> [624]
               6 (2.50K) <SecCertificate 0x7fcec41a55f0> [592]
                  2 (1.53K) 0x7fcec41a5cc0 [32]
                     1 (1.50K) 0x7fcebe1b8200 [1536]
                  1 (320 bytes) <Security::CssmClient::CLImpl 0x7fcec41a6020> [320]
                  2 (80 bytes) 0x7fcec41a4850 [64]
                     1 (16 bytes) 0x7fcec419ee90 [16]
               1 (1.50K) <CFData 0x7fcebe1b6a00> [1536]
               1 (160 bytes) 0x7fcec41a5550 [160]
               1 (144 bytes) <CFData 0x7fcec41a54c0> [144]
               1 (144 bytes) <CFData 0x7fcec41a5c30> [144]
               1 (80 bytes) <CFData 0x7fcec41a52d0> [80]
         7 (3.08K) <NSMutableArray 0x7fcec401ce50> [48]
            6 (3.03K) <NSMutableArray (Storage) 0x7fcebf6096e0> [16]
               5 (3.02K) <SecCertificate 0x7fcebf8d0c00> [2560]
                  1 (160 bytes) 0x7fcec401f710 [160]
                  1 (144 bytes) <CFData 0x7fcec401fe80> [144]
                  1 (144 bytes) <CFData 0x7fcec401ff10> [144]
                  1 (80 bytes) <CFData 0x7fcec401fe30> [80]
         1 (128 bytes) <OS_dispatch_queue 0x7fcec2a88620> [128]
         1 (80 bytes) 0x7fcec401fde0 [80]
         1 (16 bytes) <NSArray 0x7fcec2a7af70> [16]
         1 (16 bytes) <NSDate 0x7fcec2a40ed0> [16]

      54 (16.8K) ROOT LEAK: <SecTrust 0x7fcec2a895d0> [144]
         29 (8.28K) 0x7fcec401dba0 [64]
            28 (8.22K) 0x7fcec4006e10 [48]
               26 (8.09K) <SecTrust 0x7fcec401e600> [144]
                  13 (5.11K) <NSArray 0x7fcebf6059a0> [16]
                     12 (5.09K) __strong _object --> <SecCertificate 0x7fcec41a0fc0> [624]
                        6 (2.50K) <SecCertificate 0x7fcec41a1230> [592]
                           2 (1.53K) 0x7fcec419f840 [32]
                              1 (1.50K) 0x7fcebe1b3600 [1536]
                           1 (320 bytes) <Security::CssmClient::CLImpl 0x7fcec41a1480> [320]
                           2 (80 bytes) 0x7fcec419d390 [64]
                              1 (16 bytes) 0x7fcec41a28f0 [16]
                        1 (1.50K) <CFData 0x7fcebe1b1e00> [1536]
                        1 (144 bytes) <CFData 0x7fcec419edb0> [144]
                        1 (144 bytes) <CFData 0x7fcec41a27e0> [144]
                        1 (128 bytes) 0x7fcec41a2870 [128]
                        1 (80 bytes) <CFData 0x7fcec419f920> [80]
                  7 (2.55K) <NSMutableArray 0x7fcec41a2290> [48]
                     6 (2.50K) <NSMutableArray (Storage) 0x7fcec29ed9e0> [16]
                        5 (2.48K) <SecCertificate 0x7fcebe199200> [2048]
                           1 (144 bytes) <CFData 0x7fcec41a2310> [144]
                           1 (144 bytes) <CFData 0x7fcec41a23a0> [144]
                           1 (128 bytes) 0x7fcec41a2430 [128]
                           1 (80 bytes) <CFData 0x7fcec41a22c0> [80]
                  1 (128 bytes) <OS_dispatch_queue 0x7fcec401fd00> [128]
                  1 (80 bytes) 0x7fcec41633b0 [80]
                  1 (64 bytes) 0x7fcec413c190 [64]
                  1 (16 bytes) <NSArray 0x7fcebf606fc0> [16]
                  1 (16 bytes) <NSDate 0x7fcec401fd80> [16]
               1 (80 bytes) 0x7fcec401e490 [80]
         13 (5.33K) <NSArray 0x7fcec2a75700> [16]
            12 (5.31K) __strong _object --> <SecCertificate 0x7fcec419f9a0> [624]
               6 (2.50K) <SecCertificate 0x7fcec419eb60> [592]
                  2 (1.53K) 0x7fcec419fc50 [32]
                     1 (1.50K) 0x7fcebe1b2400 [1536]
                  1 (320 bytes) <Security::CssmClient::CLImpl 0x7fcec419d250> [320]
                  2 (80 bytes) 0x7fcec419fc10 [64]
                     1 (16 bytes) 0x7fcec4197d40 [16]
               1 (1.50K) <CFData 0x7fcebe1b0c00> [1536]
               1 (256 bytes) <CFData 0x7fcec419f6c0> [256]
               1 (256 bytes) <CFData 0x7fcec41a0a80> [256]
               1 (128 bytes) 0x7fcec419f7c0 [128]
               1 (80 bytes) <CFData 0x7fcec41a0c10> [80]
         7 (2.77K) <NSMutableArray 0x7fcec4008d10> [48]
            6 (2.72K) <NSMutableArray (Storage) 0x7fcebf605f60> [16]
               5 (2.70K) <SecCertificate 0x7fcebf8cda00> [2048]
                  1 (256 bytes) <CFData 0x7fcec401e7b0> [256]
                  1 (256 bytes) <CFData 0x7fcec401f010> [256]
                  1 (128 bytes) 0x7fcec401e8b0 [128]
                  1 (80 bytes) <CFData 0x7fcec401e760> [80]
         1 (128 bytes) <OS_dispatch_queue 0x7fcec2a88d00> [128]
         1 (80 bytes) 0x7fcec401e710 [80]
         1 (16 bytes) <NSArray 0x7fcec2a48f30> [16]
         1 (16 bytes) <NSDate 0x7fcec2a49890> [16]

      64 (16.0K) ROOT LEAK: <SecTrust 0x7fcec2e64a50> [144]
         39 (11.1K) <NSMutableArray 0x7fcec2a7dce0> [48]
            38 (11.0K) <NSMutableArray (Storage) 0x7fcec2a6aec0> [16]
               37 (11.0K) <SecCertificate 0x7fcec00e3000> [2048]
                  29 (8.42K) 0x7fcec2a87b60 [240]
                     28 (8.19K) <SecTrust 0x7fcec2a7a9b0> [144]
                        13 (5.09K) <NSArray 0x7fcec2a4b900> [16]
                           12 (5.08K) __strong _object --> <SecCertificate 0x7fcec418daf0> [624]
                              6 (2.50K) <SecCertificate 0x7fcec418cb20> [592]
                                 2 (1.53K) 0x7fcec418da90 [32]
                                    1 (1.50K) 0x7fcebe1a5200 [1536]
                                 1 (320 bytes) <Security::CssmClient::CLImpl 0x7fcec418cd70> [320]
                                 2 (80 bytes) 0x7fcec418e820 [64]
                                    1 (16 bytes) 0x7fcec417b730 [16]
                              1 (1.50K) <CFData 0x7fcebe1a2e00> [1536]
                              1 (160 bytes) 0x7fcec418d7e0 [160]
                              1 (128 bytes) <CFData 0x7fcec418da10> [128]
                              1 (128 bytes) <CFData 0x7fcec418e7a0> [128]
                              1 (64 bytes) <CFData 0x7fcec418dd60> [64]
                        7 (2.53K) <NSMutableArray 0x7fcec2e64ae0> [48]
                           6 (2.48K) <NSMutableArray (Storage) 0x7fcec2e6e320> [16]
                              5 (2.47K) <SecCertificate 0x7fcebe8c0000> [2048]
                                 1 (160 bytes) 0x7fcec2e6a5c0 [160]
                                 1 (128 bytes) <CFData 0x7fcec2e6a4c0> [128]
                                 1 (128 bytes) <CFData 0x7fcec2e6a540> [128]
                                 1 (64 bytes) <CFData 0x7fcec2e5dc20> [64]
                        3 (192 bytes) 0x7fcec2e5dcb0 [64]
                           2 (128 bytes) 0x7fcec2e68150 [48]
                              1 (80 bytes) 0x7fcec2e676b0 [80]
                        1 (128 bytes) <OS_dispatch_queue 0x7fcec2a88840> [128]
                        1 (80 bytes) 0x7fcec2e6d840 [80]
                        1 (16 bytes) <NSArray 0x7fcec2a695b0> [16]
                        1 (16 bytes) <NSDate 0x7fcec2a888c0> [16]
                  4 (240 bytes) <NSMutableArray 0x7fcec2a7ab60> [48]
                     3 (192 bytes) <NSMutableArray (Storage) 0x7fcec2a6fa20> [16]
                        2 (176 bytes) <NSURL 0x7fcec2a87c50> [112]
                           1 (64 bytes) _clients --> <CFString 0x7fcec2a7d340> [64]
                  1 (144 bytes) <CFData 0x7fcec2a87a40> [144]
                  1 (144 bytes) <CFData 0x7fcec2a87ad0> [144]
                  1 (80 bytes) <CFData 0x7fcec2a7ab10> [80]
         17 (4.39K) <NSArray 0x7fcec2e6d290> [16]
            16 (4.38K) __strong _object --> <SecCertificate 0x7fcec418bce0> [624]
               6 (1.94K) <SecCertificate 0x7fcec418b720> [592]
                  2 (992 bytes) 0x7fcec418adc0 [32]
                     1 (960 bytes) 0x7fcec418d060 [960]
                  1 (320 bytes) <Security::CssmClient::CLImpl 0x7fcec418b390> [320]
                  2 (80 bytes) 0x7fcec418ad80 [64]
                     1 (16 bytes) 0x7fcec418a4e0 [16]
               1 (1.00K) <CFData 0x7fcebe19aa00> [1024]
               4 (240 bytes) <NSMutableArray 0x7fcec41874a0> [48]
                  3 (192 bytes) <NSMutableArray (Storage) 0x7fcec418b130> [16]
                     2 (176 bytes) <NSURL 0x7fcec418a8a0> [112]
                        1 (64 bytes) _clients --> <CFString 0x7fcec418bfe0> [64]
               1 (240 bytes) 0x7fcec418b040 [240]
               1 (144 bytes) <CFData 0x7fcec418a450> [144]
               1 (144 bytes) <CFData 0x7fcec418bf50> [144]
               1 (80 bytes) <CFData 0x7fcec418bbc0> [80]
         3 (192 bytes) 0x7fcec2a7d4c0 [64]
            2 (128 bytes) 0x7fcec2a86640 [48]
               1 (80 bytes) 0x7fcec2a7c010 [80]
         1 (128 bytes) <OS_dispatch_queue 0x7fcec2e6c090> [128]
         1 (80 bytes) 0x7fcec2a7aac0 [80]
         1 (16 bytes) <NSArray 0x7fcec2e6be30> [16]
         1 (16 bytes) <NSDate 0x7fcec2e6c110> [16]

**Comment by droidmonkey** [comment]
That is all OS level code. You are seeing leaks from injected system code for code signing and other crap.
