### ISSUE TITLE
change icon naming convention

### ISSUE THREAD

**Issue by marcbone** [keepassxreboot/keepassxc#2911]
I am writing this issue to inform you that the developer from the Ubuntu Yaru theme suggests to use the -symbolic suffix for the KeepassXC Action Icons (for example change "document-open" to "document-open-symbolic") since this is the new style.

The Original comment is [here](https://github.com/ubuntu/yaru/issues/1294) and [here](https://github.com/ubuntu/yaru/pull/1296) is a pull request with more info.

**Comment by droidmonkey** [comment]
Can you point to where this has become the "new convention"?

**Comment by marcbone** [comment]
Please dont ask me. I am just the messenger :see_no_evil:

**Comment by droidmonkey** [comment]
For future reference, Adwaita introduced symbolic icons using the -symbolic suffix. However, they are absolutely not forcing a new convention. From their readme:

> Icons follow the naming specification, but have a -symbolic suffix, so only applications specifically looking up these symbolic icons will render them. If a -symbolic icon is missing, the app will fall back to the regular name.

**Comment by phoerious** [comment]
If anything would introduce a new convention, it's freedesktop.org.
