### ISSUE TITLE
as of 2.4.0 only first of multiple databases unlocks with --pw-stdin

### ISSUE THREAD

**Issue by jkt628** [keepassxreboot/keepassxc#2914]
## Expected Behavior
before 2.4.0 specifying multiple databases on the command line and providing ordered passwords to --pw-stdin unlocked all the databases.

## Current Behavior
as of 2.4.0 specifying multiple databases on the command line and providing ordered passwords to --pw-stdin unlocks only the first database.

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1. in _Tools_ / _Settings_ turn off **Remember last databases** and **Load previous databases on startup** so database order is provided by command line.
1. quit keepassxc.
1. use a method similar to https://github.com/keepassxreboot/keepassxc/utils/keepassx-kwallet to launch keepassxc.

## Context
this is a regression.

## Debug Info
KeePassXC - Version 2.4.0

Libraries:
- Qt 5.11.3
- libgcrypt 1.8.4

Operating system: Fedora 29 (Twenty Nine)
CPU architecture: x86_64
Kernel: linux 5.0.4-200.fc29.x86_64

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (only unsigned sharing)
- YubiKey

**Comment by droidmonkey** [comment]
Duplicate and fixed in 2.4.1 branch

**Comment by jkt628** [comment]
branches release/2.4.1 and develop fail on Linux and MacOS.

**Comment by phoerious** [comment]
No, they build just fine.

https://ci.keepassxc.org/viewType.html?buildTypeId=KeepassXC_MacOS&branch_KeepassXC=release%2F2.4.1&tab=buildTypeStatusDiv&guest=1

https://ci.keepassxc.org/viewType.html?buildTypeId=KeepassXC_UbuntuLinux&branch_KeepassXC=%3Cdefault%3E&tab=buildTypeStatusDiv&guest=1

**Comment by droidmonkey** [comment]
Sorry I should have read the issue more closely. This is a legit problem.
