### ISSUE TITLE
"Show TOTP QR Code" generates incorrect otpauth string for entry names that contain slash

### ISSUE THREAD

**Issue by Valentin-N** [keepassxreboot/keepassxc#2915]
## Current Behavior
I have several entries where the title contains a slash e.g. "Google / X". I noticed I could not import the TOTP code for these entries into andOTP on Android using QR codes displayed in KeePassXC. When I try to read the TOTP QR code using Barcode Scanner on Android, I get invalid data. If I replace the slash with a hyphen (e.g. "Google - X"), I get valid data again. I notice `period` and `digits` have what seem to be invalid values. Examples below:

Broken ("Google / X"):
```
otpauth://totp/Google%2030F%20X:X?secret=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX&period=6&digits=%5&issuer=Google%2030F%20X
```

Working ("Google - X"):
```
otpauth://totp/Google%20-%20X:X?secret=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX&period=30&digits=6&issuer=Google%20-%20X
```

## Expected Behavior
I expect that TOTP QR codes export correct data regardless of title or username values. If there's an inherent limitation related to special characters, an obvious warning should be printed when trying to export the affected TOTP QR codes.

## Steps to Reproduce
1. Create a new entry with title "Google / X" and username "X".
2. Set up TOTP by pasting "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX" into the key field
3. Show TOTP QR Code
4. Try to read it via andOTP or any similar app

## Debug Info
KeePassXC - Version 2.4.0
Distribution: Flatpak

Libraries:
- Qt 5.12.2
- libgcrypt 1.8.4

Operating system: Linux 4.15.0-46-generic
CPU architecture: x86_64
Kernel: linux 4.15.0-46-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

**Comment by droidmonkey** [comment]
That's really strange, looks like / is not being properly url encoded.

**Comment by droidmonkey** [comment]
As you can see we already call into a url encoder provided by Qt:

https://github.com/keepassxreboot/keepassxc/blob/d7660dad3774ee5192e3ce1728cb4945b1e834dc/src/totp/totp.cpp#L126-L133

I am going to say this is a Qt bug at this time.

**Comment by droidmonkey** [comment]
I see what the problem is... the arguments are replaced in the QString 1 by 1 and when a '/' is encoded that is %47 and then %4 is replaced by the step.

https://github.com/keepassxreboot/keepassxc/blob/d7660dad3774ee5192e3ce1728cb4945b1e834dc/src/totp/totp.cpp#L126-L133
