### ISSUE TITLE
Database cannot be opened

### ISSUE THREAD

**Issue by uuuu1234** [keepassxreboot/keepassxc#2918]
## Expected Behavior
Open the database.

## Current Behavior
Since the update to version 2.4 KeepassXC won't open the database giving the following error message: 
"Unable to open the database:
Error while reading the database: Wrong key or database file is corrupt."

## Debug Info
KeePassXC - Version 2.4.0

Libraries:
- Qt 5.9.5
- libgcrypt 1.8.1

Operating system: Linux Mint 19.1
CPU architecture: x86_64
Kernel: linux 4.18.0-16-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (only unsigned sharing)
- YubiKey

**Comment by droidmonkey** [comment]
Are you using a key file? If so this is a known issue that will be fixed in 2.4.1

**Comment by uuuu1234** [comment]
Yes, I am. Sorry, that I have not realized that the issues was raised already. I guess the only work-around to access my database right now is to go back to an older version?

**Comment by droidmonkey** [comment]
That, or you can try creating a new key for your database that does not include a '/' in it.
