### ISSUE TITLE
Snap version 2.4 opens database read only

### ISSUE THREAD

**Issue by jamdo63** [keepassxreboot/keepassxc#2922]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Expected Behavior
Software opens database read/write

## Current Behavior
My database opens read only on the snap version.  When I install the deb from the Ubuntu store the database opens read/write

## Steps to Reproduce
1, Open database
2.  Database is read only

## Debug Info
KeePassXC - Version 2.4.0
Revision: c51752d
Distribution: Snap

Libraries:
- Qt 5.9.5
- libgcrypt 1.8.1

Operating system: Ubuntu Core 18
CPU architecture: x86_64
Kernel: linux 4.18.0-16-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

**Comment by jamdo63** [comment]
Just realized the deb version from the Ubuntu store that opens files correctly is version 2.3.4.  The snap version is 2.4

**Comment by droidmonkey** [comment]
Where are you trying to open the database from the snap? Snaps are very fickle about the filesystem

**Comment by jamdo63** [comment]
Thanks for the tip.  That is the issue.  The file is in a subdirectory of the home directory.  This subdirectory is also being synced to google drive with Insync via a soft link to the directory.  I don't know why a soft link to the directory should matter but:
1.  When I copy the file to the documents folder it is opened correctly as read/write.
2. A copy made to the original folder with a different name is opened read only.

**Comment by droidmonkey** [comment]
The soft link probably points to somewhere outside the home folder or in a hidden folder which snap cannot write to.

**Comment by jamdo63** [comment]
That would be logical but is not the case.
The link points TO the directory where the keepass database resides, a subdirectory of home. "home\bin\App_Data\"
The link to bin resides in (home\Insync) which is synced with Google Drive by the program Insync.
If I copy the database to home\Insync where the link resides it opens read/write.

**Comment by jamdo63** [comment]
I agree this is likely a wacky Snap directory issue rather than a keepassxc bug so it makes sense to close it.  Thank you for your helpful input.
