### ISSUE TITLE
Generate a password through passphrase 

### ISSUE THREAD

**Issue by skypce** [keepassxreboot/keepassxc#2924]
Hi, will be great if you can implement something like this:
https://miclave.cl/

the idea is that you in input enter a memorable password, using hash like sha1sum or md5 you can recreate exactly match password each time that you want. Better that a random password that you have no idea how to recreate. Thanks.

**Comment by phoerious** [comment]
I don't know what you mean. Could you explain this a little more? We do support passphrases already and MD5 doesn't sound like something you wanna hear in combination with passwords.

**Comment by skypce** [comment]
Sure, by example you have this in a bash console.
echo -n "password" | md5sum |cut -c 1-32 | base91 | cut -c 1-32
When you use a generator like shasum or md5sum with words you can have same hash if you retype "password" word by example. It is like when you use a shasum for verify the authenticity of a file but using words. Having the same hash you can encode applying base64, base91 or ascii85 algorythm after and you will have same "password" if you repeat the process. It is more easy to remember a simple password that build a complex password and if you input same simple password again it rebuild the same password generated before. Cheers.

**Comment by droidmonkey** [comment]
This doesn't provide any security in addition to just using the plain text password.

**Comment by skypce** [comment]
Sure, will be great if you implement it for your "Password generator" section of the app. So like a QR Code for can read passwords from mobile phones. Thanks.
