### ISSUE TITLE
Allow resizing of entry icons (favicon and standard)

### ISSUE THREAD

**Issue by ronnocnave** [keepassxreboot/keepassxc#2926]
## Summary
On my screen, the standard and downloaded favicon icons appear to be too small. They should be adjustable, and the default size shown should at least be the size of a favicon as it appears on a browser tab.

## Desired Behavior
Icon sizes are adjustable to allow for easy viewing on different hardware

## Possible Solution
Provide a slider or drop-down button to allow for multiple icon size options

## Context
Having adjustable icon sizes would speed-up selecting an entry, as it can be found visually quicker by recognizing the icon (standard generic assigned or downloaded favicon), rather than reading through the text.

**Comment by droidmonkey** [comment]
Our text search is pretty awesome at pairing down your entries. The problem with increasing the size of the icons is that _everything_ needs to increase proportionally. I do agree they are a little small, but they are the same size as keepass presents and allow for a nice compact ui.
