### ISSUE TITLE
Keepassxc crashes (segfault) when trying to change key-file only

### ISSUE THREAD

**Issue by solsticedhiver** [keepassxreboot/keepassxc#2927]
I have a keepassxc db (kdbx) locked with a password and a key-file.

In 2.3.2, when you wanted to change the password or the key-file, you had to specify the 2, them being different or not.

The new GUI in keepasxc 2.4.0 would lead us to believe one can only change the key-file without changing the password.

This does not work and keepasxc crashes as soon as you hit OK.

This works if you specify both a password and a (new) key-file

To reproduce, open a db locked with both password+key-file and attempt to change only the key-file, then hit OK => crash (segfault)

Operating system: Ubuntu Linux  18.10
CPU architecture: x86_64
Kernel: 4.18.0-16-generic

Enabled extensions:
- none

**Comment by phoerious** [comment]
It's a known bug and fixed in 2.4.1 which is due this week.
