### ISSUE TITLE
Allow open kdbx file from https Url

### ISSUE THREAD

**Issue by bugfixx** [keepassxreboot/keepassxc#2928]
We use nextcloud in our company and the kdbx is accessible via url. Windows user can open the kdbx via url in Keepass Version 2.41

Please also build the support for KeepassXC.

Thank you
Peter

**Comment by droidmonkey** [comment]
This was discussed at length in #868. If you are talking about just downloading the database over HTTPS, then you can do that through a web browser. If you mean WebDAV, that is something completely different.
