### ISSUE TITLE
Unsharp tray icon Ubuntu 18.04

### ISSUE THREAD

**Issue by AJJLagerweij** [keepassxreboot/keepassxc#2929]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )
My keepassxc, as intended, closes to the system tray. The icon does however look blurry.
This does not make it unusable, but it would be more beautiful when the item would be sharp.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
The expected behavior is that the item tray icon would be sharp, even in high resolution screens.
When running the program in windows the systemtray icon is sharper when using the same machine.

## Current Behavior
[NOTE]: # ( Tell us what actually happens )
Both the locked and unlocked item look bury, as show in the screenshot below.
![image](https://user-images.githubusercontent.com/31255888/55405066-8dbdfe80-5559-11e9-9095-962c5d924f77.png)

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )
It might be that the current icon is pixel based or compressed.
Having the icon as a vector image (such as .svg) might solve the issue already.

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1. Install KeePassXC Snap from the Ubuntu store
2. Make sure that the system tray icon is activated

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )
No major impact on use.

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.4.0
Revision: c51752d
Distribution: Snap

Libraries:
- Qt 5.9.5
- libgcrypt 1.8.1

Operating system: Ubuntu Core 18
CPU architecture: x86_64
Kernel: linux 4.19.0-041900-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

**Comment by michaelblyons** [comment]
Can the tray icons, at least optionally, use "1-bit color" (i.e. just be an alpha layer) and take advantage of `setIsMask(true)`?

**Comment by wolframroesler** [comment]
Here's the KeePassXC icon in the middle of some other icons in the system tray and dock of elementary OS 5.1 (Hera). The others are crisp but the KeePassXC one is blurry. And, this is the KeePassXC version that uses SVG icons exclusively (#475/#4066).

![Screenshot from 2019-12-27 16-28-41](https://user-images.githubusercontent.com/25565229/71522691-0920c680-28c6-11ea-9158-99b42f4b8d41.png)

![Screenshot from 2019-12-27 16-24-41](https://user-images.githubusercontent.com/25565229/71522567-931c5f80-28c5-11ea-95a2-346bf2b16dd7.png)

But it even looks fuzzy in the tray menu. Maybe the SVG needs some rework to make it scale better to small numbers of pixels?

![Screenshot from 2019-12-27 16-30-19](https://user-images.githubusercontent.com/25565229/71522792-7cc2d380-28c6-11ea-9ced-78d280965366.png)

**Comment by droidmonkey** [comment]
Are you sure its drawing from your development version? Make sure ALL other installs are cleaned from your computer. Ot could be preferring what is in /usr/local/share

**Comment by wolframroesler** [comment]
I've got no other version installed except the AppImage, and there's no KeePassXC-related stuff in /usr/local/share, so I suppose it's coming from the version I built. But who knows what kind of caching is going on behind the scenes.

**Comment by phoerious** [comment]
Try replacing the icon with something else. If that something is blurry as well, we got a problem somewhere. I noticed the awkward looks of our icon as well. Even if it were sharp, it looks somewhat out of place.

**Comment by droidmonkey** [comment]
All icons are now SVG or 256x256 PNG for the application icon.

**Comment by wolframroesler** [comment]
For the record, with the latest develop version the icon is crisp and clear in my dock (elementary OS Hera). Thanks to whoever fixed it.

![Screenshot from 2020-04-25 02 21 50](https://user-images.githubusercontent.com/25565229/80266349-aab0fc80-869b-11ea-870c-75ff5d4c73f5.png)
