### ISSUE TITLE
Browser integration does not work with snap package on Debian buster

### ISSUE THREAD

**Issue by vasyugan** [keepassxreboot/keepassxc#2930]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Expected Behavior
After running the snap helper script, browser integration should be working just as on Ubuntu

## Current Behavior
The browser extensions for Firefox and chrome say 
`Message encryption failed. Is KeePassXC running?
`even though the file org.keepassxc.keepassxc_browser.json has been installed in ~/.mozilla/native-messaging-hosts   for firefox and also in the respective directories of Chrome and tor-browser.

## Possible Solution
I have none. 

## Steps to Reproduce
1. On debian buster, install keepassxc via snap (apt install snap && snap install keepassxc)
2. download and run keepassxc helper script for snap to configure it for firefox 
3. launch keepassxc and firefox  or chrome

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )

have to use the appimage instead which is not a big issue, just that it is not installed system wide 

## Debug Info

KeePassXC - Version 2.4.0
Revision: c51752d
Distribution: Snap

Libraries:
- Qt 5.9.5
- libgcrypt 1.8.1

Operating system: Ubuntu Core 18
CPU architecture: x86_64
Kernel: linux 4.19.0-4-amd64

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

**Comment by droidmonkey** [comment]
See https://github.com/keepassxreboot/keepassxc/issues/2890

If you can help nail down a reason why the helper script is not working 100% on Debian Buster, that would be very useful.

**Comment by vasyugan** [comment]
> See #2890
> 
> If you can help nail down a reason why the helper script is not working 100% on Debian Buster, that would be very useful.

The symptoms described in the other report seem different, because I find that the path is actually correct. The json file is identical to that on another notebook running Ubuntu. Yet, while it works on the latter, it doesn't on the former. Here are the contents:

`{
    "name": "org.keepassxc.keepassxc_browser",
    "description": "KeePassXC integration with native messaging support",
    "path": "/snap/bin/keepassxc.proxy",
    "type": "stdio",
    "allowed_extensions": [
        "keepassxc-browser@keepassxc.org"
    ]
}
~        `

**Comment by droidmonkey** [comment]
If you change the path in the json to ```/usr/bin/snap/keepassxc.proxy``` does it work?

**Comment by vasyugan** [comment]
> If you change the path in the json to `/usr/bin/snap/keepassxc.proxy` does it work?

No, unfortunately. How could it, since there is no such file?

**Comment by droidmonkey** [comment]
Sorry I misunderstood your previous post.

**Comment by vasyugan** [comment]
It seems that we are experiencing different issues. The helper script does not throw an error, and the paths in the json file are all correct, and still the browser extension cannot talk to keepassxc.
I just wonder whether there is a way to get more information on what the browser extension is actually trying. On the console, I don't see anything useful, and I don't know where to look for related messages in Firefox' developer console.

**Comment by droidmonkey** [comment]
Unfortunately native messaging in browsers has little to no information provided for debugging. You can try running the browser through strace to see what it is trying to run and open. You could filter it using a grep for proxy.

**Comment by vasyugan** [comment]
Well, that's what I get from strace. To me this does not look particularly helpful though. At least it looks as if firefox is trying

[pid 24549] stat("/snap/bin/keepassxc.proxy", {st_mode=S_IFREG|0755, st_size=14997328, ...}) = 0
[pid 24839] execve("/snap/bin/keepassxc.proxy", ["/snap/bin/keepassxc.proxy", "/home/jr/.mozilla/native-messagi"..., "keepassxc-browser@keepassxc.org"], 0x7f996f9cdc00 /* 78 vars */ <unfinished ...>
[pid 24839] lstat("/snap/bin/keepassxc.proxy", {st_mode=S_IFLNK|0777, st_size=13, ...}) = 0
[pid 24839] readlinkat(AT_FDCWD, "/snap/bin/keepassxc.proxy", "/usr/bin/snap", 128) = 13
[pid 24848] execve("/usr/lib/snapd/snap-confine", ["/usr/lib/snapd/snap-confine", "--base", "core18", "snap.keepassxc.proxy", "/usr/lib/snapd/snap-exec", "keepassxc.proxy", "/home/jr/.mozilla/native-messagi"..., "keepassxc-browser@keepassxc.org"], 0xc000254300 /* 91 vars */ <unfinished ...>

**Comment by droidmonkey** [comment]
Seems like its working. Weird

**Comment by RawlzSec** [comment]
I had this problem earlier. Everything starting working mysteriously after I rebooted my machine. So I the only thing I can recommend is a reboot after you run the snap helper script.

**Comment by vasyugan** [comment]
> I had this problem earlier. Everything starting working mysteriously after I rebooted my machine. So I the only thing I can recommend is a reboot after you run the snap helper script.

Usually, you would only have to restart the browser. Did you do that?

**Comment by vasyugan** [comment]
Am 06.04.19 um 01:30 schrieb Kristofer Rawlins:
>
> I had this problem earlier. Everything starting working mysteriously
> after I rebooted my machine. So I the only thing I can recommend is a
> reboot after you run the snap helper script.
>
I just tried that, unfortunately to no avail

**Comment by vasyugan** [comment]
Strangely it now works. I wonder how long it will.

**Comment by droidmonkey** [comment]
@vasyugan is it still working for you?

**Comment by vasyugan** [comment]
@droidmonkey Yes, it still works.

**Comment by Friday13th87** [comment]
I have exactly the same issue like it is described here, but a pc restart didnt solved my issue, the addon still cant communicate with keepassxc main program.

if i install keepassxc 2.4.3 from debian buster stable the firefox addon is working (but then i cant use the new features...)

i was running the script helper, checked the links (they are existing), tried out chromium (same issue with the snapd keepassxc version)

dont know what i could try.

the addon debug console only says that maybe keepassxc is not running and that the key exchance was not succesfull.

any update on that issue?

**Comment by droidmonkey** [comment]
You can try using our AppImage instead

**Comment by vasyugan** [comment]
> You can try using our AppImage instead

Yes I know. I thought it would be convenient to have a fully functional flatpak instead because of better system integration and easier updating. Several flatpaks seem to have issues with k statusnotifier icons, saw the same with the Nextcloud desktop client
