### ISSUE TITLE
Cannot remove YubiKey CR from Database

### ISSUE THREAD

**Issue by Zocker1999NET** [keepassxreboot/keepassxc#2931]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
After clicking "Remove YubiKey Challenge-Response" and closing an database
which is encrypted using password and YubiKey before,
I want to reopen the database without using my YubiKey.

## Current Behavior
[NOTE]: # ( Tell us what actually happens )
The database cannot be saved after "removing" Challenge-Response
(it is not marked as changed like before version 2.4.0),
and I cannot reopen the database without my YubiKey,
that is still only possible with YubiKey.

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )
Remove the YubiKey challenge-response after clicking the button.

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1. Open a database encrypted with password and challenge-response
2. Select "Change master key ..."
3. Press "Remove YubiKey Challenge-Response"
4. Try to click "Save database" (not possible)
5. Close database
6. Reopen database *without* YubiKey

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )
I want to remove the Challenge-Response factor from the master key of my database.

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.4.0
Revision: c51752d
Distribution: AppImage

Libraries:
- Qt 5.10.1
- libgcrypt 1.8.1

Operating system: Debian GNU/Linux 9 (Stretch)
CPU architecture: x86_64
Kernel: linux 4.9.0.8-amd64

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (only unsigned sharing)
- YubiKey

**Comment by phoerious** [comment]
This is fixed in #2919.

**Comment by axilleas** [comment]
I just bumped onto this issue with 2.5.1 on Arch Linux. Should I file in a new bug report?
