### ISSUE TITLE
make package fails

### ISSUE THREAD

**Issue by lwt-pressy** [keepassxreboot/keepassxc#2934]
## Expected Behavior

based on the install documentiation you should be able to buid a deb package.

## Current Behavior

I tried 
* make package (based on INSTALL.md, but how would it now what package type?)
* make deb
* make debian
* make Debian

all results in: make: *** No rule to make target

How can I create a package?

**Comment by droidmonkey** [comment]
```make package``` performs a full compile and then runs cpack afterwards. On Linux operating systems, cpack only generates a zip file which is the default for cpack.

Creating a debian package is very specific and outside the scope of our build process. You can see a pre-made process here: https://github.com/keepassxreboot/keepassxc-packaging/tree/master/debian

**Comment by droidmonkey** [comment]
You can read more here: https://wiki.debian.org/HowToPackageForDebian

**Comment by lwt-pressy** [comment]
currently make package does nothing, but gives an error:

`$ make package

make: *** No rule to make target 'package'.  Stop.`

**Comment by droidmonkey** [comment]
Does running just plain old ```make``` work? You probably did not setup cmake correctly.

**Comment by lwt-pressy** [comment]
"make", "make test" also "make install" works. Just "make package" does not. I also can't find a target for package in Makefile.

**Comment by phoerious** [comment]
make && make package.
