### ISSUE TITLE
Moving from 2.3.4 to 2.40 on a Mac, cannot open existing database.

### ISSUE THREAD

**Issue by bworrell1** [keepassxreboot/keepassxc#2935]
I used the dmg download, kept both 2.3.4 and 2.4.0.  When trying to open my database in 2.4.0 I receive the attached error.

Going back to 2.3.4 it opens just fine.

I have a password and a key file.

As a test, I did a save as on the database and changed the name to "test" (with the proper extension).  File opens in 2.3.4, but same error in 2.4.0.

Running Mac OS Mojave. 

![Screen Shot 2019-04-03 at 6 12 09 PM](https://user-images.githubusercontent.com/19977752/55516726-18772a00-563c-11e9-9290-98ad8aa195ef.jpg)

**Comment by droidmonkey** [comment]
Duplicate, and already fixed in 2.4.1

**Comment by bworrell1** [comment]
I do not see a 2.4.1 on the github releases.  Is there an ETA for this?  Thanks

**Comment by droidmonkey** [comment]
Its coming very soon
