### ISSUE TITLE
Clipborard copying behavior regression

### ISSUE THREAD

**Issue by akontsevich** [keepassxreboot/keepassxc#2936]
Copying passwords or logins become very inconvenient in v2.4 comparing to v2.3.

## Expected Behavior
Ctrl-F, search phrase, Ctrl-C - to copy password from the first selected entry

## Current Behavior
Ctrl-F, search phrase, switch to entries list by Tab or Mouse click, then Ctrl-C which is inconvenient.

## Possible Solution
Revert to behavior from v2.3.x

Operating system: Linux
CPU architecture: x64
Kernel: 5.0.3

**Comment by droidmonkey** [comment]
duplicate

**Comment by akontsevich** [comment]
@droidmonkey what is original issue number?

**Comment by droidmonkey** [comment]
#2639

**Comment by akontsevich** [comment]
@droidmonkey what?! How icons related to clipboard?! Wrong number.
