### ISSUE TITLE
Dark mode white input fields

### ISSUE THREAD

**Issue by JanValkenburg** [keepassxreboot/keepassxc#2939]
When MacOS is set to "dark mode" theme (System Prefs > General > Appearance: Dark) all input fields are white and has white text. This make it impossible to read content in the input fields and make the app unusable.

![alt text](https://i.ibb.co/4VJWDBV/Screenshot-2019-04-04-at-09-20-10.png)

## Expected Behavior
The expected behavior is that the input fields have a dark background color with light colored text.

## Steps to Reproduce
1. Set MacOS to "dark mode" theme (System Prefs > General > Appearance: Dark)
2. Open KeePassXC

## Debug Info
KeePassXC - Version 2.4.0
Revision: c51752d

Libraries:
- Qt 5.12.2
- libgcrypt 1.8.4

Operating system: macOS Mojave (10.14)
CPU architecture: x86_64
Kernel: darwin 18.5.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (only unsigned sharing)
- YubiKey
- TouchID

Libraries:
- LIBS

**Comment by droidmonkey** [comment]
Did you completely restart KeePassXC after setting dark mode?

**Comment by JanValkenburg** [comment]
Just restarted the app and the background color of the input field are dark again. Thanks for the tip. 

I did some quick testing and when switching dark mode off and on again in macOS the problem is returning. So I think it should be fixed in the long run.

**Comment by droidmonkey** [comment]
This is a qt bug, not our app
