### ISSUE TITLE
URL matching doesn't work during auto-type?

### ISSUE THREAD

**Issue by l0f4r0** [keepassxreboot/keepassxc#2940]
I certainly haven't quite understood the URL matching process for auto-type feature but is my entry URL not supposed to match with my active URL opened in my browser?

## Expected Behavior
URL entry should match with the URL opened in my browser during auto-type

## Current Behavior
Auto-type doesn't trigger anything (no match)

## Steps to Reproduce
1. Check KeepassXC global setting "Use entry URL to match windows for global Auto-Type"
2. Have an entry with say http://mydomain.tld
3. Open http://mydomain.tld in a browser (make sure the URL remains the same and that you're not redirected)
4. Trigger auto-type with keyboard shortcut

## Debug Info
KeePassXC - Version 2.4.0
Revision: c51752d
Windows 10 Professional
Vivaldi browser (2.4.1488.35 - Stable channel - 64 bits)

**Comment by phoerious** [comment]
Autp-Type matches based on the window title. For URL matching you need to install our browser add-on KeePassXC-Browser.

**Comment by droidmonkey** [comment]
There are add ons for Firefox and Chrome that put the url in the window title. You need those to get KeePassXC to pick up on the url matching.

**Comment by l0f4r0** [comment]
Ok, thank you @phoerious and @droidmonkey.
I was not aware one needs a specific browser extension for that feature. Maybe it would be worth mentioning it or move the option to the "browser integration" panel setting? Because the option is currently in "General" panel setting along with "Use entry title to match winfdows for gloabal Auto-Type" which works out of the box...

**Comment by droidmonkey** [comment]
If you are using the browser integration then there is no need for Auto-Type in the browser.

**Comment by ypawlak** [comment]
> 
> 
> Autp-Type matches based on the window title. For URL matching you need to install our browser add-on KeePassXC-Browser.

Primarily I didn't want to connect the browser or install the extension. Is URL-matching feature expected to appear in future releases or is it intentionally blocked when you don't use browser integration?

**Comment by droidmonkey** [comment]
URL matching is an option in the Auto-Type settings.

**Comment by ypawlak** [comment]
Thanks for the quick reply. Still, I have that option checked (as pointed out in Steps to Reproduce) but when trying to invoke Auto-Type I get the message that matching entry wasn't found for current window title as if that setting was ignored. 
I believe that behavior was acknowledged and qualified as 'not a bug'. I just wonder if you're planning on providing that feature some time or perhaps there's a reason why it shouldn't be used this way.

**Comment by droidmonkey** [comment]
Does the window title have the url in it??

**Comment by ypawlak** [comment]
Oh, I see it now. If you read the setting description real careful it figures. I thought it's gonna match actual site URL, but obviously it's another feature if we only check os window title. And you do that in browser extension, makes sense.
