### ISSUE TITLE
Ctrl+C not working as expected on Notes

### ISSUE THREAD

**Issue by ricardofpt** [keepassxreboot/keepassxc#2941]
Hey everyone,

Don't know if it's only me, but if I select some text in the Notes section and press Ctrl+C, keepass copies whatever is in the Password field instead. I have to right click the selected text and click on Copy for it to work.

Anyone else is able to reproduce this?

I am using keepass 2.3.4 on Manjaro.

Thanks!

**Comment by droidmonkey** [comment]
Upgrade to 2.4.0
