### ISSUE TITLE
Please link to Liberapay from https://keepassxc.org/donate/

### ISSUE THREAD

**Issue by MagicFab** [keepassxreboot/keepassxc#2943]
https://keepassxc.org/donate/ does not list Liberapay.

This would help determine if this link is valid for donations:
https://liberapay.com/keepassxc/

**Comment by louib** [comment]
thanks for the feedback @MagicFab !

We have an [open issue](https://github.com/keepassxreboot/keepassxreboot.github.io/issues/46) for that already. Will close this one.

**Comment by droidmonkey** [comment]
I added it
