### ISSUE TITLE
Encryption setting can't be anything other than version 4

### ISSUE THREAD

**Issue by sseneca** [keepassxreboot/keepassxc#2948]
## Expected Behavior
Encryption setting respects what is set by the user.

## Current Behavior
Encryption setting will always switch back to KDBX 4 even if it's set to v3.1.

## Steps to Reproduce

1. Database > Database settings > Security > Encryption Settings > Database Format
2. Set it to KDBX 3.1 and press "OK"
3. Repeat step 1

KDBX version will be set to version 4 again.

## Context

I use the MiniKeePass app for iOS, which has been unmaintained for about 1.5 years. For now, I want to continue using it because it's the only app I like (that's free in both ways) but it hasn't got support for KDBX 4. A few days ago, I updated my database and tried to load it into the iOS app and it stopped working. After some research, I realised that for some reason KDBX version had changed itself to version 4 -- changing it back to version 3.1 will initially work but once I click "OK" and then re-check the version number in settings I'll see that it's changed back to version 4. This means that for now I can no longer view my password or access them on my phone.

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.4.0
Revision: c51752d

Libraries:
- Qt 5.12.2
- libgcrypt 1.8.4

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 5.0.5-arch1-1-ARCH

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (only unsigned sharing)
- YubiKey

**Comment by droidmonkey** [comment]
This is not possible since we use new features in kdbx4 to support browser integration and other plugin behavior. Think hard about your desire to use an abandoned app that secures your passwords.
