### ISSUE TITLE
Dependencies for Debian buster are not the same

### ISSUE THREAD

**Issue by erwdavid** [keepassxreboot/keepassxc#2949]
On debian buster, libargon2 is version 2.1, and the dev package for dependencies is not libargon2-0-dev (which requires a libargon2-0 library from stretch) but libargon2-dev

keepassxc built this way passes all the tests, including password generator

**Comment by droidmonkey** [comment]
What are you suggesting needs to be corrected?

**Comment by erwdavid** [comment]
To change the list of dependencies in the wiki page "linux build
environment" to install libargon2-dev in debian buster

Le 05/04/2019 à 18:47, Jonathan White a écrit :

**Comment by droidmonkey** [comment]
Made the change
