### ISSUE TITLE
Mulltiple plugin-searchable URLs per credential

### ISSUE THREAD

**Issue by beevik** [keepassxreboot/keepassxc#2950]
[TIP]:  # ( Provide a general summary of the feature in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Summary
[NOTE]: # ( Provide a brief overview of what the new feature is all about )

There should be some way to associate more than one plugin-searchable URL with a single keepassxc credential.

## Rationale

A keepassxc credential URL doesn't always match the site's URL once you double-click on the URL to launch the site in the browser.  This is because sites often redirect immediately to a different subdomain that no longer matches the original keepassxc credential URL.  The differing domains make it difficult or impossible for the keepassxc-browser plugin to find a suitable match. 

For example, if I have a credential for the URL "https://my.bank.com", double-clicking on it may open the browser and then redirect to something like "https://account-verify.login.bank.com", which no longer matches the keepassxc credential URL.

I can work around this by renaming the credential URL to something like "bank.com", but then I can no longer reliably double-click on it to reach the landing page I'm trying to reach -- a landing page which often contains a subdomain.

## Desired Behavior
[NOTE]: # ( Tell us how the new feature should work, be specific )

I would like a way to specify one or more URL aliases for a keepassxc entry.  The keepassxc-browser plugin should then search all URL aliases when selecting a credential that matches the current page URL.

## Possible Solution
[NOTE]: # ( Not required, but suggest ideas on how to implement the addition or change )

 I can see a couple possible ways such a feature might be implemented:

1. The URL aliases could be stored in the credential's advanced "Additional Attributes" section, where any attribute value whose key starts with "URL"  would be included in the keepassxc-browser plugin's URL search.  The credential's original "URL" field would remain untouched and would still be used to launch the site when double-clicked on in keepassxc.  OR:

2. The "URL" entry in the keepassxc entry page could be used to specify a list of URLs.  For greatest backward compatibility, a list of space-separated URLs could be used, since spaces are not allowed in URLs without being escaped. The keepassxc-browser plugin could then search the entire list of URLs when deciding whether it contains a match.  For launching a website from keepassxc itself, double clicking the URL would cause the first listed URL to be used.

If either of these solutions were implemented, I could associate the URLs "https://my.bank.com" and "bank.com" with my bank credential.  The first URL ("https://my.bank.com") would lead me to the page I'm trying to reach  if I double click on it. The second URL ("bank.com") would allow plugin matches against any subdomain URL the site redirected me to (e.g., "https://account-verify.login.bank.com")

**Comment by droidmonkey** [comment]
This has been discussed in several previous issues. We will be implementing this along with entry templates for 2.5.0. See #1769 and #398 and #863

**Comment by brianjmurrell** [comment]
What is the **current** status of matching multiple URLs to an entry in KeePassXC?

I see this issue is 5 years old and was closed 5 years ago as a duplicate but I still don't see how to associate an entry to multiple URLs.  I got lost in the trail of many closed and redirected issues discussing multiple URLs.

**Comment by droidmonkey** [comment]
Browser tab when editing an entry, it's documented in the user guide as well

**Comment by brianjmurrell** [comment]
Oh yeah, the *tab*s on the side.  TBH, I often disassociate that side-bar with entry addition.  It just always feels so _disconnected_ from the entry addition.

Thanks for the reminder though, it works!
