### ISSUE TITLE
Ubuntu x64 18.04 can't use shortcuts anymore

### ISSUE THREAD

**Issue by MyWay** [keepassxreboot/keepassxc#2952]
## Expected Behavior
I used to CTRL+B and CTRL+C to copy username and password of items.

## Current Behavior
After updating to the last version via apt, it's not working anymore, I do CTRL+C but the password isn't copied.

## Possible Solution
No idea, maybe checking for differences with the old version could help. Meanwhile I'm using the GUI to copy them.

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1. Install keepassxc on Ubuntu x64 Ubuntu 18.04.2 LTS using ppa:phoerious/keepassxc
2. Try to copy using shortcuts, CTRL+C to copy the password
3. The password is not in the clipboard.

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.4.0
Revision: Couldn't find it.

Libraries:
- LIBS

Operating system: Ubuntu
CPU architecture: x64
Kernel: linux 4.15.0-47-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (only unsigned sharing)
- YubiKey

**Comment by droidmonkey** [comment]
You have to explicitly select and focus on the entry you are trying to copy from. The toolbar icons should become active.

**Comment by jaywk** [comment]
Additionally, with previous version, hitting Ctrl+V on a selected entry passed Password -> Tab -> password -> Enter into webpage and this has stopped working. Ubuntu x64 18.04 here also.

**Comment by droidmonkey** [comment]
That was changed to CTRL+SHIFT+V to prevent accidental activation

**Comment by MyWay** [comment]
Seems that was a problem of selecting, like you said. If I find it again, I will re-open. Thanks.
