### ISSUE TITLE
Add option to not automatically clear search field

### ISSUE THREAD

**Issue by Barugon** [keepassxreboot/keepassxc#2953]
The search field is automatically cleared after a few ~~seconds~~ minutes and there doesn't seem to be a way to disable that (that I can find anyway).

There needs to be a way to disable this behavior.

KeePassXC - Version 2.4.0

Libraries:
- Qt 5.11.3
- libgcrypt 1.8.4

Operating system: Fedora 29 (Workstation Edition)
CPU architecture: x86_64
Kernel: linux 5.0.5-200.fc29.x86_64

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (only unsigned sharing)
- YubiKey

**Comment by droidmonkey** [comment]
The search field clears after 5 minutes. A few seconds is not the programmed behavior.

**Comment by Barugon** [comment]
> A few seconds is not the programmed behavior.

That was a mistake. The title is correct though.

> Please describe your use case that requires search results to remain after a long period of non-use.

While working, I use the same password throughout the day to access various network resources. Even for personal use, I'll use the same github password multiple times in a given period.

**Comment by rgalonso** [comment]
I have a similar use case to Barugon and this change in the UI has become very annoying.

**Comment by droidmonkey** [comment]
I hate to be the guy to say you're using it wrong... But, you really should be relying on Auto-Type window associations and browser integration to access entries. Perhaps even better organization of your entries so that you don't have to rely on a constant search being displayed.

**Comment by rgalonso** [comment]
> I hate to be the guy to say you're using it wrong... But, you really should be relying on Auto-Type window associations and browser integration to access entries. Perhaps even better organization of your entries so that you don't have to rely on a constant search being displayed. I'll consider a setting under security to enable/disable search clearing, but the issue is highlighting an inefficiency in your workflow more than anything.

Well, I do, when there's a browser window involved.  But the specific scenario I'm dealing with is for an internally hosted Git server where I'm interfacing with it through the CLI.

**Comment by Barugon** [comment]
Honestly, there's really no good reason to automatically clear the search field. If I want it cleared then I can click the X button instead of just clicking the search field. Anyway, it's all moot as I've moved to another solution.

**Comment by droidmonkey** [comment]
That is your opinion, but clearly people wanted it to be auto cleared. See #2178.

**Comment by Barugon** [comment]
Even the creator of that issue said it should be an option.

**Comment by internetstaff** [comment]
This is also a frustration for me, inefficient or not. :)

**Comment by Barugon** [comment]
Thanks @droidmonkey.

**Comment by rgalonso** [comment]
Haven't got a chance to test it out yet, but thanks @droidmonkey!

**Comment by ironashram** [comment]
i'd also like the option, the search auto resetting makes no sense to me

**Comment by droidmonkey** [comment]
This was just merged to develop

**Comment by rgalonso** [comment]
In case anyone else is curious, like me, about which specific commit is being referred to [above](https://github.com/keepassxreboot/keepassxc/issues/2953#issuecomment-518035469), the commit was 726dbc004d9e7e0af47eea077bf5ed19d24a8adb, in reference to issue #3400.
I'm looking forward to this feature finally getting close to release.  Thanks @ziah and @droidmonkey!

**Comment by bleepnetworks** [comment]
> That is your opinion, but clearly people wanted it to be auto cleared. See #2178.

I don't want it to be auto-cleared. I also do not want the overhead of maintaining browser integrations as I use a crapload of browsers for testing. I like my current worflow just fine and the recent change has disrupted it.

Auto clearing the search is a change from the default in previous versions and it really needs to be optional. Can we just have a checkbox to switch it on or off?

**Comment by polpanka** [comment]
I really hate this behavior, and anyway there is no reason to avoid adding an option to disable it.
