### ISSUE TITLE
Reactivate window on tray icon double-click

### ISSUE THREAD

**Issue by h-h-h-h** [keepassxreboot/keepassxc#2956]
[TIP]:  # ( Provide a general summary of the feature in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Summary
[NOTE]: # ( Provide a brief overview of what the new feature is all about )

I'm on Windows 10.

Some apps' tray icons require single-clicks and other ones double-clicks to show their respective windows. Even if apps' tray icons only require a single-click, a double-click is often no problem, because I usually don't need to control them by keyboard directly after showing the window.

Anyways, I regularly happen to double-click KeePassXC's tray icon. The first click shows the window, the second click deactivates it and activates the taskbar instead. Then, I'd need to press Ctrl+F and type my search text, but, first, have to activate KeePassXC's window again.

## Desired Behavior
[NOTE]: # ( Tell us how the new feature should work, be specific )

When the tray icon is double-clicked, the deactivation of the window should be undone by activating it again.

## Possible Solution
[NOTE]: # ( Not required, but suggest ideas on how to implement the addition or change )

In [`MainWindow::trayIconTriggered()`](https://github.com/keepassxreboot/keepassxc/blob/b3ce7ec9c4aaa133005ca2eb854301f92642fc5b/src/gui/MainWindow.cpp#L1034), on `isVisible() == true` and `reason == QSystemTrayIcon::DoubleClick`, `activateWindow()` should be called (alternatively `bringToFront()`).

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )

(See summary.)

**Comment by h-h-h-h** [comment]
There's another strange thing I noticed that's associated with double clicks. I regularly use <kbd>Win</kbd> + <kbd>B</kbd> to control the tray icons by keyboard (use arrow keys to select the tray icon). Showing the KeePassXC window with <kbd>Space</kbd> works, but showing it with <kbd>Enter</kbd> *doesn't work;* that just very quickly shows and hides the window.

I tried to find out what events fire when pressing <kbd>Space</kbd> or <kbd>Enter</kbd>, respectively. I used the following C# example app for that: https://github.com/kesac/SystemTrayApp. Code diff that adds logging code:

```diff
 SystemTrayApp/AppWindow.cs | 24 ++++++++++++++++++++++++
 1 file changed, 24 insertions(+)

diff --git a/SystemTrayApp/AppWindow.cs b/SystemTrayApp/AppWindow.cs
index 7ca7778..665bdb4 100644
--- a/SystemTrayApp/AppWindow.cs
+++ b/SystemTrayApp/AppWindow.cs
@@ -2,6 +2,7 @@
 using System.Collections.Generic;
 using System.ComponentModel;
 using System.Data;
+using System.Diagnostics;
 using System.Drawing;
 using System.Linq;
 using System.Text;
@@ -36,6 +37,29 @@ namespace SystemTrayApp
 
             this.Resize += WindowResize;
             this.FormClosing += WindowClosing;
+
+            //dbg:
+            this.SystemTrayIcon.Click += (sender, e) => {
+                Debug.WriteLine(DateTime.Now.Second.ToString() + " Click");
+            };
+            this.SystemTrayIcon.DoubleClick += (sender, e) => {
+                Debug.WriteLine(DateTime.Now.Second.ToString() + " DoubleClick");
+            };
+            this.SystemTrayIcon.MouseClick += (sender, e) => {
+                Debug.WriteLine(DateTime.Now.Second.ToString() + " MouseClick");
+            };
+            this.SystemTrayIcon.MouseDoubleClick += (sender, e) => {
+                Debug.WriteLine(DateTime.Now.Second.ToString() + " MouseDoubleClick");
+            };
+            this.SystemTrayIcon.MouseDown += (sender, e) => {
+                Debug.WriteLine(DateTime.Now.Second.ToString() + " MouseDown");
+            };
+//            this.SystemTrayIcon.MouseMove += (sender, e) => {
+//                Debug.WriteLine("MouseMove");
+//            };
+            this.SystemTrayIcon.MouseUp += (sender, e) => {
+                Debug.WriteLine(DateTime.Now.Second.ToString() + " MouseUp");
+            };
         }
         
         private void SystemTrayIconDoubleClick(object sender, MouseEventArgs e)
```

**Comment by droidmonkey** [comment]
This cannot be fixed until https://bugreports.qt.io/browse/QTBUG-69698 is fixed.

**Comment by droidmonkey** [comment]
Actually I figured out a workaround. PR submitted for 2.4.2
