### ISSUE TITLE
Invalid TOTP in v2.4.0

### ISSUE THREAD

**Issue by tuxsoy** [keepassxreboot/keepassxc#2959]
TOTP stopped working correctly on my system after upgrading from v2.3.4.1 to v2.4.0

Downgrading fixed the issue for me. I'm not sure what caused the issue.

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: 5.0.4

**Comment by droidmonkey** [comment]
Are you using a special form of totp?

**Comment by tuxsoy** [comment]
@droidmonkey I use `Default RFC 6238 token settings`.

**Comment by droidmonkey** [comment]
Well TOTP certainly works in 2.4.0, I use it all the time. Is the secret key valid Base32?

**Comment by tuxsoy** [comment]
That's odd. As per `RFC 4648` it is valid Base32. Some of my keys have spaces and lowercase letters, but that doesn't explain why all of them fail to work.

**Comment by alamo11** [comment]
I could detect the same buggy behavior under version 2.40 Xubuntu and 2.41 Windows Portable 64bit with different secrets. Up to version 2.3.4 it worked.

**Comment by mlippert** [comment]
It has been working for me on Linux Mint 18.03 KDE.
I'd like to know what you mean by not working correctly, just that the codes it produces are wrong, or something else? And do you have a separate utility (maybe an app on your phone) that also produces the TOTP code that you can see is different?

I just want to know what's been observed to be on the lookout for.

**Comment by tuxsoy** [comment]
@mlippert it gave an incorrect TOTP code. Using a different TOTP device I could confirm that the issue was with KeepassXC. That being said, I'm now on v2.4.1 and I haven't been able to reproduce the issue after the upgrade.

**Comment by droidmonkey** [comment]
You probably had a time issue with your computer. I am closing this because there is nothing wrong with the algorithm itself.
