### ISSUE TITLE
bad-image-KeepassXC Windows 7 64

### ISSUE THREAD

**Issue by luka44** [keepassxreboot/keepassxc#2961]
I have downloaded and installed MSYS2 per the instructions.
  MSI Installer (64-bit) and  Portable (64-bit) and the constant error message is
![bad-image-KeepassXC](https://user-images.githubusercontent.com/49309807/55704294-14be1b80-5a1f-11e9-9156-5cd9abfea4a5.PNG)
Program not responsive
Any help appreciated.

**Comment by droidmonkey** [comment]
What? Are you trying to build KeePassXC on Windows? This is an MSYS2 problem not us.
