### ISSUE TITLE
autofill google chrome

### ISSUE THREAD

**Issue by marcwyler** [keepassxreboot/keepassxc#2962]
## Expected Behavior
Wenn ich eine URL über 'URL öffnen' öffne, möchte ich zurück in keepass xc, mit einem Rechtsklick auf den Eintrag ein 'Auto-Ausfüllen' machen

## Current Behavior
Wenn ich zurück zu keepass xc wechsle, und einen Rechtsklick auf meinen Eintrag mache, sind alle Optionen deaktiviert (gesperrt) bis auf 'Neuer Eintrag'

## Possible Solution
Wenn ich anstelle des Rechtsklicks dann den Shortcut für das 'Auto Ausfüllen' drücke (Shift+CMD+V) kommt folgende Fehlermeldung:
Konnte keinen Eintrag finden, der mit dem Fenstertitel übereinstimmt:
db-name - KeePassXC
Wenn ich OK drücke ist dann wieder alles freigeschaltet und ich kann mit einem Rechtsklick das 'Auto Ausfüllen' machen
Danach ist aber wieder alles gesperrt

## Steps to Reproduce
1. Rechtsklick auf Eintrag
2. URL öffnen klicken
3. im Browser Benutzerfeld auswählen
4. zurück wechseln zu keepass xc
5. Rechtsklick auf Eintrag
6. Alle Optionen sind deaktiviert bis auf 'Neuer Eintrag'

## Debug Info
KeePassXC - VERSION 2.4.0

Operating system: OS X High Sierra
CPU architecture: 3.4 GHz Intel Core i7
8 GB 1333 MHz DDR3
![Bildschirmfoto 2019-04-08 um 20 08 22 PM](https://user-images.githubusercontent.com/49411270/55746495-1943fd80-5a3a-11e9-9198-f18339096238.png)

**Comment by droidmonkey** [comment]
This is a Qt bug and duplicate
