### ISSUE TITLE
launchpad: keepassxc 2.4.0 is missing in Xenial

### ISSUE THREAD

**Issue by mhow2** [keepassxreboot/keepassxc#2963]
The Xenial build for latest version of Keepassxc is failing : https://launchpad.net/~phoerious/+archive/ubuntu/keepassxc/+build/16528237

Can someone take a look ? That would be greatly appreciated.

Cheers

**Comment by stdedos** [comment]
Duplicate of https://github.com/keepassxreboot/keepassxc/issues/2869 ?

**Comment by oshmyrko** [comment]
Fixed in 2.4.1 (https://github.com/keepassxreboot/keepassxc/pull/2990)
