### ISSUE TITLE
Wrong default icons are loaded

### ISSUE THREAD

**Issue by xf-** [keepassxreboot/keepassxc#2964]
## Summary
Some shops provide a favicon.ico in / and set the real icon via HTML link-Tag. One of most known Software is Magneto.
Example: roastmarket[dot]de

## Desired Behavior
A simple way to set the correct icon.

## Possible Solution
Force load via duckduckgo (not as fallback) or allow to blacklist icons.

**Comment by droidmonkey** [comment]
If duck duck go cannot resolve the correct icon then you will need to add your own. We are not taking the functionality any further.

**Comment by xf-** [comment]
@droidmonkey i mean the icon is loaded from the web and i want it from duckduckgo, because the web icon is incorrect and duckduckgo is "perfect"

Wrong:
https://www.roastmarket.de/favicon.ico

DuckDuckGo
![image](https://user-images.githubusercontent.com/1295633/55797520-f878b800-5acc-11e9-855b-217cf04a97ae.png)


Setting:
![image](https://user-images.githubusercontent.com/1295633/55797599-29f18380-5acd-11e9-8049-dc71f7dac722.png)
