### ISSUE TITLE
Tab-labels not showing properly on 125% scaling

### ISSUE THREAD

**Issue by Gurran** [keepassxreboot/keepassxc#2965]
## OS: 

> Operating system: Windows 10 (10.0)
> CPU architecture: x86_64
> Kernel: winnt 10.0.17134

## Version: 
> KeePassXC - Version 2.4.0
> Revision: c51752d

_(Note: New Install)_

### [Description]
When using 125% scaling the tab-labels gets squished. This occurs on a screen resolution of 1920x1080. This does not occur if I open KeepassXC on a screen without scaling (100% scaling).

[Image](https://imgur.com/a/OqmotEX)

**Comment by droidmonkey** [comment]
Please see https://doc.qt.io/qt-5/highdpi.html#high-dpi-support-in-qt
