### ISSUE TITLE
[PRE-RELEASE] Snap: recent edge channel update (version 245) broke theming

### ISSUE THREAD

**Issue by joshirio** [keepassxreboot/keepassxc#2966]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

I'm running keepassxc snap from the edge channel. After contributing mouse cursor fixes #2832 I've been running the edge version since without issues. Today revision 245 was pushed to the edge channel and the snap theme looks broken, not sure what has been changed.

![shot](https://user-images.githubusercontent.com/12795018/55806079-e6544500-5adf-11e9-8115-eaca4ace7688.png)

## Expected Behavior
Revert to using default Qt fusion style

## Current Behavior
Fallback theme is used, see screenshot above

## Possible Solution
Revert changes or investigate possible cause

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1. sudo snap refresh keepassxc --edge
2. keepassxc

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )

## Debug Info
KeePassXC - Version 2.4.0
Revision: 29c79c9
Distribution: Snap

Qt 5.9.5
Debugging mode is disabled.

Operating system: Ubuntu Core 18
CPU architecture: x86_64
Kernel: linux 4.18.0-17-generic

Enabled extensions:
- Auto-Type
- Browser-Integration
- SSH-Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.1

Operating system: Ubuntu 18.04
CPU architecture: x86_64
Kernel: 4.18.0-17-generic

**Comment by droidmonkey** [comment]
We haven't touched anything regarding theming it snaps

**Comment by joshirio** [comment]
After some investigation it appears something changed on core18 or snapcraft/snapd side of things because many of my own snaps broke on the edge channel too, so I was too quick to blame it to keepassxc (sorry).

Sometimes when the core18 base or a dependency package changes (is updated to fix security issues or something else) edge channels snaps are usually automatic rebuilt, so that's the reason an update was pushed automatically to the edge channel.

Apparently there could be a regression inside the base snap or snapcraft, so my suggestion is to wait too see if they fix it. If not, and a new release of keepassxc is being released (2.4.1) in the meantime we could revert PR https://github.com/keepassxreboot/keepassxc/pull/2832 

A bit disappointed, shows how much this technology (snap) is still immature and needs more work.

**Comment by droidmonkey** [comment]
I am totally disappointed in snaps, to be quite honest. I do not think flatpaks are any better, but they seem easier to build on any platform.

**Comment by joshirio** [comment]
Flatpak isn't better at all, I failed multiple times to just ship a simple Qt app. At least with snap I can specify dependencies with just a package from a base, instead of building from source all deps of deps recursively, that's insane.

> The fact that I cannot build snaps in an Ubuntu 18.04 VM is a complete travesty.

from https://snapdocs.labix.org/build-on-lxd/4157
`snapcraft --destructive-mode`
will build in a VM (must be a clean Ubuntu 18.04 though), this is intended for throwaway build setups like CI systems.

And with multipass things are improving to build snaps on any distro that ship snapd, since it's basically a minimal VM.

**Comment by droidmonkey** [comment]
You cannot run a vm in a vm. I would need a host based Linux system.

**Comment by joshirio** [comment]
The documentation is a bit misleading because this actually works in any VM (inside Virtualbox for example) and is not dependent on LXD.

The `--destructive-mode` flag just tells snapcraft to not spin up a VM and use the raw system whether it is a real or virtual machine.

https://bugs.launchpad.net/snapcraft/+bug/1815319

**Comment by droidmonkey** [comment]
You sir have saved me a lot of hassle for future debugging!

**Comment by droidmonkey** [comment]
Is this theming issue still present?

**Comment by elcste** [comment]
Yes, for me, on Ubuntu MATE 19.04. I'm on the snap edge channel, version 2.5.0, rev 301.

**Comment by joshirio** [comment]
Yes, still not fixed. Tried a fresh build environment since the edge channel was not updated.
Workaround and improvements proposed in PR https://github.com/keepassxreboot/keepassxc/pull/3028.

A bit hacky though.

**Comment by galgalesh** [comment]
Just wanted to thank @droidmonkey and others for your efforts in creating such a high-quality snap package. As a user of KeePassXC, I'm very happy I can now use the latest version in Ubuntu without installing a ppa.

Also, in case you didn't know; you can now [build snaps in virtual machines using LXD](https://snapcraft.io/docs/build-on-lxd): `snapcraft --use-lxd`. This can be used, for example, to do automated builds on travis: https://github.com/snapcrafters/sdlpop/blob/master/.travis.yml

**Comment by droidmonkey** [comment]
Thank you for your kind words! If you didn't know, we have automated builds of the develop branch feeding the "edge" channel. You can try out new features and stay up to the minute very easily.
