### ISSUE TITLE
key derivation function changing back to KDBX4 after choosing KDBX3.1

### ISSUE THREAD

**Issue by limuc** [keepassxreboot/keepassxc#2967]
## Expected Behavior
When i open any database in KeePassXC 2.4.0 and edit some entry and save the database, the key derivation function and the number of key transformation rounds don't change.

## Current Behavior
I have 2 databases. Each is encrypted with AES 256-bit and the key derivation function is AES-KDF (KDBX 3.1). The number of key transformation rounds is something around 50.000.000. 
After opening the databases in KeePassXC 2.4.0 and adding new entries the key derivation function is set to AES-KDF (KDBX 4) and the number of key transformation rounds is only 1.000.000. I tried to set it to KDBX 3.1 again, but it changes back everytime as soon as i click "ok".

## Steps to Reproduce
1. Open database with KDBX 3.1 format.
2. Add new entry or make some edit.
3. Save the database.

or

1. Open database with KDBX 3.1 format.
2. Go to the encryption settings.
3. See that it is now KDBX 4.
4. Set it to KDBX 3.1 and click "ok".
5. Go back into the settings and see that it has changed back to KDBX 4 (and 1.000.000 transformation rounds)

## Debug Info
I use KeePassXC 2.4.0 in the portable version. My OS is Windows 10 Pro.

I hope this isn't already reported and includes all the necessary informations as this is my first issue ever. Also english isn't my native language so if something isn't clear ask ahead.

**Comment by phoerious** [comment]
You have entries with custom data which enforce kdbx4. I recommend you change your KDF to Argon2.

**Comment by limuc** [comment]
Ok thank you! Sorry for creating this issue.

**Comment by meersjo** [comment]
@phoerious I'm running into the same issue. What type of custom data will cause this; and if I remove said data will I be able to revert the file back to 3.1? 

We need to share the file with an older Keepass version that isn't under out control, so upgrading is not an option.

**Comment by phoerious** [comment]
Check your entries and groups for "Plugin Data".

**Comment by meersjo** [comment]
I don't have any plugins active, I think - except for browser integration, but that's a browser plugin, not a keepassxc one?

**Comment by phoerious** [comment]
The browser plugin needs to store its data somewhere.

**Comment by meersjo** [comment]
Found the data, but even after removing I wasn't able to revert to 3.1 encryption :-(

I resorted to dumping the 4.0 database to CSV and dumping the last 3.1 version out of backup to CSV, then pulling a diff and recreating the changed/new entries.

Thank you for pointing me where to look; I've disabled the browser plugin for that database now.

**Comment by droidmonkey** [comment]
What is the reason for staying with kdbx 3.1?

**Comment by meersjo** [comment]
@droidmonkey The file is shared with some people who are using an old version of the original Keepass that is, apparently, not going to be upgraded. I have no control over that, unfortunately. I'm going to bring this issue up, but I have low hopes.

**Comment by phoerious** [comment]
KeePass 2 implemented KDBX4 support in version 2.35, which was in 2017.

**Comment by meersjo** [comment]
I don't think the software has been upgraded in the last decade...

**Comment by phoerious** [comment]
If at all possible, I'd strongly recommend that. If not KeePassXC, then at least a somewhat up-to-date KeePass2.

**Comment by meersjo** [comment]
There's a reason I switched :-) I'll see if they're receptive, but I fear they see it as useless work because "it works ok".

**Comment by droidmonkey** [comment]
There is no excuse whatsoever to using out of date SECURITY software.
