### ISSUE TITLE
Wayland support

### ISSUE THREAD

**Issue by rugk** [keepassxreboot/keepassxc#2973]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

You do not seem to have any case of proper Wayland support.

If I execute it normally, I get:
```
Warning: disregarding XDG_SESSION_TYPE=wayland
To use wayland anyway, please set QT_QPA_PLATFORM=wayland
```

So now I was curious and did so, and…

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

Support Wayland properly.

## Current Behavior
[NOTE]: # ( Tell us what actually happens )

![wtfWayland](https://user-images.githubusercontent.com/11966684/55913794-c0b16380-5be5-11e9-8e99-ac614dea18f6.png)

:astonished: 
That design…? Some bluish things… Woa…
That tiny size…
(Not visible, but:) That _huge_ mouse pointer!

Also, we've even got windows without any title bar at all:

![image](https://user-images.githubusercontent.com/11966684/55913861-efc7d500-5be5-11e9-8de2-cd7d8f56adfc.png)

And finally, copying to clipboard fails…
Obviously, auto-type fails too.

Also getting this in the console:
```
QSocketNotifier: Can only be used with threads started with QThread
QObject::startTimer: Timers cannot have negative intervals
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
Maximum depth of replacement has been reached. Entry uuid: {REPLACED_AS_POTENTIALLY_SENSITIVE-SAME_AS_ABOVE_THOUGH}
Maximum depth of replacement has been reached. Entry uuid: {REPLACED_AS_POTENTIALLY_SENSITIVE-SAME_AS_ABOVE_THOUGH}
``` 

And there is a strange custom file selector instead of using the native (in my case: GNOME) file selector.

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )

Don't know, maybe it is indeed just upstream QT bug, but I think even QT support was not _that_ bad…

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1. `export QT_QPA_PLATFORM=wayland`
2. Start KeePassXC (in console).

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )

Whatever you do, Wayland is the future, so you'd better support it now. :smiley: 

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )

KeePassXC - Version 2.4.0

Libraries:
- Qt 5.11.3
- libgcrypt 1.8.4

Operating system: Fedora 29 (Workstation Edition)
CPU architecture: x86_64
Kernel: linux 5.0.5-200.fc29.x86_64

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (only unsigned sharing)
- YubiKey

**Comment by phoerious** [comment]
Supporting Wayland is Qt's job, not ours. We disabled it for the time being as it appears to be rather broken at the moment.

**Comment by rugk** [comment]
Hmm, anyway I've never such a bad thing and I think I've seen some other QT applications. So maybe it's some old version/particular problem, or do you e.g. use [this here](https://wiki.qt.io/QtWayland).

And are you sure you use no native X11 code by yourself?

**Comment by phoerious** [comment]
The only X11 magic we do is Auto-Type, so no.

**Comment by rugk** [comment]
Well… then… but this also needs to be ported then (if possible). Maybe we should open a new issue for this?

**Comment by droidmonkey** [comment]
There is no "porting" to Wayland as far as auto-type is concerned. We have to hope and see if there is a compositor standard that is adopted by the Wayland using distributions that enables access to window titles and keyboard typing. It is an unfortunate situation. I do believe that if we subscribe to the xwayland compositor we can retain "legacy" xcb controls, but I am really on the outer fringe of my understanding on all this at this point.

**Comment by e00E** [comment]
This seems to be an issue with my setup because I get the same error with other qt applications.

**Comment by rugk** [comment]
I guess you have to enable xwayland? :thinking:

**Comment by e00E** [comment]
It runs in x11 mode with xwayland. What I was trying is to intentionally use qt's wayland support which does not need xwayland.

**Comment by phoerious** [comment]
Are you trying to start this from an XWayland terminal?

**Comment by e00E** [comment]
No because in my issue I have xwayland disabled so I do not think it is possible for my terminal to be using xwayland.

I have tried `$ QT_QPA_PLATFORM=wayland keepassxc` on another machine and it does start up correctly there. So again, I believe this is an issue with the setup on the first machine and not a Keepassxc problem.

**Comment by mielouk** [comment]
Hope someone will answer my question on this cold thread, but I don't think my question is worth opening an own issue.
I'm using [sway](https://github.com/swaywm/sway) on Arch with [wofi](https://hg.sr.ht/~scoopta/wofi) as my launcher.

`QT_QPA_PLATFORM=wayland keepassxc` works as intended (confirmed with xeyes) when started from terminal or if I let it autostart with `exec 'QT_QPA_PLATFORM=wayland keepassxc'` in my sway config.
When started with wofi or another launcher KPXC runs on XWayland, while `export QT_QPA_PLATFORM=wayland` is set in .zshrc (.bashrc equivalent of [ZSH](https://www.zsh.org/))

How, where do I have to set the variable to make this also work from a launcher?

**Comment by e00E** [comment]
If you start sway from the command line and your login shell has the env set then it should work. I have a script that starts sway like this
```sh
#!/bin/sh
export QT_QPA_PLATFORM=wayland
export QT_WAYLAND_FORCE_DPI=physical
export ECORE_EVAS_ENGINE=wayland_egl
export ELM_ENGINE=wayland_egl
export SDL_VIDEODRIVER=wayland
export _JAVA_AWT_WM_NONREPARENTING=1
export MOZ_ENABLE_WAYLAND=1
sway
```
which makes every application started through sway (like wofi and my terminals) use these variables.

Alternatively you could edit the `desktop` file that is used by wofi to start keepass. On my machine it is located at `/usr/share/applications/org.keepassxc.KeePassXC.desktop`. Or you could add another keepassxc executable with higher priority than the real keepassxc that sets the environment variable and launches the real one.

**Comment by mielouk** [comment]
Thank you very much for the comprehensive answer! I got it working, now.

**Comment by tigerjack** [comment]
I tried the solution from @e00E but keepass crashes as soon as I insert the password and press enter with this error

```
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
QImage::scaled: Image is a null image
QImage::scaled: Image is a null image
Floating point exception
```

**Comment by e00E** [comment]
This was an issue with my instructions.  Make sure you don't have the QT_WAYLAND_FORCE_DPI=physical line that my answer used to have. It breaks many QT applications under wayland.

**Comment by tigerjack** [comment]
The only way it's working is when I export `QT_QPA_PLATFORM=xcb`. But I'm seeing the same problem with `pcmanfm-qt` now, so I think it has more to do with the recent qt5 update than keepassxc. Thanks anyway for your help.

**Comment by inoshy** [comment]
> Well… then… but this also needs to be ported then (if possible). Maybe we should open a new issue for this?

you are too dumb to open an issue. monke in human form

**Comment by inoshy** [comment]
> Hmm, anyway I've never such a bad thing and I think I've seen some other QT applications. So maybe it's some old version/particular problem, or do you e.g. use [this here](https://wiki.qt.io/QtWayland).
> 
> And are you sure you use no native X11 code by yourself? And even [in this old post from 2016](https://blog.qt.io/blog/2016/06/13/new-compositor-api-qtwayland/) they sounded quite positive… (the blue seemingly default window borders can also be seen there, but in the compositor example below you can see proper aligned window titles.)

eh! blaming devs like you paying for it. Fucking beggars everywhere

**Comment by develcooking** [comment]
for all  that are wondering. You need to set environment variables in your .desktop file before executing the application
`Exec=env QT_QPA_PLATFORM=wayland ECORE_EVAS_ENGINE=wayland_egl ELM_ENGINE=wayland_egl SDL_VIDEODRIVER=wayland _JAVA_AWT_WM_NONREPARENTING=1 MOZ_ENABLE_WAYLAND=1 keepassxc %f`

You need to put this execution environment variables into `/usr/share/application/org.keepassxc.KeePassXC.desktop`

and you need to have qt5-wayland installed `pacman -S qt5-wayland`

**Comment by untitled9074** [comment]
@e00E, thank you for sharing the "set proper env variables" solution! Works for me atm and I am very grateful 🙏 Could you please add the source for it? I assume it is a Qt "magic" and has to be documented somewhere. This way all affected users can keep an eye on the changes as things break again.

@droidmonkey when I launch KeePassXC (flatpak version if it matters) with the env variables suggested [above](https://github.com/keepassxreboot/keepassxc/issues/2973#issuecomment-581771317), I get the following errors:
```sh
QSocketNotifier: Can only be used with threads started with QThread
qt.qpa.qgnomeplatform: Could not find color scheme  ""
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
```

I read 3/4 as errors related to how KeePassXC uses Qt not as errors related to Qt's quality of Wayland support. But I am speculating here. Could you please advice which of the 4 errors should be reported upstream and which if any should be reported to KeePassXC team?

**Edit**: FWIW, Qt docs I found only [mention](https://wiki.qt.io/QtWayland) `QT_QPA_PLATFORM=wayland`. For me (Fedora 39, GNOME 45.2, nvidia 545.29.06, qt5-qtwayland.x86_64 5.15.11-1.fc39, KeePassXC 2.7.6) setting this variable produces the same result and stability it seems.

**Comment by droidmonkey** [comment]
None of those are errors. They are all caused by internal qt shenanigans. The first two are actually related to flatpak kde runtime, not us. The last two are an unnecessary info or debug output.

**Comment by OmniPelican** [comment]
And yet it's still an issue when install the application. There's something to be said for the reputation of ease of use.
Don't get me wrong. I'm grateful that people like you make these types of applications work and accessible.
I mean it as honest feedback.

**Comment by sascha-wi** [comment]
> You need to put this execution environment variables into `/usr/share/application/org.keepassxc.KeePassXC.desktop`
> 
> and you need to have qt5-wayland installed `pacman -S qt5-wayland`

Can you please link the exact contents of the desktop file? Because I am not sure how to format it properly.

**Comment by develcooking** [comment]
@sascha-wi 
content of  `/usr/share/application/org.keepassxc.KeePassXC.desktop`



`[Desktop Entry]`
`Name=KeePassXC`
`Exec=env QT_QPA_PLATFORM=wayland ECORE_EVAS_ENGINE=wayland_egl ELM_ENGINE=wayland_egl SDL_VIDEODRIVER=wayland _JAVA_AWT_WM_NONREPARENTING=1 keepassxc %f`
`Icon=keepassxc`
`StartupWMClass=keepassxc`
`StartupNotify=true`
`Terminal=false`
`Type=Application`
`Version=1.5`
`Categories=Utility;Security;Qt;`
`MimeType=application/x-keepass2;`
`SingleMainWindow=true`
`X-GNOME-SingleWindow=true`

**Comment by rugk** [comment]
> Because I am not sure how to format it properly.

FYI [just format it as code in Markdown](https://docs.github.com/de/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code), optionally adding `ini` as a language tag, if needed.

````md
```ini
[Desktop Entry]
Name=KeePassXC
...
```
````

**Comment by dinotheextinct** [comment]
~~Doesn't work for me:
`keepassxc[5622]: This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, xcb`~~

nvm I am stupid, I edited desktop file in /usr/share/app.. instead of ~/.local/share/apps... now it works.

**Comment by thePanz** [comment]
@dinotheextinct did it work for you? (which DE version are you using?)

My results: from running `QT_QPA_PLATFORM=wayland ECORE_EVAS_ENGINE=wayland_egl ELM_ENGINE=wayland_egl SDL_VIDEODRIVER=wayland _JAVA_AWT_WM_NONREPARENTING=1 keepassxc` directly from the KDE konsole gives me the two warnings as before:
```
keepassxc[10290]: qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
keepassxc[10290]: qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
```

Plus the UI of KeePassXC is not using the same Mouse icons of my KDE Plasma v6

system details:
```
Operating System: Arch Linux 
KDE Plasma Version: 6.0.1
KDE Frameworks Version: 6.0.0
Qt Version: 6.6.2
Kernel Version: 6.7.8-arch1-1 (64-bit)
Graphics Platform: Wayland
```

KeePass debug info:
```
KeePassXC - Version 2.7.6
Revision: dd21def

Qt 5.15.12
Debugging mode is disabled.

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 6.7.8-arch1-1

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 3.3.0
```
