### ISSUE TITLE
Hide username throughout app when Hide Usernames option is used

### ISSUE THREAD

**Issue by sebast889** [keepassxreboot/keepassxc#2974]
With the Hide Usernames option enabled in the view I think it makes sense to also hide it and show a eye icon next to it just like for passwords. Currently the username is visible when an entry is clicked on (in general tab) and also when an entry is clicked into.

**Comment by droidmonkey** [comment]
This would needlessly complicate the UI. Usernames are generally not nearly as sensitive or unique as passwords.
