### ISSUE TITLE
Retina support for database icons

### ISSUE THREAD

**Issue by ligyxy** [keepassxreboot/keepassxc#2977]
## Summary
The current data icons are quite rough in retina screens. 
https://cl.ly/039617

## Desired Behavior
Use icons with higher resolution.

## Possible Solution
Looks like the icons are from Nuvola icon set created by David Vignoni. 
A full list of icons might be found in the following places:
https://commons.wikimedia.org/wiki/Category:Nuvola_icons
https://www.iconfinder.com/iconsets/nuvola2

Or it could be replaced with a new, non-Nuvola icon set. 
Here are some examples using different icon sets:
Keepassium https://keepassium.com/
MacPass https://github.com/MacPass/MacPass/tree/master/Assets/Icons%20as%20PDF%20files

**Comment by droidmonkey** [comment]
Those icons are ancient, and in my opinion, need to be completely replaced. They are actually from the original KeePass.

![image](https://user-images.githubusercontent.com/2809491/55958905-af914280-5c37-11e9-8371-c74dd44abbf4.png)

**Comment by phoerious** [comment]
It's just a bunch of tiny Nuvola icons. Ugly now as always.

**Comment by ligyxy** [comment]
I would also like to mention that, the icon of the toolbar is also fuzzy on Mac's retina screen. and I doubt if it's well scaled.
https://cl.ly/651458

**Comment by phoerious** [comment]
Closing this in favour of 475.
