### ISSUE TITLE
key is removed from sshagent upon closing keepassxc

### ISSUE THREAD

**Issue by PF93mc8y7erq92qTmTjJBysALa** [keepassxreboot/keepassxc#2980]
Unlike with the previous version, keys are removed from the ssh agent upon closing KeePassXC.
At first glance, it seemed the setting "Remove key from agent when database is closed/locked" although unchecked, was being ignored when closing the database by closing KeePassXC itself.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
I expect the key to still be available in the agent after closing the database **and** KeePassXC 2.4.0, as was the case with KeePassXC 2.3.4.

## Current Behavior
[NOTE]: # ( Tell us what actually happens )
Current settings are as follows:
 - on/checked: Add key to agent when database is opened/unlocked
 - off/unchecked: Remove key from agent when database is closed/locked
 - off/unchecked: Require user confirmation when this key is used
 - off/unchecked: Remove key from agent after 600 seconds

The key remains in the agent after closing the database but not after closing KeePassXC. From what I recall, the key remained in the agent when using KeePassXC 2.3.4 after closing KeePassXC.

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )
Perhaps I was relying on an undefined/undocumented feature when using the previous version. 

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1. Have a database with a private key (in my case this is an external file)
2. Configure the SSH Agent for this entry with as above (add key when opened/unlocked and none of the remove required)
3. Close KeePassXC
4. Remove keys from agent (`$ ssh-add  -D`)
5. Start KeePassXC
6. Open/Unlock database
7. Verify that the key has been added to the agent (`$ ssh-add -l`)
8. Close the database (*Database Menu / close database*)
9. Verify that the key is still in the agent (`$ ssh-add -l`)
10. Close KeePassXC (*KeePassXC Menu / Quit KeePassXC*)
11. Verify that the key is no longer in the agent (`$ ssh-add -l`)

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )
My workflow previously had been to open the database with KeePassXC to add several keys to the ssh agent. This was followed by closing KeePassXC, opening later if/when needed (for other credentials).
My current workaround is to keep KeePassXC, locking and unlocking the database as needed, so that the keys stay in the ssh agent.

Before creating this issue report I searched for already reported issues and came across the following, which seemed related: 
#2902 

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.4.0
Revision: c51752d

Libraries:
- Qt 5.12.2
- libgcrypt 1.8.4

Operating system: macOS Mojave (10.14)
CPU architecture: x86_64
Kernel: darwin 18.5.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (only unsigned sharing)
- YubiKey
- TouchID

**Comment by droidmonkey** [comment]
This seems to have been the behavior even in 2.3.4. When SSHAgent was destructed it went through each key and removed the identity from the agent.

https://github.com/keepassxreboot/keepassxc/blob/6fe821c30ec747e7fda0a8abe75d774d61a21054/src/sshagent/SSHAgent.cpp#L38-L45

I personally think this is the appropriate behavior.

**Comment by PF93mc8y7erq92qTmTjJBysALa** [comment]
I just reinstalled v2.3.4 and performed the steps to reproduce listed. After closing KeePassXC, the keys are still in the agent.
Perhaps that was not the intended behavior with 2.3.4 - which contained the bug that keys were not removed when closing KeePassXC.

**Comment by droidmonkey** [comment]
Yes that is my thought as well. The problem with leaving the keys in place when KeePassXC is explicitly shutdown is that we are not cleaning up after ourselves. Perhaps there can be an additional setting of "Keep key in agent after KeePassXC shutdown" which would be available if the "Keep key in agent after database lock" is enabled.

**Comment by PF93mc8y7erq92qTmTjJBysALa** [comment]
> cleaning up after ourselves

KeePassXC 2.4.0 removes keys from the ssh agent even if those keys were added to the agent before KeePassXC was started.

**Comment by PF93mc8y7erq92qTmTjJBysALa** [comment]
Browsing the source, it appears as if in 2.3.4 m_keys was being populated only for keys with the option "remove at lock". For 2.4.0 m_addedKeys is being populated also in addIdentity.

See #2503
https://github.com/keepassxreboot/keepassxc/blob/62dc4f49d43dcbd4e79de6696352af96eb537e68/src/sshagent/SSHAgent.cpp#L216

**Comment by hifi** [comment]
If the remove-on-lock option is *not* set KeePassXC should not remove a key from the agent, even on exit. The user may want to just add keys the first time they open a database and leave them there, that's why remove-on-lock is an option.

@PF93mc8y7erq92qTmTjJBysALa correctly identified `m_keys` only had keys that had the remove on lock option set and the refactor changed that behavior.

**Comment by droidmonkey** [comment]
WABAM, your wish is my command

**Comment by PF93mc8y7erq92qTmTjJBysALa** [comment]
@droidmonkey 
@hifi 
fixed in 2.4.1, thanks!
