### ISSUE TITLE
Settings GUI scale for Windows?

### ISSUE THREAD

**Issue by 648643579** [keepassxreboot/keepassxc#2981]
use: KeePassXC 2.4.0 "Windows"

Hi, Is there any possibility of setting up GUI Scale in windows? (I would need a setting of > 150%)
If not really I would welcome this feature.

**Comment by droidmonkey** [comment]
Please see https://doc.qt.io/qt-5/highdpi.html#high-dpi-support-in-qt

**Comment by 648643579** [comment]
@droidmonkey 
Thank you, unfortunately I don't know how to set up.
in the command line, the program starts but does not change the DPI
`KeePassXC.exe -platform windows:dpiawareness=2`

I wanted to create a file "qt.conf" in which the command to change the DPI setting but I do not know the exact syntax.
can you please advise me?

**Comment by droidmonkey** [comment]
You don't want to mess with the dpiawareness setting. You want to create an environment variable that scales the UI to match your windows scaling. Here are some quick and dirty screenshots to get you going:

![image](https://user-images.githubusercontent.com/2809491/55958021-b8811480-5c35-11e9-8d7d-e9bc91d99eda.png)

![image](https://user-images.githubusercontent.com/2809491/55958057-c9318a80-5c35-11e9-803b-3366e3235d01.png)

![image](https://user-images.githubusercontent.com/2809491/55958334-5b399300-5c36-11e9-976c-12bb479fb99c.png)

**Comment by sebast889** [comment]
Off topic but @droidmonkey how did you create the screenshots with arrows/blur? It's nice

**Comment by droidmonkey** [comment]
Snagit, I absolutely love it

**Comment by affinityv** [comment]
> Snagit, I absolutely love it. https://www.techsmith.com/store/snagit

http://freshmeat.sourceforge.net/projects/scrot/
Unless it is Winblows.... then just use the "built-in" snipping tool.

Other options:
https://alternativeto.net/software/scrot/

**Comment by deron-dev** [comment]
For those on Linux who end up here (though I think you can do this on Windows, too), if you don't want to run the same scale for all Qt apps, you can run the application like

```bash
QT_SCALE_FACTOR=1.5 keepassxc
```
I have this bound to SUPER + K on Hyprland, and it works great.
