### ISSUE TITLE
Entry URLs should allow "exact" match

### ISSUE THREAD

**Issue by pridetechdesignllc** [keepassxreboot/keepassxc#2986]
## Summary
[NOTE]: Exact matching for URL field

## Desired Behavior
[NOTE]: If I put in the URL field "somedomain.com", it should match any instance of "somedomain.com", but if I put in "https://somedomain.com" it should ONLY match "https://somedomain.com".

## Context
[NOTE]: If I have a terminal window that has the domain name in it's title, keepass will match it for webapps. That is obviously frustrating as it leads to a huge list of matched passwords, when it should only match for terminal-relevant passwords.

**Comment by varjolintu** [comment]
KeePassXC Preferences -> Browser Integration -> [x] Return only best-matching credentials

**Comment by pc-erin** [comment]
I tried enabling this option and it still activated the prompt for a subdomain.

**Comment by varjolintu** [comment]
@pc-erin I'm pretty sure there's already a feature request about this somewhere. Just couldn't find it.

**Comment by pc-erin** [comment]
#6454 looks similar
