### ISSUE TITLE
Ctrl-PgUp / Ctrl-PgDown tab order doesn't match Ctrl-Tab / Ctrl-Shift-Tab

### ISSUE THREAD

**Issue by NiceGuyIT** [keepassxreboot/keepassxc#2988]
## Summary
`Ctrl-PgUp` / `Ctrl-PgDown` should match `Ctrl-Tab` / `Ctrl-Shift-Tab` with regard to moving to the "next" tab.

## Desired Behavior
In most applications, `Ctrl-PgDown` and `Ctrl-Tab` move to the tab to the right while `Ctrl-PgUp` and `Ctrl-Shift-Tab` move to the tab to the left. In KeePassXC, `Ctrl-PgDown` moves to the left and `Ctrl-PgUp` moves to the right. This is opposite the `Ctrl-Tab` and `Ctrl-Shift-Tab` functionality in KeePassXC and how most other applications treat `Ctrl-PgDown` / `Ctrl-PgUp`.

## Possible Solution
Please change the tab order for `Ctrl-PgDown` / `Ctrl-PgUp` to match other applications.

## Context
This is a minor usability issue with respect to using the `Ctrl-PgDown` / `Ctrl-PgUp` keyboard shortcuts to move between tabs in an application. In case it's not clear, I'm referring to the database tabs in KeePassXC.

I'm using v2.4.0 revision: c51752d on Linux / Windows / Mac. This functions the same on all 3 environments. On the Mac, `Fn-Cmd-Up` is the same as `Ctrl-PgUp` and moves to the tab to the right. `Fn-Cmd-Down` is the same as `Ctrl-PgDown` and moves to the tab to the left.

**Comment by droidmonkey** [comment]
Interesting. I associated "UP" with "next" (ie, Right). Easy fix.

**Comment by droidmonkey** [comment]
Fixed in b97cc1
