### ISSUE TITLE
Application is blurring when running with fractional display scaling on Gnome 3.32 with Ubuntu 19.04

### ISSUE THREAD

**Issue by jay-tuckey** [keepassxreboot/keepassxc#2993]
Hi, I'm running KeepassXC 2.4.1 as a snap in Gnome Shell 3.32 on Ubuntu 19.04. I have fractional scaling turned on to allow me to make things larger on my laptop screen:
```
~> lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu Disco Dingo (development branch)
Release:	19.04
Codename:	disco
~> uname -a
Linux jay-t470s-ubu 5.0.0-8-generic #9-Ubuntu SMP Tue Mar 12 21:58:11 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
~> apt list gnome-shell
Listing... Done
gnome-shell/disco,now 3.32.0+git20190410-1ubuntu1 amd64 [installed,automatic]
```
When I turn on fractional display scaling, and change the scaling to 150%, the application shows at the correct size, but is blurry. It would be nice if the application could render correctly when scaled. This isn't a serious issue when using the application, just a nice-to-have.

To turn on fractional scaling in Ubuntu 19.04 you need to run:
```
~> gsettings set org.gnome.mutter experimental-features "['scale-monitor-framebuffer']"
~> gsettings get org.gnome.mutter experimental-features 
['scale-monitor-framebuffer']
```
Debug info from KeepassXC:
```
KeePassXC - Version 2.4.1
Revision: 7bafe65
Distribution: Snap

Qt 5.9.5
Debugging mode is disabled.

Operating system: Ubuntu Core 18
CPU architecture: x86_64
Kernel: linux 5.0.0-8-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.1
```
Please let me know if there's any further info you need, or any way I can assist.

**Comment by droidmonkey** [comment]
See https://doc.qt.io/qt-5/highdpi.html
