### ISSUE TITLE
What is KeeShare?

### ISSUE THREAD

**Issue by rugk** [keepassxreboot/keepassxc#2999]
There seems to be a new feature called "KeeShare" in v2.4.0, but I mostly just see empty GUIs with empty list views. And two checkboxes "Enable import" and "Enable export" that seem to do… ehm… nothing?
I also see buttons that do nothing ("trust", "do not trust", …) and in the database settings I see another GUI that has an entirely empty list view and no way to insert anything/interact.

And the list views have no buttons at all that would allow me to add anything to them. I would have expected a button "Open file" or so, then I can at least try to open some files(?). But well… I also have no idea what files I would choose… :laughing: 

This feature is really puzzling for me…

It's also nowhere documented.

---

So maybe you need to improve the UX for that a little? First, there should not be empty GUIs without any explanation for a feature that is not straightforward.

Secondly, buttons that currently cannot do anything, should be disabled.

Thirdly, when I enable a checkbox, I want to see something happen or so. I can toggle these, but I have no idea what they actually do…

Also opened https://github.com/keepassxreboot/keepassxreboot.github.io/issues/57 for website doc for that feature. Maybe you can also link to the website doc from the application, if you need to explain things a little more.

**Comment by droidmonkey** [comment]
We have full documentation being developed right now. KeeShare is a part of that documentation.

**Comment by akomm** [comment]
@droidmonkey and where can you see the current state of the documentation? Is it open-source?

**Comment by Adirelle** [comment]
Any update ? Or is the partial documentation available somewhere ?

**Comment by rugk** [comment]
Indeed, I have a new feature in KeePassXC for months now, but I don't know how to use it or even what it is… cause… well… documentation… 📜

This is really a mystery for me… :laughing:

**Comment by rugk** [comment]
Some helpful pecker pointed me to this doc: https://github.com/keepassxreboot/keepassxc/blob/develop/docs/QUICKSTART.md#using-sharing

**Comment by droidmonkey** [comment]
This is better tracked under #3220

**Comment by danielkr123** [comment]
> Some helpful pecker pointed me to this doc: https://github.com/keepassxreboot/keepassxc/blob/develop/docs/QUICKSTART.md#using-sharing

Documentation has moved and can be found here now:
https://github.com/keepassxreboot/keepassxc/blob/develop/docs/topics/KeeShare.adoc

**Comment by morciej** [comment]
So, let me get it straight. You have documentation that refers to a feature that is not yet implemented?

See two screen shots below. How are these supposed to refer to the same thing? How is a user supposed
to display the "Personal certificate" section of the window?

I have a GPG certificate BTW. Dragging it from Seahorse window does nothing.

![as-documented](https://user-images.githubusercontent.com/17895139/114218348-285a3080-991e-11eb-8011-79b70b427ddd.png)
This  is what has been documented

![as-implemented](https://user-images.githubusercontent.com/17895139/114218358-2abc8a80-991e-11eb-9986-283f99e19b2c.png)
This is what I see as of ver. 2.4.3 in Linux Mint ulyssa/focal
???

**Comment by rugk** [comment]
It is implemented and it works. You cannot use other keys AFAIK, you need to generate them with KeePassDX.
The doc for that feature now seems to live here:
https://keepassxc.org/docs/KeePassXC_UserGuide.html#_database_sharing_with_keeshare

**Comment by morciej** [comment]
No I cannot. There is no "Generate", "Import" or "Export" button, and no "Signer:", "Key:", "Certificate:", or "Fingerprint:" fileds.

**Comment by droidmonkey** [comment]
Ignore this feature, certificates are going away in 2.7.0. Just use the kdbx version of keeshare when you create a share.

**Comment by morciej** [comment]
I see, thanks.
