### ISSUE TITLE
add_feature_info --- unknown to Cmake on Mac

### ISSUE THREAD

**Issue by CoderJason123** [keepassxreboot/keepassxc#3000]
Hello.  I followed the Mac OS instructions, installed all the dependencies, and I am not able to build.  Originally the instructions said to make a build direction and build from there, but it couldn't find Cmake lists.  So I build from src.  Any thoughts on the error?

My Cmake options are 
-DCMAKE_INSTALL_PREFIX=/users/Me/documents/ -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_BUILD_TYPE=Release -DWITH_XC_AUTOTYPE=ON -DCMAKE_PREFIX_PATH=/usr/local/cellar/qt/5.12.2/lib/cmake/

CMake Error at CMakeLists.txt:191 (add_feature_info):
  Unknown CMake command "add_feature_info".

**Comment by phoerious** [comment]
Do not forget the `..` at the end of the `cmake` command.

**Comment by CoderJason123** [comment]
this is not the issue, I wish it was.  I was able to add include(FeatureSummary) and make it work.  I did already have .., just didn't paste it.  Adding the above command helped.  I am using auto type but now get stopped at  install TARGETS given no LIBRARY DESTINATION for module target
  "keepassx-autotype-cocoa"

this is the only module I need at the moment.  Looking at the doc, the specific libraries were not clear for auto type.  Please assist me.

**Comment by CoderJason123** [comment]
Never mind --- honestly, after I build from the src directory, instead of build. it worked, and frankly I might have read the doc wrong.  thank you kindly.  I just thought I was missing a step.
