### ISSUE TITLE
Auto-Type doesn't work when app is shown as a workspace

### ISSUE THREAD

**Issue by sparstormo** [keepassxreboot/keepassxc#3003]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Auto-Type should put the Username and password into the browser window.

## Current Behavior
[NOTE]: # ( Tell us what actually happens )
It puts the password in the keepass searchbar.

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )
It was working correctly in 2.3.

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1. Open your Firefox browser to a login page.
2. Highlight the corresponding entry in your keepass database.
3. Press Auto-Type button or keyboard short-cut.

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )
I now have to go back and forth from keepass to the webpage copying both the username and the password.

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.4.1
Revision: REVISION

Libraries:
- LIBS

Operating system: OSX
CPU architecture: ARCH
Kernel: KERNEL

Enabled extensions:
- EXTENSIONS

**Comment by sparstormo** [comment]
I should add that it appears to work correctly when the browser is in the desktop but not when it is in a workspace.

**Comment by droidmonkey** [comment]
What is the difference between a desktop and a workspace? The behavior was updated in 2.4.1 to always minimize the KeePassXC window before performing the auto-type action. It should be *impossible* to type into the search box.

**Comment by sparstormo** [comment]
Jonathan,

In OSX the desktop is when you don't have the window full screen. You can
have windows of various sizes that all sit on the desktop. When you open up
to full screen (click the green button in the upper left corner) it moves
the window off the desktop to a workspace. If you do a three finger swipe
on the touch pad it (or press the Mission Control button, f3) will show you
the dashboard, desktop, and your open work spaces at the top of the screen.

I've done some more testing and here are the configurations and outcomes:

1) If the browser and keepassxc are both on the desktop then Auto-Type
appears to work as intended.
2) If the browser is in a workspace and keepassxc is on the desktop then it
prints the information to another app (like in my case Apple notes)
3) If both the browser is on the desktop and keepassxc is in a workspace
then sometimes it prints to another application (like the terminal if its
open) or to the keepassxc searchbar.
4) If both are in different workspaces then it seems to behave like #3
above.

I'm using Firefox Developer Edition 67.0b10 and OSX Mojava 10.14.4

If  you can't duplicate this behavior, please let me know because it
perhaps means my computer has a problem.

I hope this helps.

Spar

**Comment by droidmonkey** [comment]
Oh great that is fantastic information. So a workspace is similar to maximizing the application? Either way, it seems we need to call different functions depending on the state of the applications.

**Comment by sparstormo** [comment]
I might have the term wrong. It might really just be another desktop.
Regardless, Auto-Type does weird stuff if there is not a browser with the
right fields available in the same desktop. It seems like it finds a cursor
somewhere and pastes to it.

**Comment by seguri** [comment]
Same here. KeePassXC 2.4.0 (2.4.1 not available as cask) opened in a "normal" window on the desktop. When I press autotype (why did you change the shortcut from cmd-v to cmd-shift-v?) it will insert my password in the search bar.
I've not found any combination of desktops/windows that works.

**Comment by kitingChris** [comment]
> When I press autotype (why did you change the shortcut from cmd-v to cmd-shift-v?) it will insert my password in the search bar. 
Ah so it did not just confuse me!

**Comment by l0f4r0** [comment]
From my side, KeePassXC 2.5.3 Autotype under Linux Debian 10 is totally inconsistent indeed.
It rarelly does what I expect it to do. Either it does nothing at all, or only gives focus to KeePassXC window, or autotypes with missing characters...

NB: I have no issue under Windows.

**Comment by droidmonkey** [comment]
Are you running Wayland? That's why it's inconsistent.

**Comment by l0f4r0** [comment]
> Are you running Wayland? If so, that's why it's inconsistent.

No, x11

**Comment by droidmonkey** [comment]
Well we'll need way more information about your use cases on Debian to understand why its not working.

**Comment by l0f4r0** [comment]
> Well we'll need way more information about your use cases on Debian to understand why its not working.

Vivaldi 2.10.1745.27 (Stable channel) (64 bits)
KeePassXC 2.5.3
Debian 10 with kernel 5.4.0-0.bpo.2-amd64

Example: I have a simple Autotype entry {USERNAME}{TAB}{PASSWORD}{ENTER} for https://mon.allocine.fr/connexion called "Allociné".
When I click Ctrl+Alt+Y, Autotype is triggered, a popup with my "Allociné" entry appears but after clicking on it, either 1) nothing happens or 2)fields are filled in but some login letters are missing so it doesn't work. Sometimes, popup never appears (I don't know if Autotype is not triggered at all or if it's just a popup issue)...

**Comment by l0f4r0** [comment]
Weird enough, only letter "aA" is missing when Autotype is filling in fields (at least in {USERNAME}, I can't verify in {PASSWORD})!

**Comment by droidmonkey** [comment]
This could be that you are still holding down the modifier keys when typing starts. Try adding a longer delay in the auto-type settings.

![image](https://user-images.githubusercontent.com/2809491/74587997-da21f980-4fc6-11ea-957a-78b1daa60329.png)

**Comment by l0f4r0** [comment]
How could it be connected to the issue? I don't understand the logic (letters "aA" could be anywhere in {USERNAME}...).
Anyway, I've tested that with no improvement ;)

**Comment by droidmonkey** [comment]
Ah I thought you meant just from the beginning of the autotype.

**Comment by l0f4r0** [comment]
> hought you meant just from the beginning of the autotype. If you are using an alternate keyboard layout then this is a known issue on linux.

I'm using Generic 105-key PC (intl.) - french layout.
So it's known issue?

**Comment by droidmonkey** [comment]
See #2475 and #374

**Comment by droidmonkey** [comment]
Fixed in 2.7.0
