### ISSUE TITLE
Observed issues with cryptomator software

### ISSUE THREAD

**Issue by luixxiul** [keepassxreboot/keepassxc#3004]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

### Description of the issue:

Existing database file created on the virtual drive mounted with Cryptomator gets corrupted after updating to `2.4.1` if "Backup database file before saving" is enabled.

### Steps to Reproduce:
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1. Install Cryptomator
2. Mount a virtual drive
1. Create a database on the previous version on the virtual drive
2. Enable `Backup database file before saving` on the preference setting
3. Update KeePassXC to `2.4.1`
4. Re-open the database
5. Edit the file 
6. Save
6. Close the database 
7. Re-open it

### Current Behavior:

The database file cannot be opened due to `Error while reading the database: Not a KeePass database.`

The backed up file can be opened.

### Expected Behavior:

The database file should be opened

### Possible Solution:
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )

### Context:
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )

The issue cannot be reproduced on the fresh database created on `2.4.1`. 

`Safely save database files` is not enabled because that does not work on the virtual drive mounted with Cryptomator.

### Debug Info:
[NOTE]: # ( Paste debug info from Help → About here )

KeePassXC - Version 2.4.1
Revision: 7bafe65

Qt 5.12.2
Debugging mode is disabled.

Operating system: Windows 10 (10.0)
CPU architecture: x86_64
Kernel: winnt 10.0.17134

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.4

**Comment by luixxiul** [comment]
The issue also can be reproduced by importing the CSV file which has been created on the previous version.

**Comment by droidmonkey** [comment]
To be clear, does the error display when you try to open the original database file and the backup file, or just the original?

**Comment by luixxiul** [comment]
> 
> 
> To be clear, does the error display when you try to open the original database file and the backup file, or just the original?

Both files cannot be opened.

**Comment by droidmonkey** [comment]
I installed cryptomator and attempted your reproduction steps, but could not cause corruption to occur. Creating a database in 2.3.4 (portable) using your settings worked fine, made multiple edits, ok. Confirmed that safe saves do not work with cryptomator. Opened the same database with 2.4.1 (installed) and made changes. Locked database. Unlocked without issues.

An observation, you absolutely do not need to put a kdbx file in a cryptomator mount. The entire database is already encrypted with AES encryption. Encrypting encrypted data offers no additional protection.

**Comment by luixxiul** [comment]
ok- so which information might be helpful here?

**Comment by luixxiul** [comment]
If you open the original file with sublime text, you'll notice that it has been added with a lot of lines like:
````
0000 0000 0000 0000 0000 0000 0000 0000
0000 0000 0000 0000 0000 0000 0000 0000
0000 0000 0000 0000 0000 0000 0000 0000
0000 0000 0000 0000 0000 0000 0000 0000
0000 0000 0000 0000 0000 0000 0000 0000
0000 0000 0000 0000 0000 0000 0000 0000
0000 0000 0000 0000 0000 0000 0000 0000
0000 0000 0000 0000 0000 0000 0000 0000
````

**Comment by droidmonkey** [comment]
Those options have absolutely nothing to do with the file saving process.

**Comment by luixxiul** [comment]
Yeah, I confirmed that issue can only be reproduced on the virtual drive mounted on Cryptomator. It is not reproduced on the local drives.

**Comment by droidmonkey** [comment]
Whether a file is created on the virtual drive or drag/dropped doesn't make any difference to KeePassXC.

**Comment by luixxiul** [comment]
So is this a compatibility issue that should be fixed by Cryptomator's side?

**Comment by droidmonkey** [comment]
I'm not blaming cryptomator at this point, it doesn't care a lick about what files are being stored or applications accessing them. However I find it highly suspect that the database file is all 0's. KeePassXC certainly does not write that information. If anything it would be random data.

**Comment by luixxiul** [comment]
The issue has been reported here by another user: https://github.com/cryptomator/cryptomator/issues/875. In favor of that I'm going to close this issue as invalid. I reported this issue on https://github.com/cryptomator/cryptomator/issues/873

**Comment by luixxiul** [comment]
The issue has been reported here by another user: https://github.com/cryptomator/cryptomator/issues/875. In favor of that I'm going to close this issue as invalid. I reported this issue on https://github.com/cryptomator/cryptomator/issues/873

**Comment by droidmonkey** [comment]
Yikes that is a scary bug on their end.

**Comment by luixxiul** [comment]
Update: the issue looks to have been fixed on their side. The issue is no longer experienced on my side.

**Comment by droidmonkey** [comment]
Great, I actually am using their software now as well, works very nicely. Thank you for introducing me to it!
