### ISSUE TITLE
Scrolling extremely sluggish on macOS

### ISSUE THREAD

**Issue by heapifyman** [keepassxreboot/keepassxc#3007]
Since updating to version 2.4.0 (also with latest version 2.4.1) scrolling in the list of Logins is extremely sluggish. 
I have a few hundred (maybe 400) entries in my list of logins and when I scroll up and down in that list using the touchbar the scrolling is not as smooth as I am used to on Mac OS. It is very slow and often stops.

KeePassXC - Version 2.4.1
Revision: 7bafe65

Qt 5.12.2
Debugging mode is disabled.

Operating system: macOS Mojave (10.14)
CPU architecture: x86_64
Kernel: darwin 18.5.0

Enabled extensions:
- Auto-Type
- Browser-Integration
- SSH-Agent
- KeeShare (only unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
 libgcrypt 1.8.4

**Comment by droidmonkey** [comment]
Does this occur for you in a group that does NOT have hundreds of entries? Seems like it could be a Qt bug as well.

**Comment by heapifyman** [comment]
Yes, it does

**Comment by droidmonkey** [comment]
I cannot replicate this behavior on my mac mini.

**Comment by heapifyman** [comment]
My machine is a Macbook Air (Mid 2012). It's pretty old but I do not experience any scrolling issues in any other application.

**Comment by weslly** [comment]
I can't reproduce this on my mac mini (late 2012) and ~500 entries. I tried scrolling with my magic mouse and a normal mouse but both are pretty smooth.

**Comment by larslaade** [comment]
On my machine it is slow/sluggish as well, macbook pro 13 inch (mid 2014), 10.14.4 with keepassxc 2.4.1
Entry count does not matter, even a small amout to scroll is sluggish/slow.
Scrolled via touchbar and normal Mouse, even via dragging the scrollbar.

**Comment by 6Vmf2y48AaGbfTD2-vfDsr759VA49m-uePFkE** [comment]
I see the same issue.
Scrolling in the groups is as expected, scrolling in the list of entries can be sluggish.

When the window is resized such that only a few columns are displayed (title, username, url), it seems to me scrolling is not so sluggish. (What is still sluggish in that case is changes in direction.) However, once the window is resized such that more of the date-containing colums appear, the sluggishness cannot be mistaken. That is, scrolling seems sluggishest when columns created, modified, and accessed are shown, less so when just two (created and modified) are shown, less yet when just one (created).

I bet that helps. Cheers. :D



KeePassXC - Version 2.4.1
Revision: 7bafe65

Qt 5.12.2
Debugging mode is disabled.

Operating system: macOS High Sierra (10.13)
CPU architecture: x86_64
Kernel: darwin 17.7.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (only unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
 libgcrypt 1.8.4

**Comment by droidmonkey** [comment]
@6Vmf2y48AaGbfTD2-vfDsr759VA49m-uePFkE are you using a retina display?

**Comment by droidmonkey** [comment]
This is very likely a bug in Qt. I cannot find an existing bug report on the Qt issue board, but it could have been introduced with Qt 5.12 which is what we upgraded to with the 2.4.x series.

**Comment by 6Vmf2y48AaGbfTD2-vfDsr759VA49m-uePFkE** [comment]
I have seen it on an older iMac:
 iMac (21.5-inch, Mid 2011)

using built-in Display
 - 21,5-inch (1920 x 1080)
 - AMD Radeon HD 6750M 512 MB graphics

**Comment by 6Vmf2y48AaGbfTD2-vfDsr759VA49m-uePFkE** [comment]
I experimented a bit with this yesterday. After the trials I would no longer claim that the slow scrolling comes merely from having the date columns shown. Resizing the KeePassXC window such that some but not all of the columns were shown, even if all three date columns were shown, seemed to be enough to speed up scrolling. Mind you the list of groups on the left does not appear affected.

What can be done to provide the detailed info you need to isolate the issue? Building the Debug variant of the application? Would you like a small video of the scrolling?

**Comment by PF93mc8y7erq92qTmTjJBysALa** [comment]
I see the same and found a possibly related bug report, [QTBUG 70704](https://bugreports.qt.io/browse/QTBUG-70704). It discusses some of the same symptoms but apparently is limited to just scrollbar scrolling.

In my case, scrolling with the scrollbars is faster than scrolling with the touchpad.

Furthermore, scrolling (via flicking/mouse) seems faster after reseting the column widths to "Fit to Window". Scrolling seemed worse after I then adjusted all columns manually, making each a tick wider.

**Comment by droidmonkey** [comment]
They were a few bugs in the Qt board about scrolling, but none seemed relevant. I'll see if I can create a minimal example that replicates the kpxc environment without all the distractions.

**Comment by krugerk** [comment]
I had seen this previously but not (yet) once with 2.6.0 on macos 10.15.x.

**Comment by heapifyman** [comment]
yes, seems to have been fixed with 2.6.0
