### ISSUE TITLE
Support clearing KDE Plasma 5.12 clipboard

### ISSUE THREAD

**Issue by kozaq** [keepassxreboot/keepassxc#3008]
## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
KDE Plasma's 5.12 clipboard should be cleared after 10 seconds (period specified in settings). Please note that KDE Plasma 5 does not use Klipper anymore. KDE Plasma 5.12 has it's own Plasma's clipboard manager.

## Current Behavior
[NOTE]: # ( Tell us what actually happens )
Clipboard is not cleared after 10 seconds.

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1. Open KeePassXC
2. Unlock the database
3. Copy username or password
4. Wait 10 seconds (the period specified in Settings > Security > Clear clipboard after)
5. Press Ctrl+V to paste content of clipboard to any application 

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC 2.4.1

Operating system: Kubuntu 18.04.2 LTS (Bionic Beaver)
CPU architecture: x86_64
Kernel: 4.15.0-47-generic

KDE Plasma version:
5.12.7

**Comment by droidmonkey** [comment]
From plasma-workspace 5.12.8 the "x-kde-passwordManagerHint" is supported, so in Ubuntu Cosmic (which has 5.13.5) it should work.

**Comment by droidmonkey** [comment]
Associated code for KeePassX was proposed here: https://github.com/keepassx/keepassx/pull/211

**Comment by droidmonkey** [comment]
@kozaq it looks like the actual fix on Klipper's end was nost merged until 5.12.8. You are one third digit build away. I am closing this issue because there is nothing further we can do.

**Comment by kozaq** [comment]
Thanks anyway, it looks I have to wait until Plasma update for Kubuntu 18.04 (I don't want Cosmic as it's non-LTS).
