### ISSUE TITLE
Design broken on Linux Mint 19.1

### ISSUE THREAD

**Issue by ledermueller** [keepassxreboot/keepassxc#3009]
Since the update to 2.4.1 from the official PPA the design of keepassxc is huge. It is nearly impossible to find entries or do anything in the window.
My current resolution is 1920x1080 and the keepass window does not fit onto the desktop.
Also the tray icon seems to have a wrong resolution.
Already tried to reinstall but no luck.

## Expected Behavior
The design and size of the previous version was perfect.

## Debug Info
KeePassXC - Version 2.4.1
Revision: 7bafe65

Qt 5.9.5
Debugging mode is disabled.

Operating system: Linux Mint 19.1
CPU architecture: x86_64
Kernel: linux 4.18.0-17-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (only unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.1

![keepass_design_broken](https://user-images.githubusercontent.com/722521/56120999-90641f00-5f6f-11e9-859a-8b31da3871e5.png)

**Comment by rsavjani** [comment]
I +1 this.
Im running GDM on Debian Stretch and new UI is huge and not usable.

**Comment by droidmonkey** [comment]
Please do a search for huge ui, you'll find your answer. It's a Qt bug

**Comment by ledermueller** [comment]
Thanks for the hint. I was able to resolve the issue for me by adding the following to the menu entry (created by the PPA version):
```
env QT_AUTO_SCREEN_SCALE_FACTOR=0 
```

**Comment by ledermueller** [comment]
#2815
