### ISSUE TITLE
LSOpenURLsWithRole() failed with error -10810 for the file /Applications/KeePassXC.app.

### ISSUE THREAD

**Issue by hovancik** [keepassxreboot/keepassxc#301]
## Expected Behavior

App should start

## Current Behavior

```
open /Applications/KeePassXC.app
LSOpenURLsWithRole() failed with error -10810 for the file /Applications/KeePassXC.app.
```

## Steps to Reproduce (for bugs)

1. brew update && brew install keepassxc
2. open /Applications/KeePassXC.app

## Your Environment

* KeePassXC version/commit used: (can be found under Help -> About) KeePassXC-2.1.1
* Qt version (e.g. Qt 5.3): 
* Compiler (e.g. Clang++3.6.0): 
* Operating System and version: macOS 10.11.6

**Comment by phoerious** [comment]
Is this with or without KeePassHTTP? KeePassHTTP only works on 10.12, unfortunately.

**Comment by hovancik** [comment]
```
brew cask install keepassxc 
==> Downloading https://github.com/keepassxreboot/keepassxc/releases/download/2.1.1/KeePassXC-2.1.1-HTTP.dmg

```

Ah, I guess it's HTTP then .

**Comment by phoerious** [comment]
Yeah, that's with HTTP. Try the DMG without from our website.
We are working on getting KeePassHTTP to run on Mac OS X < 10.12, but right now libmicrohttpd is giving us a headache.

**Comment by hovancik** [comment]
Thanks for your efforts, non HTTP version works ;]

**Comment by phoerious** [comment]
Duplicate of #265
