### ISSUE TITLE
Update notification gets in the way when user enters password

### ISSUE THREAD

**Issue by rugk** [keepassxreboot/keepassxc#3010]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1. Start an old KeePassXC (2.4.0)
2. You start typing your password…

## Current Behavior
[NOTE]: # ( Tell us what actually happens )

I can enter my password, but then suddenly the "New version is available" popup pops up. Thus, in the middle of my password I enter some characters there (that are shown nowhere) and I have no idea what part of my password I've already entered.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

Let me enter my password.

I know, update notifications are important, but not _that_ important as to interrupt the user while they are entering their password.

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )

Possibly wait until a DB is opened and only show it afterwards?
Or at least not while user is entering a password…

Or possibly even banner, show a _banner_ instead of whole new window popup for that notification.

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )

Outdated KeePassXC.

## Debug Info
KeePassXC - Version 2.4.0

Libraries:
- Qt 5.11.3
- libgcrypt 1.8.4

Operating system: Fedora 29 (Workstation Edition)
CPU architecture: x86_64
Kernel: linux 5.0.7-200.fc29.x86_64

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (only unsigned sharing)
- YubiKey

**Comment by droidmonkey** [comment]
This was fixed in 2.4.1, you should update!
