### ISSUE TITLE
HOME / END keys do not work on Mac OS X Mojave

### ISSUE THREAD

**Issue by patrick0057** [keepassxreboot/keepassxc#3012]
## Expected Behavior
Home / End keys should bring you to the beginning of the line or end of line respectively on MacOS X Mojave when editing entries in KeePassXC.

## Current Behavior
Home / End keys do nothing.

## Steps to Reproduce
1. Edit or create new entry
2. Add text to username field for example.
3. Attempt to go to beginning of the line with HOME key or end of the line with END key.

## Debug Info
KeePassXC - Version 2.4.1
Revision: 7bafe65

Qt 5.12.2
Debugging mode is disabled.

Operating system: macOS Mojave (10.14)
CPU architecture: x86_64
Kernel: darwin 18.5.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (only unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
 libgcrypt 1.8.4

**Comment by droidmonkey** [comment]
HOME / END do not perform these actions in any other macOS application that I tried. Use CMD + LEFT / RIGHT

**Comment by droidmonkey** [comment]
See https://damieng.com/blog/2015/04/24/make-home-end-keys-behave-like-windows-on-mac-os-x

**Comment by patrick0057** [comment]
I actually have similar changes in my system already as shown below.

```
$ cat ~/Library/KeyBindings/DefaultKeyBinding.dict 
{
/* Remap Home / End keys */
/* Home Button*/
"\UF729" = "moveToBeginningOfLine:"; 
/* End Button */
"\UF72B" = "moveToEndOfLine:"; 
/* Shift + Home Button */
"$\UF729" = "moveToBeginningOfLineAndModifySelection:"; 
/* Shift + End Button */
"$\UF72B" = "moveToEndOfLineAndModifySelection:"; 
/* Ctrl + Home Button */
"^\UF729" = "moveToBeginningOfDocument:"; 
/* Ctrl + End Button */
"^\UF72B" = "moveToEndOfDocument:"; 
 /* Shift + Ctrl + Home Button */
"$^\UF729" = "moveToBeginningOfDocumentAndModifySelection:";
/* Shift + Ctrl + End Button*/
"$^\UF72B" = "moveToEndOfDocumentAndModifySelection:"; 
}
```

I am able to use my HOME and END keys in all applications, Chrome, SecureCRT, Slack etc.  Maybe we could reopen this as a feature request?

**Comment by droidmonkey** [comment]
Ah, confirmed, remapping does not work in KeePassXC for whatever reason. I got it to work in Firefox. Qt is probably ignoring the DefaultKeyBinding.dict

**Comment by droidmonkey** [comment]
Confirmed it is a Qt bug: https://bugreports.qt.io/browse/QTBUG-393
