### ISSUE TITLE
Choosing additional attribute evokes unsaved changes, w/o any mods

### ISSUE THREAD

**Issue by affinityv** [keepassxreboot/keepassxc#3013]
## Expected Behavior
Should be able to fully view any elements of an entry without making any changes and not be prompted about "unsaved changes" when leaving the entry

## Current Behavior
If you view an attribute by clicking on an entry, then you can't leave that entry without getting the warning about unsaved changes (with nothing being changed).

## Steps to Reproduce
1. Open entry with additional attributes.
2. Click on any attribute
3. Exit from entry

## Context
Just normal use

## Debug Info
KeePassXC - Version 2.4.1
Revision: 7bafe65
Distribution: AppImage

Qt 5.10.1
Debugging mode is disabled.

Operating system: Devuan GNU/Linux ascii
CPU architecture: x86_64
Kernel: linux 4.9.0-6-amd64

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (only unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.1

**Comment by droidmonkey** [comment]
This requires more than 1 attribute. You click on the one that is not selected and it marks the entry dirty.

**Comment by affinityv** [comment]
Yes, I think so, if you only have one attribute, then it is already selected; you have to actually choose another attribute.
