### ISSUE TITLE
Manjaro: Can't update to 2.4.1

### ISSUE THREAD

**Issue by BunnyTheLifeguard** [keepassxreboot/keepassxc#3014]
## Expected Behavior
Update notification through Pamac / Successful update via pacman

## Current Behavior
No update notification in Pamac,
` sudo pacman -S keepassxc ` results in `warning: keepassxc-2.4.0-1 is up to date -- reinstalling
`

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.4.0
Revision: c51752d

Libraries:
- Qt 5.12.2
- libgcrypt 1.8.4

Operating system: Manjaro Linux 18.0.4
CPU architecture: x86_64
Kernel: linux 4.19.32-1-MANJARO

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (only unsigned sharing)
- YubiKey

**Comment by droidmonkey** [comment]
We don't control what is available in other distros.
