### ISSUE TITLE
Add keyboard shortcut customization in settings

### ISSUE THREAD

**Issue by kitingChris** [keepassxreboot/keepassxc#3017]
In the settings add a tab to configure the keyboard shortcuts

I was used to "Perform Auto-Type" with STRG+V and it got changed recently?
Anyway. Giving the possibility to change the keyboard shortcuts (all of them) would be very nice.

**Comment by droidmonkey** [comment]
Duplicate of #2689, but I prefer this issue because it is more direct. This is a pretty big undertaking so this may not get done anytime soon.
