### ISSUE TITLE
"Perform Auto-Type Shortcut" changed... 

### ISSUE THREAD

**Issue by kitingChris** [keepassxreboot/keepassxc#3018]
## Expected Behavior
Pressing STRG + V should perform the Auto-Type sequence of the selected entry. 

## Current Behavior
In the current version the shortcut changed to STRG + SHIFT + V

## Possible Solution
See Feature Request #3017 

## Steps to Reproduce
Select Entry and press STRG + V. Nothing happens

## Debug Info
KeePassXC - Version 2.4.1
Revision: 7bafe65

Qt 5.9.5
Debugging mode is disabled.

Operating system: Ubuntu 18.04.2 LTS
CPU architecture: x86_64
Kernel: linux 4.15.0-47-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (only unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.1

**Comment by droidmonkey** [comment]
This was changed on purpose. Overloading the paste shortcut was NEVER a good idea.

**Comment by kitingChris** [comment]
Yea but the current situation is unusable. Only solution is to downgrade until this issue is resolved somehow? 

It totally crashes my whole workflow... :-(

**Comment by kitingChris** [comment]
Btw @droidmonkey : What was the "other" functionality for STRG + V? 
I just knew and used the shortcut to perform the auto-type.
Perhaps it would be more reasonable to change the shortcut for the other functionality since STRG + B and STRG + C are used for copy username and copy password (which I also use for password fields that do not work well with auto type)

**Comment by droidmonkey** [comment]
CTRL+V is paste in every application

**Comment by kitingChris** [comment]
@droidmonkey yea... made perfectly sense to do a autotype with that. Since it is an pasting of username and password in the login fields of another Application...

What else should the paste do in the context of selecting a keepass entry here than autotyping it?

**Comment by droidmonkey** [comment]
The danger, as discussed extensively in other issues including the one that specifically requested (and was endorsed by MANY) to change the shortcut, are:

1. Accidentally triggering Auto-Type of an entry when paste was intended
2. Making sure the action was intended by the user
3. Aligning "action" shortcuts to include SHIFT and mere "copy" shortcuts to not have SHIFT.

You are being awfully dramatic about this change. Adding a SHIFT to your keyboard shortcut is functionally the same and hardly a burden.
