### ISSUE TITLE
project wiki references KeePassHTTP

### ISSUE THREAD

**Issue by PF93mc8y7erq92qTmTjJBysALa** [keepassxreboot/keepassxc#3022]
A)
Documentation in the wiki makes mention of KeePassHTTP although this feature was removed (no longer available in 2.4.0).
B)
The displayed text for the wiki is at https://github.com/keepassxreboot/keepassxc.wiki.git (displayed when viewing the wiki) not https://github.com/keepassxreboot/keepassxc-wiki.git (linked as one of the 9 projects for the keepassxreboot team).

[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
wiki stays in sync with releases. (a release requires up-to-date documentation)

## Current Behavior
[NOTE]: # ( Tell us what actually happens )
https://github.com/keepassxreboot/keepassxc/wiki mentions KeePassHTTP and its security implications although KeePassHTTP is no longer part of current versions of KeePassXC (since 2.4.0) (see #1752).

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )
Remove the reference to KeePassHTTP, possibly replacing it with a line about browser integration using the plugin KeePassXC-Browser. 

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1. Visit https://github.com/keepassxreboot/keepassxc/wiki
2. Notice the last main feature listed is that of browser integration
3. Notice that the specific details of this browser integration refer to the _old_ way (KeePassHTTP) and not the new/current/secure way (KeePassXC-Browser). 

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )
I am not sure your policy on community contributions to the wiki itself. The wiki repository shown at https://github.com/keepassxreboot/ (https://github.com/keepassxreboot/keepassxc-wiki.git), last updated December 2017, is obviously not the same as the one linked in the main keepassxreboot/keepassxc interface (Code, Issues, Pull Requests, Wiki, Insights). Source files for the currently linked wiki are not at keepassxc-wiki rather at keepassxc.wiki (https://github.com/keepassxreboot/keepassxc.wiki.git).

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.4.1
Revision: 7bafe65

Qt 5.12.2
Debugging mode is disabled.

Operating system: macOS Mojave (10.14)
CPU architecture: x86_64
Kernel: darwin 18.5.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (only unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
 libgcrypt 1.8.4

**Comment by droidmonkey** [comment]
Good catch, updated accordingly
