### ISSUE TITLE
Support vector graphics for entries

### ISSUE THREAD

**Issue by nagromc** [keepassxreboot/keepassxc#3023]
[TIP]:  # ( Provide a general summary of the feature in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Summary
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
It would be nice to support vector graphics format for entries.

## Desired Behavior
[NOTE]: # ( Tell us how the new feature should work, be specific )
This should be transparent for the user. The icon picker should filter the current supported formats + SVG format. I don't know if the favicon downloader would have impacts since I'm not sure if SVGs could be used as favicons.

## Possible Solution
[NOTE]: # ( Not required, but suggest ideas on how to implement the addition or change )
On the [original KeePass FAQ](https://keepass.info/help/base/faq_tech.html#moreclienticons), the supported formats are BMP, EMF, GIF, ICO, JPEG, PNG, TIFF and WMF. We would probably need to make them support it before KeePassXC.

However, it seems KeePassXC already have differences about icon support. This chart shows the supported format when we try to import a custom icon:

| Format | KeePass v2.41 | KeePassXC v2.4.1 |
| ----- | ----- | ----- |
| `.bmp`  | ✔️ | ✔️ |
| `.cur`  |   | ✔️ |
| `.emf`  | ✔️ |   |
| `.gif`  | ✔️ | ✔️ |
| `.icns` |   | ✔️ |
| `.ico`  | ✔️ | ✔️ |
| `.jfi`  | ✔️ |   |
| `.jfif` | ✔️ |   |
| `.jif`  | ✔️ |   |
| `.jpe`  | ✔️ |   |
| `.jpeg` | ✔️ |   |
| `.jpg`  | ✔️ |   |
| `.pbm`  |   | ✔️ |
| `.pgm`  |   | ✔️ |
| `.png`  | ✔️ | ✔️ |
| `.ppm`  |   | ✔️ |
| `.tif`  | ✔️ |   |
| `.tiff` | ✔️ |   |
| `.wmf`  | ✔️ |   |
| `.xbm`  |   | ✔️ |
| `.xpm`  |   | ✔️ |

I know, some of those are the same like `.ico` and `.cur`. But KeePassXC doesn't support JPEG family formats, and KeePass doesn't support `.xbm` or `.xpm` formats. So... why not include SVG? ☺️

If it's not possible, as a workaround, the SVG could be rasterized at import time to have sharper icons.

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
The result would be cleaner and sharper icons for entries.

Besides, my DB is currently ~160 kB and I'm afraid to make it significantly bigger if I use [raster graphics/bitmat](https://en.wikipedia.org/wiki/Raster_graphics). Using [vector graphics](https://en.wikipedia.org/wiki/Vector_graphics) can significantly limit the size of the DB. For instance, https://github.com/edent/SuperTinyIcons claim their icons are "under 1KB each" (vs several kB for bitmap icons).

**Comment by phoerious** [comment]
SVG may already be possible. The file type filters do not necessarily reflect the supported image formats as those are determined by the available Qt plugins.

**Comment by droidmonkey** [comment]
SVG is supported on Windows. If you are Ubuntu you probably need to install: https://packages.ubuntu.com/cosmic/libqt5svg5

**Comment by nagromc** [comment]
Well, when I opened the issue, I didn't even tried. I've just tried now and the following message with a red background is displayed:

> No icons were loaded
The following icon failed:
C:/Users/morgan/Downloads/google.svg

[Source of the file](https://camo.githubusercontent.com/ce783627cac13ab026860e2010ab4070171760e5/68747470733a2f2f6564656e742e6769746875622e696f2f537570657254696e7949636f6e732f696d616765732f7376672f676f6f676c652e737667)

**Comment by nagromc** [comment]
We commented at the same time. To be sure you see my message, let me bump the thread.

> 
> 
> SVG is supported on Windows. If you are Ubuntu you probably need to install: https://packages.ubuntu.com/cosmic/libqt5svg5

No, it doesn't seem.

**Comment by nagromc** [comment]
Windows 10 1607 v14393.2906
KeePassXC v2.4.1 portable (from [scoop](https://github.com/lukesampson/scoop-extras/blob/master/bucket/keepassxc.json))

**Comment by droidmonkey** [comment]
I downloaded your source SVG and added it as a custom icon to my entry. I am running 2.4.1 (installed).

**Comment by droidmonkey** [comment]
I just added the SVG icon using Win64 Portable 2.4.1 as well.

**Comment by droidmonkey** [comment]
BTW, we also support JPEG and JPG. Make sure you are extracting the ENTIRE contents of the portable zip before running.

**Comment by nagromc** [comment]
Here is what I done:

1. Open my DB
2. Edit an existing entry
3. On the left menu, click _Icon_
4. Click _Add custom icon_
5. Select _All file_ in the filter
6. Select the mentioned SVG file

The error message is displayed.

**Comment by droidmonkey** [comment]
AH I must apologize, I just saw that my instance of KeePassXC was using my MSYS2 directory to load plugins. Hmmmmmm

**Comment by nagromc** [comment]
> 
> 
> AH I must apologize, I just saw that my instance of KeePassXC was using my MSYS2 directory to load plugins. Hmmmmmm

No problem ☺️

> 
> 
> I just added the SVG icon using Win64 Portable 2.4.1 as well.

Just tried with [KeePassXC-2.4.1-Win64-portable.zip](https://github.com/keepassxreboot/keepassxc/releases/download/2.4.1/KeePassXC-2.4.1-Win64-portable.zip). I still have the same problem.

**Comment by PF93mc8y7erq92qTmTjJBysALa** [comment]
on macos I see the following list when attempting to "add custom icon":

#### graphical:
![keepassxc 2 4 1 on macos - supported image types for custom icons](https://user-images.githubusercontent.com/2647660/56296011-fac2be00-612d-11e9-87ca-59ffb12cef45.png)

#### textual:
bmp, cur, gif, heic, heif, icns, ico, jp2, jpeg, jpg, pbm, pgm, png, ppm, svg, svgz, tga, tif, tiff, wbmp, webp, xbm, xpm

And it worked fine to add the sample.svg file as a custom icon. 


## Debug Info
KeePassXC - Version 2.4.1
Revision: 7bafe65

Qt 5.12.2
Debugging mode is disabled.

Operating system: macOS Mojave (10.14)
CPU architecture: x86_64
Kernel: darwin 18.5.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (only unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
 libgcrypt 1.8.4

**Comment by droidmonkey** [comment]
Got a fix for this coming in 2.4.2. Thank you for pointing this out!

**Comment by phoerious** [comment]
Ah, it comes back to me now. I think we had issues with QtSvg on Windows in the past when we tried to deploy it ourselves, so we left it out intentionally. windeployqt should bundle QtSvg and all its dependencies properly now.
