### ISSUE TITLE
Endless Storing when drive is removed

### ISSUE THREAD

**Issue by 0xpr03** [keepassxreboot/keepassxc#3024]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Program errors out and can be exited normally.

## Current Behavior
[NOTE]: # ( Tell us what actually happens )
Program shows "Couldn't save file, backup was saved under /temp/XXX" and interates in the XXX filename every half second. (Endless backup store)

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )
Worked in pre 2.4 Keepass

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1. Open Keepass DB in a container (Veracrypt)
2. Unmount container
3. Try closing keepass

## Context
KeePass has to be killed (-9), as it won't close otherwise.

## Debug Info
KeePassXC - Version 2.4.1
Revision: 7bafe65

Qt 5.9.5
Debugging mode is disabled.

Operating system: Ubuntu 18.04.2 LTS
CPU architecture: x86_64
Kernel: linux 4.15.0-47-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (only unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.1

**Comment by droidmonkey** [comment]
When you are exiting KeePassXC, is there an asterisk next to the file name? (ie, there are pending changes to be saved)

**Comment by 0xpr03** [comment]
Yes, although I don't change anything knowlingly.

**Comment by 0xpr03** [comment]
Could be the browser Plugin or anything like that, I'm only using the entries, not editing.

**Comment by droidmonkey** [comment]
You should be able to use safe file saves, please try enabling that in settings and see if that works for you.

**Comment by 0xpr03** [comment]
Hey, I'm currently trying to find that option.
I've made a video showing the bug life. This also showed that the bug only triggers if you have a second database open at the same time and then try to close the first one.
The zip file contains the video as github apparently doesn't like mp4 but .zip..
[keepass_bug_save_disk_removal.zip](https://github.com/keepassxreboot/keepassxc/files/3091165/keepass_bug_save_disk_removal.zip)

**Comment by 0xpr03** [comment]
Just to clarify: I don't expect keepass to save in that situation. The bug is that it starts creating a huge amount of /tmp/XXX files and consumes the CPU when I just want to close the tab.

**Comment by droidmonkey** [comment]
OK found the problem.

**Comment by owlnical** [comment]
Thanks for fixing this bug, and for keeping this software up to date. I use it everyday. Will download the latest release ASAP!
