### ISSUE TITLE
Can not save database in folder of origin

### ISSUE THREAD

**Issue by entjesbe** [keepassxreboot/keepassxc#303]
## Expected Behavior
After opening the databasefile and adding or changing some information, by pressing the save icon the file must be saved in the same location it came from.

## Current Behavior
Pressing the save icon results in an error-message stating the save has failed; the file can not be saved becaus it is in use by another proces.

## Possible Solution
Just save the file.

**Comment by phoerious** [comment]
Please don't delete stuff from the issue template. The operating system you're using is an important piece of information.
Also a more precise description of what your problem is and how it can be reproduced would be helpful.

**Comment by entjesbe** [comment]
I'm running windows 10, 64 bit.

**Comment by phoerious** [comment]
I'm still missing a lot of information about what you were doing to produce this error. Simply opening and saving a file doesn't produce this error, unless maybe you have it open in two KeePassXC instances at the same time.

**Comment by entjesbe** [comment]
I tried this morrning again. I have just one instance running.
In a normal folder it works fine. The problem appears when using the file in a local dropbox folder.
At the same time I get the error, a strange file is produced in that folder. See attachment.
[KpXC Db.kdbx.zip](https://github.com/keepassxreboot/keepassxc/files/773586/KpXC.Db.kdbx.zip)

**Comment by phoerious** [comment]
That piece of information is vital. So it appears to be a problem with Dropbox in combination with KeePassXC. Could you please update your original bug description, so we have all the information in one place? Thanks!

**Comment by phoerious** [comment]
Perhaps a related issue: #197

**Comment by entjesbe** [comment]
Looks like the same issue.
Removed the zip file because I don't know what is in it.
