### ISSUE TITLE
Incorrect CLI help message on Windows

### ISSUE THREAD

**Issue by davidvidmar** [keepassxreboot/keepassxc#3032]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
When running from command line on windows, the help for usage show incorrect text.

## Current Behavior
[NOTE]: # ( Tell us what actually happens )

The ".exe" text is show after command, right thing would be after "keepassxc-cli".

```
> keepassxc-cli.exe show
Usage: keepassxc-cli show**.exe** [options] database entry
```

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1. Run ```keepassxc-cli.exe show```

**Comment by droidmonkey** [comment]
Confirmed, this is due to a find/replace that occurs to inject the "command" into the help text.
