### ISSUE TITLE
Improve keyboard navigation when searching

### ISSUE THREAD

**Issue by ensc** [keepassxreboot/keepassxc#3034]
## Summary

Keyboard navigation when searching is somehow confusing atm; e.g. when typing `C-f ` and a search term, I usually want to navigate to a result and copy the password.

With the actual version:
- the focus (blinking cursor) is in the saarch field (--> this is ok and expected)
- some actions (`C-c`, `enter`) seem to affect the first selected entry (copy passphrase, open edit dialog)
- other (`down`) affect the search text field itself; e.g. when pressing down there, nothing happens visually but the search result list gets the focus and a second `down` is required to move the selection down. 

I would expect, that

- all actions happen either completely in the search field (e.g. `C-c` would work as copy & paste there, or `enter` would move focus to search results), 

  or

- the `up` and `down` navigation keys change the selection immediately.  E.g. `down` will select the **2nd** result and `up` will select the last one.

The first option is probably more consistent with rest of the system while the second one is more effective.

[version 2.4.1 on Fedora 29]

**Comment by feuerbach** [comment]
Somewhat related: I just updated to keepassxc 2.4.0 on Fedora 29 and I think this behaviour has changed since the last version I had (not sure which one).

Specifically, after finding an entry C-f, C-c no longer works. I have to focus on the entry (e.g. with the mouse) for C-c to work. So it looks like the behaviour shifted towards your option (1), whereas I'd certainly prefer option (2).

**Comment by droidmonkey** [comment]
2.4.1 corrects the Ctrl+C behavior

**Comment by feuerbach** [comment]
@droidmonkey I tried 2.4.1. I can confirm that C-c works from the search, however, C-b (copy username) does not. Should I open a separate issue, or does it fit here?

**Comment by droidmonkey** [comment]
This issue is sufficient

**Comment by feuerbach** [comment]
Same for C-t (for TOTP).
