### ISSUE TITLE
Not asking to save with specific keystroke (Ctrl + ENTER then ESC)

### ISSUE THREAD

**Issue by fam4r** [keepassxreboot/keepassxc#3036]
## Expected Behavior

When creating a new entry, you can edit fields and save and exit:
- if you press CTRL+ENTER the entry is saved

## Current Behavior

For a new entry: data loss. KeepassXC is not asking to save an unsaved entry, when you press "CTRL+ENTER" it only says "Entry updated successfully." but no data is really saved.

For an existent entry: CTRL+ENTER saves the edit, so if you press ESC you are not asked to save unsaved data (and that's correct because they have been saved)

## Possible Solution

Make the keybind "CTRL + ENTER" save a new entry

## Steps to Reproduce

1. Create a new entry
2. Edit some fields
3. Ctrl + ENTER
4. ESC to exit
5. See that no new entry is created

## Debug Info
KeePassXC - Version 2.4.1
Revision: 7bafe65

Qt 5.12.2
Debugging mode is disabled.

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 5.0.7-arch1-1-ARCH

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.4

**Comment by droidmonkey** [comment]
I made an error when I coded this, I should have called "acceptEntry()" instead of "commitEntry()". Ctrl+Enter should be the same as press "OK"
