### ISSUE TITLE
Entries deletion - %1 instead of entries' number in French

### ISSUE THREAD

**Issue by Maxime-J** [keepassxreboot/keepassxc#3037]
## Expected Behavior
When multiple entries are deleted, a confirmation prompt shows the number of entries which are about to be deleted.

## Current Behavior
When using French language, the confirmation prompt shows %1 instead of the number of entries.

## Possible Solution
Pull the corrected translated string from Transifex

## Steps to Reproduce
1. Selecte multiple entries
2. Delete them

## Context
French language

**Comment by droidmonkey** [comment]
If its updated in Transifex then it'll be applied on the next update

**Comment by MinIsMin** [comment]
Same for German (if it's not already fixed)
![grafik](https://user-images.githubusercontent.com/18466226/58022471-0b839c80-7afd-11e9-9b35-ab57035c3bc7.png)

**Comment by Maxime-J** [comment]
Ok, German translation updated, will be fixed in next release :)
