### ISSUE TITLE
"New version avaiable" dialog shows up while typing password

### ISSUE THREAD

**Issue by thiagomacieira** [keepassxreboot/keepassxc#3042]
When you open KeepassXC and are typing the database password, it will check for a new version. Often, that dialog pops up while typing the password. That is very annoying, as finding out where you were in the password is difficult, leading most people to erase all the password and type again.

## Expected Behavior
Not show the "new version available" dialog while typing the password. Preferably, not show at all.

## Current Behavior
The dialog pops up while typing the password. Since it's the same application, there's no focus-stealing prevention solution from the window manager.

## Possible Solution
Don't show the "new version available" dialog at all.

## Steps to Reproduce
1. Install a not-currrent version of KeepassXC
2. Open it
3. Begin typing the password to decrypt the databsae

## Debug Info
KeePassXC - Version 2.4.0
Revision: c51752d

Libraries:
- Qt 5.12.2
- libgcrypt 1.8.4

Operating system: openSUSE Tumbleweed
CPU architecture: x86_64
Kernel: linux 5.0.6-1-default

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
Enabled extensions:
- EXTENSIONS

**Comment by droidmonkey** [comment]
This was fixed in 2.4.1

**Comment by agateau** [comment]
I have the same problem with 2.5.2. I could disable the update check, but I'd rather not, it's useful to know when a new version is available. It would be nicer if the information were presented in a banner so that it does not steal the focus.
