### ISSUE TITLE
No button to generate key (for sharing)

### ISSUE THREAD

**Issue by tessus** [keepassxreboot/keepassxc#3043]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
When I go to `Preferences -> KeeShare` there should be a `Generate` button (as shown in the [wiki](https://github.com/keepassxreboot/keepassxc/blob/develop/docs/QUICKSTART.md#using-sharing))

## Current Behavior
[NOTE]: # ( Tell us what actually happens )

As you can see, there's no `Generate button`
<img width="667" alt="image" src="https://user-images.githubusercontent.com/223439/56453550-fe169f00-6311-11e9-8be6-3bad48f220b2.png">

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1. Go to `Preferences -> KeeShare`

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )
I'm not able to create a key as described in the wiki.

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.4.1
Revision: 7bafe65

Qt 5.12.2
Debugging mode is disabled.

Operating system: macOS Mojave (10.14)
CPU architecture: x86_64
Kernel: darwin 18.5.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (only unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
 libgcrypt 1.8.4

**Comment by phoerious** [comment]
This is because Homebrew has no quazip5 at the moment, so we needed to build without WITH_XC_KEESHARE_SECURE.

**Comment by tessus** [comment]
@phoerious Thanks for the reply and shedding some light on this.

However, I'm not sure I understand your statement. What does the release .dmg have to do with brew? I don't care about brew, since I install KeePassXC via the .dmg file, so why should everybody suffer because of brew's ineptitude?

**Comment by phoerious** [comment]
Our build is dependent on what is available through Homebrew. Building a version of quazip5 ourselves isn't impossible, but inconvenient. We plan to create and submit a package to brew in the future.
