### ISSUE TITLE
can't change the Notes field of a database

### ISSUE THREAD

**Issue by tessus** [keepassxreboot/keepassxc#3044]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
When I open a database there are 3 tabs at the botton:

<img width="225" alt="image" src="https://user-images.githubusercontent.com/223439/56454628-a849f300-6321-11e9-95a7-fa0e5cacf95e.png">

The notes field should not be read-only or it should be possible to change the content in the database settings.

## Current Behavior
[NOTE]: # ( Tell us what actually happens )

The field is read-only and there's no way to change the content of `Notes`.

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1. Open a database
2. Check the `Notes` tab at the bottom and the database settings

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )
I'm not able to change the content of the database Notes field.

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.4.1
Revision: 7bafe65

Qt 5.12.2
Debugging mode is disabled.

Operating system: macOS Mojave (10.14)
CPU architecture: x86_64
Kernel: darwin 18.5.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (only unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
 libgcrypt 1.8.4

**Comment by phoerious** [comment]
Open the entry edit dialogue and use the notes field there. The preview panel is only a preview of an entry.

**Comment by tessus** [comment]
@phoerious thanks, but I think you did not read the problem properly. I'm not talking about the notes field for an entry, but for the **database**:

<img width="1137" alt="Screen Shot 2019-04-20 at 16 39 55" src="https://user-images.githubusercontent.com/223439/56462124-b7fe2180-638b-11e9-8c1b-1084bd240d31.png">

There is no entry dialog for the database, but only for entries. Also, as soon as I click on an entry I have no idea how to get back to that window again. It only shows right after opening a database (before clicking on an entry).

**Comment by phoerious** [comment]
There is no notes field for the database. That is the entry nodes field.

**Comment by droidmonkey** [comment]
That is the notes for the root group.

**Comment by tessus** [comment]
> That is the notes field of the first entry.

Hmm, my first entry has 5 tabs in the prwview, not three:

<img width="430" alt="image" src="https://user-images.githubusercontent.com/223439/56462730-234cf100-6396-11e9-90a9-abed3d421754.png">

**Comment by tessus** [comment]
> That is the notes for the root group. Just edit the root group.....

That was it. Thanks. It is very confusing, because it doesn't display the name of the group (anywhere in the preview).
It shows `/` but that's not the same as `/root`. Posix makes this distinction. And if you renamed `root` to `blabla`, it would still show `/`? Well, in any case, this is something that people have to know. This is not intuitive.

Also, when I click on the group, the preview for the group doesn't show again.

**Comment by droidmonkey** [comment]
That last part is a bug

**Comment by tessus** [comment]
Ok, so what now? Are you going to open a separate ticket for the bug?

My problem is solved, but I'm more than happy to open another ticket if you need me to.

**Comment by droidmonkey** [comment]
I'll probably just fix it, pretty simple
