### ISSUE TITLE
DPI change

### ISSUE THREAD

**Issue by Tomas688** [keepassxreboot/keepassxc#3047]
Hello,
How can I change DPI (Only for KeePassXC)?
I found: https://github.com/keepassxreboot/keepassxc/issues/2981
But I can't use this solution, I have installed other applications that use Qt and are having problems when I change DPI for all applications.
I'm using the portable version so I need the DPI set up changes to be written to some file that will be with the application KeePassXC.

**Comment by affinityv** [comment]
You can use it with the environment variables set on the same line as KPXC like this
`ENV1=ssss ENV2=wwwww /path_to_KPXC/KPXC`

Here is an example without KPXC, just a quick /bin/bash:
`aaa1=333 aaa2=444 /bin/bash -c 'echo "~${aaa1}~ ~${aaa2}~"''`
And the result of that:
`~333~ ~444~`

Just use the right variables for QT as per the reference.

**Comment by Tomas688** [comment]
@affinityv @droidmonkey
I understand the script function but my problem is i don't know what variables it use to change DPI.
PS: I need a Windows solution not for Linux. thanks.

**Comment by droidmonkey** [comment]
Please read here: https://doc.qt.io/qt-5/highdpi.html
