### ISSUE TITLE
Attached images in entry lost

### ISSUE THREAD

**Issue by lbkvu** [keepassxreboot/keepassxc#3048]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

I always capture the QR code for 2FA and save it in the entry as backup. However, when I check the attachment, its size becomes 0B.
## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Here's from my previous backup of the database
![image](https://user-images.githubusercontent.com/1523943/56467582-d03d7180-645b-11e9-84d0-22106a28a4fc.png)

## Current Behavior
[NOTE]: # ( Tell us what actually happens )
![image](https://user-images.githubusercontent.com/1523943/56467616-24e0ec80-645c-11e9-98c5-9d2b75c6b127.png)

# Difference in image size
**Normal state**
![image](https://user-images.githubusercontent.com/1523943/56467603-f6fba800-645b-11e9-9e8d-634301b1dbee.png)

**Current state**
![image](https://user-images.githubusercontent.com/1523943/56467599-f19e5d80-645b-11e9-8b4e-b344b7b3044a.png)

## Possible Solution, but broken
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )
I use my backup database as the base database, then merge my current database into it. However, some attachment are still lost. The database file size becomes smaller than before.

**Before merging**
![image](https://user-images.githubusercontent.com/1523943/56467674-06c7bc00-645d-11e9-9bb5-b44f05b8a5f1.png)

**After merging**
![image](https://user-images.githubusercontent.com/1523943/56467675-0a5b4300-645d-11e9-8937-e6b0cda2c9f2.png)

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.4.1
Revision: 7bafe65

Qt 5.12.2
Debugging mode is disabled.

Operating system: macOS Mojave (10.14)
CPU architecture: x86_64
Kernel: darwin 18.0.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (only unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
 libgcrypt 1.8.4

**Comment by droidmonkey** [comment]
Are you using any other program to access your database?

**Comment by lbkvu** [comment]
On iPhone, I use [Keepass Touch](https://itunes.apple.com/us/app/keepass-touch/id966759076?mt=8). On Windows, I use KeePass 2

**Comment by droidmonkey** [comment]
Losing attachments is a big deal, we take any type of data loss seriously. I would not read too much into the total size of your database, KeePass databases employ compression before being encrypted so it could very well be the compression engine doing its job.

I am hesitant to point my finger elsewhere for this issue, but you are using three different password manager applications. I use KeePassXC and KeePass2Android and have never lost an attachment.

Please do the following to confirm the extent of the damage (on the broken db):

1. Open your database in KPXC
2. In the search bar type: ```attach:*```. This will show all entries with attachments.
3. Open each entry and confirm if the attachment was zeroed out.
4. Report back your findings.

I am trying to see if there are any patterns. Do all of your attachments have the same file name?

**Comment by lbkvu** [comment]
I have 59 items which have attachment and their attachments were all zeroed out. This affects all files attached, not limited to images as you can see in the below image
![image](https://user-images.githubusercontent.com/1523943/56732235-a3f55e00-6797-11e9-913b-8a412da25a85.png)

For 2FA images, they all have the same filename format: **2fa-<site-name>.png**

**Comment by droidmonkey** [comment]
Please try to replicate this issue on a test database that is NOT opened by other programs (ie, only use KeePassXC). Your problem leads me to believe one of the other programs is not writing the data for the file on saving.

Are you using KDBX4?

**Comment by SilverFire** [comment]
Hello.
I've faced the same problem on my real database. I also use KeepassXS on my Mac, Keepass 2.41 on Windows and KeePass Touch on my iPhone with the same set of plugins. I use Dropbox to synchronize files between devices.

> Are you using KDBX4?
Yes, I do.

First, I've tried to restore the database by synchronizing the latest corrupted version and outdated backup. Nither broken>backup nor backup>broken synchronization works: empty files remain empty.

Then I tried to reproduce the problem on a scratch database but failed to get the same result. Maybe, you have any ideas on how to reproduce the error?

**Comment by droidmonkey** [comment]
I am wondering if the attachments are being blown away during a merge operation that occurs. Try leaving the database unlocked on your macOS, modify the database on Windows or on iPhone, then watch when the database reloads and merges into the one on macOS.

**Comment by SilverFire** [comment]
Ok, I've reproduced the problem on a clean database using some of the private attachments, I had in my database. I've tried to mess up the database by editing it in KeePassXS/KeePass/KeePass touch, and I succeeded somehow, but not sure that I can do it once more. Nevertheless now I have KDBX that has non-empty attachment in KeePass 2.4.1 

![image](https://user-images.githubusercontent.com/4499203/58096904-cfc10380-7bde-11e9-9df6-602de1ce2782.png)

but it's empty in KeePassXS

![image](https://user-images.githubusercontent.com/4499203/58096876-bc159d00-7bde-11e9-9fa5-03868cd690d6.png)


[issue3048_broken.kdbx.zip](https://github.com/keepassxreboot/keepassxc/files/3202544/issue3048_broken.kdbx.zip)

Use password `3048`

**Comment by lbkvu** [comment]
I suspect that this problem is due to KeePass Touch. Sometimes it shows error dialog that there's problem when syncing my DB file due to my network is connected/disconnected. Perhaps during the sync process, it messes up my DB file. I've been using KyPass for 3 weeks now and this problem hasn't appeared yet (my network is still the same, up/down a lot since I move around a lot)

**Comment by droidmonkey** [comment]
On KeePass Touche's app page it lists the last fix as addressing: 

> Critical bugfix: For some of you your files disappeared. This patch should fix this again and show all files, imported whatever way used.

**Comment by SilverFire** [comment]
> @SilverFire you should give KyPass a try

Thanks, I will!

> On KeePass Touch's app page it lists the last fix as addressing:

The fix is a few months old, but yes, I suspect KeePass Touch is guilty.

The KDBX I've provided in my previous post contains uncorrupted files on Windows KeePass 2.4.1 and KeePass Touch, however, KeePassXC shows `win_attach.txt` as an empty file. @droidmonkey could you check why it happens?

**Comment by droidmonkey** [comment]
Yes I'll run in through the debugger

**Comment by droidmonkey** [comment]
OK so here is the problem I observed:

1. There are 4 attachment binaries located in the supplied KDBX
2. There are 5 attachments referenced
3. Attachment 5 (ref id == 4) is win_attach.txt
4. Because there is no 5th attachment the ref id points to nothing, thus the 0 byte file

My Opinion:
When KeePass Touch writes the database they have an off-by-one error that only writes n-1 attachment binaries to the database file. Save it multiple times and you get many attachments with 0 bytes. 

@lbkvu did you save your database in KeePass Touch many many times?

**Comment by droidmonkey** [comment]
This should be easy to replicate if you just make 4 saves to the database in KeePass Touch then all the attachments should be 0 bytes

**Comment by SilverFire** [comment]
I tried to edit "Attach from Wndows KeePass" record 4 times from KeePass Touch, but it seems that nothing changed: still one corrupted file

[issue3048_broken_after_4_edits.kdbx.zip](https://github.com/keepassxreboot/keepassxc/files/3206135/issue3048_broken_after_4_edits.kdbx.zip)

**Comment by SilverFire** [comment]
1. Create a new database on MacOS with plaintext attachment [issue3048.kdbx.zip](https://github.com/keepassxreboot/keepassxc/files/3206179/issue3048.kdbx.zip)
2. Add a new record with a plaintext attachment from KeePass on Windows [issue3048.kdbx.zip](https://github.com/keepassxreboot/keepassxc/files/3206224/issue3048.kdbx.zip)
3. Add another plaintext attach to "Windows" record using KeePassXC [issue3048.kdbx.zip](https://github.com/keepassxreboot/keepassxc/files/3206231/issue3048.kdbx.zip), see 
4. Rename "Windows" record using KeePassTouch [issue3048.kdbx.zip](https://github.com/keepassxreboot/keepassxc/files/3206238/issue3048.kdbx.zip)
5. Add plaintext attach to "KeePassXC" record using KeePass on windows. Choose "Binary mode" when adding attach. [issue3048.kdbx.zip](https://github.com/keepassxreboot/keepassxc/files/3206257/issue3048.kdbx.zip)
6. Rename "KeePassXC" record using KeePass touch 
[issue3048.kdbx.zip](https://github.com/keepassxreboot/keepassxc/files/3206271/issue3048.kdbx.zip)

Still no luck :( I'm not sure how I managed to mess it up previously

**Comment by SilverFire** [comment]
@droidmonkey I am still curious why KeePass on Windows shows `win_attach.txt` in [this](https://github.com/keepassxreboot/keepassxc/issues/3048#issuecomment-494375480) database correctly.

**Comment by droidmonkey** [comment]
OK so I found the issue... some program is adding a duplicate binary data (win_attach.txt) which is against the new kdbx4 standard. When this happens, KeePassXC discards the duplicate binary, however the entry still points to attachment 4 which now does not exist in our internal representation of the attachment data.

This is both a failure of the KDBX4 standard (it should be using UUID to identify attachments, not index values) and the program that is duplicating the binary attachment.

To fix this issue we would have to ignore duplicate attachment binaries, which could result in databases growing in size unnecessarily.

**Comment by phoerious** [comment]
We should build a map that maps indices to hashes and then use the hashes internally to refer to files. That way we can "correct" erroneous index pointers by mapping them to the same hash, which then points (hopefully) to the correct file. This would automatically fix issues like this when the file is saved eventually.

**Comment by SilverFire** [comment]
Thank you for the investigation. In there anything else I could do to help you fix the problem?

**Comment by droidmonkey** [comment]
We still need to figure out what triggers this situation. I am starting to think this is happening in keepass itself!

**Comment by SilverFire** [comment]
Thank you for the response and prompt fix.
Do you have nightly builds somewhere? I can check the fix on my main KDBX database

**Comment by droidmonkey** [comment]
We do but they are for develop branch. What OS are you running?

**Comment by SilverFire** [comment]
Mojave 10.14.5

**Comment by droidmonkey** [comment]
Here is a build I made, it is unsigned so install it "side-by-side" with your existing KeePassXC install: https://s3.amazonaws.com/droidmonkey-keepassxc/snapshots/KeePassXC-2.4.2-snapshot.dmg

**Comment by SilverFire** [comment]
Sorry for a late reply.

My original database with corrupted files still remains corrupted, adding new dumb record and saving does not fix old corruptions. However, the sample database I've made for this issue works well: previously missing files are available.

I opened the latest healthy (but outdated) database and merged a corrupted one into the old. The newer changes got imported and the files remain available, so I think the problem is fixed.

**Comment by gorrioncillo** [comment]
I have a similar problem, I attach a .txt file with original keepass in win10.
When I try to open it I can not because seems to be mess.
Then I figure out that it was compressed in .gzip
So simple change the extension to .gzip and open it.
Hope help others and if someone knows a better way please share
