### ISSUE TITLE
High CPU usage on OS X w/2.4.1

### ISSUE THREAD

**Issue by BrettDikeman** [keepassxreboot/keepassxc#3061]
I updated to 2.4.1 from 2.4.0 recently and KeepassXC is now often uses 5-15% of my CPU, averaged over a 5 second window - more than any other application process, including the Chrome helper process I'm typing in now.

UPDATE: I had the about dialog open, KeepassXC was idle with an open database; I closed the window, and the high CPU usage returned.

## Context

This period of high CPU usage lasts for several minutes at a time, regardless of whether the database is locked or not, and does not seem related to using browser integration. KeepassXC was idle with an open but locked database when I first noticed it; several minutes later the high CPU usage ceased, and then several minutes later, it returned for several minutes.

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.4.1
Revision: 7bafe65

Libraries:
Qt 5.12.2
libgcrypt 1.8.4

Operating system: MacOS X
CPU architecture: x86_64

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (only unsigned sharing)
- YubiKey
- TouchID

**Comment by BrettDikeman** [comment]
Further testing reveals that this seems to be triggered by two things:

- switching applications (not to/from KeepassXC but between any other applications)
- covering and uncovering the KeepassXC database window with other application windows (covering it completely = low idle CPU. Uncovering it, even a small sliver = high CPU activity)

Hiding KeepassXC also will kill high idle CPU usage.

**Comment by droidmonkey** [comment]
I wonder if this is related to the sluggish scrolling other Mac users have reported. Window painting (what happens when you uncover a portion of the window) is there job of Qt. A couple questions:

1. Are you running in dark mode?
2. Have you used auto type before the cpu usage increases?
3. If you just open KeePassXC, with no database unlocked ever, is there still high cpu usage?

**Comment by BrettDikeman** [comment]
Hi Jonathan!

I have the dark menubar/dock enabled (no "dark mode" in 10.13, I think?); I
don't use auto-type at all; with no database open, the high CPU usage does
not seem to happen, so it looks like this only occurs with an open or
locked database.

Also, FWIW, I have never noticed a problem with scrolling.

~B

**Comment by droidmonkey** [comment]
OK, thank you for the responses. I am not currently aware of any looping processes within KeePassXC. I did fix an issue before the release of 2.4.0 that caused high CPU usage after saving. If you can narrow down exactly when the high cpu usage starts happening (ie, after what particular action or window state) that would be incredibly helpful.

**Comment by BrettDikeman** [comment]
I already described some actions - easiest to reproduce is
covering/uncovering the keepassxc window when keepassxc is not the
front-most application. Or did you mean something else?

**Comment by droidmonkey** [comment]
I cannot reproduce this on my mac mini. That is the problem. I need to know what the initial trigger is that starts causing the high cpu usage.

**Comment by droidmonkey** [comment]
Oh interesting, I am able to reproduce this issue.

**Comment by BrettDikeman** [comment]
Ahh. I suppose I couldn't been more specific about what section of the UI
was displayed and such; sorry. Looks like you're all set, though. Happy to
provide more information if I can.
