### ISSUE TITLE
KeePassXC Portable Functionality

### ISSUE THREAD

**Issue by adit-s** [keepassxreboot/keepassxc#3062]
Hello. I was trying to figure out if the [KeePassXC PortableApp](https://portableapps.com/apps/utilities/keepassxc-portable#download_details) is compiled with network communication _disabled_. 
Based on what I can see, it looks like there's no need for any kind of network communication, but would appreciate it if someone who knows for sure can confirm?

Thanks in advance,
Adit

**Comment by droidmonkey** [comment]
We don't control that distribution method. I'm pretty darn sure it has networking built in. You can just download it, open it, and go to Help -> About and look at the debug info.

**Comment by adit-s** [comment]
Hello. What should it say if network communication is disabled?

Here is the output and it looks the same as a standard installation:
KeePassXC - Version 2.3.4
Revision: 6fe821c

Libraries:
- Qt 5.11.1
- libgcrypt 1.8.3

Operating system: Windows 10 (10.0)
CPU architecture: i386
Kernel: winnt 10.0.17134

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

Thanks.

**Comment by droidmonkey** [comment]
It is enabled. That is also the old version

**Comment by adit-s** [comment]
Hi again. I compiled keepassxc on Ubuntu 18.04 following these [instructions](https://github.com/keepassxreboot/keepassxc/wiki/Building-KeePassXC) and substituting -DWITH_XC_NETWORKING=OFF in cmake per [faq](https://keepassxc.org/docs/#faq-security-no-network).
This was the command I used:
cmake -DWITH_XC_NETWORKING=OFF -DCMAKE_BUILD_TYPE=Release ..

However, when I run and click "check for update" it still reports it's the latest version;
So it looks like it is still running with networking enabled and communicating to check with the update server.

Am I missing something?
Should I have used a different option in cmake?

Here's the about->debug output:
KeePassXC - Version 2.4.1
Revision: 7bafe65

Qt 5.9.5
Debugging mode is disabled.

Operating system: Ubuntu 18.04.2 LTS
CPU architecture: x86_64
Kernel: linux 4.15.0-47-generic

Enabled extensions:
- Auto-Type

Cryptographic libraries:
 libgcrypt 1.8.1

Thanks again,
Adit

**Comment by droidmonkey** [comment]
You have to disable the update check feature as well: -DWITH_XC_UPDATECHECK=OFF

**Comment by adit-s** [comment]
Thanks again. I'll try that.
1. can you tell me where I find all of the compile options - ie  -DWITH_XC_UPDATECHECK, -DWITH_XC_NETWORKING...

2. How can I tell from the debug info that network communication is disabled?
(The earlier debug info was as follows and you explained that network communication is enabled. What was it in the debug info which told you that/what is it that shows it's diasabled?

earlier debug info:
KeePassXC - Version 2.3.4
Revision: 6fe821c

Libraries:
    Qt 5.11.1
    libgcrypt 1.8.3

Operating system: Windows 10 (10.0)
CPU architecture: i386
Kernel: winnt 10.0.17134

Enabled extensions:
    Auto-Type
    Browser Integration
    Legacy Browser Integration (KeePassHTTP)
    SSH Agent
    YubiKey
)

**Comment by droidmonkey** [comment]
The legacy browser integration used networking

**Comment by adit-s** [comment]
Thanks for the quick response. I'll take your feedback and try it again.

Adit

**Comment by droidmonkey** [comment]
You can see a list of build options on our INSTALL.md just above this section:

https://github.com/keepassxreboot/keepassxc/blob/develop/INSTALL.md#installation

**Comment by adit-s** [comment]
Thanks again. That's what I was looking for.

Adit

**Comment by adit-s** [comment]
Hello. I'm new to this so maybe this is a silly question, but I was wondering if I can make the keepassxc on Linux and run it on Windows? If yes, could you tell me how? (do I simply copy the DESTDIR from "make DESTDIR=~/.local install" on Linux to Windows? and then run it as an executable?)

Thanks in advance,
Adit

**Comment by droidmonkey** [comment]
No you cannot do that. You have to follow the Windows build instructions.

**Comment by adit-s** [comment]
Thanks again for the quick response.
