### ISSUE TITLE
Password generator skips special characters

### ISSUE THREAD

**Issue by charsi** [keepassxreboot/keepassxc#3064]
## Expected Behavior
Password should be generated with all selected character types

## Current Behavior
Password gets generated without special characters even though they are selected in the 'character types' option below.

## Possible Solution
Clicking the special characters button a couple of times fixes this.

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1. Open KeepassXC
1. Create a new entry
1. Generate new password (dice icon) from within the new entry
1. View the password (eye icon)
1. It should have special characters, but it doesn't
1. Tap the special characters button a couple of times and click regenerate. 

![image](https://user-images.githubusercontent.com/826310/56559375-5ccc5a80-6556-11e9-87a5-246e4fa9e3bd.png)

## Context
I have less than secure passwords for a few sites now. Other affected users might be doing this without realizing.
I usually blind generate a password and copy paste it into the site when registering for something. I ran into a site that enforced special characters and only then realized my passwords didn't have any.

## Debug Info
KeePassXC - Version 2.4.1
Revision: 7bafe65

Qt 5.5.1
Debugging mode is disabled.

Operating system: Linux Mint 18.3
CPU architecture: x86_64
Kernel: linux 4.15.0-47-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.1

Probably related to https://github.com/keepassxreboot/keepassxc/issues/2749 but the main password generator window is unaffected by this one. The special characters option shows as unselected.

**Comment by droidmonkey** [comment]
Yes this is a big deal, it has bit me before as well.

**Comment by droidmonkey** [comment]
Related to #2749

**Comment by ba32107** [comment]
I did some investigation and I pretty sure I found the root cause. I think it was caused by https://github.com/keepassxreboot/keepassxc/pull/1841. It should also fix #2749.

A PR will be opened shortly.
