### ISSUE TITLE
Errors in Firefox on some sites after update 22.04.2019

### ISSUE THREAD

**Issue by dmitryvakulenko** [keepassxreboot/keepassxc#3065]
Hello!
After last update I start to get this error when try to select checkbox.
![image](https://user-images.githubusercontent.com/2528588/56569562-dcdbda00-65c1-11e9-9749-8320cd2d82ab.png)

I use Firefox 66.0.2 (64-bit) Under Linux mint

**Comment by droidmonkey** [comment]
Already fixed
