### ISSUE TITLE
Weird sidebar coloring

### ISSUE THREAD

**Issue by stdedos** [keepassxreboot/keepassxc#3067]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
![image](https://user-images.githubusercontent.com/133706/56575128-a60bc100-65cd-11e9-9ccf-f315189a41ac.png)

## Current Behavior
[NOTE]: # ( Tell us what actually happens )
![image](https://user-images.githubusercontent.com/133706/56575099-942a1e00-65cd-11e9-876f-120e76e0c8a2.png)

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )
It seems related to the vertical size of the window. Also disallows further resizing after it becomes "small enough" so that the issue disappears

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1. Move the menu bar to the side
2. Expand/Contract the window

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.4.1
Revision: 7bafe65

Qt 5.5.1
Debugging mode is disabled.

Operating system: Ubuntu 16.04.6 LTS
CPU architecture: x86_64
Kernel: linux 4.15.0-45-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.1

**Comment by stdedos** [comment]
_Following the resolution of https://github.com/keepassxreboot/keepassxc/issues/3066, I did install various packages, and purged them all (minus the `ini` configuration file). Issue still persists._

**Comment by droidmonkey** [comment]
Does the same coloring issue happen if the toolbar is docked on the right hand side or floating?

**Comment by droidmonkey** [comment]
Btw, this is most likely, 99% certain, a Qt issue if anything.

**Comment by stdedos** [comment]
* Right side: Yes 
![image](https://user-images.githubusercontent.com/133706/56578590-aeb4c500-65d6-11e9-82dd-e05a27afb063.png)
![image](https://user-images.githubusercontent.com/133706/56578610-bb391d80-65d6-11e9-925e-fa043aa60bb7.png)
* Floating: No

**Comment by stdedos** [comment]
Yes, I cannot replicate with `snap`
