### ISSUE TITLE
Inconsistent ENTER behavior

### ISSUE THREAD

**Issue by ensc** [keepassxreboot/keepassxc#3069]
The ENTER key opens sometimes the Edit dialog and is ignored other times. 

E.g.

1. open a group with multiple entries
2. click with the mouse on one of the entries (column matters; target the username or password column)
3. press ENTER
4. press up/down
5. press ENTER
6. repeat step 4 until selection wraps at bottom or top
7. press ENTER

## Current Behavior

When in 2. there was clicked in the password or username column, the ENTER in step 3 and step 5 is ignored.  It opens the edit dialog in step 7.

When clicking on title or some of the time columns, ENTER opens the edit dialog everytime.

## Expected Behavior

Behavior should be consistent; I would prefer when the edit dialog will **never** be opened by ENTER but only by `C-e`

## Debug Info

```
KeePassXC - Version 2.4.1
Revision: 7bafe65

Qt 5.11.3
Debugging mode is disabled.

Operating system: Fedora 29 (Twenty Nine)
CPU architecture: x86_64
Kernel: linux 5.0.7-200.fc29.x86_64

Enabled extensions:
- Auto-Type
- Browser-Integration
- SSH-Agent
- KeeShare (only unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.4
```

**Comment by droidmonkey** [comment]
I believe when you are hitting enter and it is not going to edit you are actually triggering the copy to clipboard action for that particular cell.
