### ISSUE TITLE
[2.4.1]keepassxc: qt_message_fatal(): keepassxc killed by SIGABRT

### ISSUE THREAD

**Issue by Germano0** [keepassxreboot/keepassxc#3070]
Upstream clone of bugreport https://bugzilla.redhat.com/show_bug.cgi?id=1702186

Crash backtrace
https://gist.github.com/Germano0/2cc839db054abaef6a00bfaaa00543cd

KeePassXC - Version 2.4.1
Revision: 7bafe65

Qt 5.11.3
Debugging mode is disabled.

Operating system: Fedora 29 (Workstation Edition)
CPU architecture: x86_64
Kernel: linux 5.0.7-200.fc29.x86_64

Enabled extensions:
- Auto-Type
- Integracja z przeglądarką
- Agent SSH
- KeeShare (only unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.4

**Comment by droidmonkey** [comment]
I cannot access that bug report on redhat's website. Can you please summarize the issue here. Is this an issue with KeePassXC?

**Comment by phoerious** [comment]
The stack trace shows some KeePassXC locals (looks like the main function?), but is otherwise not very helpful. I guess this is a Qt crash, but we need a trace of a debug build to be sure.
