### ISSUE TITLE
Legible text

### ISSUE THREAD

**Issue by pkail** [keepassxreboot/keepassxc#3071]
[TIP]: The text is too small to see without getting very close to the screen and squinting.
 # ( Provide a general summary of the feature in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Summary
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
Making the menus, etc. legible without squinting.

## Desired Behavior
[NOTE]: # ( Tell us how the new feature should work, be specific )
Please either a) allow it to use system fonts or b) add an option to increase the font size.

## Possible Solution
[NOTE]: # ( Not required, but suggest ideas on how to implement the addition or change )
Or just make the standard font legible.

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )

**Comment by droidmonkey** [comment]
We do use the system font. If you have a high dpi screen you may have to set the environment variable: QT_AUTO_SCREEN_SCALE_FACTOR = 1
