### ISSUE TITLE
Add support for Hashicorp Vault backend

### ISSUE THREAD

**Issue by pillarsdotnet** [keepassxreboot/keepassxc#3073]
[TIP]:  # ( Provide a general summary of the feature in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Summary
It would be nice if KeepassXC were able to store and retrieve passwords from a [HashiCorp Vault](https://www.vaultproject.io/) server.

## Desired Behavior

In order of most-useful to most-easily-implemented:

1. Full backend support
   * Specify a Vault URL for the database storage location.
2. Import/Export with merge
   * Import from Vault, overwriting older entries in current db.
   * Export current db to Vault, overwriting older entries in Vault.
3. Simple Import/Export
   * Import from Vault, overwriting entries in the current db.
   * Export current db to Vault.

## Possible Solution

For reference, the [vault-keepass-import](https://lab.enough.community/singuliere/vault-keepass-import) tool (also available via [`pip install vault-keepass-import`](https://pypi.org/project/vault-keepass-import/)) supports a one-way conversion, reading a Keepass DB and writing to a Vault.

Also see [VaultKee](https://github.com/ShadowApex/vaultkee) which has a similar [feature-request](https://github.com/ShadowApex/vaultkee/issues/13).

## Context

Using a Vault server makes more sense, for enterprise use, than passing `.kdbx` files around via email, Google Drive, and the like.

**Comment by droidmonkey** [comment]
To be honest there is a very low probability of this being implemented unless someone from the community does it (and does it REALLY well).

**Comment by pillarsdotnet** [comment]
Vault isn't really a cloud service -- it's usually implemented within a firewalled internal LAN.

But yeah, I kinda figured I'd need to follow-up with a PR to get serious consideration.
