### ISSUE TITLE
Entry cannot be dragged into another group

### ISSUE THREAD

**Issue by macwirbel** [keepassxreboot/keepassxc#3077]
Using macOS 10.13.6 and KeePassXC 2.4.1 drag and drop is disabled usually. Cannot figure out why in seldom cases it works but mostly not. I have 6 folders below root. Doesn't matter from which to which folder you want to move an entry. Just cannot pick it up.

Opened and closed the "About" dialogue, then dragging worked. Wierd behaviour.

**Comment by droidmonkey** [comment]
Works just fine for me on macOS 10.14.3
