### ISSUE TITLE
keepassxc: segfault at error 4 in libQt5WaylandClient

### ISSUE THREAD

**Issue by Tormen** [keepassxreboot/keepassxc#3082]
I noticed that keepassxc keeps crashing from time to time (once or twice every day) since I moved to Wayland ~ 1 month ago!

I am using swaywm. Relevant versions:
* community/keepassxc 2.4.1-2 (Installed)
* extra/kwayland 5.57.0-1 (kf5) [installed]
* extra/kwayland-integration 5.15.4-1 (plasma) [installed]
* extra/qt5-wayland 5.12.3-1 (qt qt5) [installed]
* extra/wayland 1.17.0-1 [installed]
* extra/wayland-protocols 1.17-1 [installed]
* extra/xorg-server-xwayland 1.20.4-1 (xorg) [installed]
* aur/sway-git (Installed: r5885.236ca634-1)
* aur/wlroots-git (Installed: 0.5.0.r51.g8d3369d7-1)

But I can't reproduce (yet).
Now I took the time to look and cought one crash in the log:
Here is what I fished out of the syslog: I gave a little bit of context, because I noticed `unhandled X11 event: FocusOut ` and `IPC Client 183 disconnected` which don't sound normal.

```Apr 26 08:03:53 huit dbus-launch[8398]: 2019-04-26 08:03:53 - [sway/sway/commands.c:258] Handling command 'focus'
Apr 26 08:03:53 huit dbus-launch[8398]: 2019-04-26 08:03:53 - [sway/sway/commands.c:150] find_handler(focus)
Apr 26 08:03:53 huit dbus-launch[8398]: 2019-04-26 08:03:53 - [sway/sway/commands.c:258] Handling command 'floating disabled'
Apr 26 08:03:53 huit dbus-launch[8398]: 2019-04-26 08:03:53 - [sway/sway/commands.c:150] find_handler(floating)
Apr 26 08:03:53 huit dbus-launch[8398]: 2019-04-26 08:03:53 - [sway/sway/tree/arrange.c:190] Usable area for ws: 1920x1055@0,25
Apr 26 08:03:53 huit dbus-launch[8398]: 2019-04-26 08:03:53 - [sway/sway/tree/arrange.c:221] Arranging workspace 'web' at 0.000000, 25.000000
Apr 26 08:03:53 huit dbus-launch[8398]: 2019-04-26 08:03:53 - [sway/sway/tree/arrange.c:38] Arranging 0x7ffe970ea490 horizontally
Apr 26 08:03:53 huit dbus-launch[8398]: 2019-04-26 08:03:53 - [sway/sway/desktop/transaction.c:412] Transaction 0x557a7265f880 committing with 4 instructions
Apr 26 08:03:53 huit dbus-launch[8398]: 2019-04-26 08:03:53 - [sway/sway/ipc-server.c:921] Added IPC reply of type 0x0 to client 183 queue: [ { "success": true }, { "success": true }, { "success": true } ]
Apr 26 08:03:53 huit dbus-launch[8398]: 2019-04-26 08:03:53 - [xwayland/xwm.c:967] XCB_PROPERTY_NOTIFY (924)
Apr 26 08:03:53 huit dbus-launch[8398]: 2019-04-26 08:03:53 - [xwayland/xwm.c:1291] unhandled X11 event: FocusOut (10)
Apr 26 08:03:53 huit dbus-launch[8398]: 2019-04-26 08:03:53 - [xwayland/xwm.c:967] XCB_PROPERTY_NOTIFY (924)
Apr 26 08:03:53 huit dbus-launch[8398]: 2019-04-26 08:03:53 - [xwayland/xwm.c:1291] unhandled X11 event: FocusOut (10)
Apr 26 08:03:53 huit dbus-launch[8398]: 2019-04-26 08:03:53 - [sway/sway/ipc-server.c:509] Client 183 writable
Apr 26 08:03:53 huit dbus-launch[8398]: 2019-04-26 08:03:53 - [sway/sway/ipc-server.c:215] Client 183 hung up
Apr 26 08:03:53 huit dbus-launch[8398]: 2019-04-26 08:03:53 - [sway/sway/ipc-server.c:539] IPC Client 183 disconnected
Apr 26 08:03:53 huit audit[17337]: ANOM_ABEND auid=1001 uid=1001 gid=1001 ses=12 pid=17337 comm="keepassxc" exe="/usr/bin/keepassxc" sig=11 res=1
Apr 26 08:03:53 huit kernel: keepassxc[17337]: segfault at 0 ip 00007f105bab55ca sp 00007ffd659d5980 error 4 in libQt5WaylandClient.so.5.12.3[7f105baaf000+82000]
Apr 26 08:03:53 huit kernel: Code: 78 14 04 7e 13 31 db e9 43 ff ff ff 48 8b 7c 24 10 e8 9a f4 ff ff eb e3 48 89 df ff 15 f7 4e 0a 00 48 89 c7 ff 15 36 67 0a 00 <48> 8b 10 48 89 c7 ff 52 30 48 89 df 41 89 c6 67 e8 31 f7 ff ff 48
Apr 26 08:03:53 huit kernel: audit: type=1701 audit(1556258633.658:644): auid=1001 uid=1001 gid=1001 ses=12 pid=17337 comm="keepassxc" exe="/usr/bin/keepassxc" sig=11 res=1
```

I guess this is a bit little to debug from ;)
What can I do to "zoom in" here and provide more debug output ?

Thanks!

**Comment by droidmonkey** [comment]
Need Qt version. This is very likely on the Qt side of things. Their Wayland support is very beta until you get to around Qt 5.12

**Comment by Tormen** [comment]
@droidmonkey : Good point :)

`qtdiag` output: http://sprunge.us/28eAEs

The gist:
```
Using Wayland-EGL
This plugin does not support createPlatformVulkanInstance
QVulkanInstance: Failed to initialize Vulkan
Qt 5.12.3 (x86_64-little_endian-lp64 shared (dynamic) release build; by GCC 8.3.0) on "wayland" 
OS: Arch Linux [linux version 5.0.9-arch1-1-ARCH]
```

**Comment by droidmonkey** [comment]
Can you try running with ```WAYLAND_DEBUG=1 keepassxc``` which should help isolate the issue. The problem is clearly with Qt since the crash is happening in the Qt Wayland platform plugin.

Otherwise you can build a debug version of KeePassXC and run it until it crashes which should produce a Core dump.

**Comment by Tormen** [comment]
Will use `WAILAND_DEBUG=1 keepassxc` for now and update asap.
Thanks!

**Comment by Tormen** [comment]
Hi @droidmonkey, 

sorry for the delay :/

It is very easily replicable acually now for me.

1. I start keepassxc.
2. I plug an external monitor through a USB-C docking station from DELL.
3. I disable the local screen in sway to force all output to external screen.
4. I unplug external screeen.
5. I enable local screen again.

And somewhere between start of 4. and end of 5. keepassxc crashes.
I did a `date` right before (4.): Mon May  6 10:26:15 CEST 2019
And I did a `date` right after (5.): Mon May  6 10:26:31 CEST 2019

The timestamp of the crash in syslog is 10:26:18 ... so 1-2 seconds after I unplugged... but that's probably the time for udev +kernel to process the unplug event...

So it's in link with (4.), not (5.) ;)

In any case here is the syslog (jouranctl) of the crash:
```
May 06 10:26:18 huit kernel: keepassxc[2818]: segfault at 0 ip 00007f7f459125ca sp 00007ffd2d6bef50 error 4 in libQt5WaylandClient.so.5.12.3[7f7f4590c000+82000]
May 06 10:26:18 huit kernel: Code: 78 14 04 7e 13 31 db e9 43 ff ff ff 48 8b 7c 24 10 e8 9a f4 ff ff eb e3 48 89 df ff 15 f7 4e 0a 00 48 89 c7 ff 15 36 67 0a 00 <48> 8b 10 48 89 c7 ff 52 30 48 89 df 41 89 c6 67 e8 31 f7 ff ff 48
May 06 10:26:18 huit kernel: audit: type=1701 audit(1557131178.295:71): auid=1001 uid=1001 gid=1001 ses=6 pid=2818 comm="keepassxc" exe="/usr/bin/keepassxc" sig=11 res=1
May 06 10:26:18 huit audit[2818]: ANOM_ABEND auid=1001 uid=1001 gid=1001 ses=6 pid=2818 comm="keepassxc" exe="/usr/bin/keepassxc" sig=11 res=1
```

Here is the journalctl:
http://sprunge.us/voutbt

Here is the logfile created from launching keepassxc with aboves `WAYLAND_DEBUG=1`:
http://sprunge.us/dqtYxD

Hope that helps. Please let me know. Thanks!!

Tormen

**Comment by droidmonkey** [comment]
Ok that is a known Qt bug on Wayland.

https://bugreports.qt.io/browse/QTBUG-62044

It was allegedly fixed though..

**Comment by Tormen** [comment]
But then I can reopen this bug, because:
'[2019-04-23 00:32] [ALPM] upgraded qt5-wayland (5.12.2-1 -> 5.12.3-1)'
so I was already on 5.12.3-1 when I did my above "bug-capture"

Thanks for the qt-bug link.

**Comment by Tormen** [comment]
Ended up reporting a new upstream bug, as the issue you linked to happened when reconnecting and for me things happen when unplugging...

https://bugreports.qt.io/browse/QTBUG-75768
