### ISSUE TITLE
AutoOpen with file URI broken

### ISSUE THREAD

**Issue by 0xC4N1** [keepassxreboot/keepassxc#3083]
## Expected Behavior
Entries with a file URI in the AutoOpen group unlock the corresponding database as suggested in #1053

## Current Behavior
Upon unlock there is a delay and the databases from the AutoOpen group are not unlocked.

## Possible Solution
Make file URI schemes work on Windows or explain AutoOpen in the Wiki without mentioning the file URI scheme so people don't search for the pull request.

## Steps to Reproduce
1. Create C:\db1.kdbx
2. Create C:\db2.kdbx
3. Create the group `AutoOpen` in db1.kdbx
4. Create an entry in `AutoOpen` with file URI: `file://C:\db2.kdbx`
5. Lock and unlock db1.kdbx
6. Get afraid because `db1.kdbx` doesn't unlock anymore and all credentials became inaccessible until it finally unlocks after some timeout. 😉 `db2.kdbx` is still locked.
6. Change the entry URL to `C:\db2.kdbx`
7. Lock and unlock db1.kdbx - db2.kdbx should be unlocked

## Context
With https://github.com/keepassxreboot/keepassxc-browser/issues/359 in mind I was trying the workaround mentioned in https://github.com/keepassxreboot/keepassxc-browser/issues/353#issuecomment-447854533 to deny certain KeepassXC-Browser instances access to critical credentials. #1053 was the first guidance I could find about the AutoOpen feature and it mentioned to use the file URI scheme. It was quiet challenging to find out that the mentioned AutoOpen folder is actually a group in the database and I wasn't sure about it until I've managed to create a working entry without file URI scheme.

## Debug Info
KeePassXC - Version 2.4.1
Revision: 7bafe65

Qt 5.12.2
Debugging mode is disabled.

Operating system: Windows 7 SP 1 (6.1)
CPU architecture: x86_64
Kernel: winnt 6.1.7601

Enabled extensions:
- Auto-Type
- Browser-Integration
- SSH-Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

**Comment by droidmonkey** [comment]
So the issue is when you use a file uri, AutoOpen takes a long time to work?

This makes sense because the file uri will actually kick off the standard windows handling of the kdbx file. This causes a new instance of KeePassXC to launch, get closed because of single instance, and then open the database in the already existing KeePassXC instance.

So the fix is just not to use file uri's. Is this really only about documentation?

**Comment by 0xC4N1** [comment]
> So the issue is when you use a file uri, AutoOpen takes a long time to work?
It takes a long time to unlock db1.kdbx and doesn't unlock db2.kdbx when you're using a file uri.

> So the fix is just not to use file uri's. Is this really only about documentation?
It seems like AutoOpen doesn't work with file uri on Windows.

**Comment by droidmonkey** [comment]
OK, I'll tee this up for 2.5.0. In the meantime recommend not using file uri's for auto open.

**Comment by droidmonkey** [comment]
I cannot reproduce this delay behavior in 2.5.0.
