### ISSUE TITLE
List entries show with black background when hovered

### ISSUE THREAD

**Issue by adacom81** [keepassxreboot/keepassxc#3084]
areas of screen go black as i move around - move the pointer to somewhere else and all is then fine until another line or area goes black

image attached of one example

![keepass](https://user-images.githubusercontent.com/50025747/56821021-3f90d800-6845-11e9-915e-842e1d491f10.jpg)

i always ask what am i doing wrong so thats my first question

**Comment by droidmonkey** [comment]
You didn't include your debug information..

**Comment by adacom81** [comment]
sorry - new to this - missed the bit asking for that - hopefully this is what you want

KeePassXC - Version 2.4.1
Revision: 7bafe65

Qt 5.12.2
Debugging mode is disabled.

Operating system: Windows 10 (10.0)
CPU architecture: x86_64
Kernel: winnt 10.0.18362

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.4

**Comment by droidmonkey** [comment]
I've not experienced this on Windows, ever. Are you running an insider preview edition of Windows? Do you have up-to-date graphics card drivers?

**Comment by adacom81** [comment]
hi - yes am running insider preview but issue is not new - i had it on an earlier standard install 

graphics drivers are up to date - as said issue is not new - just changed my laptop - Dell E5550 - previously had Dell E6520 and it was on that - that had bog standard win 10 on it - i had tried your version a while ago and stopped using it for this reason - thought i would give it a try on this new laptop and came up with same problem

so would say its not something i am doing wrong - anything you want me to test please ask

tony

**Comment by droidmonkey** [comment]
It looks like you have custom window decorations (I can tell by the look of the minimize, maximize, close buttons). Is this true?

Are you running on a High DPI screen (aka 4K)?

**Comment by adacom81** [comment]
i am certainly running a 3rd party theme if thats what you mean by custom window decorations and would have been on the earlier laptop

screen is standard laptop res 1920 x 1080 or something like that - dont think its the screen as old laptop was lower res 

so i guess it could be the 3rd party theme - will try standard Microsoft and report back

**Comment by adacom81** [comment]
ok - am back - loaded standard windows theme and all is good - i dont want to drop the 3rd party theme so i either put up with the problem or try and find why the theme is doing it

thanks for the input

**Comment by adacom81** [comment]
for info and interest keepassX also shows black areas - not as bad as XC 
however the original KeePass does not - it may be coming from 3rd party skins but it would seem it is something you have not got right

can i say a bug?

**Comment by droidmonkey** [comment]
No, it is very likely a negative interaction with Qt. Original KeePass uses C#. This would be a bug between Qt and your theme service. Im going to close this.

**Comment by adacom81** [comment]
ok - cannot argue with that as i have no idea - themes have been around a long time but they are not supported so i guess there nothing that can be done - pity!
