### ISSUE TITLE
Crash if database is closed when "Browser Confirm Access" dialog is open and the Allow button is pressed

### ISSUE THREAD

**Issue by stefansundin** [keepassxreboot/keepassxc#3085]
## Expected Behavior
Any open "Browser Confirm Access" dialog should be automatically denied and closed.

## Current Behavior
If the Allow button is pressed after closing the database, the program crashes.

## Possible Solution
1. Add some new safeguards to prevent the crash.
2. Automatically deny and close these dialogs.

## Steps to Reproduce
1. Create a new entry and connect a browser to KeePassXC.
2. Go to the login page and get the "Browser Confirm Access" dialog.
3. Do not act on the dialog. Instead, focus the main window and close the database.
4. Click the Allow button.
5. The program crashes.

## Context
I just happened to accidentally run across this. I think this is very rare, but it could perhaps lead to data loss if multiple databases are open.

## Debug Info
KeePassXC - Version 2.4.1
Revision: 7bafe65

Qt 5.12.2
Debugging mode is disabled.

Operating system: macOS Mojave (10.14)
CPU architecture: x86_64
Kernel: darwin 18.5.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (only unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
 libgcrypt 1.8.4

**Comment by droidmonkey** [comment]
Good find, likely trying to access the pointer of the previously open database.

**Comment by varjolintu** [comment]
Same happens with popup dialog when giving a name to a new connection.

**Comment by varjolintu** [comment]
Some extra checking was also needed when making a new connection. It didn't crash but the key was only stored in the memory, not in the database itself.

Connection to `reject()` slot was enough for Linux but with macOS that still crashed. That's why I had to make some extra checking after the popup was returned.
