### ISSUE TITLE
Feature request: shamir39 as shared secret/backup for master key

### ISSUE THREAD

**Issue by anothernewusername** [keepassxreboot/keepassxc#3086]
There are circumstances (accident, death, whatever) you wish to backup your master key without actually writing it on a paper or telling it a 3rd person. Therefore one could use a mechanism like Shamir's Secret Sharing (https://en.wikipedia.org/wiki/Shamir%27s_Secret_Sharing) to provide X unique parts to different people (for example 5) and you need Y of them to regain the passphrase (for example 3). 

This could be an extra option during the creation of a new database.

A prototype of Shamir´s Secret Sharing is provided by iancoleman: https://github.com/iancoleman/shamir39 and can be tested online.

A possible scenario could be the following: you want your family to have access to your password database in the case anything bad happens to you. Therefore 5 unique parts are given to trustworthy people and you need like 3 of them to combine there parts to regain the original passphrase. Choosing the right people and telling them to handle there parts with care is up to you obviously.

**Comment by droidmonkey** [comment]
Interesting idea. In the meantime you can simply use an online tool to calculate your Shamir shards: https://asecuritysite.com/encryption/shamir

**Comment by TCB13** [comment]
+1 on this!

**Comment by anothernewusername** [comment]
Any news on this one?

**Comment by droidmonkey** [comment]
Considering that this only works for passwords and there are already numerous tools available to build the shamir secret... I don't see this getting integrated into KeePassXC any time soon.
