### ISSUE TITLE
Yubikey is listed twice in combobox

### ISSUE THREAD

**Issue by sschuberth** [keepassxreboot/keepassxc#3087]
## Expected Behavior

When configuring Yubikey Challenge-Response, my single attached Yubikey is only listed once in the combo box to choose the Yubikey from.

## Current Behavior

My single Yubikey is listed twice in the combo box (with exactly the same string incl. the same slot number).

## Possible Solution

None.

## Steps to Reproduce
1. Launch KeePassXC.
2. Create a new database.
3. Accept defaults, then "Add additional protection", then "Add Yubikey Challenge-Response".
4. Wait for the discovery of Yubikeys to finish.

## Context

N/A

## Debug Info

KeePassXC - Version 2.4.1
Revision: 7bafe65

Qt 5.12.2
Debugging mode is disabled.

Operating system: Windows 10 (10.0)
CPU architecture: x86_64
Kernel: winnt 10.0.17763

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.4

**Comment by droidmonkey** [comment]
This happens sometimes, no harm though. Still shouldn't happen.
