### ISSUE TITLE
AutoType on Mac Broken 2.4.1 -- Similar to Issue  #2883

### ISSUE THREAD

**Issue by HUGHUSR** [keepassxreboot/keepassxc#3089]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )
Just upgraded to 2.4.1 from 2.3.something. No issue with autotype in previous version.

Neither CMD-V nor SHIFT-CMD-V work.
Does not work on a second attempt to an app either. Or, third, for that matter.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

## Current Behavior
[NOTE]: # ( Tell us what actually happens )

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1.
2.
3.

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.4.1
Revision: 7bafe65

Qt 5.12.2
Debugging mode is disabled.

Operating system: macOS Sierra (10.12)
CPU architecture: x86_64
Kernel: darwin 16.7.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (only unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
 libgcrypt 1.8.4

**Comment by HUGHUSR** [comment]
A few clarifications.

1) Re: Hide window when performing entry auto-type on macOS #2969 -- I do NOT have this option selected.
2) Breaks with any app I try, including: Cliqz (any website login), Firefox (any website login), Safari (any website login), Grammarly app, iTunes app, and Adium app.

**Comment by HUGHUSR** [comment]
INI File -- in case it helps:

[General]
AutoReloadOnChange=true
AutoSaveAfterEveryChange=true
AutoSaveOnExit=true
AutoTypeDelay=25
AutoTypeEntryTitleMatch=true
AutoTypeEntryURLMatch=true
AutoTypeStartDelay=500
BackupBeforeSave=true
GlobalAutoTypeKey=0
GlobalAutoTypeModifiers=0
IgnoreGroupExpansion=true
LastChallengeResponse=@Variant(\0\0\0\x1c\0\0\0\0)
LastDatabases=/Volumes/Bar1/Bar2/Bar3/foo.kdbx
LastDir=
LastKeyFiles=@Invalid()
MinimizeOnCopy=false
OpenPreviousDatabasesOnStartup=true
RememberLastDatabases=true
RememberLastKeyFiles=false
SSHAgent=false
SingleInstance=true
UpdateCheckMessageShown=true
UseAtomicSaves=true
UseGroupIconOnEntryCreation=true
UseTouchID=@Variant(\0\0\0\x1c\0\0\0\x1\0\0\0J\0/\0V\0o\0l\0u\0m\0\x65\0s\0/\0K\0\x65\0y\0s\0/\0K\0\x44\0\x42\0 \0M\0\x61\0s\0t\0\x65\0r\0s\0/\0j\0k\0P\0\x61\0s\0s\0.\0k\0\x64\0\x62\0x\0\0\0\x1\0)

[Browser]
AlwaysAllowAccess=false
AlwaysAllowUpdate=false
BestMatchOnly=false
CustomProxyLocation=
Enabled=false
HttpAuthPermission=false
MatchUrlScheme=true
SearchInAllDatabases=false
ShowNotification=true
SortByUsername=false
SupportBrowserProxy=true
SupportKphFields=true
UnlockDatabase=true
UpdateBinaryPath=true
UseCustomProxy=false

[GUI]
CheckForUpdates=true
CheckForUpdatesIncludeBetas=false
CheckForUpdatesNextCheck=1556931127
DarkTrayIcon=false
HidePreviewPanel=true
HideToolbar=false
Language=system
MinimizeOnClose=false
MinimizeOnStartup=false
MinimizeToTray=false
MovableToolbar=false
ShowTrayIcon=false
ToolButtonStyle=1

[KeeShare]
Settings.active="<?xml version=\"1.0\"?>\n<KeeShare xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\">\n  <Active/>\n</KeeShare>\n"
Settings.foreign="<?xml version=\"1.0\"?>\n<KeeShare xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\">\n  <Foreign/>\n</KeeShare>\n"
Settings.own="<?xml version=\"1.0\"?>\n<KeeShare xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\">\n  <PrivateKey/>\n  <PublicKey/>\n</KeeShare>\n"

[security]
HidePasswordPreviewPanel=true
IconDownloadFallback=true
autotypeask=true
clearclipboard=true
clearclipboardtimeout=20
hidenotes=false
lockdatabaseidle=true
lockdatabaseidlesec=3600
lockdatabaseminimize=true
lockdatabasescreenlock=true
passwordemptynodots=true
passwordscleartext=true
passwordsrepeat=true
relockautotype=false
resettouchid=false
resettouchidscreenlock=true
resettouchidtimeout=30

**Comment by gfairchild** [comment]
I can confirm. I'm seeing the same behavior. I'm running 2.4.1 on macOS 10.14.4.

**Comment by Eyjafjallajokull** [comment]
Same here, nothing happens when I press autotype key. I've downgraded to 2.3.4 and works fine.

**Comment by droidmonkey** [comment]
Try disabling and enabling accessibility access for KeePassXC in the macOS settings.

**Comment by HUGHUSR** [comment]
Hi,
Sorry... but I have no clue. I don't see anywhere in settings in macOS
10.12.6 to control this. Nothing in Accessibility and nothing in
Extensions. Where should I have been looking?
Thanks!
On 5/14/2019 at 4:59 PM, "Jonathan White"  wrote:

	Try disabling and enabling accessibility access for KeePassXC in the
macOS settings.

**Comment by HUGHUSR** [comment]
Uh... I found it -- security & privacy. It never has been enabled.
Enabling it did not fix the problem.
On 5/14/2019 at 5:55 PM, hu-github@nym.hush.com wrote:Hi,
Sorry... but I have no clue. I don't see anywhere in settings in macOS
10.12.6 to control this. Nothing in Accessibility and nothing in
Extensions. Where should I have been looking?
Thanks!
On 5/14/2019 at 4:59 PM, "Jonathan White"  wrote:

	Try disabling and enabling accessibility access for KeePassXC in the
macOS settings.

**Comment by HUGHUSR** [comment]
For what it is worth, upgraded to 2.4.3 and this is still broken.
If I downgrade 2.3.4, it works. So, it is not a macOS issue.

**Comment by droidmonkey** [comment]
I just used auto-type with 2.4.3 on macOS. I can assure you it works.

**Comment by gfairchild** [comment]
Clicking on a row in KeePassXC and hitting CMD+V definitely does *not* work for me. This used to work without issue, but it no longer works for me with 2.4.3. @droidmonkey, how did you make it work for you? Is there some config change that needs to happen?

**Comment by droidmonkey** [comment]
The keyboard shortcut for selected Auto-Type was changed to CMD+SHIFT+V in 2.4.0

**Comment by HUGHUSR** [comment]
Hi,
Can you please explain to me what I may be doing different that is
preventing it from working?
I have tried it on two different Macs and it fails on both.
The only thing potentially unusual is that I have the app installed on
the memory stick with my databases.
Also, I don't have a problem with 2.3.x, so what could possibly be
different?
Thanks!
Jon K
On 6/19/2019 at 11:04 AM, "Jonathan White"  wrote:

	I just used auto-type with 2.4.3 on macOS. I can assure you it works.
I meant to close this before.

**Comment by HUGHUSR** [comment]
Right.
But, when using that shortcut, or using the menu, it still does not
work.
I have done some experimenting. If I enable Global AutoType, it never
finds a match on either title or URL -- despite them being exact
matches for what is in KDBX.
I appreciate any help / suggestions you may have.
Thanks!Jon K
On 6/19/2019 at 7:39 PM, "Jonathan White"  wrote:

	The keyboard shortcut for selected Auto-Type was changed to
CMD+SHIFT+V in 2.4.0

**Comment by droidmonkey** [comment]
If you are using the "entry level" auto-type and the KeePassXC window goes to the background and the last used window gets focus but nothing gets typed... that indicates the accessibility "control of computer" setting is not applying. Remove and re-add KeePassXC as a trusted application. If you have BOTH KeePassXC 2.3.4 and 2.4.3 installed you may have to enable both of them.

If you are using the global auto-type and nothing is being found in the database, try relaxing the window matching criteria by introducing wildcards:

![image](https://user-images.githubusercontent.com/2809491/59853578-22f1b780-933f-11e9-8602-fc022d84fc98.png)

**Comment by gfairchild** [comment]
> The keyboard shortcut for selected Auto-Type was changed to CMD+SHIFT+V in 2.4.0

This worked! I must've missed that line when I read the changelog. Thanks for the help.
