### ISSUE TITLE
Can't select several hotkey combinations for autotype.

### ISSUE THREAD

**Issue by freakynl** [keepassxreboot/keepassxc#309]
Hi,

I used to use Alt+P as the hotkey for autotype. This, and several other Alt+, combinations currently can't be set because of the hotkeys assigned to several checkboxes. When trying to set Alt+P, it will get stuck at Alt+, because when pressing the P whilst holding alt it will flip the checkbox for the 'Load previous databases on startup' setting.

Likewise you can't set Alt+M as it flips 'Minimize when copying to clipboard' etc.

**Comment by phoerious** [comment]
Please don't delete the issue template.
What operating system are you using?

**Comment by freakynl** [comment]
Hi,

I'm on gentoo linux.

Resolved it for now by setting it manually in ~/.config/keepassxc/keepassxc.ini GlobalAutoTypeKey=80

**Comment by TheZ3ro** [comment]
Note that you can't use in-program hotkey as autotype-hotkey

**Comment by phoerious** [comment]
Are you, by any chance, using KDE? The KDE platform themes seems to add Alt hotkey accelerators automatically.

**Comment by freakynl** [comment]
Hi,

yes I'm using KDE on gentoo. Can set the same hotkey fine with keepassx on the same system, but in keepassxc the hotkey thus flips the checkbox instead. Many options get a letter underlined when holding the alt key on that screen indicating the shortcut Alt+<underlined letter> for flipping the setting.

Also have a laptop with Fedora 24. Used the unofficial package that's been added to the site (I think yesterday, there was no link for Fedora when I checked on Tuesday). I can set the hotkey just fine there as and don't see any underscores for the other options when holding Alt then.

It works fine by setting it manually in the configuration ini file. Just a matter of finding the right code (80 in case of Alt+P).

**Comment by phoerious** [comment]
It's a problem with the KDE Platform Theme.
You can disable automatic accelerators by adding this to your `~/.config/kdeglobals`:
```
[Development]
AutoCheckAccelerators=false
```

**Comment by phoerious** [comment]
I'm closing this, since it can't be fixed from our side. You may file a bug report with KDE, though.
