### ISSUE TITLE
Excess CPU usage on macOS when database locks after switching user

### ISSUE THREAD

**Issue by HUGHUSR** [keepassxreboot/keepassxc#3090]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

When do a switch-user, if KeePassXC has an open database on the user who is being switched out, you get a CPU runaway on that user -- apparently when it tries to lock the database on the switch (a previous bug I reported) but doesn't have access to the UI (or, so is my guess).

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Database on switched-away-from user to be locked but not kill the CPU.

## Current Behavior
[NOTE]: # ( Tell us what actually happens )
See screen shots.
setup: original user (user switched away from): kiblerj
current user: anon
KeePassXC-CPUrunaway.png -- Shows runaway CPU usage.

switch back to kiblerj and cpu immediately drops no nominal:
KeePassXC-SwitchBack.png

<img width="1074" alt="KeePassXC-SwitchBack" src="https://user-images.githubusercontent.com/46979127/56844047-23f2f500-6878-11e9-90bf-0a62f295dc6d.png">
<img width="807" alt="KeePassXC-CPUrunaway" src="https://user-images.githubusercontent.com/46979127/56844049-2a816c80-6878-11e9-91df-14109924fb97.png">

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1. User "A" -- Open KDBX
2. Switch to User "B"
3. Not clear if it tries to close KDBX on User A immediately or when database open timer times out, but suddenly fans start running and checking CPU utilization from User B shows high KeePassXC utilization
3a. Don't know if relevant, but also have a KDBX file open on User B at the same time, However, User B KeePassXC CPU utilization normal
4. Switch back to User A
5. CPU utilization instantly drops back to normal

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )
I am running KeePassXC from /Volume/FlashDrive/Applications -- that is, I have it installed on a flashdrive instead of on my Mac (I travel too much internationally, and don't want any visibility that I have a password database).

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.4.1
Revision: 7bafe65

Qt 5.12.2
Debugging mode is disabled.

Operating system: macOS Sierra (10.12)
CPU architecture: x86_64
Kernel: darwin 16.7.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (only unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
 libgcrypt 1.8.4

**Comment by HUGHUSR** [comment]
This is different behavior than I had observed in 2.3.4 with bug #2642. I had thought the bug was fixed, as the database now appears to close on switching users, but but #2642 still shows as open.

**Comment by droidmonkey** [comment]
I cannot replicate the excessive CPU usage, but I also notice that the database does NOT lock when switching users. This is on macOS 10.14.3.

**Comment by HUGHUSR** [comment]
A little clarification and some more details...

Assume:   USER-A -- Original User who opens a KDBX file, then with
KeePassXC open, does a switch user via AppleScript
   USER-B -- Second User who is switched to from USER-A. USER-B then
opens a different KDBX file

There appears to be two use-cases here:
1) At some point after the switch user from USER-A to USER-B occurs
(time varies; no pattern identified thus far), USER-A's KeePassXC CPU
utilization starts to increase until it is consuming >50% of CPU. When
switching back to USER-A from USER-B, USER-A's KDBX database is now
LOCKED whereas it had been unlocked before switch. After switching
back to USER-A, CPU utilization drops to normal background
utilization. Conjecture: USER-A's KeePassXC is trying to lock the
database but can't get control of the UI to make the required change,
driving the CPU utilization up, but as soon as the switch back to
USER-A occurs, the database locks and CPU utilization returns to
normal. If I had to venture a guess here, sometimes the lock DB
timeout timer expires when USER-A is not the active user, and other
times, it does not; why this difference would be the question I would
have.

2) After switching to USER-B, no attempt to lock USER-A's KDBX file
occurs, and there is no increase in CPU utilization. Returning to
USER-A the KDBX file is still unlocked.
I have not figured out a reproducible way to create Use-Case #1. It
just seems to happen at random and only started after upgrading to
2.4.1.

Also, just for what it is worth, I use the following AppleScript to do
a SwitchUser:     do shell script "/System/Library/CoreServices/Menu\
Extras/User.menu/Contents/Resources/CGSession -suspend"
II simply invoke it from the AppleScripts icon on the menu bar. Don't
know if that makes any difference here.
On 4/27/2019 at 11:45 AM, "Jonathan White"  wrote:

	I cannot replicate the excessive CPU usage, but I also notice that
the database does NOT lock when switching users. This is on macOS
10.14.3.

**Comment by HUGHUSR** [comment]
I have some additional information.
1) Screen shot in second user (anon) showing high utilization in first user (kiblerj) [ kpxc-am.png]
2) Spin dump taken from second user [kpxc-Spindump.txt]
3) When returning to first user, CPU utilization drops back to normal [kpxc-after-am.png]
4) When returning to second user, CPU utilization again goes high
<img width="800" alt="kpxc-am" src="https://user-images.githubusercontent.com/46979127/60577440-612ea400-9d4d-11e9-8410-a79bceea9a05.png">
[kpxc-Spindump.txt](https://github.com/keepassxreboot/keepassxc/files/3354056/kpxc-Spindump.txt)
<img width="1079" alt="kpxc-after-am" src="https://user-images.githubusercontent.com/46979127/60577441-612ea400-9d4d-11e9-8f43-96943477e494.png">

**Comment by HUGHUSR** [comment]
Another instance of runaway.

This is a spingdump once again. 

[Spindump2.txt](https://github.com/keepassxreboot/keepassxc/files/3368009/Spindump2.txt)

I tried sampling the process, but it ran for over 20 minutes and then froze my system. I had to sleep the box, then I was able to kill the sampling, then the KeePassXC process.

**Comment by droidmonkey** [comment]
Based on your spindump it is clearly not KeePassXC code that is causing this. Most likely this is an issue in Qt.

**Comment by droidmonkey** [comment]
Not seeing this anymore with the latest version
