### ISSUE TITLE
Entry-Specific Special Characters for Password Generator

### ISSUE THREAD

**Issue by HUGHUSR** [keepassxreboot/keepassxc#3091]
[TIP]:  # ( Provide a general summary of the feature in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Summary
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
Many websites and a few apps are lame and only allow some subset of special characters to be used in their passwords. It would be nice to be able to define what the allowed special characters are (a KDBX column?) and when present, use those as the default for special characters when generating passwords.

Why? Because it is often a real pain to figure out what special characters are and are not allowed, and when a site requires passwords to be changed every 30 days (lame!), it is a real pain to have to track down what are the allowed special characters.

An additional related feature would be to allow the entry of what is the minimum and maximum password length allowed for a given entry, then constrain the password length generator to that range if that information is entered.

## Desired Behavior
[NOTE]: # ( Tell us how the new feature should work, be specific )

For a given website or application (KDBX entry) you optionally can enter the subset of special characters allowed by that site/app, and optionally enter the minimum and maximum password lengths, and if any of that information is provided for the entry, when the password generation creates a password for that site, it uses the information provided when creating the password.

## Possible Solution
[NOTE]: # ( Not required, but suggest ideas on how to implement the addition or change )

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )

I have several hundred passwords and probably a third of them have to be changed every 30 to 90 days. Most only allow a few of the special characters (sites are too stupid to do proper special character escaping in dialog boxes) and have strange length requirements (e.g., 7 to 21 characters). Remembering all those constraints or having to look them up every time you have to create a new password is a pain!

**Comment by droidmonkey** [comment]
This is covered under #2628
