### ISSUE TITLE
Send "Password About To Expire" Notifications (macOS)

### ISSUE THREAD

**Issue by HUGHUSR** [keepassxreboot/keepassxc#3092]
[TIP]:  # ( Provide a general summary of the feature in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Summary
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
I have several hundred passwords across about a dozen password databases. Many of the passwords expire every 30 to 90 days. Rather than have to continually check for expiring passwords, it would be nice to have KeePassXC send notifications X days in advance of expiration (X to be determined by the user).

## Desired Behavior
[NOTE]: # ( Tell us how the new feature should work, be specific )
Use macOS notifications to send expiration notifications.

## Possible Solution
[NOTE]: # ( Not required, but suggest ideas on how to implement the addition or change )
The "Expiration List" should be independent of the databases, as I would want to receive a notification of an expiration on a password in a database that has not been recently opened, as well as databases that are currently open.

My thought would be to create a table in the INI file (or elsewhere) that had three columns: Database Name, GroupNamePath/EntryName, Entry Title. Then, whenever KeePassXC runs, it would check for expiring passwords on a regular (daily?) basis and send notifications. An even better solution would be to have a "helper" app that started on login and ran in the background and did nothing but send notifications -- so you'd get notifications even if you were not running KeePassXC.

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
I'm tired of having passwords expire and having to deal with various client's tech support departments to get my password reset. It also makes me look lame to my clients.

**Comment by HUGHUSR** [comment]
Some more thought on this issue. Complicating factors that must be taken into account:
1) Databases may be shared by more than one user, so should every user that opens the database  be on the distribution list for that expiration??
2) Or, should only the person who created an entry be notified?
3) Or, should this be user-configurable (Notify me if this entry expires)?

I can see where this could become an interesting problem...

**Comment by droidmonkey** [comment]
This is covered under #551. We are not going to be implementing a continuous notification service nor store information from a database into the INI file.
