### ISSUE TITLE
Cannot close and discard changes on one database while another is opened

### ISSUE THREAD

**Issue by danielnbalasoiu** [keepassxreboot/keepassxc#3094]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
While opening two databases, keep changes to one database and discard them to the second database.

## Current Behavior
[NOTE]: # ( Tell us what actually happens )
Cannot discard the changes on one database and save them on the other without saving both databases (or kill the application and lose all changes).

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1. Open a Keepass database
2. Open another Keepass databse
3. Make some changes on both databases
4. Save just one database and discard the changes on the other one.

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.3.3
Revision: 0a155d8

Libraries:
- Qt 5.9.3
- libgcrypt 1.8.2

Operating system: macOS 10.14
CPU architecture: x86_64
Kernel: darwin 18.5.0

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

[Related: https://github.com/keepassxreboot/keepassxc/issues/1312](https://github.com/keepassxreboot/keepassxc/issues/1312)

**Comment by droidmonkey** [comment]
First step, you need to update to version 2.4.1.

**Comment by danielnbalasoiu** [comment]
Work fine with the latest version (2.4.1) 
Thank you!
