### ISSUE TITLE
'key exchange was not sucessful' error with Debian 10 (Buster), firefox 66.0.03, keepassxc 2.4.1 both installed via 'snap' package manager

### ISSUE THREAD

**Issue by sputnick-dev** [keepassxreboot/keepassxc#3095]
Installed keepassxc and firefox via `snap install <pkg>`

Now, I can't connect the firefox keepassxc plugin to the keepassxc instance (browser integration enabled) even after reboot (just to be 100% sure)

Was working well with firefox-esr and keepassxc installed via `apt`

## filtered strace output
	[pid 24435] open("/proc/self/mountinfo", O_RDONLY) = 99
	[pid 24435] quotactl(QCMD(Q_GETQUOTA, USRQUOTA), "ext4", 1000, 0x7f75d43c97f0) = -1 ENOENT (No such file or directory)
	[pid 24435] open("/home/stardust/snap/firefox/common/.mozilla/firefox/dtq5boiy.20190211/storage/default/moz-extension+++0503e311-c7b4-4658-bf09-2aae177bc7bf^userContextId=4294967295/idb", O_RDONLY|O_CLOEXEC) = 99
	[pid 24446] +++ exited with 0 +++
	[pid 25594] open("/home/stardust/snap/firefox/common/.mozilla/native-messaging-hosts/org.keepassxc.keepassxc_browser.json", O_RDONLY) = -1 ENOENT (No such file or directory)
	[pid 25594] open("/usr/lib/mozilla/native-messaging-hosts/org.keepassxc.keepassxc_browser.json", O_RDONLY) = -1 ENOENT (No such file or directory)
	[pid 25594] open("/home/stardust/snap/firefox/common/.mozilla/native-messaging-hosts/org.keepassxc.keepassxc_browser.json", O_RDONLY) = -1 ENOENT (No such file or directory)
	[pid 25594] open("/usr/lib/mozilla/native-messaging-hosts/org.keepassxc.keepassxc_browser.json", O_RDONLY) = -1 ENOENT (No such file or directory)

but after copying :
    cp ~/.mozilla/* /home/stardust/snap/firefox/common/.mozilla

no more strace errors, but 'key exchange' failed

## Expected Behavior
I expect to successfully connect to DB

## Current Behavior
Can't connect to database

## Steps to Reproduce

1. open keepassxc
2. open firefox
3. click on the button 'connect'

## Context
 - debian 10 buster
 - firefox 66.0.03
 - keepassxc 2.4.1
 - snap/snapd 2.38
 <t_�k>b<t_��><t_��><t_��><t_��><t_��><t_��>kbh				
- x86_64 kernel 4.19.0-4-amd64

**Comment by droidmonkey** [comment]
We currently do not support browsers installed as snaps.

**Comment by damufo** [comment]
Same problem with:
Debian 9 Stretch
Kernel 4.19.0
Waterfox 56.2.10
