### ISSUE TITLE
Ubuntu Firefox Apparmor is blocking proxy execution

### ISSUE THREAD

**Issue by colans** [keepassxreboot/keepassxc#3096]
## Expected Behavior

KeePassXC-Browser connects to the database.

## Current Behavior

`Cannot connect to KeePassXC. Check that browser integration is enabled in KeePassXC settings.`

And the following in syslog:

> Apr 28 00:00:43 snake kernel: [ 5557.144991] audit: type=1400 audit(1556424043.323:187): apparmor="DENIED" operation="exec" profile="/usr/lib/firefox/firefox{,*[^s][^h]}" name="/usr/bin/keepassxc-proxy" pid=24413 comm=444F4D20576F726B6572 requested_mask="x" denied_mask="x" fsuid=1000 ouid=0

## Possible Solution

1. Provide an automatic allowance for this communication in the Debian/Ubuntu package.
1. Provide documentation for how one can fix this if it can't be provided with the `deb`.
1. At the very least, add this possibility to the [troubleshooting guide](https://github.com/keepassxreboot/keepassxc/issues/1559#issuecomment-369508900), and explain how it can be fixed.

I still have no idea how to get this working.  Is there a specific command that can be run to allow the connection, and have it persist?

## Steps to Reproduce

1. `sudo apt install keepassxc`
1. Run KeePassXC.
1. Run Firefox.
1. Install KeePassXC-Browser
1. Attempt to connect it with the DB as per the docs.

## Debug Info

KeePassXC - Version 2.4.1
Revision: 7bafe65

Qt 5.12.2
Debugging mode is disabled.

Operating system: Ubuntu 19.04
CPU architecture: x86_64
Kernel: linux 5.0.0-13-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.4

**Comment by droidmonkey** [comment]
We don't deploy with App Armor expect the snap. Are you running Firefox with app armor?

**Comment by colans** [comment]
@droidmonkey I was using the snap initially, but then I switched to the deb after if was new enough.

Is it possible that `sudo snap remove keepassxc` didn't remove everything?  Or could it be another problem?

**Comment by droidmonkey** [comment]
You can use KeePassXC browser with the latest snap version.

**Comment by colans** [comment]
Okay, thanks, but is is possible to switch?  If so, how can this be fixed?

**Comment by droidmonkey** [comment]
Are you running Firefox as a snap?

**Comment by colans** [comment]
No, I'm not.  It's the standard Firefox `deb` that's in the Ubuntu repos.

```sh
colan@snake[Sun 28 15:29]% snap list                                           
Name               Version          Rev   Tracking  Publisher       Notes
core               16-2.38          6673  stable    canonical✓      core
core18             20190409         941   stable    canonical✓      base
gtk-common-themes  0.1-16-g2287c87  1198  stable    canonical✓      -
keepassxc          2.4.1            267   stable    keepassxreboot  -
phpstorm           2019.1.1         95    stable    jetbrains✓      classic
```

**Comment by droidmonkey** [comment]
You are running some form of App Armor on your browser. That error is telling me the browser App Armor policy is denying execution of the keepassxc-proxy.

**Comment by colans** [comment]
That makes sense, but to the best of my knowledge, I've made no changes to the default Firefox-Apparmor set-up.  (I didn't even know how Apparmor worked until I researched it today.)  As such, I've opened [an Ubuntu bug report for Firefox](https://bugs.launchpad.net/ubuntu/+source/firefox/+bug/1826793).

Thanks for helping me track this down.  Any additional insight or help you could provide to move this along would be appreciated.

What I don't understand is why I'm running into this on one particular device (not my other laptop), and why there aren't more folks running into this as well.

**Comment by droidmonkey** [comment]
Typically people just "deal with it" and try something else. Thank you for posting an issue, you are in the 1% club! Luckily our users are more active/vocal than usual, which lets us fix issues for the majority.

**Comment by colans** [comment]
Thanks for jumping in there.  This may be a Debian (Ubuntu upstream) issue, not just an Ubuntu one, but I'm not completely sure so maybe the title here isn't generic enough.  I posed the question in the Launchpad ticket.

Re reporting issues: As a [FLOSS maintainer myself](https://en.wikipedia.org/wiki/Aegir_Hosting_System), I can't not do it for other projects. ;)

**Comment by StableNarwhal** [comment]
Stumbled across this issue myself after finding out about AppArmor only a few minutes ago. 
This isn't something fixable by the keepass maintainers I recon, you have to modify your Firefox AppArmor profile.

Here's how I fixed it:
1. Set your firefox profile to complain by invoking `aa-complain usr.bin.firefox` or your respective profile path.
2. Run `aa-logprof` and set your keepassxc-proxy to (C)hild
3. Set your firefox profile to complain by invoking `aa-enforce usr.bin.firefox`

Cheers!

**Comment by alexanderadam** [comment]
Thank you for this @StableNarwhal!

I had to install `apparmor-utils` since `aa-complain` and `aa-logprof` aren't available otherwise.

> * Run `aa-logprof` and set your keepassxc-proxy to (C)hild
> 
> * Set your firefox profile to complain by invoking `aa-enforce usr.bin.firefox`

Would it be possible to explain these steps with more details?

Thank you in advance!

**Comment by StableNarwhal** [comment]
> 
> 
> Thank you for this @StableNarwhal!
> 
> I had to install `apparmor-utils` since `aa-complain` and `aa-logprof` aren't available otherwise.
> 
> > * Run `aa-logprof` and set your keepassxc-proxy to (C)hild
> > * Set your firefox profile to complain by invoking `aa-enforce usr.bin.firefox`
> 
> Would it be possible to explain these steps with more details?
> 
> Thank you in advance!

It's been a while, so I won't be able to provide an in-depth explanation without researching again myself, unfortunately.
But what these terminal commands basically do is this:
1. By invoking **aa-complain** on your firefox instance, you set the enforcement mode to complain mode. In this mode security policy is not enforced but rather access violations are logged to the system log.
2. By invoking **aa-logproof**, you are able to update your existing AA profile based on logged violations (We turned on logging in step 1). Since keypassxc-proxy will be logged as one of those violations, we are able to modify the profile rules regarding the process. By setting it to (C)hild, we allow it to run it with a sub-profile of the parent process, effectively allowing communication via native messaging **only** for our proxy. 
3. By invoking **aa-enforce** we turn the strict enforcement of the new profile back on, this time with the added exception.

I hope this was helpful!

**Comment by alexanderadam** [comment]
### Step 1

```bash
$ sudo aa-complain usr.bin.firefox
Setting /etc/apparmor.d/usr.bin.firefox to complain mode.
```

### Step 2

I'm not quite sure how I add `keepassxc-proxy` to child:

![sudo aa-logprof Reading log entries from /var/log/syslog. Updating AppArmor profiles in /etc/apparmor.d. Enforce-mode changes:  Profile:    /usr/lib/snapd/snap-confine Capability: fsetid Severity:   9   [1 - #include <abstractions/libvirt-qemu>]   2 - capability fsetid,  (A)llow / [(D)eny] / (I)gnore / Audi(t) / Abo(r)t / (F)inish  Profile:    firefox Capability: sys_admin Severity:   10   [1 - capability sys_admin,] (A)llow / [(D)eny] / (I)gnore / Audi(t) / Abo(r)t / (F)inish  Profile:  firefox Path:     /run/user/1000/ICEauthority New Mode: owner r Severity: unknown   [1 - owner /run/user/1000/ICEauthority r,] (A)llow / [(D)eny] / (I)gnore / (G)lob / Glob with (E)xtension / (N)ew / Audi(t) / (O)wner permissions off / Abo(r)t / (F)inish  Profile:  firefox Path:     /sys/devices/pci0000:00/0000:00:0d.0/resource New Mode: r Severity: 4   [1 - /sys/devices/pci0000:00/0000:00:0d.0/resource r,] (A)llow / [(D)eny] / (I)gnore / (G)lob / Glob with (E)xtension / (N)ew / Audi(t) / Abo(r)t / (F)inish](https://user-images.githubusercontent.com/372620/107885599-93c5ea00-6efb-11eb-8f47-2e0ee97867a4.png)

For now I typed `i`gnore for every entry. These are all.

**Comment by StableNarwhal** [comment]
Did you try to connect Keepass to Firefox after enabling complain mode and before invoking aa-logproof? As far as I remember, it should up.

**Comment by alexanderadam** [comment]
Yes, and `dmesg -rw` is even showing the log entries.

**Comment by alexanderadam** [comment]
Ah, I see: the initial post was about `profile="/usr/lib/firefox/firefox{,*[^s][^h]}"` but mine are about `profile="snap.keepassxc.proxy"` and `profile="snap.keepassxc.keepassxc"`!

Sorry, this is probably a different issue then!

**Comment by StableNarwhal** [comment]
Firefox itself was sufficient when I tried it 2 years ago. Does it show up if you substitute **usr.bin.firefox** with **/etc/apparmor.d/usr.bin.firefox** ?

**Comment by alexanderadam** [comment]
No, but I just saw that my `dmesg` is full of:

```
<5>[….… audit: type=1400 audit(….…:…): apparmor="DENIED" operation="open" profile="snap.keepassxc.proxy" name="/snap/core/…/usr/share/locale/en_GB/LC_MESSAGES/snappy.mo" pid=500505 comm="snap-exec" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
```

after KeePassXC is _closed_‽

When I start KeePassXC I'm getting
```
<5>[….…] audit: type=1400 audit(….…:…): apparmor="DENIED" operation="open" profile="snap.keepassxc.keepassxc" name="/snap/core/10823/usr/share/locale/en_GB/LC_MESSAGES/snappy.mo" pid=… comm="snap-exec" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
<5>[….…] audit: type=1400 audit(….…:…): apparmor="DENIED" operation="open" profile="snap.keepassxc.keepassxc" name="/sys/bus/usb/devices/" pid=… comm="keepassxc" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
<5>[….…] audit: type=1107 audit(….…:…): pid=… uid=103 auid=4294967295 ses=4294967295 subj=unconfined msg='apparmor="DENIED" operation="dbus_method_call"  bus="system" path="/org/freedesktop/login1" interface="org.freedesktop.DBus.Introspectable" member="Introspect" mask="send" name="org.freedesktop.login1" pid=… label="snap.keepassxc.keepassxc" peer_pid=… peer_label="unconfined"
                   exe="/usr/bin/dbus-daemon" sauid=103 hostname=? addr=? terminal=?'
<5>[….…] audit: type=1107 audit(….…:…): pid=… uid=103 auid=4294967295 ses=4294967295 subj=unconfined msg='apparmor="DENIED" operation="dbus_method_call"  bus="system" path="/org/freedesktop/login1" interface="org.freedesktop.login1.Manager" member="GetSession" mask="send" name="org.freedesktop.login1" pid=… label="snap.keepassxc.keepassxc" peer_pid=15592 peer_label="unconfined"
                   exe="/usr/bin/dbus-daemon" sauid=103 hostname=? addr=? terminal=?'
<5>[….…] audit: type=1400 audit(….…:…): apparmor="DENIED" operation="open" profile="snap.keepassxc.proxy" name="/snap/core/10823/usr/share/locale/en_GB/LC_MESSAGES/snappy.mo" pid=… comm="snap-exec" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
```

So maybe it is an external call in that case? Or is that the call coming from the Firefox extension who wants to communicate with KeePassXC?

**Comment by StableNarwhal** [comment]
Hm, maybe the containerized nature of snaps is the issue here. You could try to run KeepaasXC as a traditional package and see if it works then, otherwise I'm out of ideas, unfortunately.

**Comment by varjolintu** [comment]
Related thread: #281.
