### ISSUE TITLE
When "never ask before accessing credentials" don't save access info

### ISSUE THREAD

**Issue by AdamPS** [keepassxreboot/keepassxc#3098]
## Steps to Reproduce
1. Enable browser integration
2. Enable advanced setting "Never ask before accessing credentials"
3. Use the browser to create a new entry

## Expected Behavior
New entry should not have property "KeePassXC-Browser Settings" - this property is not needed with the above setting.

## Current Behavior
New entry has property "KeePassXC-Browser Settings"

## Possible Solution
Remove "KeePassXC-Browser Settings" property when a entry is saved if "Never ask before accessing credentials" is enabled.

## Debug Info
KeePassXC - Version 2.4.1
Revision: 7bafe65

Qt 5.12.2
Debugging mode is disabled.

Operating system: Windows 7 SP 1 (6.1)
CPU architecture: x86_64
Kernel: winnt 6.1.7601

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.4

**Comment by droidmonkey** [comment]
I am on the fence about this. It is nice to have a record of which entries were accessed, this property kind of does that. Also, if this setting is disabled then you'll have to reapprove access to previously used entries if the property was not stored.

These type of settings should not be written in the negative. It should be written as: "Allow access to all entries without confirmation"

**Comment by AdamPS** [comment]
Thanks for reading my issue.

Personally I just don't want the clutter in my database.  For any user who is sharing the database across multiple devices  (e.g. Android) this property isn't very useful or accurate because as far as I know other KeePass programs don't read or write to it.

I guess it could be an option whether to discard them or not?

**Comment by droidmonkey** [comment]
It's technically not cluttering anything because as of 2.4.0 these properties are stored in the entry's custom data which is not meant for users to interact with.

**Comment by AdamPS** [comment]
Fair enough - it sort of bugs me but I should just get over it I guess!
