### ISSUE TITLE
What is the History setting for?

### ISSUE THREAD

**Issue by emkei-cz** [keepassxreboot/keepassxc#3099]
Hello, What exactly is the history setting for?
https://i.vgy.me/3Z8rUI.png

**Comment by droidmonkey** [comment]
Please directly embed your image into your post.

I am assuming you are talking about the history settings in the database settings. They restrict the number and size of entry history if enabled.

**Comment by emkei-cz** [comment]
@droidmonkey Yes I speak (history settings in the database settings)

What history and size limit? please be more specific.
I can't see any log record history in the program.

**Comment by droidmonkey** [comment]
Its for each entry

**Comment by emkei-cz** [comment]
@droidmonkey I don't understand what you mean.
I repeat, please be more specific to what this function does or reopen Topic if someone else can answer, thanks.

**Comment by droidmonkey** [comment]
This is an entry:

![image](https://user-images.githubusercontent.com/2809491/56985677-e1bb0380-6b56-11e9-8006-ee51d52021d7.png)

Double click it (or press ENTER) to edit it.

![image](https://user-images.githubusercontent.com/2809491/56985703-ef708900-6b56-11e9-859e-43cec547674b.png)

Click this down arrow to see more editing options

![image](https://user-images.githubusercontent.com/2809491/56985711-f8f9f100-6b56-11e9-8ce2-c358f54ffd3d.png)

This is your entry's history. You can view an older version and restore it if you like. The number you put in the max history items dictates the maximum number of items will be in this list. The oldest items get deleted if there are more than the number set.

The maximum history size calculates the total size of the history items and deletes the oldest ones until the history goes below that max size.
