### ISSUE TITLE
Add Choose Custom login fields option to KeepassXC-Browser submenu

### ISSUE THREAD

**Issue by rcalpha** [keepassxreboot/keepassxc#3101]
## Summary
Some website, like for example banks, open a windows without address bar so the KeepassXC icon cannot be accesed to invoke "Choose Custom login fields" to configure the fields for that webiste

## Desired Behavior

In the KeepassXC-Browser submenu using right mouse click over a form field, have an option to invoke the "Choose Custom login fields for this page" action, as an alternative

## Context

I access a bank website that open a windows without address bar and doesn't have the KeepassXC-Browser icon. This login page have 3 fields needed for login

**Comment by droidmonkey** [comment]
Duplicate of issue already in the browser extension repository

**Comment by schnittchen** [comment]
See https://github.com/keepassxreboot/keepassxc-browser/issues/122
