### ISSUE TITLE
text fields grey, but usable

### ISSUE THREAD

**Issue by mer2329** [keepassxreboot/keepassxc#3102]
## Expected Behavior
1) open database
2) see all text fields are normal colored
3) add or edit a new entry
4) see all text fields are normal colored

## Current Behavior
1) open database
2) see all text fields have a grey coloring on them see (attached image 1)
3) add or edit a new entry
2) see all single line text fields have a grey coloring on them (see attached image 2)

## Steps to Reproduce
see behavior

## Context
this issue confuses my mother, as when she sees a grayed text field. she assumes it is "grayed out" and unusable.

## Debug Info
KeePassXC - Version 2.4.1
Revision: 7bafe65

Libraries:
Qt 5.9.5
Debugging mode is disabled.

Operating system: Linux Mint 19.1
CPU architecture: x86_64
Kernel: linux 4.15.0-48-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (only unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.1

## Attachments
attachments are sterile. all possibly sensitive info has been removed
![1](https://user-images.githubusercontent.com/6768243/56976583-e4a6fb80-6b38-11e9-9a3a-e998f6d641ea.png)
![2](https://user-images.githubusercontent.com/6768243/56976584-e4a6fb80-6b38-11e9-9fa8-5d6df80ba83d.png)

**Comment by mer2329** [comment]
im not sure if it matters i used the ubuntu PPA to install keepassxc

**Comment by droidmonkey** [comment]
This is a theme issue. Do you have qt5ct installed?

**Comment by mer2329** [comment]
yes 
from apt-get when trying to install it
`qt5ct` is already the newest version (0.34-1build2).

> This is a theme issue
i know but i dont know how to set tags and bug was applied by default.

**Comment by mer2329** [comment]
i ran the tool and it shows the following
![1](https://user-images.githubusercontent.com/6768243/56981312-33a65e00-6b44-11e9-875b-f696057047bb.png)
![2](https://user-images.githubusercontent.com/6768243/56981313-33a65e00-6b44-11e9-965f-d8653a3d5d5c.png)
![3](https://user-images.githubusercontent.com/6768243/56981315-33a65e00-6b44-11e9-8097-2ca51396a9b4.png)
![4](https://user-images.githubusercontent.com/6768243/56981316-343ef480-6b44-11e9-8b98-31acd4ec7d53.png)
![5](https://user-images.githubusercontent.com/6768243/56981317-343ef480-6b44-11e9-9a87-744f195e5b20.png)

**Comment by mer2329** [comment]
ok this is a issue with the default qt theme [not bug] or theme issue

**Comment by droidmonkey** [comment]
Try running KeePassXC in the terminal with:

```QT_QPA_PLATFORM_THEME=qt5ct keepassxc```

**Comment by mer2329** [comment]
no still is greyed out

first i closed keepass xc (im just gonna call it keepass from now on)
then ran the command
heres its output.
`qt5ct: using qt5ct plugin
qt5ct: D-Bus global menu: no
qt5ct: D-Bus system tray: no
QObject::startTimer: Timers cannot have negative intervals
`
keepass started and looks the same (GTK2 was already set as the theme)

**Comment by droidmonkey** [comment]
We don't specify the background color of the text entry fields. There must be a theme being applied. Try playing around with the qt5ct settings to get the themes to be reset.
