### ISSUE TITLE
Application crashes when attempting to copy

### ISSUE THREAD

**Issue by balaji-marist** [keepassxreboot/keepassxc#3103]
Application crashes when attempting to copy any data

I am expecting it to copy the content to the clipboard

Unhandled exception causing the application to crash

![image](https://user-images.githubusercontent.com/46973150/56984060-29d82700-6b53-11e9-863d-713fc2e14b6b.png)

Log in to the app and copy any content

KeePassXC - 2.4.1
Revision: 7bafe65

Libraries:
libgcrypt 1.8.4

Operating system: Windows 7 SP 1
CPU architecture: x86_64
Kernel: winnt 6.1.7601

Enabled extensions:
Auto-type
Browser-Integration
SSH Agent
KeeShare
YubiKey

**Comment by droidmonkey** [comment]
This does not occur on Windows 10.

**Comment by balaji-marist** [comment]
I do not have any special software for clipboard management.

**Comment by StellarStorm** [comment]
I get this same error (on Windows 7) for the 64-bit builds but not the 32-bit builds. No clipboard software installed either.

KeePassXC - Version 2.4.2
Revision: a775031

Qt 5.12.3
Debugging mode is disabled.

Operating system: Windows 7 SP 1 (6.1)
CPU architecture: x86_64
Kernel: winnt 6.1.7601

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.4

**Comment by droidmonkey** [comment]
Fixing this will require someone to run a debug build on Windows 7. I suspect there is an incompatibility between Windows 7 and Qt 5.12.
