### ISSUE TITLE
Application crashes immediately

### ISSUE THREAD

**Issue by Noammac** [keepassxreboot/keepassxc#3104]
## Expected Behavior
When running the `keepassxc` command or pressing on any of the KeePassXC icons, it is expected that the application will launch.

## Current Behavior
The application crashes immediately, with a segfault and the message: 
```
Cannot mix incompatible Qt library (version 0x50c02) with this library (version 0x50c03)
```

I have also checked the system log and found this:
```
Process 1235 (keepassxc) of user 1000 dumped core.

Stack trace of thread 1235:
#0  0x00007f92e6a8e82f raise (libc.so.6)
#1  0x00007f92e6a79672 abort (libc.so.6)
#2  0x00007f92e6f767fc _ZNK14QMessageLogger5fatalEPKcz (libQt5Core.so.5)
#3  0x00007f92e6f8a3d6 n/a (libQt5Core.so.5)
#4  0x00007f92e17b7f3f n/a (libqgtk2style.so)
#5  0x00007f92e17a65f0 n/a (libqgtk2style.so)
#6  0x00007f92e17bab00 n/a (libqgtk2style.so)
#7  0x00007f92e7d933dd _ZN13QStyleFactory6createERK7QString (libQt5Widgets.so.5)
#8  0x00007f92e7dbab7d _ZN11QProxyStyleC2ERK7QString (libQt5Widgets.so.5)
#9  0x00007f92e17cab77 _ZN15Qt5CTProxyStyleC1ERK7QString (libqt5ct-style.so)
#10 0x00007f92e17ca7da _ZN16Qt5CTStylePlugin6createERK7QString (libqt5ct-style.so)
#11 0x00007f92e7d933dd _ZN13QStyleFactory6createERK7QString (libQt5Widgets.so.5)
#12 0x00007f92e7d265bc _ZN12QApplication5styleEv (libQt5Widgets.so.5)
#13 0x00007f92e7d26906 _ZN19QApplicationPrivate10initializeEv (libQt5Widgets.so.5)
#14 0x00007f92e7d2696b _ZN19QApplicationPrivate4initEv (libQt5Widgets.so.5)
#15 0x000055c9e4130bc6 n/a (keepassxc)
#16 0x000055c9e411b087 n/a (keepassxc)
#17 0x00007f92e6a7ace3 __libc_start_main (libc.so.6)
#18 0x000055c9e411d8fe _start (keepassxc)

Stack trace of thread 1272:
#0  0x00007f92e6b470d1 __poll (libc.so.6)
#1  0x00007f92e3a90630 n/a (libxcb.so.1)
#2  0x00007f92e3a922db xcb_wait_for_event (libxcb.so.1)
#3  0x00007f92e3610b69 n/a (libQt5XcbQpa.so.5)
#4  0x00007f92e6fb063c n/a (libQt5Core.so.5)
#5  0x00007f92e6a3da92 start_thread (libpthread.so.0)
#6  0x00007f92e6b51cd3 __clone (libc.so.6)

```

## Steps to Reproduce
1. Install KeePassXC using `pacman` on an Arch system
2. Attempt to launch KeePassXC

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.4.1
Revision: 7bafe65

Libraries:
-  libgcrypt 1.8.4

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 5.0.10-arch1-1-ARCH

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

**Comment by joshirio** [comment]
Looks like a distro upstream issue, they probably updated the Qt packages without rebuilding keepassxc, not the first time this happened.

**Comment by telans** [comment]
I'm currently experience this, but I'm building keepassxc. Should it not be building against the library I have? `0x50e00` vs `0x50e01`

**Comment by andpol** [comment]
For future readers, I had a similar problem today:
```
 Cannot mix incompatible Qt library (5.15.0) with this library (5.15.1)
```

The cause in my case was that I had set `QT_STYLE_OVERRIDE=gtk2`. Removing it (and using `QT_QPA_PLATFORMTHEME=gtk2` instead) fixed the problem.

**Comment by micw** [comment]
For me (on archlinux), the cause was that aur/qt5-styleplugins 5.0.0.20170311-23 was installed which was probably build/linked against the old qt library and was not auto-updated.

**Comment by elisdg** [comment]
> For me (on archlinux), the cause was that aur/qt5-styleplugins 5.0.0.20170311-23 was installed which was probably build/linked against the old qt library and was not auto-updated.

Just noting for future searchers: this also solved the problem after the last update 
_"Cannot mix incompatible Qt library (5.15.7) with this library (5.15.8)"_

after removing `qt5-styleplugins` keepassxc started again _(just for testing: after reinstalling `qt5-styleplugins 5.0.0.20170311-35` kepassxc still started successfully)_
