### ISSUE TITLE
how to use keeshare

### ISSUE THREAD

**Issue by userosos** [keepassxreboot/keepassxc#3106]
How To use it? I generate key and other next i export a file.key.share from PC after it i import the file an laptop and what next? If you will do help for it - will be good!

**Comment by IpsmLorem** [comment]
Just import on your laptop the file.key.share and your entries will be synced.

**Comment by userosos** [comment]
> 
> 
> Just import on your laptop the file.key.share and your entries will be synced.

Ok! I think that it work use network. Can you add sync use LAN?

**Comment by IpsmLorem** [comment]
Use whatever means ncessary to tranport the file. Keeshare doesn't provide the file trasnfert.
