### ISSUE TITLE
locked database: after relogin not find any match entry

### ISSUE THREAD

**Issue by gregormueller1** [keepassxreboot/keepassxc#3109]
## Expected Behavior
when the database is locked and I try to use the autotype-feature. 
first I ned login again into the database. the login-dialog is open.
then the lookup for the matching entry will started. the correct entry is found and the auto type will start

## Current Behavior
the login window comes. I type in my password. After this an info-message cocoas, which said, there is no matching entry in the database.
when I go back to my application-login-screen and press the shortcut-key for autotype, now the matching entry will be found and the autotoype works fine.
this info message only comes, after the database was locked, it works fine with an unlocked database

## Steps to Reproduce
1. open keepassxc
2. wait until database is locked
3. go to applications login screen
4. press shortcut for autotype
5. in the login window of keepassxc type your password
6. error screen will show 

Operating system: MACOS and linux
CPU architecture: x64

**Comment by droidmonkey** [comment]
This was fixed by #3138 and will be released with 2.4.2
