### ISSUE TITLE
v2.41 "Agent connection failed" with Pageant v0.71

### ISSUE THREAD

**Issue by mircsicz** [keepassxreboot/keepassxc#3110]
When opening my Database the expected Behaviour would be to load my keys into Pageant.

Instead i get a "Agent connection failed" Error in the red Bar on top of the KeepassXC Window.

KeePassXC - Version 2.4.1
Revision: 7bafe65

Qt 5.12.2
Debugging mode is disabled.

Operating system: Windows 10 (10.0)
CPU architecture: x86_64
Kernel: winnt 10.0.17763

Enabled extensions:
- Auto-Type
- Browser-Integration
- SSH-Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.4

**Comment by mircsicz** [comment]
@droidmonkey Tried to debug with your [precompiled bin](https://drive.google.com/open?id=1VEvRIqmmgcZLzLsufSum8eqDrl0vsOa8) from [2751](https://github.com/keepassxreboot/keepassxc/issues/2751) but that is 0.70 and even if I run it in an Admin-Shell doesn't give me any output...

**Comment by droidmonkey** [comment]
So pageant updated and now KeePassXC does not connect?

**Comment by mircsicz** [comment]
Not so sure if it's about the Pageant Update, cause if I use your 0.70(DEBUG) it refuses to connect too...

**Comment by mircsicz** [comment]
My 2.41 was installed through Chocolatey, just tried the portable from the [Homepage](https://keepassxc.org/download/) tried adding a key to your 0.70 DEBUG Pageant and got "Agent-Protocollerror"

**Comment by mircsicz** [comment]
Don't know WTF happened but after another try all seems to be fine again... Don't have to get it on damn Windows, even a reboot didn't help before I posted! :-(

**Comment by droidmonkey** [comment]
Haha, no problems glad its working
