### ISSUE TITLE
KeePassXC-Browser in firefox deaktiviert

### ISSUE THREAD

**Issue by ernie222** [keepassxreboot/keepassxc#3116]
Am 04.05.2019 wurde KPXC-Browser (1.4.3) von Firefox 66.0.3 (Ubuntu 18.04) als "konnte nicht verifiziert werden" deaktiviert. Es gab bei verschiedenen Sites seit einigen Tagen bereits Probleme, die Einträge in der Datenbank zu finden.

**Comment by amadeous** [comment]
Their docs recommend to ask add-on maintainers to sign their extension.

Could you please consider it ? Thanks a lot for your marvelous add-on !
https://support.mozilla.org/en-US/kb/add-on-signing-in-firefox

**Comment by droidmonkey** [comment]
Mozilla made a global error today, they already released a fix.

**Comment by amadeous** [comment]
Alright. Sorry and thank you for the information !
