### ISSUE TITLE
Minimize after unlocking database (as separate option)

### ISSUE THREAD

**Issue by n-st** [keepassxreboot/keepassxc#3118]
[TIP]:  # ( Provide a general summary of the feature in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Summary
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
Previously, the "Minimize Window at Application Startup" option allowed/required the user to unlock the database before minimizing the window. This (understandably) annoyed users who wanted the exact behaviour described by the option ("minimize on startup"), but was a useful feature for others (see use case below). (see #105, #155, #1147)
The behaviour was changed in 19a960856c79cca02036c85e5c7147924ca75da8. So far it seems there was only discussion about *reverting* the behaviour of *this* option.
I would like to suggest adding a separate option, which would allow us to accommodate both user groups.

## Desired Behavior
[NOTE]: # ( Tell us how the new feature should work, be specific )
When "minimize after unlocking" is enabled, launch KeePassXC with its window visible, allow the user to unlock the database, then minimise to systray.

## Possible Solution
[NOTE]: # ( Not required, but suggest ideas on how to implement the addition or change )
The code for this already existed until it was removed in 19a960856c79cca02036c85e5c7147924ca75da8, so it could probably be adapted to work with the current codebase.

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
I primarily use KeePassXC through the KeePassXC-Browser extension.
When the database is locked, the browser extension becomes completely non-functional; it does not seem to be able to open an unlock window.
My usual workflow is to launch KeePassXC, unlock the database, minimise it (which I currently have to do manually), then launch my browser. The "minimize after unlock" option would remove that extra step, which would be a very useful feature.

**Comment by droidmonkey** [comment]
As a temporary work around you can use the minimize keyboard shortcuts:

Ctrl+M = Minimize window
Ctrl+Shift+M = Minimize to tray (if enabled)
