### ISSUE TITLE
Tray icon disappears after suspend

### ISSUE THREAD

**Issue by zetheroo** [keepassxreboot/keepassxc#3120]
## Expected Behavior
After waking from suspend the tray icon should still be there.

## Current Behavior
After waking from suspend the tray icon is gone - even though keepassxc is still running.

## Steps to Reproduce
1. With KeePassXC running in the tray icon put laptop into suspend
2. Wake from suspend
3. KeePassXC tray icon no longer there

# Debug Info
KeePassXC - Version 2.4.1
Revision: 7bafe65

Qt 5.9.5
Debugging mode is disabled.

Operating system: Ubuntu 18.04.2 LTS
CPU architecture: x86_64
Kernel: linux 4.15.0-47-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (only unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.1

**Comment by droidmonkey** [comment]
What desktop environment are you running? This is likely the fault of the environment, not KeePassXC.

**Comment by zetheroo** [comment]
Desktop environment is the default for Ubuntu 18.04 ... Gnome

**Comment by jtl5770** [comment]
I wouldn't put the blame so fast on gnome :-) 
I use Fedora 30 with the top icons extension (to get tray icons functionality) and I see the same behavior, but my dropbox tray icon remains to be displayed, only keepassxc icon disappears.

**Comment by droidmonkey** [comment]
The blame belongs to the desktop env, and in your case the extension, because they are not properly restoring state after resume. We use the standard Qt methods for tray icon, nothing fancy at all. It is likely Dropbox is working around the failure of the desktop envs by continually re-adding the tray icon. It shouldn't be that way.

**Comment by jtl5770** [comment]
You may very well be right - unfortunately I don't know how to fix that
behaviour... or even further test if your theory is correct. In that
case I am really just a simple user :-)

**Comment by adatum** [comment]
I have the same issue on Fedora 30 with Gnome Shell. Actually it happens with icons after the screen is locked. Since sleep also involves locking the screen, it happens in this case too.

Note that only some icons are affected. Unaffected icons include: dropbox, pidgin, dnfdragora.

I don't know whether the issue lies with individual programs, the TopIcon Plus Gnome extension, or Gnome Shell itself.

**Comment by hho** [comment]
KeePassXC 2.4.3 5d6ef0c, Ubuntu 18.04.2 (Gnome Shell + Ubuntu Appindicators extension), same issue.

Keybase works, Dropbox works, KeePassXC doesn't :cry:

**Comment by Mq89** [comment]
I have the issue with Lubuntu 16.04 LTS and Lxpanel 0.8.2.
After locking and unlocking the screen, the tray icon is gone.
Disabling it in application settings and applying the settings and then re-enabling it restores the tray icon.
Keepassxc 2.5.0

**Comment by Mq89** [comment]
I link this issue as I think it contains helpful information to track down the problem:
https://github.com/ubuntu/gnome-shell-extension-appindicator/issues/75

**Comment by droidmonkey** [comment]
I'm closing this as it's pretty clearly not a KeePassXC issue.

**Comment by hho** [comment]
That's very disappointing.

If Dropbox, Keybase, Remmina and many others work fine and KeePassXC doesn't, then it _does_ seem to be a KeePassXC issue – no matter if KeePassXC is actually at fault or if it's just missing a workaround for someone else's fault.

**Comment by droidmonkey** [comment]
Are those other apps you mentioned using Qt? Please read through the issue thread posted above.

**Comment by rob151515** [comment]
Not if this little observation is relevant or not but I have noticed that if you have not unlocked your vault then the icon remains even after waking from suspend. As soon as you unlock your vault and suspend the icon disappears the next time the machine woken.Seems odd that the behaviour is different depending on if the vault is locked or not?
