### ISSUE TITLE
KeePassXC-Browser "Key exchange was not successful."

### ISSUE THREAD

**Issue by d2uriel** [keepassxreboot/keepassxc#3121]
Hey there,

I've been using KeePass portable v2.3.4 and it was working fine until I decided to follow the upgrade recommendation that KeePassXC-Browser plugin was showing. I upgraded to KeePassXC v2.4.1. Now, when I click on the addon icon it shows a message:

`Cannot connect to KeePassXC. Check that browser integration is enabled in KeePassXC settings.`

After clicking the Reload button twice a different message pops up:

`Key exchange was not successful.`

I'm unable to use KeePassXC-Browser now because of that.

## Expected Behavior
KeePassXC-Browser should connect to KeePassXC.

## Current Behavior
I get these two messages from KeePassXC-Browser:
`Cannot connect to KeePassXC. Check that browser integration is enabled in KeePassXC settings.`

`Key exchange was not successful.`

## Possible Solution
No idea.

## Steps to Reproduce
I don't have a second computer to try it out. What I have already tried so far is:
1. Downgraded to KeePassXC v2.3.4 (removed to whole KeePassXC folder and extracted the portable version from the original archive) - same problem.
2. Created a new DB - same problem. I'm using a password protected DB, not a key file.
3. Uninstalled Firefox and installed it again (fresh addon installation, etc.) - same problem.
4. Tried KeePassXC-2.5.0-snapshot - same problem.

Firefox v66.0.4 (64-bit)

## Debug Info
```
KeePassXC - Version 2.4.1
Revision: 7bafe65

Qt 5.12.2
Debugging mode is disabled.

Operating system: Windows 10 (10.0)
CPU architecture: x86_64
Kernel: winnt 10.0.17134

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.4
```
Thank you in advance for any suggestions that might help solve the problem.

Daniel.
![ff_version](https://user-images.githubusercontent.com/1568637/57224076-82eb0380-7008-11e9-9d1c-0a1bafeda7c6.png)
![browser_ext_error](https://user-images.githubusercontent.com/1568637/57224079-85e5f400-7008-11e9-84da-f687acf1d88f.png)
[debug_info_v2.4.1.txt](https://github.com/keepassxreboot/keepassxc/files/3147816/debug_info_v2.4.1.txt)
[debug_info_v2.5.txt](https://github.com/keepassxreboot/keepassxc/files/3147817/debug_info_v2.5.txt)

**Comment by d2uriel** [comment]
Problem solved. I renamed to folder... and there registry key 

`HKEY_CURRENT_USER\\Software\\Mozilla\\NativeMessagingHosts\\`

pointed to a wrong path. Sorry for trouble and thanks to varjolintu for pointing me to Troubleshooting Guide (missed it somehow).

**Comment by Berulon** [comment]
hi there
for my the exact same problem but
HKEY_CURRENT_USER\\Software\\Mozilla\\NativeMessagingHosts\\
there was no entry for KeePassXC
