### ISSUE TITLE
keepassxc-proxy.exe

### ISSUE THREAD

**Issue by mufaho** [keepassxreboot/keepassxc#3122]
https://github.com/keepassxreboot/keepassxc/issues/1765
now this is for firefox 66.0.4 and esr 60.6.2 clean install.
dont check other versions since its support only from 55
sometimes when i click connect to database button in addon in task manager created cmd and .exe process and not get connected to database.
you can reproduce it by connecting to database, login it to some site and exit keepass database w/o disable extension. addon can start creating processes on its own.

**Comment by varjolintu** [comment]
Disable auto-reconnect from extension settings to get rid of this. We need to fix the proxy.

**Comment by varjolintu** [comment]
A possible fix for this: https://github.com/keepassxreboot/keepassxc-browser/pull/529
