### ISSUE TITLE
Unable to connect to Vivaldi browser on Windows if browser is opened first

### ISSUE THREAD

**Issue by TraceyC77** [keepassxreboot/keepassxc#3124]
## Expected Behavior
After opening Vivaldi and then KeePassXC and authenticating:
- The KeePassXC icon in Vivaldi shows the icon to connect to the database
- After clicking the icon, the database is connected and the "Redetect Login Fields" button is available, which allows field filling

## Current Behavior
- The KeePassXC icon in Vivaldi shows the icon to connect to the database
- The extension then shows the error "Cannot decrypt message" and the "Reopen Database" button. Clicking that button does nothing.

## Workaround
Close Vivaldi and re-open

## Steps to Reproduce
1. Start Windows 10, open Vivaldi
2. Navigate to a page requiring a login (like github.com)
3. Open the KeePassXC database and authenticate
4. Click on the KeePassXC extension button in Vivaldi

## Context
- This issue does not affect Vivaldi and KeePassXC on KDE Neon (based on Ubuntu 18.04)
KeePassXC 2.4.1 (up to date). In that case, the extension button works immediately.
- After opening an Incognito window (KeePassXC is the only extension enabled in Incognito), the extension icon turned green. After a few moments, it did show it was connected to the database and showed the "Redetect login fields" button. It was then able to fill in credentials normally.

## Debug Info
KeePassXC - Version 2.4.1
Revision: 7bafe65

Qt 5.12.2
Debugging mode is disabled.

Operating system: Windows 10 (10.0)
CPU architecture: x86_64
Kernel: winnt 10.0.17763

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.4

**Comment by SmoochiesBoss** [comment]
Same here with Firefox, in regular--not private--mode. Even happens sometimes if the browser is open after KeyPassXC.

**Comment by kgraefe** [comment]
I have the same in Chrome and Win10. More often than not KeePassXC must also be restarted.

**Comment by droidmonkey** [comment]
This problem was fixed with an update to the browser extension.
