### ISSUE TITLE
Do not grab focus when starting, let WM do it

### ISSUE THREAD

**Issue by Thermi** [keepassxreboot/keepassxc#3125]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Expected Behavior
keepassxc starts, does not grab focus by itself; Behaves like any other application is supposed to. Focus grabbing is configured solely by the WM or is configurable in the application's settings

## Current Behavior
keepassxc grabs the focus when it starts

## Possible Solution
Do not grab the focus.

## Steps to Reproduce
1. Make sure your WM Is configured to not automatically set the focus to new windows
2. start keepassxc
3. watch it get the focus

## Context
Grabbing the focus when keepassxc starts causes unintended inputs to be given to the keepassxc window. That happens when one is typing while keepassxc is starting in the background.

## Debug Info
KeePassXC - Version 2.4.1
Revision: 7bafe65

Qt 5.12.3
Debugging mode is disabled.

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 5.0.13-zen1-1-zen

Enabled extensions:
- Auto-Type
- Browser-Integration
- SSH-Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.4

**Comment by phoerious** [comment]
We do not grab focus. What we do is to activate an existing window if you try to start another instance, which can happen if KeePassXC is both in your autostart and started as part of your desktop environment's session restore.

**Comment by Thermi** [comment]
I just tested it and it behaves as I described.

**Comment by droidmonkey** [comment]
If you want to disable this simply enable the minimize on startup setting.
