### ISSUE TITLE
Suggest frequently used usernames when creating an entry

### ISSUE THREAD

**Issue by jbtrystram** [keepassxreboot/keepassxc#3126]
## Summary
Most people will use a few different usernames for all their accounts. Most of the time the username is an email. The value for username i'm going to use when creating a new entry is very likely to already exist in the database. Typing my e-mail address in there is cumbersome imo.
It would be nice to suggest values in the username field when creating / editing an entry.

## Desired Behavior
when creating an entry, maybe have a drop down selection menu attached to the username field so I can select a username that already exist in the database.

## Possible Solution
Maybe split the field in half ? The right hand side of the field could display suggestions

**Comment by droidmonkey** [comment]
Oh i like the idea of a dynamic drop down of "most used" usernames. For now, you can go to the database settings and set a default username there.

**Comment by zachtib** [comment]
A similar feature I'd like to see is setting a default username per-folder. For example, I have a work folder where I want to use my work email as the default username when creating new entries in it.
