### ISSUE TITLE
Database doesn´t shrink after removing attachments

### ISSUE THREAD

**Issue by AnanasPfirsichSaft** [keepassxreboot/keepassxc#3128]
The database doesn´t shrink after removing attachments. I had stored several larger files as attachments resulting in a total database size of about 1.2 megabytes. They have become useless so I removed them. After saving the database the size remains and hadn´t been compacted. It should have been around a few dozens of kilobytes.

## Expected Behavior
Unlinked data(blocks) should result in reduced filesize.

## Current Behavior
The filesize remains large.

## Possible Solution
I could export the data in CSV and reimport them. But I heavily use my own symbols and extended attributes which weren´t exported when I tested it. It would be quite a bunch of work to write them down and rebuild the database by hand.

I also tried to merge my current database with an empty new one. My hope was that keepassxc would detect the deleted attachments as unused space. But this also results in a large filesize.

## Steps to Reproduce
As explained.

## Context
Well, it may be important to say that I have used **keepassx** for a long time and the database has been around for years. It was affected by several format changes and I started using it in keepassxc a few months ago.

## Debug Info
KeePassXC - Version 2.4.0
Revision: c51752d
Distribution: AppImage

Libraries:
- Qt 5.10.1
- libgcrypt 1.8.1

Operating system: KDE neon User Edition 5.15
CPU architecture: x86_64
Kernel: linux 4.19.36-114a4e

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (only unsigned sharing)
- YubiKey

**Comment by droidmonkey** [comment]
This is because they are still stored in the history of the entry. If you are concerned with database size you can limit the history size in the database settings.

**Comment by phoerious** [comment]
If it's just that one entry, you can simply clear its history individually.
