### ISSUE TITLE
"Key exchange was not successful" (Chrome+Firefox+Solus Fortitude)

### ISSUE THREAD

**Issue by CryptoTropico** [keepassxreboot/keepassxc#3133]
Running KeepassXC + Google Chrome + Firefox on SolusOS Budgie

## Expected Behavior
KeePassXC-Browser should connect to KeePassXC.

## Current Behavior
I can't seem to make the browser extension/addon to work on both **chrome** and **firefox**.

Clicking the reload button on the extension shows this message:

> "Cannot connect to KeePassXC. Check that browser integration is enabled in KeePassXC settings."

After clicking reload about two times, the message changes to:

> "Key exchange was not successful."

I followed the troubleshooting guide, and everything seems to check.

1) Browser integration is enabled in KeepassXC
2) Chrome and Firefox are checked
3) keeypass-proxy is running, and also seems to be launching when I open a new chrome/firefox instance. Don't know if this is relevant but sometimes there are several keepassxc-proxy processes runing. Tried killing a few, leaving just one, but that doesn't help.
4) The json files for both Chrome and Firefox exist in their corresponding folders and point to the correct path to the proxy.
5) Tried debugging with developer tools. The output is incomprehensible to me.

**Heres the console output:**

```
keepass.js:1003 Connecting to native messaging host org.keepassxc.keepassxc_browser
keepass.js:1158 Objectdisconnect: ƒ disconnect()name: (...)onDisconnect: (...)onMessage: (...)postMessage: ƒ postMessage()sender: (...)get name: ƒ ()get onDisconnect: ƒ ()get onMessage: ƒ ()get sender: ƒ ()__proto__: Object
keepass.js:1088 Error 9: Key exchange was not successful.
```

**Here's the content of the json file for chrome:**

```
{
    "allowed_origins": [
        "chrome-extension://iopaggbpplllidnfmcghoonnokmjoicf/",
        "chrome-extension://oboonakemofpalcgghocfoadofidjkkk/"
    ],
    "description": "KeePassXC integration with native messaging support",
    "name": "org.keepassxc.keepassxc_browser",
    "path": "/usr/bin/keepassxc-proxy",
    "type": "stdio"
}

```
Worth mentioning, if I open KeePassXC app I am able to connect and open the database and the extension seems to function normally.

Also, I tried changing the path to **keepassxc** instead of **keepassxc-proxy** and it opens the KeePassXC app when launching **chrome**. So, this indicates to me the json file is being read and thus located/accesible to the extension.

UPDATE: Tried rebooting the system. Still nothing.

## Debug Info
```
KeePassXC - Version 2.4.1
Revision: 7bafe65

Qt 5.12.2
Debugging mode is disabled.

Operating system: Solus 4.0 Fortitude
CPU architecture: x86_64
Kernel: linux 5.0.7-114.current

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.4

```

**Comment by CryptoTropico** [comment]
Ok, so I booted my windows machine, installed keepass, loaded the database, enabled browser integration... check chrome, firefox, etc... installed the chrome extension and seems like it works with KeePassXC app open. But, right after I close KeePassXC I am having exactly the same issue.

Close all windows, re-open chrome, keepassxc extension icon shows a red x, click/reload same messages, just like in SolusOS:

> Cannot connect to KeePassXC. Check that browser integration is enabled in KeePassXC settings.

> Key exchange was not successful.

Followed the troubleshooting guide for windows, and everything seems to check.

**Could I be doing something horribly wrong? missing a step to configure properly perhaps?**

**Comment by droidmonkey** [comment]
Wait what? You need to have KeePassXC running to use the browser extension...

**Comment by CryptoTropico** [comment]
Wait... wait... I need to have KeePassXC open, with the database open for the extension to work???

Doesn't that defeat the purpose of letting anyone in my office to just open KeePassXC and see all of my passwords?

I might be completely wrong and clueless. Excuse me if I understood wrong.

**Comment by droidmonkey** [comment]
You lock your database when you are not using it. That prevents anyone from getting access to ut

**Comment by CryptoTropico** [comment]
LOL, then I am the one to blame for all. I definitely got this all wrong. If that's how the software is expected to work, then it is working perfectly!

I thought you could just "set and forget" and never have to deal with the KeePassKC app itself unless you wanted to manage the database.

Is there an instruction that points this out? I didn't see this being written in the FAQ?

Maybe it is obvious for you, but I would have never thought that was how it is supposed to work lol

**Comment by droidmonkey** [comment]
We have a beginner user guide that will be published soon that clears up all these things. Sorry for the confusion!

**Comment by Mayurifag** [comment]
For any people using librewolf on linux, this dirty hotfix may help you

```sh
ln -s ~/.mozilla/native-messaging-hosts ~/.librewolf/native-messaging-hosts
```

source: https://github.com/keepassxreboot/keepassxc/issues/6907
