### ISSUE TITLE
Authentication: flexible options

### ISSUE THREAD

**Issue by SloCompTech** [keepassxreboot/keepassxc#3135]
## Summary
Hi,
first of all, thanks to all involved in this project. I regularly use kepassxc on day to day basis, but every time I need to access my passwords I need to enter both password and touch my YubiKey, would it be possible to add checkbox or something, so I would be able to use my password or YubiKey ?

## Desired Behavior
When authenticating use password OR/AND YubiKey

## Possible Solution
- Add checkbox in the master key menu
- I don't know how encryption is implemented under the hood, but in case when using both password and YubiKey that are both used for decrypting database, then you would always need both of them, so there are few ideas that came to me:
    + Generate key, encrypt it twice, 1 version encrypted with password, other with YubiKey, than you just decrypt that key than decrypt data
   + First time after boot use password & YubiKey, later require only press on YubiKey (add option via checkbox)

## Context
This feature would improve user experience. I value my privacy and I use really long password for security, but I don't like to enter it every time when database is locked in single workday, when I'm always around my computer.

Thanks

**Comment by droidmonkey** [comment]
We cannot do an either/or, but we could support using the Yubikey to setup a quick unlock feature. Its not a bad idea actually!

**Comment by SloCompTech** [comment]
Yes, that's what I would appreciate having
