### ISSUE TITLE
keepassxc-cli without gui dependencies

### ISSUE THREAD

**Issue by Sec42** [keepassxreboot/keepassxc#3136]
[TIP]:  # ( Provide a general summary of the feature in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Summary
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
I want to be able to query passwords on my server (e.g. via an ssh session) -
I can't install keepassxc-cli without having to install dependencies on GUI toolkits like QT5

## Desired Behavior
[NOTE]: # ( Tell us how the new feature should work, be specific )
Able to build / run keepassxc-cli without Qt5

## Possible Solution
[NOTE]: # ( Not required, but suggest ideas on how to implement the addition or change )

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )

**Comment by droidmonkey** [comment]
Qt is not just a gui toolkit. It is a C++ framework, that includes way more than just GUI elements. This project uses qt5, you must install it. I believe there is a kdbx python project out there, but YMMV.
