### ISSUE TITLE
Use of keyboard shortcut for context menu fails to show context menu

### ISSUE THREAD

**Issue by affinityv** [keepassxreboot/keepassxc#3140]
Mouse can right-click on an entry to get the context menu, but the normal keyboard method of bringing up the context menu doesn't work.  This is "`<ctrl><f10>`" .... it works with other applications.

## Expected Behavior
Use keyboard shortcut should show context menu.

## Current Behavior
No menu is shown using keyboard shortcut (mouse is okay).

## Steps to Reproduce
Select an entry, via keyboard or mouse, it doesn't matter.
Use "`<ctrl><f10>`" -- no menu

## Context
Probably not relevant, but this is on a MacbookPro11,3 -- have to use FN key as well as `<ctrl><f10>`.
(running Linux, not MacOS as per the debug info)

## Debug Info
KeePassXC - Version 2.4.1
Revision: 7bafe65
Distribution: AppImage

Qt 5.10.1
Debugging mode is disabled.

Operating system: Devuan GNU/Linux ascii
CPU architecture: x86_64
Kernel: linux 4.9.0-6-amd64

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (only unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.1

**Comment by affinityv** [comment]
No updates on this?  I thought it would have been fixed for 2.4.2, but it is still the same.

**Comment by affinityv** [comment]
New debug info:

KeePassXC - Version 2.4.2
Revision: a775031
Distribution: AppImage

Qt 5.10.1
Debugging mode is disabled.

Operating system: Devuan GNU/Linux ascii
CPU architecture: x86_64
Kernel: linux 4.9.0-6-amd64

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (only unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.1

**Comment by droidmonkey** [comment]
This was not marked for 2.4.2? I have implemented this in an upcoming PR for accessibility. It's aimed at 2.5.0.

**Comment by affinityv** [comment]
Okay, so is 2.5.0 going to be after 2.4.3 or further down the track?

**Comment by droidmonkey** [comment]
2.5.0 is coming out next. Probably in 1 month.

**Comment by affinityv** [comment]
Great, thanks.
