### ISSUE TITLE
New entry is lost when canceling and then saving

### ISSUE THREAD

**Issue by jf4923** [keepassxreboot/keepassxc#3141]
## Expected Behavior
After creating a new entry and adding data you can press the escape key or cancel button to trigger the 'Entry has unsaved changes' dialog. Clicking 'Save' should close the dialog and add a new item to the tree.

## Current Behavior
Clicking 'Save' does the same thing as 'Discard' - it closes the new entry and drops the new data. 

**The entered data are lost!**

## Possible Solution
Not pressing 'Save'! Pressing 'Cancel' lets you at least return to the new entry and continue.

This seems related to the closed issue #1133 (apply key was removed as solution apparently...). Maybe you should remove the 'Save' button as well if you can't fix this.

## Steps to Reproduce
1. Click 'Add a new entry'
2. Enter at least one character as title
3. Hit 'Escape' key or click 'Cancel' at the bottom right
4. Click 'Save' on the dialog
5. Look for the new entry - it's not there

## Context
I wanted to save without using the mouse and thought that 'Escape' is a nice trigger.

## Debug Info
KeePassXC - Version 2.4.1
Revision: 7bafe65

Qt 5.9.5
Debugging mode is disabled.

Operating system: Ubuntu 18.04.2 LTS
CPU architecture: x86_64
Kernel: linux 4.15.0-48-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (only unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.1

**Comment by droidmonkey** [comment]
I thought I fixed this problem. Sorry for the data loss. For future reference, pressing Ctrl+Enter is the same as pressing OK.

**Comment by droidmonkey** [comment]
confirmed this is a big problem

**Comment by jf4923** [comment]
Thanks, works! :)
