### ISSUE TITLE
2.4.1 crash

### ISSUE THREAD

**Issue by sashka4** [keepassxreboot/keepassxc#3144]
Immediately upon launch

Process:               KeePassXC [2540]
Path:                  /Applications/KeePassXC 2.app/Contents/MacOS/KeePassXC
Identifier:            org.keepassx.keepassxc
Version:               ???
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           KeePassXC [2540]
User ID:               501

Date/Time:             2019-05-13 09:32:58.163 -0700
OS Version:            Mac OS X 10.11.6 (15G22010)
Report Version:        11
Anonymous UUID:        B573C07D-D3B3-BC6A-D01C-F77708CB4A75

Time Awake Since Boot: 610 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (Code Signature Invalid)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

kernel messages:

VM Regions Near 0x7fff7d5750a8 (cr2):
    __LINKEDIT             00007fff61864000-00007fff61879000 [   84K] r--/rwx SM=COW  /usr/lib/dyld
--> Submap                 00007fff70000000-00007fff80000000 [256.0M] r--/rwx SM=PRV  process-only VM submap
    unused shlib __DATA    00007fff7a415000-00007fff7e9b8000 [ 69.6M] rw-/rw- SM=COW  system shared lib __DATA not used by this process

Thread 0 Crashed:
0   dyld                          	0x00007fff617f1000 _dyld_start + 0

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x000000000000000d  rbx: 0x0000000000000000  rcx: 0x0000000000000000  rdx: 0x0000000000000000
  rdi: 0x0000000000000000  rsi: 0x0000000000000000  rbp: 0x0000000000000000  rsp: 0x00007fff5c930c48
   r8: 0x0000000000000000   r9: 0x0000000000000000  r10: 0x0000000000000000  r11: 0x0000000000000000
  r12: 0x0000000000000000  r13: 0x0000000000000000  r14: 0x0000000000000000  r15: 0x0000000000000000
  rip: 0x00007fff617f1000  rfl: 0x0000000000000201  cr2: 0x00007fff7d5750a8
  
Logical CPU:     0
Error Code:      0x020000f4
Trap Number:     133

Binary Images:
    0x7fff617f0000 -     0x7fff61827a47  dyld (???) <6B9CD3BA-2D60-3629-A0CB-AB810F55E8DD> /usr/lib/dyld

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 2998
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=308K resident=0K(0%) swapped_out_or_unallocated=308K(100%)
Writable regions: Total=10.2M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=10.2M(100%)
 
                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Process Corpse Info               2048K        2 
STACK GUARD                       56.0M        2 
Stack                             8192K        2 
VM_ALLOCATE                          4K        2 
__DATA                             240K        3 
__LINKEDIT                          84K        2 
__TEXT                             224K        2 
mapped file                       4588K        4 
shared memory                        8K        3 
===========                     =======  ======= 
TOTAL                             71.0M       13 

Model: MacBookPro11,4, BootROM MBP114.0184.B00, 4 processors, Intel Core i7, 2.5 GHz, 16 GB, SMC 2.29f24
Graphics: Intel Iris Pro, Intel Iris Pro, Built-In
Memory Module: BANK 0/DIMM0, 8 GB, DDR3, 1600 MHz, 0x802C, 0x31364B544631473634485A2D314736453120
Memory Module: BANK 1/DIMM0, 8 GB, DDR3, 1600 MHz, 0x802C, 0x31364B544631473634485A2D314736453120
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x152), Broadcom BCM43xx 1.0 (7.21.95.178.1a2)
Bluetooth: Version 4.4.6f4, 3 services, 27 devices, 1 incoming serial ports
Network Service: Thunderbolt Ethernet, Ethernet, en3
Network Service: Wi-Fi, AirPort, en0
Serial ATA Device: APPLE SSD SM0256G, 251 GB
USB Device: USB 3.0 Bus
USB Device: Apple Internal Keyboard / Trackpad
USB Device: Bluetooth USB Host Controller
Thunderbolt Bus: MacBook Pro, Apple Inc., 27.1

**Comment by droidmonkey** [comment]
Your OS is not supported.
