### ISSUE TITLE
I can not open the image file registered in the entry

### ISSUE THREAD

**Issue by glowcat** [keepassxreboot/keepassxc#3146]
I can not open the image file registered in the entry.

## Expected Behavior
I can view the image file attached to the entry

## Current Behavior
I can not open the image file registered in the entry.

## Steps to Reproduce
Make an entry as below and attach an image file.
![scr_01](https://user-images.githubusercontent.com/47072588/57764896-52f5db80-773f-11e9-9f4e-56462897215e.png)
I get an error when I try to open the attached image file.
![scr_02](https://user-images.githubusercontent.com/47072588/57765003-90f2ff80-773f-11e9-9289-4a885f59c026.png)

Text files can be opened without problems.
I can open images without any problems with mac version.
(I tried with the latest 2.4.1 version, but it was the same)

Is this a bug of the windows version? Or is it a specification? Is there a way to view the image without problems?
(Could you tell me if there were other similar reports.)

thanks.

## Debug Info
KeePassXC - Version 2.3.4
Revision: 6fe821c

Libraries:
- Qt 5.11.1
- libgcrypt 1.8.3

Operating system: Windows 7 SP 1 (6.1)
CPU architecture: x86_64
Kernel: winnt 6.1.7601

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by glowcat** [comment]
It seems that even pdf files can not be opened as well.

**Comment by SteveParson** [comment]
I tested this on Linux, and it worked as expected. Give the [newer version ](https://github.com/keepassxreboot/keepassxc/releases/tag/2.4.1) a shot and see if it resolves your problem.
-----------------------------------------------
KeePassXC - Version 2.4.1
Revision: 7bafe65

Qt 5.12.1
Debugging mode is disabled.

Operating system: Fedora 30 (Workstation Edition)
CPU architecture: x86_64
Kernel: linux 5.0.13-300.fc30.x86_64

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (only unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.4

**Comment by glowcat** [comment]
I tried with the latest 2.4.1 version, but it was the same.

Since it worked without problems even with the mac version, only the windows version may occur.

**Comment by droidmonkey** [comment]
Opening attachments works perfectly on Windows. Make sure you have an application associated with opening PNG and PDF files.
