### ISSUE TITLE
TouchId setting can be sticky across restarts

### ISSUE THREAD

**Issue by vraravam** [keepassxreboot/keepassxc#3147]
[TIP]:  # ( Provide a general summary of the feature in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Summary
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
The TouchId support is great on Mac OS Mojave. But, as a user, I would like for the checkbox for touchId to be sticky across restarts of the application.

## Desired Behavior
[NOTE]: # ( Tell us how the new feature should work, be specific )
Each time I reboot my machine or quit and restart KeepassXC, I start typing. Automatically, the focus is on the password field (since I have set it to remember the previous db). Once I enter the password/phrase, I have to use the trackpad/mouse to move the cursor and click on the "TouchId" checkbox for it to be enabled. Instead, if this setting is sticky (from the stored preferences), it would be easier for power users to avoid the mouse/touchpad.

## Possible Solution
[NOTE]: # ( Not required, but suggest ideas on how to implement the addition or change )

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )

**Comment by MageJohn** [comment]
I think this issue might be resolved. The touchID checkbox remains ticked across application restarts for me. Though I haven't confirmed that it works across a reboot.
