### ISSUE TITLE
Key Derivation Function settings not kept

### ISSUE THREAD

**Issue by TomTom-42** [keepassxreboot/keepassxc#3148]
Hi,

I have problem changing the Key Derivation Function in Database Settings.

## Expected Behavior
Be able to set Key Derivation Function with Argon2 algo

## Current Behavior
Key Derivation Function always go back to AES-KDF (KDBX 4) with 1000000 transform rounds
Even if I keep AES-KDF (KDBX 4) and I just modify the transform rounds, increasing it for example, it always go back to 1000000 transform rounds.

## Steps to Reproduce
1. Change the Key Derivation Function in order to set Argon2
2. Save the modification
3. close and re-open KeepassXC
4. go back to Database Settings / Encryption
5. Key Derivation Function value is AES-KDF (KDBX 4) and Transform rounds value is 1000000

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.3.4
Revision: 6fe821c

Libraries:
- Qt 5.11.1
- libgcrypt 1.8.3

Operating system: Ubuntu 18.10
CPU architecture: x86_64
Kernel: linux 4.18.0-20-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by droidmonkey** [comment]
You are using an outdated version of KeePassXC. Recommend upgrading to 2.4.1. You can use the appimage if your distro does not supply it.

**Comment by TomTom-42** [comment]
Indeed... weird it is so old in my distrib...
I added the ppa phoerious/keepassxc and now I have an uptodate version 2.4.1
It's working well now and key derivation function is saved correctly  ;-)

Sorry I disturbed you for that solved problem
