### ISSUE TITLE
Can't open password database which looks fine in KeePass

### ISSUE THREAD

**Issue by pattyland** [keepassxreboot/keepassxc#3151]
## Expected Behavior
Open my Database. 

## Current Behavior
Display a message: 
> Invalid credentials were provided, please try again.
> If this reoccurs, then your database file may be corrupt.

## Context
Right now I'm using the orgininal KeePass 2.41 which works fine with both of my databases. I would like to switch to KeePassXC, but it only works with one of my two databases. I tried to export the "corrupt" database, but that didn't helped.
A reinstall like in #3015 didn't helped.

## Debug Info
KeePassXC - Version 2.4.1
Revision: 7bafe65

Qt 5.12.2
Debugging mode is disabled.

Operating system: Windows 10 (10.0)
CPU architecture: x86_64
Kernel: winnt 10.0.16299

Enabled extensions:
- Auto-Type
- Browser-Integration
- SSH-Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.4

**Comment by droidmonkey** [comment]
Are you using a key file or Yubikey with the other database? Its impossible to help you without your databases unfortunately

**Comment by pattyland** [comment]
No, just a normal password.

I have just created a new database "tmp" with KeePass, the password is "123".
Can be opened with KeePass without problems, KeePassXC says "corrupt"!


[tmp.zip](https://github.com/keepassxreboot/keepassxc/files/3191192/tmp.zip)

**Comment by droidmonkey** [comment]
I can't open that database in KeePass either.

**Comment by droidmonkey** [comment]
Recommend you download KeePass-2.42 portable and give it a try. There is not something right about your installed KeePass. 

https://keepass.info/download.html

**Comment by pattyland** [comment]
Ok I was wrong, new created databases can be opened with KeePassXC. My old database can be opened with KeePass 2.42.1 portable, but not with KeePassXC

**Comment by droidmonkey** [comment]
For your old database, recommend you update it to KDBX4 using Argon2. This may make it compatible:

![image](https://user-images.githubusercontent.com/2809491/57975337-d65c3a80-7994-11e9-9d1e-afb25cceeb3b.png)

**Comment by pattyland** [comment]
After updating the database to KDBX4 I can open and edit it with KeePassXC, thanks for the tip!

If it's technically possible, would it probably be very helpful for users to tell you about this problem when opening it? I would never have thought that it was my file format.

**Comment by droidmonkey** [comment]
I have no idea what your old format was or why it failed to open. You're the first one to ask this, so not too concerned because it works now.

**Comment by dipunm** [comment]
Would like to mention here, I know that this issue is closed, but this thread helped me. My database was set to use AES-KDF as its key deriviation function, after changing it to use Argon2, I could access it with KeepassXC.
