### ISSUE TITLE
Export application settings among a database (optional)

### ISSUE THREAD

**Issue by Slobish** [keepassxreboot/keepassxc#3155]
## Summary
Security settings should be exported among a database.
When an imported database has settings set, these settings should overwrite the default settings. 

## Desired Behavior
I believe security settings should be linked to the database itself.

## Possible Solution
Save the settings in the database and export them with it (optional).

## Context
Many of us use different databases for different purposes, say:
* One with a short and easy password for low-risk accounts
* One with large and strong passwords for money related accounts.

As well as the passwords hardness of both databases is different, the security preferences that you usually would like to apply differ too.

**Comment by droidmonkey** [comment]
This is already tracked by #891 and #2189
