### ISSUE TITLE
Get database password after lock

### ISSUE THREAD

**Issue by lucasgolino** [keepassxreboot/keepassxc#3156]
## Expected Behavior
Clean password field, after locking database.

## Current Behavior
Not cleaning password field after lock database

## Steps to Reproduce
1. Lock Database
2. Click on Eye button (show password as text)
3. Ctrl + Z on field
4. Last typed password is showed

## Context
If anyone can access my computer unlocked, tab to KeepassXC window and CTRL + Z on password field, can get my database password.

## Debug Info
KeePassXC - Version 2.3.1
Revision: 2fcaeea

Libraries:
- Qt 5.9.5
- libgcrypt 1.8.1

Operating system: Ubuntu 18.04.2 LTS
CPU architecture: x86_64
Kernel: linux 4.15.0-48-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by droidmonkey** [comment]
This is already done in 2.4.0
