### ISSUE TITLE
Keyboard shortcuts with all locales

### ISSUE THREAD

**Issue by AveTim** [keepassxreboot/keepassxc#3157]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
When I click cmd+F with active English locale, search becomes active
When I click cmd+F with active differently locale, nothing's going on. 

## Current Behavior
[NOTE]: # ( Tell us what actually happens )
When I click cmd+F with active differently locale, search becomes active
All other shortcuts with ru-locale working good.

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1. MacOS. Add a new keyboard (e.g. Russian). Set it active
2. Type cmd+F
3. ...

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )
It's uncomfortable because KeepassX didn't have this bug

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.4.1
Revision: 7bafe65

Operating system: MacOS

**Comment by droidmonkey** [comment]
Interesting, we should be "translating" our custom keyboard shortcuts. https://doc.qt.io/qt-5/qkeysequence.html#keyboard-layout-issues

**Comment by droidmonkey** [comment]
Looking into this a little further, the search widget already uses the "standard" Qt key sequence. Perhaps this is a bug in Qt.

**Comment by droidmonkey** [comment]
This is a Qt bug if it still is a bug. Closing.
