### ISSUE TITLE
German localisation: "tray icon" translated as "Taskleistensymbol" (task bar icon)

### ISSUE THREAD

**Issue by jeeger** [keepassxreboot/keepassxc#3158]
The naming of this configuration option is misleading in the German locale: ![grafik](https://user-images.githubusercontent.com/3542252/58010983-af674b00-7af1-11e9-8add-31760908c091.png)

## Expected Behavior

Configuration setting should be called "Infoleistensymbol anzeigen" oder "Benachrichtigungssymbol anzeigen".

## Current Behavior

Configuration setting is called "Taskleistensymbol".

## Possible Solution

Modify localisation file to "Infoleisten-Icon anzeigen", "Tray-Icon anzeigen" or "Benachrichtigungssymbol anzeigen".

## Version

Keepassxc 2.4.1

**Comment by phoerious** [comment]
Translations are managed on Transifex. Please perform changes to translations there. Please keep in mind, however, that specific translations for these things vary from platform to platform and Windows terminology may not be understood by macOS or Linux users, for instance. We need terms that work across platforms.

**Comment by jeeger** [comment]
Alright, thanks for the answer!
