### ISSUE TITLE
Deleting many entries results in crash

### ISSUE THREAD

**Issue by MinIsMin** [keepassxreboot/keepassxc#3159]
Deleting many entries crashes KeepassXC without any dialog/message.

## Expected Behavior
When deleting many entries KeepassXC shouldn't crash.

## Current Behavior
KeepassXC deletes the selected entries and crashes.
Console output just says `memory access error`.
The deleted entries are gone after restarting KeepassXC.

## Steps to Reproduce
1. Have more than 70 entries in one group
2. Delete many/all of them
3. Watch it crash

## Debug Info
```
KeePassXC - Version 2.4.1
Revision: 7bafe65

Qt 5.9.5
Debugging mode is disabled.

Operating system: Linux Mint 19.1
CPU architecture: x86_64
Kernel: linux 5.0.17-050017-generic

Enabled extensions:
- Auto-Type
- Browser-Integration
- SSH-Agent
- KeeShare (only unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.1
```

**Comment by droidmonkey** [comment]
Do any of the entries contain references?

**Comment by MinIsMin** [comment]
Not that I know.
How can I check without manually reviewing all entries?

**Comment by droidmonkey** [comment]
Entries would be dimmed (lighter gray) if they have a reference.

**Comment by MinIsMin** [comment]
No entry has a reference.

**Comment by elsesiy** [comment]
Can confirm this is happening in `2.4.2` on MacOS too.

**Comment by MinIsMin** [comment]
Works now with 2.5.2. :+1:
