### ISSUE TITLE
Autosave sometimes doesn't work on iCloud

### ISSUE THREAD

**Issue by defragmentator** [keepassxreboot/keepassxc#3168]
After upgrade from 2.3.4 to 24.1 very often when using keypass file stored in iCloud folder autosave mode does not work. It seems that it occures more likely when the file is opened on more than one device at a time. What is strange even opening in Strongbox on iOS in read only mode very often triggers that issue. It does occur with and without "safe wirte" enabled. 
What is wired disabling and enabling autosave does help, but only until first app restart. 
I lost my recently generated passwords few times :(

Effect:
After change in database save button becomes active, no information is presented to user, changes are not saved. (If user notified that button is now active and clicked it , the changes are saved) After some longer time app shows a dialog that current version differs form that on a storage. It doesn't matter of I choose to merge or not changes are lost.

Solution:
For now only downgrade to 2.3.4 succeed (I wasn't trying 2.4.0 ).

KeePassXC - Version 2.4.1
Revision: 7bafe65

Qt 5.12.2
Debugging mode is disabled.

Operating system: macOS Mojave (10.14)
CPU architecture: x86_64
Kernel: darwin 18.5.0

Enabled extensions:
- Auto-Type
- Integracja z przeglądarką
- Agent SSH
- KeeShare (only unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
 libgcrypt 1.8.4

**Comment by droidmonkey** [comment]
We fixed a lot of saving issues in 2.4.1, it is surprising this is still an issue.
