### ISSUE TITLE
Property field displays old text after removing it

### ISSUE THREAD

**Issue by MinIsMin** [keepassxreboot/keepassxc#3170]
When editing a property field of an entry the old text is shown even if it is deleted/overriden.
See this video: https://streamable.com/zye1d

## Expected Behavior
The deleted/overriden text should get hidden/deleted from UI.

## Current Behavior
The deleted/overriden text is still shown

## Steps to Reproduce
1. Edit an entry
2. Go to Advanced
3. Add/edit property

## Debug Info
```
KeePassXC - Version 2.4.1
Revision: 7bafe65

Qt 5.9.5
Debugging mode is disabled.

Operating system: Linux Mint 19.1
CPU architecture: x86_64
Kernel: linux 5.0.17-050017-generic

Enabled extensions:
- Auto-Type
- Browser-Integration
- SSH-Agent
- KeeShare (only unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.1
```

**Comment by droidmonkey** [comment]
I have never seen this before. Does not happen on Windows.

**Comment by droidmonkey** [comment]
I also cannot reproduce on Linux Mint 19.1 using the appimage. This could be a Qt bug.

**Comment by MinIsMin** [comment]
Maybe.
I use KeepassXC via [phoerious ppa](https://launchpad.net/~phoerious/+archive/ubuntu/keepassxc).

**Comment by droidmonkey** [comment]
Sorry but this cannot be a problem with KeePassXC itself, and I cannot reproduce it.
