### ISSUE TITLE
Minimize at application startup not working

### ISSUE THREAD

**Issue by g0r3** [keepassxreboot/keepassxc#3171]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Minimise window at application startup is activated. 
Application should minimize when started.
Instead it stays open and I have to close it.

## Current Behavior
[NOTE]: # ( Tell us what actually happens )
Minimise window at application startup is activated. 
Application does not minimize when starting up.

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1. Activate 'Minimise window at application startup'. 
2. Close the application
3. Start the application
4. KeepassXC shows opened database or the open database window

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )
(Un)Ticking the 'Minimize' option does not seem to matter. Using Arch Linux with Budgie 10.5
Keepass gets started via the cmd 
```zsh -c "keepassxc --pw-stdin ~/Google\ Drive/Other/logins.kdbx <<< password```
But also when starting it normally, it does start minimized.

## Debug Info
KeePassXC - Version 2.4.1
Revision: 7bafe65

Qt 5.12.3
Debugging mode is disabled.

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 5.1.2-arch1-1-ARCH

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.4

**Comment by droidmonkey** [comment]
Please see #2481

**Comment by g0r3** [comment]
Hi,

I neither use KDE nor some kind of session restore. KeepassXC is also not started at the point where the shell command to start it is executed. So I am not seeing any other commonalities except than Arch Linux. Also adding a pause (sleep 5) didn't change anything. I am happy to provide any other information if needed.

**Comment by droidmonkey** [comment]
Ok good to know. We've had issues with this on macOS as well (although it is a mac specific issue)

**Comment by ba32107** [comment]
I am having the same problem. I'm using the snap package (2.4.3) on Ubuntu, and it does not honor the minimize setting.

I built the master branch (also 2.4.3) and that works correctly (with the same config file). I think it might be an environmental issue, but unsure what.

**Comment by ba32107** [comment]
I just installed the ubuntu specific package, and this bug is not present. I think this is a snap-specific issue.

**Comment by CountCypher** [comment]
I'm having the same issue with version 2.4.3 on Fedora 30. I've tried both the Fedora repository version and the AppImage - both ignore the minimize at startup setting.

**Comment by ekianjo** [comment]
I have the same issue on GNOME (Solus) with the version in the repository. Here the debug info:

KeePassXC - Version 2.4.3
Revision: 5d6ef0c

Qt 5.13.1
Debugging mode is disabled.

Operating system: Solus 4.0 Fortitude
CPU architecture: x86_64
Kernel: linux 5.2.20-130.current

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.5

**Comment by boggle247** [comment]
Not sure which github issue to comment on, but I'm still having this issue on Manjaro 20.0 XFCE. Check box is toggled in the keepass settings. starts open and not minimized, or minimized to tray.

KeepassXC ver: 2.5.4-2 from community repo

**Comment by onire77** [comment]
I have the same problem.

KeePassXC - Version 2.5.4
Revision: dcca5aa

Qt 5.15.0
Debugging mode is disabled.

Operating system: openSUSE Tumbleweed
CPU architecture: x86_64
Kernel: linux 5.7.5-1-default

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.5

**Comment by droidmonkey** [comment]
We fixed this in 2.6.0

**Comment by droidmonkey** [comment]
Just tested 2.6.0, this only affects the snap build.

**Comment by droidmonkey** [comment]
No longer a problem with 2.7.0
