### ISSUE TITLE
Delay while typing master password

### ISSUE THREAD

**Issue by pixel8383** [keepassxreboot/keepassxc#3173]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
While typing the master password the dots on the field should appear as fast as the char is typed on the keyboard

## Current Behavior
[NOTE]: # ( Tell us what actually happens )
You have to wait for dots to appears. The issue appeared on keepassxc 2.4.1

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1. Open keepassxc on macOS
2. Type your password
3. Check on the password field the input speed

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.4.1
Revision: REVISION

Libraries:
- LIBS

Operating system: macOS 10.14.5
CPU architecture: Intel
Kernel: KERNEL

Enabled extensions:
- EXTENSIONS

**Comment by droidmonkey** [comment]
We didn't change anything related to typing in 2.4.1. It is likely this is yet another issue with Qt 5.12.x on macOS. There are also reported slowdowns for scrolling as well.

**Comment by pixel8383** [comment]
Sorry, I wasn't accurate, it appeared with KeePassXC 2.4.
Everything was fine with 2.3.x

**Comment by droidmonkey** [comment]
Yeah this is probably a qt related issue. The version of qt bundled with 2.4 is brand new

**Comment by pixel8383** [comment]
Do you think there will be any improvments in the next releases of keepassxc? It's a bit annoying.

**Comment by droidmonkey** [comment]
I don't experience this behavior in my macos client. I don't have a clue as to the cause. We certainly do not make it slow by any means.
