### ISSUE TITLE
security issue: keepassXC can not clear username and password from windows 10 **multiple clipboard** !

### ISSUE THREAD

**Issue by vejagaho** [keepassxreboot/keepassxc#3177]
windows 10 v1903
keepassxc v2.4.1

keepassXC can not clear username and password from windows 10 **multiple clipboard** !

![Capture](https://user-images.githubusercontent.com/50960891/58268607-f461da80-7d9a-11e9-9156-fab07479dacf.PNG)

**Comment by droidmonkey** [comment]
Just disable it
