### ISSUE TITLE
Pressing enter with search field focus opens highlighted entry

### ISSUE THREAD

**Issue by metronidazole** [keepassxreboot/keepassxc#3178]
## Expected Behavior
Pressing enter after typing in a search query should simply show all search results. This is the behaviour in keepass and keepassx.

## Current Behavior
Pressing enter after typing in a search query opens the first search result.

## Possible Solution
After pressing enter, the focus should return to the search result and not open the first search result.

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1. Type in search query
2. Press enter
3. First search result opens

## Context
This makes it difficult to use keepassXC as it is unexpected behaviour and breaks standard UI design practices.

## Debug Info
KeePassXC - Version 2.4.1
Revision: 7bafe65

Qt 5.12.3
Debugging mode is disabled.

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 5.1.4-arch1-1-ARCH

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.4

**Comment by droidmonkey** [comment]
This is by design. Search is performed automatically and thus there is no need to press Enter. There is no "standard" for this, it is how our application works.
