### ISSUE TITLE
auto-type windows associations issue

### ISSUE THREAD

**Issue by povad1** [keepassxreboot/keepassxc#3179]
windows10 1903
keepass2.4.1 64bit portable

when i choose and setup windows title with **specific sequence** and click on _perform auto-type_ from right click menu the keepass can not detect windows title and enter **default** auto-type for every windows! 

but when choose a shortcut ( for example ctrl+c) keepass detect correct windows and no problem.

**Comment by droidmonkey** [comment]
The "Perform Auto-Type" button and associated keyboard combo uses the default auto-type sequence for the entry on the last selected window. This is by design.
