### ISSUE TITLE
How to choose a default entry to open on startup?

### ISSUE THREAD

**Issue by JPL1** [keepassxreboot/keepassxc#3182]
## Expected Behavior
Option in Tools | Settings to allow user to select default entry to open when KeepassXC opens the database

## Current Behavior
As far as I can see there is no such option. The database opens each time with two particular entries displayed, and I have no idea why as I did not knowingly select them. I can't find any config-type file to adjust either (Windows).

## Possible Solution
If there is such an option, make it more obvious.

## Steps to Reproduce
1. Open KeepassXC enter password
2. Database opens. In my case two particular entries are displayed

Operating system: Win10
CPU architecture: x64

Enabled extensions:
- None

**Comment by droidmonkey** [comment]
We show the root group when you open the database. If you don't want to see those two entries, move them to another group.
