### ISSUE TITLE
Database format v3.1 is ignored by KeePassXC v2.4.1 when Browser integration enabled

### ISSUE THREAD

**Issue by jonastr** [keepassxreboot/keepassxc#3183]
## Background
I have a database in 4.x format, which is apparently not compatible with thirdparty tools (namely MiniKeePass and KeePassX). So, I wanted to go back to the older 3.1 format, which is compatible.

However, selecting v3.1 as database format did not result in a file with 3.1 format. Instead, I would still have a 4.x format file.

## Expected Behavior
When the browser integration is enabled and keys have been migrated to the new format (according the UI dialog), selecting v3.1 database format should not be shown anymore or provide some migration to the browser integration data that makes it compatible to format v3.1 again.

## Current Behavior
It looks like the v3.1 format selection is ignored:
* Database saved with format selector set to v3.1 shows "v4" after reopening.
* Database cannot be opened in MiniKeePass (iOS) nor the original KeePassX.

## Steps to Reproduce
1. Save a file in 4.x format
2. Enable browser extension
3. Add site-specific settings for the integration
4. Go to database settings and change format to v3.1
5. Safe the database
6. Re-open database settings - format 4.x is shown again.

## Context
Database could not be opened anymore by thirdparty applications, leaving me in trouble when I needed access to the database.

## Debug Info
KeePassXC - Version 2.4.1
Revision: 7bafe65

Qt 5.12.2
Debugging mode is disabled.

Operating system: macOS High Sierra (10.13)
CPU architecture: x86_64
Kernel: darwin 17.7.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (only unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
 libgcrypt 1.8.4

**Comment by phoerious** [comment]
Browser integration relies on custom data, which requires KDBX4, so this is working as intended.
There is no reason to keep using KeePassX and for iOS I would recommend Strongbox.

**Comment by jonastr** [comment]
@phoerious the point I'm making is that the UI is inconsistent and giving bad UX: it suggests that one can go back to 3.1 format, which simply doesn't work in this case.
so, the dropdown should IMHO not list the 3.1 format in this case. that's why i'm calling it a bug.

thx for the recommendation on strongbox though, i'll check it out.

**Comment by droidmonkey** [comment]
I agree we should just disable the ability to downgrade the database version

**Comment by phoerious** [comment]
Downgrades should be possible, we just need to check if the database contains custom data and disable it then.

**Comment by jonastr** [comment]
@phoerious exactly, that would be a good fix IMHO.
