### ISSUE TITLE
sanity check with regard to migration of keepasshttp attributes

### ISSUE THREAD

**Issue by PF93mc8y7erq92qTmTjJBysALa** [keepassxreboot/keepassxc#3184]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Button to trigger migration of KeePassHTTP attributes to KeePassXC-Browser custom data need not be so prominent, especially if no such attributes exist.

## Current Behavior
[NOTE]: # ( Tell us what actually happens )
#### KeePassXC Menu / Database / Database settings / Browser Integration
There is a wide button to "Move KeePassHTTP attributes to KeePassXC-Browser custom data". This button shows up and is enabled even if a migration just took place as well as if no such attributes exist. 
Upon clicking the button the "are you sure" dialog appears. Confirm with "yes" which is followed by another msgbox "the active database does not contain an entry with KeePassHTTP attributes" OK.

## Possible Solutions
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )
a) Button should be disabled if no such attributes exist.
b) Button should not be visible if no such attributes exist.
c) Allow the button but instead of the "are you sure" show either "no such entries exist" or "x entries found, are you sure".
d) Leave it as is

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.4.1
Revision: 7bafe65

Qt 5.12.2
Debugging mode is disabled.

Operating system: macOS Mojave (10.14)
CPU architecture: x86_64
Kernel: darwin 18.6.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (only unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
 libgcrypt 1.8.4

**Comment by droidmonkey** [comment]
This is in the database settings (pretty buried) and does not harm if nothing is present. It will eventually go away when everyone has migrated to KDBX4 and KeePassXC 2.4.x. I choose option (d). 😄
