### ISSUE TITLE
Open URL with...

### ISSUE THREAD

**Issue by hublol** [keepassxreboot/keepassxc#3185]
## Summary
It would be nice if to be able to open URLs in different browsers, instead of always using the default browser.

## Desired Behavior
It should be possible to control the behavior when double clicking on a URL (ie control in which browser the window is opened), and to customize multiple entries.
For example, my default browser is chromium, but I always connect to critical web sites (banking, etc.) in a new private Firefox window.
When right clicking on a URL in the database, I would like to have the choice of where the site will be opened (this is what I currently have in Keepass).

## Context
Many people are using different browsers for different purposes. Having to manually open the URL in the correct browser instead of just launching the site from the database is cumbersome.

**Comment by droidmonkey** [comment]
Sorry we won't be implementing this. It is too cumbersome to deal with anything but the default defined by the OS.
