### ISSUE TITLE
Extracting password hash from kbdx

### ISSUE THREAD

**Issue by farid-fari** [keepassxreboot/keepassxc#3186]
I created a database and near-instantly forgot the password

I want to bruteforce the hash since I know the whole password apart from one word, which I know is an adjective

What would be the easiest way of extracting the hash from the database file? I tried `keepass2john` but the format is too recent for it...

**Comment by droidmonkey** [comment]
If you are using kdbx4 with argon2 it might be near impossible to brute force unless you really only have one word and its from the passphrase word list.

**Comment by farid-fari** [comment]
Great thanks!

I actually just reset my passwords so there's no need, but it's good to know this is possible this way.
