### ISSUE TITLE
Unable to use numerous passwords for a single field with KeePass-XC Browser

### ISSUE THREAD

**Issue by AltusForm** [keepassxreboot/keepassxc#3188]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
It's possible to have a lot more than 20 access for one website. Any data should be selectable using KeePass-XC Browser, even the ones that are down in the field. 

## Current Behavior
[NOTE]: # ( Tell us what actually happens )
Only the first 20 or so data can be seen, unable to see the last ones (can be selected but without knowing which one is selected).
![image](https://user-images.githubusercontent.com/51131089/58497558-7cb9f400-817c-11e9-998c-44a9b14c4dde.png)

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )
Add a scroll bar to KeePass-XC Browser field

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1.
2.
3.

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )
A lot of different access for one website

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION 2.4.1
KeePassXC-Browser version : 1.4.5
Revision: REVISION

Libraries:
- LIBS

Operating system: OS Windows
Web navigator : Firefox 67
CPU architecture: ARCH
Kernel: KERNEL

Enabled extensions:
- EXTENSIONS

**Comment by droidmonkey** [comment]
You should use the extension popup dialog instead which includes a text filter. The input box selector is not designed for so many credentials.

**Comment by AltusForm** [comment]
Thanks for your fast answer
Quite often the extension popup dialog is not working properly since the
last update. I have a lot of problem connecting the database. In this case,
the extension popup dialog is just saying " L'échange de clé a échoué." and
the only way to use KeepassXC is to use the field on the website. Even if I
have this message, the database is connected most of the time...
[image: image.png]

Le mar. 28 mai 2019 à 19:54, Jonathan White <notifications@github.com> a
écrit :

**Comment by varjolintu** [comment]
Disable the Auto-reconnect from the extension's settings if you encounter any issues connecting to the database.

**Comment by AltusForm** [comment]
Thank you, I'll try that

Le mer. 29 mai 2019 à 05:55, Sami Vänttinen <notifications@github.com> a
écrit :

**Comment by varjolintu** [comment]
I suggest you follow this PR as it might solve your problem when the feature is implemented: https://github.com/keepassxreboot/keepassxc-browser/issues/478.

**Comment by AltusForm** [comment]
Sounds great, thank you
Alain

Le ven. 31 mai 2019 à 14:58, Sami Vänttinen <notifications@github.com> a
écrit :

**Comment by varjolintu** [comment]
Having any issues?

**Comment by AltusForm** [comment]
For me it's working now.
It's great, thank you
Alain

Le sam. 19 oct. 2019 à 13:30, Sami Vänttinen <notifications@github.com> a
écrit :
