### ISSUE TITLE
After returning from search, list is in random order

### ISSUE THREAD

**Issue by creideiki** [keepassxreboot/keepassxc#319]
I have the password list sorted by the "Title" field, ascending. There is a down-pointing arrow at the rightmost edge of the "Title" column header showing this.

When I start typing in the "Find" text box, a column "Group" appears to the left of "Title". The down-pointing arrow moves to its column header. However, the list still seems to be sorted according to "Title".

When I press Escape to return to the full list, the column "Group" disappears and the down-pointing arrow moves back to the "Title" column header. However, all the lines are now in random order. To get them sorted again, I have to click the "Title" column header twice; once to change to descending sort, and once again to switch back to ascending.

## Expected Behavior
The lines should continue to be sorted according to my set preference, no matter the filtering state.

Also, the sort indication UI (the arrow in the column header) should match the actual sort state of the list.

## Your Environment
* KeePassXC version/commit used: 2.1.1, 44c58a66d1076d0112f93d84fccd47c6e41dab5a
* Qt version (e.g. Qt 5.3): 5.7.1
* Compiler (e.g. Clang++3.6.0): GCC 5.4.0
* Operating System and version: Gentoo Linux

**Comment by TheZ3ro** [comment]
Wow, I've never notice this!

**Comment by phoerious** [comment]
I cannot quite reproduce your issue as you describe it. But what I can reproduce is this:

- I search for entries, they show up ordered by group (as expected)
- I cancel the search, items get reordered by name, but in various chunks

So when I have entries a, b, c, d, e, f, I get an order like c, d, e, f, a, b. It's not totally random (and the same order is reproducible for every search).

Nice find! I'll look into it and see if we can maybe squeeze the fix into 2.1.2 even. I didn't want to make another patch for that release, but maybe the fix is small enough.

**Comment by droidmonkey** [comment]
Defer to 2.2 this should go with other search enhancements.

Caveat: unless its a one line fix

**Comment by phoerious** [comment]
That's what I'm checking right now.
BTW after trying again a couple of times I can also reproduce the initial sort order by title instead of group.

**Comment by creideiki** [comment]
@phoerious You're right, I wasn't checking carefully enough. The jumbled order after returning from search is the same every time (including after restarting the program), and if I scroll around in the list, I do find some blocks that are internally sorted. These are in a clear minority, though.

**Comment by TheZ3ro** [comment]
In one of my database (a KeePassX 0.4 database converted to KeePassXC) I can clearly see all the older KeePassX 0.4 entry at the top (that have a different icon) and the KeePassXC at the bottom. 
I think they are ordered based on their position in the .kdbx XML. 
I will try using the keepassxc-cli extract option to confirm this.

**Comment by phoerious** [comment]
It has something to do with column reordering. The switching between group and entry list mode happens by showing or hiding the first column ("Group") and then re-ordering. When I skip the first step, the order always works as expected, but when I change the number of shown columns, it gets messed up.
