### ISSUE TITLE
Allow keyfiles through named pipes

### ISSUE THREAD

**Issue by josechrist** [keepassxreboot/keepassxc#3190]
## Expected Behavior
`keepassxc --keyfile <named pipe> <path to kdbx> &` should work

## Current Behavior
`keepassxc --keyfile <named pipe> <path to kdbx> &` failed to open keyfile

## Possible Solution
Read the name pipe and go in background

## Steps to Reproduce

1. Create a named pipe
2. Load a key in it
3. Put that named pipe as an argument of keepassxc

## Debug Info
KeePassXC - VERSION : 2.4.1
Operating system: OS linux fedora
CPU architecture: x86-64
Kernel: KERNEL 5

**Comment by droidmonkey** [comment]
How (and why) are you feeding the keyfile through a named pipe? Just point to the keyfile itself.

**Comment by josechrist** [comment]
A named pipe behaves as a file. I point to the named pipe as I would point to a file. I use a named pipe for security reasons. This works with Keepass I am migrating from.

It seems that Keepassxc reads the named pipe twice (or more), then the second time it is empty.

**Comment by schlomie** [comment]
I too, would find this a useful feature.  It would be useful to keep a gpg encrypted keyfile that only is only decrypted at use time.

e.g. `keepassxc-cli --key-file <(gpg -d keyfile.asc) ...`

Just one extra layer of security, really.

**Comment by josechrist** [comment]
Yes, I use the named pipe because feeding Keepassxc through a stream doesn't works, see also
`echo "$MY_CLEARKEY" | keepassxc --key-file - <path to the db>`

**Comment by droidmonkey** [comment]
You might be looking for ```keepassxc --pw-stdin``` instead in this case?

**Comment by schlomie** [comment]
The password through stdin works, but then you lose the MFA nature of keyfiles + passwords.

I'm making due without.   For my use, #3190 would be better suited as a feature request than a bug.

**Comment by phoerious** [comment]
There is no inherent advantage of keyfiles vs. random passwords. If you want to strengthen your not-so-secure password by random bytes you cannot remember, but don't want to rely on a file alone, you can always pipe both a keyfile and a password into stdin one after the other.

**Comment by schlomie** [comment]
This is true.   Even separating the fields does little more than:

`NeededPassword = Password1 + Keyfile (Password2)`

The means by which the Password and Keyfile are provided does have some value - although there are ways to mimic even this.

Truthfully, I'm more looking forward to #2754, #2064.  (I do have a yubikey, but highly prefer the openness of the OnlyKey over yubikey.)  The level of security a deterministic HMAC challenge/response really isn't any higher than password + keyfile either, but for convenience.  Right now my keyfile is stored on a secured flash drive, apart from the db, and will continue to be sufficient.

Perhaps the biggest improvement would be #1257, but that would really be beyond the design goals of keepassxc.

Anyway, now I'm off topic and digress.  My apologies!

**Comment by josechrist** [comment]
In fact I use a yubikey to encrypt/decrypt the keyfile I will check with a password.

**Comment by josechrist** [comment]
OK it works with passwords.... needs to remove the master key and set new password. The password is not visible in the process list.
