### ISSUE TITLE
Multi Users Access on DB / Lost Informations

### ISSUE THREAD

**Issue by liberodark** [keepassxreboot/keepassxc#3191]
Hi,

PC 1 KeepassXC 2.41 / PC 2 KeepassXC 2.41

Just one question very simple i want to use on my enterprise keepassxc over keepass.
But no have see sync possibility. (same as keepass)
Have make test on sshfs or on cifs or samba.
But all not work is normal ?
No have sync on multi users on same DB.

In my example I created a db.
The pc 1 adds an entry the pc2 also adds an entry.
But in the end the pc1 does not see the pc2 input without relaunching keepassxc.
To be sure I did my tests on 3 network protocols but I do not understand that it does not work.
If this is normal then I should stay on keepass.
I don't speak fusion of db that is work but no have automatical see for change ?

Still a bigger problem I saw a data loss
In the case where PC 1 enters information and it closes keepassxc and that PC 2 enters other information that erases the data of PC 1 when PC 2 closes are keepassxc.

I am going to write in french to be sure to make me understand basically there is a case where keepassxc loses data:

PC 1 and PC 2 are on the same DB the one that will enter the information last without making a merge I speak of a use to the normal keepass or everyone can put information at the same time.
Then the last pc that closes and reopen keepassxc overwrites the other user's data.

---------------------

Je vais écrire en français pour etre sur de me faire comprendre en gros il y a un cas ou keepassxc perd des données : 

PC 1 et PC 2 sont sur la meme DB celui qui va entrer les informations en dernier sans faire de fusion je parle d'une utilisation à la keepass normale ou tout le monde peut mettre des informations en meme temps.
Alors le dernier pc qui ferme et réouvre keepassxc écrase les données de l'autre utilisateur.

Best Regards
PS : Thx for your very great work i love your QT5 port.

**Comment by droidmonkey** [comment]
See #2389. This issue will correct issues with sharing via SMB/sshfs/etc on Linux.
