### ISSUE TITLE
KeepassXC repeatedly spawns a new instance when KeepassXC-Browser enabled on Chrome or Firefox

### ISSUE THREAD

**Issue by drewfreyman** [keepassxreboot/keepassxc#3192]
On my Mac whether using Firefox or Chrome, as soon as I open the browser the following happens in two scenarios:

1.  KeePassXC is already open:  an additional instance of KPXC is spawned long enough to be seen in the dock, then killed, then spawned, ad infinitum.
2. KeePassXC was not open:  A new instance is opened and once I input my password, an additional instance of KPXC is spawned long enough to be seen in the dock, then killed, then spawned, ad infinitum.

When additional instances are being spawned focus is drawn to it momentarily making it almost impossible to gain control of the computer to use another application.

This is re-produceable. 

Here is info about my Mac
 Model Name:	Mac mini
  Model Identifier:	Macmini8,1
  Processor Name:	Intel Core i5
  Processor Speed:	3 GHz
  Number of Processors:	1
  Total Number of Cores:	6
  L2 Cache (per Core):	256 KB
  L3 Cache:	9 MB
  Memory:	8 GB
  Boot ROM Version:	220.260.170.0.0 (iBridge: 16.16.5125.0.0,0)

Here are samples taken using the Activity Monitor and Chrome task manager of both the Chrome extension and of KPXC.
[Sample of Google Chrome Helper.txt](https://github.com/keepassxreboot/keepassxc/files/3235506/Sample.of.Google.Chrome.Helper.txt)

[Sample of KeePassXC.txt](https://github.com/keepassxreboot/keepassxc/files/3235483/Sample.of.KeePassXC.txt)

**Comment by varjolintu** [comment]
Please enable the proxy feature in KeePassXC's settings (Browser Integration -> Advanced tab). If you still have problems with it, disable Auto-Reconnect from extension's settings.

**Comment by drewfreyman** [comment]
Was this potential problem and setting solution explained in any of the
documentation for KPXC? Could you direct me to it?


~  please excuse message brevity--sent from mobile device  ~

**Comment by renataogarcia** [comment]
I was experiencing the same problem and once I've enabled the proxy option "Use a proxy application..."(there are two) it stopped the re-spawn issue and I was able to see that it was failing with a key exchange error. Once I removed the entry in the "Connected Databases" in the extension settings and reconnected it's works again. In order to get the extension to launch KeyPassXC as previously, I had to disable the proxy option again.

Hope this helps.

**Comment by Kyshman** [comment]
> I was experiencing the same problem and once I've enabled the proxy option "Use a proxy application..."(there are two) it stopped the re-spawn issue and I was able to see that it was failing with a key exchange error. 

Had the same issue and my resolution was the same as you when on KPXC  2.4.1. However I decided to upgrade my KPXC after resolution to 2.4.2

<img width="457" alt="key_exchange" src="https://user-images.githubusercontent.com/42900317/58761068-8c548680-8548-11e9-9340-0c10f5f583d3.png">

This happens on both my browsers (Vivaldi & Firefox)

> Once I removed the entry in the "Connected Databases" in the extension settings and reconnected it's works again. In order to get the extension to launch KeyPassXC as previously, I had to disable the proxy option again.
> 

Removing the connected database doesn't not work for me. Have even removed the KeepassXC-Browser completely on both browsers and restarted them then installed. Still get the key exchange issue.
 
However curiously when I downgrade KXPC to 2.4.1 the key exchange error is gone and am able to connect to the database as normal. Am at a loss as what's changing in 2.4.2 that makes the database unusable from the browsers.

Surviving on manually copy and paste for now.

**Comment by varjolintu** [comment]
@Kyshman This happens because KeePassXC 2.4.2 had a wrong linkage with keepassxc-proxy and it's not launched properly. As a workaround you can downgrade to 2.4.1 (like you did), or install `libsodium` via Homebrew (I assume you are a macOS user).

**Comment by Kyshman** [comment]
> @Kyshman This happens because KeePassXC 2.4.2 had a wrong linkage with keepassxc-proxy and it's not launched properly.

Will this be fixed?
 
>As a workaround you can downgrade to 2.4.1 (like you did), or install `libsodium` via Homebrew (I assume you are a macOS user).

Yes am a macOS user and unfortunately also a **MacPorts** not Homebrew person. I see this in the ports library

libchloride @20140929_1 (devel, security)
    Networking layer for libsodium, based on CurveCP

libsodium @1.0.17 (devel, security)
    Portable and packageable NaCl-based crypto library

I installed libsodium but see no change. Will stick with 2.4.2 for a while to see if anything changes before downgrading.

**Comment by varjolintu** [comment]
@Kyshman It will be fixed soon with a new version. Another workaround is to copy `keepassxc-proxy` from the earlier build. Works like this (when the package is downloaded and opened): https://github.com/keepassxreboot/keepassxc-browser/issues/559#issuecomment-497956804

**Comment by Kyshman** [comment]
> @Kyshman It will be fixed soon with a new version. Another workaround is to copy `keepassxc-proxy` from the earlier build. Works like this (when the package is downloaded and opened): [keepassxreboot/keepassxc-browser#559 (comment)](https://github.com/keepassxreboot/keepassxc-browser/issues/559#issuecomment-497956804)

THis works!!
