### ISSUE TITLE
HiDPI text size ubuntu 18.10

### ISSUE THREAD

**Issue by demon101** [keepassxreboot/keepassxc#3195]
After installation of 2.4.1 everithing looks good. But after reboot font size become small. Inputs and texts are very small 

## Expected Behavior
Font size should be big enough 

## Current Behavior
Difficult to read

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1.
2.
3.

## Debug Info
KeePassXC - Version 2.4.1
Revision: 7bafe65

Qt 5.11.1
Debugging mode is disabled.

Operating system: Pop!_OS 18.10
CPU architecture: x86_64
Kernel: linux 4.18.0-20-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.3

**Comment by droidmonkey** [comment]
Please read up on https://github.com/keepassxreboot/keepassxc/issues/2815#issuecomment-475668798
