### ISSUE TITLE
Convert QR code to TOTP seed key

### ISSUE THREAD

**Issue by sebast889** [keepassxreboot/keepassxc#3196]
## Summary

There are websites that provide TOTP 2FA but only provide QR codes not seed keys that can be copy pasted into KeePassXC. It is cumbersome to convert QR code to a TOTP seed key (requires downloading additional programs to convert or online services).

## Desired Behavior

There should be a easy way to just select/input the QR code (saved as image file from the website) into KeePassXC and make it set up TOTP for an entry automatically from that QR code.

**Comment by droidmonkey** [comment]
This would require bringing in a whole image processing library and associated controls. It is FAR easier to just use a web service such as https://webqr.com/. I am going to say no to this. Thank you for the idea though.
