### ISSUE TITLE
Usability: can't save while editing an entry

### ISSUE THREAD

**Issue by nicad** [keepassxreboot/keepassxc#3198]
When I'm editing an item saving (with CMD-S) has no effect. I have to click ok and then save when I can see all items.

That's not what I would expect, with other editing apps I've used I'm able to save at any point.
It's particularly useful to save while editing an entry: my workflow is to generate a password, copy it, ideally save the entry (what's not happening at the moment), context switch to another app, paste the password. Ideally I don't even have to go back to the password manager but even if I do it could be some time and if things crash I'll be stuck: new password got accepted in other system but not saved locally.

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.4.2-snapshot (but I don't think it's version specific, it has always been that way, even KeePassX behaves this way)

Operating system: Mac
CPU architecture: Intel
Kernel: 10.14.5

Enabled extensions:
none

**Comment by droidmonkey** [comment]
I agree there is no good reason not to have the save button enabled in this context.

**Comment by nicad** [comment]
Forgot to mention: I have auto save on (didn't trigger, not sure what's the frequency), also I can do CMD-S and nothing happens, so I don't even get feedback that changes weren't saved. It has happened to me in the past that I do this and when I get the "cancel / don't save" dialog a long time after (could be days that I don't check keepassxc) and I don't realized I never made a change and assume I've made a typo and do cancel. I've since learned to always save.

**Comment by droidmonkey** [comment]
If you have autosave on then the database will save when you press Apply or OK

**Comment by nicad** [comment]
just tried again, when I added an entry, pressed OK then it auto-saved. So then I tried to modify a password, pressed ok then no auto-save. Just added another entry and no auto-save again. Saved explicitly, added another entry and it auto-saved, added one the next minute and no auto-save. Confused what to expect ... is there a timer logic impacting auto-save ?

**Comment by droidmonkey** [comment]
Uh no? If you have autosave enabled it works every time there is a database change. I tested it in 2.4.2 on windows and it works as expected.

**Comment by nicad** [comment]
Thanks for checking, I tried again not relying on Finder getting updated, using fswatch directly and running stats manually too. If an update is done close (few seconds) to another one there is no auto-save (mtime is unchanged). Might be MacOS related but I would be very surprised.

**Comment by droidmonkey** [comment]
This now works in 2.6.0
