### ISSUE TITLE
Entries with references are hard to read when using a dark theme

### ISSUE THREAD

**Issue by guixxx** [keepassxreboot/keepassxc#3201]
## Expected Behavior
To actually have readable entries when your desktop theme is dark-styled.

## Current Behavior
Entries with references are really hard to read under a dark desktop theme. Being more specific, I'm running KDE Plasma 5.15.5 and my desktop theme is called Breeze Transparent Dark, which is a slightly modified version of the official Breeze Dark (one of the themes that ships with KDE by default):

![Screenshot_20190601_005233](https://user-images.githubusercontent.com/27077338/58743445-ab97ca80-8407-11e9-9ae7-b7f3b87ca04e.png)

## Possible Solution
Not really sure if applicable here, but if I understood correctly: @droidmonkey [suggested](https://github.com/keepassxreboot/keepassxc/issues/860#issuecomment-497724900) that having a more generic way to detect dark desktop modes/themes could solve this.

## Steps to Reproduce
1. Have KDE Plasma as your desktop environment (I haven't tested this on GNOME)
2. Enable a dark theme (e.g. Breeze Dark)
3. Create a new entry which references fields of some other entry
4. Entry becomes "unreadable"

## Debug Info
KeePassXC - Version 2.4.2
Revision: a775031

Qt 5.12.3
Debugging mode is disabled.

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 5.1.5-arch1-2-ARCH

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.4

**Comment by guixxx** [comment]
I forgot to mention that macOS users were having the same issue (#860), but it's been fixed already.

**Comment by mrbenjoi** [comment]
I am having the exact same problem. I hope it's fne to tell this in an extra comment. I also added a ThumbsUp to the isse description.

**Comment by runiq** [comment]
This also happens with the 'normal' Breeze Dark theme that ships with Fedora 30/31. I think I've experienced this problem since Fedora 28.

**Comment by chtiland** [comment]
As problem seems to be linked to this one, don't think a new issue is required.

**macOS 10.15 Catalina... dark mode**

- KeePassXC - Version 2.4.3
- Revision: 5d6ef0c

Input field background and font color are the same so it's unreadable...

![KeePassXC 2019-10-20 11-10-25](https://user-images.githubusercontent.com/298526/67157298-983fba00-f32a-11e9-8578-381111b2299d.png)

**Comment by phoerious** [comment]
This tends to happen if you change the theme while KeePassXC is running. If you restart it, everything should look normal. I noticed the same thing on KDE.

**Comment by chtiland** [comment]
> This tends to happen if you change the theme while KeePassXC is running. If you restart it, everything should look normal. I noticed the same thing on KDE.

This is effectively what happened ! I had to go back to "Normal mode" for a few minutes for another app ! Restarting KeepassXC "solved" my problem. Thanks for the "tip" ;)

**Comment by mrbenjoi** [comment]
I'm not sure, but I don't think it's related to the problem with the input fields.

The problem with the input fields occurs when changing the desktop theme from bright to dark, while KeepassXC is running. A restart of the app resolves this problem. The problem described in this issue is not resolved when restarting KeepassXC. It remains.

If you start KeepassXC using a bright theme, entries with references also are less readable than other entries, because the labels are displayed with a "dimmed" grey color. Probably this color is not well adapted to dark themes and therefore the labels become almost unreadable when using a dark theme, as visible above in the screenshot.



> As problem seems to be linked to this one, don't think a new issue is required.
> 
> **macOS 10.15 Catalina... dark mode**
> 
>     * KeePassXC - Version 2.4.3
> 
>     * Revision: [5d6ef0c](https://github.com/keepassxreboot/keepassxc/commit/5d6ef0c47191f1bd9e8ae296920357aeb74e8fd5)
> 
> 
> Input field background and font color are the same so it's unreadable...
> 
> ![KeePassXC 2019-10-20 11-10-25](https://user-images.githubusercontent.com/298526/67157298-983fba00-f32a-11e9-8578-381111b2299d.png)

**Comment by mrbenjoi** [comment]
Might it be possible to simply make KeepassXC not show entries with references in a "dimmed" fashion? Is this an explicitly desired behaviour or could we just decide to not have it and display entries with references just like normal entries?

This would change to code to something like this:

```cpp
    } else if (role == Qt::ForegroundRole) {
        if (entry->foregroundColor().isValid()) {
            return QVariant(entry->foregroundColor());
        } else {
            return QVariant(p.color(QPalette::Active, QPalette::Whatever));
        }
    }
```

If thats not possible, then I guess the color pallete "mid" for dark themes must be adapted.

> This appears to be the relevant code:

**Comment by droidmonkey** [comment]
We already use the palette color. The code is exactly: `return QVariant(p.color(QPalette::Active, QPalette::Mid));`

Therefore, if your theme doesn't display that correctly it is a theme issue, not our issue.

**Comment by stingray21** [comment]
Could you please be a little more specific what the problem with the theme is (and maybe even provide a hint on how to fix it)? 
I am running Manjaro with Gnome and I tried many different themes (light and dark, different qt themes with Kvantum and different Gnome themes with Gnome Tweaks), the entries with references are always very hard to read.

**Comment by droidmonkey** [comment]
The color selection for Active//Mid is too dark

**Comment by stingray21** [comment]
Thanks, and that is in the qt theme?

**Comment by droidmonkey** [comment]
Sweet

**Comment by droidmonkey** [comment]
Sweet

**Comment by thePanz** [comment]
@stingray21 could you share how you altered that color setting? can not find the "dim" colors in my KDE settings

**Comment by stingray21** [comment]
> @stingray21 could you share how you altered that color setting? can not find the "dim" colors in my KDE settings

I used qt5ct to change the color settings. In qt5ct (Qt5 Configutation Tool or Qt5 Settings in Gnome):
- In the section Appearance: I have the *Style* set to *kvantum* 
- Also in Appearance: Select under *Palette* the *Custom* and select a *Color scheme*
- In the *"..."* menu: choose *Create a copy*, then open the menu again and choose *Edit*
- The *Palette Editor* open and you can set the colors the way you want. In my case, I had to change *Less dark*

These steps change the font colors for the reference entries, at least for the currently open instance of KeepassXC after I hit *Apply*. 
Unfortunately, once I restart KeepassXC, it's the previous font color again. So if you find a way to make it persistent, let me know.
