### ISSUE TITLE
Ubuntu: can't launch keepassxc desktop

### ISSUE THREAD

**Issue by Eleonore9** [keepassxreboot/keepassxc#3204]
On Ubuntu 18.04.2 can't open KeePassXC desktop app

## Expected Behavior
Expect to launch KeePassXC desktop app by clicking on the icon on the dock or by running `keepassxc` on the command line.

## Current Behavior
* upon clicking the icon on the dock, I can see a loading icon at first, then nothing happens,
* upon running `keepassxc` on the command line I get:
```
$ keepassxc
/snap/keepassxc/348/usr/bin/keepassxc: error while loading shared libraries: libqrencode.so.3: cannot open shared object file: No such file or directory
```
It used to launch fine until today, but I have been having troubles saving new entries in KeePassXC lately (see [thread](https://twitter.com/EleonoreMayola/status/1128631430416879617)) which I didn't report as a new issue here.

## Possible Solution
`libqrencode.so.3` and `libqrencode-dev` are installed:
```
$ sudo apt install libqrencode3
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libqrencode3 is already the newest version (3.4.4-1build1).
```
```
$ sudo apt install libqrencode-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libqrencode-dev is already the newest version (3.4.4-1build1).
```
I guess they're not where they're expected to be. 

```
$ sudo find / -iname libqrencode*
/usr/share/doc/libqrencode-dev
/usr/share/doc/libqrencode3
/usr/lib/x86_64-linux-gnu/libqrencode.so
/usr/lib/x86_64-linux-gnu/libqrencode.so.3
/usr/lib/x86_64-linux-gnu/pkgconfig/libqrencode.pc
/usr/lib/x86_64-linux-gnu/libqrencode.so.3.4.4
/var/lib/dpkg/info/libqrencode-dev.md5sums
/var/lib/dpkg/info/libqrencode3:amd64.triggers
/var/lib/dpkg/info/libqrencode3:amd64.list
/var/lib/dpkg/info/libqrencode3:amd64.shlibs
/var/lib/dpkg/info/libqrencode-dev.list
/var/lib/dpkg/info/libqrencode3:amd64.symbols
/var/lib/dpkg/info/libqrencode3:amd64.md5sums
/snap/keepassxc/267/usr/lib/x86_64-linux-gnu/libqrencode.so.3
/snap/keepassxc/267/usr/lib/x86_64-linux-gnu/libqrencode.so.3.4.4
/snap/keepassxc/267/usr/share/doc/libqrencode3
``` 

There's a symbolic link pointing to `/snap/keepassxc/267/` that maybe should point to `/snap/keepassxc/348/`.

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1. run `keepassxc`
2.
3.

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )
I can't access most of my passwords. Luckily I had an older version of my database exported to CSV saved somewhere.

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.4.1
Revision: REVISION

Libraries:
- LIBS

Operating system: Ubuntu 18.04.2
CPU architecture: 64-bit
Kernel: Linux 4.15.0-50-generic

Enabled extensions:
- EXTENSIONS

**Comment by acesabe** [comment]
Same here. Looks like same as #3203 reported earlier.

**Comment by droidmonkey** [comment]
I rolled back the snap version. Launchpad is currently broken....
