### ISSUE TITLE
It's too troublesome to upgrade keepassxc

### ISSUE THREAD

**Issue by happyZYM** [keepassxreboot/keepassxc#3208]
I'll lose all my settings if I use the upgrade package to overwrite the installation directory.

**Comment by happyZYM** [comment]
Can it upgrade automatically?

**Comment by droidmonkey** [comment]
Don't delete the issue template. What OS are you using? What installation package are you using for that OS?

**Comment by happyZYM** [comment]
@droidmonkey 
OS: Windows10 X64
installation package: KeePassXC-2.4.2-Win64-portable

**Comment by droidmonkey** [comment]
If you are using the portable version it is incumbent upon you to copy your settings to the next portable version. Just copy keepassxc.ini from the main directory.
