### ISSUE TITLE
macOS - Can't connect database + keepassxc-proxy cannot be opened

### ISSUE THREAD

**Issue by ko-dever** [keepassxreboot/keepassxc#3209]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Expected Behavior
Be able to connect a database and use the extension with the desktop app as intended.

## Current Behavior
1. Each time I open my browser, I get the following error :
![keepassxc-proxy](https://user-images.githubusercontent.com/4114656/58768493-0bbb7780-8594-11e9-9681-5e278f51a3dc.png)

2. In the extension's settings, clicking on the button "Connect" the tab "Connected Databases" does nothing.

## Possible Solution
-

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1. Install the desktop app : `brew cask install keepassxc`
2. Install the browser extension (in my case Chromium) : https://chrome.google.com/webstore/detail/keepassxc-browser/oboonakemofpalcgghocfoadofidjkkk
3. Enable **Browser Integration** in the desktop app
4. Open extension's setting and try to connect a database

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )
Before creating this Issue I was using the desktop app v2.4.1 + the browser extension v1.4.4 and everything was working fine.
I just upgraded them to v2.4.2 and v.1.4.6 and I get these errors.

I tried to uninstall/uninstall the extension, close the browser, disable **Browser Integration**, close the desktop etc. No change.

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.4.2
Revision: a775031

Qt 5.12.3
Debugging mode is disabled.

Operating system: macOS Mojave (10.14)
CPU architecture: x86_64
Kernel: darwin 18.6.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
- libgcrypt 1.8.4

**Comment by droidmonkey** [comment]
There was a deployment error in our macos build pipeline. The proxy application is looking for libsodium in the wrong directory. You can either downgrade to 2.4.1 or install homebrew (https://brew.sh) then install libsodium using ```brew install libsodium```

We cannot publish a new macOS release until next week. The lead maintainer with the signing key is AFK.

**Comment by varjolintu** [comment]
Another workaround is to use `install_name_tool` for fixing the linking:

```
install_name_tool -change /usr/local/opt/libsodium/lib/libsodium.23.dylib "@executable_path/../Frameworks/libsodium.23.dylib" /Applications/KeePassXC.app/Contents/MacOS/keepassxc-proxy
```

**Comment by droidmonkey** [comment]
Note that using the name tool will invalidate the app signature and prevent use of touchid. It might also impact Auto-Type

**Comment by ttimasdf** [comment]
Looks like you have the `brew`. So `brew install libsodium` will be okay.
