### ISSUE TITLE
Setting a custom password length gets arbitrarily changed

### ISSUE THREAD

**Issue by elsesiy** [keepassxreboot/keepassxc#3211]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Setting a custom password length of 32 chars should not be changed to 92.

## Current Behavior
[NOTE]: # ( Tell us what actually happens )
Manually setting the length to 32 is only possible after removing the automatic override of 32 with 92.

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1. Open an entry and modify it's password.
2. Select a length of 32.
3. See length of 92.

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )
I'm changing a lot of old passwords right now and while setting my new ones to longer sequences if possible, I noticed this issue.

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.4.2
Revision: a775031

Qt 5.12.3
Debugging mode is disabled.

Operating system: macOS Mojave (10.14)
CPU architecture: x86_64
Kernel: darwin 18.2.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
 libgcrypt 1.8.4

**Comment by droidmonkey** [comment]
I am confused by this report. Can you be more specific about the exact steps you take and the conditions it occurs? When you are editing an entry we do set the length in the password generator to the length of the current password. Beyond that, there is nothing setting the length besides what you move the slider to.

**Comment by elsesiy** [comment]
I‘m sorry it‘s not clear enough. I‘m not using the slider but set the number manually in the respective text field. I can create a screencast if that helps?

**Comment by droidmonkey** [comment]
Sure would love to see a screencast. Be sure not to show any real information.

**Comment by elsesiy** [comment]
@droidmonkey It looks like someone removed the disk image for MacOS from the releases page so I need to wait until tomorrow to get a hold of my other machine where I installed it already.

**Comment by droidmonkey** [comment]
Yes that was me and on purpose. We didn't change anything related to the password generator in 2.4.2 so you should be able to relocate on 2.4.1 if it is a bug.

**Comment by elsesiy** [comment]
@droidmonkey Not sure why this was happening but I can't reproduce it anymore at the moment. I'll reopen if I can reliable show how to reproduce it. Thanks!

**Comment by droidmonkey** [comment]
I have a tickler in my todo list to look over the whole password generator code, it is not very good or extensible.
