### ISSUE TITLE
The GPL is not an EULA

### ISSUE THREAD

**Issue by ospalh** [keepassxreboot/keepassxc#3212]
## Expected Behavior

Mention of the GPL in passing, if at all, during installation.

## Current Behavior

The Windows MSI installer makes users agree to the General Public *License* as if it were a license *agreement*, which it is not.
![keepassxc_agree_gpl_crop](https://user-images.githubusercontent.com/1690429/58789117-a8f6ca00-85ed-11e9-95a9-c430a2e8a9e6.png)

## Possible Solution

Change the installer so it runs without the user agreeing to the not-agreement.

## Steps to Reproduce

1. Run the windows installer
2. See the screen treating the GPL like an EULA

## Context

This behavior is [not forbidden](https://www.gnu.org/licenses/gpl-faq.en.html#ClickThrough), but an unnecessary annoyance.

There is a whole [Tumblr blog](https://gpleula.tumblr.com/) dedicated to this.

## Debug Info

KeePassXC - Version 2.4.2
Revision: a775031

Qt 5.12.3
Debugging mode is disabled.

Operating system: Windows 10 (10.0)
CPU architecture: x86_64
Kernel: winnt 10.0.17134

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.4

**Comment by droidmonkey** [comment]
This is just an artifact of the installer presets...

**Comment by droidmonkey** [comment]
And I kind of do want you to read, understand, and agree to what is written, specifically sections 15 and 16.
