### ISSUE TITLE
There is no 2.4.2 dmg for macOS on github. 

### ISSUE THREAD

**Issue by rt-krz** [keepassxreboot/keepassxc#3213]
Can't update the keeppassx through the brew because of lack of the package:
Error: Download failed on Cask 'keepassxc' with message: Download failed: https://github.com/keepassxreboot/keepassxc/releases/download/2.4.2/KeePassXC-2.4.2.dmg

**Comment by varjolintu** [comment]
See https://github.com/keepassxreboot/keepassxc/issues/3209
