### ISSUE TITLE
Minimize to tray not working anymore

### ISSUE THREAD

**Issue by ArchangeGabriel** [keepassxreboot/keepassxc#3214]
## Expected Behavior

Minimizing with “Minimize to tray” active should… well, minimize to tray.

## Current Behavior

Minimize to taskbar. Also, clicking on the tray icon to minimize does not work anymore either.

## Debug Info
KeePassXC - Version 2.4.2
Revision: a775031

Qt 5.12.3
Debugging mode is disabled.

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 5.1.6-arch1-1-ARCH

Enabled extensions:
- Auto-Type
- Intégration aux navigateurs
- Agent SSH
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.4

**Comment by drrobotic** [comment]
Can confirm, Left-Clicking on Tray-Icon doesnt minimize to tray anymore. Im also on ArchLinux with XFCE.
@ArchangeGabriel the option "minimize to tray icon" means, that if you close the keepassxc window, it should minimize to tray but not with normal "minimize" button.
