### ISSUE TITLE
Corrupted icon for some websites

### ISSUE THREAD

**Issue by xPaw** [keepassxreboot/keepassxc#3216]
Some favicons turn into a corrupted mess, one specific example is Namecheap: https://www.namecheap.com/favicon.ico

It doesn't matter whether I download in the UI, or manually and then add it as a file, it ends up looking like this:
![03-110637607](https://user-images.githubusercontent.com/613331/58797476-c2593f80-8608-11e9-8f9b-5754e1f908f8.png)

The icon displays fine in the browser, but for some reason it's not actually a valid ICO (trying to open in IfranView also produces an error).

ImageMagick is able to correctly convert the icon (16/32 sizes) into a png by doing `convert favicon.ico test.png` command.

Is there anything that Keepass can do to work this around?

## Debug Info
KeePassXC - Version 2.4.2
Revision: a775031

Qt 5.12.3
Debugging mode is disabled.

Operating system: Windows 10 (10.0)
CPU architecture: x86_64
Kernel: winnt 10.0.18362

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.4

**Comment by droidmonkey** [comment]
It is a Qt bug, I have reported it to them, and it will be fixed when they release Qt 5.12.4

https://bugreports.qt.io/browse/QTBUG-75214
