### ISSUE TITLE
SSH-Agent with GitHub / Codeberg on bash

### ISSUE THREAD

**Issue by Codeberg-AsGithubAlternative-buhtz** [keepassxreboot/keepassxc#3217]
The workflow with ssh-agent and git (GitHub, Codeberg, GitLab, ...) is still unclear for me.
I setup a key pair (incl. passphrase) and the SSH-agent as mentioned here

https://blog.valouille.fr/post/2018-03-27-how-to-use-keepass-xc-with-ssh-agent/

Then I tested (on Debian unstable) with `ssh -vvvT buhtz@codeberg.org`.

What should happen then?
How comes the passphrase from KeePassXC automaticly (?) into my bash/terminal-emulator when ssh (or the git client) ask me for?

The ssh-agent has know the key after opening the database and clicking on "add key to agent".
```
$ ssh-add -l
4096 SHA256:BwvlGY+mEDnswn1q77CDuW0qopTvNSwGlWphLSnFR74 user@vdebian-unstable (RSA)

```
What I can read in this logs is that `ssh` can not find a key-file on my hard-disc. Of course there is now because it is now integreated in my KeePassXC database attached to an entry.
```

debug1: Authentications that can continue: publickey,password
debug3: start over, passed a different list publickey,password
debug3: preferred gssapi-keyex,gssapi-with-mic,publickey,keyboard-interactive,password
debug3: authmethod_lookup publickey
debug3: remaining preferred: keyboard-interactive,password
debug3: authmethod_is_enabled publickey
debug1: Next authentication method: publickey
debug1: Trying private key: /home/user/.ssh/id_rsa
debug3: no such identity: /home/user/.ssh/id_rsa: No such file or directory
debug1: Trying private key: /home/user/.ssh/id_dsa
debug3: no such identity: /home/user/.ssh/id_dsa: No such file or directory
debug1: Trying private key: /home/user/.ssh/id_ecdsa
debug3: no such identity: /home/user/.ssh/id_ecdsa: No such file or directory
debug1: Trying private key: /home/user/.ssh/id_ed25519
debug3: no such identity: /home/user/.ssh/id_ed25519: No such file or directory
debug2: we did not send a packet, disable method
debug3: authmethod_lookup password
```

**Comment by frederickjh** [comment]
@Codeberg-AsGithubAlternative-buhtz  Place the keys' public files in your `~/.ssh/` folder. The ssh agent will then be able to identify them using the public files. In `~/.ssh/config` you can use `IdentityFile ~/.ssh/id_<name of file without .pub>` and also  `IdentitiesOnly yes`. If you are using these keys with a forwarding agent to get to a third computer via a second one, also copy the public keys to the second computer's `~/.ssh` folder.

I had to hunt to find this information, so I hope it helps someone else.

Also the passphrase goes in the password field in KeePassXC. If you want it to ask each time the key is used using sshaskpass, check the _Require user confirmation when this key is used_ box under the **ssh agent** section. KeePassXC will enter the passphrase for you.

**Comment by hifi** [comment]
We're going to improve the documentation soon. I don't know how this issue slipped through unanswered before, sorry for that.
