### ISSUE TITLE
Mac dark mode makes links in pop ups unintelligible

### ISSUE THREAD

**Issue by dpb657** [keepassxreboot/keepassxc#3218]
Just received the update notice for 2.4.2 on my Mac. the link to the KeepassXC website is unreadable with the shade of blue in use and the dark gray background. This is also true for the links in about pop up.

**Comment by droidmonkey** [comment]
This is a Qt issue

**Comment by dpb657** [comment]
Would you please explain what a Qt issue is?

Darryl Baker  (he/him/his)
Sr. System Administrator
Distributed Application Platform Services
Northwestern University
1800 Sherman Ave.
Suite 6-600 – Box #39
Evanston, IL  60201-3715
darryl.baker@northwestern.edu<mailto:darryl.baker@northwestern.edu>
(847) 467-6674

**Comment by droidmonkey** [comment]
Qt is the c++ framework we use to develop KeePassXC. It is responsible for the UI and underlying infrastructure. Theme issues are the responsibility of this framework.

**Comment by dpb657** [comment]
Thank you for the explanation. Should I find the Qt project and open a ticket with them? Or do you have a way to pass the issue on to them?

Darryl Baker  (he/him/his)
Sr. System Administrator
Distributed Application Platform Services
Northwestern University
1800 Sherman Ave.
Suite 6-600 – Box #39
Evanston, IL  60201-3715
darryl.baker@northwestern.edu<mailto:darryl.baker@northwestern.edu>
(847) 467-6674

**Comment by droidmonkey** [comment]
There is already an open ticket for this issue. https://bugreports.qt.io/browse/QTBUG-71740

**Comment by dpb657** [comment]
Thank you very much for your assistance in this matter.

Darryl Baker  (he/him/his)
Sr. System Administrator
Distributed Application Platform Services
Northwestern University
1800 Sherman Ave.
Suite 6-600 – Box #39
Evanston, IL  60201-3715
darryl.baker@northwestern.edu<mailto:darryl.baker@northwestern.edu>
(847) 467-6674
