### ISSUE TITLE
custom URL issues

### ISSUE THREAD

**Issue by Niko-CZ** [keepassxreboot/keepassxc#3219]
## Expected Behavior
- "Open URL" for [ff://http://xxx.com/wp-admin] shall start custom URL handler and open Firefox browser page.
- "Open URL" for [chrome://google.com] shall start custom URL handler and open Chrome browser page.

## Current Behavior
- "Open URL" for [ff://http://{NOTES}/wp-admin], where {NOTES} is equal to [xxx.com]:
<img width="210" alt="image" src="https://user-images.githubusercontent.com/44586336/58812534-c007dd00-862a-11e9-8aad-2d2b1454c15a.png">

	1) special symbol colons disappeared (maybe was not encoded) 
	2) reference was not transferred to value
- "Open URL" for [chrome://google.com]
has no reaction at all.
- "Open URL" for [chrome:////google.com]
is starting custom URL handler and opens Chrome browser page.

From Mac OS terminal following custom URLs are opened in correct way:
	- [open ff://http://xxx.com/wp-admin]
	- [open chrome://google.com]
They are also opened in correct way from MacPass 0.7.3 after double click on URL (same database file).

OS: macOS Mojave 10.14.5
Enabled extensions: None

**Comment by droidmonkey** [comment]
ff://http:// is not a valid URL. If you want to launch specifically Firefox use the cmd:// syntax: ```cmd://firefox http://{NOTES}/wp-admin```

**Comment by Niko-CZ** [comment]
I recall that one of closed bugs/features in 2.4.2 was dedicated to OS handling of URLs
(Fix opening url's with non-http schemes #3153). Description from fix "...Let the OS handle how to open the url...". In this case obviously handling was no handover-ed to OS, which is able to run "open ff://http://xxx.com/wp-admin". 
Is it possible to simplify custom URL handling with following logic:
analyze URL string [<URL>://<command>]
If <URL> is custom --> run OS command [open <URL>://"<command>"]
?

**Comment by SohamG** [comment]
I honestly didn't even know about `ff://` and `chrome://` when I started the PR

I did some investigating (Ubuntu 18.04 with backports): 
 - `xdg-open ff://https://youtube.com` opens default browser (firefox) with the string `ff://https://youtube.com` in the default search engine (here `ff://` can be any random string, same result)
 - `xdg-open chrome://https://youtube.com` started a new instance of default browser, at the home page
 - I did some digging into the .desktop files provided by both
     - firefox.desktop is set to handle chrome:// urls, but not ff://
     - google-chrome.desktop is set to handle neither chrome:// not ff://
     - "set to handle" means using `x-scheme-handler/<scheme>` in the `MimeTypes=` field in the desktop file
 - I had the EXACT same results attempting to open ff:// and chrome:// through keepassxc.

All this leads me to believe this has something to do with Qt-MacOS interfacing, as on my system my OS is handling the urls. Further emphasized by `ff://` not being handled by either browser. I don't know really where to go from here

**Comment by Niko-CZ** [comment]
Well... Dont know how to help with it. Maybe only to reference MacPass 0.7.3 which is able to open URLs in the same way OS does.

**Comment by Niko-CZ** [comment]
Also tested with standard URL "ssh".
For macOS 10.14.5 it looks like slashes shall be escaped (and most probably other special symbols) in Qt call.
- ssh://<ip> - do not work
- ssh:////<ip> - works

**Comment by SohamG** [comment]
Further evidence of it being a Qt --> Mac interface issue, I had explicitly tested ssh:// (and steam://) before opening the PR. Makes me wonder if its an upstream bug/quirk, based on no mention of any of this in the [QUrl class docs](https://doc.qt.io/qt-5/qurl.html) and [QDesktopServices class](https://doc.qt.io/qt-5/qdesktopservices.html#openUrl)

About MacPass, it only targets macOS (and is written in objective c) where as keepassxc targets (through Qt) mac windows and linux, so I don't think it can be used as reference

**Comment by droidmonkey** [comment]
Interesting, I'll run this through the debugger on mac later.

**Comment by SohamG** [comment]
Wonder if https://github.com/keepassxreboot/keepassxc/pull/3264 fixes this

**Comment by alxdlv** [comment]
How do you create custom URL handlers in MacOS?

**Comment by Niko-CZ** [comment]
> How do you create custom URL handlers in MacOS?
simple way: 1) create apple script which will handle custom URLs. 2) generate application from it 3) Put all URLs which you want to associate with it in Info.plist
*Btw you may find all you need on 1st results Google page for "mac os custom url".

**Comment by khzied** [comment]
Hello,
Any news I cannot open url with another browser than the default one.
MacOS 10.15
KeePassXC : 2.6
