### ISSUE TITLE
Installation on fedora fails with a file conflict

### ISSUE THREAD

**Issue by psoberoi** [keepassxreboot/keepassxc#322]
When installing on fedora using the bugzy/keepassxc repo, I get a file conflict:

$ sudo dnf copr enable bugzy/keepassxc

$ sudo dnf install keepassxc
...
Running transaction check
Transaction check succeeded.
Running transaction test
The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing 'dnf clean packages'.
Error: Transaction check error:
  file /usr/share/mimelnk/application/x-keepass2.desktop from install of keepassxc-2.1.1-4.fc25.x86_64 conflicts with file from package keepassx-1:2.0.3-2.fc25.x86_64

Could you rename the file so that it does not conflict with the keepassx package?

**Comment by phoerious** [comment]
We don't maintain the Fedora packages ourselves. Please report those issues to the downstream packager: https://copr.fedorainfracloud.org/coprs/bugzy/keepassxc/
I think, keepassxc should generally be marked as conflicting with keepassx. There is little value in having both installed.

**Comment by psoberoi** [comment]
Thanks - I will file a bug downstream.

It is useful to have both installed, since I want to be able to test drive keepassxc before uninstalling keepassx (and in my quick look so far, I think I did find problems - I'll look at them more closely and file separate bugs for them if appropriate).
