### ISSUE TITLE
Improve Keeshare documentation

### ISSUE THREAD

**Issue by rugk** [keepassxreboot/keepassxc#3220]
[TIP]:  # ( Provide a general summary of the feature in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Summary
[NOTE]: # ( Provide a brief overview of what the new feature is all about )

I have found this quote in the [quickstart docs](https://github.com/keepassxreboot/keepassxc/blob/develop/docs/QUICKSTART.md#technical-details-and-limitations-of-sharing) about KeeShare:
> it is not possible to detect if someone replaced the data with an older version from a valid signer. To prevent this, the container could be placed at a location which is only writeable for valid signers.

I'd challenge that… :smiley: 

So but first, if I understand that correctly, you basically do not protect against replay attacks currently, i.e. an attacker keeping an old share file and adding it again ("replaying" it) to emulate an older version and… don't know… can that delete password entries? 🤔

## Desired Behavior
[NOTE]: # ( Tell us how the new feature should work, be specific )

So actually replay attacks are nothing fancy, but pesky, but have already been accounted for a long time in software updates e.g. The famous [TUF](https://theupdateframework.github.io/) e.g. accounts for that threat (and many others), so you may want to have a look there.

However, some quick ideas I would have:
* just reject _really_, _really_ old updates (<30 days e.g. – when you don't sync your DB in 30 days, you likely have bigger problems with your network or so)
* somehow save old imported share databases and keep a reference for them (some hash) that you later compare against to protect from re-importing. (disadvantage: costs storage space, yeah)
* maybe also just ask the user for too old imports?

## Context

security

## BTW

> the container could be placed at a location which is only writeable for valid signers.

Well… if you do that, you would not need any signing at all likely, so you could forget anything anyway… :laughing: 
Because well… if the file path you configure is trusted and cannot be modified by non-signers due to OS restrictions or so, you don't need to sign that/a signer.

:smile:

**Comment by droidmonkey** [comment]
The merge algorithm will always prefer the newer version of an entry. This means that replacing a database with an older version of it will result in no action on a subsequent import. The only issue here is the way this paragraph is worded.

**Comment by rugk** [comment]
So actually, there is no risk whatsoever? Is that really your assessment? (I don't want to challenge that, you likely know the system better, but just to be sure…)

So about wording: Then why do you suggest a "fix" for a vulnerability/problem that does not exist… this sounds very strange to me…

(also the new issue title is way too generic IMHO)

**Comment by droidmonkey** [comment]
Its the same "risk" as someone replacing a kdbx file anywhere else. There is nothing specific to KeeShare involved here

**Comment by rugk** [comment]
Yeah, but remember that share file may be saved on a publicly accessible file. So it is a different risk considering how the file is used.

Also, if I follow you claim, that would mean I could modify all passwords or delete them all together… (because I can do so by replacing kdbx file). However, you just before denied I can do this…

So hmm… you really need to explain the risks associated with that technology. Maybe also actually explain the advantages of just putting a kdbx file on a shared network location.
And yes, probably a good doc is the best place to do that.

**Comment by droidmonkey** [comment]
Don't confuse file level access with unencrypted database access

**Comment by rugk** [comment]
Another question one have, e.g. is: Does this sharing work, if multiple clients do write changes into the file? (so not only 1:1 sharing/syncing)

**Comment by droidmonkey** [comment]
https://keepassxc.org/docs/KeePassXC_UserGuide.html#_database_sharing_with_keeshare
