### ISSUE TITLE
Neither minimize nor restore down working in 2.4.2 for Windows

### ISSUE THREAD

**Issue by GeronimosLaw** [keepassxreboot/keepassxc#3221]
After installing the 2.4.2 update on windows 10 I wasn't able to see the main program window anymore.

After checking the task manager if KeePassXC was really running I found out that right clicking the sub entry in task manager and choosing 'maximize' brings back the main window or in case KeePassXC was restarted before - the login screen, but as soon as I try to minimize the window or to restore it down then it is gone again and I'm able to get it back via the task manager only

**Comment by dpruth** [comment]
I am also having this issue in Windows 10. The only way I can see the KeePassXC window is if it's fully maximized (which I had to do via the Task Manager). If I try to minimize it or make the window smaller, I can no longer see the window at all. And the preview of the window in my taskbar is a blank white rectangle. I tried updating to 2.4.3, but that hasn't helped.

**Comment by droidmonkey** [comment]
Please provide more details about your computer: resolution(s) used, external monitors, docking station, etc

**Comment by dpruth** [comment]
Well, now that I've submitted a bug it's working perfectly well. A number of Windows updates were installed last night (KB4503327, KB4503308 and KB4465065), so perhaps that fixed whatever issue it was.

**Comment by droidmonkey** [comment]
Since this occurred recently to a few people I would not be surprised if there was a windows 10 incompatibility with Qt 5.12. Hopefully you are correct. I'll leave this open for now

**Comment by omega3** [comment]
After recent update on Manjaro Plasma 5 (Keepasssc 2.4.2) clicking on icon in systemtray does nothing. I need to use option minimize to tray. 

Operating System: Manjaro Linux 
KDE Plasma Version: 5.15.5
KDE Frameworks Version: 5.59.0
Qt Version: 5.12.3
Kernel Version: 5.0.21-1-MANJARO
OS Type: 64-bit

**Comment by droidmonkey** [comment]
2.4.3 corrects that behavior in Linux
