### ISSUE TITLE
When searching, an entry is highlighted, but not actually selected. If it's not selected, it should not appear selected.

### ISSUE THREAD

**Issue by quinncomendant** [keepassxreboot/keepassxc#3222]
In the screenshot below, showing a search in KeePassXC version 2.4.2, there is an entry which is highlighted (in pink), but it is not actually selected. (The root group is also highlighted in the same pink.) When I actually do select that entry ("Wordfence"), it is highlighted in my system's selection color (red).

Does this pink highlighted state have any functionality? Or is it a bug? I find it a problem because it can be mistaken that there is an entry *selected*, but then commands don't work, such as "Copy password", because there is actually nothing selected.

**Screenshot showing the state of the application after doing a search:**

<img width="803" alt="Screen Shot 2019-06-03 at 20 57 04" src="https://user-images.githubusercontent.com/6884276/58846194-fa31a880-8643-11e9-9fdf-862efb66a494.png">

**Screenshot showing the color of the entity after selecting it:**

<img width="843" alt="Screen Shot 2019-06-03 at 21 15 29" src="https://user-images.githubusercontent.com/6884276/58846423-bf7c4000-8644-11e9-8417-a6da9c9a7eb0.png">

**Comment by droidmonkey** [comment]
Its actually a fault in the theme for making the "inactive selection" and "focused selection" colors so close together.

**Comment by quinncomendant** [comment]
This wasn't an issue in 2.3. Since updating, KeePassXC 2.4.2 is the only app on my computer which has a *colored* inactive selection. Version 2.3, and all other apps that I use, have a light grey color for inactive selections. As an example, below I've included screenshots of iTunes with *inactive* and *active* selections.

Can we return inactive selections to grey like they were in 2.3?

<img width="842" alt="Screen Shot 2019-06-03 at 22 14 36" src="https://user-images.githubusercontent.com/6884276/58848706-2ef62d80-864d-11e9-8336-32d1cd297f3b.png">
<img width="842" alt="Screen Shot 2019-06-03 at 22 14 39" src="https://user-images.githubusercontent.com/6884276/58848705-2ef62d80-864d-11e9-877a-3a575e2f2793.png">

**Comment by droidmonkey** [comment]
We don't set the color at all. It is either qt or a theme. You didn't put your OS down. I actually assumed you were on Ubuntu when I saw that screenshot! This would be a Qt issue.

**Comment by quinncomendant** [comment]
I'm on macOS, which doesn't use "themes". Agreed, this must be a qt issue, although I read the qt documentation to see if there was an option to set the inactive selection highlighting, but didn't find anything. 

Since we're discussing qt issues, I have one more to report: the `+` and `-` buttons on the auto-type screen have poor contact on the text color:

<img width="802" alt="Screen Shot 2019-06-04 at 14 47 51" src="https://user-images.githubusercontent.com/6884276/59069356-757d9f00-887c-11e9-8f94-2f0d0d62fd18.png">

**Comment by droidmonkey** [comment]
I can't reproduce either of your issues (10.14.5). I tried multiple different accent and highlight combinations in light mode:

![image](https://user-images.githubusercontent.com/2809491/59069918-d4e0ac80-8886-11e9-9412-c86c14ac09bf.png)

![image](https://user-images.githubusercontent.com/2809491/59069937-e629b900-8886-11e9-97ee-ceaefa5853d9.png)

**Comment by quinncomendant** [comment]
I'm using macos 10.13.6, and haven't customized my system for "custom themes" or anything like that. I have qt 5.12.3 installed via brew (does that matter, since keepassxc comes pre-compiled?)

I just noticed more buttons with white backgrounds:

<img width="365" alt="Screen Shot 2019-06-12 at 14 33 11" src="https://user-images.githubusercontent.com/6884276/59388595-d05a3f00-8d31-11e9-99e4-847f1bbdc0e2.png">
