### ISSUE TITLE
Build fails using static libgcrypt and static libgpg-error

### ISSUE THREAD

**Issue by tuxmaster5000** [keepassxreboot/keepassxc#3223]
The tests of the static libs will passed, so I think the libs are build correct.
But linking it into keepassxc will fails with:

> cd /builddir/build/BUILD/keepassxc-2.4.2/build/src/cli && /usr/bin/cmake3 -E cmake_link_script CMakeFiles/keepassxc-cli.dir/link.txt --verbose=1
> cd /builddir/build/BUILD/keepassxc-2.4.2/build/src && /usr/bin/cmake3 -E cmake_link_script CMakeFiles/keepassxc.dir/link.txt --verbose=1
> /usr/lib64/ccache/c++  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1  -m64 -mtune=generic -fno-common -Wall -Wextra -Wundef -Wpointer-arith -Wno-long-long -Wformat=2 -Wmissing-format-attribute -fvisibility=hidden -fvisibility-inlines-hidden -fstack-protector --param=ssp-buffer-size=4 -fno-exceptions -fno-rtti -Wnon-virtual-dtor -Wold-style-cast -Woverloaded-virtual -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -Werror=format-security -Wcast-align -pie -fPIE -std=c++11 -DNDEBUG  -Wl,-z,relro -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -Wl,--no-add-needed -Wl,--as-needed -Wl,--no-undefined -Wl,-z,relro,-z,now -Wl,--export-dynamic -rdynamic CMakeFiles/keepassxc.dir/main.cpp.o CMakeFiles/keepassxc.dir/keepassxc_autogen/mocs_compilation.cpp.o  -o keepassxc  -L/builddir/build/BUILD/keepassxc-2.4.2/helper/usr/lib64 libkeepassx_core.a libautotype.a browser/libkeepassxcbrowser.a qrcode/libqrcode.a /usr/lib64/libQt5Svg.so.5.9.2 -lqrencode /usr/lib64/libQt5Concurrent.so.5.9.2 -lsodium -lyubikey -lykpers-1 libzxcvbn.a -largon2 ../../helper/usr/lib64/libgpg-error.a -lz sshagent/libsshagent.a /usr/lib64/libQt5Network.so.5.9.2 keeshare/libkeeshare.a /usr/lib64/libQt5Widgets.so.5.9.2 /usr/lib64/libQt5Gui.so.5.9.2 crypto/ssh/libcrypto_ssh.a ../../helper/usr/lib64/libgcrypt.a -lquazip5 /usr/lib64/libQt5DBus.so.5.9.2 /usr/lib64/libQt5Core.so.5.9.2 
> /usr/lib64/ccache/c++  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1  -m64 -mtune=generic -fno-common -Wall -Wextra -Wundef -Wpointer-arith -Wno-long-long -Wformat=2 -Wmissing-format-attribute -fvisibility=hidden -fvisibility-inlines-hidden -fstack-protector --param=ssp-buffer-size=4 -fno-exceptions -fno-rtti -Wnon-virtual-dtor -Wold-style-cast -Woverloaded-virtual -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -Werror=format-security -Wcast-align -pie -fPIE -std=c++11 -DNDEBUG  -Wl,-z,relro -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -Wl,--no-add-needed -Wl,--as-needed -Wl,--no-undefined -Wl,-z,relro,-z,now -rdynamic CMakeFiles/keepassxc-cli.dir/keepassxc-cli.cpp.o CMakeFiles/keepassxc-cli.dir/keepassxc-cli_autogen/mocs_compilation.cpp.o  -o keepassxc-cli  -L/builddir/build/BUILD/keepassxc-2.4.2/helper/usr/lib64 libcli.a ../libkeepassx_core.a ../../../helper/usr/lib64/libgcrypt.a -lsodium -largon2 ../../../helper/usr/lib64/libgpg-error.a -lz ../libzxcvbn.a ../libautotype.a ../browser/libkeepassxcbrowser.a -lsodium ../qrcode/libqrcode.a /usr/lib64/libQt5Svg.so.5.9.2 -lqrencode /usr/lib64/libQt5Concurrent.so.5.9.2 -lyubikey -lykpers-1 -largon2 ../../../helper/usr/lib64/libgpg-error.a -lz ../sshagent/libsshagent.a /usr/lib64/libQt5Network.so.5.9.2 ../keeshare/libkeeshare.a /usr/lib64/libQt5Widgets.so.5.9.2 /usr/lib64/libQt5Gui.so.5.9.2 ../crypto/ssh/libcrypto_ssh.a ../../../helper/usr/lib64/libgcrypt.a -lquazip5 /usr/lib64/libQt5DBus.so.5.9.2 /usr/lib64/libQt5Core.so.5.9.2 
> ../../helper/usr/lib64/libgcrypt.a(random-drbg.o): In function `memset':
> /usr/include/bits/string3.h:81: warning: memset used with constant zero length parameter; this could be due to transposed parameters
> /usr/bin/ld: ../../helper/usr/lib64/libgcrypt.a(libgcrypt_la-visibility.o): undefined reference to symbol 'gpg_strerror'
> //usr/lib64/libgpg-error.so.0: error adding symbols: DSO missing from command line
> collect2: error: ld returned 1 exit status
> make[2]: *** [src/keepassxc] Error 1
> make[2]: Leaving directory `/builddir/build/BUILD/keepassxc-2.4.2/build'
> make[1]: *** [src/CMakeFiles/keepassxc.dir/all] Error 2
> make[1]: *** Waiting for unfinished jobs....
> ../../../helper/usr/lib64/libgcrypt.a(random-drbg.o): In function `memset':
> /usr/include/bits/string3.h:81: warning: memset used with constant zero length parameter; this could be due to transposed parameters
> make[2]: Leaving directory `/builddir/build/BUILD/keepassxc-2.4.2/build'
> [100%] Built target keepassxc-cli
> make[1]: Leaving directory `/builddir/build/BUILD/keepassxc-2.4.2/build'
> make: *** [all] Error 2

Here the complete build log:
[build.log](https://github.com/keepassxreboot/keepassxc/files/3250693/build.log)
OS: CentOS 7.6

**Comment by droidmonkey** [comment]
Why are you even doing this in the first place? Of all libraries, you want your crypto to be shared and independently updated for security reasons.

**Comment by tuxmaster5000** [comment]
This is needed, because libgcrypt is to old on CentOS to build keepassxc.
Only libgcrypt-1.5.3-14.el7.x86_64 is available. So I need to link an new one as static lib on it.

**Comment by droidmonkey** [comment]
Or use the appimage

**Comment by tuxmaster5000** [comment]
This will not possible, because only rpm packages are allowed.

**Comment by droidmonkey** [comment]
Your error is here:
```
../../helper/usr/lib64/libgcrypt.a(libgcrypt_la-visibility.o): undefined reference to symbol 'gpg_strerror' //usr/lib64/libgpg-error.so.0: error adding symbols: DSO missing from command line
```

You need to compile the libraries again or figure out why this function is missing. This is not a KeePassXC concern or issue.

**Comment by tuxmaster5000** [comment]
I have try to change the order, but the result is the same.
This was my patch:

> diff -Nuar keepassxc-2.4.2.org/src/CMakeLists.txt keepassxc-2.4.2/src/CMakeLists.txt
> --- keepassxc-2.4.2.org/src/CMakeLists.txt      2019-06-06 15:09:29.983314299 +0200
> +++ keepassxc-2.4.2/src/CMakeLists.txt  2019-06-06 15:10:30.424994416 +0200
> @@ -277,8 +277,8 @@
>          ${YUBIKEY_LIBRARIES}
>          ${ZXCVBN_LIBRARIES}
>          ${ARGON2_LIBRARIES}
> -        ${GCRYPT_LIBRARIES}
>          ${GPGERROR_LIBRARIES}
> +        ${GCRYPT_LIBRARIES}
>          ${ZLIB_LIBRARIES})
>  
>  if(WITH_XC_SSHAGENT)

**Comment by droidmonkey** [comment]
You might have to move them to the top of the list as well.

**Comment by tuxmaster5000** [comment]
I have  try it, but it also fails.
My new patch.
[keepassxc-cmake.patch2.txt](https://github.com/keepassxreboot/keepassxc/files/3264836/keepassxc-cmake.patch2.txt)

**Comment by droidmonkey** [comment]
At this point I am not sure what to tell you...

**Comment by tuxmaster5000** [comment]
For testing I have used an dynamic version of the libs.
This will work. So it looks like an linking problem of keepassxc when using static libs.

**Comment by tuxmaster5000** [comment]
Now I have the right patch for it.:
```
diff -Nuar keepassxc-2.5.3.org/src/cli/CMakeLists.txt keepassxc-2.5.3/src/cli/CMakeLists.txt
--- keepassxc-2.5.3.org/src/cli/CMakeLists.txt  2020-04-01 12:27:27.176364435 +0200
+++ keepassxc-2.5.3/src/cli/CMakeLists.txt      2020-04-01 13:12:35.460140891 +0200
@@ -51,13 +51,13 @@
 
 add_executable(keepassxc-cli keepassxc-cli.cpp)
 target_link_libraries(keepassxc-cli
+        ${GPGERROR_LIBRARIES}
         cli
         keepassx_core
         Qt5::Core
         ${GCRYPT_LIBRARIES}
         ${sodium_LIBRARY_RELEASE}
         ${ARGON2_LIBRARIES}
-        ${GPGERROR_LIBRARIES}
         ${ZLIB_LIBRARIES}
         ${ZXCVBN_LIBRARIES})
 
diff -Nuar keepassxc-2.5.3.org/src/CMakeLists.txt keepassxc-2.5.3/src/CMakeLists.txt
--- keepassxc-2.5.3.org/src/CMakeLists.txt      2020-04-01 12:27:27.172364396 +0200
+++ keepassxc-2.5.3/src/CMakeLists.txt  2020-04-01 14:37:35.892446377 +0200
@@ -305,9 +305,8 @@
         ${YUBIKEY_LIBRARIES}
         ${ZXCVBN_LIBRARIES}
         ${ARGON2_LIBRARIES}
-        ${GCRYPT_LIBRARIES}
-        ${GPGERROR_LIBRARIES}
-        ${ZLIB_LIBRARIES})
+        ${ZLIB_LIBRARIES}
+       )
 
 if(WITH_XC_SSHAGENT)
   target_link_libraries(keepassx_core sshagent)
@@ -349,6 +348,7 @@
 endif()
 
 add_executable(${PROGNAME} WIN32 ${keepassx_SOURCES_MAINEXE} ${WIN32_ProductVersionFiles})
+target_link_libraries(keepassx_core ${GCRYPT_LIBRARIES} ${GPGERROR_LIBRARIES})
 target_link_libraries(${PROGNAME} keepassx_core)
 
 set_target_properties(${PROGNAME} PROPERTIES ENABLE_EXPORTS ON)
```

**Comment by droidmonkey** [comment]
Cool, can you submit a PR?

**Comment by tuxmaster5000** [comment]
Yes, I will create one as soon as possible.
