### ISSUE TITLE
Make the keepassxc-cli session based

### ISSUE THREAD

**Issue by qwc** [keepassxreboot/keepassxc#3224]
[TIP]:  # ( Provide a general summary of the feature in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Summary
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
The current behaviour of the cli is that you have to issue a command at a time and input the password for your database everytime you issue your command.
I would like to have that session based.

## Desired Behavior
[NOTE]: # ( Tell us how the new feature should work, be specific )
So, if you issue keepassxc-cli, you start a CLI session where you may open a database, enter the password for it, and then work on the database, just like the GUI after all.
And after you type "close" or "quit" the database is closed again and the session terminated.
Also a timeout to automatically close the CLI session might be a good idea, but should be configurable.

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
Well, I'm living on the console with huge tmux sessions, local and on my server, where I would also like to access my credentials for different things. And after all it's cool that KeePassXC provides a CLI, but to always type in your 25-30 character password with every command issued is damn annoying.

**Comment by sjamesr** [comment]
I'm working on a prototype of a readline-based solution, where you'd do something like:

```
$ keepassxc-cli open passwords.kdbx
> ls
Banking/
Internet/
```

The commands understood by the cli shell would be the same as those understood by keepassxc-cli itself.

Subclasses of Command would have a new optional method `suggest` (or something similar), allowing them the opportunity to offer tab completion suggestions.

For systems without readline, the fallback would just be to read from standard input with no fancy features such as editing, history, tab completion, etc.

Would this be of interest?

**Comment by droidmonkey** [comment]
It would make more sense to add a command "shell" which would drop you into this interface. Then you could use the standard commands from there.

**Comment by sjamesr** [comment]
`shell` seems like a fine name for this command too.

I’d like to reuse the existing command parsing code as much as possible. However, QCommandLineParser requires a QStringList of arguments. Since the existing commands rely on the shell to split strings, the `shell` command is probably going to implement splitting differently. This might cause surprises.

Do you have a better idea about how to navigate this issue?

**Comment by droidmonkey** [comment]
Sorry I missed that you introduced the new command `open` in your previous post. That is also appropriate and a little more elegant.

Look at how normal commands are executed:
https://github.com/keepassxreboot/keepassxc/blob/6ae27fa47b070902eabb44ebab68d471eb68d0e9/src/cli/keepassxc-cli.cpp#L86-L98

The argument list is simply a string list which can be obtained by:
```
line = readline();
arguments = line.split(' ')

auto command = Command::getCommand(arguments.takeFirst())
command->execute(arguments)
```

**Comment by sjamesr** [comment]
We'll need to handle filenames and parameters that contain spaces though,
possibly with a backslash escape character. Perhaps people will want to
surround parameters with quotes as well.

**Comment by droidmonkey** [comment]
That is a good point. You can just emulate the functionality of the entire "main" function in keepassxc-cli.cpp. Define a QCommandLineParser with the single command positional argument and pass the remainder onto the execute function.

**Comment by sjamesr** [comment]
You can try out interactive mode now with pull request #3426, it's just a demo but it supports the `ls` and `show` commands, thus it's already quite useful.

Tab completion is just standard readline (i.e. filenames) right now, but I'm planning to extend that with context-aware completion.
