### ISSUE TITLE
Possibility to add Different Login Permission on Same DB ?

### ISSUE THREAD

**Issue by liberodark** [keepassxreboot/keepassxc#3226]
## Summary
Feature for add a single db with users permissions.

## Desired Behavior
My idea is if you have possibility to add multi login on same DB but not same access.

## Possible Solution
For me is probably add limite access on "folders" in db.
And would be great to add user / password access on same db.
A little promt just for create user "toto" & pwd "123"

## Context
That would be a great super feature for what on professional use is not simple to use multiple db for multi access better if you have users need to no see this folder on db.
Is not great to make another db just for that.
And this feature push KeepassXC in too KeepassNext Future :D

**Comment by droidmonkey** [comment]
This is not possible with a single kdbx database because of the way it is architected. This is from the original KeePass program. Something like this is possible with KeeShare.

**Comment by liberodark** [comment]
That be good with keeshare
