### ISSUE TITLE
Support Import/Export of browser bookmarks

### ISSUE THREAD

**Issue by danieru98** [keepassxreboot/keepassxc#3227]
## Summary
KeePassXC already has almost all the features to be a bookmark manager. The only feature missing is support for Import and Export of entries in the netscape's html bookmark format. This should be easy to implement but just for reference keepass support this.

## Desired Behavior
Add an "Import browser bookmarks" menu item just below the "Import CSV" menu item. When clicked it will open a file picker windows configured to filter for .html files. Once the user select an html file with <!DOCTYPE NETSCAPE-Bookmark-file-1> KeePassXC will begin to create a group for each "folder" (\<H3\> tags) with their corresponding name. And a new entry for each bookmark (\<A\> tags). Each field of the entry would be filled with information in the html file, such as the tittle, url and icon.

## Possible Solution
The already implemented CSV Import and Export and XML export could be used a reference on how to implement this. 

## Context
I love being able to access my passwords from any computer using whatever protocol or service I choose (from sftp to dropbox and everything in between) using KeepPassXC. At the same time I hate the idea of using a browser specific service to access my bookmarks over different computers. So, why not just use KeepPassXC as a bookmark manager?

**Comment by droidmonkey** [comment]
We will not be implementing this.

**Comment by wolframroesler** [comment]
Second your decision @droidmonkey. Let's stick to the Unix philosophy of making a tool that does one thing, and does that thing well. Cloud sync (#2631)? Backup version control (#3279)? Bookmark manager? Come on, this is a password manager, not an operating system. Thanks for keeping the project focused.
