### ISSUE TITLE
"Use group icon on entry creation" does not work with blue folder icon

### ISSUE THREAD

**Issue by JitterBugGitterHub** [keepassxreboot/keepassxc#3228]
## Expected Behavior
With the "Use group icon on entry creation" option enabled, the new entry should inherit the group icon. 
![options](https://i.postimg.cc/zvv7t5SB/1559703795-SUk-ZYp-N242nb5-Tq-M.png)

## Current Behavior
This works for **_every_** default icon (and custom icon, too), **_except for_** the blue folder icon:
![icon](https://i.postimg.cc/JnPK5tXv/1559703625-OBm9-KMlg-CBrkwp-W5.png)(click to enlarge)

Using the blue folder icon as a group icon, the newly created entry uses the yellow/golden key icon instead: 
![key](https://i.postimg.cc/fWHDJKVj/1559704940-Fhu7-ODh-Pb-CVA58-E0.png)

## Possible Solution
Can be currently fixed by setting that icon ("**[...]\KeePassXC\share\icons\database\C48_Folder.png**") as a custom icon for the group:
![custom](https://i.postimg.cc/LsBh71NC/1559705341-F10s1-Jv9-IFK1q-JAT.png)

That way a newly created entry successfully inherits the group icon.

## Steps to Reproduce
1. Turn on the "Use group icon on entry creation" option
2. Create a new group, using the blue folder as the group icon (should be the default one anyway)
3. Create a new entry

## Debug Info
KeePassXC - Version 2.4.2
Revision: a775031

Qt 5.12.3
Debugging mode is disabled.

Operating system: Windows 10 (10.0)
CPU architecture: x86_64
Kernel: winnt 10.0.18362

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.4

**Comment by droidmonkey** [comment]
Personally I find this to be a feature not a bug.

**Comment by JitterBugGitterHub** [comment]
It still makes that setting inconsistent. And even if you say it doesn't make sense to use a folder icon for an entry, all the other default folder icons are still used for entries.

Anyway, this is definitely not something of high priority. Just wanted to put this out there for people like me who like to use that icon for entries and might wonder why it's not working. :D

Best regards.

**Comment by droidmonkey** [comment]
Although I do agree if you manually set the icon then it should work. Just not the auto-icon because I would argue the majority of users would not want that one icon to propogate to entries.
