### ISSUE TITLE
The dll in the created package is not loaded properly

### ISSUE THREAD

**Issue by glowcat** [keepassxreboot/keepassxc#3229]
## Expected Behavior
The path of dll loaded from exe executed after build is different from the intended one

## Current Behavior
It occurs in the windows version.
Build and make a package.
Unzip the created package zip and execute exe inside.
Various dlls are copied to the internal folder when creating a package, but dlls are not read from those folders but from msys64.
When I brought the package to another PC, if there is an msys environment and there is a different version of dll, I can not start it properly.
(If you change the folder name of msys64 etc., it will be read correctly)

The following is the output of dll loaded by windbg

```
odLoad: 00000000`6dcc0000 00000000`6ddc7000   C:\msys64\mingw64\share\qt5\plugins\platforms\qwindows.dll
ModLoad: 00000000`70cc0000 00000000`70cf4000   C:\msys64\mingw64\share\qt5\plugins\styles\qwindowsvistastyle.dll
ModLoad: 00000000`77a30000 00000000`77a37000   C:\Windows\system32\psapi.DLL
ModLoad: 00000000`65100000 00000000`65113000   C:\msys64\mingw64\share\qt5\plugins\imageformats\qgif.dll
ModLoad: 00000000`635c0000 00000000`635d5000   C:\msys64\mingw64\share\qt5\plugins\imageformats\qicns.dll
ModLoad: 00000000`6f380000 00000000`6f393000   C:\msys64\mingw64\share\qt5\plugins\imageformats\qico.dll
ModLoad: 00000000`6c1c0000 00000000`6c1d3000   C:\msys64\mingw64\share\qt5\plugins\imageformats\qjp2.dll
ModLoad: 00000000`03260000 00000000`032dd000   C:\msys64\mingw64\bin\libjasper-4.dll
ModLoad: 00000000`6b800000 00000000`6b83d000   C:\Program Files (x86)\GtkSharp\2.12\bin\libjpeg-8.dll
ModLoad: 00000000`65580000 00000000`65622000   C:\msys64\mingw64\bin\libjpeg-8.dll
ModLoad: 00000000`6cdc0000 00000000`6cdd6000   C:\msys64\mingw64\share\qt5\plugins\imageformats\qjpeg.dll
ModLoad: 00000000`6cac0000 00000000`6cad1000   C:\msys64\mingw64\share\qt5\plugins\imageformats\qmng.dll
ModLoad: 00000000`64e40000 00000000`64ebf000   C:\msys64\mingw64\bin\libmng-2.dll
ModLoad: 00000000`05160000 00000000`051c5000   C:\msys64\mingw64\bin\liblcms2-2.dll
ModLoad: 00000000`65fc0000 00000000`65fd1000   C:\msys64\mingw64\share\qt5\plugins\imageformats\qsvg.dll
ModLoad: 00000000`6d980000 00000000`6d9d2000   C:\msys64\mingw64\bin\Qt5Svg.dll
ModLoad: 00000000`6e7c0000 00000000`6e7d1000   C:\msys64\mingw64\share\qt5\plugins\imageformats\qtga.dll
ModLoad: 00000000`008e0000 00000000`008f4000   C:\msys64\mingw64\share\qt5\plugins\imageformats\qtiff.dll
ModLoad: 00000000`68ec0000 00000000`68f33000   C:\Program Files (x86)\GtkSharp\2.12\bin\libtiff-5.dll
ModLoad: 00000000`68ec0000 00000000`68f3e000   C:\msys64\mingw64\bin\libtiff-5.dll
ModLoad: 00000000`63cc0000 00000000`63cee000   C:\Program Files (x86)\GtkSharp\2.12\bin\liblzma-5.dll
ModLoad: 00000000`63cc0000 00000000`63cec000   C:\msys64\mingw64\bin\liblzma-5.dll
ModLoad: 00000000`64d80000 00000000`64e30000   C:\msys64\mingw64\bin\libzstd.dll
ModLoad: 00000000`63400000 00000000`63411000   C:\msys64\mingw64\share\qt5\plugins\imageformats\qwbmp.dll
ModLoad: 00000000`65200000 00000000`65212000   C:\msys64\mingw64\share\qt5\plugins\imageformats\qwebp.dll
ModLoad: 00000000`61940000 00000000`619b8000   C:\msys64\mingw64\bin\libwebp-7.dll
ModLoad: 00000000`6bbc0000 00000000`6bbcf000   C:\msys64\mingw64\bin\libwebpdemux-2.dll
```

In the portable version dll is loaded from the correct location, so I want to know how to do the same.

```
ModLoad: 00000000`6dcc0000 00000000`6ddbb000   I:\keepassxc\KeePassXC-2.3.4-Win64\platforms\qwindows.dll
ModLoad: 00000000`70cc0000 00000000`70cf4000   I:\keepassxc\KeePassXC-2.3.4-Win64\styles\qwindowsvistastyle.dll
ModLoad: 00000000`77a30000 00000000`77a37000   C:\Windows\system32\psapi.DLL
ModLoad: 00000000`77a30000 00000000`77a37000   C:\Windows\system32\psapi.DLL
ModLoad: 00000000`65100000 00000000`65113000   I:\keepassxc\KeePassXC-2.3.4-Win64\imageformats\qgif.dll
ModLoad: 00000000`635c0000 00000000`635d5000   I:\keepassxc\KeePassXC-2.3.4-Win64\imageformats\qicns.dll
ModLoad: 00000000`6f380000 00000000`6f393000   I:\keepassxc\KeePassXC-2.3.4-Win64\imageformats\qico.dll
ModLoad: 00000000`6cdc0000 00000000`6cdd5000   I:\keepassxc\KeePassXC-2.3.4-Win64\imageformats\qjpeg.dll
ModLoad: 00000000`6b800000 00000000`6b83d000   C:\Program Files (x86)\GtkSharp\2.12\bin\libjpeg-8.dll
ModLoad: 00000000`65580000 00000000`65622000   C:\msys64\mingw64\bin\libjpeg-8.dll
ModLoad: 00000000`65200000 00000000`65212000   I:\keepassxc\KeePassXC-2.3.4-Win64\imageformats\qwebp.dll
ModLoad: 00000000`61940000 00000000`619b8000   C:\msys64\mingw64\bin\libwebp-7.dll
ModLoad: 00000000`6bbc0000 00000000`6bbcf000   C:\msys64\mingw64\bin\libwebpdemux-2.dll
ModLoad: 00000000`6c440000 00000000`6c49d000   I:\keepassxc\KeePassXC-2.3.4-Win64\libkeepassx-autotype-windows.dll

```

## Debug Info
KeePassXC - Version 2.3.4
Revision: 6fe821c

Libraries:
- Qt 5.11.1
- libgcrypt 1.8.3

Operating system: Windows 7 SP 1 (6.1)
CPU architecture: x86_64
Kernel: winnt 6.1.7601

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by droidmonkey** [comment]
First off, update to 2.4.2 there are changes made to build/deploy.

After build issue command: ```cpack -G ZIP``` and everything will work.

**Comment by glowcat** [comment]
thanks.

Is there a way to do the same thing in the 2.3.4 environment?
I want to create a similar environment because the dll is loaded without problems in the portable version of 2.3.4.

**Comment by droidmonkey** [comment]
On Windows, the dll search order is: 1. Directory where exe is located 2. Path env var 3. Probably some hard coded system32 lookups

**Comment by glowcat** [comment]
thanks.

I checked, but it seems that the dll itself is correctly copied to the folder with exe.

This also suffers from that, for example, when msys64 is renamed to msys64_ etc., dll inside exe will be loaded correctly.

What I do not know well is that, for example, "C:\msys64\mingw64\share\qt5\plugins\" is referred to preferentially even though it does not pass through the path.

What's bothersome is that if you're in 2.3.4 or the portable version, you'll read dll inside exe correctly (even if the msys path is set), but how is this package created? Is there?

We believe that if you can do the same at build time you may be able to solve the problem.

**Comment by droidmonkey** [comment]
I really don't know what to say except just use the portable version in the official release. We can't offer build/deploy support beyond what we already do for releases.
