### ISSUE TITLE
KeePassXC across machines, different DB?

### ISSUE THREAD

**Issue by ossii79** [keepassxreboot/keepassxc#3230]
This might just be me that doesn't understand KeePassXC..
I have stored the database on my google drive storage.
I unlock the db on my linux workstation usually, but I also open it on my windows PC as well.
I use a password + a keyfile to unlock it.

However changes I have made while using my linux workstation, isn't reflected over to what I see on the windows PC.
Right now I sit on my windows PC and I had to reset my github password, because the one in keepassxc didn't work.
Not so long ago I reset my email address as well as password from the linux machine, but now on windows PC it only had my old email address stored.

Even I save the DB on the linux machine and open it a week later, all changes I have done are there. Same with the fact that after I recently reinstalled the linux workstation, all recent changes where present in the DB.

I rely havily on the firefox plugin and using different browser IDs, like LinuxWS, WindowsWS etc.

Shouldn't this work? Am I experiencing some weird google drive sync issue, more than KeePassXC issue?

-Osi

**Comment by droidmonkey** [comment]
Sounds like your linux machine is not syncing to the google drive

**Comment by DarthFutuza** [comment]
@ossii79 Have you verified that the file itself on Google Drive actually changes when you edit the database on the linux machine?  (Like if you login with a browser, does it actually sync and change?)

**Comment by ossii79** [comment]
Well since I recently reinstalled the OS on the linux box and where able to see all recent additions to the db I assume the linux side is all good. If KeePassXC should have handled this just fine Ill go ahead and blame windows and the google drive client.

**Comment by droidmonkey** [comment]
You have some basic testing to do. Try syncing a simple text file to see if all works

**Comment by ossii79** [comment]
Aye, this seemed to have been a google drive issue on windows. I uninstalled google drive and reinstalled it, now suddenly I got a whole different (and correct...) database.
Then I know this should have worked :) case closed
