### ISSUE TITLE
Version 2.4.0 breaks theming on GNU+Linux, not fixed in 2.4.2

### ISSUE THREAD

**Issue by psvenk** [keepassxreboot/keepassxc#3231]
I am running the latest version of KeePassXC on Arch Linux, installed by `pacman` from the official repositories. After updating to 2.4.0, I saw that KeePassXC stopped using its own icons in some places but instead used the system icon theme, which made the interface inconsistent and ambiguous. I waited until 2.4.2 because #3057 seems to have fixed it for Snap packages, but I continue to face this issue after upgrading to 2.4.2. All of my packages are up to date. This issue is a continuation of <https://github.com/keepassxreboot/keepassxc/pull/3057#issuecomment-498874246>.

<a name="452573975-expected-behavior" id="452573975-expected-behavior"></a>

## Expected Behavior
KeePassXC either uses its own icons everywhere, or detects the system icon theme and uses icons that look native to that icon theme but are not ambiguous or inconsistent.

## Current Behavior

I tested with the following icon themes:
- Bluecurve (my default, and the default on Fedora many years ago)
- Adwaita (GNOME 3's default)
- GNOME (GNOME 2's default)
- Breeze (KDE Plasma's default)
- Humanity (Ubuntu's default)

With each of these icon themes, with the exception of Adwaita, KeePassXC's icons were inconsistent or ambigous. I will now go in depth about the issues that I noticed.
- In Bluecurve, GNOME 2, and Humanity, the "lock database" icon is a generic file icon instead of a lock icon.
- In Bluecurve, Breeze, and Humanity, the "copy username", "copy password", and "copy URL" icons are not consistent.
- In Humanity, the "search" icon is a computer icon instead of a magnifying glass.
- In Bluecurve and Humanity, "copy password" and "password generator" use the same system icon.

Bluecurve:
![Bluecurve](https://user-images.githubusercontent.com/45520974/58919100-de3d0e00-86fa-11e9-8d0a-39bb647bdcd2.png)

Adwaita:
![Adwaita](https://user-images.githubusercontent.com/45520974/58919099-de3d0e00-86fa-11e9-988e-5d0b0036da31.png)

GNOME 2:
![GNOME 2](https://user-images.githubusercontent.com/45520974/58919102-de3d0e00-86fa-11e9-8815-4677dd66f232.png)

Breeze:
![Breeze](https://user-images.githubusercontent.com/45520974/58919101-de3d0e00-86fa-11e9-9e88-8101bcd39f27.png)

Humanity:
![Humanity](https://user-images.githubusercontent.com/45520974/58919103-ded5a480-86fa-11e9-9062-50feec2f5e09.png)

## Possible Solution
See [Expected Behavior](#452573975-expected-behavior).

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1. `sudo pacman -R keepassxc`
2. `sudo pacman -S keepassxc`

(or the equivalent commands for your package manager)

## Debug Info
KeePassXC - Version 2.4.2
Revision: a775031

Qt 5.12.3
Debugging mode is disabled.

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 5.1.6-arch1-1-ARCH

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.4

**Comment by phoerious** [comment]
We have always relied on the system theme, nothing has changed here. If certain icons look different, then its because they are missing in your system's icon theme. We try to use the icons that work best, but sometimes themes have very different icons than others, which we cannot do anything about.

**Comment by droidmonkey** [comment]
I think this warrants some debugging to understand why some themes are giving wildly different icon "types" for the requested icon.

**Comment by psvenk** [comment]
As to @phoerious's comment saying that KeePassXC has always behaved like this, here is a screenshot of 2.3.4 on my system with the Bluecurve icon theme (from my [`pacman` cache](https://wiki.archlinux.org/index.php/Downgrading_packages), but originally from the official Arch repositories):

![Screenshot at 2019-06-05 21-57-05](https://user-images.githubusercontent.com/45520974/59001560-03a24880-87dd-11e9-803e-e28897df32e9.png)

The icons that are commonly found in icon themes (new file, open, save) are the system ones, while the ones that are unlikely to be in the icon theme are the ones provided by KeePassXC. I'm not sure what caused the change in 2.4.0.

**Comment by bungabunga** [comment]
Exactly the same behaviour here on Ubuntu 19.04.

**Comment by droidmonkey** [comment]
The only PR I can think of that impacted the icons for 2.4.0 is this one: https://github.com/keepassxreboot/keepassxc/pull/2113
