### ISSUE TITLE
Keepassxc won't save changes after I log off.

### ISSUE THREAD

**Issue by swalls62** [keepassxreboot/keepassxc#3234]
I have Ubuntu 16.04. KeePassXC stopped saving changes to database entries after I quit. When I apply changes or new entries, it says it's saved and as long as I don't quit the session, they are good. But, when I quit and reopen, everything is the same as it was before I made the edits.

**Comment by droidmonkey** [comment]
Where are you saving your database? Network share? Home directory?

What installation method are you using? Snap? Flatpak? Appimage? Distro repository?

What version are you running?

When did this start happening? Has it always happened? Did you install some OS update or major software change?

You need to provide way more detail.

**Comment by swalls62** [comment]
Database is in Home folder.

Since it is in the Snap folder, I would assume was done with Snap.

I originally downloaded it from the Ubuntu Software Center.

Version Ubuntu 16.04.6 LTS

Have updated KeepassXC to the latest version

When I first noticed this happening was on April 5, 2019. Up til then

it worked flawlessly.

I personally think that an update from Ubuntu possibly caused this as no other changes

were made at that point. I updated the KeepassXC recently to maybe help this issue

but to no avail.

I also note that the buttons on KeepassXC dashboard grey out and are unusable

unless I click around.

**Comment by swalls62** [comment]
Database is in Home folder.

Since it is in the Snap folder, I would assume was done with Snap.

I originally downloaded it from the Ubuntu Software Center.

Version Ubuntu 16.04.6 LTS

Have updated KeepassXC to the latest version

When I first noticed this happening was on April 5, 2019. Up til then

it worked flawlessly.

I personally think that an update from Ubuntu possibly caused this as no other changes

were made at that point. I updated the KeepassXC recently to maybe help this issue

but to no avail.

I also note that the buttons on KeepassXC dashboard grey out and are unusable

unless I click around.

**Comment by droidmonkey** [comment]
If you saved into the snap folder... Try looking in the different number folders to see if your database is there. Everytime a snap is updated a new number folder is created and your files are "supposed" to be moved over.

**Comment by swalls62** [comment]
I have 4 folders with the database in them

49 (modified Mar 17) with Passwords.kdbx modified Mar 17

191 (Modified Mar 20) with Passwords.kdbx modified Mar 20

267 (Modified Apr 14) with Passwords.kdbx modified Mar 17 ?

Current (Modified Apr 14) with Passwords.kdbx Modified Mar 17 ?

Not making sense to me. I have updated several times since those dates with no success.

**Comment by droidmonkey** [comment]
Double check where you are storing your database file when in KeePassXC. You can save as to move it into your actual home folder.

**Comment by swalls62** [comment]
Writing to database failed: permission denied.

**Comment by droidmonkey** [comment]
Does it show you that no matter where you try to save it?

**Comment by swalls62** [comment]
Yes it does and also KeepassXC locks up and I have to reboot.

**Comment by swalls62** [comment]
OK I found out what happened. KeepassXC was linked to folder 49 and it said "read only" so I could never change anything. The last time I rebooted and restarted KeepassXC, I had to fill in the database location and I chose the folder location "Current". Now it's normal. Database is open without the "read only" note. Everything works ok now. Thanks for your help!

**Comment by droidmonkey** [comment]
Perfect! Glad it works again
