### ISSUE TITLE
Font size is micro sized

### ISSUE THREAD

**Issue by 0xC1A551C** [keepassxreboot/keepassxc#3235]
## Expected Behavior
Regular readable font-size. It was working previously with no issues.

![Screenshot from 2019-06-05 16-44-56](https://user-images.githubusercontent.com/36227001/58997391-4a7a4900-87b1-11e9-8b71-b23378ccb1a5.png)

## Current Behavior
Font-size is as small as a particle

## Possible Solution
Allow font sizing

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1.
2.
3.

## Context
Unreadable

## Debug Info
KeePassXC - Version 2.3.4
Revision: 6fe821c

Libraries:
- Qt 5.12.2
- libgcrypt 1.8.4

Operating system: Ubuntu 19.04
CPU architecture: x86_64
Kernel: linux 5.1.5-050105-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by droidmonkey** [comment]
See #2815 for some solutions. This is a Qt problem.
