### ISSUE TITLE
Load previously open databases also on Auto-Type

### ISSUE THREAD

**Issue by christianglodt** [keepassxreboot/keepassxc#3237]
When "Load previously open databases on startup" is enabled, but the database can not be opened at startup time, it would be good if it could be opened "on-demand" when Auto-Type is triggered.

I use a single database that is located on a (drive-mapped) network share. Quite often, Windows will fail to re-mount the share to the drive letter on startup. When this happens, KeepassXC will not react to the Auto-Type key until I manually open its window and open the database.

## Expected Behavior
When triggering Auto-Type, the previously opened database should be opened if it could not be opened at startup.

## Current Behavior
There is no reaction when triggering Auto-Type if the previously opened database could not be opened at startup.

## Possible Solution
On Auto-Type, if there is no database open, and the "Load previously opened database" setting is active, retry to open the database.

## Steps to Reproduce
I've not tried these steps, but they should work.
1. (Optional) Clear the history of previously opened databases somehow.
2. Open a database, make sure "Load previously opened databases at startup" is checked.
3. Close KeepassXC
4. Rename the database file to something else.
5. Start KeepassXC
6. Rename the database file back to its original name.
7. Attempt to trigger Auto-Type and nothing happens.

## Debug Info
I've observed the same problem on my Linux and Windows OSes. Here's the debug info of the linux machine:

KeePassXC - Version 2.4.1
Revision: 7bafe65

Qt 5.12.2
Debugging mode is disabled.

Operating system: Ubuntu 19.04
CPU architecture: x86_64
Kernel: linux 5.0.0-16-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.4

**Comment by droidmonkey** [comment]
I can see this behavior causing more harm then good. I don't think this will be implemented.

**Comment by christianglodt** [comment]
> I can see this behavior causing more harm then good. I don't think this will be implemented.

Thanks for your reply. Would you be able to give a counter-example where this behaviour might cause harm? I can't seem to come up with one.

Please bear in mind that I'm not asking for the database to be unlocked (which would not be possible anyway), but only for it to be opened.

KeepassXC would ask for the master key, then perform Auto-Type. Same as it already does when the last opened database was successfully loaded at startup.

**Comment by droidmonkey** [comment]
The problem comes in when you are programming two completely different functions (auto-type and open on startup) where numerous edge cases and exceptions start creeping in.

I think a better solution, overall, is not to "silently" discard the database tab when a database file cannot be found on startup. Instead, we should show a special page that explain the file could not be found and offer two options: Retry or Close

**Comment by christianglodt** [comment]
While I agree that anything is better than a silent failure, I would not want to have a special page pop up on login in essentially random fashion (ie. whenever the drive mapping fails to reconnect on login in Windows, which is often). Maybe a notification would do the job less intrusively.

**Comment by droidmonkey** [comment]
Not a pop-up. A replacement for the credential entering page (or an extension/alteration of it).

**Comment by phoerious** [comment]
I'd be in favour of an empty "error" tab which gets reloaded when it receives focus like the YubiKey selection does. In the other hand, sometime you just want to open a temporary database from somewhere and then this might get annoying.
