### ISSUE TITLE
2.4.3 Build fails on Fedora 29 -- quarzip.h not in expected include path

### ISSUE THREAD

**Issue by cslux** [keepassxreboot/keepassxc#3238]
Hey!

The build fails on Fedora 29 when Keeshare extension is enabled, because **quarzip.h** is not located in **/usr/include/** but rather in **/usr/include/quarzip/**.

Operating system: Fedora 29
Kernel: Linux HOST 5.1.6-200.fc29.x86_64 #1 SMP Mon Jun 3 17:20:05 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

Enabled extensions:
- ALL

**Comment by droidmonkey** [comment]
Which version are you trying to build? We modified the behavior in 2.4.2 to not require quazip and better find it.

**Comment by cslux** [comment]
2.4.3

Hmm, that's embarrassing. It's working now. I don't know what was wrong,
probably some cached cmake generated files.

Sorry for the noise.
