### ISSUE TITLE
after paste (username or password) into firefox, only able to create new entry

### ISSUE THREAD

**Issue by adudek16** [keepassxreboot/keepassxc#3240]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Expected Behavior
full access the the menu when right clicking on entry after pasting to another app

## Current Behavior
search an entry
after pasting item in another app, only option in keepassxc is "new entry"  
This doesn't seem to happen everytime in my test database but I do hit it about 80% of the time.

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1. Searched for an entry
2. copied either username or password using right click
3. pasted into firefox (do not think app maters)
4. switch to that app (to hit enter)
5. switched back to keepassxc
6. right click on item and only option that is not grayed out is "new entry"
7. close keepassxc and reopen, everything it back

## Context
Have to close and reopen the app

## Debug Info
KeePassXC - Version 2.4.1
Revision: 7bafe65

Qt 5.12.2
Debugging mode is disabled.

Operating system: macOS Mojave (10.14)
CPU architecture: x86_64
Kernel: darwin 18.6.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (only unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
 libgcrypt 1.8.4

![Screen Shot 2019-06-07 at 10 37 36](https://user-images.githubusercontent.com/15655321/59112190-82e46900-8910-11e9-964a-795442707f1a.png)

**Comment by droidmonkey** [comment]
This was fixed in 2.4.2. The Mac release will be back up this weekend.
