### ISSUE TITLE
Browser plugin connection failure: AppImage + XFCE

### ISSUE THREAD

**Issue by rolli-31** [keepassxreboot/keepassxc#3241]
I'm first time trying to use KeePassXC instead of Lastpass.
I installed the KeePassXC as appimage in Bionic Beaver XFCE Desktop.
The computer is Lenovo E520.
Everything is going well except the connection neither to Chromium nor to Firefox which are all in the latest update installed.

I'm not  in Linux/Ubuntu, only a normal user. Even if dumps or whatever is needed to find out, I need advice, how to do.
Thanks in Advance - I want to avoid online PW Treasure because it is not save enough.
Rolf

**Comment by droidmonkey** [comment]
Please see https://keepassxc.org/quickstart/

**Comment by rolli-31** [comment]
I followed the guide, downloaded the file again and set up as guided.
Same problem as written above. the Connection fails. 
On the other side I can open pages out of the database stored in KeepassXC.
Please help.
Rolf

**Comment by droidmonkey** [comment]
Please note that we do not support connections to the snap versions of browsers. What error message does the keepassxc-browser plugin show in your browser?
