### ISSUE TITLE
Please update the Ubuntu PPA

### ISSUE THREAD

**Issue by pizzadude** [keepassxreboot/keepassxc#3242]
Please update the Ubuntu PPA with KeepassXC 2.4.2.

Thanks and many thanks for making this excellent software!

**Comment by SohamG** [comment]
[There's some issue with Launchpad due to which its not updated](https://github.com/keepassxreboot/keepassxc/issues/3203#issuecomment-497937852)

**Comment by pizzadude** [comment]
ah, i'll use the snap until this is fixed

**Comment by droidmonkey** [comment]
PPA has been updated!

**Comment by AvverbioPronome** [comment]
Is this happening again? The browser addon complains about KeePassXC not being up to date, but I'm at the last ppa-available version.

**Comment by droidmonkey** [comment]
What version are you on?

**Comment by AvverbioPronome** [comment]
2.4.3
