### ISSUE TITLE
Show size of entries (including history) in column view

### ISSUE THREAD

**Issue by bleepnetworks** [keepassxreboot/keepassxc#3243]
## Summary
I cannot identify which entries have large files attached

## Desired Behaviour
An option to filter based on attachment size

## Possible Solution
Attachment size column, user enabled / disabled

## Context
Controlling database size. Large images can bloat database and when it comes time to cleanup you don't know where to begin.

**Comment by droidmonkey** [comment]
This is a good idea!

**Comment by bleepnetworks** [comment]
thanks @droidmonkey, I was running an older version (2.2.1 😅) that didn't have this feature, thanks!

**Comment by droidmonkey** [comment]
Implemented in #4588
