### ISSUE TITLE
Es lassen sich keine PDF-Dateien mehr öffnen.

### ISSUE THREAD

**Issue by Werner-Berhand** [keepassxreboot/keepassxc#3245]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

## Current Behavior
[NOTE]: # ( Tell us what actually happens )

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1.
2.
3.

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION
Revision: REVISION

Libraries:
- LIBS

Operating system: OS
CPU architecture: ARCH
Kernel: KERNEL

Enabled extensions:
- EXTENSIONS

**Comment by weslly** [comment]
KeePassXC doesn't (and shouldn't) open PDF files.

**Comment by phoerious** [comment]
This may refer to a Windows bug where KeePassXC keeps a lock on the file, so some PDF readers cannot view the file. Saving it first somewhere and then opening it from there should work around that
