### ISSUE TITLE
Password template

### ISSUE THREAD

**Issue by Gustry** [keepassxreboot/keepassxc#3250]
[TIP]:  # ( Provide a general summary of the feature in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Summary
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
Provide a password template for the database

## Desired Behavior
[NOTE]: # ( Tell us how the new feature should work, be specific )

I'm using more and more a specific template for my passwords. So I'm not generating them with KeepassXC. It's seems possible with Keepass but I didn't see this feature in KeepassXC.

For instance, to be able to generate a password like this:

```regex
![A-Z]{4}#\d{4}-[a-z]{4}\{
```

which can output:
```
!JJKE#6372-djkz{
```

## Possible Solution
[NOTE]: # ( Not required, but suggest ideas on how to implement the addition or change )

Implement a password template in the database settings.

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )

**Comment by droidmonkey** [comment]
This is the antithesis of a password manager. The whole point is to have a randomized password, not one derived from a template. We already have an issue for "password profiles" which would select the appropriate settings of the password generator to comply with site restrictions on symbol usage.

We will not be implementing a template for the password itself though. Sorry.
