### ISSUE TITLE
Saving file over DAV in snap.

### ISSUE THREAD

**Issue by searoso** [keepassxreboot/keepassxc#3252]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Expected Behavior
Double click a file on a share, attached via DAV. Modify the file. Hit Ctrl+S and save the changes.

## Current Behavior
Ctrl+S gives you **nothing** which is generally bad. Using *Save as* works around. But takes huge amount of attention.

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1.
2.
3.

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.4.2
Revision: b5bc1aa
Distribution: Snap

Qt 5.9.5
Debugging mode is disabled.

Operating system: Ubuntu Core 18
CPU architecture: x86_64
Kernel: linux 5.0.0-16-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.1

**Comment by droidmonkey** [comment]
This was fixed in 2.6.0
