### ISSUE TITLE
2.4.2 Clicking on notification area icon no longer hides the window

### ISSUE THREAD

**Issue by FuturePilot** [keepassxreboot/keepassxc#3256]
## Expected Behavior
Clicking the icon in the notification area should hide the window if it is currently open.

## Current Behavior
Clicking the icon in the notification area does nothing if the window is currently open.

## Steps to Reproduce
1. Enable "Show a system tray icon" in Settings
2. Click the icon in the notification area
3. Nothing happens

This is a regression from 2.4.1 behavior. Running Kubuntu 19.04

## Debug Info
KeePassXC - Version 2.4.2
Revision: a775031

Qt 5.12.2
Debugging mode is disabled.

Operating system: Ubuntu 19.04
CPU architecture: x86_64
Kernel: linux 5.0.0-16-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.4

**Comment by droidmonkey** [comment]
Ahh I found the logic error. On Windows clicking the tray icon causes the application window to unfocus. This does not happen in KDE Plasma so it does not trigger the tray action. Interestingly double clicking the tray icon does not work at all. I believe this to be a Qt bug.
