### ISSUE TITLE
Open URL now requires https://

### ISSUE THREAD

**Issue by Murphyau** [keepassxreboot/keepassxc#3259]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )
I just upgraded from KeePassXC 2.4.1 to 2.4.2 running under Linux Mint 18.3

Under 2.4.1, the Open URL menu option worked as expected with the format www.somewebsite.com, but under 2.4.2 it now seems to requires the format https://www.somewebsite.com to open a URL.

I tried various options under Browser Intergration, but none had any effect.  

The only solution appears to be to edit an existing URL entry and add the https:// format.

Is it possible to get 2.4.2 to open a URL like it did in 2.4.1 without having to edit multiple entries ??

**Comment by droidmonkey** [comment]
Just tested a plain www.url.com type of URL on Windows and it worked fine. I suspect this is a Linux issue with handling Schema-less URL's.

**Comment by Murphyau** [comment]
Just upgraded from 2.4.2 to 2.4.3, but the problem still persists.

**Comment by varjolintu** [comment]
I can reproduce this with i3wm. The reason is that the entry URL is passed directly to QUrl's constructor and if there's no scheme, it comes out as `://example.com`.

Using `QUrl:fromUserInput()` would set the scheme to `http` by default. Maybe it would be simpler to just add a check that if the entry URL has no scheme, `https` will be added to it.

**Comment by SohamG** [comment]
Safe to say this is related to https://github.com/keepassxreboot/keepassxc/pull/3153

I can't reporduce this, `google.com` in the URL field works for me.
FWIW even putting a garbage value in the URL field opens my browser (firefox) to `https://<garbage>`

I'm on Ubuntu 18.04 with i3wm and I'm assuming this is thanks to my weird setup (trying out DEs).

That being said I can implement the fix by varjolintu above easily

**Comment by droidmonkey** [comment]
I agree with using fromUserInput.
