### ISSUE TITLE
After upgrade to 2.4.3 enabled extensions in "Debug Info" does not match enabled extensions

### ISSUE THREAD

**Issue by drewfreyman** [keepassxreboot/keepassxc#3261]
## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
After upgrading to KPXC 2.4.3 the "Debug Info" enabled extensions should match the extensions actually enabled in the preferences as set by me.

## Current Behavior
[NOTE]: # ( Tell us what actually happens )
"Debug Info" lists SSH Agent, KeePass Share, etc. as enabled extensions but they are not.

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1. open KPXC 2.4.3
2. open database
3. view About KeePassXC

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.4.3
Revision: 5d6ef0c

Qt 5.12.3
Debugging mode is disabled.

Operating system: macOS Mojave (10.14)
CPU architecture: x86_64
Kernel: darwin 18.6.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
 libgcrypt 1.8.4

![Screen Shot 6](https://user-images.githubusercontent.com/13743114/59398480-3a301400-8d45-11e9-87d9-8047245eab56.png)
![Screen Shot 7](https://user-images.githubusercontent.com/13743114/59398481-3a301400-8d45-11e9-96c6-0583738cafbf.png)
![Screen Shot 4](https://user-images.githubusercontent.com/13743114/59398482-3a301400-8d45-11e9-908e-de5fe40740d4.png)
![Screen Shot 3](https://user-images.githubusercontent.com/13743114/59398483-3a301400-8d45-11e9-8aa5-7b7c4731fe01.png)

![Screen Shot 2](https://user-images.githubusercontent.com/13743114/59398484-3ac8aa80-8d45-11e9-8f24-bee011560fce.png)
![Screen Shot 1](https://user-images.githubusercontent.com/13743114/59398485-3ac8aa80-8d45-11e9-81ee-041389e1cbd6.png)

**Comment by droidmonkey** [comment]
The about dialog shows which extensions are _compiled into_ the application. It does not take into account your settings.

**Comment by drewfreyman** [comment]
Thanks for your reply. Did I miss that in the documentation? I Don't want
to bother people with this sort of simple matter. However after the upgrade
I considered that there could have been some security breach. I searched
for an explanation but could not find one that's why I put up a but report.

~  please excuse message brevity--sent from mobile device  ~

**Comment by droidmonkey** [comment]
The enabled extensions have been a part of KeePassXC since the begining.
