### ISSUE TITLE
keepassxc snap browser integration in Vivaldi gives error message

### ISSUE THREAD

**Issue by AxelMKlein** [keepassxreboot/keepassxc#3263]
Hello,
I have keepassxc installed as a snap in Ubuntu 19.04. I want to use the browser integration in Vivaldi.
The browser extension gives the error message: " KeePassXC-Browser hat einen Fehler festgestellt: Schlüsselaustausch war nicht erfolgreich." ("KeePassXC-Browser encountered an error: Key exchange not successful.")
I've run the script " keepassxc-snap-helper.sh" before.
What do I do wrongly? Is there help?
Thank you in advance.

**Comment by varjolintu** [comment]
That's the extension version? Please disable Auto-Reconnect if it causes any issues.

**Comment by AxelMKlein** [comment]
Thank you for the answer.

Unfortunately the Auto-Reconnect is already disabled. 
The first error message is: "Die Nachrichtenverschlüsselung ist fehlgeschlagen. Läuft KeePassXC?" 
("Message-Encryption failed. Does KeePassXC run?" )
After I press "Neu laden" ("Re-load"), the message in my first message appears.

**Comment by AxelMKlein** [comment]
As additional information, this are the messages on the command line when I start the KeePassXC from it:

snap run keepassxc &
[1] 7403
xxx:~$ Gtk-Message: 13:53:37.101: Failed to load module "canberra-gtk-module"
Gtk-Message: 13:53:37.115: Failed to load module "canberra-gtk-module"
Qt: Session management error: None of the authentication protocols specified are supported
QObject::startTimer: Timers cannot have negative intervals

**Comment by tabacha** [comment]
I have the same problem

**Comment by varjolintu** [comment]
Still having the problem?

**Comment by tabacha** [comment]
Hi, I have switched from smap package to app image package. Here it works.

**Comment by AxelMKlein** [comment]
Hello,
Sorry to come in again. I've just updated to snap keepassxc 2.5.0. I have still the same issue. Browser integration in Vivaldi does not work. Same message "Schlüsselaustausch war nicht erfolgreich."

**Comment by AxelMKlein** [comment]
I've found the root-cause and solved it on my side.

I have Vivaldi Snapshot installed. Therefore the Vivaldi directory in ~/.config is not ~/.config/vivaldi/ but ~/.config/vivaldi-snapshot/ .
After I have changed that in the script  keepassxc-snap-helper.sh, the browser integration works.

**Comment by t0bsen** [comment]
> I've found the root-cause and solved it on my side.
> 
> I have Vivaldi Snapshot installed. Therefore the Vivaldi directory in ~/.config is not ~/.config/vivaldi/ but ~/.config/vivaldi-snapshot/ .
> After I have changed that in the script keepassxc-snap-helper.sh, the browser integration works.

Thanks for the hint. I copied ~/.config/vivaldi/NativeMessagingHosts/org.keepassxc.keepassxc_browser.json into the corresponding ~/.config/vivaldi-snapshot/ path, which also works.
