### ISSUE TITLE
Documentation or Manual or help in software

### ISSUE THREAD

**Issue by webafrancois** [keepassxreboot/keepassxc#3266]
[TIP]:  # The software don't have include any manual or documentation

## Summary
[NOTE]: # When new users install the software, in "help" menu, there is no help. Just "About", "Verify update", "Donate" or "report a bug".
If they choose help menu, they may have some help with Documentation or link to documentation.

## Desired Behavior
[NOTE]: # They should have 2 entries like "Documentation" and FAQ.

## Possible Solution
[NOTE]: # change the menu.

**Comment by droidmonkey** [comment]
It's coming, see #696 and #1629
