### ISSUE TITLE
Implement Master password (PIN) for open (unlock) multiple password databases via single password

### ISSUE THREAD

**Issue by MurzNN** [keepassxreboot/keepassxc#3268]
At now opening KeePassXC with multiple databases are very annoying - users must type different passwords for each database to open. Using same password or one key file for all databases is not so good idea, especially for shared databases.

Will be good to implement "Master password" feature, that simplify opening multiple databases via entering only one master password one time at app startup, and it will unlock and open all stored databases automatically.

So current application instance will store all passwords of opened databases in some local configuration file, that will be encrypted by one local Master password (or key file), and update them on demand when users open-close databases in app interface.

As result, users will can open app and enter only one local master password for unlock multiple databases at once.

What do you think about this idea?

**Comment by droidmonkey** [comment]
This is what AutoOpen and KeeShare are all about. Already implemented, just not documented. See https://github.com/keepassxreboot/keepassxc/pull/1053

**Comment by KochTobi** [comment]
Hi there :)
Is there a way without KeeShare as KeeShare only provides password unlock for shared groups. I have the scenario that several unrelated database files (I need to keep them separate) are needed. The databases are stored online and I am forced to lock them with a password and keyfile (keyfiles/passwords differ for the databases with different people having access to different key files as they are not online). Is there a way to still use autofill/any browser plugin without having to unlock all the databases separately everytime?
I would appreciate if you could point me to the documentation in case I missed it or if you could help me out any other way.

EDIT: Probably same request as https://github.com/keepassxreboot/keepassxc/issues/10108

**Comment by droidmonkey** [comment]
You absolutely need to unlock a database to use it with any feature. You can make that easier on yourself using auto open or click to open. See here:https://keepassxc.org/docs/KeePassXC_UserGuide#_automatic_database_opening

**Comment by KochTobi** [comment]
Thank you @droidmonkey 🙇 
I missed that
