### ISSUE TITLE
Sensible feature in password generator is missing: including instead of excluding characters

### ISSUE THREAD

**Issue by Git-Hub-User-1** [keepassxreboot/keepassxc#3271]
[TIP]:  # ( Provide a general summary of the feature in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Summary
In the password generator one can choose different groups of characters to be used. In the advanced settings one can exclude certain characters of these groups.

That is not practical. Many websites announce which special characters can be used, not the opposite, which cannot be used. This correspondents very rarely with the groups in the generator. So usually one can copy a list of admissible characters from the websites.

Since in the generator one can only exclude characters one has to check the groups in which the allowed characters are in. This is the first time consuming nuiscance. And after the checking of the correspondent groups one has painfully to search for all the characters the web sites does NOT allow to put them in the exclude list. 

## Desired Behavior
There should be a feature to generate an own character group in which one can copy and paste the correspondent special or any characters allowed by a website.

## Possible Solution
Just create a group "User Defined Characters" where one can write or copy&paste in characters.

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
I am annoyed any time when I use the generator about this bad unpractically conception.

**Comment by droidmonkey** [comment]
I am annoyed by websites imposing ridiculous artificial restrictions on the character set of a password. It usually indicates one of two things:

1. They are not hashing passwords prior to storing in the database, or are using an antiquated hash algorithm.

2. They think they know better than their users and want to limit the character set so you don't forget your password.

Your criticism is valid though and I agree it is a pain to align the generator with ridiculous website restrictions.

**Comment by phoerious** [comment]
I think that mostly comes from the old and obsolete NIST recommendation. They totally blew it back then. They have corrected their mistakes and no longer recommend silly password rules, but once such a thing is out in the wild...
