### ISSUE TITLE
Add ability to merge groups by name

### ISSUE THREAD

**Issue by wgunruh** [keepassxreboot/keepassxc#3272]
keepassxc 2.4.1 for linux as in Mageia 7.
The merge database function does not seem to work. I tried to merge the database from another computer to the current one on this computer, and instead of merging the databases, it created two databases in the same database. Ie, 
on the opening menu I had
Internet
eMail
Backup
Internet
eMail
Backup

where the second set was associated with the second database that I was trying to merge in. Ie, instead of merging them it just copied over the second, which was not what I wanted.
What I wanted and assumed that "Merge" did was to create a single database out of the two. with the latest one being used for any duplicate entry.
So either I do not understand the Merge function at all, or there is a bug.

**Comment by droidmonkey** [comment]
If those two databases never shared a history with each other than the groups will have different unique Id's. From the merge algorithm perspective, they are different groups and the behavior you experience is the correct behavior. You can manually clean up the merge results by dragging the entries from one group to another.

**Comment by wgunruh** [comment]
Is there some way of forcing the two groups to have the same ID?

William G. Unruh __| Canadian Institute for|____ Tel: +1(604)822-3273
Physics&Astronomy _|___ Advanced Research _|____ Fax: +1(604)822-5324
UBC, Vancouver,BC _|_ Program in Cosmology |____ unruh@physics.ubc.ca
Canada V6T 1Z1 ____|____ and Gravity ______|_ www.theory.physics.ubc.ca/

**Comment by droidmonkey** [comment]
Unfortunately no, that is not a user editable field

**Comment by droidmonkey** [comment]
I think there is a good idea here to have a database level setting to merge groups by name instead of uuid

**Comment by droidmonkey** [comment]
This is a duplicate request
