### ISSUE TITLE
Paper Backup (aka printer/PDF output)

### ISSUE THREAD

**Issue by wolframroesler** [keepassxreboot/keepassxc#3277]
## Summary

Provide a print/PDF output feature to "back up the password database to paper".

## Desired Behavior

Get as much information as possible on as few printed pages as possible. The Paper Backup should contain all information (attributes, annnotions, notes, etc.) in clear text, so that it can be used instead of the KeePass database if necessary.

## Possible Solution

Implementing printer output is difficult. My idea to get started is to implement something like "Export to HTML file" which creates a single HTML file (with embedded CSS) that users can display and print using their browser. Direct printer output can be added later.

The existing "Export to CSV file" feature could be used as a starting point.

## Context

I'm in the process of migrating from 1Password to KeePassXC, and printer output is the one feature I'm really missing. I used to back up my password database to paper once in a while, and store it in a safe place together with other confidential and important documents, to prepare for complete loss of IT infrastructure or other catastrophic situations (including death in which case my family will have to access my online accounts without knowing how to locate or open my kdbx file).

**Comment by louib** [comment]
Related issues https://github.com/keepassxreboot/keepassxc/issues/876 and https://github.com/keepassxreboot/keepassxc/issues/1434

**Comment by droidmonkey** [comment]
I like this idea only because it is the most flexible way to approach paper backups. Let the PDF viewer / browser handle the actual printing operation. I assume you are going to establish some sort of HTML template located in the share folder.

**Comment by wolframroesler** [comment]
The current implementation doesn't use a template but hard-codes everything, including the style sheet. Using something in the share folder is a good idea, especially for the CSS.

**Comment by RGBsysIT** [comment]
Why provide PDF output, but no provision to open/print it.
