### ISSUE TITLE
Choose Backup Location

### ISSUE THREAD

**Issue by rwat1** [keepassxreboot/keepassxc#3279]
[TIP]:  # ( Provide a general summary of the feature in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Summary
[NOTE]: # ( Provide a brief overview of what the new feature is all about )

Currently the backup is saved on the same folder, which defeats the purpose if my laptop catches on fire.

Ability to choose a different backup location (e.g. a different folder like Dropbox folder)

## Desired Behavior
[NOTE]: # ( Tell us how the new feature should work, be specific )

![image](https://user-images.githubusercontent.com/13740715/59575860-2eb55380-908b-11e9-9ddd-3c6ebcdb0d10.png)

## Possible Solution
[NOTE]: # ( Not required, but suggest ideas on how to implement the addition or change )

An option to select the same folder or a new folder (even better if allows multiple locations to backup to)

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )

I like to backup to my Nextcloud, OneDrive, and Dropbox, each cloud has one copy of latest backup everytime I press save.

**Comment by droidmonkey** [comment]
This is a good idea!

**Comment by grenzor** [comment]
Please make it so users can choose a custom backup database filename as well

**Comment by mustelid** [comment]
And please include the ability to keep multiple backups (up to a thousand previous versions) with date/time as a filename suffix.

**Comment by droidmonkey** [comment]
We aren't implementing a version control system here.

**Comment by mustelid** [comment]
It would be useful to save some historical copies in the backup folder rather than repeatedly overwriting the single .old.kdbx file as is now the case.

**Comment by droidmonkey** [comment]
Two reasons why that is unnecessary:

1. Every entry has a history, you control how many history items are stored in the database settings
2. Multiple backups creates a host of complications and ultimately ends up polluting the disk. Use a proper backup service if you are very concerned.

**Comment by rwat1** [comment]
@mustelid  Yea, it's one reason why I can't full abandon KeePass original, because of nifty plugin called 'DatabaseBackup' that can backup to multiple locations (Dropbox, OneDrive, Other location) upon save. 

I like KeePassXC because it has very nice features like favicon downloads built-in and VERY good QR code scanning for TOTP. World beater, definitely a great software.

**Comment by beckerj** [comment]
I would also like the possibility to make multiple automatic backups of the db on save.

**Comment by meersjo** [comment]
> The backup file is really meant for corruption recovery on save and if you fudge a master password change.

Give the default setting is autosave after every change, that means that if I change two entries in one session, the good copy is also overwritten, though.

**Comment by droidmonkey** [comment]
This is true, but lets say you allow for 5 backup files... then 6 changes and you are now dead in the water. There is no good answer to this problem, EXCEPT, use a proper backup service and/or version control system outside of KeePassXC. You never want the same program doing the actions also doing your backups. Generally speaking a fault in the program that corrupts your save file will most likely corrupt your backup as well. You want to have a dead simple, program agnostic backup solution. Examples:

1. All major cloud storage providers do version control of files.
2. You can do daily backups of your databases using built-in OS tools in Windows, Linux, or macOS
3. Use Git to version control your database, run a periodic script that calls `git commit -a -m "Database Backup"`

As you can see, there is no reason for us to waste cycles implementing this in KeePassXC.

**Comment by meersjo** [comment]
I agree that there's no perfect solution, I just want a good-enough one :-p

* cloud locations aren't supported, I think; so that requires a manual action after every change.
* most backup tools are, as you say, daily. I opened my other rfi exactly to mitigate that :-)
* git, again, requires manual action after every change.

I'm not saying this is a high-urgency feature, far from it; but it would be a damn nice one to have.

In the other rfi, I suggested a (configurable?) time before overwriting the backup copy again; while there would obviously still be potiential for data loss, I think that is a fairly simple thing to implement, that would mitigate (my) major concerns.

Then again, I appreciate you are doing this in your own time, so I'm certainly not about to tell you what you should and shouldn't do; I'm merely arguing my case :-D Thank you for doing this at all!

**Comment by idl0r** [comment]
Yeah, something like that would be great. For me, it's just to have another copy somewhere, regularly updated, that is on a different device. #4302  might be related.
Would you accept a patch, that just adds the option to choose a different path for the backup file?

**Comment by droidmonkey** [comment]
If you have C++ and Qt experience I would love a patch for this.

**Comment by idl0r** [comment]
I don't but I started anyway. I think it's at least half done and I can upload the patch somewhere, if someone else also wants to take a look / continue. Right now I'm busy with real life stuff and I don't know when I am able to finish the work.

**Comment by rwat1** [comment]
I'm still using the original KeePass for it's back-up plugin.

**Comment by idl0r** [comment]
> I'm still using the original KeePass for it's back-up plugin.

Which one in particular? Do you have a link? Does it work in keepassxc?

**Comment by rwat1** [comment]
> > I'm still using the original KeePass for it's back-up plugin.
> 
> Which one in particular? Do you have a link? Does it work in keepassxc?

I personally use this one https://keepass.info/plugins.html#databasebackup

It's great, you can select multiple locations (I selected my NextCloud, OneDrive, and Dropbox folders) and you can set an auto self-delete threshold (like delete after 20 copies). It auto backup with every save.  I don't think it works with keepass though :(

**Comment by grravity** [comment]
It would be really nice to have to be able to have it sign the backups with a keyfile, this would make backing up and syncing soo much easier and would negate the need to deal with manually merging, or anything.
So I can have a database on my local machines that do not require the keyfile, but all the backups to my remote devices do require the keyfile to be present to unlock. 
This alongside being able to set the custom backup location.

**Comment by mchllngr** [comment]
I'm still interested in the original feature request of being able to change the backup location, of which I think this issue somewhat drifted away from.
I'm currently mounting a WebDAV folder from my NAS (where it's backed up daily) and open the database from there. I'd like to have a local copy of the database in case my connection to or the NAS itself fails. By changing the backup location I could have this setup pretty easily without any third party help.

**Comment by rwat1** [comment]
Saving backup to different location saved my butt. I was working off an obsolete folder that I accidentally deleted. :-) Thank goodness I saved to Dropbox or all my porn passwords will be erased.

**Comment by htismaqe** [comment]
Is this something that is being considered for future version?  This would be extremely helpful.  Right now, our choices are to either manually move the backup or just use manual backup.  The auto-backup feature is extremely limited right now because of this.

**Comment by grravity** [comment]
I personally would not want a sync/backup integrated into keepassxc, but a seperate minimal program to handle it. Many already exist like such, rSync, Borgbackup, Syncthing, etc.

However the db files don't like to Sync at least on Syncthing nicely, it tends to create a fair amount of conflict db files.

Also as I mentioned in the past, I wish I could have Keepassxc set a backup location, anytime I edited the database, it could backup new databases to a second folder, and I can sync those instead of the primary. The benefit being I would be able to add a keyfile to those backup databases that I plan to store remotely, meanwhile the ones locally I can have password protected. Then the remote ones would be automatically updated with ease.
The only way to currently handle 2 databases with different protections is by creating 2 databases, and constantly merging them, or just keep manually copying your databases and signing with keyfiles.

**Comment by htismaqe** [comment]
Sorry, maybe I wasn't clear.

I want the ability to set a backup location, just like you.

Right now, because it automatically saves it in the same folder as the original, we have no choice but to either manually copy (or manually backup) or do some kind of sync.

**Comment by rwat1** [comment]
Yea, same. Just the option for it to save to another folder, instead of same folder.

**Comment by droidmonkey** [comment]
Also allow to choose the file name of the resulting backup, perhaps with a date time placeholder.

**Comment by htismaqe** [comment]
Thanks so much for putting this in the 2.7.0 plan.  I went ahead and donated.
