### ISSUE TITLE
information

### ISSUE THREAD

**Issue by osteopathievilleraymontreal** [keepassxreboot/keepassxc#328]
hi
i am new to keepass and also on a computer

my question how can i sync my database on google drive with keepassxc like i used to do with keepass with googlesyncplugin

thanks all
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* KeePassXC version/commit used: (can be found under Help -> About)
* Qt version (e.g. Qt 5.3): 
* Compiler (e.g. Clang++3.6.0): 
* Operating System and version:

**Comment by phoerious** [comment]
You can download the Google Drive sync client for your operating system and then simply synchronize your KDBX file with it.

**Comment by osteopathievilleraymontreal** [comment]
Ok but its notre the best app
Really take a lot of ressources

Le 18 févr. 2017 2:44 PM, "Janek Bevendorff" <notifications@github.com> a
écrit :

**Comment by osteopathievilleraymontreal** [comment]
Thanks for the answer

Le 18 févr. 2017 2:44 PM, "Janek Bevendorff" <notifications@github.com> a
écrit :

**Comment by phoerious** [comment]
You can use Dropbox, Nextcloud, OneDrive, iCloud, whatever you like. But you need one of those clients. KeePassXC itself does not synchronize anywhere and will not do so in the future.

**Comment by osteopathievilleraymontreal** [comment]
Ok perfect
Thanks again

Le 18 févr. 2017 2:47 PM, "Janek Bevendorff" <notifications@github.com> a
écrit :
