### ISSUE TITLE
"Associated email" field --- or custom fields in general.

### ISSUE THREAD

**Issue by Toideng** [keepassxreboot/keepassxc#3284]
I am not a developer, but a keen user of KeePassXC.

I have many Internet accounts, and many emails. Nowadays almost every website
wants to be linked to an e-mail for verification or account restore or just to use as a login.

I want a dedicated field for "associated e-mail", which would be included by default or
possible to include in preview table, main entry edit form and sort/search by it.

At the moment i am using "notes" field for this, but it is somewhat obscure ux. I suspect i can use the "Advanced" tab, but it is quite painful to do so.

If one would generalize this idea, it would look like the issue #1177 --- adding custom fields that would be displayed in main entry edit form and preview table.

**Comment by droidmonkey** [comment]
The attributes found in the advanced portion of the entry are your best bet for this. Create an attribute named "assoc_email" or similar and set it's value to the email. The templates feature tracked in #863 will allow you to create a custom view that fits your need. This is a big feature though.

I am closing this issue in favor of existing ones.
