### ISSUE TITLE
Connection [browser to database] lost after update to 2.4.3 Win64

### ISSUE THREAD

**Issue by wjk82** [keepassxreboot/keepassxc#3285]
## Expected Behavior
[NOTE]: # Connect to database via KeePassXC-Browser

## Current Behavior
[NOTE]: # Browser extension don't see database. "key exchange was not successful" message. One thing changed: updated KeePassXC, nothing more.

## Steps to Reproduce
1. Update KeePass-XC from v2.4.2 to v2.4.3
2. Copy keepassxc.ini from previous version
3. Try to connect to database from browser

## Context
[NOTE]: # Chromium v71.

## Debug Info
KeePassXC - Version 2.4.3
Revision: 5d6ef0c

Qt 5.12.3
Debugging mode is disabled.

Operating system: Windows 7 SP 1 (6.1)
CPU architecture: x86_64
Kernel: winnt 6.1.7601

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.4

Operating system: Windows
CPU architecture: 64-bit

Enabled extensions:
-  KeePassXC-Browser v1.4.6

**Comment by droidmonkey** [comment]
absolutely nothing was changed with browser extension between 2.4.2 and 2.4.3. Try restarting your browser, the native messaging proxy probably needs to be reinstated.
