### ISSUE TITLE
Database won't open on Xubuntu with update to 2.4.3

### ISSUE THREAD

**Issue by retteep** [keepassxreboot/keepassxc#3288]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Expected Behavior
Expect to open database with password

## Current Behavior
Keypass doesn't ask for password. Message states it cannot open database

KeePassXC - Version 2.4.3
Revision: 5d6ef0c
Distribution: Snap

Qt 5.9.5
Debugging mode is disabled.

Operating system: Ubuntu Core 18
CPU architecture: x86_64
Kernel: linux 4.15.0-51-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.1

**Comment by droidmonkey** [comment]
Probably related to what happened in #3234

**Comment by droidmonkey** [comment]
Is this still an issue?

**Comment by pentachore** [comment]
I have exactly the same issue, I'm running xubuntu 18.04.3 LTS, with keepassxc 2.4.3 and firefox plugin version 1.5.1.
My browser integration is activated but the plug in says
" Impossible de se connecter à KeePassXC. Vérifiez que l'intégration navigateur soit activée dans les paramètres de KeePassXC."

**Comment by droidmonkey** [comment]
This should be closed as no further information was provided. It also is a totally different issue then you describe.
