### ISSUE TITLE
Custom URL field not working

### ISSUE THREAD

**Issue by azfarhashmi** [keepassxreboot/keepassxc#3289]
When using URL USERNAME placeholder in custom URLs such as "ssh://**{USERNAME}**@xxx.xxx.xxx.xxx:22" keepassxc previewieing the username correctly but when double clicking the field its opening the terminal but feeding username as "{USERNAME}" to shell instead of actual username.

**Comment by droidmonkey** [comment]
Already reported and fixed for 2.5, thanks
