### ISSUE TITLE
[Windows] .msi installer creates invalid icon in Start Menu/Desktop

### ISSUE THREAD

**Issue by sanyarnd** [keepassxreboot/keepassxc#3292]
## Expected Behavior
I expect KeePassXC icon to be shown.

The issue is the similar to #2868 

## Current Behavior
KeePassXC icon is not displayed in Start Menu/Desktop, instead the program's logo associated with .ico is shown:
![bad_icon](https://user-images.githubusercontent.com/6544384/59830993-85e84c00-9349-11e9-900c-39264d5dd8f3.png)

I don't remember when it was introduced, but I think somewhere in 2.3x branch. I thought it was a system issue, but then it happened on my work PC and all other devices (3+) I've been using.

## Possible Solution
![compare](https://user-images.githubusercontent.com/6544384/59831269-1faff900-934a-11e9-9228-0a9eb7601608.png)
I've been re-placing the corrupted icon with my own for some time, and it works like charm.

You can see on the screenshot the difference between working and non-working shortcut, so I think it's possible to fix it on the installer level.

## Steps to Reproduce
I am not sure, because I never paid close attention to it and I don't have clean system right now, but I think this is the way:
1. Associate .ico extension with any program [IcoFX as mentioned in #2868, or [Nomacs (OSS)](https://nomacs.org/)].
2. Bug happens.

## Debug Info
KeePassXC - Version 2.4.3
Revision: 5d6ef0c

Qt 5.12.3
Debugging mode is disabled.

Operating system: Windows 10 (10.0)
CPU architecture: x86_64
Kernel: winnt 10.0.17763

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.4

**Comment by phoerious** [comment]
I am pretty sure this is not a bug on our side, but some application on your system hijacking our icon. I remember a similar report a while ago. We haven't had any other mentions of this issue.

**Comment by droidmonkey** [comment]
It would appear that windows is thinking that the shortcut used for KeePassXC is actually a shortcut for the registered .ico program. That is interesting.

**Comment by droidmonkey** [comment]
Confirmed this is an issue. We are not setting enough parameters in the shortcut function for WiX and it is filling in the blanks with bogus information. I did an lnk dump of our shortcut and another known-good one and the difference is striking. I am currently fixing the WiX installer to correct this issue. Also, we do not remove the shortcut on uninstall which will also be fixed.
