### ISSUE TITLE
Feature Request: Multi user / team support

### ISSUE THREAD

**Issue by vladaman** [keepassxreboot/keepassxc#3293]
We'd love to enhance security with KeepassXC for our team. Ideal solution the password file is synced across multiple devices using File sync service / shared Samba server etc.

## Summary
To support team sharing single file the KeepassXC would require additional level of security / ACL.

## Possible Solution
1. Add support for user accounts stored directly in the keypass file - fot this we could just use dedicated folder names such like `Users` and `Groups` - then any username/password would be user's account.
2. Add support for folder ACL which user/group can actually see/edit the data in particular folder
3. Add Log trace support - Keepass would log all requests directly to password file to maintain audit trail who opened/viewed/edited what

## TODO
Still don't know how to protect the database against copying away from the shared storage. But if the ACL would be per folder this means the user can access just it's own passwords limiting possibility of data theft.

**Comment by droidmonkey** [comment]
There are fantastic commercial solutions available with those features. It would be a huge undertaking and likely require a custom database file format to achieve this in KeePassXC. It is very unlikely we would ever implement this.

**Comment by My1** [comment]
ACL could be chaos as the question is how to protect it, but one thing that would be quite epic would be allowing multiple decryption options, like keep the header or whatever storeing the master-key of the DB encrypted as many times as users are needed.
