### ISSUE TITLE
Flip between show/hide main window when clicking tray icon

### ISSUE THREAD

**Issue by olafhering** [keepassxreboot/keepassxc#3298]
## Summary
It would be nice if clicking the tray icon would flip the state of the mainwindow betwen "show" and "hide". That way one would avoid the mouse navigation to the "X" to close the window, or to the keyboard to use something like Alt+F4 to hide the window.

## Desired Behavior
Click tray icon, show or hide main window, depending on previous state.

This is version 2.4.2 on Leap 15.1 on git.xfce.org#master.

**Comment by droidmonkey** [comment]
This is a limitation imposed by your desktop environment, not us. On Gnome and XFCE clicking the tray icon forces the notification window to be shown (it emulates a right click behavior). We cannot do anything about this.

**Comment by olafhering** [comment]
Well, pidgin does it just fine. But, that one is gtk based.

**Comment by droidmonkey** [comment]
Then this would be a Qt bug perhaps.

**Comment by olafhering** [comment]
It happens to work (again?) with 2.4.3.
