### ISSUE TITLE
Is it possible to allow search to include passwords themselves?

### ISSUE THREAD

**Issue by courtarro** [keepassxreboot/keepassxc#3301]
## Summary
The Windows version of KeePass2 includes the ability to include password text when doing searches in the database. Can we add that to KeePassXC? Or is it already available and I'm just not seeing it?

## Desired Behavior
Search bar includes password fields when looking for results to return.

## Possible Solution
Add this as a setting since it's likely that not everyone would want this to happen.

## Context
Sometimes I can remember the password of a service account but not the username, so this helps me track down the account. Or, I may have a low-security password compromised and I want to find other services that use that password, or one like it, to correct them all (bad practice, sure, but still something that people might be dealing with).

**Comment by droidmonkey** [comment]
It is already possible with 2.4.0+. Just type `password:<text to search>`
