### ISSUE TITLE
Passwords are not protected by secure input entry in macOS

### ISSUE THREAD

**Issue by aapeliv** [keepassxreboot/keepassxc#3307]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

Password fields that are not visible should be inaccessible to event taps by other apps. See [Apple tech note TN2150](https://developer.apple.com/library/archive/technotes/tn2150/_index.html). With SIP, this also stops root apps from creating such taps.

## Current Behavior
[NOTE]: # ( Tell us what actually happens )

Passwords can be accessed using an event tap (at least for apps registered in the accessibility menu, e.g. Dropbox).

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )

See PR

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1. Open Keepass and a keylogger (e.g. https://github.com/caseyscarborough/keylogger)
2. Type text into a password field that is hidden

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )

## Debug Info
KeePassXC - Version 2.4.3
Revision: 5d6ef0c

Qt 5.12.3
Debugging mode is disabled.

Operating system: macOS Mojave (10.14)
CPU architecture: x86_64
Kernel: darwin 18.5.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
 libgcrypt 1.8.4

**Comment by droidmonkey** [comment]
This tech note is from 2007. The methods applied are no longer valid.
