### ISSUE TITLE
Cleanup CMake files

### ISSUE THREAD

**Issue by droidmonkey** [keepassxreboot/keepassxc#331]
There are some quirks in the CMake build process that can be smoothed out:

- [x] Remove ```cmake/FindLibMicroHTTPD.cmake```
- [x] Use KEEPASSXC_VERSION_[MAJOR|MINOR|PATCH] to describe version numbering
- [x] Set KEEPASSXC_VERSION to dynamically build based on the above variables
- [x] Remove KEEPASSXC_VERSION_NUM entirely

**Comment by phoerious** [comment]
- [ ] Clean up CMake directory structure and move stuff where it belongs

**Comment by phoerious** [comment]
Guard or remove `link_libraries(ws2_32 wsock32)`
