### ISSUE TITLE
AppImage: Enable update native msg manifest file on startup by default

### ISSUE THREAD

**Issue by TheAssassin** [keepassxreboot/keepassxc#3314]
AFAICS, KeepassXC writes some JSON files into `~/.chromium/config/NativeMessagingHosts/org.keepassxc.keepassxc_browser.json` that the Chromium plugin uses somehow to connect to the running KeePassXC (Firefox etc. work similar).

Here's the problem: With AppImageLauncher, the file looks basically like this:

```
{
    "allowed_origins": [
        "chrome-extension://.../",
        "chrome-extension://.../"
    ],
    "description": "KeePassXC integration with native messaging support",
    "name": "org.keepassxc.keepassxc_browser",
    "path": "/run/user/1000/appimagelauncherfs/0417.AppImage",
    "type": "stdio"
}
```

You see some awkward appimagelauncherfs path in there. The ID is assigned randomly and will change when e.g., the underlying AppImage changes, or there's new AppImages. It's like downloading a new version of KeePassXC, or moving the AppImage file around.

Now, so far so good, browser integration works initially. However, when that ID changes (and that happens regularly with AppImageLauncher and also when there's updates), this won't work again, since the file doesn't seem to be ever touched again by KeePassXC after installing it once.

I hit the bug a few times now and always kept wondering why the heck the browser integration stopped working. Today, I managed to find a correlation between "KeePassXC file/path change" (I sometimes randomly manipulate files to test AppImage related features) and "browser integration weird key exchange failed message".

```
> cat /run/user/1000/appimagelauncherfs/map | ag keep
0585.AppImage -> /home/.../Applications/KeePassXC-2.4.3-x86_64_77f8854b719f8b192879d23d89ff297d.AppImage
```

There's an easy fix for this: just rewrite *all these files* on every configuration change and especially when KeePassXC starts up. You might even just write that file whenever the database is opened, it's not such an expensive operation to do that. Just make sure the path in there is always pointing to the AppImage that is running. I just live-edited that path with the new ID and suddenly the plugin started working again.

**Comment by droidmonkey** [comment]
Already an option:

![image](https://user-images.githubusercontent.com/2809491/59984963-62006100-95fc-11e9-8560-1c4122e910ea.png)

**Comment by TheAssassin** [comment]
Is that enabled by default? That should IMO not even be configurable.

**Comment by droidmonkey** [comment]
Perhaps it should be for the AppImage.

**Comment by TheAssassin** [comment]
Wouldn't hurt in general either, I guess. I already mentioned that rewriting the file isn't really a big deal.

**Comment by TheAssassin** [comment]
I might open a second issue regarding naming of the option.
