### ISSUE TITLE
Cancel search when choosing new location in tree

### ISSUE THREAD

**Issue by pbhenson** [keepassxreboot/keepassxc#3317]
In keepassx, when you select a new location from the navigation tree on the left, any active search is automatically cancelled and you see the contents of the new selection. In keepassxc, the search results remain after selecting a new location and you have to manually cancel the search. This seems inefficient; presumably if you're trying to see something else now you don't want the search results anymore.

Thanks...

**Comment by droidmonkey** [comment]
This is already the default behavior. What version are you running?
