### ISSUE TITLE
Exit application after inactivity

### ISSUE THREAD

**Issue by kitingChris** [keepassxreboot/keepassxc#3324]
Keepass2 had an option to exit the application after inactivity or locking the database.

Due to using a global hotkey on ubuntu to let keepass appear  it is necessary for me that the application exits after locking the database or dropping in the background.

**Comment by droidmonkey** [comment]
Why is that necessary? We have single instance mode which will raise the existing window.

**Comment by kitingChris** [comment]
Yea but that does not help much. The application does not get focus on re-open it.

And why do I need the application open after auto-typing an password?
It is an extra process that is not necessary.

**Comment by kitingChris** [comment]
Any chance this missing feature may come in keepassxc soon? 

It is really a feature that I heavily rely on.

Cause for accessing my passwords I have set up a shortcut (STRG + K) which opens keepassxc. 
Unfortunatelly when it is already open in the background (after auto-typing a password for example) it won't reappear.

Also it is still a wasted process when not needed and idling in the background.
So please implement at least an option that gives the possibility to close the application after certain time or auto-typed passwords.

**Comment by droidmonkey** [comment]
What operating system are you using? If Linux, are you using the snap package? The real problem here is the application not coming to the front when you relaunch it. KeePassXC uses about 24 MB of ram on Windows 10.

**Comment by kitingChris** [comment]
I am currently using Ubuntu. Switching to Debian soon. Not using snap.
Getting the application to front would be a acceptable solution for me as it would solve my main concern. Although I would still have a background process and window.

**Comment by droidmonkey** [comment]
You can enable the tray icon and minimize to tray to get rid of the window.
