### ISSUE TITLE
Can't download favicons

### ISSUE THREAD

**Issue by janmichalski** [keepassxreboot/keepassxc#3326]
## Expected Behavior
To download favicons for database entries.

## Current Behavior
Download bar stucks at 0%. After clicking cancel, window with progress bar shows three more times. Option "Use Google as fallback for downloading website icons" is checked.

## Debug Info
KeePassXC - Version 2.3.4
Revision: 6fe821c

Libraries:
- Qt 5.11.1
- libgcrypt 1.8.3

Operating system: Windows 10 (10.0)
CPU architecture: x86_64
Kernel: winnt 10.0.17763

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by droidmonkey** [comment]
You need to update KeePasXC...
