### ISSUE TITLE
Prompt to migrate KeePassHTTP settings only if Browser Integration is enabled

### ISSUE THREAD

**Issue by janteau** [keepassxreboot/keepassxc#3327]
I would like to retain my KeePassHTTP settings for use on Windows.  I use auto-type in KeePassXC, so I do not want to migrate my KeePassHTTP settings.  Unfortunately, I am prompted every time that I unlock my database with KeePassXC (even though Browser Integration is disabled).  Would it be possible for the migration prompt to only be displayed when the Browser Integration settings are enabled and KeePassHTTP attributes are found?

### Current Behavior
When a database with KeePassHTTP entries is unlocked, the user is prompted to migrate these settings.  If "No" is chosen, the user will again be prompted on next database unlock.

### Expected Behavior
Only prompt to migrate KeePassHTTP settings when Browser Integration is enabled in the settings.

**Comment by phoerious** [comment]
I strongly discourage the use of KeePassHTTP and the browser extensions that support it. A lot of work has been put into making our own browser extension as secure as possible. You can use KeePassXC on Windows as well.

**Comment by janteau** [comment]
I understand the dislike of KeePassHTTP.  I typically use auto-type.  I would just prefer to leave my database entries untouched, especially since I'm not using the browser integration feature.

**Comment by droidmonkey** [comment]
I don't see anything wrong with this request, if the feature is disabled we should not be prompting the user about the feature.
