### ISSUE TITLE
TOTP time sync problem

### ISSUE THREAD

**Issue by Shpigorx** [keepassxreboot/keepassxc#3328]
Running same TOTP on WinAuth app and KeePass keys are different.

## Current Behavior
TOTP not correct or shifted in time with correct code

## Possible Solution
As I understand KeePass takes PC time, not internet time. 
Should take internet time OR force win to sync PC time with internet

## Debug Info
KeePassXC - Version 2.4.0
Revision: c51752d
Win 7 x64 SP1

Libraries:
- Qt 5.12.1
- libgcrypt 1.8.4

**Comment by droidmonkey** [comment]
TOTP is only accurate up to 30 seconds of time deviation. You need to sync your PC with the internet time, that is not our application's responsibility.
