### ISSUE TITLE
Attachments are mixed up between entries

### ISSUE THREAD

**Issue by ElucGeek** [keepassxreboot/keepassxc#3330]
I had discover a strange bug lately. I have many entries with text file as attachments and today I noticed that the content of one attachment was in fact the content of another attachment, only the file name was correct but content was not. Is not just swaped between the two, as when I open attachement 1.txt of entry A, I see the content of attachement2.bin from entry B. But when I check entry B in attachement2.bin I have the content of attachement3.key entry C... So it's never ending and a mess to recover all of them.
I have changed the extension as in my case luckily it was only between text files (so far) but it occurs even if the file as another extension like .bin, .key or anything, I guess it doesn't matter what is the extension.

**Comment by droidmonkey** [comment]
What version of KeePassXC are you running?
Have you used any other KeePass-like program at all?
Need more details because we had a similar issue with KeePass2 duplicating attachment binaries and causing havoc (against their own spec).

**Comment by sergiofagostinho** [comment]
Hi guys, I have a similar issue. In my case, I would remove the file and add a new, but the content would be unchanged (MD5). After a couple of retries, I add the file, but it has a different checksum when extracting it via a Python script (https://github.com/pschmitt/pykeepass).

It's worth noticing that we are also using KeePassX... perhaps the file has become corrupted?

**Comment by ElucGeek** [comment]
> 
> 
> What version of KeePassXC are you running?
> Have you used any other KeePass-like program at all?
> Need more details because we had a similar issue with KeePass2 duplicating attachment binaries and causing havoc (against their own spec).

Thanks for your replay, I'm using 2.4.1
The keepass archive is very old and I've tried many Keepass compatible clients. It was created on the original Keepass and recently I've moved to Keepass XC, I'm also using KeepassDX on Android with the same archive. A short time after moving to XC I was prompt to change the encryption and keyfile, what I did. If I open the backup of my old archive before these 2 changes, I don't have the issue (what ever software I use to open it). I used many devices so I'm not sure if at some point I did save the new archive with Keepass2 then continue making change with both KeepassXC and DX. It's also well possible that the change occur at the migration to the new encryption but cannot confirm that either.

At least I have a way to recover all my attachment but I will have to manual open both archive and transfert the attachement one by one, unless there is a better solution to solve the issue.

**Comment by droidmonkey** [comment]
Please update to 2.4.3 to prevent further issues

**Comment by ElucGeek** [comment]
> 
> 
> Please update to 2.4.3 to prevent further issues

Hello, Ok I did just open the same archive in 2.4.3 and the issue is not solved, attachment are still mixed up.

**Comment by droidmonkey** [comment]
It doesn't fix an already broken database, its too late now. You have to go back to the known good and it won't break again.

**Comment by fansari** [comment]
https://gitlab.gnome.org/World/secrets/-/issues/344

I remember I noticed something like this in the past but today it really hit me. I had some wallet backup from 2021 as attachment and today I needed it and only found a passphrase in it. Means all the money of this wallet is gone forever.
