### ISSUE TITLE
Dark mode buttons highly confusing

### ISSUE THREAD

**Issue by ygrange** [keepassxreboot/keepassxc#3331]
In the password generation screen, I can pick between a few options for what charcters should and should not be in the password. 

##  Expected Behavior
[NOTE]: #  Showing whether an option is pushed or not in an unambiguous way. 

## Current Behavior
[NOTE]: # In this screenshot, I would conclude that the first three options are turned OFF and the last two are turned ON (they look 'pushed down' due to the bright border). The generated password shows that the exact opposite is the case. Every time I generate a password, this has me confused.  
<img width="790" alt="Screenshot 2019-06-27 at 22 28 35" src="https://user-images.githubusercontent.com/6578686/60298515-fd5e4280-992a-11e9-9e3d-8e380aec5d5f.png">

## Possible Solution
[NOTE]: # Maybe add a shadow to the ON version of the button. Or invert the colours of ON and OFF, though this may confuse others. Or pick slightly different colours.

## Steps to Reproduce
1. Generate a password
2. Push the buttons

## Context
[NOTE]: # It confuses me :) 

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.4.3
Revision: 5d6ef0c

Qt 5.12.3
Debugging mode is disabled.

Operating system: macOS Mojave (10.14)
CPU architecture: x86_64
Kernel: darwin 18.6.0

Enabled extensions:
- Auto-Type
- Browserintegratie
- SSH-agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
 libgcrypt 1.8.4

**Comment by droidmonkey** [comment]
This is not our application, but the Qt theme for dark mode macOS. You will have to let them know it is confusing over at https://bugreports.qt.io
