### ISSUE TITLE
Application window is minimized when switching workspace on Ubuntu

### ISSUE THREAD

**Issue by ba32107** [keepassxreboot/keepassxc#3333]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )
Whenever I switch workspace on Ubuntu (19.04), the running KeepassXC instance is automatically minimized. This is happening even if the window is not in focus.

The issue does not happen when the 'Hide window to system tray when minimzed' option is disabled - however I do want this option.

Installed KeepassXC from official Ubuntu PPA. The issue did not happen when I was using the snap package if I recall correctly.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
The application window should remain in its original state when I switch workspace (same as every other application).

## Current Behavior
[NOTE]: # ( Tell us what actually happens )
The application window is automatically minimized when I switch workspace.

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1. Have the application running with the window in the foreground
2. Press CTRL+ALT+Down to move one workspace down
3. Window is minimized

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )
I usually have the window not minimized in my main workspace, but I regularly switch to my coding workspace. Whenever I need a password or a specific username, I need to restore the window from the system tray which is two extra clicks and a lot of mouse movement.

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.4.3
Revision: 5d6ef0c

Qt 5.12.2
Debugging mode is disabled.

Operating system: Ubuntu 19.04
CPU architecture: x86_64
Kernel: linux 5.0.0-17-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.4

**Comment by ba32107** [comment]
After taking a look at the code, I don't think this can be solved. On a window minimized event, the application checks if the 'Hide window to system tray when minimzed' setting is enabled - if so, it hides the window.

Presumably the cause of this issue is that Ubuntu switches workspace by minimizing all applications in the workspace. I did some initial research, and it seems that it's not possible to detect workspace change events in QT - thus I think we cannot do anything about this in KeePassXC.

I worked around this by disabling the 'Hide window to system tray when minimzed' setting and enabling the 'Minimize instead of app exit' setting. This way I can hide the window when I want to, but it's also kept open when I switch workspaces.

If you agree with my analysis above, please go ahead and close this issue - otherwise I'd be interested in your input.

**Comment by droidmonkey** [comment]
It could very well be that windows are given the "Minimized" property when they are not visible on the active desktop.
