### ISSUE TITLE
Endless loop when auto-open in a file opens a file that auto-opens the first file

### ISSUE THREAD

**Issue by hrehfeld** [keepassxreboot/keepassxc#3334]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1. File A has AutoOpen to file B
2. File B has AutoOpen to file A
3. Try opening file A
3. Endless loop of KPXC opening databases

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

Open both databases.

## Current Behavior
[NOTE]: # ( Tell us what actually happens )
KPXC gets stuck in an endless loop opening databases. The UI is still clickable but very laggy, and the first database never gets opened.

This will probably also fail transitively? I.e. A -> B -> C -> A
And fails when using a single file that autoopen-references itself: A -> A

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )
Check which files are already open / were already requested to auto-open. (This also happens when file B is already open)

## Debug Info
keepassxc-git 2.4.3.r54.ga22e8a1f-1

Operating system: ARCH
CPU architecture: x86
Kernel: linux 5.1.14.arch1-1

**Comment by hrehfeld** [comment]
This is *especially* annoying if you have a reference to file A in AutoOpen of file A :see_no_evil: . keepassxc rm database `/entry/path`  can help in this case.

**Comment by droidmonkey** [comment]
There is no need to disable auto open, this recursion just needs to be fixed.
