### ISSUE TITLE
in vers. 2.4.3 yubikey challenge response not working Linux Mint 19.1

### ISSUE THREAD

**Issue by elli1981** [keepassxreboot/keepassxc#3335]
[TIP]:  # yubikey challenge response does not work in vers. 2.4.3 on Linux Mint 19.1
[TIP]:  # computer OS is Linux Mint 19.1 and has vers. 2.4.3 (via snap) as vers. 2.3.1 (via apt-get) installed.... same database (secured by challenge response) ..... 2.3.1 unlocked without any problems ... 2.4.3 yubikey is not detected

database origin created in Vers. 2.4.1 on Linux Mint 18.3 on another computer - there also no problems to unlock with yubikey

## Expected Behavior
[NOTE]: # unlock database with yubikey

## Current Behavior
[NOTE]: #no problem here
 KeePassXC - Version 2.3.1
Revision: 2fcaeea

Bibliotheken:
- Qt 5.9.5
- libgcrypt 1.8.1

Betriebssystem: Linux Mint 19.1
CPU-Architektur: x86_64
Kernel: linux 4.15.0-20-generic

Aktivierte Erweiterungen:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1.
2.
3.

## Context
[NOTE]: # no access to database in version 2.4.3
![keepassxc](https://user-images.githubusercontent.com/52331416/60365544-47a5f900-99e9-11e9-8a16-cf94085c1728.png)

## Debug Info
[NOTE]: # (KeePassXC - Version 2.4.3
Revision: 5d6ef0c
Distribution: Snap

Qt 5.9.5
Debugging mode is disabled.

Operating system: Ubuntu Core 18
CPU architecture: x86_64
Kernel: linux 4.15.0-20-generic

Enabled extensions:
- Auto-Type
- Browser-Integration
- SSH-Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.1

**Comment by elli1981** [comment]
same problem when creating new database..
vers. 2.3.1 - no problem to found yubikey and challenge response in slot 2
vers. 2.4.3 - error - no yubikey found

the yubikey was during the whole trial connected

**Comment by droidmonkey** [comment]
When you use the snap you need to enable raw usb permission. See https://keepassxc.org/docs/#faq-appsnap-yubikey

**Comment by elli1981** [comment]
Many thanks for your answer. Sorry for my inconvenience.
