### ISSUE TITLE
Tab key in search box no longer goes to list of matching entries

### ISSUE THREAD

**Issue by michael-adler** [keepassxreboot/keepassxc#3338]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
In previous versions, hitting the tab key after searching moved focus to the top of the list of matching entries. This made search and selection easy without a mouse.

## Current Behavior
[NOTE]: # ( Tell us what actually happens )
Tab in the search box now moves focus to something near the bottom of the window, selecting something that isn't very useful. Hitting tab a couple more times eventually moves focus to the top of the hierarchy in the left pane and clears the search box!

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )
Revert to previous behavior.

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1. ^F to search, enter a string
2. Tab to move focus

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.4.3

Operating system: MacOS
CPU architecture: x86

**Comment by ba32107** [comment]
There is already an issue for this: https://github.com/keepassxreboot/keepassxc/issues/2878

**Comment by michael-adler** [comment]
Sorry, searched but missed the existing report.
