### ISSUE TITLE
Keepassxc snap cannot display foreign characters.

### ISSUE THREAD

**Issue by tkuraku** [keepassxreboot/keepassxc#334]
I have a directory with Japanese characters and keepassxc cannot display them properly. This is on Ubuntu 16.04 using the snap package.

## Expected Behavior
Display Japanese Characters.

## Current Behavior
Shows an empty box like it can not recognize the character.
(keepassx installed via apt displays them fine)

## Possible Solution
The snap package is not able to access necessary fonts.

## Steps to Reproduce (for bugs)
1.Fresh install of Ubuntu 16.04 with language support
2.Install keepassxc snap package
3.open a keepass database from a directory with Japanese characters.

![tc kdbx - keepassxc_001](https://cloud.githubusercontent.com/assets/11217294/23142352/b987d0d6-f778-11e6-9ca5-97241b6829c4.png)

## Context

I was just trying keepassxc (use keepassx now) and it doesn't display Japanese characters

## Your Environment
* Operating System and version: Ubuntu 16.04
* Snap Package

**Comment by phoerious** [comment]
Please don't delete the issue template.

Does this problem only occur in the file path or also inside your database?

**Comment by tkuraku** [comment]
Sorry about deleting the template, I edited the issue to fix it.

It also occurs inside the database

![tc - keepassxc_001](https://cloud.githubusercontent.com/assets/11217294/23147174/103d883c-f79a-11e6-9b99-df694c4bbd0d.png)

After some experimentation I can not enter Japanese using Mozc (IBUS) into keepassxc either.

I assume this is specific to the snap package.
(There is no problem using keepassx installed with apt)

**Comment by phoerious** [comment]
> (keepassx installed via apt displays them fine)

That's some vital information. 😄 

Can you try the AppImage and tell me if it's working with that one?

**Comment by tkuraku** [comment]
The AppImage can display the Japanese characters as expected.

However, I can not enter Japanese characters into the program via Mozc (IBUS).

**Comment by phoerious** [comment]
Okay, so it's definitely a packaging bug.
Can you enter Japanese via input methods (ibus and the like) into the DEB version (see our website) or a custom-built one?

**Comment by tkuraku** [comment]
I have not tried the the deb version yet. I'll try it and get back in the next couple days.

**Comment by Throne3d** [comment]
I can reproduce this issue (inability to type Japanese characters into a snap using Mozc, and Japanese characters displaying as boxes after being copy-pasted in on a snap). Using a version of KeePassXC where I built it from source (a few days ago), typing using Mozc works fine and characters display appropriately. It therefore seems to be a problem with the snap itself.

**Comment by tkuraku** [comment]
I just tried the keepassxc_2.1.2-1_amd64_stable.deb from the website. Everything works like keepassx installed from apt. It displays Japanese characters and allows input from Mozc. It seems to be an issue with AppImage and snap packages.

**Comment by Throne3d** [comment]
Using `KeePassXC-2.1.2-x86_64.AppImage`, using Mozc to input Japanese text does not seem to work (Mozc refuses to move from the 'Direct input' input mode), but it does appear to display Japanese text just fine, at least on my system.

So it seems like *input* is a problem shared between the snap and the AppImage, but display is just a problem with the snap.

**Comment by droidmonkey** [comment]
Can someone give me a step-by-step on how to setup the environment and replicate the bug. As a US-English person I never venture into localization and alternative character renders. I want to fix this with snaps. Sorry ☹️

**Comment by tkuraku** [comment]
Here is a good step by step guide to setting it up.

https://moritzmolch.com/2287

If you have done everything correctly if you open up gedit or something and type "suki"  and space "好き" should appear.

(Don't worry I am a US-English person too, just happened to have lived in Japan for couple years before)

**Comment by droidmonkey** [comment]
Thanks! After some research it looks like a mozc interface was recently added to the unity7 plug. Make sure you are running at least snapd version 2.0.8.

https://developer.ubuntu.com/en/blog/2016/06/15/snapd-208-universal-snaps-and-desktop-interfaces/

**Comment by Throne3d** [comment]
Running `snap version` gives me:

```
snap    2.22.5
snapd   2.22.5
series  16
ubuntu  16.10
```

Mozc input continues not to work in the snap. "日本語" continues to show as boxes (doesn't show as boxes here in Chrome).

**Comment by tkuraku** [comment]
snap version
```
snap    2.22.3
snapd   2.22.3
series  16
ubuntu  16.04
```

Everything is as up to date as possible.

**Comment by droidmonkey** [comment]
Are any other snaps affected?

**Comment by tkuraku** [comment]
I don't use snaps too much, but I just tried the libreoffice snap. And I can't enter Japanese text use libreoffice writer either. It might be an issue with snaps in general.

**Comment by droidmonkey** [comment]
Looks like the bug is with the mozc interface in the unity7 plug.

**Comment by Throne3d** [comment]
What about character display, though?

**Comment by tkuraku** [comment]
I just tried the libreoffice snap and it can't display Japanese characters either. I will try to report the bug for snapd.

**Comment by brglng** [comment]
+1 for issue on Chinese system, Ubuntu 17.10.
![2017-10-27 12-43-12](https://user-images.githubusercontent.com/1525226/32088273-90f658f8-bb14-11e7-88c4-868e50f7fb49.png)

**Comment by weeix** [comment]
I can still reproduce this bug in snap package v2.3.1

snap    2.32.3
snapd   2.32.3
series  16
ubuntu  16.04
kernel  4.13.0-37-generic

**Comment by kapsy** [comment]
Is there any update on this issue? I'm getting the same problem using Artix.

**Comment by droidmonkey** [comment]
We are no longer making any improvements to the snap distribution. Recommend switching to flatpak.
