### ISSUE TITLE
Left-clicking tray icon in Elementary OS doesn't toggle window, but shows menu

### ISSUE THREAD

**Issue by wolframroesler** [keepassxreboot/keepassxc#3343]
## Expected Behavior

When left-clicking the KeePassXC icon in the system tray (or whatever that thing is called, I mean the horizontal bar at the top of the screen which contains the clock, battery indicator, and application icons), the KeePassXC window should be "toggled" (made visible if hidden and vice-versa). Right-clicking the system tray icon should display a menu with "toggle", "lock database", and "quit".

## Current Behavior

Left-clicking the system tray icon in Elementary OS displays the menu, just like right-clicking does.

## Possible Solution

If I knew one I'd implement it right away.

## Steps to Reproduce

1. Start KeePassXC in Elementary OS.
2. Left-click the KeePassXC icon in the system tray (in the upper right of the screen).
3. If the KeePassXC window is shown/hidden, everything's OK. If a pull-down menu appears, that's the bug.

## Context

Elementary OS 5.0 (Juno) with all updates installed as of today.

## Debug Info

KeePassXC - Version 2.4.3
Revision: 5d6ef0c
Distribution: AppImage

Qt 5.10.1
Debugging mode is disabled.

Operating system: elementary OS 5.0 Juno
CPU architecture: x86_64
Kernel: linux 4.15.0-51-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (only unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.1

**Comment by kpcee** [comment]
Elementary OS afaik does not support tray icons, but uses the indicators designed by Canonical which do not distinguish between left and right click. So it is not a bug of KeePassXC or in this case Qt, but a feature of Elementary OS.

**Comment by droidmonkey** [comment]
Yah this is not something we have control over.

**Comment by wolframroesler** [comment]
I read a bit more about the UI philosophy of elementary OS (https://elementary.io/docs/human-interface-guidelines) and now understand why it behaves the way it does. Hiding/showing an app via the tray icon (or, in the case of an application like KeePassXC, showing a tray icon at all) goes against that philosophy (in particular, https://elementary.io/docs/human-interface-guidelines#does-your-app-need-an-indicator), that's why it's excusable that it doesn't work. The elementary way is to configure KeePassXC to "minimize instead of app exit" and "not show a system tray icon", and to use the dock to hide/show the app.
