### ISSUE TITLE
Copy button on 'Generate Password' does not work on KDE Plasma

### ISSUE THREAD

**Issue by ronnocnave** [keepassxreboot/keepassxc#3345]
When I generate a new password using the password generator tool on KDE Plasma, pressing the 'copy' button does not copy the newly-generated password. Highlighting, then right-clicking in the newly-generated password field and selecting 'copy' does work, however.
 
Expected Behavior:
Pressing the copy button actually copies the new password to Klipper in the #1 spot for use in the OS.

Current Behavior:
Copying the password via the copy button does not appear to do anything.

Steps to Reproduce:

1. Open password generator tool
2. Generate new password
3. Click the 'Copy' button

Context:
Running the Snap version of KeepassXC, which I suspect may be a factor here.

Debug Info:
KeePassXC - Version 2.4.3
Revision: 5d6ef0c
Distribution: Snap

Debugging mode is disabled.

Operating System: KDE neon 5.16 (Ubuntu 18.04)
KDE Plasma Version: 5.16.2
KDE Frameworks Version: 5.59.0
Qt Version: 5.12.3
Kernel Version: 5.1.15-050115-generic
OS Type: 64-bit
Processors: 8 × AMD FX-8370 Eight-Core Processor
Memory: 15.6 GiB of RAM

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Libraries:
Qt 5.9.5

Cryptographic libraries:
libgcrypt 1.8.1

**Comment by droidmonkey** [comment]
I cannot replicate this in Ubuntu 19.04 using KDE Plasma 5.15.4
