### ISSUE TITLE
CLI: search command

### ISSUE THREAD

**Issue by davad** [keepassxreboot/keepassxc#3348]
## Summary
Currently, using `keepassxc-cli` to find and display an entry is a little awkward. I often end up with this in my shell history:

```
% keepassxc-cli ls path/to/db.kdbx 
% keepassxc-cli ls path/to/db.kdbx 'folder1'
% keepassxc-cli ls path/to/db.kdbx 'folder2'
% keepassxc-cli ls path/to/db.kdbx 'folder2/folder3'
% keepassxc-cli show path/to/db.kdbx 'folder2/folder3/find me'
```

It would be nice to have a CLI feature similar to the UI search feature:
```
% keepassxc-cli search path/to/db.kdbx 'find me'
folder1/find me here
folder2/find me again
folder2/folder3/find me
```

## Desired Behavior

Add new subcommand in CLI for searching a database. Usage info might look like this:
```
% keepassxc-cli search -h
Usage: keepassxc-cli search [options] database term
Search for an entry.

Options:
  -q, --quiet                   Silence password prompt and other secondary
                                outputs.
  -k, --key-file <path>         Key file of the database.
  --no-password                 Deactivate password key for the database.
  -a, --attributes              Also search attributes
  -p, --path <path>             Restrict search to <path>
  -h, --help                    Displays this help.

Arguments:
  database                      Path of the database.
  term                          Term to search for
```

**Comment by droidmonkey** [comment]
This brings up an interesting point in that you could be spilling information about your database structure (and possibly entry names) through command line history. @louib what do you think about adding a flag such as `--secure-input` so that commands like `ls` and `search` force you to type your query through a prompt instead of as part of the command.

**Comment by louib** [comment]
@droidmonkey That would make sense, yeah. Maybe `-i --interactive`?

**Comment by droidmonkey** [comment]
Good idea

**Comment by sjamesr** [comment]
This could now be achieved with 

```
$ keepassxc-cli open path/to/db.kdbx
> locate "find me"
folder1/find me here
folder2/find me again
folder2/folder3/find me
> show "folder2/folder3/find me"
```

As suggested in #4212, it would be nice to concatenate trailing positional arguments together to avoid needing to quote or escape the path parameter in the case that it contains whitespace.

**Comment by droidmonkey** [comment]
Yes I believe this is implemented. @louib agree?

**Comment by louib** [comment]
I'm not really comfortable with merging the last arguments together, I feel like it's not really explicit, as opposed to escaping or quoting. I'm not fiercely against it though.

**Comment by droidmonkey** [comment]
No i meant the search capability is implemented, we can close this issue? I don't want to merge parameters implicitly, it's not good form

**Comment by louib** [comment]
Yes if the search is only intended for the title of the entry, `locate` will do the job.

**Comment by droidmonkey** [comment]
Ok nevermind, we would still want a search function that would pass the string to the entrysearcher

**Comment by droidmonkey** [comment]
This is resolved by https://github.com/keepassxreboot/keepassxc/commit/e8f2c9d126ac59aa65a1c3400aad83c97b38c9a7
