### ISSUE TITLE
crash when switching between groups

### ISSUE THREAD

**Issue by Mintulix** [keepassxreboot/keepassxc#335]
## Expected Behavior
When switching groups with a mouse click or per keyboard, the entries of the selected folder should be shown.

## Current Behavior
After a few group switches the application crashes and closes. When startet from command line, it just says "Speicherzugriffsfehler" or "memory-access-error".

## Possible Solution
?

## Steps to Reproduce (for bugs)
1. compile with parameters "cmake -DWITH_TESTS=OFF -DWITH_XC_AUTOTYPE=ON -DWITH_XC_HTTP=OFF .."
2. start keepassxc, create a few groups including a few entries
3. switch between groups a few times
4. for me it crashes after the 2nd or 3rd switch

## Your Environment
* KeePassXC version/commit used: 2.1.2
* Qt version (e.g. Qt 5.3): 5.5.1
* Compiler (e.g. Clang++3.6.0): GNU 5.4.0
* Operating System and version: Linux Mint 18.1 Cinnamon 64bit, latest updates

**Comment by phoerious** [comment]
Are you doing anything else besides clicking on various entries in the group tree?
I am not able to reproduce the crash.

**Comment by Mintulix** [comment]
No, nothing else. How can I debug this to give you more information?
Just one other point: I didn't make a new database from scratch, but imported it from keepassx 0.4.4.
I didn't change the folders since then. Will make a new database and test it, but not today.

**Comment by TheZ3ro** [comment]
Try compiling with `-DCMAKE_BUILD_TYPE=Debug` and post here the stack trace.

By selecting groups I can't reproduce the bug either

**Comment by Mintulix** [comment]
$ cmake -DWITH_TESTS=OFF -DWITH_XC_AUTOTYPE=ON -DWITH_XC_HTTP=OFF -DCMAKE_BUILD_TYPE=Debug ..
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test WERROR_C_AVAILABLE
-- Performing Test WERROR_C_AVAILABLE - Success
-- Performing Test WERROR_CXX_AVAILABLE
-- Performing Test WERROR_CXX_AVAILABLE - Success
-- Found LibGPGError: /usr/lib/x86_64-linux-gnu/libgpg-error.so  
-- Found Gcrypt: /usr/lib/x86_64-linux-gnu/libgcrypt.so (Required is at least version "1.6.0") 
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.8") 
-- Performing Test ZLIB_SUPPORTS_GZIP
-- Performing Test ZLIB_SUPPORTS_GZIP - Success
-- Performing Test HAVE_PR_SET_DUMPABLE
-- Performing Test HAVE_PR_SET_DUMPABLE - Success
-- Performing Test HAVE_RLIMIT_CORE
-- Performing Test HAVE_RLIMIT_CORE - Success
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Found X11: /usr/lib/x86_64-linux-gnu/libX11.so
-- /home/me/compiles/KeePass/keepassxc-2.1.2/share/translations/keepassx_lt.ts;/home/me/compiles/KeePass/keepassxc-2.1.2/share/translations/keepassx_ko.ts;/home/me/compiles/KeePass/keepassxc-2.1.2/share/translations/keepassx_el.ts;/home/me/compiles/KeePass/keepassxc-2.1.2/share/translations/keepassx_es.ts;/home/me/compiles/KeePass/keepassxc-2.1.2/share/translations/keepassx_ja.ts;/home/me/compiles/KeePass/keepassxc-2.1.2/share/translations/keepassx_pl.ts;/home/me/compiles/KeePass/keepassxc-2.1.2/share/translations/keepassx_pt_BR.ts;/home/me/compiles/KeePass/keepassxc-2.1.2/share/translations/keepassx_en_plurals.ts;/home/me/compiles/KeePass/keepassxc-2.1.2/share/translations/keepassx_pt_PT.ts;/home/me/compiles/KeePass/keepassxc-2.1.2/share/translations/keepassx_da.ts;/home/me/compiles/KeePass/keepassxc-2.1.2/share/translations/keepassx_nl_NL.ts;/home/me/compiles/KeePass/keepassxc-2.1.2/share/translations/keepassx_zh_TW.ts;/home/me/compiles/KeePass/keepassxc-2.1.2/share/translations/keepassx_uk.ts;/home/me/compiles/KeePass/keepassxc-2.1.2/share/translations/keepassx_zh_CN.ts;/home/me/compiles/KeePass/keepassxc-2.1.2/share/translations/keepassx_fr.ts;/home/me/compiles/KeePass/keepassxc-2.1.2/share/translations/keepassx_de.ts;/home/me/compiles/KeePass/keepassxc-2.1.2/share/translations/keepassx_ru.ts;/home/me/compiles/KeePass/keepassxc-2.1.2/share/translations/keepassx_sv.ts;/home/me/compiles/KeePass/keepassxc-2.1.2/share/translations/keepassx_sl_SI.ts;/home/me/compiles/KeePass/keepassxc-2.1.2/share/translations/keepassx_cs.ts;/home/me/compiles/KeePass/keepassxc-2.1.2/share/translations/keepassx_it.ts;/home/me/compiles/KeePass/keepassxc-2.1.2/share/translations/keepassx_id.ts
-- Enabled features:
 * Autotype , Auto-type passwords in Input fields

-- Disabled features:
 * KeePassHTTP , KeePassHTTP support for ChromeIPass and PassIFox

-- Configuring done
-- Generating done
-- Build files have been written to: /home/me/compiles/KeePass/keepassxc-2.1.2/build

**Comment by phoerious** [comment]
That's not the stack trace.
You get the stack trace by running the keepassxc binary with gdb.

Open a terminal and run
```
gdb keepassxc
```
In the appearing input prompt enter `run` and then try to reproduce your crash. You get the backtrace by running `bt` after the crash.

**Comment by Mintulix** [comment]
Sorry, need a bit more help with this:
```
(gdb) run
Starting program: /usr/local/bin/keepassxc 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Cannot find user-level thread for LWP 18192: generic error
(gdb)
```
keepassxc is running somewhere in the background without visible GUI then.

**Comment by phoerious** [comment]
This appears to be some depper library problem on your system. it's not a KeePassXC bug.
Also these permission errors let assume that your GDB setup is somehow broken. I can't relly help you with this.

I would suggest you try our AppImage and see if that works.

**Comment by Mintulix** [comment]
OK, thanks for analyzing. I will try again when I make a new system install in 1 or 2 months.
