### ISSUE TITLE
Firefox Browser plugin not decrypting database

### ISSUE THREAD

**Issue by baffled2** [keepassxreboot/keepassxc#3350]
## Expected Behavior

when opening pages with logins I have saved, I would expect the browser plugin to detect the login field as a saved entry, and offer to complete the login fields

## Current Behavior
I open the KeePassXC database, then I open Firefox - ie database is open and accessible prior to starting firefox.
Firefox plugin fails to detect database, giving error message

KeePassXC-Browser has encountered an error:
Cannot decrypt message 

clicking on reopen database, or closing and reopening database manually has no impact - it still is unable to access databse

manually going to relevent entry in database and clicking on Perform Autotype still works, but this rather negates the point of having the browser plugin.

## Possible Solution
Not sure, do not know what is causing it

## Steps to Reproduce
Open database
Open Firefox
Open page with login that is saved in database
attempt to use plugin to enter saved login

## Context
I am not aware of any unique circumstances

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.4.3
Revision: 5d6ef0c

Qt 5.5.1
Debugging mode is disabled.

Operating system: Ubuntu 16.04 LTS
CPU architecture: i386
Kernel: linux 4.4.0-21-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.1

**Comment by droidmonkey** [comment]
You should probably try re-connecting your database to the browser extension. Go to the extensions settings page, then click on "Connected Databases", then remove all connections. You should be prompted to connect again when you open the extension dialog.

**Comment by varjolintu** [comment]
Does the same happen if you keep your database closed and then open Firefox? Just asking if this only happens in a certain situation.

**Comment by baffled2** [comment]
uninstalling and re-installing the browser plugin seems to have cured the problem
It has been working OK today at any rate

**Comment by baffled2** [comment]
OK

issue came back

This is what happened

I opened KeePassXC database
I opened Firefox browser
  >>  browser plugin worked fine
Screensaver kicked in
KeePass database locks automatically when system goes idle
I unlock database
I get "cannot decrypt" message back when attempting to open any login page

If I disconnect connected databases in browser extension, I cannot re-connect database subsequently, I have to fully remove and reinstall plugin to reconnect database

**Comment by sinned130** [comment]
Hello,

same issue for me, but only under Linux (x86_64 Linux 5.2.1-1-MANJARO). I have as dual boot installed windows too and there is not this issue. 

nothing seems to have a impact to make it properly work again. some times its works like a charm but often I got the message "Cannot decrypt message" 

KeePassXC 2.4.3
Browser: Mozilla Firefox 68.0
BrowserPlugin 1.4.6

**Comment by varjolintu** [comment]
@sinned130 Are you using Auto-Reconnect? If so, try to disable it and see if it helps.

**Comment by sinned130** [comment]
@varjolintu No I dont use this function.

**Comment by sinned130** [comment]
Update: the issue is still available.

I found out that I have to close keepassxc first and then to close firefox to make it work again. if I close firefox first it dosent work.

**Comment by varjolintu** [comment]
@sinned130 Do you change/delete/modify your recycle bin in any way? In the current version it can cause a hash change in the extension. This is already fixed in the next version though.
