### ISSUE TITLE
Autotype challenges on macOS 10.12

### ISSUE THREAD

**Issue by HUGHUSR** [keepassxreboot/keepassxc#3351]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
As per previous bug, I cannot get autotype to work in 2.4.x.

I have figured out why -- more or less.

## Current Behavior
[NOTE]: # ( Tell us what actually happens )
When I enter a CMD-SHIFT-V or select "Perform AutoType" from the menu, KeePassXC minimizes and the last file highlighted in Finder has its filename named to (usually) the password of the entry highlighted in KeePassXC.

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )
The problem is that GPG is already using CMD-SHIFT-V to sign files. Since the signature request is not being initiated from withing GPG, apparently things get really confused.
Deselecting the shortcut for GPG in System Preferences for Keyboard does not fix the issue.

Furthermore, trying to use Global AutoType also throws errors, never finding a match either on Name or URL, despite being EXACTLY as in the app.

RECOMMENDED FIX: Enable the ability for a user to select the Perform AutoType key sequence (or, revert to 2.3.x behavior).

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1.
2.
3.

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.4.3
Revision: 5d6ef0c

Qt 5.12.3
Debugging mode is disabled.

Operating system: macOS Sierra (10.12)
CPU architecture: x86_64
Kernel: darwin 16.7.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
 libgcrypt 1.8.4

**Comment by droidmonkey** [comment]
> and the last file highlighted in Finder has its filename named to...

What?? None of this sounds like a problem that KeePassXC can control or change. It sounds like the GPG application is at fault for listening to a global keyboard shortcut even when disabled.

When you press the autotype toolbar button there is no keyboard shortcut pressed. You still experience the same behavior? Points to something totally unrelated to keyboard shortcuts.

**Comment by oh-hello-tomcat** [comment]
For what it's worth, it seems to me that autotype works via shortcut, context menu or toolbar button, unless the target is a popup window. Terminal or websites with forms are ok, but if you have an application that opens a separate login window things go really wrong: credentials are sent to whatever happens to be open in the background: finder, browser, you name it...

**Comment by droidmonkey** [comment]
This could be a limitation/feature of macOS itself.

**Comment by HUGHUSR** [comment]
I don't think this has anything to do with macOS per se. It works
properly, even with pop-ups, on the 2.3.x release chain.
On 7/11/2019 at 8:17 AM, "Jonathan White"  wrote:

	This could be a limitation/feature of macOS itself.

**Comment by oh-hello-tomcat** [comment]
I don't think it has anything to do with macOS either. Just recently updated (keepassxc, not macOS), and it stopped working.

**Comment by oh-hello-tomcat** [comment]
I went back to keepassxc 2.4.0, and things are normal again. Tested with 2.4.1 also and could see the erroneous behavior there, so it seems to have been introduced with 2.4.1.

I'm running macOS 10.14.5 (Mojave), btw.

**Comment by HUGHUSR** [comment]
I can confirm that the problem begins in 2.4.1 (that is, 2.4.0
works).. Furthermore, I highly suspect that the problem has to do with
minimizing KP on autotype.
I can also confirm that there is a conflict between keepassxc and GPG.
For the new autotype key-combo of shift-cmd-V, you must disable GPG
shortcuts in system preferences. I would also recommend that you
integrate the keepassxc keyboard shortcuts into system preferences to
provide visibility of potential app keyboard shortcut conflicts.
On 7/12/2019 at 1:20 AM, "oh-hello-tomcat"  wrote:

	I went back to keepassxc 2.4.0, and things are normal again. Tested
with 2.4.1 also and could see the erroneous behavior there, so it
seems to have been introduced with 2.4.1. 

	I'm running macOS 10.14.5 (Mojave), btw.

**Comment by droidmonkey** [comment]
Yes the change that occurred in 2.4.1 was that instead of raising the last active window, we lowered KeePassXC (see #2883 and #2969). This probably results in the unintended side effect that modal dialogs are not "activated" when the implicit switch to the previously used application occurs.

Can someone provide a simple example application that can be used to replicate this behavior? Does this only impact older versions of macOS?

**Comment by droidmonkey** [comment]
OK I think I found the fix, I tested with Tunnelblick. If I call the `macUtils()->raiseLastActiveWindow()` function just before hiding KeePassXC then everything works as expected.

**Comment by HUGHUSR** [comment]
Hi,

Any progress on releasing the fix you found? It's been three months since you found the fix, but no release. 

Thanks for your update!

**Comment by droidmonkey** [comment]
I honestly forgot about this! PR has been submitted.
