### ISSUE TITLE
Challenge-Response forwarding from mobile devices

### ISSUE THREAD

**Issue by Zocker1999NET** [keepassxreboot/keepassxc#3356]
[TIP]:  # ( Provide a general summary of the feature in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Summary
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
An app on a mobile device simulating a challenge-response device for unlocking your database like a YubiKey. The app can also use an existing security key like YubiKey to respond to the challenge. The PC and mobile device should be connected via the local network. The connection needs to be secured, an idea is shown below.

## Desired Behavior
[NOTE]: # ( Tell us how the new feature should work, be specific )
- Connect both devices to the same network
- If not done already, pair them by pressing a button on both and accepting the pairing request (see commucation section below)
- Type in password and/or select key file in KeePassXC
- Select your mobile device as challenge-response device and click on unlock
- App on mobile device opens and responds to the request of the PC (see commucation section below)
- KeePassXC unlocks database using the response

### Communication between Mobile Device and KeePassXC
Here is an idea how to implement the commuction between the mobile device and the PC.
If someone finds a security issue, please answer with your concerns.

#### for pairing
- App generates before pairing a public key pair, stores private key in a safe way
- KeePassXC sends pairing request via UDP on a common port (can be repeated every 5 seconds)
- App waiting for pairing request answers to request with its public key using TCP
- KeePassXC shows representation of received public key as QR Code
- KeePassXC sends a temporary AES key to the app encrypted with the public key (used below)
- App requests user to take a photo of the QR code for checking that the public key was not modified
  - Alternative: Both devices show a representation of the public key and request the user to verify
- App answers encrypted with the AES key saying that the user verified the pairing
- KeePassXC stores public key for using later

#### for unlocking
- KeePassXC sends request via UDP on a common port, encrypted with the known public key, containing a temporary AES key of KeePassXC for the response, the challenge itself
- App receives request and answers to common port on the PC using TCP encrypted with the AES key saying that the request was received
- KeePassXC increases timeout and shows an ID representing the AES key (e.g. first six digits of hash of AES key)
- App shows the ID representing the AES key so the user can verify that the request is not manipulated
- App asks for (biometric) authentication / challenge-response device / ...
- App answers to challenge via TCP encrypted
- KeePassXC receives response and unlocks database

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
I am using a YubiKey 5 NFC on with my PC and Android phone for unlocking my database (together with a strong password). However I am now trying to unlock the database on a laptop with only USB C ports. So to unlock my database I need to use an adapter or an identical configured YubiKey Type C. So I thought about using my Android device for my laptop as NFC reader for the YubiKey to unlock my database on my laptop. Enabling a feature like that would also enable users who cannot buy a YubiKey can use a biometric locked app on their phone simulating a challenge-response device.

**Comment by droidmonkey** [comment]
We appreciate the idea, but this is very complicated and absolutely prone to attacks. There is very little chance this would ever be implemented. What you have described is basically how [Duo Mobile works](https://duo.com/product/multi-factor-authentication-mfa).
