### ISSUE TITLE
Provide a dark theme for Windows

### ISSUE THREAD

**Issue by Puro00** [keepassxreboot/keepassxc#3358]
How to get Dark theme on Windows? 

I cannot find option in the program

**Comment by phoerious** [comment]
We do not have a dark theme. KeePassXC uses the theme of your system.

**Comment by Puro00** [comment]
I have dark theme on for the system. Even then program doesn't get dark

**Comment by phoerious** [comment]
Qt does not yet support dark mode on Windows. Once it does, it will pick up your theme. It took a while for macOS.

**Comment by underlineGalaxy** [comment]
> Qt does not yet support dark mode on Windows. Once it does, it will pick up your theme. It took a while for macOS.

Is there a way to manually enable dark theme on KessPass XC? I have it on my elementary OS but not on KessPass XC

**Comment by ImportTaste** [comment]
@phoerious Given how low a priority Windows is to the Qt project, I'd like to ask if you could consider integrating this as an option?

[github.com/Jorgen-VikingGod/Qt-Frameless-Window-DarkStyle](https://github.com/Jorgen-VikingGod/Qt-Frameless-Window-DarkStyle/blob/master/DarkStyle.cpp) ([MIT License](https://github.com/Jorgen-VikingGod/Qt-Frameless-Window-DarkStyle#licence))

If you'd like it to be specific to having Dark Theme enabled on Windows, you could use `QSettings settings("HKEY_CURRENT_USER\\Software\\Microsoft\\Windows\\CurrentVersion\\Themes\\Personalize",QSettings::NativeFormat);` and check the value of `AppsUseLightTheme` (0 means dark mode).

**Comment by arigit** [comment]
Windows 10 has a 'dark' switch now. It would be nice if keepassxc would follow the system setting

**Comment by dimon222** [comment]
Was this cancelled? just curious why it got closed

**Comment by droidmonkey** [comment]
It's been implemented in develop
