### ISSUE TITLE
Clear clipboard and gpaste

### ISSUE THREAD

**Issue by FMuro** [keepassxreboot/keepassxc#336]
Guys, thanks a lot for developing this awesome password manager! I'd like to report that the clear clipboard option does not work on Gnome 3.22 (Fedora 25) when the clipboard manager gpaste is enabled (it does otherwise). I've looked this up in Google, this issue has been risen both in keepass and keepassx forums, and also in clipboard manager forums. It doesn't seem to be something easy from either side. I decided to post this here anyway since you're boosting the development of this tool with new ideas, and also because now, under Wayland, auto-type is not an option (I've seen elsehwere that you have ideas to make this work under wayland, that would also be great, indeed a better than clearing the clipboard). Currently, I use a shortcut (ctrl+alt+v) to delete the last entry in gpaste whenever I copy from keepassxc, but I often forget to do this. Maybe there is a way of automatically triggering this sortcut right after copying from keepassxc?

**Comment by phoerious** [comment]
This seems to work with Klipper on KDE.
But it is generally a problem we can't do anything about. We cannot prevent you from pasting the password anywhere and so can't we prevent any application to copy the clipboard contents and store them elsewhere. When the clipboard manager refuses to delete an entry on its own when the clipboard is cleared, we're out of options.

**Comment by droidmonkey** [comment]
I generally consider those clipboard history tools to be a major security risk.

**Comment by FMuro** [comment]
Thanks, phoerious! I'll report this to Gpaste.

droidmonkey, you're right, I'd prefer auto-type support for Wayland, and I appreciate your effort in this direction.
