### ISSUE TITLE
Wiki typo

### ISSUE THREAD

**Issue by onlykey** [keepassxreboot/keepassxc#3363]
https://github.com/keepassxreboot/keepassxc/wiki/Set-up-Build-Environment-on-Windows

**This**
mingw-w64-$(uname -m)-qrencode mingw-w64-($uname -m)-quazip

**should be this**
mingw-w64-$(uname -m)-qrencode mingw-w64-$(uname -m)-quazip

**Comment by droidmonkey** [comment]
Wow that is subtle, didn't even see the difference! Fixed.
