### ISSUE TITLE
AutoType broken between 2.3.3 and 2.3.4 on Windows8.1 x64 with Firefox 68.0 x64 and TreeStyle Tabs extension

### ISSUE THREAD

**Issue by Clouds123** [keepassxreboot/keepassxc#3364]
## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

## Current Behavior
The user name is entered, but the first two characters of the password are also sent to username field. Then it moves to the next Firefox browser tab, opens the Find box at the bottom (as if Ctrl+F was pressed in FF), and then enters the remaining characters of the password in this find field.

## Possible Solution
If the tab you want to auto-type to is the last tab, the AT works fine. Also, there seems to be a conflict between KeePassXC 2.3.4 and TreeStyle Tabs extension, as when the extension is disabled auto-type works OK, even when it's not the last tab..

The shortcut for going to the next tab in FF is Ctrl+TAB, so I'm guessing KeePassXC is sending that combination after the first two password chars are sent, causing it to move to the next tab. It must then be sending Ctrl+F, as this is what opens the find bar at the bottom, before sending the remaining password characters.

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1. Go to https://www.ntlite.com/community/index.php and click on Login button at top right. Make sure it's not the last tab, and the TreeStyle Tabs extension is installed and visible
2. Make the username field is active by clicking on it
3. Switch to KeePassXC and do Auto-type

**Comment by Clouds123** [comment]
All versions after 2.3.3 conflict with the TreeStyle Tabs extension. v2.3.3 has no conflict and works fine with TreeStyle Tabs.

**Comment by droidmonkey** [comment]
First off, we are at version 2.4.3 right now, please update.

Secondly, I don't know what TreeStyle Tab extension does, but we are not doing anything with autotype besides pressing keys programmatically. Firefox has a habit of delaying the switch between input fields when you press tab. You can go into KeePassXC settings and increase the auto-type typing delay which usually fixes this issue.

**Comment by Clouds123** [comment]
I have updated to 2.4.3, but went back through older versions to see where the problem/conflict was introduced, as 2.3.3 does not have any conflict with TreeStyle Tabs (ie. 2.3.3 Auto-Type works fine with TreeStyle tabs extension enabled) . Something changed between 2.3.3 and 2.3.4 that has caused this conflict.

TreeStyleTab adds a pane to the left of the FF window that shows tabs in a treeview.

**Comment by droidmonkey** [comment]
No auto-type code was modified between 2.3.3 and 2.3.4.

**Comment by Clouds123** [comment]
Something changed that has caused a conflict though.

**Comment by Clouds123** [comment]
I noticed the size of the app increased quite a lot (more than 1MB).
