### ISSUE TITLE
Add ability to get password of specific entry without password input if database is already unlocked

### ISSUE THREAD

**Issue by rook59** [keepassxreboot/keepassxc#3366]
## Summary
It is currently not possible to get passwords from an unlocked keepassxc database. The ability to do so would be quite nice.
I know this can be a security issue in some situations so better only opt in and not default.

## Desired Behavior
For KeePassHTTP there are already a few scripts/libs which can do this but KeePassHTTP has 
been deprecated and will probably dropped soon.

Examples:
https://github.com/berrnd/KeePassHttpCli
https://github.com/Kjarrigan/keepasshttp-ruby

It could look like:
`keepassxc-cli show --without-password <entry title>`
`keepassxc-cli show --unlocked-database <entry title>`

## Context
Adding this would help in many situations, for example cli scripts.

**Comment by droidmonkey** [comment]
This will likely not be implemented, but it could be done by anyone who wants to use the proxy service. The problem is you have to store the access/encryption key and respond to the api. Native integration between the cli and the gui app is not in the cards.

**Comment by dot-mike** [comment]
For anyone looking for an altermative, check out https://github.com/nwwdles/kpxcpc
