### ISSUE TITLE
macOS 10.11.6 Crash on startup: Exception Type: EXC_CRASH (Code Signature Invalid)

### ISSUE THREAD

**Issue by Clouds123** [keepassxreboot/keepassxc#3367]
## Current Behavior
After launch it crashes with Exception Type: EXC_CRASH (Code Signature Invalid) and the "KeePassXC quit unexpectedly." error dialog is displayed, followed by a dialog saying "'KeePassXC.app' is an application downloaded from the internet. Are you sure you want to open it?". Clicking Open on the second dialog does nothing (obviously because it has already crashed).

The exception shows the Code Signature is invalid.

KPXC 2.3.3 works without issue. I haven't tried other in-between versions yet on macOS.

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1. Launch the KeePassXC 2.4.3 on macOS 10.11.6
2.
3.

**Comment by droidmonkey** [comment]
We do not support that version of macOS
