### ISSUE TITLE
Help Using Reference Fields

### ISSUE THREAD

**Issue by xefil** [keepassxreboot/keepassxc#3369]
Hi all,
I've moved from Keepass2 to KeepassXC (portable). Everything works fine, but I'm not able t ouse reference fields (i.e. add a new entry with username pointing to oldd entry).
The imported database from previous Keepass is able to work with existing reference fields ({REF:U@I:22....) but have no idea how to add a new entry/reference field.
In Keepass2 there was an option on the popup in which I was able to add a reference field into another field, but here it's missing.
Could someone help me?
I'm using version 2.4.3 portable on Windows 10.
Thanks!

**Comment by droidmonkey** [comment]
You do this using a "clone" of an entry. Simply right click the entry you want to reference and click on "Clone Entry...". Make sure you check the box that says reference username and password fields.

**Comment by xefil** [comment]
Ok, Now I've understood. It's shown only when I clone. It means I can reference ONLY username and / or Password?

**Comment by droidmonkey** [comment]
You can reference any field using the KeePass syntax. We do not have a GUI aid to make it easy though. That is covered under #433

**Comment by xefil** [comment]
ok,many thaks!
Simon
