### ISSUE TITLE
Question: Auto Type with matching for URL

### ISSUE THREAD

**Issue by jrodan** [keepassxreboot/keepassxc#337]
Hi together, 

isn't a matching via URL easier to handle than a matching via the browser title?
Isn't this method used due to cross platform problems?

This would be really a helpful feature for me. 

Thanks and regards

**Comment by phoerious** [comment]
The window title is the only thing we can get from a window. There is no direct way to access the current URL of a browser tab.
But you can install the browser extension PassIFox (Firefox) or chromeIPass (Chrome) and use KeePassHTTP for communicating with KeePassXC which will do matching based on URLs.
