### ISSUE TITLE
SSH Agent integration should work better

### ISSUE THREAD

**Issue by marco-brandizi** [keepassxreboot/keepassxc#3370]
## Summary
The current way to use KeePassXC with the ssh agent is painful and it could be better

## Details
I had to make a few attempts before understanding how to work with ssh-agent under my Mac (macOS 10.14.5, KeePassXc 2.4.3). 

The only way I see is: 
- Start ssh-agent via eval $(ssh-agent)
- from the same terminal window, start KeePassXC via command line and as a background process ( '&' )
- from the same window, Start ssh to one of the host that has keys inside KeePassXC

this is because every run of ssh-agent starts a new agent, with its own PID and set of keys, and one has to ssh-connect using the same that KeePassXC is using (so, in the procedure above, both share the same env variables and hence point to the same agent). 

## Desired Behavior
A simple solution could be:
- KeePassXC starts an ssh-agent when it launches (or takes note of the existing env variables and use the agent they point to)
- KeePassXC has a config option to tell where it should save the variables that are needed to point to the ssh agent it started. This will allow KeePassXC to save the output of `ssh-agent` (when it launches it at startup) to a .sh file stored in a known location, so my profile could simply `eval` that file to direct ssh to the right agent.

**Comment by droidmonkey** [comment]
I just tested this and it worked perfectly for me without a single change to my mac. You might have to restart KeePassXC if you didn't have ssh-agent running prior to.

**Comment by droidmonkey** [comment]
> this is because every run of ssh-agent starts a new agent, with its own PID and set of keys

This is not how ssh-agent works or is supposed to work. It runs as a daemon and will not use a new PID or key list unless it died or you killed it.

**Comment by marco-brandizi** [comment]
@droidmonkey, thanks, it seems that as soon as something tries to access the agent subsystem (eg, `ssh-add -l`) a new agent is launched if none was running. So, even without steps 1-2 from your comment, I can launch KeePassXC when no agent is active, launch the terminal and see that ssh-add -l yields values.

But, if one keeps typing ssh-agent, new daemons are started, though the existing env variables point to the first one.

It's confusing, but works. Would be good to document the way to work with this feature (the FAQs don't say much about it, I got more info from elsewhere ([[1]][[2]])

[1]: https://www.techrepublic.com/article/how-to-integrate-ssh-key-authentication-into-keepassxc/
[2]: https://blog.valouille.fr/post/2018-03-27-how-to-use-keepass-xc-with-ssh-agent/

**Comment by droidmonkey** [comment]
This is more about something wrong with your system / environment and not KeePassXC.
