### ISSUE TITLE
KeepassXC won't start

### ISSUE THREAD

**Issue by Buliwif** [keepassxreboot/keepassxc#3372]
Hi, 
Im' currently using Ubuntu 18.04.2LTS desktop.
I use snapd to install Keepassxc  but when I try to start the software : 
    > he appears for few seconds on my menu bar
    > my mouse let me thing that something happend cause the cursor is loading
    > after few second, keepassXC dissapear from my menubar and it's over.

is there something I miss ?

**Comment by Buliwif** [comment]
I have to say that with the official AppImage, it work like a charm

**Comment by jmks** [comment]
I'm having the same problem on KDE Neon 5.16

```
$ snap version          
snap    2.38+18.04
snapd   2.38+18.04
series  16
neon    18.04
kernel  5.0.0-23-generic

$ snap list keepassxc
Name       Version  Rev  Tracking  Publisher       Notes
keepassxc  2.4.3    378  stable    keepassxreboot  -
```
