### ISSUE TITLE
Donate via normal bank transfer

### ISSUE THREAD

**Issue by markusd112** [keepassxreboot/keepassxc#3374]
Please give the possibility to send a one time donation via normal bank transfer (IBAN / BIC) or normal credit card. I don't have paypal...

**Comment by droidmonkey** [comment]
Create a PayPal account and then you can use your bank/card. You can also donate through Patreon or LibraPay.

**Comment by markusd112** [comment]
Patreon and LibraPay are not for one time donations, only for recurring donations. Maybe it's possible to offer a link to "paypal guest payment", where the payer doesn't need to create a paypal account. For myself: I will not create a paypal account, sorry.

**Comment by droidmonkey** [comment]
You can do a one time Patreon donation by starting it and immediately canceling the donation.
