### ISSUE TITLE
Debian package issues: still on 2.3.4 and "marked for autoremoval"

### ISSUE THREAD

**Issue by gwerbin** [keepassxreboot/keepassxc#3377]
## Expected Behavior

Debian "unstable" (Sid) package is up-to-date with Git releases (2.4.3 as of now), Debian "testing" (Bullseye) is on > 2.4.0, and Debian "stable" (Buster) has a > 2.4.0 backport.

It's too bad  2.4.0 didn't make it into Buster, but hopefully a backport will be possible.

## Current Behavior

All Debian versions have 2.4.3, and there's this warning on https://tracker.debian.org/pkg/keepassxc:

> Marked for autoremoval on 13 August due to [yubikey-personalization](https://tracker.debian.org/pkg/yubikey-personalization): [#931081](https://bugs.debian.org/931081) high

> Version 2.3.4+dfsg.1-1 of keepassxc is marked for autoremoval from testing on Tue 13 Aug 2019. It depends (transitively) on [yubikey-personalization](https://tracker.debian.org/pkg/yubikey-personalization), affected by [#931081](https://bugs.debian.org/931081). You should try to prevent the removal by fixing these RC bugs.

## Possible Solution

Publish a new version of KeepassXC to the Debian repo (I have no idea how to do this, although I've been slowly reading up on Debian packaging).

I'm honestly not 100% sure what the alert means. I'm relatively new to Debian and there's a lot of jargon floating around. It *looks like* there was a bug in the current yubikey-personalization v1.19.3-3, so they are publishing a new version of the package v1.20.0-1 (currently on unstable/Sid). So it's possible that publishing a new package for KeepassXC would obviate this issue.

It appears that KeepassXC depends on [yubikey-personalization](https://packages.debian.org/source/sid/yubikey-personalization) because that is the source package for [libykpers](https://packages.debian.org/sid/libykpers-1-1).

KeepassXC has a ">=" version dependency on libykpers, so maybe the autoremoval warning will go away once the new package version is released.

## Steps to Reproduce

Visit [https://tracker.debian.org/pkg/keepassxc](https://tracker.debian.org/pkg/keepassxc) as of July 14, 2019.

## Context

Installing KeepassXC from the official Debian package repo, even on testing and unstable, results in an out-of-date version that doesn't work with the latest version of the browser extension.

And (unless I misunderstand) it looks like the package will be removed entirely unless some kind of action is taken, although I have no idea what that action is supposed to be.

## Debug Info

N/A

**Comment by phoerious** [comment]
We do not maintain the Debian package. Please take it to the Debian bug tracker.
