### ISSUE TITLE
Add keyboard shortcuts to documentation

### ISSUE THREAD

**Issue by new-on-github** [keepassxreboot/keepassxc#3378]
I cannot find a documentation of the shortcuts working in keepassxc. Is there a documentation of the available shortcuts? The shortcuts I use, i found by trial and error, this is maybe not the best user experience.

**Comment by cirulls** [comment]
[This page](https://github.com/keepassxreboot/keepassxc/blob/develop/docs/KEYBINDS.md) gives you the list of keyboard shortcuts. Hope it helps...

**Comment by new-on-github** [comment]
Thanks a lot. This looks very good.

Maybe this could be added to the preferences menu of keepassxc as enhancement. The most users will search for it in the application itself.
