### ISSUE TITLE
Autotype dialog does not display on main screen

### ISSUE THREAD

**Issue by wummel** [keepassxreboot/keepassxc#338]
On Linux/QT5: if the keepassxc main windows is on another virtual screen, the autotype
dialog is not displayed on the current screen but on that of the keepassxc main windows.

## Expected Behavior

The autotype dialog box should open on the current screen.

## Current Behavior

The autotype dialog box opens on the screen where the keepassxc main windows is.

## Possible Solution

It seems in Qt5 the Qt::WA_X11BypassTransientForHint option at https://github.com/keepassxreboot/keepassxc/blob/develop/src/autotype/AutoTypeSelectDialog.cpp#L39 does not work anymore.

## Steps to Reproduce (for bugs)

1. Open keepassxc and switch screen
2. Activate autotype
3. See Dialog open on inactive screen (where keepassxc windows is)

## Context

Switching screens is annoying

## Your Environment

* KeePassXC version/commit used: b9279f73fa58d75e1ec88f734f3c77c0f015a348
* Qt version (e.g. Qt 5.3):  Qt 5.3.2, libgcrypt 1.6.3
* Compiler (e.g. Clang++3.6.0): g++-4.9.real
* Operating System and version: Debian Linux 8.7

**Comment by phoerious** [comment]
It works well for me. Do you have any specific window rules which might override WA_X11BypassTransientForHint? If your window manager thinks the window should be opened on the screen where the main window is, there is very little we can do about it. Window manager is boss.

**Comment by technodrome** [comment]
I have the same problem with MacOS Sierra 10.12.4. I use several desktops and autotype window appears wherever it wants. 

Sometimes it is shown on the desktop where the app is running. 
At other times it has focus (so ENTER can confirm the first entry) but the autotype window is not shown  - it does not switch desktops so I have to manually go through all of them to actually find the autotype window. This is very annoying.

**Comment by wummel** [comment]
I switched to XFCE 4.12 with xfwm (Debian Linux 9), and it works now for me.
Previous desktop was KDE with kdm. So it was definitely a faulty window manager
configuration.
