### ISSUE TITLE
Feature change request: ignore empty password field on lock screen

### ISSUE THREAD

**Issue by CodingSpiderFox** [keepassxreboot/keepassxc#3380]
## Summary
When someone uses a key file only to unlock the database (and enables the checkbox for it), but accidentally also enables the "password" checkbox on the lock screen but enters no character into the password field, KeepassXC should only consider the key.

That would speed up the user a little and avoid an unnecessary interruption of his work flow.

**Comment by droidmonkey** [comment]
This is fixed already in 2.5.0

**Comment by CodingSpiderFox** [comment]
Thanks :)
