### ISSUE TITLE
Feature Request - Disable History By Default

### ISSUE THREAD

**Issue by trymeouteh** [keepassxreboot/keepassxc#3385]
For security I think these settings should be disabled by default. 

General->Basic Settings->Remember Last Databases
General->Basic Settings->Remember Last Key Files And Security Dongles
General->Basic Settings->Load Previous Databases On Startup

If someone gets into your computer and opens the KeePassXC, they will see where your KeePass file is stored on your device. This is especially the case if you rename the extension from kdbx to something else to hide the file on your computer.

I do not want this feature gone, just disable out of the box.

**Comment by droidmonkey** [comment]
This won't happen, most users want the last used database remembered. Far fewer want it disabled.
