### ISSUE TITLE
Auto-Type & Chromium-based Edge Insider issues

### ISSUE THREAD

**Issue by zmni** [keepassxreboot/keepassxc#3386]
1. If you have an entry with title `Microsoft`, when performing auto-type via shortcut (<kbd>ctrl</kbd> + <kbd>alt</kbd> + <kbd>a</kbd>) on other site, auto-type window always show up displaying the target site and Microsoft entry.
2. If the window title doesn't match anything, auto-type will continue fill the form with `Microsoft` entry details.

## Expected Behavior
1. Do not show auto-type window with Microsoft entry in it, and perform auto-type normally on target site.
2. Display warning no window title match. Do not fill it with Microsoft details.

## Current Behavior
1. If you have an entry with title `Microsoft`, when performing auto-type via shortcut (<kbd>ctrl</kbd> + <kbd>alt</kbd> + <kbd>a</kbd>) on other site, auto-type window always show up displaying the target site and Microsoft entry.
2. If the window title doesn't match anything, auto-type will continue fill the form with `Microsoft` entry details.

## Possible Solution
Perform auto-type using <kbd>ctrl</kbd> + <kbd>shift</kbd> + <kbd>v</kbd>.

## Steps to Reproduce
1. Create entry with title `Microsoft`.
2. Go to login page on any sites in your entry list other than Microsoft. Example `https://github.com/login`
3. Perform auto-type using <kbd>kbd</kbd> shortcut (<kbd>ctrl</kbd> + <kbd>alt</kbd> + <kbd>a</kbd>)

## Context
Only happened in Chromium-based Edge Insider.

## Debug Info
```
KeePassXC - Version 2.4.1
Revision: 7bafe65

Qt 5.12.2
Debugging mode is disabled.

Operating system: Windows 8.1 (6.3)
CPU architecture: x86_64
Kernel: winnt 6.3.9600

Enabled extensions:
- Auto-Type
- Integrasi Peramban
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
libgcrypt 1.8.4
```

**Comment by droidmonkey** [comment]
This isn't a bug, per say. We are not going to filter out specific examples of where auto-type entry matching fails. You can tune the behavior of auto-type matching in the application settings.
