### ISSUE TITLE
MacOS 2.4.3 can't open database that Windows and Keepass2Android can

### ISSUE THREAD

**Issue by j-hat** [keepassxreboot/keepassxc#3391]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
The database should have unlocked when I entered the correct password.

## Current Behavior
[NOTE]: # ( Tell us what actually happens )
I get this error message: 
`Error while reading the database: Invalid credentials were provided, please try again.
If this reoccurs, then your database file may be corrupt.`

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
Uncertain. Creating a new DB from Mac and trying to unlock that does work. The broken database was created about a year ago from Windows.

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )
I can't access my passwords from my Database on my work Macbook, I have been getting my passwords from my Android phone (Keepass2Android) and sending them over securely.

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.4.3
Revision: 5d6ef0c

Qt 5.12.3
Debugging mode is disabled.

Operating system: macOS Mojave (10.14)
CPU architecture: x86_64
Kernel: darwin 18.5.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
 libgcrypt 1.8.4

**Comment by droidmonkey** [comment]
As the message states, the file may be corrupt. Try moving the file over to your Mac again.

**Comment by j-hat** [comment]
@droidmonkey It's the same file shared using cloud storage. I've tried restoring it several times.

**Comment by droidmonkey** [comment]
You can try resetting the master password of the database. Also, for testing, try sharing the known working database, make a change, then see if it still works after sync.

**Comment by j-hat** [comment]
OK, I created a new DB, it seems when I write a new entry to it then close it, it's no longer able to be opened on Mac. I then transferred the new DB to android and I can open it with Keepass2Android.

**Comment by droidmonkey** [comment]
What service are you using for cloud sync? Are you saving this new test database to that same service?

**Comment by j-hat** [comment]
I just tried again but saving the new test database to local storage, not
cloud storage, and the same problem occurs - after closing the database,
the password no longer unlocks it, and the same error message appears.

**Comment by droidmonkey** [comment]
Do you only have the password checkbox checked on the unlock page? Clearly our program can unlock databases... So I'm leaning on some sort of fundamental misunderstanding of the program

**Comment by droidmonkey** [comment]
Do you only have the password checkbox checked on the unlock page? Clearly our program can unlock databases... So I'm leaning on some sort of fundamental misunderstanding of the program

**Comment by j-hat** [comment]
Obviously, it can. But in my case, it doesn't. I used this program for a long time with no issues and it just stopped working one day. The password and the key file checkboxes are ticked. 

I'm not saying that this is a bug that will occur for everyone, obviously. However, it seems that there is something wrong here. Can I provide any more info?

**Comment by droidmonkey** [comment]
If you are not using a key file, uncheck that box

**Comment by j-hat** [comment]
Okay, that has fixed the issue for me, so you were right, haha.

That being said, I think the error message is misleading, and considering that I had used to program for a long time and couldn't figure out how to fix this, perhaps some UI changes could be made here. For a user that isn't aware of what key file really is, like myself, it was easy to make the mistake of browsing for and opening my .kdbx file in that box, then not understanding why it says I am using an incorrect password / corrupt database file.

**Comment by droidmonkey** [comment]
Already made significant ux/ui changes to the unlock page for 2.5.0. This problem won't happen again after it is released.

**Comment by vwettenh** [comment]
I have the same problem still, I even tried 2.5.0-snapshot 5th of Sep 2019 release. We have keepass file in the windows file share, and all the other people uses windows expect me who uses Mac. I always get that error message: 
Error while reading the database: Invalid credentials were provided, please try again.
If this reoccurs, then your database file may be corrupt.

**Comment by droidmonkey** [comment]
Likely a totally different problem

**Comment by vwettenh** [comment]
> Likely a totally different problem

Any suggestions how to troubleshoot this further? It still occurs for me.

**Comment by droidmonkey** [comment]
There is nothing further I can suggest given the information you provided.

**Comment by DanTheManUK** [comment]
I can confirm this is still a problem.

Out of my team of 12 using the same keepass file, 2 with mac cannot open the DB, 10 with Windows can.
