### ISSUE TITLE
Taskbar preview of unlocked databases should be cleared when locked

### ISSUE THREAD

**Issue by luixxiul** [keepassxreboot/keepassxc#3392]
[TIP]:  # ( Provide a general summary of the feature in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Summary
[NOTE]: # ( Provide a brief overview of what the new feature is all about )

Screenshot of locked databases is not cleared on "Task View" on Windows 10.

Steps to reproduce the issue:

1. Run the programm
1. Open the database on Windows 10
2. Open Application Settings
3. Go to Security
4. Enable and set `Lock databases after inactivity of` to `10` sec
5. Click OK
6. Change the focus to another window
7. Wait around 10 seconds
8. Run Task View mode

Actual result: there appears the screenshot of the unlocked window.

## Desired Behavior
[NOTE]: # ( Tell us how the new feature should work, be specific )

The screenshot should be cleared or replaced with a screenshot of the locked window.

## Possible Solution
[NOTE]: # ( Not required, but suggest ideas on how to implement the addition or change )

I'm not sure if it is possible for an application to change that Windows 10's behavior.

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )

**Comment by droidmonkey** [comment]
I'm pretty sure this is not possible. The taskbar is caching the "last known view" that the window painted. When a window is minimized or sent to the tray it is actually not updated at all from a GUI standpoint.

**Comment by luixxiul** [comment]
I see. The substantial issue here is that if you click the eye button in the General tab to show the password and minimize the window, both username and password are displayed in a plain text.

**Comment by droidmonkey** [comment]
The attack scenario on this is very limited. If someone else can see this thumbnail preview then they can do whatever they want at this point.

**Comment by gnr8shn** [comment]
> The attack scenario on this is very limited. If someone else can see this thumbnail preview then they can do whatever they want at this point.

When screen sharing using Teams/Zoom etc I often use Alt-Tab or Windows-Tab. If screen recording is in place - or a remote viewer with good eyesight - the password is visible in the "last known view".

**Comment by droidmonkey** [comment]
This is no longer an issue due to hiding the window from screen recording.
