### ISSUE TITLE
Replace GlobalEventMonitor (NSEvent) with CGEventTap

### ISSUE THREAD

**Issue by georgesnow** [keepassxreboot/keepassxc#3393]
I realized you closed off the other ticket, but I found the reference in documentation from  Apple (others ...).

https://developer.apple.com/videos/play/wwdc2019/701/

refere to: 19:45

The CGEventTap appears to be the appropriate way to handle hotkeys with carbon being deprecated/removed.

GlobalEventMonitoringMask as reference here still technically uses Carbon (difference RegisterEVentHotKey includes the keycode):
https://www.sciencedirect.com/science/article/pii/S1742287616300524

" This parent class has members block and mask, which are initialized using the function's parameters. addGlobalMonitorForEventsMatchingMask then calls InstallEventHandler (Carbon Event Manager) with a target parameter of GetEventMonitorTarget() and a handler GlobalObserverHandler."

And other reference:
https://boredzo.org/blog/archives/2010-01-18/carbon-dated
"No, those NSEvent class methods introduced in Snow Leopard are not direct replacements for Carbon Event Manager hot-keys. You’d have to sift through the events yourself, whereas Carbon Event Manager filters them for you and only calls your function when your key is pressed. The correct analogue would be CGEventTap.)"

Example of taps:

https://github.com/tekezo/osx-event-observer-examples

**Comment by droidmonkey** [comment]
I'll look into it, but I don't see it changing for 2.5.0

**Comment by georgesnow** [comment]
Understood and from what I can tell from the code it looks you are using CGEvent already to capture the key code.

**Comment by georgesnow** [comment]
I am also not convince CGEventCreateTap is correct. I think their is misunderstanding of the depecrated frameworks of Carbon (there **3 frameworks** - Application Services, Carbon, and Core Services - ). You might consider going back to Carbon Event Manager (this falls under the Carbon Framework **not** Core Services).


I followed all the references below.


**Carbon Frameworks:**
http://mirror.informatimago.com/next/developer.apple.com/referencelibrary/API_Fundamentals/Carbon-api-date.html
 
 **Carbon deprecations _("Carbon Core, a subframework of the Core Services umbrella framework")_:**

https://developer.apple.com/documentation/coreservices/carbon_core

https://developer.apple.com/library/archive/releasenotes/General/CarbonCoreDeprecations/index.html#//apple_ref/doc/uid/TP40012224-CH1-SW4

**These mail corresponds to those above (ie Aliases.h under CoreServices/CoreServices.h -- Alias Manager Reference)**
http://mirror.informatimago.com/next/developer.apple.com/documentation/Carbon/Reference/CoreServicesReferenceCollection/CoreServicesReferenceCollection.pdf

**Comment by georgesnow** [comment]
@droidmonkey I have confirmed what i said in the other post. KeePassXC while addGlobalMonitor:NSEventMaskKeyDown is registered as a monitor (with GAutotype would be all theme) will view all keypresses of all other apps. (Screenshot and code below.) I added the NSLog line so it would it printout the event. In the screenshot you will see _KeePassXC_ is the process viewing the keypresses NOT a callback from OS. Provided you must have the Accessibility option enabled, but you need that in order for Global Autotype to work anyway. 



![keepassxc-globaleventmonitor](https://user-images.githubusercontent.com/12751441/61798122-bf9fed00-adf6-11e9-8fba-71d434348de8.png)


**/keepassxc/src/gui/macutils/AppKitImpl.mm**

> void* AppKit::addGlobalMonitor(CGKeyCode keycode, CGEventFlags modifier, void* userData, void (*handler)(void*))
> {
>     return [static_cast<id>(self) addGlobalMonitor:NSEventMaskKeyDown handler:^(NSEvent* event) {
>         NSLog(@"key read by app %@", event.characters);
>         if (event.keyCode == keycode && (event.modifierFlags & modifier) == modifier) {
>             handler(userData);
>         }
>     }];
> }

**Comment by georgesnow** [comment]
@droidmonkey following up to see if you made any further consideration on what i found?

**Comment by droidmonkey** [comment]
No I haven't to be honest. Did you modify the KeePassXC code in your example? I am a bit confused by what you did.

**Comment by georgesnow** [comment]
I did but just the line in the NSEvent handler to print the "event" the app is viewing to the Console:

_NSLog(@"key read by app %@", event.characters);_

This type of event has a bunch of characteristics/methods. One of them is "characters" (another is value i believe etc..50=~ etc..). ie the key that is being pressed. 


And when you look at the Console you can see the process viewing the key presses is "KeePassXC". So **all key presses** get **"viewed" by KeePassXC** that are outside that app regardless of modifiers. The global event monitor is having the app itself basically look at all keyboard events on the system waiting to see match. **Not a callback.** Hence why you need to have "Accessibility" turned on for KeePassXC in the privacy settings (CGEventTap does something similar.)

**Comment by georgesnow** [comment]
@droidmonkey so the short version of what I am getting at is. The portion of the Carbon framework for hotkeys is **_not_** deprecated (see my above posts and works on Catalina). And is really seems like still the appropriate API to use for this situation.

And as per Apple documentation _"Event monitors should be used only when there is no other way to solve your problem."_

**Comment by georgesnow** [comment]
@droidmonkey just as an update to confirm. The 3 apps I know use the Carbon API for global hot keys still work and don’t require Full keyboard permissions To view all key presses

**Comment by georgesnow** [comment]
On Catalina

**Comment by georgesnow** [comment]
@droidmonkey closing issue. reverted to back to carbon api.

**Comment by droidmonkey** [comment]
yup thank you
