### ISSUE TITLE
Cant follow the "Building inside a Docker container" instructions

### ISSUE THREAD

**Issue by ashjas** [keepassxreboot/keepassxc#3394]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )
I need to build appimage for the latest snapshot in develop branch, for which i follow the official:
[wiki](https://github.com/keepassxreboot/keepassxc/wiki/Building-KeePassXC),but i end up in docker error, for which i cant seem to find a solution.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
The docker image is built

## Current Behavior
[NOTE]: # ( Tell us what actually happens )
I issue the command:
`docker build --no-cache -t keepassxc/ubuntu:14.04 .`
which ends up in the below error:
`unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /home/user/keepassxc/Dockerfile: no such file or directory`

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
run the above command.

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )
I need to have a appimage for a snapshot with the advanced search feature, that is not yet integrated in to the stable branch.

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - on develop branch as of 21 July 2019

Operating system: Ubuntu 18.04
CPU architecture: 64Bit
Kernel: 4.15.0-54-generic

**Comment by droidmonkey** [comment]
Advanced search is in 2.4.0 and above

**Comment by droidmonkey** [comment]
We provide pre-built appimages of the develop branch here: https://snapshot.keepassxc.org

**Comment by droidmonkey** [comment]
I also updated the docker instructions.
