### ISSUE TITLE
Modified date vs Accessed date

### ISSUE THREAD

**Issue by Organizer21** [keepassxreboot/keepassxc#3395]
I've noticed for a while that the "Accessed" date generally also triggers the "Modified" date (or it happens for some reason that I don't understand), which is more than confusing as I would only expect the Modified date to trigger if I actually did a change to the entry as right now the whole column becomes rather pointless in my eyes at least. 

E.g. I just wanted to compare two DBs (due to an issue) and check which entries I had updated in the one as to manually update them in the other, but with at least how my DB looks (pending it's not just my issue) that job is not an easy one. I am confused as to why I have so many entries seemingly in sync (modified/accessed date) when I have not updated the entries. Any clarity would be welcome.

KeePassXC - Version 2.4.3
Revision: 5d6ef0c
Operating system: Windows 10 (10.0)
CPU architecture: x86_64
Kernel: winnt 10.0.17763

**Comment by droidmonkey** [comment]
See #2005 and #2368

**Comment by Organizer21** [comment]
> See #2005 and #2368

Cheers, had a quick search but failed to come across these. Could really need a "real" modified date in the UI but I now see that there are reasons it's showing as it currently is.
