### ISSUE TITLE
Translation source is out of sync in translation files

### ISSUE THREAD

**Issue by priv** [keepassxreboot/keepassxc#3397]
## Expected Behavior
All language files should have same source strings as in keepassx_en.ts, or localizations will fail.

## Current Behavior
Source strings are seriously out of sync.  Transifex does not have correct information either.

e.g.
```
keepassx_en.ts:
<source>Use DuckDuckGo service to download website icons</source>
<source>Include beta releases when checking for updates</source>
Other ts files:
<source>Use DuckDuckGo as fallback for downloading website icons</source>
<source>Include pre-releases when checking for updates</source>

```
## Possible Solution
Could you please update the source strings in github and transifex?

## Steps to Reproduce
N/A

## Context
I'm trying to complete traditional chinese language files but strings missing in UI are not fixable due to the problem mentioned above.

**Comment by droidmonkey** [comment]
Yes we'll update soon. I have a rather large accessibility PR I need to submit first.
