### ISSUE TITLE
Use stderr for CLI password prompt

### ISSUE THREAD

**Issue by stephen-dexda** [keepassxreboot/keepassxc#3398]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

foo="$(keepass-cli show \<db\> -a \<attr\>)" should display "Insert password to unlock \<db\>" and store \<attr\> in $foo.

## Current Behavior
[NOTE]: # ( Tell us what actually happens )

Shows no prompt, and stores "Insert password to unlock \<db\>\n\<attr\>" in $foo.

With -q, stores \<attr\> in $foo, but still shows no prompt.

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )

Send the prompt to stderr so it is printed instead of captured. This is a widespread convention in *nix tools (e.g. "read").

isatty() could also be used if there's some reason not to unconditionally behave this way.

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )

This isn't fixed by #831, as no prompt is shown at all using that option.

When a script is being run interactively, the user needs to be prompted for their password.

A workaround is to manually echo a prompt to stderr beforehand, but there should be a way to get keepassxc-cli to behave similarly to other CLI tools.

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.4.3

**Comment by louib** [comment]
> Send the prompt to stderr so it is printed instead of captured. This is a widespread convention in *nix tools (e.g. "read").

Interesting, I didn't know about that. Do you have other examples of that, or a reference?
[here's the corresponding line](https://github.com/keepassxreboot/keepassxc/blob/6ae27fa47b070902eabb44ebab68d471eb68d0e9/src/cli/Utils.cpp#L111)

**Comment by stephen-dexda** [comment]
Off the top of my head, another prompt example with a common tool is `curl -u <username> <url>`, which will prompt for a password on stderr (you can check by redirecting stderr to null (append `2>/dev/null`) and see that the prompt disappears).

Basically only send the requested information (i.e. the attribute in this case) to stdout, and send everything else to stderr. Then you'll get sensible behaviour with assignment, piping etc.

Some reference:

https://unix.stackexchange.com/questions/336983/when-to-use-standard-error-stream-in-command-line-application/336989#336989
https://www.jstorimer.com/blogs/workingwithcode/7766119-when-to-use-stderr-instead-of-stdout

**Comment by louib** [comment]
@stephen-dexda makes sense, thanks for the suggestion and references!
