### ISSUE TITLE
Memorable Password Generator

### ISSUE THREAD

**Issue by bandi30** [keepassxreboot/keepassxc#3401]
[TIP]:  # ( Provide a general summary of the feature in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Summary
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
Hi, can you please add a generator for passwords that can handel memorable passwords? for example, i would like to generate passwords like
trouble1309@Beautiful@Once@Wait
substances16(character(Tube(who
Workers671#Substances#dream#try
Material684-Gentleman-Bean-coat
branches293]adjective]wrong]lct
and so on. please if you have SafeInCloud just check this feature there. I like to rather use keepassxc because its open source and has a great comunity, unlike SafeInCloud which is only a single person behind, have no Linux Integration and not much future for handling crypto-currency related problems in the future. I just cound on you. Keep up the good work you guys. thank you.

## Desired Behavior
[NOTE]: # ( Tell us how the new feature should work, be specific )

## Possible Solution
[NOTE]: # ( Not required, but suggest ideas on how to implement the addition or change )

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )

**Comment by droidmonkey** [comment]
![image](https://user-images.githubusercontent.com/2809491/61838241-62d41f00-ae56-11e9-83c1-10dd34218b22.png)
