### ISSUE TITLE
General option "Save DB after change" does not work

### ISSUE THREAD

**Issue by thowi84** [keepassxreboot/keepassxc#3403]
The checkbox for saving the database after changes is checked and preferences saved by clicking "ok". But the database won't be saved after changes. For testing purposes I added a password and waited minutes. Then I needed to click "save database" in the menu bar, because it is not being saved automatically.

## Debug Info
KeePassXC - Version 2.4.3
Revision: 5d6ef0c

Qt 5.12.3
Debugging mode is disabled.

Operating system: macOS Mojave (10.14)
CPU architecture: x86_64
Kernel: darwin 18.6.0

Enabled extensions:
- Auto-Type
- Browser-Integration
- SSH-Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
 libgcrypt 1.8.4

**Comment by droidmonkey** [comment]
Are you saving the database to disk or cloud storage? It certainly works for me on both Windows and MacOS.

**Comment by thowi84** [comment]
I am saving the database to dropbox. But after two restarts of the program it seems to work. I will monitor that for the next time and when I see any chance to reproduce the problem I will post it here.

**Comment by wolframroesler** [comment]
Did you uncheck "Safely save database files" on "Application settings -> Basic settings -> File management"? This check box should be off when the database is in a Dropbox folder.
