### ISSUE TITLE
Force re-authentication before CSV export

### ISSUE THREAD

**Issue by CodingSpiderFox** [keepassxreboot/keepassxc#3404]
Imagine you leave a friend with not so nice intentions a little while on PC while you go to the toilet etc. 

He could easily export all keys to CSV and steal that file. To make that a bit harder, a re-authentication would be useful.

**Comment by phoerious** [comment]
He could also change your password and copy the file or dump the memory or screenshot your password manager and so on.
Encryption and authentication are two different things. There is no inherent protection coming from this.

**Comment by droidmonkey** [comment]
Not going to implement this
