### ISSUE TITLE
SSH-Agent only works when KeePassXC is started from the terminal

### ISSUE THREAD

**Issue by Hofer-Julian** [keepassxreboot/keepassxc#3406]
## Expected Behavior
I start KeePassXC by searching it on my Fedora 30 workstation with GNOME on it.
I use the distribution package of Fedora.
After unlocking my database I expect that it adds the ssh-key to the database

## Current Behavior
It does not add it.
I also cannot add it manually with the dedicated button.
However it works perfectly when I run it by typing `keepassxc` in the terminal

## Debug Info
KeePassXC - Version 2.4.3
Revision: 5d6ef0c

Qt 5.12.4
Debugging mode is disabled.

Operating system: Fedora 30 (Workstation Edition)
CPU architecture: x86_64
Kernel: linux 5.1.18-300.fc30.x86_64

Enabled extensions:
- Auto-Type
- Browser-Integration
- SSH-Agent
- KeeShare (only unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.4

**Comment by droidmonkey** [comment]
Are you using a key loaded from a file or embedded in the database (ie an attachment)?

**Comment by Hofer-Julian** [comment]
Embedded in the database

**Comment by Hofer-Julian** [comment]
It also works when I start keepassxc by pressing Alt-F2 and then typing keepassxc

**Comment by droidmonkey** [comment]
On the surface by the way you describe the situation, it doesn't seem like this is a KeePassXC issue. Can you confirm that the process is started with the correct user and permissions when run from the search. Also make sure you don't have the snap, appimage, or flatpak accidentally installed or findable with the search feature.

**Comment by Hofer-Julian** [comment]
Even though I tested the "bug" for multiple scenarios and some restarts in between, I can't reproduce my problem any more. I will close the issue for now if that's okay for you.
Thank you for your time.

**Comment by droidmonkey** [comment]
Yup, I don't think it was an issue on our end

**Comment by Hofer-Julian** [comment]
Me neither :)

**Comment by Norrodar** [comment]
I have the exact same problem. I'm on Manjaro, installed keepassxc using pamac on a fresh system, nothing more. Keepassxc only adds the keys if I start it using the terminal: `keepassxc`.
If I start it by a link, search or from the start menu Keepassxc can't find any ssh-agent.
It always start with my username. I don't know how I can provide more information to you, I'm new to manjaro.
