### ISSUE TITLE
Losing Passwords Due To Read Only Database

### ISSUE THREAD

**Issue by 0o-o0** [keepassxreboot/keepassxc#3407]
## Expected Behavior
When using Keepassxc on my new OS installation with a copy of my database, I continued savings passwords using the "automatically save changes" setting.

## Current Behavior
Due to not thinking to manually change the owner and group on the database, it was opening as read-only. While I was adding new entries for services or machines, they were not being saved. I didn't realize the problem until I'd entered 5 or 6 new entries, and had to go back and recover all of the passwords.

## Possible Solution
Although the database was accurately labeled as "Read Only", it isn't a very eye-catching notification. I like "save automatically" because I don't have to think about checking to make sure my data is saved. Maybe if a database is opened as Read Only *and* the "Save Automatically" setting is set to true, provide some sort of splashy warning to make sure users understand their information is not being saved before they exit?

## Steps to Reproduce
1. Set "save changes automatically" to true.
2. Open a database as read only.
3. Make changes to the database.
4. Close the database.
5. When you reopen the database, changes are gone.

## Debug Info
KeePassXC - 2.4.3

Libraries:
- LIBS

Operating system: Ubuntu
CPU architecture: 86_64

Enabled extensions:
- None

**Comment by Gustry** [comment]
I just got the same problem too. It's is IMHO critical as I'm also using the autosave feature and I didn't get any warning saying that save failed because of read-only mode.

As @0o-o0 said, there should be a warning when save failed (especially when autosave is enabled).

I lost 2 days of password for me. Thanks for this work.

**Comment by droidmonkey** [comment]
This issue is addressed in the PR mentioned above your post
