### ISSUE TITLE
Aditional atribute list beetween entries

### ISSUE THREAD

**Issue by Wolvverine** [keepassxreboot/keepassxc#3413]
It would be useful to share a list of additional attributes for entries, between entries in the database, for example in the form of a selection list, so that you can select attributes already created for another entry.

**Comment by droidmonkey** [comment]
Please provide the use case for this

**Comment by Wolvverine** [comment]
The point is that the field names between entries containing the same should be with the same name, such as Pin (PiN, PIN) etc.

**Comment by droidmonkey** [comment]
That is tracked in another request.
