### ISSUE TITLE
Primary click of tray icon for OSX does not restore the KeePassXC window

### ISSUE THREAD

**Issue by TraceyC77** [keepassxreboot/keepassxc#3414]
Left clicking the KeePassXC icon in the system tray in OSX does not restore the window. It brings up the right click menu.

This is similar to #2130

## Steps to Reproduce
Minimize program to the system tray
Left click the icon in the tray

## Expected Behavior
The KeePassXC window is restored

## Current Behavior
See context menu instead of restoring program (the same as right clicking the icon)

## Context
The primary click behavior works properly on Windows 10 and KDE Neon Linux
On OSX other tray icons have different behavior for primary click and secondary click

## Debug Info

KeePassXC - Version 2.4.3
Revision: 5d6ef0c

Qt 5.12.3
Debugging mode is disabled.

Operating system: macOS Mojave (10.14)
CPU architecture: x86_64
Kernel: darwin 18.7.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
 libgcrypt 1.8.4

**Comment by droidmonkey** [comment]
This is not our bug, it belongs to Qt. This is default and uneditable behavior.

**Comment by TraceyC77** [comment]
OK, where can I report that upstream if this project doesn't report bugs upstream?

**Comment by droidmonkey** [comment]
https://bugreports.qt.io

**Comment by TraceyC77** [comment]
Thanks for confirming the correct place to report this. For the sake of people finding this issue in the future, I've filed this bug with the QT project:

https://bugreports.qt.io/browse/QTBUG-77254

**Comment by TraceyC77** [comment]
@droidmonkey  The QT folks response makes it seem like they don't think there is a bug in QT. Could I trouble you to reach out to them with more details about the QT bug to facilitate things? Thanks. :)
