### ISSUE TITLE
Add "Minimize after unlock" option

### ISSUE THREAD

**Issue by mi271** [keepassxreboot/keepassxc#3419]
Like the original Keepass application i would like to see a feature to unlock the database when i start my computer and KeepassXC starts automatically via Windows Autostart, even when i start the app minimized.

## Desired Behavior
I would like to have a checkbox where i can choose if i want to unlock the database on startup or not.

## Context
I come from the original Keepass app and there i got used to this behavior and i find it quite comfortable to unlock my database when i start my computer and the app window goes straight to the tray afterwards.
Im surprised that this is not possible here

**Comment by droidmonkey** [comment]
I'm pretty sure there is a "minimize on unlock" option. We also have two keyboard shortcuts:

Ctrl+M = minimize to taskbar
Ctrl+Shift+M = Minimize to tray icon (if enabled)

**Comment by mi271** [comment]
Maybe i`m too blind to see it, but i can`t find "minimize to unlock" in the settings...

**Comment by droidmonkey** [comment]
You are correct there is no option to "Minimize after unlock"

**Comment by artlov** [comment]
I voting for this feature too.

**Comment by irgendsontyp** [comment]
I am currently trying to implement this.

A question came up: Should the logic for minimizing after unlocking the database go into MainWindow.cpp or DatabaseWidget.cpp?

**Comment by droidmonkey** [comment]
MainWindow should listen for the databaseunlocked signal

**Comment by irgendsontyp** [comment]
Oh, seems like this has already been implemented: https://github.com/keepassxreboot/keepassxc/commit/0a3b19edf230264a28010f1783b37d43ae9608c3

The option "Minimize window after unlocking database" is under "Startup". In my opinion it would fit better under "General" as the option does not only work for application startup.

Also, the change was implemented in DatabaseWidget.cpp. Why not MainWindow.cpp? What is DatabaseWidget's purpose? Where is it used?

**Comment by droidmonkey** [comment]
Ehh it could go either way. I do prefer putting main window type actions within the main window class. Although I approved this PR. Need to close this issue.
