### ISSUE TITLE
Add an option to hide comment fields

### ISSUE THREAD

**Issue by tkisason** [keepassxreboot/keepassxc#342]
Hello,

It would be great to have an option to hide the comments field as a toolbar toggle option, ala keepassz 

Thank you!
Sincerely,
Tonimir

**Comment by phoerious** [comment]
I'm not quite sure what you mean. Do you mean the "Notes" field on the edit entry screen? If so, why would you want to hide it?

**Comment by tkisason** [comment]
Sorry, notes. that's what i ment. 
Simply because the notes can contain confidential information, and that could reduce the potential issues with shoulder surfing.  (Without going into a overly too specific issue)

**Comment by phoerious** [comment]
Why don't you use advanced attributes for that? We already have a patch on the way for 2.2.0 which allows you to hide advanced attributes. The notes field is more for general notes and not for private keys etc.

**Comment by droidmonkey** [comment]
Recommend using the attributes section for anything that needs to be "protected" from view. See #220

**Comment by tkisason** [comment]
I have a database that is more than 5 years old with a ton of entries, and there are a lot of comments below. :) That's the practical reason. Attributes are cool for new stuff, but unfortunately, there are legacy issues. :(

**Comment by Throne3d** [comment]
Added in #1124?
