### ISSUE TITLE
Verification Failed Mac OS High Sierra

### ISSUE THREAD

**Issue by joland** [keepassxreboot/keepassxc#3420]
I followed the instructions your page https://keepassxc.org/verifying-signatures/
Installed GPG Tools manually. Downloaded the dmg bundel, gpg signature, digest and the keepassxc_master_signing_key.asc manually. They are all on my desktop. 

When i right click keepassxc_master_signing_key.asc and go to: services -> OpenPGP: verify signature of file i get "Verification FAILED".

I downloaded the bundle twice (just in case) but keep getting the error message. 

In terminal i get this:

$ shasum -a 256 -c KeePassXC-2.4.3.dmg.DIGEST 
KeePassXC-2.4.3.dmg: OK

$ gpg --verify KeePassXC-2.4.3.dmg.sig
gpg: assuming signed data in 'KeePassXC-2.4.3.dmg'
gpg: Signature made Wed Jun 12 02:09:16 2019 CEST
gpg:                using RSA key C1E4CBA3AD78D3AFD894F9E0B7A66F03B59076A8
gpg: Good signature from "KeePassXC Release <release@keepassxc.org>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: BF5A 669F 2272 CF43 24C1  FDA8 CFB4 C216 6397 D0D2
     Subkey fingerprint: C1E4 CBA3 AD78 D3AF D894  F9E0 B7A6 6F03 B590 76A8

**Comment by droidmonkey** [comment]
No failure here:

> gpg: Good signature from "KeePassXC Release
