### ISSUE TITLE
Notes Window Formatting

### ISSUE THREAD

**Issue by rnc** [keepassxreboot/keepassxc#3421]
[TIP]:  # ( Provide a general summary of the feature in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Summary
[NOTE]: # ( Provide a brief overview of what the new feature is all about )

Font / formatting configuration in certain UI elements.

## Desired Behavior
[NOTE]: # ( Tell us how the new feature should work, be specific )

While I can see monospace fonts in e.g. the password entry box (so I can easily see the difference between `0 | O `, I would find it very useful to be able to configure whether to use monospace in Notes or not. Or alternatively always use monospace.

I have also noticed that while the password is entered in monospace, once the entry is saved and upon reveal it is not displayed in monospace. This seems inconsistent.

## Possible Solution
[NOTE]: # ( Not required, but suggest ideas on how to implement the addition or change )

Options : Toggle monospace versus 'normal' font in Notes.

Another idea, which might actually be better, is to allow markdown formatting. 

This would effectively give me the same ability and also allow some more useful formatting of titles, lists etc.
[ Edit : noticed that #1057 already suggested markdown ]

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )

The use-case is I want to record other information inside the encrypted DB and I don't want to confuse `O|0` and want the text to be formatted as I prefer.

**Comment by droidmonkey** [comment]
Already implemented by #3321
