### ISSUE TITLE
CSV delimiter choosing

### ISSUE THREAD

**Issue by Xpym482** [keepassxreboot/keepassxc#3423]
[TIP]:  # ( Provide a general summary of the feature in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Summary
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
It's great to have a choose, which delimiter must use exporting csv files. For example i am using non-english version of excel and with default delimiter - comma, text is placed in one cell, to fix it excel needs to use semicolon.

## Desired Behavior
[NOTE]: # ( Tell us how the new feature should work, be specific )
In general settings needs to have option to write own delimiter for csv files.

**Comment by droidmonkey** [comment]
You can choose the delimiter on import into Excel.

**Comment by droidmonkey** [comment]
![image](https://user-images.githubusercontent.com/2809491/62423131-3eb0e300-b68b-11e9-9853-db1935b9b4e2.png)
