### ISSUE TITLE
Can't hide password

### ISSUE THREAD

**Issue by DOF90** [keepassxreboot/keepassxc#3424]
When i open my database, I can see in clear all my registered password and not the usual dots...
Can you help me please?

I'm on Ubuntu 16.04 and using Keepassxc 2.4.3

**Comment by droidmonkey** [comment]
Press Ctrl+Shift+C

**Comment by khazhyk** [comment]
This is a pretty bad default hot-key binding, considering "cntl-shift-c" is "copy username" on the default keepass. You'll trigger this without noticing if you move from that software
