### ISSUE TITLE
2.4.3 on macos 10.14.6, "unable to open attachment"

### ISSUE THREAD

**Issue by tomjennings** [keepassxreboot/keepassxc#3429]
i am unable to open a file attached to a record. the database is old, the record from 2005, so i exported the DB as a .CSV file. a quick search of the .CSV file with vi revealed no reference to the attached file's name. luckily i have a working copy of the file in the filesystem (id_rsa key).

all other features seems to work just fine.

quit keepassxc, downloaded 2.4.3 DMG file, reinstalled, imported the .CSV file to re-create the database. went to the record in question; no attachments listed. opened record ("edit entry") clicked advanced, "ADD" a file (id_rsa text file). successfully added. added filename appears in the "attachments" box, under "name".

double-clicking the filename puts up the red bar with "unable to open attachment: Can't open file: foobar".

same results after all of the following: click OK to end edit; command-S save DB; quit program/restart/etc. 

*** rebooted computer, opened keepassxc, opened DB, entry, etc. same error as before.

*** added second file. OK, now i am able to open the second file (also text, 734B) but "unable to open attachment" on the first (3.17 KiB).

*** created new, empty database. added one entry ("foo"). created simple test text file ("text.txt"). added that file to that entry; opens successfully, as does a second test file.

doesn't seem to like my current database. though it's old, it's only 24KB long; only one record had two text file attachments, and i keep the DB pruned tightly. 

i had pruned the columns down too, the first line of the .CSV file (headers) is:
"Group","Title","Username","Password","URL","Notes"

*** on Keepass2Android, opening the original ("old", above) database, the same record entry, shows the attachments, but attempts to open them with the internal viewers gives a blank screen, as if the files were empty.

computer is a box-stock 27" Mac, Mojave 10.14.6, up to date.

so i'm fairly stumped.

**Comment by droidmonkey** [comment]
We use the desktop association for the file extension (Qt does this actually) to properly open files. This probably cannot be done with an id_rsa file. Just save the attachment to disk and open it from there.

**Comment by tomjennings** [comment]
OMFG so bluntly obvious. my apologies. i often overlook the rigidity of Mac associations (old habits die hard).
