### ISSUE TITLE
Add support for high ANSI characters in the password generator

### ISSUE THREAD

**Issue by ixnari** [keepassxreboot/keepassxc#343]
This is something I miss from when I used to use KeePass on my windows partition. The current character set is great, but the addition of high ANSI characters would increase the strength of a password and would make KeePassXC even more awesome.

**Comment by TheZ3ro** [comment]
I like this. I will work on this after the #373 PR.

**Comment by ixnari** [comment]
Awesome, thank you! Looking forward to v2.2.0!
