### ISSUE TITLE
Database locks on screen energy saver turn off in macOS

### ISSUE THREAD

**Issue by steveedmonds** [keepassxreboot/keepassxc#3432]
With the setting "Lock databases when session is locked or lid is closed" checked the database locks with the screen energy saver activation rather than on session locking.

## Expected Behavior
Database should lock on session locking

## Current Behavior
With mac settings;
>Energy Saver>Turn display off after + 2 mins
>screen saver start after 20 mins.
>security and privacy> require password 15 mins after screen saver or sleep.

Database locks on display turn off.

## Steps to Reproduce
1. Mac settings as above
2. Open database
3. Wait for screen to turn off

## Context
Nothing unique

## Debug Info
KeePassXC - Version 2.4.3
Revision: 5d6ef0c

Qt 5.12.3
Debugging mode is disabled.

Operating system: macOS Mojave (10.14)
CPU architecture: x86_64
Kernel: darwin 18.7.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
 libgcrypt 1.8.4

**Comment by otaithleigh** [comment]
Encountering the same bug on Ubuntu 18.04.

### Debug info:
KeePassXC - Version 2.5.3
Revision: f8c962b

Qt 5.9.5
Debugging mode is disabled.

Operating system: Ubuntu 18.04.3 LTS
CPU architecture: x86_64
Kernel: linux 4.15.0-74-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.1
