### ISSUE TITLE
Add "execute without question" option.

### ISSUE THREAD

**Issue by Phaturia** [keepassxreboot/keepassxc#3433]
[TIP]:  # ( Provide a general summary of the feature in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Summary
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
It would be nice if I could enable/disable auto `_EXEC_CMD: 1` in the options.
If I Enable this option then all the commands would run without question.
(Currently I moving from Keepass2 and now I have to modify hundreds of entries)

An other solution for this if the .csv export/import includes the Attributes for the entries. In that way I could change it for all of my entries at once.

**Comment by droidmonkey** [comment]
We have a checkbox that disables asking. just use that.

**Comment by droidmonkey** [comment]
The only development we would do is have a global option to not ask to execute.

**Comment by Phaturia** [comment]
Yes, I meant a global option to never-ever ask, even for the first time.

**Comment by droidmonkey** [comment]
We will not be implementing this
