### ISSUE TITLE
Linked database file become a regular file

### ISSUE THREAD

**Issue by SzzSHUN** [keepassxreboot/keepassxc#3435]
I make a link to an database file. If I open the database through the linked file, then modify and save the database, the link is gone and a regular file saved over the link.

## Expected Behavior
The link to the original file is remaining as a link.

## Current Behavior
[NOTE]: # ( Tell us what actually happens )
The link to the original file saved as a regular file (copy of the original one).

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1. Create a link to the original file.
![createlink4file](https://user-images.githubusercontent.com/53933081/62763541-19a5e100-ba8c-11e9-8b99-fd2eb5144dc5.png)

2. Open the database through this link. Edit something and save the database.
3. The link file is gone, and the copy of the original file is created at the link path.
![aftereditlink4file](https://user-images.githubusercontent.com/53933081/62763626-55d94180-ba8c-11e9-85c6-7e7fd836bb31.png)

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )
The original KeePass 2.42.1 program don't do that.

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.4.3

Operating system: Manjaro Linux
CPU architecture: 64bit
Kernel: 4.19.62-1-MANJARO
![neofetch](https://user-images.githubusercontent.com/53933081/62763706-802aff00-ba8c-11e9-8721-aeba3ad236e7.png)

Enabled extensions:
- None

I do not speak English well. Sorry about that.

**Comment by droidmonkey** [comment]
Do you have safe file saves disabled?

**Comment by SzzSHUN** [comment]
Yes, i have.
![safefilesave](https://user-images.githubusercontent.com/53933081/62774508-2be04900-baa5-11e9-98d4-4f0f4513a2af.png)

**Comment by droidmonkey** [comment]
Yup we should be resolving the canonical file path. Good catch!

**Comment by SzzSHUN** [comment]
Nice to help you improve!
