### ISSUE TITLE
Website download page: "Installed" should be "Installer"

### ISSUE THREAD

**Issue by deisner** [keepassxreboot/keepassxc#3442]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
I expect the heading for the installers to be "Installer".

## Current Behavior
[NOTE]: # ( Tell us what actually happens )
The heading for the installers is "Installed":

![image](https://user-images.githubusercontent.com/742277/62946715-39504880-bdaf-11e9-9411-acd12a7d8f13.png)

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )
s/Installed/Installer/

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1. Visit https://keepassxc.org/download/

**Comment by droidmonkey** [comment]
It is correct, these are the "Installed" versions of KeePassXC
