### ISSUE TITLE
Autotype keeps typing "q" instead of "@"

### ISSUE THREAD

**Issue by therealmaxmoon** [keepassxreboot/keepassxc#3445]
I've changed from keepassx to keepassxc and the first thing I realized is, that some autotypes don't work. I figured out if the login information contains an e-mail instead of a username, it doesn't work anymore. After seeing that my e-mail address has a "q" instead of an "@", I just was confused.

I am on a freshly installed FreeBSD 12 system and use a German keyboard. The @-sign can be print if you press AltGr+q on a German keyboard.

Thank you for your help.

**Comment by droidmonkey** [comment]
Duplicate issue.
