### ISSUE TITLE
Text is same color as background of text input field

### ISSUE THREAD

**Issue by NginUS** [keepassxreboot/keepassxc#3446]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Expected Behavior
Being that the text input field was white, I expected the typed text to be dark so as to be legible

## Current Behavior
The typed text is the same color at the background of the text input field, & as such is only visible when it's selected.

## Possible Solution
I'd like to know where in my DE theme/whatever I need to adjust where the colors it's using are defined so I can fix it.

## Steps to Reproduce
1. Install app
2. Click to create new database
3. Type the entries in the text input fields provided

## Context
I'm using a dark theme, but have never seen anywhere that text fields were affected. Other text fields have light backgrounds but their text is always black until now.

## Debug Info
KeePassXC - Version 2.4.3
Revision: 5d6ef0c
Distribution: AppImage

Qt 5.10.1
Debugging mode is disabled.

Operating system: Linux Mint 18.3
CPU architecture: x86_64
Kernel: linux 4.15.0-58-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (only unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.1

Operating system: Linux Mint 18.3 (Ubuntu 16.04 LTS)
CPU architecture: x86_64
Kernel: Linux rc 4.15.0-58-generic #64 16.04.1-Ubuntu
DE: KDE Plasma Workspace 4:5.8.9-0ubuntu1~ubuntu16.04 ppa1
DE Theme: Breeze Dark / Oxygen

Screenshot attached
![2019-08-15_Theme_Text_Invisible](https://user-images.githubusercontent.com/8769067/63123593-59326880-bf77-11e9-95ce-9ae74694db26.png)

**Comment by NginUS** [comment]
Changing the "Application Color Scheme" to "Obsidian Coast" is still dark enough for my taste, & has a slightly darker text input field background, so the white text is barely visible enough that it's functional.

I'm leaving this issue open since I'd much prefer the app utilize whatever text foreground values the rest of the system is using so that it'd no longer be white on white while using the "Breeze Dark" color scheme. Especially since "Breeze" is the default & simply switching to the 'Dark' 'Breeze' variant shouldn't be problematic like this.

**Comment by droidmonkey** [comment]
We do use the default foreground text. This is an issue in the theme and how it is applied to Qt apps. You should probably use Qt5ct to control this. This is not a bug in KeePassXC.
