### ISSUE TITLE
Introduction of copied field for quick access to most used passwords

### ISSUE THREAD

**Issue by jeroenbreedveld** [keepassxreboot/keepassxc#3448]
Hi,

The introduction of (last) copied field for every entry would allow for the database to be sorted on this copied field. This way for most of the passwords I use I could immediately copy desired password from the list at the top of the screen saving me to search for a password *every* time I use keepassxc.

Thanks!

**Comment by droidmonkey** [comment]
Are you referring to a "last accessed" attribute / recently used?

**Comment by jeroenbreedveld** [comment]
No, I expected this but "last accessed" does not seem to be updated when a password is copied. 

At least not on macos...

**Comment by droidmonkey** [comment]
There is a good reason for that, it would require saving (or marking your db dirty) every time you interact with anything. That is not acceptable given the encryption delays we have for security. This won't be implemented.

**Comment by jeroenbreedveld** [comment]
Ok, I can appreciate that because I use a Yubikey so that would mean I would have to touch that twice.

Thinking about this I solved it by moving all passwords to a folder "Rarely used" and keeping often used passwords in the root.

**Comment by droidmonkey** [comment]
Sweet, good idea. You can also add text to the title like "important" and search using: `title:important`
