### ISSUE TITLE
Inherit Username/password from parent group instead of referencing them one by one

### ISSUE THREAD

**Issue by dieterlohrstraeter** [keepassxreboot/keepassxc#3449]
## Summary
I think it would be better to inherit username/passwords from parent groups instead of creating manually a reference to another entry?

I often have the situation, that multiple accounts on different URL's have the same username/password and it would be extremely easy to organize all accounts within same Groups and just add a username/password on the group.

Technically, this is very similar to the already implemented references, but it would be more intuitive usability.
In case, a password needs to be changed on one URL, it shall be changing the groups password, where it was inherited from.

## Desired Behavior
Add entries as usual and put them into any group.
Edit <Group> and add Username/passwords to it.
In case any password is already defined within entries of this group, provide them as list to choose.
Put them as additional entry in same way as the Auto-Type inherits the sequences from parent group and optionally remove it from entries in the group.

When searching or using Auto-Type, the entry is searched in same way as usual. But in case there 
is no username, inherit value from parent-group. Same with password and maybe other values.

## Context
Reason is more or less similar to the idea for references. But difference is the way of organization within KeePass database structure.
As long as all URL within same group are share the same account in background, it would be very easy to change the password on just one location. All others would automatically be adjusted.
In my opinion, this is much more intuitive than the referencing-idea, which needs more effort and has much less overview.

Another idea would be to use the reference as is and just create an additional "view" on all referenced objects in groups.

**Comment by droidmonkey** [comment]
There are a few things that prevent this from being implemented. One is, we do not condone in any way using the same password on multiple accounts. The other is this does not conform to how Groups and Entries work in the kdbx framework (ie it is not portable to other keepass programs).

I think you are trying to use the program in an awkward way and suggest you describe better what your use case is and we can help you

**Comment by dieterlohrstraeter** [comment]
I understand that my request is not easy to understand nor is it easy to implement, but I have some ideas (see at bottom).
Previously I managed accounts within Firefox, but this was too proprietary and since I need also sharing them with other Browsers like Chrome, I started using KeePassXC.

I'm working in an enterprise environment as 3rd-Lvl-Support for productive and Testsystems of a bigger platform with many GUI's and need to manage a real huge amount of shared and different accounts. Some of the accounts are stored and shared/replicated in background (based on same PW-database), similar to AD, but most of the URL's are totally different and you cannot see easily, that they are related.
Moreover, on each of the systems with same password-DB I need to use multiple different accounts for different purposes. This means, for a platform with 5 different URLs (GUI 1.1, GUI 1.2, GUI 1.3, GUI 1.4) , I have to use about 4 or more different shared accounts for different clients. Similar is for another big module of the platform with 3 URLs (Service 2.1, Service 2.2, Service 2.3) saved in another password-database (I mean the pw-db of the platforms, not KeePass.kdbx).
Some of the services don't have ability to change the password. This must usually be done with just one of the services.
What it makes more complex is, that I need the same schema for different environments like (Production, Reference, Test[1-6]). This means, I need 4 shared accounts on Service-1-DB and another 3 shared accounts on Service-2-DB = 7 accounts per environment, times 4 clients times 8 environments = 7x4x8=224 theoretical accounts just for one global platform.
This was not my design and since some of them are client-independend, I'm using maybe about 40-50 out of them for my normal work.
In addition, we have also some totally independent enterprise services, sharing the same account.

Coming back to the implemented reference feature:
I hope you can imagine, that using references by just cloning each of them is very anoying and error-prone in my situation. Moreover, I'm loosing the overview, because they are not grouped visibly.
As long as I don't use such like References, if I've changed one of them, I need currently to change also all the others in KeePass. If I come back to them much later, I need to read first the current PW from correct entry and reset it for the other entries as well.
Additionally, I need to do many manual tasks for each new entry, e.g. changing the URL, testing etc.

My idea for implementation with using the same internal KeePass.kdbx is as follows:
All grouping/referencing shall be done within KeePassXC client! If another client imports, it shall use them with this grouping, but they don't need to consider the special relationship.

1. defining a new Account-Group (adding special attribute?), that shall later group all shared accounts. This group has no real difference to standard groups, except the attribute (if possible) -> no change on .kdbx

2. Adding first account to this marked group. This is then the reference-account for this group.

3. Open a new URL without matching entry in KPXC using Browser-addons.
 In this case, enable searching for already stored accounts in KPXC. This seems currently not directly being supported in right-menu.

4. When choosing another entry from the list, offering either clone and/or the reference to it.
If the selected entry is member of an Account-Group, then
 * use selected entry as reference
 * put the new entry into this group
 * such groups should be able to be defined even on deeper levels of sub-groups.

If it would be possible to save accounts and passwords on Group-Level, it would even be more elegant, but I assume, this would not fit to KeePass design for other clients.

On import of .kdbx, the contents could be reorganized, so that all accounts referencing the same master-account shall be put into the same Account-Group.

I don't know the internal db-structures. Thus, I'm not sure, if this idea has a chance.
However, it would really bring a big benefit to me and all others in similar situations.

**Comment by droidmonkey** [comment]
I am confused as to why you need so many duplicate entries to handle this workload. Wouldn't one entry suffice? Are you using Auto-Type to inject credentials into the platform you are using? You can define multiple matching criteria in the Auto-Type setup that works across the windows you are using.

**Comment by dieterlohrstraeter** [comment]
Hard to explain all the details, but first answer: If using the Browser-Extension KeePassXC-Browser for Firefox and Chrome can also be called Auto-Type, then yes. I need automatic identification of matching entries. It's the only way to keep efficient.
I've made some more minds about the situation and due to my workload come back to you later...

**Comment by droidmonkey** [comment]
Browser extension and Auto-Type are completely different features

**Comment by dieterlohrstraeter** [comment]
Okay, but at the end, both features need to identify the correct entries. Of course, both have more or less different approaches to find them, but currently they cannot eliminate duplicates easily.
At the moment I see only the option of referencing to other entries, which must be made manually for every account separately.
I have some ideas, which could be implemented in a very compatible way, that saves the keepass.kdbx file so, that it can be loaded by other tools.
All depends on one question:
Is it technically possible to save some Key/value pairs on Group-level, which might be ignored by other tools? I haven't seen it so far.
If yes, I would explain my idea in more details.
If not, then the only way of avoiding duplicates is using references, but it requires manual work once per each shared account and each URL.

**Comment by dieterlohrstraeter** [comment]
Thanks, this would allow a backward compatible implementation, that allows even other Keepass users to load and use the KP-DB.

I'm using following terms:
 - KPXC = KeePassXC
 - KP = Keepass (and any other derivates)
 - pw-db = Server based PW database, e.g. LDAP or any other.
 - KP-db = KeePass database


**The problem:**
Accounts are created and saved on any kind of server pw-db. Multiple applications with partially totally different URL's can use the same pw-db.
On complex environments, users sometimes have multiple different accounts for specific purposes.
So, you might have multiple levels of accounts:
 - 1.Level: One account per pw-db
 - 2.Level: Multiple accounts per pw-db

Combine this with multiple applications with different URL's using the same pw-db:
 - app=1..n for n applications
which makes it more complex.

Example:
Peter is a customer admin and needs accounts for 3 different independent clients within the same application. So each account is bound exclusively to a specific client, because application requires to have strict independencies between clients. Moreover, for each client it uses different URL's.
Additionally, the application has multiple admin GUI's for specific modules/areas of the application.
But all of these accounts are stored within the very same pw-db.
However, since all are connected to the same pw-db, accounts are unique globally. No chance to define two accounts with same name for different clients.

So Peter has to use following abstract accounts at abstract URL's:
 - Peter.cust1.clientA at Client1.com
 - Peter.cust1.clientA at Management.com (Account mgmt)
 - Peter.adm1.clientA at Management.com (Account mgmt)
 - Peter.adm1.clientA at Client1.com
 - Peter.adm1.clientA at module1.internal.com (for internal module1 GUI)
 - Peter.adm1.clientA at module2.internal.com (for internal module2 GUI)

 - Peter.cust2.clientB at Client1.com
 - Peter.cust2.clientB at Management.com (Account mgmt)
 - Peter.adm2.clientB at Management.com (Account mgmt)
 - Peter.adm2.clientB at Client1.com
 - Peter.adm2.clientB at module1.internal.com (for internal module1 GUI)
 - Peter.adm2.clientB at module2.internal.com (for internal module2 GUI)

- same with clientC ...

As user, the browser just sees the different URL's and also different window descriptions. It has only limited chances to identify relations between different accounts.
Currently only the option to use references in KP would allow to use and update the same accounts, but this is a big effort each time a new client is added.

**Solution proposal:**
Idea for implementation with using the same internal KeePass.kdbx is as follows:

All grouping/referencing shall be done within KeePassXC client! If another client imports, it shall use them with this grouping, but they don't need to consider the special relationship.

1. defining a new group **as Account-Group** (adding special attribute), that shall later group all shared accounts. This group has no real difference to standard groups, except the attribute -> no change on .kdbx
All accounts within this Account-Group will be unique

2.  Create new entry as usual with username/pw URL etc.
     E.g. Peter.cust1.clientA at Client1.com

3. Then move it into this Account-Group! No further changes to standard behavior.

4. When searching for accounts on different URL (e.g. Peter.cust1.clientA at module1.internal.com), there is no matching entry found with standard search methods, but KPXC shall offer additionally to search within Account-Groups. If user chooses this option, he shall select one of the offered Account-Groups. Then KPXC shall offer any accounts within this Account-Group, no matter that URL doesn't match. If users chooses it and later is asked to save, KPXC adds a new entry with this URL within this Account-Group automatically. No need to reference it, but password of every account within this group having the same account-name must be updated with the new password.

5. Opening same page of module1.internal.com again, will then automatically detect, that URL is part of Account-Group and automatically search and offer for every account-name within this group, no matter, if URL matches with other entries. If no entry exists, user is asked to create new as usual and again all passwords with same accountname will be updated.

Basically the idea is: In case KPXC searches a matching entry within it's kp-db, then it does it in following order:
1. search by standard method as usual (will also find accounts as created by Account-Group below)
2. if no entry is found:
 2.1 if any Account-Group is defined:
    Offer searching within Account-Groups instead.
    If Account-Group is selected: Offer all existing Accounts within this Group for selection, even if URL doesn't match
3. If login works, then offer "new"/"update" as usual, but in this case, put it automatically into this Account-Group instead of Default "KeePassXC-Browser Passwords" group. This automatically enriches the Account-Group with new URL's for other purposes.

4. If new account for existing URL within Account-Group is created, then other URL's within this Account-Group allow easily to use this account for those URL's as well.

**KP Compatibility**
There are no standard references used. This increases effort for search and update a little bit, but shouldn't be a performance problem. Advantage is, that even one entry is dropped, we don't need to ensure a complex consistency check.
If another KP client loads the db, it doesn't consider the Account-Group flag, but should be able to use all existing entries as usual.
If KPXC loads kp-db again that has been modified by another client, it should also work, but maybe not all passwords of same account were updated and are in sync. This is cleared by KPXC at next PW-update automatically.

I see, it is a big description and of course, I have not described every detail, but it should give you an idea about my vision. But this way, keeping accounts in sync will get much more easy to users, because if relations are defined once correctly in Account-Groups, every account with same name can easily kept up2date and no need to define each account completely new.

I hope, this description was clear enough to understand. Maybe you have a complete different opinion, but for me it would help to keep all my accounts under control.

**Comment by droidmonkey** [comment]
This will not be implemented
