### ISSUE TITLE
HyperSECU HyperFIDO support

### ISSUE THREAD

**Issue by danescobar** [keepassxreboot/keepassxc#3450]
This Canadian company has developed a similar solution to Yubikey with similar capabilities [https://www.hypersecu.com/products/hyperfido](url)

## Summary
Shouldn't be very hard to provide support for this alternative to Yubikey. More so knowing HyperSECU's solution is 9 times less the price of a Yubikey.

I bought an HyperFIDO thinking that your mention of Yubikey was meant to illustrate this type of device and any similar OTP hardware authentication device would be compatible with KeepassXC.

**Comment by droidmonkey** [comment]
I don't see anywhere on their site that the key supports HMAC challenge response. Either way, we are not going to add support for any keys that cannot be accessed through the Yubikey API. OnlyKey was added in 2.5.0 because it supports the Yubikey API and can be queried with no code changes on our end.

**Comment by danescobar** [comment]
@droidmonkey thanks for your answer. When I setup my HyperFIDO with linux, it used the same config files that Yubikey uses so that made me believe they would be compatible.

**Guide:** [https://www.hypersecu.com/downloads/files/userguides/HSTE-NB0033.7-RV1.0-FIDO_Linux_Setup.pdf](url)

I agree that adding support for other types of 2FA would be some work but there's a discussion thread in keepass.info that illustrates the security flaws of Yubikey and HMAC based hardware autheticators.

Yubikey price is $45, is based on HMAC that uses shared secrets (a security flaw), in addition Yubico switched to non-open source.

HyperSECU and other solutions that use U2F have no shared secret adding much more security to the 2FA process, they remain open source and for $5 a piece you can have many affordable backups.

I can understand if you have some kind of agreement with Yubico to only support their hardware but if not, implementing U2F would be work well invested imho. Perhaps there could be some collaborator who would be willing to code a plugin to support it?

Original thread: [https://sourceforge.net/p/keepass/discussion/329220/thread/6d018442/#26c5](url)

**Comment by droidmonkey** [comment]
Please read and understand this response to that same thread: https://sourceforge.net/p/keepass/discussion/329220/thread/6d018442/#7296
