### ISSUE TITLE
Mousewheel scroll through Settings selects & changes drop-down menu causing unwanted changes

### ISSUE THREAD

**Issue by NginUS** [keepassxreboot/keepassxc#3451]
## Expected Behavior
Using the mouse wheel to scroll to the unseen portion of the Settings screen changes view without affecting settings.

## Current Behavior
Using the mouse wheel to scroll to the unseen portion of the Settings screen changes the "General" > "Button style" drop-down menu to its lowest selection "Follow style" whenever scrolling to the lower unseen portion of the Settings screen by means of the mouse wheel. EDIT: Apparently this occurs when the drop-down menu is hovered over inadvertently.

## Possible Solution
Reduce width of drop-down menu so that mouse doesn't hover over it when positioned toward the right side of the screen

## Steps to Reproduce
1. Open application
2. Open Settings screen
3. Resize application such that Settings screen contains a page fold requiring to scroll down to view
4. Continue scrolling down using mouse wheel after the Settings screen is at its lowest position
5. Hover mouse pointer over far right side of drop-down menu.
5. Observe the "Button style" drop-down menu changing to its lowest position selection as if it was desired.

## Context
Is simply irritating to have to remember to always use the scrollbar instead of the mouse wheel, & interrupts normal workflow habits. Costs a few seconds each time I use the Settings screen to reset the drop-down menu to its desired selection upon noticing it's been inadvertently changed.

## Debug Info
KeePassXC - Version 2.4.3
Revision: 5d6ef0c
Distribution: AppImage

Qt 5.10.1
Debugging mode is disabled.

Operating system: Linux Mint 18.3
CPU architecture: x86_64
Kernel: linux 4.15.0-58-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (only unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.1

Operating system: Linux Mint 18.3 (Ubuntu 16.04 LTS)
CPU architecture: x86_64
Kernel: Linux rc 4.15.0-58-generic keepassxreboot/keepassxc#64 16.04.1-Ubuntu

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (only unsigned sharing)
- YubiKey

**Comment by NginUS** [comment]
Apologies for my error- I don't see how to change it from "bug" to an appropriate tag after-the-fact.

**Comment by droidmonkey** [comment]
This is functionality inherent to Qt. In 2.5.0 we shrunk the size of the settings boxes so they are not as easy to accidentally change.

**Comment by droidmonkey** [comment]
Looks like this can be prevented altogether but you need to override Qt behavior: https://stackoverflow.com/a/37460760

I'll add this to the accessibility PR since I find the wheel behavior annoying as well.
