### ISSUE TITLE
different auto-type selected entry

### ISSUE THREAD

**Issue by natask** [keepassxreboot/keepassxc#3453]
[TIP]:  # ( Provide a general summary of the feature in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Summary
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
Alongside a __"pick a target field in a target window, pick a desired entry from database and then auto-type"__ pattern currently present through ctrl+shift+v keybinding; support a __"pick a desired entry from database, pick a target field in target window, then auto type"__ pattern for a more general auto-typing experience.

## Desired Behavior
[NOTE]: # ( Tell us how the new feature should work, be specific )
On [keepass2](https://keepass.info/help/base/cmdline.html) it is possible to auto type into a field through a shortcut when keepass2 is in the background.  The setup follows a select desired entry then pick target field design pattern.
It sets up a work flow I am used to: 
   * search for entry to autotype
   * select that specific entry
   * change to target window and focus target field
   * press shortcut to auto type

keepassxc's entry autotype (ctrl+shift+v in the latest version) has a pick target field first then select desired entry design pattern. This has a drawback that if the window goes out of focus when keepassxc attempts to switch back to the target window, it auto types in the wrong window.  And since I have enabled mouse changes focus for Gnome environment, moving the mouse when selecting desired entry sometimes lands the mouse on another window while keepassxc swaps to the target window, unless the target window is full screen. 

## Possible Solution
[NOTE]: # ( Not required, but suggest ideas on how to implement the addition or change )
A possible solution would be to offer a command line flag that prints the custom sequence of the last selected entry, if its database is unlocked, when called. something like ```keepassxc --last-selected-entry```. Then users can call it while focusing the target field of the target window through autohotkey on windows or a Window environment's usual shortcut customization tool on Linux.  

This is how keepass2 implements this feature, at least for linux. 

Keeping track of the UUID of the last selected as meta-data, then constructing its custom sequence and then using OS specific methods to write that to currently focused window, which I believe is already implemented, should be sufficient.

According to my understanding, beyond tracking another state variable for each open database (granularity of implementation either on the database level, window level or process level), and implementing another cli flag, new  logic shouldn't be needed.

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
I have gotten so used to this workflow on keepass2 that this and custom attributes within the context of templates (issue #863) that I can't move away from mono keepass2. 
The approach should also be useful for implementing  #2093, without needing to implement an internal hot-key.

__not related:__ it would be nice to know where key bindings are set within the code (place the information somewhere in KEYBINDS.md possibly) so that if a person doesn't like the key bindings, they can easily edit the code and compile. That is until editing these key-bindings is possible from the GUI.

**Comment by droidmonkey** [comment]
This is entirely possible in KeePassXC. Check out the Auto-Type settings tab in the application settings to set your gonna keyboard shortcut.

**Comment by natask** [comment]
@droidmonkey this is a different feature from Global Auto-type. Global auto-type depends on the entry's title or url attribute to match the window. Therefore if you have yet to modify an entries title or url to match the target window, it doesn't work.  The feature I am suggesting allows you to auto type the latest selected entry directly in different means than that of the currently existing architecture to auto type the currently selected entry. I agree that it auto types the latest selected entry in a manner similar to Global Auto-type where you press the hot-key within the target window and not within keepassxc like the current implementation of auto typing a selected entry.

This feature also allows for auto typing an entry to multiple windows and auto typing multiple entries to a window.

Auto typing an entry to multiple windows isn't truly supported yet by keepassxc global auto type(I guess you can still auto type to two windows by matching title and url attributes to two different windows or to any arbitrary amount of windows by having duplicate entries) until [multiple urls](#1769) is implemented the upcoming 2.5 version.

Keepassxc Global auto type currently supports auto typing multiple entries to a window but selecting from the global auto-type popup window isn't scalable when you have multiple entries to type into a window because unlike the keepassxc window, it doesn't support search to quickly find the entry you want to auto type.

**Comment by droidmonkey** [comment]
Two pending features cover this request already: search from the Auto-Type window and selecting any entry from a database when Auto-Type doesn't match.

**Comment by natask** [comment]
I see. that is even better. seems like version 2.5 meets all my requirements. can't wait to try it out.

**Comment by droidmonkey** [comment]
"soon"
