### ISSUE TITLE
custom keybindings

### ISSUE THREAD

**Issue by natask** [keepassxreboot/keepassxc#3455]
[TIP]:  # ( Provide a general summary of the feature in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Summary
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
Implement a settings page to customize key-bindings. This should function much like the one implemented for the global auto-type key-binding.

## Desired Behavior
[NOTE]: # ( Tell us how the new feature should work, be specific )
Be able to customize all key-bindings from the user's side.

## Possible workaround 
Linking the code base locations for these key-bindings in [keybindings.md](https://github.com/keepassxreboot/keepassxc/blob/develop/docs/KEYBINDS.md) in the mean time seems to be a good starting point. People can then either implement this feature or can fork and compile a version meeting their key binding preferences.

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
Customization is king.

**Comment by droidmonkey** [comment]
Duplicate issue
