### ISSUE TITLE
save as for attachment files

### ISSUE THREAD

**Issue by Leon0824** [keepassxreboot/keepassxc#3456]
## Save as for attachment files
[NOTE]: # ( Provide a brief overview of what the new feature is all about )

Currently, we can only double click an attachment file to open it by OS default application.
I suggested to have a context menu item to save as attachment files.

## Desired Behavior
[NOTE]: # ( Tell us how the new feature should work, be specific )

Right click an attached file and there is an context menu item of Save As...

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )

For a .key extension file could be a Keynote file or a security key file. In the case macOS would open the file with Keynote and failed to open it.

**Comment by droidmonkey** [comment]
There is a button titled "Save" that does exactly this on the attachments view

**Comment by reneederer** [comment]
Is it possible to do this from the command line?

**Comment by droidmonkey** [comment]
Bo
