### ISSUE TITLE
Database changes by itself even when I don't change entries

### ISSUE THREAD

**Issue by masi** [keepassxreboot/keepassxc#3458]
## Expected Behavior
Database doesn't change automatically without user interaction.

## Current Behavior
Database doesn't all the time but I don't have a clue what has changed.

## Context
In conjunction with Firefox-plugin.

**Comment by droidmonkey** [comment]
What is changing? What do you observe? Are you using ssh agent or keeshare features? Need way more information

**Comment by masi** [comment]
I tried to figure out what triggers the changes. I'm using the SSH agent feature but not keeshare. As I wrote I use Firefox with the KeepassXC plugin.

I found out that within the database a signature for each client (Firefox, Chrome, etc) is stored. And after opening the database with Keepass (the original software) I also noticed that any permission for an entry to be used on a particular website is stored within the database (and not the browser as I have assumed).

I will have a further look at this. If this is the cause then it's ok though a bit annoying for me as I have the databases on a USB stick which I tend to remove after opening my databases.

**Comment by droidmonkey** [comment]
Yes we have to store site association permissions in the database. This is all by design and there is no issue here. I absolutely strongly recommend that you DO NOT store your database on a usb stick. That is a recipe for losing all of your data.
