### ISSUE TITLE
{DELAY xx} doesn't work in Autotype

### ISSUE THREAD

**Issue by Alt68er** [keepassxreboot/keepassxc#3459]
Under Win 10 pro x64, Firefox x64 v68.0.2, KeePassXC 2.4.3, KeePassXC Browser 1.4.7:

## Expected Behavior
[NOTE]: # KeePassXC should automatically fill the user and password fields and submit an ENTER-keystroke to the Website.

## Current Behavior
[NOTE]: # On some pages this does not work properly (e.g. https://www.cyberport.de/, https://geizhals.de/) and so I started to test it with a modified Autotype-sequence by inserting at different positions {DELAY xx} (where xx is the number milliseconds the dealy should last). But irrespective of the number of xx (from 50 to 10000) I cannot see ANY delay in autotyping.

## Possible Solution
[NOTE]: # If this is a bug in KeePassXC the parsing of the Autotype-sequence should be corrected; if it is a bug in Firefox a workaround should be established by KeepassXC and/or Firefox should amend its code ...

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1.
2.
3.

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )

## Debug Info
[NOTE]: # KeePassXC - Version 2.4.3
Revision: 5d6ef0c

Qt 5.12.3
Debugging mode is disabled.

Operating system: Windows 10 (10.0)
CPU architecture: x86_64
Kernel: winnt 10.0.18362

Enabled extensions:
- Auto-Type
- Browser-Integration
- SSH-Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.4

Libraries:
- LIBS

Operating system: OS
CPU architecture: ARCH
Kernel: KERNEL

Enabled extensions:
- EXTENSIONS

**Comment by droidmonkey** [comment]
Firefox does strange things with auto-type. Why not use our browser extension?

**Comment by droidmonkey** [comment]
I cannot replicate this at all using Firefox 68.0.2 on Windows 10 1903.

**Comment by Alt68er** [comment]
Thanks a lot for your comments.-

I AM using your browser extension (KeePassXC-Browser) as stated in the first line of my report ...
I don't know why it is not stated in the debug info.-

Please be so kind and create and create an account in www.geizhals.de and try to login using the autotype sequence 
"{USERNAME}{DELAY 10000}{TAB}{PASSWORD}{DELAY 10000}{ENTER}".
My understanding is that there should be a pause of 10 seconds before remitting TAB and also before remitting ENTER. Here I cannot see ANY pause.
My conclusion was and still is: the DELAY-command - for whatever reason - does not work.

Do you have any idea what can happen and how I can work around?

**Comment by droidmonkey** [comment]
What I am saying is you are not **using** the browser extension. The extension, when connected to KeePassXC, can auto fill login forms for you with the credentials for that site. That feature is completely independent of Auto-Type. 

Try to replicate the issue in notepad or similar to see if it is your Firefox or KeePassXC.

**Comment by Alt68er** [comment]
Now I have it. It didn't realize that - using the KeePassXC-Browser - the Autotype-function is disabled resp. not necessary. And therefore any amendments to the sequence doesn't have any effect. Oh, how blind I was. Sorry!
