### ISSUE TITLE
Win: "Default system" language ignored

### ISSUE THREAD

**Issue by opsi-archIT-KIT** [keepassxreboot/keepassxc#3461]
## Expected Behavior
On a german win10 (version 1809) the UI should be german as in "Settings" the language is configured to "System default"

```
C:\Windows\system32>dism /online /get-intl

Tool zur Imageverwaltung für die Bereitstellung
Version: 10.0.17763.1

Abbildversion: 10.0.17763.107

Bericht zu internationalen Onlineeinstellungen wird generiert

Standardmäßige Benutzeroberflächensprache des Systems : de-DE

```
## Current Behavior
UI of KeePassXC is english

## Debug Info
KeePassXC - Version 2.4.3
Revision: 5d6ef0c

Qt 5.12.3
Debugging mode is disabled.

Operating system: Windows 10 (10.0)
CPU architecture: x86_64
Kernel: winnt 10.0.17763

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.4

**Comment by droidmonkey** [comment]
This is fixed in 2.5.0 accessibility fixes

**Comment by opsi-archIT-KIT** [comment]
When will 2.5.0 be released?

**Comment by droidmonkey** [comment]
Soon
