### ISSUE TITLE
Win: AppData in "Local" instead of "Roaming"

### ISSUE THREAD

**Issue by opsi-archIT-KIT** [keepassxreboot/keepassxc#3462]
## Expected Behavior
AppData of KeePassXC (e.g. keepassxc.ini for personal settings) for the current user should be in "Roaming"

## Current Behavior
AppData is located in "Local"

## Context
Environment with "roaming profiles" (e.g. computer pools for students).

## Debug Info
KeePassXC - Version 2.4.3
Revision: 5d6ef0c

Qt 5.12.3
Debugging mode is disabled.

Operating system: Windows 10 (10.0)
CPU architecture: x86_64
Kernel: winnt 10.0.17763

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.4

**Comment by droidmonkey** [comment]
This is a duplicate issue
