### ISSUE TITLE
Recycle bin entries should appear below other search results

### ISSUE THREAD

**Issue by robertgzr** [keepassxreboot/keepassxc#3464]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
I previously deleted an entry for `example.com` and it was moved to `Recycle Bin`.
Hit `Ctrl-f` and search for another `example.com` in the folder `Work`.

In the results list I get:
```
- Work/example.com
- Recycle Bin/example.com
```

I can copy the entry in `Work` because it was auto-selected.

## Current Behavior
[NOTE]: # ( Tell us what actually happens )
In the results list I get:
```
- Recycle Bin/example.com
- Work/example.com
```

And the deleted entry is auto-selected.

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )
Force entries in the bin to always appear below the rest instead of just sorting by folder names.

## Debug Info
KeePassXC - Version 2.4.3
Revision: 5d6ef0c
Distribution: AppImage

Qt 5.10.1
Debugging mode is disabled.

Operating system: Linux
CPU architecture: x86_64
Kernel: linux 5.2.2-122.current

**Comment by droidmonkey** [comment]
Perhaps we shouldn't be searching the recycle bin to begin with. I think there is an open issue for that.

**Comment by droidmonkey** [comment]
Searching is disabled for the recycle bin by default, this won't be implemented
