### ISSUE TITLE
Ctrl-C copies Title when no password saved

### ISSUE THREAD

**Issue by amcdonald714** [keepassxreboot/keepassxc#3465]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
If an entry doesn't have a password, I would expect nothing ("") to be copied to the clipboard. I would not expect Ctrl-C to copy data from a different field instead without warning.

## Current Behavior
[NOTE]: # ( Tell us what actually happens )
Ctrl-C will copy the Title to the clipboard if there is no password. I discovered that I had actually been using the title of an entry as a password because I had accidentally failed to save a generated password in an earlier version where saving was required.

I assumed Ctrl-C wouldn't be used to copy anything other than passwords.

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )
Have Ctrl-C copy "" in the usual interface (i.e. when an entry is selected from the list) if there is no password. Use a different shortcut consistently for Title if necessary (like the way Ctrl-B copies username).

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1. Create an entry with a title but no password
2. Ctrl-C copies the title instead of ""

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )

In normal use, I don't see what my passwords are in KeepassXC or in web interfaces, so there was no way for me to realize that I was copy-pasting a field that wasn't the password. I had been using the title field as a password for an account without knowing it.

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.4.3
Revision: 5d6ef0c

Operating system: macOS Mojave (10.14)
CPU architecture: x86_64
Kernel: 18.6.0

**Comment by bahelit** [comment]
Mind if I tackle this issue? If so what would be the desired out come to resolve this issue? Would it be to just copy an empty string to the clipboard, or maybe pop-up a dialog to notify the user a password hasn't been sent?

Am able to reproduce this on my machine.

KeePassXC - Version 2.4.3
Revision: 5d6ef0c

Operating system: Manjaro Linux
CPU architecture: x86_64
Kernel: linux 4.19.66-1-MANJARO

**Comment by droidmonkey** [comment]
The ideal scenario is to do nothing if there is no password present.

**Comment by bahelit** [comment]
So took a little time to look at this. When pressing Ctrl+C on an entry that is highlighted in the window grabs the title, but searching for an entry and pressing Ctrl+C while the search box is still in focus will copy an empty string. Copy from the "Entries" menus and right-click dialog is grayed out so this isn't an issue.
So will be looking next into how DatabaseWidget::copyPassword get's called when pressing Ctrl+C. This doesn't get called when the password is empty but neither does DatabaseWidget::copyTitle which kinda threw me off, as that's what I expected to happen.

**Comment by droidmonkey** [comment]
The issue is where you have focus changes the functionality of Ctrl+C. This is why making "Copy Password" as Ctrl+C is not a good idea...

![image](https://user-images.githubusercontent.com/2809491/64475373-0c921580-d150-11e9-970e-9aea2039b7ee.png)

See how the dashed lines appear around the title cell, pressing Ctrl+C will copy the title. If the dashed lines are around the username, Ctrl+C copies the username. Ctrl+C in the search field forces a call to the "copy password" function.

The simple fix is to always call the "Copy Password" function even if the password is empty.

**Comment by droidmonkey** [comment]
I just went ahead and made the fix, PR is above
