### ISSUE TITLE
Delete key ⌦ does not delete entry 

### ISSUE THREAD

**Issue by brad2014** [keepassxreboot/keepassxc#3466]
The menu item Entries->Delete Entry shows the delete key icon (⌦) as an accelerator.  But when I select an item, and hit the delete key, the item is not deleted.

## Expected Behavior
- dialog box should come up: `Do you really want to move "foo" to the recycle bin?`

## Current Behavior
- nothing

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )

## Steps to Reproduce
1. select entry
2. hit delete on keyboard (macbook pro)

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )
As far as I can tell, the only way to delete an entry is via the app menu or the entry's context menu. I couldn't find a working keyboard accelerator.

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.4.3
Revision: 5d6ef0c

Libraries:
- LIBS

Operating system: MacOS 10.14.6
CPU architecture: x86
Kernel: Darwin Kernel Version 18.7.0: Thu Jun 20 18:42:21 PDT 2019; root:xnu-4903.270.47~4/RELEASE_X86_64 x86_64

Enabled extensions:
- none

**Comment by droidmonkey** [comment]
You probably need to press Fn + Del

![image](https://user-images.githubusercontent.com/2809491/63563859-99be5300-c530-11e9-866d-8f5b4f28ca04.png)

**Comment by brad2014** [comment]
Thank you!  That's it.
