### ISSUE TITLE
Increase timeout for TouchID login

### ISSUE THREAD

**Issue by milkotodorov** [keepassxreboot/keepassxc#3467]
It's great that the quick unlock now is working with the TouchID, but it would be much better if we can login from the beginning with the TouchID and don't use password at all. Just like in the 1Password there could be a password request every 2 weeks.

**Comment by droidmonkey** [comment]
I really wish there was a good way to test this without having a macbook pro/air.

**Comment by milkotodorov** [comment]
VirtualBox with installed MacOS?

**Comment by erikvanoosten** [comment]
I tried https://github.com/wimpysworld/quickemu recently, works amazingly well!

Unfortunately, it is of course without touch id :(

**Comment by droidmonkey** [comment]
This will be closed with the final tweaks to Quick Unlock, duplicate of #7445
