### ISSUE TITLE
`-k, --key-file` option in `keepassxc.ini`

### ISSUE THREAD

**Issue by Dauliac** [keepassxreboot/keepassxc#3468]
Could you include an option that include the `-k` `--key-file` flags in the `keepassxc.ini`
only exist in `keepassxc-cli` call.

The option could take this behavior for example:
```ini
[keepassxc]
database=mydatabase.kbx
keyfile=mykeyfile.key
```
Have a nice day

**Comment by droidmonkey** [comment]
We already have that in the settings under general. You can remember previously used key files for opened databases.
