### ISSUE TITLE
Wayland: Tooltips and menus appear with an offset in multi-monitor setups.

### ISSUE THREAD

**Issue by chron-isch** [keepassxreboot/keepassxc#3469]
I use a laptop and switch workplaces/desktops relativly offen, but as soon as I connect an external display and give it a fixed absolute position tooltips and menus appear with an offset on Wayland compositors(Sway in this case, but this also happends in other compositors).

## Expected Behavior
Toolstips and menus should show up where my mouse is, not with an offset.
![tooltip_offset4](https://user-images.githubusercontent.com/1332352/61699864-f82ec080-ad3b-11e9-910b-f793688ddbb2.png)

## Current Behavior
![image](https://user-images.githubusercontent.com/1332352/61697874-af6d0c80-ad27-11e9-8c5f-43800a7812d6.png)
![image](https://user-images.githubusercontent.com/1332352/61697886-b4ca5700-ad27-11e9-8830-6027e5d0306e.png)

## Possible Solution
Already discussed here: https://github.com/swaywm/sway/issues/3135
QT fix: https://github.com/swaywm/sway/issues/3135#issuecomment-459217564
https://community.kde.org/Guidelines_and_HOWTOs/Wayland_Porting_Notes

## Steps to Reproduce (in Sway)
Assign a second output a fixed position and disable the first output.
```
# swaymsg output HDMI-A-1 position 1366 0
# swaymsg output eDP-1 disable
```
```
# swaymsg -t get_outputs
Output HDMI-A-1 'Unknown HP E243 CNK9030QM3' (focused)
  Current mode: 1920x1080 @ 60.000000 Hz
  Position: 1366,0
  Scale factor: 1.000000
  Subpixel hinting: unknown
  Transform: normal
  Workspace: 3:files
  Available modes:
    [ removed for readability ]
    1920x1080 @ 60.000000 Hz

Output eDP-1 'Unknown 0x04E3 0x00000000' (inactive)
  Available modes:
    1366x768 @ 59.993000 Hz
```
Output eDP-1 is disabled, HDMI-A-1 stays at position 1366,0.

Tooltips and menus appear with an offset:
(see screenshots above)

## Context
Leaves you unable to really use keepassxc, not being able to right-click or use a menu is very limiting.

## Debug Info
KeePassXC - 2.4.3
Revision: 5d6ef0c

Operating system: Archlinux
CPU architecture: x86_64
Kernel: 5.2.9.a-1

**Comment by droidmonkey** [comment]
This is a Qt bug and has been discussed before.

**Comment by chron-isch** [comment]
Fair enough, could you please point me at the previous ticket or even bettter yet, the qt ticket? I can't seem to find it.

**Comment by droidmonkey** [comment]
Yes
