### ISSUE TITLE
Autotype: +{TAB}does not work as expected

### ISSUE THREAD

**Issue by tchamade61** [keepassxreboot/keepassxc#3470]
## Expected Behavior
+{TAB} should send SHIFT+TAB sequence. (This works in Keepass.)

## Current Behavior
KeepassXC sends plus ('+') and TAB.

## Possible Solution
Unknown.

## Steps to Reproduce
1. Create an entry in keepass database with a +{TAB} in the autotype sequence.
2. Open a browser to a login page.
3. Highlight the entry in the keepass database.
4. Press auto-type button or invoke keyboard shortcut.

## Debug Info
KeePassXC 2.4.3
OS: XUbuntu 19.04

**Comment by droidmonkey** [comment]
The + modifier is not implemented. This is a duplicate issue.
