### ISSUE TITLE
macOS: Not possible to enter some special characters (only when password value is exposed)

### ISSUE THREAD

**Issue by dotWee** [keepassxreboot/keepassxc#3472]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
1. Select working KeePass database file
2. Enter password with special character like a tilde (`~`) into the password field with characters hidden
3. KeePassXC unlocks database

## Current Behavior
[NOTE]: # ( Tell us what actually happens )
1. Select working KeePass database file
2. Enter password with special character like a tilde (`~`) into the password field with characters hidden, but character won’t append to field value

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )
1. Select working KeePass database file
2. Before entering a special character like a tilde (`~`) into the password field, press on the eye icon the make password visible
3. Special character will appear just like a normal letter
4. Press on the eye icon to hide the password
5. Continue as usual

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1. Select working KeePass database file
2. Try to enter special character like a tilde (`~`) while the characters are hidden

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )
**It is not possible to enter a complicated password without exposing it everyone.**

Related issues:

- #1117

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.4.3
Revision: 5d6ef0c

Qt 5.12.3
Debugging mode is disabled.

Operating system: macOS Mojave (10.14)
CPU architecture: x86_64
Kernel: darwin 18.7.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
 libgcrypt 1.8.4

**Comment by droidmonkey** [comment]
This is a bug in Qt and has been discussed before. We cannot fix it.
