### ISSUE TITLE
waste of time ....

### ISSUE THREAD

**Issue by dachmiitz** [keepassxreboot/keepassxc#3474]
just had a look at keepassxc for windows ….

whilst it might be technically competent at a security level there is no font change/select feature so for me that's a null points rating and I will now uninstall keepassxc

an app that needs nm to use a magnifying glass to use it is no good to wo/man or beast

in this day an age, no true type font ? the keepassxc developers need to get in the 21st century

I'll keep checking back and if the keepassxc developers get around to providing a font change /select feature I'll give it another

**Comment by droidmonkey** [comment]
Thanks for your feedback
