### ISSUE TITLE
Unexpected Internet Connections

### ISSUE THREAD

**Issue by StarPicard** [keepassxreboot/keepassxc#3479]
Hey, after I enter the command below, I get a message that KeepassXC initiates connections to the Internet. Is this a display error or do you know the servers / IPs?

Thx!

## Expected Behavior
No Internet connections at all

## Current Behavior
According to:
`lsof -i -P | grep ESTABLISHED | grep keepassxc`
KeepassXC is connecting to the following Servers:
```
a23-2-13-168.deploy.static.akamaitechnologies.com:80
ec2-52-43-174-132.us-west-2.compute.amazonaws.com:443
93.184.220.29:80
```

## Steps to Reproduce
1. Start KeepassXC
2. Unlock the Database
3. Create an entry
4. Minimize KeepassXC to the tray

Was not able to reproduce it.

## Debug Info
KeePassXC - Version 2.4.3
Revision: 5d6ef0c

Qt 5.13.0
Debugging mode is disabled.

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 5.2.9-arch1-1-ARCH

Enabled extensions:
- Auto-Type
- Browser-Integration
- SSH-Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.4

**Comment by StarPicard** [comment]
I'm not betting because I'd lose my money ;) Thanks for the explanation!
The funny thing is that I've done my best to turn tracking and telemetry of...

**Comment by benonilearns** [comment]
Bumping this because i have my firefox telemetry closed yet still see a connection on port 443. Really disliking this. 

```
sudo lsof -i -P -n | grep ESTABLISHED

keepassxc  5510          username  122u  IPv4 13714724      0t0  TCP 192.168.1.X:37260->34.212.158.50:443 (ESTABLISHED)
```

![ff](https://user-images.githubusercontent.com/44271101/64134110-c2253780-cde3-11e9-9741-f8b874397c0e.png)

For a quick work around maybe we can create a no-internet user with the help of ip tables?

**Comment by droidmonkey** [comment]
See https://support.mozilla.org/en-US/kb/how-stop-firefox-making-automatic-connections

If you are not running Firefox, do you still see these connections?
