### ISSUE TITLE
How can I decrypt "LastKeyFiles" in ini

### ISSUE THREAD

**Issue by mueller-ma** [keepassxreboot/keepassxc#3481]
I have a full file system backup and want to extract the KeePassXC database and key file.
The entry `LastKeyFiles` in `keepassxc.ini` in `AppData` contains a long string starting with `@Variant(`. How can I decrypt this string to know, which file was used as key file?

OS: Windows 7 64bit

**Comment by phoerious** [comment]
It's not difficult to decode. Simply delete all `\0` bytes and the rest is a mixture of ASCII characters and hex codes prefixed with `\x`, which you can decode into ASCII as well.

**Comment by mueller-ma** [comment]
Thanks, I was able to read the entry.

**Comment by RmiTtro** [comment]
For anyone else that land here, it is also possible to get the value using python and PyQt6:

```python
from PyQt6.QtCore import QSettings

settings = QSettings("keepassxc.ini", QSettings.Format.IniFormat) # This import the keepassxc.ini of the current directory
settings.value("LastKeyFiles") # This will return you the value

# Do this if you need a value from a key under another group than [General]
settings.value("GUI/ListViewState") 
```
