### ISSUE TITLE
Enable "group" field to be searched

### ISSUE THREAD

**Issue by dssouza-ti** [keepassxreboot/keepassxc#3482]
## Summary
I would like to find all entries in a group by searching for the groups name.

## Desired Behavior
Let's say I have my database organized in the following way:

groups -> subgroups -> entries:
![image](https://user-images.githubusercontent.com/16449739/63857330-e0211100-c979-11e9-8f8e-d665a38f2d31.png)

If I search for "subgroup1", I want the search results to bring me all entries within all groups named subgroup1:
![image](https://user-images.githubusercontent.com/16449739/63859878-8707ac00-c97e-11e9-8f4a-5289751906b3.png)

If I search for "client2 subgroup3", I want only the entries in subgroup3 of group client2 to be shown as a result:
![image](https://user-images.githubusercontent.com/16449739/63859888-8b33c980-c97e-11e9-9047-4ae8d2e77539.png)

## Current Behavior
Today it's not possible to search for group names, since the group field is not enabled in the search feature:
![image](https://user-images.githubusercontent.com/16449739/63859899-9129aa80-c97e-11e9-81f0-553bde74ec7e.png)

Search help:
![image](https://user-images.githubusercontent.com/16449739/63858713-62aad000-c97c-11e9-9e81-21c5c6f85236.png)

## Possible Solution
Enable the group field in the search feature

## Context
I'm an I.T. service provider with several clients. I have a database with more than 80 groups named after the clients and all of them have the same subgroups, which are named after equipment categories, for example: group "Client1" -> subgroups "Storage", "Firewall", "VPN".

Inside the subgroups, the entries names always are different, because my clients use different equipments, so client 1 firewall will be a Sonicwall, while client 2 firewall will be a Fortigate, and so on.

It's very common that I need to search for entries in a "firewall" group within a specific "client" group, or search for all entries in every "storage" group within all "client" groups, and I can't do that now because the "group" field is not enabled to be searched. I did that a lot when I was using mono implementation of keepass, but I find keepassxc way better in several aspects, so I'm using it anyway, but it's really a bummer not being able to perform a search like this.

**Comment by tomhundt** [comment]
> You can enable "group scoped" search by clicking the search icon to the left of the bar. With that, just select the group you want to search in and do your search.

Ha, yet another feature I never new existed, thank you for pointing it out :-)  
I'm using the Mac version (2.4.3) and it only drops down the menu if I click on the rightmost third of the binocular/gear search icon.  (I'll test this some more and log it separately.) 

> Search used to include group names by design but it didn't make sense to do this as searching returned results that had nothing to do with the desired search query (which is normally for a specific entry ).

Ah, I was just about to suggest search should include groups, and moreover, that it should include the _notes_ for the groups.  I have, for example, a "Computers" group and the Notes for it says "Local laptops/desktops/computers/PCs/servers/machines" which are all keywords I'd like to be able to search for.

So in the OP's use case, he would be able to type "g:acme firewall" and get the "Firewall" entry in the "Acme Corp" group.  Or in my case I could type "g:laptop jane" and get any entry with "jane" that's in my Computers group.

An alternative implementation would be to have an Application Setting like "Include groups in searches" which would try to match _all_ the search terms to Groups also.

**Comment by danoe** [comment]
It would be really nice to have the group included in searches. Same use-case as @dssouza-ti basically, every group is a server name here, with the actual entries being for services, like SSH, HTTP, MySQL etc.
In my case the server name is not referenced anywhere on the actual item, the URL field is set with the IP address in most cases or just empty.

**Comment by droidmonkey** [comment]
The group name is listed on the far left of search results. You can sort by group name in the results.

**Comment by danoe** [comment]
I saw that, thanks, and just tested, typing a letter makes it jump to that letter too, which is nice.
Though, after opening a group, I have to switch back to the top folder and search `*` again.

**Comment by johanfleury** [comment]
> Search used to include group names by design but it didn't make sense to do this as searching returned results that had nothing to do with the desired search query (which is normally for a specific entry ).

Just to add some more to this conversation, I used to search by group name because I have group named after some servers.

So, for instance, I used to search for `foobar2000`, get to the "root" entry and copy the password. Now I need to go to the group, and look for the root entry, search bar has no interest in this case anymore.

**Comment by HoffmannP** [comment]
+1 for group search, same as johanfleury. We have a bunch of servers all containing MySQL root and SSH root. So just searching for title:mysql user:root still gives me to many.
group could als use the `[$groupname] > [$subgroup] …` syntax you see at the bottom when a group is selected

**Comment by smoebody** [comment]
I just want to mention that *keepass*-search includes groups as well and it would make migration much easier. As mentioned by a lot of people before, we also have a group per server (whether this is clever or not) and searching for it is currently not possible.

Thanks to @droidmonkey for addressing this.

However i want suggest not to have the term prefixed by `g:` or `group:` since one has to be aware that it is searching a group. Instead i would appreciate a setting like "include groups in search" as @tomhundt suggested.

**Comment by tomhundt** [comment]
As a workaround if one is really desperate for searching by groups, one could use the command-line version of the program, and just keep it running in a window:
```
$ keepassxc-cli open ~/mydb.kdbx
mydb> ls -Rf 
TEST/
TEST/H TEST
TEST/TEST - Clone
TEST/TEST1
TEST/TEST2
TEST/TEST2 - Clone
mydb> ls TEST
H TEST
TEST - Clone
TEST1
TEST2
TEST2 - Clone
mydb> show TEST/TEST1
Title: TEST1
UserName: just.a.spacer
Password: PROTECTED
URL:
Notes:
mydb> show -s TEST/TEST2
Title: TEST2
UserName: joe.user
Password: something🤣else
URL: http://test2.foo/
Notes:          (__)
         (oo)
  /-------\/
 / |     ||
*  ||----||
   ^^    ^^

Example table (lines up correctly in fixed width)
ID      USER    STATUS
123     foo     Failure
400     bar     Awesome

```
Here, `TEST` is the name of the group (sorry, lame example) and the things next to it (`TEST2 - Clone`) are entries.  It asks for the password when you `open` the db.  You have to use `-s` to get `show` to display the `PROTECTED` items, i.e., the password.

This is not great security.  Make sure you lock your computer when you go for a coffee ;-)

**Comment by smoebody** [comment]
@tomhundt I am not sure whether this is working, at least your example is proving nothing. Since `TEST` is also included in the item names it could be that the search only finds by items.

Try to add new item in group `TEST` with a name like `foobar` and see whether it appears when searching for `TEST`.

**Comment by BO41** [comment]
In https://github.com/keepassxreboot/keepassxc/blob/develop/src/core/EntrySearcher.cpp#L145 does a simple `case` with something like this `entry->group()->database()->rootGroup()->print(true, false)` sound right?
Or is it a more complicated problem?

**Comment by BO41** [comment]
Please help the maintainers to merge #4705 to get this feature (finally) fixed :smiley:
