### ISSUE TITLE
Browser Integration: Show connected Browsers to DB and add possibility to remove connected Browsers

### ISSUE THREAD

**Issue by pkolmann** [keepassxreboot/keepassxc#3484]
##  Summary
I have multiple Browsers connected to my KeepassXC Database. I want to take a look at all the connected Browsers that have accumulated in the Database and also be able to remove browsers I don't want to have access anymore.

## Desired Behavior
Add a tab to Settings -> Browser Integration where you display the connected browsers and add a possibility to remove (a) selected browser(s).

## Context
As stated above I'd like to get an overview which browsers have been connected to the DB.

**Comment by droidmonkey** [comment]
You just go to the database settings then the browser integration section.
