### ISSUE TITLE
Browser plugin: Search in all open databases returns only matches in connected database

### ISSUE THREAD

**Issue by lhurt** [keepassxreboot/keepassxc#3485]
## Expected Behavior
When the option "Search in all open databases for matching credentials" is ticked, it should do so.

## Current Behavior
Only the credentials of the connected database are used and available for fill in.

## Steps to Reproduce
1. Delete all Browser connections in all databases (eg. named A and B)
2. Restart Browser and Keepassxc
3. Open all databases and activate tab A
4. Connect to database A
5. Open Webpage where credentials are stored in B
6. As no autofill happens, right click in keepassxc context menu "fill username and password"
7. System returns "No matching credentials"

Tested with Firefox 68.0.2 and Chrome 76.0.3809.100.
Keepass browser is 1.4.7 and Keepassxc is 2.4.3

## Debug Info
Tested with Firefox 68.0.2 and Chrome 76.0.3809.100.
Keepass browser is 1.4.7 and Keepassxc is 2.4.3

Operating system: Win10 x64
CPU architecture: Intel
Kernel: KERNEL

**Comment by droidmonkey** [comment]
I'm torn on this because I feel like this is expected behavior. The default behavior is the plugin only queries the currently active, connected database. The extended behavior would then make sense to query all open connected databases.

**Comment by lhurt** [comment]
The option reads "Search in all open databases for matching credentials" and this pretty clearly implies my described expected behavior.

My use case is that I separate the passwords in different databases for sharing. One database is common and another contains only my personal ones. It's pretty unhandy to open Keepassxc and change the active database. I don't get the point why this should be necessary. If the database is open, you proved to have the right credentials for it and then you should be able to use it.

Actually this worked some way in the past and I'm missing it now a lot.

**Comment by varjolintu** [comment]
#3480 changes the tooltip to "All databases connected to the extension will return matching credentials" which makes the option clearer.

This is not a bug, and you can get entries from multiple databases if those databases are connected to the extension. Previously (in the KeePassHTTP plugin also) users were able to read credentials from all open databases without connecting them to the extension, which is actually considered as a leak. We prefer that user always has to approve the database to give credentials to the extension, meaning conneting the extension to the active database.

**Comment by lhurt** [comment]
@varjolintu The point is clear. But then we have another bug, because in the current version it's impossible for the browser plugin to connect to multiple open databases simultaneously.
Therefore the use case is still broken.
As soon as I connect to another database, the old connection gets deleted. Do you want me to create another bug for that and where? I suppose its the https://github.com/keepassxreboot/keepassxc-browser repo, right?

**Comment by varjolintu** [comment]
It's not a bug that you cannot connect multiple databases simultaneously. Mostly that is restricted because usually there's no need for a such feature. But you can always make a feature request about it.

The old connection gets deleted? You mean a situation where you connect multiple browsers to same database? But yes, please do a new bug report about it.

**Comment by lhurt** [comment]
This leaves me a bit helpless and may be I get something really wrong.

My use case is that I have **multiple** (4) keepass **databases** because I want to have **separate access** (e.g. business and private). When I open my browser I want to have **access to all** of the credentials in all of the databases. Therefore **all** of them **are open**.

_Now here is my problem._
You state [above ](https://github.com/keepassxreboot/keepassxc/issues/3485#issuecomment-526826587)that the browser has to be connected to every database it wants to receive credentials from.

> This is not a bug, and you can get entries from multiple databases if those databases are connected to the extension.

but in your [last comment](https://github.com/keepassxreboot/keepassxc/issues/3485#issuecomment-527440130) you wrote

> It's not a bug that you cannot connect multiple databases simultaneously. Mostly that is restricted because usually there's no need for a such feature. 

So what's the point then having a setting "**Search in all opened database for matching credentials**" if this is impossible anyways? And why is there a "Connect" button in the browser extension then?

I'd really like to understand that. BTW in the past it was possible to connect to multiple databases.

Thanks in advance.

**Comment by varjolintu** [comment]
Let's make this clear. To **connect** always means connecting to a non-connected database. Having access to a connected database means it's **associated** with it, so there's a permission to read/write.

So, it's possible to have multiple databases **associated** at the same time, if all of those are **connected** to the extension, and the "Search in all open databases for matching credentials" option is enabled.

A database must be **connected** to the extension before it's **associated** to retrieve any credentials or data.

It "worked" previously because there was a bug that allowed all open databases to retrieve data (so all db's were automatically **associated**) even if only one of those was **connected**.

**Comment by lhurt** [comment]
Thanks for your answer. This confuses me even more as you now introduce new terms that don't show up in the UI. I think I got you.

Nevertheless you stated above that it's impossible to connect to multiple databases and that's also my observation. As said I have 4 databases, all are open and my browser options only shows one row similar to this (a key is partially visible)
![198001](https://user-images.githubusercontent.com/379072/64177710-5503b780-ce60-11e9-921a-40213c50259e.png)
I can change the database connection (I refer to the screenshot) but I have to close KeePassXC, reopen it, open all databases and switch the active tab to the database I want to connect to. Otherwise I didn't find a way to connect another open database. The row displayed on the screenshot will change and the previous content will be replaced by the new association with the new name and a new key. There won't be a second row.

It would tremendously help and I would appreciate it very much if you could help me and tell me a way how to connect and associate multiple databases. I don't find a way how to do it.

Thank you very much.

**Comment by varjolintu** [comment]
The steps:
1) Open the first database, and connect it from the extension
2) Switch to a second database, connect it also (give it a different name). Repeat the steps for third and fourth database
3) If "Search in all open databases for matching credentials" is enabled, you can get credentials from all open databases that are now connected

**Comment by lhurt** [comment]
Thanks. Unfortunately that doesn't work. I can only connect one database.

When I switch to another database by changing the tab in KeePassXC and one database is already connected in the browser plugin the "Connect" button does nothing. No windows opens at all, even under the browser window there's nothing.

**Comment by varjolintu** [comment]
Then I suggest that you remove all databases from the extension's list, and delete the connection keys from your databases via KeePassXC. A fresh start could work.

**Comment by lhurt** [comment]
Didn't work. I clicked "Disconnect all browsers" in all databases. Restarted KeePassXC and Chrome.

After connecting the first database the Connected Databases look like this.
![2019-09-03 16_34_45-Settings _ KeePassXC-Browser](https://user-images.githubusercontent.com/379072/64186854-d7e03e80-ce6f-11e9-9966-24e411f037f7.png)
The Connect button still didn't do anything after switching the database. After restarting Chrome the changed database was recognized and I was able to connect the other one. But instead of adding the connection to the list the old one was replaced as before.
![2019-09-03 16_36_13-Settings _ KeePassXC-Browser](https://user-images.githubusercontent.com/379072/64187011-14ac3580-ce70-11e9-8b4b-5c81a39cab50.png)
Nevertheless the keys are present in the respective databases. So each one has an entry.

This is a mistery to me.

**Comment by lhurt** [comment]
Could verify the behavior on Linux with Firefox as well.

**Comment by varjolintu** [comment]
@lhurt The connection shouldn't be replaced. Are you able to debug the settings page script `options.js` and see what really happens there? I cannot reproduce this error.

**Comment by lhurt** [comment]
@varjolintu I could try, but after having a look at the script it would be helpful if you could provide a bit of assistance at which function to look.
My idea was to debug the part where a new database is connected to the browser, but I didn't find a sufficient place in the script to place a breakpoint.

Any other ideas?

**Comment by lhurt** [comment]
@varjolintu I tried to track the issue down by the following steps,

1. A browser had one associated database.
2. changed the active database tab in keepassXC
3. restarted the browser to make him associate the database of the changed tab
4. Clicked "connect" on the options/connected databases page
5. Stepped in the debugger to the point where the name for the association is requested. (keepass.js:126). The message contained all the information of the new connection. Here's the request object (some data shortened with ...).
```
request:
	action: "associate"
	clientID: "ZB9xxkKsluyWJW...."
	message: "0AbgKJ5oDny9jfBhclG/MViWiAT06dxQpJxUtPUspHeRB1lx1NElAHzY...."
	nonce: "k9TJNdrdtNFIOxiJ...0"
	triggerUnlock: "true"
```
6. I wasn't able to debug the message sending itself, but after this call returned the old connection was replaced by this one.

My Javascript knowledge is too limited to be able to dig deepter without spending days.

----

The second issue is that if there's an associated database and the active tab in keepassXC is switched, something is triggered in the extension leading to the effect that the connect button on the  options/connected databases page has no effect at all.

I'm not sure what is related to keepassXC and what to the browser extension. Please let me know if you want me to split it an create a new ticket in the [keepassxc-browser](https://github.com/keepassxreboot/keepassxc-browser) repository.

Would be great if someone could help.

**Comment by varjolintu** [comment]
@lhurt I suggest you test the KeePassXC snapshot build and see if this still happens. Also, a new extension version will be released soon that fixes some of the connection issues people are having.

**Comment by lhurt** [comment]
@varjolintu Thanks for the suggestion. Unfortunately the situation didn't change.
