### ISSUE TITLE
Highlight Master Password When Incorrect Password Entered

### ISSUE THREAD

**Issue by jackdozier** [keepassxreboot/keepassxc#3487]
## Summary
It's fairly common for me to mistype my master password when unlocking my database. When I do this, I prefer to just retype the whole password again from scratch as it's more a muscle memory thing rather than actual memory. In order to do that, though, I have to press Ctrl-A to select the entire password field. This works, but it's an extra step.

I'm running version 2.4.3 on Centos 7. I searched the bug database for a similar issue, but didn't find it. Feel free to let me know if this is already implemented in some way.

## Desired Behavior
After typing a password on a master key and attempting to decrypt the database, if the database fails encryption, show the message that says "Error while reading the database: Invalid credentials were provided..." and then select the entire password field so that the user can begin typing their password again to attempt a new unlock.

## Possible Solution
If this isn't a desired default feature, it could be added but controlled via a setting in the Settings panel. Something like "After incorrect master password entered, auto-select password field to allow new entry". Or even "After incorrect master password entered, clear password field"

## Context
Discussed in Summary

**Comment by droidmonkey** [comment]
I like it

**Comment by phoerious** [comment]
If we implement this, we should add two more minor changes:

- correctly reset visibility toggle button (right now the password is reset to bullets, but the toggle button is not)
- add warning for cAPSLOCK

**Comment by droidmonkey** [comment]
CAPSlock detection is challenging across platforms, not impossible though.

**Comment by phoerious** [comment]
Doesn't seem to be too difficult:

https://github.com/savolai/Qt-Widgets-password-dialog-with-Caps-Lock-check/blob/master/passworddialog.cpp#L36

https://stackoverflow.com/questions/49561510/how-to-detect-the-status-of-the-capslock-in-linux-programmatically

https://developer.apple.com/library/archive/qa/qa1519/_index.html

**Comment by Maxqia** [comment]
I have a old commit for a toggle for clearing the key when you hit enter.
https://github.com/Maxqia/keepassxc/commit/99806f1cf1b087db7530fafcb3f74dd2d572171e
IIRC i did this because at the time KeepassXC cleared the password all of the time and I wanted it to stop doing that, but it doesn't do that now
It'd probably need some work to make it mergable again....

**Comment by droidmonkey** [comment]
That is not desirable behavior
