### ISSUE TITLE
Auto-Type on more Key matches

### ISSUE THREAD

**Issue by RolandSM** [keepassxreboot/keepassxc#3489]
Hello,

I come from KeePass2 in my Kubuntu because I want to try in near future a YubiKey. KeePassXC looks very great against KeePass2 and I like it already.
Currently I use 2.4.3 with Chrome & Firefox Browser integration.
Is there a possibility to autofill a form from an website-login, where more than one matches are found?
In KeePassXC I can set every entry, if Auto-Type is enabled or not. This I have done, but the Auto-Type is not working when only one entry is with this box enabled?

If there is only one record matching with the domain, all is working as well.

Greets

**Comment by droidmonkey** [comment]
Auto-Type and browser integration are two separate features. If multiple entries have the same domain in the url field (and schema, ie http vs https) then they will be returned to the browser plugin and you can choose which one you want.

**Comment by RolandSM** [comment]
Is it not possible to set one as default which is filled, not submitted?
If I want I can select one of the others, but in 80% of cases the only one is the main one?

**Comment by droidmonkey** [comment]
Not at this time, no. That might be a good feature but can be complicated to setup
