### ISSUE TITLE
Add: change created date and modified date

### ISSUE THREAD

**Issue by eeKpass** [keepassxreboot/keepassxc#3490]
Hello Keepassxc,

i use an iMac (2011) and macOS 10.13.6. (+ including current secure update)

I am using current 1Password (7.3.2) version
https://app-updates.agilebits.com/product_history/OPM7

But I don't want to use 1Password anymore, because of their business model.

I used KeePassXC (2.4.3) for the first time. And I think it works very well and the UI/UX are enough for me.

Now comes the problem. I have over 100 notes in 1Password that have a lot of text. The texts also have special characters (but all typed with the english keyboard).
I have in 1Password the "Export" function and the selected (most important to me ) "Title" "Notes" "Modified Date" "Created Date" and "Tags"** and then saved as csv file (over 1.5 MB in size).
** Tags, too, but KeePassXC does not support tags. Here I have as an alternative the folder (group) function

In the csv file everything is added correctly for each column (according to my observations).

Then I used the import csv function of the KeePassXC. But it doesn't work wait over 5 hours and the software doesn't respond.

Even if I make fewer entries so 3 notes in a single csv file, it sometimes and then again does not work.
-------------------------

The title and notes can be copied manually and then added to KeePassXC manually (it takes a long time), but better than nothing. But can't change the **modified date** and **created date** manually.

So here's my proposal. Can you add a function where the user can change the "modified date" and "created date" for the entries? It is very important to me because of the history of the notes.

**Comment by droidmonkey** [comment]
We have a 1Password vault import in 2.5.0

**Comment by SmootheSmooth** [comment]
I only use KeePassXC (2.6.0) AppImage on my Linux Notebook and generally look for the possibility to change the Created Time and Modified Time of the entries.

Is that possible?

**Comment by droidmonkey** [comment]
No

**Comment by SmootheSmooth** [comment]
> No

Can you support it?

**Comment by droidmonkey** [comment]
Yes since this is still an open request
