### ISSUE TITLE
import xml data preserving group hierarchy

### ISSUE THREAD

**Issue by 8fo8tHRcc3** [keepassxreboot/keepassxc#3492]
I used the revelation password manger (https://revelation.olasagasti.info/index.php) in previous releases of Ubuntu, no longer included as of 19.04 as the project has not been actively maintained since 2012.

revelation will export data in XML format which preserves the group hierarchy.

A KeePassxc import option to import from XML could be useful.

Sample revelation XML export file:

[revelation-xml.txt](https://github.com/keepassxreboot/keepassxc/files/3563778/revelation-xml.txt)

**Comment by droidmonkey** [comment]
There is no such thing as "import from XML" as XML is unstructured. You must import from a specific schema, this one being the schema used by Revelation. We are not going to implement that for obvious reasons.

**Comment by varac** [comment]
@8fo8tHRcc3 I also need to migrate from revelation to keepassxc and will give https://github.com/wzzrd/keepass-converter a try.

**Comment by droidmonkey** [comment]
That's the power of open source right there!
