### ISSUE TITLE
Support key files with Auto Open feature

### ISSUE THREAD

**Issue by metaphys** [keepassxreboot/keepassxc#3495]
## Summary
Currently the auto open feature does not support auto opening database that require a key file

## Desired Behavior
The auto open feature should be able to open any database that keepass can open manually

## Possible Solution
- The key file path could be provided in a special field
- the key file could be provided as an attached file (like for the ssh-agent)

## Context
Key file are an important factor of security for a DB. Supporting them in every case use is important to push for better security

**Comment by droidmonkey** [comment]
The key file doesn't add any additional security over a longer password. It all gets added together in the master key. Unless you must open the file separately from the original, just use a very long master password.

**Comment by metaphys** [comment]
the way I understand it a keyfile is the only way to make brute force nearly impossible. Use case: database on the cloud, keyfile on a local device.

**Comment by droidmonkey** [comment]
To make brute force nearly impossible you do two simple things:

1. Use KDBX4 and Argon2 (defaults on new database)
2. Use a [randomized] password that is 15 characters or more in length

**Comment by metaphys** [comment]
Is this documented somewhere? Basically what you are saying is that keyfile should be made obsolete?

**Comment by droidmonkey** [comment]
The keyfile is good if you want a simpler password, but add more entropy through a randomized password (aka keyfile) appended to it. It is not obsolete, but my professional opinion is a keyfile is not necessary to protect a database given what I said above. Brute force protection is not related to key files.

**Comment by metaphys** [comment]
ah ok but in my case I don't use a fully randomized password, i use only only 3 randoms words out of a ~13000 entries dictionary so I guess I do need a keyfile. I also like the principle of having two factors. Ideally given how critical this can be used, I would like to have also TOTP to open the database

**Comment by droidmonkey** [comment]
TOTP is not useful for encrypted storage. If you increase your word count to 6 you become very nearly unbreakable.

**Comment by metaphys** [comment]
Well I'm not sure if this is the place to go on with this discussion. If not let me know. 
Me apart, I don't know anybody that would use 6 random words or a 15 letters gibberish password. They all call me paranoid and so on. And I don't care.
But this is a problem because if I need to share a DB with someone, either they will change the password, here goes the security, or they will not use it because they find it impractical, here goes the utility. In that case a keyfile can bring a middle way (which in turn bring its own constraints, but the whole point of having as many authentication way as possible is that you can adapt the tools to your public and use case, and you can combine them as a safeguard if one of them get compromised...)

**Comment by droidmonkey** [comment]
I support the feature request to allow key file attachments in the Auto Open definition. It'll just take a bit of work to implement it.

**Comment by metaphys** [comment]
Actually I think that I just did it. Let me find how to make a pull request...

**Comment by metaphys** [comment]
here we go...
#3504

**Comment by foorschtbar** [comment]
> allow key file attachments in the Auto Open definition

I searched the documentation and the issues/PRs, but i cant find this feature. Is it implemented? I have a keyfile as attachmend, the path to database and the password and want to open the 2nd database like KeePass Windows Application

**Comment by droidmonkey** [comment]
No that isn't supported
