### ISSUE TITLE
Strange way of presenting the results of a search

### ISSUE THREAD

**Issue by liar666** [keepassxreboot/keepassxc#3496]
Hi,

Thanks again for the tools, they are very usefull!!!

Here is a problem that took me a while to figure out...

Let's imagine the following setting: 
- Group 1
  - Entry 1 & Entry 2
- Group 2 [ with "notes" matching "cool" ] 
  - Entry 3 & Entry 4 & Entry 5 & Entry 6
- Group 3
  - Entry 7 [ matching "cool" ]
(when nothing specified, entries/groups have nothing to do with "cool")

Currently, in KeepassXC, if I search for "cool", then the results list will contain:
Entry 3
Entry 4
Entry 5
Entry 6
Entry 7

This is not the expected result, as none of Entry 3 & Entry 4 & Entry 5 & Entry 6 is matching anything related to the query!
It should display only
Group 2
Entry 7
Which are indeed the 2 only entities  matching the query.

As I understand the problem, you designed the results list to contain objects of type Entry, thus when a Group matches, you display all its Entries.
This is wrong (see below explanations in actual settings).
You should create an object/interface on top/common to Entry/Group and display that as results.

I created a Minimum Workable Prototype file (pass = password) (link will work until September 9)
https://lufi.alolise.org/r/ExdRrowopn#g2fTwY+dtkvkll4MODXT/JMouKmlwcbqS+nCRkGNqWA=

Here is the troublesome result of the query:
![strange](https://user-images.githubusercontent.com/3216927/64114491-64660080-cd8d-11e9-92b3-a229e67bac4d.png)

In my actual settings, I have several groups with hundreds of passwords each, and each with a  "notes" field that describes the entries in the group. If I search for a specific Entry, I almost always get the whole Group as a result a search, as the "notes" fields as many chances to match the same keywords as one of its Entries.
The current behaviour renders the use of the "search" functionality totally useless in this simple setting.

Cheers,

**Comment by dssouza-ti** [comment]
Hi,

What I asked for here #3482 could be related to what you need.

**Comment by droidmonkey** [comment]
We don't do any matching against groups

**Comment by droidmonkey** [comment]
You must be using a very old version of KeePassXC that searched group information. I cannot replicate:

![image](https://user-images.githubusercontent.com/2809491/64117891-564fba00-cd64-11e9-9525-6d9c9629df07.png)
