### ISSUE TITLE
TOTP support remote server's time if different to local

### ISSUE THREAD

**Issue by affinityv** [keepassxreboot/keepassxc#3498]
Ordinarily TOTP works perfectly well with local time, but sometimes the server has a slightly different time than local; so it would be good to be able to use the server in the TOTP settings entry as follows:
30;6;http://accounts.google.com

## Summary
TOTP codes are time dependent and the server may be slightly different to local time; so it would be better to use the server's time (any server the user wants) for the time value used when calculating the right TOTP code from the secret.

## Desired Behavior
Allow entry/adjustment of settings field when adding TOTP (including time period, number of required digits and server to use for the time) as per above.

## Context
Because I know that the time of the server can be different; either the local isn't in proper sync with real time clocks or the remote server isn't -- perhaps one or the other end isn't updating properly from NTP or other servers.  If the timing is out, then the results period is skewed one way or the other.

**Comment by droidmonkey** [comment]
The more likely problem is your local computer is out of time sync. It also has to be drastically off since most TOTP receivers accept the last 3-4 entries for this very reason.

**Comment by affinityv** [comment]
I believe that KP2 has server options for time via the actual server in play; I do understand that servers sometimes provide a window for variations to time, but not all servers do.

**Comment by affinityv** [comment]
I actually use a python script that is able to use the server's time; but as with all things like this, it is handy to have alternatives if, for whatever reason, the python script fails.  I don't use authenticators from Google or any other provider and keep TOTP off my mobile.

**Comment by droidmonkey** [comment]
Can you provide your python script as a template? Besides querying via http and parsing the header, I am at a loss for how you know what time the server is currently using.

**Comment by affinityv** [comment]
For the following links, you can see the "formatted" version;
 \- simply remove the trailing / on the links for raw data.

I have these files in my ~/.oathtool directory

 - [http://ix.io/1Uag/](http://ix.io/1Uag/) -- oathtool -- (oathtool.py)
   - [http://ix.io/1Uah/](http://ix.io/1Uah/)  -- .oathtool.conf (has 0600 permissions set)
 - [http://ix.io/1Uam/](http://ix.io/1Uam/) -- make-gpg-file-here
   - [http://ix.io/1Uan/](http://ix.io/1Uan/) -- dropbox (sample service setup file used with make-gpg-file-here)

The get_server_time(server) function is probably all you need, using one of a few methods, but essentially yes, parsing the header from the server; I settled on method 3 as can be seen in the script.

NB: I don't expect the script to be perfect, in fact I'm sure it could be significantly improved upon, but it works for me so long as I have the required python includes from the "use" statements and the gpg versions are compatible.

**Comment by affinityv** [comment]
I also have all the essential data within my KPXC database as well to use the already included TOTP features as they are right now.
