### ISSUE TITLE
Last key created will be saved and the previous ones disappear

### ISSUE THREAD

**Issue by stickmanChampion** [keepassxreboot/keepassxc#3500]
## Expected Behavior
Save all keys created

## Current Behavior
Only saving the last key

## Steps to Reproduce
1. Open
2. Create several keys (only the title needed)
3. Close
4. Open
You will see that the only the last key was saved.

## Context
Last time I made modification I lost all of them except one key.

## Debug Info
KeePassXC - 2.4.3
Revision: REVISION

Libraries:
- LIBS

Operating system: OS
CPU architecture: ARCH
Kernel: KERNEL

Enabled extensions:
- N/A

**Comment by droidmonkey** [comment]
See #3415

**Comment by stickmanChampion** [comment]
Thanks for the solution.
I probably will use a VM in the mean time since the update is on Beta.

But it's the same as the others. AMD 3xxx
