### ISSUE TITLE
Error while reading the database: Invalid number value

### ISSUE THREAD

**Issue by wjjessen** [keepassxreboot/keepassxc#3505]
I have a KeePass 2 database that is stored on NextCloud and is accessed with KeePassXC on my MacBook. Using the NextCloud app KeeWeb (v1.8.2), I created a new record in the database. Now KeePassXC is unable to open the file, displaying the following in red when the password and key file are provided:

`Error while reading the database: Invalid number value`

Database format: KeePass 2
KeePass file version: 3.1
Database generator: KbdxWeb
Outer encryption: AES
Compressed: yes
Transform rounds: 600000
Inner encryption: Salsa20
Number of entries: 332

Although KeePassXC cannot open the database, MacPass (v0.7.9) and Strongbox (v1.11.0) both open it without issue. I can also open the kdbx file with KeeWeb on NextCloud.

## Debug Info
KeePassXC - Version 2.4.3
Revision: 5d6ef0c

Qt 5.12.3
Debugging mode is disabled.

Operating system: macOS High Sierra (10.13)
CPU architecture: x86_64
Kernel: darwin 17.7.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
 libgcrypt 1.8.4

**Comment by droidmonkey** [comment]
This indicates that a non-number was stored where a number was expected in the inner XML.

**Comment by wjjessen** [comment]
After testing, this happens every time a new record is created in the NextCloud app KeeWeb (v1.8.2), although it's not the new record that's the issue. I can open the kdbx file with MacPass and delete the new record, but KeePassXC will still not open the file and reports the same error (invalid number value).

**Comment by droidmonkey** [comment]
Are you capable of providing an example database that is broken by KeeWeb?

**Comment by adaugherity** [comment]
Is it possible to enable debug logging to see which entry has the problem?

I am experiencing the same issue, but am of course unable to share our KeePass database.  Creating a new database with KeeWeb and adding a simple entry did not trigger this bug.  I wonder if it might be some of the entries with tags, attached files, or additional fields, but those would be a stab in the dark without any guidance as to which entry is affected.

I tried launching `/Applications/KeePassXC.app/Contents/MacOS/KeePassXC --debug-info` but that just reports build info and does not perform any extra logging.

**Comment by droidmonkey** [comment]
You'll have to build your own keepassxc and run it through a debugger.
