### ISSUE TITLE
Email & Phone Number Field

### ISSUE THREAD

**Issue by trymeouteh** [keepassxreboot/keepassxc#3507]
Many websites now require not only just a username and a password but an email and even a phone number. I think it will be user friendly to add these fields without having to create them as custom attributes.

This should also be a request made for the KeePass app too.

**Comment by droidmonkey** [comment]
This is handled by templates which already has an open issue.

**Comment by droidmonkey** [comment]
This is handled by templates which already has an open issue for tracking.
