### ISSUE TITLE
Make KeePassXC-Browser check only domain in URL

### ISSUE THREAD

**Issue by Lantizia** [keepassxreboot/keepassxc#3509]
## Summary
As I understand it... KeePass **/** KeePassXC-Browser looks up the URL field in your entries to find any where it matches the *beginning* (and thus possibly the *whole*) of the full URL for the website you're currently browsing.

## Desired Behavior
Instead use some kind of RegEx to extract just the domain/hostname portion of an entries URL field and match on that instead of just matching from the beginning.

## Example of the problem
Let's say you're currently browsing this full URL in your browser...
https://secure.scottishwidows.co.uk/frame.wpl/839

You could...
a) Store that exact full URL, which'd also be handy for clicking in KeePassXC to open that page. 
b) Store just the beginning of 'https://secure.scottishwidows.co.uk' in the URL field, so KeePassXC-Browser can match this URL _even if_ the 'frame.wpl/83' part changes.

You might say a) is best... as there is a full match.  Sure but the number at the end of that URL *sometimes* changes when they edit the login UI a little (probably due to some odd CGI script), which will break KeePassXC-Browser's ability to match it.

You might say b) is best... betting that the shortened version probably redirects to the proper login page anyway - WRONG.  It doesn't :)  So you can't open the login page from KeePassXC any more.

## Example after desired behavior
If you store the full URL (like in option a) above) but only the bit in bold was matched...

https://**secure.scottishwidows.co.uk**/frame.wpl/839

Then you'd have the best of both worlds... a URL you can click in KeePassXC that works (unless the site changes the magic number at the end again) and also helps KeePassXC-Browser find the right credentials no matter if...
a) you used http:// or https://
b) the end part of the URL changed

## Conclusion

You'd be forgiven for thinking this is a fringe thing that is only applicable to this one site.  I've encountered this a number of times now with various sites and this was just the first one that came to mind to use as an example here.  

Most often it's the kind of sites which use some kind off sso.mydomain.com setup where they pass along some magic information to the single-sign-on service to say which site you're logging in to... and that magic information FIDGETS :P and changes over time in it's format/content... but the domain part remains consistent.

I'd be *tempted* (but I'm not) to go as far as to say... ignore subdomains... so login.domain.com / sso.domain.com / signin.domain.com / secure.domain.com - would all match for domain.com.  But that *would* be a massive pain as you've no idea what is a subdomain (without a full list of current top-level-domains)... and even then it'd wreck certain sites that live below other peoples domains.

But at least the main suggestion above means the minimum maintenance people need to do to have KeePassXC-Browser to continue to work... is to update their URL entries if the site changes the actual domain that the credentials are being taken on, and you don't need to bother if it's just the protocol that's changed or the filename/URI of the page asking.

## Addendum

It probably makes sense to have this behaviour be an optional setting which you can set on the KeePassXC application itself as an application-wide preference.

Mostly because I expect there will be some people who have one entry for http://mydomain.com/blog/login.php and another for https://mydomain.com/my-secure-account/login.php 

But I suspect a lot of people just put in http://mydomain.com and then have KeePassXC-Browser ask them which one they want (again, in case the login page for those services shuffle around on the site).  But that does then break having the ability to get to those login pages with a single click inside KeePassXC itself.

**Comment by droidmonkey** [comment]
Matching against either http or https is not going to happen. It is a security feature to enforce https matching if that is how the url is stored in the database.

**Comment by Lantizia** [comment]
Fair enough that had crossed my mind but from another angle... that it should be sensitive to ports.  So possibly match protocol + domain + port (if specified).  And since http and https are traditionally running on different ports it just adds to that.

**Comment by droidmonkey** [comment]
We already do this kind of matching you mention in this post. It just doesn't seem to be working in your case for some reason. This requires some careful debugging.

**Comment by droidmonkey** [comment]
OP reported that this functionality works. Closing for now, but there are some good points for consideration in his post.

**Comment by Lantizia** [comment]
>  but there are some good points for consideration in his post.

No there isn't!  (certainly not now I've edited them out of existence)
