### ISSUE TITLE
Make URL in Notes clickable

### ISSUE THREAD

**Issue by gyli** [keepassxreboot/keepassxc#3511]
## Summary
A feature in KeePass I used to use a lot is that I can click the URL in Notes and it would open the link in browser. 

## Desired Behavior
Parse the URL in Notes, make it openable

## Possible Solution
-

## Context
Sometimes I would like to store links in Notes if I have to store multiple URLs and this feature allows me to open the link quickly.

**Comment by droidmonkey** [comment]
Related to #1057

**Comment by Anubis-105** [comment]
Is it also possible to use links & referencing links in the notes as it is possible in KeePass?

Screenshot:
Hyperlink (URL) number [1] works.
Hyperlink (URL) number [2] does not work.

![KeePassXC-Notes-Clickable](https://user-images.githubusercontent.com/49913906/160554629-b0ddde8a-4cda-46a3-87bf-7a536909a280.png)

There are other articles about this:
https://github.com/keepassxreboot/keepassxc/issues/7093
https://github.com/keepassxreboot/keepassxc/issues/3511
https://github.com/keepassxreboot/keepassxc/issues/5369
https://github.com/keepassxreboot/keepassxc/issues/1057
