### ISSUE TITLE
Change the symbol for Add entry button 

### ISSUE THREAD

**Issue by markusd112** [keepassxreboot/keepassxc#3513]
[TIP]:  # ( Provide a general summary of the feature in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Summary
In the moment, the button in the horizontal toolbar for adding an entry is a key with an arrow. It would be more intuitive to see an icon containing a key and a plus symbol.

## Possible Solution
Change symbol to a key with a plus symbol

## Context
I have to guess which symbol is for what in the moment and I have a look into the hint that is appearing when moving the mouse onto the symbol without clicking

**Comment by markusd112** [comment]
![Bildschirmfoto 2019-09-07 um 14 15 55](https://user-images.githubusercontent.com/14372683/64474802-32341480-d17a-11e9-9941-65a7389c2619.png)

**Comment by droidmonkey** [comment]
This is covered by #475
