### ISSUE TITLE
Add mouseover help texts for the controls in the add key dialogue box

### ISSUE THREAD

**Issue by markusd112** [keepassxreboot/keepassxc#3514]
[TIP]:  # ( Provide a general summary of the feature in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Summary
The three buttons on the right side in the add password entry dialogue box has no mouse over help text to help the user for what the buttons. Please add some short textual hint when moving the mouse over without clicking the buttons 

## Desired Behavior
A short text appears when moving the mouse over the buttons explaining what the buttons are for.

## Possible Solution
Add mouse over text

## Context
When generating a cryptic password I have to search which button is for that functionality. I have to guess in the moment, because there is no explanaition

**Comment by droidmonkey** [comment]
Is this for the password generator? If so that has been added in 2.5.0

**Comment by markusd112** [comment]
No, I mean the dialogue box where you create a new entry in your keepass database. On the right side there are three buttons without a mouseover text:
![Bildschirmfoto 2019-09-07 um 14 06 32](https://user-images.githubusercontent.com/14372683/64474740-18de9880-d179-11e9-9e3b-474b9611c970.png)

**Comment by droidmonkey** [comment]
The tooltip for the last button was added in develop, but the other two are not. I will add those in.

![image](https://user-images.githubusercontent.com/2809491/64475243-38ac9700-d14e-11e9-8179-723094323fcc.png)
