### ISSUE TITLE
Inconsistent standard of saving browser integration settings on Windows and Linux

### ISSUE THREAD

**Issue by Toorero** [keepassxreboot/keepassxc#3517]
Every time I open a database that was previously opened on Linux and connected via the KeepassXC-Browser-Integration I get this message if I try to open it on Windows:
> KeePassXC: native browser integration settings found:
Your KeePassXC browser settings must be moved to the database settings. This is necessary to maintain your current browser connections. Would you like to migrate your existing settings now? 

### Current Behavior ###

On Linux the browser integration safes the browser-integration in a normal key.
On Windows, on the otherhand it's saved in the database settings.
That results in error messages if you open a database with native browser integration settings on Windows.

If i accept to migrate the settings the connection on Linux resets.
### Expected Behaviour ###

Both Linux and Windows browser-integration should use the same method to safe there settings, so there are no file conflicts between the both operation systems.

**Comment by droidmonkey** [comment]
You need to upgrade to 2.4.0 on both machines.
