### ISSUE TITLE
non-Latin input script not working

### ISSUE THREAD

**Issue by agharbeia** [keepassxreboot/keepassxc#352]
The AppImage doesn't detect the changing of the input language.

I cannot verify whether this is because it is a an AppImage is unable to detect installed keyboards and their status, or would also be present if installed as a system package, since 1) this is my first experience with an AppImage, and 2) I'm unable to install the DEB due to dependency mismatch:
`keepassxc depends on libqt5core5a (>= 5.3.0); however:
  Version of libqt5core5a:amd64 on system is 5.2.1+dfsg-1ubuntu14.3.
 keepassxc depends on libqt5gui5 (>= 5.3.0); however:
  Version of libqt5gui5:amd64 on system is 5.2.1+dfsg-1ubuntu14.3.`

## Expected Behaviour
Changing the keyboard input language to Arabic, either by the keyboard shortcut or the indicator icon should enable entering Arabic in the master key entry dialogue

## Current Behaviour
Even though the language indicator changes in the system's panel, Latin characters are typed in KeePassXC instead of Arabic. Typing elsewhere works as expected.

## Steps to Reproduce (for bugs)
1. Launch KeePassXC AppImage
2. open a KDBX file
3. In the password field of the master key dialogue switch the keyboard to Arabic 
4. Type in some Arabic text

## Your Environment
* KeePassXC: 2.1.2 (AppImage, using Qt 5.8.0 & libgcrypt 1.6.1)
* Qt version: 5.2.1(system's)
* Operating System and version: Ubuntu 14.04.5

**Comment by phoerious** [comment]
I would assume this is related to #272.
Does the new keyboard layout work when you restart KeePassXC?

**Comment by agharbeia** [comment]
It seems so, @phoerious. If I start with Ar as the keyboard layout before launching KeePassXC, then I'm able to only use Arabic keyboard, and not switch to English.
