### ISSUE TITLE
Copy Custom Attributes from entry context menu

### ISSUE THREAD

**Issue by E-Fail** [keepassxreboot/keepassxc#3521]
It would be nice to copy custom fields via context menu. Some Services need 3 Factor (bitbuckets Bucket key for example, so I need User, Pass and API Key). 

I think it can be look like this:

Copy attribute... > and here should be the list of my custom entries.

**Comment by Diadlo** [comment]
Maybe I misunderstand issue, but it looks like this feature is already exists

**Comment by droidmonkey** [comment]
Yes it does exist, does it work for you?

**Comment by Diadlo** [comment]
Yes
