### ISSUE TITLE
Use KeepassXC in web pages where the Username and Password are disjoined on two different pages

### ISSUE THREAD

**Issue by Piteur57** [keepassxreboot/keepassxc#3522]
Hello.

I use KeepassXC software (with Windows or Linux) with a lot of profit. I
would like to highlight a few wishes here:

- the fact that KeepassXC reacts badly when the username and password
are **on two different webpages** (I use Firefox and KeepassXC-browser),
which is more and more often the case, is annoying: unless I am
mistaken, the contextual menu does not provide for "pasting the only
username".

- at the same time, it would be good to provide a way to keep the
KeepassXC window in the foreground, even when the focus is not on it. This is certainly possible natively in LinuxOS, but **not in Windows** without an additional tool (which one, by the way?)!

Thank you.

Sincerely,

Piteur

**Comment by droidmonkey** [comment]
For number 1- we are addressing this on the extension side with a user interface upgrade. This will be released soon.

For number 2, take your pick: https://www.itechtics.com/10-tools-to-always-on-top-any-app-in-windows-10/

**Comment by Piteur57** [comment]
Thanks

**Comment by trupf** [comment]
When will this user interface upgrade be released? I still have the same issue.
