### ISSUE TITLE
ssh agent paths for multiple OSes

### ISSUE THREAD

**Issue by stratacast** [keepassxreboot/keepassxc#3523]
Is there some sort of equivalent to ~/ for paths to ssh keys in keepassxc? I tried using the standard tilde but it didn't properly load the path. Because of this issue, it seems I have to have a duplicate entry for both macOS and Linux/*BSD...is there something I'm missing that's not specified or does keepassxc not have a way to translate home directories, and the solution is to have duplicates for OS-specific paths? I'm using the 2.4.3 release on macOS 10.14, Kubuntu 18.04, and FreeBSD 12.0

**Comment by droidmonkey** [comment]
Probably need to use canonical path internally

**Comment by stratacast** [comment]
Is there a current workaround for this in the meantime that doesn't include duplicate entries for OSes with different absolute paths to the ~/.ssh directory?

**Comment by droidmonkey** [comment]
Nope
