### ISSUE TITLE
Password generator does not use symbols

### ISSUE THREAD

**Issue by Germano0** [keepassxreboot/keepassxc#3524]
I was registering to a website that requires symbols in the password, and I have noticed that the password generated by KeepassXC did not meet the requirement, so I clicked on "show password" in KeepassXC and I have noticed that the generated password did not have any symbol despite the option was on. I tried to regenerate the password and the problem was the same. To fix it I unchecked and checked again the option for symbols in password generator.
For information completeness, other enabled options were: `A-Z` `a-z` `0-9`

## Debug Info
KeePassXC - Version 2.4.3
Revision: 5d6ef0c

Qt 5.12.4
Debugging mode is disabled.

Operating system: Fedora 30 (Thirty)
CPU architecture: x86_64
Kernel: linux 5.2.9-200.fc30.x86_64

Enabled extensions:
- Auto-Type
- Integrazione con i browser
- Agente SSH
- KeeShare (only unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.4

**Comment by droidmonkey** [comment]
Please screenshot your exact settings.

**Comment by Germano0** [comment]
![kpxc](https://user-images.githubusercontent.com/5477747/64612134-5dfe0700-d3d3-11e9-8df7-a020ff2892c7.jpg)

**Comment by droidmonkey** [comment]
I cannot replicate this behavior. When I choose the symbols button the password immediately updates and contains a multitude of symbols.
