### ISSUE TITLE
Add Email Field

### ISSUE THREAD

**Issue by Lippoli** [keepassxreboot/keepassxc#3525]
[TIP]:  # ( Provide a general summary of the feature in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Summary
Additional Email Field

## Desired Behavior
Add and Email Field along the existing ones. 

## Possible Solution
[NOTE]: # ( Not required, but suggest ideas on how to implement the addition or change )

## Context
Besides Title, Username, etc, very often (almost always) when saving data for a website for example, an Email is required. Now I am saving it in a Notes field, but I have to specify that is a main email, because I need to store also other infos. sometimes other emails also.
The perfection could be to allow the customisation of additional fields...

**Comment by droidmonkey** [comment]
This is being tracked by the issue recommending templates.
