### ISSUE TITLE
Pressing ENTER in the search field opens the first hit

### ISSUE THREAD

**Issue by chevdor** [keepassxreboot/keepassxc#3530]
## Summary
Pressing ENTER in the search field opens the first hit which I don't find very user friendly.

## Desired Behavior
I have been using Keepass for years and I think that the default behavior is to search on enter or ignore the enter key. The implementation of KeepassXC is actually much better IMO (big Kudos to the team btw). My suggestion would be to NOT open the first entry on ENTER.

## Possible Solution
Do NOT open the first entry on ENTER. 
It may be a good option to not select an entry on a search, this way, pressing ENTER would likely do nothing.

There is no real reason to assume that the first entry in the list is THE one.

## Context
It is kinda automatic to press enter in a field. That is in that case rather inconvenient as you need to get out of the 'edit' mode to see the list of hits and pick the interesting one.

**Comment by t-m-w** [comment]
This issue is being discussed in https://github.com/keepassxreboot/keepassxc/issues/3443

(posting for the benefit of others; it took me a few minutes to find)
