### ISSUE TITLE
keepassxc.ini created but Keepassxc cannot access

### ISSUE THREAD

**Issue by fishmister11** [keepassxreboot/keepassxc#3531]
After installing everything works except when I want to change preferences.

I should be able to save preferences in the app.

When I try to edit the preferences I get this error:
Access error for config file /Users/chad.fisher/Library/Application Support/keepassxc/keepassxc.ini

I have verified that the file exists and that the permission on the path allow access to the file.
Not sure why it can't access the file.

## Steps to Reproduce
1. Install
2. Go to menu and Preferences
3. Pops the window for Preferences and displays all the options.  Not able to save anything because of the error listed above.

## Context
I can use KeePassXC but can tweak preferences

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.4.3
Revision: 5d6ef0c

Operating system: macOS Mojave
Version 10.14.6 (18G96)
CPU architecture: 2.9 GHz Intel Core i7

**Comment by droidmonkey** [comment]
You can try deleting the current ini file. Have you logged off and back on again to ensure no latent application is locking the file up?

**Comment by fishmister11** [comment]
> Could you confirm what `ls -la` shows for the file/dir?

![image](https://user-images.githubusercontent.com/55259828/64915800-f3c7c800-d72c-11e9-808d-a0fab30897a1.png)

**Comment by fishmister11** [comment]
> You can try deleting the current ini file. Have you logged off and back on again to ensure no latent application is locking the file up?

Deleted file closed down KeepassXC
still same error
![image](https://user-images.githubusercontent.com/55259828/64915830-810b1c80-d72d-11e9-8045-62460a12aa8b.png)

**Comment by droidmonkey** [comment]
are you running in a domain environment?

**Comment by fishmister11** [comment]
> are you running in a domain environment?
Meaning a company domain with AD integration?  Yes
I have full admin access when making changes though.

**Comment by droidmonkey** [comment]
Are you running KeePassXC with that same full admin access? Seems like it could be an issue. I am not an expert on MacOS enterprise behavior but this is certainly an untested area.

**Comment by emcniece** [comment]
Just fought through this. Our Macbooks are provisioned by remote admins, and I found that `~/Library/Application\ Support/keepassxc` was owned by `root` instead of my user.

Fixed via `chown [username]:staff ~/Library/Application\ Support/keepassxc`

**Comment by droidmonkey** [comment]
Makes sense, poor install process

**Comment by droidmonkey** [comment]
I am going to close this because this isn't something that KeePassXC is doing wrong.
