### ISSUE TITLE
Automatically open KeypassXC when needed by browser

### ISSUE THREAD

**Issue by dbolton** [keepassxreboot/keepassxc#3532]
## Summary
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
KeyPassXC-browser extension should automatically open KeePassXC and establish the necessary connection when needed (including prompting for a master password). This would be less confusing that the generic error message: "Cannot connect to KeePassXC." 

## Desired Behavior
[NOTE]: # ( Tell us how the new feature should work, be specific )
Ideally KeePassXC-browser would automatically open KeePassXC when needed, or at the very least give the user instructions on what to do. 

## Possible Solution
[NOTE]: # ( Not required, but suggest ideas on how to implement the addition or change )
_Ideal solution_: the KeePassXC-browser extension would automatically open the KeePassXC application when needed, and prompt the user to unlock the database when needed. 

_Alternative solution 1_: automatically start KeePassXC when you log in. That way it is probably open when the browser extension needs it. The disadvantage of this solution is the user might close KeePassXC at any point and we are back to the original problem. See https://github.com/keepassxreboot/keepassxc/issues/1218

_Alternative solution 2_: give an instructive message to the user such as "Make sure KeePassXC is open and signed in." Rather than just stating an error. Obviously this is the least ideal solution from the end-user perspective, but probably the easiest to implement. 

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
This feature is only useful to those who integrate KeePassXC with their browser to save and enter credentials on website. 

I'm using KeePassXC 2.4.3 on Windows 10 and KeePassXC-browser extension on Firefox 69.

**Comment by droidmonkey** [comment]
The issue with launching KeePassXC from the browser extension (really the proxy) is that the browser then owns the KeePassXC process. This means when the browser closes, so does KeePassXC. It also eliminates the benefit of the proxy being separated from the main application.

**Comment by droidmonkey** [comment]
With the new UX update pending for the extension, this is the message shown when KeePassXC is not running:

![image](https://user-images.githubusercontent.com/2809491/64901744-daf6de00-d66a-11e9-868e-7347e91cea76.png)

After KeePassXC is started, and reload pressed, this is what is shown:

![image](https://user-images.githubusercontent.com/2809491/64901758-f82bac80-d66a-11e9-9e9f-29b25f8df876.png)
