### ISSUE TITLE
Problems connecting to browser extensions

### ISSUE THREAD

**Issue by xzj8b3** [keepassxreboot/keepassxc#3533]
keepassxc-2.4.3-4.fc30.src.rpm

Excuse me, but why if I log in with two different browsers like Firefox and Chromium or TorBrowser does it keep me overwriting my login password instead of automatically detecting it in Fedora 30? I find this a bit annoying, can't we fix and improve the connection to browser extensions without these annoyances?

**Comment by droidmonkey** [comment]
Can you please rephrase your question, it does not make much sense. What is being overwritten? You have to connect each browser independently due to each one having it's own extension settings. Just use a different name for each browser to prevent overwriting.

**Comment by xzj8b3** [comment]
> Puoi per favore riformulare la tua domanda, non ha molto senso. Cosa viene sovrascritto? Devi connettere ogni browser in modo indipendente a causa del fatto che ognuno ha le proprie impostazioni di estensione. Basta usare un nome diverso per ciascun browser per evitare la sovrascrittura.

Thank you I will, yes sometimes translators are even worse than my poor English!!!!!
