### ISSUE TITLE
Ask for password after open keepassxc from tray icon

### ISSUE THREAD

**Issue by hokreb** [keepassxreboot/keepassxc#3534]
I like the option to hide app to tray icon very much. What I am missing, is a security option to ask for the password to unhide the app, but begin able to use the app while hidden as tray icon.  This way you can use the app hidden, but only if the acutal user knows the password, he can reopen the app for accessing all the passwords. It would give a certain add on level of security, if someone different than the main user get access to the computer for a short time (like for serviceing tasks or during a pair coding session where you have to leave the computer for a very short time), he can't get access to all the passwords.

**Comment by droidmonkey** [comment]
Just enable lock on minimize
