### ISSUE TITLE
Entering/pasting URL instead of local path into any Windows file dialog box freezes app

### ISSUE THREAD

**Issue by leonyu** [keepassxreboot/keepassxc#3535]
Entering/pasting URL instead of local path into any Windows file dialog box freezes app (unusable state)

* Open Database dialob
* Favicon dialog

## Expected Behavior
* Ideally, download the URL, use as file.

## Current Behavior
* App becomes unusable

## Possible Solution
* Block this behavior with an error so at least prevent app go into unusable state

## Steps to Reproduce
Favicon (more useful case):
* Open any entry
* Go to icon tab
* Click "Add custom icon"
* Type/paste an URL into the open dialog box
* Observe that browser opens up (close browser or do nothing)
* Return to KeePassXC, see that the app is no longer responding to user clicks
   * Database will still lock after certain time
* Must end-task to fix

Open database: 
* Database -> Open
* Type/paste an URL into the open dialog box
* Observe that something happen
* Return to KeePassXC, see that the app is no longer responding to user clicks
* Must end-task to fix

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )

## Debug Info
KeePassXC - Version 2.4.3
Revision: 5d6ef0c

Qt 5.12.3
Debugging mode is disabled.

Operating system: Windows 10 (10.0)
CPU architecture: x86_64
Kernel: winnt 10.0.18362

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.4

**Comment by jorgheymans** [comment]
+1 it would be useful if i keepassxc could open a database just by URL e.g. https://my.server/pass.kdbx . Such setup would be read-only ofcourse, no updates to the database would be possible.
