### ISSUE TITLE
Cannot access any new database on Windows 10 once created ("Invalid credentials were provided")

### ISSUE THREAD

**Issue by ImaticCS** [keepassxreboot/keepassxc#3536]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
After creating a database, the application should let me view the database when attempting to open it after entering the correct master key.

## Current Behavior
[NOTE]: # ( Tell us what actually happens )
After creating a database, closing it, attempting to open it and inputting the correct master key, I cannot view the database. Instead, I get this message: 

Error while reading the database: Invalid credentials were provided, please try again.
If this reoccurs, then your database file may be corrupt. (HMAC mismatch)

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1. Create new database using the official Windows application from the website with the default settings and the password test
2. Close database
3. Attempt to open the database with the same password used to create it (in this case, test)

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )
I literally can't use the application as a password manager, because it doesn't work. It doesn't matter what password I use when I create a new database, it simply won't let me back in once I've closed it.

I thought I may have simply gotten unlucky with the first database I let the application create, or maybe I did forget the password. So I did it again, this time writing down the password and making sure it was visible when I entered it in the creation process. The same thing happened.

Then I decided to create ANOTHER one with the password test, and I still have the same issue.

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.4.3
Revision: 5d6ef0c

Libraries:
Cryptographic libraries:
 libgcrypt 1.8.4

Operating system: Windows 10 (10.0)
CPU architecture: x86_64
Kernel: winnt 10.0.18362

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

**Comment by droidmonkey** [comment]
Make sure all checkboxes are unchecked except the password one.

**Comment by ImaticCS** [comment]
> 
> 
> Make sure all checkboxes are unchecked except the password one. This is on the unlock dialog.

Well, now I feel silly. I did what you said and it works now with no issues. Thank you for your help and sorry for the inconvenience. That being said, I think it would be beneficial to let people know somewhere in the application when you first open it about the checkboxes in case they run into the same problem as me. I just assumed you had to tick the boxes if you were using the fields next to them.

**Comment by droidmonkey** [comment]
The checkboxes are eliminated in the next release.
