### ISSUE TITLE
Search Help: does not state that field names can be abbreviated

### ISSUE THREAD

**Issue by tomhundt** [keepassxreboot/keepassxc#3537]
The search help doesn't state (but does imply, by example) that field names can be abbreviated to least-unique size.  The example given is for "username", abbreviated to "user".

[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Expected Behavior
Add a statement to this effect.  Assuming it is true :-)

Presumably, "username" could be shortened even to just "us".

Maybe give some different examples with, say, a full-length usage, and then with an extreme shortening: _title:_ shortened to _t:_ or _notes:_ shortened to _n:_

This is a great feature btw ;-)

## Debug Info
KeePassXC - Version 2.4.3
Revision: 5d6ef0c

Qt 5.12.3
Debugging mode is disabled.

Operating system: macOS Mojave (10.14)
CPU architecture: x86_64
Kernel: darwin 18.7.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
 libgcrypt 1.8.4

**Comment by droidmonkey** [comment]
This was fixed already in develop branch
