### ISSUE TITLE
Search: clicking Search icon ignores clicks except rightmost 1/3 of it

### ISSUE THREAD

**Issue by tomhundt** [keepassxreboot/keepassxc#3538]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
**Clicking the Search icon** (at the left end of the Search field -- on my Mac it is binoculars on top of a gear) is supposed to drop down a small menu, including options _Case sensitive_ and _Limit search to selected group_.  But: it **ignores clicks except for on the rightmost third** (or so) of the icon.  This may be platform specific (I'm on Mac, v3.4.3, see Debug Info below).

Here's what this look like:
![search menu](https://user-images.githubusercontent.com/12475662/64915503-24a00100-d71d-11e9-8acc-1b9bfadf811d.png)

I'm having a hard time capturing the mouse pointer, so here's a picture of it with the approximate "sensitive" area outlined (it's supposed to be the _entire_ icon):
![icon](https://user-images.githubusercontent.com/12475662/64915518-bd368100-d71d-11e9-88b5-115b9f7c1bab.png)

## Debug Info
KeePassXC - Version 2.4.3
Revision: 5d6ef0c

Qt 5.12.3
Debugging mode is disabled.

Operating system: macOS Mojave (10.14)
CPU architecture: x86_64
Kernel: darwin 18.7.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
 libgcrypt 1.8.4

**Comment by droidmonkey** [comment]
This is a bug in Qt, it should be showing the arrow target
