### ISSUE TITLE
Remove the "Create a new database" button

### ISSUE THREAD

**Issue by lindhe** [keepassxreboot/keepassxc#3539]
[TIP]:  # ( Provide a general summary of the feature in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Summary
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
I suggest removing the button "Create a new database" from the icon tray, since I don't think it's used very frequently.

![Screenshot from 2019-09-15 14-18-38](https://user-images.githubusercontent.com/7773090/64921713-d9dac380-d7c6-11e9-8f6d-52a3fd2f9760.png)

## Desired Behavior
[NOTE]: # ( Tell us how the new feature should work, be specific )
Creation of a new database should be available through the Database menu option, but not via the icon tray.

## Possible Addition
I would argue that creating a new database is an infrequent action when a database is already open. However, when no database is open it might make sense to display to big nice buttons at the centre of the screen; one for "Create a new database" and one for "Open a database".

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
I think the icon tray should hold the most frequently used buttons, and I do not see why "Create a new database" would be frequently used. It is important, but not the first choice during everyday use.

I frequently get it confused for the button for "Add a new entry", since both has something to do with creating new stuff. I often add new passwords to my database, but rarely create new databases.

**Comment by droidmonkey** [comment]
This has been debated before and we decided to change the keyboard shortcut for a new entry to Ctrl+N and a new database to Ctrl+Shift+N. I do not agree with removing the icon, it fits in with new/open/save.

**Comment by lindhe** [comment]
I'm glad to hear. Sorry if I missed some existing issue, I made a handful of searches before posting.

Yes, it does fit it. But I don't think that fitting in is a strong argument. I can come up with other options that fits in too (e.g., save as, close database, import, merge) but I think they are not used very often so it's good to not have them in the quick access menu.

**Comment by droidmonkey** [comment]
See #289, #513, and #515

**Comment by rnc** [comment]
As many people have differing opinions on what should or shouldn't be visible would another option be to allow the toolbar to be customised (like firefox does) so people can add/remove buttons to it. That way, a sensible set of defaults can be shipped but for certain users they can modify it as they so desire ?

**Comment by droidmonkey** [comment]
Closed in 84e3925e7b9a3b660227df7d62a04b2c44efce5c
