### ISSUE TITLE
Auto-type disabled when building from sources

### ISSUE THREAD

**Issue by anatoli26** [keepassxreboot/keepassxc#354]
Cmake shows:
```
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test WERROR_C_AVAILABLE
-- Performing Test WERROR_C_AVAILABLE - Success
-- Performing Test WERROR_CXX_AVAILABLE
-- Performing Test WERROR_CXX_AVAILABLE - Success
-- Found LibGPGError: /usr/lib/x86_64-linux-gnu/libgpg-error.so  
-- Found Gcrypt: /usr/lib/x86_64-linux-gnu/libgcrypt.so (Required is at least version "1.6.0") 
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.8") 
-- Performing Test ZLIB_SUPPORTS_GZIP
-- Performing Test ZLIB_SUPPORTS_GZIP - Success
-- Performing Test HAVE_PR_SET_DUMPABLE
-- Performing Test HAVE_PR_SET_DUMPABLE - Success
-- Performing Test HAVE_RLIMIT_CORE
-- Performing Test HAVE_RLIMIT_CORE - Success
-- <multiple *.ts files>
-- Enabled features:

-- Disabled features:
* KeePassHTTP , KeePassHTTP support for ChromeIPass and PassIFox
* Autotype , Auto-type passwords in Input fields
```
It is invoked with: `cmake ..`

`libxi`, `libxtst` and `libqt5x11extras5` are all installed (dev and lib), all other packages as described at https://github.com/keepassxreboot/keepassxc/wiki/Set-up-Build-Environment-on-Linux are also installed (except the YubiKey ones).

## Environment
* KeePassXC version/commit used: 2.1.2 tag (b9279f7)
* Qt version (e.g. Qt 5.3): QMake version 3.0 / Qt version 5.5.1
* Compiler (e.g. Clang++3.6.0): gcc 5.4.0
* Operating System and version: Ubuntu 16.04

**Comment by anatoli26** [comment]
OK, found the problem with more digging.. cmake should be invoked this way: `cmake -DWITH_XC_AUTOTYPE=ON ..`

Why this option is not ON by default and this is not documented anywhere?

**Comment by phoerious** [comment]
It is documented. Have a look at our wiki. https://github.com/keepassxreboot/keepassxc/wiki/Building-KeePassXC

We may enable the feature by default in the future.

**Comment by anatoli26** [comment]
I had, this document https://github.com/keepassxreboot/keepassxc/wiki/Install-Instruction-from-Source doesn't mention it, the INSTALL.md in the root of the repo (https://github.com/keepassxreboot/keepassxc/blob/develop/INSTALL.md) also have not a single mention.

The one you provide does mention it, but just as an example without explaining its meaning.

Who would want to build KPRC without auto-type? Definitely not a typical user. IMO this option should be ON by default and/or clearly explained in the INSTALL.md and related docs.

**Comment by phoerious** [comment]
I think it's pretty clear what -DWITH_XC_AUTOTYPE=ON does, so it doesn't need any explanation. The only thing that may be confusing is why you need to explicitly specify it. But as I said, we may change that.

**Comment by TheZ3ro** [comment]
@anatoli26 

> I had, this document https://github.com/keepassxreboot/keepassxc/wiki/Install-Instruction-from-Source doesn't mention it

This document mention it and describe it clearly under the [Building extension](https://github.com/keepassxreboot/keepassxc/wiki/Install-Instruction-from-Source#building-extension) section

**Comment by anatoli26** [comment]
You're right, haven't seen it. Hope you'll turn it ON by default, as Janek said, to avoid confusion.

By the way, the app is better and better with every release. Great job, guys!
