### ISSUE TITLE
Include TOTP settings in CSV export 

### ISSUE THREAD

**Issue by lonelymaw** [keepassxreboot/keepassxc#3541]
[TIP]:  # ( Provide a general summary of the feature in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Summary
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
Currently, exporting a database as a .csv as far as I can tell only includes the bare information fields, i.e., Group, Title, Username, Password, URL, and Notes.

## Desired Behavior
[NOTE]: # ( Tell us how the new feature should work, be specific )
Expected behavior would be for other important fields, such as AutoType window associations, to be included, such that re-importing the .csv into KeePassXC would yield an exact copy of the original.

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
There have been times I've needed to edit a field currently not editable in KeePassXC -- creation or access dates, for example -- and have needed to export them as a .csv file, edit them, then re-import them to do so. Current behavior then requires me to re-enter any window association information for AutoType, which can be tedious and time-consuming.

**Comment by louib** [comment]
Yeah that would be nice to have, especially when we'll be able to import and export from the CLI (https://github.com/keepassxreboot/keepassxc/pull/3278 is still a work in progress).

**Comment by droidmonkey** [comment]
The problem is you get unbounded results which do not play well with csv. Sure we could encode the information (base64 for example) but that really isn't the point of csv export. It is not intended for you to edit the time and reimport. Its meant to cross over to another password manager (no data lock) that most likely doesn't support these features anyway, and certainly wouldn't understand the import of that information.

**Comment by louib** [comment]
But we have that problem already, no? There could be commas in the password or in the notes already. At that point we could export everything there is for an entry and let the users decide what fields they want to use.

**Comment by droidmonkey** [comment]
Any reserved keywords are escaped per csv convention. The problem isn't commas, it's multi-dimensional data. You either create a new column for each Auto-Type entry, only export 1 or 2, or whatever. Its not a trivial problem.

**Comment by louib** [comment]
I guess we could at least export "standard" fields like uuid, modification and access dates. Expiration date and TOTP attributes could make sense too.

**Comment by droidmonkey** [comment]
Yes agree we should at least export the Created and Modified times. TOTP settings is also good. Anything that can be imported by CSV should be exported to CSV.

**Comment by llucax** [comment]
I think it is important to have a text format that can be used to export the DB without loss of information. although I agree CVS might not be the best choice. I think keepass2 uses an XML file for that. Right not there seems to be some wrong date in my database and I can't find a way to "debug" this problem, as the only export option I have doesn't include the dates, so I have no way to easily search the DB for potential problems.

As a side note, it seems I'm not the only one experiencing this issue, which makes the DB unreadable for the Android App [keepass2android](https://github.com/PhilippC/keepass2android). See https://github.com/PhilippC/keepass2android/issues/868. But this is probably for a different issue.

**Comment by droidmonkey** [comment]
You can use the cli tool to export to xml

**Comment by llucax** [comment]
Oh, cool, thanks! I didn't know that. I finally identified the problem. I recently migrated all my passwords from Firefox to keepass and the Firefox password export tool ([FF Password Exporter](https://github.com/kspearrin/ff-password-exporter)) uses a weird *unix* timestamp to represent dates. It adds 3 more digits at the end, I assume representing sub-second time. These were then interpreted as regular unix timestamps by the keepassxc importer and thus making the dates in a very distant future. I just wrote a small script to remove those extra 3 digits from the timestamps and re-imported and that made my issue go away.

**Comment by pmajkutewicz** [comment]
A lot of sites have 2FA now.
Exporting TOTP config is like "must-have" in my opinion.

If I do export-import now I won't be able to login to the site with 2FA enabled.

**Comment by friend18** [comment]
I realize that this is a complex problem, whose complete (and satisfying) resolution may be a long-ish time coming.
In the meantime, though, please revise the cautionary message (issued when first exporting a database into a CSV file) to include something to the effect of "_**not all information in the database will be written into the CSV file**_" (and make that text in Italics/Bold).  Possible further refinement could enumerate either what *is* written, or what is *not* written (or even issue the additional diagnostic iff there would be information loss) -- but what I'm suggesting would clarify that writing/reading-back a CSV file ***loses information***.  I'm speaking as someone who was just burned by this now-discovered fact.

**Comment by droidmonkey** [comment]
I got a fix ready for 2.6.2

**Comment by pmajkutewicz** [comment]
@droidmonkey Now I'm lost.
I was waiting for this release long time. Now I have 2.6.2 (AppImage) and I did export to csv.
Following columns are exported
`"Group","Title","Username","Password","URL","Notes"`

So... where is TOTP? Do I have to change settings?

**Comment by droidmonkey** [comment]
Oh no! That commit was merged to develop and not the 2.6.2 release branch

**Comment by pmajkutewicz** [comment]
Oh... now i see. Works like a charm. Thank You!
