### ISSUE TITLE
KeepassXC stopped working after Windows 10 update

### ISSUE THREAD

**Issue by NdranC** [keepassxreboot/keepassxc#3542]
After my Windows 10 updated this last friday to the latest cumulative updates (including .NET Framework and Adobe Flash Player) KeepassXC just stopped rendering the UI at all and it just closes while the program remains in the taskbar.

## Expected Behavior
When I click the taskbar icon or try to use my previously established auto-type keybind I expect the program to open into it's own window like usual and allow me to type my master password and allow me to browse the database.

## Current Behavior
When I launch the program it will launch "seemingly" correctly into the taskbar but any attempts to get the UI window to show up through ether "Toggle window" or click or using my auto-type keybind will result in nothing happening or the program showing up in the window toolbar with a missing icon and unable to open the UI. I can only preview the window and it looks all blank.
![keepass bug](https://user-images.githubusercontent.com/27837113/64957374-d09b3680-d85a-11e9-8c33-cf0bdd7bdc96.jpg) Hopefully the screenshot will provide a better visual aid.

## Possible Solution
I'm not entirely sure what caused this. From my point of view the only meaningful thing that happened between the last time it worked and the first time I noticed this problem was my windows OS asking me to reboot because of some resent Security updates for Adobe Flash Player, cumulative update to .NET Framework and some other windows 10 updates.

I've tried repairing my install, I've deleted the program and reinstalled it. I've tried using the portable version. I've tried downloading the latest beta branch (2.5 I believe) and it still present the same problem.

## Steps to Reproduce
This behavior only happens on my computer and it doesn't seem to happen on my other windows computers.

## Debug Info
KeePassXC - 2.4.3 (both install and portable) 2.5 (portable)

Libraries:
- LIBS

Operating system: Windows 10
CPU architecture: Intel i5-6600K

Enabled extensions:
None

**Comment by droidmonkey** [comment]
That is very strange. I haven't experienced this on Windows 10 (yet) and don't know where to start helping you since you already tried our other avenues of application delivery. My best guess is your graphics driver is causing heartburn with Qt. Can you try another Qt application like Zeal?

**Comment by NdranC** [comment]
I downloaded the portable version of Zeal and it seems to work. I can see the UI so I would imagine that Qt is working.

I'm not entirely if it was my windows update but I can't think of anything else that happened in the last 24 hours before I encountered the problem. I guess I'm going to try uninstalling the sep 14th updates and see if that fixes anything. I hope windows 10 can handle update uninstalling in a sensible way.

**Comment by NdranC** [comment]
As expected from Windows 10, I seem to be unable to truly uninstall everything that got installed on the last update. As soon as I reboot to apply the changes Windows proceeds to install the same updates immediately upon booting. Maybe I'm doing something wrong I guess.

Regardless, it's possible the updates has nothing to do with it. Is there anything I can do to provide better feedback? Some logs somewhere maybe?

KeepassXC is an important part of my daily routine and these last couple days have been uncomfortable to say the least. I guess I could just say screw it and format my computer but that could potentially not fix my problem and/or prevent whatever the bug might be from being fixed for someone else.

**Comment by droidmonkey** [comment]
Some similar examples:

https://www.qtcentre.org/threads/69399-Qt-application-is-completely-white
https://community.atlassian.com/t5/Hipchat-questions/Windows-Desktop-App-only-shows-a-blank-white-window/qaq-p/277535

For the second link see the response from Bernd for a possible fix. You can also try reinstalling OpenGL. I am not sure if this is even the issue since we don't use OpenGL, but it seems to be the common thread among my google searching.

**Comment by mogwa1** [comment]
I seem to have run into the same problem when I booted my work laptop this morning.
I haven't run into the same problem with the home computers so far.  
The biggest problem is that I don't have permissions to reinstall graphics drivers on the work laptop, so I can't check whether that might solve the problem.

**Comment by mogwa1** [comment]
After some experimenting I got the GUI back.  
I think that I fixed it by adding a new rule for keepassxc in "Graphics Settings".  Just add the executable to the Graphics Settings table, and then set it to "High Performance".
I suspect that the default setting does not allow the program to use accelerated graphics?

However, I'm not 100% sure that that is what fixed it or whether the fix will be permanent.  Only time will tell.

**Comment by NdranC** [comment]
Hmmm, well so far I've reinstalled the graphic driver and tried to create a game profile for KeepassXC in Radeon Settings then changed as many settings as I could, including setting anything related to High Performance or the equivalent and it doesn't seem to work.

The only thing that I haven't tried is reinstalling opengl but I'm not sure how to go about doing that. I though opengl was part of the graphic driver you install for your video card. I'll see if I can find some time to research this problem today.

Thanks for your suggestion @mogwa1

**Comment by NdranC** [comment]
After trying a variety of vague things I was unable to get my keepassXC working again. I opted to just format my windows box and so far it seems to be working just like before. Not sure what happened.

**Comment by droidmonkey** [comment]
That is very strange, glad it works again. I'm closing since this wasn't something on our end.
