### ISSUE TITLE
Menus only appear when on one monitor (X11, i3; multi-monitor)

### ISSUE THREAD

**Issue by nmschulte** [keepassxreboot/keepassxc#3543]
## Expected Behavior
Clicking to open a menu displays the menu, regardless of which monitor "owns" the (parent) window.

## Current Behavior
Clicking to open a menu has no effect unless the (parent) window is on a particular monitor.  The menu button appears activated, but the menu only displays when on a particular monitor.

![2019_09_16-07_31_38-500x419](https://user-images.githubusercontent.com/8540239/64958181-1c96ad00-d854-11e9-8339-bc8aa45d3410.png)
Note I see the issue with other monitor setups as well.

This issue has existed for me for quite a while.

## Possible Solution
I'm guessing this is a bug in Qt, as I believe I've seen it in another application before.  I see it in KeepassXC daily, however.

## Context
All menus, including top-level, menus when editing entries, etc.

## Debug Info
Debian Buster/Sid, Linux 5.2.0-2-amd64
KeepassXC v2.4.3 (Version: 2.4.3+dfsg.1-1, Sep 06)

**Comment by droidmonkey** [comment]
This is a Qt bug and has been reported to them.

**Comment by nmschulte** [comment]
@droidmonkey thanks, I found that bug as well but the description was a bit different.  Do you have any suggested workaround?  Is there a way to make KeepassXC always show on a particular monitor / x/y location or so?

**Comment by droidmonkey** [comment]
I don't have any further information unfortunately.
