### ISSUE TITLE
Browser integration for `firefox` cannot be enabled unless using `root`

### ISSUE THREAD

**Issue by sarpik** [keepassxreboot/keepassxc#3544]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
KeepassXC > Settings > Browser integration:
Once `Enable KeepassXC browser integration` is enabled, I expect to be able to `Enable integration for these browsers:` `Firefox`.

## Current Behavior
[NOTE]: # ( Tell us what actually happens )

I wanted to enable integration for `Firefox`, but it failed:

```error
cannot save the native messaging script file
```

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )

It was strange, so I tried the same procedure, but instead I opened the database as `root`.
Everything worked fine then! So I went into `/root/.mozilla/` and compared it to mine. My user account was missing the folder `native-messaging-hosts`, so I copied it over:

```sh
[root] $ cp ~/.mozilla/native-messaging-hosts /home/kipras/.mozilla/
```

and restarted `keepassxc`:

```sh
$ killall keepassxc
$ keepassxc
```

Boom - everything works fine now, without using `root`.

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )

See "Current behavior"

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )
I've tried to use this together with the `KeePassXC-Browser` extension, paired up with `Firefox` (specifically, `firefox-developer-edition`). Obviously, without enabling integration for firefox, you cannot use it in the firefox browser.

I'd like to suggest adding a more helpful & user-friendly error message in the `KeepassXC-Browser` extension, because the current one just said that it *failed to connect*.

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.4.3
Revision: 5d6ef0c

Qt 5.13.1
Debugging mode is disabled.

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 5.2.14-arch2-1-ARCH

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.5

**Comment by phoerious** [comment]
This is almost certainly due to wrong permissions on your .mozilla folder and not a KeePassXC issue.

**Comment by sarpik** [comment]
@phoerious 	whoops, I checked - it's owned by root because I installed it using [LARBS](https://larbs.xyz)

I'll inform the creator; this can be closed.
