### ISSUE TITLE
Clipboard clearing not working in KDE Archlinux

### ISSUE THREAD

**Issue by quantenProjects** [keepassxreboot/keepassxc#3545]
## Expected Behavior
The Clipboard is cleared after the configured time

## Current Behavior
the clipboard still contains the password

## Possible Solution
???

## Steps to Reproduce
1. Set Clear clipboard after 10 sec
2. Copy Password/Username with Contextmenu / Ctrl+C/B
3. Wait 10 sec
4. Press Ctrl+V in another Application

## Context
The password is not showing up in the KDE Clipboard history, as #3008 suggests. But it is still pasteable

I am using plasma-workspace 5.16.5-1

## Debug Info
KeePassXC - Version 2.4.3
Revision: 5d6ef0c

Qt 5.13.1
Debugging mode is disabled.

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 5.2.14-arch2-1-ARCH

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.5

**Comment by phoerious** [comment]
You need to turn off "Prevent empty clipboard".
There is a special flag we can set to tell Klipper not to retain the password, but it may not get be implemented in your KDE version.

**Comment by quantenProjects** [comment]
Thanks a lot, that helped. 

Is it documented or mentioned in the FAQ?
