### ISSUE TITLE
remember last used group

### ISSUE THREAD

**Issue by paulsaivetz** [keepassxreboot/keepassxc#3547]
have keepassxc remember the last used group, eg Internet, so when you relaunch keepassxc you are already on that group.

i have been a keepassx user for many years and it remembers the last used group.  this is nice to have as it saves a mouse click when opening keepass.

**Comment by droidmonkey** [comment]
We decided not to support this behavior.

**Comment by spartanicus** [comment]
Is it possible to give this further consideration? I really like keypassxc, but as a long keepassx user, I too find it frustrating to lose my last open group when the window locks. It's the only thing I find frustrating - all else I really like.

**Comment by droidmonkey** [comment]
Last used group and entry are remembered when the database locks, but not when the application is closed.
