### ISSUE TITLE
browserplugin password selection workflow

### ISSUE THREAD

**Issue by wommel** [keepassxreboot/keepassxc#3548]
the communication between or espacialy keepassxcs reaction to the browser plugin seems somewhat inconsistent if not buggy.

## Expected Behavior
When i press the fill username + password shortcut i'd expect:
1. the browser plugin tells keepassxc somthing like "hey, i need username and password for $url"
2. keepassxc looks the url up and if it finds any entrys opens a popup asking which one to provide to the browser
3. now the user can select one or completly reject the request
4. then keepassxc tells the browser the selected credentials (and only the selected) or an error like "no entrys found" or "request rejcted"
5. the plugin fills the login fields with the provided credentials (and if configured autosubmits)

## Current Behavior
on pressing the shortcut i currently get a somewhat random behaviour:
- if only one entry found it gets autofilled without further confirmation
- if only one entry found i get a popup from keepassxc asking if its ok to use the entry
- if multiple entrys found i get a dropdown to select which one to use
- if multiple entrys found i get a popup from keepassxc which one to use. if i deny the popup opens again, once for evry matchingentry. if i allow access, no matter which one i select (luckily no further popups on allow), all are provided to the browser and i have to select again via dropdown.

## Possible Solution
- i don't know what causes the sometimes-popup behaviour but some clarification and a keepassxc option to enforce it woud be nice.
- triggering multiple popups if multiple matches found is a simple bug
- allowing one entry should only provide this one entry to the browser (actualy the browser should not even know how many entrys match)

## Steps to Reproduce
have multiple logins in one (or many, no difference) database for the same site.

## Context
multiple logins on the same site. i'm using the browser plugin in chromium.

## Debug Info
KeePassXC - Version 2.4.3
Revision: 5d6ef0c

Qt 5.13.1
Debugging mode is disabled.

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 5.2.14.a-1-hardened

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.5

**Comment by droidmonkey** [comment]
There is nothing wrong with the workflow, the problem is the user interface is confusing. This is being addressed through https://github.com/keepassxreboot/keepassxc-browser/pull/351
