### ISSUE TITLE
Exporting database to CSV non-english characters messy

### ISSUE THREAD

**Issue by yuyujulin** [keepassxreboot/keepassxc#3549]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Expected Behavior

Non-English such as Chinses characters   looks good while exporting to csv

## Current Behavior

Non-English such as Chinses characters  looks messy while exporting to csv

![111](https://user-images.githubusercontent.com/4941575/65102250-07a94d80-d9fd-11e9-99fd-282ecb7dd705.jpg)

## Steps to Reproduce

1.  add an entry
2. enter some Chinese characters for title or other fields.
3. export database as csv file

## Context

the exported csv is not readable for me

## Debug Info

KeePassXC - Version 2.4.3
Revision: 5d6ef0c

Qt 5.12.3
Debugging mode is disabled.

Operating system: Windows 10 (10.0)
CPU architecture: x86_64
Kernel: winnt 10.0.17134

Enabled extensions:
- Auto-Type
- 浏览器配合
- SSH 代理
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.4

**Comment by droidmonkey** [comment]
This is probably an encoding issue

**Comment by phoerious** [comment]
Your screenshot looks a little messy, but not like something is fundamentally wrong. Can you rule out encoding bugs during the Libreoffice import? Make sure you select utf-8 as the encoding.

**Comment by gyli** [comment]
It is an encoding issue indeed. But I think it's more like an Excel's issue.
KeePassXC generates the csv file in UTF8 without BOM, while it's just not readable in Excel, at least on my Excel Mac. If I open the file in Sublime Text and save it with BOM, the file turn to be openable in Excel.
Adding an option in KeePassXC to choose exporting CSV file with or without BOM might solve this issue.

**Comment by droidmonkey** [comment]
It's pretty silly that Excel uses (and requires) a BOM on UTF-8

**Comment by yuyujulin** [comment]
> It is an encoding issue indeed. But I think it's more like an Excel's issue.
> 
> KeePassXC generates the csv file in UTF8 without BOM, while it causes Excel reading Unicode characters wrongly. If I open the file in Sublime Text and save it with BOM, the file would be open and parsed correctly in Excel.
> 
> Adding an option in KeePassXC to choose exporting CSV file with or without BOM might solve this issue.
> 
> An easier solution for now, for @yuyujulin, is opening the file with text editor instead of Excel.

Geneiues!  Indeed, when I open it with a text editor, everything works well. Anyway, like you said, add an option to choose exporting CSV file with/without BOM to solve this issue. It there any chance to do that? @droidmonkey
