### ISSUE TITLE
Add .desktop and .appdata.xml strings to translations on Transifex

### ISSUE THREAD

**Issue by scootergrisen** [keepassxreboot/keepassxc#3554]
I suggest adding the strings from org.keepassxc.KeePassXC.desktop to the same place where the rest of the translation is being made (Transifex) so that translators will not miss it.

Currently GenericName is only translated to 4 languages and Comment to 0 languages.

Perhaps also add the strings from org.keepassxc.KeePassXC.appdata.xml but exclude the `<releases>` part.

Files are at https://github.com/keepassxreboot/keepassxc/tree/develop/share/linux

**Comment by droidmonkey** [comment]
The problem is the way the file handles the translation. It cannot be imported into Transifex and forces a manual translation.

**Comment by scootergrisen** [comment]
I dont know how it can be done in keepassxc but for other projects i see e.g. they have a po file where the strings for the .desktop is added and then the lines in the .desktop file that need translation have a "_" in front.

For Deepin on Transifex i see they have a ressource like deepin-editor-desktop-ts with just 3 strings for the .desktop file for that program. So it sounds like they figured out some way to do it.
Maybe its a ts file on Transifex and then they convert/extract the strings from that format and use it in another way.

If nothing like this is done i would at least suggest to meantion other things that needs translations on https://github.com/keepassxreboot/keepassxc/blob/develop/.github/CONTRIBUTING.md#translations and not just the strings on Transifex so that people can translate it more fully.

**Comment by droidmonkey** [comment]
We will handle this through PR's at this time.
