### ISSUE TITLE
Using Appimage and Firejail - cannot open kdbx

### ISSUE THREAD

**Issue by keymaster312** [keepassxreboot/keepassxc#3555]
OK, so I am using Lubuntu 18.04.3 LTS, Firejail and KeePassXC-2.4.3-x86_64.AppImage

Not sure if this is an issue with Firejail, expected behavior or....? If I run Firejail with the AppImage on the desktop, and create a new database with a password. Save it to home/user folder. Close all programs. Reopen Appimage in Firejail and try and open the database, it won't open. The Firejail terminal shows: 
```
inotify_add_watch("/home/user/Desktop/Passwords.kdbx")` failed: "Permission `denied"
libudev:` udev_monitor_new_from_netlink_fd: error getting socket: Operation not supported
```
Should I be encountering this kind of permissions issue? If I move the database to the desktop, close everything, restart and then try again to reopen it works.

**Comment by droidmonkey** [comment]
You need to setup your firejail directory permissions correctly. When we open a file we watch it for external changes so they can be merged into your open database.

**Comment by seisdr** [comment]
libudev: udev_monitor_new_from_netlink_fd: error getting socket: Permission denied
