### ISSUE TITLE
keepassxc blocks session logout if minimize on close is enabled

### ISSUE THREAD

**Issue by jpalus** [keepassxreboot/keepassxc#3556]
Steps to reproduce on Linux desktop:
1. Enable "Minimize instead of app exit"
2. Leave keepassxc window open
3. Try to logout

Expected: session ends and user is logged out
Actual: keepassxc window closes but session is left running

It appears that keepassxc does not distinguish between window close initiated by user and window close initiated by session manager. I did some checking, though I have no experience with Qt, and it seems like solution might be to override https://doc.qt.io/qt-5/qguiapplication.html#commitDataRequest that would set MainWindow::m_appExitCalled

**Comment by droidmonkey** [comment]
This is a duplicate issue

**Comment by andersk** [comment]
Google sent me here, so for posterity, see

* #3944
