### ISSUE TITLE
Can't connect firefox and desktop application

### ISSUE THREAD

**Issue by c269574** [keepassxreboot/keepassxc#3557]
should i click Connect?
![изображение](https://user-images.githubusercontent.com/40603957/65228765-bd46d000-dad3-11e9-85e3-a65e266a85d8.png)
 nothing changes. I enabled browser integration and opened a database...

KeePassXC - Version 2.4.3
Revision: 5d6ef0c

Qt 5.12.3
Debugging mode is disabled.

Operating system: Windows 10 (10.0)
CPU architecture: x86_64
Kernel: winnt 10.0.17763

Enabled extensions:
- Auto-Type
- Интеграция с браузером
- SSH-агент
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.4

**Comment by droidmonkey** [comment]
Please follow this guide https://keepassxc.org/quickstart/

**Comment by c269574** [comment]
why did you close it?

 I have no dialog indicating that a request to connect has arrived in application.

**Comment by c269574** [comment]
![image](https://user-images.githubusercontent.com/40603957/65241903-706ff300-daed-11e9-98a9-a897a8d3a1db.png)

**Comment by schmittlauch** [comment]
I am also affected by this: keepassxc 2.5.2 on Windows 10 and Firefox.

I did follow the guide: Browser support is enabled in Keepasxc, the add-on is properly installed, but it also fails with `Key exchange was not successful.`.

I already tried disabling-and-reenabling the browser support in Keepassxc, but that didn't work.

Are there any debug options I can enable?

**Comment by droidmonkey** [comment]
Are you running an alternative version of Firefox or a beta/nightly version?

**Comment by schmittlauch** [comment]
@droidmonkey No, it's the latest mainline 72.0.1 Firefox.
