### ISSUE TITLE
I have no dialog indicating that a request to connect has arrived in application.

### ISSUE THREAD

**Issue by c269574** [keepassxreboot/keepassxc#3559]
![image](https://user-images.githubusercontent.com/40603957/65242870-d52c4d00-daef-11e9-9a5f-6f4b31841abc.png)

**Comment by droidmonkey** [comment]
Are you running the portable version of KeePassXC?

This error indicates that the extension cannot talk to the KeePassXC application.

**Comment by c269574** [comment]
Yes, portable.
So I need to install full version and browser will understand app’s location?

**Comment by c269574** [comment]
still the same :(

**Comment by c269574** [comment]
![image](https://user-images.githubusercontent.com/40603957/65255862-4aefe300-db07-11e9-8323-cf580cf34356.png)

**Comment by c269574** [comment]
So i don't have Connect button. Only in **Settings** > Connected Databases:
![image](https://user-images.githubusercontent.com/40603957/65255995-7ffc3580-db07-11e9-88ff-026265ea6dcc.png)

**Comment by droidmonkey** [comment]
Are you running Firefox portable as well? If so then that's your issue

**Comment by c269574** [comment]
> 
> 
> Are you running Firefox portable as well? If so then that's your issue

no, both are installed

**Comment by c269574** [comment]
Chrome - the same. Should i setup some proxy settings? I use corporate PC and network with proxy.

**Comment by droidmonkey** [comment]
The communication is handled by stdin not networking. With the installed version of KeePassXC, try disabling then reenabling the browser plugin.
