### ISSUE TITLE
HMAC mismatch

### ISSUE THREAD

**Issue by wgordon17** [keepassxreboot/keepassxc#3562]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )
Unfortunately it appears that I've managed to corrupt my kdbx database. Now, whenever I try to open it, I get a "HMAC mismatch" error. When I try to open the DB in KeePass on Windows, I get an error related to the `p.Memory` value being invalid. Some people seem to think this is related to an [invalid Argon2 memory value](https://sourceforge.net/p/keepass/discussion/329221/thread/cc9a98081e/#e415). I even tried using the [Import (Repair Mode)](https://keepass.info/help/base/repair.html) in Windows, and it just ends up importing an empty group.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
I would preferably expect that my DB doesn't get corrupt 😉 but at the very least, if this _is_ due to an invalid Argon2 memory value, I would expect to at least get warned.

## Current Behavior
[NOTE]: # ( Tell us what actually happens )
`HMAC mismatch` error

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )
Any insight into helping me restore my DB would be appreciated!

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1. The memory value set for Argon2 was possibly right about 2GiB or higher

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION 2.4.3
Revision: REVISION 5d6ef0c

Qt 5.12.3
Debugging mode is disabled.

Libraries:
- libgcrypt 1.8.4

Operating system: macOS Mojave (10.14)
CPU architecture: x86_64
Kernel: darwin 18.7.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeyShare (signed and unsigned sharing)
- YubiKey
- TouchID

**Comment by phoerious** [comment]
2GB is way too high. Can you still open it in KeePassXC?

**Comment by wgordon17** [comment]
Yeah, unfortunately I'm finding out that it's too high _after_ the fact. KeePassXC won't open it, complaining about `HMAC mismatch`.

If there's _any_ suggestions on recovery, I'm all ears. Otherwise, at the very least, this bug is about preventing others from screwing up like I did.

**Comment by droidmonkey** [comment]
You are probably running out of RAM during the key transformation.

**Comment by wgordon17** [comment]
I'm running this on a machine with 10GiB RAM...could I have, for some reason, ran out while the DB was being saved, and corrupted my DB...or should I try to unlock it on a machine with even _more_ RAM?

**Comment by droidmonkey** [comment]
How many threads did you set the argon2 up for? My understanding is argon2 uses the amount of RAM designated per thread. If your system is using 4 GB normally, that leaves 6 GB for argon2.

**Comment by wgordon17** [comment]
Well jeeze...I had it set for 8 threads...if it really is 2GiB each...no wonder I'm having problems!

I think this might have to be more of a feature request as opposed to a bug. It would be ideal if the app prevented us from shooting ourselves in the foot 👍🏻

**Comment by droidmonkey** [comment]
The algorithm is: # 1 KiB blocks = mem_size / 4*thread_count. So that is 125K blocks per thread.

**Comment by phoerious** [comment]
We do have some precautions in place to prevent you from accidentally setting stupidly high round numbers. We do not have any such thing for memory or number of threads.

**Comment by rabauss** [comment]
I'm having also Problem on Ubuntu 19.10 with KeepassXC 2.5. Since the Update from 2.43 I cannot unlock my Database. Finally, importing the existing DB in a new Database is working but I cannot unlock the new one after login, too.

Do you have any suggestions as workaround?

**Comment by droidmonkey** [comment]
@rabauss 

![image](https://user-images.githubusercontent.com/2809491/67728048-1bfc4500-f9c2-11e9-925c-58775f6cd804.png)
