### ISSUE TITLE
Hmac mismatch

### ISSUE THREAD

**Issue by Midi3m** [keepassxreboot/keepassxc#3563]
Hi,
I encountered this problem yesterday morning, and I was able to repair it by restarting my computer, but in the night the problem occurred again

KeePassXC - Version 2.4.3
Revision: 5d6ef0c
Qt 5.12.3
Debugging mode is disabled.
Operating system: Windows 10 (10.0)
CPU architecture: x86_64
Kernel: winnt 10.0.17763
Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
Cryptographic libraries:
 libgcrypt 1.8.4

Thanks

**Comment by droidmonkey** [comment]
Unfortunately there is no way for us to know what the problem is, or even if a problem exists. You could have typed the password wrong or have more checkboxes checked then necessary on the unlock screen.
