### ISSUE TITLE
The tray icon title on KDE Plasma is all lowercase characters

### ISSUE THREAD

**Issue by guihkx** [keepassxreboot/keepassxc#3564]
[TIP]:  # ( Provide a general summary of the feature in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Summary
The tray icon title of KeePassXC, at least on KDE Plasma, is written in lowercase characters:

![kpxc](https://user-images.githubusercontent.com/626206/65370541-38bd9400-dc30-11e9-9eb2-a3cd055b32f1.png)

## Desired Behavior

IMO, having the title properly stylized, looks much better, along with the other icons:

![kpxc-ok](https://user-images.githubusercontent.com/626206/65370538-35c2a380-dc30-11e9-96cd-4d7e17f149ad.png)

## Possible Solution

I "fixed it" by simply changing the following line:

https://github.com/keepassxreboot/keepassxc/blob/2.4.3/src/main.cpp#L63

Qt doc [states](https://doc.qt.io/qt-5/qcoreapplication.html#applicationName-prop):

>This property holds the name of this application
>If not set, the application name defaults to the executable name (since 5.0).

Now, I'm not a C++ programmer so I wouldn't know if it breaks something else.

## Context
This is just for looks, honestly.

**Comment by droidmonkey** [comment]
Huh, sounds good

**Comment by guihkx** [comment]
Hi again,

I'd feel silly sending a PR to change only that one line I mentioned. Nonetheless, if you think I should do it, please let me know. 😆

**Comment by droidmonkey** [comment]
Please do
