### ISSUE TITLE
Accept Persian language request on Transifex

### ISSUE THREAD

**Issue by aurora-of-earth** [keepassxreboot/keepassxc#3567]
Please accept language codes 'fa' and 'fa_IR' on Transifex so Persian speaking contributers could translate KeepassXC into Persian.

It seems to have been already requested, but no answer so far.

- <a href="https://www.transifex.com/keepassxc/keepassxc">transifex.com/keepassxc/keepassxc</a>

**Comment by droidmonkey** [comment]
Done!
