### ISSUE TITLE
requires macos 10.12, but can be launched on any older system version

### ISSUE THREAD

**Issue by core-code** [keepassxreboot/keepassxc#3568]
this is missing from your **Info.plist** file:

```
    <key>LSMinimumSystemVersion</key>
    <string>10.12</string>
```

**Comment by phoerious** [comment]
Have you actually tested that? The 10.12 requirement is nothing we ourselves are enforcing. We are just victims of Qt's and Apple's lazy backwards compatibility policies. Qt 5.12 doesn't run on older macOS versions AFAIK.

**Comment by droidmonkey** [comment]
This would, possibly, cause a warning or error message to be displayed by the OS that the app cannot run... Instead of just crashing

**Comment by core-code** [comment]
it just crashes at launch under 10.11, the LSMinimumSystemVersion key should definitely be added to at least provide a nice dialoge that a newer OS is needed instead of an unfriendly crash:

<img width="960" alt="Screenshot 2019-09-25 at 21 04 57" src="https://user-images.githubusercontent.com/1261954/65631670-4c724d00-dfd8-11e9-99a5-848309968bb6.png">

**Comment by phoerious** [comment]
I understand. You just want that to get a nicer error message. I thought you wanted that as a hack to be able to launch it anyway.

**Comment by core-code** [comment]
yes it is about the error message. also, it is the right thing to do. mac apps are supposed to properly contain their system requirements.

**Comment by phoerious** [comment]
If we add that, it somehow needs to be determined by the build system. KeePassXC itself can be run on older macOS versions. Only our binaries are incompatible, because they were compiled on a newer macOS release and with Qt 5.12.

**Comment by core-code** [comment]
shouldn't be too hard. i guess there are a million different ways, depending on the build system. you can always edit the Info.plist file directly

`/usr/libexec/PlistBuddy -c "Set :LSMinimumSystemVersion 10.12" "${INFOPLIST_FILE}"
`
