### ISSUE TITLE
KeepassXC generates identical UUIDs and overwrites entries

### ISSUE THREAD

**Issue by v4rakh** [keepassxreboot/keepassxc#3569]
## Expected Behavior
When creating new entries, I expect that UUIDs under the tab 'Advanced' differ from each other for newly created entry.

## Current Behavior
UUID is always ffffffffffff4fffbfffffffffffffff. Database gets saved normally and the latest entry with this UUID overwrites every old entry. Don't know how many entries I have overwritten now.

## Steps to Reproduce
1. Create a new entry, look at Advanced tab, see UUID
2. Create another entry, look at Advanced tab, see the same UUID
3. Close database, reopen, only the latest is still present
4. (optional) Compare with mono Keepass app which tells that some UUIDs for entries are the same and suggests to repair it

## Context
I encountered this issue with my daily used database. I then tried it with a freshly created one and the same behavior occurs.

## Debug Info
KeePassXC - Version 2.4.3
Revision: 5d6ef0c

Qt 5.13.1
Debugging mode is disabled.

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 5.3.1-arch1-1-ARCH

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.5

**Comment by v4rakh** [comment]
Ok, this was solely related to my AMD 3rd Gen CPU running on old firmware. Updated BIOS and it's working as expected now.

But would it be good if we had a detection for the duplicate UUIDs problem?

**Comment by droidmonkey** [comment]
You are three weeks late to the party
