### ISSUE TITLE
App is pixelated after connecting an external display

### ISSUE THREAD

**Issue by tschf** [keepassxreboot/keepassxc#3570]
I am running on Ubuntu 18.04 and have keepassxc installed with the snap. See debug info for version

My computer is Lenovo Thinkpad T440P, and I have the ultra dock which I use to connect to my display.

My display is a Dell 4K.

If I am running keepassxc on my laptop before being connected to the display, and subsequently connect to the external display, the app becomes very pixelated.

![image](https://user-images.githubusercontent.com/1747643/65401714-3b291500-de0d-11e9-970f-4f02febca327.png)

it usually looks like this:

![image](https://user-images.githubusercontent.com/1747643/65401874-21d49880-de0e-11e9-924a-cb24fc3e3bb9.png)

## Steps to Reproduce
1. On Ubuntu, open up keepassxc, without being connected to external display
2. Connect to external, higher res display
3. Observe the pixelation (see above screenshot)

## Workaround

Quit Keepass and re-open

## Context

Note, keepassxc is the only application that does this in my environment.
If I open whilst being connect to the external display, disconnect, and the reconnect, there is no issue with the pixelation.

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
```
snap info keepassxc
name:      keepassxc
summary:   community driven port of the windows application “Keepass Password Safe”
publisher: Jonathan White (keepassxreboot)
contact:   https://github.com/keepassxreboot/keepassxc
license:   unset
description: |
  KeePassXC is an application for people with extremly high demands on secure
  personal data management. It has a light interface, is cross platform and
  published under the terms of the GNU General Public License.
  
  For usage tips see: https://github.com/keepassxreboot/keepassxc/wiki/Snap-Tips
commands:
  - keepassxc.cli
  - keepassxc
  - keepassxc.proxy
snap-id:      jf2HsR51rlftaREcwhtxiEcDc76gL4O6
tracking:     stable
refresh-date: 2019-06-15
channels:
  stable:    2.4.3 2019-06-12 (378) 100MB -
  candidate: ↑                            
  beta:      2.4.2 2019-06-09 (353) 102MB -
  edge:      2.5.0 2019-09-22 (521) 104MB -
installed:   2.4.3            (378) 100MB -
```

```
KeePassXC - Version 2.4.3
Revision: 5d6ef0c
Distribution: Snap

Qt 5.9.5
Debugging mode is disabled.

Operating system: Ubuntu Core 18
CPU architecture: x86_64
Kernel: linux 4.15.0-64-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.1
```

**Comment by phoerious** [comment]
This is a problem if your system not communicating the different PPI settings of your monitors correctly.

**Comment by tschf** [comment]
Ah OK. Wasn't sure when I didn't experience this issue with any other app, so figured it may be worth reporting here. If not an issue on this end, no prob!

**Comment by droidmonkey** [comment]
This could be a combination of using a snap and Qt not being told what is what.

**Comment by tschf** [comment]
I'm closing this since it doesn't seem related to this project based on the previous 2 replies.
