### ISSUE TITLE
Question for 2.5.0 WIP

### ISSUE THREAD

**Issue by rnc** [keepassxreboot/keepassxc#3574]
Is https://github.com/keepassxreboot/keepassxc/pull/3311 targeted for 2.5.0? As I can't see it mentioned in https://github.com/keepassxreboot/keepassxc/blob/develop/CHANGELOG.md (and I think its useful / important enough to be mentioned there - I am eagerly anticipating this feature :-) )

**Comment by phoerious** [comment]
Yes. Why don't you ask below that pr?

**Comment by rnc** [comment]
@phoerious Because that was a closed ticket/pr....

**Comment by phoerious** [comment]
Doesn't mean you can't reply to it anymore

**Comment by rnc** [comment]
Ok ;-) I have added a comment to that PR. In general I've found a lot of projects prefer new tickets over reopening but obviously its down to each maintainer :-)

**Comment by droidmonkey** [comment]
Just look for the milestone on an issue or PR and that tells you what version it's destined for.

**Comment by wolframroesler** [comment]
Added #3583 with a change log entry for HTML Export.

By the way, keeping an alphabetically sorted change log instead of adding everything to the end would prevent merge conflicts in some situations.

**Comment by droidmonkey** [comment]
Doesn't matter the sorting, merge conflicts will occur on adjacent lines.
