### ISSUE TITLE
issue with touchID on MacBook Pro - it keeps asking for passwd each time I open an app

### ISSUE THREAD

**Issue by jacek-1** [keepassxreboot/keepassxc#3575]
Hi,

Somehow keePassXC 2.4.3 on MacOS Mojave 10.14.6 keeps asking for passwd every time I open an app,
Besides passwd I have also key file enabled,
„touchID for quick unlock” selected doesn’t work,

my expected behaviour would be to open a db without a need to enter a passwd, authentication would be only using TouchID.

Thanks

**Comment by jacek-1** [comment]
I found a kind of workaround for this:

https://github.com/keepassxreboot/keepassxc/issues/2720#issuecomment-506710663

> I am using KeepassXC 2.4.3, and realised that to trigger TouchID on mac, I needed to leave the password field blank, and press the enter key. Then I see the "TouchID" dialog and am able to unlock with my fingerprint. Of course, this happens only on "lock" of an open database. First time login into a database still requires a password (which is good).

well I would expect configurable behaviour and to be able to authenticate with TouchID also when opening a DB for the first time, so I would say its still a bug

**Comment by droidmonkey** [comment]
This is covered by #2865
