### ISSUE TITLE
Find duplicate and insecure passwords

### ISSUE THREAD

**Issue by absolutez3** [keepassxreboot/keepassxc#3579]
[TIP]:  # ( Provide a general summary of the feature in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Summary
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
This new feature would essentially perform a password audit on your database by looking for duplicate/reused passwords or weaker passwords.

## Desired Behavior
[NOTE]: # ( Tell us how the new feature should work, be specific )
Add a menu option under "Tools" called 'Password Audit". It will then return entries that have either weak or reused passwords.

## Possible Solution
[NOTE]: # ( Not required, but suggest ideas on how to implement the addition or change )

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
It increases the overall security of multiple accounts by letting a user quickly review any issues.

**Comment by droidmonkey** [comment]
This is a duplicate issue

**Comment by absolutez3** [comment]
Could you link to the original? I wasn't able to find it hence me posting this

**Comment by droidmonkey** [comment]
Search for password analyzer

**Comment by absolutez3** [comment]
https://github.com/keepassxreboot/keepassxc/issues/551
