### ISSUE TITLE
More control over notifications in main window

### ISSUE THREAD

**Issue by CleyFaye** [keepassxreboot/keepassxc#3580]
## Summary
Currently some operations trigger the display of a notification in the main window (at the top, right under the toolbar). In some cases this notification can get huge; having some settings to limit the size of the notification, or to request a shorter version, would mitigate the issue.

## Desired Behavior
There could be a "notification" section in the settings, that allow the users to set settings for different categories of notifications.
For example, when saving, one could select to have either the full save/keeshare sync messages displayed, or just "Database saved" (or, disable this notification altogether).

## Possible Solution
A section in settings with a few notifications categories (save, load, auto-update, etc.) which provide settings for each to either have full details, one-liner, or to disable the category.

## Context
The one thing that prompted me to ask for this is that I have a single keepass database which hold a lot of keeshare entries. Everytime I save there is a notification that ends up taking the whole windows, with one line for each keeshare entry.
While very annoying, it also triggers a small bug where the bottom of the window (with buttons) is slightly pushed out of frame by this.

It looks like this:
![image](https://user-images.githubusercontent.com/1065984/65694661-82660e80-e076-11e9-9014-e227c6e5834c.png)

**Comment by droidmonkey** [comment]
Go to the KeeShare settings and enable the "only show warnings and errors" option.

**Comment by CleyFaye** [comment]
I'm sorry, but I do not seem to have this option.
Right now I'm on windows with keepassxc 2.4.3, and I believe the same version on Linux at my office, but neither have such option.

The only settings I see in KeeShare settings are Allow Import/Export, certificate generation and imported certificates.
If it is a feature coming in the next version it's okay, I just want to make sure. If that's the case feel free to close this ticket.

Here's a capture of my Keepass settings page, just in case.
![image](https://user-images.githubusercontent.com/1065984/65715188-eb607d00-e09c-11e9-9927-1d20e0ae9107.png)

**Comment by droidmonkey** [comment]
Whoops! That was introduced in 2.5.0. You can download a snapshot of develop at https://snapshot.keepassxc.org.

**Comment by CleyFaye** [comment]
Nice. As long as it's coming, it's ok for me. Thanks.
