### ISSUE TITLE
Open database without pwd

### ISSUE THREAD

**Issue by livier** [keepassxreboot/keepassxc#3581]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Expected Behavior
keepassxc never pens without passwd

## Current Behavior
After a power failure, when the computer restarts, keepassxc reopens without asking for a password again.

## Possible Solution
Excuses my english
- be sure to put a lock file in ram so it is lost after a reboot or power failure
- check the inactivity time at startup

## Steps to Reproduce
1. Hot power shutdown while keepassxc is open
2. reboot and start keepassxc
3.

## Context
desktop computer

## Debug InfoKeePassXC - Version 2.4.3
Revision: 5d6ef0c

Qt 5.12.3
Debugging mode is disabled.

Operating system: KDE neon User Edition 5.16
CPU architecture: x86_64
Kernel: linux 4.15.0-64-generic

Enabled extensions:
- Auto-Type
- Intégration aux navigateurs
- Agent SSH
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.1

**Comment by droidmonkey** [comment]
What???

**Comment by gyli** [comment]
@livier This is way too weird. Maybe you can try another database or another computer first?

**Comment by droidmonkey** [comment]
Im closing this cause it doesn't make sense
