### ISSUE TITLE
Database opens in read-only mode when accessed remotely using 'dav' protocol

### ISSUE THREAD

**Issue by ckoul** [keepassxreboot/keepassxc#3584]
When the database file is stored on a remote host accessed through the DAV protocol the file is always opened in read-only mode. If I save the file with a different filename the file stays in write mode until I close it. When I reopen the (second) file it opens in read-only mode. Ownership and file permissions are always the same in both files (opened or closed).

The client used to access the remote file is the built-in Gnome Online Accounts (nextcloud account) which maps the remote location to a local link like:
/run/user/1000/gvfs/dav:host={host},ssl=true,user={user},prefix=%2Fremote.php%2Fwebdav/{folder}

## Expected Behavior
The file opens in 'rw' mode.

## Current Behavior
The file opens in 'ro' mode

## Steps to Reproduce
1. Connect to a nextcloud account in Gnome Online Accounts.
2. Using KeePassXC open a .kbdx file from the remote location.
3. The file opens in read-only mode.

## Context
This only happens when accessing the database file through Gnome's Online Accounts (which uses the DAV protocol).

## Debug Info
KeePassXC - 2.4.3
Revision: 5d6ef0c

Libraries:
- libgcrypt 1.8.1

Operating system: Pop!_OS 18.04 LTS
CPU architecture: x86_64
Kernel: 5.0.0-23-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

**Comment by droidmonkey** [comment]
A test is performed when the file is opened to see if it can be opened in Read-Write mode. If that tests fail then the file is opened read only. This, to me, could be a bug in the Gnome Online Accounts.

**Comment by ckoul** [comment]
The test fails but maybe this has to do with the non-conventional file system. The file/location is writeable as indicated by the success of the "Save as" function.

I wonder if a different 'test' method could be implemented that would succeed on the specific file system or even an attempt to open the file in 'rw' directly.

I'll take a look at the code and try to test some of the assumptions.

**Comment by ckoul** [comment]
Closing, as the problem probably lies on the way Gnome Online Accounts connects to the webdav folder.
