### ISSUE TITLE
Access search via keyboard when hidden in toolbar

### ISSUE THREAD

**Issue by elig0n** [keepassxreboot/keepassxc#3586]
When the toolbar items are bigger than what can fit in the visible width of the toolbar and the '>>' extension button is shown if the search bar is hidden from view a Ctrl+F doesn't let one access the search bar, visibly or invisibly. I often rely on the keyboard to reach entires and it would be cool to either allow multi row toolbar, or reorder the toolbar items, or focus/pop up the search bar nonetheless.

**Comment by droidmonkey** [comment]
Duplicate issue

**Comment by elig0n** [comment]
@droidmonkey can you please link to the original issue ?

**Comment by droidmonkey** [comment]
#505
