### ISSUE TITLE
Shorten search delay timer

### ISSUE THREAD

**Issue by toofar** [keepassxreboot/keepassxc#3587]
## Summary
https://github.com/keepassxreboot/keepassxc/commit/4b983251cb464d104aafd95ea56e19b5c404247a#diff-54192eee50d5dba69b89f9f6caa74abcR140 changed the duration of the timer after which a new search filter is applied from 100ms to 300ms. This has been annoying me since I upgraded (which was quite delayed since i am on Debian). I get that this might be preferrable on constrained devices due to the more complex search behaviour now but would it be possible for this to be configurable so we can make it "instant" on more beefy machines?

## Desired Behavior
I don't have to wait for a noticable amount of time for the filtered search results.

## Possible Solution
Add a new config option to configure the search delay time, similar to https://github.com/keepassxreboot/keepassxc/pull/3411 except probably don't need to be able to disable it.

## Context
I think I got used to a workflow of searching for a string that I knew would match and copying right away, now I have to wait. It isn't a big delay but because it is different than what I am used to I notice it (I've been on 2.4.3 (previously on 2.3.4) for two weeks now). I'm surprised no-one has complained already tbh.

**Comment by droidmonkey** [comment]
It doesn't need to be configurable, just lessened. Tbh I think it was a mistake that it was increased to begin with (I was messing around with different values and didn't revert)
