### ISSUE TITLE
add option to require enter press before performing search

### ISSUE THREAD

**Issue by nagimov** [keepassxreboot/keepassxc#3589]
## Summary
Add an option requiring ENTER press before performing a search (maybe merge this with #3587 if delay is going to be added to the settings as well?)

## Desired Behavior
Start search only after pressing enter

## Possible Solution
Add a settings flag requiring pressing enter before searching

## Context
I'm switching to keepassxc from keepass, so it is now in my DNA to press enter after typing any search query. This opens up a first highlighted entry for editing which is not what I expect.
I'm sure I can't be the only one who's annoyed by this default behavior after switching from keepass.

**Comment by droidmonkey** [comment]
This has been discussed SEVERAL times.

**Comment by droidmonkey** [comment]
#3443 is the active discussion for this
