### ISSUE TITLE
Repeated Import/Export when changing database

### ISSUE THREAD

**Issue by franzlst** [keepassxreboot/keepassxc#3590]
When I make a change to my database, KeePassXC repeatedly shows Export to [Location] / Imported from [Location] / Export / Import /... . After a while (minutes), a dialog pops up that the database file has changed and I have unsaved changed, whether I want to merge. After Merging, the spook ends.

I think this is related to icons being retrieved from a URL. At least I saw this the first time when I commanded KeePassXC to retrive an icon from a URL.

## Debug Info
KeePassXC - Version 2.4.3
Revision: 5d6ef0c

Qt 5.12.3
Debugging mode is disabled.

Operating system: Windows 10 (10.0)
CPU architecture: x86_64
Kernel: winnt 10.0.18362

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.4

**Comment by droidmonkey** [comment]
You probably setup a circular KeeShare. Check your keeshare locations.

**Comment by franzlst** [comment]
Thank you for the hint. I indeed had a KeeShare setup. I removed it (I no longer need it) and the issue is gone. So for me, the problem is solved.

However, I'm wondering what you mean with "circular" and why such an error is not caught be KeePass.

**Comment by droidmonkey** [comment]
It is in develop so this won't be an issue in the future
