### ISSUE TITLE
Please add browser support for firefox-wayland

### ISSUE THREAD

**Issue by asterbini** [keepassxreboot/keepassxc#3591]
I have noticed that when I use firefox-wayland on Fedora 30 the browser extension does not communicate with KeepassXC.
Would it be possible to add support for the browser firefox-wyland?

**Comment by phoerious** [comment]
Probably related to #3520

**Comment by droidmonkey** [comment]
No this is probably because firefox-wayland stores its configuration in an "off" directory. You'll have to manually move the native messaging configuration.

**Comment by asterbini** [comment]
Thanks, I understand, I'll try to move the configuration as you suggested
