### ISSUE TITLE
Mouse cursor constantly switches from default to i-beam when hovered over input

### ISSUE THREAD

**Issue by sgerace** [keepassxreboot/keepassxc#3595]
## Expected Behavior
When hovered over an input, the cursor should change from the default pointer to an i-beam cursor (and remain an i-beam cursor while hovered). 

## Current Behavior
When hovered over an input, the cursor is constantly switching between the default cursor and an i-beam:

![cursor](https://user-images.githubusercontent.com/1239058/65997287-1533ee00-e467-11e9-8c8f-f6c805721b90.gif)

## Steps to Reproduce
1. Open KeePassXC
2. Hover mouse cursor over input (it exhibits this behavior for all inputs when I run the application)

## Debug Info
KeePassXC - Version 2.4.3
Revision: 5d6ef0c

Qt 5.12.3
Debugging mode is disabled.

Operating system: macOS Mojave (10.14)
CPU architecture: x86_64
Kernel: darwin 18.7.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
 libgcrypt 1.8.4

**Comment by droidmonkey** [comment]
This isn't something we would have any control over. This doesn't happen to me on macOS either.

**Comment by sgerace** [comment]
@droidmonkey I just installed v2.4.1 this behavior definitely goes away. Installing v2.4.3 again causes this behavior to return. I was going to test v2.4.2 but didn't see a .dmg package from the [GitHub releases page](https://github.com/keepassxreboot/keepassxc/releases/tag/2.4.2). 

Clearly _something_ must have changed between v2.4.1 and v2.4.3 to cause this behavior. I'll try testing on my other Macs to see if I see the same behavior there with the latest release.

**Comment by droidmonkey** [comment]
The version of Qt changed to my knowledge

**Comment by sgerace** [comment]
Ahh, I think that explains it, knowing what to look for, the issue seems to be described in this StackOverflow question:

https://stackoverflow.com/questions/56129711/macos-mouse-pointer-flashing-with-signals-and-qlineedit-blinking-cursor

and this Qt bug report:

https://bugreports.qt.io/browse/QTBUG-75552

Sure enough, KeePassXC v2.4.1 is using Qt 5.12.2 while KeePassXC v2.4.3 is using Qt 5.12.3 (which is the affected version listed in that bug report). Do you think it would be worth re-opening this ticket to track upgrading to the new version of Qt, or would it be helpful if I created a new ticket specifically for that purpose, or should I just use v2.4.1 until KeePassXC is upgraded to a new version of Qt?

**Comment by droidmonkey** [comment]
No the version will be 5.13 on the next release

**Comment by sgerace** [comment]
Sounds good, thanks for the update and I'll keep my eyes open for the next release.
