### ISSUE TITLE
Copy column field value on double-click

### ISSUE THREAD

**Issue by nfnty** [keepassxreboot/keepassxc#360]
## Expected Behavior

Column field value should be copied directly when double-clicked in the main view.

## Current Behavior

Either you enter the full entry view or clicking the URL field opens the link in a browser.

## Context

Partly depends on configurable columns, as reported in  #17.

Should be default on username/password fields and configurable for all fields.

Have been using KeePassX `0.4.4` for a long time and really missing this feature.

## Your Environment

* KeePassXC version/commit used: `2.1.2`
* Qt version (e.g. Qt 5.3): `5.8.0`
* Compiler (e.g. Clang++3.6.0): GCC `6.3.1`
* Operating System and version: Arch Linux

**Comment by GillesP** [comment]
Hi, in my mind, the best behavior is when double-clicking an entry, the URL opens, and the password is copied to the clipboard. (Revelation, on Gnome env. does)

**Comment by ConcurrentHashMap** [comment]
👍 The behavior from original KeePass is great: Double-clicking the username copies the username, double-clicking the password colum (see #17) copies the password (and so on for all other fields except the URL field). Double-clicking the URL opens the URL.

**Comment by fonic** [comment]
Covered by #849
