### ISSUE TITLE
Positive checkbox texts in application settings dialog

### ISSUE THREAD

**Issue by wolframroesler** [keepassxreboot/keepassxc#3601]
## Summary

In the checkbox texts in the application settings dialogs, I find negative formulations like "Don't do that" difficult to understand, and prefer positive formulations like "Do that". For example, instead of "Don't mark database as modified for non-data changes", I'd prefer "Mark database as modified for non-data changes" (and reverse the meaning of the checkbox).

## Desired Behavior

Current checkbox texts:

* Don't mark database as modified for non-data changes
* Don't require password repeat when it's visible
* Don't hide passwords when editing them
* Don't use placeholder for empty password fields

Suggested new checkbox texts:

* Mark database as modified for non-data changes
* Require password repeat when it's visible
* Hide passwords when editing them
* Use placeholder for empty password fields

Note that this reverses the meaning of the checkbox itself (i. e., checked now is unchecked after the change, and vice-versa).

Technically, it's not a breaking change because existing installations will continue working as before. However, users may find this breaking when they memorized something like "clear the checkbox that says modified for non-breaking changes", because in the future they have to check it to achieve the same behavior.

## Possible Solution

Volunteering to implement it.

## Context

In a different app, I recently spent too much time wondering why something didn't work, when a checkbox was checked but it should have been unchecked. (Checkbox text wasn't completely visible due to low screen resolution, I assumed checking it meant "activate something" when it in fact meant "don't activate it".)

**Comment by droidmonkey** [comment]
The way the setting is named internally could complicate this, but I ensure the change

**Comment by wolframroesler** [comment]
Great, will turn to it when I find the time.

**Comment by droidmonkey** [comment]
This would be targeted for 2.6.0 with our GUI overhaul, so no rush.
