### ISSUE TITLE
Merging databases: error (db in use) but bin gets merged

### ISSUE THREAD

**Issue by Bug-Ninja** [keepassxreboot/keepassxc#3604]
I have 2 databases. Lets call them "Main" and "OldDB". When I try to merge OldDB with the Main, so the main will contain data of both DBs, I get an error that the merge cannot be done, because OldDB is in use.  However, the bin of OldDB gets placed in Main. I end up with 2 bins in Main. In other words: the merge is partly done.

## Expected Behavior
I'd expect one of these 2 things:
1. a warning that OldDB is in use, and must be closed prior to the merging. No action will be taen.
2. The merging takes place, after the program saves and closes OldDB automatically prior to merging.

## Possible Solution
I'm not that technical I can provide a solution, but if solution 1 or 2 could be implemented, it would be helpful.

## Steps to Reproduce
1. open 2 databases, let's call them db1 and db2
2. delete some items from db2, so they end up in the bin.
3. with db1 in the active tab, choose "Merge from database" from the menu "Database" and locate the database file of db2
4. the program warns you that you cannot merge as db2 is in use, but in db1 you will see 2 bins, the latter being from db2

## Context
I am new to the program and imported my passwords from firefox to delete old entries. I simply wanted to merge the result of this with my default database.

## Debug Info
KeePassXC - 2.4.3
Revision: 5d6ef0c

Qt 5.12.3
Debugging mode is disabled.

Operating system: Windows 7 SP 1 (6.1)
CPU architecture: x86_64
Kernel: winnt 6.1.7601

Enabled extensions:
- Auto-Type
- Browserintegratie
- SSH-agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.4

**Comment by droidmonkey** [comment]
Please post the exact error message (screenshot of it is ok, don't screenshot your passwords). Have you tried merging without having db2 open in KeePassXC?
