### ISSUE TITLE
Prevention of database file truncation if no space left

### ISSUE THREAD

**Issue by KevinSeroux** [keepassxreboot/keepassxc#3606]
This issue can be see as a bug but not directly related to KeePassXC, hence the feature request.

## Summary

Suppose, there are:
1. Pending changes in the database
2. Writings, by another process on the database file device, which are about to fill it

This is what happen when saving:
1. The database file is truncate to 0 bytes for future writings
2. The concurrent process fill the remaining device space
3. No bytes can be written to the database file
4. KeePassXC ignore this error

Thus, "[database_file_name].kdbx" is empty (0 bytes).

## Desired Behavior

KeePassXC could :
1. Detect the writing error (if no error are thrown by system calls, perform a manual check)
2. Inform the user
3. Ask the user a location with space left to save a backup
4. Save another copy in any cases (if the user ignore the error) somewhere else (eg. ~ or HOME).

I'm sure there are better solutions.

## Context

I guess this is what happened to me today. The device was a remote ssh mount. Furthermore, the "[database_file_name].old.kdbx" was as empty. I was lucky to have an internal cache of the database file on my mobile phone (keepass2android) which had not sync yet.

This is a rare situation, but the integrity of the data seems to me extremely important when dealing with passwords. This is why I think a solution should be implemented.

Have a nice day!

**Comment by droidmonkey** [comment]
Is it possible to determine the space remaining on a remote ssh mount? I suspect this is why their was a catastrophic failure, Qt was just sending data to the mount and the mount itself was not complaining that it had no space left (just dropped it). We rely 100% on Qt to send us file system errors. If no error is provided, then that to me means the file system did not communicate it.

**Comment by KevinSeroux** [comment]
Hello,

Yes, it is possible to determine the left space as any device with the command : `df`. Maybe when writing, sshfs skips some errors.

In any case, even if the left space is enough. Maybe, it is still possible that between the check and the writing, the reported space has been used.
 
Safe saves are enabled.

**Comment by droidmonkey** [comment]
df is a shell command. The protocol that you are using (I am assuming sshfs) does it report space available? I assume not. Safe saves do not allow overwriting the file until the entire temporary file is fully written. If no errors are reported, then there is nothing we can do.
