### ISSUE TITLE
Set focus after buttonTogglePassword was pressed

### ISSUE THREAD

**Issue by Ovascos** [keepassxreboot/keepassxc#3607]
[TIP]:  # ( Provide a general summary of the feature in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Summary
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
On opening a database, set the focus on the password field after the toggle password button ("eye"-button) was pressed.

## Desired Behavior
[NOTE]: # ( Tell us how the new feature should work, be specific )
When entering a password I usually press Tab followed by Space to unhide the entered password. It would be very convenient to set the focus back on the password field (and set the cursor after the last symbol) after the toggle button was "clicked".
I adopted this habit back when still using Keepass2, this suggestion is Keepass2's default behaviour.

## Possible Solution
[NOTE]: # ( Not required, but suggest ideas on how to implement the addition or change )
Should be a one-line change in DatabaseOpenWidget.cpp(?).

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
The suggested behaviour seems naturally to me, since after unhiding the password, one might very likely (continue) entering the password.

**Comment by droidmonkey** [comment]
This is a duplicate
