### ISSUE TITLE
Doubleclick on URL should open Browser

### ISSUE THREAD

**Issue by MegaV0lt** [keepassxreboot/keepassxc#3608]
[TIP]:  # ( Provide a general summary of the feature in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Summary
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
In the database records is a URL. It should be possible to double click it to open the URL in the default browser. 

Using KeePassXC 2.4.3 @ Linux Mint 19.2

## Desired Behavior
[NOTE]: # ( Tell us how the new feature should work, be specific )
Well, when i double click the url field it should pen in the browser.

## Possible Solution
[NOTE]: # ( Not required, but suggest ideas on how to implement the addition or change )

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )

**Comment by viktorfrom** [comment]
Cannot replicate this in MacOS Mojave v10.14.6 or Fedora v30. Is this Win10 specific?

**Comment by droidmonkey** [comment]
Where exactly are you double clicking?

**Comment by MegaV0lt** [comment]
It makes no diference where i click. See picture:
![Auswahl_20191008_14:11:39](https://user-images.githubusercontent.com/2804301/66394570-ca215a00-e9d5-11e9-9855-8c4ea43ac388.jpg)

Using KeePassXC 2.4.3
Linux Mint 19.2

**Comment by droidmonkey** [comment]
Yah then that means you need to setup your default browser in the OS

**Comment by droidmonkey** [comment]
Did this start happening all of a sudden or since the begining of use?

**Comment by MegaV0lt** [comment]
For me it never worked. I use Linux for one year or so. First with original KeePass and Mono...
