### ISSUE TITLE
macOS 10.15: Auto-type requires screen reader permission

### ISSUE THREAD

**Issue by Shuyinsama** [keepassxreboot/keepassxc#3609]
## Expected Behavior
I am using the shortcut ALT+SHIFT+A as my auto-type. Whenever I press that combination I expect the auto-type to start either by inputting the credentials or by showing a dialog with credential options for that website/application

## Current Behavior
After updating to macOS Catalina auto-type stopped working. My shortcut starts something but for every website/application I get the error message saying:
"Couldn't find an entry that matches the window title: passwords.kdbx - KeePassXC"
When I check the auto-type settings for that website I also notice that the "Window title:" dropdown does not get populated with possible windows titles that are currently open.

## Steps to Reproduce
1. Update to macOS Catalina
2. Open browser
3. Open KeePassXC
4. Browse to website where auto-type is setup
5. Use shortcut to start auto-type
6. The error message should appear

## Context
We use KeePassXC at work with passwords that are all generated through KeePassXC so I personally don't remember any of the passwords. Currently I manually copy and paste the credentials which is more annoying but it works for now.

## Debug Info
KeePassXC - Version 2.4.3
Revision: 5d6ef0c

Qt 5.12.3
Debugging mode is disabled.

Operating system: macOS 10.15
CPU architecture: x86_64
Kernel: darwin 19.0.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
 libgcrypt 1.8.4

**Comment by droidmonkey** [comment]
You probably need to remove and readd KeePassXC to the privacy controls in settings.

**Comment by codemunin** [comment]
Same problem here.

I completely removed the KeePassXC App and "reinstalled" it. I cleared out the Library and Privacy settings, too. Nothing changed.

The shortcut is only recognized inside the application. When i got to another window, for example Remote Desktop, it doesn't work.

**Comment by Shuyinsama** [comment]
@droidmonkey Like @codemunin I indeed did that. Although I did not fully reinstall the application but I did reassign the permissions in the macOS privacy settings. The shortcut is indeed only recognised inside the KeePassXC application itself.

**Comment by droidmonkey** [comment]
Please try our snapshot for macOS: https://snapshot.keepassxc.org

I moved to a newer keyboard shortcut API in 2.5.0

**Comment by Shuyinsama** [comment]
Thanks. Sadly the snapshot version exhibits the same bug.

**Comment by codemunin** [comment]
I tried it inside a fresh installed VM. Same problem in a clean OS.

I noticed KeepassXC has not requestet the OSX privacy settings. Adding it manually hasn't helped too.

**Comment by droidmonkey** [comment]
Time to spend 3 hours with the terrible apple api documentation

**Comment by michaelblyons** [comment]
I don't know if it helps with Qt at all, but MacPass is working on [the same problem](https://github.com/MacPass/MacPass/issues/948).

**Comment by droidmonkey** [comment]
Certainly does help point in the right direction! Thank you.

**Comment by Shuyinsama** [comment]
@droidmonkey It seems like we need  Screen Recording permissions to read window titles? It could be that the global hotkey works for KeePassXC but it just can't find/read the correct window to input.

If there is anything I can do to help please let me know :)

**Comment by codemunin** [comment]
> Time to spend 3 hours with the terrible apple api documentation...

Thank you very much. You can Message me for help or testing.

**Comment by georgesnow** [comment]
@droidmonkey i believe this is what you are looking for:

https://developer.apple.com/documentation/coregraphics/1455137-cgwindowlistcopywindowinfo?preferredLanguage=occ

It requires proper permissions for screen recording in order to use this function

**Comment by Joachim-42he** [comment]
I just had to update BetterTouchTool, where they also stated that they can only get widow titles from macOS if the have Screen Recording Permissions.

**Comment by droidmonkey** [comment]
You can test the Auto-Type itself by using the Cmd+Shift+V shortcut. That doesn't use window titles

**Comment by droidmonkey** [comment]
I could not replicate this failure at all on Catalina. Everything worked perfectly immediately after the first boot from upgrade.

**Comment by Najkon** [comment]
whether it is possible the patch be released as an official package?
terribly I regret the absence of this option :/

**Comment by droidmonkey** [comment]
This will be released very soon

**Comment by nolimitcarter** [comment]
Still no solutions?

**Comment by ttomasini** [comment]
I'm using KeePassXC 2.5.2 stable at the moment but I still have the problem that AutoType is not working via the hotkey on Catalina. I get the following notification: "Couldn't find an entry that matches the window title: passes - KeePassXC".

The Screen Recording Permission is set. How can I get more detailed logs about the issue?

**Comment by droidmonkey** [comment]
Are you using the hotkey when the window you want Auto typed into is focused? There is also an issue (I think) with Auto-Type on windows that are in the macOS super maximized mode.

**Comment by obfuscoder** [comment]
I installed version 2.6.1 and after hitting the autotype key combination I got the message that accessibility and screen recoing access is required. Keepass showed up in the Accessibility tab of the privacy settings and I checked it so it can use this feature. However, KeePass was not showing up in the Screen Recording tab at all so I could not check it. I tried restarting KeePass, and hitting autotype key combo showed again this error message. Following the button to the system preferences, I ended up in Accessibility section (with KeePass being checked there) again and KeePass was still not added to the screen recording section. Unable to proceed.

**Comment by obfuscoder** [comment]
There is also no "+" button in the screen recording section of the privacy settings which would allow me to add KeePass manually, btw.

**Comment by georgesnow** [comment]
@obfuscoder what version of macOS are you running?

**Comment by droidmonkey** [comment]
@obfuscoder you need to restart your mac
