### ISSUE TITLE
CTRL+C copies password instead of notes

### ISSUE THREAD

**Issue by NicolasGoeddel** [keepassxreboot/keepassxc#3614]
Please reopen one of these issues:

https://github.com/keepassxreboot/keepassxc/issues/1653
https://github.com/keepassxreboot/keepassxc/issues/2941

This issue still exists or exists again in version 2.4.3.

## Context
If I select some text in the notes panel and press CTRL+C it should copy the selected text and not the password of the selected entry. I nearly copied my password to the wrong place because of this behaviour. It really should be changed.	

## Debug Info
KeePassXC - Version 2.4.3
Revision: 5d6ef0c

Qt 5.12.2
Debugging mode is disabled.

Operating system: Ubuntu 19.04
CPU architecture: x86_64
Kernel: linux 5.0.0-29-generic

Enabled extensions:
- Auto-Type
- Browser-Integration
- SSH-Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.4

**Comment by droidmonkey** [comment]
This is already fixed in develop and will be in 2.5.0
