### ISSUE TITLE
2.4.3 - What Is This Share Tab? Notes Greyed Out?

### ISSUE THREAD

**Issue by 0pLuS0** [keepassxreboot/keepassxc#3618]
## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
I assumed this ```Share``` tab was related to ```KEESHARE``` & ```KEESHARE_SECURE```?

## Current Behavior
[NOTE]: # ( Tell us what actually happens )
When I click on a Directory in the left window pane, I will always see 3 tabs listed on the right side; ```General - Notes - Share``` Notes is also always greyed out, is this normal too?

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )
I don't really know if this is a bug, I'm just trying to understand what it is I'm seeing and what this ```Share``` tab is for?

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1. Run KeepassXC
2. Click on a directory on the left side pane
3. Now view the right side, where you will now see these 3 tabs.

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )
I'm not understanding, seeing the point to these 3 tabs, what their purpose is?

As I mentioned before I assumed this Share tab was related to the KEESHARE, I disabled these at compile time, and these are my compile flags I used;

-DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_BUILD_TYPE=Release \
    -DWITH_TESTS=OFF \
    -DWITH_XC_BROWSER=OFF \
    -DWITH_XC_YUBIKEY=OFF \
    -DWITH_XC_NETWORKING=OFF \
    -DWITH_XC_AUTOTYPE=ON \
    -DWITH_XC_SSHAGENT=OFF \
    -DWITH_XC_KEESHARE=OFF \
    -DWITH_XC_KEESHARE_SECURE=OFF \
    -DWITH_XC_UPDATECHECK=OFF \

Shared is for what?
Also why is Notes greyed out?

Operating system: Slackware 14.2
CPU architecture: x64
Kernel: 4.19.78

```I've attached a screen shot showing these 3 tabs.```

![share_tab](https://user-images.githubusercontent.com/36190223/66622073-e2f85e00-ebd5-11e9-91b1-c88e5fed0bff.jpg)

**Comment by droidmonkey** [comment]
Thats just a preview pane for the group. If there is nothing to see the tab gets disabled.

**Comment by 0pLuS0** [comment]
I asked before what is the ```Share``` tab doing there, what sharing?

THANKS

**Comment by droidmonkey** [comment]
Yes the share tab shows keeshare settings for the group if set up for sharing. Since you disabled it you'll never see information there. The folders on the left are called groups in KeePassXC and the items on the right side are called entries.

**Comment by 0pLuS0** [comment]
Hi,

I appreciate you taking the time to explain.

Since I disabled the Share feature, then this Share tab shouldn't even be displayed. Rhetorically speaking, why show something that doesn't even work, has been disabled, that seems odd.

You mentioned these as ```Entries```, if there are not entries then it would be nice to not have empty tabs appear that serve no function, but only appear when you have something in that Group, that to me makes the most sense...

Is there a way to disable this permanently? I really have no need for these tabs, I also see the ```Close``` button on the right, but once you click and close it, and then go back to the group it just appears again, that also doesn't make sense, I assumed it would then always remain close...

If you can remember these things to add in a new update it would be greatly appreciated, otherwise I can submit a ```Feature Request```?

THANKS

**Comment by 0pLuS0** [comment]
@droidmonkey 

SORRY ```Notes``` is perfectly fine to leave, I apologize for not paying attention better to this, and I greatly appreciated your time.

BUT having the ```Share``` tab showing up when I have ```KEESHARE``` disabled at compile time, that does seem like a BUG, and that if it's disabled at compile time should not be appearing, so can you please keep this report ```OPEN``` and in a future update when ```KEESHARE``` is disabled we do not get this Tab?

THANKS

**Comment by droidmonkey** [comment]
I agree with that

**Comment by 0pLuS0** [comment]
Ok I added this report for removing the Share Tab;

https://github.com/keepassxreboot/keepassxc/issues/3619
