### ISSUE TITLE
TOTP auto type keyword (e.g. `{TOTP}`)

### ISSUE THREAD

**Issue by owlnical** [keepassxreboot/keepassxc#3620]
## Summary

A function to include a TOTP in a auto-type sequence.

## Desired Behavior

In the auto-type section in entries there are settings to change the "Auto-Type sequence". `{PASSWORD}`, `{ENTER}` etc. If this entry also has TOTP setup it would like the possibility to add `{TOTP}`.

Example sequence: `{USERNAME}{TAB}{PASSWORD}{TOTP}{ENTER}`

## Possible Solution

Unfortunately I don't know how to solve this feature request.

## Context

A lot of the services I access with TOTP require the following fields:

1. username
2. password + TOTP (as in a single string with password and TOTP combined).

To login I do the following:

1. **Once**: remove the `{ENTER}` from the default auto-type sequence
2. Trigger auto-type on login fields
3. tab to keepassxc
4. copy TOTP
5. tab to application
4. Paste TOTP
5. login

So with this feature request I would be able to skip step 3 -> 5. :)

**Comment by droidmonkey** [comment]
This is already a keyword.

**Comment by owlnical** [comment]
No. Way. Of course someone has already thought of this! Thanks for the quick response.
