### ISSUE TITLE
Implement better handling of ports in browser integration

### ISSUE THREAD

**Issue by RolandSM** [keepassxreboot/keepassxc#3621]
Hello,
should the current KeePassXC with Firefox or Chrome extension handle different ports on same device (URL or IP).
On my local NAS I use some Docker Services and all are on different ports. Becaus its the same URL or Domain all Logins are shown on every service.
Greets

**Comment by droidmonkey** [comment]
Add the port to the url (e.g., https://example.com:5678) then ensure this setting is enabled in the application settings:

![image](https://user-images.githubusercontent.com/2809491/66718079-b303b300-edad-11e9-98e7-e29cdaf8cd99.png)

**Comment by varjolintu** [comment]
@droidmonkey The whole matching would need a refactoring. It has been almost the same since the KeePassHTTP implementation, and it could be improved a lot. I'll give it some thought.

**Comment by droidmonkey** [comment]
This might also be a place for the entry-specific settings to step in, or even at the group level.

**Comment by RolandSM** [comment]
Hello @droidmonkey 
yes, the checkbox in your image is active.
It would be nice if there is a better implementation for ports and subdomains.

**Comment by RolandSM** [comment]
Hello,
should this be fixed in 2.5.1?
Or was 2.5.1 only for the subdomain handling?
At the moment the port handling is not working with 2.5.1
I have an entry for:
1. my-nas.fritzbox -> opens NAS panel
2-5 my-nas.fritzbox:4000-4004 -> opens docker containers...

Both browser integrations on firefox and chrome insert only the 1. data, not the other. 
But the others stand also on ALLOW for the main url...

**Comment by varjolintu** [comment]
@RolandSM Can you test https://github.com/keepassxreboot/keepassxc/pull/3854? There's at least one test concerning this, and it works properly.

**Comment by RolandSM** [comment]
Hello,
when this PR is merged into master? Would this be in 2.5.2 and when will this come?
Or how can I test #3854?

**Comment by varjolintu** [comment]
@RolandSM https://snapshot.keepassxc.org/

**Comment by RolandSM** [comment]
Oh nice, the smaller font looks great!

But the port handling is not working...
my-nas.fritzbox -> opens NAS panel
my-nas.fritzbox:4000-4004 -> opens docker containers...

**Comment by varjolintu** [comment]
Just tested this with a local Python HTTP server site.

Entry without a port matches `http://localhost:8000/test.html`. If I change the entry URL using port 80, nothing will be matched. Switching the entry URL's port to 8000 matches the site correctly. So at least it's working for me.

**Comment by RolandSM** [comment]
Okay. I made also tests.
The point is, that I have an existing entry without port (standard 80) which leads to the original NAS control panel.
This entry matches also on the ones with port, as you also wrote, but this entry is wrong on the other ports!
I tried already to give the URL :80 but this is not working, because the browser cuts :80 and this one is not matching...

**Comment by varjolintu** [comment]
Currently there's no way to disable the non-port (or port 80) entry from appearing with entries with the port defined.

**Comment by RolandSM** [comment]
The point is, when the non port entry is active, no other with ports matches.
If I deactivate the nonport one the other is filled again.

If I can select on active non port it would be already a solution.

But without I am not able to get to the correct entry.

Perhaps a entry in deny list would be a solutions?
Allowed on localhost, denied on localhost:8000

**Comment by RolandSM** [comment]
Think this would be a nice Feature.
Solved for the moment with a change of the main control panel from port 80 to 8080 so no entry without port is existing...

**Comment by varjolintu** [comment]
You can try to achieve this by enablind the "Return only best-matching credentials" option.

**Comment by RolandSM** [comment]
Is already enabled...

**Comment by varjolintu** [comment]
And it still returns both entries for localhost:8000?
