### ISSUE TITLE
KeepassXC crashes after Win10 suspend/resume when kdbx is remote on smb3 share

### ISSUE THREAD

**Issue by ralkas** [keepassxreboot/keepassxc#3628]
I run KeepassXC 2.4.3 portable on Windows 10 with lates Updates. 

Both, the portable exe/directory and kdbx db and a key file are provided by a single smb3 share, served by samba 4.7.6 default config via smb3.1.1 protocol. Its hosted on a Ubuntu (buster/sid) Virtual Machine hosted on the same physical Windows 10 where I also start the exe and the network connection is local only (host only network). I use VMWare Workstation 12.5.9, but that should not matter. 

Do not ask why I can not put it directly on NTFS somewhere within windows itself, there are multiple reasons why I share data to my Native Windows from out of a VM hosted by that native Windows itself and that works fine for other applications.

Now my problem is:

- I put my Windows 10 Laptop into S3/Sleep (Close LID), while KeePassXC still running (locked with AutoSaveAfterEveryChange and BackupBeforeSave and UseAtomicSaves all true, so there should be no outstanding writes).
- then wake up the Laptop again, focus into the KeePassXC Window, enter my Password, it unlocks and I can start searching
- I search something and it is found
- I found the entry and try to edit it (CTRL-E) or just double click it or try to copy password (CTRL-C)
- KeepassXC just ends itself without anything in Windows Event Log - I can only restart it and it works fine

Its regardless on how long I wait after S3-Resume/Wakeup.

I thought its due to the fact that the SMB3 Share has to reconnect on Wakeup (its a stateful protocol), and I was too fast. But I monitored this and am sure that the network path is fully available before I start working with KeepassXC again. Maybe its kind of related to SMB LeaseLocks etc. However, I make sure I can fully access the Share before I attempt to use Keepass again after S3/resume  and even check the connection status using Powershell Get-SmbMapping and it shows ok. Still KeePassXC just ends itself without any further notice. Even when I access the SMB Share from Windows Explorer before and do something there (like any R/W IO to any file which works fine)

So my next attempt of tracing this down to a root cause, was to use sysinternals procmon to trace the keepassxc.exe and see what happens short before it just ends without notice, however, when I do this, timing seems to slightly change, its noticable that KeepassXC is slower while I have procmon tracing turned on. Now KeepassXC.exe does not just end itself anymore as before but I get at least an application error in windows event viewer and popup:

KeePassXC: Windows - Application Error : The instruction at 0x00000000004B91FF referenced memory at 0x0000000000662AEC. The required data was not placed into memory because of an I/O error status of 0xc00000c4.

NTSTATUS 0xc00000c4 is STATUS_UNEXPECTED_NETWORK_ERROR - so still this points somewhere to SMB3 reconnect issues. My next attempt would have been to packet-trace the SMB side to see where the STATUS_UNEXPECTED_NETWORK_ERROR is probably coming from. But I had no time to do this yet.

I think there is something within database-access or file locking code within KeepassXC that prevents continuous availability after a SMB3 session reconnect on Sleep/Resume.

Does anyone have the possibility to reproduce this or give any further advise? It would be great if KeepassXC could be made resilient against that kind of crash by some code changes.

The following is the last systemcall stack (captured from procmon.exe), before keepassxc.exe crashes. As mentioned above, I am not sure if this is the identical signature as when it would just crash silently. The Stack indicating relevance of autotype, but definitely I don't do any autotype stuff when it crashes, so this must be generic, the crash is directly after I double click the entry after it was found by using search:

0	FLTMGR.SYS	FltDecodeParameters + 0x1c5d	0xfffff8028570555d	C:\WINDOWS\System32\drivers\FLTMGR.SYS
1	FLTMGR.SYS	FltDecodeParameters + 0x17bc	0xfffff802857050bc	C:\WINDOWS\System32\drivers\FLTMGR.SYS
2	FLTMGR.SYS	FltDecodeParameters + 0x1328	0xfffff80285704c28	C:\WINDOWS\System32\drivers\FLTMGR.SYS
3	FLTMGR.SYS	FltDecodeParameters + 0x111e	0xfffff80285704a1e	C:\WINDOWS\System32\drivers\FLTMGR.SYS
4	dgmaster.sys	dgmaster.sys + 0x1fa4b	0xfffff802859bfa4b	C:\WINDOWS\system32\drivers\dgmaster.sys
5	ntoskrnl.exe	IofCallDriver + 0x59	0xfffff8027de8aba9	C:\WINDOWS\system32\ntoskrnl.exe
6	ntoskrnl.exe	KeCountSetBitsAffinityEx + 0x48a0	0xfffff8027df20600	C:\WINDOWS\system32\ntoskrnl.exe
7	ntoskrnl.exe	RtlSetAllBits + 0x1119	0xfffff8027de6e0d9	C:\WINDOWS\system32\ntoskrnl.exe
8	ntoskrnl.exe	RtlSetAllBits + 0x1a7d	0xfffff8027de6ea3d	C:\WINDOWS\system32\ntoskrnl.exe
9	ntoskrnl.exe	MmProbeAndLockPages + 0x4a7d	0xfffff8027deda46d	C:\WINDOWS\system32\ntoskrnl.exe
10	ntoskrnl.exe	setjmpex + 0x41e9	0xfffff8027dfd3bc9	C:\WINDOWS\system32\ntoskrnl.exe
11	KeePassXC.exe	ZN14AutoTypeActionD0Ev + 0x2699f	0x2b91ff	D:\KeePassXC\KeePassXC.exe
12	KeePassXC.exe	ZN14AutoTypeActionD0Ev + 0x2775c	0x2b9fbc	D:\KeePassXC\KeePassXC.exe
13	KeePassXC.exe	KeePassXC.exe + 0x6fb79	0x1efb79	D:\KeePassXC\KeePassXC.exe
14	KeePassXC.exe	KeePassXC.exe + 0x1fb4d	0x19fb4d	D:\KeePassXC\KeePassXC.exe
15	KeePassXC.exe	KeePassXC.exe + 0x339fc	0x1b39fc	D:\KeePassXC\KeePassXC.exe
16	Qt5Core.dll	Qt5Core.dll + 0x1e9199	0x66929199	D:\KeePassXC\Qt5Core.dll
17	Qt5Widgets.dll	Qt5Widgets.dll + 0x12d927	0xccd927	D:\KeePassXC\Qt5Widgets.dll
18	Qt5Core.dll	Qt5Core.dll + 0x1e9199	0x66929199	D:\KeePassXC\Qt5Core.dll
19	Qt5Widgets.dll	Qt5Widgets.dll + 0x1320f3	0xcd20f3	D:\KeePassXC\Qt5Widgets.dll
20	Qt5Widgets.dll	Qt5Widgets.dll + 0x132475	0xcd2475	D:\KeePassXC\Qt5Widgets.dll
21	Qt5Widgets.dll	Qt5Widgets.dll + 0x128ad8	0xcc8ad8	D:\KeePassXC\Qt5Widgets.dll
22	KeePassXC.exe	KeePassXC.exe + 0x1fdbb	0x19fdbb	D:\KeePassXC\KeePassXC.exe
23	KeePassXC.exe	KeePassXC.exe + 0x201d5	0x1a01d5	D:\KeePassXC\KeePassXC.exe
24	KeePassXC.exe	KeePassXC.exe + 0x339c6	0x1b39c6	D:\KeePassXC\KeePassXC.exe
25	Qt5Core.dll	Qt5Core.dll + 0x1e9199	0x66929199	D:\KeePassXC\Qt5Core.dll
26	Qt5Widgets.dll	Qt5Widgets.dll + 0x17a8be	0xd1a8be	D:\KeePassXC\Qt5Widgets.dll
27	Qt5Widgets.dll	Qt5Widgets.dll + 0x177aa1	0xd17aa1	D:\KeePassXC\Qt5Widgets.dll
28	Qt5Widgets.dll	Qt5Widgets.dll + 0x17ab4c	0xd1ab4c	D:\KeePassXC\Qt5Widgets.dll
29	KeePassXC.exe	KeePassXC.exe + 0x20710	0x1a0710	D:\KeePassXC\KeePassXC.exe
30	KeePassXC.exe	KeePassXC.exe + 0xbed7d	0x23ed7d	D:\KeePassXC\KeePassXC.exe
31	KeePassXC.exe	KeePassXC.exe + 0xbf9f1	0x23f9f1	D:\KeePassXC\KeePassXC.exe
32	KeePassXC.exe	KeePassXC.exe + 0x91f51	0x211f51	D:\KeePassXC\KeePassXC.exe
33	KeePassXC.exe	KeePassXC.exe + 0x36796	0x1b6796	D:\KeePassXC\KeePassXC.exe
34	Qt5Core.dll	Qt5Core.dll + 0x1e9199	0x66929199	D:\KeePassXC\Qt5Core.dll
35	Qt5Widgets.dll	Qt5Widgets.dll + 0x12d9c6	0xccd9c6	D:\KeePassXC\Qt5Widgets.dll
36	Qt5Core.dll	Qt5Core.dll + 0x1e9199	0x66929199	D:\KeePassXC\Qt5Core.dll
37	Qt5Widgets.dll	Qt5Widgets.dll + 0x13430c	0xcd430c	D:\KeePassXC\Qt5Widgets.dll
38	Qt5Widgets.dll	Qt5Widgets.dll + 0x126e8d	0xcc6e8d	D:\KeePassXC\Qt5Widgets.dll
39	Qt5Widgets.dll	Qt5Widgets.dll + 0x4558e	0xbe558e	D:\KeePassXC\Qt5Widgets.dll
40	Qt5Widgets.dll	Qt5Widgets.dll + 0x12d076	0xccd076	D:\KeePassXC\Qt5Widgets.dll
41	Qt5Widgets.dll	Qt5Widgets.dll + 0x7ab1	0xba7ab1	D:\KeePassXC\Qt5Widgets.dll
42	Qt5Widgets.dll	Qt5Widgets.dll + 0xf075	0xbaf075	D:\KeePassXC\Qt5Widgets.dll
43	Qt5Core.dll	Qt5Core.dll + 0x1c1b88	0x66901b88	D:\KeePassXC\Qt5Core.dll
44	Qt5Widgets.dll	Qt5Widgets.dll + 0x5e392	0xbfe392	D:\KeePassXC\Qt5Widgets.dll
45	Qt5Widgets.dll	Qt5Widgets.dll + 0x7ab1	0xba7ab1	D:\KeePassXC\Qt5Widgets.dll
46	Qt5Widgets.dll	Qt5Widgets.dll + 0xea04	0xbaea04	D:\KeePassXC\Qt5Widgets.dll
47	Qt5Core.dll	Qt5Core.dll + 0x1c2048	0x66902048	D:\KeePassXC\Qt5Core.dll
48	Qt5Gui.dll	Qt5Gui.dll + 0x340de	0x6640de	D:\KeePassXC\Qt5Gui.dll
49	Qt5Gui.dll	Qt5Gui.dll + 0x38d75	0x668d75	D:\KeePassXC\Qt5Gui.dll
50	Qt5Gui.dll	Qt5Gui.dll + 0x14b7c	0x644b7c	D:\KeePassXC\Qt5Gui.dll
51	Qt5Core.dll	Qt5Core.dll + 0x2155bf	0x669555bf	D:\KeePassXC\Qt5Core.dll
52	USER32.dll	USER32.dll + 0xca66	0x7ffac79eca66	C:\WINDOWS\System32\USER32.dll
53	USER32.dll	USER32.dll + 0xc582	0x7ffac79ec582	C:\WINDOWS\System32\USER32.dll
54	Qt5Core.dll	Qt5Core.dll + 0x21492b	0x6695492b	D:\KeePassXC\Qt5Core.dll
55	qwindows.dll	qwindows.dll + 0x78105	0x6dd38105	D:\KeePassXC\platforms\qwindows.dll
56	Qt5Core.dll	Qt5Core.dll + 0x1c04f5	0x669004f5	D:\KeePassXC\Qt5Core.dll
57	Qt5Core.dll	Qt5Core.dll + 0x1c91b5	0x669091b5	D:\KeePassXC\Qt5Core.dll
58	KeePassXC.exe	KeePassXC.exe + 0x1edd4b	0x36dd4b	D:\KeePassXC\KeePassXC.exe
59	KeePassXC.exe	KeePassXC.exe + 0x13a5	0x1813a5	D:\KeePassXC\KeePassXC.exe
60	KeePassXC.exe	KeePassXC.exe + 0x14db	0x1814db	D:\KeePassXC\KeePassXC.exe
61	KERNEL32.DLL	KERNEL32.DLL + 0x17974	0x7ffac56d7974	C:\WINDOWS\System32\KERNEL32.DLL
62	ntdll.dll	ntdll.dll + 0x6a271	0x7ffac846a271	C:\WINDOWS\SYSTEM32\ntdll.dll

**Comment by ralkas** [comment]
![procmon](https://user-images.githubusercontent.com/34063633/66923788-c327c680-f029-11e9-9698-a8a1bfd4b2a8.png)

**Comment by phoerious** [comment]
Does the same happen if you disable "Automatically reload the database when modified externally"?

**Comment by droidmonkey** [comment]
Does the same happen if you are running KeePassXC on the local machine versus through the SMB share?

**Comment by ralkas** [comment]
@droidmonkey no, with local storage it works fine even after S3suspend/resume

@phoerious yes, the first attempt with that option disabled, triggered a silent crash right away when I attempted to search instead of clicking a result and teh crash signature in procmon looks a bit different with similar "NETWORK ERROR" ib libicuuc64.dll

![procmon2](https://user-images.githubusercontent.com/34063633/66928374-92e42600-f031-11e9-9880-ed2acfff0578.png)
