### ISSUE TITLE
Global auto type stopped working on Mac Catalina

### ISSUE THREAD

**Issue by m9769k** [keepassxreboot/keepassxc#3629]
am on Keepass 2.4.3 and everything was working fine on Mac Mojave. Once I upgraded to Catalina, am getting the following error message
"Couldn't find an entry that matches the window title:" 

## Expected Behavior
Expect the Global auto type to work

## Current Behavior
[NOTE]: # Getting an error message once I invoke GLobal auto type short cut
"Couldn't find an entry that matches the window title:"

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1.
2.
3.

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION
Revision: REVISION

Libraries:
- LIBS

Operating system: OS
CPU architecture: ARCH
Kernel: KERNEL

Enabled extensions:
- EXTENSIONS

**Comment by droidmonkey** [comment]
This is fixed for 2.5.0 coming out soon

**Comment by dimarudik** [comment]
Hi, still doesn't work

**Comment by nolimitcarter** [comment]
^
