### ISSUE TITLE
Allow to Auto-Type entry password or username from selection dialog

### ISSUE THREAD

**Issue by SebiderSushi** [keepassxreboot/keepassxc#3630]
[TIP]:  # ( Provide a general summary of the feature in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Summary
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
Per default, auto-type enters username, tab, password, then enter.
The requested feature should be a user-friendly way to customize this behavior on-the-fly and as needed whenever something else is required by the user.

## Desired Behavior
[NOTE]: # ( Tell us how the new feature should work, be specific )
KeePassXC should offer a user-friendly way to quickly select and auto-type any single attribute of a password entry. This would already make the feature sufficient, but to take things further, KeePassXC might as well offer the possibility to customize an auto type sequence based on certain temporary requirements.

## Possible Solution
[NOTE]: # ( Not required, but suggest ideas on how to implement the addition or change )
The former can be accomplished by adding a new option in the right click menu of a password entry. It could be called "Auto-type attribute" and should work similar to "Copy attribute...".

The latter could be accomplished using "Auto-type profiles". I.E. KeePassXC would offer the ability to define multiple, named auto-type sequences, either globally or for a specific entry. These could also be selected on-the-fly in the right-click menu of a password entry.
Using this feature, a user could create the global sequence `{PASSWORD}{TAB}{PASSWORD}` and use it whenever a password change on a website requires typing the new password twice.

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
When changing their password, a user is confronted with a differend promt than the usual login, mostly requiring the old password, then the new one twice.

Apart from that, the user might want to use an attribute from a password entry that should not enter the clipboard area.

As far as i know, Auto-type can only be used to meet these circumstances if the user is willing to make a significant effort, as KeePassXC currently just offers the following features to deal with this scenario:
- Temporarily override the auto type sequence by hand, in order to match the current requirements
- Define Window associations to try and match the window title present in the affected situation. This can be impossible, since the title is likely the same for e.g. login and password change on a website.

As these circumstances can occur quite frequently, this effort should be reduced.

**Comment by droidmonkey** [comment]
This is a great proposal, I find myself in this awkward situation commonly that you describe. I think this would be best implemented through a separate global shortcut that brings up an attribute picker instead of executing the defined Auto-Type sequence.

**Comment by jonzyk** [comment]
+1 for this. Useful when application saves the username, to autotype only the password.

**Comment by JeanBarry** [comment]
Agree, this is a great idea that could be useful in many cases.
