### ISSUE TITLE
macOS 10.15: global auto-type broken because KeePassXC can't read the current window title

### ISSUE THREAD

**Issue by Tobi823** [keepassxreboot/keepassxc#3631]
I guess that KeePassXC has not the permission to do that.

![Screenshot 2019-10-16 at 10 56 12](https://user-images.githubusercontent.com/10066140/66993802-85c84500-f0cc-11e9-8202-ac47ccbe3eaf.png)
![Screenshot 2019-10-16 at 10 56 19](https://user-images.githubusercontent.com/10066140/66993817-8b258f80-f0cc-11e9-9c40-8c833f752b3f.png)

## Expected Behavior
After pressing the key shortcut for global auto-type (In my case: ctrl+alt+m), KeePassXC should read the window title of the currently active window. 

## Current Behavior
KeePassXC always reads the window title of the KeePassXC-window. 

## Possible Solution
MacPass 0.7.9 was also effected - when I try to auto-type with MacPass, I got the message `No Match for (null)!`. Then I discovered this issue https://github.com/MacPass/MacPass/issues/948. 

In MacPass `Continuous 2019-09-17`, the app asks for "Screen Recording" permission. After granting the permission, auto-type works again.

## Steps to Reproduce
1. Install macOS Catalina
2. Open a database and enable global auto-type
3. Try to global auto-type in any other window (like Safari, Firefox, etc.)

## Context
Result: I don't want to use the browser plugin. I only use global auto-type to log into my accounts like Github, Gitlab etc. Without a working global auto-type, I have to manually copy+paste the username+password.

## Debug Info
KeePassXC - Version 2.4.3
Revision: 5d6ef0c

Qt 5.12.3
Debugging mode is disabled.

Operating system: macOS 10.15
CPU architecture: x86_64
Kernel: darwin 19.0.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
 libgcrypt 1.8.4

Libraries:
- LIBS

**Comment by droidmonkey** [comment]
Already fixed in develop and this is a duplicate issue.
