### ISSUE TITLE
Some translation strings don't work

### ISSUE THREAD

**Issue by eson57** [keepassxreboot/keepassxc#3632]
Hi,
While trying to fix Swedish translation I found the following not working/missing translation strings.

## Expected Behavior
[NOTE]: # GUI translated into Swedish

## Current Behavior
[NOTE]: # Some strings don't translate and some strings missing

## Possible Solution
[NOTE]: # Correct source strings for not working translation and add missing strings

These are not working strings:

- keepassx_sv.ts:114: <source>Remember last databases</source>
- keepassx_sv.ts:118: <source>Remember last key files and security dongles</source>
- keepassx_sv.ts:122: <source>Load previous databases on startup</source>
- keepassx_sv.ts:201: <source>Language</source>
- keepassx_sv.ts:235: <source>Check for updates at application startup</source>
- keepassx_sv.ts:239: <source>Include pre-releases when checking for updates</source>
- keepassx_sv.ts:250: <source>Button style</source>
- keepassx_sv.ts:329: <source>Use DuckDuckGo as fallback for downloading website icons</source>

These are missing strings:

- keepassx_sv.ts:253: <source>(restart program to activate)</source>
- keepassx_sv.ts:519: <source>&amp;Allow returning expired credentials.</source>

**Comment by phoerious** [comment]
Please complete translations on Transifex.

**Comment by eson57** [comment]
That was exactly what I was doing, but I can't correct source strings at Transifex, can I?
Strings above is not correct or missing.

**Comment by droidmonkey** [comment]
The source needs to be updated

**Comment by eson57** [comment]
> The source needs to be updated

Exactly my point. Will you do it your self or do you prefer a PR? I already have a working sv.ts, but I don't really know how to make it "all languages source".

**Comment by droidmonkey** [comment]
We update it before release. Once a couple more PR's are merged with new strings I'll update it

**Comment by phoerious** [comment]
The update is fully automated. No need for manual pull requests.
