### ISSUE TITLE
toolbar icon not displaying

### ISSUE THREAD

**Issue by oddysey** [keepassxreboot/keepassxc#3633]
## Expected Behavior
toolbar icon to display the KeePassXC logo instead of a blank white sheet of paper.

## Current Behavior
Instead of toolbar icon, blank white sheet of paper is displayed

## Possible Solution
Not sure

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1. Updated to 2.4.3 
2. Run application
3. view application toolbar icon

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )
It affects me in the sense that it's hard to tell where my KeePassXC window is because I don't have the correct toolbar icon to identify it by.

## Debug Info
KeePassXC - Version 2.4.3
Revision: 5d6ef0c

Qt 5.12.3
Debugging mode is disabled.

Operating system: Windows 10 (10.0)
CPU architecture: x86_64
Kernel: winnt 10.0.17763

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.4

**Comment by droidmonkey** [comment]
Try unpinning and repinning the application

**Comment by oddysey** [comment]
It wasn’t pinned to the taskbar to begin with, but pinning and re-pinning happened to fix it. Thanks!


Thanks,

William Smyth

**Comment by oddysey** [comment]
The icon disappears only when pinned to tool/taskbar. Unpinned it shows the correct icon.


Thanks,

William Smyth

**Comment by xPaw** [comment]
I'm having the same issue.

I don't have keepass pinned to taskbar, but opening it shows white paper icon. Pinning and unpinning fixes it until the app is closed.

This only started hapenning for me after upgarding to 2.5
