### ISSUE TITLE
Lock databases when remote session mode changes

### ISSUE THREAD

**Issue by rocwhite168** [keepassxreboot/keepassxc#3635]
## Summary
Offer an option to lock databases when remote session mode changes.

## Desired Behavior
Detect when someone logs into the machine remotely (via Windows Remote Desktop, VNC, TeamViewer) and lock databases.

## Context
I lock my session frequently whenever I step out of my office, and I don't want to lock databases and re-enter the (complex) master password every time I do so. I assume that people in my building will not (or will not have enough time to) try to guess my computer password. However, since my computers are kept on almost all the time, being able to lock whenever the remote control mode is changed would be very useful (for fear of being hacked).

I recently discovered KeePassXC after wanting to use my KeePass database in Linux. I quickly converted even in Windows. However, this is one of the features I missed most. Another is the ability to synchronize two databases easily, which according to what I read is being worked on in some fashion with KeeShare. The last feature I think it's quite neat is auto completing when typing the name of an Additional Attribute, which I'm creating in another feature request.

**Comment by droidmonkey** [comment]
I don't think this is possible? Especially with third party clients.

**Comment by rocwhite168** [comment]
@droidmonkey Very likely so. KeePass only handles Windows Remote Desktop (under Windows of course). I was just laying out the ideal case there in case anyone knows a way to achieve it.

**Comment by droidmonkey** [comment]
Yes RDP pushes out an event, couldn't find the actual developer resource but found that event(s) are produced when connecting.

**Comment by rocwhite168** [comment]
I'm not sure about KeePassXC's user composition, but I think ~80% desktop users are running Windows. And this feature would be a really nice, sane security default for this big population of users.

**Comment by droidmonkey** [comment]
That may be true but likely 1-5% of that 80% have RDP access to their computers enabled for third parties to "get into". I am not including enterprise environments.

**Comment by rocwhite168** [comment]
That's a statistics we don't have. I understand in such cases our estimates tend to be dramatically influenced by our individual experience and priorities. I certainly _feel_ that KeePassXC users would be more advanced type of computer users (compared to say everyone or LastPass users) and that there would be a much bigger fraction of them using RDP, but that might just be because I use it myself :) I'll just keep this open in case anyone wants to pick it up.

**Comment by droidmonkey** [comment]
We won't be implementing this, the remote session should lock the "screen" when disconnected which will lock the database. Either that or set a timed lock.
