### ISSUE TITLE
Lost search bar section in the UI for MacOS release

### ISSUE THREAD

**Issue by witnsby** [keepassxreboot/keepassxc#3637]
Main problem is Lost search bar section in the UI for MacOS release

KeePassXC - Version 2.4.3
Revision: 5d6ef0c

Qt 5.12.3
Debugging mode is disabled.

Operating system: macOS 10.15
CPU architecture: x86_64
Kernel: darwin 19.0.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
 libgcrypt 1.8.4

**Comment by droidmonkey** [comment]
Screenshot please, I have no idea what you mean

**Comment by witnsby** [comment]
<img width="1270" alt="Screen Shot 2019-10-18 at 20 45 52" src="https://user-images.githubusercontent.com/36894731/67116374-f2d0fd00-f1e8-11e9-990c-2b917aa959ba.png">
<img width="1273" alt="Screen Shot 2019-10-18 at 20 42 09" src="https://user-images.githubusercontent.com/36894731/67116376-f2d0fd00-f1e8-11e9-9c48-0b0d8b43feb5.png">

I've attached 2 images where the first is from 2.3.4 release and the second one is 2.4.3

**Comment by droidmonkey** [comment]
![image](https://user-images.githubusercontent.com/2809491/67117702-5b9c8300-f1b1-11e9-85f4-170ad50dfb27.png)

**Comment by witnsby** [comment]
WOW. I'm so stupid )) thanks
Though I can't find anything in my BD when I marked to hide toolbar (I regarded the hotfey command+f should work)

**Comment by witnsby** [comment]
I'm not sure but U can close my bug. If I uncheck hide toolbar I see search bar and, additionally, can use hot key for search my records.
it is enough me.

**Comment by droidmonkey** [comment]
There was a period of time when you could right click on the toolbar itself to hide it... and hiding it was actually broken. So when you updated you could have had that option set unknowingly and the fix made it actually disappear.
