### ISSUE TITLE
Global Auto-Type key option is missing in preferences

### ISSUE THREAD

**Issue by jaltek** [keepassxreboot/keepassxc#364]
## Expected Behavior
Ability to set the global Auto-Type key combination in the application settings menu.

## Current Behavior
The option to set the global Auto-Type key combination is missing in the preferences.
There is also no ```GlobalAutoTypeKey``` in ```~/.config/keepassxc/keepassxc.ini```

## Your Environment
* KeePassXC version/commit used: ```Revision: b9279f73fa58d75e1ec88f734f3c77c0f015a348```
* Qt version (e.g. Qt 5.3): ```Qt 5.7.1```
* Operating System and version: openSUSE Tumbleweed

## Screenshot
![selection_263](https://cloud.githubusercontent.com/assets/359552/23505440/05b7f300-ff44-11e6-8a8a-7f73a988e4ea.png)

**Comment by droidmonkey** [comment]
Did you run cmake using ```-DWITH_XC_AUTOTYPE=ON```?

**Comment by jaltek** [comment]
I'm using this openSUSE repo:

https://build.opensuse.org/package/show?project=security&package=keepassxc

According to the [RPM spec](https://build.opensuse.org/package/view_file/security/keepassxc/keepassxc.spec?expand=1) the flag is set, yes.

**Comment by jaltek** [comment]
Side-note: This is the build log:

https://build.opensuse.org/package/live_build_log/security/keepassxc/openSUSE_Tumbleweed/x86_64

**Comment by TheZ3ro** [comment]
Seems that the RPM spec is missing 2 dependencies for autotype: `libxi libxtst` (maybe on openSuse they have different names)

**Comment by phoerious** [comment]
We should start generating CMake errors when Auto-Type is enabled, but libxi and libxtst are missing. People keep reporting these kinds of issues.

**Comment by jaltek** [comment]
Filed a bug at openSUSE bug tracker.

https://bugzilla.opensuse.org/show_bug.cgi?id=1027653

Thank you guys for your help.

**Comment by phoerious** [comment]
Thanks! I'll close this one here.

**Comment by TheZ3ro** [comment]
@phoerious 

> We should start generating CMake errors when Auto-Type is enabled, but libxi and libxtst are missing. People keep reporting these kinds of issues.

I think it's a good idea...
