### ISSUE TITLE
macOS Catalina: Global Autotype not working with "couldn't find and entry that matches the window title - KeePassXC"

### ISSUE THREAD

**Issue by maltokyo** [keepassxreboot/keepassxc#3640]
## Expected Behavior
Using Global Autotype, with DB unlocked in the background, when in browser with the login screen for a site open, I press global auto-type key combo, it should search my KeePassXC DB for an entry according to the URL or site name in the browser. 

## Current Behavior
Using Global Autotype, with DB unlocked in the background, when in browser with the login screen for a site open, I press global auto-type key combo, and get the message that it cannot find a match from the KeePassXC app screen! (not the browser, where it should be looking!)
See screenshot here:

## Screenshot
![image](https://user-images.githubusercontent.com/1388507/67145158-45f58f00-f27f-11e9-8736-d0f029854584.png)

## Debug Info
KeePassXC - Version 2.4.3
Revision: 5d6ef0c

Qt 5.12.3
Debugging mode is disabled.

Operating system: macOS 10.15
CPU architecture: x86_64
Kernel: darwin 19.0.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
 libgcrypt 1.8.4

**Comment by droidmonkey** [comment]
Already fixed in develop branch

**Comment by maltokyo** [comment]
How can I use that?

**Comment by maltokyo** [comment]
@droidmonkey do inneed to wait until it’s released, or some way I can use (as an non developer user)

**Comment by droidmonkey** [comment]
https://snapshot.keepassxc.org/latest
