### ISSUE TITLE
Compiling from source but not getting an Auto-Type tab in Settings

### ISSUE THREAD

**Issue by pespinoz** [keepassxreboot/keepassxc#3642]
Hi. I'm compiling keepassxc 2.4.3 from source in an Ubuntu 19.04 system with:
`cmake -DWITH_XC_ALL=ON -DCMAKE_BUILD_TYPE=Release -DWITH_TESTS=ON -DWITH_GUI_TESTS=ON ..`

With the DWITH_XC_ALL=ON, I would expect the autotype feature to be enabled. The output of the above command shows:
`-- Enabled features:
 Auto-Type, Automatic password typing
`

However, after installation (with no errors), I only get a 'Basic Settings' tab in the Settings Section. But no 'Auto-Type' tab next to it, as I would expect. Thanks.
![Screenshot from 2019-10-19 12-56-40](https://user-images.githubusercontent.com/28991434/67149765-f90cbb00-f274-11e9-878e-ad58c8825732.png)

**Comment by droidmonkey** [comment]
That's interesting, did the build process produce a `libkeepassx-autotype.so` library at all? It would be under build/src/autotype

**Comment by pespinoz** [comment]
The folder build/src/autotype/ exists, but its contents are:  
CMakeFiles/,    cmake_install.cmake,    CTestTestfile.cmake,    Makefile,    test/

In test/, there's a file called: libkeepassx-autotype-test.so
Do you think I could execute the code in build/src/autotype/ individually?

**Comment by droidmonkey** [comment]
Try doing `make autotype`

**Comment by pespinoz** [comment]
It ran but it didn't help nor it created the libkeepassx-autotype-xcb.so file. Thanks for the suggestion though, it's puzzling.

**Comment by droidmonkey** [comment]
Yah this is strange

**Comment by droidmonkey** [comment]
This is what I see after building on Ubuntu 19.04

![image](https://user-images.githubusercontent.com/2809491/67161965-90cde000-f32d-11e9-9bf5-c90439e81b09.png)

I installed to the ./deploy folder to make it easier to see what is going on. Running keepassxc yields autotype capability.

**Comment by pespinoz** [comment]
Yes, building keepassxc from source does yield autotype capability... I just installed it in a second Ubuntu 19.04 machine and it worked without problems. On the original machine, I couldn't troubleshoot it and ended up installing the apt version which worked as well. Thanks for the help.

**Comment by phoerious** [comment]
You might be missing the required runtime dependencies. Please check our GitHub wiki for more details.
