### ISSUE TITLE
AutoType not working after upgrading to macOS Catalina

### ISSUE THREAD

**Issue by vikdean** [keepassxreboot/keepassxc#3647]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Current Behavior
[NOTE]: # ( Tell us what actually happens )
AutoType was working perfectly before the upgrade, but now its not. When I hit the AutoType shortcut, nothing happens, it seems that it cannot find the window title or something.
Same thing happened with MacPass: https://github.com/MacPass/MacPass/issues/981

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.4.3
Revision: 5d6ef0c

Qt 5.12.3
Debugging mode is disabled.

Operating system: macOS 10.15
CPU architecture: x86_64
Kernel: darwin 19.0.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
 libgcrypt 1.8.4

**Comment by droidmonkey** [comment]
Fixed already in develop

**Comment by qauff** [comment]
I've updated to 2.5.0 and I don't think this is fixed. When I hit the Auto-Type global shortcut, I get this error: 

```
Couldn't find an entry that matches the window title:

<DATABASE NAME> - KeePassXC
```

This will happen regardless of app I'm hitting the shortcut in. In my latest scenario, it's in Safari. Previous versions of macOS if KeePassXC couldn't find the entry, it would have the window title of the application I hit the shortcut key from, not the window title of KeePassXC.

**Comment by droidmonkey** [comment]
You need to give KeePassXC screen reader permission

**Comment by qauff** [comment]
@droidmonkey ah. thanks for that!
