### ISSUE TITLE
No Auto-Type with QT_QPA_PLATFORM=wayland (Fedora 31)

### ISSUE THREAD

**Issue by mabachel** [keepassxreboot/keepassxc#3648]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Expected Behavior
Even with QT_QPA_PLATFORM=wayland KeePassXC should have Auto-Type

## Current Behavior
There is no Auto-Type button present and Ato-Type shortcut has no effect.

Also copy to clipboard of Debug Info does not work with QT_QPA_PLATFORM=wayland

## Steps to Reproduce
1. open terminal
2. enter export `QT_QPA_PLATFORM=wayland`
3. enter `keepassxc`
4. Try to use Auto-Type

## Context
This is going to be in Fedora 31:
https://fedoraproject.org/wiki/Changes/Qt_Wayland_By_Default_On_Gnome

## Debug Info
KeePassXC - Version 2.4.3
Revision: 5d6ef0c

Qt 5.12.5
Debugging mode is disabled.

Operating system: Fedora 30 (Workstation Edition) with QT_QPA_PLATFORM=wayland but on Fedora 31 by default
CPU architecture: x86_64
Kernel: linux 5.3.6-200.fc30.x86_64

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.5

**Comment by phoerious** [comment]
Wayland does not allow Auto-Type. Right now, there is no known solution for this. I'm closing this, since its a known issue and we are already tracking similar requests elsewhere.
