### ISSUE TITLE
keepassxc as libsecret provider/daemon makes emacs hang/time out on dbus connection

### ISSUE THREAD

**Issue by hrehfeld** [keepassxreboot/keepassxc#3667]
Since switching to keepassxc as my libsecret daemon (as soon as the commit was pushed a few months ago), secrets in emacs have stopped working.

## Expected Behavior
List passwords in the keepass password database (="Keyring") folder (="Keyring") that's marked as exposed to libsecret.

## Current Behavior
Emacs times out with 

```
Debugger entered--Lisp error: (dbus-error "call timed out")
  signal(dbus-error ("call timed out"))
  dbus-call-method(:session "org.freedesktop.secrets" "/org/freedesktop/secrets" "org.freedesktop.Secret.Service" "OpenSession" "plain" (:variant ""))
  secrets-open-session()
  secrets-get-items("/org/freedesktop/secrets/collection/keyring")
  secrets-list-items("Keyring Login")
  eval((secrets-list-items "Keyring") nil)
  elisp--eval-last-sexp(nil)
  eval-last-sexp(nil)
  funcall-interactively(eval-last-sexp nil)
  call-interactively(eval-last-sexp nil nil)
  command-execute(eval-last-sexp)

```

## Possible Solution
python-keyring stopped working as well, iirc because it assumed different keys in the exposed data?
Because that stopped working, I wrote my own minimal implementation : https://github.com/hrehfeld/python-keyring-minimal/blob/master/keyring

## Steps to Reproduce
1. create a db named Keyring, expose a folder via libsecret
2. `emacs -Q`
3. eval (C-x C-e): `(require 'secrets)`
4. eval: `(secrets-list-items "Keyring")`

## Context
GNU Emacs 26.3 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.10) of 2019-08-29

## Debug Info
```
KeePassXC - Version 2.5.0-snapshot
Build Type: Snapshot
Revision: 6ae27fa

Qt 5.13.1
Debugging mode is disabled.

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 5.3.7-arch1-1-ARCH

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.5

```

**Comment by Aetf** [comment]
`python-keyring` is working fine here and actually that's the tool I used for debugging in development. If you have more info about the error I may be able to fix it.

For emacs, could you help me debug the error since I'm not familiar with emacs at all? It looks like either no one is listening on the DBus, or something bad happened in KeepassXC that it can't even send back an error reply.

The following command checks for the first situation and it should print `string "org.freedesktop.secrets"` if KeepassXC is listening
```
dbus-send --session --dest=org.freedesktop.DBus --type=method_call --print-reply  /org/freedesktop/DBus org.freedesktop.DBus.ListNames | grep 'org.freedesktop.secrets'
```

When doing step 4, have the following command running to capture all dbus messages related to libsecret. Note that the password will be captured so use a new db.
```
dbus-monitor "interface='org.freedesktop.Secret.Service'" "interface='org.freedesktop.Secret.Collection'" "interface='org.freedesktop.Secret.Item'" "interface='org.freedesktop.Secret.Prompt'" > dbus.log
```

**Comment by hrehfeld** [comment]
1. command works fine.
2. command output:

    $ dbus-monitor "interface='org.freedesktop.Secret.Service'" "interface='org.freedesktop.Secret.Collection'" "interface='org.freedesktop.Secret.Item'" "interface='org.freedesktop.Secret.Prompt'"
    signal time=1572340258.106216 sender=org.freedesktop.DBus -> destination=:1.255 serial=2 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameAcquired
       string ":1.255"
    signal time=1572340258.106272 sender=org.freedesktop.DBus -> destination=:1.255 serial=4 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameLost
       string ":1.255"
    method call time=1572340266.011337 sender=:1.257 -> destination=org.freedesktop.secrets serial=4 path=/org/freedesktop/secrets; interface=org.freedesktop.Secret.Service; member=OpenSession
       string "plain"
       variant       string ""
    method call time=1572340291.020592 sender=:1.257 -> destination=org.freedesktop.secrets serial=11 path=/org/freedesktop/secrets; interface=org.freedesktop.Secret.Service; member=ReadAlias
       string "Keyring"
    method call time=1572340291.024260 sender=:1.257 -> destination=org.freedesktop.secrets serial=14 path=/org/freedesktop/secrets; interface=org.freedesktop.Secret.Service; member=Unlock
       array [
          object path "/org/freedesktop/secrets/collection/keyring_2Donline"
       ]
    method call time=1572340291.027924 sender=:1.257 -> destination=org.freedesktop.secrets serial=17 path=/org/freedesktop/secrets/prompt/<someid>; interface=org.freedesktop.Secret.Prompt; member=Prompt
       string "<string>"
    signal time=1572340291.028278 sender=:1.20 -> destination=(null destination) serial=1101 path=/org/freedesktop/secrets/prompt/<someid>; interface=org.freedesktop.Secret.Prompt; member=Completed
       boolean false
       variant       array [
          ]
    method call time=1572340291.030431 sender=:1.257 -> destination=org.freedesktop.secrets serial=19 path=/org/freedesktop/secrets; interface=org.freedesktop.Secret.Service; member=OpenSession
       string "plain"
       variant       string ""

**Comment by hrehfeld** [comment]
Also, testing is quite easy. Just install emacs, and then:


    $ emacs -Q --eval "(progn (require 'secrets) (secrets-list-items \"Keyring\"))" 

Replace Keyring with the name of your keyring.

**Comment by hrehfeld** [comment]
How do you use python-keyring? 

```
/usr/bin/keyring get 'Keyring' '<my entry title>'
```

or

```
/usr/bin/keyring get '<my entry title>' '<my username>'
```

Just doesn't work.

**Comment by hrehfeld** [comment]
If you want to see emacs backtraces, use:

```
$  emacs -Q --eval "(progn (toggle-debug-on-error) (require 'secrets) (secrets-list-items \"Keyring\"))"  
```

(foo a b) is a function call

(progn BODY...) just evaluates some expressions and returns the result of the lastone, i.e. converts a list of expressions to a single expression

**Comment by Aetf** [comment]
I just fixed an error causing no reply gets sent when opening non-encrypted sessions, could you try my branch at https://github.com/Aetf/keepassxc/tree/fdo-secrets-fixes?

**Comment by hrehfeld** [comment]
Seems to work!

**Comment by Aetf** [comment]
Great! What about `python-keyring`? Does it work for you now?

**Comment by hrehfeld** [comment]
`python-keyring` works only if I manually add the custom properties `service` and `username`. The usual ui field for username exposes on libsecret as `UserName`, and service is not present :frowning_face:

**Comment by Aetf** [comment]
In the Freedesktop Secret Storage standard, an secret entry contains a textual `Label` (maps to title) and a binary secret data (maps to password if `plain/text`, protected attachment otherwise). All other things are custom attributes which are completely up to the application to interpret. For example, some applications may don't have the notion of an user name and just wants to save a secret key.

So in general, while everything is in the same database, there's little we can expect for interoperability among entries created by different applications.

**Comment by hrehfeld** [comment]
Yep, but wouldn't it a good idea to emulate what gnome-keyring, etc. is doing instead of reinventing key names?

**Comment by hrehfeld** [comment]
(feel free to close this once #3761 is merged.)

**Comment by Aetf** [comment]
> Yep, but wouldn't it a good idea to emulate what gnome-keyring, etc. is doing instead of reinventing key names?

I wanted the same thing but `gnome-keyring` isn't doing anything special in this regard. It's just a daemon saving whatever attributes other applications give to it. I checked a few existing applications:

- Seahorse set the description as the label, and sets an additional `xdg:schema` => `org.gnome.keyring.Note` when creating passwords through UI.
- Secret-tool lets you specify the label, and any additional attributes.
- Chrome saves its secrets with `application` => `chrome` and `xdg:schema` => `chrome_libsecret_os_crypt_password_v2`
- python-keyring uses `application` => `Python keyring library`, `service`, and `username`

So there seems not to be a consistent usage of attributes in existing applications :(

I'm open to suggestions to improve the compatibility though.

**Comment by Aetf** [comment]
Fixed by #3761

**Comment by hrehfeld** [comment]
Awesome, it seems to work now. Thanks a bunch! :+1:

**Comment by hpfr** [comment]
@hrehfeld sorry to resurrect this old issue, but I figured you might have unique experience with Emacs and KeePassXC's secret service and I wanted to capitalize on the "emacs libsecret keepassxc" SEO here for others. I'm having issues with it. While I seem to be able to read from my collection, I cannot write to it. My database is called "Main". Evaluating `(secrets-create-item "Main" "test emacs item" "test pw")` returns `D-Bus error: "No such method 'CreateItem' in interface 'org.freedesktop.Secret.Collection' at object path '/org/freedesktop/secrets/collection/main' (signature 'gibberish')`, where I replaced some strange characters with `gibberish` in case they are related to secrets somehow.

@Aetf I know nothing about D-Bus, but the above works for me on a Gnome system with Gnome Keyring and I noticed that Gnome Keyring writes some dbus service files:  [org.freedesktop.impl.portal.Secret.service](https://gitlab.gnome.org/GNOME/gnome-keyring/-/blob/18a58e6344bfab6f4036f9e0f128e7bc7ed0a317/daemon/org.freedesktop.impl.portal.Secret.service.in) and [org.freedesktop.secrets.service](https://gitlab.gnome.org/GNOME/gnome-keyring/-/blob/18a58e6344bfab6f4036f9e0f128e7bc7ed0a317/daemon/org.freedesktop.secrets.service.in). Would this be causing the above error?

The ["session" collection](https://github.com/emacs-mirror/emacs/blob/898a94a9be06a3ab51116778f6b4a263f832759d/lisp/net/secrets.el#L80) emacs normally creates to last the lifetime of an emacs session also doesn't seem to exist like it would on a system running Gnome Keyring. When I try to create a collection with `(secrets-create-collection "test")`, KeePassXC prompts me to create a database, so maybe this has something to do with it. Does the FDO Secrets API specify a way to create a temporary collection headlessly that KeePassXC doesn't implement?

It seems like the KeePassXC implementation of the Secret Service API might be missing some things here? Thanks for any insight you can provide!

**Comment by Aetf** [comment]
@hpfr 

> D-Bus error: "No such method 'CreateItem' in interface 'org.freedesktop.Secret.Collection' at object path '/org/freedesktop/secrets/collection/main' (signature 'gibberish'), where I replaced some strange characters with gibberish in case they are related to secrets somehow.

The signature encodes the method argument types emacs tying to call. It's likely that emacs somehow called the method with wrong arguments and thus the method not fount error.


> Gnome Keyring writes some dbus service files: org.freedesktop.impl.portal.Secret.service and org.freedesktop.secrets.service. Would this be causing the above error?

Those service files should not be required for the service to function.

> The "session" collection emacs normally creates to last the lifetime of an emacs session also doesn't seem to exist like it would on a system running Gnome Keyring. When I try to create a collection with (secrets-create-collection "test"), KeePassXC prompts me to create a database, so maybe this has something to do with it. Does the FDO Secrets API specify a way to create a temporary collection headlessly that KeePassXC doesn't implement?
> It seems like the KeePassXC implementation of the Secret Service API might be missing some things here?

Unfortunately the [spec](https://specifications.freedesktop.org/secret-service/latest/index.html) doesn't include the session collection or any other temporary collection whose lifetime is tied to an application's session. That's purely a Gnome keyring thing. KeePassXC implements the full spec (with some caveats in searching a locked db #4443).
