### ISSUE TITLE
TouchID does not work with key file only in 2.5.0

### ISSUE THREAD

**Issue by gyli** [keepassxreboot/keepassxc#3674]
## Expected Behavior
After touching, database should be unlocked.

## Current Behavior
With key file only and no password, after touching TouchID, it pops up "you did not enter a password".

## Possible Solution
Open with TouchID should support all credentials, including password only, key file only, combination, etc.

## Steps to Reproduce
1. Set database with key file only credentials
2. Check open with TouchID when opening DB
3. Lock DB and try to re-open it through TouchID
4. Touch TouchID
5. It will pop up
<img width="424" alt="Screen Shot 2019-10-26 at 3 55 57 PM" src="https://user-images.githubusercontent.com/2060045/67627066-047a5c00-f80a-11e9-95fa-083402db00c1.png">

## Debug Info
KeePassXC - Version 2.5.0
Revision: 1ab8a9f

Qt 5.13.1
Debugging mode is disabled.

Operating system: macOS Mojave (10.14)
CPU architecture: x86_64
Kernel: darwin 18.7.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
 libgcrypt 1.8.5

**Comment by parodymshifter** [comment]
My experience with the TouchID feature on Mac OS Mojave is that it never has worked properly for me after enabling it.  The documentation on how to set it up and how to use it is almost non-existent.

**Comment by droidmonkey** [comment]
In the current implementation, you can use TouchID by having a clear key file field after your first successful unlock. The problem is the implementation stores the master key to the macOS key ring and then on unlock pulls that key and then adds again the key file data to it.

**Comment by droidmonkey** [comment]
This is going to have to wait until 2.6.0 because it is a mess currently. We also need to implement a way to test this with a TouchID stub. The current implementation is impossible to test without a Mac Book Pro.

**Comment by droidmonkey** [comment]
After reviewing this we will have to rework how unlocking occurs when the Quick Unlock feature is implemented... this will allow us better control over the process.

**Comment by danielporto** [comment]
It seems that this is high priority since 2019. 
I honestly got confused why there is a touchid option but it doesnt seem to work.
Wouldn't be better to remove it while is  not working?

**Comment by droidmonkey** [comment]
Touchid works fine, unless you have key file only.

**Comment by danielporto** [comment]
@droidmonkey thanks for replying.
I'm a bit confused. I have a database with password. no keyfile no hardware key.
How can I make the touchid work? 
Can it open the database with a touch?

How is it supposed to be the workflow? I mean, is it required that the user open the database every time the system reboots and then from this point on the touch would suffice?
Thanks a lot!

**Comment by droidmonkey** [comment]
Yes the touch ID resets after every boot. You log in the first time with your password and check the touchid box. Once database locks you can unlock by just checking the touchid box and press enter, you'll be prompted to touch your fingerprint. This whole interface is being overhauled in 2.7.0.

**Comment by danielporto** [comment]
Awesome, Just noticed (because my database was not being locked) that I need to press enter with the empty password field and the touchid checkbox marked.
then a box to use the fingerprint showed and I was able to open it :-)
Looking forward for the new interface in 2.7.0 to make it even more user friendly :D

**Comment by hu1buerger** [comment]
@gyli did you close keepass before trying to login again? It seems that over the livetime of keepass touchid works, but as soon as it dies once it needs to be resetuped.

**Comment by droidmonkey** [comment]
Oh good news this is no longer a problem with 2.7.0
