### ISSUE TITLE
KeePassXC would like to record this computer's screen

### ISSUE THREAD

**Issue by steve733** [keepassxreboot/keepassxc#3675]
I received this prompt after installing KeePassXC on macOS 10.15:
![Screen Shot 2019-10-26 at 12 40 53](https://user-images.githubusercontent.com/57051283/67627732-6385a400-f7fd-11e9-960f-57b125f52af8.png)

KeePassXC - Version 2.5.0
Revision: 1ab8a9f

Qt 5.13.1
Debugging mode is disabled.

Operating system: macOS 10.15
CPU architecture: x86_64
Kernel: darwin 19.0.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
 libgcrypt 1.8.5

The application is signed:
codesign -dvvv KeePassXC.app
Identifier=org.keepassx.keepassxc
Format=app bundle with Mach-O thin (x86_64)
CodeDirectory v=20200 size=32214 flags=0x0(none) hashes=999+5 location=embedded
Hash type=sha256 size=32
CandidateCDHash sha256=a8f8076143d4420196eeefe9252482e36a82bd32
CandidateCDHashFull sha256=a8f8076143d4420196eeefe9252482e36a82bd323288fd7b2c7bf14113861ce1
Hash choices=sha256
CMSDigest=a8f8076143d4420196eeefe9252482e36a82bd323288fd7b2c7bf14113861ce1
CMSDigestType=2
CDHash=a8f8076143d4420196eeefe9252482e36a82bd32
Signature size=8931
Authority=Developer ID Application: Janek Bevendorff (G2S7P7J672)
Authority=Developer ID Certification Authority
Authority=Apple Root CA
Timestamp=Oct 26, 2019 at 11:17:24
Info.plist entries=15
TeamIdentifier=G2S7P7J672
Sealed Resources version=2 rules=13 files=330
Internal requirements count=1 size=184

**Comment by droidmonkey** [comment]
This is necessary for Auto-Type to find windows.

**Comment by ov** [comment]
@droidmonkey I personally don't use the Auto-Type feature and I believe I am not alone. Nevertheless I now have to click that "Deny" button every time I start the app. It would be really nice to have an option to completely disable it somewhere in settings, please.

**Comment by droidmonkey** [comment]
Interesting, in my testing when I clicked deny it never prompted again

**Comment by ov** [comment]
I'm getting it every time when I run the app after upgrading to Catalina. Not sure if it is the mac os feature or the feature of version 2.5, as I upgraded them both at the same time. Never had this on 2.4 + macos 10.14

**Comment by droidmonkey** [comment]
Its the joy of macOS
