### ISSUE TITLE
Compilation failed.

### ISSUE THREAD

**Issue by Achaean** [keepassxreboot/keepassxc#3676]
Hi! :-)

I'm on a Debian oldstable based distro, where I have successfully compiled the previous stable release (2.4.3), so I tried to compile the latest one (2.5), but I failed!
I received the message "error: ‘YubiKey’ has not been declared", although I don't need it and I disabled support for it.

Anyway! I'm attaching the cmake and make logs.
[LOGS.zip](https://github.com/keepassxreboot/keepassxc/files/3775422/LOGS.zip)

**Comment by droidmonkey** [comment]
Can you please just post the failure portion?

**Comment by phoerious** [comment]
Duplicate of #3684

**Comment by Achaean** [comment]
Just for the record, at my own compilation YUBIKEY=OFF.
-- Disabled features:
.
.
.
* YubiKey
