### ISSUE TITLE
Autotype button missing in 2.5.0?

### ISSUE THREAD

**Issue by vraravam** [keepassxreboot/keepassxc#3680]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Expected Behavior
[NOTE]: # Autotype button was present in 2.4.3. This was very useful to not copy each attribute individually.

## Current Behavior
[NOTE]: # After opening my pre-existing db in 2.5.0, I am unable to see the autotype button.

## Possible Solution
[NOTE]: # Is there a setting or some other process to enable this?

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1. Install 2.5.0 and open an existing db
2.
3.

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.5.0
Revision: REVISION

Libraries:
- LIBS

Operating system: macOS (Mojave)
CPU architecture: ARCH
Kernel: KERNEL

Enabled extensions:
- EXTENSIONS

**Comment by phoerious** [comment]
Which auto-type button do you mean? We didn't remove any buttons.

**Comment by vraravam** [comment]
I had to re-authorize this in System preferences - then it started working. Closing
