### ISSUE TITLE
v2.5 doesn't open file on Windows 10 1903 - credentials incorrect or file corrupt?

### ISSUE THREAD

**Issue by gurahamu** [keepassxreboot/keepassxc#3681]
## Expected Behavior
Expected file to open

## Current Behavior
Select file from in app browser, type in password, upon pressing 'OK' receive red banner that credentials are incorrect, or file is corrupt. File opens in 2.4.3. 

## Debug Info
KeePassXC - Version 2.5.0
Revision: 1ab8a9f

Qt 5.13.1
Debugging mode is disabled.

Operating system: Windows 10 (10.0)
CPU architecture: x86_64
Kernel: winnt 10.0.18362

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.5

**Comment by phoerious** [comment]
Duplicate of #3678.
