### ISSUE TITLE
Custom URL issues

### ISSUE THREAD

**Issue by Niko-CZ** [keepassxreboot/keepassxc#3682]
After the "Open URL" click custom URLs are not handled correctly in MacOS.

## Current Behavior
**1. Upper to lower case transformation occurs after '@' symbol**
  F.e. in database URL is:
    `rdp://host1.domain1 -u user@DOMAIN`
  During the call it will be converted to:
    `rdp://host1.domain1 -u user@domain`
  *this transformation affects all text in user, password, URL fields.

**2. Some of URLs are considered as web-pages**
  F.e. URL is opened by custom handler:
    `rdp://host1.domain1 -u user@DOMAIN`
  But, following URL is opened by browser:
    `rdp://host1.domain1 -p 4444  `

**3. Colon truncate in protocols**
  F.e. URL:
    `ff://https://google.com`
  will be converted to:
    `ff://http//google.com`

## Debug Info
KeePassXC - Version 2.5.0
Revision: 1ab8a9f

Operating system: macOS 10.15
CPU architecture: x86_64
Kernel: darwin 19.0.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- TouchID

**Comment by droidmonkey** [comment]
All of these examples are a result of QUrl converting them into "proper" URI syntax. I played around with this for a while and couldn't figure out a good way to avoid this from happening.

I will note that the following didn't cause a loss of : in case 3 - `ff:///http://google.com`

Technically the lowercase DOMAIN should not cause any issues.

**Comment by Niko-CZ** [comment]
> Technically the lowercase DOMAIN should not cause any issues.

As I wrote:

> *this transformation affects all text in user, password, URL fields.

Everything what is used for URL composition is affected. So it is critical. 
[P@SSWORD] will become [P@ssword].

**Comment by droidmonkey** [comment]
Missed that part. Recommend using the cmd:// structure

**Comment by Niko-CZ** [comment]
The issue is [`cmd://firefox https://google.com`] not cross-OS format. We are using one keepass database for group of admins/developers. As I understand QUrl has no alternatives now, right? 
Maybe you may consider URL override functionality? I wrote already in one of related bugs:

_There is another possibility how to build custom workflow of URL handling in form of enhancement. It is implemented in Keepass 2.x and called "URL override". For the case above it would be like that:
URL to override: ff
Command: cmd://firefox {URL:RMVSCM}
So each user of shared kdb could customize execution scheme independently of OS platform.
https://keepass.info/help/base/autourl.html#override_

this could be really helpful for those who are using URLs intensively.
