### ISSUE TITLE
2.5.0 can’t be opened because Apple cannot check it for malicious software.

### ISSUE THREAD

**Issue by JaroslawOnGitHub** [keepassxreboot/keepassxc#3685]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Just after updating to 2.5.0 and a trial of opening the application, maOS informs: 

<<“KeePassXC.app” can’t be opened because Apple cannot check it for malicious software.
This software needs to be updated. Contact the developer for more information.
Safari downloaded this file today at 11:13 from github-production-release-asset-2e65be.s3.amazonaws.com.>>

## Current Behavior
[NOTE]: # ( Tell us what actually happens )
I cannot open the app.

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )
Previous version has been working well.

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.5.0

Operating system: macOS Catalina 10.15

**Comment by varjolintu** [comment]
This does not happen with macOS Mojave 10.14.

**Comment by JaroslawOnGitHub** [comment]
After coming back to a previous version 2.4.3 the app works well again.

**Comment by beckerj** [comment]
I just updated from 2.4.3 to 2.5 on Catalina (10.15) and it works fine.

**Comment by KamilRT** [comment]
I'm having exactly the same issue. macOS Catalina here.

**Comment by droidmonkey** [comment]
See here: https://support.apple.com/en-us/HT202491

**Comment by treee111** [comment]
I had no problem with opening v2.5.0 under macOS Catalina

**Comment by JaroslawOnGitHub** [comment]
> See here: https://support.apple.com/en-us/HT202491

It works very well now. Thanks!
Have a good time ahead!

**Comment by heikkij** [comment]
Does it mean that we don't get fix for this as the case is closed?

**Comment by chriscareycode** [comment]
I noticed this also. You right click and select Open the first time and get the warning. Right click and select Open the second time and you get a different prompt and can open it.

**Comment by droidmonkey** [comment]
There is nothing to fix. This is just how Apple has decided to treat developers. Unless you release on the app store this is what you have to deal with unfortunately. Even though we sign the app with a paid certificate!!

**Comment by phoerious** [comment]
The only way to "fix" it is to get our app notarised somehow, which means throwing even more money at Apple. They make €99 a year of us already for doing absolutely nothing except letting their fully automated system generate a certificate for us.

**Comment by heikkij** [comment]
OK, I have understood that by paying 99  per a year includes possibility to have apps notarized..

**Comment by droidmonkey** [comment]
The other problem with motorization is that you have to wait for it to actually be done before you deploy since Apple actually sounds your release package.

**Comment by s01ipsist** [comment]
Solution outlined on https://support.apple.com/en-us/HT202491 didn't work on one MacBook. 

I found you can get round this by deleting the quarantine extended attribute on the application.

```
xattr -d com.apple.quarantine /Applications/KeePassXC.app
```
Then open as normal.

Ref: https://discussions.apple.com/thread/250425993

**Comment by erikolofsson** [comment]
> The other problem with notorization is that you have to wait for it to actually be done before you deploy since Apple actually signs your release package.

You don't have to, it will check online at run time if you don't staple the package.

While annoying it's not hard to add it to your build scripts:
* Run `xcrun altool` to notarize
* Poll for notarization to finish with `altool --notarization-info`. This takes couple minutes
* Staple the `.app` file to make it work offline (`xcrun stapler`)

**Comment by phoerious** [comment]
We'll try that for 2.5.1, thanks.

**Comment by mdavis-xyz** [comment]
Should we add a link to [that support page](https://support.apple.com/en-us/HT202491) from the [Mac download page](https://keepassxc.org/download/)?

**Comment by phoerious** [comment]
Why? The binaries are signed and notarized.

**Comment by mdavis-xyz** [comment]
> Why?

Because this error is still happening. I did a `brew update` last week and my mac refused to run the app unless I went into the Mac security settings and ticked the box. I don't know what signing is done presently, but it's not sufficient to prevent my mac from blocking execution of the app by default.

**Comment by phoerious** [comment]
It is and I can confirm that it works. If it doesn't, then there's another problem somehow. Perhaps with Homebrew even.

**Comment by pleunv** [comment]
FWIW, I'm experiencing the same issue again with v2.7.4 on homebrew. macOS 12.6.1.

**Comment by phoerious** [comment]
Make sure you install the correct version for your processor. Also try closing your browser before installing the app.
