### ISSUE TITLE
Allow Gobal Auto-Type keyboard shortcut to trigger selected entry auto-type when  KeePassXC window has focus

### ISSUE THREAD

**Issue by archont00** [keepassxreboot/keepassxc#3686]
## Expected Behavior
* User defines the global auto-type keyboard shortcut in KeePassXC.
* This shortcut works when pressed e.g. in Firefox (searches by window title, URL, etc and proposed KeePassXC entries to be used).
* However, when auto-look up does not work, the user may switch to KeePassXC window, look-up the entry via search and then press the global auto-type keyboard shortcut and let KeePassXC write the user & password sequence.

## Current Behavior
* The global auto-type keyboard shortcut does not trigger autotype when used in KeePassXC window.

## Possible Solution
* Use the original auto-type shortcut (CTRL+SHIFT+V)
* Click on auto-type button.

## Context
I am just desperately trying not to use CTRL+SHIFT+V because that is quite difficult to press with a single-hand.
CTRL+LeftAlt+A works better (this is what I have setup in settings).

## Debug Info
KeePassXC - Version 2.4.3
Revision: 5d6ef0c

Qt 5.13.1
Debugging mode is disabled.

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 5.3.6-arch1-1-ARCH

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.5

**Comment by droidmonkey** [comment]
Covered by #429
