### ISSUE TITLE
Bug: Cannot drag entries between folders

### ISSUE THREAD

**Issue by always-depends** [keepassxreboot/keepassxc#3687]
My setup:
Windows 10 Pro 64 bit, Version 1903, Build 18362.418
KeePassXC 2.5.0
KeePassXC Browser version 1.5.3, Firefox 70.0 64 bit (not sure these matter for this but mentioning them anyhow)

I have new entries saved to the "KeePassXC-Browser Passwords" folder in KeePassXC then I move them into an appropriate folder based on category.  I am not able to move any entries around at all regardless of the folder.  This is a new issue as of KeePassXC 2.5.0; previous versions worked fine.

**Comment by droidmonkey** [comment]
I cannot replicate this on Windows 10

**Comment by always-depends** [comment]
I had this problem in another app as well.  It turned out to be a Windows issue, although I don't know why it happened nor how to fix it.  I rebooted and it was fine.  Sorry for the false alarm.
