### ISSUE TITLE
Hide "Sequence" column from appearing in "Auto-Type" popup if not needed

### ISSUE THREAD

**Issue by S3NTYN3L** [keepassxreboot/keepassxc#3688]
## Summary
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
As in the title, an option to disable the "Sequence" column from appearing in the "Auto-Type" popup when multiple entries exist.

## Desired Behavior
[NOTE]: # ( Tell us how the new feature should work, be specific )
Hide "Sequence" column in "Auto-Type" popup.

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
It's awfully distracting to see the Auto-Type sequence when trying to pick an entry from the list.
I know this sort of option was/is available in KeePass for Windows, but I've forgotten how it's done.
I can no longer check to see as I have no machines running Windows and run Linux full-time.

A picture of the column in question:
![DisableSequenceColumnKeePassXC](https://user-images.githubusercontent.com/25750/67640663-55ee1e00-f8d2-11e9-9cd0-2ba64f6b3276.png)

**Comment by droidmonkey** [comment]
The reason it is there is so you can pick the right sequence for entries that have multiple sequences. This will likely not be an option, it really doesn't make sense to hide that information.

**Comment by S3NTYN3L** [comment]
How can there be multiple sequences for the same website?
It makes perfect sense to hide the information if the user so chooses. That's WHY they're called OPTIONS.

**Comment by droidmonkey** [comment]
Every OPTION requires additional CODE and TESTING that takes more TIME. :wink:

**Comment by S3NTYN3L** [comment]
I understand that and never expected it to be done overnight.
Why am I sensing hostility in your comments for simply making a suggestion and it being dismissed out of hand?

**Comment by droidmonkey** [comment]
My apologies, just getting excited. One feature about Auto-Type is that it allows you to define multiple sequences for each entry. Those could be for different windows, but can also be the same. The sequences column allows you to distinguish between them. Just giving some context for the reason why that column exists.

![image](https://user-images.githubusercontent.com/2809491/67643599-93ad6f80-f8ef-11e9-9593-f811ebdf9eb6.png)

![image](https://user-images.githubusercontent.com/2809491/67643604-9740f680-f8ef-11e9-98f0-5c40a180366f.png)

**Comment by S3NTYN3L** [comment]
I see now, thanks.

Forgive my ignorance, but why not adapt the code that Keepass for Windows uses for this?
IIRC, they used a right-click context and/or window menu entry for this.

Anyway, your suggestion of hiding the column unless multiple Auto-Type Sequences exist is a good one. ;)

**Comment by droidmonkey** [comment]
Unfortunately KeePass is written in C# using .NET and we cannot use any of their code for our project.

**Comment by S3NTYN3L** [comment]
Hmm, that's a shame.
So much for it being open source. :(

**Comment by S3NTYN3L** [comment]
Latest update to 2.7.1 seems to have broken whatever was done to correct this issue in #3794.
Would you all be so kind as to look into this again?
Thanks in advance.
