### ISSUE TITLE
Shows multiple unapplicable logins for each ambiguous page

### ISSUE THREAD

**Issue by r0ckarong** [keepassxreboot/keepassxc#3690]
## Expected Behavior
The suggestions for logins should be limited to the applicable and stored URLs in the database.

## Current Behavior
Some entries that had multiple entries in the `URL` field will show various logins from across the database.

## Possible Solution
1) Improve resolution of the login URLs to show only applicable logins
2) Provide better documentation on how "alternative" acceptable URLs must be formulated in the `URL` field. This has been buggy for a while.

## Steps to Reproduce
Store multiple entries as `URL,URL2,URL3`
access some random website. See all three of the URLs.

## Context
This has worked fine on 2.4.3 before (multiple Linux distros) and now I'm getting these pointless prompts. I've removed some "backup/alternative" URLs from the respective entries and that solved the problem but I would expect to NOT be shown suggestions for anything that even closely matches.

## Debug Info
KeePassXC - Version 2.5.0
Revision: 1ab8a9f

Qt 5.9.5
Debugging mode is disabled.

Operating system: Ubuntu 18.04.3 LTS
CPU architecture: x86_64
Kernel: linux 4.15.0-65-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.1

Extension Version: 1.5.3

**Comment by droidmonkey** [comment]
As of 2.5.0, this is now completely unnecessary. For entries that need multiple URLs simply edit the entry, go to the browser integration settings page, then add the urls as needed.

Revert the URL field to the primary URL only.
