### ISSUE TITLE
"Auto-Type" UI - Please Remove Sequence Column

### ISSUE THREAD

**Issue by 0pLuS0** [keepassxreboot/keepassxc#3691]
Auto-Type - Please Remove Sequence Column

## Summary
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
For the Auto-Type window please remove the ```Sequence``` Column

## Desired Behavior
[NOTE]: # ( Tell us how the new feature should work, be specific )
It seems redundant to have this ```Sequence``` Column, especially when the end-user, under ```Edit entry``` can look at the ```Auto-type``` to see what is the default behaviour, and change this.  So then I personally don't understand why the need to show this  ```Sequence``` Column section in the UI when logging into a site, it just creates a bigger bloated UI.

## Possible Solution
[NOTE]: # ( Not required, but suggest ideas on how to implement the addition or change )

I hope this  ```Sequence``` Column can please be removed...

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )

As I listed above, it just creates a bigger, more bloated UI. 

The columns: ```Group - Title - Username``` are sufficient enough.

I've attached a screen shot showing this UI and what I'm referring to.

THANKS

![sequence](https://user-images.githubusercontent.com/36190223/67642426-a5990d80-f903-11e9-93ef-41b79ae45cd9.jpg)

**Comment by 0pLuS0** [comment]
@droidmonkey sorry, there was already a request for this, because I didn't see you reference the original to this post?

THANKS

P.S. Keep up the great work, all involved in this project, it's a GREAT APP!

**Comment by droidmonkey** [comment]
Yes this was duplicate

**Comment by 0pLuS0** [comment]
Ok thanks :)

**Comment by 0pLuS0** [comment]
@droidmonkey from what I can tell this has been changed now in 2.5.0?

If this is changed now in 2.5.0 I still see this happening.

These are my compile flags for 2.5.0;

export LDFLAGS="-ltermcap"

mkdir -p build
cd build
  cmake \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_BUILD_TYPE=Release \
    -DWITH_TESTS=OFF \
    -DWITH_XC_BROWSER=OFF \
    -DWITH_XC_YUBIKEY=OFF \
    -DWITH_XC_NETWORKING=OFF \
    -DWITH_XC_AUTOTYPE=ON \
    -DWITH_XC_SSHAGENT=OFF \
    -DWITH_XC_KEESHARE=OFF \
    -DWITH_XC_KEESHARE_SECURE=OFF \
    -DWITH_XC_UPDATECHECK=OFF \
    ..

  make
  make install DESTDIR=$PKG

**Comment by droidmonkey** [comment]
I don't understand the question

**Comment by 0pLuS0** [comment]
@ droidmonkey I'm sorry I ended up talking about the ```Share Tab``` which is now gone, when I meant the ```Sequence Column``` still shows up in the ```Auto-type``` UI.

I'm talking about the original issue I opened this report over, that screen shot I thought that was changed in 2.5.0?

Sorry for the confusion... :(

THANKS

**Comment by 0pLuS0** [comment]
@droidmonkey I ended up talking about the ```Share Tab``` by mistake, sorry for the confusion... :(

So was the ```Sequence Column``` suppose to have been removed in 2.5.0?

THANKS

**Comment by droidmonkey** [comment]
It was added in 2.5

**Comment by 0pLuS0** [comment]
@droidmonkey I am still seeing it then in 2.5.0, it's not gone...

![Sequence](https://user-images.githubusercontent.com/36190223/68060765-a235c580-fcf9-11e9-98f2-b74812438c7c.jpg)

**Comment by phoerious** [comment]
We didn't say it was gone. It was added in 2.5, which is the opposite of gone.

**Comment by 0pLuS0** [comment]
@phoerious ok thanks...
