### ISSUE TITLE
Auto-type focus switching to KeePassXC window before search

### ISSUE THREAD

**Issue by bigwheat123** [keepassxreboot/keepassxc#3694]
When trying to use auto-type, the entry can't be found because it searches for the window title of KeePassXC (on MacOS 10.15).

### Expected Behavior
The entry search should be based on the window title that is in focus when the hotkey is pressed.

### Current Behavior
The entry search uses the KeePassXC window so it never finds a matching entry to '<Database name> - KeePassXC'.

### Steps to Reproduce
This only started happening a few weeks ago. I am not sure what changed.

### Debug Info
KeePassXC - Version 2.4.3
Revision: 5d6ef0c

Qt 5.12.3
Debugging mode is disabled.

Operating system: macOS 10.15
CPU architecture: x86_64
Kernel: darwin 19.0.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
 libgcrypt 1.8.4

**Comment by phoerious** [comment]
Please upgrade to 2.5.0. The problem you reported should be fixed there. If not, please reopen this issue.
