### ISSUE TITLE
Add information on Auto-Type shortcut to Quick Start Guide 

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [keepassxreboot/keepassxc#3695]
The current Quick Start Guide (last commit a8c10cd 5 days ago) does not seem to either confirm or deny that KeePassXC performs the following behaviour.

There is a hotkey such that, when pressed and no database is opened, the program will prompt to open a database; and then, if/when that is done, the program will try to fill any field that was selected when the keypress occured.

I find that, at least without the browser extension, the behaviour at issue - which is what I would expect and is what the original KeePass does - does not occur. (If the extension is meant to provide the behaviour, why have a hot key for the core for KeePassXC at all?) If that behaviour is meant to occur - without the extension - that I will file a bug report for that.

**Comment by droidmonkey** [comment]
Are you referring to Auto-Type? That is in the users guide.

**Comment by LinuxOnTheDesktop** [comment]
I am indeed talking about Auto-Type. I'm saying the following. The Quick Start Guide should make it clear whether auto-type will, without the browser extension, unlock the database (and I am wondering whether it _does_ do that and, if it does not, why not).

I have trouble locating the user guide. Is it [this](https://github.com/keepassxreboot/keepassxc/wiki)?

**Comment by droidmonkey** [comment]
Its literally the menu item below the quickstart guide in the help menu of KeePassXC. Or were you referring to the quickstart on our website?

**Comment by droidmonkey** [comment]
Ergh, I should have clicked the commit hash, I was thinking if something completely different.

**Comment by LinuxOnTheDesktop** [comment]
Yes, I am talking about the quick start guide on the website. (I suppose I could have been clearer.)

With your help, I have found the user guide. Looking at its contents page, I notice that there are the following chapters.

1 Introduction
2 Installing KeePassXC
3 Entry Management
4 Database Management
5 KeePassXC-Browser-Extension
6 Search Operations
7 Password Generator

So, nothing on autotype. But I find that the third chapter discusses autotype (or 'Auto-Type' as it calls it). But so far as I can see that section does not actually answer my question. If I am correct in that assertion, then I request that you (i) change the documentation (quick start and userguide) to answer the question, (ii) actually tell me, here, the answer.

**Comment by droidmonkey** [comment]
When you press the global Auto-Type keyboard shortcut it will prompt to unlock your database if it is not already.

**Comment by LinuxOnTheDesktop** [comment]
@droidmonkey 

Thanks. But (1) that does need to be in the documentation and prominently so, (2) that prompt was not happening for me. Strangely, though, it is now working; I don't know what I have changed.
