### ISSUE TITLE
Allow to login one of the options

### ISSUE THREAD

**Issue by 1mdc** [keepassxreboot/keepassxc#3700]
[TIP]:  # ( Provide a general summary of the feature in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Summary
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
If I enable security option with both password and yubikey, it asks me to login with both password and yubikey. I can use yubikey on desktop but not on mobile, so it is not easy for me to open database. Is there an option to allow me to login with password or yubikey?

## Desired Behavior
[NOTE]: # ( Tell us how the new feature should work, be specific )

## Possible Solution
[NOTE]: # ( Not required, but suggest ideas on how to implement the addition or change )

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )

**Comment by phoerious** [comment]
Since both factors are used to create the final key and KDBX only supports one decryption key, this is not possible. You can use your YubiKey on mobile via NFC or USB C.
