### ISSUE TITLE
UI: Notes section doesn't render line breaks since 2.5.0

### ISSUE THREAD

**Issue by ei-ke** [keepassxreboot/keepassxc#3701]
## Expected Behavior
Viewable line breaks of notes in the preview section for entries.

## Current Behavior
Linebreaks for notes are only shown correctly when you open an entry to edit it. In the preview section linebreaks are ignored since updating to 2.5.0. Before this update, IIRC, those were rendered as expected.

![2019-10-28_10-41](https://user-images.githubusercontent.com/17415256/67668736-cea3b780-f970-11e9-8a7d-ed94a28fc8ba.png)

## Context
Makes it unfeasible to work with notes from the preview section.

## Debug Info
KeePassXC - Version 2.5.0
Revision: 1ab8a9f

Libraries:
- libgcrypt 1.8.5

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: 5.3.7-arch1-1-ARCH

Enabled extensions:
- Auto-Type
- Browser-Integration
- SSH-Agent
- KeeShare (bestätigtes und unbestätigtes Teilen)
- YubiKey

**Comment by MyXelf** [comment]
Totally supporting this.

On v2.4.3 the widget was a `QTextEdit` now on v2.5.0 it was changed to a `QLabel`. I don't think that `QLabel` would be the right widget for the 'Notes' field.

I would use a transparent widget with the ability to "glue" to the right + bottom of the preview, using the remaining space, and in case the vertical space is too small or the content of the Note is too much, the widget's scrollbar would show up.
