### ISSUE TITLE
Browser password addon always lists a wrong account on access request

### ISSUE THREAD

**Issue by MartinX3** [keepassxreboot/keepassxc#3702]
## Expected Behavior
I want nothing if no account is found or the correct entry.

## Current Behavior
I want to login on ebay and it wants to put in my O² account data.

If it finds the correct account on another side it still wants access to my O² account.

It seems that it always picks my O² account regardless if it founds a matching account or not.

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1. I go to ebay
2. I want to login
3. It wants access to my O² account credentials

1. I go to paypal
2. I want to login
3. It wants access to my O² and paypal account credentials

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )
I updated from 2.3.1 to 2.5.0 via ubuntu repository
Now this is happening.

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.5.0
Revision: 1ab8a9f

Libraries:
- libgcrypt 1.8.1

Operating system: Ubuntu 18.04 / Linux Mint 19.2
CPU architecture: x86_64
Kernel: 5.0.0-32-generic

Enabled extensions:
- Auto-Type
- Browser-Integration
- SSH-Agent
- KeeShare (bestätigtes und unbestätigtes Teilen)
- YubiKey

**Comment by droidmonkey** [comment]
Does your O2 account have an * in the url?

**Comment by MartinX3** [comment]
oh
I added `https://login.o2online.de, https://www.o2online.de/ecareng/billing/`as url in the thinking I could add multiple urls for the browser addon.

**Comment by droidmonkey** [comment]
Processing of url changed. Use the new multi url setting in the browser integration page.

**Comment by droidmonkey** [comment]
Auto-Type is totally different. Go to the Auto-Type settings and disable matching url in entry title

**Comment by flanger001** [comment]
@droidmonkey I'm sorry - am I confusing the feature names? When I visit a website and I click into a username field, I expect to see an entry for that field if one exists in the db. I'm currently seeing that every website returns the same list (sorry for blanked out usernames but I can assure you they are the same):

Paypal:
![Screen Shot 2019-10-29 at 11 44 00 AM](https://user-images.githubusercontent.com/1645017/67791170-624ab600-fa4d-11e9-85a1-b7f735cda030.png)

Credit Karma:
![Screen Shot 2019-10-29 at 12 10 08 PM](https://user-images.githubusercontent.com/1645017/67791172-624ab600-fa4d-11e9-94bd-266dc4f88ced.png)

I'm using the regular KeepassXC-Browser extension on Firefox and nothing else of note.

**Comment by droidmonkey** [comment]
Yes you confused the feature names, hehe. Can you screenshot the entry edit page for those three accounts. Please obscure your username and password fields. 

Alternatively, create a demo database that replicates this behavior so we can debug it.

**Comment by flanger001** [comment]
I can, but having looked at those I know what you're going to tell me. Here's the Nintendo one.

![Screen Shot 2019-10-29 at 1 26 14 PM](https://user-images.githubusercontent.com/1645017/67792682-eaca5600-fa4f-11e9-9cc3-cffa7ef9b8ac.png)

The others have multiple urls too. My bad! I'll fix.

**Comment by flanger001** [comment]
One of them did have an asterisk in the url. Any suggested fix there?

**Comment by MartinX3** [comment]
please remove the second url and it's `;` and put it in the "browser integration" symbol (left side, scroll down)
I did exactly the same wrong entry, except that I did use the `,`
