### ISSUE TITLE
Check for updates should consider checking weekly while running

### ISSUE THREAD

**Issue by jsoref** [keepassxreboot/keepassxc#3706]
## Summary
There's an option to `Check for updates at application startup once per week`, but if I leave KeePassXC running for a month, it seems like it won't tell me that I'm out of date.

## Desired Behavior
In addition to checking at startup if it hasn't been checked in a week, schedule a new check for a week later to be run if the app is still running at that point (and to be repeated a week after that...).

## Context
I (and many others) leave certain apps running for extended periods of time. Currently, Chrome.app has a white up arrow in a green circle telling me that I'm out of date. That will eventually turn to Yellow/Amber and later Red if I wait long enough (it definitely happens for some colleagues).

**Comment by droidmonkey** [comment]
This is a great point
