### ISSUE TITLE
"own certificate" is awkward

### ISSUE THREAD

**Issue by jsoref** [keepassxreboot/keepassxc#3708]
It's hard to precisely explain why this is wrong.

The simplest way to think about it is that you shouldn't be able to find anything else that uses `own` like this.

* **Windows** for a while used `My Computer` (and they were more or less ridiculed for it). Modern **Windows** uses `This PC`.
* **macOS** has used `Macintosh HD` which avoids this problem.
* **Firefox** (via **NSS**/**PSM** which is an unloved ui element in its own right) uses `Your Certificates` and `You have certificates...` in its **Certificate Manager**.
* **Windows** Uses `Current User`>`Personal` for the equivalent element in its **Certificate Manager**.

Yes, I'm aware that none of these are perfect analogs to the UI element here (the **Certificate Manager** cases which might seem to be closer are actually further as they cover multiple certificates whereas the element in question here is a singleton).

Fwiw, imo, `own` is worse than `This` (pronoun, determiner, adverb), `My` (determiner possesive pronoun), or `User` -- I think because of the part of speech (I think of it as a verb, although it is also an adjective which is probably how you're using it)

## Expected Behavior
Some other terminology

## Current Behavior
https://github.com/keepassxreboot/keepassxc/blob/3b330ee2d11221b598ec60e506cc4c5652e33dd6/src/keeshare/SettingsWidgetKeeShare.ui#L80

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )

## Steps to Reproduce
1. Open KeePassXC.app
1. Preferences
1. KeeShare

## Debug Info
KeePassXC - Version 2.5.0
Revision: 1ab8a9f

Qt 5.13.1
Debugging mode is disabled.

Operating system: macOS Mojave (10.14)
CPU architecture: x86_64
Kernel: darwin 18.7.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
 libgcrypt 1.8.5

**Comment by droidmonkey** [comment]
Personal certificate?

**Comment by jsoref** [comment]
Sure

**Comment by droidmonkey** [comment]
This can be fixed in translations.
