### ISSUE TITLE
Disabled scroll button for Application Settings in macOS dark is unclear

### ISSUE THREAD

**Issue by jsoref** [keepassxreboot/keepassxc#3709]
## Expected Behavior
It should be obvious that a button is disabled (I think that means that the arrow should be gray instead of white)

## Current Behavior
There's no particular distinction between the enabled up arrow and the disabled down arrow, as seen here:
![image](https://user-images.githubusercontent.com/2119212/67695266-27784d80-f97b-11e9-9376-4d3394ef2978.png)

## Possible Solution
Change the color of the arrow to a gray (in macOS dark at least).

## Steps to Reproduce
1. Enable dark mode on macOS
1. Open KeePassXC
1. Preferences...
1. Scroll to the bottom of the Application Settings area (so that KeeShare is fully visible and General is not)

## Debug Info
KeePassXC - Version 2.5.0
Revision: 1ab8a9f

Qt 5.13.1
Debugging mode is disabled.

Operating system: macOS Mojave (10.14)
CPU architecture: x86_64
Kernel: darwin 18.7.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
 libgcrypt 1.8.5

**Comment by droidmonkey** [comment]
We don't control this color. Please file a bug report with Qt.
