### ISSUE TITLE
display problems in QPlainTextEdit

### ISSUE THREAD

**Issue by Arg0s1080** [keepassxreboot/keepassxc#3711]
cannot see the letters written on some PlainTextEdit using dark themes

![image](https://i.imgur.com/VLv2HWY.png)

- Kernel: 5.3.6
- Distro: Kde Neon 5.17.1 64 bit
- Theme: Breeze Dark
- Installed from: `ppa:phoerious/keepassxc`
- Qt version: 5.13.1

**Comment by droidmonkey** [comment]
Restart KeePassXC after changing the theme

**Comment by droidmonkey** [comment]
This is the theme's fault, not ours

**Comment by Arg0s1080** [comment]
I said this because Breeze is Plasma KDE default theme

My apologies

**Comment by droidmonkey** [comment]
Yah that makes it worse, they should be testing this! No worries
