### ISSUE TITLE
Documentation / usability: one must search for search (*sic*)

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [keepassxreboot/keepassxc#3712]
The userguide - the one accessible from within KeePassXC - has a whole chapter on refining searches, Ch. 1 of that guide boasts of the 'intergrated search function'. None of that material actually tells one how to search. Having, er, searched all the menus, eventually I found a little button that revealed a previously hidden search box. That button is on the right here:

![image](https://user-images.githubusercontent.com/47056543/67736077-2d634280-f9fe-11e9-8d60-2c4007886cab.png)

This situation seems to me to be a failure of both documentation and interface. I suggest that you put an easily recognisable search icon on the toolbar and mention that icon in the guide. Otherwise - unless I miss something - you will have frustrated users and get more reports like this one. EDIT: a keyboard shortcut - ctrl-F? - wouldn't hurt either.

The search seems to work well, once one has found it.

**Comment by phoerious** [comment]
This only happens when your window is too small and hardly fixable.

**Comment by LinuxOnTheDesktop** [comment]
> hardly fixable.

Well . .

- The documentation could mention the situation and suggest that if one encounters it, one could turn off the display of icons names.
- There could be a keyboard shortcut.
