### ISSUE TITLE
[KeeShare] Update shared file on startup

### ISSUE THREAD

**Issue by Bruceforce** [keepassxreboot/keepassxc#3714]
[TIP]:  # ( Provide a general summary of the feature in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Summary
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
I'm using KeePass on a Windows notebook at work since this is installed by default from the infrastructure team. I would like to share some of the groups to my private database and vice versa. If I now add passwords via KeePass on my notebook, KeepassXC on my private PC naturally doesn't know about this. So I have to open the work database with KeePassXC and do some operations, to make it save the database for the KeeShare saving mechanism to kick in.

## Desired Behavior
[NOTE]: # ( Tell us how the new feature should work, be specific )
The shared database file should be updated / synchronized on start of KeePassXC (right after decryption of the database).

## Possible Solution
[NOTE]: # ( Not required, but suggest ideas on how to implement the addition or change )
Check for changes in the shared file right after the database is unlocked and write them back to the shared file.

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
(see summary)

**Comment by droidmonkey** [comment]
Will be corrected with overall changes to KeeShare.
