### ISSUE TITLE
Allow to register more than one URL for a Login

### ISSUE THREAD

**Issue by Mannshoch** [keepassxreboot/keepassxc#3715]
## Summary/Context
I Use a Company Login which is shared over some Website with different URL. I have to change my Password every three Month once. But because KeePassXC do not allow to have more than one URL per login. I have to change these passwords some more Logins also.

## Desired Behavior
Ability to add an additional URL for the same Password.

## Possible Solution
allow to add ; separated additional URLS or somthing like that.

**Comment by droidmonkey** [comment]
This was implemented in 2.5.0. look under the browser integration tab of entry editing.
