### ISSUE TITLE
Include Settings Option to get the Notes Tab back?  

### ISSUE THREAD

**Issue by TheRoarkster** [keepassxreboot/keepassxc#3722]
Would it be possible to add an option to get the "Notes" tab back?  
I saw that it was merged into the General tab, but that makes it just a string of characters. 

The previous Notes tab included the formatting, which made it much more usable. 

Thanks.

**Comment by droidmonkey** [comment]
We are not bringing the notes tab back, we are going to fix the formatting. This is a duplicate.
