### ISSUE TITLE
Please Remove These UI Paths?

### ISSUE THREAD

**Issue by 0pLuS0** [keepassxreboot/keepassxc#3725]
## Summary
When you click on an Entry, above the TABS it lists the /path that you are looking at, which is redundant, because both the left UI pane and the main pane show us the /paths already, there is no need for this, and it just adds more clutter to the UI. In 2.4.3, at least the /paths looked more Unix/Linux correct shown with the forward slash /path/names now in 2.5.0 it has [Brackets] and a greater than sign to show the paths which is not even Unix/Linux formatting...

## Desired Behavior
[NOTE]: # ( Tell us how the new feature should work, be specific )
```Remove these paths listed above the tabs and only display the Name/Entry.```

## Possible Solution
[NOTE]: # ( Not required, but suggest ideas on how to implement the addition or change )

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
It creates to much UI clutter and it's redundant.

Please see the attached screen shots of before and after... 

```2.5.0 BEFORE```
![before-tab](https://user-images.githubusercontent.com/36190223/67821050-922ca480-fab3-11e9-85b4-36cefc358d06.jpg)

```2.5.0 AFTER```
![new-tab](https://user-images.githubusercontent.com/36190223/67821054-9789ef00-fab3-11e9-8c5f-6f632f5e87ee.jpg)

THANKS

**Comment by droidmonkey** [comment]
We are not going to remove this, it is a feature we like.

**Comment by 0pLuS0** [comment]
@droidmonkey at least put it back that represents the PATH format of the source you compiled it for, and since I'm talking about Linux, that is /paths/that/look/like this.

The Brackets and Greater Than sign looks more like BBCode...

Hey, don't take me the wrong way, if you want it, great, but at least let's stick to a proper FORMAT, this isn't...

And of course for Windows that would be \paths\with\backslashes...

THANKS

**Comment by droidmonkey** [comment]
It was explicitly changed because we did not want it to look like a path...

**Comment by 0pLuS0** [comment]
Ok I understand that, but PLEASE for simplicity sake, let's just keep it simple then, because then it's easier on the eyes...

Why not just make it like this then?

```Root - Internet - Misc - Mapquest```

THANKS

**Comment by droidmonkey** [comment]
You are welcome to modify the code and remove the brackets for your personal use

**Comment by 0pLuS0** [comment]
@droidmonkey Well thanks for posting this, but for now I needed to revert back to 2.4.3, because as I mentioned in my last reply here;

https://github.com/keepassxreboot/keepassxc/issues/3726

If you have a lot of notes, then they are getting cut off, you only see the partial notes, so we really need to get this Notes Tab put back...


THANKS

**Comment by 0pLuS0** [comment]
@droidmonkey So if I wanted to remove the brackets and the greater than sign and just have it like this;

```Internet - Misc - Firefox```

Does this look correct?

QString EntryPreviewWidget::hierarchy(const Group* group, const QString& title)
{
    const QString separator(" - ");
    QStringList hierarchy = group->hierarchy();
    QString groupList = QString("%1").arg(hierarchy.join(separator));

    return title.isEmpty() ? groupList : QString("%1 - %2").arg(groupList, title);

```THANKS```

**Comment by droidmonkey** [comment]
Yes, but please don't clutter this PR with unrelated topics.

**Comment by 0pLuS0** [comment]
@droidmonkey ok thanks a lot, I really have appreciated all your time!

Keep up the great work! :+1:
