### ISSUE TITLE
Password generator does not respect default choices

### ISSUE THREAD

**Issue by Gunni** [keepassxreboot/keepassxc#3733]
![Screenshot from 2019-10-30 11-44-01](https://user-images.githubusercontent.com/358099/67855598-a354d000-fb0a-11e9-8c5e-c0de542c7b30.png)

## Expected Behavior
I expect the password generator to respect the selected character types.

## Current Behavior
Password is generated using all character types except ExtendedASCII.

## Steps to Reproduce
1. Open KeePassXC
2. Click the "Password Generator" die at the top
3. Observe wrong password is generated until you check/uncheck a character type

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )
Many systems can't handle special character so I disabled it, but it stays active, almost every time i use the generator, i have to check and then uncheck specials again.

## Debug Info
KeePassXC - Version 2.4.3
Revision: 5d6ef0c

Qt 5.12.5
Debugging mode is disabled.

Operating system: Fedora 30 (Workstation Edition)
CPU architecture: x86_64
Kernel: linux 5.3.7-200.fc30.x86_64

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.5

**Comment by droidmonkey** [comment]
I believe this is fixed in 2.5.0.

**Comment by Gunni** [comment]
I'm using the package from dnf, maybe someone knows who maintains that?

```
# dnf info keepassxc
Last metadata expiration check: 0:00:11 ago on mið 30.okt 2019, 12:19:55 UTC.
Installed Packages
Name         : keepassxc
Version      : 2.4.3
Release      : 6.fc30
Architecture : x86_64
Size         : 15 M
Source       : keepassxc-2.4.3-6.fc30.src.rpm
Repository   : @System
From repo    : updates
Summary      : Cross-platform password manager
URL          : http://www.keepassxc.org/
License      : Boost and BSD and CC0 and GPLv3 and LGPLv2 and LGPLv2+ and LGPLv3+ and Public Domain
Description  : KeePassXC is a community fork of KeePassX
             : KeePassXC is an application for people with extremely high demands on secure
             : personal data management.
             : KeePassXC saves many different information e.g. user names, passwords, urls,
             : attachemts and comments in one single database. For a better management
             : user-defined titles and icons can be specified for each single entry.
             : Furthermore the entries are sorted in groups, which are customizable as well.
             : The integrated search function allows to search in a single group or the
             : complete database.
             : KeePassXC offers a little utility for secure password generation. The password
             : generator is very customizable, fast and easy to use. Especially someone who
             : generates passwords frequently will appreciate this feature.
             : The complete database is always encrypted either with AES (alias Rijndael) or
             : Twofish encryption algorithm using a 256 bit key. Therefore the saved
             : information can be considered as quite safe.
```

**Comment by Gunni** [comment]
I got the "You are using an old version of KeePassXC." warning in KeePassXC-Browser now, soooo when is this getting updated @Germano0?

I even upgraded to Fedora 31, but I still only get this: keepassxc-2.4.3-6.fc31

**Comment by Germano0** [comment]
2.4.0 will not be pushed to stable Fedora repositories. Please read
https://bodhi.fedoraproject.org/updates/FEDORA-2019-15c92c2e66#comment-1113383

>

**Comment by Gunni** [comment]
Thanks for point that out, i was unaware of that problem. and the website you linked.

If only dnf would explain what you said and give the same link.

**Comment by droidmonkey** [comment]
@Germano0 have not received any UI issues as it relates to gtk. Care to have atim explain himself in an issue report. It's not getting fixed if it's just an empty complaint.

**Comment by Germano0** [comment]
@droidmonkey 

> @Germano0 have not received any UI issues as it relates to gtk. Care to have atim explain himself in an issue report. It's not getting fixed if it's just an empty complaint.

I posted the URL for the KXC Github issues listed in the message. I was not willing to post things about GTK
