### ISSUE TITLE
Focus on password field after database lock when multiple databases are open

### ISSUE THREAD

**Issue by boeserwolf** [keepassxreboot/keepassxc#3735]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
The field "Enter password:" should have the focus after switching to the application window (using CMD+Tab on macOS), so one may start typing right away.

## Current Behavior
[NOTE]: # ( Tell us what actually happens )
After locking the database manually or automatically, switching to another application and back to KeePassXC, the field "Enter password:" doesn't have the focus set. 

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )
Press "Tab" twice to focus it manually.

## Steps to Reproduce
1. Open KeePassXC with a database and unlock it using your password.
2. Lock the database manually or wait for it to lock after timeout.
3. CMD+Tab to another application.
4. CMD+Tab to KeePassXC.
5. You wont be able to type in your password directly, like in older KeePassXC versions before.
6. Due to muscle memory you'll type away anyways.

## Debug Info
KeePassXC - Version 2.5.0
Revision: 1ab8a9f

Qt 5.13.1
Debugging mode is disabled.

Operating system: macOS Mojave (10.14)
CPU architecture: x86_64
Kernel: darwin 18.7.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
 libgcrypt 1.8.5

Operating system: macOS Mojave 10.14.6 
CPU architecture: x86_64
Kernel: Darwin Kernel Version 18.7.0

**Comment by droidmonkey** [comment]
This is a duplicate issue
