### ISSUE TITLE
Autotype Shortcuts broken on MacOS Mojave 10.14.6 after update to 2.5.0

### ISSUE THREAD

**Issue by parodymshifter** [keepassxreboot/keepassxc#3737]
After updating through a brew upgrade to KeePassXC 2.5.0 the global auto-type shortcut stopped working until I went into various settings and tinkered with things.  The shortcuts started working again after tinkering with various shortcut settings.  It's unclear which one actually triggered re-enabling the keyboard shortcuts functioning.

**Comment by parodymshifter** [comment]
Autotype shortcuts are working sometimes. In the case of the Terminal app the 1st character of the passwords is being dropped, making the feature useless.  In other cases the shortcut keys seem to be ignored entirely.

**Comment by parodymshifter** [comment]
In general autotype shortcuts are completely unreliable on OS X Mojave 10.14.6 since this update.

**Comment by mr-falafel** [comment]
I have the same issue on Windows 10. It seems to recognise the shortcut, as pressing it prompts me to unlock the database if I haven't already. However, it doesn't enter any credentials for any app. Perhaps it's the window-title reading function that is broken?

**Comment by mr-falafel** [comment]
Performing a full uninstallation and re-installation has fixed the issue for me...

**Comment by XenitXTD** [comment]
I have my autotype shortcut set to Option+/ on mac. it was no issue until update now its triggering but also inputing the character that occurs ÷ so I have to manually remove this character from the input field... this wasnt an issue prior to updating to 2.5.0

**Comment by HUGHUSR** [comment]
The problem I am seeing is:
1) In Firefox
2) Switch to KP
3) Invoke Autotype
4) **Finder is switched to before switching back to Firefox** (THIS IS THE BUG)
5) Firefox is switched to, and the first character of the username is dropped, because it was typed while Finder was the current app.

**Comment by HUGHUSR** [comment]
Although I am not using Global AutoType, I have found that if I set the "AutoType Start Delay" to 1500ms, it more or less fixes the problem... but not 100% of the time.

I suspect that problem also has something to do with animation changes in Mojave. I have reduced motion turned on and that also seems to help improve the reliability of autotype.

**Comment by HUGHUSR** [comment]
Testing in an ElCap VM, it is not a problem. Something changed in Mojave that is causing it to break. (Thanks, Apple!)

BTW, can you please label this post? Don't know how it got created w/o one.

**Comment by droidmonkey** [comment]
@georgesnow you win, I'm reverting back to Carbon API

**Comment by georgesnow** [comment]
The immediate workaround i would try is to use a hotkey for global auto type (Mac) that any apps you use doesn’t have assigned. Otherwise if the app uses that shortcut it could invoke auto type **and** shortcut for that app. That’s why in the case of certain text fields opt+/  will insert a division character(you can see on this page other reserves option shortcuts https://www.webnots.com/option-or-alt-key-shortcuts-to-insert-symbols-in-mac-os-x/). 

I believe you can add command key and in “most” cases you won’t have a conflict. Again mileages will vary since the hotkey is getting passed to the other active apps

**Comment by jgallias** [comment]
As soon as I revert to 2.4.3 it works normally again; 2.5.0 is broken, no amount of trying to adjust the hotkey, toggle settings, etc. work for me, only complete downgrade.

**Comment by jgallias** [comment]
Oh awesome; as of today 2.4.3 can no longer "copy" a password, it just minimizes the window!
So auto-type is broken 2.5.0, 2.4.3 minimizes the windows instead of copying... I guess I'm using 2.5.0 without auto-type until 2.5.1 since 2.4.3 is now literally unusable.

**Comment by georgesnow** [comment]
@jgallias do you have minimize on copy turned on? Maybe try turning it off on 2.4.3.

**Comment by jgallias** [comment]
@georgesnow 
WOW good catch, I didn't even see "Minimize when copying to clipboard" as an option: Looks like it got removed in 2.5.0

~/Library/Application Support/keepassxc/keepassxc.ini
MinimizeOnCopy=true

I deleted ~/Library/Application Support/keepassxc/keepassxc.ini to make it create a new file

Don't know how it got enabled, but maybe switching between 2.4.3 and 2.5.0 confused either app and it decided to set MinimizeOnCopy=true

Thanks! I'm working normally on 2.4.3 again for now.

**Comment by georgesnow** [comment]
Glad to hear you are at least working again

**Comment by l0f4r0** [comment]
Same issue here with KeePassXC 2.5.0 on macOS Catalina 10.15.1 (>Mojave)
