### ISSUE TITLE
Compile Flag To Disable Building/Installing Translations

### ISSUE THREAD

**Issue by 0pLuS0** [keepassxreboot/keepassxc#3739]
## Summary
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
Request for compile flag option to disable building/installing translations.

## Desired Behavior
[NOTE]: # ( Tell us how the new feature should work, be specific )
-DWITH_XC_TRANSLATIONS=[ON|OFF] Enable/Disable the installation of Translations support (default: ON)

## Possible Solution
[NOTE]: # ( Not required, but suggest ideas on how to implement the addition or change )
Just needs to be added/edited to the source code.

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
Some users do not need/require Foreign Translations...

I hope this request will be added in a future release.

THANKS

```P.S. I did do a search to see if there was a request on this already, I didn't see any. If I overlooked it sorry, I did try...```

**Comment by droidmonkey** [comment]
But why? Translations take up absolutely no space and "compile" in microseconds.

**Comment by 0pLuS0** [comment]
Well first let me say, I'm not certainly not here to make things more difficult, just asking for more flexibility with the source to allow this is all.

It's pretty common in Linux source, to have this ability, I guess you could say it's just a compile option like any other you find in source.

Please remember, those that compile from source do so, so they can have the choice of how they way their software to end up with all the various options enabled/disabled for various reasons...

Maybe in time this can be changed...


THANKS

**Comment by droidmonkey** [comment]
If you are comfortable compiling from source then you can just delete the install lines for the translations.

**Comment by phoerious** [comment]
This is clearly a WONTFIX. Translations do not add any significant weight to the compiled output, but are crucial to anyone using the application, including speakers of English.

The raw untranslated strings are English in nature, but not what's actually displayed on the screen. There is a reason why we have an explicit en_US locale (in addition to en_GB). Even though we write source strings in a language already resembling en_US, without the locale, you will not have proper plurals and you will also not benefit from after-the-fact fixes of wordings etc.

I also strongly object to adding any additional complexity to our build system for something like this, let alone making such an option on by default.

**Comment by 0pLuS0** [comment]
@droidmonkey

This? ---> ```#add_subdirectory(translations)```

THANKS

**Comment by droidmonkey** [comment]
Yes

**Comment by 0pLuS0** [comment]
@droidmonkey thanks, greatly appreciated! :+1:
