### ISSUE TITLE
KeepassXC-Browser not connecting

### ISSUE THREAD

**Issue by mlafois** [keepassxreboot/keepassxc#3741]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Browser extesnion should be able to connect to KeepassXC (Browser integration is enabled)

## Current Behavior
[NOTE]: # ( Tell us what actually happens )
After installing KeepassXC form apt and then removed it (becaused BrowerExtesnion said it is not up to date), then I swapped to the snap package of Keepassxc. I downloaded and ran "keepassxc-snap-helper.sh".

After that, etiher on Firefox or Chrome, the extension is not able to connect to keepassxc. When I click on the reload button ("Recharger" in french) it return "key exchange has failed" ("L'échange de clé a échoué." in french).

I removed the snap package then reinstalled it but with no success.
However didn't tried to reinstall Browser extension.

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )
For Chrome : 
 ~.config/google-chrome/NativeMessagingHosts/org.keepassxc.keepassxc_browser.json
"path" was pointing to "/usr/bin/keepassxc-proxy" but it is not existing on the system. I changed the value to "/snap/bin/keepassxc.proxy" and it's now working.
Firefox :
I did the same as above on the file :
~.mozilla/native-messaging-hosts/org.keepassxc.keepassxc_browser.json
And it worked

 I don't know if the trick I USED is a good idea or not but obvisously the root cause is that I don't have keepassxc-proxy in /usr/bin, no ? Or if me trick is good, the helper is not generating the good proxy path in the jsons

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
Not sure if previous apt installation is not responsible
1. Install keepassxc snap -> sudo snap install keepassxc
2. Download and then install helper -> sudo ./keepassxc-snap-helper.sh     
3. Try to use the extension

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - snap package
Revision: 2.5.0

Libraries:
- LIBS

Operating system: Ubuntu 19.10
CPU architecture: x86_64
Kernel: KERNEL : 5.3.0-19-generic

Enabled extensions:
- KeepassXC-Browser Chrome : 1.5.3
-KeePassXC-Browser Firefox : 1.5.3

**Comment by varjolintu** [comment]
Does KeePassXC has the following setting enabled: Browser Integration -> Advanced -> Update native messaging manifest files at startup?

**Comment by kaalk** [comment]
In KeepassXC this option is grayed out and not checked

**Comment by varjolintu** [comment]
Strange. That option should be enabled by default, especially with snaps.

**Comment by serebrov** [comment]
Looks like I have the same issue. 

I am on Ubuntu 19.04 and had keepassxc 2.4.3 installed from PPA and Chrome browser extension. 

Then I removed PPA version and installed 2.5.0 via `snap install keepassxc`, after that I started getting the "Key exchange was not successful" error in browser extension.

Now I edited the `~/.config/google-chrome/NativeMessagingHosts/org.keepassxc.keepassxc_browser.json` and changed `path` from `/usr/bin/keepassxc.proxy` to `/snap/bin/keepassxc.proxy` (@kaalk thanks for the tip) and it started working again.

**Comment by varjolintu** [comment]
Using the option said above should update those scripts manually to point to the correct location. Not sure why those are disabled for you.

**Comment by droidmonkey** [comment]
He is using a snap.

**Comment by thunderdome2** [comment]
Hello.

I downloaded the latest KeepassXC version from snap and I had to download the "keepassxc-snap-helper.sh" aloneside from GitHub. I think this can be useful to package this script directly into the package, either into the snap or DEB or RPM.

Thanks for this great work.

**Comment by droidmonkey** [comment]
We cannot include it in the snap because it must be run outside of the sandbox
