### ISSUE TITLE
Create Database dialog unusable on KDE with some themes

### ISSUE THREAD

**Issue by mcamou** [keepassxreboot/keepassxc#3743]
I am using the "Relax" KDE theme. When trying to create a new database, the Encryption Settings dialog shows up as light-gray text with a light-gray background (you cannot see the text)

![image](https://user-images.githubusercontent.com/87200/67966226-cdd68400-fc03-11e9-91d8-0a3a2090245f.png)

## Expected Behavior
The background color should be that set by the theme

## Current Behavior
The background is not the same color as that set by the theme, in this case it is the same color as the text

## Possible Solution
Respect the theme background color everywhere

## Steps to Reproduce

1. Using KDE, set the Relax theme
2. Press the New Database button on KeepassXC
3.

## Context
It is impossible to create a new database unless I change my desktop theme

## Debug Info
KeePassXC - VERSION
Revision: REVISION

Libraries:
KeePassXC - Version 2.5.0
Revision: 1ab8a9f

Qt 5.12.4
Debugging mode is disabled.

Operating system: Ubuntu 19.10
CPU architecture: x86_64
Kernel: linux 5.3.0-19-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.4

**Comment by droidmonkey** [comment]
We are using standard Qt widgets for this dialog. This is either a Qt problem or a theme problem. It is not a KeePassXC problem.

**Comment by phoerious** [comment]
This is most likely a problem with the Breeze Dark theme and should be reported there.
