### ISSUE TITLE
Documentation missing on KeeShare

### ISSUE THREAD

**Issue by JonTheNiceGuy** [keepassxreboot/keepassxc#3749]
[TIP]:  # ( Provide a general summary of the feature in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Summary
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
KeePassXC has a feature KeeShare that looks interesting, and could solve some issues around having multiple people all controlling their own security of their KeePass databases, but having shared data between several databases. Having done some research into how KeeShare works, it's clear that there's limited documentation on this, mostly in comments on other websites, and very little direct from KeepassXC - including nothing in documentation.

## Desired Behavior
[NOTE]: # ( Tell us how the new feature should work, be specific )
I would like to see some documentation on how KeeShare should work, some of the terms you're likely to see while progressing through, and what sort of workflow would occur if you were to enable KeeShare.

## Possible Solution
[NOTE]: # ( Not required, but suggest ideas on how to implement the addition or change )
I propose that if I can talk to some of the KeePassXC people who have built KeePassXC. I can author, or co-author some documentation about how KeePassXC works with KeeShare, including the workflow of someone who wants to share elements of their own KeePass file to peers, colleagues or family members. This would be incorporated into the bundled help file, the online documentation and/or the wiki.

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
There are two strings to this "bow". I currently use KeePassXC on my laptop, which synchronises with SyncThing to a home server. I and my wife both use KeePass2Android on our mobile phones, and these synchronise to the same home server using DropBox. I currently run an X desktop on my home server, and use KeePass2 on Ubuntu under Mono to synchronise these three disparate files into a temp directory, and then transfer the resulting file back to the three sync paths. Ideally, I would use KeePassXC on my laptop to hold credentials that are relevant to me on my laptop, and KeePass2Android on my mobile to hold an incomplete set of similar credentials that I'm likely to need from my mobile. My wife would synchronise just the resources she needs in her KeePass2Android on her mobile. I'd use the server with KeeSync to keep the three other databases in sync... Or, at least, that's how I envisage it happening!

In addition, I've discussed how, at work, we might consider using KeePass to share service account details between individual staff members who require access to those devices, but limit the access to only those who require access at any time, by using something like how I envisage KeeShare works!

Without more of an understanding of the workflow of KeeShare, I can't properly flesh out whether either use case actually matches the way KeeShare works, or if I have to rule out changing the way I do things.

**Comment by JonTheNiceGuy** [comment]
Apologies, it looks like this is in the [develop documents](https://github.com/keepassxreboot/keepassxc/blob/develop/docs/QUICKSTART.md#user-content-using-sharing). Is there any way to request this gets pushed into master and added to the next release?

**Comment by droidmonkey** [comment]
https://keepassxc.org/docs/KeePassXC_UserGuide.html#_database_sharing_with_keeshare
