### ISSUE TITLE
Reject junk URLs for browser integration instead of matching everything

### ISSUE THREAD

**Issue by piegamesde** [keepassxreboot/keepassxc#3751]
I just got a wrong URL match using the KeepassXC browser extension.

# Current behaviour

URL in question: `https://sso.tu-darmstadt.de/login`
URLs of matched entries: `http://https//aur.archlinux.org https://archlinux.org`, `https://passport.twitch.tv https://www.twitch.tv/` `https://sso.tu-darmstadt.de/login […] https://print.informatik.tu-darmstadt.de/user`

Among the correct entry, there are two false positives. If I allow the correct entry, it is filled in and I can log in. If I click on one of the false positives, it does not fill in and "Error: No logins found" pops up. If I check "Return only best-matching credentials", there still are the false positives, but the correct entry doesn't show up anymore.

# Expected behaviour

There are no false positives, only one suggestion. I think it is reasonable to expect that an url must match at least the first and second domain level `example.com` exactly to be sent over.

## Steps to Reproduce (for bugs)
I cannot reproduce this deterministically yet (you can try creating entries with the urls above), but this is not the first time this happens. When it happens, it is always with the same two false positives.

## Debug info

KeePassXC - 2.5.0
KeePassXC-Browser - 1.5.3
Operating system: Arch Linux
Browser: Chromium 78.0.3904.70

**Comment by libklein** [comment]
@varjolintu Do you have any plans on fixing this / rework the url validation/matching system? Thats something i'd like to do as well. If you have any ideas i'd be happy to discuss them, otherwise i'll just write up a pull request as outlined above tonight.

**Comment by droidmonkey** [comment]
This will be fixed for 2.5.1

**Comment by varjolintu** [comment]
@libklein I'm currently busy and cannot do much until next week. So if you have a proper solution ready, go ahead.

**Comment by varjolintu** [comment]
I got the fix working. So releasing a PR soon.

**Comment by txtsd** [comment]
@droidmonkey What version was the `Additional URLs` feature added in?

**Comment by varjolintu** [comment]
@txtsd 2.5.0.

**Comment by txtsd** [comment]
Thanks, it isn't included in the changelog.

**Comment by varjolintu** [comment]
@txtsd It is. Named as _Browser: Add initial support for multiple URLs_.

**Comment by txtsd** [comment]
Oh good.
