### ISSUE TITLE
Add a sponsor button in the repository

### ISSUE THREAD

**Issue by johanricher** [keepassxreboot/keepassxc#3753]
I'm currently a (very small) supporter on Patreon and I think you would have more people like me, users who are big fans of your work, actually donate some money if the option was more visible.

Adding a Sponsor button at the top of your repository's page is simple: https://help.github.com/en/github/building-a-strong-community/displaying-a-sponsor-button-in-your-repository#about-funding-files

Your `FUNDING.yml` would look something like:
```
custom: ["https://keepassxc.org/donate/", "https://paypal.me/jbevendorff", "https://flattr.com/@phoerious"]
patreon: keepassxc
liberapay: keepassxc
```

**Comment by droidmonkey** [comment]
We have a donate page on our website and a link to that page within the application. Thank you for the suggestion but we rather direct users to the donation page on our website for a more complete list of options.

**Comment by droidmonkey** [comment]
Sponsors button added, thank you!
