### ISSUE TITLE
Visual Inconsistency in password field of  "Unlock Database" screen

### ISSUE THREAD

**Issue by Nomadluap** [keepassxreboot/keepassxc#3756]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

When entering characters in the "Enter password" field of the unlock screen, I would expect that there be equal spacing between the character indicator dots. 

## Current Behavior
[NOTE]: # ( Tell us what actually happens )

When typing characters into the password dialog, the spacing between the dots is inconsistent. The dots seem to be visually grouped in a 2-1-2-1 pattern. See the attached image for an example.

![keepassxc-password-dots-display-issue](https://user-images.githubusercontent.com/561969/68031288-bfcf4480-fc91-11e9-8e42-91439f4cedba.png)

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )

1. Open KeepasXC
2. Open any Keepass database. You will be asked to unlock the database. 
3. Type any characters into the password field. You should notice the display bug.

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )

This is just a visual bug, however since it appears on the first screen most people see when using KeepassXC, I feel that it leaves a bad impression on the quality of an otherwise great piece of software. 
## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )

KeePassXC - Version 2.5.0
Revision: 1ab8a9f

Qt 5.13.1
Debugging mode is disabled.

Operating system: Windows 10 (10.0)
CPU architecture: x86_64
Kernel: winnt 10.0.17134
Screen Resolution: 3840x1080
Text Scaling: 100% (Recommended)
Settings -> Display -> Advanced Scaling Settings -> Let Windows Try to Fix Apps so they're not blurry: Off

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.5

**Comment by phoerious** [comment]
This is nothing we can fix. It's either a bug in Qt or with your font rendering.
