### ISSUE TITLE
Advanced Attributes Values Unreadable in macOS 10.14.6 on KeePass 5.0

### ISSUE THREAD

**Issue by HUGHUSR** [keepassxreboot/keepassxc#3757]
Using Light Mode on Mojave, the values of advanced attributes are nearly unreadable (too light of a color) and I can't figure out a way to darken them or change to a different text color.

Please see screenshot of a test entry.

## Debug Info
KeePassXC - Version 2.5.0
Revision: 1ab8a9f

Qt 5.13.1
Debugging mode is disabled.

Operating system: macOS Mojave (10.14)
CPU architecture: x86_64
Kernel: darwin 18.7.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
 libgcrypt 1.8.5

<img width="462" alt="Screen Shot 2019-11-01 at 10 41 35 " src="https://user-images.githubusercontent.com/46979127/68033893-07a49a80-fc97-11e9-9ad7-2567e02b9854.png">

**Comment by droidmonkey** [comment]
Restart the application after changing from light to dark theme
