### ISSUE TITLE
always on top

### ISSUE THREAD

**Issue by alfredo-ardito** [keepassxreboot/keepassxc#3758]
Window always on top feature (feature like the one in KeePassX)

![Screenshot from 2019-11-01 19-08-55](https://user-images.githubusercontent.com/6663326/68046703-c505b100-fcdc-11e9-9fc2-b0a68afa6f4e.png)

## Summary
If the 'always on top' option is set, keepassxc, once opened, should always stay on top allowing us to collect or view all needed information and to copy and paste whatever is needed.
Manually I can activate the Always on top feature by pressing "Alt+Space and T"

## Context
With the 'Always on top' option set, there would be no need to activate it manually pressing "Alt+Space, T"

**Comment by alfredo-ardito** [comment]
I'm actually using KeePassX and I appreciate a feature called 'always on top' 
is this feature missing here or is hidden somewhere?

**Comment by droidmonkey** [comment]
Please fill out the issue template.
