### ISSUE TITLE
List all Contributors and Translators in About Dialog

### ISSUE THREAD

**Issue by TheZ3ro** [keepassxreboot/keepassxc#376]
## Context
Right now in the About screen only KeePassXC maintainers are listed.
We need to make a list of Contributors and Translators in the About screen.
<s>Also we should add the KeePassXC Team copyright in every file header (that has been modified since the fork) and list all the contributor in the COPYING file.</s>

**Comment by droidmonkey** [comment]
Narrowed the scope of this issue, opened a new one for the file headers: #628

**Comment by Mogost** [comment]
The list of translators is very outdated for now.

**Comment by phoerious** [comment]
Indeed. We will update it for 2.3.
