### ISSUE TITLE
2.5.0 Doesn't Maintain Desktop Position

### ISSUE THREAD

**Issue by 0pLuS0** [keepassxreboot/keepassxc#3762]
## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
When placed in the center of the desktop it should remain in this position, and then stack on Top of Windows still in the center.

## Current Behavior
[NOTE]: # ( Tell us what actually happens )
When 2.5.0 is centered on the desktop, then minimized, then a browser is opened up, then I reopen up KeepassXC, it now opens up in the lower left of my desktop.

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )
2.4.3 would stack on top of Firefox and remain positioned in the center of the screen.
Revert back to the previous behaviour that 2.4.3 had?

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1. Center 2.5.0 on the desktop
2. Minimize 2.5.0
3. Open up a browseer
4. Open up KeepassXC, now it opens up in the lower left of my screen.

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )
It makes it more inconvenient having the window at the lower left to read and access, it is more comfortable centered on the desktop for easier access...

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.5.0

Libraries:
- LIBS
gcc-5.5.0 - qt5-5.9.8 - cmake-3.14.4 - qrencode-4.0.2 - argon2-20190702 - libsodium-1.0.18

Operating system: Slackware 14.2
CPU architecture: x86_64
Kernel: 4.19.78
Desktop: Openbox 3.6.1
Taskbar: tint2 - 16.7

Here is a screen shot when I have KeepassXC in the center of my desktop over the top of Firefox.

![center](https://user-images.githubusercontent.com/36190223/68061478-00b07300-fcfd-11e9-82e2-b975a1a42237.jpg)

Now I minimize KeepassXC to the tint2 system tray and then click on the tint2 system tray to open it back up and now it appears in the lower left of my desktop.

![lower](https://user-images.githubusercontent.com/36190223/68061506-2178c880-fcfd-11e9-8a23-5c54600b68be.jpg)

If I minimize Firefox and then reopen KeepassXC it does appear back on the desktop centered. The problem now is that it no longer wants to stack on top of another window/application in the center...

```P.S. I do have several applications I've been using in Openbox under Slackware that will stack on top of each other, staying centered. Openbox is a stacking window manager, unless the behaviour has been built into the UI to not respect position, then it will operate the way KeepassXC 2.5.0 is now doing, otherwise it should stack on top of another window/application.```

**Comment by 0pLuS0** [comment]
I find this really odd, for around 15 minutes it would constantly act in this manner, then I rebooted my system, logged back into Slackware, started KeepassXC and now it's staying in the center stacked over the top of Firefox...

Hmm odd

```On another Issue, has there been any Issues made in regards to the Password section cutting off text/characters under the General Tab?

If I click on the Eye to view many of my passwords they do not display properly.

I have several where it's being cutoff in the middle and displaying instead 3 dots ...

So if I have as an example a 32 character password like this;

9-~:>i/8v]^Mx7'K%zr<By@jkY[ap;42

I'll end up seeing it as example like this instead;

9-~:>i/8v]^...'K%zr<By@jkY[ap;42

The Mx7 part gets removed and replaced, many of them now look like this...

hmm

**Comment by droidmonkey** [comment]
We didn't change anything regarding window positioning in 2.5.0. This is definitely a slackware issue (if it is still an issue).

**Comment by 0pLuS0** [comment]
@droidmonkey it's not happenning now, really odd, not sure why and what cause it.

I'm still not seeing it...

SORRY for the ISSUE report.

Keep up the great work!
