### ISSUE TITLE
XML Import/Export in GUI

### ISSUE THREAD

**Issue by ghost** [keepassxreboot/keepassxc#3765]
As the title says, I am wondering whether there's any plan on implementing XML importing/exporting in the GUI since it is the only format that actually imports/exports all the data related to an entry (TOTP and other attributes) as opposed to CSV, where only the basic fields are imported/exported. Also, is the current CLI XML import/export stable yet? I mean are there any major bugs present in the current implementation? 

And is it possibly to add an import option in existing database? I think currently, to import a CSV/1Pass, we need to create a whole new database altogether.

**Comment by droidmonkey** [comment]
Agree, importing into the currently open database should be requested for all import options.

**Comment by digulla** [comment]
A great feature would be to support encrypted exports. The workflow should be like this:

- Recipient creates an "import request" (basically a key pair with a random passphrase stored in the DB).
- He send the request (just the public key part) to someone else
- A subset of all entries in the DB can be selected for export
- When exporting, there is an option to take such a request into account.
- The export is then encrypted accordingly
- File is sent to recipient
- During import, the private key is located in the DB and the file is decrypted

This way, passwords can be safely shared in work groups. Examples would be: Developers sharing a database account, support members sharing maintenance accounts, etc.

**Comment by oschihin** [comment]
Just to note, there is another issue and a remark (https://github.com/keepassxreboot/keepassxc/issues/3541#issuecomment-546700556)

My problem with that function is: You're asked for a password prompt, and then there's no writing of stdout to a file:
```
$ keepassxc-cli extract mypasswords.kdbx > bkp.xml
[emtpy promt, you do not see the question for your password]
[if you enter it, the question is written on top of the xml]
```

This is not very nice, even if there might be bigger cli-experts than myself. A GUI function would be very nice, as in KeePass (using that at work, where it is important to backup regularly to an encrypted drive)

**Comment by droidmonkey** [comment]
You need to update your KeePassXC, that was fixed.

**Comment by oschihin** [comment]
Thanks. Looks like ubuntu has an older version in their package:
```
apt show keepassxc
Package: keepassxc
Version: 2.3.1+dfsg.1-1
```

**Comment by droidmonkey** [comment]
This is implemented nicely in the CLI and there is no real reason to have this feature in the GUI. End users should never perform this action unless they know exactly what they are doing.

**Comment by Freeedim** [comment]
Sorry if I am mistaken, but as far as I can see in v 2.7.3, there is no import of XML., which makes this issue only half completed.

I am not sure what you @droidmonkey mean exactly in your last comment, but one example of use case is one of my clients needing to import many credentials, with advanced fields (email different from username, postal address) and expiration dates. It is not possible with a CSV, but at least I might convert the CSV in XML, which is quite easy, then I would be able to import it.

I have Debian (and only Debian), with a dpkg not recognising the zst compression for packages (long lasting issue). So I cannot install the package v2.7.x from the Ubuntu repository. The version in Debian repositories is 2.6.x, and the FlatPak 2.7.3 I've been using so far doesn't seem to provide a CLI. I guess I need to install Virtualbox and and set a virtual machine just for that import. I would be very glad to know if I missed something and if there is a simpler way in my case... T_T

**Comment by droidmonkey** [comment]
> one of my clients needing to import many credentials, with advanced fields (email different from username, postal address) and expiration dates

Just send them the kdbx file!

**Comment by Freeedim** [comment]
I only have their CSVs, which have been their only password management. I have just convinced them to switch to KeePassXC

**Comment by droidmonkey** [comment]
Also for the flatpak you need to use the cli like so: `keepassxc cli [parameters]`

Note the space

**Comment by Freeedim** [comment]
Maybe it's irrelevant (and sorry if it's the case, as I am quite a beginner. Since their CSVs have basically too many fields that seem not recognised by the CSV import tool, I think I need to convert them to XMLs with all the information, including advanced fields, then import those XMLs.

I did not know about the `keepassxc cli` thing. Thanks a lot for this tip!

**Comment by droidmonkey** [comment]
Yah sorry I reread your message after waking up a little. If you can script convert csv to properly formatted kdbx xml then that would be a useful tool indeed.

**Comment by Freeedim** [comment]
Yes. Unless it's easier for you to include more columns in the CSV import tool, and allow for custom columns like "advanced-xxx" where the values in the column would be stored in the "xxx" field of the advanced tab.

**Comment by droidmonkey** [comment]
#854 is dedicated to that topic, it's kind of messy no matter what you do (columns versus stuffed cells)
