### ISSUE TITLE
Database settings locks up window when database contains enormous entries

### ISSUE THREAD

**Issue by banym** [keepassxreboot/keepassxc#3766]
After upgrade to 2.5.0 on Windows x64 version the existing database settings can't be edited. When I try to open the database setting keepassxc hangs. 

Operating system: Windows 10
CPU architecture: amd64

Tried to copy the database -> no luck. 
Tried to save the database to new file -> no luck. 

Workaround I downgraded to 2.4.3 and everything works like before.

**Comment by droidmonkey** [comment]
Do you mean the Database -> Database Settings... Menu?

**Comment by banym** [comment]
Yes

**Comment by droidmonkey** [comment]
Hmm I wonder if one of your entries is causing the database statistics to fail. That was the big change to that menu in 2.5

**Comment by banym** [comment]
I traced it down to the entry causing the probem. Looks like some import or migration on that old database went wrong. The password field contained a 30057 character long string. The string consists of combined database entries as one long string. 

Removing the entry from the database fixed the problem.

**Comment by droidmonkey** [comment]
Oh wow! Well it still shouldn't hang, although that is surely an anomaly.
