### ISSUE TITLE
SSH key is not removed from pageant after database close with 2.5.0

### ISSUE THREAD

**Issue by banym** [keepassxreboot/keepassxc#3767]
When I use 2.5.0 my SSH-Key is not removed from pageant when database is closed.
It works with 2.4.3 like expected, same database opened with 2.5.0 does not work like configured. 

OS: Windows 10

**Comment by hifi** [comment]
I tested with the KeePassXC 2.5.0 Windows 64-bit MSI installer and the latest stable Pageant with a fresh RSA key generated with PuTTYgen.

In all cases adding and removing worked either by manually or automatically on close. There hasn't been much changes to the SSH Agent feature between 2.4 and 2.5 so I'm not sure what would be different.

**Comment by banym** [comment]
I created a new database file, migrated all entries and this works. Old database seems to have some issues.  
The old database was migrated from keepass2.
