### ISSUE TITLE
Entry toolbar buttons are disabled when interacting with preview panel

### ISSUE THREAD

**Issue by swalls62** [keepassxreboot/keepassxc#3770]
OS is Ubuntu 18.04.3 LTS
KeypassXC version is 2.5.0-1ppa1-bionic1
Whenever database is opened, the buttons are lit and then I select an entry then open the url the buttons go grey. This only happened after the update and I can't get it to work whether or not the SSH agent is enabled.

**Comment by droidmonkey** [comment]
I need a lot more information to help you. Don't delete the issue template, it's there for a reason. Screenshots would be immensely helpful.

**Comment by swalls62** [comment]
![Screenshot from 2019-11-03 13-08-17](https://user-images.githubusercontent.com/51415228/68090621-5f7c0680-fe3b-11e9-84c2-b0731a449cdc.png)
![Screenshot from 2019-11-03 13-04-40](https://user-images.githubusercontent.com/51415228/68090626-63a82400-fe3b-11e9-97e9-5f2789b3ce3c.png)

**Comment by droidmonkey** [comment]
Ah hah i get what you mean. I deleted your images to make sure your privacy is protected.

**Comment by swalls62** [comment]
That's it!

**Comment by ba32107** [comment]
@droidmonkey You should also remove the comment's edit history, the content is still available to see (sorry for pointing out publicly, but I thought it's still better than not saying anything)

**Comment by droidmonkey** [comment]
Good point, I forgot GitHub has a zealous history.
