### ISSUE TITLE
Add button to immediately expire an entry

### ISSUE THREAD

**Issue by mahescho** [keepassxreboot/keepassxc#3772]
## Summary
Add a check box to mark entries as disabled.

## Desired Behavior
When an entry is disable passwords should not appear in browser plugins and SSH keys should not be presented by the SSH agent.

## Context
Some times I want to keep old user names / passwords / SSH keys (my current use case) but no longer use them. Main purpose by now, prevent SSH agent from using my old keys for ssh-copy-id.

**Comment by droidmonkey** [comment]
You can just expire the entry. I believe we already exclude expired entries from the browser extension.

**Comment by varjolintu** [comment]
For browser extension, you can disable an entry using the option when editing enty: _Browser Integration -> [x] Hide this entry from the browser extension_.

**Comment by mahescho** [comment]
OK, thanks! I've found the option "Add key to agent when database is opened/closed". I will test if this does the trick too.

**Comment by wolframroesler** [comment]
How about adding "Now" to the "Presets" combobox next to the expiration date in the entry editor?

**Comment by droidmonkey** [comment]
I already solved this problem
