### ISSUE TITLE
QUESTION: Issue Report Deleted?

### ISSUE THREAD

**Issue by 0pLuS0** [keepassxreboot/keepassxc#3773]
I made a report yesterday over the General Tab and the password section cutting off replacing the password characters with 3 dot symbols.

Today I did not see the report here any longer, and I assumed if it was a duplicate it would of been listed as one and not deleted.

What happened to this Issue Report?

THANKS

```P.S. I did do a search for a similar issue and I did not see any...```

**Comment by 86423355844265459587182778** [comment]
Are you referring to [your comment in #3762](https://github.com/keepassxreboot/keepassxc/issues/3762#issuecomment-548996040)?
> The Password section is cutting off text/characters under the General Tab.
> 
> If I click on the Eye to view many of my passwords they do not display properly.
> 
> I have several where it's being cutoff in the middle and replacing characters instead with 3 dots.

**Comment by droidmonkey** [comment]
I didn't delete anything, probably just closed

**Comment by 0pLuS0** [comment]
@droidmonkey nothing in the closed section...

Hmm odd

Anyhow in 2.5.0 passwords, I'm not sure what length in character, the middle of the password is being replaced by ... 3 dots

Did anyone make an Issue report on this? If not I'll make it over...

THANKS

**Comment by droidmonkey** [comment]
What part of the GUI are you referring to? If it is the preview widget that is "by design"

**Comment by 0pLuS0** [comment]
I've attached a screen shot...

![keepassxc-password](https://user-images.githubusercontent.com/36190223/68166168-6731cd00-ff59-11e9-8e88-4f151dd28467.jpg)

Just after the letter ```p``` you'll see the 3 dots ```...```.

I hope this is not "by design" because having this preview is pointless, and I thought it was for quick/easy access when people needed to get at the password for whatever reason(s)...

Hmm

**Comment by droidmonkey** [comment]
The preview is not meant to be all encompassing. Edge cases like this break the layout, thus the ellipses. Although perhaps a QTextEdit with no border and transparent background would be best so that it could be "select all"'d

**Comment by 0pLuS0** [comment]
@droidmonkey I hope in the future we can preview the entire password, otherwise it might as well be removed...

Thanks
