### ISSUE TITLE
Window Unresponsive after opening pre-existing database in 2.5

### ISSUE THREAD

**Issue by propagating** [keepassxreboot/keepassxc#3774]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
KeepassXC window should maintain same performance after opening an existing database in 2.5

## Current Behavior
[NOTE]: # ( Tell us what actually happens )
KeepassXC window is extremely sluggish to navigate, freezing up when trying to move the window, not registering mouse clicks, searches, etc. 

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )
Creating a new database works fine, but attempting to merge an existing database into the new one results in the same behaviour. 

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1. Open KeepassXC 2.5
2. Open existing database
3. 

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )
KeepassXC 2.5 is unusable, but 2.43 works correctly.

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.4.3
Revision: 5d6ef0c

Qt 5.12.3
Debugging mode is disabled.

Operating system: Windows 10 (10.0)
CPU architecture: x86_64
Kernel: winnt 10.0.18362

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.4

**Comment by droidmonkey** [comment]
Are you accessing over network shares?

**Comment by propagating** [comment]
No, they are local files and a local installation.

**Comment by droidmonkey** [comment]
Can't say i experience that behavior at all on Windows 10

**Comment by propagating** [comment]
I haven't been able to pinpoint anything. I have a few items that have some small files (~50kb), and I have 10 or so different categories. 

Oh, I did find that if I right-click the icon in the taskbar, then right click again, it looks like there's dozens of clicks happening trying to click 'Open'. Only in 2.5 though

**Comment by cpowski** [comment]
I am seeing the same behavior in the official Arch Linux version. UI is very sluggish, almost unusable, keyboard shortcuts only work intermittently. The database is about 160MB and contains a few largish pdfs. Prior to this version the only slowdown occurred when saving, which was understandable.

**Comment by droidmonkey** [comment]
This is because of the hash file checking. Please revert back to 2.4.3 until 2.5.1 is released.

**Comment by phoerious** [comment]
160MB?! Wow. Our internal data structures (or rather the way we access the them) are still rather inefficient, because nobody has refactored that part since we forked from KeePassX. I was wondering if there are actually people with very large DBs, because that would require us to be a lot more efficient in how we work with the data in-memory. I guess if its just a moderate number of entries with large attachments, it's not a problem yet. But if you actually had 160MB in small entries, the whole application would be unusable all the time.

**Comment by propagating** [comment]
Oh, my database is 350MB....

**Comment by droidmonkey** [comment]
Dear God. My databases are barely over 50 KB. I strongly recommended that you move large files into an encrypted file storage container like cryptomator. The KDBX file is not meant for this much data!

**Comment by droidmonkey** [comment]
This is almost certainly due to the file hashing issue that is already fixed for 2.5.1.

**Comment by propagating** [comment]
I'll have to split out the passwords into multiple-databases then. Removing the files still results in ~105mb of text.

**Comment by droidmonkey** [comment]
Try limiting the size of the history in the database settings. You likely still have attachments in the history of entries. This is a large reason why storing large files in the database doesn't make sense. We should really heavily warn people before allowing large attachments.

**Comment by propagating** [comment]
The history was at the default max of 6mb. Disabling, saving, and reloading hasn't had an impact. 

Maybe disable attachments altogether if you don't want them being used? Most of the files stored were PGP keys which are rarely larger than 1 or 2kb. Even for the bigger files, 50kb isn't something I'd consider 'large'.

**Comment by droidmonkey** [comment]
How do you have 150 MB of text data? That's a tremendous amount of entries!

**Comment by propagating** [comment]
Yea, something is off. There are a few thousand entries, but that shouldn't be taking up that much space. 

Okay, it looks like notes in the oldest entries got corrupted or something to that effect. They had a huge amount of gibberish like this: "Ǣɽꋧ㗋ⲅ邹񇚷ث[򏜏ŧ뭆ٲJ񂳡񒒗̀႙׸쇲֨瘁򷑕ݧۄG􂠌𭂺jʩ㡫".  I'm assuming they all had notes previously, but I can't remember at this time.

I can't imagine it happened when I switched to using KeepassXC as there are other entries that existed prior to the switch that were fine.
