### ISSUE TITLE
Prefer most recent value when autocomplete username and don't autocomplete complete matches

### ISSUE THREAD

**Issue by c00** [keepassxreboot/keepassxc#3776]
In [this Pull Request](https://github.com/keepassxreboot/keepassxc/pull/3300) the feature for auto-completing usernames has been added. The Pull shows a screenshot of the settings dialog with an option under "Entry Management" to enable or disable "autocomplete username on typing". 
This option seems to be missing, leaving the user no way to disable this feature.

## Expected Behavior
In the settings dialog, I expect the setting to exist, as it was defined in the [pull request](https://github.com/keepassxreboot/keepassxc/pull/3300):
![image](https://user-images.githubusercontent.com/6259056/68080713-82a2b800-fe33-11e9-899f-895292e405b6.png)

## Current Behavior
Setting is missing:
![image](https://user-images.githubusercontent.com/6259056/68080711-6f8fe800-fe33-11e9-80db-67e93c670832.png)

## Steps to Reproduce
1. Open KeepassXc, 
2. Click the Settings icon in the taskbar
3. Scroll down to "Entry Management"

## Context
My usernames and email addresses often overlap. e.g. a common username in my database is `johndoe`, and a common email address `johndoe@example.com`. For some entries the email address is the username. For others, the username is just `johndoe`.
When adding a new entry, if I enter the name `johndoe`, it will autocomplete it to `johndoe@example.com`, which is not desirable.

## Debug Info
KeePassXC - Version 2.5.0
Revision: 1ab8a9f
Distribution: Snap

Qt 5.9.5
Debugging mode is disabled.

Operating system: Ubuntu Core 18
CPU architecture: x86_64
Kernel: linux 4.15.0-65-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.1

**Comment by droidmonkey** [comment]
It had a setting? I don't think that was ever in the code submitted. I also just noticed that PR removed a default config setting for no reason...

**Comment by c00** [comment]
I haven't checked the code, so I don't know whether the code was ever submitted, I can only see that the pull related to the feature showed intent for a setting (see the image). It's quite possible it was forgotten in actual code.

**Comment by droidmonkey** [comment]
So question for you. Would you rather the autocomplete prefer your default user / shortest match first? This would be in lieu of a setting to disable it altogether. We are trying to avoid settings creep, its bad enough already.

**Comment by c00** [comment]
Fair enough. I think the normal behavior of these types of fields, and something I could agree with is: a) prioritize more recent values first, but b) when the field is an exact match to any value, don't autocomplete. 

So if I'm typing `johnd` it can be completed to `johndoe@example.com`, because that's the most recent match used. But when I type `johndoe` it will not autocomplete to anything because that's an exact match to an existing value.

Does that make sense?

**Comment by droidmonkey** [comment]
Perhaps, I have to think about this

**Comment by droidmonkey** [comment]
Better tracked by #4029
