### ISSUE TITLE
Crash: Download favicon for URL

### ISSUE THREAD

**Issue by MalcolmHall** [keepassxreboot/keepassxc#3778]
Clicking on the icon "Download favicon for URL" for any BT site (e.g. https://home.bt.com/) crashes the application with a popup box with an address of memory could not be read. Click OK to terminate or CANCEL to debug.
![image](https://user-images.githubusercontent.com/57315162/68083651-03a58380-fe23-11e9-93ae-13d7fce075db.png)

Repeatable.

KeePassXC - Version 2.5.0
Revision: 1ab8a9f

Qt 5.13.1
Debugging mode is disabled.

Operating system: Windows 10 (10.0)
CPU architecture: x86_64
Kernel: winnt 10.0.18362

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.5

**Comment by varjolintu** [comment]
Can you provide a debug/crash log?

**Comment by droidmonkey** [comment]
I cannot replicate this on Windows 10, same website you mentioned. Tried all different methods to download the icon.

**Comment by MalcolmHall** [comment]
Still crashes everytime.
Just retried "https://home.bt.com/" and I now just get a crash without a windows warning.
If I try "https://signin1.bt.com/login/emailloginform" I get "Unable to fetch fabicon." as a orange banner.
No other sites fail.

Have also tried OpenSuse version (2.4.3) with a copy of the same database and it works OK.

Just noticed I have Qt 5.13 in my path. Interference perhaps? But why only on BT's site?

Sorry not much extra help.

**Comment by droidmonkey** [comment]
Can't say for sure, but if you are loading 5.13 instead of the bundled 5.12.4 then that would cause phantom issues.

**Comment by MalcolmHall** [comment]
Been investigating further.
The path is c:\qt513\5.13.0\msvc2017_64\bin
which is a slightly different version to yours.
Tried renaming 5.13.0 to 5.13.0.XXX which made no difference, still bombs out.
Tried an Admin download and re-install, but still no joy as either Admin or User.
Tried it on a completely different PC and it worked OK.
On the failing PC I uninstalled it and downloaded and run the "portable" version.
SUCCESS!
Will use that instead of the installable version.
Thanks for the help/app!

**Comment by droidmonkey** [comment]
Ok no problem

**Comment by JaneDougall** [comment]
This just happened on manjaro linux, kernel 5.5.15-1.
URL was "https://pinterest.***" - i was testing to see if i could use asterix as a wildcard for variations on .com - .ca etc

**Comment by droidmonkey** [comment]
Crash does not happen in 2.6.0-develop branch, thank you for reporting though!
