### ISSUE TITLE
Error cannot read and load kdbx files ( keepass ) after upgrading to 2.5

### ISSUE THREAD

**Issue by broros** [keepassxreboot/keepassxc#3781]
the app worked before, and after downloading version 2.5 I get the error message

```
Error while reading the database: Invalid credentials were provided, please try again.
If this reoccurs, then your database file may be corrupt.
```

macos 10.14.6

just to confirm the kdbx file opens in windows KeePass 2.43

**Comment by broros** [comment]
Badly designed interface... it's still telling me to select a file even after I already did


<img width="756" alt="Screenshot 2019-11-03 at 6 59 24 PM" src="https://user-images.githubusercontent.com/598228/68096214-87d02900-fe6c-11e9-9383-f1a8bb263693.png">

**Comment by droidmonkey** [comment]
That is for a key file, which can be used as a supplemental to your password. You missed the "Enter Additional Credentials" header just above this form element.

**Comment by broros** [comment]
the interface is very confusing ( especially the login screen), and hard on the eyes, everything is smushed together on the lists

**Comment by phoerious** [comment]
The thing that jumps to me is that the macOS theme appears to be incompetent at properly aligning widgets again.

**Comment by droidmonkey** [comment]
Would you mind mocking up an interface that would be less confusing from your perspective? We are working on a simple UI over in this issue thread: #3779

**Comment by rynnova** [comment]
Can confirm this is still an issue for me on Windows 10 Professional. Create a password file with default options, close it, try to open again, and get this:

![Passwords kdbx  Locked  - KeePassXC 11_6_2019 2_05_00 PM](https://user-images.githubusercontent.com/34715556/68329180-ba616800-009e-11ea-8aa5-4877f6ce0ae0.png)

**Comment by phoerious** [comment]
Please read the pinned issues. The key file field is not for your KDBX file.
