### ISSUE TITLE
Autotype doesnt work in active tab when multiple tabs open

### ISSUE THREAD

**Issue by rootion** [keepassxreboot/keepassxc#3787]
## Expected Behavior
When performing autotype with multiple tabs opened in the browser, KeePassXC should fill the log in details in the active tab.

## Current Behavior
When performing autotype with multiple tabs opened in the browser, if the active tab is not the first tab, KeePassXC will focus on the first tab and fill the log in details in that first tab, ignoring the active one.

## Context
It used to work in Mojave in KeePassXC 2.4
This issue happens in Firefox 71.0b6 (64-bit) and Chrome Version 78.0.3904.70 (Official Build) (64-bit)

## Debug Info
KeePassXC - Version 2.5.0
Revision: 1ab8a9f

Qt 5.13.1
Debugging mode is disabled.

Operating system: macOS 10.15
CPU architecture: x86_64
Kernel: darwin 19.0.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
 libgcrypt 1.8.5

## Operating system
OS Catalina 10.15.1

**Comment by droidmonkey** [comment]
What is your Auto-Type shortcut key? I bet it's the same shortcut as switch tab or select first tab.

**Comment by rootion** [comment]
Damn, that was it. I had it as ctrl + 1 which was fine in Mojave, but not anymore in Catalina. Changing the shortcut fixed it. Thanks so much for the hint.
