### ISSUE TITLE
Autotype spells username wrong

### ISSUE THREAD

**Issue by allan2** [keepassxreboot/keepassxc#379]
When I perform autotype, it spells my username wrong in the input field.

e.g. username in KeePass entry will be allan@domain.ca

Expected input field: allan@domain.ca
Results:: alaln@domain.ca

Using default sequence.

## Steps to Reproduce (for bugs)
1. Create entry
2. Edit entry -> Auto-Type -> Add Window title -> Autocomplete to match Firefox tab
3. Perform Auto-Type

* KeePassXC version 2.1.2
* Qt version: 5.6.2
* Gentoo stable, keepassxc keyworded ~amd64

Sometimes, when I try to reproduce this, autotype will take me to a different folder in my KeePass database instead of filling the matched window title.

**Comment by phoerious** [comment]
Does this happen reliably or does it just mix up characters randomly? What happens when you add a delay to your Auto-Type sequence?

**Comment by allan2** [comment]
The mixed up characters seemed reliable in order.
Now, the autotype always takes me to a different folder in my KeePass database. For one of my entries, it inputs my password into the search bar..

**Comment by phoerious** [comment]
I cannot reproduce this, but I suppose adding a slight delay between key presses may solve this issue. There is also a PR for KeePassX that adds a 100ms delay between each keystroke, thus I suppose you're not the only one having issues. I guess we could make the delay configurable.

**Comment by TheZ3ro** [comment]
You can test with the `{DELAY n}` sequence in autotype
