### ISSUE TITLE
Database is always marked as unsaved when using keeshare on Linux.

### ISSUE THREAD

**Issue by dssouza-ti** [keepassxreboot/keepassxc#3791]
## Expected Behavior
When I save a database with a shared group, the "save database" button should be greyed out:
![Selection_571](https://user-images.githubusercontent.com/16449739/68145387-6f1b4e00-ff14-11e9-88a9-c8e39b771459.jpg)

## Current Behavior
Currently, if I click the save button, it saves the database, but refreshes the unsaved state and enables the save button again:
![Selection_572](https://user-images.githubusercontent.com/16449739/68145572-db964d00-ff14-11e9-8487-38f99ac57ed3.jpg)

## Possible Solution
Don't know how to help.

## Steps to Reproduce

1. Share a group using keeshare.
2. Make a change and save the database.
3. Observe that the save database button is enabled again, as if there were unsaved changes.

## Context
I have a team that uses the same database on KeePass2 on a samba share utilizing the bidirectional sync option. When trying to move from KeePass2 to KeePassXC, we ran some tests and found this issue.

Since the share file is overwritten and the first changes are lost if more then one person saves the file before importing, this issue can lead to data loss due to human errors, as the user will see the enabled "save database" button and click it.

## Debug Info
KeePassXC - Version 2.5.0-snapshot
Build Type: Snapshot
Revision: a8c10cd

KeePassXC - Also tested with stable version 2.5.0 from the Ubuntu PPA and got the same results.

Qt 5.12.4
Debugging mode is disabled.

Operating system: Ubuntu 19.10
CPU architecture: x86_64
Kernel: linux 5.3.0-19-generic

Operating system: Also tested with Ubuntu 18.04 with Kernel 5.0 and got the same results.

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.4

**Comment by phoerious** [comment]
I recommend you turn on autosave, which defaults to on anyway.
You are also having weird issues with your icon theme.

**Comment by dssouza-ti** [comment]
> I recommend you turn on autosave, which defaults to on anyway.

I can't, because of what I described in #3790 

> You are also having weird issues with your icon theme.

That is my fault, I like to change the appearance of my desktop and install custom themes from time to time. :)
