### ISSUE TITLE
Add ability to duplicate / clone / copy group with subgroups

### ISSUE THREAD

**Issue by YogSottot** [keepassxreboot/keepassxc#3796]
[TIP]:  # ( Provide a general summary of the feature in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Summary
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
Add the ability to duplicate a group with subgroups.

## Desired Behavior
[NOTE]: # ( Tell us how the new feature should work, be specific )
Ability to duplicate a group with subgroups.

## Possible Solution
[NOTE]: # ( Not required, but suggest ideas on how to implement the addition or change )
![duplicate group](https://i.imgur.com/LnEe61R.png)

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
I use group template (skeleton) to create multiple entries with the same structure. In a subgroup of this template group, there is a templates records, which should also be copied.  
I rename duplicated group and fill the new values in the template record in the subgroups. This saves time.

**Comment by droidmonkey** [comment]
Not a bad idea

**Comment by michaelk83** [comment]
This would be covered by a more generic Cut/Copy/Paste ([#2074](https://github.com/keepassxreboot/keepassxc/issues/2074#issuecomment-828463235)). If there are actual templates, then maybe disable Cut for the templates.
