### ISSUE TITLE
Minimized KeePassXC does not restore window on "Reopen database"

### ISSUE THREAD

**Issue by archont00** [keepassxreboot/keepassxc#3797]
After clicking on "Reopen database" in Google Chrome browser extension, only a (desktop) notification appears and KeePassXC window remains minimized in dock.

## Expected Behavior
KeePassXC window should restore to foreground so that the user can open the database (by entering the key).

## Current Behavior
A desktop notification appears. KeePassXC icon in dock does not change (no blinking, etc.)

## Steps to Reproduce (for bugs)

1. Start KeePassXC, but do not open the database
2. Minimize KeePassXC to dock.
3. Start Google Chrome, click on Browser Extension "Reopen database"

## Debug info
KeePassXC-Browser Version: 1.5.3

KeePassXC - Version 2.5.0
Revision: 1ab8a9f

Qt 5.12.4
Debugging mode is disabled.

Operating system: Ubuntu 19.10 (Gnome)
CPU architecture: x86_64
Kernel: linux 5.3.0-19-generic

Enabled extensions:

Auto-Type
Browser Integration
SSH Agent
KeeShare (signed and unsigned sharing)
YubiKey
Cryptographic libraries:
libgcrypt 1.8.4

**Comment by varjolintu** [comment]
I reproduced it. Clicking the "Reopen database" a second time shows the application. I'm quite sure this has something to do how Gnome handles the notifications.

**Comment by droidmonkey** [comment]
This also happens in Windows

**Comment by varjolintu** [comment]
It seems macOS is not affected.

**Comment by droidmonkey** [comment]
macOS uses a different function call then windows and Linux. We might need to just add a delay in between raising the window and bringing it to the front.

**Comment by varjolintu** [comment]
This is going to be replaced anyway in the future: https://github.com/keepassxreboot/keepassxc/pull/3698

**Comment by bobblkabb** [comment]
Can't open tray minimized keepassxc. Works when I change icon set from breeze-dark to adwaita.

Operating System: openSUSE Tumbleweed 20200112
KDE Plasma Version: 5.17.5
KDE Frameworks Version: 5.65.0
Qt Version: 5.13.1
Kernel Version: 5.4.7-1-default
OS Type: 64-bit
Processors: 4 × Intel® Core™ i5-4590 CPU @ 3.30GHz
Memory: 15,5 GiB
