### ISSUE TITLE
bad installation on Windows 10 with version 2.5

### ISSUE THREAD

**Issue by ktrls** [keepassxreboot/keepassxc#3798]
Hi, I'm trying to updat may KeepassXC on Win10 but something goes wrong.

After upload of the 64 bit version .msi I try to lunch it and it runs. After that I check on the license agreement and go on.
Then I select the installation folder  (the default is ok, so overwrite current one) and after a click I click on the Install button.
The windows changes but appears a poupup with "Impossibile aprire il dispositivo o il file specificato" alert. If I click ok appeara a new popup that say the erro code is 2755

What am i do wrong?

Thanks in advance

**Comment by droidmonkey** [comment]
Do you have administrator permissions? Seems like it cannot write to the program file folder.

**Comment by ktrls** [comment]
Maybe you are right. It's very strange because all work fine.
I tried to install portable versione and it's ok but it doesn't write settings. I think that in my company have changed some policy on the disk....grrrr!

Thanks for your reply
