### ISSUE TITLE
Display and allow changing of database encryption parameters

### ISSUE THREAD

**Issue by e00E** [keepassxreboot/keepassxc#3802]
Keepass2 can change all encryption parameters (algorithm, key derivation function, iterations, memory, parallelism) for existing databases.

As far as I can tell as a new user, Keepassxc can neither display nor change these parameters for existing databases - only when creating a new one.

**Comment by phoerious** [comment]
Go to Database/Database Settings/Security.

**Comment by e00E** [comment]
Thanks. I was on that settings page and could not figure out. After looking again I noticed that I missed the advanced settings check box at the bottom left. Thats probably on me but maybe the ui could be more obvious.

**Comment by droidmonkey** [comment]
It's non obvious for a reason :wink:
