### ISSUE TITLE
[UX] Apply/Cancel/OK Button placement confuses users

### ISSUE THREAD

**Issue by huertanix** [keepassxreboot/keepassxc#3803]
## Summary
When training some users on using KeepassXC, a number of them clicked Apply when they meant to click Cancel when editing an entry.

## Desired Behavior
Users should have a button placement for editing entries that is more familiar to other similar applications. Lastpass and 1Password on macOS have the cancel button on the left (screenshots below).

![1password_button_placement](https://user-images.githubusercontent.com/72914/68244509-f7682480-ffe2-11e9-8945-abf136507edd.png)

![lastpass_button_placement](https://user-images.githubusercontent.com/72914/68244515-f9ca7e80-ffe2-11e9-97de-4ef14f85e671.png)

## Possible Solution
Move cancel button from the middle to the left; e.g. [Cancel] [Apply] [OK]

Additionally, it may be helpful to highlight what the default user flow's "next step" is likely to be, presumably this is the OK button, which may be a good idea to highlight in some way.

## Context
I am a digital security trainer at the Freedom of the Press Foundation. We help journalists learn good credential security practices, including learning how to use password managers. I would like to prevent my trainees from making mistakes that end up locking them out of their accounts.

**Comment by phoerious** [comment]
The placement of our buttons is in line with the UX guidelines of the respective platform. For Windows and KDE, it's OK/Cancel/Apply, for macOS and Gnome, it's the other way round.

**Comment by huertanix** [comment]
@phoerious At the moment, KeepassXC on Gnome places the cancel button in between Apply and OK. This Gnome HIG example for a window layout shows a Cancel button on the left, rather than in the center: https://developer.gnome.org/hig-book/unstable/design-window.html.en

**Comment by phoerious** [comment]
Those screenshots are wildly outdated. I cannot find any resources about the placement of Apply right now. The current HIG only mention two buttons of which Cancel should be on the left. Placing Apply further right would make sense to me, placing it to the left would be in line with how macOS does it (although I'm not entirely sure either if that is as per their HIG or simply how Qt does it). In any case, this would be a Qt issue and I recommend you report it there instead. The different layouts are documented here: https://doc.qt.io/qt-5/qdialogbuttonbox.html

**Comment by huertanix** [comment]
It may be worth consulting with a usability expert to determine if the Apply button should be removed altogether, as it has been in most other password managers.

**Comment by phoerious** [comment]
The password managers you showed are designed in a macOS-like fashion and violate the HIGs of other platforms. There is no one-size-fits-all, since different platforms have different standards, even if they are not perfect.

**Comment by huertanix** [comment]
@phoerious I understand that each platform has different HIG recommendations, however, I feel it is important to make adjustments to interfaces when they don't work with the expectations of users and cause mistakes to happen in using them. It may be worth keeping things simple with a familiar, relatively cross-platform standard of a Cancel and Save button.

**Comment by phoerious** [comment]
As I said, this should be fixed in Qt.

**Comment by droidmonkey** [comment]
Since the placement its 100% controlled by the qt framework you should Lodge an issue on bugs.qt.io

**Comment by phoerious** [comment]
Unless there are sources I missed that say otherwise, the reject role should be left of all accept roles if one were to sensibly generalise the Gnome HIG to more than two buttons. From what I can tell after a very short search, the same would be true for macOS. You should report that fact upstream mentioning that the current layouts may not be in strict compliance with platform standards

**Comment by huertanix** [comment]
Thanks, I'll discuss the issue with QT.

**Comment by phoerious** [comment]
That said, I do think you have a point nonetheless. I don't like the Windows and KDE button orders, but they are at least consistent and logical. The macOS and Gnome orders make no sense to me and I don't think Qt interpreted the platform HIGs the way their authors intended.
