### ISSUE TITLE
Add Unicode character support to password generation

### ISSUE THREAD

**Issue by sysrabbit** [keepassxreboot/keepassxc#3804]
[TIP]:  # ( Provide a general summary of the feature in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Summary
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
At the moment the vast majority of ASCII characters are supported for use in generated passwords. Ideally this could be expanded to the vast majority of Unicode characters.

## Desired Behavior
[NOTE]: # ( Tell us how the new feature should work, be specific )
To align with the current workflow, if the advanced option is enabled, the one or more buttons would be added to enable or disable Unicode character groups.

## Possible Solution
[NOTE]: # ( Not required, but suggest ideas on how to implement the addition or change )
This is trivial to actually implement support for as passwords are QStrings with each index being a randomly generated QChar following certain rules, and QStrings/QChars support UTF-16. I hijacked extended ASCII to show off that this is possible:

![Screenshot_20191105_221858](https://user-images.githubusercontent.com/38366556/68265601-88a6bd80-001a-11ea-8cd4-13a611eaf1fd.png)

However, supporting features such as disabling look alike characters is where most of the work will lie. Unicode introduces hundreds, if not thousands of look alike characters. The easiest solution would be to specify which characters are look-alikes for standard ASCII characters from an existing list, and ignore Unicode look-alikes.

Also Unicode characters could be divided in logical groups, i.e. shapes/icons, emojis, and various languages, to both add more configurability and reduce work when ensuring no look-alikes are missed.

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
Expanding the variety of characters used for generating passwords will increase the security of passwords. Also I really want emojis in my passwords.

**Comment by phoerious** [comment]
I don't really see how this would be useful. All that counts is how many bytes your password has, not how many bytes per symbol your alphabet allocates. I think extended ASCII provides a sufficiently compressed password format.

**Comment by droidmonkey** [comment]
How many services would mishandle your unicode password or simply reject it outright?

**Comment by borderm** [comment]
>I don't really see how this would be useful. All that counts is how many bytes your password has, not how many bytes per symbol your alphabet allocates. I think extended ASCII provides a sufficiently compressed password format.

Apologies, but I'm slightly confused by your statement. If I assume you're talking about how Unicode is technically 1-4 ASCII characters and that adding support for Unicode brings no extra security benefit, rather it just makes individual characters take more binary space, then you're technically correct. However, KeepassXC skips a number of ASCII characters as they are control characters, so Unicode would add some increased security at the very least.

There's also another benefit I forgot to mention in my initial request that is tangentially related, Unicode ranges compress the number of characters that you need to enter. 16 random Unicode characters are likely going to take at least twice as much binary space as 16 random ASCII characters, making the Unicode characters effectively closer to 32 ASCII characters in this particular example. Further, it may also be easier to enter 16 Unicode characters if you constrain them to say a language like Japanese or emojis than it is 16 random ASCII characters, especially those in the extended range.

>How many services would mishandle your unicode password or simply reject it outright?

Probably more than the number of services that mishandle or reject the extended ASCII range, which for the record I've had be accepted and then be told my password was invalid, sometimes requiring the site admin/support team to manually change it, and sometimes just straight-up send me to a server error page. Notably at the moment my NPM password doesn't seem to be able to be reset. Yet, that range is supported.

**Comment by phoerious** [comment]
> However, KeepassXC skips a number of ASCII characters as they are control characters, so Unicode would add some increased security at the very least.

Not really. Length is so much more important that no alphabet size. 

> Unicode ranges compress the number of characters that you need to enter.

As I said, extended ASCII should be compress the display size enough.

> Probably more than the number of services that mishandle or reject the extended ASCII range, which for the record I've had be accepted and then be told my password was invalid

That is very unlikely. All the characters generated by the password generator are already Unicode after all. What we call extended ASCII are in fact Unicode symbols with decimal codes between 161 and 255. If those aren't accepted already, why should Emoji, upside-down letters, Chinese, or Sanskrit script be?

**Comment by borderm** [comment]
>Not really. Length is so much more important that alphabet size.

While I agree length is incredibly important for a secure password, using an alphabet with a small number of characters increases the minimum password length needed to make cracking a password computationally infeasible. Of course, the current selection of characters is good enough to easily generate passwords that are computationally infeasible to crack, but I see no reason to stop at good enough when the amount of work required to make it even better is so low.

> That is very unlikely. All the characters generated by the password generator are already Unicode after all. What we call extended ASCII are in fact Unicode symbols with decimal codes between 161 and 255. If those aren't accepted already, why should Emoji, upside-down letters, Chinese, or Sanskrit script be?

Considering the extended range is constrained to the space of a single byte, I figure it's possible obscure backbends exist that handle that range correctly, but anything larger will cause an issue. I didn't mean significantly more, just more back ends would have issues. Thought toying around with c, it seems you have to go out of your way to achieve that, so I concede the number that will handle them differently is insignificant.

**Comment by phoerious** [comment]
A password manager's purpose is to take away the burden of remembering and typing passwords from the user. So why is having short passwords so important? Most password fields require at least 8 characters anyway, which is terrible little for a typical password. Now explain to the user when their password is sufficiently secure so the could use only 8 characters anyway. Why not just make a long password instead and let the password manager bother with it? I tend to make my passwords absurdly long, just because I can. Add to that the fact that many sites also still require specific ASCII characters to be present, others absent, and overall cannot handle any sort of non-ASCII properly, I often don't even turn on any fancy special characters. And for the handful of passwords I might need to type and remember anyway, I use a passphrase instead, because no matter if absurdly long or absurdly character-rich but short, I either couldn't type it correctly in due time or type it at all on a keyboard.

**Comment by txtsd** [comment]
> However, supporting features such as disabling look alike characters is where most of the work will lie. Unicode introduces hundreds, if not thousands of look alike characters. The easiest solution would be to specify which characters are look-alikes for standard ASCII characters from an existing list, and ignore Unicode look-alikes.

No one is going to memorize unicode passwords, so look-alikes are a non-issue.
