### ISSUE TITLE
cmd+f doesn't works

### ISSUE THREAD

**Issue by jspanos** [keepassxreboot/keepassxc#3805]
macOS: 10.15.1
KeepassXC: 2.5.0

I have been using keepassx for years and I just install KeepassXC but I have a very big problem. Search functionality doesn't seem to work at all. Every time I unlock my database the auto-search seems to work great and search among all the groups as expected. but if I want to perform a second search then nothing seems to happen. if I lock and unlock the database then I can search again. I install KeepassXC through brew.

Thanks.

**Comment by droidmonkey** [comment]
I can't replicate this behavior on any platform

**Comment by jspanos** [comment]
also there is no search bar where I can click and type

**Comment by droidmonkey** [comment]
Make your KeePassXC window larger. All your problems will be solved

**Comment by jspanos** [comment]
the windows is maximized

![image](https://user-images.githubusercontent.com/1932335/68521396-8d0aea80-0255-11ea-9ece-fe8073abf950.png)

as you can see on the ss if I search for github I am gettin results 

if I start navigating with my mouse through groups ctrl+f or cmd+f doesn't do anything anymore
there is no search bar prompt anymore 
![image](https://user-images.githubusercontent.com/1932335/68521439-da875780-0255-11ea-84b5-4c93bfb38474.png)
and only responds to single key presses like if I press t will get me to test record.
am I doing something wrong?

**Comment by droidmonkey** [comment]
When you click a group it cancels the current search.

**Comment by jspanos** [comment]
and how do I start a new search?

**Comment by droidmonkey** [comment]
Cmd+F

I'm really confused by this issue

**Comment by droidmonkey** [comment]
@jspanos Make sure your toolbar settings look like this:

![image](https://user-images.githubusercontent.com/2809491/68529110-07288700-02c9-11ea-89a9-f31f98865f1b.png)

**Comment by jspanos** [comment]
that works, now I have a search bar. Thanks a lot
