### ISSUE TITLE
Firefox integration still checks for KeepassXC updates

### ISSUE THREAD

**Issue by Germano0** [keepassxreboot/keepassxc#3808]
Ticket [Add compilation flag to disable updates check](https://github.com/keepassxreboot/keepassxc/issues/2887) was fixed with [this pull request](https://github.com/keepassxreboot/keepassxc/pull/2968) but I received e-mails from Fedora users saying that the Firefox integration still complains about KeepassXC. This happens because 2.5.0 has not been pushed to stable Fedora repositories because we will wait for 2.5.1, so many users get this message.

CC @droidmonkey

**Comment by droidmonkey** [comment]
You can disable update checks on the browser extension side. Two different components.
