### ISSUE TITLE
Since v2.5 serious lag

### ISSUE THREAD

**Issue by zetheroo** [keepassxreboot/keepassxc#3811]
Since upgrading from 2.4 to 2.5 there has been serious lag when using the program. Search, clicking around, opening creds, etc ... all very, very slow. I am using both locally and network stored DB's.

## Debug Info
KeePassXC - Version 2.5.0
Revision: 1ab8a9f

Qt 5.9.5
Debugging mode is disabled.

Operating system: Ubuntu 18.04.3 LTS
CPU architecture: x86_64
Kernel: linux 4.15.0-66-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.1

**Comment by droidmonkey** [comment]
This has been addressed already for 2.5.1

**Comment by zetheroo** [comment]
Where is the bug report which addresses this?

**Comment by droidmonkey** [comment]
It's resolved. 2.5.1 will be released tomorrow

**Comment by zetheroo** [comment]
Ah super. Thanks!

**Comment by darkwing1** [comment]
I was just going to say the same thing. Thanks.
