### ISSUE TITLE
Support other clipboard tools in CLI 

### ISSUE THREAD

**Issue by laur89** [keepassxreboot/keepassxc#3812]
[TIP]:  # ( Provide a general summary of the feature in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Summary
More clipboard tools should be supported on linux than `xclip`; I'd recommend adding support at least for `xsel`, but can't see why we couldn't also consider newer managers such as `copyq` (which is cross-platform).

**Comment by johnchen902** [comment]
Here is a workaround:

```
$ mkdir /tmp/test/
$ printf '#!/bin/sh\nwl-copy' > /tmp/test/xclip
$ env PATH=/tmp/test:"$PATH" keepassxc-cli clip password.kdbx /General/GitHub
Enter password to unlock password.kdbx:
Entry's password copied to the clipboard!
```

Replace `wl-copy` with the command you want to run.

Use `alias keepassxc-cli='env PATH=/tmp/test:"$PATH" keepassxc-cli'` and replace `/tmp/test` with a persistent directory to make it permanent.

**Comment by RaghavRao** [comment]
I tried this but I get "Unable to start xclip" on 2.5.4

**Comment by droidmonkey** [comment]
This was fixed in 2.6.0

**Comment by RaghavRao** [comment]
Thank you. The dnf repository is on 2.5.3 and the app image seems to
provide the GUI.

Is there an 'appimage' of the CLI?

**Comment by droidmonkey** [comment]
Yes it's part of the appimage
