### ISSUE TITLE
Add "unlock" to tray context menu

### ISSUE THREAD

**Issue by mahescho** [keepassxreboot/keepassxc#3813]
It would be nice to have an entry in the tray context menu to unlock the database.

The use case where this is handy: I've stored my SSH key in KeePassXC. My KeePassXC is configured to lock the database when my screen is locked. To unlock it I've to open KeePassXC first to get the unlock dialog and then KeePassXC stays open. Because I don't need it (I just want to use SSH) I've to close it again to get it out of the way. It would be nice to have an option to just unlock the database like in KeePass2 without keeping the main windows open.

**Comment by droidmonkey** [comment]
You want minimize after unlock which os covered by another issue already

**Comment by mahescho** [comment]
"minimize after unlock" will do for my use case where I use only one database.
