### ISSUE TITLE
But an extension for Opera????

### ISSUE THREAD

**Issue by xzj8b3** [keepassxreboot/keepassxc#3814]
But an extension for Opera????

It's a very popular browser, it's time to allow integration ....Chromium is getting heavier and heavier

**Comment by phoerious** [comment]
Opera supports Chrome extensions, so you can simply install it from the Chrome Web store.

**Comment by droidmonkey** [comment]
The native messaging json still needs to be deployed though

**Comment by phoerious** [comment]
Opera simply uses the Chrome one iirc, I might be wrong, though.

**Comment by xzj8b3** [comment]
> Opera simply uses the Chrome one iirc, I might be wrong, though.

Funktioniert es? Ich sehe es nicht wählbar in der Browser-Integration.

**Comment by xzj8b3** [comment]
> Opera simply uses the Chrome one iirc, I might be wrong, though.

Too bad it does not work, it is not selectable in integration browser also works

**Comment by xzj8b3** [comment]
> The native messaging json still needs to be deployed though

So what, impossible to use opera with KeePassXC?

**Comment by phoerious** [comment]
Please see #2879
