### ISSUE TITLE
Wait for KeePassXc to be closed to write the DB ?

### ISSUE THREAD

**Issue by blablanumerodeux** [keepassxreboot/keepassxc#3816]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
I'm expecting the DB to be wrote as soon as I do a modification on an entry.

## Current Behavior
[NOTE]: # ( Tell us what actually happens )
I see a 0kb db file written in the folder and I have to quit (Ctrl+Q) for the DB to be really written. 

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1. check the size of an existing db in a folder (let's call him A) 
2. open the DB and modify modify an entry 
3. check the size of the db
4. close keepass and recheck the size

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )
When my desktop crash, my DB is deleted

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.5.0
Revision: 1ab8a9f

Libraries:
- LIBS

Operating system: OS
CPU architecture: ARCH
Kernel: KERNEL

Enabled extensions:
- EXTENSIONS

**Comment by droidmonkey** [comment]
We don't hold open the file after it's written, this is probably an anomaly with your file manager. Do you have safe saves disabled?

**Comment by blablanumerodeux** [comment]
No, safe save is enabled

**Comment by blablanumerodeux** [comment]
I'm on Manjaro with thunar as a file manager

**Comment by droidmonkey** [comment]
I guarantee if you open that "0 KB" file in a text editor you'll see lots of data.

**Comment by blablanumerodeux** [comment]
okay, one thing i didn't mention is that i'm writing in a webdav folder mounted on /mnt/webdav.
I see the correct file size when i'm in /mnt/webdav (localy) but remotly, i see 0kb.
I have to wait for KeepassXC to be closed for the file to be written to the webdav host (remotly).

**Comment by droidmonkey** [comment]
We close the file after write. Likely a gvfs issue.
