### ISSUE TITLE
Enhance Auto Type behaviour Mac

### ISSUE THREAD

**Issue by XenitXTD** [keepassxreboot/keepassxc#3817]
[TIP]:  # ( Provide a general summary of the feature in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Summary
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
Adjust the behavior around Auto Type pop up window to better enhance user experience

## Desired Behavior
[NOTE]: # ( Tell us how the new feature should work, be specific )
The behavior around auto type makes it bring the main window to the forefront as well as the auto type window. This should be optional where you can set it to only pop up the auto type window

## Possible Solution
[NOTE]: # ( Not required, but suggest ideas on how to implement the addition or change )
So just change the behavior in the popup of the auto type window. I believe not to alienate those who are happy with the current behavior to make this an optional setting. Where when the auto type window pops up as it currently does don't bring up the main application window. Maybe add a button (optional) to the auto type window to bring up main window if somehow password is not in the list.

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
So I use multiple displays and it almost feels like the Auto Type pop up is linked to the main window (Tethered). And when you just want to have the popup to select the password to be used it pops up on the secondary display but because the main application window is on the primary display the application will launch from minimized state and show and if the full screen apps are open it will snap to desktop view... which is not what you wanted, you simply wanted to have the password input on the current active window and remain passive in the background waiting for your need to use it.

Sometimes it feels like the main window and the autotype window are fighting for focus... (Recent bug that required to remove default char input required you to click to app remove char and then click on the auto type window in that motion when you click back on the auto type window the focus moves to main window and you have to click a second time to keep focus on auto type window.

These little things don't bother you at first but continuously encountering them causes them to stack. And eventually it makes for a bad user experience.

**Comment by varjolintu** [comment]
AFAIK it's not possible to use just a popup with macOS. It always brings the main window to the front too.

**Comment by droidmonkey** [comment]
This is a macOS limitation (or a bug with Qt). I've already spent many hours trying to fix it.
