### ISSUE TITLE
Option to Enable Taskbar Icon and Hide from Doc

### ISSUE THREAD

**Issue by XenitXTD** [keepassxreboot/keepassxc#3818]
[TIP]:  # ( Provide a general summary of the feature in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Summary
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
Setting to Hide application in the dock when enabled on taskbar.

## Desired Behavior
[NOTE]: # ( Tell us how the new feature should work, be specific )
Option to enable the taskbar Icon (Currently Available) and then set the option to hide from dock so that the icon is not permanently in the dock. 

## Possible Solution
[NOTE]: # ( Not required, but suggest ideas on how to implement the addition or change )
Option to enable the taskbar Icon (Currently Available) and then set the option to hide from dock so that the icon is not permanently in the dock. 

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
This option is available in alot of applications and I was surprised when I started using the application that it didnt have this functionality and remains evasive in continuous updates.

This is a passive application, meaning that it mostly works in the background. yes users use it extensively at first setting things up but eventually once setup it moves into the background and becomes a passive application.

Like most people I keep only Active Applications in the Dock stuff that I am continuously working with and applications that act as passive tools (Caffiene, SnippetsLab, Docker etc) are set to only be on the taskbar as you dont actively run them and they exist in the background but if you need to access them you can find them on the taskbar... This is obviously user dependent and preference but I think this is a very good view to work from where a passive application should have a taskbar icon only option with nothing in the dock.

**Comment by droidmonkey** [comment]
This is a duplicate issur
