### ISSUE TITLE
Allow manual entry/editing of KeePassXC-Browser keys

### ISSUE THREAD

**Issue by Lantizia** [keepassxreboot/keepassxc#3819]
This is a FR based on an IRC chat with @varjolintu 

Essentially before they Key/Value bits were migrated from being an entry in the 'Root' folder to being a custom data section of the KDBX file (and thus available in 'Browser Integration' under Database settings...').  You could at least manually modify the existing Key/Values and also add in ones manually.

This is handy if you've got multiple PCs and might want to reuse a key value after a re-install or just want to better manage this data as you're testing newer versions of the extension, etc...

**Comment by dariopnc** [comment]
I'm using 2.6.4 on Windows 10 and I can't see how to manually edit the keys.

Even the commit doesn't seem to shine a light on how to do this

I don't know if I am missing something or is the issue is still relevant

**Comment by droidmonkey** [comment]
Double click on them

**Comment by dariopnc** [comment]
> Double click on them

Nothing happens both if I double click on the Key field of on the Value field.

Same goes with the _LAST_MODIFIED key, which is the only other key showing

**Comment by Lantizia** [comment]
Doesn't sound like you're in... Database | Database Settings | Browser Integration | Stored keys

I can double click fields under the 'Key' or 'Value' columns just fine now to edit them.

Haven't said that I now can't remember why I filed this feature request... but I'm sure I had a good reason :)

**Comment by dariopnc** [comment]
Thank you @Lantizia for your clarification, I was talking about other KeepassXC-Broser keys. I wrongly assumed this issue was referring to them.

I meant the one stored per credential, I'll open a new issue
