### ISSUE TITLE
CMake Error when compiling

### ISSUE THREAD

**Issue by bigbuffy** [keepassxreboot/keepassxc#382]
## Expected Behavior
Source should compile with Wiki instructions under Solus.

## Current Behavior
When compiling with the instructions I get this error:
```
~/Building/keepassxc/src/build` $ cmake -DWITH_XC_AUTOTYPE=ON -DWITH_XC_HTTP=ON -DWITH_XC_YUBIKEY=ON \
>     -DCMAKE_BUILD_TYPE=Release ..
-- The C compiler identification is GNU 6.3.0
-- The CXX compiler identification is GNU 6.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:20 (include):
  include could not find load file:

    GetGitRevisionDescription


CMake Error at CMakeLists.txt:21 (get_git_head_revision):
  Unknown CMake command "get_git_head_revision".


CMake Warning (dev) in CMakeLists.txt:
  No cmake_minimum_required command is present.  A line of code such as

    cmake_minimum_required(VERSION 3.6)

  should be added at the top of the file.  The version specified may be lower
  if you wish to support older CMake versions for this project.  For more
  information run "cmake --help-policy CMP0000".
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring incomplete, errors occurred!
```
KeePassXC does not compile.

## Possible Solution
not sure :(

## Steps to Reproduce (for bugs)
1.  Following the wiki https://github.com/keepassxreboot/keepassxc/wiki/Set-up-Build-Environment-on-Linux under Arch Linux. Installed all dependencies minus yubico-c yubikey-personalization. 
2. Following https://github.com/keepassxreboot/keepassxc/wiki/Building-KeePassXC
5. git clone https://github.com/keepassxreboot/keepassxc.git
4. mkdir build
5. cd build
6. cmake -DWITH_XC_AUTOTYPE=ON -DWITH_XC_HTTP=ON -DWITH_XC_YUBIKEY=ON \
    -DCMAKE_BUILD_TYPE=Release .. <<<<<< is where I get stuck.

## Context
Trying to build KeePassXC from the source as Solus does not package it. 

## Your Environment

* KeePassXC version/commit used:  latest pull
* Qt version (e.g. Qt 5.3): qt5 5.6.2-3
* Compiler (e.g. Clang++3.6.0): gcc 6.3.0-23
* Operating System and version: Solus (latest)

**Comment by TheZ3ro** [comment]
What version of CMake do you have?

**Comment by bigbuffy** [comment]
Ok I feel stupid.. your supposed to make the build dir in the root of the git source.. I have gotten a bit further now, but I ran into this error:
```
cmake -DWITH_XC_AUTOTYPE=ON -DWITH_XC_HTTP=ON  -DCMAKE_BUILD_TYPE=Release ..
CMake Error at /usr/lib64/cmake/Qt5Gui/Qt5GuiConfigExtras.cmake:9 (message):
  Failed to find "GL/gl.h" in "/usr/include/libdrm".
Call Stack (most recent call first):
  /usr/lib64/cmake/Qt5Gui/Qt5GuiConfig.cmake:158 (include)
  /usr/lib64/cmake/Qt5Widgets/Qt5WidgetsConfig.cmake:99 (find_package)
  CMakeLists.txt:165 (find_package)


```

Cmake version:
```
cmake --version
cmake version 3.6.2

CMake suite maintained and supported by Kitware (kitware.com/cmake).
```

**Comment by bigbuffy** [comment]
Found a rabbit hole of dependencies through googling.. sorry for the trouble. I'll figure out the exact packages needed from Solus repositories. Looks like a majority of stuff is not bundled like other operating systems.

**Comment by bigbuffy** [comment]
Here are all the build dependencies needed to compile on Solus successfully.

Might try to package it when I have time..
```
    - libxi
    - libxtst
    - libgcrypt
    - libyubikey
    - libglu
    - libglu-devel
    - qt5-base
    - qt5-x11extras
    - qt5-tools
    - qt5-tools-devel
    - yubikey-personalization
```

Thanks for the help!
