### ISSUE TITLE
It`s just not working.

### ISSUE THREAD

**Issue by David205u** [keepassxreboot/keepassxc#3821]
The irc chat is not working so i`m trying contacting someone here.
The whole problem is it wont work on my Linux Mint 64bit new install.
I keep getting the below error no matter what i do.
I tried to install using the terminal CLI but only downloaded or just went through the motions but i could not find it anywhere.
I downloaded fron Git etc. installed the FireFox extension but it wont work either, see below error messsage.
I went all through the Settings but could not get it to work.
I liked it because of the CSV import feature, but it does not work.
I also got a message Data Base is locked, i did set a Master Password & it`s the only thing that does work, but thats it nothing else does.

KeePassXC-Browser has encountered an error:

Cannot connect to KeePassXC. Check that browser integration is enabled in KeePassXC settings.

**Comment by droidmonkey** [comment]
Start here: https://keepassxc.org/quickstart/
