### ISSUE TITLE
The preview pane is not rich text, so it is cluttering the content

### ISSUE THREAD

**Issue by Tux** [keepassxreboot/keepassxc#3822]
In commit 1ceacdf6363a233d3 the type of the preview pane changed to Qt::RichText, but it is not
resulting in a cluttered and incomprehansible view:
![20191108121624](https://user-images.githubusercontent.com/2492/68475076-66ce5600-0227-11ea-9263-e744061d1cf9.png)
Reverting the `.ui` part of that commit:
```
diff --git a/src/gui/EntryPreviewWidget.ui b/src/gui/EntryPreviewWidget.ui
index 124923a7..db0231cf 100644
--- a/src/gui/EntryPreviewWidget.ui
+++ b/src/gui/EntryPreviewWidget.ui
@@ -502,9 +502,6 @@
                   <property name="text">
                    <string notr="true">notes</string>
                   </property>
-                  <property name="textFormat">
-                   <enum>Qt::RichText</enum>
-                  </property>
                   <property name="alignment">
                    <set>Qt::AlignTop</set>
                   </property>
```
will return to a useful view from which I can copy/paste:
![20191108130213](https://user-images.githubusercontent.com/2492/68475296-07bd1100-0228-11ea-9e2a-55acbab4e414.png)

**Comment by droidmonkey** [comment]
Already fixed

**Comment by Tux** [comment]
The (hot)fix still destroys the TAB's :(

**Comment by droidmonkey** [comment]
Will correct that
