### ISSUE TITLE
Option to remove favicon from a single entry or from all entries

### ISSUE THREAD

**Issue by imadockerman** [keepassxreboot/keepassxc#3823]
It's really a simple request. I have a large database and a good portion of the size goes to favicons. I would like to see an option to remove favicon from a given entry or remove them from all entries (similar to how we have a favicon installation implementation). Is it possible to push this in 2.5.1?

**Comment by droidmonkey** [comment]
You can already remove favicons from entries. They really shouldn't be taking up too much space, KeePassXC at least resizes them to 128x128 pixels.
