### ISSUE TITLE
TOTP does not automatically add base32 padding for Amazon secret keys

### ISSUE THREAD

**Issue by derekjc** [keepassxreboot/keepassxc#3825]
I'm trying to "setup TOTP" for my amazon login. It's failing with the error ```You have entered an invalid secret key. The key must be in Base32 format.
Example: JBSWY3DPEHPK3PXP```

## Expected Behavior
OTP key should be accepted

## Current Behavior
OTP key is invalid

## Possible fix
Automatically add base32 padding (like oathtool and other authenticator apps). For example, adding ==== to the keys below fixes the issue

## Steps to Reproduce
Generate an OTP key using Amazon. Following are examples(no longer in use).
5FT7WWLR3OWA26NWZ6DFCRLM3NGEWVUE7ZYWFMGCWBGJ7K3IEWDA
QGRCOIYTPUPG37U54CDNHJEZU323J7QV63ZMKOMVPT2CCA7ZVWYA

## Debug Info
KeePassXC - Version 2.5.0
Revision: 1ab8a9f

Qt 5.12.4
Debugging mode is disabled.

Operating system: Pop!_OS 19.10
CPU architecture: x86_64
Kernel: linux 5.3.0-20-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.4

**Comment by varjolintu** [comment]
This is fixed with https://github.com/keepassxreboot/keepassxc/pull/3622.
