### ISSUE TITLE
After 2.5.0 update - Notes are shown as one long line of text.

### ISSUE THREAD

**Issue by darkwing1** [keepassxreboot/keepassxc#3831]
## Expected Behavior
I expect to view the notes as i typed them in v2.4.3 with new lines, etc.

## Current Behavior
Currently notes are shown as one long line of text when viewed. However, if you go **into** one of the entries you can then see the notes as they were typed previously.

## Steps to Reproduce
1. Open your DB
2. View your notes that you typed into one of the entries
3. Notes are shown as one long line of text.

Please can you fix this soon? because its unbearable.  The solution to this until fixed is to keep opening up the entry to view your text with proper line spaces.

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.5.0 AppImage amd64

Operating system: Ubuntu 18.04

Enabled extensions:
NONE

**Comment by droidmonkey** [comment]
Fixed
