### ISSUE TITLE
Keeshare

### ISSUE THREAD

**Issue by daftracer4231** [keepassxreboot/keepassxc#3836]
When exporting database for Keeshare the structure changes.

## Expected Behavior
When exporting the group via keyshare I expected that all off the groups/structure would remain the same.

## Current Behavior
The passwords all go into one group in the exported DB.

## Steps to Reproduce
1.Export a group for Keeshare with sub groups.

## Debug Info
KeePassXC 2.5.0 

Operating system: Windows OS

**Comment by droidmonkey** [comment]
Duplicate issue

**Comment by daftracer4231** [comment]
If this is a duplicate issue where is the post were this was originally raised?

**Comment by droidmonkey** [comment]
Search for "keeshare groups"
