### ISSUE TITLE
"New Entry" right click glitch on KeepassXC 2.5.0 on MacOS

### ISSUE THREAD

**Issue by sunjam** [keepassxreboot/keepassxc#3839]
## Current Behavior
Occasionally, after selecting a right click option in an entry on MacOS 10.12 in KeepassXC 2.5.0, the menu options for all entries will change from usual _copy username, password, etc._ to only _New Entry_.  Only way to fix this behavior is to restart the application entirely.
![Screen Shot 2019-11-03 at 4 41 36 PM](https://user-images.githubusercontent.com/1787238/68554267-34b22500-03dc-11ea-9060-0ffcf5a5fd9a.png)

This problem can come up while browsing within the application or after switching away to another open application.

**Comment by droidmonkey** [comment]
This is due to a bug in Qt. You have to click the title bar of KeePassXC to regain "full focus"

**Comment by sunjam** [comment]
Has the bug already been reported?

**Comment by droidmonkey** [comment]
Interesting, I thought I had reported it but it looks like I did not :(

**Comment by sunjam** [comment]
> Interesting, I thought I had reported it but it looks like I did not ☹️

Do you need any help with reporting this?  Let me know if any assistance required with getting this addressed.  Thank you!

**Comment by sunjam** [comment]
Is this issue resolved @droidmonkey?

**Comment by droidmonkey** [comment]
It's a Qt bug and has been reported. This is actually a duplicate issue on our board.

**Comment by sunjam** [comment]
Please leave open until resolved, as this is an active problem.

**Comment by droidmonkey** [comment]
No you can refer to #3412
