### ISSUE TITLE
2.5.0 Appears to have corrupted my database when using in KeepassXC

### ISSUE THREAD

**Issue by jtandrew** [keepassxreboot/keepassxc#3840]
I upgrade to 2.5.0 earlier today on one of my Mac's.  It then proceeded to not accept my password to open and gave me the corrupt message.

I then proceeded to update on my other Mac and had the same issue.  I reinstalled 2.4.3 and it will not open with that version either now.

I also then rolled back my Key file to a version from a few days ago and it will not open as well.

## Expected Behavior
I would expect the file to open as usual.

## Current Behavior
I cannot open on either Mac with 2.4.3. or 2.5.0
I can open that same file on my iPhone

## Debug Info
KeePassXC - Version 2.5.0
Revision: 1ab8a9f

Qt 5.13.1
Debugging mode is disabled.

Operating system: macOS Mojave (10.14)
CPU architecture: x86_64
Kernel: darwin 18.7.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
 libgcrypt 1.8.5

**Comment by droidmonkey** [comment]
> I also then rolled back my Key file to a version from a few days ago and it will not open as well.

What does this mean? You change your key file regularly?

**Comment by jtandrew** [comment]
My file is in a synced Dropbox folder. I went into Dropbox and rolled back
to an old version.

I use the same file and have for several years.  I make a change to it
every several weeks with regular use but I wouldn’t say my use case is odd.

**Comment by Mixter338** [comment]
same problem. Had to restore the keyfile from Backup to open the Database with 2.4.3.

**Comment by droidmonkey** [comment]
Sorry for the confusion, a key file is an additional "password" in our terms. Did you mean the database file itself or an actual key file?

**Comment by Mixter338** [comment]
I mean the key file to open the database 
![keepass](https://user-images.githubusercontent.com/57625005/68589230-a7c6a480-048b-11ea-8d7c-d6ad45871003.JPG)

**Comment by phoerious** [comment]
We had the frequent problem that people were entering their KDBX file into that field.

**Comment by droidmonkey** [comment]
You cannot just change the key file without the database already being unlocked. I believe you also need to go to the master key setup and explicitly select the same (or different) key file to ensure your next save actually uses that key file. Otherwise you lock yourself out of the database same as if you were typing a different password.

**Comment by jtandrew** [comment]
Sorry my issue is the database file

**Comment by nrlnell** [comment]
I had same issue. Solved by deleting keepassxc folder ( C:\Users\username\AppData\Local\keepassxc)

**Comment by phoerious** [comment]
That's a different issue. See #3678

**Comment by jtandrew** [comment]
It appears this was user error on my part I was putting the kdbx file in the key file box as well as trying to open the key file.

**Comment by phoerious** [comment]
So it was the same thing after all?

**Comment by jtandrew** [comment]
With opening page interface change I was connecting to the database file
and then also putting the database file in the Key field. When I removed
the database file from that field it started working again.

**Comment by psantucc** [comment]
Drat. Not so for me - I never used a keyfile or entered a path to one, 2.5.0 or previous. Just the database file itself and a password.
