### ISSUE TITLE
Ugly cursor on Ubuntu 19.10

### ISSUE THREAD

**Issue by ba32107** [keepassxreboot/keepassxc#3841]
Since the 2.5.0 update, the mouse pointer is pretty ugly whenever I move it over the application window. It doesn't matter which cursor I choose in Ubuntu, it's always the same ugly one over the application. It does not happen if I move it over the title bar.

![1](https://user-images.githubusercontent.com/26036493/68567593-4681df80-0451-11ea-94e6-7e4342bca2e6.png)
![2](https://user-images.githubusercontent.com/26036493/68567594-4681df80-0451-11ea-9e3d-c9ba20cd450e.png)

## Expected Behavior
Mouse cursor should remain the same as the OS default.

## Current Behavior
Mouse cursor changes to a larger one, if I move it over the application.

## Steps to Reproduce
1. Open KeePassXC
1. Move the cursor over the application

## Debug Info
KeePassXC - Version 2.5.0
Revision: 1ab8a9f

Qt 5.12.4
Debugging mode is disabled.

Operating system: Ubuntu 19.10
CPU architecture: x86_64
Kernel: linux 5.3.0-19-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.4

**Comment by ba32107** [comment]
I will take a look into this in the next couple of days, but if anybody has any ideas, please let me know.

**Comment by phoerious** [comment]
This is a theming issue on your system, not much we can do from our side here. I would assume you are using either the AppImage or Snap, but your debug info says otherwise?

**Comment by phoerious** [comment]
BTW that cursor looks like the Ubuntu default cursor. I am pretty sure that if you try the same with other Qt-based apps, you will see the same problem. Please check if your custom theme is applied correctly to non-GTK apps.

**Comment by ba32107** [comment]
My KeePassXC is not installed as snap (nor AppImage), and I don't use a custom cursor. The black one is built into Ubuntu. However, I just tried again after a reboot and now it works correctly - not really sure what happened here.

**Comment by ba32107** [comment]
I can now reliable reproduce this. The issue only occurs if I set up KeePassXC to start at system startup. When I log in, KeePassXC is already runnig, and the cursor changes when I hover over the window. If I quit and relaunch the application, it's working correctly.

The application is **not** installed as snap or AppImage. I am using a custom theme, but I can reproduce this even if I switch back to the default Ubuntu theme. Also, the cursor is **not** the default Ubuntu cursor, in fact, no matter which cursor I choose in the Ubuntu settings, I can't find this exact same cursor. 

This suggests that the cursor is brought in by QT, but I'm not familiar enough with the details. The fact that it only happens if the application is launched at system startup might potentially suggest a bug.

Any advice?

**Comment by droidmonkey** [comment]
You are probably starting KeePassXC before the proper platform theme plugin environment variable is setup. Add a delay to KeePassXC startup.

**Comment by schlimmchen** [comment]
`X-GNOME-Autostart-Delay=` is not working for me (debian (bullseye)).

This stanza in your autostart `.desktop` file seems to be the best way to enforce a delay, which solves the problem for me.

```Exec=bash -c "sleep 1 && keepassxc"```

**Comment by jee-r** [comment]
@schlimmchen try this : 
```
X-GNOME-Autostart-Delay=2
X-GNOME-Autostart-enabled=true
```
it's work for me on debian bullseye gnome 3.38
