### ISSUE TITLE
Auto-type settings are missing in 2.5.0 using macos 10.12.6

### ISSUE THREAD

**Issue by neunzehnachtneun** [keepassxreboot/keepassxc#3842]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Current Behavior
[NOTE]: # ( Tell us what actually happens )
Since I installed tha latest update two things have changed. firstly keepassxc is asking to control my computer and secondly the auto-type tab of the general settings has disappeared. I attached two screenshots.

![Bildschirmfoto 2019-11-11 um 11 32 17](https://user-images.githubusercontent.com/18753899/68580839-13e6df80-046f-11ea-85dc-81864e85005a.png)

![Bildschirmfoto 2019-11-11 um 11 32 40](https://user-images.githubusercontent.com/18753899/68580864-23febf00-046f-11ea-9a89-ddb0caaa4c8c.png)

I don't know, maybe this is also related to #3737 and #3689, but as both issues are adressing a different macos version, I submitted a separated issue. Thanks in advance!

## Debug Info
KeePassXC - 2.5.0
Operating system: Macos 10.12.6

**Comment by neunzehnachtneun** [comment]
Well I just recognized, that this issue may be a duplicate of #3731.

**Comment by phoerious** [comment]
It is. These permissions are required for Auto-Type.
