### ISSUE TITLE
ENTER Key shortcut for Copy Password

### ISSUE THREAD

**Issue by rafafallo** [keepassxreboot/keepassxc#3843]
[TIP]:  # ( Provide a general summary of the feature in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Summary
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
It is very common to me pressing Enter after typing a string for search, as it is common way in many applications to run a search. As I usually search for an entry in order to copy the password, it is a bit annoying to me that KeypassXC opens the found entry for editing, because then I have to close the edition dialogue in order to copy the password.

## Desired Behavior
[NOTE]: # ( Tell us how the new feature should work, be specific )
I would suggest that either KeypassXC does nothing in response to pressing the Enter key or, maybe better, it copies the password of the found entry.

## Possible Solution
[NOTE]: # ( Not required, but suggest ideas on how to implement the addition or change )

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )

**Comment by droidmonkey** [comment]
You can press Ctrl+C to copy the password of the first entry directly in the search dialog. There is already an issue to ignore the enter key pressing.
