### ISSUE TITLE
Memory explosion on first password copy

### ISSUE THREAD

**Issue by maxolasersquad** [keepassxreboot/keepassxc#3847]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Expected Behavior
Memory use should stay sane

## Current Behavior
When KeePassXC is first loaded and the a password is copied for the first time then memroy usage exploads to about 20 gigs.

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1. Load KeePassXC
2. Select an entry
3. Type <ctrl><c> to copy the password
4. Computer freezes for about 10 minutes as the memory gets consumed.

## Context
I am running Ubuntu 18.04. This started with KeePassXC 2.5.1. The memory becomes unrecoverable and does not show up 

## Debug Info
[NOTE]: #
KeePassXC - 2.5.1

Operating system: Ubuntu 18.04
CPU architecture: 64-bit
Kernel: 4.15.0-66-generic

Enabled extensions:
- None

**Comment by maxolasersquad** [comment]
![Screenshot from 2019-11-11 21-29-57](https://user-images.githubusercontent.com/177150/68636796-bc765d00-04ca-11ea-8919-cd4095abe8f1.png)

Here's a screenshot from System Monitor after a fresh boot with only KeePassXC running. This acted a little different from usual, where I load up KeePassXC when I have a myriad of applications already up and running, but still documents there is a problem with the memory exploding the first time I copy a password.

**Comment by droidmonkey** [comment]
We didn't change anything here. Does the process manager show that KeePassXC is the cause?

**Comment by maxolasersquad** [comment]
When the memory is exploding my computer is frozen, so I can't check anything. Usually when my computer becomes responsive again I have about 10 gigs of RAM used and 10 gigs of swap used. No matter if I'm checking my memory with System Monitor, top, or htop, nothing shows what is using the memory. Only a reboot reclaims the memory.

The only real evidence I have is that this started the day I upgraded to 2.5.0 and only ever happens the very first time I copy a password. If I never copy a password then the problem never shows up.

**Comment by maxolasersquad** [comment]
I just tried rebooting my computer and copy various things. None of them had any negative effects.

**Comment by maxolasersquad** [comment]
It's also worth mentioning that I installed KeePassXC from https://launchpad.net/~phoerious/+archive/ubuntu/keepassxc

**Comment by droidmonkey** [comment]
From what version did you upgrade from?

**Comment by maxolasersquad** [comment]
Probably 2.4.3

**Comment by maxolasersquad** [comment]
I tried copying passwords, the first two caused a freeze for about 2 - 3 minutes accompanied with RAM usage that subsided after the freeze, just like in my screenshot. The third copy then caused this spike.

![Screenshot from 2019-11-11 22-10-33](https://user-images.githubusercontent.com/177150/68640288-40354700-04d5-11ea-810c-f78224a14356.png)

Where you see the RAM usage spike and then drop  a little is where you can see the computer become usable again, after about 10 minutes.

The applications I have open are Firefox, Natuilus, PHPStorm, gnome-terminal, System Monitor, and KeePassXC. As you can see from this screenshot I don't have any application eating up any sort of memory that would explain this.

![Screenshot from 2019-11-11 22-49-58](https://user-images.githubusercontent.com/177150/68640394-999d7600-04d5-11ea-8231-ac4876c6e544.png)

It's like the memory gets consumed, but no process owns it. Even if I close all applications, including KeePassXC, the memory usage remain. Only a reboot reclaims it.

**Comment by droidmonkey** [comment]
Can you try using the AppImage or Snap version to see if the problem follows

**Comment by maxolasersquad** [comment]
I installed version 2.5.1 from the Snap Store and had the same problem. I then tried the 2.4.3 version from Flathub and that one is not giving me any problems. After that one didn't show any issues I tried 2.5.1 from Flathub and that appears to be working. I'm not in a position where I can reasonably reboot, but when I can I will see if any issues show up after a reboot.

**Comment by phoerious** [comment]
I tried reproducing it, but I had a constant 117M memory consumption.

**Comment by maxolasersquad** [comment]
It have discovered that if I disable all of the Gnome 3 shell extensions except Ubuntu AppIndicators and Workspace Grid. I have tested with only enabling Dash to Dock, GSConnect, and Multi Monitors Add-On and each one individually enabled would cause the KeePassXC copy bug I'm experiencing. I also have TopIcons Plus and Ubuntu Dock installed. I have not yet tested individually enabling those two. It doesn't seem likely that it is these individual Gnome 3 extensions that is the bug, but maybe something that they are doing and with how KeePassXC handles storing passwords in memory and then purging after a set time.

**Comment by droidmonkey** [comment]
We do nothing special outside of Qt.

**Comment by hongquan** [comment]
@maxolasersquad  This is the issue of GNOME on Wayland. It happen with other applications on this environment as well (like when I use GPaste, Flameshot).

**Comment by maxolasersquad** [comment]
I checked and I am running Gnome on X, not Wayland.

**Comment by hongquan** [comment]
@maxolasersquad Ok. Then it is GNOME problem.
