### ISSUE TITLE
Is it possible to reference attachment in the URL?

### ISSUE THREAD

**Issue by braykov** [keepassxreboot/keepassxc#3851]
[TIP]:  # ( Provide a general summary of the feature in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Summary
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
I would like to be able to use a URL calling putty.exe with the -i flag and then pass the attached private key file. Is that possible at all? How do I reference an attached file?

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
I have entries for logging to various servers, I have created URLs in the form `cmd://C:\kitty\kitty.exe  {S:Host} -l {USERNAME} -i {my_privkey}`.

I would like to have kitty automatically login using the attached private key file.

**Comment by droidmonkey** [comment]
If kitty (lol) can work with ssh-agent then you should load the private key from the attachment into there using the KeePassXC ssh agent integration

**Comment by hifi** [comment]
Kitty is a fork of PuTTY so loading up Pageant with the SSH agent integration should work just fine.
