### ISSUE TITLE
Would it be possible to have a function to unlock / lock the databse by PAM events? Without Yubikey?

### ISSUE THREAD

**Issue by TheCataliasTNT2k** [keepassxreboot/keepassxc#3856]
It want to have a feature, to set  a function or any other hook in my PAM file to unlock database by PAM lock / unlock events just like my screensaver does.

## Possible Solution
Make a hook, or any other commandline option to unlock the database of an already running KeePassXC  instance, because I want only one instance running, and can not close it each time it should be locked. my browser does not reconnect automatically, even if I enable the option to do so, so I can  not reopen KeePassXC every time.

## Context
Would be great to have not to fill in the master password every time I need one of the stored passwords (I enabled automatic locking for security reasons)
I do not want to buy a Yubikey to archive  that :) I have other PAM devices.

**Comment by hifi** [comment]
When a database is locked it means it has been unloaded from memory and unlocking it means reading it from your hard drive and unlocking with the master password plus any combination of added key data.

Unlocking based on an event would be equal to not locking it in the first place as that would require keeping the unencrypted database in memory or keeping the unlock key data in memory which is closely equivalent to keeping the unencrypted database itself there. 

If you lock the database in addition to your desktop for security reasons there is really no secure shortcut to unlock it.

**Comment by TheCataliasTNT2k** [comment]
But how dows the system keyring work then? It does also store passwords doesn't it?
The only reason I am locking the database is that no one can access it, when I set my computer to sleep, or shut it down, if anyone takes out the drive.

**Comment by hifi** [comment]
If someone pulls your drive when your system is in sleep or shut down it will not contain an "unlocked" database, it's only unlocked in your system memory. The on-disk version is always encrypted.

**Comment by TheCataliasTNT2k** [comment]
So there is no possibility to unlock it via any command? I saw a solution, which uses the system's keyring to store the key and pipes it into an unlocking command, but the problem is, that it only works, if I restart  KeePassXC, it does not work on a running instance....
Here is the link:
https://github.com/keepassxreboot/keepassxc/issues/1405
Is this possible without starting an new instance? Then that  would be the solution... 
Maybe another command to lock the database of a running instance as well, but unlocking is much more important for me...

**Comment by kocjs** [comment]
#2089

**Comment by tmccombs** [comment]
The way unlocking the system keyring works is, it uses the user's password as the key to the keyring. Then there is a pam module that uses the user's password to unlock the keyring when the user enters their password to login. Typically the module will also update the keyring password when the user updates their password.

I don't think there is any reason a pam module couldn't do the same with keepassxc. Such a module could be a separate pronect from keepassxc itself.

Also, the keepassxc database could potentially be secured using a different password than the user account, if the master password was stored in a separate file, encrypted using the user's account password.

**Comment by droidmonkey** [comment]
This won't be implemented. We support dbus unlock and lock. We also support this through the command line of keepassxc.
