### ISSUE TITLE
Message notifying of database file changes right after saving

### ISSUE THREAD

**Issue by darkwing1** [keepassxreboot/keepassxc#3858]
This started happening after v2.5.1

On occasion after saving, i would get the popup asking me if i want to load the changes. i click yes.  But why does this pop up after random saves?

**Comment by droidmonkey** [comment]
Are you saving to a remote share?

**Comment by darkwing1** [comment]
No i am not saving to a remote share.
The only time i got multiple popups of these, is when saving and then making another change before closing keepassxc and saving again, and repeating this type of save event.  This never occured on versions before 2.5.0

**Comment by darkwing1** [comment]
I can disable the setting but this seems like a bug as the db is not being shared anywhere else.

**Comment by droidmonkey** [comment]
Yes there is a bug here, but need to replicate and track it down

**Comment by darkwing1** [comment]
I reproduced the issue again today.
- I opened KeepassXC
- Made a change and clicked Save.
- At this point, i did not close KeepassXC.  I made another change within a minute, clicked Save and after it saved, it threw the popup again.

**Comment by darkwing1** [comment]
Today i opened KeepassXC and edited an entry by putting a simple space in notes, pressed apply and it popped up with this message again.
Having ticked the box setting that you said, doesnt help, because after saving the DB, it continues to reload the DB as i can see a spike in cpu.
Again i want to say that this started happening, most probably more noticable after v2.5.0 (not 2.5.1)
I tried to reproduce this with a new DB, but with basic settings and i didnt get this popup as yet.

I tried one more time with my DB and what happened was when i clicked Apply, before clicking Save. KeepassXC crashed completely(for my first time). Related to this: https://github.com/keepassxreboot/keepassxc/issues/3933
Im pretty sure that these 2 issues are related in some way, as reading through the posts i figured out that the crashes started happening a few version before 2.5.1, same time more/less that this popup message has been happening after clicking Apply.  Also, it doesnt always happen, its intermittent same as the crashes.

Sorry if i am repeating most of the things i have already said, but i needed to report more of my findings.

DB settings are as follows:
chacha256
Argon2
900 rounds

I really hope you can find this issue. Its really difficult to reproduce at will.

How would i do a stacktrace?  Im willing to help as much as possible to find the issue as it is very annoying.
I am using the appimage Ubuntu 18.04.

**Comment by droidmonkey** [comment]
I believe to have fixed this in my latest PR and this issue is indeed the same as #3933. I am closing this one in favor of the other.

**Comment by darkwing1** [comment]
I just experienced this popup again on the latest version 2.5.2
I had it open, did a few edits, Saved the DB, then did another few edits, Saved the DB, did it once more and then the message pops up again!  All while keeping keepassXC open.
I dont think im the only one this is happening to.

**Comment by darkwing1** [comment]
I also just experienced a crash when deleting (by selecting 2 entries) from Recycle Bin, on 2.5.2
Ubuntu 18.04

The crashes still persist.

**Comment by darkwing1** [comment]
> I believe to have fixed this in my latest PR and this issue is indeed the same as #3933. I am closing this one in favor of the other.

@droidmonkey This is not fixed and i dont know how to troubleshoot this issue.
I dont usually save everyday. i save every couple of weeks, like now for example i just opened keepassxc and did ONE change, and after pressing apply and then pressing the SAVE icon, it saves and then pops up with the same message after which i have to press YES and then it takes another minute to save.
Can you please tell me how to debug this issue?  I cant be the only one having this issue.
Can you try reproduce?  (i didnt do anything special, it just happens RANDOMLY - this is the problem)
please assist.

**Comment by droidmonkey** [comment]
I meant fixed it in develop. Try using our snapshot to test https://snapshot.keepassxc.org
