### ISSUE TITLE
UI recent database issues

### ISSUE THREAD

**Issue by cslux** [keepassxreboot/keepassxc#386]
Hey everybody,

## Expected Behavior
1. When I click *Database -> Recent databases -> Clear history* the history is cleared from *Database -> Recent databases* and from the main view list widget *Recent databases*.

2. On startup select the recent databases instead of focusing the button *Create new database*, when there are recent databases.

3. When a recent database is selected in the main view list widget *Recent databases* the database should be opened on key *Enter*.

## Current Behavior
1. The *Recent databases* menu is cleared but the list widget *Recent databases* in the main view of keepassxc still shows the *Recent databases*, see picture below. After a restart, however, the main view list widget *Recent databases* is cleared too.
![keepassx-initial-view](https://cloud.githubusercontent.com/assets/1712313/23789917/3ac0eb44-057d-11e7-8569-e710ffa521e6.png)

2. On startup the button *Create new database* gets the focues, even though there are recent databases. 

3. Nothing happens when I press *Enter* on the selected recent database, instead I have to raise my hand from the keyboard and need to use the mouse, whhhaaatt... :-)

## Your Environment
KeePassXC - Version 2.1.3
Revision: 31494ec32796ed723cd5b772bae014cc6e8afe6c

Libraries:
- Qt 5.7.1
- libgcrypt 1.6.6

Operating system: Fedora 25 (Workstation Edition)
CPU architecture: x86_64
Kernel: linux 4.9.13-200.fc25.x86_64+debug

Enabled extensions:
- KeePassHTTP
- Auto-Type
- YubiKey

Thanks,

Christian

**Comment by TheZ3ro** [comment]
1. Ok, I can reproduce that

2. It's not really a bug. Depends on user workflow. 

3. We can add that, but currently the Recent database list isn't focusable with tab so you still need to click 1 time on one element to give it the focus so you can double click instead of single click

**Comment by cslux** [comment]
2. Yeah, right! You can ignore that
3. Hmm, are you sure? I can focus it by pressing 3x TAB after startup and can select the elements with the space key, but pressing enter doesn't do anything. As a side note, the buttons at the main view get triggered with the space key, so, I would either change the behaviour so everything gets triggered with the enter key or instead of highlighting (selecting) the recent database in the list widget with space, open it on space.

**Comment by droidmonkey** [comment]
I concur with the need to catch enter in the recent database view.

**Comment by TheZ3ro** [comment]
@cslux 
3. Ok I was missing the space step :sweat_smile:
