### ISSUE TITLE
libsecret error on Nextcloud

### ISSUE THREAD

**Issue by virtualdxs** [keepassxreboot/keepassxc#3860]
## Expected Behavior
Nextcloud stores its secret in the database and retrieves it in the future

## Current Behavior
Does not, and console errors with:
`libsecret-Message: 21:45:22.398: Remote error from secret service: org.freedesktop.DBus.Error.UnknownObject: No such object path '/org/freedesktop/secrets/aliases/default'`

## Steps to Reproduce
1. Enable KeePassXC libsecret integration
2. Install nextcloud client and run in terminal
3. Connect to a Nextcloud server and look at terminal output

## Context
I have to reauthorize Nextcloud each run

## Debug Info
KeePassXC - Version 2.5.0
Revision: 1ab8a9f

Qt 5.13.2
Debugging mode is disabled.

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 4.19.83-1-lts

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.5

**Comment by droidmonkey** [comment]
I believe this is fixed in 2.5.1. Please update.

**Comment by virtualdxs** [comment]
Upgraded; not fixed.

**Comment by droidmonkey** [comment]
Ping @aetf

**Comment by Aetf** [comment]
@virtualdxs After enabling the integration, did you expose any database group?

**Comment by virtualdxs** [comment]
Nope. I just figured out how to do that, and now it's working (for some definition of working, but this is a completely different issue). The process should probably be documented. Thanks for your work on this @Aetf !

**Comment by Aetf** [comment]
@virtualdxs  I'm glad it works for you. The process is indeed quite confusing at the moment. I'm working on improving the UI to make it more clear.

**Comment by nycex** [comment]
@virtualdxs How did you expose a database group? I can't find any option to do it?

**Comment by Aetf** [comment]
@nycex, it's a per-database setting so I placed it in the database's settings page: `Database` -> `Database settings` -> `Secret Service Integration`.
