### ISSUE TITLE
Crash after close of TOTP dialog

### ISSUE THREAD

**Issue by tegoo** [keepassxreboot/keepassxc#3862]
## Expected Behavior
Nothing happens

## Current Behavior
Sometimes crashes with segmentation fault:

```
QObject::startTimer: Timers cannot have negative intervals
Segmentation fault
```

## Steps to Reproduce
1. Create entry with TOTP
2. Show TOTP
3. Close TOTP dialog

## Context
- KUbuntu 19.10
- Recycle bin disabled
- History disabled

## Debug Info
KeePassXC - Version 2.4.3
Revision: 5d6ef0c

Qt 5.12.4
Debugging mode is disabled.

Operating system: Ubuntu 19.10
CPU architecture: x86_64
Kernel: linux 5.3.0-19-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (only unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.4

**Comment by tegoo** [comment]
Are there actions needed to be performed when the application crashes with segfault? For example, is some cleanup needed not to accidentally leave unencrypted database somewhere on the disk?

**Comment by droidmonkey** [comment]
When the application crashes the kernel reclaims the memory for re use elsewhere. Before another application gets allocated that memory space it is zeroed out.

**Comment by droidmonkey** [comment]
You should update to 2.5.1 before I will look into this issue. Closing for now.

**Comment by tegoo** [comment]
@droidmonkey, sorry for asking may be already answered question, but how do I check that no core dumps are created for the crashed keepassxc process?

**Comment by phoerious** [comment]
Coredumps are disabled for KeePassXC.

**Comment by tegoo** [comment]
@phoerious , as far as I understand in Ubuntu core dumps are automatically handled by apport (and potentially can be sent to Canonical for analysis):
```
$ cat /proc/sys/kernel/core_pattern 
|/usr/share/apport/apport %p %s %c %d %P
```
Is KeePassXC has some way to override it? How is it done?

**Comment by tegoo** [comment]
@phoerious , I have just checked, that for regular process core dumps are collected and written to /var/crash by joint effort of apport & whoopsie. 

So the question is still the same: how KeePassXC prevents this default system behavior?

**Comment by tegoo** [comment]
@phoerious , I have traced KeePassXC and found following in logs
```
prlimit64(0, RLIMIT_CORE, {rlim_cur=0, rlim_max=0}, NULL) = 0
prctl(PR_SET_DUMPABLE, SUID_DUMP_DISABLE) = 0
```
Is that the configuration to prevent core dump generation? Please, correct me if I'm wrong in my following understanding:

1. Program crashes
2. Kernel collects core dump
3. Kernel delivers collected dump to program or just writes to file according to /proc/sys/kernel/core_pattern. In case of Ubuntu Kernel delivers it to apport which handles report preparation and potentially sends it to Canonical.

- By executing prlimit KeePassXC prevents any further processing of crash on step 2. That means that no matter how any particular Linux distribution handles crashes, KeePassXC stops it on the Linux kernel level.

**Comment by droidmonkey** [comment]
This is where the core dumps are disabled in code: https://github.com/keepassxreboot/keepassxc/blob/d007ee97e3eb794a384776e75192126c857bf74f/src/core/Bootstrap.cpp#L129

**Comment by tegoo** [comment]
@droidmonkey , how user will see the warning message when KeePassXC is started by desktop shell and disabling core dumps failed? I guess application will just continue to run and user will have no visible indication that certain security mechanism is not enabled.

**Comment by droidmonkey** [comment]
A good question but only a small number of users even know what core dumps are or the ramification of them not being disabled.

**Comment by tegoo** [comment]
Yes, I understand. I just think that it might make sense to popup at least some message in UI saying "Warning: some security mechanisms are not activated, see logs for more details". For security aware user it might be beneficial. But yes, that will happen only in case system does not support core dumps / syscall fails. Do you think that would make sense to add it?

**Comment by droidmonkey** [comment]
Sure does
