### ISSUE TITLE
add path placeholders to autoopen functionality 

### ISSUE THREAD

**Issue by stingray21** [keepassxreboot/keepassxc#3863]
Would it be possible to add placeholders for the url of the autoopen functionality?

e.g. {DB_DIR}{ENV_DIRSEP}passwords.kdbx

This would it make easier to sync a database with a child database on multiple devices via file sharing services.

I know that currently relative paths work in KeepassXC, but they don't work in e.g. Keepass2Android. Vice versa, the path placeholders work in Keepass2Android but not in KeepassXC.

Keepass placeholders:
https://keepass.info/help/base/placeholders.html

**Comment by droidmonkey** [comment]
Interesting, this shouldn't be too difficult. The env dir sep is overkill though.

**Comment by stingray21** [comment]
I agree that it is not really necessary, but I included it because the placeholder exists in the keepass placeholder list. 
If placeholders are added anyways, I might not hurt to include it.

**Comment by stingray21** [comment]
Since I used KeepassXC for a while now, I thought I maybe should get started to contribute. I read the [Contributing  guide](https://github.com/keepassxreboot/keepassxc/blob/develop/.github/CONTRIBUTING.md), cloned the repo, made a local branch and tried to implement this feature.

This is the code I changed/added

`src/gui/DatabaseWidget.cpp` - line 1750
```
QFileInfo filepath;
        QFileInfo keyfile;

        QString pathUrl;
        pathUrl = entry->url();

        QFileInfo currentpath(m_db->filePath());
        QString databasePath = currentpath.absolutePath();
        pathUrl.replace("{DB_DIR}", databasePath );

        if (pathUrl.startsWith("file://")) {
            QUrl url(pathUrl);
            filepath.setFile(url.toLocalFile());
        } else {
            filepath.setFile(pathUrl);
            if (filepath.isRelative()) {
                QFileInfo currentpath(m_db->filePath());
                filepath.setFile(currentpath.absoluteDir(), pathUrl);
            }
        }

        if (!filepath.isFile()) {
            continue;
        }
```

It is very basic, but it works for me so far. So this might be a starting point.

I got sometimes a `[1]    24539 segmentation fault` when I changed the url and clicked *Apply*/*OK*, but I couldn't reliably reproduce the error.

I am no expert in c++ and haven't contributed to open source projects yet, but I'm happy to learn.

**Comment by droidmonkey** [comment]
Nice start, but you will want to add the DB_DIR detection within the Entry.cpp code. There is a function called replacePlaceholdersRecursive or something like that where this magic happens.

**Comment by stingray21** [comment]
Okay, I will look into that.

**Comment by stingray21** [comment]
I now have a first version that seems to work, but I have a question about the code. I had to change some lines in multiple files (core/Entry.cpp, core/Entry.h, and gui/DatabaseWidget.cpp). 
What would be the next step? Should I do a pull request or post the code here?

**Comment by droidmonkey** [comment]
See here: https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/proposing-changes-to-your-work-with-pull-requests

**Comment by stingray21** [comment]
Thank you, I made a draft PR, I hope this is okay the way I did it
https://github.com/keepassxreboot/keepassxc/pull/3901

**Comment by droidmonkey** [comment]
Yes its actually perfect!

**Comment by xandris** [comment]
> The env dir sep is overkill though.

Isn't it needed for interoperability between Windows and everything else? Or can you use forward slashes (/) everywhere?

**Comment by droidmonkey** [comment]
It's handled in the implementation
