### ISSUE TITLE
KeepassXC does not work as a libsecret provider for GNOME Online Accounts (GOA)

### ISSUE THREAD

**Issue by Taijian** [keepassxreboot/keepassxc#3864]
## Expected Behavior
When using KeepassXC as a libsecret provider and trying to access a Nextcloud Account via GOA, it will just work, i.e. GOA will store the credentials in KeepassXC and look them up from there.

## Current Behavior
When trying to access my Nextcloud account via GOA, I get queried for my credentials. I new database entry then gets added to the relevant KeepassXC folder (the one exposed as secret service folder). GOA then informs me that my credentials have expired and that I need to fill them in again. A new (second) database entry gets generated. GOA tells me that my credentials have expired.... (repeat until sufficiently bored/frustrated...)

I have noticed one difference in the way GOA stores secrets vs how other programms (e.g. Evolution, Nextcloud desktop client) store secrets. Whereas other programms seem to use the format of `password123` in the password field of the relevant KeepassXC database entry, what GOA stores is `{'password': <'password123'>}`. Apparently this is then not properly read back and so GOA refuses to coooperate with KeepassXC.

## Steps to Reproduce
1. Use KeepassXC as secret service provider under GNOME 3.34.1
2. Try to add a new Nextcloud account in GOA
3. Follow steps outlined above.
4. Bug happens

## Context
This makes me currently unable to use GOA with KeepassXC as the secret service backend.

## Debug Info
KeePassXC - Version 2.5.1
Revision: 0fd8836

Qt 5.13.2
Diagnosemodus ist deaktiviert.

Betriebssystem: Arch Linux
CPU-Architektur: x86_64
Kernel: linux 5.3.11-arch1-1

Aktivierte Erweiterungen:
- Auto-Type
- Browser-Integration
- SSH-Agent
- KeeShare (bestätigtes und unbestätigtes Teilen)
- YubiKey
- Secret-Service-Integration

Kryptographische Bibliotheken:
 libgcrypt 1.8.5

**Comment by Aetf** [comment]
@Taijian does this work for gnome-keyring? In my Ubuntu 19.10 VM, I can't get this to work even with the default gnome-keyring. I was using a trial instance from https://try.nextcloud.com
server: `https://try.nextcloud.com/uquuz1ae`
user: `ubuntu`
pass: `for#3864`

**Comment by Aetf** [comment]
On the other hand, adding a google account via GOA works well and I can access google drive in the file manager.

The google account also stores something similar: `{'authorize_code': <'code'>}`. So the password content should be the problem.

**Comment by Taijian** [comment]
> @Taijian does this work for gnome-keyring? In my Ubuntu 19.10 VM, I can't get this to work even with the default gnome-keyring. 

Yes, I had been using this setup for over a year with gnome-keyring. Deleting the old instance and re-adding the account did not help.

OTOH I have also not been able to add a google account to GOA. That one also keeps asking me for my credentials without ever doing anything else...

**Comment by Aetf** [comment]
> GOA then informs me that my credentials have expired and that I need to fill them in again. A new (second) database entry gets generated.

> That one also keeps asking me for my credentials without ever doing anything else...

Are you sure keepassxc is 2.5.1? The symptom looks really like the fixed #3729. If all attributes match (label, custom attributes, etc), the existing entry should be used rather than creating a new one. Are these entries exactly the same?

**Comment by Taijian** [comment]
OK, I cannot stress enough how embarrassed I am about this, but apparently this was a case of "have you tried turning it of and turning it back on again"... It now works, all that was apparently missing was a good, solid reboot.

Sorry for wasting your time, I'll try to do better next time.
