### ISSUE TITLE
Database file has been removed after update

### ISSUE THREAD

**Issue by antimech** [keepassxreboot/keepassxc#3865]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

My friend have a big problem finding his database after updating KeePassXC on Mac but I'm not a Mac-guy. It's also a mystery how he found himself in such a situation, I'm trying to solve it. Your help is welcome, thanks! He also got backup on external drive but this backup is very old.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
It should find the last used database automatically and open it after entering the password.

## Current Behavior
[NOTE]: # ( Tell us what actually happens )
The database file has been moved from "documents" in the app's folder (`/Applications/KeePassXC.app/Contents/`) and got removed after update.

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
These steps is created from the words of my non-tech friend and may be incorrect:
1. Install KeePassXC v2.5.0 (probably);
2. Save a database to documents folder;
3. Try open, it works;
4. ???
5. Try again, get "HMAC Mismatch"; This is possibly related to #3678 but it doesn't matter at this moment; It means this database is still exists;
6. Update KeePassXC to v2.5.1;
7. Can't open again, but this time the file is missing!
8. Use "Recent Databases" to wounder why the database has been moved to `/Applications/KeePassXC.app/Contents/Passwords.kdbx`; It looks like the database has been removed after updating the application data folder.

Operating system: Mac OS

**Comment by droidmonkey** [comment]
What? That is not the documents folder, that's the folder where the application is installed to. Documents is under /Users/[username]/Documents

**Comment by varjolintu** [comment]
Sounds like your friend has been using KeePassXC on macOS in a dangerous "portable" way - storing the database inside the application package.

Please, do not do this. Ever.

**Comment by antimech** [comment]
I'm sure we were saving it in documents for the first time, and he made some updates before this bug happens. I don't know how it's appeared in app's folder.

**Comment by antimech** [comment]
But It feels more like misclick or something because I wan't able to reproduce the bug.

**Comment by droidmonkey** [comment]
He should be able to recover the file using time machine. Its a macOS always on backup service.

**Comment by antimech** [comment]
@droidmonkey unfortunately the time machine history was clear, probably because it was disabled.
Anyways I'm about to approach cyber crime forensics way. He is got FileVault enabled, so I have to make a backup of whole drive and decrypt it manually:
https://github.com/libyal/libfvde/wiki/Mounting
then try to restore the file.

**Comment by droidmonkey** [comment]
Good luck, although ANY overwrite to the files bits will prevent you from opening it.

**Comment by antimech** [comment]
I know it, thanks!
