### ISSUE TITLE
KeepassXC uses wrong keyboard layout during autotype

### ISSUE THREAD

**Issue by reyabo** [keepassxreboot/keepassxc#3866]
# Summary
After a reboot KeepassXC uses the wrong keyboard layout during autotype. Need to restart the program to fix it. 
 
## Expected Behavior
KeepassXC uses the right layout (german)

## Current Behavior
Uses wrong layout

Operating system: Kubuntu 19.10
CPU architecture: 64bit
Kernel: KERNEL5.3.0.23

**Comment by droidmonkey** [comment]
This is a duplicate issue.
