### ISSUE TITLE
KeeShare duplicates file extension for new shares

### ISSUE THREAD

**Issue by PechenTreski** [keepassxreboot/keepassxc#3867]
When I create a new group and make it synchronizable, I give the new shared DB a name in a built-in Macos file dialog. KeepassXC appends ".kdbx.share" extension twice.

## Expected Behavior
The full file name must be foo.kdbx.share

## Current Behavior
The filename is foo.kdbx.share.kdbx.share

## Steps to Reproduce
1. enable KeeShare
2. create a new group
3. choose a path for the shared db (either with a file dialog or type a path manually)
4. click OK
5. take a look at the extension of the new file

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.5.1
Revision: release

Operating system: Macos 10.14.6

**Comment by alphaman64** [comment]
This is still an issue on macOS 10.15.3 Catalina, and there doesn't appear to be a satisfactory work-around.

**Comment by droidmonkey** [comment]
Does this occur only when the extension is added manually in the dialog?

**Comment by alphaman64** [comment]
No, when it's added automatically. Trying to add a .kdbx.share file to another db results in the file extension being truncated to .kdbx in the file selector dialog, but still seeing doubled file extensions in the Path field.
<img width="953" alt="Screen Shot 2020-02-27 at 15 01 32" src="https://user-images.githubusercontent.com/7073322/75487462-08fb8080-5974-11ea-9f37-5bc20e824636.png">
<img width="1189" alt="Screen Shot 2020-02-27 at 15 01 58" src="https://user-images.githubusercontent.com/7073322/75487473-0bf67100-5974-11ea-97f2-7bc8a6c4ab9d.png">
<img width="953" alt="Screen Shot 2020-02-27 at 15 05 29" src="https://user-images.githubusercontent.com/7073322/75487479-0dc03480-5974-11ea-99d0-a2cb62042763.png">
<img width="1189" alt="Screen Shot 2020-02-27 at 15 06 22" src="https://user-images.githubusercontent.com/7073322/75487485-10bb2500-5974-11ea-8211-8b01d488b54b.png">

**Comment by droidmonkey** [comment]
Fixed in 2.7.0
