### ISSUE TITLE
Clearly explain why Auto-Type is disabled under Wayland

### ISSUE THREAD

**Issue by bastiaanb** [keepassxreboot/keepassxc#3868]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
1. Working Auto-Type, i.e. control-shift-V works and is shown in context menu. I know this depends on Wayland support, so absent that, I woud expect:
2. Greyed out Auto-Type button / context menu, with eplanation in hover text, or similar.

## Current Behavior
[NOTE]: # ( Tell us what actually happens )
Upgraded to Fedora 31, with KeePassXC 2.4.3. Auto-Type was still visible, but partially broken (failing for pasting in FireFox, but still working in Chrome). 
Upgraded to KeePassXC 2.5.1. Auto-Type function has vanished without explanation. Gone from context menu, control-shift-V, etc. Auto-Type config is still present in entries and settings.
Release Notes do not mention anything.  

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )
Document this in the app, or at least in the release notes instead of having people hunt for explanations. Eventually I found #3520. 

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1. Install KeePassXC 2.5.1 in Fedora 31 running Wayland
2. Open database
3. Search for a way to perform Auto-Type
4. Fail to find it

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )
Can no longer use Auto-Type with Chrome. 

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.5.1
Revision: 0fd8836

Qt 5.12.5
Debugging mode is disabled.

Operating system: Fedora 31 (Workstation Edition)
CPU architecture: x86_64
Kernel: linux 5.3.11-300.fc31.x86_64

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.5

**Comment by latchr** [comment]
I have run into this issue. I had Keepassxc working fine on Fedora 30 (I don't know what version of Keepassxc that was). I have just upgraded to Fedora 31 (gnome, wayland) and now the auto-type is broken in Keepassxc.

The autotype tab in settings is gone, and the autotype entry in the right-click drop-down menu is also missing. I could see no explanation until I found this thread, and now it seems (vaguely) that there is a compatibility issue with Wayland.

However, I certainly had autotype working with Fedora 30, which was also wayland.

**Comment by lvanderree** [comment]
@latchr I installed an older version of Keepassxc which still works fine on wayland in fedora 31. But you can also install (the original) keepass which can also auto complete without any problem

**Comment by cwmke** [comment]
I just stumbled into [ydotool](https://github.com/ReimuNotMoe/ydotool) when looking at Wayland options for autotype. Is this something that could work for Keepassxc?

**Comment by droidmonkey** [comment]
Probably not because it is not actively maintained and most likely requires root permission.

**Comment by cwmke** [comment]
Last commit was a couple days ago but I missed the part about /dev/uinput needing root. Oh well.

**Comment by latchr** [comment]
@lvanderree I used `sudo dnf install keepassxc-2.4.3-6.fc31` to downgrade to an older version (this was the only other option when I did `sudo dnf --showduplicates list keepassxc` ). With this older version of Keepassxc I do have the autotype tab in the settings dialog, but when I press that key combination with a Firefox window in focus nothing happens. Do I need to do something else to get autotype functioning again?

**Comment by phoerious** [comment]
Wayland is unsupported and the old version enforces X11, which is why it works. Set QT_QPA_PLATFORM=xcb or start KeePassXC with the -platform xcb.

**Comment by Thatoo** [comment]
> Wayland is unsupported and the old version enforces X11, which is why it works. Set `QT_QPA_PLATFORM=xcb` or start KeePassXC with the `-platform xcb` flag

How to do that when we launch the appimage?

**Comment by Thatoo** [comment]
The interesting part for me is that autotype works when I ask keepass to autotype in a "password" field (master password when Thunderbird launch) but not if I want it to autotype in a text edit or the terminal (too bad for ssh passphrase).
I really hope a solution will be find or keepassXC will loose interest under wayland.

**Comment by phoerious** [comment]
You can auto-type from XWayland into other XWayland windows.

**Comment by Thatoo** [comment]
So we should wait for KeepassXC to be fully working under Wayland which is needed as from the next Firefox and Thunderbird version they will launch with Wayland for what I understood.

What about this solution : https://github.com/rockihack/keepassx/tree/wayland-autotype/src/autotype/wayland ?

**Comment by Thatoo** [comment]
Is it not the same bug as https://github.com/keepassxreboot/keepassxc/issues/2281#

**Comment by droidmonkey** [comment]
Added this to our documentation.
