### ISSUE TITLE
Application error when pressing enter twice after logging into KPXC

### ISSUE THREAD

**Issue by john3voltas** [keepassxreboot/keepassxc#3872]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
After pressing enter to log into KPXC, I would expect to enter the application.
After pressing enter twice on the login, I guess KPXC would either just show the main window as usual or maybe open the first record on the database.

## Current Behavior
[NOTE]: # ( Tell us what actually happens )
After pressing enter twice on the login, the application crashes, prints out an error message and then it disappears. No trace of the app in taskmanager.
Link to a print of the error message: https://imgur.com/SxRcGw8

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )
I don't know because I don't have programming skills.

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1. Open KeepassXC application in Windows 7.
2. Select a *.kdbx database
3. Enter the password and at the end type enter twice instead of a single time

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )
I accidentally typed enter twice and found the issue.
It doesn't affect me at all.

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.5.1
Revision: 0fd8836

Qt 5.13.1
Debugging mode is disabled.

Operating system: Windows 7 SP 1 (6.1)
CPU architecture: x86_64
Kernel: winnt 6.1.7601

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.5

**Comment by john3voltas** [comment]
Thanks @droidmonkey .
Cheers

**Comment by ba32107** [comment]
I am unable to reproduce this on Linux. @john3voltas, could you provide more details? If you put in the correct password, you should be taken to the main window of the application right after you press Enter once. I assume this happens if you type in an invalid password? Is the focus still in the textfield when you press the Enter twice?

Can someone try and reproduce this on Windows?

**Comment by john3voltas** [comment]
@ba32107 
Hey there.
Sure.
This is a Windows 7 Pro (Spanish ISO with English language pack).
KPXC 2.5.1 was installed via chocolatey package manager but I have already uninstalled and tried installing KPXC through the normal installer on the website and yet I can still reproduce the issue.

This is easily reproducible, at least on my system.
All you need to do is:
- open KPXC's main window
- load a *.kdbx file
- type the main password for the kdbx file
- instead of clicking OK button to open the kdbx file, simply press 'enter key' twice, very fast.

My basic understanding is that the first time you press 'enter' KPXC starts to load the kdbx file. Now, **while it is still trying to load the kdbx** file the second 'enter' comes in at that moment and I guess that's why I get the crash.

Please note that this is an old intel i3 laptop running Windows from a regular 2,5" 5400rpm HDD drive, far far away from the speeds the regular SSD's can reach today, and that's why I can press 'enter' the second time before the kdbx file is loaded and show on screen.
I don't think it's a RAM issue because I have 3GB free RAM from a total of 8GB, and I still have the regular swapfile.
Please let me know if there's anything I can do to help debug the issue but bear in mind that I don't have any coding skills. At all.
Thanks in advance.
Cheers

**Comment by ba32107** [comment]
Thanks @john3voltas. On my machine the DB loads in an instant. I was able to reproduce this by adding an artifical delay on DB open.
Fix is open: https://github.com/keepassxreboot/keepassxc/pull/3885

**Comment by john3voltas** [comment]
Great!
Thanks a bunch, @ba32107 .
Cheers
