### ISSUE TITLE
Don't show KeePassXC window after Firefox is  closed

### ISSUE THREAD

**Issue by Karpfly2822** [keepassxreboot/keepassxc#3873]
## Expected Behavior
KeePassXC should stay minimized in tray

## Current Behavior
When closing Firefox, KeePassXC window is showing up on desktop instead of stay in tray

## Steps to Reproduce
1. KeePassXC in tray(blocked)
2. Open Firefox with KeePassXC-browser addon enabled
3. Close Firefox, KeePassXC should popup to desktop

Firefox version: 70.0.1(x64)
OS: Linux Mint 19.2 Tina x86_64 
Kernel: 5.0.0-36-generic 
All system updates installed

## Debug Info
KeePassXC - Version 2.5.1
Revision: 0fd8836
Distribution: Flatpak

Qt 5.13.2
Debugging mode is disabled.

Operating system: Linux 5.0.0-36-generic
CPU architecture: x86_64
Kernel: linux 5.0.0-36-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.5

##Debug info form addon:
KeePassXC - 2.5.1
KeePassXC-Browser - 1.5.3
Operating system: Linux x86_64
Browser: Mozilla Firefox 70.0

**Comment by droidmonkey** [comment]
Never seen this behavior before.

**Comment by Karpfly2822** [comment]
I made video [https://youtu.be/_1aHeUIgBiU](url)
KeePass  is starting automatically with system boot, this is command copied from auto start menu:
/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=keepassxc --file-forwarding org.keepassxc.KeePassXC @@ %f @@

**Comment by droidmonkey** [comment]
Hmmm that is strange also there is a black artifact on the window.

**Comment by Karpfly2822** [comment]
oh, don't worry about black thing, i only covered my personal data in video editor :) 
btw, before update it didn't happen, and on same pc with same browser configuration but running on windows 10 it works ok

**Comment by droidmonkey** [comment]
If it works on Windows 10 then I cannot fix this. Windows 7 is End of Life in January 2020 anyway. Time to move on

**Comment by Karpfly2822** [comment]
I have this bug in Linux Mint not in Windows

**Comment by droidmonkey** [comment]
Sorry got my wires crossed with another issue reported against win 7

**Comment by droidmonkey** [comment]
Closing this since I cannot replicate.

**Comment by Owlwasrowk** [comment]
I have the same problem and the error appears in both cases (with and without the tray setting). Can you reopen the issue?

**Comment by Owlwasrowk** [comment]
Additonaly: If i close Firefox by closing all tabs (last tab with Middle-Mouse-Click, not with shortcut or click on X), the KeePassXC windows will not be shown.

**Comment by Darkcacok** [comment]
I have the same issue in Chrome and Firefox.
I use flatpak version.
