### ISSUE TITLE
keepassxc generate different TOTP code from Google Authenticator in 2.5.1 for secrete key require padding

### ISSUE THREAD

**Issue by zydxt** [keepassxreboot/keepassxc#3874]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )
After updating to 2.5.1, keepassxc generate wrong TOTP code which is different from the code generated by Google Authenticator.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
When I use keepassxc to set a RFC6283 TOTP password, and right click the record -> display TOTP QR code. Then I use google authenticator to scan the QR code keepassxc give me. The TOTP code generated by google auth and keepassxc should be same, and both them should be able to sign in my account (epic store for this case)

## Current Behavior
[NOTE]: # ( Tell us what actually happens )
When I use google auth to scan the QR code, I found that Google auth generate a different code.  I can't use the code keepassxc generate to sign in my account (which is wrong)  and I can use the code google auth generate to sign in.

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )
In the realease log, I found some fix for TOTP secrete key need padding. Maybe this change something aboute handle screte key.
https://github.com/keepassxreboot/keepassxc/pull/3764

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1. Add a recode and set RFC6283 TOTP password. Use this key: IJHUOVSYLJHDOVCGKJKEKNZVLE3EGSBVJE2UGRBVIRHEUQKCJVKA (This is my legacy key, no use now)
2.Input this key in Google Authenticator
3. Compare the code 

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )
It generate wrong code and I can't sign in my account now. 

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.5.1

Operating system: windows 10
CPU architecture: x86_64

Enabled extensions:
- EXTENSIONS

**Comment by droidmonkey** [comment]
Sync your time in your computer

**Comment by zydxt** [comment]
Sorry , My bad. I tested it on Linux, and It works. I found that my windows time is synced, but when I boot to Linux ( dual-boot ) It will mess up the windows time zone configuration, which make the totp code wrong
