### ISSUE TITLE
Yubikey static password keepassxc stores shift key modifer 

### ISSUE THREAD

**Issue by Grotax** [keepassxreboot/keepassxc#3875]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Press yubikey button and the static password is entered

## Current Behavior
[NOTE]: # ( Tell us what actually happens )
Press yubikey button:
 A) you have pressed the shift key before: first "key" from yubikey gets shift applied
 B) you did not press the shift key before: first "key" form yubikey normal

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )
When releasing the shift key the shift-state needs to be reset

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1. Focus any editable field in keepassxc 
2. press shift, release it, press yubikey button (static password)
3. first key upper case (if it was lower case before)

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.5.1
Revision: 0fd8836
Distribution: AppImage

Operating system: Linux Mint 19.2
CPU architecture: x64
Kernel: 4.15.0-70-generic

Enabled extensions:
- Browser

**Comment by Grotax** [comment]
Checked version 2.4.3 no issue there

**Comment by phoerious** [comment]
Why are you not using your YubiKey as an HMAC token?

**Comment by droidmonkey** [comment]
This sounds like a Yubikey bug

**Comment by Grotax** [comment]
Maybe but it was not an issue in 2.4.3.
Anyway I switched to HMAC.

@phoerious When I started using Yubikey HMAC what nos possible for me, legacy stuff ;)
