### ISSUE TITLE
Question: No -Auto-type UI when only one account?

### ISSUE THREAD

**Issue by 0pLuS0** [keepassxreboot/keepassxc#3878]
Hello,

Sorry if this has already been asked...

Is there a request, or does keepassxc have the ability, when there is only one account being logged in, it just automatically types it in, rather then getting the Auto-type login UI to appear, that we need to click on just one account?

I assumed keepassxc would work in this manner that keepassx did with only one account.

THANKS

**Comment by droidmonkey** [comment]
Go to the Auto-Type settings and disable "Always ask before Auto-Type"

**Comment by 0pLuS0** [comment]
@droidmonkey thanks, sorry, I didn't realize that is what that option meant... 

Keep up the great work!
