### ISSUE TITLE
Automatic group reorder

### ISSUE THREAD

**Issue by slevesque** [keepassxreboot/keepassxc#388]
Can't reorder groups.

## Expected Behavior

Automatically reorder main level of groups on the left sidebar.

## Current Behavior

No possibility to reorder at all.

## Your Environment

Révision: 76dcfb5ed0c874f6a835ef0347ddf6098b149e9b

Use :
- Qt 5.6.1
- libgcrypt 1.7.2-beta

Extensions :
- KeePassHTTP
- Autotype

* KeePassXC version/commit used: (can be found under Help -> About)
* Qt version (e.g. Qt 5.3): 
* Compiler (e.g. Clang++3.6.0): 
* Operating System and version:

**Comment by droidmonkey** [comment]
Reorder is accomplished using drag/drop. Does this not work for you?

**Comment by slevesque** [comment]
I didn't notice this. It works. But Its a little time consumming to do it on 200 groups. If we have an option do reorder automatically when we want to, it will be fine.

**Comment by PF93mc8y7erq92qTmTjJBysALa** [comment]
Another similar issue is for the list to be sorted in lexicographical order, #69.
