### ISSUE TITLE
date of last modified entries in db 

### ISSUE THREAD

**Issue by hafx** [keepassxreboot/keepassxc#3881]
[TIP]:  # ( Provide a general summary of the feature in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Summary
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
Until now I used keepass (not "xc"). I synchronize my db on a server with multiple device and sometimes I encounter syncronization problems. To check if the database I'm using is up to date, I look at the last modified time (named "last modified entries" in keepass).
I didn't find a way to see what are the last modified entries in the db.

## Desired Behavior
[NOTE]: # ( Tell us how the new feature should work, be specific )
I would like to see the date/hour of the last modification in my db (like https://keepass.info/)

Sorry if this function already exists, but I didn't find it.

**Comment by droidmonkey** [comment]
There is a column for last modified on each entry. If you want to see all the entries at once just search for "*".

**Comment by hafx** [comment]
top, it responds to my request. Thanks
