### ISSUE TITLE
Copying password from the auto-type popup does not follow references

### ISSUE THREAD

**Issue by GenericPseudonym** [keepassxreboot/keepassxc#3882]
Right clicking an entry in the auto-type window gives the option to copy the username or password for that entry.
If the entry's password field is a reference to another entry, only the raw string {REF:P@I: [hex string] } will be copied. 

## Expected Behavior
When I right click an entry in the auto-type window and select copy password, my clipboard should contain the password corresponding to that entry. 

## Current Behavior
If the entry's password field is a reference to another entry, my clipboard will instead contain the string {REF: etc}

## Steps to Reproduce
1. Create an entry in KeepassXC with any username/password
2. Right click that entry in the database, select "clone entry", and check the "replace username and password with references" box.
3. Bring up the auto-type window in an application matching the entry's title.
4. Right click on the list item for the cloned entry and select "copy username" or "copy password".
5. Paste your clipboard into a text editor and observe. 

## Debug Info
KeePassXC - Version 2.5.1
Revision: 0fd8836

Qt 5.13.1
Debugging mode is disabled.

Operating system: Windows 7 SP 1 (6.1)
CPU architecture: x86_64
Kernel: winnt 6.1.7601

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.5

**Comment by Semnodime** [comment]
This holds true for a reference to a username field as well:
References won't get resolved in either case.

**Comment by droidmonkey** [comment]
Great point, this also impacts my complete overhaul of this select dialog, will fix in my PR.
