### ISSUE TITLE
Could not open keepassxc database if it's on veracrypt volume (Ubuntu 19.10)

### ISSUE THREAD

**Issue by PeterWq** [keepassxreboot/keepassxc#3883]
Unable to open database error if the database is on veracrypt volume (decrypted of course) on Ubuntu 19.10.
If I copy the database from veracrypt volume to somewhere else (any folder) I could successfully open the database without any issue (so the database is OK). Tried to create a new veracrypt volume with FAT format type and also tried with EXT4 but same error both time. 
Original veracrypt volume is exFAT and of coursehas same issue (note: it's working fine on my mac.)  

## Expected Behavior
Will expect to work same way on Linux as on Mac, to allow to open the keepassxc database from veracrypt volume if it's decrypted

## Current Behavior
unable to open keepassxc database, ERROR: "unable to open file /media/veracrypt1/....kdbx"

## Possible Solution
copy the keepassxc file to other place (not on veracrypt volume) and then it's possible to open it successfully. 

## Steps to Reproduce
prerequisites: create a veracrypt volume (encrypted file container) and move keepassxc database to the veracrypt created container.
1. mount the veracrypt file container;
2. go to the container in Files and click to open it with KeepassXC app;
3. input the password and in my case + the yubikey challenge-response;
4. The error display  "unable to open file /media/veracrypt1/....kdbx"

## Context
I was setup my new laptop using Ubuntu 19.10 and was trying to setup same setup as on my mac laptop. KeepassXC database is residing on veracrypt encrypted container and when is needed, mount the veracrypt volume and open the keepass database (this setup is working fine for years on mac)

## Debug Info
KeePassXC - Version 2.5.1
Revision: 0fd8836
Distribution: Snap

Qt 5.9.5
Debugging mode is disabled.

Operating system: Ubuntu Core 18
CPU architecture: x86_64
Kernel: linux 5.0.0-36-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.1

**Comment by droidmonkey** [comment]
"Unable to open" is a file read error and not something KeePassXC is failing to do. Can you open any other files from that container? The other issue may be because you are using the snap distribution. Because it is sandboxed sometimes it gets upset when you try to open exotic file systems.

**Comment by PeterWq** [comment]
Yes, I was using a snap distribution. And yes I could open other files from veracrypt volume. 
Tried with appimage and I was able to open keepassxc database from veracrypt volume. 
Please close this ticket as it looks like it was a snap specific issue.

**Comment by droidmonkey** [comment]
Yup likely sandbox issue
