### ISSUE TITLE
[2.5.1] Crash when clicking different tab while database is decrypting

### ISSUE THREAD

**Issue by MartinX3** [keepassxreboot/keepassxc#3887]
## Expected Behavior
It unlocks my database and opens the tab of the locked database.

## Current Behavior
The application crash with a segfault.

## Possible Solution
---

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1. Open 2 password files
2. Enter the password in the second tab
3. At the same time you execute the unlocking, click on the first tab

## Context
I have 2 password files open at the same time.

## Debug Info
KeePassXC - Version 2.5.1
Revision: 0fd8836

Qt 5.9.5
Diagnosemodus ist deaktiviert.

Betriebssystem: Linux Mint 19.2
CPU-Architektur: x86_64
Kernel: linux 5.0.0-36-generic

Aktivierte Erweiterungen:
- Auto-Type
- Browser-Integration
- SSH-Agent
- KeeShare (bestätigtes und unbestätigtes Teilen)
- YubiKey
- Secret-Service-Integration

Kryptographische Bibliotheken:
 libgcrypt 1.8.1

**Comment by ba32107** [comment]
We could solve this the same way as https://github.com/keepassxreboot/keepassxc/pull/3885, but I don't think that's the right approach.

I've narrowed down the problem to this method: https://github.com/keepassxreboot/keepassxc/pull/3885
The crash happens when the future completes (if the DB tab is switched). Not really sure yet why.

**Comment by SteveBresson** [comment]
I'm running 2.5.1 on 
Linux rogue 5.0.0-36-generic #39~18.04.1-Ubuntu SMP Tue Nov 12 11:09:50 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
And am getting a 'Segmentation fault' after performing a couple of operations if
that helps your diagnosis at all.
This morning I created a new entry and saved it. Brought it up to edit the entry. Saved it.
On the next attempt it crashed when I did the OK.

**Comment by XanatosX** [comment]
The same problem happens on Windows 10. If you unlock the database and select another window such as the browser while the unlocking is still in progress KeepassXC is crashing

KeePassXC - Version 2.5.1
Revision: 0fd8836

Qt 5.13.1
Diagnosemodus ist deaktiviert.

Betriebssystem: Windows 10 (10.0)
CPU-Architektur: x86_64
Kernel: winnt 10.0.18362

Aktivierte Erweiterungen:
- Auto-Type
- Browser-Integration
- SSH-Agent
- KeeShare (bestätigtes und unbestätigtes Teilen)
- YubiKey

Kryptographische Bibliotheken:
 libgcrypt 1.8.5

**Comment by droidmonkey** [comment]
Can no longer replicate this on the 2.5.2 branch.
