### ISSUE TITLE
KeeShare live synchronize issues

### ISSUE THREAD

**Issue by veehexx** [keepassxreboot/keepassxc#3888]
Client1: Fedora using repo keepassxc
Client2: Win10 using keepassxc msi installer.
Sync method: Owncloud (using owncloud desktop sync application)

## Expected Behavior
when configuring KeeShare, 'synchronize' should allow a multi-way sync between all clients with access to the shared file with immediate 'live' updates. 

## Current Behavior
KeeShare enabled groups only update either at initial configuration of keeshare, or unlocking of kdbx.

## Possible Solution
sugestion: KeeShare does not appear to honour the 'automatically reload the database when modified externally' setting. KeeShare should honour this setting to allow immediate visibility across all synced devices.

## Steps to Reproduce
1. Client1: existing database, in settings>keeshare enable import&export, & configure 'Own Certificate' section.
2. client1:  create group & enable keeshare as Synchronize, path to Owncloud location, configure password. Create a password entry to test.
3. client1: ensure DB is saved & check file.kdbx.share has been created & synced.
4. client2: create new DB, setting>keeshare enable import&export & configure 'Own Certificate' section (different name & cert details than client1)
5. client2: create group & enable keeshare as Synchronize, path to Owncloud location, configure password. Note that when selecting existing file.kdbx.share, it prompts to overwrite existing file.
6. client2: see that the entry created in step2 is visable.
7. client1: create second entry & save
8. client2: wait for owncloud to sync and see that new entry is not visible.
9. client2: close KPXC/lock DB and re-open. see that the password list is correct between the two clients. 

side notes:
1. 'automatically reload the database when modified externally' is ticked on both clients.
2. KeeShare Imported Certificates shows the other client on both client1&2 as trusted.

## Context
currently testing new feature with the view to use at work for 4man team.

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
linux:
KeePassXC - Version 2.5.1
Revision: 0fd8836

Qt 5.12.5
Debugging mode is disabled.

Operating system: Fedora 31 (KDE Plasma)
CPU architecture: x86_64
Kernel: linux 5.3.11-300.fc31.x86_64

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.5

Windows10
KeePassXC - Version 2.5.1
Revision: 0fd8836

Qt 5.13.1
Debugging mode is disabled.

Operating system: Windows 10 (10.0)
CPU architecture: x86_64
Kernel: winnt 10.0.18362

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.5

**Comment by droidmonkey** [comment]
Duplicate issue
