### ISSUE TITLE
[2.3.1] Database is read only

### ISSUE THREAD

**Issue by Jan-vi** [keepassxreboot/keepassxc#3894]
have Ubuntu 18.04 LTS with keepassxc 2.3.1 from the Ubuntu rep installed. Everything works fine until the database is on a smb network drive (Buffalo NAS). The drive permissions are definitely Read/Write although they are indicated as "could not be determined". Read/write of any other files works fine and even the jv.kbdx works from same drive using Dominik Reichls keepass 2.4.1 from a W10 PC. If I open database by keepassxc it is locked to read only. Save Database is always grey. Anyway "Save database as" works fine. File will be replaced and is read/write until next start of keepassXC
![Screenshot from 2019-11-17 23-27-10](https://user-images.githubusercontent.com/55537299/69015178-d1069980-0991-11ea-8f2e-7423dd5af3a9.png)

**Comment by droidmonkey** [comment]
Holy wow you are about 10 versions behind the latest

**Comment by droidmonkey** [comment]
Either way this is a bug in gvfs fuse not KeePassXC
