### ISSUE TITLE
Selection of the path for Keeshare causes application hang

### ISSUE THREAD

**Issue by Ralffe** [keepassxreboot/keepassxc#3895]
## Expected Behavior
Selection of the path for Keeshare

## Current Behavior
Selecting the path for Keeshare on MacOS 10.15.1 Catalina not possible

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.5.1
Revision: 0fd8836

Qt 5.13.1
Diagnosemodus ist deaktiviert.

Betriebssystem: macOS 10.15
CPU-Architektur: x86_64
Kernel: darwin 19.0.0

Aktivierte Erweiterungen:
- Auto-Type
- Browser-Integration
- SSH-Agent
- KeeShare (bestätigtes und unbestätigtes Teilen)
- YubiKey
- TouchID

Kryptographische Bibliotheken:
 libgcrypt 1.8.5

**Comment by droidmonkey** [comment]
Wow this is true. Clicking the "browse for file" button causes CPU to spike to 100% and fail to load. The CPU spike occurs in the macOS file open dialog process which I believe is just killed by the kernel.

**Comment by droidmonkey** [comment]
This is a Qt bug in Qt 5.13

**Comment by droidmonkey** [comment]
This is still a bug in Qt 5.14

**Comment by droidmonkey** [comment]
This is actually a macOS bug!

https://github.com/lionheart/openradar-mirror/issues/16907

The fix is to remove the leading `.` in the filetypes variable.
