### ISSUE TITLE
Extend KeePassXC to use vault as a storage backend

### ISSUE THREAD

**Issue by flassagne** [keepassxreboot/keepassxc#3896]
## Summary

Use Vault as a storage backend

### Creation user's workflow

1. Select a storage type
2. Authent on Vault
3. Retreive secrets
4. Manage secrets
    - Add
    - Remove
    - Edit
    - Use

### Open user's workflow

1. Authent on Vault
2. Retreive secrets
3. Manage secrets
    - Add
    - Remove
    - Edit
    - Use

## Possible Solution

I see two possible implementation.

#### PROS

Easy implementation, we just have to add a authent form with url and credential.

#### CONS

Not user-friendly if we want use all vault features.

#### PRO

Use all vault's features.

#### CONS

Complex implementation.

## Context

Currently we use KeePassXC to store user's secrets and it's not a user-friendly at scale company.

* Everybody have to copy the wallet on his workstation and may lead to leak information
* Secret handling and revocation it's a burden.
* Secret audit is impossible.
* General automation is impossible for now.
* There is no separation possible in the KeePassXC, it's a all or nothing strategy.

We would like propose a PR in order to use Vault as secret's storage which permit to solve these issues.

**Comment by flassagne** [comment]
## Create a new storage type

I choose to start this solution but it's lead me to do some refactoring and I prefer ask you if it's ok for you.

### Design choice

![KeePassXC_Vault](https://user-images.githubusercontent.com/29461133/69045529-4e182a00-09f7-11ea-97de-ea01d3e5a7ab.png)

#### Handle secrets in generic wallet concept

If we want add new storage type, we need to add a generic concept to handling secrets. For me wallet can be represents effectively a set of secret independently of storage type.

So we create a controller `Wallet` which can use a storage object to save data.

#### Handle storage backend

In order to use several storage type, we create a generic interface `Storage` and implement with specific backend `Database` and `Vault` .

### PR process

Due to the lot of modification, I propose to send two PR :

1. Do the refactor and add `Wallet` concept without vault backend
2. Propose vault backend

**Comment by droidmonkey** [comment]
This looks more like a fork to me.

**Comment by hifi** [comment]
If you want some sort of integration then an importer would probably fit KeePassXC better. The target audience of Vault users wanting to use a native frontend is likely very narrow to begin with.

**Comment by droidmonkey** [comment]
I think what you are really looking for is this: https://github.com/adobe/cryptr

More options are available here: https://www.vaultproject.io/api/relatedtools.html

I'd be willing to entertain a Vault Import/Export plugin. But full sync and operating under Vault's rules of business is not something I want to incorporate into KeePassXC. We are not an enterprise focused tool with strict control over every credential.

**Comment by flassagne** [comment]
First of all, thank you for your answers.

@hifi we don't just want sync between local database and vault but use vault as backend storage.

I would like clarify we don't just want a vault's front-end but use KeePassXC features like auto-complete, password generator or totp.

Don't you think using several kind of backend or letting it in a first step can be really nice feature for KeePassXC ? This feature can be usefull not only for companies but also for common users.

**Comment by droidmonkey** [comment]
If you can set it up similar to KeeShare I think we might have something here

**Comment by hifi** [comment]
For me personally a KeeShare style integration with LastPass (Enterprise) would be really helpful, at least in single direction (from LastPass). Having auto-type etc. would indeed be handy.

So if this bears any fruit having it extensible to LastPass would be great.

**Comment by flassagne** [comment]
Basically you would like have a backend aggregator with KeeShare style integration in order to retrieve all secrets in KeePassXC store in local database. 

But one of our use-case is to not store in local database. It's make sense in team secret management. This is why, I suggest the wallet abstraction.
Furthermore I think it's easier for synchronization to fetch data when we need it and avoid offline storage with storage provider.

Maybe you can have some ideas to content everybody ?

**Comment by droidmonkey** [comment]
I do not support renaming our structure. We aren't a wallet, we are a database. The name is irrelevant anyway. KeePassXC is an offline encrypted store of information. Full stop. When you are proposing integrations to that model you must live within those boundaries or else you are looking for an entirely different program with a different data model and workflow.

**Comment by flassagne** [comment]
I understand so a fork it will be
