### ISSUE TITLE
Update INSTALL.md to include xvfb testing instructions

### ISSUE THREAD

**Issue by Achaean** [keepassxreboot/keepassxc#3897]
On a Debian oldstable based distribution x64, I tried to build the last version (2.5.1).

The options for cmake were to keep from plugins, only the update check:
`cmake -DCMAKE_VERBOSE_MAKEFILE=OFF -DCMAKE_BUILD_TYPE=Release -DWITH_APP_BUNDLE=OFF -DWITH_XC_AUTOTYPE=OFF -DWITH_XC_NETWORKING=ON -DWITH_XC_UPDATECHECK=ON -DWITH_GUI_TESTS=ON ..`

Cmake and make completed successfully.
However, tests failed:
```
94% tests passed, 2 tests failed out of 34

Total Test time (real) =  63.37 sec

The following tests FAILED:
         32 - testcli (Failed)
         33 - testgui (Failed)
Errors while running CTest
Makefile:116: recipe for target 'test' failed
make: *** [test] Error 8

```

**Comment by phoerious** [comment]
These two tests need an X server (e.g. xvfb).

**Comment by Achaean** [comment]
Xvfb is already installed.

**Comment by droidmonkey** [comment]
Yes something on your end, our ci has no such problem.

**Comment by phoerious** [comment]
You need to start the tests in xvfb. Only having it installed is not enough.

**Comment by Achaean** [comment]
> You need to start the tests in xvfb. Only having it installed is not enough.

Then the INSTALL.md sould be corrected.
It says:
```
Testing
=======

You can perform test on the executable
```
make test
```
```

**Comment by droidmonkey** [comment]
Certainly we are assuming you are running tests in a GUI environment. There used to be a wiki entry on how to run the xvfb tests. I agree we can add this into INSTALL.md:

```
## Run GUI and CLI tests
If you are not currently running on an X Server or Wayland, run the GUI and CLI tests as follows:

xvfb-run -e errors -a --server-args="-screen 0 1024x768x24" make test ARGS+="-R test\(cli\|gui\) --output-on-failure"
```
