### ISSUE TITLE
Monospace Notes and passwords are too small on macOS

### ISSUE THREAD

**Issue by vikdean** [keepassxreboot/keepassxc#3904]
## Current Behavior
[NOTE]: # ( Tell us what actually happens )
The monospaced font size when viewing or editing entry Notes are really small and barely readable.

![image](https://user-images.githubusercontent.com/16238514/69331639-68e7da00-0c55-11ea-93fb-01f7923468b7.png)

I believe its like since the 2.5.0 update or since the Dark mode, not sure.

## Expected Behavior
It would be great the get back the old font size or make it adjustable.

**Comment by droidmonkey** [comment]
This is a Qt bug, but still a big (small) issue on macOS

**Comment by droidmonkey** [comment]
This will be fixed with #621
