### ISSUE TITLE
Clear-text password displayed in url of entry preview pane

### ISSUE THREAD

**Issue by MaxMatti** [keepassxreboot/keepassxc#3905]
## Expected Behavior
Password in censored in displayed URL

## Current Behavior
Password is partially shown in displayed URL
![image](https://user-images.githubusercontent.com/1584478/69332493-1ad3d600-0c57-11ea-8539-f819f85fede1.png)

## Steps to Reproduce
* Password should include < and >
* Password should be included within "" in the URL

## Debug Info
KeePassXC - Version 2.5.0
Revision: 1ab8a9f

Qt 5.13.2
Diagnosemodus ist deaktiviert.

Betriebssystem: Arch Linux
CPU-Architektur: x86_64
Kernel: linux 5.3.11-arch1-1

Aktivierte Erweiterungen:
- Auto-Type
- Browser-Integration
- SSH-Agent
- KeeShare (bestätigtes und unbestätigtes Teilen)
- YubiKey

Kryptographische Bibliotheken:
 libgcrypt 1.8.5

**Edit:** Updated screenshot to include actual password.

**Comment by ba32107** [comment]
Raised fix: https://github.com/keepassxreboot/keepassxc/pull/3910

**Comment by droidmonkey** [comment]
So interesting enough, this is a bug in Qt. We set the rawText to use the password masking. However, it seems that when you set the URL to something that contains HTML _AND_ uses double quotes it causes an error in the rawText display!

The following URL does NOT exhibit this behavior: `cmd://ssh {password}@127.0.0.1 -p {password}`

![image](https://user-images.githubusercontent.com/2809491/69479660-ba1ad980-0dcd-11ea-8806-06c1650cf480.png)

Adding a double quote anywhere in the URL string causes the issue to appear: `cmd://ssh {password}@127.0.0.1 " -p {password}`

![image](https://user-images.githubusercontent.com/2809491/69479681-0239fc00-0dce-11ea-8baf-8307b26ec996.png)

**Comment by ba32107** [comment]
Yeah agreed, and this happens because the URL string will be put into the the `<a href="">`, and you can essentially do "HTML injection". Not sure why `ElidedLabel` does not encode the URL string by default.

**Comment by droidmonkey** [comment]
I am modifying your PR to do just that

**Comment by MaxMatti** [comment]
I don't know about the exact internals but there are still two things that seem wrong to me:
1. Why is the password even used in this context? It's not like I want to have my password show up in the URL. It's supposed to be censored anyway. So why even load the password into memory instead of just loading a bunch of `*`s directly?
2. Why are you using a type of field that supports HTML? Is there no other way to make the URL a clickable "Link"? Does this also mean that the password is loaded into RAM unencrypted for the whole time my KeePassXC-Window is open?

**Comment by droidmonkey** [comment]
@MaxMatti ALL of your passwords are loaded into RAM unencrypted when you unlock your database.
