### ISSUE TITLE
Database export timeout is too short

### ISSUE THREAD

**Issue by blittlewood** [keepassxreboot/keepassxc#3906]
**Problem:**
When attempting to export a database to an external USB device, it took me several tries before I was able to actually save an exported file before the dialog apparently timed out and disappeared.
On my first couple of tries, upon the dialog disappearing while I was navigating, I was worried that I had fat-fingered something and sent a copy of my (unencrypted) database to some unknown location (who knows, maybe I did).
Now that I know to rush (my target directory is 4 or 5 levels deep on another device), I am still concerned that I might make a mistake in haste and send the file somewhere unsafe.
This "feature" (if that is what it is), is going to annoy/confuse/worry users, and could result in a mistake from haste that sends an unencrypted database to an unsafe location.

**To reproduce:**
Toolbar | Database | Export | Export to CSV file
then, in the filename specification dialog, quickly rush to select the external USB device, click down to select the appropriate directory, key in the desired filename and select Save to save the export to the specified file.  If you are not fast enough, the dialog disappears before you are able to complete the save, with no indication of why it disappeared.

**Suggested solutions:**
Quick fix: increase the timeout to at least twice what it currently is, or eliminate the timeout.
Ultimate fix: provide for user-configuration of the timeout, similar to what is available for the clipboard timeout.

**About:**
macOS Mojave 10.14.6 (18G103)

KeePassXC - Version 2.5.1
Revision: 0fd8836

Qt 5.13.1
Debugging mode is disabled.

Operating system: macOS Mojave (10.14)
CPU architecture: x86_64
Kernel: darwin 18.7.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
 libgcrypt 1.8.5

**Comment by droidmonkey** [comment]
We don't have a timer of this dialog.

**Comment by blittlewood** [comment]
Ok, thanks, nice to know you're on it!
Bill

**Comment by nuclearfall** [comment]
I can confirm the bug exists under different circumstance. For the Menubar -> FIle -> Save As… Dialog as well, with or without USB on the same versions of macos, qt, and keepassxc.  Scribus uses the same version of qt but doesn't use native file dialog. I wonder if qt 15.2 would have the same issue. 

Running the keepassxc from the command line I get this when the application opens:

```
./KeePassXC 
objc[42353]: Class AppKitImpl is implemented in both /Applications/KeePassXC.app/Contents/MacOS/./KeePassXC (0x1023c6bf0) and /Applications/KeePassXC.app/Contents/PlugIns/libkeepassx-autotype-cocoa.so (0x109822b90). One of the two will be used. Which one is undefined.
```

And this when the bug occurs:

`objc[42353]: Class FIFinderSyncExtensionHost is implemented in both /System/Library/PrivateFrameworks/FinderKit.framework/Versions/A/FinderKit (0x7fff9a06b3d8) and /System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride (0x109902f50). One of the two will be used. Which one is undefined`

Not sure if this helps at all.

**Comment by droidmonkey** [comment]
Qt 5.13 has definite bugs with macOS file dialog.
