### ISSUE TITLE
Password Variable for login. I have 3 medical same password, 3 veterans and Links with more  one logon screens. 

### ISSUE THREAD

**Issue by Yellow-jack** [keepassxreboot/keepassxc#3908]
[TIP]:  # ( Provide a general summary of the feature in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Summary
[NOTE]: # ( Provide a brief overview of what the new feature is all about )

## Desired Behavior
[NOTE]: # ( Tell us how the new feature should work, be specific )

## Possible Solution
[NOTE]: # ( Not required, but suggest ideas on how to implement the addition or change )

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )

**Comment by droidmonkey** [comment]
Uh what?
