### ISSUE TITLE
Use the full domain name when retrieving site icons.

### ISSUE THREAD

**Issue by iokiwi** [keepassxreboot/keepassxc#3909]
[TIP]:  # ( Provide a general summary of the feature in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Summary
[NOTE]: # ( Provide a brief overview of what the new feature is all about )

When retrieving icons for sites only the few rightmost parts of the domain name are used and the remaining subdomain parts are ignored. If the resources at the subdomains use a different icon that the resources at the first or second parts of the domain name then it just gets the same icon as the higher level domain,

**For example:**

The following two (related) sites share the last part of the domain name but use totally different icons.

* https://catalyst.net.nz
* https://dashboard.cloud.catalyst.net.nz

However when their icons are retrieved, both sites get assigned the icon for https://catalyst.net.nz

## Desired Behavior
[NOTE]: # ( Tell us how the new feature should work, be specific )

The icons retrieved and used for each site should be the unique icons found at the full domain name.

* https://catalyst.net.nz
* https://dashboard.cloud.catalyst.net.nz

A corolory of this would also be that the correct application icon will be used for 3rd party applications hosted on subdomains of the same domain.

https://&lt;app&gt;.catalyst.net.nz/  can use the correct icon for &lt;app&gt; whether that be jenkins, redmine, jira rather than just using the icon for https://catalyst.net.nz

## Possible Solution
[NOTE]: # ( Not required, but suggest ideas on how to implement the addition or change )

Try retrieve the icon at the full domain name first - if that fails, then fall back to existing means.

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )

As an employee of catalyst and catalyst cloud I have lots of logins for various apps at both cloud.catalyst.net.nz and catalyst.net.nz and want them to use their proper icons for better visual cue's

**Comment by droidmonkey** [comment]
This might be due to duck duck go icon service. we submit the full domain then if that fails, chop off a subdomain, submit, etc

**Comment by iokiwi** [comment]
Ah I took brief look at the code and saw the DDG image service there but missed the fact that that that was a the primary / only source for the Icons.

Is there a reason why Icons are being requested from DDG and not by trying to download the favicon served by the application itself? Would I be wasting my time to try and implement this?

**Comment by droidmonkey** [comment]
Yes you would be. As a last resort we try to retrieve the favicon.ico from the base url. We prefer duck duck go because 99% of the time it has already done all the hard parsing work. Foe your case, if you really want different icons, just download them yourself and add them as files.

**Comment by iokiwi** [comment]
Thanks for the confirmation @droidmonkey
