### ISSUE TITLE
 "Toggle window" hides window when minimized instead of showing

### ISSUE THREAD

**Issue by archfrog** [keepassxreboot/keepassxc#3911]
## Summary
I'd like to request that the Linux tray icon menu item "Toggle window" is changed to "Show window".  Every time I click it, I have to do it one more time to get the window to display.

## Desired Behavior
The substitute menu item, `Show window`, should show the window unconditionally instead of toggling between showing and hiding the window.  Hiding the window can easily be done with the Minimize button so there's not really any point in this feature.

## Possible Solution
Simply change the functionality of `Toggle window` into `Show window`.

## Context
It matters to me because I have to toggle the window twice, every time, to get it to display :-)

**Comment by droidmonkey** [comment]
It was literally just changed to toggle window because that's what it does. Perhaps not in your desktop env. Care to share your setup?

**Comment by archfrog** [comment]
I use Manjaro Linux x64 (Gnome Edition) with GNOME v3.34.1.

It may be the way I use it, but to me it always toggles to hidden first and then toggles to visible.

I suppose it may be because I use the Minimize button when I want to minimize the window.  And then I try to make it show again using the "Toggle window" button.

But my point is, why would anybody ever use the "Toggle window" button to hide the window?  There's already plenty of ways of doing that :-)

As far as I can tell, it would be much more usable to have it always simply show the window.

**Comment by archfrog** [comment]
I thought that perhaps I needed to change my use of KeePassXC, but if I double-click the tray icon, to make it visible, it does exactly the same - I have to double-click it twice to make it show.

**Comment by droidmonkey** [comment]
Ok then we can look into that

**Comment by ba32107** [comment]
@archfrog, I am on Ubuntu and unable to reproduce this no matter what I try. Can you let us know the following:
1. From your settings, what are the values of 'Minimize instead of app exit' and 'Hide window to system tray when minimized'?
2. Your debug info (Help / About / Debug Info)
3. Exact reproduction steps (let us know where you click exactly, in what order, and what state the application is in)

**Comment by archfrog** [comment]
**NOTE: I just discovered that Arch Linux only provides v2.5.0, which I think is the cause of the issue.**

I will build v2.5.1 and let you know if that fixes the problem.  The Arch Linux package is flagged as outdated, but nobody seems to have done anything about it.

@ba32107, here is the requested information:

1. `Minimize instead of app exit` is checked/enabled.
2. `Hide window to system tray when minimized` is checked/enabled.
3. The debug info follows below:
```
KeePassXC - Version 2.5.0
Revision: 1ab8a9f

Qt 5.13.2
Debugging mode is disabled.

Operating system: Manjaro Linux
CPU architecture: x86_64
Kernel: linux 5.3.11-1-MANJARO

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.5
```

Reproduction steps:
1. Launch KeePassXC and enter credentials.
2. The app is now maximized.
3. I then click the minimize button.
4. If I now right-click the tray icon and select "Toggle window", nothing happens.
5. If I do the above one more time, the window appears.
6. I then click the minimize button.
7. If I now double-click the tray icon, nothing happens.
8. If I do the above one more time, the window appears.

**Comment by ba32107** [comment]
@archfrog, sorry, still unable to reproduce this one. This might be indeed an environment specific problem. Please try with 2.5.1.

**Comment by archfrog** [comment]
@ba32107, sorry to say that the problem persists.  

Here's my new debug info:
```
KeePassXC - Version 2.5.1
Revision: 0fd8836

Qt 5.13.2
Debugging mode is disabled.

Operating system: Manjaro Linux
CPU architecture: x86_64
Kernel: linux 5.3.11-1-MANJARO

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.5
```

Let me know if you want the Arch Linux x64 package that I built; I had to tweak the PKGBUILD file a little bit to get it to build.  I can also provide you with the PKGBUILD file instead.

**Comment by archfrog** [comment]
I switched to Ubuntu Desktop 19.10 x64 and there are no problems at all.

I don't know how Manjaro builds Gnome, but the problem went away as soon as I switched.

Please feel free to close this issue and thanks for looking into it.

**Comment by droidmonkey** [comment]
No problem thank you for reporting back!

**Comment by archfrog** [comment]
Hi guys,

I am having this problem again even on Ubuntu Desktop 19.10 x64...  

As far as I can tell, the issue lies with the Minimize button.  If I use the Close button (x), everything works as it should, but if I use the Minimize button, KeePassXC begins to act up and refuse to show when I select `Toggle Window`.

I haven't looked at the code, but I suppose there's some difference in how you handle Minimize and Close events.  And the Minimize stuff doesn't work well, whereas the Close stuff works as it should.

I am in the process of learning to use the Close button instead of Minimize (with the appropriate setting enabled so that the app only closes to tray), but I thought you might want to know about my experiences :-)

**Comment by droidmonkey** [comment]
Are you using Gnome? Wayland?

**Comment by archfrog** [comment]
Gnome 3.34.1 with NVIDIA drivers 435.

**Comment by archfrog** [comment]
I sometimes suspect that Arc Menu is the culprit.  Everything worked fine until I installed it, but I don't know for sure if it *can* affect anything.

**Comment by archfrog** [comment]
I just wanted to add that the same issue exists for the AutoType feature, which automatically minimizes the window upon completion.  Only the `Close` button appears to work as it should.

It seems that there has been issues with this before: #1595.

I cloned the source to try to look at it myself, but I'm no GUI developer.  As far as I can tell, though, it is `MainWindow::toggleWindow()` that's somehow the root of the problem I am experiencing.

Perhaps this issue needs reopening?

**Comment by droidmonkey** [comment]
I am not going to spend inordinate amount of time diagnosing this issue unless a large contingent of users report it. Otherwise the problem is highly suspect to be your OS environment and NOT KeePassXC.

**Comment by archfrog** [comment]
I fully understand and agree with that.

I'll see if I can locate the precise cause of the issue (Arc Menu?  NVIDIA drivers?) as it **is** very difficult for you guys to fix something that you can't recreate.

However, I don't agree that it is "my OS environment": Manjara (Arch Linux) and Ubuntu BOTH behaves in the same way.

I'll look into it and if and only if I find the cause of the problem, I'll report in this thread here.

Thanks for your time so far :-)

**Comment by droidmonkey** [comment]
Your welcome 😊

**Comment by ba32107** [comment]
@archfrog, I also use stock Ubuntu 19.10, with the same Gnome version as you. I tried to reproduce this again, no luck. I even installed Arc Menu to test, but it still works correctly. 

I think you may install some other program/script/extension that causes this. I suspect this because 1) you are the only one who reported this, and 2) you mentioned you experienced the same thing in two different Linux flavors. Presumably, you set up your environment the same way in both systems - perhaps a setting or application that you installed for both can cause this.

On the flip side, I learned about Arc Menu today which is an awesome extension, so thank you! :)

**Comment by archfrog** [comment]
@ba32107 I think you're right.

Here's my setup procedure (GitHub won't allow me to upload a markdown file), in case you're interested: [Ubuntu-Desktop-Installation.zip](https://github.com/keepassxreboot/keepassxc/files/3993034/Ubuntu-Desktop-Installation.zip)

I'll spin up VMWare and try to install a new Ubuntu 19.10 and see if I can recreate the problem, but it seems highly probable now that it is indeed a problem particular to my setup.

I'm glad you like Arc Menu, it is indeed an awesome extension :)

**Comment by archfrog** [comment]
@ba32107, I have tried with VMware and VirtualBox, and a vanilla Ubuntu Desktop 19.10 x64.  In both cases, I could recreate the problem immediately with nothing else than KeePassXC installed after `sudo apt update; sudo apt upgrade` and a reboot.

Perhaps we're talking past each other?  Basically, what I do is this:

Enable these options in KeePassXC:

1. General/General/Minimize instead of app exit.
2. General/General/Show a system tray icon.
3. General/General/Hide window to system tray when minimized.
4. Click OK in the bottom right corner.

Then what I do is this:

1. I open a KeePass database using my credentials.
2. I click the Minimize button to minimize the window.
3. I repeatedly click the `Toggle Window` menu item on the tray icon.

What I observe is this:

Every second time I clock `Toggle Window`, nothing happens.

If I instead click the `Close` button in the upper right corner of KeePassXC, everything works as expected.  Basically, an overview is as follows:

1. `Close` button works as it should and causes no problems afterwards.
2. `Minimize` button works every time, but causes problems for the next `Toggle Window`.
3. `Toggle Window` tray icon menu item seems to work every time.
4. `Perform Auto-Type` behaves like `Minimize`.

I tried to record a video of what happens, but that didn't work out too well.

The reason this issue is so important for me is that I have like 550 passwords so I use KeePassXC a lot during the day :)  I guess I could switch back to KeePass, but I do prefer KeePassXC.

P.S. I have donated $10 to you guys as a token of appreciation.  I'm a bit low on cash due to the time of the year and the time of the month, but that should probably pay the web hosting for a month or so.

**Comment by droidmonkey** [comment]
Thank you! Also, these steps are very easy to follow, I will try it myself. So the error occurs when you use the normal OS minimize button, then try to toggle window with the tray icon.

**Comment by droidmonkey** [comment]
I cannot replicate this on 19.04 using the exact steps you gave. Will try on 19.10.

**Comment by archfrog** [comment]
I just don't understand what is happening here.  I seem to be the only one that can replicate this issue and yet I used two different virtual machines (which should weed out the possibility of an NVIDIA driver bug).  I am using an RTX 2060 Super with the NVIDIA 435 drivers.

By the way, I noticed that line 1267 in `MainWindow.cpp` uses the macro `Q_OS_UNIX`.  Is that intentional?  The comment below suggests that the code is relevant only for Linux so perhaps `Q_OS_LINUX` would be more appropriate?  Just an odd observation :-)

But I guess we're reaching a point where I just have to accept this little quirk.  We can't chase after shadows forever :-)  If you can't recreate the issue on Ubuntu 19.10, I'll just forget about it.

**Comment by droidmonkey** [comment]
`Q_OS_UNIX` is defined everywhere except Windows. Technically we should just be looking for `Q_OS_LINUX` there to simplify things. That code is also only compiled in for Qt less than 5.9.0.

**Comment by phoerious** [comment]
2.5.0 contains a fix for exactly this behaviour. Previously, it just toggled the window, now it is bringing it to the front instead if it is either minimised or hidden. What you are experiencing is probably a qurirk where this detection isn't working properly. See #3666 for details.

**Comment by ba32107** [comment]
I also did these same exact steps, but was unable to reproduce.
