### ISSUE TITLE
Search does not return results from Group Notes field

### ISSUE THREAD

**Issue by DeeCentralize** [keepassxreboot/keepassxc#3913]
Issue: Entering search keywords only returns matches from individual URL Note fields. and not the Group Notes. This behavior is observed in both Windows 7 and MX Linux 18.3.

Expected Behavior: Search results should include results from the Group Notes

Context: I keep extensive Notes in Groups as well as individual URLs. My previous bookmark manager (Compass - Windows only) held over 30,000 entries collected from 1999 to 2019. KeePassXC is slowly being populated with this personal information manager, bookmark and password data - thus search across all fields is very important.

Thank you for a great tool.

KeePassXC - Version 2.5.1
Revision: 0fd8836

Qt 5.13.1
Debugging mode is disabled.

Operating system: Windows 7 SP 1 (6.1)
CPU architecture: x86_64
Kernel: winnt 6.1.7601

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.5

**Comment by droidmonkey** [comment]
I'm not sure why groups even have notes, TBH

**Comment by DeeCentralize** [comment]
I would be happy to donate an amount you deem suitable in order for a Group Notes search capability to appear in a future version. I have 20 years of extensive notes across hundreds of topic areas in hundreds of folders and this would be extremely valuable. Thanks.

KeePassXC - Version 2.5.1
Revision: 0fd8836
Distribution: AppImage

Qt 5.12.3
Debugging mode is disabled.

Operating system: Debian GNU/Linux 9 (stretch)
CPU architecture: x86_64
Kernel: linux 4.19.0-1-amd64

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.1

**Comment by droidmonkey** [comment]
What do you expect to be returned if a search query matches the group notes? All entries in the group? The notes themselves?

Unfortunately I think you are expecting a different experience from our program then it provides.

**Comment by DeeCentralize** [comment]
I would simply want the search results from the Group Notes to show up in the same Search Results listing that contains hits from the individual URLs. I would not want all the entries in the group to appear if there were search results returned from the Group Notes only. If there were search results from a Group Note and also matching keywords from URL Notes in that group they would both appear in the Search Results list.

There would be no entries under the Title or URL for Group Notes search results as those are not relevant for Group Notes. So those columns would be blank for Group Notes search results. But the Group Notes and URL Notes Search Results would be still co-mingled in one search results listing. If it is easier to code a separate Group Notes Search Results list that should appear in the same screen as the URL Notes Search Results.

**Comment by droidmonkey** [comment]
I'm sorry but this is not going to be implemented.

**Comment by ba32107** [comment]
I agree with @droidmonkey that the current search functionality should not search notes. However I do think there is merit in creating a new group search feature. It could be a subtle, out-of-sight feature (meaning I wouldn't introduce a new search bar). E.g. right click on a group, and search (in all subgroups). We could either filter the group tree to the results only, or show a separate dialog with the results and details.

@DeeCentralize, what do you mean by "URL Notes"?

**Comment by DeeCentralize** [comment]
Each web page that you add to KeePassXC includes a Notes text field. That is the URL Notes. You can toggle it on and off.

Searching by individual Groups to find keywords in the Group Notes is not useful. A Group Notes search should be across the entire database just as the URL Notes Search Results are.

I have decided to work around this bug by adding a "-- Group Notes" entry to each group (without a URL of course) and entering my Group Notes there so that the Search picks them up. Work around.

**Comment by ba32107** [comment]
This is not a bug. It's the lack of a feature that addresses a pretty specific use-case. The groups are just conceptually different from the entries. They offer a logical grouping and hierarchy to organize your entries. The search allows you to filter those, it and should not return the grouping itself. 

To be clear, with my suggestion you can still search all your groups in one click. You could perform a search on your root group, which would search in all your subgroups (and consequently every group you have in your database). But it should return the results in a different way than the search that is currently available.

The main thing to take away here is that it's not possible to merge results from the group search with the entry search results. The two data formats are just not compatible with each other. The way you described the feature would be very counterintuitive.

**Comment by droidmonkey** [comment]
Search is not for groups, we won't be implementing this.
