### ISSUE TITLE
Icons are tiny and fonts are tiny and unreadable on regular laptop screen

### ISSUE THREAD

**Issue by ioogithub** [keepassxreboot/keepassxc#3916]
## Expected Behavior
I would expect that I ran run the application and be able to use it.

## Current Behavior
It is currently unusable with tiny fonts and icons.

## Possible Solution
I have been reading threads for hours and hours about these font and icon scaling issues and I am totally bewildered. Most of them are marked closed and have long discussions, I've tried several solutions but none of them work. I have been using Keepass without any issues for years but I am a new KeepassXC user just trying to get the application running. If anyone knows how I can get the regular sizes icons larger (while not being horribly jagged and blurry) and the text that is a normal readable size I would really appreciated learning about it.

I am not using any special hardware just a regular laptop with a standard 1920 x 1080 screen.

I did check the FAQ as well and didn't see anything helpful here.

## Steps to Reproduce
1. Launch KeePassXC
2. Observe the fonts are tiny and unreadable and the icons are also tiny.

## Context
I can't use the app as it is.

## Debug Info
KeePassXC - Version 2.3.4
Revision: 6fe821c

Libraries:
- Qt 5.11.3
- libgcrypt 1.8.4

Operating system: Debian GNU/Linux 10 (buster)
CPU architecture: x86_64
Kernel: linux 4.19.0-6-amd64

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by droidmonkey** [comment]
Screenshot?

**Comment by SimonChelkowski** [comment]
Hi, I installed KeePassXC under Linux Mint 20 just days ago and have the same issue. My screen is 12" and has FullHD (1920x1080) resolution. 

I attach three screenshots. 
The first shows the "new entry" dialog, where you can see nicely the small icons and small  font in front of each line of entry and also in the side panel on the left hand side. Also you can see that the "entry title" named "Internet > add entry" has font size 16 as set in the system settings (see screenshot # 2) for the "Vorgabeschrift (German language, might be something like "preset font" in English) for the system fonts. 

I played around and found out, that when KeepassXC is open and I change in the  system settings the "preset font" size to a different value, then all fonts are scaled correctly, see screenshot # 3. But apparently, it looks like in screenshot # 1 once I close and relaunch KeePassXC again. 

Note that the icons on the right hand side are tiny as well. This is a further issue.

Please fix this issue. Thank you very much.

Best regards,
Simon

Screenshot # 1: Showing KeepassXC "New entry" dialog with the tiny fonts
![01_Screenshot_KeePassXC_tiny_fonts](https://user-images.githubusercontent.com/622095/95609399-edef0400-0a5e-11eb-8e46-d1e520860e56.png)

Screenshot # 2: Showing system settings dialog for system fonts (German language dialog)
![02_systemfont_dialog_first16](https://user-images.githubusercontent.com/622095/95609405-ef203100-0a5e-11eb-9615-5bdd04e74879.png)

Screenshot # 3: Showing KeepassXC "New entry" dialog with the correctly scaled fonts as the font has been adapted in the system settings / system font dialog while KeepassXC is running and the "new entry" dialog is open
![03_Bildschirmfoto vom 2020-10-09 18-25-46](https://user-images.githubusercontent.com/622095/95609408-f0515e00-0a5e-11eb-89f6-1583ff670ecd.png)

**Comment by droidmonkey** [comment]
Update to 2.6.1. This is not an issue anymore
