### ISSUE TITLE
Autotype feature missing in KeepassXC snap package

### ISSUE THREAD

**Issue by d3vas** [keepassxreboot/keepassxc#392]
The snap package doesn't show the autotype action in the menu and context menu.

## Expected Behavior
Allow autotype when using the snap package of keepassxc

## Current Behavior
Installing the snap package of keepassxc hides autotype entries from the menu

## Possible Solution
Bundle what is needed to make this work inside the snap package

## Steps to Reproduce (for bugs)
1. Install snap
2. Open or create a database
3. Autotype is not shown in the context menu when clicking on an entry

## Context
Without this feature the snap version is not usable for me, also because of the security implications, copying to clipboard exposes the contents...

## Your Environment
* KeePassXC version/commit used: 2.1.3
* Qt version (e.g. Qt 5.3): Qt 5.6.1
* libgcrypt 1.7.2-beta
* Operating System and version: Elementary OS Loki 0.4 (ubuntu 16.04)

**Comment by droidmonkey** [comment]
This is my fault, I forgot to add the X11 libraries to the snapcraft build script so it never built the auto-type plugin (cmake guards FTW).

I have uploaded a new build of v2.1.3 that supports auto-type

**Comment by StefanB08** [comment]
Same environment, same issue in v.2.1.4.

**Comment by droidmonkey** [comment]
And that's cause the new snapcraft file is in develop branch... I cant win lol

**Comment by droidmonkey** [comment]
Working in 2.2.0 snap release.
