### ISSUE TITLE
Spanish translation vocabulary changed

### ISSUE THREAD

**Issue by cyphra** [keepassxreboot/keepassxc#3920]
[keepassx_es.ts.gz](https://github.com/keepassxreboot/keepassxc/files/3882685/keepassx_es.ts.gz)

**Comment by cyphra** [comment]
"Fichero llave" modified to "Cerrojo", maybe there are some no modified.

**Comment by droidmonkey** [comment]
Make any translation changes on https://transifex.com/keepassxc
