### ISSUE TITLE
RFE: Historical password tracking / database

### ISSUE THREAD

**Issue by rcpao** [keepassxreboot/keepassxc#3923]
## Summary
Keep track of previously used/stored passwords (with site and date) to prevent reuse.

## Desired Behavior
When a password is stored, it should be checked in the database and a warning given if it has been used before.

## Possible Solution
Some people want online checking (in a secure fashion which does not give out your password in checking the comparison); however, this database would be stored locally with no network access.
A locally stored password history (possibly using backup entries in the existing file) might be a quick to code solution.

## Context
It would be good not to accidentally reuse a password that has already been used elsewhere.

**Comment by droidmonkey** [comment]
If you are using the password generator then password reuse is not an issue.
