### ISSUE TITLE
Move browser integration access key management from the DB level to the group level

### ISSUE THREAD

**Issue by hardfalcon** [keepassxreboot/keepassxc#3926]
Please move the access key management for browser extensions and other clients using KeepassXC as their backend from the database level down to the group level, so users can have distinct groups inside the same database for different clients. For example, I might want to use KeepassXC as my credentials storage for both Firefox and Chromium, but I might want to grant Chromium access to a different subset of credentials than Firefox. Also, in the future, there might (hopefully) be an extension allowing Thunderbird to use KeepassXC in a manner similar to Firefox, so I might want to have a distinct group for this as well.

The access permissions should be (recursively) inherited from parent groups down to their child groups.

**Comment by varjolintu** [comment]
This has been discussed here: https://github.com/keepassxreboot/keepassxc-browser/issues/353
