### ISSUE TITLE
MacOS keybindings are incorrect in recent commit

### ISSUE THREAD

**Issue by adudek16** [keepassxreboot/keepassxc#3928]
It appears that the changes to docs/KEYBINDS.md  for macosx shortcuts are incorrect.
Should they be cmd + <key> instead of ctrl +<key> ?
This is in commit cb28329f144ac9a3b022fcadd493677e5b6ba927

At least testing on my mac i need to use the cmd key.

**Comment by droidmonkey** [comment]
We don't change the bindings file specifically for macOS. A simple comment at the top should be sufficient.

**Comment by adudek16** [comment]
I would assume that would be fine. It seems confusing to those who would be new as the file says ctrl when it is actually cmd.

**Comment by c4rlo** [comment]
Nitpick: note that cb28329 (from #3917) did not change this. `KEYBINDS.md` was created in #3215.

**Comment by adudek16** [comment]
Sorry. I did not look back and I did misread the comment thinking it was mentioning the keyboard shortcuts for MacOS.
