### ISSUE TITLE
Ability to export search results to CSV, HTML, etc

### ISSUE THREAD

**Issue by bigalgeorge** [keepassxreboot/keepassxc#3929]
## Summary
The desktop application should be able to manage the content, and/or use the content for reports.

For example, Ive just found that gishpuppy.com has after many years ceased to exist. My db of 100's of items include possible 50% mynominatedemail@gishpuppy.com and the only reference to all of these is not my email program, but Keepassxc.

I do a search for gishpupply using Keepassxc which gives me an excellent view of all my needed references, but there is no way to print, let alone export these entries as csv.

Export csv does the lot, not selected.
Thanks, Al.

**Comment by droidmonkey** [comment]
Why do you need to export the search results?

**Comment by schollw** [comment]
I have to agree with bigalgeorge. It would be nice to have an export function that does not export the whole database but groups and / or search results (is also a good idea). I am an IT consultant and my customers, for example, would like a printout of the entries. The possibility to export only one group or a search result to your own database would be a great thing! The other way around. The customer also uses KeePass and I want to import his database into mine (into a group). Would be nice too.

**Comment by droidmonkey** [comment]
This would be covered under #1940
