### ISSUE TITLE
Bug: Cannot drag entries between folders

### ISSUE THREAD

**Issue by porjo** [keepassxreboot/keepassxc#3930]
Fedora Linux 31
Wayland Display Manager
keepassxc-2.5.1-1.fc31.x86_64

I can't move items between folders by dragging them. The item drags, but when I release it doesn't move to the new folder and stays in the older folder. I've tried dragging from child folder to parent, and vice versa - nothing works. I have rebooted my PC but the issue remains. This has worked for me in the past, but I couldn't say on which version as it has been some time since I've needed to do this.

May be related to #3687

**Comment by droidmonkey** [comment]
This isn't something that is broken in KeePassXC

**Comment by droidmonkey** [comment]
Ahhh confirmed, this is a Wayland bug. Likely a bug in Qt.

**Comment by droidmonkey** [comment]
Confirmed this is a Qt bug: https://bugreports.qt.io/browse/QTBUG-80303

**Comment by rickhewes** [comment]
Work around: 

```> keepassxc -platform xcb ```

Until upstream fix comes in.
