### ISSUE TITLE
CLI: provide password via environment variable

### ISSUE THREAD

**Issue by NautiluX** [keepassxreboot/keepassxc#3934]
# Use environment variable to unlock database

## Summary

Currently, when using `keepassxc-cli` in scripts multiple times, I have to enter the password each time. I see that a cache as mentioned in [this issue](https://github.com/keepassxreboot/keepassxc/issues/1483) would mean a huge refactoring.

As a first easier step, I would like to be able to provide the password in an environment variable, so I can read it once at the beginning of my script and `keepassxc-cli` automatically uses it if the variable is set (guess that would be [somewhere here](https://github.com/keepassxreboot/keepassxc/blob/cb28329f144ac9a3b022fcadd493677e5b6ba927/src/cli/Utils.cpp#L130)).
I thought about implementing it right away, but I'd like to open a discussion around naming and usefulness.
## Possible Solution
read environment variable (proposal: `KEEPASS_DB_PASSWORD`) [here](https://github.com/keepassxreboot/keepassxc/blob/cb28329f144ac9a3b022fcadd493677e5b6ba927/src/cli/Utils.cpp#L130) and use it to unlock database if set. If not, ask as before

## Context
I want to execute multiple keepassxc-cli commands in one script without entering the password multiple times.

**Comment by droidmonkey** [comment]
That seems extraordinarily insecure

**Comment by NautiluX** [comment]
It's up to the user of it to use it in a secure or unsecure way I'd say. I don't see an issue in reading the password from CLI and use it in a script, it will only be stored in memory for the runtime of the script.

**Comment by droidmonkey** [comment]
We also have a open mode now in 2.5 that keeps the database open

**Comment by NautiluX** [comment]
sounds nice, can you point me to how to use it?

**Comment by droidmonkey** [comment]
`man keepassxc-cli`

**Comment by dverbeek84** [comment]
For people reading this issue:

`echo "passsword" | keepassxc-cli ls vault.kdbx`

**Comment by dzintars** [comment]
^ Just make sure to clean up the trails. `echo` is not the safest method.
