### ISSUE TITLE
Unable to drag passwords between folders on Linux

### ISSUE THREAD

**Issue by exicx** [keepassxreboot/keepassxc#3936]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

Keys should be drag-able between folders

## Current Behavior
[NOTE]: # ( Tell us what actually happens )

When I select a key entry and attempt to drag it into a new folder (group) in the left pane the key should be moved from the current folder to the new one. This used to work in previous versions.

If I select an entry and attempt to drag it, I'll see the entry name/box move as expected to follow my mouse, and when dragging the entry to a new folder I'll see the folder highlight under my mouse. But when I release the mouse the entry fades and nothing happens.

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1. Have 2+ folders, make an entry in folder A and attempt to drag to folder B.

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.5.1
Revision: 0fd8836

Qt 5.12.5
Debugging mode is disabled.

Operating system: Fedora 31 (Workstation Edition)
CPU architecture: x86_64
Kernel: linux 5.3.11-300.fc31.x86_64

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.5

Package installed from system package manager, however it also happens in the flatpak version. GNOME/Wayland on Fedora Desktop.

**Comment by droidmonkey** [comment]
This is a bug with Qt on Wayland. Already reported in a separate issue.

**Comment by exicx** [comment]
Ah, thanks!
