### ISSUE TITLE
Crashes when idling and quitting

### ISSUE THREAD

**Issue by TempSpas** [keepassxreboot/keepassxc#3937]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )
With the most recent update, KeePassXC has begun crashing occasionally. I've noticed it a few times upon quitting the application and just now it crashed while idling.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Application should not crash.

## Current Behavior
Application occasionally crashes when idle or upon quitting.

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
I can't get it to crash consistently, but when it has crashed upon quitting I've done the following:

1. Press Command-Tab and navigate to the application icon
2. Command-Q to quit
3. Observe program hangs and eventually crashes.

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.5.1
Revision: 0fd8836

Qt 5.13.1
Debugging mode is disabled.

Operating system: macOS Mojave (10.14)
CPU architecture: x86_64
Kernel: darwin 18.7.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
 libgcrypt 1.8.5

macOS 10.14.6

The following is a log of the crash that occurred while the application was idling. If I can repeat one of the hang/crash instances upon quitting, I will upload that.

[kpx_crash.txt](https://github.com/keepassxreboot/keepassxc/files/3894888/kpx_crash.txt)

**Comment by droidmonkey** [comment]
This is a bug in Qt and reported in a separate issue already.
