### ISSUE TITLE
KeepassXC crashes at start

### ISSUE THREAD

**Issue by Sibiriak** [keepassxreboot/keepassxc#3938]
After recent update to the latest version 2.5.1-Win64, KeepassXC is not working anymore, it crashes during start with the next mistake:

> 
> This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
> 
> Available platform plugins are: direct2d, minimal, offscreen, webgl, windows.

Mistake happens in 32-bit and 64-bit versions both.

Operating system: Windows 10 x64
CPU architecture: x64

No extensions were isntalled, I used  standard version of the program, it worked fine before update.

**Comment by droidmonkey** [comment]
Are you using the ZIP or MSI version

**Comment by Sibiriak** [comment]
> 
> 
> Are you using the ZIP or MSI version

MSI installer was used

**Comment by droidmonkey** [comment]
And you downloaded it from https://keepassxc.org?

Can you check if the following file exists: C:\Program Files\KeePassXC\platforms\qwindows.dll

**Comment by Sibiriak** [comment]
> 
> 
> And you downloaded it from https://keepassxc.org?
> 
> Can you check if the following file exists: C:\Program Files\KeePassXC\platforms\qwindows.dll

Yes, I downloaded from the official web-site and the mentioned file exists.

**Comment by droidmonkey** [comment]
Do you have any development environments setup like Cygwin or MSYS? Do you have any QT environment variables defined? Qt installed anywhere else on your computer?

This is clearly not an issue with KeePassXC itself, there is something going on with your computer setup that is causing this.

**Comment by Sibiriak** [comment]
> 
> 
> Do you have any development environments setup like Cygwin or MSYS? Do you have any QT environment variables defined? Qt installed anywhere else on your computer?
> 
> This is clearly not an issue with KeePassXC itself, there is something going on with your computer setup that is causing this.

As far asI remember, not dealed with Cygwin nor MSYS.
The only related software is Pyside2 library installed on my computer, and system variable "QT_PLUGIN_PATH" with value "C:\Users\username\Roaming\Python\Python37\site-packages\PySide2\plugins"

**Comment by droidmonkey** [comment]
Delete that ENV var, that is the source of your problems. https://stackoverflow.com/questions/51286721/changing-qt-plugin-path-in-environment-variables-causes-programs-to-fail

**Comment by Sibiriak** [comment]
> 
> 
> Delete that ENV var, that is the source of your problems. https://stackoverflow.com/questions/51286721/changing-qt-plugin-path-in-environment-variables-causes-programs-to-fail

Then why does version KeePassXC-2.4.3-Win64  work fine even with this variable but 2.5.1 crashes?

**Comment by droidmonkey** [comment]
It is not crashing, it is telling you it cannot find the plugin information. This is most likely because the new Qt version is doing something different then before.
