### ISSUE TITLE
TOTP seems broken on ppc64le

### ISSUE THREAD

**Issue by avollmerhaus** [keepassxreboot/keepassxc#3939]
I'm using KeepassXC on a ppc64le machine (IBM Power9 processors), and it seems that the TOTP feature has some ppc64le-related bug.
It's working with the same database on a x86_64 machine.

## Expected Behavior
Working TOTP tokens.

## Current Behavior
I've tried multiple sites, but they won't accept the tokens generated by my KeepassXC instance as long as I'm using the ppc64le machine.
This is true for TOTP setup as well as tokens that are generated for entries that I've already setup on x86_64.

## Steps to Reproduce
1. Install KeepassXC on ppc64le, I'm using a Raptor Engineering Talos2
2. Generate TOTP token
3. Websites reject the token

## Debug Info
KeePassXC - Version 2.5.1
Revision: 0fd8836

Qt 5.12.5
Debugging mode is disabled.

Operating system: Gentoo/Linux
CPU architecture: power64le
Kernel: linux 4.19.72-gentoo

Enabled extensions:
- Auto-Type
- SSH Agent
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.5

**Comment by droidmonkey** [comment]
Check your computer time

**Comment by avollmerhaus** [comment]
It's synchronized via NTP using chronyd, the same as on the x86_64 machines.
```
$ timedatectl --monitor
               Local time: Mi 2019-11-27 12:58:19 CET
           Universal time: Mi 2019-11-27 11:58:19 UTC
                 RTC time: Mi 2019-11-27 11:58:19
                Time zone: Europe/Berlin (CET, +0100)
System clock synchronized: yes
              NTP service: active
          RTC in local TZ: no
```

**Comment by droidmonkey** [comment]
I have no clue what else to check

**Comment by avollmerhaus** [comment]
My guess: somewhere inside the TOTP code (or one of it's dependencies?) there is an assumption that's only true when compiled for x86_64.

**Comment by droidmonkey** [comment]
Here's the calculation code, can you spot anything untoward:

https://github.com/keepassxreboot/keepassxc/blob/cb28329f144ac9a3b022fcadd493677e5b6ba927/src/totp/totp.cpp#L185-L250

**Comment by avollmerhaus** [comment]
I've clicked through to that one already, but I've got almost no C / C++ skills at all.

**Comment by hifi** [comment]
Do the TOTP tests succeed if you could build KeePassXC outside of portage and run all tests?

**Comment by avollmerhaus** [comment]
I've compiled it myself using `-DWITH_XC_YUBIKEY=OFF` for the configuration step, `make test` reports `100% tests passed, 0 tests failed out of 31`

**Comment by avollmerhaus** [comment]
Oh, and mind the "le" at the end of "ppc64le", this is actually a little endian host :)
And thanks for the support so far!

**Comment by droidmonkey** [comment]
If the tests pass then the calculation of the totp code is not the fault

**Comment by avollmerhaus** [comment]
Okay, is there anything I can do to debug this further?

**Comment by droidmonkey** [comment]
I don't have any ideas at this time. This could even be a bug in Qt on that platform.

**Comment by avollmerhaus** [comment]
It simply started working for me. I have no clue why.

**Comment by droidmonkey** [comment]
Must have hit the ducomodulator button again. Hehe
