### ISSUE TITLE
Default the expiry date to today / add the preset

### ISSUE THREAD

**Issue by MisterY** [keepassxreboot/keepassxc#3940]
This is for the desktop client.

![image](https://user-images.githubusercontent.com/462445/69715141-0d5f9580-1108-11ea-977e-0dbf2ca47aad.png)

## Summary
Please provide a preset for Today *or* set the default value in the Expires field to today, if it is not checked.

## Desired Behavior
a) Add the preset in the drop-down that sets the Expires value to today's date, or
b) Set the Expires value to today in case it is not active. This way it will default to today if we tick the box.

## Context
Currently it takes quite a few clicks to set today's value if we are deprecating the entry.
I'm not sure where the current default comes from. For me it is often months or years away from the current day.

![image](https://user-images.githubusercontent.com/462445/69715489-9ecf0780-1108-11ea-9362-1c36646716bd.png)

**Comment by JJRcop** [comment]
Do you mean at an arbitrary time today, like 23:59, or do you mean the current date and time, as in expiring immediately?

If the latter, I would say *"Now"* is a better description for the preset.

**Comment by MisterY** [comment]
"Now" is probably more practical, based on my experience so far. I normally just want to mark entries as expired. Most of the time I don't know when exactly they have expired but they are definitely expired now. So, the current time or time in the past would work. That means that  "today" would also be OK (at least in my case), with Today being today's date with 00:00 time.

**Comment by MisterY** [comment]
Thank you!
