### ISSUE TITLE
Merge popup randomly appears when kdbx file is on network share

### ISSUE THREAD

**Issue by brainfoolong** [keepassxreboot/keepassxc#3941]
I have, ever since i use KPXC, one of my databases on a network share in windows, assigned to a drive letter. Since v2.5.0 (Also on current 2.5.1) every now and then the "Merge" popup snaps into my view, doesn't matter which programm i have currently opened.

So it happens sometime that the popup distract my work in certain programs. I always press "Merge" or "Abort", it doesn't matter. The file hasn't changed, neither on KPXC side nor on the share.

The only thing i can imagine is that, for a short period, the network drive seems inactive/not available and as soon as it comes available again KPXC will detect this and pops up the merge window for whatever reason.

I cannot give a reproduction example here, as it doesn't happen when i try to reproduce it. It happen round about 5-10 times during 8 hours of activity.

This happen only on my files that are on a windows shared drive, it does not happen on local disk files.

Here is the codeline (i guess) for the popup that appears: https://github.com/keepassxreboot/keepassxc/blob/develop/src/gui/DatabaseWidget.cpp#L1449

Again, nothing has changed on network or local side in the KPXC database when it appear, but the Asterisk beside the database name in the tab indicates a change.

Let me know if i can provide any more information.

	KeePassXC - Version 2.5.1
	Revision: 0fd8836

	Qt 5.13.1
	Diagnosemodus ist deaktiviert.

	Betriebssystem: Windows 10 (10.0)
	CPU-Architektur: x86_64
	Kernel: winnt 10.0.17134

	Aktivierte Erweiterungen:
	- Auto-Type
	- Browser-Integration
	- SSH-Agent
	- KeeShare (bestätigtes und unbestätigtes Teilen)
	- YubiKey

	Kryptographische Bibliotheken:
	 libgcrypt 1.8.5

**Comment by brainfoolong** [comment]
Here is the codeline (i guess) for the popup that appears: https://github.com/keepassxreboot/keepassxc/blob/develop/src/gui/DatabaseWidget.cpp#L1449

Again, nothing has changed on network or local side in the KPXC database when it appears.

**Comment by droidmonkey** [comment]
Duplicate issue

**Comment by fan-tom** [comment]
Have the same issue with WebDAV on macOS

**Comment by droidmonkey** [comment]
I think I discovered the cause of this issue

**Comment by brainfoolong** [comment]
Hi, just an information. This specific issue is not resolved with 2.5.2. Still have this problems.

**Comment by droidmonkey** [comment]
You are probably seeing what is described in #4118

**Comment by brainfoolong** [comment]
Probably yes, i wait for 2.6.0 than. Thanks.
