### ISSUE TITLE
KeepassXC 2.5.1 Import of Chrome password CSV not including the URL in new database.

### ISSUE THREAD

**Issue by kregerjd** [keepassxreboot/keepassxc#3949]
Started a new database using the CSV file Chrome generated. When I went to login in for some sites to test the browser extension out, the login couldn't be found. Dug around the individual entries, and noticed the URL was missing from every entry. I checked the CSV using LibreOffice Calc, and noticed that the CSV Chrome generated does include the URL, along with the name. But name ends up as it's own group, and url becomes a title, with username, and password as 'username' and 'password.' I do not know if this is due to the way Chrome generates the CSV, or how Keepass imports the data.

Operating system: Windows 10 Version	10.0.18363 Build 18363
CPU architecture: Intel x86

Enabled extensions:
- KeepassXC-Browser

**Comment by kregerjd** [comment]
So I figured this out, it was my misunderstanding of how to properly import the CSV. I just needed to select the title column and make that fall under the URL column in KeepassXC. Sorry for wasting time. I don't really have much experience in DB management.

**Comment by iQiexie** [comment]
Thanks!! You helped me so much
