### ISSUE TITLE
display bug, 

### ISSUE THREAD

**Issue by pwepwe973** [keepassxreboot/keepassxc#3950]
display bug windows has a higher resolution than any other computer software 
![Capture du 2019-11-28 22-56-45](https://user-images.githubusercontent.com/37281042/69833858-c58b5c00-1236-11ea-8a50-4c81a3daf827.png)

## Expected Behavior
That the Software is a nominal size

## Current Behavior
the resolution is disproportionate compared to the other softwares, the texts, the window, the logos are very big you can compare the color of the text on the attached picture in relation to thunderbird

## Debug Info
( Paste debug info from Help → About here )
KeePassXC - 2.5.1 and  2.4.3 on AppImage
Revision: 0fd8836

Libraries:
- LIBS

Operating system: OS
Ubuntu Version 19.10 (Eoan Ermine) 64-bit
Noyau Linux 5.3.0-23-generic x86_64
MATE 1.22.2
Memoir : 15,5 Gio
CPU architecture: Intel® Core™ i7-8750H CPU @ 2.20GHz × 12 

Enabled extensions:
- Saisie automatique
- Intégration aux navigateurs
- Agent SSH
- KeeShare (partage signé et non signé)
- YubiKey
- Intégration au Secret Service

Bibliothèques cryptographiques :
 libgcrypt 1.8.1

**Comment by varjolintu** [comment]
Try setting the Qt scale factor manually:
`export QT_AUTO_SCREEN_SCALE_FACTOR=1`

You can also try to tweak `export QT_SCREEN_SCALE_FACTORS='1.5;1'`.

**Comment by droidmonkey** [comment]
That is exactly the issue.

**Comment by pwepwe973** [comment]
hello
how do I have to modify this parameter?

**Comment by droidmonkey** [comment]
You can add it to your `.bashrc` file in your home directory, log off/log on. Or you can start KeePassXC like this: `QT_AUTO_SCREEN_SCALE_FACTOR=1 keepassxc`

**Comment by pwepwe973** [comment]
ok thank you, i go try

**Comment by pwepwe973** [comment]
I come to try and not to walk

**Comment by droidmonkey** [comment]
shouldn't be a problem, just put the AppImage executable in place of "keepassxc"

**Comment by pwepwe973** [comment]
Yes, that's what I did but it did not change anything

**Comment by droidmonkey** [comment]
Then you should try the QT_SCREEN_SCALE_FACTORS env var. That lets you set a custom scale for each monitor. The problem here is that Qt cannot properly determine your screen scaling due to whatever reason. This is common on Linux and not something KeePassXC is doing wrong.

**Comment by pwepwe973** [comment]
thank you for your help
this worked eventually, I put a file keepassxc.sh that I run from a file.desktop

**file.desktop :** 
[Desktop Entry]
Encoding=UTF-8
Version=1.0
Type=Application
NoDisplay=true
Exec=sh /home/pseudo/Appimages/Securité/KeePassXC.sh
Name=KeePassXC
Comment=Définition personnalisée pour KeePassXC
Name[fr_FR]=keepassxc
Keywords=gestionaire;mot de passe;
Icon=keepassxc
Categories=Outil;

**File.sh :** 
#! /bin/bash
export QT_SCALE_FACTOR=1
export QT_AUTO_SCREEN_SCALE_FACTOR=0
export QT_SCREEN_SCALE_FACTORS=1
/home/pseudo/Appimages/Securité/KeePassXC-2.5.1-x86_64.AppImage

**Comment by droidmonkey** [comment]
Ok great!
