### ISSUE TITLE
Copy & Paste issues on Fedora 31

### ISSUE THREAD

**Issue by joh-ku** [keepassxreboot/keepassxc#3956]
## Expected Behavior
Copy & Paste should copy password from keepassxc to any application.

## Current Behavior
Copy & Paste does not work for (to) all applications. E.g. i cannot paste a password in [VeraCrypt](https://www.veracrypt.fr/en/Home.html) or [CherryTree](https://www.giuspen.com/cherrytree/).

## Possible Solution
1. Copy & Paste elsewhere in between (e.g. text editor) and copy/paste from there
2. Downgrade keepass to 2.4.3, which is the previous available package on fedora 31
```
$ sudo dnf --showduplicates list keepassxc
Letzte Prüfung auf abgelaufene Metadaten: vor 0:17:14 am So 01 Dez 2019 10:07:24 CET.
Installierte Pakete
keepassxc.x86_64                      2.5.1-1.fc31                      @updates
Verfügbare Pakete
keepassxc.x86_64                      2.4.3-6.fc31                      fedora  
keepassxc.x86_64                      2.5.1-1.fc31                      updates 
```

## Steps to Reproduce
On fedora 31 install KeePassXC v.2.5.1 and e.g. VeraCrypt v1.24 and try to copy & paste.

## Debug Info
From package manager (dnf): keepassxc.x86_64 2.5.1-1.fc31
VeraCrypt: 1.24-Hotfix 1
CherryTree 0.38.9

Operating system: Fedora 31
CPU architecture: Intel i7-6700K (Skylake)
Kernel: 5.3.12-300.fc31.x86_64

Enabled extensions:
- none

**Comment by droidmonkey** [comment]
This is probably a Wayland issue and not something we can solve. In 2.5 we enabled Wayland support again and all its glorious BS.

**Comment by joh-ku** [comment]
Hi @droidmonkey 
you're right. The problem disappears by logging into fedora with Xorg instead of Wayland. Strange that this behavior affects just a bunch of applications anyway ..

**Comment by droidmonkey** [comment]
Not something we can fix, this would be a Qt thing.

**Comment by btong** [comment]
I only have this problem with keepassxc in Fedora 32.
