### ISSUE TITLE
Currently there seems no way to update one passwords for several entries

### ISSUE THREAD

**Issue by bitstreamout** [keepassxreboot/keepassxc#3958]
that is that there is no way to do a mass password update e.g. for a domain wide or host group which are all with the same e.g. company  password.

**Comment by droidmonkey** [comment]
You should setup references between those entries.

**Comment by bitstreamout** [comment]
OK, that is also described in the documentation,  only I've modified firefox_decrypt to generate me a csv which I have used to create a kdbx with the main group Internet for my firefox passwords.  Now I've beside other entries a lot of company entries with same user and password and I'm looking for a way to change this password.  The reference way would be prefect if I'm would be able or understand how to do this afterwards for independent entries ;)

**Comment by droidmonkey** [comment]
First you need to know the UUID of the entry you want to reference:
![image](https://user-images.githubusercontent.com/2809491/70391615-00af2d00-19a5-11ea-9043-60827bf58794.png)

Then craft a password for every other entry in the following format:
![image](https://user-images.githubusercontent.com/2809491/70391618-0ad12b80-19a5-11ea-85cb-b9cd168d7314.png)

`{REF:P@I:[UUID HERE]}`

**Comment by droidmonkey** [comment]
A GUI way to do this is covered by #433
