### ISSUE TITLE
macOS: Keepassxc settings stay always in dark mode 

### ISSUE THREAD

**Issue by stefan1983** [keepassxreboot/keepassxc#3959]
I'm running keepassxc on macOS Catalina and set my desktop to "automatic" (to switch between light and dark mode). When in dark mode, the settings page looks good:

![image](https://user-images.githubusercontent.com/8542806/69914750-0dcd9880-1448-11ea-974f-95d4c88734dd.png)

when switching to light mode (which Catalina does itself based on current daytime), it looks like that:

![image](https://user-images.githubusercontent.com/8542806/69914761-3786bf80-1448-11ea-82f5-9b0fb0c3bf28.png)

KeePassXC - Version 2.5.1
Revision: 0fd8836

Qt 5.13.1
Diagnosemodus ist deaktiviert.

Betriebssystem: macOS 10.15
CPU-Architektur: x86_64
Kernel: darwin 19.0.0

Aktivierte Erweiterungen:
- Auto-Type
- Browser-Integration
- SSH-Agent
- KeeShare (bestätigtes und unbestätigtes Teilen)
- YubiKey
- TouchID

Kryptographische Bibliotheken:
 libgcrypt 1.8.5

**Comment by droidmonkey** [comment]
This is a Qt issue and you need to restart KeePassXC when the desktop color changes.

**Comment by stefan1983** [comment]
Will it be fixed though? Other non-OS programs don't have this kind of issue.

Thanks

**Comment by droidmonkey** [comment]
If Qt fixes it, sure. We don't have control over that

**Comment by parautenbach** [comment]
Just adding my 2c: This issue also exists on v2.6.6. 

Is there perhaps a link to the relevant issue reported on the Qt project?

I've scanned through a [list of issues](https://bugreports.qt.io/browse/QTCREATORBUG-23828?jql=text%20~%20%22dark%20mode%20macos%22) that might be relevant but wasn't sure which of these would be causing this particular issue. Some of the [feedback](https://bugreports.qt.io/browse/QTCREATORBUG-23828?focusedCommentId=506542&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-506542) seems quite hostile, so there may not be any hope.

**Comment by droidmonkey** [comment]
Hmmmm? We solved this problem in 2.6.3. https://github.com/keepassxreboot/keepassxc/pull/5851

**Comment by parautenbach** [comment]
Thanks, good to know. 

Unfortunately, I followed the advice here so I've destroyed the evidence, but my app was stuck in this combo mode for about a week now. I'll wait for it to happen again and then post a screenshot.
