### ISSUE TITLE
Can't copy Custom Attributes

### ISSUE THREAD

**Issue by swamp-fish** [keepassxreboot/keepassxc#396]
Can't copy Custom Attributes that i've added in Advanced -> Additional Attribues. In Keepassx2 it works as it should.
## Expected Behavior

1) Right Click on the entry
2) Copy attributs to clipboard
3) Choose custom attribute that you created
4) Paste it anywhere
5) See your information pasted well

## Current Behavior

1) Right Click on the entry
2) Copy attributs to clipboard
3) Choose custom attribute that you created
4) Paste it anywhere
5) Nothing is pasted

## Your Environment

Revision: b9279f73fa58d75e1ec88f734f3c77c0f015a348
Using:
- Qt 5.8.0
- libgcrypt 1.7.6
- latest Manjaro
- keepassxc 2.1.2-2

**Comment by TheZ3ro** [comment]
I'm using KeePassXC 2.1.3, Revision: 882115ecadb7fa6fcfb811d385d7491fa5c2f7a0

Everything works fine

**Comment by droidmonkey** [comment]
Related to #68 ?

**Comment by phoerious** [comment]
I would assume so.
