### ISSUE TITLE
v2.5.1 for Mac constantly crashing on saving action

### ISSUE THREAD

**Issue by JanZeman** [keepassxreboot/keepassxc#3960]
Hello,

Since the update to v2.5.1 KeyPassXC is constantly crashing on my Mac on 25% of the saving actions. Every cca fourth attempt to save data means crash. I save to OneDrive, guessing this might be connected to the issue? Please let me know how to find crash log in case the app creates one.

Best regards
Jan

Here is the Debug Info:
KeePassXC - Version 2.5.1
Revision: 0fd8836

Qt 5.13.1
Debugging mode is disabled.

Operating system: macOS Mojave (10.14)
CPU architecture: x86_64
Kernel: darwin 18.7.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
 libgcrypt 1.8.5

**Comment by droidmonkey** [comment]
This is a duplicate issue.
