### ISSUE TITLE
Right click menu missing Add new entry to when in non-empty group

### ISSUE THREAD

**Issue by adudek16** [keepassxreboot/keepassxc#3962]
When in a group, when you right click, add new entry used to be on of the choices in all groups, not just Root or empty groups. Cu

## Summary
Add New Entry to right click menu when in a group.

## Desired Behavior
When you right click in the in entry (?) window, add new entry should be a choice just as it is in the Root or empty groups.ally happens )

## Steps to Reproduce
1. Create new group
2. Enter group
3. right click, new entry is the only available option...
4. add new entry
5. right click, new entry is no longer available

## Context
Used to having add new entry in the menu. Nothing wrong with the keyboard shortcut, just breaks workflow when using the mouse and not having the option in the menu and having to either go to the menu item or use the keyboard shortcut

## Debug Info
[KeePassXC - Version 2.5.1
Revision: 0fd8836

Qt 5.13.1
Debugging mode is disabled.

Operating system: macOS Mojave (10.14)
CPU architecture: x86_64
Kernel: darwin 18.7.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
 libgcrypt 1.8.5

**Comment by droidmonkey** [comment]
Duplicate issue

**Comment by adudek16** [comment]
This is not a duplicate of #3839

**Comment by droidmonkey** [comment]
We removed it from the **context** menu when an entry was selected because it made no sense. It's not going back in at this point.
