### ISSUE TITLE
[Feature Request] Domain synonym

### ISSUE THREAD

**Issue by TTTPOB** [keepassxreboot/keepassxc#3964]
[TIP]:  # ( Provide a general summary of the feature in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Summary
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
Imagine a scene, a website has multiple ip/domains pointed to the same service, if I can tell keepassxc that these domains stand for the same website, things would be more easy. otherwise I will need to add the same credential multiple times

## Desired Behavior
[NOTE]: # ( Tell us how the new feature should work, be specific )
I think the similar function of lastpass meets my demand

## Possible Solution
[NOTE]: # ( Not required, but suggest ideas on how to implement the addition or change )

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )

**Comment by droidmonkey** [comment]
This already exists using the browser integration as of 2.5. Go into the entry editing page and choose browser integration to add multiple urls.
