### ISSUE TITLE
Inserting Password or Username only Hotkey-definition 

### ISSUE THREAD

**Issue by Lihaes** [keepassxreboot/keepassxc#3965]
## Summary
[NOTE]: # Settings for the Hotkey-Setting for Password / User insertion

## Desired Behavior
[NOTE]: # There should be an option within the settings to specify Hotkeys for password / user insertion (only)

## Possible Solution
[NOTE]: # ( Not required, but suggest ideas on how to implement the addition or change )

## Context
[NOTE]: # Many websites do only let you insert password after you click "next" or whatever

**Comment by droidmonkey** [comment]
This is a duplicate
