### ISSUE TITLE
Password are shown and username are hidden

### ISSUE THREAD

**Issue by hargathor** [keepassxreboot/keepassxc#3966]
The passwords of the database are shown in the KeepassXC windows and the usernames are hidden

## Expected Behavior
Passwords hidden and usernames shown

## Current Behavior
Usernames are hidden and Passwords are shown

## Possible Solution
.....

## Steps to Reproduce
1. Open KeepassXC
2. Unlock your database
3. prepare to be amazed :)

## Context
Windows manager i3 (not sure that it is relevant)

## Debug Info
KeePassXC - Version 2.5.1
Revision: 0fd8836

Qt 5.13.2
Debugging mode is disabled.

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 5.3.13-arch1-1

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.5

**Comment by droidmonkey** [comment]
Press Ctrl+Shift+C

**Comment by hargathor** [comment]
my bad, sorry about that......

**Comment by droidmonkey** [comment]
No worries, its a common question.
