### ISSUE TITLE
OnlyKey not typing password into KeePasXC window, unless re-plugged in

### ISSUE THREAD

**Issue by dhammel** [keepassxreboot/keepassxc#3968]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Current Behavior
[NOTE]: # ( Tell us what actually happens )
When OnlyKey is currently plugged in, then I launch KeePassXC and press button to type out my keepass password, onlykey acts as if its typing it (light goes out, then back on) yet no text is typed in. Restarting program doesn't resolve it, but unplugging and replugging onlykey does, until it gets locked out due to inactivity, then I must unplug and replug after opening software. This seems to occur when, and only when the Hardware key option in the dialog and shown with selectable options for i beleive challenge response. If that option is greyed out, which is what happens when in unplug and replug onlykey then my password can be typed out by onlykey. This issue only occurs in KeePassXC. I have done a factory reset of onlykey, and re-tried it after restore. I've even tried a different onlykey as well. Not many ways i know of debugging this type of issue.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
The onlykey should be able to, at any time be able to type out the password stored into the password dialog box of KeePassXC

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )
Since I do not use the Hardware key feature, the ability to disable the hardware key function all together may solve it for me. People who do use this feature, who have this same issue it would be another solution to try and resolve this, I wouldn't know what exactly is causing this. Maybe it's looking for a response from the onlykey, but not receving something expected and assuming that said response is not to be typed in.

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.5.1
Revision: 0fd8836

Operating system: Ubuntu 19.10
CPU architecture: x86_64
Kernel: linux 5.3.0-24-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.4

**Comment by onlykey** [comment]
@dhammel This may be related to https://github.com/trustcrypto/OnlyKey-Firmware/issues/98

We are still working on trying to reproduce this issue, I think it may be specific to Linux, any procedures to reproduce would be helpful. This is not an issue with KeepassXC so feel free to post over on the OnlyKey-Firmware repo. Once we are able to reproduce we would release a fix for this in the next OnlyKey firmware release.
