### ISSUE TITLE
Root directory always selected after unlocking db

### ISSUE THREAD

**Issue by jelle-k** [keepassxreboot/keepassxc#3969]
## Expected Behavior
After selecting sub-directory, then selecting entry and performing auto-type, KeepassXC is minimized. Eventually database is locked automatically.

After logging back into database, I expect sub-directory/entry to be selected.

## Current Behavior

After logging back into database home (parent) directory is selected.

## Possible Solution

Add _Remeber previously used entry_ in *Application Settings*

## Debug info

KeePassXC - 2.5.0
Operating system: Windows 10

**Comment by phoerious** [comment]
This is kind of working as expected. We completely erase the database from memory when we lock it. We'd have to store the selection somewhere.
