### ISSUE TITLE
Can't auto type when child window have title(Tencent TIM can't autotype password)

### ISSUE THREAD

**Issue by plusls** [keepassxreboot/keepassxc#3972]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
The program which i used is TIM
[Download Link](https://office.qq.com/download.html)
![image](https://user-images.githubusercontent.com/23459592/70129143-2e505980-16b9-11ea-8111-9eb127775d0b.png)
When I press autotype hotkey, I hope keepassxc will input username and password.
My autotype config is 
```
^{BACKSPACE}{USERNAME}{TAB}{PASSWORD}{ENTER}
```
window title is **TIM**

## Current Behavior
[NOTE]: # ( Tell us what actually happens )
Keepassxc only input my username, and type key {TAB}, do not input my password.

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )
I use AutoHotkey to see what happened, I use it `#InstallKeybdHook`, and view key history, keepassxc only type my username and type key {TAB}, do not input my password.
![image](https://user-images.githubusercontent.com/23459592/70129795-5e4c2c80-16ba-11ea-8a8a-8610ae8a618d.png)

And I press autotype hotkey when i click password window, keepassxc tell me password textbox title is **QQEdit**
![image](https://user-images.githubusercontent.com/23459592/70129987-ae2af380-16ba-11ea-9bc8-632a38b50caf.png)

And I use spy++ to see window title detail.
![image](https://user-images.githubusercontent.com/23459592/70130436-84be9780-16bb-11ea-8165-cdca6ec38d9f.png)

I found that QQEdit is a child window of TIM
![image](https://user-images.githubusercontent.com/23459592/70130532-ad469180-16bb-11ea-9933-57a6b2e6d2a1.png)

I guess because password textbox have title, when keepassxc type key {TAB}, it found now window's title is not **TIM**, and stop autotype.

I hope although the current window has not empty title,  keepassxc can try to get parent window's title.If parent window's title is same with the title in config, keepassxc will continue autotype.

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1. open tim
2. press autotype hotkey
3. you will find that keepassxc only input username

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION
Revision: REVISION

Libraries:
- LIBS

Operating system: WIndows 10
CPU architecture: amd64
Kernel: KERNEL

Enabled extensions:
- EXTENSIONS

**Comment by droidmonkey** [comment]
If you press tab manually from the username field does it select the password field or some other element? It looks like there are a bunch of elements on that dialog. You might have to issues two `{TAB}` in order to select the password field before typing. You might also need to add a delay `{DELAY 50}` after the tab.

**Comment by plusls** [comment]
it select the password filed when i press tab manually from the username field.

**Comment by plusls** [comment]
And i try to add delay 50, but it still do not input my password.
`{USERNAME}{TAB}{Delay 50}{PASSWORD}{ENTER}`

**Comment by droidmonkey** [comment]
Unfortunately there is nothing we can do about a bad UI from another program. You will just have to define two Auto-Type patterns, one for the username and one for the password.
