### ISSUE TITLE
Attempt to reduce size of Windows deployment

### ISSUE THREAD

**Issue by zb-z** [keepassxreboot/keepassxc#3973]
KeePassX was already very large but this now is godzilla (about 100 MB on Windows).
How about going carefully through files, dependencies, maybe some config (if there's any) and deciding what's really, really needed for this particular utility - not some "general of general QT app"?  

For  a start I'm pretty sure you don't need libicudt64.dll at or ICU-direct anything. As far as I remember Qt maintains its own localization subsystem which knows how to interface with native OS services (Win and Mac in particular) with a fallback to ICU libs on Linux.

Does anyone really need keepassxc-cli.exe ? With the same size as the GUI binary ? It should have zero dependencies on Qt, no "localization" fancies and be the minimalist of the minimalist binary if someone really needs it.

Why does it carry it's own ssl lib? It should be figuring out and using whatever client a guy is already using on his box. The whole point of KeyPass is to be small and use what's already on the system. Otherwise you might as well ship a Docker image :-) Seriously. NGNIX runner costs 3MB, node.exe costs 28 MB, LSA (RAID manager UI) costs 60 MB (and runs NGNIX, under Windows :-) Compare with a tiny little app like KeyPass.

Bitwarden actually DOES have a Docker image :-))) Here: https://github.com/bitwarden/server#deploy Which you don't really need - that was just their way of proving a point - if you really don't want that free vault account, you can run your own without having to build anything.

**Comment by droidmonkey** [comment]
Go ahead and delete some of the libraries you mentioned in your install and see if the application keeps working. If it does not, then please close this issue.
