### ISSUE TITLE
Neo2 Layer 3 does not work in version 2.3.4 on macOS Mojave (QT BUG)

### ISSUE THREAD

**Issue by mauricemeyer** [keepassxreboot/keepassxc#3976]
I’m using [Neo2](https://neo-layout.org/) with [Karabiner Elements](https://github.com/pqrs-org/Karabiner-Elements) on macOS Mojave (10.14.6 (18G103))

When I type in the master password to any kdbx database with the password hidden, layer 3 (where most of the special characters are) of Neo2 does not work.

Once I click the eye to make the password visible, layer 3 does work.

I’m at a complete loss for why this could be happening and have no idea how to debug it. Any hints are very welcome.

**Comment by droidmonkey** [comment]
We don't provide any support for that specific keyboard. Also v2.3.4 is VERY out of date. Update to v2.5.1.

**Comment by jascosius** [comment]
It's still the same issue with macOS Catalina and KeePassXC v2.5.1. It would be wonderful if someone could spent the time to fix this.

**Comment by droidmonkey** [comment]
You are going to have to take this to the Qt bug board, we aren't imposing any specific limitations on our password edit fields.
