### ISSUE TITLE
Downloading favicon fails even though favicon exists on websites

### ISSUE THREAD

**Issue by txtsd** [keepassxreboot/keepassxc#3977]
## Expected Behavior
The websites show a favicon in a browser, so KeepassXC should be able to correctly fetch the favicons.

## Current Behavior
Fails with no reasons.
![2019-12-05-094821_457x367_scrot](https://user-images.githubusercontent.com/768728/70203956-c21b3780-1744-11ea-9115-fc0bbe2fa106.png)
Fails for this list of URLs:
- https://www.androidfilehost.com/user/?w=login
- http://careers.cisce.org/eCareersPublicClient/Web
- https://digitizeindia.gov.in/signin
- https://www.warframe.com/

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )

## Steps to Reproduce
1. Make an entry in KeepassXC with the URL `https://www.androidfilehost.com/user/?w=login`
2. Save the entry, rightclick on it, and hit `Download favicon`
3. It fails.

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.5.1
Revision: 0fd8836

Qt 5.13.2
Debugging mode is disabled.

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 5.4.1-2-ck-zen

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.5

**Comment by X4** [comment]
Same on windows 10

**Comment by drone540** [comment]
I found this issue on another URL in particular.

https://id.sonyentertainmentnetwork.com

In version 2.4.3 it gave an actual error screen about unable to access memory location. But 2.5.1 just says unable to fetch icon.

**Comment by StellarisStudio** [comment]
For me doing that corrected the issue :
Go to Tool>Setting>Security and enable "Use DuckDuckGo to download favicon" !!!

**Comment by stdedos** [comment]
Could it be related to https://github.com/keepassxreboot/keepassxc/pull/2996#issuecomment-579498487?

At least for androidfilehost.com/user/?w=login, icon is here, https://androidfilehost.com/assets/favicon/favicon.ico not where it's expected to be found

**Comment by droidmonkey** [comment]
If the favicon is not in the root folder then we will not find it

**Comment by stdedos** [comment]
I thought the purpose of DuckDuckGo was privacy.

In any case: I understand "why" you don't want to play that game. However, parsing `<link rel="shortcut icon" type="image/x-icon" href="../img/favicon.ico">` as a fallback to DuckDuckGo and `/favicon.ico` doesn't sound so awful.

I mean it wouldn't have helped in my case (TPLink is hopeless anyway), but on the above url it would have.

**Comment by droidmonkey** [comment]
Privacy when compared to the Google service.

**Comment by droidmonkey** [comment]
I'm closing this because it seems like there was an expectation from the OP that will not be met.

**Comment by txtsd** [comment]
@droidmonkey `Use DuckDuckGo service to download website icons` is already selected for me and it still doesn't work.

**Comment by droidmonkey** [comment]
Then there is nothing else we can do. You will have to download the icon manually and load it in. Sorry about that!

**Comment by droidmonkey** [comment]
Here are the icons you need:

https://androidfilehost.com/assets/favicon/favicon-160.png
https://careers.cisce.org/eCareersPublicClient/Web/Content/image/favicon.ico
http://n9e5v4d8.ssl.hwcdn.net/images/warframe/favicon.ico

**Comment by txtsd** [comment]
> Then there is nothing else we can do. You will have to download the icon manually and load it in. Sorry about that!

Gotcha. Manual it is.

**Comment by lyallp** [comment]
Tried to update Twitter favicon, can't.
KeepPassXC says icon already exists.
No matter what I did, I could not update to the new X icon, from the old bird icon.

**Comment by droidmonkey** [comment]
That means X hasn't actually updated their favicon.ico or the new icon hasn't landed on duckduckgo service yet. Patience.

**Comment by Nightfish88** [comment]
Can you please reffer to DuckDuck icon service, I'm trying to make a project, and seems the best way to fetch icon is using Duck.
But I'can't find info on how to add them to my script

**Comment by lyallp** [comment]
Instead of selecting a group of entries and downloading the icons for the group, I had to individually select the entry I wanted to download the icon for.
It would be nice if 'download all icons' did just that, rather than me having to search for sites, individually.
