### ISSUE TITLE
Keepasssxc -  Login DataBase Fields are all mixed up.

### ISSUE THREAD

**Issue by David205u** [keepassxreboot/keepassxc#3978]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
The Login DataBase Fields should be sequence - in there proper place. 

## Current Behavior
[NOTE]: # ( Tell us what actually happens )
The Login DataDase Fields are not in sequential order according to how you would normally login to a web site **URL** > ** USER NAME** > PASSWORD.

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )
Don`t know the actual cause but a possible solution would be a feature to reorder the fields in there proper order.

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1.
2.
3.

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )
Switching from Windows over to Linux Mint but have used windows for 20+ years and all passwords are in RoboForm & finding something to replace it is very difficult as none i have tried worked correctly according to description. Something simple and easy like RoboForm would be best as i never had a problem with it, linux programs are still buggy even though they should work as planned. This is the reason for the hold up in switching over to linux. 
I tried to include a image but it would not attach so i will describe it.
The user name field is displaying the URL to go to "www.mysite.com"
The password is being displayed in the user name used to login.
The URL is displaying the site password used to login.
Everything is backwards.

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION
Revision: REVISION

Libraries:
- LIBS

Operating system: OS
CPU architecture: ARCH
Kernel: KERNEL

Enabled extensions:
- EXTENSIONS

**Comment by droidmonkey** [comment]
How did you import the information in to KeePassXC?

**Comment by David205u** [comment]
From a CSV file from RoboForm KP will accept manual imputs and formatt correctly but not when using a CSV file.

**Comment by David205u** [comment]
Also the browser app does not function either it wont auto login & has difficulity connecting to the data base 99.9+% of the time.

**Comment by David205u** [comment]
If you want a image i could upload to a file download site as i can`t get it done here.

**Comment by droidmonkey** [comment]
When you import the CSV you need to assign the right columns to the fields in the database. You must not have chosen correctly when you imported. The browser extension won't work when all your entry's URL's are not correct.

![image](https://user-images.githubusercontent.com/2809491/70293670-f9263300-17ae-11ea-857e-bbea608b656f.png)

**Comment by David205u** [comment]
I did it correctly as you described but after importing it assigned the data to the wrong columns, no settings were changed on my end it did it on it`s own. -> The browser add on does not work as described either even when i manually entered the login data to a specific site & 99.9% of the time it wont connect to the data base. What i`ll do is upload to a file download and you can download if you want to -Or- I can send you me email for direct contact that way i can send you inline images. Let me know what you want to do if at all.
Ps. The import csv file is from RoboForm on a Windows PC the file looks like this RfExport below it say`s export.csv would this make a difference ?

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by droidmonkey** [comment]
Can you create a sample database in roboform and export to CSV? I do not want your actual database.

**Comment by David205u** [comment]
Yes, that`s what i did RoboForm does have a export feature in both csv and html. I wanted to send you images of the error not my data base. I can black out anything  so no problem there. If you want to use a temp email thats ok also or direct contact or file download if you want to, you decide. I just thought it would be easier to visualize what going on.
And thank`s for your concern also, my pleasure.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by droidmonkey** [comment]
Please send to team@keepassxc.org
