### ISSUE TITLE
Option to minimize to tray when manually locking database

### ISSUE THREAD

**Issue by jmbreuer** [keepassxreboot/keepassxc#3979]
## Summary
Introduce a settings option to minimize (to tray) when clicking the padlock in the main window - sort of a pendant to the existing "lock on minimizing" option.

## Context
I like to frequently minimize/restore the main window to have it out of the way, while working with systems where I frequently need credentials so I still like KeePassXC at the tip of my fingers.

When I end such an activity, I click on the padlock icon to lock the database. Since now there's no point to the UI taking up screen space any more, I'd like an option for it to instantly also minimize to tray, so that I can bring it up from there to unlock it whenever I need it next.

**Comment by droidmonkey** [comment]
Duplicate request
