### ISSUE TITLE
Dedicated URL field takes precedence over additional URLs when using multiple Databases

### ISSUE THREAD

**Issue by koelle25** [keepassxreboot/keepassxc#3981]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Regardless of storing a websites address in the *main* `URL` field or the `Additional URL's` field/list all matching entries are offered through the browser plugin.

## Current Behavior
[NOTE]: # ( Tell us what actually happens )
I have two Databases open and some entries have credentials for the same website. In one of them, the websites address is saved in the *main* `URL` field, in the other the address is in the `Additional URL's` field/list (aka `KP2A_URL[_*]`).

Now when I go to this website the browser plugin only offers the entry where the address is in the **main** `URL` field. The **other** entry (where the address is in the `Additional URL's` field/list) is **not** offered.

The URLs in both entries are **exactly** the same (so specificity is not the issue here).

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )
*none yet*

## Steps to Reproduce
see *Current Behavior*

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.5.1
Revision: 0fd8836

Qt 5.9.5
Debugging mode is disabled.

Operating system: Linux Mint 19.2
CPU architecture: x86_64
Kernel: 4.15.0-70-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.1

**Comment by varjolintu** [comment]
"Search in all opened databases for matching credentials" is enabled from Browser Integration -> Advanced page? Works fine for me.

**Comment by koelle25** [comment]
Yes, this is enabled. It works when the same adress is either in the *main* `URL` field in both entries or in the `Additional URL's` field in both entries.
Only when in one entry the address is in the *main* field and in the other its in the *additional* field this problem occurs.

**Comment by varjolintu** [comment]
Did exactly that to test it. First DB had a single entry with the URL. Second DB had only one entry with the same URL only in the Additional URL's. Cannot reproduce it.

**Comment by droidmonkey** [comment]
You probably have one of the database with deny permission on that entry for that url to send it to the browser extension.

**Comment by koelle25** [comment]
I just did `Forget all site-specific settings on entries` for both databases (it actually deleted 23 respectively 11 entries of some kind) but the problem persists.

Then I tested with 2 completely new Databases and also a new Browser (Chromium) - same problem.

After stitching around in the different Browser Integration settings the culprit seems to be with the `Return only best-matching credentials` setting (Application settings > Browser Integration).
When this is enabled, I only get the *main* URL entry. After disabling it, I also get the one with the *additional* URL.
**Problem** is: Then I also get all entries for any other subdomain. In my case I have in the desired entries the address `https://sub.example.com` but I also get e.g. `https://foo.example.com`.

**Comment by varjolintu** [comment]
@koelle25 The subdomain bug is already known and fixed for KeePassXC 2.5.2.

Good to know that certain option causes the behaviour. We need to fix it to include also the Additional URL entries.

**Comment by koelle25** [comment]
Oh yeah, when building KeepassXC from the [release/2.5.2](https://github.com/keepassxreboot/keepassxc/tree/release/2.5.2) branch (including e2c95f75f1869f86181eeecbec3458c5cd325f85) it work's as it should when disabling the `Return only best-matching credentials` setting.

The only question left is: Is this setting still useful? I know it was useful prior to the "Additional URLs" feature (the reason why I have/had it enabled) but in the current state it leads to the behaviour discussed above.
Maybe it would be useful to rename it (and obviously fix the behaviour) to `Check full URL (instead of domain only)`?

**Comment by varjolintu** [comment]
@koelle25 I agree. The setting would be much more useful with that kind of option.

**Comment by varjolintu** [comment]
@koelle25 I tried to fix this but when enabling `Return only best-matching credentials` the entry with only Additional URL still returns normally. So I cannot reproduce this at all. I'm using the current `release/2.5.2` branch for testing this so I'd suggest you try a snapshot build and see if it still happens.
