### ISSUE TITLE
Allow Longer TOTP Secret Keys

### ISSUE THREAD

**Issue by trymeouteh** [keepassxreboot/keepassxc#3982]
I have some websites which provider a long TOTP secret key such as 52 characters long. I am able to add these longer TOTP secret keys into apps such as andOTP but they do not work in KeePassXC and I get this error.

> You have entered an invalid secret key. The key must be in Base32 format.
> Example: JBSWY3DPEHPK3PXP

Please allow us to enter more formats and longer TOTP secret keys.

**Comment by droidmonkey** [comment]
Upgrade to 2.5.1
