### ISSUE TITLE
Remove icon (single and bulk)

### ISSUE THREAD

**Issue by metbril** [keepassxreboot/keepassxc#3983]
# Summary
My database is large and takes longer and longer to sync and open.

Just like downloading a favicon for a single item or all selected items, I would like to have the option to remove an icon.

### Edit entry window

In the entry screen, you can already go to icon and there remove the icon, no change required

### Entry list

In the entry list right clicking a single row or a selection should show an extra option, for example directly below Download favicon "Remove icon".

## Possible Solution
[NOTE]: # ( Not required, but suggest ideas on how to implement the addition or change )

See above.

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )

Large database, long syncs, long opening.

**Comment by metbril** [comment]
Loosely related to #2110 and/or #1950.

**Comment by droidmonkey** [comment]
If you just delete the custom icons within ONE entry it will delete them across your database. There is no need to do remove icon for each entry.

**Comment by droidmonkey** [comment]
I recommend just deleting all your custom icons then redownloading them by right clicking the root group then download icons. We only store a 128x128 icon image.

**Comment by metbril** [comment]
I have a large database (>6MB) with 600+ icons and need to delete those 1 by 1. Deleting all custom icons is taking a very long time. Just like downloading each individual favicon which does have a bulk option. What I still like is, to be able to:

1. remove icons from all entries (replace by default 'key' icon) and
2. be able to purge all unused favicons

The former is this request. 
The latter already has a feature request #1950 for it. 

This should shrink the database significantly. 

Hope you reconsider reopening the request.

**Comment by droidmonkey** [comment]
The former is covered by #2110 since I intend to make it possible to multi-select icons in the UI

**Comment by metbril** [comment]
I hope this will be implemented soon. 

For my purpose I manually deleted all 600+ icons (just like you suggested) for ~650 logins. The database is now 83 KB and opening and syncing fast... 😄

**Comment by droidmonkey** [comment]
Hell yah, good to hear it
