### ISSUE TITLE
Are there any updates for Fedora 31?

### ISSUE THREAD

**Issue by xzj8b3** [keepassxreboot/keepassxc#3984]
Are there any updates to solve problems with Wayland and torbrowser-launcer where extension in both cases just didn't work?

It's definitely a bit uncomfortable to use on such a desktop or browser for those who use Fedora and have recently chosen to rely on this extension!!!!!

**Comment by droidmonkey** [comment]
You already have an open issue for Fedora. We do not control that distribution, if there are issues with packages or whatever that needs to be addressed with the maintainer. We also do not fully support Wayland.

**Comment by xzj8b3** [comment]
> You already have an open issue for Fedora. We do not control that distribution, if there are issues with packages or whatever that needs to be addressed with the maintainer. We also do not fully support Wayland.

Yes I understand, I will return to Lastpass because services provided by this extension are really scarce!!!!!

**Comment by xzj8b3** [comment]
> You already have an open issue for Fedora. We do not control that distribution, if there are issues with packages or whatever that needs to be addressed with the maintainer. We also do not fully support Wayland.

Sorry but Fedora Magazine advised your service and maybe I overestimated the thing, Wayland is more than usable already from Fedora 29 seems to me but it is clear receive constant upgrades

I opened a second issue because after several requests in the previous one I was not even given confirmation as per request if the data provided later were necessary to identify the problem in question!!!

I was interested in seeing the efficiency of the service as I was looking for something reliable!!!
