### ISSUE TITLE
Database write issues when database is on an automounted device

### ISSUE THREAD

**Issue by ckastner** [keepassxreboot/keepassxc#3985]
On a Debian 10 system with KeePassXC 2.4.3, I'm seeing two kinds of problems when the database is on an automounted device:
  1. When adding a new entry, after confirming with [OK], the entry is sometimes not added to the group (and no change of database is detected, "Save" remains inactive)
  2. The entry is added after confirming with [OK], but then a "Merge request" dialog pops up (because the underlying database has changed).

I can see that systemd.automount is repeatedly mounting and unmounting the device.

If I force the directory to remain mounted (eg by opening the directory in a file browser), the issue disappears.

I'm guessing that KeePassXC reads the database in its entirety upon startup, then closes it again, only to open it again when a writeout needs to happen, all while periodically checking whether the underlying file has changed?

Here is an example fstab entry:
`UUID=xxx   /media/foo ext4  noauto,x-systemd.automount,x-systemd.idle-timeout=3  0   0              `

## Possible Solution

An option to force the database (or even just the underlying directory) to remain in use would be nice.

## Debug Info
KeePassXC - Version 2.4.3
Revision: 5d6ef0c

Qt 5.11.3
Debugging mode is disabled.

Operating system: Debian GNU/Linux 10 (buster)
CPU architecture: x86_64
Kernel: linux 5.3.0-0.bpo.2-amd64

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (only unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.4

**Comment by droidmonkey** [comment]
Upgrade to 2.5.1 and you'll be all set.

**Comment by ckastner** [comment]
Apologies for the late reply, I didn't get around to testing the newest version back then.

2.5.4 was released as a backport in Debian recently, and I just wanted to confirm that it indeed fixed the issue.

Thanks!
