### ISSUE TITLE
Have search function include additional text fields in search [enhancement]

### ISSUE THREAD

**Issue by brad2014** [keepassxreboot/keepassxc#3987]
It seems I cannot search by password. So if I may, an idea for making search/find more useful:

- Implement a global security option *"Include protected fields in search"* that causes the search operation to scan protected attribute values and all passwords in search. It is *off* by default.

- **Passwords:** When the global security option is enabled, or when the password column is active and unhidden, the search operation should scan the content of the password fields for matches.

This allows me, for example, to search for a "compromised" password, and find all my accounts that have that password, to change them. 

- **Additional Attributes:** The search function scans "additional attributes", both keys and non-protected values. If the global security option is enabled, it also scans protected values.

For example, if an entry has a pair like this (which is used by the android app Keepass2Android for recording additonal URL's for its autofill):
```
KP2A_URL_1: "androidapp://com.tripit"
```
then I can search for "KP2A_URL" or for "androidapp" to find such an entry.  I'd also be able to search for "otp" to find all the entries that have otp set up (super useful if I lose my yubikey and want to either reload it, or get the list of accounts for which TOTP needs to be revoked and re-enabled).

**Comment by droidmonkey** [comment]
You absolutely can search by password. `pass:[insert text here]`

You can also search by attribute as well.
