### ISSUE TITLE
Support 58 char TOTP seeds

### ISSUE THREAD

**Issue by Lantizia** [keepassxreboot/keepassxc#3988]
In the UK we're able to use various GOV.UK-related websites... each site is a government department that are slowly being merged into one big website (or made to look that way anyway).  For years now there has been (sadly the bloody Tories seem intent on dismantling and outsourcing instead) a "Government Gateway" type of account which allows you to login to various government department websites that accept it.

One of the departments/sites accepting GG accounts is HMRC (Her Majesty's Revenue & Customs, for you non-brits!) which additionally let to use TOTP as well (but just on their website), the seed length was 16 characters... and these codes still work.

However I noticed when I logged in today... it told me that my existing 2FA could now be used on all department websites that also accept GG accounts, hurrah!  After logging in I looked at the settings and found the existing 2FA setup listed as "HMRC App" -- An odd name to use as there was never an "App"... if anything they just recommended "Google Authenticator" back then.

I thought to check what occurred if you were a new user setting up 2FA for the first time now (as though you'd never used the HMRC version)... and it gave this otpauth:// URL...  (obviously I've not used this seed, it's safe to post here)

`QR-Code:otpauth://totp/Government%20Gateway:Joe+Smith?secret=GEZDSNBSMJRGILLFGFTDOLJUGRTDILJZGEZDMLLCME2GGZLEHAYDKOLGME&digits=6&issuer=Government%20Gateway&algorithm=SHA1&period=30`

This is 58 characters long instead of 16 or 32.

What I find curious though is that this new 2FA setup talks of you simply searching for any old authenticator app on your phones app store - no one particular recommendation (e.g. Google Authenticator) or specific proprietary app to use.

But KeePassXC just throws out...
![image](https://user-images.githubusercontent.com/10448369/70389079-75d52f00-19b2-11ea-9904-e379fdc8a3b0.png)

Is this an easy fix to allow 58 characters?  Could other websites be using even longer seeds?

**Comment by droidmonkey** [comment]
What version of KeePassXC are you using

**Comment by Lantizia** [comment]
:)

All my machines are on 2.5.1, except for this bloody one! (which was on 2.5.0)

Just upgraded, works fine now... out of curiosity what was changed to make it work, just an maximum length type of deal or something else?

**Comment by droidmonkey** [comment]
It was a parsing error to determine if the key was valid or not.
