### ISSUE TITLE
Autotype Inputs Incorrect

### ISSUE THREAD

**Issue by altayevrim** [keepassxreboot/keepassxc#3989]
# Autotype started to work incorrectly.

## Expected Behavior
I am selecting the entry as usual. And using CTRL + V shortcut. It should go to the previously used windows (usually my browser). And perform autotype.

## Current Behavior
I am selecting the entry as usual. And using CTRL + V shortcut. It is going to the previously used windows (usually my browser). It waits a bit, longer than usual. And my CPU usage increases a lot for 2 seconds. Then It just sends bunch of strings like that. And It presses ENTER, and of course wrong credentials. 

rrrrrrrrrrrrrrrr7rrr    rrrrr%é5rrr&4rrrrrrr

## Possible Solution
I don't know why that happens. But I think it encounters some problem but still tries to write the data.

## Steps to Reproduce
I am using the KeePassXC on my Ubuntu 18.04.3 LTS
Intel® Core™ i5-6200U CPU @ 2.30GHz × 4 - 64Bit

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )

## Debug Info
KeePassXC - Version 2.3.1
Revision: 2fcaeea

Libraries:
- Qt 5.9.5
- libgcrypt 1.8.1

Operating system: Ubuntu 18.04.3 LTS
CPU architecture: x86_64
Kernel: linux 4.15.0-70-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by droidmonkey** [comment]
You are VERY outdated, update to 2.5.1

**Comment by altayevrim** [comment]
Yeah updated but still the same result.
rrrrrrr?rrrrrrrrrr=rr/r^(rrrrrrrrrr)

**Comment by droidmonkey** [comment]
Are you using different keyboard layouts or languages? If so then this is already a known issue.

**Comment by altayevrim** [comment]
Yeah I was actually. But didn't see the issue. Then this one can be closed. Thanks. I removed the other language and now it works.
