### ISSUE TITLE
Add option to ignore external database modifications

### ISSUE THREAD

**Issue by quinncomendant** [keepassxreboot/keepassxc#3994]
## Summary
Currently, the only option for watching for external database modifications is, *“Automatically reload the database when modified externally.”* If this option is unchecked, a dialog will pop-up every time the database is modified, *“The database file has changed. Do you want to load the changes?”* On some cloud sharing services, this happens every time the file is accessed, even if it is not modified). This can be really annoying if the dialog appears multiple times per day.

## Desired Behavior
If you never want to receive external modifications, there should be an option to *always ignore externally modified database*, so this dialog is never displayed.

## Possible Solution
I suggest changing the *“Automatically reload the database when modified externally?”* option, replacing the checkbox with three radio buttons:

    If the database is modified externally:
      (_) Automatically reload the database
      (_) Ignore modifications
      (_) Ask every time

## Context
I only care about one-way sync, I only want to make changes to the database in KeePassXC. I know if my database is closed and modified externally, those changes can't be ignored, but in my case the changes are only the modification timestamp, so I don't want KeePassXC to do anything in response to changes.

**Comment by droidmonkey** [comment]
We can still check for changes in the file right before save and prompt to merge them. This wasn't possible prior to 2.5.

**Comment by quinncomendant** [comment]
Related issue: it would be helpful if KeePassXC didn't duplicate dialogs: today I had about 25 of *“The database file has changed.”* dialogs stacked on top of each other, and had to click "No" on each to dismiss them all.

<img width="598" alt="Screen Shot 2019-12-10 at 17 05 00" src="https://user-images.githubusercontent.com/6884276/70580864-dadb8100-1b7a-11ea-80bc-3ea35457fdb7.png">

**Comment by droidmonkey** [comment]
I have figured out the cause of the duplicated notices.

**Comment by droidmonkey** [comment]
This feature is no longer necessary with 2.6.0, sync and merge "just works" now.
