### ISSUE TITLE
Auto Type option doesn't do anything.

### ISSUE THREAD

**Issue by bram1253** [keepassxreboot/keepassxc#3997]
## Expected Behavior
I believe that if you disable auto type for a folder of accounts then those accounts shouldn't show up anymore in the drop down list when clicking an input field.

## Current Behavior
The Auto-Type option doesn't seem to do anything. However if you disable the Search option then the accounts will no longer show up in the drop down.

## Steps to Reproduce
0. Make sure you have browser integration set up.
1. Right click on your root folder.
2. Click "Edit group"
3. Change Auto-Type to "Disable"
4. Go to any web page where you normally are able to simply select your account when you click on the input field
5. Watch all of the accounts still appear in the drop down and when clicking on any of them watch auto-type function even though it's disabled.

## Context
I have a lot of old or alt accounts for websites and wish to store them in a folder I can search for but it doesn't show up in my auto type list.

## Debug Info
KeePassXC - 2.5.1
Revision: 0fd8836

Libraries:
- Qt 5.13.1

Operating system: Windows 10
CPU architecture: intel 64 bit
Kernel: NT

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

**Comment by droidmonkey** [comment]
Auto-Type is an entirely different feature from browser integration. You want to go to the browser integration tab of the entries you don't want to be accessible and disable it there.
