### ISSUE TITLE
Add a browser integration tab in folders

### ISSUE THREAD

**Issue by bram1253** [keepassxreboot/keepassxc#3998]
## Summary
Instead of having to go through each entry one by one to edit it's browser integration settings we should be able to change it directly from the folder. Mainly the "Skip Auto-Submit for this entry" and the "Hide this entry from the browser extension" options.

## Context
I have a lot of old or alt accounts for websites and wish to store them in a folder named "alt accounts" where they don't all show up when clicking on the login field. Currently you can do this by disabling the Search field of the folder, but I'd still like to be able to search through my old accounts for when the occasion is there and I need to check my old email account for example.

**Comment by droidmonkey** [comment]
This is a good idea

**Comment by varjolintu** [comment]
The problem here is when receiving the state of the options. Meaning: what the state is if there's for example 5 entries with an option enabled but with two of those the same option is disabled?

**Comment by droidmonkey** [comment]
The group setting would effectively cancel all entry settings. You could gray out the browser integration tab of the entry in such a group with a note that says "This entry is in a group that has disabled browser integration".

**Comment by varjolintu** [comment]
@droidmonkey This is what my code is doing right now: overwriting the settings for all entries in the group and subgroups.

The problem I meant can be reproduced like this:
- Have a group with three entries
- Enable the group setting for not showing the entries to the Browser Integration
- Edit one or multiple entries using edit entry widget and disable that setting
- The group setting will still show the option enabled. There's no way to get the reliable state for the option.

**Comment by droidmonkey** [comment]
I'm confused by the sequence, sorry. Are you saying that when editing an entry's options it should impact the parent group's setting as well?

**Comment by varjolintu** [comment]
Argh. What I'm trying to say is that when you open the Group Edit widget, those Browser Integration settings will have to have some state (meaning enabled/disabled in this case). Now you can enable one of those options inside a group (in my test branch), but you can still manually disable those options via Edit Entry widget, and the Group Edit would still show the same option enabled, no matter what the entry options actually are.

So the state of the checkbox displayed in Group Edit widget can be totally false.

**Comment by bram1253** [comment]
@varjolintu I believe a checkbox has a state specifically for that.
![image](https://user-images.githubusercontent.com/6538678/71546382-95022380-2996-11ea-9ad8-e35fe18a16fc.png)
If there are conflicting settings just set the checkbox to an indeterminate state.

**Comment by varjolintu** [comment]
@bram1253 I was talking about a plain QCheckBox class. The settings page would be similar to Edit Entry view, but in the Group Edit page listing. Or are you suggesting something else entirely?

**Comment by bram1253** [comment]
@varjolintu No, I'm just replying to the following.
> The problem here is when receiving the state of the options. Meaning: what the state is if there's for example 5 entries with an option enabled but with two of those the same option is disabled?

Well if it does, just set the checkbox to an indeterminate state so that the user knows that whenever he clicks on it, he'll be overwriting conflicting settings.

**Comment by varjolintu** [comment]
I'm not sure if that's possible with QCheckBox.

**Comment by bram1253** [comment]
I'm not that familiar with QT but I looked at their docs and while it doesn't seem like it's documented in detail, it does have a `tristate` boolean property to determine whether a checkbox has three states.

**Comment by varjolintu** [comment]
Ah, true! https://doc.qt.io/qt-5/qt.html#CheckState-enum
