### ISSUE TITLE
OPVault importer uses legacy attribute for TOTP secrets

### ISSUE THREAD

**Issue by dne** [keepassxreboot/keepassxc#3999]
## Expected Behavior
TOTP secrets (i.e. "otpauth" URIs) in 1Password/OPVault items should be converted to the "otp" attribute in KeePass format, that e.g. KeePassXC's own TOTP setup dialog uses.

## Current Behavior
TOTP secrets are converted to the legacy(?) "TOTP Settings" attribute.

## Possible Solution
Change the OPVault import code to use the "otp" attribute for otpauth URIs.

## Steps to Reproduce
1. Import OPVault data with TOTP secrets.
2. Inspect attributes of imported entries with TOTP secrets.

## Context
The legacy "TOTP Settings" attribute appears to be enough for KeePassXC to generate TOTP codes, but the Strongbox iOS app would not – I believe it also expects a "TOTP Seed" attribute in this case, which the importer doesn't add. The problem was resolved by simply renaming the attribute to "otp".

## Debug Info
KeePassXC - Version 2.5.1
Revision: 0fd8836

Qt 5.13.1
Debugging mode is disabled.

Operating system: macOS Mojave (10.14)
CPU architecture: x86_64
Kernel: darwin 18.7.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
 libgcrypt 1.8.5

**Comment by droidmonkey** [comment]
It sure does! Good find
