### ISSUE TITLE
USB/Removable Drive Access

### ISSUE THREAD

**Issue by Huxly72** [keepassxreboot/keepassxc#400]
i feel like i am just missing something really obvious here...but i cant seem to find it :(

## Expected Behavior
Open a db or key file from an external removable usb drive

## Current Behavior
When i try to open a db for key file from a usb drive, i cannot see the drive, i am restricted to my home folder only.  

## Steps to Reproduce (for bugs)
1. Attach usb drive with key file on it
2. start keepassxc
3. Click 'browse' (for key file)
4. Cannot see the usb drive that is mounted in /media/username/

## Context
Cannot open db file or key file

## Your Environment

* KeePassXC version/commit used: 2.1.3
* Qt version (e.g. Qt 5.3): 5.6.1
* Compiler (e.g. Clang++3.6.0): snap 2.23.1
* Operating System and version: Ubuntu 16.04 LTS 64bit 
* Other 
    * my home folder is encrypted (using built in ubuntu feature)
    * i see that snap has a removable-media interface now, but it doesnt seem to be available as a plug for keepassxc

**Comment by phoerious** [comment]
Try our AppImage and see if it works. Snap packages have dedicated permission management and you might not have the needed permissions to access USB drives.

**Comment by Huxly72** [comment]
yes, it does work from the appimage.  perhaps you could add the removable-media interface as a plug for the snap package in a future release?

https://github.com/snapcore/snapd/wiki/Interfaces#removable-media

**Comment by droidmonkey** [comment]
Ugh so many plugs....

**Comment by colinl** [comment]
This also affects permanently mounted network drives, not just removable USB drives.

**Comment by droidmonkey** [comment]
I'm just going to inject this into the current 2.1.4 release so that we get it up and running.

**Comment by droidmonkey** [comment]
OK, the snap has been updated in the store to include the removable-media plug. Since it is NOT auto connected, you have to manually execute the following command after installation to use it:

```sudo snap connect keepassxc:removable-media :removable-media```

Based on my limited testing it also appears that you need to manually type in ```/media``` into the filename entry of the open file window to actually see the drive...

**Comment by hummeling** [comment]
Hi there,
Not sure if my issue is related to this issue, but I can't open any KDBX files on mounted drives in Ubuntu 18.04.01 LTS. I'm trying to open a file on an NFS share somewhere under /mnt. The Permissions button of Ubuntu Software shows a dialog with three op/off-options, which can be modified but aren't retained after closing and reopening the dialog.
Version is 2.3.4.

Kind regards,
Ralph Hummeling

**Comment by droidmonkey** [comment]
Did you connect the plug like I mentioned above?

**Comment by hummeling** [comment]
Yes, I did, at no avail.


⁣Sent from BlueMail ​

**Comment by droidmonkey** [comment]
I cannot reproduce this on 18.04. Following the steps to connect the removable-media plug worked flawlessly. You do have to restart KeePassXC for the plug to work.

**Comment by hummeling** [comment]
The snap is installed via Ubuntu Software, the database I'm trying to open is on my NAS, mounted during startup. The mountpoint is /mnt, as copied from online examples. Didn't encounter any issues with that before.

**Comment by droidmonkey** [comment]
@hummeling please read this: https://docs.snapcraft.io/reference/confinement

**Comment by hummeling** [comment]
@droidmonkey understood, it's clearly a safety measure. Nonetheless, the user should be notified with some explanation why the app isn't able to access that location.
About the Permissions action in Ubuntu Software, is this beyond the control of this snap?

**Comment by droidmonkey** [comment]
This is largely a complete failure on Ubuntu's part to clearly articulate the limitations of snaps through the Ubuntu store. Even worse, they are not making snaps and ppa's available side-by-side in the store. This creates much confusion for end users. We already have this documented in our FAQ on our website.
