### ISSUE TITLE
Cannot save/save as when open for several weeks

### ISSUE THREAD

**Issue by ZaHyPyCa** [keepassxreboot/keepassxc#4000]
- Windows 10 LTSC Version 1809 (OS build 17763.557) x64.
- KeePassXC 2.5.1 porable with option auto save after every change.

Open & use DB long time (about 2 weeks) without shutdown/restart PC, only sleep.

I can create new entry, use auto type, copy username, password but the DB don't auto save. Click save button but don't work. Select save as, it show me location to save. Give another DB name, click OK but new DB don't appear. Only way is force close (end task) & reopen DB

**Comment by droidmonkey** [comment]
Unfortunately we don't have enough information here to understand whats going on. Where are you trying to save? Where is the portable instance running? Network drive, USB?

**Comment by ZaHyPyCa** [comment]
Hi droidmonkey,

Thanks for your reply. Let me make it clear:

- Portable KeePassXC run on internal HDD laptop.
- DB is on HDD too.
- Laptop runs from 7am - 3pm. It sleeps 30 minutues. Run from 3.30pm - 2am. Daily routine.
- After 2 - 3 weeks KeePassXC look like freeze save function.
- I can add new, edit entry but KeePassXC not auto save.
- Try to click save button. DB donot save.
- Try to save as. It show a box for chosing location to save as DB.
- Enter new DB name 7 click OK. Nothing happen. No new DB on disk.
- Click close button [x] on KeePassXC -> not work.
- Open task manager & end KeePassXC task -> process is closed.
- Open KeePassXC & DB again -> everything work fine (new, edit entry -> auto save work)
----------
- I run 6 portable KeePass Password Safe 2.43 instances with KeePassXC.
- 1 KeePass Password Safe opens 5 DB. Total is ~ 30 DB
- All DB are saved in local HDD.

**Comment by droidmonkey** [comment]
Hmmm that is interesting. I keep KeePassXC open for many weeks at a time on my laptop through sleep cycles and have not experienced this issue. If you can identify any other unique triggers please update it here. Otherwise my best advice is to restart KeePassXC every once in a while

**Comment by droidmonkey** [comment]
@ZaHyPyCa Still an issue?

**Comment by phoerious** [comment]
My work PC is always up and KeePassXC has been running there for months at a time. On my laptop it's been days and weeks throughout sleep cycles, depending on when updates force me to reboot. Never had a problem. But my DB also locks after 15 minutes or when closing the lid.
