### ISSUE TITLE
Selected unlocking password: CTRL+Backspace jumps to front instead of removing typed characters

### ISSUE THREAD

**Issue by LucaBernstein** [keepassxreboot/keepassxc#4001]
## Expected Behavior
The same behavior as with not selected password is expected: When hitting `CTRL+Backspace` while all characters are selected it is expected that all are removed.

## Current Behavior
At the moment the cursor jumps to the front of the characters (or bullets), the characters remain.

This could provide a potential security issue or be inconvenient if you want to remove all typed characters and begin anew.

## Possible Solution
Fix the jump: If all characters are selected and `[CTRL + ] Backspace` is hit, delete all selected characters.

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1. Open KeePassXC
2. Enter some characters
3. Select all by hitting `CRTL + A`
4. Hold down `CTRL` and press `Backspace`
5. Characters remain, cursor jumps to front, selection is removed.

## Context
For me this occurred when trying to remove the typed characters as I mistyped somewhere and wanted to start anew. While selecting everything with `CTRL+A` I still held the `CTRL`-key down (as the keyboard still registered it) and hit `backspace`. The password was not removed.

## Debug Info
KeePassXC - Version 2.5.0
Revision: 1ab8a9f

Qt 5.13.1
Debugging mode is disabled.

Operating system: Windows 10 (10.0)
CPU architecture: x86_64
Kernel: winnt 10.0.18362

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.5

**Comment by droidmonkey** [comment]
The only Windows program I can find that exhibits the Ctrl+Backspace behavior you define is notepad. Even in MS office the behavior is to do nothing. Either way this is not behavior we define, it is defined by Qt. This means we would have to explicitly override it in all text fields which is silly.

**Comment by droidmonkey** [comment]
See https://doc.qt.io/qt-5/qkeysequence.html#standard-shortcuts

Specifically "delete start of word" which is the default behavior for the shortcut you describe.
