### ISSUE TITLE
keepassxc browser integration breaks after upodate to FF71

### ISSUE THREAD

**Issue by robbosch** [keepassxreboot/keepassxc#4003]
This morning I had a browser update to FF71 on Fedora30
Since the browser update I have a problem with the browser intergration addon.
(translated) message by the Keepassxc-Browser addon:
An error has occurred in KeePassXC Browser: No connection with KeePassXC. Check in KeePassXC settings if browser integration is activated.

The browser integration is active for FF browser.

I am not 100% sure this is because of the browser update, but I noticed this behavior after the update. I already reinstalled both KeepassXC and the FF KeePassXC-Browser addon. Also reset the KeePassXC settings to default to rule out my own fckups.
Any investigations I can do to help getting around this problem?

**Comment by robbosch** [comment]
Probably related to: https://github.com/keepassxreboot/keepassxc-browser/issues/711

**Comment by varjolintu** [comment]
Duplicate of https://github.com/keepassxreboot/keepassxc-browser/issues/704
