### ISSUE TITLE
KeepassXC not providing Freedesktop.Secrets after lock/unlock of database.

### ISSUE THREAD

**Issue by chron-isch** [keepassxreboot/keepassxc#4004]
Uppon first opening an applications that tries to access the Freedesktop.Secrets service the user is asked to unlock his database with the following screen:
![Screenshot_10 12 19_13:59:15](https://user-images.githubusercontent.com/1332352/70537301-80cdc200-1b60-11ea-8964-637b4da437c7.png)
Password are accesible and everything works, but if you close the application, close the database and reopen the application (Remmina in this case) you are not asked to unlock the database again. Even after manually unlocking the database Remmina will not find any of it's stored secrets, you have to kill keepassxc and start from scratch.

The same behaviour can also be observed with `secret-tool` or `python-keyring`

## Expected Behavior
Ask to unlock the keyring again/resume freedesktop.secrets service after locking/unlocking the database .

## Steps to Reproduce
```
secret-tool store --label='Test' username testuser password testpassword
Password: Testpassword

#Keepassxc asks to unlock the database

libsecret-Message: 16:06:06.692: Remote error from secret service: org.freedesktop.Secret.Error.IsLocked: Error return with empty body:
secret-tool: Error return with empty body:

secret-tool store --label='Test' username testuser password testpassword
Password: Testpassword
# Works

secret-tool lookup username testuser
Testpassword
# Works

#Lock database

secret-tool lookup username testuser

#Not asked to unlock again
#Manually unlock database

 secret-tool lookup username testuser
# No secrets found...
```

## Context
I'm forced to leave my database constanly unlocked, can't even lock it when I close the session, gnome-keyring had no problem with locking the keyring and asking to reopen it.

## Debug Info
KeePassXC - Version 2.5.1
Revision: 0fd8836

Qt 5.13.2
Debugging mode is disabled.

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 5.4.2-arch1-1

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.5

**Comment by Aetf** [comment]
I can reproduce this locally. The `default` alias, as well as the currently unlocked collection, is not present on DBus.

This must be a regression since I last refactored the alias handling code.

**Comment by chron-isch** [comment]
@Aetf I just gave commit ec61a02c245d525e7ac8fc89ed8652b78d3cb54a a try and I can find secrets after unlocking now, but it still doesn't ask to unlock again, but I'm pretty sure you're aware of that. Thanks.

**Comment by Aetf** [comment]
@chron-isch Yes.

* `secret-tool search/lookup` doesn't work when the database is locked. The spec requires the database to be searchable even when locked, but that's not possible in KeePassXC.
* `secret-tool store` will work when the database is locked. It triggers the unlock dialog now. However, there's another bug I'm fixing that preventing the entry to be actually created after unlocking

**Comment by hadogenes** [comment]
@Aetf can keepasscx ask for password when search/lookup?
If we cannot follow the specs, so make it user friendly.
It is quite annoying that I cannot use remmina after screen lock (and keepasscx auto lock)
