### ISSUE TITLE
Windows 10 "memory could not be read error" 2.5.1

### ISSUE THREAD

**Issue by dpb657** [keepassxreboot/keepassxc#4005]
![keepassXC 2019-12-10 172006](https://user-images.githubusercontent.com/18661193/70578113-71f00b00-1b72-11ea-8309-6bf5cd1f517d.png)

I had left KeepassXC-2.5.1 open on my home PC. When I returned from work I saw the error above. I was using KeepassXC-2.5.1 on my Mac at work.

**Comment by kekukui** [comment]
@dpb657 - why close this? --the issue persists

![image](https://user-images.githubusercontent.com/20834957/72734006-fd43bf80-3b66-11ea-96b5-4b3031efc46c.png)

**Comment by droidmonkey** [comment]
This is likely fixed in 2.5.2

**Comment by kekukui** [comment]
@droidmonkey - this occurred on 2.5.2.  An update was offered for 2.5.3 but http://keepassxc.org/ appears offline.

**Comment by kekukui** [comment]
1.  The issue perists in 2.5.3

![image](https://user-images.githubusercontent.com/20834957/75111720-06fb8f80-560b-11ea-92ce-f4f4205bbc6f.png)

2.  The firewall at KeepassXC.org is silently blocking VPN proxies, so updates are not possible.
3.  I see multiple instances of `KeepassXC.exe` still running in task manager after I quit the app.
