### ISSUE TITLE
GUI test failed - Child aborted***Exception

### ISSUE THREAD

**Issue by HelixDeCube** [keepassxreboot/keepassxc#4006]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
testgui PASSED

## Current Behavior
[NOTE]: # ( Tell us what actually happens )
38/40 Test #38: testgui ..........................Child aborted***Exception:  25.19 sec
...
98% tests passed, 1 tests failed out of 40

Total Test time (real) = 112.24 sec

The following tests FAILED:
	 38 - testgui (Child aborted)
Errors while running CTest
make: *** [test] Error 8

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1. cmake -DCMAKE_OSX_ARCHITECTURES=x86_64 -DCMAKE_BUILD_TYPE=Release -DWITH_TESTS=ON -DWITH_GUI_TESTS=ON -DCMAKE_PREFIX_PATH=/usr/local/Cellar/qt/5.13.2/lib/cmake -DWITH_XC_ALL=ON ..
2. make -j8 package
3. make test

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )
GUI Test not passed

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.5.1
Revision: 0fd8836

Qt 5.13.2
Debugging mode is disabled.

Operating system: macOS 10.15
CPU architecture: x86_64
Kernel: darwin 19.0.0

Enabled extensions:
All extensions -DWITH_XC_ALL=ON

**Comment by droidmonkey** [comment]
Never seen that before. Are you running this within a gui environment?

**Comment by HelixDeCube** [comment]
Yes, I'm running it on Mac. Once it reach "testgui", many many windows
starts popup/close fine, so testgui seems to be able to pass number of it's
steps.
But once it reach such window(attached) it freezing for several seconds
then throw the error.

[image: image.png]

36/40 Test #36: testbrowser ......................   Passed    0.09 sec

      Start 37: testcli

37/40 Test #37: testcli ..........................   Passed    5.22 sec

      Start 38: testgui

38/40 Test #38: testgui ..........................Child aborted***Exception:
23.79 sec

      Start 39: testguipixmaps

39/40 Test #39: testguipixmaps ...................   Passed    0.23 sec

      Start 40: testguibrowser

40/40 Test #40: testguibrowser ...................   Passed    1.53 sec


98% tests passed, 1 tests failed out of 40


Total Test time (real) =  54.62 sec


The following tests FAILED:

38 - testgui (Child aborted)

Errors while running CTest

make: *** [test] Error 8

**Comment by HelixDeCube** [comment]
<img width="803" alt="testgui" src="https://user-images.githubusercontent.com/58761642/70636338-5bde5b00-1c03-11ea-9d5a-74e2eef09155.png">

**Comment by droidmonkey** [comment]
Unfortunately there is not much I can do to help you. You will have to run the test with error reporting turned on (see our wiki).

**Comment by HelixDeCube** [comment]
Executed test with CTEST_OUTPUT_ON_FAILURE=1

32/33 Test #32: testgui ..........................Child aborted***Exception:  24.64 sec
********* Start testing of TestGui *********
Config: Using QtTest library 5.13.2, Qt 5.13.2 (x86_64-little_endian-lp64 shared (dynamic) release build; by Clang 11.0.0 (clang-1100.0.33.8) (Apple))
2019-12-11 11:31:13.297 testgui[34031:188202] CoreText note: Client requested name ".SFNSMono-Regular", it will get Times-Roman rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[NSFont systemFontOfSize:].
2019-12-11 11:31:13.297 testgui[34031:188202] CoreText note: Set a breakpoint on CTFontLogSystemFontNameRequest to debug.
2019-12-11 11:31:13.297 testgui[34031:188202] CoreText note: Client requested name ".SFNSMono-Regular", it will get Times-Roman rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[NSFont systemFontOfSize:].
QWARN  : TestGui::initTestCase() Couldn't load translations.
PASS   : TestGui::initTestCase()
PASS   : TestGui::testSettingsDefaultTabOrder()
PASS   : TestGui::testCreateDatabase()
QDEBUG : TestGui::testMergeDatabase() Merge Sample Entry/Sample Entry with local on top/under NewDatabase
QWARN  : TestGui::testMergeDatabase() History entry of Sample Entry[9f4544c2ab00c74a8a1a6eaf26cf57e9] at 2010-09-06 20-28-24-000 contains conflicting changes - conflict resolution may lose data!
PASS   : TestGui::testMergeDatabase()
QDEBUG : TestGui::testAutoreloadDatabase() Merge Sample Entry/multiline title with alien on top under NewDatabase
QWARN  : TestGui::testAutoreloadDatabase() Inconsistent history entry of Sample Entry[9f4544c2ab00c74a8a1a6eaf26cf57e9] at 2019-12-11 16-31-16-000 contains conflicting changes - conflict resolution may lose data!
QWARN  : TestGui::testAutoreloadDatabase() Inconsistent history entry of Sample Entry[9f4544c2ab00c74a8a1a6eaf26cf57e9] at 2019-12-11 16-31-16-000 contains conflicting changes - conflict resolution may lose data!
QWARN  : TestGui::testAutoreloadDatabase() History entry of Sample Entry[9f4544c2ab00c74a8a1a6eaf26cf57e9] at 2010-09-06 20-28-24-000 contains conflicting changes - conflict resolution may lose data!
PASS   : TestGui::testAutoreloadDatabase()
PASS   : TestGui::testTabs()
PASS   : TestGui::testEditEntry()
PASS   : TestGui::testSearchEditEntry()
PASS   : TestGui::testAddEntry()
PASS   : TestGui::testPasswordEntryEntropy()
PASS   : TestGui::testDicewareEntryEntropy()
QWARN  : TestGui::testTotp() QObject::connect: No such signal DatabaseWidget::lockedDatabase()
QWARN  : TestGui::testTotp() QObject::connect:  (receiver name: 'TotpDialog')
PASS   : TestGui::testTotp()
FAIL!  : TestGui::testSearch() '(searchTextEdit->hasFocus())' returned FALSE. ()
   Loc: [/Users/ysharov/Software/Opensource/keepassxc/tests/gui/TestGui.cpp(840)]
FAIL!  : TestGui::testDeleteEntry() 'entryDeleteWidget->isEnabled()' returned FALSE. ()
   Loc: [/Users/ysharov/Software/Opensource/keepassxc/tests/gui/TestGui.cpp(968)]
FAIL!  : TestGui::testCloneEntry() 'action->isEnabled()' returned FALSE. ()
   Loc: [/Users/ysharov/Software/Opensource/keepassxc/tests/gui/TestGui.cpp(1452)]
QFATAL : TestGui::testCloneEntry() Received signal 11
         Function time: 84ms Total time: 23107ms
FAIL!  : TestGui::testCloneEntry() Received a fatal error.
   Loc: [Unknown file(0)]
Totals: 12 passed, 4 failed, 0 skipped, 0 blacklisted, 23107ms
********* Finished testing of TestGui *********

**Comment by droidmonkey** [comment]
Curiously these don't fail on the continuous integration server

**Comment by madhead** [comment]
I am seeing very similar error messages when using Git Gui after update to macOS 10.15.2. Something changed in the update, perhaps.

**Comment by droidmonkey** [comment]
Ok closing this, thank you!
