### ISSUE TITLE
Autofocus Find input after opening database

### ISSUE THREAD

**Issue by vaidotas-adf** [keepassxreboot/keepassxc#401]
## Expected Behavior
After opening database find input dialog should be focused, that eliminates additional click or key combination to start searching.

## Current Behavior
Find input dialog is not focused.

## Your Environment
* KeePassXC version/commit used: 2.1.3
* Operating System and version: MacOS X El Capitan

**Comment by droidmonkey** [comment]
This seems like it should be a preference. Everyone has a different workflow when it comes to search and keyboard shortcuts. Frankly, hitting CTRL+F right before you search isnt that big of a deal.

**Comment by vaidotas-adf** [comment]
Having preference to enable autofocus would be great. I'm used to how Keepass on Windows works, where search autofocus is enabled by default.

**Comment by anewuser** [comment]
@droidmonkey You're right that everyone has a different use, but I'd assume that most users who open the program from the system tray or unlock it just want to quickly find a password by typing the first letters of an entry without the need of using <kbd>CTRL</kbd> + <kbd>F</kbd> or any other key combination. The previous programs I used (Enpass and KeeWeb) both focused their search fields automatically.

**Comment by ccoenen** [comment]
implemented in pr #887

**Comment by marcovtwout** [comment]
Focus the search window after unlocking works fine, but I noticed it doesn't work when restoring from tray. Would that be useful to implement and should I create a new issue for that?

**Comment by droidmonkey** [comment]
Sure

**Comment by marcovtwout** [comment]
Issue created: https://github.com/keepassxreboot/keepassxc/issues/9128
