### ISSUE TITLE
Segfaulting when importing csv

### ISSUE THREAD

**Issue by AyJ3y** [keepassxreboot/keepassxc#4011]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Succesfully creating a kdbx from csv.

## Current Behavior
[NOTE]: # ( Tell us what actually happens )
KeePassXC segfaults when i try to import a csv. This happens at the very last stage when the kdbx is created. The kdbx will be there and readable but it's completely empty. In the Notes of the root directory it also says that it was created from the imported csv.

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1. Export the Database as a csv file.
2. Try importing it again.

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )
I wasn't able to open my database (the HMAC mismatch issue regarding version 2.5) even tho I deleted the config directory. The database couldn't even be opened with an older Version, seems like v2.5 corrupted my database somehow. Luckily i have Backups. I opened a backup file and exported it and tried to reimport it. The importing doesn't work with any version I've tried.

On Linux: 2.4.3 & 2.5.1
On Windows: 2.5.1

**Comment by droidmonkey** [comment]
Duplicate issue
