### ISSUE TITLE
Support alternative password that erases the database

### ISSUE THREAD

**Issue by brazero** [keepassxreboot/keepassxc#4012]
hi,
an option should be outstanding.
the ability to configure a "nuke" password... if this password is used, all the password database is deleted.
another option is to have a safe password, if it's entered, keespass launch normally but with a separate database.
those options can offer a big security upgrade. if you're "forced" to give the master password to someone you can cheat him.
regards

**Comment by droidmonkey** [comment]
Hard pass from mw

**Comment by bram1253** [comment]
If this feature was added then you'd still be able to simply copy the database before trying to unlock it, so if it does get nuked you always can try again.

Plus I don't really see how this would have any practical uses.

**Comment by phoerious** [comment]
Or use an alternative client for that matter.
