### ISSUE TITLE
Browser Addons wants access to wrong passwords

### ISSUE THREAD

**Issue by fbnkrs** [keepassxreboot/keepassxc#4014]
## Expected Behavior

Addon should provide only the credentials for saved URL

## Current Behavior

On some websites the Addon wants access to a lot of saved credentials of totally different websites.

I go to websiteA and the addon wants access to websiteD, websiteX, websiteB....

## Debug Info
KeePassXC - Version 2.5.1
Revision: 0fd8836

Qt 5.13.2
Diagnosemodus ist deaktiviert.

Betriebssystem: Manjaro Linux
CPU-Architektur: x86_64
Kernel: linux 5.4.2-1-MANJARO

Aktivierte Erweiterungen:
- Auto-Type
- Browser-Integration
- SSH-Agent
- KeeShare (bestätigtes und unbestätigtes Teilen)
- YubiKey
- Secret-Service-Integration

Kryptographische Bibliotheken:
 libgcrypt 1.8.5

Libraries:
- LIBS

**Comment by varjolintu** [comment]
Duplicate of https://github.com/keepassxreboot/keepassxc-browser/issues/686
