### ISSUE TITLE
File dialog boxes disappear a few seconds when a database is open.

### ISSUE THREAD

**Issue by rmcgarry** [keepassxreboot/keepassxc#4015]
## Expected Behavior
When opening any file, whether a database or importing an icon, the "Open file" window should allow us to select a new file and not disappear  after a few seconds.

## Current Behavior
On Mac 10.14.6 (Mojave).  After upgrading to KeePassXC 2.5.1, I can select a database to open without issue.  When I perform any subsequent operation that requires a File Dialog box (Open a database, Save As..., Import an Icon), the "Open File" window will open, but then disappear after several seconds, usually between 10-30 seconds.  This behavior only shows when a database is  open.  

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )

## Steps to Reproduce
1.  Open KeePassXC 2.5.1 on MacOS 10.14.6
2.  Select an existing database and open it.
3.  Perform any file operation that requires browsing a filesystem to select a file, including opening a new database, importing an icon, or selecting "File->Save As".
4.  Wait 10-30 seconds.  
5.  The Finder window will disappear.

## Context
I have just upgraded from an earlier version (I believe 2.4.3) I removed that version from the Application folder, and used  homebrew to install this version (brew cask install homebrew).

It is possible to complete an operation (e.g. open a second database), but you have to be quick and perform the action before the finder window disappears.

This behavior persisted after a "brew cask uninstall keepassxc" and "brew cask install keepassxc".

## Debug Info
KeePassXC - Version 2.5.1
Revision: 0fd8836

Qt 5.13.1
Debugging mode is disabled.

Operating system: macOS Mojave (10.14)
CPU architecture: x86_64
Kernel: darwin 18.7.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
 libgcrypt 1.8.5

**Comment by droidmonkey** [comment]
This is a bug in Qt 5.13
