### ISSUE TITLE
Merge loses unsaved changes when file on disk is changed

### ISSUE THREAD

**Issue by Paul-kp** [keepassxreboot/keepassxc#4016]
## Steps to Reproduce
1. Ensure "Automatically save after every change" is off.
2. Open existing database.
3. Add something to the Notes field of an entry, OK.
4. Use KeePass to open the same database and modify the same entry by adding something to the Notes. Save the changes in KeePass.
5. KeePassXC pops up the "Merge Request" window. Click "Merge".

The changes made in KeePassXC are lost.

## Debug Info
KeePassXC - V2.5.1 portable

Operating system: Windows 8.1

## Screenshots
Modified Note in KPXC. Changes not saved.
![KPXCmodified](https://user-images.githubusercontent.com/58877040/70846959-c5a27300-1e56-11ea-8186-8acd8bf79f29.PNG)

Same entry modified in KeePass.
![KPmodified](https://user-images.githubusercontent.com/58877040/70846960-c5a27300-1e56-11ea-8815-6e727d5c742e.PNG)

Merge request in KPXC following save in KeePass.
![KPXCmergeRequest](https://user-images.githubusercontent.com/58877040/70846961-c63b0980-1e56-11ea-828c-59c8c484d617.PNG)

KPXC entry post merge.
![KPXCpostMerge](https://user-images.githubusercontent.com/58877040/70846962-c63b0980-1e56-11ea-86ff-d798e20d4942.PNG)

**Comment by droidmonkey** [comment]
That's not how merging works in the KeePass world. Every attribute, notes included, are covered under one modified time (the entry's). You can easily reproduce this on keepass side as well.

**Comment by Paul-kp** [comment]
Sorry, I left out the important bit.
The KPXC change is not saved in the history so the data is lost.

The most recent change should be kept and the older placed in history.

**Comment by droidmonkey** [comment]
Ah yes I agree with that!

**Comment by droidmonkey** [comment]
I could not replicate the failure. When I made a change to the notes and did not save the database. Then modified the notes in KeePass and then merged in KeePassXC, I had a history item with my original "unsaved" notes.

**Comment by Paul-kp** [comment]
Seems I have misled you. Because I didn't reload the DB in KeePass between tests I wasn't using the latest DB all the time - thought it was odd.
It is now working as expected.

Thanks for taking the time.
