### ISSUE TITLE
Autotype doesn't work after update

### ISSUE THREAD

**Issue by velichkin** [keepassxreboot/keepassxc#4017]
After update to 2.5.1 autotype doesn't work. When I press autotype sequence (in my case it's Cmd+Ctrl+M), dialog with password entries opens; when I choose one of them - nothing happens. It was working fine with 2.5.0. I've tried to install 2.5.0 then, but issue is still there.

## Debug Info
KeePassXC - 2.5.1
Revision: 0fd8836

Operating system: MacOS Catalina (10.15)

**Comment by droidmonkey** [comment]
Open the system privacy settings and enable KeePassXC. You can also remove the application from all privacy settings and it will prompt you to enable when you try again.

**Comment by velichkin** [comment]
Thanks. It was really issue with privacy settings. In my case, all permissions were enabled, but I couldn't uncheck them. This workaround helped me - https://github.com/aahung/Unshaky/issues/118
