### ISSUE TITLE
Crash After Adding Custom Icon

### ISSUE THREAD

**Issue by HUGHUSR** [keepassxreboot/keepassxc#4019]
Added a custom icon. When clicking on the added icon to select it, keepassxc crashed. See attached crash report.

When restarting keepassxc, icon had been added to custom collection, but it had not been selected for the entry's icon. Selecting the icon then worked without an issue.

DEBUG INFO
==========
KeePassXC - Version 2.5.1
Revision: 0fd8836

Qt 5.13.1
Debugging mode is disabled.

Operating system: macOS Mojave (10.14)
CPU architecture: x86_64
Kernel: darwin 18.7.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
 libgcrypt 1.8.5
[KeePassXC_2019-12-14-164931_Me.crash.zip](https://github.com/keepassxreboot/keepassxc/files/3964387/KeePassXC_2019-12-14-164931_Me.crash.zip)

**Comment by droidmonkey** [comment]
Duplicate issue and fixed by #3991
