### ISSUE TITLE
URL Opening doesn't pass {USERNAME} and {PASSWORD} variables correctly

### ISSUE THREAD

**Issue by ugoviti** [keepassxreboot/keepassxc#402]
Hi,
thank you very much for the project...
I'm coming from KeepassX 2.0.3 and I using URL Opening with passing {USERNAME} and {PASSWORD} field.

With KeepassX works good, but from KeepassXC it doesn't works...

Example:

in the URL I have: rdp://{USERNAME}:{PASSWORD}@192.168.0.217

opening this link the {USERNAME} and {PASSWORD} are not passed as real values, ah that is the resulting launched URL to the program handling RDP mime type protocol:

rdp://%7BUSERNAME%7D:%7PASSWORD%7D@192.168.0.217/

With kind regards

## Your Environment

* KeePassXC version/commit used: 2.1.3
* Qt version (e.g. Qt 5.3): qt5-5.7.1-14.fc25.x86_64
* Compiler (e.g. Clang++3.6.0): 
* Operating System and version: Fedora Linux 25

**Comment by phoerious** [comment]
Adding the password to the URL is a pretty bad idea. You can find that in the process explorer and most likely also in your desktop logs.

**Comment by ugoviti** [comment]
I understand the idea... this is a feature of KeepassXC?
anyway rdesktop hide the password from the process list...
Now the correct way to handle the automatic connection to the server is via Auto-Type?

however, passing the {USERNAME} to the URL would be useful.

Would be great to have a settings to enable disable the passing of {USERNAME} and {PASSWORD} variables.

Kind regards

**Comment by phoerious** [comment]
I'm not aware that we changed anything here that would prevent substitution of placeholders in URLs, but I also wasn't aware that it is possible.

**Comment by TheZ3ro** [comment]
I will look into this ASAP

**Comment by TheZ3ro** [comment]
Yes I can confirm this bug, I'm working on it. Thanks for the submission

**Comment by TheZ3ro** [comment]
@ugoviti I've submitted a PR, if you want to try if it works #405

**Comment by ugoviti** [comment]
Good job @TheZ3ro , just compiled and tested... works perfectly now!

Thank you very much!

Keep up the good job.

Kind regards

**Comment by TheZ3ro** [comment]
Thanks @ugoviti :smile:

**Comment by ugoviti** [comment]
Hi @TheZ3ro ,
I'm Sorry, but I discovered a little bug... if the password contains the percent '%' simbol, the first character after the %, is uppercased, example:

REAL PASSWORD = abcd%asd

is passed to the command, as: abcd%Asd

Thank you very much

**Comment by TheZ3ro** [comment]
This is a different problem so you should open a different Issue.

Anyway I've tried it out,
Username is `Jo%hn` password is `sec%ret` this is the URL resolved:
![istantanea_2017-03-17_14-15-55](https://cloud.githubusercontent.com/assets/686894/24044642/6f6259ec-0b1c-11e7-9ea4-8454fdcbb137.png)

If I copy the URL this is the clipboard content `http://twitter.com/Jo%hn.sec%ret`
If I open the URL this is the page visited `https://twitter.com/Jo%25hn.sec%25ret`, the `%` symbol is URLEncoded to `%25` correctly
