### ISSUE TITLE
SSH Agent settings added to entry when not needed

### ISSUE THREAD

**Issue by Thurion** [keepassxreboot/keepassxc#4020]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
KeeAgent.settings should only be added to an entry when there are settings to store, as in a key is set up to be used.

## Current Behavior
[NOTE]: # ( Tell us what actually happens )
KeeAgent.settings are added to an entry on some occasions.

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )
Don't add KeeAgent.settings if it does not exist and the key is not set up (i.e. chosen attachment or path are empty).

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1. Enable SSH Agent
2. Restart the program
3. Create a new entry and add an attachment.
    * Also works when editing an existing entry.
4. Save it by pressing `Ok`.
5. Notice that KeeAgent.settings is present but not required

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )
The impact of this issue is minor at best. I noticed it when I opened my database on my phone and looked at an entry where I added an attachment.
The ~1.4 KB the file adds to the entry is not large but it could add up for a larger database and could become noticeable when syncing it on a mobile client.

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.5.1
Revision: 0fd8836

Libraries:
-  libgcrypt 1.8.5

Operating system: Windows 10 (10.0)
CPU architecture:  x86_64
Kernel: winnt 10.0.18362

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

**Comment by hifi** [comment]
If all settings for SSH Agent are at their defaults the attachment is removed on apply. Even a minor change (like selecting between attachment and external file) would create the KeeAgent.settings attachment.

Would need to know more details if the attachment is not removed when default settings are restored. There's also a refactor coming in 2.6.0 which will likely change this behavior a bit.

**Comment by hifi** [comment]
There are now multiple fixes/changes to KeeAgent.settings handling coming in for 2.6.0 and I'm fairly confident this is fixed. If there's no way to repro this reliably I'm going to close this as fixed when 2.6.0 is released.

Thanks.
