### ISSUE TITLE
URL match bug

### ISSUE THREAD

**Issue by plusls** [keepassxreboot/keepassxc#4021]
When i open a url endwith `com.cn` or `edu.cn`(chinese university's domain endwith edu.cn, such as [http://gradadmission.tsinghua.edu.cn/f/login](http://gradadmission.tsinghua.edu.cn/f/login)), keepassxc return many record **if i don't have record in this site.**

![image](https://user-images.githubusercontent.com/23459592/70864647-14532880-1f8f-11ea-9bdb-6b9d39360b94.png)

## Expected Behavior
keepassxc will tell me no record matched.

## Current Behavior
keepassxc return many record if i don't have record in this site.

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )
Keepassxc 2.5.0 don't have this bug, but 2.5.1 have.
I think its url match algorithm have some problem.
I hope keepassxc can match the entire url including port, subdomain and path.

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1. open [http://gradadmission.tsinghua.edu.cn/f/login](http://gradadmission.tsinghua.edu.cn/f/login))
2. keepassxc will display many record it matched.

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )

## Debug Info
KeePassXC - 2.5.1
Revision: 0fd8836

Libraries:
- LIBS

Operating system: Windows10
CPU architecture: x86_64
Kernel: winnt 10.0.18363

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

**Comment by droidmonkey** [comment]
Duplicate and already fixed for 2.5.2

**Comment by Anagastes** [comment]
Isnt complete fix iun 2.5.2 (i have comoiled it for me)

It's in the URL field.

https://vhost.test.test/phpmyadmin/

But it is also loaded under this URL.

https://vhost.test.test/

Why? Exact match is activated.

**Comment by Anagastes** [comment]
> Duplicate and already fixed for 2.5.2



> Duplicate and already fixed for 2.5.2

Isnt complete fix iun 2.5.2 (i have comoiled it for me)

It's in the URL field.

https://vhost.test.test/phpmyadmin/

But it is also loaded under this URL.

https://vhost.test.test/

Why? Exact match is activated.
