### ISSUE TITLE
Auto-Type does not find Firefox window using IP addresses

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [keepassxreboot/keepassxc#4023]
## Expected Behavior
When I have an entry for (1) URL `http://192.168.1.78` and an entry (2) for URL `192.168.1.50` then, when I enter 2 into my browser's URL bar and invoke autocompleted, the credentials for 2 should be enterered.

Both sets of credentials are for logging into routers (I have, or rather had, two routers on the same home setup).

## Current Behavior
The credentials for _1_ are entered.

## Possible Solution

Note that the following did not help: ensuring that both 1 and 2 - i.e. all database entries for local addresses - include in their URL the 'http' prefix.

Deleting 1 did not solve the problem either. Rather, so doing produced the error 'Couldn't find an entry that matches the window title'.

## Steps to Reproduce
1. Have Firefox installed.
2. Have router on IP 192.168.1.50 (though perhaps any internal address would do).
3. Enter the relevant credentials into KeePassXC, together with that IP.
4. Try to autofill the IP.

## Context

The only relevant browser extension that I have (for any browser) is 'KeePass Helper - URL in title'. I have the problem on both Windows and Linux. Well: when use Firefox. Iridium (a Chrome variant) does not suffer from the problem.

## Debug Info

For my Linux machine:
```

KeePassXC - Version 2.5.1
Revision: 0fd8836

Qt 5.9.5
Debugging mode is disabled.

Operating system: Linux Mint 19.2
CPU architecture: x86_64
Kernel: linux 5.3.16-050316-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration


Cryptographic libraries:
 libgcrypt 1.8.1

```

For my Windows machine:

```
KeePassXC - Version 2.5.1
Revision: 0fd8836

Qt 5.13.1
Debugging mode is disabled.

Operating system: Windows 10 (10.0)
CPU architecture: x86_64
Kernel: winnt 10.0.18362

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.5
```

**Comment by droidmonkey** [comment]
This is likely already fixed in 2.5.2 with the matching behavior fixes.

**Comment by LinuxOnTheDesktop** [comment]
I tried the latest AppImage (so, I tested on Linux, not Windows) and I had the same problem. That is: having deleted one of the router entries, I went to the URL for which an entry remained and got the, ' 'Couldn't find an entry that matches the window title' error.

**Comment by droidmonkey** [comment]
Wait so you are using Auto-Type not the browser integration?

**Comment by LinuxOnTheDesktop** [comment]
As I said: yes, auto-type.

**Comment by droidmonkey** [comment]
No, you wrote autofill above. You also did not include what the title of the firefox browser window was when you tried to autofill. Does the title even have the ip address in it?

**Comment by LinuxOnTheDesktop** [comment]
I'm sorry; I was not alive to a distinction between autofill and autotype (and I did write: 'The only relevant browser extension that I have [. .]').

Here is a gif. You will see that there are two complications with the situation. (1) The authentication window is a pop-up. (2) Authentication is requested only when switching tabs within the router UI.

![Peek 2019-12-16 03-51](https://user-images.githubusercontent.com/47056543/70878002-9f481900-1fb7-11ea-9e43-4a4e56dd01fa.gif)

**Comment by droidmonkey** [comment]
That popup is an http auth dialog. You will have to register that window with the auto-type configuration for the router's entry. Otherwise it will not find it.

OR you can use the browser plugin which will take care of all this for you.

**Comment by LinuxOnTheDesktop** [comment]
> You will have to register that window with the auto-type configuration for the router's entry.

Would you mind explaining how one does that, please? Here is the setup I have at present:

![image](https://user-images.githubusercontent.com/47056543/70878734-90169a80-1fba-11ea-884c-6c0a660d9bf5.png)

**Comment by droidmonkey** [comment]
Go to the Auto-Type tab, then with the http auth window open, press the plus button at the bottom and select that window on the right side.

**Comment by LinuxOnTheDesktop** [comment]
Thanks. But it still does not work. I tried:
![image](https://user-images.githubusercontent.com/47056543/70880279-4fba1b00-1fc0-11ea-8230-3b260f78e490.png)

And I tried using the following strings (for, after all, I want it not to matter which tab, within the router UI, generates the authentication window), all to no avail:

- 192.168.1.50 - DD-WRT
- 192.168.1.50 - DD-WRT*

**Comment by droidmonkey** [comment]
You want to use the "Authentication Required" window title.

**Comment by LinuxOnTheDesktop** [comment]
Ah. Thank you. That works. However: won't all such windows have that title? If so, will there be a problem if within my database I have more than one entry that cites that window title? Perhaps not. For, perhaps the autofil will be trading (so to speak) on what is in the URL field, too.

**Comment by droidmonkey** [comment]
If more than one entry matches you will be given a selection dialog
