### ISSUE TITLE
Issues with compiling from source

### ISSUE THREAD

**Issue by elvisef** [keepassxreboot/keepassxc#4024]
I tried to compile from source, to upgrade existing version with domains problem, but cannot, I dont know why.. The Internet shows nothing useful.

![image](https://user-images.githubusercontent.com/25976749/70888428-9ae42600-1fe0-11ea-9a7c-d9163136f512.png)

Can anyone advise me what to install/do ?

The screenshot shows any tries.
I am using Debian v10 Buster.

**Comment by phoerious** [comment]
I don't know what your CMake version is, but it looks pretty darn old. You need a newer one, which is at least version 3.7, as state in the error message.

**Comment by elvisef** [comment]
![Zaznaczenie_172](https://user-images.githubusercontent.com/25976749/70891497-a38c2a80-1fe7-11ea-8a29-27b00ac2b322.png)

**Comment by elvisef** [comment]
![Zaznaczenie_173](https://user-images.githubusercontent.com/25976749/70891576-c3bbe980-1fe7-11ea-80dc-16891424a354.png)

**Comment by phoerious** [comment]
Seems like it's actually complaining not about the version, but about a missing command. Are you sure you have a clean and complete checkout?

**Comment by phoerious** [comment]
NVM. It seems like the FeatureSummary module might not be auto-included on your system. I submitted a fix for review. To make it work on your checkout, just add

``
include(FeatureSummary)
```

at the top of the CMakeLists.txt file.

**Comment by elvisef** [comment]
It seems that something is still wrong, look:

![Zaznaczenie_175](https://user-images.githubusercontent.com/25976749/70893754-fcf65880-1feb-11ea-8765-f4f36ad18a3d.png)
![Zaznaczenie_174](https://user-images.githubusercontent.com/25976749/70893757-fec01c00-1feb-11ea-8b0c-d2d0b8b04ee3.png)

Should then I add any more lines ?

**Comment by elvisef** [comment]
Sorry, but something is still wrong, look:

![Zaznaczenie_175](https://user-images.githubusercontent.com/25976749/70894062-8efe6100-1fec-11ea-8050-49ae4ce37b48.png)
![Zaznaczenie_174](https://user-images.githubusercontent.com/25976749/70894067-902f8e00-1fec-11ea-9fa5-043b692cebcc.png)

Should I add any more lines ?
KeepassIt seems that something is still wrong, look:

![Zaznaczenie_175](https://user-images.githubusercontent.com/25976749/70893754-fcf65880-1feb-11ea-8765-f4f36ad18a3d.png)
![Zaznaczenie_174](https://user-images.githubusercontent.com/25976749/70893757-fec01c00-1feb-11ea-8b0c-d2d0b8b04ee3.png)

Should then I add any more lines ?

**Comment by phoerious** [comment]
Can you check if it works if you add it in line 39 of src/CMakeLists.txt?

**Comment by elvisef** [comment]
Tried it, nothing changes. Still "add_feature_info" problem ; (

![Zaznaczenie_177](https://user-images.githubusercontent.com/25976749/70896313-c53ddf80-1ff0-11ea-99c3-6f7b442e1b29.png)

**Comment by phoerious** [comment]
Can you try the `hotfix/4024-feature-summary-include` branch, please?

**Comment by elvisef** [comment]
Tried it, no change.All I have above the "cmake_minimum_required" command is as on the screenshot below:

![Zaznaczenie_181](https://user-images.githubusercontent.com/25976749/70897945-f53ab200-1ff3-11ea-948e-d0940db13744.png)

So it's only a default commented out block of information.

**Comment by phoerious** [comment]
You have to have the line in there, just not before the first line in the file. Please try the branch I mentioned.

**Comment by elvisef** [comment]
Yea, I know, but look at my screenshot:

![Zaznaczenie_184](https://user-images.githubusercontent.com/25976749/70984905-93de1600-20bb-11ea-8a37-fe8e3cbd9ee2.png)

It is really weird.. because the line that says "cmake_minimum_required" is already in CMakeLists.txt file.

**Comment by carlolf** [comment]
I tried to build the application by cloning the latest official release and doing the cmake as stated in the build notes.
I am using Mint 20.1, cmake version is 3.16.3. And I am running into the same error "Unknown CMake command "add_feature_info".
