### ISSUE TITLE
[PRE-RELEASE] MacOS snapshot only runable on 10.15, not earlier versions

### ISSUE THREAD

**Issue by PTR-inc** [keepassxreboot/keepassxc#4025]
## Expected Behavior
Can run snapshot on macos 10.14

## Current Behavior
Is compiled for macos 10.15 only, not able to run

## Possible Solution
Compile it to also run on earlier versions

Operating system: MacOS 10.14.6

**Comment by droidmonkey** [comment]
The snapshots are built on a macOS 10.15 machine. Not sure how to make them work otherwise.

**Comment by phoerious** [comment]
You have to set the compilation target via an environment variable. The release-tool does that.

**Comment by droidmonkey** [comment]
Should update our CI then

**Comment by droidmonkey** [comment]
CI has been updated
