### ISSUE TITLE
Statisics shows problems, but does not show where

### ISSUE THREAD

**Issue by MegaV0lt** [keepassxreboot/keepassxc#4028]
[TIP]:  # ( Provide a general summary of the feature in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Summary
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
At the statistics page i have some warnings (eg. short passwords), but i can not easily find the entry's in the database

## Desired Behavior
[NOTE]: # ( Tell us how the new feature should work, be specific )
There should be a list with the items to be fixed

## Possible Solution
[NOTE]: # ( Not required, but suggest ideas on how to implement the addition or change )

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
is almost impossible to fix the mentiones problems. See Screenshot:
![Auswahl_20191216_15:22:13](https://user-images.githubusercontent.com/2804301/70914890-2bd6f380-2019-11ea-9c3d-4e90379ce6b7.jpg)

**Comment by bram1253** [comment]
Perhaps a new column in your database would be an intuitive way of spotting insecure passwords. For example: a column called "Rating" and it can show you a green circle (good password), a yellow circle (reused), or a red one (weak password). And then you can hover over the colored circle to know exactly what the meaning of it is with a tooltip appearing.

Then to fix the issues all you'd have to do is sort by this column and fix them one by one. Kind of like a checklist.

**Comment by MegaV0lt** [comment]
@bram1253 
yes, that would be a great help. But i have 30+ groups. So i have to go group by group. But anyway; that "Rating" is worth an Feature Request. Thank you

**Comment by droidmonkey** [comment]
See #3993

**Comment by wolframroesler** [comment]
@MegaV0lt I appreciate that you're using Nextcloud and that you've got an excellent average password length, and your password database is much bigger than mine :) however in the future you may want to consider posting screenshots not of your own database but of the demo database we created for this very purpose. You find it here: https://github.com/keepassxreboot/keepassxc/blob/develop/share/demo.kdbx (the password is `secret`).

Anyway, thanks for reporting this issue, I think many people feel the same (me included). I've thought about adding a tool tip with a list of entries (not very useful if there are many of them), or convert the table into something like a tree view that you can un-collapse to show the entries, which could then be double-clicked to jump into the entry editor.

However, as mentioned by @droidmonkey, the upcoming Health Check (#551/#3993) already has a detailed list of problematic entries (double-clickable to edit them right away), so maybe that will remedy your issue?

@bram1253 I like your idea ("Rating" column with password quality indicator in the entry list), and Health Check gives us the tools needed (e. g. a password quality assessment including a color), so I think adding it won't be too difficult. Can you create a new issue for that? A single issue shouldn't cover two independent features IMO.

**Comment by MegaV0lt** [comment]
The Healthcheck would be enought for me. Thanks for the hint. Hope it comes soon ;-)

**Comment by wolframroesler** [comment]
Thanks @MegaV0lt :)

Would you mind closing the issue then? @bram1253's suggestion should go into an issue of its own IMO.
