### ISSUE TITLE
crash when switching to favicon

### ISSUE THREAD

**Issue by FlorinAndrei** [keepassxreboot/keepassxc#403]
## Expected Behavior
Download favicon, apply it to the entry.

## Current Behavior
Crash when clicking OK.

## Steps to Reproduce (for bugs)
1. Right-click a key entry, select View/Edit, select Icon.
2. Click Download Favicon
3. Click OK.

Do NOT click once on the favicon to select it after it's downloaded.

## Context
KPXC 2.1.3 on Mac OS X 10.12.3. I just started using it today.
The DB is shared via Dropbox.
The DB was made last night, on Windows, using KPXC 2.1.3, from an imported v1 DB made with the old KeePassX (not sure which version, but probably really old, like maybe 0.4). I have not made edits to this DB yet on KPXC. It started with default icons everywhere.

So I've relaunched KPXC, went again into the Icon menu, actually clicked once on the downloaded favicon to select it, clicked OK, and it was fine.

## Your Environment

* KeePassXC version/commit used: 2.1.3
* Qt version (e.g. Qt 5.3): 5.8.0
* Compiler (e.g. Clang++3.6.0): no idea, I've installed it from the binary installer
* Operating System and version: Mac OS X 10.12.3

**Comment by FlorinAndrei** [comment]
Correction: it crashes every time after downloading a new favicon, after you click once to select it, then click OK to apply. Basically the favicon thing is broken.

**Comment by phoerious** [comment]
I cannot reproduce the crash. Tried on both Arch Linux and OS X.

**Comment by droidmonkey** [comment]
Can you produce a stacktrace through gdb?

**Comment by weslly** [comment]
This happened to me a few times before but I can't to reproduce now.

**Comment by FlorinAndrei** [comment]
I cannot reproduce it on Ubuntu 16.04 (installed from snap), but on OS X it crashes every time.

I'll see if I can figure out how to get the stack trace.

**Comment by redzacke** [comment]
Hi,
unfortunately I have the same problem reproduced in the same way.
+1

**Comment by sephie** [comment]
Experiencing the same on MacOS 10.12.5.
Additionally, it seems that the crash occurs when downloading the icon twice, AND that the icon that gets added to the list is the icon of the previous entry/url you attempted to dowload the icon from. There's an off-by-one error somewhere.

**Comment by droidmonkey** [comment]
Oh gross and no bounds check!

**Comment by quinncomendant** [comment]
I've experienced this too, but can't reproduce it now. :(

**Comment by phoerious** [comment]
I could also reproduce casual crashes when downloading icons twice, but I've had no time to dig deeper on this. I'll take a deeper look in the evening.
