### ISSUE TITLE
Application crash when performing multiple updates to a OneDrive synced database

### ISSUE THREAD

**Issue by RylandDeGregory** [keepassxreboot/keepassxc#4030]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Expected Behavior
Edit multiple secrets (rename, change username, change url) and application remains open.

## Current Behavior
Application crashes unexpectedly, losing modified data.

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1. Launch KeePassXC for MacOS.
2. Open a database that is hosted on Microsoft OneDrive.
<img width="311" alt="Screen Shot 2019-12-16 at 3 33 15 PM" src="https://user-images.githubusercontent.com/18073815/70941015-896b4000-2019-11ea-9be9-c8776b9e3ba7.png">

3. Edit a secret's title. Click OK.
4. Edit a second secret's title. Click OK.
5. (If the second update didn't crash the app, try making a third update to a different field)
6. KeePassXC application crashes.
<img width="437" alt="Screen Shot 2019-12-16 at 3 36 09 PM" src="https://user-images.githubusercontent.com/18073815/70941172-dd762480-2019-11ea-976d-f8a98f8f1cfb.png">

## Context
The Database is stored in a synced folder using OneDrive for Business.
<img width="541" alt="Screen Shot 2019-12-16 at 3 41 37 PM" src="https://user-images.githubusercontent.com/18073815/70941510-a2c0bc00-201a-11ea-9818-1a2d64e8ad9e.png">

## Debug Info
KeePassXC - Version 2.5.1
Revision: 0fd8836

Qt 5.13.1
Debugging mode is disabled.

Operating system: macOS 10.15.1
CPU architecture: x86_64
Kernel: darwin 19.0.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
 libgcrypt 1.8.5

Libraries:
- LIBS

**Comment by droidmonkey** [comment]
Already fixed in 2.5.2

**Comment by RylandDeGregory** [comment]
> Already fixed in 2.5.2

When can I expect the 2.5.2 release?

Thanks for the quick reply! :)

**Comment by droidmonkey** [comment]
As soon as Qt 5.14 is pushed to brew (that also fixes several issues on macOS)
