### ISSUE TITLE
Please compile the 2.5x package for Debian.

### ISSUE THREAD

**Issue by torerobo** [keepassxreboot/keepassxc#4032]
On the official website, a reference to the old package https://packages.debian.org/sid/keepassxc

No .deb builds either https://github.com/keepassxreboot/keepassxc/releases

I do not want to take a package from Ubuntu.
As a result, you need "statistics", I’m waiting by the sea for weather ...

**Comment by phoerious** [comment]
We do not maintain the Debian package, please ask them to update their repositories.
