### ISSUE TITLE
Lock database after inactivity is not working with popup windows

### ISSUE THREAD

**Issue by bobsaintcool** [keepassxreboot/keepassxc#4037]
## Expected Behavior
I believe when set, the database should be locked when popup windows are opened from within keepassxc.

## Current Behavior
Database is not beeing lock after X second of inactivity.

## Possible Solution
Not sure if its something that can be done?

## Steps to Reproduce
- Configure keepassxc with the following: 
```ini
[security]
lockdatabaseidle=true
lockdatabaseidlesec=10
```
- Open the database
- Open a popup windows from keepassxc, it includes at least:
  - `Database` > `Open Database`
  - `Help` > `About`
- After 10s (or more) the database is not lock

## Context

First discovered this when my datastore was remounted RO for some reasons and that auto save features weren't available. After 10 sec. of inactivity the database was still unlocked and keepassxc was only asking me if I wanted to save or cancel my modification.

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.3.4
Revision: 6fe821c

Libraries:
- Qt 5.12.2
- libgcrypt 1.8.4

Operating system: Linux Ubuntu
CPU architecture: amd64
Kernel: 5.0.0-37

**Comment by droidmonkey** [comment]
This is a known issue and has been addressed in more recent versions of KeePassXC. You should update. There is already an issue tracking further fixes for this.
