### ISSUE TITLE
Display Current Database Path/name

### ISSUE THREAD

**Issue by craigarno** [keepassxreboot/keepassxc#4038]
[TIP]:  # ( Provide a general summary of the feature in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Summary
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
When only one database is open there is no display showing the opened database path and filename.

## Desired Behavior
[NOTE]: # ( Tell us how the new feature should work, be specific )
When two databases are open hovering over the tab identifies the path E:\Passwords.kdbx or /media/user/Passwords.kdbx.  With only one database open, there is no way to retrieve this information.

## Possible Solution
[NOTE]: # ( Not required, but suggest ideas on how to implement the addition or change )

- Make hovering over the "Root" entry display database path/file info.

- Less desirable but perhaps easier to implement, keep the tab available, even when there is only one database open.

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
I might have up to 3 password databases available which I'm trying to merge/update.  If I close the wrong tab, then I'm not sure which database I have open;

- Local storage (in a laptop, desktop, server)

- Network drive, destination; NAS (big Linux system) for remote access and backup

- USB Storage (goes in my pocket, or a fireproof safe)

**Comment by droidmonkey** [comment]
Good idea with the root group hover

**Comment by climb-on** [comment]
The "workaround" suggested by DroidMonkey back in 2019 is not exactly right for the current version.  The file information is under Database "Reports" rather than "Settings".

**Comment by craigarno** [comment]
I found it under "Database Reports...",
and I give each copy of the database a different name which means something to me which shows up in the tab; "Server.com", "Local Computer", "Flash Drive" [of course I give real names, not generic ones given here for illustration.]
This works on both my Windows Laptop and Linux installations.
![image](https://user-images.githubusercontent.com/4262930/182205860-c72a9701-8a65-4025-af0a-66d9148adb0f.png)

**Comment by climb-on** [comment]
Found it. Thanks!
