### ISSUE TITLE
When exporting a database to CSV, export all fields

### ISSUE THREAD

**Issue by HUGHUSR** [keepassxreboot/keepassxc#4040]
[TIP]:  # ( Provide a general summary of the feature in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Summary
Currently, an export only exports what appears to be KDBv1 fields. 

Preferably, all data (fields) associated with an entry should be exported. If you have an export of the entire database (all fields for all records), then it would be possible to fully recover from a corrupted database, lost keys, etc. 

Now, only the basic (most critical) information is recoverable -- which is better than nothing, but not ideal.

Caveat: A CSV DR export should be written to an encrypted file system. I will open another issue to document what I consider KeePassXC Disaster Recovery Best Practices. 

## Desired Behavior
Export everything in the database when performing a CSV export.

## Possible Solution
[NOTE]: # ( Not required, but suggest ideas on how to implement the addition or change )

## Context
Export to an encrypted FS provides a recovery path to protect against database corruption, app bugs, lost keys, lost fobs, etc.

**Comment by droidmonkey** [comment]
CSV is not a recovery tool or database rebuild tool, and never will be. This has been discussed elsewhere in the issue board and duplicates that discussion.

**Comment by HUGHUSR** [comment]
I had searched on "recovery" and did not find anything that seemed relevant. Can you please point me to some of those discussions?

If not covered in those discussions... since you don't consider CSV a recovery option, what are your thoughts on recovery?

**Comment by HUGHUSR** [comment]
Okay. Thanks! Did not even know about the CLI tool. I see no mention of it in the KeePassXC User's Guide. Where is it documented?

THANKS for the heads-up!!

**Comment by droidmonkey** [comment]
Its self documented (--help) and man page on Linux (man keepassxc-cli).
