### ISSUE TITLE
Program-crash without saving after second time to apply a change in an entry (apply button)

### ISSUE THREAD

**Issue by AlwaysOn24** [keepassxreboot/keepassxc#4043]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
it should be possible, to edit an entry, click on apply and edit it again without loosing the last edited informations by programcrash. 

## Current Behavior
[NOTE]: # ( Tell us what actually happens )
It doesn t matter if you click Apply a second time or the OK-button, the programm crashes and forgets about the change that was made in the entry. 

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )
program should not suddenly crash and forget about the changeds of data that was entered in an already existing entry. 

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1. open program
2.enter password to open the database
3. open an already existing entry and edit something like in the notes a blank sign or word. 
4. click "apply"
5. edit again in the notes, some space or some other words
6. click the button apply   --->program crash, data of last edit missing. 

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )
this has already affected me in a way, that I could not log in a website anymore, because the password in an entry was forgotten (not saved).

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION 2.5.1, Official Ubuntu PPA from https://keepassxc.org/download/
Revision: REVISION

Libraries:
- LIBS

Operating system: OS Ubuntu
Distributor ID:	LinuxMint
Description:	Linux Mint 19.1 Tessa
Release:	19.1
Codename:	tessa
andipepino@andipepino-TravelMate-P245-M:~$ 

CPU architecture: ARCH
Kernel: KERNEL
processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 69
model name      : Intel(R) Pentium(R) 3556U @ 1.70GHz
stepping        : 1
microcode       : 0x25
cpu MHz         : 995.603
cache size      : 2048 KB
physical id     : 0
siblings        : 2
core id         : 0
cpu cores       : 2
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopolog:

Enabled extensions: no extensions enabled. 
- EXTENSIONS

**Comment by droidmonkey** [comment]
This is fixed already in 2.5.2 coming out this weekend.

**Comment by AlwaysOn24** [comment]
2.5.2, that is fantastic, please can you also deliver the new version for
ubuntu?

**Comment by droidmonkey** [comment]
It will be, we also offer the snap version and AppImage in case the apt repository is slow to update.
