### ISSUE TITLE
Support CJK input in AppImage

### ISSUE THREAD

**Issue by opqriu** [keepassxreboot/keepassxc#4044]
I want to use the latest version of Keeppass XC on Debian. The basic apt install keeppassxc allows CJK input. However, for flatpak or appimage, it is not possible to enter cjk.
I wish I could solve it, but I won't be disappointed if it's impossible.
However, some of the other Flatpak, Appimage apps are supported by CJK Input, which is not impossible.

Thank you for offering good SW open source. It's okay if it's not corrected. I won't be disappointed. Thank you. Good night.

ex) CJK Okay appimage : Joplin Note app. +++
ex) CJK OKay flatpak : Skype. Uberwriter. gnomeTodo. +++

CJK Input Med
1. Uim
2. Fcitx
3. Nimf (https://github.com/hamonikr/nimf - This Good.)
4. +++++++

**Comment by droidmonkey** [comment]
This is likely due to apparmor blocking access

**Comment by phoerious** [comment]
The Flatpak is not supported by us. The AppImage may be missing a Qt plugin or perhaps it's simply not working properly in combination with the fcitx (or whatever else you are using) on your system.
