### ISSUE TITLE
Segfault at 0 ip ... error 4 in keepassxc | Frequent Crashes

### ISSUE THREAD

**Issue by roberestarkk** [keepassxreboot/keepassxc#4045]
## Expected Behavior
Open KeePassXC
Continue using computer normally
KeePassXC remains running and usable

## Current Behavior
I open KeePassXC and login to my database.
The instant I do so I get a log saying "libpng warning: iCCP: known incorrect sRGB profile"
Though it continues to run as normal for a while.
Then, for reasons I'm not yet able to reproduce, I see the following in KSystemLog:
https://i.imgur.com/ZzobtKs.png

## Steps to Reproduce
1. Open KeePassXC
2. Enter DB Password
3. Minimise to System Tray
4. Wait/Interact with system normally
5. Suddenly notice when trying to sign into a website that you can't because KPXC isn't running

## Context
I am tabbing between Remmina on one screen remoted into Windows and Linux on the other.

## Debug Info
KeePassXC - Version 2.5.1
Revision: 0fd8836

Qt 5.13.2
Debugging mode is disabled.

Operating system: Manjaro Linux
CPU architecture: x86_64
Kernel: linux 4.19.88-1-MANJARO

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.5

**Comment by droidmonkey** [comment]
Does it do this with the AppImage or snap version?

**Comment by droidmonkey** [comment]
This seems like a library issue (outside of KeePassXC). You could also have a corrupt icon in your database.
