### ISSUE TITLE
"Agent connection failed" message on start and "Add to agent"

### ISSUE THREAD

**Issue by mackushev** [keepassxreboot/keepassxc#4046]
## Expected Behavior
I'm trying to add key from KeepassXC
Key added and checkbox 'Add key to agent then database is unlocked ' is set 
I expect than key became visible  in ssh-agent -L

## Current Behavior
[NOTE]: # ( Tell us what actually happens )
Then keepass starts it shows "Agent connection failed"
Button "Add to agent" shows the same message

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1. Add key to keepass
2. Set  'Add key to agent then database is unlocked ' on
3. Exit keepass and start it again

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )
ssh-agent don't crash on "add to agent" or "remove from agent" buttons like at https://github.com/keepassxreboot/keepassxc/issues/1746

SSH_AUTH_SOCK=/run/user/1001/keyring/ssh 

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.5.1
Revision: 0fd8836
Distribution: Snap

Qt 5.9.5
Debugging mode is disabled.

Operating system: Ubuntu Core 18
CPU architecture: x86_64
Kernel: linux 4.15.0-1065-oem

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.1
Libraries:
- LIBS

**Comment by droidmonkey** [comment]
You cannot use ssh agent with the snap distribution due to sandboxing.

**Comment by erikjoling** [comment]
I also ran into this problem. And I solved it by installing the Ubuntu package, not the snap distribution. 

You can download the default ubuntu package, but it's outdated (2.4.3, 2019). To install a more recent version follow the instructions on this blog-article: https://keepassxc.org/blog/2017-10-25-ubuntu-ppa/

**Comment by theHilikus** [comment]
@droidmonkey 
Just for the record, IIUC, there is a snap-approved solution to this: make the snap run its own ssh-agent instead of connecting to the global one
See [here for a discussion](https://forum.snapcraft.io/t/ssh-agent-plug-request/1250/4)

Now, whether it is worth implementing that solution in KPXC or not, I have no idea, but there seems to be a way a least

**Comment by droidmonkey** [comment]
That is not a solution. No other app can benefit from using an agent within your snap environment.
