### ISSUE TITLE
Error while reading the database: Unable to decompress binary

### ISSUE THREAD

**Issue by jeisoncp** [keepassxreboot/keepassxc#4050]
## Expected Behavior
Open the database with my password and key file.

## Current Behavior
I unable to open the database on KeePassXC, only getting this error: "Error while reading the database: Unable to decompress binary".

## Steps to Reproduce
1. Open KeePassXC
2. Select the database
3. Type the password
4. Select the key file
5. Click in OK

## Context
I have the same database file synchronized with my phone (using Syncthing) and there I able to open the file with KeePassDX. They are the same files, I checked that. I even copied manually from phone to computer, but still I couldn't open in KeePassXC.

## Debug Info
KeePassXC - Version 2.5.1
Revision: 0fd8836

Qt 5.13.2
Debugging mode is disabled.

Operating system: Manjaro Linux
CPU architecture: x86_64
Kernel: linux 4.19.88-1-MANJARO

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.5

**Comment by droidmonkey** [comment]
Looks like KeePassSX corrupted the database in its own unique way. Can you open it using KeePass2 or Keepass2android?

**Comment by droidmonkey** [comment]
Any more info? If not i am closing this.

**Comment by jeisoncp** [comment]
> Looks like KeePassSX corrupted the database in its own unique way. Can you open it using KeePass2 or Keepass2android?

No, I can't. I will try to export my database from KeePassDX and create a new one. Thanks!

**Comment by droidmonkey** [comment]
Sounds like the error is with KeePassDX

**Comment by ffgiraldez** [comment]
I have same error, using KeePassDX on android sync with google drive and KeePassXC 2.5.1, updating to 2.5.3 does not fix the problem

**Comment by droidmonkey** [comment]
https://github.com/Kunzisoft/KeePassDX/issues/412
