### ISSUE TITLE
KeePassXC Browser Chrome - enable autotype usage

### ISSUE THREAD

**Issue by aisbergde** [keepassxreboot/keepassxc#4052]
I configured some autotype sequences like these
{BS}{BS}{BS}{S:Filiale}{DELAY 500}{BS}{BS}{BS}{BS}{BS}{BS}{BS}{S:Konto}{DELAY 500}{BS}{BS}{BS}{BS}{BS}{BS}{BS}{BS}{BS}{BS}{PASSWORD}
because there are 4 input fields and I should use 3 of them
And the autotype sequences are working fine if I visit the website 
https://meine.deutsche-bank.de/trxm/db/
then I search the item in KeePassXC
And then I use the Ctrl-Shift-V (Perform Auto-Type)

But I would like to use the Browser plugin. And this doesn't work in the KeePassXC Browser Plugin. The Browser finds KeePassXC entries, but it will send the {USERNAME} to the third input mask which should not be used at all. Autotype sequence is ignored.

I can't find a way to use the Auto-Type sequence with the Browser Plugin

Request:
It should be possible to use the Auto-Type Sequence directly from the Browser plugin

**Comment by phoerious** [comment]
The browser extension doesn't 'type' and thus doesn't use the Auto-Type sequence. You can define custom fields for individual websites instead.

**Comment by aisbergde** [comment]
I tried to define custom fields, but I can only assign user and password, I can't find a way to assign advanced attributes to different fields. Should I ask this feature request or will this also be rejected?

**Comment by phoerious** [comment]
You can assign custom fields prefixed with KPH:

**Comment by varjolintu** [comment]
This is explained in the docs: https://keepassxc.org/docs/#faq-browser-string-fields

I've tested the possibility to trigger Auto-Type via the browser plugin, and it's possible to make. Just haven't had time to do it properly. This could mean that the user doesn't have to configurate the window titles, but the URL is used as a direct match.

**Comment by aisbergde** [comment]
yes, this works fine. But it is very hard to find if a user doesn't know about this feature.
if you go to "https://keepassxc.org/docs/" and you search for "auto" you will not find this part of the documentation. you need to search for "KPH", but no one will search for KPH if he doesn't know that this exists.
the question "How do I fill in additional values using String Fields?" will also not give this information.

The documentation should be extended a little bit with some words like "auto-type" in this section so a user can easy find this.

**Comment by phoerious** [comment]
Auto-Type and the browser extension are two entirely different things.

**Comment by aisbergde** [comment]
Yes, you are right. But for the user they are related. The goal is similar: entries from KeePassXC database should be used to automatically fill some fields on the website. And there are different ways. One way is autotype, another way are customer attributes.
