### ISSUE TITLE
global autotype - option to select the wanted item to use in case several items will match the matching conditions

### ISSUE THREAD

**Issue by aisbergde** [keepassxreboot/keepassxc#4053]
global "perform auto type" is fine if there is only one matching item.
But it is hard to use if there are several items matching the current web site.
For example I have several banking accounts but the login page is the same.
Currently: when I "perform auto type" the first matching item is used, but this could be the wrong item.

I suggest an option to provide a list of possible items in case several item will match. And the user should be able to select the wanted item.

**Comment by droidmonkey** [comment]
This is already the behavior. Make sure you are actually matching the window title.

**Comment by aisbergde** [comment]
this is not the behavior, otherwise I would not ask. 
Maybe this is a bug:
I have group "Deutsche Bank" containing the definition of the autoype sequence
in this group there are two similar entries for 2 different accounts
the url is the same, but some account specific entries are different, the content of some attributes.
If I visit the url and I use "perform autotype" I should get a list with my two accounts because both are matching, but I don't get this list, instead of the autotype is performed for the first account.

**Comment by aisbergde** [comment]
btw, when I use the KeePassXC-browser and I visit the url then I get the list of 2 accounts.
But when I use the "perform aoto-type" directly in the KeePassXC application, I don't get this list.

**Comment by droidmonkey** [comment]
You are confusing two completely different features. They do not use the same rules to match entries.

**Comment by droidmonkey** [comment]
There is already an issue for selecting an arbitrary entry if nothing matches: #429 

This is what the Auto-Type selection dialog looks like if multiple entries match (or if you enable "Always ask before performing Auto-Type". You can setup a trivial test by creating two entries titled "Notepad" or similar simple application. Then try to perform Auto-Type into that application:

![image](https://user-images.githubusercontent.com/2809491/71417545-e8d9d900-2633-11ea-94a6-224d2e76a84d.png)

![image](https://user-images.githubusercontent.com/2809491/71417549-ec6d6000-2633-11ea-9c48-46919b4b4d68.png)

You can also explicitly link window titles (with wild card support!) within each entry:

![image](https://user-images.githubusercontent.com/2809491/71417557-fc853f80-2633-11ea-867c-62af8a26a275.png)

**Comment by aisbergde** [comment]
The issue is, that it is not working as your describe. This is how it should work, but in my case it doesn't.
And it's not a good idea simply to close the issue instead of investigate why it is not working in this special case. And it is not working, otherwise I did not open the issue.

**Comment by droidmonkey** [comment]
There is no special case. You must explicitly define your entries to match the window title. If you don't do that they won't match.

You have not provided any information for which to replicate the behavior you experience.
