### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by vahidkhorasani** [keepassxreboot/keepassxc#4054]
It' ll be really awesome Keepassxc provides dark theme

**Comment by phoerious** [comment]
We take whatever your system's theme is. If that is dark, KeePassXC is dark also.

**Comment by vahidkhorasani** [comment]
Thank you Dear Janek
Because I use i3wm as my desktop environment I did not know how to change
theme in KeepassXC. I thought that it may have a dark them option in it's
setting menu.
