### ISSUE TITLE
Expand Donate page with Open Collective

### ISSUE THREAD

**Issue by keunes** [keepassxreboot/keepassxc#4055]
Hello,
I am preparing a round of donations to various FOSS projects. KeePassXC is on the list. It's the first time I'm doing this, and I think I'll mostly use Open Collective. I found [KeePassXC](https://opencollective.com/keepassxc) there as a project also, and it seems active. However, I'm not sure if it is indeed the right project - it's not listed anywhere on the project [website's Donate page](https://keepassxc.org/donate/).

So, my questions:
* Can I safely use the aforementioned Open Collective page? And/or is another method really preferred?
* Should the Donate page be update to mention Open Collective?

**Comment by droidmonkey** [comment]
Please do not use open collective. I hate it and have never received a dime from it

**Comment by phoerious** [comment]
Your build Agent license acquisition seems to have been approved.

**Comment by droidmonkey** [comment]
Approved but not paid out.

**Comment by phoerious** [comment]
Gracious. Sounds tedious.

**Comment by keunes** [comment]
> have never received a dime from it

Is that an issue with the Open Collective platform or with the 'fiscal host' Open Source Collective 501(c)(6)? (though I'm realising only now the two are probably linked)

> If you use Patreon the donations go to me, if you use PayPal they go to @phoerious.

Cool, thanks. And then we have GitHub's Sponsor option - would that be ok for you? I don't have Patreon.

**Comment by droidmonkey** [comment]
GitHub Sponsors will match any donation you give, which is awesome!

**Comment by keunes** [comment]
Good to know, thanks!

> Open Collective's process forces you to spend time/money in advance then hope that they will reimburse you for it based on your monthly contributions. It does not let you save up to make a large expenditure or operate on credit. Its actually very stupid model unless you have a few hundred dollars coming in a month.

Ok, that is really different from the impression you get as a regular user/potential donor. It seems to me that recurring donations add up to the balance, and that you can claim costs (e.g. for specific dev work, web services - so not depending on your contributions), which have to be approved by the organisation (which is also you, in this case), and which are [paid out on Thursdays](https://docs.opencollective.com/help/expenses-and-getting-paid/expenses). If the costs you claimed have been approved but not paid for over a week you should probably contact them to see what's going on. Seems to work for for example [Mastodon](https://opencollective.com/mastodon/transactions) - maybe they might be of help too.

But yeah, it does work based on a reimbursement model, so first costs and then the compensation (but then again, that's how it works often for companies also). On the other hand, as a supporter I like very much the transparency.

Anyway, some love will come to you through GitHub then if all goes well.

**Comment by droidmonkey** [comment]
Actually you are correct, I was wrong. Monthly contributions are added to the pot, we just never had any recurring ones (until recently) and I assumed there wasn't a pot. We currently have ~$200 in the pot, which is actually with the Open Source Collective (stored there). So yes, technically you can give through OpenCollective and it will work for us and I could technically submit an invoice for "my time" working on PR's or whatever. Or you can skip that silly song and dance and just donate directly to me or other lead devs. HEHE

**Comment by keunes** [comment]
Ok, I just actually checked GitHub and seems it _also_ isn't possible to do one-off donations :/ I could do the one through PayPal and the other through Open Collective, but I'll just do it in the latter for the both of you - sorry!

**Comment by rosmo** [comment]
Just dropping a note that the PayPal donation link is broken on the website :)

**Comment by droidmonkey** [comment]
Works just fine for me

**Comment by rosmo** [comment]
Strange, now it works for me as well. Was giving a "this organization's page is broken" or something similar.

**Comment by droidmonkey** [comment]
Done
