### ISSUE TITLE
Improve SSH Agent Documentation

### ISSUE THREAD

**Issue by CodingSpiderFox** [keepassxreboot/keepassxc#4056]
## Summary
The UI settings contain a view called "ssh-agent". I don't know what it does exactly.
Does it enable ssh-agent permanently when checked? 
Does it enable ssh-agent every time I start keepassxc? 
If so, does it shutdown ssh-agent if I close keepassxc?
Does it automatically load keys from keepass into ssh-agent?

![image](https://user-images.githubusercontent.com/25173078/71363945-0018b800-259b-11ea-9c63-61c115acc852.png)

## Desired Behavior
I want a label or a question mark icon with tooltip text containing some more info right under/next to the checkbox.

**Comment by droidmonkey** [comment]
Ping @hifi. This settings page needs a lot of love

**Comment by hifi** [comment]
#3801 adds some more content to the page so it isn't so naked but it should at least have a description somewhere about how it works for sure.

I'm not sure about the Auto-Type tab, all other "plugins" have their own page while Auto-Type is sort of "built-in" plugin if that could be said.

**Comment by hifi** [comment]
I'm going to add 2.6.0 as a target for general documentation that is available in bundled "User Guide" as there is currently no documentation at all for SSH Agent. This shall be the tracking bug.

**Comment by CodingSpiderFox** [comment]
Great!

**Comment by droidmonkey** [comment]
Being worked on with our AsciiDoc conversion
