### ISSUE TITLE
Clicking in the empty space of the groups section causes position in group to be reset

### ISSUE THREAD

**Issue by DoctorNefario** [keepassxreboot/keepassxc#4059]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Expected Behavior
When clicking in the empty part of the groups section it should do nothing

## Current Behavior
The currently selected entry will be reset to the first position

## Possible Solution
This might be caused by the "group selected" event firing even though no group was intentionally selected. 

## Steps to Reproduce
1. Select any entry that is not the first one
2. Click in the groups section below the folders

![example](https://user-images.githubusercontent.com/5243039/71459516-0194eb00-27fc-11ea-9185-1e1bf7b0bd66.gif)

## Context
This issue is not major, but it does annoy me whenever it happens. Every other application I use does nothing when a blank section of the app is clicked on, which lets me switch between them easily.

Operating system: Windows 10
CPU architecture: x64

**Comment by droidmonkey** [comment]
No longer a problem
