### ISSUE TITLE
Load custom attributes from CSV if there are any

### ISSUE THREAD

**Issue by TheZ3ro** [keepassxreboot/keepassxc#406]
## Expected Behavior

When loading a database from CSV file, load extra columns as custom attributes using the column name as attributes name.

## Current Behavior

Loads only the default attributes column (Title, Username, Password, URL, Notes)

Maybe we can assign this to @seatedscribe

**Comment by seatedscribe** [comment]
> Maybe we can assign this to @seatedscribe

Sure! I'll start asap.

**Comment by seatedscribe** [comment]
As we are on this, why not add the Entry/Notes input column as well?
I think it is a more thorough approach (and the GUI is a little more pleasant to look at :grin: )

**Comment by phoerious** [comment]
Whatever you think is useful.

**Comment by lumos0** [comment]
+1

**Comment by lumos0** [comment]
keepassXC can export to xml with custum attributes but can't import  custum attributes  (via xml) , little bit confusing...

**Comment by TertiaWorks** [comment]
+1

**Comment by droidmonkey** [comment]
#854 better tracks this request
