### ISSUE TITLE
TOTP secrets not saved if set up from within entry

### ISSUE THREAD

**Issue by MyGH001** [keepassxreboot/keepassxc#4060]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
TOTP secrets saved

## Current Behavior
[NOTE]: # ( Tell us what actually happens )
TOTP secrets not saved if set up from within entry

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1. Create new entry or open any previously created
2. From WITHIN entry do Set up for TOPT
3. Switch to Advanced(on the left) to see that "OTP" attribute NOT presented.
4. You still can get TOTP code fine as until close/reopen DB.
5. After reopen DB TOTP fully cleaned.

The only way it works correct(save secrets) if set up TOTP for entry from the main grid.
1. Select entry (not drill down)
2. Setup TOPT via right click menu or main menu.

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.5.1
Revision: 0fd8836

Qt 5.13.1
Debugging mode is disabled.

Operating system: macOS 10.15
CPU architecture: x86_64
Kernel: darwin 19.2.0

**Comment by MyGH001** [comment]
<img width="849" alt="Screen Shot 2019-12-25 at 11 47 24 PM" src="https://user-images.githubusercontent.com/36414348/71459814-40cd2880-2777-11ea-9877-d8e907ef8258.png">
<img width="849" alt="Screen Shot 2019-12-25 at 11 49 00 PM" src="https://user-images.githubusercontent.com/36414348/71459820-462a7300-2777-11ea-8e3a-cb391764fffa.png">
<img width="849" alt="Screen Shot 2019-12-25 at 11 50 15 PM" src="https://user-images.githubusercontent.com/36414348/71459827-4c205400-2777-11ea-878e-84fb128c9c22.png">
<img width="849" alt="Screen Shot 2019-12-25 at 11 50 42 PM" src="https://user-images.githubusercontent.com/36414348/71459834-517d9e80-2777-11ea-8e6e-94ecc2706b99.png">
<img width="815" alt="Screen Shot 2019-12-25 at 11 51 05 PM" src="https://user-images.githubusercontent.com/36414348/71459839-55a9bc00-2777-11ea-9a48-d8b271a62688.png">

After close and reopen DB
<img width="815" alt="Screen Shot 2019-12-25 at 11 51 57 PM" src="https://user-images.githubusercontent.com/36414348/71459844-5a6e7000-2777-11ea-8dc8-809bb3b6f81d.png">

**Comment by MyGH001** [comment]
Same behavior on Windows 10, so seems common issue.

**Comment by droidmonkey** [comment]
I could have sworn to have tested this when I enabled the menu actions while editing an entry. This is an unfortunate side effect.

**Comment by MyGH001** [comment]
Right, just checked. If push "Cancel" it saves OTP, too complex pattern I would say for end users ). Might be better either disable TOTP set up within entry or make behavior consistent(which would be preferable).

**Comment by droidmonkey** [comment]
Its a bug, not intentional pattern

**Comment by feuerbach** [comment]
Just hit this as well. Seems like a very dangerous bug — if the user does this and does not save recover code or the secret key, they would be locked out of their account.

**Comment by droidmonkey** [comment]
I agree will fix

**Comment by doczkal** [comment]
I hit this bug as well and it will cost me 5€ to get access to the account again because there are no recover codes or secret keys available...

**Comment by densha** [comment]
@droidmonkey Any update on this? I can confirm the same issue happens on KeePassXC 2.5.4 on Linux Mint.

**Comment by droidmonkey** [comment]
Yeah I need to fix this for 2.6
