### ISSUE TITLE
"Hide passwords" option on main view keeps getting reset to show passwords

### ISSUE THREAD

**Issue by afontenot** [keepassxreboot/keepassxc#4062]
Every now and then Keepassxc will start showing all of my passwords in the main view. I right click on the column headers to check "hide passwords", but the problem eventually comes back.

## Expected Behavior
I think the obvious, sane default is not to show the user's passwords in the main view. I'm not sure why it's even an option, but at any rate I expect (a) Keepassxc to hide passwords by default, and (b) Keepassxc to respect my setting to hide the passwords and not change it.

## Current Behavior
For a while, Keepassxc doesn't show my passwords in the main view. Then eventually I will notice that they're visible again.

## Possible Solution
Obviously this is not a bug that can be easily reproduced, that's the nature of the problem. I just now came up with one guess: the only keyboard shortcuts I use in this program are ctrl-f, ctrl-c, and ctrl-shift-v. It's *possible*, but not certain, that I'm doing this to myself by sometimes accidentally hitting ctrl-shift-c instead of ctrl-c.

If that's in fact what is happening, I think it's crucial to change this keyboard shortcut as soon as possible. It's very dangerous to have the keyboard shortcuts for "show all my passwords to anyone looking over my shoulder" and "copy this one password into the clipboard" so similar. 

A security setting to just disable anything that could result in passwords becoming visible might go a long way. A "good enough" alternative for me would be a way to change or disable keyboard shortcuts, but other people are going to run into this problem. This is probably what happened to this user as well: https://github.com/keepassxreboot/keepassxc/issues/3452

## Debug Info
KeePassXC - Version 2.5.1
Revision: 0fd8836

Qt 5.14.0
Debugging mode is disabled.

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 5.4.6-arch1-1

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.5

**Comment by vvrein** [comment]
Same thing
Video of a bug
https://site.tort.icu/bin/b60ow3xh.mp4
DB from video, pass: 1111
https://site.tort.icu/bin/test.kdbx

QT_QPA_PLATFORM=xcb DISPLAY=:1 keepassxc --debug-info
KeePassXC - Version 2.5.1-snapshot
Build Type: Snapshot
Revision: ed0b768

Qt 5.14.0
Debugging mode is disabled.

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 5.4.6-zen3-1-zen

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.5

**Comment by droidmonkey** [comment]
Almost 100% positive you are pressing Ctrl+Shift+C

**Comment by afontenot** [comment]
I agree that that's quite likely. The reason I still filed this report was that I was actually more than halfway through writing it when the possibility occurred to me, and the only reason it did was that I read another bug report by a user who probably had the same problem.

I think this is likely to confuse many users, and worry anyone who isn't able to figure out why all their passwords are suddenly visible. Consider this bug report a request to change (or otherwise provide some mechanism for changing) this keyboard shortcut.

**Comment by droidmonkey** [comment]
The keyboard shortcut wont be changed, but we have an issue to allow for customizing the keyboard shortcuts. See #2689

**Comment by afontenot** [comment]
> The keyboard shortcut wont be changed, but we have an issue to allow for customizing the keyboard shortcuts. See #2689

Is there some way of warning new users that it's trivial to accidentally make all their passwords visible while someone is looking over their shoulder by adding a single modifier to the most common keyboard combination? I feel sure other people have run into this problem before, and it's almost certain to confuse anyone who doesn't expect it.
