### ISSUE TITLE
GPG integration

### ISSUE THREAD

**Issue by StevenDoesStuffs** [keepassxreboot/keepassxc#4064]
[TIP]:  # ( Provide a general summary of the feature in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Summary
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
It'd be nice if we could secure the database with gpg. 

## Desired Behavior
[NOTE]: # ( Tell us how the new feature should work, be specific )
I have a gpg smartcard (nitrokey start). Ideally, I'd be able to secure the database using it. As in each access of a password or anything required having the smartcard decrypt it. 

## Possible Solution
[NOTE]: # ( Not required, but suggest ideas on how to implement the addition or change )
There should be libraries for interfacing with GPG (I believe). 

Also, this isn't quite the same #255 or #1210 because it's about securing individual entries, which I admit is a bit overkill, but it's desired because it almost emulates the behavior of having the database on the key itself.

**Comment by droidmonkey** [comment]
We dont encrypt individual entries. That would be a huge change to how the app operates and breaks cross compatibility.

**Comment by StevenDoesStuffs** [comment]
Ah ok. That makes sense.

**Comment by gynet** [comment]
@StevenDoesStuffs I wrote some thoughts on [KeeWeb](https://github.com/keeweb/keeweb/issues/1538)
