### ISSUE TITLE
Yubikey is not detected if already plugged

### ISSUE THREAD

**Issue by ibahnasy** [keepassxreboot/keepassxc#4065]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
A yubikey should be detected if it's plugged in.

## Current Behavior
[NOTE]: # ( Tell us what actually happens )
The yubikey is not detected if it's already plugged in before launching the KeePassXC.

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1. Insert yubikey
2. Launch KeePassXC
3. Try to unlock the database or 'refresh' for the keys.

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.5.1

Operating system: Arch Linux
CPU architecture: 64
Kernel: 5.4.6

**Comment by ovz93br43v7** [comment]
I have the same issue on elemetaryOS (ubuntu linux). But as long as the yubico personalisation tool is installed, the yubikey is detected by keepassXC everytime. 
If I uninstall the personalisation tool keepassXC isn't able to find the yubikey anymore.

**Comment by droidmonkey** [comment]
Are you using the snap version?

**Comment by AsavarTzeth** [comment]
Just thought I'd share my quick conclusion.

This has to do with the Yubikey udev rules. Some distribution types (such as Flatpak) can't ship them, or rather can't make them available to the host. It works fine if the user installs the rules manually, usually via the yubikey-personalization (libyubikey-udev on Ubuntu) package.

I'm curious, is this an issue with snaps as well? A quick search seems to reveal that [hotplug support](https://snapcraft.io/docs/hotplug-support) exist, but it is limited and experimental.

See the Flathub issue linked by @ovz93br43v7 for a more detailed explanation.

**Comment by droidmonkey** [comment]
Snaps support raw usb access with a permission enabled by the user (although only root can grant it).

**Comment by AsavarTzeth** [comment]
I see, that is good to know. However that isn't really what I asked.

What I am asking is if snap also installs the required udev rules? or in other words, will the system make use of any udev rules installed in a snap filesystem?

If not, it won't matter if permission is granted, since the device won't be recognized. That is unless the user, as mentioned, installs the rules themselves.

*Flatpak also allows raw device access, but installing udev rules is another matter.*

**Comment by droidmonkey** [comment]
If I remember correctly the snap version still requires the libykpers library to be installed.

**Comment by AsavarTzeth** [comment]
Then we may very well have a common issue. I install libykpers inside the Flatpak container, but you still need to install it (or add the udev rules manually) on the host system.

**Comment by TheRojam** [comment]
great! smb is having nearly the sameproblem as i do.
my specs

KeePassXC - Version 2.5.2
Revision: 62cda9d

Qt 5.14.0
Debugging mode is disabled.

Operating system: macOS Mojave (10.14) -- macOS 10.14.6 (18G1012)
CPU architecture: x86_64
Kernel: darwin 18.7.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
 libgcrypt 1.8.5

But let me tell you smt: it worked on my windows machine w/ keepass 2.5.1...

**Comment by ibahnasy** [comment]
Any workaround or planned solution for this issue?

**Comment by droidmonkey** [comment]
Just unplug and replug the Yubikey

**Comment by ibahnasy** [comment]
But other programs don't have that issue like Firefox on Linux!

**Comment by phoerious** [comment]
Firefox is using a different mode of they key.

**Comment by ibahnasy** [comment]
Alright, then I hope there is software solution to avoid wear out from re-plugging frequently.
You may check with the Yubikey's developer support on that if you suspect it's from their lib!
Thanks!

**Comment by droidmonkey** [comment]
On our end the only thing we are doing is asking the Yubikey library whether a key is available, and if so which slots support challenge-response. If the library chokes on step 1 for whatever reason internally then there is not much we can do. It could even be that the particular version of libykpers you have installed is wildly out of date and this is already fixed in a current released version.

**Comment by TheRojam** [comment]
> great! smb is having nearly the sameproblem as i do.
>
> Operating system: macOS Mojave (10.14) -- macOS 10.14.6 (18G1012)
> CPU architecture: x86_64
> Kernel: darwin 18.7.0

I've upgraded last weekend to catalina and know what it works now
> Operating system: macOS 10.15
> CPU architecture: x86_64
> Kernel: darwin 19.2.0

**Comment by auwsom** [comment]
> Just thought I'd share my quick conclusion.
> 
> This has to do with the Yubikey udev rules. Some distribution types (such as Flatpak) can't ship them, or rather can't make them available to the host. It works fine if the user installs the rules manually, usually via the yubikey-personalization (libyubikey-udev on Ubuntu) package.
> 
> I'm curious, is this an issue with snaps as well? A quick search seems to reveal that [hotplug support](https://snapcraft.io/docs/hotplug-support) exist, but it is limited and experimental.
> 
> See the Flathub issue linked by @ovz93br43v7 for a more detailed explanation.

@AsavarTzeth thanks so much for that tip! While just leaving the personalization tool open doesnt work for me on Kubuntu Jelly, at least I can click the tool window and click back to KPxc and it seems to work. I'm not using the Snap or Flatpak, and this only happens with KPxc, other apps are fine when I tap the yubikey after it being idle. Any other insight into a workaround using udev rules when using the Ubuntu apt installation? Thanks

**Comment by auwsom** [comment]
Also, I noticed the yubikey is typing letters in the background somewhere, because if I tap it and then click the pers-tool window, and click back to KPxc, it types out the last half of the static password. That means udev is probably working, its just that KPxc is not using/recognizing the output from the key.
