### ISSUE TITLE
Please support Tor Browser and onion addresses

### ISSUE THREAD

**Issue by BillDietrich** [keepassxreboot/keepassxc#4067]
## Summary
Please make KeePassXC "know" what application is the Tor Browser and "know" that entries containing "onion" addresses should be associated with that application.

## Desired Behavior
Database can contain some entries that are normal clearnet addresses (www.whatever) and others that are onion addresses.  If I select an entry with a clearnet address and do "open URL", it finds/launches my normal browser and opens the URL.  If I select an entry with an onion address and do "open URL", it finds/launches my Tor Browser and opens the URL there.

**Comment by droidmonkey** [comment]
You need to add the tor URI handler to the url, not sure what it is but maybe tor:// or onion://

This signals to the operating system to use the application associated with the uri. We don't pick the application.

**Comment by BillDietrich** [comment]
tor:// and onion:// protocols do nothing in my KeePassXC 2.5.1 on Linux Mint 19.3 Cinnamon.  Also can't find any GUI option to add a URI handler; I guess I have to edit a config file or put overrides in individual entries.  The cmd:// protocol does work.

**Comment by phoerious** [comment]
cmd is hardcoded. Everything else is handed to xdg-open.

**Comment by droidmonkey** [comment]
You can add an xdg mime type following these instructions: https://askubuntu.com/a/739199

**Comment by meglio** [comment]
It would make sense to have a clean link in a url field, the workarounds are kind of ugly.

May I suggest to add a setting "Open .onion links in..." to the "Browser Integration" tab in the Settings, and just let the user choose their preferred browser application?
