### ISSUE TITLE
Unable to select 1password .opvault file for import

### ISSUE THREAD

**Issue by sublocale** [keepassxreboot/keepassxc#4069]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

Import existing 1password.opvault file into KeepassXC 2.5.1

## Current Behavior
[NOTE]: # ( Tell us what actually happens )

Whether choosing `import for 1password` from the welcome dialog or selecting from `Database > Import > 1password vault...` the opvault file is unable to be selected.

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )

Adding a `.txt` extension to the `1password.opvault` file allows it to be selected and imported.  

## Debug Info
KeePassXC - Version 2.5.1
Revision: 0fd8836

Qt 5.13.1
Debugging mode is disabled.

Operating system: macOS 10.15
CPU architecture: x86_64
Kernel: darwin 19.3.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
 libgcrypt 1.8.5

**Comment by droidmonkey** [comment]
There is a file? We support importing the directory.

**Comment by sublocale** [comment]
You are correct, 1password.opvault is a directory but presents itself like a single file just like .app or any number of other packages on macos

For this bug the file/directory is 'grayed out' until it has '.txt' or any other extension appended. Once the new extension is added the 1password.opvault file now looks and behaves as a directory and can be successfully imported.

**Comment by droidmonkey** [comment]
Weird, this must be a silly Mac "feature"

**Comment by cmroanirgo** [comment]
Can confirm. On MacOS (with 1Password installed), the directory looks and acts like a file. This is not uncommon on a mac. 
Normally, in Finder you can Right Click "Show Package Contents" to delve into it, but in KPXC it's greyed out unless you rename it as OP described. (I used .dir extension.... it can be *anything*)

**Comment by ChristlMett** [comment]
Hi, could you please specify which version of 1Password you're using? I tried to import from 1PW v. 6.8.9 and the file was readable, but got error that folder ".opvault/default" doesn't exist and therefore KPXC couldn't find a db instance to import :-(
Import via csv would a) ignore all "special" stuff like 2FA etc. and didn't even work for simple passwords when I tried (completely mixed up all entries). Would really like to migrate to KPXC, but would take forever to copy hundreds of logins manually...

Thanks!
 Chris

**Comment by sublocale** [comment]
Looks like the same version as you. 

1Password 6 - Version 6.8.9 (689001)

**Comment by nunux13** [comment]
Guys, it take time to figure out how this work:

First: Don't try to export .1pif file, it's not what you need.
Second: To get opvault file from 1 password, you can use Preferences/Synchronise/Folder
Third: you have to rename the opvault file to make it a folder: 
mv 1Password.opvault ../1Passwordvault

Then select 1Passwordvault as Folder to import, and TADA !

I have still an issue with 2nd or 3rd password stored on the same sheet. Look like it' imported into "Advance" section but named "Protected"

Hope that can help others like me, using also 1 Password 6 - Version 6.8.9

**Comment by markus-seidl** [comment]
> Weird, this must be a silly Mac "feature"

Well, other operating systems have their own "file format". Mac has a directory, others have zipped XMLs and others just invent their own proprietary thing.
I'm glad it's actually quite simple and not an additional format.

**Comment by droidmonkey** [comment]
I have no idea what you are talking about. The opvault is a directory on every operating system with multiple files underneath it. Apparently in macOS 1password registered this extension to make it act like a package with is a fake file that is really a directory. So no, it's not any simpler.

**Comment by MLS-EA69** [comment]
Having same issues as above- can't import OP vault.
When in .opvault form Keepassxc can not select it (option greyed out).

When changing file to .txt (or anything else)  I get this response:
Read Database did not produce an instance
Directory .opvault/default must exist

or
Read Database did not produce an instance
Unable to decode masterKey: Malformed OpData01 due to a failed HMAC

I know correct OP vault password as I'm able to sync back to app database
1Password 7
Version 7.6 (70600006)
Mac App Store

**Comment by MLS-EA69** [comment]
Update- I was able to import the OPVault by appending .txt to the OPVault file.
Not sure why couldn’t before, doing same.

Everything is working great. 

Thanks for making Keepass XC an awesome PW manager! 
Will definitely contribute $ to help keep it going.

**Comment by osenvosem** [comment]
Still doesn't work. The "open" button is greyed out. Adding/renaming the extension to .txt changes nothing.

<img width="912" alt="Screenshot 2021-11-04 at 19 35 15" src="https://user-images.githubusercontent.com/6762673/140380669-8c31a2ac-50d2-4121-b3ef-06b31fea46b1.png">

**Comment by andredami** [comment]
Might be usefull, I had the exact same HMAC error. I finally realized I had to remove from my password any special characters and the import worked like a charm.

> Having same issues as above- can't import OP vault. When in .opvault form Keepassxc can not select it (option greyed out).
> 
> When changing file to .txt (or anything else) I get this response: Read Database did not produce an instance Directory .opvault/default must exist
> 
> or Read Database did not produce an instance Unable to decode masterKey: Malformed OpData01 due to a failed HMAC
> 
> I know correct OP vault password as I'm able to sync back to app database 1Password 7 Version 7.6 (70600006) Mac App Store

**Comment by droidmonkey** [comment]
There is a known Qt bug that causes unicode and extended ascii characters to not enter correctly when the password field is in hidden mode (the dots).
