### ISSUE TITLE
Deleting (moving to bin) an entry should produce an atime or mtime change

### ISSUE THREAD

**Issue by Yanestra** [keepassxreboot/keepassxc#4070]
When you delete an entry, it is merely moved to the "bin" but remains completely unchanged. That makes it impossible to find out WHEN it has been moved there.
This behavior makes it impossible to find out how old these entries are (how long ago they have been deleted). An entry could be created a long time ago, but having been deleted quite recently.

## Summary
There is a need for deletion time field or, alternatively, at least atime or mtime should be stamped with the current time on deletion. In the latter case, it would make sense to write protect deleted entries (keeping them unchanged except for final deletion).

## Desired Behavior
A deletion should result in an appropriate time field being stamped.

## Possible Solution
[NOTE]: # ( Not required, but suggest ideas on how to implement the addition or change )

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )

**Comment by droidmonkey** [comment]
There is no differentiation between moving an entry between folders and "recycling" an entry. It's just moved to the special recycling group. Since the entry itself didn't change at all I do not endorse changing the mtime. This is not the behavior on any operating system I've used either.

**Comment by Yanestra** [comment]
Windows (example) stores the deletion date in the trashbin database. It needs the date to do regular cleanups. NTFS doesn't store a deletion date because deleted items are not intended to be recovered, except by shadow copy.

**Comment by droidmonkey** [comment]
Besides knowing how long ago an entry has been recycled, whats the use case? Why do you care about this time?

**Comment by Yanestra** [comment]
It was suggested as a possible workaround if extension of the date fields could not be considered for compatibility reasons. BTW: shouldn't deletion be considered a "touch"? I mean, using common sense, not operating system knowledge.

**Comment by droidmonkey** [comment]
This can be done, just was wondering what the utility of spending time doing it is.
