### ISSUE TITLE
'Failed to open key file: No such file or directory' error with file available

### ISSUE THREAD

**Issue by dkwo** [keepassxreboot/keepassxc#4076]
My password database is encrypted with password+keyfile.
If I insert the USB stick, wait a few secs and then try to open the database, it gives the error
`Failed to open key file: No such file or directory`
If instead I first open the USB folder with Nautilus and then try to unlock it in keepass, it works fine.
So I believe this is a bug of keepass.
I'm with version 2.5.1 on Arch Linux.

**Comment by droidmonkey** [comment]
Sounds like your usb stick isn't auto mounting properly.

**Comment by dkwo** [comment]
You are right.
