### ISSUE TITLE
Merge from database overwrites Browser Integration Stored Keys in Database settings

### ISSUE THREAD

**Issue by jharvell** [keepassxreboot/keepassxc#4077]
When merging from another database that has one stored key/value pair to the existing database that has a key/value pair with a different key, the end result is that the merged database has the single key/value pair from the "from" database.

## Expected Behavior
I expect the set of keys in the merged database to be the union of the sets of keys from the from and to databases.  When the from and to databases both have the same key but with different values, either the user should be prompted to choose which value or the value changed more recently should be the value in the merged database

## Current Behavior
The set of keys in the merged database is equal to the set in the from database.

## Possible Solution
described in expected behavior

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1. start with identical databases on two different machines where the database settings under Browser Integration has no stored keys
2. connect to keepassxc using the keepassxc-browser plugin on machine A.  when prompted to give a name for the connection, use the value "A"
3. save the database on machine A
4. connect to keepasxc using the keepassxc-browser plugin on machine B.  when prompted to give a name for the connection, use the value "B"
5. save the database on machine B
6. transfer a copy of the database from machine A to machine B
7. with the machine B database opened in keepassxc on machine B, select Database->Merge from database...  In the file chooser, selec the copy of the database from machine A described in step 6
8. observe that the resulting merged database has only key A in Database->Database settings under Browser Integration.  key B is missing

## Context
I use git to manage copies of my database on different machines.  When I make changes to a database on one machine (and not on the other), I update my copy  on the other machine by using git to pull the changes.  If I make changes on two different machines (now much more common with keepassxc-browser saving settings in the database related to which entries to use for which URLs), I make commits on both machines.  To merge tha, I do a git merge --no-checkin -s ours.  But before I check in the result of the git merge, I perform a "Database->Merge from database...." and specify a copy of the remote machine's copy (i.e. the "theirs" copy) of the database.  This allows me to actually merge the two copies and to also correctly reflect that merge in git.

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.5.1
Revision: 0fd8836

Libraries:
- Qt 5.12.3

Operating system: Gentoo Linux and Windows 10 (from database of the merge is Gentoo Linux)
CPU architecture: x86_64 on both
Kernel: linux 5.1.15

Enabled extensions: (in French because that's my system language)
- Saisie automatique (this is auto-type)
- Intégration aux navigateurs (this is browser integration)
- Agent SSH
- YubiKey
- Intégration au Secret Service

**Comment by droidmonkey** [comment]
You should use unique names for all your browser connections. Kdbx merge function prefers the most recent change, always. There is an open issue to allow for different merge strategies and to "preview" merge. Those cover all cases, not just this specific one.

**Comment by jharvell** [comment]
@droidmonkey I did use different keys for the two browser connections but the merge still clobbered one.

**Comment by droidmonkey** [comment]
Good to know! This may be a bug in the custom data merge code.

**Comment by derMart** [comment]
Exact same problem here. This is sadly quite annoying, one has to readd browsers all the time after a merge.

**Comment by varjolintu** [comment]
I'll try to fix this for 2.6.0.

**Comment by rocketraman** [comment]
This also happens when using KeeShare. I have a main database D1 with Browser Integration keys A and B. I a KeeShare "Import from" KeeShare entry for database D2 (which also contains integration key B).

After an update of database D2, the browser integration keys in D1 are now just left with B.

Furthermore, if all the browser integration keys are deleted from D2, then after any save of D2, D1 loses its browser integration keys completely as well.

**Comment by droidmonkey** [comment]
Please open a new issue regarding KeeShare.

**Comment by rocketraman** [comment]
> Please open a new issue regarding KeeShare.

Ok, I'll re-open and update #4684 .
