### ISSUE TITLE
On some Websites ALL Database entrys are shown

### ISSUE THREAD

**Issue by MegaV0lt** [keepassxreboot/keepassxc#4078]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
When the url is mached or partly only that entrys shold be selectet

## Current Behavior
[NOTE]: # ( Tell us what actually happens )
On some sites all entrys in the database are offered
![Auswahl_058](https://user-images.githubusercontent.com/2804301/71690255-717b1680-2da4-11ea-8d3f-50e810907749.png)

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )
No idea what can be the cause

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1. go to "https://sso.myfritz.net/"
2. Select the username field
3. all entrys of the db are offered, so a useful selection is not possible

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )
Entry in db
![Auswahl_059](https://user-images.githubusercontent.com/2804301/71690293-86f04080-2da4-11ea-909e-7370dbfda684.png)

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.5.1
Revision: 0fd8836

Libraries:
-  libgcrypt 1.8.1

Operating system: Linux Mint 19.3
CPU architecture:  x86_64
Kernel: 5.0.0-37-generic

Enabled extensions:
- Auto-Type
- Browser-Integration
- SSH-Agent
- KeeShare (bestätigtes und unbestätigtes Teilen)
- YubiKey
- Secret-Service-Integration

**Comment by droidmonkey** [comment]
Fixed in 2.5.2
