### ISSUE TITLE
Not exiting on close of main window

### ISSUE THREAD

**Issue by dpb657** [keepassxreboot/keepassxc#4079]
## Expected Behavior
When I click on the close X in the main window I expect that the window closes and the application exits. 

## Current Behavior
The window closes and the application no longer appears active in the task bar.

## Possible Solution
None available

## Steps to Reproduce
Not sure why this happens but it is not consistent.
1.
2.
3.

## Context
I end up opening the task manager and manually ending the KeepassXC process. 

Note:
Previous bug report was closed.

## Debug Info
KeePassXC - Version 2.5.1
Revision: 0fd8836

Qt 5.13.1
Debugging mode is disabled.

Operating system: Windows 10 (10.0)
CPU architecture: x86_64
Kernel: winnt 10.0.18363

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.5

**Comment by droidmonkey** [comment]
Do you have the setting: "Minimize instead of app exit" enabled?

**Comment by dpb657** [comment]
No the application is not available from the task bar either.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by droidmonkey** [comment]
I do not observe this behavior on Windows 10 at all

**Comment by dpb657** [comment]
I have been in support for several decades and I understand the difficulty of an intermittent problem but, that is what I have. It may be related to KeepassXC being open for a long time or that the DB is on Google Drive but I have not been able to determine a way to make it repeatable on demand.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by droidmonkey** [comment]
If you can find a way to reproduce it please let us know. A screenshot of your settings would be helpful to determine the exact state of the application.

**Comment by Rainyan** [comment]
For the record, I'm experiencing this exact issue too, with a Windows 10 64-bit system. It's been happening on both 2.5.1 and 2.5.2 releases downloaded from this repo's releases page, but I'm fairly certain it was not happening before that (version 2.5.0 and older).

Unfortunately, I can't consistently reproduce it either; most of the time the app terminates and re-opens as expected, but rarely (a couple times a week), it remains open in the background, and I have to kill the process via task manager before I can successfully re-launch the app.

I've also attached my settings screen below, in case it's helpful.

![kpxc252_settings](https://user-images.githubusercontent.com/6595066/71814295-9dd4b280-3084-11ea-995f-4e578f8face1.png)

**Comment by droidmonkey** [comment]
Thank you for this! Can you enable the system tray icon for a while to see if the problem persists?

**Comment by Rainyan** [comment]
Just one monitor and no docking station on my end. I'll enable the system tray icon and report back if the problem persists.

**Comment by Rainyan** [comment]
I've ran into the issue again with the system tray enabled.

When this happens, the icon remains in the system tray, but it no longer reacts to mouse right or left clicks in any way. Hovering the mouse over the icon still highlights it, though (cursor not captured in this screenshot):
![hover_ex](https://user-images.githubusercontent.com/6595066/71974963-8aa81b00-321b-11ea-854c-d320375793a3.png)

Here's the "hung" process visible in Windows task manager:
![zombie1](https://user-images.githubusercontent.com/6595066/71975026-b1fee800-321b-11ea-9571-3deb05077971.png)

Trying to re-launch, the new process briefly flashes in the process list and then terminates (presumably because "Start only a single instance" is ticked in the settings):
![zombie2](https://user-images.githubusercontent.com/6595066/71975065-c0e59a80-321b-11ea-8d08-a2c53004b062.png)

Not sure how much this helps, as I still have no idea how to reproduce the issue. I could see about compiling with debug flags and attaching a debugger when this next happens, if that would be helpful.

**Comment by dpb657** [comment]
I would not see the task bar icon behavior in this way that since I have KeepassXC pinned to the task bar. What I did see was that I could not start a new KeepassXC using the task bar icon or any other method until using the task manager to end the KeepassXC process.

Darryl Baker, GSEC  (he/him/his)
Sr. System Administrator
Distributed Application Platform Services
Northwestern University
1800 Sherman Ave.
Suite 6-600 – Box #39
Evanston, IL  60201-3715
darryl.baker@northwestern.edu<mailto:darryl.baker@northwestern.edu>
(847) 467-6674

**Comment by XyjpcpXNF6UGaQ** [comment]
@dpb657 almost exactly the same issue, including the additional details in your posts, and as detailed in the closed #4143, on Windows 7 x64.

**Comment by dpb657** [comment]
Your reply is terse beyond my ability to understand what you are trying to say. You reference a previously closed ticket that has no solution.
What is the solution, work around, or what more data do you need to fix this? The last time I saw this issue I captured a dump of the process if that will help.

Darryl Baker, GSEC  (he/him/his)
Sr. System Administrator
Distributed Application Platform Services
Northwestern University
1800 Sherman Ave.
Suite 6-600 – Box #39
Evanston, IL  60201-3715
darryl.baker@northwestern.edu<mailto:darryl.baker@northwestern.edu>
(847) 467-6674

**Comment by XyjpcpXNF6UGaQ** [comment]
My apologies, - I was not intending to answer your post; I was simply trying to add a reply to the effect that I, too, have the same issue and as already (clearly) detailed by yourself. I have also avoided the @ reference, this time, in order to avoid further confusion.

**Comment by SmoochiesBoss** [comment]
I have the same issue. +1

**Comment by droidmonkey** [comment]
@dpb657 can you send the dump to team@keepassxc.org

**Comment by wombat01** [comment]
This problem still persists. When I try to quit the application. (Exit app from menu) does not terminate and stays in the toolbar.

The application cannot be terminated even through the task manager, it does not solve logout, hibernation, etc. It is necessary to restart the PC.

I have the lastest snapshot from 2020-04-01.

**Comment by droidmonkey** [comment]
The KeePassXC.exe process does not appear in your task manager screenshots. Am I missing something?

**Comment by wombat01** [comment]
Yes, I quit the application, it hangs in the toolbar, and when I try to kill the process it is not in the task manager. It is therefore necessary to restart the PC.

**Comment by droidmonkey** [comment]
If the process is not in the taskmanager then it is not running. Sometimes taskbar icons stick around when processes are force killed, usually hovering over the icon causes it to disappear.

**Comment by wombat01** [comment]
No, the "process" stays somewhere and the application cannot be start (eg when upgrading) until the PC restart.

**Comment by Rainyan** [comment]
I don't have much to add, but can confirm this is still happening for me as well. Seems rarer, but I end up having to kill the process from Task Manager after quitting the app maybe once or twice a week. Using currently latest version 2.5.3.

**Comment by wombat01** [comment]
If I could kill, I have no problem, but I have no process, I have to restart.

**Comment by dpb657** [comment]
Let me add a bit. The keepass process remains but it looks more like a service than an application after closing out of it. What I mean is rather than being at the top of the task manager window, where it is before closing out of it, keepass is listed down with the services like keepass-proxy and Google Chrome plugins.

Darryl Baker, GSEC  (he/him/his)
Sr. System Administrator
Distributed Application Platform Services
Northwestern University
1800 Sherman Ave.
Suite 6-600 – Box #39
Evanston, IL  60201-3715
darryl.baker@northwestern.edu<mailto:darryl.baker@northwestern.edu>
(847) 467-6674

**Comment by wombat01** [comment]
I only have this, what other process is used? When it appears described.

![image](https://user-images.githubusercontent.com/20426629/78158024-098aa980-7441-11ea-8f42-0d3f581b3851.png)

**Comment by droidmonkey** [comment]
Go to the details tab of the task manager and sort by process name

**Comment by dpb657** [comment]
Try going to the detail view and alphabetize the process list. I find a process called keepassxc which I can end. Then I can start a new KeepassXC application.

Darryl Baker, GSEC  (he/him/his)
Sr. System Administrator
Distributed Application Platform Services
Northwestern University
1800 Sherman Ave.
Suite 6-600 – Box #39
Evanston, IL  60201-3715
darryl.baker@northwestern.edu<mailto:darryl.baker@northwestern.edu>
(847) 467-6674

**Comment by wombat01** [comment]
Yes, I also only have KeePassXC.exe, so better when closing the application, kill this process from task manager. If the GUI cannot be terminated correctly under certain circumstances.

**Comment by droidmonkey** [comment]
It would be incredibly helpful if you can isolate the circumstances that cause the failure to close. The next time it happens try to enumerate exactly what you were doing prior to witnessing it.

**Comment by wombat01** [comment]
Ok, but it will be difficult ;-) I can't think of any context.

**Comment by dpb657** [comment]
Would it be helpful if I submit a dump of the keepassxc process in this state of limbo?

Darryl Baker, GSEC  (he/him/his)
Sr. System Administrator
Distributed Application Platform Services
Northwestern University
1800 Sherman Ave.
Suite 6-600 – Box #39
Evanston, IL  60201-3715
darryl.baker@northwestern.edu<mailto:darryl.baker@northwestern.edu>
(847) 467-6674

**Comment by droidmonkey** [comment]
Only if you are running the snapshot build. Be aware of you have your personal database unlocked then the dump will contain your passwords.

**Comment by dpb657** [comment]
That does suck. I’m not running a snapshot build, but I can reliably duplicate the problem. It seems the longer I have the application running the more likely it is to leave the process behind that I have to kill the remaining process.

Darryl Baker, GSEC  (he/him/his)
Sr. System Administrator
Distributed Application Platform Services
Northwestern University
1800 Sherman Ave.
Suite 6-600 – Box #39
Evanston, IL  60201-3715
darryl.baker@northwestern.edu<mailto:darryl.baker@northwestern.edu>
(847) 467-6674

**Comment by droidmonkey** [comment]
You can run a snapshot build easily by downloading one from https://snapshot.keepassxc.org

**Comment by dpb657** [comment]
It wasn’t running the snapshot that was the issue, it was not sharing my unencrypted DB.

Darryl Baker, GSEC  (he/him/his)
Sr. System Administrator
Distributed Application Platform Services
Northwestern University
1800 Sherman Ave.
Suite 6-600 – Box #39
Evanston, IL  60201-3715
darryl.baker@northwestern.edu<mailto:darryl.baker@northwestern.edu>
(847) 467-6674

**Comment by dpb657** [comment]
Thought about this just after hitting send on the last message. If I lock the database before closing the program is the data still in the clear? Isn’t keeping the database in memory in the clear a security issue anyway?

Darryl Baker, GSEC  (he/him/his)
Sr. System Administrator
Distributed Application Platform Services
Northwestern University
1800 Sherman Ave.
Suite 6-600 – Box #39
Evanston, IL  60201-3715
darryl.baker@northwestern.edu<mailto:darryl.baker@northwestern.edu>
(847) 467-6674

**Comment by droidmonkey** [comment]
Yes we zero out the in memory database when it gets locked.

**Comment by wombat01** [comment]
In the morning I tried reproducible and the same problem. I dare say it's somehow related with sleep mode.

**Comment by dpb657** [comment]
Do you still want a dump of the hung remnant task? I can install a snapshot version if you do.

Darryl Baker, GSEC  (he/him/his)
Sr. System Administrator
Distributed Application Platform Services
Northwestern University
1800 Sherman Ave.
Suite 6-600 – Box #39
Evanston, IL  60201-3715
darryl.baker@northwestern.edu<mailto:darryl.baker@northwestern.edu>
(847) 467-6674

**Comment by droidmonkey** [comment]
Yes I would love a dump

**Comment by dpb657** [comment]
I have not been able to reproduce the issue with any of the snapshot images I have tried. To recreate the issue, I worked my way back through the snapshot versions from the latest. I’ve gone back as far as the 50102 snapshot but can’t reproduce the problem. I guess we can call it fixed in 2.6.X.  If you have a 2.5.X snapshot to you would like me to try to reproduce the problem with, please provide a link. I am guessing the reason that it has to be a snapshot for the dump is that you need symbols that are stripped from the released versions.

Darryl Baker, GSEC  (he/him/his)
Sr. System Administrator
Distributed Application Platform Services
Northwestern University
1800 Sherman Ave.
Suite 6-600 – Box #39
Evanston, IL  60201-3715
darryl.baker@northwestern.edu<mailto:darryl.baker@northwestern.edu>
(847) 467-6674

**Comment by droidmonkey** [comment]
Well that's good news! I can post a debug build of 2.5.3 because I want to make sure it is fixed. Will link to it here.

**Comment by wombat01** [comment]
Anything new about this? Can I still help you find the problem? At the moment, the only way to exit the program correctly is via Task Manager> End Task

**Comment by dpb657** [comment]
I am still having to use the Task Manager to force the exit of KeepassXC after it has been running for a while. The program seems to exit fine if it has not been running long. I do not have a good handle on how long is long enough to trigger the issue.

Darryl Baker, GSEC  (he/him/his)
Sr. System Administrator
Distributed Application Platform Services
Northwestern University
1800 Sherman Ave.
Suite 6-600 – Box #39
Evanston, IL  60201-3715
darryl.baker@northwestern.edu<mailto:darryl.baker@northwestern.edu>
(847) 467-6674

**Comment by XyjpcpXNF6UGaQ** [comment]
Ditto: I, too, usually have to force Keepass XC to close via Task Manager. Version 2.5.4 is a slight improvement on the situation, but I am uncertain what the problem is; although it appeared to be related to a Java issue in 2.5.3.

My operating system is Windows 7 x64.

**Comment by a-vrma** [comment]
Same issue, I will post details in a bit.

**Comment by wombat01** [comment]
Thanks, I'll try. But I'm used to killing via the task manager :-)

**Comment by a-vrma** [comment]
Currently on
```
KeePassXC - Version 2.6.0-snapshot
Build Type: Snapshot
Revision: 43c82cc

Qt 5.14.2
Debugging mode is disabled.

Operating system: Windows 10 Version 1909
CPU architecture: x86_64
Kernel: winnt 10.0.18363

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.5
```

And I _think_ I might have encountered the bug but I'm not 100% sure. Will continue testing.

**Comment by wombat01** [comment]
Iit's better, the application "quits" but stays in the processes and needs to be killed manually. The shift is that the application did not close correctly and disappeared from the processes.

Snapshot from 05.06.

**Comment by johny-mnemonic** [comment]
I may be late to the party, but every time this happened to me, it was tied to db sync conflict in Dropbox.
It always happened on the other side then where I did the conflict resolution and merge of databases.
And killing the exe from taskmanager was reliable cure.
Usually it either hanged after trying to close the app itself or few times also while trying to merge databases. So obviously it was tied to writing to already rewritten db file.

I just installed 2.6.0, so hopefully this is the issue of the past...

**Comment by wombat01** [comment]
2.6.0 Still the same issue.

`KeePassXC - Verze 2.6.0-snapshot

Typ sestavení: Snapshot

Revize: b6787d9

Qt 5.15.0
Ladící režim je vypnutý.

Operační systém: Windows 10 Version 2004
Architektura procesoru: x86_64
Jádro systému: winnt 10.0.20161

Zapnutá rozšíření:
- Automatické vyplňování
- Napojení na webový prohlížeč
- SSH agent
- KeeShare (podepsané a nepodepsané sdílení)
- YubiKey

Kryptografické knihovny:
 libgcrypt 1.8.5
`

BTW is it normal for a simple password app to have almost 500 MB in size?

**Comment by droidmonkey** [comment]
First you are not running 2.6.0, you are running a snapshot which has debugging symbols. Second, I absolutely cannot replicate this problem at all.

**Comment by wombat01** [comment]
This means that KeePassXC-2.6.0-snapshot-Win64.zip **2020-07-09 13:56** is older than stable 2.6.0 **Jul 7, 2020 - 22:30 CEST**?

I'm trying all the new builds to see if the issue shows up. So now I have stable 2.6.0 and the issue is the same.

**Comment by droidmonkey** [comment]
It's got to be with your computer

**Comment by wombat01** [comment]
So I gave "stable" (portable) 2.6.0 a clean directory, the default config and the issue exactly the same as with snapshots.

So I have to kill process like this:
![dsfsd](https://user-images.githubusercontent.com/20426629/87219815-c9e82d80-c35e-11ea-8fdd-faf2eb71e12a.png)

**Comment by droidmonkey** [comment]
This might have something to do with your language, what language is keepassxc set to?

Also, please give EXACT steps to reproduce and settings that you have enabled/disabled.

**Comment by wombat01** [comment]
The language is "System default" - Czech. Tested with default settings.

Reproduce easily, start and after a while (I have no idea what, but for example a few hours), when I want to quit, it is no longer possible, it stays hanging in the processes and it is necessary to kill manually.

**Comment by droidmonkey** [comment]
That is not exact. What state is the application in (maximized, minimized, hidden to tray), is the database locked or unlocked, do you have unwanted changes, etc.

**Comment by wombat01** [comment]
Run by default, minimized on the toolbar .. not in the tray, unlocked database, no changes.

**Comment by droidmonkey** [comment]
I ran that exact scenario in a debugger for 2 days and nothing happened.

**Comment by wombat01** [comment]
![image](https://user-images.githubusercontent.com/20426629/87222279-d1193680-c372-11ea-88da-987d6bbe480f.png)

![image](https://user-images.githubusercontent.com/20426629/87222282-d8404480-c372-11ea-9469-11723ad7d298.png)
(Impossible to turn on - at this point i can just kill the process and run)

**Comment by wombat01** [comment]
at this moment this setting:

`
[General]
ConfigVersion=1
UpdateCheckMessageShown=true
AutoSaveAfterEveryChange=false
AutoSaveOnExit=false
UseAtomicSaves=false
AutoReloadOnChange=false

[GUI]
TrayIconAppearance=monochrome-light

[Browser]
CustomProxyLocation=

[KeeShare]
Own="<?xml version=\"1.0\"?>\n<KeeShare xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\">\n  <PrivateKey/>\n  <PublicKey/>\n</KeeShare>\n"
Foreign="<?xml version=\"1.0\"?>\n<KeeShare xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\">\n  <Foreign/>\n</KeeShare>\n"
Active="<?xml version=\"1.0\"?>\n<KeeShare xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\">\n  <Active/>\n</KeeShare>\n"
QuietSuccess=true

[Security]
LockDatabaseScreenLock=false
PasswordsHidden=false
PasswordsRepeatVisible=false
`

`
[General]
LastDir=C:/Users/xxx/OneDrive/Apps/Keepass2Android
LastDatabases=C:\\Users\\xxx\\OneDrive\\Apps\\Keepass2Android\\NewDatabase.kdbx
LastKeyFiles=@Variant(\0\0\0\x1c\0\0\0\0)
LastChallengeResponse=@Variant(\0\0\0\x1c\0\0\0\0)
LastActiveDatabase=C:\\Users\\xxx\\OneDrive\\Apps\\Keepass2Android\\NewDatabase.kdbx
LastOpenedDatabases=C:\\Users\\xxx\\OneDrive\\Apps\\Keepass2Android\\NewDatabase.kdbx

[GUI]
CheckForUpdatesNextCheck=1594920076
MainWindowGeometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\x3o\0\0\x1q\0\0\x6\x90\0\0\x3\xe8\0\0\x3p\0\0\x1\x90\0\0\x6\x8f\0\0\x3\xe7\0\0\0\0\0\0\0\0\n\0\0\0\x3p\0\0\x1\x90\0\0\x6\x8f\0\0\x3\xe7)
MainWindowState=@ByteArray(\0\0\0\xff\0\0\0\0\xfd\0\0\0\0\0\0\x3 \0\0\x2\a\0\0\0\x4\0\0\0\x4\0\0\0\b\0\0\0\b\xfc\0\0\0\x1\0\0\0\x2\0\0\0\x1\0\0\0\xe\0t\0o\0o\0l\0\x42\0\x61\0r\x1\0\0\0\0\xff\xff\xff\xff\0\0\0\0\0\0\0\0)
SplitterState=@Invalid()
PreviewSplitterState=@Invalid()
ListViewState="@ByteArray(\0\0\0\xff\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\x1\x1\0\0\0\xe\0\0\0\0\0\0\0\x3\0\0\0\x4\0\0\0\x5\0\0\0\x6\0\0\0\a\0\0\0\b\0\0\0\t\0\0\0\n\0\0\0\v\0\0\0\x1\0\0\0\f\0\0\0\x2\0\0\0\r\0\0\0\xe\0\0\0\0\0\0\0\n\0\0\0\f\0\0\0\x1\0\0\0\x2\0\0\0\x3\0\0\0\x4\0\0\0\x5\0\0\0\x6\0\0\0\a\0\0\0\b\0\0\0\t\0\0\0\v\0\0\0\r\0\0\0\xe!;\0\0\0\a\0\0\0\a\0\0\0\x64\0\0\0\x6\0\0\0\x64\0\0\0\0\0\0\0\x64\0\0\0\x3\0\0\0\x64\0\0\0\r\0\0\0\x64\0\0\0\t\0\0\0\x64\0\0\0\v\0\0\0\x64\0\0\x2\x1e\0\0\0\xe\x1\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x64\0\0\0\x18\0\0\0\x81\0\0\0\0\0\0\0\xe\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\x18\0\0\0\x1\0\0\0\x2\0\0\0\x18\0\0\0\x1\0\0\0\x2\0\0\0\x63\0\0\0\x1\0\0\0\0\0\0\0\x63\0\0\0\x1\0\0\0\0\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\x63\0\0\0\x1\0\0\0\0\0\0\0\x63\0\0\0\x1\0\0\0\0\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\x62\0\0\0\x1\0\0\0\0\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\x3\xe8\x1\0\0\0\x64)"
SearchViewState=@ByteArray()

[SSHAgent]
AuthSockOverride=
`

**Comment by droidmonkey** [comment]
There are two possibilities: (1) the main window is being hidden as if there is a tray icon but there really is none so you cannot recover from that, (2) the application is in a crashed state.

**Comment by wombat01** [comment]
`[General]
HideWindowOnCopy=false
MinimizeOnCopy=true
UpdateCheckMessageShown=true
SingleInstance=true
RememberLastDatabases=true
RememberLastKeyFiles=true
OpenPreviousDatabasesOnStartup=true
AutoSaveAfterEveryChange=true
AutoSaveOnExit=true
BackupBeforeSave=false
UseAtomicSaves=true
AutoReloadOnChange=true
MinimizeAfterUnlock=false
MinimizeOnOpenUrl=false
DropToBackgroundOnCopy=false
UseGroupIconOnEntryCreation=true
IgnoreGroupExpansion=true
AutoTypeEntryTitleMatch=true
AutoTypeEntryURLMatch=true
FaviconDownloadTimeout=10
GlobalAutoTypeKey=0
GlobalAutoTypeModifiers=0
AutoTypeDelay=25
AutoTypeStartDelay=500
ConfigVersion=1

[GUI]
CheckForUpdates=true
CheckForUpdatesNextCheck=1588957102
HideUsernames=false
HidePasswords=true
Language=system
HidePreviewPanel=false
HideToolbar=false
MovableToolbar=false
MonospaceNotes=false
ApplicationTheme=auto
ToolButtonStyle=0
ShowTrayIcon=false
DarkTrayIcon=false
MinimizeToTray=false
MinimizeOnClose=false
MinimizeOnStartup=false
CheckForUpdatesIncludeBetas=true
AdvancedSettings=true

[security]
passwordscleartext=true
HidePasswordPreviewPanel=false
passwordsrepeat=true
PasswordsHidden=false

[Browser]
Enabled=false
ShowNotification=true
BestMatchOnly=false
UnlockDatabase=true
MatchUrlScheme=true
SortByUsername=false
SupportBrowserProxy=true
UseCustomProxy=false
CustomProxyLocation=
UpdateBinaryPath=true
AllowExpiredCredentials=false
AlwaysAllowAccess=false
AlwaysAllowUpdate=false
HttpAuthPermission=false
SearchInAllDatabases=false
SupportKphFields=true
NoMigrationPrompt=false

[KeeShare]
QuietSuccess=true
Active="<?xml version=\"1.0\"?>\n<KeeShare xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\">\n  <Active/>\n</KeeShare>\n"
Own="<?xml version=\"1.0\"?>\n<KeeShare xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\">\n  <PrivateKey/>\n  <PublicKey/>\n</KeeShare>\n"
Foreign="<?xml version=\"1.0\"?>\n<KeeShare xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\">\n  <Foreign/>\n</KeeShare>\n"

[PasswordGenerator]
SpecialChars=false
ExcludedChars=
Length=14
LowerCase=false
UpperCase=false
Numbers=false
AdditionalChars=
`

**Comment by johny-mnemonic** [comment]
Just to make sure you are not looking wrong way.
I am using 2.6.0 portable on Czech Windows 10 with KeePassXC set to "System default" language and I just tried stopping it and it stopped without any issue.
As I described before, I would bet that this issue is related to issue with accessing (writing to) DB file. Once app has issue with that, it gets stuck and don't even exit correctly (at least that's what used to happen on 2.5.x). I haven't experienced any issue on 2.6.0 so far though...

**Comment by wombat01** [comment]
I use sync via OneDrive (system folder OneDrive) in the Windows 10. And still the same problem.

KeePassXC - Verze 2.6.1-snapshot

**Comment by wombat01** [comment]
I tried to replace portable with a classic installation and the problem still persists with this difference.

*Quit via Menu> Exit

![image](https://user-images.githubusercontent.com/20426629/96370505-55dbd380-115e-11eb-89ee-6882f0629606.png)

**Comment by NoSubstitute** [comment]
This is still an issue with portable 64bit 2.6.4 on Windows 10 Pro 20H2 19042.928.

I'm not locked out of starting a new process, even though I too have the setting _Allow only one instance_.
I also use DropBox for syncing, but it's not showing any errors at all, and all changes are synced without issue.

TaskManager shows 6 processes, with 5 of them being ghosts.
Just like everyone else I can't consistently create an exit failure. It seems to happens randomly.

![image](https://user-images.githubusercontent.com/12572734/115422161-ede57300-a1fc-11eb-9570-e1208310bb64.png)
