### ISSUE TITLE
Add direct option to Hide Window To System Tray When Closed

### ISSUE THREAD

**Issue by 0pLuS0** [keepassxreboot/keepassxc#4080]
## Summary
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
Please provide the option to Hide window to System tray when closed, besides minimized.

## Desired Behavior
[NOTE]: # ( Tell us how the new feature should work, be specific )
Allows the users to close the app, which will minmize it to the system tray.

At present, the only way to place it in the System tray is to minimize it, but in Unix/Linux, many apps function by also allowing them to minimize to the system tray by the ```close``` function.

I use keyboard shortcuts in Linux to open and close apps, having this ability makes it easier to place it in the sytem tray, at least it does for me, because I don't have any shortcut keys to minimizing apps. So it would be nice if I could just use my close keyboard short cut on keepassxc, to then have it minimized to the system tray.

THANKS

**Comment by droidmonkey** [comment]
This is literally an option in the general settings

**Comment by 0pLuS0** [comment]
@droidmonkey

I only see; ```Hide window to system tray when minimized```

I was asking that this can include when ```Closing``` too...

So as an example the new option could read like this;

```Hide window to system tray when closed or minimized```

THANKS

**Comment by droidmonkey** [comment]
Enable that and "Minimize instead of app exit"

**Comment by 0pLuS0** [comment]
As I mentioned I have short cut keys setup already for Closing apps.

It's always been my understanding in Unix/Linux that that DE and WMs have options for key shortcuts to close apps, not minimizing it.

I use Openbox, it does not have any minimize options that I'm aware of.

If you can please make it laster as I mentioned, that would be great!

Hide window to system tray when ```closed``` or minimized.

THANKS

**Comment by phoerious** [comment]
You have to trigger a close or minimise request.

**Comment by 0pLuS0** [comment]
2.5.4 now has this option, so I'm closing this!

THANKS
