### ISSUE TITLE
Segmentation Fault when creating and deleting unsaved entries (specific steps)

### ISSUE THREAD

**Issue by guihkx** [keepassxreboot/keepassxc#4084]
## Expected Behavior
No SEGFAULT

## Current Behavior
SEGFAULT

## Steps to Reproduce
1. Create a new entry, pick any title and click **OK**.
2. Now delete the recently created entry.
3. Create another entry, pick any title, but now you click **Cancel** instead.
4. A dialog will pop up, asking you to: **Save**, **Discard** or **Cancel**.
5. Choose: **Discard**.
5. KeePassXC will crash with segfault

## Debug Info
KeePassXC - Version 2.5.1
Revision: 0fd8836

Qt 5.14.0
Debugging mode is disabled.

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 5.4.7-zen1-1-zen

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.5

**Comment by droidmonkey** [comment]
This is fixed in 2.5.2 releasing tomorrow.

**Comment by guihkx** [comment]
Just updated to 2.5.2, still can reproduce this.

**Comment by guihkx** [comment]
Found out this is only reproducible if you've disabled the recycle bin in your database.

**Comment by droidmonkey** [comment]
Good to know!!

**Comment by guihkx** [comment]
I've tried capturing a trace with gdb. Hope it's helpful:

[gdb.txt](https://gist.githubusercontent.com/guihkx/0d1d4944090787e7006d05615d2c558b/raw/aa66880e3bf4466418f20aa2aeab321e282ae084/gdb.txt)

**Comment by droidmonkey** [comment]
Yes it is helpful and points to exactly what I suspected the problem was. It is directly related to the bug I reported yesterday: #4093

**Comment by droidmonkey** [comment]
This has been fixed in 2.6
