### ISSUE TITLE
Copy password in edit screen improvement

### ISSUE THREAD

**Issue by cimm** [keepassxreboot/keepassxc#4085]
## Summary

It would be nice to have a way to copy the password and TOTP from the edit entry screen.

![screen](https://user-images.githubusercontent.com/68112/71770643-39540f00-2f2f-11ea-8cda-11d9f0ed6a1f.png)

## Desired Behavior

I know you can copy the password, TOTP and other attributes from the "index" screen (the one listing all the entries) via  the menu, shortcuts or right-click menu. This is something I miss the same functionality on the entry edit screen, mainly for copying the password and TOTP codes.

## Possible Solution

No strong preference. A button or shortcut would work I think. There is the `Entries > Copy password` menu that does work but the `CTRL + C` shortcut does not copy the password on the entry edit screen.

## Context

Ubuntu 18.04, KeePassXC 2.5.2 (revision 62cda9d) installed from via PPA.

I guess the "edit" in the entry edit screen explains its purpose, editing entries. So it's not a screen I should use too often. I still find myself using that part of the application all the time since I use the notes screen extensively. I use it to write down the email address I used  when registering if the websites uses a username to log in, take note of the order number or client number, if I used my real address or not and so on.

The result is I am often on the edit screen in KeePassXC when I need my password or TOTP code. Say I am changing my email address with on some website and they ask my password to confirm the change. I can not simply use `CTRL+C` to copy the password. I also can't highlight the obfuscated password (the dots) and copy those. I have to click the eye icon to show the password, highlight it and copy it (or use the menu which I keep forgetting). Same for the TOTP code.

Thank you for the KeePassXC. I am a 1Password to Enpass to KeePass convert I didn't know KeePass is what I was looking for all along. Thank you contributors!

**Comment by droidmonkey** [comment]
The toolbar buttons are enabled for copying fields while editing an entry.

**Comment by cimm** [comment]
Makes sense, thank you. To be honest I didn't even notice the toolbar buttons until you mentioned it here. :see_no_evil:

**Comment by droidmonkey** [comment]
It's in the entry menu, Entry -> TOTP -> Copy TOTP
