### ISSUE TITLE
Qt 5.14 is incompatible with macOS 10.12

### ISSUE THREAD

**Issue by amcd2** [keepassxreboot/keepassxc#4089]
KeePassXC 2.5.2 is installed from dmg image from keepassxc.org/download and when starting KeePassXC the message is: KeePassXC cannot be opened because of a problem

Starting from command line:

$ /Applications/KeePassXC.app/Contents/MacOS/KeePassXC 
dyld: Symbol not found: _OBJC_CLASS_$_MTLCaptureManager
  Referenced from: /Applications/KeePassXC.app/Contents/MacOS/../Frameworks/QtGui.framework/Versions/5/QtGui (which was built for Mac OS X 10.13)
  Expected in: /System/Library/Frameworks/Metal.framework/Versions/A/Metal
 in /Applications/KeePassXC.app/Contents/MacOS/../Frameworks/QtGui.framework/Versions/5/QtGui
Abort trap: 6

## Possible Solution
It appears to be possible to revert back to 2.5.1 and KeePassXC opens

Note: keepassxc.org/download/ states: Supported on macOS 10.12 and later
Perhaps it was intended to remove macOS 10.12 support and the documentation was not updated?

## Steps to Reproduce
Install KeePassXC-2.5.2.dmg on macOS 10.12 using dmg image from keepassxc.org
Attempt to start KeePassXC

## macOS problem info

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x4] Symbol missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Symbol not found: _OBJC_CLASS_$_MTLCaptureManager
  Referenced from: /Applications/KeePassXC.app/Contents/MacOS/../Frameworks/QtGui.framework/Versions/5/QtGui (which was built for Mac OS X 10.13)
  Expected in: /System/Library/Frameworks/Metal.framework/Versions/A/Metal
 in /Applications/KeePassXC.app/Contents/MacOS/../Frameworks/QtGui.framework/Versions/5/QtGui

[keepassxc-2.5.2-error-messages.zip](https://github.com/keepassxreboot/keepassxc/files/4022830/keepassxc-2.5.2-error-messages.zip)

**Comment by amcd2** [comment]
While I was editing another issue was created. This issue appears to be a duplicate of https://github.com/keepassxreboot/keepassxc/issues/4087

**Comment by droidmonkey** [comment]
This is because Qt 5.14 does not support macOS 10.12.

**Comment by amcd2** [comment]
This issue can be closed with the release of KeePassXC-2.5.2-Sierra.dmg and now KeePassXC-2.5.3-Sierra.dmg
