### ISSUE TITLE
Safari and Chrome Extension

### ISSUE THREAD

**Issue by mimmog** [keepassxreboot/keepassxc#409]
Hi, there is KeepassXC safari or chrome extension ? Where I can find all available extension ?

Thank you

**Comment by phoerious** [comment]
There are no dedicated browser extensions, but KeePassXC is compatible with PassIFox and chromeIPass. You find those in the Mozilla add-on database and the Chrome web store.

**Comment by Xant1k** [comment]
CKP better.
