### ISSUE TITLE
Entry Preview Widget continues to show entry after being deleted

### ISSUE THREAD

**Issue by droidmonkey** [keepassxreboot/keepassxc#4093]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Select the group after all entries within a group are deleted / moved to the recycle bin.

## Current Behavior
[NOTE]: # ( Tell us what actually happens )
The last entry selected still appears in the entry preview widget.

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )
Select the group after all entries in a group are deleted.

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1. Add entry to a group
2. Select the entry
3. Delete the entry
4. Observe the preview widget still shows information about that entry

**Comment by kusune** [comment]
Although this issue has been closed, I believe the underlying problem remains unresolved.

There are situations where the SSH agent (such as Pageant) may be restarted after KeePassXC is already running. In such cases, there is currently no way to trigger a re-send of all configured public keys to the agent without closing and reopening the database — which unfortunately also disconnects all other clients using the same database (e.g., browser extensions).

Even worse, if multiple entries are configured with SSH keys, there is no batch operation available to re-send them. The user is forced to re-add each one manually, one by one. This is tedious, error-prone, and undermines the purpose of centralized credential management via KeePassXC.

The application already provides a "clear SSH agent" function in the settings, so I believe it would be entirely appropriate to also provide a "reconnect" or "re-send all keys" action — whether as a menu option, toolbar button, or automatic behavior upon agent availability detection.

Please consider reopening this issue or tracking the request in a more focused ticket.

**Comment by droidmonkey** [comment]
Your comment has nothing to do with this issue. I created a new issue for you
