### ISSUE TITLE
System Tray Icon is not shown and minimize to tray is not working

### ISSUE THREAD

**Issue by Dabuka** [keepassxreboot/keepassxc#4094]
The problem introduced in 2.5.2. 2.5.1 is working fine.

Ubuntu 18.04.3 LTS. KeePassXC installed from the Official Ubuntu PPA. No other packages were upgraded at the time of 2.5.1 -> 2.5.2 switch.

![image](https://user-images.githubusercontent.com/7505083/71782005-1e90a180-2fe6-11ea-883a-151a558553ac.png)

System Tray Icon is not shown. The app is minimized to taskbar instead of system tray.

**Comment by droidmonkey** [comment]
We didn't touch any code related to the system tray icon in 2.5.2

**Comment by Dabuka** [comment]
@droidmonkey ,  the problem disappeared after OS restart. This issue should probably be closed. Thank you!
