### ISSUE TITLE
KeepassXC 2.5.2 isn't usabele after performing autotype

### ISSUE THREAD

**Issue by ovz93br43v7** [keepassxreboot/keepassxc#4095]
## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Until KeepasXC 2.5 I could select an entry of my database, right click --> auto type, login / password fields were filled and keepassxc was normally usable afterwards

## Current Behavior
[NOTE]: # ( Tell us what actually happens )
With KeepassXC 2.5.2 I start the autotype feature by right click, login/password fields are filled and I'm logged in. But the keepassXC window is afterwards no longer maximized, looks unsharp (wrong resolution?) and I can't move the keepassXC window anymore.

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )
Close keepassXC and open it again or copy paste the login, password and other attributes step-by-step.

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1. Open KeepassXC and login
2. Browse with firefox to the desired webpage
3. Select the login field on the webpage
4. Open the keepassXC window
5. Select the entry in the password database
6. Right click on autotype
7. Firefox is opened and the autotype is performed.
8. I can use the webpage as expected.
9. Switching again to the keepassXC windows. But I can't move the window anymore, the keepassxc window is no longer maximized, the all buttons in the keepassxc window looking unsharp

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.5.2
Revision: 62cda9d

Qt 5.9.5
Diagnosemodus ist deaktiviert.

Betriebssystem: elementary OS 5.1 Hera
CPU-Architektur: x86_64
Kernel: linux 5.0.0-37-generic

Aktivierte Erweiterungen:
- Auto-Type
- Browser-Integration
- SSH-Agent
- KeeShare (bestätigtes und unbestätigtes Teilen)
- YubiKey
- Secret-Service-Integration

Kryptographische Bibliotheken:
 libgcrypt 1.8.1

**Comment by droidmonkey** [comment]
Does simply minimize and maximize the window cause the same issue?

**Comment by ovz93br43v7** [comment]
No minimize maximize works normally!

**Comment by droidmonkey** [comment]
Are you running the snap version?

**Comment by ovz93br43v7** [comment]
No I use the ppa version.

**Comment by droidmonkey** [comment]
I could not reproduce this using the snap version or a natively built version on Ubuntu 19.04. Try restarting your computer.

**Comment by ovz93br43v7** [comment]
I have restarted and tested it again. One addition: Before starting auto-type the keepassxc window has to be maximized. If the window is small the failure don't happen. 

I can make a video with a test database if it helps.

**Comment by ovz93br43v7** [comment]
Attached a link to the video with a test database:
[https://drive.google.com/open?id=1pRsMsvB77EFMhF2Bzg3whXmeq0iaqQPZ](url)

**Comment by droidmonkey** [comment]
Ahhhh gotcha, will try again.

**Comment by phoerious** [comment]
I've been using Ctrl+Shift+V Auto-Type on Linux (KDE) and Windows and have not seen any such issues.

**Comment by ovz93br43v7** [comment]
> I've been using Ctrl+Shift+V Auto-Type on Linux (KDE) and Windows over the last couple of days and have not seen any such issues.

Before 2.5.2 everything works perfekt!

**Comment by droidmonkey** [comment]
I do agree that after performing Auto-Type with the window maximized, the window does not return to the maximized state on Ubuntu 19.04. However, I do not have the problem that your video shows.

**Comment by ovz93br43v7** [comment]
> I do agree that after performing Auto-Type with the window maximized, the window does not return to the maximized state on Ubuntu 19.04 (this is with the snap version only). However, I do not have the problem that your video shows.

Is it possible to downgrade to the previous version with the ppa?

**Comment by ovz93br43v7** [comment]
> I do agree that after performing Auto-Type with the window maximized, the window does not return to the maximized state on Ubuntu 19.04 (this is with the snap version only). However, I do not have the problem that your video shows.

Can you test Ubuntu 18.04 and elementaryOS Hera in a virtual machine?
I have tried it on my second laptop (same OS, keepassXC 2.5.2) and it shows the same behaviour. (window is smaller, not movable and looking unsharp)

**Comment by ovz93br43v7** [comment]
I have found out that this issue only happens when the keepassxc window is maximized before starting the auto type feature. If the keepassxc window is little bit smaller then maximized everything works as expected.
