### ISSUE TITLE
macOS Crashing with segmentation fault

### ISSUE THREAD

**Issue by delize** [keepassxreboot/keepassxc#4097]
Hello,

I have been using KeepassXC on two different macOS machines, and both crash with segmentation faults. Attached is a log file of the issue when it crashes.
[keepassxc-crash.log](https://github.com/keepassxreboot/keepassxc/files/4023896/keepassxc-crash.log)

**Comment by phoerious** [comment]
Please update to version 2.5.2 and try again.

**Comment by delize** [comment]
I have not received a crash yet, I will reopen this issue if it occurs with 2.5.2.
