### ISSUE TITLE
Add column "Size" so a Search by Size is possible

### ISSUE THREAD

**Issue by OLLI-S** [keepassxreboot/keepassxc#4101]
## Summary
Show my password entries sorted by date or by size

## Details
I suggested these two views to KeePass and Dominik implemented them:

The following screen shot is the "Find" menu in KeePass:
![image](https://user-images.githubusercontent.com/8037790/71786865-fd917600-3010-11ea-9cff-3b9e124ced5f.png)

This shows all entries in my password database in a new window sorted by size or sorted by date.

**Searching by size** is very useful when you want to find large entries.
I had one entry with 4 MB in size, it contained a PDF (1 MB) and the same PDF 3 times in the history, So I delete the history and replaced the PDF with a JPG, now the entry is 60 KB.

**Searching by size** is very useful when you want to see what entries you have last modified (I use this very often).

**Comment by OLLI-S** [comment]
For illustration here some screen shots from KeePass:

### Search by Modification-Date
![image](https://user-images.githubusercontent.com/8037790/73598106-28012100-4534-11ea-9d7f-facb67a0c4db.png)

### Search by Size
![image](https://user-images.githubusercontent.com/8037790/73598151-ac53a400-4534-11ea-8c04-af5a29988ace.png)

**Comment by phoerious** [comment]
You can enter * into the search box to list all entries and then sort by whatever column you like.

**Comment by OLLI-S** [comment]
Thank you @phoerious, did not know this.
Here the column "Size" is missing, so if you implement this column then I could also search by size.
I will update the title.

**Comment by droidmonkey** [comment]
Size colum would be very nice indeed
