### ISSUE TITLE
Mobile Apps

### ISSUE THREAD

**Issue by OLLI-S** [keepassxreboot/keepassxc#4102]
## Summary
Please release mobile apps (Android, iOS) of KeePassXC

## Details
What is annoying in KeePass and KeePassXC is that there are no **official** mobile apps.
I am forced to use apps from 3rd party developers (like KeePass2Android) that look and behave different than KeePass/KeePassXC and that have slightly other features than KeePass/KeePassXC.
This is the main argument why some of my colleagues use Bitwarden, LastPass, or 1Password.

I fear that this is too much work for this project and that this idea gets rejected.
But I suggest it anyways, because it is important for a good usability.

**Comment by droidmonkey** [comment]
This is already tracked in another issue.
