### ISSUE TITLE
Double-Click to open a group modifies the database -> Bug?

### ISSUE THREAD

**Issue by OLLI-S** [keepassxreboot/keepassxc#4103]
## Expected Behavior
When I Double-Click a group (like the root entry) it should be collapsed/expanded.
The database should not be modified (like in KeePass).

## Current Behavior
The group expands/collapses but the database gets modified (the "*" is shown in the application title bar).
**I am not sure is this is a bug or a feature** (it is different to KeePass)

## Debug Info
KeePassXC - Version 2.5.2
Revision: 62cda9d

Qt 5.13.2
Diagnosemodus ist deaktiviert.

Betriebssystem: Windows 10 (10.0)
CPU-Architektur: x86_64
Kernel: winnt 10.0.18363

Aktivierte Erweiterungen:
- Auto-Type
- Browser-Integration
- SSH-Agent
- KeeShare (bestätigtes und unbestätigtes Teilen)
- YubiKey

Kryptographische Bibliotheken:
 libgcrypt 1.8.5

**Comment by droidmonkey** [comment]
Could not reproduce, make sure this setting is enabled:

![image](https://user-images.githubusercontent.com/2809491/71790622-61ab3e80-2fff-11ea-9b43-aa54472d0138.png)

**Comment by OLLI-S** [comment]
Indeed this option is **not set**.

I am using KeePassXC portable x64, so I deleted the complete folder and extracted it from the ZIP (KeePassXC-2.5.2-Win64-portable.zip) again.
By **default** this setting is **not set**, maybe you consider setting it by default?

When I click the button to reset the settings, then this checkbox is checked.
So the default settings, that you deliver in the ZIP, don't match to the settings that you restore when you press the reset button.

Does this need to be adjusted?
I work as UX expert (user experience, accessibility, usability) and my goal is to make KeePassXC better (not to critisize without reason).

**Comment by droidmonkey** [comment]
Oops yes that is a problem, need a new default settings file for the portable.

**Comment by OLLI-S** [comment]
Glad that I found the bug....

**Comment by firepainting** [comment]
I'm having the same issue but that option under File Management is not available for me (Linux Mint 21.2 Cinnamon; KeePassXC version 2.7.6, installed via PPA because the AppImage would not show attachments). Any workarounds? Thank you.
