### ISSUE TITLE
Unlock KeePass on Secure Desktop in Windows

### ISSUE THREAD

**Issue by OLLI-S** [keepassxreboot/keepassxc#4107]
## Summary
Switch to a secure desktop in Windows when entering the master key.

## Details
KeePass has an option "Enter master key on secure desktop":

![image](https://user-images.githubusercontent.com/8037790/71827559-d2566780-30a0-11ea-8e1e-a8ea49d3484e.png)

When this option is turned on, then a secure desktop environment is created (he desktop is dimmed out and input is only possible in the master-password dialog).
This **prevents keyloggers to steal the master password**, so it **increases the security**.

I searched for a screen shot and found this one (to illustrate the feature):

![image](https://user-images.githubusercontent.com/8037790/71827768-39741c00-30a1-11ea-8f1e-24c67ebbee71.png)

The feature is described here: https://keepass.info/help/kb/sec_desk.html

**Comment by droidmonkey** [comment]
This is a duplicate request.
