### ISSUE TITLE
URL matching not strict enough

### ISSUE THREAD

**Issue by principis** [keepassxreboot/keepassxc#4108]
After one of the recent big updates, I was busy and can't remember which one, the URL matching has changed to no longer be strict enough.

"Return only best-matching credentials" is enabled. The behavior seems to be the same if it's enabled or not.

I'm not sure if this should be reported to the browser-plugin repository.

## Expected Behavior
When logging in on `service1.example.org` 
- If `service1.example.com` exists, is should only show that one.
- If only `example.com` exists and `service1.example.com` does not, it should show the first one and not any other logins for other subdomains. (e.g. `service2.example.org`)

## Current Behavior
When logging in on `service1.example.org` it shows
- `example.com`
- `service2.example.com` (user1)
- `service2.example.com` (user2)

Changing `https://example.com` to `example.com` did not change anything.

## Possible Solution
Change it to not show the logins for `service2.example.com`  when surfing to `service1.example.com` because it's not logical.

## Steps to Reproduce
1. Add a login for `example.com`
2. Add a login for `service2.example.com`
3. Surf to `service1.example.com`

## Context
We have basic authentication on `service1.example.org`. In earlier versions, it immediately logged me in, but now I have to select the account which takes a long time and is annoying.

## Debug Info
KeePassXC - Version 2.5.1
Revision: 0fd8836

Qt 5.12.5
Debugging mode is disabled.

Operating system: Fedora 31 (Thirty One)
CPU architecture: x86_64
Kernel: linux 5.3.16-300.fc31.x86_64

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.5

**Comment by droidmonkey** [comment]
Update to 2.5.2
