### ISSUE TITLE
CLI: display the UUID in the show command

### ISSUE THREAD

**Issue by hanspr** [keepassxreboot/keepassxc#4112]
## Description

Add Uuid as a default attribute to list in `show` command or as an attribute with `-a option` to be able to retrive it

`keepassxc-cli show path/to/database 'search'`

Should show:

```
Insert password to unlock path.kdbx: 
Title: mi title
UserName: username
Password: *****
URL: 
Uuid: 9340590348503485034
Notes: 
```

`keepassxc-cli show -a Uuid path/to/database 'search'`

Should show:

```
Insert password to unlock path.kdbx: 
9340590348503485034
```

## Context
It helps to integrate with other applications because it guaranties no duplicate entries.

**Comment by bahelit** [comment]
Hello, would like to contribute on this one. Long time user and referrer of this software looking to contribute. Have looked over the code and see where the changes need to take place.

**Comment by droidmonkey** [comment]
Have at it

**Comment by hanspr** [comment]
@bahelit 

Thanks Michel, if is not to much to ask, would be nice if you could link the solution with #4113

**Comment by bahelit** [comment]
@hanspr That's not to much, no problem.

**Comment by bahelit** [comment]
The UUID now displays from the show command and is also a searchable attribute for #4113.

Show command output:
`Title: snorg
UserName: derp
Password: PROTECTED
URL: snorgtees.com
Uuid: {076b5698-5ad7-4c47-97a7-c5e373efa0b3}
Notes: `

Will see about removing those braces.
The unit test TestCli::testShow() @ tests/TestCli.cpp:1773 looks like it'll fail now base on the way the test data is prepared, the uuid would be different every time. Didn't run it yet though as I didn't see which make recipe to call to trigger it.

**Comment by bahelit** [comment]
Removed the braces surrounding the UUID with regex.

**Comment by bahelit** [comment]
Added TestCli to the Makefile and CmakeLists.txt to run the unit tests but there are build errors all throughout TestCli.cpp as well as in a few other files under src/cli. Didn't commit those changes as a new issue should probably be created to address that.

**Comment by phoerious** [comment]
The tests have to pass. If they don't, it means your changes break the code base.
