### ISSUE TITLE
Documentation: Example of how to add a new entry using keepassxc-cli add

### ISSUE THREAD

**Issue by MountainX** [keepassxreboot/keepassxc#4117]
I had to experiment to find out how to add an entry to a database using the command line utility, keepassxc-cli.

There is help output, but (for me) It was not clear what is the meaning of the "Path of the entry to add". Therefore, I am sharing my notes.

### What is the **Path of the entry to add**?

Experimenting showed that path means the hierarchy inside the database. It does not require starting with "Root" in my experience. (I am not sure if it case sensitive.) For path element separators I am using "/" (on Linux). See example below.

The "Path of the entry to add" is **not** the filesystem path of a CSV file containing the credentials (similar to a bulk CSV import, but containing a single entry). I initially assumed it was this. However,that results in the error like this:
Could not create entry with path /path/to/my/file.csv
So that is incorrect.

### **Here's an example of how to add an entry from the command line:**

This assumes your database file is in the current directory. If not, provide the full path to it.

keepassxc-cli add yourdatabase.kdbx --username "Joe Reno" --url "https://www.yahoo.com" -p "Financial/My Yahoo Finance Account"

You will first be prompted for the credentials for the KeePass database.
Next you will be prompted for the password for the new entry.

This will create a new entry named "My Yahoo Finance Account" under the Group hierarchy: Root > Financial.

### You can find the full help output as shown below:

$ keepassxc-cli add -h
Usage: keepassxc-cli add [options] database entry
Add a new entry to a database.

Options:
  -q, --quiet                Silence password prompt and other secondary
                             outputs.
  -k, --key-file <path>      Key file of the database.
  --no-password              Deactivate password key for the database.
  -y, --yubikey <slot>       Yubikey slot used to encrypt the database.
  -u, --username <username>  Username for the entry.
  --url <URL>                URL for the entry.
  -p, --password-prompt      Prompt for the entry's password.
  -g, --generate             Generate a password for the entry.
  -L, --length <length>      Length of the generated password
  -l, --lower                Use lowercase characters
  -U, --upper                Use uppercase characters
  -n, --numeric              Use numbers
  -s, --special              Use special characters
  -e, --extended             Use extended ASCII
  -x, --exclude <chars>      Exclude character set
  --exclude-similar          Exclude similar looking characters
  --every-group              Include characters from every selected group
  -h, --help                 Display this help.

Arguments:
  database                   Path of the database.
  entry                      Path of the entry to add.

**Comment by alexzanderr** [comment]
how can i add the password of a new entry using above command without generating new password? (adding an argument such as --existing-password "existing_password")

and how can i add an entry from file? what type of file should be that entry?

**Comment by JohnLGalt** [comment]
For password:

-p, --password-prompt Prompt for the entry's password.

**Comment by alexzanderr** [comment]
i tried that. it prompts to enter manually.

instead. i want to enter password `from code` or `specified` as an `command-line argument`.

**Comment by droidmonkey** [comment]
Pipe the password to the program to set the stdin. Remember to include a new line

**Comment by alexzanderr** [comment]
> Pipe the password to the program to set the stdin. Remember to include a new line

i tried that, but one thing should be `considered`. when you want to add `new entry` you must enter the password for the `keepassxc database file`, so you need to pipe the password for database first and after that pipe the password for entry, but i dont know how to do that. (just skips it)

example of command that i used:
```bash
echo 'db_pass' | keepassxc-cli add -k "keyfile_path" "database_path.kdbx" \
--username "this is the username" \
--url "this is the URL" "this is the title" -p
```
this command creates a new entry with below attributes, but doenst put any password to entry. when i look into the database, the entry doesnt have a password at all. 

- i used key file for db, so should be passed, i think.
- i used db path
- template username
- template url
- template title

but how do i `double echo` to be able to pipe the password for entry, because keepassxc-cli prompts you to insert `2 times`, 1 for db password, 1 for entry password.

the above command works with `password auto generation`:
```bash
echo 'db_pass' | keepassxc-cli add -k "keyfile_path" "database_path.kdbx" \
--username "this is the username" \
--url "this is the URL" "this is the title" -g -L 20 -l -U -n -s --exclude-similar
```
this generates a random password and puts a new entry to database, `works like a charm`, but `i dont want this`, i want to manually insert the password because i have existing passwords from accounts.

any help would be appreciated. thanks.

**Comment by droidmonkey** [comment]
Try this:
`printf '%s\0%s' "$str1" "$str2" | keepassxc-cli ...`

**Comment by alexzanderr** [comment]
thank you so much.

i tried your version, doesnt work, it was very close. 

it should be '%s\n%s'. works like a charm. 

adds new entry to database with custom password.

**Comment by droidmonkey** [comment]
Sweet made the correction on mine

**Comment by DougWeiner** [comment]
Unfortunately this isn't an option on window systems.
