### ISSUE TITLE
Browser integration returns multiple unrelated credentials

### ISSUE THREAD

**Issue by elman22** [keepassxreboot/keepassxc#4122]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
When I open URL site.domain.com, I expect to get credential matches for site.domain.com and not any other domain (e.g. not site2.domain.com).

## Current Behavior
[NOTE]: # ( Tell us what actually happens )
When I open URL site.domain.com in any browser (tried Firefox and Chrome), I get many results from unrelated domains. Even top level domain doesn't fit. For example if I open site.domain.com, I get results from site2.domain.com, site.domain.org, site3.domainX.edu, etd... Can't find any connection between the sites.

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )
Maybe some setting to mange domain matching? As far as I know there is only option to match http or https.

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1. Connect browser plugin to database
2. Enter URL into browser
3. Observe fetched results.

I know this is not unambiguous, but this is how it happens to me.

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )
This behavior was introduced in 2.5.0. Before that I only got 1 result for correct domain.

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.5.1
Revision: 0fd8836

Qt 5.14.0
Debugging mode is disabled.

Operating system: Manjaro Linux
CPU architecture: x86_64
Kernel: linux 5.4.6-2-MANJARO

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.5

**Comment by droidmonkey** [comment]
Update to 2.5.2

**Comment by elman22** [comment]
Version 2.5.2 works fine again. Thank a lot :+1:
