### ISSUE TITLE
On tor browser does not seem to work 

### ISSUE THREAD

**Issue by xzj8b3** [keepassxreboot/keepassxc#4123]
On Tor, the browser does not seem to work and does not connect to the database.

**Comment by DmitriyPanteleev** [comment]
working json portabe linux (if doesnt exist - create it):
.../TorBrowser/Browser/TorBrowser/Data/Browser/.mozilla/native-messaging-hosts/org.keepassxc.keepassxc_browser.json
{
  "description": "KeePassXC integration with native messaging support",
  "name": "org.keepassxc.keepassxc_browser",
  "path": "/usr/bin/keepassxc-proxy",
  "type": "stdio",
  "allowed_extensions": ["keepassxc-browser@keepassxc.org"]
}
