### ISSUE TITLE
Use favicon from subdomain even after CNAME occurs

### ISSUE THREAD

**Issue by jblachly** [keepassxreboot/keepassxc#4125]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

When clicking the option to download the favicon from the URL in an entry, this can fail for subdomains that have a CNAME.

## Expected Behavior
I expect the favicon for the URL in the KeepassXC entry to be downloaded.

## Current Behavior
If the URL's hostname is a CNAME, it moves to the second-level domain (i.e., `foobar.domain.com -> domain.com`.

## Possible Solution
This is because of the following block of code in IconDownloader::setUrl

https://github.com/keepassxreboot/keepassxc/blob/8ded3bdba239c089c8a9c3d206895da0d79ea0c4/src/core/IconDownloader.cpp#L87-L103

### Specific example:

issues.dlang.org (a bugzilla tracker for the D language) has the Bugzilla favicon. However, KeepassXC adds the dlang.org main domain website favicon. 

## Context
This leads to misleading icons for entries, increasing cognitive overhead in large databases

## Debug Info

KeePassXC - 2.5.1 (code current in ~develop)

Operating system: MacOS, but code current in ~develop
CPU architecture: x86_64
Kernel: Darwin

Enabled extensions:
firefox browser integration

**Comment by droidmonkey** [comment]
We check the most specific URL first, the check the level up domain. Perhaps we cannot find the favicon for issues.dlang.org for some reason.

**Comment by jblachly** [comment]
@droidmonkey thanks for your quick reply. However, I might not have done a good job explaining the bug.

I am suggesting that the following expression evaluates to false in the case of a CNAME[0] record:

```addr.toString() == fullyQualifiedDomain```

This is because the addr.toString() contains the canonical name; thus, this does not match the variable `fullyQualifiedDomain`. For example:
```
jsbmbp13:~/Downloads$ nslookup issues.dlang.org
Server:		192.168.1.1
Address:	192.168.1.1#53

Non-authoritative answer:
issues.dlang.org	canonical name = issues-d.puremagic.com.
Name:	issues-d.puremagic.com
Address: 54.187.1.105
```

I apologize I do not have QT [1][2] installed to create a test case.

James

[0] https://en.wikipedia.org/wiki/CNAME_record
[1] https://doc.qt.io/qt-5/qhostinfo.html#fromName
[2] https://code.woboq.org/qt5/qtbase/src/network/kernel/qhostinfo.cpp.html#_ZN9QHostInfo8fromNameERK7QString

**Comment by droidmonkey** [comment]
Ahhh gotcha

**Comment by droidmonkey** [comment]
Need to verify this is still a problem.

**Comment by jblachly** [comment]
This is still a bug in 2.7.0

**Comment by phoerious** [comment]
This is nothing to do with the CNAME. The reason why you don't get the Bugzilla favicon is simply that https://issues.dlang.org/favicon.ico does not exist triggering the fallback to dlang.org. The icon you are looking for is at https://issues.dlang.org/images/favicon.ico, but we cannot know that without parsing the HTML code.

We may do some basic HTML parsing or at least some regex matching in a future version, but for now this is out of scope and I suggest you simply enable the DuckDuckGo fallback.
