### ISSUE TITLE
Keyboard clipboard is *not* cleared after timeout

### ISSUE THREAD

**Issue by l0b0** [keepassxreboot/keepassxc#4126]
The clipboard is not cleared according to the relevant security setting.

## Steps to Reproduce

1. In KeePassXC go to Tools → Settings → Security
2. Tick "Clear clipboard after" and set the timeout to "10 sec"
3. Open a password database
4. Highlight an entry with a password and press <kbd>Ctrl-c</kbd>
5. Wait for more than 10 seconds
6. Focus another window and paste **using the keyboard** (<kbd>Ctrl-v</kbd> or <kbd>Ctrl-Shift-v</kbd>, depending on the application)

## Expected Behavior

Nothing should be pasted.

## Current Behavior

The password is pasted!

## Context

The mouse clipboard *is* cleared.

I'm running vanilla Ubuntu 19.10 (with GNOME) with the latest updates. I'm not running any custom clipboard managers as far as I know.

This *did* work on every other KeePassXC version + OS + WM combination I've ever tried before.

## Debug Info

KeePassXC - Version 2.4.3
Revision: 5d6ef0c

Qt 5.12.4
Debugging mode is disabled.

Operating system: Ubuntu 19.10
CPU architecture: x86_64
Kernel: linux 5.3.0-24-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (only unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.4

**Comment by droidmonkey** [comment]
Holy cow confirmed. This affects Linux only.

**Comment by phoerious** [comment]
I bet you are using a clipboard manager. In Klipper you have to turn off "Prevent empty clipboard".
I cannot reproduce this with that setting turned off.

**Comment by l0b0** [comment]
@phoerious I'm not using Klipper, at least. And none of these show any results:

1. `apt list --installed | grep -i clipboard`
1. `ps x | grep [c]lipboard`

`apropos clipboard` only shows `xclipboard`, which AFAIK is not a clipboard manager.

Do you know any other ways to check whether I am using a clipboard manager?

**Comment by phoerious** [comment]
We discussed this on IRC, it may be that Gnome has some built-in clipboard management features or there is a weird Qt interaction preventing us from clearing the clipboard. On KDE I cannot reproduce this behaviour.

Can you test if

```
xclip -selection clipboard <(echo -n) && xsel -c
```

reliably clears both (!) the Ctrl+V and the middle-mouse-button clipboard buffers?

**Comment by l0b0** [comment]
@phoerious Verified:

1. Installed xclip and xsel
1. Selected the command in your comment to populate the mouse clipboard
1. Pressed <kbd>Ctrl-c</kbd> to populate the keyboard clipboard
1. Opened a GNOME Terminal
1. Pressed <kbd>Ctrl-Shift-v</kbd> to paste from the keyboard buffer
1. Ran the command
1. Pressed <kbd>Ctrl-Shift-v</kbd> (nothing was pasted)
1. Middle clicked (nothing was pasted)

**Comment by Laxa** [comment]
Hello, I am encoutering the same issue on Debian unstable but kernel  `4.19.0-5-amd64`. This issue has been present since I switched from KeepassX to KeepassXC about 1 or 2 months ago. I had not this issue from using KeePassx. Funny thing is, I tried , the `keepassxc-cli clip` and the timeout successfully cleared the clipboard. I am using gnome 1:3.30+2. I am using the packaged keepassxc version (2.4.3).

**Comment by phoerious** [comment]
The CLI uses xclip for managing the clipboard.

**Comment by phlfm** [comment]
Instead of clearing the clipboard, wouldn't it be more reliable to change it to some whitespace?

**Comment by droidmonkey** [comment]
That may be the issue, Gnome could be ignoring a blank clipboard entry and retaining the existing clipboard.

**Comment by bm-3500** [comment]
Don't know if this is any help, in Debian buster no issue
KeePassXC - Version 2.3.4
Revision: 6fe821c
Libraries: - Qt 5.11.3, - libgcrypt 1.8.4
Kernel: linux 4.19.0-6-amd64

**Comment by rmader** [comment]
To add some context: GS/Mutter 3.34 (the version shipped with Ubuntu 19.10) introduced a clipboard  manager by default. Whenever the clipboard is cleared, the c-m takes over and provides a copy previously taken for further use. So what we see here is likely a conflict of features.

The solution taken here, explicitly setting a new empty content, therefore appears to be the safest solution, also taken other clipboard managers into account.

**Comment by rmader** [comment]
FTR, actually Carlos found a way to allow clearing the clipboard without the c-m taking over - backported to gnome 3.34 / 3.36 (https://gitlab.gnome.org/GNOME/mutter/-/merge_requests/1206?commit_id=5671f0a284a5875f7d964a4d368470c33581ba80)
