### ISSUE TITLE
Make the UI more modern and more sexy

### ISSUE THREAD

**Issue by OLLI-S** [keepassxreboot/keepassxc#4127]
## Summary
Offer a modern and ste-of-the-art UI

## Details
I really like and KeePassXC and told some colleagues about it (and also showed them KeePassXC at my PC with Windows 10).
One of my told me that the layout looks a bit "old-fashioned" and that it should me made "more modern" and "more sexy".
He uses 1Password on a Mac and iPhone.

I know that KeePassXC is cross-platform and that it looks very similar on all platforms.
But is it possible to make it look more modern (make it look like some web apps)?

Maybe we discuss here if this is needed and what can be done.

**Comment by droidmonkey** [comment]
We don't need an issue for this, there is already one. AND we have a PR in the works for this! 🚀 

See #4110
