### ISSUE TITLE
GPG Snap package verify

### ISSUE THREAD

**Issue by jheld** [keepassxreboot/keepassxc#413]
I've installed the snap package version for ubuntu, and I wanted to verify the GPG signature. How can I do this? Do I need to do this? I'll uninstall in the meantime, just in case.

**Comment by droidmonkey** [comment]
There is currently no way to sign a snap package unfortunately. You can confirm that the author is me (droidmonkey) on the Ubuntu store.

**Comment by purachina** [comment]
Looks like “keepassxreboot” for me.
![](https://cloud.githubusercontent.com/assets/24848379/24086711/afcc6cee-0ce2-11e7-86ae-37ddb97dc503.png)

**Comment by droidmonkey** [comment]
Yes sorry, that is correct. I changed my developer name to reflect the "organization" name we have.
