### ISSUE TITLE
Use semver for your version numbers

### ISSUE THREAD

**Issue by hoall** [keepassxreboot/keepassxc#4135]
First of all, thank you for your awesome work. I love your tool and use it in private as well as at work.

I am most of the time confused when you release a new version of keepassXC.

Like the current release 2.5.2 you did a lot of changes. You did:

- add new functionality
- adaptions
- and bugfixes

Although your version number only changed in the third position, indicating (at least in my eyes) just bugfixes, even though you did much more.

To honor your work more in the version number, I suggest to use [semver ](https://semver.org/). Semver is a simple versioning scheme using three positions. Basically the first one is for breaking changes in the API, the second for additional functionality and bugfixes included, and the third for pure bugfixes.

I use KeepassXC now for a while and I would say you could be by version 2.10 or more. I know it is just versioning, but:

- it would honor your work much more in my opinion
- most people would know instantly if it is a release with breaking changes, new functions or bugfixes.

So, it's just a small wish, nothing mandatory, but maybe it would also remove the headache from the developer thinking about which would be the next version number :)

Best Regards

**Comment by droidmonkey** [comment]
I'm not into a strict adherence to "Just Bugfixes". Sometimes adding "features" also fixes bugs and they should not be withheld. We do an excellent job (IMO) of segmenting out which features are major (second digit) and minor (third digit).

**Comment by phoerious** [comment]
It is very unlikely that there will be a version 3.x in the forseeable future (if ever). The reason why all our releases are within the 2.x line is to indicate compatibility with KeePass2. So unless there is a KeePass3 at some point, we will most likely stick to this. Our "major" releases are in the second digit, our "minor" or "patch" releases are in the third digit. Minor releases only contain bug fixes or very small changes which are needed and unlikely to break anything. Actually new features are only introduced in second-digit releases.

**Comment by hoall** [comment]
Ahh ok, I did not know that. Thank you for the info :)
