### ISSUE TITLE
HMAC error, now unable to calc master key (MacOS)

### ISSUE THREAD

**Issue by workrbee** [keepassxreboot/keepassxc#4136]
First problem was HMAC error in two databases (pwd confirmed, Yubikey working). Now getting error Unable to calculate master key. Not a happy day here.

Mac 10.14.6, debug info:

```
KeePassXC - Version 2.5.1
Revision: 0fd8836

Qt 5.13.1
Debugging mode is disabled.

Operating system: macOS Mojave (10.14)
CPU architecture: x86_64
Kernel: darwin 18.7.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
 libgcrypt 1.8.5
```

Tried older version of KPXC (.4.3) but no open success. Suggestions?

**Comment by droidmonkey** [comment]
Any more context? Where are these databases stored? What changes did you do recently? Any patterns?

**Comment by workrbee** [comment]
The databases are stored on a drive that's sync'd with a second computer (resilio sync) but problems started happening when second computer hadn't been on for a couple of days, so no syncing action recently.

Actions: last action was yesterday, saving a couple of new passwords in KPXC then locked the database. No recent system updates, resilio or KPXC updates that I'm aware of. No patterns (other than HMAC errors). KPXC has been working beautifully for days, then this morning (nothing special) not working. Yubikey is recognized, I've checked for typos in password.

No idea what Argon2 settings are. My Activity Monitor says all is well. 

Tried restarting the computer but it didn't change this. I'm perplexed.

**Comment by droidmonkey** [comment]
Unable to calculate master key is a new one for me. Will have to dig into that.

**Comment by workrbee** [comment]
Able to reproduce the Unable to calculate master key error: slot for Yubikey has not been refreshed and still thinks there's a key, only password entered.

**Comment by workrbee** [comment]
Mysteriously, today the passwords work. Same Yubikey as before.

**Comment by droidmonkey** [comment]
I was suspecting a hardware issue like bad RAM.

**Comment by workrbee** [comment]
Will give that a closer look. Thanks.
