### ISSUE TITLE
Missing German Translations

### ISSUE THREAD

**Issue by OLLI-S** [keepassxreboot/keepassxc#4137]
## Missing German translations
In the German UI of KeePassXC 2.5.2 some elements are in English language:
- Edit Entry -> Browser-Integration -> Checkbox "**Use this entry only with HTTP Basic Auth**"
- Edit Entry with a user-defined field that is protected -> Button "**Reveal**"
- Edit Entry with a user-defined field that is protected -> Button "**Hide**"

## Debug Info
KeePassXC - Version 2.5.2
Revision: 62cda9d

Qt 5.13.2
Diagnosemodus ist deaktiviert.

Betriebssystem: Windows 10 (10.0)
CPU-Architektur: x86_64
Kernel: winnt 10.0.18363

Aktivierte Erweiterungen:
- Auto-Type
- Browser-Integration
- SSH-Agent
- KeeShare (bestätigtes und unbestätigtes Teilen)
- YubiKey

Kryptographische Bibliotheken:
 libgcrypt 1.8.5

**Comment by droidmonkey** [comment]
That just means the German translation is not 100% complete. Head on over to https://transifex.com/keepassxc

**Comment by OLLI-S** [comment]
@droidmonkey I registered at transifex and also activated my account.
But when I open the link https://www.transifex.com/keepassxc/ then I get: 

![image](https://user-images.githubusercontent.com/8037790/72091547-b3f6a300-3310-11ea-8b31-d95f78eaae1d.png)

If log in and search for KeePass (https://www.transifex.com/explore/projects/?search=keepass) then I get:

![image](https://user-images.githubusercontent.com/8037790/72091785-3f703400-3311-11ea-8b34-dda5debeaa2e.png)

Am I really too stupid to find your project?

**Comment by droidmonkey** [comment]
Wow their search is terrible!!! Search for keepassxc

**Comment by OLLI-S** [comment]
> Wow their search is terrible!!! Search for keepassxc

Then I found it and I also joined the German translation team.
And now the link https://transifex.com/keepassxc is showing some content.
Means: first I have to register, then I need to search for keepassxc and join the team and then the link will work...

**Comment by OLLI-S** [comment]
I looked up my findings and here are the results:

1. Edit Entry -> Browser-Integration -> Checkbox "Use this entry only with HTTP Basic Auth"

I searched for **HTTP Basic Auth** in in **keepassx_en.ts** and **keepassx_en_2.6.ts**, but I could not find "Use this entry only with HTTP Basic Auth".
Seems like this text is not included in the language files.

2. Edit Entry with a user-defined field that is protected -> Button "Reveal"

I searched for **Reveal** in  **keepassx_en.ts** and found an entry.
But this is already translated correctly!
So do you have a static caption (don't use the text from the language file)?

> 3. Edit Entry with a user-defined field that is protected -> Button "Hide"

I searched for **Hide** in **keepassx_en.ts** and **keepassx_en_2.6.ts**, but no results (for a text that is just "Hide".
So is this button caption not in the language files?

**Comment by phoerious** [comment]
Do not look in the language files, they are auto-generated. You have to look in the cpp files. Everything that is wrapped in `tr(...)` (or `QObject::tr(...)` for that matter) will end up in the language files next time we update them.
