### ISSUE TITLE
No Bépo keyboard support (french dvorak), problem with autotype

### ISSUE THREAD

**Issue by bipox** [keepassxreboot/keepassxc#414]
It will enter login information wrong, for example what should be "bépo" will become qwer (on a qwerty configuration).
I understand this is not a priority, and I'm no developer, but if I can help in any way with this I'd be happy to.

**Comment by TheZ3ro** [comment]
I think it's a duplicate of #324

**Comment by bipox** [comment]
Yes, probably. However phoerious is able to make it work when restarting the program, as I can't make it work, be it starting manually after boot, or closing and relaunching it.
