### ISSUE TITLE
software exception when opened from console and BrowserIntegration is activated

### ISSUE THREAD

**Issue by BARR001** [keepassxreboot/keepassxc#4140]
#3852  Expected Behavior
opening from console without error

## Current Behavior, Testet in 32 bit Portable Version
unknown software exception (0x40000015)
Stelle 0x000000006FF2CD04

## Steps to Reproduce
1. create a database test.kdbx - password = password 
2. activate browserIntegration
3. open it from console like: echo password| "KeePassXC.exe" --pw-stdin "D:\test.kdbx

KeePassXC - 2.5.2
I testet all Versions: 
- Portable 32 and 64 bit
- installed 32 and 64 bit
64 bit versions don't accept password
32 bit versions acceppt password from console but crashes when browserintegration ist activated

Operating system: OS Windows 10
CPU architecture: 64 Bit

Enabled extensions/settings:
- default
- BrowserIntegration

i would be happy if one of the 4 versions would work
thanks from Germany
Rainer

**Comment by BARR001** [comment]
i found the reason for the bug. If browser integration is activated only the last 3 characters are forwardet. But i didn't have a workaround to start without error.

**Comment by droidmonkey** [comment]
Varjolintu could this be because stdin it being sent to the proxy?
