### ISSUE TITLE
You just can't support it properly Wayland????

### ISSUE THREAD

**Issue by xzj8b3** [keepassxreboot/keepassxc#4142]
You just can't support it properly Wayland????

keepassxc-2.5.2-1.fc31.src.rpm

Even with Torbrowser-launcher still doesn't work!!!!!!

![Schermata da 2020-01-09 15-26-01](https://user-images.githubusercontent.com/26720956/72075812-bf3bd580-32f4-11ea-8e6c-62e771568738.png)

**Comment by phoerious** [comment]
Thank you for your insightful bug report.

**Comment by xzj8b3** [comment]
> Grazie per la tua brillante segnalazione.

If I was more experienced I would have reported in more detail it seems obvious, but if I'm not mistaken among you there were those who answered me some time ago would have tested Fedora 31 to solve problems with Torbrowser-launcher and Wayland and certainly knows debugging better than me.

**Comment by xzj8b3** [comment]
> Grazie per la tua brillante segnalazione.

Otherwise tell me how to proceed and I'll try to provide more details

**Comment by phoerious** [comment]
You could start by giving a description of what exactly your problem is instead of insulting us.
But I can tell you already that if the problem is something Wayland-related, there is usually not much we can do. We can only wait for Qt and Gnome to fix their bugs.

**Comment by xzj8b3** [comment]
> Potresti iniziare dando una descrizione di quale sia esattamente il tuo problema invece di insultarci.
> Ma posso già dirti che se il problema è legato a Wayland, di solito non c'è molto che possiamo fare. Possiamo solo aspettare che Qt e Gnome risolvano i loro bug.

But what insult? Well with Torbrowser launcher extension does not go and is now used by Manjaro and many other distributions, already solve that would be great, but unfortunately I do not know how to describe it better ... already solve that would be very positive!!

**Comment by droidmonkey** [comment]
I'm guessing a translator tool has insulted us

**Comment by phoerious** [comment]
I don't think a translator inserts excessive punctuation on it's own.

**Comment by xzj8b3** [comment]
> Non credo che un traduttore inserisca una punteggiatura eccessiva da solo.

I don't think that excessive punctuation can be considered an insult, I think instead keepassxc is a nice tool that could do better solving small gaps and it would be very nice to use it in the future both with Torbrowser-launcer and maybe with Wayland improving the support given the desktop is getting better and better!!

**Comment by droidmonkey** [comment]
The problem is what is perceived as a small gap is usually incredibly time consuming to replicate, identify a fix, test the fix, submit a PR, merge the code, then release. We deal with hundreds of these "tiny" fixes all the time. Unfortunately this one is very specific and likely not going to be worked on.

**Comment by xzj8b3** [comment]
> The problem is what is perceived as a small gap is usually incredibly time consuming to replicate, identify a fix, test the fix, submit a PR, merge the code, then release. We deal with hundreds of these "tiny" fixes all the time. Unfortunately this one is very specific and likely not going to be worked on.

Well, I hope we can improve both things in the future and I'm sorry I don't have enough expertise to give more details about that.

**Comment by tallero** [comment]
@xzj8b3 anch'io non ho capito esattamente che problema stai riscontrando.
