### ISSUE TITLE
Auto-Type Tab greyed out

### ISSUE THREAD

**Issue by supaeasy** [keepassxreboot/keepassxc#4144]
Hello there. I don't know if this is a bug or intended but this bugs me a bit..

## Expected Behavior
When I select an entry, I should be able to navigate to the "Auto-Type" Tab below and view/configure a custom autotype-Sequence ther

## Current Behavior
Tab/Button is greyed out even IF a custom sequence is set. I have to open the entry and navigate on the left side.

## Steps to Reproduce

1. Open Database
2. Click on any entry (not double click)
3. See entry details below. All tabs should be active. Only the first one is.

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.5.2 MacOS (I think same issue applies to Windows version)
Revision: ? (Most recent version)

Operating system: OSX 10.15.2 (also win10)

**Comment by droidmonkey** [comment]
Screenshot?

**Comment by supaeasy** [comment]
<img width="636" alt="screenshot" src="https://user-images.githubusercontent.com/59504964/72140316-cadcda00-3390-11ea-95db-898e0db48d3a.png">

**Comment by supaeasy** [comment]
Nevermind. I just realised that it gets active only when you define custom window settings. It is a little counter-intuitive to me but I feel like this is the intended behaviour. I am closing this as I was just confused.

**Comment by droidmonkey** [comment]
Yes that is only a preview of your entry. You cant edit it from there.
