### ISSUE TITLE
Global Auto-type isn't functional in Vcxsrv

### ISSUE THREAD

**Issue by Vskilet** [keepassxreboot/keepassxc#4149]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Auto-type functionnal in every type of windows, and softwares.

## Current Behavior
[NOTE]: # ( Tell us what actually happens )
When I performed my shortcut to auto-type my password in a windows that execute a Linux desktop in a Xserver, the password isn't send but there is a carriage return.

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1. Launch Vcxsrv
2. SSH on a server that allow the Xforwarding
3. Launch a light desktop
4. Try to auto-type in the terminal in the Vcxsrv

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.5.2
Revision: 62cda9d

Operating system: Windows 10
CPU architecture: x64

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
- libgcrypt 1.8.5

**Comment by droidmonkey** [comment]
This is a duplicate issue. We have one regarding virtual desktops and remote sessions already.
