### ISSUE TITLE
Same database file for several local users

### ISSUE THREAD

**Issue by PeterM-9** [keepassxreboot/keepassxc#415]
I expected to be able to use the same kdbx file for several users on on machine (one after the other not opening the database at the same time) by placing the file in a folder available to all, adding all users to group "keepass" and giving group "keepass" w/r permissions on the file.
However it seems, that only the owner of the kdbx file can open the database (and unlock it with the password). When I chown, the new owner can open the database without problems.
Is this a design decision or am I doing something wrong?
For me it would be very usefull, if I could keep one password database for all my users on a given machine.
I am running Ubuntu 16.04 64bit.

**Comment by droidmonkey** [comment]
You are probably not doing the permissions correctly.

**Comment by PeterM-9** [comment]
All users are in group keepass and the group has read/write access to the file, what other permissions could there be to set?
When the owner of that file (whoever that is in any a given moment) opens it, all works fine.
@droidmonkey do you mean to say, that you are sure my szenario is supposed to work?
Thanks for any tipps

**Comment by phoerious** [comment]
Permissions on that file must be 664 for that to work and you cannot have any additional restrictions via, e.g., AppArmor or SELinux.
We do not put any restrictions on who can access the database file in addition to your file permissions, so this is not a KeePassXC problem.
