### ISSUE TITLE
Always On Top [Windows 10]

### ISSUE THREAD

**Issue by GarlandKey** [keepassxreboot/keepassxc#4151]
## Summary
On the Windows 10 version (at least), there should be an optional feature called "Always on top", which would keep the KeepassXC window on top of all other windows until it's minimized. This will prevent having to click back and forth between applications to enter both the username and password when autofill doesn't work. 

Most Linux Desktop Environments handle the always on top feature pretty well independently. Unfortunately, Windows 10 does not and it makes using KeepassXC very inconvenient to use because it doesn't have the feature built in.

## Desired Behavior
User selects a feature called "Always on top". When activated, all KeepassXC related windows will remain on top of all other windows on the screen until it's minimized.

## Possible Solution
Add a check box that says "Always on top", in Tools > Settings > General > General. In Qt, I'm pretty sure the line would be something like: `@setWindowFlags(Qt::WindowStaysOnTopHint);@` 

## Context
It matters to me because I'm forced to use Windows 10 for certain applications and not having an always on top feature makes using KeepassXC (which I use frequently for multiple VPNs, VMs, Web apps, websites, etc) very annoying. I'm having to swap between windows twice for many apps where autofill doesn't work.

**Comment by droidmonkey** [comment]
This will be a great addition to the new View menu in 2.6.1
