### ISSUE TITLE
Save database automatically every X minutes

### ISSUE THREAD

**Issue by sojusnik** [keepassxreboot/keepassxc#4152]
Similar to "save database after closing" I would prefer to have an option that will save the database after minimizing KeePassXC. I'm aware of the option that saves the database after a change was made, but I don't like the delay (the time when the database is saving) it's causing.

**Comment by droidmonkey** [comment]
I think a better setting would be save every X minutes.

**Comment by sojusnik** [comment]
Was also thinking of this and find your suggestion even better than saving after minimizing the more I think of it.

**Comment by droidmonkey** [comment]
We decided to not implement this feature.
