### ISSUE TITLE
keepassxc-mail

### ISSUE THREAD

**Issue by kkapsner** [keepassxreboot/keepassxc#4154]
I created https://github.com/kkapsner/keepassxc-mail which is a MailExtension for Thunderbird that communicates with KeePassXC. The configuration of the Native Messaging is kind of cumbersome and I would really like to see it as simple as it is for keepassxc-browser. (Actually in my current installation guide I just copy the keepassxc-browser manifest and adjust the names).

So adding a checkbox for "Thunderbird" in the Browser-Integration part of the settings and then doing the same as for "Firefox" but with adjusted addon-name would do the trick.

PS: do you mind that I use the official KeePassXC icon?

**Comment by droidmonkey** [comment]
See #1683 please post to that issue.

**Comment by kkapsner** [comment]
> See #1683 please post to that issue.

Already posted there... or should I add something.

> Just saw that your icon is blue, which is OK

Great - then I will leave it like that.

**Comment by droidmonkey** [comment]
I didn't see your post in the other thread, that will suffice. Thank you!!
