### ISSUE TITLE
Entry list loses focus after entry edit

### ISSUE THREAD

**Issue by AlwaysOn24** [keepassxreboot/keepassxc#4157]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )
ok
## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
open keepassxc, program starts
login
arow down arow down: (fokus now in the list of entries)
ctrl+e: entry opens, edit the titel or anything other
alt + o (save and close of the entry)
arow down or up: focus jumps from one entry to the next, with ctrl+e open is working

## Current Behavior
[NOTE]: # ( Tell us what actually happens )
open keepassxc, program starts
login
arow down arow down: (fokus now in the list of entries)
ctrl+e: entry opens, edit the titel or anything other
alt + o (save and close of the entry)
arow down or up: focus has been lost in the list of entries. ctrl+e open is not working. only with shift+tab the focus is back in the list and can be opened with ctrl+e or browsed with the up and down arrow.

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )
after saving, make sure, the focus is back in the list of entries.

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1. n a
2.
3.

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )
the issue affected me in the way of disrupting my workflow when working just with the keyboard only. the bug forces me, to make additional mouse operations or press shift+tab to regain control of the focus in the list of entries. 

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION
Revision: REVISION
KeePassXC - Version 2.5.2
Revision: 62cda9d
Distribution: Snap

Qt 5.9.5
Debugging mode is disabled.

Operating system: Ubuntu Core 18
CPU architecture: x86_64
Kernel: linux 5.0.0-37-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.1

Libraries:
- LIBS

Operating system: n a
CPU architecture: ARCH na
Kernel: KERNEL na

Enabled extensions:
- EXTENSIONS
na

**Comment by droidmonkey** [comment]
This is not the behavior on Windows 10. Must be a Linux thing...

**Comment by errolpais** [comment]
Verified behavior exists on:
KeePassXC-2.5.2-x86_64.AppImage
Ubuntu 16.04.6 LTS

**Comment by sigmaupsilon** [comment]
I was able to recreate this issue with the latest build on Windows and Linux. In 2.5.2, entryView and groupView are temporarily disabled after the database is edited to ensure it is safely saved and keyboard focus is lost. I can open a PR in a bit.
