### ISSUE TITLE
keepassxc + PassIFox doesn't work with 'Iceweasel(hardened-preferences)'

### ISSUE THREAD

**Issue by darkneptune** [keepassxreboot/keepassxc#416]
keepassxc + PassIFox doesn't work with 'Iceweasel(hardened-preferences)'

## Expected Behavior
passwords should be fieeld in the web pages.

## Current Behavior
no data is filled in the web pages. And PassIFox contextual menu to fill in doesn't work.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* KeePassXC version/commit used: 2.12 (can be found under Help -> About)
* Qt version (e.g. Qt 5.3): 5.8.0
* Compiler (e.g. Clang++3.6.0): -
* Operating System and version: GNU Parabola https://www.parabola.nu/
 
Extension: PassIFox 1.2.2
Browser: Iceweasel (hardened-preferences) GNU Parabola. https://wiki.parabola.nu/Iceweasel
KeePassHttp version: None
pages on which the error occur: all

**Comment by phoerious** [comment]
Can you test if it works with KeePass2 and the KeePassHTTP plugin?

**Comment by darkneptune** [comment]
Hi,

I've tried 3 different password managers: 'keepass' 'keepasx2' and
'keepassxc'.

Together with 'keefox', 'passIfox' web plugins and have copied
'keePassHttp.plgx' into /usr/share/keepassx2.


No results. :(



In other web browser (like 'Icecat') they works:

keepass + keefox
or
keepassxc + passIfox


In 'Icedove (hardened-preferences)', even the message 'keepassfox has
not been configured' doesn't appear (in Icecat it does).

**Comment by phoerious** [comment]
This is not a KeePassXC issue then. You should make sure your browser plugin settings are correct and if they are, file a report to PassIFox.
