### ISSUE TITLE
Toggle password visibility button should timeout

### ISSUE THREAD

**Issue by dadosch** [keepassxreboot/keepassxc#4163]
[TIP]:  # ( Provide a general summary of the feature in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Summary
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
If you enter your password into the field, but then leave KeePassXC open without pressing enter, it may be possible for 3rd parties with access to your pc to reveal your password (or at least the part you typed in)

## Desired Behavior
[NOTE]: # ( Tell us how the new feature should work, be specific )
Toggle password visibility button should not be pressable if no input has been made for a specific amount of time to the main password field.

## Possible Solution
[NOTE]: # ( Not required, but suggest ideas on how to implement the addition or change )

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
Reveiling passwords should only be possible if you are actually at the process of typing the password in, not 10 minutes later

**Comment by droidmonkey** [comment]
This does not make sense. As commented in your other feature, a timeout that clears the password field is preferred.
