### ISSUE TITLE
CLI: show --attributes reveals protected attributes even without --show-protected

### ISSUE THREAD

**Issue by dbulashe** [keepassxreboot/keepassxc#4166]
## Expected Behavior
protected attributes shouldn't be displayed in clear text unless **--show-protected** option is used.

## Current Behavior
**show** command ignores the absence of **--show-protected** option and shows even protected attributes.

## Steps to Reproduce
1. Create an entry **entry** with a protected attribute **protected** in a database **test.kdbx**
2. Execute `keepassxc-cli show test.kdbx entry --attributes protected`

3. The attribute value is shown in a clear text

## Context
![protected attribute](https://user-images.githubusercontent.com/11806243/72222773-bce1b180-3568-11ea-85f4-eef546372606.png)

## Debug Info
KeePassXC - Version 2.5.2
Revision: 62cda9d

Qt 5.12.4
Debugging mode is disabled.

Operating system: Ubuntu 19.10
CPU architecture: x86_64
Kernel: linux 5.4.3-050403-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.4

**Comment by droidmonkey** [comment]
This seems like expected behavior to me. If you are explicitly requesting a particular attribute from the entry, why would we return PROTECTED instead?

**Comment by louib** [comment]
@droidmonkey yeah that was the expected behavior. Maybe we could document that in the manpage and help message if it's not already the case.

**Comment by droidmonkey** [comment]
To me it would be a bug to return the incorrect value....

**Comment by dbulashe** [comment]
@droidmonkey I got your point. I was confused by built-in help:

```keepassxc-cli help show
Usage: keepassxc-cli show [options] database entry
Show an entry's information.

Options:
  -q, --quiet                   Silence password prompt and other secondary
                                outputs.
  -k, --key-file <path>         Key file of the database.
  --no-password                 Deactivate password key for the database.
  -y, --yubikey <slot>          Yubikey slot used to encrypt the database.
  -t, --totp                    Show the entry's current TOTP.
  -a, --attributes <attribute>  Names of the attributes to show. This option
                                can be specified more than once, with each
                                attribute shown one-per-line in the given order.
                                If no attributes are specified, a summary of the
                                default attributes is given.
  -s, --show-protected          Show the protected attributes in clear text.
  -h, --help                    Display this help.

Arguments:
  database                      Path of the database.
  entry                         Name of the entry to show.
```
