### ISSUE TITLE
Health Check - Export Results of Health Check

### ISSUE THREAD

**Issue by OLLI-S** [keepassxreboot/keepassxc#4169]
## Summary
Please let me export the health report (CSV and TXT).
This way I open the exported file and go though it line by line and can change multiple passwords before I have to go back to the health report.
Without the export I have to write down 2-3 entries, change them, run the report again, write down, change and so on.

**Comment by droidmonkey** [comment]
I like this idea!

**Comment by droidmonkey** [comment]
Upon further thought, I don't understand the use case nor do I support exporting metadata from the database in unencrypted form. If we need to add better search/manipulation of reports we should just do that, not export to some other program (excel).
