### ISSUE TITLE
Domain matching not strict enough. xyz.com entry offered for abcxyz.com

### ISSUE THREAD

**Issue by tremby** [keepassxreboot/keepassxc#4170]
## Expected Behavior

Only matching domains and superdomains (if that's the opposite of subdomains) should be offered. If I have an entry for example.com and an entry for otherexample.com, only the entry for otherexample.com should be offered when I visit otherexample.com.

## Current Behavior

If I have an entry for example.com and an entry for otherexample.com, both of these entries are offered when I visit otherexample.com.

## Possible Solution

I'm guessing the matching algorithm is just a bit too permissive. It should maybe check for slash or dot at the start of the match.

## Steps to Reproduce
1. Have password entries for a xyz.com and abcxyz.com
2. Go to abcxyz.com
3. See that KeepassXC offers both of those entries, not just the abcxyz.com one.

## Debug info

KeePassXC - 2.5.2
KeePassXC-Browser - 1.5.4
Operating system: Linux
Browser: Firefox

**Comment by varjolintu** [comment]
I couldn't reproduce this. I tried this with multiple sites, with schemes and without them. Can you provide any more information?

**Comment by tremby** [comment]
1. Go to nytimes.com and click "log in".
2. Add two entries:
    - name: nytimes.com, username: test1, password: test1, domain: nytimes.com
    - name: times.com, username: test2, password: test2, domain: times.com
3. Click the button to fill details
4. See popup. Mine looks like this.

    ![screen](https://user-images.githubusercontent.com/199635/72237611-f1b52f00-358f-11ea-9670-e39be1b25fc2.png)

In the settings, in browser integration, I have "match URL scheme" checked. I do not have "return only best-matching credentials" checked. Let me know what else you might need to know.

**Comment by tremby** [comment]
I see now that my example scenario and issue title are backwards. I was saying the longer entry is offered for the shorter domain, but it's the other way around.

**Comment by tremby** [comment]
I've updated the title and original post. Sorry about the mixup.

**Comment by varjolintu** [comment]
Reproduced it, and found out why it happens. Fixing it already.
