### ISSUE TITLE
Glitch when switching between dark and light mode macOS Catalina

### ISSUE THREAD

**Issue by armin77** [keepassxreboot/keepassxc#4173]
## Expected Behavior
When switching between dark and light mode all ui-elements should reflect the change.

## Current Behavior
In v2.5.2 some ui-elements did not fully reflect the change. Despite the text-color is switching correctly the background is not. 
![Screenshot_2020-01-13 08 09 10_GlLODH](https://user-images.githubusercontent.com/7791321/72238104-1b487780-35dd-11ea-8c82-850aa2494b85.png)
![Screenshot_2020-01-13 08 08 48_4dhCdH](https://user-images.githubusercontent.com/7791321/72238105-1b487780-35dd-11ea-9767-9a69aee6964c.png)

## Steps to Reproduce
Just switch between dark and light mode the App is running

## Debug Info
KeePassXC - Version 2.5.2
Revision: 62cda9d

Qt 5.14.0
Debugging mode is disabled.

Operating system: macOS 10.15
CPU architecture: x86_64
Kernel: darwin 19.2.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
 libgcrypt 1.8.5

**Comment by phoerious** [comment]
That's something Qt had to fix.
