### ISSUE TITLE
Snap package crush with EACCES

### ISSUE THREAD

**Issue by hhemul** [keepassxreboot/keepassxc#4175]
Snap package 2.5.2 fail to run with message "cannot create temporary directory for the root file system: permission denied". While debian package (2.5.2) runs fine. strace shows what keepassxc process fail to create temp directory /tmp/... get EACCES and exits. On my ubuntu 19.10 /tmp is symbolic link with correct permissions (0777) and mkdir /tmp/... works fine with current user. It seems it is some snap issue with kernel namespaces or something similar.

**Comment by droidmonkey** [comment]
Does any snap work for you? We don't request creating /tmp in our program

**Comment by hhemul** [comment]
Yeah it is snap issue not keepassxc. Sorry for bothering you. I should report to snap team.
