### ISSUE TITLE
Customise Toolbar Ability

### ISSUE THREAD

**Issue by rnc** [keepassxreboot/keepassxc#4178]
[TIP]:  # ( Provide a general summary of the feature in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Summary
[NOTE]: # ( Provide a brief overview of what the new feature is all about )

Ability to (like Firefox) customise the toolbar.

## Desired Behavior
[NOTE]: # ( Tell us how the new feature should work, be specific )

I would like to be able to:

- Reorder the elements
- Remove specific elements (this would solve #3539 for specific users then)

This would also help with #505 as users could put the Find option first to prevent it overflowing and becoming hidden.

## Possible Solution
[NOTE]: # ( Not required, but suggest ideas on how to implement the addition or change )

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )

**Comment by droidmonkey** [comment]
This is a lot of overhead for minimal gain.

**Comment by rnc** [comment]
Having had a very brief look at Qt API I see it unfortunately doesn't include an out-of-the-box configurable toolbar option :-( Only libraries such as https://api.kde.org/frameworks/kxmlgui/html/index.html , https://gitlab.com/mattia.basaglia/Qt-Toolbar-Editor seem to provide it but that of course increases the dependencies.

**Comment by droidmonkey** [comment]
If you would like specific changes to the toolbar please post them here and we can discuss.

**Comment by janhajer** [comment]
Personally I would squeeze the 'New entry', the two 'copy ...' and the 'search bar' icons into the limited space I have in my small window. However I doubt that there can be an optimal icon arrangement that makes everybody happy. Hence the repeated wish for more customizability. Just to underline that this can be a bigger issue that it seems. In KDE text alongside icons is the default which makes keepassxc somewhat awkward to use.

![Screenshot_20200901_140103-1](https://user-images.githubusercontent.com/13359942/91849359-38a97f00-ec5c-11ea-8f34-592535c406f7.png)

**Comment by droidmonkey** [comment]
That is not the default. Go to application settings and fix your setting for icons, its at the bottom of the general setting page.

**Comment by toddz262** [comment]
> This is a lot of overhead for minimal gain.

> If you would like specific changes to the toolbar please post them here and we can discuss.

Hope I can reopen this conversation. There may be minimal gain for most users -- but this could benefit senior and other less-techy users who struggle to manage their password load (and those of us who tech-support them.)

I'm setting up KeepassXC for my senior parents -- and I'd love to be able to simplify the toolbar, removing items they'll never need and making the search bar always visible. Icons+text are a necessity, but at a modest screen resolution this forces the search bar into a drop-down menu.

Current situation:
<img width="1358" height="133" alt="Image" src="https://github.com/user-attachments/assets/3378fec2-2fb1-4bfd-988e-06af79a6c3a8" />

Ideal customization:
<img width="995" height="71" alt="Image" src="https://github.com/user-attachments/assets/e2a55a30-71e9-4584-b0b2-23e03294a120" />

A partway solution would be to wrap the toolbar so nothing is hidden. I found one comment about that, in a different context:

> As the window is resized, what about moving the search bar to a second toolbar row of instead of hiding them in an overflow dropdown?

 _Originally posted by @travelalpaca in [#505](https://github.com/keepassxreboot/keepassxc/issues/505#issuecomment-731283256)_

For people already overwhelmed by technology, adopting any additional app is intimidating. As straightforward as it is, KeePassXC could be tweaked to be even more approachable.

**Comment by droidmonkey** [comment]
I would only be open to hiding/showing specific toolbar icons. Not reordering. This would greatly simplify the implementation and meet your use case.

As for multi-level toolbar, that might be possible but need to check the qt options.

**Comment by toddz262** [comment]
> hiding/showing specific toolbar icons... would greatly simplify the implementation and meet your use case

Yes, it would. Thank you for opening the new issue 😊
