### ISSUE TITLE
Open URL not working in snap distribution (menu and shortcut)

### ISSUE THREAD

**Issue by Barjea** [keepassxreboot/keepassxc#418]
KeepassX 2.0.2 with Firefox 52.0 Ubuntu 16.04
select an entry right click menu 'open URL' it opens the corresponding URL -> OK
vs
KeepassXC 2.1.3 with Firefox 52.0 Ubuntu 16.04
select an entry right click menu 'open URL' nothing happens as if this menu is not active. -> not OK
select an entry  CTRL U nothing happens -> not OK
all other shortcuts are OK

tried Chromium : same behaviour KeepassX 2.0.2 OK  vs  KeepassXC 2.1.3 not OK
tried several entries :  same behaviour . Exemple : https://askubuntu.com/users  https://github.com/  etc..

note 
installed KeepassXC 2.1.3 with 
sudo snap install keepassxc

## Your Environment

* KeePassXC version/commit used: (can be found under Help -> About) 2.1.3
* Qt version (e.g. Qt 5.3):  qt5-default  ( Qt 5.1 ?)
* Compiler (e.g. Clang++3.6.0): 
* Operating System and version:  Ubuntu 16.04

**Comment by phoerious** [comment]
Can you try the AppImage or DEB and see if it works? This might be the following problem: https://keepassxc.org/docs#faq-ubuntushortcuts

**Comment by Barjea** [comment]
Hi Janek,

I have tried all 3 options together :*no result*
"

*Why do the tray menu and in-app shortcuts not work on Ubuntu/Unity?*
    This is a bug caused by |appmenu-qt5|.
    You have 3 options:

      * Remove the |appmenu-qt5| package
      * Set the environment variable |UBUNTU_MENUPROXY=''|
      * Set the environment variable |QT_QPA_PLATFORMTHEME=''|

    *Note:* When you choose the first or third option, KeePassXC will
    lose the Unity look and feel. 
"
note : I did set environment variable in /etc/environment

then
remove environment variable
sudo snap remove keepassxc
installed : keepassxc_2.1.3-1_amd64_stable.deb

*Open URL  is now working fine.*
then
sudo apt-get install  appmenu-qt5
*Open URL  is still working fine.

Therefore snap **keepassxc package is the issue
*

**Comment by phoerious** [comment]
When  you set the environment variable in /etc/environment you have to re-login for the changes to be applied. Better set the environment in the terminal with
```
export UBUNTU_MENUPROXY=1
```
and then start KeePassXC from the same terminal instance. But when you didn't have appmenu-qt5 installed in the first place, it's not an appmenu-qt5 bug. When it only happens for the snap package, then we are probably missing some plugs again or so. @droidmonkey can you look into it?

**Comment by droidmonkey** [comment]
This is rather awkward... I found this resource: http://www.ktechpit.com/linux/using-xdg-open-snap-package-open-external-url/

That fix works for normal URL's. There is still a problem with the cmd:// syntax since that uses QProcess to launch the command. This can probably be fixed in a similar manner??

**Comment by uboubo** [comment]
I use a kp.sh
`#/bin/bash
export UBUNTU_MENUPROXY=''
keepassxc`
to get the shortcuts working.

**Comment by droidmonkey** [comment]
Fixed in v2.2.2

**Comment by ekennedy80** [comment]
Issue has raised its ugly head again! Here is the debug info for KeePassXC 2.3.4:

KeePassXC - Version 2.3.4
Revision: 2cc52a8
Distribution: Snap

Libraries:
- Qt 5.9.5
- libgcrypt 1.8.1

Operating system: Ubuntu Core 18
CPU architecture: x86_64
Kernel: linux 4.15.0-34-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey
