### ISSUE TITLE
[one time] App closed and lost info when database lock timeout happened

### ISSUE THREAD

**Issue by BillDietrich** [keepassxreboot/keepassxc#4181]
## Current Behavior
Had database open, opened an entry for editing, typed in the Notes field.  Went away for a while.  I think the "lock database after N minutes idle" timeout went off.  A dialog appeared saying "Lock database ?  You are editing an entry.  Discard changes and lock anyway ?" and two buttons, Discard and Cancel.  I clicked Cancel, and the KeePass app disappeared, gone.  Launched KeePass again, and the text I had added to the Notes field was gone.

Tried three times to replicate this problem, can't get it to happen again.  Will keep trying.

## Debug Info
KeePassXC - Version 2.5.2
Revision: 62cda9d

Qt 5.9.5
Debugging mode is disabled.

Operating system: Linux Mint 19.3
CPU architecture: x86_64
Kernel: linux 5.3.0-24-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.1

**Comment by droidmonkey** [comment]
Sounds like the application crashed if it totally disappeared. Will try to replicate as well.

**Comment by droidmonkey** [comment]
I could not replicate this either. There is not functional difference between locking the database with Ctrl+L and the timeout lock. I'm going to close this unless you can replicate.
