### ISSUE TITLE
Warning and error related to application v.2.5.2 as Appimage

### ISSUE THREAD

**Issue by Ricky-Tigg** [keepassxreboot/keepassxc#4183]
**OS**: Fedora; **Environment**: Gnome; **File**: /KeePassXC-2.5.2-x86_64.AppImage, renamed _keepassxc_.
```
$ file -b keepassxc
ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.18, stripped
```
Despite the application can be launched in a Wayland session, the following output is produced:
```
$ ./keepassxc
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
```
Following output is produced both in Wayland and X sessions.
```
$ firejail --appimage --private --noprofile ./keepassxc
Mounting appimage type 2
Error mounting appimage: appimage.c:119 appimage_set: Invalid argument
```
Issue: Appimage types reported in `file` and `firejail` outputs **differ from each other**.

It seems possible to integrate file's _check-sum_ into the file while compiling it as format Appimage. One case is from [cpvrlab Imageplay](https://imageplay.io/).
```
$ file -b imageplay
ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.18, BuildID[sha1]=d629f6099d2344ad82818172add1d38c5e11bc6d, stripped
```

**Comment by droidmonkey** [comment]
I don't understand what the problem is.

**Comment by Ricky-Tigg** [comment]
Is it just you?

**Comment by Ricky-Tigg** [comment]
At last you realized; you don't understand.
