### ISSUE TITLE
Is there a way to provide password+OTP string via the browser extension?

### ISSUE THREAD

**Issue by diggnsaegg** [keepassxreboot/keepassxc#4185]
[TIP]:  # ( Provide a general summary of the feature in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Summary
I setup OTP login for a website. To login I need to provide the password + an TOTP token in the same field, so for example: passw0rd377231
I setup a custom auto type sequence like this: {USERNAME}{TAB}{PASSWORD}{TOTP}{ENTER}

This works indeed when I press STRG + SHIFT + V or simply right-click on the entry in KeePassXC.

It doesn't work from the browser extension. I provided username and password for the entry, so the extension fills these fields as expected but not the TOTP. A right click into the field and selecting "Fill  TOTP" simply overwrites the password.

## Desired Behavior
Use custom autotype-sequence I setup for specific entry.

## Possible Solution
Let the browser extension autofill by custom autotype-sequences.

## Context
I'm lazy ;)

**Comment by droidmonkey** [comment]
We chose not to support these rare edge cases in the browser plugin since it greatly complicates the setup and workflow. Auto-Type, as you have seen, is the preferred workaround and it is sufficient without over complication.

**Comment by s-v-o** [comment]
I don't think that this is an edge case. Many sites with 2FA need to enter a password or pin together with the TOTP. So all this sites cannot be filled by the browser integration (for me the most attractive advantage of keepassxc over keepass).
