### ISSUE TITLE
Health Report - Advanced Check for Insecure Passwords (dictionary)

### ISSUE THREAD

**Issue by OLLI-S** [keepassxreboot/keepassxc#4186]
## Summary
Add an advanced check for insecure passwords (check against a dictionary)

## Desired Behavior
We all know that passwords should not contain normal words that can be found in a dictionary, because hackers use word lists to attack passwords via brute force/rainbow tables.
I am not an security expert, but you know what I mean.

Adding numbers or symbols at the beginning or at the end of normal words makes passwords also not safe. 
Also replacing single letters with special characters (like replacing an "a" with an "@" or replacing an "i" with "1") is not a good idea, because hackers know this trick. 

So here are some examples of weak and Insecure passwords:
- J@nu@ry01
- p@$$w0rd
- n00b
- all words from a normal dictionary (with or without numbers at the end, like "vase" or "vase01")
- names (with or without numbers at the end, like "Oliver" or "Oliver01")

It would be great if KeePassXC warns me if I use such insecure passwords. 
Here I don't mean pwned passwords, that can be found in Have I Been Pwned. 
I mean insecure passwords that can be found in dictionaries (like described above)

I don't know id there is a **web service** that checks the security of passwords (like you have "Have I Been Pwned" for pwned passwords).

When I search for "check password security" then I find these websites where users can check their passwords:
- https://howsecureismypassword.net/
- https://password.kaspersky.com/de/
- http://www.passwordmeter.com/
- https://www.my1login.com/resources/password-strength-test/
- https://lastpass.com/howsecure.php
Maybe these links are useful to test this feature (test the results of the password strength report).

When I search for "check password security" then I find these services
- https://www.codeproject.com/Articles/19245/Google-Password-Strength-API
- https://www.enzoic.com/docs-passwords-api/
- https://cmatskas.com/password-validation-and-creation-using-a-public-api/
I am not a programmer, so I don't know if these links are helpful (at least I tried).

I think **programming this manually** is a lot of work, because you would have to:
- convert the password to lower case
- replace symbols with the corresponding characters (like convert an "@" to "a")
- remove leading and trailing symbols
- remove leading and trailing numbers
- check if the password is in a dictionary (multiple languages)

My intention is to tell users if they are using insecure passwords.
I know that this is a huge task and much to code, but this would increase password quality in KeePassXC.

**Comment by droidmonkey** [comment]
This is exactly what the "weak password" indicator represents. Zxcvbn does this check already when determining entropy.

**Comment by OLLI-S** [comment]
@droidmonkey Sorry for the stupid question: where do I see the password strength for an existing entry?
If I edit the entry I don't see this below the "Password" and "Repeat" fields (also when I show the passwords).
When I start the password generator in the edit window I see the password strength for the generated password (not for the existing one).

**Comment by droidmonkey** [comment]
There is a feature request to add the meter to the existing password fields

**Comment by OLLI-S** [comment]
This is so embarrassing for me.
I wrote a suggestion (this took me also some time, worked it over several times to make it perfect) for a feature that is already existing.
