### ISSUE TITLE
kdbx file does not open in KeePassXC but opens in KeePass

### ISSUE THREAD

**Issue by gottfired** [keepassxreboot/keepassxc#4190]
## Expected Behavior
Expect File to open after entering master password

## Current Behavior
When opening the file I get the error: "Invalid EnableSearching value"

## Possible Solution
This issues from KeeWeb seems similar, so I assume it might help: https://github.com/keeweb/keeweb/issues/23#issuecomment-155290463

## Steps to Reproduce
Can't provide steps, since it would involve exposing my master keepass db

## Context
I share a keepass file via dropbox between macos, windows and ios. So somehow the EnableSearching flag seems to get written with a value, that cannot be read by KeePassXC, but opens fine with KeePass on Windows and StrongBox on iOS

## Debug Info
KeePassXC - 2.5.2
Revision: 62cda9d

Libraries:
- LIBS

Operating system: Windows 10
CPU architecture: Intel 
Kernel: KERNEL

Enabled extensions:
- EXTENSIONS

**Comment by droidmonkey** [comment]
If your database is not kdbx 4 I recommend upgrading it now to see if that clears the error.

**Comment by gottfired** [comment]
That helped. Thanks!

**Comment by ghost** [comment]
My database was already kdbx 4, but I used Google Drive for Desktop (The new one) for syncing, it may be the problem.

**Comment by snhrdt** [comment]
I just encountered this issue, with a kdbx 4 database and KeepassXC 2.6.6. The database was fine with a previous release of KeepassXC (2.5.X), and it still can be opened without any issues with Keeweb.

This is on macOS Big Sur.

I would suggest to re-open this issue.

**Comment by droidmonkey** [comment]
You may have updated it to KDBX 4.1 if you used a more recent version of KeePass 2.

**Comment by snhrdt** [comment]
@droidmonkey Thanks for the hint! In my case, only KeepassXC (2.5.X and 2.6.6) and Keeweb were involved, I do not use Keepass.

**Comment by droidmonkey** [comment]
Keeweb has been known to make a database non functional in the past. Try opening this in keepass 2.

**Comment by ghost** [comment]
I forgot this discussion even existed, so I forgot to update: KeeWeb is the problem, I then used [StrongBox](https://strongboxsafe.com/) then synchronized the database to fix it.
I forgot how it even does this in the first place, but if I have to guess, it would be that it is empty?

**Comment by eliandoran** [comment]
I have had the same issue when opening a file created in KeeWeb in KeePassXC.

I was able to analyze the issue and it appears that the .xml dump contains invalid values for some elements, such as:
```xml
<EnableSearching/>
```
Where the value should be `true`, `false`, or `null`. These self-closing elements containing no value are also present in the "meta" information of the databases.

Since I've had multiple databases affected by this, I've created a script which tries to automatically solve these issues. If you are interested, it can be found here https://github.com/eliandoran/fix-keeweb-kdbx. For more information on how it works: https://github.com/eliandoran/fix-keeweb-kdbx/blob/master/How-it-works.md

**Comment by droidmonkey** [comment]
This needs to be reported to keeweb as they are not following the standard.

**Comment by KaKi87** [comment]
Hi,

KeeWeb is unmaintained, and I'm not on Mac but Linux, how could I open my database on KeePassXC despite experiencing this error ?

Thanks

**Comment by droidmonkey** [comment]
Hi this is 3 years old and cannot speak to this issue anymore.
