### ISSUE TITLE
Add new field "email address" to KP entries

### ISSUE THREAD

**Issue by digisus** [keepassxreboot/keepassxc#4191]
## Summary
Many users attach the email address they used when registering on a website to the respective KP entry, especially if they have more than one email address in use. 

## Desired Behavior
When editing a new entry in KP, I want to be able to add an email address specific to that entry. For example, the email address I used to register for a paid service or banking account, etc. because they are essential in recovering passwords and managing the account.
To make it even more comfortable, I'd like to be able to register several email addresses in the KP database and then select from a drop-down list whenever I create/edit a new entry in KP.

## Context
Most websites today need an email address for registration and many of us have more than one address in use. KP already tracks/stores password, login, and URL for each entry. The email address would simply complete the set of core attributes of an entry and make managing registered email addresses less faulty and easier.

Thank you for considering this proposal - and thank you for providing a trusted store for passwords.

**Comment by droidmonkey** [comment]
This is a literal duplicate

**Comment by digisus** [comment]
Ugh, sorry for that.My search was not good enough. Great that it is on the list.

**Comment by droidmonkey** [comment]
Nice feature request though!
