### ISSUE TITLE
Problem with keepassxc browser extension on new Microsoft Edge browser (Chromium based)

### ISSUE THREAD

**Issue by gfrangiamone** [keepassxreboot/keepassxc#4195]
I encounter a problem with Keepassxc browser extension on new Microsoft Edge browser (Chromium based).

Using latest release of extension (1.5.4) I get this error: The exchange of keys failed.

In the same PC, Keepassxc browser extension on Chrome works correctly.

Thanks
Giuseppe

**Comment by droidmonkey** [comment]
I'm going to assume you are not running the release/2.5.3 build

**Comment by gfrangiamone** [comment]
I'm running the release 2.5.2. Now I try to install and use also latest KeePassXC Snapshot Builds but the result don't change.

**Comment by droidmonkey** [comment]
Snapshot doesn't have this feature in it yet

**Comment by donamk** [comment]
I hope KeePassXC supports the Edge browser soon.

**Comment by donamk** [comment]
@droidmonkey Today, I installed 2.5.3 build but still not working with Edge

**Comment by droidmonkey** [comment]
Did you enable it in the browser integration settings?

**Comment by donamk** [comment]
@droidmonkey  Yes, I enabled the browser integration settings for the edge. I don't know what was wrong but now It works well after update(uninstall and then reinstall) to the latest edge(Version 79.0.309.71). I cannot solve the issue with reinstall KeePassXC or KeePassXC-Browser.
