### ISSUE TITLE
Hide entry notes isn't consistent

### ISSUE THREAD

**Issue by gelldur** [keepassxreboot/keepassxc#4197]
![image](https://user-images.githubusercontent.com/175790/72662159-34d62e80-39e4-11ea-9d25-77a3ca1cf41d.png)

## Expected Behavior
I shouldn't see notes in table view

## Current Behavior
I see "hidden" stuff

## Steps to Reproduce
Setting -> Security -> Hide entry notes by default

## Debug Info
KeePassXC - Version 2.5.2
Revision: 62cda9d

Qt 5.14.0
Debugging mode is disabled.

Operating system: Manjaro Linux
CPU architecture: x86_64
Kernel: linux 5.4.6-2-MANJARO

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.5

**Comment by droidmonkey** [comment]
Good catch!

**Comment by droidmonkey** [comment]
This is fixed already!
