### ISSUE TITLE
Binary or Installation Guide for MacOS Sierra

### ISSUE THREAD

**Issue by andikade** [keepassxreboot/keepassxc#42]
Hey!

I found this project today. I downloaded the sources and tried to compile a binary it with CMake but it didn't work (...I could pass QT5 to CMake but however not libgcrypt). Do you have a Step-by-Step Installation Guide or a binary for MacOS Sierra?

Thank you in advance.
andikade

**Comment by TheZ3ro** [comment]
If you have brew installed, execute this in a Terminal
`brew install libgcrypt`

I was planning to write some Guide but we have other things to do atm.

**Comment by droidmonkey** [comment]
This needs to be included in the Readme. I'd accept a pull request to develop once you figure it out.

**Comment by TheZ3ro** [comment]
I will take care of this once @andikade confirm that it works :wink:

**Comment by droidmonkey** [comment]
On a side note, I need to re-enable the travis-ci build for osx.

**Comment by andikade** [comment]
Thanks for your hints. I think I figured it out!  Here is what I did.

Install Homebrew (it is the easiest way to install the required packages on macOS):
`/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"`

Then install the required libraries (zlib already exists on macOS Sierra so it is not needed to install it):
```
brew install cmake
brew install qt5
brew install libgcrypt
brew install libmicrohttpd
```
Note the version of qt5 because we use later.

Navigate to the path you want to install KeePassX and then download the current version of KeePassX from GitHub to your local drive:
 ```
cd /Users/{insert_your_user}/Applications/
mkdir KeePassXR
cd KeePassXR
git clone https://github.com/keepassxreboot/keepassx.git
```

Build it. You need to provide the path to qt5 and run it as root. Adapt the path with the right version:
`cd keepassx`
`cmake -DCMAKE_PREFIX_PATH=/usr/local/Cellar/qt5/5.6.2/lib/cmake/`
`make`

Now you should find a program called KeePassX in the src folder.

At last, create a package (.dmg) which can be mounted. The drag & drop KeePassX to the application folder and you're ready:
`make package`

**Comment by TheZ3ro** [comment]
Seems that application's icon can't load (in the top menu every button should have an Icon).

Can you try a `make install` from the KeePassXR folder?

Reopening this

**Comment by andikade** [comment]
@TheZ3ro You are right. All icons are missing including the ones for the menu, entries and groups except the ones I imported manually. I will check that and respond.

**Comment by TheZ3ro** [comment]
Thanks a lot for the testing :+1:

**Comment by harizvi** [comment]
Does the Mac version have both keepass-http and autotype working?  I see mentions of keepass-http all over, but not the auto-type, hence the question. I'm using eugenesan's version with keepass-http, but without auto-type.

**Comment by TheZ3ro** [comment]
@harizvi at the moment auto-type works only on Linux, we are working on porting it to other platforms

**Comment by TheZ3ro** [comment]
I have written the [Installation instruction](https://github.com/keepassxreboot/keepassx/wiki/Install-Instruction-from-Source) and the [Building Env on MacOS](https://github.com/keepassxreboot/keepassx/wiki/Building-Environment-on-MacOS) from @andikade fork.

If it's all right I will close this issue with an edit to the README.md pointing to the Wiki

**Comment by agunnerson-ibm** [comment]
@TheZ3ro The packages I build following those instructions seem to crash at startup.

I'm building with:
```sh
cmake .. -DWITH_TESTS=OFF -DCMAKE_PREFIX_PATH=/usr/local/Cellar/qt5/5.7.0/lib/cmake -DCMAKE_BUILD_TYPE=Release
make -j8
make package
```

Dependencies:
```
cmake-3.6.2
qt5-5.7.0
libgcrypt-1.7.3
libmicrohttpd-0.9.51
```

Crash log: https://gist.github.com/agunnerson-ibm/a5e22bbe773b1cc15431cf3850585ee9

Files included in `KeePassX.app`: https://gist.github.com/agunnerson-ibm/cff7af5c0a0cf7c11927b7e1b600668a

If I try to run `/Applications/KeePassX.app/Contents/MacOS/KeePassX` manually, I get the following:

```
This application failed to start because it could not find or load the Qt platform plugin "cocoa"
in "".

Reinstalling the application may fix this problem.
[1]    53014 abort      /Applications/KeePassX.app/Contents/MacOS/KeePassX
```

**Comment by TheZ3ro** [comment]
@agunnerson-ibm Thanks for the feedback.
While I'm investigating the problem can you open a new Issue? 
So we keep this for the documentation and the new one for your problem.
Thanks

**Comment by agunnerson-ibm** [comment]
@TheZ3ro Thanks, will do! I've just created #60
