### ISSUE TITLE
Keepassxc requires Yubikey (with challenge auth) for each save

### ISSUE THREAD

**Issue by rajil** [keepassxreboot/keepassxc#4202]
Keepass (with keechallenge) only needed the Yubikey to open the database. However, Keepassxc needs the Yubikey for each save. Is it possible to disable that behavior?

**Comment by droidmonkey** [comment]
No it's not and we are not going to change this behavior because it dramatically increases security. The reason the key it required on save is because every save randomizes the nonce that forms the challenge.
