### ISSUE TITLE
The AppImage distribution of the 2.5.3 release requires GLIBC 2.30 to function

### ISSUE THREAD

**Issue by amvasilyev** [keepassxreboot/keepassxc#4204]
## Expected Behavior

The KeePassXC release 2.5.3 should be running fine from the AppImage distribution.

## Current Behavior

When trying to execute the latest release on Debian Testing the KeePassXC does not start due to library version mismatch:

```
keepassxc: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.30' not found (required by /tmp/.mount_keepas7zC5CZ/usr/lib/libsystemd.so.0)
keepassxc: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.30' not found (required by /tmp/.mount_keepas7zC5CZ/usr/lib/libudev.so.1)
```
Currenly Debian Testing provides GNU LibC 2.29, Debian Stable - 2.28.

## Possible Solution

Please downgrade the AppImage build environment, so it will not depend upon the latest GNU LibC release.

## Steps to Reproduce

1. Download the latest AppImage distribution.
2. Make it executable.
3. Try to execute it.

## Debug Info

Unavailable on 2.5.3. 

Portions of debug info from 2.5.2 that runs without errors.

KeePassXC - Версия 2.5.2
Revision: 62cda9d
Distribution: AppImage

Qt 5.12.6

OS: Debian GNU/Linux bullseye/sid
CPU Architecture: x86_64
Kernel: linux 5.4.0-2-amd64

Enabled extensions:
- Autoinput
- Browser integration
- SSH-agent
- KeeShare 
- YubiKey
- Secret Service integration

Libraries:
 libgcrypt 1.8.1

**Comment by phoerious** [comment]
Right, totally my bad. I built it on the wrong base image. Will upload another one in the evening.

**Comment by amvasilyev** [comment]
Thank you! Will be waiting for the new release.

**Comment by phoerious** [comment]
Builds are updated.
