### ISSUE TITLE
Yubikey not detected if already plugged in

### ISSUE THREAD

**Issue by ibahnasy** [keepassxreboot/keepassxc#4205]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Yubikey should be detected when the 'refresh' button is pressed in all cases.

## Current Behavior
[NOTE]: # ( Tell us what actually happens )
If the yubikey is already plugged in before launching KeePassXC, it won't be detected even after a refresh.

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1. Plug the Yubikey.
2. Launch KeePassXC.
3. Try to unlock the DB or refresh for the hardware token.

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.5.2
Revision: 62cda9d

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 5.4.13-arch1-1

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

**Comment by droidmonkey** [comment]
Dup #4065
