### ISSUE TITLE
Update Search Modifiers Documentation

### ISSUE THREAD

**Issue by nod0n** [keepassxreboot/keepassxc#4206]
Hello

The searchbox supports "Search Modifiers". I tested the modifier "!" and "-". Both did the same. "!" is listed in "Search Help" (https://i.imgur.com/Ajqy0yU.png) and "-" is listed in the "User Guide" (https://i.imgur.com/2ij7Bvj.png). I suggest deciding on which one "shall be used" (even if both are supported, maybe because of backwards compatibility, or for other reasons) and then refer to it in both places: "Search Help" and "User Guide"

Salutations
Nodøn

If required:

Operating system: GNU/Linux Ubuntu 18.04 (with ppa: deb http://ppa.launchpad.net/phoerious/keepassxc/ubuntu bionic main)
CPU architecture: x86_64
Kernel: Linux 5.3.0-26-generic #28~18.04.1-Ubuntu SMP Wed Dec 18 16:40:14 UTC 2019

KeePassXC - Version 2.5.3
Revision: f8c962b

Qt 5.13.2
Debugging mode is disabled.

Operating system: KDE neon User Edition 5.17
CPU architecture: x86_64
Kernel: linux 5.3.0-26-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.1

**Comment by droidmonkey** [comment]
Should also take this moment to convert the search documentation into HTML so it doesn't look terrible on different platforms.

**Comment by nod0n** [comment]
thx. :+1:
