### ISSUE TITLE
Build on RHEL 7.7 fails

### ISSUE THREAD

**Issue by popxunga** [keepassxreboot/keepassxc#4207]
Hi Team ...

Build on RHEL 7.7 failing for 2.5.2 and 2.5.3 versions.

## Expected Behavior
The error bellow didn't occur with 2.5.1 version and previous versions.

## Current Behavior
While building I get this in the terminal:
[ 41%] Linking CXX static library libkeeshare.a
cd /home/xxxxxxxx/rpmbuild/BUILD/keepassxc-2.5.3/build/src/keeshare && /usr/bin/cmake3 -P CMakeFiles/keeshare.dir/cmake_clean_target.cmake
cd /home/xxxxxxxx/rpmbuild/BUILD/keepassxc-2.5.3/build/src/keeshare && /usr/bin/cmake3 -E cmake_link_script CMakeFiles/keeshare.dir/link.txt --verbose=1
/usr/bin/ar qc libkeeshare.a  CMakeFiles/keeshare.dir/keeshare_autogen/mocs_compilation.cpp.o CMakeFiles/keeshare.dir/SettingsPageKeeShare.cpp.o CMakeFiles/keeshare.dir/SettingsWidgetKeeShare.cpp.o CMakeFiles/keeshare.dir/DatabaseSettingsPageKeeShare.cpp.o CMakeFiles/keeshare.dir/DatabaseSettingsWidgetKeeShare.cpp.o CMakeFiles/keeshare.dir/group/EditGroupWidgetKeeShare.cpp.o CMakeFiles/keeshare.dir/group/EditGroupPageKeeShare.cpp.o CMakeFiles/keeshare.dir/KeeShare.cpp.o CMakeFiles/keeshare.dir/KeeShareSettings.cpp.o CMakeFiles/keeshare.dir/ShareImport.cpp.o CMakeFiles/keeshare.dir/ShareExport.cpp.o CMakeFiles/keeshare.dir/ShareObserver.cpp.o CMakeFiles/keeshare.dir/Signature.cpp.o
/usr/bin/ranlib libkeeshare.a
make[2]: Leaving directory `/mnt/mydata/Development/rpmbuild/BUILD/keepassxc-2.5.3/build'
[ 41%] Built target keeshare
make[1]: Leaving directory `/mnt/mydata/Development/rpmbuild/BUILD/keepassxc-2.5.3/build'
make: *** [all] Error 2
error: Bad exit status from /var/tmp/rpm-tmp.PSTCvQ (%build)

RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.PSTCvQ (%build)

**In the CMakeError.log I see this:**
Performing C++ SOURCE FILE Test HAVE_MALLOC_USABLE_SIZE failed with the following output:
Change Dir: /home/xxxxxxxx/rpmbuild/BUILD/keepassxc-2.5.3/build/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/gmake cmTC_32a10/fast 
/usr/bin/gmake -f CMakeFiles/cmTC_32a10.dir/build.make CMakeFiles/cmTC_32a10.dir/build
gmake[1]: Entering directory `/mnt/mydata/Development/rpmbuild/BUILD/keepassxc-2.5.3/build/CMakeFiles/CMakeTmp'
Building CXX object CMakeFiles/cmTC_32a10.dir/src.cxx.o
/usr/bin/c++    -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic -fno-common -Wall -Wextra -Wundef -Wpointer-arith -Wno-long-long -Wformat=2 -Wmissing-format-attribute -fvisibility=hidden -fvisibility-inlines-hidden -fstack-protector --param=ssp-buffer-size=4 -fno-exceptions -fno-rtti -Wnon-virtual-dtor -Wold-style-cast -Woverloaded-virtual -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -Werror=format-security -Wcast-align -pie -fPIE -std=c++11 -Wno-deprecated-declarations -DHAVE_MALLOC_USABLE_SIZE   -o CMakeFiles/cmTC_32a10.dir/src.cxx.o -c /home/xxxxxxxx/rpmbuild/BUILD/keepassxc-2.5.3/build/CMakeFiles/CMakeTmp/src.cxx
/home/xxxxxxxx/rpmbuild/BUILD/keepassxc-2.5.3/build/CMakeFiles/CMakeTmp/src.cxx: In function 'int main()':
/home/xxxxxxxx/rpmbuild/BUILD/keepassxc-2.5.3/build/CMakeFiles/CMakeTmp/src.cxx:2:44: error: too many arguments to function 'size_t malloc_usable_size(void*)'
     int main() { malloc_usable_size(NULL, 0); return 0; }
                                            ^
In file included from /home/xxxxxxxx/rpmbuild/BUILD/keepassxc-2.5.3/build/CMakeFiles/CMakeTmp/src.cxx:1:0:
/usr/include/malloc.h:151:15: note: declared here
 extern size_t malloc_usable_size (void *__ptr) __THROW;
               ^
gmake[1]: *** [CMakeFiles/cmTC_32a10.dir/src.cxx.o] Error 1
gmake[1]: Leaving directory `/mnt/mydata/Development/rpmbuild/BUILD/keepassxc-2.5.3/build/CMakeFiles/CMakeTmp'
gmake: *** [cmTC_32a10/fast] Error 2

Source file was:
#include <malloc.h>
    int main() { malloc_usable_size(NULL, 0); return 0; }

## Environment
KeePassXC - 2.5.3
Revision: 1

Operating system: RHEL 7.7
CPU architecture: x86_64
Kernel: 5.4.13-1 (elrepo)

Thanks.

**Comment by phoerious** [comment]
This looks like your compiler does not support sized deallocation, but I don't recall changing anything in that area in 2.5.2.
There are users here building AppImages on RHEL using our `release-tool` and our Ubuntu 14.04 Docker image. I don't think KeePassXC builds natively on RHEL anymore.

**Comment by popxunga** [comment]
Hi @phoerious ...
Thanks for your feedback.
Just to make sure, I just successfully tested the rebuild of keepassxc 2.5.1 on my RHEL 7.7.
In order to make this possible, I do to use modified versions of libgpg-error (1.33) and libgrypt18 (1.8.2) libs and a slightly modified spec file.
Like before, I'm using the source rpm keepassxc packages from koji for the latest Fedora dist.
I suspect that this issue is not due to keepassx source modifications, but to modifications in the build process.
Any suggestion that may help investigating this ?

**Comment by tuxmaster5000** [comment]
I use the gcc 9.1 which comes from the the devtoolset-9.
But I fails at:
https://github.com/keepassxreboot/keepassxc/issues/3223

**Comment by popxunga** [comment]
> I use the gcc 9.1 which comes from the the devtoolset-9.
> But I fails at:
> #3223

Hi @tuxmaster5000 
Thanks for the devtoolset-9 tip.
I just built from the 2.6.0 develop branch successfully thanks to your patch.
How have you solved the libgcrypt requirement ? 
Are you using the libgcrypt18 as well ?
Thanks a lot !

**Comment by popxunga** [comment]
Hi @tuxmaster5000 
Just figured out how to build a libgcrypt 1.8 from it's latest version available on Koji, with just a couple of minimal changes in the spec and renaming the base directory name inside the 1.8.5-3 hobble tar.xz.
So all good now. Thanks !

**Comment by popxunga** [comment]
Closing.

**Comment by tuxmaster5000** [comment]
I have linked the actual version of libgcrypt and libgpg-error static.

**Comment by popxunga** [comment]
Hi @tuxmaster5000 ...
I tried to apply the patch against the 2.5.3 code and the build fails near the end. 

This is what I'm getting:
[100%] Linking CXX shared module libkeepassx-autotype-xcb.so
cd /home/xxxxxxxx/rpmbuild/BUILD/keepassxc-2.5.3/build/src/autotype/xcb && /usr/bin/cmake3 -E cmake_link_script CMakeFiles/keepassx-autotype-xcb.dir/link.txt --verbose=1
/opt/rh/devtoolset-9/root/usr/bin/c++ -fPIC -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic -fno-common -Wall -Wextra -Wundef -Wpointer-arith -Wno-long-long -Wformat=2 -Wmissing-format-attribute -fvisibility=hidden -fvisibility-inlines-hidden -fstack-protector-strong -fno-exceptions -fno-rtti -Wnon-virtual-dtor -Wold-style-cast -Woverloaded-virtual -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -Werror=format-security -Wcast-align -pie -fPIE -std=c++11 -fsized-deallocation -Wno-deprecated-declarations -DNDEBUG -Wl,-z,relro -Wl,--no-add-needed -Wl,--as-needed -Wl,-z,relro,-z,now -shared  -o libkeepassx-autotype-xcb.so CMakeFiles/keepassx-autotype-xcb.dir/keepassx-autotype-xcb_autogen/mocs_compilation.cpp.o CMakeFiles/keepassx-autotype-xcb.dir/AutoTypeXCB.cpp.o ../../libkeepassx_core.a /usr/lib64/libQt5X11Extras.so.5.9.7 -lX11 -lXi -lXtst ../../libautotype.a ../../browser/libkeepassxcbrowser.a ../../qrcode/libqrcode.a /usr/lib64/libQt5Svg.so.5.9.7 -lqrencode ../../fdosecrets/libfdosecrets.a /usr/lib64/libQt5Concurrent.so.5.9.7 -lsodium -lyubikey -lykpers-1 ../../libzxcvbn.a -largon2 -lz ../../sshagent/libsshagent.a /usr/lib64/libQt5Network.so.5.9.7 ../../keeshare/libkeeshare.a /usr/lib64/libQt5Widgets.so.5.9.7 ../../crypto/ssh/libcrypto_ssh.a -lquazip5 /usr/lib64/libQt5DBus.so.5.9.7 -lgcrypt -lgpg-error /usr/lib64/libQt5Gui.so.5.9.7 /usr/lib64/libQt5Core.so.5.9.7 
/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld: CMakeFiles/keepassxc.dir/main.cpp.o: in function `main':
/home/xxxxxxxx/rpmbuild/BUILD/keepassxc-2.5.3/src/main.cpp:62: undefined reference to `Application::Application(int&, char**)'
/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld: /home/xxxxxxxx/rpmbuild/BUILD/keepassxc-2.5.3/src/main.cpp:67: undefined reference to `Bootstrap::bootstrapApplication()'
/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld: /home/xxxxxxxx/rpmbuild/BUILD/keepassxc-2.5.3/src/main.cpp:62: undefined reference to `Application::~Application()'
/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld: /home/xxxxxxxx/rpmbuild/BUILD/keepassxc-2.5.3/src/main.cpp:101: undefined reference to `Application::isAlreadyRunning() const'
/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld: /home/xxxxxxxx/rpmbuild/BUILD/keepassxc-2.5.3/src/main.cpp:103: undefined reference to `Application::sendFileNamesToRunningInstance(QStringList const&)'
/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld: /home/xxxxxxxx/rpmbuild/BUILD/keepassxc-2.5.3/src/main.cpp:111: undefined reference to `Crypto::init()'
/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld: /home/xxxxxxxx/rpmbuild/BUILD/keepassxc-2.5.3/src/main.cpp:132: undefined reference to `MainWindow::MainWindow()'
/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld: /home/xxxxxxxx/rpmbuild/BUILD/keepassxc-2.5.3/src/main.cpp:138: undefined reference to `Bootstrap::restoreMainWindowState(MainWindow&)'
/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld: /home/xxxxxxxx/rpmbuild/BUILD/keepassxc-2.5.3/src/main.cpp:148: undefined reference to `Utils::STDOUT'
/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld: /home/xxxxxxxx/rpmbuild/BUILD/keepassxc-2.5.3/src/main.cpp:148: undefined reference to `Utils::getPassword(_IO_FILE*)'
/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld: /home/xxxxxxxx/rpmbuild/BUILD/keepassxc-2.5.3/src/main.cpp:132: undefined reference to `MainWindow::~MainWindow()'
/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld: /home/xxxxxxxx/rpmbuild/BUILD/keepassxc-2.5.3/src/main.cpp:129: undefined reference to `Config::createConfigFromFile(QString const&)'
/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld: /home/xxxxxxxx/rpmbuild/BUILD/keepassxc-2.5.3/src/main.cpp:152: undefined reference to `MainWindow::openDatabase(QString const&, QString const&, QString const&)'
/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld: /home/xxxxxxxx/rpmbuild/BUILD/keepassxc-2.5.3/src/main.cpp:114: undefined reference to `Crypto::errorString()'
/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld: /home/xxxxxxxx/rpmbuild/BUILD/keepassxc-2.5.3/src/main.cpp:115: undefined reference to `MessageBox::critical(QWidget*, QString const&, QString const&, unsigned long, MessageBox::Button, MessageBox::Action, QCheckBox*)'
/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld: /home/xxxxxxxx/rpmbuild/BUILD/keepassxc-2.5.3/src/main.cpp:123: undefined reference to `Crypto::debugInfo()'
collect2: error: ld returned 1 exit status
make[2]: *** [src/keepassxc] Error 1
make[2]: Leaving directory `/mnt/mydata/Development/rpmbuild/BUILD/keepassxc-2.5.3/build'
make[1]: *** [src/CMakeFiles/keepassxc.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld: CMakeFiles/keepassxc-cli.dir/keepassxc-cli.cpp.o: in function `enterInteractiveMode(QStringList const&)':
/home/xxxxxxxx/rpmbuild/BUILD/keepassxc-2.5.3/src/cli/keepassxc-cli.cpp:122: undefined reference to `Commands::setupCommands(bool)'
/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld: /home/xxxxxxxx/rpmbuild/BUILD/keepassxc-2.5.3/src/cli/keepassxc-cli.cpp:124: undefined reference to `Open::Open()'
/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld: /home/xxxxxxxx/rpmbuild/BUILD/keepassxc-2.5.3/src/cli/keepassxc-cli.cpp:127: undefined reference to `Open::execute(QStringList const&)'
/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld: CMakeFiles/keepassxc-cli.dir/keepassxc-cli.cpp.o: in function `SimpleLineReader::SimpleLineReader()':
/home/xxxxxxxx/rpmbuild/BUILD/keepassxc-2.5.3/src/cli/keepassxc-cli.cpp:61: undefined reference to `TextStream::TextStream(_IO_FILE*, QFlags<QIODevice::OpenModeFlag>)'
/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld: /home/xxxxxxxx/rpmbuild/BUILD/keepassxc-2.5.3/src/cli/keepassxc-cli.cpp:61: undefined reference to `TextStream::TextStream(_IO_FILE*, QFlags<QIODevice::OpenModeFlag>)'
/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld: CMakeFiles/keepassxc-cli.dir/keepassxc-cli.cpp.o: in function `enterInteractiveMode(QStringList const&)':
/home/xxxxxxxx/rpmbuild/BUILD/keepassxc-2.5.3/src/cli/keepassxc-cli.cpp:140: undefined reference to `Utils::STDERR'
/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld: /home/xxxxxxxx/rpmbuild/BUILD/keepassxc-2.5.3/src/cli/keepassxc-cli.cpp:140: undefined reference to `TextStream::TextStream(_IO_FILE*, QFlags<QIODevice::OpenModeFlag>)'
/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld: /home/xxxxxxxx/rpmbuild/BUILD/keepassxc-2.5.3/src/cli/keepassxc-cli.cpp:144: undefined reference to `Database::metadata()'
/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld: /home/xxxxxxxx/rpmbuild/BUILD/keepassxc-2.5.3/src/cli/keepassxc-cli.cpp:144: undefined reference to `Metadata::name() const'
/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld: /home/xxxxxxxx/rpmbuild/BUILD/keepassxc-2.5.3/src/cli/keepassxc-cli.cpp:155: undefined reference to `Utils::splitCommandString(QString const&)'
/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld: /home/xxxxxxxx/rpmbuild/BUILD/keepassxc-2.5.3/src/cli/keepassxc-cli.cpp:160: undefined reference to `Commands::getCommand(QString const&)'
/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld: /home/xxxxxxxx/rpmbuild/BUILD/keepassxc-2.5.3/src/cli/keepassxc-cli.cpp:146: undefined reference to `Database::filePath() const'
/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld: /home/xxxxxxxx/rpmbuild/BUILD/keepassxc-2.5.3/src/cli/keepassxc-cli.cpp:174: undefined reference to `Database::releaseData()'
/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld: CMakeFiles/keepassxc-cli.dir/keepassxc-cli.cpp.o: in function `DatabaseCommand::~DatabaseCommand()':
/home/xxxxxxxx/rpmbuild/BUILD/keepassxc-2.5.3/src/cli/DatabaseCommand.h:27: undefined reference to `vtable for DatabaseCommand'
/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld: /home/xxxxxxxx/rpmbuild/BUILD/keepassxc-2.5.3/src/cli/DatabaseCommand.h:27: undefined reference to `Command::~Command()'
/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld: CMakeFiles/keepassxc-cli.dir/keepassxc-cli.cpp.o: in function `main':
/home/xxxxxxxx/rpmbuild/BUILD/keepassxc-2.5.3/src/cli/keepassxc-cli.cpp:180: undefined reference to `Crypto::init()'
/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld: /home/xxxxxxxx/rpmbuild/BUILD/keepassxc-2.5.3/src/cli/keepassxc-cli.cpp:188: undefined reference to `Bootstrap::bootstrap()'
/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld: /home/xxxxxxxx/rpmbuild/BUILD/keepassxc-2.5.3/src/cli/keepassxc-cli.cpp:189: undefined reference to `Commands::setupCommands(bool)'
/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld: /home/xxxxxxxx/rpmbuild/BUILD/keepassxc-2.5.3/src/cli/keepassxc-cli.cpp:191: undefined reference to `TextStream::TextStream(_IO_FILE*, QFlags<QIODevice::OpenModeFlag>)'
/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld: /home/xxxxxxxx/rpmbuild/BUILD/keepassxc-2.5.3/src/cli/keepassxc-cli.cpp:200: undefined reference to `Commands::getCommands()'
/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld: /home/xxxxxxxx/rpmbuild/BUILD/keepassxc-2.5.3/src/cli/keepassxc-cli.cpp:201: undefined reference to `Command::getDescriptionLine()'
/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld: /home/xxxxxxxx/rpmbuild/BUILD/keepassxc-2.5.3/src/cli/keepassxc-cli.cpp:235: undefined reference to `Commands::getCommand(QString const&)'
/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld: /home/xxxxxxxx/rpmbuild/BUILD/keepassxc-2.5.3/src/cli/keepassxc-cli.cpp:222: undefined reference to `Crypto::debugInfo()'
/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld: /home/xxxxxxxx/rpmbuild/BUILD/keepassxc-2.5.3/src/cli/keepassxc-cli.cpp:181: undefined reference to `Crypto::errorString()'
collect2: error: ld returned 1 exit status
make[2]: *** [src/cli/keepassxc-cli] Error 1
make[2]: Leaving directory `/mnt/mydata/Development/rpmbuild/BUILD/keepassxc-2.5.3/build'
make[1]: *** [src/cli/CMakeFiles/keepassxc-cli.dir/all] Error 2
make[2]: Leaving directory `/mnt/mydata/Development/rpmbuild/BUILD/keepassxc-2.5.3/build'
[100%] Built target keepassx-autotype-xcb
make[1]: Leaving directory `/mnt/mydata/Development/rpmbuild/BUILD/keepassxc-2.5.3/build'
make: *** [all] Error 2
error: Bad exit status from /var/tmp/rpm-tmp.PBKujo (%build)


RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.PBKujo (%build)

Thanks.

**Comment by popxunga** [comment]
> I have linked the actual version of libgcrypt and libgpg-error static.

You mean the 1.5.3 version on EL7 ?

**Comment by tuxmaster5000** [comment]
I use 1.37 for gpgerror and 1.8.5 for gcrypt.

**Comment by popxunga** [comment]
> I use 1.37 for gpgerror and 1.8.5 for gcrypt.

1.35 for gpgerror and 1.8.5 for gcrypt as well here.

Any idea about the error posted above ?

**Comment by tuxmaster5000** [comment]
Her my build log, I hope it will help.
[build.log](https://github.com/keepassxreboot/keepassxc/files/4450312/build.log)
[installed_pkgs.log](https://github.com/keepassxreboot/keepassxc/files/4450313/installed_pkgs.log)

**Comment by popxunga** [comment]
Hi @tuxmaster5000 
Thanks for the logs.
I really could not figure out what's wrong with 2.5.3.
Anyway I just built the new 2.5.4 successfully without changing anything in my build system:-)
Thanks again. 
Closing.
