### ISSUE TITLE
Enhancement to distinguish pages 

### ISSUE THREAD

**Issue by GITMichaelK** [keepassxreboot/keepassxc#4208]
I'm using KeePassXC since a while, it's a pleasure!
I'd like to propose an enhancement: Actually, the webpages are distinguished by Page-Title, which is stored (potentially including *-masking) and this string is used in Auto-Text for identification.
Now I tried to use it for different REDDIT-channnels, f.e [Kreddit](https://www.reddit.com/r/kde/) or [LinuxHardware](https://www.reddit.com/r/linuxhardware/) where the page titles are absolutely different and I cant log-in using KeePassXC. Same problem with Thunderbird and different mail accounts.
So is there any chance to distinguish between such pages or use-cases? May be, to add the URL for identification?

**Comment by droidmonkey** [comment]
I'm confused, there is only one Reddit login, doesn't matter what subreddit you are on. Are you using the browser extension or Auto-Type?

**Comment by phoerious** [comment]
Auto-Type can only read window titles. Use our browser extension for matching by URL.
