### ISSUE TITLE
Customized Passphrase Generator Options

### ISSUE THREAD

**Issue by javaisbetterthanpython** [keepassxreboot/keepassxc#4209]
## Summary
The Passphrase generator should include options to have numbers and special characters. 

## Desired Behavior
Add two checkboxes, one for numbers, and one for special characters.

## Context
I like to generate passphrases using the KeePassXC generator, however many websites still require at least one number and one special character in the password, meaning I always have to add those manually at the end.

**Comment by droidmonkey** [comment]
Interesting idea

**Comment by phoerious** [comment]
I like the idea. Would be great if one could configure the length as well. Some websites still require passwords longer than 8 characters.

**Comment by javaisbetterthanpython** [comment]
> I like the idea. Would be great if one could configure the length as well. Some websites still require passwords longer than 8 characters.

I find the length usually isn't as much of an issue with the passphrase generator. Even with the word count set to 2 it's usually over 8 characters, if anything I sometimes generate passphrases that are too long. Maybe to take both suggestions into account we could also have a minimum and maximum character length as well, or just a length option like the password generator has.

**Comment by msrn** [comment]
This would be a welcome addition to the passphrase generator.
As an example, Keepass plugin [Readable Passphrase Generator](https://bitbucket.org/ligos/readablepassphrasegenerator/wiki/Home). Has pretty extensive options to customize generated passphrases with options ranging from providing your own dictionary to generate from, to customizing [phrase strenghts](https://bitbucket.org/ligos/readablepassphrasegenerator/wiki/Combination-Counting).

While KeePassXC might not need this extensive customizing I think it would be good to provide a way to customize how many upper case and lower case words there are, etc.

![kuva](https://user-images.githubusercontent.com/14147811/73125726-cf210e00-3fb2-11ea-9584-98e657fe2e63.png)

Above example generates following passphares:

> a-birch-bloats-the-BREAKAGE30
> the-freckle-WHOOPS-your-demo04
> his-extra-PAYS-a-monolith62

**Comment by phoerious** [comment]
Holy cow. That is a nightmare of a dialogue.

**Comment by droidmonkey** [comment]
LoL, the readable passphrase generator has an utterly incomprehensible dialog.

**Comment by msrn** [comment]
> 
> 
> Holy cow. That is a nightmare of a dialogue.

> 
> 
> LoL, the readable passphrase generator has an utterly incomprehensible dialog.

I have seen worse. Only downside of that dialogue is that you need to open the wiki to see what each variable does because the names of those are not self-explanatory.
You read that dialogue from top to bottom, first you specify phrase options (min-max lenght, phrase style) and then mutators(capital or lower words) if you want any. At the bottom it shows entropy of your current passphrase options.

Much harder was finding how original Keepass handles different password generation profiles.

**Comment by droidmonkey** [comment]
That is certainly not the only problem.

**Comment by msrn** [comment]
> 
> 
> That is certainly not the only problem.

While this has nothing do with the initial issue and this is going offtopic, but I'd like to know why it seems too confusing and incomprehensible design? 
From what I gather the dialog presents too many options at once and doesn't make a clear separation between them and wording of some options might sound too "technical". 
Btw, here is the original[ The Dialog ](https://www.jensroesner.com/wgetgui/wgetgui.png) :-)

**Comment by vsug** [comment]
so maybe this issue will be added to the working list?
I really need it.

**Comment by arrowmaster** [comment]
Similar to the request from @msrn. I think the https://xkpasswd.net/ method of making passphrases with numbers and symbols embedded would be a great enhancement. It doesn't make grammatically correct phrases but has good options for adding extra entropy to a passphrase in a memorable way.

**Comment by archmalet** [comment]
I started implementing something similar to this feature request.
The passphrase generator has the option to include a number (users can choose how many digits the number has) and a special character in the generated passphrases.

The UI would look something like this:
![Proposed passphrase dialog with numbers and special characters support](https://user-images.githubusercontent.com/6935429/87961585-36c59b00-cab6-11ea-827e-37c4a39162f6.png)

The code is in my [fork](https://github.com/archmalet/keepassxc).
If you are interested in this, I'd be glad to clean it up and submit a pull request.
Please let me know.

**Comment by javaisbetterthanpython** [comment]
@archmalet that looks really great. I would be really interested in seeing that submitted as a pull request

**Comment by catleeball** [comment]
@archmalet Seconding @javaisbetterthanpython , would love to see that in a PR.

Would also be nice to have a "Maximum characters" count box for websites or applications that only support passphrases no longer than N characters.

If that is feature creep for this FR, let me know and I'll make a separate github issue.

**Comment by nicosalvadore** [comment]
Hello all,
this is a feature I would use for sure too ! @archmalet have you been able to clean it up as you said ?

Thank you !

**Comment by archmalet** [comment]
It didn't look to me like that many people are interested in this before, so I haven't done that.

It looks like its worthwhile now.
Gonna be hard for me to find time for the cleanup in the next few weeks.
I'll do my best

**Comment by droidmonkey** [comment]
I am not in favor of it because it violates the point of a passphrase.

**Comment by javaisbetterthanpython** [comment]
@archmalet  I think this would definitely be helpful. Can't wait to see!

> I am not in favor of it because it violates the point of a passphrase. If you want extra security use a password. If you need a memorable password, and need to add characters to meet a password requirement, do it manually.
If you want extra security, use a password? That doesn't make sense to me. And when people add things manually to a passphrase, it always becomes "1" or something similar at the end. Better to have it randomly included.

**Comment by droidmonkey** [comment]
A password, in the context of keepassxc, is a totally random sequence that is impossible to memorize and incredibly difficult to guess. A passphrase is a random selection from a fixed word list that has the _sole purpose_ of being easy to remember while still being difficult to guess (word count > 4). Adding totally random characters to a passphrase completely defeats its own purpose. You should just use a password instead. Thank you.

**Comment by javaisbetterthanpython** [comment]
A passphrase can still be easy to remember and have numbers and symbols.

Take this generator as an example. It's simple in that it appends a numeric digit to the end of the passphrase. The separator takes care of the "special character" requirement.  https://correcthorsebatterystaple.net/


So a generated password goes from this,

> Subject-Aunt-Remind-Shore


to something like this. I don't believe that the latter would be more difficult for a user to remember, yet it increases the complexity and meets the criteria for special characters, uppercase and lowercase, and special characters.

> Subject-Aunt-Remind-Shore-3

**Comment by arrowmaster** [comment]
The most complicated variant I have seen is still not nearly as complicated as a password. https://xkpasswd.net/

In this one you need to know a separator, a punctuation mark, two 2 digit numbers, your passphrase, and the set pattern they are combined into. If I was going to use passphrases in a business setting for accounts I had to share with others in a password manager, this would be the one I would pick to make them as complicated as possible but still match most password policies and be easy to read off over the phone to a team member.

I would see it as valuable to add this as a separate option in addition to the current password and passphrase generator. That would also satisfy @droidmonkey's definition of keeping passphrase simple.

**Comment by archmalet** [comment]
I'm trying to gather requirements discussed in this issue:

1. The passphrase is easy to remember
2. The passphrase has a reasonable amount of entropy
2. The passphrase passes common password policies like at least one special character and number.
3. The UI is easy to configure and understand.

The entropy part is covered by choosing enough words.
The special character part is covered by the word separator option. We could set the default to something like "_".

A possible way forward is just including a number. We could add a 1 or 2 digit number in a fixed position (beginning or end) to keep the passphrase as easy to memorise as possible.
Adding just the number option (and maybe excluding look-alike characters and digit count) wouldn't make the UI much more complicated..

**Comment by msrn** [comment]
Points listed by @archmalet are mostly good and there is actually nothing wrong with current passphrase generator except for lack of generating numbers. My passphrases usually follow the format @javaisbetterthanpython posted as in `Subject-Aunt-Remind-Shore-3`.

But I would argue that the current phrases are not that memorable, just because they are phrases with random words, without any structure. Creating an phrase with meaningful structure would make the passphrase more memorable.

These were created with 'readable passphrase option at [Make Me A Password](https://makemeapassword.ligos.net/)
This format follows some rule eg. `<ńoun> <verb> <adjective>`
Most of these are pretty memorable and usually the funny ones stick with you most
```
the hydrant will promise a byway
will Ernestine scatter a conduit
the morose one overrates an urine
will her 1 chapter get her shelf
will a doctor dope the subject
Junior has mimed that episcopal folio
```

These are created with KeePassXC.
While you can easily learn to remember these phrases, they don't 'jump' at you like the ones above.
```
prevent tabby vista sighing
mower ramrod drove aflutter
favorite sector power resisting
tadpole brunette public sixtieth
```

**Comment by archmalet** [comment]
> But I would argue that the current phrases are not that memorable, just because they are phrases with random words, without any structure. Creating an phrase with meaningful structure would make the passphrase more memorable.

@msn I agree that structured passphrases do make it easier to remember the passphrase.
It would also decrease entropy (thus potentially require longer phrases) and require a complete restructuring of the passphrase generator.
Currently it just takes random words out of a single wordlist.
For your proposal we would need separate wordlists for different types (I guess those should be available?) and a way to describe the pattern.
Allowing users to customise the pattern implies a complicated UI.
This also makes it much harder to simply increase the word count, because the pattern needs to be updated in a sensible way.

I'm not saying I like the idea, just wanna point out that this is much more effort.

**Comment by msrn** [comment]
> > But I would argue that the current phrases are not that memorable, just because they are phrases with random words, without any structure. Creating an phrase with meaningful structure would make the passphrase more memorable.
> 
> @msn I agree that structured passphrases do make it easier to remember the passphrase.
> It would also decrease entropy (thus potentially require longer phrases) and require a complete restructuring of the passphrase generator.
> Currently it just takes random words out of a single wordlist.
> For your proposal we would need separate wordlists for different types (I guess those should be available?) and a way to describe the pattern.
> Allowing users to customise the pattern implies a complicated UI.
> This also makes it much harder to simply increase the word count, because the pattern needs to be updated in a sensible way.
> 
> I'm not saying I like the idea, just wanna point out that this is much more effort.

I know, and I intended the comment just as an pointer not a feature request. Sorry if I gave the wrong impression.

But if there ever is going to be work around this then for UI, there could be radio button for two options; readable passphrase or random passphrase, but that could get confusing if the user has no idea what those two mean. 

And yes there are dictionaries available with XML key-value regarding to what type of a word it is. [Link](https://makemeapassword.ligos.net/faq#dictionaries).

Also for general usage I think more advanced users could just use external sites/generator for generating those types of passphrases. Even I only have few readable passphrases in use. So I don't think implementing something like this is worth it.

**Comment by archmalet** [comment]
@msn I do think implementing something like this in addition to including numbers and special characters might be worthwhile.
This might make the passphrases more memorable as a whole, thus fulfilling all the requirements we gathered.
That is if there is a way to keep the UI comprehensible

**Comment by jgonera** [comment]
Related idea: support for languages other than English (possibly mixing words from different languages). It's a wild guess but I feel this would make for more secure passwords (assuming that when someone tries to hack a password they are likely to just use an English dictionary).

**Comment by jgonera** [comment]
@AzureCerulean this is a bit of a deal-breaker for me: https://github.com/lesspass/lesspass/issues/471

**Comment by droidmonkey** [comment]
This is not going to be implemented due to discussions in other (more recent) requests. Passphrases can have symbols and numbers added to them manually, doing so automatically defeats the purpose of the passphrase.
