### ISSUE TITLE
Aesthetics 

### ISSUE THREAD

**Issue by FMuro** [keepassxreboot/keepassxc#421]
So far, I've run the Fedora unofficial package. I've just tried the AppImage. I'd like to use it, because it's an official way to install KeePassXC, but it doesn't integrate in Gnome. I've tried hard to run it with the nice Adwaita Qt5 theme by all means known to me, but I've consistently failed. I don't really know how AppImages work. Is it maybe the case that they can't pick Qt themes which are not bundled with them? If so, would it be possible to bundle adwaita-qt5 into KeePassXC? Another issue, possibly related, is the font size. It's smaller than elsewhere in my system. Thanks for reading and for developing this wonderful piece of software!

**Comment by phoerious** [comment]
The AppImage cannot pick up your system theme when your Qt binaries are in a different location than on the system the AppImage was built on. That's simply a limitation of how AppImages and Qt themes work.
We were thinking about bundling a theme, but that wouldn't make things better. It might look good on your platform, but surely not on mine or many other platforms.

If you want perfect system integrations, I recommend you use the Fedora Copr packages.
