### ISSUE TITLE
Windows Installer should check for previous Versions

### ISSUE THREAD

**Issue by tilllt** [keepassxreboot/keepassxc#4213]
I just installed KeePassXC 2.5.3 over my 2.3.4 install on Windows 10 and to my surprise, after the installation, both versions where installed, but named identically. While i understand there are advantages of having the option to install multiple versions of a software at the same time, i would suggest to add the version number to the created Shortcut, so you can see which Version you are actually starting...

Alternatively, it should ask to deinstall the old version.

**Comment by phoerious** [comment]
I suppose you had 2.3 installed using the exe installer, which has been discontinued. Thr msi installer takes care of previously installed versions.
