### ISSUE TITLE
keepassxc-browser: Unable to connect to a second database

### ISSUE THREAD

**Issue by gxfgbo** [keepassxreboot/keepassxc#4215]
I'm trying to connect keepassxc-browser in Firefox to two databases. I can connect to and use a single database fine. I cannot fully connect and use a second database.

## Expected Behavior
A second DB connection should be connected and maintained.

## Current Behavior
When I go into keepassxc-browser settings, I can connect to a second database if its tab is selected in keepassxc. Both databases are show on the DB connections page in keepassxc-browser, however refreshing that DB connections page results in the first DB connection being removed.

## Possible Solution
None I could find

## Steps to Reproduce
1. Select the first DB tab in keepassxc
2. Connect to the first DB in keepassxc-browser
3. Select the second DB tab in keepassxc
4. Connect to the second DB in keepassxc-browser
5: Refresh the DB connections keepassxc-browser setting page

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )

## Debug Info
KeePassXC - 2.5.3
keepassxc-browser: 1.5.4

Libraries:
- N/A

Operating system: Windows 10
CPU architecture: Intel x64

Enabled extensions:
- keepassxc-browser

**Comment by droidmonkey** [comment]
Are you using unique names for your connections?

**Comment by varjolintu** [comment]
Is your second database a clone from the first one? You can verify this by viewing the Root group properties and check the Uuid.

**Comment by gxfgbo** [comment]
I am using unique names for the connections.

It is possible that the second database was originally created from a copy of the first database. The purpose of the two databases was to split all logins into two DBs (Personal vs Work).

I'll look for the bug with cloned databases.

I should add, my ultimate objective is to allow searching across both databases. In keepassxv, I have enabled "Search across all open databases, but keepassxc-browser still returns entries from only the DB whose tab is selected in keepassxc. If I'm off base how I'm trying to do this, all feedback is appreciated!

**Comment by varjolintu** [comment]
Creating a new database and merging/importing credentials from your old database should do the trick.

**Comment by gxfgbo** [comment]
> Creating a new database and merging/importing credentials from your old database should do the trick.

Thanks @varjolintu. That solved it!

I created a new "second DB", merged all entries from the old instance and created a new connection key. Both DB keys remain when I refresh the keepassxc-browser options and I can now search properly across multiple DBs.

Many thanks for the help from all those that replied. Please let me know if I should do anything to add to the existing cloned-DB bug report.

**Comment by droidmonkey** [comment]
We should probably add a button to the database browser settings page to "Refresh Database ID" or similar which would create a new UUID for the database.

**Comment by varjolintu** [comment]
The same has been suggested in the original issue thread: https://github.com/keepassxreboot/keepassxc-browser/issues/640
