### ISSUE TITLE
Double-quotes wrongly removed from password in cmd://

### ISSUE THREAD

**Issue by andusvan** [keepassxreboot/keepassxc#4217]
When I try to open putty via URL command using the placeholder {PASSWORD} and the password contains a double-quote (", character 0x22), the shell does not auto-login.
I debugged it (using strace and looking to /proc/<PID>/cmdline). It seems, that the program removes the double quote before calling execve().

## Expected Behavior
Opening putty and auto log in.

## Current Behavior
Open putty in dialog mode. No login.

## Possible Solution
Correct removal of quotes.

## Steps to Reproduce
1. Add entry
2. Set username and a password with a double-quote (")
3. Set URL to "cmd://putty -ssh -l {USERNAME} -pw {PASSWORD} 127.0.0.1"
4. Try to open

## Context
Always

## Debug Info
KeePassXC - 2.5.1
Revision: 0fd8836

Libraries:
 libgcrypt 1.8.5
 Qt 5.12.5

Operating system: Fedora 30 (Workstation Edition)
CPU architecture: x86_64
Kernel: linux 5.4.7-100.fc30.x86_64

Enabled extensions:
- Auto-Type
- Browser-Integration
- SSH-Agent
- KeeShare
- YubiKey
- Secret-Service-Integration

**Comment by droidmonkey** [comment]
Update to 2.5.w
