### ISSUE TITLE
AppImage SSL errors on load

### ISSUE THREAD

**Issue by l0f4r0** [keepassxreboot/keepassxc#4219]
Hi,

Whether I install KeePassXC 2.5.3 via snap or AppImage on my Debian 10, I get errors displayed on console when launching the software (not exactly the same errors though).

## Expected Behavior
No errors on console.

## Current Behavior
If KeePassXC is installed via snap, I get the following errors when launching the software:
```
Qt: Session management error: Authentication Rejected, reason : None of the authentication protocols specified are supported and host-based authentication failed
QObject::startTimer: Timers cannot have negative intervals
```

If installation was made via AppImage, the errors are the following instead:
```
QObject::startTimer: Timers cannot have negative intervals
qt.network.ssl: QSslSocket: cannot resolve CRYPTO_num_locks
qt.network.ssl: QSslSocket: cannot resolve CRYPTO_set_id_callback
qt.network.ssl: QSslSocket: cannot resolve CRYPTO_set_locking_callback
qt.network.ssl: QSslSocket: cannot resolve ERR_free_strings
qt.network.ssl: QSslSocket: cannot resolve EVP_CIPHER_CTX_cleanup
qt.network.ssl: QSslSocket: cannot resolve EVP_CIPHER_CTX_init
qt.network.ssl: QSslSocket: cannot resolve sk_new_null
qt.network.ssl: QSslSocket: cannot resolve sk_push
qt.network.ssl: QSslSocket: cannot resolve sk_free
qt.network.ssl: QSslSocket: cannot resolve sk_num
qt.network.ssl: QSslSocket: cannot resolve sk_pop_free
qt.network.ssl: QSslSocket: cannot resolve sk_value
qt.network.ssl: QSslSocket: cannot resolve SSL_library_init
qt.network.ssl: QSslSocket: cannot resolve SSL_load_error_strings
qt.network.ssl: QSslSocket: cannot resolve SSL_get_ex_new_index
qt.network.ssl: QSslSocket: cannot resolve SSLv3_client_method
qt.network.ssl: QSslSocket: cannot resolve SSLv23_client_method
qt.network.ssl: QSslSocket: cannot resolve SSLv3_server_method
qt.network.ssl: QSslSocket: cannot resolve SSLv23_server_method
qt.network.ssl: QSslSocket: cannot resolve X509_STORE_CTX_get_chain
qt.network.ssl: QSslSocket: cannot resolve OPENSSL_add_all_algorithms_noconf
qt.network.ssl: QSslSocket: cannot resolve OPENSSL_add_all_algorithms_conf
qt.network.ssl: QSslSocket: cannot resolve SSLeay
qt.network.ssl: Incompatible version of OpenSSL
qt.network.ssl: QSslSocket::connectToHostEncrypted: TLS initialization failed
```

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )

## Steps to Reproduce
1. Download & install KeePassXC 2.5.3 binary from https://keepassxc.org/download/#linux (snap or AppImage)
2. Launch KeePassXC

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.5.3
Révision : f8c962b
Operating system: Linux Debian 10
CPU architecture: amd64
Kernel: 5.4.0-0.bpo.2-amd64

**Comment by jclement** [comment]
Also seeing this open Debian 10 with KeepassXC 2.5.3 AppImage.  Is it possible to include the appropriate version of OpenSSL in the package?

**Comment by phoerious** [comment]
The problem with bundling OpenSSL is that every Linux distro does their own thing where they place their root certificates.

**Comment by jclement** [comment]
Oh.  Of course.  That makes sense :(  Thank you.

**Comment by droidmonkey** [comment]
Idea from @dhanak, use curl to perform network requests when running as appimage to circumvent the ssl certificate issues.

**Comment by Smojo** [comment]
Same here (I don't have much OpenSSL request of KeepassXC but, especially about the favicon download via DuckDuckGo it is a bit annoying ... currently download some manually but as this is a bit time consuming I mostly skip it).

System Facts:
KeepassXC: 2.6.6 (Revision: 9c108b9; Distribution: AppImage)
OS: PureOS 10 – Byzantium (based on Debian 11 - Bullseye; Kernel 5.10 LTS ; Windowing System: Wayland / Gnome 3.38.5 )

Any news regarding this issue?

**Comment by luzat** [comment]
Favicon download works here, probably since 2.7 (it didn't in the past with AppImage).

* KeePassXC: 2.7.0 AppImage
* OS: Debian bookworm/sid

Only error at startup is related to PCSC/YubiKey:

    YubiKey: Failed to establish PCSC context.
    YubiKey: PCSC interface is disabled or not initialized.

Not sure if the YubiKey would work, but I have not found much use in the integration so far.

**Comment by phoerious** [comment]
The 2.7 AppImage is built on Ubuntu Focal instead of Xenial. That's probably why it works now. It may fail again in the future if the Focal base image falls far enough behind users' host systems.

**Comment by l0f4r0** [comment]
@luzat : indeed, favicon download works with AppImage or snap 2.7.0.

On snap, I still have the error messages I indicated in my initial post:
```
Qt: Session management error: Authentication Rejected, reason : None of the authentication protocols specified are supported and host-based authentication failed
YubiKey: Failed to establish PCSC context.
YubiKey: PCSC interface is disabled or not initialized.
QObject::startTimer: Timers cannot have negative intervals
```

But on AppImage, I don't have the SSL errors anymore (only the same errors above than snap).

**Comment by droidmonkey** [comment]
Those are not errors. Closing due to working again.

**Comment by jee-r** [comment]
Seems this bug is back :/  

Ouput when i try download a favicon :
```
qt.network.ssl: QSslSocket: cannot resolve EVP_PKEY_base_id
qt.network.ssl: QSslSocket: cannot resolve SSL_get_peer_certificate
qt.network.ssl: QSslSocket: cannot call unresolved function SSL_get_peer_certificate
qt.network.ssl: QSslSocket: cannot call unresolved function SSL_get_peer_certificate
qt.network.ssl: QSslSocket: cannot call unresolved function SSL_get_peer_certificate
qt.network.ssl: QSslSocket: cannot call unresolved function SSL_get_peer_certificate
qt.network.ssl: QSslSocket: cannot call unresolved function SSL_get_peer_certificate
```

Debug Info:
```
KeePassXC - Version 2.7.6
Revision: dd21def
Distribution: AppImage

Qt 5.15.2
Debugging mode is disabled.

Operating system: Fedora Linux 38 (Workstation Edition)
CPU architecture: x86_64
Kernel: linux 6.4.15-200.fc38.x86_64

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.19.1
```

**Comment by droidmonkey** [comment]
We recommend just using flatpak, appimage has a whole host of problems.

**Comment by jee-r** [comment]
ok thanks @droidmonkey sorry for the  inconvenience i did not know that. I switched to fedora pkg manager which seems relatively maintained.

**Comment by dhanak** [comment]
> We recommend just using flatpak, appimage has a whole host of problems.

It is slightly unfortunate, then, that the most prominent download option on https://keepassxc.org/download/#linux is the AppImage version. It definitely looks as though that is the preferred, most supported option.

**Comment by droidmonkey** [comment]
For _download_ sure, otherwise your first option is your package manager in the OS.
