### ISSUE TITLE
Notes field eats keyboard focus

### ISSUE THREAD

**Issue by hifi** [keepassxreboot/keepassxc#4222]
When editing an entry. Going into the notes field with keyboard will eat focus forever as it will produce literal tab character with the tab key. 

On Linux shift-tab works to go back but it doesn't help when you want to accept/cancel the entry edit with keyboard only. On Windows I have not found a way to get away from the field without mouse.

[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Tab key probably shouldn't be eaten by the editor, is it really necessary to produce literal tab characters in it?

## Current Behavior
[NOTE]: # ( Tell us what actually happens )
Focus is lost into notes field without mouse.

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )
Possibly correct solution would be to allow tab to work as normal rather than producing literal tab characters. Inelegant solution could be to create a custom binding like ctrl+tab to jump forward from this field only.

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1. Edit entry
2. Focus notes field
3. Press tab, press shift-tab

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )
For screen reader users this is a showstopper bug.

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.5.3
Repro on Windows and Linux

**Comment by droidmonkey** [comment]
I fixed this in 2.6.2, #5424
