### ISSUE TITLE
Win10 pinned task bar icon disappearing during upgrade

### ISSUE THREAD

**Issue by evitalis** [keepassxreboot/keepassxc#4226]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Pinned KeepassXC shortcut on the taskbar remains when the application is upgraded.

## Current Behavior
[NOTE]: # ( Tell us what actually happens )
When doing the installation the icon is removed from the taskbar. It can easily be readded but is a pain to not stay.

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1. Install KeepassXC for Windows
2. Pin the shortcut to the taskbar
3. Install a new version of KeepassXC

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )
I keep pinned shortcuts for various items I use consistently with KeepassXC being one of them. While this is not breaking for me it is bothersome from a user perspective to find this missing after an upgrade.

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.5
Revision: any

Libraries:

Operating system: Win 10
CPU architecture: x64

Enabled extensions:
-

**Comment by Jon-guy30** [comment]
I'm glad someone reported this. I was about to report it myself. Every time I upgrade it deletes the taskbar icon. I've just dealt with it until now.

**Comment by xpusostomos** [comment]
I just installed Keepassxc 2.6.6 and this is STILL an issue. I don't know what you guys did, but it didn't work.
