### ISSUE TITLE
Auto-type doesn't work with Firefox in case Lockwise is used

### ISSUE THREAD

**Issue by pallalino** [keepassxreboot/keepassxc#4229]
Hi,

I'm a new user of KeePassXC so please excuse me in case it's described somewhere.

I cerated a new entry with user/password and enabled auto-type in KeePassXC for the page web.de. Before that I already enabled the auto-type of firefox, called Lockwise (72.0.2 (64-Bit)). 

## Expected Behavior
I expect that when I use auto-type in KeePassXC user and password are entered and I'm logged in; before I navigate the the web page and place the cursor into the user field (not sure if this shoudl also work automatically).

## Current Behavior
I see that user name is typed in correct, but pssword is wrong; I think the password is doubled due to Lockwise & KeePass (the visible length indicates this).

## Possible Solution
I removed the entry in Lockwise; then it works with keePass. Nevertheless, I think it should also work in case Lockwise is active.

## Debug Info
KeePassXC - Version 2.5.3
Revision: f8c962b

Qt 5.14.0
Diagnosemodus ist deaktiviert.

Betriebssystem: macOS Mojave (10.14)
CPU-Architektur: x86_64
Kernel: darwin 18.7.0

Aktivierte Erweiterungen:
- Auto-Type
- Browser-Integration
- SSH-Agent
- KeeShare (bestätigtes und unbestätigtes Teilen)
- YubiKey
- TouchID

Kryptographische Bibliotheken:
 libgcrypt 1.8.5

**Comment by droidmonkey** [comment]
There is no way we can operate in addition to another manager. You cannot use both for the same entries.
