### ISSUE TITLE
Hangs when not run as superuser

### ISSUE THREAD

**Issue by boconnell** [keepassxreboot/keepassxc#424]
## Expected Behavior
I can run keepassxc as a normal user and it shouldn't hang. At the very least, it should provide an error / timeout on whatever is causing it to hang.

## Current Behavior
I can only run it as a superuser.

## Possible Solution
Not sure. I installed keepassxc via unofficial debian stable package (and am running debian stable) using sudo but am otherwise running as a normal user. I can run keepassxc -v/-h without sudo. I can run keepassxc with sudo and everything works fine. The password file is owned by the normal user.

## Steps to Reproduce (for bugs)
1. Probably dependent on my system.

## Context
I just want to run the app.

## Your Environment

* KeePassXC version/commit used: 2.1.3
* Qt version (e.g. Qt 5.3): not sure
* Compiler (e.g. Clang++3.6.0): not sure
* Operating System and version: Debian stable

Happy to provide debug logs if I can do this without building from source.

**Comment by TheZ3ro** [comment]
Can you post the permission for the `~/.config/keepassxc/keepassxc.ini` file in your home folder?

**Comment by boconnell** [comment]
-rw-r--r-- 1 <username> <username>

**Comment by Keisial** [comment]
What about ~/.config/keepassxc/ folder?
