### ISSUE TITLE
Copy and paste username / password keyboard shortcut in autotype popup

### ISSUE THREAD

**Issue by gouletjg** [keepassxreboot/keepassxc#4245]
## Summary
A copy and paste keyboard shortcut in the autotype pop-up would be nice to have. At the moment, you can right click on an entry to copy the username or the password individually.

## Possible Solution
Why not add the same shortcut keys that the database has (ctrl+B for username and ctrl+ C for password)?

## Context
Websites do not all share the same sequence of login fields. The top two (in my experience) seem to be:

1. Username above, password below
2. Username -> click submit -> password -> click login

As such, I have the default autotype for everything set to type the password, then press enter.  If I do not remember my username, I pull up autotype on the username field. It would be nice to have a keyboard shortcut to press for username entry.

**Comment by droidmonkey** [comment]
This doesn't make sense, if you are doing Auto-Type why would you want to copy paste

**Comment by gouletjg** [comment]
Really it's just a convenience thing. I'm on the website, and I press the autotype shortcut and it pulls up the window. I use that to check the username and it would be convenient to have a keyboard shortcut from that which would copy the username into the clipboard.
