### ISSUE TITLE
Process umask setting is ignored when safe saves are disabled

### ISSUE THREAD

**Issue by sfuhrm** [keepassxreboot/keepassxc#4246]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

Protection bits of saved databases should comply to the umask of the process.

## Current Behavior
[NOTE]: # ( Tell us what actually happens )

Protection bits of saved databases are always 0600 (user read, user write).

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )

None known.

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1. umask 0007 # DB should have 0660
2. start keepassxc
3. save database
4. view protection bits of database

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )

Sharing the database on a shared directory is being quite difficult because the access rights are cut back to user-only.

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.3.4

Operating system: Debian Linux
CPU architecture: amd64
Kernel:  4.19.0-6-amd64

**Comment by droidmonkey** [comment]
Why would the process umask have anything to do with files modified by the process? We actually have an open issue to save databases as 0600. Please check the umask on the shared folder you are saving to, that controls file access.

**Comment by droidmonkey** [comment]
I cannot replicate this issue on Ubuntu 19.10 saving to a local folder. This leads me to believe you have not setup your umask properly on your shared folder _or_ you have custom  ACL's configured.

![image](https://user-images.githubusercontent.com/2809491/73145738-3b684400-407d-11ea-9b1f-bdbf20e4349e.png)

In the above image, test.kdbx was created under `umask 0007` producing proper 0660. The other database, test2.kdbx, was created under `umask 0022` producing proper 0644. I also modified test.kdbx under `umask 0022` and it retained the original 0660.

**Comment by sfuhrm** [comment]
@droidmonkey thanks for your review!

I have no ACL configured:

![image](https://user-images.githubusercontent.com/5055427/73172551-90e73400-4103-11ea-8aa8-1dc8b7a2f885.png)

And the directory is allright:

![image](https://user-images.githubusercontent.com/5055427/73172789-19fe6b00-4104-11ea-85d3-d30d902cf1de.png)

Unfortunately I don't know how to configure the umask of a directory, maybe you can help me here?

On my system it works like this:

### Setup

![image](https://user-images.githubusercontent.com/5055427/73172252-e5d67a80-4102-11ea-9ebb-5855e9fbbc83.png)

### Result 

After saving a new database, user bits set, but everyone should do everything:

![image](https://user-images.githubusercontent.com/5055427/73172317-03a3df80-4103-11ea-934e-99340e9d67b6.png)

But the keepassxc process has the right umask according to its proc fs entry:

![image](https://user-images.githubusercontent.com/5055427/73172450-58dff100-4103-11ea-9ea4-9a8316fe2952.png)

**Comment by sfuhrm** [comment]
Is this the right version?

    fury@cetus:~$ dpkg -l|grep keepassxc
    ii  keepassxc                               2.3.4+dfsg.1-1                       amd64        Cross Platform Password Manager

**Comment by droidmonkey** [comment]
You will want to upgrade to 2.5.3. You can use the snap package or AppImage distribution.

**Comment by sfuhrm** [comment]
Well, 2.5.3 with AppImage:

    fury@cetus:~$ umask 0000; bin/KeePassXC-2.5.3-x86_64.AppImage 

same result:

    -rw-------  1 fury       fury         1605 Jan 27 18:43 Passwörter.kdbx

I'm confused.

**Comment by droidmonkey** [comment]
It's gotta be something with your shared folder.

**Comment by sfuhrm** [comment]
@droidmonkey I did the stuff in `/tmp` (root fs). The combination umask/touch showed that it works with this directory:

    $ (umask 0000; touch 0000)

Results in

    -rw-rw-rw-  1 fury       fury            0 Jan 27 21:45 0000

Keepassxc somehow behaved differently:

    $ (umask 0000; keepassxc)

Results in

    -rw-------  1 fury       fury         1365 Jan 27 21:46 123123.kdbx

Both output files reside in the same directory `/tmp`.
No network folders, no acl, no fancy stuff involved. I thought /tmp (on the ext4 root volume) would be a nice place to compare your and my results.

**Comment by droidmonkey** [comment]
We don't have any code that changes the permissions of files. If this is a bug its with Qt and not us. We just tell Qt where to save the file and it does all the work.

**Comment by sfuhrm** [comment]
I've found at least [this](https://bugreports.qt.io/browse/QTCREATORBUG-6513) Qt bug/feature.
Could this be the reason for the behaviour?

**Comment by droidmonkey** [comment]
Huh, we do the same. So that means you are not using safe file saves. Enable safe file saves in the settings and this problem will go away.

**Comment by sfuhrm** [comment]
Yep! This solved it! 
Thanks for your patience on this. You helped me a lot!

**Comment by droidmonkey** [comment]
As of 2.6.0 we will be creating all new key files and databases with 0600 permissions regardless of the process umask. This follows with #2575.
