### ISSUE TITLE
Open URL in private window mode

### ISSUE THREAD

**Issue by z8O-Hec** [keepassxreboot/keepassxc#4248]
Hi, thank's for your keepassxc.

### Summary
Add for each entry, a new option to select the mode of browsing (private or standard).

### Context
Users behaviours depend on the web site. Sometime, they browse a site with the standard configuration of the browser, sometime with the private navigation mode.

i.e. with my bank web site, I use the private navigation mode systematically to access to my account.

### Desired Behaviour
Add a single checkbox flag on the entry edition window to set on the private browsing option.

On the CTRL-U key press, add the option of the browser in the command line call.

_Maybe, it will be necessary to select in the preference of Keepassxc, the default browser used._

### Example
Firefox browser add the option --private-window

     firefox --private-window https://keepassxc.org/

Vivaldi, Chromium

     chromium --incognito https://keepassxc.org/
     vivaldi --incognito https://keepassxc.org/ 

Unfortunately, this option is not the same or available on all browser.

Nota :
It's different of this issue #3185 because the goal of my issue is to select only the browsing mode.

**Comment by droidmonkey** [comment]
Just add `cmd://` in front of the example you provided in your url field.

**Comment by droidmonkey** [comment]
Will be possible with #4495
