### ISSUE TITLE
keepassxc application hangs on Ubuntu 18.04

### ISSUE THREAD

**Issue by reinierpost** [keepassxreboot/keepassxc#4251]
The `keepassxc` application installed from the current Ubuntu 18.04 package (`2.3.1+dfsg.1-1`) hangs when put into the background:
```
$ keepassxc me.kdbx &
[1] 26236
$ 
$ 
$ 

[1]+  Stopped                 keepassxc me.kdbx
$ 
```
Note how I pressed return a few times. During that time, the application was responsive and I successfully provided my password to open the database. A few seconds later, the `Stopped` message appeared. After that, the application is unresponsive and the only `kill` signal that has any effect on it is `-9` to put it out of its misery. The current `keepassx` (`2.0.3-1 `) doesn't have this problem.

I haven't tested this with the `snap` version or the PPA version yet, so this may need to be fixed downstream; considering Ubuntu's popularity, I think it's worth mentioning here in any case.

This is on an HP ZBook laptop running current Ubuntu 18.04, Linux 4.15.0-74-generic #84-Ubuntu SMP Thu Dec 19 08:06:28 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux.

No extensions are installed, I'm using the packaged `keepassxc` as is.

**Comment by droidmonkey** [comment]
That version of KeePassXC is about 2 years  old. Upgrade and try to reproduce.

**Comment by reinierpost** [comment]
I've also tested the current Ubuntu 18.04 `snap` version. It throws two errors ('Qt: Session management error: None of the authentication protocols specified are supported' and 'Failed to load module “canberra-gtk-module”' and then refuses to open my .kdbx files, so I don't even get to the stage where I can test it.

The current PPA version (2.5.3) does not have the problem. So I'll assume this is a matter of the Debian/Ubuntu package maintainers upgrading their versions.

**Comment by droidmonkey** [comment]
The PPA is maintained by the other lead developer, Phoerious. The snap is auto built from the master branch from launchpad.
