### ISSUE TITLE
Browser Integration comments and discussion

### ISSUE THREAD

**Issue by selinkan** [keepassxreboot/keepassxc#4252]
[TIP]:  # ( Provide a general summary of the feature in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Summary
[NOTE]: # ( Provide a brief overview of what the new feature is all about )

## Desired Behavior
[NOTE]: # ( Tell us how the new feature should work, be specific )
crhome is constantly causing problems with connections
search button does not exist in database
explorer plug-in does not exist

## Possible Solution
[NOTE]: # ( Not required, but suggest ideas on how to implement the addition or change )

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )

**Comment by selinkan** [comment]
To save new passwords, the default set:, the name is very unnecessary and causes problems.

**Comment by selinkan** [comment]
The chrome plug-in is more convenient to contact the database directly and ask for a database password when using the password, instead of appearing passive when there is no connection. Like other password managers...

**Comment by selinkan** [comment]
![test](https://user-images.githubusercontent.com/60379230/73241181-f5f56500-41a9-11ea-8b82-49acb83bb036.png)

**Comment by selinkan** [comment]
This area is unnecessary. It's more appropriate to automatically save my title on the databasa. If there are more than one title, save it to that title if I select the default title.

**Comment by selinkan** [comment]
Many, on the site, empty value can not be entered, error, icona click and select the data, enters the site. This error needs to be fixed.
![2020-01-28_100720](https://user-images.githubusercontent.com/60379230/73242352-62be2e80-41ad-11ea-9db7-612321c959f2.png)

**Comment by varjolintu** [comment]
1. What is "explorer plugin"?

2. We are not going to ask your master password in the extension, ever. And we are not going to connect the database directly. The whole meaning of the extension is to communicate with KeePassXC.

3. The default group setting has nothing to do with the entry title. There's already a feature request for setting the title to the page title when saving new credentials.

4. I don't understand the last error you have described.

**Comment by selinkan** [comment]
Shortcomings in the program.

1-Chrome also has a constant connection error. The chrome add-in cannot enter automatically when the database is opened.
![01](https://user-images.githubusercontent.com/60379230/73330366-4089e680-4269-11ea-8f7a-0e61c75ad0bd.png)
Gives an error even though the database is open
![02](https://user-images.githubusercontent.com/60379230/73330374-4384d700-4269-11ea-9960-5957b02a574c.png)
2-I can't search the database between passwords.
3-Internet Explorer support is not available.Internet Explorer also cannot use the program.
4- Some sites do not see the website when the password is filled in "space value cannot be entered" error occurs. 
![03](https://user-images.githubusercontent.com/60379230/73330521-a8403180-4269-11ea-9263-5c434d77d6a5.png)
5-2 Hotmail with a progressive username and password entered cannot save or recognize e-mail addresses for sites such as gmail yandex.
![2020-01-29_083626](https://user-images.githubusercontent.com/60379230/73330614-f2c1ae00-4269-11ea-839b-9d8e113295d8.png)
![2020-01-29_083702](https://user-images.githubusercontent.com/60379230/73330623-f5240800-4269-11ea-92a3-b1c8367ccb41.png)

6-When saving a password, only user input should be allowed, and only the user must register without a password.

If the issues I have specified are to be taken into account, I will indicate what is missing as a user in the coming days. I don't want to deal with it for nothing if it's not going to be taken into account.

There may be sentence deficiencies because it is Translate.

Thank you for your interest.

**Comment by varjolintu** [comment]
1. The extension must be connected to KeePassXC before it can detect database open. You can enable Auto-Reconnect from the settings.

2. I don't understand what you mean.

3. Internet Explorer is dead. Also, Native Messaging API required for the communication between the extension and KeePassXC is not available for IE. The new Microsoft Edge is supported.

4. I doubt this has anything to do with the extension. Does the same error show if you copy/paste the password?

5. Go to extension settings, Site Preferences tab. Add the site to the list and enable _Username-only detection_.

6. Saving a new entry with only the username is currently not possible.

**Comment by selinkan** [comment]
1-I have already made the settings you said. Chrome often has a connection error. The chrome plugin cannot automatically enter when the database is opened.
2-When I want to search for any user and password in the program interface, there is no search button. For example, I have 100 passwords registered in the program, I need to search them one by one.
3-ok
4-If I copy and paste the password, it logs in. When logging in with KeePassXC, some sites do not detect the data entered. it is perceived as a password that has not been entered.
5- "Go to extension settings, Site Preferences tab. Add the site to the list and enable Username-only detection."
Although it is set, I cannot save the password and open it automatically. For example, I cannot save my Google passwords. I cannot see Google even if I save manually, I cannot open my Google email.
Can you send a video about saving google yandex hotmail entry?
6-ok
7-Automatic registration menu does not appear on some sites. does not detect autosave. Can not the registration feature be added to the icon displayed in the user name fields?
Thank you for your attention.
Yours truly

**Comment by selinkan** [comment]
Can you help me with what I have specified.
Thanks

**Comment by varjolintu** [comment]
1. What is your operating system? What version of KeePassXC are you using? You deleted the issue template. Please don't do that.

2. The credentials are matched with the site URL. There's no feature to search for all password from you database.

4. Maybe the site is doing a check that a password is filled, not copy/pasted.

5. Previously you said there's a problem filling the password, now it's saving it. Is it the saving that causes the problem? I'll check on that.

7. You can save credentials manually using the context menu. Right-click on the input field and select _KeePassXC-Browser -> Save credentials_.
