### ISSUE TITLE
Warnings about SSLv3 methods

### ISSUE THREAD

**Issue by sfuhrm** [keepassxreboot/keepassxc#4254]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

No warnings when starting the AppImage app.

## Current Behavior
[NOTE]: # ( Tell us what actually happens )

There are warnings in the Linux consule when running the app:

    QObject::startTimer: Timers cannot have negative intervals
    qt.network.ssl: QSslSocket: cannot resolve SSLv3_client_method
    qt.network.ssl: QSslSocket: cannot resolve SSLv3_server_method

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1. Start app
2. Load/unlock db (AFAIK kdbx format 3.1)
3. Save db (kdbx format 4.0)

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )

No real impact. Application seems to work.

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.5.3
Revision: f8c962b
Distribution: AppImage

Libraries:
- none

Operating system: Linux
CPU architecture: amd64
Kernel: 4.19.67-2+deb10u2

Enabled extensions:
- none

**Comment by phoerious** [comment]
The first warning is the result of a needed workaround for a Qt bug, the other two point to an incompatibility between the AppImage and your OpenSSL version.

**Comment by sfuhrm** [comment]
Thanks for the quick reaction!
With the amount of shared libraries in the appimage I'm curious why the openssl library is loaded from the OS? Are the OS SSL CA certs needed?

**Comment by phoerious** [comment]
Yes, OpenSSL needs a certificate store and I believe it's generally better to have such a critical library updated by the system.

**Comment by sfuhrm** [comment]
Well so from my understanding there is no clean solution here -> closing
