### ISSUE TITLE
Gratuitous pop-up when saving database to Dropbox

### ISSUE THREAD

**Issue by Bill-cpp** [keepassxreboot/keepassxc#4255]
My KeePassXC database lives on Dropbox. When I open it, modify it, and then save, a gratuitous **File has changed** modal dialog appears. I first encountered this bug when upgrading from 2.4.3 to 2.5.1. Thinking #3991 would fix the problem, I upgraded to 2.5.3. Problem persists. This bug doesn't much affect my usage of KeePassXC, but it's annoying and a bit disconcerting.

## Expected Behavior
When saving a database, nothing anomalous happens. 

## Current Behavior
The anomalous behavior is intermittent, but it happens for me about 90 percent of the time.

After selecting **Save database**, the database is saved. Then, after a delay of 1 or 2 seconds, a gratuitous **File has changed** modal dialog appears, asking me whether I want to load the changes. I must select **Yes** or **No**. Either way, the popup disappears, and there is no discernible state change.

## Steps to Reproduce
1. Open database stored on Dropbox.
2. Modify database.
3. Save database.
4. Wait 1 or 2 seconds.
5. About 90 percent of the time, **File has changed** modal dialog appears.

## Debug Info
KeePassXC - Version 2.5.3
Revision: f8c962b
Distribution: AppImage

Qt 5.12.6
Debugging mode is disabled.

Operating system: Linux Mint 19.3
CPU architecture: x86_64
Kernel: linux 4.15.0-74-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.1

**Comment by droidmonkey** [comment]
Thank you will try to reproduce. For background, 2.5.2 introduced a change that checks to see if the actual file contents changed (hash) prior to issuing a change notification to the rest of the code. This was done because Dropbox keeps touching files after sync modifying the mtime unnecessarily triggering a change notice.

**Comment by Bill-cpp** [comment]
That makes sense. So checking the hash should work. I'm assuming there's some kind of timing issue, since the problem is intermittent.

**Comment by droidmonkey** [comment]
Does your database have a long decryption time setup?

**Comment by Bill-cpp** [comment]
No. In Database settings -> Security -> Encryption Settings, selecting _Benchmark 1-second delay_ yields 8 transform rounds. My database is set for 12 transform rounds. This should require 1.5 seconds to decrypt (right?), but AFAICT my database unlocks in a little less than a second.

**Comment by droidmonkey** [comment]
Ok just wondering trying to isolate the cause

**Comment by Bill-cpp** [comment]
Right. Let me know if there's any other way I can help.

**Comment by droidmonkey** [comment]
Using 2.5.3 snap distribution on Ubuntu 19.10, I turned off automatic reload of database (which would cause a popup to appear) and created a database with a 35 MB attachment to slow things down. I stored it in dropbox then made several trivial changes. Database saved without issue each time and synced with Dropbox. I never once saw a popup requesting to reload the database.

**Comment by Bill-cpp** [comment]
To test the problem more carefully, I created two trivial test databases (1.8 KB) called **short** and **long**, using default settings except as follows: For Encryption Settings, I set **short** to 1 transform round and **long** to 80 transform rounds. I also set parallelism to 1 for both. On my desktop, **short** opens in perhaps 100 mS, and **long** opens in 15 seconds. When I modify and save the **short** and **long** databases, I find the following:

1. The 90 percent bug rate I reported originally is now about 10 percent. I have no idea why.
2. The bug appears in waves: If the bug appears in one test, it's likely to appear again if I repeat the test right away with the same database. If the bug doesn't appear in one test, it's likely to not appear the next time with the same database. In other words, there's typically a sequence of multiple successive bugs followed by a sequence of multiple no-bugs. This makes me think the bug is sensitive to something that's changing slowly in the environment. 
3. The bug seems to occur more often in the **long** database than in the **short** database.

Q: In **Settings**, I found an option **Safely save database files (may be incompatible with Dropbox, etc)**, which is checked by default. I would be afraid to uncheck this box. What exactly is the possible Dropbox incompatibility? Since I didn't change the defaults, is my problem related to this?

Q: Further down in that same **Settings** window, I see an option to **Automatically reload the database when modified externally**. I'm guessing this might be what you referred to in your most recent comment. This checkbox is unchecked by default. Since I use the defaults, shouldn't I already be OK?

**Comment by droidmonkey** [comment]
If you check that last setting you won't see the popups

**Comment by Bill-cpp** [comment]
I'll try that, and see if it works OK.

**Comment by JulianVolodia** [comment]
@Bill-cpp what if you save db with Dropbox stopped and after saving start Dropbox. Does it alter (and how?) the file on your OS fs?

**Comment by Bill-cpp** [comment]
@droidmonkey: Checking the checkbox **Automatically reload the database when modified externally** seems to prevent the gratuitous pop-up dialog. Since the problem has been intermittent, I've waited until now to report back.

It was not obvious to me that checking this checkbox would solve my Dropbox problem. Perhaps it would clarify to add a parenthetical addendum to this option saying something like **(fixes Dropbox incompatibility)**, referring to the **Safely save database files** option.

**Comment by droidmonkey** [comment]
That setting is not related to Dropbox, but network shares.

**Comment by JulianVolodia** [comment]
@Bill-cpp have you check what dropbox does (binary) to your file while trying to sync? Even no changes was applied literally by you. Maybe that will show what is done to your file.

**Comment by Bill-cpp** [comment]
@droidmonkey: As I understood your comment on 1/31, you suggested that my pop-up problem with Dropbox would go away if I checked the box for **Automatically reload the database when modified externally**. So I gave that a good try, and reported that it worked. Now you're saying that that setting is not related to Dropbox. What am I missing?

@JulianVolodia: Although I'm using Dropbox for sharing, I'm only saving the database to Dropbox from one (Linux Mint) machine. From other machines, I'm only reading the database. So my assumption is that Dropbox is simply gratuitously updating the timestamp on my database file past my write time, thus causing the pop-up. (At least, that's my hope!) But to answer your questions, no, I haven't really tried to debug what Dropbox is doing.

**Comment by droidmonkey** [comment]
The pop-up is because "something" is modifying your database and changing the hash of the file. In this particular case, it appears to be Dropbox. However that setting, and the feature, is meant for shared databases on network shares. Adding Dropbox to the setting is inappropriate since its not specifically for Dropbox

**Comment by Bill-cpp** [comment]
It sounds pretty scary to think that Dropbox is modifying my database. Doesn't the hash depend only on the file content, and not on the file timestamp? Why would Dropbox modify the content? And if it did, why wouldn't that trash the file?

**Comment by droidmonkey** [comment]
I can't answer those questions. You can do some tests yourself, take the MD5 hash of the file right after saving then wait until KeePassXC gives you the reload pop-up. Take the MD5 hash again.

**Comment by phoerious** [comment]
I doubt the actual contents are modified. It's probably just the ctime or mtime that's changed.

**Comment by droidmonkey** [comment]
2.5.2 explicitly added a check to ignore just mtime/ctime changes.

**Comment by Bill-cpp** [comment]
Looking more carefully, I now see that my problem description was slightly incorrect: The “Wait 1 or 2 seconds” is apparently the time it took to encrypt my 66KB database. Therefore, saving to dropbox occurs **after** that delay, not before. The pop-up actually occurs **immediately upon saving**, not after a noticeable delay. I know this from saving a test database with a 5-second encryption delay, and watching for the end of the greyed-out period. The file's MD5 hash does not change until the greyed-out period ends. The pop-up occurs at essentially the same time that the grey-out ends.

Therefore, I don't see a practical way to take an MD5 hash after saving but before pop-up, unless I build and modify KeePassXC to execute MD5. Any ideas for a simpler way to diagnose this problem?

**Comment by droidmonkey** [comment]
With your new description I know where the problem lies

**Comment by Bill-cpp** [comment]
Terrific! Thanks so much, and sorry for the not-quite-correct initial problem description. How will I know what release the fix will be in?

**Comment by droidmonkey** [comment]
It'll be 2.6.0
