### ISSUE TITLE
CSV Import toggle "first column has field names" hangs for ~20 seconds

### ISSUE THREAD

**Issue by stdedos** [keepassxreboot/keepassxc#4257]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

I tried to import Chrome passwords to KeePassXC.

(First of all, I don't understand why do I have to "mandatorily" create a new database, save it, and then import that one to the one database that I have already open. It could "just" be a Root/Child, named at the last step).

When I tried to process the Chrome.csv, I noticed that "first column has field names" was not detected, so I activated it.

That resulted in a good application hung (with Windows reporting as "Unresponsive") for a good time.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Toggling that option should be a breeze.

## Current Behavior
[NOTE]: # ( Tell us what actually happens )
Lags ... excessively

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1. Export Chrome passwords as CSV
2. Start the import process to KeePassXC
3. Toggle the "first column has field names" option

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )

_(maybe make debuginfo `LC=C`?)_

KeePassXC - Version 2.5.3
Revision: f8c962b

Qt 5.13.2
Debugging mode is disabled.

Operating system: Windows 10 (10.0)
CPU architecture: x86_64
Kernel: winnt 10.0.17134

Enabled extensions:
- Auto-Type
- Ενσωμάτωση Περιηγητή
- πράκτορας SSH
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.5

**Comment by droidmonkey** [comment]
How big is this CSV file

**Comment by stdedos** [comment]
55kb / 651 lines

**Comment by droidmonkey** [comment]
Seems related to all your other freezes. I think it's your computer and/or way you are running the application.

**Comment by droidmonkey** [comment]
can you provide the first line of the exported CSV file from chrome? You can copy/paste it into this issue. I want to make sure we are replicating with the same CSV file.

**Comment by stdedos** [comment]
```
name,url,username,password
example.org,https://example.org/,user,secret
example2.org,https://example2.org/,anotheruser,extrasecret
[...]
```

**Comment by droidmonkey** [comment]
I do get a small hang (~1 second) but it is certainly not terrible.

**Comment by stdedos** [comment]
I could just do a video to prove that what I see is happening; due to privacy issues however, I don't really want to. Is there some debug/tracing I could add, and upload a log instead?

**Comment by droidmonkey** [comment]
I don't disbelieve you, I think this has more to do with your computer then our app
