### ISSUE TITLE
"Download all favicons" freezes app

### ISSUE THREAD

**Issue by stdedos** [keepassxreboot/keepassxc#4258]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

I recently imported my Chrome.csv (>600 entries). Then, I wanted to "beautify" my database, so I eagerly pressed "Donwload all favicons".

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
I should be seeing a "proper" progress bar with scraped entries/urls/state(search/download/complet) table

## Current Behavior
[NOTE]: # ( Tell us what actually happens )
It appears that too much might be done on the main thread (along with all that network).
While the current state is not bad (freeze lasted less than 3 minutes, I think, since I was multitasking), it is a "not happy" experience

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1.
2.
3.

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.5.3
Revision: f8c962b

Qt 5.13.2
Debugging mode is disabled.

Operating system: Windows 10 (10.0)
CPU architecture: x86_64
Kernel: winnt 10.0.17134

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.5

**Comment by droidmonkey** [comment]
Everything is already done in a thread pool... Not sure what is going on with your setup but doesn't freeze for me.

**Comment by stdedos** [comment]
I keep forgetting to mention: I am using the portable version (if that changes things)

**Comment by W1r3W0lf** [comment]
I run into a similar issue on Linux. But instead of freezing the program flat out crashes if you click on the close button if it's not finished downlaoding all of the icons.

I'm not sure if this requires a new issue or not.

**Comment by droidmonkey** [comment]
@W1r3W0lf see if it still crashes using the latest https://snapshot.keepassxc.org

**Comment by W1r3W0lf** [comment]
@droidmonkey I tried it out and it still crashes.

It's trying to download about 240 icons. 

And here is the output I got in the terminal.

Empty filename passed to function
Empty filename passed to function
QObject::startTimer: Timers cannot have negative intervals
qt.network.ssl: QSslSocket: cannot resolve CRYPTO_num_locks
qt.network.ssl: QSslSocket: cannot resolve CRYPTO_set_id_callback
qt.network.ssl: QSslSocket: cannot resolve CRYPTO_set_locking_callback
qt.network.ssl: QSslSocket: cannot resolve ERR_free_strings
qt.network.ssl: QSslSocket: cannot resolve EVP_CIPHER_CTX_cleanup
qt.network.ssl: QSslSocket: cannot resolve EVP_CIPHER_CTX_init
qt.network.ssl: QSslSocket: cannot resolve sk_new_null
qt.network.ssl: QSslSocket: cannot resolve sk_push
qt.network.ssl: QSslSocket: cannot resolve sk_free
qt.network.ssl: QSslSocket: cannot resolve sk_num
qt.network.ssl: QSslSocket: cannot resolve sk_pop_free
qt.network.ssl: QSslSocket: cannot resolve sk_value
qt.network.ssl: QSslSocket: cannot resolve SSL_library_init
qt.network.ssl: QSslSocket: cannot resolve SSL_load_error_strings
qt.network.ssl: QSslSocket: cannot resolve SSL_get_ex_new_index
qt.network.ssl: QSslSocket: cannot resolve SSLv3_client_method
qt.network.ssl: QSslSocket: cannot resolve SSLv23_client_method
qt.network.ssl: QSslSocket: cannot resolve SSLv3_server_method
qt.network.ssl: QSslSocket: cannot resolve SSLv23_server_method
qt.network.ssl: QSslSocket: cannot resolve X509_STORE_CTX_get_chain
qt.network.ssl: QSslSocket: cannot resolve OPENSSL_add_all_algorithms_noconf
qt.network.ssl: QSslSocket: cannot resolve OPENSSL_add_all_algorithms_conf
qt.network.ssl: QSslSocket: cannot resolve SSLeay
qt.network.ssl: Incompatible version of OpenSSL
qt.network.ssl: QSslSocket::connectToHostEncrypted: TLS initialization failed
qt.network.ssl: QSslSocket::connectToHostEncrypted: TLS initialization failed
qt.network.ssl: QSslSocket::connectToHostEncrypted: TLS initialization failed
...
Then it ends in a segmentation fault.

**Comment by droidmonkey** [comment]
@phoerious we need to fix the ssl issues with appimage, if possible

**Comment by phoerious** [comment]
Which Linux distribution is that?

**Comment by W1r3W0lf** [comment]
@phoerious I'm using Ubuntu 19.10.

**Comment by droidmonkey** [comment]
Closed because it is not reproducible on Windows.
