### ISSUE TITLE
Cannot import .ico

### ISSUE THREAD

**Issue by stdedos** [keepassxreboot/keepassxc#4259]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

I recently imported my Chrome.csv. Until I clear them out, I moved them to a separate Root/Child, and I wanted to assign it the Google Chrome favicon

With this search: https://duckduckgo.com/?q=chrome+favicon&atb=v118-7o_&ia=web
I downloaded this [chrome.google.com.ico.zip](https://github.com/keepassxreboot/keepassxc/files/4124960/chrome.google.com.ico.zip)

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

Favicon was imported

## Current Behavior
[NOTE]: # ( Tell us what actually happens )

```
No icons were loaded
The following icon failed:
E:/user/Desktop/chrome.google.com.ico
```

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )

I could also be a feature request: Expand the DuckDuckGo "mechanism", so that I can somehow provide terms, and get favicon options to select from (in expansion of the mechanism is used to get those favicons). It would resemble e.g. Calibre's / VirtualDJ's mechanism of scrapping book/album covers - then this would go away.

Of course, "tin-foil hats" can still opt-in the "import file" way; I don't see why should I download, save, locate, import, and remove a file - now that there is a scrapping mechanism

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1.
2.
3.

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.5.3
Revision: f8c962b

Qt 5.13.2
Debugging mode is disabled.

Operating system: Windows 10 (10.0)
CPU architecture: x86_64
Kernel: winnt 10.0.17134

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.5

**Comment by droidmonkey** [comment]
Just set the url to whatever you want the icon to be, download it, then set the url back. With that said, we can import ico files, perhaps that one is malformed?

**Comment by stdedos** [comment]
> Just set the url to whatever you want the icon to be, download it, then set the url back. 

Should've thought of that.
Meh, but I understand why. It can be a workaround.

> With that said, we can import ico files, perhaps that one is malformed?

I know, I've been doing it 😕 That's why I uploaded it. "It seemed like every other ico to me".

**Comment by droidmonkey** [comment]
The "ico" file you downloaded is actually a PNG image. That is why it didn't load:

```
00000000: 89 50 4E 47 0D 0A 1A 0A 00 00 00 0D 49 48 44 52    .PNG........IHDR
00000010: 00 00 00 10 00 00 00 10 08 03 00 00 00 28 2D 0F    .............(-.
00000020: 53 00 00 01 59 50 4C 54 45 00 00 00 7A 9D 51 E3    S...YPLTE...z.Qc
00000030: 8E 4B F4 C8 41 19 99 5B DB 52 4B DC 49 3E DD 50    .KtHA..[[RK\I>]P
00000040: 44 FE CD 41 16 A0 5C 1D A3 61 FE CC 41 1E A3 61    D~MA..\.#a~LA.#a
00000050: DD 4B 40 17 9F 5B FC CB 40 17 9E 5B FC CB 40 DB    ]K@..[|K@..[|K@[
```

**Comment by stdedos** [comment]
Interesting. I didn't know that "it was important".

I need to stop hanging around Linux 😆
