### ISSUE TITLE
Auto-Type {CLEARFIELD} not working

### ISSUE THREAD

**Issue by schiorean** [keepassxreboot/keepassxc#426]
I want to make sure that user name and password fields are cleared. So I setup the auto-type sequence as {CLEARFIELD}{USERNAME}{TAB}{CLEARFIELD}{PASSWORD}

## Expected Behavior
I expected that user name and password fields will be cleared.

## Current Behavior
The fields weren't cleared, just like {CLEARFIELD} was non existent.

## Steps to Reproduce (for bugs)
1. Set auto-type (either group or entry itself) {CLEARFIELD}{USERNAME}{TAB}{CLEARFIELD}{PASSWORD}
2. The try auto type feature

## Your Environment

* KeePassXC version/commit used: 2.1.3
* Qt version (e.g. Qt 5.3): 5.8.0
* Compiler (e.g. Clang++3.6.0): 
* Operating System and version: Ubuntu 16.04.2

**Comment by TheZ3ro** [comment]
I'm aware of this bug and I'm surprised it was never added as an Issue

**Comment by droidmonkey** [comment]
Can this also be implemented as a generic config option? (e.g., Always clear fields before autotype)

**Comment by chrisma** [comment]
@droidmonkey Instead, you can also try to edit the root group attributes (*right-click on the root group -> edit group*) to set a default auto-type sequence for all entries (including the `CLEARFIELD` command):

![image](https://user-images.githubusercontent.com/1652117/38358527-c1904044-38c5-11e8-9858-36bdccb87a14.png)

As long as all entries and groups are set to inherit the auto-type behavior from parent groups this should work.

![image](https://user-images.githubusercontent.com/1652117/38358618-108734c8-38c6-11e8-94f6-3092cbd644d1.png)

**Comment by droidmonkey** [comment]
This was already fixed
