### ISSUE TITLE
Autotype not working in latest KeePass XC 2.5.3 on Mac OSX Mojave

### ISSUE THREAD

**Issue by hermansb** [keepassxreboot/keepassxc#4264]
* Just recently upgraded from KeePassXC 2.4 and after the upgrade i immediately noticed that while the shortcuts for autotype worked, when I selected the entry for autotype in the Autotype window nothing gets typed. This is despite it working in the previous version referenced above and allowing KeePassXC to control the computer through Accessibility in the Mac OS X Settings for Security and Privacy.

**Comment by droidmonkey** [comment]
I can guarantee that Auto-Type works perfectly well. Try totally removing permissions and re-adding them again.

**Comment by infidelus** [comment]
I don't know if this is relevant but, having recently started using KeePassXC on Linux, I couldn't get auto-type working either and was about to post about it.  Having just seen this thread I then went to the general options and saw the auto-type tab which had nothing set up for the default key combination.  Once I'd set the default ctrl+shift+w it worked as expected.

**Comment by hermansb** [comment]
Thank you infidelus! That worked for me. I tried removing/re-adding permissions which did nothing. Saw the global auto-type shortcut was set to Ctrl+V which did nothing, set it to ctrl+shift+V which fixed the issue.

**Comment by hermansb** [comment]
So the issue here seems to be that the global auto-type shortcut needs to be set up once again post-installation

**Comment by droidmonkey** [comment]
Ctrl+V is a terrible choice since that is a standard shortcut (paste) in almost any application which will result in KeePassXC never seeing it.

**Comment by droidmonkey** [comment]
Ctrl+V is a terrible choice since that is a standard shortcut (paste) in almost any application which will result in KeePassXC never seeing it.

**Comment by hermansb** [comment]
@droidmonkey you may be confusing cmd+v with ctrl+v on Macs at least. ctrl+v does indeed translate to the paste shortcut on Windows and Linux machines. However on Macs the shortcut does not do anything. Would it be possible to put a conditional around the platform and allow it to be used on Macs?

**Comment by droidmonkey** [comment]
We allow you to use whatever shortcut you want. Good point on the Mac difference. Either way, a global shortcut with just one modifier key will usually get gobbled up by the focused application.

**Comment by infidelus** [comment]
I guess in my case either the global shortcut was never there when I originally installed KeePassXC (which if memory serves was 2.5.1) or the upgrade to 2.5.2/2.5.3 deleted it, so a check needs to be made to ensure the box isn't empty.

**Comment by hermansb** [comment]
Sweet so I set it back to ctrl+V on a Mac and its working as before. There seems to be a bug that after the upgrade the global autotype shortcut doesn't work until you set it to another shortcut and then set it back again, perhaps only on a Mac?

**Comment by droidmonkey** [comment]
We did not clear the setting and the default is no shortcut key set. I have upgraded my test Mac KeePassXC and worked on develop versions numerous times without having to reset the key. Could just be a random issue that required re-establish the setting.

**Comment by infidelus** [comment]
So it's not set at all by default?  This seems to go against the documentation at https://github.com/keepassxreboot/keepassxc/blob/develop/docs/KEYBINDS.md which is linked directly from the applications' Help menu.  If it needs to be manually set could I suggest the document be updated to reflect that.

**Comment by droidmonkey** [comment]
Trigger Auto-Type is referring to entry level Auto-Type. This is from the entry list. That is NOT global Auto-Type shortcut.

**Comment by infidelus** [comment]
Sorry, I'm not quite sure what your comment actually means.

From my perspective, as a new user, the help menu should reflect the global default shortcut, which in this case is Ctrl + Shift + V.  As my global entry was blank when I looked at it, either the documentation is wrong and needs updating or the documentation is right and there's a bug in KeePassXC.

**Comment by droidmonkey** [comment]
Entry-level Auto-Type:
![image](https://user-images.githubusercontent.com/2809491/73593820-17ba5900-44d6-11ea-9789-deaf0ca2ff2a.png)

Global Auto-Type:
![image](https://user-images.githubusercontent.com/2809491/73593819-14bf6880-44d6-11ea-9386-0a3e18d5e1fd.png)

**Comment by infidelus** [comment]
Thanks, I see the difference between the two.  The point still remains though, the documentation states the auto-type shortcut is Ctrl + Shift + V which, to me, means that should be the default and should already be set.  In my case it wasn't, so again is it a bug or is the documentation wrong?

**Comment by droidmonkey** [comment]
Neither! These are two completely different functions.

**Comment by infidelus** [comment]
OK, I'm obviously not being clear here, so apologies for that.  Ignore the entry level AutoType.  I am talking about the global AutoType shortcut.

So, if you open KeePassXC, click on 'Help' then 'Keyboard Shortcuts' it takes you to [this GitHub page](https://github.com/keepassxreboot/keepassxc/blob/develop/docs/KEYBINDS.md).

On that page it clearly states that there is a default shortcut for AutoType:

`Trigger AutoType | Ctrl + Shift - V`

As already mentioned, when I looked at this entry after initially seeing this bug entry, the global shortcut setting was blank.  So if the documentation states that AutoType should be triggered by the above key combination, the fact the setting was blank on my install means there is either a bug somewhere that:

- didn't set it
or
- deleted it after a version upgrade

If there is not supposed to be a default AutoType key combination and it's something the user has to manually define, then the documentation is wrong.

**Comment by droidmonkey** [comment]
You need to take a step back. "Trigger AutoType" is not "Trigger **GLOBAL** AutoType". There is no bug in the code. We do not set the **GLOBAL** AutoType shortcut by default to anything.

**Comment by infidelus** [comment]
OK, and again apologies, but if you don't set a global AutoType, what is the point of the documentation that says there is a defined shortcut?  If the documentation isn't wrong, then it's just extremely unclear and quite unhelpful as any new user (me being a case in point) will see that and assume that there IS a default and that it's not working.

You see how this is confusing?

**Comment by climb-on** [comment]
I realize infidelus's comments above are old, but clearly that user was having difficulty realizing that "Global AutoType" and "AutoType" are two different things.  This caught me out at first.  It does make perfect sense, but at the same time this is exactly the kind of thing that easily trips people up.  Perhaps it would be better to name "Global AutoType" something completely different.

That said, I just installed the latest version of KeepassXC (2.7.1) on my Mac OS Catalina 10.15.7.  AutoType does not work.  It pops up a dialog asking if I want to perform AutoType in the previous window, and when I say yes it returns focus to that window.  But it does not type anything.

Can't get Global AutoType to work either, but I don't really use that, so that's less of a concern.

Switched back to 2.3.4 and it works fine again.

Thanks,

Duncan

**Comment by droidmonkey** [comment]
We have a rather well written user guide now that answers all the above in a better way than it existed 3 years ago. You may have to remove and re-add the permissions given to KeePassXC after you upgrade from 2.3 to 2.7. That is a rather substantial jump (we at least recommend you use 2.6) and I can confirm that Auto-Type does work quite well on macOS for 2.7.1.

**Comment by climb-on** [comment]
Thanks.  I did try removing and re-adding permissions, but at first it didn't seem toward.  However, I have it working for me now.  What worked was:

a) Remove both the old and new versions of KeepassXC from the Mac, which removed the permissions. (Having two different versions installed I think was what was messing things up.)

b) Reboot the Mac (this might not have been necessary)

c) Reinstall the latest version of KeepassXC

d) Grant permissions to the new version - "Allow the apps below to control your computer" under  System Preferences / Security and Privacy / Privacy / Accessibility. 

Thanks!

Duncan
