### ISSUE TITLE
Ctrl-Shift-U not actioning goto url

### ISSUE THREAD

**Issue by bigalgeorge** [keepassxreboot/keepassxc#4268]
Hi iI type in first letters of desired item until it shows the hit the keycombo. Elementary OS the combo works as expected. In Budgie it adds a 'U' to the search line.
If I move to the line of url (instead of search) Ctrl+Shift+U then instantiate browser; problem only when cursor is in search field.
I suspect this is an issue with how Budgie handles keyboard but worth mentioning anyway.

**Comment by droidmonkey** [comment]
Yah this isn't our bug.
