### ISSUE TITLE
Password Health Check - UI Improvements

### ISSUE THREAD

**Issue by OLLI-S** [keepassxreboot/keepassxc#4274]
## Summary
Today I tested the new Password Health Check (https://github.com/keepassxreboot/keepassxc/pull/3993) and here is some feedback for the UI

## Details
When I run the report, then the results look like this:

![image](https://user-images.githubusercontent.com/8037790/73594513-620bfc00-450f-11ea-8fe8-dc8915669957.png)

Here I wish to have the following features:
1. Allow me to resize the columns (so I can make the "Title" a bit smaller to see more text in "Reason")
2. The column "Title" is aligned to the longest entry, but maybe you make the column smaller, so 80% of all entries can be displayed in one line (the text of the other 20% is wrapped into multiple lines)
3. Same for the column "Path" (also here the width should be reduced like suggested in 2.)
4. Add icons in addition to the color in the first column as discussed here: https://github.com/keepassxreboot/keepassxc/issues/1083#issuecomment-571751841
5. Show statistics below the table (number of weak passwords, number of expired passwords, number of reused passwords, total number of findings) like you have them in the Statistics page (saves me one click)
6. Exclude expired entries like suggested here https://github.com/keepassxreboot/keepassxc/issues/551#issuecomment-573309071
I have 116 expired entries and nearly all of them are for services/websites that are no longer existing (but I want to keep the entries).
7. Let me sort the table by any column
8. Show the entropy directly behind the text "Very weak password" (is faster than having to open the tool tip in the column "Reason") so this info can be removed from the tool tipp:
For example: "Very weak password (entropy is 28.73 bits)"
9. Show the expiry date directly behind the text "Password has expired" (is faster than having to open the tool tip in the column "Reason") so this info can be removed from the tool tipp:
For example: "Password has expired (31.12.2006 23:00)"
10. For re-used passwords it would be cool to have the possibility to expand the text in the column "Reason" so I see the locations directly below the line "Password is used x times".
So here also no tool tipp is needed (it can completely be removed)

The Health Check is a fantastic feature and I see now that i have a lot to do!

## Debug Info
KeePassXC - Version 2.5.3-snapshot
Build Type: Snapshot
Revision: c427000

Qt 5.12.0
Debugging mode is disabled.

Operating system: Windows 10 (10.0)
CPU architecture: x86_64
Kernel: winnt 10.0.18363

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.4

**Comment by droidmonkey** [comment]
Entropy is confusing information to most people, which is why it's in the tooltip. We also don't want to clutter the reason field with so much information to the point it becomes cluttered. I think showing the number of days the password is expired is more readable then the exact date. Resizing and sorting columns would be a great improvement, I think the title and path columns should have word wrapping turned on.

Excluding _all_ expired entries is easy. What we would most likely want to do is add a setting to groups to exclude whole groups from the health report (similar to exclude from search) so you can toss all your expired entries in that group.

Great feedback!

**Comment by OLLI-S** [comment]
@droidmonkey I updated my text above while you posted your reply (textual changes).

One reason why I want to get rid of the tool tip is: how can blind people get this information with a screen reader? If It is a normal table where the text is written inside, then the chances are higher that the screen reader can read it.
And a tool tip forces users to perform a manual action (move the mouse and wait) and this for each entry. This is the second reason why I want to get rid of the too tipp.

Preventing whole groups from the health report is a fantastic idea.
I already begun to move expired entries into a separate group so they can be ignored.
Perfect.

And ignoring single entries from health check is suggested here: https://github.com/keepassxreboot/keepassxc/issues/4168

**Comment by droidmonkey** [comment]
The point of the tooltip is that it presents information that is _not necessary_ to most users. For accessibility we can populate the "accessible description" in addition to the tooltip so that screen readers will read it out.

**Comment by OLLI-S** [comment]
@droidmonkey I updated my reasons in the posting above (added reason 2.)

I agree that the password entropy and the exact expiry date is an information, that is optional (not needed for normal users).
But the location of re-used passwords is really important!

So what about adding multiple "details" pulldowns in one cell:

<details>
  <summary>Very weak password</summary>
  Password entropy is 28.73 bits
</details>
<details>
  <summary>Password has expired </summary>
  Password expiry was 31.12.2006 23:00
</details>
<details>
  <summary>Password is used 3 times</summary>

- Used in OLLI\Hardware\Network\Name of the Entry
- Used in OLLI\Music\Name of the second entry
- Used in OLLI\Programming\Lazarus\Name of the 3rd Entry

</details>

This way users can collapse and expand the information they need.
And you can get rid of the tool tips.
