### ISSUE TITLE
Crashes on Save As

### ISSUE THREAD

**Issue by architect55** [keepassxreboot/keepassxc#4277]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Expected Behavior
[NOTE]: # ( Save as a new KeePassXC file when updating passwords)

## Current Behavior
[NOTE]: # ( KeePasXC crashes when doing a Save As )

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1.
2.
3.

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION 2.5.3
Revision: REVISION

Libraries:
- LIBS

Operating system: Mac OS Mojave
CPU architecture: ARCH
Kernel: KERNEL

Enabled extensions:
- EXTENSIONS

**Comment by droidmonkey** [comment]
Thanks for providing all the information!

**Comment by phoerious** [comment]
Probably a duplicate of #4289 anyway.
