### ISSUE TITLE
Add "exlude characters" to random password generation options

### ISSUE THREAD

**Issue by codekandis** [keepassxreboot/keepassxc#4278]
I'm sorry I'm not able to provide you with an feature request in your desired way. But I really took care of your needs while writing my request.

I'm actually using KeepassXC to provide ansible vault passwords in a vagrant provisioning process. This requires to provide the Ansible Vault password by a shell script which can lead to unexpected side effects while the passwords can contain special shell interpreted characters. For example I experienced problems if the password includes characters like `, ^, \ and others.

Currently KeepassXC provides options to activate very wide ranged sets of characters for new passwords. Repsecting my current experiences I'm often generating a password multiple times (in my case passwords of a length of 50) until I can assure the password doesn't contain any unwanted characters. This can lead to a lot of try and error cases until a password is `accepted` by Ansible.

I really encourage you to provide an option to exclude characters from the password generation. My use case described above is one of possible use cases where a password in fact reasonably needs character exlusions.

**Comment by droidmonkey** [comment]
Feature already exists. Click the advanced button in the password generator.

**Comment by codekandis** [comment]
I'm sorry. The official Debian release is outdated. I forgot to check first. I using the AppImage now. Works for me.
