### ISSUE TITLE
Accented characteres don't work in the master key input field on Linux

### ISSUE THREAD

**Issue by tonnydourado** [keepassxreboot/keepassxc#428]
My master key has some accented charactes in it (like á, é, ç, ó, ú, ñ, etc), but the accent is not inputted in the master key field, so I can't unlock the database. I typed it in other window and copied to the master key input field and it worked, though.

## Expected Behavior
When I type a accented character in the master key input field, it should input the accented character

## Current Behavior
The character without the accent is entered. So, if I type `á`, it shows up as `a`

## Steps to Reproduce (for bugs)

1. Install KeepassXC on Ubuntu 14.04, with Unity, pt_BR keyboard
2. Open a database whose master key contains accented characters
3. Try to type the master key
4. Accented characters will show without the accent

## Context

Since my password has those accented characteres, I can't unlock my database without resorting to workarounds 

## Your Environment

* KeePassXC 2.1.3
* Qt 5.8.0
* Operating System and version: Ubuntu 14.04, running Unity, pt_BR keyboard, but the system's language is en_US.

**Comment by seatedscribe** [comment]
Tried on KXC 2.1.0 and accents are displayed correctly.

**Comment by TheZ3ro** [comment]
@tonnydourado are you using the Snap package?

**Comment by tonnydourado** [comment]
@TheZ3ro No, the AppImage package.

**Comment by phoerious** [comment]
Can you try the DEB package, please?

**Comment by tonnydourado** [comment]
I didn't really want to run a unofficial package, but I'll give it a try

**Comment by tonnydourado** [comment]
Tried, can't install any of the .deb packages in Ubuntu 14.04, they all have unsolvable dependencies (libgcrypt20 >= 1.7.0 for testing and unstable and libqt5core5a >= 5.3.0 for stable)

**Comment by Keisial** [comment]
Have you tried with the locale set to pt_BR instead of en_US? (not necessarily for the whole system, you may change the env variables before launching keepassxc)

keepassx masked password fields fail miserably on accented characters, but unless there has been a recent regression, they work on keepassxc. I will test with last version to confirm this.

Note that you can build keepassxc on Ubuntu 14.04 without needing to upgrade the libraries. There's a bug with native menus if you are using metacity as WM, though.

**Comment by tonnydourado** [comment]
Tried setting `LC_ALL`, `LANG` and `LANGUAGE` in the terminal before launching the AppImage executable. The text in the UI actually changed, but the master key field still didn't show the accented character in my master key.

**Comment by Keisial** [comment]
I confirm that I can enter accented characters on the master password field also on KeePassxc 2.1.3. I am using a copy natively compiled on Ubuntu 14.04.

I would try compiling it locally, in case the AppImage is somehow interfering.
See https://github.com/keepassxreboot/keepassxc/wiki/Set-up-Build-Environment-on-Linux and https://github.com/keepassxreboot/keepassxc/wiki/Building-KeePassXC

**Comment by hecnm** [comment]
I can confirm this happens as well in OSX 10.11.6 (El Capitan) with KeePassXC 2.2.0 and US keyboard.
For inputing accented characters with the US keyboard, a sequence is needed (for example: Alt+e, then a equals á).
When typed in the default mode for the master key (masked characters) it behaves as described above (ignoring the accent). When the real characters are showing up (the eye button has been clicked) the same sequence gets the desired accented character.

**Comment by phoerious** [comment]
Most likely a Qt bug. Maybe not directly related to #324, but I assume Qt is somehow using a non-deadkey version of your input layout.

**Comment by rgo** [comment]
KeePassXC 2.3.4 in OSX 10.13.6 and installed with Homebrew has the same issue and behaviour described by @ghost

**Comment by droidmonkey** [comment]
Still an issue with 2.4.3?

**Comment by FMuro** [comment]
> Still an issue with 2.4.3?

Yes. The ugly workaround is to type the password visibly. It also happens when you type an accent and then the place in order to input the accent along.

**Comment by droidmonkey** [comment]
This is better tracked by #2452
