### ISSUE TITLE
Two-Channel auto-type obfuscation

### ISSUE THREAD

**Issue by Gfiles** [keepassxreboot/keepassxc#4282]
## Summary
This is a Feature in Keepass 2 that will scramble the why the user and password are copied to their respective fields

## Desired Behavior
In the Auto-Type Settings have the option to activate this Feature.
If active when the user presses auto-type the program will randomly copy over part of the user, then it can do some backspace, write in some more text, move the cursor to the left, type some more move the cursor to the right , copy some text. for the password the same type of scrambling will happen. ate the send have the option to send enter or not (Not all site or programs will work with enter at the end.
The idea here to to complicate the reading of copied or type text, which could be read by key-loggers.
Specific features:
Copy part of the text randomly
move cursor back and forth randomly,
type wrong text randomly,
delete the wrong text,
delete proper text randomly.
Use copy paste functions and typing text.

## Possible Solution
[NOTE]: # ( Not required, but suggest ideas on how to implement the addition or change )

## Context
This is the Feaure in Keepass 2 that makes me estay with the program, In Keepass XC had this feature i would already have moved over.
For me this is the best feature of the Auto-Typing and I alwys use it on PC´s that I don´t trust when i need to acess my accounts.

**Comment by droidmonkey** [comment]
Search the issues please
