### ISSUE TITLE
verifying signature if installing through debian software center

### ISSUE THREAD

**Issue by debjanus** [keepassxreboot/keepassxc#4283]
Good evening, I wanted to ask, how can I verify the signature of keepassxc, if I installed the program through the Debian software center or if I installed it through sudo get install keepassxc? Installing this way I cannot find the folder where the .digest file is located, so the command reported on the internet site doesn't work?

**Comment by droidmonkey** [comment]
You cannot verify the signature via this installation method. Those packages are built and maintained by Debian, not us.
