### ISSUE TITLE
Deliver a set of black icons for groups

### ISSUE THREAD

**Issue by OLLI-S** [keepassxreboot/keepassxc#4285]
## Summary
Deliver a set of black icons in addition to the default icons.

## Details
In KeePassXC I added some nice black icons for many (but not all) groups:

![image](https://user-images.githubusercontent.com/8037790/73690215-2704f680-46d0-11ea-8978-fed14b0fa0ac.png)

It would be cool when KeePassXC delivers in addition to the default icons a set of black icons.
The Icons I am using are downloaded from: http://www.iconarchive.com/show/windows-8-icons-by-icons8.html
These icons are **Linkware** (means you have to publish a link to http://icons8.com )

If this idea is interesting for you then I will
- search for some icons that are interesting for KeePassXC
- post here the icons and the URL to the icon

Such dark icons would look excellent in the new light theme and would fit perfectly to the new toolbar icons (also black icons).
But I know that for the dark theme some light icons are needed (here I have to search for light icons).

**Comment by phoerious** [comment]
We don't want monochrome icons for entries and groups, since it creates too much uniformity. However, we do have as selection of new coloured icons by Icons8 that we plan on replacing the old selection of icons with.

**Comment by OLLI-S** [comment]
@phoerious Can you please post a screen shot of these new icons or send them by Matrix?

What is bad about uniformity (other password managers have uniform group icons).
And it is still the users choice what icons he wants to use (my suggestion is to keep the current icons and add the new icons behind the existing icons):

![image](https://user-images.githubusercontent.com/8037790/73692828-62ee8a80-46d5-11ea-9d78-9659a6be0618.png)

**Comment by phoerious** [comment]
We do not have a definitive selection yet, but a few candidate that go well together with the material icons.
These grossly hideous Nuvola icons we have right now are definitely getting the sack.

**Comment by OLLI-S** [comment]
So you don't like the idea that you also deliver some black icons in addition to the existing ones?

**Comment by phoerious** [comment]
No, there are already too many standard icons.

**Comment by OLLI-S** [comment]
OK

**Comment by droidmonkey** [comment]
The problem with the standard icons is that they are hard numbered in the kdbx file. Adding more to the end will result in KeePass or Keepass2android not displaying the right icon (perhaps just the blue folder).

**Comment by OLLI-S** [comment]
OK, thank you @droidmonkey for explaining me this.
So this is a "bad design" in KeePass.

**Comment by wolframroesler** [comment]
@OLLI-S you'll want to have a look at #4071 concerning the ongoing re-design of the database icons. Your feedback is welcome.
