### ISSUE TITLE
Crashes when saving 

### ISSUE THREAD

**Issue by alfwro13** [keepassxreboot/keepassxc#4289]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Expected Behavior
Database should be saved when new entry is added.
I would like to add that I have autosave and browser integration enabled.

## Current Behavior
The whole KeePassXC window is greyed out - Asterix next to database name indicates that it hasn't been saved. Unable to save, close or exit application. Only way is to use taksmanager to kill it and start it again.
When that happens the app is still usable, i.e. I am able to search.

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1. Start KeepassXC
2. In Firefox (or any other supported browser) go to a website and enter logon details - when prompted by KeePass plugin click add new entry to database
3. App crashes

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )

## Debug Info
KeePassXC - Version 2.5.3
Revision: f8c962b

Qt 5.13.2
Debugging mode is disabled.

Operating system: Windows 10 (10.0)
CPU architecture: x86_64
Kernel: winnt 10.0.18363

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.5

**Comment by droidmonkey** [comment]
How long does it take to decrypt your database when you open it the first time? How long have you waited for the dialog to come back to life? Where are you storing your database (network share, cloud storage, etc)?

**Comment by alfwro13** [comment]
It takes 2-3 seconds to decrypt the db on first open.
The dialog never recovers - it has to be killed via task manager
The database is stored locally

**Comment by JulianVolodia** [comment]
HI @alfwro13 , you mentioned 'Crashes when saving' but in reproduce steps described only creating new entry from examplary browser Firefox. Could you elaborate if there is sth specific in passwd, count of credentials saved for this particular website, what settings are on Firefox or what behaviour when all other plugins are disabled and sync is off?

**Comment by GonGmata** [comment]
have the same Bug. 
disabling Browser Integration helped. didn't need it, using Auto-type
