### ISSUE TITLE
Question strings displayed when using global auto-type key

### ISSUE THREAD

**Issue by WNickNick** [keepassxreboot/keepassxc#4292]
If you have an existing KeyPass database, and you need to change the strings associated with various questions, KeePassXC does not do this correctly. For example, if you change the questions title using the "Advanced" section of an open entry, when you go to actually use it on the chosen website, what you get are the original strings, not the new ones you just entered. This is because the changes entered by KeePassXC are ONLY in the "Advanced" section of the KeePass database, and do not propagate to the "Auto-Type" section of the Keypass database. The only current solution to this is to open the Keepass database in KeePass, copy the new strings in the "Advanced" section to the Auto-Type section. I suspect this bug is in all versions of KeePassXC. I am using 2.5.3. Thanks... Nick...

**Comment by droidmonkey** [comment]
I don't understand what you are trying to do. Please provide screenshots of the issue.

**Comment by WNickNick** [comment]
No Worries. My apologies. I simply did not not know how to use the
"autotype" page correctly. I started out by generating a one entry new
database, kept going back and forth between KeePass and KeePassXC until I
had everything working properly and finally understood the flow of editing
the autotype page in KeePassXC . Thanks for your patience, and keep up the
good work. Nick...😁

**Comment by droidmonkey** [comment]
Ok great, yes that page is a bit awkward
