### ISSUE TITLE
Cleanup option for icons

### ISSUE THREAD

**Issue by xf-** [keepassxreboot/keepassxc#4295]
[TIP]:  # ( Provide a general summary of the feature in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Summary
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
Clean up icons. It is nice to update all icons at once, but old unused icons are stored in DB. I found no way to clean them fast (e.g. button to remove unused - no relation OR select&delete all and re-download them)

## Desired Behavior
[NOTE]: # ( Tell us how the new feature should work, be specific )
Some easy way to clean the DB

## Possible Solution
[NOTE]: # ( Not required, but suggest ideas on how to implement the addition or change )
Option to clean icons without an relation

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
Smaller DB - less to sync

**Comment by droidmonkey** [comment]
See #2110
