### ISSUE TITLE
GUI Window Does Not Appear When Network Doesn't Have Internet

### ISSUE THREAD

**Issue by paulrrogers** [keepassxreboot/keepassxc#4297]
## Expected Behavior
Opening KeePassXC when Wifi router is disconnected from Internet will still open a GUI window

## Current Behavior
No windows appeared. Right-clicking dock icon then choosing "Show All Windows" read "No Windows"

## Steps to Reproduce
1. Disconnect router from Internet so computer has Wifi connection, but no Internet
2. Open KeePass GUI from dock or Applications folder
3. Verify KeePass icon is in dock yet there are no windows

## Context
Cannot use KeePass GUI application until Internet is restored

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.5.3
Revision: 123B

Libraries:
- LIBS

Operating system: MacOS 10.15.3
CPU architecture: Intel
Kernel: Darwin 19.3.0

Enabled extensions:
- EXTENSIONS

**Comment by JulianVolodia** [comment]
hi @paulrrogers if someone provide me some debug output I will try my best to resolve this looking at code. Cheers

**Comment by droidmonkey** [comment]
Cannot replicate this at all.
