### ISSUE TITLE
Keyboard shortcuts for "search" with a different keyboard layout (eg. dvorak, bepo)

### ISSUE THREAD

**Issue by 0lie** [keepassxreboot/keepassxc#4300]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Expected Behavior
[NOTE]: #  CTRL+F should always use the same F key to call for Search Focus.

## Current Behavior
[NOTE]: # Sometimes the letter F is the QWERTY F Key as in all applications and browsers but sometimes KeepassXC does not respond to the F Key and I need to use my Dvorak/BEPO keyboard  F key (i.e. the "?/" Key) instead. 
After that initial activation, both "F Keys" work fine.
****
This issue is similar with other shortcuts. 
It is actually worse because only my modified Dvorak/Bepo keys are recognized as the actual letter for the shortcuts (for example CTRL + Shift + M ; M should be the QWERTY "M" not my modified keyboard M as in the vast majority of other application shortcuts.

## Possible Solution
[NOTE]: # Allow a personalized shortcuts configuration option or fix the mapping keys issues.

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1.
2.
3.

## Context
[NOTE]: # From a programming point of view, Keepass XC does actually work fine by using the modified keys.
The issue is that Keepass XC does not behave as every other software or apps usually do.
Shortcuts should be universal like the CTRL+F option (that's why my modified keyboard allows to still use the QWERTY "F" key to call for CTRL+F.

## Debug Info
[NOTE]: # 
KeePassXC - Version 2.5.3
Revision: f8c962b

Qt 5.13.2
Debugging mode is disabled.

Operating system: Windows 8.1 (6.3)
CPU architecture: x86_64
Kernel: winnt 6.3.9600

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.5

**Comment by droidmonkey** [comment]
This is a Qt bug, not us
