### ISSUE TITLE
Window interface lockout

### ISSUE THREAD

**Issue by rredford** [keepassxreboot/keepassxc#4301]
This is increase of security on access when computer is open and keepassxc database is open. This adds ability to lock logins browsing but leaves it still accessible via various services like browser login extension. The goal is to prevent casual browsing of all logins and passwords at once.

## Desired Behavior
Add "Lock database browser" or such to gui. It closes list of logins and shows ui for logging into database again. On back end it is still accessable so you can still log in various browsers but cannot just directly browse list of logins and discover new sites person can login and take advantage of, such as banking website logins. Additional features would be timed GUI lock, so it can secure itself in say 10 minutes, with options of course. 

## Possible Solution
[NOTE]: # ( Not required, but suggest ideas on how to implement the addition or change )

## Context
Suppose I have to leave my computer short time in order to restroom, it would be inconvenient for me to secure everything. Physical access means person may be able to figure out the login at my computer and since keepassxc is still open that person can simply browse though all logins at once. Having to find browse urls is harder. In other words, more layers of security.

**Comment by droidmonkey** [comment]
We have decided in the past that we will not support a "half open" state. It does not increase security because your database would still be fully decrypted in memory and your passwords accessible via the browser. In your scenario the person would simply visit Google or similar site, fill credentials, then write them down. Sorry, this will not be implemented.

**Comment by droidmonkey** [comment]
Also see #1809
