### ISSUE TITLE
'Save database copy...' option on 'Database' menu

### ISSUE THREAD

**Issue by RustyD** [keepassxreboot/keepassxc#4302]
This is a feature request for a new option on the 'Database' menu called 'Save database copy...'

This would work in the same way as the 'Save a Copy' option on the 'File' menu within LibreOffice Calc. In other words, it can be used to create an alternate copy of your database without renaming the current 'in memory' copy of the database.

This is useful for manually creating backup copies of my database in an alternate location (to hopefully avoid catastrophic loss of data should a disk fail). My KeyPassXC database is continually growing as a secure repository of knowledge for more and more of my digital life.

I could use the 'Save database as..' option on the 'Database' menu, but then I have to remember to manually close down that database and re-open my original database, otherwise any edits I make will be to the copy/backup database. This is not an academic possibility - a couple of years ago I made the mistake of continuing to edit the 'backup' database and ended up losing edits before realizing my mistake.

Additionally, remembering the last 'Save database copy...' directory within the actually database (to hopefully avoid excessive directory navigation) would be a bonus.

**Comment by droidmonkey** [comment]
Good idea!
