### ISSUE TITLE
[CLI] `create` does not honor --no-password

### ISSUE THREAD

**Issue by Crote** [keepassxreboot/keepassxc#4307]
## Expected Behavior
When I run `keepassxc-cli create --no-password --key-file somekey newdb.kdbx`, the CLI should create a database without a password. This behaviour would be similar to that of all other cli commands and is heavily implied by the manpage

## Current Behavior
The command returns `Unknown option 'no-password'`

## Possible Solution
A current workaround is to use `echo '' | keepassxc-cli create --key-file somekey newdb.kdbx` instead, but this is very cumbersome.

It seems to be fixable by wrapping the https://github.com/keepassxreboot/keepassxc/blob/develop/src/cli/Create.cpp#L100 part in a `if (!parser->isSet(Command::NoPasswordOption))` block and adding that flag to the options parser.

## Context
Current behaviour is inconsistent with other commands and contradicts the manpage.

**Comment by louib** [comment]
I think the `no-password` option is used when unlocking the database, whereas here it would be used to set (or not) the password. What about an option `--no-set-password`?

**Comment by Crote** [comment]
The `--key-file` option is also used both for setting and unlocking, so there is already a precedence.

The phrasing `--no-set-password` is a bit weird for `create`: what else would you do with a password  besides setting it?

I don't really have any opinion regarding a future `db-edit` command, as long as the flags are somewhat consistent and well-documented.

**Comment by JulianVolodia** [comment]
`--no-password` is put in General options in the man pages, so should work imho.

**Comment by JulianVolodia** [comment]
Adding `Command::NoPasswordOption` in `src/cli/Create.cpp` to cover execution of:
```
100     auto password = Utils::getPasswordFromStdin();
```
in the if clause?

**Comment by louib** [comment]
@Crote thanks for pointing out the `--key-file`, I also think it's a mistake. I think we should be using different option names for the creation options and the opening options.

**Comment by JulianVolodia** [comment]
@louib why not to used meta options like -k -no-password instead of having flustrating differences and long manpage?

**Comment by louib** [comment]
@JulianVolodia we would still have to document in the manpage what the options are used for in different contexts (creation and opening), so we'll have to add stuff to the manpage anyway. I'd rather have argument with names that are explicit about what they do, than re-use arguments from other commands to implement a completely different functionality.

**Comment by JulianVolodia** [comment]
Documented manpage is excuse. But, you are in Team - you decide.

In free time check out some cli tools out there and how you like using one which have parameters context dependant. As we all type `keepass-cli create` and then `--no-password` that is self-explaining that we want to create with setting no password (and begging keepass-cli to not ask for that to avoid the hacks like piping "\n" by `echo '' |` prefix.

I accept your decision - it is your issue, but I want that you see other point and still say that yours is better.
