### ISSUE TITLE
Snap Ugly GTK default theme (raleigh)

### ISSUE THREAD

**Issue by gitarra** [keepassxreboot/keepassxc#431]
I installed keepassxc from the snap on Xubuntu 16.04 and the application looks ugly.

It is using the default gtk theme which probably isnt supposed to happen?

Screenshots:

![screenshot_1](https://cloud.githubusercontent.com/assets/4739888/24270762/255384a4-101f-11e7-9167-ab2489abe3ac.png)
![screenshot2](https://cloud.githubusercontent.com/assets/4739888/24270769/28edab08-101f-11e7-9dbd-b898e22f2e2d.png)

**Comment by gitarra** [comment]
I am also wondering why it uses an old beta version of libgcrypt?

**Comment by gitarra** [comment]
Looks like it doesnt register a mime type either so that database files would be registered for the application and show a nice icon etc

**Comment by droidmonkey** [comment]
Noted. Snaps have been a journey... The packages that build the program are all from ubuntu 16.10 i presume. Not sure why there is a beta gcrypt, never noticed that!

**Comment by schiorean** [comment]
Snap package doesn't display the keepassxc tray icon to me (Ubuntu 16.04.02). I gave up on snap and use appimage which looks ok until now. You may try appimage instead, although I'm not sure if appimage has to be updated manually when a new version is released.

**Comment by schiorean** [comment]
if libgcrypt 1.7.2 is old then mine is even older? 

> Using:
> - Qt 5.8.0
> - libgcrypt 1.6.1

**Comment by phoerious** [comment]
Can you try unsetting `$XDG_DATA_DIRS` in the terminal and then run the KeePassXC snap from there?
```
unset XDG_DATA_DIRS
```

**Comment by gitarra** [comment]
Tried unsetting XDG_DATA_DIRS, nothing changed, that is if I did it correctly.

So here is a list of issues I see, not sure I should make a new issue for each of them?

1. No tray icon
2. Application does not register a MIME type for the database files (.kdbx), so my file manager does not know what to do with them and does not show an icon for the files.
3. Uses default GTK theme, probably too 90's for most users.
4. Uses an old beta version of libgcrypt. Security implications?

I'm not sure if the new fancy welcome page is supposed to be there yet, if it is thats another thing thats missing.

**Comment by phoerious** [comment]
At least on Ubuntu the Snap should use the system theme.

**Comment by gitarra** [comment]
I installed the Snap on Ubuntu (not Xubuntu) 17.04 and it uses the system theme like it should.

**Comment by droidmonkey** [comment]
This is a snapcraft issue and there it nothing we can do about it right now.

**Comment by gitarra** [comment]
@droidmonkey Thanks. Do you have a link to a snapcraft bug report of this?

**Comment by droidmonkey** [comment]
No I don't. My understanding of snaps at this time is that they are only officially supported in Ubuntu 16.10 (that means with Gnome)

**Comment by StefanB08** [comment]
I think this is the bug report you are looking for https://bugs.launchpad.net/ubuntu/+source/snapd/+bug/1585332

**Comment by gitarra** [comment]
@droidmonkey Ubuntu 14.04 and flavours are supported:

https://snapcraft.io/docs/core/install-ubuntu

@StefanB08 Thanks for the link!

**Comment by droidmonkey** [comment]
Yah my bad, i need to keep up with the times. Funny thing though is that when you publish a snap to the store you can only target 16.10

**Comment by corehack** [comment]
I'm confused, this is Qt app right ? What does it have to do with gtk themes ? Does it mean that the theme engine is getting confused and provides a gtk-compatible fallback theme (what happens if you run a Qt app in a Gtk environment such as Gnome) ? Note, I'm using Kubuntu, native Qt environment, so it should just skip the gtk stuff altogether.

**Comment by kroka** [comment]
Maybe you should mention on the download page that the official Snap package might not be able to use the system's theme.

Some weeks ago I've already tried the snap package and uninstalled KeepassXC immediately after it was that ugly. Only today I've learned that this behavior is caused by Snap (https://github.com/keepassxreboot/keepassxc/issues/949#issuecomment-329535675)

With the _unofficial_ Debian package KeepassXC looks as good as it should.

--
KDE neon User Edition 5.10
based on Ubuntu 16.04
