### ISSUE TITLE
Extension now working in Wayland 

### ISSUE THREAD

**Issue by xzj8b3** [keepassxreboot/keepassxc#4310]
After a re-installation of Fedora 31 and with ext4 filesystem, the window lock problem no longer seems to occur on Wayland. 

Or in case some improvements were made with the latest release of KepassXC-Browser thank you very much given it now seems to be working 

If you could also solve the problem with Torbrowser-laucher you would be great given the convenience of this extension!!!!

Is it possible to import a CSV that keeps itself updated without importing empty folders from previous groups???

so he doesn't find himself in a situation like the one in the picture?

![Schermata da 2020-02-10 19-40-23](https://user-images.githubusercontent.com/26720956/74179512-e6f8c300-4c3d-11ea-9ccc-e0bd0055fa83.png)

**Comment by trashcan55** [comment]
> If you could also solve the problem with Torbrowser-laucher you would be great given the convenience of this extension!!!!

You should be aware that additional browser extensions might add up to your browser fingerprint and thereby deanonymize the tor browser. also, untested extensions might break functionalities. it is [strongly discouraged by the tor project](https://tb-manual.torproject.org/plugins/)

**Comment by xzj8b3** [comment]
> > Se anche tu potessi risolvere il problema con Torbrowser-laucher, sarebbe fantastico vista la comodità di questa estensione !!!!
> 
> È necessario essere consapevoli del fatto che ulteriori estensioni del browser potrebbero aggiungere l'impronta digitale del browser e quindi rendere il browser anonimo. inoltre, le estensioni non testate potrebbero compromettere le funzionalità. è [fortemente scoraggiato dal progetto tor](https://tb-manual.torproject.org/plugins/)

Thanks, I didn't know that.

However, it would be equally convenient to be able to use KeepassXC-Browser .... for the greater use Tor Browser only for sites hosted on the Onion network that are generally sites on Linux, science, news or other .... pertato in that case anononimato little matter to me in reality.

But I will take this into account and I will avoid installing other extensions other than KeepassXC !!!
