### ISSUE TITLE
Mac OS TouchID Quick Unlock

### ISSUE THREAD

**Issue by s-ahuja** [keepassxreboot/keepassxc#4318]
Quick Unlock Touch ID doesnt work on my latest install of keepassxc v2.5.3. 
On the "Unlock KeepassXC Database" screen, I type in the password and have the "TouchID for Quick Unlock" option checked. However, each time i have to put in the password.

## Expected Behavior
Expect that once the password is provided ; the TouchID option should unlock the database.

## Current Behavior
Each time I have to type in password

## Debug Info
KeePassXC - Version 2.5.3
Revision: f8c962b

Qt 5.14.0
Debugging mode is disabled.

Operating system: macOS 10.15
CPU architecture: x86_64
Kernel: darwin 19.3.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
 libgcrypt 1.8.5

**Comment by s-ahuja** [comment]
Read from one of othet github issues: "I needed to leave the password field blank, and press the enter key"

**Comment by kesselborn** [comment]
thanks ... this wasn't apparent for me either
