### ISSUE TITLE
Update auf neue Version - Hardwareschlüssel wird gefordert

### ISSUE THREAD

**Issue by xxljerry** [keepassxreboot/keepassxc#4319]
Hallo, habe auf die neue Version ein Update gemacht, und meine Datemnbank lässt sich nicht öffnen, und dort wo man einen Hardwareschlüssel eingeben kann, läuft wie ein kleines Fließband. Ich habe alles deinstalliert, und die neue version installiert, und das gleiche problem wieder.

**Comment by droidmonkey** [comment]
Duplicate of #4260
