### ISSUE TITLE
Security audit payed by crowdfunding?

### ISSUE THREAD

**Issue by paolostivanin** [keepassxreboot/keepassxc#432]
I was thinking that after release 2.2.0 (which will bring a lot of new stuffs) it would be nice to have a security audit being made by  a third party. Of course this requires money but I think the amount could be easily found by setting up a crowdfunding campaign.

What do you think?

**Comment by phoerious** [comment]
If we actually manage to raise enough money, I'm all for it. We have thousands of users already, but I don't know how many of them are actually willing to contribute financially. Our fundraising campaign for the Authenticode certificate went rather slowly.

**Comment by paolostivanin** [comment]
@phoerious I think it's worth a shot. Worst case nothing happens :) 
Maybe this time we can try to involve more users to share the link to all the social networks! 
We can also try also by posting on reddit, hackernews, by contacting major website like omgubuntu, etc.

**Comment by weslly** [comment]
While I would love to see that happen, it probably would be a wasted effort right now since a serious security audit costs a lot of money (we are talking about thousands) and I don't think KeepassXC is nearly popular enough to raise that much money.

Even the original Keepass app which has been around since 2003 and probably have hundreds of thousands of users, only got their [1st security audit last year](https://www.ghacks.net/2016/07/22/keepass-password-manager-icode-audit/).

**Comment by paolostivanin** [comment]
```
> cloc keepassxc/src 
     328 text files.
     328 unique files.                                          
       3 files ignored.

github.com/AlDanial/cloc v 1.72  T=1.64 s (198.6 files/s, 47562.5 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
C/C++ Header                   156           1876           3209          31453
C++                            129           4924           3089          24119
Qt                              24              0              0           5512
C                                1            401            218           1851
CMake                           11             58             47            394
Markdown                         2            133              0            342
Python                           1             18             28             61
Objective C++                    1             17             31             54
-------------------------------------------------------------------------------
SUM:                           325           7427           6622          63786
-------------------------------------------------------------------------------
```

I am no security code experts but I have read online that an estimate could be:
1 kLOC/hour
150 USD/h

64 (KLOC) * 150 (USD) = 9600 USD. Sounds reasonable :)

**Comment by phoerious** [comment]
The thing is, before we do anything for a security audit, we need to increase our test coverage.

**Comment by TheZ3ro** [comment]
And maybe have a stable version

**Comment by bannmann** [comment]
How about applying to [Mozilla's Secure Open Source program](https://www.mozilla.org/en-US/moss/secure-open-source/)? Surely, a password manager is "vital to the continued functioning of the Internet or the Web".

**Comment by TheZ3ro** [comment]
@bannmann read the faq about that https://keepassxc.org/docs#faq-audit

**Comment by bannmann** [comment]
@TheZ3ro Well, I see nothing in that FAQ entry that indicates why KeepassXC should not apply to that program.

The entry says that the project has no money, but Mozilla SOS is a grant program. In fact, it even says "Maybe you can beg OSTIF or OTF for funding a KeePassXC audit", and I merely suggested someone else to "beg" (though I don't find that term appropriate).

Then, the FAQ entry says audits don't really "prove" security, which I totally agree with, but that fact has no effect on whether to apply to a program that awards free audits.

OTOH, @phoerious and you, @TheZ3ro, suggested that before having an audit, the project should increase test coverage and have a stable version. This is a valid argument (albeit not made by the FAQ entry), but to me, it's not very convincing. It sounds a bit like "let's wait for the software to be finished", but software never is. This software is published, it has a nice website and real users, so why wait?

**Comment by phoerious** [comment]
There is quite a bit of technical legacy we inherited from KeePassX, which I know will potentially be brought up by auditors. I'm not saying we have security issues, but our code base is just relatively old and new paradigms for better, more stable and safe  software have evolved since. It's not much use to pay for an audit (or let someone else pay fwiw) while there are still quite a lot of things we already know need improving. We are actively working on ironing these things out, but it takes time. I agree that software is never finished, but right now we are still at a point where I'm hesitant to spend money on an audit.

**Comment by bannmann** [comment]
@phoerious sounds reasonable. I suggest adding that reasoning to the FAQ entry, replacing the "maybe you can beg" line.

**Comment by TheZ3ro** [comment]
Yeah, I have pasted the FAQ link without explaining my PoV.
Essentially what I wanted to say was:
We can beg and apply to Mozilla SOS (as well as OSTIF and OTF), but keep in mind that an audit is not a 100% proof that the software is safe and secure and the audit only cover a single "snapshot" of it.

Only the last week alone we merged 9 PR, since 2.2.4 in `develop` we had almost 400 new commit.
The project is pretty active and an audit for 2.2.4 version will be totally useless once 2.3.0 will be released.

Personally I would wait to merge some major feature, add code documentation, deprecate KeePassHTTP (that is basically flawed) and some other thing before an audit.
Otherwise you/we/they will spend money for something pretty "useless"

**Comment by ArchangeGabriel** [comment]
I definitively agree with the idea that the current code base being inherited from a former project that had some time to rot before being forked, an audit should at least wait for the codebase to be /internally/ audited first. Also, while software development never ends, you might at least want to reach state-of-the-art in your project before making an audit. And I think that they are more security implications in the KeePassHTTP replacement and the switch to KDBX4 than in what might come next (excepted maybe DBus).

**Comment by grenzor** [comment]
Wouldn't it be a good idea to start the initiative of an audit now and accept donations specially for it? 

I agree it's best for the audited version of the program to be the one which includes the most important new security features, removes most of the legacy technology and fixes the already known issues but it's not like the money is on hand that once that version is stable and released that an audit can immediately be paid for. I'm sure donations will be coming in slowly and starting now will be good to give some time to build up for the money needed for an audit.

**Comment by droidmonkey** [comment]
My personal feelings on the matter: a security audit makes 1-2 people really rich for very little gain to the project.

We are open source, anyone can perform an audit on select parts of the codebase at any time. In fact, we audit our own code more often then not. Our biggest attack surface is by far the Qt platform itself, especially in how it handles memory.

I would much rather spend the money on quality static code analysis tools and cloud based scanning services that would serve us now and in the future. I am already incorporating some of those tools as I find them and test them out.

**Comment by bannmann** [comment]
@droidmonkey Be sure to include https://about.sonarcloud.io/ in your list of tools. It's free for FOSS projects. Not spending any money on static code analyzers would be the best option.

**Comment by droidmonkey** [comment]
The enpass and bitwarden reviews are a joke. They aren't even code reviews! Being part of FOSSA would be awesome and I think FOSSA 2 was a huge miss since they included such ancient software like Notepad++.

**Comment by OLLI-S** [comment]
I am currently writing an email to Julia Reda (jreda@cyber.harvard.edu).

Here I write, that **I am a user** (not a project member) of KeePassXC and that I switched form KeePass to KeePassXC. 
I also write that KeePassXC has some advantages in comparison to KeePass.
And I ask her to support your project.

I have not sent the mail yet.

**Comment by JulianVolodia** [comment]
@OLLI-S have you asked about it? Maybe better contact with FOSSA 2 project here: digit-oss-strategy@ec.europa.eu
ref: https://ec.europa.eu/info/departments/informatics/eu-fossa-2_en

As Julia mentioned here https://juliareda.eu/2019/07/fossa-cybersecurity/ :

> Now that my mandate in the European Parliament has come to an end, there is one important project that will still go on until the fall of this year: The European Free and Open Source Software Audit project – FOSSA for short – that was initialised in 2014, is coming to an end. After running for 2 years as a “pilot project”, and for 3 more years as a “preparatory action”, the next step to follow-up on the project is to establish its actions in European law.

As I read on Julia's blog the outcome of 2 iteration of FOSSA the outcome was:

> 
> Outreach: FOSSA hackathons
> 
> One of the main outcomes of the first FOSSA year was the idea that audits alone aren’t sufficient to increase security. Instead, we must approach security already in software development. To that end, we want to invite projects to Brussels to spend time together to work on security-relevant issues in their software, and to learn more about secure software development.
ref: https://juliareda.eu/fossa/

...so they come to idea like @droidmonkey mentioned indeed here before. Creating secure software always will be more important than auditing it 'once upon a time'.

**Comment by OLLI-S** [comment]
I think a security audit of 2.6 would be very important.
A real audit, not a code inspection with any tool.

So we should all donate for this feature at bountysource:
https://www.bountysource.com/issues/43394289-security-audit-payed-by-crowdfunding

If bountysource is the official way to donate, then count me in with 50 Euro!

**Comment by OLLI-S** [comment]
@JulianVolodia I contacted Julia at jreda@cyber.harvard.edu but have not yet received any reply.
But I will send my mail again to digit-oss-strategy@ec.europa.eu

**Comment by droidmonkey** [comment]
Please don't donate to this issue

**Comment by OLLI-S** [comment]
@droidmonkey OK, but how can we collect money for the code audit?

**Comment by droidmonkey** [comment]
If the intent is to pay for a **full audit** that would likely cost upwards of $10,000 
- $50,000. I don't know any security professionals who would spend up to 6 months reviewing every code path in our code base for less than that.

**Comment by OLLI-S** [comment]
@droidmonkey Sorry, I am not a security specialist, so my word **full** was not correctly.
As far as I know there are several levels of a security audit:
1. Tools like Checkmarx that automatically check the code and tell you possible vulnerabilities
2. A security audit done by security specialists (they take several days, not 6 months)
3. A full code review (taking 6 months)

Maybe there are more levels existing, but I concentrate on these 3.

You are absolutely right, that **3)** makes no sense (costs too much time and too much money).
I had **2)** in my mind, where a security company makes a security audit of KeePassXC (that takes several days).
So sorry for the confusion.

Of cause I am willing to donate for **2)** to increase the security of KeePassXC.

**Comment by droidmonkey** [comment]
Hopefully an educational center with grant money could perform this work. This would make for a great thesis (eg, evaluating the security of open source password managers).

**Comment by OLLI-S** [comment]
I am still willing to donate some money (my personal money) for a security audit done by security specialists.
Waiting for a huge sponsor will take too long in my eyes.
