### ISSUE TITLE
KeepassXC support for XML import and export

### ISSUE THREAD

**Issue by RetiredTechie** [keepassxreboot/keepassxc#4320]
[TIP]:  # ( Provide a general summary of the feature in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Summary
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
Keepass 2.44 for windows supports exports and imports XML file format type databases.
Will or does KeepassXC for Linux support this feature?

## Desired Behavior
[NOTE]: # ( Tell us how the new feature should work, be specific )

## Possible Solution
[NOTE]: # ( Not required, but suggest ideas on how to implement the addition or change )

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )

**Comment by phoerious** [comment]
You can use the CLI to export the raw XML. Keep in mind that the raw XML format is entirely unprotected.
