### ISSUE TITLE
Database cannot be opened on MacOS Catalina

### ISSUE THREAD

**Issue by fsnilsberg** [keepassxreboot/keepassxc#4322]
## Expected Behavior
When opening the application and opening the database i expect the database to be opened when I enter my password

## Current Behavior
When opening the application and trying to open a database, upon entering the correct password the application gives an error message. "Unable to open file <FILENAME>"

## Possible Solution
The problem can be bypassed by opening the application as administrator `sudo /Applications/KeePassXC.app/Contents/MacOS/KeePassXC`
I suspect the problem is related to changes in read / write permissions introduced in MacOS Catalina. I tried to whitelist KeePassXC in the "Security and Privacy" settings of the OS, but that did not help. Could it be because the application is build in QT? I've seen similar problems with application build on Ruby where one had to give read permissions to the runtime "/user/bin/ruby"

## Steps to Reproduce
1. Open KeePassXC on MacOS Cataline
2. Open database
3. Choose database from filesystem
4. Enter password
5. Error message occurs

## Debug Info
KeePassXC - Version 2.5.3
Revision: f8c962b

Qt 5.14.0
Debugging mode is disabled.

Operating system: macOS 10.15
CPU architecture: x86_64
Kernel: darwin 19.3.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
 libgcrypt 1.8.5

**Comment by droidmonkey** [comment]
Where you have stored your database seems to not be accessible by your user account. Do not run the application as administrator, fix the permissions where your database is stored.
