### ISSUE TITLE
can not open database from ZFS filesystem

### ISSUE THREAD

**Issue by dyadMisha** [keepassxreboot/keepassxc#4324]
## Summary
can not open database from ZFS filesystem.
I push "open existing database" button, dialog opens and shows me all directories except ZFS mountpoints and even symlinks to ZFS mountpoints.

if I click on bookmarks to ZFS directories at the left pane of open dialog, it shows me content of "/"

there were no such problems in versions 2.4.x 

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1. put database on ZFS 
2. try to open it in 2.5.3

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )
nothing else changed in OS, just removed 2.4.x with apt and installed 2.5.3 with snap.

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.5.3
Revision: f8c962b
Qt 5.9.5

Operating system: Ubuntu 19.10
CPU architecture: x86_64
Kernel: 5.3.0-28-generic

**Comment by dyadMisha** [comment]
KeePassXC - Version 2.4.3 Revision: 5d6ef0c which works fine uses Qt 5.12.4, btw

**Comment by dyadMisha** [comment]
KeePassXC - Version 2.5.3 Revision: f8c962b from PPA repo uses Qt 5.12.4 and works as expected with ZFS

**Comment by droidmonkey** [comment]
This is due to snap sandboxing. Please read our FAQ: https://keepassxc.org/docs/#faq-appsnap-homedir
