### ISSUE TITLE
Snap page is missing verification checkmark

### ISSUE THREAD

**Issue by helght** [keepassxreboot/keepassxc#4325]
Snap page is currently missing verification checkmark. 

Snap store is not moderated and anyone can upload anything I believe.
Since keepass is a security-critical software it might be useful to get a checkmark to indicate that the download is "official" and comes from developers, not elsewhere. 

If the validation process is not hard or expensive, it should be done.

**Comment by droidmonkey** [comment]
Ubuntu has stated they are not giving check marks out to small developers. Also, there is no process to apply for one.
