### ISSUE TITLE
Search help window only displayed for < 1 second

### ISSUE THREAD

**Issue by rugk** [keepassxreboot/keepassxc#4327]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

The help/window for the search help cannot be displayed.

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1. Ctrl+F.
2. Click on the green help icon in the search box.

## Current Behavior
[NOTE]: # ( Tell us what actually happens )

For 0-1 seconds a window flashes up and is immediately closed again.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

It should show the window?

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )

This is possibly a bug related to Wayland, see https://github.com/keepassxreboot/keepassxc/issues/2973

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )

I am using KeePassXC from Flathub with Wayland.
Fedora 31

## Debug Info
KeePassXC - Version 2.5.2
Revision: 62cda9d
Distribution: Flatpak

Qt 5.13.2
Diagnosemodus ist deaktiviert.

Betriebssystem: Linux 5.4.18-200.fc31.x86_64
CPU-Architektur: x86_64
Kernel: linux 5.4.18-200.fc31.x86_64

Aktivierte Erweiterungen:
- Auto-Type
- Browser-Integration
- SSH-Agent
- KeeShare (bestätigtes und unbestätigtes Teilen)
- YubiKey

Kryptographische Bibliotheken:
 libgcrypt 1.8.5

**Comment by droidmonkey** [comment]
This is fixed already in an open PR.
