### ISSUE TITLE
Add support for browsers installed as snaps

### ISSUE THREAD

**Issue by colans** [keepassxreboot/keepassxc#4328]
I've found many closed issues in the queue about snap-installed browsers not being supported, but couldn't find any open ones about adding support for these.  If I missed it, please link to it from here, and we can close this.

Otherwise:
* Would it even be possible to do this,
* is it considered an out-of-scope Won't Fix,
* or is it that nobody's had a chance to work on this yet?

**Comment by varjolintu** [comment]
This cannot be solved until snap allows Native Messaging to connect outside the sandbox.

See: https://bugs.launchpad.net/ubuntu/+source/chromium-browser/+bug/1741074

**Comment by colans** [comment]
Roger that.  Is there a Postponed label we can add here?

**Comment by colans** [comment]
@varjolintu Looks like the upstream issue is still open so how can this be closed?

**Comment by varjolintu** [comment]
@colans Snap Firefox is already working with KeePassXC. AFAIK the support is coming to Chromium too. After all, this is not a KeePassXC issue.
