### ISSUE TITLE
Just saying thanks at ILoveFS day 2020

### ISSUE THREAD

**Issue by rugk** [keepassxreboot/keepassxc#4329]
Hi,
it's [ILoveFs](https://fsfe.org/campaigns/ilovefs/) day again. So I take this chance to thank you for KeePassXC. 

It's a big project and a big inheritance, and after [many](https://www.keepassx.org/), many forks, you finally got a very good, fancy new password manager and many, many new features.

I have used it for many years now, and can certainly say KeePassXC is stable and a good piece of software that just works. :+1: And of course it's one of the most essential pieces of software, I use regularly. :smile:

And as I see, [other new features](https://github.com/keepassxreboot/keepassxc/issues/1083) are coming up, so I am keen on the future of KeePassXC.

So keep up the great work and thanks for the software. :smiley:

**Comment by nixpc** [comment]
KeePassXC is the first and only password manager I've ever used. I have trust issues when it comes to cloud password managers mainly due to security concerns.

So thanks to KeePassXC for making my life a lot easier!

**Comment by tomhundt** [comment]
W00t! 

I never heard of ILoveFS day before, but have put it on my calendar ;-)

**Comment by phoerious** [comment]
I'm gonna close this here. Thanks for the appreciation. ❤️
