### ISSUE TITLE
Auto-type not working on macOS Catalina

### ISSUE THREAD

**Issue by pixel8383** [keepassxreboot/keepassxc#4330]
## Expected Behavior
[NOTE]: # Select one record and type CMD+SHIFT+V (or select the function with a right click on the item) and auto-type the setup elements (default user & password) to the application (i.e. on the browser)

## Current Behavior
[NOTE]: # Nothing is being pasted to the target app.

## Context
[NOTE]: # KeepassXC works fine with Windows 10 but it's failing on macOS Catalina. I suspect something on the operating system is stopping the app from working correctly (some security settings maybe?)

KeePassXC has screen reader and accessibility permissions enabled on macOS.

## Debug Info
[NOTE]: # 
KeePassXC - Versione 2.5.3
Revisione: f8c962b

Qt 5.14.0
La modalità di debug è disabilitata.

Sistema operativo: macOS 10.15
Architettura CPU: x86_64
Kernel: darwin 19.3.0

Estensioni abilitate:
- Completamento automatico
- Integrazione con i browser
- Agente SSH
- KeeShare (condivisione firmata e non firmata)
- YubiKey
- TouchID

Librerie crittografiche:
 libgcrypt 1.8.5

Operating system: macOS 10.15.3 (19D76)

**Comment by droidmonkey** [comment]
Remove KeePassXC from the permissions and add it again.

**Comment by pixel8383** [comment]
I already did it for screen reader. I cannot do the same for Accessibility since when I click on it the tick will not disappear (and it is not grayed out).

**Comment by droidmonkey** [comment]
Try this: https://gist.github.com/mcandre/697aa10dc9bf5ce0a638

**Comment by pixel8383** [comment]
Thank you, that did the trick.
