### ISSUE TITLE
Vim-like Navigation of Database

### ISSUE THREAD

**Issue by chuckn246** [keepassxreboot/keepassxc#4331]
[TIP]:  # ( Provide a general summary of the feature in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Summary
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
Add a setting to enable vim-like navigation while searching/browsing the database

## Desired Behavior
[NOTE]: # ( Tell us how the new feature should work, be specific )
`/` : Search database
`n` : Search forward
`N` : Search backward
`h`, `j`, `k`, `l` : Navigate the entry trees

Possibly:
`yu` : Yank username 
`yp` : Yank password
`yy` : Yank URL
`pp` : Open URL

..and so on

## Possible Solution
[NOTE]: # ( Not required, but suggest ideas on how to implement the addition or change )
I am not sure how this could be implemented. 

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
As a frequent user of i3wm, qutebrowser and cmus, (and other apps that offer vim-like navigation), it would be nice to use keepassxc without affecting workflow.

**Comment by droidmonkey** [comment]
This is not gonna happen
