### ISSUE TITLE
SSH Agent: Support OpenSSH 8.2 security key (FIDO/U2F) backed SSH keys

### ISSUE THREAD

**Issue by hifi** [keepassxreboot/keepassxc#4334]
OpenSSH 8.2 added support for U2F backed ECDSA and ED25519 keys.

https://www.openssh.com/txt/release-8.2

## Summary
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
Need to implement required changes to OpenSSHKey class to support reading/writing these new keys. They are documented within OpenSSH source and are trivial to support: https://github.com/openssh/openssh-portable/blob/master/PROTOCOL.u2f

Though unfortunately there's a fatal assumption in OpenSSHKey class that all key parts are "strings" in OpenSSH slang but the new keys contain uint8 flags which can't be represented in the current internal format.

## Possible Solution
[NOTE]: # ( Not required, but suggest ideas on how to implement the addition or change )
I'm working on it. With a small hack I can add security key backed SSH keys to ssh-agent from KeePassXC so it's not a big technical requirement on our end.

OpenSSHKey internal storage format needs to be changed to either include the type of each part of a key or store them as a complete blob. Problem is KeeShare depends on the internal format of OpenSSHKey so a blob might not fit here. Possibly RSA keys could have their own class instead of depending on OpenSSHKey which is neutral to the internal structure of a key.

WIP branch (depends on agent func tests), does not pass tests because we need a bigger refactor: https://github.com/hifi/keepassxc/tree/feature/sshagent-sk-keys

## Context
It's better to support them early on so people who upgrade to newer OpenSSH can start using KeePassXC with the keys immediately. Therre's not really any overhead on KeePassXC side.

**Comment by hifi** [comment]
Ubuntu 20.04 LTS is shipping with OpenSSH 8.2 so it's one of the first LTS distributions to pick it up.

**Comment by hifi** [comment]
It took a year but this now depends on #6209 to be merged as there were major integration issues with the changes that were needed. I have the work queued up in my personal branch that is on top of the Botan work and will be PR'd once it lands.

**Comment by typoon** [comment]
Will this change also support the key type `sk-ssh-ed25519@openssh.com`? If not, is it possible to add support to it or should I open a new request for that?

Thanks!

**Comment by hifi** [comment]
Yes both sk-ecdsa and sk-ed25519 will work.
