### ISSUE TITLE
Copying text from notes after openeing URL causes false unsaved changes

### ISSUE THREAD

**Issue by anthonybilinski** [keepassxreboot/keepassxc#4338]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
The "Apply" button is only active when there are changes, and the "Entry has unsaved changes" prompt is only presented when there are unsaved changes.

## Current Behavior
[NOTE]: # ( Tell us what actually happens )
keepassxc often thinks there are unsaved changes when there aren't, after interacting with the "Notes" section.

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1. Select an entry with a URL and notes, and press ctrl+shift+u to open the URL.
2. Return to keepassxc and double click the entry to open it.
3. Select some text in the notes section, and press ctrl+c to copy it.

Alternative repro, with possibly the same root cause:
1. Open an entry with notes, and place cursor inside the notes section.
2. alt+tab to change windows
3. alt+tab back to keepassxc

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )
This frequently causes a bit of concern making me wonder if I changed something and if it was intentional.

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.4.3
Revision: 5d6ef0c

Qt 5.12.4
Debugging mode is disabled.

Operating system: Ubuntu 19.10
CPU architecture: x86_64
Kernel: linux 5.3.0-29-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (only unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.4

**Comment by droidmonkey** [comment]
Could not replicate on Windows 10 using 2.5.3.

**Comment by anthonybilinski** [comment]
I can't reproduce this in version 2.5.3 with Qt 5.14.1 either. Maybe a Qt issue on my other system.

**Comment by anthonybilinski** [comment]
I'm seeing this again on 2.6.1 with Qt 5.14.2 on Ubuntu 20.10. I have 100% repro running under Wayland but can't repro under Xorg.

The steps seem to be:
* Hitting modifier keys with the notes area selected.
* Selecting another window.

In either order. As soon as the second step happens, the "Apply" button enables, and exciting after that point prompts for save.

Based on not being about to repro under Xorg, that might explain why it's not repro-able on Windows.

Under Wayland by default Qt is still running keepassxc as an X11 app, logging `Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.`, but even if I set  `QT_QPA_PLATFORM=wayland` I can still repro.

I'd send a video of the repro with `evtest` logging key presses, but screen recoridng's broken on Ubuntu 20.10 under Wayland :upside_down_face:

@droidmonkey could this be re-opened?

**Comment by droidmonkey** [comment]
We are on 2.6.4 now

**Comment by anthonybilinski** [comment]
Repro's on `af55d1b` now fwiw, but yeah that's fair enough, I guess it must be a Qt bug.

**Comment by droidmonkey** [comment]
Wayland or xwayland or qtwayland must be trigger a "text changed" event even when you are using modifier keys.

**Comment by anthonybilinski** [comment]
Right, `QTextDocument::contentsChanged` is being emitted when I just pressed and released Ctrl here.
```
Thread 1 "keepassxc" hit Breakpoint 1, EditWidget::setModified (this=0x55624408b530, state=true) at /home/abilinski/builds/keepassxc/src/gui/EditWidget.cpp:148                                                    
148         m_modified = state;                                                                                                                                                                                    
(gdb) bt                                                                                                                                                                                                           
#0  EditWidget::setModified(bool) (this=0x55624408b530, state=true) at /home/abilinski/builds/keepassxc/src/gui/EditWidget.cpp:148                                                                                 
#1  0x00007fd8f7aa8320 in doActivate<false>(QObject*, int, void**) (sender=0x5562440df9d0, signal_index=7, argv=0x7ffdf16ea8b0) at ../../include/QtCore/../../src/corelib/kernel/qobjectdefs_impl.h:395
#2  0x00007fd8f7aa8320 in doActivate<false>(QObject*, int, void**) (sender=0x5562440e3b10, signal_index=3, argv=0x7ffdf16ea990) at ../../include/QtCore/../../src/corelib/kernel/qobjectdefs_impl.h:395
#3  0x00007fd8f88250a3 in QWidgetTextControl::qt_metacall(QMetaObject::Call, int, void**) (this=0x5562440e3b10, _c=QMetaObject::InvokeMetaMethod, _id=0, _a=0x7ffdf16eaaa0)
    at .moc/moc_qwidgettextcontrol_p.cpp:489
#4  0x00007fd8f7aa8030 in doActivate<false>(QObject*, int, void**) (sender=0x5562440e60c0, signal_index=4, argv=0x7ffdf16eaaa0, argv@entry=0x0) at /usr/include/c++/10/bits/atomic_base.h:741
#5  0x00007fd8f7aa2068 in QMetaObject::activate(QObject*, QMetaObject const*, int, void**)
    (sender=<optimized out>, m=m@entry=0x7fd8f84b7820 <QTextDocument::staticMetaObject>, local_signal_index=local_signal_index@entry=1, argv=argv@entry=0x0) at kernel/qobject.cpp:3930
#6  0x00007fd8f83abc07 in QTextDocument::contentsChanged() (this=<optimized out>) at .moc/moc_qtextdocument.cpp:427
#7  0x00007fd8f807c724 in QTextDocumentPrivate::finishEdit() (this=0x5562440e69b0) at text/qtextdocument_p.cpp:1247
#8  0x00007fd8f807cb1c in QTextDocumentPrivate::endEditBlock() (this=<optimized out>) at text/qtextdocument_p.cpp:1203
#9  QTextDocumentPrivate::endEditBlock() (this=<optimized out>) at text/qtextdocument_p.cpp:1186
```
so not a keepassxc bug. Maybe this 7 year old Qt bug https://bugreports.qt.io/browse/QTBUG-36609.

**Comment by droidmonkey** [comment]
We could work around it by storing the contents to a buffer and comparing the "changes" to the buffer, but that is wasteful and annoying to be honest. We rely on these signals to perform to their documented specs. A new Qt bug should be opened or this specifically under your working environment.

**Comment by anthonybilinski** [comment]
Agreed, I don't think re-doing the work of checking for changes makes sense.

I've opened https://bugreports.qt.io/browse/QTBUG-91093, thanks for the support.
