### ISSUE TITLE
Trying to open a URL after searching inserts a 'u' into the search field

### ISSUE THREAD

**Issue by anthonybilinski** [keepassxreboot/keepassxc#4339]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
After searching, key combos should act on the highlighted search result, rather than have the modifiers stripped and keys input into the search term.

## Current Behavior
[NOTE]: # ( Tell us what actually happens )
After searching, key combos that are pressed insert new characters into the search field rather than acting on the selected search result.

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )
Bare keys should be added to the search term, but modified keys should act on the search result.

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1. Type in some search query until your desired entry is selected in the list of results.
2. Press ctrl+shift+u to open the URL of the selected query.

Workaround: click on the seemingly already selected search result, then press the same key combo.

## Debug Info
KeePassXC - Version 2.4.3
Revision: 5d6ef0c

Qt 5.12.4
Debugging mode is disabled.

Operating system: Ubuntu 19.10
CPU architecture: x86_64
Kernel: linux 5.3.0-29-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (only unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.4

**Comment by droidmonkey** [comment]
This is not a bug in 2.5.x because we fixed it already.
