### ISSUE TITLE
GUI Scaling problem

### ISSUE THREAD

**Issue by schiorean** [keepassxreboot/keepassxc#434]
The App GUI is scaled too large, almost the entire screen. My screen resolution is 1920x1080.

## Expected Behavior
Normale window size.

## Current Behavior
Huge window size.

## Steps to Reproduce (for bugs)
I'm not sure, but what I have is a laptop that I usually keep it connected with another external monitor when at work. So what I did:
1. Installed the AppImage version of the application while connected to the external monitor
2. All good, used it for days
3. Closed laptop and disconnected the external monitor
4. Restarted and now the scaling is way off

## Context
I'm not sure the cause is the disconnection from the external monitor and I can't test it until monday when I get back to work. It could also be that I restarted the system.

## Your Environment
* KeePassXC version/commit used: 2.1.3
* Qt version: 5.8.0
* Compiler (e.g. Clang++3.6.0): 
* Operating System and version: Ubuntu 16.04.2

**Comment by schiorean** [comment]
If I change the Ubuntu desktop app exec line instead of
`Exec="/home/sorin/App/KeePassXC-2.1.3-x86_64.AppImage" %U`
to
`Exec=env QT_SCALE_FACTOR=1 "/home/sorin/App/KeePassXC-2.1.3-x86_64.AppImage" %U`

it's working. Anyway, some bug is lurking somewhere. Suddenly it didn't work.

**Comment by phoerious** [comment]
I suppose your second monitor has a very different pixel density and/or resolution. This is most likely the same issue as this one: #323

**Comment by pskraemer11** [comment]
this
"Exec=env QT_SCALE_FACTOR=1 "/home/.../App/KeePassXC-2.1.3-x86_64.AppImage" %U"

does not wor for me. The font size ist still too small.

**Comment by droidmonkey** [comment]
Please see https://doc.qt.io/qt-5/highdpi.html#high-dpi-support-in-qt
