### ISSUE TITLE
Show last used time/grant time for browser integration keys

### ISSUE THREAD

**Issue by rugk** [keepassxreboot/keepassxc#4340]
[TIP]:  # ( Provide a general summary of the feature in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Summary
[NOTE]: # ( Provide a brief overview of what the new feature is all about )

It would be nice to have the "last used" date/time column in the browser integration panel.

## Desired Behavior
[NOTE]: # ( Tell us how the new feature should work, be specific )

In the DB settings -> browser integration, where the keys for the integrations are listed, there should be a column for when that connection has last been used.

Maybe also, when it was added?

## Possible Solution
[NOTE]: # ( Not required, but suggest ideas on how to implement the addition or change )

So maybe two columns.

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )

The problem is when looking at the list the identifiers (which I mainly name after browser/profile) may not be enough to really know when I have granted that thing, and whether I can revoke it.
To "cleanup" old entries it may just be useful to revoke all entries that were used long ago. 🤔

**Comment by varjolintu** [comment]
"Created" is quite easy to implement. "Last Used" must be implemented in a way that it's only updated when connecting to the database. Updating the timestamp on every action causes a lot of updates to the database, as the custom data would be constantly updated on every request.

**Comment by rugk** [comment]
So  #4392 was just about the created column. May we then reopen this issue or so for the "Last Used" later?

**Comment by varjolintu** [comment]
@rugk I'm ok with reopening this with a modified title. However, "Last Used" is something that must be discussed: how to implement it, or implement at all. I'm worried about the constant changes to the database, so the connection process itself must be modified or we have to figure out how to save the "Last Used" state without rewriting to the custom data all the time.

**Comment by rugk** [comment]
Maybe once a day is enough? I guess we don't need a time, so having the date there is enough.

**Comment by droidmonkey** [comment]
I have no interest in adding additional meta data to the connection id.
