### ISSUE TITLE
Differ password generator icon after build

### ISSUE THREAD

**Issue by margre8** [keepassxreboot/keepassxc#4342]
After build KeePassXC 2.5.3 I can see differ icon of password generator in tab (keys in place of dice)
![Snímek obrazovky pořízený 2020-02-17 20-33-26](https://user-images.githubusercontent.com/40942201/74682031-33577c00-51c5-11ea-8113-d0b4453030e6.png)

My OS:
Ubuntu 18.04.4

Update: I think this differ icon is a logo of Gnome Seahorse app (Passwords and keys)

Thank you for help

**Comment by droidmonkey** [comment]
This wont be a problem in 2.6, we are moving to new icons
