### ISSUE TITLE
TouchID Issues?

### ISSUE THREAD

**Issue by resilowash** [keepassxreboot/keepassxc#4343]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Expected Behavior
New user to KeepassXC: Ability to unlock database with touchID on Mac. 

## Current Behavior
There doesn't seem to be any ability to do this?

## Possible Solution
I'm not sure what the "TouchID For Quick Unlock" checkbox actually does. I don't see much in the documentation about touchID and would be happy to contribute to the documentation of this feature if someone could describe to me how it works.

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1. Create a new database
2. Check the box "TouchID for Quick Unlock"
3. Lock the database
4. Can only unlock with password. 

I'm not sure what the TouchID feature is supposed to do 

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.5.3

Libraries:
- LIBS

Operating system: MacOS
CPU architecture: Intel
Kernel: BSD?

Enabled extensions:
- EXTENSIONS

**Comment by droidmonkey** [comment]
See #2865
