### ISSUE TITLE
Double click in browser credentials dialogue should immediately select this entry

### ISSUE THREAD

**Issue by jo-so** [keepassxreboot/keepassxc#4345]
## Summary

It would be handy if double clicking on an entry in the selection dialogue for the browser integration would immediately select only this one entry and send it to the browser.

It shouldn't matter for which other entries the checkmark is set, the double click on the text behind the checkmark should select and close the dialogue. This would line up with the »auto-fill single entry« of the browser addon, because this would reduce the mouse movements and clicking.

**Comment by droidmonkey** [comment]
@varjolintu add this to the credential selection dialog revamp

**Comment by varjolintu** [comment]
This should be in it already.

https://github.com/keepassxreboot/keepassxc/pull/6549 - "A double click accepts a single entry right away."

**Comment by droidmonkey** [comment]
Excellent
