### ISSUE TITLE
TOTP codes are not accepted anywhere

### ISSUE THREAD

**Issue by PautassoEGiacomina** [keepassxreboot/keepassxc#4346]
Hello,

I have a fairly urgent problem:
The TOTP codes provided by my KeePassXC file are no longer accepted on any site, even if I reset them from scratch. It appears as if it performs different calculations than the site...? Until yesterday everything was fine, I have always used KeePassXC and its TOTP tool and I have always had a great time, but from today I can no longer access any site of mine.
The only thing I have changed since yesterday is the PC, can it be because of this?

Please, help me...
Thank you in advance!

**Comment by droidmonkey** [comment]
Synchronize your system time

**Comment by PautassoEGiacomina** [comment]
Thanks a lot, it works!
In fact I saw only after posting that the solution to my problem had already been treated, sorry.
For those who were reading: my OS is Ubuntu, KeePassXC was installed via Snap package. In case you have my same problem, just set the **automatic** time in Ubuntu, and not manual.

**Comment by PautassoEGiacomina** [comment]
> Synchronize your system time

Thanks a lot, it works!
In fact I saw only after posting that the solution to my problem had already been treated, sorry.
For those who were reading: my OS is Ubuntu, KeePassXC was installed via Snap package. In case you have my same problem, just set the **automatic** time in Ubuntu, and not manual.
