### ISSUE TITLE
Cannot copy note from preview panel after search

### ISSUE THREAD

**Issue by pavlkx** [keepassxreboot/keepassxc#4347]
You search for an entry and want to copy a part of the note text from the first (automatically selected) entry from the Entry preview panel. You select a part of the text you want, press Ctrl-C and the password gets copied instead.

Copying the username works. If you manually select another search result, everything works correctly. It seems that the problem affects only the entry that gets automatically selected during the search.

This may be an edge case of #1653, because it only happens for the automatically preselected entry during the search.

## Expected Behavior
Selected text from notes field gets copied to clipboard.

## Current Behavior
Password gets copied instead.

## Steps to Reproduce
1. Have an entry with username, password and a note text.
2. Search for that entry, it will be preselected with details displayed in the Entry preview panel.
3. Select a part of (or the entire) text in the Notes field of the preview panel and press Ctrl-C.
4. After pasting the text, you will see that the password got copied instead.

## Debug Info
KeePassXC - Version 2.5.3
Revision: f8c962b

Qt 5.9.7
Debugging mode is disabled.

Operating system: openSUSE Leap 15.1
CPU architecture: x86_64
Kernel: linux 4.12.14-lp151.28.36-default

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.2

**Comment by droidmonkey** [comment]
Confirmed

**Comment by shish** [comment]
I sent someone my bank account password because of this (Was trying to send them the sort code which was written in the notes field - so I selected that text, ctrl-c, ctrl-v). "Copy password even if password field isn't selected" seems a pretty dangerous default >.>

**Comment by droidmonkey** [comment]
This is fixed already in develop branch
