### ISSUE TITLE
Keepassxc Portable on Windows cannot connect to Firefox (& solution)

### ISSUE THREAD

**Issue by spaetz** [keepassxreboot/keepassxc#4348]
Posting this here in the hope that it might be useful for other keepassxc portable users on Windows.

# Expected Behavior
KeepassXC Portable (v2.5.3) Windows works in tandem with latest Firefox browser extension.

## Current Behavior
Some things work:

* I have a registry key under "Computer\HKEY_CURRENT_USER\Software\Mozilla\NativeMessagingHosts\org.keepassxc.keepassxc_browser",
* it points to the correct org.keepassxc.keepassxc_browser_firefox.json file
* which points to a correct path "C:\\Users\\spaetz\\bin\\PortableApps\\KeePassXCPortable\\App\\KeePassXC\\keepassxc-proxy.exe"

When I start Firefox, I get a running keepassxc-proxy.exe process as a Firefox child process. However, trying to connect, all I get is a "key exchange failed" error. Turning on add-on debugging leads to the same result and not more helpful information.
When I start keepassxc and turn off the use of a proxy, starting Firefox actually starts a keepassxc process, however all I still get is a "key exchange failed" error.

NO combination of options, deleting of keepassxc and/or the broweser extension, deletion of registry entries, or using a fresh Firefox profile helped.

## Possible Solution
I noted that there are actually 2 binaries:
**BINARY1:**
C:\Users\spaetz\bin\PortableApps\KeePassXCPortable\KeePassXCPortable.exe (248kb) and
**BINARY2:**
C:\Users\spaetz\bin\PortableApps\KeePassXCPortable\App\KeePassXC\KeePassXC.exe (7094kb)

The latter is also the directory which contains the keypassxc-proxy.exe. The binary in the former directory is what is started when one starts Keepassxc through the PortableApps menu.

IF I directly start the latter binary, the Firefox extension is able to connect to the running keepassxc. If I start the former, I will get a key exchange failed error. Somehow, in this case the proxy will probably try to talk to the wrong binary. (not sure what weird wrapper the first binary is).

I autostart BINARY2 now on system start and seems to do the trick for me. I realize that this is not the fault of keepassxc, but given the multitude of reported errors and the unhelpful error message I think this might be of us for other users of the Portable Version. It might be useful on the wiki if confirmed by other users of the portable version on windows....

## Debug Info
KeePassXC - Version 2.5.3
Revision: f8c962b
Qt 5.13.2
Diagnosemodus ist deaktiviert.
Betriebssystem: Windows 10 (10.0)
CPU-Architektur: x86_64
Kernel: winnt 10.0.16299
Aktivierte Erweiterungen:
- Auto-Type
- Browser-Integration
- SSH-Agent
- KeeShare (bestätigtes und unbestätigtes Teilen)
- YubiKey
Kryptographische Bibliotheken:
 libgcrypt 1.8.5

**Comment by droidmonkey** [comment]
We don't support the "PortableApps" distribution. The only portable version for windows we support is the zip download from our GitHub here.
