### ISSUE TITLE
ssh-agent integration with git?

### ISSUE THREAD

**Issue by Gooberpatrol66** [keepassxreboot/keepassxc#4349]
[TIP]:  # ( Provide a general summary of the feature in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Summary
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
Can the agent be used to allow me to git push etc. without entering my password every time?

## Desired Behavior
[NOTE]: # ( Tell us how the new feature should work, be specific )
I believe KDE's agent does this. Working like that does would be nice.

## Possible Solution
[NOTE]: # ( Not required, but suggest ideas on how to implement the addition or change )

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
Want to use git

**Comment by droidmonkey** [comment]
Yes, git will pull from a running ssh-agent process.

**Comment by Gooberpatrol66** [comment]
How to set it up?

**Comment by droidmonkey** [comment]
@hifi do you have docs for sshagent

**Comment by hifi** [comment]
The terminology is a problem here. We work as a *client* and if you already have a working ssh-agent process KeePassXC will just work with it. 

The agent configuration page should have a brief explanation as it's still quite empty. Any objections to that?

**Comment by Gooberpatrol66** [comment]
So I need use an agent from somewhere else? KDE/GNOME/whatever?

**Comment by hifi** [comment]
Yes, if `ssh-add` works from a terminal then you should have an agent running, most likely OpenSSH `ssh-agent` started by your desktop environment. KeePassXC just works at that point when you enable the integration.
