### ISSUE TITLE
Only actionable menu items (not greyed-out) are "Open Database" and "Password Generator"

### ISSUE THREAD

**Issue by grant-gitcode** [keepassxreboot/keepassxc#435]
## Expected Behavior

When I open the keepassxc application, there should be a button which says "create new database". There is none.

## Current Behavior

Instead of seeing the option to create a new database, there is only the option to open a database, which itself does not give the option to create a new database.

The terminal prints:

```
Gtk-Message: Failed to load module "overlay-scrollbar"
Gtk-Message: Failed to load module "gail"
Gtk-Message: Failed to load module "atk-bridge"
![keepassxc_error_maybe](https://cloud.githubusercontent.com/assets/22384743/24327987/d543c236-11a3-11e7-86b3-ee6d5feba121.png)

Gtk-Message: Failed to load module "unity-gtk-module"
Gtk-Message: Failed to load module "canberra-gtk-module"
XmbTextListToTextProperty result code -2
XmbTextListToTextProperty result code -2
XmbTextListToTextProperty result code -2
```

## Steps to Reproduce (for bugs)

1. sudo snap install keepassxc
2. snap run keepassxc
3.
4.

## Your Environment

* KeePassXC version/commit used: 2.1.3

* Qt version (e.g. Qt 5.3): 0.3.0
* Compiler (e.g. Clang++3.6.0): g++ 5.4.0
* Operating System and version: Ubuntu 16.04 LTS
![keepassxc_error_maybe](https://cloud.githubusercontent.com/assets/22384743/24327994/e9d64926-11a3-11e7-9123-e09b5063eb90.png)

**Comment by phoerious** [comment]
The action to create a new DB is hidden in the menu, which unfortunately isn't shown in Ubuntu unless you hover over the top bar. 

In develop we already have a nice welcome interface, though, and additionally a button in the toolbar.
