### ISSUE TITLE
Crash if including a "-" character at the end of URL and then fetching the icon.

### ISSUE THREAD

**Issue by floppydisken** [keepassxreboot/keepassxc#4352]
## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Error message with "Failed to fetch website icon"

## Current Behavior
[NOTE]: # ( Tell us what actually happens )
Crashes the program with message "Unhandled exception at 0x00007FFD591247A5 (msvcrt.dll) in KeePassXC.exe: 0xC0000005: Access violation reading location 0x000001DF1CFF6000." (this the message in Visual Studio)

## Steps to Reproduce
1. Create a new entry
2. Put "https://google.com-" without quotes into the URL field
3. Click the fetch icon button.

## Debug Info
KeePassXC - Version 2.5.1
Revision: 0fd8836

Qt 5.13.1
Debugging mode is disabled.

Operating system: Windows 10 (10.0)
CPU architecture: x86_64
Kernel: winnt 10.0.18363

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.5

Operating system: Windows 10
CPU architecture: x64

**Comment by droidmonkey** [comment]
"That's interesting"
