### ISSUE TITLE
Browser integration does not work with keepassxc snap package on Debian buster

### ISSUE THREAD

**Issue by Friday13th87** [keepassxreboot/keepassxc#4353]
Exactly same issue as in #2890 described
 
## Expected Behavior
After
- installing keepassxc from snapd
- installing the official keepassxc addon for firefox/chromium etc
and
- running the script helper (matching the keepassxc version) with a browser restart (or pc restart)

a window should pop up after hitting the connect database button in the extension settings to connect to the already opened keepass database

## Current Behavior
after taking the steps described above, nothing is happening when hitting the "database connect" in extension settings

with nothing, i mean nothing, no error just nothing
if i press the reload button at the addon icon at the browser, there is an error with key exchange.
debug console says that maybe keepassxc is not running (but it is ofc)

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )

## Steps to Reproduce
1. install keepassxc over snapd
2. install browser extension
3. try it out urself

## Context
cat ~/.mozilla/native-messaging-hosts/org.keepassxc.keepassxc_browser.json
{
    "name": "org.keepassxc.keepassxc_browser",
    "description": "KeePassXC integration with native messaging support",
    "path": "/snap/bin/keepassxc.proxy",
    "type": "stdio",
    "allowed_extensions": [
        "keepassxc-browser@keepassxc.org"
    ]
}

ls -a -l /snap/bin
lrwxrwxrwx 1 root root 13 Feb 20 18:14 keepassxc -> /usr/bin/snap
lrwxrwxrwx 1 root root 13 Feb 20 18:14 keepassxc.cli -> /usr/bin/snap
lrwxrwxrwx 1 root root 13 Feb 20 18:14 keepassxc.proxy -> /usr/bin/snap

ls -a -l /usr/bin/ | grep snap
lrwxrwxrwx 1 root root           19 Feb 20 19:17 keepassxc -> /snap/bin/keepassxc
-rwxr-xr-x 1 root root     14997328 Jun  6  2019 snap
lrwxrwxrwx 1 root root           20 Jun  6  2019 snapctl -> ../lib/snapd/snapctl
lrwxrwxrwx 1 root root           25 Jun  6  2019 ubuntu-core-launcher -> ../lib/snapd/snap-confine

## Debug Info
KeePassXC - VERSION 2.5.3

Operating system: Debian Buster
CPU architecture: amd64
Kernel: 4.19.0-8 current stable Buster kernel

Enabled extensions:
tried it with a clean new install of latest firefox from debian unstable and firefox-esr from debian stable - both same behavior

**Comment by droidmonkey** [comment]
Where is the snap directory in your home folder?

**Comment by Friday13th87** [comment]
ls -l ~/snap/keepassxc
687
common
current -> 687

so i have a folder "snap" directly in my home directory if this answers your question

**Comment by droidmonkey** [comment]
Yah what I'm thinking is that for some reason the named pipe for native messaging is not being created properly. It should be placed in ~/snap/keepassxc/common

**Comment by Friday13th87** [comment]
actually i dont understand what u are meaning
if u mean the json file, placed in the browser directorys, i thought they need to be where they are.
i was checking the trouble page of course and i thought they should direct to the keepassxc-proxy.

i was installing a build from flatpak and this one is working as it should

**Comment by droidmonkey** [comment]
The json file tells the browser how to launch the application the communicates over native messaging. The named pipe is how the launched proxy application actually sends the I/O to and from KeePassXC.

**Comment by DarrenSchwartz** [comment]
I got snap browser integration working by running the script, but had to fix an error in the script first. The script refers to `keepassxc.proxy` but the file is actually named `keepassxc-proxy` on my debian system. Once I replaced the period with a dash on lines 27 and 32, the script ran without errors and the browser extension worked. The typo also exists in line 26 comment and line 28 echo string, so should also be corrected for good measure.

**Comment by droidmonkey** [comment]
That's not a typo, that is how snaps name extra executables. Are you sure you are using the snap?

**Comment by DarrenSchwartz** [comment]
> 
> 
> That's not a typo, that is how snaps name extra executables. Are you sure you are using the snap?

Yes, definately using snap.  And after seeing your reply and investigating, I may have to backtrack on my original fix.  Changing the period to a dash did eliminate the script error, but did not allow the browser to connect. Running the script as-is gives the error `Could not find keepassxc.proxy! Ensure the keepassxc snap is installed properly.` however, the file does exist at `/snap/bin/keepassxc.proxy`
I originally replaced the period with a dash because I searched around and found a path like this:
`/snap/keepassxc/current/usr/bin/keepassxc-proxy`.  This fixed the script error, but did not fix the connection problem because it's not the right file (I thought this is how I fixed it on another computer, but it didn't work this time).  It did highlight for me that the path to `keepassxc.proxy` was not being found by the script because it was looking in the wrong directory.  The real fix for me was to replace `keepass.proxy` in the script with the full path `/snap/bin/keepass.proxy`.

**Comment by droidmonkey** [comment]
That means your snap bin directory is not on your PATH

**Comment by DarrenSchwartz** [comment]
> 
> 
> That means your snap bin directory is not on your PATH

Ahh, of course. Sorry, this was my first introduction to snap.  Should the directory not be added automatically when you `apt install snapd`?  Anyways, thanks!

**Comment by droidmonkey** [comment]
That is curious

**Comment by RogerWeihrauch** [comment]
Hi all
Well, I experienced the same 'error'/phenomenon with version KeePassXC2.6.6.
BUT, above mentioned steps helped me out a bit.
Well, is there a way to have/create a kind of a 'link' in xfce4 menues to get KeePassXC 'confortably' started?
Additionally: I get the following 'messages' when invoking 'keepassxc' on terminal
debian@CorSaiR:~/Downloads$ keepassxc
Qt: Session management error: Authentication Rejected, reason : None of the authentication protocols specified are supported and host-based authentication failed
/usr/share/libdrm/amdgpu.ids: No such file or directory
QObject::startTimer: Timers cannot have negative intervals

(keepassxc:4893): GLib-GIO-WARNING **: 08:20:35.817: Error creating IO channel for /proc/self/mountinfo: Permission denied (g-file-error-quark, 2)
Gtk-Message: 08:20:36.119: GtkDialog mapped without a transient parent. This is discouraged.

Do I have to grumble on them or 'can'/do I have to ignore them?

Thank you all on your highly appreciated response.

Kind regards
Roger

**Comment by calraith** [comment]
@DarrenSchwartz You sure /snap/bin is in your $PATH?  Remember that your X environment doesn't source ~/.bashrc or ~/.profile or similar by default.  Unless you've created an .xsessionrc and set your $PATH there your windowing environment and your console sessions have two very different understandings of $PATH.

On my own system I put the following into ~/.profile, then did `ln -s ~/.profile ~/.xsessionrc`:

    # set PATH so it includes /snap/bin if it exists
    if [ -d "/snap/bin" ] ; then
        PATH="/snap/bin:$PATH"
    fi

**Comment by droidmonkey** [comment]
@calraith did that fix everything for you?

**Comment by calraith** [comment]
@droidmonkey Fixed everything except Brave integration.

**Comment by droidmonkey** [comment]
Brave might require a custom definition for the native messaging json file. Brave changes where their config files are stored on every platform.
