### ISSUE TITLE
database is locked automatically (timeout is disabled)

### ISSUE THREAD

**Issue by ovz93br43v7** [keepassxreboot/keepassxc#4358]
## Expected Behavior
Database stays open until I lock it myself because the timeout function is disabled.

## Current Behavior
Database locks itself after some time.

## Possible Solution
No idea.

## Steps to Reproduce
Open database. Do something (surfing, working, playing. Next time I switch to  KeepassXC the database is locked.

## Context
OS: elementaryOS 5.1 (two different laptops, same behaviour)
KeepassXC from ubuntu PPA

## Debug Info
```
KeePassXC - Version 2.5.3
Revision: f8c962b

Qt 5.9.5
Diagnosemodus ist deaktiviert.

Betriebssystem: elementary OS 5.1.2 Hera
CPU-Architektur: x86_64
Kernel: linux 5.3.0-40-generic

Aktivierte Erweiterungen:
- Auto-Type
- Browser-Integration
- SSH-Agent
- KeeShare (bestätigtes und unbestätigtes Teilen)
- YubiKey
- Secret-Service-Integration

Kryptographische Bibliotheken:
 libgcrypt 1.8.1

```

**Comment by droidmonkey** [comment]
Screenshot of your security settings page please

**Comment by ovz93br43v7** [comment]
![Screenshot von 2020-02-22 15 48 56](https://user-images.githubusercontent.com/48738861/75094395-ed1a6800-558a-11ea-95f3-585e982dd0f9.jpeg)

**Comment by droidmonkey** [comment]
I have this setting disabled and never experienced a timed lockout. You do have lock when lid closed, sleep, etc. Sometimes when you connect/disconnect a second monitor this lock behavior is triggered.

**Comment by ovz93br43v7** [comment]
It varies from time to time.
Sometimes the databases is locked after just some minutes and today it stays open all the day.

Do you need some additional logs? (I have no idea what could be helpful...)

**Comment by droidmonkey** [comment]
We don't log any of this information. Report back if you keep experiencing this. I suspect you are triggering the lid/session lock and not the timeout.

**Comment by ovz93br43v7** [comment]
Is there any info /system log that I could provide additionally? I'm experiencing this during active working at the PC.

**Comment by droidmonkey** [comment]
Not that I'm aware of, your best bet is to run a debug build and set breakpoints on the lock function to dump a stack trace. If you can't do that than unfortunately there is nothing we can do right now. Have you tried disabling the lock when screen lid/screensaver is activated.

**Comment by ovz93br43v7** [comment]
Ok, I think I'm not able to test this with a debug build. (I don't know how)

I have checked that elementaryOS don't have any screensavers implemented, I disabled the display timeout in the settings and I disabled tlp (notebook powersaving) but the datebase was locked again after some minutes.
