### ISSUE TITLE
Preconfig Settings

### ISSUE THREAD

**Issue by MiJo112** [keepassxreboot/keepassxc#4359]
I would like to roll out KeePassXC in our company for the users. It would be nice if I could preconfigure the settings and block some settings from being changed. An ADMX template for the Windows GPOs would be very nice, but it can also be a simple configuration file that I also install.
Is this possible or is it planned in the future?

**Comment by droidmonkey** [comment]
Download the portable zip version and configure the application to your liking, don't open any database. Then close the app and copy the `keepassxc.ini` file that was modified in the root directory. You can deploy that to c:/users/{user}/AppData/Local/keepassxc/

We have another issue tracking the request for administratively controlled settings.
