### ISSUE TITLE
Payment Methods and Addresses

### ISSUE THREAD

**Issue by Y0Mamma** [keepassxreboot/keepassxc#4361]
Chromium-based browsers have the ability to autofill addresses and payment methods. This is an awesome feature to have, but It would be much safer and portable if this was done via KeepassXC instead of a browser.

**Comment by droidmonkey** [comment]
We have discussed this before and will not be implementing this behavior.

**Comment by Y0Mamma** [comment]
Hi DroidMonkey. It's been a while and I may have asked this somewhere else before but I can't remember. What is the reason(s) for not implementing this feature? I'm just curious and am not trying to be a goob. :-) I love KeePassXC and I think you guys have done a phenomenal job with this app. I love this feature in Ungoogled Chromium, but I don't trust them as much as I trust KeePassXC.

**Comment by droidmonkey** [comment]
Its an unbounded problem, many different form types and input fields. We are a password manager not an address book application. This would be a tremendous amount of work, a constant headache, and there are already existing solutions that work incredibly well.
