### ISSUE TITLE
Could'nt connect Browser extension to database

### ISSUE THREAD

**Issue by zulu34sx** [keepassxreboot/keepassxc#4362]
My KeepassXC-Browser firefox addon showed the message upgrade your keepassXC when connecting to the loggedin database. After checking my Debian10's repos, i looked up how to upgrade in the internet and found the snap installer, installed **version 2.5.3**. 
Now, after the addon didn't connect anyway, i found **the script on to unsandbox keepassxc and used it**. Unfortunately, it still doesn't work, i still can't connect my keepassXC to my Firefox-Extension. 
KeePass-Proxy is running. 
Can anyone help me?

**Comment by droidmonkey** [comment]
Use the AppImage instead

**Comment by zulu34sx** [comment]
Please tell me more precisely, how do I do that, what does that mean?

**Comment by droidmonkey** [comment]
From our download page: https://keepassxc.org/download/#linux
