### ISSUE TITLE
Cannot  read complete name of subfolders of database

### ISSUE THREAD

**Issue by Alainternaute** [keepassxreboot/keepassxc#4365]
Hello
When KeepasXC is at minimum size windoww, 
I can't extend left panel and can't read complete name of subfolders of database.
## Possible Solution
 Allow at least half of the window for left panel size.
## Context
Version 2.53 on Windows 10.

**Comment by droidmonkey** [comment]
Any particular reason for having the app at minimum size? There is also a horizontal scrollbar for the overflow.

**Comment by Alainternaute** [comment]
No, just to take a minimum on screen.
In french name are longer and yes, there is a scrollbar but for reading the left panel it's not very handy. 
At least it should go until all the displayed names are not truncated .
Keepass have not this behavior.
As explorer, you can move the vertical separation from a minimum left to a maximum right.
![2020-02-23 21_22_47-Window](https://user-images.githubusercontent.com/26257992/75119381-bd4e8b80-5682-11ea-86c7-0213580f4ded.jpg)
![2020-02-23 21_23_03-Window](https://user-images.githubusercontent.com/26257992/75119383-bfb0e580-5682-11ea-8503-6e09ee1fe46b.jpg)

**Comment by droidmonkey** [comment]
Agree this is a bug
![image](https://user-images.githubusercontent.com/2809491/75119532-a9d6fc80-5651-11ea-9c4d-0c843fd92932.png)

**Comment by Alainternaute** [comment]
Thanks.

**Comment by droidmonkey** [comment]
This is no longer a problem after our theming improvement.
