### ISSUE TITLE
Window content garbeld after resuming from suspend

### ISSUE THREAD

**Issue by gilgwath** [keepassxreboot/keepassxc#4369]
Hello everybody,
First off: Massive thank you for making my life easier and more secure with this fantastic application!

I hope I included everything you need. If you need more information or if you want me to do additional testing, please feel free to ask.

# Current Behavior
I have my Keepass set to lock when the lock screen comes on. This works fine my display timeout kicks in or I lock it manually. However, if I resume Windows 10 the machine from "Hibernate" state after the closing the lid, the content of the KeepassXC window is corrupted. The application still accepts input and updates the window content, but the user has no idea what they are doing because of the mismatch between where the controls are rendered and where in the windows the actually are. See screen this screenshot:

<img width="801" alt="keepassXC garbeld screen." src="https://user-images.githubusercontent.com/9314993/75138626-f589b480-56ea-11ea-9a26-6109781a452d.png">

# Expected Behavior
Window Content looks normal after resuming from hibernation

# Possible Solution

No idea.

# Steps to Reproduce

1.  Set windows to hibernate when closing the laptop lid.
2. Open any database
3. Close laptop lid and let it go to sleep
4. Open the laptop lid and resume from hibernate
5. Unlock account
6. Try to unlock Keepass database

# Context
Hardware Model: ThinkPad 470p

I have to add that this laptop has a 2K display and I often use it in conjunction with two external 4K displays. Judging from the state of the window it might be a high DPI scaling issue. 

**Debug info:**
KeePassXC - Version 2.5.3
Revision: f8c962b

Qt 5.13.2
Debugging mode is disabled.

Operating system: Windows 10 (10.0)
CPU architecture: x86_64
Kernel: winnt 10.0.18362

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.5

**Comment by droidmonkey** [comment]
That's unique! I have never seen it do that before. I run mine on a win10 4k laptop without problems. Please isolate whether this happens without the 4k monitors.

**Comment by rennefJ** [comment]
I might be observing a related issue. 
I also put my Laptop to sleep in the evening and when I unlock my account in the morning, there is no keepassxc window at all.
When I try to open keepassxc again, nothing happens and I cannot get a keepassxc window.
The keepassxc process is still running.
After killing the keepassxc process everything works again.

**Comment by gilgwath** [comment]
I tried finding out more about the specific conditions around my docking station, attached monitors and the relationship between wake-up/suspend. The frustrating thing is: since I opened this issue I was unable to replicate the behavior on purpose. It sometimes happens, but always when I did not pay any particular attention to what the specific order of events and circumstances was. When I sit down and start methodically testing it,  I can't really nail it down.  I also had it happen ONCE on my Microsoft Surface Pro 7, no external screens attached there though.  If I find the time, I'll have another try tomorrow.

**Comment by droidmonkey** [comment]
It is likely nothing we can do about it. Could even be a bug with Windows scaling

**Comment by gilgwath** [comment]
> 
> 
> It is likely nothing we can do about it. Could even be a bug with Windows scaling
You are probably  right, I just had Qownnotes play the same trick on me. Seems to be a problem with QT on Windows then. Maybe overriding the scaling settings via Application Properties gets rid of the problem. Should I file a bug with QT then?

**Comment by droidmonkey** [comment]
Yes this is surely a Qt bug. Try to isolate the cause for them.
