### ISSUE TITLE
"No match found", issue with subdomains

### ISSUE THREAD

**Issue by Razer0123** [keepassxreboot/keepassxc#4370]
## Expected Behavior
Would expect to login if the subdomain is different

## Current Behavior
Just imported a database, most of the websites won't login because of domain issues, for example, a login saved for aliexpress.com won't login in, de.aliexpress.com or login.aliexpress.com

KeepassXC for Firefox says "no match found"

## Possible Solution
Check for subdomain matches

## Steps to Reproduce
[NOTE]: # C
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1. Create login for aliexpress.com
2. Try to login via de.aliexpress.com or login.aliexpress.com

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Versione 2.5.3
Revisione: f8c962b
Qt 5.14.1
System: Arch Linux

**Comment by droidmonkey** [comment]
Couldn't replicate this at all.

**Comment by Razer0123** [comment]
Just checked again, the issue happens having www in the address

Like https://www.aliexpress.com

**Comment by droidmonkey** [comment]
That is because www is a subdomain.
