### ISSUE TITLE
Application Crashes when closing database then exiting/closing KeepassXC app

### ISSUE THREAD

**Issue by alfwro13** [keepassxreboot/keepassxc#4373]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Expected Behavior
Database closes and application quits

## Current Behavior
Occasionally the application crashes with error:
The instruction 0xAddress referenced memory at 0x00000000000000000000. The memory could not be read. Click on OK to terminate the program
![image](https://user-images.githubusercontent.com/10945277/75261763-7330eb80-57e3-11ea-92e6-36207fc83613.png)

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1. Open KeePassXC
2. Open Database
3. Use the program for some time 
4. Close Database
5. Quit KeePassXC 

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )

## Debug Info
KeePassXC - Version 2.5.3
Revision: f8c962b

Qt 5.13.2
Debugging mode is disabled.

Operating system: Windows 10 (10.0)
CPU architecture: x86_64
Kernel: winnt 10.0.18363

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.5

**Comment by droidmonkey** [comment]
This is a result of bad interactions betwern saving and locking databases. I already fixed it in a PR so closing this issue.
