### ISSUE TITLE
Password Generator resets when window is minimised

### ISSUE THREAD

**Issue by ddabici** [keepassxreboot/keepassxc#4376]
Hi,
If generate a password and then minimise keepassxc to taskbar without saving, then open again, the generated password is lost.

# Expected Behavior
Keep the new generated password until I save it or cancel it.

## Current Behavior
New generated password is lost when minimise keepassxc to taskbar

## Steps to Reproduce
1.Generate a new password in order the change old one.
2.Minimise keepassxc to the taskbar  
3.

## Context
[NOTE]: # I generate the password in order to change old one, then minimise the keepassxc to the taskbar  and when open again the password was gone. 

## Debug Info
[NOTE]: #4374 
KeePassXC - Version 2.5.2
Revision: 62cda9d

Qt 5.13.2
Debugging mode is disabled.

Operating system: Windows 10 (10.0)
CPU architecture: x86_64
Kernel: winnt 10.0.17763

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.5

KeePassXC - VERSION 2.5.2
Revision: REVISION

Operating system: windows 10

Enabled extensions:
- EXTENSIONS

**Comment by droidmonkey** [comment]
Pretty sure I fixed this in #4367

**Comment by ddabici** [comment]
I have upgrade  keepassxc to 2.5.3 but behavior is the same

**Comment by phoerious** [comment]
I can confirm: the password is regenerated when the window is minimised and then shown again. Password visibility is also toggled.

**Comment by droidmonkey** [comment]
This is because the reset() function is called on show event. I deleted that from my PR linked above. That is for the next version not 2.5.3.
