### ISSUE TITLE
TOTP shows wrong code in KeePassXC 2.5.3

### ISSUE THREAD

**Issue by 5FeetUnder** [keepassxreboot/keepassxc#4377]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Keepassxc TOTP is the same code as TOTP in android app with same secret

## Current Behavior
[NOTE]: # ( Tell us what actually happens )
The TOTP generated by Keepassxc with the same secret as the TOTP generated by the android app has always a different code than the android app.

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1. Scan a QR code for a Google Authenticator type TOTP with phone QR reader
2. Scan that same code with TOTP app on phone
3. Create TOTP on Keepass entry using string after "secret=" in URL scanned in step 1
4. Compare generated codes

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.5.3
Revision: f8c962b

Qt 5.13.2
Debugging mode is disabled.

Operating system: Windows 10 (10.0)
CPU architecture: x86_64
Kernel: winnt 10.0.18363

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.5

PS: the weird thing is, when I then use "Show TOTP QR Code..." in Keepass and scan this with my TOTP app, it shows the same as Keepass. Sadly this isn't a solution, since the code shown by Keepass is wrong.

**Comment by droidmonkey** [comment]
Sync your system time

**Comment by 5FeetUnder** [comment]
my system time should be synced, I made sure of that after reading this in the other issues of that type.

**Comment by droidmonkey** [comment]
If the codes are the same then it must be your system time (or even your phone's time).

**Comment by 5FeetUnder** [comment]
if that is the case, then why is the code the same on my phone when I scan the keepass QR code?

**Comment by droidmonkey** [comment]
The only other difference could be using sha512 instead of sha256. I am not aware of Google authenticator supporting that though.

**Comment by 5FeetUnder** [comment]
I did now try with sha1, sha256 and sha512 and all of them don't produce the expected code.
maybe the QR code URL could give hints as to what is happening?
the provided URL which makes the app produce the correct code is of form `otpauth://totp/[name of the service i want to log into]%20MFA-Only:[user id in lower case]?secret=[SECRETKEY]&digits=6&algorithm=SHA1&issuer=[name of the service i want to log into]%20MFA-Only&period=30` and the URL provided by the Keepass QR code is of form `otpauth://totp/[name I gave the keepass entry]:[user id in upper case]?secret=[SECRETKEY]&period=30&digits=6&issuer=[name I gave the keepass entry]`

**Comment by 5FeetUnder** [comment]
it works now after a totp secret reset of the service i want to log into.

**Comment by droidmonkey** [comment]
That would imply that the original QR code you used for the authenticator app was not the same as the one you used for standard QR reader.
