### ISSUE TITLE
"Show Passwords" shortcut in entry view is undiscoverable and should not persist

### ISSUE THREAD

**Issue by pklapperich** [keepassxreboot/keepassxc#4378]
## Expected Behavior
 There should be a menu item in Entries or Tools labeled "Show Passwords Ctrl-Shift-C"

## Current Behavior
There's no context menu, setting, or menu item associated with Ctrl+Shift+C. But this key sequence reveals all of your passwords until you press it again. Lock the database and even closing KeePassXC doesn't restore the passwords to the default, hidden state.

## Possible Solution

- Add a menu item that clearly denotes the key sequence. Document the feature in the user guide.

## Steps to Reproduce
1. Open and unlock a database
2. Notice a tabular view is shown with the password column completely obscured.
3. Press Ctrl+Shift+C
4. Notice all your password are visible
5. Lock and unlock the database. Notice all your passwords are still visible.
6. Close and re-open KeePassXC. Unlock your database. Notice all your passwords are still visible.
7. Check the context menus, main program menu bar, Tools -> Settings, Database -> Settings, and Help -> User Guide. Notice there is no mention of Ctrl+Shift+C. 

## Context
[NOTE]: # 
This is very clearly a UI and/or Documentation bug. While the ability to show the contents of the password field is certainly something one might find desirable, the ability to KNOW HOW to quickly show and hide the contents of this field is even more desirable.

Pressing this key sequence accidentally is EXTREMELY UNNERVING and there is no clear way to undo the action.

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.5.3
Revision: f8c962b

Libraries:
 libgcrypt 1.8.5

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: 5.4.8-arch1-1

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

**Comment by droidmonkey** [comment]
Right click the header of the entry view (column names). We do need to make this a temporary setting instead of persist.

**Comment by NathanaelA** [comment]
Just a FYI; this should be CTRL-H to match Keepass2.   I was looking for this keystroke; and ran into this issue.  :-D

**Comment by pklapperich** [comment]
@droidmonkey the header still doesn't show the shortcut and I clearly didn't think to look there.

**Comment by loligator** [comment]
I accidentally hit this combination while trying to copy something from a terminal. Until I found this issue I had no idea what had happened. Frankly, I'd prefer if this shortcut could be disabled in settings.

**Comment by droidmonkey** [comment]
@phoerious should we remove this keyboard shortcut in 2.6? I do agree it is unnecessary and causes a lot of issues.

**Comment by NathanaelA** [comment]
@droidmonkey - The keystroke is useful, but It would be much better if it matched keepass itself's ctrl-H (Hide/unHide)
