### ISSUE TITLE
Add Menubar Icon MacOS

### ISSUE THREAD

**Issue by ibrokemypie** [keepassxreboot/keepassxc#438]
## Expected Behavior

Keepassxc minimises into menubar on MacOS when closed or minimised

## Current Behavior

Currently closing quits the app entirely and minimising goes to dock instead, with no configurable options

## Possible Solution

Add options (similar to on linux with the statustray)

## Context

Especially for KeeHTTP, the app needs to be constantly running in the background, but currently it goes against the MacOS design standards by completely quiting the app when the close window button is hit, and it needs to be minimised to the dock to continue running in background.
egs from 1password
![](https://i.agilebits.com/megan/spg_mini.png)

![](https://www.intego.com/mac-security-blog/wp-content/uploads/2014/11/1password-menubar.png)

![](http://www.guidingtech.com/assets/postimages/2016/05/1Password-Mac-Menu-Bar.png)

![](http://blog.macsales.com/wp-content/uploads/2016/12/1PasswordMenuBar1280.jpg)

![](https://us.v-cdn.net/5020219/uploads/editor/m1/1xtbs2qw8kn2.png)

## Your Environment

* KeePassXC version/commit used: 76dcfb5ed0c874f6a835ef0347ddf6098b149e9b
* Qt version (e.g. Qt 5.3): 5.8.0
* Compiler (e.g. Clang++3.6.0): libgcrypt 1.7.6?
* Operating System and version: MacOS Sierra

**Comment by ibrokemypie** [comment]
have updated following the template and providing numerous examples

**Comment by droidmonkey** [comment]
Um there is already an option to "minimize on close"

**Comment by mrrsm** [comment]
That setting doesn't show up for me either actually on MacOS Sierra.  I am going to rebuild off of develop just to verify that it isn't there.

To confirm it should show up under the "Basic Settings" tab in the "General" section?

**Comment by phoerious** [comment]
The setting is disabled on OS X. The code comment is "tray is useless on OS X". Since I'm not using OS X myself, I've never verified if that is true also for new versions.

**Comment by mrrsm** [comment]
I personally like the tray apps I have on osx for other apps however most of them seem to have some unique drop down/popup like @ibrokemypie showed in the images he posted.  I am not sure what your feelings are about having custom code for an osx taskbar or if it would mimic the way it works on other systems.  I haven't looked into it yet but I may spend some time in the near future looking into it to understand how it works and possibly implementing it.

**Comment by droidmonkey** [comment]
Wow, sorry didn't realize this was disabled for osx!

**Comment by ibrokemypie** [comment]
That explains a lot to me! Personally, I would be content with the option simply hiding the window and removing the dock entry, with the only functionality being click to restore it and keeping it running in the background for keehttp

**Comment by damongant** [comment]
This leads to sort of another issue, KeePassXC ignores signals when shutting down, requiring the user to either wait for the timeout or close KeePassXC manually.

**Comment by phoerious** [comment]
Are you sure you are using the latest version? Shutdown interference has been fixed a couple of versions ago.
