### ISSUE TITLE
Keepass does Spacebar behind Auto Type Username

### ISSUE THREAD

**Issue by freakms** [keepassxreboot/keepassxc#4380]
While Using Auto Type for an Application I am able to use the short cut.

But the username is wrong everytime, because Keepassxc put a space bar char behind the Username

Version: KeePassXC 2.5.3
Applications: Multiple

OS: Windows 10 1909

**Comment by droidmonkey** [comment]
Gonna need more information. What is your Auto-Type shortcut, what application, does this happen across multiple applications.
