### ISSUE TITLE
crashes under macos 10.15.4 Beta (19E242d)

### ISSUE THREAD

**Issue by pixelparliament** [keepassxreboot/keepassxc#4381]
Dock icon just appears for a second after start, then closes.

starting from terminal ends with this message:
"killed     /Applications/KeePassXC.app/Contents/MacOS/KeePassXC"

Konsole displays:
"proc 1217: load code signature error 4 for file "KeePassXC"""
"Security policy would not allow process: 1217, /Applications/KeePassXC.app/Contents/MacOS/KeePassXC"

KeePassXC-2.5.3

**Comment by droidmonkey** [comment]
Completely uninstall and then reinstall. You need to authorize the app to run.

**Comment by pixelparliament** [comment]
I deleted the App in Applications, the folder in Application Support and the file in Preferences.
I reinstalled the current version. System asked me if I really want to open it blablabla... Say yes. Still the same eror.

**Comment by droidmonkey** [comment]
My guess is this is related to the OS beta. It certainly isn't broken on our end since we work on all other macOS

**Comment by pixelparliament** [comment]
Thank you for your help. I will post as soon it is resolved.

**Comment by pixelparliament** [comment]
Tried to open KeePassXC again with todays MacOS Beta Update. Still no luck. Then went on your GitHub page, downloaded the KeePassXC 2.5.3-snapshot. 

Snapshot works.

**Comment by droidmonkey** [comment]
Snapshot is not signed
