### ISSUE TITLE
Double click on title resets search filter

### ISSUE THREAD

**Issue by RainerSchwarze** [keepassxreboot/keepassxc#4384]
Double clicking on title cell resets search filter instead of opening the edit dialog for that entry.

## Expected Behavior

The dialog for editing the entry should appear

## Current Behavior

The search filter is cleared. The edit dialog does not open.

## Steps to Reproduce

1. start KeePassXC
2. press Ctrl-F or click in search field
3. type something to filter the database entries
4. double click on the title cell for one of the entries

## Context

confusing UX

## Debug Info

KeePassXC - Version 2.5.3
Revision: f8c962b

Qt 5.13.2
Debugging mode is disabled.

Operating system: Windows 10 (10.0)
CPU architecture: x86_64
Kernel: winnt 10.0.17763

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.5

**Comment by phoerious** [comment]
This is not really a bug, it's more of a feature with bad usability. It matters where you double-click. The group column takes you to the group, the entry title column takes you to the entry. Clicking any other column does nothing.

**Comment by droidmonkey** [comment]
This doesn't happen to me, i can edit an entry from a search without issue.

**Comment by RainerSchwarze** [comment]
> This doesn't happen to me, i can edit an entry from a search without issue.

I am using the portable edition (just extracted the ZIP file contents to a directory). Could this make any difference?
