### ISSUE TITLE
KeepassXC crash on todays macOS public beta

### ISSUE THREAD

**Issue by stesser** [keepassxreboot/keepassxc#4385]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
KeepassXC does not crash immediately when invoked.

## Current Behavior
[NOTE]: # ( Tell us what actually happens )
Crash, the diagnostic output generated includes:

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (Code Signature Invalid)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace CODESIGNING, Code 0x1

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )
Probably a problem with a new security mechanism in macOS 10.15.4 Beta (19E242d).

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1. Update a Mac to macOS 10.15.4 Beta (19E242d)
2. Try to start KeepassXC
3. Observe crash message pop-up

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )
No access to KeepassXC data. An attempt to use another Keepass clone (KeepassX) was not successful ("Unable to open the database. Unsupported KeePass database version.").

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.5.3 -- more information is not available due to the early crash
Revision: REVISION

Libraries:
- LIBS

Operating system: macOS 10.15.4 Beta (19E242d)
CPU architecture: amd64
Kernel: KERNEL

Enabled extensions:
- EXTENSIONS

**Comment by stesser** [comment]
Assigning a new certificate with

```
# codesign --force --deep --sign - /Applications/KeePassXC.app
```

allows to start KeePassXC again. 

I have not tried to identify the reason for the rejection of the certificate delivered with the dmg file. It had worked up to the macOS upgrade today, though, but it fails even on a new installation (from the previously working dmg file), so it appears that a change in macOS is causing the rejection of the certificate delivered with 2.5.3.

**Comment by droidmonkey** [comment]
This was already reported and closed......

It's definitely a macOS issue.

**Comment by jonatan-ivanov** [comment]
@droidmonkey Should not this be recorded as a known issue with the workaround in the Wiki?

**Comment by droidmonkey** [comment]
Check out our pinned issues
