### ISSUE TITLE
Crash when a site has no favicons available

### ISSUE THREAD

**Issue by ubronan** [keepassxreboot/keepassxc#4387]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Just a message that no favicon is present on the site which has non

## Current Behavior
[NOTE]: # ( Tell us what actually happens )
When a favicon does not exist keepass crashes fully, no matter what.
If a favicon is present it keeps running fine.

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )
No favicon on the site is crash

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1. http://fritz.box/
2. https://www.funda.nl/
3. https://www.mijnobvion.nl/Login
4. 
## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION
Revision: REVISION

Libraries:
- LIBS

Operating system: OS
CPU architecture: ARCH
Kernel: KERNEL

Enabled extensions:
- EXTENSIONS

**Comment by droidmonkey** [comment]
What version are you running

**Comment by ubronan** [comment]
2.5.3

**Comment by diggnsaegg** [comment]
Just my 2 cents, as I was googling about downloading fav icons for all my keepassXC entries: I successfully downloaded favicons for all my entries. Of course I have some websites without a favicon and KeePassXC didn't crash :).

Version: 2.5.3 on Windows 10
