### ISSUE TITLE
Use Tab to navigate into an entry until validate OK

### ISSUE THREAD

**Issue by webafrancois** [keepassxreboot/keepassxc#4388]
[TIP]:  # Use Tab to navigate between fields until OK

## Summary
[NOTE]: # I frequently use my keyboard to create a new entry.
Ctrl + N : New entry
Title : I write the title + Tab
login : I replace the default  login if necessary + Tab +  Tab + Tab + Tab 
Space to open the "password generator" + Tab
URL : I write or paste the Url + Tab (icon) + tab (expir.) + Tab (preselect) + Tab (notes) + Tab
an then I'm in the text area and tab make a real tabulation of 20 spaces. I can't exit from that area without the mouse.

## Desired Behavior
[NOTE]: #  I imagine that like a web fom, I can jump to the OK button and validate the entry only with my keyboard.

When I manually click to the "Ok" Button, a pop-up come and ask me to confirm the aleat generate password.

## Possible Solution
[NOTE]: # Like in some web form, Tab is use to navigate between fields.
Like here : https://assistance.ouvaton.coop/index.php?a=add&category=1

**Comment by droidmonkey** [comment]
Handled by #4265
