### ISSUE TITLE
Touch input doesn't work properly on Linux

### ISSUE THREAD

**Issue by countcretinos** [keepassxreboot/keepassxc#4389]
## Expected Behavior
The application would work with touchscreen as with mouse

## Current Behavior
The UI components are unresponsive to touch events

## Steps to Reproduce
Install KeepassXC from Fedora repos and try to use it with a touchscreen

## Debug Info
KeePassXC - VERSION
Revision: REVISION

Operating system: Fedora 31
CPU architecture: x86_64
Kernel: 5.5.5-200.fc31.x86_64

**Comment by droidmonkey** [comment]
Which ui components? Our application is not meant for touch screen use, but we use standard components that react to mouse commands.

**Comment by count-cretinos** [comment]
None :) I cannot activate input fields or press buttons. My assumption would be that whatever UI framework you use, there are no actions registered with touch events (Probably touch events don't register as mouse presses there).

**Comment by droidmonkey** [comment]
Are you using the snap install? Do touch inputs work with all your other applications? We use Qt which has touch support.

**Comment by count-cretinos** [comment]
Yes, no problems with any other application so far. This is a RPM package from Fedora.

**Comment by droidmonkey** [comment]
No that is only if you want to have special behavior for touch. The default for Qt is to convert touch to mouse click and move.

**Comment by countcretinos** [comment]
New test results. Controls and fields do indeed work using a touchscreen except for the following:
- Dragging the window using the title bar doesn't work
- Tapping on input fields doesn't activate on-screen keyboard
- After losing focus the touchscreen doesn't work KeepassXC when refocused

**Comment by droidmonkey** [comment]
Those all sound like problems with your display manager /  OS

**Comment by countcretinos** [comment]
Don't encounter stuff like this with any other app. Anyway, I'll try build KeePassXC and debug with it at some point and then report back.
