### ISSUE TITLE
KeePassHTTP plugin reports out of date version

### ISSUE THREAD

**Issue by ibrokemypie** [keepassxreboot/keepassxc#439]
## Expected Behavior

No error in chromeIpass

## Current Behavior

chromeIpass reports 
`You use an old version of KeePassHttp. 
Please download the latest version from GitHub.`

## Possible Solution

Update keehttp/report latest version

## Context

Somewhat confusing/annoying in the chromeIpass window

## Your Environment

* KeePassXC version/commit used: 76dcfb5ed0c874f6a835ef0347ddf6098b149e9b
* Qt version (e.g. Qt 5.3): 5.8.0
* Compiler (e.g. Clang++3.6.0): libgcrypt 1.7.6?
* Operating System and version: MacOS Sierra

**Comment by TheZ3ro** [comment]
What version of ChromeIPass are you using?
Probably this isn't only a "report to chromeIPass a different version" but also some changes in the protocol

**Comment by ibrokemypie** [comment]
chromeIPass Version:2.8.1
KeePassHttp Version:1.8.4.1

**Comment by widowild1** [comment]
some problem in archlinux

**Comment by joshplus** [comment]
I've also seen this message with Chrome on Ubuntu FWIW.

**Comment by droidmonkey** [comment]
I've fixed this on the 2.1.4 release branch, give it a whirl: https://github.com/keepassxreboot/keepassxc/tree/release/2.1.4

**Comment by RlndVt** [comment]
Slight tangent but I was trying to test it, but the release tool doesn't seem to find the tag, is that something separate that is missing?

```
$ ./release-tool build -v 2.1.4 -p "autotype http"
KeePassXC Release Preparation Helper
Copyright (C) 2017 KeePassXC Team <https://keepassxc.org/>

[ INFO ] Performing basic checks...
[ INFO ] Changing to source directory...
[ ERROR ] Tag '2.1.4' does not exist!
[ INFO ] Checking out original branch...
[ INFO ] Leaving source directory...

```

**Comment by RealOrangeOne** [comment]
@RlndVt 2.1.4 isnt tagged as a release yet, it's just a branch. Once it's actually released and tagged then it'll work, until then you'll have to use the branch name instead (if it supports it?)

**Comment by droidmonkey** [comment]
The release tool is mainly for use to assist with signing releases anf standardizing the process. You just have to build and run it which can be doneby following the build instructions in the wiki.
