### ISSUE TITLE
Remember hardware key position 

### ISSUE THREAD

**Issue by Jeroen2000** [keepassxreboot/keepassxc#4390]
## Desired Behavior

When a slot has been selected by the user, KeepassXC should remember that selection next time the database requires a hardware key in order to get unlocked. This should work on a per password database basis. If the hardware key can be uniquely identified (by its serial number for instance), it would also be possible to do this on a per hardware key basis.

For instance:
- Database 'Bob' will always use slot **1**
- Database 'Alice' will always use slot **2**
- When hardware key 12345 is detected, KeepassXC will default to slot **2**
- When hardware key 678910 is detected KeepassXC will default to slot **1**

## Context

I open multiple databases. For a subset of them, I always have to reselect the 2nd slot because KeepassXC always defaults to the 1st slot. This is not very user friendly and often leads to errors if I forget which slot corresponds to a specific database

**Comment by phoerious** [comment]
This becomes difficult when you have multiple identical keys with different serial numbers (e.g. for backup purposes).

**Comment by Jeroen2000** [comment]
Hi Phoerious,

Would it be possible to just remember the last setting used? (I.e. the last slot used)

**Comment by phoerious** [comment]
Maybe. Need to evaluate what works best.

**Comment by droidmonkey** [comment]
This is implemented
