### ISSUE TITLE
Attribute Sections & Copy from Advanced tab

### ISSUE THREAD

**Issue by CoinPoopy** [keepassxreboot/keepassxc#4391]
[TIP]:  # ( Provide a general summary of the feature in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Summary
Improved organization by using attribute `Sections` for grouping and ability to copy from the `Advanced` tab.

## Desired Behavior
Group attributes with labels (and possibly add icons in the future) to make it easier to manage and faster to copy from the menu and advanced tab.

#### Mockup: Edit
_Section name input & `+` button_
![mockup-Attributes_Edit-1_v2](https://user-images.githubusercontent.com/61665366/75641705-e5f0fb00-5c17-11ea-8e82-69e6ec09f5f3.png)

_New section & Remove/Delete button_
![mockup-Attributes_Edit-2_v2](https://user-images.githubusercontent.com/61665366/75641749-1769c680-5c18-11ea-855b-aa574709ce76.png)

#### Mockup: Copy from Menu
![mockup-Attributes_CopyFromMenu](https://user-images.githubusercontent.com/61665366/75641770-23558880-5c18-11ea-98a6-1c182b8e32b4.png)

#### Mockup: Copy from Advanced tab
![mockup-Attributes_CopyFromAdvancedTab](https://user-images.githubusercontent.com/61665366/75641784-2b152d00-5c18-11ea-9d71-3726e04db2e6.png)

## Context
Having all of the attributes unorganized makes it time-consuming (for long lists) to locate the correct item. Also, eventually being able to copy from the Advanced tab seems like an important UI improvement.

**Comment by droidmonkey** [comment]
I appreciate the mock ups!

This seems to further complicate the UI when editing advanced attributes though. I like the right click copy option in the preview widget!

If we went with a hierarchy structure it would be easier to make it like the groups which is a tree view.

**Comment by CoinPoopy** [comment]
> This seems to further complicate the UI when editing advanced attributes though. I like the right click copy option in the preview widget!

Agreed, wasn't really convinced on my editing UI mockup. As long as we can get a more organized display of the right click + copy option I'm happy ☺️


> If we went with a hierarchy structure it would be easier to make it like the groups which is a tree view. This does not work with the KDBX structure though, you would have to save the attributes with a naming convention like `Section 1||Entry1`

This sounds perfect!

**Comment by droidmonkey** [comment]
This will be taken care of with #8228
