### ISSUE TITLE
2.5.3 on Linux intermittently saying database has changed, intermittently hanging

### ISSUE THREAD

**Issue by BillDietrich** [keepassxreboot/keepassxc#4393]
This seems to have started with the 2.5.3 version, I think:

- Sometimes after I save the database, a dialog will pop up saying something like "database file has changed, want to accept the changes ?"  Nothing else in my system is modifying the database, so this must be KeePass reacting to its own database save.

- Sometimes when I quit out of KeePass and then a few minutes later do a system shutdown, the system says "KeePass is not responding, wait or kill ?".  But KeePass seemed to quit fine when I closed the app.

Both of these are intermittent, I don't see any patterns.

## Debug Info
KeePassXC - Version 2.5.3
Revision: f8c962b

Qt 5.9.5
Debugging mode is disabled.

Operating system: Linux Mint 19.3
CPU architecture: x86_64
Kernel: linux 5.3.0-40-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.1

**Comment by droidmonkey** [comment]
Saving to Dropbox?

**Comment by BillDietrich** [comment]
No, database is on system hard disk.

**Comment by physikerwelt** [comment]
I have a similar problem. Can not save, the database. Even restarting the program does not help, I could only resolve the issue by restarting my entire PC. I am syncing the DB with nextcloud.
Debug info.
```
KeePassXC - Version 2.5.4
Revision: c023bf9

Qt 5.14.2
Debugging mode is disabled.

Operating system: Windows 10 Version 2004
CPU architecture: x86_64
Kernel: winnt 10.0.19536

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.5

**Comment by BillDietrich** [comment]
I haven't seen the "process hung when shutting down" behavior for a while now.  Maybe upgrading to 2.5.4 got rid of that, I don't know.

But I definitely still see (about 50% of the time) that after I save the database, a dialog will pop up saying something like "database file has changed, want to accept the changes ?"

**Comment by physikerwelt** [comment]
I updated to 2.5.4. The situation has improved. KeepassX now crashes from time to time with a cryptic 
![2020-04-23 (3)](https://user-images.githubusercontent.com/2777736/80125517-0d1dd600-8592-11ea-8a03-6c7e483fef23.png)
message, but at least I can restart without having to reboot my PC.

**Comment by droidmonkey** [comment]
@physikerwelt how big is your database file?

**Comment by SowaNMS** [comment]
I have the same issue.
KeePassXC 2.6.2 running on Gentoo
Database is opened via WebDAV on Nextcloud.

KeePassXC freezed after asking "database file has changed, want to accept the changes" doesn't matter whether I click merge or discard.

**Comment by droidmonkey** [comment]
Update to 2.6.6. I am closing this since there is insufficient data to action. If you can collect debug traces or similar then please open a new issue.
