### ISSUE TITLE
Request option to Exit instead of Locking after inactivity

### ISSUE THREAD

**Issue by kevinp2** [keepassxreboot/keepassxc#4395]
## Summary
KeePass on Windows has a feature that is very useful in a multi-user environment.  If an inactivity Lock is specified, there is also an option to Exit the app instead of locking the password database.  See the attached screenshot.

![KeePass options](https://user-images.githubusercontent.com/609677/75796552-76732c80-5d39-11ea-80d9-2fae1201bc2e.png)

## Desired Behavior
Just like the above.  If Lock and Exit are both specified, save the file (if necessary), close it and exit the app.  This will allow Dropbox to propagate any changes and also allow other users to use it safely, by reducing the risk of collision.

## Context
I share the same database across Windows and Mac.  Invariably, people forget to close the database when they no longer need it.  This allows the database to be safely closed for others to use.

**Comment by droidmonkey** [comment]
This has been requested before and we will not be implementing this feature.
