### ISSUE TITLE
Having login issues with several sites which do user or email first

### ISSUE THREAD

**Issue by ubronan** [keepassxreboot/keepassxc#4396]
This far some sites open at a different login way.
First they ask the username or email and then open a new screen where either both or only passwords are to be filled.
Sadly the program seems to not be able to handle these sites.
Even though the info is in the database it can not find the needed info.
Whatever i do it am not able to login with keepassxc on these sites.
I discovered other password managers are also struggling with this new login system ( roboform and lastpass failed as well)
Actually google is one of them as well, i constant have to go into the database and have to copy paste the info manually.
Which is kinda annoying, i admit at first i did not bother me much.
Simply because i hardly ever login to google itself.
I get my emails through thunderbird but once in a while i have to login to set something or block things. Because that maybe once in i think 3 months i did not care. But sadly many others start using this very annoying way to login their products and even have pages where a copy&paste is blocked to make it even worse. For me that is absolute hell, i have a severe short term memory disorder so i need to constant look at what i need to use.
For example a 6 figure confirmation number takes me like 5 to 12 tries get it right. I can not remember these things longer than a second or so.
Its becoming a nightmare to login into sites which makes my life miserable with these so called security extras. Sadly non of them changes these idiot ways and i discovered more and more sites starting to use similar ways to login.
The excuse is more security, but that is of course a farce it has nothing todo with security. Anyway the program constant reports no data found when the site has swicthed to this new login system

**Comment by droidmonkey** [comment]
You need to add the site to the list of "Username only logins" on the browser plugin side. When you are on the login for such a site, the plugin popup window "should" ask you to add this as one of those special sites.
