### ISSUE TITLE
if a note is hidden but empty, do not show cues and options to unhide

### ISSUE THREAD

**Issue by FlorinAndrei** [keepassxreboot/keepassxc#4397]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
I set the app to hide notes by default. It shows the eye button next to, and the dot-dot-dot-dot symbol within all notes.
If a note is empty, the eye button should be grayed out, and the multiple dots should not be shown in the note field.

## Current Behavior
[NOTE]: # ( Tell us what actually happens )
When a note is empty, clicking the eye button does not unlock anything. You click that button and it shows an empty note. It's a little bait-and-switch-y.

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )
If a note is empty, the eye button should be grayed out, and the multiple dots should not be shown in the note field.

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1.
2.
3.

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.5.3
Revision: REVISION

Libraries:
- LIBS

Operating system: macOS Catalina 10.15.3
CPU architecture: ARCH
Kernel: KERNEL

Enabled extensions:
- EXTENSIONS

**Comment by droidmonkey** [comment]
No longer an issue in 2.6.0
