### ISSUE TITLE
Integrate libsecret to enable access to GNOME or KDE keyring

### ISSUE THREAD

**Issue by kwill** [keepassxreboot/keepassxc#440]
[libsecret](https://developer.gnome.org/libsecret/) is a GNU/Linux library used to access the GNOME or KDE keyring, including passwords, SSH keys, GPG certificates and more. Given that KeePassXC stores similar data (passwords), would libsecret integration offer any benefits? Or are the goals of a keyring and a password manager distinct?

* KeePassXC treats the system keyring as a KeePass database via libsecret
* The system treats a KeePassXC database as a keyring via libsecret
* Master passwords for KeePassXC databases are stored in the system keyring, allowing for invisible unlocking when the user is logged in
* ...something else?

**Comment by phoerious** [comment]
I had something like this in mind already. I'll see how we can integration OS keyrings and KeePassXC in the best possible way. We already have ssh-agent integration on the agenda.

**Comment by bugzy** [comment]
Not sure if the following pull request would be worth looking at:
https://github.com/keepassx/keepassx/pull/159
I am not sure that what you have described above is supported in it.

**Comment by Keisial** [comment]
Yes!
I would find useful both 
a) auto-opening if the master key for that file is in the keyring
(note: would need to store it based on database full path, which is fragile. It would require a UI for storing the master password there, too)

b) fetching passwords stored in Keepassxc through libsecret
(would likely need some mapping to determine the keepass location of key foo. This could be done by launching a dialog on first use by the app that instead of requesting the password requests the entry -potentially created at that time-)

**Comment by eNTi** [comment]
I came here with the exact same question.
I'd like the database be able to opened automatically with an unlocked gnome-keyring.

**Comment by eppelmania** [comment]
I am looking for the same feature. In the past I've worked with several workarounds, but i would prefer a clean solution.

**Comment by rugk** [comment]
Yeah, good idea. See https://github.com/keepassxreboot/keepassxc/issues/753 for my use case/explanation.

**Comment by jleclanche** [comment]
Moving my comment from #1109:

On linux: What is a system keyring? GNOME Keyring and KWallet are system keyrings. For standardization purposes, they both implement the [Secret Service API](https://specifications.freedesktop.org/secret-service/), which is a DBus based API.

The meat of it:
- The secret service handles secure storage of secrets at rest
- The service is able to [open sessions over DBus](https://specifications.freedesktop.org/secret-service/ch06.html)
- In sessions, clients are able to [securely ask and receive secrets](https://specifications.freedesktop.org/secret-service/ch07.html)
- The service [may require items to be unlocked before being accessed](https://specifications.freedesktop.org/secret-service/ch08.html).

If KeepassXC wanted to implement this, most of the work would be in adapting it to the DBus API, as its model is already essentially fully implemented. It would also probably be worth keeping separate to the KeepassXC core (some kind of plugin? Enable on demand?).
Another hard bit to answer for would be: How do items map to the ones advertised by the system keyring? Maybe they don't, maybe there's a special database (or table in an existing database) for the system stuff.

**Comment by bugzy** [comment]
For those merely looking to open keepassxc with kwallet, there is a small tutorial here:

https://blog.nixserve.net/auto-unlocking-keepass-database-on-plasma-5-desktop-login/

**Comment by kwill** [comment]
It seems like the answer to the original, broad question is, yes, each of these use cases is feasible and in-scope for this KeePassXC:

1. Access and modify libsecret keyrings with KPXC interface
2. Make KPXC databases accessible via libsecret/DBus
3. Store KXPC passwords in (libsecret) system keyring
4. Unlock KXPC databases on login (using 3)

These use cases are each quite different though, so I'm not sure they can be tracked in a single ticket. I'm happy to close this one and create individual tickets for each user story?

**Comment by eNTi** [comment]
i don't see the point in 3. and how it relates to 4.?

**Comment by TheElixZammuto** [comment]
I think that point n.3 stands for storing database's  password into the
system keyring. So on logon kpxc can read it and autounlock the database
(point 4)

Il 15 gen 2018 2:44 PM, "eNTi" <notifications@github.com> ha scritto:

**Comment by kolya-ay** [comment]
From my point of view it would be invaluable cool if keepassxc can completely replace KWallet replicating its DBus API or/and API of sercret-service. It seems that [KWallet is stagnating](https://mail.kde.org/pipermail/plasma-devel/2016-July/055641.html) quite a while (correct me KDE gurus if I'm wrong). So KXPC could become its drop-in replacement.

Regarding p.3 there is [qtkeychain](https://github.com/frankosterfeld/qtkeychain) library that might be useful. I picked it up form aforementioned tread.

**Comment by kwill** [comment]
Created tickets as described:

* #1402 Access system keyring data from KPXC UI
* #1403 Access KPXC data from system keyring UI
* #1404 Store KPXC unlock passphrases in system keyring
* #1405 Given #1404, support autounlocking on login (including programmatic access)

**Comment by ArchangeGabriel** [comment]
In which of this issues would implementing `org.freedesktop.secrets` so that application using `libsecret` could store and retrieve password within KPXC?

**Comment by jleclanche** [comment]
That'd be #1403.

**Comment by secretmango** [comment]
A workaround solution to at least automatically unlock a KeepassXC storage using KWallet (I am sure something similar exists for GNOME keyring)

1. Open "KWalletManager"
2. If not existent, create a new folder called "Passwords" by clicking on the clear area and then "New"
3. Open that folder, in here you find multiple folders, one is called "Passwords" in your systems language
4. Right click the "Passwords" subfolder and press "new"
5. Name the entry for example "Keepass", click on the entry and "show content", enter your Keepass Password
6. Create an Appstarter for quick-opening your password storage!

You can create an App Desktop Entry like this, open your Terminal and enter:

When using KeepassXC Flatpak:

```
cat > ~/.local/share/applications/keepassxc-unlock.desktop <<EOF
[Desktop Entry]
Name=Keepass-unlock
Comment=Unlock your KeepassXC vault
Exec=kwallet-query -r KeepassXC kdewallet | /usr/bin/flatpak run --branch=stable --arch=x86_64 --command=keepassxc --file-forwarding org.keepassxc.KeePassXC --pw-stdin ~/passwords.kdbx
Icon=emblem-encrypted-unlocked
Type=Application
EOF
```

When using a native package:

```
cat > ~/.local/share/applications/keepassxc-unlock.desktop <<EOF
[Desktop Entry]
Name=Keepass-unlock
Comment=Unlock your KeepassXC vault
Exec=kwallet-query -r KeepassXC kdewallet | keepassxc --pw-stdin ~/passwords.kdbx
Icon=emblem-encrypted-unlocked
Type=Application
EOF
```
*(I am writing this to many top level search results of "Keepassxc kwallet" so dont wonder. This is not documented at all it seems)*

**Comment by ricardobranco777** [comment]
Avoid GNOME keyring like the plague.

https://github.com/sungjungk/keyring_crack

**Comment by michaelk83** [comment]
Lol, that's not a crack, that's just reading all the secrets through the keyring's public API. The fact that there's no isolation between apps, and every app can read every other app's secrets (_of the same user_) is a known limitation of Linux. Implementing such isolation is nearly impossible without deeper OS support. This isn't limited to GNOME Keyring.

This is why you should keep your keyring locked until needed.

**Comment by rugk** [comment]
Yeah I guess (read in: hope) flatpak has a isolation for home keyring but I guess even that may still be missing. It's a good choice to be implemented there though.
