### ISSUE TITLE
Clear history doesnt seem to work on KPXC 2.5.1 on Expandrive mounted keystore, Windows 2016 server

### ISSUE THREAD

**Issue by MattWeatherford** [keepassxreboot/keepassxc#4401]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Expected Behavior
[NOTE]: # I expect to open KPXC and see an empty "Recent databases" list below after clearing via Databases-> Recent Databases -> clear history
I dont see the last database that I did open either, which should take its place.  

## Current Behavior
[NOTE]: #  I see an old database that I have attempted several times to clear via Databases-> Recent Databases -> clear history

## Possible Solution
[NOTE]: #  
Is there some length limit ? My database resides in y:\Keys\Kpxv2\Matts-kpxv2-database-2020.kxdb  - that doesnt seem too long. 
Note that my database file sits on a file share mounted via "expandrive" from a cloud provider

## Steps to Reproduce
oni Windows server 2016
Put 2 key file databases on a cloud drive such as google or dropbox
mount toa drive letter via expandrive (free trial available)
open keyfile1 database
close everything
open again, clear the recent databases 
open file2
close everything
open KPXC - you will see keyfile1 in the list and not keyfile2

## Context
[NOTE]: #  Its just annoying, not a show stopper

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.5.1
Revision: 0fd8836

Qt 5.13.1
Debugging mode is disabled.

Operating system: Windows Server 2016 (10.0)
CPU architecture: x86_64
Kernel: winnt 10.0.17763

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.5

**Comment by droidmonkey** [comment]
Can you add screenshots of your repetition steps so we can be sure of your issue
