### ISSUE TITLE
White GUI after some time

### ISSUE THREAD

**Issue by superwinni2** [keepassxreboot/keepassxc#4404]
## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
The GUI should work as normal

## Current Behavior
[NOTE]: # ( Tell us what actually happens )
The GUI is has a "white out". You still can click the menu bar on top and you see how the coursor switches (like if the GUI is working). But you only see white. 
If you try to minimize he application it doesn't go to the icon on bommen right. It just minimize.
If you close the Window GUI the whole Application is goining to shut down. You need to start it manually again. After this the behavior is normal till the screen whites out again.

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.5.3
Revision: f8c962b

Qt 5.13.2
Diagnosemodus ist deaktiviert.

Betriebssystem: Windows 10 (10.0)
CPU-Architektur: x86_64
Kernel: winnt 10.0.18363

Aktivierte Erweiterungen:
- Auto-Type
- Browser-Integration
- SSH-Agent
- KeeShare (bestätigtes und unbestätigtes Teilen)
- YubiKey

Kryptographische Bibliotheken:
 libgcrypt 1.8.5

**Comment by droidmonkey** [comment]
This is a duplicate issue.
