### ISSUE TITLE
Darkmode for Windows 10

### ISSUE THREAD

**Issue by F3000** [keepassxreboot/keepassxc#4405]
is this already implemented ? 

on OS X and Linux I can use it but under Windows I can’t find any setting for that . 

Thanks for help

**Comment by phoerious** [comment]
Qt does not support Windows dark mode, but we have a custom theme coming up in 2.6 that comes with one.

**Comment by F3000** [comment]
@phoerious
Nice to hear . When we can expect 2.6 ? In the Next half year ?

**Comment by droidmonkey** [comment]
In the next month or so

**Comment by F3000** [comment]
Do you have a overview with all planned features for that release ?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by droidmonkey** [comment]
Just look at our pull requests and release information. We tag everything with the appropriate release tag.
