### ISSUE TITLE
Notes should be hidden in entry view when hidden from preview panel

### ISSUE THREAD

**Issue by FlorinAndrei** [keepassxreboot/keepassxc#4412]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Let's say a note is hidden - meaning, you click the entry and its note is not visible unless you click the eye symbol. Then the contents of the note should not be visible anywhere.

## Current Behavior
[NOTE]: # ( Tell us what actually happens )
The contents of the note are visible in the Notes column in the list of entries.

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )
Don't show the note in the Notes column.

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1.
2.
3.

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.5.3
Revision: REVISION

Libraries:
- LIBS

Operating system: Windows 10
CPU architecture: ARCH
Kernel: KERNEL

Enabled extensions:
- EXTENSIONS

**Comment by droidmonkey** [comment]
Good point!
