### ISSUE TITLE
Passwords of kdbx dbs opened via AutoOpen are leaked when databases are locked

### ISSUE THREAD

**Issue by heldchen** [keepassxreboot/keepassxc#4414]
# Expected Behavior
when the databases are locked (either manually via Tools -> Lock Databases or automatically after the idle timeout), the passwords should be cleared for all locked databases.

## Current Behavior
when the databases are locked (either manually via Tools -> Lock Databases or automatically after the idle timeout), the passwords of the autoopened databases are not cleared - any secondary, inactive database that was opened through AutoOpen feature has its password *pre-entered*, so it can be viewed and/or used by anyone gaining access to the computer.

## Steps to Reproduce
1. create 3 database (master, slave1, slave2)
2. create autoopen entries on master for slave1 & slave2
3. close all databases (Ctr+W)
4. open & unlock master database
5. ensure that slave1 & slave2 are opened and unlocked, but **do not click their tabs**
6. lock databases via Tools > Lock databases (Ctr+L)
7. click on slave1 tab. while the database is locked, its password is prefilled and even viewable via the eye-button
8. click on slave2 tab. while the database is locked, its password is prefilled and even viewable via the eye-button

this password leak only occurs on the first open (not first unlock!) of each slave database. i.e. after a second unlock & lock of the main database, the slave passwords are cleared correctly.

## Context
autoopen feature with multiple slave databases.

## Debug Info
KeePassXC - Version 2.5.3
Revision: f8c962b

Qt 5.12.4
Debugging mode is disabled.

Operating system: Ubuntu 19.10
CPU architecture: x86_64
Kernel: linux 5.4.0-8-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.4

**Comment by droidmonkey** [comment]
This may be fixed already in develop. Will test tonight.

**Comment by heldchen** [comment]
thanks for the quick reply, Jonathan. I can confirm that this is fixed in https://snapshot.keepassxc.org/latest/KeePassXC-SNAPSHOT-x86_64.AppImage  (love the new icons, btw :))

any chance on pushing a fix to the ubuntu ppa?

**Comment by droidmonkey** [comment]
We are going to be release 2.6.0 within the month. You are free to use the snapshot until then. Thank you for the feedback!
