### ISSUE TITLE
Challenge-Response recovery utility documentation

### ISSUE THREAD

**Issue by ghost** [keepassxreboot/keepassxc#4415]
Can you add documentation about [Challenge-Response recovery utility](https://github.com/keepassxreboot/keepassxc/tree/develop/utils/keepassxc-cr-recovery) (See #1734)  to official docs or Github wiki (I think this would look good in the same doc section where there's information about using Yubikey)

People don't have to buy a second hardware auth device when they can decrypt the db with secret token.

**Comment by countcretinos** [comment]
And since code > words, here's a [PR](https://github.com/keepassxreboot/keepassxreboot.github.io/pull/68).
