### ISSUE TITLE
Snap install: write configuration to common directory instead of current version directory

### ISSUE THREAD

**Issue by syphr42** [keepassxreboot/keepassxc#4416]
**Edited to change proposal from using `$XDG_CONFIG_HOME` to using the snap common directory.**

## Summary
When installed on Ubuntu using a deb, the config file is written to `$XDG_CONFIG_HOME` as expected. However, when installed via snap, the file lands in a symlinked directory under `~/snap/keepassxc/current` (a sandbox area) with a similar structure to `$XDG_CONFIG_HOME`.

## Desired Behavior
Write the configuration to the snap common directory instead.

## Possible Solution
Using ~/snap/keepassxc/common would allow the user to more easily control configuration files while maintaining the snap sandbox.

## Context
I version control my configuration so my dotfiles are stored in Git. Because the configuration for KeePassXC is stored in a directory under a symlink, it can't be directly added to Git. Moreover, the underlying directory changes with snap upgrades so I can't add that to Git either. The common directory would solve this problem.

**Comment by droidmonkey** [comment]
People like the fact that the snap version cannot access most of their files. The sandbox is a feature, not a bug. I do not agree with this proposal.

**Comment by syphr42** [comment]
I think that is why the "personal-files" feature was added to snapd. It allows limited access while still maintaining the sandbox. Not being able to manage configuration certainly limits the usefulness of snaps.

**Comment by syphr42** [comment]
There is another alternative without leaving snap's filesystem. Currently the keepassxc.ini file resides in the following location for me: 

~/snap/keepassxc/687/.config/keepassxc/keepassxc.ini

That "687" is what changes and causes problems for version control. However, there is also a directory here:

~/snap/keepassxc/common

which contains a ".cache" directory. Perhaps the configuration could be written there instead of the version-specific folder that changes. This would solve my problem and not write anything outside the sandbox. Something like this:

~/snap/keepassxc/common/.config/keepassxc/keepassxc.ini

I can look into using AppImage or just use the deb. Since Ubuntu is embracing snaps, I was attempting to start using them as well.

**Comment by droidmonkey** [comment]
No you need to point to ~/snap/keepassxc/current/

**Comment by syphr42** [comment]
The use of the symlink at ~/snap/keepassxc/current is problematic and the original motivation for this proposal.

Perhaps this can issue can change to a proposal to write the configuration in the common directory which also solves my problem.

**Comment by droidmonkey** [comment]
Why is that problematic

**Comment by syphr42** [comment]
I version control my dotfiles/configuration with Git. Because the configuration for KeePassXC (when installed via snap) is in a directory that is only accessible either by symlink or under a constantly changing name, I am unable to manage the ini file in the same way as other app configuration files.

**Comment by droidmonkey** [comment]
We are not going to expend time to fix this, use the flatpak verison.
