### ISSUE TITLE
Add "raNdom caPitaliZation" and/or "RANDOM Capitalization" to passphrase (diceware) generator

### ISSUE THREAD

**Issue by shaneknysh** [keepassxreboot/keepassxc#4417]
Add the ability to have random capitalization on generated passphrases.

This may be mentioned in #4209

## Summary
The current passphrase generator supports UPPER, lower, and Title case. 

## Desired Behavior
There are two ways to consider random capitalization.
1. Capitalize random letters in a passphrase
rigiDness thRoat aBANdoned sprouT

2. Apply a random capitalization to each word.
rigidness Throat ABANDONED Sprout

## Possible Solution
Adding this feature should be relatively simple (based on my experience working with the code base setting up a development environment on windows was the hardest part) the tricky part will be creating a simple and effective panel to use these features will be a challenge.

Adding raNdOm to the existing list would be simple then randomly capitalize at least one letter in each passphrase word.

Adding random case to each word gets more complicated because decisions need to be made on whether to add the ability to select which capitalization type to include - particularly if random should be included. I can see a significant number of users wanting to only have lower, upper, and title included. I don't want to over complicate the dialog.

## Context
I am proposing this is I want the feature for my own use. Adding either of these adds a small increase in entropy for passphrases.

**Comment by droidmonkey** [comment]
We are not introducing any more features to the pass phrase generator. The whole point of a passphrase is to generate passwords that humans can remember using words. Introducing random changes totally defeats that purpose.

**Comment by shaneknysh** [comment]
okay I'll just keep it in my own fork.
