### ISSUE TITLE
Improvement: Select least recently accessed entries

### ISSUE THREAD

**Issue by Zugschlus** [keepassxreboot/keepassxc#4419]
Hi,

first let me congratulate you on the keepassx reboot. keepassxc is vastly more useful than keepassx (a good tool in itself) has ever been. I use it daily and love it.

To clean out my past password databases, I'd like to be able to select (or sort) entries by their last access date (which is already present, to my huge and positive surprise). That way, I could review entries that haven't been used in years and decide to remove them.

Greetings
Marc

**Comment by droidmonkey** [comment]
Unfortunately the access time is exactly equivalent to the last modified time. I would not use it as a basis for unused entries.

**Comment by t214c** [comment]
Maybe we can store access time automatically as an attribute?
