### ISSUE TITLE
Improvement: Multiple Database Handling

### ISSUE THREAD

**Issue by Zugschlus** [keepassxreboot/keepassxc#4420]
Hi,

thanks again for providing keepassxc. I understand that this feature request is probably a very big change and that there are feature requests that are way more important. I'm filing it anyway.

I'd like to have the possibility to have multiple databases open at the same time and to be able to easily move entries from one database to the other.

That way, I could clean out ancient password entries to a different database without having to completely delete them or keeping a backup of my entire database, which might not be desireable¹.

Greetings
Marc

¹ If I keep backups of my main database, I'd need to keep track of them to be able to change their keys or passphrase in case that it gets compromised. Changing the key on the master copy is easy, but that doesnt do anything if you still have backups with the old key around.

**Comment by droidmonkey** [comment]
You can already do this today. Open both databases and drag the entries from one tab to another. Make sure you drop them into a group.
