### ISSUE TITLE
Find and Delete favicon from entries

### ISSUE THREAD

**Issue by adudek16** [keepassxreboot/keepassxc#4423]
## Summary
Find any and all entries that make use of favicon and either modify or delete references to using faveicon

## Desired Behavior
Find which entries are using favicon and delete the reference to download favicon for that entry(ies)

## Possible Solution
Not sure if this is possible

## Context
on VPN, I may not have full internet access, when launching keypassxc, it takes a long time to open. On a Mac, icon just bounces for a long time, once I disconnect from the vpn, keepassxc opens.

**Comment by droidmonkey** [comment]
When you delete a custom icon it will ask you if you want to remove from all entries. This is already a thing.
