### ISSUE TITLE
General Memory Error (Windows)

### ISSUE THREAD

**Issue by express-oh** [keepassxreboot/keepassxc#4424]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Application should close normally without additional dialogue.

## Current Behavior
[NOTE]: # ( Tell us what actually happens )
Occasionally, when closing application with database open, application hangs, crashes, and gives dialogue for a memory error (memory cannot be read). Error appears similar to one reported [here](https://github.com/keepassxreboot/keepassxc/issues/4005).

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )
Unknown (refer to 'Context')

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1. Open application
2. Unlock database
3. Exit application with database open

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )
I have little experience with this type of application in particular, but I have a suspicion the case may be that it is not playing nicely with Windows 10's 'controlled folder access'. Other than protecting access to essential folders, it also blocks access to sections of memory Windows considers most sensitive.

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.5.3
Revision: f8c962b

Libraries:
-  libgcrypt 1.8.5

Operating system: Windows 10
CPU architecture: AMD64

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

**Comment by droidmonkey** [comment]
This is fixed already in develop will be out in 2.6.0

**Comment by express-oh** [comment]
Thanks, appreciate the update.
