### ISSUE TITLE
[Qt Bugs] MacOS Multi-monitor bugs

### ISSUE THREAD

**Issue by stefansundin** [keepassxreboot/keepassxc#4426]
I sometimes use two monitors on Mac. A MacBook Pro with a 2880x1800 display, and an 1920x1080 external display (non-Apple brand).

When I drag the KeePassXC window from my external monitor to the MacBook display, the content in the window show up smaller.

![keepassxc1](https://user-images.githubusercontent.com/1991151/76382107-dc048180-6314-11ea-8846-e842aae90638.png)

When I stop dragging and then hover the mouse over the contents, everything in the window goes black, and when my mouse cursor hovers parts of the window (e.g. toolbar buttons), they become visible. Sometimes you have to click too. It's a bit annoying to get everything to show up.

Then when I drag it back, this happens:

![keepassxc2](https://user-images.githubusercontent.com/1991151/76382228-37cf0a80-6315-11ea-9f9d-0009652aed27.png)

So the opposite effect. You can see that not all toolbar buttons are visible because I had not hovered the mouse cursor over all of them yet.

Lastly, windows sometimes pop up on the wrong monitor, and with the wrong size. I can't remember what popup this was.

![keepassxc3](https://user-images.githubusercontent.com/1991151/76382390-d52a3e80-6315-11ea-95de-f1acab86c65f.png)

## Debug Info
KeePassXC - Version 2.5.3
Revision: f8c962b

Qt 5.14.0
Debugging mode is disabled.

Operating system: macOS 10.15
CPU architecture: x86_64
Kernel: darwin 19.3.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
 libgcrypt 1.8.5

**Comment by stefansundin** [comment]
This is probably related to:
- https://github.com/keepassxreboot/keepassxc/issues/2815
- https://github.com/keepassxreboot/keepassxc/issues/2401

Sorry I didn't find them before opening this.

**Comment by droidmonkey** [comment]
These are 100% Qt issues, unfortunately. Please follow the tips in the other issues you linked to above to help mitigate the problems.
