### ISSUE TITLE
Icons are barely visible on Fedora 31.

### ISSUE THREAD

**Issue by mclucario** [keepassxreboot/keepassxc#4427]
The icons are barely visible for whatever reason. I might not be the first one mentioning this issue but I couldn't find another issue.
![image](https://user-images.githubusercontent.com/10533763/76404817-6ede0400-6387-11ea-97ac-968b4a557815.png)

![image](https://user-images.githubusercontent.com/10533763/76404828-730a2180-6387-11ea-9134-42ea00b73a8e.png)

## Expected Behavior
The Icons should be visible.

## Current Behavior
The Icons arent visible.

## Possible Solution
Add icons which are useable for dark and light themes.

## Steps to Reproduce
1. Install Fedora 31 on a Computer with KeePass XC
2. Start KeePass XC

## Context
I just cant see the icons and its hard to quickly generate new passwords if needed.

## Debug Info
KeePassXC - Version 2.5.3
Revision: f8c962b

Libraries:
 libgcrypt 1.8.5

Operating system: Fedora 31 (Workstation Edition)
CPU architecture: x86_64
Kernel: linux 5.5.7-200.fc31.x86_64

Enabled extensions:
- Auto-Type
- Browser-Integration
- SSH-Agent
- KeeShare (bestätigtes und unbestätigtes Teilen)
- YubiKey
- Secret-Service-Integration

**Comment by phoerious** [comment]
I don't know what is causing this, but 2.6 will definitely fix it.

**Comment by mclucario** [comment]
> I don't know what is causing this, but 2.6 will definitely fix it.

Is there an ETA on when 2.6 is coming?

**Comment by phoerious** [comment]
Soon-ish.

**Comment by dhalucario** [comment]
Update got pushed out for me.
