### ISSUE TITLE
crash after clone and then saving a new entry

### ISSUE THREAD

**Issue by gridstorm** [keepassxreboot/keepassxc#443]
## Expected Behavior

Cloning an existing item and then editing that item should allow the database to be saved with a new modified entry.

## Current Behavior

Duplicating an existing item and then editing/changing the information in that item followed by a database save, causes the application to crash. After reopening the database, the cloned entry is saved but the modified item information is not saved.

## Steps to Reproduce (for bugs)

1. Open an existing database that contains items
2. clone an item
3. edit the information associated with the newly cloned item
4. save the database

## Context

Unable to clone and edit item. Must save and exit the database and then reopen the database.  I was not able to reproduce this issue with KeePassX version 2.0.3

## Your Environment

* KeePassXC Version 2.1.3 
* Qt version 5.8
* Operating System and version: macOS 10.12.3

**Comment by louib** [comment]
@gridstorm was not able to reproduce this one. Anything in the cloned entry except title username and password?

**Comment by gridstorm** [comment]
It doesn't appear to matter which fields contain data, however I am only able to recreate this in my daily working database which has multi layered subgroups .  I have recreated an empty database with sub groups and cannot reproduce the crash, but I can always reproduce the crash in my working database.  How can I generate more debugging information?

Below is the macos error report.

`Process:               KeePassXC [850]
Path:                  /Applications/KeePassXC.app/Contents/MacOS/KeePassXC
Identifier:            org.keepassx.keepassxc
Version:               2.1.4 (2.1.4)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           KeePassXC [850]
User ID:               502

Date/Time:             2017-05-01 12:25:12.050 -0400
OS Version:            Mac OS X 10.12.4 (16E195)
Report Version:        12
Anonymous UUID:        CCBB51B4-BF72-649B-1515-6331C92DF824


Time Awake Since Boot: 2700 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       EXC_I386_GPFLT
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [0]
`

**Comment by louib** [comment]
@gridstorm Is the crash happening with all of the entries of your working database? Was your database migrated from a keepass1 database? How deep is the folder nesting? Which options do you check when cloning? 

You can probably obtain more debugging info if you build the project with the `DEBUG` flag (`-DCMAKE_BUILD_TYPE=Debug`)

**Comment by dossy** [comment]
@louib - You closed this issue but there's no commit that references this issue as fixing it - why?  I think this crash is still reproducible in v2.2.4.

**Comment by louib** [comment]
@gridstorm Do you still have this problem with the latest version (2.3.1)?

**Comment by droidmonkey** [comment]
I cloned several entries without issue recently.

**Comment by RostKost** [comment]
## Current Behavior
App crushed in case of edit cloned entry.
After reopening the database, the cloned entry saved but results of the edit is **not** saved.
DB located in the folder which sync with Google Drive by Google Drive File Stream client Version: 29.1.15.303
Outside of this folder issue not reproduced.

## Steps to Reproduce
1. Open DB
2. Select an entry in the group and clone it
3. Edit cloned entry. Change part of the Title, Username, Password, Notes fields
4. Press OK button to close entry 
5. App crush immediately after press OK and reopened. 

## Possible Solution
Pause syncing with Google Drive during the edit entry
May be useful to test to make a pause or some delay on save the change inside the app. 


## Debug Info
KeePassXC - Version 2.3.4
Revision: 6fe821c

Libraries:
- Qt 5.9.3
- libgcrypt 1.8.2

Operating system: macOS High Sierra (10.13)
CPU architecture: x86_64
Kernel: darwin 17.7.0

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey
