### ISSUE TITLE
Add option to add multiple URLs

### ISSUE THREAD

**Issue by mDfRg** [keepassxreboot/keepassxc#4430]
## Desired Behavior
Please add an option in "edit entry" dialog to add multiple URLs, possibly by adding plus ("+") sign which would spawn more URL boxes (URL 1, URL 2... etc.). Alternatively, there might be one box to add URL, and the list of added URLs will be listed in some box below 'Notes' section.

## Context
I use KeepassXC with firefox addon to login to my bank account. Unfortunately, depending on how I land on the login page, the URL may differ. In other words, if I login directly (by visiting bank's page and clicking "login") there will be different url than if I got redirected from online shopping page. Because of this, autofill function of KeePassXC addon will not always work and I have to paste credentials manually (I am aware of Ctrl+Shift+V).

**Comment by droidmonkey** [comment]
We already have this option in the current released version. It is under the browser integration tab when editing an entry.

**Comment by Stephan-P** [comment]
Please consider re-opening this request
1. Documentation: This "how-to add multiple urls" is quite hard to find
2. Implementation: The actual manner at which multiple urls can be added seems to me a bit far fetched and non-intuitive
3. Wouldn't it be more logical to allow entering multiple urls using a separator character, e.g. semicolon, or would this not stroke with kdbx specs?

**Comment by droidmonkey** [comment]
1. Agree, but that is being done already.
2. Disagree, it can't be any easier (both UI and Programming are dead simple). The only reason multiple URL's is needed is for the browser integration. No other plugin requires that feature. That is why it is added to that tab.
3. No, that breaks opening by URL
