### ISSUE TITLE
Improve Auto-Type when using AutoOpen

### ISSUE THREAD

**Issue by tyllmoritz** [keepassxreboot/keepassxc#4432]
## Summary
When using Auto-Type I am asked to unlock the Database in the currently active tab.
I have a Main-Database (with folder AutoOpen) and a Child-Database (which is opened automatically). I do not know the Child-Databases password.
When the current Tab is the Child-Database, I have to switch to the Main-Database first.
When the current Tab is the Main-Database, KeePassXC first tells me, that the Entry was not found, then opens the Child-Database. Using Auto-Type again succeeds.
![KeePassXC_AutoOpen_and_Autotype](https://user-images.githubusercontent.com/5952186/76544721-cfa13580-6488-11ea-9620-1522d3850059.gif)

## Desired Behavior
1. For Databases, which were opened using Auto-Open, ask for the Password of the Main-Database instead.
2. Open all Child-Databases before searching for Auto-Type-Entries.

## Possible Solution
1. when locking Databases, which were opened with AutoOpen, switch the active Tab to the Main-Database.
2. Wait with AutoType until after AutoOpen finished

## Partial Solution 2
#2322, Case 2 would help a with manually switching to the Main-Database.

**Comment by tyllmoritz** [comment]
tested on Version 2.5.1, AppImage, CentOS7
https://github.com/keepassxreboot/keepassxc/issues/3728#issuecomment-559558699

I think it's still the same on 2.5.3.

**Comment by droidmonkey** [comment]
This will be solved with #2322 no need for a duplicate issue.
