### ISSUE TITLE
The UI won't open after PC locks profile if window is minimized to tray

### ISSUE THREAD

**Issue by muchqs** [keepassxreboot/keepassxc#4435]
## Expected Behavior
Click on the tray icon, KeepassXC window should open.

## Current Behavior
When I click on the tray icon, the main window doesn't open, nothing happens on screen at all. I have to force shutdown the process and relaunch it to get it to work. This only seems to happen if the main window is minimized to tray and the computer starts screensaver which locks the Windows profile and locks KeepassXC database.

## Possible Solution
I don't know, but this did not happen before, maybe 2 versions or so ago.

## Steps to Reproduce
1. Minimize KeepassXC to tray.
2. Let my computer idle for 10 min so screensaver starts and profile + database gets locked.
3. Relog into Windows and try to open KeepassXC window.

## Context
Please see above.

## Debug Info
KeePassXC - Version 2.5.3
Revision: f8c962b

Qt 5.13.2
Debugging mode is disabled.

Operating system: Windows 10 (10.0)
CPU architecture: x86_64
Kernel: winnt 10.0.18362

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.5

Sorry for off-topic but why does debug info say SSH Agent enabled, I don't have it checked in settings.

Thanks.

**Comment by droidmonkey** [comment]
Duplicate issue. This is addressed already in 2.6.0 (develop branch)

**Comment by droidmonkey** [comment]
The debug info just shows which extensions have been compiled into the application.
