### ISSUE TITLE
Copy-paste doesn't work

### ISSUE THREAD

**Issue by countcretinos** [keepassxreboot/keepassxc#4437]
## Expected Behavior
Copy, or at least paste should work

## Current Behavior
Copy nor paste works

## Debug Info
KeePassXC - 2.5.3

Operating system: Fedora Workstation 31
CPU architecture: x86_64
Kernel: Linux 5.5.7-200.fc31.x86_64 #1 SMP Fri Feb 28 17:18:37 UTC 2020

**Comment by droidmonkey** [comment]
Gonna need more details here.

**Comment by countcretinos** [comment]
Sorry 'bout that :) Copy-paste was not working for in input fields but now everything is magically OK! :tada:
