### ISSUE TITLE
SECURITY: AutoOpen database gets visible password after being locked

### ISSUE THREAD

**Issue by llucax** [keepassxreboot/keepassxc#4439]
I have a DB configured with a couple of `AutoOpen` DBs. I have a timeout for DBs to be locked again, and it's also done when the laptop is suspended or locked.

After the laptop was suspended, the main DB was locked as well as the AutoOpen DBs, but the AutoOpen DBs had the password filled in! I could even see the password when clicking on the eye. After going to another DB tab and coming back to the DB with the pre-filled password, the password was cleared.

##  Expected Behavior
AutoOpen DBs should get an empty password field after the DB is locked.

## Current Behavior

After the laptop was suspended, the main DB was locked as well as the AutoOpen DBs, but the AutoOpen DBs had the password filled in! I could even see the password when clicking on the eye. After going to another DB tab and coming back to the DB with the pre-filled password, the password was cleared.

## Possible Solution
Make sure the program always clear passwords from user input.

## Steps to Reproduce
I don't have time right now to try to reproduce this with a bogus example DB, but I will try to do so if nobody did it yet.

## Context
This is a very serious bug as the whole point of getting DBs autocked is that if my laptop get stolen or similar, other people don't have access to my passwords, but if the password is pre-filled, is like no having a password at all.

## Debug Info
KeePassXC - Version 2.5.3
Revision: f8c962b
Distribution: AppImage

Qt 5.12.6
Debugging mode is disabled.

Operating system: Debian GNU/Linux bullseye/sid
CPU architecture: x86_64
Kernel: linux 5.4.0-4-amd64

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.1

**Comment by droidmonkey** [comment]
Literal duplicate of #4414

**Comment by llucax** [comment]
Sorry about that, I did a search for autoopen and didn't find #4414, probably because it is already opened.

**Comment by droidmonkey** [comment]
When you create a new issue, similar issues will appear below the title you create.

**Comment by droidmonkey** [comment]
erg... nvm looks like GitHub changed that feature to be FAR less visible and useful.......

![image](https://user-images.githubusercontent.com/2809491/76683529-2454c580-65db-11ea-82e1-1c73018d2b01.png)
