### ISSUE TITLE
Global Auto-Type Hot Key bug

### ISSUE THREAD

**Issue by vlenzer** [keepassxreboot/keepassxc#444]
Since some days my KeePass XC 2.1.3 has a strange bug. Didn't change anything before the bug appeared.

After every reboot the global Auto-Type hot key doesn't work anymore. When going to settings the field with the relevant key is highlighted in red. After switching the key it works again till next reboot.
I'm not able to choose same key as it gets highlighted red again.

- KeePass XC 2.1.3
- Qt 5.8.0
- libgcrypt 1.6.1
- Linux Mint 18.1 Cinnamon 64-bit

**Comment by droidmonkey** [comment]
Can anyone else confirm that this is an issue? It seems to me that your configuration file is becoming corrupt/deleted/wiped somehow.

**Comment by TheZ3ro** [comment]
Do you properly close KeePassXC after changing settings (and before reboot) ?
