### ISSUE TITLE
KeePassXC crashing when switching tab by Ctrl+Tab during database decryption

### ISSUE THREAD

**Issue by morozdan2003** [keepassxreboot/keepassxc#4440]
## Expected Behavior
Possibly, KeePassXC should decrypt database in background mode and switch to the second tab.

## Current Behavior
If we enter required credentals, press Enter and then Ctrl+Tab for switching tab, we get crash

![Screenshot of error message appearing](https://user-images.githubusercontent.com/52320050/76688680-1be2a600-6640-11ea-9f15-e61e580e50e4.png)

## Steps to Reproduce
1. Open database file
2. Enter required credentals
3. Quickly press Enter then Ctrl+Tab
4. Error message will appear immediately

## Context
Nothing special, tested on my 2 databases, and I have the same result.
Program crashes only when database decrypts successfully.

## Debug Info
```
KeePassXC - Версия 2.5.3
Ревизия: f8c962b

Qt 5.13.2
Режим отладки выключен.

Операционная система: Windows 10 (10.0)
Архитектура ЦП: x86_64
Ядро: winnt 10.0.18363

Включённые расширения:
- Автоввод
- Интеграция с браузером
- SSH-агент
- KeeShare (доступ с использованием подписей и без)
- YubiKey

Криптографические библиотеки:
 libgcrypt 1.8.5
```

**Comment by droidmonkey** [comment]
Fixed in develop will be out with 2.6
