### ISSUE TITLE
Hardware key detection causes UI lockup

### ISSUE THREAD

**Issue by keisimq** [keepassxreboot/keepassxc#4442]
Please re-open issue **Hardware Key bug #4284**

I encounter the same problem. It only happens on virtual machine.

Each time I try to open database, Hardware Key bar moves without end. After entering password KeePass freezes - it looks like it's still looking for hardware key.
Initially it happened once every few times. Now it happens every time.
Resetting setting to default changes nothing.

KeePassXC - Current VERSION 2.53
Operating system: Virtual Machine - Win10 64bit
CPU architecture: Intel

![ScreenShot](https://user-images.githubusercontent.com/62240710/76747714-dde99d00-6779-11ea-9df3-d59a02cebb51.PNG)

**Comment by droidmonkey** [comment]
This is a known issue. Can you see if our snapshot build fixes it for you in your environment? I have yet to reproduce the problem on my own even tinkering with the code to try to coax it to occur.

https://snapshot.keepassxc.org

**Comment by keisimq** [comment]
I tried the last build 50102 without success.
The only difference is that is has a new GUI and the bar does not move under the 'Select slot...' field.
I tried to open the database both in a shared folder and on a local disk - no difference, KeePass freezes.

**Comment by ctand** [comment]
@droidmonkey This crash is not specifically related to hardware keys. It is not a sleep issue either. This is triggered by the database saving. It doesn't always happen but this is definitely what triggers it.

**Comment by droidmonkey** [comment]
Yes I figured it wasn't a hardware key issue, per say. There are a couple of issues that are hard to reproduce. The hardware key progress bar freeze, couldn't reproduce that even by tweaking the code to force it to fail. The freeze after save was reproducible by me (save then lock database immediately while saving) causes a crash in 2.5.3. I fixed that in the develop branch. There seems to be another issue floating around that I cannot isolate.

**Comment by alpha14** [comment]
Like #4284  I still have the same issue on the new stable version of KeePass

KeePassXC - Version 2.5.3
Revision: f8c962b
Operating system: Win10 64bit
CPU architecture: Intel

I'm available if you need more information related to the issue

**Comment by alpha14** [comment]
@droidmonkey  I'm happy to say that all the crashes and freezes are no longer happening since the installation of Keepassxc version 2.6.0-snapshot Revision: 7f98323
thanks !
