### ISSUE TITLE
Crash while switching database tabs during unlocking

### ISSUE THREAD

**Issue by furai** [keepassxreboot/keepassxc#4445]
## Expected Behavior
Switch to other locked tab without crashing.

## Current Behavior
It crashes when you switch tab.

## Possible Solution
Easy: block switching database tabs while one is being unlocked.
Hard: actually fix the bug.

## Steps to Reproduce
1. Launch KeePassXC with at least 2 database tabs.
2. Unlock one with password and master key.
3. Switch to the other tab while the first one is being unlocked.
4. Crash.

## Context
I'm not sure about any unique circumstances. Ask in comments if anything is unclear.

## Debug Info
KeePassXC - Version 2.5.3
Revision: f8c962b

Qt 5.12.4
Debugging mode is disabled.

Operating system: Ubuntu 19.10
CPU architecture: x86_64
Kernel: linux 5.5.9-050509-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.4

**Comment by droidmonkey** [comment]
Fixed in develop, will be out with 2.6.0
