### ISSUE TITLE
marking weak passwords

### ISSUE THREAD

**Issue by frits44** [keepassxreboot/keepassxc#4446]
When I checked the statistics of my keepassxc database I saw that 15 of my 180 passwords were considered "weak". Would it be possible to mark these so I can easily find and update them?

Thanks for your great program.

**Comment by droidmonkey** [comment]
I'm assuming you are using the new database reports in the develop branch. If so, then you can edit the entry right from that view by double clicking it. If not, wait until 2.6.0 to be released.
