### ISSUE TITLE
Secret Protection

### ISSUE THREAD

**Issue by KitchM** [keepassxreboot/keepassxc#4447]
The basic idea would be to have more than one "section" of entries sharing a common login screen.  Each section would act like a separate database and would be accessible by its own password but would all share the main login screen.

Therefore, if someone is threatened with the $5 Wrench Attack, they can give out the password for one database section without compromising the main one.  The idea here is to work similarly to digital hardware wallets which require a password to enter, but would hide the fact that there are multiple accounts whose access is dependent upon the password entered.

While KeePassXC does allow multiples databases, the interface does not necessarily hide the fact that there may be more than one.  Carrying the database around on a flash drive would allow the possibility of someone trying to crack into it.  But at the same time, being able to have a portable password safe would be extremely handy until something better comes along.  Solving this security paradox is imperative.

Perhaps the solution is simply a new opening interface?

**Comment by droidmonkey** [comment]
We will not be implementing "plausible deniability" databases. If you want to do that just create a separate database and don't use the kdbx extension. Hide it among a bunch of "normal" files. Disable remembering recently used databases.
