### ISSUE TITLE
Request: Add "Also include" analogous to "Do not include" in password generator

### ISSUE THREAD

**Issue by Rabattkarte** [keepassxreboot/keepassxc#4448]
## Summary

In password generator there is an option to "Do not include" characters. An analogous feature "Also include" would help with weird password policies / umlauts.

## Desired Behavior

- Add a new textbox "Also include" to the **Advanced Options** of password genereator.
- Every character in this box also gets included in the character pool.
- Let this box overwrite every other button like "A-Z" or "0-9".

## Possible Solution

Maybe the fields "Do not include" and "Also include" could be toggled to only display one at a time. I'm not sure about this idea, though.

## Context

Today I stumbled across this password policy as a German user:

- Lower-case letters a-z
- Upper-case letters A-Z
- Numbers 0-9
- Special characters: äöüÄÖÜß
- Needs to be 5-10 characters long

I was not able to create this character set without excluding **every other character** from "Extended ASCII".

My solution with this feature request would be:

- Enable buttons: A-Z, a-z, 0-9
- Set length: 10
- Fill "Also include" with: äöüÄÖÜß

**Comment by droidmonkey** [comment]
Already done in develop

**Comment by droidmonkey** [comment]
See #3876
