### ISSUE TITLE
Seems to be no way to import a CSV file

### ISSUE THREAD

**Issue by stevep99** [keepassxreboot/keepassxc#445]
Wanted to try keepassxc out, to compare against lastpass.
I exported my data from lastpass - the only format supported by lastpass is CSV.

There seems to be no way to import this CSV data into keepassxc. 

## Expected Behavior
Should be able to import lastpass CSV.

## Current Behavior
Unable to import from lastpass CSV file.

## Possible Solution
Add required feature.

## Context
It is important to allow users migrate from other services.
What is the recommended procedure for a lastpass (or user of another service) if they want to switch to keepassxc? 

## Your Environment
KeePassXC 2.1.3 on Ubuntu 16.04.

**Comment by seatedscribe** [comment]
Which branch are you using? CSV feature has been merged weeks ago on
develop.

**Comment by phoerious** [comment]
2.1.3 does not yet support CSV import. You need to compile the develop branch or wait for 2.2.0.

**Comment by stevep99** [comment]
Wow, quick response!

I simply did:
`sudo snap install keepassxc`
on Ubuntu 16.04 LTS.

The only import option I see is "Import keepass 1 database".

**Comment by stevep99** [comment]
OK great, will look forward to 2.2.0 then.
