### ISSUE TITLE
Ability to search for entries by password

### ISSUE THREAD

**Issue by DarthFutuza** [keepassxreboot/keepassxc#4451]
I searched for this, but didn't see this feature/request yet, but thought it might be nice to have.

## Summary
Want to be able to use the search field in keepassxc to find entries by password rather than by just username, url, title, etc.

## Desired Behavior
Current behavior:
![image](https://user-images.githubusercontent.com/4450419/77129220-c9770000-6a18-11ea-8290-84ae95b3c60d.png)  

Expected behavior:
![image](https://user-images.githubusercontent.com/4450419/77129724-aa796d80-6a1a-11ea-8192-9c1783e7c16a.png)

## Suggestion
By default it should probably be disabled, since people expect their passwords to be hidden.  Users may enable this feature in the settings under Security > Convenience:
![image](https://user-images.githubusercontent.com/4450419/77129540-00014a80-6a1a-11ea-8220-cb54f8f44d4d.png)

## Context
I figure it might provide an easy enough solution for most to find what passwords should be changed in the event of password breaches/compromise or for users who want to see if any passwords they use are the same/similar or remember a password but not other information, etc.

**Comment by droidmonkey** [comment]
Use advanced search terms:

`pass:somePassword`
