### ISSUE TITLE
Lost response

### ISSUE THREAD

**Issue by hzrv149** [keepassxreboot/keepassxc#4452]
The keepassxc loses response from time to time
Even though I do nothing
When it loses its response it keeps grey all the time and I can't quit the keepassxc except using Task manager.  
Also when I click TOTP autofill in edge,there is no code.
(Windows 10 ltsc 2019)
![8g8ia8.png](https://s1.ax1x.com/2020/03/20/8g8ia8.png)

**Comment by droidmonkey** [comment]
This is reported in another issue already
