### ISSUE TITLE
Update libykpers to 1.20.0

### ISSUE THREAD

**Issue by onlykey** [keepassxreboot/keepassxc#4453]
Hey so integration with OnlyKey and KeePassXC has been working pretty well with Windows and Mac versions, thanks again for adding support for this! Windows and Mac come with the latest version of yubikey-personalization library 1.20.0 (libykpers), Linux seems to still be an issue though as some users report issues which usually is because they have an older version of libykpers. The fix is to compile from source with the libykpers 1.20.0. I am trying to find where the old versions are coming from so these can be updated, I found these:

There is an old version (1.18.0) in the KeepassXC PPA here:
https://launchpad.net/~phoerious/+archive/ubuntu/keepassxc

There is an old version (1.18.0) included with the KeepassXC Snap:
```
locate libykpers
/snap/keepassxc/687/usr/lib/x86_64-linux-gnu/libykpers-1.so.1
/snap/keepassxc/687/usr/lib/x86_64-linux-gnu/libykpers-1.so.1.18.0
/snap/keepassxc/687/usr/share/doc/libykpers-1-1
/snap/keepassxc/687/usr/share/doc/libykpers-1-1/changelog.Debian.gz
/snap/keepassxc/687/usr/share/doc/libykpers-1-1/copyright
```
It also looks like the Appimage includes old version of ykpers, I extracted the appimage with:
```
KeePassXC-2.5.3-x86_64.AppImage --appimage-extract
```
And found that located in squashfs-root/usr/lib/libykpers-1.so.1

If we could update this to libykpers 1.20.0 for the next release that would be great as it would allow OnlyKey support without having to compile KeePassXC from source on Linux.

**Comment by droidmonkey** [comment]
Good catches

**Comment by onlykey** [comment]
@droidmonkey Also I tested out the docker image for building with docker - https://github.com/keepassxreboot/keepassxc/wiki/Building-KeePassXC#building-inside-a-docker-container

Looks like that is using libykpers v1.17.2

![image](https://user-images.githubusercontent.com/18121756/78297806-5bddd000-74fe-11ea-83cd-4870bfb6db92.png)

Edit: I am guessing the docker image is based on Ubuntu 16.04, that has the libykpers 1.17.2 version library:
https://packages.ubuntu.com/xenial/amd64/libykpers-1-1/filelist
![image](https://user-images.githubusercontent.com/18121756/78298098-1d94e080-74ff-11ea-84b9-6bde388da711.png)

**Comment by droidmonkey** [comment]
Yes we would have to provide this through the PPA (controlled by @phoerious)

**Comment by phoerious** [comment]
I checked this matter again. The version in our PPA is for Trusty only, which isn't support anymore. I should just delete it. Of the still-supported versions, Bionic is the only one that doesn't ship with 1.20 already. Considering that Focal is an LTS release, I don't want to maintain another package when the already existing one should already be fine for most users.
