### ISSUE TITLE
Onlykey: possible cross platform issue

### ISSUE THREAD

**Issue by Bnixn7** [keepassxreboot/keepassxc#4455]
## Current Behavior
When I secure a database with Onlykey HMAC while using Windows 10, I cannot open the same database using Linux. Similarly, when I create/save a Onlykey secured database while using Linux, I cannot open it when using Windows. When staying within one operating system, the Onlykey support seems to work fine so far.

PS: I had to compile the stable version of keepassxc from source (Debian package version is outdated) to make Onlykey work. The snap/appimage versions work in general, but do not recognize Onlykey (probably some additional configuration needed to get USB access).

## Expected Behavior
A Onlykey secured database should be accessable on all supported operating systems when using the same keepassxc version and hardwarekey.

## Context
I have a Windows/Linux dualboot setup and would like to secure my Windows database with HMAC, while beeing able to create non-HMAC backups of that particular database when using Linux.

## Debug Info

**Linux**

KeePassXC - Version 2.5.3
Revision: f8c962b

Qt 5.12.5
Diagnosemodus ist deaktiviert.

Betriebssystem: Debian GNU/Linux bullseye/sid
CPU-Architektur: x86_64
Kernel: linux 5.4.0-4-amd64

Aktivierte Erweiterungen:
- Auto-Type
- Browser-Integration
- SSH-Agent
- KeeShare (bestätigtes und unbestätigtes Teilen)
- YubiKey
- Secret-Service-Integration

Kryptographische Bibliotheken:
 libgcrypt 1.8.5

**Windows**

KeePassXC - Version 2.5.3
Revision: f8c962b

Qt 5.13.2
Diagnosemodus ist deaktiviert.

Betriebssystem: Windows 10 (10.0)
CPU-Architektur: x86_64
Kernel: winnt 10.0.18363

Aktivierte Erweiterungen:
- Auto-Type
- Browser-Integration
- SSH-Agent
- KeeShare (bestätigtes und unbestätigtes Teilen)
- YubiKey

Kryptographische Bibliotheken:
 libgcrypt 1.8.5

**Comment by droidmonkey** [comment]
Most definitely related to, if not cause by, #4453
