### ISSUE TITLE
Second Yubikey

### ISSUE THREAD

**Issue by ibahnasy** [keepassxreboot/keepassxc#4456]
## Summary
Being able to add a second Yubikey in case the first one is damaged or lost.

**Comment by droidmonkey** [comment]
Already an issue for thiz

**Comment by phoerious** [comment]
Program two keys with the same secret.

**Comment by EvilOlaf** [comment]
> 
> 
> Program two keys with the same secret.

That partially works. But I had once the issue that KeepassXC was explicitly asking for the first key that has been added. After flipping again I tried editing the database, save it, close and reopen it with the 2nd key and was working again. Maybe KeepassXC under some circumstances  is looking for the key's serial number?

**Comment by droidmonkey** [comment]
You cannot open a database with one key and use a different hardware key to save that database, even if the secret is the same.

**Comment by EvilOlaf** [comment]
As long as it is possible to switch keys while the database is closed everything is fine.
