### ISSUE TITLE
KeePassXC won't start at boot because "libgcrypt-20.dll missing".

### ISSUE THREAD

**Issue by CerebralFreeze** [keepassxreboot/keepassxc#4458]
Hello, Everyone!

**The Problem**
Whenever I reboot my computer (Windows 10), KeePassXC won't automatically open by itself and the following dialog box appears during the boot up process:

KeePassXC.exe - System Error
The code execution cannot proceed because libgcrypt-20.dll was not found. Reinstalling the program may fix this problem.

![image](https://user-images.githubusercontent.com/24355773/77251417-a15bec80-6c24-11ea-8116-17d820df6c44.png)

**How I Fixed This Issue**
I opened up my startup folder I realized that there is not a shortcut to the KeePassXC.exe file that is located in my Program Files folder.  Rather, there is an actual copy of KeePassXC.exe in the Startup Folder.  When I try to double-click this actual copy, KeePass won't open and the same above dialog box appears.

However, when I open the copy of KeePassXC.exe that is in the C:\Program Files\KeePassXC folder, KeePassXC now opens correctly.

As a fix, I deleted the original copy of KeePassXC.exe in the Startup folder and replaced it with a shortcut to the copy of KeePassXC located in the Program Files folder.

Now, everything works fine.

I've tried looking up the problem via Issues on this GitHub page and via Google, but I haven't encountered anyone with this same problem.  I just wanted to mention it to help anyone else that might be confused.

**## Debug Info**
KeePassXC - Version 2.5.3
Revision: f8c962b

Qt 5.13.2
Debugging mode is disabled.

Operating system: Windows 10 (10.0)
CPU architecture: x86_64
Kernel: winnt 10.0.18362

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.5

**Comment by droidmonkey** [comment]
Why did you make a new issue?
