### ISSUE TITLE
Removing an entry from a synced KeyShare group does not remove it from others

### ISSUE THREAD

**Issue by AJJLagerweij** [keepassxreboot/keepassxc#4459]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )
When one of my users deletes a key from the shared database it is not deleted from the databases of other users.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
I expect a removed key to be removed for all users that synchronize to the keeshare group

## Current Behavior
[NOTE]: # ( Tell us what actually happens )
Currently, it only removes the key for one user. This means that everyone has to remove the key.

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1. Create a shared folder where both users are in synchronization mode.
2. Have a user add a key.
3. Have any user remove the key.
4. Look if the key still exists in the database of the other user.

I did test this on both Windows and Ubuntu devices across platforms and between two Ubuntu sessions.

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )
It is simply a pain to have every user remove a key after it has become unused.
Of course one could have one admin with export mode and user that can only import groups to solve the issue. This means that only the admin can edit the keys inside the group. However, in my case there are different users that must be able to create keys.

### Operating system 1
KeePassXC - Versie 2.5.3
Revisie: f8c962b
Distributie: Snap

Qt 5.9.5
De foutopsporingsmodus is uitgeschakeld.

Besturingssysteem: Ubuntu Core 18
CPU-architectuur: x86_64
Kernelversie: linux 5.3.0-42-generic

Geactiveerde extensies:
- Auto-type
- Browserintegratie
- SSH-agent
- KeeShare (getekend en ongetekend delen)
- YubiKey
- Integratie van geheime diensten

Cryptografische bibliotheken:
 libgcrypt 1.8.1

### Operating system 2
KeePassXC - Versie 2.5.3
Revisie: f8c962b

Qt 5.13.2
De foutopsporingsmodus is uitgeschakeld.

Besturingssysteem: Windows 10 (10.0)
CPU-architectuur: x86_64
Kernelversie: winnt 10.0.18362

Geactiveerde extensies:
- Auto-type
- Browserintegratie
- SSH-agent
- KeeShare (getekend en ongetekend delen)
- YubiKey

Cryptografische bibliotheken:
 libgcrypt 1.8.5

**Comment by droidmonkey** [comment]
I wouldn't necessarily call this a bug, it might be desired behavior in another organization. It should be explicit that you intend to remove the entry from all synced databases.

**Comment by AJJLagerweij** [comment]
Thanks for your good point, it makes sense to be like this for other organizations.

I guess implementing it in a way that it is useful in both situations will lead to more options in the setup. One could:
1. add more synchronization options one that differentiates between the rights of uses, one for create and edit only and one for create, edit and remove,
2. create an option in the 'do you want to move this file to trash' window with the question if you want to remove the key for all users.
3. allow everyone to add keys, but only the original creator of a key can remove it for all othr users.

I'm sure there are more possibilities but am unsure if we want te code/uses to become more complex. The user simplicity of the keeshare in its current state is quite nice.

**Comment by droidmonkey** [comment]
Just to be sure, the entry was deleted and not just moved to recycling bin?

**Comment by AJJLagerweij** [comment]
It was moved to the recycling bin.
It asked for that, see the image below.
![image](https://user-images.githubusercontent.com/31255888/77287743-9792c180-6cd6-11ea-8e07-d97effc535ec.png)

Of course for the other users of the shared group there was no change.
Is it was moved to the bin only for the user that tried to delete it.

**Comment by droidmonkey** [comment]
You must actually delete it to affect any change. Empty the recycle bin or delete it from the bin and report back if it removes from the other shares.

**Comment by AJJLagerweij** [comment]
That fixes the problem, now it removes the key for all users across the platforms.
I'm sorry for wasting your time, I should have search more extensively with the label: "plugin: KeeShare".

Here is the related issue #2798, this one can be labeled as a duplicate.
