### ISSUE TITLE
[UI] Don't set window to modified if group tree view gets collapsed or expanded

### ISSUE THREAD

**Issue by cslux** [keepassxreboot/keepassxc#446]
## Expected Behavior
When the tree gets collapsed or expanded (groupview (tree view)) the window should not be set to modified, instead silently save the state.

## Current Behavior
The window is set to modified, on quit the user will be asked whether the "changes" should be saved or not.

![keepassxc-modified](https://cloud.githubusercontent.com/assets/1712313/24518724/2d35513e-1583-11e7-9c50-1151bb03ea16.png)

## Your Environment
KeePassXC - Version 2.1.3
Revision: b7546b45b3c48e2ffa150be72fc6ce03db1adf00

Libraries:
- Qt 5.7.1
- libgcrypt 1.6.6

Operating system: Fedora 25 (Workstation Edition)
CPU architecture: x86_64
Kernel: linux 4.10.5-200.fc25.x86_64+debug

Enabled extensions:
- Auto-Type

Thank you guys!

Chris

**Comment by cslux** [comment]
The **Tools* menu entry hasn't an accelerator either.

**Comment by louib** [comment]
This could at least be a setting. I might be surprising the first time you get prompted to save your changes when you don't remember creating / editing any entry.

@cslux can you create new issues for the menu accelerators please?

**Comment by cslux** [comment]
> @cslux can you create new issues for the menu accelerators please?

Sure!

**Comment by droidmonkey** [comment]
Consider the case when you make changes to the database then expand a group. The auto save option is not desired.

**Comment by louib** [comment]
> The auto save option is not desired.
I didn't notice that the solution proposed was to silently auto save. I was thinking about an option that does not consider changes in group expansion as changes, so that no saving is required for that.

**Comment by cslux** [comment]
I personally can leave with the solution from #464. But of course, saving state would be better.  Saving the state in the **keepassxc.ini** file is probably not a solution, isn't it? Also, what happens when the user collapses the tree, saves the state, enables the option "Ignore group expansion" #464, would the tree than always be collapsed when the user opens the database?

**Comment by cslux** [comment]
> Also, what happens when the user collapses the tree, saves the state, enables the option "Ignore group expansion" #464, would the tree than always be collapsed when the user opens the database?

I just applied #464. Yes, the group will always be collapsed. I would always expand the tree if the option from #464 is enabled.

**Comment by louib** [comment]
> I just applied #464. Yes, the group will always be collapsed.

Unless you expand that group and then save the database, even though it's not marked as modified.

>  I would always expand the tree if the option from #464 is enabled.

I don't think we should do any automatic expand or collapse based on the new option. If a user wants certain groups expanded and other groups collapsed on startup, he can always save the db this way, even though it won't be marked as modified.

**Comment by cslux** [comment]
@louib OK :-)

**Comment by louib** [comment]
@cslux the feature has been merged in the `develop` branch, you can try it out!

**Comment by cslux** [comment]
Works as you said. Even when it is not marked as modified I can still save the
new state.

Thank you!
