### ISSUE TITLE
Show time left for TOTP code in Entry Preview pane

### ISSUE THREAD

**Issue by Penaus** [keepassxreboot/keepassxc#4461]
[TIP]:  # ( Provide a general summary of the feature in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Summary
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
A little Timer which is counting downto 0 to show how long the current TOTP is valid.

## Desired Behavior
[NOTE]: # ( Tell us how the new feature should work, be specific )
Show a little timer next to the TOTP

## Possible Solution
[NOTE]: # ( Not required, but suggest ideas on how to implement the addition or change )

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
Happend a few times to me that i copied the code and it expired during switching to the browser.

My idea as a primitive paint.exe job
![totp](https://user-images.githubusercontent.com/28874650/77312006-772c2c80-6d01-11ea-9c4c-be7fc9213472.JPG)

**Comment by droidmonkey** [comment]
A little progress bar would work great as well. Good idea! 

We also need a way to easily copy that, maybe even just on click or something

**Comment by thecolinw** [comment]
Maybe it is although an option to say if I copy the totp and the totp changes while the timeout to clear the clipboard has not expired to replace the totp in the clipboard with the new one automatically.

**Comment by droidmonkey** [comment]
This was implemented in 2.7.0
