### ISSUE TITLE
keepassxc-cli: handle attachments

### ISSUE THREAD

**Issue by grcancelliere** [keepassxreboot/keepassxc#4462]
[TIP]:  # ( Provide a general summary of the feature in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Summary
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
Being able to work with attachments in entries from the CLI.

## Desired Behavior
[NOTE]: # ( Tell us how the new feature should work, be specific )
- the `add` command should have switches to add attachments by path
- the `edit` command should have switches to add attachments by path or remove attachments by name
- the cli should have a  command (`getattachment` ?) to export an attachment from an entry by name

## Possible Solution
[NOTE]: # ( Not required, but suggest ideas on how to implement the addition or change )

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
I'd like to use the CLI to automate the handling of secure files (e.g. SSH keys, GPG keys, ...) by storing them in Keepass entries.

**Comment by hifi** [comment]
Just a note that you can use SSH keys from within KeePassXC with the SSH Agent feature.

**Comment by mmaridev** [comment]
+1 would be really useful to automate SSH private keys generation

**Comment by mStirner** [comment]
I stubled across this issue. 
It would be really nice to work with attachments from the cli, like open/edit/delete/add/export.
