### ISSUE TITLE
Password placeholder is not masked out in cmd confirmation message box

### ISSUE THREAD

**Issue by asmallwood0311** [keepassxreboot/keepassxc#4463]
When a new or modified cmd:// url is added to an item, a message box pops up displaying the full command line and prompting the user if they wish to execute it. The password is shown in plain text and should be *******.

**Comment by phoerious** [comment]
I am not sure what you mean. Is your password part of the command?

**Comment by phoerious** [comment]
I just tested it: when I use a placeholder, it is replaced with asterisks in the entry list, but not in the popup. This would be a bug. If you write your password directly into the command, then we wouldn't be able to detect it of course.

**Comment by asmallwood0311** [comment]
Correct. I am using only the password field. **** shows in the entry list but not in the pop up. Confirmed I am not entering it into the command line, but using the placeholder {PASSWORD}.
