### ISSUE TITLE
Application error due to memory being unable to read

### ISSUE THREAD

**Issue by gofraidh** [keepassxreboot/keepassxc#4466]
## Expected Behaviour
The error occurs during the start of the application when attempting to unlock the database.

The Kee Pass XC runs on Windows 10 Pro 1909 (64bit) with the database hosted on cloud and key on internal hard drive.

## Current Behaviour
On an attempt to unlock the database, the database does not load, the window stops responding and it can't be closed. The main window is not responsive and does not unlock the database. When quitting the application using tray option (Ctrl + Q) the application reports the error shown below.

![image](https://user-images.githubusercontent.com/7356171/77418988-97babc00-6dbf-11ea-94bd-96223dfa4911.png)

## Steps to Reproduce
I do not know what may trigger the error and can't reproduce it. However; I suspect it could have something to do with the computer being put in the "Sleep" state. I suspect the error is triggered when attempting to run the app once the computer is up and running from "Sleep".

## Context
The error leaves the application non responsive and it has to be closed via tray (error triggered) or forced shut down from task manager. However; once this is done the app starts and unlocks the database as usual.

## Debug Info
KeePassXC - Version 2.5.3
Revision: f8c962b

Qt 5.13.2
Debugging mode is disabled.

Operating system: Windows 10 (10.0)
CPU architecture: x86_64
Kernel: winnt 10.0.18363

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.5

Libraries:
- LIBS

Operating system: OS
CPU architecture: ARCH
Kernel: KERNEL

**Comment by droidmonkey** [comment]
This is a duplicate report. I believe to have fixed this already for our 2.6.0 release and in develop branch. You can try using our snapshot to see if it persists: https://snapshot.keepassxc.org

**Comment by gofraidh** [comment]
@droidmonkey Thank you very much. It looks like 2.6.0 will be the next release? If that's the case I will wait for the stable release.

**Comment by droidmonkey** [comment]
Can you test the snapshot to see if the issue persists?

**Comment by droidmonkey** [comment]
This is caused by whatever issue is causing #4442
