### ISSUE TITLE
[UI] Missing menu entry accelerators

### ISSUE THREAD

**Issue by cslux** [keepassxreboot/keepassxc#447]
## Expected Behavior
At least the menu entry should have an accelerator.

## Current Behavior
The **Database** and **Tools** menu entry do not have an accelerator.

## Your Environment
KeePassXC - Version 2.1.3
Revision: b7546b45b3c48e2ffa150be72fc6ce03db1adf00

Libraries:
- Qt 5.7.1
- libgcrypt 1.6.6

Operating system: Fedora 25 (Workstation Edition)
CPU architecture: x86_64
Kernel: linux 4.10.5-200.fc25.x86_64+debug

Enabled extensions:
- Auto-Type

**Comment by mkasberg** [comment]
This was tagged as beginner so I took a stab at it. I think the change is pretty straightforward, but let me know if I missed anything.

**Comment by TheZ3ro** [comment]
Thanks @mkasberg :smile:
