### ISSUE TITLE
Grave Problem with KeePassXC - Program Speed!

### ISSUE THREAD

**Issue by CerebralFreeze** [keepassxreboot/keepassxc#4470]
## Expected Behavior
1. When I open a password entry, I'll sometimes make a change to a field such as changing the password.  I will then click the **Apply** and **Close** button that is located at the bottom right.
2. My KeePassXC's entry window will immediately close and KeePassXC's main window with its list of password entries will appear.  
3. I think what a great program.

## Current Behavior
1. When I double click an entry to open and change it, I will do and change something like the password.  Afterward, I will usually click the bottom-right button called **Apply** and then the button called **Close**.
2. The KeePassXC entry window will immediately close but KeePassXC's main window with its list of entries will not be immediately responsive.  Instead, KeePassXC will be greyed out.  And, I will have to wait an ungodly 2 seconds.  As you know, that's a very long time and it drives me crazy.  
3. Sometimes, it might even take as long as 3 seconds and I will respond by doing something very naughty.  I click somewhere within the KeePassXC window.  As a result, the top window bar's title at the left will change angrily and letters suddenly appear at the right of it.  It looks like it says "Not Responding."
4. I'll wait for another second or so, ready to give up but miraculously, everything returns back to normal.
5. I wipe the sweat off my brow.

[NOTE]: # ( Tell us what actually happens )
As you can see, it takes a _very_ long time for KeePassXC to execute certain functions.  I have a decent computer (i7, 64 gig, Nvidia 1080, SSD, Windows 10 OS) and all programs pretty much respond and open and close pretty quickly.  However, for some odd reason, KeePassXC seems to take an incredibly long time for it to respond whenever I make any type of changes to entries or settings.

I was wondering if there was a way to remedy this grave problem.  Can I do something here or do something over there to a part of the OS so it could make KeepPassXC operate just as fast as every other program?

To be honest, I'm slightly embarrassed by this question.  This problem really isn't that grave.  It still annoys me a lot though!  KeePassXC hangs and I was wondering if there was a way to stop it.

## Possible Solution
Maybe I can somehow put all of KeePassXC into RAM memory and everything occurs at super-speed?

## Context
This problem has led to heart palpitations and thus, heart problems.

## Debug Info
KeePassXC - Version 2.5.3
Revision: f8c962b

Qt 5.13.2
Debugging mode is disabled.

Operating system: Windows 10 (10.0)
CPU architecture: x86_64
Kernel: winnt 10.0.18362

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.5

**Comment by droidmonkey** [comment]
Go to Database menu and choose change master key. Then click the encryption tab and move the time to encrypt to a lesser value. Press OK.

**Comment by CerebralFreeze** [comment]
Holy Moly!  You must have five thousand IQ!  I was so sure that I was going to stump you or anyone else for a while that I didn't check the answer until just now.

I'm not going to lie.  I think I'm in love with you.  Please make a baby with me.  I don't know how that will work since I'm a guy but I'm sure we can figure out a way!  Please!

I bet you were wishing that I looked like this:
![image](https://user-images.githubusercontent.com/24355773/77615888-d018e200-6f06-11ea-9cb5-d2efb79e87b5.png)

Too bad for you I look like this:
![image](https://user-images.githubusercontent.com/24355773/77615991-05253480-6f07-11ea-9389-a1ed581b20ef.png)

In all seriousness, no wonder KeePassXC kicks ass.  You, guys really have done an awesome job and I should know.  I've spent a lot of time trying out other password managers.  I've used Dashlane, 1Password, Roboform, and LastPass, trying each from at least a few months to a few years.

This last go around, I decided to transfer everything to KeePassXC because I read this Berkeley research paper that said online password storage is not a very good idea.  So, I think you guys have a really awesome program.  I think if you get an inexpensive designer with an art degree that can make the GUI and logo look cool, I think massive amounts of people will flock to your product.

Whatever you, guys decide, I wish you the best.  And, if there is anything that I can do to help, let me know!

**Comment by phoerious** [comment]
You should try a 2.6 snapshot.

**Comment by droidmonkey** [comment]
Thanks, lol, glad you are back up to speed
