### ISSUE TITLE
KeepassXC does not start after latest macos security update

### ISSUE THREAD

**Issue by roycec** [keepassxreboot/keepassxc#4471]
After applying the latest security update (macos 10.14.6 in my case) KeePassXC does not start any more.

## Expected Behavior
KeePassXC starts and asks for password to open the database

## Current Behavior
MacOS message (window) appears. Something like "app has unexpectedly quit". Only possible to send report to Apple but no change to reopen the app. Reinstalling the app does not fix the problem.

## Steps to Reproduce
1. Update MacOS Mojave to Apple Security Update 2020-02
2. Open KeePassXC

## Context
Experieced error (?) during update. Mac was turned off and on several times. I turned it off manually, started it again and the rest of the update went thru without any errors.

## Debug Info
KeePassXC - 2.5.3
Revision: 

Operating system: MacOS 10.14 (Mojave)
CPU architecture: x84_64
Kernel: Darwin 18.7.0

**Comment by ciaran-byrne** [comment]
I have the same issue on 10.15.4:
`Process:               KeePassXC [37139]
Path:                  /Applications/KeePassXC.app/Contents/MacOS/KeePassXC
Identifier:            org.keepassx.keepassxc
Version:               ???
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           KeePassXC [37139]
User ID:               501

Date/Time:             2020-03-24 23:36:23.888 +0000
OS Version:            Mac OS X 10.15.4 (19E266)
Report Version:        12
Bridge OS Version:     4.4 (17P4263)

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (Code Signature Invalid)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY`

**Comment by phoerious** [comment]
Duplicate of #4398. Apple fucked up their code signing.
