### ISSUE TITLE
macOS 10.14.6 - Code Signature Invalid

### ISSUE THREAD

**Issue by commx** [keepassxreboot/keepassxc#4472]
After installation of the latest security update for macOS today (2020-002 to be exact), KeePassXC no longer launches but crashes immediately with `EXC_CRASH`. According to the report being generated it looks like it has something to do with Code Signing.

<img width="1112" alt="Screenshot 2020-03-25 at 00 31 59" src="https://user-images.githubusercontent.com/2342384/77486733-cb81fa00-6e30-11ea-9614-2feca79b4e6b.png">

KeePassXC has been installed via homebrew, but the same behaviour is seen when launching the application directly from the latest .dmg file provided on the website.

## Expected Behavior
The application should start.

## Current Behavior
The application crashes right after start.

## Possible Solution
Probably Code Signing.

## Steps to Reproduce
Start the application.

## Context
Crash happens after installation of the latest macOS security update 2020-002.

## Debug Info
KeePassXC 2.5.3 (further info not available since application won't start).

Operating system: macOS 10.14.6 ("Mojave")
CPU architecture: x86_64
Kernel: Darwin 18.7.0, root:xnu-4903.278.28~1/RELEASE_X86_64

Enabled extensions: none

**Comment by phoerious** [comment]
Duplicate of #4398.
