### ISSUE TITLE
KeePassXC 2.5.3 ceased working following the release of macOS Catalina version 10.15.4

### ISSUE THREAD

**Issue by kvjcarr** [keepassxreboot/keepassxc#4473]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

## Current Behavior
[NOTE]: # ( Tell us what actually happens )

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1.
2.
3.

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION
Revision: REVISION

Libraries:
- LIBS

Operating system: OS
CPU architecture: ARCH
Kernel: KERNEL

Enabled extensions:
- EXTENSIONS

**Comment by alessandrousseglioviretta** [comment]
error message:

```
Process:               KeePassXC [3251]
Path:                  /Applications/KeePassXC.app/Contents/MacOS/KeePassXC
Identifier:            org.keepassx.keepassxc
Version:               ???
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           KeePassXC [3251]
User ID:               <id>
```

**Comment by swa66** [comment]
Was apparently known against macOS 10.15.4 beta releases.
https://github.com/keepassxreboot/keepassxc/issues/4398#issuecomment-603604527

**Comment by droidmonkey** [comment]
Duplicate issue
