### ISSUE TITLE
KeepassXC 2.5.3 - OSX 10.14.6 - Crashes on open (Code signing issue?)

### ISSUE THREAD

**Issue by leff** [keepassxreboot/keepassxc#4474]
## Expected Behavior

App opens

## Current Behavior

App crashes instantly on open.

## Possible Solution

Rolling back to 2.5.2 works for me.

## Steps to Reproduce
1. Install all security updates on OSX 10.14.6
2. Install KeepassXC 2.5.3
3. Try to open KeepassXC

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here ) << I Don't get this far.
KeePassXC - 2.5.3
Revision: Don't know how to tell, it won't open

```
Process:               KeePassXC [14544]
Path:                  /private/var/folders/*/KeePassXC.app/Contents/MacOS/KeePassXC
Identifier:            org.keepassx.keepassxc
Version:               ???
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           KeePassXC [14544]
User ID:               501

Date/Time:             2020-03-24 22:20:55.963 -0500
OS Version:            Mac OS X 10.14.6 (18G4032)
Report Version:        12
Anonymous UUID:        ....................


Time Awake Since Boot: 3000 seconds

System Integrity Protection: enabled

Notes:                 Translocated Process

Crashed Thread:        0

Exception Type:        EXC_CRASH (Code Signature Invalid)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace CODESIGNING, Code 0x1

kernel messages:

VM Regions Near 0 (cr2):
--> 
    __TEXT                 000000010f853000-000000010fbe5000 [ 3656K] r-x/r-x SM=COW  

Thread 0 Crashed:
0                                 	0x0000000111593000 _dyld_start + 0

```

Libraries:
- ?

Operating system: OSX 10.14.6
CPU architecture: Intel
Kernel: 

Enabled extensions:
- keepassxc has extensions?

**Comment by l2dy** [comment]
See #4398.

**Comment by leff** [comment]
> See #4398.

Oh yeah, that does look pretty much exactly the same.
