### ISSUE TITLE
Keepassxc cannot open on MacOS Catalina 10.15.4

### ISSUE THREAD

**Issue by pnlinh** [keepassxreboot/keepassxc#4475]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Current Behavior
[NOTE]: # ( Tell us what actually happens )
Keepassxc cannot open

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1. Open keepassxc app

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.5.3
Revision: 9d7be57716fe51f0f28a92d080e75ea122b641cd4b83ab41ce0c39fc5022c9e0

Libraries:
- LIBS

Operating system: MacOS
CPU architecture: Intel 2.3 GHz Dual-Core Intel Core i5
Kernel: XNU

Enabled extensions:
- EXTENSIONS

**Comment by filmfan2206** [comment]
I just upgraded my MBP tonight (8pm, 3/24/20) and I can't open the application now. :(  same problems as above.

**Comment by darkb1t** [comment]
I have the same issue. 
Exception Type:        EXC_CRASH (Code Signature Invalid)

**Comment by themandersen** [comment]
I am seeing the same problem with Keepassxc version 2.5.3 after upgrading MacOS to 10.15.4.
The error/exception I am seeing in the Problem Details is:

Exception Type:        EXC_CRASH (Code Signature Invalid)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace CODESIGNING, Code 0x1

It seems the latest update for Catalina doesn't jive with the app signature of 2.5.3

**Comment by pnlinh** [comment]
> I just upgraded my MBP tonight (8pm, 3/24/20) and I can't open the application now. :( same problems as above.
> 
> Edit 1: I downgraded to 2.5.2 and it works again! Fyew!

I just download ver 2.5.2, it's worked. Thanks!

**Comment by l2dy** [comment]
See #4398.

**Comment by gopipal** [comment]
> > I just upgraded my MBP tonight (8pm, 3/24/20) and I can't open the application now. :( same problems as above.
> > Edit 1: I downgraded to 2.5.2 and it works again! Fyew!
> 
> I just download ver 2.5.2, it's worked. Thanks!

Could you add the download link for 2.5.2?

**Comment by gopipal** [comment]
> > > I just upgraded my MBP tonight (8pm, 3/24/20) and I can't open the application now. :( same problems as above.
> > > Edit 1: I downgraded to 2.5.2 and it works again! Fyew!
> > 
> > 
> > I just download ver 2.5.2, it's worked. Thanks!
> 
> Could you add the download link for 2.5.2?

https://github.com/keepassxreboot/keepassxc/releases/download/2.5.2/KeePassXC-2.5.2.dmg

**Comment by DasLeo** [comment]
It's still a bug though or is there any follow up issue?

**Comment by Nothing4You** [comment]
@DasLeo #4398

**Comment by filmfan2206** [comment]
> It's still a bug though or is there any follow up issue?

Yes, it's still a bug in the latest version!

**Comment by phoerious** [comment]
Use 2.5.3-2., not 2.5.2.

**Comment by Olegf13** [comment]
`brew update && brew cask reinstall keepassxc` worked for me (reinstalls with 2.5.3-2 version, as mentioned above)

**Comment by raulicomr** [comment]
2.5.3-2 works in macOS Catalina 10.15.4 !!
https://github.com/keepassxreboot/keepassxc/releases/download/2.5.3/KeePassXC-2.5.3-2.dmg
