### ISSUE TITLE
Keypassxc crashed since Apple's update to macOS 10.15.4

### ISSUE THREAD

**Issue by AVDProjects** [keepassxreboot/keepassxc#4476]
<img width="1180" alt="Screenshot 2020-03-25 at 08 17 17" src="https://user-images.githubusercontent.com/62640744/77513702-c6936980-6e75-11ea-98be-a7ca34641506.png">

Sorry no time to fill in the rest. I know Apple updates are crappy over the last year, but this is the second updates where by KeypassXC don't work anymore.  

I hope you can fix this soon :) success!

**Comment by tswestendorp** [comment]
See #4398
