### ISSUE TITLE
Broken on MacOS 10.15.4

### ISSUE THREAD

**Issue by autarchprinceps** [keepassxreboot/keepassxc#4477]
Breaks since the update to 10.15.4 yesterday. I tried reinstalling, but that doesn't help either.

Process:               KeePassXC [4768]
Path:                  /Applications/KeePassXC.app/Contents/MacOS/KeePassXC
Identifier:            org.keepassx.keepassxc
Version:               ???
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           KeePassXC [4768]
User ID:               501

Date/Time:             2020-03-25 08:51:40.168 +0100
OS Version:            Mac OS X 10.15.4 (19E266)
Report Version:        12
Bridge OS Version:     4.4 (17P4263)
Anonymous UUID:        DD84F205-E9D1-AC8F-7FEB-0A96E56EEDEB

Time Awake Since Boot: 1200 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (Code Signature Invalid)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace CODESIGNING, Code 0x1

kernel messages:

VM Regions Near 0 (cr2):
--> 
    __TEXT                 000000010ba75000-000000010be07000 [ 3656K] r-x/r-x SM=COW  

Thread 0 Crashed:
0   ???                           	0x0000000111323000 _dyld_start + 0

**Comment by tswestendorp** [comment]
See #4398
