### ISSUE TITLE
MacOS 10.15.4 update - KeePassXC 2.5.3 crash

### ISSUE THREAD

**Issue by dicksondickson** [keepassxreboot/keepassxc#4478]
Just updated to MacOS 10.15.4 today and KeePassXC 2.5.3 won't load. App crashes on exec. No UI or anything just the error report window saying the app crashed.

Snippet from the error report:

Exception Type:        EXC_CRASH (Code Signature Invalid)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Thank you!

**Comment by tswestendorp** [comment]
See #4398
