### ISSUE TITLE
KeePassXC barfs under 10.15.4 Catalina

### ISSUE THREAD

**Issue by MaurizioLoreti** [keepassxreboot/keepassxc#4479]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Expected Behavior
[NOTE]: # 
KeePassXC should start

## Current Behavior
[NOTE]: # 
KeePassXC quits unexpectedly

## Possible Solution
[NOTE]: # 
?

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1. Install MacOS 10.15.4 (did it today)
2. Open KeePassXC
3. KeePassXC quit unexpectedly. This report will be sent to Apple automatically

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION 2.5.3
Revision: REVISION

Libraries:
- LIBS

Operating system: MacOS 10.15.4
CPU architecture: intel core i7
Kernel: KERNEL Darwin 19.4.0

Enabled extensions:
- EXTENSIONS

**Comment by tswestendorp** [comment]
See #4398

**Comment by phoerious** [comment]
@tswestendorp the triage bot. Thanks. :-D
