### ISSUE TITLE
keepassxc version2.53 hard crashed on macOS10.14.6 after security update

### ISSUE THREAD

**Issue by bcmatteo** [keepassxreboot/keepassxc#4488]
KeePassXC does not start.  Gives "KeePassXC quit unexpectedly" error.  error report file attached:

[KPxcError.txt](https://github.com/keepassxreboot/keepassxc/files/4382197/KPxcError.txt)

**Comment by droidmonkey** [comment]
Download 2.5.3-2

**Comment by phoerious** [comment]
Duplicate of pinned issue #4398.

**Comment by bcmatteo** [comment]
> Download 2.5.3-2

fixed it. thanks.
