### ISSUE TITLE
Make a KeePassXC Limited Version

### ISSUE THREAD

**Issue by ferdigant** [keepassxreboot/keepassxc#449]
Hello,
I just want to remove some Options of KeePassXC Portable.
This File is located at a "shared" Cloud and some users can open it like ist installed, but don`t have to edit it.

## Expected Behavior
1. Portable Edition should not Export Passwords as an CSV File
2. Portable Edition should not reset Database Masterkey
3. Portable Edition should not use "Tools" "Settings"

## Context
I know that somebody just can download KeePassXC Portable by himself and change this settings, but this is not necessary.

## Your Environment
* Qt version Qt 5.8.0- libgcrypt 1.7.6
* Operating System:  Windows 10

**Comment by TheZ3ro** [comment]
This is not really a "Portable" version but it's a "Limited" version.

Like you said

> I know that somebody just can download KeePassXC Portable by himself and change this settings, but this is not necessary.

So IMHO it's useless put effort into it

**Comment by eternaltyro** [comment]
> This File is located at a "shared" Cloud and some users can open it like ist installed, but don`t have to edit it. 

Can you elaborate on this? 

> Portable Edition should not reset Database Masterkey
Why? I don't understand the context for this.

**Comment by TheZ3ro** [comment]
@eternaltyro From what I've understand, he has the KDBX file in a shared folder and want to put a KeePassXC Portable and Limited version along with it.
Since many users can access the shared storage he want a limited version so users can't edit the master password (making others unable to access the kdbx file) and other various things.

> Portable Edition should not Export Passwords as an CSV File

This is useless since users can manually copy passwords one by one

**Comment by ferdigant** [comment]
@TheZ3ro Yeah, I want to do it like this
For sure they can copy it one by one but its not simply as the Export and it may prevent it.

@eternaltyro 
its on a shared Folder where the users can open it. 

SharedFolder -> KeepassXC -> KepassXCPortable
SharedFolder  -> Database

working fine right now, but i want to close this Settings because of prevention sb. steal the Password of my customers at once.

**Comment by TheZ3ro** [comment]
Sorry but we are not developing this. I'm closing

**Comment by ferdigant** [comment]
Well I dont think that this is a big Deal,
I just want to hide the Export Funktion for the users

**Comment by phoerious** [comment]
You are free to compile a custom version of KeePassXC. A guide to compiling the program can be found in our wiki and removing the menu entries is quite trivial. But we cannot support such exotic use cases.
