### ISSUE TITLE
issues on Mac in dark mode while using snapshot of 2.6

### ISSUE THREAD

**Issue by dpbaker57** [keepassxreboot/keepassxc#4490]
## Expected Behavior
Everything on screen needs to be readable

## Current Behavior
There are a number of items not visible in dark mode most notably cloned entries using references.

I was using 2.6 as a workaround for the Mac 10.15.4 issue. Thanks for 2.5.3-2!

**Comment by phoerious** [comment]
Fixed in #4410.
