### ISSUE TITLE
Add Key File Support For Auto Open Entries

### ISSUE THREAD

**Issue by Emily7777** [keepassxreboot/keepassxc#4493]
## Summary
Current auto open entries are great, but they don't support vaults with key files.

## Desired Behavior
Support auto open vaults with key files.

## Possible Solution
Allow for a key file path to be saved along with the vault name, password, and path.
If a key file path is entered, include the key file path in the auto open credentials.

## Context
I need to sandbox vaults.  I can't keep everything in one vault.  Certain work contexts require a group of vaults to be opened at once, hence the extensive use of auto open.  However, those vaults are now protected with key files,  And now I have to open them one at a time.

**Comment by Emily7777** [comment]
Sorry...timeout caused a duplicate post.

**Comment by droidmonkey** [comment]
Fixed!

**Comment by droidmonkey** [comment]
Btw this feature has already been added.
