### ISSUE TITLE
Display Entry Attributes as Passwords

### ISSUE THREAD

**Issue by TheZ3ro** [keepassxreboot/keepassxc#45]
In KeePassX you can add extra attributes for an Entry.
This attributes can only be Clear-text type.

Add support for Extra Password Attributes (like PIN, Secret Answer, etc) obviously encrypted

Original KeePassX issue: https://dev.keepassx.org/issues/540
KeePass feature: http://keepass.info/help/v2/entry.html (Advanced -> Custom Strings)

**Comment by droidmonkey** [comment]
I think there is slight confusion here. The attributes are **stored** encrypted in the database, but display as clear text. We really just desire the attributes to be displayed with asterisks or some other masking technique. Is that correct?

**Comment by TheZ3ro** [comment]
Are you sure that they are stored encrypted?
If so, the problem is only for the UI.

> We really just desire the attributes to be displayed with asterisks or some other masking technique. Is that correct?

Yes, but it depends.
If I want to store a note or a message it's fine to have it clear-text, 
If I want to store a Password or a PIN we should use the same UI as every password field.
But I don't think we can "detect" what user want.

Ideas?

**Comment by magkopian** [comment]
There are a few things such as access tokens, that technically aren't passwords so it would make sense to store them on the `Additional Attributes` section. But on the other hand, they should not be displayed by default as plain text when the user opens the `Advanced` tab.

**Comment by droidmonkey** [comment]
Updated the title to reflect the request. Attributes are stored in the database file as encrypted. I checked the code, everything written to the database format (CSV, KeePass1, KeePass2) is passed through the encryption output stream prior to writing. This includes attributes.

The question becomes, do we want to add a feature to enable the visible protection of certain attributes similar to password protection. Or protect the display of ALL attributes as if they were passwords.

**Comment by TheZ3ro** [comment]
I personally find usefull to store note in the additional attributes so I don't think we should protect ALL attributes as password. If we can protect the display of only certain attribute it will be good, otherwise there is no Issue.

Maybe the good thing will be something like:
When adding an additional attribute the user select if it's Text or Password and we store that information somehow and so KeePassXR will show the correct UI for that attribute
(this must be backward compatible)

**Comment by droidmonkey** [comment]
Dropping this here as it may be useful in this issue: https://sourceforge.net/p/keepass/discussion/329221/thread/fd78ba87/

**Comment by droidmonkey** [comment]
It looks like there is already a way to "protect" attributes (along with other entry data fields) that is saved in the database, but this does not translate into anything in the GUI. I think it would be pretty trivial to add a "protect" checkbox in the add/edit attributes gui area and if marked protected it would display the data as a password (ie astericks) unless unmasked by the user.

https://github.com/keepassxreboot/keepassx/blob/develop/src/core/EntryAttributes.cpp#L71

https://github.com/keepassxreboot/keepassx/blob/develop/src/gui/entry/EditEntryWidget.cpp#L406

**Comment by lebarondemerde** [comment]
Hi,

Keepass2Android has a feature like this. It allows to add a additional "string" with name, value, and if it should display masked or not.

I use it for a second password I need, and that password appear on "Additional Attributes" on KeePassX.

_IMHO, Keepass2Android have a very good usuability. It is like comparing apples and oranges, but the experience on it is a lot of better than on KeePassX_.

Cheers!

**Comment by anatoli26** [comment]
If an attribute is masked, there should also be buttons to copy its value to clipboard (without unmasking it, like the main pass) as well as (optionally) an option to perform auto-type using the attribute's value.

Another consideration: right now the value field is a multi-line text. In case of masked values, I believe it should be single-line.

**Comment by TheZ3ro** [comment]
I'm working on auto-type using attribute but this is a separate issue
