### ISSUE TITLE
Snap Old version of libgcrypt

### ISSUE THREAD

**Issue by gitarra** [keepassxreboot/keepassxc#450]
The Snap uses an old beta version of libgcrypt.

![screenshot](https://cloud.githubusercontent.com/assets/4739888/24549591/b37bb93c-1622-11e7-9a29-a04949bd0a1e.png)

**Comment by TheZ3ro** [comment]
For the next version @droidmonkey will address this (since he is the maintainer of the snap ;)

**Comment by droidmonkey** [comment]
Come to find out, much to my chagrin, this is the version reported by gcrypt.h in Ubuntu 16.10.

Even though the package lists the version as 1.7.2, gcrypt.h indicates it is 1.7.2-beta. I have filed a bug report with the ubuntu team.

https://bugs.launchpad.net/ubuntu/+source/libgcrypt20/+bug/1700157

**Comment by droidmonkey** [comment]
Ugh, 17.04 suffers from the "same" issue... gcrypt.h is reporting the version as 1.7.6-beta

**Comment by adatum** [comment]
I'm trying to install v2.2.0 (never have I been so impatiently excited for a package release!) from https://github.com/magkopian/keepassxc-debian/releases/tag/2.2.0-1 on Ubuntu 16.04 32-bit, and I get 

> Error: Dependency is not satisfiable: libgcrypt20 (>=1.7.0)

> $ dpkg -l | grep libgcrypt
ii  libgcrypt11:i386                                            1.5.3-2ubuntu4.4                                      i386         LGPL Crypto library - runtime library
ii  libgcrypt11-dev                                             1.5.4-3+really1.6.5-2ubuntu0.2                        all          transitional libgcrypt11-dev package
ii  libgcrypt20:i386                                            1.6.5-2ubuntu0.2                                      i386         LGPL Crypto library - runtime library
ii  libgcrypt20-dev                                             1.6.5-2ubuntu0.2                                      i386         LGPL Crypto library - development files

How do I get libgcrypt20 >=1.7.0 on 16.04?
