### ISSUE TITLE
Adding a small wordlist doesn't work and doesn't notify the user about it.

### ISSUE THREAD

**Issue by hialvaro** [keepassxreboot/keepassxc#4500]
### **Expected behaviour**
Adding a **999** words word-list should generate word passwords or give a detailed error of why this is not possible.

### **Current behaviour**
Adding a **999** words word-list generates an invisible error (the list just doesn't generate any word) and the user doesn't know what is happening. The minimum seems to be **1000** words.

### **Possible solution**
Users should be able to add at least a 500 words word-list (imo) and still be able to use it. If for some reason this is not possible the user should be notified that the wordlist is shorter than the minimum accepted.

### **Steps to Reproduce**
I'm on Arch Linux and I also tested on Windows (portable version). Create a text file and set up a list with 999 words. Place the word list on `/usr/share/keepassxc/wordlist`. Start KeepassXC and go to generate password. Select the new wordlist. See that nothing shows up and the slider seems broken.

### **Context**
Trying to set up a personalised wordlist and realising it wasn't working. After some time testing I realised that it was the length of the wordlist.

**Comment by droidmonkey** [comment]
Will be solved with #988
