### ISSUE TITLE
Force KeePassXC to front when called from browser extension

### ISSUE THREAD

**Issue by F3000** [keepassxreboot/keepassxc#4502]
At the moment when Windows is locked and a user login back , KeepassXC is also locked .so he sees at a login page a red icon . 

Under Windows 10 when I click on that red button on a website only the KeepassXC taskbar icon is blinking to indicate that I have to unlock the database with my password . 

Would be nice when it’s possible to bring the KeepassXC window in the foreground at this moment 👍

**Comment by varjolintu** [comment]
AFAIK that is now possible with Windows.

**Comment by droidmonkey** [comment]
It's hit or miss, sometimes it works great. Maybe we can temporarily make the window always on top?

**Comment by varjolintu** [comment]
That could be tried at least.

**Comment by droidmonkey** [comment]
No longer a problem with the new DB Open Dialog usage.
