### ISSUE TITLE
Export Site Settings and Userdefined Fields

### ISSUE THREAD

**Issue by RolandSM** [keepassxreboot/keepassxc#4503]
Hello,

on my systems I use Chrome and also Firefox.

In Firefox (main browser) I have a big list of site-settings.

It would be great, if these entries and also userdefined fields are also exported and imported into another browser.

Also I found two times the "save only domain" entry in category "save login data" and also again in "advanced settings"

Greets

**Comment by droidmonkey** [comment]
This is for the browser extension? That already exists, go to the bottom of the extension settings page.

**Comment by RolandSM** [comment]
A true... A browser restart was required after importing...
