### ISSUE TITLE
Some strings are in English despite being translated

### ISSUE THREAD

**Issue by Matthaiks** [keepassxreboot/keepassxc#4504]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
All translatable strings should be translated in KeePassXC when its language files are complete

## Current Behavior
[NOTE]: # ( Tell us what actually happens )
Some strings are in English despite being translated into other languages and present in the language files.

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
Switch to the 100% translated language (for instance, Polish or German) and check these strings in KeePassXC 2.5.3:

From 'Browser Integration'

> KeePassXC-Browser is needed for the browser integration to work.
> Download it for %1 and %2. %3
> 

From 'Encryption Settings'

> AES: 256-bit
> Twofish: 256-bit
> ChaCha20: 256-bit
> 
> Argon2 (KDBX 4 – recommended)
> AES-KDF (KDBX 4)
> AES-KDF (KDBX 3.1)
> 

From 'Secret Service Integration'

> 
> File Name
> Group
> Application
> Manage
> None
> Edit database settings
> Lock database
> Unlock to show
> Unlock database to show more information

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.5.3
Revision: f8c962b

Qt 5.12.5
Debugging mode is disabled.

Operating system: Ubuntu Focal Fossa (development branch)
CPU architecture: x86_64
Kernel: linux 5.4.0-18-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.5

**Comment by phoerious** [comment]
Translations are managed by volunteers on Transifex and completeness depends on their progress. If some strings are missing, it's not a hug.

**Comment by droidmonkey** [comment]
Are we sure that the secret service strings are wrapped in tr(...)?

**Comment by Matthaiks** [comment]
@phoerious Those strings aren't missing, they're translated but KeePassXC doesn't show them.

**Comment by phoerious** [comment]
Then they will be included in the next release.

**Comment by Matthaiks** [comment]
I've checked translations files from keepassxc-2.5.3-src.tar.xz. They're included already. However, KeePassXC 2.5.3. shows those strings in English.

**Comment by phoerious** [comment]
AES: 256-bit, Twofish: 256-bit, ChaCha20: 256-bit, AES-KDF (KDBX 4), and AES-KDF (KDBX 3.1) are the same for all languages, there is nothing to translate. 

Argon2 (KDBX 4 – recommended) is translated for me, although I can see that it isn't when advanced settings are on, so that may actually be a thing that should be fixed.

**Comment by Matthaiks** [comment]
In Polish, AES-KDF (KDBX 4) and AES-KDF (KDBX 3.1) are the same, but:
> AES: 256-bitowy
> Twofish: 256-bitowy
> ChaCha20: 256-bitowy

**Comment by Matthaiks** [comment]
KeePassXC 2.6.3
![KPXC](https://user-images.githubusercontent.com/3577122/104488467-ab454680-55ce-11eb-8971-554f33a84740.png)

"Hide Usernames" and "Hide Passwords" are present and translated in the PO file, "Always on Top" is missing entirely. All of them are in English only, though.
