### ISSUE TITLE
Snap No tray icon

### ISSUE THREAD

**Issue by gitarra** [keepassxreboot/keepassxc#451]
The Snap does not show a tray icon.

![screenshot2](https://cloud.githubusercontent.com/assets/4739888/24549686/2dc55950-1623-11e7-9e28-db628121f0a4.png)

![screenshot](https://cloud.githubusercontent.com/assets/4739888/24549668/0f577408-1623-11e7-8377-d9aaccbbe83b.png)

**Comment by droidmonkey** [comment]
I cant figure out how to make it work, tried several ways. Any ideas?

**Comment by TheZ3ro** [comment]
Can you verify that those file exists on you system?
`/usr/share/keepassxc/icons/application/24x24/apps/keepassxc-locked.png`
`~/.local/share/pixmaps/appimagekit-keepassxc.png`

**Comment by droidmonkey** [comment]
They exist in the snap, but for whatever reason the snap isn't exposing them properly...

**Comment by TheZ3ro** [comment]
This is maybe related to #102 or #194

**Comment by droidmonkey** [comment]
Currently working in 2.2.0 snap.
