### ISSUE TITLE
[FeatureRequest] Partial lock of data base (primarily for Yubikey) or challenge to release single passwords

### ISSUE THREAD

**Issue by riedel** [keepassxreboot/keepassxc#4512]
## Summary
It would be great if the database could be "soft"-unlocked by touching the Yubikey. (Alternatively a key could only be released/shown upon touch.)

When saving the database you already only need to touch the Yubikey (actually to increment the HOTP).  

It could also be used to encourage longer password if data is at rest vs the interactive use: Some mobile implementation e.g. already only ask for the last part of a password.

## Desired Behavior

I would want to use a hardware token as an UX improvement not only as an additional layer of security: Unlocking the database easily more often or touching a physical button for PW release.

## Possible Solution
One possible solution (that could be extended to also PIN only mechanism) is to have stages of unlock dialogs and keep either only the computed key or the database in memory.

Onother solution is to actually add another layer of security when releasing keys by always asking the token e.g. also within a 30 sec time window (A user in this case would set a longer timeout).

## Context
While I am at my PC the hardware token provides enough security as a second factor. Asking the HW token on key release would further prevent remote attacks via the UI. If my PC is unattended only having a hardware token is not a good idea.

**Comment by droidmonkey** [comment]
This is called Quick Unlock and already tracked in an issue.

**Comment by riedel** [comment]
Thanks for pointing out #488 (I somehow wasn't able to find it with the keywords I was using!)
