### ISSUE TITLE
Application sporadically crashes with a Windows memory read error

### ISSUE THREAD

**Issue by nniesen** [keepassxreboot/keepassxc#4514]
## Expected Behavior
Application doesn't sporadically crash.

## Current Behavior
Application crashes with a Windows Application Error on memory read when it's not the active application or being directly used. It's possible the browser extension is accessing the application.

Error Message: "The instruction at 0x00000000004D3342 referenced memory at 0x0000000000000004. The memory could not be read."
![image](https://user-images.githubusercontent.com/4194475/77855491-61fa4680-71b6-11ea-9334-bcffb762b568.png)

## Possible Solution
None but I don't expect this to be easy to solve given the limited information.

## Steps to Reproduce
1. N/A.

## Context
1. My databases and key files are on a NAS.
2. It happens either while using another application, possibly the browser, or when I wake the PC. I don't recall it ever happening while directly using the application.
3. It's happened 5-10 times since using 2.5.3. I'll try to pay more attention to what was running.
4. I didn't see anything in the Windows Event Viewer but next time will check that right away.

## Debug Info
KeePassXC - Version 2.5.3
Revision: f8c962b

KeePassXC-Browser - 1.6.2
Operating system: Win32
Browser: Chrome/Chromium 80.0.3987.132

Qt 5.13.2
Debugging mode is disabled.

Operating system: Windows 10 (10.0)
CPU architecture: x86_64
Kernel: winnt 10.0.18362

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.5

**Comment by droidmonkey** [comment]
Yah this is already reported. I cannot isolate the issue and made substantive changes in the develop branch to try and mitigate it. If I could reproduce this would be fixed.

**Comment by nniesen** [comment]
Thanks. Can you link the duplicate?

**Comment by droidmonkey** [comment]
I don't have a specific issue number. I can't isolate your issue anyway with the data provided (not your fault).

**Comment by nniesen** [comment]
No response needed, just logging another occurrence in another version.

Happened again with 2.5.4 with KeePassXC in the background and switching browser tabs. I'm assuming it's probably something triggered by the browser plugin but really have no idea.

I did find it the Windows event log this time but that didn't provide any more detail: 
 <EventData>
  <Data Name="Caption">KeePassXC: Windows - Application Error</Data> 
  <Data Name="Message">The instruction at 0x0000000000BF3B12 referenced memory at 0x0000000000000004. The memory could not be read. Click on OK to terminate the program</Data> 
  </EventData>

KeePassXC - Version 2.5.4
Revision: c023bf9

Qt 5.14.2
Debugging mode is disabled.

Operating system: Windows 10 Version 1903
CPU architecture: x86_64
Kernel: winnt 10.0.18362

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.5

**Comment by droidmonkey** [comment]
There has been theories that the browser extension is triggering this behavior. However I have never witnessed it and I use the extension daily. Very strange
