### ISSUE TITLE
Catalina 10.15.4 breaks Touch ID unlocking

### ISSUE THREAD

**Issue by guardiande** [keepassxreboot/keepassxc#4515]
## Expected Behavior

After enabling touch id unlocking and unlocking the database initially with the passphare, entering an empty password should allow touch id unlocking.

## Current Behavior

The touch id unlock dialog does not show. The database cannot be unlocked by touch id.

## Possible Solution
None known.

## Steps to Reproduce
* Start KeepassXC
* Unlock the database by passphrase
* Lock the database
* Leave the passphrase empty and hit return the passphrase field

## Debug Info
KeePassXC - Version 2.5.3-2
Revision: f8c962b

Qt 5.14.1
Diagnosemodus ist deaktiviert.

Betriebssystem: macOS 10.15.4
CPU-Architektur: x86_64
Kernel: darwin 19.4.0

Aktivierte Erweiterungen:
- Auto-Type
- Browser-Integration
- SSH-Agent
- KeeShare (bestätigtes und unbestätigtes Teilen)
- YubiKey
- TouchID

Kryptographische Bibliotheken:
 libgcrypt 1.8.5

**Comment by droidmonkey** [comment]
We know, this was the casualty of getting the app working again with the new security modal.

**Comment by marcofranssen** [comment]
@droidmonkey are there plans to bring it back? Is it possible to bring this back?

**Comment by droidmonkey** [comment]
We submitted a bug report to Apple regarding their entitlements issue.

**Comment by microcreators** [comment]
Just to make it clear, I see the same in macOS 10.14.6 (latest Mojave). Thanks.

**Comment by AriaLyy** [comment]
macOS 10.14.6 the same

**Comment by TMA64** [comment]
If it helps, i have the same issue with 2.5.2 and 2.5.3.x on latest macOS 10.15.4. 
I reinstalled 2.5.1 and it works great.

**Comment by microcreators** [comment]
> If it helps, i have the same issue with 2.5.2 and 2.5.3.x on latest macOS 10.15.4.
Funny enough - 2.5.2 works for me.

**Comment by TMA64** [comment]
> > If it helps, i have the same issue with 2.5.2 and 2.5.3.x on latest macOS 10.15.4.
> 
> Funny enough - 2.5.2 works for me.

I can confirm, i reinstalled 2.5.2, it works too.

**Comment by AriaLyy** [comment]
2.5.2 works for me.

**Comment by usr42** [comment]
2.5.2 is not working on Catalina 10.15.4 for me. 
I get following error: 
“KeePassXC.app” cannot be opened because the developer cannot be verified.
macOS cannot verify that this app is free from malware.

@AriaLyy  @microcreators You are not running Catalina (10.15.4), aren't you? It makes sense for me, that the older version is running for you.

@TMA64 You said you are running 10.15.4 Catalina, aren't you? And 2.5.2 and 2.5.1 are running for you? Can you provide me the link, where you downloaded the working version?

**Comment by usr42** [comment]
Now that I removed 2.5.3-2 to test the older versions, I cannot reinstall this version manually either.
The strange thing is that I can still install it with brew.

**Comment by usr42** [comment]
I managed to install 2.5.2 with brew and it's also working for me:
```bash
brew cask uninstall keepassxc
brew cask install https://raw.githubusercontent.com/caskroom/homebrew-cask/8bea804de422d0d70057943d57f3a5a194aad258/Casks/keepassxc.rb
```

I still don't get why I can install it via brew but not manually. Does anyone has an idea?

**Comment by TMA64** [comment]
@usr42 
https://github.com/keepassxreboot/keepassxc/releases/tag/2.5.2

**Comment by usr42** [comment]
@TMA64 Is a manual install working for you?

**Comment by TMA64** [comment]
@usr42 yes. Oh, i see my SIP is disabled. Maybe it has something to do with this.

**Comment by stormbeta** [comment]
Can confirm that downgrading back to 2.5.2 makes TouchID work on my 2019 MBP 16".

Running Catalina 10.15.4, original install via brew, downgrade via DMG.

**Comment by droidmonkey** [comment]
Locking this, thank you for all your input. @phoerious is working a solution with Apple engineers.

**Comment by phoerious** [comment]
Could somebody please test if TouchID is working again with this package? Thanks.
https://drive.google.com/open?id=1yk2raD_zpGeUzEii1Z_4hxvYVNzAO50t

**Comment by TMA64** [comment]
@phoerious great, worked for me. Latest macOS. SIP disabled.

**Comment by phoerious** [comment]
Thanks.

**Comment by usr42** [comment]
@phoerious Also worked for me with SIP enabled.
Before I could install it (move it to the Application folder) I had to manually open the application once via the context-menu->Open. Then the Application was validated and I was asked if I want to start this application which was downloaded from the internet.
After that the installation was successful and also the Touch ID is working again. 👍
