### ISSUE TITLE
Proper(?) workaround for #4398 (Not starting KeepassXC on OSX 10.15.4 or newer) with `brew cask reinstall --no-quarantine`

### ISSUE THREAD

**Issue by opntr** [keepassxreboot/keepassxc#4516]
There is an easier workaround for the #4398 issue with brew. As you can see, this is not the most elegant solution, because you disable on of Mac OSX's security function, but at least you can access your password.

``` bash
brew cask reinstall --no-quarantine KeePassXC
```

<img width="1920" alt="Screenshot 2020-03-29 at 21 12 34" src="https://user-images.githubusercontent.com/2576589/77858232-6e0bf580-7202-11ea-8df8-40d87d7c05c4.png">

**Comment by opntr** [comment]
After install it with the above parameters, it ends up with the following:

```
root@mongoose:/Applications# spctl --assess -vvvv /Applications/KeePassXC.app
/Applications/KeePassXC.app: accepted
source=Notarized Developer ID
origin=Developer ID Application: Janek Bevendorff (G2S7P7J672)
```

and for comparison, here is the `spctl` query for Sporify too:
```
root@mongoose:/Applications# spctl --assess -vvvv /Applications/Spotify.app
/Applications/Spotify.app: accepted
source=Notarized Developer ID
origin=Developer ID Application: Spotify (2FNC3A47ZF)
```

**Comment by phoerious** [comment]
Why are you creating a new issue for this? Brew reinstall has been discussed before.
