### ISSUE TITLE
Add views for tags

### ISSUE THREAD

**Issue by OLLI-S** [keepassxreboot/keepassxc#4517]
## Summary
Add at top of the groups a Quick View that shows all entries with a TOTP.

## Details
For many entries I have to copy the TOTP out of KeePassXC, because they are not automatically filled in the website or because I want to log into an application.
This forces me to search for the entry in KeePassXC and then to copy the TOTP code.

As a work around I created a new group called TOTP (luckily there is already an icon in KeePassXC that matched). Here I created for each service that offers TOTP a new (**duplicate**) entry containing just the name, the icon and the TOTP code:

![image](https://user-images.githubusercontent.com/8037790/77859677-1de56100-720b-11ea-8e4e-c52bdbe3ada1.png)

With this group I have quick access to those entries having a TOTP.
This is faster than searching for "*" and sorting the results by the column "TOTP".
And it is also faster than searching for the entry in the search field.

But I have all these entries twice in my database (one entry in the group "TOTP" containing just the TOTP and one entry in the original folder containing, also containing the TOTP code but also all other data like username and password).

It would be cool to have on top of the groups an entry called "TOTP".
This is **not a physical folder**, it is **just a view**.
Here all entries are displayed that have a TOTP stored.

The advantages are:
* I have no duplicate entries
* I have quick access to the TOTP entries
* It is just a view, nothing is stored in the KeePass database (no compatibility issues with other KeePass applications)

So please take this feature under consideration.
There can also be additional views like "Favorites" or "Insecure Passwords" that opens the report page.

**Comment by droidmonkey** [comment]
This is analogous to the way tags work in KeePass. I would argue that tags are the "views" you are seeking and would make grouping entries from across groups very easy.

**Comment by OLLI-S** [comment]
It would be cool when I could also add some "Views" (like groups) that just show all entries of a specific tag. Like in the screen shot above I could add a view for the tag "TOTP" and an other view for the tag "Favorite".
I saw that you already have the issue **Add Tag Feature** (#508) so I will rename this issue to "Add views for tags"
