### ISSUE TITLE
Snap does not register a MIME type for database files

### ISSUE THREAD

**Issue by gitarra** [keepassxreboot/keepassxc#452]
The Snap does not register a MIME type for the database files.

This means that my File Manager does not know what to do with the files and does not show an icon for them.

![screenshot](https://cloud.githubusercontent.com/assets/4739888/24549811/bb4822e4-1623-11e7-81bc-c86eb2348997.png)

**Comment by usinggh** [comment]
Confirmation: Same with version 2.1.4

**Comment by droidmonkey** [comment]
Fixed in v2.2.2 (some distros may require manual linking the kdbx to keepassxc snap)
