### ISSUE TITLE
add run at startup to Settings, just like Keepass

### ISSUE THREAD

**Issue by eturk1** [keepassxreboot/keepassxc#4520]
[TIP]:  # ( Provide a general summary of the feature in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Summary
Add a new checkbox in Options to automatically start with Windows.
having to manually make the app start at boot is like being stuck in the 1990s.

## Desired Behavior
Keepass has this setting. Make it at least as modern as Keepass.
![image](https://user-images.githubusercontent.com/525280/77865255-473dc700-71e2-11ea-8105-025d73833472.png)

## Possible Solution
Could probably look at the code for Keepass so it not too confusing for the devs.

Please do not just mark this issue in as the same as other requests that were ignored, in a circular loop with some other request that points to another request that was just closed & ignored.

**Comment by droidmonkey** [comment]
Duplicate request
