### ISSUE TITLE
Refresh connection between browser addon and keepasxc on clicking the autofill icon

### ISSUE THREAD

**Issue by MrRinkana** [keepassxreboot/keepassxc#4521]
## Summary
If you opened keepasxc after loading in a site you want to login on, the autofill icon (on login field, not the one in the addons field) is red and cannot fill in information (states "database is locked"). To solve this you have to click the keepassxc addon and then "refresh" and then finally the autofill icon that now is green.

My feature request is that clicking the autofill icon while its red has the same effects as clicking "reload" in the addon menu.

Additionally a message informing you something along the lines of "Failed to connect to database" could be added if the refresh "fails".

## Desired Behavior:
Clicking the autofill icon, present on login fields, while red refreshes addon connection to keepassxc application (addon to database). 

Additionally:
If the refresh fails to connect to the application, a message informing you of that pops up.

## Context
This would be convenient as it reduces the amounts of clicks, and for laptopusers with a touchpad like me, also how much the mouse is moved; allowing for faster logins. I believe this feature has a very high convience-to-work factor and would love to see it added.

**Comment by droidmonkey** [comment]
This is already reported in the browserb extension repository.
