### ISSUE TITLE
Unable to save at all after trying to 'save as' with an invalid name

### ISSUE THREAD

**Issue by ameyer0** [keepassxreboot/keepassxc#4525]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
When trying to 'save as' the active database with an invalid file name, it should fail, and if 'cancel' is selected after that, future saves should use the original file name.

## Current Behavior
[NOTE]: # ( Tell us what actually happens )
If 'save as' fails and is cancelled, future saves will attempt to use the invalid file name, making saving impossible except through 'save as.'

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )
The 'save as' method changes the database path to the user's input before attempting to save, but doesn't change the path back when the save fails.

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1. Database > Save database as
2. Enter an invalid file name (e.g. does_not_exist/database.kdbx)
3. Attempt to save at least once, then cancel
Attempting to save (except through Save As) will now fail

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )
It's a bit of an obscure situation, but if a user encounters it they could lose data (since it also affects autosaves and saving on close).

**Comment by droidmonkey** [comment]
This is already fixed in 2.6.0 develop.

**Comment by ameyer0** [comment]
I just checked, I'm still able to replicate the issue in the latest Linux snapshot.
