### ISSUE TITLE
Connecting to database 2.5.3-2 macOS 10.15.4 firefox 74

### ISSUE THREAD

**Issue by a7hybnj2** [keepassxreboot/keepassxc#4527]
## Expected Behavior
I expected it to work like it did before I upgraded to macOS 10.15.4 which broke keepassxc 2.5.3 which made me update to keepassxc 2.5.3-2 which broke the browser extension.

## Current Behavior
When I go to `settings - connected databases` and click `connect` nothing happens.  
When I go to `settings - general - updates` it lists `You are running KeePassXC version: unknown`  
I have installed keepassxc via .dmg as well as with brew and neither effect the issue.

## Debug info

KeePassXC - 2.5.3-2 (listed in the about page as just 2.5.3 but on the download it specified the -2)
KeePassXC-Browser - 1.6.2
Operating system: Mac 10.14.4
Browser: Firefox 74.0

**Comment by phoerious** [comment]
This is most likely a result of #4398. We do not have a fix for it yet and are awaiting a response from Apple.

**Comment by droidmonkey** [comment]
I couldn't replicate the problem.

**Comment by a7hybnj2** [comment]
@droidmonkey wow! Guess it had been so long since I setup keepass with the browser addon I did not remember having to turn it on from the keepass settings. It is connecting now. Thanks.

**Comment by droidmonkey** [comment]
Perhaps the change in entitlements caused issues with the config file, have no idea.

**Comment by phoerious** [comment]
Alright, good to know that the entitlements patch did not also break the browser extension.
