### ISSUE TITLE
Prompt to migrate browser settings must be more specific, and should behave differently.

### ISSUE THREAD

**Issue by morgansimonsen** [keepassxreboot/keepassxc#4528]
## Expected Behavior
The migrate browser settings dialogue should explain that it will take your existing KeePassHTTP settings and convert them to KeePassXC-Browser settings, and then _destroy_ the old settings, with no way to undo the change.

## Current Behavior
The migrate browser settings dialogue does not explain what is actually happening.

## Possible Solution
It is fine to migrate the existing KeePassHTTP settings to KeePassXC-Browser, but the default should be to just migrate, and not destroy the data. Both types of settings can live in the DB. If you are eager to remove the old settings, the user should be informed specifically what that means and then be given an additional choice of removing them.

## Steps to Reproduce
Hit 'yes' in the migration box.

## Context
This really forked my KeePass DB. Now I have 500 entries that don't work with regular KeePass+KeePassHTTP anymore, which I really need them to. (And please don't tell me that I can run KeePassXC on different OS', or that KeePassXC is better. I know that, it's not what I want to do, and it's not a fix in this case.) It boils down to good programming behavior; don't destroy data.

**Comment by varjolintu** [comment]
The button and dialog says _Move_, but yes, it doesn't mention destroying the old data.

Maybe instead of destroying the old settings entry, it could be moved to Recycle bin.

**Comment by droidmonkey** [comment]
You haven't been backing up your database? If you are storing in a cloud provider you probably have a versioned database and just need to pull a version down. 

Second, there is a KeePass plugin yo interface with our browser extension, so just transfer over. Our extension is way more secure and functional than keepasshttp.

**Comment by morgansimonsen** [comment]
*sigh* This is not a matter of backing up or not, nor whether your extension is better than anything else. The fact remains; data was destroyed. Users should be properly notified.

**Comment by varjolintu** [comment]
Or: we just move the old data to Recycle Bin and not destroy it directly, like I suggested earlier.

**Comment by droidmonkey** [comment]
I understand your frustration but I am compelled to defend ourselves here... we do not make any claim that your existing settings would remain where they are. We also use the terms "migrate" and "move" which generally speaking do not imply retaining information where it is currently. Technically we are not destroying data, we move it into a different location of the database. We do not support simultaneously running the HTTP agent and our own agent, this has been discussed before on this issue board.

At this point we can change the wording, but the cats out of the bag for the past 2 years on functionality and it makes no sense to change the way it works.
