### ISSUE TITLE
KeePassXC 2.5.3 crashes on launch on macOS 10.14.6

### ISSUE THREAD

**Issue by sreenadhp** [keepassxreboot/keepassxc#4529]
I am having a similar issue to [4398](https://github.com/keepassxreboot/keepassxc/issues/4398), but on 10.14.6 too. Despite installing it via `brew cask`, I could not find it when I ran `brew cask list`. I fixed it by [reinstalling it via brew](https://github.com/keepassxreboot/keepassxc/issues/4398#issuecomment-604284180).

> brew cask reinstall keepassxc

Its fine for now, but not sure if the issue with comeback again. It's a pain as all my password is in it and I have to fix it before I can do my task.

I am curious to understand the cause. I am assuming its something Mac is doing, but what. Its not just a Catalina issue, I am on Mojave. I faced this issue after installing a security update from Apple about ~2gb. I could not find the details of the patch to share it. What all softwares will be at risk?

## Debug Info
Process:               KeePassXC [42787]
Path:                  /Applications/KeePassXC.app/Contents/MacOS/KeePassXC
Identifier:            org.keepassx.keepassxc
Version:               ???
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           KeePassXC [42787]
User ID:               501

Date/Time:             2020-03-31 15:37:36.758 +0400
OS Version:            Mac OS X 10.14.6 (18G4032)
Report Version:        12
Anonymous UUID:        888EB6E4-E576-0581-6D21-464FF4B841E8

Sleep/Wake UUID:       61E67791-0546-4A0B-A13E-3F46E54C65CD

Time Awake Since Boot: 1500 seconds
Time Since Wake:       1100 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (Code Signature Invalid)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace CODESIGNING, Code 0x1

kernel messages:

VM Regions Near 0 (cr2):
--> 
    __TEXT                 000000010f2fa000-000000010f68c000 [ 3656K] r-x/r-x SM=COW  

Thread 0 Crashed:
0                                 	0x0000000114612000 _dyld_start + 0

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0x0000000000000000  rcx: 0x0000000000000000  rdx: 0x0000000000000000
  rdi: 0x0000000000000000  rsi: 0x0000000000000000  rbp: 0x0000000000000000  rsp: 0x00007ffee0905c00
   r8: 0x0000000000000000   r9: 0x0000000000000000  r10: 0x0000000000000000  r11: 0x0000000000000000
  r12: 0x0000000000000000  r13: 0x0000000000000000  r14: 0x0000000000000000  r15: 0x0000000000000000
  rip: 0x0000000114612000  rfl: 0x0000000000000200  cr2: 0x0000000000000000
  
Logical CPU:     0
Error Code:      0x00000000
Trap Number:     0

Binary Images:
       0x10f2fa000 -        0x10f68bfff + (0) <16AE8CED-0E4C-3291-AE43-913B0D7192FF> 
       0x114611000 -        0x11467b70f + (655.1.1) <C192CA31-D059-3770-9882-D864FEFA0C96> 

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 956
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=4552K resident=0K(0%) swapped_out_or_unallocated=4552K(100%)
Writable regions: Total=8404K written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=8404K(100%)
 
                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
STACK GUARD                       56.0M        1 
Stack                             8192K        1 
__DATA                             372K        4 
__LINKEDIT                         468K        2 
__TEXT                            4084K        2 
shared memory                        8K        2 
===========                     =======  ======= 
TOTAL                             68.8M       12 

Model: MacBookPro11,1, BootROM 159.0.0.0.0, 2 processors, Intel Core i5, 2.4 GHz, 8 GB, SMC 2.16f68
Graphics: kHW_IntelIrisItem, Intel Iris, spdisplays_builtin
Memory Module: BANK 0/DIMM0, 4 GB, DDR3, 1600 MHz, 0x80AD, 0x484D54343531533641465238412D50422020
Memory Module: BANK 1/DIMM0, 4 GB, DDR3, 1600 MHz, 0x80AD, 0x484D54343531533641465238412D50422020
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x112), Broadcom BCM43xx 1.0 (7.77.61.3 AirPortDriverBrcmNIC-1305.9)
Bluetooth: Version 6.0.14d6, 3 services, 27 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
Serial ATA Device: APPLE SSD SM0256F, 251 GB
USB Device: USB 3.0 Bus
USB Device: Apple Internal Keyboard / Trackpad
USB Device: BRCM20702 Hub
USB Device: Bluetooth USB Host Controller
Thunderbolt Bus: MacBook Pro, Apple Inc., 17.2

**Comment by phoerious** [comment]
Please read the pinned issues.
