### ISSUE TITLE
I use the latest version, I would like to ask how to chromeipass and keepassxc configuration

### ISSUE THREAD

**Issue by xingxing9688** [keepassxreboot/keepassxc#453]
If you are using several KeePass databases you can define a specific icon-color to each of them. 
This will help you to easily determine from which database the credentials are retrieved.  ？

**Comment by TheZ3ro** [comment]
Can you re-elaborate the request? Sorry but I can't understand what you mean

**Comment by droidmonkey** [comment]
This is a feature in the chromeipass plugin itself
