### ISSUE TITLE
Add support for `Page Up / Down` and `Home / End` keys in Auto-Type entry selector

### ISSUE THREAD

**Issue by codekandis** [keepassxreboot/keepassxc#4530]
## Summary
In the current debian stock version `2.3.4+dfsg.1-1` it's a working feature.

If I have multiple entries matching an auto type criteria and my search keyword I can use `Page Up / Down` and `Home / End` to get faster to the requested database entry in the list. In the latest version `2.5.3` (tested on Windows 10 only) it's not working.

An example: As a software developer I'm using KeePassXC for several virtual environments provisioned with Ansible. So I have tons of database entries matching my terminal title to store the unique Ansible Vault passwords. While working with the keyboard I'm selecting the requested entry with the `Up / Down` keys which become often annoying.

## Desired Behavior
Please re-implement the auto type list navigation with `Page Up / Down` and `Home / End`.

**Comment by droidmonkey** [comment]
This is likely due to differences between Linux and Windows default keyboard shortcuts. We don't register any special shortcuts for this dialog. Try using Ctrl+Up/Down for top/bottom of list on Windows.

**Comment by droidmonkey** [comment]
Confirmed not even Ctrl+Up/Down works. This will need some investigating.

**Comment by codekandis** [comment]
I tried several of the common keystrokes like "Shift+U/D", "Ctrl+U/D", "Alt+U/D" and "U/D" with all possible mixed modifiers. None of them were working as expected.

I know there are ambivalent keystroke interpretations of all OS. But in my opinion the keystrokes for item list navigation are too overall-OS-common.

**Comment by codekandis** [comment]
I did try it on Debian today. It's the same OS config as used with the old version. With the mentioned old version "paging" is working fine. With the latest one it's not.

Now I can say it's not OS dependent.
