### ISSUE TITLE
SSH agent keys get removed even when other databases are closed

### ISSUE THREAD

**Issue by snstamml** [keepassxreboot/keepassxc#4532]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
SSH agent keys from databases B, C, D... should not be removed from the key agent when database A is closed. Only keys from database A should be removed.

## Current Behavior
When closing database A, SSH agent keys from database B (or any other database) registered with the key agent are removed.

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )
Check from which database an agent key derives from, and remove only those that come from the database that is being closed.

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1. Create and open databases A and B
2. Create an entry in database B with a "SSH Agent" key and click "Add to agent"
3. Check the key list in the SSH agent (e.g. Pageant on Windows)
4. Close database A
5. Check the key list in the SSH agent

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )
Every time any database is closed, all keys from the other databases need to be manually re-added to the key agent.

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.5.3
Revision: f8c962b

Qt 5.13.2
Debugging mode is disabled.

Operating system: Windows 10 (10.0)
CPU architecture: x86_64
Kernel: winnt 10.0.18363

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.5

**Comment by hifi** [comment]
We don't currently track the database a key was added from which causes this issue.

It either needs to be "hacked" in as an extra argument to `SSHAgent::addIdentity` or a more creative solution be figured out. I don't like changing the API just to have an extra argument for this purpose but it may be an interim solution.

Whatever the final solution is the corner case of not having a database when adding a key (however unlikely) needs to be accounted for.

**Comment by droidmonkey** [comment]
Recommend tying it to the Database UUID.
