### ISSUE TITLE
Health Check - Exclude MULTIPLE entries from check

### ISSUE THREAD

**Issue by OLLI-S** [keepassxreboot/keepassxc#4533]
## Summary
Allow users to exclude multiple entries from health check with one mouse click.

## Details
If you implement the feature **Health Check - Exclude entries from check** (#4168) then it might be an idea that you allow the user to exclude multiple entries from the health check with one mouse click.
Therefore users can select multiple entries in the password list (like the result of the search or multiple entries in a group), press the right mouse button ans select "Exclude from Health Check".
Then the new flag is set for these entries.

As a logical consequence you should also add "Include in Health Check" so users can include multiple items that were excluded before.
Here I would always offer these two entries, no matter if the selected entry/entries are included or excluded. Otherwise you have to check the status of all selected entries.

**Comment by DJCrashdummy** [comment]
IMHO it would be awesome to be able exclude complete folders from health check, auto-type, browser-extension etc.... but i'm not sure if this is possible resp. fits the "idea of saving flags/keys/settings per item". :thinking: 
alternatively it would be just a kind of a batch editing, as already suggested at this issue.

**Comment by OLLI-S** [comment]
Excluding an complete folder would help a lot, because I have all expired entries in one folder.

**Comment by droidmonkey** [comment]
We decided not to do this because you could inadvertently exclude tons of entries. However with the "Show excluded" option that is alleviated. We can implement this

**Comment by OLLI-S** [comment]
Thank you for planning to implement this feature.
