### ISSUE TITLE
Password fields on Mac do not accept Complex Modification Rules of Karabiner Elements

### ISSUE THREAD

**Issue by Xarno** [keepassxreboot/keepassxc#4534]
##  Setup
I use Karabiner Elements (https://github.com/pqrs-org/Karabiner-Elements/) to use Neo Keyboard Layout (https://neo-layout.org/ ) on Mac OS 10.15.4. 
For that to work I also need the complex modifications for neo:
https://ke-complex-modifications.pqrs.org/?q=neo

I have enabled this rule: „Prevent all layer 3 keys from being treated as option key shortcut“
otherwise I press shortcuts for any Key on layer 3.

## Current Behavior
Under this Setup all Password fields in Keepass XC do not input the correct character, when the field is masked. 
If I reveal the password I can see keys from layer 1. (In the case of neo Layer 1 contains small letters, Layer 3 contains Symbols like „[]<>!?+“.) 
If I input Layer 3 keys to revealed password fields the correct character shows up.

It is not a problem with any system or browser or other app password field. The recieve the typed key from Layer 3.

## Steps to Reproduce
1. Install Neo Layout to have a Layer 3 https://github.com/jgosmann/neo2-layout-osx
2. Install Karabiner Elements https://karabiner-elements.pqrs.org/
3. Install Neo 2 komplex Modifications https://ke-complex-modifications.pqrs.org/?q=neo
4. In Karabiner Elements komplex modifications enable „Neo 2 mod 3 and 4 key“ (either) and  „Prevent all layer 3 keys from being treated as option key shortcut”
5. Go to a Password field, hold Caps Lock or # key and then press any key. 
6. Unmask the password field. If you see letters and not symbols then there is this bug.
7. Try with keychain app or browser to see that it only happens on Keepass XC.

## Debug Info
KeePassXC - Version 2.5.3
Revision: f8c962b

Qt 5.14.1
Diagnosemodus ist deaktiviert.

Betriebssystem: macOS 10.15
CPU-Architektur: x86_64
Kernel: darwin 19.4.0

Aktivierte Erweiterungen:
- Auto-Type
- Browser-Integration
- SSH-Agent
- KeeShare (bestätigtes und unbestätigtes Teilen)
- YubiKey
- TouchID

Kryptographische Bibliotheken:
 libgcrypt 1.8.5

**Comment by droidmonkey** [comment]
This is a Qt bug and has been reported to them already.

**Comment by Xarno** [comment]
Thanks for looking into it.
Crosslinks:
#2452 
https://bugreports.qt.io/browse/QTBUG-73363
