### ISSUE TITLE
Keepassxc is Not responding in Manjaro

### ISSUE THREAD

**Issue by ndpandit** [keepassxreboot/keepassxc#4536]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Expected Behavior
Load file window shows kdbx files as usual

## Current Behavior
Keepassxc is not responding window is shown with Force Quit and Wait options, none of which do anything, keeps recurring.

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )

## Steps to Reproduce
1. Mount webdav remote with fstab, davfs2
2. Navigate to the mounted location to load kdbx file

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION : 2.5.3-1
Revision: REVISION

Libraries:
- LIBS

Operating system: Manjaro
CPU architecture: ARCH
Kernel: 5.4.28-1

Enabled extensions:
- EXTENSIONS

Screenshot:
![Screenshot from 2020-04-02 13-10-23](https://user-images.githubusercontent.com/21022809/78224989-0f3aca80-74e7-11ea-816f-0cf973d76a24.png)

Annoying part is that the process can't even be killed. tried pkill, kill, kill -9, killall, and all these 4 with root. but the zombie process remains. Rebooting seems to be the only option.

This does not happen with keepass2 with mono, but I prefer native keepassxc.

Thanks & Regards.

**Comment by ndpandit** [comment]
Hi,
The process got terminated after some time, didn't notice it.
My net speed is slow, around 5 Megabits, but I think that should not be the reason.

Best Regards.

**Comment by droidmonkey** [comment]
Are you using the snap or appimage?

**Comment by ndpandit** [comment]
Neither. Keepassxc is installed from standard community repository.

**Comment by droidmonkey** [comment]
Please try our AppImage

**Comment by ndpandit** [comment]
Hi,
It works perfectly in AppImage.

Thanks & Best Regards.

**Comment by BO41** [comment]
@droidmonkey Does this mean the Arch build is wrong, or what is different on the AppImage?
