### ISSUE TITLE
cli part needs X11/GUI libraries 

### ISSUE THREAD

**Issue by tuxmaster5000** [keepassxreboot/keepassxc#4537]
## Summary
In the current version (2.5.3) the cli part is using X11 Libs.
ldd /tmp/keepassxc-cli 
	linux-vdso.so.1 =>  (0x00007ffcfad33000)
	libasan.so.5 => not found
	libsodium.so.23 => /lib64/libsodium.so.23 (0x00007f9928354000)
	libargon2.so.0 => /lib64/libargon2.so.0 (0x00007f992814c000)
	libz.so.1 => /lib64/libz.so.1 (0x00007f9927f36000)
	libreadline.so.6 => /lib64/libreadline.so.6 (0x00007f9927cf0000)
	libQt5Svg.so.5 => /lib64/libQt5Svg.so.5 (0x00007f9929594000)
	libqrencode.so.3 => /lib64/libqrencode.so.3 (0x00007f9927ae3000)
	libQt5Concurrent.so.5 => /lib64/libQt5Concurrent.so.5 (0x00007f992958b000)
	libykpers-1.so.1 => /lib64/libykpers-1.so.1 (0x00007f99278d2000)
	libQt5Network.so.5 => /lib64/libQt5Network.so.5 (0x00007f9927749000)
	libQt5Widgets.so.5 => /lib64/libQt5Widgets.so.5 (0x00007f99270de000)
	libQt5Gui.so.5 => /lib64/libQt5Gui.so.5 (0x00007f9926c26000)
	libquazip5.so.1 => not found
	libQt5DBus.so.5 => /lib64/libQt5DBus.so.5 (0x00007f9929504000)
	libQt5Core.so.5 => /lib64/libQt5Core.so.5 (0x00007f9926779000)
	libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007f9926472000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f9926170000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f9925da2000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f9925b86000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f99293f6000)
	libtinfo.so.5 => /lib64/libtinfo.so.5 (0x00007f992595c000)
	libGL.so.1 => /lib64/libGL.so.1 (0x00007f99256d0000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f99254ba000)
	libyubikey.so.0 => /lib64/libyubikey.so.0 (0x00007f99252b7000)
	libusb-1.0.so.0 => /lib64/libusb-1.0.so.0 (0x00007f992509e000)
	libssl.so.10 => /lib64/libssl.so.10 (0x00007f9924e2c000)
	libcrypto.so.10 => /lib64/libcrypto.so.10 (0x00007f99249c9000)
	libpng15.so.15 => /lib64/libpng15.so.15 (0x00007f992479e000)
	libharfbuzz.so.0 => /lib64/libharfbuzz.so.0 (0x00007f9924501000)
	libdbus-1.so.3 => /lib64/libdbus-1.so.3 (0x00007f99242b1000)
	libsystemd.so.0 => /lib64/libsystemd.so.0 (0x00007f9924080000)
	libicui18n.so.50 => /lib64/libicui18n.so.50 (0x00007f9923c81000)
	libicuuc.so.50 => /lib64/libicuuc.so.50 (0x00007f9923908000)
	libicudata.so.50 => /lib64/libicudata.so.50 (0x00007f9922335000)
	libpcre2-16.so.0 => /lib64/libpcre2-16.so.0 (0x00007f99220c9000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f9921ec5000)
	libgthread-2.0.so.0 => /lib64/libgthread-2.0.so.0 (0x00007f9921cc3000)
	libglib-2.0.so.0 => /lib64/libglib-2.0.so.0 (0x00007f99219ad000)
	libGLX.so.0 => /lib64/libGLX.so.0 (0x00007f992177b000)
	libX11.so.6 => /lib64/libX11.so.6 (0x00007f992143d000)
	libXext.so.6 => /lib64/libXext.so.6 (0x00007f992122b000)
	libGLdispatch.so.0 => /lib64/libGLdispatch.so.0 (0x00007f9920f75000)
	libudev.so.1 => /lib64/libudev.so.1 (0x00007f9920d5f000)
	libgssapi_krb5.so.2 => /lib64/libgssapi_krb5.so.2 (0x00007f9920b12000)
	libkrb5.so.3 => /lib64/libkrb5.so.3 (0x00007f9920829000)
	libcom_err.so.2 => /lib64/libcom_err.so.2 (0x00007f9920625000)
	libk5crypto.so.3 => /lib64/libk5crypto.so.3 (0x00007f99203f2000)
	libfreetype.so.6 => /lib64/libfreetype.so.6 (0x00007f9920133000)
	libgraphite2.so.3 => /lib64/libgraphite2.so.3 (0x00007f991ff05000)
	libcap.so.2 => /lib64/libcap.so.2 (0x00007f991fd00000)
	librt.so.1 => /lib64/librt.so.1 (0x00007f991faf8000)
	libselinux.so.1 => /lib64/libselinux.so.1 (0x00007f991f8d1000)
	liblzma.so.5 => /lib64/liblzma.so.5 (0x00007f991f6ab000)
	liblz4.so.1 => /lib64/liblz4.so.1 (0x00007f991f496000)
	libgcrypt.so.11 => /lib64/libgcrypt.so.11 (0x00007f991f215000)
	libgpg-error.so.0 => /lib64/libgpg-error.so.0 (0x00007f991f010000)
	libresolv.so.2 => /lib64/libresolv.so.2 (0x00007f991edf7000)
	libdw.so.1 => /lib64/libdw.so.1 (0x00007f991eba6000)
	libpcre.so.1 => /lib64/libpcre.so.1 (0x00007f991e944000)
	libxcb.so.1 => /lib64/libxcb.so.1 (0x00007f991e71c000)
	libkrb5support.so.0 => /lib64/libkrb5support.so.0 (0x00007f991e50c000)
	libkeyutils.so.1 => /lib64/libkeyutils.so.1 (0x00007f991e308000)
	libbz2.so.1 => /lib64/libbz2.so.1 (0x00007f991e0f8000)
	libattr.so.1 => /lib64/libattr.so.1 (0x00007f991def3000)
	libelf.so.1 => /lib64/libelf.so.1 (0x00007f991dcdb000)
	libXau.so.6 => /lib64/libXau.so.6 (0x00007f991dad7000)

## Desired Behavior
Don't use GUI libs

**Comment by droidmonkey** [comment]
We know, already tracked thank you
