### ISSUE TITLE
auto-type is missing some certain characters

### ISSUE THREAD

**Issue by oguzhantopcu** [keepassxreboot/keepassxc#4538]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

Once I press control+shift+v I expect all characters should be typed to the current textbox by auto-type feature .

## Current Behavior
[NOTE]: # ( Tell us what actually happens )

Some certain characters are always missing.

As en example Every time I auto-type the username 'ozkara-dev' it writes 'ozkaradev'.

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1. Create an entry with username 'ozkara-dev'
2. Auto-type it to somewhere, for example: firefox-nightly, kwrite
3. You see, dash is missing.

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )

No idea.

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.5.3
Revision: f8c962b
Qt 5.13.2
Debugging mode is disabled.

Operating system: Fedora 31 (Thirty One)
CPU architecture: x86_64
Kernel: linux 5.5.11-200.fc31.x86_64

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.5

**Comment by droidmonkey** [comment]
Are you using an alternative keyboard layout? If so this is a known issue.

**Comment by oguzhantopcu** [comment]
I use Turkish Q keyboard layout.  Is that "alternative keyboard layout"?

**Comment by droidmonkey** [comment]
Yes it is. See #2475, #3605, #2246, and #324
