### ISSUE TITLE
Snapshot - compile date, build version in About.

### ISSUE THREAD

**Issue by wombat01** [keepassxreboot/keepassxc#4539]
[TIP]:  # ( Provide a general summary of the feature in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Summary
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
Please view build version or compile date in "About" window. (Snapshot)

![image](https://user-images.githubusercontent.com/20426629/78240535-70f73680-74df-11ea-87af-036d85a324aa.png)

## Desired Behavior
[NOTE]: # ( Tell us how the new feature should work, be specific )

## Possible Solution
[NOTE]: # ( Not required, but suggest ideas on how to implement the addition or change )

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )

**Comment by droidmonkey** [comment]
That's a great idea!
