### ISSUE TITLE
one-character password text field

### ISSUE THREAD

**Issue by piramiday** [keepassxreboot/keepassxc#4541]
I have encountered this issue many times, yet I don't understand how to reproduce it.
I searched for similarly-named issues without finding any.

sometimes I cannot type anything more than a **_single character_** in the text field. e.g.:

![Screenshot at 2020-03-31 16-55-04](https://user-images.githubusercontent.com/48775554/78314844-14f8d600-7510-11ea-8aa3-104ad7cd6f8c.png)

has anyone else experienced this?

## Expected Behavior
every time KeePassXC is opened, and the database is locked, the password text box should be accepting input in order to unlock the database.

## Current Behavior
sometimes when KeePassXC is opened, and the database is locked, the password text box accepts only a single character and therefore prevents me from typing the full password to unlock the database.

## Possible Solution
whenever that happens, I close the program and re-execute it: upon doing this, the password text box goes back to normal.

## Steps to Reproduce
not clear at the moment, sorry.

## Context
although it's not deal-breaking, this issue does bring down the usability of KeepassXC a bit.

## Debug Info
KeePassXC - Version 2.5.3
Revision: f8c962b

Qt 5.9.5
Debugging mode is disabled.

Operating system: Linux Mint 19.3
CPU architecture: x86_64
Kernel: linux 5.3.0-45-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.1

**Comment by droidmonkey** [comment]
Never seen this every

**Comment by piramiday** [comment]
just tried. yes! the same happens with visible characters, too. well, _character_, singular:

![Screenshot at 2020-04-03 08-37-42](https://user-images.githubusercontent.com/48775554/78378837-6643ac80-7586-11ea-849a-d6f1a79b9a2d.png)

**Comment by piramiday** [comment]
FYI, I have just observed this again with 2.6.0 ...

**Comment by droidmonkey** [comment]
Its on your end

**Comment by piramiday** [comment]
I haven't done anything that could cause this, either.
I reported this because maybe other users experienced it, too, enough to deserve some scrutiny.
if they haven't, and it doesn't, then I'll close this issue and live with it.

**Comment by droidmonkey** [comment]
Haven't seen tha from anyone else. It certainly is an anomaly.
