### ISSUE TITLE
broken copying from notes

### ISSUE THREAD

**Issue by 648643579** [keepassxreboot/keepassxc#4544]
Sorry but I don't know how I would really describe this bug.

I use KeePassXC v2.5.3 portable version for Windows 10 and Linux Ubuntu/Mint (this problem occurs in both systems).
I'll search for some text like "ebay" I mark my email and do Ctrl+C, (that doesn't work in 30% of cases)
https://i.imgur.com/OMVrMpE.png

the only option is to right-click and select the copy option from the context menu > then of course the function is Ctrl+V.

Does anyone have a similar problem ?

INFO:
KeePassXC - Verze 2.5.3

Revize: f8c962b

Qt 5.13.2
Ladící režim je vypnutý.

Operační systém: Windows 10 (10.0)
Architektura procesoru: x86_64
Jádro systému: winnt 10.0.17763

Zapnutá rozšíření:
- Automatické vyplňování
- Napojení na webový prohlížeč
- SSH agent
- KeeShare (podepsané a nepodepsané sdílení)
- YubiKey

Kryptografické knihovny:
 libgcrypt 1.8.5

**Comment by droidmonkey** [comment]
This is fixed in develop branch!
