### ISSUE TITLE
Interface Scaling

### ISSUE THREAD

**Issue by Mr-Sheep** [keepassxreboot/keepassxc#4552]
I have a 4k display and a 1080p external monitor. When using only the external monitor, KeePassXC works just fine with readable text size. But when I unplugged the DP cable and using only the builtin 4k display on the laptop, some text became tiny and hard to read.
System: Windows 10 Home
CPU: Intel core i7 9750h
## Expected Behavior
same interface scaling for all test
![expected](https://keepassxc.org/images/screenshots/windows/screen_001.png)

## Current Behavior
![current](https://i.imgur.com/rxB3ZNm.png)

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1. Using external screen
2. Unplug it

**Comment by droidmonkey** [comment]
This is a Qt issue, you will have to restart the application

**Comment by Mr-Sheep** [comment]
Same happens after restart the app

**Comment by droidmonkey** [comment]
Then you need to define some Qt environment variables to help out. See https://doc.qt.io/qt-5/highdpi.html#high-dpi-support-in-qt

**Comment by droidmonkey** [comment]
If you are not using the built-in windows 10 display scaling, then that is also contributing to your issue. In all technicality, the font size and widgets are scaled properly. 4K literally means 4x 1080p resolution, so in an unscaled application things should look 1/4 their normal size without any scaling.

![image](https://user-images.githubusercontent.com/2809491/78557691-3b07ca00-77df-11ea-8f47-9767a9604ea2.png)
