### ISSUE TITLE
Add run on login in Windows

### ISSUE THREAD

**Issue by morozdan2003** [keepassxreboot/keepassxc#4554]
## Summary
Make the option which enables launching the program on system boot

## Desired Behavior
I want to have option like "Launch KeePassXC on boot", which makes program to launch every time I login in the system.

## Possible Solution
I'm not in programming very much, sorry (^_^). Maybe it would be solution to make certain autorun key in the Windows Registry

## Context
I'm too lazy to launch KeePassXC every time I need to login on sites. Autorun would make this process easier.

**Comment by droidmonkey** [comment]
Duplicate issue
