### ISSUE TITLE
Database Sync

### ISSUE THREAD

**Issue by KitchM** [keepassxreboot/keepassxc#4555]
Is there a way to synchronize two or more keepassxc databases?

**Comment by droidmonkey** [comment]
At this time you need to merge database A into database B then merge database B into database A. Two operations. There is an issue to fix this already: #90

**Comment by KitchM** [comment]
How is a merge done?

**Comment by droidmonkey** [comment]
The merge strategy is to compare all elements by UUID, last changed wins, old version of entry is stored in its history.

**Comment by KitchM** [comment]
What are the exact methods for doing that?  What application is used?  Details please.

**Comment by droidmonkey** [comment]
It is done within KeePassXC. If you want  more details you will have to read the code: https://github.com/keepassxreboot/keepassxc/blob/develop/src/core/Merger.cpp

**Comment by KitchM** [comment]
So you mean Database>Merge from KeePassXC database.  Am I assuming correctly that one is open and the other is selected from the above menu item?  Is it also correct that one would then close the program and open it with the other database and do the same thing with the first one?

I would assume that the first step would work by itself if it were then copied over the second one.  Correct?

**Comment by droidmonkey** [comment]
Sorry misunderstood your last question. Here is the sequence:

1. Open KeePassXC and unlock Database A
2. Go to Database > Merge from database...
3. Choose Database B
4. Save resulting Database A
5. Open Database B and unlock it
6. Go to Database > Merge from database...
7. Choose Database A
8. Save resulting Database B
9. Now A and B are synced with each other

**Comment by KitchM** [comment]
That's exactly what I was looking for.  That also explains that a merge cannot occur without the passwords of both databases.  (Can't recover lost password database that way.)

I will be able to merge two now and that helps a lot.  Thanks.

**Comment by droidmonkey** [comment]
Yah there is absolutely no way to crack a database with a good master password.

**Comment by KitchM** [comment]
I believe you meant "with **or without** a good master password".

Also, is there any indication of anything happening between steps 3 and 4 above?  Nothing happened for me.

**Comment by droidmonkey** [comment]
No we don't have a merge results prompt yet, it's on the list.

I did mean what i said. If you have a crappy password it can be cracked, just not that easily.

**Comment by KitchM** [comment]
So then, what is the way  to crack it if it has a bad password?

**Comment by droidmonkey** [comment]
Dictionary attacks

**Comment by AzureRaptor** [comment]
@droidmonkey Forgive me for raising an old issue, but this seemed strongly related as opposed to opening something new.

If one uses the keepassxc-cli program to merge, do both databases need to be closed in all instances of the KeepassXC gui (or any other program that reads them, I assume)?

Also, as a sidenote, I am confused about what the --no-password-from argument does.  I know you can't open a database w/o the passphrase and/or key.  Does this option _strip_ the password out of the "from" database, and leave it blank, or something else I'm not getting?

Thank you kindly in advance.

**Comment by droidmonkey** [comment]
We don't keep file locks so you can leave them open in the GUI, they should auto reload. The no password flag means the database has no password and to not request it to be entered.
