### ISSUE TITLE
Strange mouse behaviour.

### ISSUE THREAD

**Issue by altayevrim** [keepassxreboot/keepassxc#4556]
## Expected Behavior
Normal GUI experience.

## Current Behavior
It's like first mouse button is pressed all the time, so when selecting any category, you can unintentionally move them around. 

## Steps to Reproduce
You can watch this small video: https://www.youtube.com/watch?v=Sm86yAvz1Lg
(I am not holding my left mouse button pressed, it acts like it is constantly pressed, this behaviour does not happen in any other software that I use.)

## Context
It's really hard to use the GUI. I can't select Categories without moving them unintentionally, this effects every side of the program (Settings, etc.) 

## Debug Info
KeePassXC - Version 2.5.3
Revision: f8c962b

Qt 5.9.5
Debugging mode is disabled.

Operating system: Ubuntu 18.04.4 LTS
CPU architecture: x86_64
Kernel: linux 4.15.0-91-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.1

**Comment by droidmonkey** [comment]
There is no way that is something we are doing.

**Comment by altayevrim** [comment]
I believe that but isn't it too strange that only KeepassXC has that? I tried reinstalling and everything but still it is same. And only KeepassXC. If you don't have any idea then we can close this.

**Comment by droidmonkey** [comment]
Try our snap or appimage instead

**Comment by altayevrim** [comment]
I reinstalled using your snaps. Still same :/

**Comment by altayevrim** [comment]
I finally managed to found the issue; I am using Lenovo YOGA 510, that has touchscreen. I don't know why that is causing an issue only in KeepassXC but after disabling the touchscreen this behaviour disappeared. In order to do that you can refer to [this](https://www.tomordonez.com/disable-touchscreen-ubuntu.html) site. It may help someone in the future. Sorry for bothering you @droidmonkey.

**Comment by droidmonkey** [comment]
You can probably exclude our app from touchscreen input in your system settings.
