### ISSUE TITLE
TestCsvParser::testUnicode fails on openSUSE

### ISSUE THREAD

**Issue by cyphar** [keepassxreboot/keepassxc#456]
I've been trying to build the master `develop` branch using the official openSUSE package's `.spec` file. The `isUnicode` test fails when building inside both `osc build` (locally) and on OBS. Is there a particular version requirement of `libQt5-*` to make the CSV parser handle Unicode properly?

## Expected Behavior
All of the tests should succeed, as they do with `2.1.3`.

## Current Behavior
```
[   68s] ********* Start testing of TestCsvParser *********
[   68s] Config: Using QtTest library 5.7.1, Qt 5.7.1 (x86_64-little_endian-lp64 shared (dynamic) release build; by GCC 6.2.1 20161209 [gcc-6-branch revision 243481])
[   68s] PASS   : TestCsvParser::initTestCase()
[   68s] FAIL!  : TestCsvParser::testUnicode() 't.at(0).at(0) == "€1"' returned FALSE. ()
[   68s]    Loc: [/home/abuild/rpmbuild/BUILD/keepassxc-develop/tests/TestCsvParser.cpp(332)]
[   68s] PASS   : TestCsvParser::testLF()
[   68s] PASS   : TestCsvParser::testEmptyReparsing()
[   68s] PASS   : TestCsvParser::testSimple()
[   68s] PASS   : TestCsvParser::testEmptyQuoted()
[   68s] PASS   : TestCsvParser::testEmptyNewline()
[   68s] PASS   : TestCsvParser::testSeparator()
[   68s] PASS   : TestCsvParser::testCR()
[   68s] PASS   : TestCsvParser::testCRLF()
[   68s] XFAIL  : TestCsvParser::testMalformed() Bad format
[   68s]    Loc: [/home/abuild/rpmbuild/BUILD/keepassxc-develop/tests/TestCsvParser.cpp(66)]
[   68s] WARNING: TestCsvParser::testMalformed() malformed string: (row,col) 2,2
[   68s]
[   68s]    Loc: [/home/abuild/rpmbuild/BUILD/keepassxc-develop/tests/TestCsvParser.cpp(68)]
[   68s] PASS   : TestCsvParser::testMalformed()
[   68s] PASS   : TestCsvParser::testQualifier()
[   68s] PASS   : TestCsvParser::testNewline()
[   68s] PASS   : TestCsvParser::testEmptySimple()
[   68s] XFAIL  : TestCsvParser::testMissingQuote() Bad format
[   68s]    Loc: [/home/abuild/rpmbuild/BUILD/keepassxc-develop/tests/TestCsvParser.cpp(56)]
[   68s] WARNING: TestCsvParser::testMissingQuote() missing closing quote: (row,col) 2,1
[   68s]
[   68s]    Loc: [/home/abuild/rpmbuild/BUILD/keepassxc-develop/tests/TestCsvParser.cpp(58)]
[   68s] PASS   : TestCsvParser::testMissingQuote()
[   68s] PASS   : TestCsvParser::testComments()
[   68s] PASS   : TestCsvParser::testBackslashSyntax()
[   68s] XFAIL  : TestCsvParser::testReparsing() Wrong qualifier
[   68s]    Loc: [/home/abuild/rpmbuild/BUILD/keepassxc-develop/tests/TestCsvParser.cpp(290)]
[   68s] PASS   : TestCsvParser::testReparsing()
[   68s] PASS   : TestCsvParser::testEmptyFile()
[   68s] PASS   : TestCsvParser::testQuoted()
[   68s] PASS   : TestCsvParser::testMultiline()
[   68s] PASS   : TestCsvParser::testColumns()
[   68s] PASS   : TestCsvParser::cleanupTestCase()
[   68s] Totals: 22 passed, 1 failed, 0 skipped, 0 blacklisted, 4ms
[   68s] ********* Finished testing of TestCsvParser *********
```

The full build log is available from OBS: https://build.opensuse.org/build/home:cyphar:branches:security/openSUSE_Tumbleweed/x86_64/keepassxc/_log

## Steps to Reproduce (for bugs)
1. Try to build the package from here: https://build.opensuse.org/package/show/home:cyphar:branches:security/keepassxc

## Context
I'm trying to build `develop` so  that I can use the CSV importer to import my LastPass passwords.

## Your Environment
This is also available from the build log in OBS.

* KeePassXC version/commit used: b7546b45b3c48e2ffa150be72fc6ce03db1adf00
* Qt version (e.g. Qt 5.3): `libQt5Core5-5.7.1-1.1`
* Compiler (e.g. Clang++3.6.0): `GCC 6.3.1`
* Operating System and version: openSUSE Tumbleweed

**Comment by cyphar** [comment]
FWIW, I just built `keepassxc` without the tests and the CSV importer seemed to work fine. But this'll be an issue in the future if the next release starts failing tests on openSUSE.

**Comment by seatedscribe** [comment]
Can you give some context on the locale configuration? Environment
variables like LANG and all the LC_* family as a first step.

**Comment by droidmonkey** [comment]
This test fails if your lang is not set to UTF-8
