### ISSUE TITLE
After updated my system to macOS Catalina 10.15.4 cannot use Touch ID for quick unlock

### ISSUE THREAD

**Issue by lethefrost** [keepassxreboot/keepassxc#4562]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
(The check box "TouchID for Quick Unlock" is checked.) After first time I enter the password to the database, when I leave the password field blank and press "OK" button, or just hit Enter, I should be able to use touch ID to unlock this database, as what I usually do until this system update.

## Current Behavior
[NOTE]: # ( Tell us what actually happens )
![image](https://user-images.githubusercontent.com/47198693/78746005-bed2cb00-7933-11ea-8227-56bc7dbdbbc3.png)
![image](https://user-images.githubusercontent.com/47198693/78746015-c6926f80-7933-11ea-97d2-6e03c539b452.png)

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )
Actually after I update macOS, I cannot even open the application. Every time I tired to run KeePassXC it crashes at the beginning (I cannot even see the first graphic interface). I tried many times and restart my laptop but it was not solved. Finally, I download the latest release version of KeePassXC (however, my local version which was unable to run at my machine was already the latest at that time) and overwrote/ re-installed the app and now it works. I don't really know why.

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
I don't know how the behavior is caused. Now on my machine it can be reproduce every time I run it but I don't know how to reproduce it on other machines. I suppose it is because the system update because I everything was normal just before this update and I hardly did anything else other than updating my system to 10.15.4.

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.5.3
Revision: f8c962b

Qt 5.14.1
Debugging mode is disabled.

Operating system: macOS 10.15
CPU architecture: x86_64
Kernel: darwin 19.4.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
 libgcrypt 1.8.5

**Comment by lethefrost** [comment]
Oops I've seen others asking same question. Will there be a solution recently? Thanks anyway!

**Comment by BendingBender** [comment]
Seems to be related/duplicate to #3207.

**Comment by BendingBender** [comment]
Seems to be related/duplicate to #4515.
