### ISSUE TITLE
Grey menu

### ISSUE THREAD

**Issue by siriusacma** [keepassxreboot/keepassxc#4565]
Keypassxc starts fine and after a couple of minutes makes the contents of the program gray and non-clickable. Database locking does not work, the exit button in the tray does not work. I unload program through the task manager. After rebooting, the program first works fine, then again makes the menu gray.
![VmTqDKkUEZ](https://user-images.githubusercontent.com/25794418/78906526-2437d080-7a88-11ea-895b-574400f3ce81.jpg)

Windows 10
Intel Core 2 Duo x64
Keepass XC 2.5.3

**Comment by droidmonkey** [comment]
Known issue that has been fixed in the next major release.
