### ISSUE TITLE
Password Generator improvement suggestions & multi-step login support

### ISSUE THREAD

**Issue by Banndditt** [keepassxreboot/keepassxc#4570]
Hello,
I am new to KeepassXC, and password managers in general, always having just generated long strong passwords on my own.
After deciding to use a manager, I determined that KeepassXC is the best.  :-)
Either I don't know how to do the following, or I'd like to make some feature suggestions:

1.  I'll add my vote for integration with ThunderBird. Maybe a separate extension for ThunderBird is what is needed?

2.  I'd like to see some additional features for password generation.
Specifically 'presets' for generating passwords for sites & services.

When a user goes to sign up for a service/site, it is common that service/site wants an email/username as a login, and then also a password.
It is always best to use the max possible password length and complexity.

_But for any site & service, what is the max length of the password? What characters are allowed? What characters are prohibited?_

I have run into this many times where I have entered a password, then the validation refuses to accept it as it is too long and/or certain characters are not allowed. (Or worse, their storage system truncates the password without notification.)

So if there was a preset, such as "generate max complexity password for:"  'gmail' selected, that would allow KeepassXC to generate a max complexity password compliant for the service/site selected, and without the user having to pre-research what length and characters/symbols can be used.
Afterall, what is the advice always given? Use a max complexity/length password and use a password manager to use them. Since KeepassXC is going to be storing password, having long secure ones shouldn't be a problem. :-)

Some example sites that would be particularly useful:
- gmail and other email
- forums
- ebay, Paypal, Kijiji, amazon, craigslist, bestbuy, staples
- banks, Square,
- kickstarter
- post office and gov't services, CRA, libraries, utilities
- router logins, DD-WRT
- imgur, facebook, twitter, instagram,
- dropbox, SpiderOak, WeTransfer, SugarSync, and other storage
- Firefox, Chrome, Mozilla
- services like OpenDNS, NextDNS, Cloudfare,
- apps like Whatsapp, netflix, Hulu,

And this compliance generation would also apply for generating passwords for WiFi WPA2/WPA3 PSK
Eg:  WPA2 is 63 characters, but several times I used the WPA2 key generator at  http://www.yellowpipe.com/yis/tools/WPA_key/index.php  but repeatedly found that the PSK it generated were somehow not apple device compliant. I would enter them on iOS devices in particular, but sometimes the iOS device would either not accept a character to be used or not work once entered. In ALL cases once I tinkered with the PSK and removed/replaced some symbols then apple devices would work. (of course then I had to go around and change everything, what a time waster for apples non compliance with standards).

Also, the password generator to be able to generate easier usable passwords for non US English keyboards. Eg a UK or Canadian English/French keyboard has a slightly different layout and some characters can not be entered on a US keyboard and vice versa. This would be more problematic for, say, even other Latin based keyboards/languages; and further yet for something like Cyrillic.

3. Multi-level login support. On many sites, a user is faced with a login that has a enter 'username/email' box and a enter 'password' box right on the same login area. Easy.
But how does KeepassXC support multistage logins?
There are several sites I use where there are several login steps. Such as:

First a user enters the username/clientID number then clicks next or hits enter. Step 2 is to enter the first password then click next or hit enter. Steps 3 is to enter the second password then click next or hit enter. Sometimes the web page refreshes for each step, sometimes just the login box.

Some sites the passwords are not the same each time - it asks a different question out of a bank of 'x' that the user has answered or entered a password for. Eg step 2 is one of six questions of such type of "Your favorite color is: __" or "Name of your former neighbors cat? __"; or there are 2 such steps and then a fixed password.

So support for multi step logins would be nice.

4. In the FAQ is discussion on supporting Keepass plugins.
Looking at the Keepass plugins listed here: 

https://keepass.info/plugins.html 

It actually seems like most of that functionality is already implemented in KeePassXC, but the following would be nice:

CheckPasswordBox
ColoredPassword
OnScreen Keyboard
- ability to print out the database? (but since it can be exported to html or CSV, maybe this is not needed).

5. Does KeePassXC also work with  PaleMoon?  WaterFox?

Thank you

**Comment by Banndditt** [comment]
re: password generator suggestions...
I should add that I actually have run into people who have used shorter passphrases then they otherwise could remember and would use on sites, like for email, but have restricted themselves as they have previously ran afoul of some validation, so they have become afraid of 'breaking' the internet. (OK, so they're not greatly computer literate, but at least if a site can use long passphrases, it would be nice to know about it).

So, if gmail would accept a 200 character password, sure, let's use it.

**Comment by phoerious** [comment]
Thanks for your suggestions.

> I'll add my vote for integration with ThunderBird. Maybe a separate extension for ThunderBird is what is needed?

There is some community effort going on to bring KeePassXC-Browser to Thunderbird, but I wouldn't expect any results soon.

> I'd like to see some additional features for password generation.
Specifically 'presets' for generating passwords for sites & services.

We have discussed this a few times . Our current status is that we do not want to add all this complexity for supporting password antipatterns if there isn't dire need for it. Such a list is hard to maintain, never complete, quickly outdated, and how often do you change you GMail password anyway?

> CheckPasswordBox
ColoredPassword
OnScreen Keyboard

There is an open feature request for coloured passwords (#4099). Checking the password box is quite hard to do cross-platform and we do not only auto-type passwords anyway. We also complete usernames and whatever else you want. On-screen keyboards are clearly the operating system's job.

> ability to print out the database? (but since it can be exported to html or CSV, maybe this is not needed).

You gave yourself the correct answer.

> Does KeePassXC also work with PaleMoon? WaterFox?

No, and we never will be unless they decide to port their technology stack to 2020.

**Comment by droidmonkey** [comment]
Hello, welcome to KeePassXC. I read through your entire post and as Phoerious mentioned most of your requests are captured in existing issues already. The remainder would be impractical or not worth the effort. Closing this as a duplicate.

**Comment by Banndditt** [comment]
Hello, thanks for your replies.

Between when I posted this and now, I was goggling some answers, and found this info for those interested in password length/complexity:

https://github.com/dumb-password-rules/dumb-password-rules
https://www.theglobeandmail.com/technology/digital-culture/why-canadas-banks-have-weaker-passwords-than-twitter-or-google/article18325257/
http://web.archive.org/web/20130907182806/https://defuse.ca/password-policy-hall-of-shame.htm
https://spideroak.support/hc/en-us/articles/115004715803-Password-Length-and-Allowable-Characters
https://www.amazon.ca/gp/help/customer/display.html?nodeId=201909100
http://www.passwordpit.com/password-requirements/
https://squareup.com/help/ca/en/article/6212-square-s-password-policy

**Comment by Banndditt** [comment]
Hello, but what about question 3

Multi-level login support. On many sites, a user is faced with a login that has a enter 'username/email' box and a enter 'password' box right on the same login area. Easy.
But how does KeepassXC support multistage logins?
There are several sites I use where there are several login steps. Such as:
First a user enters the username/clientID number then clicks next or hits enter. Step 2 is to enter the first password then click next or hit enter. Steps 3 is to enter the second password then click next or hit enter. Sometimes the web page refreshes for each step, sometimes just the login box.

Some sites the passwords are not the same each time - it asks a different question out of a bank of 'x' that the user has answered or entered a password for. Eg step 2 is one of six questions of such type of "Your favorite color is: __" or "Name of your former neighbors cat? __"; or there are 2 such steps and then a fixed password.

So support for multi step logins would be nice.

**Comment by droidmonkey** [comment]
This is already a feature in our browser plugin.

**Comment by Banndditt** [comment]
Great, would you please point me to instructions on how to do this, as i don't understand how to.
Thanks

**Comment by Banndditt** [comment]
Is it possible, and if so how, to specify the type of webpage opened?
Yes, I understand a user can double lick or right lick from within KeepassXC and open a webpage with login info.
But if we want that webpage to be a Private/Incognito page or a GUEST page, how can we specify that?
Thanks

**Comment by droidmonkey** [comment]
Use the cmd:// syntax and include the switch for incognito mode. An example: `cmd://firefox -incognito https://google.com`
