### ISSUE TITLE
KeePassXC 2.5.4 on Ubuntu 18.04.4 It does not display GUI

### ISSUE THREAD

**Issue by Adriano-Baldi** [keepassxreboot/keepassxc#4571]
After upgrading from version 2.5.3 KeePassXC 2.5.4 starts but does not display GUI.

# ps awx|grep keepassxc
8506 pts/0    S+     0:00 grep --color=auto keepassxc
8586 tty2     RLl+   0:07 keepassxc

# keepassxc --debug-info
KeePassXC - Version 2.5.4
Revision: dcca5aa

Qt 5.9.5
Debugging mode is disabled.

Operating system: Ubuntu 18.04.4 LTS
CPU architecture: x86_64
Kernel: linux 4.15.0-96-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
libgcrypt 1.8.1

**Comment by phoerious** [comment]
Are you sure it's not just hidden in the systray?

**Comment by Adriano-Baldi** [comment]
No, I can't see it on the systray. :-(

**Comment by phoerious** [comment]
Please delete your config file (make a copy before that) and try again.

**Comment by Adriano-Baldi** [comment]
No, no GUI, and the keepassxc.ini file is not regenerated.
How can I try to install the previous version?
Thanks for the support in real time :-)))

**Comment by Adriano-Baldi** [comment]
At the second run the keepassxc.ini file is't regenerated

[General]
HideWindowOnCopy=false
MinimizeOnCopy=true

but still no GUI

**Comment by phoerious** [comment]
This is puzzling. We did not change anything that would affect Linux users. Please try if the AppImage works for you.

**Comment by Adriano-Baldi** [comment]
Same problem with the AppImage.
I would like to reinstall the previous version to rule out that this is a problem with my system.

**Comment by droidmonkey** [comment]
Just download it from our releases page

**Comment by Adriano-Baldi** [comment]
Sorry phoerious, I made a mistake! The AppImage work perfectly! 
Before I had mistakenly tried with the Snap pakage (instead the AppImage) and this does not work like the installation via PPA. So only Appimage works for me.
