### ISSUE TITLE
Feature request: ChromeOS support

### ISSUE THREAD

**Issue by F3000** [keepassxreboot/keepassxc#4572]
Hi , 

do you have this on the roadmap already ?

**Comment by droidmonkey** [comment]
Just use our AppImage download, it will work out of the box.

**Comment by F3000** [comment]
Great thanks 😊

**Comment by F3000** [comment]
@droidmonkey 

any recommendations how to sync database via Nextcloud on chromeOS ?

**Comment by droidmonkey** [comment]
No you will have to find a tutorial on that, nothing special required on our end.

**Comment by F3000** [comment]
Good idea . Until now I have only the Account for Drive 😁

**Comment by F3000** [comment]
@Droidmonkey I have tried to install the app image . Is not possible . 

But Ubuntu package is working . This is only in 2.3.4

**Comment by droidmonkey** [comment]
Then you can use our PPA to get the latest version.

**Comment by F3000** [comment]
Sorry . I have seen chromeOS using Debian 10 (buster) . Do you have also a .deb file in a beer version ?
