### ISSUE TITLE
KeePassXC 2.5.4 on macOS 10.15.4 right mouse click not working and permission for screen capture cannot be set

### ISSUE THREAD

**Issue by alexanderkress** [keepassxreboot/keepassxc#4573]
In KeePassXC 2.5.4 the right mouse click on macOS 10.15.4 is only showing the element "new entry" which should only be shown on a blank area. However, any existing entry is now not editable via right mouse click.

Autofill is also not working, since the system permission "screen capture" cannot be set. This permission cannot be added, since KeePass does not show up in the section. The under the "accessibility" option, KeePassXC is shown.

Rolled back to v2.5.3-2, where right mouse, screen capture and accessibility option are working fine.

**Comment by phoerious** [comment]
I cannot reproduce the new entry bug.
Auto-Type worked for me after deleting every instance of KeePassXC first and then reinstalling it.

**Comment by dbluxo** [comment]
Same problem here, updated from v2.5.3-2 to v.2.5.4 via homebrew-cask. Then rolled back to v2.5.3-2.

**Comment by phoerious** [comment]
I tested it on another Mac and could reproduce that KeePassXC didn't show up under Screen Recording. I could fix it be deleting all traces of previous KeePassXC installations and downloads, reinstalling KeePassXC 2.5.4 and rebooting the system. After the reboot, I could grant screen recording permissions after pressing the global Auto-Type key once.

**Comment by h0lgerg** [comment]
Same problem with Screen Recording permissions. Even after removing any traces of KeePassXC I could found, restarting and reinstalling v2.5.4, it does not show up under Screen Recoding. Rolled back to v2.5.3-2.

**Comment by phoerious** [comment]
It will not show up before you start a global Auto-Type.

**Comment by h0lgerg** [comment]
Tried it again, following you steps, but stil no luck. KeePassXC does not show up unter Screen Recording after starting a global Auto-Type. Only receive the message that permission are required again and again.

Btw, I can reproduce the right mouse click issue. It happens, if you right click into the KeePassXC window, when it is not the active window. I can only go back to normal right click behaviour, if I activate another window again and make a left mouse click into the KeePassXC window. However, this happens in 2.5.3 as well.

**Comment by droidmonkey** [comment]
Both of these are known issues, one with macOS 10.15 permissions and one with Qt (bug report is filed).

To fix the permissions issue just follow these instructions:

https://apple.stackexchange.com/questions/384230/how-do-i-reset-screen-recording-permission-on-macos-catalina

**Comment by quinncomendant** [comment]
I don't have a `Screen Recorder` section in the System Preferences > Security & Privacy > Privacy pane. Is that something that should exist in Mojave?

**Comment by phoerious** [comment]
The Screen Recording permission is new in Catalina.

**Comment by alexanderkress** [comment]
I was able to get v2.5.4 running incl. right mouse click and autotype:
- close running instance 2.5.3
- download latest 2.5.4
- move app to Applications folder
- reboot !!
- start KeePassXC 2.5.4 first time after reboot
--> right mouse click was already working
--> accessibility option for KeePassXC was already set
- performed autotype --> system requires screen capture option --> this time the entry was listed and I could activate it

Summary:
After the installation of 2.5.4 I reboot the Mac, which solved my issue.

**Comment by alexanderkress** [comment]
I can also confirm the right click issue reported by @h0lgerg.
So in general the right click is also working in 2.5.4.

**Comment by hmueller01** [comment]
Thanks for these hints. I did not need to remove the application. But I needed a reboot to get screen recording work. Is MacOS now like Windows where you need to reboot to get things work???

**Comment by ChristopherSchultz** [comment]
Confirmed rebooting 10.15 Catalina resurrects auto-type. I haven't yet rebooted my 10.14 Mojave laptop.

**Comment by HUGHUSR** [comment]
I'm confused. Is this an open issue or not? It's pinned, yet status shows as CLOSED!

It is **_definitely_** still a problem on fully patched macOS 10.14.6 and it is only broken on KeepassXC 2.5.4 and worked correctly on 2.5.3.

It is whitelisted in Accessibility settings, too.

**Comment by alexanderkress** [comment]
Since the reboot solved the auto-type feature, the issue has been closed.
At least 4 users had been able to get auto-type running again after rebooting the Mac.

The right mouse click menu entries is a different topic and not related to this issue anymore.

**Comment by HUGHUSR** [comment]
Hello,
Okay, it took me an hour or so to save everything and reboot. But,
when I did, I agree it works now.
This is obviously a bug that should be reported to Apple.
I hope you all have reported it. If not, you should!
Thanks for your help.
On Apr 15, 2020, at 19:25 , Alexander Kress  wrote:
	Since the reboot solved the auto-type feature, the issue has been
closed.
 At least 4 users had been able to get auto-type running again after
rebooting the Mac.

	The right mouse click menu entries is a different topic and not
related to this issue anymore.

**Comment by rogierg** [comment]
I'm on 10.15.3 and also had issues with autotype. Tried rolling back but the problem persisted. I got it going again on 2.5.4 with the following steps:

1. Remove keepassxc and all traces (plist etc.)
2. Check that keepassxc is no longer visible in accessibility and screen recording (if it is: you did not remove it completely)
3. Install 2.5.4 and perform auto type twice
4. Confirm permissions for screenrecording and autotype
5. Restart keepass
6. Profit

Reboot was not necessary. Previous version (2.5.3 for me) had all required permissions.

**Comment by antman2** [comment]
Adding an issue comment because I still think there's something fishy going on here - none of my other Accessibility-requesting apps require a reboot after installs and updates.

I also found a reboot was necessary with KeePass 2.5.4 so as to get Control-Command-A Auto-Type working, however Shift-Command-V Auto-Type always worked after granting Accessibility permission.

Having been uninstalling and reinstalling KeePass 2.5.0, 2.5.1, 2.5.2, 2.5.3, 2.5.3-2 and 2.5.4 for the last little while before discovering this issue ticket, 2.5.4 was the only version to prompt for Documents folder permissions when opening a .kdbx file. KeePassX did not appear in Security & Privacy > Files and Folders until after the reboot occurred, at which point it appears with Documents ticked like most normal applications. This seems new/different/odd and may be related.
