### ISSUE TITLE
KeepassXC 2.5.4 on macOS 10.15.4 not listing Hardware Key (YubiKey)

### ISSUE THREAD

**Issue by UnbornChicken** [keepassxreboot/keepassxc#4575]
## Expected Behavior
Unlock database using Password + Hardware Key (YubiKey) Challenge Response

## Current Behavior
After upgrading to KeepassXC 2.5.4 and opening a database secured by a password and a (hardware key) challenge response, no hardware keys were listed in the dropdown list

## Steps to Reproduce
1. Upgrade to KeepassXC 2.5.4 (I used Homebrew)
2. Open a database secured by a password and challenge response  
3. Try to select a hardware key  (none are listed)
4. Click 'Refresh' --> still no hardware keys listed
5. Fail to unlock database

## Context
After reverting to 2.5.3-2 unlocking works again

## Debug Info
KeePassXC - Version 2.5.4
Revision: dcca5aa

Qt 5.14.1
Debugging mode is disabled.

Operating system: macOS 10.15
CPU architecture: x86_64
Kernel: darwin 19.4.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
 libgcrypt 1.8.5

**Comment by phoerious** [comment]
Works for me. Try replugging the key and check that it's not plugged in upside down, then hit Refresh. If it's still not working then try rebooting.

**Comment by UnbornChicken** [comment]
Replugging didn't solve the problem and I am using a USB-C key which can't be plugged in upside down, however rebooting fixed the issue. :)

**Comment by clifflu** [comment]
YubiKey 4 / KeepassXC 2.5.4 / macOS 10.15.4 (Catalina)

After reboot, KeepassXC asked for permission to receive keystroke.
YubiKey backs to normal after granting that permission from `Security & Privacy`.

**Comment by maybeageek** [comment]
I have the same issue. Rebooting does not help, nor does using KeepassXC 2.5.3 work. KeePassXC does not see any Yubikey on the mac.

The yubikey works without problem in my browsers, for example tested with webauthn.io

Yubikey 5 NFC / KeepassXC 2.5.3 and 2.5.4 / macOS 10.15.4 (with supplemental update: build 19E287)
