### ISSUE TITLE
AppleWatch unlock possible ?

### ISSUE THREAD

**Issue by F3000** [keepassxreboot/keepassxc#4576]
could this be integrated in KepassXC for OSX ? 

Didn’t find any setting for that yet

**Comment by droidmonkey** [comment]
No this will not be integrated.

**Comment by F3000** [comment]
Ok . Can I ask why ?

**Comment by droidmonkey** [comment]
We are not an iOS app, for one. Two, there is no way to test this without an iWatch and it is not ever going to happen based on time  required to implement it if it even is possible.

**Comment by F3000** [comment]
you don’t have to create an iOS app for that .... 

But you decide for which feature do you have time 👍
