### ISSUE TITLE
the new version pop-up is too aggressive

### ISSUE THREAD

**Issue by FlorinAndrei** [keepassxreboot/keepassxc#4577]
v2.5.3

When a new version is detected, the app creates a pop-up message. This happens too soon after the app is launched.

This is a utility app. I launch it at the moment when I'm about to log into a website and I need a password *right now*. Anything that pulls me out of the workflow is a distraction. What I expect is to be able to type in my master password quickly, and get to the information as soon as possible.

Instead, the pop-up gets in the way. I often type the password blindly, then hit enter, and *then* I notice there was a pop-up there. What was it? Was it important? Did something crash? Did I hit Enter on something I did not intend to do? And by the way, typing the password did not work, because it was masked by the pop-up.

Folks, slow down. You're WAY too aggressive with that pop-up. Give it some extra time. Let the users settle in, let them get their info first.

Thanks!

**Comment by droidmonkey** [comment]
You can disable the check for updates on the settings. I want to place that notice in our new notification center once it is created. I hate pop-ups as well.
