### ISSUE TITLE
Not Clearing Clipboard

### ISSUE THREAD

**Issue by Minter1** [keepassxreboot/keepassxc#4578]
## Expected Behavior
The clipboard should clear automatically after the number of seconds set in settings. 

## Current Behaviour
The clipboard contents remains on the clipboard for pasting into any programme which is a security risk. 

## Steps to Reproduce (for bugs)
It should be easy to replicate. I am running Fedora 31
1.
2.
3.
4.

## Debug info

KeePassXC - Version 2.5.3
Revision: f8c962b
Distribution: Flatpak

Qt 5.13.2
Debugging mode is disabled.

Operating system: Linux 5.5.15-200.fc31.x86_64
CPU architecture: x86_64
Kernel: linux 5.5.15-200.fc31.x86_64

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.5

Operating system: Linux
Browser: Firefox

**Comment by Minter1** [comment]
Hi, yes I am. :+1: 

Also, I have noticed that the autotype hot key ctrl + v is not working to autofill password and username.

**Comment by droidmonkey** [comment]
This is a duplicate issue and not one we can correct (in either case).

**Comment by Minter1** [comment]
ok, thanks for your reply. Do you think it is a Linux issue in general rather than a specific distro ssue? 

Also,, in case its of interest to you, I did have the basic autotype working in KeePassX on Linux Mint.

**Comment by droidmonkey** [comment]
It's Wayland

**Comment by malo44** [comment]
I have the same problem with Keepassxc 2.4.3 in Ubuntu 19.04. I dont run Wayland

echo $XDG_SESSION_TYPE = x11
