### ISSUE TITLE
Improve column selection in CSV import window

### ISSUE THREAD

**Issue by jwatt** [keepassxreboot/keepassxc#458]
Thanks so much to @seatedscribe for the work to implement CSV import! I just built from source to try it out and managed to successfully import a CSV file exported from Firefox. This is a really great step forward to lowering the barrier to switching to KeePassXC. :)

I have one piece of feedback: I found the way that columns are selected to be really quite frustrating in practice since in my case I had to reorder multiple columns and the whole thing became a bit of a memory game. The crux of the issue is that when a column is changed, the data it contains is replaced with the contents that *should* be under that header, making it necessary to memorize what *used* to be in that column for when you need to specify that column later. The more columns you update, the harder it becomes to remember. Maybe it was because I was tired, maybe it's because I'm dumb, but I personally had to start over a couple of times before getting it right, which was a bit frustrating. ;)

In case the preceding description of the problem isn't clear, here's a walk through to hopefully make the issue more concrete:

Say I start out with:

<pre>
 Group             Title   Username   Password                      URL         Notes
 --------------------------------------------------------------------------------------------
 https://foo.com   jwatt   pass1      https://foo.com/form-target   Foo Login   usernameField
 https://bar.com   jwatt   pass2      https://bar.com/form-target   Bar Login   userField
 ...
</pre>

Now say I update the "Group" dropdown to select "Not present in the CSV file", the display now changes to:

<pre>
 Group           Title   Username   Password                      URL         Notes
 ------------------------------------------------------------------------------------------
                 jwatt   pass1      https://foo.com/form-target   Foo Login   usernameField
                 jwatt   pass2      https://bar.com/form-target   Bar Login   userField
 ...
</pre>

Then I update the "Title" dropdown to select "Column 5", and the display changes to:

<pre>
 Group     Title       Username   Password                      URL         Notes
 ----------------------------------------------------------------------------------------
           Foo Login   pass1      https://foo.com/form-target   Foo Login   usernameField
           Bar Login   pass2      https://bar.com/form-target   Bar Login   userField
 ...
</pre>

Now I switch to the "Username" dropdown and look for that data in the table, but it's gone. Since I was paying attention to what data I needed, not what data I was *hiding*, I've already forgotten which column in the source data contained the usernames. I reset the columns and start over and the next time round I remember that it's column 2 that contains the usernames, so I set the "Usernames" dropdown to "Column 2":

<pre>
 Group     Title       Username   Password                      URL         Notes
 ----------------------------------------------------------------------------------------
           Foo Login   jwatt      https://foo.com/form-target   Foo Login   usernameField
           Bar Login   jwatt      https://bar.com/form-target   Bar Login   userField
 ...
</pre>

Moving on to the "Password" dropdown I manage to remember that that's the column I just hid, so I set the dropdown to "Column 3":

<pre>
 Group     Title       Username   Password   URL         Notes
 ---------------------------------------------------------------------
           Foo Login   jwatt      pass1      Foo Login   usernameField
           Bar Login   jwatt      pass2      Bar Login   userField
 ...
</pre>

Now I'm at the "URL" dropdown and, since that was a column I hid several steps ago, I've again completely forgotten which source column I need.

Frustrated, I start over from the beginning once again, telling myself there has to be a better system for users to specify which columns contain which data in the CSV.

This time I write out what each column in the source data contains on a piece of paper in advance and, yay, succeed. :)

**Comment by jwatt** [comment]
To avoid confusion I think it would be best to avoid changing the table of data that is displayed, and especially to avoid hiding data that the user would prefer to see. Offhand I have two suggestions:

Perhaps one solution would be to make the headers of the columns into dropdowns from which the user is asked to select the type of data in each column. Something like:

<pre>
 Select the data that each column contains:

 |select|          |select|  |select|   |select|                      |select|    |select|
 -------------------------------------------------------------------------------------------
 https://foo.com   jwatt     pass1      https://foo.com/form-target   Foo Login   usernameField
 https://bar.com   jwatt     pass2      https://bar.com/form-target   Bar Login   userField
 ...
</pre>

Where each dropdown contains:

<pre>
 | Group            |
 | Title            |
 | Username         |
 | Password         |
 | URL              |
 | Notes            |
 | other (ignored)  |
</pre>

Alternatively if the headers can be made to be dragable (possibly more tricky in terms of implementation) then the user could be asked to drag the headers to the correct columns (or vice versa). This seems less usable for users with some disabilities though.

**Comment by seatedscribe** [comment]
Hello Jonathan! Thanks for your feedback, it's really appreciated.

The idea behind this approach is simply that while you visit each of the
combo boxes with the mouse, you scroll with the central wheel until you
think the data makes sense. Do this for every column and you are done.

No need to write down the right column in advance, just play a little bit
since you have unlimited shots and just six scrolls to choose from! :)

Your (first) solution could be an alternative, however we should consider
that the fields would not be in a fixed order and this could confuse (at
least, me) when looking at the whole table for the final approval.

P.S. With this approach I tried to avoid frustration already, not to add
more! ;)

**Comment by jwatt** [comment]
Hi Tarquin! Thanks for being open to listening to my feedback!

Now that you explain it I can see how spinning the dropdown with a mouse wheel would work. It's clever. :) There are two reasons I don't think most users will end up working with the importer in this way in practice though.

First, people are used to selecting from a dropdown, but they're not used to their actions changing and hiding columns in a table at the same time. There's a mental leap for people to make to hit on the method of interaction you describe and I'm not sure most people will make it.

Second I don't think most people **can** spin the dropdown in the way you envisage since most people nowadays are using laptops and tablets without a mouse connected. Well, at least at home. But then people that click-and-select (rather than spin) at home are likely to do the same at work out of habit, even though they're more likely to have a mouse available to them at work.

Oh, and of course the people who are visually impaired and others who rely on a screen reader don't typically use a mouse. (But for them the changing of the contents of the table will be a much bigger nightmare anyway, unfortunately.)

> Your (first) solution could be an alternative, however we should consider that the fields would not be in a fixed order and this could confuse (at least, me) when looking at the whole table for the final approval.

I'm not sure what you mean. Do you mean that you would find it confusing that when you import one CSV file you could end up with the headings in a different order than when you later import a different CSV file from different source? The headers would still match what's under them though, no?

> P.S. With this approach I tried to avoid frustration already, not to add more! ;)

Absolutely! I'm not in any way saying otherwise. Part of UX design is to gather feedback from people not involved in the design to see how they get on with your design in practice though. I'm just trying to provide some feedback for you on how this one user (me) got on with it, and why I might have had the experience I had. :)

**Comment by seatedscribe** [comment]
> Part of UX design is to gather feedback from people not involved in the
design to see how they get on with your design in practice though. I'm just
trying to provide some feedback for you on how this one user (me) got on
with it, and why I might have had the experience I had. :)

Thank you very much for your feedback and thoughtful considerations! I hope
more and more people do the same and share their experience here.
