### ISSUE TITLE
Compile Windows version with CFG enabled

### ISSUE THREAD

**Issue by savchenko** [keepassxreboot/keepassxc#4582]
## Summary
Please consider compiling Windows version of KeePassXC with [control flow guard](https://docs.microsoft.com/en-us/windows/win32/secbp/control-flow-guard) enabled.

## Desired Behavior
CFG enabled.

## Possible Solution
Use MS Visual Studio for the build process of Windows version end [enable `/guard:cf` flag](https://docs.microsoft.com/en-us/cpp/build/reference/guard-enable-control-flow-guard?view=vs-2019)

## Context
CFG is amongst techniques used by MS to defend against ROP / memory corruption.  
This seems to be relevant in context of the application that acts as the central secrets storage.

**Comment by droidmonkey** [comment]
We don't build with visual studio.

**Comment by droidmonkey** [comment]
However, this might be relevant: https://clang.llvm.org/docs/ControlFlowIntegrity.html

**Comment by asvc** [comment]
Thanks Jonathan, `-fsanitize=cfi` and `-fsanitize-cfi-cross-dso` look promising. I will be happy to beta-test the build if KeePass XC can be compiled this way.

**Comment by droidmonkey** [comment]
Sure you can give it a go

**Comment by asvc** [comment]
Err, what I have meant is "if someone can compile such build"... Too late.

_/me heads off learning how to build KeePassXC on Windows..._

**Comment by asvc** [comment]
I have compiled using defaults and `v2.6.0-snapshot` binary was operational. 

Next, building using the release tool:
```sh
$ ./release-tool build --cmake-options "-fsanitize=cf -flto" --version "cfi"`
# Enabled features:
 * Auto-Type, Automatic password typing
 * Networking, Compile KeePassXC with network access code (e.g. for downloading website icons)
 * KeePassXC-Browser, Browser integration with KeePassXC-Browser
 * SSHAgent, SSH agent integration compatible with KeeAgent
 * KeeShare, Sharing integration with KeeShare (requires quazip5 for secure containers)
 * YubiKey, YubiKey HMAC-SHA1 challenge-response
 * UpdateCheck, Automatic update checking
```
...and it fails with `0xc000007b`:
![image](https://user-images.githubusercontent.com/300146/79639876-7c2faf00-81cd-11ea-8fb9-5d4f2d49256f.png)

Alright, let's try with a gentle touch first:
```sh
./release-tool build --cmake-options "-fsanitize=cfi-cast-strict -fsanitize-stats -fsanitize-recover=all -flto" --version "cfi"
```
...Same result. Checking the PE:
```powershell
FileName         : C:\msys64\home\user\keepassxc\release\build-release\src\KeePassXC.exe
ARCH             : AMD64
DotNET           : False
ASLR             : True
DEP              : True
Authenticode     : False
StrongNaming     : N/A
SafeSEH          : N/A
ControlFlowGuard : False
HighentropyVA    : True
```

Shall this issue be labelled as "not going to happen" and closed?

**Comment by droidmonkey** [comment]
Don't use the release tool to build, you should create a build folder and run cmake directly in that folder.

**Comment by asvc** [comment]
Thanks, will give it a go.

**Comment by asvc** [comment]
Same error, but this time I have ended-up with 116Mb (!) binary:
```ps
Get-PESecurity -File .\KeePassXC.exe
FileName         : C:\msys64\home\user\keepassxc\build\src\KeePassXC.exe
ARCH             : AMD64
DotNET           : False
ASLR             : False
DEP              : False
Authenticode     : False
StrongNaming     : N/A
SafeSEH          : N/A
ControlFlowGuard : False
HighentropyVA    : False
```

**Comment by droidmonkey** [comment]
That's the debug build with symbols included.

**Comment by asvc** [comment]
I thought so, but it seems like MSYS either falls back to gcc if template is used, or refuses to switch over to clang if compiler options are passed via command line:
```sh
$ cmake -G"MSYS Makefiles" -DWITH_XC_ALL=OFF -DCMAKE_CXX_COMPILER=/mingw64/bin/clang++ -DCMAKE_C_COMPILER=/mingw64/bin/gcc ..
-- The C compiler identification is GNU 9.3.0
-- The CXX compiler identification is Clang 10.0.0
CMake Error at CMakeLists.txt:19 (project):
  The CMAKE_C_COMPILER:

    C:/msys64/mingw64/bin/gcc

  is not a full path to an existing compiler tool.

  Tell CMake where to find the compiler by setting either the environment
  variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
  the compiler, or to the compiler name if it is in the PATH.


CMake Error at CMakeLists.txt:19 (project):
  The CMAKE_CXX_COMPILER:

    C:/msys64/mingw64/bin/clang++

  is not a full path to an existing compiler tool.

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.
```

**Comment by asvc** [comment]
Built it with clang, image does not load with the same error as above. I have tried passing options via `-D` flag as well as `--cmake-options`.

Interesting glitch: I had to export CC/CXX _not_ as full paths to make it work:
```sh
$ echo $CXX && echo $CC
clang++
gcc
```

After exporting the variables above, compilers were defined via ` -DCMAKE_CXX_COMPILER=$CXX -DCMAKE_C_COMPILER=$CC `

**Comment by phoerious** [comment]
Try building with everything off, particularly Auto-Type. Your CC is still pointing to gcc.

**Comment by savchenko** [comment]
I am not using Windows systems as much as I used to when this issue was created and unlikely to continue working on it.

If someone else is interested in picking this up - I hope that information present in this issue will be of some help.
