### ISSUE TITLE
KeepassXC 2.5.4 will not start on Windows

### ISSUE THREAD

**Issue by MLipfert1** [keepassxreboot/keepassxc#4583]
## Description
The latest version 2.5.4 compiled for Windows x64 will not start after the installation is finished. The Windows-Task-Manager shows a RAM-usage of only 3 KB and no CPU-load. 

A complete uninstallation followed by a re-installation will also not circumvent this problem. Even removing old configuration files will not fix this starting problem.

The old version 2.5.3 is able to start again, after I downgraded KeepassXC.

## Debug Info
KeePassXC - 2.5.4

Operating system: Windows 10 (2004) Build 19041.173
CPU architecture: x64

**Comment by droidmonkey** [comment]
Have you tried restarting your computer?

**Comment by MLipfert1** [comment]
Yes, of course. That will change nothing.

**Comment by dhardtke** [comment]
Just upgraded, works for me without problems on Windows 10 64bit Version 1909.

Maybe it's got something to do with the newer Windows version that you're using?

**Comment by asvc** [comment]
Works fine here:
```
KeePassXC - Version 2.5.4
Revision: c023bf9

Qt 5.14.2
Debugging mode is disabled.

Operating system: Windows 10 Version 1909
CPU architecture: x86_64
Kernel: winnt 10.0.18363
```

**Comment by MLipfert1** [comment]
I am able to start version 2.5.4 in a virtual machine using the same version 19041.173 of Windows 10 with only Visual Studio 2019 installed in this virtual machine. So the windows version itself is not the problem. I will try to investigate further on it.

**Comment by MLipfert1** [comment]
It seems to be related to Qt 5.14.2, that is bundled with KeePassXC 2.5.4. The old version 2.5.3 uses Qt 5.13.2. If I copy the new 5.14.2 DLLs to the directory of KeePassXC 2.5.3 it will show the same problem as 2.5.4. Of course copying the files to the directory is not a clean way to prove it, but it might be a hint.

**Comment by hifi** [comment]
Does 2.5.4 work with Qt 5.13.2 libraries?

**Comment by droidmonkey** [comment]
You can't just willy nilly copy Qt files

**Comment by phoerious** [comment]
This sounds an awful lot like #4536.

**Comment by MisterY** [comment]
Just upgraded via MSI and the app started normally at the end of the installation process.
```
KeePassXC - Version 2.5.4
Revision: c023bf9

Qt 5.14.2
Debugging mode is disabled.

Operating system: Windows 10 Version 1903
CPU architecture: x86_64
Kernel: winnt 10.0.18362

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.5
```

**Comment by eL-M0** [comment]
I observe the same issue as MLipfert1. I upgraded from 2.5.3 to 2.5.4 and it is not working. After run I do not see program's window only process.

Operating system: Windows 10 (10.0) [I do know why revision is not recognized]
CPU architecture: x86_64
Kernel: winnt 10.0.18362

**Comment by kekukui** [comment]
Related issue https://github.com/keepassxreboot/keepassxc/issues/4650

**Comment by Farix1337** [comment]
I have the same issue. 2.53.0 works just fine. 2.54.0 does not work either
see my comment in the related issue: https://github.com/keepassxreboot/keepassxc/issues/4650#issuecomment-620596822

**Comment by MLipfert1** [comment]
The problem is somehow also related to the Windows user account. I created a second account on the machine, on which the problem occurs. Using this account, KeepassXC 2.5.4 (portable) is starting fine. I will investigate on it further.

**Comment by MLipfert1** [comment]
I finally found the culprit for this issue and a way to solve it for me. The issue is caused by [this](https://bugreports.qt.io/browse/QTBUG-84275) QT-Bug. 

When the Windows locale is using the same character for decimal places and thousands seperators for floating point numbers, QT is deadlocking. According to the QT bugreport, this is especially a problem for the greek locale.

I am using the german locale and for whatever reason my locale settings were misaligned. Usually the problem should not occur for my locale, because of different characters for the mentioned parameters. I was able to fix it for me by just clicking the reset button (step 3 in the screenshot):

![Locale](https://user-images.githubusercontent.com/63508182/82660675-12bb1a00-9c2b-11ea-83d9-0800d151ec62.png)

So I suggest to release an updated version of KeepassXC as soon as the QT bug is fixed and the updated QT version is available.

**Comment by droidmonkey** [comment]
Wow wtf

**Comment by MLipfert1** [comment]
According to the Qt-Bugreport, this issue should have been fixed with Qt 5.15.0. Is this version already available for the MingW environment? If yes, I am willing to test it.

**Comment by stdedos** [comment]
Maybe pull off 2.5.4 from the updater notification until this is resolved? 😕

**Comment by droidmonkey** [comment]
It usually takes up to a week for mingw to be updated with new Qt.

**Comment by droidmonkey** [comment]
Good news, Qt 5.15 is now available on msys2, this will be resolved when we release 2.6.0.

**Comment by Dreanad** [comment]
Hello there, sorry to send a comment on a closed issue but i think i have the same problem, but the reset local number not working for me .. 

i have tried a lot of things, restart, uninstall,  empty all ghub  folder, clean registry, start ghub in order with update/agent/ghub 
but nothing worked ... ( i dont see the agent in process when i launch it ) 

do you have an idea ?

**Comment by droidmonkey** [comment]
No, use the latest release and you should be fine.

**Comment by Dreanad** [comment]
thats what i do ! the lghub_agent.exe seems to stop imediately and disapear from tasks

**Comment by droidmonkey** [comment]
Are you on the right project? We don't have an lghub_agent.exe

**Comment by Dreanad** [comment]
Oops sorry, my bad
