### ISSUE TITLE
KeePassXC 2.5.4 auto-type is not working anymore on MacOS Catalina 10.15.4 

### ISSUE THREAD

**Issue by relgames** [keepassxreboot/keepassxc#4586]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
When I select an entry and then select Auto-Type from the menu, it should minimize the KeePassXC window and auto-type username/password

## Current Behavior
[NOTE]: # ( Tell us what actually happens )
It keeps prompting for Accessibility permissions, and it has the permission.
I tried to re-install, remove / add permission, in different combinations, did not help.

<img width="664" alt="Screenshot 2020-04-11 at 19 14 46" src="https://user-images.githubusercontent.com/179605/79050268-34d37c80-7c29-11ea-849d-ba47a19b2d1d.png">
<img width="463" alt="Screenshot 2020-04-11 at 19 13 55" src="https://user-images.githubusercontent.com/179605/79050382-f4c0c980-7c29-11ea-8e02-9b18873c8984.png">

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )
Probably, started to happen after upgrade to MacOS 10.15.4 - so maybe check what changed in Apple APIs?

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1. Select an entry
2. Select auto-type from the right-click menu
3. It asks for MacOS permissions, but giving permission and restarting KeePassXC does not help

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )
Nothing unique, latest MacOS, and latest KeePassXC 2.5.4 installed via homebrew

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.5.4
Revision: dcca5aa

Qt 5.14.1
Debugging mode is disabled.

Operating system: macOS 10.15
CPU architecture: x86_64
Kernel: darwin 19.4.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
 libgcrypt 1.8.5

**Comment by droidmonkey** [comment]
Search the issue board please.

**Comment by relgames** [comment]
Hi, I did searched before and I did tried multiple work-arounds, as I mentioned in the bug description.

Here is the search query I used: https://github.com/keepassxreboot/keepassxc/issues?page=5&q=is%3Aissue+auto-type

Issues I found and tried work-arounds but they did not help:
- https://github.com/keepassxreboot/keepassxc/issues/4330
- https://github.com/keepassxreboot/keepassxc/issues/4264
- https://github.com/keepassxreboot/keepassxc/issues/4573
- https://github.com/keepassxreboot/keepassxc/issues/3089
- https://github.com/keepassxreboot/keepassxc/issues/2883
- https://github.com/keepassxreboot/keepassxc/issues/2825
- https://github.com/keepassxreboot/keepassxc/issues/2473
- https://github.com/keepassxreboot/keepassxc/issues/2448

Seems like other people also have the same issue, where they tried same steps as I did but it still did not work, yet you just closed their issues just like this issue.

Some steps I tried:
- Uninstalled and installed KeePassXC
- Removed and added back KeePassXC in Privacy / Accessibility 
- Restarted KeePassXC

Tried to reset Accessibility:
```
~ tccutil reset Accessibility
Successfully reset Accessibility
~ tccutil reset Accessibility org.keepassxc.keepassxc
Successfully reset Accessibility approval status for org.keepassxc.keepassxc
Successfully reset Accessibility approval status for org.keepassxc.keepassxc
```
KeePassXC disappeared from the list in Privacy Settings, I restarted it but issue is still there.

Is there anything I can do to help debug the problem?

**Comment by phoerious** [comment]
You need to reboot your system.

**Comment by relgames** [comment]
I rebooted again and this time it worked. Never though I'm back to old Windows times where need to reboot to make something work. Thanks and sorry for taking your time.

**Comment by droidmonkey** [comment]
Welcome to macos catalina
