### ISSUE TITLE
macOS dock show "All desktops" not working

### ISSUE THREAD

**Issue by Tormen** [keepassxreboot/keepassxc#4587]
## Expected Behavior
Until the update to v2.5.4 I had set keepassxc to show on all desktops and this was working as epxected: when keepassxc is visible on desktop A and one switches to desktop B keepassxc stays visible!
And I tested the same with other apps (e.g. 'iTerm' and there it works as expected: Select "All Desktops", switch desktop and iTerm "follows" sticks to all desktops !

## Current Behavior
Now it sticks to the desktop it was opened in, no matter what I try.
See screencast: https://0x0.st/iSlS.mkv
The screencast starts with keepassxc just have been launched (after quitting it) and I pretyped my password, then started the screenrecording.

## Possible Solution
No solution / workaround found :(

## Steps to Reproduce
See screencast: https://0x0.st/iSlS.mkv

1. Start Keepassxc on desktop A
2. Right click Dock, options, select "All desktops"
3. Switch to desktop B, keepassxc window should be visible, but it isn't

## Context
I heavily use workspaces / desktops. Have different apps on different workspaces. Keepassxc needs to be able to show / pop-up on ANY of these workspaces (hence the "All desktops" setting).

## Debug Info
```
KeePassXC - Version 2.5.4
Revision: dcca5aa

Qt 5.14.1
Debugging mode is disabled.

Operating system: macOS 10.15
CPU architecture: x86_64
Kernel: darwin 19.4.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
 libgcrypt 1.8.5
```

Libraries:
- ?? installed via `brew cask install keepassxc`

Operating system: MacOS Catalina 10.15.4 (19E287)
CPU architecture: 64-bit
Kernel: Darwin macado.no-panic.eu 19.4.0 Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64 x86_64

Enabled extensions:
- ? You mean MacOS kernel extensions ?
If yes:
`kextstat|awk '{print $6}'|grep -v "^com.apple"`

Name
at.obdev.nke.LittleSnitch
com.paragon-software.kext.VDMounter
com.paragon-software.filesystems.ntfs
org.virtualbox.kext.VBoxDrv
org.virtualbox.kext.VBoxUSB
org.virtualbox.kext.VBoxNetFlt
org.virtualbox.kext.VBoxNetAdp

**Comment by droidmonkey** [comment]
Have you tried restarting your computer? Are you sure you have the right app docked? Try undocking and redocking it.

**Comment by Tormen** [comment]
Hi, yes tried to restart. Right app docked: Yes, see screencast :)

**Comment by Tormen** [comment]
Humm. OK. I thought it's the right App docked as it clearly responded when clicking the dock... but your idea to undock and redock fixed the issue!

Sorry for the fuzz. Still relatively new to MacOS and learning.
