### ISSUE TITLE
Startup crash on Kubuntu 16.04.1 installed from snap

### ISSUE THREAD

**Issue by corehack** [keepassxreboot/keepassxc#459]
Can't start it in graphics mode. Only cli interface works.

## Expected Behavior
Keepassxc started

## Current Behavior
```
$ keepassxc 
amdgpu: drmGetDevice failed.
Segmentation fault

```
## Your Environment
Kubuntu 16.04
`Linux 4.8.0-41-generic #44~16.04.1-Ubuntu SMP Fri Mar 3 17:11:16 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`
KeePassXC 2.1.3
Qt 5.5.1
Using AMD Polaris gfx card with opensource driver (amdgpu). Also using Padoka PPA for fresh Mesa stuff

**Comment by droidmonkey** [comment]
Snaps are only officially supported in Ubuntu 16.10.

**Comment by corehack** [comment]
Snap as a feature of Ubuntu is supported since 16.04, it was preinstalled in my distribution of Kubuntu.
https://www.ubuntu.com/desktop/snappy
Or did you mean something different ?

**Comment by droidmonkey** [comment]
Interesting, I stand corrected. Please try the latest snap that i posted on the store. This might also be an issue with snaps interacting with your X11 interface for display. Do any other snaps work?

**Comment by corehack** [comment]
I haven't tried any other snaps, generally I don't use that type of packaging. But I've tried the AppImage package, and it worked. I just don't like AppImage since its just one big binary, and I don't want to use Debian repo since its marked as unofficial.

I've tried to download and install the snap again, no change..still crashing

**Comment by droidmonkey** [comment]
I think this is something unique to your situation. Continue using the snap. I recommend performing a complete reinstall of the snap infrastructure and trying another snap to rule out our app in particular.

**Comment by corehack** [comment]
I've tried a simple Qt app in a snap package.
```
$ sudo snap install notes
notes 0.9.0~gitb6e3b34 from 'notes-developers' installed
$ notes
libGL error: pci id for fd 9: 1002:67df, driver (null)
libGL error: No driver found
libGL error: failed to load driver: (null)
libGL error: pci id for fd 9: 1002:67df, driver (null)
pci id for fd 11: 1002:67df, driver (null)
libGL error: failed to create dri screen
libGL error: failed to load driver: radeonsi
XmbTextListToTextProperty result code -2
XmbTextListToTextProperty result code -2
XmbTextListToTextProperty result code -2
```
You can see there are many errors reported, but the application starts and works without any visible problem.

**Comment by corehack** [comment]
I've tried another snapped app - kdenlive. It also has GL related errors on startup, but it starts in the end, falling back to software rendering. Same as "notes" app above, I guess.
So the problem with keepassxc could be that it can't fall back to software rendering as other apps.

**Comment by corehack** [comment]
Perhaps official Debian/Ubuntu repos could be provided as an alternative. Looking at https://bugs.launchpad.net/ubuntu/+source/snapd it doesn't look like Snap is ready to serve as the main packaging solution.

**Comment by droidmonkey** [comment]
Can't agree more. Snaps need a lot of work and most of the errors are opaque to the developer. It's certainly not our primary means of distribution... It's just the only means that does not require obscene reviews.

**Comment by corehack** [comment]
Care to open the issue ? Seems its still valid as your claim about snap unsupported in 16.04 proved to be incorrect

**Comment by corehack** [comment]
@droidmonkey Just informing you, I no longer have the issue. Maybe one of the recent system updates fixed this. But its ugly (#431)
Btw, you may consider flatpak instead of snap (or in addition)
