### ISSUE TITLE
KeePassXC (for macOS) stopped recognizing YubiKey after upgrade to ver. 2.5.4

### ISSUE THREAD

**Issue by aak2014** [keepassxreboot/keepassxc#4590]
Hello All,

straight after upgrade from ver 2.5.3-2 to ver 2.5.4 KeePassXC stopped working with YubiKey. Hitting 'Refresh' button doesn't help - it keeps showing "Select slot..." text. Can't open my pwd database... Please help!

my OS: macOS ver 10.15.4

Thanks and cheers,
Anton

**Comment by droidmonkey** [comment]
You probably need to reauthorize the USB permissions. Check it out: https://github.com/keepassxreboot/keepassxc/issues/3329#issuecomment-529847992

**Comment by aak2014** [comment]
Thank you! Actually I authorized KeePassXC in Full Disk Access, Input Monitoring and Accessibility, before writing the first post, just in case. It didn't help. Then after some time my laptop went to hibernation mode (with power off, not sleep). Then it started loading the OS but crashed (kernel panic). After full OS reboot KeePassXC started working with YubiKey, with no other specific actions from my side. Hope it will not stop again. Wired stuff......

**Comment by droidmonkey** [comment]
Welcome to macOS Catalina. They are trying to replicate the good old days of Windows Vista...

**Comment by doits** [comment]
I can confirm it does not work for me, either, even when giving it access to input monitoring manually.

What works, though, is starting it from terminal (iTerm2 in my case) with `/Applications/KeePassXC.app/Contents/MacOS/KeePassXC`.  The request to require input monitoring popped up once and I allowed it. Now iTerm is listed at input monitoring, too, but KeePassXC can access the yubikey at least.

Starting KeePassXC standalone does still not work, though, even everything worked with 2.5.3-2 ... what a mess.

**Comment by oivano** [comment]
This is an issue in ver 2.5.4 Simple rollback to ver 2.5.3 and all is working as expected.

**Comment by phoerious** [comment]
You need to reboot your system.
