### ISSUE TITLE
Persistent Application Settings in TailsOS

### ISSUE THREAD

**Issue by heyJonBray** [keepassxreboot/keepassxc#4592]
**Tails version:**4.4 --bootable USB
**KeePass version:**2.3.4

I have my Tails Persistence Manager set up to save my database every time I load Tails. The `keepassxc.ini` file `[General]` variables:
```
LastDatabases=/home/amnesia/Persistent/myDatabase.kdbx
LastDir=/home/amnesia/Persistent/
LastOpenedDatabases=/home/amnesia/Persistent/myDatabase.kdbx
```
All my database entries, auto-fill, and other settings are saved per item. However, the global settings that involve the auto-lock time and the 'Global Auto-Type Shortcut' are reset every time I reload TailsOS.

It would be nice if these settings would be saved as well.

**Comment by phoerious** [comment]
Please take this issue to the Tails developers. We do not peovide support for downstream distributions.
