### ISSUE TITLE
KeePassXC does not detect hardware key on Mac

### ISSUE THREAD

**Issue by itsayellow** [keepassxreboot/keepassxc#4593]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

I can no longer use my USB Yubikey with my Mac using KeePassXC 2.5.4.  In the "Unlock KeePassXC Database" dialog, it will not show my hardware key (or anything) even if I unplug/replug, and/or hit Refresh.

I could successfully use my USB Yubikey with my Mac using KeepassXC 2.5.3 and before.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
KeePassXC should detect my Yubikey USB key in the Hardware Key section of the "Unlock KeePassXC Database" dialog.

## Current Behavior
[NOTE]: # ( Tell us what actually happens )
The Hardware Key section of the "Unlock KeePassXC Database" dialog is grayed out, only the words "Select slot..." are grayed out and visible.  Pushing refresh doesn't find my key.  I cannot select anything in the Hardware Key section.

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1. Plug in a Yubikey to a USB port
2. Start KeePassXC
3. See if you can select the Yubikey in the Hardware Key section of the "Unlock KeePassXC Database" dialog.

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )

I can no longer open my database because I require my Yubikey

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.5.4
Revision: dcca5aa

Qt 5.14.1
Debugging mode is disabled.

Operating system: macOS 10.15
CPU architecture: x86_64
Kernel: darwin 19.4.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
 libgcrypt 1.8.5

**Comment by phoerious** [comment]
Please reboot your Mac. This issue has been discussed before.
