### ISSUE TITLE
Repeat of issue 4249 in v2.5.4

### ISSUE THREAD

**Issue by pwilliamson19** [keepassxreboot/keepassxc#4597]
Unable to terminate Keepass from tray. It's not clear to me from the 2 related issues whether this should be fixed in 2.5.4 (I run the portable version). Usual scenario - in tray, database has not been opened. Tried to terminate with right-click and exit. Just hangs, has to be terminated from task manager.

**Comment by droidmonkey** [comment]
This was not addressed by 2.5.4
