### ISSUE TITLE
MacOS: auto-type does not ask for screen recording permission

### ISSUE THREAD

**Issue by tcgoetz** [keepassxreboot/keepassxc#4598]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

When initiating auto-type, the app asks for accessibility permission, but does not ask for screen recording permission. A popup appears for with the following message:

> KeePassXC requires the Accessibility and Screen Recorder permission in order to perform global Auto-Type. Screen Recording is necessary to use the window title to find entries. If you already granted permission, you may have to restart KeePassXC.

When the app has "Accessibility" permission already, but does not have "Screen Recorder" permission, "Screen Recorder" can not be added manually.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

App causes OS dialog to appear for confirmation of "Screen Recorder" permission.

## Current Behavior
[NOTE]: # ( Tell us what actually happens )

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1.
2.
3.

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION
Revision: REVISION

Libraries:
- LIBS

Operating system: OS
CPU architecture: ARCH
Kernel: KERNEL

Enabled extensions:
- EXTENSIONS

**Comment by droidmonkey** [comment]
Search please
