### ISSUE TITLE
Bring HTTP Confirmation window to the front on MacOS

### ISSUE THREAD

**Issue by joshplus** [keepassxreboot/keepassxc#460]
In Linux, when a browser extension makes a request to KeepassXC, the window to confirm access pops up and comes to the foreground. In MacOS, the window pops up but it stays behind the browser.

## Expected Behavior
KeepassXC's confirmation window comes in front of the browser.

## Current Behavior
It stays behind the browser window. This makes it a lot more difficult to select the password or realize what's going on. For example, in Passifox, the context menu doesn't show up until the confirmation window has been dealt with.

## Possible Solution
It may work to close then re-open the window.

## Steps to Reproduce (for bugs)
1. Install Passifox, Firefox and KeepassXC on MacOS
2. Enable HTTP mode
3. Connect the two
4. The window to confirm will be behind Firefox.
5. Right click on a site with a saved password
6. The confirmation for access will stay in the background.

## Your Environment
* KeePassXC version/commit used: 2.3.1/76dcfb5ed0c874f6a835ef0347ddf6098b149e9b
* Qt version (e.g. Qt 5.3): 5.8.0
* Compiler (e.g. Clang++3.6.0): (Downloaded from home page)
* Operating System and version: MacOS Sierra

**Comment by droidmonkey** [comment]
This impacts windows as well. I'll take a look at it. Requests from the same site also get queued up causing you to press allow/deny many times.

**Comment by sheavner** [comment]
Seeing the same thing on OSX.   Sometimes there's a bouncy kpxc icon in the dock but only 20% of the time.   

v2.3.1 downloaded dmg on sierra 10.12.4.

**Comment by droidmonkey** [comment]
This will be fixed in 2.1.4

**Comment by joshplus** [comment]
Thank you very much!

**Comment by droidmonkey** [comment]
Corrected in v2.1.4 and merged to develop
