### ISSUE TITLE
Yubikey for "2FA" is not detected by 2.5.4 anymore (latest macOS)

### ISSUE THREAD

**Issue by cs-1** [keepassxreboot/keepassxc#4601]
## Expected Behavior
When starting KeePassXC on macOS it detects a plugged in Yubikey as a second factor. You enter the passphrase via keyboard and will then be prompted to press the hardware button of the Yubikey afterwards. This will unlock the KeePass DB.

## Current Behavior
The Yubikey is not detected at KeePassXC startup. Restarting the hardware key detection doesn't fix the problem.

## Possible Solution
Currently only a downgrade to 2.5.3-2 helps.

## Steps to Reproduce
1. Create a DB that's protected via Yubikey second factor.
2. Open KeePassXC with a plugged-in Yubikey
3. Observe that the Yubikey is not detected.

## Context
I've been using a Yubikey on macOS for a long while with KeePassXC. I haven't had any trouble so far. The problem seems to have been introduced in 2.5.4.

## Debug Info
KeePassXC - Version 2.5.4
Revision: dcca5aa

Qt 5.14.1
Diagnosemodus ist deaktiviert.

Betriebssystem: macOS 10.15
CPU-Architektur: x86_64
Kernel: darwin 19.4.0

Aktivierte Erweiterungen:
- Auto-Type
- Browser-Integration
- SSH-Agent
- KeeShare (bestätigtes und unbestätigtes Teilen)
- YubiKey
- TouchID

Kryptographische Bibliotheken:
 libgcrypt 1.8.5

**Comment by phoerious** [comment]
Please use the search function. Rebooting may already solve your problem.
