### ISSUE TITLE
Accessibility settings reset when trying autotype on macOS

### ISSUE THREAD

**Issue by sam1902** [keepassxreboot/keepassxc#4602]
When trying to use the trusty autotype feature, macOs asks for KeePassXC to be authorized in the Accessibility settings. After doing so, restarting the program and trying autotype again it automatically reverts the Accessibility setting to "unauthorized" even though I just authorized is.

## Expected Behavior
Usually, after installing/updating KeePassXC, the user should allow the app to take control of the keyboard by going to the Accessibility settings of the OS, clicking a checkbox, and restarting KeePassXC.

## Current Behavior
Now, when following the above steps and restarting the app, *when performing the autotype combo CMD+SHIFT+V*, the checkbox in Accessibility settings gets unchecked, an OS window prompts to allow or deny the permission to the app, and KeePassXC prompts the user to go to the settings to enable Accessibility.

## Possible Solution
I don't have a solution at the present time. I think this bug might be cause by a subroutine executed when KeePassXC tries to actually take control of the keyboard because the checkbox in settings doesn't uncheck when starting the app but only when autotyping.

This issue is closely related to #4264 but the proposed solution of removing/re-adding the permission doesn't work (tested)

## Steps to Reproduce
1. Close KPXC
2. Go to System Preferences > Security & Privacy > Accessibility
3. Unlock the pane
4. Remove KeePassXC in the right hand panel if it is present
5. Check/Add KeePassXC and check the checkbox next to it
6. Without closing the System Preference window, and while keeping the checkbox on screen, start KeePassXC
7. Go to any entry and press CMD+SHIFT+V (or go manually to Entries > Perform Auto-Type)
8. Witness the checkbox unchecking itself, an OS prompt in the background and a KPXC prompt in the foreground

## Context
I use auto type regularly with my web browser and not being able to use it anymore is really frustrating, and possibly a security threat (copy pasting instead of auto typing).

## Debug Info
KeePassXC - Version 2.5.4
Revision: dcca5aa

Qt 5.14.1
Debugging mode is disabled.

Operating system: macOS 10.15
CPU architecture: x86_64
Kernel: darwin 19.4.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
 libgcrypt 1.8.5

**Comment by phoerious** [comment]
Please reboot your system.

**Comment by sam1902** [comment]
> Please reboot your system.

Yes
