### ISSUE TITLE
Get an Independent 3rd Party Expert(s) to Test KeePassXC's Security 

### ISSUE THREAD

**Issue by CerebralFreeze** [keepassxreboot/keepassxc#4608]
## Summary
KeePassXC is pretty good.  When I first tried KeePass eons ago, I tried it for a couple of weeks and I had to uninstall it and go back to using LastPass.  But, now, I can say it's a truly first-rate product.  Of course, the most important quality in a Password Manager is the security of the program but that is something I have no idea about.  Why don't the developers submit the program to an independent 3rd party of experts who can truly assess the security of the program?  Not only would this skyrocket the visibility of the program itself, but current users will be confident that this is just as good or better than other programs out there.

## Desired Behavior
Have research scientists in this field do a full test on the product and have them publish the results.  With test results coming back with great news, many people will flock to using this program as well as current users will feel safe that their password manager is in good hands.

## Possible Solution
I first read this research paper that made me wary of LastPass and made me seek an alternative, especially one that is not web-based.  The research study was conducted by 5 researchers at the University of Berkeley, California.  The name of the published paper was **The Emperor’s New Password Manager: Security Analysis of Web-based Password Managers**.  Perhaps, contact them and request that they put KeePassXC through a rigorous test of how safe and strong it is.

## Context
I use KeePassXC and I want to know if the program is truly safe to use.

**Comment by droidmonkey** [comment]
See #433
