### ISSUE TITLE
Increase the DPI scaling of KeePassXC

### ISSUE THREAD

**Issue by CerebralFreeze** [keepassxreboot/keepassxc#4609]
## Summary
I have a 4k monitor and I would love if KeePassXC got an upgrade for its GUI.

## Desired Behavior
Make KeePassXC look beautiful.

## Possible Solution
Request some students to re-design the GUI.

## Context
I really like KeePassXC and I think the current developers did a great job.  With a new coat of paint, the developers will receive the recognition that they deserve.

**Comment by droidmonkey** [comment]
We already did this for the next version.

**Comment by wolframroesler** [comment]
Thanks for the thumbs-up @CerebralFreeze. You may want to check these for a few sneak preview pics:

* New icons: #4066 
* New themes: #4110 

or, if you're feeling lucky, download a snapshot version (=possibly unstable developer version) from https://snapshot.keepassxc.org.

That being said, beauty is in the eye of the beholder, and your comments are welcome.

**Comment by CerebralFreeze** [comment]
Wow, what you guys have done makes a HUGE visual improvement.  The graphics actually match up to the actual capabilities of the program.  The masses will no longer immediately dismiss this program as some amateur project by just looking at the superficial exterior and not even test-drive it.  I think it will make a real impact.  Great job.

That being said, you also said that "beauty is in the eye of the beholder, and your comments are welcome."

I genuinely believe that what you guys did looks great.  I mean it.  But, I think it could even look _better_ if you used someone with an art major.  I'm a project manager in construction and have completed more than a few projects.  I think I have decent tastes.  Ironically, _all_ contractors believe they have great tastes but literally _all_ of them have terrible tastes.  It really looks bad if you ever leave it up to them to design anything.  You shouldn't even let them pick the colors for the inside closet.  (j/k)

We rely on designers that have attended art school and it makes a world of a difference.  They actually study theory on why things look beautiful to people.  Symmetry, composition, types of colors do what, etc.  Altogether, it makes a huge difference.  That's why interior designers even exist and get paid so much.  You can get the architect to do the design as well as drawing the plans but people with money or the major large projects use dedicated designers for a reason.

So, with that said, ever think about getting _upper-class or graduated_ graphic art students give a go at re-designing the entire GUI?  They get to add something to their art portfolio and you guys get a powerhouse GUI.  You can even get multiple graphic design artists to provide multiple design proposals and you can pick which one you like best.

What do you, guys think?



> Thanks for the thumbs-up @CerebralFreeze. You may want to check these for a few sneak preview pics:
> 
> * New icons: #4066
> * New themes: #4110
> 
> or, if you're feeling lucky, download a snapshot version (=possibly unstable developer version) from https://snapshot.keepassxc.org.
> 
> That being said, beauty is in the eye of the beholder, and your comments are welcome.

**Comment by phoerious** [comment]
> I genuinely believe that what you guys did looks great. I mean it. But, I think it could even look better if you used someone with an art major. I'm a project manager in construction and have completed more than a few projects. I think I have decent tastes. Ironically, all contractors believe they have great tastes but literally all of them have terrible tastes.

I know exactly what you mean. Everybody can appreciate things that look good, but hardly anybody can create them. I am no professional designer (i.e. I didn't formally attend art school and don't earn money with it on a regular basis), but I have quite some (also theoretical) background in it. The design as it is now is a beginning. There are still a lot of things that absolutely must change. The current iteration is merely a new layer of paint, but structural changes must follow also (and new database icons).

That said, if there are designers who want to contribute, they are very welcome. The difficulty is largely, that it is easy for designers to invent a totally new UI, but it is a very different thing for us to implement it with the tools we have. Qt gives us a huge amount of flexibility in many areas, but not so much on the visual aspect, unfortunately (I suppose due to its age). Were KeePassXC based on web technologies, that would be much easier, but you wouldn't want to do that for many other reasons.

**Comment by wolframroesler** [comment]
For the record, new database icons are being worked on (#4071).

**Comment by CerebralFreeze** [comment]
Phoerious, You and I are kindred spirits.  You just said exactly what I was trying to say!

As you said, I think everyone likes to think of themselves as having great tastes.  But, it's much rarer for someone to have that "gift".  Even from the ones that come out of design school, many don't pass muster.

I said this before but I think this is a possible idea.  Announce a contest for RISDE (Rhode Island School of Design, the #1 art school in the US) and Cornell (#2) to create a totally new GUI.  Their reward will be that their GUI will be on display on hundreds of thousands of computers.  They can put it in their art portfolio that will secure them a job upon graduation.  (Getting a job is really hard in an art/graphic related field.)  While you, guys get an awesome GUI.  It's a win-win!

By the way, I do genuinely believe that the new upgrade looks great.  It's much better.  I was hoping for an entirely new interface, that's all.

> > I genuinely believe that what you guys did looks great. I mean it. But, I think it could even look better if you used someone with an art major. I'm a project manager in construction and have completed more than a few projects. I think I have decent tastes. Ironically, all contractors believe they have great tastes but literally all of them have terrible tastes.
> 
> I know exactly what you mean. Everybody can appreciate things that look good, but hardly anybody can create them. I am no professional designer (i.e. I didn't formally attend art school and don't earn money with it on a regular basis), but I have quite some (also theoretical) background in it. The design as it is now is a beginning. There are still a lot of things that absolutely must change. The current iteration is merely a new layer of paint, but structural changes must follow also (and new database icons).
> 
> That said, if there are designers who want to contribute, they are very welcome. The difficulty is largely, that it is easy for designers to invent a totally new UI, but it is a very different thing for us to implement it with the tools we have. Qt gives us a huge amount of flexibility in many areas, but not so much in the visual aspects, unfortunately (I suppose due to its age). Were KeePassXC based on web technologies, that would be much easier, but you wouldn't want to do that for many other reasons.

**Comment by phoerious** [comment]
An entirely new UI is easier said than done. I don't think the bottleneck is designing one, it's rather integrating it into our technology stack and making it work cross-platform.

**Comment by wolframroesler** [comment]
@CerebralFreeze The database icons (aka default icons) are currently being redesigned. Have a look at #4071, your feedback is highly appreciated.
