### ISSUE TITLE
KeePassXC freezes Gnome at shutdown.

### ISSUE THREAD

**Issue by FMuro** [keepassxreboot/keepassxc#461]
Gnome freezes for about half a minute when KeePassXC is open (or just in the system tray) and I try to shut down or restart. I'm running Fedora 25, and using bugzy's copr package. I reported there, but have been told to ask here.

https://github.com/bugzy/keepassxc-rpm-spec/issues/4#issuecomment-290120951

**Comment by droidmonkey** [comment]
Does this happen regularly? Do you have pending changes to be saved in the database? If KeePassXC is NOT started does the behavior go away?

**Comment by FMuro** [comment]
I address each question:

1) Always.

2) No.

3) Yes, I've just noticed this behavior with KeePassXC open, even if just in systray.

**Comment by droidmonkey** [comment]
OK, I'll spin up an instance of fedora and see if I can replicate, thanks.

**Comment by droidmonkey** [comment]
I can't replicate this unfortunately.

**Comment by FMuro** [comment]
Thanks for checking! It may be something else, then. Really strange. Let's hope I can see this behavior somewhere else, so that I can get to know what may be causing it.

**Comment by droidmonkey** [comment]
Try loading up a vm and replicating it if you can. There might be something in your gnome config or extension that is causing bad behavior.

**Comment by FMuro** [comment]
OMG, I think it was the following bug of the caffeine gnome shell extension:

https://github.com/eonpatapon/gnome-shell-extension-caffeine/issues/48

Believe me, I've only experienced it with KeePassXC open, who knows why.

Thanks a lot for having tested and helped!

**Comment by droidmonkey** [comment]
Sweet, glad you found the culprit and even happier it wasn't us, hehe.
