### ISSUE TITLE
KeepassXC 2.5.4 does not recognize hardware key on Mac (reboot does not help)

### ISSUE THREAD

**Issue by sarndt** [keepassxreboot/keepassxc#4610]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )
After upgrading from KeepassXC 2.5.3 to KeepassXC 2.5.4, the hardware key stopped being recognized.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
When I start up KeepassXC and press "Refresh" on the hardware key login option, I expect it to recognize my Hardware key.

## Current Behavior
[NOTE]: # ( Tell us what actually happens )
When I start up KeepassXC and press "Refresh" on the hardware key login option, a blue progress bar below the dropdown menue indicates an ongoing search for hardware keys for a few moments, then the operation stops with no hardware key being found. 
This behaviour is the same as if no hardware key was inserted into the Mac.

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )
No known solution from my side.
Current workaround is to drop back to version 2.5.3, as the hardware key gets recognized in that version without issue.

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1. Start KeepassXC in version 2.5.4
2. Press "Refresh" next to the hardware key login option
3. After a short time, the operation ends without the hardware key being recognized

## Context
- Hardware key is a Yubikey 5C (USB-C dongle)
- KeepassXC has been installed via homebrew cask
- Restarting the Mac does not solve the problem
- Shutting the Mac down and starting it again a bit later does not solve the problem
- Putting the key into a different USB-C port on the Mac does not solve the problem 
- The key is otherwise working fine

## Debug Info
KeePassXC - Version 2.5.4
Revision: dcca5aa

Qt 5.14.1
Debugging mode is disabled.

Operating system: macOS 10.15
CPU architecture: x86_64
Kernel: darwin 19.3.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
 libgcrypt 1.8.5

**Comment by droidmonkey** [comment]
You need to perhaps remove keepassxc from the input monitoring permission and then re-add it.

**Comment by sarndt** [comment]
Hey @droidmonkey,

Is this a new requirement? When I look at my KeepassXC 2.5.3 version it does not have the Input Monitoring permission.

Interesting to add: 2.5.3 exhibited the same behaviour after the downgrade, but a reboot fixed it for the old version, while it did not help for 2.5.4.

**Comment by droidmonkey** [comment]
This is a "fun" Mac feature with Catalina. There is nothing we can do to make it better.

**Comment by dbmarshall** [comment]
Ran into same issue after rebooting Catalina, nothing showed up for Hardware Key, the select pulldown was blank, even after refresh.

I checked Privacy System Prefs under Input Monitoring and KeepassXC had become unchecked.  I rechecked it and the app recognizes the Yubikey now.

**Comment by dbmarshall** [comment]
Ran into same issue after rebooting Catalina, nothing showed up for Hardware Key, the select pulldown was blank, even after refresh.

I checked Privacy System Prefs under Input Monitoring and KeepassXC had become unchecked. I rechecked it and the app recognizes the Yubikey now.
