### ISSUE TITLE
extend search function under "advanced"

### ISSUE THREAD

**Issue by Bondarz** [keepassxreboot/keepassxc#4611]
Hello,
for each login/account i store my email addresses cryptically.
for example: zf0q874tz0ve0hq@domain.de

if now, in case of a leak, this e-mail is stolen, i have to search for it at keePass, of course. I enter the mail entries under notes as registration mail.

Unfortunately the search function does not find these entries.
Is there a hint, or do I have to put my mail addresses under the notes to find them with the search function?

Windows 10 / KeePassXC 2.5.4

![grafik](https://user-images.githubusercontent.com/19914015/79391600-1eebf180-7f72-11ea-94ae-d90787506f34.png)

**Comment by droidmonkey** [comment]
Search for `attr:attributename`

**Comment by Bondarz** [comment]
Thanks, works :)
