### ISSUE TITLE
"Recharge" could launch the app...

### ISSUE THREAD

**Issue by ehquionest** [keepassxreboot/keepassxc#4612]
Hi team,
I am on Mac Osx... When KeePassXC is locked and not launched, it would be great when we click on the KeePassXC icone in Firefox addons and then clic on "Recharge", that this action launch the app and then we just have the master password to type...
Thanks.
Mark

**Comment by droidmonkey** [comment]
This has been discussed before

**Comment by ehquionest** [comment]
Where ?

**Comment by droidmonkey** [comment]
#3532
