### ISSUE TITLE
[PRE-RELEASE] Buttons in the Generate password

### ISSUE THREAD

**Issue by wombat01** [keepassxreboot/keepassxc#4618]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

in the generate password window, there are two buttons next to the password field, somehow I didn't understand what the next is good for.

I believe this is a cosmetic issue.

## Current Behavior
[NOTE]: # ( Tell us what actually happens )
 
![sdfsd](https://user-images.githubusercontent.com/20426629/79487371-6f1d8f00-8018-11ea-8a45-3374a0de6abb.png)

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1.
2.
3.

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION
Revision: REVISION
KeePassXC - Version 2.6.0-snapshot
Build Type: Snapshot
Revision: 5795051

Qt 5.14.2
Debugging mode is disabled.

Operating system: Windows 10 Version 1909
CPU architecture: x86_64
Kernel: winnt 10.0.18363

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.5

**Comment by phoerious** [comment]
This is fixed already, we only need to merge the branch.
