### ISSUE TITLE
Create an official fedora package

### ISSUE THREAD

**Issue by noraj1337** [keepassxreboot/keepassxc#462]
I wanted to see KeePassXC into QubeOS so I opened an issue on their [tracker](https://github.com/QubesOS/qubes-issues/issues/2717). But they use Fedora (raw) templates and told me to ask Fedora.
So I asked Fedora on [their bugtracker](https://bugzilla.redhat.com/show_bug.cgi?id=1434572) but in order to request a package you must create the package and be the maintainer.

So the better way is that you become the maintainer, not me.

**Comment by hifi** [comment]
@bugzy has https://github.com/bugzy/keepassxc-rpm-spec going and it's well maintained

I talked with the Fedora KeePassX maintainer and he said it's sort of orphaned by now (the keepassx package) so they really need a new new maintainer for KeePassXC as the current one wouldn't take on a new package.

Ideally such package needs to be co-maintained for continuity.

**Comment by hifi** [comment]
An [official](https://apps.fedoraproject.org/packages/keepassxc) package has been pushed to Fedora which was tracked as [RHBZ #1450633](https://bugzilla.redhat.com/show_bug.cgi?id=1450633).

Initial website update pending as https://github.com/keepassxreboot/keepassxreboot.github.io/pull/13

This issue can be closed as resolved.
