### ISSUE TITLE
MacOS 2.5.4 Keeps asking for permissions

### ISSUE THREAD

**Issue by parodymshifter** [keepassxreboot/keepassxc#4620]
I updated to 2.5.4 using Brew.

Since updating every time I try to use autotype I get prompted to grant keepassxc permission to control the Mac.

I enabled permission for Accessibility for KeePassXC in the Mac Settings App, closed the Keepassxc app and reopened it.  There is NO Screen Recorder entry visible in the Privacy section of  Security & Privacy in the System Preferences on my Mac.

I'm still getting prompted:

"KeePassXC requires the Accessibility and Screen Recorder permission in order to perform global Auto-Type. Screen Recording is necessary to use the window title to find entries. If you already granted permission, you may have to restart KeePassXC."

Is there something ELSE that needs to be enabled?  I don't see anywhere to enable "Screen Recorder" permission.  How does one enable that?

KeePassXC - Version 2.5.4
Revision: dcca5aa

Qt 5.14.1
Debugging mode is disabled.

Operating system: macOS Mojave (10.14)
CPU architecture: x86_64
Kernel: darwin 18.7.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
 libgcrypt 1.8.5

**Comment by droidmonkey** [comment]
Check out the pinned issues........
