### ISSUE TITLE
Linux 2.5.4: Menu entries are moved to far left and partly cut from the screen

### ISSUE THREAD

**Issue by deepfighter** [keepassxreboot/keepassxc#4621]
## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Open KeePassXC
2. Click on one of the Menu entries (Database, Entries, Groups,...) e.g. on the Login-Screen
3. See that the drop-down list, which pops up are not in place.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
The menus should be underneath their Top Menu entry. The hover explanation of the symbols should be under the symbol and not somewhere far left/right of it.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
See the [pictures here](https://imgur.com/a/2v32oGj). All menus are on the left side and partly cut of the screen. Hover explanation of the symbols are not under the symbols but far left/right from it. Furthermore they are not moving so if you hovering through the symbols with the mouse, the hover explanation stays there at the same vertical line with the changed symbol corresponding text.

## Context
[NOTE]: # ( Give us any additional information you may have. )
Nothing more, sadly I can't recall if this happened in 2.5.3 as I always went straight to typing the password and found this by accident. I haven't found the same issue other bug reports. Please tell me, if there is something else I can help with to narrow that bug down.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.5.4
Revision: dcca5aa

Qt 5.13.2
Debugging mode is disabled.

Operating system: Fedora 31 (Workstation Edition)
CPU architecture: x86_64
Kernel: linux 5.5.16-200.fc31.x86_64

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.5

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux (Fedora)
Desktop Env: Gnome 31
Windowing System: Wayland

**Comment by phoerious** [comment]
We did not change anything about the menus. This must be a Qt problem on your system.

**Comment by droidmonkey** [comment]
This was a Qt bug that has been fixed in more recent versions
