### ISSUE TITLE
Right-Click > Open URL, then righ-click menu is lost

### ISSUE THREAD

**Issue by pbgbob** [keepassxreboot/keepassxc#4625]
## Overview
I just moved to KeePassXC from KeePassX and noticed that right-click menu goes to single possible choice after selecting open URL.

## Steps to Reproduce
1. Right-click an entry then select 'Open URL' [URL opens in browser]
2. Right-click same entry and the menu is a single item 'New entry.'

## Expected Behavior
Expect right-click menu to not default to 'New entry,' as I will now like to copy the password through the right-click menu. Images attached for first right-click on entry and subsequent right-click on same entry.

## Actual Behavior
As above, right-click menu goes to single entry of 'New entry,' which is not useful for my use.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION 2.5.4
Revision: REVISION dcca5aa

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS
Desktop Env: Mojave 10.14.6

![Right-Click_01](https://user-images.githubusercontent.com/63919088/79642757-6db1ab00-816d-11ea-949d-be5c24f549e8.png)
![Right-Click_02](https://user-images.githubusercontent.com/63919088/79642762-70140500-816d-11ea-80a1-fb6b0d58ebb2.png)

**Comment by droidmonkey** [comment]
This is a Qt bug. Don't right click into the window. You have to always left click to gain focus.
