### ISSUE TITLE
Sort groups by name

### ISSUE THREAD

**Issue by rdavid2** [keepassxreboot/keepassxc#4626]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )

The groups can only be shown in the order in which you have added them, but when you have many it is difficult to find a specific one. To sort by name would be an easy solution to finding a group

Credentials can be sorted by table fields and also have search, but groups have nothing

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )

I have about 60 groups, for example one for each client, impossible to find a group easily.

I have seen other colleagues with similar listings in number, I am not the only one.

**Comment by droidmonkey** [comment]
![image](https://user-images.githubusercontent.com/2809491/79673810-f864cb00-81aa-11ea-978a-7bade3358adb.png)

**Comment by rdavid2** [comment]
Thank you very much, Ubuntu 19.10 brings version 2.4.3 and this version does not allow it.

Finally I upgraded to 2.5.4 using the ppa sources phoerious/keepassxc
