### ISSUE TITLE
Improve handling of custom icons

### ISSUE THREAD

**Issue by droidmonkey** [keepassxreboot/keepassxc#4627]
OK, I did some research. The way we handle custom icons is pretty terrible if they are multi-resolution ICO files. Here is what we are doing:

* Read: XML Data -> QByteArray -> Database::Metadata::QImage
* Display: QImage/QPixmap
* Write: Database::Metadata::QImage::Save -> XML Data

We store in our database model the processed QImage format of the ICO. This causes the first layer (16x16) to be read and displayed everywhere. Instead we should be storing the raw QByteArray data in the database model and only loading QImage/QPixmap representations for display in the GUI. The correct sequence should be:

* Read: XML Data -> QByteArray -> Database::Metadata::QByteArray
* Display: QImageReader(data) -> Choose correct resolution using QImageReader::jumpToNextImage() and QImageReader::size() -> QImage/QPixmap -> GUI
* Write: Database::Metadata::QByteArray -> XML Data

_Originally posted by @droidmonkey in https://github.com/keepassxreboot/keepassxc/issues/3232#issuecomment-500237614_

**Comment by wolframroesler** [comment]
Could be covered in #4071.

**Comment by droidmonkey** [comment]
This is about reading/writing custom icons to the kdbx format.
