### ISSUE TITLE
Add button to standalone password generator to create a new entry

### ISSUE THREAD

**Issue by serovar** [keepassxreboot/keepassxc#4629]
## Summary
Add a history of generated passwords (as 1Password and Bitwarden do, I have not tried the others).

## Context
Sometimes the browser addon fails to recognize that a new entry should be added to the database when registering to some website or changing its password, and if you did not copy the generated password, you lose access and have to recover it (a real bother sometimes).

**Comment by droidmonkey** [comment]
Already got it...

![image](https://user-images.githubusercontent.com/2809491/79692706-9badf280-8234-11ea-974c-057308098173.png)

**Comment by serovar** [comment]
No, please reopen the issue, I am referring to generated passwords that are not already added to existing entries.

The ones generated here:
![Screenshot_2020-04-19_18-05-10](https://user-images.githubusercontent.com/6732420/79692985-74711880-8268-11ea-810c-a0e3e35ece2d.png)

**Comment by droidmonkey** [comment]
That's an issue with the extension, not the desktop app.

**Comment by serovar** [comment]
It's something that happens rarely of course, but I do not think that the extension could possibly recognize every possible site login implementation. 1Password and Bitwarden devs aknowledge this possibility, and in the eventuality in which this happens, you have a generated password history, problem solved.

I do not see how it could be a security issue if this history would be encrypted inside the database.

Regarding the procedure you suggest, you don't know when the browser extension will fail, so you should do this cumbersome procedure every time you register or change your password.

**Comment by droidmonkey** [comment]
The standalone password generator is not within the confines of a database.

**Comment by serovar** [comment]
I understand your point of view, but I don't think the extension will ever be perfect in this regard, because there are almost unlimited websites and registering forms, and new ones will be created, in an everlasting cat and mouse game that will bear an inherent risk of losing your password when you register or change your password.

That said, I will report the extensions issues when they will arise again to avoid other users the same problem in the affected sites, but in my opinion if saving the generated password history within the encrypted database is technically infeasible with the present code, then the present code regarding password generation should be changed.

Just my 2 cents, thanks as always for your great work :)

**Comment by droidmonkey** [comment]
Although you bring up a good idea, from the standalone password generator we could have a button "Create Entry" that creates a new entry in the last used database with the current password. I'll reopen this issue for that feature.

**Comment by serovar** [comment]
While I appreciate the attempt to compromise (I really do), I do not think this feature would solve any problem (since at that point, it is the same of adding a new entry every time and generating the password from inside the new entry), and it would only be a waste of time for you and a redundancy for the users. Thanks anyway :)
