### ISSUE TITLE
Descriptive tooltip for the search patterns immediately vanishes when clicking the right computer icon in the search bar

### ISSUE THREAD

**Issue by systemoperator** [keepassxreboot/keepassxc#4632]
## Overview
The descriptive tooltip for the search patterns immediately vanishes when clicking the right computer icon in the search bar.

## Steps to Reproduce
1. Click the right computer icon in the search bar.
2. The tooltip immediately vanishes.

## Expected Behavior
The descriptive tooltip for the search patterns should be shown and stay visible (at least for a while).

## Actual Behavior
The descriptive tooltip for the search patterns immediately vanishes and is unreadable.

## Context
KeePassXC - Version 2.5.4 (But this problem already exists in older versions as well.)
Revision: dcca5aa

Operating System: Linux (Ubuntu 16.04)
Desktop Env: Mate
Windowing System: X11

**Comment by droidmonkey** [comment]
This is fixed already for the next version.
