### ISSUE TITLE
Minimize to TRAY for Windows

### ISSUE THREAD

**Issue by tessierp** [keepassxreboot/keepassxc#4634]
Hi,

Really like your application. There is only one thing that is very annoying about it. It would be a very welcome feature if you could implement a minimize to Windows Tray to remove the clutter from the taskbar. Please consider implementing the feature.

Thanks

**Comment by droidmonkey** [comment]
![image](https://user-images.githubusercontent.com/2809491/79813006-76120d80-8348-11ea-82d0-f9730fff87f7.png)
