### ISSUE TITLE
Keyboard handling: re-focus accounts panel after editing the account entry

### ISSUE THREAD

**Issue by etosan** [keepassxreboot/keepassxc#4635]
## Summary
When user edits the account entry with keyboard exclusively (CTRL+E), after account is saved, focus breaks severally. Some other element than accounts panel is focused, making the program unusable from keyboard.

## Examples
  * Click into account pane to focus it.
  * Pick any account with arrows.
  * Press **CTRL-E** to edit it.
  * Do the edit (**eg. actually change something!**).
  * Press **ENTER** to save account.
  * **Account details close, but account panel is unfocused**.
  * Program is unusable from the keyboard now.

**Important!** Focus handling works properly if you just **CTRL-E** (edit) account and then press **ESC** (cancel), so I guess it's some bug in focus handover only when account saving.

## Context
I use tiling window manager and keyboard extensively. CLI tools are more suited for such environment, but lot of GUI programs are plenty usable as well. I know there are CLI alternatives for this task, but many times keyboard driven GUI is most efficient worktool, especially in ad-hoc cases.

**Comment by droidmonkey** [comment]
This is already fixed in develop branch and 2.5.4.

**Comment by etosan** [comment]
Thank you!
