### ISSUE TITLE
Keyboard handling: make both panels focusable and keep last used panel focus properly

### ISSUE THREAD

**Issue by etosan** [keepassxreboot/keepassxc#4636]
## Summary
As two major workflow starting points, one can focus either Groups Panel or Accounts Panel.
Once panel is focused, keyboard can be used to work with items on the panel efficiently (even in Groups panel, by using MENU key). 

Unfortunately it is impossible to focus any of these panels straight from keyboard :(. One has to always click. What's worse focus dances around randomly.

## Examples
I suggest adding following things to the program to make it more bearable:
  * Add shortcut to focus Groups panel explicitly (for example **F2** or **CTRL +G**)
  * Add shortcut to focus Accounts panel explicitly (for example **F3** or **CTRL + A**)

This would allow user to refocus to given panel if anything goes wrong, and these shortcuts should be window global.

Then, if there is the will to implement this I suggest panel focusing //specialcase//, for handling focus when in-panel. If Groups or Accounts panel is focused, make **TAB** switch to other one.

KeepassXC GUI can be essentially seen as special case of OFM (Orthodox File Manager) where left panel is permanently Groups panel and right panel is permanently Accounts panel. In such software **TAB** key allows to quickly transition from left panel to right and back. I need to stress out that this special case should apply only to focused Groups or Accounts panel. For other UIs **TAB** key should behave like it normally does.

If //specialcasing// **TAB** (in described conditions) is a problem, **ALT+LEFT/RIGHT** key combinations could be used to switch panels instead (when in-panel of course).

## Context
I use tiling window manager and keyboard extensively. CLI tools are more suited for such environment, but lot of GUI programs are plenty usable as well. I know there are CLI alternatives for this task, but many times keyboard driven GUI is most efficient worktool, especially in ad-hoc cases.

**Comment by droidmonkey** [comment]
Qt tab key handling is severely broken (as you can see). Good idea for dedicated keyboard shortcut for focusing. I was thinking of writing a special case handling of the major MainWindow components.

**Comment by etosan** [comment]
I understand! Any keyboard friendly way to travel from one panel to anther is fine with me.

**Comment by droidmonkey** [comment]
I FIXED IT!! #4641

**Comment by etosan** [comment]
The fix is great overall, now I can cycle through all major GUI parts...

But using it during work, I am discovering, that I would still be very grateful, if I could focus Groups and Accounts explicitly, right away as well.

**Comment by droidmonkey** [comment]
OK I will add that to the PR, it is a good idea. I am in favor of the shortcut Alt + G and  Alt + E to not confuse with the shortcuts for handling entries (Ctrl + [Shift] + C/V/B/T/...). This would align also with the browser-like tab navigation of Alt + #.

**Comment by etosan** [comment]
One last thing, before this goes in, don't you think some users might have problem with F1 being "help"? I just picked F-keys because those seemed unused, but then I remembered some software binds F1 to inline help. I personally don't mind in this specific case.

**Comment by droidmonkey** [comment]
I pressed F1 in various parts of our application and it didn't do anything. I think F1 for help is a legacy holdover that is not relevant to today's use of computer software. I personally hate it when I hit F1 by accident in Word and it takes forever for the stupid pop-up help window to load.

**Comment by etosan** [comment]
Understood.
