### ISSUE TITLE
Focus indication is insufficient

### ISSUE THREAD

**Issue by etosan** [keepassxreboot/keepassxc#4637]
## Overview
When both Group and Account are focused, either by mouse or by keyboard, it is impossible to discern, which panel has focus, as both entries (Group and Account) are highlighted by selected item colour (within tree/listbox). More over it's impossible to discern if either panel has focus at all.

## Steps to Reproduce
  * Click onto any Group in Group panel, background becomes highlighted (by default blue).
  * Click onto any Account in Account panel, background becomes highlighted (by default blue).
  * Click into searchbox.
  * Step away from computer and turn around once in a room.
  * Sit back and look at KeepassXC.
  * Reply quickly (under 1 second) just by looking at GUI, which element is focused?

## Expected Behavior
Focused elements in unfocused panels should change highlight color to indicate selection, but not focus, eg. by default they should have dark gray background or something similar.

Each panel could also have small header line above it's rectangle or some other way to indicate it has focus (dark blue (focused) or gray (unfocused)).

## Actual Behavior
Nothing. All selected elements appear focused. It is impossible to tell quickly what has focus.

## Context
Daily use.

KeePassXC - 2.5.3
Revision: f8c962b

Operating System: Linux
Desktop Env: none/WM
Windowing System: X11

**Comment by droidmonkey** [comment]
I agree and it's even worse in our new theme. Ping @phoerious

**Comment by phoerious** [comment]
This cannot be fixed without making the inactive selection colour vastly different.

**Comment by droidmonkey** [comment]
I think we should make it blend into the background color, it is currently rather difficult to discern the difference. This is especially true in dark mode.

**Comment by etosan** [comment]
Thanks for looking into it! 

I remember in Windows Classic GUI (it is some time I used windows), classic color theme, the selected but unfocused item went gray (but only in some programs). Those colors used to be provided by GUI toolkit by default, not sure how things stand now with modern Qt. But I think any color other than focused one (which in my QT theme is "blue") is fine.

**Comment by phoerious** [comment]
These are custom colours, not system-provided ones. And grey isn't exactly what we are after (nor does "modern" Windows 10 look like that anymore).

**Comment by etosan** [comment]
I see. I am not on windows, and am using default Qt theme ... too lazy to check its name atm, but you know, the one with rounded buttons.
