### ISSUE TITLE
Selection window outside the main window

### ISSUE THREAD

**Issue by BugProg** [keepassxreboot/keepassxc#4638]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Install the keepass with the flatpak
2. Execute it
3. Right click on an entry
[
![Screenshot from 2020-04-21 14-47-16](https://user-images.githubusercontent.com/54059521/79867694-0733c380-83df-11ea-9891-e708bc7d3190.png)
](url)

KeePassXC - Version 2.5.4
Revision: dcca5aa
Distribution: Flatpak

Qt 5.14.2
Debugging mode is disabled.

Operating system: KDE Flatpak runtime
CPU architecture: x86_64
Kernel: linux 5.5.16-200.fc31.x86_64

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.5

**Comment by droidmonkey** [comment]
It's a Qt bug
