### ISSUE TITLE
Browser access confirmation dialog pops up on tab change

### ISSUE THREAD

**Issue by droidmonkey** [keepassxreboot/keepassxc#4639]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
This only happens while currently on a website that requires confirmation of credentials. When a new database tab is selected, the browser access confirmation dialog pops up, steals focus, and regardless of whether Allow or Deny is chosen KeePassXC minimizes.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Go to a website that requires credential access confirmation
2. Open multiple databases
3. Switch between database tabs

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Merely switching database tabs will not re-trigger a credential access confirmation. This should only happen when the user refreshes the page, clicks "Reload" in the extension popup menu, or requests credentials from the KPXC icon on the page.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Access confirmation is triggered every time.

## Context
[NOTE]: # ( Give us any additional information you may have. )
Occurs in 2.6.0-develop

**Comment by varjolintu** [comment]
Nice find!

**Comment by varjolintu** [comment]
Did you have search from all databases enabled?

**Comment by droidmonkey** [comment]
Yes I do

**Comment by varjolintu** [comment]
The problem here is that the browser extension detects the database change and requests the credentials again. I'm not sure that's something we want to prevent.

For me the access confirmation dialog stayed open when database was switched.

**Comment by droidmonkey** [comment]
If I am not interacting with the browser there is no reason for the browser service to repoll for credentials. That is a bug IMO.

The real crime in all this is that the application gets minimized when I dismiss the credential access dialog. That behavior should be removed entirely.

**Comment by varjolintu** [comment]
> If I am not interacting with the browser there is no reason for the browser service to repoll for credentials. That is a bug IMO.

This would mean user will have to refresh the page every time database is switched, and the credentials are no longer retrieved automatically. The same kind of polling happens when your database is locked and you open it.

> The real crime in all this is that the application gets minimized when I dismiss the credential access dialog. That behavior should be removed entirely.

That's awful indeed.
