### ISSUE TITLE
Browser access confirmation popup has buttons the wrong way around

### ISSUE THREAD

**Issue by simonvanderveldt** [keepassxreboot/keepassxc#4640]
## Overview
The Allow and Deny buttons are the wrong way around in the Browser Confirm Access dialog, the default affirmative action (Allow) should be (and has been until recently?) on the right.
Screenshot of current layout
![image](https://user-images.githubusercontent.com/204286/79906856-e0927e80-8418-11ea-9186-5a84e073365a.png)

## Steps to Reproduce
1. Trigger browser confirm access popup
2. Accidentally close it because you automatically clicked on the rightmost button to confirm

## Expected Behavior
- The rightmost button is Allow, left button is deny

## Context
KeePassXC - 2.5.3
Revision: f8c962b

Operating System: Linux
Desktop Env: Gnome
Windowing System: X11

**Comment by droidmonkey** [comment]
This dialog has been completely redone for the next version.
