### ISSUE TITLE
Add the ability to specify protocols/run commands on records

### ISSUE THREAD

**Issue by tunbridgep** [keepassxreboot/keepassxc#4642]
## Summary
So there is a great Keepass2 plugin called QuickConnectPlugin (https://github.com/cristianst85/QuickConnectPlugin). This is immensely useful for administrators and others who have a lot of accounts on network machines or a lot of virtual machines they want to SSH or RDP to, as it allows one to very easily login to a box from within keypass. Because KeepassXC doesn't support plugins, but has a lot integrated, I have thought up a relatively simple way of implementing similar functionality.

The user would be able to specify a list of protocols in their config file, which act as commands, using variable notation to substitute attributes. Then, in a given entry, they can specify "__protocol" as a custom attribute, and can use "Open URL" to run the command specified by that protocol, or open in the default browser if no protocol is specified.

Specifying the command in the config file rather than the entry itself makes sense because it would avoid a lot of duplication and allows keepassXC clients on different computers (and operating systems) to use whatever program they want to open entries of a certain protocol easily.

## Examples
lets say I have the following entries in my config file:

[Protocols]
ssh="ssh ${url}" //use ssh agent to log in
rdp="xfreerdp /v:${url} /d:${domain} /u:${username} /p:${password}"

Where ${<value>} represents any standard or custom attribute in keepassXC for a given entry.

Then, when I define an entry with a "__protocol" custom attribute, with the value of "rdp", the command specified by rdp will be run as a new process.

KeepassXC would display an error if the specified protocol isn't in the config file, or if a specified attribute in the command doesn't exist.

## Context
This feature would hopefully matter to anyone who is frequently signing into remote boxes and virtual machines. Especially when some of them are running windows, some are running Linux, meaning a multitude of protocols may be required. Currently, I use a collection of rdp files, but these store passwords outside of keepass and need to be synced manually if the password changes. While not designed for anything else, this could also be useful for people who want to use protocols for things like opening certain sites in specific browsers (if they have a particular corporate webpage that only works on IE6, for example).

All this said, maybe there's a more secure way of doing this in the first place, and this feature suggestion is going in the wrong direction. I'm open to suggestions there.

**Comment by hifi** [comment]
It is trivial to register custom URI protocols on Windows and Linux. You can already do this by registering, say `xfreerdp://` and point it to a batch file or shell script to start any program with custom arguments.

**Comment by droidmonkey** [comment]
Use our cli program

**Comment by tunbridgep** [comment]
> Use our cli program

Jumping into a CLI is not exactly the most convenient thing to do in this case, especially for those of us who are used to the GUI version of keepassxc (which is basically required at this point as the cli program is extremely limited). Having to jump out of the convenient application and into a cli to connect to a machine defeats the purpose and I may as well just connect manually.

> It is trivial to register custom URI protocols on Windows and Linux. You can already do this by registering, say `xfreerdp://` and point it to a batch file or shell script to start any program with custom arguments.

I don't think it would be possible to pass the username/etc from keepassxc this way

**Comment by droidmonkey** [comment]
I misunderstood your use case. You have examples of a couple cli programs (ssh and xfreerdp) so writing a simple script to encapsulate their use could with our cli would be trivial for a system admin.

Within the gui app you can simply write the URL for the entry by using the cmd:// syntax.

`cmd://ssh {username}@server.com `
