### ISSUE TITLE
KeePassXC 2.5.4 for Mac installs into a subfolder rather than overwriting version 2.5.3 

### ISSUE THREAD

**Issue by grahampugh** [keepassxreboot/keepassxc#4644]
## Overview
KeePassXC 2.5.4 for Mac installs into a subfolder rather than overwriting version 2.5.3 

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Install KeePassXC 2.5.3 on a Mac
2. Install KeePassXC 2.5.4
3. Observe that KeePassXC 2.5.3 remains in `/Applications`, and KeePassXC 2.5.4 is at `/Applications/KeePassXC/KeePassXC.app`

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
KeePassXC 2.5.4 should replace 2.5.3

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
KeePassXC 2.5.4 is at `/Applications/KeePassXC/KeePassXC.app`

## Context
[NOTE]: # ( Give us any additional information you may have. )
Tested on macOS 10.15.4

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.5.4
Revision: dcca5aa

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS

**Comment by phoerious** [comment]
KeePassXC doesn't install anything. You simply copy over the .app folder into your /Applications folder. I suspect you accidentally clicked "Keep both" instead of "Replace".

**Comment by grahampugh** [comment]
To clarify, this occurs when the application is put into a package (`.pkg`) for deployment, as the drag-and-drop method is not possible in some Mac software automated deployment solutions, such as the most commonly used one, Jamf Pro. This would therefore not affect personal users who are manually deploying software, but developers should be aware that this is only one possible method that software gets onto computers.

I've now figured out why this happens. The `CFBundleIdentifier` in the `Info.plist` of the KeePassXC app changed from `org.keepassx.keepassxc` in version 2.5.3 to `org.keepassxc.keepassxc` in version 2.5.4. 

When installing an application from a package using the `installer` command, Apple built in a check to see if the identifier is the same as the application already there. If it is the same, it overwrites the existing bundle, but if it is different, as a safety measure, instead a folder of the same name as the application is created, and the new version is placed inside, leaving the old app intact.

To reproduce, package up version 2.5.4 of KeePassXC and then install it on a Mac that already has 2.5.3 installed.

So, the moment has passed and there is nothing that the developers could do to remediate. However, I can at least encourage them pay attention to the `CFBundleIdentifier`, and hopefully not change it too often.

![Screenshot 2020-05-07 at 11 01 03](https://user-images.githubusercontent.com/5802725/81275510-1149f900-9052-11ea-9a07-29ec3febbbb4.png)

**Comment by phoerious** [comment]
The bundle identifier was changed on purpose, since the app ID changed as well and it was time to straighten things out. This is not something we are doing often, but it is something we had to do this time.

**Comment by grahampugh** [comment]
Yes, I could see that the change made sense. I just wanted to bring some consequences to your attention that your previous answer indicated that you were probably not aware of, in case somebody else reports it.
