### ISSUE TITLE
Include version number in AppImage

### ISSUE THREAD

**Issue by TheAssassin** [keepassxreboot/keepassxc#4645]
Please embed version numbers in your AppImages. Right now, every time I upgrade, a number is appended to avoid having 2+ exactly same looking entries in my app launcher:

![keepassxc](https://user-images.githubusercontent.com/4503202/80012537-bfd83080-84cd-11ea-84d3-1f16a6c6b8e1.png)

Cura for instance embeds version numbers, which makes it easy to maintain multiple versions:

![screenshot_2020-04-22_19-19-32](https://user-images.githubusercontent.com/4503202/80012851-40972c80-84ce-11ea-8f90-862a92a408a3.png)

Before generating an AppImage, just `export VERSION=...`. That will then be picked up by appimagetool, which both embeds it in the desktop file (which is picked up by AppImageLauncher etc.) and the filename, too.
linuxdeploy-plugin-appimage internally uses appimagetool, too, so it should "just work" in your `release-tool`.

**Comment by phoerious** [comment]
I am pretty sure we are doing that already, but I'll check. 😕

**Comment by TheAssassin** [comment]
```sh
> cat /tmp/.mount_KeePasm3kVWk/org.keepassxc.KeePassXC.desktop 
[Desktop Entry]
Name=KeePassXC
GenericName=Password Manager
GenericName[da]=Adgangskodehåndtering
GenericName[de]=Passwortverwaltung
GenericName[es]=Gestor de contraseñas
GenericName[fr]=Gestionnaire de mot de passe
GenericName[ru]=менеджер паролей
Comment=Community-driven port of the Windows application “KeePass Password Safe”
Comment[da]=Fællesskabsdrevet port af Windows-programmet “KeePass Password Safe”
Exec=keepassxc %f
TryExec=keepassxc
Icon=keepassxc
StartupWMClass=keepassxc
StartupNotify=true
Terminal=false
Type=Application
Version=1.0
Categories=Utility;Security;Qt;
MimeType=application/x-keepass2;
```
I don't spot `X-AppImage-Version` in there...

**Comment by phoerious** [comment]
I checked how I can solve this issue and it turns out we are indeed already exporting VERSION before building the AppImage, but AppImageTool isn't picking it up for reasons that are beyond me. Here's the relevant core: https://github.com/keepassxreboot/keepassxc/blob/develop/release-tool#L743

**Comment by TheAssassin** [comment]
Maybe because it isn't set correctly? But looking in the code, there should be some value... Mind to share the log output of appimagetool?

> appimage_name="KeePassXC-${RELEASE_NAME}-x86_64.AppImage"

That bit is unnecessary, if you set `$VERSION`, appimagetool automatically generates that name.

**Comment by phoerious** [comment]
There is a value, I checked (otherwise the file name would come out wrong as well). I know that appimagetool used to embed the version into the path, but at some point it also started embedding the Glibc version, so we decided to generate the file name ourselves. I believe that's why the lack of version information has gone unnoticed.

I tried setting VERSION at various points in the pipeline, but it doesn't make a difference. The only fix I could come up with is adding X-AppImage-Version to the desktop file myself.

**Comment by TheAssassin** [comment]
Found it. See https://github.com/AppImage/AppImageKit/blob/master/src/appimagetool.c#L716-L738. appimagetool only includes a version number in the desktop file if you don't specify a custom output filename.

This is clearly a bug. Mind to open an issue?

**Comment by TheAssassin** [comment]
Issue opened: https://github.com/AppImage/AppImageKit/issues/1054

**Comment by phoerious** [comment]
Cool, thanks!

**Comment by TheAssassin** [comment]
Fixed.

**Comment by phoerious** [comment]
Okay. We have merged the other fix where I just set the property manually and removed the VERSION envvar. It's probably not worth adding another patch just now that reverts it, but I'll keep it in mind for later.
