### ISSUE TITLE
Problem with keepassxc browser extension on QQBrowser (Chromium based)

### ISSUE THREAD

**Issue by muyun12** [keepassxreboot/keepassxc#4648]
After installing the keepassxc and enable browser integration,  generate some .json files ,content like blow:
```json
{
    "allowed_origins": [
        "chrome-extension://pdffhmdngciaglkoonimfcmckehcpafo/",
        "chrome-extension://oboonakemofpalcgghocfoadofidjkkk/"
    ],
    "description": "KeePassXC integration with native messaging support",
    "name": "org.keepassxc.keepassxc_browser",
    "path": "D:\\Program Files\\KeePassXC\\keepassxc-proxy.exe",
    "type": "stdio"
}
```
But after installing the keepassxc browser plugin, the id is 'hlkgcboejkmckpbcnebokepladlkdhdo',
this resulted in a failure to connect to KeePass.

How to solve this situation？

**Comment by droidmonkey** [comment]
Confirm that you installed the official keepassxc extension from the chrome store.

**Comment by muyun12** [comment]
I downloaded and installed from ‘https://github.com/keepassxreboot/keepassxc-browser‘  and I can not access chrome store.  Provide a method to manually enter whether it is feasible to connect the ID of KeePass, such as database setting interface.

**Comment by droidmonkey** [comment]
Just edit the json file with your own ID.

**Comment by muyun12** [comment]
It does't work.  Json file will be automatically modified after KeePassXC is restarted. I changed the source code and repackaged it to solve the problem and it work. Thanks!
I think the extension ID should support customization to deal with the problems I encounter. It is difficult for non professionals to modify the source code and package.

**Comment by droidmonkey** [comment]
We don't recommend using niche browsers. There is right control over the allowed extension id for good reason. It is an area with major security issues.

**Comment by muyun12** [comment]
OK，Thank you!
