### ISSUE TITLE
Use multiple Yubikeys with a single database

### ISSUE THREAD

**Issue by dummys** [keepassxreboot/keepassxc#465]
Hello,

I'm wondering if it's possible to use more than one yubikey with the same database ?

**Comment by droidmonkey** [comment]
At this time, no. What is the purpose for needing two yubikeys at the same time?

**Comment by dummys** [comment]
No the same time, But I get one at job and one that never leave my laptop. So I need to be able to open it with the two keys.

**Comment by droidmonkey** [comment]
Oh I see. If I am not mistaken, the database encryption key is a composite of the three items (password, key file, yubikey). In order to decrypt the database you need to provide all three or a combination of the three. You can't arbitrarily switch out one of those items with another.

**Comment by dummys** [comment]
Hmm ok. I dont know if its possible to copy challenge from one key to the other...

**Comment by phoerious** [comment]
KeePassXC uses HMAC-SHA1, nocht U2F. Therefore the secret is user-configurable. You can easily configure two different YubiKeys with the same secret.

**Comment by seatedscribe** [comment]
The only thing I can think of is the two-man rule...

https://en.m.wikipedia.org/wiki/Two-man_rule

**Comment by ei-ke** [comment]
@dummys Maybe [this manual](https://www.yubico.com/wp-content/uploads/2016/06/YubiKey_Identical_Credentials_ConfigGuide_en.pdf) is helpful for anyone who wants to have a two yubikeys with the same secret.
