### ISSUE TITLE
KeepassXC on Wayland does not have window borders

### ISSUE THREAD

**Issue by janvlug** [keepassxreboot/keepassxc#4652]
## Overview
KeepassXC does not have window borders on a fully up-to-date Fedora Linux running GNOME Wayland. On Xorg the windows are present on the same system.
I have two Fedora systems, strange enough is the window on one of them present on Wayland, on the other system not.

## Steps to Reproduce
1. Start KeepassXC on Fedora GNOME Wayland

## Expected Behavior
I expect the KeepassXC window to have borders.

## Actual Behavior
The KeepassXC window does not have borders.

## Context
Copied from a Fedora bug:
This version of the URL is better https://github.com/keepassxreboot/keepassxc/pull/2635
and in comments you can see that the code has been removed on September 2019 -> https://github.com/keepassxreboot/keepassxc/pull/3520

See these bugs for more info:
https://bugzilla.redhat.com/show_bug.cgi?id=1825630
https://github.com/keepassxreboot/keepassxc/issues/2973
https://github.com/keepassxreboot/keepassxc/issues/2006

keepassxc.x86_64                                     2.5.4-1.fc31

Operating System:
Fedora Linux 5.5.17-200.fc31.x86_64
Desktop Env: Gnome
Windowing System: Wayland

**Comment by droidmonkey** [comment]
Ummm this isn't on us

**Comment by phoerious** [comment]
That's a problem with your window manager / compositor.

**Comment by janvlug** [comment]
Starting KeePassXC this way solves this issue:
`QT_QPA_PLATFORM=xcb keepassxc`
