### ISSUE TITLE
2 wishes for the next release

### ISSUE THREAD

**Issue by bear30** [keepassxreboot/keepassxc#4653]
Hello,

first: I love this software and it work's perfect for me!

I have only 2 wishes for the next release:

1. Can you increase the maximum "lock database time" to 86400 sec

2. I use the "backup database file before saving" an i have many databases in my directory for all my clients. Now all files are double there with this "old" file suffix. Please implement a option to save this "old" backup files in a subdirectory.

Thank you and best regards from Germany
Bernd

----------------------------------------------------------

KeePassXC - Version 2.5.4
Revision: dcca5aa

Qt 5.12.4
Debugging mode is disabled.

Operating system: Ubuntu 19.10
CPU architecture: x86_64
Kernel: linux 5.3.0-46-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.4

**Comment by droidmonkey** [comment]
We will not be changing the maximum lock timeout. Your second request is already an open issue: #3279
