### ISSUE TITLE
Option to clone folder, when right clicking it

### ISSUE THREAD

**Issue by b4d** [keepassxreboot/keepassxc#4654]
## Summary
I use templates for folders, currently I need to hold ALT key and drag'n'drop the template to clone it.
It would be great if menu that opens when you right click on folder gives an option to clone it. Similar as the items.

**Comment by droidmonkey** [comment]
Interesting idea, I didn't even know you could copy a folder by holding ALT.

**Comment by droidmonkey** [comment]
Implemented in 2.7.0
