### ISSUE TITLE
provide usr/pwd to print dialog

### ISSUE THREAD

**Issue by dkwo** [keepassxreboot/keepassxc#4655]
Not sure if this is a missing feature, or just my ignorance.
On Linux, using gnome-keyring, when an application tries to print via GtkPrintUnixDialog (to a shared samba printer in my case), the user/password are provided by the keyring via libsecret (dbus).
It seems to me something similar should be possible with keepassxc: do you know how it could work?

**Comment by droidmonkey** [comment]
You will either have to use Auto-Type to type into the credentials dialog, or setup the FDO Secrets integration. KeePassXC can act as the system's keyring, but there can only be ONE keyring. See https://github.com/keepassxreboot/keepassxc/pull/2726

**Comment by dkwo** [comment]
Thank you. The second one seems what I need.

>

**Comment by dkwo** [comment]
FDO integration works well for my initial purpose.
Here's another small issue I have: I'm using Chromium on Arch linux, and I'd like it to use keepassxc (the only keyring installed) as well to store its secrets.
With the flag `--password-store=gnome` I had mixed success (mostly working, but a few times it would not unlock and behave as if no session cookies present); if instead I set it to `detect` it just saves the passwords and the cookies' encryption key as plain text in the file Login Data, so it does not detect anything.
Do you have experince with this?

**Comment by droidmonkey** [comment]
@aetf ping

**Comment by dkwo** [comment]
(I must say, most of the times it works fine with `gnome` option, as well as most of the times integration with ssh-agent works, just every now and then it happens it does not. :)

**Comment by dkwo** [comment]
I think this can be closed, as it's been working for a while with no issues.
Thanks.
