### ISSUE TITLE
Auto-Type stopped working

### ISSUE THREAD

**Issue by masterleming** [keepassxreboot/keepassxc#4656]
## Overview
For past few days I am not able to use the Ayto-Type feature and all references for it in the UI has disappeared -- there is no mention about it in the settings, there are no entries in the context menu when right clicking on any entry.

## Steps to Reproduce
1. Open settings and look for Auto-Type section
2. RMB click on an entry and look for "perform auto-type" action
3. press CTRL + SHIFT + V to perform auto-type of a selected entry
4. use Auto-Type system shortcut

## Expected Behavior
1. The settings be found
2. the context menu entries available
3. Auto-Type performed
4. Auto-Type performed

## Actual Behavior
Nothing

## About my version
KeePassXC - Version 2.5.4
Revision: dcca5aa

Qt 5.14.2
Debugging mode is disabled.

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 5.4.34-1-lts

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.5

## System
Operating System: Arch Linux LTS kernel
Desktop Env: Sway
Windowing System: Wayland

**Comment by phoerious** [comment]
Wayland is to blame. You can force KeePassXC to use XWayland by setting QT_QPA_PLATFORM=xcb on it, but it will only work with other XWayland features.

**Comment by masterleming** [comment]
Thank you, that helped!
I was fiddling with Qt setting on my PC never thinking it might break stuff.
