### ISSUE TITLE
"Key exchange was not successful." when using Brave Portable with KeepassXC Portable

### ISSUE THREAD

**Issue by gb-123-git** [keepassxreboot/keepassxc#4657]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Install Brave Portable KeepassXC-Browser Plugin
2. Install KeepassXC Portable (Unzip and check appropriate settings i.e browser integration, proxy etc)
3. Restart both

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
KeepassXC is able to work Normally

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Error : Key exchange was not successful.

## Context
[NOTE]: # ( Give us any additional information you may have. )
Added NativeMessagingHosts Key to Brave Browser registry and checked that other Registry keys are present.
Something to do with linking NativeMessagingHosts to KeypassXC

[NOTE]: # ( Paste debug info from Help → About here )

KeePassXC - Version 2.5.4
Revision: c023bf9

Qt 5.14.2
Debugging mode is disabled.

Operating system: Windows 10 Version 1909
CPU architecture: x86_64

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.5

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 10

**Comment by varjolintu** [comment]
https://github.com/keepassxreboot/keepassxc-browser/wiki/Troubleshooting-guide

**Comment by gb-123-git** [comment]
I have already gone through the Troubleshooting Guide. There is no 'Brave Section'. All other registry entries are in place.

**Comment by varjolintu** [comment]
AFAIK Brave uses Chrome's settings for registry in Windows. Or has that changed?

**Comment by gb-123-git** [comment]
I just checked again - extensions in Firefox is working perfectly but I noticed its not working in Chrome Browser either. The registry key is present.

**Comment by gb-123-git** [comment]
I tried changing the key (which was \KeePassXC\org.keepassxc.keepassxc_browser_brave.json to ..\KeePassXC\org.keepassxc.keepassxc_browser_chrome.json) but still same error

**Comment by gb-123-git** [comment]
I also tried adding : HKEY_CURRENT_USER\Software\BraveSoftware\Brave-Browser\NativeMessagingHosts\org.keepassxc.keepassxc_browser key manually but that doesnt work either.

**Comment by gb-123-git** [comment]
Console Debugging shows this :
Connecting to native messaging host org.keepassxc.keepassxc_browser
keepass.js:952 Failed to connect: Error when communicating with the native messaging host.
keepass.js:1183 Error: No content script available for this tab.
keepass.js:1065 Error 5: Cannot connect to KeePassXC. Check that browser integration is enabled in KeePassXC settings.
keepass.js:982 Connecting to native messaging host org.keepassxc.keepassxc_browser
keepass.js:952 Failed to connect: Error when communicating with the native messaging host.
keepass.js:1183 Error: No content script available for this tab.
keepass.js:1065 Error 9: Key exchange was not successful.
keepass.js:982 Connecting to native messaging host org.keepassxc.keepassxc_browser
keepass.js:952 Failed to connect: Error when communicating with the native messaging host.
keepass.js:1183 Error: No content script available for this tab.
keepass.js:1065

**Comment by varjolintu** [comment]
Did you install the extension using Chrome Web Store?

And the following registry entry exists and it's pointing to the correct file?
`HKEY_CURRENT_USER\\Software\\Google\\Chrome\\NativeMessagingHosts\\org.keepassxc.keepassxc_browser`

Also, what's the `path` variable's value in the JSON file?

**Comment by gb-123-git** [comment]
> Did you install the extension using Chrome Web Store?
Yes
> And the following registry entry exists and it's pointing to the correct file?
HKEY_CURRENT_USER\\Software\\Google\\Chrome\\NativeMessagingHosts\\org.keepassxc.keepassxc_browser
YES
> Also, what's the path variable's value in the JSON file?
E:\\Apps(Portable)\\KeePassXC\\keepassxc-proxy.exe

**Comment by gb-123-git** [comment]
I just found the problem. It is with the Directory name. Since I removed the parentheses (  ) and changed the directory name to "App_Portable" and it works. Seems like the js script is taking the part of the filename as a command.

**Comment by gb-123-git** [comment]
Btw. Thanks for your support ! I am really impressed and really appreciate the quick support extended by you.

**Comment by gb-123-git** [comment]
Do you need me to close this ticket or would you want it to stay open so that .js file can be altered to account for  ( ) or other characters if possible ?

**Comment by varjolintu** [comment]
Did the Process Monitor show any splitted strings when there was parentheses in the path? Using those in JSON should be just fine. Gotta double check that KeePassXC is not doing anything with those kind of strings, so let's keep this issue open.

**Comment by gb-123-git** [comment]
I didn't use Process Monitor. I just had a random hunch seeing the codes of keepass.js file under the debug. I agree this should not have been a problem in JSON and both Linux & Windows allow parentheses in folder names. However, I believe some problem is occurring when the path is passed to the keepass.js function. I cant figure out what though. Maybe the folder-name gets converted to string and this becomes a problem at the time of conversion ? (maybe javascript takes it as a part of function end rather than file name ?)

I can confirm though that after renaming the base folder to App_Portable instead of App(Portable), I am able to get the connection and auto-fill passwords.

**Comment by varjolintu** [comment]
Thanks for all the info! It makes much easier to catch the actual problem.

**Comment by varjolintu** [comment]
I could reproduce the issue, but I'll take a closer look at it a bit later.

**Comment by asavageiv** [comment]
I am seeing this on macOS with Brave non-portable, but I don't have any parenthesis in my path.

OS: macOS 10.14.6
KeePassXC 2.5.4 installed from brew at /Applications/KeePassXC.app
KeePassXC-Browser 1.6.3 installed from Chrome web store
Brave Version 1.8.95 Chromium: 81.0.4044.138 (Official Build) (64-bit) - Installed using installer from site. Non-portable I assume.

```
dreadnought:NativeMessagingHosts alan$ cat /Users/alan/Library/Application\ Support/BraveSoftware/Brave-Browser/NativeMessagingHosts/org.keepassxc.keepassxc_browser.json 
{
    "allowed_origins": [
        "chrome-extension://pdffhmdngciaglkoonimfcmckehcpafo/",
        "chrome-extension://oboonakemofpalcgghocfoadofidjkkk/"
    ],
    "description": "KeePassXC integration with native messaging support",
    "name": "org.keepassxc.keepassxc_browser",
    "path": "/Applications/KeePassXC.app/Contents/MacOS/keepassxc-proxy",
    "type": "stdio"
}

dreadnought:NativeMessagingHosts alan$ ls -l /Applications/KeePassXC.app/Contents/MacOS/keepassxc-proxy
-rwxr-xr-x@ 1 alan  staff  46928 Apr  9 12:55 /Applications/KeePassXC.app/Contents/MacOS/keepassxc-proxy
```

Extension background console log shows
```
Connecting to native messaging host org.keepassxc.keepassxc_browser
Failed to connect: Specified native messaging host not found.
```

Chrome works with an identical NativeMessagingHosts file. Nothing special is printed to the Browser's stdout/stderr when running it from the command line.

**Comment by asavageiv** [comment]
And now it started magically working. I have no idea what changed.
