### ISSUE TITLE
KeepassXC snap uses an ugly theme

### ISSUE THREAD

**Issue by YamashitaRen** [keepassxreboot/keepassxc#4659]
## Overview
KeePassXC arguably uses ugly icons, ugly font and ugly theme.

## Steps to Reproduce
1.  Install KeePassXC snap on Kubuntu.

## Expected Behavior
Beautiful theming : ![Keepassok](https://user-images.githubusercontent.com/4103637/80220866-c6d57f00-8644-11ea-98c9-746bf7c5dd21.jpg)

## Actual Behavior
Arguably ugly theming : ![Keepassnok](https://user-images.githubusercontent.com/4103637/80220927-d8b72200-8644-11ea-94e4-09064d379dc5.jpg)

## Context
Maybe the theming is a bit limited by snap but I am surprised that every aspects of theming but cursor are arguably ugly.

KeePassXC 2.5.4

Operating System: Linux (snap)
Desktop Env: KDE
Windowing System: X11

**Comment by droidmonkey** [comment]
Not going to be a problem when 2.6.0 is released.

**Comment by wolframroesler** [comment]
Duplicate of #475. You're perfectly right :) check out #4161 for a preview of the new icons we're getting with 2.6.0.

**Comment by YamashitaRen** [comment]
This is great news !
I will try to not look at KeePass too much in the meantime :D
