### ISSUE TITLE
Is not usable on very small screens

### ISSUE THREAD

**Issue by RasmusRendal** [keepassxreboot/keepassxc#4662]
## Overview
With the new [Pinephone](https://wiki.pine64.org/index.php/PinePhone) and [Librem 5](https://puri.sm/products/librem-5/) each having been released in beta versions, it would be helpful to have the UI on KeepassXC be responsive, and work on those devices.

I am personally using a Pinephone with Debian on it, but 

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. 
2. 
3. 

## Expected Behavior
When using KeepassXC on a mobile-sized screen, the UI should adapt in a manner so that it is useful.

## Actual Behavior
KeepassXC seems to have a minimum width that is twice the width of my phone in portrait mode. When I try to use it in landscape mode, KeepassXC is too tall. 

Version:
KeePassXC - 2.4.3
Revision: 5d6ef03

Operating System: Debian Bullseye arm64
Desktop Env: Gnome/Phosh
Windowing System: Wayland

I'm sorry I didn't attach any screenshots, but I couldn't figure out how to do it in Phosh.

**Comment by droidmonkey** [comment]
We are not going to be adopting to mobile devices.

**Comment by Razzeee** [comment]
So even "just" using libHandy is out of the question? 

(this might be a very stupid question)

**Comment by phoerious** [comment]
libhandy is a GTK library.

**Comment by Razzeee** [comment]
I did know that and searched for https://github.com/keepassxreboot/keepassxc/search?q=gtk&unscoped_q=gtk in this repo earlier today. But seems like that lead to a wrong assumption on my end, sorry. Should have looked for Qt also, sorry.

**Comment by Arnavion** [comment]
For people landing here from search engines, `gnome-passwordsafe` supports reading KeepassXC's file format and has a mobile-usable UI. The current 5.0 release doesn't support TOTP, so you have to use something else like `otpclient` for that, though `otpclient` does *not* support the KeepassXC file format so you'll have to re-import all your registrations into it. [The 6.0 release of `gnome-passwordsafe` should support TOTPs.](https://gitlab.gnome.org/World/PasswordSafe/-/merge_requests/491)

(I use `gnome-passwordsafe` to only read the kdbx file; to make changes to it I still use regular KeepassXC from a desktop and sync the file to my phone. So even if `gnome-passwordsafe` happens to have some bugs in *writing* the kdbx file that would break it with KeepassXC, it's not a problem for me.)

Edit: As Razzeee points out below, another thing missing from `gnome-passwordsafe` is a browser extension. Its UI has convenient buttons to copy the username and password so I haven't missed an extension. But it's true an extension would help prevent phishing and be more convenient in general.

**Comment by razzeee** [comment]
I think the blocker for that is going to be https://gitlab.gnome.org/World/PasswordSafe/-/issues/34 for now.

**Comment by erebion** [comment]
> We are not going to be adopting to mobile devices.

So when are you gonna make sure it stops working on my tablet, laptop and phone that all run Debian?

You know, a smaller screen is just smaller. There's no fundamental difference, some buttons might just be in the wrong location and not accessible because you cannot see those.

I don't get why a software should work one some devices that all run the some OS, but not on others, just because the screen has a different size.
