### ISSUE TITLE
KeepassXC 2.5.4 on Ubuntu 18.04 from Snap can't execute xclip

### ISSUE THREAD

**Issue by argvi** [keepassxreboot/keepassxc#4663]
## Overview
keepassxc.cli is unable to start xclip when attempting "keeppassxc.cli clip ...". was installed using apt, keepassxc is installed using snap. I believe it might have something to do with snap confinement.

## Steps to Reproduce
1. `snap install keepassxc`
2. `sudo apt install xclip`
3. `keepassxc.cli clip <kdbx_path> <entry_path> <timeout>`

## Actual Behavior
"Unable to start program xclip"

## Context
returned exit code is 1.

KeePassXC - Version 2.5.4
Revision: dcca5aa
Distribution: Snap

Qt 5.9.5
Debugging mode is disabled.

Operating system: Ubuntu Core 18
CPU architecture: x86_64
Kernel: linux 5.3.0-46-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.1

Operating System: Linux
Desktop Env: Gnome
Windowing System: X11

**Comment by droidmonkey** [comment]
We would have to install xclip into our snap.

**Comment by Toothless204** [comment]
You could make the snap a "classic" snap which removes most of the confinement allowing it to execute xclip

**Comment by droidmonkey** [comment]
That totally defeats the purpose of being a snap

**Comment by argvi** [comment]
> We would have to install xclip into our snap.

I've tested that on my machine by adding "xclip" to parts.keepassxc.stage-packages, and it did seem to insert the xclip binaries into the snap's filesystem The error message was gone, but the passwords weren't copied to the clipboard. Maybe xclip can't access the clipboard from inside a confined snap? I'd love to try debugging it on my own but I'm not very familiar with restrictions on snaps. anything I should check to pinpoint the problem?
