### ISSUE TITLE
When opening from Systemtray keepassxc window is not always shown in front of previous active window

### ISSUE THREAD

**Issue by yennor** [keepassxreboot/keepassxc#4664]
## Overview
I use minimize to system tray on exit. So keepassxc mostly is only in the system tray, but not in the task bar.
Then when I click on the icon once, keepassxc gets opened, in the sense of that it appears in the task bar and it is shown to be the currently active task. But still the window of the previous active task is shown. When I click again on the icon in the system tray, keepassxc disappears from the task bar, and when then I click once more on the icon in the system tray, it gets opened properly.
So I got used to, to always open it with 3 clicks.
It doesn't show this behavior all the time, so far I couldn't find out yet, what triggers it.
Also, when I open it, with a single click and it's window is not shown and I change to an other task and then back to keepassxc, its window is shown properly.

## Steps to Reproduce
As said above, I'm not sure how to trigger the behavior.

## Expected Behavior
The keepassxc window gets shown properly on only one click on the system tray icon

## Actual Behavior
A lot of times only the task bar entry is shown, but still the window of the previous task.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.5.4
Revision: dcca5aa

Qt 5.12.5
Debugging mode is disabled.

Operating system: Debian GNU/Linux 10 (buster)
CPU architecture: x86_64
Kernel: linux 5.4.0-4-amd64
Desktop environment: KDE Plasma

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.4

**Comment by droidmonkey** [comment]
This may be corrected already for the next version.

**Comment by yennor** [comment]
ok cool. I'll stand by and test when released :-)

**Comment by yennor** [comment]
meanwhile I'm using 2.6.0. But I'm still getting the same behaviour.

**Comment by droidmonkey** [comment]
Prefer to track this from #4970
