### ISSUE TITLE
Hide database properties until opened (i.e. last modified on, last accessed on, etc.)

### ISSUE THREAD

**Issue by pobiddy** [keepassxreboot/keepassxc#4667]
It would be helpful to keep a few "dummy" databases in the same directory as my actual ones to reduce likelihood of an actual one being selected for brute force attacks. The dummies may, at least, waste the time and resources of a potential attacker. However, since anyone is able to view the properties of each database, they can quickly determine the ones I have last accessed and modified (my working databases), thus defeating my intent of having the "dummies" (which I don't plan on accessing).
Cheers, POB

**Comment by droidmonkey** [comment]
Sorry but this is not something we will do anything about. Using default settings when creating a database coupled with a strong master password will prevent any and all brute force attacks.
