### ISSUE TITLE
Amend dialog on MacOS for granting accessibility to include system reboot

### ISSUE THREAD

**Issue by dovecode** [keepassxreboot/keepassxc#4669]
## Summary
Since MacOS Catalina, it seems you have to restart the computer for accessibility granting to take effect. I propose we add this information to the pop-up dialog.

## Examples
The following is the current dialog:
![Current dialog](https://user-images.githubusercontent.com/16987409/80387246-69c10f80-8876-11ea-82a4-cedf9706317f.png)

I propose we change the last sentence to "If you have already granted permissions, you may have to restart KeePassXC or your system."

## Context
There are several issues in the tracker documenting this. There are already several issues in the issue tracker on this particular problem. Adding this to the next update could potentially avoid more issues being opened.

The dialog already mentions the potential for having to restart KeepassXC, so adding " and/or your system" makes sense, and is very simple to add.

**Comment by phoerious** [comment]
This is a quirk that should only happen if you upgrade from 2.5.3 to 2.5.4 and goes away in the future (I hope).

**Comment by dovecode** [comment]
Well, it happens for all upgrades from 2.5.3 or earlier to 2.5.4 or later, unless Apple fixes this. The latter seems unlikely to me, given their propensity for the "well, the user just needs to get used to this" attitude.

It would seem prudent to just add it for the next minor release anyway. I'd make a pull request myself, but I can't for the life of me figure out where that dialog text is stored...

**Comment by dovecode** [comment]
Never mind. Found the translation bundle.

**Comment by phoerious** [comment]
I don't think you should update the source file, just add it to the English translation on Transifex.
The issue is connected to our application signature changes, so it's expected to happen to any upgrade from an earlier version to 2.5.4. With a bit of luck, it won't happen for any upgrade from 2.5.4 to a later version.

**Comment by dovecode** [comment]
OK. Updated in the keepassx_en.ts resource in Transifex. I didn't update the keepassx_en_2.6.ts resource. We could do that if Apple still haven't addressed that when it comes to a 2.6 release, I suppose.

Btw (possible separate issue), the prompt I got said that I needed the "Accessibility and Screen Recorder permission", but I never saw the latter. Is that an old permission that is no longer in MacOS?

**Comment by robdevops** [comment]
Thanks for doing this. I had been suffering through this for months, going through various reboots, but it does not activate unless you reboot immediately after changing it (i.e. without reopening the system preferences, I suspect). Then you have to repeat for the Screen Recording permission, as it is not an available option on the first round. Not sure if that can be improved?
