### ISSUE TITLE
Can't paste in to KeePassXC. KeePassXC's and the global clipboard only syncs one-way.

### ISSUE THREAD

**Issue by jtagcat** [keepassxreboot/keepassxc#4672]
## Overview
Can:
 - Copy from KeePassXC to KeePassXC.
 - Copy from KeePassXC to anything else (say Firefox)

Can't
 - Copy from anything else (say Firefox) to KeePassXC.

## Steps to Reproduce
1. Try to copy external content to KeePassXC.

## Expected Behaviour
Content is pasted.

## Actual Behaviour
The most recent thing you copied from KeePassXC is pasted instead.

## Context
KeePassXC - Version 2.5.4
Revision: dcca5aa

Qt 5.13.2
Debugging mode is disabled.

Operating system: Fedora 32 (Workstation Edition)
CPU architecture: x86_64
Kernel: linux 5.6.6-300.fc32.x86_64

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.5

Operating System: Fedora 32
Desktop Env: Gnome
Windowing System: Wayland

**Comment by droidmonkey** [comment]
This is a Wayland issue and been discussed before.

**Comment by lessfoobar** [comment]
is something going to be done about it or not? Main distros have moved to Wayland and this is affecting people

**Comment by droidmonkey** [comment]
We cannot do anything about it, it's not our program that is causing the problem.

**Comment by cig0** [comment]
> We cannot do anything about it, it's not our program that is causing the problem.

I'm using Wayland in my KDE and SwayWM systems, and I can copy and paste stuff in every app I have tried so far, except KeePassXC.

I'd say it is pretty much an issue with the app not properly supporting the Wayland protocol.
