### ISSUE TITLE
Shortcut to Move Between Database "Tabs"

### ISSUE THREAD

**Issue by rishanb** [keepassxreboot/keepassxc#4673]
## Summary
Similar to Google Chromes tab shortcuts, it would increase productivity if a user could switch between databases with keyboard shortcuts.

## Examples
CTRL + 1 - 1st database in tabbed list
CTRL + 2 - 2nd database in tabbed list
CTRL + TAB - Next database in tabbed list
CTRL + SHIFT + TAB - Prev database in tabbed list

## Context
Useful when working with multiple databases that may be used in different contexts.

**Comment by droidmonkey** [comment]
Already implemented for the next version
