### ISSUE TITLE
Segmentation fault on tab switch while unlocking database

### ISSUE THREAD

**Issue by spcified** [keepassxreboot/keepassxc#4674]
## Overview
Crashes when switching tabs while unlocking the database with the correct password. Won't crash if password ist wrong.

## Steps to Reproduce
Prerequisites:
  Two databases KDBX 4.0 with 1s decryption and one shrared master key.
1. Open both databases in different tabs
2. Try to unlock one database with correct password
3. While unlock is in progress ctrl + page/up/down to next tab
4. seg fault

## Expected Behavior
Either crash on correct and incorrect password, or don't crash at all and unlock database in the background

## Actual Behavior
Crash on tab switch

## Context
KeePassXC - Version 2.5.4
Revision: dcca5aa

Qt 5.14.2
Debugging mode is disabled.

Operating system: Manjaro Linux
CPU architecture: x86_64
Kernel: linux 5.6.6-1-MANJARO
Desktop Env: KDE
Windowing System: Wayland

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.5

**Comment by droidmonkey** [comment]
Fixed in develop branch
