### ISSUE TITLE
keepassxc 2.5.4 from snap is not able to connect to ssh agent

### ISSUE THREAD

**Issue by daber** [keepassxreboot/keepassxc#4678]
## Overview
Snap version on ubuntu 18.04 is not able to connect to ssh-agent if ssh agent integration is enabled.

## Steps to Reproduce

1. Install app from snap.
2. Add record with ssh-key
3. Enable ssh integration in settings.
4. Restart keepassxc

## Expected Behavior
keepassxc connect to agent  adds keys

## Actual Behavior
keepassxc displays "Agent connection failed" red popup.

## Context
This might be an issue with containers.

KeePassXC - Version 2.5.4
Revision: dcca5aa
Distribution: Snap

Qt 5.9.5
Debugging mode is disabled.

Operating system: Linux 5.3.0-7648-generic
CPU architecture: x86_64
Kernel: linux 5.3.0-7648-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.1

**Comment by droidmonkey** [comment]
Duplicate #1951
