### ISSUE TITLE
Autotype broken on linux

### ISSUE THREAD

**Issue by brokoli-mate** [keepassxreboot/keepassxc#4679]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
Autotype does not work properly on linux
OS: Ubuntu 18.04.4 LTS
kernel: linux 4.15.0-45-generic
KeepassXC version: 2.3.1 and 2.5.4
                                 

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Open website
2. Trigger auto-type hotkey or switch to the program and choose autotype from context menu
3. Chose entry
4. Look at the entry fields
## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Auto-type works 
For example: **nina**
## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Types the first latter of username and repeat it till last chracter
For example: **nnnn**

in addition: after this i connot change keyboard layout by hotkeys

**Comment by droidmonkey** [comment]
Duplicate issue. If you are using Wayland then that can cause Auto-Type to not work. If you are using Firefox there are known issues with Firefox blocking typing sometimes, use our browser extension.

**Comment by brokoli-mate** [comment]
I do not use firefox nor wayland. This happens in both chromium and brave browsers and in some other apps.

**Comment by droidmonkey** [comment]
Use our browser extension, there are lots of issues with auto-typing into browsers

**Comment by brokoli-mate** [comment]
How does it transfer entries to extension? is it safe enough?

**Comment by droidmonkey** [comment]
It is explicitly designed for security.

**Comment by brokoli-mate** [comment]
Thanks for quik replies. I'll stick with extensions
