### ISSUE TITLE
Previous databases being prefered to the program arguments

### ISSUE THREAD

**Issue by Keisial** [keepassxreboot/keepassxc#468]
The setting "Load previous databases" takes precedence over the db passed as argument when choosing the foreground database.

## Steps to Reproduce
* Ensure "Load previous databases" is checked
* Create two databases: bd1.kbdx and bd2.kbdx
* Close keepassxc with bd1.kbdx open
At this point keepassxc will automatically load bd1.kbdx at startup.

* Run "keepassxc bd2.kbdx" (or double-click bd2.kbdx if keepassxc is configured to open such files)

## Current Behavior
* bd2.kbdx is opened on the first tab, on background
* bd1.kbdx is opened on the second tab, on foreground
* keepassxc will be asking for bd1.kbdx master password

## Expected Behavior
* keepassxc should be attempting to open bd2.kbdx, which is the one the user intended to open.
* bd1.kbdx should be on background and bd2.kbdx on foreground

**Comment by louib** [comment]
@Keisial I was unable to reproduce the double-clicking behavior with Mac. What OS did you use for that use case?

Either way, #473 should fix this.

**Comment by Keisial** [comment]
I tested it on Linux. I assumed that double clicking a database, _when keepassxc is closed_ (and it is associated with kdbx files) calls “keepassxc database.kdbx”, but didn't actually check that.

I tested your patch on top of 2.1.3 and confirm that it solves the issue, also on double-click.
