### ISSUE TITLE
AppImage Version - Can't Add Custom Word List?

### ISSUE THREAD

**Issue by metal450** [keepassxreboot/keepassxc#4682]
The documentation specifies that to add your own custom word lists to the password generator, they should be added to the share/wordlists directory inside the installation directory.  On Linux, this is /usr/share/keepassxc.

However, that's not the case when running as an AppImage.  I tried creating /usr/share/keepassxc/share/wordlists to put my wordlists in there anyway, but it didn't pick them up.

Is there no way to supply custom wordlists to the AppImage version of KeePassXC?

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.5.4
Revision: dcca5aa
Distribution: AppImage

Operating System: Linux
Desktop Env: Cinnamon

**Comment by droidmonkey** [comment]
You could item the appimage as a zip file and put your custom word list inside. Otherwise you need to use the PPA repository version.

**Comment by droidmonkey** [comment]
There is already an issue requesting to allow for custom word lists loaded from the gui.

**Comment by metal450** [comment]
Gotcha. Fwiw, I couldn't find any open issues with the terms "gui word list."

Perhaps a note in the docs describing this would be helpful? It currently says:

     You can add additional word lists to the passphrase generator by copying the word list file to the share/wordlists folder inside your KeePassXC installation directory and then restarting KeePassXC. On Linux, the default install location is /usr/share/keepassxc
