### ISSUE TITLE
KeeShare import causes Browser Integration entries to change or disappear

### ISSUE THREAD

**Issue by rocketraman** [keepassxreboot/keepassxc#4684]
## Overview

I use KeeShare. I have a main database D1 with Browser Integration key A. I have a KeeShare "Import from" entry for database D2, with browser integration key B.

After an update and save of database D2, the browser integration keys in D1 are now just left with B. A has been completely deleted.

If database D2 has no browser integration keys, then upon a save of D2, the keys from database D1 are also deleted.

## Steps to Reproduce
1. Create two databases and use Keeshare "import only" mode to import the second database into the first.
2. Create Keeshare entries in the first database.
3. Modify the second database and save it.

KeePassXC - Version 2.5.4
Revision: dcca5aa

Operating System: Linux
Desktop Env: KDE
Windowing System: X11

**Comment by varjolintu** [comment]
Possible related issue: https://github.com/keepassxreboot/keepassxc/issues/4077

**Comment by rocketraman** [comment]
> Possible related issue: #4077

That's it exactly! Because I use KeeShare I actually had browser integration entries of the same name in both databases, and after the KeeShare-based merge, it seemed as if some of the entries had disappeared. But in fact, having now read through #4077, I now realize that all 3 entries in my main database were being replaced by the single entry in the imported db.

I'll close this as a duplicate and comment on #4077.

**Comment by rocketraman** [comment]
I've re-opened this issue, and modified the description to reflect the new information gleaned from #4077.
