### ISSUE TITLE
[Basic integrity check - Windows] update zip filetype verify code.

### ISSUE THREAD

**Issue by nkiki** [keepassxreboot/keepassxc#4686]
[https://keepassxc.org/verifying-signatures/  ](url)
[Basic integrity check - Windows] update zip filetype verify code.

`(Get-FileHash .\KeePassXC-*-Win64-portable.zip).Hash -eq (Get-Content .\KeePassXC-*-Win64-portable.zip.DIGEST).split(" ")[0].ToUpper()`

**Comment by droidmonkey** [comment]
What's the problem?
