### ISSUE TITLE
GPG-agent can't store passwords with libsecret integration

### ISSUE THREAD

**Issue by bionade24** [keepassxreboot/keepassxc#4689]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1.  Call gpg-agent during a GUI session, GTK window appears where you can type in the password, check save password (if even avaiable)
2. Check if password is saved now
## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Password should be stored in the keepassxc's freedesktop keyring.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
On one machine password storing option isn't available since I uninstalled gnome-keyring, on the other it  never works. 

## Addtional debug info
```
dbus-send --session --type=method_call --print-reply --dest=org.freedesktop.secrets /org/freedesktop/secrets/aliases org.freedesktop.DBus.Introspectable.Introspect

Error org.freedesktop.DBus.Error.UnknownObject: No such object path '/org/freedesktop/secrets/aliases'
```
Similar to #3955 

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.5.4
Revision: 2

[NOTE]: # ( Pick choices based on your environment )
Operating System: Arch Linux
Desktop Env: KDE
Windowing System: X11

**Comment by arnottcr** [comment]
This issue disappeared when I configured a database to expose entries under this group:
<img src="https://user-images.githubusercontent.com/1519759/53147426-8e846d80-3575-11e9-81b9-4aff85c31547.png" alt="expose entries under this group">

**Comment by bionade24** [comment]
How do you get there? I can only find the site with my exposed databases.

**Comment by arnottcr** [comment]
Use these [instructions](https://www.cogitri.dev/posts/03-keepassxc-freedesktop-secret/#setting-up-within-keepassxc). Screenshots borrowed from #2726.
