### ISSUE TITLE
ادخال الاحداثيات عند التقاط صور من تطبيق عدسه قوقول

### ISSUE THREAD

**Issue by copra7070** [keepassxreboot/keepassxc#4690]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )

**Comment by copra7070** [comment]
Thanks

**Comment by phoerious** [comment]
Please provide an adequate description of your feature suggestion. We also don't speak Arabic, so it's easier for us if you could formulate it in English.
