### ISSUE TITLE
TailsOS - Application settings do not persist

### ISSUE THREAD

**Issue by TheMeatMan** [keepassxreboot/keepassxc#4691]
## Overview
Operating System: TailsOS (bootable USB)

Using KeePassXC in TailsOS, have KeePassXC data saved to my persistent drive, but the Application settings do not persist (Global Auto-Type Shortcut, Lockout time, etc.)

## Steps to Reproduce
1. Ensure that KeePassXC is saved to persistent drive in Persistence settings.
2. Open KeePassXC in Tails with persistence enabled.
3. Set Global Auto-Type Shortcut or any other application setting; Apply, Save.
4. Shut down tails & reboot.
5. Open Tails with persistence enabled, database will be saved, but all application data is cleared. 

## Expected Behavior
Since my DB is persistent and the application KeePassXC is set to enabled on my persistent drive, I would expect application settings to persist.

## Actual Behavior
DB persists, Application Settings do not.

KeePassXC - Version 2.3.4
Revision: 6fe821c

Libraries:
- Qt 5.11.3
- libgcrypt 1.8.4

Operating system: Linux 5.4.0-4-amd64
CPU architecture: x86_64
Kernel: linux 5.4.0-4-amd64

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by phoerious** [comment]
Please report your issue to Tails. We cannot help you with distribution-specific bugs.
