### ISSUE TITLE
Simpler Storage of Files

### ISSUE THREAD

**Issue by campfireman** [keepassxreboot/keepassxc#4693]
First of all: THANK for the great app. It worked like a charm for me on Linux for one year now.

I have large files containing environment variables for the deplyment of webservices. I would love to store these more easily in keepassxc.

The single line password field gets very messy for large multi-line files.

**Comment by phoerious** [comment]
You can add any number of additional fields when you click the advanced tab.

**Comment by campfireman** [comment]
Well that is utter incompentence on my side, thank you very much for the quick reply!
