### ISSUE TITLE
Support multiple URLs for DB entry

### ISSUE THREAD

**Issue by DShirk** [keepassxreboot/keepassxc#4698]
## Summary
Allow many URLs to one database entry so browser plugin works for all listed URLs. This is useful when landing page is different URL than exit page that allows user to log back in, or when web based application has multiple services that that allow login for different purposes but are all related and have single login. This functionality is in FireFox Kee plugin that works with Keepass2 and was very helpful.  Note, this is still only one password for the site, it just supports sites that have multiple URL access.

## Examples
The following are examples where this is useful:

- Bank has username and password on different pages, but they also have different urls. Login first page takes username at https://www.bank.com/... and second page taking password is at different URL https://www.online.bank.com/...

- Initial login page for site is different URL than landing page after logging out when that page also lets user log back in (in case it logged user out for inactivity). 

- SaS site with multiple services login pages, but universal username password for all services. These sites work fine no matter where your initial login occurred, but in KeepassXC user must clone for each of service's login pages if user wants to be able to start with that service.

## Context
I have about a dozen sites where this was used in my Keepass2 with Kee plugin to Firefox. I am moving to KeepassXC but am having to create cloned entries with the additional urls. UI would need ability to delimit URLs in current field or a screen to list additional URLs. Plugin would need ability to validate multiple URLs from each database entry.

Presumably, the result would be that the properties for the Plugin Data would have multiple URLs in the "Allow" section. E.g. 
Key: KeePassXC-Browser Settings 
Value: {"Allow":["www.bank.com", "www.online.bank.com"],"Deny":[], "Realm":""}

**Comment by droidmonkey** [comment]
Already a feature, check out the browser integration tab when editing an entry. Version 2.5+
