### ISSUE TITLE
No warning when closing with unaccepted generated password

### ISSUE THREAD

**Issue by JustMyGithub** [keepassxreboot/keepassxc#4700]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Open PW Generator within an entry (new or existing)
2. Close the application (X or Ctrl+F4)
3. App closes without any warning, that the generated password is not stored

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
A warning - you might accidentally lose an important Passwort that you just generated

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
No warning

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.5.4
Revision: c023bf9

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 10

**Comment by droidmonkey** [comment]
Thus won't be problem in the next version, the password generator is now in a modal dialog.
