### ISSUE TITLE
ssh-agent integration on kubuntu20.04

### ISSUE THREAD

**Issue by jweismann** [keepassxreboot/keepassxc#4701]
## Overview
ssh-agent integration issue on kubuntu 20.04 with snap-store install of keepassxc and
official kubuntu openssh agent. 

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
Install vanilla kubuntu20.04, install kubuntu package. openssh-client and finally install keepassxc from snap-store.
Add an ssh-key entry and within the ssh-dialog choose your external file (the type of key that I tried was: ed25519) . 
Press add to agent.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Expectation is that it would be added as it is done when one does a manual ssh-add on the CLI. Moreover, expectation is that the ssh-integration in keypassxc would work as it has done in the past, e.g. on kubuntu 18.04,  cf. below.

## Actual Behavior
When I press the 'Add to agent' it complains with 'Agent connection failed' and I can confirm with 'ssh-add -l' that key hasn't been loader.

## Context
Using strace I noticed that the key file is indeed opened (which matches expectation since it shows 
additional key information like fingerprint, public key and comment on the GUI.
It has worked fine in the past, e.g. just re-confirmed that it worked fine with keepassxc 2.3.1 (kubuntu 18.04). 

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.5.4
Revision: dcca5aa
Distribution: Snap

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux - kubuntu 20.04
Desktop Env: KDE plasma
Windowing System: X11

Openssh agent from: openssh-client 1:8.2p1-4

**Comment by droidmonkey** [comment]
Please search, ssh agent and the snap build are incompatible.
