### ISSUE TITLE
Snap version: closes after inactivity even though check-box for that is not checked

### ISSUE THREAD

**Issue by BillDietrich** [keepassxreboot/keepassxc#4702]
Database closes after inactivity even though check-box for that is not checked.

I'm using Ubuntu 20.04 desktop GNOME.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.5.4
Revision: dcca5aa
Distribution: Snap

Qt 5.9.5
Debugging mode is disabled.

Operating system: Ubuntu Core 18
CPU architecture: x86_64
Kernel: linux 5.4.0-29-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.1

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows/Linux/macOS
Desktop Env: Gnome/KDE/XFCE/Mate/Cinnamon
Windowing System: X11/Wayland

**Comment by droidmonkey** [comment]
Cannot replicate at all.
