### ISSUE TITLE
"Max. history items" setting keeps oldest history items not newest.

### ISSUE THREAD

**Issue by cyphar** [keepassxreboot/keepassxc#4703]
## Overview
If you specify a value for "max. history items" in a database's settings, rather than retaining the **latest** N entries, it will simply keep the **oldest** N entries. This is quite counter-intuitive, and means that the only history which you can access is very old (and useless).

## Steps to Reproduce
1. Set the database's "max. history items" to a small number (say, `3`).
2. Change the password for an entry more than `3` times.
3. Note that the history only shows you the first three modifications, rather than the last three.

## Expected Behavior
The last `N` entries should be shown in the history.

## Actual Behavior
The oldest `N` entries are shown in the history.

## Context
```
KeePassXC - Version 2.5.4
Revision: dcca5aa

Qt 5.14.1
Debugging mode is disabled.

Operating system: openSUSE Tumbleweed
CPU architecture: x86_64
Kernel: linux 5.6.4-1-default

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.5

Operating System: Linux
Desktop Env: i3
Windowing System: X11
```

**Comment by droidmonkey** [comment]
I couldn't replicate that behavior on my sample database. I opened a random entry that had 4 history items. I changed the database settings to only allow 2 history items. Reopening that entry showed it had the most recent 2 history items remaining.

**Comment by droidmonkey** [comment]
![image](https://user-images.githubusercontent.com/2809491/81174658-3a925880-8f70-11ea-8659-1c001a60831a.png)

![image](https://user-images.githubusercontent.com/2809491/81174660-3cf4b280-8f70-11ea-9ae4-a9f61f637812.png)

![image](https://user-images.githubusercontent.com/2809491/81174666-3ebe7600-8f70-11ea-9bf3-757505660744.png)

**Comment by cyphar** [comment]
Sorry, this looks like it was fixed already (I should've tried to reproduce the issue on the latest version before posting a bug) -- I managed to have this issue when I changed a password on an a machine with an old KeePassXC and then copied the database to a machine with a newer KeePassXC. I guess it's just that the old KeePassXC had this issue.

Sorry about that.
