### ISSUE TITLE
save and reuse autotype window title patterns

### ISSUE THREAD

**Issue by ezzra** [keepassxreboot/keepassxc#4704]
for several website I use multiple accounts and for each of them I have set the window title in autotype. Sometimes websites change their title, then I have to change it for every saved password too. I don't know if this is a very special use case, but I would like to be able to select from a list of pre configured patterns that can be changed in one place.

Maybe thats a more general approach, that there might be multiple accounts for the same tool/website/etc. and they all share the same autotype pattern, url, etc.

**Comment by droidmonkey** [comment]
That is why we have a browser extension. Also you can use asterisks in the Auto-Type association
