### ISSUE TITLE
Feature request : delete priviouly opened database entry’s

### ISSUE THREAD

**Issue by F3000** [keepassxreboot/keepassxc#4710]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )

When KeepassXC starts it display a list with the last opened databases . 

The idea is to right click on one entry to delete the information. 

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )

Background : sometimes network locations changes where my database is saved and I want to clean the interface of old entry’s .

**Comment by phoerious** [comment]
You can click Database/Recent databases/Clear history.
