### ISSUE TITLE
screen lock (slock) does not lock database

### ISSUE THREAD

**Issue by dkwo** [keepassxreboot/keepassxc#4712]
I use suckless slock to lock my screen:
1. if I suspend and lock, then the database is correctly locked.
2. if instead I just lock screen with slock (e.g. when laptop is docked), then database is not locked.

Is it possible to correct this behavior?

Desktop Env: dwm
Windowing System: X11
KeePassXC - Version 2.5.4
Revision: dcca5aa

Qt 5.14.2
Debugging mode is disabled.

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 5.6.10-arch1-1

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.5

**Comment by droidmonkey** [comment]
Are you using i3?

**Comment by droidmonkey** [comment]
Sounds like slock is not sending the standard FreeDesktop.org signals that a lock event occurred. Please open an issue with them.

**Comment by dkwo** [comment]
I'm using dwm.
Ok, I will do that.
Thanks.

>

**Comment by droidmonkey** [comment]
Related to what needed to happen to correct #3339

**Comment by dkwo** [comment]
I have been informed that slock currently has no dbus support.
The suggestion was to try and wrap it by something like

```
dbus-send --dest=org.freedesktop.secrets /org/freedesktop/secrets
org.freedesktop.Secret.Service.Lock
array:objpath:"/org/freedesktop/secrets/collection/default"
```

which works for gnome-keyring.
Do you happen to know how to modify it, to make it work with keepassxc?

**Comment by droidmonkey** [comment]
Send the standard dbus screen lock message from freedesktop.orh

**Comment by dkwo** [comment]
Do you know what that is?

>

**Comment by dkwo** [comment]
Actually, it is described in your wiki, if only the command were written correctly, see https://github.com/keepassxreboot/keepassxc/issues/2764#issuecomment-495713251
Is there a way to use dbus-send instead of qdbus?

**Comment by dkwo** [comment]
Nevermind, I found that
`dbus-send --type=method_call --dest=org.keepassxc.KeePassXC.MainWindow /keepassxc org.keepassxc.MainWindow.lockAllDatabases`
does the job.
Thanks.

**Comment by droidmonkey** [comment]
No I meant this one:

https://github.com/keepassxreboot/keepassxc/blob/3dc8b7a5d0ed8ea2cad2ef09f6802a755e22ac88/src/core/ScreenLockListenerDBus.cpp#L33-L36
