### ISSUE TITLE
Window/font mismatch on reopen after minimize post sleep

### ISSUE THREAD

**Issue by dlapine** [keepassxreboot/keepassxc#4713]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
After some screen changes, un-minimizing the app causes it to show the normal window frame, but with the 3 internal areas only occupying 1/4 of that frame, and not functional. 

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Not sure on this. Doesn't do it all the time,
2. 
3. 

## Expected Behavior
The window should restore to same size and position and be usable with the standard 3 frames for folders, keys and details. Or, if reset for security, should offer a Unlock KeePassXC Database prompt to last access db within the windows frame

## Actual Behavior
The window opens in old the old position but the 3 frames are shrunk and only occupty  1/4 of the windows frame. Clicking on anything either does nothing or generates spurious menus.

## Context
Running dual montors, one with 4k and with 2K (1440) Frequently drag the app from one to the other. frequently sleep the OS or power off one of more monitors

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.5.4
Revision: c023bf9

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 10 Pro
Desktop Env: Windows standard (no mods)
Windowing System: Windows standard (no mods)

**Comment by dlapine** [comment]
doing a sleep and relogin on windows showed expected behavior( back to functional unlock screen) so I suspect that it's either monitor power off or movement between windows.
Note this behavior was not present in 2.4.3 on the same set up

**Comment by droidmonkey** [comment]
Please test a development snapshot: https://snapshot.keepassxc.org

**Comment by dlapine** [comment]
sure I will test that today. H
<img width="1920" alt="KeePassXC-2 5 4 size issue" src="https://user-images.githubusercontent.com/11180010/81570152-d1db1f80-9365-11ea-9e8d-eea01cda7ed6.png">
<img width="1920" alt="KeePassXC-2 5 4 size issue-when unlocked" src="https://user-images.githubusercontent.com/11180010/81570183-dbfd1e00-9365-11ea-8985-11822f7777df.png">

ere are 2 screen shots of the behavior

**Comment by dlapine** [comment]
The first is the initial attempt to start and the second is the expanded window of the app itself

**Comment by droidmonkey** [comment]
That's not a snapshot build

**Comment by dlapine** [comment]
Sorry, yes that was the 2.5.4 build, but the first chance I had to screen capture a failure- as I said, it's sporadic. 

Here's me running a snapshot build and getting the same effect
<img width="1920" alt="KeePassXC-2 6 0beta size issue-when unlocked" src="https://user-images.githubusercontent.com/11180010/81880038-fd226200-9551-11ea-941d-b59e65dd05a4.png">

**Comment by dlapine** [comment]
That was today, and it's the same issue between versions. As it's only happened once in the last two, can't say if more or less often. 

Please let me know if you need information.

**Comment by droidmonkey** [comment]
This seems like something unique to your computer.

**Comment by dlapine** [comment]
um, AMD 12C, running windows 10 Pro, radeon RX5700 running Radeon 20.4.2 on X570 MB. 
1 LG 4k monitor and 1 2k Asus monitor, both on the same video card. 
It's high-ish end, but nothing unique about it. 
This was never issue with KeepassXC 2.4.3 or earlier, and I was running for at least a month with the previous version before updating to 2.5.4. 
Was the Qt version updated in the windows packages in these later builds from the 2.4.x series?

**Comment by droidmonkey** [comment]
Yes

**Comment by dlapine** [comment]
Is there a dev branch of 2.5.4 or 2.6 using the older QT- I could run that and verify that the bug is in QT?

**Comment by droidmonkey** [comment]
If you want to use an older Qt you'll have to compile the code on your own, unfortunately.

**Comment by SimonChelkowski** [comment]
Hi all,

I have just reported a similar issue (font scaling changes after relaunch of KeePassXC) under #3916. There you can find screenshots showing the issue.

Best regards,
Simon
