### ISSUE TITLE
  When Esc key is pressed the current entry edition shall not be discarded without warning and confirmation.

### ISSUE THREAD

**Issue by bikepunk** [keepassxreboot/keepassxc#4716]
## Overview
While editing an entry, when Esc key is pressed, the entry window is closed and the current edition is discarded :'-(

The current entry edition shall not be discarded without warning and confirmation.

As a Vim user, I regularly press Esc key and this behavior is going on my nerves 

## Steps to Reproduce
1. edit or create an entry
2. press Esc key
3. your edition is lost :'-(

## Expected Behavior
Or Esc key do nothing
Or at least give a popup asking if you want to discard or save your current edition

## Context
[NOTE]: # ( Give us any additional information you may have. )

KeePassXC - Version 2.3.4
Revision: 6fe821c

Libraries:
- Qt 5.11.3
- libgcrypt 1.8.4

Operating system: Debian GNU/Linux 10 (buster)
CPU architecture: x86_64
Kernel: linux 4.19.0-8-amd64

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by droidmonkey** [comment]
Upgrade to the latest version
