### ISSUE TITLE
Segfault when clicking edit/unlock database settings in libsecret settings

### ISSUE THREAD

**Issue by Frederick888** [keepassxreboot/keepassxc#4718]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
Segfault when clicking edit/unlock database settings in libsecret settings

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Open Settings -> Secret Service Integration
2. Tick 'Enable KeepassXC Freedesktop.org Secret Service integration' (by the way typo here, should be KeePassXC with a capital letter P)
3. Click Edit database settings or Lock and then Unlock

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Not sure, just trying it out for the first time, guess it should open the settings of the selected database?

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Segmentation fault

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.5.4
Revision: dcca5aa

Qt 5.14.2
Debugging mode is disabled.

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 5.6.11-zen1-1-zen

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.5

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: KDE
Windowing System: X11

**Comment by ahorn42** [comment]
This might be related to #3945 ... I had the same behaviour here, but when terminating other services it worked for me. Also if you only click at the "OK" button you will get an errormessage instead of a crash.

**Comment by droidmonkey** [comment]
I believe this was fixed in develop branch already. Features were added to show you the current running libsecret process.

**Comment by Frederick888** [comment]
Are there a series of commits that I can directly apply onto 2.5.4 to test it out? If not I'm happy to wait for 2.5.5 and get back to you guys.

**Comment by droidmonkey** [comment]
You can test our development snapshot at https://snapshot.keepassxc.org

**Comment by Frederick888** [comment]
Yes I can confirm there's no segfault anymore. It didn't show 'the current running libsecret process' tho (I'm using KWallet) and I was actually able to enable libsecret integration in KeePassXC.
