### ISSUE TITLE
Support for Windows arm64 platform

### ISSUE THREAD

**Issue by mirogl** [keepassxreboot/keepassxc#4719]
## Summary
Hi,
are there any plans to release an Windows arm64 version of KeepassXC ? I tried to find an information, how to compile it myself for Windows arm64, but the standard build uses MSYS2, which has no Windows arm64 support -
https://github.com/msys2/MSYS2-packages/issues/1888
So other possibility to compile this for Windows arm64 or official support ?
Many Thanks

**Comment by droidmonkey** [comment]
No we will not because of the msys2 problem.

**Comment by hifi** [comment]
It's probably no use to you but ARM64/AArch64 is well supported on Linux and BSDs and KeePassXC runs just fine on those.

**Comment by Jihadist** [comment]
You need to compile Qt for win ARM64 and then you can compile keepass for arm64. Forget about msys2

**Comment by droidmonkey** [comment]
We use many more libraries than just Qt...

**Comment by mirogl** [comment]
Thanks for the feedback. I'm now using KeeWeb, which now supports Windows win64.

**Comment by droidmonkey** [comment]
Ummm we support win64

**Comment by mirogl** [comment]
> Ummm we support win64

sorry - had a typo - should be Windows arm64 - i corrected it in my post.
