### ISSUE TITLE
Database created on Mac cannot be openend by Linux keepassxc or keepass2android.

### ISSUE THREAD

**Issue by rickvek** [keepassxreboot/keepassxc#4721]
## Overview

[NOTE]: # 
Made a keepasscx database on Mac, cannot open it with keepass2android, Invalid composite key. Tried to open it with linux keepasscx, same cannot open it but different error (description):

All versions are as the latest versions available of today ( fresh installations, 10-05-2020) .
Test database attached
[Passwords.zip](https://github.com/keepassxreboot/keepassxc/files/4606576/Passwords.zip)

Password of database = "LetMeIn"

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. create keepassxc database on Mac with only a password
2. copy the file to android.  open database with keepass2android.
3. copy the file to linux. Open database with keepassxc 

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
database to be openend

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Linux 
**Error while reading the database: Invalid credentials were provided, please try again.
If this reoccurs, then your database file may be corrupt. (HMAC mismatch)**

Android 
 **Invalid composite key**

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.5.4
Revision: dcca5aa
Distribution: Flatpak
Qt 5.14.2
Debugging mode is disabled.
Operating system: KDE Flatpak runtime
CPU architecture: x86_64
Kernel: linux 5.6.7-300.fc32.x86_64
Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
Cryptographic libraries:
 libgcrypt 1.8.5

Android  version 1.07b-r0

Mac 
KeePassXC - Version 2.5.4
Revision: dcca5aa
Qt 5.14.1
Debugging mode is disabled.
Operating system: macOS 10.15
CPU architecture: x86_64
Kernel: darwin 19.0.0
Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- TouchID
Cryptographic libraries:
libgcrypt 1.8.5

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux/macOS
Desktop Env: Gnome/Cinnamon
Windowing System: Wayland

**Comment by droidmonkey** [comment]
Are you sure you have the password correct?
