### ISSUE TITLE
Promote KeePassXC for inclusion in PatchMyPC

### ISSUE THREAD

**Issue by keunes** [keepassxreboot/keepassxc#4722]
## Summary
[TIP]:  Promote KeePassXC for inclusion in PatchMyPC. I'm doing my bit via this issue, might be good to promote it on other channels (e.g. via a Tweet) as well.

[NOTE]: PatchMyPC is a programme that enables users to update all applications on their PC in one go. They have a list with potential apps for inclusion, and KeePassaXC is on that list. Users can vite on that list, which would peioritise their work presumably.

## Context
[NOTE]: I would like to use KeePassXC on my parents' & partner's devices - maintenance would be much easier if KeePassXC were supported in PatchMyPC. Also, at my work this software is used to keep my device up to date. Now I need to ask the support every time to update my installation, would be nice if that wouldn't be necessary any-more. (Also, for context, I suggested office-wide introduction of KeePassXC. Not being in the PatchMyPC list was apparently a blocker. Wondering if the same would be true for any other organisations using this or similar software to keep devices up to date.)

**Comment by droidmonkey** [comment]
We're already on their suggestion list https://ideas.patchmypc.com/ideas/PATCHMYPC-I-544

**Comment by keunes** [comment]
@droidmonkey I know it's on the list - sorry if I diddn't note it clearly enough in my comment. This issue is about doing some _promotion_ of KeePassXC being on that list. Being on the list itself doesn't do much, receiving votes hopefully does.

I can also understand if you don't want to do it, then please do tell. Please also let me know if I should use a different channel to request this.

**Comment by droidmonkey** [comment]
Please use social media outlets if you want to publicize this inclusion. We do not endorse third party vendors distributing our binaries, but we can't prevent it either. We ALWAYS recommend obtaining our installers from the GitHub releases.
