### ISSUE TITLE
Resolution and scaling do not work properly

### ISSUE THREAD

**Issue by BoltCitizen** [keepassxreboot/keepassxc#4723]
## Overview
On tablet at 200% scaling and 2736x1824 resolution, KeePassXC text is unreadably tiny. If the tablet is connected to an external monitor at 100% scaling and 1680x1050 resolution, all is fine. Closing and re-starting the application does nothing

## Steps to Reproduce
1. Run KeePassXC on tablet/laptop with Windows 10 at 200% scaling and 2736x1824 resolution
2. Connect external monitor and display only on this monitor at 100% scaling and 1680x1050 resolution

## Expected Behavior
Same scaling behavior as other programs, thus well readable text. On KeePass 2 this works fine

## Actual Behavior
Text is tiny, unreadable

## Context
KeePassXC - Version 2.5.4
Revision: c023bf9

Qt 5.14.2
Debugging mode is disabled.

Operating system: Windows 10 Version 1909
CPU architecture: x86_64
Kernel: winnt 10.0.18363

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.5

Operating System: Windows 10 Home 64-bit
Desktop Env: Surface Pro 6

**Comment by droidmonkey** [comment]
You are going to need to define custom scaling parameters for each of your monitors. This is a Qt problem and not KeePassXC.

https://doc.qt.io/qt-5/highdpi.html#high-dpi-support-in-qt

Specifically `QT_SCREEN_SCALE_FACTORS [list]`.

**Comment by BoltCitizen** [comment]
I am sorry, I don't understand the answer. Is this something you are working on to improve in the future?

**Comment by droidmonkey** [comment]
The size of the text and user interface is largely controlled by the Qt framework, not this project. Sometimes Qt cannot properly detect monitor DPI and behaves poorly. Follow the instructions above to correct the issue.

**Comment by BoltCitizen** [comment]
Thank you
