### ISSUE TITLE
fehlerhaft

### ISSUE THREAD

**Issue by maki13121** [keepassxreboot/keepassxc#4727]
kann es sein dass die neue datei für mac https://keepassxc.org/download/ fehlerhaft ist? ich kann leider nichts installieren, weil das zumindest mein mac sagt ;)

und jetzt hat es doch funktioniert aber beim öffnen sagt er es ist malware und will sofort wieder die app löschen?

ist das normal?

## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. 
2. 
3. 

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows/Linux/macOS
Desktop Env: Gnome/KDE/XFCE/Mate/Cinnamon
Windowing System: X11/Wayland

**Comment by droidmonkey** [comment]
That is just Mac being ridiculous. You can absolutely ignore that

**Comment by maki13121** [comment]
thanks!

Taubstummengasse 5/3/32
1040 Wien
+43/664/148 69 69
mk@eventbox.cc

Please consider environment before printing this mail.
