### ISSUE TITLE
Segmentation fault when switching databases while unlocking one

### ISSUE THREAD

**Issue by annervisser** [keepassxreboot/keepassxc#4731]
## Overview
When switching to a different database with Ctrl + Tab during the unlock of a database (after entering the password en pressing entire, there is a brief decryption time) the application crashes with a segfault

## Steps to Reproduce
1. Open two keepass databases
2. Re-start keepass
3. Enter password for one database
4. Press enter for unlock database
5. While the database is unlocking press Ctrl + Tab to switch to the other database (higher decryption time makes this easier to reproduce)
6. Keepass crashes

## Expected Behavior
No segfault. Database should continue decrypting in background after switching, or switching should be disabled.

## Actual Behavior

Application closes and stdout shows Segmentation fault

## Context
KeePassXC - Version 2.5.4
Revision: dcca5aa
Distribution: Snap

Qt 5.9.5
Debugging mode is disabled.

Operating system: Ubuntu Core 18
CPU architecture: x86_64
Kernel: linux 4.15.0-99-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.1

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux (Ubuntu 18.04)
Desktop Env: Gnome
Windowing System: X11

**Comment by droidmonkey** [comment]
Fixed in develop
