### ISSUE TITLE
Workflow improvement suggestion: alt+ mnemonics shortcuts through the password generator

### ISSUE THREAD

**Issue by elig0n** [keepassxreboot/keepassxc#4732]
## Summary
Is there a chance to add Alt+mnemonic keyboard shortcut keys for the password generator in the `Add entry` window ? Specifically for the `Regenerate`, `Copy` and `Accept` buttons.

## Description
When I add a new entry I usually use the tab key to move from one input field to another.
When I reach the `Password:` field and I want to use the password generator I can still hit Tab twice to reach the password generator toggle button and then hit Space to toggle it but getting from there to buttons like Regenerate/Copy/Accept takes at least 9 more Tab hits, or altogether raising my hands from the keyboard and having to use the mouse, only to then Alt+Tab back to a registration form, Ctrl+V, and then get back Accept, and perhaps fill more fields.

## Examples
Those can be implemented something like Alt+R for `Regenerate`, Alt+C for `Copy`, Alt+A for `Accept`

## Context
I usually employ a keyboard-centric workflow, and already the keyboard is being mostly used when adding an entry.

**Comment by droidmonkey** [comment]
Already done in develop branch. Ctrl+C copies generated password, Ctrl+R regenerates password, Enter accepts password, Esc rejects password.
