### ISSUE TITLE
KeePassXC Installation Folder

### ISSUE THREAD

**Issue by Gram95** [keepassxreboot/keepassxc#4736]
Please be gentle - I am a mere user looking for advice.
MacBook, MacOS Catalina 10.15.4.
I downloaded KeePassXC 2.5.4 and it installed itself into my Canon Utilities folder.
Am I able to change this location to my Application folder?
Sorry if it's just a basic question.
Thanks.

**Comment by phoerious** [comment]
I don't think it installed itself to anywhere. The DMG is just a disk image with the application bundle inside. You can copy or move it anywhere you want.

**Comment by Gram95** [comment]
Thanks, phoerious.
I dragged the DMG to my Applications folder, as required by the helper/installer (not sure what it is called), but the application ended up in my Applications/Canon Utilities folder.
I have subsequently tried to move it within Finder but it simply puts an alias in the destination folder.  The KeePassXC application staying firmly in the Canon Utilities folder.

**Comment by phoerious** [comment]
Make sure you have the required permissions. There is really no connection between KeePassXC and Canon.

**Comment by Gram95** [comment]
I have the necessary permissions, Jane, and I understand that there is no connection to Canon.
It's just a bit weird that it will not install, or move to, the Applications folder.
Perhaps I'll try uninstalling the application then re-installing it - what do you think?
G

**Comment by Gram95** [comment]
Sorted, thank you.
Application uninstalled, downloaded again and re-installed.
Now in its rightful place!
Keep safe.

G
