### ISSUE TITLE
MacOS: Copy+Paste into Apple Mail app not working (nothing gets pasted)

### ISSUE THREAD

**Issue by Tormen** [keepassxreboot/keepassxc#4737]
## Overview
When copying a text selection from the description-textbox of an entry within keepassxc and pasting into the mail body textbox of a new email within Apple Mail nothing happens.

## Steps to Reproduce
1. Open keepassxc and unlock it.
2. Hide it (CMD+H).
3. Open Mail and start writing a new Mail (CMD+N), write something in the mail textbox.
4. Activate keepassxc window, search for an entry (must have a description text), open it. select a part of the description.
5. Right click on the selected text, chose "copy"   (/OR/ use CMD+C)
6. Activate Mail app and the mail window you were writing and chose "Edit" Menu, "Paste" (/or/ CMD+V)

## Expected Behavior
The step 6.) should paste the selected text into the Mail.

## Actual Behavior
But instead nothing happens! If I now start the TextEdit app which opens with a new text document window and press CMD+V (or Edit "paste") it works. And when I copy this then I can also paste it into Mail.

## Context
Tried to provide all steps alreaady. But I also screencasted it for you (short) showing exactly what I did and the problem and the annoying workaround via TextEdit:

http://sprunge.us/Voyh0f

KeePassXC - Version 2.5.4
Revision: dcca5aa

Operating System: macOS
Desktop Env: default macOS
Windowing System: default macOS

**Comment by droidmonkey** [comment]
Do you mean the notes field?

**Comment by Tormen** [comment]
Hi sorry about the screencast link... here is now one that works!

https://0x0.st/iLHU.mp4

To answer your question: Yes, the notes field. Sorry for not being more precise here. I thought I remembered the fields name, but I did not verify ;)

**Comment by droidmonkey** [comment]
That looks like an issue with Apple Mail since we can paste into the TextEdit without issue.

**Comment by Tormen** [comment]
Of course this crossed my mind. 
But then I could argue:
   But why can I copy and paste the same text from TextEdit, but not from KeePassXC ?

Honestly: I was super astonished when I first noticed this problem and I do not have the paste problem with any other app.
Can we somehow zoom in and get the byte representation of the clipboard content ?
To then being able to compare the content (and its metadata!) from KeepassXC and from TextEdit ?

Any other idea how to get more insight / proof who's to blame here ?

**Comment by droidmonkey** [comment]
We do add attributes (Metadata) to our clipboard copy to indicate the text is possibly a password or secure information. However, that is NOT done when copying text using the right click -> copy built in featur.

**Comment by Tormen** [comment]
Unfortunately this does not seem to be systematic :(
I just tried to reproduce and was not able to.
But it definitely happened before!
So if you have any idea how I could "zoom-in" next time this happens, I would gladly listen.

Otherwise I will try what I can get through osascript ... 
for now I found this AppleScript listing the types of the last clipboard item:
```
use AppleScript version "2.4" -- Yosemite (10.10) or later
use framework "Foundation"
use framework "AppKit"
use scripting additions

current application's NSPasteboard's generalPasteboard()'s pasteboardItems()'s firstObject()'s types() as list
```

In any case thanks for your comment.
If you don't have further ideas, maybe we can keep this open and I will come back with more details once I have them.

**Comment by Tormen** [comment]
... ok, just tried it again and BAM ;)

So... the above applescript lists a LOOOOT of types ;)

```
public.utf8-plain-text, com.apple.traditional-mac-plain-text, public.utf16-plain-text, public.text, com.trolltech.anymime.text--plain, public.html, com.trolltech.anymime.text--html, com.trolltech.anymime.application--vnd.oasis.opendocument.text
```

For the same text out of TextEdit this looks like this: `public.rtf, public.utf8-plain-text, dyn.ah62d4rv4gu8y63n2nuuhg5pbsm4ca6dbsr4gnkduqf31k3pcr7u1e3basv61a3k, public.utf16-external-plain-text`

And for the same text copied here from this Firefox Textbox: `public.utf8-plain-text`

And for the same text copied from the Terminal.app: `public.rtf, public.utf8-plain-text, public.utf16-external-plain-text`

In all 4 cases I copied the single world `Recovery` ! :))

So I'd say: Can you bring down the list of types to 1 or 2 ?
`public.utf8-plain-text`
and maybe also
`public.utf16-plain-text`

depending on if Keepassxc supports UTF16...

?

---------

Now about your CTRL+B / CTRL+C question:
I tried with CTRL+B and I got DIFFERENT possible types (then when copying from "Notes"): 

```public.utf8-plain-text, com.apple.traditional-mac-plain-text, public.utf16-plain-text, public.text, com.trolltech.anymime.text--plain, org.nspasteboard.ConcealedType, com.trolltech.anymime.application--x-nspasteboard-concealed-type
```

**Comment by Tormen** [comment]
Here is the screencast of (some of) the above:

https://paste.c-net.org/BrainerTriad

**Comment by droidmonkey** [comment]
Those are default Qt mimetypes being applied, notice the nspasteboard-concealed-type that is what I was referring to in my previous comment. As long as at least one mimetype matches what the receiving (pasted to) app accepts then the paste will happen. Shortening the list would do nothing. This is most definitely a bug outside of KeePassXC.

**Comment by Tormen** [comment]
OK I see your point. Thank you! :)

The only other explanation could maybe be a bug in QT I guess.
It remains pretty strange.
