### ISSUE TITLE
Item added to DeletedObjects when Recycled

### ISSUE THREAD

**Issue by strongbox-mark** [keepassxreboot/keepassxc#4742]
## Overview
I'm starting to implement "Synchronization" or "Merging" in Strongbox and I've come across an issue which I think could be a problem/bug. 

From my understanding an item should only be added to the DeletedObjects list when it is deleted (and NOT when it is moved to the Recycle Bin). However I was playing around with KeePassXC today for some experiments and discovered that even with the Recycle Bin enabled an item I "recycled" was added to the DeletedObjects list.

I think this could cause some real issues on synchronization. For example if a user recycles an entry (E) in version A of database, then the user syncs database A with an older copy (B), would KeePassXC now delete (hard delete, not recycle) E completely because E is in the DeletedObjects list? 

Shouldn't a recycle action just be a "Move" action to the Recycle Bin?

Perhaps I'm misreading things or not understanding fully how the system works and would be happy with any clarification so I can get things right on my side. Cheers!
-Mark

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Create a new database (all defaults are fine, e.g. Recycle Bin enabled)
2. Create a new entry (defaults fine)
3. Delete this entry and select 'Move' when asked if you want to move it to the Recycle Bin
4. Save your database.

## Expected Behavior
Recycled Entry should not appear in the DeletedObjects list

## Actual Behavior
Recycled Entry appears in the DeletedObjects list

## Context
As above, I'm working on Strongbox sync code and can see the DeletedObjects list. Not sure if you have a special too to see this, or just dump the XML to confirm.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.5.4
Revision: dcca5aa

Qt 5.14.1
Debugging mode is disabled.

Operating system: macOS 10.15
CPU architecture: x86_64
Kernel: darwin 19.4.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
 libgcrypt 1.8.5

**Comment by droidmonkey** [comment]
Good find, needs to be investigated

**Comment by droidmonkey** [comment]
I tried replicating this in develop branch and the deleted object list is not changed when an entry is moved to the recycle bin.

**Comment by strongbox-mark** [comment]
Cool thanks @droidmonkey! Should this be fixed then in the next release?

**Comment by droidmonkey** [comment]
There was nothing to fix, the behavior described did not happen when I tested it.

**Comment by strongbox-mark** [comment]
OK, no worries, thanks @droidmonkey
