### ISSUE TITLE
Show TOTP window blocks auto lock

### ISSUE THREAD

**Issue by kostas-theo** [keepassxreboot/keepassxc#4743]
## Overview
If I open the "Show TOTP" window and forget to close it my database will NOT be locked when I sleep my machine.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Right-click on any database entry with TOTP enabled
2. In the TOTP menu, select "Show TOTP..."
3. Put machine to sleep or close lid of laptop

## Expected Behavior
KeepassXC should lock my database

## Actual Behavior
My database remains unlocked with the Show TOTP still visible

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.5.4
Revision: dcca5aa

Qt 5.14.1
Debugging mode is disabled.

Operating system: macOS Mojave (10.14)
CPU architecture: x86_64
Kernel: darwin 18.7.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
 libgcrypt 1.8.5

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS

**Comment by droidmonkey** [comment]
This was fixed in develop branch.
