### ISSUE TITLE
Searchable KeepassXC-Browser integration

### ISSUE THREAD

**Issue by MrFrank17** [keepassxreboot/keepassxc#4748]
## Summary 
It would be helpful to have the option to search in the browser integration for hyperlinks (or names) in the KeepassXC database.

## Context
Right now I have to open links through KeepassXC or bookmark them in the browser. The latter is a duplication of information and therefore I try to avoid it, especially as links can change.
Going through KeepassXC of course works for me, but it would be more streamlined having it in the browser add-on.

**Comment by droidmonkey** [comment]
It is a design decision to not allow unlimited access to the database through the browser extension. We only allow access to a current, active site's entry. Allowing arbitrary searches breaks that model.
