### ISSUE TITLE
Portable Snapshot seems to write data in %AppData%

### ISSUE THREAD

**Issue by OLLI-S** [keepassxreboot/keepassxc#4751]
## Overview
After using the portable snapshot build, the settings in KeePassXC 2.5.4 are messed up (changes are saved immediately, browser-integration is turned off, etc).

## Steps to Reproduce
1. Install KeePassXC 2.5.4 in Windows 10 Pro to the default folder (C:\Program Files\KeePassXC)
2. Start KeePassXC and change some settings
3. Exit KeePassXC
4. Download the portable snapshot build KeePassXC-2.6.0-snapshot-Win64.zip from 15.05.2020
5. Extract the zip file to any folder (I extracted it in C:\Temp\KeePassXC - Snapshot)
6. Start the snapshot build, change the theme to "dark" and close it
7. Start KeePassXC 2.5.4 and check if the settings have changed

**Note:**
After this problem occurred, I posted this issue **without retesting** it.
Tell me if I should retest it or **if you need my settings files** (to check if the snapshot build really wrote in %AppData%).

## Expected Behavior
The **portable** version should never write any data in %AppData%

## Debug Info
KeePassXC - Version 2.6.0-snapshot
Build Type: Snapshot
Revision: 287e822

Qt 5.14.2
Debugging mode is disabled.

Operating system: Windows 10 Version 1909
CPU architecture: x86_64
Kernel: winnt 10.0.18363

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.5

**Comment by phoerious** [comment]
The portable ZIP from snapshot.keepassxc.org does not have a `keepassxc.ini`. We add that later with the release-tool, which isn't being used by the CI. So this is not really a bug. We could add the ini via CMake to the install target, then we wouldn't have to repackage the ZIP and snapshots would have it as well.

**Comment by droidmonkey** [comment]
I tried the cmake approach in the past..

**Comment by phoerious** [comment]
What failed? If its not fixable, we can close this.

**Comment by droidmonkey** [comment]
You have to setup a component build in order to selectively add files to a particular cpack installer. However that brings all sorts of challenges with the installer process. It's really just a mess.

We really should just "touch" a `.portable` file or similar instead of relying on arbitrary settings ini being in the root directory. The is especially so now that we have local vs remote settings.
