### ISSUE TITLE
keeshare does not sync for second group

### ISSUE THREAD

**Issue by thetuxinator** [keepassxreboot/keepassxc#4755]
## Overview
Hi, we use the keeshare feature for a single group already since quite some time and never had an issue with it.

We now wanted to add another group to synchronize, however it does not seem to synchronize the changes in that second group. We added the "Trust" to the certificate when it was asked to do so.

Also tried changing to import/synchronize does not help

Using KeepassXC 64bit Portable Zip on Windows X86_64

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.5.4
Revision: c023bf9

Qt 5.14.2
Diagnosemodus ist deaktiviert.

Betriebssystem: Windows 10 Version 1809
CPU-Architektur: x86_64
Kernel: winnt 10.0.17763

Aktivierte Erweiterungen:
- Auto-Type
- Browser-Integration
- SSH-Agent
- KeeShare (bestätigtes und unbestätigtes Teilen)
- YubiKey

Kryptographische Bibliotheken:
 libgcrypt 1.8.5

**Comment by droidmonkey** [comment]
Are your groups stored on network shares? If so this will be fixed in 2.6.0

**Comment by thetuxinator** [comment]
Hi, yes those are on network-shares. Any workaround?

**Comment by thetuxinator** [comment]
i looked around for information about 2.6 roadmap, but could not find anything, is there a roadmap?

**Comment by droidmonkey** [comment]
This is the fix PR: https://github.com/keepassxreboot/keepassxc/pull/4720
