### ISSUE TITLE
Persistent lockups/freeze/crash

### ISSUE THREAD

**Issue by dgmdevelopment** [keepassxreboot/keepassxc#4757]
## Overview
When adding new entry, it wont let me save the entry.  Program locks up. 

![image](https://user-images.githubusercontent.com/188736/82236434-18022700-9902-11ea-8fbb-eb7801591b7f.png)

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Add new entry
2. try to save. 
3. Must use task manager to end keepassxc to allow it to reopen.  Will not shut down on its own. 

## Expected Behavior
It should not freeze up. 

## Actual Behavior
Program terminates after freezing.  

## Context
Windows 10, build 9608.1000
Browser: Edge Version 83.0.478.33 (Official build) beta (64-bit)
Using Keepassxc chrome extension 

KeePassXC - Version 2.5.4
Revision: c023bf9

Qt 5.14.2
Debugging mode is disabled.

Operating system: Windows 10 Version 2004
CPU architecture: x86_64
Kernel: winnt 10.0.19608

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.5

**Comment by droidmonkey** [comment]
Fixed already for next version. Try our snapshot build at https://snapshot.keepassxc.org
