### ISSUE TITLE
database not readable from mounted partition

### ISSUE THREAD

**Issue by GilliganGH** [keepassxreboot/keepassxc#4762]
I just installed Ubuntu 20.04 and then KeePassXC.
KeePassXC version 2.5.4 refuses to read some directories, where the Database
is located. The Database can be read from my home directory, but that is not
where I keep it! I keep it in another partition that is encrypted.

$HOME = /home/uschcld
Database = /media/uschcld/Data_A/uschold/hidden/KeePassX.kdbx
I get a permission error reading the directory. see attached image.
permissions are read for all:
ls -l /media
drwxr-xr-x 3 root root 4096 2020-05-17 18:10 /media/

Other versions of KeePassX have no problems reading the Database.

![KeePassXC_Open1](https://user-images.githubusercontent.com/59489669/82349010-94127280-99c7-11ea-9d38-3d40c508d9dc.png)
![KeePassXC_Open2](https://user-images.githubusercontent.com/59489669/82349013-94127280-99c7-11ea-9e0e-d450cf37c605.png)

**Comment by droidmonkey** [comment]
Welcome to the wonderful world of snaps!

https://keepassxc.org/docs/#faq-appsnap-homedir
