### ISSUE TITLE
KeePassXC crashes when creating a new database that uses AES-KDF with less than 100000 transformation rounds.

### ISSUE THREAD

**Issue by ptmxl** [keepassxreboot/keepassxc#4764]
KeePassXC 2.5.4 on Ubuntu 20.04 crashes when creating a new database that uses AES-KDF with less than 100000 transformation rounds.

The crash only occurs when creating a new database not when changing the number of rounds of an existing database.

**Comment by droidmonkey** [comment]
Cannot replicate on develop branch.

**Comment by ptmxl** [comment]
The version I'm using is 2.5.4 from phoerious's PPA not the older version found in Ubuntu's repository.

Steps to reproduce the bug:

Starting from a fresh install
run KeePassXC
click "Create new database"
click "Continue"
click "Advanced Settings"
change the key derivation function to AES-KDF (KDBX 4) or AES-KDF (KDBX 3.1)
change the transform rounds to 1
click "Continue"
the "Number of rounds too low" warning dialogue will appear
click "Understood, keep number"
KeePassXC immediately crashes

I hope this helps.

**Comment by droidmonkey** [comment]
Nope, still not crashing

**Comment by ptmxl** [comment]
When I start KeePassXC from the terminal rather than using the icon and repeat the steps I have listed previously the terminal shows "Segmentation fault" when KeePassXC crashes. It might be reliant that I am conducting these tests in VirtualBox.
