### ISSUE TITLE
Copy paste bug in BaseStyle.cpp

### ISSUE THREAD

**Issue by qarmin** [keepassxreboot/keepassxc#4765]
Probably second occurrence of `colors[S_text]` should be removed

https://github.com/keepassxreboot/keepassxc/blob/26ea2742591da815e16608406e5bda7a39c793f5/src/gui/styles/base/BaseStyle.cpp#L398-L400

**Comment by droidmonkey** [comment]
Phantom bug. https://github.com/randrew/phantomstyle

**Comment by randrew** [comment]
I've fixed this upstream at randrew/phantomstyle@22c58ee4f9ff440fb9fd364c4af578d4f60bce8b

**Comment by randrew** [comment]
You should be able to apply this fix without any visual changes occurring in your UI.

I think these are the palette values you're using:

https://github.com/keepassxreboot/keepassxc/blob/develop/src/gui/styles/light/LightStyle.cpp#L33
https://github.com/keepassxreboot/keepassxc/blob/develop/src/gui/styles/dark/DarkStyle.cpp#L32

For these palettes, and my own test palettes, and all of the palettes I've seen in the wild, `QPalette::Text` and `QPalette::WindowText` ColorRoles use the same color value.

Thanks for finding this bug.

---

Unrelated aside: I saw that you're using `QStringLiteral` to populate the color values. `QStringLiteral` tends to generate a fair bit of binary bloat, at least with the compilers I've used. You might instead want to consider using integer literals, if that sort of thing is a priority in your project.

**Comment by phoerious** [comment]
Text and WindowText are the same, yes.

It's true that QStringLiteral is not optimal for strings which are not necessarily unique, perhaps we could be using QLatin1String or so instead. The reason why these are not numerical colour values is because hex codes are easier to copy-paste in and from graphics applications, where we can tweak and optimise them.

**Comment by droidmonkey** [comment]
BTW, @randrew, we just tried Qt 5.15 and it completely fails to apply the palette. I believe this to be a Qt bug, rather major one.

**Comment by randrew** [comment]
@phoerious you can use hex literals, which is what those strings are emulating -- just replace `QStringLiteral("#1D1D20")` with `0x1D1D20`.

@droidmonkey I don't have access to a Qt 5.15 installation right now. Are you saying you tried the KeePassXC code and the palettes didn't apply, or you tried the PhantomStyle code (probably the 'funhouse' project) and it didn't work? (Or both?)

**Comment by phoerious** [comment]
> you can use hex literals, which is what those strings are emulating -- just replace QStringLiteral("#1D1D20") with 0x1D1D20.

Good point. We should do that.
