### ISSUE TITLE
Option pointer but may be nullptr in BaseStyle.cpp

### ISSUE THREAD

**Issue by qarmin** [keepassxreboot/keepassxc#4766]
In line 4624 `option` pointer is used but in 4628 is checked if is null

https://github.com/keepassxreboot/keepassxc/blob/26ea2742591da815e16608406e5bda7a39c793f5/src/gui/styles/base/BaseStyle.cpp#L4624-L4628

**Comment by droidmonkey** [comment]
This is a Phantom bug too, please report to them as well.

**Comment by randrew** [comment]
I've fixed this upstream at randrew/phantomstyle@581192d10ef06ad9592267138fa567aab7223e01
