### ISSUE TITLE
Error on reopening locked database

### ISSUE THREAD

**Issue by SmoochiesBoss** [keepassxreboot/keepassxc#4767]
![error](https://user-images.githubusercontent.com/34968026/82468050-5fb6b900-9a90-11ea-8141-c114721d38e0.png)

This one is new. I'm on 2.5.4 on Win 10. The file locked when the PC went to sleep, and this error happened after XC hung while trying to reopen the file. Closing the app generated this.

**Comment by droidmonkey** [comment]
Fixed in develop branch
