### ISSUE TITLE
Opening keepass database from within keepass database

### ISSUE THREAD

**Issue by Keisial** [keepassxreboot/keepassxc#477]
People sometimes works with multiple database files (eg. some of them are shared with other people), albeit often having a main one which contains the master password for the other databases.

It would be desirable to open them directly from within keepassxc. Currently there doesn't seem to be an option to do so.
I propose that if the url starts with kdbx://, it is captured internally¹ and the rest of the url is treate as a filename opened by the current instance using the password field as master password.

Then, opening such database would be a matter of using the Open URL action over the entry.

¹ This could all be handled externally, but then the password would not be available or it would have to be passed in a less-secure way.

**Comment by scic** [comment]
Instead of implementing a new mechanism for this I propose using the same concept that the  **[KeeAutoExec](http://keepass.info/plugins.html#keeautoexec) plugin** for Keepass uses.

This has the advantage of being compatible with this plugin and switch/migrate between keepass and keepassxc.

### Excerpt from the KeeAutoExec documentation:

> 
>
> <p>First of all, create a new group in your database and name it
> <i>&quot;AutoOpen&quot;</i> (without the quotes).</p>
> 
> <p>Each non-expired entry in this group corresponds to a database that should
> be opened automatically when the current database is opened.
> The fields of each entry specify the following:</p>
> 
> <ul>
> <li><b>Title:</b>
> Ignored by the plugin; can be used for comments.</li>
> <li><b>Password:</b>
> The <a href="http://keepass.info/help/base/keys.html#password">master password</a>
> for the database to open. If no password is
> required, leave this field empty.</li>
> <li><b>URL:</b>
> Path to the database file to open. The path can be either absolute or
> relative to the directory containing <code>KeePass.exe</code>.</li>
> </ul>

The KeeAutoExec plugin has many more features but supporting the title, password and url fields should be a good starting point.

**Comment by scic** [comment]
Since there is now the PR https://github.com/keepassxreboot/keepassxc/pull/959 that implements this feature maybe someone can have a look and see if it is feasible to schedule this feature for the 2.3.0 release? If the PR is good it could be a low hanging fruit.

**Comment by TheZ3ro** [comment]
I've already seen it, need time for testing and review. Right now I (we) are prioritizing 2.2.2 since we identified some issue with 2.2.1, after that we can focus on 2.3.0 and that specific PR :)

**Comment by Remonli** [comment]
What's the news of this feature ? Does it work like keepass with -pw-enc  ?

**Comment by TheZ3ro** [comment]
Implemented in 2.3.0
