### ISSUE TITLE
Key exchange was not successful.

### ISSUE THREAD

**Issue by terrydixon** [keepassxreboot/keepassxc#4770]
When invoking KeePassXC (2.5.4) with Firefox (76.0.1) on Ubuntu (19.10) gives the message:
    Message encryption failed. Is KeePassXC running?
Even though KeePassXC is running. On hitting the reload button the following message is produced:
    Key exchange was not successful.
The KeePassXC-Browser addon has been installed in FIrefox. This has just started to happen. Up till then KeepassXC work flawlessly. 

KeePassXC - 2.5.4
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: Gnome
Windowing System: Wayland?

**Comment by droidmonkey** [comment]
Are you running the snap version?

**Comment by varjolintu** [comment]
Are you running the snap version of Firefox?

**Comment by Androphin** [comment]
I have the same error.
No snap version. Installed from Gentoo repo with USE flags autotype, browser and network.
 
KeepassXC: 2.5.3
KeepassXC Browser Integration for Firefox: 1.6.3
Firefox: 76.0.1
Operating System: Gentoo linux x86_64
DE: KDE

Firefox is started/used by another user than KeepassXC. So maybe it could be a permission problem with the keepass-proxy and nativemessaging?

What I discovered looking into the browser console if trying to refresh the connection to KeepassXC:
![1590736961](https://user-images.githubusercontent.com/40770104/83233550-29172780-a18f-11ea-90ef-e429ef1de427.jpg)

**Comment by droidmonkey** [comment]
You must run them as the same user
