### ISSUE TITLE
fringerprint

### ISSUE THREAD

**Issue by adelpourmand** [keepassxreboot/keepassxc#4771]
Hello to keepassXC team,
I wish you could add fingerprint reader to the masterkey of database.
Most of today's laptops have fingerprint reader/scanner for windows signing-in process. So we can type a password, or use fingerprint reader to sing in. You add this feature to the keepassXC to be able to enter database without typing the password every time. 

Regards,
Adel

**Comment by droidmonkey** [comment]
See #2462
