### ISSUE TITLE
Passwords in the password generator are not entered into the password field of a record

### ISSUE THREAD

**Issue by courtarro** [keepassxreboot/keepassxc#4773]
## Overview
Passwords in the password generator are not entered into the password field of a record

## Steps to Reproduce
1. Create a new password record
2. Click "Password Generator"
3. Click "Close" (tooltip says "Accept password")

## Expected Behavior
The password field of the new record is still empty

## Actual Behavior
The password field has the contents of the generated password entered into it

## Workaround
I must copy the password, close the generator, and paste into the password field myself.

## Context
None

## Version details
KeePassXC - Version 2.5.4
Revision: dcca5aa

Qt 5.9.5
Debugging mode is disabled.

Operating system: Ubuntu 18.04.4 LTS
Desktop Env: xfce
Windowing System: x11
CPU architecture: x86_64
Kernel: linux 5.3.0-51-generic

Enabled extensions:
- Auto-Type

Cryptographic libraries:
 libgcrypt 1.8.1

**Comment by droidmonkey** [comment]
This is totally reworked in the next release.
