### ISSUE TITLE
Backup Copy of My Database Is Not the Same as Original 

### ISSUE THREAD

**Issue by CerebralFreeze** [keepassxreboot/keepassxc#4774]
## Overview
I recently got hacked by a spiteful creature.  This one was a real...let's just say he or she wasn't very nice.  Programs would work and then stop working just to make me mad.  This hack extended to my smartphone.  I can't even use any browser because the keyboard doesn’t stay open.  I'll write about half a word and then the keyboard disappears.  For over about a week, a nice person at BleepingComputers.com tried to help me foil this hacker.  Ultimately, we failed so we killed ourselves...

As if!  We weren't that depressed.  I simply created a Window Installation flash drive and reinstalled Windows 10.  Took me a while but my computer works.  Now, it's the drudgery of moving all my files and reinstalling all my original programs.  Now, I really feel like killing myself.

Luckily, I back up my data, abiding by the Rule of Three.  I have Macrium Reflect uploading daily backups to a network drive and I also have Resilio Sync do continuous backups to the same network drive.  (I also use archival quality M-disk blu-rays to back up annually.)

## Steps to Reproduce
But, something strange happened when I downloaded 2 different copies of KeePassXC database files, one from my Macrium folder and one from my Resilio folder.  The databases are supposed to be protected by a file key but when I tried to use them, they wouldn't open!  I got really scared at this point and tried tons of passwords, thinking that somehow I wrote it down wrong.  But, about 5 weeks later, I finally thought about trying to access my passwords without the file key.  (j/k, it was about 5 minutes later)  I finally got access!  **The file key was unnecessary.**  What?!?!

The next strange thing is that the dates of my password entries were incorrect.  It stated that the most recent modifications and creations to my password database were made in mid-April.  I know for a fact that I made modifications this past week.  I also can't sort my entries by creation date.  I don't know why.  Something is fishy going on.  Using my impressive detective skills, I realized that my settings were different too!  They didn't get saved.

At this point, I'm not sure if any passwords are missing.  They do seem a little low but I'm not really sure since I just found out all this about 30 minutes ago.  I checked copies of the KeePassXC from other days and they all display and react the same way.  The last modification is that same day in mid-April.

## Expected Behavior
I guess I expected that when I put the file key in the same exact location as before and typed in the correct password, I expected that my life would be fulfilled.  I can tell you with 100% certainty that this didn't happen.

## Actual Behavior
Obviously, my password files are a bit messed up and it makes me really sad.  Tomorrow, I'm going to hang myself.  This time I mean it.  Before then, if anyone can explain to me what had happened to my files, I would appreciate it greatly.  I'll even buy you a beer next week!

## Context
Conspiracy and crazy talk time!  Maybe the person who hacked my computer had gotten access to my password manager and did stuff to it!  

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.5.4
Revision: c023bf9

Qt 5.14.2
Debugging mode is disabled.

Operating system: Windows 10 Version 1909
CPU architecture: x86_64
Kernel: winnt 10.0.18363

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.5

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows
Desktop Env: A jungle of papers, food, plates, and books.
Windowing System: Windows 10

**Comment by droidmonkey** [comment]
Please dont hang yourself. The most likely scenario is that your backup solution failed to backup your database file since mid April. When did you start using a key file for your database?

**Comment by CerebralFreeze** [comment]
**I think DroidMonkey is Indeed a Great Detective**

When did I start using a key file for my database?  That's a hard question.  I admit that I was one of those remedial kids put in special classes.  I might have started using a key file starting from….wait....mid-April!  I can't remember when to be honest but I think it was about a month ago!  Seriously!  I saw the key file feature and figured it would be really good to learn since I wanted to maybe try to transfer my KeePassXC database on my smartphone.  It would be additional security.  I didn't get to my phone but started using a key file for my desktop about a month ago.

Impressive.  You are a good detective.  So, you think there is some correlation?  That due to the key file, my password file wasn't being correctly copied daily for all that time?  Maybe that is why I feel like my password list looks a little smaller than it should.  I don't know if I see any new passwords.  I definitely notice that the passwords have been modified and they all seem to have the date of mid-April.  When I sort by modified date, sorting is executed orderly.  But, when I try to sort the list by creation date, the list goes all crazy.  The dates are all mixed up and not in order.

Are you hinting to me that I might have lost a month-worth of new login-passwords!  I am so depressed!  That's the worst news I've ever heard.  I know it's not your fault.  This happens with open source programs.  But, I think I'm going to kill myself!  Maybe with a knife to get it over with. 
 Please help me.  My life is in your hand.

Should I just get rid of the key file and stop using it?

**Comment by droidmonkey** [comment]
I don't see why you need the key file, just use a good master password. I believe this is entirely on your end, check your backups.
