### ISSUE TITLE
broken integration with chromium via fdo

### ISSUE THREAD

**Issue by dkwo** [keepassxreboot/keepassxc#4775]
With the last Chromium update on Arch Linux (from 81 to 83.0.4103.61-1), it seems integration of Chromium with Keepassxc via FDO secret agent is broken. Downgrading Chromium solves the issue, although I'm not sure what is causing it. Do you have any suggestion?

**Comment by Aetf** [comment]
How exactly is the integration broken? To help further debug, could you provide the output of the following command? The command will print to stdout all interactions between keepassxc and other clients via fdo secret service. Make sure you mask out secrets in the output.

```
dbus-monitor "interface='org.freedesktop.Secret.Service'" "interface='org.freedesktop.Secret.Collection'" "interface='org.freedesktop.Secret.Item'" "interface='org.freedesktop.Secret.Prompt'"
```

**Comment by dkwo** [comment]
I don't know what changed, but the same Chromium version now has FDO
working.
I will keep monitoring it.
Thanks for your assistance.
