### ISSUE TITLE
Tray Icon Symbol to large with Ubuntu Budgie

### ISSUE THREAD

**Issue by MBurchard** [keepassxreboot/keepassxc#4778]
https://bugs.launchpad.net/ubuntubudgie/+bug/1880561
I do a cross post of this issue. It might be, that KeepassXC does not contain the icons in correct size and can fix this. Might be that the budgie guys have to fix it.
I don't know...

**Comment by droidmonkey** [comment]
That is definitely a budgie problem. If anything it is a Qt problem.

**Comment by MBurchard** [comment]
> The app needs to respect the api convention which is 16pxto 24px.
> We don't and will not scale png based icons
> Suggest report this to the upstream keeps developers

@droidmonkey

**Comment by droidmonkey** [comment]
The icon is svg for the next release, that is also a ridiculous requirement from them. They are in control of the size of items in their taskbar. If anything icons should be passed at higher resolutions and scaled down for high dpi purposes.

**Comment by MBurchard** [comment]
I couldn't agree with you more
