### ISSUE TITLE
Cannot connect browser extension on Chromium

### ISSUE THREAD

**Issue by mara004** [keepassxreboot/keepassxc#4779]
## Overview
Cannot connect browser extension with KeePassXC (Chromium, Win 8.1), even though browser integration for Chromium is enabled in the settings.

## Steps to Reproduce
1. Use Windows 8.1 Version 6.3 (Build 9600) with Chromium 83.0.4103.61, KeePassXC 2.5.4 and KeePassXC-Browser 1.6.3 (install Chromium and KeePassXC from chocolatey package manager)
2. Open KeePassXC and unlock your password database
3. Start Chromium
4. The following warning will be displayed: "Cannot connect to KeePassXC. Check that browser integration is enabled in KeePassXC settings."
5. When pressing the refresh button, it says "Key exchange was not successful."

## Expected Behavior
When unlocking the database and refreshing the browser extension, it should connect with KeePassXC.

## Actual Behavior
It doesn't connect.

## Context
Apparently, this problem is concerning Chromium only, since browser integration works perfectly with Firefox on the same machine.
The issue has already occurred with a previous version of Chromium (81.0.4044.138).

KeePassXC-Browser - 1.6.3
Operating system: Win32
Browser: Chrome/Chromium 83.0.4103.61

KeePassXC - Version 2.5.4
Revision: c023bf9
Qt 5.14.2
CPU architecture: x86_64
Kernel: winnt 6.3.9600
libgcrypt 1.8.5

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 8.1 Version 6.3 (Build 9600)

**Comment by droidmonkey** [comment]
Don't use chocolatey for either keepassxc or chromium...

**Comment by mara004** [comment]
I think there has been a little misunderstanding. My Chromium is an official build and a standard installation. If I go to "About Chromium", it says "Version 83.0.4103.61 (Official Build) (64-bit)"
Chocholatey don't make their own builds (unlike Linux distributions). This package manager just automates the process of downloading and executing official binaries with powershell scripts, so software is easier to update. This means my Chromium installation is completely the same as it would be if I manually downloaded and executed the official binaries, because this is all chocolatey does.
If you want to ensure I am right, you can read the chocolatey documentation: https://chocolatey.org/docs
Enclosed you will also find a screenshot of my Chromium about page.

Thank you for developing KeePassXC!

Kind Regards,
mara004
![Screenshot (3)](https://user-images.githubusercontent.com/65915611/82886599-0b578180-9f47-11ea-94c8-61c7e4852809.png)

**Comment by droidmonkey** [comment]
Ok good point

**Comment by varjolintu** [comment]
@mara004 Have you checked the [Troubleshooting guide](https://github.com/keepassxreboot/keepassxc-browser/wiki/Troubleshooting-guide)?

**Comment by mara004** [comment]
Thanks for the troubleshooting document, which I hadn't found before. I have now gone through the steps and verified everything, but all from points 1) - 3) seems to be okay.
1) - org.keepassxc.keepassxc_browser_chromium.json can be found where it's supposed to be
   - the registry key exists
   - path variable is pointing to "C:\\Program Files\\KeePassXC\\keepassxc-proxy.exe", which is the exact location
2) - the second ID in allowed_origins is chrome-extension://oboonakemofpalcgghocfoadofidjkkk/, which is the same as the one shown in the extention's page
3) - I have checked in the resource monitor that keepassxc-proxy is running (it has PID 2736 and uses 2 threads)
4) - Console output says the following:
   Error 5: Cannot connect to KeePassXC. Check that browser integration is enabled in KeePassXC settings. [I checked that]
   keepass.js:982 Connecting to native messaging host org.keepassxc.keepassxc_browser
   keepass.js:952 Failed to connect: Specified native messaging host not found.
   keepass.js:1185 Error: No content script available for this tab.
   keepass.js:1065 Error 9: Key exchange was not successful.

If you need any further information or if I can help somehow, please tell me!

**Comment by varjolintu** [comment]
Everything should be ok then. Can you check what [Process Monitor](https://docs.microsoft.com/en-us/sysinternals/downloads/procmon) shows when it's trying to connect to the proxy?

**Comment by mara004** [comment]
When the extention attempts to access some registry keys, process monitor says "name not found" four times. Here's a [screenshot](https://www.magentacloud.de/lnk/0lAGGF8Z).

**Comment by droidmonkey** [comment]
Ummm..... You installed Chrome not Chromium

**Comment by mara004** [comment]
No, I am sure it is Chromium (as you can also see from the first screenshot and from the icon in the second screenshot), but the process is just called chrome.exe in process monitor. I don't know why that is the case... In the task manager it is properly displayed as Chromium.

**Comment by varjolintu** [comment]
What droidmonkey means that you've probably enabled the support for Chome in KeePassXC settings but not for Chromium. Those are two different things.

That registry path should have a default value that points to the `org.keepassxc.keepassxc_browser_chromium.json` file with full path.

**Comment by mara004** [comment]
No, I've verified that I only enabled it for Chromium...

**Comment by mara004** [comment]
But you're right. It's indeed pretty strange that the registry path contains Google\Chrome

**Comment by mara004** [comment]
This is what procmon displays about chrome.exe [(screenshot).](https://www.magentacloud.de/lnk/W8AmGa8N) It also recognizes it as Chromium, it's just the process which is called chrome.

**Comment by varjolintu** [comment]
Still, KeePassXC is looking for Chrome's registry entries, not Chromium's. What happens if you enable all three (Chrome, Chromium and Brave) in KeePassXC?

**Comment by mara004** [comment]
If I enable both Chrome/Vivaldi/Brave and Chromium, it works fine :). Thank you! Close the issue?

**Comment by droidmonkey** [comment]
So Chromium is now looking in Google Chrome registry settings???
