### ISSUE TITLE
Bug: Opening database with key from CLI displays error in GUI

### ISSUE THREAD

**Issue by nasirhemed** [keepassxreboot/keepassxc#4783]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
Whenever I open a keepass database from the command line and supply a key file, I get the following error:  
>Error while reading the database: Invalid credentials were provided, please try again.
If this reoccurs, then your database file may be corrupt. 

However, when I enter my password, the database opens up and everything is fine. I am not sure why I get the error up.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Run the command `keepassxc --keyfile <your_keyfile> <your_database>`
2. 
3. 

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Things open up normally with no errors. Should be able to enter password and open database

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Getting an error note:
> Error while reading the database: Invalid credentials were provided, please try again.
If this reoccurs, then your database file may be corrupt. 

Logs 
`Qt: Session management error: None of the authentication protocols specified are supported
QObject::startTimer: Timers cannot have negative intervals`

Although, when I enter my master password to the database, it opens up fine.

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.4.3
Revision: 5d6ef0c

[NOTE]: # ( Pick choices based on your environment )
Operating System: Ubuntu 20.04 LTS
Desktop Env: Gnome
Windowing System: X11

**Comment by droidmonkey** [comment]
You also need to supply your password on the command line. Otherwise don't supply any key file.
