### ISSUE TITLE
Emergency access

### ISSUE THREAD

**Issue by Thomas131** [keepassxreboot/keepassxc#4784]
Hi!
## Summary
I need a way to give trusted persons emergency-access for my account.

## Ideas
- Implement a way of having a 2nd Emergency-Password
- Implement a dialog where you can generate Shamir Secret Sharing pieces of the 2nd Password (or even the 1st one would be great)
- make a way to display the internal Key and print that as QR-Code for example
- **[...]**

## Examples
- [LastPassword Implementation](https://helpdesk.lastpass.com/de/emergency-access/)
- [1Password Implementation](https://support.1password.com/emergency-kit/)

## Context
Last year a friend of me died unexpectedly (not a close friend). It made me thinking: I am responsible for a lot of stuff voluntarily and at some point I will also die, or not be able to do them because of other unexpected events. I need a way to give trusted friends emergency-access to my passwords.

Best Regards!
Thomas131

**Comment by droidmonkey** [comment]
You can do a shamir secret using publicly available websites right now. We do not intend to have alternative credentials, that is not how kdbx is structured and will break KeePass compatibility.

Your best bet is to store your master password on a piece of paper in a safe that others can access. There are also dead-man switches that send information to select individuals after a set number of days of inactivity.

Ultimately this is up to you to implement in your own life and there is nothing we should change at this time.

**Comment by phoerious** [comment]
You might be able to piggyback that onto KDBX with key files. You can encrypt a secret with the shared key and then feed they decrypted key as a Keyfile into KeePassXC.

**Comment by Thomas131** [comment]
Thanks for all the ideas!

It seems to boil down to not changing the master password or keyfile but share that information encrypted or in parts. Still I think it would be helpful to make it easier for people to do that - or just to remind people of the problem of good encryption - if you are lost (physically) then the information is lost. (A lot of passwords gladly can be changed pretty easily using mail)

Thanks and god bless!
Thomas131

**Comment by Borkason** [comment]
> Still I think it would be helpful to make it easier for people to do that.

I don't see how that would make it easier than sharing your secret key with another person. If anything, implementing something like @phoerious described just obscures that you are still sharing one common secret with another person.

It also gives a false sense of security. If you want or must change your password and someone has emergency access, you are only changing your personal secret. The common secret remains unchanges.

Also, when the emergency contact leaks the password, you will never know. If you had actually shared the secret password with your emergency contact, at least it is clear to the database creator that someone else has your secret and there is a danger that they leak it.

**Comment by phoerious** [comment]
If you shard your master key, the shared secret will become useless when you change the master key. In that sense it is indeed more secure than sharing a secret that gives direct access to the data. Otherwise, it's pretty equivalent.
