### ISSUE TITLE
For portable mode artifact, including a `keepassxc.ini` risks overwriting existing `keepassxc.ini`

### ISSUE THREAD

**Issue by stdedos** [keepassxreboot/keepassxc#4786]
If the average Joe cleanly de-compresses a new portable version on top of an existing one (and assuming that ofc the default "Replace All" is selected), then:

## Expected Behavior
Existing configuration is preserved

## Actual Behavior
Existing configuration is lost

## Proposed Solution
Rename `keepassxc.ini` to something else, e.g. `keepassxc.ini.in`

If portable mode is detected by the existence of `keepassxc.ini`, then this needs to be fixed (e.g. make it depend on both `keepassxc.ini` and `keepassxc.ini.in` doing `cp keepassxc.ini.in keepassxc.ini` if `keepassxc.ini` does not exist)

-----

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows

**Comment by stdedos** [comment]
_Related to https://github.com/keepassxreboot/keepassxc/issues/4751#issuecomment-630156249_

**Comment by stdedos** [comment]
_Or pick `keepassxc.orig.ini` if no templating is done: highlighting is preserved in extension-based highlighters_

**Comment by droidmonkey** [comment]
This is covered under the discussion in #4751 which will be implemented in 2.6.
