### ISSUE TITLE
Use X.509 certificates for password unlock

### ISSUE THREAD

**Issue by tuxmaster5000** [keepassxreboot/keepassxc#4787]
## Summary
It will be very nice, when certificates can be used to protect the database.
Then no passwords for the database must be shared.

## Examples
Using it together with many employees in an team.
To allow only the right team the access, the verification can be done via the ou part of the certificate. 

## Context
Using certificates make it much simpler in business  scenarios.
For example, when an certificate was stolen, and it was revoked, then keepassx can deny the access, because the ocsp service tell it, that the certificate is invalid.
So you have more time to change the passwords, which are stored in the database.

**Comment by droidmonkey** [comment]
I am not tracking how this would be possible. KDBX databases use a master key that is a transformation of the combined hash of password hash + keyfile bytes hash + Yubikey CR hash. Using X.509 certificates would not provide information to this process that could be revocable.

**Comment by autarchprinceps** [comment]
This is possible with Keepass on Windows, so why shouldn't it be possible in Keepass XC? It would have to open the same databases no less.

**Comment by phoerious** [comment]
It's not. What you are referring to is pretty much this: #255
You encrypt a symmetric secret key with a bunch of private RSA keys. The trust status of the certificate itself is irrelevant. Nothing prevents you from decrypting the database with a revoked certificate.
