### ISSUE TITLE
Windows x86 build

### ISSUE THREAD

**Issue by jsoref** [keepassxreboot/keepassxc#479]
Currently the website only provides a 64bit build.
Some netbooks have 32bit UEFI and thus can't run 64bit versions of Windows.

## Expected Behavior
There should be a download for 32bit versions of Windows. This could be a unified download, or it could be a standalone download.
If you do not unify them, then the 64bit installer needs to warn/error visibly when someone tries to run it on a 32bit version of Windows.

## Current Behavior
1. User downloads Windows installer.
1. User runs Windows installer.
1. User "installs" application
1. User tries to run application
1. Nothing happens.
1. User is very very very confused.

## Steps to Reproduce (for bugs)
1. Visit https://keepassxc.org/download#windows
2. Click Executable installer
3. Click Run
4. ...

## Context
This prevented me from accessing my keepass database.

## Your Environment
* Windows 10 (32bit) / Asus EeeBook X205TA

**Comment by droidmonkey** [comment]
I posted 32-bit builds of v2.1.4 on the releases page!

https://github.com/keepassxreboot/keepassxc/releases/tag/2.1.4
