### ISSUE TITLE
Hide the left Groups panel?

### ISSUE THREAD

**Issue by zohozer** [keepassxreboot/keepassxc#4792]
I would like to have a feature to remove the left Groups panel from the main window as I never use that and it is only using unnecessary screen space for me. Seems that I can do-it smaller but it never dissapears.

**Comment by droidmonkey** [comment]
Duplicate #689

**Comment by sblatnick** [comment]
While this is a duplicate of #689, the feature's pull request was closed without merging: https://github.com/keepassxreboot/keepassxc/pull/1482
