### ISSUE TITLE
Prompt for password in CLI should be on stderr

### ISSUE THREAD

**Issue by tremby** [keepassxreboot/keepassxc#4794]
## Overview
When keepassxc-cli is run in command substitution as part of a script, in order to capture the output, its prompt for the password isn't shown.

## Steps to Reproduce
1. Run `keepassxc-cli show ~/mydb.kdbx My/Entry`, see that you are prompted for a password
2. Run `output=$(keepassxc-cli show ~/mydb.kdbx My/Entry)`, see no prompt for a password
3. Note that the prompt for the password is captured along with the output in the `$output` variable.

## Expected Behavior
I expect the prompt for the password to be output on stderr so that it's shown even if stdout is being captured, and so that it isn't included in the stdout captured by my script.

## Actual Behavior
The password prompt is output on stdout.

## Context
```
KeePassXC - Version 2.5.3
Revision: f8c962b

Qt 5.9.5
Debugging mode is disabled.

Operating system: Ubuntu 18.04.3 LTS
CPU architecture: x86_64
Kernel: linux 4.15.0-74-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.1
```

**Comment by droidmonkey** [comment]
This is already done in develop branch

**Comment by tremby** [comment]
Oh, nice. Thanks!
