### ISSUE TITLE
Error while reading the database

### ISSUE THREAD

**Issue by thisisverygreat** [keepassxreboot/keepassxc#4795]
## Overview
After MacOS security updates (Update 2020-003 and Update 2020-002) I was not able to load my password file into KeePassXC anymore.  

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. run KeePassXC
2. load my .kdbx file

## Expected Behavior
that it loads the database as months without any problems:

## Actual Behavior
it shows an error as if the password is incorrect. but I am very sure it is not. 

_**ERROR:**_ 

_Error while reading the database: Invalid credentials were provided, please try again.
If this reoccurs, then your database file may be corrupt. (HMAC mismatch)_

## Context
I checked the password-file for not being massivly broken by checking the header in the hex-editor as descibed in https://keepass.info/help/base/repair.html . that looked fine. 

KeePassXC - Version 2.5.4
Revision: dcca5aa

Qt 5.14.1
Debugging mode is disabled.

Operating system: macOS High Sierra (10.13)
CPU architecture: x86_64
Kernel: darwin 17.7.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
 libgcrypt 1.8.5

Operating System: macOS

**Comment by droidmonkey** [comment]
There is nothing we can do to help you unfortunately. This isn't a problem with our program, make absolutely sure you are entering your credentials correctly.
