### ISSUE TITLE
Automatically Deploy Binaries from TravisCI to GitHub Release

### ISSUE THREAD

**Issue by TheZ3ro** [keepassxreboot/keepassxc#48]
Should be nice to have automatic build (for Linux/Mac) directly from TravisCI only when pushed to develop/master or only when a new tag is created
## Expected Behavior

When committing a new tag, Travis will automatically build executables and push them on GitHub Release.
## Current Behavior

Manual deployment 
## Possible Solution

Editing the .travis.yml file to deploy on Github Release
https://docs.travis-ci.com/user/deployment/releases/
With conditional deployment
https://docs.travis-ci.com/user/deployment#Conditional-Releases-with-on%3A

**Comment by droidmonkey** [comment]
This would technically be automatic deployment, retitling.

**Comment by droidmonkey** [comment]
Closing since we moved to TeamCity and deploying releases requires many steps for us at this point.

**Comment by mongrelion** [comment]
@droidmonkey is there any documentation on the steps for creating a new release? that'd make it easier for volunteers to pick-up and automate the task, no matter the CI environment.

**Comment by droidmonkey** [comment]
You can't make a release because they are signed by our team key and also by the windows code signing.

**Comment by mongrelion** [comment]
Right, I'm not talking about creating the release myself (perhaps only for testing purposes) but rather have it done automatically by TeamCity, for example.
Is that an acceptable idea? the automation of the building of the artifacts for all platforms?

**Comment by droidmonkey** [comment]
We do plan on getting TeamCity to build a nightly at some point, it is already in the code since 2.3
