### ISSUE TITLE
New feature: "Include" filed in password generation windows

### ISSUE THREAD

**Issue by MAPIIIAJI** [keepassxreboot/keepassxc#4800]
First of all, thank you for your product!
I would like to have the "Include" field in addition to "Do not include". sometimes this is a very necessary option in order to generate a password using certain characters. In such cases, you have to resort to third-party services.

![image](https://user-images.githubusercontent.com/35526267/83393408-2a0abc00-a410-11ea-8ace-fe0d195fe463.png)

**Comment by droidmonkey** [comment]
Already added for next version
