### ISSUE TITLE
Save decision to release key depending on browser identification key and add some warnings.

### ISSUE THREAD

**Issue by riedel** [keepassxreboot/keepassxc#4801]
## Summary
1. It seems that most browser plugins do not fully implement the keepass-xc-browser protocol by not safely storing the identification key ( https://github.com/keepassxreboot/keepassxc-browser/commit/be5bc3cbdf14eaf9c461315c126f0dbd06be3a40#diff-1fb5fb2fd451ca9f3f1047a50118b457R16 ) . This currently seems to be not possible with most browsers (See: https://github.com/keepassxreboot/keepassxc/issues/4513#issuecomment-636322271) . Consequently, a user should be able to make the difference between browsers implementing the "SHOULD" and those that don't (makes a huge difference IMHO)

1. IMHO, also the requesting API key and a word of warning should be added to the releas key dialog with the "remember my decision" check box by default.

1. In the id key registration dialog it should be made clear, that this will probably only protect access by other webextensions not by applications that can access the filesystem. I think people will have a huge misconception about the added security (what happened to me)

## Examples
If I would trust eg. a sandboxed chrome to save the identification but e.g. would not trust firefox I could not make a difference (which IMHO would be essential)

## Context
This is important to me, because I actually want to retrieve passwords from the command line. ATM, I could just extract the key from Chrome or Firefox to retrieve most passwords without a popup, because I trusted the webextension to store the key safely (my fault? The consequences did not occur to me, because of all the fuzz about registering the webextension...)

~I have now a hard time removing the "KeepassXC-Browser-Settings" from each item to bring the popup back. Binding it to a key would allow easy revoking decisions.~

**Comment by droidmonkey** [comment]
The problem with binding it to a key is that makes re-connecting your browser a giant PITA. At this point we are discussing moving the boundary between security and usability. I am not sure we want to do that, it's already a complex process for most users.

**Comment by riedel** [comment]
Actually I you can bind it just to the name of the key. That one can be easily overwritten. Also this could be a simple checkbox on the advanced page of the browser integration.

**Comment by varjolintu** [comment]
@riedel Database settings -> Browser Integration -> Forger all site-specific settings on entries.
