### ISSUE TITLE
Cannot save new database to SMB share.

### ISSUE THREAD

**Issue by Borkason** [keepassxreboot/keepassxc#4809]
## Overview

I cannot save a new kdbx file to a SMB share. I do have write access to the location.

(When I save it locally and then move it to the SMB share, I can open the file in KeePassXC and also save it.)

## Steps to Reproduce

1. Create a new database.
2. Attempt to save the database to an SMB share.

## Expected Behavior

It should work.

## Actual Behavior

> Writing the database failed: The system cannot find the path specified.

![image](https://user-images.githubusercontent.com/2971735/83486515-9d144100-a4a9-11ea-96a9-4ecd32ad2013.png)

## Context

```
KeePassXC - Version 2.5.4
Revision: c023bf9

Qt 5.14.2
Debugging mode is disabled.

Operating system: Windows 10 Version 1909
CPU architecture: x86_64
Kernel: winnt 10.0.18363

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.5
```

**Comment by droidmonkey** [comment]
Confirmed this is a bug.

**Comment by droidmonkey** [comment]
And got a fix for it.
