### ISSUE TITLE
Preferences sub-menu not in KeepassXC menu on macOS

### ISSUE THREAD

**Issue by CfKu** [keepassxreboot/keepassxc#481]
The preferences sub-menu entry is in the tools menu if language is set to "German" on macOS.

## Expected Behavior
If I set the language to "English" the preferences sub-menu is as expected in the KeepassXC menu. But not if I change the language to "German". I expect it to be also in the "KeepassXC" menu.

## Current Behavior
If I set the language to "German" the "Einstellungen" (=Preferences) sub-menu is in the tools menu

## Possible Solution
No idea

## Steps to Reproduce (for bugs)
On macOS
1. Go to KeepassXC - Preferences...
2. Set lanuage to "German"
3. Restart KeepassXC
4. Check "KeepassXC" and "Tools" menu

## Context
---

## Your Environment
* KeePassXC version/commit used: Revision: 76dcfb5ed0c874f6a835ef0347ddf6098b149e9b (2.1.3)
* Qt version (e.g. Qt 5.3): Qt 5.8.0
* Operating System and version: macOS Sierra 10.12.4

**Comment by weslly** [comment]
Happens to other languages too. 

Fixed on #483
