### ISSUE TITLE
Relative Path for SSH Keys

### ISSUE THREAD

**Issue by MBurchard** [keepassxreboot/keepassxc#4810]
## Summary
If you synchronize your password database on several computers with different operating systems/hard disk partitions, then an absolute path for the key file does not work well.

A relative Path check would solve this problem.

If the Path starts with .ssh, KeepassXC should first check if the path matches the standard path of every SSH Installation that is /home/username/.ssh (Linux) or %Home%/.ssh (Windows). If the Path does not point to a file there, KeepassXC should check if the Path relative to the Database File Location matches a File.

## Examples
![grafik](https://user-images.githubusercontent.com/4256302/83496477-70682580-a4b9-11ea-8a93-34d0ec6dfb19.png)

**Comment by hifi** [comment]
We have environment variable substitution in 2.6.0 so you can use `$HOME/. ssh`.
