### ISSUE TITLE
Search - Remove entry form search, priority

### ISSUE THREAD

**Issue by abacao** [keepassxreboot/keepassxc#4811]
Hello KeepassXC team, thank you for your work and software.

It is possible to consider the following things:

- Remove an entry from the search like we can do it with groups
- Give search results a priority. 

Example: "Set Priority 1 on entryC"
I have 3 entries (A, B and C) and the user is always admin.
By default the entry selected after the search for "admin" is "entryA".
After I set "Priority 1" on entry Cm the entry selected when searching "admin" will be "entryC"

This is a twist on the "Favourite Entry". This seems more flexible.

Thanks

**Comment by droidmonkey** [comment]
This could be done with the tags feature. I do not agree with hiding specific entries from search nor a search priority.

**Comment by abacao** [comment]
Where can I find the tags feature in keepassxc 2.6.0 ?

**Comment by droidmonkey** [comment]
Coming in 2.7
