### ISSUE TITLE
Changing Settings on "old" Yubikey-DB results in "No password set" warning

### ISSUE THREAD

**Issue by 0xpr03** [keepassxreboot/keepassxc#4814]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
If you go to database settings and toggle the "Max. history" settings and click ok you'll get a warning about having no password for the Database, when using a yubikey only authentication.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Create a HMAC-Yubikey based database (no password)
2. Go to Database -> Database Settings and unpick "Max. history items"
3. Click on Ok

## Expected Behavior
Settings are saved, no warning.

## Actual Behavior
I get a warning during save like down below.
![image](https://user-images.githubusercontent.com/1280209/83620978-619f7280-a58e-11ea-8ab4-156e3600682a.png)

## Context
[NOTE]: # ( Give us any additional information you may have. )
This happens on an existing database. Apparently you added support for passwords with yubikey as 2nd factor since I created this DB. I had to try around to figure out the real meaning of this dialog. Previously you only had a password xor a yubikey, so I didn't even knew what the dialog was supposed to mean. (Invalid detection of no password due to missing check for yubikey hmac "password" / password is cleared /..) Because of this I also feared a DB lockout.

I can understand warning about this with a dialog, but getting this when you change an unrelated setting in your DB, without even knowing about the new feature, is really frightening.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.5.4
Revision: dcca5aa

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: KDE
Windowing System: X11

**Comment by phoerious** [comment]
We have never supported just one or the other. You could always set a password and a YubiKey together and we always recommended setting a password no matter if you are also using a key file or YubiKey. The setting is not unrelated. You changed a database setting and this triggered a full validation of your choices.

**Comment by 0xpr03** [comment]
Hm that's interesting. Based on what I saw back then on your website and the setup back then I assumed you can only have one or the other. Either way it's nice to have both. I'll close it and maybe other folks have had the same problem.
