### ISSUE TITLE
NIT: Autotype Icon is Upside Down?

### ISSUE THREAD

**Issue by Gurran** [keepassxreboot/keepassxc#4815]
## Overview

The autotype icon diplayed as an ISO enter key is upside down! I know that there are a few keyboards that use this variant, but it's not the standard. 

![image](https://user-images.githubusercontent.com/42462633/83646222-a7bafd00-a5b3-11ea-9cca-042d12c9cfbc.png)

**Comment by Gurran** [comment]
![image](https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/ISO_keyboard_%28105%29_QWERTY_UK.svg/1280px-ISO_keyboard_%28105%29_QWERTY_UK.svg.png)

**Comment by phoerious** [comment]
Please take your complaints to the Oxygen icon designers. We won't be using these icons in 2.6 anymore.
