### ISSUE TITLE
HOW to store more than one URL into the same Entry

### ISSUE THREAD

**Issue by vyujitanaka** [keepassxreboot/keepassxc#4816]
I understand that there is the possibility to add more than one URL in the same Entry in KeePassXC as was answered [here](https://github.com/keepassxreboot/keepassxc/issues/4812). But it was not said how to do this. Can you provide a step by step?

I'm sorry, but I am a new user. And knowing that there is a possibility to do this since version 2.5.0 unfortunately does not answer my question.

Thanks in advance!

Best regards.

**Comment by droidmonkey** [comment]
When editing an entry, click on the browser integration tab on the left.
