### ISSUE TITLE
The previous database is not loaded on macOS if language set to "German"

### ISSUE THREAD

**Issue by CfKu** [keepassxreboot/keepassxc#482]
The previous database is not loaded on macOS if language set to "German" and if I close KeepassXC with &#8984;Q instead of clicking on the red cross.

## Expected Behavior
If I change the language to "English" the previous used database is loaded as expected. But if I use my system's language (german) or set it manually to "German" the previous database is not loaded on startup on macOS, despite having the option in the preferences set.

## Current Behavior
If language set to "German", the previous database won't be loaded on startup on macOS if I close KeepassXC with &#8984;Q. If I press the red cross it works also with the "German" language.

## Possible Solution
Switch language to "English", then it works as expected.

## Steps to Reproduce (for bugs)
1. KeepassXC - Preferences...
2. Switch language to "German"
3. Close with &#8984;Q
4. Open KeepassXC
4. Load and unlock your database
5. Close with &#8984;Q (not with the red cross on the window)
6. Open KeepassXC
7. KeepassXC starts with the welcome screen, not as expected with the password prompt for the previous used database.

## Your Environment
* KeePassXC version/commit used: Revision: 76dcfb5ed0c874f6a835ef0347ddf6098b149e9b (2.1.3)
* Qt version (e.g. Qt 5.3): 5.8.0
* Operating System and version: macOS Sierra 10.12.4

**Comment by weslly** [comment]
This is related to #481 and was also fixed in #483.
