### ISSUE TITLE
KepassXC 2.5.4 Snap on Ubuntu 20.04 can't access database key in user home when folder/key file is user r/w only

### ISSUE THREAD

**Issue by mark-harsch** [keepassxreboot/keepassxc#4821]
## Overview
KeepassXC 2.5.4 issues following error message when trying to select a key file:
`Could not read the contents of .keepasssecret
Error opening directory '/home/<user>/.keepasssecret':
Permission denied`
Permission that KeepassXC is allowed to access the home folder is set in the global permission settings.

## Steps to Reproduce
Prerequisite: Have an existing database and key file for that data base
1. Create a hidden folder in user home with user only drwx permissions
2. Place a key file in the folder with user only rw permissions
3. Try to select the key file in database opening dialog

## Expected Behavior
One can use a key file located in a user only accessible hidden folder

## Actual Behavior
Error message prevents me to select the file

## Context
With non Snap ("bare-metal") KeepassXC this is no issue.

KeePassXC - Version 2.5.4
Revision: dcca5aa
Distribution: Snap

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux (Ubuntu 20.04)
Desktop Env: Gnome
Windowing System: Wayland

**Comment by droidmonkey** [comment]
Limitation of snaps, not our program. You cannot access "dot-files" from a snap.

**Comment by mark-harsch** [comment]
Thanks, didn't know that. Sorry for bothering you.
