### ISSUE TITLE
Linux and Windows: main window persistently shows the name of a particular entry that is not selected

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [keepassxreboot/keepassxc#4824]
## Overview

On both Linux and Windows, the main KeePassXC window (the database window) persistently shows the name of a particular entry that is not selected. I do not know how long this has been happening; I've noticed it only just now. The problem survives a restart of the application.

## Steps to Reproduce
On my computers - one Linux, one Windows - simply opening the main window (having entered the password) suffices.

## Expected Behavior
If I have an entry selected, then that entry should show in the titlebar. If I have no entry selected, then no entry name should show in the titlebar.

## Actual Behavior
See image (from Windows):
![image](https://user-images.githubusercontent.com/47056543/83899835-010c6300-a751-11ea-9371-06f0878d5451.png)

## Context

[NOTE]: # ( Paste debug info from Help → About here )
From the Windows version of the program:
```
KeePassXC - Version 2.5.4
Revision: c023bf9

Qt 5.14.2
Debugging mode is disabled.

Operating system: Windows 10 Version 1909
CPU architecture: x86_64
Kernel: winnt 10.0.18363

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.5
```

Operating System: Windows and Linux
Desktop Env: Cinnamon (on Linux)
Windowing System: X11 (on Linux)

**Comment by droidmonkey** [comment]
That is not the name of the entry, that is the name of your database. Go into Database settings and change the name.

**Comment by LinuxOnTheDesktop** [comment]
Apologies! Perhaps though prepending `[Database:] ` to the titlebar string might be an idea.

**Comment by droidmonkey** [comment]
Not going to do that
