### ISSUE TITLE
Password generator should display length of candidate password/phrase

### ISSUE THREAD

**Issue by tomhundt** [keepassxreboot/keepassxc#4828]
## Summary
**Make the Generate Password dialog display a running count of characters in the password or passphrase displayed.**  Currently, it displays a running entropy count -- the character count could be displayed next to this.  This would be useful anytime one edits the generated/suggested string.

[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
## Context and Motivation
Many websites have minimum and maximum limits on the number of characters a password is allowed to have.

For example, I was just changing my password on Southwest, and they want it to be between 8 and 16 characters long:
![southwest-password-rules](https://user-images.githubusercontent.com/12475662/83952068-028a6980-a7eb-11ea-9863-87c6f25dc6a5.png)

Yes, the password generator lets you specify a length, but that's just a starting point.  The candidate password can then be edited (for example, to add a punctuation mark – many sites limit the ones allowed so it's not helpful to use the built-in – and it's different for every one).  Often it's quicker just to type a couple of keys than set up the Advanced option's exclusion list.

What I usually do is generate a passphrase, and then edit it to include some "noise" characters  to make it resistant to dictionary attacks.  Often, I'm over the limit and have to go back and forth, trimming it down and copying/pasting again.  It's this back-and-forth that the proposed feature would make unnecessary.

## Examples (Mock-ups)
[NOTE]: # ( Show us a picture or mock-up of your proposal )
<img width="624" alt="password-mock" src="https://user-images.githubusercontent.com/12475662/83952247-59dd0980-a7ec-11ea-8090-3e6b6c332aae.png">

<img width="624" alt="passphrase-mock" src="https://user-images.githubusercontent.com/12475662/83952249-5d709080-a7ec-11ea-96f5-aabf77f432b1.png">

**Comment by droidmonkey** [comment]
Good idea

**Comment by droidmonkey** [comment]
Length is already on password, it has been added to passphrase generator for 2.7.0

**Comment by ygoe** [comment]
@droidmonkey Can't see it here for passwords in v2.7.6. Was it removed again? I came here to suggest adding it. It's also a bit hidden for passphrases, after all the config inputs. I would have suggested the same screen layout as in the mocks above. Right beside the entropy, that's the perfect place for it.
