### ISSUE TITLE
Passphrase generator doesn't update Password Quality, Entropy in realtime

### ISSUE THREAD

**Issue by tomhundt** [keepassxreboot/keepassxc#4829]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
In the Generate Password dialog, the Password generator shows the current password quality and entropy values as one edits the string.  In contrast, the Passphrase generator does not update these as the string is edited; they retain the same value as when the passphrase was first generated.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Bring up the Generate Password dialog (e.g., by clicking the dice icon, or Tools > Password Generator). 
2. Go to the Password tab.  It will present you with a string.  (Mine is set to length 16 with most of the Character Types enabled, so usually it's something like `J"rh.u%hG[mQ_d7g`.)  In the below example I have the Advanced button clicked:

<img width="624" alt="generate pw" src="https://user-images.githubusercontent.com/12475662/83953019-e807be80-a7f1-11ea-96c3-7f7339cca4c0.png">

3. Note the values of _Password Quality_ (for the above, "Excellent") and _Entropy_ (for the above, 105.12 bit).
4. Copy the password.
5. Click on the Passphrase tab.
6. Set the word count to 2, which should give you a "Poor" quality password with low entropy.
<img width="624" alt="generate pp" src="https://user-images.githubusercontent.com/12475662/83953064-256c4c00-a7f2-11ea-8df8-204a45fdc8a4.png">

7. Select the entire passphrase and paste the password from Step 4 in.  Note the values of _Password Quality_ and _Entropy_ don't change:
<img width="624" alt="pasted pw" src="https://user-images.githubusercontent.com/12475662/83953070-3917b280-a7f2-11ea-8434-6ab24ad123e4.png">

Type some characters.  Note the values still don't change:
<img width="624" alt="pasted and edited pw" src="https://user-images.githubusercontent.com/12475662/83953078-45037480-a7f2-11ea-95c8-1b9704f709d3.png">

8. Start from scratch with a new passphrase and edit it.  Still the values don't change.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
The passphrase tab should work the way the Password one does, namely: **_Password Quality_ and _Entropy_ should update whenever the passphrase string changes.**

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
_Password Quality_ and _Entropy_ don't update when the passphrase string changes.

## Context
[NOTE]: # ( Give us any additional information you may have. )
Note that there are two instances of the Generate Password dialog: one attached to a database entry (comes up when you click the dice icon at the end of the password field, and featuring an Apply Password button), and another that is "standalone" (comes up when you click the die in the toolbar or use Tools > Password Generator).

[NOTE]: # ( Paste debug info from Help → About here )
```KeePassXC - Version 2.6.0-snapshot
Build Type: Snapshot
Revision: a91358e

Qt 5.14.1
Debugging mode is disabled.

Operating system: macOS 10.15
CPU architecture: x86_64
Kernel: darwin 19.5.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
 libgcrypt 1.8.5```

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows/Linux/macOS
Desktop Env: Gnome/KDE/XFCE/Mate/Cinnamon
Windowing System: X11/Wayland

**Comment by phoerious** [comment]
You have to have password selected when editing manually, not passphrase. The passphrase calculation is based on the size of the word list.

**Comment by droidmonkey** [comment]
This is a duplicate
