### ISSUE TITLE
"Automatically save after every change" fails if file is reverted while open

### ISSUE THREAD

**Issue by l0b0** [keepassxreboot/keepassxc#4831]
## Overview

It looks like this functionality depends on the state of the file.

## Steps to Reproduce

1. Unlock a database.
2. Edit a field in an existing entry.
3. Click "OK".
4. `git checkout` the database file in a terminal to revert it to the state at which it was unlocked in step 1.
1. Edit a field in an existing entry.
3. Click "OK".

## Expected Behavior

The database should be saved *immediately* after clicking OK the second time.

## Actual Behavior

The "Save database" icon stays enabled and there is an asterisk after the database name in the window title.

## Context

KeePassXC - Version 2.4.3
Revision: 5d6ef0c

Qt 5.12.8
Debugging mode is disabled.

Operating system: Ubuntu 20.04 LTS
CPU architecture: x86_64
Kernel: linux 5.4.0-33-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (only unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.5

Operating System: Ubuntu Linux
Desktop Env: Gnome
Windowing System: X11

**Comment by droidmonkey** [comment]
You are on a very old version of KeePassXC. If you can replicate your issue on a develop snapshot I'll reopen. https://snapshot.keepassxc.org
