### ISSUE TITLE
Applications settings lost after moving from stable to git

### ISSUE THREAD

**Issue by yan12125** [keepassxreboot/keepassxc#4835]
## Overview
With recent git commits, the configuration file is moved from `~/.config/keepassxc/keepassxc.ini` to `~/.config/KeePassXC/keepassxc.ini` (changed cases), but there is no migration path. As a result, application settings are lost.

~I didn't run git bisect, but I believe the cause is https://github.com/keepassxreboot/keepassxc/pull/4665.~ See https://github.com/keepassxreboot/keepassxc/issues/4835#issuecomment-640573296

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Backup and remove all of ~/{.cache,.config}/{KeePassXC,keepassxc}/*.ini to make sure nothing can interfere
2. Install KeePassXC 2.5.4
3. Change some settings. For example, I enable "Show a system tray icon"
4. Uninstall KeePassXC 2.5.4 and install git. Here I use 1ad0184.

## Expected Behavior
Application settings remain. I can still get a system tray icon.

## Actual Behavior
Application settings are lost. I don't see a system tray icon and the "Show a system tray icon" option is unchecked.

And from strace log, `~/.config/keepassxc/keepassxc.ini` is not consulted:

```
660558 access("/home/yen/.cache/KeePassXC/keepassxc.ini", F_OK) = -1 ENOENT (No such file or directory)
660558 access("/home/yen/.config/KeePassXC/keepassxc.ini", F_OK) = -1 ENOENT (No such file or directory)
660558 statx(AT_FDCWD, "/home/yen/.config/KeePassXC/keepassxc.ini", AT_STATX_SYNC_AS_STAT, STATX_ALL, 0x7ffda8154650) = -1 ENOENT (No such file or directory)
660558 statx(AT_FDCWD, "/home/yen/.config/KeePassXC/keepassxc.ini", AT_STATX_SYNC_AS_STAT, STATX_ALL, 0x7ffda81545f0) = -1 ENOENT (No such file or directory)
660558 access("/home/yen/.cache/KeePassXC/keepassxc.ini", F_OK) = -1 ENOENT (No such file or directory)
660558 statx(AT_FDCWD, "/home/yen/.cache/KeePassXC/keepassxc.ini", AT_STATX_SYNC_AS_STAT, STATX_ALL, 0x7ffda8154650) = -1 ENOENT (No such file or directory)
660558 statx(AT_FDCWD, "/home/yen/.cache/KeePassXC/keepassxc.ini", AT_STATX_SYNC_AS_STAT, STATX_ALL, 0x7ffda81545f0) = -1 ENOENT (No such file or directory)
660558 access("/home/yen/.config/KeePassXC/keepassxc.ini", F_OK) = -1 ENOENT (No such file or directory)
660558 openat(AT_FDCWD, "/home/yen/.config/KeePassXC/keepassxc.ini.lock", O_RDWR|O_CREAT|O_EXCL|O_CLOEXEC, 0666) = 18
660558 access("/home/yen/.config/KeePassXC/keepassxc.ini", F_OK) = -1 ENOENT (No such file or directory)
660558 statx(AT_FDCWD, "/home/yen/.config/KeePassXC/keepassxc.ini", AT_STATX_SYNC_AS_STAT, STATX_ALL, 0x7ffda81545b0) = -1 ENOENT (No such file or directory)
660558 access("/home/yen/.config/KeePassXC/keepassxc.ini", F_OK) = -1 ENOENT (No such file or directory)
660558 statx(AT_FDCWD, "/home/yen/.config/KeePassXC/keepassxc.ini", AT_STATX_SYNC_AS_STAT, STATX_ALL, 0x7ffda8154510) = -1 ENOENT (No such file or directory)
660558 statx(AT_FDCWD, "/home/yen/.config/KeePassXC/keepassxc.ini", AT_STATX_SYNC_AS_STAT|AT_SYMLINK_NOFOLLOW, STATX_ALL, 0x7ffda8154500) = -1 ENOENT (No such file or directory)
660558 linkat(AT_FDCWD, "/proc/self/fd/19", AT_FDCWD, "/home/yen/.config/KeePassXC/keepassxc.ini", AT_SYMLINK_FOLLOW) = 0
660558 statx(AT_FDCWD, "/home/yen/.config/KeePassXC/keepassxc.ini", AT_STATX_SYNC_AS_STAT, STATX_ALL, {stx_mask=STATX_ALL, stx_attributes=0, stx_mode=S_IFREG|0644, stx_size=26, ...}) = 0
660558 statx(AT_FDCWD, "/home/yen/.config/KeePassXC/keepassxc.ini", AT_STATX_SYNC_AS_STAT, STATX_ALL, {stx_mask=STATX_ALL, stx_attributes=0, stx_mode=S_IFREG|0644, stx_size=26, ...}) = 0
660558 access("/home/yen/.config/KeePassXC/keepassxc.ini", R_OK) = 0
660558 access("/home/yen/.config/KeePassXC/keepassxc.ini", W_OK) = 0
660558 access("/home/yen/.config/KeePassXC/keepassxc.ini", X_OK) = -1 EACCES (Permission denied)
660558 chmod("/home/yen/.config/KeePassXC/keepassxc.ini", 0644) = 0
660558 unlink("/home/yen/.config/KeePassXC/keepassxc.ini.lock") = 0
660558 access("/home/yen/.cache/KeePassXC/keepassxc.ini", F_OK) = -1 ENOENT (No such file or directory)
660558 statx(AT_FDCWD, "/home/yen/.cache/KeePassXC/keepassxc.ini", AT_STATX_SYNC_AS_STAT, STATX_ALL, 0x7ffda8154680) = -1 ENOENT (No such file or directory)
660558 statx(AT_FDCWD, "/home/yen/.cache/KeePassXC/keepassxc.ini", AT_STATX_SYNC_AS_STAT, STATX_ALL, 0x7ffda8154620) = -1 ENOENT (No such file or directory)
```

## Context

KeePassXC - Version 2.6.0-snapshot
Build Type: Snapshot
Revision: 1ad0184

Qt 5.15.0
Debugging mode is disabled.

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 5.6.15-arch1-1

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.5

Operating System: Arch Linux
Desktop Env: LXQt
Windowing System: X11
Package sources: the stable version from [official Arch package](https://www.archlinux.org/packages/community/x86_64/keepassxc/) and the git version from [AUR](https://aur.archlinux.org/packages/keepassxc-git)
Filesystem: ext4, case-sensitive

**Comment by phoerious** [comment]
I wonder why Qt is capitalising the folder name all of a sudden. This is pretty inconsistent on their side.

**Comment by yan12125** [comment]
I think I found the actual cause. Here are some commits in keepassxc related to case changes (older to newer)

1. 6339d61419e70bb9c3cf44caa9119166c0440fb4 That commit changes the application name from `keepassxc` to `KeePassXC`.
2. 596d2cf425c3c8495b4c4a58c61798afe9fdd536 Before that commit, the configuration path uses hard-coded folder name `/keepassxc/` [1]. After that commit, `QStandardPaths::AppConfigLocation` is used, and the latter uses the application name as the folder name.
3. 2073f2ddc30f6922eda89ee3c66e80f9cb426859 Before that commit, the first call to `Config::instance()` happens in the constructor of `Application` in `src/gui/Application.cpp` [2], which is before `setApplicationName` in `src/main.cpp`. At that time, the application name is not set and thus Qt uses the binary name [3], which is `keepassxc` on Linux.

Overall, the intended config path is now `~/.config/KeePassXC/keepassxc.ini`.

[1] https://github.com/keepassxreboot/keepassxc/commit/596d2cf425c3c8495b4c4a58c61798afe9fdd536#diff-461928dbf0b7b4c50bab629bfe990c75L155
[2] https://github.com/keepassxreboot/keepassxc/commit/2073f2ddc30f6922eda89ee3c66e80f9cb426859#diff-3b26d22744b00bff24a5e19c5acc3542L71
[3] https://doc.qt.io/qt-5/qcoreapplication.html#applicationName-prop

**Comment by droidmonkey** [comment]
This should be fixed in the beta.

**Comment by phoerious** [comment]
Shall we stick with lowercase keepassxc? I think KeePassXC makes sense, but Linux configs tend to be all-lowercase.

**Comment by droidmonkey** [comment]
IMO revert that change and stick with lowercase

**Comment by droidmonkey** [comment]
Yah it's a silly github bug, issues should close with the linked pr
