### ISSUE TITLE
Option to auto-minimize keepassxc window on loss of focus (e.g. when switching (back) to another app)

### ISSUE THREAD

**Issue by Tormen** [keepassxreboot/keepassxc#4836]
## Summary

Help to visually unclutter your desktop(s) by providing an option in preferences/settings: `Hide keepassxc window on deactivation (on loss of focus)`. This should hide the window when activating another application, switching away from the app, either through clicking on another window or by using the task switcher (CMD+TAB on MacOS or ALT+TAB on Windows + Linux).

### Important clarification:

> HIDING in my below text refers to what happens when pressing "CMD+H" on a MacOS while KeepassXC is running and the Application window is focused: The app window vanishes, but the App stays visibly running in the list of running application (the "DOCK" on MacOS and the task switcher evoked by CMD+TAB by default). MacOS distinguishes between /minimizing/ and /hiding/. I refer to /hiding/ under MacOS, because minimize leaves a small screenshot of the keepassxc window in the DOCK beside the running app icon... which would only be annoying. So hide is better, it just "minimizes" the app like Linux and Windows would do when you cick the minimize button on the app-window. 
>
> So I mean auto-minimize under Windows and Linux and auto-hide under MacOS. As all 3 operating systems are equal I changed the title this ticket to auto-minimize (from auto-hide). 

### The Problem:
I can't benefit from the already existing minimize/hide features:
* Using KeepassXC in conjunction with the great keepassxc browser addon does not make it possible to benefit from the already existing "hide when minimize window on copy/open-URL/auto-type" feature.
* The hide to system-tray is irrelevant as you still need to manually trigger the hide, which I would like to avoid.

So for now I need to **manually press CMD+H / hide the app everytime** I went to the keepassxc window, which is what I would like keepassxc to do. Unfortunately on MacOS this cannot be achieved by scripting IMHO, so the app needs to do it.

### Advantage: 
To hide keepassxc once you are not actively working with it makes much sense **as 
keepassxc is an app "living" in between other applications** (like web-browser or login-popups from your vpn ...).

Every app visible, without needed to be visible counts, so help to auto-hide this one :)
And in MacOS only the App can implement this for security reasons, hence I need your help.

## Example Implementation in another app:

I discovered this feature with a calculator (more under CONTEXT), which makes sense as well as a calculator also often "lives" in between apps and the same applies to keepassxc!

The specific MacOS Application I refer to is called "Magic Number 2". It has a preference called "Window mode", with 3 choices:
 * Normal
 * Hide on deactivation (loss of focus)
 * float above others

BUT my focus here lies ONLY on the "Hide on deactivation" option,
which should also (hopefully) make it easier to implement across platforms.

## Context

My specific use case, even though I believe (for above reasons) that this is valuable in general:
KeePassXC is running in the background. I have a shortcut to activate and show the window allowing me to manually search for things or check that the correct URL is in the entry, ...

But today when switching away from the keepassxc window still stays more or less visible, even though you are done.
Here it would be amazing if the keepassxc window hid itself as soon as I switch away the active window - focus (either by clicking on another window, or the task switcher, ...).

This especially makes sense for keepassxc if you have a keyboard shortcut to bring up the KeepassXC Window.
But even without it helps to visually unclutter your desktop(s) in case you are not actively doing something in keepassxc. 

And even though I am using a MacOS, I believe, this should be a handy feature for users across all 3 platforms.

Also: I checked and hope I did not overlook an existing feature and feature-request.

**Comment by droidmonkey** [comment]
We already have hide to system tray on minimize. We also have options to minimize the window on copy, open URL, and auto type. We also fixed the showing of the dock icon when hidden in the system tray (it properly hides now in 2.6.0). I personally don't like this option and would find it annoying in no time, it makes it impossible to switch between keepassxc and another application.

**Comment by Tormen** [comment]
Hi @droidmonkey ,
I know about the options you listed. Unfortunately non of them is able to do what I want:
 * I use Keepassc in conjunction with the browser addon hence I can't benefit from the "minimize window on copy/open-URL/auto-tyuupe.
 * Hide to system-tray is irrelevant as you still need to manually trigger the hide, which I would like to avoid.

About your point of this feature disturbing you: 
I can only speak for MacOS in this case: No. Hiding the window in MacOS makes is super easy and in no way annoyting to switch back to the app! Meaning: The position of the app in the task-swicher is not affected. So hiding keepassxc activates the last app used before keepassxc and Finder if no other app is there. 
If you press CMD+TAB then you can simply switch back to the hidden app (no difference if hidden or not!).
Same goes for clicking on the application icon.
Same goes for using "/usr/bin/open /Applications/KeePassXC.app/".
The only restriction you have: The window to click on in order to activate keepassxc is gone... but thats' to whole point here: To visually unclutter your desktop while not actively using keepasxc.

I hope this was helpful.

**Comment by droidmonkey** [comment]
I think our terminology is not the same. What you describe is the application dropping to the background (still in dock, still in CMD+TAB list, still technically visible). Hiding refers to the window dropping off the dock, being non-visible, and not in CMD+TAB.

**Comment by Tormen** [comment]
Good point! I mean `*hiding* in the sense of pressing CMD+H` (default MacOS keyboard shortcut)!

**Comment by Tormen** [comment]
I added a clarification regarding this to my summary. Thanks for pointing that out @droidmonkey.

So what do you think? Did I make a convincing case? :))

**Comment by droidmonkey** [comment]
It is similar to the option we have to drop to background when copying to the clipboard. I still don't like the idea of the app totally disappearing when losing focus but we can keep this open.

**Comment by Tormen** [comment]
@droidmonkey , thanks for your feedback. 
Yes what I ask for is what this option does just triggered by loss of focus, because in the way I work with keepassxc:
  * I either access keepassxc mainly through the browser addon
   * But when this does not work (e.g. the URL changed) or I need to lookup something, then I summon the keepassxc with a keyboard shortcut assigned to "/usr/bin/open /Applications/KeePassXC.app/". This shows the keepassxc window. When I am done looking things up or editing things, I use often another keyboard shortcut to go where I need to go next or CMD+TAB or similar to switch back to the app where I was. 

So for me when keepassxc loses focus I don't need it anymore, so it should drop to background / minimize (or "hide" on a MacOS)... 

But as pointed out, it does NOT dissappear totally, just the window is minimised. Under a Mac you still see it in the DOCK and can click on it, or use CMD+TAB to get right back to it!

For now I always end up manually cleaning up the "dangeling" keepassxc window.

I would be interested to see if there is different (more efficient) way to adapt my keyboard-shortcut based way of using keepassxc to look things up / edit things, that would *not* benefit from this feature.

With this I'll rest my case.

**Comment by droidmonkey** [comment]
I am against adding this feature, it seems like a usability nightmare.
