### ISSUE TITLE
KeepassXC tray icon doesn't look good

### ISSUE THREAD

**Issue by popxunga** [keepassxreboot/keepassxc#4837]
## Overview
While testing 2.6.0 beta1 the KeepassXC tray icon doesn't look good.

## Steps to Reproduce
Activate the "Show a system tray icon" in KeepassXC settings (General-> User Interface):
![image](https://user-images.githubusercontent.com/37672088/84044613-b9c7e180-a99f-11ea-8578-48778dd03785.png)

## Expected Behavior
This is how it looks on 2.5.4:
![image](https://user-images.githubusercontent.com/37672088/84038713-2ccd5a00-a998-11ea-8b4f-32a36ca96e2b.png)

## Actual Behavior
Systray icon looks ugly no matter what icon type is selected.

This is how it looks with "Tray icon type" set with "Monochrome light":
![image](https://user-images.githubusercontent.com/37672088/84038856-57b7ae00-a998-11ea-9758-39ed8eab3cde.png)

This is how it looks with "Tray icon type" set with "Colorful":
![image](https://user-images.githubusercontent.com/37672088/84044516-98ff8c00-a99f-11ea-80a9-141e0775f557.png)

With Adwaita-Dark selected as system theme and the "Tray icon type" set with "Monochrome dark", the KeepassXC icon cannot be seen in the system tray.

## Context
None.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.0-snapshot
Build Type: Snapshot

Qt 5.9.7
Debugging mode is disabled.

Operating system: Red Hat Enterprise Linux Workstation 7.8 (Maipo)
CPU architecture: x86_64
Kernel: linux 3.10.0-1127.8.2.el7.x86_64

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.5

[NOTE]: # ( Pick choices based on your environment )
Operating System: RHEL 7.8
Desktop Env: Gnome3 (gnome-shell-3.28.3-24.el7.x86_64, gnome-shell-extension-top-icons-3.28.1-11.el7.noarch)
Windowing System: X11

In addition I confirm the issue described in #4835 as well.

Thanks.

**Comment by popxunga** [comment]
Done !

**Comment by droidmonkey** [comment]
So this could be a Qt problem with render SVG's or a problem with the RHEL taskbar in rendering SVG's.

**Comment by popxunga** [comment]
Hi @droidmonkey 

The problem is that the top-icons gnome extension provided by gnome-shell-extension-top-icons-3.28.1-11.el7.noarch does not render the KeepassXC svg icon properly.

I've built the same KeepassXC code version on CentOS 8 where I have gnome-shell-extension-top-icons-3.32.1-10.el8.noarch and the icon renders fine.

It renders fine on EL7.x as well after disable the system default top-icons extension and then use [this](https://github.com/zhangkaizhao/gnome-shell-extension-tray-icons) extension for example.

Thanks.

**Comment by droidmonkey** [comment]
Thanks for checking in on this. Closing the issue since it's a bug in the top icons extension.
