### ISSUE TITLE
2.6.0-beta1 doesn't use system icons and colors anymore

### ISSUE THREAD

**Issue by Dunedan** [keepassxreboot/keepassxc#4838]
## Overview

KeepassXC 2.6.0-beta1 doesn't use system icons and colors anymore. That's annoying as it breaks the "visual conformity" of applications running in the desktop environment and prevents users from choosing their own preferred icons and colors.

Aside from the underlying problem of not using the system provided icons and colors anymore, the now used colors might be especially problematic for certain visual impacted people (like with red-green color blindness).

## Steps to Reproduce

1. Install KeepassXC 2.6.0-beta1 under Debian/unstable
2. Start it while running KDE.

## Expected Behavior

KeepassXC uses the system styles, icons sets and colors (as it did before).

## Actual Behavior

KeepassXC uses a greenish color style now and it's icons are a completely different icon set.

## Context

KeePassXC - Version 2.6.0-beta1
Revision: e5b0219
Operating System: Debian/unstable
Desktop Env: KDE
Windowing System: X11

**Comment by phoerious** [comment]
This is totally intended. The system icons are almost always incomplete and often have different semantics, causing inconsistent visuals and confusing UX.

**Comment by Dunedan** [comment]
> The colours of the new theme are carefully adjusted to accommodate to accessibility guidelines, but if you don't like it, you can always switch back to "Classic".

Thanks for pointing that out. While I did look for such an option in the settings I failed to find it on first try. I found it now under "Tools" -> "Settings" -> "General" -> "Basic Settings" -> "User Interface" -> "Application Theme".

**Comment by droidmonkey** [comment]
@phoerious can we make classic mode still use phantom? It will pickup the system theme and not be ugly Qt.

**Comment by phoerious** [comment]
No, what's the point of that? Classic is for those who want their native system theme, which even looks somewhat alright on Breeze (pretty ugly everywhere else).

**Comment by droidmonkey** [comment]
The point would be to allow for our "new look" with the OS colors

**Comment by phoerious** [comment]
That wouldn't be classic, that'd be "system palette" or so. But Qt palettes only marginally resemble what the system colours really are. Almost all widgets are completely redrawn by the platform plugin and don't even consider the platform palette.

**Comment by droidmonkey** [comment]
That's true, carry on!

**Comment by idontusenumbers** [comment]
I can't find the 'classic' theme on macosx.

![image](https://user-images.githubusercontent.com/1175031/87207941-cc04aa80-c2d2-11ea-85f7-84b4cfbb44da.png)

I much prefer the system/native look and feel. It's much better looking and much more usable. It seems the new look and feel is also quite buggy; many dialog boxes come up filled with black.

**Comment by droidmonkey** [comment]
Did you look in the view menu?

**Comment by idontusenumbers** [comment]
I looked three times for a view menu and didn't find it any of those times, although I see it now. I don't know why I didnt see it earlier. For what it's worth and in my defence, it's not in the right place.

![image](https://user-images.githubusercontent.com/1175031/87209376-3ae40280-c2d7-11ea-8e90-85ba285ca1a8.png)
![image](https://user-images.githubusercontent.com/1175031/87209379-3e778980-c2d7-11ea-8408-7889a837a525.png)
![image](https://user-images.githubusercontent.com/1175031/87209384-41727a00-c2d7-11ea-9c85-a1d2bf844947.png)
![image](https://user-images.githubusercontent.com/1175031/87209334-1851e980-c2d7-11ea-8893-a37718f97369.png)
![image](https://user-images.githubusercontent.com/1175031/87209340-1ee06100-c2d7-11ea-8119-9c0a10a3eeb1.png)
![image](https://user-images.githubusercontent.com/1175031/87209345-230c7e80-c2d7-11ea-9db8-f8640edeb98e.png)
![image](https://user-images.githubusercontent.com/1175031/87209352-27d13280-c2d7-11ea-94e3-03945331a989.png)
![image](https://user-images.githubusercontent.com/1175031/87209399-52bb8680-c2d7-11ea-9e31-81facb2b6897.png)
![image](https://user-images.githubusercontent.com/1175031/87209405-56e7a400-c2d7-11ea-9a5c-54fc445ee541.png)
![image](https://user-images.githubusercontent.com/1175031/87209410-5b13c180-c2d7-11ea-859b-5fa439dddab7.png)

**Comment by GeorgiKarapetrov** [comment]
OS: Arch Linux
Which icon-set should I install to get the icons and ideally the tray icon to display.

Screenshot - text under icons:
[<img src="https://imgur.com/uChBnSO.png">](https://imgur.com/)

**Comment by phoerious** [comment]
Please read the pinned issues. You may also want to disable text besides icons.
