### ISSUE TITLE
Option to generate username

### ISSUE THREAD

**Issue by mrsoso13** [keepassxreboot/keepassxc#4839]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
Be able to generate a username.

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )
Make a new button username generator
![image](https://user-images.githubusercontent.com/66329552/84145288-e93b2480-aa59-11ea-81ea-fdda832d0c85.png)

**Comment by droidmonkey** [comment]
We have decided not to include that specific feature separate from the password generator. Use the Passphrase generator to make a username.

**Comment by aaaawwWWWwwwwWWW** [comment]
@droidmonkey why was that decision made? it is bad usability having to copy/paste to get an automatic generated username.

**Comment by phoerious** [comment]
It's a niche feature.
