### ISSUE TITLE
Keepass read only via Gnome google drive 

### ISSUE THREAD

**Issue by yegnal** [keepassxreboot/keepassxc#4840]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Ubuntu 20.04
2. Add google account to gnome via settings
3. Google drive appears in Nautilus

## Expected Behavior
[NOTE]: # ( Keepass database shouldn't be 'READ ONLY' )
Keepass database shouldn't be 'READ ONLY'

## Actual Behavior
[NOTE]: # ( Keepass database is 'READ ONLY' )
Keepass database is 'READ ONLY'

## Context
[NOTE]: # ( Works fine with DropBox, but they (Dropbox) limit the number of devices now so I'm moving to Google drive. )
Works fine with DropBox, but they (Dropbox) limit the number of devices now so I'm moving to Google drive.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION 2.4.3
Revision: REVISION  5d6ef0c

[NOTE]: # ( Pick choices based on your environment )
Operating System: Ubuntu 20.04
Desktop Env: Gnome
Windowing System: X11/?

**Comment by droidmonkey** [comment]
Fixed in 2.6.0
