### ISSUE TITLE
KeePassXC Secret Service not showing notifications?

### ISSUE THREAD

**Issue by piramiday** [keepassxreboot/keepassxc#4845]
## Overview
I'm experimenting with KeePassXC's Secret Service, and I'd like to get some kind of notification whenever something happens.
I have tried switching a flag that seems intuitively linked to what I'd like to accomplish, but nothing changes.

I'm not sure whether I have misconfigured something, or the feature does not work...
any help is appreciated.

## Steps to Reproduce
1. browse to `Tools > Settings > Secret Service Integration`,
2. under General, select `Show notification when credentials are requested`,
3. engage the Secret Service e.g. `secret-tool lookup attribute value`.

## Expected Behavior
I get a notification in some form -- something happens on my desktop showing me that someone (e.g. `secret-tool`) accessed something (e.g. `attribute value`).

## Actual Behavior
the lookup works, but without notifications.

## Context
```
KeePassXC - Version 2.5.4
Revision: dcca5aa

Qt 5.9.5
Debugging mode is disabled.

Operating system: Linux Mint 19.3
CPU architecture: x86_64
Kernel: linux 5.3.0-53-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.1
```

**Comment by piramiday** [comment]
oh, I see -- KeePassXC **does not show notifications**, but rather _traybar icon tooltips_, and I need to enable the tray icon to see those!

![Screenshot_20191211_125346](https://user-images.githubusercontent.com/48775554/84332582-224ec400-ab42-11ea-9f65-773e08f96da3.png)

now I understand what was the point of #4073.

**Comment by Aetf** [comment]
I think it's safe to close this as a duplicate to #4073.
