### ISSUE TITLE
Take captilization from the wordlist as one option in the passphrase generator

### ISSUE THREAD

**Issue by ospalh** [keepassxreboot/keepassxc#4849]
## Summary

When users uses their own wordlists to generate passphrases, one option should be that words that are capitalized in the list should stay that way, and words that are not capitalized there should stay that way, too.

## Examples
When using a German word list, the nouns should be capitalized and other words should use lower case. For example i got »rufen vorschau absahnen kutte« as a suggested four word German passphrase. It should have been »rufen Vorschau absahnen Kutte«, as »Vorschau« and »Kutte« are (always) nouns and have to be capitalized, the others are (usually) verbs and should be lower case.

## Context

The idea is that passphrases should be easy to remember. When German speakers encounter a noun, they assume that it should be capitalized, as that is the German spelling rule. When the noun is written with a lower case letter, that is an extra bit of information to keep in mind, making the passphrase (slightly) harder to remember.
I think the “as is” option could take the place of the current “lowercase”, or it could be added as another option.

I am aware of issue #4417, but think this is different, as this would bring the passphrase closer to the standard spelling then the current version, not remove it from it.

**Comment by droidmonkey** [comment]
This is hyper specific and most likely will never be implemented. You can manually capitalize your passphrase prior to accepting it.
