### ISSUE TITLE
Tab to search results ? 

### ISSUE THREAD

**Issue by iammichiel** [keepassxreboot/keepassxc#4850]
## Overview
Hi, 

First of all, thanks to all contributors for all the hard work on this project. I've been using for a couple of years and could definitely not go back :)

So that being sad, I have acquired a few habits using this software. I have quite a database 1k+ entries and only use the search function to access those. My general workflow is typing in the first letters of the entry and then `tab` twice to go to the result page and `Cmd+b`/`Cmd+v` to copy those to my clipboard. 

I upgraded from version 2.4.x to a 2.5.4 today and this no longer works? When the search field loses focus, it drops its values, resetting the entries. 

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Use the search bar
2. Press `Tab` twice to go to the results panel

## Expected Behavior
The search bar should keep its value and the result panel should be filtered. 

## Actual Behavior
Search bar value resets and search-result panel is reset to the main view.

## Context
KeePassXC - 2.5.4.
Operating System: macOS

**Comment by droidmonkey** [comment]
Fixed in 2.6.0
