### ISSUE TITLE
Tabbing into notes on Entry Edit is broken

### ISSUE THREAD

**Issue by droidmonkey** [keepassxreboot/keepassxc#4852]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
Tab sequencing for editing an entry is slightly broken. Cannot tab into the notes field.

**Comment by phoerious** [comment]
I noticed that too. But it has the correct tab order. Not sure what's going on there.

**Comment by droidmonkey** [comment]
I can't get it to work, very strange.

**Comment by phoerious** [comment]
Yeah, me neither. I tried to fix it, but failed. Random idea: what's the focus behaviour of the field? Is it click-only perhaps?

**Comment by droidmonkey** [comment]
No it's set to strong. Tab focus changing is so broken
