### ISSUE TITLE
Parsing and Perl Errors

### ISSUE THREAD

**Issue by HuckleHubbing** [keepassxreboot/keepassxc#4854]
## Overview
KeepassXC is repeating the same two error messages in syslog. One about an invalid perl operator, and the other about anime.
Everything still works as expected as far as I can tell. But somethin' ain't happy.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Open KeepassXC
2. Run out of shows to watch on Netflix
3. Find yourself reading your syslog

## Expected Behavior
No error messages. Pure clean running like 100% efficient solar energy. An empty syslog is a happy syslog.

## Actual Behavior
Repeated errors about every 10 seconds fillin' up my syslog with noise.

`Jun 13 14:10:34 box org.keepassxc.KeePassXC.desktop[15357]: ../../chromium/third_party/re2/src/re2/re2.cc:846: Invalid RE2: invalid perl operator: (?!
Jun 13 14:10:44 box org.keepassxc.KeePassXC.desktop[15357]: ../../chromium/third_party/re2/src/re2/re2.cc:200: Error parsing '^https?:\/\/([0-9a-z\-]+\.)?(animeland|animenova|animeplus|animetoon|animewow|gamestorrent|goodanime...': invalid perl operator: (?!`

## Context
[NOTE]: # ( Give us any additional information you may have. )
Everything seems to function as expected. I haven't had any issues using KeepassXC.
I was needing to find some messages for another service in the syslog and noticed that 99% of my syslog was filled with keepass messages. The anime* messages really caught my attention. Especially since the word anime doesn't even show up in my Keepass database anywhere.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.3.4 (installed from the Debian repositories)
Revision: 6fe821c
Libraries:
- Qt 5.11.3
- libgcrypt 1.8.4
Operating system: Debian GNU/Linux 10 (buster)
CPU architecture: x86_64
Kernel: linux 4.19.0-9-amd64
Desktop Env: Gnome
Windowing System: X11
Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by HuckleHubbing** [comment]
Actually, I'm seeing these errors occurring even while KeepassXC is not running. I've verified it's not running through the ps command. No sign of it. But I'm still getting the exact same syslog entries every few seconds.

**Comment by droidmonkey** [comment]
This is in no way connected to keepassxc. We don't use perl. It's coming from chromium.
