### ISSUE TITLE
Which columns are shown in Auto-Type Dialog?

### ISSUE THREAD

**Issue by jolange** [keepassxreboot/keepassxc#4857]
## Summary
Document which columns are shown in the Auto-Type Dialog under which circumstances.
Or even better: make it configurable. (related to #1416)

## Context
In most cases, the columns *Group, Title, Username* are shown in the Auto-Type Dialog, but sometimes the *auto-type sequence* is shown. I was not able to figure out under which exact circumstances this is the case. It seems to be related to whether there is a custom sequence configured for at least one matching entry, but that does not seem to be a sufficient condition.

Is this documented somewhere? I searched the usual places without luck, but maybe I missed something.

I personally would like to have the auto-type sequence always shown, because I'd like to check it before auto-typing. Having this configurable would be a plus (related to #1416), but first of all understanding and documenting the current behaviour would be great!

**Comment by droidmonkey** [comment]
It doesn't need to be documented because its transparent to the user. The sequence column shows up when there is an entry with multiple different sequences defined for a particular window. The whole point of window to sequence assignments is that you don't need to verify the sequence, the program does that for you.

**Comment by jolange** [comment]
> It doesn't need to be documented because its transparent to the user. 

For me, as a user (maybe not *the* user?), it is rather confusing. I knew I once had a dialog where I could see the sequence. Now I did not see that any more and thought I misconfigured something, but did not find a setting. Then I thought, I maybe had this behaviour in a self-compiled version and even checked if there was some compile-time option, which I did not find. So I ended up believing that I remembered the old behaviour from keepassx, not keepassxc.

Until I "accidently" came across this behaviour again at some day...

So it would have been helpful to find an explanation for the behaviour somewhere.


> The sequence column shows up when there is an entry with multiple different sequences defined for a particular window title match. The whole point of "window title to sequence" assignments is that you don't need to verify the sequence when you actually use it, the program does that for you.

It is not only about "window title to sequence" assignments, but you can also set an auto-type sequence for the whole entry. And the sequence column can definitely also show up if there are two different entries matching the window title. In that case, does it also only show up if the sequences of the different entries differ? That would not make too much sense to me.

In my opinion is very useful to always display the sequence that will be typed, because I am very often unsure if the sequence I once set is still the right one:
- Most websites use (or have used) a username-field and a password-field in one form. So you want {USERNAME}{TAB}{PASSWORD}.
- But I recently noticed several websites moving to a login where you first enter your username, click a button or press enter, and then on a new page enter the password separately. In some cases the username is saved for the next login and you directly arrive on a page where you only enter the password.
- Each time I come across this "modern" version, I wonder if I have (already) configured the right sequence. So I open the database and check it, instead of just hitting enter.

**Comment by droidmonkey** [comment]
No longer necessary after #5864
