### ISSUE TITLE
No such signal BrowserService::activeDatabaseChanged()

### ISSUE THREAD

**Issue by yan12125** [keepassxreboot/keepassxc#4858]
## Overview

Whenever I need to confirm access requests from the browser to KeePassXC from the following dialog

![image](https://user-images.githubusercontent.com/1937689/84594595-f440eb00-ae85-11ea-957b-99d5faaa14ba.png)

A warning message appears in my terminal:
```
QObject::connect: No such signal BrowserService::activeDatabaseChanged()
QObject::connect:  (receiver name: 'BrowserAccessControlDialog')
```

Seems the warning is from

https://github.com/keepassxreboot/keepassxc/blob/92a7fe33bd902cf292d31cae673eb4ba04ec4c97/src/browser/BrowserService.cpp#L758

and is related to https://github.com/keepassxreboot/keepassxc/pull/4660.

## Steps to Reproduce
1. Enable browser integration and enable keepassxc-proxy from the browser. Here I use Firefox but I don't think the browser type matters.
2. Attempt to log in to some website

## Expected Behavior
It works.

## Actual Behavior
It works, but with a warning message in the terminal (see the Overview section for the message).

## Context
KeePassXC - Version 2.6.0-snapshot
Build Type: Snapshot
Revision: c68f487

Qt 5.15.0
Debugging mode is disabled.

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 5.7.2-arch1-1

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.5

I compiled keepassxc by replacing `branch=develop` with `branch=release/2.6.0` in [the AUR script](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=keepassxc-git).

Operating System: Arch Linux
Desktop Env: LXQt
Windowing System: X11
Browser: Firefox 77.0.1
Browser addon: KeepassXC-Browser 1.6.3

**Comment by droidmonkey** [comment]
There is a really no reason for us to care about the active database, you cannot change it when this dialog is shown since it is modal.

**Comment by yan12125** [comment]
Thanks for fixing this! Closing manually for the same reason as #4835.
