### ISSUE TITLE
Add Documentation Describing the main window to the Help

### ISSUE THREAD

**Issue by BrerRabbit999** [keepassxreboot/keepassxc#4859]
Main window lists groups, entries, etc. and has many features that are not clear to a new user.  One feature that puzzles me is that some entries are greyed out.  I cannot figure out why.

**Comment by droidmonkey** [comment]
We have documentation in the help menu. Grayed out entries are probably references to other entries. Our documentation is being overhauled for 2.6.0

**Comment by BrerRabbit999** [comment]
I had reviewed the documentation before writing this request and I reviewed it again, and I still have not found any illustration of the main window or description of the elements contained therein.  If they are there, could you please point out to me exactly where I should look?

**Comment by droidmonkey** [comment]
I will write a section for that in the new documentation set

**Comment by BrerRabbit999** [comment]
Thank you very much.
