### ISSUE TITLE
Allow in-memory protection for additional attributes

### ISSUE THREAD

**Issue by SaltwaterC** [keepassxreboot/keepassxc#486]
Hi. This functionality exists in KeePass, however it doesn't exist in KeePassXC. While a protected attribute is handled by KeePassXC (read / modify), KeePassXC is unable to enable / disable this functionality or create new attributes which have this functionality.

Basically, this is how KeePass is doing this on the UI side:

![Imgur](http://i.imgur.com/beYxAqZ.png)
![Imgur](http://i.imgur.com/mUwk9Bs.png)
![Imgur](http://i.imgur.com/HRcNrGb.png)
![Imgur](http://i.imgur.com/6W44wgd.png)

## Expected Behavior

Have a checkbox to enable / disable the in-memory protection. Hide the value when the box is ticked. Allow the user to view this hidden information.

## Current Behavior

The UI doesn't provide the possibility to enable / disable the protection. A protected attribute value created by KeePass looks the same from the user's perspective in KeePassXC instead of being hidden from view.

## Possible Solution

By looking at the XML schema of the KDBX 3.1 format, I see all the XML nodes holding attributes are children of Entry. Notes, Password, Title, URL, and UserName have special meaning by convention rather than enforced by the schema. The Password attribute already has this protection turned on by default. I guess the code handling this may be reused which means at least half the solution is already there. Haven't checked whether there's support for disabling the protection as my C++ is bit rubbish.

I think the biggest challenge really is to redesign the UI. A column of checkboxes may avoid having a modal at the expense of more cluttering. A button for viewing the protected input may be provided  the same way one is available for the Password attribute if the feature is turned on. TBH, I don't know whether avoiding having a modal is best.

## Context

This issue is about interoperability with KeePass (KDBX 3.1) created databases. Running KeePass with Wine / Mono when the OS is not Windows is a joke. Not a good one either.

The added benefit of having the value hidden from view is also an extra.

## Your Environment

KeePassXC 2.1.3

**Comment by droidmonkey** [comment]
This was implemented in the develop branch already, thanks for the exception writeup though!

See #220

**Comment by SaltwaterC** [comment]
Brilliant. Cheers!

**Comment by phoerious** [comment]
Actually, we do not really have any in-memory protection. Those fields are saved as a Salsa20-encrypted stream inside the AES container, but are loaded in plain text to memory. We do, however, prevent against memory dumps of the whole program. I'm not sure, though, if this also applies to swap space.

**Comment by SaltwaterC** [comment]
I was using the same terminology as KeePass. Thanks for clarifying. I wasn't sure whether the Salsa20 stream is actually protected.

Out of curiosity, when you say "plain text to memory" are they being held as the base64 segments of the Salsa20 stream or KeePassXC decrypts them beforehand?

**Comment by phoerious** [comment]
KeePassXC decrypts them while parsing the file.
If I'm not mistaken, then what KeePass does is it keeps the Salsa20 cipher text and only decrypts them on-demand with the key being stored in a protected memory area. However, this "protected" are is only as secure as the operating system can make it. On most platforms it simply means that area cannot be swapped out.

**Comment by droidmonkey** [comment]
My thoughts are not to waste time with in memory encryption until​ we get a functional integration with TPM chips. Otherwise you are just playing memory shell games cause you gotta store the key somewhere. In the develop branch right now we have enabled DEP and ASLR for Windows builds which helps a lot to prevent against memory grabs.

**Comment by rugk** [comment]
This branch is not merged yet, is not it?

**Comment by phoerious** [comment]
We do support inner stream encryption on additional attributes, but we don't do actual in-memory protection.

**Comment by rugk** [comment]
Hmm, I better open a new issue.
