### ISSUE TITLE
Issue with opening database after idle time

### ISSUE THREAD

**Issue by mbilas** [keepassxreboot/keepassxc#4860]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
Sometimes I cannot open a locked database after idle time. When a password is typed, the indication bar below the Hardware Key drop down is still showing (I don't use a hardware key). It blocks a database unlocking process.

![csrss_vLKcJNflyF](https://user-images.githubusercontent.com/30262938/84646205-05c7d880-af02-11ea-9d41-9c3fa1abba97.png)

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Lock your Windows account (Windows + L)
2. Unlock Windows and open KeePassXC
3. Enter a password, the Hardware Key indication bar is displaying

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
The user should be able to unlock KeePassXC Database

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
The application is frozen, no ways to close the app. Only killing the process from Task Manager.

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.5.4
Revision:  c023bf9

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 10

**Comment by droidmonkey** [comment]
This is fixed in 2.6.0
