### ISSUE TITLE
Quick typing of e.g "asd" results in "aaa"

### ISSUE THREAD

**Issue by simon5738** [keepassxreboot/keepassxc#4861]
When typing any text field,  I am limited how fast I can type. If I'm to fast, this will result in repeating the previous letter.
If I type "asdasdasd"; this can result in "aaaaaaaaa". "qwert" becomes "qqqqt" because it takes me time to bring my index finger from "r" to "t".

Expected behaviour: "asd" resulting in "asd" and not "aaa". 

Notes:
- Other applications don't show this behaviour in Windows with RDP connection. 
- KeePassXC 2.5.4 doesn't show this behaviour in Ubuntu 19.10.

Windows 10,
KeePassXC 2.5.4 
(Remote connected with RDP with Remmina 1.4.6 from Ubuntu 19.10)

**Comment by droidmonkey** [comment]
If anything this would be a Qt bug but certainly not us.

**Comment by simon5738** [comment]
Oke! Thank you for the response. I can created a bug report at Qt: https://bugreports.qt.io/browse/QTBUG-85068

**Comment by simon5738** [comment]
I have discovered the same issue in an other application: Eagle 9.6.0, so it is definitely not you guys.

Thanks anyway!

**Comment by droidmonkey** [comment]
It's actually most likely Rimmina

**Comment by simon5738** [comment]
Not that I have any understanding how RDP and Qt work under the hood but to me it seems to be too specific for Remmina. I see the problem in Eagle (uses also Qt), and Keepassxc but not in Windows' notepad or Firefox (both no Qt). The common factor seems to be Qt in my opinion.. If you can explain why you think its Remmina, please let me know!

**Comment by droidmonkey** [comment]
The common factor is Remmina + Qt. Qt on its own does not exhibit this behavior, it is exhibited through Remmina (based on your report). Since Qt is not aware of Remmina, that I know of, it is unlikely a code bug within Qt. Additionally, typing into Qt windows works flawlessly with VirtualBox, RDP, VNC, and TeamViewer.
