### ISSUE TITLE
KeepassXC freezes in Windows

### ISSUE THREAD

**Issue by lupa18** [keepassxreboot/keepassxc#4862]
## Overview

[NOTE]: # ( Give a BRIEF summary about your problem )

After some time, keepassxc freezes (in windows 10)

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Open a database
2. Change some elements
3. Wait and do other things, after some use and saves, it freezes

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Save and keep your changes safe

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Because KP freezes, you lost your last changes. I lost my facebook access due a TOTP configuration lost. 
Then, you have to open task manager and kill it to get it working again

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.5.4
Revision: c023bf9

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 10 (updated)

**Comment by droidmonkey** [comment]
Fixed in 2.6.0

**Comment by lupa18** [comment]
Where can I find 2.6.0 version? can't see here: https://keepassxc.org/download/#windows

**Comment by droidmonkey** [comment]
Click releases at the top of this page, it's still in beta
