### ISSUE TITLE
Secondary file target to allow multi user workflow with syncthing/onedrive/dropbox

### ISSUE THREAD

**Issue by charsi** [keepassxreboot/keepassxc#4866]
## Summary
It would be great if KeepassXC could add an option to set a secondary file to track for changes. 

## Context
The intention of this feature would be to allow safely using keepass with a file syncing app like syncthing, onedrive etc. in a multi user environment. The secondary file would be inside the sync directory and the main file outside of it. 

Currently you run the risk of losing your changes if the syncing apps downloads a file with remote changes before syncing your changes in. If you have keepassXC running you are covered but if keepassXC is closed at the time you'll likely lose your changes from the last save.

## Examples
Keepass suggests setting up triggers to work around this issue -
https://keepass.info/help/kb/trigger_examples.html#dbsync 

I am proposing this should be built into keepassXC as this is probably a pretty common use case. Teams using a shared keepass store on onedrive etc.

**Comment by phoerious** [comment]
You are not going to lose anything. In the rare case that a conflict happens, your sync client will create a conflict file which you can simply merge into your main database. For more advanced multi-user sharing setups, you can use KeeShare.

**Comment by charsi** [comment]
I am aware about the second file being created. But it is a silent issue. Users normally wouldn't realize anything is amiss until somebody goes to try using one of those lost passwords. 
In larger teams this can be pretty big problem unless a better and looking at the proposed solution of keepass it sounds like this can be improved easily.

**Comment by phoerious** [comment]
The process is completely transparent. Adding more logic would complicate things making everything more fragile instead of safer.

**Comment by charsi** [comment]
The case I have is not for user specific passwords so keeshare is not a good fit. All users should have ability to make changes anywhere.
This feature would not require keepass to be aware of how conflict files are named. Or move any of them around.

The user will just simply save their file wherever they want and keepassXC will write the changes in two places. If the synced file is overwritten by the sync app it KeepassXC will trigger a normal merge into the file with changes from user's local file. Nobody has to look at the conflict files or worry about them anymore.

**Comment by phoerious** [comment]
Your idea will joy work. If a conflict appears, the sync client will save the server version to a new file which KeePassXC will never see.

**Comment by charsi** [comment]
I think you are missing the point here. If a conflict occurs it is true the sync client will save a conflict file which keepass won't see. But it does not matter.
Since the main file user is working with outside of the synced folder keepassXC will detect a mismatch with the sync file and trigger a merge. 
This is detailed a more in the link in the first post (not my idea). Keepass does it with triggers that a user has to manually configure. But this could potentially be automated and offered as a checkbox 'enable secondary file sync'.

**Comment by phoerious** [comment]
Conflicts are rare and easy to solve. Adding all this logic makes the whole process more brittle and complicated. Any situation in which there is no conflict isn't a problem to begin with, so I suggest you just use it as is. And there is no such thing as "enable secondary file sync" without manual intervention as to where and how the sync client is creating conflict files, there is no way this is going to work. You are only creating one more file that needs to be kept in sync with everything without gaining any advantage.

**Comment by charsi** [comment]
I agree this solution adds complication. Urge you to read the "How it works" section above.
With this in place the conflict files can be ignored/discarded. They don't matter and you avoid fixing anything manually.

**Comment by phoerious** [comment]
There is no point. You are just delaying the problem. You can save all your changes to a local database, but the moment KeePassXC needs to sync the changes, your are facing the same problem, so you gained nothing.

**Comment by charsi** [comment]
How am I facing the same problem? 

**Without this solution:**
- You have keep looking for the conflict files to even detect an issue.
- Manually merge in the conflict files to get your changes in the main file.

**With this solution:**
- Sync app overwrites the file. 
- Keepass detects your local copy (outside of sync folder) has changes that aren't in the sync app file.
- Keepass merges your copy in and the sync app sends the changes back up to the server.
User does not have to think about conflicts or do any manual intervention.

**Comment by phoerious** [comment]
In the scenario you described, you will trigger data loss for all clients which are not configured with such an aggressive merge policy.

**Comment by charsi** [comment]
This will need to be used by all users. Up to the users to guarantee that.
From the link above -
> Perform these steps on all PCs that you will sync with Dropbox.

**Comment by phoerious** [comment]
Yeah, not going to implement that. The whole thing would also trigger a cascade of key transformations, which are particularly irritating if your database is secured with a YubiKey.

**Comment by charsi** [comment]
Thanks for your consideration.
