### ISSUE TITLE
URL Field by reference {REF:} is not resolved while comparing URL with website

### ISSUE THREAD

**Issue by 4-FLOSS-Free-Libre-Open-Source-Software** [keepassxreboot/keepassxc#4867]
No matching of Entries using URL Field by reference {REF:} is not resolved while comparing URL with website.
Why? Because you may use multiple Account for single login page. most common work/private.
But while reduce redundancy in database where possible and  for better allowing of changes.

## Expected Behavior
keepassxc-browser should offer filling of entry that uses referenced Field.

## Current Behavior
Any entry with referenced url is not found or offered for login.

## Possible Solution
Consider resolve References in URL field of entries while matching URI

## Steps to Reproduce (for bugs)
1. create a entry.
2. make sure keepassxc-browser lets you login into website
3. duplicate entry and choose for the duplicate entry URL FIELD the original entry URL FIELD as reference
4. navigate to website, don't find the duplicate entry 

## Debug info
KeePassXC-Browser-Version: 1.6.4
KeePass-Version: 2.4.3
Operating system: Win
Browser: Chrome Version 83.0.4103.106 (64-Bit)

**Comment by droidmonkey** [comment]
Not a problem in newer version of keepassxc

**Comment by sergio-upango** [comment]
I'm facing this same issue: if I specify the full URL in a certain entry autofill works perfectly but when I use a reference it won't list my entry anymore.

## Steps to reproduce
1. Create an entry like:
  Title: MyDomain
  URL: my.domain.com

2. Reference it in another entry like:
  Title: MyDomain page1
  URL: http://{REF:A@I:<MY_DOMAIN_UUID>}/some_page1

3. Also try HTTPS:
  Title: MyDomain page2
  URL: https://{REF:A@I:<MY_DOMAIN_UUID>}/some_page2

## Expected behaviour
Have both entries (from steps 2 and 3) listed in browser extension whenever you access the domain.

## Current Behaviour
None of the entries which are using references are listed. Only the entry from step (1) is listed.

## Debug Info
Operating System: Windows 11
KeePassXC version: 2.6.6
KeepassXC browser version: 1.7.11
Browser: Chrome 99.0.4844.51

**Comment by droidmonkey** [comment]
Remove the http:// from the reference. The field must ONLY contain the ref. If you want to specify multiple urls for a single entry then go to the browser integration settings when editing the entry and add them there.

**Comment by sergio-upango** [comment]
Thanks for the quick reply. I'm trying your suggestion but I guess it doesn't apply to my use case.

My use case is quite similar to the one in [this comment](https://github.com/keepassxreboot/keepassxc/issues/3718#issuecomment-564569297): I have a series of subpages based on the same domain where each of the subpages grants access to different dashboards, having each subpage its own credentials.

## Current setup

Currently I have four entries with the full URL to each of the subpages and each entry stores the specific credentials for the subpage.
| TITLE | USER | PASSWORD | URL |
| -------- | -------- | -------------- | ---------------------------------- |
| Board1 | user-b1 | password-b1 | http://my.domain.com/board1 |
| Board2 | user-b2 | password-b2 | http://my.domain.com/board2 |
| Board3 | user-b3 | password-b3 | https://my.domain.com/board3 |
| Board4 | user-b4 | password-b4 | https://my.domain.com/board4 |

## Future setup
I recently discovered the REF feature (from steps 3 and 4 [here](https://keepassxc.org/docs/KeePassXC_UserGuide.html#_clone_an_entry)) and I was trying to use a single KeePassXC entry to keep the reference to the base domain.
My goal is then to use it as follows:
| TITLE | USER | PASSWORD | URL |
| -------- | -------- | --------------- | ---------------------------------- |
| Domain |             |                       | my.domain.com                         |
| Board1 | user-b1 | password-b1 | http://{REF:A@I:<DOMAIN_UUID>}/board1 |
| Board2 | user-b2 | password-b2 | http://{REF:A@I:<DOMAIN_UUID>}/board2 |
| Board3 | user-b3 | password-b3 | https://{REF:A@I:<DOMAIN_UUID>}/board3 |
| Board4 | user-b4 | password-b4 | https://{REF:A@I:<DOMAIN_UUID>}/board4 |

Sometimes we do migrations and we have to update the base domain. If we could use the REF feature it would make our lives much easier.

Is there any way I can achieve it?

**Comment by droidmonkey** [comment]
Unfortunately no, there is currently no way to handle this use case. It's an interesting idea though, I'll use your last post to make a new issue.

**Comment by sergio-upango** [comment]
Well, then I'll continue using separate entries. Fortunately we don't do migrations everyday :)
Thanks anyway for your help. Really appreciated.
