### ISSUE TITLE
Autofill detection by window class

### ISSUE THREAD

**Issue by amitlevy21** [keepassxreboot/keepassxc#4868]
## Summary
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
My use case is as follows:
I want to use autofill to fill my sudo password every time i'm asked in my terminal.
I'm aware of the option of window associations option in "Edit entry -> Autofill" but I can only associate autofill with a window name.

It would be excellent if I could just associate a window class with the name of my chosen terminal `st`, or even better, read my $TERMINAL environment variable.

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
The problem with window title is that it changes as I write a command. For example, if I write the command `yay` which prompts for my sudo password the window title is yay, where as if I type the `su` command the window title is su. So I would have to add each window title association to each possible command that I would like to autofill when I'm sudo prompted, which is tedious. 

p.s I would also like to use this method for other autofills, like for my ssh password. So when I would type my autofill shortcut when I'm using my terminal, I would like keepassxc to offer autofill for all passwords that match that window class.

Thank you for your time.

**Comment by droidmonkey** [comment]
You can use wildcards in the Window Name definition. So if you have a fixed word in the title you can do: `*<WORD>*`

**Comment by amitlevy21** [comment]
Thanks for the quick response.

I wasn't aware of the wildcard option however it would not help in this case since yay, su and many other command don't have the same character sequence that I can use to capture them all

**Comment by sd2k9** [comment]
I highly support this feature request.

Some window titles are unusable for matching, e.g. just saying
"Sign In" during login phase, and I have a few windows of this style.  
So the matching regexp rules become complicated.

On the other hand the window class (in combination with the window title) is unique, allowing me to find the right autofill entry.

Thanks for the great work of everybody involved.

**Comment by krodelabestiole** [comment]
I came across this topic looking for a way to autofill my **sudo** passwords. So... thumbs up !

May I add that it would allow us (people who use more than one computer) to use more complex user passwords, especially when we have to type them dozen times a day...

I wonder about the _platform: Windows_ label on this issue though...

**Comment by droidmonkey** [comment]
Since the time that this was proposed, we made substantial improvements to the Auto-Type experience. Adding window class wouldn't make it better, especially for a dynamic experience like terminal (you don't know what you'll be using). Use the search in the Auto-Type window.
