### ISSUE TITLE
There is no RTL with Note Editor !

### ISSUE THREAD

**Issue by ghost** [keepassxreboot/keepassxc#4869]
## Overview
Its clear Issue .. There is no RTL with Note Editor .. even if i choose Arabic as ui lang ... even if i press RCTRL+ RShift like in notepad on windows 10 

![RTLkpxc](https://user-images.githubusercontent.com/63208539/84918906-e7acd480-b0c9-11ea-9ef3-002d3cf414bc.png)

**Comment by homhom1416** [comment]
you can copy this for fast testing:
----
TEST
تجربة تجربة تجربة

BesT
جيّد جيّد جيّد جيّد

**Comment by phoerious** [comment]
There are also a lot of layout issues in your screenshot. Please try our 2.6 beta to see if it's any better.

**Comment by droidmonkey** [comment]
For what its worth it doesn't work in GitHub either...

![image](https://user-images.githubusercontent.com/2809491/84967280-990b3480-b0e1-11ea-87d6-819b514bff9d.png)

**Comment by homhom1416** [comment]
i hope you fixing this nearly ..

in [2.7.0](https://github.com/keepassxreboot/keepassxc/milestone/27) for example ..

**Comment by chromer030** [comment]
No support yet.

**Comment by jermanuts** [comment]
hey @droidmonkey why was this closed as completed?

RTL is still not supported, I'm using Windows 10 latest build btw.

![Image](https://github.com/user-attachments/assets/3cc6b2cc-d7da-4162-8763-f4419d670a8d)

**Comment by droidmonkey** [comment]
This isn't our bug if it doesn't work, it's qt

**Comment by jermanuts** [comment]
Is there any issue on Qt tracking it?

Found https://www.arabeyes.org/Qtbugs, is it helpful?

**Comment by droidmonkey** [comment]
Doesn't matter it's likely fixed in qt6
