### ISSUE TITLE
customizable UI ...

### ISSUE THREAD

**Issue by homhom1416** [keepassxreboot/keepassxc#4870]
## Summary & Examples
Just like QOwnNotes ... we Can drag and drop panels anyware we want ... Top ... Right ... left ... etc.
![qwnote](https://user-images.githubusercontent.com/63208539/84920858-64d94900-b0cc-11ea-89c4-2e3fbb38d960.png)

## Context
i want to make the entry preview panel on the right OR Top OR move the entries panel to under group panels etc....

And also its very important to change the entry preview panel FONT SIZE ... or all ui font size like keepass2 ...

Thank you ...

**Comment by droidmonkey** [comment]
We will not be implementing this feature.
