### ISSUE TITLE
Auto-Type problem.  login typing ferst letter instead other letter

### ISSUE THREAD

**Issue by DDosos** [keepassxreboot/keepassxc#4871]
Hi all!
Problem: When I click the combination for Auto-Type in the browser, a window for selecting options appears, and I select the one that is needed. After that, the login is printed in the input window, in which all characters (except special ones: numbers, slash, dot, comma,...) are replaced with the first letter in the login. test@debian.org tttt@tttttt.ttt, instead of login34@test.com lllll34@llll.lll also, switching the keyboard layout using hot keys stops working after this.

KeePassXC - Version 2.5.4
Revision: dcca5aa

Qt 5.12.5
Debugging mode is disabled.

Operating system: Debian GNU/Linux bullseye/sid
CPU architecture: x86_64
Kernel: linux 5.6.0-2-amd64
KDE

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (only unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.5

**Comment by droidmonkey** [comment]
known issue, its already on that issue board.
