### ISSUE TITLE
Custom icon disapear after assigning to created group

### ISSUE THREAD

**Issue by tdslot** [keepassxreboot/keepassxc#4875]
## Overview
Problem is with custom icon. In tree list create group the go to edit and in Icons assign custom icon. Take from file system of push button "Download icon".

## Steps to Reproduce
1. Create group in tree list
2. Go to "Edit Group"
3. Go to Icon
4. Push button "Add custom Icon"
5. Select icon
6. Save
7. Quit from KeepassXC
8. Open KeepassXC

## Expected Behavior
Icon after assignment should be stay not disappear.

## Actual Behavior
When icon is disappear after open .kdbx file in "Use custom icon" list when add again icon it is unusual space, is wider that other icons have.

## Version
KeePassXC - Version 2.5.4
Revision: dcca5aa

Qt 5.14.1
Debugging mode is disabled.

Operating system: macOS 10.15
CPU architecture: x86_64
Kernel: darwin 19.5.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
 libgcrypt 1.8.5

Operating System: macOS

**Comment by droidmonkey** [comment]
Known issue
