### ISSUE TITLE
Comments in Terminal when start KP 

### ISSUE THREAD

**Issue by tuxedotje** [keepassxreboot/keepassxc#4876]
## Overview

(keepassxc:25177): dconf-WARNING **: 13:28:25.156: failed to commit changes to dconf: Error sending credentials: Error sending message: Broken pipe

(keepassxc:25177): dconf-WARNING **: 13:28:26.127: failed to commit changes to dconf: Error sending credentials: Error sending message: Broken pipe

(keepassxc:25177): dconf-WARNING **: 13:28:26.176: failed to commit changes to dconf: Error sending credentials: Error sending message: Broken pipe

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. start Keepassxc in Terminal (Fedora 33)
2. read comments in Terminal
3. 

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
expect no comments

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

(keepassxc:25177): dconf-WARNING **: 13:28:25.156: failed to commit changes to dconf: Error sending credentials: Error sending message: Broken pipe

(keepassxc:25177): dconf-WARNING **: 13:28:26.127: failed to commit changes to dconf: Error sending credentials: Error sending message: Broken pipe

(keepassxc:25177): dconf-WARNING **: 13:28:26.176: failed to commit changes to dconf: Error sending credentials: Error sending message: Broken pipe
 but KP does do his job. 
## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION  2..5.4
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linus Fedora 33
Desktop Env: Gnome/
Windowing System: /Wayland

**Comment by droidmonkey** [comment]
Remove (Backup) your dconf-folder: `mv ~/.config/dconf/ ~/.config/dconf.bak` and try it again. We don't do anything with dconf, this seems like an error with your computer.
