### ISSUE TITLE
Password is displayed on the Windows clipboard history

### ISSUE THREAD

**Issue by MADXhh** [keepassxreboot/keepassxc#4879]
When I copy a password to the clipboard (double-click the password or the clipboard icon), it appears in the Windows clipboard history?
-> Windows key + v shortcut to open the clipboard history

KeePassXC - Version 2.5.4
Revision: c023bf9

Qt 5.14.2
Diagnosemodus ist deaktiviert.

Operating System: Windows 10 Version 1909
CPU-Architektur: x86_64
Kernel: winnt 10.0.18363

Kryptographische Bibliotheken:
 libgcrypt 1.8.5

**Comment by droidmonkey** [comment]
Duplicate issue

**Comment by MADXhh** [comment]
oh ok, sorry

**Comment by MADXhh** [comment]
> 
> 
> Duplicate issue #2358
oh ok, sorry
