### ISSUE TITLE
Browser integration shows expired credentials

### ISSUE THREAD

**Issue by jo-so** [keepassxreboot/keepassxc#4881]
## Overview

In Firefox I see expired credentials, even if I've not selected to show them.

![grafik](https://user-images.githubusercontent.com/23032146/85144497-8280ec80-b24b-11ea-832e-58765000dba1.png)
![grafik](https://user-images.githubusercontent.com/23032146/85144537-9298cc00-b24b-11ea-9b6e-72a98f81d09b.png)
![grafik](https://user-images.githubusercontent.com/23032146/85144563-9c223400-b24b-11ea-9051-77594d0e8a8a.png)
![grafik](https://user-images.githubusercontent.com/23032146/85144583-a3e1d880-b24b-11ea-92e8-38863b9cf43f.png)

KeePassXC - Version 2.6.0
Revision: 1ad0184

Qt 5.12.5
Diagnosemodus ist aktiviert.

Betriebssystem: Debian GNU/Linux bullseye/sid
CPU-Architektur: x86_64
Kernel: linux 5.6.0-2-amd64

Aktivierte Erweiterungen:
- Auto-Type
- Browser-Integration
- SSH-Agent
- KeeShare (nur unbestätigtes Teilen)
- YubiKey
- Secret-Service-Integration

Kryptographische Bibliotheken:
 libgcrypt 1.8.5

**Comment by jo-so** [comment]
Stepping into this with the debugger starting at *src/browser/BrowserService.cpp:852* and stepping into *config.load(entry)* the value of `entry->customData()->value(KEEPASSXCBROWSER_NAME)` in *browser/BrowserEntryConfig.cpp:85* is empty, i.e. `s.isEmpty() == true` in the next line.

**Comment by droidmonkey** [comment]
Easy fix, the expired check needs to come before the config loading. Good find!
