### ISSUE TITLE
Please have 2 fields for each entry that show when the entry was created and when last updated

### ISSUE THREAD

**Issue by vraravam** [keepassxreboot/keepassxc#4889]
## Summary
imo - this feature is a good way to ensure when we need to rotate. For eg, I just saw a report that listed my email address having been pwned in a breach back 3 years ago. Now, if I had had the ability to check in the keepassxc db when I had last changed the password for that site, I could have easily made the decision whether to reset my pwd or not. 

I know that the "Expires on" is kind of this feature - but "expires on" is more of a "pre-facto" thing we can do. I am looking for the diametrically "post-facto" scenario's solution.

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )

**Comment by droidmonkey** [comment]
Duplicate request
