### ISSUE TITLE
Windows Build is missing for latest version

### ISSUE THREAD

**Issue by shyim** [keepassxreboot/keepassxc#489]
Hey,
could you add also a windows build for the latest version 2.1.4?

**Comment by sts10** [comment]
Would love a macOS build of 2.1.4 too while you're at it!

Though when I tried to build 2.1.4 from source I was having some problems launching the application. I built the DMG file just file, dragged it into Applications, but then when I launched the app it just instantly closes. Wonder if it's a permission issue? (I'm using macOS 10.10.5)

**Comment by droidmonkey** [comment]
They're coming tonight

**Comment by droidmonkey** [comment]
Builds for Mac and WIndows are posted. I also compiled and posted 32-bit windows builds!
