### ISSUE TITLE
UI Settings Don't Save

### ISSUE THREAD

**Issue by JenDot** [keepassxreboot/keepassxc#4893]
## Overview
When I change the settings on the main screen (columns, show pw's, etc.), they don't save from one session to another.  I'll set the columns the way I want them, have the passwords revealed, save and close.  When I re-open it, it's all back to the default.

## Steps to Reproduce
1. Set customized columns
2. Save db
3. Close db
4. Open db
5. Settings reset to default.

## Expected Behavior
Column settings should save from one session to another.
![image](https://user-images.githubusercontent.com/67236590/85231064-0e5c5b00-b3a9-11ea-893c-9b55fdb75c76.png)

## Actual Behavior
The settings revert to default, with all columns displayed and passwords hidden.
![image](https://user-images.githubusercontent.com/67236590/85231047-f71d6d80-b3a8-11ea-8153-2c6730eed26e.png)

## Context

[NOTE]: KeePassXC - Version 2.5.4
Revision: dcca5aa
Distribution: Snap

Qt 5.9.5
Debugging mode is disabled.

Operating system: Ubuntu Core 18
CPU architecture: x86_64
Kernel: linux 5.4.0-37-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.1

[NOTE]: # ( Pick choices based on your environment )
Operating System: Ubuntu Focal Fossa
Desktop Env: Gnome
Windowing System: X11/Wayland (no idea)

**Comment by droidmonkey** [comment]
Could not replicate in 2.6.0 using snap version.
