### ISSUE TITLE
Can't connect to keepassxc database in Vivaldi Snapshot on macOS

### ISSUE THREAD

**Issue by tohn** [keepassxreboot/keepassxc#4900]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
Since the side-by-side installation of Vivaldi ([Blogpost](https://vivaldi.com/blog/snapshots/desktop/side-by-side-installation-of-vivaldi-on-macos-vivaldi-browser-snapshot-1950-3/)) I can't connect to my keepassxc database via keepassxc-browser.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. [Install Snapshot on macOS](https://downloads.vivaldi.com/snapshot/Vivaldi.3.2.1950.3.dmg)
2. Try to connect to keepassxc via keepassxc-browser

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
I can successfully connect to the database via the browser plugin.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Nothing happens.

## Context
[NOTE]: # ( Give us any additional information you may have. )
I assume this issue is related to the renaming and in the settings (Browser Integration) there is no "Vivaldi Snapshot" yet, so I reported the issue here instead of the browser extension.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.5.4

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS 10.15.4

**Comment by droidmonkey** [comment]
We don't support beta or snapshot browsers. You will have to manually move the native messaging configuration to the correct settings folder. In 2.6.0 we introduced a custom browser configuration so you can set up a custom path.
