### ISSUE TITLE
KeepassXC does not accept database password

### ISSUE THREAD

**Issue by Eleison23** [keepassxreboot/keepassxc#4901]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Expose KeepassXC window
2. Type correct database password

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
KeepassXC unlocks database, ready for use

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Database relocks and KeepassXC minimizes

## Context
[NOTE]: # ( Give us any additional information you may have. )
Master database uses password and key file combination. Key file is of course also correct.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.5.4
Revision: dcca5aa

Qt 5.9.5
Debugging mode is disabled.

Operating system: Ubuntu 18.04.4 LTS
CPU architecture: x86_64
Kernel: linux 4.15.0-106-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.1

[NOTE]: # ( Pick choices based on your environment )
Operating System: Ubuntu Linux 18.04.4 LTS
Desktop Env: KDE Plasma 5
Windowing System: X11

**Comment by phoerious** [comment]
I am not quite sure what your problem is or how to reproduce it. We need a bit more information about what exactly is happening.

**Comment by Eleison23** [comment]
What kind of information would you like? I am happy to provide what I can. But the upshot is that KeepassXC resolutely keeps the database locked, even after I type in the correct password 10 times in a row. I have turned on "reveal password" and verified, letter-by-letter, that the password is correct, but it will not unlock the database. I leave it sit for some minutes, come back, try the same password and it unlocks.

**Comment by Eleison23** [comment]
I can offer some critical information. I am using the KeepassXC browser integration extension on Chromium, and this bug only occurs when I activate KeepassXC by using the "Database locked" icon in the login field.

I click the lock icon and the KeepassXC window comes up (or it doesn't.) Then I enter my password and it silently re-minimizes while staying locked. If I expose KeepassXC normally without the browser extension, it unlocks properly with the correct password.

**Comment by phoerious** [comment]
That is absolutely intended behaviour. KeePassXC is only brought up so you can unlock it. If it is unlocked and you are on a website that has login fields for which you have an entry in your database, the browser extension will ask you for permission to fill them.

**Comment by phoerious** [comment]
BTW It also sounds like you have enabled the option to lock automatically on minimise. I highly recommend disabling that option.

**Comment by droidmonkey** [comment]
We need to just remove that as an option, it serves no real purpose besides confusion and UX failure.
