### ISSUE TITLE
Shared Entries in Subgroups appear in Rootgroup

### ISSUE THREAD

**Issue by color-space** [keepassxreboot/keepassxc#4903]
## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. create a shared database on a network drive.
2. create a subgroup below the shared group and save an entry inside.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
I expected it to also sync subgroups of the shared group.
So when i create one - it's visible to the others. 

## Observed Behavior
The Entries in created Subgroups appear in the rootgroup for others.

## Context
KeePassXC - 2.6.0 beta 
Win10

But i'm not sure if this is a bug or how it would be intended.
Because you could probably just have a completely seperate DB on the network drive and thanks to autoreload & autosave on change it would be synced like what i imagined.

**Comment by droidmonkey** [comment]
Using keeshare? Unfortunately that's the way it works, already got an issue for that.

**Comment by droidmonkey** [comment]
See #3045

**Comment by color-space** [comment]
I didn't look for similar issues.
my bad - closed.
