### ISSUE TITLE
Databases on SFTP mount were opened read-only

### ISSUE THREAD

**Issue by NicolasGoeddel** [keepassxreboot/keepassxc#4905]
## Overview
When I open a database from a SFTP mount KeepassXC always marks the database as read-only (Schreibgeschützt).

## Steps to Reproduce
1. Mount an external server using sftp://myserver in Nautilus.
2. Locate the database and open it with KeepassXC.
3. It shows "Schreibgeschützt" (read-only) in the title and saving is not allowed.

## Expected Behavior
It should be possible to save the database as it would be located locally or on an CIFS mount.

## Actual Behavior
The save button is gray and it tells me "Schreibgeschützt".

## Context
Other applications can read and write without an issue on the same mount.
The server is configured in `~/.ssh/config` and I can access it over an OpenVPN connection.
KeePassXC - Version 2.5.3
Revision: f8c962b

Qt 5.12.8
Diagnosemodus ist deaktiviert.

Betriebssystem: Ubuntu 20.04 LTS
CPU-Architektur: x86_64
Kernel: linux 5.4.0-33-generic

Aktivierte Erweiterungen:
- Auto-Type
- Browser-Integration
- SSH-Agent
- KeeShare (bestätigtes und unbestätigtes Teilen)
- YubiKey
- Secret-Service-Integration

Kryptographische Bibliotheken:
 libgcrypt 1.8.5

Operating System: Linux
Desktop Env: Gnome
Windowing System: X11

**Comment by droidmonkey** [comment]
This is fixed in 2.6.0, but we are seeing issues with GVFS especially with cloud service providers that obfuscate the name of the file.

**Comment by NicolasGoeddel** [comment]
In my case it's just an other Ubuntu Server. No special cloud service provider.
When will 2.6.0 be available in the PPA?

**Comment by droidmonkey** [comment]
You can try it out in beta right now: https://github.com/keepassxreboot/keepassxc/releases/tag/2.6.0-beta1

**Comment by NicolasGoeddel** [comment]
I just tested it with Version 2.6.0 from the PPA: https://launchpad.net/~phoerious/+archive/ubuntu/keepassxc
And it works great.
