### ISSUE TITLE
Statistics about passwords and than what?

### ISSUE THREAD

**Issue by leomayer** [keepassxreboot/keepassxc#4917]
## Summary
I see the statistics of my database and see how many passwords are too short, used more than 3 times, etc.etc.

But how to find the entries which belong to these categories? e.g. Find these passwords which are less than 8 chars, which are not unique, etc.

And IF this query already exists (which I have no idea) than add a link which fills automatically the search and display the results.

**Comment by droidmonkey** [comment]
I'm assuming you are using 2.6.0 beta release. There are other report tabs that show you password issues.

**Comment by leomayer** [comment]
2.5.4 on Linux. I'm referreing to the enclosed screenshot. 

I don't see any chances to an idea which 41 entries have a short password or... 

![Uploading Bildschirmfoto von 2020-06-29 14-43-07.png…]()

**Comment by droidmonkey** [comment]
2.6.0 implements what you are after

**Comment by leomayer** [comment]
Ahh... OK.... I didn't see any reference to this kind of functionality in the Changelog. Therefore I assume(d) its not included. But lets see. Thx for the update.
