### ISSUE TITLE
KeePassXC v2.5.4 and Onlykey not detected / working correctly - Windows, 32+64bit

### ISSUE THREAD

**Issue by space97** [keepassxreboot/keepassxc#4918]
## Overview

I'm using the portable Windows version(s) of KeePassXC. With Windows 8.1 and Windows 10, both 64bit. There are two issues.

1. When using the 32bit version on a 64bit OS, @onlykey is not detected. Refresh doesn't help. Running as Administrator also doesn't make a difference.

2. When using the 64bit version, the Onlykey procedure doesn't seem to work correctly.

## Steps to Reproduce

1. Start KeePassXC
2. Create New Database
3. Insert Onlykey

Here the process stops.

## Expected Behavior

To be able to use Onlykey with the Portable versions of KeePassXC on both 32 and 64bit OS.

## Actual Behavior

I create new database, the key is detected (64bit version) and you can selected slot 1 or 2. After pressing done, a Message Box is shown, and after that it either keeps asking OR it no longer shows any keys. Refresh doesn't help, only by removing and inserting Onlykey it is detected again. I did enter the PIN of course and it does flash yellow the first time. 

**Message Box:**
```
---------------------------
Failed to change master key
---------------------------
No YubiKey detected, please ensure it's plugged in.
---------------------------
OK   
---------------------------
```

Remark:

After several attempts I did manage to create a database and proceed to the next step, but KeePassXC then keeps asking to touch the yubikey to save the database, but it it fails, and keeps asking.

## Context

KeePassXC - Version 2.5.4
Revision: c023bf9

Operating system: Windows 10 Version 1903
CPU architecture: x86_64
Kernel: winnt 10.0.18362

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

**Comment by phoerious** [comment]
Make sure you have the latest firmware on your OnlyKey.

**Comment by space97** [comment]
**Firmware v0.2-beta.8c** which seems to be the latest [OnlyKey Firmware Beta 8](https://github.com/trustcrypto/OnlyKey-Firmware/releases/tag/v0.2-beta.8) 

fyi Documentation onlykey & KeePassXC here: https://docs.crp.to/usersguide.html#keepassxc

**Comment by droidmonkey** [comment]
Try our 2.6.0 beta release, only key is vastly improved.

**Comment by space97** [comment]
👍 Getting the occasional error but it works on 2.6.0 beta 1, 64bit.  

It still doesn't see the Onlykey when using the 32bit version.
