### ISSUE TITLE
KeepassXC 2.5.4 on Ubuntu Budgie 20.04 not recognized Hardware Key (YubiKey)

### ISSUE THREAD

**Issue by artemusgit** [keepassxreboot/keepassxc#4919]
## Overview
By using KeepassXC 2.5.4 on Ubuntu Budgie 20.04 a yubikey (hardware key with challenge response) not listed in the combobox. 

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
-     Reinstallation my OS to Ubuntu Budgie 20.04
-     Install KeepassXC 2.5.4 as Snap
-     Open a existing database secured by a password, keyfile and challenge response
-     Try to select a hardware key (none are listed)
-     Click 'Refresh' --> still no hardware keys listed
-     Fail to unlock database

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Yubikey is recognized an listed in the combobox

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Still no hardware keys listed in the combobox

## Context
[NOTE]: # ( Give us any additional information you may have. )
Yubikey-Support reproduced the issue and it didn't work too. They report back it appears to be an issue with KeepassXC.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION   2.5.4
Revision: REVISION  dcca5aa

[NOTE]: # ( Pick choices based on your environment )
Operating System: Ubuntu Budgie 20.04
Desktop Env: Budgie
Windowing System: X11/Wayland

**Comment by droidmonkey** [comment]
https://keepassxc.org/docs/#faq-appsnap-yubikey
