### ISSUE TITLE
Show some screenshots on the website

### ISSUE THREAD

**Issue by Wandmalfarbe** [keepassxreboot/keepassxc#492]
It would be nice to know what the program looks like before downloading and installing it.

## Possible Solution
You could show some screenshots of the program on the website.

**Comment by RealOrangeOne** [comment]
Probably better posted to the websites repo at https://github.com/keepassxreboot/keepassxreboot.github.io

**Comment by phoerious** [comment]
We planned that for 2.2.0. For 2.1.x there is no point in posting screenshots. It looks basically the same as KeepassX, which isn't exactly pretty.

**Comment by Wandmalfarbe** [comment]
I understand.

**Comment by schiorean** [comment]
Is there a timeline for 2.2.0? Looking forward :).

**Comment by TheZ3ro** [comment]
No, we don't have a fixed timeline @schiorean

**Comment by seatedscribe** [comment]
Is there a branch for the 'improving GUI' goal?

**Comment by droidmonkey** [comment]
Any additional major GUI changes are slated for 2.3.0. Due to the way qt gui files are crafted it would be best to do them all at once.

**Comment by louib** [comment]
Created issue https://github.com/keepassxreboot/keepassxreboot.github.io/issues/11 for this. Closing.
