### ISSUE TITLE
TOTP generator impedes session timeout

### ISSUE THREAD

**Issue by marcosaedro** [keepassxreboot/keepassxc#4920]
## Overview

The Time-based One-Time Password (TOTP) generator stops KeePassXC session from timing out.

## Steps to Reproduce
0. Set a session timeout of X seconds or other session ending triggers in Tools > Settings > Security.
1. In the main screen select an entry where TOTP is configured
2. Click on Entries > TOTP.. > Show TOTP     or     Ctril+Shift+T
3. Do something else for X seconds.

## Expected Behavior
The session should finish and the password database should be locked, requiring the passphrase to reopen.

## Actual Behavior
The TOTPs are produced one after another forever (= at least one day).

## Context
KeePassXC - Version 2.5.4
Revision: dcca5aa
Distribution: Snap

Qt 5.9.5
Debugging mode is disabled.

Operating system: Ubuntu Core 18
CPU architecture: x86_64
Kernel: linux 5.3.0-61-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.1

**Comment by droidmonkey** [comment]
Fixed in 2.6.0
