### ISSUE TITLE
Libsecret integration wants to move NetworkManager VPN entry to trash

### ISSUE THREAD

**Issue by marcstraube** [keepassxreboot/keepassxc#4921]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
When I want to connect to an VPN Network via nm-applet, KeePassXC wants to move the entry to the trash folder.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Left-click on the nm-applet icon.
2. Chose a VPN connection for which you have an entry in KeePassXC.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
After choosing the VPN connection entry, NetworkManager should just connect to the VPN.

## Actual Behavior
A popup appears that asks "Do you really want to move [entry name] to trash?"

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.5.4
Revision: dcca5aa

[NOTE]: # ( Pick choices based on your environment )
Operating System: ArchLinux
Desktop Env: Awesome WM
Windowing System: X11
Packages:
- networkmanager
- networkmanager-pptp
- network-manager-applet

**Comment by droidmonkey** [comment]
Sounds like a bug in the VPN network requestor.

**Comment by marcstraube** [comment]
[1.txt](https://github.com/keepassxreboot/keepassxc/files/4853814/1.txt)
[2.txt](https://github.com/keepassxreboot/keepassxc/files/4853815/2.txt)

I've added the dbus-monitor logs:
1.txt contains the log when clicking on the connection in the nm-applet.
2.txt contains the log when clicking on the "Cancel" button of the "move to trash" dialogue.

The "move to trash" dialogue also appears when I open the settings of the VPN connection.
Left click on nm-applet -> VPN connection -> Configure VPN -> double click on the connection.
I can create the dbus log for this one, too, if needed.

**Comment by haarp** [comment]
Ssame here.

It does try to move the entry to the trash, but if allowed it will immediately recreate a copy of the deleted entry in its former place. Odd behavior. There could be intent behind in, in which case KeepassXC would have to deal with it in some way.

**Comment by TeaMoe** [comment]
vscode does the same when signing in to live share

**Comment by Aetf** [comment]
@TeaMoe, @haarp  could you share the dbus-monitor log?

@marcstraube Thanks for your log, but they don't contain the important moment when nm-applet asks to delete the entry. Also, it looks like nm-applet having trouble finding the service name `org.freedesktop.secrets` (or maybe that's just normal).

To have a useful log, run the following running from the beginning, perform all steps and share **all** outputs here.

```
dbus-monitor "destination=org.freedesktop.secrets" "sender=org.freedesktop.secrets"
```

Make sure to search for `array of bytes` and mask those when sharing the log here. Those may contain your real password.

**Comment by haarp** [comment]
@Aetf

[dbus-monitor.txt](https://github.com/keepassxreboot/keepassxc/files/7309375/dbus-monitor.txt)
 
I'm not aware if the password is contained somewhere in this log, so I changed it just to be safe.

**Comment by Aetf** [comment]
@haarp Thanks.

From the log, nm-applet indeed explicitly asked to delete the item so KPXC was doing what it was told to do.

A quick search on the nm-applet source code reveals [this](https://gitlab.gnome.org/GNOME/network-manager-applet/-/blob/main/src/applet-agent.c#L748-L749): secrets are firstly deleted before saving.

Usually the item can be updated so the deletion seems unnecessary. But maybe there's a reason for that. I just spent less than 10 min on their code base anyway.

As a workaround, you can disable the confirm delete option for now. It should be pretty safe, as the option only affects the exposed group, which usually only contains client saved items.

I'd suggest to report this to nm-applet. I'm closing the issue as there's nothing we can do in KPXC.

@TeaMoe this issue turns out to be nm-applet specific. If you still experience problems, please open a separate issue with dbus-monitor log.

**Comment by phoerious** [comment]
On first glance, that looks to me like a workaround for a bug in some other keyring implementation they encountered in the past. Especially with that explicit comment. 

However, the line hasn't been touched in 10 years, so it's safe to assume that whatever that might have been isn't relevant anymore: https://gitlab.gnome.org/GNOME/network-manager-applet/-/blame/main/src/applet-agent.c#L748

**Comment by haarp** [comment]
https://gitlab.gnome.org/GNOME/network-manager-applet/-/issues/147
