### ISSUE TITLE
Won't reload/save database or quit properly after running for while

### ISSUE THREAD

**Issue by drone540** [keepassxreboot/keepassxc#4923]
## Overview
It appears that KeepassXC seems to not update with my Nextcloud Database from another computer if it's been running for a couple of days. 

Also when quiting KeepassXC, it will continue to still be running in the background, and you are unable to reopen it. It could be either related to the browser extension maybe, or the fact that I have auto lock database turned off. 

But it seems to not reload the database after I'm not sure how many hours. But I've had it happen in less then 24 hours before. I think the program will function correctly and even let you appear to add new new passwords to the database, but they sometimes will not actually get saved also (maybe when it's out of sync?)

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Run Firefox with KeepassXC-Browser
2. Open KeepassXC.exe, login to database, and go to settings/security and disable lock database after inactivity
3. Wait a couple of hours. (Time unknown till bug)
4. Try to update the database from another program or cloud data. This step could probably be optional, but can confirm when the bug happen if the data does not get updated automatically
5. Quit KeepassXC and see that it's still running in task manager in the background. And will not reopen when trying until you kill the process.

## Expected Behavior
Program to function normally

## Actual Behavior
Seems to get in end up in some blocked state

## Context
Does not appear to have this issue on Linux. Seems to be a windows problem.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.5.4
Revision: c023bf9

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows

**Comment by droidmonkey** [comment]
Duplicate issue and fixed in 2.6.0
