### ISSUE TITLE
Browser Extension: Add an explicit possibility to save/update new credentials

### ISSUE THREAD

**Issue by LightTemplar** [keepassxreboot/keepassxc#4924]
## Summary
Sometimes the browser extension doesn't suggest creating new record in the database. This is very inconvenient to create it then manually. I think I could use then some explicit command to create it.  

It could work on this scenario:
1) Iog in on site.
2) watching, keepassxc hasn't recognize the login.
3) log out
4) enter credentials on the site again but without actually logging in
5) explicit command to create the record
6) log in

**Comment by droidmonkey** [comment]
We do the best we can to recognize when a new credential is entered. Unfortunately some websites make it very difficult to detect this case. Also, you can increase the number of redirects allowed after account creation in the browser extension settings.
