### ISSUE TITLE
Mac version doesn't have search feature

### ISSUE THREAD

**Issue by DShirk** [keepassxreboot/keepassxc#4925]
## Summary
Windows version has search field in title bar. I just switched to Mac and can't find search field anywhere. Maybe because I am new to Mac, but if it exists I haven't found it in menu or interface. Keyboard shortcut ⌘ + F does not function either.

## Context
NOTE: Really helpful to be able to search the database in Windows version, absent in Mac. Running Keepass XC 2.5.4 on 2019 MacBook Pro with Catalina 10.15.5

**Comment by droidmonkey** [comment]
The search bar is in the same location, try making the window larger.

**Comment by DShirk** [comment]
Trouble was config setting to hide toolbar icons... maybe that will help others.
