### ISSUE TITLE
Added custom icons are saved as distorted images

### ISSUE THREAD

**Issue by keepassium** [keepassxreboot/keepassxc#4926]
## Overview

A custom PNG icon added with KeePassXC ends up as a washed out/distorted image in the database.

## Steps to Reproduce
1. Create a new kdbx4 database with one entry
2. Add [this image](https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/160/apple/237/firecracker_1f9e8.png) as a custom icon for the entry:
![original icon](https://user-images.githubusercontent.com/38399598/86243948-80058780-bba7-11ea-8fff-7c5d2f824bc5.png)
3. Export the database to XML (using KeePass, for example) -> [result](https://pastebin.com/Qq9mHny0)
4. [Convert](https://base64.guru/converter/decode/file) base64 string of the custom icon to a binary file:

## Expected Behavior
The image in the database should be similar to the original.

## Actual Behavior
The image in the database appears washed out:
![Custom icon added by KeePassXC](https://user-images.githubusercontent.com/38399598/86243896-695f3080-bba7-11ea-891f-daa798eebef4.png)

The same icon added by KeePass 2.45 looks just fine:
![Custom icon added by KeePassXC vs by KeePass](https://user-images.githubusercontent.com/38399598/86244780-c4ddee00-bba8-11ea-92dd-c46687482f0c.png)

## Context
KeePassXC - Version 2.5.4
Revision: c023bf9

Qt 5.14.2
Debugging mode is disabled.

Operating system: Windows 7 Version 6.1 (Build 7601: SP 1)
CPU architecture: x86_64
Kernel: winnt 6.1.7601

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.5

**Comment by phoerious** [comment]
I cannot reproduce this issue, at least not on Linux. I added the firecracker to a new database, dumped the XML contents via `keepassxc-cli export`. The decoded PNG still looks the same, just rescaled to 128x128px.

**Comment by droidmonkey** [comment]
Not reproducible:

![image](https://user-images.githubusercontent.com/2809491/86255747-808d2680-bb85-11ea-92a6-1120cec761f1.png)

**Comment by keepassium** [comment]
@droidmonkey, I never said it _looked_ wrong in KPXC, I said it gets _stored_ in a distorted format. 

Here's a database made by KPXC 2.5.4 on the current macOS 10.15.5 (Qt 5.14.1):
[issue4926.kdbx.zip](https://github.com/keepassxreboot/keepassxc/files/4858678/issue4926.kdbx.zip) (password: "demo")

Here's how it looks on the same Mac in KPXC, MacPass and KeeWeb:

<img width="822" alt="Screen Shot 2020-07-01 at 17 08 57" src="https://user-images.githubusercontent.com/38399598/86260680-e4cbdc80-bbbd-11ea-8351-f91d3b3ff427.png">

**Comment by droidmonkey** [comment]
I tested between KeePass 2.44 and KeePassXC without issue. Issue points to the other apps.

**Comment by keepassium** [comment]
> Issue points to the other apps.

The binary blob in the XML is rather app-neutral, though :)

Ok, I'll make the last effort...

The issue is possibly related to #4341 . Here's an excerpt from [your analysis](https://github.com/keepassxreboot/keepassxc/issues/4341#issuecomment-599141315):

> It would appear that the error occurs when loading the previously saved PNG binary data. I tried one of my own PNG files and the error does not occur at all. 

Anyway, suit yourself, my part is done.

**Comment by droidmonkey** [comment]
Original image -> load into KPXC -> everything looks the same -> lock/unlock -> everything looks the same. After the lock/unlock step if it was a storage issue I would expect the image to look different since it is going through the Qt image processing. Opened database in KeePass, everything looks the same. Cleared all icons and loaded the icon in KeePass -> open KPXC and icon looks the same. Given both apps use entirely different PNG pipelines I am having a hard time seeing a problem.

**Comment by droidmonkey** [comment]
Also from the XML export:

![image](https://user-images.githubusercontent.com/2809491/86270354-1d0cf400-bb99-11ea-87d2-a52fcab80ab5.png)

**Comment by droidmonkey** [comment]
This could just be a problem in 2.5.4, I tested in 2.6.0 where I fixed a couple problems with the icon pipeline.

**Comment by keepassium** [comment]
Can you please upload your test DB? I'd check the difference between PNG records.

**Comment by droidmonkey** [comment]
[Passwords.zip](https://github.com/keepassxreboot/keepassxc/files/4859696/Passwords.zip)

Password is 'a'

**Comment by keepassium** [comment]
Thank you for the database.

The PNGs have a few significant differences:

|                     | problematic.png             | non-problematic.png          |
|---------------------|-----------------------------|------------------------------|
|File Size            | 17580                       | 18691                        |
|Profile Name         | Custom                      | sRGB                         |
|Green Matrix Column  | 0.3851 0.7169 **0.09709**   | 0.3851 0.7169 **0.09711**    |
|Blue Matrix Column   | 0.14308 0.06062 **0.71417** | 0.14308 0.06062 **0.71416**  |
|Media White Point    | **0.95045** 1 **1.08905**   | **0.95042** 1 **1.0889**     |
|Profile Description  |                             | sRGB                         |
|Pixels Per Unit X    | 2835                        | 6614                         |
|Pixels Per Unit Y    | 2835                        | 6614                         |
|Software             | Adobe ImageReady            |  *(no such field)*           |

The most obvious difference is the messed up color profile (Custom vs. sRGB). The original image does not have any color profile (ICC profile chunk) at all.

Interestingly, if I remove the color profile chunk from the problematic PNG, the colors become correct:
`pngcrush -rem iccp problematic.png fixed.png`
![problematic](https://user-images.githubusercontent.com/38399598/86286677-3177dd80-bbe7-11ea-84b1-80b3b687b55f.png)  ![fixed](https://user-images.githubusercontent.com/38399598/86286681-3472ce00-bbe7-11ea-82a3-fcb6016c6be7.png)

Then, things become directly related to #4341. 

When I save the [test database](https://github.com/keepassxreboot/keepassxc/files/4858678/issue4926.kdbx.zip) which contains the *problematic.png* (with the broken color profile) — the DB becomes 17 KB smaller. The next time it opens, the custom icon is empty (which is exactly #4341). However, if *problematic.png* is replaced by the *fixed.png* — same image, but without the ICC chunk — the custom icon successfully survives DB saving and issue #4341 does not happen.

**So, it seems that #4341 is caused by the corrupted ICC chunk in the stored PNG (in line with [this](https://github.com/keepassxreboot/keepassxc/issues/4341#issuecomment-599153962) finding).**

When such a corrupted PNG is loaded by AppKit/UIKit (macOS/iOS) apps, they show the image with weird colors.

When such a corrupted PNG is loaded by KeePass, I guess .NET ignores the corrupted ICC profile and draws the image using display's native color profile. As a proof, here's the same *problematic.png* rendered by Paint.NET and the standard Win 7 image viewer. One looks fine, the other one looks weird:

![Screen Shot 2020-07-01 at 23 05 12](https://user-images.githubusercontent.com/38399598/86292476-19a55700-bbf1-11ea-9322-0e6f043f3e08.png)
This explains why the corrupted icon looks fine in KeePass.

Finally, when such a corrupted PNG is loaded by KPXC, three things happen:

- Corrupted PNG data get loaded as QImage (probably with a warning about ICC profile)
- For drawing, the QImage is [converted](https://github.com/keepassxreboot/keepassxc/blob/develop/src/core/Metadata.cpp#L381) to QPixmap, which [fixes](https://stackoverflow.com/a/40368994/1671985) the color profile (likely by enforcing the display native's ICC profile). This explains why the corrupted icon looks fine in KPXC.
- When the user saves the database, we are back to QImage. It [fails the ICC check](https://github.com/keepassxreboot/keepassxc/issues/4341#issuecomment-599153962), so the image data written to the database is empty — that is, #4341 happens.

**Summary:**
1. KPXC seems to corrupt color profiles of the PNGs added as custom icons (this issue)
2. Such corrupted PNGs look fine in KP and KPXC, and pretty bad in MacPass, KeeWeb and KeePassium.
3. Such corrupted PNGs are not preserved by KPXC when saving the database (the high-priority #4341)

Are you convinced yet?

**Comment by droidmonkey** [comment]
Yes absolutely, I'll eat some crow on this one. However, it looks like the latest version of Qt solves the problem entirely. We didn't make any code changes on our end to establish the correct color profile.

**Comment by droidmonkey** [comment]
Confirmed that #4341 is totally fixed with the latest Qt version.

**Comment by phoerious** [comment]
When I tested it, I opened the extracted image in Gwenview, which displayed it correctly. So it is indeed possible that there was a problem, but only if you display the image in non-Qt applications.
