### ISSUE TITLE
TOTP secrets are lost, not stored in kdbx file

### ISSUE THREAD

**Issue by mrpg** [keepassxreboot/keepassxc#4928]
## Overview
KeePassXC does not store TOTP secrets in kdbx file

## Steps to Reproduce
Unknown. Happens sometimes. But in general, TOTP secrets are lost after some time and on occasion immediately after restarting KeePassXC.

## Expected Behavior
TOTP secrets are not lost.

## Actual Behavior
TOTP secrets utterly disappear.

## Context
KeePassXC - Version 2.5.4
Revision: dcca5aa

Qt 5.15.0
Debugging mode is disabled.

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 5.6.19.a-1-hardened

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.5

**Comment by droidmonkey** [comment]
I'm assuming you are adding the TOTP secret when editing an entry. This is a known bug that has been fixed in 2.6.0
