### ISSUE TITLE
UI of the clone window is imperfect

### ISSUE THREAD

**Issue by Throne3d** [keepassxreboot/keepassxc#493]
The clone window does not display very neatly when I open it by default.

## Expected Behavior
The window should be an appropriate size to display all the text and the text should wrap if necessary (or somehow otherwise display all the text neatly).

## Current Behavior
The "Append '- Copy' to title" text is truncated at "titl", the "Replace username and password with references" text is truncated at "refere(n)" (and by the end of the window), and the "Copy history" text label seems to be chopping off the descenders of the 'p' and 'y' characters (presumably due to weird sizing).
Screenshot:
![image](https://cloud.githubusercontent.com/assets/577128/24926216/cf46df9c-1ef2-11e7-9bdc-e5925564f028.png)

## Possible Solution
Modify the whatever structure that UI uses to work well when resized? (Grid structure, specify a minimum width, etc?)

## Steps to Reproduce (for bugs)
1. Open a database
2. Right-click and entry and click to clone it
3. See the truncated text (perhaps requires a specific desktop theme? or a specific lack of the Unity feel)

## Context
I'm trying to clone an entry and the box appeared but was quite ugly. :P

## Your Environment
* KeePassXC version/commit used: "2.1.4", revision 82b3013b0f7247f6f20daae0b92654c88cba144f
* Qt version (e.g. Qt 5.3): 5.7.1
* Compiler (e.g. Clang++3.6.0): gcc 6.3.0 (is installed, at least? I don't know how to tell if I'm using this one)
* Operating System and version: Ubuntu 17.04 (beta, yes, so it is plausibly a problem with the beta, but the app displays fine in all other location I can see and so I expect this can be reproduced elsewhere, or is at least a sign of something weird going on behind the scenes; also shows in a VirtualBox that started with Ubuntu 16.10 and was upgraded to Ubuntu 17.04)

**Comment by TheZ3ro** [comment]
@Throne3d can you check if the bug is resolved for you after the last PR?

**Comment by Throne3d** [comment]
Yep, looks fixed:
![image](https://cloud.githubusercontent.com/assets/577128/25055721/74afa084-215c-11e7-959f-2f2bb794c944.png)

Thanks @weslly and @TheZ3ro.
