### ISSUE TITLE
Feature Request: Shortcut for 'Add to agent'

### ISSUE THREAD

**Issue by ingroxd** [keepassxreboot/keepassxc#4931]
## Summary
It would be nice to have a shortcut for 'Add to agent' in the 'SSH Agent' key section.

## Examples
- I open KeepassXC
- I select a key
- I press Ctrl + s
- The public ssh key set in KeeAgent.settings is added to my agent
- I SSH login with the key

## Context
This feature matter to me beacuse I use the keyboard most of the time and this is the only feature I use that requires me to stop typing, pick the mouse, open the key properties, select 'SSH Agent' tab, and click on 'Add to agent' and then "get back to work".

**Comment by droidmonkey** [comment]
Already done in 2.6

**Comment by ingroxd** [comment]
Ok, thank you
