### ISSUE TITLE
Keepass keeps opening when closing firefox

### ISSUE THREAD

**Issue by mannotserious** [keepassxreboot/keepassxc#4932]
## Overview
I am running the flatpak version of KeePassXC 2.5.4 on POP!_OS 20.04. The deb version runs fine but the flatpak, with the same settings, will maximize every time I close firefox.

## Steps to Reproduce
1. Open Keepass
2. Minimize kepass to panel
3. Open then close firefox

## Expected Behavior
Keepass should not do anything here.

## Actual Behavior
Keepass will open and maximize window

## Keepass version
KeePassXC - Version 2.5.4
Revision: dcca5aa
Distribution: Flatpak

## Environment
Operating System: Linux POP!_OS 20.04
Desktop Env: Gnome
Windowing System: POP Shell

**Comment by droidmonkey** [comment]
This is a flatpak issue, won't be an issue in 2.6.0

**Comment by mannotserious** [comment]
This is still an issue for me on 2.6.0. Though the UI looks beatiful! Nice job :)

**Comment by marshevms** [comment]
This is still an issue for me on 2.6.0.

**Comment by mannotserious** [comment]
Can we please reopen this issue droidmonkey?

**Comment by droidmonkey** [comment]
Are you using the Flatpak? If so, no, you'll have to bring it up with the Flatpak maintainer.

**Comment by mannotserious** [comment]
Sweet droid I'll do that. I don't know where that is though. Searching didn't bring up anything? Thanks in advance

**Comment by droidmonkey** [comment]
https://github.com/flathub/org.keepassxc.KeePassXC

**Comment by marshevms** [comment]
Thanks! Now everything works as it should.
