### ISSUE TITLE
Add A Dedicated Database Type For Only TOTP

### ISSUE THREAD

**Issue by grravity** [keepassxreboot/keepassxc#4935]
## Summary
Suggesting to add a dedicated database type specifically for TOTP authentication. This would remove a lot of the fields like username and password, streamline down the UI for this DB and make it much easier to generate, add, copy, and overall deal with TOTP codes.
Ontop of this, I have suggested not to long ago, including the feature to add TOTP from sites that only supply you with a QR code, this has made it impossible to use KeepassXC as my primary TOTP DB and I hope to be able to see this ability soon to be able to finally switch over.

**Comment by droidmonkey** [comment]
Not gonna happen, there is no benefit to this at all
