### ISSUE TITLE
Add support for Blizzard 2FA Authentication (Battle.net)

### ISSUE THREAD

**Issue by notNSANE** [keepassxreboot/keepassxc#4936]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
Add Blizzard's own 2FA authentication method: https://us.battle.net/support/en/article/24520

It's featured on WinAuth: https://winauth.github.io/winauth/

Perhaps you can look up the code to get a headstart on it? https://github.com/winauth/winauth/blob/master/Authenticator/BattleNetAuthenticator.cs

## Examples
[NOTE]: # 

Just a screenshot of WinAuth to show that they could implement it.

![image](https://user-images.githubusercontent.com/7162375/86486054-b6bad980-bd30-11ea-8995-8f3c5686faef.png)

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
As the Steam authenticator, this feature will add even more value to KeePassXC.

**Comment by grravity** [comment]
Big +1 for this, I need to get my 2FA migrated away from their app into KeepassXC. I hope to see this very soon.

**Comment by froks** [comment]
It's a bit of work, but you can use https://github.com/jleclanche/python-bna to generate the url, and put it into the Advanced/otp-property.

**Comment by Offerel** [comment]
Can this be closed? An url like otpauth://totp/Battle.net:username?secret=yoursecret&period=30&digits=8&issuer=Battle.net is working with Battle.Net accounts. At least in my case:

![image](https://user-images.githubusercontent.com/14041522/171454312-db718d6e-7aae-497f-9bef-e9c9485a5c3d.png)

**Comment by templis** [comment]
@Offerel and what is this url for?
the authenticator on battle.net needs a serial number and an authenticator code.
![2022-06-01 19_19_45-Battle net Account](https://user-images.githubusercontent.com/9048398/171464813-c6726a9f-160d-4240-9dea-65ac5a1074be.png)
and the totp in KeePassXC needs a secure key, there is no way to put an URL in it?!

**Comment by dimon222** [comment]
> @Offerel and what is this url for? the authenticator on battle.net needs a serial number and an authenticator code. ![2022-06-01 19_19_45-Battle net Account](https://user-images.githubusercontent.com/9048398/171464813-c6726a9f-160d-4240-9dea-65ac5a1074be.png) and the totp in KeePassXC needs a secure key, there is no way to put an URL in it?!

Use above script on python to generate necessary secret, then plug with example suggested into keepassXC

**Comment by templis** [comment]
ahh nice, thank you @dimon222, @froks and @Offerel :)

for those others who also struggle a bit:
I've installed bna with pip:
`pip install bna`
then initialize it, to get the secret for KeePassXC and the serial for Battle.net:
`~/.local/bin/bna new`
and generate the URL with:
`~/.local/bin/bna show-url`
then you'll get an URL like:
`otpauth://totp/Blizzard:####SerialNumber###?secret=#####Secret####issuer=Blizzard&digits=8`

Now you have to put the serial number into the battle.net page and the secret into the KeePassXC custom TOTP settings.
You also have to make settings like showed by @Offerel.
You also must generate your first Code and put it into the Authenticator-Code field on the battle.net page.

**Comment by notNSANE** [comment]
I don't have python, is there any way to do this without installing extra software?

**Comment by Offerel** [comment]
> I don't have python, is there any way to do this without installing extra software?

WinAuth. If i remember correctly out of development, but it works. And is portable.

**Comment by notNSANE** [comment]
I don't quite get it... can I use winauth to generate the urls or whatever for keepass?

**Comment by Offerel** [comment]
You can use Winauth to extract the Secret Key for using it with KeePass.

1.  Open the [WinAuth](https://github.com/winauth/winauth/releases) app and set up Battle.net (Create new Authenticator)
2.  Click the gear icon, then export.
3.  Check the box to protect the ZIP file and enter a basic password.
4.  Hit Browse for where you want to put the file, then hit OK.
5.  Extract that ZIP. The text file should look something like this (the data in this string has been randomized for security): `otpauth://totp/BattleNet:Battle.net?secret=DTQVJKTQK5FN2MMCUFE8RTKARN9RM3AZ&digits=8&issuer=BattleNet&serial=US232383696946`
6.  Copy and paste that string in custom field in KeepassXC with name "otp".
7.  Click save.


You can use a similar procedure for Steam.
