### ISSUE TITLE
Add option to specify specific special characters to use (or exclude) in password generator

### ISSUE THREAD

**Issue by macthecadillac** [keepassxreboot/keepassxc#494]
Hi,

This is not a bug report so there is nothing to reproduce. However, I'm wondering if you guys would eventually add the option for users to choose which special character to include/exclude when generating a random password. The current password generator in both KeePassX and KeePassXC would use any available special character on the US keyboard when the special character group is selected; however, some sites only allow a subset of these special characters to be used while also making the use of such characters mandatory. My current workaround is to use the output of the password generator then swap out those forbidden characters by hand, which is less than ideal. (If I remember correctly, KeePassX 1.x did have such an option.)

KeePassXC version: 2.1.4
Qt Version: Qt 5.7.1
Platform: Debian Stretch

Thanks.

**Comment by droidmonkey** [comment]
This is a nice feature but it vastly complicates the UI to generate a password. We decided to keep things as simple as possible. Recommend you simply delete characters that are not allowed when formulating your password.

**Comment by markismappingman** [comment]
Do you realize how difficult it is to constantly remove characters and then add the ones that are valid for a particular application or website? Most modern password generators contain this feature. There's even a web based tool. I mean really, how difficult is it to add code to only include pre-selected groups and then remove/include the ones manually entered. Sheese!

**Comment by droidmonkey** [comment]
@markismappingman not only did you necropost, but you also didn't do your due diligence before posting a nasty response:

https://github.com/keepassxreboot/keepassxc/pull/1841

This is part of the 2.4.0-beta1 available for testing right now in releases.

**Comment by markismappingman** [comment]
Hmmm. Well, if you had made mention of that there may not have been such a strong response. I wouldn’t say nasty. Anyway, the FAQ page has nothing about this. I couldn’t find any documentation online. And this was the only post regarding this issue. I was simply responding to your ridiculous response to the end user. 

Happy trails.

**Comment by droidmonkey** [comment]
See also #820
