### ISSUE TITLE
KeeShare Import Only Runs When Database is First Opened

### ISSUE THREAD

**Issue by NathanielJS1541** [keepassxreboot/keepassxc#4941]
## Overview
As far as I understand from the [Quickstart guide](https://github.com/keepassxreboot/keepassxc/blob/develop/docs/QUICKSTART.md#user-content-using-sharing), if a folder is set to "Import" from a KeeShare Signed Container, it is supposed to monitor the container and update the database when it sees a change. I have found that the database never detects a change I make, and will only update passwords when the database is first opened (Or the import setting is turned off and then on again).

## Steps to Reproduce
1. Create two new databases (Test1 and Test2) and open both in the same KeePassXC Window.
2. Enable Import and Export in the KeePass settings.
3. Set the Root folder of Test1 to Export to a KeeShare signed container.
4. Set the Root of Test2 to Import from the signed container you just set up.
5. Now create a new entry in Test1 and save it.

## Expected Behavior
I would expect that after saving Test1, the KeeShare container would be updated. Test2 would then update with the new record that has been written to the KeeShare container and update accordingly.

## Actual Behavior
Test2 will not update with the new entry until it is reopened, or the import feature is disabled and re-enabled.

## Context
This may be because of the databases being open in the instance of KeePassXC, therefore they will both be using the same signing key. However I think it is a valid use case to want to have one database sync with another on your machine. For instance I use a Yubikey to unlock my primary password database. If I lose it I need a backup database with all of my 2FA backup codes and passwords which I can store ONLY on my local machine (My main database is carried around on a USB). The easiest way to implement this is to AutoOpen the backup database from my main one when it is available, and have any changes I make to my main database sync to my backup.

### KeePassXC Info
KeePassXC - Version 2.5.4
Revision: c023bf9

Qt 5.14.2
Debugging mode is disabled.

Operating system: Windows 10 Version 2004
CPU architecture: x86_64
Kernel: winnt 10.0.19041

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.5

**Comment by droidmonkey** [comment]
This is fixed in 2.6.0
