### ISSUE TITLE
Save settings in correct folderstructure under Haiku

### ISSUE THREAD

**Issue by BeOSR** [keepassxreboot/keepassxc#4942]
## Summary
Save settings in folder /boot/home/config instead of /boot/home/.config

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
To keep Haiku clean, make use of the folderstructures that exist instead of creating new ones next to them.

**Comment by droidmonkey** [comment]
This may be fixed in 2.6.0, if not than it is a Qt bug with getting the standard config folder and you should report it to them at https://bugreports.qt.io

**Comment by droidmonkey** [comment]
have you tried 2.6.0 yet?
