### ISSUE TITLE
Invalid links in the README and INSTALL

### ISSUE THREAD

**Issue by sorairolake** [keepassxreboot/keepassxc#4943]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
The links to the following docs in `README.md` and `INSTALL.md` are invalid:
* `keepassxc-cli` man page (DIR was changed)
* `QUICKSTART.md` (removed)
* `KEYBINDS.md` (removed)

Related PR: #4937

**Comment by sorairolake** [comment]
`QUICKSTART.md` and `KEYBINDS.md` were removed, but it has not been reflected in `README.md` and `INSTALL.md`.

**Comment by droidmonkey** [comment]
Thank you good catch, will update these with the CHANGELOG
