### ISSUE TITLE
keepassxc-snap-helper.sh fails when run with sh

### ISSUE THREAD

**Issue by xpusostomos** [keepassxreboot/keepassxc#4946]
## Overview

keepassxc-snap-helper.sh comes with no instructions. None. None at all.

Now when I see a file with an extension .sh, my natural inclination is to run...
sh script.sh

Yeah, maybe I'm old school, but that's how things were for like... decades. Then you've got your ordinary users who can't even get that far.

And keepassxc-snap-helper.sh does not run with /bin/sh. Why you'd bother going to the trouble of making it non posix shell compliant, I don't know. Sure, it has #!/bin/bash in it, but files downloaded from the internet are not executable by default, so your typical dumb user won't get past that hurdle either.  Apart from having instructions on the web site, it wouldn't hurt to have instructions in the script itself. Unless you mean keepassxc to be exclusively for UNIX geeks.

## Steps to Reproduce
1.  sh keepassxc-snap-helper.sh
2. Choose chromium
3. fail, scripting error.

## Expected Behavior
1. Having instructions on the web site.
2. Preferably have it posix shell compliant, or else have a .bash file extension
3. have instructions within the script itself.

## Actual Behavior
syntax error

**Comment by droidmonkey** [comment]
Aren't you a ray of sunshine! I made the necessary changes to allow the script to be run by sh: https://github.com/keepassxreboot/keepassxc/commit/138378626f652f75a9e7e2ab4469e1eb0d134a02

**Comment by Sinead-CYF** [comment]
Hi, 

Newb here, I'm trying to figure out what I do with this file and I'm trying to troubleshoot keepassxc browser incompatibilities, such a pain.

**Comment by droidmonkey** [comment]
Download the file, open a terminal, navigate to where the file is located, run file using .\keepassxc-snap-helper.sh
