### ISSUE TITLE
Autotype via hotkey for a sepcific entry?

### ISSUE THREAD

**Issue by TheCataliasTNT2k** [keepassxreboot/keepassxc#4947]
## Summary
I want a feature so that I can use a shortcut to trigger autotype for a specific entry, and only that entry, without being in a specific window. So I can store my sudo password in the database or whatever, and when I press this shortcut, it triggers the autotype for exactly that entry I want to have and types it in.
Can also be solved via shortcuts which trigger a command and uses the cli of keepassxc in the terminal. But not even this cli does provide such a feature.
I do not want to copy the password, because I have a program to "log" my clipboard, so I can have multiple clipboard entries, and switch between them. My password would also be stored in there, and I don't want that (clipman).

**Comment by hifi** [comment]
You can setup auto type to always prompt and have a wildcard entry for your terminal window so that it will always be offered but never typed without confirmation.

**Comment by droidmonkey** [comment]
We won't be implementing a shortcut PER entry. There is another request to bind an entry/sequence to a window handle/class which would overcome the window title issues. But until then, @hifi suggestion is the best way.

**Comment by TheCataliasTNT2k** [comment]
Sure, I can do that, BUT it takes longer to get the keepassxc window into foreground, search for the entry and click on "autotype" than pressing just a shortcut. As I said, you do not need to make a shortcut per entry, it would be enough, if I can trigger autotype via the cli, providing for example the uuid of the entry to be typed. This would enable me, to set a custom shortcut on that command. Its the same like (copied from the help of `keepassxc-cli`), but instead of copying, trigger autotype.
`clip           Copy an entry's password to the clipboard.`

**Comment by hifi** [comment]
You can trigger auto type with a global shortcut which you configure in keepassxc settings. That's pretty much what you describe but you still need to confirm the entry in the pop-up window.
