### ISSUE TITLE
Site says supported on macOS 10.12 and later, but doesn't appear to run due to QT Error

### ISSUE THREAD

**Issue by robint** [keepassxreboot/keepassxc#4949]
I have 10.12.6  however when I try to run the program I get this error:

-
KeePassXC cannot be opened because of a problem.

Check with the developer to make sure KeePassXC works with this version of macOS. You may need to reinstall the application. Be sure to install any available updates for the application and macOS.

Click Report to see more detailed information and send a report to Apple.

[Ignore]  [Report]
--

When I look at the crash report. I think I found the issue, it looks like the version of QAGui was build for MacOs 10.13

—
Dyld Error Message:
  Symbol not found: _OBJC_CLASS_$_MTLCaptureManager
  Referenced from: /Applications/KeePassXC.app/Contents/MacOS/../Frameworks/QtGui.framework/Versions/5/QtGui (which was built for Mac OS X 10.13)
  Expected in: /System/Library/Frameworks/Metal.framework/Versions/A/Metal
 in /Applications/KeePassXC.app/Contents/MacOS/../Frameworks/QtGui.framework/Versions/5/QtGui
—

Of course it could be something else. But looks like it may be the issue to me.

If needed can attach the full crash report

**Comment by droidmonkey** [comment]
Unfortunately we will not be shipping custom Qt binaries so this will be a WONTFIX.

**Comment by robint** [comment]
I was thinking you should fix the documentation to say you only support 10.13.xx.

but of course would not have turned down a a binary that was complied against a older version :)
(Which had to have been the case at one point otherwise 10.12 would not be listed as a supported version)

**Comment by robint** [comment]
Nice. I see you updated the site. I would mark as fixed :)

**Comment by phoerious** [comment]
For 2.5, there is a binary that should be running on 10.12. For 2.6, we will not support this version of macOS anymore.
