### ISSUE TITLE
Release 2.6.0 marked as pre-release, no macOS binaries

### ISSUE THREAD

**Issue by crunchtime-ali** [keepassxreboot/keepassxc#4951]
I was about to update the Homebrew Cask of KeepassXC when I noticed that:

- the 2.6.0 release is marked as a pre-release
- the macOS binaries are missing

Is there a reasoning behind this?

/cc @droidmonkey

**Comment by phoerious** [comment]
It's marked as pre-release for a reason. We are not done building all the packages yet.

**Comment by crunchtime-ali** [comment]
> It's marked as pre-release for a reason. We are not done building all the packages yet.

Understood.
