### ISSUE TITLE
UNC paths are not handled properly (when they point to WSL)

### ISSUE THREAD

**Issue by oliversalzburg** [keepassxreboot/keepassxc#4953]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Export a file that's stored in a database into a WSL location or try to open a KeeShare that resides in WSL.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Files are opened and stored from and to the locations selected.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
KeePassXC doesn't understand the path and saves to an invalid location or is unable to open files from the selected location.

## Context
[NOTE]: # ( Give us any additional information you may have. )
When I try to open `\\wsl$\Ubuntu\home\oliver\foo.kdbx.share` it is interpreted as `\Ubuntu\home\oliver\foo.kdbx.share`. Files I save into the WSL location sometimes end up in completely different folders. Or KeePassXC created `C:\Ubuntu\home\oliver\` and places the files there. There's also a myriad of errors that happen when repeating the process.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.5.4
Revision: c023bf9

Qt 5.14.2
Debugging mode is disabled.

Operating system: Windows 10 Version 2004
CPU architecture: x86_64
Kernel: winnt 10.0.19041

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.5

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 10

**Comment by phoerious** [comment]
Probably something Qt has to fix.

**Comment by malobre** [comment]
See [QTBUG-86277](https://bugreports.qt.io/browse/QTBUG-86277), it was fixed in Qt version `5.15.2`.
