### ISSUE TITLE
2.6.0 is listed as a "Preview Release"

### ISSUE THREAD

**Issue by michaelblyons** [keepassxreboot/keepassxc#4954]
## Overview
On [the releases page](https://github.com/keepassxreboot/keepassxc/releases), the 2.6.0 release is marked "Pre-release."

## Expected Behavior
If it's still pre-release, maybe it should have `-beta2` or something appended?

## Actual Behavior
Next logical semver version is marked "pre-release"

**Comment by phoerious** [comment]
Patience. We're not finished.

**Comment by michaelblyons** [comment]
Oops. I should have caught #4951 as well.
