### ISSUE TITLE
Unexpected update to v2.6.0

### ISSUE THREAD

**Issue by AngelHair** [keepassxreboot/keepassxc#4955]
I am running Ubuntu 18.04.4 LTS and my KeePassXC apparently just upgraded itself to v2.6.0.  This is one of the two versions that currently show on the Ubuntu Software repository (the other shows as 2.3.1+dfsg.1-1).  Was this supposed to happen?  If not, what should I do.  If so, I would like to express my extreme displeasure at being surprised this way.  Either way, I think the new icons are junk.  Is there a way to use the old icons?  I looked around, and tried different themes, but I cannot find the old, good-looking icons.
![Screenshot from 2020-07-07 13-08-01](https://user-images.githubusercontent.com/14369583/86817928-addd4700-c053-11ea-9eeb-f14bb0ea3dea.png)

**Comment by phoerious** [comment]
It's surprisingly early, but yeah, that's supposed to happen. But you should also be seeing the new UI theme by default.

**Comment by droidmonkey** [comment]
You are using the snap distribution which is automatically updated based on our master branch. Welcome to the future.

**Comment by dijit** [comment]
> master branch.

OT: please don't use problematic terms. (◠‿◠✿)

**Comment by phoerious** [comment]
Oh, right. We should rename it to "partner" branch.
