### ISSUE TITLE
KeepassXC 2.6.0 on Ubuntu Budgie 20.04 not recognized Hardware Key (YubiKey) 

### ISSUE THREAD

**Issue by artemusgit** [keepassxreboot/keepassxc#4957]
## Overview
By using KeepassXC 2.6.0 on Ubuntu Budgie 20.04 a yubikey (hardware key with challenge response) not listed in the combobox. Manually enable the raw-usb interface in order to use the YubiKey (sudo snap connect keepassxc:raw-usb core:raw-usb) does not solve the problem.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
    Update KeepassXC 2.5.4 to KeepassXC 2.6.0 (as Snap)
    Open a existing database secured by a password, keyfile and challenge response
    Try to select a hardware key (none are listed)
    Click 'Refresh' --> still no hardware keys listed
    Fail to unlock database

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Yubikey is recognized an listed in the combobox

## Actual Behavior
Still no hardware keys listed in the combobox

## Context
Yubikey-Support reproduced the issue and it didn't work too. They report back it appears to be an issue with KeepassXC. The approach described on "https://keepassxc.org/docs/#faq-appsnap-yubikey" does not solve the problem.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION  2.6.0
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: Ubuntu Budgie 20.04
Desktop Env: Budgie
Windowing System: X11/Wayland

**Comment by droidmonkey** [comment]
Couldn't replicate. I gave KPXC Snap the permission to read raw USB and restarted the app. Worked first time after pressing "Refresh" to find hardware keys.

**Comment by droidmonkey** [comment]
Although I did this on Ubuntu 20.04, but it would seem this is a Budgie bug if it is not working for you on that distro.

**Comment by droidmonkey** [comment]
I replicated on Budgie, but there isn't anything we can do, its a bug on their end. You can use the Appimage distribution.

**Comment by droidmonkey** [comment]
Tested on Budgie and found the problem. On Budgie the Yubikey device is controlled by root, if you run KeePassXC as root (sudo) it works. Also running `ykinfo -s` from the terminal shows the following message: `USB error: Access denied (insufficient permissions`. Looks like udev or similar needs to be configured to mount the usb device in user space.

**Comment by artemusgit** [comment]
I followed the suggested solution, but unfortunately I couldn't fix the error. "ykinfo -s" displays the serial number and does not indicate the USB-error message. In addition, the Yubikey is addressed when "reloading" (recognizable by the green signal).

**Comment by droidmonkey** [comment]
Then you have the yubikey bug that is fixed in 2.6.1.

**Comment by artemusgit** [comment]
Thank you for the quick response and the hint. I already suspected that it will be fixed with version 2.6.1.

**Comment by droidmonkey** [comment]
You can workaround it immediately by using a snapshot build: https://snapshot.keepassxc.org
