### ISSUE TITLE
wiki fails to mention build dependency asciidoctor

### ISSUE THREAD

**Issue by c4rlo** [keepassxreboot/keepassxc#4958]
#4937 introduced a build dependency on `asciidoctor`. This is mentioned in [INSTALL.md](https://github.com/keepassxreboot/keepassxc/blob/master/INSTALL.md), but also needs to be added to the relevant wiki pages:

- https://github.com/keepassxreboot/keepassxc/wiki/Set-up-Build-Environment-on-Linux
- https://github.com/keepassxreboot/keepassxc/wiki/Set-up-Build-Environment-on-macOS
- https://github.com/keepassxreboot/keepassxc/wiki/Building-KeePassXC

**Comment by c4rlo** [comment]
Btw, I would have edited the wiki myself but don't have the privs.

**Comment by droidmonkey** [comment]
Done.
