### ISSUE TITLE
Some of the new icons look too similar

### ISSUE THREAD

**Issue by anewuser** [keepassxreboot/keepassxc#4960]
## Summary
I like version 2.6.0 and think that you've done a good job improving the program, but the new monochrome icons look too similar, especially in the context menu. Consider adding some color to them.

I right-clicked an entry to delete it, and wasn't able to tell what the delete option was without reading the text. If the icon was red, I'd have found it much faster. I think that the repeated word "Entry..." could also be dropped from the first three items to make it easier to find what you're looking for:

![too similar](https://user-images.githubusercontent.com/6733770/86829178-7d54d780-c06a-11ea-94ca-cca8e0a40feb.png)

To improve usability, even Microsoft is changing the Windows 10 icons to make them colorful again too: [Microsoft rolls out colorful new Windows 10 icons](https://web.archive.org/web/20200702051800/https://www.theverge.com/2020/2/20/21145157/microsoft-windows-10-new-icons-modern-release-update-apps).

**Comment by AngelHair** [comment]
I second the motion that the new icons are a big step backward into the low resolution monochrome past.  The old icons were much better.

New Icons: Just because you can do it does not make it a good idea.

**Comment by phoerious** [comment]
> into the low resolution monochrome past.

If something was low resolution, it's the old icons. They were 16x16 for the database icons and 24x24 for the rest. It looked horrible on low DPI already and completely unbearable on high DPI.

**Comment by droidmonkey** [comment]
These icons are not going to receive color and we won't be changing the name of the action.

**Comment by anewuser** [comment]
@droidmonkey don't you agree them look too similar in the menu, though? Since you like monochrome icons, what about choosing another set or at least editing the current one for the icons to stand out next to each other?

**Comment by droidmonkey** [comment]
Sure they look similar, you'll get used to it. You are always welcome to use your own icons in a fork

**Comment by anewuser** [comment]
They might have been proposed and discussed by the people who are active in the development, but only starting this week the majority of regular users will be seeing them for the first time, including people with limited computer skills and sight. 

I won't bother you with this topic again, but please don't let the minority of users who also have Github accounts and give you rude feedback influence your opinion on whether to address issues that also affect all the other users.

**Comment by droidmonkey** [comment]
We receive feedback from all over the place, not just GitHub. We trialed 4 different styles of icons for the entry actions and the circle-based icons were the least busy of the lot. I'm open to options if you find them, but we are not going to make the action icons color-based again.
