### ISSUE TITLE
Link GettingStarted and UserGuide are bad on Linux

### ISSUE THREAD

**Issue by webafrancois** [keepassxreboot/keepassxc#4964]
## Overview
[TIP]:  # clic on the Help menu to "Gettingstarted" and "UserGuide" show just licence and contact us 
[NOTE]: # There is no UserGuid and no help for new user on KeepassXC software

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. clic on help menu
2. choose UserGuide or Getting Sarted
3. read the web page on : 
file:///usr/share/keepassxc/docs/KeePassXC_UserGuide.html or 
file:///usr/share/keepassxc/docs/KeePassXC_GettingStarted.html

## Expected Behavior
[NOTE]: # I would see the good help pages.

## Actual Behavior
[NOTE]: # Just  
* License and Disclaimers
* Disclaimer of Warranty
* Limitation of Liability
* Contact Us

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.6.0
Revision: 0765954
2.6.0-1ppa3~bionic1 installed from https://launchpad.net/~phoerious/+archive/ubuntu/keepassxc

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux Mint 19.3 - 64bits
Desktop Env: Mate
Windowing System: X11

**Comment by sts10** [comment]
Having a similar issue. 

I installed to Ubuntu via Snap. For me, both `file:///snap/keepassxc/978/usr/share/keepassxc/docs/KeePassXC_GettingStarted.html` and `file:///snap/keepassxc/978/usr/share/keepassxc/docs/KeePassXC_UserGuide.html` load, but they only have these four sections in the document:

```
Table of Contents

    License and Disclaimers
        Disclaimer of Warranty
        Limitation of Liability
    Contact Us
```

## My debug info
KeePassXC - Version 2.6.0
Revision: 0765954
Distribution: Snap

Qt 5.9.5
Debugging mode is disabled.

Operating system: Ubuntu Core 18
CPU architecture: x86_64
Kernel: linux 5.3.0-7648-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.1

**Comment by droidmonkey** [comment]
This is most likely because of legacy version of asciidoctor not understanding new syntax.

**Comment by droidmonkey** [comment]
This is a known bug in the snap distro currently. I cannot get the docs to open (tried multiple ways) when run as a snap.

**Comment by phoerious** [comment]
@droidmonkey Is this fixable short-term? If not, postpone to 2.8.0.

**Comment by droidmonkey** [comment]
It works fine everywhere except snaps, of course. 2.8.0 it is

**Comment by droidmonkey** [comment]
We are not going to expend time to fix this, use the flatpak verison.
