### ISSUE TITLE
AppImage indefinitely checks for an update due to an SSL error

### ISSUE THREAD

**Issue by idunno101** [keepassxreboot/keepassxc#4965]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
When checking for an update on 2.5.4 an SSL error is output to the system log but there is no indication of the error in the UI.

I noticed that this issue seems to be a repeat of #3280 and is also probably related to #4219
I don't know if this has been corrected in 2.6.0 but if not then it could be looked at.
It's fine if bundling OpenSSL isn't an option but I think that some kind of error should be shown and it could refer the user to Github to check for new releases.
## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Open KeePassXC 
2. Help -> Check for Updates

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Expected a notification that an update was avilable
Or for the check to time out at some point

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
This error appears in journalctl:
`qt.network.ssl: QSslSocket::connectToHostEncrypted: TLS initialization failed`

The dialog appears as if it is still checking (left it running for over an hour)
[![keepassxc.png](https://i.postimg.cc/2y87PsdL/keepassxc.png)](https://postimg.cc/0MFSSHB9)
## Context
[NOTE]: # ( Give us any additional information you may have. ) 

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.5.4
Revision: dcca5aa
Distribution: AppImage

Qt 5.12.7
Debugging mode is disabled.

Operating system: Fedora 32 (Workstation Edition)
CPU architecture: x86_64
Kernel: linux 5.7.6-201.fc32.x86_64

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.1

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux (Fedora 32)
Desktop Env: Gnome
Windowing System: Wayland

**Comment by droidmonkey** [comment]
2.6.0 is released, test it and report back

**Comment by phoerious** [comment]
I don't think this is fixed. It's a known issue with AppImages and the way they handle OpenSSL. It's near-impossible to do it right, unfortunately.

**Comment by idunno101** [comment]
> 2.6.0 is released, test it and report back

Same behaviour after the initial download yesterday but after restarting the system today it gives a proper error message when checking for updates.

[![Screenshot-from-2020-07-08-09-36-37.png](https://i.postimg.cc/fR1NR3sz/Screenshot-from-2020-07-08-09-36-37.png)](https://postimg.cc/G4PNMm9V)

The update looks great by the way :+1: Thank you for your work

**Comment by matibarriento** [comment]
Having the same issue with AppImage 2.6.0. Same error with the HIBP report
![image](https://user-images.githubusercontent.com/5904261/88067186-0d078500-cb45-11ea-85ab-91c2a0f2e692.png)

**Comment by grande-mephistopheles** [comment]
Hi, is there any update on this? I'm thinking of watching the github releases as I have no other way to get updates.

**Comment by phoerious** [comment]
It's almost impossible to fix, unfortunately. We are looking for alternatives.

**Comment by worddiangames** [comment]
> Hi, is there any update on this? I'm thinking of watching the github releases as I have no other way to get updates.

For KeePassXC 2.7.4 / 2.7.5, I fixed the update error by installing libssl1.1

Installation instructions from here:
https://gist.github.com/joulgs/c8a85bb462f48ffc2044dd878ecaa786

`wget http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.0g-2ubuntu4_amd64.deb`
`sudo dpkg -i libssl1.1_1.1.0g-2ubuntu4_amd64.deb`
