### ISSUE TITLE
KeePassXC v2.6.0 crashing after downloading favicons

### ISSUE THREAD

**Issue by mgoodman** [keepassxreboot/keepassxc#4966]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
KeePassXC v2.6.0 on MacOS crashes consistently when downloading favicons if the download screen is closed before the database finishes saving.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Right click on any entry that has a URL and select Download Favicon
2. Wait for the Favicon download to finish
3. Click "Close" on the favicon download screen before the database has finished saving in the background

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
KeePassXC should finish saving and remain open / usable.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
KeepPassXC crashes after saving is complete and must be re-opened.

## Context
[NOTE]: # ( Give us any additional information you may have. )
This seems to happen regardless of whether or not I have DuckDuckGo favicon lookup enabled in the security settings. I have not seen it crash yet if I wait for the database to finish saving in the background before closing the download window. I can provide a video of the crash happening if you want.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.0
Revision: 0765954

Qt 5.15.0
Debugging mode is disabled.

Operating system: macOS 10.15
CPU architecture: x86_64
Kernel: darwin 19.5.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
 libgcrypt 1.8.5

**Comment by Drumstickx** [comment]
I can reproduce this behavior on Arch Linux for version 2.5.4 - Revision: `dcca5aa`.

**Comment by ruanmed** [comment]
I can reproduce this behavior on on Linux Mint 19.3 for version 2.6.0 - Revision: `0765954`.

I can also add the information that the same behavior happens when you right click a folder or go into the Groups  and select the _Download All Favicons..._  option, but ONLY when just a single entry gets into the queue and a new favicon is found for it, if there are multiple entries in the Download Favicons queue does not matter if any of then are successful or not, the application works as supposed.

**Comment by riosdcs** [comment]
In case it's helpful, figured I'd add that this affects Windows 10 as well on version 2.6.0 - Revision: `0765954`

**Comment by droidmonkey** [comment]
This crashes here: https://github.com/keepassxreboot/keepassxc/blob/b6787d91a30c965bf4dbf6b9fd9714e014a1a55a/src/gui/DatabaseWidget.cpp#L1833

The reason is because the pointer "focusWidget" points to the Icon Downloader box which was deleted when closed.
