### ISSUE TITLE
Theme choosing option missing in 2.6.0 release

### ISSUE THREAD

**Issue by koelle25** [keepassxreboot/keepassxc#4968]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
The option to switch between the light and the dark theme is missing in the general settings under "User interface". On the 2.6.0-beta1 it was available. See screenshots.
### 2.6.0 release
![Bildschirmfoto vom 2020-07-08 01-02-27](https://user-images.githubusercontent.com/915514/86853907-bcf5e080-c0b7-11ea-8143-caa3ce7845f4.png)
### 2.6.0-beta1
![Bildschirmfoto vom 2020-07-08 01-02-50](https://user-images.githubusercontent.com/915514/86853917-bf583a80-c0b7-11ea-9837-c30e3d7e9769.png)

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Go to *Tools* > *Settings*
2. Look under *General* > *User Interface*
3. See missing *Application theme* option

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
The possibility to change the application theme from light (seems to be default) to dark.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Nothing. Besides the fact, that the icon bar is also buggy, may be related (see #4963).

[NOTE]: # ( Paste debug info from Help → About here )
### 2.6.0 Release
```
KeePassXC - Version 2.6.0
Revision: 0765954

Qt 5.9.5
Diagnosemodus ist deaktiviert.

Betriebssystem: Linux Mint 19.3
CPU-Architektur: x86_64
Kernel: linux 5.3.0-62-generic

Aktivierte Erweiterungen:
- Auto-Type
- Browser-Integration
- SSH-Agent
- KeeShare (bestätigtes und unbestätigtes Teilen)
- YubiKey
- Secret-Service-Integration

Kryptographische Bibliotheken:
 libgcrypt 1.8.1
```
### 2.6.0-beta1
```
KeePassXC - Version 2.6.0-beta1
Build Typ: PreRelease
Revision: e5b0219
Distribution: AppImage

Qt 5.14.2
Diagnosemodus ist deaktiviert.

Betriebssystem: Linux Mint 19.3
CPU-Architektur: x86_64
Kernel: linux 5.3.0-62-generic

Aktivierte Erweiterungen:
- Auto-Type
- Browser-Integration
- SSH-Agent
- KeeShare (bestätigtes und unbestätigtes Teilen)
- YubiKey
- Secret-Service-Integration

Kryptographische Bibliotheken:
 libgcrypt 1.8.1
```

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux (Linux Mint 19.3)
Desktop Env: Cinnamon
Windowing System: X11

**Comment by piramiday** [comment]
I think they just moved it: https://github.com/keepassxreboot/keepassxc/issues/4963#issuecomment-655179742
> Theme choice is now in the view menu
