### ISSUE TITLE
Automatic database locking does not work with the Xfce screensaver

### ISSUE THREAD

**Issue by IngoMeyer441** [keepassxreboot/keepassxc#4969]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
Since Xfce 4.14 the desktop environment ships an own screensaver and registers as dbus service `org.xfce.ScreenSaver`. Support for the xfce screensaver can probably be added like in PR #1249 by simply replacing `gnome` with `xfce`.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Activate "Lock databases when session is locked or lid is closed".
2. Lock the Xfce screensaver (e.g. by pressing Ctrl+Alt+Del)
3. Unlock the screensaver
4. The database is still unlocked

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
The database should be locked when the screensaver is activated.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
The screensaver state does not influence if the database is locked or not. However, closing the lid or going to sleep locks the database.

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.5.4
Revision: dcca5aa

[NOTE]: # ( Pick choices based on your environment )
Operating System: Manjaro Linux
Desktop Env: Xfce 4.14
Windowing System: X11

**Comment by phoerious** [comment]
Thank God they introduced their own interface and didn't adhere to boring standards.

**Comment by PolyMMA** [comment]
This issue persists in KeePassXC - Version 2.6.2. Same steps of reproducing the error are still valid.

```
KeePassXC - Version 2.6.2
Revision: e9b9582

Qt 5.9.5
Debugging mode is disabled.

Operating system: Ubuntu 18.04.5 LTS
CPU architecture: x86_64
Kernel: linux 4.15.0-122-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.1
```


additional system info:
```
System:    Host: ***** Kernel: 4.15.0-122-generic x86_64 bits: 64 gcc: 7.5.0
           Desktop: Xfce 4.12.3 (Gtk 2.24.31) info: gnome-shell,xfce4-panel dm: gdm3
           Distro: Ubuntu 18.04.5 LTS
```

**Comment by droidmonkey** [comment]
Huh, this should be closed. OP coded the fix and we merged it into 2.6.1

**Comment by PolyMMA** [comment]
Well...  It still does not lock in xfce4 on ubuntu 18.

**Comment by IngoMeyer441** [comment]
I use the builtin XFCE screensaver (and the fix is only for this screensaver). But you use the XScreensaver which is not recognized by KeePassXC I think. Maybe it uses another yet unsupported dbus interface. :disappointed:
