### ISSUE TITLE
Inconsistent Focus Behavior When Activating From Tray

### ISSUE THREAD

**Issue by metal450** [keepassxreboot/keepassxc#4970]
## Overview
When activating the main window by single-clicking the tray icon, it usually restores the window to the foreground (as desired). Sometimes, however - seemingly at random - it restores behind the current window (unexpected).  In this latter case, it still appears first in the alt-tab program list, as though it were in the foreground - so you must alt-tab *twice* to bring it to the foreground.

## Steps to Reproduce
1. Settings->General->Basic->Minimize window at application startup
2. Settings->General->Basic->Minimize window after unlocking database
3. Settings->General->Basic->Minimize instead of app exit
4. Settings->General->Basic->Show a system tray icon
5. Settings->General->Basic->Hide window to system tray when minimized
6. Open & unlock your database
7. Minimize the main window (to tray)
8. Open some other application (i.e. Firefox)
9. Single-click the KeePassXC tray icon to reveal the main window

## Expected Behavior
Main window appears in the foreground

## Actual Behavior
Sometimes - seemingly at random - the main window restores behind the current application (i.e. Firefox).  It still appears first in the alt-tab program list, as though it were in the foreground - but it isn't.

KeePassXC - 2.6.0
Revision: 0765954
Operating System: Linux
Desktop Env: KDE
Windowing System: X11

**Comment by metal450** [comment]
For fear of seeming impatient - I wonder if anyone has come up with at least a workaround for this? I find it quite frustrating as it's something I deal with day in & day out, each & every day since switching over to Linux :/  Even a bandaid would be much appreciated, if or until a proper bug fix has been implemented :)

**Comment by droidmonkey** [comment]
What version of KDE are you using?

**Comment by metal450** [comment]
Kubuntu 20.04
KDE Plasma 5.18.5
KDE Frameworks 5.68.0
Kernel 5.4.42-050442

**Comment by metal450** [comment]
(...w/ apt fully updated)

**Comment by Kansai53** [comment]
I'm experiencing this issue too, still on KeePass 2.6.3

**Comment by phoerious** [comment]
My guess is that we cannot really do anything about that. KWin makes a lot of assumptions about how windows are supposed to be activated. You can try to setting the focus stealing prevention for the application or window to none.

https://docs.kde.org/trunk5/en/kde-workspace/kcontrol/windowbehaviour/index.html#action-focus

**Comment by Kansai53** [comment]
Thanks will give that try.  But I should say that of all the many softwares I have, this doesn't happen to any other, it is a problem unique only & solely for KeePassXC.
