### ISSUE TITLE
2.6.0 fails to launch on macOS Catalina

### ISSUE THREAD

**Issue by alan-ogilvie** [keepassxreboot/keepassxc#4973]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

![image](https://user-images.githubusercontent.com/47188595/86901698-e25d0b80-c104-11ea-8dd5-9f69a8986239.png)

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Update keepassxc using `brew cask upgrade`
2. Launch keepassxc from the Applications folder

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Application should launch successfully, as it did with the previous release

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Application fails to launch with the system warning shown above

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.6.0
Revision: Unknown (since app fails to launch)

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS Catalina
Desktop Env: macOS
Windowing System: macOS

**Comment by phoerious** [comment]
Oh, Apple again. The DMG is signed and notarised, I really have no idea what's wrong this time. Can anybody reproduce this?

**Comment by varjolintu** [comment]
Could not reproduce this with macOS Catalina 10.15.5.

**Comment by h0lgerg** [comment]
For me it is starting without any issues on Catalina 10.15.5.

**Comment by alan-ogilvie** [comment]
I'm running Catalina 10.15.2 - maybe it's time to hit the update button...

**Comment by alan-ogilvie** [comment]
Upgrading to Catalina. 10.15.6 fixed the problem
