### ISSUE TITLE
2.6.0 - Tray Icon shows missing icon

### ISSUE THREAD

**Issue by syphernl** [keepassxreboot/keepassxc#4974]
## Overview
After upgrading to 2.6.0 the tray-icon shows a "missing icon" image. 

![image](https://user-images.githubusercontent.com/639906/86915716-c10b1800-c122-11ea-8d0b-10376dd53f09.png)
(KeePassXC is the 2nd icon from the left)

I have tried all Tray Icon Type's but neither actually show any icons right now.

It could be related to #4963, but since I didn't know whether that's caused by the same thing I'm opening a separate issue.

## Context
```
KeePassXC - Version 2.6.0
Revision: 0765954

Qt 5.12.8
Debugging mode is disabled.

Operating system: Ubuntu 20.04 LTS (Budgie)
CPU architecture: x86_64
Kernel: linux 5.4.0-40-generic
```

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: Budgie
Windowing System: X11

**Comment by phoerious** [comment]
Same issue.
