### ISSUE TITLE
Feature request : add dark window frame in windows 10

### ISSUE THREAD

**Issue by F3000** [keepassxreboot/keepassxc#4975]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )

At the moment the top bar is white . Windows itself is turned into dark mode .

See attached picture 
![image](https://user-images.githubusercontent.com/8161283/86917240-0892a380-c125-11ea-903d-ebb89cc36c32.jpeg)

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )

**Comment by droidmonkey** [comment]
We tried and it's not possible

**Comment by musm** [comment]
This has nothing to do with KeeAgentXC

Just set registry keys to 

```
Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\DWM]
"AccentColor"=dword:171717
"AccentColorInactive"=dword:171717
"ColorPrevalence"=dword:1

```
