### ISSUE TITLE
Fix sorting of database report columns

### ISSUE THREAD

**Issue by jacopotediosi** [keepassxreboot/keepassxc#4976]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
Sorting by score in database integrity check is done in alphabetical sort instead of in natural sort, so for example 9 is considered greater than 64.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
Database menù --> Database Report --> Integrity Check --> Order by score column

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Rows should be sorted by score in natural order

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
![image](https://user-images.githubusercontent.com/20026524/86920810-8f964a80-c12a-11ea-8f91-fb8f42dcb1cf.png)

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.0
Revision: 0765954

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 10

**Comment by droidmonkey** [comment]
Good find!

**Comment by NikolausDemmel** [comment]
Might be the same in the score column of the health check report. Also breaks sorting for negative numbers.

**Comment by stefan123t** [comment]
As a side note, I also noticed the alphabetical sort order for the score.
Also Sorting by severity does not sort by numerical score, results are only grouped per category (red, orange, green) but otherwise remain unsorted.

**Comment by rocketraman** [comment]
Also applies to the "Password Exposed" column in the HIBP report.

**Comment by jacopotediosi** [comment]
Fixed with #5426 (merged)
