### ISSUE TITLE
Bug: new “database unlock” screen doesent get mouse focus

### ISSUE THREAD

**Issue by F3000** [keepassxreboot/keepassxc#4977]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. When windows is locked try to unlock 
2. Open a website which has an entry in database 
3. Click KeepassXC icon in the password field -> new database unlock screen pops up 
4. Try to enter password

This is not possible directly because the user have to click first in the window to make it active . 
Than password type in is possible 

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

Directly make this window active so we don’t need a mouse click first to type the password 

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows/Linux/macOS
Desktop Env: Gnome/KDE/XFCE/Mate/Cinnamon
Windowing System: X11/Wayland

**Comment by droidmonkey** [comment]
This is a windows problem that we cannot solve. Focusing windows is very hit and miss on windows and we already do everything we can to make it work correctly.

**Comment by F3000** [comment]
Thanks for explaining
