### ISSUE TITLE
Character Types for Passphrase

### ISSUE THREAD

**Issue by kwilson4** [keepassxreboot/keepassxc#4978]
When generating a password in KeePass you can pick the character types used in the password. It would be handy to have the same options when generating a passphrase as well.

**Comment by kwilson4** [comment]
To add to the above, the feature could be similar to how you can generate a passphrase through this website: https://correcthorsebatterystaple.net/

**Comment by droidmonkey** [comment]
We already do all that.

**Comment by kwilson4** [comment]
Oh ok, where do I get to choose the included characters or ending characters? I know I can change the word separator and word case, but looking to add number(s) in passwords as well. Thanks!

**Comment by droidmonkey** [comment]
We don't have any intention of supporting that for passphrase. You can add a number yourself in the generated phrase.
