### ISSUE TITLE
Automatic theme defaults to dark on macOS 10.13

### ISSUE THREAD

**Issue by j-schultz** [keepassxreboot/keepassxc#4979]
## Overview
I upgraded to KeePassXC 2.6 on macOS 10.13. By default the theme is set to "Automatic". Given that Dark Mode was introduced in macOS 10.14, I expected that "Automatic" would resort to the light theme, but after upgrading I was greeted by the dark theme instead, which doesn't fit particularly well into the OS theme.

## Steps to Reproduce
1. Set theme to automatic on macOS 10.13.

## Expected Behavior
It should match the OS theme (which is light on macOS 10.13)

## Actual Behavior
It falls back to using the dark theme, which is not consistent with the OS.

**Comment by phoerious** [comment]
We are using the macOS API to detect your current theme, so it looks like your system thinks that it's in dark mode..

**Comment by j-schultz** [comment]
But does that API even exist in macOS 10.13? From what I know, dark mode was only introduced in macOS 10.14 so I suppose you get a bogus value when calling that API in older macOS versions.

**Comment by phoerious** [comment]
Probably not.

**Comment by droidmonkey** [comment]
Closing this based on the 10.14 introducing dark mode. Just pick a them instead of automatic.

**Comment by phoerious** [comment]
I think we could just default to light on pre-10.4.

**Comment by droidmonkey** [comment]
This is really a non issue
