### ISSUE TITLE
Windows hello unlock

### ISSUE THREAD

**Issue by aelisya** [keepassxreboot/keepassxc#4980]
## Summary

Hello i want to know if it's possible to add a functionnality to store the password in windows hello, and unlock the database with it like this module for keepass2 does ?

#### A database key is encrypted and decrypted using Windows Hello API in order to unlock the database. KeePass Composite Key data is Encrypted with a Cryptographic Key signed with a Windows Hello Key Credential and saved as a Password Credential to a Password Vault.

**source :** https://github.com/Angelelz/WinHelloUnlock (plugin for keepass2 who does this feature)

## Examples

<img src="https://raw.githubusercontent.com/Angelelz/WinHelloUnlock/master/WinHelloUnlock/Screenshots/WinHello.png" width="400">
<img src="https://user-images.githubusercontent.com/42673166/86942105-0b04f580-c145-11ea-9c7b-20a25ad4fac7.png" width="300">

## Context

With this feature windows user can setup a time lock very fast it doesn't matter since we can unlock the database very fast too (Fingerprint or Face detection of Windows Hello).

**Comment by droidmonkey** [comment]
Search the issue list, duplicate

**Comment by aelisya** [comment]
@droidmonkey you have locked it, and said it's for uwp only, it's not true anymore, so unlock the other or let this one open or said open-fully u don't want this feature. so we don't ask for it anymore.
