### ISSUE TITLE
Kee SSH Agent compatibility with Cygwin/Msys on Windows

### ISSUE THREAD

**Issue by musm** [keepassxreboot/keepassxc#4981]
## Summary

Does anyone know how to setup and have a compatible  keepassxc ssh agent using Windows OpenSSH with Cygwin and WSL2 ?  

I currently have a working setup using KeeAgent on KeePass but am looking to switch, but can't find any guides on how to set this up.

AFAIK KeePassXC using the existing agent, and does not provide an agent itself (as KeeAgent does)?

**Comment by hifi** [comment]
It basically boils down to picking one of the supported agents (OpenSSH or Pageant) and installing additional tools to bridge that into other environments.

I don't remember what tools someone used but in a fairly recent github issue it was discussed and the reporter found a working combination.

**Comment by musm** [comment]
@hifi  Your spot on on needing bridges. I'm just trying to determine what those bridges are for  Cygwin and WSL2. 

For KeeAgent, a Cygwin compatible socket file is required:
![image](https://user-images.githubusercontent.com/4319522/86946685-bea3c080-c118-11ea-827c-16d5dd559c5b.png)

**Comment by hifi** [comment]
For Git you can actually just tell it to use the Windows OpenSSH ssh.exe and it will just work if that is your only Msys2 application.

**Comment by musm** [comment]
> For Git you can actually just tell it to use the Windows OpenSSH ssh.exe and it will just work if that is your only Msys2 application.

I already have that setup.


But I do development using with Cygwin and WSL2 and it's important for me to have one universal  SSH agent across all of these platforms.

**Comment by hifi** [comment]
The issue was #4303 and the reporter ended up using: https://github.com/benpye/wsl-ssh-pageant

**Comment by mxcd** [comment]
I had the same struggles and ended up writing a tool that forwards the pageant identities to WSL:
https://github.com/mxcd/PuttyAuthSock

**Comment by hifi** [comment]
Closing this as well now, thanks.

**Comment by nithinphilips** [comment]
For anyone looking for a Cygwin-pageant bridge: https://github.com/wesleyd/charade
