### ISSUE TITLE
Hide Password - Remove tick not remembered in V 2.6.0

### ISSUE THREAD

**Issue by jeff10104** [keepassxreboot/keepassxc#4982]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
Title says it all.  Unticking Hide Password is not now remembered between sessions.  It always has been for as long as I can remember

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Go to Header Bar
2. Right Click
3. Remove Tick against Hide Password

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Previously the ability to **always** show passwords was remembered between sessions it certainly is in ver 2.5.4

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Show & Hide Passwords setting **is** remembered in the Preview panel
But not in the Main Panel

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows/Linux/macOS
Desktop Env: Gnome/KDE/XFCE/Mate/Cinnamon
Windowing System: X11/Wayland

**Comment by droidmonkey** [comment]
This was by design and purposefully changed based on feedback. I want to move the Hide/Show Username/Password actions into the View menu anyway and disable the keyboard shortcuts. Once moved there it will become persistent again.
