### ISSUE TITLE
Yubikey 5 NFC not working with Keepass XC 2.6.0

### ISSUE THREAD

**Issue by joomla4free** [keepassxreboot/keepassxc#4983]
Yubikey 5 NFC works fine with previous version 2.5.4 on Windows 10 using USB
In the new version 2.6.0 the key is not recognised. Tried portable 64bit and 32bit versions. Tried existing database or adding Yubikey to new database. Is not recognised. Refreh does not help. Tried on different computers and installs running Windows 10 v 1909.

**Comment by kaikobarg** [comment]
hey you, i just installed V 2.6.0 and had exactly the same problem you mentioned above (Windows 10, 64-bit).
the field "hardware token" was blank. pressing the button "reload" next to the field did not help either.
the only way to get access to my keepass-database again, was to deinstall Version 2.6.0 and reinstall Version 2.4.2.

**Comment by droidmonkey** [comment]
Single up on issue #4987
