### ISSUE TITLE
Wiki not updated with latest release

### ISSUE THREAD

**Issue by bmhatfield** [keepassxreboot/keepassxc#499]
First off, I wanted to say thank you for this project/fork. You've really moved the ball forward on a bunch of KeePassX things that were annoying me for some time.

I've been actively watching this project because it's moving quickly, and I noticed that the changelog on the wiki (linked from the home page) does not refer to the latest release: https://github.com/keepassxreboot/keepassxc/wiki/KeePassXC-Changelog

**Comment by TheZ3ro** [comment]
Thanks for the reminder! Fixed :wink:
