### ISSUE TITLE
Tabular view to display a password with positional characters

### ISSUE THREAD

**Issue by bashruleseverythingaroundme** [keepassxreboot/keepassxc#4990]
This is a feature already implemented in 1password that I always found incredibly useful, the idea is to have an extra option on the context menu "Diplay attribute" when right clicking on a password which will allow any of the custom fields to be displayed with numbers underneath each character of the password. 

A good example of this can be found in this screenshot from 1password:

![image](https://user-images.githubusercontent.com/34572632/86968215-55916c80-c15b-11ea-953d-b7a52198d5d7.png)

The most common use case is on sites that let you set a password but then ask you for a few random characters from it in a different order. For instance a 20 char password but on login they will require character 3, 12 and 17. With this new feature you will be able to display the password on screen and pick the appropriate characters without having to count them.

Thank you for the amazing work you guys are doing on keepassxc!

**Comment by droidmonkey** [comment]
Duplicate
