### ISSUE TITLE
[disregard] 2.6.0 Linux AppImage Initial Window Unreadable at Launch

### ISSUE THREAD

**Issue by stevednm** [keepassxreboot/keepassxc#4991]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
KeePassXC-2.6.0-x86_64.AppImage
At Launch in Linux Mint 20 (XFCE edition, 64-bit), KeepassXC window has display anomaly as in screenshot.

![keepassXC_2 6 0_screenshot-1](https://user-images.githubusercontent.com/403883/86971168-ed786180-c12d-11ea-8064-fb136725614d.png)

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Download official AppImage of KeepassXC 2.6.0 for Linux
2. Save file in Linux Mint 20, XFCE edition, and mark AppImage as executable in file browser or in command-line terminal
3. Launch KeePassXC-2.6.0-x86_64.AppImage

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Expected to see readable initial window to create or open a database, and full listing of menu items (the Quit item is not visible in the Database menu, for example)

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Initial KeepassXC window is not readable and has a number of display anomalies, as illustrated in attached screenshot.

## Context
[NOTE]: # ( Give us any additional information you may have. )
Linux Mint 20, 64-bit, XFCE desktop environment, Linux kernel 5.4.0-39-lowlatency #43-Ubuntu SMP PREEMPT

[NOTE]: # ( Paste debug info from Help → About here )
Revision: 0765954
Distribution: AppImage

Qt 5.14.2
Debugging mode is disabled.

Operating system: Linux Mint 20
CPU architecture: x86_64
Kernel: linux 5.4.0-39-lowlatency

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.1

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: XFCE
Windowing System: X11

--

**Comment by stevednm** [comment]
I wish to retract this bug report. I had been using the AppImage for KeePassXC-2.5.4-x86-64, downloaded the AppImage for 2.6.0, marked it executable in the file browser and launched it, and the display anomalies in the first comment above appeared.

However, after a reboot this morning (the following day) everything appears fine (screenshot below). Perhaps the initial issue was caused by leftover state or configuration in files written by the previous KeePassXC-2.5.4 in a hidden directory in the user home directory? I have no idea, but so far, so good, with a very nice-looking KeePassXC 2.6.0.

Thank you!

**Comment by phoerious** [comment]
Perhaps related to #4995.
