### ISSUE TITLE
Input the Login and Password for Variations of the URL.

### ISSUE THREAD

**Issue by CerebralFreeze** [keepassxreboot/keepassxc#4993]
## Summary
I'm sorry if this is a stupid question but I am what you called mentally challenged.  I can't help it.

When does credentials work for a slightly different URL if you have the login and password for the main URL?  What are the rules?  How similar does the URL in the browser have to be to the URL stored in KeePassXC for the browser extension to accept the login and password?

## Examples
Today, I was testing it and to see the limits and I couldn't figure it out.  If I create a KeePassXC entry with a simple domain like https:://amazon.com, and then if I go to https:://appliance.amazon.com, KeePassXC won't recognize this URL as being associated with amazon.com.  Then, I tried going https:://amazon.com/electronic and then logging on, KeePassXC didn't seem to recognize that either.

## Context
Does the URL have to match exactly for credentials to be given for the website?  And, does any slight differences in URL have to be added to Browser Integrations under Additional URL's?

It would be nice if creating an entry in KeePassXC would allow us to log into any derviations of the main domain. 

By the way. A.W.E.S.O.M.E. upgrade.  You, guys must have been itching for the past month to tell us about it.  It looks really great.  You guys must have hired a professional designer.  I love it.  And, I love KeePassXC even more.

**Comment by varjolintu** [comment]
The URL's work like this:
- `https://amazon.com` matches `https://*.amazon.com/*`
- `https://applicance.amazon.com` matches `https://*.appliance.amazon.com/*`
- Etc..

So the URL has a default wildcard for all subdomains and paths. 2.6.1 will have another upgrade to the URL handling with best-matching credentials returned: https://github.com/keepassxreboot/keepassxc/pull/4832

Glad you like the upgrade.

**Comment by CerebralFreeze** [comment]
Was it like this before or after the upgrade?  Because I am confused.  It
did seem that variations in the URL did indeed work most of the time but
suddenly in the past few weeks, it didn't seem to work for me.  I couldn't
figure out why it would work sometimes and why it wouldn't other times.  I
was under the assumption that as long as the domain was the entered URL
(eg. https://amazon.com then anything would work such as https:/*.
amazon.com/* but it doesn't seem to work sometimes.)  Maybe I did something
stupid and typed something wrong.  I'll check again and let you know if it
doesn't work.

Thanks again!
