### ISSUE TITLE
Feature request: allow deletion of entries from the 'database report'

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [keepassxreboot/keepassxc#4994]
So far as I can tell, one must leave the report in order to delete entries. One can move easily from the report to the entry editor but that editor seems to have no option to delete the whole entry. Yet, looking through the report, one might be apt to want simply to delete old entries. I know I was.

Also (and I will file this separately if you like), what are the big yellow rectangles for, please? Should that not be made clearer? But perhaps those boxes are the artefact of some problem. Screenshot:

![image](https://user-images.githubusercontent.com/47056543/86986333-56da8d80-c18b-11ea-9e01-1b5c8e2d2f61.png)

**Comment by droidmonkey** [comment]
Duplicate
