### ISSUE TITLE
Broken rendering with 2.6.0

### ISSUE THREAD

**Issue by telans** [keepassxreboot/keepassxc#4995]
## Overview
Since upgrading to 2.6.0, rendering for the application is incorrect. However, this doesnt not just happen with KeePassXC but qBittorrent too. Although this means it is most likely a Qt bug, this does not happen with version 2.5.4.

Could you please describe the changes relating to Qt / the application theme introduced with 2.6.0? Hopefully it will allow me to narrow down the issue. This is not due to the default Fusion Qt theme either, as changing that does not help.

![Screenshot from 2020-07-08 13-16-29](https://user-images.githubusercontent.com/45819748/87002971-deb5ab80-c20e-11ea-9de9-c4fcb7b631ab.png)

Other application example:
![Screenshot from 2020-07-09 09-55-17](https://user-images.githubusercontent.com/45819748/87002979-e2e1c900-c20e-11ea-8f47-6e244838288c.png)

## Expected Behavior
Correct rendering

## Actual Behavior
Incorrect rendering

## Context
KeePassXC - Version 2.6.0
Revision: 0765954

Qt 5.15.0
Debugging mode is disabled.

Operating system: Gentoo/Linux
CPU architecture: x86_64
Kernel: linux 5.7.6-gentoo

Enabled extensions:
- Browser Integration
- SSH Agent
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.6

Desktop Env: i3
Windowing System: X11

**Comment by phoerious** [comment]
Please read the pinned issues.

**Comment by telans** [comment]
> Please read the pinned issues.

Not the same issue.

https://github.com/keepassxreboot/keepassxc/issues/4963#issuecomment-655225453

**Comment by telans** [comment]
@droidmonkey Could this get reopened?

**Comment by phoerious** [comment]
This is some external theming bug.

**Comment by telans** [comment]
Could you give an indication as to what changed theme wise between releases? I might do a bisect as this seems like a regression to me

**Comment by phoerious** [comment]
It's a custom theme. You can revert back to the old one by choosing "Classic" from the view menu.

**Comment by telans** [comment]
That doesn't change the rendering issues, so it's definitely a non-theme regression then even if it's from a Qt bug. What changed gui wise aside from the custom themes?

I'm looking through https://github.com/keepassxreboot/keepassxc/commits/develop/src/gui but I don't see much that could cause qt to break like this.

Also, could the "bug" label get re-added? 

Cheers

**Comment by phoerious** [comment]
If the classic theme is broken as well, then it's definitely an external issue.

**Comment by telans** [comment]
```
telans@genbox ~/src/keepassxc $ git bisect good
790b3382a322235e4a9b97350834478407cc2cdc is the first bad commit
commit 790b3382a322235e4a9b97350834478407cc2cdc
Author: database64128 <free122448@hotmail.com>
Date:   Mon Jun 29 10:48:59 2020 +0800

    Call `QGuiApplication::setHighDpiScaleFactorRoundingPolicy` to fix #2815

 src/main.cpp | 3 +++
 1 file changed, 3 insertions(+)
```

https://github.com/keepassxreboot/keepassxc/commit/790b3382a322235e4a9b97350834478407cc2cdc

I'll see if there are any quirks relating to this and my system - but this is the commit that breaks the GUI for me.

**Comment by telans** [comment]
Setting `QT_SCALE_FACTOR_ROUNDING_POLICY` to anything except "PassThrough" fixes the issue for both KeePassXC and qBittorrent. Any ideas why?

**Comment by database64128** [comment]
Yet another Qt bug. 😅 https://github.com/qbittorrent/qBittorrent/issues/12441

**Comment by telans** [comment]
I swear to god I searched for this issue there - sigh. Thanks
