### ISSUE TITLE
Auto-type on MacOS not working: version 2.5.4 and version 2.6.0

### ISSUE THREAD

**Issue by ciscfs** [keepassxreboot/keepassxc#4996]
## Overview
Auto-type stopped working for me with 2.5.4, works fine on reverting back to 2.5.2. When I go to System Preferences, it shows auto-type as disabled. Re-enabling it and restarting KeePassXC does not help, in fact it shows up once again as disabled in System Preferences.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Choose an entry in the database, go to the corresponding webpage in Safari.
2. Use Perform Auto-type menu item or Shift/Command V.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
The auto-type of user and password.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Error message that says that it can't do it.
## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION 2.5.4 and 2.6.0
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS 10.14.6

**Comment by droidmonkey** [comment]
You need to reboot your mac for permissions to take. Pinned issue.

**Comment by ciscfs** [comment]
Thanks - that worked. The only comment I would make then is that the message from KeePassXC should be quite explicit about that. I don’t beleive it mentioned a restart, though I guess I could be mistaken.

Thanks, Chris

**Comment by phoerious** [comment]
This is really something that shouldn't be necessary and I expect Apple to fix it in upcoming releases. Usually it works without restart, but sometimes it doesn't.
