### ISSUE TITLE
Bulk deletion of custom icons

### ISSUE THREAD

**Issue by msalini** [keepassxreboot/keepassxc#4997]
## Summary
Provide an easy way to select and remove multiple custom icons

## Context
I hope this feature request was not covered before.
I have imported a large number of custom icons in KeePassXC but I would now like to remove quite a lot of them. Currently, to my knowledge, the "delete custom icon" only allows you to delete icons one by one. It would be a good idea to be able to select those I wish to delete and a have a "delete selected icons" button, instead.

**Comment by droidmonkey** [comment]
Covered by #2110
