### ISSUE TITLE
KeepassXC display in Linux Mint Cinnamon 20.0 cannot be resized.

### ISSUE THREAD

**Issue by ineuw** [keepassxreboot/keepassxc#4999]
## Overview
The KeepassXC 2.6.0 window in Linux Mint 20.0 Cinnamon cannot be resized.

## Steps to Reproduce
1. Install and Open KeepassXC in Linux Mint 20.0. 
2. Select any theme and any window control,
3. Open KeepassXC

## Expected Behavior
Permit the user to modify the window size.

## Actual Behavior
It is locked in full size display mode and covers the screen. The only available controls are 'Minimize' or 'Close'.

## Context
This was not so with the previous version of KeepassXC in Linux Mint 19.3 Cinnamon.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.0
Revision: 0765954

Qt 5.12.8
Debugging mode is disabled.

Operating system: Linux Mint 20
CPU architecture: x86_64
Kernel: linux 5.4.0-40-generic

Enabled extensions:
I did not install any extensions yet

Cryptographic libraries:
 libgcrypt 1.8.5

Operating System: Linux
Gnome
Windowing System: X11/Wayland ?

**Comment by ineuw** [comment]
The database also freezes when I try to exit.

**Comment by phoerious** [comment]
I tested KeePassXC yesterday in a Mint 19.3 VM and couldn't reproduce any of that.

**Comment by stevednm** [comment]
In Linux Mint 20 XFCE edition neither of these issues is present. The KeepassXC 2.6 window can be resized at will, and the database does not freeze when exiting KeepassXC.

The display issue I had with KeepassXC 2.6.0 (issue reported separately, now closed) resolved itself after a computer reboot, so you might want to try a simple log-out, login, or a reboot or shutdown/boot, and see if the problem persists.

**Comment by ineuw** [comment]
You have a long way to go and learn how to provide decent support, nt to mention common courtesy. I put down your rudeness to the lack of comprehension. I wrote Cinnamon and you checked XFCE. If you had no problems, why did you have to reboot? And why didn't you give me a chance to reply?

Since KeepassXC uses qt, I had the identical issue with Videolan. I tried their solution with KeepassXC but didn't help.

I can reduce the height but not the width which remains fixed at any resolution. Also, I wasn't sure where this issue is to be addressed, KeepassXC or Linux Mint?

Attached is the image. One can see that there is no control for the user to set the size. I set the display resolution to 1920p x 1080p which showed the control but it was still frozen.
![KeepassXC 2020-07-09 14-22-22](https://user-images.githubusercontent.com/10367016/87088067-2550d900-c202-11ea-8b6d-cf2c0a6c91a3.png)

**Comment by droidmonkey** [comment]
Welcome to github, any one can comment on issues, even non project maintainers. This is not a help desk.

**Comment by ineuw** [comment]
I read the article and set QT_AUTO_SCREEN_SCALE_FACTOR=1 which works. Everything is displayed normally.
So, I added to the .profile file the following line just as I did for Videolan. .
**export QT_AUTO_SCREEN_SCALE_FACTOR=1 keepassxc**

Please let me know if this is the correct method to set it permanently.

**Comment by stevednm** [comment]
@ineuw 
To address your criticism, I am a user, not a developer.
A close friend uses KeepassXC with Linux Mint and the Cinnamon desktop, as you do. I took the following screenshot on his computer, to illustrate one method of resizing the window: right-click on the title bar of the KeepassXC window and choose Resize, then move your mouse.
Best wishes--

**Comment by ineuw** [comment]
Closing the issue before I had the chance to reply was wrong. As for resizing, that is what I tried many times and all that happened is that it moved the whole window as well sideways but remained full screen size. While your image displays the window's middle sizing control, mine still doesn't. 

I rebooted and unfortunately, the problem reappeared. adding **export QT_AUTO_SCREEN_SCALE_FACTOR=1 keepassxc** didn't help.

**Comment by ineuw** [comment]
To close the topic before I had a chance to respond was wrong. In any case. my changes did not last. After reboot, it is the wrong display again. Compare the top right controls of your image and mine. I can move the whole frame but cannot resize it.

**Comment by droidmonkey** [comment]
The issue was closed because it is not a problem with our program but a problem with your environment.

**Comment by ineuw** [comment]
Thanks for the direction, Finally found the problem, which was the same with VLC previously and yesterday. The displays were identically big. The environment variable **QT_AUTO_SCREEN_SCALE_FACTOR=0** was missing. I placed it in the $HOME .profile file and this took care of the display issue. 

Posted this in case someone else has such an issue.

**Comment by droidmonkey** [comment]
Good news!

**Comment by i-srinivas** [comment]
I am looking from migrating from the original keepass that I have been using from past 5+ years and landed on this project, which I am happy to use and contribute. I have looked at KeePassX too, before heading here.

The original keepass smaller window is handy to be movable/resizable across diferent screen formats, expecially useful when the target login / authentication window and keepass window are visible at the same time.

This issue is reproducible in latest release build v2.6.4 on Window 10, MacOS 10.13, Debian 10/buster with Mate. I would recommend re-opening this issue.
