### ISSUE TITLE
Compile two separate binaries, one with http plugin and one without

### ISSUE THREAD

**Issue by TheZ3ro** [keepassxreboot/keepassxc#50]
For some people having networking capabilities extend the attack/vulnerability surface.

It would be nice if we can exclude networking code in the compiled executable 
(also because keepasshttp don't have good support on Windows, See: https://groups.google.com/forum/#!topic/keepassx-reboot/yV__ujozMtI)
letting user (or disto-maintainer) decide if include keepasshttp or not in the executable

Note: by default keepasshttp is disabled at runtime

**Comment by droidmonkey** [comment]
What if the compiler output two builds: keepassxr and keepassxr-http

Distros could provide both builds either in the same package or separate packages and users could decide which to use.

**Comment by TheZ3ro** [comment]
This idea is beautiful! :+1:

**Comment by droidmonkey** [comment]
Re-titled the issue to capture the expectations.

**Comment by TheZ3ro** [comment]
How do you want to do this?

One #define for keepasshttp and then #ifdef on the http code, then
when you compile you set the keepasshttp to true or false ?

**Comment by droidmonkey** [comment]
yup, that's what I was thinking. only problem with that approach is it will essentially compile twice, there is no reuse (i think) of compiled object files.

Option 2 is to compile the http code into a library, and also compile http stubs into another library. The linker will link the real stuff or the stubs depending on the binary output. This lets you reuse the compiled objects (ie compile once, link twice).

**Comment by fcore117** [comment]
Better is to add option to turn it off 100%

**Comment by george-viaud** [comment]
Not possible to handle it runtime / statup via config?

**Comment by TheZ3ro** [comment]
@george-viaud it's already possible, but having networking code in an Offline password manager is not the best option

**Comment by anatoli26** [comment]
Agree with @TheZ3ro, also the compilation time is almost insignificant, IMO a couple of seconds (even minutes) more during the compilation step for a more secure deployment is a great trade-off. I support the idea 
> One #define for keepasshttp and then #ifdef on the http code, then when you compile you set the keepasshttp to true or false ?
