### ISSUE TITLE
Widgets on login screen stay at their minimal size on Linux Mint 19

### ISSUE THREAD

**Issue by Redsandro** [keepassxreboot/keepassxc#5000]
KeePassXC - 2.6.0
Revision: 0765954

After an automatic update, the login screen looks like this:

![image](https://user-images.githubusercontent.com/1702193/87056652-3996d500-c206-11ea-8de5-0269085c94ba.png)

Cropped sentences, cropped buttons, but there is enough space. The previous version would resize the form to use the full size of the window.

Also there are a lot of empty buttons on the toolbar. That doesn't change after logging in.

**Comment by phoerious** [comment]
Missing icons is definitely pinned issue #4963. The rest is probably related.

**Comment by Redsandro** [comment]
Not sure I follow how the padding issue is probably related to the icon issue, but I will track the other issue first.
