### ISSUE TITLE
Download favicon.ico not possible with port number in URL

### ISSUE THREAD

**Issue by pvdl** [keepassxreboot/keepassxc#5001]
## Overview
Downloading a favicon.ico is not possible if an URL contains an port number.
Example: `https://192.168.1.1:1234/favicon.ico`

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Open in browser  `https://192.168.1.1:1234/favicon.ico` (Favicon is visible, server listen to port 1234)
2. Open in browser  `https://192.168.1.1/favicon.ico` (Favicon is NOT visible, because server doesn't listen to port 443)
3. Make an entry with `https://192.168.1.1:1234/login` (example)
4. Select option 'Download Favicon' -> It shows a dialog with a status 'Download Failed'

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
In the last step 4 the favicon should be downloaded.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
In the last step 4 the favicon is not downloaded, however it is accessible in a browser (Step 1)

## Context
[NOTE]: # ( Give us any additional information you may have. )
Probably the port number is not 'added' after the FQDN which is used to search the favicon.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.6.0
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux Mint 19.3 and macOS
Desktop Env: Cinnamon
Windowing System: X11/Wayland ???

**Comment by pvdl** [comment]
Maybe also a relation with issue #5419 ?

**Comment by droidmonkey** [comment]
So you have a proxy setup?
