### ISSUE TITLE
MacOS build fails due to some problem with clipboard utility (pbcoby).

### ISSUE THREAD

**Issue by fpohtmeh-github** [keepassxreboot/keepassxc#5003]
## Overview
My pull request #4956 failed on MacOS. I noticed unexpected messages in build log:
```
[Step 3/6] FAIL!  : TestCli::testClip() Compared values are not the same
[Step 3/6]    Actual   (((clipboard->text()))): ""
[Step 3/6]    Expected (QString("Password"))  : "Password"
[Step 3/6]    Loc: [/Users/kpxc/keepassxc/60040/tests/TestCli.cpp(442)]
```
It means that system clip utility doesn't work. My changes were in UI only, I couldn't break MacOS build.

## Steps to Reproduce
Open build [log](https://ci.keepassxc.org/viewLog.html?buildId=60041&buildTypeId=KeepassXC_MacOS) for MacOS in my pull request.
Please notice that it's showstopper for many others pull requests (#4971, #4967, etc). It's **CRITICAL ISSUE** for contributors.

## Expected Behavior
MacOS builds must be ok

## Actual Behavior
Many pull requests are stopped by this issue.
Additionally, I run tests on Kubuntu without xclip installed. I got the same fail. It proves that test can't find or run correctly clip utility.

**Comment by droidmonkey** [comment]
Solved

**Comment by apteryks** [comment]
The testClip test appears to hang inside a containerized environment, with the exact same error reported in this old issue.  It seems the xclip subprocess is blocking and waiting until it times out (15 s).  I'm guessing this is due to the lack of a true TTY, but I haven't pushed the investigation.
