### ISSUE TITLE
Tree/list pane switch

### ISSUE THREAD

**Issue by ConnorMcF** [keepassxreboot/keepassxc#5006]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
Being able to use the left/right arrow keys to switch between the tree and password list would be really helpful.

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )
Right arrow key in the tree pane should bring you to the list
Left arrow key in the list pane should bring you to the tree

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
This feature would be useful as I often alt-tab into KeePass and being able to only use the keyboard without tabbing back and forth between panes would be nice.

**Comment by droidmonkey** [comment]
Not a bad idea!

**Comment by fpohtmeh-github** [comment]
Left/right keys are already reserved by tree control to go up, collapse or expand node.
Good old Tab/Shift+Tab works fine.

**Comment by droidmonkey** [comment]
Oh good point, then this will be no fix

**Comment by ConnorMcF** [comment]
If there are no deeper nodes is it possible to have it do it perhaps?

**Comment by droidmonkey** [comment]
No I'm not needing with the default behavior
