### ISSUE TITLE
Add unicode support for search and auto-type 

### ISSUE THREAD

**Issue by jionkitten** [keepassxreboot/keepassxc#5007]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
I found that the unicode characters in the title of entry can be displayed normally, but the title matching of unicode characters does not work.

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )
The entry with title containing unicode characters:
![image](https://user-images.githubusercontent.com/30788097/87109682-e3727200-c297-11ea-8d35-6b98464744c6.png)
But when I search the title no result is displayed:
![image](https://user-images.githubusercontent.com/30788097/87109766-1452a700-c298-11ea-9489-dd2f50d713e3.png)

And I also found that title matching for the websites does not support unicode character. I guess that the whole matching part hasn't designed to be compatible with unicode.

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
Languages in different countries almost determines the languages of websites or applications designed for specific country, for example, in Japn titles of most websites are written in Japanese not in pure ASCII characters.  To match the title of these websites unicode support is needed.

OS: Windows 10 x64
Program version: 2.6.0

**Comment by droidmonkey** [comment]
I couldn't replicate this:

![image](https://user-images.githubusercontent.com/2809491/87263369-ec776500-c48a-11ea-8b96-ea96cb9f9eb1.png)
