### ISSUE TITLE
Relative Path for SSH Key does not work on Windows and Linux with the same setting

### ISSUE THREAD

**Issue by MBurchard** [keepassxreboot/keepassxc#5008]
As a follow up to the closed Issue #4810 I tested it with the new release and it does not work as it should, but as expected...

On Linux it works with $HOME...

On Windows there is no HOME Variable but I created one.

But as expected $HOME does not work with Windows because Windows only knows %HOME%.

I suggest a smart string substitution before using that Path.

If variable is detected but the current operation system does not support it then replace it before using it...

**Comment by hifi** [comment]
On non-Windows we substitute `~` with `$HOME`. Would it work for you if we do that on Windows as well but substitute it with `%HOMEPATH%` as according to a quick Google search it should be equivalent?

Supporting both notations at the same time is possible but I'm afraid it could also have unexpected results.

**Comment by MBurchard** [comment]
The suggestion sounds good.

Under Windows, the counterpart to $HOME would be %USERPROFILE% instead of %HOMEPATH%.

If I understood this correctly, the user could use **~** and it would be replaced with **$HOME** under Linux and then with **%USERPROFILE%** under Windows.
That would be great.

But users might want more flexibility. So I would require Linux notation for other variables. By the way, other applications do that as well.
Then, if KeePassXC runs on Windows and finds the $MyPath variable, it could be converted to %MyPath% without risk.

Thank you for that great piece of software...

**Comment by hifi** [comment]
Okay, so here's my take on this. I think tilde replacement on all platforms is fine but when it comes to other environment variables they don't necessarily have the same _meaning_ on Windows and Unix-like systems and certainly most don't have the same name.

I'm happy to have tilde replacement in 2.6.1 and if someone comes up with a reasonable use case for other environment variables in this context (SSH key path) we can take another look.
