### ISSUE TITLE
Focused/hovered button on classic theme has incorrect rendering

### ISSUE THREAD

**Issue by Phyxion** [keepassxreboot/keepassxc#5009]
## Overview
Right and bottom side have more border, seems to occur only with display scaling set > 100%:
![](https://i.imgur.com/b8rF5o1.png)

Also, there are other problems with the button, namely left/right/bottom border going away on hover/click:
https://streamable.com/pvswth

## Steps to Reproduce
1. Focus/hover over any button.

## Context
KeePassXC - Version 2.6.0
Revision: 0765954

Qt 5.15.0
Debugging mode is disabled.

Operating system: Windows 10 Version 2004
CPU architecture: x86_64
Kernel: winnt 10.0.19041

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.5

**Comment by droidmonkey** [comment]
It's classic for a reason

**Comment by phoerious** [comment]
That is Qt being generally buggy with non-integer scaling factors. Nothing we can do about it.
