### ISSUE TITLE
--pw-stdin fails with multiple databases as of 2.6.0

### ISSUE THREAD

**Issue by jkt628** [keepassxreboot/keepassxc#5012]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. use https://github.com/keepassxreboot/keepassxc/blob/develop/utils/keepassxc-keychain to launch multiple databases, e.g., Work and Home, add `-d` to generate the debug log.
2. notice only one database is unlocked.
3. check the debug log to find your setup is just fine.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

both (or more) databases should unlock.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

only one database unlocked.

## Context
[NOTE]: # ( Give us any additional information you may have. )

the only thing that changed was `brew cask upgrade keepassxc` from 2.5.4 to 2.6.0.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.0
Revision: 0765954

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS Catalina 10.15.5
Desktop Env: Finder
Windowing System: Aqua

**Comment by lkrms** [comment]
Unfortunately I'm having the same issue on Linux (version details below).

I use [this script](https://github.com/lkrms/lk-scripts/blob/master/bin/keepassxc-start.sh) to open two databases at startup and it's no longer working. So far I've tried using fewer newlines between subsequent passwords, to no avail.

It works as normal if starting a new KeePassXC instance with either of the two databases, but opening a second one doesn't work in any scenario (including running `keepassxc --pw-stdin` after starting an instance).

> KeePassXC - Version 2.6.0
> Revision: 0765954
> 
> Qt 5.15.0
> Debugging mode is disabled.
> 
> Operating system: Arch Linux
> CPU architecture: x86_64
> Kernel: linux 5.7.7-arch1-1
> 
> Enabled extensions:
> - Auto-Type
> - Browser Integration
> - SSH Agent
> - KeeShare (signed and unsigned sharing)
> - YubiKey
> - Secret Service Integration
> 
> Cryptographic libraries:
>  libgcrypt 1.8.6

**Comment by lkrms** [comment]
In case it's useful to others (or assists with debugging), I discovered while testing something else entirely that `keepassxc --pw-stdin` was responsive to input for each database specified on the command line _after a small delay._ On one of my slower computers, adding a 2-second delay wasn't enough (presumably because KeePassXC was starting up at the same time as everything else on the system) but 5 seconds has been working fine.

I'm guessing there's an input buffer being flushed somewhere it shouldn't be, but it's good to have a workaround while the bug is being tracked down.

Thanks so much for this excellent software that I rely upon all day, every day :smiley:

**Comment by lkrms** [comment]
Sorry to post again; I forgot to provide an example of the delay in a script. Here's the [one I'm using now](https://github.com/lkrms/lk-platform/blob/master/bin/lk-keepassxc.sh) (it has an `--autostart` option to register databases to open at startup on macOS, if that appeals to anybody other than me) and here's the code that adds a 5-second delay after the first password:

```bash
if lk_is_true "$DAEMON"; then
    exec "$KEEPASSXC" \
        --pw-stdin "${DATABASES[@]}"
else
    nohup "$KEEPASSXC" \
        --pw-stdin "${DATABASES[@]}" >/dev/null 2>&1 &
    disown
fi < <(echo "${PASSWORDS[0]}" &&
    [ ${#PASSWORDS[@]} -le 1 ] ||
    for PASSWORD in "${PASSWORDS[@]:1}"; do
        sleep 5
        echo "$PASSWORD"
    done)
```
