### ISSUE TITLE
Can't access current password while creating new password

### ISSUE THREAD

**Issue by belisama** [keepassxreboot/keepassxc#5013]
V2.6.0 broke one of the best features of KeepassXC, which is that you could still access the old password (as well as the rest of the entry) while putting together the new one. A lot of sites require the current password as part of the update process and now if you start the process to generate a new password and realize you need the current one, or need to add a note, or anything at all, you have to cancel all the work on the new password.

**Comment by phoerious** [comment]
You can simply create the new password and get the old one from the history.

**Comment by droidmonkey** [comment]
I'm not following, so you prematurely open the password generator before entering your current password in the website form. Just reverse those steps in your work flow.

**Comment by belisama** [comment]
Sure, I'll just magicially fix every badly designed password update page on the internet *and* never, ever make an mistake in my own workflow. Thanks ever so much for that advice. You had a really useful feature, you broke it for no apparent reason, and telling people "you're holding it wrong" doesn't change that. Time to go looking for another program.

**Comment by phoerious** [comment]
Wow. You just got two pointers as to how you can get your old password, but you prefer throw a tantrum. There ARE very good reasons why we changed it to a pop-up window. If you don't like it, that is totally all right, but don't act like you were entitled to dictating the way we design our application.

**Comment by droidmonkey** [comment]
Can you provide a sample website that asks for your new password _before_ your current one?
