### ISSUE TITLE
AutoOpen IfDevice check has a bad first letter case

### ISSUE THREAD

**Issue by pvalsecc** [keepassxreboot/keepassxc#5017]
## Overview
The implementation of #2871 looks at the wrong attribute. It should be `IfDevice` instead of `ifDevice`.

The spec says:

> Computer/device ID check. The custom entry string "IfDevice" (without the quotes) may contain a comma-separated list of computer/device IDs or negated computer/device IDs (with the prefix '!') on which the database is opened automatically.

Looking at the code, I've found another problem. In the same area of the doc, it is said:

> If the string is "!Pqr, !Xyz", the database is opened automatically on all computers/devices that are called neither Pqr nor Xyz. 

If my hostname is `foobar`, with this example, it should open the entry. The current code would wrongly not open it.

**Comment by droidmonkey** [comment]
Your quote of the spec uses an uppercase I

**Comment by pvalsecc** [comment]
Yes, and the code wrongly uses lowercase i

**Comment by droidmonkey** [comment]
Got cross eyed, will correct for 2.6.1
