### ISSUE TITLE
KPxc Tray icon is transparent in tray, using default settings.

### ISSUE THREAD

**Issue by bkoch58** [keepassxreboot/keepassxc#5019]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
When KPxc is minimized to the system.tray, the usual XPxc icon is transparent in tray, (there is a place-holder in the tray but no icon).  I had to goto Settings > "Show a system tray icon" > change "Tray icon type:" from "Monochrome (light)" to "Colorful", then the tray icon would appear in view.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Set XPxc to minimize on Exit to system tray.
2. With the default "Tray icon type:" set to "Monochrome (light)" in my environ', the system tray icon is transparent. 

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
I expected to see the KPxc green icon appear in the system tray when KPxc is minimized.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
See screen-cap, where the tray icon is transparent.
![Transparent KPxc icon is Tray](https://user-images.githubusercontent.com/43045699/87180132-cc7e5080-c294-11ea-90cf-cbf1cb38859f.JPG)

## Context
[NOTE]: # ( Give us any additional information you may have. )
1. Immediately after update to 2.6.0, I noticed that the system tray icon for KPxc "disappeared".
2. I tried changing the theme to each of the 4 values.  No change.
3. While submitting this bug report, I "stumbled" across the new feature, to be able to set the tray icon to one of three values.
4. Given my system, the default icon of "Monochrome (light)" would cause the tray icon to be transparent.
5. My proposal, is to change the default setting from "Monochrome (light)" to "Colorful", in future releases, to avoid this (minor) issue.

![Show system Tray icon before](https://user-images.githubusercontent.com/43045699/87180151-d30cc800-c294-11ea-8092-c82697e6d710.JPG)
![Show system Tray icon after](https://user-images.githubusercontent.com/43045699/87180159-d902a900-c294-11ea-83dc-982a5fac91dd.JPG)

Note: this is my first 'bug-report' on github so please be kind. :)

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.0
Revision: 0765954

Qt 5.15.0
Debugging mode is disabled.

Operating system: Windows 8.1 Version 6.3 (Build 9600)
CPU architecture: x86_64
Kernel: winnt 6.3.9600

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.5

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows
Desktop Env: KDE
Windowing System:

**Comment by droidmonkey** [comment]
Ping @phoerious. *glares*

**Comment by phoerious** [comment]
There are two options for monochrome icons, one for dark taskbars (the default), and one for light taskbars. And then there is the "colorful" option if you like the classic look. On macOS, we select the monochrome variant automatically, on Windows we simply assume you are using a dark taskbar, since it can basically have any colour and dark is usually the default.

**Comment by happnatious1** [comment]
In Linux Mint 20 it never displays an icon.
You can select Monochrome light, Monochrome dark, or colorful and it's always just an empty place holder.
even between reboots.

**Comment by phoerious** [comment]
That's another issue: #4963

**Comment by droidmonkey** [comment]
Fixed by #5011
