### ISSUE TITLE
Always clear clipboard when database is locked

### ISSUE THREAD

**Issue by bsuggs5** [keepassxreboot/keepassxc#5020]
## Overview
I found a bug in that on a session anyone can open the program and change the Settings, especially the feature under security and clear clipboard so that it is disabled...without logging into a database.  This leaves the user vulnerable on the event they come log into that database, copy to clipboard, and then exit the program.  

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Verify setting is enabled for a sample amount of time, clear clipboard setting works with a database open.
2. Closing database, then changing that setting to disable, then logging back into database.  Verified that Clesr clipboard is still disabled after database login.  Copy field works, but after previous set amount of time clear clipboard does NOT happen.  This leaves user vulnerable to paste minutes to hours later.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
1.  I expect that either: 
   a. the security settings should not able to be modified by non logged in user
   b. or logged in user's settings should be authority to protect user within the database settings.
   c. or copied fields are mandatory cleared each time program exits regardless of clipboard setting.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.0
Revision: 0765954

Qt 5.15.0
Debugging mode is disabled.

Operating system: Windows 10 Version 1909
CPU architecture: x86_64
Kernel: winnt 10.0.18363

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.5

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 10

**Comment by droidmonkey** [comment]
Application settings are stored in your user home directory, so only that user (and administrators) can access it. I agree that the clipboard should be cleared when the database is locked regardless of the clear clipboard setting.
