### ISSUE TITLE
Toolbar hover doesnt unhover

### ISSUE THREAD

**Issue by idontusenumbers** [keepassxreboot/keepassxc#5023]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

![image](https://user-images.githubusercontent.com/1175031/87208332-f4d96f80-c2d3-11ea-9c32-8c04cc93313b.png)

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1.  Mouse over the toolbar buttons

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Only one remains hilighted

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
All buttons moused over remain highlighted

KeePassXC - Version 2.6.0
Revision: 0765954

Qt 5.15.0
Debugging mode is disabled.

Operating system: macOS High Sierra (10.13)
CPU architecture: x86_64
Kernel: darwin 17.7.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
 libgcrypt 1.8.5

**Comment by droidmonkey** [comment]
You have a lot of theming problems. Are you running qt5ct?

**Comment by idontusenumbers** [comment]
I have no idea. Is it not part of the .app bundle?

**Comment by idontusenumbers** [comment]
Heres the version info of Qt from the keepassxc .app
![image](https://user-images.githubusercontent.com/1175031/87209741-9fec2800-c2d8-11ea-8992-8b690f01d9a5.png)

**Comment by idontusenumbers** [comment]
After activating classic theme, it looks like this on hover:
![image](https://user-images.githubusercontent.com/1175031/87209849-07a27300-c2d9-11ea-840a-33d92104cdfa.png)

**Comment by phoerious** [comment]
Why is everybody using icons with text all of a sudden? It just makes the toolbar huge.

**Comment by droidmonkey** [comment]
I agree, I thought we messed up the default toolbar setting

**Comment by idontusenumbers** [comment]
I'm using it because the icons are not the system default icons for those buttons so it's hard to tell what they do. Additionally, they are monochrome, outline, and most have the same general shape, which makes it even harder to identify the button.

**Comment by droidmonkey** [comment]
I can't reproduce this on Catalina.
