### ISSUE TITLE
Edit entry dialog separator (bullet) is rendered as a box with stripes (Mojave)

### ISSUE THREAD

**Issue by zyv** [keepassxreboot/keepassxc#5025]
## Overview

As requested in #4110 by @phoerious.

## Steps to Reproduce
1. Install KeePassXC on macOS Mojave
2. Open database
3. Edit entry

## Expected Behavior

A bullet point being rendered correctly.

## Actual Behavior

<img width="347" alt="Screenshot 2020-07-11 at 10 56 08" src="https://user-images.githubusercontent.com/607401/87220591-64e40600-c365-11ea-93a9-f5d7f6ee09d9.png">

## Context

KeePassXC - Version 2.6.0
Revision: 0765954

Qt 5.15.0
Debugging mode is disabled.

Operating system: macOS Mojave (10.14)
CPU architecture: x86_64
Kernel: darwin 18.7.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
 libgcrypt 1.8.5

**Comment by droidmonkey** [comment]
Doesn't do this in Catalina.

**Comment by quinncomendant** [comment]
Can we use the more common BULLET character `•` (U+2022), which is visually similar to BLACK SMALL DIAMOND `⬩` (U+2B29)? It should be available in more systems.

**Comment by droidmonkey** [comment]
Ping @phoerious
