### ISSUE TITLE
Unusable interface after update to 2.6.0 on Arch Linux

### ISSUE THREAD

**Issue by afv** [keepassxreboot/keepassxc#5029]
## Overview
I can't see/select most things.
I'm aware of #4963: the icons became better (second screenshot) after unsetting `QT_QPA_PLATFORMTHEME` (or setting it to `gtk2`), but the main issue remains.
Tried changing the theme (automatic/light/dark), and also downgrading `qt5ct` from 1.0-1 to 0.41-5, but the result is the same.

## Actual Behavior

![2020-07-11_12-29-56_keepassxc1](https://user-images.githubusercontent.com/1532245/87223364-3a4d7980-c374-11ea-8a33-111de2aaf480.png)

After setting `QT_QPA_PLATFORMTHEME` to `gtk2`:

![2020-07-11_12-32-12_keepassxc2](https://user-images.githubusercontent.com/1532245/87223368-4afdef80-c374-11ea-8148-34479dc26571.png)

Blindly entering my database password (as I know the password field is usually focused) allows me to unlock it (text blurred on purpose):

![2020-07-11_12-51-21_keepassxc3](https://user-images.githubusercontent.com/1532245/87223485-556cb900-c375-11ea-8abc-3429c1fec6bb.png)

Edit item:

![2020-07-11_12-53-35_keepassxc4](https://user-images.githubusercontent.com/1532245/87223514-9369dd00-c375-11ea-89aa-a80e63c20169.png)

---

![2020-07-11_12-40-15_keepassxc_about](https://user-images.githubusercontent.com/1532245/87223374-5bae6580-c374-11ea-81be-935f19732f77.png)

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.0
Revision: 0765954

Qt 5.15.0
Debugging mode is disabled.

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 5.7.7-arch1-1
Desktop Env: Gnome/KDE (AwesomeWM)
Windowing System: X11

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.6

**Comment by droidmonkey** [comment]
Check out https://doc.qt.io/qt-5/highdpi.html#high-dpi-support-in-qt

**Comment by afv** [comment]
Thanks!

My screen is 2560×1440. `QT_SCALE_FACTOR` set to `1.2` helps:

`$ QT_SCALE_FACTOR=1 QT_QPA_PLATFORMTHEME= keepassxc`

![2020-07-11_16-36-38_scale_factor_1](https://user-images.githubusercontent.com/1532245/87227739-eacb7580-c394-11ea-8870-031210069d82.png)

`$ QT_SCALE_FACTOR=1.1 QT_QPA_PLATFORMTHEME= keepassxc`

![2020-07-11_16-37-04_scale_factor_1 1](https://user-images.githubusercontent.com/1532245/87227760-046cbd00-c395-11ea-91d7-36a776b54ccf.png)

`$ QT_SCALE_FACTOR=1.2 QT_QPA_PLATFORMTHEME= keepassxc`

![2020-07-11_16-37-22_scale_factor_1 2](https://user-images.githubusercontent.com/1532245/87227767-0767ad80-c395-11ea-820c-8617a6e44e4c.png)

**Comment by busimus** [comment]
I have the exact same issue on my 1080p screens. Setting `QT_SCALE_FACTOR=1.2` helps (though it still looks a lot worse than it did in previous versions), but I've never used any scaling options before.

**Comment by phoerious** [comment]
Can everybody who has this problem please state their distribution, Qt version, and QT_QPA_PLATFORMTHEME? This seems to be a systematic Qt bug and we need to single out which versions are affected.

**Comment by spvkgn** [comment]
There are missing icons in panel

OS: Ubuntu 18.04
DE: MATE Desktop
Qt: 5.9.5
`QT_QPA_PLATFORMTHEME`: `qt5ct`

![Без имени](https://user-images.githubusercontent.com/4147135/87229516-039e5000-c3c2-11ea-9022-f10f28076a47.png)

**Comment by phoerious** [comment]
That's another problem. Please read the pinned issues.

**Comment by Ghosthree3** [comment]
Having similar issues here using a regular 1080p display.

Distro: Arch
DE: Sway/Wayland
QT: 5.15.0
QT_QPA_PLATFORMTHEME unset

**Comment by migu** [comment]
Same issue on 1920x1200 display.

Distro: Arch Linux
DE: None, xorg, i3wm
QT: 5.15.0
QT_QPA_PLATFORMTHEME: unset (or unknown to me)

**Comment by Segaja** [comment]
Distro: Arch Linux
DE: i3wm
QT: 5.15.0
QT_QPA_PLATFORMTHEME: unset

**Comment by andrewlin16** [comment]
Having this issue too with 2 24" 1080p displays, although it looks like mine is not nearly as bad as OP's. Using the "Classic (Platform-native)" theme, but this issue occurs on the default theme as well.

![Screenshot_2020-07-11_14-30-46](https://user-images.githubusercontent.com/4985970/87234339-c10a5280-c384-11ea-8914-1d47a59507d2.png)

![Screenshot_2020-07-11_14-35-06](https://user-images.githubusercontent.com/4985970/87234342-c5cf0680-c384-11ea-844d-97066c1a3997.png)

Distro: Arch Linux
DE: none (Openbox)
Qt: 5.15.0
`QT_QPA_PLATFORMTHEME`: unset

Setting `QT_SCALE_FACTOR=1.1` fixes the cutoff issues but obviously makes the UI slightly bigger than normal.

**Comment by droidmonkey** [comment]
Common theme is arch Linux, HD display (not hidpi), and no platform theme set

**Comment by kendellfab** [comment]
Distro: Arch Linux
DE: Gnome
Qt: 5.15.0
QT_QPA_PLATFORMTHEME: qt5ct
Display: Both 1080p & 1440p

Distro: Fedora 32 (AppImage)
DE: Gnome
Qt: ?
QT_QPA_PLATFORMTHEME: qt5ct
Display: Both 1080p & 1440p

**Comment by di72nn** [comment]
Distro: Arch Linux
DE: None (i3wm)
Qt: 5.15.0
QT_QPA_PLATFORMTHEME: qt5ct (Breeze is selected in qt5ct)
Display: 1080p

I had this issue (classic theme because I was comparing it with pre-2.6 keepassxc):
![Screenshot_20200712-122218](https://user-images.githubusercontent.com/1114779/87243341-66392f80-c446-11ea-9dbe-f6f05a1a9cc9.png)
but after setting the correct DPI in `~/.Xresources`: `Xft.dpi: 96` it got resolved:
![Screenshot_20200712-134619](https://user-images.githubusercontent.com/1114779/87243362-8cf76600-c446-11ea-8c50-0c20320a00ea.png)

The icons are still fuzzy (compared to crisp icons of pre-2.6 keepassxc).

Weirdly enough, on a different machine (only screen resolution is different) that seems to have correctly detected DPI from EDID, setting `Xft.dpi` was necessary too.

**Comment by phoerious** [comment]
Your icon theme is wrong. You have to unset QT_QPA_PLATFORMTHEME.

**Comment by di72nn** [comment]
The theme is not wrong, it's *custom* (that's the point of themes, isn't it?).
Unsetting `QT_QPA_PLATFORMTHEME` does change icons. It also changes sizes and widgets' looks, which is certainly undesirable.

Anyway, the icons in the screenshots work perfectly fine with pre-2.6 keepassxc **and** other Qt5 applications (e.g. KDE apps).

I'm not bothered enough (yet) to investigate the icons, maybe they simply don't scale well for that size.

**Comment by droidmonkey** [comment]
We don't support third party icons at all, you assume all issues

**Comment by Kevinjil** [comment]
Distro: Arch Linux
DE: None (i3wm)
Qt: 5.15.0
QT_QPA_PLATFORMTHEME: qt5ct (Breeze darker)
Display: 1080p

**Comment by konecny-ondrej** [comment]
Setting QT_AUTO_SCREEN_SCALE_FACTOR to 0 worked around the problem for me.

**Comment by droidmonkey** [comment]
Yup for non-4K monitors that's the perfect setting

**Comment by dextercd** [comment]
I have the same issue.

Distro: Arch Linux
DE: i3wm
Qt: 5.15.0-4
QT_QPA_PLATFORMTHEME: not set
Display: Two: 1920x1080 and 1024x768, I'm launching on the lower resolution one.

Setting QT_AUTO_SCREEN_SCALE_FACTOR to 0 or setting QT_SCALE_FACTOR to 1.5 fixes the issue for me. Setting the DPI in .Xresources also fixes the issue.

**Comment by droidmonkey** [comment]
Bottom line is that this is a configuration issue with the system that prevents Qt from determining the appropriate scaling factor to use.

**Comment by Ghosthree3** [comment]
Are you marking this as a wontfix then? Should we just export the variable in our environment? Qt is never going to be properly configured on my system because I don't use anything that requires it to be.

**Comment by droidmonkey** [comment]
This is a can't fix, your environment needs to be updated

**Comment by virtualdxs** [comment]
Are you sure it's actually a system configuration issue, not an app issue that can be worked around with system configuration? I don't see this issue on other QT apps I use, such as Musescore, the Nextcloud client, or OBS.

**Comment by droidmonkey** [comment]
Those apps probably don't have support for HiDPI. This occurs when that support is enabled, and it's not something that we can configure since it needs to be set prior to everything bootstrapping.

**Comment by phoerious** [comment]
We could skip this step when no platform theme is set, but that's an ugly hack.

**Comment by droidmonkey** [comment]
That has unintended consequences written all over it

**Comment by konecny-ondrej** [comment]
Hm, I think that QT just does not like that my monitor has a non-standard DPI of 91x91. I have set the `Xft.dpi` to 96 and it works as well. I can live with this. On my laptop issue this does not happen (also latest Arch).

**Comment by spaceporn** [comment]
Facing the same issues (Arch, bspwm, Qt 5.15.0-4, 1600x900 + 2560x1080, QT_QPA_PLATFORMTHEME=qt5ct). Both environment variables fixed it (1.1 for the scale factor suffices here). Isn't there a way for the application itself to test for the resolution and set the proper scale factor? I have a bunch of other Qt applications that are unaffected by this. I mean, sure most people will figure out how to fix this, but can't the application at least see that it's rendering everything wrong and print a warning or open a dialog about the environment variable?

**Comment by droidmonkey** [comment]
@spaceporn direct that question over to Qt please.

**Comment by phoerious** [comment]
Regarding other Qt applications being unaffected: those probably do not have fractional scaling enabled.

**Comment by droidmonkey** [comment]
I am going to fix this by disabling the setting of the rounding policy to "PassThrough" on Linux and macOS. Only Windows will allow fractional scaling until Qt fixes their bug.
