### ISSUE TITLE
Add context menu entry to clean the Recycle Bin in databases

### ISSUE THREAD

**Issue by vsvyatski** [keepassxreboot/keepassxc#503]
It is actually a feature request.

When an entry is removed from a KDBX database it's first placed in a special folder (group) called "Recycle Bin" (it can have different names if the database was initially created in KeePassXC with non-english locale). The original Keepass 2 (.NET based) has an option in the context menu of the recycle bin allowing to clean it. In KeePassXC you need to go into that folder (group), select all the entries and then delete them. It would be nice for KeePassXC to have that context menu entry like KeePass does, because many systems, having some sort of a recycle bin, trash, etc., usually have a context menu allowing to quickly clean it.

Here is what I mean
![noclean](https://cloud.githubusercontent.com/assets/11542782/25063591/175c0ed2-21f1-11e7-8bc2-e2eb2b0f7fbc.jpg)

## My environment
* KeePassXC version/commit used: 2.1.4 (so called unofficial variant for Debian/Ubuntu)
* Qt version: 5.5.1 (which is in the repositories for Ubuntu 16.04 LTS)
* Compiler: g++ (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609 (but I didn't build your app from the source myself, I had just downloaded the *.deb file)
* Operating System and version: Linux Mint 18.1 Serena Cinnamon Edition 64 bit

**Comment by vsvyatski** [comment]
I have implemented my own feature request [with this pull request](https://github.com/keepassxreboot/keepassxc/pull/520).

**Comment by schnappijedi** [comment]
This is great. Just wanted to add that the empty recycle bin context menu only works when the option "Use recycle bin" in database settings is turned on.
