### ISSUE TITLE
Chromium (Ubuntu) can not connect to Database

### ISSUE THREAD

**Issue by rindvieh1234** [keepassxreboot/keepassxc#5035]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

System: Ubuntu 20.04 LTS, Update from today 11. July
KeePass XC Information:

KeePassXC - Version 2.6.0
Revision: 0765954

Qt 5.12.8
Debugging mode is disabled.

Operating system: Ubuntu 20.04 LTS
CPU architecture: x86_64
Kernel: linux 5.4.0-40-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.5

KeePassXC-Browser shows following message after update:
"Can not connect to KeepassXC. Check the Browser integration is enabled in KeePass XC settings"

When I press reload button: "Kex exchange was not successful"

Actions done:
Disabled / enabled Browser integration, no change.
re-installed KeePassXC_browser: no change

Removed the Key for the browser integration on KeePassXc and in the Chromium KeePassXC Browser extension.
Now I dont get the blue "Connect" button any more to create a new Database connection

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. 
2. 
3. 

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows/Linux/macOS
Desktop Env: Gnome/KDE/XFCE/Mate/Cinnamon
Windowing System: X11/Wayland

**Comment by droidmonkey** [comment]
Are you running chromium as a snap?

**Comment by rindvieh1234** [comment]
I installed it from Ubuntu sources.
I followed this guide: https://github.com/keepassxreboot/keepassxc-browser/wiki/Troubleshooting-guide

My org.keepassxc.keepassxc_browser.json looks good, path is ok, my Firefox is working.
{
    "allowed_origins": [
        "chrome-extension://pdffhmdngciaglkoonimfcmckehcpafo/",
        "chrome-extension://oboonakemofpalcgghocfoadofidjkkk/"
    ],
    "description": "KeePassXC integration with native messaging support",
    "name": "org.keepassxc.keepassxc_browser",
    "path": "/usr/bin/keepassxc-proxy",
    "type": "stdio"
}


Thats the messages from the Console Tab in developer mode:
Error 5: Cannot connect to KeePassXC. Check that browser integration is enabled in KeePassXC settings.  keepass.js:1067

Connecting to native messaging host org.keepassxc.keepassxc_browser                                     keepass.js:984 

Failed to connect: Specified native messaging host not found.                                           keepass.js:954 

Error: No content script available for this tab.                                                        keepass.js:1188 

Error 9: Key exchange was not successful.                                                               keepass.js:1067 

Error: No content script available for this tab.                                                        keepass.js:1188

**Comment by varjolintu** [comment]
Is your KeePassXC installed as Snap? If so, did you use the helper script from https://keepassxc.org/download/#linux ?

**Comment by rindvieh1234** [comment]
Hi,
looks like Ubuntu is installing per default a snap. Output of my chrome://version/


Chromium | 83.0.4103.116 (Official Build) snap (64-bit)
-- | --
Revision | 8f0c18b4dca9b6699eb629be0f51810c24fb6428-refs/branch-heads/4103@{#716}
OS | Linux
JavaScript | V8 8.3.110.13
Flash | (Disabled)
User Agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) snap Chromium/83.0.4103.116 Chrome/83.0.4103.116 Safari/537.36
Command Line | /snap/chromium/1213/usr/lib/chromium-browser/chrome --no-default-browser-check --no-first-run --password-store --flag-switches-begin --flag-switches-end --disable-webrtc-apm-in-audio-service
Executable Path | /snap/chromium/1213/usr/lib/chromium-browser/chrome
Profile Path | /home/jochen/snap/chromium/common/chromium/Default


Is there a way to fix this or just switch to chrome?

**Comment by varjolintu** [comment]
@rindvieh1234 You can always try to install Chromium using Debian's repositories: https://askubuntu.com/questions/1204571/chromium-without-snap

**Comment by rindvieh1234** [comment]
Thanks for the help. Maybe its time to check out Linux Mint

**Comment by bigfatfrog67** [comment]
I'm getting exactly this problem on Firefox on Ubuntu 18.04.4
The connect button does nothing.
I've gone through the troubleshooting document on the wiki and all looks good.

**Comment by varjolintu** [comment]
@bigfatfrog67 And Firefox is not installed via snap? Is there any difference if you use the button from the popup or from the settings page?

**Comment by bigfatfrog67** [comment]
how do i tell if it's installed by snap?

**Comment by bigfatfrog67** [comment]
Oh:
jonathan@ubuntu-laptop:~/.mozilla/native-messaging-hosts$ which firefox
/snap/bin/firefox

so yes I guess

I'll try downloading it from Mozilla .....

**Comment by varjolintu** [comment]
@bigfatfrog67 Use `which firefox` to check it.

**Comment by bigfatfrog67** [comment]
Yes, works fine if I install direct from Mozilla.

Thanks
