### ISSUE TITLE
Change meaning of F1-F2-F3 shortcuts

### ISSUE THREAD

**Issue by fpohtmeh-github** [keepassxreboot/keepassxc#5037]
## Overview
App has 3 undocumented shortcuts for changing of focus: F1, F2, F3. In other software they are reserved for another functionality, so current behavior is confusing.

## Steps to Reproduce
Press F1, F2, F3 in main window.

## Expected Behavior
F1 - show help
F2 - edit value in table or list
F3 - find next. Shift+F3 - find previous. Or disable F3 at all.

## Actual Behavior
App changes focus

**Comment by droidmonkey** [comment]
So you would prefer they did absolutely nothing like before?

**Comment by fpohtmeh-github** [comment]
- Ok, probably **F1** is the history, no need to open help.

- **F2** is my main misunderstanding here. It's default Qt shortcut for editing of value in place. There are at least 3 places where it looks natural:
1. Edit entry / Edit name of attribute in list
2. Edit entry / Edit attachment name (it's upcoming feature #5034)
3. Edit group (name) in tree

Basically it should work for any Q*****View if it's not read-only.
Optionally, we can edit entry on F2. It's not "edit in place", but it's another kind of association of F2 and editing.

- **F3** looks better for search than F1. In my opinion

**Comment by droidmonkey** [comment]
F1 groups, F2 entries (if already on entries then edit the current selected entry), F3 search

**Comment by fpohtmeh-github** [comment]
I like that we move in F2 default functionality direction.
How about idea to use F3-F4-F5 instead of F1-F2-F3? We will leave F2 for a single action, it will not work differently depending on the context.
Moreover F1-F2-F3 triple isn't documented and probably is not widely used.

**Comment by droidmonkey** [comment]
I considered shifting to the higher keys but that's even more obtuse. The non documentation was a mistake and not intentional.

**Comment by fpohtmeh-github** [comment]
> F1 groups (if already on groups edit the current group), F2 entries (if already on entries then edit the current selected entry), F3 focus search. I can disable taking over F2 if the entry view is not visible, then it defaults to normal behavior.

Ok, let's stop on this
