### ISSUE TITLE
Center "Generate Password" window over the application window

### ISSUE THREAD

**Issue by jjakob** [keepassxreboot/keepassxc#5039]
## Overview

In a dual-monitor setup where the left monitor visible area is shifted downwards, the "Generate Password" window is opened outside the monitor visible area, in the top-left corner, unable to be reached by mouse.
![keepassxc-window-bug](https://user-images.githubusercontent.com/5466039/87245168-8adfd800-c443-11ea-8b4a-2fde25b01ebd.jpg)

It's still present in the window switcher and can be moved outside the dead area by doing: Alt-Tab to the window, Alt-Space to open the window's menu, press 'down' 3 times to get to 'Move', press Enter, then move the window by mouse into the monitor visible area.

It can also be seen in a screenshot done with scrot, `import -window root ~/keepassxc_window_bug.png` ('import' from the 'imagemagick' package) or xwd, but not in gnome-screenshot (which blacks out the "dead" area)

## Steps to Reproduce

1. In a dual-monitor setup on Ubuntu 16.04 (Gnome on XOrg), shift the left monitor downwards so there is a dead area above the left monitor at least the height of the "generate password" window.
2. click "Generate password"
3. The window is created in the dead area.

## Context
```
apt-cache policy keepassxc
keepassxc:
  Installed: 2.6.0-0ppa2~xenial1
  Candidate: 2.6.0-0ppa2~xenial1
  Version table:
 *** 2.6.0-0ppa2~xenial1 500
        500 http://ppa.launchpad.net/phoerious/keepassxc/ubuntu xenial/main amd64 Packages
        100 /var/lib/dpkg/status
```

```
KeePassXC - Version 2.6.0
Revision: 0765954

Qt 5.5.1
Debugging mode is disabled.

Operating system: Ubuntu 16.04.6 LTS
CPU architecture: x86_64
Kernel: linux 4.4.0-179-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.1
```

Operating System: Ubuntu 16.04
Desktop Env: Gnome
Windowing System: X11

**Comment by droidmonkey** [comment]
The window should be created directly over the keepassxc window. This could very well be related to your very old Qt version. Recommend updating that if possible.

**Comment by droidmonkey** [comment]
Actually I think this is a Qt bug because your keepassxc window edge is touching the edge of the monitor. Try moving the keepassxc window to the middle of the screen.

**Comment by jjakob** [comment]
There's no change if I move the main window to the center of the screen so that it doesn't touch any edge. I can try it on a different machine with newer Qt.

**Comment by jjakob** [comment]
The AppImage doesn't have this bug (tested on the same machine).

Since Ubuntu 16.04 LTS (xenial) is still supported and the official PPA provides this latest version to xenial, maybe it should be fixed anyway?

**Comment by droidmonkey** [comment]
Sure we can force centering, but this is definitely a Qt bug
