### ISSUE TITLE
Classic theme doesn't actually use the system theme

### ISSUE THREAD

**Issue by PureTryOut** [keepassxreboot/keepassxc#5040]
## Overview
My system theme is Breeze Dark. As the name says, it's a dark theme. However, after I set KeepassXC to use the "Classic (Platform-native)" theme, Breeze Dark is never actually used and instead a lot of grey colors appear.

![Screenshot_20200712_132247](https://user-images.githubusercontent.com/1565836/87245124-2e7cb880-c443-11ea-9ed2-7a67a1c164f8.png)

I can set the application to use the built-in dark theme, and although it then appears dark, it still doesn't look like it belongs on my desktop with the rest of the applications.

## Steps to Reproduce
1. Run KeepassXC in a KDE Plasma environment
2. Set system theme to Breeze Dark
3. Set KeepassXC theme to "Classic (Platform-native)"

## Expected Behavior
The application to look as before the 2.6.0 upgrade and use the Breeze Dark colors

## Actual Behavior
The application appears as grey with white instead.

## Context
KeePassXC - 2.6.0
Revision: 0765954

Operating System: Linux
Desktop Env: KDE Plasma
Windowing System: X11
Qt: 5.14.2

**Comment by droidmonkey** [comment]
Are you running the snap version?

**Comment by phoerious** [comment]
Looks like you are using the AppImage or Snap release.

**Comment by PureTryOut** [comment]
I am not. This is straight from the [Alpine Linux repositories](https://pkgs.alpinelinux.org/package/edge/community/x86_64/keepassxc). I _never_ use either of those 2 packaging systems.

**Comment by phoerious** [comment]
Actually, nvm. That is indeed Breeze, but it doesn't propagate the palette. This is a Qt configuration issue on your system.

**Comment by PureTryOut** [comment]
Uh, ok, strange? I never had this with any other (Qt) application before. I just set the system theme using Plasma's systemsettings application :thinking: 

Is it some missing package?

**Comment by Watkurem** [comment]
Same issue on Arch linux. I'm using `qt5ct` to configure my Qt looks.
`keepassxc-2.5.4`:
![image](https://user-images.githubusercontent.com/7015572/87677035-fac2cb00-c781-11ea-8977-283604df6954.png)
`keepassxc-2.6.0` with classic theme:
![image](https://user-images.githubusercontent.com/7015572/87677352-555c2700-c782-11ea-8838-874d5677783e.png)

I don't mind new themes as long as I can switch to the old one and it looks same (except icons, of course).

**Comment by phoerious** [comment]
Classic uses whatever is defined as your system default. If your system default is qt5ct, then you have to configure that correctly. At the moment it looks like you either have no system theme (therefore Qt falls back to Fusion) or Fusion is defined as your default in qt5ct.

**Comment by Watkurem** [comment]
> If your system default is qt5ct, then you have to configure that correctly.

@phoerious 
Yes. And I do believe it is configured:
- Everything else uses proper theme with proper colors;
- Keepassxc 2.5.4 uses proper theme with proper colors.
- Keepassxc 2.6.0 actually uses the theme set in qt5ct, but ignores color scheme.

Issue is same as the one @PureTryOut is having: theme is picked up correctly, but keepassxc ignores the colors specifically for some reason.
I don't work with Qt, but if I had to guess, I'd guess a flag like "use custom color profile and ignore system settings" that should not be set for the classic theme.

While I do have Fusion set as my theme, changing to something different in qt5ct actually changes the theme for keepassxc. For example, keepassxc 2.6.0 with "Windows" theme set via qt5ct:
![image](https://user-images.githubusercontent.com/7015572/87689988-8d1e9b00-c791-11ea-9081-44c72749b5e4.png)
It changes the theme, but it ignores the "Palette" choice. 2.5.4 works fine.

Is there a special setting I have to make for 2.6.0 somewhere?

**Comment by droidmonkey** [comment]
I figured out why this is happening, we are forcing the use of the standard palette no matter if it's classic or custom theme. Will fix in 2.6.1.

**Comment by Watkurem** [comment]
@droidmonkey 
Thanks! And thank you guys for keeping the old theme available.

Another thing to try could be using new theme, but applying system-wide palette to it (I stay on classic because I dislike the choice of white-green/black-green, for example).

**Comment by funeralchris** [comment]
Mind that color palette is most likely not the only related issues, the program is also having heavy issues with fonts and icons since 2.6.0.

![keepassxc](https://user-images.githubusercontent.com/23239177/87782537-37460380-c822-11ea-85c5-f64481768db4.png)

**Comment by phoerious** [comment]
Read the pinned issues please.

**Comment by thyringer** [comment]
I also have a small cosmetic complaint: I use KDE, and KeePassXC (no snap) adopts the native system theme, but the icons remain unchanged, only adjust their color depending on Breeze light vs. dark mode.
Is it intended that these custom icons are always used? Is it possible to change this somehow?

**Comment by droidmonkey** [comment]
Yes that is intentional and no you cannot change that behavior.

**Comment by thyringer** [comment]
This is a pity; so the application seems a bit alien. :(
