### ISSUE TITLE
Advanced Settings tab is grayed out for open database in Database settings

### ISSUE THREAD

**Issue by 92VV3M42d3v8** [keepassxreboot/keepassxc#5041]
## Overview
When we try to alter advanced settings of database like encryption algorithm etc., we can't do same as advanced settings cannot be accessed.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1.  Open any database of yours.
2.  Database> Database settings...>Advanced settings checkbox at lower left corner
3. Grayed out, so not clickable.

## Expected Behavior
It should work and we should be able to alter advanced settings.
![Annotation 2020-07-12 043241](https://user-images.githubusercontent.com/58817562/87245262-df119a80-c3f8-11ea-80ab-44452d16cb82.png)
![Annotation 2020-07-12 043241](https://user-images.githubusercontent.com/58817562/87245272-f5b7f180-c3f8-11ea-9797-22a0ba70b206.png)

## Actual Behavior
Option is grayed out.

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION 2.6.0
Revision: REVISION Website version Windows

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows
Desktop Env: Windows 10 version 2004 latest updated
Windowing System: X11/Wayland

**Comment by droidmonkey** [comment]
Go to the security category then click encryption tab. If you have to ask, don't use it.

**Comment by phoerious** [comment]
Not all settings have advanced settings.
