### ISSUE TITLE
No tray icon after update to Linux Mint Version 20

### ISSUE THREAD

**Issue by happnatious1** [keepassxreboot/keepassxc#5042]
## Overview
After update to Linux Mint 20 there is no longer a tray icon visible when KeePassXC is minimized to system tray. There is a place holder for it but no visible icon with light theme, dark theme, or colorful.

## Steps to Reproduce
Update Linux Mint 19.3 to Linux Mint 20

## Expected Behavior
There should be a tray icon visible

## Actual Behavior
No Visible icon.

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.0
Revision: 0765954
Distribution: AppImage

Qt 5.14.2
Debugging mode is disabled.

Operating system: Linux Mint 20
CPU architecture: x86_64
Kernel: linux 5.4.0-40-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.1

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux Mint
Desktop Env: Cinnamon
Windowing System:

**Comment by droidmonkey** [comment]
Change the tray icon in settings

**Comment by vicentesiufi** [comment]
I have the same issue but with other App.
Where in settings @droidmonkey ?

**Comment by droidmonkey** [comment]
In the keepassxc application settings
