### ISSUE TITLE
Inconsistent startup after updating to 2.6.0 (snap)

### ISSUE THREAD

**Issue by markquotation** [keepassxreboot/keepassxc#5043]
## Overview
KeepassXC has been updated automatically to 2.6.0 by snap (in Debian 10) and is showing inconsistent launch behaviour.

## Steps to Reproduce
1. Update to 2.6.0 using snap
2. Start KeepassXC from App-Drawer
3. Or start KeepassXC from command line

## Expected Behavior
KeepassXC launches

## Actual Behavior
KeepassXC does not launch
Or throws errors
Or launches (when run as root)

## Context
[NOTE]: # ( Give us any additional information you may have. )

When I try to launch from the App-Drawer (using Cinnamon) it does not launch at all. Task Manager does not show a task related to keepassxc (as far as I can see).

When starting from the command-line (`snap run keepassxc`) without root I receive the following error:
```
Qt: Session management error: None of the authentication protocols specified are supported
Fontconfig warning: FcPattern object weight does not accept value [0 210)
Speicherzugriffsfehler 
```
_Speicherzugriffsfehler_ being german for _Error accessing memory_

I have tried changing permissions and reloading cache as [suggested here](https://askubuntu.com/a/1244102), but the error stays the same

When I start from command line with root (`sudo snap run keepassxc`) it launches and is fully operational to my eye. This is the command line output:

```
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
YubiKey: Failed to initialize USB interface.
```

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.6.0
Revision: 0765954
Distribution: Snap
Qt 5.9.5

Operating System: Linux
Desktop Env: Cinnamon
Windowing System: X11/Wayland

**Comment by markquotation** [comment]
Please tell me, if you nee more information and if I missed a duplicate or posting rule.

**Comment by droidmonkey** [comment]
Sounds like a snap problem, not a keepasxc problem.
