### ISSUE TITLE
Allow logging into VMs

### ISSUE THREAD

**Issue by OLLI-S** [keepassxreboot/keepassxc#5045]
## Summary
I am using the **Hyper-V Manager** of Windows 10 and have created there a Windows 10 test VM.
Here I can not log into Windows 10 pressing the Auto-Type hot key.
Same for **Geforce Experience**, when I start a game, then Steam is started in the VM but here I can not log into Steam using KeePassXC.
Also pasting the password from the clipboard is not possible in both systems (but this is not an issue of KeePassXC), so I really have no idea how to enter the passwords via KeePassXC.

## Debug info from KeePassXC
KeePassXC - Version 2.6.0
Revision: 0765954

Qt 5.15.0
Debugging mode is disabled.

Operating system: Windows 10 Version 2004
CPU architecture: x86_64
Kernel: winnt 10.0.19041

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.5

**Comment by droidmonkey** [comment]
Duplicate issur

**Comment by OLLI-S** [comment]
Strange, I searched but found only one issue about VirtualBox for MacOS.

**Comment by droidmonkey** [comment]
See #1833

**Comment by OLLI-S** [comment]
Thank you, this was the issue that I mentioned above but I thought this is VirtualBox specific.

**Comment by droidmonkey** [comment]
No it affects all virtual machine interfaces
