### ISSUE TITLE
Check for PWND Passwords in the Edit-Dialog

### ISSUE THREAD

**Issue by OLLI-S** [keepassxreboot/keepassxc#5046]
## Summary
One useful feature of Bitwarden is the check for PWND passwords in the edit dialog.
Behind the password field there is a button that checks the password from the password field:

![image](https://user-images.githubusercontent.com/8037790/87248253-cafd8580-c458-11ea-8c4e-25d7ca5b5e3a.png)

![image](https://user-images.githubusercontent.com/8037790/87248255-cdf87600-c458-11ea-869b-b8845143f72f.png)

Such a button would be very useful also for KeePassXC (the best password manager in the world).

This button could also perform other checks, like weak password or duplicate password.
So users see at once if the new password is safe to use.

**Comment by droidmonkey** [comment]
I dont understand the purpose. We have this capability in the reports feature. I have no interest in duplicating that in the browser.

**Comment by OLLI-S** [comment]
There are situations where I can not use a random-generated password, like:
* I have some passwords stored that belong to family members or my karate teacher and these passwords must be "normal" for users without a password manager
* I have some websites where I log it when I am at other computers where no password manager is installed (so I need a "rememberable" and "typeable" password).

In these cases a random password is not possible.
So when I enter a new password I can check it with one click if it got breached.

Same situation for websites that still have a limitation of the password length.
My bank allows only 10 digits and here I want to see when changing the password if the new password is really safe.

So this suggestion increases the usability (one button click to check the current password instead of multiple clicks to check it from the reports.

**Comment by droidmonkey** [comment]
I'm not buying the use cases, you gave me two examples of people who need to use KeePassXC in general. How are you transmitting the password to your karate teacher? Insecure email? 😭

**Comment by droidmonkey** [comment]
I could consider this, but it would have to be super streamlined

**Comment by OLLI-S** [comment]
My Karate teacher is not good in German language so I am managing the emails of the karate dojo.
And unfortunately I am the guy that has also to update the website of the karate dojo (yeah).
I have stored the passwords of the web-mailer and the web-editor (CMS) in KeePassXC so I can log into the websites using KeePassXC.

My karate teacher has set up passwords that are easy to remember (he is not using any password manager) but unfortunately one of the passwords is breached.
So I convinced him to change both passwords.

Now I need an pronounceable, easy to remember password for each website that is not yet breached.
And here my feature coms in: I edit the password entry, enter a new password and in the password dialog I check if this password has already been breached.

Currently I have to change the password and then check in the database reports if the PW is breached.
If it is, then I edit the password and check it again in the database reports.
Having a button would save me many mouse clicks (increase the usability).

Alternatively you can add this button in the password generator.
So I open the password generator, enter the new password there (instead of generating it), check with one button click, and if it is OK I copy or apply the password to the entry.

I hope now you understand the reason for this suggestion.

Of cause I can go to https://haveibeenpwned.com/Passwords
But having this feature in KeePassXC would also other user benefit from it.

**Comment by droidmonkey** [comment]
If you are using the password generator to enter a hand crafted password then you are definitely "holding it wrong"

**Comment by SVilgelm** [comment]
What about teaching you karate teacher to use a password manager? There are a lot of managers fro any platforms, and many of them are compile with each other.
I just installed a password manager to my wife's phone, we started from one password for Skype (it was around 3 years ago) and now she stores bunch of passwords in the manager and has no problems with using it

**Comment by OLLI-S** [comment]
My karate teacher is **just one example**.

An other example (that is more common) is:
When I change the password of a website I can check the password while changing it.
This is very useful when you have some passwords listed in the reports (as unsafe, duplicate or pwnd), change them and can check them while editing them.

**Comment by SVilgelm** [comment]
But the chance, that a randomly generated password is pwnd, is very low
I understand your point, and agree, it would be great to have it, but think about this:
  every time you generate a password, or even open an entry, the KeePassXC should make an http request to check the password or it should have a 20GB+ of cache.
And I'm not sure that the haveibeenpwned.com will be available forever.
There is another problem, if KeePassXC checks a password with some external resource and at that time that resource is unavailable, so what type of icon should KeePassXC show? Is it password safe or no? We cannot show that it's safe, because we cannot check it and at same time we cannot show that it's not safe for same reason.

**Comment by OLLI-S** [comment]
I suggested to have a button where you can execute the check.
If the HIBP service is not available, there should be a message shown telling that the service is not available.
When the checked password is save or unsafe, then there also should be a message.

**Comment by llucax** [comment]
Just to add an extra data point to this issue. I just discovered keepassxc had HIBP integration and I have been using it for years. I think having an option to automatically check for any new password/passwords updates to HIBP would give this integration a much bigger visibility.

You can even not make the request automatically but just have a button with a nice HIBP logo so users can click it whenever they want to. This would also give much more visibility to the integration. Same for reused passwords in one owns database. Anything that prevents (and educate) the user to have good password hygiene should be a good addition for a password manager IMHO.

**Comment by droidmonkey** [comment]
We will not implement this, instead use the database reports.
