### ISSUE TITLE
Button icons are blank in Linux Mint 19.3 Cinnamon

### ISSUE THREAD

**Issue by dkellygb** [keepassxreboot/keepassxc#5048]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
After the upgrade, the icons on several of the buttons have disappeared leaving blank buttons.  The only way to know the function of a button is by the tool tip.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Upgrade
2. Open Keepassxc
3. Notice blank buttons on the tool bar.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

Buttons should have an icon to understand their function.
![image](https://user-images.githubusercontent.com/16733048/87252007-bbd20400-c467-11ea-8cd5-81f764818ef9.png)

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

Button is blank.

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.0
Revision: 0765954

Qt 5.9.5
Debugging mode is disabled.

Operating system: Linux Mint 19.3
CPU architecture: x86_64
Kernel: linux 5.3.0-62-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.1

[NOTE]: # ( Pick choices based on your environment )

Desktop Env: Cinnamon
Windowing System: X11/Wayland

**Comment by dkellygb** [comment]
Also, changed QT settings from cleanlooks to GTK2.  Behaviour was the same.

**Comment by ipeacocks** [comment]
The same problem for Ubuntu 20.04 with Gnome.

**Comment by ybychenok** [comment]
Oh, now I see pinned issue. Sorry.

**Comment by droidmonkey** [comment]
Pinned issue

**Comment by Junker** [comment]
The same problem for ArchLinux

**Comment by phoerious** [comment]
Read the pinned issues please.
