### ISSUE TITLE
"Search Results" banner background color is not themed properly

### ISSUE THREAD

**Issue by zyv** [keepassxreboot/keepassxc#5049]
## Overview

The background color of "Search Results" panel is bright yellow and doesn't match the rest of the theme.

## Steps to Reproduce
1. Enter something in the "Search" box
2. Observe the results

## Expected Behavior

Color of the panel matches the rest of the theme.

## Actual Behavior

Panel is coloured bright yellow:

<img width="807" alt="Screenshot 2020-07-12 at 19 23 59" src="https://user-images.githubusercontent.com/607401/87252763-fcd11500-c475-11ea-998b-788e5a7e48b0.png">

## Context

KeePassXC - Version 2.6.0
Revision: 0765954

Qt 5.15.0
Debugging mode is disabled.

Operating system: macOS Mojave (10.14)
CPU architecture: x86_64
Kernel: darwin 18.7.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
 libgcrypt 1.8.5

**Comment by phoerious** [comment]
That's something we wanted to fix, thanks for the reminder.
