### ISSUE TITLE
Automatic launch at system startup

### ISSUE THREAD

**Issue by andriy-svirskyy** [keepassxreboot/keepassxc#5050]
## Overview
Specifying an option 'Automatically launch KeePassXC at system startup' in application settings does not result in application being launched at system startup

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Install app via AppImage
2. Set the option 'Automatically launch KeePassXC at system startup' to ON, click OK button
3. Restart the computer
4. Log in into the same computer account

## Expected Behavior
KeePassXC is running

## Actual Behavior
KeePassXC is not running

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.0
Revision: 0765954
Distribution: AppImage

Qt 5.14.2
Debugging mode is disabled.

Operating system: Ubuntu 18.04.4 LTS
CPU architecture: x86_64
Kernel: linux 4.15.0-109-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.1

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env:
Windowing System:

**Comment by phoerious** [comment]
The AppImage adds the current binary path, which is a temporary path. We'd need to use the original AppImage path instead.

**Comment by FaMux** [comment]
@phoerious This issue is resolved with 2.6.4.
