### ISSUE TITLE
Browser integration not finding entry credentials after 2.6.0 upgrade

### ISSUE THREAD

**Issue by dejaboom** [keepassxreboot/keepassxc#5052]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

I am using Windows 10 Pro Version 10.0.18363 (64-bit) and the web browsers I use KeePassXC 2.6.0 on are Google Chrome Version 83.0.4103.116 (Official Build) (32-bit) and Opera Version 69.0.3686.57.  Both web browsers are connected to KeePassXC 2.6.0 via KeePassXC-Browser extension.

There are 2 sites that clearly have username and password fields which were previously performing auto-fill properly under KeePassXC 2.5.4 are no longer doing so now:

InSightly:  https://login.insightly.com/User/Login?ReturnUrl=%2F

Kronos:  http://10.151.10.122/wfc/logon  (This link is likely inaccessible due to being on company intranet, however I'm including screenshot of webpage)

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Just go to the site and the appropriate fields do not auto-fill as they should

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

I have the username and password for each of these sites in my database file and they are not autofilling into the appropriate fields as they should
![InSightly Webpage](https://user-images.githubusercontent.com/68215759/87273628-441fcb80-c49f-11ea-8f66-28cd0ea1276a.jpg)
![Kronos Webpage](https://user-images.githubusercontent.com/68215759/87273631-441fcb80-c49f-11ea-8daa-697ee0567e89.jpg)

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows/Linux/macOS
Desktop Env: Gnome/KDE/XFCE/Mate/Cinnamon
Windowing System: X11/Wayland

**Comment by jbastruz** [comment]
Hello, On my side I have something similar, I'm using KeepassXC on my Mac, MacOS 10.15.5, the extension is installed on Brave V 1.10.97, KeePassXC-Browser extension propose the auto-fill, but pretends it doesn't find any match for the Websites

**Comment by varjolintu** [comment]
This is fixed by: https://github.com/keepassxreboot/keepassxc-browser/pull/937
