### ISSUE TITLE
Auto-type doesn't minimize the KeepassXC application after the first time.

### ISSUE THREAD

**Issue by LennyMcLennington** [keepassxreboot/keepassxc#5053]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
Auto-type doesn't minimize the KeepassXC application on any auto-types attempted after the first one.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Perform an auto-type
2. Attempt to perform another auto-type

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
The second auto-type makes KeePassXC minimize and it auto-types into the application that was intended.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
The second auto-type does not make KeePassXC minimize and therefore it auto-types into KeePassXC itself instead of the application I wanted it to type in.

## Context
[NOTE]: # ( Give us any additional information you may have. )
This is NOT the same as #4962 with it failing when "Hide window to system tray when minimized" is enabled. This happens with that option disabled.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.0
Revision: 0765954

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: KDE
Windowing System: X11

**Comment by droidmonkey** [comment]
Duplicate of #4962

**Comment by LennyMcLennington** [comment]
This is not a duplicate, this happens with that option disabled and is unrelated. It's not minimizing for a short amount of time and then re-appearing, it's literally not minimizing at all.

**Comment by droidmonkey** [comment]
I have never witnessed this problem and there is nothing in code that would cause it.

**Comment by LennyMcLennington** [comment]
This is related to KWin's "Keep window thumbnails: Always" option. I don't know why I had that enabled, my apologies.

**Comment by jmichel359** [comment]
I have this problem with gnome shell too.
