### ISSUE TITLE
Browser plugin does not detect Magento 1.x login form

### ISSUE THREAD

**Issue by thegeek1977** [keepassxreboot/keepassxc#5054]
Hi.

Lately The browser plugin (not browser specific but testet with Latest Firefox And Google Chrome) does not detect the login form for magentos backend like this one 

http://hyndeskraedderen.dev.magepartner.net/admin

The above is not a production site so you're welcome to go and test there. 

Furthermore selecting "choose own credential fields for this page" does not work as the fields of the form comes up un
![Screenshot_2020-07-13 Log ind på Magento Admin](https://user-images.githubusercontent.com/11729750/87313198-d10b6900-c521-11ea-9a4f-5464934aa566.png)
selectable once the above is selected. Also "redetect login fields" does not help. 

The screenshot is taken right after the "choose own crtedential fields" are selected. The fields for the username "Brugernavn" and the password "Kodeord" cannot be selected making the field mapping impossible.

What can be done to make this work. It has been, sort of, working before but suddently stopped working on multible computer running both Windows (8.1) and Linux. Don't know what to do from here to remedy this situation.

Thank you in advance.

**Comment by droidmonkey** [comment]
Fixed in latest plugin release
