### ISSUE TITLE
Login with Yubikey - Keybase

### ISSUE THREAD

**Issue by Ralffe** [keepassxreboot/keepassxc#5057]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
If Keybase is installed on your computer and you are not logged in to Keybase, there is no access when logging in to KeepassXC with a yubikey. Only after logging in to Keybase the yubikey can be accessed when opening the database in KeepassXC.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Login with Yubikey not possible until you are logged in to Keybase.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
The normal login with password and Yubikey.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
No login possible until you are logged in to Keybase.

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.0
Revision: 0765954

Qt 5.15.0
Diagnosemodus ist deaktiviert.

Betriebssystem: macOS 10.15
CPU-Architektur: x86_64
Kernel: darwin 19.5.0

Aktivierte Erweiterungen:
- Auto-Type
- Browser-Integration
- SSH-Agent
- KeeShare (bestätigtes und unbestätigtes Teilen)
- YubiKey
- TouchID

Kryptographische Bibliotheken:
 libgcrypt 1.8.5

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS 10.5.5

**Comment by droidmonkey** [comment]
I have no idea what keybase is, has nothing to do with our program.

**Comment by Ralffe** [comment]
https://keybase.io/

**Comment by droidmonkey** [comment]
If keybase is holding the USB port for exclusive use prior to unlocking it. File a bug with keybase please, this isn't on us.
