### ISSUE TITLE
Screen Broken (2.6.0) (arch) (gnome)

### ISSUE THREAD

**Issue by tmpjg** [keepassxreboot/keepassxc#5058]
## Overview
hi! i recently upgrade my keepass (2.6.0) on archlinux with gnome (3.36.4)  and after that, the principal screen is broken

![Untitled](https://user-images.githubusercontent.com/58488383/87338659-e1204a00-c51b-11ea-923f-1d4e70618209.png)

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Upgrade keepassxc 2.6.0
2. Open keepassxc

## Expected Behavior
Nice screen with my passwords :)

## Actual Behavior
The screen looks broken. I cant click anything. 

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.6.0-1

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: Gnome
Windowing System: Wayland

**Comment by droidmonkey** [comment]
Pinned issues
