### ISSUE TITLE
Keepassxc 260 : "generate password" too close to "toggle password"

### ISSUE THREAD

**Issue by LudovicGui** [keepassxreboot/keepassxc#5059]
Hi,

At the end of the field "Password" of an entry, we can find two icons : "generate password" and "toggle password". It is very easy to click on "generate password" instead of "toggle password". Then, "confirm" is the default action, so we can easily change a password involuntarily.
The only icon at the end of the field "Password" should be 'toggle password". "Generate password" should be located elsewhere, far from the field "password".
 
Many thanks.

**Comment by droidmonkey** [comment]
Sorry but this is not something we are going to change. You can hide/unhide passwords with the Ctrl+H keyboard shortcut to prevent misclicks.
