### ISSUE TITLE
Autotype KeepassXC in snap package Ubuntu 14.04 LTS

### ISSUE THREAD

**Issue by wowotiel** [keepassxreboot/keepassxc#506]
## Expected Behavior
autotype function with the key combination: ctrl+V
choose autotype function within the menu
## Current Behavior
autotype function with the key combination: ctrl+V : nothing happens
choose autotype function within the contextmenu : this is working ok
## Possible Solution
Make the key combination: ctrl+V working

## Steps to Reproduce (for bugs)
1. Install snap
2. Open or create a database
3. The key combination ctrl+V

## Context
Without this feature the snap version is not usable for me.
So I am using the program KeePassX 2.03 because in this program the key combination ctrl+V is working ok.

## Your Environment
* KeePassXC version/commit used: 2.1.4 
revision: cb283bb95ae559d044415f426f841c27bff383f0
* Qt version: Qt 5.6.1
* libgcrypt 1.7.2-beta
* Extensions: KeepassHTTP and Autotype
* Operating System and version: Ubuntu 14.04 LTS 64-bit

**Comment by e2jk** [comment]
I hit the same issue on Ubuntu 16.04.2 LTS, keepassxc 2.1.4 installed via Snap.
Right-clicking on an entry and selecting Autotype does work fine, so it's not the entire feature but just the shortcut that is not recognized.

Note that I'm also hitting the same issue with Ctrl+U to Open the URL (issue #507), but that other shortcuts (such as Ctrl+B and Ctrl+C) work fine.

**Comment by droidmonkey** [comment]
When using snaps all those tricks go out the window.

**Comment by droidmonkey** [comment]
Currently working in 2.2.0 snap.

**Comment by wowotiel** [comment]
I have upgraded form Ubuntu 14.04 LTS to Ubuntu 16.04 LTS.
With version 2.2.0 I have tested ctrl+V =autotype and it is now working fine.
Thanks!
