### ISSUE TITLE
Missing extended Autotype

### ISSUE THREAD

**Issue by ujmoser** [keepassxreboot/keepassxc#5060]
Until I upgraded my notebook last weekend I used keepass2 on Linux. Now I installed keepassxc and I miss the extended Autotype that is available in keepass2.

**Comment by droidmonkey** [comment]
I have no idea what you are talking about.

**Comment by ujmoser** [comment]
keepass2 has an option to enable additional autotype functions except for that to autotype username and password. This enables an additional context menu entry with a submenu that offers additional autotype functions like only autotype the username or username + TAB or password or password + ENTER etc. This way you can autofill forms that for example only require a password or PIN. To give an example: I use a banking application that has the usernames for all accounts stored in its database but requires the passwords to be provided when accessing the accounts. This way I can use the same entry in keepass to directly to the bank account through their ebanking website and use it to connect to the accounts from within my banking application.
![Bildschirmfoto zu 2020-07-13 22-00-13](https://user-images.githubusercontent.com/4654822/87349239-42fda580-c556-11ea-99e6-7136b9724642.png)
![IMG_20200713_220715](https://user-images.githubusercontent.com/4654822/87349673-fd8da800-c556-11ea-9a62-1c46a4243119.jpg)

**Comment by droidmonkey** [comment]
Being implemented already in #4891
