### ISSUE TITLE
Minimize on application startup not working

### ISSUE THREAD

**Issue by W4RH4WK** [keepassxreboot/keepassxc#5061]
## Overview

With the upgrade to 2.6.0 the *Minimize window at application startup* options seems to be broken.

![image](https://user-images.githubusercontent.com/328798/87351929-85c17c80-c55a-11ea-8b28-1ee1b43917ed.png)

The application starts upon login, the window is not minimized, and it even steals the focus from other applications during startup.

## Context

I am using the tray icon:

![image](https://user-images.githubusercontent.com/328798/87352090-c28d7380-c55a-11ea-802b-e0e639a23a26.png)

KeePassXC - Version 2.6.0
Revision: 0765954

Operating System: Windows

**Comment by droidmonkey** [comment]
Seems to work fine for me (Windows 10, 2.6.0). Does it also fail when you start the program normally or only on system login?

**Comment by W4RH4WK** [comment]
I think I just figured it out. There was still a shortcut to the application located in the *startup* folder. My guess is that it automatically started via the startup setting (registry entry) before my system invoked that shortcut. Since the instance was already running (and single instance is forced) it would just bring up the application's main window. So definitely an error on my end.

Remove the shortcut seemed to resolve the issue just fine.
