### ISSUE TITLE
Allow searching without toolbar

### ISSUE THREAD

**Issue by elig0n** [keepassxreboot/keepassxc#5063]
Please allow searching without toolbar because either if the toolbar is hidden, or the search box inside the toolbar is too far and thus hidden the search functionality will not operate.

I've seen it done with a popup input box on the bottom/top right of the entry list, or entirely a popup dialog with filter criteria (search in title, description etc...). reg-ex search can also prove useful.

**Comment by droidmonkey** [comment]
Duplicate request

**Comment by elig0n** [comment]
please link?

**Comment by droidmonkey** [comment]
Please search
