### ISSUE TITLE
KeePassXC Doesn't Forget (macOS)

### ISSUE THREAD

**Issue by tahyonline** [keepassxreboot/keepassxc#5065]
## Overview
Previously used databases are displayed when _Remember previously used databases_ is turned off.

![Screenshot 2020-07-14 at 08 16 51](https://user-images.githubusercontent.com/50040009/87396821-525b0e00-c5ab-11ea-920a-7debefd73a41.jpg)

![Screenshot 2020-07-14 at 08 17 13](https://user-images.githubusercontent.com/50040009/87396830-571fc200-c5ab-11ea-9fec-3eb5e4803256.jpg)

Fresh install of KeePassXC 2.6.0 (via Homebrew) on fresh install of macOS Catalina.

## Steps to Reproduce
0. Fresh install of KeePassXC
1. Open some databases
2. Quit, forgetting that it's a new install and you haven't turned off _Remeber previously used databases_
3. Reopen KeePassXC
4. Realise your mistake and turn off _Remeber previously used databases_
5. Quit KeePassXC
6. Reopen KeePassXC

## Expected Behavior
The tabs of the previously opened databases should not show.

## Actual Behavior
The tabs of the previously opened databases are still there.

In 2.5.x, the old database tabs were correctly not shown.

## Context
KeePassXC - Version 2.6.0
Revision: 0765954

Qt 5.15.0
Debugging mode is disabled.

Operating system: macOS 10.15
CPU architecture: x86_64
Kernel: darwin 19.5.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
 libgcrypt 1.8.5

**Comment by phoerious** [comment]
It might be that we are not clearing the previously remembered databases.

**Comment by droidmonkey** [comment]
Sometimes macOS gets confused with the config file. We absolutely uncheck both of those checkboxes when you uncheck the parent. Check it and uncheck it, the setting gets disabled.

**Comment by tahyonline** [comment]
No, checking and unchecking does not work.

1. Initial state:
<img width="465" alt="Screenshot 2020-07-15 at 11 21 45" src="https://user-images.githubusercontent.com/50040009/87534286-b8b85d00-c68d-11ea-9cee-0759dab3e10f.png">

2. Re-enable:
<img width="465" alt="Screenshot 2020-07-15 at 11 21 56" src="https://user-images.githubusercontent.com/50040009/87534328-c66de280-c68d-11ea-8635-82bdfbe4a4d4.png">

3. Uncheck both underneath
<img width="465" alt="Screenshot 2020-07-15 at 11 22 07" src="https://user-images.githubusercontent.com/50040009/87534364-d38ad180-c68d-11ea-8bb0-790f024d3345.png">

4. Uncheck _Remember..._
<img width="465" alt="Screenshot 2020-07-15 at 11 22 18" src="https://user-images.githubusercontent.com/50040009/87534386-d8e81c00-c68d-11ea-84b8-1d32426602f8.png">

5. Click OK

6. Back to Preferences, and...
<img width="465" alt="Screenshot 2020-07-15 at 11 22 32" src="https://user-images.githubusercontent.com/50040009/87534437-ec938280-c68d-11ea-9d68-1989cf9ce094.png">

**Comment by droidmonkey** [comment]
Do any of your settings changes save? You probably need to clear out the config file under ~/Library/Application Support/KeePassXC

**Comment by tahyonline** [comment]
Cleared file, no effect.

After clearing, the app asked for checking for updates - this was immediately saved.

In addition, tested:
_Minimize window after locking_
_Backup database file before saving_

These are both saving.

**Comment by droidmonkey** [comment]
Confirmed this is a macOS only bug. No obvious reason for it though...
