### ISSUE TITLE
KeepassXC connecting to google??

### ISSUE THREAD

**Issue by Thomas131** [keepassxreboot/keepassxc#5067]
## Overview
I installed KeepassXC using snap. Today I noticed this:
```bash
sudo netstat -p | grep keepassxc
tcp       59      0 MyHostname:47556              151.101.192.201:https   CLOSE_WAIT  25408/keepassxc-pro 
tcp        1      0 MyHostname:37270              93.184.220.29:http      CLOSE_WAIT  25408/keepassxc-pro 
tcp        1      0 MyHostname:43762              muc12s04-in-f14.1:https CLOSE_WAIT  25408/keepassxc-pro 
tcp        1      0 MyHostname:39624              server-99-86-243-:https CLOSE_WAIT  25408/keepassxc-pro 
udp    22528      0 MyHostname:59635              muc12s04-in-f14.1e1:443 VERBUNDEN   25408/keepassxc-pro 
udp    42496      0 MyHostname:40667              muc11s03-in-f3.1e10:443 VERBUNDEN   25408/keepassxc-pro
```

Can someone give me an explaination for it? And maybe document it in the FAQ?

## Steps to Reproduce
(I didn't try it in a fresh system, but that is basically what I did)
1. install it using Snap on Linux Mint 19.1
2. use it for a while
3. execute sudo netstat -p | grep keepass

## Expected Behavior
It not connecting to a foreign Server in an undocumented way. I checkt through the settings and the only setting enabled which will open a connection is checking for updates weekly. But that shouldn't keep an connection open, should it?

## Actual Behavior
It connects to servers run by Google and other IP-Adresses.

## Context
KeePassXC - Version 2.6.0
Revision: 0765954
Distribution: Snap

Operating System: Linux Mint 19.1
Desktop Env: Cinnamon

**Comment by Thomas131** [comment]
Oh, I enabled the browser-extension. Does it have something to do with that? But can't they connect locally? If not can't this be documented somewhere?

Thanks in advance!
Thomas

**Comment by phoerious** [comment]
This is just a bug in Firefox. See https://github.com/keepassxreboot/keepassxc-browser/issues/100
