### ISSUE TITLE
build consistently failing at the same point

### ISSUE THREAD

**Issue by boudiccas** [keepassxreboot/keepassxc#5068]
## Overview
My build from source is consistently failing at 92% saying 

```
/home/boudiccas/git/keepassxc/src/gui/osutils/nixutils/NixUtils.cpp:30:10: fatal error: qpa/qplatformnativeinterface.h: No such file or directory
 #include <qpa/qplatformnativeinterface.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
````

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. cmake -DWITH_XC_ALL=ON -DCMAKE_BUILD_TYPE=Release ..
2. make -j8

## Expected Behavior
I'm expecting it to build as consistently as it has before. I've built the last 2 versions very easily from source, but now its failing.

## Actual Behavior
````
[ 92%] Building CXX object src/CMakeFiles/keepassx_core.dir/gui/osutils/nixutils/NixUtils.cpp.o
[ 92%] Building CXX object src/CMakeFiles/keepassx_core.dir/core/OSEventFilter.cpp.o
/home/boudiccas/git/keepassxc/src/gui/osutils/nixutils/NixUtils.cpp:30:10: fatal error: qpa/qplatformnativeinterface.h: No such file or directory
 #include <qpa/qplatformnativeinterface.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [src/CMakeFiles/keepassx_core.dir/build.make:2345: src/CMakeFiles/keepassx_core.dir/gui/osutils/nixutils/NixUtils.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:204: src/CMakeFiles/keepassx_core.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
````

## Context
I'm using Debian 10, and have these packages installed for the build - build-essential cmake g++ qttools5-dev qttools5-dev-tools libqt5svg5-dev libgcrypt20-dev libqrencode-dev zlib1g-dev mesa-common-dev libgl1-mesa-glx qtbase5-dev libgl1-mesa-dev libglu1-mesa-dev libgl-dev libargon2-0-dev qtbase5-dev qttools5-dev qttools5-dev-tools libqrencode-dev zlib1g-dev libgl-dev libglu-dev libqt5svg5-dev libgcrypt20-dev libxi-dev libxtst-dev libqt5x11extras5-dev libyubikey-dev libykpers-1-dev libsodium-dev libcurl4-openssl-dev libquazip5-dev libgl-dev libglu-dev mesa-common-dev libgl1-mesa-glx libgl-dev libglu-dev mesa-common-dev libgl1-mesa-glx libxi-dev libxtst-dev libqt5x11extras5-dev libyubikey-dev libykpers-1-dev libsodium-dev libcurl4-openssl-dev libquazip5-dev asciidoctor

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.6.0 - this is what I'm trying to build

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: fluxbox
Windowing System: X11

**Comment by phoerious** [comment]
You need to install qtbase5-private-dev. See wiki: https://github.com/keepassxreboot/keepassxc/wiki/Set-up-Build-Environment-on-Linux
