### ISSUE TITLE
show existing shortcut information in text when hoovering icons

### ISSUE THREAD

**Issue by aisbergde** [keepassxreboot/keepassxc#5074]
## Summary

It should be possible to get the shortcut information in the hoover text of icons if a shortcut exists.
Currently shortcut information is available only when using the menu.
It is common in many programs to show shortcut information when hoovering icons.
For example the text should be "open database... (Ctrl-O)" but not only "open database..."

I don't remember how this was before 2.6.0 but currently when I hoover the icons no shortcut information is available in the text and I can't find an option to enable.

## Context

I remember and learn shortcuts only when I use some action often and then decide to spent energy to learn shortcuts.
If I don't see shortcut information I think there is no shortcut.
I want to use keepassxc similar to other software.

**Comment by droidmonkey** [comment]
That information is all in the menu items unless you are on Mac

**Comment by aisbergde** [comment]
I know, I even wrote about this:
> Currently shortcut information is available only when using the menu.

And I still want to request to show this information also in hoover text as this is common in many other programs.
I know this is only a "nice to have" feature.

**Comment by droidmonkey** [comment]
Unfortunately we won't be doing this feature since it requires significant code work. There is no automatic way to do this in Qt.
