### ISSUE TITLE
Colorized Icons on Toolbar

### ISSUE THREAD

**Issue by abacao** [keepassxreboot/keepassxc#5075]
1st, thank you for all the work with this app.
2nd, the new 2.6 is really pretty.
3rd, I'm struggling with icons on toolbar. I believe that if they were colored, It would be a better experience rather than a grey stylish icon.

**Comment by phoerious** [comment]
We will not change the toolbar icons. The icons are so simple that colour wouldn't help anyway.

**Comment by abacao** [comment]
That wasn't the reply I was hoping (and to be honest the answer was really "dry".
I was suggesting the possibility of multiple choice as it exists on the tray icon, not a mandatory change.
:vulcan_salute:
