### ISSUE TITLE
Database Reports issues

### ISSUE THREAD

**Issue by abacao** [keepassxreboot/keepassxc#5076]
Using Ubuntu 20.04 and Keepassxc 2.6.0

1. Can't move the size of columns.
2. Negative Score isn't being sorted correctly.
Ex: 
-1
-161
-20
-22
-280
3. Please allow multi-select to exclude from report.
4. On each group, please add option to exclude group from report.

**Comment by finitenamespace** [comment]
Positive values also have issues sorting. 
Unfortunately I fixed a bunch before thinking to report the bug so I only have one remaining:

![Capture](https://user-images.githubusercontent.com/39365213/88444878-d1c9c680-ce62-11ea-82ac-0257174d9953.PNG)

**Comment by droidmonkey** [comment]
Related to #4976
