### ISSUE TITLE
Crash on disabling/changing output in Sway

### ISSUE THREAD

**Issue by chron-isch** [keepassxreboot/keepassxc#5078]
## Overview
If you have KeepassXC running and disable/enable an output(closing the laptop lid for example) the KeepassXC tray icon will go invisible and the entire programm will stop responding/crash.

## Steps to Reproduce
1. Start KeePassXC with tray icon enabled
2. 
```
swaymsg output eDP-1 disable
swaymsg output eDP-1 enable
```
Or close/open the laptop lid
3. Tray icon goes transparent and keepassxc will stop responding

## Expected Behavior
Don't crash on output change

## Actual Behavior
After the crash calling keepassxc again will simply result in `Another instance of KeePassXC is already running.` but it will not open the keepassxc window. I have to `pkill -9 keepassxc` and start it again.

## Context
```
Operating System: ArchLinux
Desktop Env: Sway 1.5-rc2
Windowing System: Wayland
```
```
KeePassXC - Version 2.6.0
Revision: 0765954

Qt 5.15.0
Debugging mode is disabled.

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 5.7.8-arch1-1

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.6```

**Comment by droidmonkey** [comment]
What does changing/disabling output mean? Are you referring to the display?

**Comment by droidmonkey** [comment]
This is a Qt bug: https://bugreports.qt.io/browse/QTBUG-75768
