### ISSUE TITLE
System tray icon does not respect system theme

### ISSUE THREAD

**Issue by magnus-gross** [keepassxreboot/keepassxc#5080]
![Screenshot_20200714_214857](https://user-images.githubusercontent.com/21310755/87469628-da78fc00-c61b-11ea-80de-b5d00bd5e17d.png)

As you can see, the Keepass icon no longer respects the system theme and looks vastly different in comparison to other icons. Before 2.6, the icon was monochrome like all the other icons. With 2.6, the icon now doesn't respect the icon theme anymore.

**Comment by droidmonkey** [comment]
Just select the monochrome dark icon from the application settings

**Comment by phoerious** [comment]
"No longer"

It has never done that.
