### ISSUE TITLE
Use of uninitialized memory

### ISSUE THREAD

**Issue by jo-so** [keepassxreboot/keepassxc#5081]
## Overview

I've ran *valgrind* with keepassxc and it reported an issue:

```valgrind
==736644== Conditional jump or move depends on uninitialised value(s)
==736644==    at 0x1B7BBC: MessageWidget::hideMessage() (MessageWidget.cpp:77)
==736644==    by 0x19C308: MainWindow::MainWindow() (MainWindow.cpp:199)
==736644==    by 0x17BFED: main (main.cpp:135)
```

The member variable `MessageWidget.m_animate` don't become initialized and is used in 

```cpp
void MessageWidget::hideMessage()
{
    emit hideAnimationStarted();
    if (m_animate) {
        animatedHide();
    } else {
```

# Debug info

KeePassXC - Version 2.6.0-snapshot
Build Typ: Snapshot
Revision: 316037d

Qt 5.14.2
Diagnosemodus ist aktiviert.

Betriebssystem: Debian GNU/Linux bullseye/sid
CPU-Architektur: x86_64
Kernel: linux 5.7.0-1-amd64

Aktivierte Erweiterungen:
- Auto-Type
- Browser-Integration
- SSH-Agent
- Secret-Service-Integration

Kryptographische Bibliotheken:
 libgcrypt 1.8.5

**Comment by droidmonkey** [comment]
Good find!
