### ISSUE TITLE
Searching does not include folder names anymore

### ISSUE THREAD

**Issue by katsar0v** [keepassxreboot/keepassxc#5085]
## Overview
Searching in KeePassXC (2.6.0) does not include folder names anymore.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Just search the name of a folder

## Expected Behavior
Find entries from this folder? As in previous version of keepassxc

## Actual Behavior
No entries are shown

## Context
I updated to 2.6.0 and maybe it was not a good decision...

Also saw that use an old version of Qt.. it would be great to update

```
KeePassXC - Version 2.6.0
Revision: 0765954

Qt 5.9.5
Debugging mode is disabled.

Operating system: Ubuntu 18.04.4 LTS
CPU architecture: x86_64
Kernel: linux 5.3.0-62-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.1
```

Operating System: Linux Ubuntu 18.04
Desktop Env: Default
Windowing System: Default

**Comment by droidmonkey** [comment]
To search for a folder use the `group:<search term >` or simply g:

**Comment by katsar0v** [comment]
Why did you close @droidmonkey, did you read the problem thoroughly? If I want to search all entries within a folder, why do I have to type this explicitly? Sometimes I don't know the url or the group, but know a keyword, which also may be in the notes. I cannot explicitly define this then

**Comment by droidmonkey** [comment]
Your problem statement was literally find groups, that's how you do it.

**Comment by katsar0v** [comment]
That's a bad decision and I will roll back then. The searched keyword can also match the group name, I don't see a reason not to include entries whose group matches the search phrase.

**Comment by droidmonkey** [comment]
🤷 If you're interested you can read the lengthy discussion of this over in #3482

**Comment by droidmonkey** [comment]
As for your Qt version, that is on you and your system. You are running Xenial which is locked into Qt 5.9.5. If you want a newer version of Qt, use a PPA or upgrade your Ubuntu version.

**Comment by katsar0v** [comment]
```
I'm not sure what the point is (besides combining entries from similarly named disparate groups). You can enable "group scoped" search by clicking the search icon to the left of the bar. With that, just select the group you want to search in and do your search.

What I'm trying to say is the groups are already binning the entries.
```
This group scoped does not help. And it seems you just took decision and just hammered it. I can see other people also want that the group name is taken as well when searching.

E.g. I have a group `localhost` and instead of previously writing just `local` in the search field, I have to type `g:local`, which is just inconvenient. Also when a two groups have the same name but under different parent, you don't see this in the search results

**Comment by katsar0v** [comment]
In such case, to satisfy both world, the best decision would be to add a setting, which defines how the search field acts. Under setting, I mean here 
![image](https://user-images.githubusercontent.com/7236157/87543247-b01f5100-c6a4-11ea-98ea-9db690a828a1.png)

not a click on the search icon

**Comment by droidmonkey** [comment]
If you want to search explicit hierarchy you can use my implementation which is quite robust:

https://github.com/keepassxreboot/keepassxc/pull/4705#issuecomment-625867901

And remember you can use wildcards so this is a perfectly valid search: `g:/parent*/local router`

**Comment by phoerious** [comment]
Xenial is 5.5 even, which has a lot of known bugs and will never get updates.

**Comment by katsar0v** [comment]
And where is the discussion where the decision was made to remove this from the search?

@phoerious thanks for the off-topic

**Comment by katsar0v** [comment]
Obviously there is no point in debating this all day, but I (as well some other people from the community) think that this was not a good decision. What would satisfy all parties would be, as suggested, a setting for the search box and how it acts. 

@droidmonkey I don't want wildcards or any fancy keywords. I want when I search for a term (could be `asd`) that also the entries from group `asd1` and `asd2` come.

**Comment by katsar0v** [comment]
Just saw that some shortcuts were changed. E.g. `ctrl + shift + v` for auto type. But on ctrl + shift my language changes... I don't know how you make decisions here and who closes/merges the PRs, but except the new UI, the new KeePassXC is not an improvement for me. I cannot even set the shortcut, because someone here decided to change it, now I have to re-order the shortcuts of my system so it works with KeePass.

**Comment by droidmonkey** [comment]
I'm sure someday some pissed off user is going to rail on your bad decisions in your programming as well. Thanks for the feedback.

**Comment by katsar0v** [comment]
Yeah, if there were so many conflicts. Why didn't you just create the settings for it so everybody can do it however he likes. Now you basically hammered your code and "pissed off" me + other users. You are welcome for the feedback! Anytime :wink:

**Comment by phoerious** [comment]
We had a bunch of possible shortcuts and settled on Ctrl+Shift+V because we knew it would piss of you + "other users". Next release will copy entries with Ctrl+Alt+Delete.
