### ISSUE TITLE
Search ctrl+F does not work ubuntu 18.04

### ISSUE THREAD

**Issue by bulgin** [keepassxreboot/keepassxc#5087]
combination of ctrl+F does not bring up search in Ubuntu 18.04

**Comment by phoerious** [comment]
Are you sure your window is large enough to show the search field?

**Comment by bulgin** [comment]
I have a 27" monitor with keepassxc expanded to the full width.

**Comment by droidmonkey** [comment]
No screenshot, no bug report template information, this is not a bug.

**Comment by bulgin** [comment]
Ok.  So how do I handle this?  Appreciate some direction.

**Comment by bulgin** [comment]
Can I leave a video of me pressing the cntrl+F? And then show that the search bar does not open?  How about that?  Otherwise a screenshot of what?  I can't show a screenshot of something that doesn't happen.

**Comment by phoerious** [comment]
The search bar is not supposed to "open". It is always there.

**Comment by bulgin** [comment]
Discovered that if I clear cache and cookies (a common procedure) column width is not preserved, at least not on my install of Ubuntu. 18.04

**Comment by bulgin** [comment]
The search bar is not "open" by default I need to right click on right-facing chevons (>>) to open it and then search.

**Comment by droidmonkey** [comment]
I'm pretty sure you have text showing in your toolbar. You'll want to do this:

![image](https://user-images.githubusercontent.com/2809491/87548410-75082800-c67a-11ea-81ff-9637610b78b4.png)

**Comment by bulgin** [comment]
Problem solved!  Thank you droidmonkey.
