### ISSUE TITLE
Please preserve column width in 2.6.0

### ISSUE THREAD

**Issue by bulgin** [keepassxreboot/keepassxc#5088]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
Previous versions preserved column width in classic template.  Now every time I open Keypassxc I must re-align columns to view titles. 

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )

**Comment by droidmonkey** [comment]
column width is absolutely preserved between sessions.

**Comment by bulgin** [comment]
Absolutely as in what?  I'm reporting that it doesn't.  Should I present a video of my opening and closing then re-opening keeppassxc?  Would that be sufficient to prove my issue?

**Comment by phoerious** [comment]
Column width is preserved unless you shut down KeePassXC forcefully perhaps. A clean Ctrl+Q definitely preserves the GUI state.

**Comment by droidmonkey** [comment]
the problem is just because **you** are seeing this issue doesn't mean it is an issue with KeePassXC. It could very well be that the local config file (stored in ~/.local/share/keepassxc) is not storing properly due to an environment issue on your end.

**Comment by bulgin** [comment]
The only config file I see is not in ~/.local/share/keepassxc but in ubuntu 18.04 in :~/.config/keepassxc.  I believe the issue is that bleachbit is overwriting that file, but bleachbit has not way (at least that I can find) to whitelist .dotted directories.

Thanks for the pointers.

**Comment by droidmonkey** [comment]
Yup if there is no config file in local share then that is the problem. Disable bleach bit and see if the problem goes away

**Comment by phoerious** [comment]
`.config/keepassxc` is in fact the correct location on Linux. But Bleachbit can be a problem anyway.

**Comment by deflock** [comment]
Can confirm this issue on windows 10. It preserves, but after _some_ reboots (or app restarts?) it restores column layout to default one. Portable version.

**Comment by droidmonkey** [comment]
Never experienced this issue. Most likely your "local" config file is being deleted or overwritten.

**Comment by deflock** [comment]
How this local config can be deleted if other local options (e.g. window geometry) are loaded correctly? 🤦‍♂️
Well, looks like I have to dig into the sources myself. Stay tuned. 😁

**Comment by deflock** [comment]
See https://github.com/keepassxreboot/keepassxc/issues/5435

**Comment by bulgin** [comment]
In Ubuntu 20.04 I can confirm that running bleachbit and whitelisting the keepassxc folder and the .ini file therein will not preserve column widths.

If you create the column width you want, close then open again column widths will be preserved.  Then run bleachbit while even whitelisting the keepassxc folder and .ini file, then when you restart keepassxc the column widths will not be preserved.  

Not running bleachbit is not an option so it's a choice between throwing away keepassxc or bleachbit.  

Take your choice.

**Comment by droidmonkey** [comment]
You obviously have not whitelisted the configuration file correctly. We also now offer a command line switch (--localconfig) and environment variable KPXC_CONFIG_LOCAL that let's you define where you want the ini file to be located.

https://keepassxc.org/docs/KeePassXC_UserGuide.html#_command_line_options

Take your choice.

**Comment by bulgin** [comment]
Thanks I'm on ubuntu 20.04 and looks like those commands are for windows.  anything similar for Ubuntu?  I see I can get it to work when I whitelist the keypassXC .cache files although don't know if that's safe as it appears to contain some encrypted data. . .

**Comment by droidmonkey** [comment]
There is nothing sensitive in the ini files. You need to use the appimage or snap if you want to use the latest version of keepassxc.
