### ISSUE TITLE
Monochrome light tray icon doesn't work

### ISSUE THREAD

**Issue by aalhitennf** [keepassxreboot/keepassxc#5090]
## Overview
Switching tray icon changes only to monochrome-dark, monochrome-light and colorful changes to same icon with green background.

## Steps to Reproduce
1. switch tray icon from settings to monochrome light

## Expected Behavior
1. icon should change to light icon

## Actual Behavior
 icon changes to colorful icon with green background

## Context
KeePassXC - Version 2.6.0
Revision: 0765954

Operating System: Arch Linux
Desktop Env: AwesomeWM
Windowing System: X11

**Comment by droidmonkey** [comment]
Works everywhere else, must be AwesomeWM

**Comment by aalhitennf** [comment]
Yes it stays wrong. Also noticed that monochrome dark is only a dark circe: https://i.imgur.com/rhw3Dfn.png

**Comment by phoerious** [comment]
I believe you are running qt5ct as your platform theme. Unset QT_QPA_PLATFORMTHEME. See #4963.
