### ISSUE TITLE
Unhide passwords column permanently

### ISSUE THREAD

**Issue by Korezze** [keepassxreboot/keepassxc#5091]
When I untick "Hide passwords", I noticed that my choice is cancelled after closing/opening database. It will really nice if KeepassXC respected my choice by offering a permanent option. I understand that the current functioning can be considered as a choice of security but I would prefer to be free of my own decision on this subject.
Thanks.

**Comment by phoerious** [comment]
The state of this toggle is not persisted to the settings file. Even though that almost looks like a bug, I am pretty sure it is intended.

**Comment by droidmonkey** [comment]
Intentional until this is moved to the view menu. This is a duplicate
