### ISSUE TITLE
Go back to old icons

### ISSUE THREAD

**Issue by pxeger** [keepassxreboot/keepassxc#5092]
## Overview
The new interface is pretty neat, but it doesn't match my system's theming. I much prefer my native, customisable KDE/Qt styling, and while I can go back to the "classic" UI, I can't get the previous icons back. The new icons aren't too bad, but importantly they are coloured and not monochrome! This makes it look terrible because they don't match anything else. Please provide a way to get the old ones back. (Personally I think the icons shouldn't have been changed in the first place, there was absolutely nothing wrong with the old ones. But they absolutely shouldn't be in colour!)

![image](https://user-images.githubusercontent.com/67427173/87557581-fb8b2c80-c6af-11ea-9b43-4c9434296b02.png)

## Steps to Reproduce
1. Open the app

## Expected Behavior
It looks good in any theme because white and black go with anything

## Actual Behavior
It looks bad because yellow doesn't look good on anything except pure grey/black

## Context
KeePassXC - 2.6.0
Revision: 0765954

Operating System: Arch Linux
Desktop Env: KDE
Windowing System: X11

**Comment by phoerious** [comment]
I am not sure what you are talking about. The toolbar icons ARE monochrome and the group and entry icons have always been in colour. And yes, there were plenty of things wrong with the previous icons, such as that they were limited to 16x16px and the toolbar icons didn't match their intended meaning. There is no way we are going back to the old icons.

**Comment by pxeger** [comment]
*eats words*
