### ISSUE TITLE
Search bar disappeared

### ISSUE THREAD

**Issue by Anagastes** [keepassxreboot/keepassxc#5095]
## Overview

Search bar disappeared

In the new design of keepassxc there is no search bar anymore. Also CTRL+F no longer works.

As soon as the design is set to "Native", the search bar is back.

## Steps to Reproduce
Set the theme to Auto, Light or Dark and the search bar disappears.

## Expected Behavior
The search bar should always be there as well as the search function.

## Actual Behavior
The search bar and the search function disappear.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.0
Revision: 0765954

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux/Manjaro-Stable
Desktop Env: KDE
Windowing System: X11

**Comment by varjolintu** [comment]
Resize the window?

**Comment by Anagastes** [comment]
> Resize the window?

Didnt work.

Nativ-Theme with searchbar ![Screenshot_20200715_173900](https://user-images.githubusercontent.com/17494592/87575353-166d9900-c6d0-11ea-85fc-e17733d97bec.png)


New-Theme without searchbar ![Screenshot_20200715_173927](https://user-images.githubusercontent.com/17494592/87575359-18375c80-c6d0-11ea-9c9b-763ad9f19a78.png)

**Comment by phoerious** [comment]
Yeah, turn off text besides icons in the settings.

**Comment by Anagastes** [comment]
> Yeah, turn off text besides icons in the settings. I don't understand why that thing keeps enabling for some folks.

Sorry, I didn't realize it was active. The native design didn't have that by default. Now it works.

**Comment by phoerious** [comment]
Do you have any idea why it might switch? It doesn't make sense that it's enabled in the first place, but theme switching definitely shouldn't trigger it.

**Comment by Anagastes** [comment]
> Do you have any idea why it might switch? It doesn't make sense that it's enabled in the first place, but theme switching definitely shouldn't trigger it.

I'm afraid not. It could have to do with version jumps. My KeeepassXC has been in use since version 2.4.X and has only ever been updated.

It is possible that old settings caused a collision.

**Comment by tgreve15** [comment]
I also had a problem finding the search bar with the theme set to automatic (came up dark considering time). Took me a while to realize I had to maximize the window to find that. With the dark theme the two arrows indicating there are more toolbar items is not visible unless you know it's there and look VERY closely. Ctrl+F didn't show anything and there was nothing in the menus. I even looked at the User Guide to try to find out how to search. It would be ideal I suppose if you press Ctrl+F if the search field isn't visible that it also triggers the ">>" button to show the additional toolbar items not visible. If nothing else, perhaps an entry in your FAQ about finding the search bar?
![image](https://user-images.githubusercontent.com/15937202/87771077-36819180-c863-11ea-83e8-5627ee587bca.png)

**Comment by phoerious** [comment]
Disable text below icons.

**Comment by tgreve15** [comment]
I understand, but as a regular/newer user, how am I supposed to know I need to do that to find the search field? Besides which, showing text is a valid setting for the app, so do I need to choose between having it on or seeing the search bar?

**Comment by phoerious** [comment]
Did you enable that yourself? I feel like there are cases where this setting activates itself and people just assume that's what it's supposed to look like.

**Comment by tgreve15** [comment]
I don't recall. I installed it a while ago and have been still using KeePass. I just updated it today when opening a KeePass file and realizing it was associated with XC. I am quite sure the theme was new as I don't recall it being dark previously.

**Comment by phoerious** [comment]
No, I meant the text below your toolbar icons.

**Comment by georgeowell** [comment]
I also had this problem as I prefer text below icons. The old search hotkey "Ctrl+f" also didn't work either with the search bar not visible. This is a UX bug really as you're left in a sticky position with hundreds of passwords and no way to search :smile: 

Could the search bar be moved so that it's not affected by this text below icons setting?

**Comment by droidmonkey** [comment]
There is an issue tracking showing search bar if not visible.

**Comment by georgeowell** [comment]
> There is an issue tracking showing search bar if not visible.

Where is that issue @droidmonkey ?

**Comment by droidmonkey** [comment]
#505
