### ISSUE TITLE
Cannot save database changes or new databases on 2.6.0

### ISSUE THREAD

**Issue by phila85** [keepassxreboot/keepassxc#5097]
## Overview
I am able to open my password database and can add new entries, but when I attempt to save with the changes, I receive a message "Writing the database failed: Destination file exists". When I close and reopen the password database, the added entries are not there. If I try to save the modified database under a different name, I get the same error message, and no new database is saved. I tried unchecking the safe save option, but this did not solve the problem. I did not run into this behavior before the update to 2.6.0. 

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Open database
2. Click 'add new entry' and input information
3. Click OK --> results in error message above

## Expected Behavior
Adding new entry does not produce error message and new entry is saved

## Actual Behavior
When I click 'OK' to close a new entry, I receive an error message "Writing the database failed: Destination file exists". The new entry is still visible in the list of entries. If I attempt to database --> save database or database --> save database as, I get the same error message. If I close the database and then re-open it, the new entry is gone. Problem persists after restarting my computer several times. 

## Context
[NOTE]: # KeePassXC was recently updated from the previous version. I did not have this problem with the previous version.

[NOTE]: # 
KeePassXC - Version 2.6.0
Revision: 0765954
Distribution: Snap

Qt 5.9.5
Debugging mode is disabled.

Operating system: Ubuntu Core 18
CPU architecture: x86_64
Kernel: linux 4.15.0-107-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.1

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: Unity
Windowing System: X11

**Comment by droidmonkey** [comment]
Where are you trying to save to?

**Comment by phila85** [comment]
Trying to save to local directory/database.kdbx

**Comment by droidmonkey** [comment]
Do you have write permissions? This could be a snap issue. Try our appimage to confirm.

**Comment by phila85** [comment]
I had write permission for the database file, but was still unable to save new information to it. I solved the problem simply by removing then reinstalling the snap package and am now not having any problems with saving databases.

**Comment by bzhr** [comment]
I'm having this issue after updating from Ubuntu 18.04 to 20.04

**Comment by arthureroberer** [comment]
same

**Comment by Bevor** [comment]
On Ubuntu, this is because it points to the wrong instance. Obviously there was an update via Snap but the dialog still wants to open the old database. So point to the correct Password.kdbx (probably /home/[YOURUSER]/snap/keepassxc/[NUMBER]/Passwords.kdbx) when the login dialog appears and it will work.

**Comment by TimFH** [comment]
I've had this problem now for at least the past year, and keep having to copy the /tmp file to save my database, which is a real PITA. I was hoping this would've been fixed long ago, but it seems that despite a steady litany of complaints here, the developers are blissfully unaware that anything is wrong. Meanwhile, no donations from me!

For what it's worth, I'm using the flatpak version on the latest version of Ubuntu.

**Comment by droidmonkey** [comment]
@TimFH your post offers no way to assist you. All I can glean from it is you are using the alternative save pattern to write to a temporary directory and move into place. Perhaps try going back to the default save pattern or use the direct write method. Without any further information it is impossible to solve your very specific circumstance.

**Comment by TimFH** [comment]
Thank you for the unexpectedly rapid reply.

I'm afraid I don't know what a "save pattern" is, but I'm pretty sure I never mucked with it, and certainly not intentionally.

It seems that when the program fails to overwrite an existing database (including the one that's open, which is what it's doing), it writes it instead to a file with a random name in /tmp, and gives me about 10 seconds to copy it manually from a terminal window before it deletes it. But certainly never asked it to do that!

Hope that helps. If there's an environment variable I can set to generate detailed debugging output, be glad to oblige.

-- Tim

⁣Get TypeApp for Android ​

**Comment by droidmonkey** [comment]
We don't implement a 10 second window for anything related to saving. Recommend going to Tools -> Settings, then adjust your save file settings. See here for more info: https://keepassxc.org/docs/KeePassXC_UserGuide#_advanced_save_options
