### ISSUE TITLE
Status of special characters button in password generator is not persisted

### ISSUE THREAD

**Issue by Frederick888** [keepassxreboot/keepassxc#5098]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

Status of special characters button in password generator is not persisted. It can only be correctly persisted by opening Advanced and turning on/off all sub-groups of special characters.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Open password generator
0. Click Advanced button to reveal the sub-groups
0. Turn on all special character sub-groups
0. Click Advanced button to hide the sub-groups
0. Click Special Character button to disable it
0. Click Close
0. Open password generator again

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Special Characters button remains greyed out.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Special Characters button is highlighted, though the password generated contains no special characters.

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.0
Revision: 0765954

Qt 5.15.0
Debugging mode is disabled.

Operating system: macOS 10.15
CPU architecture: x86_64
Kernel: darwin 19.5.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
 libgcrypt 1.8.5

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS

**Comment by droidmonkey** [comment]
Good catch. We really need to persist advanced mode and simple mode independently. We kind of do, but when we load the settings we do not respect advanced vs simple.

**Comment by joshualibrarian** [comment]
In addition to these settings persisting, it would be really nice if each entry persisted generator settings, as these requirements vary a lot across sites and some have particularly finicky requirements.  This would make updating your password easier and compliment the "expires" functionality.  Is this even possible with the database format?

**Comment by droidmonkey** [comment]
Search for the issue called "password profiles"
