### ISSUE TITLE
(Context)-Menu Unresponsive Sometimes

### ISSUE THREAD

**Issue by tonobo** [keepassxreboot/keepassxc#5099]
## Overview
The Menu-Buttons such as "Database" or Table-Header in entry list is sometimes loosing the responsiveness. They become un-clickable after some time. This isn't a newly introduced bug i think. I'm experiencing the issue since months.

## Steps to Reproduce
I've know Idea how to reproduce.

## Expected Behavior
To keep the context buttons clickable.

## Actual Behavior
Context-Menu not working after some time. Entries are keeping clickable and the OK / Apply and Cancel Buttons also keeps working. Restarting Keepass fixes the issue.

```
KeePassXC - Version 2.6.0
Revision: 0765954

Qt 5.14.2
Debugging mode is disabled.

Operating system: Debian GNU/Linux bullseye/sid
CPU architecture: x86_64
Kernel: linux 5.7.0-1-amd64

Enabled extensions:
- Auto-Type  // not used
- Browser Integration
- SSH Agent
- KeeShare (only unsigned sharing) // not used
- YubiKey
- Secret Service Integration // not used

Cryptographic libraries:
 libgcrypt 1.8.5

Desktop Env: i3
Windowing System: X11
```

**Comment by tonobo** [comment]
I've talked to my Coworkers. @joconcepts is experiencing exactly the same issue on the latest Fedora (same Qt version) and others which are running different distros (Ubuntu & Fedora) with KDE are not noticing any issues.

Do you have any Idea where the Issue might come from?

**Comment by droidmonkey** [comment]
Most likely a Qt bug
