### ISSUE TITLE
Yubikey on Mac not being detected (v2.6.0)

### ISSUE THREAD

**Issue by Bertrand256** [keepassxreboot/keepassxc#5100]
## Overview
All versions above 2.5.3 have problems with detecting Yubikey on Mac.

## Steps to Reproduce
1. Plug-in Youbikey and open the app 
2. Click <Refresh> on the right of the "Hardware key"
3. "No hardware keys detected" is displayed.

## Expected Behavior
I should see an entry in the "Hardware key" list related to the Yubikey plugged-in to the computer, just like v2.5.3 does.

## Actual Behavior
The latest Mac version of the app doesn't detect Yubikey anymore.

## Context
Windows 10 version with the same Yubikey (but on another computer) works well - it detects Youbikey without any problems.

KeePassXC - Version 2.6.0
Revision: 0765954

Qt 5.15.0
Debugging mode is disabled.

Operating system: macOS 10.15
CPU architecture: x86_64
Kernel: darwin 19.5.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
 libgcrypt 1.8.5

Operating System: macOS

**Comment by phoerious** [comment]
You may need to restart your Mac in order to be able to activate the needed permissions.

**Comment by Bertrand256** [comment]
Yes, that was it! Actually, os didn't ask me for new permission, so I had to add it manually, but that was the problem. Thanks for the hint.
