### ISSUE TITLE
Appimage 2.6.0 User Guide

### ISSUE THREAD

**Issue by N3tFX** [keepassxreboot/keepassxc#5102]
## Overview
In the Appimage version of KeePassXC the User Guide is not complete.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1.  Using the Appimage v2.6.0 just click: "Help>User Guide".

## Expected Behavior
The local copy of the User Guide should be complete **_or_** the Menu should point to the online version.

## Actual Behavior
In the Appimage version of KeePassXC the User Guide is not complete. It only shows for its Table of Contents, "License and Disclaimers" and "Contact Us". In the online versions of the **"Getting Started Guide"** [https://staging.keepassxc.org/docs/KeePassXC_GettingStarted.html](url) and **"User Guide"** [https://staging.keepassxc.org/docs/KeePassXC_UserGuide.html](url), the documentation is complete.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Appimage 2.6.0

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux

**Comment by droidmonkey** [comment]
Known issue with older version of asciidoctor. Just use the online docs for now.
