### ISSUE TITLE
Password Health Check includes duplicate counts of Password Backups

### ISSUE THREAD

**Issue by stefan123t** [keepassxreboot/keepassxc#5103]
## Overview
I have multiple Backups of Credentials/Passwords in my Database, I believe they were created automatically under /root/Backup in the past using Keepass 1.x.
Now when I run a Password Health Check the Backup copies are counted towards the repetition count of my password.

## Steps to Reproduce
1. Create a password
2. Configure KeepassXC to create Backup of Passwords under /root/Backup
3. Change Credential Details, but keep Password, ie. add some notes or some other information like URL 
4. Save Database
5. Check Password Health Check

## Expected Behavior
Either Backups under /root/Backup should be excluded from Password Health Check or only be included as an option.

## Actual Behavior
6. Your two entries /root/Backup/Password and /root/Password are counted as two occurences of the same password

## Context
I have been converting my Database from Keepass 1.x to Keepass 2.x and since that changed to using XKeepass and now KeepassXC. Thanks for your work on Keepass it looks great!

KeePassXC - Version 2.6.0
Revision: 0765954

Qt 5.9.5
Debugging mode is disabled.

Operating system: Linux Mint 19.3
CPU architecture: x86_64
Kernel: linux 5.3.0-62-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.1

Operating System: Linux Mint 19.3 (sometimes iOS 13 / seldom Windows 10)
Desktop Env: Cinnamon
Windowing System: X11

**Comment by droidmonkey** [comment]
Are you referring to entry clones using references?

**Comment by stefan123t** [comment]
@droidmonkey thanks for the answer. No I haven't checked the entry clones using references yet, though this would probably be another interesting statistical oddity.

This is for Backups, any time I change a password or anything else of an entry KeepassXC creates a copy of the old entry under /root/Backup.

**Comment by droidmonkey** [comment]
We have no such feature, now I'm confused

**Comment by stefan123t** [comment]
The last modified entry under Backups is from 16 Jul 2020 12:33:55 and I am using KeepassXC since a couple of months if not more than 1 or 2 years now.
Keepass DB is KDBX3.1 version. Maybe some old function in the Database file ?

**Comment by stefan123t** [comment]
But apart from the last two entries under /root/Backup from this year, all others date to 2016 and earlier. Maybe the duplicates are from an earlier version of XKeepass or Keepass 2.x / 1.x which I have used in the past.

**Comment by stefan123t** [comment]
I probably will need to purge the Backup folder and rely on the newer History feature of KeepassXC.
