### ISSUE TITLE
Auto Type Selected Shortcut

### ISSUE THREAD

**Issue by GautamMKGarg** [keepassxreboot/keepassxc#5104]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
In windows version of keepass 2.45 downloaded from https://keepass.info/download.html is having option to Auto Type Selected entry. But linux version of keepassxc is not having that option. keepassxc there is option of "Global Auto Type Shortcut", but whenever I try to use this, it always gives error "Couldn't find an entry that matches the window title". Keepassxc never work with this option. On the other hand in keepass 2.45, if I select the entry and use shortcurt to auto type selected entry, it works. Please me know if you need more information.

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )

**Comment by droidmonkey** [comment]
Read our documentation

**Comment by GautamMKGarg** [comment]
I have already checked all the documentation, but I could not find this feature in keepassxc. As I mentioned, in keepassxc there is option of "Global Auto Type Shortcut" but there is no option to "Auto Type select entry" using shortcode without opening keepass app.
Yes, there is option to directly press Ctrl + Shift + V and the select entry will auto type, but this option only work if keepassxc window is active. I am talking about the option to auto type selected entry even if keepassxc window is minimized.

**Comment by droidmonkey** [comment]
That is what global auto type is for.

**Comment by GautamMKGarg** [comment]
As I mentioned, this feature is there in windows version of keepass.
https://keepass.info/download.html
