### ISSUE TITLE
More plugins architecture

### ISSUE THREAD

**Issue by smerdysmerdy** [keepassxreboot/keepassxc#5110]
I would like to see KeepassXC more plugin based architecture then I can remove features completely

Things that are candidates for plugins (and you can still ship these as standard, just implemented as a plugin)

Password generator
Freedesktop.org Secret Service Agent (and any other external management service integration features)
Auto-type

Anything around the core features of managing account entries can be implemented as a plugin, then we have 1) modularity and 2) replacability and removability, everybody is happy

I really want to have this so I can remove the things I consider a risk and don't like, and people whom do use them can still have them (you can install them by default if you wish and I can remove them post-installation)

If you look at the likes of many "environment" apps like Android Studio and VSCode etc, they are heavy on plugin architectures for features, and I think KeepassXC should be the same way, it is an account mangement environment and features around it, as plugins.

Right now I have only one choice, recompile your code with the features I do not want, coded out, and that is just absolutely a TERRIBLE architecture

**Comment by phoerious** [comment]
This is not going to be implemented. We add the features we deem important and we integrate them well. We do not want the wild-wild-west of plugins that KeePass2 is.

**Comment by smerdysmerdy** [comment]
You can ship them as standard, I just want to remove the fucking things

**Comment by phoerious** [comment]
Maybe you need to use a different software then. Auto-Type is a core component of KeePassXC. In fact, Auto-Type specifically IS already a separate dynamic library, but we are not going to expand that to a general plugin system. If you don't want a feature, don't use it.

**Comment by droidmonkey** [comment]
FWIW, auto-type is a built in feature of KeePass2 that is you cannot explicitly disable from code. Soooo.... Enjoy your mono?

**Comment by phoerious** [comment]
Yeah, let alone the 167k lines of C# code that KeePass2 is without any plugins. We have 185k lines of CPP files including ALL features for ALL platforms of which a large portion isn't even compiled on any specific platforms and it runs  faster by than KeePass2 by a magnitude. Very bloated.
