### ISSUE TITLE
Documentation: Open kdbx:// URLs with UNC Paths on Windows

### ISSUE THREAD

**Issue by Netzvamp** [keepassxreboot/keepassxc#5112]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
This is not really a bug but a request to add this to the documentation. This is a windows only behavior.

KeepassXC 2.6 has this new nice feature to open another database with an URL like "kdbx://C:/path/to/database.kdbx". On first look this doesn't work for UNC-Paths, cause "kdbx://fileserver/share/database.kdbx" just trows an error. 

You have to give the URL field two "protocols" to get this done: "kdbx://file://fileserver/share/database.kdbx" works. 

I don't think this need to be improved, but documented. Maybe someone will find this, if it doesn't get added to official documentation, so i think this report is usefull.

**Comment by droidmonkey** [comment]
This is standard practice

**Comment by Netzvamp** [comment]
> This is standard practice

Look trivial, i know. But it took me some minutes and i think some users could get stuck with that. The whole kdbx url thing isn't in the documentation, it's such a nice feature. I've just waited for exactly this, to migrate from keepass to keepassXC.

**Comment by droidmonkey** [comment]
I need to document that and AutoOpen

**Comment by Netzvamp** [comment]
> I need to document that and AutoOpen

Thank you for your work! I really like the new version :)
