### ISSUE TITLE
KeePassXC not minimized when launched at system startup

### ISSUE THREAD

**Issue by 0ecd3e** [keepassxreboot/keepassxc#5113]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
KeePassXC is not staying minimized to tray on system startup. Once it loads, the window will show in the foreground prompting the user to unlock the database. KeePassXC is minimized when launched from a shortcut, such as the Start menu entry.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Enable "Automatically launch KeePassXC at system startup"
2. Enable "Minimize window at application startup"
3. Reboot system

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
KeePassXC will launch at startup, but stay minimized in the system tray. This was the behaviour for all versions up to but excluding 2.6.0.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
KeePassXC launches and displays its window in the foreground, and is not minimized. Launching KeePassXC from the Start menu or a shortcut will keep the program minimized to tray as expected.

## Context
[NOTE]: # ( Give us any additional information you may have. )
My settings have not changed since I updated from the previous 2.5.x version of KeePassXC. This feature has always worked perfectly.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.6.0
Revision: 0765954

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 10 1909 (x64)

**Comment by droidmonkey** [comment]
You have it both in your startup folder and enabled to start in your registry. Remove the shortcut from your startup folder.

**Comment by 0ecd3e** [comment]
This is not correct. KeePassXC was not in my startup folder, and never has been. 
**The fix is, unintuitively, disabling the KeePassXC startup entry through Task Manager.** 
Considering reviewing the update installer and how it adds startup entries.

**Comment by droidmonkey** [comment]
We add it per system standards

**Comment by 0ecd3e** [comment]
Obviously something has changed in this behaviour between 2.6.0 and 2.5.x (and previous versions, I have used KeePassXC for 2 years with zero issues). Otherwise, this issue wouldn't have popped up at all. It might not have been intentional, but a change is present. Even if it is low priority, bugs like these detract from what is otherwise a very polished piece of software.

**Comment by droidmonkey** [comment]
Did you setup keepassxc to startup on login before 2.6.0? If so, that means you most likely had it starting twice after you upgraded. The second startup causes the program to gain focus because of single instance.

**Comment by 0ecd3e** [comment]
**Previous installations of KeePassXC may have used a Task Scheduler entry to start up the program on boot. I did some digging and found a task created in 2018 which does this. Disabling this task should fix it.**

Yes, as noted in my report from above my KeePassXC has been configured to start on login for the past 2 years. The only way I have set it to start on login is to tick the box in the KeePassXC settings page. I have reviewed #5061 and **I did not manually add any start up entries anywhere because I have never needed to. Just ticking and unticking the box in the settings worked to change the setting.** I suppose ticking that box in the past would have created the task, and unticking it would have disabled it.

KeePassXC 2.5.x and below never had a startup entry in Task Manager for me, which is why it was working fine until now as it was only being launched by Task Scheduler.

The current behaviour of adding a registry entry in Task Manager when the auto start is enabled, and removing it when it is disabled is the expected behaviour. It would be best to leave a notice in the changelog or FAQ somewhere indicating the change in how the startup entry is made in the upgrade to 2.6.0, and possible fixes if this is encountered again.

**Comment by droidmonkey** [comment]
We never had a task scheduler entry, where did you pull that from?

**Comment by 0ecd3e** [comment]
Wait a minute. How is 2.6.0 the first one that can start on login? I've used this feature for years because it was there. Task Scheduler entry I found by manually searching through my Task Scheduler list. 
I did not manually make this task, everything just worked when I first installed KeePassXC that time two years ago. All updates up to and including 2.5.4 have come and gone flawlessly.

**Comment by phoerious** [comment]
We have never had such a feature.

**Comment by 0ecd3e** [comment]
Then what was the "start automatically on login" box doing for all these years? I do not remember that part of the interface changing.

**Comment by droidmonkey** [comment]
That setting only ever appeared in 2.6.0.

**Comment by 0ecd3e** [comment]
Interesting, so it was never there. I just checked 2.5.4 on my Linux machine.
My suggestion now is to make this evident in the changelog, as it stands it doesn't have enough emphasis. It could use some bold font, along with a link to this issue or #5061 in case someone else runs into what I or they have.

**Comment by 0ecd3e** [comment]
Thanks for being responsive and helping me figure this out.
