### ISSUE TITLE
Toggle password visibility shortcut conflicts with system shortcut on macOS

### ISSUE THREAD

**Issue by ian-h-chamberlain** [keepassxreboot/keepassxc#5114]
## Overview
With KeePassXC 2.6.0, there is a new shortcut to toggle password visibility when entering a master password (`ctrl+H` on other platforms, `cmd+H` on macOS).

Unfortunately, cmd+h is a macOS system shortcut to hide the current application, so this appears to take precedence over the KeePassXC shortcut.

![Screen Shot 2020-07-17 at 11 05 44](https://user-images.githubusercontent.com/11131775/87805341-2649c200-c823-11ea-8e08-2f6f6e40568a.png)
![Screen Shot 2020-07-17 at 11 06 51](https://user-images.githubusercontent.com/11131775/87805345-26e25880-c823-11ea-93d0-cbc87c40de42.png)

There is a workaround for this in the meantime: users can change the default `Hide KeePassXC` shortcut using System Preferences to something else to avoid the conflict:
![Screen Shot 2020-07-17 at 11 45 05](https://user-images.githubusercontent.com/11131775/87805273-103c0180-c823-11ea-9e3c-a7752d6f1fc4.png)
At this point, the `cmd + H` shortcut works as expected. I don't think this is optimal, since some users probably want to hide KeePassXC using `cmd + H` the same way they would normally do for other applications.

## Steps to Reproduce
1. Attempt to open a database
2. With password field focused, type `cmd + H` 

## Expected Behavior
I am not sure if it is possible to override the builtin macOS shortcut from the app
I would suggest either using a different default shortcut (perhaps `ctrl + cmd + H` or `cmd + shift + H`?) on macOS only, since `cmd + H` (and `cmd + option + H`) is normally a system-wide shortcut and most users probably expect this to behave the same way in all applications.

Alternatively, the user could be given the ability to customize this shortcut in KeePass settings.

## Actual Behavior
The app is hidden instead of toggling password visibility.

## Context
KeePassXC - Version 2.6.0
Revision: 0765954

Qt 5.15.0
Debugging mode is disabled.

Operating system: macOS 10.15
CPU architecture: x86_64
Kernel: darwin 19.5.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
 libgcrypt 1.8.5

**Comment by droidmonkey** [comment]
Forcing the keyboard shortcut to be Ctrl + H on macOS would solve this. Qt auto converts Ctrl to Cmd and is sometimes annoyingly broken.
