### ISSUE TITLE
Unable to connect to keepassxc-browser after update 2.6.0

### ISSUE THREAD

**Issue by Toemmel** [keepassxreboot/keepassxc#5117]
## Overview
since update to 2.6.0 no connection to the browser plugin possible.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. 
2. 
3. 

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - unknown
KeePassXC-Browser - 1.6.6
Operating system: Linux x86_64
Browser: Chrome/Chromium 84.0.4147.89

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env:  Mint 19

**Comment by varjolintu** [comment]
Make sure your browser is not installed via Snap. Otherwise please read the [Troubleshooting guide](https://github.com/keepassxreboot/keepassxc-browser/wiki/Troubleshooting-guide) and report your findings.

**Comment by Toemmel** [comment]
i get this error after trying to start keepassxc-proxy manually:

_./keepassxc-proxy: /usr/lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5.14' not found (required by ./keepassxc-proxy)_

dont know if this is the problem...
to be honest, i have changed nothing to the system. Just updated keepassXC to 2.6.0

**Comment by varjolintu** [comment]
Well that is clearly the problem. Do you have some other version of Qt libraries installed? Have you tried the official AppImage instead?

**Comment by Toemmel** [comment]
following versions installed:
![image](https://user-images.githubusercontent.com/68441774/87823781-58374480-c874-11ea-9f6e-b0b1ce55fe57.png)

official appimage - you mean to install keepassXC new?

**Comment by droidmonkey** [comment]
You have Qt 5.9.5 installed but keepassxc is looking for Qt 5.14. You have a package management problem going on. Are you using the PPA?

**Comment by Toemmel** [comment]
dont ask me such things, PPA what?
Actually i am a linux beginner...i only use that:
![image](https://user-images.githubusercontent.com/68441774/87825090-c2e97f80-c876-11ea-9cb7-4e16a32d9ec6.png)

**Comment by Toemmel** [comment]
> You have Qt 5.9.5 installed but keepassxc is looking for Qt 5.14. You have a package management problem going on. Are you using the PPA?

Do you mean this?
![image](https://user-images.githubusercontent.com/68441774/87826703-a569e500-c879-11ea-9b77-f2bce05c707f.png)

**Comment by droidmonkey** [comment]
Perhaps, who the heck is jtaylor? Install from our downloads page or using phoerious' PPA (listed on downloads page)

**Comment by droidmonkey** [comment]
Get rid of that PPA

**Comment by Toemmel** [comment]
Thanks a lot for your support droidmonkey - its working now
