### ISSUE TITLE
Minimize when copying to clipboard is not working

### ISSUE THREAD

**Issue by elopio** [keepassxreboot/keepassxc#512]
I can copy and paste my passwords if the `Minimize when copying to clipboard` option is not selected. But when I select it, copy and paste doesn't work.

## Expected Behavior

After entering `Ctrl+c` in a selected password entry, the keepassxc window is minimized. Then after entering `Ctrl+p`, the password is pasted.

## Current Behavior

The window is minimized but the password is not in the clipboard, so `Ctrl+p` does nothing.

This is logged in syslog:

`Apr 18 18:03:26 calchas org.gnome.Shell.desktop[2254]: QXcbClipboard: Cannot transfer data, no data available`

## Steps to Reproduce

1. Go to Tools>Settings.
2. Check the `Minimize when copying to clipboard` option.
3. Click the `Ok` button.
4. Open your database.
5. Select an entry.
6. Enter `Ctrl+c`.
7. Click a text field.
8. Enter `Ctrl+p`.

## Your Environment
Ubuntu Gnome 17.04, with all the defaults.
keepassxc installed from the snap:
tracking:    stable
installed:   2.1.4 (8) 72MB -

**Comment by secondwtq** [comment]
OS X 10.9.5 with KeePassXC 2.1.4 here, also not working.

**Comment by erpalma** [comment]
Same here on Gentoo with KeePassXC@master, Qt 5.7.1

**Comment by TheZ3ro** [comment]
@erpalma can you try with the `develop` branch?

**Comment by droidmonkey** [comment]
Please try to reproduce in the 2.2.0 release.

**Comment by erpalma** [comment]
Ok found the problem: when "lock database after minimizing" is active, if I copy username/password to the clipboard the main window is minimized and locked (probably) before the copy operation.

**Comment by droidmonkey** [comment]
Seems like a bug. Can you open a new ticket with this issue please.
