### ISSUE TITLE
Option to disable entry details

### ISSUE THREAD

**Issue by Germano0** [keepassxreboot/keepassxc#5120]
Can you please add an option to permanently disable this frame that shows entry details?

![keepassxc](https://user-images.githubusercontent.com/5477747/87852634-f1fa0280-c903-11ea-8e95-f5715ad7abe6.jpg)

**Comment by droidmonkey** [comment]
View -> 
![image](https://user-images.githubusercontent.com/2809491/87852856-9e6fc080-c8d3-11ea-9b9c-c1292a260074.png)
