### ISSUE TITLE
YubiKey cannot be found after 2.6 refraction [#4584, #4843]

### ISSUE THREAD

**Issue by Zocker1999NET** [keepassxreboot/keepassxc#5125]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
KeePassXC 2.6.0 cannot find my YubiKey, meaning I cannot unlock my database with the new version. The old version is not affected.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Insert YubiKey
2. Launch KeePassXC
3. Select my YubiKey on Hardware Keys drop down

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Find YubiKey and show in drop down menu, like before 2.6, see:
![image](https://user-images.githubusercontent.com/1645646/87855552-72772e00-c919-11ea-8103-c550c7c143e4.png)

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
![image](https://user-images.githubusercontent.com/1645646/87855573-920e5680-c919-11ea-8ed2-9c71f1db9007.png)
But the YubiKey does light up when I launch KeePassXC or try to refresh the list like before.

## Context
[NOTE]: # ( Give us any additional information you may have. )
I'm running Debian Testing/Unstable on amd64. KeePassXC 2.6.0 installed from the Debian repository does show the same wrong behavior. 2.5.4 as AppImage or installed from the repository do both detect my YubiKey.

It could be that this issue was not found during test because I installed the challenge-response key on slot 2 instead of slot 1, but I cannot test this assumption on my own.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.0
Revision: 0765954
Distribution: AppImage

Qt 5.14.2
Debugging mode is disabled.

Operating system: Debian GNU/Linux bullseye/sid
CPU architecture: x86_64
Kernel: linux 5.7.0-1-amd64

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.1

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: KDE
Windowing System: X11

**Comment by droidmonkey** [comment]
This is already fixed for the next release.
