### ISSUE TITLE
Regression: opening KeePassXC on MacOS very slow

### ISSUE THREAD

**Issue by edensg** [keepassxreboot/keepassxc#5126]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
KeePassXC 2.6.0 takes a long time to start up on MacOS, compared to 2.5.x. Between launching the app and being able to interact with the app there's ~30s where the app appears to be frozen.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Open KeePassXC 2.6.0
2. Time KeePassXC's startup time

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
App is usable within a short period of time (on 2.5.x this was easily less than half a second).

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
App hangs for about 30s on startup (spinning beachball), before becoming usable. The app name appears without any other menu bar items in the menu bar during this time, and the normal menu bar items appear when the main window opens.

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.0
Revision: 0765954

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS 10.14.6 (18G5033)

**Comment by droidmonkey** [comment]
Not reproduced on test mac (10.15.5)

**Comment by iipamonkey** [comment]
I confirm startup in 2.6.0 is taking a a good 5+ seconds to start on two different MBPs on macOS 10.15.5. Startup in previous version was sub-second.

**Comment by droidmonkey** [comment]
There's nothing special about startup on Mac that I am aware of. If anything this is a Qt induced problem. Qt was updated in this deployment.

**Comment by iipamonkey** [comment]
Based on my observation about starting it directly vs. double-clicking an associated database file, I'm reminded that this would not be the first time macOS has some weird thing related to opening directly vs. alternative methods. In MKVToolnix on macOS, opening a file with Finder's "Open With" dialog results in MKVToolnix opening to an empty GUI without loading the opened file in question. No errors - just flatly ignores it.

**Comment by iipamonkey** [comment]
For what it's worth, 2.6.1 has pretty much eliminated this issue for me. There is only a slight delay now which is no longer noticeable as something odd.

**Comment by dclee9** [comment]
not sure why, it's running slow for me on keepassxc 2.7.9 running on oclp ventura 13.6.9 macbook pro 2015 on 1680 x 1050 resolution. 
------------------------
ok, i re-ran -OCLP patch, now it's fast. i'm guessing it's something to do with Mac Graphic driver, not keepassxc's problem or QT.

**Comment by geeeezmo** [comment]
> ## not sure why, it's running slow for me on keepassxc 2.7.9 running on oclp ventura 13.6.9 macbook pro 2015 on 1680 x 1050 resolution.
> 
> ok, i re-ran -OCLP patch, now it's fast. i'm guessing it's something to do with Mac Graphic driver, not keepassxc's problem or QT.

What's "-OCLP patch" and how do I run it?
On my M1 MBP it takes 20-30 seconds to start the app.
