### ISSUE TITLE
Snap helper script doesn't work on Fedora 

### ISSUE THREAD

**Issue by 1robo2020** [keepassxreboot/keepassxc#5127]
From site i could see that to enable integration with browser if i install KeepassCX 2.6.0 using snap i need download script https://raw.githubusercontent.com/keepassxreboot/keepassxc/master/utils/keepassxc-snap-helper.sh

So i download it and try run

sh keepassxc-snap-helper.sh

but nothing happen while script code ii guess should output some message.

When i check script code i could see that it's try use this path /snap/bin/keepassxc.proxy but i don't have such file (and actually even /span folder). I install snapd only actually but this look as enough to run span: dnf install snapd

System is Fedora 32 with latest kernel.  BTW. Fedora do not yet update KeepassCX and release version is still 2.5.4

KeePassXC - Version 2.6.0
Revision: 0765954
Distro: Snap
Operating System: Fedora 32 64 bit
Desktop Env: Gnome
Windowing System: Wayland

So as result i still cannot integrate KeepassXC with Firefox.

**Comment by droidmonkey** [comment]
use `bash ./keepassxc-snap-helper.sh`

**Comment by 1robo2020** [comment]
which keepassxc:
/var/lib/snapd/snap/bin/keepassxc

bash ./keepassxc-snap-helper.sh dit not gave me any output (BTW. should it return anything or command is silent? I just seen in code somehing like menu to select between browsers etc. ).

**Comment by 1robo2020** [comment]
Also, Firefox and plugin version: 
KeePassXC - unknown
KeePassXC-Browser - 1.6.6
Operating system: Linux x86_64
Browser: Mozilla Firefox 78.0

**Comment by droidmonkey** [comment]
You should at least get a menu of choices. It won't work anyway since Fedora stores snaps in a totally different folder.

**Comment by 1robo2020** [comment]
Ya, i found binary /var/lib/snapd/snap/keepassxc/978/usr/bin/keepassxc-proxy and i modify paths it still not working. Finally i removed snap installation and restore KeepassXC 2.5.4, it is work fine.
