### ISSUE TITLE
keepassxc crashes after downloading favicon

### ISSUE THREAD

**Issue by GentlyD** [keepassxreboot/keepassxc#5128]
Hi,

keepassxc crashes after downloading favicon. Error message is as attached. Anything I can do to resolve this?

Thanks so much,
Dirk

![Screen089](https://user-images.githubusercontent.com/52222791/87874233-72823700-c9c8-11ea-91ea-a2a70a1da84e.jpg)

**Comment by droidmonkey** [comment]
Probably a duplicate of #4966 or #2734
