### ISSUE TITLE
Ambiguous shortcut overload: Ctrl+N

### ISSUE THREAD

**Issue by yan12125** [keepassxreboot/keepassxc#513]
## Expected Behavior

Ctrl+N creates a new entry

## Current Behavior

There's a warning and nothing happens:
```
QAction::eventFilter: Ambiguous shortcut overload: Ctrl+N
```

## Possible Solution

At least "New Database" and "Add new entry" uses Ctrl+N. One of them should use another shortcut.

## Steps to Reproduce (for bugs)

1. Open an database
2. Hit Ctrl+N

## Your Environment

* KeePassXC version/commit used: (can be found under Help -> About) 70bd598ead950ae8be8ddcdf8f5eb1595033cc2a
* Qt version (e.g. Qt 5.3): 5.8.0
* Compiler (e.g. Clang++3.6.0): GCC 6.3.1
* Operating System and version: Arch Linux x86_64 up-to-date

**Comment by TheZ3ro** [comment]
We have discussed that "add new entry" should use CTRL+Shift+N, I think that wasn't change

**Comment by yan12125** [comment]
I found #316 and thus I guess you were meaning "New database". With that in mind, I opened #515

**Comment by TheZ3ro** [comment]
Ok, found the discussion at #289 

The current behaviour is a bug (my fault when reverting in #316), but since this will be fixed in 2.2.0 I would prefer having the feature from #289 discussion.

@yan12125 Can you work on it? It will be a little bit more complex

**Comment by yan12125** [comment]
Sorry I'm a little bit confused. Should I continue on #515? Or behavior based shortcut is the way to go?

**Comment by TheZ3ro** [comment]
You can continue with #515, I've requested some changes for that PR. Sorry for the confusion :smile:

**Comment by TheZ3ro** [comment]
Thanks for the PR @yan12125
