### ISSUE TITLE
allow changing advanced encryption settings of already created databases

### ISSUE THREAD

**Issue by deathtrip** [keepassxreboot/keepassxc#5131]
## Summary
Currently you can only change advanced encryption settings during database creation.
I'm talking about encryption algorithm, kdf iterations, used memory, threads etc.
These settings should be available in Database Settings -> Security -> Encryption Settings, as this tab is currently nearly empty, allowing to only change the database format and decryption time, with no fine-grained control.

## Context
Not being able to change the encryption algorithm and other settings can be a problem if you need to open the database in another application.

**Comment by droidmonkey** [comment]
Read the documentation please, shows you exactly what you need to know. Click the advanced settings checkbox in lower left.
