### ISSUE TITLE
Autotype hiding window stopped working with i3 wm

### ISSUE THREAD

**Issue by zli117** [keepassxreboot/keepassxc#5133]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Use i3 as the window manager
2. Use keepassxc 2.6.0
3. In Tools > Settings > General, select `Show a system tray icon` and `Hide window to system tray when minimized` as suggested here: https://github.com/keepassxreboot/keepassxc/issues/457#issuecomment-357475380 

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
After issuing autotype either from clicking the button or Ctrl-Shift-V, keepassxc should hide itself and type into the previous active window

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Instead of hiding the window, keepassxc types into itself

## Context
[NOTE]: # ( Give us any additional information you may have. )
It was working for version 2.5.4 and before. Also reproduced on Ubuntu 20.04 with i3 version 4.17.1, with the official app image downloaded from the website.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.6.0
i3wm - 4.18.1
qt - 5.15.0

[NOTE]: # ( Pick choices based on your environment )
Operating System: Arch Linux - 5.4.52-1-lts
Desktop Env: i3wm
Windowing System: X11

It seems to be broken on Ubuntu 20.04 with gnome (the default one) as well, when `Show a system tray icon` and `Hide window to system tray when minimized` are selected

**Comment by droidmonkey** [comment]
Duplicate issue, there is already one for auto type not minimizing with this setting enabled.

**Comment by zli117** [comment]
Upon some debugging, I think the offending code is here https://github.com/keepassxreboot/keepassxc/blob/develop/src/gui/MainWindow.cpp#L1154. The reason is that `hide()` will set visible to false, which later will cause `showMinimize()` to call `setVisible(true)` as here: https://code.woboq.org/qt5/qtbase/src/widgets/kernel/qwidget.cpp.html#_ZN7QWidget13showMinimizedEv

**Comment by droidmonkey** [comment]
Thanks already bisected it to that code, the fix will be interesting because we don't want to revert the change that caused the bug. This also only impacts Linux.

**Comment by zli117** [comment]
One way to fix I could think of is to create a signal called `hideOrMinimizeForAutoType` or something alike in `AutoType`, and wire it to `minimizeOrHide()` in `MainWindow`. Then replace [autotype](https://github.com/keepassxreboot/keepassxc/blob/develop/src/autotype/AutoType.cpp#L236) with the signal emit. This will also make the hide behavior consistent with others fixed in https://github.com/keepassxreboot/keepassxc/commit/b9daed20558103e3c8e799f3e0575522bf823df6.

**Comment by droidmonkey** [comment]
Not a bad idea!

**Comment by droidmonkey** [comment]
Implemented in upcoming patch: https://github.com/keepassxreboot/keepassxc/commit/30e9bb2c2820dafe3e521ebb919316b8ce32c6ac#diff-25d902c24283ab8cfbac54dfa101ad31

**Comment by zli117** [comment]
Cool! Thank you so much!
