### ISSUE TITLE
Reports: Average password length calculation is incorrect

### ISSUE THREAD

**Issue by simon816** [keepassxreboot/keepassxc#5134]
## Overview

The "Average password length" value shown in the database statistics is incorrect when there are multiple non-unique passwords.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Create a database with two entries using the same password: "test"
2. Open the statistics page

## Expected Behavior

Average password length is 4.

## Actual Behavior

The average password length is 8

## Context
KeePassXC - Version 2.6.0
Revision: 0765954

Qt 5.9.5
Debugging mode is disabled.

Operating system: Ubuntu 18.04.4 LTS
CPU architecture: x86_64
Kernel: linux 5.0.10-050010-generic

**Comment by simon816** [comment]
## Cause

https://github.com/keepassxreboot/keepassxc/blob/ff9dd432628d3261a5f21856d40a27a073e079c1/src/gui/reports/ReportsWidgetStatistics.cpp#L148

`pwdTotalLen` is added for every password

https://github.com/keepassxreboot/keepassxc/blob/ff9dd432628d3261a5f21856d40a27a073e079c1/src/gui/reports/ReportsWidgetStatistics.cpp#L61

However, the total is divided by the number of unique passwords. While we're here, this should probably round to the nearest int, rather than floor integer division.

**Comment by wolframroesler** [comment]
Seems like this is in my code so I'll fix it.
