### ISSUE TITLE
Auto-Type doesn't hide to system tray even though 'Hide window to system tray when minimized' is enabled [regression]

### ISSUE THREAD

**Issue by hugthecactus** [keepassxreboot/keepassxc#5135]
## Overview
When the option 'Hide window to system tray when minimized' is enabled, Auto-Type used to hide to system tray. Now it just minimizes the open window

## Steps to Reproduce
1. Enable 'Hide window to system tray when minimized'
2. Perform Auto-Type

## Expected Behavior
KeepassXC hides to system tray

## Actual Behavior
KeepassXC window minimizes but does not hide to system tray

## Context
It hides to tray correctly on copy of username/password (with 'Hide window when copying to clipboard > Minimize' enabled), just not on Auto-Type

KeePassXC - Version 2.6.0
Revision: 0765954

Qt 5.15.0
Debugging mode is disabled.

Operating system: Manjaro Linux
CPU architecture: x86_64
Kernel: linux 5.4.52-1-MANJARO
Desktop Env: XFCE
Windowing System: X11

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.6

**Comment by hugthecactus** [comment]
> Duplicate issue.

Apologies if that's the case. Are you referring to #4962 ? It seemed to describe different behaviour as Auto-Type types into the correct window for me. You'd know better if they're related though.

**Comment by droidmonkey** [comment]
The fix for that will fix your issue

**Comment by hugthecactus** [comment]
Great, thank you
