### ISSUE TITLE
Regression: Error when opening private ssh key

### ISSUE THREAD

**Issue by mircsicz** [keepassxreboot/keepassxc#5137]
I've all my SSH key's referenced to external files, so that they are loaded to the agent upon opening my database

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. open the database
2. ssh-add -l
3. 

## Expected Behavior
ssh-add -l shows my keys

## Actual Behavior
trying to save the entry that contains the reference to the external key give's me: "Fehler beim öffnen des privaten Schlüssels" which should translate to: Error when opening private ssh key

KeePassXC - 2.6.0 installed through brew cask
Operating System: 10.15.6

**Comment by hifi** [comment]
Can you give an example of what kind of path the key files have?
