### ISSUE TITLE
AppImage does not launch without sudo

### ISSUE THREAD

**Issue by tamirOK** [keepassxreboot/keepassxc#5138]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
When I run AppImage executable, I get following error:
```
Cannot open /proc/self/exe: Permission denied
Failed to get fs offset for /proc/self/exe
```
However it is working with sudo.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. `./KeePassXC-2.6.0-x86_64.AppImage`

KeePassXC - 2.6.0
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux Fedora 32
Desktop Env: Gnome
Windowing System: Wayland

**Comment by phoerious** [comment]
Your fusermount permissions are probably messed up. 

https://discourse.appimage.org/t/opensuse-leap-42-2-appimage-applications-will-not-run/197
https://bugzilla.suse.com/show_bug.cgi?id=1041159
