### ISSUE TITLE
Allow choosing the database to be unlocked when invoking auto-type and browser plugin

### ISSUE THREAD

**Issue by bb4242** [keepassxreboot/keepassxc#5141]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )

In keepassxc 2.6.0, both the auto-type and browser plugin features seem to use only the last opened database when presenting the user with the unlock screen.  It would be nice if you had the option to pick a different database to use in this screen.

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )

The main keepassxc window already has a nice tabbed UI that allows easy switching between different databases.  It would be nice if the unlock screen that pops up when you invoke auto-type or the browser plugin had the same tabs.  Then you could select the relevant database and unlock it.

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )

I have two keepassxc databases, a personal one and one for work.  I keep the databases locked except when I need to access them.  I frequently need to switch between them as I log into various sites throughout the day.  I really like the auto-type and browser plugin features.  But the current behavior makes it much less efficient to use these nice features, because if the last site I logged into used a different database than the one I need to use now, there's no way I can see to select the new database.  When that happens, the workflow usually goes like:

1) Try to use the browser plugin.
2) The unlock screen pops up, and I realize it's trying to unlock the wrong database.
3) Close the unlock screen.
4) Open the main keepassxc UI.
5) Click the tab for the right database and unlock it.
6) Use auto-type (which will now use the correct, unlocked database) to log in.

If the browser plugin/auto-type unlock screen had a tab per database, I think it could go like this instead:

1) Try to use the browser plugin.
2) Select the correct database and unlock it.  Done! :)

Thanks for making keepassxc, it's a great project!

**Comment by droidmonkey** [comment]
Duplicate request.

**Comment by bb4242** [comment]
Haha thanks @droidmonkey!  I tried to search for similar issues and couldn't find one either, apologies if I missed it.  If you do end up finding the original one, please feel free to close this.  Thanks! :)

**Comment by varjolintu** [comment]
This one: https://github.com/keepassxreboot/keepassxc/issues/2322

**Comment by droidmonkey** [comment]
Huzzah! And it has a bounty too
