### ISSUE TITLE
Auto-Type

### ISSUE THREAD

**Issue by mplx** [keepassxreboot/keepassxc#5142]
## Overview

Autotype does not focus previous application and types into KeePassXC instead

## Steps to Reproduce

1. select entry
2. either use CTRL-SHIFT-V or Icon "Perform Auto-Type"

## Expected Behavior

Focus on previous app and autotype there

## Actual Behavior

Autotype starts but types into KeePassXC itself

## Context

- current ArchLinux with Budgie desktop

[NOTE]: # ( Give us any additional information you may have. )

- broken since 2.6.0, worked well up to 2.5.4

[NOTE]: # ( Paste debug info from Help → About here )

KeePassXC - Version 2.6.0
Revision: 0765954

Qt 5.15.0
Debugging mode is disabled.

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 5.7.9-arch1-1

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.6

**Comment by droidmonkey** [comment]
Duplicate and we fixed it for 2.6.1
