### ISSUE TITLE
2.6.0 TAB+SPACE on pwd promt does not toggle password visibility

### ISSUE THREAD

**Issue by ni720** [keepassxreboot/keepassxc#5143]
Since v2.6.0 pressing TAB + SPACE does not automatically change the focus to the "make password visible button" and so space does not activate this function.

Steps to Reproduce:

- open keepassx and have a default database configured so it asks for a password
- press TAB, press SPACE

Expected Behavior:

- pressing tab focus jumps to the eye-icon (make pwd visible)
- pressing space executes this button
- Password entry is marked visible and focus jumps back to pwd promt

Actual Behavior:

- focus jumps to "keyfile" row and space enters a path of " " in the field.

current setup: Ubuntu Mate 20.04

**Comment by droidmonkey** [comment]
Ctrl + H
