### ISSUE TITLE
KeepassXC 2.6 can't connect to KeePassXC-Browser anymore

### ISSUE THREAD

**Issue by khedrub** [keepassxreboot/keepassxc#5144]
I upgraded KeepassXC to Version 2.60 on our Windows Terminal Server and ever since then, the connection to the Firefox-Plugin KeePassXC-Browser (also latest Version 1.6.6) can not be established. Tried reinstalling, removing the the Connection and so on, for days now. All I get is the error message of the browser plugin that the message encryption failed, asking me if KeepassXS is running. If I click reload I get key exchange was not successful. Keepass is of course running and locked in and has the browser integration enabled.

**Comment by droidmonkey** [comment]
Have you tried removing all connections and re-adding the browser

**Comment by khedrub** [comment]
Yes I have removed all connections. For many different users. But can not re-add because of the error above.

**Comment by droidmonkey** [comment]
If you go back to 2.5.4, in this current state, does the issue resolve?

**Comment by khedrub** [comment]
Yes going back to 2.5.4 works.

**Comment by varjolintu** [comment]
Check https://github.com/keepassxreboot/keepassxc-browser/wiki/Troubleshooting-guide and verify the registry paths etc.

**Comment by khedrub** [comment]
> Check https://github.com/keepassxreboot/keepassxc-browser/wiki/Troubleshooting-guide and verify the registry paths etc.

Been there, done that. The entry is exactly the same with 2.6 and 2.5.4.

**Comment by varjolintu** [comment]
@khedrub And it doesn't help if you disable Browser Integration, close the settings and the re-enable it? If anything else doesn't solve it, I suggest you use https://docs.microsoft.com/en-us/sysinternals/downloads/procmon and try to find `keepassxc` from the logs. Maybe it could show where it tries to load the JSON script files, and if those files has the correct path for `keepassxc-proxy.exe`.

**Comment by khedrub** [comment]
> @khedrub And it doesn't help if you disable Browser Integration, close the settings and the re-enable it? 

No, that did not help, was one of the first things I tried.

Btw. I also have 2 other Computers on which the upgrade worked fine, so I used those to compare the settings, the registry entries, etc, with the ones from the Terminal Server on which is doesn't work. But no luck there.

**Comment by bittner** [comment]
I also get a "Key exchange was not successful" in Firefox 79.0 (64-bit) after pressing the <kbd>Reload</kbd> button in the browser plugin, with KeePassXC 2.6.0, database unlocked, installed as a snap package on Ubuntu Bionic 18.04.5 LTS:

```console
$ snap list
Name                     Version                     Rev   Tracking         Publisher        Notes
...
keepassxc                2.6.0                       978   latest/stable    keepassxreboot   -
...
```
Details of the Firefox browser plugin:

- KeePassXC - unknown
- KeePassXC-Browser - 1.6.6
- Operating system: Linux x86_64
- Browser: Mozilla Firefox 79.0

Is the KeePassXC as a snap the problem?
Should I better create a ticket in [keepassxreboot/keepassxc-browser](https://github.com/keepassxreboot/keepassxc-browser/issues)?

**Comment by droidmonkey** [comment]
Did you use the snap helper script? Is Firefox running as a snap?

**Comment by bittner** [comment]
No. That should have actually been my question: Does the "installed as a snap doesn't work" only apply to the Web browser or (also?) to the KeePassXC desktop application? – I'll give the helper script a try. Thank you!

**Comment by bittner** [comment]
Cool! Thank fixed it, great! (at least for me) :1st_place_medal: Thanks!
