### ISSUE TITLE
External hook on save / open commands

### ISSUE THREAD

**Issue by renard** [keepassxreboot/keepassxc#5145]
## Summary
FAQ is clear about cloud sync and this makes sense. However a save hook that runs a command on local machine can provide a way so allow user to sync his database to remote location by using the tool of his chois (such as rsync or rclone or whatever)

Of course on some system a inotify-like daemon can be setup to achieve this goal but requires skills and the daemon to run.

Do you thing it would be a good idea to look for a file such as`/path/to/db.post-save` to do some actions? In the same way a `/path/to/db.pre-open` file can be used to automatically fetch the database from the cloud. Of course this will require the user to be very careful about potential data lost.

## Context

This feature will allow any user to push / fetch database from a remote location and make sure it is synchronized across multiple devices while keeping the base code clean and simple.

**Comment by droidmonkey** [comment]
You are probably looking for something like https://github.com/facebook/watchman

**Comment by renard** [comment]
Ok fair enough.

Thanks for the hint.
