### ISSUE TITLE
Input window detached/duplicated from main window

### ISSUE THREAD

**Issue by rugk** [keepassxreboot/keepassxc#5146]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Use DB. Autolock.
2. Minimze, un-minimize, minimize etc. (multiple times or so)

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
I should have one window.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
I have a detached input window ?????!!

![grafik](https://user-images.githubusercontent.com/11966684/87885419-3249a580-ca16-11ea-9335-1194d22cb95e.png)

## Context
[NOTE]: # ( Give us any additional information you may have. )
Wayland, Fedora 32
flatpak from Flathub

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.0
Revision: 0765954
Distribution: Flatpak

Qt 5.14.2
Diagnosemodus ist deaktiviert.

Betriebssystem: KDE Flatpak runtime
CPU-Architektur: x86_64
Kernel: linux 5.7.8-200.fc32.x86_64

Aktivierte Erweiterungen:
- Auto-Type
- Browser-Integration
- SSH-Agent
- KeeShare (bestätigtes und unbestätigtes Teilen)
- YubiKey

Kryptographische Bibliotheken:
 libgcrypt 1.8.5

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: GNOME
Windowing System: Wayland

**Comment by droidmonkey** [comment]
Yes I've noticed this as well, why bother showing the dialog if the main window comes up as well.

**Comment by tim427** [comment]
I've seen the same behaviour, which is fairly easy to reproduce;

With the option "Browser Integration" -> "Request to unlock the database if it is locked" checked, the database itself locked and a simple press on "Reopen database" within the browser extension. This results in a "extra" detached KeePassXC window, which I couldn't close, minimize, or hide.

KeePassXC-Browser Version: 1.7.0
KeePassXC Version 2.6.1 (Revision: 9a35bba, Qt 5.15.0)
Operating system: macOS 10.15
CPU architecture: x86_64
Kernel: darwin 19.6.0

**Comment by droidmonkey** [comment]
To fix this requires a code refactoring which i am slogging through for autotype.
