### ISSUE TITLE
no update for keepassXC on fedora 32

### ISSUE THREAD

**Issue by x0rld** [keepassxreboot/keepassxc#5147]
I don't have the 2.6 update on the repository for fedora 32

KeePassXC - Version 2.5.4
Révision : dcca5aa

**Comment by droidmonkey** [comment]
Please bring that up with the repository maintainer

**Comment by MichaelBitard** [comment]
For those wondering what happens: https://bodhi.fedoraproject.org/updates/FEDORA-2020-fff7107d31

**Comment by droidmonkey** [comment]
That's a random process if I've ever seen one. Why was it unpublished for the yubikey bug, affects very few users and has a workaround (configure slot 1).
