### ISSUE TITLE
KeepassXC scales up

### ISSUE THREAD

**Issue by Doccos** [keepassxreboot/keepassxc#5148]
## Overview
After some time KeepassXC scales up, I can't click anything anymore and I have to restart it

## Steps to Reproduce
I do not know it happens automatically after a certain time

## Expected Behavior
it doesn't change

## Actual Behavior
After some time KeepassXC scales up, I can't click anything anymore and I have to restart it

## Context
this is how it looks when everything is okay:
[https://imgur.com/01T8qjE](https://imgur.com/01T8qjE)
when the error occurs:
[https://imgur.com/6aPNsU6](https://imgur.com/6aPNsU6)

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.6.0
Revision: 0765954

Betriebssystem: Windows 10 Version 2004
CPU-Architektur: x86_64
Kernel: winnt 10.0.19041

Aktivierte Erweiterungen:
- Auto-Type
- Browser-Integration
- SSH-Agent
- KeeShare (bestätigtes und unbestätigtes Teilen)
- YubiKey

Kryptographische Bibliotheken:
 libgcrypt 1.8.5

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 10
4K @ 150% scale

**Comment by droidmonkey** [comment]
Do you have multiple monitors?

**Comment by Doccos** [comment]
Oh yes, I have a 4k laptop with two 4k screens connected

**Comment by Doccos** [comment]
In this screen you can see that the search bar ends and the control buttons are available
[https://imgur.com/qnW8RtG](https://imgur.com/qnW8RtG)
and here you can see that the search bar, the window and the control buttons are not visible
[https://imgur.com/w3kITOh](https://imgur.com/w3kITOh)


I have recorded the whole program, the black area is my desktop

**Comment by Kurama2121** [comment]
This also happens regularly on mac 10.14.6 normally after you do a password auto type. Keepass gets stuck on the top of all windows and the only way to close is to force quit.

**Comment by droidmonkey** [comment]
@Kurama2121 totally different issue, that is due to you setting KPXC as a workspace, and is tracked already.

@Doccos recommend you set the following environment variable due to varying scaling between your monitors: `QT_SCALE_FACTOR_ROUNDING_POLICY=Round`
