### ISSUE TITLE
Segmentation Fault on version 2.6.0 snap

### ISSUE THREAD

**Issue by alyms108** [keepassxreboot/keepassxc#5150]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
When launching the KeepassXC snap from the desktop start menu, launch fails. When launching from the command line via `snap run keepassxc`, an error message is returned indicating a segmentation fault.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Run `snap run keepassxc` in a terminal

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
KeepassXC launches and the window appears.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
On the terminal, the following output is seen:
```
Gtk-Message: 18:15:24.020: Failed to load module "canberra-gtk-module"
Gtk-Message: 18:15:24.107: Failed to load module "colorreload-gtk-module"
Gtk-Message: 18:15:24.107: Failed to load module "appmenu-gtk-module"
Fontconfig warning: FcPattern object width does not accept value [85 100)
[1]    88221 segmentation fault  snap run keepassxc
```

## Context
[NOTE]: # ( Give us any additional information you may have. )
I am running Manjaro KDE edition and recently performed a system update. I don't recall if the snap was at version 2.6.0 before the system update or not.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.6.0

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: KDE
Windowing System: X11

**Comment by droidmonkey** [comment]
Does running it with just `keepassxc` cause a crash?

**Comment by alyms108** [comment]
I didn't realize it was an option to run with `keepassxc` by itself. Unfortunately, I've already removed the snap and installed the version in Manjaro's repos, so I don't know if I could test the snap.

**Comment by droidmonkey** [comment]
Yah can have both installed but you might have to run it explicitly like `/snap/bin/keepassxc`

**Comment by Alcsaw** [comment]
Hi!

I have the same issue here on Ubuntu 20.04 (Gnome).

keepassxc            2.6.2               1136   latest/stable    keepassxreboot  -

~ ➜  keepassxc                             
Gtk-Message: 08:30:46.342: Failed to load module "canberra-gtk-module"
Gtk-Message: 08:30:46.344: Failed to load module "canberra-gtk-module"
Qt: Session management error: None of the authentication protocols specified are supported
Fontconfig warning: FcPattern object weight does not accept value [0 205)
[1]    47575 segmentation fault  keepassxc
~ ➜  snap run keepassxc
Gtk-Message: 08:33:10.885: Failed to load module "canberra-gtk-module"
Gtk-Message: 08:33:10.886: Failed to load module "canberra-gtk-module"
Qt: Session management error: None of the authentication protocols specified are supported
Fontconfig warning: FcPattern object weight does not accept value [0 205)
[1]    47761 segmentation fault  snap run keepassxc

I was using the apt version (2.4) and it was running fine... Do you know how to fix that? Thanks!

**Comment by droidmonkey** [comment]
This cannot be reproduced, it is most likely a fault introduced by the snap containment. Can you try running our appimage?

**Comment by Alcsaw** [comment]
I could run the AppImage flawlessly here. It is indeed only happening with the snap version, @droidmonkey

**Comment by Alcsaw** [comment]
Hi!

I noticed some other apps I tried to install today via snap were also not being able to start. Searching for the problem for DBeaver, I saw this link: https://github.com/dbeaver/dbeaver/issues/9307

This solved for DBeaver and also for KeepassXC... Kinda. I still get the error, but app launches:
```
➜  /snap/bin/keepassxc 
Gtk-Message: 15:53:17.292: Failed to load module "canberra-gtk-module"
Gtk-Message: 15:53:17.305: Failed to load module "canberra-gtk-module"
Qt: Session management error: None of the authentication protocols specified are supported
propsReply "An AppArmor policy prevents this sender from sending this message to this recipient; type=\"method_call\", sender=\":1.369\" (uid=1000 pid=26748 comm=\"/snap/keepassxc/1136/usr/bin/keepassxc -style fusi\" label=\"snap.keepassxc.keepassxc (enforce)\") interface=\"org.freedesktop.DBus.Properties\" member=\"GetAll\" error name=\"(unset)\" requested_reply=\"0\" destination=\"org.freedesktop.NetworkManager\" (uid=0 pid=636 comm=\"/usr/sbin/NetworkManager --no-daemon \" label=\"unconfined\")"
nmReply "An AppArmor policy prevents this sender from sending this message to this recipient; type=\"method_call\", sender=\":1.369\" (uid=1000 pid=26748 comm=\"/snap/keepassxc/1136/usr/bin/keepassxc -style fusi\" label=\"snap.keepassxc.keepassxc (enforce)\") interface=\"org.freedesktop.NetworkManager\" member=\"GetDevices\" error name=\"(unset)\" requested_reply=\"0\" destination=\"org.freedesktop.NetworkManager\" (uid=0 pid=636 comm=\"/usr/sbin/NetworkManager --no-daemon \" label=\"unconfined\")"
"Object path cannot be empty"
QObject::startTimer: Timers cannot have negative intervals
```

**Comment by droidmonkey** [comment]
Awesome thanks for the report back!

**Comment by droidmonkey** [comment]
Solution: https://github.com/dbeaver/dbeaver/issues/9307#issuecomment-702426109
