### ISSUE TITLE
Filepicker for key files no longer remembers the last location

### ISSUE THREAD

**Issue by JC85206** [keepassxreboot/keepassxc#5151]
## Overview

1) Since the last (?) update I noticed two files at ~/.config, the usual `keepassxcrc` file that I have under source control, but also `KeePassXCrc`

2) I always keep this file as _read only_ because it leaks the  _filenames_ of the _key files_. I want it to remember the last location of the keyfile but not the file itself. Now the filepicker opens at my home folder instead.

>[KFileDialog Settings]
>Recent Files[$e]=
>Recent URLs[$e]=file:$HOME/example/folder-with-my-keyfile

3) keepassxc.ini used to have

>LastDir=/home/example/folder-with-my-keyfile

But the settings below do not exist anymore, at least when I check my git diff they were/get removed, and `ConfigVersion=1` added.

```
LastActiveDatabase=/home/example/example.db
LastDatabases=/home/example/example.db
LastDir=/home/example/folder-with-my-keyfile
LastKeyFiles=@Invalid()
LastOpenedDatabases=/home/example/example.db
```

## Steps to Reproduce
1. Open KeePassXC
2. Click on _Browse..._ to select the keyfile

## Expected Behavior
Filepicker (for key files) opens at _LastDir_, or even at the first directory of _Recent URLs[$e]_

## Actual Behavior
Filepicker (for key files) opens at my home folder by default instead

## Context
KeePassXC - Version 2.6.0
Revision: 0765954
Qt 5.12.7
Operating System: Linux
Desktop Env: KDE
Windowing System: X11

**Comment by droidmonkey** [comment]
Lemme guess, you mount your ~/.cache directory to a tempfs

**Comment by JC85206** [comment]
@droidmonkey  No. I wasn't aware it used the cache folder. I just added `LastDir=` there manually and it works. Since I restarted keepassxc and locked/unlocked the database multiple times for testing my guess would be that the value wasn't transfered on config upgrade or that it isn't being saved on database unlock.

**Comment by JC85206** [comment]
To be clear, I have `RememberLastKeyFiles=false` but like I said I only want the "last folder" option to get saved on disk. It worked like that for years, maybe unintentionally I don't know. But if the new behavior is better this issue can be closed. I confirmed and if you have `RememberLastKeyFiles=true` everything works correctly, the cache file gets updated.

**Comment by droidmonkey** [comment]
We explicitly clear the LastDir config value if you have "Remember last keyfiles" disabled.
