### ISSUE TITLE
Auto-Type "window association" does not work properly with Steam

### ISSUE THREAD

**Issue by Jeddunk** [keepassxreboot/keepassxc#5152]
## Overview
When using auto-type with Steam's login window, KPXC will use the default sequence instead of the one set up with the "Window association" setting in the entry.

## Steps to Reproduce
1. Create an entry with login data for Steam.
2. Add a window association for the Steam application (Window title: "Steam Login") and save changes.
3. Execute auto-type.

## Expected Behavior
Auto-type uses the sequence specified for the application.

## Actual Behavior
Auto-type uses the default sequence.

## Context
KeePassXC - Version 2.6.0
Revision: 0765954

Qt 5.15.0
Debugging mode is disabled.

Operating system: Windows 10 Version 2004
CPU architecture: x86_64
Kernel: winnt 10.0.19041

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.5

**Comment by droidmonkey** [comment]
Works perfectly fine for me

**Comment by droidmonkey** [comment]
![image](https://user-images.githubusercontent.com/2809491/88175735-45b26780-cbf4-11ea-974e-4541ebd5fb52.png)

**Comment by Jeddunk** [comment]
Can you try adding {TAB}{SPACE} between {PASSWORD} and {ENTER} (eventually with delays)? This is so the "Remember my password" checkbox is set to true. I should've mentioned it in my initial bug report, sorry.

**Comment by droidmonkey** [comment]
Worked without issue: `{USERNAME}{TAB}{DELAY 500}{PASSWORD}{TAB}{DELAY 500}{SPACE}{ENTER}`

**Comment by Jeddunk** [comment]
ok thank you...
