### ISSUE TITLE
Feature request : Pinned items

### ISSUE THREAD

**Issue by F3000** [keepassxreboot/keepassxc#5153]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )

Right click on an entry and say "pin this to top etc.." 

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )

**Comment by kresdjan** [comment]
+1 that would actually be very useful.

**Comment by droidmonkey** [comment]
This will be a great feature to combine with #508

**Comment by F3000** [comment]
Maybe this feature is already in the keepass standard so other clients and keepassxc can display the same pinned entry's .

E.g. @strongbox have implemented it already

**Comment by droidmonkey** [comment]
Compliment to #4518

**Comment by dotancohen** [comment]
On Issue #4518 I mention my workaround to pinning items. I start the Notes section with two backticks ``` `` ```, then I can search the Find field for two backticks and easily find the items that ו would otherwise piח.

**Comment by CorentiOS** [comment]
+1

**Comment by CorentiOS** [comment]
+1, any update ?

**Comment by phoerious** [comment]
No. But I suggest, you simply use the search function.

**Comment by droidmonkey** [comment]
Considering the new tags feature, adding this feature is UI bloat that achieves the same thing as one click on a tag. Just add a "Pinned" or "Favorite" tag to those entries you want to pin. You can combine this with "Search within current group" to really get a pinned like experience.

**Comment by michaelk83** [comment]
> Just add a "Pinned" or "Favorite" tag to those entries you want to pin.

It may still be useful to have a one-click method to do this, though IMO "Pinned" and "Favorite" are more or less the same thing.

A more generalized approach may be to add a global setting of "Quick toggle tags" where users can enter a short list of tags that can be toggled with a single click in the entry edit page (and maybe in the preview). The list would default to just the "Favorite" tag. Probably overkill, but just throwing ideas...

**Comment by droidmonkey** [comment]
Yes I have a pending PR that expands the tag experience with "Saved Searches" and easily set standard tags (like Favorite). I find tags to be the one feature I never knew I needed until I used it.
