### ISSUE TITLE
Error in nixutils compilation from v2.6.X due to missing additional dependency (qtbase5-private-dev)

### ISSUE THREAD

**Issue by KnightOfCups** [keepassxreboot/keepassxc#5156]
## Overview
Under Debian 10 Buster, I had to compile the sources of the last stable version to get work with the browser addon. Previously, I successfully compiled the 2.5.4 version after installing the dependencies requested. When I switched to 2.6.x branches, `asciidoctor` was presumably the only new one to have but I failed to build with the following error.

## Steps to Reproduce
1. Debian 10 Buster OS
2. Downloading of `keepassxc` sources from 2.6.X version
3. Installation of dependencies listed in `INSTALL.md` or raised by `cmake` run

## Expected Behavior
I guess `cmake` should have detected the missing package `qtbase5-private-dev`, I found the solution thanks to [this external ticket](https://github.com/zealdocs/zeal/issues/123).

## Actual Behavior
`[ 63%] Building CXX object src/CMakeFiles/keepassx_core.dir/gui/osutils/nixutils/NixUtils.cpp.o`
`/home/user/Downloads/keepassxc-2.6.0/src/gui/osutils/nixutils/NixUtils.cpp:30:10: fatal error: qpa/qplatformnativeinterface.h: No such file or directory`
` #include <qpa/qplatformnativeinterface.h>`
`          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~`
`compilation terminated.`

## Context
KeePassXC - 2.6.X
Operating System: Linux
Desktop Env: Gnome
Windowing System: X11

**Comment by droidmonkey** [comment]
It is already listed in our environment setup for Debian/Ubuntu: https://github.com/keepassxreboot/keepassxc/wiki/Set-up-Build-Environment-on-Linux#install-the-required-dependencies
