### ISSUE TITLE
MacOS – KeePassXC Unexpectedly Quit

### ISSUE THREAD

**Issue by faxotherapy** [keepassxreboot/keepassxc#5158]
## Overview
I thinks it's related to CAPS lock key.

## Steps to Reproduce
Unfortunately, issue happens randomly.

## Expected Behavior
I expect the app to open the database without crashing.

## Actual Behavior
Crash while opening the databse

## Context
CAPS lock on.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION 2.6.0
Revision: 0765954

Operating System: Windows/Linux/macOS

## Log
[CrashReport.txt](https://github.com/keepassxreboot/keepassxc/files/4965365/CrashReport.txt)

**Comment by droidmonkey** [comment]
The crash is in Qt, please report this to them:

<details>
<summary>Stack Trace</summary>
Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   org.qt-project.QtGui          	0x0000000101192818 QTextLayout::drawCursor(QPainter*, QPointF const&, int, int) const + 616
1   org.qt-project.QtWidgets      	0x0000000100ba7344 QWidgetLineControl::draw(QPainter*, QPoint const&, QRect const&, int) + 596
2   org.qt-project.QtWidgets      	0x0000000100ba1933 QLineEdit::paintEvent(QPaintEvent*) + 1779
3   org.qt-project.QtWidgets      	0x0000000100a9b855 QWidget::event(QEvent*) + 1093
4   org.qt-project.QtWidgets      	0x0000000100b9fc85 QLineEdit::event(QEvent*) + 725
5   org.qt-project.QtWidgets      	0x0000000100a61ce6 QApplicationPrivate::notify_helper(QObject*, QEvent*) + 262
6   org.qt-project.QtWidgets      	0x0000000100a63125 QApplication::notify(QObject*, QEvent*) + 581
7   org.qt-project.QtCore         	0x0000000101878de4 QCoreApplication::notifyInternal2(QObject*, QEvent*) + 212
8   org.qt-project.QtWidgets      	0x0000000100a8d393 QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) + 3411
9   org.qt-project.QtWidgets      	0x0000000100a95b77 QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) + 1079
10  org.qt-project.QtWidgets      	0x0000000100a8d6aa QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) + 4202
11  org.qt-project.QtWidgets      	0x0000000100a95b77 QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) + 1079
12  org.qt-project.QtWidgets      	0x0000000100a8d6aa QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) + 4202
13  org.qt-project.QtWidgets      	0x0000000100a95b77 QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) + 1079
14  org.qt-project.QtWidgets      	0x0000000100a8d6aa QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) + 4202
15  org.qt-project.QtWidgets      	0x0000000100a95b77 QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) + 1079
16  org.qt-project.QtWidgets      	0x0000000100a8d6aa QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) + 4202
17  org.qt-project.QtWidgets      	0x0000000100a95b77 QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) + 1079
18  org.qt-project.QtWidgets      	0x0000000100a8d6aa QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) + 4202
19  org.qt-project.QtWidgets      	0x0000000100a95b77 QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) + 1079
20  org.qt-project.QtWidgets      	0x0000000100a8d6aa QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) + 4202
21  org.qt-project.QtWidgets      	0x0000000100a95b77 QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) + 1079
22  org.qt-project.QtWidgets      	0x0000000100a8d6aa QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) + 4202
23  org.qt-project.QtWidgets      	0x0000000100a95b77 QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) + 1079
24  org.qt-project.QtWidgets      	0x0000000100a8d6aa QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) + 4202
25  org.qt-project.QtWidgets      	0x0000000100a95b77 QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) + 1079
26  org.qt-project.QtWidgets      	0x0000000100a8d6aa QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) + 4202
27  org.qt-project.QtWidgets      	0x0000000100a95b77 QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) + 1079
28  org.qt-project.QtWidgets      	0x0000000100a8d6aa QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) + 4202
29  org.qt-project.QtWidgets      	0x0000000100a95b77 QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) + 1079
30  org.qt-project.QtWidgets      	0x0000000100a8d6aa QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) + 4202
31  org.qt-project.QtWidgets      	0x0000000100a6f52c 0x100a51000 + 124204
32  org.qt-project.QtWidgets      	0x0000000100a6f832 0x100a51000 + 124978
33  org.qt-project.QtWidgets      	0x0000000100a9ba7e QWidget::event(QEvent*) + 1646
34  org.qt-project.QtWidgets      	0x0000000100bacb04 QMainWindow::event(QEvent*) + 276
35  org.qt-project.QtWidgets      	0x0000000100a61ce6 QApplicationPrivate::notify_helper(QObject*, QEvent*) + 262
36  org.qt-project.QtWidgets      	0x0000000100a63125 QApplication::notify(QObject*, QEvent*) + 581
37  org.qt-project.QtCore         	0x0000000101878de4 QCoreApplication::notifyInternal2(QObject*, QEvent*) + 212
38  org.qt-project.QtCore         	0x0000000101879f63 QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) + 803
39  libqcocoa.dylib               	0x00000001038c48a2 0x10388b000 + 235682
40  libqcocoa.dylib               	0x00000001038c4fa8 0x10388b000 + 237480
41  com.apple.CoreFoundation      	0x00007fff34232d17 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
42  com.apple.CoreFoundation      	0x00007fff34232cbd __CFRunLoopDoSource0 + 108
43  com.apple.CoreFoundation      	0x00007fff3421667b __CFRunLoopDoSources0 + 195
44  com.apple.CoreFoundation      	0x00007fff34215c45 __CFRunLoopRun + 1189
45  com.apple.CoreFoundation      	0x00007fff3421554e CFRunLoopRunSpecific + 455
46  com.apple.HIToolbox           	0x00007fff334741ab RunCurrentEventLoopInMode + 292
47  com.apple.HIToolbox           	0x00007fff33473ee5 ReceiveNextEventCommon + 603
48  com.apple.HIToolbox           	0x00007fff33473c76 _BlockUntilNextEventMatchingListInModeWithFilter + 64
49  com.apple.AppKit              	0x00007fff3180b77d _DPSNextEvent + 1135
50  com.apple.AppKit              	0x00007fff3180a46b -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1361
51  com.apple.AppKit              	0x00007fff31804588 -[NSApplication run] + 699
52  libqcocoa.dylib               	0x00000001038c3d34 0x10388b000 + 232756
53  org.qt-project.QtCore         	0x0000000101874fb7 QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) + 439
54  org.qt-project.QtCore         	0x0000000101879372 QCoreApplication::exec() + 130
55  org.keepassxc.keepassxc       	0x0000000100371aa0 0x100368000 + 39584
56  libdyld.dylib                 	0x00007fff6017e3d5 start + 1
</details>
