### ISSUE TITLE
KeePassXC: Windows - Application Error

### ISSUE THREAD

**Issue by Jman211677** [keepassxreboot/keepassxc#5159]
Overview: I am new to KeePassXC. Not very computer savvy. Trying to learn as much as I can about securing my information. This is the first step of many. Thank you in advance for the help.

Note: The pop-up error: "The instruction at 0x0000000001991ED9 referenced memory at 0x0000000000000008. The memory could not be read. Click on OK to terminate the program"  appears while I attempt to change my password of my database. This has been happening on and off. Was finally able to change it after restarting the program. Wanted to make sure this wasn't happening to anyone else. 

Steps to Reproduce:
1. Click database
2. Click database security (with the key icon)
3. Change password
4. Start typing and experience the popup.

Expected Behavior: To be able to change password.

Actual Behavior: Pop-up error occurs and program terminates.

Context: Downloaded KeePassXC two days ago. Using a refurbished computer that is from certified manufacturer. Owned the computer for two days. No other modifications to computer.

The below is copied from my program's debugging info:

KeePassXC - Version 2.6.0
Revision: 0765954

Qt 5.15.0
Debugging mode is disabled.

Operating system: Windows 10 Version 1909
CPU architecture: x86_64
Kernel: winnt 10.0.18363

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.5

Operating system: Windows 10

**Comment by droidmonkey** [comment]
Cannot reproduce at all. If anyone else can reproduce I'll reopen.
