### ISSUE TITLE
Computer immediately suspends upon wake if keepassxc is open.

### ISSUE THREAD

**Issue by tmccombs** [keepassxreboot/keepassxc#5161]
## Overview
If I have keepassxc open with an unlocked databaser, I must press the power button 3-4 times to actually wake up my computer. If keepassxc is not running it works on the first try

## Steps to Reproduce
1. Open keepassxc and unlock a password database
2. Suspend computer
3. Attempt to wake up computer

## Expected Behavior
The computer wakes up on the first try. Keepassxc is locked on resume.

## Actual Behavior
The first few times I try, the computer will start to wake up, but will then immediately go back to sleep. If I continue trying it will eventually resume, at which point the keepassxc database is locked as expected.

## Context
I am running archlinux, with sway as my wayland compositor.

KeePassXC - Version 2.6.0
Revision: 0765954

Qt 5.15.0
Debugging mode is disabled.

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 5.7.9-arch1-1

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.6

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: sway
Windowing System: Wayland

**Comment by droidmonkey** [comment]
We don't issue any sleep commands.

**Comment by tmccombs** [comment]
no

**Comment by tmccombs** [comment]
I just got the problem without keepassxc running, so it is probably something else.
