### ISSUE TITLE
When the system boots, two instances of the program are launched

### ISSUE THREAD

**Issue by blackshef** [keepassxreboot/keepassxc#5162]
## Overview
When the system boots, two instances of the program are launched, although the toggle switch for the launch parameter of one instance is on

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - KeePassXC 2.6.0
Revision: 0765954

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 10 Pro
Ver: 1903
Build the OS: 18362,239
![Снимок экрана (51)](https://user-images.githubusercontent.com/68725808/88365436-a37ab700-cd8e-11ea-8c66-6674f1e66779.png)
![Снимок экрана (52)](https://user-images.githubusercontent.com/68725808/88365437-a4134d80-cd8e-11ea-90af-81d080566502.png)

**Comment by droidmonkey** [comment]
You probably need to remove a shortcut from your startup folder
