### ISSUE TITLE
XFCE4 + v 2.6.0 layout broken

### ISSUE THREAD

**Issue by skewwhiffy** [keepassxreboot/keepassxc#5173]
## Overview
![image](https://user-images.githubusercontent.com/964993/88467476-7b46a180-cecf-11ea-965c-7266ac8b2f58.png)
Font rendering and layout are out in XFCE4. Have reproduced in Arch and Debian (testing).

## Steps to Reproduce
1. Use vanilla XFCE4 Debian (testing) install
2. Install keepassxc
3. Behold, nothing lines up in the layout.

## Expected Behavior
Layout should be beautiful new flat layout

## Actual Behavior
Buttons and text are often half invisible.

## Context
Seems to work fine in Cinnamon / GNOME on the same machine and distributions.

KeePassXC - 2.6.0
Revision: 0765954

Operating System: Linux
Desktop Env: XFCE
Windowing System: X11

**Comment by droidmonkey** [comment]
Pinned issue
