### ISSUE TITLE
2.6.0 Cannot disable Load previously open databases on startup

### ISSUE THREAD

**Issue by 01yakiek** [keepassxreboot/keepassxc#5174]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
On version 2.6.0, there is no way to uncheck "Load previously open databases on startup" after unchecking "Remember previously used databases". Even unchecking in order, after restarting, the setting persists as checked and still loads previously open databases on startup.
I'm quite sure this didn't happen prior to 2.6.0. After I updated it, I reset the settings and this is the result.
Somehow, it's no longer to completely disable both at once which are history-related.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Load a test database.
2. Check "Remember previously used databases".
3. Uncheck "Load previously open databases on startup".
4. Uncheck "Remember previously used databases".
5. Save settings by clicking OK.
6. Restart.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
What it's intended to do is it should not keep any history, not even previous open databases.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
History is not not kept, and previous databases are still being loaded after restart, which it should not. Somehow, this is no longer possible.

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.0
Revision: 0765954

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows

**Comment by droidmonkey** [comment]
This was a bug, already fixed in 2.6.1 upcoming
