### ISSUE TITLE
Writing the database failed: File exists

### ISSUE THREAD

**Issue by perahodlr** [keepassxreboot/keepassxc#5175]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )

Error "Writing the database failed: File exists" saving database stored on a samba share (iomega nas) when on Fedora 32 running the AppImage. This setup works on my Windows 10.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Launch KeePassXC-2.6.0-x86_64.AppImage, with default settings, DB on samba share
2. Make changes, save
3. Error: Writing the database failed: File exists

## Expected Behavior
Saving/writing to the DB should complete error free.

## Actual Behavior
Saving changes to DB produces error Writing the database failed: File exists

## Context

Fedora release 32
Linux localhost.localdomain 5.7.10-201.fc32.x86_64 #1 SMP Thu Jul 23 00:58:39 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
DB is on a samba share (iomega nas)
mount output:
type cifs (rw,relatime,vers=1.0,cache=strict,username=user,uid=1000,forceuid,gid=1000,forcegid,addr=192.168.x.x,soft,unix,posixpaths,serverino,mapposix,acl,rsize=61440,wsize=65536,bsize=1048576,echo_interval=60,actimeo=1,user=user)

Removing the DB file from the samba share, the DB file is created when saving in KeePassXC and no error message.
With "Safely save database files" disabled, I am able to save to the DB.

In the terminal where I launched the AppImage, a message "QFSFileEngine::open: No file name specified" shows when I click save and the error "Writing the database failed: File exists" shows in the GUI.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.0
Revision: 0765954
Distribution: AppImage

Qt 5.14.2
Debugging mode is disabled.

Operating system: Fedora 32 (Workstation Edition)
CPU architecture: x86_64
Kernel: linux 5.7.10-201.fc32.x86_64

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.1

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: Gnome
Windowing System: Wayland
Running AppImage shows the following output:
$ KeePassXC-2.6.0-x86_64.AppImage 
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.

**Comment by droidmonkey** [comment]
Probably same issue as with #4856

**Comment by cagdasalagoz** [comment]
I am having the same problem yet I do not use Google drive. The only similarity I can see with the #4856 is my database and key files are also on another partition. So they must be mounted before accessing the database. Looks like it's caused by mounting/unmounting partitions.

**Comment by kevin25** [comment]
I have the same issue

**Comment by 1953willys** [comment]
Same problem, perhaps different causes.  This is MAC installation, with Ventura 13.2.1 software and 2.7.4 Keypass XC.  There are two user accounts (in addition to the admin acct).  The  database is kept in a shared folder, with the box checked for shared access via "get info" on the folder.  The data base file has been set in permissions for both users to have read and write access.  I can create the problem by successfully making a database change from one user, then, accessing the same database from the other user, and if a change is made, this same error message appears.  I can then reverse the  process in terms of which user goes first, and then the problem occurs with  the other user.  This is a relatively new problem, this setup  of one database and two users worked well for quite a while, but no more.  I have a duplicate arrangment on another  MAC, and it's developed the same problem.  Appreciate any attention or thoughts

**Comment by droidmonkey** [comment]
@1953willys did the problem develop after a keepassxc update or a macos update?

**Comment by 1953willys** [comment]
I don't know, but there are more frequent MAC updates than Keepass XC ones, I think.
________________________________

**Comment by 1953willys** [comment]
I think I have a work around.  I make a copy of the .kdbx database,  and rename it.  Then, I  have each user access one of the two databases only.  This works, problem does not occur.  I have some  additional work to make sure entries by one user are captured  to the other database periodically.  This is necessary anyway given the sneakernet  method to coordinate databases between 3 machines.  The configuration of a mac, using two separate users on one machine, is not very common, I bet.

**Comment by IshanDindorkar** [comment]
for me this worked, 
1. Created new password file.
2. Transferred existing credentials to new one.

**Comment by FLAK-ZOSO** [comment]
Same here
