### ISSUE TITLE
flatpak broke start-up script

### ISSUE THREAD

**Issue by jucajuca** [keepassxreboot/keepassxc#5179]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
Flatpak broke my integrations. keepassxc was launching nicely at startup and it connected automatically to the browser. All this is not working anymore. 

my start-up script: `/bin/bash -c "secret-tool lookup keepassxc jccb-passwords | keepassxc --pw-stdin /mnt/folder/foleder/passwords/my-passwords-file.kdbx"`

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Migrate to flatpak (as forced by Pop!Os

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Start up launch and browser integration should work automatically

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Keepassxc does not launch at start-up

## Context
[NOTE]: # ( Give us any additional information you may have. )
Pop-Os

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.0
Revision: 0765954
Distribution: Flatpak

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux  - PopOS
Desktop Env: Gnome
Windowing System: X11

**Comment by jucajuca** [comment]
adding this solved the problem:
https://launchpad.net/~phoerious/+archive/ubuntu/keepassxc
I saw that packaging is a problem. Maybe you should drop snaps but dropping support for the DEB packages is definitely not a great idea.

**Comment by phoerious** [comment]
We are not dropping support for DEBs und the Flatpak ist not maintained by us. Please report your issues there.
