### ISSUE TITLE
checksum matching

### ISSUE THREAD

**Issue by MLS-EA69** [keepassxreboot/keepassxc#5180]
Hi all.
I'm new to Keepass XC and would like to trial it.
Please help me understand why I'm getting 2 different checksums in terminal for the .digest and .dmg files for the newest Keepass xc release.
The PGP signature matches.
Please advise. Thanks

**Comment by droidmonkey** [comment]
Did you follow the verify signatures instructions exactly? Did you download it for our downloads page or releases on github?

**Comment by MLS-EA69** [comment]
I downloaded from Keepass XC download page.
I typed shasum -a 256 for both .digest and .dmg in Terminal and received 2 different checksums

**Comment by droidmonkey** [comment]
So you didn't follow the instructions. Of course they are going to be different. The DIGEST has the checksum in the file itself.

**Comment by MLS-EA69** [comment]
I originally typed the command as on the website:
 shasum -a 256 -c KeePassXC-*.dmg.DIGEST
KeePassXC-*.dmg.AppImage: OK

This didn't work for me. Not sure why

**Comment by droidmonkey** [comment]
This is the command, the second line is the expected response. 

`shasum -a 256 -c KeePassXC-*.dmg.DIGEST`

**Comment by MLS-EA69** [comment]
I did enter that command and did not get that response.
I’ll try to figure out what’s going on my end.

Thanks for promptly responding.
Have a good day.

**Comment by MLS-EA69** [comment]
So...I was able to verify the checksum by converting the .digest file into .txt file which displays the checksum of the installer.
Thanks

**Comment by droidmonkey** [comment]
Great!
