### ISSUE TITLE
Feature suggestion

### ISSUE THREAD

**Issue by h0gwash** [keepassxreboot/keepassxc#5181]
Ability to store and manage basic contacts (addresses and phone numbers). In "add entry", create more fields relative to the entry being a contact and/or a login. This would simply be at least 3 fields for "phone number", "address" and "email address". "Title" would serve as the contacts name. At the moment, I am using keepass for this very purpose since it makes sense to me that my login auths and contacts live together in one place and is offline, secure and portable. I create a group called "contacts" and go from there. A "login" and a "contact" are fundamentally the same thing. In fact, phone numbers could potentially change to a password format and achieve the same result and with added benefits.

**Comment by droidmonkey** [comment]
Duplicate of #863
