### ISSUE TITLE
Regression: keepassxc 2.6.0 from flatpak fails for URLs starting with "cmd://"

### ISSUE THREAD

**Issue by Bob837217** [keepassxreboot/keepassxc#5182]
## Overview
keepassxc 2.4.3 as installed as a standard deb package works as it should.
keepassxc 2.6.0 as installed from flatpak does not work as it should.  This is a regression.

## Steps to Reproduce
1.  Launch flatpak keepassxc 2.6.0
2. Create a new entry with any description, username, password
3. Edit the URL field and set the following URL text (without surrounding quotes): "cmd://firefox --private-window https://gmail.google.com"
4. Save the new entry
5. Double click to launch the new instance of firefox as Private Browsing Mode (click Yes on the "Execute command?" dialog box first)
6. Observe a new instance of firefox in Private Browsing with the url set to: https://gmail.google.com

## Expected Behavior

After step 5, you should see and instance of firefox in Private Browsing with the url set to: https://gmail.google.com

## Actual Behavior

After step 5 (confirming Yes on the "Execute command?" dialog box) - nothing appears at all

## Context

**Working Version Details**
KeePassXC - Version 2.4.3
Revision: 5d6ef0c

**Regression Version Details**
KeePassXC - Version 2.6.0
Revision: 0765954
Distribution: Flatpak

Operating System: Linux
Desktop Env: Gnome
Windowing System: X11

**Comment by droidmonkey** [comment]
We don't maintain the flatpak

**Comment by Bob837217** [comment]
I think the issue may be to do with sandboxing and flatpaks?  Do you know at all how do I find who I need to talk to regarding the flatpak for KeePassXC 2.6.0 ?

**Comment by droidmonkey** [comment]
Yes thats the place.
