### ISSUE TITLE
Provide visual feedback when icons are clicked

### ISSUE THREAD

**Issue by keithfetterman-nxturn** [keepassxreboot/keepassxc#5183]
## Summary
The 2.6.0 version of KeePassXC included new icons in the top navigation bar.  When I click them with the mouse, I don't see any visual feedback that they were clicked, so I am not sure if they are clicked or not until the window changes.  It would be nice if there was some feedback, like highlight, when the icons are clicked.

I am using KeePassXC on MacOS.  

Here is the Debug Details from KeePassXC:

KeePassXC - Version 2.6.0
Revision: 0765954

Qt 5.15.0
Debugging mode is disabled.

Operating system: macOS Mojave (10.14)
CPU architecture: x86_64
Kernel: darwin 18.7.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
 libgcrypt 1.8.5

**Comment by droidmonkey** [comment]
There is visual feedback in the toolbar, both hover and on click. Provide a screenshot or video of your experience.

**Comment by droidmonkey** [comment]
OK I see this with "Classic Mode" theme, but we are not going to correct that since that is default Qt behavior.

**Comment by keithfetterman-nxturn** [comment]
Hi Jonathan,

Thank you for investigating and letting me know that the Light or Dark themes have the visual feedback. I changed from Classic to Automatic theme and it’s working.

Keith

—
Keith Fetterman | Ecommerce Service Manager
NetSuite Certified SuiteCommerce Developer
Office: 954.580.3958 | Mobile: 206.276.8096
Email: keith@nxturn.com<mailto:keith@nxturn.com><mailto:keith@nxturn.com><mailto:keith@nxturn.com>
Web: www.nxturn.com<http://www.nxturn.com>

[cid:84BB3951-B9A2-4F7A-A0A1-7B43DFB958A6@hsd1.wa.comcast.net.]

On Jul 27, 2020, at 7:36 PM, Jonathan White <notifications@github.com<mailto:notifications@github.com>> wrote:



OK I see this with "Classic Mode" theme, but we are not going to correct that since that is default Qt behavior.

**Comment by droidmonkey** [comment]
Good to hear, cheers!
