### ISSUE TITLE
SLowing firefox / freezing Google

### ISSUE THREAD

**Issue by ramjet303** [keepassxreboot/keepassxc#5186]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
KeepPassXC on a financial services (share broker site) freezes on web page and then exhibits warning in screenshot attached.
Give option in error message to switch off KeePassXC for this site 
## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Log into site 
2. Open Watch list 
3. Wait and then Freezes (in Firefox) or silently locks (Google)
Selecting options to disable KeePassXC for that site does not fix

## Expected Behaviour
[NOTE]: # ( Tell us what you expected to happen )
That KeePassXC would not lock up the site

## Actual Behaviour
[NOTE]: # ( Tell us what actually happens )
As above

## Context
[NOTE]: # ( Give us any additional information you may have. )
This broker website only affected. Very severe renders site unusable (importantly unable to do financial transactions).
Manually set SITE PREFERENCE in Settings to site https://trading.directshares.com.au/ but for no benefit. Tried all three options - best seem to disable app for that site- but does not fix problems. Flags intermittently. Severe.Effectively prevents use of a the financial site altogether.

Tried Firefox add on that enables switching javascript on and off but if off key features of web site disappear!

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION  2.6.0
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows/Linux/macOS   Windows 10
Desktop Env: Gnome/KDE/XFCE/Mate/Cinnamon  Windows 10 Desktop
Windowing System: X11/Wayland Windows 10
![https trading directshares com aue](https://user-images.githubusercontent.com/23646628/88619401-d26e9100-d0de-11ea-8acc-06e42c07aa7b.PNG)
![GOLD All Time HIGH](https://user-images.githubusercontent.com/23646628/88619404-d3072780-d0de-11ea-823a-84f56eab887a.PNG)

**Comment by ramjet303** [comment]
Images below yellow bar with warnings accidentally added BUT not relevant. Only that in yellow is relevant. Unable to delete unwanted images added by accident.

**Comment by droidmonkey** [comment]
This issue is being fixed by the extension developer right now.
