### ISSUE TITLE
Password Score in Database Health Check sorted alphabetically

### ISSUE THREAD

**Issue by corrodedHash** [keepassxreboot/keepassxc#5188]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
In the database healthcheck report, sorting the score results in the column not being sorted numerically

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Fresh database, enter 3 passwords with password score 60, 58, 7
2. [Menu] Database -> Database Reports... -> Health Check
3. Sort by Column 'Score'

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Passwords are sorted in ascending numerical order, e.g. 7, 58, 60

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Passwords are sorted in ascending alphabetical order, e.g. 58, 60, 7

## Context
KeePassXC - Version 2.6.0
Revision: 0765954

Qt 5.15.0
Debugging mode is disabled.

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 5.7.10-arch1-1

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.6

[NOTE]: # ( Pick choices based on your environment )
Desktop Env: Awesome WM
Windowing System: X11

**Comment by droidmonkey** [comment]
Duplicate
