### ISSUE TITLE
Version 2.6.0 is not available in Fedora 32 repository.

### ISSUE THREAD

**Issue by JanFisherGG** [keepassxreboot/keepassxc#5192]
## Summary
I have a suspicion that something might have gone wrong with the .rpm package build process. Version 2.6.0 is not available from Fedora 32 repositories. Or the newest version is unavailable for some other reason. Note that all other distributions have the package available in their repositories.

## Examples
On the [download page](https://keepassxc.org/download/#linux) clicking on on the green "Fedora package" link
![image](https://user-images.githubusercontent.com/59537943/88717051-42e9d200-d120-11ea-87af-de7fd8485e8e.png)
![image](https://user-images.githubusercontent.com/59537943/88716866-01592700-d120-11ea-955a-bb5629143bb9.png)
takes me to a [page](https://apps.fedoraproject.org/packages/keepassxc) where the package is supposed to be hosted(?) but the "(...)service is currently unavailable."

On their [status page](https://status.fedoraproject.org/)they do report that the "Fedora Packages App" is down. I guess that's what's responsible for making the package available.
![image](https://user-images.githubusercontent.com/59537943/88718699-76c5f700-d122-11ea-88f9-9ed2c2c21f1b.png)]
Do you as a developer of KeePassXC have any idea on this topic or does Fedora take your code and it's not your concern?

## Context
I use Fedora and it's important to me to be able to easily download and install KeePassXC from Fedora's repository.

**Comment by droidmonkey** [comment]
Duplicate, take this to the repository maintainer
