### ISSUE TITLE
KeepassXC memorize previous database when this setting is set to not

### ISSUE THREAD

**Issue by narzb** [keepassxreboot/keepassxc#5193]
## Overview
KeepassXC 2.6.0 keep previous open database when I set « memorize previous database» to False.

## Steps to Reproduce
1. set « memorize previous database» to False
2. open db an close keepassxc
3. reopen keepassxc

## Expected Behavior
previous database should not pre-load

## Actual Behavior
previous database pre-load

[NOTE]: #
KeePassXC - 2.6.0

[NOTE]: #
Operating System: Windows

**Comment by droidmonkey** [comment]
Already fixed for 2.6.1
