### ISSUE TITLE
Bug layout keepassxc

### ISSUE THREAD

**Issue by willy1920** [keepassxreboot/keepassxc#5195]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. default manjaro keepassxc already broken
2. I use snap too but it's still broken
3. I clone the project and rebuild and run still broken

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: XFCE
Windowing System: X11/Wayland (not sure)

![Screenshot_2020-07-29_21-41-28](https://user-images.githubusercontent.com/21374073/88814662-9faec080-d1e4-11ea-86a1-a3a2d3ae23a9.png)

**Comment by droidmonkey** [comment]
Pinned issue
