### ISSUE TITLE
[Bug] KeePassXC CLI errors, when used with network path for database file

### ISSUE THREAD

**Issue by bela53** [keepassxreboot/keepassxc#5196]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

KeePassXC CLI seems to be not usable with network shares, mounted via SMB (v3). The GUI version works with same environment and database file.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )

Install KeepassXC as AppImage. Mount network share akin to: 
```
sudo mount -t cifs -o username=user,password=pw,vers=3.11,uid=user //network/share /media/share
```
Then:
1. `keepassxc.cli ls /media/share/db.kdbx` (network path)
2. `keepassxc.cli ls ~/db.kdbx` (local path)

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Both network (1) and local share access (2) result in a password prompt and finally in a listing of all entries (after success). 

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Case 1) results in an error (before password is prompted):
> Failed to open database file /media/share/db.kdbx: not a plain file

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.6.0
Revision: 0765954

[NOTE]: # ( Pick choices based on your environment )
Operating System: Ubuntu 20.04
Desktop Env: Gnome
Windowing System: X11

## Suggestion
If network paths via CLI aren't supported yet, a more meaningful error message would result in better user experience, like :
`Network paths for CLI aren't supported yet.`

**Comment by droidmonkey** [comment]
You need to enable media access because you are using the snap

**Comment by bela53** [comment]
Thanks, could you elaborate a bit further on that? If you mean /media folder permission: these should fit, as both keypassxc process and mount point are started/initiated by `user`. How can I check, if a plugin is missing?

**Comment by droidmonkey** [comment]
https://keepassxc.org/docs/#faq-appsnap-homedir

**Comment by bela53** [comment]
The example above is a bit contrived for illustration - in real environment, I mount the network shares inside `/home/user/share`. I think, your linked FAQ entry actually has been the reason to do it this way (circumvent snap restrictions).

I changed the option to be checked, unfortunately with no effect.

**Comment by yash-fn** [comment]
I am having the same problem. Seem keepassxc.cli is subject to different snap sandboxing regarding network and I cannot find a way to change it for just the cli. regular gui works fine though. Perhaps the package should be split into two snaps?

**Comment by droidmonkey** [comment]
Just use the appimage or ppa for this use case

**Comment by yash-fn** [comment]
Oh didn't know about the app image. Thanks!
