### ISSUE TITLE
Palette support is disabled. Blank Icons

### ISSUE THREAD

**Issue by Ogurezzz** [keepassxreboot/keepassxc#5200]
Almost all icons in program are blank.
I use PPA version.
![Снимок экрана от 2020-07-30 11-25-35](https://user-images.githubusercontent.com/11271441/88900002-6fecd080-d257-11ea-8df7-3e3340317beb.png)

Linux Mint 20 Cinnamon

`ogurezzz@Ozzz-AMD:~$ keepassxc
qt5ct: using qt5ct plugin
qt5ct: palette support is disabled
qt5ct: D-Bus global menu: no
QPainter::begin: Paint device returned engine == 0, type: 3
QPainter::setCompositionMode: Painter not active
qt5ct: D-Bus system tray: yes
QPainter::begin: Paint device returned engine == 0, type: 3
QPainter::setCompositionMode: Painter not active
QPainter::begin: Paint device returned engine == 0, type: 3
QPainter::setCompositionMode: Painter not active
`

**Comment by phoerious** [comment]
Pinned issue.
