### ISSUE TITLE
Interface for Secure Notes

### ISSUE THREAD

**Issue by CerebralFreeze** [keepassxreboot/keepassxc#5202]
## Summary
I am sure that many people have already asked this question.  Is the KeePassXC going to add a Secure Notes feature some time in the near future?  _If so, could you tell us aproximaltely when such a feature might be included into KeePassXC?_

I just completely terminated my LastPass account completely and I am totally now committed to KeePassXC.  LastPass had such a feature that was nice.  So, I was wondering if there would be a similar feature added to KeePassXC in the near future and when.

## Examples
An obvious example is if you like to store all the social security numbers and other private info for your family in one place so you can fill out forms.  You search for "social security" and out pops a large square box type of entry that provides info that consists of just a title and a large text box.  I think LastPass executes this function fairly well.  I'm sure a few other password managers execute it well too.

## Context
It's important because it's not really a login and password type of entry.  You can customize your entries to fit the current entry but it would be prettier if there was an actual entry that was customized for such information.

_Any info on when such a feature might be added?_

**Comment by varjolintu** [comment]
It could work if the browser extension would support filling any additional attributes added to the entry. There's a (probably stalled) PR here: https://github.com/keepassxreboot/keepassxc-browser/pull/722

**Comment by varjolintu** [comment]
An update: https://github.com/keepassxreboot/keepassxc-browser/pull/1023

**Comment by droidmonkey** [comment]
Covered by #8228
