### ISSUE TITLE
Build wiki page missing qrencode dependency

### ISSUE THREAD

**Issue by catleeball** [keepassxreboot/keepassxc#5203]
Ran through the [build steps on the wiki](https://github.com/keepassxreboot/keepassxc/wiki/Building-KeePassXC) and noticed the dependency `qrencode` may need be added to the list of dependencies. Encountered this [cmake error](https://gist.githubusercontent.com/catleeball/a7254769609dd58e1b6d5ca54c3d6ffd/raw/91f5b414ecace7f04d20a00a90737bf7d3007f5f/build.log) when trying to build without it using a minimal set of features for a MacOS appimage.

Didn't see if there was a good way to send a PR for wiki edits on github (not sure how to fork a wiki repo). Let me know if there's a process to follow for sending wiki edits. In lieu of that, there's a small [git diff here](https://gist.github.com/catleeball/2d296db75c342e45341465dabc3dde31).

-----

KeePassXC - v2.6.0
Revision: 71b05db
Operating System: macOS 10.15.5

**Comment by droidmonkey** [comment]
The environment setup instructions have this already https://github.com/keepassxreboot/keepassxc/wiki/Set-up-Build-Environment-on-macOS#install-the-required-dependencies

**Comment by catleeball** [comment]
Understood, I did see that in each OS's page afterward. Is there any reason to exclude `qrencode` from the list of dependencies on the main build page? Particularly if it's needed for all environments to build with.

**Comment by droidmonkey** [comment]
No, I'll include it, just want to make sure you are setting up the build env from the right instruction set.

**Comment by catleeball** [comment]
Oh, got it, thanks for clarifying. And no worries, I got it built. 🙂
