### ISSUE TITLE
Make it possible to Copy/Cut/Paste entries

### ISSUE THREAD

**Issue by NicolasGoeddel** [keepassxreboot/keepassxc#5204]
## Summary
The original Keepass has the functionality to copy/cut/paste entries with CTRL+SHIFT+C/X/V. This way you can easily copy entries and also whole folders/groups and paste them somewhere else. In principle it's works like the current clone mechanism but can clone one or multiple entries into every other group you want and can even clone whole groups.

## Examples
It did not create a picture to show off that feature because I think it is clear how it should work.

## Context
I have a machine with lots of Linux containers and if I create a new container I usually just clone the whole group consisting of credentials of an already existing container with all its entries and modify just a few fields so it matches my new container. In other cases I copy entries as a template from one group into a new group to have less work and to be consistent in my naming conventions.

**Comment by droidmonkey** [comment]
I don't like the idea of using the clipboard for this action, I do like the the idea though.

**Comment by NicolasGoeddel** [comment]
What about CTRL+Drag'n'Drop to copy selected files or groups?

**Comment by SirTwistDo** [comment]
Just a suggestion from a newbie: 
You can perhaps generate an internal session key and encrypt the whole clipboard entry.
Or (my favorite) put only the GUIDs into clipboard. 
This way, the user will have the experience of using ctrl-c/x/v, but without exposing the entry to other applications.

**Comment by droidmonkey** [comment]
#172
