### ISSUE TITLE
Attachments aren't included in XML exports

### ISSUE THREAD

**Issue by decadent** [keepassxreboot/keepassxc#5207]
## Overview

The database has attachments, but XML exported with the command-line tools has basically bupkis instead of them.

Consequently, if the database is re-imported, attachments are gone.

## Steps to Reproduce

1. Create a database (in the KDBX 4 format), add an entry, add attachment(s).
2. Export the database with `keepassxc-cli`.
3. Find bupkis instead of the attachment(s).

## Expected Behavior

Attachments are included in the exported XML—e.g. a comment for the issue #4233 notes this as the expected behavior. Hopefully they are also included with the rest of the data when re-importing.

## Actual Behavior

For an attachment, this is found in the XML:

```xml
<Binary>
	<Key>foobar.png</Key>
	<Value Ref="0"/>
</Binary>
```

Actual content of the attachment is nowhere in the whole XML. Size of the XML export with just one entry is about 3 KB whereas the test attachment itself was 300 KB.

In the re-imported db, the attachment is shown as present, but with the size of 0 bytes.

BTW: when importing, `keepass-cli` prints a cryptic message `Unmapped keys left`—perhaps this is related to the missing attachments? But maybe not, since a Qt warning is also in the output.

## Context

KeePassXC - Version 2.6.0
Revision: 0765954

Qt 5.15.0
Debugging mode is disabled.

Operating system: macOS High Sierra (10.13)
CPU architecture: x86_64
Kernel: darwin 17.7.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
 libgcrypt 1.8.5

Operating System: macOS

**Comment by decadent** [comment]
BTW, a bit offtopic quick question: if I export a database to XML and re-import it, am I *expected* to lose any (meta)data? E.g. editing history for an entry is there, but maybe there's something else that's not included in exports.

Asking because I'm trying to edit some data via XML without affecting the ‘last modified’ times, which is how I discovered the attachments bug.

**Comment by droidmonkey** [comment]
Kdbx4 attachments are not stored in the xml......

**Comment by decadent** [comment]
Huh, indeed, the 3.1 format has attachments exported. Weird arrangement.

Though, seeing as the `<Binary>` structure in the `<Entry>` seems to be identical in the two cases, perhaps KeePassXC could circumvent that limitation—possibly in the `<CustomData>` section. So that people aren't surprised by missing files and don't have to mess up the modification dates by re-adding the attachments by hand.
