### ISSUE TITLE
Missed translations in v2.6.0

### ISSUE THREAD

**Issue by Stephan-P** [keepassxreboot/keepassxc#5208]
The following text strings are not translated (into Dutch)(Dutch translation was complete at time of release)

- in Settings - OK/Cancel buttons
- in Unlock database - OK/Cancel buttons
- in Edit Entry - OK/Cancel/Apply buttons
- in Settings - Language - option System Default

I suspect that these are not yet present in Transifex

**Comment by Stephan-P** [comment]
Another one found:
- open website with browser
- log into some account
- go through the procedure to change the password (in my case my bank website forced me to update the password)
- After changing the password, KPXC-browser asks what to do with the changed credentials
- Update, of course
- Finally a small window appears (from KPXC?) requesting final confirmation
- Buttons Save and Cancel are not translated (and not yet in Transifex)

**Comment by droidmonkey** [comment]
Ok / Cancel and such are translated by Qt. Otherwise you need to go to transifex and translate. We dont track that here.

**Comment by Stephan-P** [comment]
I don't understand what you mean with "we don't track that here"
Is there a place where we can translate these QT-strings?

**Comment by droidmonkey** [comment]
All translation work is done on transifex, I have no context for your findings so I can't help you with the Qt problem.

**Comment by jose1711** [comment]
Seeing the same issue on my system (Arch Linux) with Slovak translation while Czech translation doing fine I did a comparison and found out that the OK/Cancel buttons translation is taken from `qtbase_[LANGCODE].qm`. So it looks like we'll need to check Qt5 manual on translation.
