### ISSUE TITLE
Path translation breaks recent database list

### ISSUE THREAD

**Issue by dmtucker** [keepassxreboot/keepassxc#5209]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

When I open a kdbx from [KBFS](https://book.keybase.io/docs/files) (e.g. `/keybase/private/dmtucker/path/to/the.kdbx`), keepassxc shows a translated path (e.g. `$XDG_RUNTIME_DIR/doc/somehex/the.kdbx`). This is not really a problem because I can unlock/modify the kdbx; however, the translated path is stored in the recent database list, and that path does not seem to be valid after reboot (because `somehex` changes).

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Create a kdbx on KBFS.
2. Open it in keepassxc.
3. Reboot.
4. Try to open the entry in "Recent Databases".

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

I expected to see the real path in the recent list, or at least be able to use whatever entry ends up there after rebooting.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

I cannot use the entry in the recent list after rebooting. I must re-Open it.

## Context
[NOTE]: # ( Give us any additional information you may have. )

I tried Googling this a little, and this is the most relevant result I could find: https://forum.snapcraft.io/t/home-path-is-translated-into-run-user-1000/15415/4

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.0
Revision: 0765954
Distribution: Flatpak

Qt 5.14.2
Debugging mode is disabled.

Operating system: KDE Flatpak runtime
CPU architecture: x86_64
Kernel: linux 5.4.0-7634-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.5

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: Gnome3
Windowing System: x11

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Pop
Description:	Pop!_OS 20.04 LTS
Release:	20.04
Codename:	focal
```

**Comment by droidmonkey** [comment]
This is similar to what happens when you try to open a GVFS hosted file, Qt sees `google-drive://passwords.kdbx` as something under the `/run/user/1000` directory that causes havoc with saving.

**Comment by phoerious** [comment]
Is this still an issue?

**Comment by droidmonkey** [comment]
There is no fix for this issue, it's really a qt problem imo. Closing.
