### ISSUE TITLE
Add PR #254 to a release

### ISSUE THREAD

**Issue by nabeelomer** [keepassxreboot/keepassxc#521]
PR #254 has been merged but doesn't seem to appear in any of the releases.

**Comment by xf-** [comment]
Is in milestone for 2.2.0 - compile master and it should be included

Milestone
https://github.com/keepassxreboot/keepassxc/milestone/2

**Comment by TheZ3ro** [comment]
Like @xf- said, that PR will be available in KeePassXC version 2.2.0.
We don't have a roadmap so we don't know when it will be released.

Closing
