### ISSUE TITLE
macOS: "Toggle Password" ⌘H keyboard shortcut doesn't work

### ISSUE THREAD

**Issue by dfabulich** [keepassxreboot/keepassxc#5211]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
In KeePassXC 2.6.0, when unlocking the database, you can click the eye icon to toggle showing the password. If you hover your mouse over the eye, it says, "Toggle Password ⌘H."

The ⌘H keyboard shortcut doesn't work on macOS.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Open a database on macOS.
2. Hover your mouse over the eye icon.
3. Press ⌘H.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Show or hide the password, as if you'd clicked on the eye.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
⌘H is a built-in macOS keyboard short cut that hides the current application. When you type ⌘H, KeePassXC disappears from the screen completely.

<img width="1181" alt="Screen Shot 2020-08-01 at 3 39 02 PM" src="https://user-images.githubusercontent.com/96150/89111651-4bd2f000-d40d-11ea-9e71-1e7ad8e45013.png">

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.0
Revision: 0765954

Qt 5.15.0
Debugging mode is disabled.

Operating system: macOS 10.15
CPU architecture: x86_64
Kernel: darwin 19.5.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
 libgcrypt 1.8.5

**Comment by droidmonkey** [comment]
Already fixed for 2.6.1
