### ISSUE TITLE
Bug? - Only navigating the group tree results in "Database was modified. Save changes?" dialog

### ISSUE THREAD

**Issue by Simplenuity** [keepassxreboot/keepassxc#5215]
## Overview
When I navigate the group tree in my database, i.e. click an arrow to see sub-groups, I'm getting the dialog box "Database was modified. Save changes?" when I want to quit Keepassxc, even without making any change to any database entry.

## Steps to Reproduce
1. Open a database that contains at least one group with sub-groups
2. Click on the arrow next to the group to see the sub-groups
3. Choose to quit Keepassxc

## Expected Behavior
Keepassxc will be quit without any further dialog.

## Actual Behavior
I get presented the dialog "Database was modified. Save changes?" even if I didn't change any entry and the "Save" icon is still grayed out.

## Context
n.a.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.0
Revision: 0765954

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: XFCE
Windowing System: X11

Dialog even with grayed out Save icon:
![save_changes_dialog](https://user-images.githubusercontent.com/13347943/89124997-7ab79780-d4db-11ea-8779-204f32b46ae5.jpg)

**Comment by droidmonkey** [comment]
See #5210
