### ISSUE TITLE
Program crashes after auto-downloading Icon(s)

### ISSUE THREAD

**Issue by MrUserMan** [keepassxreboot/keepassxc#5218]
## Overview
Within a few seconds of downloading the icon of a website (using the 'Download FavIcon' menu item) the program crashes. On restarting the program, the database appears undamaged (phew!) and the new icon is present.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Choose an entry currently without Favicon (default 'key' icon)
2. Select 'Download Favicon'
3. On successful download, click 'Close'
4. Program immediately crashes with error window:

KeePassXC: Windows - Application Error
The instruction at 0x0000000001392734 referenced memory at 
0xFFFFFFFFFFFFFFFF. The memory could not be read. 
Click on OK to terminate the program

5. However, this does not happen every time and up to now I have used this function with no problem.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Expected it not to crash :)
Expected newly downloaded icon to be applied to the current entry - on restarting, it is present.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
See 'Steps to reproduce'

## Context
[NOTE]: # ( Give us any additional information you may have. )
KeePassXC 2.6.0
Windows 10 Home, version 2004
HP Pavilion Laptop.
Earlier I had deleted a duplicate favicon - could perhaps an index have got corrupted?

I can't think of anything else of relevance.
My database is quite large and is occasionally used by the original KeePass program, but there's never been a problem afterwards.
Sorry, I'm just a user. I hope this info is sufficient.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.6.0
Revision: 0765954

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 10 Home
Desktop Env: Windows
Windowing System: er, Windows?

**Comment by droidmonkey** [comment]
This is fixed in 2.6.1 to be released soon
