### ISSUE TITLE
Remove or decrease the minimum window size constraints

### ISSUE THREAD

**Issue by milankni** [keepassxreboot/keepassxc#522]
KeePassXC window cannot be made smaller than 580 x 680 px (cca).

## Expected Behavior
The user should be able to resize the window to smaller area, especially the height (say: 580 x 300 px). The decision on usability of such a window size should be left up to the user.

## Current Behavior
In Mate and Gnome 3 (Arch Linux) with a screen size 2560 x 1440 px, I can freely resize the window to be larger than the minimum size. It cannot be made smaller, though - see the screenshots.
![01 kpxc - list](https://cloud.githubusercontent.com/assets/937861/25302522/097ed2fa-2740-11e7-9f23-27187b7de951.png)
![02 kpxc - data entry](https://cloud.githubusercontent.com/assets/937861/25302524/162df922-2740-11e7-98b4-f1627812aaef.png)

## Possible Solution
Set lower limits for window size.

## Your Environment
KeePassXC - Version 2.1.4
Revision: 70bd598ead950ae8be8ddcdf8f5eb1595033cc2a

Libraries:
- Qt 5.8.0
- libgcrypt 1.7.6

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 4.10.8-1-ARCH

Enabled extensions:
- KeePassHTTP
- Auto-Type
- YubiKey

**Comment by phoerious** [comment]
I don't see how this would be useful. But I see it often enough that fir done reason window managers ignore Suze hints and then you end up with an unusably small window.

**Comment by droidmonkey** [comment]
I don't agree with this request.

**Comment by milankni** [comment]
If the limitation is on purpose and you guys think it causes less troubles than the possibility to set any size as per user's needs, I am fine with your decision.

**Comment by phoerious** [comment]
I think the minimum size is sensible. The window isn't usable at smaller sizes and things are likely to break.

**Comment by RienNeVaPlus** [comment]
I have a dedicated space for KeePass on my screen. However KeePassXC's minimal size takes up almost twice as much space.
I'd be very happy to have the ability to shrink the window further down. I'm no expert, but it seems like the only limitation is the icon bar, which could be hidden / moved into a burger menu. Everything else seems to be responsive.

**Comment by mfally** [comment]
I had the same bothering issue. Solved it by going to "View->Themes->Classic (Platform native)". 
KeePassXC 2.6.4, on Ubuntu 18.04

**Comment by slapcodes** [comment]
Thanks mfally, this was driving me nuts! This is a part of KeePassXC and proves the window size can be smaller. I need a smaller window so I can see more of what I am working on. The default window size takes up way too much real estate. Almost went back to the clunky OG KeePass until I saw this post.
