### ISSUE TITLE
Add a password quality check for the database password

### ISSUE THREAD

**Issue by Noir-** [keepassxreboot/keepassxc#5220]
## Summary
When creating a new database, there're the plain password input fields without any quality checks. But the choice of this password is very essential since the secrecy of all the credentials depends on this password. Therefore there should be a quality check in place to guide the user with creating the password. The user _could_ already do that in the password generator but the chances are good that we have a first-time user who doesn't even know how to handle that. It's also pretty counter-intuitive because auto-generating a password is not what a user wants in most cases.

## Examples
I think having this bar under the first input field would help in the first place.
![image](https://user-images.githubusercontent.com/6486186/89218079-b2067100-d5cd-11ea-8904-703890b9e00e.png)

Bonus: But there could be some very simple hints for making the password better as well. It could be very generic like "add more length" or "avoid common patterns". This addition could be helpful in the other places where password strength is measured as well but might be subject for a separate request tho.

## Context
I'm dealing with a lot of users who are not tech-savvy in non-profit organizations and in private life. I tell them a lot about (password) security and most of them are trying their best in doing things better. But it would help everyone having a tool at hand which makes it easier to follow these best practices.

**Comment by droidmonkey** [comment]
Good ideas, this is technically a duplicate request but I love your writeup.

**Comment by Noir-** [comment]
Thank you! :)
I'm planning to get involved into this and this looks like a low-hanging fruit.

**Comment by tunbridgep** [comment]
The master password should also show in the health report if it's weak or used within the database itself
