### ISSUE TITLE
Change the default word separator in the passphrase generator to something different than space

### ISSUE THREAD

**Issue by Noir-** [keepassxreboot/keepassxc#5221]
## Summary
In a perfect world, a website would accept any password as long as it's strong enough. (Now please don't argue that in a perfect world we wouldn't need passwords at all :stuck_out_tongue_winking_eye: ) In reality, each service has it's own weird policy with allowed chars. And in a (still) surprisingly high amount of cases, the space character isn't allowed in a password.

## Examples
I'd pledge for `.`, `_`  or `-` as they seem to be widely accepted.  I think `_` would be the most readable but it requires slightly more effort for typing. From this perspective, `.` would be the best option when we also consider different keyboard layouts.

## Context
It would help to ease the UX and might prevent some pain for the users dealing with shitty password policies. But I also think we should keep it how it is on existing installations because it's hard to tell what the user is actually used to.

**Comment by droidmonkey** [comment]
Once changed the separator is remembered for future use so I don't see this as a problem. This is one of those situations where there is no consistently right choice so we make a choice. A space is the traditional separator for passphrases.

**Comment by adudek16** [comment]
if you want to use a passphrase but the website doesn't allow spaces.  If this is user definable and the default is a space, what is the issue? I, for one, would like to be able to change the separator to any one of the usable characters on my keyboard.

**Comment by droidmonkey** [comment]
It can be changed trivially in the passphrase generator.
