### ISSUE TITLE
Add the possibility to add a second panel and compact panel, for Notes

### ISSUE THREAD

**Issue by SmootheSmooth** [keepassxreboot/keepassxc#5223]
Hello,

I use KeePassXC (2.6.0) AppImage on my Linux Notebook.

Currently KeePassXC shows only the main view of the database in three main partitions.

The problem is there is no way to add an extra panel on the left or right side because of notes.

Sometimes I have very long notes and this "preview panel" is too small.

It would be very good if this extra panel for notes also has the possibility to edit and save the notes directly. It should also show the creation time and modified time.

**Comment by droidmonkey** [comment]
We are not going to add another panel to the UI, sorry about that.

**Comment by SmootheSmooth** [comment]
I meant only as a way to add an additional panel. by default it is disabled.

Is there an extension or something like that to solve the problem? Maybe another KeePass software on Linux?

Currently I always have to go into edit mode for long notes to view only my notes. But this is not user friendly. Too many unnecessary clicks.

**Comment by droidmonkey** [comment]
Not that I'm aware of. KeePass in general is not meant to store/present extremely long notes. However, perhaps with entry templates you could have a "secure note" template that would be just for notes

**Comment by SmootheSmooth** [comment]
My notes are not long, the longest notes have as many words as the conversation here. That is very little.

I tried that already, too many clicks, too small preview panel or don't see the other entries in edit mode (sometimes I just want to look at the notes).

**Comment by droidmonkey** [comment]
What screen resolution are you running? Seems like you have a tiny screen.

**Comment by SmootheSmooth** [comment]
> What screen resolution are you running? Seems like you have a tiny screen.

Yes, the maximum screen resolution is 1366 x 768.

**Comment by droidmonkey** [comment]
That is your main problem unfortunately

**Comment by SmootheSmooth** [comment]
But also on my Desktop PC (Linux) with higher resolution (Full HD) is the same result. The main view with three main partitions generally too small.

In the future, the resolution will increase to 4K (by default), and I think the KeePassXC view concept is not optimized for this. The current views are outdated and not elegantly well solved for notes.

For the other areas, like entry selection and groups is well done, but not for notes.
