### ISSUE TITLE
KeepassXC 2.6.0 requests for 'Screen Recording' permission on MacOS Mojave

### ISSUE THREAD

**Issue by veysiertekin** [keepassxreboot/keepassxc#5224]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
KeepassXC requires `Screen Recording` permission that introduced at macOS Catalina, because of that it constantly opens system preference dialog

<img width="1287" alt="Screen Shot 2020-08-04 at 11 50 56" src="https://user-images.githubusercontent.com/500893/89274322-6f827a00-d649-11ea-9cba-049860ab63c0.png">

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Open KeepassXC on Mojave and unlock database
2. Open browser and press global shortcut
3. Permission dialog will open.
4. Even if you give `Accessibility` permission, it will constantly open a dialog says that it requires `Accessibility` and `Screen Recording` permission which is `Screen Recording` not available on Mojave

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

Should open entry selection dialog

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

Fails with `Screen Recording` permission

[NOTE]: # ( Paste debug info from Help → About here )
## Program Specs
KeePassXC - Version 2.6.0
Revision: 0765954

Qt 5.15.0
Debugging mode is disabled.

Operating system: macOS Mojave (10.14)
CPU architecture: x86_64
Kernel: darwin 18.7.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
 libgcrypt 1.8.5

[NOTE]: # ( Pick choices based on your environment )
## System Specs
Operating System: macOS Mojave 10.14.6

**Comment by phoerious** [comment]
Of you don't have the permission, you need to restart your Mac.

**Comment by veysiertekin** [comment]
Hi @phoerious ,

Thank you. Strangely restart solved the problem, may be this can be detailed in the dialog;

```
... If you have already granted permission, you may have to restart KeePassXC or your system.
```

How you manage such transcript changes? I can change this in English and Turkish transcripts, but can't do for the rest.

**Comment by droidmonkey** [comment]
Transifex handles translations.
