### ISSUE TITLE
Allow relative path for external SSH keys

### ISSUE THREAD

**Issue by Adirelle** [keepassxreboot/keepassxc#5225]
## Summary
Consider any relative path in the "external file" field for a SSH key to be relative to the directory containing the database file.

Note: for safety reason, it could be necessary to prevent accessing files outside the directory containing the database file.

## Examples
If my database is in `/home/user/KeePass/master.kdbx`, a path of `ssh/mykey.id` or `./ssh/mykey.id` would be resolved to " `/home/user/KeePass/ssh/mykey.id`.

## Context
I am using KeePassXC on both Windows and Linux, using SeaFile to keep them in sync. There are stored in totally different places, but the local directory structure is preserved by SeaFile.

On Linux, I am using the path to the key files in the SSH configuration (IdentityFile) to automatically select the right key for the right server, so I cannot store them as attachments.

**Comment by droidmonkey** [comment]
Does {DB_DIR} work in that field?

**Comment by hifi** [comment]
Interestingly I mentioned this a while ago when wondering if this specific use case would be a common one.

The key file path supports env substitution in 2.6.0 and it was tweaked a little for 2.6.1.

Adding another substitution method to the same field wouldn't be a good idea but I was thinking of adding a global option which would set if the relative path is from the runtime directory (current behavior, also KeeAgent) or from the database path.

**Comment by Adirelle** [comment]
> The key file path supports env substitution in 2.6.0 and it was tweaked a little for 2.6.1.

If you refer to https://github.com/keepassxreboot/keepassxc/commit/7c39907251a73e91b81f2ae8cc3e0703cb494933, it looks interesting.
