### ISSUE TITLE
KeePassXC 2.6.0 forgets the "Hide Passwords" setting each time it's started

### ISSUE THREAD

**Issue by davidekelly** [keepassxreboot/keepassxc#5229]
Hi, I run KeePassXC 2.6.0 with the "Hide Passwords" setting in the main display headings disabled, so that the password for each item is displayed. However, each time I restart KeePassXC, it hides the passwords and I have to again disable "Hide Passwords". I've searched for a setting that would instruct KeePassXC to remember these column settings, but I can't find one. Can KeePassXC please remember the chosen display window column settings. Thank you.

**Comment by droidmonkey** [comment]
This is by design, it was changed in 2.6.0. This is a duplicate request.
