### ISSUE TITLE
How to use KeepassXC with Yubikey HMAC-SHA1?

### ISSUE THREAD

**Issue by minthemiddle** [keepassxreboot/keepassxc#523]
I'm using KeePassXC 2.1.4 on macOS Sierra 10.12.4. In the about window I read "Extensions: … - Yubikey". My Yubikey is inserted and works flawlessly. But in KeePassXC I cannot find any place where I could use the Yubikey, not in the master key settings (1), the database settings (2) nor anywhere in the "Preferences" settings.

I could not find any documentation on how to use Yubikey with KeepassXC.

How can I get started?

(1)
![screen shot 2017-04-22 at 12 27 06](https://cloud.githubusercontent.com/assets/1950766/25303607/1079a96a-2757-11e7-9b67-e427cc010a83.png)

(2)
![screen shot 2017-04-22 at 12 28 16](https://cloud.githubusercontent.com/assets/1950766/25303618/394c55c2-2757-11e7-81b5-2010781e8db6.png)

**Comment by weslly** [comment]
KeePassXC 2.1.4 doesn't support Yubikey yet, you should either compile the develop branch or wait until v2.2.0 is released.

**Comment by minthemiddle** [comment]
Convincing answer. I just thought so as it is already in the `readme.md`.
