### ISSUE TITLE
Wrong mouse position when working with multiple monitors

### ISSUE THREAD

**Issue by Snakey26** [keepassxreboot/keepassxc#5230]
## Overview
I work with two monitors. One is my notebook monitor, the other an external one which I sometimes unplug. Often KeepassXC gets into a state where it does not recognize the mouse position correctly. All mouse clicks work on a position that is shifted to the left (i.e. I have to click further to the right to perform an action).

## Steps to Reproduce
1. Start KeepassXC on a system with 2 monitors (mine have different size) and open the database. Keepass is open on the first monitor.
2. Minimize KeepassXC
3. Unplug the first monitor
4. Plug the first monitor in again
5. Open KeepassXC. Mouse behaviour is buggy now.

## Expected Behavior
All mouse clicks should have an effect at the position where I click.

## Actual Behavior
All mouse clicks have their effect as if I clicked further to the left.

## Context

KeePassXC - Version 2.6.0
Revision: 0765954

Qt 5.15.0
Diagnosemodus ist deaktiviert.

Betriebssystem: Windows 10 Version 1903
CPU-Architektur: x86_64
Kernel: winnt 10.0.18362

Aktivierte Erweiterungen:
- Auto-Type
- Browser-Integration
- SSH-Agent
- KeeShare (bestätigtes und unbestätigtes Teilen)
- YubiKey

Kryptographische Bibliotheken:
 libgcrypt 1.8.5

**Comment by droidmonkey** [comment]
Definitely a Qt bug.

**Comment by droidmonkey** [comment]
Possibly this one: https://bugreports.qt.io/browse/QTBUG-62149
