### ISSUE TITLE
garbled icon in add / edit screen

### ISSUE THREAD

**Issue by mx1up** [keepassxreboot/keepassxc#5231]
## Overview
Just upgraded KeepassXC on windows to 2.6.0 and noticed a weird problem with the icon/character on the add/edit screen. See screenshot.
![kxc_bug](https://user-images.githubusercontent.com/178714/89463585-72778a80-d76f-11ea-9048-61b534371e34.png)
I did not experience this issue on linux.

## Steps to Reproduce
1. open DB
2. add entry

## Expected Behavior
no garbage between "Root" and "Add entry"

## Actual Behavior
garbage between "Root" and "Add entry"

## Context
I upgraded from an older version?

KeePassXC - Version 2.6.0
Revision: 0765954

Qt 5.15.0
Debugging mode is disabled.

Operating system: Windows 7 Version 6.1 (Build 7601: SP 1)
CPU architecture: x86_64
Kernel: winnt 6.1.7601

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.5

Operating System: Windows

**Comment by droidmonkey** [comment]
Same as #5025

**Comment by mx1up** [comment]
thanks for caring :) This is my laptop from work and due to circumstances I have not been able to upgrade. New laptop with win10 is incoming this month though :crossed_fingers: 
I will verify on my desktop too which has win10

So, I guess it's not really an icon then but a unicode char rendering issue somehow?

**Comment by droidmonkey** [comment]
Yes exactly
