### ISSUE TITLE
Delete entry without confirmation: Config option

### ISSUE THREAD

**Issue by minidisk1147** [keepassxreboot/keepassxc#5232]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
Add a configuration option to allow  deletion of entries without confirmation dialog.

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
  * The confirmation dialog makes it very annoying to clean up the database from a large amount of obsolete entries.
  * When the recycle bin is used, you can recover the entry anyway

**Comment by droidmonkey** [comment]
You can multi select and delete many at a time, but agree.
