### ISSUE TITLE
Favicon Crash with automatically save enabled

### ISSUE THREAD

**Issue by Kellett** [keepassxreboot/keepassxc#5234]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
Crash when you download a favicon and close the window before the database has saved

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Turn on "Automatically save after every change"
2. Right click an entry that has a url and no favicon already and choose "Download Favicon"
3. As soon as the Status field on the popup window says OK click "Close"

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
The "Download Favicons" popup should close

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
The app crashes

## Context
[NOTE]: # ( Give us any additional information you may have. )
This seems to be because my database takes a second or two to save and if I close the window while it is saving in the background it causes the crash

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.0
Revision: 0765954

Qt 5.15.0
Debugging mode is disabled.

Operating system: Manjaro Linux
CPU architecture: x86_64
Kernel: linux 5.4.52-1-MANJARO

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.6

**Comment by droidmonkey** [comment]
Already fixed
