### ISSUE TITLE
Interface icons are not displayed

### ISSUE THREAD

**Issue by airosa-id** [keepassxreboot/keepassxc#5235]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
Interface icons are not displayed

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Just install and run

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
app is run without error but interface icons are not displayed

## Context
[NOTE]: # ( Give us any additional information you may have. )
Qt 5.12.8
Linux Mint 20
CPU: x86_64
Kernel: linux 5.4.0-42-generic
libgcrypt 1.8.5

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.6.0
Revision: 0765954

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: Cinnamon
Windowing System: X11

**Comment by airosa-id** [comment]
Interface icons are not displayed
![screen-2020-0806_183846](https://user-images.githubusercontent.com/10205470/89552054-51b54080-d814-11ea-8c54-4c1c41ebec1d.png)

**Comment by vkhikhlov** [comment]
I have the same issue.

**Comment by droidmonkey** [comment]
Pinned issue...

**Comment by airosa-id** [comment]
oh my what is a shame! sorry.
