### ISSUE TITLE
Allow the three main partitions to be displayed as Side by Side

### ISSUE THREAD

**Issue by SmootheSmooth** [keepassxreboot/keepassxc#5236]
## Summary
Currently in KeePassXC 2.6.0 it is only possible to display the three main partitions as stacked.

There is no function to display the three main partitions as Side by Side.

## Examples
I have no mockup. Sorry.

## Context
Side by Side has the advantage that I can adjust the three main partitions equally.

If it is stacked, the problem for me is that the preview panel is too small, or if I make the preview panel larger, it hides the entries too much.

**Comment by SmootheSmooth** [comment]
Can you add that in the future?

**Comment by droidmonkey** [comment]
Possibly

**Comment by droidmonkey** [comment]
We will not be implementing this feature

**Comment by homhom1416** [comment]
I think you should revive this issue ... why not !?

**Comment by turmoggy** [comment]
Yes it needs an option for side by side ui layout. I find it more functional than bottom view.
