### ISSUE TITLE
Database kdbx on USB cannot be accessed Ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by freturn13** [keepassxreboot/keepassxc#524]
## Expected Behavior
One should be able to use Database on external drive
Database on external dive should be accessable
## Current Behavior  
Database kdbx on external drive is not accessable
I had to copy database to Desktop and then open it there
## Steps to Reproduce
1. Install keepassxc on Ubuntu 16.04 LTS
2.Install Database kdbx on external drive
3.Access database on external driv
## Context
I will not be able to use keepassxc for the time being
## Your Environment
Using Ubuntu16.04 LTS (latest)
I downloaded keepassxc from Ubuntu Software

**Comment by droidmonkey** [comment]
Known issue already, thanks
