### ISSUE TITLE
Extreme memory usage

### ISSUE THREAD

**Issue by dataviruset** [keepassxreboot/keepassxc#5240]
## Overview
My KeePassXC process is using a lot of memory.

## Steps to Reproduce
It seems to happen directly after opening it, even before unlocking my password database.

## Expected Behavior
I'd expect it to consume much less memory, maybe not more than 100 MiB or so.

## Actual Behavior
It was consuming 1.6 GiB.
```
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
oskar     6468  0.0 10.0 2456700 1636148 ?     SLl  11:02   0:13  |   \_ /snap/keepassxc/978/usr/bin/keepassxc -style fusion
```
Tried reinstalling and then it used 1.2 GiB instead even before opening or creating a password database.

## Context
KeePassXC - Version 2.6.0
Revision: 0765954
Distribution: Snap

Qt 5.9.5
Debugging mode is disabled.

Operating system: Ubuntu Core 18
CPU architecture: x86_64
Kernel: linux 5.3.0-64-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.1

Operating System: Ubuntu 19.10
Desktop Env: Gnome
Windowing System: X11

**Comment by phoerious** [comment]
Do you have a high-DPI screen?

**Comment by dataviruset** [comment]
> Do you have a high-DPI screen?

Yes, two screens, 2560x1600 and 3840x2160. Fractional scaling enabled on both, 150%.
