### ISSUE TITLE
Problems Saving And Closing KeePass File

### ISSUE THREAD

**Issue by Lako29** [keepassxreboot/keepassxc#5242]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

Since the new update, when I add a new entry to my keepass database, there's an error notification claiming 'Destination file exists, back-up file stored in C:\Users\AppData\Local\Temp'. When I want to close my keepass window, a popup appears asking me whether I want to keep the changes or discard them. If I press 'Save', then the popup dissapears but the window does not close. The new entry ends up not being saved.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Add a new entry in an existing document.
2. Save the entry. 
3. Close the window.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

It should save new entries without error messages appearing, and I should be able to save and close the file.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

See Description

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION 2.6.0.
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 10
Windowing System:

**Comment by droidmonkey** [comment]
Are you trying to save to a read only file

**Comment by Lako29** [comment]
Not trying to save to a read only file/to cloud storage; and safe saves is disabled. I'm only saving changes to an existing, local kdbx file.

**Comment by droidmonkey** [comment]
The error indicates keepassxc cannot write to the file. Try renaming the existing kdbx and saving.

**Comment by Lako29** [comment]
I did that, it's still not working. Tried also saving the file under a different name, it does not want to save, giving me an error 'could not find the file, please check again'. It's weird, as if it is searching for an existing file rather than saving one. Also tried deleting KeePassXC and re-installing, didn't help.

Weird, never had these problems before the last update. Any other ideas? Thanks for the help in any case.

**Comment by droidmonkey** [comment]
To rule out the update try running previous version as portable

**Comment by Lako29** [comment]
Where do I find a previous version?

**Comment by droidmonkey** [comment]
https://github.com/keepassxreboot/keepassxc/releases

**Comment by Lako29** [comment]
Done, it still doesn't work. Also downloaded KeePass (not KeePassXC) to check, same error shows up. So the update is ruled out. Seems perhaps the file is corrupted or something :/

**Comment by droidmonkey** [comment]
Definitely on your end, sorry mate

**Comment by droidmonkey** [comment]
Could be virus scanner, maybe, interfering with operations.

**Comment by willuhn** [comment]
I had the same problem. Was caused by windows' controlled folder access. Make sure, you don't store the file in one of the protected folders - https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/controlled-folders

**Comment by Lako29** [comment]
I fixed it in the meantime. My windows firewall was blocking me from saving the files.

-- 
 Sent with Tutanota, the secure & ad-free mailbox: 
 https://tutanota.com


Feb 27, 2021, 12:40 by notifications@github.com:
