### ISSUE TITLE
Please allow adjusting screen width and removing group window pain

### ISSUE THREAD

**Issue by wolfsage** [keepassxreboot/keepassxc#5243]
Hi folks. I'm still using keepass 0.4.4 because a lot of the newer changes have not worked with my use of keypass, but keeping this old version running is incredibly painful.

Specifically: I don't want the group pain as I don't use it and it takes up valuable real estate.

But more importantly, I want to be able to adjust my windows to whatever width I want.

The default settings are horrible for me. I open up keepass and shrink it to a very tall, very thin window, where I can see the name of the entries and nothing else. I leave this on the right side of my screen where it's out of the way unless I need it.

I can't think of any other applications out there that require a minimum screen size as large as this, or any minimum sizes at all really.

I would love to see this changed.

Thanks.

**Comment by droidmonkey** [comment]
You are going to need to find a new application because we won't support that.  Hiding group pane maybe

**Comment by wolfsage** [comment]
I've got to admit I'm surprised by the response because allowing an application to be resized arbitrarily seems like pretty basic functionality.

But thanks for the response.

**Comment by droidmonkey** [comment]
You're welcome to set that up yourself, the setting is in MainWindow.ui but some other widgets may restrict minimum size of the window. The application is not setup to be responsive so shrinking the window so small will break basically everything.

**Comment by wolfsage** [comment]
Thanks for the helpful response. I see now part of what the problem is - the widgets are all opened in the main window instead of separate ones like they used to be, bummer.

Okay, well this gives me something to go on at least.

I really appreciate it.

Cheers

**Comment by digimeas** [comment]
Hi @droidmonkey ! Where is this MainWindow.ui of which you speak? It doesn't seem to be part of the PPA. Can it be stuck somewhere where KPXC can see it?
Thanks, Doug

**Comment by droidmonkey** [comment]
Its part of the source code
