### ISSUE TITLE
Dark title bar on Windows when in dark mode

### ISSUE THREAD

**Issue by lazylazyllama** [keepassxreboot/keepassxc#5244]
## Summary
Right now the title bar of keepassxc is always white in windows. Even when keepassxc is in dark mode.
A dark app with a white title bar looks kind of strange.
So it would be nice, if the title bar in keepassxc would match the theme in Windows.

**Comment by droidmonkey** [comment]
We can't fix this, Windows provides no adequate API for C++ applications. We tried.

**Comment by phoerious** [comment]
I will give it another try, but I cannot promise anything.
