### ISSUE TITLE
Crash when passing a wildcard to some CLI commands on Windows

### ISSUE THREAD

**Issue by Still34** [keepassxreboot/keepassxc#5245]
# Summary

If a wildcard character (`*`) is passed into the `keepassxc-cli show` or `keepassxc-cli locate` command, the application crashes before a password prompt is shown. The same behavior cannot be reproduced on a headless Linux system (at least for WSL)

![image](https://user-images.githubusercontent.com/5843208/89713887-5e30c900-d9cd-11ea-939e-b59ffd7901a2.png)

## Expected Behavior

1. `keepassxc-cli [show|locate] dummy.kdbx *`
2. All entries in the database are shown

## Actual Behavior 
1. `keepassxc-cli [show|locate] dummy.kdbx *`
2. Instant crash

**Comment by SleepyTheDank** [comment]
ok

**Comment by droidmonkey** [comment]
Confirmed, the crash occurs when the help text attempts to be displayed.

**Comment by droidmonkey** [comment]
This is actually a Qt bug, requesting the arguments list with any number of "*" in the positional args causes a crash.

**Comment by droidmonkey** [comment]
Opened a bug report with Qt: https://bugreports.qt.io/browse/QTBUG-87441
