### ISSUE TITLE
Display error in cinnamon 

### ISSUE THREAD

**Issue by mlopezcoria** [keepassxreboot/keepassxc#5246]
Description:

After updating keepassxc 2.5.4-2 -> 2.6.0-1 some interface component are not correctly displayed, like text boxes, buttons, etc.

Additional info:
* Cinnamon 4.0.8-1.0

Steps to reproduce:

Open KeePassXC
![Screenshot from 2020-07-22 09-27-48](https://user-images.githubusercontent.com/15494802/89720779-5a407f00-d9ac-11ea-900b-298b8bc388d5.png)

**Comment by droidmonkey** [comment]
Pinned issue...
