### ISSUE TITLE
Empty Key Not Allowed

### ISSUE THREAD

**Issue by Marksway** [keepassxreboot/keepassxc#5249]
## Overview
Unable to save base with empty key.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )

1. Database Security

2. Remove password

![1](https://user-images.githubusercontent.com/61252259/89747490-aaf8ca80-dac7-11ea-97f1-987ca21d3059.png)

3. Ok - Continue without password

![2](https://user-images.githubusercontent.com/61252259/89747494-b0561500-dac7-11ea-8760-8fdd760d3f39.png)

4. Error

![3](https://user-images.githubusercontent.com/61252259/89747500-b3e99c00-dac7-11ea-923a-5648a381daaf.png)

5.Base master key has not changed

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
The program must accept a user-selectable key value.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
An empty key is not accepted.

## Context
[NOTE]: # ( Give us any additional information you may have. )
* This does not apply to security issues as 1) there may be different reasons for specifying an empty key, 2) The program accepts a key in one character.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION 2.6.0

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 10

**Comment by droidmonkey** [comment]
Having no password and no key file and no yubikey is equivalent to having a text file.

**Comment by Marksway** [comment]
AND? Why can't user use base as a "text file", for example, as a directory of records?

**Comment by droidmonkey** [comment]
Just use excel then or a one character password like 'a'.
