### ISSUE TITLE
Strange UI issue on Linux AppImage

### ISSUE THREAD

**Issue by Emily7777** [keepassxreboot/keepassxc#5250]
## Overview
UI is not displaying correctly.

See:
![image](https://user-images.githubusercontent.com/28765920/89756304-22901f00-daf3-11ea-807c-85eacb98f5bb.png)

## Steps to Reproduce
1. Download Appimage on Linux PureOS 
2. Run Appimage.

## Expected Behavior
The UI correctly renders like 5.3 version did.

## Actual Behavior
See screenshot above ^^^.

## Context
This is the Appimage, run on Linux PureOS distro.

KeePassXC: KeePassXC-2.6.0-x86_64.AppImage

Operating System: Linux PureOS
Desktop Env: Gnome
Windowing System: Wayland

**Comment by droidmonkey** [comment]
This is a pinned issue, need to set the scaling Env vars or use a develop snapshot until 2.6.1 is released
