### ISSUE TITLE
Auto-Type can show a search window for database when it "Couldn't find an entry that matches the window title" ?

### ISSUE THREAD

**Issue by takeTrace** [keepassxreboot/keepassxc#5251]
## Summary
Can Add a search function in auto-type when it can't match any result by window title?
Because some times the active window title don't match the title I save in keepass, so the auto-type result can't show any result. If this time there is a Search Bar for type by my self and show the search result to choose will be a convenient point.

**Comment by droidmonkey** [comment]
Duplicate request
