### ISSUE TITLE
No Database Connection Microsoft Edge KeepassXC extension

### ISSUE THREAD

**Issue by BenKu82** [keepassxreboot/keepassxc#5253]
## Overview
KeepassXC Extension is not connecting to database in Edge.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Install KeepassXC extension from the store to Edge
2. Enable the browser integration for Edge
3. Try to connect to the open database

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Opening Browser Access Request. 

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Message:
Cannot connect to KeePassXC. Check that browser integration is enabled in KeePassXC settings.
![2020-08-11 15_04_37-Window](https://user-images.githubusercontent.com/26143943/89904946-d1af2200-dbe9-11ea-8211-0b77ca4ae4ab.png)

Message after clicking Reload:
Key exchange was not successful.
![2020-08-11 15_04_48-Window](https://user-images.githubusercontent.com/26143943/89904957-d673d600-dbe9-11ea-9fdf-87d0d7d0d446.png)

## Context
[NOTE]: # ( Give us any additional information you may have. )

- The file  ...\appdata\local\KeepassXC\org.keepassxc.keepassxc_browser_edge.json does exist.
- The registry value Default in HKEY_CURRENT_USER\Software\Microsoft\Edge\NativeMessagingHosts\org.keepassxc.keepassxc_browser does exist with he right path.

[NOTE]: # ( Paste debug info from Help → About here )
Debug info:
KeePassXC - unknown
KeePassXC-Browser - 1.6.6
Operating system: Win32
Browser: Microsoft Edge 83.0.478.61
_____________________
We are using KeepassXC 2.6.0

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 10 x64 1809 LTSC

**Comment by varjolintu** [comment]
Where does that path variable inside `...\appdata\local\KeepassXC\org.keepassxc.keepassxc_browser_edge.json` point to?

**Comment by BenKu82** [comment]
This is the content:
`
{
    "allowed_origins": [
        "chrome-extension://pdffhmdngciaglkoonimfcmckehcpafo/",
        "chrome-extension://oboonakemofpalcgghocfoadofidjkkk/"
    ],
    "description": "KeePassXC integration with native messaging support",
    "name": "org.keepassxc.keepassxc_browser",
    "path": "C:\\Program Files\\KeePassXC\\keepassxc-proxy.exe",
    "type": "stdio"
}
`

**Comment by varjolintu** [comment]
Is `keepassxc-proxy.exe` running when you start the browser?

**Comment by BenKu82** [comment]
Yes, it is running.
![2020-08-12 13_36_44-Task-Manager](https://user-images.githubusercontent.com/26143943/90010984-15b12e00-dca1-11ea-8279-77dc9ace2a6f.png)

**Comment by varjolintu** [comment]
In this case your only chance is to use https://docs.microsoft.com/en-us/sysinternals/downloads/procmon and find anything related to KeePassXC. It could show what registries and files Edge tries to load.

**Comment by BenKu82** [comment]
Ok, I made a run with Procmon.
Is it correct, that msedge.exe is searching in a Google Chrome registry path?
`High Resolution Date & Time:	12.08.2020 14:06:48,4952256
Event Class:	Registry
Operation:	RegOpenKey
Result:	NAME NOT FOUND
Path:	HKLM\SOFTWARE\WOW6432Node\Google\Chrome\NativeMessagingHosts\org.keepassxc.keepassxc_browser
TID:	16668
Duration:	0.0000399
Desired Access:	Query Value
`

**Comment by varjolintu** [comment]
No that's definitely not correct. But it's not the first time we've heard that Chromium-based browsers are searching for Chrome's registry paths.

Try to enable Chrome support in KeePassXC if that solves the problem.

**Comment by BenKu82** [comment]
Now I tested every possible constellation of activated and deactivated browser supports.
It does not solve the Problem. 
It´s funny. msedge.exe is search in both registry pathes. For Google Chrome and for Edge.
`High Resolution Date & Time:	12.08.2020 14:06:48,4947416
Event Class:	Registry
Operation:	RegOpenKey
Result:	NAME NOT FOUND
Path:	HKLM\SOFTWARE\WOW6432Node\Microsoft\Edge\NativeMessagingHosts
TID:	16668
Duration:	0.0000260
Desired Access:	Query Value
`

**Comment by varjolintu** [comment]
So, does it also look for `HKEY_CURRENT_USER\Software\Microsoft\Edge\NativeMessagingHosts` or just the registry paths under `WOW6423Node`? If so, you could try to copy the values from the first registry path.

**Comment by droidmonkey** [comment]
Why are you running 32 bit edge on 64 bit windows

**Comment by BenKu82** [comment]
In HKLM iit is searching for, but it does not exist.
In HKCU it is not search for, but it does exist.
We are running MS edge in 64bit on Win10 64bit.
Funny is, that Microsoft is still installing the 64bit version to Program Files (x86).
![2020-08-12 14_55_04-Process Monitor - Sysinternals_ www sysinternals com](https://user-images.githubusercontent.com/26143943/90017581-0a173480-dcac-11ea-82e2-dded8b205dd7.png)

**Comment by droidmonkey** [comment]
That's really odd

**Comment by gnr8shn** [comment]
I experience the same problem. Edge is installed in enterprise management mode however. Will that make an effect?

**Comment by phoerious** [comment]
Is "Isolated Browsing" via MS Defender Application Guard enabled?

**Comment by gnr8shn** [comment]
In my case (corporate computer with corporate MS Edge) Isolated Browsing is *not* installed.

**Comment by detharonil** [comment]
I believe I've found the issue.  Microsoft publishes security baselines for several of their products in the form of group policy objects (which we're applying at my company), and one of the policies therein is causing this problem.  User-level native messaging hosts are blocked in the baseline policy, which prevents Edge from searching HKCU for the manifest:

![image](https://user-images.githubusercontent.com/4337033/94155585-1a930100-fe4d-11ea-809e-6cebb09184c1.png)

I was able to publish the same path to HKLM, which got browser integration working, but this is definitely a hack:

![image](https://user-images.githubusercontent.com/4337033/94155961-88d7c380-fe4d-11ea-948c-81d67fedc7e1.png)

Creating a second configuration file at C:\ProgramData\keepassxc\org.keepassxc.keepassxc_browser_edge.json for KeepassXC during its installation with a matching registry entry in HKLM seems like a much cleaner solution, perhaps selecting specifically for installations by users with administrative privileges.

@gnr8shn You can verify that this policy is applying on your PC by asking your IT department or (if you have local admin rights), running `gpresult /h {filename}.html` in an elevated CMD or PowerShell session and reviewing the output.

**Comment by gnr8shn** [comment]
Hi  @detharonil gpresult showed the following:
Software\Policies\Microsoft\Edge\NativeMessagingUserLevelHosts | 0 | C - Microsoft Edge
The ADMX was not available so it's raw, but importantly the value is 0 which seems to align with "disabled".

I copied the setting from HKCU to HKLM which worked.

So a good result for those on non-shared machines with administrative privileges. A hack indeed, but we're trying to circumvent an administrative/corporate lockdown so this is fair.

Thanks for following this up!

**Comment by detharonil** [comment]
It looks like a few changes can be made to src/Browser/NativeMessageInstaller.cpp to make the non-portable version create the json files in C:\ProgramData and write the appropriate entries into HKLM instead of HKCU, but I'm not sure what changes would be needed to force KeePassXC to create all of the files at install time rather than when they are enabled in the UI.  Here's the diff, if it could be useful, but I won't make a pull request out of this due to its incompleteness:

<pre>
diff --git a/src/browser/NativeMessageInstaller.cpp b/src/browser/NativeMessageInstaller.cpp
index 8b038f61..15172fc5 100644
--- a/src/browser/NativeMessageInstaller.cpp
+++ b/src/browser/NativeMessageInstaller.cpp
@@ -52,16 +52,16 @@ namespace
     const QString TARGET_DIR_EDGE = QStringLiteral("/Library/Application Support/Microsoft Edge/NativeMessagingHosts");
 #elif defined(Q_OS_WIN)
     const QString TARGET_DIR_CHROME = QStringLiteral(
-        "HKEY_CURRENT_USER\\Software\\Google\\Chrome\\NativeMessagingHosts\\org.keepassxc.keepassxc_browser");
+        "HKEY_LOCAL_MACHINE\\Software\\Google\\Chrome\\NativeMessagingHosts\\org.keepassxc.keepassxc_browser");
     const QString TARGET_DIR_CHROMIUM =
-        QStringLiteral("HKEY_CURRENT_USER\\Software\\Chromium\\NativeMessagingHosts\\org.keepassxc.keepassxc_browser");
+        QStringLiteral("HKEY_LOCAL_MACHINE\\Software\\Chromium\\NativeMessagingHosts\\org.keepassxc.keepassxc_browser");
     const QString TARGET_DIR_FIREFOX =
-        QStringLiteral("HKEY_CURRENT_USER\\Software\\Mozilla\\NativeMessagingHosts\\org.keepassxc.keepassxc_browser");
+        QStringLiteral("HKEY_LOCAL_MACHINE\\Software\\Mozilla\\NativeMessagingHosts\\org.keepassxc.keepassxc_browser");
     const QString TARGET_DIR_VIVALDI = TARGET_DIR_CHROME;
     const QString TARGET_DIR_TOR_BROWSER = TARGET_DIR_FIREFOX;
     const QString TARGET_DIR_BRAVE = TARGET_DIR_CHROME;
     const QString TARGET_DIR_EDGE = QStringLiteral(
-        "HKEY_CURRENT_USER\\Software\\Microsoft\\Edge\\NativeMessagingHosts\\org.keepassxc.keepassxc_browser");
+        "HKEY_LOCAL_MACHINE\\Software\\Microsoft\\Edge\\NativeMessagingHosts\\org.keepassxc.keepassxc_browser");
 #else
     const QString TARGET_DIR_CHROME = QStringLiteral("/google-chrome/NativeMessagingHosts");
     const QString TARGET_DIR_CHROMIUM = QStringLiteral("/chromium/NativeMessagingHosts");
@@ -211,7 +211,7 @@ QString NativeMessageInstaller::getNativeMessagePath(SupportedBrowsers browser)
     if (QFile::exists(QCoreApplication::applicationDirPath() + QStringLiteral("/keepassxc.ini"))) {
         basePath = QCoreApplication::applicationDirPath();
     } else {
-        basePath = QStandardPaths::writableLocation(QStandardPaths::DataLocation);
+        basePath = QStandardPaths::standardLocations(QStandardPaths::AppConfigLocation).at(1);
     }
</pre>

The implications of that could also be ugly, as browser integration could only be globally enabled or disabled rather than selected for a given browser.  I'm not sure what to suggest beyond that.

**Comment by droidmonkey** [comment]
This is not the solution as it will break normal edge deployments (ie non managed). Given that managed deployments are controlled by sys admins, they should manually deploy the registry key to point to a valid json configuration file using GPO.

**Comment by varjolintu** [comment]
The custom browser option originally had a feature to add custom registry paths with Windows. Maybe we should try to bring it back and finish the feature?

**Comment by droidmonkey** [comment]
The problem here is that any competent IT department would have HKLM locked down for the users. They are not able to make changes to that part of the registry.

**Comment by detharonil** [comment]
If the program's installation requires admin privileges, then how would placing the .json files in C:\ProgramData and the pointers in HKLM break operation for typical users?  If KeePassXC is capable of accepting or rejecting browser plugin connections based on its configuration rather than the presence of these files, then why not let that be the point of control?  Sure, our IT department can modify the installation to perform the steps above, but I can't seem to figure out why it's not done that way from the start since the default installation of KeePassXC is multi-user.

**Comment by droidmonkey** [comment]
You are missing the point. We don't pre-install any registry keys for native messaging, they are controlled _by the user_. As a result, in order to support native messaging in a controlled computing environment (eg. HKLM registry) then it will need to be done by the system administrators.

**Comment by BenKu82** [comment]
Solution via GPO and software deployment:
1. Deploy the **org.keepassxc.keepassxc_browser_edge.json** to for example **C:\ProgramData\KeepassXC**
2. Set registry value: 
`Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Edge\org.keepassxc.keepassxc_browser]
@="C:\\ProgramData\\KeepassXC\\org.keepassxc.keepassxc_browser_edge.json"

`
3. Configure GPO options (Registry result):
`Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Edge]
"NativeMessagingUserLevelHosts"=dword:00000000

[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Edge\ExtensionInstallAllowlist]
"1"="pdffhmdngciaglkoonimfcmckehcpafo"

[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Edge\NativeMessagingAllowlist]
"1"="org.keepassxc.keepassxc_browser"`

@detharonil Thank you very much for your research result!

**Comment by droidmonkey** [comment]
We'll add that to the documentation

**Comment by phoerious** [comment]
That said, an installer option to pre-install these makes total sense.

**Comment by t3easy** [comment]
@BenKu82 

> [HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Edge\org.keepassxc.keepassxc_browser]

The path is [HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Edge\NativeMessagingHosts\org.keepassxc.keepassxc_browser]

**Comment by joaociocca** [comment]
any tips on fixing this for Edge on Linux? I'm having the same problem with KeePassXC 2.6.6 and Edge 97
![image](https://user-images.githubusercontent.com/6473725/146765162-abd6bc7e-15e7-495e-b831-84d68f40a371.png)
![image](https://user-images.githubusercontent.com/6473725/146765191-aca4c483-15d3-423c-81b6-b777cec74085.png)
![image](https://user-images.githubusercontent.com/6473725/146765205-fe275195-47eb-44e9-98e6-1790d38c59cb.png)
![image](https://user-images.githubusercontent.com/6473725/146765224-65f439ae-f651-488a-8c16-c909100295b1.png)
![image](https://user-images.githubusercontent.com/6473725/146765249-7d3a34ee-f7c5-4783-8410-edb49c11e9a6.png)

**Comment by droidmonkey** [comment]
Use the custom browser option under the advanced tab. We don't support beta browsers natively through the gui. Although they released a stable edge on Linux.

**Comment by joaociocca** [comment]
I had found [this article](https://www.initpals.com/linux/how-to-enable-keepassxc-plugin-for-microsoft-edge-browser-in-linux/) mentioning the custom browser field under the advanced tab, but mine doesn't have it?
![image](https://user-images.githubusercontent.com/6473725/146769222-a1b4615c-f153-413e-8851-ec533b43aae3.png)

Also, in the General tab, it only says that "browsers installed as snaps are currently not supported" and there are no checkboxes for "enable integration for these browsers", like shown in the article
![image](https://user-images.githubusercontent.com/6473725/146769469-cef4cba1-0026-49b8-9886-330ed663ba81.png)

While I do have bad memory, I don't remember installing Edge via snap (and bash history supports that, heh)

**Comment by varjolintu** [comment]
@joaociocca It should be on the advanced tab. Another solution is to copy or make a symbolic link of the JSON script file. Probably the path is something like `/microsoft-edge-beta/NativeMessagingHosts` instead of the default `/microsoft-edge/NativeMessagingHosts` under your `.config`.

**Comment by bsarrowood** [comment]
This helped me in 2024. Thank you. After updating KeePassXC within the last 3 days the browser extension started saying it couldn't connect to the database. When trying to reset the connection, both in the program and extension and restarting each program, the KeePassXC-Browser wouldn't respond when selecting Connect, nothing would pop-up to prompt anything. Additionally, removing the browser extension and reinstalling it didn't resolve.
After confirming everything else was configured, working and running properly, copying the regkey from current_user to local_machine and restarting the browser worked.

**Comment by detharonil** [comment]
@bsarrowood Glad the bruises on my forehead weren’t for nothing, lol

**Comment by biajf** [comment]
Hello,

I had the problem and I had apply the docs but isn't worked. 
In my case, I need to set NativeMessagingUserLevelHosts to 1 (enable) :
```
[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Edge]
"NativeMessagingUserLevelHosts"=dword:00000001 
```


This configuration active NativeMessagingUserLevelHosts policy (in doc value is to "NativeMessagingUserLevelHosts"=dword:0000000 and disable the NativeMessagingUserLevelHosts policy).

So, I use this config (you can apply key with .reg file) : 
```
Windows Registry Editor Version 5.00
[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Edge\NativeMessagingHosts\org.keepassxc.keepassxc_browser]
@="%userprofile%\AppData\Local\KeePassXC\org.keepassxc.keepassxc_browser_edge.json"

[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Edge]
"NativeMessagingUserLevelHosts"=dword:00000001

[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Edge\ExtensionInstallAllowlist]
"1"="pdffhmdngciaglkoonimfcmckehcpafo"

[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Edge\NativeMessagingAllowlist]
"1"="org.keepassxc.keepassxc_browser"
```

And extension works fine :)

**Comment by varjolintu** [comment]
That is also described in https://keepassxc.org/docs/KeePassXC_UserGuide#_advanced_setup. It is already linked in the Troubleshooting Guide.

**Comment by biajf** [comment]
Thanks @varjolintu for the link. I read the Troubleshooting guide (before post) and it 's write to set NativeMessagingUserLevelHosts to 0 and not 1 ;) . This configuration disable NativeMessagingUserLevelHosts (and extension not working in my case).

Extract from guide (in Configure GPO options (registry result) ) : 
```
[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Edge]
"NativeMessagingUserLevelHosts"=dword:00000000
```

In my case, I need to set this value (you have 1 at the end)  : 
```
[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Edge]
"NativeMessagingUserLevelHosts"=dword:00000001
```

**Comment by droidmonkey** [comment]
The guide is correct, but only if you have KeePassXC installed on the system. You (seem to) have it as a portable installation which would prevent you from using the native messaging host in a managed environment.

https://learn.microsoft.com/en-us/deployedge/microsoft-edge-policies#nativemessaginguserlevelhosts

**Comment by biajf** [comment]
Thanks @droidmonkey. KeepassXC is installed on the system by corporate tools and I think the package is installed only with user level (like a portable installation) and this explain why I need to activate NativeMessagingUserLevelHosts.

**Comment by clgsg** [comment]
Apparently, it all ads to:  the registry entry for Edge add-on is created in the HKEY_CURRENT_USER. To solve it, create a new org.keepassxc.keepassxc_browser key under HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Edge\NativeMessagingHosts\ and assign as a value the route to the configuring json file (C:/............/KeePassXC-2.7.9-Win64/config/org.keepassxc.keepassxc_browser_edge.json)

**Comment by droidmonkey** [comment]
If you have a managed browser then yah you need to do the work to manage it 😉 

https://keepassxc.org/docs/KeePassXC_UserGuide#_advanced_setup
