### ISSUE TITLE
Auto-Reload database on change should not be default

### ISSUE THREAD

**Issue by SciLor** [keepassxreboot/keepassxc#5255]
Auto-Reload database on change should not be default. If you by chance overwrite your file with an older version the "in memory" backup of the file will be destroyed.

Asking as standard what to do should be standard (use new or merge)

**Comment by droidmonkey** [comment]
Sounds more like auto reload did something you were not expecting or desired. I think the real fix is to determine if the changes are significant and prompt the user if that's what they intend.
