### ISSUE TITLE
[Linux] Unable to open databases from partitions

### ISSUE THREAD

**Issue by KizunaH** [keepassxreboot/keepassxc#5257]
## Steps to Reproduce 
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Save a database manually in other partition (not ubuntu partition)
2. Database > Open database > Other locations(ubuntu). In that window only shows Computer(ubuntu) partition.
(Signed in as non root user)

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.6.0

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux Ubuntu 20.04.01 LTS
Desktop Env: Gnome
Windowing System: X11

**Comment by droidmonkey** [comment]
Are you using the snap version?

**Comment by KizunaH** [comment]
> Are you using the snap version?

Yes. any problem with it?

**Comment by KizunaH** [comment]
Ah, i found the reason https://keepassxc.org/docs/KeePassXC_GettingStarted.html#_linux
