### ISSUE TITLE
Keepassxc doesn't remember certain closed windows or no option to disable it

### ISSUE THREAD

**Issue by KizunaH** [keepassxreboot/keepassxc#5258]
![Screenshot from 2020-08-12 12-11-59](https://user-images.githubusercontent.com/63988538/89977626-ca455280-dc95-11ea-8b16-546a197dade0.png)

I believe keepassxc devs able to recognize that window. It appear as default for every databases and subgroups and it has close button in right corner however that remain appear every time when keepass launched and open them also no way to disable it through settings

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.6.0

[NOTE]: # ( Pick choices based on your environment )
Operating System: Ubuntu
Desktop Env: Gnome
Windowing System: X11

**Comment by droidmonkey** [comment]
It's in the View menu, show preview panel
