### ISSUE TITLE
Unable to open database on mounted drive in snap package Ubuntu 17.04

### ISSUE THREAD

**Issue by colinl** [keepassxreboot/keepassxc#526]
Using snap package in Ubuntu 17.10 I am unable to open a database in an external drive mounted as /media/drivename/path/to/file. I get a permission denied error. The file is owned by the current user and he has full permissions (the file opens and is editable in keepassx). A further symptom is that it is not possible to browse to /media in Database > Open, it does not appear in the browse window. Even if the database is linked to from the Documents folder it still shows a permission error. If I copy the file to the local machine it opens ok.

## Expected Behavior
It should be possible to open a database on a mounted drive

## Current Behavior
Permission error when opening a database on a mounted drive.

## Steps to Reproduce (for bugs)

1. Mount an external drive containing a database in /media/<drivename>
2. Link to the database from the home folder
3. Attempt to open the database
4. Also attempt to browse to the file using Open Database and browsing to /media

## Your Environment

* KeePassXC version/commit used: (can be found under Help -> About)
2.1.4, installed using 
sudo snap install keepassxc
* Operating System and version: 
Ubuntu 17.10

**Comment by droidmonkey** [comment]
This is a known and reported issue.

**Comment by louib** [comment]
@colinl duplicate of https://github.com/keepassxreboot/keepassxc/issues/400, just so you can keep track of the issue.

**Comment by colinl** [comment]
OK, thanks. I did not notice the similarity as that bug refers to USB removable drives, though looking at the description I see that it is the same issue.

**Comment by droidmonkey** [comment]
And I fixed it with the latest update to the snap today. Please follow the instructions I put in my comment on #400
