### ISSUE TITLE
Exlude sites with special params

### ISSUE THREAD

**Issue by RolandSM** [keepassxreboot/keepassxc#5260]
Hello,

I am on a Kubuntu 19.10 System and KeePassXC 2.6.0 with KeePassXC-Browser 1.6.6

I use a CMS like Joomla where I have a login page with username/password.
Also inside the CMS I can manage users, also with usernam and password.

I have activated autofill because on login page I want this and this works of course.
But I dont want this autofill on other pages like user management.

The problem is, that those sites are only handeled with params. All redirects to https://mypage.de/index.php

When I enter https://mypage.de/index.php* to browser pugins page settings and disable all function it works for login on https://mypage.de/index.php and not if there is any other caracter behind.
Also this works that in usermanagement no passwords are filled.

But If I logout, I come back to login but this contains now for example https://mypage.de/index.php?logout
Also then is not password autofilled but  here I want it again???

What are my possibilites, in best example without an logout rewrite???
Is it not possible to add also params into page-settings detection like https://mypage.de/index.php?usermanager...

Greets

**Comment by droidmonkey** [comment]
Unless you configure your CMS / htaccess to do url rewrite instead of query based methods then this won't be possible

**Comment by RolandSM** [comment]
Now way to do exclusions with a plugin-page-setting?
https://mypage.de/index.php?option?usermanger* would be anought???
A redirect is no good idea because CMS needs parameter calls to work

**Comment by droidmonkey** [comment]
We don't check the query string because that would cause way more issues than fix niche cases like this

**Comment by droidmonkey** [comment]
This is fixed in 2.6.2 when you enable "Return best matching credentials". Query strings are compared.

**Comment by RolandSM** [comment]
Great news, Thanks. Looking forward for the Release...
