### ISSUE TITLE
Moving groups between databases can cause data loss

### ISSUE THREAD

**Issue by somevar** [keepassxreboot/keepassxc#5262]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )

1. Create first db with some groups (subgroups) and entries
2. Save db
3. Create second db and move group from first db
4. Reopen first db without save
5. Move group back to first
We have two groups with subgroups and entries with same UUIDs
7. Save and reopen first db - one group with all substructure dissapears

This is for example. I faced disappearing records when Drag&Drop (or manual import *.kdbx) from different databases. And no reports about that conflicts. For stay safe i have to clone every entry before move or import. Or do import/export through CSV (very unsafe).

Sorry for my English, please!

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.0
Revision: 0765954

Qt 5.15.0
Debugging mode is disabled.

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 5.7.12-arch1-1

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.6

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: i3
Windowing System: X11

**Comment by droidmonkey** [comment]
Check your steps I think you swap first and second db in there

**Comment by somevar** [comment]
> Check your steps I think you swap first and second db in there

Yes. - 3. Create second db and move group FROM first db

**Comment by somevar** [comment]
[Reproduce of bug in different databases (YouTube)](https://youtu.be/I_HYWVpFWPc)

**Comment by droidmonkey** [comment]
Will investigate this, thanks for reporting
