### ISSUE TITLE
Username dropdown not listing all options

### ISSUE THREAD

**Issue by iMartyn** [keepassxreboot/keepassxc#5263]
## Overview
The dropdown list of usernames is not complete and there appears to be no way to add to it/remove from it.

## Steps to Reproduce
Have a database with many usernames / passwords (I have a folder called relics with user/pass from previous companies)

## Expected Behavior
I expect to either be able to edit the list or it be complete.

## Actual Behavior
I cannot select my current work email from the list, it's not there, even though I have 5 or more entries in the database with that email as username

## Context
database is loaded from a webdav share mounted as a drive letter on windows

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.0
Revision: 0765954

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows

**Comment by droidmonkey** [comment]
It presents the 10 most frequently used usernames, i believe there is a minimum count necessary.
