### ISSUE TITLE
Add keyboard shortcut to search through all database, typing entry title

### ISSUE THREAD

**Issue by Yoannjap** [keepassxreboot/keepassxc#5264]
Hello,

First, thanks for your brilliant work with KeepassXC development!

Then, I don't manage to search through my database.
For example, typing CTRL+F doesn't do anything, any search bar appears, and I can't search through database typing something corresponding to text saved in the title fields of any entry.

Could you add it in next update?

Thanks,

Yoannjap

**Comment by somevar** [comment]
Please use the latest stable release. Search box on the right side of the toolbar. Ctrl + F sets focus to the search field. [User guide](https://keepassxc.org/docs/KeePassXC_UserGuide.html#_searching_the_database).

**Comment by droidmonkey** [comment]
Duplicate issue, showing search bar when hidden in the toolbar overflow menu.
