### ISSUE TITLE
Toolbar icons not displayed

### ISSUE THREAD

**Issue by balping** [keepassxreboot/keepassxc#5265]
## Overview
I upgraded to the new version 2.6.0. Since the toolbar became too wide to display the search bar, I tried to set *Toolbar button style* to "Icon only" without success.

## Steps to Reproduce
1. Go to Tools -> Settings
2. Under *User Interface* change *Toolbar button style* to *Icon only*

## Expected Behavior
Toolbar buttons should display icons only.

## Actual Behavior
Toolbar buttons are displayed with text.

## Screenshots

<table><tr><td><img src="https://user-images.githubusercontent.com/5840038/90177620-b63b4700-dda2-11ea-95f6-91cebf6e555e.png" /></td><td><img src="https://user-images.githubusercontent.com/5840038/90177632-bcc9be80-dda2-11ea-8c82-83a58d4a2b26.png" /></td></tr></table>

## Context
I'm using the native theme, but this is the same for dark/light themes.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.6.0
Revision: 0765954

[NOTE]: # ( Pick choices based on your environment )
Operating System: Ubuntu 16.04
Desktop Env: Mate
Windowing System: X11

**Comment by droidmonkey** [comment]
Pinned iasue
