### ISSUE TITLE
Codesmell: qpa/qplatformnativeinterface.h - you  really need qplatformnativeinterface?

### ISSUE THREAD

**Issue by truschival** [keepassxreboot/keepassxc#5269]
## Overview
Not a real bug, just looks strange on the first glance. 
I was building keepassxc 2.6.0 on Debian Bullseye. I build quite a few QT applications and never had the issue:
```
keepassxc/src/gui/osutils/nixutils/NixUtils.cpp:30:10: fatal error: qpa/qplatformnativeinterface.h: No such file or directory
   30 | #include <qpa/qplatformnativeinterface.h>
``` 

AFAIK these are special headers that are QT internal and should not be used in client applications.

The missing packages in Debian were `qtbase5-private-dev` (https://packages.debian.org/sid/qtbase5-private-dev )which states in the description: "Use at own risk" 

# Environment
Operating System: Linux 5.7.12, Debian Bullseye, QT 5.14, gcc 10.1
Desktop Env: i3wm & KDE
Windowing System: X11

**Comment by phoerious** [comment]
Yes, we need it.
