### ISSUE TITLE
Hide KeePassXC after chose auto-type

### ISSUE THREAD

**Issue by Niquit** [keepassxreboot/keepassxc#527]
Hi,

I had switched from Windows to Mac. I was looking for the best similar solution for KeePass.

I found KeePassX and KeePassXC. I chosen of course KeePassXC, because of global auto-type, what I need mostly.

But I have just one visual problem, what KeePassX with global auto-type doesn't have ( https://github.com/keithbennett/keepassx/releases ).

When I call for global auto-type the main windows always is restored, but never hidden after choose global type.

Is not important, but I never used QT5 and I'm sure there is something to resolve this issue like add one line to code. I have already prepare everything for build the source, so I just need some tips.

**Comment by Jasha10** [comment]
Hi, why was this issue closed?

**Comment by droidmonkey** [comment]
You're right, this for uniquely affect macOS

**Comment by droidmonkey** [comment]
This is no longer a problem in 2.7.0
