### ISSUE TITLE
Pop-up switches focus to KeepassXC app (only since update to 2.6)

### ISSUE THREAD

**Issue by ParaplegicRacehorse** [keepassxreboot/keepassxc#5270]
## Expected Behavior
When the browser extension detects a login which has not previously been selected as "always remember" (poor security practice), granting or denying permission window returns user to web page. This is what happened in version previous to KPxc 2.6.

## Current Behavior

Selecting a permission state switches app focus from browser to keepassxc forcing user to manually switch back to browser.
(since update to keepassxc 2.6/keepassxc-browser 1.6.6, Manjaro KDE, no settings changed on update)

## Steps to Reproduce (for bugs)

1. Load a web page with login fields; a site which does not have "remember" permission.
2. When extension prompts for permission, select accept or deny.
3. Watch as your browser become backgrounded while focus changes to keepassxc.

## Debug info

KeePassXC - 2.6
KeePassXC-Browser - 1.6.6
Operating system: Linux (Manjaro KDE)
Browser: Firefox, Brave

**Comment by droidmonkey** [comment]
Do you mean the focus is not returned to the browser after selecting allow/deny and the pop-up disappearing?

**Comment by ParaplegicRacehorse** [comment]
Yes. The focus is not returned to the browser.

https://cloud.nextcloudily.com/s/XyKqLyQKF4pySRk

**Comment by droidmonkey** [comment]
That is an anomaly with your desktop environment, the main window should not be appearing during this transaction.

**Comment by ParaplegicRacehorse** [comment]
@droidmonkey 

I am aware that the main window should not appear during the transaction. It is new on update to kpdx 2.6. It didn't used to happen. I am tempted to roll back to 2.5 until there is a fix.

**Comment by droidmonkey** [comment]
If you have the window hidden to the system tray this may prevent it from happening. Perhaps even having it minimized.

**Comment by ParaplegicRacehorse** [comment]
Minimized app window did prevent focus switch. I will have to try again with window closed (systray active) to determine.

Why the focus change with window open, though?

**Comment by droidmonkey** [comment]
It's a bug

**Comment by kotoko** [comment]
I can confirm this bug. It's happening for me too. I'm on Gentoo with KDE. Whenever I accept/deny this prompt keepassxc always goes to the foreground (even if was minimized in tray).

**Comment by droidmonkey** [comment]
This is no longer a problem in 2.7.0

**Comment by ParaplegicRacehorse** [comment]
2.7.1 problem remains.

Manjaro KDE-Plasma

**Comment by flaf** [comment]
I can confirm **this bug is still happening** for me, years after this issue was reported and closed. 😞

Environment:

* KeePassXC **2.7.12 (latest version)**
* KeePassXC-Browser 1.10.3
* Ubuntu 24.04
* GNOME Shell 46.0 (Wayland session)
* Firefox 156.0.1 (Snap package)
