### ISSUE TITLE
Add varying typing delay with auto type 

### ISSUE THREAD

**Issue by Meister1593** [keepassxreboot/keepassxc#5271]
## Summary
Title speaks for itself. Would be a good idea to add option to enable varying character typing speed with auto type (or a varying time delay between character typing with auto type).
Also would be nice to have this setting per-entry available.

## Examples
For example, we have a login, pass, then we would use autotype. 
Usually it would write every character with same time delay `original-delay` between every character. 
Now it would add `original-delay +-N ms` delay before typing new character. 
For example for +-5 ms, it would write like this:
**p**`{original-delay + 5ms}`**a**`{original-delay + 2ms}`**s**`{original-delay + 1ms}`**s**`{original-delay + 4ms}`**w**`{original-delay + 3ms}`**o**`{original-delay + 2ms}`**r**`{original-delay + 5ms}`**d**

## Context
I think it would improve security , because no app could detect that you use password manager through typing if your typing speed is is not consistent, like usual person would type.

**Comment by droidmonkey** [comment]
This is not going to be implemented and would not thwart any attempt at keylogging
