### ISSUE TITLE
Add a command line option which set search query

### ISSUE THREAD

**Issue by Galliver7** [keepassxreboot/keepassxc#5273]
## Summary
Add a command-line option such as `--query [query_string]` to GUI application that set a query without typing `"CTRL + F"`
This feature enables easy-access to password or attributes without typing `CTRL + F` every time.

## Examples

Idea 1:
Optional argument
`"KeePassXC.exe" --keyfile C:\example.kdbx {query string such like"google"}`

Idea 2:
Add a new argument
`"KeePassXC.exe" --keyfile C:\example.kdbx --query {query string such like"google"}`

## Context
I am accessing keepassxc trough 3rd party application launcher ([keypirinha](https://keypirinha.com/)) which can add an argument.
Typing CTRL+F every time makes me so annoying to grab a password ( or attributes) so I needed it.
With that argument, I will use it like this:

![screenshot_101](https://user-images.githubusercontent.com/8030470/90309844-f7f4fa80-df26-11ea-95ab-0e6e6f969bf0.png)

*the command name is just an example, I will change the command to short one like "ks".

Hope this feature makes better KeepassXC experience! 🐬

**Comment by droidmonkey** [comment]
Technically search is focused on unlock so you just need to type your query

**Comment by Galliver7** [comment]
yeah, that's right. But having the function will enable more application so
What do you think droidmonkey, is it better to NOT have the feature to keep it simple?

Personally, I definitly would like to have the feature but wanna know your feeling.

**Comment by droidmonkey** [comment]
I don't envision anyone using this feature (besides you), it is extremely niche and would require a bit of coding work

**Comment by Galliver7** [comment]
Right. I respect your judgement anyway 👍

**Comment by droidmonkey** [comment]
Won't be implementing this
