### ISSUE TITLE
Please take away this flatness from the UI

### ISSUE THREAD

**Issue by Agych** [keepassxreboot/keepassxc#5280]
## Summary
Please take away this flatness from the UI.

## Context

It is cool that the dark theme was added.
But have to say that the whole new UI is a huge step back.
Flat, primitive, tasteless.
The step back of the v2.6.0 UI from the v2.5.4 UI is the same as Windows 10 from Windows 7/Vista design.

Even the icons were replaced with the flat ones!
Even the buttons were replaced with the flat minimalistic black-n-while ones!
Which also makes the "classical" theme not really classical, and this theme doesn't really help much.

Please bring back the old look, or make a re-design with 3D/classic style and with no flatness.

Will stay on v2.5.4 for now.

**Comment by droidmonkey** [comment]
No thanks
