### ISSUE TITLE
Many icons are not showing up

### ISSUE THREAD

**Issue by 480gh8q0hg08** [keepassxreboot/keepassxc#5281]
![Screenshot from 2020-08-16 19-30-13](https://user-images.githubusercontent.com/49598754/90346462-a75dca00-e018-11ea-9857-bcfe6992540b.png)
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
Some of the icons on the top panel are not working

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Just opening the program
2. 
3. 

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Some of the icons on the top panel are not showing up. I can still click on them and if I hover my mouse on them it says a description but no icon image.

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.0
Revision: 0765954

Qt 5.9.5
Debugging mode is disabled.

Operating system: Linux Mint 19.1
CPU architecture: x86_64
Kernel: linux 4.15.0-112-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.1

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux Mint
Desktop Env: Cinnamon
Windowing System: X11/Wayland

**Comment by droidmonkey** [comment]
pinned........
