### ISSUE TITLE
Allow any file as keyfile

### ISSUE THREAD

**Issue by EvilOlaf** [keepassxreboot/keepassxc#5282]
## Summary
Allow to select any file as keyfile

## Examples
Veracrypt (formerly Truecrypt) allows us to use any file available as keyfile by simply using the first 1024bit or so and mixing that together with the password. Using this method an additional layer of "security through obscurity" could be added because nobody knows (or should know from just looking at least) which file to use or IF to use ANY AT ALL.

Of course the user needs to make sure that this particular file must not be altered in any way but as stated it works for TC/VC too.
Could be any binary for example which usually do not alter by themselves or get modified.

I tried to dig through the existing issues and maybe I missed it because I was quite sure somebody must have asked this before, could not find a matching report though.

Thanks for reading.

**Comment by phoerious** [comment]
You can use any file as a key file.

**Comment by EvilOlaf** [comment]
Well then my bad. Got irritated by the predefined selection: 
![grafik](https://user-images.githubusercontent.com/3305006/90364048-0268de80-e064-11ea-9c91-6afa732132c5.png)
Maybe it should be altered to be any file by default.

**Comment by droidmonkey** [comment]
No it shouldn't that is not a good idea because any changes to that file will lock you out of your database

**Comment by EvilOlaf** [comment]
That is your point of view. The concept worked for TC/VC so... ¯\_(ツ)_/¯
