### ISSUE TITLE
KeePassXC - Version 2.6.0 sometimes hangs on db unlock

### ISSUE THREAD

**Issue by hrez** [keepassxreboot/keepassxc#5286]
## Overview
KeePassXC - Version 2.6.0 sometimes hangs on db unlock

## Steps to Reproduce
Can't really reproduce.
It happened multiple times. As far as I remember it's never on an initial unlock but rather after an autolock due to a sleep or a locked screen.
Type in the password, hit enter and it just hangs there. I tried to wait it out but it never unfroze.
It never happened on 2.5.1. 

KDBX 4.0, key file, chacha20, argon2, 4 threads.

## Expected Behavior
Unlock db

## Actual Behavior
freezes

## Context
KeePassXC - Version 2.6.0
Revision: 0765954

Qt 5.15.0
Debugging mode is disabled.

Operating system: Windows 10 Version 2004
CPU architecture: x86_64
Kernel: winnt 10.0.19041

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.5

**Comment by droidmonkey** [comment]
You are probably setting your argon2 parameters too high.

**Comment by LinuxOnTheDesktop** [comment]
I have just experienced this, on KeePassXC 2.6.1, on Windows 10. I am unaware of setting any 'argon2' value. The problem is hard to reproduce on my machine: I experienced it just now and I think I experienced it once before (but that previous time may have been a hang while KeePassXC was not unlocking but instead doing something else).

**Comment by stevenxed** [comment]
I've had it happen a couple of times as well, on windows 10, KeePassXC v2.6.1 and have it benchmarked to 1 sec on 4 threads with argon2. Unlocking gets stuck on decrypting but you can still access the settings and menus. Gotta force quit it with task manager every time it happens. PC is always on, and it's always running in the tray. Seems to randomly occur only after an initial unlock + running for at least a few hours?

**Comment by DominiqueAllen** [comment]
I've had this issue happen under the same circumstances (usually after auto-lock due to hibernating, but it also happened once randomly after the program was running for a few hours). I've also had the database unlocked, but the UI gray out and go unresponsive. Quite annoying.

> KeePassXC - Version 2.6.6
> Revision: 9c108b9
> 
> Qt 5.15.2
> Debugging mode is disabled.
> 
> Operating system: Windows 10 Version 2004
> CPU architecture: x86_64
> Kernel: winnt 10.0.19041
> 
> Enabled extensions:
> - Auto-Type
> - Browser Integration
> - SSH Agent
> - KeeShare (signed and unsigned sharing)
> - YubiKey
> 
> Cryptographic libraries:
> - libgcrypt 1.9.2-unknown

**Comment by droidmonkey** [comment]
I've never experienced this problem in testing or use on my own database. There is not much that could cause the application to deadlock during unlock, failures cause hard fail outs with error message. Is your database stored on a network share or of abnormally large size?

**Comment by DominiqueAllen** [comment]
No, it's stored on a local drive and reasonably small (~30 KB).

The behavior is intermittent on my machine, similar to the other reports, but I'd be happy to help get you more information if you have thoughts on the best way for me to do so.

**Comment by droidmonkey** [comment]
Best way to get more info is to run a snapshot build and see if it persists. You should be able to take core dumps of snapshot builds through task manager. https://snapshot.keepassxc.org

**Comment by LinuxOnTheDesktop** [comment]
@DominiqueAllen 

Might I ask whether you still have the problem? I myself still have the problem (#6582). I am using KeePassXC 2.7.1 (on Windows 10).

**Comment by zellchristensen** [comment]
Just ran in to this issue today.  Attempted to unlock my db and it was hung unlocking for 3 minutes before i force closed and restarted KeePassXC. It worked as normal after restarting KPXC.. User account usually gets logged out daily but was recently left logged on about 3 days.  There is a high decrypt time set but the db is fairly small.  This is KeePassXC 2.7.4 on Win10, i5 7500T 2.70GHz, 16GB Memory
