### ISSUE TITLE
Crash after downloading favicon

### ISSUE THREAD

**Issue by matywastaken** [keepassxreboot/keepassxc#5291]
## Overview

When i download a Favicon for a new entry, the application freezes for a second, then crashes. However the favicon is functional and the changes are saved to the database.

## Steps to Reproduce

1. Create a new entry
2. Download favicon for the new entry
3. The app crashes when pressing "Close" after the download was successful

## Expected Behavior

The message closes, the app does not.

## Actual Behavior

The message closes along with the app.

## Context

KeePassXC - Version 2.6.0
Revision: 0765954

Qt 5.15.0
Debugging mode is disabled.

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 5.8.1-arch1-1

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.6

Desktop Environment - Gnome
The error happens with both X11 or Wayland

**Comment by droidmonkey** [comment]
Fixed already for 2.6.1
