### ISSUE TITLE
How do i export TOTP codes from KeePassXC?

### ISSUE THREAD

**Issue by Glass47** [keepassxreboot/keepassxc#5292]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
Option to export shared secret for TOTP

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )
It would take me much much time to export KeePassXC totp database into other password manager, but when i have secret with exporting, it wouldn't take too long.

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
 I exported database from KeePassXC and imported to Bitwarden, but my TOTP didn't. Is there a way to transfer all TOTP codes into Bitwarden so i don't have to manually do it. I transferred my KeePassXC database into Bitwarden before purchasing Bitwarden subscription. Is that reason why my TOTP codes didn't transfer? If someone doesn't know what i mean by saying TOTP codes, i mean the main code that is in charge of generating 1 time use codes when logging into some account. Best regards!

**Comment by droidmonkey** [comment]
You'll need to use the cli to export the xml version of the database, then you can search for TOTP to gather the codes/urls. `keepassxc-cli export ./database.kdbx`

**Comment by droidmonkey** [comment]
Covered in #3541

**Comment by Glass47** [comment]
@droidmonkey Thank you for answer but i don't know how to do that. Can you please explain me if possible, i don't have much knowledge in that area... Btw i am using windows.

**Comment by Glass47** [comment]
I think i got this but i can't figure what to do next 
![image](https://user-images.githubusercontent.com/55170107/90646692-c8503600-e237-11ea-91aa-185a839cd26b.png)

**Comment by droidmonkey** [comment]
Remove the 'xml' part of the command and add ` > database.xml` after the whole command. So `keepassxc-cli export db.kdbx > database.xml`

**Comment by Glass47** [comment]
> 
> 
> Remove the 'xml' part of the command and add ` > database.xml` after the whole command. So `keepassxc-cli export db.kdbx > database.xml`

Thank you for your answer, do you maybe have idea why it says "Error while reading the database: Invalid credentials were provided, please try again.
If this reoccurs, then your database file may be corrupt. (HMAC mismatch)"

database is in folder called DB and file is named "pws.kdbx" 
![image](https://user-images.githubusercontent.com/55170107/90668625-a8793c00-e250-11ea-8bdb-ddbdc26bcef9.png)

As you can see on screenshot i used `keepassxc-cli export C:\Users\xD\Desktop\DB\pws.kdbx > database.xml` and looks like it works but i have error, is that error because i have keyfile ? Because my database can't open without keyfile, or not ? 
![image](https://user-images.githubusercontent.com/55170107/90668800-e6766000-e250-11ea-903e-66db322ffa6e.png)
![image](https://user-images.githubusercontent.com/55170107/90668818-ed04d780-e250-11ea-8adc-29a24e8d6a7a.png)

**Comment by Glass47** [comment]
Update. I solved it. Thank you for helping me. I really appreciate.
