### ISSUE TITLE
Strange line on Edit Screen

### ISSUE THREAD

**Issue by Magxss** [keepassxreboot/keepassxc#5293]
## Overview
A strange line appears on the edit screen.  Please see attached screenshot.
Apologies if this has been reported already.  I could not find anything.
![18162564-99B2-48FA-AEE7-D5A79B9246F7](https://user-images.githubusercontent.com/69898787/90622054-a77ee500-e225-11ea-9119-d1f668607c8b.jpeg)

## Steps to Reproduce
I am running KeePassXC 2.6 Portable on Windows 10 (installed through Portable Apps platform).  Just opening an entry will show this strange line on the edit screen.  It does not happen every time, but most of the time.  I have seen this on two separate PCs.

## Expected Behavior
No line.

## Actual Behavior
Line

## Context
Nothing further I can think of to describe it better.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows/Linux/macOS
Desktop Env: Gnome/KDE/XFCE/Mate/Cinnamon
Windowing System: X11/Wayland

**Comment by droidmonkey** [comment]
Does the line appear if you use our official portable version? We do not endorse using portable apps distribution.

**Comment by Magxss** [comment]
Thanks for the quick response.  I now tried the official portable version and do not get this line.  I wasn’t aware that there was a difference.  Will use the official version going forward.
Thanks for the help!

**Comment by Magxss** [comment]
Hi, I have been using the official portable version from the KeepassXC website.  At first, the line was gone, but it has now come back.  Recent screenshot attached and debug info below.  I am getting this on two different PCs.  Any help would be much appreciated.

KeePassXC - Version 2.6.1
Revision: 9a35bba

Qt 5.15.0
Debugging mode is disabled.

Operating system: Windows 10 Version 2004
CPU architecture: x86_64
Kernel: winnt 10.0.19041

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.5


![image](https://user-images.githubusercontent.com/69898787/92222665-67b82e80-eeb0-11ea-9bff-8cd019294120.png)

**Comment by droidmonkey** [comment]
We don't know the cause and can't reproduce it

**Comment by Magxss** [comment]
Strange.  Anything I can do to provide further info?

**Comment by droidmonkey** [comment]
Do you have a 4K monitor or 1080p?

**Comment by Magxss** [comment]
Yes, I do have a 4K monitor!

**Comment by droidmonkey** [comment]
Darn i was hoping you didn't, that would have possibly narrowed down the reason.

**Comment by Magxss** [comment]
Bummer. Thanks. I’ll learn to live with it.

**Comment by gadgetpig** [comment]
Confirm having the same issue in Win10 2004 (19041), and resizing it makes it disappear.

**Comment by droidmonkey** [comment]
This is fixed in #5424
