### ISSUE TITLE
Unable to select hidden files in OS system file open dialogs

### ISSUE THREAD

**Issue by pbukva** [keepassxreboot/keepassxc#5296]
## Overview
All OS system pop-up dialogs for file open like `Open Database...` do not allow to select hidden files - e.g. on unix system files starting with `.`, like for instance `.secrets.kdbx`.

## Steps to Reproduce
1. Create new kdbx database and save it as `.secrets.kdbx` (on macOS)
2. Go to `Database -> Open Database...`
3. OS system dialog for File Open pops up
4. Press the `Shift` + `Command` + `.` key combination to display hidden files in the openned dialog 
5. Browse to directory where the `.secrets.kdbx` file from point 1. above is located
6. If necessary(it should not need to be) select the `All files(*)` in drop-down combobo-box located at the bottom of the dialog (at least in macOS)
6. The `.secrets.kdbx` file is listed in dialog in dimmed mode = it can not be selected for opening (not even when selecting with up & down arrow keys on keyboard)

## Expected Behavior
1. *ALL* files shall be selectable in File Open dialog when `All files (*)` option is selected in the combo-box, *disregard* of their file extension or their hidden status  
2. If `KeePass2 Database (*kdbx)` option is selected, then hidden files with `.kdbx` suffix shall be selectable in File Open dialog  

## Actual Behavior
Hiden files are not selectable in the system File Open dialog even if they are displayed there (they are dimmed).

## Context
KeePassXC - Version 2.6.1
Revision: 9a35bba

Operating System: macOS
Desktop Env: n.a.
Windowing System: n.a.

**Comment by droidmonkey** [comment]
Again Qt bug or macOS bug

**Comment by pbukva** [comment]
I would not jump to `Qt Bug` / `macOS` bandwagon so quickly.
This is about OS system dialog for File Open - no Qt is shall be involned here.

**Comment by droidmonkey** [comment]
@pbukva confirmed its a Qt Bug: https://bugreports.qt.io/browse/QTBUG-65530

**Comment by simawn** [comment]
I found a workaround:
- Right click the dot file and choose "Rename". This will still select the dot file
- Press on Open
