### ISSUE TITLE
keepasshttp attribute migration shows up every time I open db

### ISSUE THREAD

**Issue by gabrielambuehl** [keepassxreboot/keepassxc#5297]
I am recently trying out latest stable release. I like what I see but it bothers me that keepassxc wants to migrate browser config everytime I open the DB. Even if I go to DB settings and tell it to forget all browser connections and remove site specific data, it still asks me to do the migration agqain next time I open the DB.

I could obviously set the checkbox to suppress the dialog but it is a bit worrying that the DB does not seem to be properly cleaned...

**Comment by droidmonkey** [comment]
Just do the migration, you can't use browser integration if you don't.

**Comment by gabrielambuehl** [comment]
I did the migration at least 5 times - still shows up every time I open the DB.

Browser integration itself works just fine.

**Comment by hackel** [comment]
I just got hit by this as well.  I merged an old database from my phone that must have been from before I migrated the first time, and now every time it starts, it asks me to move browser settings into the database settings.  Then when I hit yes, it says "The active database does not contain an entry with KeePassHTTP attributes."

**Comment by gabrielambuehl** [comment]
Did you check the Recycle bin? That's where they were hiding in my case. Occasionally I even got that error, too.
