### ISSUE TITLE
Scrollbar shows up in middle of edit/details screens

### ISSUE THREAD

**Issue by gaelanlloyd** [keepassxreboot/keepassxc#5300]
![keepass-details-scrollbar-issue](https://user-images.githubusercontent.com/1403649/90791120-b0bb9080-e2bd-11ea-8420-35a3050355ee.png)

## Overview
I just upgraded from 2.5.4 to 2.6.1 today and I'm seeing vertical scrollbars floating over the middle of the edit panel.

## Steps to Reproduce
Whenever I edit a folder, or the first time I edit a particular password's entry.  If I open the same password entry it doesn't happen, but it always happens when editing a folder's entry.

## Expected Behavior
Scrollbar shouldn't be floating in the middle of the window.

## My system info
KeePassXC - Version 2.6.1
Revision: 9a35bba

Qt 5.15.0
Debugging mode is disabled.

Operating system: Windows 10 Version 1909
CPU architecture: x86_64
Kernel: winnt 10.0.18363

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.5

Let me know if there's anything else I can provide to help debug this issue.

**Comment by th3m** [comment]
Got the same bug, no extensions enabled, Win10 64 bit.
"Maximize" or "Restore down" the application temporary fixes the visual bug.

**Comment by droidmonkey** [comment]
Are you using the portable apps download?

**Comment by gaelanlloyd** [comment]
No, the Windows 64-bit MSI installer.

**Comment by jnqnfe** [comment]
Affects Linux also. I reported it for Debian on Sunday with v2.6.0 as [bug #968542](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=968542). I've just received the v2.6.1 update and it's still there. Qt version here is 5.14.2.

**Comment by droidmonkey** [comment]
I've debugged this before and there is no obvious reason why its visible.

**Comment by gaelanlloyd** [comment]
Something interesting: When I open an entry, the scrollbar sometimes isn't there.  But if I leave the entry details window open and switch window focus to another window, the scrollbar shows up.

**Comment by woowoo803** [comment]
Also seeing this on a Windows 7 machine with 2.6.1 MSI installer 64 bit, typically running normal view (not compact) and Auto theme.  In my case it happens every time on every entry.  Tried switching themes and Auto/light/dark have a thin bar, while Classic has a wide bar.  The bar is always there in all themes, but only in the Edit-Entry screen, not in the Advanced, Icon, etc.  Normally the bar just cuts into the Notes field, but if I go to one of the other Edit screens and return to Entry then the bar is longer, about 1/2 way down the notes field.  If I cancel the edit and return to Edit the bar is shorter again.

**Comment by PoolJK** [comment]
Happens also on MacOs (Catalina).

**Comment by CYBRPVNK** [comment]
I am having the same problem. I noticed that resizing the window temporarily fix it for current entry.

**Comment by turbosmurfen** [comment]
I have never seen this before, And I have not added a new entry since I downloaded portable 2.6.1. Now when adding new entry it show up a scrollbar in the middle. I have tried to resize the window and the scrollbar disappear from the new entry settings. But if I add a new entry it's back. So yes I have the same problem. I'm using Windows 10 2004 x64.

**Comment by droidmonkey** [comment]
Locking issue, we have enough information, but none of the devs can replicate the problem in order to debug and correct it.
