### ISSUE TITLE
Allow using old icon set

### ISSUE THREAD

**Issue by gaelanlloyd** [keepassxreboot/keepassxc#5301]
The new icons are pretty and modern, but they have flat, muted colors and soft edges so they don't really stand out on the screen.  I'd love if there was a way to use the original icon set.

**Comment by phoerious** [comment]
Soft edges?

**Comment by gaelanlloyd** [comment]
![keepassxc-icons-small](https://user-images.githubusercontent.com/1403649/90808165-714c6e80-e2d4-11ea-8c87-2b7d7503fa0a.png)

![keepassxc-icons](https://user-images.githubusercontent.com/1403649/90808027-4104d000-e2d4-11ea-9309-198680d6790b.png)

The new icons are made with fewer colors and have less contrast at the edges, so the edges appear "softer."

But anyway, I'd not like my personal feelings on the new icon set to distract from my original request to have the chance to use the old icon set :-)

**Comment by droidmonkey** [comment]
We won't do this

**Comment by boundless-thread** [comment]
@droidmonkey is there a reason why the old icon set cannot be included in the classic theme?

**Comment by droidmonkey** [comment]
The icons are 16px in size and terrible
