### ISSUE TITLE
Allow hiding folder and password entry icons

### ISSUE THREAD

**Issue by gaelanlloyd** [keepassxreboot/keepassxc#5302]
![keepass-icons](https://user-images.githubusercontent.com/1403649/90792814-cd58c800-e2bf-11ea-9808-f6679494dee2.png)

I'd like to request the ability to:

1. Hide icons in the folder tree
2. Hide icons in the password entries list

When I was submitting #5301 it got me thinking: I'd actually like an option to hide icons in the program completely.

I can see how the icons are helpful in organizing entries, but I use folders for that.  I find myself spending a lot of time managing the icons, finding "the right ones" for my folders, and then ensuring all of the entries have the same icon for the group.

Having the ability to toggle on/off icons for folders and password entries would help save me from some of my obsessive icon-management tendencies.

**Comment by droidmonkey** [comment]
I do not support this
