### ISSUE TITLE
Username entries are suddendly hidden behind ••••••

### ISSUE THREAD

**Issue by evilSwanson** [keepassxreboot/keepassxc#5303]
## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
The entries in the username-column should not be hidden. It should look like this https://keepassxc.org/images/screenshots/database_view.png

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
The entries in the username-column are hidden: 
![keepassxc](https://user-images.githubusercontent.com/35380225/90796597-0bc1a780-e2ff-11ea-8ca8-c88ae19f62dd.png)

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.6.1
Revision: 9a35bba

[NOTE]: # ( Pick choices based on your environment )
Operating System: Kubuntu 20.04.1
Desktop Env: KDE
Windowing System: X11

**Comment by phoerious** [comment]
Right-click column, uncheck hide usernames.
