### ISSUE TITLE
Saving Database fails with Yubikey 2FA Challenge-Response

### ISSUE THREAD

**Issue by stmllr** [keepassxreboot/keepassxc#531]
I have a database with Yubikey 2FA Challenge-Response enabled.
If I remove the yubikey from the USB port and re-insert it, then saving the database fails with
> Writing the database failed.
> Unable to issue challenge-response.

This error also occurs, after the OS woke up from the suspend-to-ram state.

## Expected Behavior
Database is always saved 

## Current Behavior
Database is only saved, when Yubikey has never been removed before.

## Possible Solution
Scan for Yubikey before Saving Database

## Steps to Reproduce (for bugs)
1. Create a database and enable Challenge-Response with Yubikey inserted
2. Add entry
3. Save database --> success
4. Remove Yubikey from USB port
5. Add entry
6. Re-Insert Yubikey to USB port
7. Save database

Result: Error 
> Writing the database failed.
> Unable to issue challenge-response.

## Workaround
1. ...
2. ...
3. ...
4. ...
5. ...
6. Re-Insert Yubikey to USB port
7. Open "Change master key" dialog
8. Activate "Challenge Response" checkbox
9. Cancel "Change master key" dialog
10. Save database

## Context
Build: `-DWITH_XC_YUBIKEY=ON`

## Your Environment
Debian Linux Jessie
KeePassXC - Version 2.1.4
Revision: ad79162061c19decdd122784ff8adc4f18d6ce9b

Libraries:
- Qt 5.3.2
- libgcrypt 1.6.3

Enabled extensions:
- KeePassHTTP
- Auto-Type
- YubiKey

**Comment by stmllr** [comment]
The setting "Remember last key files and security dongles" is activated

**Comment by mritun** [comment]
This is an extremely annoying problem while using YubiKey with KeepassXC (my prime reason for using XC in the first place). I shall take a look and see what can be done.

**Comment by droidmonkey** [comment]
Its fixed in a PR already

**Comment by stmllr** [comment]
PR #880 fixes this issue for me. Thanks @droidmonkey

**Comment by stmllr** [comment]
didn't see the fix because there was no cross reference in the pull request into here.

**Comment by Tormen** [comment]
Hi,

I ran into this as well. Glad to see that there is already a solution for this in the making.

When might the version with the PR #880 get released ?
(I am on archlinux, using community/keepassxc 2.2.0-2)

Thanks a lot!

Tormen

Also @stmllr : Thanks a lot for the workaround! :) ... I had not yet succeeded in finding one ;)

**Comment by droidmonkey** [comment]
Looks like this can be closed.
