### ISSUE TITLE
Local config data is cleared when ~/.cache mounted on tempfs

### ISSUE THREAD

**Issue by gripped** [keepassxreboot/keepassxc#5313]
## Overview
Since the big update (new gui) keepassXC  very very rarely remembers the last database no matter whether I shutdown the desktop cleanly or with a three or four finger salute (KDE only ?). Before the update it remembered fine. It is enabled in the options. Remember and open on startup

As I only ever use one database my workaround has been , just now, to change it's user .desktop file to explicitly open the database

## Steps to Reproduce

1. Tell keepassXC to remember last database and open on start up.
2. Restart the computer or X by any method
3. Start KeepassXC

## Expected Behavior
Ask me for the password for the last used database instead of having to navigate to it's location almost every time.

## Actual Behavior
Have to navigate to it's location almost every time.

## Context
It occasionally works but I fail to see a pattern. I've tried making sure KeepassXC is closed cleanly but that doesn't make a difference AFAICT. 

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.1
Revision: 9a35bba

Qt 5.15.0
Debugging mode is disabled.

Operating system: Gentoo/Linux
CPU architecture: x86_64
Kernel: linux 5.8.3-gentoo-x86_64

Enabled extensions:
- SSH Agent
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.6

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux/
Desktop Env: KDE
Windowing System: X11

**Comment by gitvalds** [comment]
On Fedora 35 /tmp/ is a tmpfs.

The following procedure works for me on Fedora 35 with KDE, for replacing:
```${HOME}/.cache```
with:
```/tmp/kde_cache/```
but preserving the settings of keepassxc.

You can copy paste after replacing all the occurrencies of:
```<user>```
with the name of your user.

This procedure is based on the suggestions made by:
https://github.com/keepassxreboot/keepassxc/issues/4911#issuecomment-659856141

Thank you so much to everybody who contributes to this amazing software :+1:
_____________________________________________________

As the user ```<user>```, run the following commands:
```
mv /home/<user>/.cache /home/<user>/.cache.renamed
mkdir /tmp/kde_cache/
ln -s /tmp/kde_cache/ /home/<user>/.cache
mkdir /home/<user>/.local/share/keepassxc
cp /home/<user>/.cache.renamed/keepassxc/keepassxc.ini /home/<user>/.local/share/keepassxc/keepassxc.ini
```
_____________________________________________________

As the user root, run the following commands:
```
vim /etc/profile.d/my.sh
```
```
### this block of lines is the whole content of the file;
### it does not need to be executable;
###
### to use tmpfs for /home/<user>/.cache/
if [[ ! -e /tmp/kde_cache/ ]]; then
  mkdir /tmp/kde_cache/
  ### the following two commands are because keepassxc currently stores settings under
  ###   /home/<user>/.cache/
  ### and we want to preserve them between reboots;
  mkdir /tmp/kde_cache/keepassxc/
  ln -s /home/<user>/.local/share/keepassxc/keepassxc.ini /tmp/kde_cache/keepassxc/keepassxc.ini
  chown --recursive <user>:<user> /tmp/kde_cache/
  chmod --recursive u=rwX,go= /tmp/kde_cache/
fi
```
_____________________________________________________

```
systemctl reboot
```

**Comment by droidmonkey** [comment]
With keepassxc 2.6.0 and above you can just add an environment variable or command line flag to point to a different folder for the local config.

https://keepassxc.org/docs/KeePassXC_UserGuide.html#_command_line_options

--localconfig or KPXC_CONFIG_LOCAL

**Comment by gitvalds** [comment]
Hi @droidmonkey.
That is great :)
I tested both options and they both work on Fedora 35.
Most certanly the man pages on Fedora are not maintained by you but, just for your information, the "--localconfig" option is not mentioned in "man keepassxc".
The "--config" option is, but it does not achieve this result.
Thank you very much.

**Comment by droidmonkey** [comment]
Oops forgot to put that in the man page, but it is in the user guide 😇

**Comment by cemno** [comment]
I had this problem on multiple machines recently for a couple of months until i found this thread. My keepassxc.ini file in ~/.cache/keepassxc  was stuck on LastOpenedDatabases=@Invalid() . Deleting it resolved it, but it took me quite a while to find out and it somehow came up on multiple machines. Even reinstalling did not clear up the ini file in the .cache location, which was my last resort after nothing else worked... Maybe there should be some kind of cleanup after a reinstall?

**Comment by droidmonkey** [comment]
Open application settings, scroll to bottom, click "Reset to defaults"

**Comment by cemno** [comment]
I tried it on a different machine that still had this problem. Using the reset Button does not work, only deleting it the ini file. Maybe it has something to do with switching between the installationmethod? I switched from .deb to snap and settled on flatpak (on snap the icon wasn't working).

**Comment by droidmonkey** [comment]
Deb, Snap, and Flatpak all store the config files in different locations.

**Comment by cemno** [comment]
Switching the installation method then might not have been creating the problem all along, but i would still count being stuck with a broken config/.ini file without the possibility to repair it through normal means (using the reset button or reinstalling) should count as a bug.

But i apologize for posting in this probably off-topic issue, i guess i got here from [#4911](https://github.com/keepassxreboot/keepassxc/issues/4911) where the relevant file i had to delete was mentioned. Should i open a new issue?
Sadly i don't know what cause this issue, only the symptoms.

**Comment by droidmonkey** [comment]
The reset settings does what it describes. You'll have to provide very specific details on your situation otherwise.
