### ISSUE TITLE
Program errors and crashes[v2.6.0&2.6.1]

### ISSUE THREAD

**Issue by VIIEMPTY** [keepassxreboot/keepassxc#5319]
## Overview
When I open the program, or add and edit the password, it will directly cause the program to crash and exit. This problem appeared in version 2.6.0 so that it could not be used normally, so I rolled back to version 2.5.4 without any problems. Recently, version 2.6.1 was newly released, which did not solve this crash and error.

## Steps to Reproduce
1. There will be occasional crashes when starting the program, the probability is about 50%
2. When editing any password information, when any character is entered, the program crashes immediately with a 100% probability of occurrence.
3. When adding a new password information, and then click to start editing, when the first character is entered, it immediately crashes and exits. The probability of occurrence is 100%.

## Actual Behavior
As the picture shows
![image](https://user-images.githubusercontent.com/70069731/90961625-d2df2980-e4dc-11ea-9099-39a87d4b229b.png)

KeePassXo: Windows-application error
An exception occurred in the application unknown software exception (O40000015), location
Is 0×000000006FC5EF2A
To terminate the program, click "OK"

## Context
There is no problem in version 2.5.4, and the error has appeared since the official version of 2.6.0. Until now, the official version of 2.6.1 has not resolved the error.

In addition, I also checked the system and hardware devices and there were no errors.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION:2.6.0&2.6.1 Officially released 64-bit portable version
Revision:  9a35bba

Qt 5.15.0
Debug mode is disabled.

PC: hp elitebook735g5
version：Windows10 Home Chinese Version
version number：2004
CPU：AMD Ryzen 2700u pro 2.2Ghz
RAM: Kingston Hacker God Bar 8g*2
Installation date：2020/6/7
Operating system version：19941450
Kernel: winnt 10.0.19041
Other：The system and drivers are the latest stable version

Enabled extensions:
-Automatic input
-Browser coordination
-SSH agent
-KeeShare (signed and unsigned sharing)
-YubiKey

Cryptography public library:
  libgcrypt 1.8.5

**Comment by Nyar233** [comment]
我遇到了同样的问题。除此此外，还有另外一个问题：关闭keepassXC窗口后，keepassXC的进程仍然在运行，必须自己手动通过任务管理器关闭。

这些问题都是在便携版里遇到的，msi的版本是正常的。
