### ISSUE TITLE
inconsistent text alignment

### ISSUE THREAD

**Issue by jnqnfe** [keepassxreboot/keepassxc#5321]
username and notes text is slightly out of alignment with title, password and URL

version 2.6.1 on Debian. Interface text (in Gnome tweak tool) is size 12 with scaling 0.90 (to offset a recent increase in shell theme font size). Screen is HiDPI with scaling 200%.

![misaligned_text](https://user-images.githubusercontent.com/33935229/90967567-cfe23a00-e4d8-11ea-9643-c7828994ef94.png)

**Comment by boisbleu** [comment]
Same issue here on Windows 10 2004.

![Anmerkung 2020-08-26 201514](https://user-images.githubusercontent.com/57126931/91340832-ee964880-e7d8-11ea-8f42-9508af5cff1d.png)

**Comment by phoerious** [comment]
You, in fact, have the stray scrollbar.

**Comment by boisbleu** [comment]
Yes, and I need to wear glasses.

Here ist the correct issue: https://github.com/keepassxreboot/keepassxc/issues/5300
