### ISSUE TITLE
Breadcrumbs delimiter should be something other than `🮁`

### ISSUE THREAD

**Issue by quinncomendant** [keepassxreboot/keepassxc#5323]
## Overview
The navigation breadcrumbs that appear when editing an entry, e.g., `Root > Twitter > Edit entry`, is delimited with a `🮁	` character instead of something like a `>` or `/` (maybe it's not exactly the `🮁` character, but that's the closest unicode I could find that looks similar).  See screenshot:
![Screen Shot 2020-08-22 at 19 09 50](https://user-images.githubusercontent.com/6884276/90967959-5a607480-e4ac-11ea-8a20-cc3bc5f2fe2c.png)

## Steps to Reproduce
1. Edit any entry.
2. There is no step two.

## Expected Behavior
I would expect breakcrumbs to be delimited with a `>` or `/` character.

## Actual Behavior
My breadcrumbs are delimited with what appear to be `🮁` characters. Maybe it is but my system has the wrong fonts to display it correctly?

## Context
This has been happening for the last few versions. 

## Versions
KeePassXC - Version 2.6.1
Revision: 9a35bba

Qt 5.15.0
Debugging mode is disabled.

Operating system: macOS Mojave (10.14)
CPU architecture: x86_64
Kernel: darwin 18.7.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
 libgcrypt 1.8.5

**Comment by yan12125** [comment]
I also got issues with that symbol and I cannot find the duplicate, so I post my findings here. Hopefully it will help others.

From the source code the symbol is U+2B29 ⬩ [1]. I got the correct symbol after installing noto-fonts package on my Arch Linux box and restart keepassxc.

[1] https://github.com/keepassxreboot/keepassxc/blob/2.6.1/src/gui/entry/EditEntryWidget.cpp#L805

**Comment by quinncomendant** [comment]
I think the duplicate is #5025.

**Comment by droidmonkey** [comment]
Thats the one

**Comment by yan12125** [comment]
Thanks and sorry for bothering.
