### ISSUE TITLE
 osx 10.15.6 “KeePassXC.app is damaged and can’t be opened. KeePassXC-2.6.1

### ISSUE THREAD

**Issue by dakkusingh** [keepassxreboot/keepassxc#5328]
I upgraded to KeePassXC-2.6.1 and the dreaded 
```
App “is damaged and can’t be opened. You should move it to the Trash” Error on Mac
```

Specifically:
```“KeePassXC.app is damaged and can’t be opened``` started to appear.
Its easily fixable by doing:

```
xattr -cr /Applications/KeePassXC.app
```

Anyone else had this? I am on osx 10.15.6

**Comment by droidmonkey** [comment]
Did you try a fresh install, this isn't an issue that anyone else has encountered

**Comment by hifi** [comment]
Doesn't macOS do that when you try to install from an "untrusted" source and you don't have the tap enabled to do that?

**Comment by dakkusingh** [comment]
Guys, firstly Kudos on the new app. The UI looks *stunning* - awesome job.

@droidmonkey - I tried a fresh install - as in, downloaded the new DMG, moved the app to /Applications - as soon as i did that, the above warning started.

@hifi - I have the "untrusted" setting already enabled, but this seems to be related to issue discussed here https://osxdaily.com/2019/02/13/fix-app-damaged-cant-be-opened-trash-error-mac/

**Comment by tomhundt** [comment]
**+1 on this issue.**  Upgraded from 2.6.0, same as Dakku.  Did the `xattr` thing and was able to run it.  Looking forward to using the new release!

In my case, it wasn't taking "No" for an answer to "You should move it to the trash," so I dragged it from Trash to Downloads, did the xattr to it, and then dragged it to Applications -- with no more popup, and running no problem.  

When the message first came up, I opened System Preferences > Security & Privacy, hoping to see the "Open it anyway" type of option there, but that never showed up.

MacOS 10.15.6 Beta (19G71a).

**Comment by cpjones44** [comment]
I too have this issue with any version I install.

`App “is damaged and can’t be opened. You should move it to the Trash”`

Running the command:

`xattr -cr /Applications/KeePassXC.app`

fixes the problem.

OSX 10.15.6.

**Comment by droidmonkey** [comment]
Have you all tried restarting your mac? That is a common tip given. Also, have you verified the download hash to ensure nothing was altered? This isn't a keepassxc problem, per say, its a random thing that happens to any application.

**Comment by WoLpH** [comment]
I have the same issue and restarting my mac does not fix it. I'm running OS X 10.15.7.

As for checking the file integrity:
```
# sha256sum --check KeePassXC-2.6.4-x86_64.dmg.DIGEST                                                                                             KeePassXC-2.6.4-x86_64.dmg: OK
```

The xattr command helps though. Not ideal but it works.

If I had to guess, I would think that it might be due to a compatibility flag or something which causes it to stop working on some OS X versions.
