### ISSUE TITLE
HIBP database report sorting by Password Exposed column is not logical

### ISSUE THREAD

**Issue by rocketraman** [keepassxreboot/keepassxc#5329]
## Overview

The sorting of the "Password exposed..." column in the HIBP report makes no sense. It looks like it is a simple lexicographical order as opposed to ordered based on the underlying numeric meaning. IOW, the attached screenshot shows the current order, descending:

![image](https://user-images.githubusercontent.com/53049/91069572-95c18700-e603-11ea-836d-9dd38bb8fa44.png)

See that "up to 10,000 times" should be right after "millions of times", but instead is shown after "once" and "up to 10 times".

## Steps to Reproduce
1. Run the HIBP report with a variety of passwords
2. Sort by "Password exposed..."

## Expected Behavior
Sorting by "Password exposed" should make logical sense

## Context

```
KeePassXC - Version 2.6.1
Revision: 9a35bba
Distribution: Snap

Qt 5.9.5
Debugging mode is disabled.

Operating system: Ubuntu Core 18
CPU architecture: x86_64
Kernel: linux 5.7.15-100.fc31.x86_64

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.1
```

Operating System: Linux
Desktop Env: KDE
Windowing System: X11

**Comment by droidmonkey** [comment]
Duplicate

**Comment by rocketraman** [comment]
@droidmonkey Can you reference the dup issue please? I searched before posting and did not find it.

**Comment by droidmonkey** [comment]
I have to find issues for people at least 5 times per day, everyone who can post an issue needs to learn how to use GitHub. Sorry but you are getting my wrath because you asked 😡 

https://github.com/keepassxreboot/keepassxc/issues?q=is%3Aopen+is%3Aissue+label%3A%22plugin%3A+Reports%22

https://docs.github.com/en/github/searching-for-information-on-github/searching-issues-and-pull-requests

**Comment by rocketraman** [comment]
No worries, I was searching for "HIBP" and "sort" and nothing came up, because I see now the issue does not mention HIBP at all. For reference, here it is: https://github.com/keepassxreboot/keepassxc/issues/4976.

**Comment by droidmonkey** [comment]
This is true, you are forgiven :relaxed:
