### ISSUE TITLE
import CSV feature

### ISSUE THREAD

**Issue by adamkapsos** [keepassxreboot/keepassxc#533]
Hi,

Great to see this new platform. I was hoping that one feature that could be introduced is a CSV import. Without one, it's a major switch for users who haven't used some form of Keepass before (i.e. people like me who have Dashlane or other non open source password managers).

I see there's a thread on this subject, but the latest version only has a .kdsb import option. That would be great if this CSV import feature could be introduced.

**Comment by TheZ3ro** [comment]
The CSV import is already in the develop branch and it will be released for 2.2.0 version
