### ISSUE TITLE
Health Check - Option to Show All Entries?

### ISSUE THREAD

**Issue by peternm22** [keepassxreboot/keepassxc#5330]
The Health Check panel only shows passwords that are bad, poor, or weak. It would be handy to have an option to view all entries to see their scores.

I think this feature may have existed at one point. In one of the screenshots on this page: https://keepassxc.org/blog/2020-08-15-keepassxc-password-healthcheck/ There is a checkbox at the bottom that says "Also show entries that have been excluded from reports". This option doesn't appear to be available any longer in 2.6.1 Unless I'm missing it somehow?

**Comment by droidmonkey** [comment]
We dont show Good or Excellent scores on purpose, there is no sense to doing so. This won't be changed.

**Comment by peterbabic** [comment]
I too would really like the checkbox that would also display "Good" score passwords n a report. My use case would be upgrading all to the "Excellent" score. There is no need for me to display those. Although I could edit the source for this in https://github.com/keepassxreboot/keepassxc/blob/f3d88fbd369e4d516510771318f2699ed34c545b/src/core/PasswordHealth.cpp#L47 and recompile

**Comment by droidmonkey** [comment]
On second look I think this could be a useful feature and is trivial to add

**Comment by shotor** [comment]
@droidmonkey did you ever add this? I only see scores for weak passwords..

**Comment by droidmonkey** [comment]
Just show the password score column in the main few and click the "all entries" saved search in the lower left.

**Comment by shotor** [comment]
@droidmonkey I created a PR because I'd like to see the scores too 😬 https://github.com/keepassxreboot/keepassxc/pull/11850
