### ISSUE TITLE
More efficient space usage on the toolbar when in "text under icon" mode

### ISSUE THREAD

**Issue by Noir-** [keepassxreboot/keepassxc#5331]
## Summary
This is a semi-bug in my opinion.
When the toolbar button style is "text under icon", the space used for each icon is very high. Depending on the configured locale, the window width must be >1400 px to display all items.

### Current state
Thats's the toolbar with the English locale which takes ~1430 px width:

![image](https://user-images.githubusercontent.com/6486186/91065008-42196280-e630-11ea-9636-7ae9e89080f9.png)

Now with the German locale which takes ~1640 px width:

![image](https://user-images.githubusercontent.com/6486186/91065515-df749680-e630-11ea-97dd-7c0ba56de82e.png)

And it can get even more extreme if you try Russian or French. The "compact mode" has almost no effect on the total width.

### Improvements
Since German is my native language, I experimented only with that. The base was the normal view, not the compact.

Here's a mock-up of an optimized toolbar layout which has a width of ~1260px:

![image](https://user-images.githubusercontent.com/6486186/91077426-544fcc80-e641-11ea-9ea8-bb5bd0daf62d.png)

The changes:

1. Text arrangement: There's an static width (measures by the biggest word) for each icon so that the label text breaks into a second line when it's to big.
2. Text: The three dots at the end of some labels were omitted since they don't add real value to the user experience.
3. Separators: I omitted the separators between the lock and generator buttons (I think there's no big logical distinction between these icons) and between the settings and the search bar (These elements are already visually distinct).
4. Minor wording hacks: I hyphenated "Passwortgenerator" since this is allowed in German grammar. Changed "Einstellungen" to "Optionen" to save a bit space.

Not in the mock-up yet but in the mid-term there might be also a better location for the search bar.

### Implementation details
I think the MVP is a semi-static bounding box for the buttons based on the configured locale. This would be a compromise between a clean layout and space usage.

Hyphenation might be tricky since this is specific to the locale but maybe it would be sufficient to treat the dash as an optional token for line breaks.

## Context
I think the display of text under the icon is the most accessible version of the GUI for new and non-tech users. The new icons are a really great improvement but letting an user guess icons (or hover-guess) is still bad UX. For a new user, even with text it's not 100% clear what each button does without trying or reading the manual.

Once the required space would be on an acceptable level, I would even pledge to set this layout as default for new installations.

**Comment by droidmonkey** [comment]
We dont control this layout, this is a Qt thing. There is nothing we are going to do (or can do) to change this.

**Comment by Noir-** [comment]
> We dont control this layout, this is a Qt thing
Ok this is bad news... I'm not really in QT yet and thought that this is just QML. Looks like there's almost nothing to configure with this kind of widget.

> text below the icons is entirely redundant
Even though there's no quick-win with this problem: I wouldn't have opened this ticket if this wouldn't represent a problem on my side.

I have to deal with a lot of users who aren't tech savvy and my experience is that labels help a lot to ease the experience. People are very used to it since most big applications like Office, Android, iOS etc. implement it this way. As long as users aren't very used to an icon (it's the case with open, save, search and settings), it increases the cognitive load for them. This brain power is better spent with maintaining a basic operational security level (which is already hard enough) rather than deciphering user interfaces.

And yes, there's a manual... but there are some problem with manuals in general and this one in particular. But that's a different issue.
