### ISSUE TITLE
release 2.6 significantly increased row height in listing of entries, increasing need/extent of (vertical) scrolling

### ISSUE THREAD

**Issue by friend18** [keepassxreboot/keepassxc#5332]
I have many entries in my keepassxc database.  Nearly all entries have favicons.  I'm running Fedora 32.
With the latest release (2.6), in the default listing of Entries (with column titles "Title ... Username ... URL ... Notes ... etc."), the height of each listing is significantly more than in previous releases.  This change forces me to scroll (whether by mouse wheel, scroll bar, or whatever) much, much more than previously, when I'm trying to locate the entry I wish to access.  It's not a fatal error, obviously, but it is a much-noticeable annoyance.

Is there any way for a user to revise (i.e., decrease) the row height?  If not, please consider adding the capability.

Thank you.

**Comment by droidmonkey** [comment]
Use compact mode in the view menu
