### ISSUE TITLE
Generated password doesn't include characters from advanced settings until they're interacted with

### ISSUE THREAD

**Issue by aknj** [keepassxreboot/keepassxc#5336]
## Overview
When the password generator window opens with advanced settings already revealed, and some groups already selected (last used settings), the generated password doesn't include any characters from those groups, unless the user interacts with the settings in some way. Clicking the regenerate password button (Ctrl+R) doesn't change this state.

## Steps to Reproduce
1. Navigate to Entries > New Entry
2. Click Generate Password
3. Click Advanced button to reveal the sub-groups
4. Turn on all special character sub-groups
5. Click Apply
6. Click Generate Password again
7. Click Reveal Password (Ctrl+H)

## Expected Behavior
The generated password includes characters from advanced settings selected last time.

## Actual Behavior
The generated password doesn't include characters from advanced settings selected last time. 
(But, kind of misleadingly, the buttons with the groups selected last time are highlighted.)

## Context
~Also, from what I can tell, this behaviour only occurs in the generator opened from the New Entry view, not the one on the toolbar.~

_

KeePassXC - Version 2.6.1
Revision: 9a35bba

Qt 5.15.0
Debugging mode is disabled.

Operating system: Windows 10 Version 2004
CPU architecture: x86_64
Kernel: winnt 10.0.19041

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
ibgcrypt 1.8.5

**Comment by droidmonkey** [comment]
This is unfortunate, confirmed.
