### ISSUE TITLE
Open database using Apple Watch "double tap" confirmation feature on MacOS

### ISSUE THREAD

**Issue by pretzelmonster** [keepassxreboot/keepassxc#5337]
Hi,

it would be great to be able to unlock the database using the Apple Watch (double tap) on MacOS. Also TouchID / FaceID like Strongbox allows it on MacOS would be great (but I don't have devices supporting this yet).
https://strongboxsafe.com/feature-comparisons-ios-mac-free-pro/

Any plans to integrate this?

Thanks for the really great application, I like the very well working browser integration which was my main reason to use KyPass before (which hasn't been updated in a year or so).

Best regards!

**Comment by droidmonkey** [comment]
I need to buy an iWatch...

**Comment by tqml** [comment]
I might have an easy solution for this but I am not able to test it due to troubles with code signing...

The debugging output is
```
DEBUG: TouchID::storeKey()
DEBUG: TouchID::storeKey - Status deleting existing entry: -25300
DEBUG: TouchID::storeKey - Status adding new entry: -34018
```

**Comment by yuriykuntsyak** [comment]
> I need to buy an iWatch...

Apple Watch Series 6 owner here. @droidmonkey please let me know if I can help with tests
