### ISSUE TITLE
Yubikey stopped working with latest upgrade

### ISSUE THREAD

**Issue by Coeos3** [keepassxreboot/keepassxc#5338]
Hi,
I use a Yubikey as a hardware key for the login. This stopped working with the latest update. Once I selected the Yubikey, typed in the password and click OK, everything greys out and stays like that. Typically it should ask me to press the button on my Yubikey to confirm the login. 

Here is some debug info:
KeePassXC - Version 2.6.1
Revision: 9a35bba

Qt 5.14.2
Debugging mode is disabled.

Operating system: Fedora 32 (Thirty Two)
CPU architecture: x86_64
Kernel: linux 4.19.132-1.pvops.qubes.x86_64

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.5

**Comment by droidmonkey** [comment]
Does pressing the yubikey work? Perhaps the notification is not showing for you for some reason but its still waiting for the press.

**Comment by Coeos3** [comment]
I tried that but it didn't work.

**Comment by droidmonkey** [comment]
What version did you upgrade from?

**Comment by Coeos3** [comment]
I used 2.5.3. When downgrading back to that version it works fine too.

**Comment by Zocker1999NET** [comment]
Maybe KeePassXC requires a newer version of a library, because I have no problem with 2.6.1 and my YubiKey 5, here are my system infos:

KeePassXC - Version 2.6.1
Revision: 9a35bba

Qt 5.14.2
Debugging mode is disabled.

Operating system: Debian GNU/Linux bullseye/sid
CPU architecture: x86_64
Kernel: linux 5.7.0-2-amd64

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (only unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.6

**Comment by Coeos3** [comment]
Everything is up to date, unless fedora hasn't released some updates already available on debian.
Do you also require to touch the Yubikey to confirm the login?

**Comment by Zocker1999NET** [comment]
I also require to touch the YubiKey.

I do not know how Fedora releases new package versions while maintaining a stable system, but seeing your old kernel version (< 5) reminded me of Debian Stable, where new versions aren't released (for most of the packages), only bugfixes and security updates will be patched into the selected stable version until an upgrade is done (for example from Stretch to Buster). Maybe Fedora follows a similar strategy.

I noticed a difference in our debug information pastes: you are using libgcrypt 1.8.5 while I am using libgcrypt 1.8.6, maybe this does cause this issue?

**Comment by droidmonkey** [comment]
Does it freeze if you try to unlock without the yubikey plugged in?

**Comment by Coeos3** [comment]
It works as expected without the Yubikey: I get an error saying invalid credentials. (and databases not needing a yubikey unlock fine).

I've tried with kernel 5.6, doesn't change anything though. I'm only running the stable versions, so 1.8.5 is the latest for fedora.

**Comment by droidmonkey** [comment]
If you create a new database and assign the yubikey to it, does that one unlock?

**Comment by Coeos3** [comment]
I can't actually save a new DB with the yubikey as I need to touch the first time I save it and that also "freezes".
Just to clarify what I mean by freeze: everything is greyed out and nothing happens, touching the yubikey doesn't help. The app itself isn't frozen though, I can still toggle between DB tabs, or open the app menus (the same is true when trying to unlock an existing DB). If I click "save" again, then I get an error saying "writing the database failed: Database save is already in progress"

**Comment by droidmonkey** [comment]
Ok good, what type of yubikey do you have? Have you tried running our appimage or snap build to rule out your system libraries?

**Comment by Coeos3** [comment]
I use the Yubikey 5 NFC.

Running the AppImage works fine.

**Comment by droidmonkey** [comment]
Then this is a problem with a system library or the build provided by Fedora.

**Comment by Coeos3** [comment]
Issue is solved -  I finally got around to get a clean install of Fedora and that fixed the issue. Sorry for the hassle.
