### ISSUE TITLE
AutoOpen of additional databases does not work any more

### ISSUE THREAD

**Issue by m-brandl** [keepassxreboot/keepassxc#5342]
Hi,

I used to be able to have a second database automatically opened by creating a group called "AutoOpen" and an entry in that group containing the relative path of the second database in the URL field and the password. But the second database does not open automatically any longer.

Has this feature been removed, or is it just broken?

Debug info:
KeePassXC - Version 2.6.1
Revision: 9a35bba

Qt 5.15.0
Debugging mode is disabled.

Operating system: Windows 10 Version 2004
CPU architecture: x86_64
Kernel: winnt 10.0.19041

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.5

**Comment by droidmonkey** [comment]
Are you using the "IfDevice" feature?

**Comment by m-brandl** [comment]
> 
> 
> Are you using the "IfDevice" feature?

Apparently...yes, I was. Keepass2Android had added the attribute, and it prevented the secondary database from auto-opening on the PC. Removed it and it works again. 

Thank you!

**Comment by PolyMMA** [comment]
Same issue here! Thanks for the spot-on feedback. Almost wrote an issue on this myself...  :+1:
