### ISSUE TITLE
Add health status to entry view columns

### ISSUE THREAD

**Issue by stefan1983** [keepassxreboot/keepassxc#5343]
Would it be possible to show duplicate passwords in a better way like Apple does it in Safari (!) already next to each PW?

<img width="852" alt="image" src="https://user-images.githubusercontent.com/8542806/91315195-ab77ad80-e7b7-11ea-801e-af650ee7453e.png">

Without the need to run / go into health check view?

**Comment by droidmonkey** [comment]
We have decided to use the Database Reports as the central place for this information.
