### ISSUE TITLE
TOTP information lost exporting a database to CSV

### ISSUE THREAD

**Issue by friend18** [keepassxreboot/keepassxc#5345]
## Overview
TOTP information not included when database exported to CSV

## Steps to Reproduce
1. Set up TOTP for some database entry.
2. Export the database into CSV.
3. Import that database, and see that the entry no longer has TOTP information.

## Expected Behavior
TOTP information included (along with account names, passwords, etc.), so that a round-trip through a CSV file does not lose that information.

## Actual Behavior
TOTP information was lost in a round-trip through a CSV file.
This was especially disconcerting because when an export-to-CSV action is taken, KeePassXC pops up a window saying
     You are about to export your database to an unencrypted file. This will leave your passwords and sensitive
     information vulnerable! Are you sure you want to continue?
Since TOTP information is certainly "sensitive information", I assumed it was included in data written to the CSV file.
That's why I'm filing this as a Bug Report, rather than a Feature Request.

## Context
I wanted to make changes to many entries' titles, enough that I didn't want to open each entry, do the edit, and then "OK".
Instead, I thought that I could export the database into a CSV file, text-edit the CSV, and then import the edited file back into KeePassXC.  Everything worked as expected, **EXCEPT** that TOTP information (that was present for some entries in the database) was not present in the imported database.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.1
Revision: 9a35bba

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: Home-brewed (using fvwm)
Windowing System: X11

**Comment by droidmonkey** [comment]
Duplicate #3541
