### ISSUE TITLE
 Transparent login screen & symbol bar [macOS 10.13.6 / KeepassXC 2.6.1]

### ISSUE THREAD

**Issue by jschmdt** [keepassxreboot/keepassxc#5347]
KeePassXC - 2.6.1
macOS High Sierra 10.13.6

**Bug**
When I start KeePassXC the DB login-screen is completely transparent. After selecting and logging into a database the symbol bar stays transparent. As soon as I resize the window the transparency vanishes and the black background for the symbol bar returns to normal.

**Comment**
I think its an OS Issue. On my macbook with the newest macOS Catalina everything works fine. 
Unfortunately I can't update my desktop computer because of NVIDIA drivers that It need for motion & 3D stuff ;)

**Screenshots**
I attached some screenshots that show the problem. I used a blueish background so you can see where the transparency is visible... The transparency is also saved when I screenshot the programm window on macOS.

![keepass_transparent_01](https://user-images.githubusercontent.com/36086898/91438655-ff43ce80-e86b-11ea-9167-7e891af2f275.jpg)
![keepass_transparent_02](https://user-images.githubusercontent.com/36086898/91438667-02d75580-e86c-11ea-9786-c45685c60d65.jpg)

Cheers

**Comment by varjolintu** [comment]
I had a similar problem with my High Sierra machine and Nvidia drivers. Sadly the only fix was to upgrade the OS.

**Comment by phoerious** [comment]
Do you have a Hackintosh or something similar with an Nvidia GPU?

**Comment by jschmdt** [comment]
Yes, I do. I'm running macOS with a GeForce 1080 Ti, latest Web Driver installed: 387.10.10.10.40.138

**Comment by phoerious** [comment]
I suppose its not an "official" configuration you could buy from Apple?

**Comment by varjolintu** [comment]
There's no fix for it if you are running a Hackintosh.

**Comment by jschmdt** [comment]
Check. It's custom built. The bug started appearing with 2.6.0 - older builds of KeepassXC ran without any issues on my config.

**Comment by phoerious** [comment]
Which is weird, because QToolBar uses the same transparency trick to show a semi-native macOS toolbar.

**Comment by xargi** [comment]
I'm seeing this same issue on an actual MacBook Pro (Retina, 15-inch, 2015), Intel Iris Pro running on 10.13.6.

**Comment by wisobe** [comment]
I have the same issue with a MacBook Pro 2011 - OSX High Sierra 10.13.6. Usage is OK but it's rather sad the UI is not rendered correctly.

**Comment by MrSoulPC915** [comment]
I have the same issue with a Mac Pro (late 2013) on macOS High Sierra (10.13.6).

Small precision, sometimes the background is transparent, sometimes it is black (I still haven't figured out what makes that difference.).

**Comment by varjolintu** [comment]
I'm glad the fix was found. I honestly thought this was not fixable at all, and blamed Nvidia drivers for it.

**Comment by droidmonkey** [comment]
Can someone on this thread please use the below DMG to test if the background problem is fixed?

https://code.launchpad.net/~droidmonkey/+snap/temp/+build/1142007/+files/keepassxc_2.6.1_amd64.snap

This is a build from #5482

**Comment by jschmdt** [comment]
Hey droidmonkey, glad you found a fix :-) I'd like to test it, but how do i open ".snap"-DMGs? A snap file was attached in the link in the notification mail … And I just send you an access request for google drive.. in case the google drive link is with the normal DMG image ;) thx for info!

**Comment by droidmonkey** [comment]
Sorry had an issue with Google Drive, use this link now: https://drive.google.com/file/d/1xJHLy7e_fSQNSyePFdwleIsnPKR2zZbs/view?usp=sharing

**Comment by wisobe** [comment]
Hi ! I downloaded and installed the version. I have an error when opening Keepassxc: KeePassXC quit unexpectedly.

**Comment by jschmdt** [comment]
KeepassXC crashes instantly when opening, here's the log:

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x4] Symbol missing

Dyld Error Message:
  Symbol not found: ____chkstk_darwin
  Referenced from: /Applications/KeePassXC.app/Contents/MacOS/../Frameworks/libgcrypt.20.dylib (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib

**Comment by droidmonkey** [comment]
Le sigh....

**Comment by droidmonkey** [comment]
Fixed the dmg, forgot to build using the MacOS target version flag.

https://drive.google.com/file/d/1xJHLy7e_fSQNSyePFdwleIsnPKR2zZbs/view?usp=sharing

**Comment by wisobe** [comment]
Hi @droidmonkey ! Thanks for trying to figure this out. Highly appreciated. :-) 

I'm having the same error as before when opening KeepassXC. Same content as @jschmdt.

**Comment by jschmdt** [comment]
Me too, same error message as before:

Termination Reason:    DYLD, [0x4] Symbol missing … etc.

**Comment by droidmonkey** [comment]
Nevermind, I retooled the fix to completely prevent using the Transparent background.

**Comment by wisobe** [comment]
Hi !

Seems like the same crash occurs with the 2.6.2 version. :-s

**Comment by droidmonkey** [comment]
Restart your mac. This is a silly bug with macOS notorization handling.

**Comment by wisobe** [comment]
Hi !

This doesn't seem to do the trick. I'm wondering if the minimal system requirements have been levelled up with this new minor release ? I'm asking because of the error message I've pasted below. It mentions OSX 10.15.

Dyld Error Message:
  Symbol not found: ____chkstk_darwin
  Referenced from: /Applications/KeePassXC.app/Contents/MacOS/../Frameworks/libgcrypt.20.dylib (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib

**Comment by droidmonkey** [comment]
There must have been an update to libgcrypt that has caused this problem.

**Comment by phoerious** [comment]
I believe the brew formula is missing an explicit target release to build for, so it assumes the one that it is built on.
