### ISSUE TITLE
[2.6.1] -WITH_XC_UPDATECHECK=OFF does not prevent KXC from asking user to check for updates

### ISSUE THREAD

**Issue by Germano0** [keepassxreboot/keepassxc#5350]
Fedora co-maintainer here.
`-WITH_XC_UPDATECHECK=OFF` should disable automatic updates check at KeepassXC startup. By the way I have been reported by Fedora users that the first time you run KeepassXC (from a clean OS installation, I tried myself too), you will be prompted for `Would you like KeePassXC to check for updates on startup?` After the user answers the question, a flag `UpdateCheckMessageShown=true` is added to file `~/.config/keepassxc/keepassxc.ini`
The flag should prevent KeepassXC from asking this question.

**Comment by droidmonkey** [comment]
Your flag is incorrect, should be `-DWITH_XC_UPDATECHECK=OFF` the question is properly guarded:

https://github.com/keepassxreboot/keepassxc/blob/fd3cc7e8c3d012d74d649773eb2236bd06f12fbc/src/gui/MainWindow.cpp#L968-L989
