### ISSUE TITLE
2.6.0 & 2.6.1: browser extension does not find entry

### ISSUE THREAD

**Issue by boozezela** [keepassxreboot/keepassxc#5351]
## Overview
When using KeepassXC 2.6.0 and 2.6.1 on different platforms with different browsers, the extension cannot find login entries.

## Steps to Reproduce
1. KeepassXC is closed
2. Go to a website that requires login credentials (in my case it was gmail asking to confirm my account)
3. Note how there is a lock on the KeepassXC icon next to the username field
4. Launch KeepassXC and unlock the database
5. Go back to the browser, click on the KeepassXC extension icon, then click on the "Reload" button
6. Since the lock is still present on the icon, reload the page where the credentials are required
7. Note how the lock disappeared from the KeepassXC icon next to the username field
8. Click on the KeepassXC icon next to the username field
9. The extension returns "Error! No Logins found"

## Expected Behavior
Once I click on "Reload", and the lock disappears from the KeepassXC icon, I would expect the extension to retrieve the credentials.

## Actual Behavior
The extension returns "Error! No Logins found".

## Workaround 1 (quick)
While KeepassXC is still open with the database unlocked close and reopen the browser.

## Workaround 2 (convoluted)
While KeepassXC still is open with the database unlocked click on the KeepassXC extension icon, then:
1. Click on the red padlock icon
2. Click on the "Reopen database" button
3. Unlock the database when KepassXC is in focus

Now the extension can find the credentials the page needs.

## Debug info platform 1:
KeePassXC-Browser extension: 1.6.6
Browser: Chrome 84.0.4147.135

KeepassXC - Version 2.6.0
Revision: 0765954

Qt 5.15.0
Debugging mode is disabled.

Operating system: macOS Mojave (10.14)
CPU architecture: x86_64
Kernel: darwin 18.7.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
 libgcrypt 1.8.5

## Debug info platform 2:
KeePassXC-Browser extension: 1.6.6
Browser: Firefox 79

KeePassXC - Version 2.6.1
Revision: 9a35bba

Qt 5.15.0
Debugging mode is disabled.

Operating system: Windows 10 Version 2004
CPU architecture: x86_64
Kernel: winnt 10.0.19041

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.5

**Comment by boozezela** [comment]
Could this be a byproduct of #5299?

**Comment by droidmonkey** [comment]
Its a duplicate yes

**Comment by boozezela** [comment]
Thanks. I wasn't sure this was a duplicate as reading through #5299 I had the feeling that was more related to the "matching credentials" algo.

**Comment by varjolintu** [comment]
@boozezela 2.6.0 is not affected. I couldn't reproduce your problem with the 1.7.0-beta1 of the extension. You can try it yourself if it solves the problem: https://github.com/keepassxreboot/keepassxc-browser/releases/tag/1.7.0-beta1

**Comment by boozezela** [comment]
@varjolintu thanks, I will give it a try and report back.

**Comment by boozezela** [comment]
Unfortunately KeepassXC-browser 1.7.0b1 fails with "Key exchange was not successful" and it's not possible to trigger the browser key integration.
I have removed all the browser keys from the DB, removed the old extension from the browser, restarted both, reinstalled 1.7.0b1 to no avail. 

As soon as I have reinstalled version 1.6.6 and clicked on the "Connect" button KeepassXC came into focus and I was able to connect the two. :/

**Comment by varjolintu** [comment]
@boozezela With Firefox everything works straight from `about:debugging`. With Chromium you'll need to modify the corresponding JSON script to accept the temporary extension's ID. See https://github.com/keepassxreboot/keepassxc-browser/wiki/Loading-the-extension-manually

**Comment by boozezela** [comment]
Thanks, I'll give it a try in a few hours.

**Comment by boozezela** [comment]
As a quick update: I have been trying to reproduce the bug with KeePassXC-Browser 1.6.6 before trying the beta, and now that I need to reproduce it the bug suddenly became elusive.

I am throwing the towel for now. :/
