### ISSUE TITLE
Fourth tray icon type, "Monochrome (automatic)"

### ISSUE THREAD

**Issue by MageJohn** [keepassxreboot/keepassxc#5352]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
Add a fourth tray icon type, "Monochrome (automatic)", that switches between light and dark with the system theme.

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
I'm currently using KeePassXC on macOS, with the system set to automatically switch between light and dark themes. This means that either of the monochrome tray icons (menu bar icon in Mac native terminology) are going to be wrong half the time. The icon is completely invisible when it doesn't match the theme, so it's not usable.

For now I've set the icon to Colorful, which is usable in both light and dark modes, but the color doesn't match the rest of the menubar.

**Comment by phoerious** [comment]
We are certainly not going to add a fourth option. If anything, we'd reduce the two to a single option "Monochrome". The reason why we have both is that on most platforms we have no idea what the user's taskbar colour is (including Windows). macOS is the only platform where we could infer it from the theme (and we are already doing it, but only on first start, not when you switch themes later on).

**Comment by tvrznikmichal** [comment]
Back to automatic is possible by removing this key
`TrayIconAppearance=colorful`
 in keepassxc.ini

**Comment by phoerious** [comment]
You don't have to modify the init file. You can simply change the setting in the application options.

**Comment by tvrznikmichal** [comment]
> You don't have to modify the ini file. You can simply change the setting in the application options.

Yes, that's true, i was confused by only dark/light options, but it works automatically when you for example set dark icon in light theme.

**Comment by MageJohn** [comment]
I think the underlying reason for this issue was fixed by 80c1b9be6a09cee67411840ecde129bcab70ebe1, so I'm happy to close this issue.
