### ISSUE TITLE
KeepassXC-related process are not terminated upon exiting the application [Windows 10 2004 / KeepassXC 2.6.1]

### ISSUE THREAD

**Issue by boozezela** [keepassxreboot/keepassxc#5353]
## Overview
Occasionally (usually after waking the computer up) when exiting the application, KeepassXC-related processes are not terminated properly.

As a result, it is not possible to launch KeepassXC anymore, and there is no way to give focus to the existing running KeepassXC.exe process.

## Steps to Reproduce
1. Launch KeepassXC and unlock the database
2. Leave it open for a couple of hours
3. Put the computer to sleep
3. Wake the computer up
4. Close KeepassXC
5. Wait a few seconds
6. Reopen KeepassXC

Note that the above is inconsistent and difficult to reproduce.

## Expected Behavior
The KeepassXC related processes should terminate.

## Actual Behavior
KeepassXC does not start, since its processes are already running.

## Debug info
KeePassXC - Version 2.6.1
Revision: 9a35bba

Qt 5.15.0
Debugging mode is disabled.

Operating system: Windows 10 Version 2004
CPU architecture: x86_64
Kernel: winnt 10.0.19041

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.5

**Comment by boozezela** [comment]
The behaviour I have experienced seems similar to what described within #4650.

**Comment by droidmonkey** [comment]
Exactly the same problem, no known reason or fix.
