### ISSUE TITLE
Delete the password from the clipboard

### ISSUE THREAD

**Issue by ZER0-X** [keepassxreboot/keepassxc#5357]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
KeePassXC don't delete the clipboard when copying the password twice before the first time expires.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. copy the password
2. copy another password or username

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
The second password is deleted, but the first one available  in the clipboard, i think KeePassXC only deletes the last text.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
When copying the first password and then copying another before the first  expiry, KeePassXC deletes the second password, but the first one remains available in the clipboard.

## Context
[NOTE]: # ( Give us any additional information you may have. )
The Clipboard history feature is enabled in my Windows machine.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC -  Version 2.6.1
Revision: 9a35bba

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows
Desktop Env: Gnome/KDE/XFCE/Mate/Cinnamon
Windowing System: X11/Wayland

**Comment by droidmonkey** [comment]
Duplicate #2358
