### ISSUE TITLE
visualize preview

### ISSUE THREAD

**Issue by PastelRanger456** [keepassxreboot/keepassxc#5358]
i closed the preview tab pressing the x on the tab. now from the menu i click on the buttun "show preview tab" but i can't visualize again the preview tab. i'm using italian translated version KeepassXC 2.6.1 ubuntu 20.04

**Comment by droidmonkey** [comment]
The X just hides it temporarily. When you clicked the view menu item you unchecked the setting and hid it permanently. Just click the view menu item again.
