### ISSUE TITLE
Minimize to Tray on Fedora 32

### ISSUE THREAD

**Issue by Apcio** [keepassxreboot/keepassxc#5359]
I am using Fedora 32 with Wayland desktop server and GNOME environment.
I have checked options "Show a system tray icon" and "Hide window to system tray when minimized", but after clicking minimize button, window is minized and showing after ALT+TAB combination, and there is no icon in system tray.
I have switched to X11 desktop server, and it works perfect.
Is possible to fix it in Wayland ? This is issue only on my machine, or it is known behavior ?

**Comment by droidmonkey** [comment]
Do you have a tray at all under wayland? If the tray icon is not showing then minimize to tray will never work.

**Comment by Apcio** [comment]
I do not know how to check. I have in the right upper corner icons: volume, wifi, battery, and when connect by GSConnect with my phone, there is a Phone Icon and whit submenu.
I have installed GNOME extension Tray icons.

**Comment by droidmonkey** [comment]
Those are system icons not application icons.

**Comment by Apcio** [comment]
AMAZING!
I did not known that this have other name than tray icon and I couldn't found worked extension, but starting searching as application icon I have installed Kstatusnotifieritem/appindicator suppor extension, switch to Wayland and it works!
Thank you :+1:

**Comment by Cherkah** [comment]
I am using majaro with Wayland desktop and KDE/Plasma environnement.
SETTINGS kpxc (options): 
      - Show a system tray icon 
      - Hide window to system tray when minimized.
      - system settings > start & stop > automatic starting > keepassxc

DESCRIPTION:
under Wayland: at the system start-up, the system launch the app. kpxc window appaered but no hinding in system-tray & no icon in the system-tray.
so No minimizing of kpxc in the tray. But i have a functional tray with some app like Qalculate, Feathernotes or Todolist wich are operational

REPRODUCE:
Apply the above settings with the following system:
     Operating System: Manjaro Linux
     KDE Plasma Version: 5.20.3
     KDE Frameworks Version: 5.76.0
     Qt Version: 5.15.1
     Kernel Version: 5.10.0-1-MANJARO
     OS Type: 64-bit
