### ISSUE TITLE
Set default size of Auto-Type selection dialogue

### ISSUE THREAD

**Issue by mwip** [keepassxreboot/keepassxc#5361]
I want to propose a feature (if it is not already there and I just didn't find it). My window manager (Xmonad) always shrinks the Auto-Type selection dialogue. I tried to set it to a specific size from the WM side but it seems that KeePassXC overrules the floating window rules I set.

![image](https://user-images.githubusercontent.com/29728338/91697425-62d24280-eb71-11ea-8e84-12497a589c5b.png)

Is there any way to set the default size of the Auto-Type selection dialogue? I found the section `AutoTypeSelectDialogSize=@Size(554 155)` in `.cache/keepassxc/keepassxc.ini` and tried to change it, but this will be overwritten when I trigger Auto-Type. 

Would it be possible to add a setting, possibly in the Auto-Type settings, to set the default Auto-Type dialogue size?

Systeminfo (Private and Work): 
Arch Linux && Ubuntu 18.04
Xmonad 0.15 && Xmonad 0.13
KeePassXC 2.6.1

**Comment by droidmonkey** [comment]
Resizing the window to fit the contents is desired behavior, but it should not cut off the list. Will be fixed as part of Auto-Type overhaul.
