### ISSUE TITLE
Missing string at Transifex

### ISSUE THREAD

**Issue by smarquespt** [keepassxreboot/keepassxc#5362]
New string missing from source in Transifex. Check below:

![screenshot](https://user-images.githubusercontent.com/1302668/91701106-bbeca700-eb6e-11ea-9784-896cf3d3bdfa.png)

**Comment by droidmonkey** [comment]
Need to upload a new translation file

**Comment by droidmonkey** [comment]
done

**Comment by smarquespt** [comment]
Looks like still something missing: Please check below:

![screenshot](https://user-images.githubusercontent.com/1302668/91850611-b918b180-ec55-11ea-8968-6246c2ce75bf.png)

**Comment by droidmonkey** [comment]
That is a Qt string
