### ISSUE TITLE
Visual glitch in Edit entry

### ISSUE THREAD

**Issue by smarquespt** [keepassxreboot/keepassxc#5363]
## Overview

Visual glicth at  Edit entry

## Steps to Reproduce

1. Right clik on an entry
2. Edit entry

## Expected Behavior
No glitch

## Actual Behavior
Glitch

## Context
Keepassxc 2.6.1 portable
Screen size 1440x900

Note: If I maximize an unmaximize it dissapears for that moment. Next time same glitch.

Check below:.

![screenshot](https://user-images.githubusercontent.com/1302668/91701727-9b711c80-eb6f-11ea-8dcb-17f1fb02f603.png)

**Comment by droidmonkey** [comment]
Su0li

**Comment by toxpal** [comment]
Could you provide a link to the original issue, please? Came here to report the same issue, did search first, but found this post only (which was marked as duplicate). Happens for me since upgrading to 2.6

**Comment by droidmonkey** [comment]
Its already fixed for the next version

**Comment by shrinedrift4553** [comment]
> Its already fixed for the next version

I can confirm this is false and I'm seeing this issue as well. I think you should reopen this. I'm using 2.6.1 on W10. I believe this is a scaling issue. When I switch to 125% scaling, it fixes it. I'm running a 1440p 165hz monitor.

![Screenshot 2020-10-21 035453](https://user-images.githubusercontent.com/73189885/96619051-388d3d80-12f5-11eb-8b28-0e62754fec8f.png)

**Comment by toxpal** [comment]
I believe the nest version @droidmonkey was talking about is 2.6.2 because 2.6.1 was released 2 months ago.

**Comment by shrinedrift4553** [comment]
I see, that makes sense.
