### ISSUE TITLE
Touch ID does not work after restart

### ISSUE THREAD

**Issue by freebrowser1** [keepassxreboot/keepassxc#5365]
## Overview
After closing KeepassXC on macOS and restarting it, I have to fill in my password again, fingering the Touch ID results in 'continue with empty password ?' 

## Steps to Reproduce
* Enable TouchID for unlocking KeepassXC
* Exit KeepassXC
* Open it again

## Expected Behavior
* Fingering the TouchID should open database, just like when entering password.

## Actual Behavior
* It prompts with 'continue with empty password ?' so I have to enter the password again which makes the Touch ID less useful.

## Context
KeePassXC - 2.6.0
Revision: REVISION

Operating System: macOS
Desktop Env: Catalina 15.5

<img width="600" alt="Screenshot 2020-09-01 at 11 55 06" src="https://user-images.githubusercontent.com/26625141/91835692-02fb9a80-ec4a-11ea-9394-497392f5d28e.png">

**Comment by droidmonkey** [comment]
This is working as designed. Touch id is meant for quick unlock, not persistent availability. A restart requires a full unlock again.

**Comment by freebrowser1** [comment]
Weird, because the Linux and Android version do have an option to permanent use the touch ID, so why can this option not be added to the macOS version ?
So then it is a 'feature request'.

**Comment by droidmonkey** [comment]
We dont have an android app, not does Linux support touchid.
