### ISSUE TITLE
Cascaded (stacked) encryption methods?

### ISSUE THREAD

**Issue by SuperHenkie** [keepassxreboot/keepassxc#5366]
## Summary
[TIP]:  # Combine existing ciphers e.g. AES + TwoFish + ChaCha20
[NOTE]: # Currently you can choose between different encryption algorithms i.e. AES or TwoFish or ChaCha20.
It would be great if you can choose to use them all three 'stacked' on eachother. So for example encrypt the data with AES, then encrypt the AES-encrypted data again with TwoFish, and then encrypted this double-encrypted data again with ChaCha20. Decryption would of course involve these 3 steps in reverse order. 
Just like VeraCrypt which [also offers this feature](https://www.veracrypt.fr/en/Cascades.html).
Of course the three ciphers should use separate keys, all three independently derived from the main password.

## Examples
[NOTE]: # Besides the currently existing encryption options: AES, TwoFish, or ChaCha20, add a fourth option "Cascade AES + TwoFish + ChaCha20" 

## Context
[NOTE]: # The advantage of this approach is in the theoretical scenario where one or even two of the ciphers get broken, or if a vulnerability or partial attack is found, the data is still secure. 
The chain would be as strong as its _strongest_ link, in this setup.
The performance cost would be negligible even with a large password database.

**Comment by droidmonkey** [comment]
This is totally unnecessary and breaks the kdbx standard.

**Comment by SuperHenkie** [comment]
OK, understand. But perhaps is there a way or place to suggest this for the KBDX standard? (I mean the next KBDX version, if there is gonna be one in the future)

I don't totally agree it's unnecessary. Of course it's not by any means urgent right now. However IF (and that's a big if) a successful attack is developed for any of the used ciphers, even just a partial attack, it would be very reassuring to know you are not exposed to vulnerabilities in any single cipher. This may never happen, or in 10 years from now, or next week. 

Of course I agree it's not worth breaking compatibility (not even an option). But if / when a new KBDX standard is defined in the future, I'd say there is no significant downside to this increase in security?

**Comment by droidmonkey** [comment]
If ghe AES standard is found to have a fault your kdbx database is the least of anyone's target...
