### ISSUE TITLE
Auto-Type new feature

### ISSUE THREAD

**Issue by aryklein** [keepassxreboot/keepassxc#537]
I think it would be very useful if Auto-Type shortcut could use URL entry to match the browser address bar. There are many sites that Title entry doesn't match with the window title, like network devices.

**Comment by TheZ3ro** [comment]
An external process can't directly access a browser address bar.
The only alternative is using an addon like [Add URL to Window Title](https://addons.mozilla.org/it/firefox/addon/add-url-to-window-title/) so KeePassXC can access it.

**Comment by networkjanitor** [comment]
I think what @aryklein means is the following:
https://dev.keepassx.org/issues/231

Afaik Auto-Type only matches window titles with the "Title" attribute in keepassxc. It would be useful if you could instruct it to also match window titles with the "URL" attribute and not just the title.

**Comment by TheZ3ro** [comment]
Seems like a slightly better request then.
I will reopen the issue and adding to wishlist since this feature isn't urgent.

You can set a new autotype window association with title equals to `//twitter.com//`. 
This will match every window title that contains *twitter.com*
