### ISSUE TITLE
What is the meaning of this command-line error sent to stderr ? : QObject::killTimer: Timers cannot be stopped from another thread

### ISSUE THREAD

**Issue by koenlapauw** [keepassxreboot/keepassxc#5370]
![Knipsel](https://user-images.githubusercontent.com/70053534/91886393-90121400-ec89-11ea-8c2f-9df0da6d6486.JPG)
## Overview
When creating a new database, with the portable keepassxc-CLI (x64 Windows version ) i get following error message : 
QObject::killTimer: Timers cannot be stopped from another thread

## Steps to Reproduce
Commandline :
C:\Temp\KeepassXC\KeePassXC-2.6.1-Win64-portable>keepassxc-cli.exe db-create -k C:\Temp\KeepassXC\Tempkey\Test.key  c:\Temp\KeepassXC\tt.kdbx

## Expected Behavior
Behavior is correct - but why is this error generated ?

## Actual Behavior
Behavior is correct

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( KeePassXC - Versie 2.6.1
Revisie: 9a35bba

Qt 5.15.0
De foutopsporingsmodus is uitgeschakeld.

Besturingssysteem: Windows 10 Version 1909
CPU-architectuur: x86_64
Kernelversie: winnt 10.0.18363

Geactiveerde extensies:
- Auto-type
- Browserintegratie
- SSH-agent
- KeeShare (getekend en ongetekend delen)
- YubiKey

Cryptografische bibliotheken:
 libgcrypt 1.8.5 )
KeePassXC - VERSION
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 10 Pro x64
Desktop Env: Windows

**Comment by phoerious** [comment]
That's a Qt-internal warning. Looks like there's a bug somewhere in a part of the code that handles threads. It is probably a very minor defect that is unlikely to affect the normal program flow.
