### ISSUE TITLE
Regex in AutoType Window Associations

### ISSUE THREAD

**Issue by Semnodime** [keepassxreboot/keepassxc#5372]
## Summary
Add (opt-in) feature to support [Regex](https://en.wikipedia.org/wiki/Regular_expression) in AutoType Window Associations

## Examples
Imagine the name of the target window is dynamic,
(but constrained by some easy pattern that can be formulated with regex).

Like `My App 13 - MainWindow` and `My App 144 - MainWindow`.
You know the number changes, the rest stays the same.

## Context
Messenger-App Rambox changes its title name according to the number of unread messages.
While I'll also request an opt-out for this in Rambox, regex allows to address this problem on a broad spectrum.

**Comment by droidmonkey** [comment]
Wildcards are supported
