### ISSUE TITLE
"History" "Keypass XC" and "KeyPass Password Safe"

### ISSUE THREAD

**Issue by misfust** [keepassxreboot/keepassxc#5373]
I have been using "KeyPass Password Safe" for several years.
A few months ago I switched to "Keypass XC".

I have now encountered the following problem:

An entry was created in the "KeyPass Password Safe".
This entry was edited a few days later, the original version appears in the "History" area.

To use "Keypass XC", the database from "KeyPass Password Safe" is used.
Changes, previously noted in "KeyPass Password Safe" are available in the "Keypass XC".
Adjustments to entries created in the "Keypass XC" are noted in the "History" area.
If entries, created in "KeyPass Password Safe" are edited in "Keypass XC", no note appears in the "History" area.

How can this problem be solved?

Operating System: Windows10

**Comment by droidmonkey** [comment]
History works regardless of the application that created the entry. There is no distinction.

**Comment by misfust** [comment]
Entry startet in "KeyPass Password Safe", but the edits I do to the entry in "Keypass XC" do not form a note in "Keypass XC" History.

**Comment by droidmonkey** [comment]
I just tested this and it worked perfectly.

**Comment by 5t0rmr1d3r** [comment]
@misfust what database version is used? 
Maybe that info can help to reproduce the error...
