### ISSUE TITLE
MacOS: Default key for "Add key to SSH agent" is taken by system

### ISSUE THREAD

**Issue by nshtg** [keepassxreboot/keepassxc#5378]
The default key for "Add key to SSH agent" is `Cmd + H` on MacOS. This is a bad choice since this is the default global key for hiding the currently active window and the command does not get executed.

Maybe you could consider `Ctrl + H` similar to Linux?
If that was the case "Remove key from SSH agent" should be changed to `Ctrl + Shift + H` too probably.

KeePassXC - Version 2.6.1
Revision: 9a35bba

Qt 5.15.0
Debugging mode is disabled.

Operating system: macOS 10.15
CPU architecture: x86_64
Kernel: darwin 19.6.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
 libgcrypt 1.8.5

Operating System: macOS

**Comment by nshtg** [comment]
Something similar was done for the password visibility toggle:

https://github.com/keepassxreboot/keepassxc/issues/5114

**Comment by hifi** [comment]
Since I don't have a Mac could @droidmonkey self assign this? 😁

**Comment by droidmonkey** [comment]
Yah I got this
