### ISSUE TITLE
Add more global shortcuts

### ISSUE THREAD

**Issue by force1164** [keepassxreboot/keepassxc#5383]
## Summary
Add more global shortcuts like in official app for windows.
I miss specifically:
- toggling the window into focus so that user do not have to always click the tray icon
- autotype password only - I know it can be set per item as typing option, but I use it for a lot of entries and it would be much simpler to just have the feature out of the box. 

## Examples
Pressing Ctrl + Alt + K instead of clicking
![image](https://user-images.githubusercontent.com/2920574/92263478-f9d62c00-eedc-11ea-9e3d-02392a61b276.png)

Pressing Ctrl + Alt + Shif + A
to fill only password

## Context
I came from windows and the app on windows does have this features and it is easy to get used to them, but then it is hard without them. Thank you

**Comment by droidmonkey** [comment]
Already working this for 2.7.0

**Comment by droidmonkey** [comment]
Covered by #99
