### ISSUE TITLE
Updating to 2.6.1 broke all matching

### ISSUE THREAD

**Issue by lophat** [keepassxreboot/keepassxc#5385]
I normally only enter the domain in the URL in Keepassxc, excluding all http/https and anything after .com. So an entry in my database would look like intel.com instead of https://www.intel.com/partners. This has worked beautifully until the latest release. It also makes more sense to do it this way to me. My browsers automatically take care of the http > https.

Currently over 90% of my saved credentials are not found and I've tried both with/without "best matching..." being checked. It makes no difference.

To me this is a very logical implementation. Can you please either add this as an option or make it a default feature?

Thank you

**Comment by droidmonkey** [comment]
Duplicate, will be fixed in 2.6.2
