### ISSUE TITLE
navigation with TAB key in "edit record" does not work as expected

### ISSUE THREAD

**Issue by vojtapolasek** [keepassxreboot/keepassxc#5388]
## Overview
I am a screenreader user, using Keepassxc under Arch Linux with Orca screenreader.
When I edit a record I use the "TAB" key to move among various edit fields etc.
In 2.5 it worked as expected, I could go through all edit fields from the "record name" up to the "cancel button". In 2.6 it does not work as expected. I can get to the checkbox "show/ hide notes" but then I go directly to the "ok"button. I can't access the "notes" field.

## Steps to Reproduce

1. Create a new record or edit existing one
2.  Keep pressing "tab" key and follow the focus.
3.  You won't get to the "notes" edit field, it will be skipped.

## Expected Behavior
I am able to navigate to the "Notes" field.

## Actual Behavior
I am not able to navigate to the "note" field.

## Context
Linux
Mate
X11

**Comment by droidmonkey** [comment]
Qt is abysmal at tab navigation. As a workaround you can shift-tab from username field into notes. But the notes field traps the cursor, its another improvement we need to make.

**Comment by droidmonkey** [comment]
Duplicate #4852
