### ISSUE TITLE
Paswords are announced when typing with screenreader

### ISSUE THREAD

**Issue by vojtapolasek** [keepassxreboot/keepassxc#5389]
## Overview
I am a blind user, using Keepassxc with Orca under Linux. When I type in passwords (unlocking database, entering new record), they are spoken aloud. Ideally each character should be spoken only as "asterisk" or something like that. I believe this could be fixed easily with QT.
This is not a good security practice. Someone could overhear my password.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1.  Start unlocking database
2.  Turn on Orca screenreader under Linux.
3.  Start typign password
4. You will hear it pronounced char by char.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Asterisk or other symbols pronounced

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
actual characters are pronounced

## Context
Linux
Mate
X11

**Comment by phoerious** [comment]
This is either a Qt or an Orca bug.

**Comment by droidmonkey** [comment]
This was a qt bug at some point, you need to provide your qt version.
