### ISSUE TITLE
OS X 10.11.6 (EI Captain): KeePassHTTP not installed or does not work.

### ISSUE THREAD

**Issue by Drewshg312** [keepassxreboot/keepassxc#539]
Hi!
OS X 10.11.6 (EI Captain)
QT5.8.0

I know it's not safe, but I've decided to test the KeepassHTTP feature.
Built keepassxc this way:
```
$ git clone
$ cd keepassxc
$ mkdir build
$ cd build
$ cmake -DWITH_XC_AUTOTYPE=ON -DWITH_XC_HTTP=ON -DWITH_XC_YUBIKEY=ON -DCMAKE_PREFIX_PATH=/usr/local/Cellar/qt5/5.8.0_2/lib/cmake ..
$ make -j8
```
There is no errors.
Keepassxc info shows this:
![untitled](https://cloud.githubusercontent.com/assets/10493450/25553296/9f71062e-2c64-11e7-9c05-8abd39112f63.jpg)

The Problem is that neither my Firefox's PassIFox, nor Chrome's ChromeIPass see any databases. I am running KeepassXC and unlocking the database, but then in browsers:

**ChromeIPass:**
```
chromeIPass has encountered an error:
Is KeePassHttp installed and is KeePass running?
```
**PassIFox**:
```
KeePassFox has not been configured
KeePassHttp is not running
```
Could you please tell how is it supposed to work?
What am I doing wrong?

**Comment by phoerious** [comment]
You need to enable it in the settings first.

**Comment by Drewshg312** [comment]
Got it... I've rebuilt it a couple times and simply did not notice new section in Settings.
