### ISSUE TITLE
KeepassXC-Browser and multiple users on Windows fails

### ISSUE THREAD

**Issue by stopat** [keepassxreboot/keepassxc#5391]
## Overview
I provided my users with KeePassXC and when they were configuring the browser extension, most were not able to connect the extension with KeePassXC itself. The popup for providing a name for the link never shows up.
This issue sounds a lot like https://github.com/keepassxreboot/keepassxc/issues/1745, but instead on MacOS, it happens on Windows.

## Steps to Reproduce
1. Login to Windows and open KeepassXC
2. Open a supported browser and install the extension/addon
3. Link the two
4. On the same system, login with a different user and repeat the above steps
5. Popup for a name never comes and the browser extension gives errors like 'key exchange failed' or 'keepassxc is not running'.

## Expected Behavior
The second (and third, fourth, etc) user can successfully connect the browser extension with keePassXC.

## Actual Behavior
No question is asked when trying to link the extension and no error messages show up. Only when clicking on the extension icon reveals something about the connection state between add-on and KeePassXC. Debugging the extension in the browser shows messages stating the other end is not responding or available.

## Suspected cause
Just like the aforementioned bug report, I suspect the socket to be the blame. I noticed with ProcessExplorer that the keepassxc-proxy process opens a NamedPipe for the first user to start the browser that is already linked to KeePassXC. Once that is done, any subsequent user cannot create a new NamedPipe, because it is not unique to the user.
The full path is \Device\NamedPipe\org.keepassxc.KeePassXC.BrowserServer
There is no mention of a user, so all users will try to create and use that pipe. Communication will fail, because the pipe is owned by a different user.

I do not know if it is possible to specify a name for the pipe, so it can be unique for every user.

## Debug Info
KeePassXC - Version 2.6.1
Revision: 9a35bba

Qt 5.15.0
Debugging mode is disabled.

Operating system: Windows Server 2012 R2 Version 6.3 (Build 9600)
CPU architecture: x86_64
Kernel: winnt 6.3.9600

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.5

**Comment by droidmonkey** [comment]
This is literally reported late yesterday.

**Comment by stopat** [comment]
Thanks. I searched before creating the issue. Can't do much about people opening issues in the wrong place. Hope it gets resolved in the next version.

**Comment by droidmonkey** [comment]
Yah just interesting we see clusters of reports for random issues. This has been an issue since day 1 of the browser extension, no one has reported till now.
