### ISSUE TITLE
Put theme setting under user interface in settings

### ISSUE THREAD

**Issue by xPaw** [keepassxreboot/keepassxc#5395]
KeePassXC 2.6.1

I was trying to change the theme, but couldn't find it in settings because it's under View -> Theme, which isn't exactly a place I would expect to find it.

**Comment by droidmonkey** [comment]
Its not going to move to settings.

**Comment by xPaw** [comment]
What's the reason for putting it under View menu, if it requries restarting? It's also possible to either duplicate it in settings without removing it from view, or at least adding a hint that the theme can be changed in the view menu.

**Comment by droidmonkey** [comment]
Its in the first section of our documentation.

**Comment by xPaw** [comment]
I still don't see what the relation of putting themes in view menu is, when you have 'user interface' section in app settings.

All other software that I can think of has theme selection in its settings.
