### ISSUE TITLE
[FR] Display number of characters in generated passphrases

### ISSUE THREAD

**Issue by catleeball** [keepassxreboot/keepassxc#5396]
## Summary

~When generating passphrases, it would be nice to have a maximum characters field. This is useful for websites / applications that have an upper limit on how many characters a user's password can be.~

When generating passphrases, it is useful to know how many characters long the passphrase is. Currently this involves using an external tool and regenerating passphrases until an appropriate length is achieved.

It would be nice to have a field that shows how many characters long the passphrase is, similar to the existing entropy field.

## UI Mock-up

Here is a tiny UI mockup. Sorry it looks bad, I used a very simple editor.

~[old mockup](https://user-images.githubusercontent.com/43632885/92334834-6587d880-f046-11ea-9ce3-8a657af26545.png)~

## Notes

See discussion below, this FR was originally for a maximum characters field, but now is for a display of how many characters are in the currently generated passphrase.

~Maximum characters isn't "exactly this many characters". This allows the implementation to be less complex and less costly to run. The purpose is to ensure to generated passphrase will be valid for a given field, and not maximizing the amount of characters used.~

This may overlap with some of the features in issue #4209 . I was worried about overloading that FR with more requests / scope creep, so I filed this separate issue.

**Comment by droidmonkey** [comment]
This along with the proposal in #4209 makes the passphrase generator much more like a password generator. If you have a character limit, just choose less words or use a password.

**Comment by catleeball** [comment]
Respectfully, I feel that this change would improve UX a lot. There is definitely a use case for diceware style passwords that fit into commonly applied character limits.

Even simply listing how many characters are in the generated passphrase would be a good improvement. The following is the current user journey for passphrases:

1. Generate a passphrase, do not know how many characters it is.
2. Copy + paste password into website field. It complains the password is too long (but not how long it is, or how many characters too long)
3. GOTO 1 and hope for the best, or
4. `echo "passphrase" | wc -c"` and try to guess approximately how many fewer words gets you to the ballpark of your limit, GOTO 1

**Comment by droidmonkey** [comment]
My thought was to just show the character count as well, it prevents interference and gives you the information you need

**Comment by catleeball** [comment]
That sounds reasonable to me. I'll change the title and update the first post.
