### ISSUE TITLE
We cannot verify the source of the shared container because it is not signed

### ISSUE THREAD

**Issue by jucajuca** [keepassxreboot/keepassxc#5398]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

I created a new file using keeshare to share passwords from a group. Exporting works fine but importing will show the error: 
**We cannot verify the source of the shared container because it is not signed**

My question is how can I sign the new file so that the error message does not appear?
I see that the file appears listed under KeeShare > Imported certificates. But the signer is unknown. 
I already generated my own personal certificate.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Create a group of passwords
2. Share it to a new file using keeShare
3. Select synchronize
4. Try updating the passwords.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

Import should work. Database origin should be confirmed. 

## Context
[NOTE]: # ( Give us any additional information you may have. )

KeePassXC - Version 2.6.1
Revision: 9a35bba

Qt 5.12.8
Debugging mode is disabled.

Operating system: Pop!_OS 20.04 LTS
CPU architecture: x86_64
Kernel: linux 5.4.0-7634-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.5

Windowing System: X11

**Comment by droidmonkey** [comment]
Change the extension of the keeshare file to .zip and check to see if there is a file named `container.share.signature` within. If you open this file it should contain XML.

**Comment by jucajuca** [comment]
is not a valid zip file. I tried with unzip, archive manager and also some online tools.
unzip:
"End-of-central-directory signature not found. ... "

**Comment by droidmonkey** [comment]
Then you have a kdbx file, rename it to kdbx and use that as your keeshare file.

**Comment by jucajuca** [comment]
pardon? from kdbx to  kdbx? 
I saved it again as kdbx.share and it now seems to work. This file is a zip file.
