### ISSUE TITLE
Keepassxc 2.6.1 Does Not Fit On Screen

### ISSUE THREAD

**Issue by pjc123** [keepassxreboot/keepassxc#5400]
So, I have been using keepassxc since it was first released, but this is the first time that when I start the program that the application does not fit on my computer screen, including version 2.6.0 which is OK.  Event the "X" button is not visible, so I have to use "Kill" to close the app.  The problem does not exist on Windows on the same computer, just Linux Mint 19.3 Cinnamon.

Not sure this helps, but here are some settings that may or may not be related:

Preferences > Font Selection > Text Scaling Factor = 1.5
Preferences > Display > Settings > User Interface Scaling = Normal
Linux kernel 5.4.0-42-generic

**Comment by droidmonkey** [comment]
What is your screen resolution?

**Comment by pjc123** [comment]
Linux Mint 19.3 and Centos 7 are installed on the same laptop and both set to 1920 X 1080, and both have the same problem with 2.6.1 but not 2.6.0.  The laptop is a lenovo T470.  I believe that is the native resolution.

**Comment by droidmonkey** [comment]
What is the output of `env | grep QT_`

**Comment by pjc123** [comment]
Output of env | grep QT_  =
QT_ACCESSIBILITY=1

See attached screen shots of versions 2.6.0 and 2.6.1

![Screenshot 2 6 0](https://user-images.githubusercontent.com/5245501/92615108-c1db3a00-f28a-11ea-8189-eb7f3bf32b8f.png)
![Screenshot 2 6 1](https://user-images.githubusercontent.com/5245501/92615112-c273d080-f28a-11ea-87ce-5a857f30db24.png)

**Comment by droidmonkey** [comment]
The big change between 2.6.0 and 2.6.1 was removing Pass-through scaling of the UI. Since you have a font scale of 1.5 it is likely scaling your ui by 2x now, which makes sense. You can add a QT env var to adjust scaling behavior:

QT_SCALE_FACTOR_ROUNDING_POLICY=PassThrough

**Comment by pjc123** [comment]
Sorry if this is a simple question, but where do I add that environment variable, and how do I make sure it affects only the keepassxc program and not any others, since all my other applications do not have this issue.

Thanks.

**Comment by droidmonkey** [comment]
You can at least test it by opening a terminal and entering `QT_SCALE_FACTOR_ROUNDING_POLICY=PassThrough keepassxc`

**Comment by phoerious** [comment]
Closing, since this is not really a KeePassXC issue.
