### ISSUE TITLE
Ask for credentials when exporting the database

### ISSUE THREAD

**Issue by skrueger8** [keepassxreboot/keepassxc#5403]
## Summary
KeePassXC should ask for database credentials when [exporting databases](https://keepassxc.org/docs/KeePassXC_UserGuide.html#_exporting_databases)

## Examples
A password prompt should pop up when using the export CSV/HTML feature.

## Context
A malicious user (the guy sitting next to you at work/train/wherever) could export all credentials in mere seconds when the database is unlocked and you forgetting to lock the screen. Another second for moving the creds to an USB stick. This should take way more time.

**Comment by droidmonkey** [comment]
They could also save as your database and change the master key.

**Comment by Colfenor** [comment]
what if we implement the condition that:

-> in order to change the current database password the user has to enter the current password **first** and
only then he is allowed to change the current password.

Does this sound reasonable ?

**Comment by ShapeShifter499** [comment]
What if there was an option for databases that have a yubikey/onlykey linked that required that yubikey/onlykey present to export?

It might save people who have a habit of taking their key with them but forgot or didn't realize their database was still open.

**Comment by Grocel** [comment]
> They could also save as your database and change the master key. Once your database is unlocked it is game over for attackers who gain physical access to your machine.

To be honest this doesn't sound like a solid reasoning to me. Leaving the database open unattended is really bad, that's fair point. But your reasoning is an additional argument for adding such a prompt during the master password change as well, not an argument on not adding prompts at all.

These prompt would rather be a protection against low tech trivial attacks. Yes, these are a thing too. You can see this as a build-in damage control. These protect against human factors.

Edit: Oops, I just saw that it is 3+ year old already. I think my above points still apply, though.

**Comment by droidmonkey** [comment]
Thanks for surfacing this as it should be closed. Find a nice, colorful, conversation on this topic here: https://github.com/keepassxreboot/keepassxc/issues/9339
