### ISSUE TITLE
Update not available through Homebrew

### ISSUE THREAD

**Issue by fsdjfhadflkjhsd** [keepassxreboot/keepassxc#5404]
Hi, not a big issue or anything. 
I just tried to reinstall homebrew to get updated to .6.1 through Terminal & Homebrew, but it seems like they .6.0 version is still the latest available that way. As I didn't know who else to contact about it I figured I'd just post here. 
So if anyone could have a look into getting the newest version up for homebrew that would be great. 
Best & thanks for all your work guys!

**Comment by varjolintu** [comment]
According to this 2.6.1 is updated to Homebrew 18 days ago.

https://github.com/Homebrew/homebrew-cask/blob/master/Casks/keepassxc.rb

**Comment by fsdjfhadflkjhsd** [comment]
Thanks a lot for your answer. My fault I guess... Just checked again and always just tried with brew reinstall instead of brew upgrade command.
