### ISSUE TITLE
Disabled SSH-Agent is tested when keeshare integration is enabled

### ISSUE THREAD

**Issue by jschrod** [keepassxreboot/keepassxc#5406]
## Overview

Compilation problem with KeePassXC, release 2.6.1 (git commit 9a35bba3)

When KeePassXC is configured with keeshare integration, but without SSH-Agent-Support (as is the default), `make` tries to test the SSH-Agent-Support nevertheless. This leads to errors.

Since `make install` executes these tests as well, one cannot simply ignore this, but must use `-DWITH_TESTS=OFF`.

## Steps to Reproduce

This is on a Debian10 system, though I doubt that this matters.

1. mkdir build ; cd build
2. cmake -DWITH_XC_KEESHARE=ON ..
    Log file is attached as [cmake-17.log](https://github.com/keepassxreboot/keepassxc/files/5191966/cmake-17.log)
3. make -j8
    Log file is attached as [make-17.log](https://github.com/keepassxreboot/keepassxc/files/5191973/make-17.log)

## Expected Behavior

Make shall not try to compile or call tests in `testsshagent.dir`

## Actual Behavior

Make compiles tests in `testsshagent.dir` and fails

## Context

It took me quite some while to find the minimal CMake-Define that caused the error.
Since you're preparing a 2.6.2 release, maybe you can fix that annoyance and I can use `-DWITH_TESTS=ON` again.

KeePassXC Version:
* Git commit 9a35bba3b702256e025af48260fb56a012676fe4
* Tag 2.6.1

I checked the following commits on branch develop and release/2.6.2; this problem wasn't addressed.

Operating System: Debian10

**Comment by jschrod** [comment]
@droidmonkey  Super-fast reaction, fabulous -- I wish I would be able to find the time to react as fast to bug reports in my own open-source projects...

**Comment by droidmonkey** [comment]
I use FastHub Android app to keep the pulse! The official github app is nice but still clunky.

**Comment by jschrod** [comment]
@droidmonkey Hi Jonathan, would you please care to mention why you closed this bug?

It is still valid on tag 2.6.6, and I don't see any commits on branch develop that fixes it.

Will it remain unresolved, as in WONT_FIX?

**Comment by droidmonkey** [comment]
It was resolved with the refactor to botan on develop branch.
