### ISSUE TITLE
Tab switching and most of the GUI become unresponsive after undocking/docking

### ISSUE THREAD

**Issue by macau23** [keepassxreboot/keepassxc#5410]
## Overview
To identify: Right-click within the KeePassXC GUI. If the context menu appears elsewhere, you have this problem.

When undocking/docking again KeePassXC 2.6.1 becomes unresponsive. I cannot switch between different password database tabs, search no longer works, I cannot really do anything at all with my mouse. I guess it has something to do with QT getting coordinates wrong when switching between different resolution screens.

## Steps to Reproduce
1. Undock
2. Dock
3. Try to use KeePassXC

## Expected Behavior
No difference. KeePassXC works as before.

## Actual Behavior
KeePassXC appears to have crashed - but keyboard navigation is possible, and any newly opened windows (e.g. version number) are usable. Only way to fix the problem is to restart KeePassXC.

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.1
Revision: 9a35bba

Qt 5.15.0
Debugging mode is disabled.

Operating system: Windows 10 Version 1909
CPU architecture: x86_64
Kernel: winnt 10.0.18363

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.5

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 10 1909

**Comment by droidmonkey** [comment]
This is a qt bug
