### ISSUE TITLE
Warning about KeePass2 database file format being obsolete

### ISSUE THREAD

**Issue by sjvudp** [keepassxreboot/keepassxc#5412]
## Overview
When opening a KeePass2 database I get a warning about an obsolete database format that won't be supported in a future version of keepassxc.  However I don't know a newer database format for KeePass2, so I guess the message is just nonsense.  If not, more information should be provided.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Open KeePass2 database file (file says: "Keepass password database 2.x KDBX")

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
KeePass2 database file should be OK as long as KeePass2 supports it (and it does _without_ a warning).

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
![Pop-up Windows (in German)](https://user-images.githubusercontent.com/6734808/92789643-563cbe00-f3ab-11ea-9efa-e5eb292894e6.png)

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.6.0
Revision: ?

[NOTE]: # ( Pick choices based on your environment )
Operating System: OpenSUSE LEap 15.1
Desktop Env: Gnome
Windowing System: X11 (I guess)

**Comment by phoerious** [comment]
You are using an old legacy key file. This warning is not about your KDBX file. Generate a new key file and you're good.

**Comment by sjvudp** [comment]
> You are using an old legacy key file. This warning is not about your KDBX file. Generate a new key file and you're good.

I thought a "key file" is just a file with random bytes in it.  Amazingly file says: "XML 1.0 document, ASCII text, with CRLF line terminators", and actually it's XML with less entropy than I had expected.
So May I ask how a "new" key file will look like, and whether KeePass2 can create those?
Even my latest key file from January this year is XML with "<KeyFile><Meta><Version>1.00</Version>...".

**Comment by droidmonkey** [comment]
Just create one in the database settings. Our key file is pure random data

**Comment by sjvudp** [comment]
> Just create one in the database settings. Our key file is pure random data

As my database and keys are on an USB stick that is used in Linux/keepassxc and Windows/KeePass2, will Windows be able to open the database using such a key file? Reading the KeePass2 documentation I guess: "Yes".
Still I wonder: Why do you declare the only key file format that KeePass2 can generate as obsolete? Does it mean keyfile generation from within KeePass is considered obsolete?

**Comment by phoerious** [comment]
It is the only thing it will generate, but not the only one it can read. And it is certainly not the one people think they are using as you may have noticed. You ate not the first to think you were using a high-entropy "arbitrary" file when in fact you weren't.

**Comment by 40four** [comment]
I know you guys closed this, but I would like to add to the discussion. 

I have been having the same issue as the OP, and I must say, the language used in the warning message is very confusing. To call the key-file generated by the main Windows version of Keepass 'legacy' does not make much sense to me. I made my key with the most current version of Keepass (v2.46).

But if you guys are saying that the crypto used to genereate this key-file is not adequate, then that's another story.  

> It is the only thing it will generate, but not the only one it can read. And it is certainly not the one people think they are using as you may have noticed. You are not the first to think you were using a high-entropy "arbitrary" file when in fact you weren't.

So again, the question wasn't answered. Are you saying the KeepassXC group is taking the stance that the key-file generated by Keepass is insufficient? I'm getting the feeling you guys believe this key-file is not safe to use?

If that is the case, shouldn't the warning message reflect that? Calling it 'legacy' doesn't really help much, when this is what the main Keypass uses. I understand other 'better' formats can be created outside the app, and used, but I imaging most people just use the built in tool. 

Admittedly, my knowledge of cryptography is very shallow. It there is any security reason why we should not use the keys generated by Keepass could you explain why? If not, I don't see any reason to not suppress the warning and continue what I'm doing.

**Comment by droidmonkey** [comment]
We already changed this language for the next major release

**Comment by 40four** [comment]
Thanks, that's good to know. I'll shut my big mouth up 🤐  Looking back, I should have thought about it a little more. Seems obvious to me now it would not be supported if it wasn't safe 🤦🏼 

Thanks for the reply, and for the fantastic product!
