### ISSUE TITLE
Recognize some special KeePass2 URLs

### ISSUE THREAD

**Issue by sjvudp** [keepassxreboot/keepassxc#5413]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
KeePass2 knows about some "special URLs" that keepassxc just treats non-special (i.e.: literally).
Let keepasxc recognize at least a few of them, or at least ignore the tokens it does not handle.

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )
For example `cmd://{FIREFOX} -private-window "https://.../"` opens Firefox (wherever it is in the system) in "Private Mode" with URL `https://.../`. That is it overrides the default browser to Firefox and passes an additional option to it.

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
This feature helps to open an URL in the way it was intended to happen.
Also in the current state it makes it complicated to open the URL correctly.

**Comment by droidmonkey** [comment]
Prefer to implement this using the solution for #4495
