### ISSUE TITLE
Custom fields management

### ISSUE THREAD

**Issue by aspsolution2012** [keepassxreboot/keepassxc#5416]
## Summary
[TIP]:  # ( Custom fields management)
[NOTE]: # ( I think it can be very useful to have the ability to create custom fields in order to be more flexible.)

## Examples
[NOTE]: # ( For example, if you wanted to have an "IP address" field or an "access port" field in addition to the URL field, now it is not possible. )

## Context
[NOTE]: # ( This improvement can be very valuable to make sure you use the software to keep passwords of more complex systems.)

**Comment by droidmonkey** [comment]
And?

**Comment by aspsolution2012** [comment]
Hi, sorry I didn't remove the comment hashtags. can you reopen the topic?

**Comment by droidmonkey** [comment]
Duplicate of #863. You can already add custom fields in the advanced tab of an entry, they just aren't visually present on the main page.
