### ISSUE TITLE
Multi-access management

### ISSUE THREAD

**Issue by aspsolution2012** [keepassxreboot/keepassxc#5417]
## Summary
[TIP]:  # ( Multi-access management)
[NOTE]: # ( I think that for many features this software is one of the best. It has only one lack, A simple multi-user access management. It would be great if I had the ability to create multiple users and multiple user groups and choose who can see that password, who can change it and who can delete it. )

## Examples
[NOTE]: # ( It might work like this:
When KeePass XC opens, you are prompted for your username and password. Once logged in with my user I am shown the databases to which I have access. A user can have access to multiple databases. The interesting feature in this case is being able to choose whether a user has the right to read, modify the database or both. An admin user will have the ability to manage users and user groups. The user who possibly made the change will also be written to the history log. )

## Context
[NOTE]: # ( With a multi-access system, the software would be more than usable even by companies. )

**Comment by droidmonkey** [comment]
Care to expand?

**Comment by aspsolution2012** [comment]
Hi, sorry I didn't remove the comment hashtags. can you reopen the topic?

**Comment by droidmonkey** [comment]
This won't ever be a feature of keepassxc or other keepass derivative products. You can so something like this with keeshare.

**Comment by aspsolution2012** [comment]
sin. The reason is the keepass structure?

**Comment by aspsolution2012** [comment]
How can I make a user access read-only on passwords?

**Comment by droidmonkey** [comment]
Put a keeshare database in a read only network share. Have them set it up as import only. Keeshare is covered in our user manual.
