### ISSUE TITLE
Support secure additional attributes

### ISSUE THREAD

**Issue by Skycoder42** [keepassxreboot/keepassxc#542]
In "vanilla" Keepass, you could mark custom attributes as secure. This way they would be displayed with dots and treated in general with the same security mechanisms as password fields.

## Expected Behavior
When adding a new custom attribute, there should be a checkbox/context action to make the field secure.

## Current Behavior
There is no way to create those, neither are existing fields with that flag displayed as such.

## Possible Solution
Since this is already in KeePass, the kdbx format already supports it. It's propably just a matter of making it accessible in the ui.

## Context
This gets relevant when you need to store additional secret information for an entry, e.g. a HOTP seed, a second password, rescue codes, etc.
There are basically 2 reasons why secure additional attributes are required in those cases:
- Sensitive fields will not be displayed to other persons that are able to look at the application.
- Additional security, because such entries should be treated like passwords, and use the same security mechanisms (prevent paging, in memory encryption, etc.)

**Comment by sainaen** [comment]
I think it's already implemented in the develop branch, see #220.

**Comment by Skycoder42** [comment]
My bad! I searched for it, but only within open issues! Closed as duplicate.
