### ISSUE TITLE
Layout issue in edit entry screen

### ISSUE THREAD

**Issue by Jon-guy30** [keepassxreboot/keepassxc#5420]
## Overview
When you select any entry in the KeePassXC database there's an odd line like a scrollbar in the middle, but it's greyed out, you can't interact with it. 

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Unlock your database.
2. Select "Edit" in any entry in your database.
3. You should see a line in the middle like a scrollbar between the password field and the dice symbol (password generator).

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Entry should display normally.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
There's an extra scrollbar where it shouldn't be.

## Context
[NOTE]: # ( Give us any additional information you may have. )
I tested all the themes, it happens in all of them.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.6.1
Revision: 9a35bba

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 8.1 x64
Desktop Env: N/A
Windowing System: DWM. (Windows)

**Comment by droidmonkey** [comment]
Already reported thank you
