### ISSUE TITLE
[Feature] Intelligently filter group names on search

### ISSUE THREAD

**Issue by Redsandro** [keepassxreboot/keepassxc#5423]
## Summary

Sometimes you cannot find an entry from what you _think_ is a good search term.

Two intuitive mechanisms would help you find this entry.

1. Sometimes you remember the name of the subgroup the entry is in.
2. Sometimes you remember that a _different_ password entry is in the same group as the password you're looking for.

In the first case, when you have many groups and subgroups, the task of opening and closing all those groups in search for the subgroup that could be grouped with different groups is rather cumbersome.

In the second case, when searching for the entry that is a sibling of the entry you want, you cannot easily travel to the sibling. You need to edit the found entry, look for the breadcrumbs, close the entry, and manually navigate to the subgroup.

Both cases could be greatly enhanced if:

1. the group tree only displays the (sub)groups that contain the search results;
2. the group tree also displays group names that match the search query.

---

As seen in the default KeePassXC 2.4.3 that comes with Ubuntu 20.04.

**Comment by droidmonkey** [comment]
Upgrade to 2.6.0 and you gain access to the group search feature using the syntax `g:<group name>`

**Comment by droidmonkey** [comment]
Although I kind of like the idea of the group tree filtering out when searching. This would be a major overhaul to the way search works though.

**Comment by Redsandro** [comment]
> @droidmonkey closed this 3 hours ago

I completely understand tree filtering is not worth a major overhaul. With that said, it's always a sad day to see an idea laid to rest. The wild things we imagine when we were young. :wilted_flower:

**Comment by droidmonkey** [comment]
lol, tis true... but onward!
