### ISSUE TITLE
Password References don't work in upper case.

### ISSUE THREAD

**Issue by DonnKey** [keepassxreboot/keepassxc#5425]
## Overview
The following password reference does not work:
{REF:P@I:8B2F0573A5819B44A4CFF1BA17D2A6F2}

This one does.
{REF:P@I:8b2f0573a5819b44a4cff1ba17d2a6f2}

They differ only by case. The effect is that neither username nor password is autofilled when using the browser plugin.
I was unable to see any error message from either the plugin or KeePassXC itself (but I may not know where to look).

## Steps to Reproduce
Create a _password_ reference with a UUID encoded in upper case. AFAICT the UUIDs generated for data base entries are pure lower case.  Reference UUIDs in upper case DO work as expected for user names (probably because they're case independent.)
I'm not sure how this occurred, but I suspect it was a consequence of moving from KeePass (plain old) to XC.

Related: there doesn't seem to be a way to search for the definition or use of a reference UUID (at least uuid: and UUID: didn't work). (Makes the workaround for this bug (fix case manually) really hard.)

## Expected Behavior
(1) I expected it to enter the user name and password.
(2) In the absence of that, provide some sort of error, rather than simply doing nothing. (I spent a lot of time assuming it was field detection before I figured this out.)  (I realize that in this situation, error reporting is hard. An off-the-wall idea if it's possible: send an eMail to the current user with the error!)

## Actual Behavior
Nothing filled in (a blank stare, as if there were no entry).

## Context
Possibly caused by move from just-plain-KeePass to XC. (I vaguely remember that References were in upper case in just-plain,
but I don't have a copy.)  (The quick-fix of fixing that during import is probably a bad idea anyway - the compare for that field type should be case-insensitive.)

KeePassXC - Version 2.6.1
Revision: 9a35bba

Qt 5.15.0
Debugging mode is disabled.

Operating system: Windows 10 Version 1909
CPU architecture: x86_64
Kernel: winnt 10.0.18363

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.5

**Comment by droidmonkey** [comment]
I cannot replicate this at all, both lowercase and uppercase reference uuid's work with the browser extension and within the KeePassXC UI.

**Comment by DonnKey** [comment]
I had a solid 100% repro. Before I see if I can characterize it further,
please confirm that you tested it with the password field.  It works fine
for the user name field, it's ONLY the password field that shows the bug.

Donn

**Comment by droidmonkey** [comment]
There is absolutely no difference in handling references. Make sure you have a P after ref

**Comment by DonnKey** [comment]
Experimentally, there absolutely is a difference. Even visually: the user
name is in a proportional font, the password is in a fixed-width font (as
makes sense for passwords) even when it's a reference. I doubt that that
visual difference is directly relevant, but it does indicate that there's
at least some difference in handling them.

You haven't said you've tried it for passwords. Just try it.  (I did a LOT
of testing to figure out both what the bug was and to confirm that it was
as weird as it sounds - I agree it "shouldn't be different", but it is.)

Donn

**Comment by droidmonkey** [comment]
I did try it and ran it through the debugger. Thanks

**Comment by DonnKey** [comment]
I can't tell from that message whether you mean "I now have the repro" or
"Even with the debugger it works correctly".  Which?

Donn

**Comment by droidmonkey** [comment]
I said before it is not reproducible.
