### ISSUE TITLE
Ability to choose tray icon size or source type

### ISSUE THREAD

**Issue by mustaqimM** [keepassxreboot/keepassxc#5428]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
Since the release of `2.6.1`, keepassxc doesn't use the set theme's 16x16 panel icon: 
![image](https://user-images.githubusercontent.com/24436622/93047977-48a66300-f64d-11ea-9250-519cb5baf618.png)

But rather uses its own icon which is far too big:
![image](https://user-images.githubusercontent.com/24436622/93047896-1432a700-f64d-11ea-9c9d-412963934099.png)

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Upgrade to `2.6.1`
2. Set tray icon

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
A smaller icon or the ability to choose one.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
A tray icon that's too big

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - `Version 2.6.1`
Revision: `9a35bba`

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: awesomewm
Windowing System: X11

**Comment by phoerious** [comment]
This is expected behaviour and we're not going to change it.

**Comment by mustaqimM** [comment]
you have to admit, the tray icon is quite jarring compared to other qt applications
