### ISSUE TITLE
request: Sort entries manually

### ISSUE THREAD

**Issue by maowm** [keepassxreboot/keepassxc#543]
I am expecting, if you will, sort entries manually feature being added as a another way of sorting the Entries Table. Or a way of sorting by date added to the group or by topics inside the group.
Have a great time.

**Comment by krejvl** [comment]
Hello guys, I would like to vote for this feature too - I used Windows Keepass (over mono) which has this feature and I miss it quite a lot in KeePassXc. Or at least sorting by the date added to the group.

**Comment by stdedos** [comment]
Duplicate of https://github.com/keepassxreboot/keepassxc/issues/2295
