### ISSUE TITLE
Saving a .kdbx file in Keepassxc causes the file to hang on Dropbox file sync

### ISSUE THREAD

**Issue by jcosentino** [keepassxreboot/keepassxc#5430]
If you make a change in your kdbx file, synced on Dropbox, and save it in KeepassXC the file hangs in file sync. Dropbox will say that it is syncing and forever hangs. The workaround is to save, move the file out of Dropbox, and move it back in.
Version numbers:
Windows 10 19041
Mac OS X 10.15.6
Dropbox v105.4.651
KeepassXC 2.6.1; 2.6.0; 2.5.4

I do NOT have the problem syncing with Keepass2Android, as a frame of reference.

**Comment by gadgetpig** [comment]
Confirmed had similar issue yesterday. Ended up changing to sync.com service as workaround for now. Windows 10 19041

**Comment by droidmonkey** [comment]
Did you disable safe file saves in the kpxc application settings?

**Comment by gadgetpig** [comment]
@droidmonkey: I checked and it's already disabled "safely save database files".
@jcosentino : Is your "safely save database files" setting checked or unchecked?

**Comment by jcosentino** [comment]
> 
> 
> Did you disable safe file saves in the kpxc application settings?

I unchecked it, problem persists.

**Comment by droidmonkey** [comment]
Dropbox has always given us trouble, will see if I can replicate.

**Comment by jcosentino** [comment]
I saved my Keepassxc database file and today, it seems for whatever reason, the file is saving just fine on Dropbox. I guess they did something server-side?

**Comment by droidmonkey** [comment]
Could have been something loopy happening with the service.
