### ISSUE TITLE
Inconsistent password preview font

### ISSUE THREAD

**Issue by mrdaftpunk** [keepassxreboot/keepassxc#5432]
This is a minor UI inconsistency. Whilst some instances of password preview were changed to use the fixed font in PR 3425 which made it into v2.5.0, there is still one instance left. This is a problem because it's hard to distinguish between some characters in the preview. It's a shame to have to go into the 'edit entry' dialogue just to see a password preview which can be easily read.

## Steps to reproduce
1. Unlock your database
2. Click on an entry
3. In the "General" section below, click the eye icon to display the password
4. Observe the password does not use the fixed font

KeePassXC - 2.6.1
Revision: 9a35bba

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 10 2004

**Comment by droidmonkey** [comment]
I'm fairly certain it does use the fixed font

**Comment by droidmonkey** [comment]
Confirmed https://github.com/keepassxreboot/keepassxc/blob/8a4a804c8ca3b1b7db89724127d694b56f5d7e7c/src/gui/EntryPreviewWidget.cpp#L53

**Comment by mrdaftpunk** [comment]
I think I am referring to somewhere else, I have created a fake entry and made a screenshot to show where this is, hopefully the cropped image doesn't disguise the location.

![keepass](https://user-images.githubusercontent.com/34904824/93229293-57386b80-f76e-11ea-901a-f43f6bb71315.png)

**Comment by droidmonkey** [comment]
That is the dialog I linked the code for

**Comment by mrdaftpunk** [comment]
Ok, understood, however the issue is still present. I've now compared this issue between Windows 10 and Kubuntu 18.04, confirming that it affects Windows only. Yet the font differs in both places on both OSs. Here's a comparison:

![keepass2](https://user-images.githubusercontent.com/34904824/93405856-17fd3e00-f886-11ea-979e-050623b4b2c8.png)

So does this suggest that Windows is overriding the default? Why are Kubuntu's two fonts different also? I am open to trying things to help out, time permitting.

**Comment by droidmonkey** [comment]
I'll take another look, that fixed font in the preview panel looks wrong even in Kubuntu

**Comment by droidmonkey** [comment]
Wow, apologies for the pushback on this, you are absolutely correct the fixed font was not applying correctly. This must be a Qt bug when switching between masked view and visible (using the eye icon).

![image](https://user-images.githubusercontent.com/2809491/93715065-de059380-fb34-11ea-917a-e6aec6520ad8.png)

**Comment by mrdaftpunk** [comment]
That's alright, I could have provided better proof in my first post! More
than happy to assist with testing should something change, but I imagine
that needs to wait for a Qt update? Thanks for your patience!

**Comment by droidmonkey** [comment]
Oh I fixed the problem, will be in 2.6.2

**Comment by mrdaftpunk** [comment]
Ah my mistake, I hadn't viewed the attached image. Looking good, thanks - I
look forward to the update! :)
