### ISSUE TITLE
Autocomplete with custom email domain

### ISSUE THREAD

**Issue by AlfHou** [keepassxreboot/keepassxc#5434]
## Summary
I love the autocomplete feature in the username/email field.

I use my own domain for my email, and I usually use the format `{service}@mydomain.com`, the autocomplete therefore usually don't pop up.

I think it would be nice if there was a way for it to autocomplete after the @ part of the email.

Other than that I am really enjoying your software. Thank you for all the work you are doing!

## Examples
![image](https://user-images.githubusercontent.com/20001253/93257365-0429dd00-f79d-11ea-99a8-05bade557e76.png)
Something like this, where the highlighted part I would like autocompleted

**Comment by droidmonkey** [comment]
Dupli and of #3776

**Comment by droidmonkey** [comment]
Thanks for the love!!
