### ISSUE TITLE
Using Move Up/Move Down resets entries columnset

### ISSUE THREAD

**Issue by deflock** [keepassxreboot/keepassxc#5435]
## Steps to Reproduce
1. Change columns settings
2. Move any entry up or down
3. Close application
4. Open application
5. Columns settings restored to defaults

## Expected Behavior
![000490](https://user-images.githubusercontent.com/26042456/93272071-5c70d700-f7bd-11ea-9f52-93817cfe2654.png)

## Actual Behavior
![000491](https://user-images.githubusercontent.com/26042456/93272072-5c70d700-f7bd-11ea-930e-8e2884db19db.png)

## Context
PORTABLE

KeePassXC - Version 2.6.1
Revision: 9a35bba

Qt 5.15.0
Debugging mode is disabled.

Operating system: Windows 10 Version 1903
CPU architecture: x86_64
Kernel: winnt 10.0.18362

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.5

![000488](https://user-images.githubusercontent.com/26042456/93272068-5b3faa00-f7bd-11ea-8fa4-e0eebb32c1b5.png)
![000489](https://user-images.githubusercontent.com/26042456/93272070-5bd84080-f7bd-11ea-8bb7-e47107833b3b.png)

**Comment by deflock** [comment]
Related https://github.com/keepassxreboot/keepassxc/pull/5327

**Comment by droidmonkey** [comment]
This bug is because we don't check to see if the logicalIndex is -1 which would indicate "no sort" and apply a sort. Easy fix, great find!

**Comment by droidmonkey** [comment]
Hmmm fix is a little more elusive then I expected. For some reason the state is not saved (or restored) properly on startup. Might be a Qt issue.

**Comment by droidmonkey** [comment]
Fix submitted

**Comment by bulgin** [comment]
So what's the exact fix?

**Comment by droidmonkey** [comment]
Uh #5438... it's linked to this issue
