### ISSUE TITLE
Why stable releases doesn't come to ubuntu focal repository?

### ISSUE THREAD

**Issue by azrea** [keepassxreboot/keepassxc#5436]
See the title and https://packages.ubuntu.com/source/keepassxc

**Comment by networkException** [comment]
More or less a duplicate of #5254

**Comment by phoerious** [comment]
Please take this to the Ubuntu maintainers. We are not involved in downstream packaging. Use our PPA if you want a version that is newer than what the Ubuntu repos offer.
