### ISSUE TITLE
Monospaced font in notes not working in Manjaro

### ISSUE THREAD

**Issue by PolyMMA** [keepassxreboot/keepassxc#5437]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

Hi!

I am running Manjaro and cannot enable the monospaced font in notes. Have tried various things but nothing has worked. Other users have also managed to reproduce this issue. I noticed this on KeePassXC v2.6.0 and it still persists in v2.6.1.

see also this [forum thread](https://archived.forum.manjaro.org/t/keepassxc-monospaced-font-for-notes-not-applied-in-manjaro/149889) on the same issue.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Install Manjaro Linux (XFCE) according to info below. 
2. Install KeePassXC 2.6.0 -- 2.6.1
3. Toggle "Monospaced font in notes" - setting
4. No change in the entry with notes

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Font in notes should switch between monospaced and not, along with toggling of the corresponding setting.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Notes font remains NOT monospaced regardless of the corresponding setting.

## Context
[NOTE]: # ( Give us any additional information you may have. )
I suspect this might have to do with Manjaro xfce desktop environment somehow overriding the font, or not allowing it to locally change in the KeePassXC software? The issue does not exist on Manjaro Plasma desktop environment, nor Ubuntu 16 and 18 using xfce! (same version of KeePassXC on all!)  See Forum post link above. 

[NOTE]: # ( Paste debug info from Help → About here )

> $ keepassxc --debug-info
KeePassXC - Version 2.6.1
Revision: 9a35bba
|
Qt 5.15.0
Debugging mode is disabled.
|
Operating system: Manjaro Linux
CPU architecture: x86_64
Kernel: linux 5.4.60-2-MANJARO
|
Enabled extensions:
Auto-Type
Browser Integration
SSH Agent
KeeShare (signed and unsigned sharing)
YubiKey
Secret Service Integration
|
Cryptographic libraries:
 libgcrypt 1.8.6

> System:    Kernel: 5.4.60-2-MANJARO x86_64 bits: 64 compiler: gcc v: 10.2.0 
|           Desktop: Xfce 4.14.2 tk: Gtk 3.24.20 info: xfce4-panel wm: xfwm4 
|           dm: LightDM 1.30.0 Distro: Manjaro Linux 

[NOTE]: # ( Pick choices based on your environment )
Operating System: Manjaro Linux
Desktop Env: XFCE

**Comment by droidmonkey** [comment]
This is an issue with your DE not providing a fixed space font.

**Comment by PolyMMA** [comment]
Looked around now, and in Qt5 Configuration Tool (Qt5 Settings) > Fonts there is a choice for "General" and "Fixed width" font. Bot were set to Catnarell 10. By setting the "Fixed width" one to a font with monospace, I got the monospaced font in KeePassXC. 

Thank you!!
