### ISSUE TITLE
KeepassXC information on https://snapcraft.io/keepassxc out of date

### ISSUE THREAD

**Issue by padraic7a** [keepassxreboot/keepassxc#5439]
The information on running KeepassXC available on snapcraft.io is out of date.

## Expected behaviour

Link to usage tips should be correct

## Steps to reproduce the problem

    Click on link in "For usage tips see: https://github.com/keepassxreboot/keepassxc/wiki/Snap-Tips"
    Find that the page doesn't exist and that the wiki on the github site doesn't have a similar page

I googled around and found that there is a 'browser help script' for the snap linked to from here; https://keepassxc.org/download/#linux - this should probably replace the current text.

**Comment by droidmonkey** [comment]
Page is updated
