### ISSUE TITLE
Error from KeepassX: Unable to open the database. XML error: Premature end of document.

### ISSUE THREAD

**Issue by ddd111ddd** [keepassxreboot/keepassxc#544]
I have a KeepassX database that got corrupted and none of the solutions I found worked. I tried importing the same file on KeepassXC and the errors are exactly the same. Is the problem on importing or saving?

Does this means this fork also have the same bug? Some issues report that special characters in comments can cause this problem to appear.

Anyway, I came here hoping somebody can help me and at the same time avoid this awful thing to happen to others in the future. I'm moving to your fork anyway, just found out about it.

https://i.imgur.com/CH1xW5N.png

> Unable to open the database.
> XML error:
> Premature end of document.
> Line 1, column 0

Re-import doesn't fix.

Repair database shows the same error.

**Comment by TheZ3ro** [comment]
The screenshot refers to KeePassX, anyway can you report the size of the corrupted KDBX file?

**Comment by ddd111ddd** [comment]
Latest valid backup (like a couple of days before):

- Keyfile: 162 bytes
- Database: 87,7 KB

Corrupted:
- Keyfile: 162 bytes
- Database: 88,4 KB

**Comment by TheZ3ro** [comment]
Seems that the corrupted has still data in it. 

You should try compiling the latest version of KeePassXC from the `develop` branch and using `keepassxc-cli extract databasepath.kdbx`, this will print out the XML content

**Comment by ddd111ddd** [comment]
@TheZ3ro how can I specify a keyfile?

>Error while reading the database:
> Wrong key or database file is corrupt.

That's what I get when I input my password.

**Comment by TheZ3ro** [comment]
@ddd111ddd oh sorry the actual version doesn't accept keyfiles. I will implement it soon, keep the corrupted file.

**Comment by ddd111ddd** [comment]
Thanks! But don't worry I already recovered the missing accounts with a password reset but I'm worried that other people might run into this bug and have no backup.

**Comment by Keisial** [comment]
Studying what got corrupted, even if the lost data is now obsolete, is probably still desirable.

**Comment by louib** [comment]
@ddd111ddd the latest version (develop branch) now accepts a key file, using the `--key-file` option. I hope that can help you in troubleshooting the issue.

**Comment by r-gcc-65061** [comment]
Hello, it appears that I have encountered this same issue; when using the command line tool it throws an error stating that "no root group was found". I am pretty sure that the data is still there, because the database is still around the same size as the previous one, albeit a bit smaller (more on that later), and I don't think the header was corrupted, since the program will still notify me if I entered the wrong key for the database. I've made backups, but I'd like to know if there is anyways to  bypass the check for parsing the root group, since that seems to be preventing me from using the extract tool to recover the database's XML data. 
As for the size thing, I think the problem source may have been me trying to save the database on a disk with insufficient space, but I haven't tried replicating the issue yet so I am not sure if that is the source of the bug.
Thanks!

> KeePassXC - Version 2.3.1
Revision: 2fcaeea
Distribution: AppImage

I had tried opening initially with an earlier version of the program, and that gave an XML error in the user interface and the root group error on the commandline, so I think that it's related to this issue.

**Comment by r-gcc-65061** [comment]
Huh, I tried that, though unfortunately it did not ouput anything. (I did spend quite a bit of time figuring out the build instructions though-the instructions for linking the libraries seemed to be buried :-P) In any case, thanks for the pointer. Is there any way to directly decrypt and dump the decrypted/uncompressed data output, raw?

**Comment by droidmonkey** [comment]
Please open a new issue to document the need for an "extract even on error" for the CLI.

**Comment by IvanArty** [comment]
Please people, can you help me, i used keepassx and i have tried to copy it, of course i can not do this and now it do not open. With this error

Unable to open the database.
XML error:
Premature end of document.
Line 1, column 0

**Comment by IvanArty** [comment]
How I can extract my passwords, or somebody who understand this program can help me.

**Comment by droidmonkey** [comment]
@IvanArty it is very likely that your database is corrupted and cannot be salvaged. What did you do just prior to this happening? Were you using KeePassX, instead of KeePassXC?

**Comment by IvanArty** [comment]
@droidmonkey thank you for answer, in kali linux, i use just keepassx, and i put usb in computer, tri to copy database to computer and after that open

**Comment by IvanArty** [comment]
And i can not open, maybe can somebody can watch it on my computer

**Comment by droidmonkey** [comment]
There is nothing we can do about this unfortunately. From the error message, it means your database contents are empty.

**Comment by IvanArty** [comment]
@droidmonkey ok thank you, what i can do if i have important passwords there and what i can do in future for use my passwords? because keepassx was helpful, can you recommend some programs

**Comment by droidmonkey** [comment]
This project is KeePassXC (note the C), we are a fork of KeePassX that has been significantly enhanced and updated. You should be using KeePassXC, even on Kali. Do you not have a backup of your database file anywhere? Were you saving/loading directly to the USB drive? I really do not understand your situation at all.

**Comment by IvanArty** [comment]
No i do not have backup, i have this database just on my usb,unfortunately. Situation is that i now lose all my password

**Comment by phoerious** [comment]
Always have a backup, especially if you are keeping the DB on a USB stick, which are known to be rather unreliable. Unplug it prematurely once and a file is truncated.

**Comment by abawany** [comment]
Running KeePassXC 2.6.1 I also ran into this issue. However, the file in question opens fine with Keepass 2.45 on W10, MacPass, and AuthPass so I am fairly sure the database is not corrupt. Any other ideas, pls?

**Comment by droidmonkey** [comment]
Are you trying to open a kdb or kdbx database?

**Comment by abawany** [comment]
kdbx. Another (different) kdbx on the same machine opens fine with MacPass, AuthPass, and KeePassXC 2.6.1.

**Comment by droidmonkey** [comment]
There's no reason why it wouldn't work that we're aware of

**Comment by abawany** [comment]
KeePassXC generates `Error while reading the database: No root group`. Looking in the OSX Console, I see the following:

```
default	10:30:43.292661-0500	KeePassXC	SetFrontProcess: asn=0x0-0x124c24b options=1
default	10:30:44.627620-0500	KeePassXC	KdbxXmlReader::skipCurrentElement: skip element "Entry"
default	10:30:44.627708-0500	KeePassXC	KdbxXmlReader::skipCurrentElement: skip element "Entry"
default	10:30:44.627815-0500	KeePassXC	KdbxXmlReader::skipCurrentElement: skip element "Entry"
default	10:30:44.629662-0500	KeePassXC	KdbxXmlReader::skipCurrentElement: skip element "UUID"
default	10:30:44.629698-0500	KeePassXC	KdbxXmlReader::skipCurrentElement: skip element "Name"
default	10:30:44.629719-0500	KeePassXC	KdbxXmlReader::skipCurrentElement: skip element "Notes"
default	10:30:44.629739-0500	KeePassXC	KdbxXmlReader::skipCurrentElement: skip element "IconID"
default	10:30:44.629760-0500	KeePassXC	KdbxXmlReader::skipCurrentElement: skip element "IsExpanded"
default	10:30:44.629781-0500	KeePassXC	KdbxXmlReader::skipCurrentElement: skip element "DefaultAutoTypeSequence"
default	10:30:44.629801-0500	KeePassXC	KdbxXmlReader::skipCurrentElement: skip element "EnableAutoType"
default	10:30:44.629822-0500	KeePassXC	KdbxXmlReader::skipCurrentElement: skip element "EnableSearching"
default	10:30:44.629842-0500	KeePassXC	KdbxXmlReader::skipCurrentElement: skip element "LastTopVisibleEntry"
default	10:30:44.629862-0500	KeePassXC	KdbxXmlReader::skipCurrentElement: skip element "Times"
default	10:30:44.629887-0500	KeePassXC	KdbxXmlReader::skipCurrentElement: skip element "Entry"
default	10:30:44.629931-0500	KeePassXC	KdbxXmlReader::skipCurrentElement: skip element "Entry"
default	10:30:44.629995-0500	KeePassXC	KdbxXmlReader::skipCurrentElement: skip element "Entry"
default	10:30:44.630064-0500	KeePassXC	KdbxXmlReader::skipCurrentElement: skip element "Entry"
default	10:30:44.630103-0500	KeePassXC	KdbxXmlReader::skipCurrentElement: skip element "Entry"
default	10:30:44.630234-0500	KeePassXC	KdbxXmlReader::skipCurrentElement: skip element "Entry"
default	10:30:44.630280-0500	KeePassXC	KdbxXmlReader::skipCurrentElement: skip element "Entry"
default	10:30:44.630317-0500	KeePassXC	KdbxXmlReader::skipCurrentElement: skip element "Entry"
default	10:30:44.630354-0500	KeePassXC	KdbxXmlReader::skipCurrentElement: skip element "Entry"
default	10:30:44.630390-0500	KeePassXC	KdbxXmlReader::skipCurrentElement: skip element "Entry"
default	10:30:44.630470-0500	KeePassXC	KdbxXmlReader::skipCurrentElement: skip element "Entry"
default	10:30:44.630512-0500	KeePassXC	KdbxXmlReader::skipCurrentElement: skip element "Entry"
default	10:30:44.630610-0500	KeePassXC	KdbxXmlReader::skipCurrentElement: skip element "Entry"
default	10:30:44.630764-0500	KeePassXC	KdbxXmlReader::skipCurrentElement: skip element "Entry"
default	10:30:44.630806-0500	KeePassXC	KdbxXmlReader::skipCurrentElement: skip element "Entry"
default	10:30:44.630867-0500	KeePassXC	KdbxXmlReader::skipCurrentElement: skip element "Group"
default	10:30:44.632390-0500	KeePassXC	KdbxXmlReader::skipCurrentElement: skip element "Group"
default	10:30:44.632766-0500	KeePassXC	KdbxXmlReader::skipCurrentElement: skip element "Group"
default	10:30:44.632905-0500	KeePassXC	KdbxXmlReader::skipCurrentElement: skip element "Group"
default	10:30:44.634193-0500	KeePassXC	KdbxXmlReader::skipCurrentElement: skip element "Group"
```

Does that reveal anything useful pls?

**Comment by droidmonkey** [comment]
Your datavase file is corruptes

**Comment by abawany** [comment]
But I am able to open it on AuthPass (ios, osx), MacPass (osx), and KeePass2 and I am able to open it there with no errors that I see.

**Comment by droidmonkey** [comment]
Then they clearly have no respect for the XML specification. If your database is kdbx3 then upgrade it to Kdbx4 to solve your problem.

**Comment by mathi14811** [comment]
> Seems that the corrupted has still data in it.
> 
> You should try compiling the latest version of KeePassXC from the `develop` branch and using `keepassxc-cli extract databasepath.kdbx`, this will print out the XML content

Same problem, my files still have data as well, yet I would like to do as you say, but I have no idea how to. Can you explain it simply ? I check YouTube and everything, but I never compiled or wrote code in my life.
