### ISSUE TITLE
Microsoft Edge Crashed on Mac OS Catalina

### ISSUE THREAD

**Issue by JamesInform** [keepassxreboot/keepassxc#5441]
Hi there!

Microsoft Edge Browser crashes after some updates. Not sure if it was after a keepassxc or an edge update.

The problem is that Edge starts but than throws a massage about keepassxc browser could not be started.

I am stuck. Reinstalling Edge doesn't help because that leaves the installed extensions as they are and throws that error right after the start of Edge.

Could someone tell me how to uninstall the keepassxc extension manually by hand, because  inside Edge I can't do anything. If e.g. I go to the extensions, a new page is opened in Edge and immediately throws the "keepassxc browser could not be started error"?!

It's quite urgent on my side!

**Comment by JamesInform** [comment]
This is what my browser constantly throws ... (It's in German language)
Errorcode: 6

![image](https://user-images.githubusercontent.com/38714600/93512869-3f571800-f925-11ea-84a4-dce9a112babf.png)

**Comment by droidmonkey** [comment]
This is definitely not because of our extension. Just reinstall edge browser.

**Comment by JamesInform** [comment]
> This is definitely not because of our extension. Just reinstall edge browser after clearing your profile folder from /Users/YourUsername/Library/Application Support/

Reinstalling doesn't solve the problem. But I have found the source of it.

It was a Safari update that I installed today. 
Now guess what: I just had to reboot my MacBook and the error was gone.

So, the Windows tricks now work on Mac ;)
