### ISSUE TITLE
KeepassXC integration for Brave does not work properly

### ISSUE THREAD

**Issue by coughingmouse** [keepassxreboot/keepassxc#5442]
## Overview
When I enabled browser integration for Brave in KeepassXC settings, it did not work.
It still did not work when I've enabled it for Chromium.
However, it started working when I enabled browser integration for Google Chrome.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Install KeepassXC, Brave, and KeepassXC-Browser for Brave.
2. Open KeepassXC and press `Command` `,` to open settings.
3. Open Browser Integration menu on the left panel.
4. On "Enable integration for these browsers:", enable checkbox for either Brave or Google Chrome and save.
5. Open Brave and its KeepassXC-Browser extension.
6. Within extension, use the "Reload" button to connect to KeepassXC.

## Expected Behavior
When Brave is checked, browser integration should work.
When Brave is not checked, browser integration should not work.
When Chromium is checked, browser integration might work since Brave is, like Ungoogled-Chromium, chromium-based.
When Chromium is not checked, browser integration might not work since Brave is, like Ungoogled-Chromium, chromium-based.

## Actual Behavior
When Google Chrome is checked, browser integration works. (?)
When Google Chrome is unchecked, browser integration still works. (???)
After unchecking, browser integration stops working after rebooting KeepassXC.

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION 2.6.1
Revision: REVISION 9a35bba

KeePassXC-Browser Version: 1.7.1

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS

Operating system: MacIntel
Browser: Chrome/Chromium 85.0.4183.102

**Comment by droidmonkey** [comment]
Before you get too excited...Brave browser changed where it looks for native messaging config files after we released support for them.

**Comment by varjolintu** [comment]
Brave needs to decide do they want to use Chrome's, Chromium's or Brave's settings path. If we change it now, how can we be sure they will not change it again?

Any user can use the Custom Browser option to set the correct path as a workaround.

**Comment by coughingmouse** [comment]
Did not know there already was a custom browser option available. My bad on that.

**Comment by lxwulf** [comment]
How can I change "the path" for the workaround? I have also installed the newest extension and every time want to connect to my database it displays `Key exchange was not successful.` I use brave-nightly. On Windows it works but not on my linux machine.

**Linux Machine Info:**

![info](https://user-images.githubusercontent.com/44492381/105695887-e4e94c00-5f02-11eb-9bb6-215814625f5e.png)

**Brave Browser Info:**

Version 1.21.21 Chromium: 88.0.4324.96 (Official Build) nightly (64-bit)

**Comment by lxwulf** [comment]
I fixed it with an easy copy job:

1. Open Terminal
2. Go to `~/.config/google-chrome/NativeMessagingHosts`
3. Copy the file `org.keepassxc.keepassxc_browser.json` to `~/.config/BraveSoftware/Brave-Browser-Nightly/NativeMessagingHosts`
4. Finished

Keep in mind that you should type your Brave Browser Version. I installed the `Nightly` version you have maybe `Beta` or the `Stable` one.
