### ISSUE TITLE
KeePassXC-Browser upgrade dialog persists after failing to find KeePassHTTP related attribute

### ISSUE THREAD

**Issue by coughingmouse** [keepassxreboot/keepassxc#5443]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
KeepassXC does its thing upgrading browser integration related stuff.
After doing so, it recycles an entry relating to KeePassXC-Browser.
Even after doing so, KeePassXC keeps sending upgrade dialog because it reads the entry in the recycle bin that it has created and thinks that there still is a KeePassXC-Browser related legacy left.

As a result, older users keep seeing a dialog until they mute it without understanding what's happening or they accidentally purge the entry from the recycle bin.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Get an old KeePassXC file with which you've integrated with a browser. I don't know how old.
2. Open it with a new KeePassXC and migrate existing settings as the program suggests. At this point it throws you this dialog:
`Your KeePassXC-Browser settings need to be moved into the database settings.
This is necessary to maintain your current browser connections.
Would you like to migrate your existing settings now?`
3. KeePassXC will tell you that it's done something. Lock the database and reopen. Or open another database and open the old database again with the tab.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Since you've already migrated existing settings, the update dialog shouldn't appear.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
`Your KeePassXC-Browser settings need to be moved into the database settings.
This is necessary to maintain your current browser connections.
Would you like to migrate your existing settings now?`
This dialog appears again. To which if you agree to do so, it says,
`The active database does not contain an entry with KeePassHTTP attributes.`
And these dialogs keep appearing.

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION 2.6.1
Revision: REVISION 9a35bba

KeePassXC-Browser Version: 1.7.1

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS

Operating system: MacIntel
Browser: Chrome/Chromium 85.0.4183.102

**Comment by droidmonkey** [comment]
Duplicate issue, being fixed for 2.6.2
