### ISSUE TITLE
Lock database time

### ISSUE THREAD

**Issue by bear30** [keepassxreboot/keepassxc#5444]
Hello, this "lock database after inativity" doesn't work correctly. It locks the database after some minutes. Please allow here reasonable times of 1 or 2 hours. Thank you!

**Comment by droidmonkey** [comment]
You can set it to whatever time limit you want up to 12 hours

**Comment by bear30** [comment]
Hi, 
did you test this function? After my opinion it does't work ...
Regards

**Comment by droidmonkey** [comment]
It works, you probably also set lock on minimize or lock on screen lock.
