### ISSUE TITLE
[SSH integration] Notify user te restart KeePass to activate functionality

### ISSUE THREAD

**Issue by GradedJestRisk** [keepassxreboot/keepassxc#5445]
## Summary
When the user check-in the option (General settings / Enable SSH integration agent), the feature in not actually active.
![image](https://user-images.githubusercontent.com/37769607/93565856-53823000-f98c-11ea-951d-462d6f633761.png)
User must restart KeePassXC so database entry SSH option is visible (SSH agent).
![image](https://user-images.githubusercontent.com/37769607/93566011-96dc9e80-f98c-11ea-9224-2c4cc3b3fd7f.png)

## Examples
It can be a pop-up to make it explicit
![image](https://user-images.githubusercontent.com/37769607/93566345-3306a580-f98d-11ea-9ea1-c8c4ee79005b.png)

## Context
This would prevent a beginner user to create an issue if he don't dare to restart

**Comment by droidmonkey** [comment]
@hifi I thought you fixed this

**Comment by hifi** [comment]
As far as I know it is fixed. The only corner case is if you have an entry edit mode open when you change the option in the settings you need to close that and open it again. Only way to fix this would be to enforce entry edit to be closed when you go to settings.

@GradedJestRisk did you encounter this even when you don't have an entry open?
