### ISSUE TITLE
UI has vertical line while editing entry

### ISSUE THREAD

**Issue by mattrobineau** [keepassxreboot/keepassxc#5446]
## Overview
A vertical line appears across inputs from Title into Notes.

![keepassxc-bug](https://user-images.githubusercontent.com/427379/93638274-01113580-f9c5-11ea-836e-5699056af242.PNG)

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Click Add Entry button from toolbar
OR
1. Open an existing entry

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
It should not have the vertical line/bar.

## Actual Behavior
Has vertical line over UI

a) Toggling `View -> Show Toolbar` fixes the issue temporarily. Closing the entry and reopening will reproduce the described issue.
b) Switching to Light theme did not resolve the issue
c) Window size does not change result
 1 - Resizing the window will temporarily remove the line however moving the focus off of the application window will make the bar reappear.
d) Restarting KeepassXC does not resolve the issue.
e) Line is not present on the other tabs (ie: Advanced, Icon, Auto-Type, etc.)

## Context
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.1
Revision: 9a35bba

Qt 5.15.0
Debugging mode is disabled.

Operating system: Windows 10 Version 1903
CPU architecture: x86_64
Kernel: winnt 10.0.18362

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.5

**Comment by droidmonkey** [comment]
Already fixed
