### ISSUE TITLE
Old entry is being used instead of the newest one

### ISSUE THREAD

**Issue by jNullj** [keepassxreboot/keepassxc#5448]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
I noticed that recently changed entries are using the wrong password, after looking at them i found out that the latest change is shows in history as last modification and the info is saved, but keepassxc is using the previous history entry showing and using the old password/info.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
cant tell why it happens or reproduce, only happens on some entries and not others.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
latest entry info should be used

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
old entry info is being used

## Context
[NOTE]: # ( Give us any additional information you may have. )
keepassxc database is being stored inside a shared directory (using resellio sync)
the entries might have been changed on versio 2.6.0.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.1
Revision: 9a35bba

Qt 5.15.1
Debugging mode is disabled.

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 5.8.9-arch2-1

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.6

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux (arch)
Desktop Env: xfce4
Windowing System: X11

**Comment by droidmonkey** [comment]
100% its your sync software overwriting your database with an older version. This isn't on us.

**Comment by jNullj** [comment]
> 100% its your sync software overwriting your database with an older version. This isn't on us.

but i still see the new password in History. which means the database saved the new file, isn't it?
Shouldn't it forget the new password instead of store them in history if that where the case?

**Comment by droidmonkey** [comment]
If you see the new password in history that means the file was merged with the old password showing newer. If you can reproduce without the sync I'll reopen
