### ISSUE TITLE
Preview pane AutoType tab greyed out

### ISSUE THREAD

**Issue by flabdablet** [keepassxreboot/keepassxc#5450]
After updating to KeePassXC 2.6.1, database entries with custom Auto-Type sequences defined but without specific window associations also defined are no longer enabling the Autotype tab in the preview pane. That tab remains greyed out until a window association is also created for that entry.

I found the behaviour of older versions more useful, because they let me see at a glance whether or not I'd already updated a KeePass 2.x database entry with a custom Auto-Type sequence copied from the entry's notes after migrating from a 1.x database.

What would be absolutely ideal is if 1.x migration had automatically defined 2.x custom Auto-Type sequences for all 1.x entries with Auto-Type: lines in their Notes field. But given that it didn't and I do need to fix these up by hand, it's a bit of a pest to have to drill into Edit Entry/Auto-Type just to check whether I've already done that or not.

**Comment by krsnik93** [comment]
Hi, I would like to tackle this issue. I am not new to using Keepass, but am new to the codebase.

After poking a bit, I think we could display the default sequence above the window-sequence associations list (still in the Autotype tab). When I say default sequence, I don't mean the default sequence possibly inherited from the entry group, but the actual default sequence for all entry associations, which can be either the group-inherited one or a custom defined one.

Then we would have to decide whether to display this (and thus, have an active Autotype tab in the entry preview pane) even for entries that have group-inherited sequences (presumably less interesting than the ones that have custom ones) and possibly no associations. This could mean that the Autotype would be active for all entries, which (in my opinion) would feel a bit redundant (showing the same info for almost all entries), but there is still a decent info gain in terms of what the user gets to see without having to right click -> edit entry -> select autotype tab etc.

**Comment by droidmonkey** [comment]
I like your proposal
