### ISSUE TITLE
Please elaborate in the docs: How to run KeeShare on a web / ssh / ftp / ??? server

### ISSUE THREAD

**Issue by mefromthepast** [keepassxreboot/keepassxc#5451]
The [KeeShare documentation](https://github.com/keepassxreboot/keepassxc/blob/develop/docs/topics/KeeShare.adoc) currently specifies that "[t]he file should be written to a location that is accessible by others." It does not provide any additional information about which protocols keeshare can interact with.

In fact, I have seen some screenshot where people have used `smb://` instead of just their local file system. I do suspect, however, that KeeShare does not support other means such as `HTTP PUT` or `ssh://` to synchronise.

Or is this possible somehow?
The idea is that I want to share passwords over the internet. Do I have to upload the file every time I change some entry, and if so, what is even the advantage of using KeeShare instead of just another DB?

The documentation should answer all of these questions.

**Comment by droidmonkey** [comment]
https://keepassxc.org/docs/KeePassXC_UserGuide.html#_database_sharing_with_keeshare

**Comment by horschi** [comment]
@droidmonkey : Is SSH supported? The linked documentation does not mention SSH.

**Comment by droidmonkey** [comment]
No, you need to setup your own file syncing such as scp or rsync.
