### ISSUE TITLE
KeePassXC 2.6.1 UI rendering error.

### ISSUE THREAD

**Issue by quasiblob** [keepassxreboot/keepassxc#5453]
## Overview
Scroll bar renders over UI when creating a new password. This also happens in some cases when  Alt-Tabbing from another application (I can't reproduce  the steps for this case).

![example](https://user-images.githubusercontent.com/13034046/93713996-4c177e00-fb68-11ea-8f52-cd2975341b63.PNG)

## Steps to Reproduce
1. Press create new entry icon in toolbar.
2. Incorrect rendering should be obvious.

Operating System: Windows 10 Pro / Nvidia 960 graphics card.

**Edit:** as soon as application window is resized incorrectly rendered bar disappears.

**Comment by droidmonkey** [comment]
Fixed already for 2.6.2

**Comment by quasiblob** [comment]
OK... good to know... Any idea when 2.6.2 will be available? 2.6.1 seems to be the latest version on download page.

**Comment by droidmonkey** [comment]
when its ready
