### ISSUE TITLE
Wildcard URLs are not possible

### ISSUE THREAD

**Issue by synergiator** [keepassxreboot/keepassxc#5459]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

Can't use asterisk sign to produce wildcard URLs for matching. As a result, no match.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Create entry 
2. Go to URL
3. Use asterisk

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Wildcard URL is possible

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Software does not accept wildcard URL.
Error: red highlight on the URL field background; exclamation sign on the right side with the tooltip "Invalid URL".

Cryptographic libraries:
 libgcrypt 1.8.5

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.1
Revision: 9a35bba

Qt 5.12.8
Debugging mode is disabled.

Operating system: Ubuntu 20.04.1 LTS
CPU architecture: x86_64
Kernel: linux 5.4.0-47-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.5

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: XFCE
Windowing System: X11

**Comment by droidmonkey** [comment]
Duplicate #3718
