### ISSUE TITLE
Label toolbar icons

### ISSUE THREAD

**Issue by williamtheaker** [keepassxreboot/keepassxc#546]
One issue that constantly emerges during KeePassX trainings is new users being confused by the toolbar icons. Though they may seem obvious to long-time KeePassX users, the meaning of the icons, like the key with the downward green arrow, can be quite opaque to inexperienced computer users. Labeling the toolbar icons would go a long way towards improving new user onboarding.

**Comment by TheZ3ro** [comment]
Note: If you hover the mouse on toolbar icons, a label should appear telling you what each icon does.

**Comment by droidmonkey** [comment]
We are looking to do a complete icon overhaul, would love your feedback on those that are especially confusing.

**Comment by phoerious** [comment]
Related to #548

**Comment by williamtheaker** [comment]
@TheZ3ro part of the issue is not being able to clearly refer to the icons when giving a walkthrough.
It would be a lot easier to say "click on the 'Add new entry' button" than "click on the key with the downward green arrow icon."

In the mean time I'll try to think of how the symbols used in the icons could be clarified.
