### ISSUE TITLE
Vertical Line

### ISSUE THREAD

**Issue by boomonics** [keepassxreboot/keepassxc#5461]
Hi,

I'm using KeePassXC with Windows 10.  After opening an entry, I get a vertical line that extends through all entry fields, about in the middle of the Edit Entry window (please see attached pic).  I can make the vertical line go away by maximizing the KeePassXC window.  It looks like it could be a redraw / refresh issue but I don't know for sure.

Once the KeePassXC window is maximized, I can get the vertical line to come back by clicking Restore Down (between X to close & Minimize, top-right) and then changing the window focus to another program like the Edge browser.  When I switch the window focus back to KeePassXC, the vertical line is back.  Any ideas how I can make this go away?
![Vertical Line](https://user-images.githubusercontent.com/55965262/93939882-89f7dc00-fcf9-11ea-849f-258781ff26a2.jpg)

**Comment by ManuelHu** [comment]
I see the same issue on Fedora 32, version 2.6.1:
![grafik](https://user-images.githubusercontent.com/10050780/93942897-ad3e7d80-fd31-11ea-88ee-2407f74fa328.png)

**Comment by droidmonkey** [comment]
Already fixed

**Comment by boomonics** [comment]
Wow, that was fast! Thank you
How do I get the updated / fixed version?  I just tried uninstalling my installed version, downloaded the latest version from the website, installed and I still get that vertical line.

**Comment by droidmonkey** [comment]
Its not deployed yet

**Comment by boomonics** [comment]
Ah, ok, thanks again
