### ISSUE TITLE
Safari 14 Supports Extensions Ported From Chrome, Firefox, and Edge

### ISSUE THREAD

**Issue by joergrenn** [keepassxreboot/keepassxc#5463]
## Summary
The new Safari 14 supports the same WebExtensions API used in other browsers, such as Chrome, Firefox, and Edge and is compatible with macOS 10.14 and 10.15.
Apple states that existing Extensions can be easily ported to Safari.
https://developer.apple.com/news/?id=kuswih5l

Would this be a way to bring the keepassxc browser extension to Safari?

**Comment by droidmonkey** [comment]
Thanks we are working on it
