### ISSUE TITLE
Cannot write new records

### ISSUE THREAD

**Issue by ho3o** [keepassxreboot/keepassxc#5466]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
When i try add new records or create backup file then i see that message: Database write error: Could not write, database not initialized!
I was  looking for option like that in settings but i haven't found.

## Context
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.6.0
Revision: 0765954

[NOTE]: # ( Pick choices based on your environment )
Operating System: Ubuntu 18.04.5 LTS
Desktop Env: Gnome
Windowing System: X11

**Comment by droidmonkey** [comment]
Is this with a new database file? Try changing or resetting your database credentials (Database -> Database Security)

**Comment by ho3o** [comment]
No, created in earlier version few month ago.

**Comment by droidmonkey** [comment]
Have you tried resetting your database credentials?

**Comment by ho3o** [comment]
Reset/change database credentials resolved problem.
Thank you @droidmonkey for you help.
