### ISSUE TITLE
RAnDomiZED caSE for passphrases, Special Chars with different positioning for passphrases, and API/Web Password Restrictions Autosensing

### ISSUE THREAD

**Issue by devopsmyth** [keepassxreboot/keepassxc#5467]
## Summary
Enhancements to the Passphrase password generator:
- Random Case - randomize uppercase letters in words
- Special Chars - add the ability to include random special characters throughout the passphrase (not just as word separators), or to tack them onto the end
- Add API functionality for capturing password requirements from web page

## Context
I use the password generator dozens of times throughout each week. I often manually manipulate the passphrase to include things like random uppercasing, not just Title Case, all UPPERCASE, or lowercase. I also typically tack on a smattering of special characters either peppered throughout, or in a bunch somewhere in the phrase. If I could rely on the generator to just do this for me, it would save me hours of my life over the course of a single year (2 pass gens/day, 5 days a week, 52 weeks a year, 10 seconds per pass) ~ 1.5 hours per year of life for just fiddling and adding the additional characters that are often required by password restrictions.

Along that same vein, if the browser plugin could scrape the page for password requirements/restrictions text, massage that into XML or JSON and then pass that data to the main KeepassXC application when the "Show Generator" option is clicked on a web page, you could potentially have that configure the passphrase, or password, options automatically so the user doesn't have to try and fail multiple times to find an actually acceptable password to use on a site. I realize not all sites will have that text available, so this is definitely a bonus feature that doesn't have to be used.  In addition, having a set of checkboxes or something on the passphrase generator would be nice so that you could manually select which additional options you'd like to be used when generating the passphrase (this already exists for the password generator, I'm speaking strictly about the phrases which I tend to use more than anything else). 

## Follow-Up
If your team is willing to accept pull requests, I might be able to find time to try to implement these features myself. However, I haven't looked at your source, so getting up-to-speed and ready to make changes to it could take a while. Plus, finding the time during the end-of-the-world is quite challenging with a hoard of children that call me "Dad."  If mockups would be helpful or necessary, I'm happy to whip something up but again it may take me a minute to get around to it. Also, If you guys aren't involved with the browser plugin team, I'm happy to post the API (password requirements scraping) feature request on their tracker as well. 

For what it's worth, I love your app and use it extensively. I was a big fan of the original KeePass, tried a ton of others over the years, and eventually settled on KeePassXC a few years back. Keep up the great work.

**Comment by droidmonkey** [comment]
See #4209 and #4417. Likely will not make anymore changes to the passphrase generator. What you are describing is a _password_ and defeats the whole purpose of a passphrase.

**Comment by droidmonkey** [comment]
Thanks for liking our application!!

**Comment by devopsmyth** [comment]
> See #4209 and #4417. Likely will not make anymore changes to the passphrase generator. What you are describing is a _password_ and defeats the whole purpose of a passphrase.

I'm confused as to why having passphrase with additional entropy from tacking on some numbers and characters would be defeating the purpose of a passphrase. I hate to be dense, but could you elaborate on that? I used passphrases because I'm pretty sure that I've read that they're inherently harder to crack and easier to remember. The reason I put random uppercase characters, numbers, and symbols in them is strictly because I'm forced to. Like my work account password that I have to use multiple times a day. I have to be able to type it from memory, like when unlocking my laptop, for instance. So in that scenario, I prefer a passphrase that is easy to remember but then I have to also include digits and special chars to meet the restrictions or requirements. 

Thanks for pointing me to the open request, and the Apple project, and I appreciate the quick feedback. Sorry for the tracker spam.

**Comment by phoerious** [comment]
Randomised casing makes it harder to remember. Passphrases are secure due to their length and the size of the word list, not due to random capitalisations or inserted numbers.

**Comment by devopsmyth** [comment]
> See #4209 and #4417. Likely will not make anymore changes to the passphrase generator. What you are describing is a password and defeats the whole purpose of a passphrase. @droidmonkey 

> Randomized casing makes it harder to remember. Passphrases are secure due to their length and the size of the word list, not due to random capitalizations or inserted numbers. @phoerious 

I understand that passphrases rely primarily on length to make them difficult to brute force. It's just that a lot of platforms still require the use of special chars, digits, upper and lower case letters, and in some cases no spaces are allowed to be used. So my point is, by using a passphrase that is long, but easy to remember, I've already made it tough to brute force. In order to comply with password requirements and restrictions, I typically make this easy by simply adding something containing the necessary chars somewhere in the password, which also isn't terribly hard to remember. 


### Incorrect way to use passphrases + (numbers & special chars)
- I don't go out of my way to make something bizarre, for example: 
> ```
> #CoRr-cT-4orSE^b@TT3rY_stAPle13$^28
> ```  this isn't even a passphrase at this point. it's secure as hell but nigh impossible to remember.

<img src="https://user-images.githubusercontent.com/8546107/94972269-e5368500-04d6-11eb-8fe6-3ea9a4396951.png" width="640" height="480">


### Correct way to use passphrases + (numbers & special chars)
- I simply utilize a passphrase generated for me and do the bare minimum or slightly more to satisfy the requirements/restrictions of whatever platform I'm creating the "password" for, like:
> ```
> correct hoRse battery staple $6109
> ```

<img src="https://user-images.githubusercontent.com/8546107/94972454-4b230c80-04d7-11eb-8716-c2eb4eee60c3.png" width="640" height="480">


### Just the passphrase without the fluff
- With just the XKCD comic passphrase example it's considerably less resilient to brute force attacks:
> ```
> correct horse battery staple
> ```

<img src="https://user-images.githubusercontent.com/8546107/94973871-dc47b280-04da-11eb-8d8b-9ee5296b5d6d.png" width="640" height="480">


### The passphrase with the same amount of chars (34)
- With an additional word to make the "pure" passphrase the same length as the first two options above, the search space deepens but still doesn't compare to my _2<sup>nd</sup>_ option above in terms of search space depth.
> ```
> correct horse battery staple putts
> ```

<img src="https://user-images.githubusercontent.com/8546107/94974080-74de3280-04db-11eb-8a38-eba943f68f3b.png" width="640" height="480">

["Search Space" Calculator](https://www.grc.com/haystack.htm)
According to this passphrase tester, the first two _options_ above have the same amount of time to be guessed with a brute force attack. However, only the second passphrase is memorable, or worth the effort to remember since the first option offers zero benefits in security protections. The last two options are obviously not super weak, but comparatively they're orders of magnitude lower than the options with special chars, digits, and mixed letter cases. 

So, what I was suggesting was just having the ability to add these requirements as checkboxes in the passphrase generator so that users don't have to add additional digits, special characters, etc. and instead can just get an auto-generated passphrase immediately that includes the required character types. Perhaps the user can check things like:

- [ x ] special characters
_select one or more_
-- [ ] start of phrase
-- [ ] end of phrase
-- [ ] mixed into phrase

- [ x ] numerical digits
_select one or more_
-- [ ] start
-- [ ] end
-- [ ] interspersed
-- [ ] as a replacement for random letters


## Summary
I was suggesting this feature to help save time for users that make almost extensive use of the passphrase generator but still have to adhere to extra password requirements on certain platforms. If there doesn't seem to be any value you in that to you all, I understand. Please answer another question or two for me, if you would:
1. If I were to fork the repo and manage to implement the proposed features with clean, bug-free code, would this team consider integrating it into a future release? If not, would you please explain to me the reasons why? I'm not trying to be a PITA. I'm seriously just trying to understand what the perceived drawbacks or complications are from your team's perspective. This might help me to not feature-request-spam you all, or other dev teams, in the future, and it will give me a clear idea of whether or not I should undertake the effort to implement my proposed features in the first place, which could save me a fair amount of time.

Thanks for time and effort you all put in on this project.

**Comment by droidmonkey** [comment]
I am not going to rehash what I already stated in very plain language.
