### ISSUE TITLE
UI becomes unclickable when font-scaling is at play!

### ISSUE THREAD

**Issue by jwilson8767** [keepassxreboot/keepassxc#5468]
## Steps to Reproduce
1. On Windows 10, set one monitor to use font scaling (125% for example), but not the other.
2. Run KeePassXC and position window on screen WITHOUT font scaling, minimize it to tray.
3. Reopen hours later and (just maybe) observe that some UI elements aren't clickable.
4. Drag to screen WITH font scaling, items become clickable again!
5. Drag back to screen WITHOUT font scaling, items remain clickable!

## Expected Behavior
Font-scaling is re-evaluated upon KeePassXC returning from being minimized.

## Actual Behavior
UI items are unclickable (keyboard navigation continues to function)

## Context

KeePassXC - Version 2.6.0
Revision: 0765954

Qt 5.15.0
Debugging mode is disabled.

Operating system: Windows 10 Version 2004
CPU architecture: x86_64
Kernel: winnt 10.0.19041

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.5

Thanks so much for taking time to look at this! Love KeePassXC, have only been using for a couple of months, but really depend on it now. Way better than KeePass 2!

**Comment by jmichler** [comment]
I can reproduce this as well :-(
