### ISSUE TITLE
Compact Mode Won't Turn Off

### ISSUE THREAD

**Issue by CerebralFreeze** [keepassxreboot/keepassxc#5471]
## Overview
I turned on Compact Mode that in View Menu at top.  When I turned it off, it would return back to compact mode frequently.

## Steps to Reproduce

1. Select Compact Mode in the View menu at the of the program. 
2. Select Compact Mode again to unselect it.
3. It converted back to Normal mode but sometimes when I would press ESC from an entry, it would list the passwords in Compact Mode.

## Expected Behavior
After unselecting Compact Mode, you wouldn't see the Compact Mode again.

## Actual Behavior
It would sporadically turn back into Compact Mode.

## Context
I uninstalled and installed and that fixed the problem.  I just wanted to tell you about this bug.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.1
Revision: 9a35bba

Qt 5.15.0
Debugging mode is disabled.

Operating system: Windows 10 Version 2004
CPU architecture: x86_64
Kernel: winnt 10.0.19041

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.5

**Comment by droidmonkey** [comment]
There is no way compact mode enabled after exiting from an entry. Compact mode really means all the icons are 16 px square in the entry and group list. This only happens at startup. I doubt this was compact mode, perhaps a scaling issue on your end. Never seen it happen, probably never will.  Thanks for the report.
