### ISSUE TITLE
KeePassXC on Mac starts on wrong desktop

### ISSUE THREAD

**Issue by ghost** [keepassxreboot/keepassxc#5472]
My iMac (Catalina, 10.15.6) is configured to start up with two 'mission control' desktops, among which I can switch using Control-left or Control-right arrow, as usual. 
By right-clicking on an app's icon in the dock, it is possible to define the 'home' desktop for every app, i.e. on which desktop each app should open.
This works well with every app, both Apple's and third party's - EXCEPT, very unfortunately, with KeePass, which seems to just ignore that configuration item. KeePassXC does not care at all, it opens on the desktop that just happens to be active when KeePassXC launches.
Q: Am I doing something wrong, or is this a bug? In case it's a bug, please fix. Thank you.

**Comment by Michael-Walther** [comment]
Really no developer knows how to cope with macOS desktops? :0

**Comment by luwadmin** [comment]
Really no developer knows how to cope with macOS desktops??  :0

**Comment by droidmonkey** [comment]
Its one a a hundred platform specific anomalies.

**Comment by jtrakk** [comment]
On Linux when I close the window it seems to remember where it was, and then I switch desktops, press "toggle window", it opens in the desktop where it was when closed, not the one that's currently active.

KeePassXC 2.6.2
wm: qtile 0.16.0
