### ISSUE TITLE
Scrollbar in the middle of the "add new entry" dialog

### ISSUE THREAD

**Issue by schipplock** [keepassxreboot/keepassxc#5477]
## Overview

When I right-mouse-click "add new entry" I see a scrollbar in the middle of the window:

![keepassxcuiglitch](https://user-images.githubusercontent.com/49938/94363464-93e75980-00c2-11eb-811c-9f9cb62c1957.png)

## Steps to Reproduce

1. right-click and select "new entry" (however it's called in english, I can't switch the language of the UI)
2. a scrollbar appears in the middle of the window

## Expected Behavior

I don't expect a scrollbar in the middle of the window.

## Actual Behavior

A scrollbar appears in the middle of the window.
When I resize the window, the scrollbar disappears.

## Notes

KeePassXC - Version 2.6.1
Revision: 9a35bba
Operating System: Windows 10 (2004 build 19041.508)

**Comment by droidmonkey** [comment]
Fixed
