### ISSUE TITLE
HiDPI icons

### ISSUE THREAD

**Issue by marcbone** [keepassxreboot/keepassxc#548]
I have an 2880x1620 display on a 15.6 inch laptop and some of the icons are really small and hard to identify. Screen scaling is at 2.0. If I set the screen scaling back to 1, all icons are equally small as they should be. So the first two icons scale, but the other dont.

## Current Behavior

![bildschirmfoto vom 2017-05-06 17-18-14](https://cloud.githubusercontent.com/assets/16033059/25773693/4000cd68-3282-11e7-9886-2f56a76ba6fe.png)

## Your Environment

* KeePassXC version/commit used: 2.1.4/cb283bb95ae559d044415f426f841c27bff383f0
* Qt version (e.g. Qt 5.3): 5.6.1
* Compiler (e.g. Clang++3.6.0): dont know i installed it with snap
* Operating System and version:  Ubuntu 16.04

**Comment by wolframroesler** [comment]
The application icons are currently being reworked (#551) and will be SVG-based, no longer PNG.
