### ISSUE TITLE
Email password from command line in mutt?

### ISSUE THREAD

**Issue by tamis-laan** [keepassxreboot/keepassxc#5480]
I am checking out keepassxc and it looks really good! 

I am running a script that checks and downloads my email (offlineimap) every minute. This script requires my smtp password and I would like retrieve it from keepassxc. I know there is keepassxc-cli, however when I use the `show` command, I have to enter my password, even though I already unlocked the database using the application. 

What gives?

**Comment by droidmonkey** [comment]
There is no link between the cli and the gui application. This is tracked by #4513
