### ISSUE TITLE
Cannot Retrieve Username/Password from KeepassXC through Apple's Universal Keyboard 

### ISSUE THREAD

**Issue by gdoubleu** [keepassxreboot/keepassxc#5487]
Using KeepassKC (2.6.1, and 2.6.0), macOS 10.15.6 and iOS 14.0, I am not able to: 

- Copy a username from KeepassXC (via the Apple+B shortcut) and paste it on my phone
- Copy a password from KeepassXC (via the Apple+C shortcut) and paste in on my phone

The phone has Universal Clipboard enabled: the phone receives a notification (since iOS 14) that the content of the clipboard is being pasted, and it turns out empty

This works: 
- Copy a username from KeepassXC (via the Apple+B shortcut) and paste it locally, universal clipboard then works fine
- Copy a password from KeepassXC (via the Apple+C shortcut) and paste it locally, universal clipboard then works fine
- Copy any content from outside of KeepassXC to iOS. 

What I have noticed: 
- I am using CopyClip and none of the Copy entries from KeepassXC are listed there. I cannot tell if it is recent or not. 
- Doing a Apple+C from a username or password entry (i.e.: no on a search result) does store the entry into CopyClip, but still does not make its way to iOS.

**Comment by droidmonkey** [comment]
This is by design and won't be changed. Using a shared clipboard is absolutely the wrong move. Use Strongbox on your phone to access you database (synced through icloud)

**Comment by gdoubleu** [comment]
Well, it has been changed. It was working until recently.

**Comment by droidmonkey** [comment]
That code hasn't been touched since 2017
