### ISSUE TITLE
KeePassXC-Browser error: Key exchange was not successful (Chromium on Ubuntu 20.04)

### ISSUE THREAD

**Issue by MrBokeh** [keepassxreboot/keepassxc#5489]
The Chromium plug-in is not connecting to the desktop app:

KeePassXC-Browser has encountered an error:
Cannot connect to KeePassXC. Check that browser integration is enabled in KeePassXC settings.

KeePassXC - Version 2.6.1
Revision: bb7a74b
Distribution: Snap

Qt 5.9.5
Debugging mode is disabled.

Operating system: Ubuntu Core 18
CPU architecture: x86_64
Kernel: linux 5.4.0-48-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.1

**Comment by varjolintu** [comment]
Did you use the Snap helper script?

**Comment by onichandame** [comment]
@varjolintu Could you elaborate a bit more on why Chromium must not be installed via Snap?

**Comment by varjolintu** [comment]
@onichandame We need Native Messaging for accessing an application (proxy for the KeePassXC) outside the browser and Snap sandbox prevents that.
