### ISSUE TITLE
Reduce installation size

### ISSUE THREAD

**Issue by quentindenis** [keepassxreboot/keepassxc#5492]
Hello,

I have replaced KeePass with KeyPassXC and love it so far. However, I have seen that KeepassXC is taking up 15x more disk space than KeePass (109MB vs 7MB), which I find hard to justify since the features are essentially the same. Is there anything that can be done to better optimize the compilation?

Regards,
Quentin

**Comment by droidmonkey** [comment]
You are not seeing the size of dot net for keepass which is well over 100 MB. Our program is as small as its going to get.
