### ISSUE TITLE
Snap stable Ubuntu 20.04: Segmentation Fault

### ISSUE THREAD

**Issue by Staberinde** [keepassxreboot/keepassxc#5493]
## Overview
Segmentation fault when running keepassxc  error on Ubuntu 20.04 after installing via snap from stable

## Steps to Reproduce
1. On Ubuntu 20.04 `snap install keepassxc`
2.  `keepassxc`
 

## Expected Behavior
Keepass GUI appears

## Actual Behavior
```
 keepassxc
Fontconfig warning: FcPattern object weight does not accept value [40 210)
Segmentation fault
```

## Context
Duplicate of closed (CNR) issue https://github.com/keepassxreboot/keepassxc/issues/4235
Tried uninstall and reinstall - no effect
Tried trashing system fontcache (just in case it had an effect) with `sudo fc-cache -f -v` - no effect

KeePassXC - 2.6.1 
Revision: Snap stable
Operating System: Linux
Desktop Env: Gnome
Windowing System: X11

`snap info keepassxc`
```
name:      keepassxc
summary:   Modern, secure, and cross-platform password manager compatible with KeePass
publisher: Jonathan White (keepassxreboot)
store-url: https://snapcraft.io/keepassxc
contact:   https://github.com/keepassxreboot/keepassxc
license:   unset
description: 
...
commands:
  - keepassxc.cli
  - keepassxc
  - keepassxc.proxy
snap-id:      jf2HsR51rlftaREcwhtxiEcDc76gL4O6
tracking:     latest/stable
refresh-date: today at 12:15 BST
channels:
  latest/stable:    2.6.1 2020-08-19 (1006) 101MB -
  latest/candidate: ↑
  latest/beta:      2.6.1 2020-09-28 (1058) 106MB -
  latest/edge:      2.6.1 2020-09-28 (1055) 106MB -
installed:          2.6.1            (1006) 101MB -
```

**Comment by droidmonkey** [comment]
https://askubuntu.com/a/1244102

Try this, use -r instead of -f

**Comment by Staberinde** [comment]
Aha, that appears to have fixed it. Many thanks!
