### ISSUE TITLE
No suggestions if domain matches but url path does not match

### ISSUE THREAD

**Issue by simonschaufi** [keepassxreboot/keepassxc#5494]
## Overview
With the release 2.6.1 I have the problem that many of my stored passwords don't show up in the browser any more because of the way the matching works. If the URL doesn't match **exactly**, there are no entries in the dropdown available.

## Steps to Reproduce
1. Set the setting "only best matching results" in browser integration (I don't know the exact setting in english as I have the german version)
2. Visit a URL where there is a login form on every page that you visit for example `https://www.facebook.com/Microsoft/`
3. Have a password entry for `https://www.facebook.com/Google/`

## Expected Behavior
With the setting "only best matches" I expect that only the domain is respected (and each subdomain is independent) but the url path doesn't matter. Yes this could be useful if you have websites that are stored in subdirectories but for a login form which is shown on all subpages this is totally bad as I don't want a new entry for `https://www.facebook.com/Google/` as well.

## Actual Behavior
I need to adjust my stored password url to match exactly the URL to see the entry in the browser dropdown

KeePassXC - Version 2.6.1
Revision: 9a35bba

Operating System: Linux

**Comment by droidmonkey** [comment]
Fixed in 2.6.2 already. Will be released soon.

**Comment by simonschaufi** [comment]
fixed in #5316
