### ISSUE TITLE
Add private key to both OpenSSH and Pageant

### ISSUE THREAD

**Issue by savchenko** [keepassxreboot/keepassxc#5495]
## Summary
As of v2.6.0, KeePassXC can add a key to either SSH agent, but not to both at the same time.
This is the request to consider an option that allows to enable both simultaneously.

## Examples
![keepassxc_add_to_ssh](https://user-images.githubusercontent.com/300146/94629646-edae7600-02b2-11eb-8ff0-064f53291612.png)

## Context
Some applications have integration exclusively with PuTTy/Pageant, others happily interface with the regular `ssh-agent`.

I have tried adding a key sequentially to both and encountered no problems whatsoever.

**Comment by hifi** [comment]
This has been discussed in a few issues already. Since it's possible to bridge between different agents by using third party tools, managing keys in multiple agents is considered out-of-scope.

https://github.com/keepassxreboot/keepassxc/issues/4981

Thanks.
