### ISSUE TITLE
GUI render bug: Scroll line appearing above inputs when window opens first

### ISSUE THREAD

**Issue by dimankiev** [keepassxreboot/keepassxc#5496]
### Description:
When accessing the entry first, there appears a scroll-line, which is placed above the input fields. After resizing, the line disappearing while you focused on KeePassXC window. When you de-focus - it appears again, until window resizing
### First entry opening:
![image](https://user-images.githubusercontent.com/30737847/94686414-77058d00-0333-11eb-875f-5978b0e08165.png)
### After "de-maximizing" (window size change):
![image](https://user-images.githubusercontent.com/30737847/94686954-38bc9d80-0334-11eb-8a6a-861aab3c0ebf.png)
### After de-focusing from "de-maximized" window:
![image](https://user-images.githubusercontent.com/30737847/94687025-4d009a80-0334-11eb-82fc-c2bbf845f501.png)
### After maximizing the window:
![image](https://user-images.githubusercontent.com/30737847/94687077-5ee23d80-0334-11eb-8106-9d7808b01f5a.png)
### After de-focusing from "maximized" window:
![image](https://user-images.githubusercontent.com/30737847/94687111-6efa1d00-0334-11eb-8282-e757184b5792.png)

## System details:
**OS:** `Windows 10 Pro x64 (August 2020 updates) [Build 19041.508]`
**KeePassXC Version:** `2.6.1 (official)`
**Display resolution:** `1680x1050`

**Comment by droidmonkey** [comment]
Already fixed 2.6.2

**Comment by dimankiev** [comment]
> 
> 
> Already fixed 2.6.2

@droidmonkey, when it'll be accessible ? :)

**Comment by droidmonkey** [comment]
When it's released
