### ISSUE TITLE
Auto-Type doesn't accept REF entries, contrary to documentation

### ISSUE THREAD

**Issue by paddylandau** [keepassxreboot/keepassxc#5497]
## Overview

According to the [documentation for Auto-Type sequences](https://keepassxc.org/docs/KeePassXC_UserGuide.html#_configure_auto_type_sequences), you can use the REF field. This allows for some complex typing. Unfortunately, Auto-Type rejects it as invalid syntax.

## Steps to Reproduce

1. Create a clone of an existing entry, replacing username and password with references (to ensure that the syntax is correct).
Example of a clone:
{REF:P@I:D2FE325A3AFE49AEBAA8BE70877C8338}

2. Test it with Perform Auto-Type (Ctrl+Shift+V) to ensure that it works correctly.

Then…

### Either

3a. Change the Auto-Type to "Use custom Auto-Type sequence". Copy one of the items (e.g. the reference username) into the field.

4a. Apply the change.

### Or

3b. Create a new Auto-Type Window Association. Copy one of the items (e.g. the reference username) into the field.

4b. Apply the change.

5b. Test the change.

## Expected Behaviour

Step 4a: The change is applied without error.

Step 5b: The Auto-Type enters the referenced field.

## Actual Behavior

Step 4a: Error message, "The Syntax of your Auto-Type statement is incorrect!" It refuses to accept the change.

Step 5b: Error message, "The Syntax of your Auto-Type statement is incorrect!" It types nothing.

## Context

[NOTE]: # ( Paste debug info from Help → About here )

KeePassXC - Version 2.6.1
Revision: 9a35bba
Distribution: Snap

Qt 5.9.5
Debugging mode is disabled.

Operating system: Ubuntu Core 18
CPU architecture: x86_64
Kernel: linux 5.4.0-48-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.1

[NOTE]: # ( Pick choices based on your environment )

Operating System: Linux Ubuntu 20.04
Desktop Env: Gnome 3.36.3
Windowing System: X11

**Comment by droidmonkey** [comment]
Duplicate #2633
