### ISSUE TITLE
cursor not visible when displaying password

### ISSUE THREAD

**Issue by damnms** [keepassxreboot/keepassxc#5498]
see https://bugzilla.redhat.com/show_bug.cgi?id=1883796

**Comment by droidmonkey** [comment]
This is not our bug

**Comment by Germano0** [comment]
This is the form to fill when you open a bugreport, you did not provide required infos

```
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )


## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. 
2. 
3. 

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )


## Actual Behavior
[NOTE]: # ( Tell us what actually happens )


## Context
[NOTE]: # ( Give us any additional information you may have. )


[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows/Linux/macOS
Desktop Env: Gnome/KDE/XFCE/Mate/Cinnamon
Windowing System: X11/Wayland
```

**Comment by droidmonkey** [comment]
This is not an issue with our code, I reviewed the redhat bug report. We don't do anything with the cursor, it is all default settings. Thus this would be a desktop env or Qt issue.

**Comment by damnms** [comment]
this ticket is already closed. so no need to keep reporting here. yes it was a bug in some env or qt whatever product. its already fixed as you might see in the linked ticket.

**Comment by damnms** [comment]
i also verified that with the windows build which has no problems, as also stated in the linked ticket

**Comment by damnms** [comment]
i encountered that problem again. i tested with keepassx which has no problems. keepassxc has no cursor visible. nowhere. i also created https://bugzilla.redhat.com/show_bug.cgi?id=1883796, unfortunately the package manager gives a shit about investigating/helping to solve that. so i reopen it here - maybe someone can give me hints how to check what is going on, who is responsible for that and who should fix that.

**Comment by damnms** [comment]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )


## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. open any database and enter the password. there is no cursor
2. 
3. 

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
a cursor that blinks

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
no cursor visible

## Context
[NOTE]: # ( Give us any additional information you may have. )


[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - keepassxc-2.6.1-1.fc33.x86_64
Revision: no idea what revision means

[NOTE]: # ( Pick choices based on your environment )
Operating System: Fedora 33
Desktop Env: KDE
Windowing System: X11

**Comment by damnms** [comment]
![image](https://user-images.githubusercontent.com/40913090/96585528-06bdac00-12e0-11eb-841d-28c85b05b077.png)
thats how it looks in keepassx

![image](https://user-images.githubusercontent.com/40913090/96585606-1d640300-12e0-11eb-9614-0d36af61ba98.png)
thats how it looks in keepassxc - no cursor

**Comment by Germano0** [comment]
>  unfortunately the package manager gives a shit about investigating/helping to solve that

Oh thank you

**Comment by damnms** [comment]
no problem, you are welcome. maybe ask what information is missing instead of closing bug reports which are still occuring.
here you have that information now. 

i am no qt/c/c++ dev, so i guess when keepassx works, it should work with keepassxc, because both use qt. so for me it looks like a bug in keepassxc.

**Comment by Germano0** [comment]
**First**: here -> https://bugzilla.redhat.com/show_bug.cgi?id=1883796#c7 you said that it turned out to be a qt problem that **has been fixed** with update https://bodhi.fedoraproject.org/updates/FEDORA-2020-c8826f3dc1 So I don't know what else should I investigate. You said that the problem was fixed.
**Second**: shall I remind you that you are **not paying** for a service? This is a best effort service

**Comment by damnms** [comment]
yes, i thought it is fixed. but you closed my report way earlier before i was able to report anything back.
yes i am not paying for anything, and i am happy that devs produce open source software.
but i am also not paid in reporting bugs. i could also just ignore that and think "i dont care if 200 other people also encounter that, its not my software so why should i care". when i see something goes wrong, i report it. for fedora. for intellij. for many other products/projects. and when the dev closes my reports faster than i could answer any question, then something goes wrong. the worst would be to also just give a shit and ignore that and dnf remove keepassxc and go back to keepassx (what i currently do because of that bug). but thats not my mentality. anyway, this is a conflict which wont lead to anything productive nor to any solution.

**Comment by droidmonkey** [comment]
Does it only occur in the password fields?

**Comment by damnms** [comment]
no, everywhere in keepassxc. so either its a wrong use of textfield (no idea how thats called in qt) or a bug in the textfield

**Comment by damnms** [comment]
if keepassxc uses some special version of qt or some "new" elements (as mentioned, i have no idea of qt, but if its like in the java world like with awt -> swing -> javafx) i could try to install any other software that uses this too to see if its a problem within qt or higher. 
i also have a couple of desktop environments (kde, gnome, etc.) and window managers (ldm, gdm, etc.) - i can switch them and test there if that helps in any way

**Comment by droidmonkey** [comment]
Please paste the debug information from the about dialog (help -> about)

**Comment by damnms** [comment]
KeePassXC - Version 2.6.1
Revision: 9a35bba

Qt 5.15.1
Diagnosemodus ist deaktiviert.

Betriebssystem: Fedora 33 (Thirty Three)
CPU-Architektur: x86_64
Kernel: linux 5.8.15-301.fc33.x86_64

Aktivierte Erweiterungen:
- Auto-Type
- Browser-Integration
- SSH-Agent
- KeeShare (bestätigtes und unbestätigtes Teilen)
- YubiKey
- Secret-Service-Integration

Kryptographische Bibliotheken:
 libgcrypt 1.8.6

**Comment by droidmonkey** [comment]
Can you try using the snap or appimage version?

**Comment by damnms** [comment]
tried it with keepassxc 2.6.2 from snap: same behaviour

**Comment by damnms** [comment]
btw i use some tools, like veracrypt etc. - i know none of them which has the same problem and i guess they also use the same tools/libraries (qt etc.)

**Comment by phoerious** [comment]
I can reproduce something similar on KDE when I toggle the window multiple times from the tray while it is not in focus. That is,

1. Hide KeePassXC behind another window
2. Click tray icon (window will be activated, though not receive focus due to KWin's focus stealing prevention)
3. Click tray icon again to hide window to tray
4. Click tray icon a third time (window will be restored and activated, but as before not receive focus)
5. Click taskbar button to bring window to the front

The result is that the window is now active and I can interact with it (including typing my password), but visually, it behaves like nothing is in focus. I can fix this weird limbo state by switching focus between KPXC and another application.

I believe this is a bug in either Qt or KWin and neither in KeePassXC nor in our theme. The same issue is reproducible with the Classic theme.

**Comment by damnms** [comment]
@phoerious which distri + version are you running?
i can reproduce at all the time... unfortunately :/

**Comment by phoerious** [comment]
Kubuntu 20.04.

**Comment by damnms** [comment]
tested now plasma wayland (works) and gnome classic (works too)

**Comment by damnms** [comment]
@phoerious any idea if its more related to kwin or to qt? then i file a report against that and maybe they can shed some light on that

**Comment by droidmonkey** [comment]
Most likely kwin

**Comment by damnms** [comment]
i do not use kwin anymore, so i can not reproduce it nor create a kwin bugreport. therefore closed

**Comment by phoerious** [comment]
I do not see this in Gnome3. What I do see is that the window activation from the dock doesn't always work properly after Auto-Type. But that is probably due to generally buggy activation behaviour between GTK-based DEs and Qt apps.

**Comment by gwarser** [comment]
Looks like someone fixed this. I just noticed cursor is here.

KeePassXC - Version 2.6.2
Revision: e9b9582

Qt 5.15.2
Debugging mode is disabled.

Operating system: Manjaro Linux
CPU architecture: x86_64
Kernel: linux 5.4.80-2-MANJARO

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.7

**Comment by damnms** [comment]
gwarser, which DE do you use? i had this problem also NOT in gnome etc. - it only affected kwin related DE's (like KDE)

**Comment by gwarser** [comment]
It's KDE.

**Comment by art-solopov** [comment]
Just in case someone has a similar problem and finds this via search: I managed to mitigate the problem by switching to the platform-dependent theme.
