### ISSUE TITLE
Global Auto-Type settings are not available/visible on Fedora 32

### ISSUE THREAD

**Issue by Alejandro-FA** [keepassxreboot/keepassxc#5499]
## Overview
It is impossible to use the Global Auto-Type feature on Fedora 32, because the "Auto-Type" settings tab is not visible, so I can't configure the Global Auto-Type shortcut.

## Steps to Reproduce
1. sudo dnf install keepassxc
2. Click on the settings option of KeePassXC to see if there is an "Auto-Type" tab next to "Basic Settings".

## Expected Behavior
Next to the tab "Basic Settings" there should be an "Auto-Type" tab, that would allow me to use global auto-type on Linux, as the user guide states that it is a feature available for all three major platforms (macOS, Windows, Linux).

## Actual Behavior
Next to the "Basic Settings" tab there's nothing and, therefore, I am not able to use global auto-type because i can't configure it.

## Context
I've tried downloading KeePassXC from the Software app (which should install the snap package I think) and I've tried too building it from source (with the default options, that should install the Auto-Type feature), both attempts with the same results (Auto-Type not available). I tried downloading the AppImage too, and in this case the Auto-Type tab was visible, but:
1. The performance is very bad (it takes almost a minute to open the settings options).
2. After configuring the Global Auto-Type shortcut (with different key combinations such as Ctrl+A, Meta+Shift+A, Ctrl+Shift+A, Meta+Alt+P), typing the corresponding shortcut does nothing (except sometimes type an A).

## Debug info (KeePassXC built from source)
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.1
Revision: 9a35bba

Qt 5.14.2
Debugging mode is disabled.

Operating system: Fedora 32 (Workstation Edition)
CPU architecture: x86_64
Kernel: linux 5.8.11-200.fc32.x86_64

Enabled extensions:
- Auto-Type

Cryptographic libraries:
 libgcrypt 1.8.5

## System
[NOTE]: # (Pick choices based on your environment )
Operating System: Linux - Fedora 32 (Workstation Edition)
Desktop Env: Gnome 3.36.6
Windowing System: Wayland

**Comment by droidmonkey** [comment]
You can't use auto type while running keepassxc on Wayland. You have to run it using xwayland.

**Comment by droidmonkey** [comment]
See #228+

**Comment by Alejandro-FA** [comment]
okay, thanks
