### ISSUE TITLE
Vertical scroller in Edit Entry

### ISSUE THREAD

**Issue by Mukrosz** [keepassxreboot/keepassxc#5500]
## Overview
Hi there,
Whenever I open an entry, I see a vertical scroll bar from preceding window
![image](https://user-images.githubusercontent.com/6380481/94963794-e6a38580-04b5-11eb-8def-d8cf3a8c47db.png)

## Steps to Reproduce
Open any entry

## Expected Behavior
Not to see the vertical scroll

## Context
KeePassXC - 2.6.1
Operating System: Linux Manjaro 20.1
Desktop Env: KDE
Windowing System: X11

**Comment by droidmonkey** [comment]
Omg really, this is the 25th report I have closed

**Comment by Mukrosz** [comment]
Sorry ...

**Comment by droidmonkey** [comment]
It's fine but search before posting in the future, thank you.

https://github.com/keepassxreboot/keepassxc/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed+vertical+line

**Comment by Mukrosz** [comment]
I certainly will. Again, my apologies.
