### ISSUE TITLE
Unlock with yubikey not possible after returning from energy save mode

### ISSUE THREAD

**Issue by kirscheGIT** [keepassxreboot/keepassxc#5501]
An unlocked database will not be able to unlock with Yubikey after system was in power save mode under MacOS.

Ways to reproduce:
- Plugin the Yubikey
- Unlock the database -> Yubikey will be automatically selected and KeePassXC is prompting for pressing the button
- Database is unlocked now wait or go into suspend or power save
- Wake Up the Mac
- KeePassXC has now locked the database. When trying to unlock, the database KeePassXC is not recognizing the Yubikey anymore and says the Yubikey hardware cannot be found. Nevertheless MacOS has detected the key. Can be checked by opening a text editor and pressing the Yubikey button.

Tried Workarounds:
- Completely closing KeePassXC -> Not working
- Restarting the computer -> working

--------------------------------------------------
System Debug Info:
KeePassXC - Version 2.6.1
Revision: 9a35bba

Qt 5.15.0
Diagnosemodus ist deaktiviert.

Betriebssystem: macOS 10.15
CPU-Architektur: x86_64
Kernel: darwin 19.6.0

Aktivierte Erweiterungen:
- Auto-Type
- Browser-Integration
- SSH-Agent
- KeeShare (bestätigtes und unbestätigtes Teilen)
- YubiKey
- TouchID

Kryptographische Bibliotheken:
 libgcrypt 1.8.5

----------------------- 
Used Token: Yubikey 5Ci

**Comment by droidmonkey** [comment]
Have you tried simply unplugging the key and plugging it back in?

**Comment by kirscheGIT** [comment]
> Have you tried simply unplugging the key and plugging it back in?

Yes, doesn't change anything. MacOS is recognizing the hardware, KeePassXC can't find it.

**Comment by droidmonkey** [comment]
There is not much we can do about this. Yubikey interface has been steadily improved over the versions.
