### ISSUE TITLE
Change of behaviour on URL detection for browser-autofill  

### ISSUE THREAD

**Issue by pakar** [keepassxreboot/keepassxc#5508]
## Overview
Autofill stopped working after the last upgrade. Issue seems to be related to changed behavior of the URL matching

## Steps to Reproduce
In this case i'm using https://login.launchpad.net/+login for reproduction of the issue, but the same behaviour is experienced on all sites.
Ex 1: Edit entry and set URL to "https://login.launchpad.net/+login" and is successfully manages to auto-fill
Ex 2: Edit entry and set URL to "https://login.launchpad.net" and it fails to auto-fill
Ex 3: Edit entry and set URL to "login.launchpad.net" and it fails to auto-fill
Ex 4: Edit entry and set URL to "launchpad.net" and it fails to auto-fill.

## Expected Behavior
In all of the above examples it should be able to auto-fill the login-fields.
This is a changed behavior from previous versions and does not really make sense.
I would expect the following when entering something in the URL field.
"https://login.launchpad.net" to match "https://login.launchpad.net/*"
"https://launchpad.net" to match https://launchpad.net/**"
"launchpad.net" to match the top-domain launchpad.net or subdomain of it "*.launchpad.net"
"login.launchpad.net" to match the top-domain login.launchpad.net or subdomain of it "*.login.launchpad.net"

## Context
After i upgraded to 2.6.1 (not sure about previous version) of keepassxc this started happening.

## Info
KeePassXC - Version 2.6.1
Revision: 9a35bba

Qt 5.12.8
Debugging mode is disabled.

Operating system: Ubuntu 20.04.1 LTS
CPU architecture: x86_64
Kernel: linux 5.8.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.5

Desktop Env: XFCE
Windowing System: X11

**Comment by droidmonkey** [comment]
Already fixed in 2.6.2
