### ISSUE TITLE
Auto-Type fails with some password fields

### ISSUE THREAD

**Issue by Msg1992** [keepassxreboot/keepassxc#5510]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
Auto-Type fails on some sites with the password field. The password is written 2-times into the password field

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Go on a page like: https://www.paypal.com/signin
2. Have Keepass XC opened
3. Click on the website on the username field
4. Go to Keepass and select the entry you want to fill in
5. Press Ctrl-Shift-V for filling in

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Log In with only one time password written in

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
On the password login it writes two times the password in

## Context
[NOTE]: # ( Give us any additional information you may have. )
This happened to me on sites like PayPal and Dropbox. Hopefully, someone can repeat this issue. You can do a simple test entry with a password of known length: e.g. user: test123, Password: 123. Then go on the website mentioned above and try the auto-fill from the desktop app. You hopefully will see that the Password is written two times in.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.1
Revision: 9a35bba

Qt 5.15.0
Debugging mode is disabled.

Operating system: Windows 10 Version 2004
CPU architecture: x86_64
Kernel: winnt 10.0.19041

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.5

**Comment by droidmonkey** [comment]
This is because you are using both Auto-Type and the browser plugin at the same time. Pick one or the other.

**Comment by Msg1992** [comment]
Oh no ... no I feel stupid :D
Thanks for this Jonathan! 

Greets Maximilian
