### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by jaycarlinux** [keepassxreboot/keepassxc#5512]
## Overview
Keepassxc with Mint18.3 crashes when 2nd letter is typed into search box Icon only toolbar
## Steps to Reproduce
1. start keepassxc load .kdbx file 
2. enter text into search bar 2nd letter causes crash
3. 

## Expected Behavior
begins search for user id/password that matches text in search bar

## Actual Behavior
Keepassxc crashes

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION 2.6.1
Revision: REVISION  9a35bba
Qt 5.5.1
Debugging mode is disabled.

Operating system: Linux Mint 18.3
CPU architecture: x86_64
Kernel: linux 4.15.0-118-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.1

[NOTE]: # ( Pick choices based on your environment )
Operating System:Linux Mint 
Desktop Env: Cinnanmon
Windowing System: ? X11/Wayland

**Comment by droidmonkey** [comment]
This is a known bug in Qt 5.5, you should run the AppImage or snap package.

**Comment by jaycarlinux** [comment]
JohnathonThanks very much .. installed snap package which resolved issuesJay
    On Monday, October 5, 2020, 08:22:20 PM EDT, Jonathan White <notifications@github.com> wrote:  
 
 


This is a known bug in Qt 5.5, you should run the AppImage or snap package.
