### ISSUE TITLE
Can't save database as it is not "Initialized"

### ISSUE THREAD

**Issue by maztan** [keepassxreboot/keepassxc#5515]
I can't save the database and I am getting the error originating from this code:

```
// Never save an uninitialized database
    if (!isInitialized()) {
        if (error) {
            *error = tr("Could not save, database has not been initialized!");
        }
        return false;
    }
```

How do I initialize the database?

**Comment by maztan** [comment]
Ok, I added a key file to the database, now it works.
Based on this code:
```
bool Database::isInitialized() const
{
    return m_data.key && !m_data.key->isEmpty() && m_rootGroup;
}
```

I propose adding more informative error message ;)

**Comment by droidmonkey** [comment]
Thats not what that code means.

**Comment by Schroedingers-Cat** [comment]
This message is also shown when a user opens a kepass file created with keepassdx (Android) without any encryption. In such a case, the error message is not meaningful. It should show something like "Not saving unencrypted database file". Best to show that warning upfront when opening such a file.
