### ISSUE TITLE
Misplaced scroll bar

### ISSUE THREAD

**Issue by jeanmigaillard** [keepassxreboot/keepassxc#5516]
The scroll bar when editing an entry places it in the middle and obstructs some of the information with the dark or light theme.

![2020-10-06 10_44_04-Window](https://user-images.githubusercontent.com/25621204/95179460-ee6a6f00-07c0-11eb-950a-302af1f3848d.png)

See capture.

Windows 10 2004 (19041.546)

Regards,

**Comment by shrinedrift4553** [comment]
Why has this been closed? I'm having the same issue.

**Comment by phoerious** [comment]
It's one of about a hundred duplicates.

**Comment by shrinedrift4553** [comment]
My bad. I'm new to Github. Original is 5300, it should say that where on this post.
