### ISSUE TITLE
Problem enter quotation mark in passphrase field to unlock the database with US Intl layout

### ISSUE THREAD

**Issue by tobias-weiss** [keepassxreboot/keepassxc#5517]
## Overview

My passphrase to unlock my database contains a quotation mark ("). I use the US Intl keyboard layout. With Layout you need to press " key and afterwards the space key. 

If the passphrase is not shown during input, the input reads a white space instead of the ". Only if make the input visible whenI type the password the correct character will be entered.

## Steps to Reproduce

1. Open KeepassXC
2. Unlock the database with passphrase that contains  a quotation mark using US Intl Layout wihout making input visible
3. make input visible and see a white spacce instead of quotation mark

## Expected Behavior

get a quotation mark also during input where you dont see what you are typing

## Actual Behavior

a white space is where should be a quotation mark

## Context

KeePassXC - Version 2.6.1
Revision: 9a35bba

tested with AppImage from homepage
also with packeged version in Debian Bullseye

Operating System: Linux (Debian)
Desktop Env: Gnome
Windowing System: Wayland

**Comment by droidmonkey** [comment]
This is a qt bug fixed in 5.10+
