### ISSUE TITLE
Auto-Type initiated with keyboard shortcut doesn't work, but does work with menu

### ISSUE THREAD

**Issue by Clouds123** [keepassxreboot/keepassxc#5519]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
If I try to do an Auto-Type by using the keyboard shortcut (ie. Shift+Cmd+V), it doesn't work. eg. on Github it doesn't enter anything in the Username field, but does fill in the password field (although not sure if it puts the user name or password in this field). However, it works fine if I use the menu option Entries > Perform Auto-Type.

Occasionally on other sites, it complains the window title doesn't match, but the window title mentioned is the KeePassXC window title, instead of the web browsers title.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Open Github.com, click login and give the user name field the focus by clicking on it
2. Switch to KeePassXC, select the Github entry
3. Press Shift+Cmd+V
4. Repeat above, but for step 3, use menu item Entries > Perform Auto-Type

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Keyboard shortcut and menu entry for Perform Auto-Type should do the same

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Keyboard shortcut doesn't work, while menu entry does

## Context
[NOTE]: # ( Give us any additional information you may have. )
This also happened on KeePassXC 2.5.x

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.1
Revision: 9a35bba

Qt 5.15.0
Debugging mode is disabled.

Operating system: macOS Mojave (10.14)
CPU architecture: x86_64
Kernel: darwin 18.7.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
 libgcrypt 1.8.5

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS

**Comment by droidmonkey** [comment]
There is absolutely no difference between using the keyboard shortcut and pressing the toolbar button or using the menu... it triggers the same code. This is not reproducable.

**Comment by Clouds123** [comment]
All I can say is that is not what I am seeing. Menu option works as expected, but keyboard shortcut doesn't.
