### ISSUE TITLE
Create New Database Memory Crash Windows

### ISSUE THREAD

**Issue by jrodriguez142514-dev** [keepassxreboot/keepassxc#5520]
When trying to create a new database KeePassXC crashes.

## Steps to Reproduce
1. On home screen, click Create new database
2. Leave default settings, press Continue
3. Leave default encryption settings, press Continue
4. Program Crashed

## Expected Behavior
Allows creation of new database

## Actual Behavior
Program Crashes

KeePassXC: Windows - Application Error
The instruction at 0x00000000011F1ED9 referenced memory at 0x0000000000000008. The memory could not be read.

Click on OK to terminate the program

Debug Info:
KeePassXC - Version 2.6.1
Revision: 9a35bba

Qt 5.15.0
Debugging mode is disabled.

Operating system: Windows 10 Version 2004
CPU architecture: x86_64
Kernel: winnt 10.0.19041

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.5

**Comment by droidmonkey** [comment]
I cannot reproduce this at all
