### ISSUE TITLE
Add more file formats to import from other password managers.

### ISSUE THREAD

**Issue by git-collab** [keepassxreboot/keepassxc#5521]
## Summary
It would be great if more import option can be added (like keepass, it has a number of file types to be imported from) as CSV format doesn't work well with import. Currently KeepassXC has only CSV as import filetype.
I tried with a CSV file exported from Bitwarden but its a mess. There's no option to import from JSON.

![keepassXcImport](https://user-images.githubusercontent.com/58650699/95324190-29ec6280-08c1-11eb-993d-f2cd877fbd0f.PNG)
## Examples
Adding a screenshot from Keepass

![KeepassImport](https://user-images.githubusercontent.com/58650699/95324148-193bec80-08c1-11eb-902f-ec9c89a9f62d.PNG)

## Context
This will be helpful for people migrating from other password managers and for managing local backups.

**Comment by droidmonkey** [comment]
We will welcome any pull requests that add this capability, but we are not going to add anymore at this time from the official development team.

**Comment by droidmonkey** [comment]
Closing this as we have issues tracking other importers, open a specific request if you need one.
