### ISSUE TITLE
2.6.1 crashes on macOS Catalina 10.15.6

### ISSUE THREAD

**Issue by xgp** [keepassxreboot/keepassxc#5522]
## Overview
Arbitrary crashes.

## Steps to Reproduce
Open the app. Command-Tab away. Command-Tab back. Do it a few times. It crashes.

https://youtu.be/rm9VseIYkus

## Expected Behavior
No crashes.

## Actual Behavior
Crashes.

## Context
Running MacOS Catalina 10.15.6 (19G2021)

[NOTE]: # ( Paste debug info from Help → About here )
```
KeePassXC - Version 2.6.1
Revision: 9a35bba

Qt 5.15.0
Debugging mode is disabled.

Operating system: macOS 10.15
CPU architecture: x86_64
Kernel: darwin 19.6.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
 libgcrypt 1.8.5
```

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS
Desktop Env:
Windowing System:

**Comment by droidmonkey** [comment]
Need more context. Is it running on own desktop, maximized, etc? This is not a problem for anyone else so must be unique to your setup.

**Comment by xgp** [comment]
Thanks for the fast look. Running on the same desktop as other apps (iMovie, Emacs, Finder, iTerm2, Zoom, Skype, TextEdit, VSCode, Timer). Size of the window unchanged from default for install. See video for more.

**Comment by droidmonkey** [comment]
Gotcha will attempt that reproduction.

**Comment by xxyzz** [comment]
Not sure if this is related, I get a segmentation fault with 2.6.1 on mac 10.15.7 but I can't reproduce it. Here is part of the crash report:

<details>
Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000012
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [49427]

VM Regions Near 0x12:
--> 
    __TEXT                 000000010d746000-000000010db3f000 [ 4068K] r-x/r-x SM=COW  /Applications/KeePassXC.app/Contents/MacOS/KeePassXC

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   org.qt-project.QtGui          	0x000000010e562818 QTextLayout::drawCursor(QPainter*, QPointF const&, int, int) const + 616
1   org.qt-project.QtWidgets      	0x000000010df7c344 QWidgetLineControl::draw(QPainter*, QPoint const&, QRect const&, int) + 596
2   org.qt-project.QtWidgets      	0x000000010df76933 QLineEdit::paintEvent(QPaintEvent*) + 1779
3   org.qt-project.QtWidgets      	0x000000010de70855 QWidget::event(QEvent*) + 1093
4   org.qt-project.QtWidgets      	0x000000010df74c85 QLineEdit::event(QEvent*) + 725
5   org.qt-project.QtWidgets      	0x000000010de36ce6 QApplicationPrivate::notify_helper(QObject*, QEvent*) + 262
6   org.qt-project.QtWidgets      	0x000000010de38125 QApplication::notify(QObject*, QEvent*) + 581
7   org.qt-project.QtCore         	0x000000010ec46de4 QCoreApplication::notifyInternal2(QObject*, QEvent*) + 212
8   org.qt-project.QtWidgets      	0x000000010de62393 QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) + 3411
9   org.qt-project.QtWidgets      	0x000000010de6ab77 QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) + 1079
10  org.qt-project.QtWidgets      	0x000000010de626aa QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) + 4202
11  org.qt-project.QtWidgets      	0x000000010de6ab77 QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) + 1079
12  org.qt-project.QtWidgets      	0x000000010de626aa QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) + 4202
13  org.qt-project.QtWidgets      	0x000000010de6ab77 QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) + 1079
14  org.qt-project.QtWidgets      	0x000000010de626aa QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) + 4202
15  org.qt-project.QtWidgets      	0x000000010de6ab77 QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) + 1079
16  org.qt-project.QtWidgets      	0x000000010de626aa QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) + 4202
17  org.qt-project.QtWidgets      	0x000000010de6ab77 QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) + 1079
18  org.qt-project.QtWidgets      	0x000000010de626aa QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) + 4202
19  org.qt-project.QtWidgets      	0x000000010de6ab77 QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) + 1079
20  org.qt-project.QtWidgets      	0x000000010de626aa QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) + 4202
21  org.qt-project.QtWidgets      	0x000000010de6ab77 QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) + 1079
22  org.qt-project.QtWidgets      	0x000000010de626aa QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) + 4202
23  org.qt-project.QtWidgets      	0x000000010de6ab77 QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) + 1079
24  org.qt-project.QtWidgets      	0x000000010de626aa QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) + 4202
25  org.qt-project.QtWidgets      	0x000000010de6ab77 QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) + 1079
26  org.qt-project.QtWidgets      	0x000000010de626aa QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) + 4202
27  org.qt-project.QtWidgets      	0x000000010de6ab77 QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) + 1079
28  org.qt-project.QtWidgets      	0x000000010de626aa QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) + 4202
29  org.qt-project.QtWidgets      	0x000000010de6ab77 QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) + 1079
30  org.qt-project.QtWidgets      	0x000000010de626aa QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) + 4202
31  org.qt-project.QtWidgets      	0x000000010de4452c 0x10de26000 + 124204
32  org.qt-project.QtWidgets      	0x000000010de44832 0x10de26000 + 124978
33  org.qt-project.QtWidgets      	0x000000010de70a7e QWidget::event(QEvent*) + 1646
34  org.qt-project.QtWidgets      	0x000000010df81b04 QMainWindow::event(QEvent*) + 276
35  org.qt-project.QtWidgets      	0x000000010de36ce6 QApplicationPrivate::notify_helper(QObject*, QEvent*) + 262
36  org.qt-project.QtWidgets      	0x000000010de38125 QApplication::notify(QObject*, QEvent*) + 581
37  org.qt-project.QtCore         	0x000000010ec46de4 QCoreApplication::notifyInternal2(QObject*, QEvent*) + 212
38  org.qt-project.QtCore         	0x000000010ec47f63 QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) + 803
39  libqcocoa.dylib               	0x0000000110dd38a2 0x110d9a000 + 235682
40  libqcocoa.dylib               	0x0000000110dd3fa8 0x110d9a000 + 237480
41  com.apple.CoreFoundation      	0x00007fff38635d52 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
42  com.apple.CoreFoundation      	0x00007fff38635cf1 __CFRunLoopDoSource0 + 103
43  com.apple.CoreFoundation      	0x00007fff38635b0b __CFRunLoopDoSources0 + 209
44  com.apple.CoreFoundation      	0x00007fff3863483a __CFRunLoopRun + 927
45  com.apple.CoreFoundation      	0x00007fff38633e3e CFRunLoopRunSpecific + 462
46  com.apple.HIToolbox           	0x00007fff37260abd RunCurrentEventLoopInMode + 292
47  com.apple.HIToolbox           	0x00007fff372607d5 ReceiveNextEventCommon + 584
48  com.apple.HIToolbox           	0x00007fff37260579 _BlockUntilNextEventMatchingListInModeWithFilter + 64
49  com.apple.AppKit              	0x00007fff358a6039 _DPSNextEvent + 883
50  com.apple.AppKit              	0x00007fff358a4880 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1352
51  com.apple.AppKit              	0x00007fff3589658e -[NSApplication run] + 658
52  libqcocoa.dylib               	0x0000000110dd2d34 0x110d9a000 + 232756
53  org.qt-project.QtCore         	0x000000010ec42fb7 QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) + 439
54  org.qt-project.QtCore         	0x000000010ec47372 QCoreApplication::exec() + 130
55  org.keepassxc.keepassxc       	0x000000010d74fb70 0x10d746000 + 39792
56  libdyld.dylib                 	0x00007fff726a5cc9 start + 1

Thread 1:: com.apple.CFSocket.private
0   libsystem_kernel.dylib        	0x00007fff727ef0fe __select + 10
1   com.apple.CoreFoundation      	0x00007fff3865ec53 __CFSocketManager + 641
2   libsystem_pthread.dylib       	0x00007fff728aa109 _pthread_start + 148
3   libsystem_pthread.dylib       	0x00007fff728a5b8b thread_start + 15

Thread 2:: com.apple.NSEventThread
0   libsystem_kernel.dylib        	0x00007fff727e6dfa mach_msg_trap + 10
1   libsystem_kernel.dylib        	0x00007fff727e7170 mach_msg + 60
2   com.apple.CoreFoundation      	0x00007fff38635ef5 __CFRunLoopServiceMachPort + 247
3   com.apple.CoreFoundation      	0x00007fff386349c2 __CFRunLoopRun + 1319
4   com.apple.CoreFoundation      	0x00007fff38633e3e CFRunLoopRunSpecific + 462
5   com.apple.AppKit              	0x00007fff35a47954 _NSEventThread + 132
6   libsystem_pthread.dylib       	0x00007fff728aa109 _pthread_start + 148
7   libsystem_pthread.dylib       	0x00007fff728a5b8b thread_start + 15

Thread 3:
0   libsystem_pthread.dylib       	0x00007fff728a5b68 start_wqthread + 0

Thread 4:
0   libsystem_pthread.dylib       	0x00007fff728a5b68 start_wqthread + 0

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0x00007ffee24b5ce0  rcx: 0x000000000000000a  rdx: 0x00000000e3e17047
  rdi: 0x00007ffee24b5ce0  rsi: 0x0000600000f9a300  rbp: 0x00007ffee24b5bc0  rsp: 0x00007ffee24b5b10
   r8: 0x000000000000007f   r9: 0x00000000000007fb  r10: 0x0000000000002300  r11: 0x0000000000000080
  r12: 0x0000000000000304  r13: 0x0000600001d151d8  r14: 0x00000000000000c4  r15: 0x0000000000000000
  rip: 0x000000010e562818  rfl: 0x0000000000010246  cr2: 0x0000000000000012
  
Logical CPU:     0
Error Code:      0x00000004 (no mapping for user data read)
Trap Number:     14
</details>

**Comment by droidmonkey** [comment]
That crashed in Qt code

**Comment by droidmonkey** [comment]
I cannot reproduce the Cmd+Tab crash

**Comment by xgp** [comment]
After a restart, I am also unable to reproduce. Apologies, but it looks like it's something that got changed locally that was causing the crash. Thanks for the help.
