### ISSUE TITLE
Can not get credential in some website

### ISSUE THREAD

**Issue by hewittchoi** [keepassxreboot/keepassxc#5523]
## Overview
Can not get credential in some website

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. My database has passwords of mail.163.com, mail.126.com, but they could not be recognised by the browser integration.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.6.1
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows

**Comment by varjolintu** [comment]
Use `https://163.com` etc. as the URL.

**Comment by hewittchoi** [comment]
It works. Thank you!

**Comment by droidmonkey** [comment]
This is fixed in the upcoming 2.6.2
