### ISSUE TITLE
Allow to search entries when using global auto type 

### ISSUE THREAD

**Issue by nitramek** [keepassxreboot/keepassxc#5524]
## Summary
When using using global auto type instead of showing dialog the window wasnt match with anything, XC would show a searchbar. This would allow to search through entries (via name or configurable propertis) and would show results in a window allowing user to select search entry to auto type and allowing to use alternate action (like copy passwod for example, via key modifier).

This describes basically plugin which I use to classic KeePass [AutoTypeSearch](https://sourceforge.net/projects/autotypesearch/). It is better described there I believe.

When users has manual control over auto typing entries, they can auto type in different windows without having to add the windows to the entry itself. It also allows to save one entry for different URLs without the problem of saving another allowed url. Only thing needed is remembering part of the entry.

[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )
![image](https://a.fsdn.com/con/app/proj/autotypesearch/screenshots/QuickSearchWindow.png/max/max/1)
reference: [KeePass AutoTypeSearch plugin](https://sourceforge.net/projects/autotypesearch/) 

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
I would like to use KeePassXC but I only use this setup for providing credintials thus this feature stops me from switching.

**Comment by droidmonkey** [comment]
Duplicate request

**Comment by nitramek** [comment]
Where I can find duplicate issue? I searched for it before submitting and I couldn't find it.

**Comment by droidmonkey** [comment]
#429
