### ISSUE TITLE
Random password generator does not remember set configuration

### ISSUE THREAD

**Issue by tasso85** [keepassxreboot/keepassxc#5525]
## Overview
When generating a random password for a new entry, after having previously configured advanced mod, the password generator seems to internally revert to simple mode, skipping additional settings previously set.

## Steps to Reproduce
This is currently my "simple" setup:

![2020-10-08 09_57_22-Personale - KeePassXC](https://user-images.githubusercontent.com/655560/95430952-c90a6c00-094c-11eb-8c0f-166af444cd60.png)

I then switch to "advanced" and configure it as:

![2020-10-08 09_58_54-Personale - KeePassXC](https://user-images.githubusercontent.com/655560/95431056-e8a19480-094c-11eb-897d-50837799cbd9.png)

Now, if I close the generator, and reopen it, it reopens in "advanced" mode with my previous config, but all generated password don't apply this configuration: to test this I generated many passwords and noticed none of them had any symbols, even though I had selected them in the characters type list.

## Expected Behavior
The application should remember previous configuration and immediately apply it.

## Actual Behavior
The symbols started appearing only after I changed the configuration, for example by disabling and re-enabling the symbols.

## Context
KeePassXC - Versione 2.6.1
Revisione: 9a35bba

Qt 5.15.0
La modalità di debug è disabilitata.

Sistema operativo: Windows 10 Version 2004
Architettura CPU: x86_64
Kernel: winnt 10.0.19041

Estensioni abilitate:
- Completamento automatico
- Integrazione con i browser
- Agente SSH
- KeeShare (condivisione firmata e non firmata)
- YubiKey

Librerie crittografiche:
 libgcrypt 1.8.5

Operating System: Windows 10 Pro

**Comment by droidmonkey** [comment]
This was a bug, it is fixed in the upcoming release 2.6.2
