### ISSUE TITLE
expiration year when manually entered shows up with thousands separator 

### ISSUE THREAD

**Issue by adudek16** [keepassxreboot/keepassxc#5527]
## Overview
When entering the expiration date's year, it shows up with thousands separator in the calendar picker even after saving.

## Steps to Reproduce
1.  Check Expires
2. Use the calendar selection (the arrow)
3. change the year 
4. Hit enter

## Expected Behavior
to display the year correctly without separator

## Actual Behavior
displays the year correctly with separator
<img width="240" alt="Calendar issue" src="https://user-images.githubusercontent.com/15655321/95478759-f1e42e80-0957-11eb-879a-c0949c8e5a77.png">

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.1
Revision: 9a35bba

Qt 5.15.0
Debugging mode is disabled.

Operating system: macOS 10.15
CPU architecture: x86_64
Kernel: darwin 19.6.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
 libgcrypt 1.8.5

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS

**Comment by droidmonkey** [comment]
This looks like a regional settings issue on your end.
