### ISSUE TITLE
Health Check - Sorting by Score is done by text not by number

### ISSUE THREAD

**Issue by CarliJoy** [keepassxreboot/keepassxc#5532]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Go to Database > Database Reports
2. Click on Score to sort the column for score

## Expected Behavior
The score is sorted by number
So -15, -10, -3, -1, ...

## Actual Behavior
The Score is sorted by string not by number, see:
![Screenshot](https://kound.de/github/Screenshot_20201009_234754.png)

## ContextNone

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.1
Revision: 9a35bba

[NOTE]: # ( Pick choices based on your environment )
Operating system: Ubuntu 20.04.1 LTS
CPU architecture: x86_64
Kernel: linux 5.4.0-48-generic
Desktop Env: KDE
Windowing System: X11

**Comment by droidmonkey** [comment]
Already fixed in 2.6.2
