### ISSUE TITLE
KeepassXC isn't locked on forced reboot

### ISSUE THREAD

**Issue by r0ckarong** [keepassxreboot/keepassxc#5540]
## Overview
This is probably related to https://github.com/keepassxreboot/keepassxc/issues/4605 but not a direct duplicate.
I have auto-login enabled in my system. Today I did a reboot using "sudo reboot" and when the session came back up KeepassXC was up and running unlocked. I have the option "Lock database when session is locked or lid is closed" enabled.

## Steps to Reproduce
1. Configure session to use auto-login
2. Open KeePassXC and open a database
3. Set KeePassXC to automatically start on boot (pin to TaskManager in openSUSE will do this)
3. Force a reboot with "sudo reboot" from the terminal
4. Wait for session to reload.

## Expected Behavior
Sessions comes back, logs in and starts a locked session of kpxc.

## Actual Behavior
Session resumes with the same opened sessions from before exposing all credentials.

## Context
I think this only happens when the OS restores the desktop session state which includes kpxc.

KeePassXC - Version 2.6.1
Revision: 9a35bba

Qt 5.15.1
Debugging mode is disabled.

Operating system: openSUSE Tumbleweed
CPU architecture: x86_64
Kernel: linux 5.8.14-1-default

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (only unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.6

Operating System: Linux
Desktop Env: KDE
Windowing System: X11

**Comment by droidmonkey** [comment]
Restoring the desktop session only means starting the applications that were running when it last ended. I doubt greatly that the session is being restored with exact RAM restore.

**Comment by r0ckarong** [comment]
Ok weird, this time it was properly locked after reboot. I'll see if this happens again. Closing for now.
