### ISSUE TITLE
FIND:  [Command-F] should always bring up find dialog

### ISSUE THREAD

**Issue by jeremyguthrie** [keepassxreboot/keepassxc#5544]
## Overview
Today if you have KeepassXC open and it is sized such that the 'find' text box in the upper right is not visible on the ribbon, then '[Command]-F' does not appear to do anything.  You cannot [Command]-F and type to search.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1.  Open/login into keepass 
2.  Resize the window such that you can only see up to 'Lock Database' on the menu bar
3.  Control/Command-F will NOT bring up the find dialog or functionality.

## Expected Behavior
-  Find should bring up a box and let you type so you can find things in keepass

## Actual Behavior
-  It does nothing, no find dialog, no typing to refine search

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.6.1
Revision: ?

Operating System: MacOS

**Comment by droidmonkey** [comment]
Duplicate issue
