### ISSUE TITLE
Add ability to activate instance from command line, for "spawn/exec" window managers (or DE) commands

### ISSUE THREAD

**Issue by etosan** [keepassxreboot/keepassxc#5546]
## Summary
Both keepassxc-cli and main executable should support activating/focusing running instance from command line:

## Examples

Keepass CLI should certainly be able to popup GUI instance - mainly from scripts, etc. On *NIX xorg platforms DISPLAY variable detection could be used to locate running keepass GUI:

```
$ keepassxc-cli popui
# UI pops
```

Perhaps message argument should be added to identify originator? Might have security implications:

```
$ keepassxc-cli popui -m 'From script XXX'
# UI pops with message displaying somewhere.
```

GUI itself currently fails when instance is already running which is correct:
```
$ keepassxc       
Another instance of KeePassXC is already running.
```

It would be nice if it could reactivate itself too:
```
$ keepassxc --activate-instance
# UI pops
```

## Context
This feature would allow to invoke/activate keepass window with externally bound shortcut/script (like from configurable window manager) without requirement to code global shortcuts codepath into the keepass application itself. It also allows greater configurability for user.

**Comment by droidmonkey** [comment]
The running instance of keepassxc should already pop up when attempting to start another. We won't link the cli with opening the gui though. That is counterintuitive.

**Comment by etosan** [comment]
Understood, GUI part should still come "forward". 

It does not do that in my setup. I wonder if it's caused by window not being actually closed, but "hidden" by other means (minimized?). For example ksnip window has no problem coming forward when it's needed - my hunch is that ksnip actually destroys the window and recreates it when called? Not sure.

I will also dive deeper into my WM, to see whether it seems some urgency or other raising hints from keepassxc.

Indeed invoking keepassxc second time does not produce error exit code yet the line indicates it a bit(?):
```
$ keepassxc
Another instance of KeePassXC is already running.
$ echo ${?}
0
```

**Comment by etosan** [comment]
Maybe tangentially related to #5390 as well?

**Comment by droidmonkey** [comment]
Please include your operating system and desktop env specs so we can try to reproduce.

**Comment by etosan** [comment]
Please see my edited [comment](https://github.com/keepassxreboot/keepassxc/issues/5547#issuecomment-722591381)  in #5547.

**Comment by droidmonkey** [comment]
Covered by #99
