### ISSUE TITLE
Re-select previously selected entry on database unlock

### ISSUE THREAD

**Issue by etosan** [keepassxreboot/keepassxc#5548]
## Overview
When keepass gets locked, it forgets entry selected, while groups open close states are still remembered.
Keepass should re-select/re-focus last selected entry on unlocking the database.

## Steps to Reproduce
1. Select 2nd entry in expanded and deeply nested group.
2. Lock keepass
3. Unlock keepass
4. While group open/close states are preserved currently selected entry is forgotten.
5. First entry of first group is selected

## Expected Behavior
Formerly selected entry should be re-selected/re-focused on unlock.

## Actual Behavior
Formerly selected entry is forgotten.

**Comment by spartanicus** [comment]
I might add to this the memory of the last selected group on unlock as referenced by this closed ticket:
https://github.com/keepassxreboot/keepassxc/issues/3547

It would be excellent (like keepassx did in the past) if the most recently selected entry OR group were still in place on unlock.

**Comment by etosan** [comment]
Works perfectly, thanks!

**Comment by kitorsoft** [comment]
It works fine when unlocking the database.

I would really love to see the same behaviour when opening a database, i. e. remember the selected group when you save the database and select it again when opening it.

I guess all the code is already there, maybe with the exception of saving and retrieving the selected group to/from the database. This could easily be saved in the database along with the settings, which is already done.

Pretty please?

**Comment by michaelk83** [comment]
@kitorsoft You should post a new bug report with steps to reproduce. When you open the DB without unlocking it, you're not supposed to see anything, so I for one don't understand where the problem is. Did you mean, *unlock* after closing, vs unlock without closing the DB?

**Comment by kitorsoft** [comment]
@michaelk83 I should have been clearer, I did mean unlock after closing vs unlock after locking. I will file a bug report as you suggested, thank you.

**Comment by droidmonkey** [comment]
There is already a feature request for that. Don't file a new request, thank you
