### ISSUE TITLE
About shortcut keys to add "New entry"

### ISSUE THREAD

**Issue by GithubABCDEFG** [keepassxreboot/keepassxc#5551]
Thanks so for you all work, I want to say it is really great.

However, this does have some minor problems.

That password of PC application is not only a browser, but it seems that the only way to add a password with a shortcut key is on the browser. What I want to say is that in other password application environments of the PC, there should be a global shortcut key to wake up the software "New entry".

**Comment by droidmonkey** [comment]
This is planned already thank you!
