### ISSUE TITLE
Automatic password input does not work on BitLocker

### ISSUE THREAD

**Issue by GithubABCDEFG** [keepassxreboot/keepassxc#5552]
On the unlock interface of BitLocker，When I press down the shortcut key combination that automatically enters the password, a window will pop up telling me that the window entry cannot be found.
In fact, no matter how I set the window title in KeepassXC, It does not work. it can not select the corresponding entry from the database.

**Comment by GithubABCDEFG** [comment]
> You will probably have to use the entry level autotype, Ctrl + Shift + V. This will autotype into the last active window just prior to switching to keepassxc.

Thank you for your reply. 
But, It(Ctrl + Shift + V) does not act on the Global, when I move out the focus of password input of the windows, disappear the windows immediately. So, It does not work.

**Comment by droidmonkey** [comment]
Care to share a screenshot of this bitlocker window?

**Comment by GithubABCDEFG** [comment]
![image](https://user-images.githubusercontent.com/71936859/96336741-8887bc80-10c9-11eb-930d-1fc57dadc5e1.png)
This window can only be displayed if it is kept at the forefront, otherwise it will disappear immediately.

**Comment by droidmonkey** [comment]
There is nothing we can do to make that dialog better, unfortunately. You can use the command line to unlock bitlocker drives though: https://www.wikihow.com/Unlock-Bitlocker-Encrypted-Drive-from-Command-Prompt

**Comment by GithubABCDEFG** [comment]
Dear Mr droidmonkey, Thank you very much for your help. 
The problem can be solved by Command. In addition, I want to know whether I can enter Exit in the "Special Key" input or other input? Regarding automatic input, my setting is "{Password}{Enter}", and I need to enter "exit" and "enter" to end the CMD window.

**Comment by droidmonkey** [comment]
Sure just make it {Password}{Enter}{Delay 500}exit{Enter}

**Comment by GithubABCDEFG** [comment]
Thanks a lot, Mr Droidmonkey, You are really helped me.
