### ISSUE TITLE
Create a New GUI

### ISSUE THREAD

**Issue by CerebralFreeze** [keepassxreboot/keepassxc#5554]
## Summary
I've been using KeePassXC daily for a long while and I actually love the new GUI vs the old GUI. It's 10x better. No, it's 100x better. The difference is night and day. Further, not only is it better, I genuinely love how it looks. YET, it still doesn't really compare to some of the best looking password managers that are out there like 1Password, Dashlane, SplashID 8, F-Secure, BitWarden, and Keeper.

I know that a design team must have put A LOT of time into the last iteration but is it possible to push for a new user interface that can hold a candle to the other password managers I just listed above?

## Examples
**Keeper**
![image](https://user-images.githubusercontent.com/24355773/96167093-e0b59780-0eec-11eb-923c-30c2f0613e71.png)

**Bitwarden**
![image](https://user-images.githubusercontent.com/24355773/96167276-270af680-0eed-11eb-8308-1c06e28ad756.png)
**F-Secure**
![image](https://user-images.githubusercontent.com/24355773/96167326-38540300-0eed-11eb-8368-0f302fc63416.png)
![image](https://user-images.githubusercontent.com/24355773/96167499-7d783500-0eed-11eb-8160-cbdc2861b69a.png)

**SplashID 8**
![image](https://user-images.githubusercontent.com/24355773/96167533-8d901480-0eed-11eb-944e-70c0b36251ed.png)
![image](https://user-images.githubusercontent.com/24355773/96167579-9da7f400-0eed-11eb-897a-bd67498bfcb7.png)

**Dashlane**
![image](https://user-images.githubusercontent.com/24355773/96167649-b912ff00-0eed-11eb-8003-38e11d310622.png)
![image](https://user-images.githubusercontent.com/24355773/96167677-c0d2a380-0eed-11eb-83aa-fa36335ff2aa.png)
![image](https://user-images.githubusercontent.com/24355773/96167698-c92ade80-0eed-11eb-88dc-ef5de8c039d4.png)
![image](https://user-images.githubusercontent.com/24355773/96167713-cd56fc00-0eed-11eb-8936-3354532d33e3.png)

**1Password**
![image](https://user-images.githubusercontent.com/24355773/96167916-0abb8980-0eee-11eb-87a4-c61eee860386.png)
![image](https://user-images.githubusercontent.com/24355773/96167923-0c854d00-0eee-11eb-9584-1062c7f7f400.png)
![image](https://user-images.githubusercontent.com/24355773/96167935-1018d400-0eee-11eb-8c7c-011910de087f.png)

## Context
You would think that aesthetics wouldn't really matter to a password manager but it really does. For example, when people are thinking about first choosing a password manager, do you think they are going to check out the password manager that looks ghetto? Even if it's the most powerful password manager, people are going to stay away from it so it doesn't stink up their computer monitor every time they need to look up a password. Don't you agree?

Is it possible to get a design team to start working on the next revision and use insights from other current password managers? You can even blatantly copy some of the nice touches that they use. Does it matter if it looks similar? If it looks awesome, people won't care.

I wouldn't recommend skins because I think that just brings down the brand equity of the product. Some people make some ugly skins and it wouldn't do justice to this program.

**Comment by CerebralFreeze** [comment]
This is extremely important improvement and should be listed as mission critical - moved to the top of the list. Everyone agree?

**Comment by phoerious** [comment]
Why are you creating a new issue?

**Comment by CerebralFreeze** [comment]
> Why are you creating a new issue?

I'm sorry.  I thought one was for the browser github and I made a new one for the regular KeePassXC.  I also included wonderful pictures.  Don't you think they are pretty?

**Comment by droidmonkey** [comment]
This request is frankly unhelpful. Highlight exactly what you do not like about our current UI or what exactly you do like about others and then we can maybe prioritize something.

**Comment by CerebralFreeze** [comment]
Droid,

I'm not criticizing your UI so please don't take it that way.  The current one looks like one from 2020.  The previous one looked like it was from 1980.

But, the ones that I just showed you are not about the UI.  It's about the GUI.  It's about the graphics.  The examples can win awards as the prettiest apps made today.  I don't know how to do that.  That's for professional designers.  Art majors who learn the definition of beauty in their 1st year of undergraduate art school.

Think of it this way.  I'm in real estate and I meet a lot of contractors and developers who think they have the best tastes.  They create product that they think are beautiful.  I recently purchased a building in which the developer installed extremely expensive marble tile for a commercial medical office.  Tens of thousands of dollars.  It was ugly as sin.  It was a pale red that was outlined with ugly brother doors and white trim.  Why was it ugly?  I do not know.  All I know is that my designer told me to dig it out.  I told her no because it was so expensive but I was just playing devil's advocate to see if she could do something with it.  She said she'd walk.  I gave in and she bought inexpensive ceramic tile that matched the doors, trim, windows, dressing...all on a color board that looked great.  The final product came out beautiful.  (I was man enough to admit that she was right.  I swallowed my pride.  She's also my long-term designer and sometimes there is no such thing as a client and an employer.  I need her more than she needs me.)  I'm sure you know the concept of what a sunk cost is.  1. Evaluate if you have the budget and 2. Evaluate if it is worth it to make a better product.  If it was worth it before and then it's worth it afterwards.  

Frankly, I hope the request now is helpful.

**Comment by xppcom** [comment]
Making KeePassXC heavy as hell by using electron or something wouldn't do anything good.

If you want KeePassXC to look ""modern"" just install a Qt theme and set your DPIs to 300

**Comment by phoerious** [comment]
Making Qt look modern is harder than you think. It's easier with QML, but QML isn't quite there yet and would require a rewrite of much of our interface logic.
