### ISSUE TITLE
Crash while typing password to open database file

### ISSUE THREAD

**Issue by harshit-j** [keepassxreboot/keepassxc#5555]
## Overview
Sometimes KeepassXC crashes while typing the password for a database. This issue happens 4-5 times in a month. This issue started since updating to v2.6.0

## Steps to Reproduce
1. Keep the database file in local folder synced with Dropbox
2. Keep Keepass opened for several days with enter password screen for the database file.
3. Sleep and resume macOS
4. Start typing password.

## Expected Behavior
1. The app should not crash

## Actual Behavior
1. The app crashes while typing the password.

## Context
[NOTE]: # ( Give us any additional information you may have. )
It is difficult to reproduce and happens intermittently. I have attached the crash log:
[KeepassXC CrashLog.txt](https://github.com/keepassxreboot/keepassxc/files/5389539/KeepassXC.CrashLog.txt)

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.1
Revision: 9a35bba

Qt 5.15.0
Debugging mode is disabled.

Operating system: macOS Mojave (10.14)
CPU architecture: x86_64
Kernel: darwin 18.7.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
 libgcrypt 1.8.5

**Comment by droidmonkey** [comment]
Do you press caps lock at all?

**Comment by droidmonkey** [comment]
Just looked at your crash log that's the problem. Fixed in #5545
