### ISSUE TITLE
add custom field

### ISSUE THREAD

**Issue by ihubgit** [keepassxreboot/keepassxc#5556]
Hi, is there a way to add a custom field ?
Thing is I have cases where I need to put in _two_ passwords for a given site and not just one.
By default your app only has a single field for the password...

**Comment by droidmonkey** [comment]
Advanced attribute or use notes.

**Comment by ihubgit** [comment]
yea, but using advanced attribute by default shows a generated password in plaintext. Sure, I can protect it, but then I don't have an immediate access to it anymore, and have to double click again in order to reveal it. That's not very intuitive at all...
And yes, notes does better but then copying the password in the pasteboard thru the icon in the menu only allows me to paste the first password, not the one I copied in notes.
It would seem so much more intuitive and user-friendly to me to simply allow adding a custom field f.ex. for a second password that can also be pasted in the pasteboard... That can't be too hard to do ?

**Comment by droidmonkey** [comment]
Templates for entries is planned for the next major release

**Comment by ihubgit** [comment]
Oh great, that seems like such an obvious feature really. Can you give me an approximate ETA for that release? Please allow for having the copy icon copy-paste the "active" password (the one that is selected). Looking forward to it !
Without making a new entry, would it be possible to have a 3 pane layout (i.e. the details of an entry at the right hand side of the pane and not underneath)? That'd be a nice add-on too...

**Comment by droidmonkey** [comment]
We have requests tracking all of those things, thank you!

**Comment by ihubgit** [comment]
Great ! Appreciated. So what would ETA be for next major release ?

**Comment by droidmonkey** [comment]
We dont operate like that. Its released when its ready and we are satisfied.
