### ISSUE TITLE
Keepassxc Snap package does not start on Ubuntu 20.10 (Groovy) Wayland

### ISSUE THREAD

**Issue by sharifm-informatica** [keepassxreboot/keepassxc#5557]
## Overview
Snap package does not run on Ubuntu 20.10 Groovy when using Wayland. Works fine using Xorg.

## Steps to Reproduce
1. Run snap package KeepassXC on ubuntu 20.10 wayland mode

## Expected Behavior
Application starts

## Actual Behavior
Brief icon flashing in task area then disappears. Behaviour similar to app crashing or quietly exiting.

## Context
Happened after upgrading from Ubuntu 20.04 to Ubuntu 20.10
May be related to #5488 

KeePassXC - 2.6.1 snap package
Revision: Tested both *stable* and *edge* snap packages

Operating System: Linux
Desktop Env: Gnome
Windowing System: Wayland

**Comment by sozonnyk** [comment]
Same story on KDE Neon 5.19 (Ubuntu Focal 20.04)
KeepassXC 2.6.2. snap package
`$ /snap/bin/keepassxc
Gtk-Message: 18:04:17.326: Failed to load module "colorreload-gtk-module"
Fontconfig warning: FcPattern object weight does not accept value [0 210)
Segmentation fault`

**Comment by droidmonkey** [comment]
So much for snaps being portable

**Comment by sharifm-informatica** [comment]
It is not a bug in KeepassXC it is a bug in Ubuntu groovy [Graphical snaps can't run in Gnome 3.38 Wayland sessions can't open X display](https://bugs.launchpad.net/ubuntu/+source/snapd/+bug/1897224)
Closing

**Comment by droidmonkey** [comment]
Yay!

**Comment by WayneNani** [comment]
> Same story on KDE Neon 5.19 (Ubuntu Focal 20.04)
> KeepassXC 2.6.2. snap package
> `$ /snap/bin/keepassxc Gtk-Message: 18:04:17.326: Failed to load module "colorreload-gtk-module" Fontconfig warning: FcPattern object weight does not accept value [0 210) Segmentation fault`

I get a very similar issue when launching the KeePassXC Snap on Fedora 33 even when I'm using Xorg (the same when using Wayland):
```
WARNING: cgroup v2 is not fully supported yet, proceeding with partial confinement  
Gtk-Message: 11:10:58.689: Failed to load module "canberra-gtk-module"  
Gtk-Message: 11:10:58.689: Failed to load module "pk-gtk-module"  
Gtk-Message: 11:10:58.691: Failed to load module "canberra-gtk-module"  
Gtk-Message: 11:10:58.691: Failed to load module "pk-gtk-module"  
Qt: Session management error: None of the authentication protocols specified are supported  
Fontconfig warning: FcPattern object weight does not accept value [0 205)  
Speicherzugriffsfehler
```
