### ISSUE TITLE
KeePassXC-Browser has encountered an error:  Key exchange was not successful. 

### ISSUE THREAD

**Issue by n-u-k-e** [keepassxreboot/keepassxc#5558]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
Just got a new laptop with Ubuntu 20.04.1 LTS. After installing all updates first thing I did was install keepassxc with snap. I then saved the browser helper script to my documents and ran the script. After doing all the necessary steps to get browser integration working with Firefox i get this error; 

KeePassXC-Browser has encountered an error:

Key exchange was not successful. 

Not sure what else I need to do to get this to work.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Open keepassxc database
2. Open firefox
3. Reload keepassxc-browser extension

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.1
Revision: 9a35bba
Distribution: Snap

Qt 5.9.5
Debugging mode is disabled.

Operating system: Ubuntu Core 18
CPU architecture: x86_64
Kernel: linux 5.6.0-1031-oem

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.1

**Comment by droidmonkey** [comment]
Is Firefox installed as a snap?
