### ISSUE TITLE
Onlykey - hardware key stopped working in latest stable 2.6.1 release

### ISSUE THREAD

**Issue by nkichukov** [keepassxreboot/keepassxc#5561]
## Overview
What has been implemented and worked flawlessly under 2.6.0, see: https://github.com/keepassxreboot/keepassxc/issues/4400, has stopped working in 2.6.1.

The two onlykey hardware slots show up in the drop-down list for hardware tokens, but selecting a slot and trying to unlock a database does not make onlykey wait for keypress to issue the secret.

Downgrading to 2.6.0 fixes the problem, so this is a regression.

## Steps to Reproduce
1. Install latest stable 2.6.1
2. Try to unlock a database that has additional hardware key setup
3. See how onlykey does not blink in blue accepting user to touch any button so the hardware key can be input

## Expected Behavior
The database would open, the same way it does in 2.6.0.

## Actual Behavior
Database does not open as onlykey is not placed into the right mode to input the hardware key.

## Context
Stable version upgrade.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.6.1
Revision: (already downgraded, so I could not collect this)

[NOTE]: # ( Pick choices based on your environment )
Operating System: GNU/Linux
Desktop Env: XFCE
Windowing System: X11

**Comment by nkichukov** [comment]
Perhaps related to: https://github.com/keepassxreboot/keepassxc/pull/5004/commits/6de3459d0d7a723f6c00a00c07809357d8ad1e57

I will revert this patch on 2.6.1 and see if it fixes it.

**Comment by droidmonkey** [comment]
Not possible, that corrects a legit bug typo

**Comment by nkichukov** [comment]
Yes, but looking at what's changed between the two, this is the only relevant explanation:
https://github.com/keepassxreboot/keepassxc/compare/2.6.0...2.6.1

**Comment by nkichukov** [comment]
I've just recompiled it and it worked fine this time. It might have been some temporary failure before, when I first saw this.
