### ISSUE TITLE
start multiple databases with seperate keyfiles with one keepassxc command 

### ISSUE THREAD

**Issue by tuxcrafter** [keepassxreboot/keepassxc#5563]
steps 1: create databases:
keepassxc-cli db-create database04.kdbx --set-key-file database04.key
keepassxc-cli db-create database05.kdbx --set-key-file database05.key
keepassxc-cli db-create database06.kdbx --set-key-file database06.key

step 2: start databases with keyfile:
keepassxc database04.kdbx --keyfile database04.key database05.kdbx --keyfile database05.key database06.kdbx --keyfile database06.key

I tried a workaround with a forced single instance, but this does not work, as the other databases do not open the keyfile.
keepassxc database04.kdbx --keyfile database04.key &
sleep 1;
keepassxc database05.kdbx --keyfile database05.key &
sleep 1;
keepassxc database06.kdbx --keyfile database06.key &
sleep 1;

step 3:
Please add feature and make an array of the given --keyfile options and an array of the given databases and match the arrays and open databases with the keyfiles, and allow opening with empty password.

step 4:
There is also an other way and that is to have an option like --add or --expand or --background to the keepassxc command and then add the current options, but then just open the database to the already running instance, so it is always clear what password or keyfile will go with the database, just don't start new instances of keepassxc and just load the database in the gui.
keepassxc database04.kdbx --keyfile database04.key --background
keepassxc database05.kdbx --keyfile database05.key --background
keepassxc database06.kdbx --keyfile database06.key --background

**Comment by droidmonkey** [comment]
duplicate request
