### ISSUE TITLE
KeepassXC: Autotype Window Title never matches

### ISSUE THREAD

**Issue by shanebowmore** [keepassxreboot/keepassxc#5564]
## Overview
I am using AutoType quite a lot. I really would like to use the "Windows Associations" feature but it never starts the ticked "use a specific sequence for this association".

## Steps to Reproduce
My example is based on a simple batch script that shall be started on a command prompt window.
1. In the AutoType Section I "Enable AutoType for this entry.
2. In the Window title I select "Command Prompt"
3. I tick "use a specefic..." and enter `connect_drives.bat {USERNAME} "{PASSWORD}"{ENTER}"`
4. save the entry and close the edit mode.
5. click "Command Prompt" Window
6. go back to KeepassXC and right click "Perform AutoType" on the entry where I entered the settings above.

## Expected Behavior
Result should be: Within the Command Prompt (cmd.exe) the following line should be entered `connect_drives.bat {USERNAME} "{PASSWORD}"{ENTER}"`
with the replaced username and password :-D

## Actual Behavior
Result: KeepassXC always enters {{USERNAME}{TAB}{PASSWORD}{ENTER}

## Context
I use the same settings with Keepass and it works.
On Linux KeepassXC behaves the same way. 

I tried to change the general "AutoType" Settings No matter what I change the result is the same. 
I read the instructions on RegEx regarding AutoType and tried to use the regex features, which did not change anything. 
It "feels" that the windows association is simple not found or executed - but that is just wild guessing. 

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.1
Revision: 9a35bba

Qt 5.15.0
Debugging mode is disabled.

Operating system: Windows 10 Version 1909
CPU architecture: x86_64
Kernel: winnt 10.0.18363

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.5

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows/Linux
Desktop Env: KDE
Windowing System: X11

**Thanks!** I hope that I haven't overseen some tick field or anything simple as that. I have seen a similar question but did not see a solution.

**Comment by droidmonkey** [comment]
Window association is only for global auto type.  Change the sequence at the top of the autotype settings for the entry level auto type.

**Comment by shanebowmore** [comment]
That leaves me somewhat puzzled. 
If I change the setting in "Use Custom AutoType sequence" - which I tried a well, it uses the sequence for all windows. 
My use case is somewhat different. I store Windows credentials once and use it for different purposes:
1. Connect shares.
2. Use it for Remote Desktop to start or Web Sites (Where is need the standard procedure with tab and enter.
3. Use it for Remote Desktop to unlock (Just the password)

If I do get you right I have to change the setting for my three use cases. Why does Keepass then behave different from KeepassXC. 
Am I on the wrong track?

**Comment by droidmonkey** [comment]
You need to define both in your case.

**Comment by droidmonkey** [comment]
What you're looking for is requested in #2490

**Comment by shanebowmore** [comment]
Oh. Ok.

I am sorry. Then I was on the wrong track.

**Comment by shanebowmore** [comment]
@droidmonkey 
I am sorry, to be annoying, regarding this subject. 
Maybe I do not understand the help page correctly. It states:

> (Optional) Define a custom auto-type sequence for each window title match by selecting the Use **specific sequence for this association** checkbox. Sequence action codes and field placeholders are detailed in the following table. A complete list of supported actions and placeholders can be found at KeePass Auto-Type Action Codes and KeePass Placeholders. Action codes and placeholders are not case sensitive.

[KeepassXC Help --> AutoType](https://keepassxc.org/docs/KeePassXC_UserGuide.html#_configure_auto_type_sequences)

What I read in the description for the change request of [#2490](https://github.com/keepassxreboot/keepassxc/issues/2490) reads very similar. I really can't see the difference..-- 

Is the help just wrong? From my humble point of view, the configuration I can make suggest that I can modify the "AutoType" depending on the window title. I do not understand how I can use the field "Use a specific sequence for this association" in a different context.  

Do you know some other description, where I can read how those configuration can be used? I just want to understand!
Thanks!

**Comment by droidmonkey** [comment]
Global Auto type: uses the global hotkey and attempts to find entries that match the window title of the current window. You can define custom sequences for each window.

Entry-level Auto-Type: uses the default sequence to Auto-Type into the previously focused window.

The feature request is to add window title matching to entry level Auto-Type.
