### ISSUE TITLE
Vertical Line on top of GUI, in Add/Edit Entry Dialog

### ISSUE THREAD

**Issue by apocalyptech** [keepassxreboot/keepassxc#5567]
## Overview

I'm using KeePassXC 2.6.1 on Arch Linux, linked against Qt 5.15.1.  On the Add/Edit Entry dialog, I've got a strange vertical line which runs through the fields.  Here's a screenshot:

![screenshot-2020-10-18-11_00_44](https://user-images.githubusercontent.com/443343/96373379-b3a5f680-1131-11eb-912c-9a4d560e59a8.png)

The line goes away as I resize the window, but reappears as soon as I release the mouse button to stop the resizing.  It doesn't actually interfere with functionality at all, but it's fairly annoying:

![screenshot-2020-10-18-11_05_20](https://user-images.githubusercontent.com/443343/96373403-d59f7900-1131-11eb-9f2d-f013d4976667.png)

## Steps to Reproduce
1. Add or Edit an entry

## Expected Behavior
No weird vertical line

## Actual Behavior
Weird vertical line

## Context
Just the usual add/edit entry dialog

KeePassXC - Version 2.6.1
Revision: 9a35bba

Qt 5.15.1
Debugging mode is disabled.

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 5.8.10-arch1-1

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.6

Operating System: Linux
Desktop Env: IceWM
Windowing System: X11

**Comment by droidmonkey** [comment]
already fixed

**Comment by apocalyptech** [comment]
Ah, okay, so I see.  Thanks!  I'd searched for duplicates first but clearly didn't find the first bugreport for that.  Cheers!
