### ISSUE TITLE
delete password generator icon in password field in entry

### ISSUE THREAD

**Issue by ihubgit** [keepassxreboot/keepassxc#5569]
Hi, 
I found it a bit dangerous of having the password generator sitting just next to the password activator in the password field of an entry. One might actually just visualize the password and accidentally hitting the button next to it, thus inadvertently creating a new password !
The password generator icon already being available in the menu, this could suffice and would reduce the risk of accidentally erasing/changing the current password.

**Comment by droidmonkey** [comment]
The password is not changed unless you press accept in the generator dialog. Additionally you can just cancel editing the entry to not save a change.
