### ISSUE TITLE
activating notes for one entry keeps it in memory for all other entries

### ISSUE THREAD

**Issue by ihubgit** [keepassxreboot/keepassxc#5571]
Hi, 
when checking the box to reveal the notes section for one given entry, it automatically duplicates a notes section for the other entries (for which I didn't check the box) displaying hidden content, thus making believe there is actual content, even though this is not the case. Clicking upon the notes entry makes the hidden text disappear.
When visualizing the notes content of a 'note entry', then clicking upon another 'noteless' entry, the text of the 'note entry' is displayed at the latter...

**Comment by droidmonkey** [comment]
This occurs in the entry preview panel. Good find!
