### ISSUE TITLE
Keepassxc 2.6.1 conflicts with Screenshot applications (Image GIF) on Linux Distros.

### ISSUE THREAD

**Issue by serial02** [keepassxreboot/keepassxc#5572]
Hello Keepassxc Team

In the Linux Distros Deepin V20 and Ubuntu 20.04 LTS when trying to record gif image of the browsers' screen to report some specific bugs there were some problems, as follows:

In Ubuntu 20.04 lts when recording the gif with the deepin screen recorder, at the end of the screen the screen goes back to the start of ubuntu and then returns to the standard screen and does not allow generating the image in gif.

In Deepin V20 the screen literally hangs and does not let you finish recording the GIF image using the Deepin standard screen recorder, being necessary to turn off the button and start the machine again.

Note: I think it's good and normal that Keepassxc does not allow you to generate an image of the application in operation, but it cannot block gif images from other applications. Was this a conflict?

We can only generate GIF images with the screen recorder, if keepassxc has not been initialized and opened by the master password.

If it is necessary to generate some images for further clarification I am available.

Here is my configuration data:

OS: Deepin 20 x86_64
Kernel: 5.9.1-amd64-desktop
Uptime: 20 mins
Packages: 2036 (dpkg), 13 (flatpak)
Shell: bash 5.0.3
Resolution: 1920x1080
FROM: Deepin
WM: KWin
WM Theme: light / deepin
Theme: deepin [GTK2 / 3]
Icons: bloom [GTK2 / 3]
Terminal: deepin-terminal
Terminal Font: Noto Mono 11
CPU: Intel i3 540 (4) @ 3.067GHz
GPU: Intel Core Processor
Memory: 967MiB / 7698MiB

Serial

**Comment by phoerious** [comment]
We are not doing anything about screenshots. All we do is prevent direkt access to KeePassXC's memory.

**Comment by droidmonkey** [comment]
How are you certain that this is the fault of keepassxc? Its certainly not something we have any involvement in or intentional disruption of.

**Comment by serial02** [comment]
> How are you certain that this is the fault of keepassxc? Its certainly not something we have any involvement in or intentional disruption of.

The two times that I tried to record GIF image they had the keepassxc open in two different linux distros. After closing keepassxc the images could be recorded normally. I'll see if I can prepare some images with a cell phone and send them later.

**Comment by phoerious** [comment]
I can totally take screenshots of KeePassXC. How do you think we created the ones we have on our website?

**Comment by serial02** [comment]
> I can totally take screenshots of KeePassXC. How do you think we created the ones we have on our website?

I have no doubts whatsoever about the efficiency of Keepassxc.
In tests performed here yesterday trying to reproduce the problem did not occur again.
What happened this morning was the firefox browser crashing, where it could be the possible cause of it all
I believe that we can close this open post and if I have any other problems related to Keepassxc, we will talk again. Thank you!
