### ISSUE TITLE
Used Password Audit and Change Log (with logged in Username) 

### ISSUE THREAD

**Issue by degus2019** [keepassxreboot/keepassxc#5573]
## Summary
In the case of shared keepass containers, several people use the same entry, unfortunately only changes to one entry can be tracked, not who has used or changed the password, whether intended or not 

## Examples
user1, user2 and user3 use the same shared container, user1 changes / copies / makes nonsense with a key or uses the access to cause damage
To avoid repetition, user2 needs to know where the cause is
Who has accessed the key should be in the history (view,edit,delete with (os?) logged in username

## Context
i want to track which user has accesed a specific key in container

**Comment by droidmonkey** [comment]
This would only be marginally useful and easily defeated. This is not part of the KDBX standard so would have to be implemented as an advanced attribute or custom data. Using any other program (even mobile apps) besides KPXC would result in no logging of the username. Additionally, users could download the file, edit it elsewhere, and upload again.

KeePassXC and KeePass in general is not design for multi-user environments where auditing and control is required. You will probably need a different product if you need those features.
