### ISSUE TITLE
Explain KeeShare protocol in Docs

### ISSUE THREAD

**Issue by faximilie** [keepassxreboot/keepassxc#5574]
## Summary
Please provide documentation on how KeeShare works, it seems rather complex and undocumented at the moment. Technical details are almost non-existent. Thus not much can be determined about it without diving into the source, which isn't efficient.

## Context
Currently I cannot find any documentation regarding KeeShare, on the developer side at least. I plan on working on a keepass2android plugin to hopefully work with KeeShare files.

To ensure this is implemented correctly and securely, I'll need to know how all the crypto works.

**Comment by faximilie** [comment]
I've dug a little into the file itself, and will post my findings here.

It seems the keeshare file is just a zip containing two files.

A `*.share.signature` and `*.share.kdbx`

The signature is just an XML containing the certificates involved with sharing, and an RSA key that I am unsure the purpose at the moment

The second file, is just a regular keepass database, and can be unlocked regularly.


If anyone can shed any light regarding the RSA key in the signature file, and the crypto process I can get to work writing the documentation around this.

**Comment by droidmonkey** [comment]
The XML file contains the signed hash of the kdbx file. This ensures integrity and verifies the last person who saved the share. Signed keeshare is an optional feature, we also support straight kdbx files without signing.

**Comment by droidmonkey** [comment]
https://keepassxc.org/docs/KeePassXC_UserGuide.html#_database_sharing_with_keeshare
