### ISSUE TITLE
Hide key file path

### ISSUE THREAD

**Issue by Philippe734** [keepassxreboot/keepassxc#5576]
## Summary
For security reason, could you hide by default the key file path.

**Screenshot current release:**

![nothiddenn](https://user-images.githubusercontent.com/24923693/96573858-fe10aa00-12ce-11eb-90e4-2bc98c913a4f.png)

**Screenshot of the feature desired:**

![2](https://user-images.githubusercontent.com/24923693/96574330-9b6bde00-12cf-11eb-9d89-abfb6c4599a2.png)

**Comment by droidmonkey** [comment]
Not a bad idea

**Comment by Philippe734** [comment]
Wonderful! Thanks!
