### ISSUE TITLE
How to batch edit keepassxc db entries?

### ISSUE THREAD

**Issue by slartibart70** [keepassxreboot/keepassxc#5577]
Due to some strange password policies, i am forced to regularly update entries of keepass database.
Right now, i use a loop like so in an expect script:

```
set entries(0) "/aaa/entry1"
set entries(1) "/aaa/entry2"
...
set entries(9) "/aaa/entry10"

foreach index [array names entries ] {
  puts "modifying entries($index): $entries($index)"

  spawn keepassxc-cli edit -p $databaseFile "$entries($index)"
  expect -re "Insert password to unlock.*:"
  send "$keepassPwd\r"
  expect -re "Enter new password for entry:"
  send "$entryPwd\r"
  expect eof
}
```

This works, but is slow as hell
Is there an alternative i could use to define a batch of entries that all need to get modified at once? (here, all with the same password, for example. I could think of other uses as well)

any help is appreciated

**Comment by droidmonkey** [comment]
Use `keepassxc-cli open` command and pass a series of stdin commands.

**Comment by slartibart70** [comment]
nice! 
Thanks
