### ISSUE TITLE
Add support for Edge Browser on Linux

### ISSUE THREAD

**Issue by serial02** [keepassxreboot/keepassxc#5578]
Hello Keepassxc Team

I installed the Edge Browser for Linux and downloaded the Keepassxc extension from (https://microsoftedge.microsoft.com/addons/Microsoft-Edge-Extensions-Home?hl=en) and also from (https://chrome.google.com/webstore/detail/keepassxc-browser/oboonakemofpalcgghocfoadofidjkkk/related) where both are unable to connect the Keepassxc 2.6.1 application, being used one at a time.

Does the Keepassxc option not enable on Integration (Edge) and does not connect with the Edge Browser for Linux? Both extensions have been tested.

Following images:

![Screen Capture_keepassxc_20201020164212](https://user-images.githubusercontent.com/32621790/96638659-ddf4e100-12f6-11eb-8312-9cc538354cfd.gif)

![Screen Capture_microsoft-edge-dev_20201020165721](https://user-images.githubusercontent.com/32621790/96638673-e4835880-12f6-11eb-91a9-37947373c7d0.gif)

**Comment by droidmonkey** [comment]
Use the custom browser feature on the browser settings advanced tab for now. We don't have built-in support for edge on linux.

**Comment by varjolintu** [comment]
@droidmonkey Enabling the support for Linux would be a quick job. Too late for 2.6.2?

**Comment by droidmonkey** [comment]
Yah wait till stable

**Comment by MightyPork** [comment]
in case it helps someone in the future:

![Screenshot_20210104_184500](https://user-images.githubusercontent.com/2041118/103563411-02effd80-4ebd-11eb-83cf-dca2378e1495.png)

the path is something like `~/.config/microsoft-edge-dev/NativeMessagingHosts` and it seems to work great (it's just restyled chrome, after all)

**Comment by F3000** [comment]
@MightyPork  I have typed in your path.

But it diese the work . 

How does your general tab in the settings looks like ?

**Comment by MightyPork** [comment]
I checked all that could be checked, but I don't think these actually matter for the custom configuration.

![Screenshot_20210107_205436](https://user-images.githubusercontent.com/2041118/103938610-cfb2a600-512a-11eb-8d70-bb95cbaa8103.png)

Double check the path and that you connected the extension to keepassxc correctly, I have no other ideas. Works fine here

**Comment by serial02** [comment]
> @MightyPork I have typed in your path.
> 
> But it diese the work .
> 
> How does your general tab in the settings looks like ?

Here it works well too.

If you installed keepassxc 1.7.4 from microsoft-egde extensions it DOES NOT work. You need to install keepassxc 1.7.4 from the Chrome Web Store.

**Comment by F3000** [comment]
Thanks . Yes I have taken the MS version 😀

**Comment by hilam** [comment]
I installed keepassxc 1.7.4 from the Chrome Web Store ((https://chrome.google.com/webstore/detail/keepassxc-browser/oboonakemofpalcgghocfoadofidjkkk/related) and edited the `keepassxc-snap-helper.sh` (https://raw.githubusercontent.com/keepassxreboot/keepassxc/master/utils/keepassxc-snap-helper.sh), to include a clone from any CHROME based setup:

```
setupEdge() {
    JSON_OUT=${JSON_CHROME}
    INSTALL_DIR="${BASE_DIR}/.config/microsoft-edge-dev/NativeMessagingHosts"
}
```

After, add the new option in the script menu, run, and voilà. Just fine!

**Comment by rogercreagh** [comment]
Using the 1.7.8.1 Chrome keepassxc-browser extension as per @MightyPork above doesn't seem to work even after restarting both browser and keepassxc itself. 

Using latest Edge Beta Version 91.0.864.27 (Official build) beta (64-bit)
 `~/.config/microsoft-edge-dev/NativeMessagingHosts` doesn't actually exist, but
`~/.config/microsoft-edge-beta/NativeMessagingHosts` does, however that doesn't work either as the custom location.
Clicking reload still gives "Key exchange not successful"

@hilam where do you find that file to edit once Keepassxc and the extension are installed. Plus I see that you are using `.../microsoft-edge-dev/...` in the path - presumably this should now be `.../microsoft-edge-beta...`?

Anyone got a working config with KeePassXC 2.6.4 and chrome keepassxc-browser 1.7.8.1 ?

**Comment by jValdron** [comment]
I have it working with:
* Edge 91.0.864.19
* keepassxc-browser 1.7.8 (from the Edge extensions store, not Chrome)
* KeePassXC 2.6.4

With the following config location: `/home/jason/.config/microsoft-edge-beta/NativeMessagingHosts`. From what I can tell, `~` does not expand to your home directory, so use an absolute path.

**Comment by rogercreagh** [comment]
Thanks @jValdron THAT'S IT
If you use the `~/` format it KeePassXC actually creates a directory called `/home/username/~/.config/microsoft-edge-beta/NativeMessagingHosts` but then doesn't use it.

The hint given in the empty dialogue box is 
`~/.custom/config/Mozilla/NativeMessagingHosts`
which if you use it as 
`~/.custom/config/microsoft-edge-beta/NativeMessagingHosts`
also simply creates a directory in your user home directory without expanding the `~`

So I think there may be two related bugs here - the password hint is wrong, and it should be parsing `~/.` correctly. In addition the drop-down that offers you a choice of Firefox/Chromium doesn't appear to do anything.
I'll open a separate issue for these.

**Comment by ssh10** [comment]
> I have it working with:
> 
> * Edge 91.0.864.19
> * keepassxc-browser 1.7.8 (from the Edge extensions store, not Chrome)
> * KeePassXC 2.6.4
> 
> With the following config location: `/home/jason/.config/microsoft-edge-beta/NativeMessagingHosts`. From my very limited testing, `~` does not expand to your home directory, so use an absolute path.

Thank you @jValdron

**Comment by carestad** [comment]
Now that Edge was finally [released in a stable version for linux](https://www.omgubuntu.co.uk/2021/10/microsoft-edge-for-linux-now-stable), maybe we could enable the option in the GUI? :grinning:

**Comment by varjolintu** [comment]
> Now that Edge was finally [released in a stable version for linux](https://www.omgubuntu.co.uk/2021/10/microsoft-edge-for-linux-now-stable), maybe we could enable the option in the GUI? 😀

Done :)
