### ISSUE TITLE
KeepassXC Generate Password tool does not respect the "Do not include" character list.

### ISSUE THREAD

**Issue by aetercrow** [keepassxreboot/keepassxc#5579]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

KeepassXC Generate Password function does not respect the "Do not include" list.

![keepass_bug](https://user-images.githubusercontent.com/2213968/96647036-e4c52900-12e1-11eb-8918-73a19321ede6.png)

Example: I have set the following characters {within the quotes) in the do not include list: "`<>"

Keepass remembers this (cool) but does not respect the list when I try to generate new passwords. Instead, I have to delete the characters and type them again which will then generate a password free of those characters. I have attached a screenshot showing the result of a new password generation attempt that has characters that are supposed to be excluded.

Please note: the characters I want to exclude are in two of the "Character Types" groupings in the password generator. I don't want to exclude whole groups to avoid single characters from those groups.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Click on password generation tool
2. Choose groups of character types to include
3. Enter discrete characters from 1 or more types into the "Do not include:" list.
4. Apply password
5. Open the tool again to generate a new password. Do not include list should be populated by your prior choices.
6. Make password visible

At this point the password will probably have a character you've asked it to exclude, but if it does not, a few refreshes will certainly generate a password that does. It only fixes itself after you delete the list and enter it again.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
When I click on the password generation tool, it should open and present a password based on the selections that are visible/defined. If there is a list of characters not to include in the box, the generator should not include them, on first run, and on refresh.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Password generator creates password that do not respect the stored "Do not include" list.

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.1
Revision: 9a35bba

Qt 5.15.0
Debugging mode is disabled.

Operating system: macOS 10.15
CPU architecture: x86_64
Kernel: darwin 19.6.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
 libgcrypt 1.8.5

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS

**Comment by droidmonkey** [comment]
Fixed in 2.6.2
