### ISSUE TITLE
[Feature] Access/read the notes quickly

### ISSUE THREAD

**Issue by silverkorn** [keepassxreboot/keepassxc#558]
Sometimes, it's a bit complicated or confusing to recognized what the group or entry is and it's not efficient nor natural to right-click the group/entry and go to "Modify" simply to get the notes information.

## Expected Behavior
Have a simple way to get the notes from the a group/entry.

## Current Behavior
Need to right-click then modify the group/entry to read the notes.

## Possible Solution
Show a tooltip text containing the "Notes" when hovering on a group or entry.
Can be checked in the parameters if desired to avoid this behaviour.

Thanks!

**Comment by C0rn3j** [comment]
Maybe it wouldn't work for your use case, but for my use case:

The search actually searches through notes too, so CTRL+F and typing what you need may work for you.

**Comment by HifeFish** [comment]
I second this request. Accessing notes has become a hassle. So much so that I sometimes create a secondary entry with the note in the username field.

At least for entries, maybe there could be an optional column to display notes. This obviously still doesn't cover more extensive notes, though.

**Comment by TheZ3ro** [comment]
What about #454 ?
Inserting a preview panel on the bottom that will show some info on the selected entry (without opening it)

**Comment by HifeFish** [comment]
@TheZ3ro Indeed the old preview panel worked great for my purposes. Especially since it doesn't require using the mouse. 

However, @silverkorn was also addressing group notes, which would not be visible there, so that would be a separate issue still.

**Comment by TheZ3ro** [comment]
We can add a preview panel for groups as well

**Comment by HifeFish** [comment]
Sounds perfect (as far as I'm concerned).

**Comment by droidmonkey** [comment]
I love the idea of a preview panel.

**Comment by paulsommer** [comment]
I too love the idea of a preview panel. Keepass has this feature and and Keepassx 0.43 used to have it, too. I just changed to KeepassXC in the hope that this feature would have been re-engaged here.
With this preview pane one can just go through the entries (e.g. with cursor down) and browse all the comments very fast.
Maybe you can borrow this feature from the 0.43 code?

**Comment by adrienbresson** [comment]
+1

**Comment by TheZ3ro** [comment]
Solved in #879

**Comment by networkproblemsolver** [comment]
I would like to suggest having the NOTES show immediately in the bottom-right pane, like this:
![KeyPassXC-Notes](https://user-images.githubusercontent.com/7603955/57259228-289e8100-70a2-11e9-8e73-a4da28286982.jpg)

**Comment by droidmonkey** [comment]
There is an issue to implement that.
