### ISSUE TITLE
KeePassXC dark theme on macOS - toolbar buttons and text not visible

### ISSUE THREAD

**Issue by sybercorp** [keepassxreboot/keepassxc#5580]
## Overview
On macOS, KeePassXC's toolbar buttons and text are nearly invisible unless you hover your mouse over them when operating in Dark Mode.  In light mode, everything is correct.

## Steps to Reproduce
1. Set macOS to dark mode
2. Open KeePassXC and set it to dark mode or to match the system mode
3. Look at the KeePassXC toolbar

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
The toolbar should change colors to account for the system theme or app theme

## Actual Behavior
The toobar button colors do not change to a color proper for dark mode viewing

## Context
[NOTE]: # ( Give us any additional information you may have. )
Screenshot 1: https://imgur.com/a/AQRbMa7
Screenshot 2: https://imgur.com/a/OiODsmC

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.1
Revision: 9a35bba

Qt 5.15.0
Debugging mode is disabled.

Operating system: macOS 10.15
CPU architecture: x86_64
Kernel: darwin 19.6.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
 libgcrypt 1.8.5

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS

**Comment by droidmonkey** [comment]
Fixed in 2.6.2

**Comment by sybercorp** [comment]
> Fixed in 2.6.2 

When is 2.6.2 going to be released?

**Comment by phoerious** [comment]
Soon.
