### ISSUE TITLE
Copying database entries causes data loss

### ISSUE THREAD

**Issue by DanPMK** [keepassxreboot/keepassxc#5583]
## Overview
If you have a database and a copy of that database and edit an entry that exists in both, so that they're "forked", and then copy the entries back to a single database, one of the forks and its history will be **silently deleted**. I accidentally stumbled upon this bug, and after updating to KeepassXC 2.6.1, still had the bug and was able to reproduce it.

## Steps to Reproduce
Step 1: Create a new database, named mine Testing.kbdx, used password 12345.
Step 2: Create a new entry (Entry 1) in the root folder, and leave "First" as a note in it.
Step 3: Copy the database (Testing - Copy.kdbx) and open the copy as well.
Step 4: In the copy, create a new entry (Entry 2), and leave "Two" as a note in it. Then, edit Entry 1 and change the note to "Edited".
Step 5: In the original database, change Entry 1's note to "Second".
Step 6: With both databases open, select and drag both entries from the copy to the original Testing.kbdx. Testing.kbdx will now have 3 entries visible (Entry 1 - Second, Entry 1 - Edited, Entry 2 - Two), while Testing - Copy.kdbx should have none. Save and close both.
Step 7: Re-open Testing.kbdx and see that the entry with "Second" as a note is now gone, not even saved in the history!
Step 8: Extract both databases to XML to confirm that the entries with "Edited" and "Two" are still there, but the one with "Second" is completely gone!

## Expected Behavior
I expect the entries to coexist and nothing gets deleted or lost, especially when it is a more recent edit and they are visible in the UI until you close it.

## Actual Behavior
An entry is lost without warning.

## Context
The act of copying seems to be considered the most recent edit, and takes precedence; in my reproduced example above, even though editing Entry 1 to "Second" in the first happened _after_ I edited it to "Edited" in the second database, the "Second" entry was lost. It may be due to sharing a UUID, perhaps those should be refreshed when a duplicate is detected, or in general when moving from one database to another, but that's my blind guess.

KeePassXC - Version 2.6.1
Revision: 9a35bba
Operating System: Windows (used Linux to extract the XML)

**Comment by droidmonkey** [comment]
Fixed in 2.6.2
