### ISSUE TITLE
Display the currently signed in database

### ISSUE THREAD

**Issue by rrgmitchell** [keepassxreboot/keepassxc#5585]
Kind of trivial, but something that has always bothered me.  I have more than one KeePass database and need to switch between them from time to time.  When I switch focus to my KeePass window, I would like to be able to see the name of the database I am looking at.  As far as I can see there is no way of knowing this.  I resort to 'Open Recent' to see which is the most recent. 

It would be nice to see the database name in the window title, for example.

**Comment by droidmonkey** [comment]
Go to database settings and change the name of your database
