### ISSUE TITLE
Unable to move generate password modal window 

### ISSUE THREAD

**Issue by ba32107** [keepassxreboot/keepassxc#5588]
## Current Behavior

While editing an entry (or creating a new one), I open the password generation window, which is a smaller, modal window. When opened, I am unable to move just this window around by dragging the title bar. The modal window moves together with the main window and blocks the view of the entry's details.

## Expected Behavior

I should be able to move the modal password generation window independently from the main one. This would allow me to see the entry's details without having to close the generation dialog.

## Steps to Reproduce (for bugs)

 1. Click "Add a new entry" in the toolbar
 1. In the Password field, click the dice icon to bring up the "Generate password" dialog
 1. Grab the title bar and move the mouse
 1. Observe that the main window "sticks" to the modal window and the two moves together as a unit

## Debug info
KeePassXC - Version 2.6.2
Revision: e9b9582

Qt 5.12.8
Debugging mode is disabled.

Operating system: Ubuntu 20.04.1 LTS
CPU architecture: x86_64
Kernel: linux 5.4.0-52-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.5

**Comment by ba32107** [comment]
Sorry, accidentally created in the wrong repo. Thanks for moving it.

The same issue does not happen in Windows:

```
KeePassXC - Version 2.6.2
Revision: e9b9582

Qt 5.15.1
Debugging mode is disabled.

Operating system: Windows 10 Version 2004
CPU architecture: x86_64
Kernel: winnt 10.0.19041

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.6
```

**Comment by droidmonkey** [comment]
What desktop environment?

**Comment by ba32107** [comment]
Sorry, forgot to mention that important piece of info. I'm using Gnome (might be worth adding this to the debug info list?)

**Comment by droidmonkey** [comment]
This must be a "feature" of modal windows on Gnome. This does not occur on XFCE.

**Comment by ba32107** [comment]
I believe you are right, however I need to point out that this only seem to apply to Qt applications. None of the applications have this problem for me in Gnome, however, I just tried VirtualBox (which is also built via Qt) and it has the same issue.

Now I am not sure if this is a feature or a bug in Qt (a quick google didn't really help just now), but if it's a feature, it must be possible to turn it off.

**Comment by Greginalld** [comment]
> Now I am not sure if this is a feature or a bug in Qt (a quick google didn't really help just now), but if it's a feature, it must be possible to turn it off.

Gnome shell has attached modal dialogs by default, and Ubuntu ships with this unchanged.
However this affects all modal windows, not just Qt apps, so I'm not sure this applies.

If you haven't already, try turning modal attach off with either
`gsettings set org.gnome.mutter attach-modal-dialogs false`
or install gnome-tweaks and toggle Windows->Attach Modal Dialogs

**Comment by droidmonkey** [comment]
Great so this is definitely not on us, thank you!

**Comment by ba32107** [comment]
Thanks @Greginalld, disabling that setting did the trick. I am a bit confused about this though - you mentioned that this is Gnome default and affects all modal windows. However I explicitly tested with multiple applications, but the only ones I found that have the modals attached are KeePassXC and VirtualBox. 

I tested this just now: opened file explorer, then clicked the three dots button in the top right corner, then `Preferences`. I consider this a modal window (I can't click anything behind it), but still I am able to move the modal around (with `Attach Modal Dialogs` enabled). This made me assume this is Qt "feature". Do you know why this happens?

**Comment by droidmonkey** [comment]
It could be that the file explorer is emulating a modal window, but its not actually modal.
