### ISSUE TITLE
As Android phone user I would like to have possibility to export additional attributes

### ISSUE THREAD

**Issue by pmajkutewicz** [keepassxreboot/keepassxc#5589]
## Summary
I'm using Keepass2Android and KeePassXC. Android versions allow me to store app id as an additional attribute. This way the android version identifies app, and my password is automagically filled. 

I would like to have the possibility to export this. So in that way after doing import and export (backup and restore from backup) I'll preserve my app configuration and would not have to set up all my apps once again.

The following screen is an example of a property that I would like to be able to export and restore:
![kp](https://user-images.githubusercontent.com/12598208/96925366-548b0d80-14b4-11eb-995a-aedf2c4bdd04.png)

IMO all properties should be exported/imported

**Comment by droidmonkey** [comment]
What are you trying to do? It sounds like you want to export your database to an _unencrypted_ file, move it somewhere, and reimport it.

**Comment by pmajkutewicz** [comment]
@droidmonkey 
Yes, I want to create backup:
- export to file, hide it, and in case of failure restore all data
- print it, hide it, and in case of failure restore it

**Comment by droidmonkey** [comment]
If you want a database backup, use the Database -> Save Backup... feature. Save it to a USB disk along with keepassxc portable and lock it away somewhere. If you want to print your database export it to html and print.

Export is not ever going to be a total backup solution. It's not the purpose. There is A LOT of data in the database that will never be exported. 

This is also a duplicate request.

**Comment by pmajkutewicz** [comment]
@droidmonkey Make sense. Thank You
