### ISSUE TITLE
Only the first auto-type entry is presented to user from a single entry where multiple window titles match

### ISSUE THREAD

**Issue by Ian2020** [keepassxreboot/keepassxc#559]
Consider a website with multiple pages to its login process that all have the same title, e.g. "Log In". We have a single entry to manage the credentials and add multiple auto-type sequences to it with the same window title match: "Log In*". Under KeePassXC only the first sequence is presented to the user for selection when triggering auto-type.

## Expected Behavior
User is presented with all the matching auto-type sequences from an entry.

## Current Behavior
User is presented with the first matching auto-type sequence for an entry, even if there are more.

## Steps to Reproduce (for bugs)
1. Create a new entry with user:user, pass:pass and URL http://keepass.info/help/kb/testform.html
1. Add two (or more) auto-type sequences, both with the same window title "Test Form*" but different sequences
2. Visit http://keepass.info/help/kb/testform.html
3. Trigger auto-type
4. Only the first auto-type sequence is presented for auto-type selection

## Context
This makes it impossible to log in to websites with multi-page logins and use just one entry to manage the credentials. The original KeePass has the expected behaviour so I see this as a bug.

## Your Environment
I don't think environment is relevant but I am on Fedora 25.

**Comment by TheZ3ro** [comment]
Related to https://github.com/keepassx/keepassx/pull/132

**Comment by Ian2020** [comment]
Fantastic thanks, look forward to trying it out.
