### ISSUE TITLE
CLI-only version

### ISSUE THREAD

**Issue by Akiiino** [keepassxreboot/keepassxc#5590]
## Summary
It would be great to be able to build only `keepassxc-cli` without any graphical parts; it seems to be impossible as of now (at least, I couldn't figure out how to do so).

## Context
I'm currently using KeepassXC on a headless remote server, and all of the UI parts are not needed there; however, they provide significant overhead in terms of storage taken up, especially when building from scratch. It's not a dealbreaker, of course, but it would be nice to have a minimal CLI-only KeepassXC for these cases.

**Comment by droidmonkey** [comment]
We are already working on it, thank you!
