### ISSUE TITLE
Support for username and password on different pages

### ISSUE THREAD

**Issue by hdkrus** [keepassxreboot/keepassxc#5591]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
It would be nice allow the browser addons to support username and passwords on different pages, since some websites ask you to enter username and after a "continue" button they ask for the password.

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )
https://accweb.mouv.desjardins.com/

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )

**Comment by droidmonkey** [comment]
We already support that. Add the site as a username only site.
