### ISSUE TITLE
auto-type entry matching

### ISSUE THREAD

**Issue by BlackFoxController** [keepassxreboot/keepassxc#5592]
At the moment, auto-type does not always find the entry related to the window title. Title and url matching are not always sufficient. (url matching does not work for me on Firefox 82.0 + Ubuntu 18.04 + KeePassXC 1.6.2, but that may be a separate issue).
In KeePass (the one written in C#) there used to be an option to match title by tag(s). This meant that you could add a tag, say "Log in" to allow KeePass to find a tab matching that entry (some websites just put their title tag to "Log in" or something). For me, the only way to attach auto-type to these windows now, is to set the entry title to "Log" or "Log in", which is non- descriptive.

I suggest there to be an option that in the case no entry is found, all the auto-type options are shown. Just as is the case when multiple entries are found. The search filter in that window is quite efficient.
Alternatively, to bring tags into the mix and allow to match windows by any/ all tags.

**Comment by phoerious** [comment]
Edit your entry, click on "Auto-Type" and add a rule to match windows titled "Login".

**Comment by BlackFoxController** [comment]
Wow. Okay! Amazing, thanks.
