### ISSUE TITLE
unlock Database on Windows Login

### ISSUE THREAD

**Issue by alex-1987** [keepassxreboot/keepassxc#5594]
## Summary
I moved from KeePass2 to KeePassXC.
One nice feature was to unlock the Database on the Windows Login

## Examples
Type your Windows passwort or Pin and automatically open the KeePassXC Database

## Context
Only One Passwort.
Now i log into Windows and need to Type my KeePassXC password again. If i Lock my Laptop i need to unlock KeePassXC again

Thanks

**Comment by droidmonkey** [comment]
Duplicate #2088

**Comment by ZhangTianrong** [comment]
@alex-1987 I guess you are looking for a less secure option such that you would like the database unlocked whenever you are logged in. I sometimes choose convenience over security too and I would suggest storing you master key in some EFS encrypted folder and set up a scheduled task to unlock the database in background by typing it to `KeePassXC.exe --pw-stdin` when you log in. You can also add more scheduled tasks to handle lock screen, hibernate, etc. I guess you can make it a bit safer by clearing tmp files and page files on log out like what people usually do with fs based encryption or even specifically make a small partition for the master key and use `bitlocker` to encrypt it.
