### ISSUE TITLE
Auto-Type problem

### ISSUE THREAD

**Issue by wilbertvolkers** [keepassxreboot/keepassxc#5595]
In the Auto-Type Dialog I press ENTER to select the correct entry. However it seems that this ENTER key is also send to the window where the information needs to be filled-in BEFORE the Auto-Type. Depending how this is handled, this action may put the Auto-Type in all the wrong places.

(to enable the dialog) Tools > Settings > Auto-Type> Always ask before performing Auto-Type

Workaround: mouseclick to select the correct entry

**Comment by droidmonkey** [comment]
You are missing debug information...

**Comment by wilbertvolkers** [comment]
KeypassXC 2.6.2 x64 for Windows
Also seen this in an earlier version (2.3.3 x64)

I have a login-window (ASUS router) where an ENTER key in the empty username-field takes you to the next field, (the password-field). This might be unusual and allows me to see this.

In the Auto-Type Dialog I press ENTER to select the correct entry. Then an ENTER is send to the login-window BEFORE the Auto-Type and the password ends up in some other place.

When I mouseclick instead of ENTER everything works as expected. 

Anyway, thank you for the tool I'm really happy with it. I hope you can use this information and if not you can close this issue if you like.

**Comment by droidmonkey** [comment]
Is this login window in a browser or a desktop app? Do any other windows (test by Auto-Type into notepad) produce the same error?

**Comment by wilbertvolkers** [comment]
Good point, I tried it in a Notepad, it does not happen there. I access the maintenance page with Firefox browser. I just tried in Edge, it does **not** happen there.

**Comment by droidmonkey** [comment]
Then it would also not be keepassxc causing the problem.
