### ISSUE TITLE
Support linking user name and password from another record

### ISSUE THREAD

**Issue by dclong** [keepassxreboot/keepassxc#5598]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )

It is common for websites to support login using other accounts (e.g., GitHub, Google, FB, etc.). Let's say that I want to create a new record (of account info) but it is identical to my GitHub account. It would be convenient if there's a way to allow me just link this new record with the existing Github account record to avoid reentering user name and password. Also, update of password in any of those linked records should be reflected in all linked records.

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )

**Comment by droidmonkey** [comment]
Clone the entry and check the box to reference the username and password of the original entry
