### ISSUE TITLE
keepassxc 2.3.1 GUI does not come up on Ubuntu 18.04 with fvwm 2.6.7 and tigervnc 1.7.0+dfsg-8ubuntu2

### ISSUE THREAD

**Issue by dstromberg** [keepassxreboot/keepassxc#5599]
## Overview
Subject line pretty much says it, but I should add that it works fine if I display from the same server with SSH tunneling to Debian with Cinnamon.  I should also mention that keepass2 works fine.l

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Start a tigervnc server with fvwm2 in it
2. Start a tigervnc viewer to that server
3. Run keepassxc
4. No GUI pops up

## Expected Behavior
I expect the GUI to come up to allow me to edit/view passwords

## Actual Behavior
No GUI comes up

## Context
N/A

[NOTE]: # ( Paste debug info from Help → About here )
keepassxc 2.3.1

[NOTE]: # ( Pick choices based on your environment )
Operating System: Ubuntu 18.04
Desktop Env: fvwm2
Windowing System: X11 (tigervnc)

**Comment by phoerious** [comment]
Please update to KeePassXC 2.6.2, we do not support 2.3 anymore.

**Comment by dstromberg** [comment]
I tried to install keepassxc 2.6.2 from source, but ran afoul of yubikey issues.  So I fell back on the PPA.  That installed 2.6.2. pretty easily.

But now when I run keepassxc, I get a blank window of about the size I'd expect (with no text), and a tall/narrow second window that appeared to span greater than the height of my fvwm pager.

Any further suggestions?

Thanks a bunch for the cool tool.

**Comment by droidmonkey** [comment]
Use the appimage

**Comment by dstromberg** [comment]
The appimage also does not work. This time I get much the same empty window, except it has a small empty rectangle in the upper left.

**Comment by dstromberg** [comment]
I'm including the tty output below.  This is from the appimage.

QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (faviconTimeoutSpinBox/QSpinBox) Negative sizes (-268435366,0) are not possible
QWidget::setMinimumSize: (faviconTimeoutSpinBox/QSpinBox) Negative sizes (-268435366,0) are not possible
QWidget::setMinimumSize: (faviconTimeoutSpinBox/QSpinBox) Negative sizes (-268435366,0) are not possible
QWidget::setMinimumSize: (faviconTimeoutSpinBox/QSpinBox) Negative sizes (-268435366,0) are not possible
QWidget::setMinimumSize: (faviconTimeoutSpinBox/QSpinBox) Negative sizes (-268435366,0) are not possible
QWidget::setMinimumSize: (autoTypeDelaySpinBox/QSpinBox) Negative sizes (-268435366,0) are not possible
QWidget::setMinimumSize: (autoTypeStartDelaySpinBox/QSpinBox) Negative sizes (-268435366,0) are not possible
QWidget::setMinimumSize: (clearClipboardSpinBox/QSpinBox) Negative sizes (-268435366,0) are not possible
QWidget::setMinimumSize: (touchIDResetSpinBox/QSpinBox) Negative sizes (-268435366,0) are not possible
QWidget::setMinimumSize: (lockDatabaseIdleSpinBox/QSpinBox) Negative sizes (-268435366,0) are not possible
QWidget::setMinimumSize: (clearSearchSpinBox/QSpinBox) Negative sizes (-268435366,0) are not possible
QWidget::setMinimumSize: (clearClipboardSpinBox/QSpinBox) Negative sizes (-268435366,0) are not possible
QWidget::setMinimumSize: (clearClipboardSpinBox/QSpinBox) Negative sizes (-268435366,0) are not possible
QWidget::setMinimumSize: (touchIDResetSpinBox/QSpinBox) Negative sizes (-268435366,0) are not possible
QWidget::setMinimumSize: (touchIDResetSpinBox/QSpinBox) Negative sizes (-268435366,0) are not possible
QWidget::setMinimumSize: (lockDatabaseIdleSpinBox/QSpinBox) Negative sizes (-268435366,0) are not possible
QWidget::setMinimumSize: (lockDatabaseIdleSpinBox/QSpinBox) Negative sizes (-268435366,0) are not possible
QWidget::setMinimumSize: (clearSearchSpinBox/QSpinBox) Negative sizes (-268435366,0) are not possible
QWidget::setMinimumSize: (clearSearchSpinBox/QSpinBox) Negative sizes (-268435366,0) are not possible
QWidget::setMinimumSize: (autoTypeDelaySpinBox/QSpinBox) Negative sizes (-268435366,0) are not possible
QWidget::setMinimumSize: (autoTypeDelaySpinBox/QSpinBox) Negative sizes (-268435366,0) are not possible
QWidget::setMinimumSize: (autoTypeStartDelaySpinBox/QSpinBox) Negative sizes (-268435366,0) are not possible
QWidget::setMinimumSize: (autoTypeStartDelaySpinBox/QSpinBox) Negative sizes (-268435366,0) are not possible
QWidget::setMinimumSize: (faviconTimeoutSpinBox/QSpinBox) Negative sizes (-268435366,0) are not possible
QWidget::setMinimumSize: (faviconTimeoutSpinBox/QSpinBox) Negative sizes (-268435366,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (spinBoxLength/QSpinBox) Negative sizes (-268435366,0) are not possible
QWidget::setMinimumSize: (spinBoxLength/QSpinBox) Negative sizes (-268435366,0) are not possible
QWidget::setMinimumSize: (spinBoxLength/QSpinBox) Negative sizes (-268435366,0) are not possible
QWidget::setMinimumSize: (spinBoxWordCount/QSpinBox) Negative sizes (-268435366,0) are not possible
QWidget::setMinimumSize: (spinBoxSkip/QSpinBox) Negative sizes (-268435366,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (lifetimeSpinBox/QSpinBox) Negative sizes (-268435366,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (lifetimeSpinBox/QSpinBox) Negative sizes (-268435366,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (lifetimeSpinBox/QSpinBox) Negative sizes (-268435366,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (lifetimeSpinBox/QSpinBox) Negative sizes (-268435366,0) are not possible
QWidget::setMinimumSize: (lifetimeSpinBox/QSpinBox) Negative sizes (-268435366,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QPainter::begin: Paint device returned engine == 0, type: 2
QWidget::render: Cannot render with an inactive painter
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (historyMaxSizeSpinBox/QSpinBox) Negative sizes (-268435366,0) are not possible
QWidget::setMinimumSize: (historyMaxItemsSpinBox/QSpinBox) Negative sizes (-268435366,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (transformRoundsSpinBox/QSpinBox) Negative sizes (-268435366,0) are not possible
QWidget::setMinimumSize: (memorySpinBox/QSpinBox) Negative sizes (-268435366,0) are not possible
QWidget::setMinimumSize: (parallelismSpinBox/QSpinBox) Negative sizes (-268435366,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (spinBoxSkip/QSpinBox) Negative sizes (-268435366,0) are not possible
QWidget::setMinimumSize: (spinBoxSkip/QSpinBox) Negative sizes (-268435366,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (lifetimeSpinBox/QSpinBox) Negative sizes (-268435366,0) are not possible
QWidget::setMinimumSize: (lifetimeSpinBox/QSpinBox) Negative sizes (-268435366,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (transformRoundsSpinBox/QSpinBox) Negative sizes (-268435366,0) are not possible
QWidget::setMinimumSize: (transformRoundsSpinBox/QSpinBox) Negative sizes (-268435366,0) are not possible
QWidget::setMinimumSize: (memorySpinBox/QSpinBox) Negative sizes (-268435366,0) are not possible
QWidget::setMinimumSize: (memorySpinBox/QSpinBox) Negative sizes (-268435366,0) are not possible
QWidget::setMinimumSize: (parallelismSpinBox/QSpinBox) Negative sizes (-268435366,0) are not possible
QWidget::setMinimumSize: (parallelismSpinBox/QSpinBox) Negative sizes (-268435366,0) are not possible
QWidget::setMinimumSize: (historyMaxSizeSpinBox/QSpinBox) Negative sizes (-268435366,0) are not possible
QWidget::setMinimumSize: (historyMaxSizeSpinBox/QSpinBox) Negative sizes (-268435366,0) are not possible
QWidget::setMinimumSize: (historyMaxItemsSpinBox/QSpinBox) Negative sizes (-268435366,0) are not possible
QWidget::setMinimumSize: (historyMaxItemsSpinBox/QSpinBox) Negative sizes (-268435366,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (lifetimeSpinBox/QSpinBox) Negative sizes (-268435366,0) are not possible
QWidget::setMinimumSize: (lifetimeSpinBox/QSpinBox) Negative sizes (-268435366,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (lifetimeSpinBox/QSpinBox) Negative sizes (-268435366,0) are not possible
QWidget::setMinimumSize: (lifetimeSpinBox/QSpinBox) Negative sizes (-268435366,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (/QPushButton) Negative sizes (-178956915,0) are not possible
QWidget::setMinimumSize: (formContainer/QWidget) The largest allowed size is (16777215,16777215)
QWidget::setMinimumSize: (formContainer/QWidget) The largest allowed size is (16777215,16777215)
QWidget::setMinimumSize: (formContainer/QWidget) The largest allowed size is (16777215,16777215)
QWidget::setMinimumSize: (formContainer/QWidget) The largest allowed size is (16777215,16777215)
QWidget::setMinimumSize: (formContainer/QWidget) The largest allowed size is (16777215,16777215)

**Comment by droidmonkey** [comment]
Please provide the output of: `env | grep QT_`

**Comment by dstromberg** [comment]
$ env | grep QT_
QT_ACCESSIBILITY=1

I think tigervnc does scaling, but I don't think I'm using it on this machine.

**Comment by droidmonkey** [comment]
This isn't something we are doing, must be a bad interaction with how you have this setup.

**Comment by dstromberg** [comment]
A Qt "hello world" appears to have the same problem.
