### ISSUE TITLE
Column Options - display from 'Advanced'

### ISSUE THREAD

**Issue by nschloss** [keepassxreboot/keepassxc#5600]
## Summary
I'm a KeepassXC newbie coming from Keepass 2.
Two things I would find very useful:
1) to be able to display columns based on data stored in fields I see on the 'Advanced' tab and be able to copy them to clipboard by double clicking
2) be able to have column displays unique to a Group

## Context
This, IMHO, would make KeepassXC more user friendly to storing and using credit card information.  Essentially just copying functionality that Keepass 2 has.

As it is currently, as I understand it, to get my credit card number onto the clipboard I have to:

1. open the credit card entry in question
2. select 'Advanced'
3. select the 'Additional attribute' I've setup for my credit card number
4. click 'Reveal'
5. highlight the number and Ctrl-C 
whereas if this info could be displayed on the default view for the Group, it could just be double clicked and copied to clipboard

**Comment by droidmonkey** [comment]
Put your credit card number in the username field. This has been discussed before, we are not going to add this feature.
