### ISSUE TITLE
Username field has an offset when in classic theme

### ISSUE THREAD

**Issue by savchenko** [keepassxreboot/keepassxc#5601]
## Overview
Username field in v2.6.2 has an invisible offset. Doesn't affect the actual information stored in db as far as I can tell.

## Steps to Reproduce
1. Install v2.6.2 on Windows 20H1, default "light" theme.
2. Create a new record.
3. Note the gap in the username field.

## Expected Behavior
All fields are aligned consistently.

## Actual Behavior
![image](https://user-images.githubusercontent.com/300146/97064761-e455b800-1597-11eb-9274-d6bc7671b1f0.png)

## Context
```
KeePassXC - Version 2.6.2
Revision: e9b9582

Qt 5.15.1
Debugging mode is disabled.

Operating system: Windows 10 Version 2004
CPU architecture: x86_64
Kernel: winnt 10.0.19041
```

**Comment by droidmonkey** [comment]
No it doesn't, I fixed a misalignment specifically in 2.6.2. Something on your end is causing this.

**Comment by a-oz** [comment]
@savchenko @droidmonkey 
I'm also seeing the offset in v2.6.2 with Win10 ltsc:

![image](https://user-images.githubusercontent.com/25366956/97113196-f6be1780-16a5-11eb-8bef-c2c994fdb0e0.png)

## Context
KeePassXC - Version 2.6.2
Revision: e9b9582

Qt 5.15.1
Debugging mode is disabled.

Operating system: Windows 10 Version 1809
CPU architecture: x86_64
Kernel: winnt 10.0.17763

**Comment by SaintBol** [comment]
This offset issue of the username field is present on macOS too (KeePassXC 2.6.2, macOS 10.15.7)

**Comment by droidmonkey** [comment]
Its an issue with the classic theme. Just use one of our themes (light or dark) to get the desired look.

**Comment by l0f4r0** [comment]
Just to be sure to understand, you ask us to use either light or dark theme to avoid the issue with the classic (platform agnostic) theme?
You have no control about the classic theme?

**Comment by droidmonkey** [comment]
The bug only affects the classic theme...

**Comment by l0f4r0** [comment]
Thanks for the feedback.
Yes, indeed. Unfortunately, this is the one I prefer because of its compactness and simplicity ;)

**Comment by solidcolour** [comment]
> Its an issue affecting the classic theme (platform agnostic). Just use one of our themes (light or dark) to get the desired look.

That didn't sound like a solution to me. Love the Mac native feel of classic theme by the way.

**Comment by droidmonkey** [comment]
Workaround != solution

**Comment by gaelanlloyd** [comment]
I'm seeing it too.  Windows 10 20H2, just updated to 2.6.2.

![2020-11-05 14_16_33-Window](https://user-images.githubusercontent.com/1403649/98303068-6075d580-1f72-11eb-87fd-00693b79c896.png)

Seems like a lot of us like the classic theme and are seeing this issue on multiple machines / OS's.

@droidmonkey: Is the classic theme is no longer supported?

**Comment by droidmonkey** [comment]
This is just a mistake.

**Comment by TonySarpano** [comment]
Thumbs up as a Classic Theme fan here 👍
