### ISSUE TITLE
[Yubikey] v2.6.2 seems to interfere with Yubico authenticator

### ISSUE THREAD

**Issue by savchenko** [keepassxreboot/keepassxc#5602]
## Overview
After upgrade to v2.6.2, Yubikey disappears from Yubico authenticator after a certain timeout.

## Steps to Reproduce
1. Open Yubico Authenticator GUI v5.0.4
2. Open .KDBX that uses challenge-response authentication
3. After some time Authenticator reports "Insert your Yubikey"

## Expected Behavior
Two application peacefully co-exist, same as before.

## Actual Behavior
Perhaps some change in v2.6.2 obtains an exclusive lock to HMAC-SHA "module" of Yubikey and this prevents OTP from being functional?..

GPG functionality doesn't seem to be affected:
```
> gpg.exe --card-status | select -first 4
Reader ...........: Yubico Yubikey 4 OTP U2F CCID 0
Application ID ...: XXXXXXXXXXXXXXXXXXXXXXXXXXXX
Application type .: OpenPGP
Version ..........: 2.1
```

## Context
```
KeePassXC - Version 2.6.2
Revision: e9b9582

Qt 5.15.1
Debugging mode is disabled.

Operating system: Windows 10 Version 2004
CPU architecture: x86_64
Kernel: winnt 10.0.19041
```

**Comment by droidmonkey** [comment]
We made no changes to yubikey for 2.6.2. In fact no meaningful changes since 2.6.0. We don't keep a persistent lock on yubikey since 2.6.0.

**Comment by savchenko** [comment]
Turned out to be Kleopatra from the recent GPG4Win...
