### ISSUE TITLE
How to find duplicate Titles/URLs that are the same?

### ISSUE THREAD

**Issue by fosam** [keepassxreboot/keepassxc#5603]
Hello!

I'm having an extremely hard time finding duplicate Titles/URLs that are associated with the same username in the database.

![Screenshot 2020-10-24 045602](https://user-images.githubusercontent.com/52612348/97066386-52f53e80-15b5-11eb-9166-8a4f9f6c9cd4.png)

I had to scroll through a very long list of entries and strain my eyes to find just some duplicates, and when i used the search function the duplicates showed up.

Why is it impossible to find such duplicates without manually checking each and every entry manually?

**Comment by droidmonkey** [comment]
Duplicate
