### ISSUE TITLE
Yubikey not dectected on ubuntu 18.04

### ISSUE THREAD

**Issue by remiFR31** [keepassxreboot/keepassxc#5604]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
Hello
I have configure my yubikey with  Challenge Response on slot number 2.
When i launch keepassxc and try to put more security with Yubikey => No physical key (aucune clé matérielle détecté)
Another precision, everything else is ok (autologin /sudoers/ .....) with my yubikey key.
Do you have any idea ?
Thanks.
Best Regards
## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. On ubuntu 18.04, launch keypassxc (installation from snap)
2. Try to add a yubikey as security
3. the key is not detected

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows/Linux/macOS
Desktop Env: Gnome/KDE/XFCE/Mate/Cinnamon
Windowing System: X11/Wayland

**Comment by droidmonkey** [comment]
Update to 2.6.2
