### ISSUE TITLE
The password generator doesn't remember configuration

### ISSUE THREAD

**Issue by SylleoYr** [keepassxreboot/keepassxc#5605]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

Unchecking special characters (like `/*+&`) only takes effect currently. KeePassXC doesn't remember the previously configured unchecking special characters.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Open the password generator:

![1](https://user-images.githubusercontent.com/23133978/97070421-b067aa80-160a-11eb-9465-1d129ef12f12.png)

2. Uncheck the special characters:

![2](https://user-images.githubusercontent.com/23133978/97070406-a776d900-160a-11eb-9adf-6cee24d675f5.png)

3. Close the generator and reopen it again:

![3](https://user-images.githubusercontent.com/23133978/97070434-c5443e00-160a-11eb-8cff-a783e3ee89b5.png)

Now the generator checks the special characters again, which does not remember my configuration. This behavior seems to be happened internally, but it also influences the password generator of KeePassXC-Browser plugin, I cannot get a expected password.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

KeePassXC should remember the configuration and write it into the config file, and apply it immediately.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

The previously unchecked special characters appears again when I reopen the generator, the configuration only takes effect currently.

## Context
[NOTE]: # ( Give us any additional information you may have. )

> Related issue: #5525 
> This problem appears since version 2.6.1, but has not been fixed yet.
> The temporary solution is change this configuration in the config file, but it is not a good way.
> 
> I install KeePassXC using [`scoop`](https://github.com/lukesampson/scoop): `scoop install keepassxc`

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.2
Revision: e9b9582

Qt 5.15.1
Debugging mode is disabled.

Operating system: Windows 10 Version 2004
CPU architecture: x86_64
Kernel: winnt 10.0.19041

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.6

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 10 2004

**Comment by droidmonkey** [comment]
I fixed this in #5129

**Comment by droidmonkey** [comment]
Ugh confirmed, this is broken

**Comment by droidmonkey** [comment]
I typoed here:
https://github.com/keepassxreboot/keepassxc/blob/cd519e1bf3f6e003327a5d45d9dd66a22aa117a4/src/gui/PasswordGeneratorWidget.cpp#L176-L180
There should be a "!" in the if statement.
