### ISSUE TITLE
Unlock window isn't being shown when traversing with ALT + TAB

### ISSUE THREAD

**Issue by imp1sh** [keepassxreboot/keepassxc#5607]
When Keepass is started the unlock window is shown. I switch to another Application so KeePassXC goes to background. I cannot switch back to it via ALT + TAB since it isn't shown as an element. I'm using Fedora 33.

## Steps to Reproduce

- Install KeepassXC

- Start Keepass

- Switch to other ap so Keepass goes into background

- Try to Switch back to Keepass with ALT + TAB.

## Expected Behavior
It should be there instead of not being there

## Context
I experienced this phenomena on two different computers, both installed freshly with Fedora 33.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.1
Revision: 9a35bba

Qt 5.15.1
Diagnosemodus ist deaktiviert.

Betriebssystem: Fedora 33 (Workstation Edition)
CPU-Architektur: x86_64
Kernel: linux 5.8.16-300.fc33.x86_64

Aktivierte Erweiterungen:
- Auto-Type
- Browser-Integration
- SSH-Agent
- KeeShare (bestätigtes und unbestätigtes Teilen)
- YubiKey
- Secret-Service-Integration

Kryptographische Bibliotheken:
 libgcrypt 1.8.6

[NOTE]: # ( Pick choices based on your environment )
Operating System: Fedora 33
Desktop Env: Gnome
Windowing System: Wayland

**Comment by droidmonkey** [comment]
This doesn't seem like something we are at fault for.
