### ISSUE TITLE
Regarding automatic input cannot recognize the window

### ISSUE THREAD

**Issue by GithubABCDEFG** [keepassxreboot/keepassxc#5609]
Thank you very much for all your hard work. I found another error:

In the volume loading window of Veracrypt, KeepassXC cannot recognize it to the automatic input window.

I would like to say whether to add a function: If the suitable password cannot be retrieved, a window will pop up to let the user choose the required password. Currently, if a suitable password cannot be retrieved, a window will pop up saying that the password cannot be retrieved. I think this design is unreasonable.

![image](https://user-images.githubusercontent.com/71936859/97079293-3fd88200-163a-11eb-95ce-7c180191dc80.png)

**Comment by droidmonkey** [comment]
This feature is already requested. Thank you!
