### ISSUE TITLE
Menu is missing Ubuntu 20.04 + kubuntu desktop

### ISSUE THREAD

**Issue by xelyos94ro** [keepassxreboot/keepassxc#5611]
## Overview
![image](https://user-images.githubusercontent.com/39236438/97086551-95a62d80-162c-11eb-8d39-11df7f0a5a79.png)

I have Qt version 5.12.8
There is no menu. 
My OS is Ubuntu 20.04

## Steps to Reproduce
1. Use ubuntu 20.04
2. Install KeepassXc from ppa (also, menu is not working if i install version 2.4.3 from ubuntu store)

## Expected Behavior
Menu is appearing

## Actual Behavior
Menu is missing

KeePassXC - VERSION 2.6.2

**Comment by droidmonkey** [comment]
This is not on us, this is your desktop env
