### ISSUE TITLE
Option to un-minimize window when auto-type fails

### ISSUE THREAD

**Issue by jsture** [keepassxreboot/keepassxc#5613]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
Instead of bringing up this error when auto-type doesn't recognize a window, just un-minimize instead. 
![image](https://user-images.githubusercontent.com/36546134/97106792-e321a980-16c3-11eb-8df1-c5bb174a2e02.png)

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )
Should be pretty self-explanatory. 

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
Generally, if I am trying to auto-type something and it fails, I would probably want to enter my password manually instead. This would save me a click or two every time.

**Comment by droidmonkey** [comment]
Duplicate request of being able to search for an entry if none are found.
