### ISSUE TITLE
Show password in list view missing

### ISSUE THREAD

**Issue by CYBRPVNK** [keepassxreboot/keepassxc#5616]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
In 2.6.1 and previous versions, the option for show all password used to be available in the column selector. In 2.6.2, it is no longer there. 

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Right click on the column. 
2. Used to have options "Hide/Unhide Username" and "Hide/Unhide Password" in the column selector

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Hide/Unhide Username and Hide/Unhide Password are present in the column selector.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Hide/Unhide Username and Hide/Unhide Password are missing.

## Context
[NOTE]: # ( Give us any additional information you may have. )
https://github.com/keepassxreboot/keepassxc/issues/2166#issuecomment-423690569

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.6.2

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 10

**Comment by phoerious** [comment]
This has moved to the View menu.
