### ISSUE TITLE
frozen macOS menu after window was hidden

### ISSUE THREAD

**Issue by mpas97** [keepassxreboot/keepassxc#5617]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
Reopening the window after it was hidden, produces a frozen menu. Only  through "tray icon"->"show window" seems to reshow the window where the main menu is not frozen.
[Demo video](https://github.com/keepassxreboot/keepassxc/files/5438133/macFrozenMenu.zip)

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. make sure "hide window when minimized" is an active setting
2. Open keepassxc with unlocked DB
3. minimize the window (eg, through yellow minus in the top left corner)
4. open keepassxc again (eg, cmd+space and type keepass and press enter)

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
I expect to be able to click on the app menu.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Nothing happens. The menu bar seems frozen.

## Context
[NOTE]: # ( Give us any additional information you may have. )
Also reopening it through the app icon (launchpad) produces a frozen menu.
When reactivating the window through "tray icon"->"show window", the menu doesn't get frozen.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.6.2 (same with 2.6.1, app has already been reinstalled etc)

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS

**Comment by droidmonkey** [comment]
Pretty sure this is a qt issue. I experience this all the time when Debugging on mac. There is nothing we can do or agree doing to cause this.
