### ISSUE TITLE
Drag and Drop not working on 2.6.2 macOS 10.15

### ISSUE THREAD

**Issue by t3easy** [keepassxreboot/keepassxc#5620]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
Drag and drop entries not working since update to 2.6.2

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Create an entry in a folder
2. Try to drag it to another folder
3. The item can not be dragged

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
D&d work

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
D&d don't work

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.6.2
Revision: e9b9582

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS

**Comment by phoerious** [comment]
Try restarting or reinstalling. We had a similar report before, but it wasn't reproducible and resolved itself.

**Comment by droidmonkey** [comment]
Reinstall fixes it, duplicate

**Comment by t3easy** [comment]
Reinstall (replace the app by the one from the v2.6.2-2 dmg) fixed the problem. Seems like you fixed it by rebuilding the app/dmg?!

**Comment by t3easy** [comment]
The problem comes back after some starts

**Comment by chriskuipers** [comment]
Hi! After the upgrade to KeepassXC v2.6.3 on macOS 11.1 I can still reproduce the issue mentioned in #5636 but I cannot reply to the issue over there since it is closed. Could you perhaps reopen the issue?

**Comment by droidmonkey** [comment]
The qt version necessary didn't make 2.6.3. It will be in 2.6.4.

**Comment by MrChocolatine** [comment]
Hi there.

Instead of (or additionally to) dragging entries, why not giving the ability to change the group of an entry using a dropdown or something like that?
- A right-click on a entry > Change group > List of existing groups
- Edit an entry > A new field `Group` like the fiel `Username`
