### ISSUE TITLE
Cannot move entry to a group

### ISSUE THREAD

**Issue by skyflyer** [keepassxreboot/keepassxc#5621]
## Overview

With reference to #3077: Running latest macos (10.15.7) and KeePassXC 2.6.2. I can not move entries to a group. The drag and drop functionality is not working at all.

## Steps to Reproduce

1. Create new database
2. Add an entry to root
3. Add a group
4. Try to move (drag) an entry from the list to the group

## Expected Behaviour

The entry would be moved to a group.

## Actual Behaviour

Dragging behaviour does not even start, nothing happens.

## Context

The KeePassXC app has permissions in the "Accessibility" section of privacy controls.

KeePassXC - Version 2.6.2
Revision: e9b9582

Qt 5.15.1
Debugging mode is disabled.

Operating system: macOS 10.15
CPU architecture: x86_64
Kernel: darwin 19.6.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
 libgcrypt 1.8.6

Operating System: macOS
Desktop Env: n/a
Windowing System: n/a

**Comment by droidmonkey** [comment]
Reinstall, duplicate

**Comment by skyflyer** [comment]
Reinstall worked like a charm 👍 . Sorry I missed a duplicate issue.
