### ISSUE TITLE
What is the difference between 2.6.2-2 and 2.6.2 in git

### ISSUE THREAD

**Issue by adudek16** [keepassxreboot/keepassxc#5624]
In git, there are 2 versions of 2.6.2 but nothing that explains why or which one you should download. We can assume but it would be nice if there was a note on why. It is possible I missed it somewhere.

**Comment by droidmonkey** [comment]
The original one should be removed. This was directly related to the inability to load keepassxc on macOS  10.13

**Comment by adudek16** [comment]
That is what I figured but wanted to double check.   
Keep up the good work.

**Comment by phoerious** [comment]
Always download the one linked on the website. I did not remove the original one to avoid breaking downstream deployment scripts.
