### ISSUE TITLE
Clicking on "Open existing database" wont show popup

### ISSUE THREAD

**Issue by Mirokko** [keepassxreboot/keepassxc#5625]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
It used to be working in some version... So i open keepassxc on startup, it launches  just fine and than, on first screen i click 

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Open keepassxc
2. Click on "Open existing database"

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Shold open popup, where i can choose db file

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
nothing

## Context
[NOTE]: # ( Give us any additional information you may have. )
i tried to downgrade a few versions like 2.6.0, 2.5.4, 2.4.0. Everything same.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.1
Revision: 9a35bba

Qt 5.15.1
Debugging mode is disabled.

Operating system: Manjaro Linux
CPU architecture: x86_64
Kernel: linux 5.8.16-2-MANJARO

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.6

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux, Manjaro
Desktop Env: Gnome
Windowing System: X11

**Comment by Mirokko** [comment]
by the way, opening database with `keepassxc /path/to/db` works fine, clicking on recent databases works too.

**Comment by Mirokko** [comment]
Looks like on my setup i cannot see file popups, because i cannot use any of these buttons too 
![image](https://user-images.githubusercontent.com/11059471/97541054-2bdfa800-19cd-11eb-9ed5-c7c11438d930.png)

**Comment by phoerious** [comment]
That is a bug on your end. It works perfectly fine on Gnome3. Please make sure you have configured your system correctly for Qt applications. Install qt5ct if it's not there.

**Comment by Mirokko** [comment]
yes, i was missing qt5ct, thanks!
