### ISSUE TITLE
Drive cannot be mounted, when KeepassXC in Autostart

### ISSUE THREAD

**Issue by Gratulant** [keepassxreboot/keepassxc#5626]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
net use X:   cannot connect to drive X:   as long as keeepassxc is in Autostart of Windows

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1.  keepassxc runs in autostart : YES
2.  Connextion to drive X: on \\Server  fails  as long as KeepassXC is running by Windows-Start
3. Info by Windows : Drive X: is already in use
Problem solved, as long as KeepassXC is not starting together with Windows-System-Start

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows/Linux/macOS
Desktop Env: Gnome/KDE/XFCE/Mate/Cinnamon
Windowing System: X11/Wayland

**Comment by droidmonkey** [comment]
Are you opening a database from drive X? Sounds like its already being auto mounted if it is in use...
