### ISSUE TITLE
Login fields detection fails, if username and password field are not on the same site

### ISSUE THREAD

**Issue by MarkoGit1900** [keepassxreboot/keepassxc#5627]
## Overview
The login fields detection of the KeepassXC-Browser plugin fails, if the website asked at first the username with a 
confirm button and ask the password on the next page.
Examples: 
- paypal.com
- store.hp.com

The userdefined choosing of the login fields wont help, because you overwrite the username field with the password field or vice versa. I define the username field, and press skip password and TOTP and confirm. On the next password page I skip the username field and set only the password field, but I see already the "1" in the password field: 
![Choose userdefined fields](https://user-images.githubusercontent.com/73645519/97571434-13c95200-19e8-11eb-9fd9-e432dd857536.png)
But I choose the field as password field, but with the next login the username field has no icon, the password field has it. The context menu (fill user name and password) is also not working in this case, he filled nothing without an error message.

Why not a simple solution like the "KeePassHelper Password Manager" addon. There I can choose fill username or password or both via the toolbar icon. Also a search entry function is here, if the URL is not stored or incorrect. But only as additional option, because your solution is faster and better, if it is working.

My URL's are correct, exactly https/http and
https://page.com instead of https://login.page.com. Have testet all variants of URL's in the db entry.

[NOTE]:
KeePassXC - VERSION 2.62

[NOTE]:
Operating System: Windows
Browser: Firefox

**Comment by varjolintu** [comment]
Add the site to extension settings' Site Preferences tab and enable _Username-only Detection_.

See also https://github.com/keepassxreboot/keepassxc-browser/pull/1010 and how it improves this in the next extension version.

**Comment by MarkoGit1900** [comment]
It didn't help. I must transfer the password via the clipboard, which is not secure.
The context menu didn't find any entry.

**Comment by varjolintu** [comment]
I had no problems with either of the sites. HP's page (under https://login.id.hp.com/login-ui) will work if your entry URL is `https://hp.com`, and Site Preferences has `https://login.id.hp.com/*` with _Username-only Detection_ enabled. I added that through the extension popup because it recommended it for the site.
