### ISSUE TITLE
open multiple databases with diffrent passwords with --pw-stdin over commandline

### ISSUE THREAD

**Issue by steel4me** [keepassxreboot/keepassxc#5629]
## Overview
open multiple databases with diffrent passwords with --pw-stdin over commandline

## Steps to Reproduce
1) `KeePassXC.exe --pw-stdin db1 < pw1`
2) `KeePassXC.exe --pw-stdin db2 < pw2`
3) `KeePassXC.exe --pw-stdin db3 < pw3`

## Expected Behavior
all databases should be opened and unlocked with their passwords

## Actual Behavior
only first database will be opened and unlocked, database 2 and 3 ask for password in gui

**Comment by droidmonkey** [comment]
thats not how it works, use it like "< pw1\npw2\npw3"

**Comment by steel4me** [comment]
thank you very much. i will test it. where can i find this information? im very sorry to make an issue. where can i watch next time? is it in documentation or wiki?

**Comment by droidmonkey** [comment]
That's just the way standard input works. Right now we don't pass the credentials to the running instance which is what occurs on your second and third call to keepassxc.  You have to do everything in one call.

**Comment by steel4me** [comment]
`\n` does not work in windows batch world. Maybe under Linux. 

I tried it over 30 minutes now with diffrent approaches.

`KeePassXC.exe --pw-stdin db1 db2 "< pw1 ^ pw2"`
`KeePassXC.exe --pw-stdin db1 db2 < pw1 ^ pw2`
`KeePassXC.exe --pw-stdin db1 db2 < pw1 ^ pw2`
`echo pw1 & echo.pw2| KeePassXC.exe --pw-stdin db1 db2`

Funfact: i work daylie with stdout and stdin under linux, i develope things in c ++ and manipulate memory, i put thousand lines of code in linux bash programming for the last few days, i automate processes professionally, but i am not able to pass passwords for keepassxc via stdin under windows to the process in 30 minutes. 
Now I'll take my pc and throw it out the window ...

**Comment by droidmonkey** [comment]
😆 lol. I am aiming to fix the "pass password to running instance" problem in 2.7

**Comment by steel4me** [comment]
> 😆 lol. I am aiming to fix the "pass password to running instance" problem in 2.7

would be damn great, i love the gui and browser integration with keepassxc

**Comment by steel4me** [comment]
`(echo pw1 & echo pw2) | KeePassXC.exe --pw-stdin db1 --pw-stdin db2` this should work but behind passwords are spaces 💯
