### ISSUE TITLE
Check Duplicated / Weak Passwords

### ISSUE THREAD

**Issue by CliffMilton** [keepassxreboot/keepassxc#5630]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )

Ability to scan all entries for duplicate/weak passwords/accounts involved in a breach

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )

To quickly identify weak or duplicated passwords.

**Comment by phoerious** [comment]
Please update your KeePassXC.
