### ISSUE TITLE
Unable to Drag and Drop entries to other folder

### ISSUE THREAD

**Issue by CliffMilton** [keepassxreboot/keepassxc#5631]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Open Application
2. Open DB
3. Find entry want to move
4. Drag to another folder

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

Entry should move.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

Nothing happens, it is as if the DB is locked and doesnt allow me to move.

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.2
Revision: e9b9582

Qt 5.15.1
Debugging mode is disabled.

Operating system: macOS 10.15
CPU architecture: x86_64
Kernel: darwin 19.6.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
 libgcrypt 1.8.6

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS Catalina 10.15.7

**Comment by droidmonkey** [comment]
Reinstall,  duplicate
