### ISSUE TITLE
Expanding group sorting capabilities?

### ISSUE THREAD

**Issue by krsnik93** [keepassxreboot/keepassxc#5632]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
Right now, it is possible to sort groups by name, either A-Z or Z-A. I am wondering if there is any interest for other criteria, for example:
- Date created
- Date modified
- Date used (this could mean the last time any entry data was copied to clipboard or auto-type used)
- Size / number of entries (?)
- Tag / Label (?)

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )
Ideally I would replace 'Sort A-Z' and 'Sort Z-A' with a single 'Sort ->' with a dropdown and then have all the conditions available in both directions (asc and desc).

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
I was looking to contribute to the project and this idea intrigued me as I don't feel fully satisfied with just being able to sort by name.

**Comment by droidmonkey** [comment]
To be honest seems like an unnecessary number of options.

**Comment by tWido** [comment]
What about just "sort by last modified" and "sort by newest"? So one can keep most used at top and it wouldn't create too many options. If that's OK, i will implement it right away.

**Comment by droidmonkey** [comment]
I really don't find this useful. I would much rather implement dynamic groups, like search groups, that find and sort entries from all over the database. That would be far more useful.

**Comment by droidmonkey** [comment]
This had been implemented
