### ISSUE TITLE
KeePassXC 2.6.2 fails to save database changes

### ISSUE THREAD

**Issue by RastislavKish** [keepassxreboot/keepassxc#5633]
## Overview

Possibly after updating KeePassXC to 2.6.2, I am no longer able to save changes in my database. After adding an entry and clicking save, nothing happens. I'm getting warnings from time to time with prompts to save changes, but when I click the button, the dialog disappears and reappears again after some time.
I got a recommendation to turn off secure saving as syncing services such as DropBox could have placed a lock on the database file.
But the issue here is, that I'm not using anything like that, and this has worked without problems in the past, may be a month ago.

## Steps to Reproduce

1. Open KeePassXC window and unlock the database.
2. Make any change in the database, for example add an entry.
3. Click on Lock the database in Tools menu.

## Expected Behavior

The changes are saved and database locked.

## Actual Behavior

A warning about database not saved pops up, after clicking save, the database stays unsaved and unlocked.

## Context

Operating system Ubuntu Mate 20.04 64-bit using X11

KeePassXC - Version 2.6.2
Revision e9b9582
Distribution Snap

Qt 5.9.5
Debugging mode turned off

Operating system: Ubuntu Core 18
CPU architecture: x86_64
Core: linux 5.4.0-52-generic

Activated extensions 
- Automatic filling
- Browser integration
- Agent SSH
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret service integration

Cryptographical libraries
 libgcrypt 1.8.1

**Comment by droidmonkey** [comment]
Try using our appimage

**Comment by droidmonkey** [comment]
See #5097 as well
