### ISSUE TITLE
Text field action buttons stacked

### ISSUE THREAD

**Issue by frudolph77** [keepassxreboot/keepassxc#5634]
## Overview
Icons in the password work box are stacked, when opening a password entry. When I scale the windows, the icons are displayed in parallel.

What is really strange is that on an other Linux Box the icons are displayed in parallel, when opening an entry.
But there are only two, the die and the eye but not the others. Same database, very same entry.

## Steps to Reproduce
1. Just open an password entry on a Linux box. 

## Expected Behavior
After scaling:
![after_scaling](https://user-images.githubusercontent.com/63302676/97705679-c36bf600-1ab4-11eb-9b86-7ce060af28f3.jpg)

## Actual Behavior
When opening an entry
![newly_opened_edit_dialoag](https://user-images.githubusercontent.com/63302676/97705640-b3ecad00-1ab4-11eb-856b-d4670749462a.png)

## KeePassXC Version, OS etc.
KeePassXC - Version 2.6.2
Revision: e9b9582
Qt 5.5.1
Betriebssystem: Ubuntu 16.04.7 LTS

Other linux box
KeePassXC - Version 2.6.2
Revision: e9b9582
Qt 5.9.5
Betriebssystem: Ubuntu 18.04.5 LTS

both: 
Desktop Env: Mate
Windowing System: X11

**Comment by phoerious** [comment]
Please try our AppImage and check if you have qt5ct installed.

**Comment by frudolph77** [comment]
The AppImage Version works fine, the icons are in parallel and only the die and the eye.
But I really want to use the version from the ppa, to automatically get the updates

qt5ct isn't install on neither machine.

**Comment by phoerious** [comment]
I believe this is a bug in Qt 5.9.

**Comment by frudolph77** [comment]
It's the box with Qt 5.5 that is 'broken' not 5.9

**Comment by phoerious** [comment]
I know this is a problem with Qt 5.5. I just assumed it also happened on 5.9, since you listed both. If it doesn't, great.

**Comment by droidmonkey** [comment]
This is a 5.5 bug
