### ISSUE TITLE
Crashes after answer merge or delete dialog

### ISSUE THREAD

**Issue by t3easy** [keepassxreboot/keepassxc#5637]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
Scenario:
Nextcloud client on Mac
Database .kdbx in the synced folder
KeeShare .kdbx.share in a synced nextcloud group folder
Two users with access to the .kdbx.share, both set the folder to synchronize
One Mac, one Windows 10
Even without changes in the databade, KeepassXC on the Mac shows the dialog that something changed and wants to merge or delete
Both options crashes KeepassXC on Mac
No Dialoge or problem on Windows 10

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Share a folder with KeeShare
2. Get a merge or delete dialoge
3. KeepassXC 2.6.2 crashes on macOS

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Merge or delete changes

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
KeepassXC crashes

## Context
[NOTE]: # ( Give us any additional information you may have. )
Nextcloud Desktop 3.0.2 on both devices
Nextcloud 18 Server

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.6.2
Revision: e9b9582

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 10 1909 and macOS 10.15.7

**Comment by t3easy** [comment]
![image](https://user-images.githubusercontent.com/3628035/97969822-e3572e80-1dc0-11eb-9932-7e4bdf6b5045.png)

**Comment by Romern** [comment]
I have the same problem occuring from time to time using KeepassXC 2.6.2 on Linux. I don't remember it occuring in the older versions, but this might be related to this Issue: https://github.com/keepassxreboot/keepassxc/issues/4393

**Comment by ZeekWorld** [comment]
Same on Mac on latest version 2.6.3, when selecting Merge, it hangs and have to Force Quit.

**Comment by chrisovergaauw** [comment]
same issue:

KeePassXC - Version 2.6.4
Revision: 34a78f0

Qt 5.15.2
Debugging mode is disabled.

Operating system: macOS 11.2
CPU architecture: x86_64
Kernel: darwin 20.3.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
- libgcrypt 1.9.1

**Comment by phirestalker** [comment]
I also get the greyed out program freeze periodically (although happening more often lately)
I am also sharing with keeshare.

KeePassXC - Version 2.6.4
Revision: b93fbd1

Qt 5.15.2
Debugging mode is disabled.

Operating system: macOS 11.2
CPU architecture: arm64
Kernel: darwin 20.3.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (only unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
- libgcrypt 1.9.1

**Comment by phirestalker** [comment]
[KeepassXC hang.txt](https://github.com/keepassxreboot/keepassxc/files/6224445/KeepassXC.hang.txt)

[KeepassXC crash report.txt](https://github.com/keepassxreboot/keepassxc/files/6224451/KeepassXC.crash.report.txt)

forgot the reports I copied from MacOS crash reporter. The one named hang is where I force quit the app, I think the other report is the same issue, but I'm not sure why it crashed instead of hanging.

**Comment by droidmonkey** [comment]
Unfortunately those crash reports aren't useful because all symbols are obfuscated. Can you reproduce the crash and hang using a snapshot dmg? Https://snapshot.keepassxc.org

**Comment by phirestalker** [comment]
I have no idea how to reproduce the problem as it seems to happen at random. I can back up my password database and run on one of the snapshots for a while though.
One question, how obvious will database corruption be if it happens?

**Comment by droidmonkey** [comment]
There is no difference to database handling between production and current snapshot. That's just a standard message to discourage casual use.

**Comment by phirestalker** [comment]
I downloaded 2.70 snapshot and it said it needed to merge like before, but this time it didn't freeze or crash.

**Comment by droidmonkey** [comment]
Excellent

**Comment by t3easy** [comment]
I tried the snapshot build-189701 but it tells me, that it doesn't support the sharing of the the previous share file.

> Your KeePassXC version does not support sharing this container type.
Supported extensions are: kdbx.

**Comment by phoerious** [comment]
You built without quazip, I suppose. That's going to be removed anyway.

**Comment by droidmonkey** [comment]
Brew moved to quazip 1.1 which is different api

**Comment by t3easy** [comment]
I didn‘t build it, I downloaded the snapshot from the given link.

**Comment by phirestalker** [comment]
> You built without quazip, I suppose. That's going to be removed anyway.

Does this mean that future versions will not support signing?
My version 2.6.4 for Apple silicon does not support signing either.

**Comment by droidmonkey** [comment]
KeeShare signed database support is being removed because it is a complete waste of time and adds no security, only hundreds of lines of code and additional dependencies.

**Comment by phirestalker** [comment]
OK, it froze again today and I had to force quit. This time however there was no hang report popup. I looked in console and could not find a crash report either. I guess I will have to wait for it to happen again?

Is there a way to force MacOS to generate a hang report every time an app is force quit?

**Comment by droidmonkey** [comment]
Use the System Monitor app

**Comment by phirestalker** [comment]
So I need to manually sample the process when it is not responding?

**Comment by phirestalker** [comment]
I sampled the process in Activity monitor while KeepassXC was not responding. I hope this helps
[Sample of KeePassXC.txt](https://github.com/keepassxreboot/keepassxc/files/6260752/Sample.of.KeePassXC.txt)

**Comment by phirestalker** [comment]
[KeepassXC hang.txt](https://github.com/keepassxreboot/keepassxc/files/6260780/KeepassXC.hang.txt)
This time it did generate a report when I force quit, so here it is.
It looks as if it is stuck calling the same function over and over just by looking at the first 50 lines or so.

**Comment by droidmonkey** [comment]
Looks like it was stuck in a timed loop, probably the database hash checker... for some reason the keepassxc symbols were not visible.

**Comment by phirestalker** [comment]
What settings can I change to make sure the symbols are visible for the next freeze?

**Comment by droidmonkey** [comment]
Besides building a debug version yourself I'm not sure

**Comment by phirestalker** [comment]
I could try that. Are there instructions for building a debug version?

**Comment by droidmonkey** [comment]
It's in our wiki

**Comment by phirestalker** [comment]
Is there a command I can run on the compiled binary that will tell me if
the symbols made it in?

**Comment by droidmonkey** [comment]
You compile with `-DCMAKE_BUILD_TYPE=Debug` you'll get symbols

**Comment by phirestalker** [comment]
OK, that was not on the wiki. It only shows options for snapshot, release,
and prerelease. Got it built and running, so will report back when it
crashes again.
Thanks for the help.

**Comment by phirestalker** [comment]
It looks like the symbols are still missing, but here it is anyway. Is it possible that it has something to do with compiling for arm64 instead of x86_64? Here was my cmake line ` cmake -DWITH_XC_ALL=ON -DCMAKE_BUILD_TYPE=Debug ..`
The hang file is the sample of the process while frozen.
[KeepassXC crash report.txt](https://github.com/keepassxreboot/keepassxc/files/6297904/KeepassXC.crash.report.txt)
[KeepassXC hang.txt](https://github.com/keepassxreboot/keepassxc/files/6297906/KeepassXC.hang.txt)

**Comment by droidmonkey** [comment]
Are you sure you are running the version you built? Those logs show it running from the installed applications folder.

**Comment by phirestalker** [comment]
Yes, I moved it there and chose replace.

**Comment by droidmonkey** [comment]
Sorry I think you need to add `-DWITH_APP_BUNDLE=OFF` to your cmake command and run the keepass binary directly from the build folder. The app bundle may be stripping the symbols as part of packaging.

**Comment by phirestalker** [comment]
It is taking a while this time. Does anyone know how to directly trigger a merge request? Does it have to be a conflicting change?

**Comment by phirestalker** [comment]
Haha, I ask about it and it happens. Here is the sample.
[Sample of keepassxc.txt](https://github.com/keepassxreboot/keepassxc/files/6319078/Sample.of.keepassxc.txt)

**Comment by droidmonkey** [comment]
Yay now we have symbols!

**Comment by droidmonkey** [comment]
OK so what is happening is the following:

1. Database begins the saving process
2. The FileWatcher triggers via timer to check if the kdbx file has changed
3. Since we are saving, it has changed and it then triggers the file reload process
4. During reload the old database (still saving btw!) is attempted to be deleted, but our mutex locker prevents that from happening.

There are a couple bugs here, mainly due to timing of events. I can't understand why the FileWatcher is still getting timer events because we stop the file watcher prior to saving the database.

**Comment by phirestalker** [comment]
I don't know if it is related or not, but it is saving the database almost every minute. It saves when I don't even use a password entry or make any changes.

**Comment by droidmonkey** [comment]
Do you have a keeshare share configured? That could be the cause if all this. If you are seeing constant saving and reloading that could also mean some external process is modifying the file in some way. Maybe even just changing the modified time on you?

**Comment by phirestalker** [comment]
Yes, I have a keeshare set up with one person. I am syncing it using Syncthing, although I had the same results with Dropbox. I know they are not using their passwords every minute, so I guess it is external software like you say. My guess is that blasted MacOS is constantly updating the last modified date because the file is open. I will endeavour to mount it with noatime options if I can and see if that helps.

**Comment by phirestalker** [comment]
Is there anything else I can help with on this? I will probably be less than worthless for coding help but am happy to help otherwise.

**Comment by droidmonkey** [comment]
No we have a fix on the pipeline

**Comment by phirestalker** [comment]
Just updated. It is saving the shared file and my database every minute. Is that normal? I am using Nextcloud for the syncing.

**Comment by droidmonkey** [comment]
Not normal, but points to something touching the file constantly.

**Comment by phirestalker** [comment]
same thing, dialog then freeze. I forgot the process for getting logs or whatever. What do I do?

**Comment by kgit42** [comment]
I also experience the freezing problem on 'file changed' dialog

**Comment by TeoTN** [comment]
@droidmonkey Also got this issue, maybe it's worthwhile reopening?

**Comment by droidmonkey** [comment]
If you have a stack trace I'll be able to fix it

**Comment by fraschm1998** [comment]
> If you have a stack trace I'll be able to fix it

I get a bunch of conflict resolution may lose data then:

```
failed to register FdoSecrets::Item(0x55e9ab2703e0) at "/org/freedesktop/secrets/collection/Passwords/debab39967d24249a63ba96c336b8127"
"Failed to register item on DBus at path '/org/freedesktop/secrets/collection/Passwords/debab39967d24249a63ba96c336b8127'"
QObject::connect(Group, Unknown): invalid nullptr parameter
QObject::connect(FdoSecrets::Item, FdoSecrets::Collection): invalid nullptr parameter
QObject::connect(FdoSecrets::Item, FdoSecrets::Collection): invalid nullptr parameter
zsh: segmentation fault  keepassxc
```
