### ISSUE TITLE
Crashes at launch on MacOS

### ISSUE THREAD

**Issue by cheekymoonkey** [keepassxreboot/keepassxc#5638]
## Overview
Updated to 2.6.2 using brew today and now app crashes at every launch

The dmg works fine

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Launch app
2. App crashes "KeePassXC quit unexpectedly"

## Context
Process:               KeePassXC [5232]
Path:                  /Applications/KeePassXC.app/Contents/MacOS/KeePassXC
Identifier:            org.keepassxc.keepassxc
Version:               2.6.2 (???)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           KeePassXC [5232]
User ID:               501
Date/Time:            2020-10-30 12:12:53.460 -0700
OS Version:            Mac OS X 10.13.6 (17G9016)
Report Version:        12
Anonymous UUID:        E4B173A0-4AE9-E184-3F05-6DEA501E44A2
Time Awake Since Boot: 3200 seconds
System Integrity Protection: disabled
Crashed Thread:        0  Dispatch queue: com.apple.main-thread
Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x4] Symbol missing

Dyld Error Message:
  Symbol not found: ____chkstk_darwin
  Referenced from: /Applications/KeePassXC.app/Contents/MacOS/../Frameworks/libgcrypt.20.dylib (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib

I tried uninstalling and reinstalling with brew, same results.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.6.2
Revision: REVISION 

[NOTE]: # ( Pick choices based on your environment )
Operating System: MacOS High Sierra 10.13.6

**Comment by droidmonkey** [comment]
Use the dmg from our website. Duplicate.
