### ISSUE TITLE
Locked out of DB (db file corrupted/HMAC mismatch) - 2.6.1

### ISSUE THREAD

**Issue by frogfroggy** [keepassxreboot/keepassxc#5639]
## Overview
Started a new keepassxc database which have not been touched from over a month without any entries. After successfully adding passwords for various sites and usernames, I could not login to the DB anymore after closing the program.

I have checked this issue in other posts, and made sure that I unchecked "file key"; left it on default settings; did not change any Argon2 values; typed in multiple times the passwords (checked spelling etc.)

Also opening the .kdbx file with KeepassX and the mobile app KeepassDX were all unsuccessful....

I would appreciate your assistance and support. Thank you in advance ! 

## Steps to Reproduce
1.  Opened Keepassxc 2.6.1
2. Added 7 username entries with their respective passwords (created with the password generator)
3. Left it open while modifying the passwords on the actual internet sites
4. Closed the program
2. Type the password for the database (making sure keylink is not selected/checked)
3. Error message displays: "Error while reading the database: Invalid credentials were provided, please try again.
If this reoccurs, then your database file may be corrupt. (HMAC mismatch)"

## Expected Behavior
Successfully logging into the database for adding new password entries

## Actual Behavior
1. Opened KeepassXC 2.6.1 (with info for new version 2.6.2)
2. Typed in the password for the database (making sure keylink is not selected/checked - default settings)
3. Error message displays: "Error while reading the database: Invalid credentials were provided, please try again.
If this reoccurs, then your database file may be corrupt. (HMAC mismatch)"

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.1
Revision: 9a35bba

Qt 5.6.1
Debugging mode is disabled.

Operating system: Slackware/Salix 14.2
CPU architecture: x86_64
Kernel: linux 4.4.240

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent

Cryptographic libraries:
 libgcrypt 1.7.10

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: XFCE 4.12
Windowing System: X11

**Comment by droidmonkey** [comment]
First, sorry but there is nothing we can do to help you. Can you replicate the issue with a brand new database and easy password (to rule that out)?

**Comment by frogfroggy** [comment]
Hi droidmonkey, after creating a new database set with an easy password the saved files are all fine. 
I will try it on a different OSs and recheck everything again. But thank you for your support.

**Comment by droidmonkey** [comment]
You're welcome, sorry that happened but could have been a corruption of the file when shared between devices.

**Comment by maciejszulia** [comment]
bug still alive cant log in :( all my passes r gone :(((

**Comment by naphelge** [comment]
I just expereinced the same issue on xubunut v2.6.6. I am not sure if the pkg was recently updated or not. I keep (3) different db's and the other two work fine but the third returns the same error. The passwd is one that I am thoroughly familiar with, so there is no issue with me having possibly forgotten the password. I have been using a variation of LeePass for 10+ years on Linux at home and Winblowz at work and I have not expereinced a corrupt db. I guess there's a first for everything. 

If the db is corrupt is there anyway to brute force a password that would be recognized, if that even makes sense? This is a serious foobar for me to rectify if not.

**Comment by droidmonkey** [comment]
If the file is actually corrupt then you cannot recover, unless you have backups.

**Comment by frogfroggy** [comment]
Hi all, the original poster here. Since I locked out of the original DB I kept on contemplating and figuring out why that particular DB with the same password I normally use would not let me sign in to the DB. And after many tries, I finally figured out the reason: Guys, check your password spelling! In my case one letter was off from my original password, and "boom" the DB opened and I was able to access all my accounts again. Hallelujah ! So in my honest opinion it is actually not a "bug" per se but a "user bug". Try checking your spelling and the password. I am pretty sure that is the main culprit.

**Comment by droidmonkey** [comment]
Almost always is 😀 glad you're back now

**Comment by dianne-tennent** [comment]
Hey there, I've just had this same issue. I'm entering my password correctly, and I really don't know why it's saying that the DB is corrupt as I haven't changed anything recently.

**Comment by Q8Khalid** [comment]
Hello, I just started using KeePassXC and made my very first Database and saved the password on a physical notepad and made a key file for extra safety and apparently no matter how many times I put the password it keeps giving me the error message:

"Error while reading the database: Invalid credentials were provided, please try again.
If this reoccurs, then your database file may be corrupt. (HMAC mismatch)"

every single time! 

So I exported the stuff I saved into csv and imported it with a new password also a new key file along side with it.
and not only I took a screenshot of the password(through my phone) but also copy/pasted in a txt file and it still gives me the same error over and over again.

any idea why and how can I get it to work as intended.

**Comment by droidmonkey** [comment]
You likely are not selecting the correct key file to unlock the database. Make sure you select the key file you generated from the unlock dialog.

**Comment by rajeevsingh-ag** [comment]
I just had the same experience -- panicked for 15 minutes before I realized that the key file was not selected. I use both a password and a key file. The key file field gets cleared if you move the kdbx file from one folder to another.
