### ISSUE TITLE
Need KeePassXC version that will work on Windows 32 bit laptop

### ISSUE THREAD

**Issue by greyowl2** [keepassxreboot/keepassxc#564]
I downloaded the portable version of KeePassXC 2.14 and tried to install in on my Dell Laptop running XP and a Win32 system.  I got an error message because this version is for Win64 computers.

Is there a Win32 version of KeepassXC that will work on my laptop?

Thanks for the help.

**Comment by weslly** [comment]
You can get a 32 bit portable zip at the [releases page](https://github.com/keepassxreboot/keepassxc/releases): https://github.com/keepassxreboot/keepassxc/releases/download/2.1.4/KeePassXC-2.1.4-Win32.zip

**Comment by jonathancross** [comment]
@greyowl2  Can this be closed?
