### ISSUE TITLE
Change unsafe saving to be direct write to database file

### ISSUE THREAD

**Issue by iandall** [keepassxreboot/keepassxc#5641]
When KeePassXC saves the database it always creates a new file. This causes problems when sharing the database with keepass2android via gdrive and likely other cloud services. keepasstoandroid apparently keeps a handle to the database file to notice changes and to save updates. After KeePassXC deletes the file, keepass2android can no longer access the original database.

I propose changing the way non-atomic database saves work. Currently the database is 1) written to a temporary file, 2) the old database is deleted, 3) the temporary file is copied to a new files with the same name as the original file, and 4) the temporary file is deleted. Steps 3 and 4 are performed by the QFile::rename function, which never results in an actual rename system call if the database is on gdrive and TMPDIR is a local filesystem. 

The only change in the actual operating system functions performed is to drop step 2 (deleting the old database). However, both QFile::rename and QFile::copy fail if the target file already exists, so it is necessary to write an copyDatabase function which does not have this restriction.

This has been tested and works with KeePassXC, keepass2android and gdrive. It seems unlikely that this would cause new problems with other use cases. This non-atomic method has the potential to leave a partially written file in the event that KeepPassXC is abruptly terminated, or that the device is full, but this is unchanged from the current implementation. 

The default atomic save option is unchanged.  

[0001-Change-behaviour-of-non-atomic-database-saves.patch.gz](https://github.com/keepassxreboot/keepassxc/files/5468917/0001-Change-behaviour-of-non-atomic-database-saves.patch.gz)

**Comment by droidmonkey** [comment]
Create a pr please

**Comment by iandall** [comment]
It is true that you could simply us Database::writeDatabase() directly to the database, but the use of a temporary file is how it is currently done. I assume there is, or was a use case where this was considered important.

Good idea on using google drive versioning, though that might not generalise to other cases.

**Comment by droidmonkey** [comment]
The temp file ensures that the entire database is written (ie, doesn't leave a half-written database file). However, if the temp file is on another partition then the copy operation will basically write a new file anyway causing the same potential problem. We might as well just overwrite the database file directly... as quickly as possible (write to memory then dump to file).

**Comment by droidmonkey** [comment]
Covered by #6335
