### ISSUE TITLE
Add option to create backup entries in defined group

### ISSUE THREAD

**Issue by Leo-PL** [keepassxreboot/keepassxc#5642]
## Summary
Original Keepass has an option to create backup entries inside database, after saving in a defined group (default "Backup"). Without this, I have to copy the entry I wish to edit there manually before editing, and this is a nuisance, because I can forget to do this - I actually did many times since migrating from Keepass to KeepassXC. I'd like this option reimplemented as in Keepass - I don't mind the database growing a few kB every save.

## Context
If for some reason changing password fails, it is nice to have the previous one without resorting to opening previous versions of database. Especially if the service wants the old password for confirmation during changing.

**Comment by droidmonkey** [comment]
Every entry has a history. Please read the documentation: https://keepassxc.org/docs/KeePassXC_UserGuide.html#_history
