### ISSUE TITLE
KeePassXC 2.6.2 crashes

### ISSUE THREAD

**Issue by RolandSM** [keepassxreboot/keepassxc#5644]
Hello,

since few weeks I see unlocated crashes with KeePassXC 2.6.2 on my Kubuntu 20.0.4.1

I have reviewed and see the errors on specific websites, INDEPENDENT if I use Chrome or Firefox...
The website is running a latest PHPMyAdmin page.

I have following testing steps, with which this issue can be reproduced:

    open a terminal and view the syslog like "tail -f /var/log/syslog"
    open keepass and login
    open firefox or chrome and load the phpmyadmin login page
    keepass crahs and close its window, but background process "pgrep kee" runs
    in syslog a "general protection fault" comes or sometimes a "segfault at xxx ip xxx sp xxx error 4 in keepassxc

Other ways.

    You can also prepare a browser with more tabs
    open with closed keepass the phpmyadmin page and in other pages some others
    switch active tab to another as phpmyadmin
    Open KeePass and login.
    Ensure the browser pugin is connected.
    Switch the tabs to the phpmyadmin and again the crash.

**Comment by droidmonkey** [comment]
Do you have a situation where the browser extension could be find over 20 entries for a site?

**Comment by RolandSM** [comment]
Yes this is also the PHPMyAdmin. I already thought on the amount of results, but the error happens also when I activate "Return only best matching ones" and with this options, normally only 1 is found.
But yes, with this domain independent http/https the result is more than 40.

**Comment by droidmonkey** [comment]
This is #5596
