### ISSUE TITLE
KeePassXC 2.6.2 fails to compile at ./src/gui/osutils/nixutils/NixUtils.cpp

### ISSUE THREAD

**Issue by mara004** [keepassxreboot/keepassxc#5645]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
I tried to bulid KeePassXC 2.6.2 from source on Linux (Debian 9, armhf), but compilation terminates because of a problem in the file `./keepassxc-2.6.2/src/gui/osutils/nixutils`:
`[ 53%] Building CXX object src/CMakeFiles/keepassx_core.dir/gui/osutils/nixutils/NixUtils.cpp.o
/home/pi/build/keepassxc-2.6.2/src/gui/osutils/nixutils/NixUtils.cpp:30:42: fatal error: qpa/qplatformnativeinterface.h: Datei oder Verzeichnis nicht gefunden
 #include <qpa/qplatformnativeinterface.h>
                                          ^
compilation terminated.
src/CMakeFiles/keepassx_core.dir/build.make:2334: die Regel für Ziel „src/CMakeFiles/keepassx_core.dir/gui/osutils/nixutils/NixUtils.cpp.o“ scheiterte
make[2]: *** [src/CMakeFiles/keepassx_core.dir/gui/osutils/nixutils/NixUtils.cpp.o] Fehler 1
make[2]: *** Es wird auf noch nicht beendete Prozesse gewartet...
CMakeFiles/Makefile2:205: die Regel für Ziel „src/CMakeFiles/keepassx_core.dir/all“ scheiterte
make[1]: *** [src/CMakeFiles/keepassx_core.dir/all] Fehler 2
Makefile:140: die Regel für Ziel „all“ scheiterte
make: *** [all] Fehler 2`

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. cmake configuration:
`cmake -DWITH_XC_AUTOTYPE=ON -DWITH_XC_YUBIKEY=OFF -DWITH_XC_BROWSER=ON -DWITH_XC_NETWORKING=ON -DWITH_XC_SSHAGENT=OFF -DWITH_XC_TOUCHID=OFF -DWITH_XC_KEESHARE=OFF -DWITH_XC_KEESHARE_SECURE=OFF -DWITH_XC_UPDATECHECK=ON -DWITH_TESTS=ON -DWITH_GUI_TESTS=ON -DWITH_ASAN=ON -DWITH_DEV_BUILD=OFF -DWITH_COVERAGE=OFF -DWITH_APP_BUNDLE=OFF -DKEEPASSXC_BUILD_TYPE=Snapshot -DKEEPASSXC_DIST_TYPE=Other -DOVERRIDE_VERSION=[1.6.2] ..`
the full cmake output is attached: [cmake_output.txt](https://github.com/keepassxreboot/keepassxc/files/5469454/cmake_output.txt)
2. make command: `make -j2`
3. compiling will fail at the file `./keepassxc-2.6.2/src/gui/osutils/nixutils`

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Compiling should complete without errors and result in an executable binary.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Compiling fails.

## Context
[NOTE]: # ( Give us any additional information you may have. )
Versions of dependencies and tools:
- GNU Make 4.1
- cmake 3.13.2
- g++ 6.3.0 (20170516)
- Asciidoctor 1.5.4
- Qt 5.7.1 (qtbase5-dev, qttools5-dev, libqt5x11extras5, libqt5core5a, libqt5dbus5, libqt5gui5, libqt5network5, libqt5widgets5)
- libgcrypt20 1.7.6
- zlib1g and zlib1g-dev 1.2.8
- libmicrohttpd12 and libmicrohttpd-dev 0.9.51
- libxi6 and libxi-dev 1.7.9
- libxtst6 and libxtst-dev 1.2.3
- libsodium23 1.0.17
- libargon2-0 and libargon2-0-dev 0~20160821-1
- qrencode and libqrencode3 3.4.4
- libzxcvbn0 2.0

KeePassXC - 2.6.2
Revision: e9b9582

[NOTE]: # ( Pick choices based on your environment )
Operating System: Debian GNU/Linux 9
Desktop Env: LXDE
Windowing System: X11
Architecture: 32-bit arm hard-float (Raspberry Pi 2B)

**Comment by droidmonkey** [comment]
You are missing the qt5-base-private-devel package.
