### ISSUE TITLE
Extra left padding in Login field when viewing/editing one entry

### ISSUE THREAD

**Issue by l0f4r0** [keepassxreboot/keepassxc#5646]
## Overview
There is an extra left padding in the Login field when one wants to view/edit a specific entry (global view is not affected).
So it looks like the login contains 1 or 2 leading space(s) because the other fields don't have the same behavior.
It can be misleading (the login is intact though).

## Steps to Reproduce
1. Create a new entry, start to fill in the Login field and you can see the left padding.
2. Or, edit any existing entry and you will notice the left padding in the Login field.

## Expected Behavior
No left padding in Login field.

## Actual Behavior
Left padding in Login field.

## Context
KeePassXC - Version 2.6.2
Revision: e9b9582
Canal: Snap
Qt 5.9.5
Desktop Env: Xfce
No debug mode
OS: Debian 10
Architecture: x86_64
Kernel: linux 5.8.0-0.bpo.2-amd64

**Comment by droidmonkey** [comment]
Duplicate #5601
