### ISSUE TITLE
Attachments damaged

### ISSUE THREAD

**Issue by phinken** [keepassxreboot/keepassxc#5647]
Attachments (various file formats) will not open and an error popup is shown instead. This does not apply to attachments I have added after I discovered the problem, so my files were corrupted at some point.

## Steps to Reproduce
Can't be reproduced as it does not apply to newly added attachments and I don't know what corrupted my database.

## Expected Behavior
The file opens in the appropriate default application when I

a) double click an attachment in the list of attachments under 'Advanced' tab of an entry.

b) save an attachment from the database to any directory and attempt to open it from my file manager.

## Actual Behavior
When trying to open any attachment from my database (either directly from the keepassXC GUI or after saving it to any directory), I get an error popup and the file does not open. Here is an example of error message "Could not open file:///tmp/vLQqvr.FILENAME.pdf." This applies to all kinds of file formats regardless of application.

However: When I add new attachments to any of my entries, they open just like expected.
In other words, all attachments in my database got corrupted at some point. I also tried to open the same database in a different application on a different device (KeePassDX on Android) and the files will still not open.

## Context
I used to store my .kdbx-file in a local directory or in a Dropbox folder for years and attachments always worked well. Recently I moved my .kdbx to a local directory that is set up to sync with my phone using Syncthing, and I discovered the problem a short while after that. However, it is a long time since I last tried to open any of my attachments, so the problem may have occurred a while ago.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.6.1
Revision: 9a35bba

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: XFCE
Windowing System: X11

**Comment by phinken** [comment]
Sorry, accidentally clicked the close issue button.

**Comment by phinken** [comment]
I have done some more testing with an old backup of my .kdbx file, and while the attachments open, they do not necessarily open the right file. More precisely, the file that opens has the name I expect, but the actual file is another one. For eksampel: I open something that was supposed to be my insurance certificate called travel_insurance.pdf, but the document instead shows my job contract, which was originally attached to an entirely different entry.

**Comment by droidmonkey** [comment]
Have you ever used any other keepass program besides keepassxc? There was a nasty bug in one of the alt brands that corrupted attachments.

**Comment by phinken** [comment]
Do you know the app with the bug? Now that you mention it, I recall using an iOS app called KeePass Touch for a while a few months back. I have also used a couple of Android apps on and off, Keepass2Android and KeePassDX, but I am almost confident my attachments have always been just fine while using those. I've probably reported the bug to the wrong project then, but it's good to kniw what to steer away from in the future.

**Comment by droidmonkey** [comment]
It was KeePass Touch: https://github.com/keepassxreboot/keepassxc/issues/3048#issuecomment-494381431
