### ISSUE TITLE
Ubuntu Mate Desktop - systray icon displaying "missing icon" icon

### ISSUE THREAD

**Issue by pdev77** [keepassxreboot/keepassxc#5649]
## Overview
Ubuntu mate desktop with keepassxc snap - systray icon broken

## Steps to Reproduce
1. All ubuntu updates installed to date
2. Latest keepassxc snap installed
3. Show systray icon set to true

## Expected Behavior
Keepassxc logo shows in systray

## Actual Behavior
systray shows as rectangle with red stop sign inside
Note: see these errors on startup
`Gtk-Message: 10:09:01.920: Failed to load module "appmenu-gtk-module"`
`Gtk-Message: 10:09:01.920: Failed to load module "canberra-gtk-module"`

## Context
Was not like this on xubuntu - worked fine

Ubuntu 20.04.1 LTS with Mate Desktop 1.24.0
keepassxc            2.6.2             1136   latest/stable    keepassxreboot  -

KeePassXC - Version 2.6.2
Revision: e9b9582
Distribution: Snap

Qt 5.9.5
Debugging mode is disabled.

Operating system: Ubuntu Core 18
CPU architecture: x86_64
Kernel: linux 5.4.0-52-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.1

Operating System: Linux
Desktop Env: Mate
Windowing System: X11

**Comment by droidmonkey** [comment]
Nothing we can do about this, have you tried installing the missing packages that are mentioned?

**Comment by pdev77** [comment]
The packages are present!

**Comment by pdev77** [comment]
![Screenshot at 2020-11-01 14-16-57](https://user-images.githubusercontent.com/17301585/97805273-fd700000-1c4c-11eb-8b40-846855b13ce7.png)
Will be a shame if this is non-fixable - as this is otherwise a splendid application !

**Comment by droidmonkey** [comment]
Recommend just using our AppImage instead.

**Comment by pdev77** [comment]
OK - same issue with official AppImage - except if you change the icon to "Monochrome (Dark)" - you get a keepass icon in the systray (but still 'red stop' sign for default/monochrome(light)/colourful)

**Comment by droidmonkey** [comment]
Directly related to #5130 then. There is not much we can do, we tried a lot of different fixes.
