### ISSUE TITLE
Browser Integration: "Additional URL" cannot consist of only an IP address

### ISSUE THREAD

**Issue by schlimmchen** [keepassxreboot/keepassxc#5651]
It is impossible to add an additional HTTP-URL for the Browser Integration feature that contains only an IP address.

Trying to do so, e.g., clicking "Add", then typing "http://192.168.22.125" and pressing enter, leads to an "<empty URL>" placeholder value.

Interestingly, this does NOT happen with "https://192.168.22.125" (HTTP**S**) and does NOT happen with "http://192.168.22.125/" (slash at the end).

KeePassXC - Version 2.6.2
Revision: e9b9582

Qt 5.11.3
Debugging mode is disabled.

Operating system: Debian GNU/Linux 10 (buster)
CPU architecture: x86_64
Kernel: linux 5.8.0-0.bpo.2-amd64

Enabled extensions:
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)

Cryptographic libraries:
 libgcrypt 1.8.4

Operating System: Debian 10.6

**Comment by droidmonkey** [comment]
There's a couple improvements needed for this feature, it's also impossible to bulk delete urls.

**Comment by droidmonkey** [comment]
This is no longer a problem.
