### ISSUE TITLE
Ubuntu 20.10

### ISSUE THREAD

**Issue by yegnal** [keepassxreboot/keepassxc#5652]
Greetings;

Ubuntu 20.10 with file residing on google drive.

In Ubuntu 20.10, I cannot save changes unless I disable:
     Safely save database files (disable if experiencing problems with Dropbox, etc.)

The program, if that option is disabled, ultimately saves but renames the database file to what I guessing is the temporary file name (moderately long random looking string of characters).  That in turn doesn't allow me to access the file from another platform, possibly due to using password+key file imported to internal folder, but haven't tested it otherwise.  I truly desire the key file imported to internal folder.  

It's not the biggest issue.  I still have cross platform access, but if I'm going to add or edit anything I have to use Windows or Android version.

**Comment by droidmonkey** [comment]
Duplicate #4856

**Comment by yegnal** [comment]
P.S.

When this first occurred, I renamed the file back to it's original human readable name, and had to access the file again on Android but, I also had to re-import the key file which doesn't stay on my Android phone for security.
