### ISSUE TITLE
Can not click on Open DB button or option

### ISSUE THREAD

**Issue by jglopezre** [keepassxreboot/keepassxc#5655]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
Issue presented from last upgrade on Gnome 3.36 and QT 5.15, can not open a DB file clicking on Open DB button.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Open program 
2. click on Open Database Button or /Data Bases/Open DB option from tool bar
3. 

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Before the last actualization, the program did open the window from user could select file to open

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
When somebody click on Open DB button, nothing happens. 

## Context
[NOTE]: # ( Give us any additional information you may have. )
But, they can open recently opened DB when it is in the recently used files register. In the same way, if a person select a DB file from file explorer and select open it with Keepass XC option, the program shows main screen, but, show a error "No such file or directory" either.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Versión 2.6.1
Revision: 9a35bba

[NOTE]: # ( Pick choices based on your environment )
Operating System: Manjaro Linux
Desktop Env: Gnome 3.36.6
Windowing System: X11

**Comment by droidmonkey** [comment]
Are you running the snap version?

**Comment by jglopezre** [comment]
Greetings.
No, I installed official repository version, applying sudo pacman -S keepassxc, when applied last upgrade to my system, apeared that issue, i couldn't remember if keepassXC was upgraded at that moment too. In other computer with manjaro at same version, but whit LxQT as desktop environment, keepasXC is working normally.
________________________________
De: Jonathan White <notifications@github.com>
Enviado: lunes, 2 de noviembre de 2020 3:47 p. m.
Para: keepassxreboot/keepassxc <keepassxc@noreply.github.com>
Cc: jglopezre <javierlopez_85@hotmail.com>; Author <author@noreply.github.com>
Asunto: Re: [keepassxreboot/keepassxc] Can not click on Open DB button or option (#5655)


Are you running the snap version?

**Comment by droidmonkey** [comment]
The file open dialog is not actually owned by keepassxc, it is provided by your desktop environment (Gnome in this case) and setup by Qt. There must be something broken in your distribution install to cause this. Check your packages.
