### ISSUE TITLE
Flatpak version of keepassxc - can't connect to DB from browser

### ISSUE THREAD

**Issue by vwalek** [keepassxreboot/keepassxc#5656]
When installing the flatpak version of the KeepassXC, the integration with the browser doesn't work. The Connection to the DB can't be established. 
The problem is that flatpak version doesn't have proxy binary in the defined location in the `~/.config/google-chrome/NativeMessagingHosts/org.keepassxc.keepassxc_browser.json`. 

## Expected Behavior
It needs workaround as the problem is not in both solutions.

## Current Behavior
Won't connect to the DB. Doesn't show any error.

## Possible Solution
The workaround is to configure the link from the `keepassxc-proxy` binary to the `/usr/bin/keepassxc-proxy`.
~~~
# sudo ln -s /var/lib/flatpak/app/org.keepassxc.KeePassXC/current/active/files/bin/keepassxc-proxy /usr/bin/keepassxc-proxy
~~~

## Steps to Reproduce (for bugs)
1. Install flatpak version of keepassxc on Linux.
2. Check if you can connect to the DB.
3. Run the workaround above.
4. Restart keepassxc and browser

## Debug info

KeePassXC - 2.6.2
KeePassXC-Browser Version: 1.7.1
Operating system: Linux - Fedora 30
Browser: Chrome

It would be good to add to README link to the flatpak.

**Comment by varjolintu** [comment]
Flatpak is not offically supported. See: https://github.com/flathub/org.keepassxc.KeePassXC/issues/29

**Comment by vwalek** [comment]
Will do. Thx

**Comment by droidmonkey** [comment]
Oh I am keeping this open because I really need to take over the flatpak

**Comment by Tau512** [comment]
> Oh I am keeping this open because I really need to take over the flatpak

Did you find time to take over?
A bit OT from this issue but the current flatpak version is 2.6.4 from Febuary (v2.6.6 is current latest) so would be beneficial for multiple reasons if you could find the time.

**Comment by droidmonkey** [comment]
Fixed with latest Flatpak distribution on Flathub
