### ISSUE TITLE
Classic theme - Top border of focus ring gets cut off in Title input box

### ISSUE THREAD

**Issue by solidcolour** [keepassxreboot/keepassxc#5657]
The bug has been existed for a while in previous versions too.
KeepassXC 2.6.2
MacOS 10.15.7

<img width="842" alt="screenshot" src="https://user-images.githubusercontent.com/1742906/97948021-2c759700-1d5d-11eb-8513-f2b6f0a1e207.png">

**Comment by droidmonkey** [comment]
I think this is fixed, need to look into it

**Comment by solidcolour** [comment]
I just tested with v2.7.1, it was not fixed.

**Comment by phoerious** [comment]
I don't think we will fix this anymore. The next major version will get a totally new edit UI anyway.
