### ISSUE TITLE
Cannot move entry to other group

### ISSUE THREAD

**Issue by b-a0** [keepassxreboot/keepassxc#5659]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
I cannot move entries from one group to the other. I remember this was possible before via drag and drop, but now I can't seem to drag any entries.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Open database with at least two groups
2. Open group 1
3. Try to drag an entry from group 1 to group 2

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
The entry "floats" with the cursor and moves from group 1 to group 2

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Nothing happens. The entry stays in place and does not "float" when dragged, it simply stays where it is.

## Context
[NOTE]: # ( Give us any additional information you may have. )

macOS 10.15.17
MacBook Pro mid 2015

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.2
Revision: e9b9582

Qt 5.15.1
Debugging mode is disabled.

Operating system: macOS 10.15
CPU architecture: x86_64
Kernel: darwin 19.6.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
 libgcrypt 1.8.6

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS

**Comment by phoerious** [comment]
Dulicate of #5636
