### ISSUE TITLE
Show several TOTP codes around now, to log into some bad-setting server

### ISSUE THREAD

**Issue by garywill** [keepassxreboot/keepassxc#5661]
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
Sometimes my computer or the server's time is not 100% correct. And the bad server's TOTP setting doesn't tolerate inaccurate time.
Every time I have to set my computer's time 1 minute by 1 minute forward and back, to log into that server.

This is how I do for now to simplify the job:
```bash
#!/bin/bash

function generate_totp_with_base32secret_and_time()
{
    BASE32SECRET="$1"
    T="$2"
    oathtool -b --totp  $BASE32SECRET -N @${T}
}

array=(
"now - 300 seconds"
"now - 270 seconds"
"now - 240 seconds"
"now - 210 seconds"
"now - 180 seconds"
"now - 150 seconds"
"now - 120 seconds"
"now - 90 seconds"
"now - 60 seconds"
"now - 30 seconds"
"now"
"now + 30 seconds"
"now + 60 seconds"
"now + 90 seconds"
"now + 120 seconds"
"now + 150 seconds"
"now + 180 seconds"
"now + 210 seconds"
"now + 240 seconds"
"now + 270 seconds"
"now + 300 seconds"
)

secret="$1"

for (( i=0;i<${#array[@]};i++ )); do
    echo -n "${array[$i]}   "
    generate_totp_with_base32secret_and_time $secret $(date +%s -d "${array[$i]}")
done
```
I hope **KeepassXC has a feature showing more than one TOTP code** like that

**Comment by droidmonkey** [comment]
Accurate time is essential to a lot of functions. Use ntp. We will not support more than the current totp.
