### ISSUE TITLE
Flatpak Keepassxc is causing the Deepin V20 1003 "system" to crash when executed.

### ISSUE THREAD

**Issue by serial02** [keepassxreboot/keepassxc#5665]
HEllo Team Keepassxc

I don't know if the flatpak team is the same, so I would like to know if anyone can help me on this issue:

Flatpak Keepassxc is causing the Deepin V20 1003 "system" to crash when executed.

The PC can only be turned off using the disconnect button after this lockout.
I believe it is raising the CPU to 100%.

I just formatted an HD with Deepin V20 updated with version 1003 precisely because of this problem.
I performed a clean installation and installed one application at a time until I found out who was causing this crash.

I only removed the keepassxc package (flatpak removes org.keepassxc.KeePassXC), but I left the KDE aggregates.
If need to remove KDE as well, tell me the command.

https://github.com/flathub/org.keepassxc.KeePassXC/issues/72

Thank

Serial02

**Comment by droidmonkey** [comment]
Duplicate
