### ISSUE TITLE
Windows Memory Error

### ISSUE THREAD

**Issue by tinokorth** [keepassxreboot/keepassxc#5666]
## Overview
On my PC at work and my laptop at home I get windows error messages that KeePassXC tries to allocate an unknown memory address (see screenshot).

## Steps to Reproduce

There is no way to really reproduce the problem. Sometimes the problems occurs 3 times a day and sometimes KPXC works fine for a few days.

## Actual Behavior
Windows shows an error window that KeePassXc.exe tried to allocate an address that is not available:

![image](https://user-images.githubusercontent.com/46132772/98276316-143c8c80-1f96-11eb-82db-e62926fe5432.png)

[NOTE]: # ( Paste debug info from Help → About here )

KeePassXC - Version 2.6.2
Revision: e9b9582

Qt 5.15.1
Diagnosemodus ist deaktiviert.

Betriebssystem: Windows 10 Version 2004
CPU-Architektur: x86_64
Kernel: winnt 10.0.19041

Aktivierte Erweiterungen:
- Auto-Type
- Browser-Integration
- SSH-Agent
- KeeShare (bestätigtes und unbestätigtes Teilen)
- YubiKey

Kryptographische Bibliotheken:
 libgcrypt 1.8.6

**Comment by droidmonkey** [comment]
Are you using the browser extension when this happens?

**Comment by ninjaneteng** [comment]
I just opened bug 5675, and then saw yours. Is your situation the same? Read through my bug and see if it fits your situation also.

**Comment by ncaos** [comment]
I can only imagine we're all having the same issue for many weeks/versions now. It is not fixed in the latest extension version either (1.7.3). I'm using Vivaldi but I'm sure it's affecting all Chrome users in general. Not sure if it's affecting Firefox users.

It is easily replicated on Google's shitty login pages. It will happen when the extension attempts to get the data, automatically or manually.

**Comment by droidmonkey** [comment]
This has nothing to do with the extension, its the application side.

**Comment by maartenmachiels** [comment]
Got the exact same issue here... The issue persists in Firefox and in Chrome. Thanks for looking into this and thanks for your great reboot of this software.
![image](https://user-images.githubusercontent.com/3584586/98590357-f8572480-22ce-11eb-9740-14446093e5a7.png)

**Comment by tinokorth** [comment]
> I can only imagine we're all having the same issue for many weeks/versions now. It is not fixed in the latest extension version either (1.7.3). I'm using Vivaldi but I'm sure it's affecting all Chrome users in general. Not sure if it's affecting Firefox users.
> 
> For me, it is easily replicated on Google's shitty login pages. It will happen when the extension attempts to get the data, automatically or manually.
> 
> Seems likely it's #5596, or similar.

Yes, it was the same issue. Sorry - I did not found this issue so I opened a new issue.
