### ISSUE TITLE
Incomplete import of 1Password OPVault

### ISSUE THREAD

**Issue by kiwiz** [keepassxreboot/keepassxc#5669]
## Overview
KeepassXC doesn't appear to fully import an `opvault` file that was created via 1Password version 4. Specifically, the following fields are not imported:
- Attributes
- Attachments
- Password History

## Steps to Reproduce
1. Load the attached opvault, which has an attribute of `test`, an attachment called `test` and a historical password of `test`.
2. Observe the error log.

## Expected Behavior
- All of the above fields are loaded.

## Actual Behavior
- The file is partially imported

## Context
It appears that attachments aren't being extracted properly because the OPVault file fails the HMAC check. Commenting out the return [here](https://github.com/keepassxreboot/keepassxc/blob/develop/src/format/OpVaultReaderAttachments.cpp#L107) appears to allow the rest of the code to run correctly and to import the attachments.

Not sure about the other two field types, but it seems like they're simply not supported? If there is interest, I can investigate that and submit a PR.

[test.opvault.zip](https://github.com/keepassxreboot/keepassxc/files/5498891/test.opvault.zip)

Debug info:
```
KeePassXC - Version 2.7.0-snapshot
Build Type: Snapshot
Revision: 91dea9c

Qt 5.12.8
Debugging mode is disabled.

Operating system: Ubuntu 20.04.1 LTS
CPU architecture: x86_64
Kernel: linux 5.4.0-52-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.5
```
Operating System: Linux
Desktop Env: XFCE
Windowing System: X11

**Comment by droidmonkey** [comment]
We support 1Password 7 or higher only.

**Comment by SubstituteDoll** [comment]
Please forgive me for necroing this old dead thread, but I think you dismissed this case without having given it some investigative consideration. And please understand that I am doing this only after 7 months of suffering in silence trying many alternatives. 

See, I **am** on 1Password 7. It doesn't work. I can assure you at least that the history does **not** get imported at all. OPVault **is** a 1Pass 7 standard. What was the reason for shooting down pull request #5670 again? 

Please see [this](https://github.com/keepassxreboot/keepassxc/issues/10345#issuecomment-2229588650) from #10345 as well.
