### ISSUE TITLE
Keepassxc Bug

### ISSUE THREAD

**Issue by TheJester00** [keepassxreboot/keepassxc#5671]
When I open the software from my computer it says that it "Doesn't answer" so I can't access to my passwords. Can you help me? I tried to repair the software and downloaded it again but none of that worked.

**Comment by droidmonkey** [comment]
You need to provide way more information than that. Use our bug report template for guidance

**Comment by TheJester00** [comment]
How can I give you more information if that is all the information there is? I cannot access to KeePassXC because the software doesn't answer. It is just rolling the blue circle and I cannot press anything
![17571120639878](https://user-images.githubusercontent.com/74042099/98361122-a34bb200-2033-11eb-9f13-10b04d05088c.png)

Here is what it gives me. Nothing else and this started today. Yesterday it worked fine and I haven't done any changes to my computer.

**Comment by droidmonkey** [comment]
Reinstall, I assume you are using windows 10...

**Comment by TheJester00** [comment]
Well, as I said in my first post that I tried to repair it and install it again, didn't work. And yes I am using w10

**Comment by droidmonkey** [comment]
"Yesterday it worked fine" implies something else on your computer changed that is interfering with the program.

**Comment by TheJester00** [comment]
Well i have no idea what could it be. Once again I uninstalled it and downloaded it again. It made no change it still says "Not responding". Anyideas how to fix this stuff?

**Comment by droidmonkey** [comment]
Try using our portable version

**Comment by TheJester00** [comment]
Well now the portable version works but I cannot get the passwords from the file. Any tips with that one?

**Comment by droidmonkey** [comment]
What do you mean?

**Comment by TheJester00** [comment]
Yeah i got the portable version working but i cannot use the file where my passwords are, the .kdbx file

**Comment by droidmonkey** [comment]
What do you mean you cannot use the kdbx file? Be very specifically

**Comment by TheJester00** [comment]
Okay so I downloaded the portable version of keepassxc. Then i tried to open the file where my passwords are. I put the correct password and it opens up, but there are no passwords. It is totally blank file when opened.

**Comment by droidmonkey** [comment]
Then there are no passwords in that file.

**Comment by TheJester00** [comment]
Okay, I had to search through my whole computer to find that file. Thank you for your help and have a good day!
