### ISSUE TITLE
System-notification instead of program-window when no entry can be found for auto-type

### ISSUE THREAD

**Issue by beatschubser** [keepassxreboot/keepassxc#5673]
When using auto-type on a site that KeepassXC doesn't know, a window pops up that needs to be dismissed before you can access the KeepassXC main window again. It would be better to have the notification on system level, e.g. the Windows 10 notification center, and the option to disable the message completely.

**Comment by droidmonkey** [comment]
This will be addressed in next version to allow you to search for an entry instead.
