### ISSUE TITLE
Amazon.de search box suddenly identified as login field - Firefox 82.0.2

### ISSUE THREAD

**Issue by r0ckarong** [keepassxreboot/keepassxc#5674]
## Overview
Not sure when this started but lately when I try to use the Amazon search box on their website, KPXC suggest entering my username. When I hit Enter to confirm my search term, it insteads enters my email address in the search field. I'm using Firefox 82.0.2 and KPXC 2.6.2

## Steps to Reproduce

1. Create entry for Amazon in KPXC database
2. Install browser extension
3. Visist website
4. Log in via browser extension
5. Click or start to type in search field

## Expected Behavior

The extension should detect that the field is a search input field and not a login field and NOT suggest login credentials.

## Actual Behavior

The field is somehow detected as a login field and the username suggestion (if enabled) pops up and replaces the search term on hitting the Enter key.

## Context

I think this started in Firefox 82.0.2 and when Amazon switched on their automatic 2FA. I don't really know how to debug this.

## Debug Info
KeePassXC - Version 2.6.2
Revision: e9b9582

Qt 5.15.1
Debugging mode is disabled.

Operating system: openSUSE Tumbleweed
CPU architecture: x86_64
Kernel: linux 5.9.1-1-default

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (only unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.7

Operating System: openSUSE Tumbleweed
Desktop Env: KDE
Windowing System: Wayland

**Comment by droidmonkey** [comment]
Fixed for next browser extension version
