### ISSUE TITLE
2.6.2 limitation of entries for same URL

### ISSUE THREAD

**Issue by ninjaneteng** [keepassxreboot/keepassxc#5675]
## Overview
Manage multiple G-Suite accounts all using the https://accounts.google.com login URL. 2.6.2 has a limit of 16 entries to the same URL before it crashes with a memory fault error

![image](https://user-images.githubusercontent.com/73964161/98398962-9bc9e000-2016-11eb-8097-b9d831fcf53c.png)

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. create a new database (just for giggles and grins and eliminate any DB issues)
2. create 16 entries for a gmail/g-suite account, but point the url to https://accounts.google.com
3. open URL https://accounts.google.com, you should view all 16 entries available to select from the account list
4. create a 17th entry in the keepass database as above pointing to accounts.google.com
5. open URL https://accounts.google.com, program crashes with a memory fault error

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
I should be able to access this site, or any other site, for any number of accounts listing the same URL. Under 2.6.1 I am able to list the 20+ odd accounts available that I manage.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Under 2.6.2, having the browser communicate with the keepass database to read in the 20+ odd accounts I have defined in my database causes an immediate application crash of keepassXC with a memory error. Under 2.6.1, it lists all my accounts without an issue.

## Context
[NOTE]: # ( Give us any additional information you may have. )
Upon first observing this problem, I thought maybe the database was damaged in some way. So I created an entirely new database and created new entries all pointing at the same URL, and slowly upped the account number until I found where it failed. 16 accounts to the same URL seems to be the limit. Creation of a 17th causes the application to memory fault and crash out.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.2
Revision: e9b9582

[NOTE]: # ( Pick choices based on your environment )
Operating system: Windows 10 Version 2004
CPU architecture: x86_64
Kernel: winnt 10.0.19041

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.6

**Comment by droidmonkey** [comment]
Duplicate
