### ISSUE TITLE
Battlenet TOTP?

### ISSUE THREAD

**Issue by grravity** [keepassxreboot/keepassxc#5681]
Was curious if there is any way to add Battlenet (Blizzard game client) TOTP to Keepassxc?
It seems like they require their app similar to Steam, but I could be wrong.
This app of course just doesn't work on devices that don't have Google Services.

So I was wondering if there was a known way to get TOTP for Battlenet on Keepass?

**Comment by droidmonkey** [comment]
Duplicate #4936

**Comment by grravity** [comment]
Oh weird, I just searched for that yesterday and it didn't come up. My bad.

**Comment by droidmonkey** [comment]
This is not on our priority list
