### ISSUE TITLE
Add support for a backup Yubikey

### ISSUE THREAD

**Issue by seanthegeek** [keepassxreboot/keepassxc#5682]
## Summary
I have a primary Yubikey and a secondary Yubikey in case the primary one is lost, stolen, or damaged. Github, Google and other sites can be configured this way. KeepassXC currently only supports using one Yubikey, so if I loose access to that device, I'd loose access to my password database.

Please add an option for a secondary/backup Yubikey.

**Comment by droidmonkey** [comment]
You configure the second yubikey with the same challenge response settings as the first.
