### ISSUE TITLE
Exporting to CSV does not save custom fields

### ISSUE THREAD

**Issue by lsiden** [keepassxreboot/keepassxc#5685]
## Steps to Reproduce
1. Open existing database 
2. Find item with custom fields or add a custom field to an item
3. Export to CSV
4. Open with spreadsheet viewer/editor

## Expected Behavior
Expecting to see custom fields saved

## Actual Behavior
Custom fields and values are not saved.

## Context
KeePassXC - Version 2.6.2
Revision: e9b9582

Qt 5.15.1
Debugging mode is disabled.

Operating system: macOS 10.15
CPU architecture: x86_64
Kernel: darwin 19.6.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
 libgcrypt 1.8.6

Operating System: macOS Catalina

**Comment by droidmonkey** [comment]
Duplicate
