### ISSUE TITLE
Needs an option to compact database

### ISSUE THREAD

**Issue by lsiden** [keepassxreboot/keepassxc#5686]
## Summary
Would like an option to compact database to remove empty space.

## Context
When I first got started, I added an image to my new database. The size ballooned from 14K to over 1M. I removed the image, but ever since, the size has only grown. I would like to recompact it so that it remains lean.

One option might be to provide a "Compact Database" operation under the Database menu, or compact it automatically when saving it.

I recall a post where a user recommended exporting the database as CSV and re-importing it.  When I tried that, I noticed that the Export operation did not save any of the custom fields I added to other entries, such as backup codes, contact info, etc.  So this is not an acceptable workaround.

**Comment by phoerious** [comment]
There is no such thing as compacting a database. All data is payload data. What you need to do is delete your entry's history.

**Comment by lsiden** [comment]
For anyone else it might help: I was able to work around that by deleting all unneeded attachments setting history to 0, then saving.
