### ISSUE TITLE
Please Add password strength check option like keepass

### ISSUE THREAD

**Issue by Virtual-Github** [keepassxreboot/keepassxc#5687]
Hi Everyone,
I want to suggest a feature that is absent in KeepassXC. The feature is to check password strength of existing account in keepassXC
. As you see below keepass have it by named option quality but keepassXC dont have it.That is very helpful to check password strength that is imported from other password manager. I always have to check by manually typing. I hope you add feature in upcoming version.
![keepass](https://user-images.githubusercontent.com/72699730/98760437-4405ed00-23f9-11eb-938e-9db66ec2c54f.png)

![keepassxc](https://user-images.githubusercontent.com/72699730/98760666-c5f61600-23f9-11eb-8882-164b3dbe4ca9.png)

**Comment by droidmonkey** [comment]
Use the database reports to see all passwords that are below "good" in an instant.
