### ISSUE TITLE
Want to unlock? Provide a wrong password first!

### ISSUE THREAD

**Issue by seatedscribe** [keepassxreboot/keepassxc#569]
With a "**saved as**" DB (and **only in this case** so far), for a successful unlock I need to provide a wrong password first

## Steps to Reproduce

1. Database->Open database - locked with master password only, no key file
2. insert master password to unlock it
3. Database->Save database as - choose a new filename
4. Database->Change master key - choose a different (e.g. empty) password
5. Database->Save database
6. Close all databases
7. Open the "saved as" database
8. Insert correct password
9. "unable to open database"
9a. Repeat step 8 as long as you like
10. Insert a wrong password
11. "unable to open database"
12. Insert correct password
13. DB is unlocked correctly

@Vegan-us maybe related to your issue #313 ?

side effect: could be useful for plausible deniability! :smile: 

## Your Environment
KeePassXC - Version 2.1.4
Revision: 9f819061cd5019b5ab54d00b8bb5667a7f3e596a

Libraries:
- Qt 5.5.1
- libgcrypt 1.6.5

Operating system: Linux Mint 18
CPU architecture: x86_64
Kernel: linux 4.4.0-62-generic

Enabled extensions:
- Auto-Type

**Comment by droidmonkey** [comment]
Most interesting.... I like the plausible deniability hah

**Comment by TheZ3ro** [comment]
Can you make some test with the keepassxc-cli tool? Like `keepassxc-cli extract`

**Comment by seatedscribe** [comment]
Hmmm...
`keepassxc-cli extract` works fine!

**Comment by TheZ3ro** [comment]
So it's a bug in the UI. The low-level decryption is good

**Comment by seatedscribe** [comment]
Changing the master password with a _different_ one throws the issue away. By the way, does KXC make no operations if the new master password and the old one are the same? I mean, changing the master password with _the same old one_ holds the issue unvaried

**Comment by seatedscribe** [comment]
Closing this in favour of #570
