### ISSUE TITLE
Global Hotkey does not work - linux

### ISSUE THREAD

**Issue by GFNIAE** [keepassxreboot/keepassxc#5690]
Hello,
I run keepassxc which autostarts at boot, on MX-Fluxbox Linux. Keepassxc starts and opens its window opens and I can unlock my database, and then close the window which is reduced in the systemtray. Unfortunately after that the global hotkey does not work, nothing happens when I type it on windows.

## Steps to Reproduce
MX-Fluxbox desktop. Keepassxc installed and updated, launched at startup.

## Expected Behavior
Hotkey on right windows should auto-type planned sequences.

## Actual Behavior
Hotkey does not auto-type anything.
I can re-activate the correct behaviour by setting a new (or the same) hotkey in keepass options. Once re-set, the auto-type feature works again.

## Context
All packages updated.
Keepass works well with the same database. It does not use its own hotkey : it relies on desktop hotkeys, and you can use the keepass --auto-type command linked to the hotkey you set in your desktop system.
Keepassxc seems not to be able to tell the desktop to wait for its internal hotkey, until you re-set the hotkey during the session. An command line option like the keepass on could make the job for me and could be a solution.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.6.2

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: MX (Debian based) with Fluxbox windows manager
Windowing System: X11

**Comment by droidmonkey** [comment]
Delay the start of keepassxc. This has been brought up before and its basically because the program starts before you cab register shortcuts with XKB. You can do the delay with a sleep command in the startup sequence.

**Comment by GFNIAE** [comment]
OK, you're right, it works.
Thanks !
