### ISSUE TITLE
[Ubuntu] Keepass not minimising to tray

### ISSUE THREAD

**Issue by dipunm** [keepassxreboot/keepassxc#5691]
## Overview
When enabling autostart on boot, Keepass will not minimise or close into the tray. Instead, it goes into the dock.
Closing and re-opening fixes this.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Go to settings and enable "Automatically launch KeePassXC at system startup.
2. Also enable "Show a system tray icon" and "Hide window to system tray when minimised"
3. Restart
4. Keepass launches after login
5. Close Keepass.

## Expected Behavior
Keepass should minimise to tray

## Actual Behavior
Keepass minimises to dock.

## Context
I am using Ubuntu Groovy and installed keepassxc via apt-get using deb http://ppa.launchpad.net/phoerious/keepassxc/ubuntu groovy main

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.2
Revision: e9b9582

Qt 5.14.2
Debugging mode is disabled.

Operating system: Ubuntu 20.10
CPU architecture: x86_64
Kernel: linux 5.8.0-26-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.5

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: Gnome
Windowing System: X11

**Comment by Androphin** [comment]
I can confirm the same behavior on Gentoo with KDE too.

**Comment by droidmonkey** [comment]
Given the linked issue to BirdTray, this is not on us.

**Comment by dipunm** [comment]
Some extra information: I was able to work around this issue by delaying the startup. I followed this tutorial: https://www.linuxuprising.com/2020/11/how-to-launch-startup-applications-with.html


### Edit the following file:
```
nano ~/.config/autostart/org.keepassxc.KeePassXC.desktop
```
### Add the following line to the bottom of the file:
```
X-GNOME-Autostart-Delay=5
```

**Comment by droidmonkey** [comment]
Nice! We can add that to the startup deployment
