### ISSUE TITLE
History entries got created in a way its not always helpful

### ISSUE THREAD

**Issue by lex2k0** [keepassxreboot/keepassxc#5695]
Creating history entries if something is changed on an entry is absolutly useful and should be continued.
But I recognized two behaviours where I would not create an history entry.

1. If I open an entry and do not change anything and click on ok to close the entry the "ok" will cause KeepassXC to create a history entry. Means an entry without any changes done thus that entry would be somehow confusing if I need to search for changes done sometime in the future and would see many duplicates.

2. Sometime I am working in a way were I want to remove a history entry, but everything else is staying the same. But also such a change or maybe due to the problem under point 1 a new history entry is created. I would understand that history entry to be created if you could see the history entries also if you open older versions of the entry. But the older versions of an entry do not show the point for the history entries valid for that older version.
This means for me that I would like to have a behavior that no history entry is created if the user only changes something in the history entries but the rest of the entry is the same.
This behavior is comparable to the behavior available in the Keepass-program.

Hopefully those two points are good described. Otherwise please let me know.

Kind regards
Alexander

**Comment by droidmonkey** [comment]
I cannot replicate this at all. Opening an entry and pressing OK does NOT create a new history item. What version are you using?

**Comment by lex2k0** [comment]
Hi there,

oh, damn. Not good if this is not reproducable. I also see that as a tricky thing.
I am using version 2.6.2.

Attached the screenshots of the example.
[sample.pdf](https://github.com/keepassxreboot/keepassxc/files/5536189/sample.pdf)
Steps done:
1. Select an entry
2. Open it
3. Navigate (if possible) to the history entries. In the example no history entry was present.
4. Click on ok
5. Reopen the entry and navigate to the history entries to show that a new history entry is created.

Whats maybe interesting in that behavior.
If I remove that created history entry after it was created clicking on apply to save it and then on ok I am for sure in the list of entries.
If I now reopen the entry and click on ok then no change is made.

Means there are circumstances where the entry is created, but there are also circumstances where it is not created.

If it helps I could also make a remote session with somebody of you.

Kind regards
Alexander

**Comment by droidmonkey** [comment]
Does this happen for a brand new entry you create?

**Comment by lex2k0** [comment]
Yes, it does.
I just created a new one entering title "testentry" and adding notes "hello again".
Stored that using "Ok" and opened it again. No history entry was there, which is right.
Clicked "Ok" again and then reopened it and then I had a history entry.

**Comment by droidmonkey** [comment]
Is your apply button always enabled? That's an indicator that pressing ok will create a new record. If you don't go to the history page, does a new history item get created?

**Comment by lex2k0** [comment]
No, the apply button is only active if I change something. Just opening the entry and navigating though different pages leaves the apply button disabled.
A history entry is also created without navigating to the history section.

**Comment by droidmonkey** [comment]
Ok this helps narrow down a code problem

**Comment by Androphin** [comment]
I have the same issue. After the update to the new KeepassXC version it seems the history entries are not read from the Keepassrc config file anymore. Also customizations like what columns to show aren't saved.

KeePassXC - Version 2.6.1
Revision: 9a35bba
Qt 5.15.1
Diagnosemode deaktivated.
Betriebssystem: Gentoo/Linux
CPU-Architektur: x86_64
Kernel: linux 5.8.1-gentoo-x86_64
Activated extensions:
- Auto-Type
- Browser-Integration
- SSH-Agent
- Secret-Service-Integration
Cryptographic lib:
 libgcrypt 1.8.6

**Comment by droidmonkey** [comment]
I still cannot find a fault on this one.

**Comment by lex2k0** [comment]
@droidmonkey. Have you found something in the meanwhile?
Because the problem is still there.
Maybe you want to have a remote session to see the topic? Or something else?

**Comment by phoerious** [comment]
History is part of the database and has never been read from the config file.
