### ISSUE TITLE
A way to add an email adress for every new entry

### ISSUE THREAD

**Issue by Toadfield** [keepassxreboot/keepassxc#5696]
## Summary
I want an extra column for email adresses when add a new entry.
I also want a new button up here to fastly copy it:https://i.imgur.com/bdhCuR1.png

## Examples
A new column in here somewhere:https://i.imgur.com/1rlVbgh.png
And a new button at the top as mentioned in "Summary"

## Context
I want that because I use different email adresses for different sites and want an overview.

**Comment by droidmonkey** [comment]
Your requested is covered by #863
