### ISSUE TITLE
Changing tab at the very moment current one unclocks - unlocks target database

### ISSUE THREAD

**Issue by furai** [keepassxreboot/keepassxc#5699]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
Switching tab at the right moment unlocks other database. 

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Freshly start keepassxc.
2. Start unlocking first database.
3. Wait till it's about to unlock.
4. Switch to other tab with locked database at the very time the first unlocks. (I think I've used ctrl+tab to switch to the other.)
5. Both databases get unlocked without providing password for the 2nd one.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
2nd database should have stayed locked.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
2nd database got unlocked.

## Context
[NOTE]: # ( Give us any additional information you may have. )
I've noticed this bug just a second ago. I don't recall opening or at all typing in a password for the 2nd database. (Though that might have happened, I'm dealing with too many things at once.) First one is protected with simple password, the other with rather long one with additional file on disk as a key (it was prefilled). I haven't been able to reproduce it again as the timing here is crucial.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.2
Revision: e9b9582

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: Gnome
Windowing System: X11

**Comment by phoerious** [comment]
I tried to reproduce this issue, but wasn't able to. I also don't see how this would be supposed to work. If anything, KeePassXC could show the database in the wrong tab, but it cannot magically unlock a different database unless they used the same password.

**Comment by furai** [comment]
Thank you for looking into it.
