### ISSUE TITLE
2.6.2 will crash when opening webpage with lot of credentials

### ISSUE THREAD

**Issue by bkeski** [keepassxreboot/keepassxc#5702]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
KeePassXC crashes when I open admin.microsoft.com in browser

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1.  Opening (Chome or Edge) admin.microsoft.com (directed to https://login.microsoftonline.com/)
2.  I have 253 saved credentials for this site (Off365 customers)
3. KeePassXC crashes every time with error "KeePassXC: Windows - Application Error X
- The instruction at Ox000000000030B556 referenced memory at 0x0000001F000000A8. The memory could not be read.
Click on OK to terminate the program"

All other webpages work as expected.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
shows different credentials

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
crashes

## Context
[NOTE]: # ( Give us any additional information you may have. )
Downgrading to 2.6.1 solves problem. Tested in multiple computer (with same database).
exported-imported to other database, deleting Off365 credentials - this does not help, so maybe it's not related to number or credentials...

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.6.2

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows10
Chrome, Edge

**Comment by bkeski** [comment]
![image](https://user-images.githubusercontent.com/33595366/99181756-42aa2c80-2739-11eb-8de9-896dad411b38.png)

**Comment by droidmonkey** [comment]
Pinned issue
