### ISSUE TITLE
Autotype on macOS Big Sur can't find window

### ISSUE THREAD

**Issue by dewitpj** [keepassxreboot/keepassxc#5706]
## Overview
Before the upgrade to Big Sur autotype would find the window if it was configured. After the upgrade it appears to swap to the "second" "alt-tab'

## Steps to Reproduce
1. Create an entry with Autotype and window title
2. Try autotype

## Expected Behavior
Auto type should find the Window and enter the password

## Actual Behavior
Auto type finds what appears to be a random window and types the password

## Context
n/a

KeePassXC - Version 2.6.2
Revision: e9b9582

Qt 5.15.1
Debugging mode is disabled.

Operating system: macOS 10.16
CPU architecture: x86_64
Kernel: darwin 20.1.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
 libgcrypt 1.8.6

[NOTE]:
Operating System: macOS

**Comment by droidmonkey** [comment]
#4863 ?

**Comment by dewitpj** [comment]
> #4863 ?

Nope, not the same - the window is even visible on the same screen
