### ISSUE TITLE
Allow multiple URL's for a single entry

### ISSUE THREAD

**Issue by Codeberg-AsGithubAlternative-buhtz** [keepassxreboot/keepassxc#5708]
Of course you should not use the same account data (name & password) on multiple plattforms. But in some situations you have one account (the account itself, not the just its name & password copied) used for multiple plattforms.

e.g. In my office we have a central user management. There is one account with one central password. I have to use this for nearly everything here.

e.g. StackExchange offer multiple sub-section sites with different URL's for login. But there is a central user management based on StackExchange and all sub-accounts are conneted together.

I would like to enter mutliple URL's in the URL field of my StackExchange account. Currently I have mutliple entries in KeePassXC for StackOverflow, StackExchange, StackExchange meta, (emacs), and some other StackExchange sites. When I need to modify my password on StackExchange I have to modify each entry in KeePassXC for that.

**Comment by droidmonkey** [comment]
Either use clone entry and check the box to reference username/password OR go to the browser settings tab and add multiple urls.

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment]
Ah, that is what "reference" means. Maybe the GUI should be more clear about that.

**Comment by droidmonkey** [comment]
Read the user guide

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment]
Try to create a self-describing and ergonomic GUI.
Just a game between two developers. Of course I know your side. But a simple RTFM - is just to simple. :)

So to explain it objective: I am not sure if the reference thing is the right way to show/view this feature to the users. But maybe I am the only one not understanding the word "reference" here. Maybe a more none-developer-language would help.

While cloning...
"Use password from the original entry."
