### ISSUE TITLE
Auto-type message "could not find entry" hidden behind other windows

### ISSUE THREAD

**Issue by Toxaris** [keepassxreboot/keepassxc#5709]
## Overview

On Windows, when I trigger the global auto-type hotkey but no entry matches the current window, an error messages pops up. That error message is in a window *below* all my other windows so I don't see it.

## Steps to Reproduce

1. Unlock database
2. go to some window with no auto-type configured
3. press global hotkey for auto-type
4. it looks like nothing happened
5. minimize windows until the error message "could not find an entry with matching window title" is visible

## Expected Behavior

Instead of steps 4 and 5, I want to see the message *in front* of all my windows. Similar to how the "select entry to auto type" window appears in case an entry has been found.

## Actual Behavior

Message is behind all the other windows so I can't see it.

## Context

KeePassXC - Version 2.6.2
Revision: e9b9582

Qt 5.15.1
Debugging mode is disabled.

Operating system: Windows 10 Version 2004
CPU architecture: x86_64
Kernel: winnt 10.0.19041

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.6

**Comment by droidmonkey** [comment]
I got rid of this message in upcoming autotype overhaul.
