### ISSUE TITLE
2FA on opening DB

### ISSUE THREAD

**Issue by jjdoran** [keepassxreboot/keepassxc#5712]
Add a 2FA option to the unlock of the DB.

![image](https://user-images.githubusercontent.com/73179949/99426746-72edf880-28fc-11eb-9a8f-c216777108ec.png)

Ensures the DB can only be opened once and in one location with the correct 2FA code and password.
We know you can use Yubikey's or a file but it would be nice to implement a free option that affords a little extra security.
 A lot of times we may visit site and not have a security file with us. 99/100 we will have a mobile on us, if not access to emergency google 2FA codes. 

Thanks
Joe.

**Comment by droidmonkey** [comment]
We support yubikey. Totp does not work with a client-only interface.
