### ISSUE TITLE
Cursor is missing when clicking on some text fields in Keepassxc

### ISSUE THREAD

**Issue by doomikus** [keepassxreboot/keepassxc#5713]
## Overview

Many months ago I switched to the dark theme and was unable to find my cursor when clicking in a field.  Some people call this the I-bar when in a text field.  Light or dark theme has the same issue with not seeing the cursor in fields.

## Steps to Reproduce

1. Open keepassxc, which opens to last open database
2. Click on any field that is Search, Title, Username, Password, etc.  I am able to see the cursor in the Notes field.

## Expected Behavior
I expect to see the cursor in all fields

## Actual Behavior
No cursor shown in many different fields

## Context
Arch Linux
Keepassxc 2.6.2

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.6.2
Revision: e9b9582

[NOTE]: # ( Pick choices based on your environment )
Operating System: Arch Linux
Desktop Env: KDE
Windowing System: X11

**Comment by droidmonkey** [comment]
This is a kwin or Qt bug, discussed here https://github.com/keepassxreboot/keepassxc/issues/5498#issuecomment-714356279

**Comment by damnms** [comment]
please report it to kwin or qt, guess this is a nasty thing which many will face in the future.
if i would not have switched from kde to xfce, i would have created such report
