### ISSUE TITLE
Portable version bundled into one single EXE ?

### ISSUE THREAD

**Issue by macruspareto** [keepassxreboot/keepassxc#5714]
If you store KeepassXC on a Flash USB or in Veracrypt container, perhaps it would be more convenient to have just one EXE ?

To achieve that, I had packed it with a bundler (git repo: /SerGreen/Appacker) and now its just Keepass.exe and Keepass.kdbx  ....
However, the way that bundler works is it is unpacking all files into a TEMP dir, and then it would delete it after you're done. Thats pretty obvious.

Maybe you can link all DLLs and subdirectories into one resource? I know it's not by design and probably not an easy task, but... just a thought.

**Comment by droidmonkey** [comment]
We have no interest in doing this. You can just create a shortcut to the executable and place that where you want.

**Comment by phoerious** [comment]
Static linking doesn't work well with Qt's dynamic plugin loading system. Besides, we have many external non-code assets which would all have to be embedded into the binary.
