### ISSUE TITLE
Display Password in BIG LETTERS

### ISSUE THREAD

**Issue by micho2** [keepassxreboot/keepassxc#5715]
## Summary

it would be very useful, to be able to show the password in big Letters as an extra option - maybe via right-mousclick or a button.
If you have to type in a long and komplex password in anothe system where copy/paste cannot be used is´s quite hard to read the small password field.

![image](https://user-images.githubusercontent.com/6312322/99505693-6f508500-2981-11eb-9c57-8f1ac506838d.png)

![image](https://user-images.githubusercontent.com/6312322/99506030-dcfcb100-2981-11eb-947f-9c1dbd3d8247.png)

**Comment by droidmonkey** [comment]
Duplicate #4099

**Comment by micho2** [comment]
@droidmonkey 

The featurerequest is not about colors but about the size of the password.
in #4099 a bigger size is not requested.

That´s a very useful feature, that can be found e.g. in 1Password

**Comment by droidmonkey** [comment]
They are linked, implementation would be both colors and size
