### ISSUE TITLE
tab should focus the eye instead of next field

### ISSUE THREAD

**Issue by damnms** [keepassxreboot/keepassxc#5716]
when i open keepass, i have to enter the password to open my database.
so i enter the password, and because i mostly type a single char wrong (its a very long one), i hit one more time tab, the eye icon gets selected and when i press now enter i see the password in plain.

in keepassxc this is different. when i enter the password and hit tab, it jumps to the next textfield instead of the eye icon.

would it be possible to change that so keepass2 and keepassxc behave the same?

**Comment by phoerious** [comment]
Press Ctrl+H to show or hide the password.

**Comment by damnms** [comment]
thanks, was not aware that theres a shortcut for it, thats even better ;)
