### ISSUE TITLE
Username is hidden instead of password in the database browse screen

### ISSUE THREAD

**Issue by sasf54** [keepassxreboot/keepassxc#5718]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Open database, enter password
2. Browse in the database
3. Username is masked, instead of the password
(username column is masked, and password is visible for all the records)

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Username is shown, and only the password column is masked

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Password is visible

## Context
example table (without actual data)
Title                  Username     Password      URL ....
Gmail               **********       MyPassword  https://gmail.com
email account  *************   password123 https://hotmail.com

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.4.3
Revision: 5d6ef0c

Qt 5.12.8
Debugging mode is disabled.

Operating system: Ubuntu 20.04.1 LTS
CPU architecture: x86_64
Kernel: linux 5.4.0-52-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (only unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.5

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux / Xubuntu
Desktop Env: XFCE4
Windowing System: X11

**Comment by droidmonkey** [comment]
Ctrl + Shift + B, show usernames. Replace B with C for passwords. You need to update to 2.6.2
