### ISSUE TITLE
"Browser Integration" section in entry doesn't show up before restarting app

### ISSUE THREAD

**Issue by t2d** [keepassxreboot/keepassxc#5720]
## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Enable "Browser Integration" in "Settings"
2. Open an entry and try to add an additional URL

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
There should be a button "Browser Integration" in the left pane

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
There is no such button.

## Context
[NOTE]: # ( Give us any additional information you may have. )
before app restart:
![Bildschirmfoto von 2020-11-19 11-46-40](https://user-images.githubusercontent.com/1834580/99657210-2ae6e700-2a5e-11eb-8212-adf284977b15.png)
after app restart:
![Screenshot from 2020-11-19 11-48-41](https://user-images.githubusercontent.com/1834580/99657234-320df500-2a5e-11eb-96f5-06e6586b92ce.png)

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.2
Revision: e9b9582
Distribution: Flatpak

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: Gnome
Windowing System: Wayland

**Comment by droidmonkey** [comment]
Did you also disable browser integration from settings?

**Comment by t2d** [comment]
I see what you mean. The problem is not with the language, but that I didn't restart KeepassXC after enabling "Browser Integration". Still a bug though, isn't it?

**Comment by droidmonkey** [comment]
No that is expected
