### ISSUE TITLE
Tray icon(s) are invisible(dark) (on dark theme)

### ISSUE THREAD

**Issue by thansk** [keepassxreboot/keepassxc#5723]
## Overview
![image](https://user-images.githubusercontent.com/53181514/99714777-e8dd9580-2a9d-11eb-96eb-4362e6717492.png)
![image](https://user-images.githubusercontent.com/53181514/99714960-2510f600-2a9e-11eb-91e8-fc721c0904db.png)

## Expected Behavior
Tray icon should be visible and when clicked on, icons next to the dropdown should be a different color that's more contrasting.

## Actual Behavior
Tray icon is invisible on both dark and light theme.
When I click on it, icons next to Toggle Window, etc. are so dark they are barely visible. They are visible on a light theme.

## Context

KeePassXC - 2.6.1
Revision: 9a35bba

Operating System: PopOS 20.10
Desktop Env: Gnome
Windowing System: X11

**Comment by droidmonkey** [comment]
Chooser the other monochrome variant in application settings

**Comment by thansk** [comment]
The top tray icon still does not appear.
