### ISSUE TITLE
Unchecking "Always ask before performing Auto-Type" messes up Auto-Type via global shortcut

### ISSUE THREAD

**Issue by KPXCBugReport** [keepassxreboot/keepassxc#5729]
## Overview
When using a global shortcut to perform Auto-Type, unchecking "Always ask before performing Auto-Type" results in incorrect output and, depending on what the global shortcut is, may also trigger application hotkeys in the active window. Only this combination (global without asking) messes up Auto-Type. With the normal Auto-Type shortcut (Ctrl+Shift+V while having an entry selected) this problem does not occur. Likewise, the global shortcut works fine when keeping "Always ask.." checked.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Open a text editor (I used Notepad++; need to type a bit, because the window title changes then).
2. Create a test database with a "Test" entry containing the login "Username" "Password".
3. Set up a window association with the text editor for the "Test" entry.
4. Tools -> Settings -> General -> Auto-Type: Uncheck "Always ask before performing Auto-Type" and set the global shortcut to Ctrl+Alt+A.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
When pressing Ctrl+Alt+A inside the text editor window, the result should be `Username<TAB>Password<RETURN>`.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
When pressing Ctrl+Alt+A inside the text editor window, the result is `<RETURN>UsernamePassword` (for this particular global shortcut). Using e.g. Ctrl+Shift+Q results in `Username` and then some Notepad++ menus get triggered.

## Context
[NOTE]: # ( Give us any additional information you may have. )
As mentioned, this only happens with the combination of using a global shortcut and disabling the confirmation list.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.2
Revision: e9b9582

[NOTE]: # ( Pick choices based on your environment )
Windows 8.1, German keyboard layout

**Comment by droidmonkey** [comment]
There is nothing we can do about other applications triggering actions on a shortcut key.

**Comment by KPXCBugReport** [comment]
That is not at all what I was saying.

**Comment by droidmonkey** [comment]
You are leaving one of the modifier keys down for too long. Either increase the start delay or remove your fingers from the keyboard faster.

**Comment by KPXCBugReport** [comment]
You are correct. I hold Ctrl+Alt and then tip A. I've been doing it like this for 10 years using the original KeePass and it wasn't a problem, so I've never thought about it. Thank you very much!
