### ISSUE TITLE
Website addition re Mac sha256 DIGEST check instructions - use shasum

### ISSUE THREAD

**Issue by bunk3m** [keepassxreboot/keepassxc#573]
## Expected Behavior
On the website [https://keepassxc.org/verifying-signatures](url) the suggestion is to use sha256 command.  This command isn't available on the Mac.  It would be nice to update the website with Mac specific instructions.

## Current Behavior
To verify the download I had to go searching for a way to check the sha256 digest.  Not impossible of course, but it would be nice to have the instructions on the website.

## Possible Solution
Command shasum can be used instead of sha256.  I recommend adding the following command for verifying the Mac DMG.

`shasum -a 256 -c KeePassXC-[Version].dmg.DIGEST`

## Context
Instead of having to search for the way to check the Digest, it would be nice to have instructions on the website.

Command above allowed me to verify the DMG.

## Your Environment
OSX 10.10.5

**Comment by TheZ3ro** [comment]
Please, reopen the issue on the website repository, thanks 
https://github.com/keepassxreboot/keepassxreboot.github.io/issues

I will close this one
