### ISSUE TITLE
Design request : make KeepasXC adaptive

### ISSUE THREAD

**Issue by MohamedBouzidGit** [keepassxreboot/keepassxc#5730]
Hello, thank you for this great app that I use since a long time. 
As I use tablet and would like to use Linux phone (Pinephone / Librem 5), please could you make KeepassXC adaptive ? 
I my tests, I can't shrink to much the window. 
There is [those guidelines](https://developer.puri.sm/Librem5/Apps/Guides/Design/Adaptive_UI/index.html) to respect adaptive UI
In [Purism's blog](https://puri.sm/posts/specify-form-factors-in-your-librem-5-apps/), they also propose to tweak some files to make them appear as a mobile app. 

I think you have many work to do, so I don't push, but I am sure KeepassXC is a must have in Linux, regardless of the device. 
Thank you for your consideration.

**Comment by droidmonkey** [comment]
See #5676
