### ISSUE TITLE
keepassxc on Linux allows adding entries to read-only database

### ISSUE THREAD

**Issue by sjvudp** [keepassxreboot/keepassxc#5731]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
To add to my dababase on a FAT-formatted USB stick, I mounted the filesystem as root in Linux, and opened it in another window. I cloned an entry, edited it several times to find the save icon is gray, so I assumed everything is fine.

Fortunately I realized that the user running keepassxc had no write access to the files being `root:root`-owned. So I saved the database with "Save as.." and then copied the file as root to the stick.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Assume you have a file `-rwxrwxr-x 1 root root 68629 Nov  2 21:06 /mnt/private.kdbx`
2. Open that file with keepassxc as non-root user
3. Add an entry to the database

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Changes to the database should not be allowed as they can't be saved

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Changes to the database are allowed, and it seems the changes are saved.

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.3.4
Revision: 6fe821c

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: XFCE (I think)
Windowing System: not known (Qubes OS)

**Comment by droidmonkey** [comment]
You are way out of date
