### ISSUE TITLE
Feature request: Sofware implementation of FIDO U2F

### ISSUE THREAD

**Issue by nognognoggynog** [keepassxreboot/keepassxc#5732]
Feature request: Sofware implementation of FIDO U2F

The problem with Hardware U2F keys is lack of transparancy on what is actually happening, lack of source code being open, backup ability in case one key fails, and the cost barrier of entry, fact is, it costs, not everybody can afford hardware for everything every time, software is cheaper entry, thus preserves access to U2F technology without a wealth barrier, hardware can fail, hardware does fail, that means you're going to end up buying twice or thrice depending

Having a software option in KeepassXC would help alleviate those barriers and risks

It may even increase adoption of U2F over TOTP by lowering the wealth barrier of entry and redundancy, and transparancy by open source and availability, also hardware depends on a manufacturing supply chain and delivery postage, risk of interception and replacing and fake and doctored hardware

Many use KeepassXC as a TOTP backup in case their mobile fails, and it does, but it's software, it's replacable, it's duplicatable, cheaply/free, U2F keys are not

having to get replacable hardware means potential denial of access and having to risk losing access to the account depending on the service and company, having a software backup (you can register multiple keys/software or hardware perhaps and keep access possible in the event of a failure of hardware)

More choice, more redundancy, lower barrier of entry, more transparancy, less risk

What may be cheap to you may not be cheap to others, there should not be a wealth barrier, there should not be an opaque implementation barrier, there should not be a backup barrier, there should not be dependency on a single vendor and supply chain

Any place there is hardware,  you have risk, lack of transparancy, and a wealth barrier, and a redundancy barrier (cannot backup hardware without more hardware and more cost, increasing the wealth barrier more), we cannot build the hardware independently as we can software, we cannot verify hardware as we can software as easily

Hardware with protocols like U2F gets dated, it needs replaced with a new spec (v2 .. v3 etc) iterations and then you have to buy replacement hardware, more cost to entry, a higher wealth barrier again. A software choice would help people adapt faster and without this cost barrier

We need an open software option, KeepassXC would be ideal for that along with the H/TOTP feature

This would help empower the individual with another U2F choice

**Comment by droidmonkey** [comment]
Besides totally defeating the purpose and security guarantees of FIDO U2F, this would require us to develop, sign, and distribute drivers for each operating system to create the fake HID device. We are not going to do that. I personally don't believe in emulating second factor hardware keys, they are hardware keys for a reason.

Your main argument is that the barrier to entry with a FIDO U2F key is cost. That is bullox, you can purchase a key for [$19](https://www.amazon.com/dp/B06XHTKFH3/ref=cm_sw_r_cp_awdb_imm_t1_VfTUFbJ7VZ4P5)

**Comment by nognognoggynog** [comment]
> Besides totally defeating the purpose and security guarantees of FIDO U2F, this would require us to develop, sign, and distribute drivers for each operating system to create the fake HID device. We are not going to do that. I personally don't believe in emulating second factor hardware keys, they are hardware keys for a reason.
> 
> Your main argument is that the barrier to entry with a FIDO U2F key is cost. That is bullox, you can purchase a key for [$19](https://www.amazon.com/dp/B06XHTKFH3/ref=cm_sw_r_cp_awdb_imm_t1_VfTUFbJ7VZ4P5)

Wasn't one argument the open source community use to defend their software is it's transparant, depending on opaque implementations is not security, even Bruce Schneier says to that effect I believe (I would need to dig up the quote and articles), so basically you've just shot down the open source argument, it's protected by math, not opaqueness

**Comment by nognognoggynog** [comment]
With respect, reopening for reconsideration and more open wider discussion

**Comment by nognognoggynog** [comment]
Referencing the RSA SecurID theft

https://arstechnica.com/information-technology/2011/06/rsa-finally-comes-clean-securid-is-compromised/

**Comment by nognognoggynog** [comment]
At least with software implementation we can generate and store our own private key in KeepassXC, with hardware you're depending on the manufacturer (reference RSA SecurID seed theft, 2011)

**Comment by nognognoggynog** [comment]
cc: @droidmonkey

**Comment by nognognoggynog** [comment]
imo with these hardware keys you do not own the private key embedded on it, the company that made it does

**Comment by nognognoggynog** [comment]
Not that it matters where it's made, but, I imagine to get cost low they're made in cheap places, "Made in China" perhaps but, I want control of that private key, I don't care where it's made, with open source I can at least know and make it myself

**Comment by nognognoggynog** [comment]
Google Titan hardware key, https://www.cnbc.com/2018/08/30/google-titan-made-by-chinese-company-feitian.html

**Comment by nognognoggynog** [comment]
I really hope I am shattering trust in those hardware keys, I really do

**Comment by nognognoggynog** [comment]
What is your private key of your hardware dongle? You don't know because you did not generate it and cannot control it.

Do you know what generated it? No

Do you know if it is stored anywhere else? No, you don't know

Do you feel less safe now? The right answer is yes imo

How can you trust it without verifying all this?
