### ISSUE TITLE
Software U2F

### ISSUE THREAD

**Issue by sanawu** [keepassxreboot/keepassxc#5733]
https://github.com/keepassxreboot/keepassxc/issues/5732

i see you deleted this fascinating issue

I too would like to see software U2F especially after reading that discussion

Why are you afraid of the fact hardware U2F keys are insecure like SecurID

**Comment by droidmonkey** [comment]
Its not fascinating, its spam

**Comment by sanawu** [comment]
Can you post the factual parts, please so we can read it? I believe that is what open source is about too, transparancy, why areyou deleting issues that are in fact real and valid issues?

That does not hold well for trust sorry

**Comment by droidmonkey** [comment]
It has absolutely nothing to do with us. We don't implement FIDO U2F.

**Comment by sanawu** [comment]
> It has absolutely nothing to do with us. We don't implement FIDO U2F.

There is when you hide issues, lock it and let it be, an issue database should not be deletable

**Comment by phoerious** [comment]
Software U2F is pretty much the same as TOTP. Hardware keys are always better.

**Comment by droidmonkey** [comment]
You can read the gist in #1996
