### ISSUE TITLE
Maintain entry view column proportions when resizing window

### ISSUE THREAD

**Issue by liar666** [keepassxreboot/keepassxc#5734]
## Summary
Hi,

First, thanks for the tool, it is very useful and the new interface is beautiful!

I'm using a tiling WM. As a consequence, sometimes keepassxc is opened full screen, other times, it shares the screen size with other windows (this auto reszing occurs right at opening, automatically).

When I opened keepassxc, it got opened fullscreen, but the columns in the "search result" were using only a small part of the available space, as can be seen in picture below :
![keepass_bug](https://user-images.githubusercontent.com/3216927/99939206-d26b5e80-2d69-11eb-9a2d-39a099e2db0f.png)

Thus, I set up the column sizes at my convenience for the current window size (full screen),

But the other day, the window got opened in "quarter of the screen" size, thus the columns were way too big for the window size.

Keepassxc is well designed, so the whole panel was inside a scrollbar and I could view the whole content, but I was wondering if it would be possible to have an option to make so the columns are automatically resized according to the current window size (and their previously set respective sizes). I think an option to set this behaviour would be the best as people might not have the same expectations as mine.

Thanks!

**Comment by droidmonkey** [comment]
Duplicate request
