### ISSUE TITLE
Password generator persistent options

### ISSUE THREAD

**Issue by Korezze** [keepassxreboot/keepassxc#5737]
Password generator: it would be convenient to persistently save the user choices of character types that should be used
for the password generation (password length is persistent, but not the characters types).
Tnaks

**Comment by droidmonkey** [comment]
They are saved already.

**Comment by droidmonkey** [comment]
See #2628

**Comment by Korezze** [comment]
Thanks for your answer. I made a new test : youre right, options are saved, except if you select group **#$%&^`~**, which is never saved.
I use version 2.6.2

**Comment by droidmonkey** [comment]
Fixed in #5610
