### ISSUE TITLE
Auto-type doesn't operate at first attempt when Keepass XC is reduced and DB locked.

### ISSUE THREAD

**Issue by Korezze** [keepassxreboot/keepassxc#5739]
Auto-type doesn't operate at first attempt when Keepass XC is reduced and DB locked.

Steps to reproduce :

1. Be sure Keepass XC is running, reduced and all DB locked.
2. Open a web site which need credentials
3. Select the main type zone of this web site (left click)
4. Type your auto-type kepass XC shortcut
5. Keepass XC window is opening. Unlock your database.

And nothing happens, no auto-type.
Repeat steps 3 & 4 and auto-type operates normally

Keepass XC 2.6.2
Windows 10 2004

Thanks

**Comment by droidmonkey** [comment]
I've overhauled autotype for the next version so I'm closing this

**Comment by droidmonkey** [comment]
If the window title changes then Auto-Type could be canceled before it starts.

**Comment by Korezze** [comment]
I do other tests : this problem occurs with every internet site with v2.6.2 (Firefox 83.0 and Chrome 87.0). But, with v2.6.1, it never occurs. It seems to be a regression ?

**Comment by droidmonkey** [comment]
We didn't change anything with autotype between those versions
