### ISSUE TITLE
Icon in systray hardly visible with bright theme on Windows

### ISSUE THREAD

**Issue by halloamt** [keepassxreboot/keepassxc#5740]
## Overview
The systray icon on Windpows ist hardy visible if the bright theme is active. Is there a possiblitity to switch to a mor blackish icon?
![grafik](https://user-images.githubusercontent.com/10853957/99987600-f43c0400-2db0-11eb-8999-941a447b6ade.png)

![grafik](https://user-images.githubusercontent.com/10853957/99987395-b343ef80-2db0-11eb-8c23-440eacf6915d.png)

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Enable bright theme on Windows 10
2. Enable KeePassXC systray icon

## Expected Behavior
An inverted or otherwise darker icon would improve contrast and visibility.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.2
Revision: e9b9582

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows

**Comment by droidmonkey** [comment]
You choose your icon color from the application settings
