### ISSUE TITLE
Mouse interactions impaired under linux/wayland

### ISSUE THREAD

**Issue by sriedel** [keepassxreboot/keepassxc#5741]
## Overview
Since a few weeks ago interacting with the UI elements has been impaired.

## Steps to Reproduce
1. Install Linux
2. Install sway wm
3. Install KeepassXC
4. start KeepassXC
5. Interact with KeepassXC

## Expected Behavior
I can click and interact with all appropriate UI elements of KeepassXC

## Actual Behavior
Currently I can successfully click on elements within the left database navigation pane, and having everything work as expected there.
Clicks on the right element navigation pane are ignored, requiring interacting with tab, cursor, enter, and escape keys.
Clicks on menus highlights the menu name, but the menu does not appear (same behaviour when selecting a Menu with an Alt+<letter> keyboard shortcut, e.g.Alt+D for the Database menu). 
Clicks on icons in the toolbar partially work (e.g. the "+" for adding an entry), partially seem to be ignored (e.g. the dice for the password generator).
Opening the "Add Entry" dialog and clicking causes the "Title" input to lose focus, no element can be focused or activated with mouse events, navigation with keyword works as expected.

Activating the Help menu with Alt+H and pressing enter opens the User Guide in my browser, so I suspect that the main issue is with displaying the actual actions/popups etc.

## Context
Archlinux, keepassxc 2.6.2-1 package, running under swaywm 1.5.1-1, wlroots 0.12.0-1

[NOTE]: # ( Paste debug info from Help → About here )
As described, the menu does not open for me. keepassxc --version outputs "2.6.2"

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Windowing System: Wayland

**Comment by droidmonkey** [comment]
Why do you suspect this is keepassxc?

**Comment by sriedel** [comment]
Uhhh... not sure how I'm supposed to respond to that question (Enduser: "I have a problem using your program..." Developer: "And why do you think thats a problem with my program?")

As an enduser of keepassxc without insight into the internals, I don't know if the root cause its in the code of keepassxc or in one of its upstream dependencies. It could be Qt. It could be wayland. It could be the WM. It could be keepassxc. I don't know.  I have this issue with keepassxc and the described behavior only presents itself in  keepassxc at the time being. KeepassXC is the only Qt program I'm using, so it may very well be an issue with Qt.

If there's a way to narrow down the cause, I'd be happy to help to the best of my abilities. However if it's certain that Qt is at fault, feel free to close the report.

**Comment by droidmonkey** [comment]
Try another qt application to see: https://wiki.manjaro.org/index.php?title=List_of_Qt_Applications
