### ISSUE TITLE
favicon downloader doesn t finish - leaving database open, when not closing window manually

### ISSUE THREAD

**Issue by sahneschnitte** [keepassxreboot/keepassxc#5744]
after downloading favicon icons, found keepassx tomorrow morning still open, even after a night in sleep, still hanging in the separate window / dialog for favicon icon downloading. ( on mojave )

**Comment by droidmonkey** [comment]
What version of keepassxc are you using

**Comment by sahneschnitte** [comment]
2.6.2

**Comment by droidmonkey** [comment]
Can you cancel the download?

**Comment by sahneschnitte** [comment]
the download was already finished.needed longer as i CMD+A- selected all.. so i forgot to close the window, as i use keepassx in fullscreen on another virtuell desktop. in the night i set my laptop to sleep, and today, when i woke him up, i recognized, that i don´t have to login again.

**Comment by sahneschnitte** [comment]
replicated the bug some seconds ago . database doesnt close, although computer went to sleep and woke up again, when the favicon download Window stays open, independently if favicon download is finished or not.
