### ISSUE TITLE
Cannot open stored attachment (rdp file)

### ISSUE THREAD

**Issue by joaogoncalv-es** [keepassxreboot/keepassxc#5745]
## Overview
KeePassXC fails to open an attachment from the type *.RDP

Background:
I want to create several Entries with info about Remote Machines and their login information.
In each entry I would like to save an Attachment with the RDP file of each Remote Machine.

## Steps to Reproduce
1. Create a new Entry
2. Add an attachment file of the type RDP (remote desktop connection)
3. Save the Entry and get back to Root Folder
4. Click on the new Entry
5. At the bottom of KeePassXC, the UI presents the option to open the attachment directly. click Open.
6. Error: The file (C:\Users\xxxxxxx\AppData\Local\Temp\xxxxxxxx.remote_machine.rdp) could not be found.

## Expected Behavior
KeePassXC should be able to open RDP file (my current attachment) directly.

## Actual Behavior
It seems that the temp file under my %TEMP% directory is being used / blocked by KeePassXC.
Even with Windows Explorer I cannot open this temp file. But if I copy it to another folder, then I can open it.

## Context

[NOTE]: # ( Paste debug info from Help → About here )
debug Info:
KeePassXC - Version 2.6.2
Revision: e9b9582

Qt 5.15.1
Debugging mode is disabled.

Operating system: Windows 10 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.19042

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.6

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows
Desktop Env: Gnome/KDE/XFCE/Mate/Cinnamon
Windowing System: X11/Wayland

**Comment by ethanjosephscott** [comment]
Playing around with this, try using the windows store version of RDP, it launches with that.

**Comment by droidmonkey** [comment]
This is because KeePassXC holds a lock on the file and RDP requests a read/write lock when opening an rdp file.

**Comment by droidmonkey** [comment]
Covered by #2400

**Comment by ethanjosephscott** [comment]
This may not solve the exact problem, however this guide will allow you to one-click rdp sessions.
[https://www.reddit.com/r/KeePass/comments/k8kitq/launch_rdp_sessions_from_keepassxc_working/](url)
