### ISSUE TITLE
Re-lock previously locked database after Browser Integration

### ISSUE THREAD

**Issue by normanr** [keepassxreboot/keepassxc#5749]
## Summary
Once Browser Integration has read username and password from the database I would like the database to re-lock.

## Context
This would be similar to how "Re-lock previously locked database after preforming Auto-Type" works.

https://github.com/keepassxreboot/keepassxc/issues/2651 is a similar idea, but not identical (so I'm opening this new Feature Request).

The way that this could work is either KeePassXC could re-lock the database directly, or KeePassXC-Browser would trigger the re-lock. The former is probably more secure.

**Comment by normanr** [comment]
actually, I didn't think that the browser integration can lock the database, but it looks like it can, so I've filed https://github.com/keepassxreboot/keepassxc-browser/issues/1124 instead.

**Comment by droidmonkey** [comment]
Agree this is better left handled by the extension
