### ISSUE TITLE
Automatic renaming of the database file 

### ISSUE THREAD

**Issue by rafalekb19** [keepassxreboot/keepassxc#5751]
Hi. I have a problem with KeepassXC. I use it on several computers, the base is on iCloud. There has been a problem starting KeepassXC for a while. I get the message: database does not exist. This is because the name or actually the extension of the database file changes automatically.
He often adds new entries to KeepassXC, and that's when this happens.
![Screenshot_1](https://user-images.githubusercontent.com/75084474/100366252-e5e42700-3000-11eb-8d52-0f33db1e9866.png)

**Comment by phoerious** [comment]
This is a problem with iCLoud. Try disabling "Safely save database files" in the settings.
