### ISSUE TITLE
Mobile App 

### ISSUE THREAD

**Issue by tan13621251388** [keepassxreboot/keepassxc#5754]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
Do you think about make a nice KeePaddXC which can use on moblie?

**Comment by droidmonkey** [comment]
Already been discussed,  we are not going to invest time in this. Already many great options.
