### ISSUE TITLE
HTML parsing in attributes

### ISSUE THREAD

**Issue by mdhooge** [keepassxreboot/keepassxc#5755]
## Overview
When attributes are printed on the "Advanced" tab in the "Preview" area, the text is analysed for HTML tags.
Whenever you have a single "inferior" sign, the sign and everything after is not printed.

## Steps to Reproduce
1. Create an attribute with text “1<2”
2. Create another attribute with text “1& lt;2” (Remove the space after the ampersand — it is there to prevent Github Markdown to trigger a conversion…)

## Expected Behavior
For #1, we should see the text “1<2“.
For #2, I'm not sure…

I don't know if this HTML parsing is done on purpose but this is misleading. If you have a long password with an inferior sign  at the end, you can easily overlook the fact that some characters are missing!

## Actual Behavior
1. “1”
2. “1<2“

## Context
KeePassXC - Version 2.6.2
Revision: e9b9582

Qt 5.15.1
Debugging mode is disabled.

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 5.9.8-arch1-1

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.7

Operating System: ArchLinux
Desktop Env: KDE
Windowing System: X11

**Comment by droidmonkey** [comment]
Thats definitely a mistake if enabled

**Comment by mdhooge** [comment]
In fact, this is enabled to easily format the output!

In file `src/gui/EntryPreviewWidget.cpp`, method `updateEntryAdvancedTab`, replace the **for** loop by something like below (Note: I didn't try to compile it — but it is really dumb!).
```
        for (const QString& key : customAttributes) {
            QString value;
            if (m_currentEntry->attributes()->isProtected(key)) {
                value = "<i>" + tr("[PROTECTED]") + "</i>";
            } else {
                value = m_currentEntry->attributes()->value(key).toHtmlEscaped();
            }
            attributesText.append(tr("<b>%1</b>: %2", "attributes line").arg(key, value).append("<br/>"));
        }
```

Ref: https://doc.qt.io/qt-5/qstring.html#toHtmlEscaped

**Comment by mdhooge** [comment]
Nice to have additions:
- If content has LineFeeds, replace them by < br / >
- If Settings are to use Monospace font for Notes, also enforce it here.

**Comment by mdhooge** [comment]
>     * If content has LineFeeds, replace them by < br / >

Done in https://github.com/keepassxreboot/keepassxc/pull/5834

>     * If Settings are to use Monospace font for Notes, also enforce it here.

Maybe I should open a new issue?
