### ISSUE TITLE
Close to tray icon

### ISSUE THREAD

**Issue by arhayati** [keepassxreboot/keepassxc#5756]
Hey.

It would be great to have an option in which we could close to tray icon. Like minimize to tray, but with the close button.

Now, when we hit thr X, it closes the program, but it would be great to have a feature that when we close the program, it locks the database (or not - at our option) and gets minimized to tray icon.

It's a habbit that many people have. Many people just want the icon be gone in taskbar or dock but they still want the program to be opened in background.

**Comment by droidmonkey** [comment]
There is this option already in application settings
