### ISSUE TITLE
Database Stays Open when Session is Locked (version 2.3.4)

### ISSUE THREAD

**Issue by Jimmy-Py** [keepassxreboot/keepassxc#5757]
In settings > security 
there is a checkbox that says "lock database when session is locked or lid is closed." I have that toggled on.

However, when I lock my session (while keeping the lid open) and then later log back into my session, the database is still unlocked.

I'm using Debian Buster, XFCE, so my package manager automatically gives me version 2.3.4. 

When I suspend my session, then the database locks on it's own successfully.

**Comment by droidmonkey** [comment]
Update your keepassxc. You'll have to use the appimage or snap variant.
