### ISSUE TITLE
Secure the "export" function

### ISSUE THREAD

**Issue by matt1tk** [keepassxreboot/keepassxc#5758]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
The "export" function is insecure. It requires a few key presses and can even be automated entirely (press alt, space, E, C, Y, enter filename, press F4, enter any directory, press alt+s) and you have the entire database. Requiring the password be entered again may not be the solution, but just some sort of dynamic delay / "click the number that is divisible by 3" or something like that would fool rudimentary scrapers. (There is procdump.exe'ing the process but that is probably more complicated than this, which abuses the export function and gets the CSV directly.)

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )
Sample attack code: https://gist.github.com/matt1tk/e78750aa39a6ea13f28af7a0d18449d8 
Regular speed video demonstrating attack: https://streamable.com/fuukny 
Sample: ![keepass](https://user-images.githubusercontent.com/54869024/100493054-3cd12580-3101-11eb-8aa2-617d92b1f664.jpg)

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
Feels like exporting should require admin rights that would be harder to spoof, or a dynamic test to ensure it isn't automated.

**Comment by phoerious** [comment]
There is no way you can protect yourself against that. Once you have unlocked your database, it is open. If we require a password to be entered, it wouldn't really secure anything. It would only halt automated key presses. But if you have a malware that does that on your PC, it's pretty much game over anyway.

**Comment by matt1tk** [comment]
Should it be this easy to steal all of the passwords? The online password managers aren't susceptible to this even when unlocked, and KeePassXC is supposed to be more secure. I understand once it's unlocked it's game over, but perhaps it shouldn't be made so easy.

**Comment by droidmonkey** [comment]
The only thing that makes this easy is the fact that you run the keypress program on your computer. Adding arbitrary barriers to export will do nothing to stop a simple program. Take for instance requiring your credentials to export. It would be just as easy to listen for your keystrokes when unlocking your database and replay them in the export sequence. This is an interesting thought experiment, but ultimately not something we can protect against.

**Comment by matt1tk** [comment]
There are a lot of "grabber" programs that simply steal everything they can in a few seconds. See "anarchy grabber" and many others that just self destruct after stealing info. Of course it is a very small attack surface, I'll admit that. If a program simply waits for db unlock, though, it opens up the possibility of an antivirus scanning it because it runs longer.

**Comment by matt1tk** [comment]
This is unrealistic of course, so if the maintainers don't see it as worth the tradeoff, feel free to close.
