### ISSUE TITLE
Entries table header settings saved only on database/application close

### ISSUE THREAD

**Issue by bin101** [keepassxreboot/keepassxc#5759]
## Overview
I just noticed that the entries table header settings are only saved on database/application close events.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. change the columns you want to (not) see.
2. shutdown/reboot the pc without closing the database or exiting keepassxc
3. after reboot start keepassxc again
4. the same columns are displayed as before the change.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Save the settings directly after the change

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
see above

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.6.2
Revision: e9b9582

[NOTE]: # ( Pick choices based on your environment )
I think every OS but tested only Windows and Linux

**Comment by shemeshg** [comment]
I thought I'd be taking this as my First Bug Quick Win, but could not reproduce that on 2.6.6
I did not Hard unplugged the power of my PC though..., instead I did 
Apple Icon-<Force Quit->KeepassXC 

And Show/hide columns were saved correctly..., also Mask of column data by choosing View->Hide Password worked fine.
...
Maybe the Github->"Projects"->Basic Support, is not the right place to start?

**Comment by droidmonkey** [comment]
The problem is that the DatabaseWidgetStateSync::sync() function is only called on app exit.

https://github.com/keepassxreboot/keepassxc/blob/724f691e159f69c16d01ca00908452d2d8d6c5d4/src/gui/DatabaseWidgetStateSync.cpp#L35

This function should also be called when columns are added,  removed, or rearranged by the user.
