### ISSUE TITLE
Cannot run 2.1.4 AppImage on 32-bit system

### ISSUE THREAD

**Issue by Phidica** [keepassxreboot/keepassxc#576]
I downloaded the current AppImage from the website (KeePassXC-2.1.4-x86_64.AppImage) and made it executable, but when trying to open the program from a file browser nothing happens. When executing from a terminal: 
```
$ ./KeePassXC-2.1.4-x86_64.AppImage
bash: ./KeePassXC-2.1.4-x86_64.AppImage: cannot execute binary file
```

This message can be indicative of many things, but I believe I have narrowed down the cause to an architecture incompatibility. I am running 32-bit Fedora 20 (thus installing from source isn't feasible, and I cannot upgrade as this is a work computer), and it appears the executable is 64-bit:
```
$ file KeePassXC-2.1.4-x86_64.AppImage
KeePassXC-2.1.4-x86_64.AppImage: ELF 64-bit LSB executable, x86-64, version 1, dynamically linked (uses shared libs), for GNU/Linux 2.6.18, BuildID[sha1]=86d6d303dd0e18dc379e91d9d4d468c5cca5c556, stripped
```

Can a 32-bit AppImage be distributed alongside the 64-bit version?

**Comment by phoerious** [comment]
No, the AppImage is only compiled for 64 bit. 32 bit is legacy technology which we don't want to support. Any even "slightly recent" computer (meaning: bought within the last 10 years) supports 64 bit. I would rather recommend you switch to a 64 bit version of Fedora. If you really can't, you have to compile KeePassXC yourself (compiling it yourself is no less "feasible" on 32 bit than on 64 bit).

**Comment by Phidica** [comment]
Actually it's infeasible because Fedora 20 is so old that I can't get sufficiently updated versions of the dependencies without in turn building those from source, and so on down the rabbit hole. I wish I could switch to a more appropriate OS but as I said, it's not my computer and I have no control over this

I agree that 32-bit is ancient tech, but I've never encountered a program that is only distributed for 64-bit systems so I assumed the lack of a 32-bit alternative was simply the result of an oversight rather than an ideological choice. That being the case then, I'll try building the newer dependencies from source and if it's no good I'll switch to a different manager

Thank you for the insight

**Comment by phoerious** [comment]
It's not really ideological, rather minimization of work. We build our AppImage inside an Ubuntu 14.04 Docker container. If you replace the 64bit image with a 32 bit one or install gcc multilib inside of it, you can build a 32 bit version without the need of having a working build toolchain on your Fedora box.

**Comment by Phidica** [comment]
FWIW, I successfully compiled from source. Turns out I only needed to compile the latest libgcrypt (and its dependency libgpg-error), as the Fedora 20 repos did have sufficiently updated versions of the remaining dependencies after all
