### ISSUE TITLE
Health Check - Possibility to exclude whole groups/folders from Health Check 

### ISSUE THREAD

**Issue by Stebs** [keepassxreboot/keepassxc#5761]
## Summary
Allow users to exclude whole groups from health check, for example in the group settings (just like excluding auto-type).

## Example use cases:
I have a folder of passwords imported from the Browser, as a sort of Backup, in case I forgot to manually add a Website to keepassxc. With Health Check, most of the passwords show up as double entries (being in my normal entries and also in my imported "Backup" folder). Some show up as triple entries because being imported twice, as http:// and https:// entries in the Backup folder.

Other use-cases:

From Bug entry:       Health Check - Exclude MULTIPLE entries from check #4533
"Excluding an folder including all sub-folders would help a lot, because I have all expired entries in a folder called "expired" and this folder has sub-folders."

Excluding folders/groups should also prohibit counting them as multiple entries.
Once you check the "Show excluded" option, this should force a recheck of multiple entries and take excluded folders into account.
I think currently, excluded entries are simply not shown, but entries with the same password are still getting a lower score because of multiple occurrences...

**Comment by droidmonkey** [comment]
This won't be implemented, instead you can now easily exclude multiple entries from the reports view introduced in #6537
