### ISSUE TITLE
Menubar icon is squished when using multiple DisplayLink monitors on Big Sur

### ISSUE THREAD

**Issue by b-a0** [keepassxreboot/keepassxc#5762]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
Since the update to Big Sur the KeePassXC icon in the menubar is squished, unless the display of the menubar has focus.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Connect one or more DisplayLink monitors
2. Open KeePassXC
3. Ensure UI settings are:
    * Show a system tray icon
    * Hide window to system tray icon

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
KeePass minimises to the menu bar icon, which remains round on all displays.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
KeePass minimises to the menu bar icon, but only the icon on the menu of the display having focus is round. All other menu bars show a squished version of the icon (see GIF below).

![sixthtry](https://user-images.githubusercontent.com/25707742/100542947-9181b700-324d-11eb-8521-a8b6c4df3128.gif)

In the screen recording I do the following: 
* I start with focus on a window that is on the display _not_ being recorded, the KeePass icon is squished (just as the green checkmark of the Nextcloud client icon by the way).
* Then I switch focus to a window on the display that is being recorded, you can see the KeePass icon "unsquish".

## Context
[NOTE]: # ( Give us any additional information you may have. )
The [Nextcloud client](https://github.com/nextcloud/desktop) icon shows the same issue. Maybe the same library is used and this can help pinpoint the issue?

This is  MacBook Pro Mid 2015 with two Philips Brilliance 241B displays, connected via DisplayLink USB using DisplayLink Manager v1.1.0 (build 54.91). My setup was the same before the update to Big Sur, but then all worked well.

I understand this setup might be rare, so if you need me to test something I am willing to help.

### KeePass info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.2
Revision: e9b9582

Qt 5.15.1
Debugging mode is disabled.

Operating system: macOS 10.16
CPU architecture: x86_64
Kernel: darwin 20.1.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
 libgcrypt 1.8.6

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS Big Sur 11.0.1

**Comment by droidmonkey** [comment]
This is certainly not our bug considering nextcloud has the exact same problem. Task bar icons are solely handled by Qt, perhaps they need to implement new api for big sur. Either way this isn't something for us to handle.

**Comment by b-a0** [comment]
You're right, apparently it has been reported in [QT bug 88600](https://bugreports.qt.io/browse/QTBUG-88600). It's marked as closed over there and it seems to be [merged into 5.51](https://codereview.qt-project.org/c/qt/qtbase/+/322339). However, I'm not certain what that means. What do I need to do to let this change propagate to KeePass (and Nextcloud)? Do the developers need to update their dependencies? Do I need to update Qt on my machine?

**Comment by droidmonkey** [comment]
When we make our next release it will be included

**Comment by b-a0** [comment]
Just wanted to note that release 2.6.3 did resolve this bug.
@droidmonkey does this mean that the Qt merge has not been incorporated in 2.6.3? Or does "next release" refer to a major or minor version update (i.e. 2.7.X or 3.0), not a patch update (2.6.**3**)?

**Comment by droidmonkey** [comment]
We ended up not incorporating Qt 5.15.2 in 2.6.3.
