### ISSUE TITLE
Keeshare Hardening: credentials only visible to the db creator

### ISSUE THREAD

**Issue by notapirate** [keepassxreboot/keepassxc#5763]
I would like to use Keeshare to enable others to use my credentials, but I don't want them to know the username/password.

So I suggest an option for Keeshare to show the credentials (and all related options like 'Copy [username|password] to clipboard') only if the certificate of the db creator is present.

Is a feature like this alreaddy in planning state?
Can I accomplish this requirement with the current SW version (2.6.2)?

**Comment by droidmonkey** [comment]
This doesn't make sense. If someone can _use_ your credentials they can see them. Full stop. Nothing prevents them from auto typing them into notepad. This will not be implemented.
