### ISSUE TITLE
Keeshare Hardening: Make a share db only writable to the creator

### ISSUE THREAD

**Issue by notapirate** [keepassxreboot/keepassxc#5764]
I would like to use Keeshare to enable others to use my credentials, but I don't want them to change anything.

So I suggest an option for Keeshare to enable write access only if the certificate of the db creator is present.

Is a feature like this alreaddy in planning state?
Can I accomplish this requirement with the current SW version (2.6.2)?

**Comment by droidmonkey** [comment]
Thats what import is for. Put the keeshare database in a network share only writable to authorized parties.
