### ISSUE TITLE
Purging unused icons

### ISSUE THREAD

**Issue by ppoilbarbe** [keepassxreboot/keepassxc#5766]
## Summary
Purging unused icons in the icon tab.

While we download icons for new sites or upgrading the ones of some sites, some icons become unsed (replaced by another one). It should be useful (at least for me :)) to have another button (completing Add, remove, download buttons) to purge all icons that are not referenced by any element of the database.

## Context
When updating sites (redownload icon), the previous one can become unused (if no other entry references it). And it is not easy to see which are not used.

**Comment by droidmonkey** [comment]
Duplicate #2110
