### ISSUE TITLE
The snap definition doesn't include a common-id information

### ISSUE THREAD

**Issue by seb128** [keepassxreboot/keepassxc#5767]
Using Ubuntu 20.10

Searching for 'keepassxc' in the Ubuntu Software Sotre lists several results for the deb and the snap. The store is able to merge the different formats under one entry (with a source selector in the details page) but for that the snap needs to specify the upstream id in its apps section of the snapcraft.yaml

`common-id: org.keepassxc.KeePassXC.desktop`

**Comment by droidmonkey** [comment]
Added in 2.7.0
