### ISSUE TITLE
2.6.2 Security Bug Found exposing key file

### ISSUE THREAD

**Issue by AndroidHemroid** [keepassxreboot/keepassxc#5768]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

Placing your encrypted database on the cloud example: on One Drive, by clicking on the database file on One Drive which then will open the KeypassXC which is on your computer along with the key file you use for extra security. As the KPxc program boots and displays the screen asking for a password but if this is the second or more times you opened this DB from the computer it already fills in the key file ? input exposing what file is used for the key file to anyone else should it not be you that clicked on the database to open.   It seems the software is not releasing the cache variable for that field which on next run it exposes the key file and location.    For better security, this field should not be allowed to remember what was entered in the past and make the user select everytime. 

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. place the database on the cloud-like one drive, place the KP app on the computer and have the DB extension when opening know to open KP,  Also have on the same computer the Key File that will be used as part of the security
2. Go open the Database by clicking on the DB file on the cloud and letting it cause the computer to book the KP app from the DB ext it recognizes. 
3. After you open your database once putting in the password and selecting the key file and its location close and repeat #2 again.
4.  This time around you only need the password as it already exposes the key File as it displays it instead of clearing that field.  This event occurs after a system reboot also.

Now, this might not be a bug if the idea of the program is to only allow the security feater if someone off-site tries to open the db without the Key File. Otherwise, it serves no security benefit in an office where multiple people are using the same computer that you do not want to have access to the DB.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
I would have thought that the Key File field would clear and be blank between each boot of the app so not to disclose what and where the key file is on the system. 

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
It displays the Keyfile after the first run and not requiring user to select and id it.

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows/Linux/macOS
Desktop Env: Gnome/KDE/XFCE/Mate/Cinnamon
Windowing System: X11/Wayland

**Comment by droidmonkey** [comment]
Just disable the setting to remember key files.
