### ISSUE TITLE
KeePassXC-2.1.4-Win64.zip.sig File is missing

### ISSUE THREAD

**Issue by daleth** [keepassxreboot/keepassxc#577]
When trying to access https://github.com/keepassxreboot/keepassxc/releases/download/2.1.4/KeePassXC-2.1.4-Win64.zip.sig via https://keepassxc.org/download#windows in order to verify the signature, i am redirected to a 404 page. 

## Expected Behavior
Expected a file to compare the checksums. 

## Current Behavior
Error 404 

## Possible Solution
Please add the file or remove the link on the download page. 

## Steps to Reproduce (for bugs)
1. Go to: https://keepassxc.org/download#windows
2. Click on GPG signature of the portable download version
3. Error 404 is displayed. 

Best regards daleth

**Comment by phoerious** [comment]
Thanks for reporting. Will upload the missing file in the evening.

**Comment by phoerious** [comment]
Done. Sorry for the inconvenience.
