### ISSUE TITLE
Consider length of path match in best-matching priority

### ISSUE THREAD

**Issue by bodograumann** [keepassxreboot/keepassxc#5770]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
Currently there are only two extremes:
- the domain and path of the entry match exactly
- only the domain matches

There should be a scale of priorities between these two extremes based on how good the path matches.

My particular use case of having a substring of the site url in an entry already worked previously, but got broken in https://github.com/keepassxreboot/keepassxc/pull/5316.

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )
The following code could be updated:
https://github.com/keepassxreboot/keepassxc/blob/c6bd22aa12c6b0ea1566a8337cee234aef4a59c1/src/browser/BrowserService.cpp#L953-L955

I propose finding the longest matching substring.
Then take its percentage length wrt the longer path of site path and entry path.
Finally scale the result linearly to the interval between 80 and 90.

### For example:
Site URL: https://myorig.in/auth/realms/prod/protocol/openid-connect/auth
Entry 1 URL: https://myorig.in/auth/realms/prod
Entry 2 URL: https://myorig.in/auth/realms/stage

Entry 1 priority:

    80 + 10 * len("/auth/realms/prod/") / max(
        len("/auth/realms/prod/protocol/openid-connect/auth"),
        len("/auth/realms/prod")
    )
     = 80 + 10 * 18 / max(46, 17)
     ≈ 83.9

Entry 2 priority:

    80 + 10 * len("/auth/realms/") / max(
        len("/auth/realms/prod/protocol/openid-connect/auth"),
        len("/auth/realms/stage")
    )
     = 80 + 10 * 13 / max(46, 18)
     ≈ 82.8

If a path matches exactly, this will still be `90` as before.
If both paths are empty we will have `0/0` and can fall back to a priority of `80`.
If one path is an exact prefix of another, the priority will linearly grow from `80` to `90` depending on the relative length of the matching prefix.

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )

My own use case is similar to the above example: a keycloak server with various realms.
I could probably always enter the complete path to make it work with the current implementation.
That would be little inconvenient though and I propose the above solution to cover a lot of related cases.

## Alternative
A simple, more narrow alternative would be to simply add a substring check on paths with a priority of 85.

**Comment by droidmonkey** [comment]
Implemented
