### ISSUE TITLE
Separate password-protected groups

### ISSUE THREAD

**Issue by matt1tk** [keepassxreboot/keepassxc#5773]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
I want to protect my online accounts, but I want to protect certain accounts more than others. For now I just attach a keepassxc database with a different password, but that's a pain (keeping 2 different databases synced across devices is difficult) and I would like if I could simply lock a single folder of logins within a db.

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )
A folder can be "locked" and unlocked with the password, but cannot be unlocked without the initial database's password

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
Some accounts that are worth more than others. I rarely open my db for actual important credentials, so it would be nice to say even if I do get malware that steals my db as I unlock it to get a login for something non-critical (social media), my critical accounts (bank, paypal, btc keys, etc) wouldn't be affected.

**Comment by droidmonkey** [comment]
I think this would be a good feature to extend KeeShare with coupled with #2658 where it would prompt for your credentials prior to mounting the database onto the designated folder.

**Comment by matt1tk** [comment]
Would a special attachment work? Simply extract the attachment to a temp folder, open the DB in a new tab, and if it's edited, add it from the temp folder back to the main DB and update the attachment. (Security issues may arise by dumping to a temp folder, but it's never unencrypted.)

**Comment by matt1tk** [comment]
This got me thinking of [Veracrypt's plausible deniability scheme](https://www.veracrypt.fr/en/Hidden%20Volume.html) as well: 
Imagine a new KDBX database version that stores a small amount of random data in the db, but with standard KDBX headers. 
If you want to add a hidden db, you can create one to overwrite the random data.
The database would need to be tweaked to not contain standard KDBX headers. (They can be re-added for decryption)
What veracrypt does to overcome this to use entirely random data as the container, is try the password you enter with every KDF available. So the steps would be: 

1. On KDBX creation, a blob of random data (with standard KDBX headers) is added to the database.
2. If the user chooses to use the plausibly deniable database, the binary data would be overwritten with a database
3. The user logs into their database. The plausibly deniable secret db is indistinguishable from the default. So even if I give up my password, no one would know if there was a secret database there or not. 

Some issues with this: If the user wanted to expand past the standard size of random data, it would be obvious that the user has a hidden database. Perhaps a slider on database creation (with a disable option) that lets you choose the size of random data would be ideal? You can choose a large 'plausibly deniable' data size, but that doesn't prove that you have one. 

It seems that the KDBX standard is not controlled by you, so perhaps this is out of scope of either the project or keepass.info. If so, that's fine. tis but a _request_.

**Comment by networkException** [comment]
Is there any reason why this got closed? Both the general idea of having inner or per group encryption as well as hiding some things in random bytes sound really interesting and worth looking at.

**Comment by droidmonkey** [comment]
There really is no reason for this feature. The referenced KeeShare enhancement (temporary mounting) would be exactly what this feature is requesting. We are not ever going to implement a "plausible deniability" feature, it is not something that we are either interested in, nor endorse.
