### ISSUE TITLE
keepassxc-proxy and external communication

### ISSUE THREAD

**Issue by moerkey** [keepassxreboot/keepassxc#5774]
## Overview
"lsof -nPi" shows external connections from keepassxc-proxy.

```
keepassxc 31838 user  364u  IPv4 653998      0t0  TCP 192.168.178.21:52356->151.101.0.133:443 (ESTABLISHED)
keepassxc 32258 user   53u  IPv4 657171      0t0  TCP 192.168.178.21:33060->104.18.21.8:443 (CLOSE_WAIT)
keepassxc 32258 user   60u  IPv4 657981      0t0  TCP 192.168.178.21:42894->193.99.144.85:443 (CLOSE_WAIT)
keepassxc 32258 user   77u  IPv4 657983      0t0  TCP 192.168.178.21:48076->66.102.1.109:993 (ESTABLISHED)
```

## Steps to Reproduce
Linux bash: sudo lsof -nPi

## Expected Behavior
Only local connections visible.

## Actual Behavior
External connections are visible.

## Context
Was already handled in https://github.com/keepassxreboot/keepassxc/issues/5067 and https://github.com/keepassxreboot/keepassxc-browser/issues/100 but this now affects thunderbird and keepassxc-mail too. The native-messaging-hosts is maybe sth to look at?!

JFYI and has nothing to do with it: 
- The keepassxc-proxy is not killable. It is restarting itself.
- keepassxc itself is only visible in ps via sudo even if it is started as normal user.

KeePassXC - Version 2.6.2
Revision: e9b9582

Operating System: Ubuntu 18.08
Desktop Env: XFCE4
Windowing System: X11

**Comment by droidmonkey** [comment]
Nothing to do with us

**Comment by moerkey** [comment]
But don´t you want to investigate it on the problem side?
I can lead to mistrust in your app.
Maybe it is worth mention it somewhere like the FAQ or so. :)

**Comment by droidmonkey** [comment]
You're welcome to look at the proxy code: https://github.com/keepassxreboot/keepassxc/tree/develop/src/proxy

There is nothing to investigate because we are literally not responsible for those connections.
