### ISSUE TITLE
Browser Integration vertical tab missing from entries

### ISSUE THREAD

**Issue by colans** [keepassxreboot/keepassxc#5775]
## Overview

After upgrading from Pop! OS 20.04 to 20.10 (the upgrade forced a change from the Debian package to the Flatpak version), the Browser Integration vertical tab is missing from all entries.  As such, I cannot access or add Additional URLs to entries.

## Steps to Reproduce

1. Select any entry in the DB.
2. Search for Browser Integration in the left sidebar.

## Expected Behavior

The Browser Integration tab should appear.

## Actual Behavior

The tab is missing.

## Context

My current version is 2.6.2, but I'm not sure what the original version was immediately after the upgrade.

KeePassXC - 2.6.2
Revision: -

[NOTE]: # ( Pick choices based on your environment )
Operating System: Pop! OS 20.10
Desktop Env: Gnome
Windowing System: Whatever the default is (not sure)

**Comment by droidmonkey** [comment]
Make sure browser integration is enabled and restart keepassxc

**Comment by colans** [comment]
Thanks!  Worked.  (Just needed a restart.)
