### ISSUE TITLE
Appindicator / TrayIcon is not shown when KeepassXC is automatically started on system startup

### ISSUE THREAD

**Issue by philipreimer** [keepassxreboot/keepassxc#5777]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
Appindicator / TrayIcon is not shown when KeepassXC is automatically started on system startup

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Install [gnome-shell-extension-appindicator](https://github.com/ubuntu/gnome-shell-extension-appindicator) using Pamac and enable it in Gnome Extensions.
2. Enable "Automatically start KeepassXC on system startup" (not sure if that is the correct English translation) in KeepassXC settings.
3. Restart computer and login again

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Appindicator / TrayIcon should be shown in the upper right corner

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Appindicator / TrayIcon is not shown.
But KeepassXC is running, as `ps -ef | grep keepassxc` shows.

This only happens when KeepassXC ist autostarted on system startup / login.
If I manually start KeepassXC after logging in, the Appindicator / TrayIcon is shown in the upper right corner.

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.2
Revision: e9b9582

[NOTE]: # ( Pick choices based on your environment )
Operating System: Manjaro Linux
Desktop Env: Gnome 3.38.2
Windowing System: X11

**Comment by droidmonkey** [comment]
Add a delay to startup of KeePassXC

**Comment by philipreimer** [comment]
How do I do that? I tried adding `X-GNOME-Autostart-delay=20` to `~/.config/autostart/org.keepassxc.KeePassXC.desktop`.

But that did not have any effect. Also, whenever I open KeepassXC's settings and then click OK, my changes to `org.keepassxc.KeePassXC.desktop` are removed again.

**Comment by droidmonkey** [comment]
There is an open PR to correct this already

**Comment by philipreimer** [comment]
Looks like it could be an issue of gnome-shell-extension-appindicator itself - see [this issue](https://github.com/ubuntu/gnome-shell-extension-appindicator/issues/250).

The [related PR](https://github.com/ubuntu/gnome-shell-extension-appindicator/pull/260) also mentions this:
>  The qt implementation with the QSystemTrayIcon, which is for example used in the Nextcloud app does not work correctly.
If during application startup it does not detect a StatusNotifierWatcher it does not wait for it show up.

**Comment by droidmonkey** [comment]
Yup that most likely is the problem
