### ISSUE TITLE
Show a System Tray Tooltip when hovered 

### ISSUE THREAD

**Issue by WildByDesign** [keepassxreboot/keepassxc#5780]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
KeePassXC on Windows 10 does not show any System Tray Tooltips. It stands out slightly awkwardly from the other system tray icons because all other systray icons show a basic tooltip.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Hover mouse over KeePassXC icon in system tray

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
KeePassXC should show a tooltip for the icon in system tray on Windows.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
KeePassXC is not showing any system tray tooltip.

## Context (Screenshot Example)
[NOTE]: # ( Give us any additional information you may have. )
![KeePassXC-systray-tooltips](https://user-images.githubusercontent.com/26308319/101179649-83021980-3618-11eb-8a00-ac2106410e6e.png)

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.2
Revision: e9b9582

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 10 (Version 20H2) Build 19042.662
CPU architecture: x86_64
Kernel: winnt 10.0.19042

Thank you for your time. Cheers!

**Comment by droidmonkey** [comment]
Pretty simple fix here https://doc.qt.io/qt-5/qsystemtrayicon.html#toolTip-prop

**Comment by WildByDesign** [comment]
@droidmonkey Would you be willing to consider this fix for milestone _2.6.3_ as opposed to _2.7.0_? Thank you.

**Comment by droidmonkey** [comment]
We are wrapping 2.6.3 today, this will be in 2.7.0

**Comment by WildByDesign** [comment]
I compiled the **hotfix/tray-icon** branch a few days ago and the tray icon fix has been working great. Thank you. I appreciate it that you were able to push this into the upcoming point release (2.6.4).

**Comment by droidmonkey** [comment]
Yah I like it too, thanks for the suggestion
