### ISSUE TITLE
[Feature request] List of sites that are missing 2FAs

### ISSUE THREAD

**Issue by TruthIsIAmIronMan** [keepassxreboot/keepassxc#5781]
I'm not entirely sure how this could be implemented, but I'm imagining something like the **Database Reports**  menu wherein
1. it gets the sites that you have in the database,
1. then compares it to a list of sites that support 2FA
1. then find out which of your entries has no TOTP setup and show that list.

An example, let's say I have this URLs in my database:
1. Google
1. Microsoft
1. Dropbox
1. Reddit
1. Firefox

But I only have TOTP/otp field setup for Google and Dropbox sites and still haven't setup the other three on my keepass database, so the list should show:

1. Microsoft
1. Reddit
1. Firefox

This feature would be really nice to have to see which sites you can still add/enable 2FA security. Cheers.

**Comment by droidmonkey** [comment]
Duplicate #4096
