### ISSUE TITLE
I hope to be able to set the horizontal display view, and a more convenient historical record viewing and comparison tool.

### ISSUE THREAD

**Issue by richex-cn** [keepassxreboot/keepassxc#5782]
## Summary

1. able to set the horizontal display view.
2. more convenient historical record viewing and comparison tool.

## Examples

Just like the Keepass's [KPEnhancedListView](https://sourceforge.net/projects/kpenhentryview/) plugin. Support all fields (standard and custom string) shown in a grid view and horizontal display view.

![image](https://user-images.githubusercontent.com/25103518/101265929-be6e2680-3785-11eb-9c4b-6ff10b61a9db.png)

I haven't found an example of historical record comparison, but I think it is necessary to at least simply view historical records.

## Context

Most computer monitor is horizontally ratio (e.g. 16:9), record may be better display in horizontally view.

More convenient display of history records helps me to view and compare the changes of items, such as adding history records to the tabs and displaying all fields in the table.

**Comment by droidmonkey** [comment]
Duplicate #4244
