### ISSUE TITLE
Feature: "Best of X" password generation

### ISSUE THREAD

**Issue by zauberparacelsus** [keepassxreboot/keepassxc#5785]
## Summary
With the random password generator, add an option to generate a "Best of X" password, where it generates X number of passwords, and chooses the one with the greatest bits of entropy.

## Examples
As an example, if the user specifies 32 as the value for X, then a series of 32 passwords will be generated, and the one with the highest entropy is picked.  Hypothetically, the more passwords generated, the better your odds for getting a password with higher potential entropy.

## Context
Because random passwords have variable amounts of entropy, I will often spam-click the Regenerate Password button until I get one with a higher level of entropy.  This feature would automate that, where it would choose the (theoretically) most secure password out of a series.

(Disclaimer: I am not a security professional, so I do not know _how_ useful this feature would be, if at all)

**Comment by droidmonkey** [comment]
You are getting too hung up on the entropy calculation being a definitive indicator of an "optimal" password. Any password that registers as a great or better entropy is going to be absolutely impossible to crack. The only thing that makes a real difference is the length of your password, not the calculated entropy of a password.
