### ISSUE TITLE
keepassxc icon in outlook search menu

### ISSUE THREAD

**Issue by serial02** [keepassxreboot/keepassxc#5786]
Hello keepasssxc team

I have recently observed that in all browsers the Kepassxc icon appears in the search field of the Outlook email client on the microsoft website. I think the application needs some adjustment.

![Screen Capture_20201206125022](https://user-images.githubusercontent.com/32621790/101295825-b56d6b80-37fe-11eb-9882-f5e03895ebe0.png)

![Screen Capture_keepassxc_20201206200910](https://user-images.githubusercontent.com/32621790/101295915-2f055980-37ff-11eb-82fb-a5046f99c842.png)

![Screen Capture_select-area_20201206201002](https://user-images.githubusercontent.com/32621790/101295919-33317700-37ff-11eb-86c6-68a69dec5c3b.png)

![Screen Capture_select-area_20201206201026](https://user-images.githubusercontent.com/32621790/101295921-36c4fe00-37ff-11eb-96eb-febd542b75c0.png)

**Comment by droidmonkey** [comment]
This is fixed for the next version of the extension.
