### ISSUE TITLE
2 suggestions..

### ISSUE THREAD

**Issue by LucLeduc** [keepassxreboot/keepassxc#5789]
Hi everyone,

I like to ask for two feature that i think would be a good assets.

- When keepassxc locking itself... only the password **field** should be visible..  The keyfile is not necessary because you already sign-in.  So your force to go back and have a few people around you, they won't see the  keyfile.

- When keepassxc locking itself...   The  **parameters** menu in the **tools** menu should be disabled because if someone else have access to the desktop, it can access some data like certificate.

Thank you so much for that software that i use since a mount now.. and the more i use it, the more i like it.

**Comment by droidmonkey** [comment]
First is addressed by #5779 

Second one is not going to be changed. There is nothing sensitive in the settings page, plus all those settings can be obtained through the keepassxc.ini file.
