### ISSUE TITLE
[2.1.4] "Ask always before auto type" does not work

### ISSUE THREAD

**Issue by Germano0** [keepassxreboot/keepassxc#579]
On version 2.1.4, "ask always before auto type" does not work. When you select auto type, KeepassXC will write user/password without asking for confirmation

**Comment by phoerious** [comment]
Thanks for the report, but please do not delete the issue template.

**Comment by jonathancross** [comment]
Hi @Germano0 What platform(s) are you using?

**Comment by sts10** [comment]
I'm experiencing this behavior as well-- I have "Always ask before performing auto-type" checked but when I do an auto-type (either by hitting `Cmd + v` or right clicking and selecting the auto-type menu option) KeePassXC just performs the auto-type right away. 

I'm using KeePassXC 2.1.4 and macOS 10.10.5. I installed KeePassXC from the DMG on the website (I didn't build it myself), so it has the Autotype extension, as well as KeePassHTTP and YubiKey. I have KeePassHTTP disabled, if that matters.

**Comment by Germano0** [comment]
@jonathancross Fedora 25, Qt 5.7.1

**Comment by epeli** [comment]
I'm seeing this too. macOS Sierra and KeePassXC v 2.2.0. Couple of times I've accidentally googled my password or something like that.

**Comment by droidmonkey** [comment]
This setting works in 2.4.0

**Comment by Germano0** [comment]
2.3.4 still affected by this problem
