### ISSUE TITLE
Document searching for custom attribute values

### ISSUE THREAD

**Issue by rhbvkleef** [keepassxreboot/keepassxc#5790]
## Summary

I only found out after searching in the code that KeepassXC supports searching for custom attributes and their values. I was unable to find this in the user guide. Reading the code to find out how this works shouldn't be necessary.

## Examples

* Show a line in the search help modal.
* Explain how searching for attributes and their values works in the user guide.

## Context
We use KeePass to store shared secrets for some of our virtual machines and hypervisors, and store information about those VM's and hypervisors in custom attributes. It is very useful to be able to search for those attributes and values. Luckily, we've now found out how this works (although it seems to have some weird restrictions), but this should really be something that is documented.

**Comment by Wandmalfarbe** [comment]
@rhbvkleef Would you mind sharing how to search for attribute values? I suspect this issue might be open for a while and I recently needed to do just that.

**Comment by tredondo** [comment]
Documenting an arcane search syntax is useful but misguided.

Searching, by default, should search in attributes as well, because [the user may not know if their search string is in a note, or in an attribute](https://github.com/keepassxreboot/keepassxc/issues/4696).

**Comment by droidmonkey** [comment]
This is already documented: `attr:searchstring` searches both name and values of attributes.
