### ISSUE TITLE
Entry with "ssh" scheme

### ISSUE THREAD

**Issue by protontrigg3r** [keepassxreboot/keepassxc#5791]
## Overview
_KeePassXC-Browser_ return entries with "ssh" scheme even if "_Match URL scheme_" is True.

## Steps to Reproduce
- Create an entry with something like "ssh user@example.com" in URL field
- Set _Browser Integration_ setting "_Match URL scheme_" to True
- Visit https://example.com

## Expected Behavior
_KeePassXC-Browser_ does not return the entry with "ssh" scheme

## Actual Behavior
_KeePassXC-Browser_ return the entry with "ssh" scheme

## Context
KeePassXC - 2.6.2
KeePassXC-Browser - 1.7.3
Operating system: Linux x86_64
Browser: Mozilla Firefox 83.0

**Comment by droidmonkey** [comment]
Scheme would imply ```ssh:\\user@example.com```.

**Comment by protontrigg3r** [comment]
So it shouldn't be returned if "_Match URL scheme_" is _True_, right?

**Comment by droidmonkey** [comment]
How is the url formatted, exactly? That is very important information.

**Comment by protontrigg3r** [comment]
In some cases it is very useful for me to enter the ssh login command in the URL field related to the user's credentials, i.e.: `ssh user@host.com`

**Comment by droidmonkey** [comment]
That is not a url that is a command. You should be adding `cmd://` in front of it

**Comment by protontrigg3r** [comment]
Yes, but this way I can't take advantage of "Copy URL" icon to avoid typing the ssh command

**Comment by droidmonkey** [comment]
If you add cmd:// you can just double click it and it'll open ssh for you! Either way this isn't a bug.

**Comment by protontrigg3r** [comment]
> If you add cmd:// you can just double click it and it'll open ssh for you! Either way this isn't a bug.

I did a quick test and this doesn't seem to be happening (on Ubuntu I would expect to see a new terminal window pop up). But this is not the subject of this issue :-)

In any case, my opinion is still the same: if I am browsing an _https_ site and "_Match URL Scheme_" is _True_, then _KeePassXC-Browser_ should not return entries with a URL field starting with anything other than "_https://_". 

But this is just my personal opinion, so thanks anyway for your much appreciated work :-)
