### ISSUE TITLE
Global Auto-Type key combo that uses current selected entry

### ISSUE THREAD

**Issue by Bob837217** [keepassxreboot/keepassxc#5792]
## Summary
This means you can double click the URL which either opens new tab in your open browser, then you click on the Username field of your website login, press the special key combo in the browser and KeePassXC will use the currently selected entry as the source to copy the user and pass from.

## Context
This matters to me as I don't believe the existing Auto-Type where it attempts to search by the Title of the page that has focus and match upon one or more entries before using that one or ones.  For me, I want to start from KeePassXC to browse for the entry that I wish to use, launch the URL into a browser which now will take input focus, then press a key combo which KeePassXC can capture and then begin the AutoType keystrokes for the entry in question that is already selected.  The existing implementation can remain as is, this is a new AutoType key combo which should not interfere with existing functionality.  Again, KeePass for Windows does perform like this with the AutoType functionality.

**Comment by phoerious** [comment]
What speaks against the basic Ctrl+Shift+V Auto-Type? Since you have to refocus KeePassXC, it's one extra step, but it achieves the same thing.

**Comment by droidmonkey** [comment]
I don't think this will be implemented especially with the new Auto-Type selection dialog.

**Comment by Bob837217** [comment]
> What speaks against the basic Ctrl+Shift+V Auto-Type? Since you have to refocus KeePassXC, it's one extra step, but it achieves the same thing.

My personal workflow (with Windows Keepass) speak against it?  By the way that would be 2 x refocuses actually.  Because the full steps would be:
KeePassXC:
1) Double click the URL to launch a browser tab (browser now has input focus)
2) Switch back to KeePassXC
3) Press CTRL-B (to copy username)
4) Switch back to browser and CTRL-V into the username field
5) Switch back to KeePassXC
6) Press CTRL-C (to copy password)
7) Switch back to browser and CTRL-V into the password field

KeePass (Windows):
1) Double click the URL to launch a browser tab (browser now has input focus)
2) Click on the username field if it doesn't have focus
3) Press CTRL+ALT+W (my chosen global keyboard combo for global autotype)
Done, no step 3 as KeePass will auto type username and password for you

It is significantly easier in the Windows version

**Comment by Bob837217** [comment]
> I don't think this will be implemented especially with the new Auto-Type selection dialog.

I have used the Auto-Type selection dialog and  found issue with that too.  If you have 2 different window title regexes, only one will be used.  ie.
a) "Login Here"
b) "Login*"
I found that one of the above matches would work against an exact title of "Login Here" and no choice to pick b) entry.  The KPXC search should match against all regexes and prepare the multi selection dialog with all matching entries.  To fix this I made both entry regexes the same "Login*" to get the dialog to show me the 2 entries.

During the workaround I was submitting credentials for the wrong website which in itself is a security problem.

**Comment by phoerious** [comment]
> Double click the URL to launch a browser tab (browser now has input focus)
> Switch back to KeePassXC
> Press CTRL-B (to copy username)
> Switch back to browser and CTRL-V into the username field
> Switch back to KeePassXC
> Press CTRL-C (to copy password)
> Switch back to browser and CTRL-V into the password field

You can auto-type both the username and the password in one go.

**Comment by Bob837217** [comment]
> You can auto-type both the username and the password in one go.
Ah, I stand corrected.  After re-reading phoerious post I see that it is possible with CTRL+SHIFT+V as suggested.  Sorry!
Yes, there is one step where I need to switch back to KPXC to initiate autotype with the non-global CTRL+SHIFT+V shortcut.  Certainly easier than the 7 steps in my post above.  Apologies.

**Comment by phoerious** [comment]
The new global Auto-Type dialogue will have a search field where you can directly look for the wanted entry instead of selecting it in KeePassXC first. I suppose that's even easier than your Windows workflow (BTW KeePassXC is available for Windows as well).
I'm closing this here, since given the upcoming Auto-Type rework, we're not going to implement this.
