### ISSUE TITLE
Localisation Mistake

### ISSUE THREAD

**Issue by SteffoSpieler** [keepassxreboot/keepassxc#5793]
## Overview
There's a word, which has "start" twice.

## Steps to Reproduce
1. Be German! (Or use the german language)
2. Go to Settings.
3. In General in "Programmstart"

## Expected Behavior
The word should be "Programmstart".

## Actual Behavior
At the moment the word is "Programmstartstart".

## Context
Since it is german, you need to have the programm in german.

KeePassXC - Version 2.6.2
Revision: e9b9582

Qt 5.15.1
Diagnosemodus ist deaktiviert.

Betriebssystem: Windows 10 Version 2009
CPU-Architektur: x86_64
Kernel: winnt 10.0.19042

Aktivierte Erweiterungen:
- Auto-Type
- Browser-Integration
- SSH-Agent
- KeeShare (bestätigtes und unbestätigtes Teilen)
- YubiKey

Kryptographische Bibliotheken:
 libgcrypt 1.8.6

Operating System: Windows 10 Pro

**Comment by phoerious** [comment]
Localisations are managed on Transifex and (in the future) on Weblate. Please make corrections there.
