### ISSUE TITLE
Startup without inserting master key

### ISSUE THREAD

**Issue by carlogarro** [keepassxreboot/keepassxc#5795]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
When the computer starts up, and KeePassXC with it, avoid having to put the master password.

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
I am using it on my personal computer at home, so I am the only one using this pc. I think it would be nice to have the option to remember the master pass.

**Comment by phoerious** [comment]
Remembering the password means no protection and you may as well save it without a password.

**Comment by droidmonkey** [comment]
I agree, this really isn't behavior or functionality that I endorse at all. It reduces your database credentials to those of your computer. You probably don't use a strong password to login to your computer...

**Comment by phoerious** [comment]
Unless you are using full-disk encryption, not even that.

**Comment by droidmonkey** [comment]
Going with a won't fix on this one.

**Comment by carlogarro** [comment]
But what if it is a desktop computer that you never move from home? I mean, at least to have to option to remember the pass. If someone doesn't want, no problem.

**Comment by droidmonkey** [comment]
We support the command line switch --pw-stdin which will allow you to auto open your database from a script or credential store.
