### ISSUE TITLE
Creating new database and set master password doesn't detect my keyboard layout.

### ISSUE THREAD

**Issue by foordeluxe** [keepassxreboot/keepassxc#5796]
## Overview
When trying to set a master password when creating a new database. 
It wont detect which layout my keyboard use.

So every time I want to type the password it will detect my keyboard as english.
So special characters and stuff is always wrong because of my keyboard.

## Steps to Reproduce
1. Set a master password when creating new database.
2. Doesn't detect my keyboard layout.
3. 

## Expected Behavior
Be able to write special characters for my keyboard.

## Version
KeePassXC - Version 2.6.2
Revision: e9b9582

Operating System: Windows 10 PRO x64 20H2 (OS Version: 19042.685)

**Comment by droidmonkey** [comment]
This is a qt bug
