### ISSUE TITLE
Passwords always shown in clear in List view

### ISSUE THREAD

**Issue by lennartjuette** [keepassxreboot/keepassxc#5800]
## Overview
When viewing the database the passwords are always being shown in clear while the username is hidden behind big dots.
<img width="912" alt="Screenshot 2020-12-10 at 12 33 08" src="https://user-images.githubusercontent.com/1701636/101766976-de824a80-3ae3-11eb-8e05-a2d1e27b2ba0.png">

## Steps to Reproduce
1. Open database attached to the ticket
2. Look at the entries and see unmasked passwords

## Expected Behavior
I expect the passwords to be masked and the usernames to be cleartext.

## Actual Behavior
The passwords are unmasked and in cleartext while the usernames are masked.

## Context
Here's the sample database from the screenshot above (Password: 'test')
[Passwords.kdbx.zip](https://github.com/keepassxreboot/keepassxc/files/5672363/Passwords.kdbx.zip)

The problem occurs with all my databases.

KeePassXC - Version 2.6.2
Revision: e9b9582

Operating System: macOS

**Comment by droidmonkey** [comment]
Check out the view menu

**Comment by lennartjuette** [comment]
I was checking the Preferences dialog for this setting and must have overlooked it in the menus. That was stupid.

Thanks!
