### ISSUE TITLE
Keepass 2 Database Field References do not work in Keepass XC

### ISSUE THREAD

**Issue by BrerRabbit999** [keepassxreboot/keepassxc#5802]
I have not seen any discussion about whether Keepass field references should work or whether they may be implemented in the future.

**Comment by droidmonkey** [comment]
It works exactly the same as keepass. Its in our documentation.

**Comment by BrerRabbit999** [comment]
Then I need to know how to make it work.  All I can find in the documentation is that it exists as an advanced feature.  existing references do not work for me.  Also, how do I make a new one?

**Comment by BrerRabbit999** [comment]
In keepass 2 the references look like URLS and clicking on them opens the referenced item  In my various instances of Keepass XC in Windows and Linux they are just text, not links.

**Comment by droidmonkey** [comment]
Read up: https://keepass.info/help/base/fieldrefs.html

**Comment by BrerRabbit999** [comment]
Yes, I read that and I also compared what the references look like in Keepass 2 but I cannot make the existing references work in Keepass XC Why not?

**Comment by BrerRabbit999** [comment]
I did all that before starting this thread

**Comment by BrerRabbit999** [comment]
Existing field references from Keepass 2 that do work there still do not work in Keepass XC for me

**Comment by BrerRabbit999** [comment]
Oh, I did finally find a reference in your help but I had not thought to look under cloning to find it.  That and finally figuring out how to find the UUID for an entry, which was also a puzzle, makes me think Keepass XC needs a helper like Keepass 2 has to help with manually creating field references.

**Comment by BrerRabbit999** [comment]
I was originally looking at your user guide under the URL:https://keepassxc.org/docs/KeePassXC_GettingStarted.html#_interface_overview.  That does not have any information about cloning as does the URL:https://keepassxc.org/docs/KeePassXC_UserGuide.html#_clone_an_entry.  Could be why I didn't find it the first time.

**Comment by BrerRabbit999** [comment]
None of that helped me figure out why my field references work fine in Keepass 2 but they do not work in Keepass XC.

**Comment by droidmonkey** [comment]
I can't help you without knowing what those references look like.

**Comment by BrerRabbit999** [comment]
The references were created in Keepass 2 using their helper tool in their entry edit window.  In Keepass 2 they are blue in color, indicating (I think) that they are links and when I click on a reference in, say, a username field and copy I get the referenced item rather than the reference text when I paste into a browser.


However, in Keepass XC I now see that in URL, Username and possibly Password fields Keepass XC actually does display the referenced item as Ref: item instead of the field reference, but in the notes section, that doesn't happen.  In a Keepass 2 entry notes field, a field reference like {REF:T@T:<Title>} can be clicked to navigate to that entry, but that doesn't work in Keepass XC.  Your help does not say if the referenced item has to be a UUID, or if references only work in certain fields.   I have some references in notes that are to some field referenced by UUID's such as {REF:T@I:<UUID>} and they do not work either.

So maybe the problem is limited to field references that appear in Notes.

Since it is very difficult to look up UUID's and manually build one in Keepass XC, I have not tried that yet.  I think the Keepass 2 tool also does some syntax validation which I doubt that Keepass XC can do without such a tool.

**Comment by BrerRabbit999** [comment]
I thought I typed <UUID> replacing the actual UUID that I copied out of my file in the correct position in  {REF:T@I:} above, but that dropped out.

**Comment by BrerRabbit999** [comment]
Hmmm.  It dropped out again

**Comment by BrerRabbit999** [comment]
I guess Greater than and Less than enclosing UUID just doesn't get through

**Comment by droidmonkey** [comment]
Ok so you are really talking about how keepass2 converts a reference into a hot link in the edit UI. We do not do that, but that doesn't mean the references are broken. The referenced field will still be used when auto typing, copying, browser extension,  etc.

**Comment by BrerRabbit999** [comment]
In Keepass2 I rely heavily on using field references to 'jump' directly from one entry note display to a related entry (or one of several related entries in some cases) simply by clicking a field reference in the note display area.  Not being able to do that in KeepassXC is one significant inconvenience which, with a few others is preventing me from moving away from needing both programs depending on my current task list.  Thus I would vote to add that functionality to KeepassXC as an enhancement.  If not, more (and easier to find) help on what works and what doesn't.

Since I am not a computer guru I didn't realize that sometimes field references go by different names if they appear in different places.

**Comment by stefan123t** [comment]
@BrerRabbit999 could you explain how you got the UUID of an entry as I am struggling with a similar challenge in #6782 and @Kasonnara is working on some syntax-coloring in #5900 which could encompass your reference field "link" feature too.
Would you be able to describe this Keepass "reference link" functionality you are referring to more closely or give us a documentation link describing it in detail ?

**Comment by droidmonkey** [comment]
You get the uuid from the properties tab when editing an entry
