### ISSUE TITLE
Wrong autotype for some apps in macOS (type aaaaaaAAaaaa)

### ISSUE THREAD

**Issue by Nibir** [keepassxreboot/keepassxc#5805]
## Overview
In some programs in macOS there is strange behavior when i try to autotype password. I got aaaaaa... instead of my password.  

## Steps to Reproduce
1. Create some entry and set to type only password (or use submenu autotype -> PASSWORD)
2. Install double commander https://doublecmd.sourceforge.io/ or use noVNC in chrome 87 (i see that behavior in any chrome)
3. Try to autotype password in any field in noVNC or in bottom text field in double commander

## Expected Behavior
I want to see my password

## Actual Behavior
I see aaaaaaaaaaaaaa or aaaaaAAaAAaaaa in different applications (if my password like "fgrtRf" i see "aaaaAa" instead for noVNC window of "aaaaaa" for double commander.)

## Context
I use autotype for noVNC because noVNC hasn't copy paste function and i need to type my passwords for virtual machines (noVNC is part of proxmox virtualization platform)
Also i found out that in TorBrowser (last) everything works fine with same noVNC window. But in Firefox (last) the same problem like in chrome. 
If i try to autotype in some editor like sublime text it works fine.  
For linux it works fine with chrome. 

I don't think that problem appears only in this cases. I believe there is a lot of apps with that problem.    

     
##About
KeePassXC - Version 2.6.2
Revision: e9b9582

Qt 5.15.1
Debugging mode is disabled.

Operating system: macOS 10.16
CPU architecture: x86_64
Kernel: darwin 20.1.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
 libgcrypt 1.8.6

**Comment by phoerious** [comment]
Pretty sure this is the same thing as #1833.

**Comment by droidmonkey** [comment]
Yup same thing
