### ISSUE TITLE
Change Password (security flaw): Require entering the old password before setting a new one

### ISSUE THREAD

**Issue by hayosc** [keepassxreboot/keepassxc#5806]
## Summary
Given a malicious individual gets access to an unlocked computer with an open KeePassXC database, it is possible to change the password and take away a fully accessible copy of the database. This is a major avoidable security flaw.

To avoid this the user shall be asked to first enter the old password when changing it.

## Examples

1. 
- Attacker Copies original kdbx file
- Opens Database -> Database Security... -> Database Credentials -> Change Password 
- Changes password in open database
- Uploads the kdbx file to somewhere in the cloud
- Closes KeePassXC
- Restores kdbx file
- Re-opens KeePassXC and database
2. 
- Attacker opens Database -> Database Security... -> Database Credentials -> Change Password 
- Changes password
- Attaches a USB stick
- Database -> Save Database as...
- Recent Databases -> Clear History
- Lock database
- Take away the stick.

In both cases the malicious individual gets full access to all passwords. 
In the first case without even having any chance to get aware of the steal.

Whereas, if any user must enter the old password in order to get the data the attacker must
- First entry Ctrl-B, Ctrl-V, Ctrl-C, Ctrl-V to some document
- Second entry Ctrl-B, Ctrl-V, Ctrl-C, Ctrl-V
- asf.
- The legitimate user returns, sees what happens and calls the Sheriff

## Context
At work my observation is that constantly people forget to lock their computer when unexpectedly called to another room. If there is additionally an open KeePassXC password database, the dangerous situation is in place.

**Comment by phoerious** [comment]
If an attacker gets hold of an *unlocked* database, then he already has all your passwords. There is nothing we can do.

**Comment by hayosc** [comment]
@phoerious: This is a community project. It is not up to you to decide within two minutes whether a feature request is valid or not. Unless the feature is already implemented or a duplicate. Give the readers time to discuss this.

>If an attacker gets hold of an unlocked database, then he already has all your passwords.
This statement is wrong. 
If you are all of a sudden standing in front of an open safe with 50 gold bars each 1 kg, does it mean you have all the gold bars? It takes two hours to carry all gold to your car. Would you take that risk?
It takes two hours to copy&paste all the information I have in my kdbx database into a text editor and to save all the attachments. Would you take that risk? 

Be realistic: A thief needs opportunity, criminal energy and a small risk. If it takes too long, the risk is too high. He will take one gold bar in each pocket, walk away and never return.

**Comment by droidmonkey** [comment]
This is not the first time this has been brought up

**Comment by phoerious** [comment]
> @phoerious: This is a community project. It is not up to you to decide within two minutes whether a feature request is valid or not. Unless the feature is already implemented or a duplicate. Give the readers time to discuss this.

I am a core maintainer of this project. It IS up to me to decide whether a feature request is valid or not.

> This statement is wrong.

It is not. And it doesn't take two hours to extract your database. Click Database->Export->CSV File and off you pop. Or simply create a new database and dump everything from the open database into it by drag&drop. There is absolutely nothing we can do if you let somebody unauthorised access your database.
