### ISSUE TITLE
On ubuntu not showing icons for actions

### ISSUE THREAD

**Issue by asikam** [keepassxreboot/keepassxc#5807]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
On ubuntu the icons for pass generator and top level icons add/remove/etc are hidden

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows/Linux/macOS
Desktop Env: Gnome/KDE/XFCE/Mate/Cinnamon
Windowing System: X11/Wayland

**Comment by phoerious** [comment]
Please update your KeePassXC version. This issue has long been fixed. See #4963.

**Comment by asikam** [comment]
I have 2.6.2 and this seems to be the newest version available !!

**Comment by phoerious** [comment]
Then please provide more information and screenshots (without any private information visible).

**Comment by asikam** [comment]
The icons just disappeared from the app on Ubuntu 20.04.1 LTS, 64-bit 
![Screenshot from 2020-12-11 12-20-11](https://user-images.githubusercontent.com/15692972/101893159-0ab5ce00-3bad-11eb-9369-e58f8b72bb85.png)
![Screenshot from 2020-12-11 12-20-42](https://user-images.githubusercontent.com/15692972/101893160-0b4e6480-3bad-11eb-9c2a-674e2dbb2917.png)
![Screenshot from 2020-12-11 12-26-15](https://user-images.githubusercontent.com/15692972/101893163-0be6fb00-3bad-11eb-916d-40e2c6194992.png)

**Comment by phoerious** [comment]
I am 99% sure that this is the same issue. Try the fixes in the issue report I linked.

**Comment by asikam** [comment]
After a restart the icons appeared again !! i did nothing its strange Thanks anyway
