### ISSUE TITLE
Tabular reveal for protected fields

### ISSUE THREAD

**Issue by JohnHind** [keepassxreboot/keepassxc#5808]
## Summary
Some sites demand entry of only specific randomly selected characters from a password for security against keylogging. I find I have to make an Excel table showing the index in column 1 and the characters in column 2, screenshot this and store it as an attachment. It would be much more usable and secure if there was a pop up to display ('reveal') the password in this form.

## Examples
There would be an additional 'reveal' button in protected fields (password and attributes) which would display the password as a table of characters against index numbers:

<img width="47" alt="PasswordIndex" src="https://user-images.githubusercontent.com/2505782/101901223-a264ed80-3ba8-11eb-9f45-a055989d7639.png">

As an additional feature, the user could highlight rows in this table and it would copy just those characters to the clipboard (I find that most such sites allow you to type the demanded characters in sequence without intervening actions).

## Context
For banking sites etc. where they demand specific randomly selected characters by index rather than the whole password.

**Comment by droidmonkey** [comment]
Already done for the next major release
