### ISSUE TITLE
App fails to launch due to missing Apparmor permission with Snapd 2.25

### ISSUE THREAD

**Issue by italy-portugal** [keepassxreboot/keepassxc#581]
## Expected Behavior

The KeepassXC application should start when launched from the command line or from the Application launcher on Ubuntu 17.04 and snapd 2.25

## Current Behavior

When launching from the Application launcher, KeepassXC does not start
When Launching from the commandline:
```
user@home:~$ keepassxc
cannot create lock directory /run/snapd/lock: Permission denied
```
Output in systemd journal:
```
May 17 10:31:30 home.localdomain keepassxc[15246]: cmd.go:114: DEBUG: not restarting into "/snap/core/current/usr/bin/snap" ([VERSION=2.24 2.24]): older than "/usr/bin/snap" (2.25+17.04)
May 17 10:31:30 home.localdomain audit[15246]: AVC apparmor="DENIED" operation="mkdir" profile="/usr/lib/snapd/snap-confine" name="/run/snapd/lock/" pid=15246 comm="snap-confine" requested_mask="c" denied_mask="c" fsuid=0 ouid=0
May 17 10:31:30 home.localdomain kernel: audit: type=1400 audit(1495035090.448:68): apparmor="DENIED" operation="mkdir" profile="/usr/lib/snapd/snap-confine" name="/run/snapd/lock/" pid=15246 comm="snap-confine" requested_mask="c" denied_mask="c" fsuid=0 ouid=0

```

## Possible Solution

Rebuild snap for latest version of snapd

## Steps to Reproduce (for bugs)

1. Install Ubuntu 17.04
2. Update snapd to version 2.25
3. In the terminal, run `sudo snap install keepassxc`
4. In the terminal, run `keepassxc`

## Context

Looking to start using keepassxc as a replacement for a proprietary solution that I would like to move away from.

## Your Environment

* Ubuntu 17.04
* snapd 2.25
* KeepassXC 2.1.4

Output from snap list: 
```
Name       Version  Rev   Developer       Notes
core       16-2     1689  canonical       -
keepassxc  2.1.4    9     keepassxreboot  -
```

**Comment by italy-portugal** [comment]
Restarting my computer solved the problem. AppArmor probably needed to be restarted.

**Comment by TheZ3ro** [comment]
Nice to know ;)

**Comment by Maokei** [comment]
sudo servicectl enable apparmor.service solved this problem for me.
