### ISSUE TITLE
Auto-template option for new entries in specific group

### ISSUE THREAD

**Issue by JohnHind** [keepassxreboot/keepassxc#5810]
## Summary
Add the facility to specify an entry to use as the template for new entries in that group.

## Examples
There would be a new field on the 'Edit  group' dialog in which a reference to any entry to use as a template could be set. If this was left blank (the default) then behavior on 'New entry' in that group would continue as at present. If it was set, then 'New entry' would clone the selected entry (the template) into the group and open it in the entry editor.

## Context
I have groups for ' Inventory' and 'Bank accounts' and also a group were I store template entries for 'Inventory' and 'Bank account'. At present, I have to first clone the template, then move the clone into the correct group, then edit the new entry. This is error prone as sometimes I forget there is a template and invent a different structure and sometimes I accidentally start editing the template itself. With the suggested system, I can simply use 'New entry' as usual and the template will always and automatically be applied.

**Comment by droidmonkey** [comment]
Duplicate #863
