### ISSUE TITLE
Show merge report and offer options per entry

### ISSUE THREAD

**Issue by miragy69** [keepassxreboot/keepassxc#5813]
## Summary (Let me know if this request is duplicate)
It will be handy if we can have a log file function so that we can view what changes after every sync among devices.
When the database file conflict happens among devices, it will be hard to tackle down the stale data. If we can have more explicit functionality to compare the difference between two database files and merge based on the comparison that will be great.

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )
For a single database file, users can see the log history of the database with authentication. Both CLI and GUI options are acceptable. A user adds, deletes, or modifies an entry that should be recorded.

For multiple database files, especially the conflict database file, it should provide a function to compare the difference between two files. For example. The added, deleted or modified entry should be detected between the old and new versions of the file. 

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
Has a version control like management should be a good feature to check data consistency.

**Comment by droidmonkey** [comment]
This is a duplicate request
