### ISSUE TITLE
Cinnamon minimize to tray keeps icon in open windows

### ISSUE THREAD

**Issue by HamburgerJungeJr** [keepassxreboot/keepassxc#5814]
I  have the options "Show Tray" and "Hide window when minimized" activated.
![2020-12-12_10-59_1](https://user-images.githubusercontent.com/11501266/101980926-4d3ce080-3c69-11eb-9a3a-5cdb12941bf0.png)
![2020-12-12_10-59](https://user-images.githubusercontent.com/11501266/101980928-4d3ce080-3c69-11eb-8720-91717edc7dfd.png)

When I minimize the Keepass window it gets minimized to the tray but the icon in the open windows stays visible. 

If I click on the icon I can see the name of my database but the window doesn't open. 
![Bildschirmfoto vom 2020-12-12 10-54-29](https://user-images.githubusercontent.com/11501266/101980929-4dd57700-3c69-11eb-80c0-86e6f45c8bf0.png)

If I open Keepass again from the Tray a new Window gets added to the open windows (It shows now 2 KeePassXC windows in the counter) and If i miminize the new window again it stays at 2 open windows.
![Bildschirmfoto vom 2020-12-12 10-59-01](https://user-images.githubusercontent.com/11501266/101980924-4c0bb380-3c69-11eb-8f77-126c16bd7423.png)

I can remove the Icon from the open windows list by reloading the desktop (Alt+F2, r)

I'm running Fedora 33 with Cinnamon 4.6.7

**Comment by droidmonkey** [comment]
Sounds like a bug in cinnamon

**Comment by HamburgerJungeJr** [comment]
You are right. The problem occures if in Cinnamon the option "Show windows from all desktops"
