### ISSUE TITLE
Support "androidapp" as valid extra URL

### ISSUE THREAD

**Issue by wanno-drijfhout** [keepassxreboot/keepassxc#5815]
KeePassXC does not currently allow me to enter additional URLs of the form `androidapp://com.acme.app`. These URLs are valid and used by Keepass2Android to detect applicable logons, though. It would be good if the URL validation would be less strict on the supported "schemas".

![afbeelding](https://user-images.githubusercontent.com/2872972/101982997-09050c80-3c78-11eb-9c87-e74f68264a55.png)

**Comment by soredake** [comment]
Working in 2.6.1
![изображение](https://user-images.githubusercontent.com/5204968/107530023-2268fd00-6bc4-11eb-9f59-5b46e702df6c.png)
