### ISSUE TITLE
Verifying Signatures instructions for windows has problems

### ISSUE THREAD

**Issue by rickhower** [keepassxreboot/keepassxc#5821]
## Overview
Issue with 
https://keepassxc.org/verifying-signatures/  page 
instructions for 
Basic integrity check - Windows

## Steps to Reproduce
Open a PowerShell window (WIN+R, type in powershell, press <enter>) and change directory to the folder you downloaded the files to

Copy/Paste the following command into the PowerShell window:
(Get-FileHash .\KeePassXC-*-Win64.msi).Hash -eq (Get-Content .\KeePassXC-*-Win64.msi.DIGEST).split(" ")[0].ToUpper()
You should see True appear, if not then the download is invalid or your files are not together.

## Expected Behavior
Response should be 'True'  according to https://keepassxc.org/verifying-signatures/  page 

## Actual Behavior
(Note: I am in the correct folder and have checked that the .msi file is in the folder.  Note:   I tried removing the .\ - no difference) 

Response is:

Get-Content : An object at the specified path .\KeePassXC-*-Win64.msi.DIGEST does not exist, or has been filtered by
the -Include or -Exclude parameter.
At line:1 char:50

... n64.msi).Hash -eq (Get-Content .\KeePassXC-*-Win64.msi.DIGEST).split( ...
                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
CategoryInfo : ObjectNotFound: (System.String[]:String[]) [Get-Content], Exception
FullyQualifiedErrorId : ItemNotFound,Microsoft.PowerShell.Commands.GetContentCommand
You cannot call a method on a null-valued expression.
At line:1 char:1

(Get-FileHash .\KeePassXC-*-Win64.msi).Hash -eq (Get-Content .\KeePas ...
  + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
  + FullyQualifiedErrorId : InvokeMethodOnNull


## Context
I see that in issue #2861 it sez:

In 'Integrity verification instructions on website' issue #2861
wavesurf432 commented on Nov 26, 2019
"Technically on Windows the msi is signed by DroidMonkey Apps, LLC so you don't 
need to do the integrity check. It's built in. You'll see this when UAC asks you 
for permission during install."

##KeePassXC-2.6.2-Win64.msi    Revision: e9b9582

##[NOTE]:
OS:    OS  Windows 10 Version 2009
--================================

SUGGESTION:
----------------
REMOVE  from https://keepassxc.org/verifying-signatures/  page 
instructions for 
Basic integrity check - Windows  for the .msi download
since 
a) it isn't working 
b) as per in issue # 2861 wavesurf432 commented on Nov 26, 2019 "you don't 
need to do the integrity check. It's built in."

Without this correction, the instructions on verification of the download result in confusion if not fright for users who don't spend time researching the issue, which  seems antithetical to the overall purpose of helping folks manage/reduce security concerns (via using a password manager). 

Thank  you !!!

**Comment by phoerious** [comment]
The command is working perfectly fine. You forgot to download the DIGEST ffile.

**Comment by droidmonkey** [comment]
Just replace the * with 2.6.2
