### ISSUE TITLE
2.6.2 fails to compile on Slackware 14.2 (solution offered)

### ISSUE THREAD

**Issue by mlmoser** [keepassxreboot/keepassxc#5822]
The issue is nearly identical to https://github.com/keepassxreboot/keepassxc/issues/3721, but the solution posted by the author of that report didn't work for me.
Apparently the assumptions are correct - libreadline included in SlackWare 14.2 doesn't expose the included libcurses library it's linked to.

The solution that worked for me was editing the build/src/cli/CMakeFiles/keepassxc-cli.dir/link.txt and adding

`/usr/lib64/libcursesw.so `

to the end of the library list.

I assume that there's a better way, but for me, the compile and install completed without further issues.
Thanks.
Mike

**Comment by mlmoser** [comment]
Apparently my intent wasn't clear.  I was *not* asking for a fix; I was documenting a possible solution for any other poor soul who stumbles on to this issue.
The only thing I *did* half-ask was if there was a better workaround (like a cmake flag to include additional link libraries).

**Comment by droidmonkey** [comment]
That solution was given in the thread you linked. They chose some other library to randomly link in, you can add `-lcursesw` to LDFLAGS. Modifying the cmake output files is absolutely not the right solution.
