### ISSUE TITLE
Circumflex key on AZERTY keyboard does not work in Wayland

### ISSUE THREAD

**Issue by Poto-Feu** [keepassxreboot/keepassxc#5824]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

When using an AZERTY keyboard in Wayland, the circumflex key does not work - instead, it just prints the letter without the circumflex. This does not occur in X11. However, pasting a letter with the circumflex in any of the text fields work.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Use the circumflex key with a letter such as i or o on an AZERTY keyboard

## Context
[NOTE]: # ( Give us any additional information you may have. )

This does not work in password fields, in the search bar and when editing/creating an entry.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.6.2
Revision: e9b9582

[NOTE]: # ( Pick choices based on your environment )
Operating System: Fedora 33
Desktop Env: KDE
Windowing System: Wayland

**Comment by droidmonkey** [comment]
Qt bug for sure, please report out to them
