### ISSUE TITLE
Keepass Database Error

### ISSUE THREAD

**Issue by KaylooYT** [keepassxreboot/keepassxc#5825]
Hello, I've copied my Password Database from my old computer to my new one and tried to open the keepassxc database.
But when Im trying to enter the password it sais the database isnt a keepassxc database.

How can I recover the file?

Thanks, 
Miinoo

**Comment by droidmonkey** [comment]
You can't, if it's saying the file is not a keypad database then it is not. Try copying your file again.

**Comment by KaylooYT** [comment]
but obviously it is a keypass database

**Comment by droidmonkey** [comment]
Provide a screenshot of the error message pls

**Comment by KaylooYT** [comment]
https://prnt.sc/w1r73c

**Comment by droidmonkey** [comment]
That message occurs if the database file does not contain the right "magic numbers" at the start of the file. This would mean that either the kdbx file it absolutely corrupted or this isn't actually a keepass database file.
