### ISSUE TITLE
Minor UI Issues (en-US)

### ISSUE THREAD

**Issue by ghost** [keepassxreboot/keepassxc#5826]
## Overview

This is to report minor issues I have noticed in the UI. Since the app’s primary language is English, these do not seem to fall under the heading of “translation issues,” although that is, of course debatable. I took the liberty of removing some of the bug reporting template as it did not seem to apply.

### About KeePassXC → Contributors

- In Patreon Supporters, "Lionel LaskÃ©” is probably not a real name
- List entries for Hebrew and Arabic are right-aligned instead of only the translators’ names, which breaks the formatting

### About KeePassXC → Debug Info

- There is no dash in front of "libgcrypt 1.8.6,” even though all other list entries are so formatted

### Entry → Edit Entry → Browser Integration

- "These settings affect to the entry's behavior with the browser extension.” should probably read “These settings affect the browser extension’s behavior with regard to this database entry.”
- “Additional URL’s” should read “Additional URLs” (no apostrophe)

### Settings → Security

- Lock databases after ~inactivity of~ (implied by the context)
- Forget TouchID after ~inactivity of~ (implied by the context)
- Use DuckDuckGo’s service to download website icons (missing possessive)

## Context

KeePassXC - Version 2.6.2
Revision: e9b9582
Qt 5.15.1
Operating system: macOS

**Comment by droidmonkey** [comment]
I made some of the changes recommended, I disagree with the security setting changes. Also the right-aligned text is a Qt feature that we don't control.
