### ISSUE TITLE
Caret is not shown in search bar

### ISSUE THREAD

**Issue by petersohn** [keepassxreboot/keepassxc#5829]
## Overview
The search bar on the main screen has no caret when the search bar is focused.

![Screenshot_20201214_100807](https://user-images.githubusercontent.com/2822847/102062180-aab16880-3df4-11eb-86b2-277cf47c23e3.png)

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Click on the search bar on the main window.

## Expected Behavior
The search bar should have a caret.

## Actual Behavior
No caret is displayed.

## Context
KeePassXC - Version 2.6.1
Revision: 9a35bba

Qt 5.15.1
Debugging mode is disabled.

Operating system: Gentoo/Linux
CPU architecture: x86_64
Kernel: linux 5.4.72-gentoo-x86_64

Enabled extensions:
- Auto-Type
- SSH Agent
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.6

Operating System: Linux
Desktop Env: Awesome WM
Windowing System: X11

**Comment by droidmonkey** [comment]
#5713

**Comment by petersohn** [comment]
The linked issue is also marked as a duplicate, linked to #5498, which is closed on the ground that it is a Qt bug. As there are other Qt apps that do not produce this issue, there should be some way to make it work?

**Comment by droidmonkey** [comment]
I cannot speak to it, but its definitely not something we are doing, and it doesn't happen on any other platforms.

**Comment by damnms** [comment]
i have not seen this in any other QT application which i use, only keepassxc
