### ISSUE TITLE
change action on double-clicking entry [feature request]

### ISSUE THREAD

**Issue by MidanTahrir** [keepassxreboot/keepassxc#5830]
Hello,

please add an option to change the action when double-clicking an entry.
Currently it is editing the entry, I would prefer to set it to "openurl".
thanks for keepassxc
regards

**Comment by droidmonkey** [comment]
Double click the url cell to open the url. We won't change the default behavior

**Comment by MidanTahrir** [comment]
i wasn't aware of double-clicking the url, sorry
