### ISSUE TITLE
Importing/exporting CSV/HTML with dates does not work as expected

### ISSUE THREAD

**Issue by ysard** [keepassxreboot/keepassxc#5831]
## Overview

Problems/missing doc during the import/export of dates in CSV and HTML files.

## Steps to Reproduce

- Import CSV
- Export CSV
- Export HTML

## Expected Behavior

- Dates are exported properly according to #5346

- ISO 8601 (Ex: 2018-01-02T22:08:12.510696) is quite cumbersome and maybe not used by many softwares.
Timestamps in milliseconds and seconds are widely used.
Thus the importer should be tolerant to such values (See #4557 discussion)

- Note also that the value of a timestamp in seconds is not necessarily an integer; 
if it's derived from timestamp in milliseconds, it's a decimal number (the separator of which can be a period (`.`) or a comma (`,`) depending on the country).
Thus, the following regex are not sufficient: https://github.com/keepassxreboot/keepassxc/blob/56c4967e5dbe90713aea5e4acd73ba13fd7e4819/src/gui/csvImport/CsvImportWidget.cpp#L225
https://github.com/keepassxreboot/keepassxc/blob/56c4967e5dbe90713aea5e4acd73ba13fd7e4819/src/gui/csvImport/CsvImportWidget.cpp#L236

- When date fields are not properly parsed the current date is used, 
which is great but the user should be warned about this.
Warned about this behavior or better: about the fact that parsing is failing.
This would avoid having to notice the problem after importing.

- Finally, the most important thing; the expected types should be specified in the official documentation:
https://keepassxc.org/docs/KeePassXC_UserGuide.html#_importing_csv_file
The user should not have to go through the issues to get the information.

## Actual Behavior

- Modification and creation dates are not exported neither in CSV nor in HTML format.
- Importing dates from a CSV file only supports ISO 8061 format, and does not support milliseconds timestamp,
which is the export format used by Firefox Lockwise (the default password manager of Firefox).

## Context

KeePassXC - 2.6.2
Revision: e9b9582

Operating System: Linux
Desktop Env: KDE
Windowing System: X11

**Comment by droidmonkey** [comment]
This is already fixed, will be part of 2.6.3

**Comment by ysard** [comment]
Thank you for your quick response but I respectfully disagree.

After testing on the following version:

KeePassXC - Version 2.7.0-snapshot
Version Type: Snapshot
Revision: 404fd94

- [x] The dates are well exported (except in HTML but I suppose that is the expected behavior?).
- [ ] Decimal timestamps are not supported (the code has not changed since 2.6.2 anyway)
- [ ] The expected types are not mentioned in the doc.
https://github.com/keepassxreboot/keepassxc/blob/develop/docs/topics/ImportExport.adoc
- [ ] The user is not warned that the conversion will fail.

The timestamp in seconds is much more problematic than the time in ISO 8601,
especially since it is internally reconverted in milliseconds.
Thus, ISO 8601 allows precision that a timestamp (integer) in seconds does not.

This is a compatibility issue with other programs.

Please reconsider this portion of the code :)

Would you accept a PR on this?

**Comment by droidmonkey** [comment]
We are not making further changes to the date format acceptability. There is a live preview to confirm the import, so yes there is a warning of sorts.

**Comment by droidmonkey** [comment]
I am not aware of any form of unix time that has a decimal or comma in it, the whole point is second precision based off of jan 1, 1970 start point.

**Comment by droidmonkey** [comment]
Thought about this a little more, I would accept a pr that converts a seconds timestamp with decimal to milliseconds timestamp, as well as strips the milliseconds from iso format.
