### ISSUE TITLE
Access to Gnome online accounts

### ISSUE THREAD

**Issue by popelop** [keepassxreboot/keepassxc#5833]
## Summary
When a distant directory is mounted with Gnome connect, it doesn't appear in the file explorer when doing Database -> Open database. 
It seems it is related to the way Gnome connect mounts the distant directory so I guess other applications may have the same issue. 
Note I can access to the distant content from LibreOffice and Veracrypt. It may be related to the fact these applications seems to use Nemo as a file explorer. 

## Context
Gnome account seems to be the default desktop synchronization client on Linux distribution using this desktop environment (at least Linux Mint cinnamon). But in KeepassXC FAQ, it is said: 
"Q: Why is there no cloud synchronization feature built into KeePassXC?
 A: Cloud synchronization with Dropbox, Google Drive, OneDrive, ownCloud, Nextcloud etc. can be easily accomplished by simply storing your KeePassXC database inside your shared cloud folder and letting your desktop synchronization client do the rest. We prefer this approach, because it is simple, not tied to a specific cloud provider and keeps the complexity of our code low. ". 
So this feature would be useful in order to access to distant database e.g. from Google cloud (or any other cloud compatible with Gnome connect). This allows to get the database synchronized and accessible from other sources without having to copy it in local.

## System
Linux Mint 18.2 Cinnamon

**Comment by droidmonkey** [comment]
Are you using the snap install?

**Comment by popelop** [comment]
I installed keepassxc via the official PPA (ppa:phoerious/keepassxc)

**Comment by droidmonkey** [comment]
Yah so we've seen this before, its a Qt deficiency with older versions of Gnome and Qt.
