### ISSUE TITLE
Upgrade to v2.6.2 on Ubuntu Tray Icon stopped working

### ISSUE THREAD

**Issue by rogercreagh** [keepassxreboot/keepassxc#5835]
## Overview
After upgrade to 2.6.2 on Ubuntu 20.04 (or possibly due to concurrent Ubuntu minor upgrade) the tray icon is no longer appearing in the top right corner. 

## Steps to Reproduce
1. Keepassxc v2.62 
2. Ubuntu v20.04.1 Gnome v3.36.8 X11 windowing
3. 

## Expected Behavior
If settings are set to "Show a system tray icon" and "Hide window to system tray when minimised" then an icon (colourful or monochrome) should appear in the top right bar on the screen. It worked fine until today's update, now it will not appear and the window icon appears permanently in the menu bar (on left or bottom) which is a nuisance/distraction/waste of space as Keepassxc is mostly used as a background app with the browser integration. 

## Actual Behavior
Tray icon no longer appears

## Context
What more can I say? 

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.2
Revision: e9b9582

Qt 5.12.8
Debugging mode is disabled.

Operating system: Ubuntu 20.04.1 LTS
CPU architecture: x86_64
Kernel: linux 5.4.0-58-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.5

[NOTE]: # ( Pick choices based on your environment )
Operating System: /Linux/
Desktop Env: Gnome/
Windowing System: X11/

**Comment by droidmonkey** [comment]
You are missing tray package for gnome to actually show the icon.

**Comment by rogercreagh** [comment]
@droidmonkey - not true. The appindicator package was there before and still is. 

It turns out that it may be an update to that package that has caused the problem as it only happens if Keepass is started on startup. If you start it once the system has settled down then the icon does appear.

**Comment by droidmonkey** [comment]
Yes you need to delay keepassxc startup. You didn't include that detail :wink:

**Comment by rogercreagh** [comment]
It wasn't necessary until the upgrade to appindicator from 33-1 to whatever the current is. Downgrading appindicator to 33-1 has fixed the problem.
I don't see any way, apart from by starting them manually, to delay the start of keepassxc either in Startup Applications or in the Keypassxc settings - am I missing something?

**Comment by droidmonkey** [comment]
We fixed this in #5724

**Comment by rogercreagh** [comment]
So it looks like the 2 sec delay isn't long enough to work with gnome 3.36.8 and gnome-shell-extension-appindicator 34, but does work with gnome 3.36.8 and appindicator 33.1...
... (not long enough in some circumstances).
Perhaps the delay could be configurable?
