### ISSUE TITLE
When the window is narrow, and the search bar hidden, the user should still be able to search entries

### ISSUE THREAD

**Issue by martin-sweeny** [keepassxreboot/keepassxc#5837]
## Summary
When the window is resized to be narrow enough that the search bar is hidden, the user is unable to search at all. The user should be able to at least use the key combo (ctrl+f) to show and use the search bar. 

![image](https://user-images.githubusercontent.com/3329959/102297949-3b379800-3f1e-11eb-9f16-6ce3094be062.png)
> The search bar is hidden

## Examples

![image](https://user-images.githubusercontent.com/3329959/102297985-51455880-3f1e-11eb-8a7e-994b1066c9b9.png)
> The search bar can be revealed by clicking the dropdown on the far right

## Context
I keep KeepassXC on my secondary monitor alongside my calendar. KDE doesn't have as robust snapping as, say, Windows 10, so (unless I want to manually resize both windows every time) I end up just delegating half the screen to each. This causes KeepassXC to hide the search bar, making it unusable.

**Comment by droidmonkey** [comment]
Duplicate

**Comment by martin-sweeny** [comment]
@droidmonkey Which issue number is this a duplicate of? I'd like to watch it.

**Comment by droidmonkey** [comment]
#505
