### ISSUE TITLE
Add a delay to hiding the hidden buttons when the window is narrow

### ISSUE THREAD

**Issue by martin-sweeny** [keepassxreboot/keepassxc#5838]
## Summary
When the KeepassXC window is narrow enough, buttons in the menu are hidden. They can be revealed with the dropdown on the far right, but as soon as the mouse exits the menu bar, they're hidden. A short delay should be added to handle accidental mouseouts.

## Context
I keep the sensitivity on my mouse high, and I keep KeepassXC alongside other windows. I often have to use the dropdown to use the search bar, but the mouse often leaves the menu area. I find myself trying multiple time to avoid leaving the mouse area. This is even more exacerbated by movement of the mouse when I take my hand off of it to type my query into the search bar

**Comment by droidmonkey** [comment]
This is not something we control, it is a part of Qt. I do agree that it is rather sensitive to mouse out, but its not a configurable item.
