### ISSUE TITLE
Can we get two-channel autotype?

### ISSUE THREAD

**Issue by kubycsolutions** [keepassxreboot/keepassxc#5846]
## Summary
One of the features of KeePassX is an autotype option which deletes a number of characters from the data, sends that reduced string through cut-and-paste, then sends a mix of cursor-motion and character keystrokes to fill in the deleted characters. The argument is that this obfuscations helps protect against at least some key-loggers or paste-buffer loggers; an attacker would need to make the effort to track both to obtain the password. Admittedly this has to be optional since it doesn't work for all programs -- some don't like pasting passwords, some don't like autotyping  -- but when it does work, I find it reassuring.

KeePassXC does not seem to have an equivalent two-channel autotype mechanism. Did I miss it, has it simply not been implemented yet, or is there a reason you've dropped it?

## Examples
Using KeePassX, if the two-channel flag is set for a record then autotyping PASSWORD occurs by copy-pasting a randomly selected subset of the string (eg, PSRD), then sending keystrokes to repair the deletions (eg left, left, left, A, S,, right, W, O) before sending the ENTER.

## Context
As noted above: This may improve security somewhat. And to be honest, it looks neat, and serves as a visual confirmation that the data is indeed coming from the password store. It's the one feature of KeePassX that I've missed most when trying to move to KeePassXC.

(I'm running KeePassXC on Windows, but I believe KeePassX supports two-channel obfuscation on other platforms as well.)

**Comment by droidmonkey** [comment]
No thank you. This was already discussed.
