### ISSUE TITLE
Drag&drop

### ISSUE THREAD

**Issue by admin60** [keepassxreboot/keepassxc#5847]
## Summary

Drag&drop of folders and entries would be very nice.

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )

## Context

Moving (sub)folders to other folders and moving entries from one folder to another would help a lot.

**Comment by phoerious** [comment]
Drag and Drop has always been a feature. If it doesn't work for you, you are probably a macOS user affected by #5636.
