### ISSUE TITLE
Updating FF to 84.0 immediately breaks KeepassXC Browser ext functionality (Firefox bug or?)

### ISSUE THREAD

**Issue by succeedmr123** [keepassxreboot/keepassxc#5848]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

Newest Firefox update breaks KeepassXC (can not establish connection with the database)

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Update Firefox
2. Witness inability of KeepassXC to establish connection with database
3. Fumble around with deleting enc key in settings in Firefox extension side, or KeepassXC side.. EDIT: losing one hour -until it works only with full extent of manual uninstalling-reinstallling extension

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Just for KPXC/FF mix work flawlessly altogether EDIT: without the need to reinstall the extension manual and lose 1 hr of personal production time. hope this guide fix solution will help someone save theirs from losing theirs

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

As in brief summary

## Context
[NOTE]: # ( Give us any additional information you may have. )

Edit: Context is that even breaking focus from production speed down to explaining this bug is unconfortable.
However, time was taken during inspection till solution have been made by total uninstall and reinstall KeepassXC browser extension - nothing else helped. Is it one of the notorious Firefox instabilities 

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.6.2
KeePassXC-Browser - 1.7.3

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 10 64 bit

**Comment by droidmonkey** [comment]
Thanks, we have a troubleshooting guide on our website and our user guide documentation. There doesn't seem to be a problem on our end and your troubleshooting steps are exactly whats in the troubleshooting guide.
