### ISSUE TITLE
Default search should include groups (folders) in addtion to entries

### ISSUE THREAD

**Issue by tsaockham** [keepassxreboot/keepassxc#5849]
## Summary
When using he search bar at the top of the window, the search results should also include group (folder) names

## Examples
<img width="853" alt="Screenshot_2020-12-18_at_13_26_35" src="https://user-images.githubusercontent.com/15480610/102619770-df932780-4134-11eb-815c-9eb2758983c9.png">

## Context
I tend to group my passwords using the grouping feature, so when searching it would be more useful for me to have a hit on a group rather than a single entry.  Would really make my life a lot easier now I've invested in the structure of keepass over the years.  Thank you!

**Comment by phoerious** [comment]
Click the search icon and select "Limit search to selected group".

**Comment by droidmonkey** [comment]
Also use the `group:` search field to narrow by group name

**Comment by tsaockham** [comment]
Thanks, would be nice if it did this by default, but happy with this solution.

**Comment by phoerious** [comment]
It used to, but everybody (including myself) got very annoyed by it.

**Comment by oceanBT** [comment]
It would be a cool feature if the user could configure whether the groups should always be searched as well.

**Comment by nod0n** [comment]
I'm using the KeePassXC search quite a lot, I'm using `g:/something` (`/` is important), `u:someuser`, `p:somepw` a lot. For it would be most often usefull, to not have to search twice if I want to find every entry that has a specific string somewhere (title, user, password, note, url, path (group), every other field). I can the filter it more precisely if I get to many entries. For me having at least the possibility to include the path (groups) by default would be wonderful!
