### ISSUE TITLE
Accessing files outside of the home dir using the Snap app

### ISSUE THREAD

**Issue by QasimK** [keepassxreboot/keepassxc#585]
I am unable to access files outside of the home directory and the app's special snap directory. I am trying to open a KeePass file on a second hard drive which is mounted at `/media/me/storage` by Ubuntu.

## Expected Behaviour
The ability to gain access to files on the network or on other hard disks.

## Current Behaviour
No files or folders are visible outside of `~/` and `~/snap/keepassxc/n/`.

## Possible Solution
I'm not sure how Snap works but ideally you would be able to specify that certain locations are okay for the app to access.

## Steps to Reproduce (for bugs)
1. Attach an encrypted ext4 formatted hard disk internally to your PC
2. Unlock and mount the drive using Ubuntu GUI
3. Attempt to open a file on that disk through KeePassXC

## Context
I just want to be able to open KeePass files from other places

## Your Environment
Ubuntu 17.04

KeePassXC 2.1.4
Revision: cb283bb95ae559d044415f426f841c27bff383f0

Using:
- Qt 5.6.1
- libgcrypt 1.7.2-beta

Extensions:
- KeePassHTTP
- Autotype

**Comment by droidmonkey** [comment]
You have to explicitly type in the directory name in the open dialog in order to get there. This is a limitation in the snap system unfortunately. Arbitrary directories under / are still restricted though. /home and /media are accessible.

**Comment by QasimK** [comment]
@droidmonkey Thanks, that workaround worked! I've also just seen similar recent issues #547 #526 #400 

I think it's clear that there is a substantial usability issue with the snap package under not-uncommon use cases. There is no documentation on how to deal with mounted devices. I fear that many more issues will be opened that are basically this until documentation is added front and centre on the snap package.

I suggest the download the snap package has a small link to important notes which will mention how to use this. What do you think?

**Comment by droidmonkey** [comment]
This issue is common to ALL snaps. I am providing feedback to the snapd developers on this and other issues.

**Comment by TheZ3ro** [comment]
Maybe we can include this in the FAQ on the website?

**Comment by droidmonkey** [comment]
Yah that would be great

**Comment by droidmonkey** [comment]
Oh great, I am glad they finally added a permissions tool. Snaps and Ubuntu Store are evolving constantly and this is a very old issue (in that regard).
