### ISSUE TITLE
Accented characters don't work when KeePassXC is installed from Snap

### ISSUE THREAD

**Issue by andrade** [keepassxreboot/keepassxc#5854]
## Overview
Accented characters don't work in KeePassXC installed from snap.

## Steps to Reproduce
1. Install from snap: `$ sudo snap install keepassxc`
2. Open DB and try typing characters (in e.g. notes or password field) with accents: `ä`, `ö`, `ô`, `ã`, etc

## Expected Behavior
We should get the characters that we type (`ã`), not the non-accented versions (`a`).

## Actual Behavior
Characters don't appear properly, we get the version without accent like `a` instead of `ä`.

## Context
There are multiple ways to install KeePassXC according to the official [downloads page](https://keepassxc.org/download/#linux). The accents work in KeePassXC when installed from Ubuntu repositories (`Version: 2.4.3+dfsg.1-1build1`) and from [Launchpad](https://launchpad.net/~phoerious/+archive/ubuntu/keepassxc) (`Version: 2.6.2-1ppa1~focal1`), but not when installed from snap.

My current solution is to use the Official Ubuntu PPA (Launchpad) instead of snap since both cases appear to have the latest version of KeePassXC.

Already uninstalled the snap version but I'm getting this from `snap info`:
`latest/stable:    2.6.2 2020-10-21 (1136)`

Operating System: Ubuntu 20.04
Desktop Env: Gnome
Windowing System: X11

**Comment by felipeaf** [comment]
Same here. Flatpak version works fine (this bug doesn't occurs in flatpak version). 

 I didn't have tried others distribution. I already have unninstalled snap versions, but i have tried in both 2.6.4 (latest/stable) and 2.7.0 (latest/beta), and both has this bug.
 
 Ubuntu 20.04, Gnome

**Comment by droidmonkey** [comment]
Can you try downloading and installing this test run of a new snap package approach?

https://launchpad.net/~droidmonkey/+snap/keepassxc-test/+build/1325383/+files/keepassxc_2.6.4_amd64.snap

`sudo snap install keepassxc_2.6.4_amd64.snap --dangerous`

**Comment by felipeaf** [comment]
Sure, but it doesn't found qt. Should i install any other snap?

```
$ keepassxc
/snap/keepassxc/x1/usr/bin/keepassxc: /snap/keepassxc/x1/usr/lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5.12' not found (required by /snap/keepassxc/x1/usr/bin/keepassxc)
```

**Comment by droidmonkey** [comment]
Wondering why it's looking for 5.12, the snap is built with Qt 5.9

**Comment by Andrade** [comment]
I got the same error as @felipeaf 

```
$ sudo snap install keepassxc_2.6.4_amd64.snap --dangerous
keepassxc 2.6.4 installed
$ keepassxc
/snap/keepassxc/x1/usr/bin/keepassxc: /snap/keepassxc/x1/usr/lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5.12' not found (required by /snap/keepassxc/x1/usr/bin/keepassxc)
```

**Comment by fabio-blanco** [comment]
I got the same problem on an Ubuntu 20.04 with KeePassXC v2.6.6 installed through snap.

Is there anyone looking for a solution?... Or should I uninstall the snap version and choose another installation method?

**Comment by droidmonkey** [comment]
Use another install method

**Comment by fabio-blanco** [comment]
> Use another install method

Ok, I will consider that the snap version of KeePassXC is problematic and avoid it now on.
