### ISSUE TITLE
Provide (convenient) method of specifying two-click autotype target window

### ISSUE THREAD

**Issue by deliciouslytyped** [keepassxreboot/keepassxc#5855]
## Summary
Due to human or window manager error, it may be unnerving to use autotype for fear of typing the password into the wrong window.

It would be nice if the autotype right-click menu item had a submenu, or somesuch, where you could click the target window that should be typed into.

This is different from the feature for specifying it statically in the autotype expression. (I'm not sure if this is actually a thing, but I got the impression from looking for other issues)

The flow would be something like:
- right click db entry
- navigate to target window in menus
- click window
- autotype types into window

**Comment by hifi** [comment]
The per-entry auto-type is very awkward to use. I suggest you switch to global auto-type hotkey with the confirmation dialog always enabled. Would that work for you or is there something specific that you find about the per-entry auto-type better over the global shortcut?

**Comment by droidmonkey** [comment]
With the new Auto-Type selection dialog we will not be implementing this.
