### ISSUE TITLE
Passing database contents to helper program

### ISSUE THREAD

**Issue by c4rlo** [keepassxreboot/keepassxc#5857]
I would like to suggest a feature whereby the user can initiate a helper program/script of their choice with the unencrypted/unprotected database contents passed as input.

My particular use case is for backing up my database file to various locations, re-encrypted with different passwords. The logic required for this is too custom to make sense in KeePassXC itself. In this, there are similarities with the discussion in #4513.

I could see a few different ways of doing this and would love to see what others think.

1. Ability to configure an external program that receives the password database on standard input, re-encrypted to an empty/absent password. Once configured, the program can be invoked from the _Tools_ menu.
    - Open question: should this be part of the global settings, or the per-database settings? I tend to favour the latter, since we are otherwise vulnerable to someone tampering with the global settings and thereby tricking the user into invoking a malicious tool rather than the intended one. On the other hand, the path to the helper program might only make sense on a particular machine (but that does not seem like a huge deal to me).
2. Instead of supporting this directly, support saving a copy of the database that is re-encrypted to an empty/absent password to a different filesystem location, such that the helper program can set up a FIFO (named pipe) at that location and listen to it (read from it). Currently, saving a database file does not work with FIFOs (at least on Linux); version 2.6.2 hangs when trying to do this, while the latest `develop` version replaces the FIFO with a regular file.

However this is solved, I would be very happy to help implement this.

**Comment by droidmonkey** [comment]
I'm sorry but we won't be implementing either of those options. We have decided not to support script calls within keepassxc (also known as triggers). Additionally, we would never endorse via gui option the ability to save out your database without any real protection. 

I you give more context perhaps we can lead you to a much better solution.

**Comment by c4rlo** [comment]
So I have a custom script that decrypts my password database and re-encrypts it with another password (stored in the database itself) before uploading it to the backup location. Without going into the details, suffice to say I don't want this backup copy to be encrypted with my primary database password, hence doing it this way.

This setup works today, but I need to enter my database password when I run the script, even if the database is already open in a KeePassXC window. And it would be nice to avoid having to re-enter the password.

I did explore a couple of alternatives already:

1. KeeShare. This saves the "share" file on every database save, which I don't want; I want to initiate it manually. Also, I'd rather deal with plain KDBX files and not involve these share files. In general, I'd like to avoid this feature due to the extra complexity it brings.
2. The Secret Service D-Bus interface. This main problem here is that once I enable this, every process on the system has access. There may be ways of limiting that using polkit that I haven't fully researched yet, but it would get pretty complicated, and the final workflow probably won't be as simple. The other issue is that KeePassXC exposes only partial information via the Secret Service interface, not the full database. I could work around that by including an entry that has the database password as a note, but I would like to avoid that as well.

One other option that would kind-of work is to have a wrapper script that prompts for the password, then tells the KeePassXC GUI to open the database using D-Bus (`org.keepassxc.MainWindow` method `openDatabase`), then does the database backup. It just means the backup is tied to unlocking the database, which isn't too terrible but not quite as flexible as I'd like.

**Comment by phoerious** [comment]
Sounds to me like you are using a weak password, but want a stronger one for your remote backup. I recommend you start using a YubiKey.

**Comment by droidmonkey** [comment]
This sounds like a good use of a key file. Just store your database without modification to cloud storage and NEVER store your key file in there. This is an exact effect of changing the database password since an attacker of your cloud storage would never have access to your key file.

The even better option is to use a Yubikey or OnlyKey.

**Comment by c4rlo** [comment]
Thanks for the suggestions, but these don't quite fit my use case.

How about an option to invoke a script with a version of the database that has been re-encrypted to another password (not blank) that is configured inside the database?

Or even just an option to save a re-encrypted version of the database (again with a pre-configured alternative password) to a different file path?

**Comment by droidmonkey** [comment]
We don't understand why you are going through this trouble. Every script you introduce is another point of attack, every password change you make does not increase your security.

**Comment by c4rlo** [comment]
Understood. As maintainers, you need to weight the potential benefit of a new feature such as this against complexity and future maintenance costs. As I said, I would be happy to implement the feature myself, but if it won't be accepted due to these considerations, I understand.

**Comment by phoerious** [comment]
Probably not. Sounds very unstable and easy to break to me.
