### ISSUE TITLE
Tray Icon not themed after update to version 2.6.2

### ISSUE THREAD

**Issue by mifidord85** [keepassxreboot/keepassxc#5858]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
After upgrading from version 2.5.4 to 2.6.2 the tray icon in my xfce-panel no longer uses my system theme (in this case Papirus) but just falls back on the icons in the hicolor folder. In the changelog for version 2.6.0 I can see that a lot happened regarding icons and theming (especially relevant is #4161 I think). My issue is only with the tray icon, everything else looks perfect. So when I downgrade again to version 2.5.4 the tray icon is using my system theme again.

Image of the [panel](https://imgur.com/CtzGiUw.png).

## Context
[NOTE]: # ( Give us any additional information you may have. )

I am not quite sure if this is intended or if it is a bug, so my question is, is it possible to just have the tray icons use the system theme? I understand the decision to use one single theme inside the application, but the tray icon should be themeable in my opinion.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.6.2

[NOTE]: # ( Pick choices based on your environment )
Operating System: Arch Linux
Desktop Env: XFCE
Windowing System: X11

**Comment by phoerious** [comment]
Working as intended. You see our app icon, not some random hicolor one.
