### ISSUE TITLE
Prevent Screenshotting of Sensitive Data [Security]

### ISSUE THREAD

**Issue by h-h-h-h** [keepassxreboot/keepassxc#5859]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )

Currently, malware/spyware can just screen-capture sensitive data displayed by KeePassXC, including the master password or just the length of it (depending on eye button state).

Windows provides an API to prevent that, which should be used: [`SetWindowDisplayAffinity(hWnd, WDA_EXCLUDEFROMCAPTURE)`](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-setwindowdisplayaffinity). This will just make the whole window black in screenshots.

To aid software documentation, articles about the software and such, it seems to be necessary to make the behavior adjustable.

There could be the following three modes of screenshottability:

- <q>Always</q> &mdash; As currently. When the user switched to this mode, which could have been temporarily necessary, just the next app start with this mode could trigger a dialog that asks the user whether they want to keep that mode. (Could be implemented by generically saving the last session's mode and comparing.)
- <q>Never</q> &mdash; If the user prefers, in case of a malware attack, to not even leak information about what their database contains. Should be the default in my opinion.
- <q>When Not Showing Passwords</q> &mdash; Makes an app window only unscreenshottable if it shows the most sensitive of data, which would include passwords (also in password generator; also key files, hardware keys or more?). To keep the window screenshottable as much as possible, it could just be made unscreenshottable when a password field contains more than zero characters. To prevent leaking the length of the all-determining master password, it could be argued that even password fields that just display dots instead of the actual characters should trigger unscreenshottability.
  - This mode could be left out, if it's not deemed important enough, because it would significantly increase implementation complexity.

If you decide against the last mode, a single menu entry may be the best: "Allow Screenshots Till Next Start", which will change to "Prevent Screenshots"/"Prevent Screenshots Again", if selected. (Behavior self-explanatory; not explained by modes above.)

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )

[How a window looks like when it's not screenshottable.](https://duckduckgo.com/?q=SetWindowDisplayAffinity&t=h_&iax=images&ia=images)

New menu entries for behavior adjustment:

```
Database   Entries   Groups   Tools   View   Help
                                      +-------------------+
                                      | [...]             |
                                      | Screenshottable > |+------------------------------+
                                      +-------------------+| • Never                      |
                                                           |   When Not Showing Passwords |
                                                           |   Always                     |
                                                           +------------------------------+
```

```
Database   Entries   Groups   Tools   View   Help
                                      +-----------------------------------+
                                      | [...]                             |
                                      | Allow Screenshots Till Next Start |
                                      +-----------------------------------+
```

```
Database   Entries   Groups   Tools   View   Help
                                      +---------------------+
                                      | [...]               |
                                      | Prevent Screenshots |
                                      +---------------------+
```

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )

This is about one vector where protection of user data is overdue should be the default behavior.

**Comment by droidmonkey** [comment]
Worth a test, I wouldn't include any in-app option just a command line switch to disable it (with a warning shown). This would allow reviewers and doc writers to capture screenshots.

**Comment by jonasstein** [comment]
Alternatively one could print the passwords a character per frame
`SECRET`

as

```
SE
  CR  
    ET    
```

**Comment by phoerious** [comment]
That's an extremely awkward solution. With 30 characters at 60Hz, your password would make your eyes bleed.

**Comment by mara004** [comment]
Could screen capture protection also be implemented on Linux, maybe at least for Wayland?

**Comment by droidmonkey** [comment]
Provide a reference and we can look into it. X11 definitely not, there is no security.

**Comment by mara004** [comment]
I'm not sure whether that helps, but maybe `https://github.com/mupuf/libwsm`

**Comment by mara004** [comment]
and https://www.x.org/releases/X11R7.6/doc/xextproto/security.html x11 security extensions, maybe section `image security`

**Comment by phoerious** [comment]
I never thought I'd read X11 and security in one sentence. Lol.

**Comment by stdedos** [comment]
> `keepassxc --allow-screenshot`

` --allow-screencapture` nowadays (_for anyone landing here_)
