### ISSUE TITLE
Add a prompt for a password prefix for double blind password

### ISSUE THREAD

**Issue by dorfsmay** [keepassxreboot/keepassxc#5861]
## Summary
Some users have started to add prefix to their passwords that is not saved anywhere, to prevent the use of their passwords in case their password manager gets compromised. This usage prevents password managers password auto-fill. A feature could be added:
- add a flag on each entry specifying if the entry uses a double blind prefix or not
- make the flag off by default on existing entries
- add a setup flag making new entries defaulting to using the double blind prefix or not
- when a keepassXC database is unlocked, prompt for the double blind prefix if any entry is setup with an existing one
- Use the double blind prefix for password auto-fill on entries using it

## Context
This is a good way to make password more resistant to password manager database compromises. A series of articles are promoting the usage of double blind password:
- https://www.allthingssecured.com/tips/password-security/double-blind-password-strategy/
- https://kaizoku.dev/double-blind-passwords-aka-horcruxing

**Comment by droidmonkey** [comment]
This is silly. If your manager is compromised or your master password is compromised, what stops an entity from compromising your double blind as well?  You are far better off using actual two factor authentication using a hardware key.

**Comment by dorfsmay** [comment]
If somebody manages to decrypt the database, for example through a master password compromise, then they don't have access to the double blind prefix since it isn't stored anywhere.

**Comment by phoerious** [comment]
That's exactly what you have a YubiKey for, so a compromised password doesn't give you access to the database in the first place. Having to remember parts of your passwords kind of defeats the purpose.

**Comment by droidmonkey** [comment]
This is a waste of time for everyone involved, end users and developers.
