### ISSUE TITLE
KeepassXC cannot open database when synced with "Backup + Sync from Google"

### ISSUE THREAD

**Issue by Yoshi8765** [keepassxreboot/keepassxc#5865]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
KeePassXC cannot open database on GDrive Backup folder.

## Steps to Reproduce
Not sure why this started happening, so these steps may or may not be useful.
1. Use "Backup + Sync from Google" in order to sync the root directory in GDrive with a local folder on machine. Uncheck all other subdirectories in GDrive. (I only have my database file in root directory, everything else is in folders)
2. Open database with KeepassXC, make some edits. Save.
3. In a different profile on the local machine, open up the database with KeepassXC.

## Expected Behavior
Should open databases in any situation.

## Actual Behavior
Perplexingly, it seems that Windows is not providing permissions for KeepassXC to open the database.
![image](https://user-images.githubusercontent.com/11256209/103104545-caa71000-45dc-11eb-9a21-9b4bcca5e5a9.png)
![image](https://user-images.githubusercontent.com/11256209/103104547-d397e180-45dc-11eb-9cea-f9fab23b1640.png)

## Context
So this is frustrating me a lot. It's puzzling.
Previously I was using Keepass. In KeepassXC, some shortcut keys are gone, I can live with that. I also really loved Google Drive sync for databases, and I understand KeepassXC's reasoning of why it's not natively supported in the program. Still, I think it can be an option, but I can live with it. Totally fine with using other programs to sync. So I've been using Google's "Backup + Sync from Google", which works fine.
I also switch between two different window users for work + play. I've been using KeepassXC for about a week, and I'm starting to get used to it. So far, great. 
Suddenly today, I switched over to my work user and tried to open my database, and I can't (see screenshot 1 above). My password is correct. I checked to see if the database was open on my play user, and it was, so I closed it. Went back to work user, still same issue. I tried to manually re-open the database, and I get a perm error (screenshot 2). I thought maybe some other program is locking it from being edited (although I would assume read access is still available?). Google Sync was reporting a failure to sync too, so I decided to override ownership.
Both my user profiles are Administrators, so I added the Administrator group to have full access to the database file. Just for good measure, both accounts individually too. Google Sync now works again.
Going back to KeepassXC... still doesn't work. And **the most puzzling of all** is I still get the perm denied error in screenshot 2.

What is going on??? Does KeepassXC not run in my user profile? Why did it suddenly break?

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.2
Revision: e9b9582

Qt 5.15.1
Debugging mode is disabled.

Operating system: Windows 10 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.19042

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.6

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows

**Comment by phoerious** [comment]
With UAC enabled, your user is not actively using the Administrator role unless you start KeePassXC with elevated privileges. So allowing access for Administrators is probably not enough. You should grant permission to the Users group or better: or your user in particular (Full access). You should also be the owner of the file, although that's not strictly necessary if you already have full access through ACLs.

**Comment by droidmonkey** [comment]
Get your permissions squared away first, Google sync could be running as an administrator (yikes).

**Comment by Yoshi8765** [comment]
It's been a few hours and I appreciate the quick responses.
@phoerious I had explicitly given permissions to both users using the "Security" panel in the file Properties. In there, there's an Advanced window you can open that lets you specify what user has which perms. 
Well, just opened it now. Only my play user had perms (???). I gave perms to my work user. No problems anymore.
Not sure what happened and why it didn't work a few hours ago. Jeez. Anyways, thanks both for your input.
