### ISSUE TITLE
TOTP on KeepassXC is different and invalid against TOTP codes generated from other TOTP apps

### ISSUE THREAD

**Issue by Qoyyuum** [keepassxreboot/keepassxc#5866]
## Overview
Setup a TOTP on KeepassXC and providing the 6 digit security code to any app returns "Invalid code or expired" or similar messages from any site or application with 2FA option.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Login to Github (or any other service site but for a simple example to reproduce, I'm setting trying this out on Github) and navigate to the settings/security on the Github account
2. Enable 2FA with Authenticator app
3. Download Recovery Codes, click Next
4. Click "Enter text" instead of scanning QR code. Copy the Secret Key text.
5. On KeepassXC, logged in to a database, navigate to the account that has the password to Github, right-click and select "Setup TOTP".
6. Paste the text into the "Secret Key" field. Leave the defaults. Click OK.
7. Copy the TOTP
8. Supply the TOTP code to Github
9. Github will display "Invalid code or expired".

Tried with Lastpass Authenticator app and its generating a different set of codes and that was accepted by Github.

## Expected Behavior
After step 8, I was expecting Github or any service to accept the TOTP code generated from KeepassXC.

## Actual Behavior
Github and any other service that I've tried rejects the generated TOTP code from KeepassXC.

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.2
Revision: e9b9582

Qt 5.15.1
Debugging mode is disabled.

[NOTE]: # ( Pick choices based on your environment )
Operating system: Windows 10 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.19042

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.6

**Comment by droidmonkey** [comment]
Our totp works perfectly, check your system time. I can't speak for the other applications.
