### ISSUE TITLE
Microsoft Edge (Chromium) Dev need Google Chrome integration enabled

### ISSUE THREAD

**Issue by F3000** [keepassxreboot/keepassxc#5867]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

In the settings there are several browser to choose for browser integration . 

I have installed MS Edge Chromium Dev under OSX Big Sur 11.1 

The browser extension only work when "Google Chrome" is activated .

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. 
2. 
3. 

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

The browser extension should work when user choose "Edge" checkbox in the settings .

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION
Revision: REVISION

**i use M1 MacBook Air 2020**

KeePassXC - Version 2.6.2 Revision: e9b9582 Qt 5.15.1 Diagnosemodus ist deaktiviert. Betriebssystem: macOS 10.16 CPU-Architektur: x86_64 Kernel: darwin 20.2.0 Aktivierte Erweiterungen: - Auto-Type - Browser-Integration - SSH-Agent - KeeShare (bestätigtes und unbestätigtes Teilen) - YubiKey - TouchID Kryptographische Bibliotheken: libgcrypt 1.8.6

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS Big Sur 11.1 ARM version

**Comment by droidmonkey** [comment]
What is MS Edge Chromium _Dev_ ? We don't support beta versions of browsers because they do stupid crap with their profile folders. This isn't a bug for regular Edge on MacOS.

**Comment by Daniel41550** [comment]
You can set a custom browser configuration for use with the Microsoft Edge betas. If you go to the advanced tab of browser integration, set the browser type to chromium, and set the config location to "/users/[username]/Library/Application Support/Microsoft Edge [Dev/Canary]/NativeMessagingHosts", it should work without having any of the browser options checked. Mine is currently set to "/users/Daniel/Library/Application Support/Microsoft Edge Canary/NativeMessagingHosts" and it works fine.
