### ISSUE TITLE
Gtk unsupported with Wayland on Fedora Linux,the window buttons as a result are not visible!!!

### ISSUE THREAD

**Issue by xzj8b3** [keepassxreboot/keepassxc#5868]
![Schermata da 2020-12-26 19-09-51](https://user-images.githubusercontent.com/26720956/103157023-40fb6c00-47af-11eb-9ea8-ff96b91b9656.png)

If you could solve the problem of the top bar that seems to malsupport the Gtk theme with Wayland in Fedora 33 Linux 64 bit would be really great, because unfortunately so are not visible buttons in the window and then creates some hiccups in the use!

I take this opportunity to wish happy holidays to the whole team.

2.fc33
x86_64
keepassxc-2.6.2-2.fc33.src.rpm
@System
updates

**Comment by droidmonkey** [comment]
We don't control the top bar, that's the window managers job. We are also not a gtk app.
