### ISSUE TITLE
Documentation: User Guide does not match program.

### ISSUE THREAD

**Issue by jlturriff** [keepassxreboot/keepassxc#5871]
## Overview
For Database Settings, the panes and their descriptions in the User Guide do not match what the program displays.

## Steps to Reproduce
1. View the online User Guide, section Database Settings.
2. Open KeePassXC
3. Go to Tools -> Settings -> Security
4. The User Guide shows panes for Database Credentials, etc.
5. The program shows checklists for Timeouts, Convenience and Privacy.

## Expected Behavior
The User Guide should describe behaviour of the actual program.

## Actual Behavior
The User Guide shows information about features that the program does not display.

## Context
Fresh install of KeePassXC.

KeePassXC - Version 2.6.2
Revision: e9b9582

Qt 5.9.7
Debugging mode is disabled.

Operating system: openSUSE Leap 15.1
CPU architecture: x86_64
Kernel: linux 4.12.14-lp151.28.75-default

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.2

Operating System: Linux
Desktop Env: Trinity
Windowing System: X11

**Comment by phoerious** [comment]
You clicked the wrong button. You need to go to Database settings, not just settings.

**Comment by jlturriff** [comment]
Ah, geez, you're right.  Colour me embarrassed.
