### ISSUE TITLE
Import from 1Password Database

### ISSUE THREAD

**Issue by philippbeer** [keepassxreboot/keepassxc#5876]
## Overview
# Cannot import 1password database successfully.
I get a: "Read Database did not produce an instance
Unable to decode masterKey: Malformed OpData01 due to a failed HMAC"

## Steps to Reproduce
1. Choose Option: Import from 1Password
2. Select existing 1Password database, e.g. main.opvault
3. Enter 1Password masterkey
4. Error message in KeepassXC appears.

## Expected Behavior
My assumption is that these are all required steps to import the 1password database.

## Actual Behavior
I get the following error message:
"Read Database did not produce an instance
Unable to decode masterKey: Malformed OpData01 due to a failed HMAC"

## Context
I have copied the .opvault-files I use. I have added the ".txt" extension as found in an oder bugreport. But this behavior seems to have change, i.e. you can now directly select the .opvault
![error message](https://user-images.githubusercontent.com/2444835/103347960-d9883980-4a98-11eb-8d8a-2a8365d7297d.jpg)

KeePassXC - Version 2.6.2
Revision: e9b9582

Qt 5.15.1
Debugging mode is disabled.

Operating system: macOS 10.16
CPU architecture: x86_64
Kernel: darwin 20.1.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
 libgcrypt 1.8.6

Operating System: macOS

**Comment by droidmonkey** [comment]
Are you using 1Password version 7? Are you sure you are entering the correct password? The error message implies bad password or corrupt opvault.

**Comment by philippbeer** [comment]
Thank you for the quick response. I am using 1Password 6 (not 7). The vault works fine in the sense, that I can use it with 1Password 6.

Does this help? Do you need additional information?

**Comment by phoerious** [comment]
We only support version 7.

**Comment by philippbeer** [comment]
Thank you for the explanation. Could you also tell me what the best strategy is to transfer the vault to keepass. I wouldn't want to buy an upgrade for 1Password to version 7. I tried the csv export. There keepass informed me, that the csv is malformed. Is there a relatively easy pass for transition given my setup? Thank you for your time.

**Comment by orihomie** [comment]
I have the same issue with 1Password version 7.

**Comment by andig89** [comment]
I have the problem too (OpData01). I bought 1P7 only for data transfer and now I have to copy all my keys by .csv...? I have KeePassXC 2.7.1.

**Comment by droidmonkey** [comment]
We only support import of the OPVault format and if that doesn't work then we'll need far more detail to even begin to diagnose. Your best bet is to use the CSV transfer if you can't get the opvault to work for you.

**Comment by andig89** [comment]
Ok, I found the problem. You can't import if You use local diacritic characters like è, ł, etc. in Your password.

**Comment by droidmonkey** [comment]
Yah that's a known qt bug when the password is hidden.

**Comment by tastycode** [comment]
> Ok, I found the problem. You can't import if You use local diacritic characters like è, ł, etc. in Your password.

Are you f#$!#@$ kidding me? I don't really understand how the whole world hasn't just moved to unicode for all purposes these days. I've used a non-typeable unicode character in my password for any password i create in the last 10 years. I'd be happy to get a dev environment for this running and fix this, but....

> Yah that's a known qt bug when the password is hidden.

Would imply that showing the password should make the problem go away?

**Comment by droidmonkey** [comment]
Yes, show the password to type a dead key character
