### ISSUE TITLE
Import from 1Password 7 database

### ISSUE THREAD

**Issue by philippbeer** [keepassxreboot/keepassxc#5881]
## Overview
# Cannot import 1password database successfully.
I had opened this ticket yesterday which was closed due to the fact that my 1Password version was 6 and not 7. Therefore, I upgraded my 1Password version to 7 and still receive the same result as before. Do you have an idea what I may be doing wrong?
![error message](https://user-images.githubusercontent.com/2444835/103417954-23eae280-4b8d-11eb-9752-a2597f6bf154.jpg)

I get a: "Read Database did not produce an instance
Unable to decode masterKey: Malformed OpData01 due to a failed HMAC"

## Steps to Reproduce
1. Choose Option: Import from 1Password
2. Select existing 1Password database, e.g. main.opvault
3. Enter 1Password masterkey
4. Error message in KeepassXC appears.

## Expected Behavior
My assumption is that these are all required steps to import the 1password database.

## Actual Behavior
I get the following error message:
"Read Database did not produce an instance
Unable to decode masterKey: Malformed OpData01 due to a failed HMAC"

## Context
I have copied the .opvault-files I use. I have added the ".txt" extension as found in an oder bugreport. But this behavior seems to have change, i.e. you can now directly select the .opvault
![error message](https://user-images.githubusercontent.com/2444835/103347960-d9883980-4a98-11eb-8d8a-2a8365d7297d.jpg)

KeePassXC - Version 2.6.2
Revision: e9b9582

Qt 5.15.1
Debugging mode is disabled.

Operating system: macOS 10.16
CPU architecture: x86_64
Kernel: darwin 20.1.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
 libgcrypt 1.8.6

Operating System: macOS

**Comment by droidmonkey** [comment]
Are you sure you are using the right opvault?

**Comment by philippbeer** [comment]
I am using the vault that I use for syncing across multiple devices. They work on all devices. So I assume: Yes, I am using the correct vaults.

**Comment by droidmonkey** [comment]
try changing your opvault password to reset the master key. This error comes up because integrity checks are failing when attempting to decode the master key of your opvault.

**Comment by philippbeer** [comment]
Thank you @droidmonkey ! This resolved my issue.

**Comment by droidmonkey** [comment]
Sweet, good to hear!
