### ISSUE TITLE
Main window pops up after password dialog in browser

### ISSUE THREAD

**Issue by ghost** [keepassxreboot/keepassxc#5882]
## Overview
The main window pops up after password dialog in firefox browser, 
## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
You go to login page
password dialog pops up letting you choose the account
then it closes after you choose

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
You go to login page
password dialog pops up letting you choose the account
the dialog closes but the main window pops up

## Context
[NOTE]: # ( Give us any additional information you may have. )
Im using kubuntu with KDE plasma and KWin window manager
I have installed it as a snap package

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.6.2
Revision: e9b9582

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: KDE plasma
Windowing System: X11

**Comment by tusooa** [comment]
Can reproduce. Really annoying.

**Comment by droidmonkey** [comment]
This is fixed on develop branch, will be out with 2.7.0
