### ISSUE TITLE
Opera GX integration

### ISSUE THREAD

**Issue by marquel83** [keepassxreboot/keepassxc#5883]
Is there a possibility to implement Opera GX integration into KeepassXC-Browser? I know there've been some issues and answers connected with Opera integration and the common answer was to check the Chrome/Chromium integration. Unfortunately it doesn't work with GX. Or maybe at least a step by step manual would suffice.

**Comment by droidmonkey** [comment]
We won't support a one off browser like that, you'll have to setup the native messaging integration manually.
