### ISSUE TITLE
version 2.6.2 error trying to add ssh key 

### ISSUE THREAD

**Issue by pcause** [keepassxreboot/keepassxc#5884]
## Overview
I am using 2.6.2 on windows.  I create a new entry, add my private RSA key as an attachment and then go to the ssh tab.  When I select that attachment I get an error saying it unknown cipher DES-EDE3-CBC. Tried on Fedora and fails there as well.

Th key itself is good and works fine on Windows, Fedora and Ubuntu.

The key was generated on an Ubuntu system.  Is this a bug or are the docs inadequate in specifying what key formats are supported.

**Comment by droidmonkey** [comment]
You are using a legacy key format, we do not support that. See https://github.com/keepassxreboot/keepassxc/issues/1783#issuecomment-733446617
