### ISSUE TITLE
Unlock password doesn't recognize characters using international keyboard with dead keys

### ISSUE THREAD

**Issue by kackburt** [keepassxreboot/keepassxc#5886]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
Special characters using dead keys (e.g. umlaut) not recognized when entering database password (hidden mode) to unlock.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Create a new database with a password including characters created with dead-keys f.e. umlaut (ä, ö, ü,...)
2. Set keyboard layout to US international with dead keys 
3. Try to open the created database while the password is hidden (when the password is not hidden it works as expected = workaround atm.)

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Password characters should be recognized / entered correctly.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Special characters using dead keys (e.g. umlaut) are recognized as a blank character.

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.6.1
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux, Pop!_OS 20.10
Desktop Env: Gnome
Windowing System: X11

**Comment by droidmonkey** [comment]
This is a qt bug.
