### ISSUE TITLE
Some folders not loaded

### ISSUE THREAD

**Issue by shaimo** [keepassxreboot/keepassxc#5887]
I just started using KeePassXC 2.6.2 on MacOS Big Sur, with a kdbx database that was previously created by KeePass or KeePass2. That database contains some entries in the "Homebanking" folder which load just fine e.g. with KeePass 2.46, but here it is empty and the entries are not found when searched. Am I missing anything or is it some issue with loading the database file?

**Comment by droidmonkey** [comment]
Sounds like your database is internally corrupted try resaving it with keepass2

**Comment by shaimo** [comment]
@droidmonkey just the same. Loads just fine on my windows machine with keepass 2.46 but shows empty also after restart on my mac

**Comment by droidmonkey** [comment]
Make sure the file is up to date.

**Comment by shaimo** [comment]
@droidmonkey you were right. I had two files and was somehow using the wrong one. Apologies for the waste of time. Will close this
