### ISSUE TITLE
Prioritizing

### ISSUE THREAD

**Issue by DavidFromNL** [keepassxreboot/keepassxc#5888]
I would like to suggest a function to prioritize entries automatically and/or manually. If keepassxc kept track of how many times a certain entry was used, it would be possible to sort by that value.

For example: I have four entries that are somewhat related to AWS. One I use regularly, the others less than once a month. Optimally, the one used regularly would be on top.

**Comment by droidmonkey** [comment]
Very similar request in #5153 and #4518. Tracking "use" of an entry is rather arbitrary and would require saving the database all the time or using "non-data" saves on exit. Also what would constitute a use? Every time the browser extension _requests_ the entry? Auto-Type usage? Copying a value? Editing it?

Until the linked issues are implemented, your best bet is to append a 1 or * or ! in front of the title and sort by title alphabetically. These entries will sort to the top naturally.
