### ISSUE TITLE
Autotype shift modifier not working

### ISSUE THREAD

**Issue by luisfontes19** [keepassxreboot/keepassxc#5889]
## Overview
Shift modifier is not working with autotype

## Steps to Reproduce
1. Create a new entry
2. Customize the autotype to something like: +{TAB}{USERNAME}{TAB}{PASSWORD}{ENTER}
3. Go to a web page and focus the password field. 
4. Use (global)autotype

## Expected Behavior
A shift tab combination should be typed getting the focus to the username field

## Actual Behavior
Types a '+' in the password field and then hits tab

## Context
According to the [docs](https://keepassxc.org/docs/KeePassXC_UserGuide.html#_configure_auto_type_sequences) Keepassxc supports the same autotype codes as keepass. With keepass doing [+{TAB}](https://keepass.info/help/base/autotype.html#autoseq) will in fact hit shift tab, getting the focus to the previous element

This is quite usefull on apps that save your username, and you need to login with other accounts, or in AWS for example, where before the username you have the account you want to login into.

KeePassXC - 2.6.2
Revision: e9b9582

Operating System: macOS

**Comment by droidmonkey** [comment]
That's cause it was not implemented. It'll be in 2.7.0
