### ISSUE TITLE
Set preferred keyboard layout

### ISSUE THREAD

**Issue by force1164** [keepassxreboot/keepassxc#5890]
## Summary
When I use auto-type, the program fills the credentials with the active keyboard layout. While this is probably the correct behavior, there should be setting for preferred keyboard layout to use instead of the current one. Here are some reasons:
1) I have two layouts. En and Cs. En is my preferred and default, but sometimes I am texting someone in Czech and then I need to fill password somewhere else in my browser and the auto-type fills nonsense because it is "typing" on cs layout (e.g. "2" instead of "@" - which is in every email address - which is almost always login name). Everybody who uses two or more keyboard layouts can probably confirm how annoying this can be. If I have to always check what layout is active and switch to the English one, then the auto type kinda looses its attractiveness..
2) It makes sense to have preferred keyboard for the passwords. Users that create passwords manually have preferred language layout too.
3) official keepass for windows always fills with default layout. - it takes the keyboard layout that is activated for ITS window instead of the target window. 

## Examples
I want to write username: "mymail@my.com" and password: "pass1", but if I have Czech keyboard activated  and it produces "mymail2my.com" and "pass+" instead.

## Context
I have Pop Os 20.10, and Gnome. For each window I can have different keyboard layout. (The same functionality is in windows). 
This setting is not important for reproducing the behavior. Same happens when all windows have same active layout, but it is not the English one (or the default one).

**Comment by droidmonkey** [comment]
#324
