### ISSUE TITLE
[GnuPG] KeePassXC Public Key Expire on 2021-01-07

### ISSUE THREAD

**Issue by aaronhatesregex** [keepassxreboot/keepassxc#5891]
This is a kind reminder that the public key (or subkeys?) will expire soon and please remember to update and upload them.

    $ gpg --fingerprint KeePassXC
    pub   rsa4096 2017-01-03 [SC]
          BF5A 669F 2272 CF43 24C1  FDA8 CFB4 C216 6397 D0D2
    uid           [ unknown] KeePassXC Release <release@keepassxc.org>
    sub   rsa2048 2017-01-03 [S] [expires: 2021-01-07]
    sub   rsa2048 2017-01-03 [S] [expires: 2021-01-07]
    sub   rsa2048 2017-01-03 [S] [expires: 2021-01-07]

**Comment by phoerious** [comment]
The key's validity has been extended last year. Refresh your public keys

**Comment by aaronhatesregex** [comment]
Hi, please take another look, it seems that you updated [public key on Ubuntu keyserver](https://keyserver.ubuntu.com/pks/lookup?op=get&search=0xbf5a669f2272cf4324c1fda8cfb4c2166397d0d2) but not [the key on your site](https://keepassxc.org/keepassxc_master_signing_key.asc).
The public key on Ubuntu goes like the following

    pub   rsa4096 2017-01-03 [SC]
             BF5A 669F 2272 CF43 24C1  FDA8 CFB4 C216 6397 D0D2
    uid           [ unknown] KeePassXC Release <release@keepassxc.org>
    sub   rsa2048 2017-01-03 [S] [expires: 2024-12-04]
    sub   rsa2048 2017-01-03 [S] [expires: 2024-12-04]

and you may want to update the description of "[Verifying Signatures](https://keepassxc.org/verifying-signatures/)" section on your site as well.

**Comment by phoerious** [comment]
I haven't updated the instructions, that's right.
