### ISSUE TITLE
Crash on attemting global Auto-type

### ISSUE THREAD

**Issue by rubaboo** [keepassxreboot/keepassxc#5892]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
New user, the app is crashing almost every time I attempt auto-type.
This is not reproducible 100% of time, but if it was crashing for everyone as often as it does for me, there would be a storm of complaints. It literally crashes most of the time.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )

1. Create a new database
2. Add an entry for a website login
3. Assign a global auto-type shortcut
4. Position the cursor in a username input field in a browser
5. Hit the global auto-type shortcut

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Get a  popup window to confirm the choice.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
The app crashes with the message "The instruction at 0x00007FFFAE4DB4F0 referenced memory at 0x0000000000000008. The memory could not be read."

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.2
Revision: e9b9582

Qt 5.15.1
Debugging mode is disabled.

Operating system: Windows 10 Version 2004
CPU architecture: x86_64
Kernel: winnt 10.0.19041

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.6

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 10, patched up to date.

**Comment by droidmonkey** [comment]
That's a null pointer reference. Would you be ok with running a debug build that creates a crash dump? Https://snapshot.keepassxc.org

**Comment by rubaboo** [comment]
I did, crashed the debug build, and it did not produce a crash dump.

**Comment by droidmonkey** [comment]
Do you have an anti-virus or similar program? This behavior is definitely...unique.

**Comment by rubaboo** [comment]
I hear you. `keepassxc-proxy.exe` got quarantined...
In other news, I just went through a bunch of driver/firmware updates (from the laptop manufacturer site, not Windows updates), and now cannot crash the app anymore :)

Feel free to close this in a few days if I forget.

**Comment by droidmonkey** [comment]
Yup no problem, definitely something outside our control.
