### ISSUE TITLE
Snap connect

### ISSUE THREAD

**Issue by Kry07** [keepassxreboot/keepassxc#5893]
## Summary
I have installed snap brave browser and snap KeePassXC. I edited the file org.keepassxc.keepassxc_browser.js
so it shows the right path "/snap/bin/keepassxc.proxy" The Problem is, that both are sandboxed and keepass can not acces this file. I would like an interface which makes it easy to connect the two snaps with each other.

## Examples
snap connect brave:keepassxs.proxy keepassxc:keepassxc.proxy

## Context
This feature would also be useable for all other browser snaps which can connect with keepass

**Comment by droidmonkey** [comment]
Sorry but that isn't for us to create, you'll have to petition Ubuntu to create a snap to snap native messaging ability.
