### ISSUE TITLE
Adresse mail

### ISSUE THREAD

**Issue by Xgmyst** [keepassxreboot/keepassxc#5894]
Bonjour,
Bravo pour le développement de Keepass XC mais pour moi, il manque une rubrique de saisie importante nécessaire sur de nombreux sites internet : L'adresse e-mail. Cette rubrique pourrait se situer entre le "Nom utilisateur" et le "Mot de passe". Toutes les inscriptions sur internet nécessitent Identifiant + Mail + Mot de passe. Sur Keepass XC, il faut sans cesse ajouter l'information dans Avancé (attributs supplémentaires). Si un jour cette évolution pouvait être réalisée, ce serait parfait.
Merci pour votre investissement et bon courage pour 2021

**Comment by droidmonkey** [comment]
Duplicate #863
