### ISSUE TITLE
Passphrase generator

### ISSUE THREAD

**Issue by theking2** [keepassxreboot/keepassxc#5896]
## Summary
Write a passphrase generator

## Examples
I love the pattern based passphrase generator in keepass

## Context
Can I extend KeePassXC and write the passphrase generator
Placeholder | Type | Character Set
-- | -- | --
a | Lower-Case Alphanumeric | abcdefghijklmnopqrstuvwxyz 0123456789
A | Mixed-Case Alphanumeric | ABCDEFGHIJKLMNOPQRSTUVWXYZ abcdefghijklmnopqrstuvwxyz 0123456789
U | Upper-Case Alphanumeric | ABCDEFGHIJKLMNOPQRSTUVWXYZ 0123456789
d | Digit | 0123456789
h | Lower-Case Hex Character | 0123456789 abcdef
H | Upper-Case Hex Character | 0123456789 ABCDEF
l | Lower-Case Letter | abcdefghijklmnopqrstuvwxyz
L | Mixed-Case Letter | ABCDEFGHIJKLMNOPQRSTUVWXYZ abcdefghijklmnopqrstuvwxyz
u | Upper-Case Letter | ABCDEFGHIJKLMNOPQRSTUVWXYZ
v | Lower-Case Vowel | aeiou
V | Mixed-Case Vowel | AEIOU aeiou
Z | Upper-Case Vowel | AEIOU
c | Lower-Case Consonant | bcdfghjklmnpqrstvwxyz
C | Mixed-Case Consonant | BCDFGHJKLMNPQRSTVWXYZ bcdfghjklmnpqrstvwxyz
z | Upper-Case Consonant | BCDFGHJKLMNPQRSTVWXYZ
p | Punctuation | ,.;:
b | Bracket | ()[]{}<>
s | Printable 7-Bit Special Character | !"#$%&'()*+,-./:;<=>?@[\]^_`{\|}~
S | Printable 7-Bit ASCII | A-Z, a-z, 0-9, !"#$%&'()*+,-./:;<=>?@[\]^_`{\|}~
x | Latin-1 Supplement | Range [U+00A1, U+00FF] except U+00AD:¡¢£¤¥¦§¨©ª«¬®¯ °±²³´µ¶·¸¹º»¼½¾¿ ÀÁÂÃÄÅÆÇÈÉÊËÌÍÎÏ ÐÑÒÓÔÕÖ×ØÙÚÛÜÝÞß àáâãäåæçèéêëìíîï ðñòóôõö÷øùúûüýþÿ
\ | Escape (Fixed Char) | Use following character as is.
{n} | Escape (Repeat) | Repeat the previous placeholder n times.
[...] | Custom Char Set | Define a custom character set.

**Comment by droidmonkey** [comment]
This is the opposite of a secure, randomized generator. This will not be implemented.
