### ISSUE TITLE
Keeps entering the password as a text search in firefox

### ISSUE THREAD

**Issue by pubuduweragoda** [keepassxreboot/keepassxc#5897]
## Overview
When I try to log in into github in firefox using auto-type feature, it enters the username correctly but the password is entered as a page search( as if when searching for text by pressing ctrl+f). (This only happened on github website)

KeePassXC - 2.6.2
Revision: e9b9582

Operating System: Arch Linux
Desktop Env: Gnome
Windowing System: Wayland

**Comment by droidmonkey** [comment]
Increase your typing delay in the application settings, there are known issues with Firefox on Linux and rapid typing.

**Comment by droidmonkey** [comment]
Did that work?
