### ISSUE TITLE
Use KeeShare db w/ Browser Extension

### ISSUE THREAD

**Issue by basbebe** [keepassxreboot/keepassxc#5903]
Maybe I got this wrong but this is what I'm trying to accomplish:

- Have one main keepass db with all my credentials.
- Create KeeShares for different usecases (e.g. a folder with only web logins that gets synced w/ my mobile phone).
- Connect the browser extension to aforementioned (unsigned) synced KeeShare

At this point, this doesn't work.
The connection to the browser extension gets moved from the KeeShare db to the main db and the extension stops working.

Is this something that will work in the future?

Is there a better workflow or a workaroung?

I know I could use multiple databases and autoopen but using KeeShares seems to offer more flexibility.

**Comment by droidmonkey** [comment]
Just connect the browser extension to the main database
