### ISSUE TITLE
URL helpers should be configurable

### ISSUE THREAD

**Issue by symcbean** [keepassxreboot/keepassxc#5905]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
It would be nice if keepassxc allowed URL helpers and their command lines to be defined by the user.

Currently if I invoke a ssh:// url in KeePassxc on my Linux system (Enlightenment desktop) it reports "Could not find 'konsole' executable." on STDERR (nothing displayed in application window). TBH, I don't see the string 'konsole' in the binary anywhere - this maybe a combination of a QT library thing and some remnants of a KDE environment in my $HOME/.config dir
 
## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )

URL                           Action
[ ^https://.*google.* ] [ chromium %url%                               ]
[ ^https{0,1}://         ] [ firefox %url%                                     ]
[ ^ssh://                   ] [ xterm ssh %user%@%url-host%      ]

(but even some documentation on how the existing functionality is implemented would be a help)

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
There is obviously an intention to provide click through functionality - but it does not appear to be working as intended on my machine.

**Comment by droidmonkey** [comment]
You need to fix your url handlers in your operating system. This is outside our scope. We pass the url directly to the os for execution.
