### ISSUE TITLE
Include Last Modified in the exported data

### ISSUE THREAD

**Issue by linuxrichard** [keepassxreboot/keepassxc#5906]
When exporting data, most likely to be able to merge two databases and import back into Keepassxc (e.g. after a conflict with a cloud-stored copy), it would be extremely useful to include the Last-Modified field in the exported data for the CSV format (it is already there in the XML format). Merging data is much easier with CSV formats than XML.

**Comment by droidmonkey** [comment]
Already implemented for next versiob
