### ISSUE TITLE
drag ^ drop not workind on Mac 11.1

### ISSUE THREAD

**Issue by basbebe** [keepassxreboot/keepassxc#5908]
I know about https://github.com/keepassxreboot/keepassxc/issues/5636 but the workaround with reinstalling the app doesn't work (for me) and 2.6.3 hasn't been released yet.

Is there another workaround?
Or is there another way to move items from one group to another?

Thank you!

**Comment by droidmonkey** [comment]
pinned issue

**Comment by basbebe** [comment]
reinstalling using brew did *not* work.

I tried reinstaling again using the .dmg file from the website, which worked for now.

**Comment by davidjiang-gorsline** [comment]
This has been a recurring issue for me - I've reinstalled the software multiple times. Each time it would fix it momentarily but then it it stop working in a few days.

**Comment by phoerious** [comment]
There is no solution at the moment. It is a Qt bug, which we cannot fix.
