### ISSUE TITLE
Change location of custom wordlists on macOS

### ISSUE THREAD

**Issue by basbebe** [keepassxreboot/keepassxc#5909]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
wordlists on macOS are currently only sourced from `/Applications/KeePassXC.app/Contents/Resources` according to the FAQ.

This makes it hard to maintain these wordlists since the contents of `KeePassXC.app` get overwritten with every update or reinstall (see https://github.com/keepassxreboot/keepassxc/issues/5636).

Using something like `~/Library/Application Support/KeepassXC` or `~/.local/share/KeepassXC` would be more appropriate I think.

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )

**Comment by droidmonkey** [comment]
You don't want your wordlists stored in userland. That would make them susceptible to manipulation by a non administrator. We don't endorse modifying the wordlists.
