### ISSUE TITLE
Tray icon gone after "Automatic Screen Lock"

### ISSUE THREAD

**Issue by The-Graphite-Mog** [keepassxreboot/keepassxc#5911]
## Overview
The system tray icon is not shown after the automatic screen lock triggered. It is necessary to open KeePassXC via "Applications"

## Steps to Reproduce
1. unlock database
2. minimize to system tray
3. wait until screen locks automatically (15min in my case)
4. re-login
5. tray icon is not shown

## Expected Behavior
System try icon is shown and database locked

## Actual Behavior
System tray icon is not shown, but database is locked

## Context
Startup-Options that have been ticked:
- Start only a single instance of KeePassXC
- Automatically launch KeePassXC at system startup
- Minimize window at application startup
- Minimize window after unlocking database
- Remember previously used database

KeePassXC - 2.6.2
Revision: e9b9582
Snap

Operating System: Linux (Ubuntu 20.10)
Desktop Env: Gnome
Windowing System: X11

**Comment by droidmonkey** [comment]
This is definitely an issue with whatever tray program/extension you are using.

**Comment by droidmonkey** [comment]
Very similar to #3120

**Comment by The-Graphite-Mog** [comment]
Okay, thanks.
I don't know what tray program it is, it is stock Ubuntu 20.10.

But like @rob151515 said in [#3120](https://github.com/keepassxreboot/keepassxc/issues/3120#issuecomment-745846054), if setting "Lock databases when session is locked or lid is closed' in Security settings" is not activated, the icon appears after screen lock.

**Comment by droidmonkey** [comment]
That's interesting. Maybe it's crashing or whatever when the icon is changed due to locking the databases.

**Comment by jtrakk** [comment]
With the monochrome icon setting, the database-locked icon is invisible for me. It is visible with the colorful icon setting. The unlocked database icon is visible in both cases.

KeePassXC 2.6.2

**Comment by phoerious** [comment]
If you have a light task bar, choose the dark monochrome tray icon and vice versa.

**Comment by jtrakk** [comment]
> If you have a light task bar, choose the dark monochrome tray icon and vice versa.

Ah my mistake, you're right. Thanks.

**Comment by droidmonkey** [comment]
Doesn't seem like anything for us to do here
