### ISSUE TITLE
Support Argon2id

### ISSUE THREAD

**Issue by giwrgosmant** [keepassxreboot/keepassxc#5913]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
Support for Key derivation fuction: Argon2id

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )

![2021-01-11 22_19_56-Database kdbx  Locked  - KeePassXC](https://user-images.githubusercontent.com/51835189/104237289-8206a800-5460-11eb-96f2-2d8247d362b6.png)

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
I cannot open the database.

**Comment by droidmonkey** [comment]
This will be in 2.6.3: https://github.com/keepassxreboot/keepassxc/pull/5778
