### ISSUE TITLE
KeePassXC on Macos 11.0.1 doesn't remember existing database

### ISSUE THREAD

**Issue by SFBdeMac** [keepassxreboot/keepassxc#5917]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
I shut both KeepassXC and my iMac down every night after use.  The next morning after the iMac is up and settled, I start KeepassXC.  The only time  the app remembers the existing database is the day AFTER I've saved that database to a new name.  Two days after said save, KeePassXC no longer knows about the existing database.  I have to use the Mac Finder to navigate to the location of the database, click on it, after which that database shows up in the KeePassXC app's "Unlock KeePassXC Database" window.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. I shut both KeepassXC and my iMac down every night after use.
2. The next morning after the iMac is up and settled, I start KeepassXC. 
3. 

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
The app USED TO show the existing database in the "Unlock KeePassXC Database" window.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
The app doesn't show the existing database in the "Unlock KeePassXC Database" window.

## Context
[NOTE]: # ( Give us any additional information you may have. )
The only time  the app remembers the existing database is the day AFTER I've saved that database to a new name.  Two days after said save, KeePassXC seems to have forgotten about the existing database.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION 2.6.2
Revision: REVISION e9b9582

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows/Linux/macOS  Macos 11.0.1
Desktop Env: Gnome/KDE/XFCE/Mate/Cinnamon
Windowing System: X11/Wayland

**Comment by phoerious** [comment]
Do you have the setting to remember recent databases checked?

**Comment by SFBdeMac** [comment]
Answering phoerious's question: yes, the box to save the "Remember previously used databases" is checked, as is the box below it to "Load previously open databases on startup".  Note there is only ONE database on my Mac.

**Comment by phoerious** [comment]
Do you have minimise on startup enabled together with minimise to tray?

**Comment by SFBdeMac** [comment]
I do not have "minimize window at application startup" nor "Minimize window after unlocking database" checked.  Note there is no "Minimize to tray" option.

BTW, I've upgraded to MacOS 11.2 as well as KeepassXC 2.6.4-2-arm64, thinking that perhaps this bug was fixed somewhere along the line.  Things are now much worse: opening this latest version of KeepassXC results in the message "You can't open the application "KeePassXC.app" because this application is not supported on this Mac"

**Comment by droidmonkey** [comment]
Do you have a Mac based off arm?
