### ISSUE TITLE
Syntax of custom auto-type sequence still checked even though it's not enabled

### ISSUE THREAD

**Issue by Carpenternl** [keepassxreboot/keepassxc#5920]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

Syntax of 'custom auto-type sequence' is still checked while it's been disabled.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Go to Entry → Auto-type
2. Enable 'use custom auto-type sequence'
3. intentionally make a syntax mistake 
4. Disable 'use custom auto-type sequence'
5. save/apply to entry

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
The Entry is saved and the custom-auto type sequence is not enabled/used

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
A syntax error occurs

## Context
[NOTE]: # ( Give us any additional information you may have. )
![afbeelding](https://user-images.githubusercontent.com/11849801/104428592-f2a6e500-5584-11eb-8697-9ef527761dcb.png)

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC  2.6.2
Revision: e9b9582

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows
Windowing System: X11/Wayland

**Comment by droidmonkey** [comment]
Fixed in #5864
