### ISSUE TITLE
Problem switching database to Argon 2id

### ISSUE THREAD

**Issue by basbebe** [keepassxreboot/keepassxc#5922]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

I have an existing database which uses Argon2d which I would like to change to Argon2id.
However, writing seems not to be possible and / or no changes take place.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Go to database settings, change KDF from Argon2d to Argon 2id
2. Press Yubikey a when asked
3.  red banner appears: could not write database. Hardwarekey in use (in German)
4. Press yubikey again when asked
5. nothing happens
6. close database, open again: no change of KDF

When disabling Hardware key authentification and going through the process no red banner appears, it seems like nothing is happening.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
change KDF to Argon2id

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
nothing happens

## Context
[NOTE]: # ( Give us any additional information you may have. )

The folder the database file lies in is synced via Syncthing. Disabling Syncthing and / or Networking doesn't change anything.
Disabling secure save (?) doesn't change anything.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.3
Revision: beae186

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS 11.1 Big Sur

**Comment by phoerious** [comment]
I cannot reproduce this at all. But what I can reproduce is a bug in the settings, which keeps showing Argon2d after changing the KDF, even though the database is using Argon2id. It's just a display bug. If you try opening the database with an older version, you will get an error that an unsupported KDF is being used.

**Comment by basbebe** [comment]
Thank you for pointing that out!

You're right: Strongbox (iOS) seems to not be able to open the database.

Just because I haven't found any reference or documentation on this:  
Which KDF will my created KeeShare files use?  
Is there a way to set it?

**Comment by phoerious** [comment]
The default is still Argon2d.

**Comment by basbebe** [comment]
> The default is still Argon2d.

So all KeeShare files i create will use Argon2d for the time being?  
Thanks!

**Comment by droidmonkey** [comment]
No, keeshare actually creates kdbx 3 using aes with 10000 rounds

**Comment by basbebe** [comment]
> No, keeshare actually creates kdbx 3.1 using aes with 10000 rounds. Something I'll be changing in 2.7.0.

Yes – I just checked and observed the same thing. 

Thank you!

**Comment by utaxiu** [comment]
Right now I updated to latest 2.6.4 release using Snap on Ubuntu 20.04 but I am still experiencing exactly the same issue as @basbebe. I am also using Yubikey for 2FA.

Any ideas?

Thanks :)

**Comment by phoerious** [comment]
I cannot reproduce this on Windows at all.
