### ISSUE TITLE
Long mouse click on menu bar text items closes menu (maps to move window?)

### ISSUE THREAD

**Issue by stevemarple** [keepassxreboot/keepassxc#5925]
## Overview
Anything other than the briefest of clicks in the menu bar closes the menu that was just opened, making it impossible to select items from the menu. 

## Steps to Reproduce
1. Open KeePassXC 2.6.3
2. Click (and hold mouse button down briefly) on any item in the menu bar
3. Menu opens, and then closes

## Expected Behaviour
Clicking on the menu keeps the menu drop-down visible, regardless of actual duration of mouse click. 
a) Menu item can be selected by releasing mouse select  button, navigating to desired item and clicking again.
b) Alternatively menu item can be selected by keeping mouse button depressed and releasing after selecting desired item.

Other programs, and KeePassXC prior to 2.6.3, allow either method to select menu items.

## Actual Behaviour
When the mouse pointer is placed over a menu it is highlighted

If a menu is opened with the briefest of mouse presses then menu drop down remains open.

If the menu is opened with a longer mouse click then menu dropdown appears and almost immediately disappears. Under my desktop environment the window becomes semi-transparent, suggesting this maps to a window move operation. If the mouse is moved during this time the window is dragged.

## Context

KeePassXC - Version 2.6.3
Revision: beae186
Distribution: AppImage

Qt 5.15.2
Debugging mode is disabled.

Operating system: Debian GNU/Linux 10 (buster)
CPU architecture: x86_64
Kernel: linux 4.19.0-13-amd64

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- libgcrypt 1.8.1

Desktop:
 - XFCE 4.12.5 Tango icon theme, XFCE style, geometry 2 x 1920x1200 displays, X11

Debian:
- 10.7

Windowing System:
 - X11

Debian Qt version:
- 4:4.8.7+dfsg-18+deb10u1

**Comment by phoerious** [comment]
I don't want to say it, but: Xfce. 🙄

**Comment by stevemarple** [comment]
It seems I have both Qt 4 and 5 installed, but I guess neither should be relevant for the AppImage version.

**Comment by JCallicoat** [comment]
I have a similar issue happening with 2.6.3 under XFCE 4.16 on arch. When I click any menu item it activates moving the window. I can click several times in quick succession and manage to get the menu to stay open. 

Qt5

```
qtdiag | head -1
Qt 5.15.2 (x86_64-little_endian-lp64 shared (dynamic) release build; by GCC 10.2.0) on "xcb" 
```
keepassxc built locally from release tarball using PKGBUILD here https://github.com/archlinux/svntogit-community/tree/packages/keepassxc/trunk

```
keepassxc -v    
KeePassXC 2.6.3
```

In version 2.6.2 (built locally in the same way) the menus work without issue. Issue also not present in any other Qt apps I have checked.

**Comment by JCallicoat** [comment]
Looks like https://github.com/keepassxreboot/keepassxc/commit/0a0b3a6b4ff26e4dc562ba86f3fb9a99418ff933 is causing the behavior. Building 2.6.3 release with those changes reverted fixes menus for me.

**Comment by JCallicoat** [comment]
Changing the eventFilter to only fire startSystemMove when there is no menubar action under the mouse cursor fixes menus for me and still allows moving the window by clicking empty areas of the menubar. I can submit a PR if this is the correct solution.

```diff
diff --git a/src/gui/MainWindow.cpp b/src/gui/MainWindow.cpp
index d1eb1fe1..89b692a8 100644
--- a/src/gui/MainWindow.cpp
+++ b/src/gui/MainWindow.cpp
@@ -1784,9 +1784,11 @@ bool MainWindowEventFilter::eventFilter(QObject* watched, QEvent* event)
 
     if (event->type() == QEvent::MouseButtonPress) {
         if (watched == mainWindow->m_ui->menubar) {
-            mainWindow->windowHandle()->startSystemMove();
-            // Continue processing events, so menus keep working.
-            return false;
+            auto* m = static_cast<QMouseEvent*>(event);
+            if (!mainWindow->m_ui->menubar->actionAt(m->pos())) {
+              mainWindow->windowHandle()->startSystemMove();
+              return false;
+            }
         } else if (watched == mainWindow->m_ui->toolBar) {
             if (!mainWindow->m_ui->toolBar->isMovable() || mainWindow->m_ui->toolBar->cursor() != Qt::SizeAllCursor) {
                 mainWindow->windowHandle()->startSystemMove();
```
