### ISSUE TITLE
#5820 breaks removing SSH key from agent when database is closed/locked

### ISSUE THREAD

**Issue by yan12125** [keepassxreboot/keepassxc#5928]
## Overview

On 2.6.3 and the `develop` branch, SSH keys in entries with "Remove key from agent when database is closed/locked" checked are no longer actually removed from the agent. `git bisect` points to the following commit:
```
f0204dbb109a8fbaf739c35b9c459d247bdccd88 is the first bad commit
commit f0204dbb109a8fbaf739c35b9c459d247bdccd88
Author: Jonathan White <support@dmapps.us>
Date:   Sat Dec 12 12:08:02 2020 -0500

    Fix closing modal dialogs on database lock
     
    * Fixes #5719, Fixes #5744

 src/browser/BrowserService.cpp       |  4 ++--
 src/gui/DatabaseWidget.cpp           | 10 +++++++++-
 src/gui/MainWindow.cpp               |  5 -----
 src/gui/TotpDialog.cpp               |  8 +-------
 src/gui/TotpExportSettingsDialog.cpp |  1 -
 5 files changed, 12 insertions(+), 16 deletions(-)
```

Also, KeePassXC crashes with segmentation fault upon exit when it tries to remove the key
```
QCoreApplication::applicationDirPath: Please instantiate the QApplication object first
QObject::connect(QCoreApplication, Config): invalid nullptr parameter

Thread 1 "keepassxc" received signal SIGSEGV, Segmentation fault.
0x00007ffff6aac447 in QMutex::lock() () from /usr/lib/libQt5Core.so.5
(gdb) bt
#0  0x00007ffff6aac447 in QMutex::lock() () from /usr/lib/libQt5Core.so.5
#1  0x00007ffff7df944e in ?? () from /usr/lib/libQt5Network.so.5
#2  0x00007ffff7dfab99 in QAbstractSocket::setSocketDescriptor(long long, QAbstractSocket::SocketState, QFlags<QIODevice::OpenModeFlag>) () from /usr/lib/libQt5Network.so.5
#3  0x00007ffff7e1167c in ?? () from /usr/lib/libQt5Network.so.5
#4  0x000055555578d2d0 in SSHAgent::sendMessage (this=this@entry=0x555555a5f040 <(anonymous namespace)::Q_QGS_s_sshAgent::innerFunction()::holder>, in=..., out=...)
    at /build/keepassxc-git/src/keepassxc/src/sshagent/SSHAgent.cpp:133
#5  0x000055555578e3ff in SSHAgent::removeIdentity (key=..., this=0x555555a5f040 <(anonymous namespace)::Q_QGS_s_sshAgent::innerFunction()::holder>)
    at /build/keepassxc-git/src/keepassxc/src/sshagent/SSHAgent.cpp:304
#6  SSHAgent::removeIdentity (this=0x555555a5f040 <(anonymous namespace)::Q_QGS_s_sshAgent::innerFunction()::holder>, key=...)
    at /build/keepassxc-git/src/keepassxc/src/sshagent/SSHAgent.cpp:286
#7  0x000055555578e56d in SSHAgent::removeAllIdentities (this=this@entry=0x555555a5f040 <(anonymous namespace)::Q_QGS_s_sshAgent::innerFunction()::holder>)
    at /build/keepassxc-git/src/keepassxc/src/sshagent/SSHAgent.cpp:410
#8  0x000055555578e7a7 in SSHAgent::~SSHAgent (this=0x555555a5f040 <(anonymous namespace)::Q_QGS_s_sshAgent::innerFunction()::holder>, __in_chrg=<optimized out>)
    at /build/keepassxc-git/src/keepassxc/src/sshagent/SSHAgent.cpp:36
#9  (anonymous namespace)::Q_QGS_s_sshAgent::Holder::~Holder (this=0x555555a5f040 <(anonymous namespace)::Q_QGS_s_sshAgent::innerFunction()::holder>, 
    __in_chrg=<optimized out>) at /build/keepassxc-git/src/keepassxc/src/sshagent/SSHAgent.cpp:32
#10 0x00007ffff62cfdb7 in __run_exit_handlers () from /usr/lib/libc.so.6
#11 0x00007ffff62cff5e in exit () from /usr/lib/libc.so.6
#12 0x00007ffff62b8159 in __libc_start_main () from /usr/lib/libc.so.6
#13 0x00005555555d07ce in _start ()
```

If I revert f0204dbb109a8fbaf739c35b9c459d247bdccd88 (https://github.com/keepassxreboot/keepassxc/pull/5820) on top of the develop branch, SSH keys are removed as configured and there are no crashes upon exit.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Create an entry with an SSH key
2. Check "Remove key from agent when database is closed/locked" for that entry
3. Add the key to the agent from KeePassXC
4. Lock the database

## Expected Behavior
The key is removed from the agent

## Actual Behavior
`ssh-add -l` still shows that key.

## Context

KeePassXC - Version 2.7.0-snapshot
Build Type: Snapshot
Revision: 3b30855

Qt 5.15.2
Debugging mode is enabled.

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 5.10.5-arch1-1

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (only unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- libgcrypt 1.8.7

Operating System: Arch Linux
Desktop Env: LXQt+xfwm4
Windowing System: X11

**Comment by droidmonkey** [comment]
Ugh, this is probably because the sshagent is using the database information AFTER lock. Before it used the information BEFORE locking. I changed that because if locking failed for some reason the keys would be removed anyway. It's probably using invalid information post lock to try and remove the keys.

**Comment by droidmonkey** [comment]
The actual crash is occurring when sshagent tries to cleanup the keys that are still loaded as a result of failing to clean them up during the database locking. It is crashing because that cleanup is occuring for a globally created object which is being destroyed AFTER QApplication is destroyed.
