### ISSUE TITLE
Ctrl+U shortcut conflict on Linux

### ISSUE THREAD

**Issue by guihkx** [keepassxreboot/keepassxc#593]
I use the search function quite often. KeePassXC will always highlight the first search result, so I expect that when I'm done typing and I hit `Ctrl+C`, for example, KeePassXC will copy its password to the clipboard -- and **it does**! However, if I want to open the URL of the first search result by pressing `Ctrl+U`, KeePassXC will actually clear the search field instead of opening it.

## Expected Behavior
Pressing `Ctrl+U` when using the search feature should open the URL of that entry.

## Current Behavior
Pressing `Ctrl+U` clears the search field.

## Possible Solution
Don't use the `Ctrl+U` shortcut to clear input fields. If possible, disable any other shortcuts being used by KeePassXC in input fields.

## Steps to Reproduce (for bugs)
1. Hit `Ctrl+F` to search for something;
2. The first result will be highlighted automatically by KeePassXC, so **do not** selected it again using your mouse (otherwise this bug will not happen, since the focus won't be in the search field anymore);
3. Hit `Ctrl+U` to try to open the URL;
4. It will clear the search field instead.

## Context
I've tried to replicate this on Windows and it didn't work. However, it did work in all Qt5-based programs for Linux I've tested. **Please note that the `Ctrl+U` shortcut doesn't work *only in this situation***.

## Your Environment
* KeePassXC version/commit used: 2.1.4 (cb283b)
* Qt version: 5.8.0
* Operating System and version: Arch Linux x64

**Comment by TheZ3ro** [comment]
The thing is that the focus is on the Search field and so when you press CTRL+U it will clear the text.
When you search you should first press the down key (to get the focus on the first entry) and then pressing CTRL+U to open the URL.

**Comment by GUiHKX** [comment]
I know I can do that, but isn't this unexpected behavior? Because on Windows I wouldn't have to do that... If its not, is there any way to prevent `Ctrl+U` from clearing input fields? Thank you

**Comment by TheZ3ro** [comment]
I don't know it there is a way to prevent this. It's not a KeePassXC defined behavior.

Are you using XFCE on ArchLinux? I'm on XFCE/Ubuntu and I can reproduce this.

**Comment by phoerious** [comment]
Ctrl+U seems to be a standard key sequence on Linux which Qt implements as `QKeySequence::DeleteCompleteLine`. See: https://doc.qt.io/qt-5/qkeysequence.html#standard-shortcuts

**Comment by knu** [comment]
Pressing Ctrl+C in the search widget copies the password of the first matching entry (only when there's no text selection) just because it is specially implemented so (#131).  It was only a fortunate case where Ctrl+C could be bound two features without confusing user.   As for Ctrl+U, I couldn't think of a similar do-what-I-mean tweak.

**Comment by GUiHKX** [comment]
>Are you using XFCE on ArchLinux?
Yup.

>Ctrl+U seems to be a standard key sequence on Linux
Thanks for the useful link, I didn't know those "standard Linux shortcuts". I wonder why they don't have this on GTK+ (thankfully lol).

Anyway... if there's no way to "workaround" this, please feel free to close this issue.

Thanks for your help!

**Comment by ccoenen** [comment]
On Windows the search is not a live-filter. You have to hit enter after search, and this focuses the list automatically, so Ctrl+U would not work there, either.

**Comment by ccoenen** [comment]
Whoops sorry for the necromancing, I didn't realize this was from may 2017.

**Comment by droidmonkey** [comment]
We are disabling all "entry" shortcuts like copying passwords and usernames and urls unless the actual entry has focus. Unexpected behavior is a keyboard shortcut doing something completely different than the expected behavior of the currently focused widget.
