### ISSUE TITLE
Enhance update button

### ISSUE THREAD

**Issue by Staubgeborener** [keepassxreboot/keepassxc#5932]
Any chance, that we can get an "update button" in keepassxc GUI (i am using the windows 64 bit version) for auto-updating, so we don't have to download the whole executable everytime?

**Comment by Staubgeborener** [comment]
> 
> 
> Any chance, that we can get an "update button" in keepassxc GUI (i am using the windows 64 bit version) for auto-updating, so we don't have to download the whole executable everytime?

**Comment by droidmonkey** [comment]
I'd consider it but we will never go to "diff patches" or inline installs. You will still have to download the whole package and go through the installer and UAC prompts.

**Comment by Staubgeborener** [comment]
> 
> 
> I'd consider it but we will never go to "diff patches" or inline installs. You will still have to download the whole package and go through the installer and UAC prompts. The only difference would be not having your browser download the package and clicking the open button.

I also have to replace my shortcut in the taskbar. Sad to hear, but ok.
