### ISSUE TITLE
Release 2.6.3 cli, gui, and guibrowser tests fail on KDE Neon 5.20

### ISSUE THREAD

**Issue by mara004** [keepassxreboot/keepassxc#5938]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
I built KeePassXC from the sources and ran `make test` afterwards. The cli, gui and guibrowser test failed.
The full log is attached: [testlog.txt](https://github.com/keepassxreboot/keepassxc/files/5819901/testlog.txt)

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. run `cmake` with the following configuration:
```
-DWITH_XC_AUTOTYPE=ON
-DWITH_XC_YUBIKEY=OFF
-DWITH_XC_BROWSER=ON
-DWITH_XC_NETWORKING=ON
-DWITH_XC_SSHAGENT=OFF
-DWITH_XC_TOUCHID=OFF
-DWITH_XC_KEESHARE=OFF
-DWITH_XC_KEESHARE_SECURE=OFF
-DWITH_XC_ALL=OFF
-DWITH_XC_UPDATECHECK=ON
-DWITH_TESTS=ON
-DWITH_GUI_TESTS=ON
-DWITH_DEV_BUILD=OFF
-DWITH_ASAN=ON
-DWITH_COVERAGE=OFF
-DWITH_APP_BUNDLE=OFF
-DKEEPASSXC_BUILD_TYPE=Release
-DKEEPASSXC_DIST_TYPE=Other
-DOVERRIDE_VERSION=2.6.3
-DGIT_HEAD_OVERRIDE=beae186
```
2. `make`
3. `LANGUAGE=en_GB CTEST_OUTPUT_ON_FAILURE=ON make test`

## Expected Behavior
No tests should fail

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
cli, gui, and guibrowser tests fail

## Context
[NOTE]: # ( Give us any additional information you may have. )
Qt Version 5.15.12

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.6.3
Revision: beae186

[NOTE]: # ( Pick choices based on your environment )
Distribution: KDE Neon User Edition 5.20 (based on Ubuntu 20.04)
Operating System: Linux
Desktop Env: KDE
Windowing System: X11

**Comment by droidmonkey** [comment]
Sometimes they fail for random reasons. Run them again.

**Comment by mara004** [comment]
Okay, but I've already run the tests at least 3 times before I reported this, and it is always the same ones which fail.
From the application's behaviour, everything appears to function correctly, though.

**Comment by droidmonkey** [comment]
The same test names or the same exact failure locations? You also have asan turned on which can complicate tests.

**Comment by mara004** [comment]
I meant the same test names, but I can run them again and make a diff to check whether it is also the same failure locations...
You're probably right that it is because of asan. When I shutdown keepassxc, kwin freezes for about a second and in the command-line, asan reports about leaks.

**Comment by mara004** [comment]
I did the diff. As far as I can see, it is the same failiure locations.

**Comment by droidmonkey** [comment]
Those leaks, except for 1, originate outside of keepassxc. I am not concerned about the test failures, they are due to spurious behavior in the testing framework, not due to failures in code.
