### ISSUE TITLE
About window blocks database lock

### ISSUE THREAD

**Issue by AgentOfDestiny** [keepassxreboot/keepassxc#5941]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Open KeePassXC 2.6.3 App (on MacBook pro running Catalina, as per specs bleow)
2. Go to menu bar top screen and click in 'drop down' the 'about KeePassXC' entry
3. Leave the 'about KeePassXC' pop up open and hit COMMAND-CTRL-Q to logout of MacBook
4. Log back in to MacBook
5. Go to KeePassXC window / icon in dock
6. KeePassXC is still open

## Expected Behavior
[NOTE]: # I expected KeePassXC to have locked all open database windows and prompt me to log back into database of my choice, as always happens when I log out with COMMAND-CTRL-Q if the popup is not open.

## Actual Behavior
[NOTE]: # KeePassXC didn't close the database window, all my database entries are visible and accessible upon re-login of the Mac OS

## Context
[NOTE]: # ( Give us any additional information you may have. )

I love your KeePassXC, been using it for a few years now without fail, every day. Thank you so much for such a GOOD application, which you can verify the files yourself and run standalone, unlike 1Password, which I do not trust my data to.
Thanks Everyone!!!
P.S. I think it is IDEAL for serious Crypto investors / people with 'stand alone' crypto dedicated laptops/computers, as it is a case of my keys... my crypto, my keys .... my passwords

[NOTE]: # ( Paste debug info from Help → KeePassXC - Version 2.6.3
Revision: beae186

Qt 5.15.1
Debugging mode is disabled.

Operating system: macOS 10.15
CPU architecture: x86_64
Kernel: darwin 19.6.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
- libgcrypt 1.8.6
 )
KeePassXC - VERSION 2.6.3
Revision: REVISION beae186

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS Catalina 10.15.7, 
CPU architecture: x86_64
Kernel: darwin 19.6.0
Desktop Env: Gnome/KDE/XFCE/Mate/Cinnamon => ?
Windowing System: X11/Wayland => ?

**Comment by 3Goldjungen** [comment]
@droidmonkey FYI
The same happens when the TOTP dialog is open. 
Should I open a new bug?
