### ISSUE TITLE
Open URL is broken in Debian stable KDE using appimage

### ISSUE THREAD

**Issue by cvandesande** [keepassxreboot/keepassxc#5942]
## Overview
Doubleclicking or ctrl-shift-u

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1.  Upgrade to 2.6.3 (Using AppImage)
2. Select an entry with a URL, ctrl-shift-u
3. Error in console
```
$ ./KeePassXC-2.6.3-x86_64_b7a0197cd7c67759f33127ad6ca89b3d.AppImage 
QObject::startTimer: Timers cannot have negative intervals
kde-open5: relocation error: /lib/x86_64-linux-gnu/libKF5KIOCore.so.5: symbol _ZN10QSslSocket21encryptedBytesWrittenEx version Qt_5 not defined in file libQt5Network.so.5 with link time reference

```

## Expected Behavior
Link opens in default browser

## Actual Behavior
Error in the console

## Context
Works in 2.6.2

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: Debian 10.7
Desktop Env: KDE
Windowing System: X11

**Comment by droidmonkey** [comment]
You have invalid qt5 libraries

**Comment by wonkyweirdy** [comment]
For the record, I see what looks like the same issue in Ubuntu 20.04.2 LTS under KDE except this is the error:

    kde-open5: symbol lookup error: /lib/x86_64-linux-gnu/libKF5KIOCore.so.5: undefined symbol: _ZN10QSslSocket21encryptedBytesWrittenEx, version Qt_5

and I was using `KeePassXC-2.6.4-x86_64.AppImage`. URLs will not open.

Using `KeePassXC-2.6.2-x86_64.AppImage` works as expected.

**Comment by droidmonkey** [comment]
That is odd because kde-open5 should be coming from your system libraries and not the appimage.

**Comment by cvandesande** [comment]
I installed Debian unstable in a VM to check this. Debian is still at version 2.6.2 due to hard freeze for the Bullseye upcoming release. This problem still occurs if you try to use an AppImage above 2.6.2, but only if you're using KDE as a DE.

Since this is broken in the Debian upstream, I'm not surprised that Ubuntu and any other downstream derivatives would also be affected.

I believe the the symbol _ZN10QSslSocket21encryptedBytesWrittenEx (and probably others) is missing from the Debian package

**Comment by chk2k2** [comment]
AppImage sets LD_LIBRARY_PATH in `AppRun.wrapped` script.
`kde-open5` then uses the Qt libraries supplied with the AppImage package.
Commenting that line fixes opening of urls. I don't know if that causes problems on other systems or distributions. 

A workaround is to hide KDE from KeePassXC AppImage by clearing environment variables.
Then the urls are not opened with the `kde-open5` command.
`$ KDE_FULL_SESSION=""; XDG_CURRENT_DESKTOP=""; ./KeePassXC-2.6.6-x86_64.AppImage`
