### ISSUE TITLE
Expired key for keepassxc-2.6.3-src.tar.xz

### ISSUE THREAD

**Issue by bfm59** [keepassxreboot/keepassxc#5944]
## Overview
The key for keepassxc-2.6.3-src.tar.xz appears to be expired.

## Steps to Reproduce
$ gpg --verify keepassxc-2.6.3-src.tar.xz.sig
gpg: assuming signed data in 'keepassxc-2.6.3-src.tar.xz'
gpg: Signature made Tue 12 Jan 2021 01:10:22 PM EST
gpg:                using RSA key C1E4CBA3AD78D3AFD894F9E0B7A66F03B59076A8
gpg: Good signature from "KeePassXC Release <release@keepassxc.org>" [unknown]
gpg: Note: This key has expired!
Primary key fingerprint: BF5A 669F 2272 CF43 24C1  FDA8 CFB4 C216 6397 D0D2
     Subkey fingerprint: C1E4 CBA3 AD78 D3AF D894  F9E0 B7A6 6F03 B590 76A8
$ uname -a
Linux hostname 4.15.0-132-generic #136-Ubuntu SMP Tue Jan 12 14:58:42 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
$ 

Operating System:  Linux
Desktop Env: XFCE
Windowing System: X11

**Comment by droidmonkey** [comment]
update your keys

**Comment by phoerious** [comment]
Refresh your public keys.
