### ISSUE TITLE
Untranslated strings - V 2.6.3

### ISSUE THREAD

**Issue by smarquespt** [keepassxreboot/keepassxc#5946]
Some strings in View menu aren't translated despite being 100% at transifex. Maybe update ts source missing?

My language is Portuguese and Windows system:
![screen](https://user-images.githubusercontent.com/1302668/104817299-5b59c000-5818-11eb-9c48-31b559052a9b.png)

First string is missing from transifex, othre 2 do exist but probably used in other context?

**Comment by droidmonkey** [comment]
I am pushing to transifex today

**Comment by phoerious** [comment]
Reminds me that I finally need to finish the Weblate stuff.
