### ISSUE TITLE
"No agent running" with OpenSSH from MS Store

### ISSUE THREAD

**Issue by QuAzI** [keepassxreboot/keepassxc#5949]
Can't user `native` agent with KeePassXC. Only `pageant` supported?
```
> powershell
PS> Add-WindowsCapability -Online -Name OpenSSH.Server
```

![image](https://user-images.githubusercontent.com/1897605/104833046-01eca200-58a7-11eb-8239-9ec5f41f127e.png)

**Comment by phoerious** [comment]
You need to enable support for OpenSSH in the settings.

**Comment by QuAzI** [comment]
OMG, I found. Thanks.
Maybe it would be nice to show proposal to enable it if OpenSSH present and no pageant found or enable by default?
