### ISSUE TITLE
Password copy on "Edit entry"

### ISSUE THREAD

**Issue by daveqr** [keepassxreboot/keepassxc#595]
Next to the Password field on the "Edit entry" screen I would like to have a "copy" button that saves the password to the clipboard.

## Expected Behavior
I envision a square the size of the current "view" button with some kind of icon representing copy. Pressing this button copies the contents of the Password field to the clipboard.

## Context
Two use cases:

1. When generating a new password, "apply" saves it Password, but I usually need to use the password immediately. Currently, I have to click the view icon and copy it manually.
2. I save extra information in the Notes field, so I often have the edit screen open when I need the password. Again, I have to click the view icon and copy.

**Comment by TheZ3ro** [comment]
Nice suggestion, actually I think it's better adding it to the password generator instead of the Edit-entry

**Comment by daveqr** [comment]
Why not both?

**Comment by TheZ3ro** [comment]
Closing for #606
