### ISSUE TITLE
Would it be possible to do a responsive UI instead of minimum window size?

### ISSUE THREAD

**Issue by ell1e** [keepassxreboot/keepassxc#5952]
## Summary
I'm currently using a [PinePhone](https://pine64.org/PinePhone), so I need access to my passwords on there. KeePassXC mostly runs super nicely, but with one major downside: it doesn't fit on the screen due to its minimum size. Fascinatingly enough, the original Keepass with Mono actually fits - but WinForms is so buggy that it is unusable with the phosh compositor, with major bugs with basic text input etc. KeePassXC however, which otherwise runs fine, opts for a different layout that works fine on larger screens, but has a higher minimum size which is now all of a sudden a problem on a phone. One cool way to solve this without making the layout worse for desktop users would be to make it responsive.

## Examples
This is the current desktop layout:
![](https://keepassxc.org/images/screenshots/database_view.png)

I think the main issue is, especially compared to original Keepass, the amount of elements on screen at once. While having no separate "View Entry" pop up is nice when having enough screen space, with small window sizes it doesn't really fit.

I think most could be solved with two principles/adjustments:

1. if the window gets small enough, just show only one of the large panes, with "Back" buttons to navigate to the previous one. Selecting any item will then forward to the "inner" plane.
2. show overflow arrows for any menus if they don't fit, where clicking/tapping it will open the remaining buttons as a popup menu to choose from

Mockups *(note: using likely a smaller width than would be possible on the current Linux phones, I just wanted to envision how it'd scale on really tiny sizes)*:

![mockup1](https://user-images.githubusercontent.com/64124388/104849288-c242ac00-58e0-11eb-8efa-21fc42fb1352.png)
![mockup2](https://user-images.githubusercontent.com/64124388/104849290-c2db4280-58e0-11eb-8200-f91f413689d8.png)
![mockup3](https://user-images.githubusercontent.com/64124388/104849291-c373d900-58e0-11eb-8130-e664465f15c0.png)

Ideally, this layout would be automatically switched to when the window size gets small. (This is also because all the Linux phones like the Librem 5 and PinePhone have excellent docking and external screen support, so it doesn't really make much sense to permanently dumb down the UI given a larger screen could suddenly be available at any time.)

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )

**Comment by phoerious** [comment]
This isn't planned at the moment.

**Comment by droidmonkey** [comment]
This has been discussed at length in this issue board as well.
