### ISSUE TITLE
Auto-type commands created and performed in KeePass 2.47 not working in KeepassXC

### ISSUE THREAD

**Issue by GscheadaHamme** [keepassxreboot/keepassxc#5953]
## Overview
Recently i switched form Keepass 2.47 on Windows (https://keepass.info/news/n210109_2.47.html) to KeepassXC on Linux.
Surprisingly, my previously working auto-type commands ceased to work in this environment.
As far as I understood the user guide, Keepass 2.47 and KeepassXC should be fully compatible in this aspect.

## Steps to Reproduce
1. Create Folder "Uni"
2. Create valid entry "Uni-Login"
3. Create another valid entry "New" in this folder with autotype command `{USERNAME}{TAB}{REF:P@T:Uni-Login}{TAB}{ENTER}`

## Expected Behavior
New entry can be saved.
When performing auto-type, `USERNAME` declared in "NEW" and `PASSWORD` declared in "Uni-Login" are inserted.

## Actual Behavior
Entry cannot be saved and an error gets prompted that the syntax of the auto-type statement is incorrect.
Auto-type entries that worked in this https://keepass.info/news/n210109_2.47.html application cannot be executed.

## Context
KeePassXC - Version 2.6.3
Revision: beae186

[NOTE]: # ( Pick choices based on your environment )
Operating System: Arch Linux
Kernel: linux 5.10.7-arch1-1
Desktop Env: none, i3 as window manager
Windowing System: X11

**Comment by phoerious** [comment]
At first glance, I can see a syntax error in your Auto-Type sequence. You have a missing closing brace behind your second `TAB`.

**Comment by GscheadaHamme** [comment]
Well, I messed this up when reducing the original statement:
`{USERNAME}{TAB}{REF:P@T:Uni-Login}{TAB}{SPACE}{ENTER}`

**Comment by droidmonkey** [comment]
Ref is not supported, will be in 2.7.0

**Comment by stefan123t** [comment]
@droidmonkey I have been using {REF:P@I:<UUID>} in the password field of additional entries without issues ever since I migrated to KeepassXC. That way I can use the ubiqituous {PASSWORD} in the auto-type sequence.
@GscheadaHamme maybe that is a workaround for your issue if you are not wanting to upgrade to 2.7.0 yet.

**Comment by KobKobson** [comment]
> @droidmonkey I have been using {REF:P@I:} in the password field of additional entries without issues ever since I migrated to KeepassXC. That way I can use the ubiqituous {PASSWORD} in the auto-type sequence.
> @GscheadaHamme maybe that is a workaround for your issue if you are not wanting to upgrade to 2.7.0 yet.

Perfect, many thanks. Works like a charm :)
