### ISSUE TITLE
Check for Updates is not working

### ISSUE THREAD

**Issue by blackbirdsr76** [keepassxreboot/keepassxc#5954]
## Overview
Retrieving update information option is not working.

## Steps to Reproduce
Help --> Check for updates

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.3
Revision: beae186
Distribution: AppImage

Qt 5.15.2
Debugging mode is disabled.

Operating system: Kali GNU/Linux Rolling
CPU architecture: x86_64
Kernel: linux 5.9.0-kali5-amd64

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- libgcrypt 1.8.1

[NOTE]: # ( Pick choices based on your environment )
Operating System: Kali Linux (very latest update)
Desktop Env: Gnome

![Screenshot from 2021-01-18 12-20-13](https://user-images.githubusercontent.com/77615473/104902961-118fe780-5988-11eb-8380-ebc88eea9aea.png)

**Comment by phoerious** [comment]
TLS is broken in the AppImage and it's pretty much unfixable at the moment. Use a different distribution such as Snap or PPA.
