### ISSUE TITLE
Browser Integration Version 2.6.3 x86_64 and M1 Mac

### ISSUE THREAD

**Issue by chrisgrnwld** [keepassxreboot/keepassxc#5956]
I've installed this version from the KeePassXC website. It's running with Rosetta 2.
Unfortunatelly I have some issues with the browser integration under google Chrome.
I think, I did all the settings correct. It shows the KeePass Logo when I want to log in. But if I press on the icon, nothing happens. Same if I right click and want to autofill username and password.
Does anyone else have the same issue? Any ideas on how to fix this?

Cheers
Chris

**Comment by phoerious** [comment]
I can test this when my M1 MBP arrives, which will probably beginning of February.

**Comment by varjolintu** [comment]
@chrisgrnwld You still connected the extension to KeePassXC normally?

**Comment by chrisgrnwld** [comment]
@varjolintu I installed the extension for Google Chrome manually.

**Comment by chrisgrnwld** [comment]
If KeePassXC is closed, the correct sign shows up at the login field. If I click on the icon, KeePassXC opens and I can tap my KeePassXC password in. The icon on the website changes. If I then klick on the icon, nothing happens...

**Comment by maxstoyanov** [comment]
I thought that I had the same issue with the Brave browser but after trying to connect by brute force clicking around it suddenly worked. I changed no settings in particular.

I'll report if the connection between the browser and KeePassXC stays flaky.

**Comment by maxstoyanov** [comment]
It worked and after updating KeePassXC it broke again. Tried to delete the connection, restart the browser, KeePassXC, reinstall everything... I can't get it back to work.

Even tried it with Firefox Developer Edition.

**Comment by phoerious** [comment]
Please see pinned issue. #6054
