### ISSUE TITLE
Misleading Keepass window focus

### ISSUE THREAD

**Issue by andreib1** [keepassxreboot/keepassxc#5957]
When launched from browser, keepass database unlock appears to have focus, and shows a cursor, however any attempt to type the master password actually types into the username field of the website in question, thereby divulging the password to the website.

**Repro**
1. Setup Keepass browser extension for Firefox.
3. Link Database.
4. Set Keepass browser extension setting: Automatically reconnect to KeePassXC. (Reconnects automatically to KeePassXC when it is detected.)
5. Close Keepass.
6. Navigate to site which requires Auth.
7. Keepass login is displayed with cursor appearing to indicate window focus.
8. Type database master password

**Expected**
Keepass has focus, password is entered in Keepass

**Actual**
Keepass box is empty
Password has been entered into current browser page

**Keepass Env**
KeePassXC - Version 2.6.3
Revision: beae186

Qt 5.15.2
Debugging mode is disabled.

Operating system: Windows 10 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.19042

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
- libgcrypt 1.8.7

** Keepass Browser Extension Env **

KeePassXC - 2.6.3
KeePassXC-Browser - 1.7.4
Operating system: Win32
Browser: Mozilla Firefox 84.0

**Comment by droidmonkey** [comment]
This was fixed in 2.6.3

**Comment by droidmonkey** [comment]
#5390

**Comment by droidmonkey** [comment]
BTW, I closed this because there is absolutely nothing else we are going to do to attempt to make this better. This is just an unfortunate "feature" of Windows.

**Comment by andreib1** [comment]
I get that, it's perfectly understandable, Windows is a pain when it comes to window focus and behavior.  It's probably worth warning about this when turning particular this feature on.
