### ISSUE TITLE
Option to remember searches?

### ISSUE THREAD

**Issue by mxmilkiib** [keepassxreboot/keepassxc#5960]
I'd like to be able to search for something, then reopen the window later on and still have the same search result present.

**Comment by droidmonkey** [comment]
Search auto clears after a set amount of time (5 min). This is a convenience and (slight) security feature. Might I recommend if you need a search available for so long just put those entries in their own group.

**Comment by mxmilkiib** [comment]
I use groups for most keys, but not all of the groups I'm aiming for are also always above the fold in the group sidebar.

Ultimately I'm looking to avoid using the mouse, so having a group in the sidebar would require selecting it via keyboard, and, if that is or could be possible, I guess that would still repeatedly require roughly about the same number of keypresses as going through the process of a search.

**Comment by droidmonkey** [comment]
![image](https://user-images.githubusercontent.com/2809491/106365688-1730ea00-6305-11eb-90fb-0dcd7a2ac3cf.png)
