### ISSUE TITLE
Icons of folders/keys super large

### ISSUE THREAD

**Issue by yangsheng6810** [keepassxreboot/keepassxc#5961]
## Overview
Icons of folders/keys super large, as if scaled 3x-4x.

## Steps to Reproduce
1. Open up a database.

## Expected Behavior
Icons of folders/keys about the same size of text, so many are visible without scrolling.

## Actual Behavior
![image](https://user-images.githubusercontent.com/2863729/104963698-b74f5080-59a0-11eb-98c7-d156087afb9f.png)

## Context
Monitor: 27 inch 2560x1440
.Xresources:
```
Xft.dpi: 96
```

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.6.3
Revision: 2.6.3-1 (from Arch official repository)

Operating System: Arch Linux
Desktop Env: i3
Windowing System: X11

**Comment by droidmonkey** [comment]
Duplicate, qt bug, use QT_SCALE_FACTOR=1.01

**Comment by yangsheng6810** [comment]
Thanks for the quick response. Could you provide a link of the upstream bug so I can keep an eye on?

**Comment by droidmonkey** [comment]
There isn't an upstream bug filed that I'm aware of (they generally don't care about fixing these) but it's not on us considering the scale factor impact.

**Comment by yangsheng6810** [comment]
Totally understood. Anyway, thanks for all your works. Have been enjoying KeePassXC since getting introduced to it.
