### ISSUE TITLE
Problem with verifying signatures using the GPG keyserver. Website's one works fine.

### ISSUE THREAD

**Issue by DesignatedJM02** [keepassxreboot/keepassxc#5963]
So I am setting up my laptop after resetting it and I am going through the process of reinstalling my apps. I went through the process of verifying KeePassXC and I ran into a problem.

Problematic version (using the GPG server, not the website):
```
PS C:\Users\XX\Downloads> gpg --keyserver keys.openpgp.org --recv-keys CFB4C2166397D0D2
gpg: key CFB4C2166397D0D2: public key "KeePassXC Release <release@keepassxc.org>" imported
gpg: Total number processed: 1
gpg:               imported: 1
PS C:\Users\XX\Downloads> gpg --verify KeePassXC-*.sig
gpg: assuming signed data in 'KeePassXC-2.6.3-Win64.msi'
gpg: Signature made 1/13/2021 9:56:10 AM Pacific Standard Time
gpg:                using RSA key C1E4CBA3AD78D3AFD894F9E0B7A66F03B59076A8
gpg: BAD signature from "KeePassXC Release <release@keepassxc.org>" [unknown]
```
However, when I used the option for the website, `gpg --fetch-keys https://keepassxc.org/keepassxc_master_signing_key.asc`, it worked as it should.
```
PS C:\Users\XX\Downloads> gpg --fetch-keys https://keepassxc.org/keepassxc_master_signing_key.asc
gpg: requesting key from 'https://keepassxc.org/keepassxc_master_signing_key.asc'
gpg: key CFB4C2166397D0D2: "KeePassXC Release <release@keepassxc.org>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
PS C:\Users\XX\Downloads> gpg --verify KeePassXC-*.sig
gpg: assuming signed data in 'KeePassXC-2.6.3-Win64.msi'
gpg: Signature made 1/13/2021 9:56:10 AM Pacific Standard Time
gpg:                using RSA key C1E4CBA3AD78D3AFD894F9E0B7A66F03B59076A8
gpg: Good signature from "KeePassXC Release <release@keepassxc.org>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: BF5A 669F 2272 CF43 24C1  FDA8 CFB4 C216 6397 D0D2
     Subkey fingerprint: C1E4 CBA3 AD78 D3AF D894  F9E0 B7A6 6F03 B590 76A8
```

**Comment by phoerious** [comment]
What does `gpg --list-keys CFB4C2166397D0D2` show with the key imported from keys.opengpg.org?

**Comment by KIMWW** [comment]
I have a similar problem with Linux Mint in the sense that when I run:
`$ gpg --fetch-keys https://keepassxc.org/keepassxc_master_signing_key.asc'
I get:
'gpgkeys: protocol `https' not supported
gpg: no handler for keyserver scheme `https'
gpg: WARNING: unable to fetch URI https://keepassxc.org/keepassxc_master_signing_key.asc: keyserver error`
and when I run:
$ gpg --keyserver keys.openpgp.org --recv-keys CFB4C2166397D0D2'
I get:
'gpg: requesting key 6397D0D2 from hkp server keys.openpgp.org
gpgkeys: key CFB4C2166397D0D2 can't be retrieved
gpg: no valid OpenPGP data found.
gpg: Total number processed: 0
gpg: keyserver communications error: keyserver helper general error
gpg: keyserver communications error: unknown pubkey algorithm
gpg: keyserver receive failed: unknown pubkey algorithm'

`gpg --list-keys CFB4C2166397D0D2'
return:
'gpg: error reading key: public key not found`

**Comment by phoerious** [comment]
Okay, pretty sure you are using an ancient OpenPGP version. Use the Ubuntu-Keyserver then. keyserver.ubuntu.com.

**Comment by DesignatedJM02** [comment]
If that is the case, then you need to update this guide 
https://keepassxc.org/verifying-signatures/ @phoerious 
Because that is where I got the commands from.

**Comment by DesignatedJM02** [comment]
And to answer your question, I get
```
PS C:\Users\XX> gpg --list-keys CFB4C2166397D0D2
pub   rsa4096 2017-01-03 [SC]
      BF5A669F2272CF4324C1FDA8CFB4C2166397D0D2
uid           [ unknown] KeePassXC Release <release@keepassxc.org>
sub   rsa2048 2017-01-03 [S] [expires: 2024-12-04]
sub   rsa2048 2017-01-03 [S] [expires: 2024-12-04]
```

**Comment by phoerious** [comment]
Any somewhat modern GPG version can handle it. Mint is notorious for it's outdated packages.

**Comment by DesignatedJM02** [comment]
I am using Windows for this machine. So I am using Powershell and GPG4Win

**Comment by KIMWW** [comment]
> Use the Ubuntu-Keyserver then. keyserver.ubuntu.com.

It worked this time, but the key is not certified with a trusted signature!

```
gpg: assuming signed data in `KeePassXC-2.6.3-x86_64.AppImage'
gpg: Signature made Tue 12 Jan 2021 18:09:52 GMT using RSA key ID B59076A8
gpg: Good signature from "KeePassXC Release <release@keepassxc.org>"
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: BF5A 669F 2272 CF43 24C1  FDA8 CFB4 C216 6397 D0D2
     Subkey fingerprint: C1E4 CBA3 AD78 D3AF D894  F9E0 B7A6 6F03 B590 76A8
```

**Comment by phoerious** [comment]
Please read the verification guide thoroughly.

**Comment by KIMWW** [comment]
Okay, SO, I read again that long explanation guide and now I understand that **the WARNING:**
**This key is not certified with a trusted signature!**
**!!! SHOULD BE IGNORED !!!**
!!! If the PRIMARY FINGERPRINT is correct !!!

Thanks for your kind help.
