### ISSUE TITLE
global Auto-type don't match with url search in my browser

### ISSUE THREAD

**Issue by webafrancois** [keepassxreboot/keepassxc#5964]
## Overview
I choose in Settings / General /auto-type to search on the URL for the global Auto-type, and not the title. 
When I try to auto-type, my browser say that he can't find the title.

![Sélection_548](https://user-images.githubusercontent.com/19719849/105030094-90058b80-5a53-11eb-86f8-374cf31c90ae.png)

![Sélection_549](https://user-images.githubusercontent.com/19719849/105030135-a6abe280-5a53-11eb-916e-7cd49a6e8b43.png)

![Sélection_550](https://user-images.githubusercontent.com/19719849/105030150-aad80000-5a53-11eb-9925-c35f6fd7053f.png)

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Select only the URL in settings / General / Auto-type
2. Choose a shortcut to Auto-type
3. Restart KeePassXC
4. Open Database
5. Open you browser on a URL saved in the Database
6. Type your shortcut.

## Context
It works, when I choose the Title, and my title in database is exactly the same on the website

[NOTE]: # ( Paste debug info from Help → About here )

## Infos
KeePassXC - Version 2.6.3
Revision: beae186

Qt 5.12.8
Debugging mode is disabled.

Operating system: Linux Mint 20.1
CPU architecture: x86_64
Kernel: linux 5.4.0-60-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- libgcrypt 1.8.5
- 

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: Mate
Windowing System: X11

**Comment by droidmonkey** [comment]
That's cause there is no url in that window title.

**Comment by webafrancois** [comment]
You say that the website should have his URL in the meta title HTML ?
I don't understand.
If I put the URL
![Sélection_552](https://user-images.githubusercontent.com/19719849/105032552-330bd480-5a57-11eb-82e4-ddc0d974938a.png)

![Sélection_551](https://user-images.githubusercontent.com/19719849/105032559-369f5b80-5a57-11eb-8d2d-214babffe4af.png)

 in the Title field, it doesn't work anymore.

It would be great if KeepassXC can find the url in my database...

Where can I see an example of auto-type, with URL working ?

I have to show KeepassXC to several employees and this feature seems really interesting to me.

**Comment by droidmonkey** [comment]
No the Firefox window title needs to contain the url for us to match against.

**Comment by webafrancois** [comment]
OK, I read this : https://www.reddit.com/r/KeePass/comments/bclhvg/keepassxc_is_it_possible_for_global_autotype_to/
So, I understand : 
- Auto-type only works with the exact title of the website, which is not easy to find, only type Ctrl + I and copy the Title field. But not so useful
- Auto-type works with websites that saved their URL in their title meta tag.
- Auto-type can't detect the URL in Firefox without extension keepassxc-browser.

![Sélection_553](https://user-images.githubusercontent.com/19719849/105035275-02c63500-5a5b-11eb-8180-56f0d7ea7476.png)

I don't know of any website that has their URL in the title tag of their page...

Thank you for the explanations.

And thank you very much for this project. It save my life of adminsys junior.

**Comment by droidmonkey** [comment]
We recommend our browser extension for all those reasons stated above.
