### ISSUE TITLE
drag & drop on macOS KeePassXC 2.6.3 still not working reliably

### ISSUE THREAD

**Issue by MasinAD** [keepassxreboot/keepassxc#5965]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
As reported in #5636 drag & drop stops working eventually. Issue has been closed with reference to next release. Next release is installed but still no drag & drop.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. I have no clue

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Drag & drop working

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Drag & drop not working

## Context
[NOTE]: # ( Give us any additional information you may have. )
I would really like to help getting rid of this problem as it is a little bit annoying. But @droidmonkey wrote he already pinpointed the cause to some Qt library (ever considered using GTK? ;-) ), so maybe there was an error in the build or makefile or it wasn't the library's fault.

[NOTE]: # ( Paste debug info from Help → About here )
```
KeePassXC - Version 2.6.3
Revision: beae186

Qt 5.15.1
Diagnosemodus ist deaktiviert.

Betriebssystem: macOS 10.15
CPU-Architektur: x86_64
Kernel: darwin 19.6.0

Aktivierte Erweiterungen:
- Auto-Type
- Browser-Integration
- SSH-Agent
- KeeShare (bestätigtes und unbestätigtes Teilen)
- YubiKey
- TouchID

Kryptographische Bibliotheken:
- libgcrypt 1.8.6
```

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS 10.15

**Comment by MasinAD** [comment]
Okay, I just read https://github.com/keepassxreboot/keepassxc/issues/5636#issuecomment-743767207 once again and compared the Qt version mentioned there with the one in 2.6.3 and it's not the version with the fix.

**Comment by MasinAD** [comment]
@droidmonkey Can you say anything about when the fix will land?

**Comment by droidmonkey** [comment]
Most likely when we release 2.6.4
