### ISSUE TITLE
MSI package not installing

### ISSUE THREAD

**Issue by Tampa** [keepassxreboot/keepassxc#5966]
## Overview
msi package does not run properly anymore

## Steps to Reproduce
1. Download 64bit msi
2. Attempt install
3. Observe msiexec.exe stuck, no installation window opening

## Expected Behavior
Installation window popping up

## Actual Behavior
Nothing happens, no install window, nothing. Have to kill the process if I want to install other msi packages.

## Context
Was using 2.6.1 prior and got the info to upgrade. As I use the installed version grabbed the latest installer from github and attempted to install over the existing installation, but nothing seems to happen. It did, unusually, ask me if I wanted to run the msi, normally that only happens if they are not properly signed, but that's also normally not a reason for it to get stuck like this.

Operating System: Windows7 64bit

**Comment by droidmonkey** [comment]
Re-download they are no problems with the msi

**Comment by Tampa** [comment]
Product: KeePassXC -- The installer has encountered an unexpected error installing this package. This may indicate a problem with this package. The error code is 2889. The arguments are: FatalError, Description,

**Comment by droidmonkey** [comment]
Just realized you are using Windows 7, that operating system is no longer supported. Use the zip package.
