### ISSUE TITLE
Password Generator label stops at 99 characters even though the password is longer than that

### ISSUE THREAD

**Issue by DodyAlkarkhi** [keepassxreboot/keepassxc#5967]
## Overview
When generating a new password the length label stops at 99 characters although the password gets to 128 characters. A minor issue, but starts to get annoying. This is in Windows 10.

## Steps to Reproduce
1.  Go to password generator
2. Take the length of more than 99 characters

## Expected Behavior
Label says how many characters there are.

## Actual Behavior
Label stops at 99 characters

## Context
First time I used it in Windows. Have used it in Linux and this issue doesn't exist there as far as I know.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.3
Revision: beae186

Qt 5.15.2
Debugging mode is disabled.

Operating system: Windows 10 Version 2009
CPU architecture: x86_64
Kernel: WinNT 10.0.19042

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
- libgcrypt 1.8.7

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows
Desktop Env: N/A
Windowing System: N/A

This is the first time I have reported a bug. Let me know if you need more info.

**Comment by droidmonkey** [comment]
Fixed already for 2.6.4

**Comment by DodyAlkarkhi** [comment]
@droidmonkey  When did it release? I literally installed it today

**Comment by droidmonkey** [comment]
We haven't released that version yet

**Comment by DodyAlkarkhi** [comment]
Ah okay. Nevermind then. Glad to see it fixed.
