### ISSUE TITLE
Wrong date format in the localized UIs

### ISSUE THREAD

**Issue by AO-LocLab** [keepassxreboot/keepassxc#5968]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

The date format currently used in the localized UIs is YYYY/MM/DD, which will be confusing for international users who are used to a different date format. e.g., for French we’d expect DD/MM/YYYY. Some users could very well confuse the month for the day.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
The date format should change according to the user locale.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: Unity
Windowing System: X11

**Comment by droidmonkey** [comment]
Please provide a screenshot of where you see this.

**Comment by AO-LocLab** [comment]
Sorry @droidmonkey, I missed the request for a screenshot, now included.

**Comment by droidmonkey** [comment]
This is set by your locale, we don't prescribe or set any format.

**Comment by markp999** [comment]
fwiw, after a bit of digging I found the af_ZA locale's default date/time format is YYYY-MM-DD HH:mm ([mix of locale/datetime formats](https://docs-previous.pega.com/sites/default/files/help_v73/tools/locale/datetimeformats-ref.htm))

I'm running keepassxc (v2.6.6) under Ubuntu so I configured a custom *.desktop to use a custom LC_TIME:

```
sudo apt-get install language-pack-af              # installs the af_ZA locale

$ cat ~/.local/share/applications/keepassxc_dt.desktop
[Desktop Entry]
Name=KeepassXC(dt)
Exec=env LC_TIME=af_ZA keepassxc
Icon=keepassxc
comment=app
Type=Application
Terminal=false
Encoding=UTF-8

```

I then went into Activities, searched on 'keep', right-clicked on the 'KeepassXC(dt)' entry and added it to my desktop/favorites

--------------------

While this gets me a usable date/time format I'd stil want to see the ability to set the format within the app (eg, `%Y-%m-%d %H:%M`)
