### ISSUE TITLE
Allow easy copying from the browser plugin for websites with dynamic password fields and other problems

### ISSUE THREAD

**Issue by tunbridgep** [keepassxreboot/keepassxc#5975]
## Summary
There are a lot of websites where the KeepassXC Browser Plugin has a lot of trouble detecting certain fields if those websites have weird dynamically loading fields. Usually this happens when a website asks for your username, then once you type it, it slides in or creates a password field. I find KeepassXC often has trouble detecting these, even when manually specifying fields.

The best solution I can think of to remedy this (and any other possible cases of non-detection of fields) is to add a "Copy Username" and "Copy Password" button to the drop-down options menu of the browser plugin.

These would use KeepassXC's built-in copy systems (meaning the clipboard will be cleared etc after a certain time limit, and other security measures as well).

These would serve as an easy "just in case" method for websites that don't want to work.

## Examples
The bitbucket website (atlassian.com) has this problem. As do a lot of others.

Here is a really terribly mock up of what this might look like:
![Context Menu with Buttons Added](https://i.imgur.com/1Z8EGxn.png)

## Context
This functionality can already technically be gained by going to the main keepassxc program, finding the entry, and either using auto-type or copying the username/password manually. However, this is tedious, and involves leaving the browser to use the application, then switching back to the browser. Overall it's a painful annoying process. Having the browser plugin make this easier would be a godsend, as website logins are one of the "sore points" for a lot of KeepassXC (and Keepass) users, as they have always had some issues.

**Comment by droidmonkey** [comment]
I disagree with this entirely. The clipboard is absolutely insecure and a worst practice for us. The best solution is to fix the anomalies as best we can, otherwise use Auto-Type.

**Comment by tunbridgep** [comment]
I understand it's insecure. It's designed as a last resort. We are going to have to either use the clipboard or auto-type anyway in this case, so it's insecure regardless.

If the clipboard is too dangerous, make it an auto-type button instead.

The entire point of this suggestion is to reduce busywork in extreme cases where the good solutions do not work. We are still going to need to use insecure methods anyway, this simply makes that less frustrating.

**Comment by droidmonkey** [comment]
When you present an insecure option up front it becomes the default option.shortcut Autotype is accessed with a global keyboard shortcut and is far more secure than clipboard. A button to activate Auto-Type for the current page url is a good idea and I would definitely endorse that.

**Comment by tunbridgep** [comment]
Okay then. Consider this suggestion officially changed from "copy and paste buttons" to "Auto-Type button"

**Comment by droidmonkey** [comment]
I'll make a new issue over on our browser extension repository
