### ISSUE TITLE
Drag and Drop not working on Mac 2.6.3

### ISSUE THREAD

**Issue by dareno** [keepassxreboot/keepassxc#5976]
## Overview
Like issue #5636 but continues on Mac 2.6.3 clean install.

## Steps to Reproduce
1. clean install of KeePassXC 2.6.3 (no prior version ever installed)
2. created a few entries and groups
3. cannot drag any entry (visual drag never begins)

## Expected Behavior
entry should drag and be droppable on another group

## Actual Behavior
holding left mouse button has no effect

## Context
I'm running 2.6.3 on two macbook pros, on one, I clean installed big sur 11.1 and installed 2.6.3. This one has the issue. On another, I've upgraded the OS and KeepassXC over the years and it's working fine on Catalina 10.15.7.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.3
Revision: beae186

Qt 5.15.1
Debugging mode is disabled.

Operating system: macOS 11.1
CPU architecture: x86_64
Kernel: darwin 20.2.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
- libgcrypt 1.8.6

**Comment by dareno** [comment]
@droidmonkey, looks like you closed this as a dup of the original; that one is still closed, will you be re-opening it?

**Comment by droidmonkey** [comment]
Look at the pinned issues

**Comment by dareno** [comment]
I see #5636 is pinned and closed and that you updated it to not be 2.6.2 specific but left it closed. Not meaning to be bothersome, just wondering if you are accepting that the issue is not resolved and if you'll be re-opening #5636.

Thanks for your time on the project.

**Comment by droidmonkey** [comment]
It's not our bug. It's a qt bug. The only fix will come from qt. They broke it and they have fixed it.
