### ISSUE TITLE
Take full url into account when updating credentials 

### ISSUE THREAD

**Issue by SealinRepo** [keepassxreboot/keepassxc#5977]
eg: I saved user info via http://localhost:8011, username: abc, password: 123456, and go to http://localhost:8022, keepassXC will auto type [abc] user info, if I type password to 222222 and save it, old password(123456) will overwrite.

**suggest: the 8022 port website do not tips or use password where saved by 8011 (these two are different websites, although the domain name is the same...)**

KeePassXC - 2.6.2
Operating System: macOS

Thanks.

**Comment by droidmonkey** [comment]
@varjolintu interesting edge case here

**Comment by droidmonkey** [comment]
@varjolintu is this still a problem?

**Comment by varjolintu** [comment]
@droidmonkey Gotta check it. I would also like to introduce an option for exact URL match. Some users really want it.

**Comment by trzustka** [comment]
@droidmonkey it seem it is ok now

KeePassXC - 2.7.0
Operating System: Windows 10
