### ISSUE TITLE
Password generator stops at 99 characters

### ISSUE THREAD

**Issue by CentauriII** [keepassxreboot/keepassxc#5978]
## Overview
When I try to create a 128 character long password it will only create a 99 character length one. I can still drag it beyond 99 characters but the number stays at 99. When I continue dragging the bar the Entropy hops back so if it says 744.82 bit then it will hop back down to maybe 702.53 bit and rise again until I reach the end. So the Entropy reacts as if I'm trying to reach 99. Updated recently and before the update I could create passwords up to 128 characters. 

## Steps to Reproduce
1. Generate a new password.
2. Click ON on every character type.
3. Pull the "length"  meter to max and it stops at 99 but I can still pull further and it "resets" itself as if its back on 99 characters.

## Expected Behavior
Go all the way up to 128 characters.

## Actual Behavior
Stops at 99 characters then "resets" itself as if its back on 99 characters.

## Context
[NOTE]: # This started happening as soon as I entered the new, updated version, of KeePassXC
![Screenshot from the password generator](https://user-images.githubusercontent.com/72753530/105339883-15fd1000-5bd5-11eb-8965-63e028c0d3a5.PNG)

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.6.3
Revision: beae186

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 10 OS Build 19041.746

**Comment by droidmonkey** [comment]
Yah there was a and bug we fixed it will be in 2.6.4 shortly.
