### ISSUE TITLE
KeeepassXC does not auto-open last used database.

### ISSUE THREAD

**Issue by msrv** [keepassxreboot/keepassxc#598]
## Expected Behavior
(KeepassXC does not autostart on Windows 10, thus i created a sheduled task to do this.)
On start, KeepassXC should attempt to mount the previously used database. The option to to this is checked in preferences.

## Current Behavior
KeepassXC starts with the default window. I have to manually select "open previously used database...", even if i check the option in preferences accordingly.

KeepassXC 2.1.4
Windows 10

**Comment by TheZ3ro** [comment]
We need more information, Thanks

**Comment by msrv** [comment]
Okay, i'll be glad to help. What exactly do you need? There is no error message, it just starts with the default screen and does not prompt for the last used database.

**Comment by TheZ3ro** [comment]
Have you downloaded it from the website?
This happen every time?
Copy here the content of `C:\Users\<youruser>\AppData\Local\keepassxc\keepassxc.ini` file

**Comment by msrv** [comment]
I've downloaded it from the website and it happens every time. 

Here the content of keepassxc.ini (removed personal & keyfile data):
`[General]
ShowToolbar=true
LastDir=C:/Users/ MYUSER /Documents
LastDatabases=C:/Users/ MYUSER /Cloud/Keepass/Keepass.kdbx
LastKeyFiles= Keyfile (here are cryptic things with / etc...)
RememberLastDatabases=true
RememberLastKeyFiles=true
OpenPreviousDatabasesOnStartup=true
AutoSaveAfterEveryChange=false
AutoSaveOnExit=true
AutoReloadOnChange=true
MinimizeOnCopy=false
UseGroupIconOnEntryCreation=false
AutoTypeEntryTitleMatch=true
GlobalAutoTypeKey=0
GlobalAutoTypeModifiers=0
LastOpenedDatabases=@Invalid()

[GUI]
Language=system
ShowTrayIcon=true
MinimizeToTray=true
MinimizeOnClose=true
MinimizeOnStartup=true
MainWindowGeometry=@ByteArray(\x1\xd9\xd0\xcb\0\x2\0\0\0\0\x1\x87\0\0\0W\0\0\x4\xb8\0\0\x2\xdd\0\0\x1\x90\0\0\0}\0\0\x4\xaf\0\0\x2\xd4\0\0\0\0\0\0\0\0\x6@)
SplitterState=@Invalid()
EntryListColumnSizes=@Invalid()
EntrySearchColumnSizes=@Invalid()

[security]
clearclipboard=true
clearclipboardtimeout=30
lockdatabaseidle=false
lockdatabaseidlesec=10
lockdatabaseminimize=false
passwordscleartext=false
passwordsrepeat=false
autotypeask=true

[Http]
Enabled=true
ShowNotification=true
BestMatchOnly=false
UnlockDatabase=true
MatchUrlScheme=true
SortByUsername=false
Port=19455
AlwaysAllowAccess=false
AlwaysAllowUpdate=false
SearchInAllDatabases=false
SupportKphFields=true
`

**Comment by TheZ3ro** [comment]
Ok, the last opened database is not saved in the config file: `LastOpenedDatabases=@Invalid()`

Seems related to #580 and #430, ping @phoerious

**Comment by louib** [comment]
I'm assuming this was fixed by https://github.com/keepassxreboot/keepassxc/pull/580. @msrv can you confirm?

**Comment by nbro** [comment]
I'm also observing this problem on a MacOS Sonoma with KeePassXC 2.7.9 installed with brew. I've previously installed KeePassXC on the same OS and with brew and I didn't get this problem. So it's weird that it's now happening. I don't remember if the KeePassXC version was the same though
