### ISSUE TITLE
Ignores macOS per-user editing key bindings.

### ISSUE THREAD

**Issue by garretwilson** [keepassxreboot/keepassxc#5980]
## Overview
macOS has a standard way for a user to remap editing keys across applications using `~/Library/KeyBindings/DefaultKeyBinding.Dict`. For example way one can map `Ctrl+Left` and `Ctrl+Right` for moving the cursor to word boundaries using the same keys used on Windows/Linux, as shown in [How to Change macOS Key Bindings](https://blog.victormendonca.com/2020/04/27/how-to-change-macos-key-bindings/) . See [Customizing the Cocoa Text System](https://www.hcs.harvard.edu/~jrus/site/cocoa-text.html) for a more in-depth explanation.

Unfortunately KeyPassXC completely ignores these settings, so that when I am entering text in a field, for example, the editing keys work completely differently than they do in other applications.

## Steps to Reproduce
1. Set up key bindings such as [How to Change macOS Key Bindings](https://blog.victormendonca.com/2020/04/27/how-to-change-macos-key-bindings/) and restart KeyPassXC. (Note that this key binding assumes you have switched the `Ctrl` and `Cmd` keys in the OS key mappings. If you have not switched the `Ctrl` and `Cmd` keys, either edit each section to use the commented line with `^` instead of `@`, or simply use the following mapping file instead: https://gist.github.com/Jimbly/9471958 .)
2. Open a text editor and verify that `Ctrl+Left` and `Ctrl+Right` navigate a line via word boundaries.
3. Switch to KeyPassXC and use `Ctrl+Left` and `Ctrl+Right` in a line of text.

## Expected Behavior
`Ctrl+Left` and `Ctrl+Right` should move the cursor to word boundaries like other applications, based upon my `~/Library/KeyBindings/DefaultKeyBinding.Dict` file.

## Actual Behavior
KeyPassXC ignores the `~/Library/KeyBindings/DefaultKeyBinding.Dict` file and navigates the cursor via word boundaries only by the default a system `Option+Left` and `Option+Right` keys.

KeePassXC - 2.6.3
Operating System: macOS Big Sur

**Comment by droidmonkey** [comment]
You'll have to take this up with Qt.
