### ISSUE TITLE
Freezing the database instead of locking

### ISSUE THREAD

**Issue by haarp** [keepassxreboot/keepassxc#5982]
## Summary
It's possible to automatically lock the database, e.g. when the session is locked. This is an useful feature, but often overkill, as it requires re-entering of the password when the session is unlocked.

Sometimes it would suffice to freeze the database during the duration of the session lock/screensaver, to prevent rogue programs from using it while the user is away. Consider e.g. the secret service or browser integrations here, which could theoretically be abused while the user is not looking.

## Examples
Frozen state: Database remains unlocked, but access requests are either frozen or rejected.
As long as a screen locker is active, the database remains in the frozen state.

## Context
The idea is to improve security without the inconvenience of having to re-enter the password repeatedly. If your work involves leaving the computer repeatedly and demands a screen lock (with short timeout), then having to re-enter the db password frequently quickly becomes annoying.

Furthermore, a hypothetical (if somehwhat contrived) attack vector could be a hardware-keylogger that is attached while the computer is locked. The requirement to enter the db passphrase after unlocking the computer means an attacker will now have both the login password, and the db password.

It's not intended to provide bullet-proof security that withstands attacks on the screen locker or cold boot attacks.

Thanks!

**Comment by droidmonkey** [comment]
This is what Quick Unlock feature is all about. The security of being locked (no unencrypted data in memory) without having to type a long password or wait for KDF to work. We won't implement a frozen state since that does not improve security.
