### ISSUE TITLE
LineEdit height changed after upgrade to 2.6.3

### ISSUE THREAD

**Issue by AKorezin** [keepassxreboot/keepassxc#5984]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
After upgrading from 2.6.2 to 2.6.3 LineEdit height changed in classic theme.
Look like they have 0px padding set.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Setup cinnamon(maybe other gtk based)
1. Use materia light compact theme
1. Use kvantum for kde theme compatibility
1. Use materia light for kvantum theme
1. Upgrade from 2.6.2 to 2.6.3
1. Open details for any entry

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
In 2.6.2 LineEdit fields in
- unlock
- database creation
- settings
- entry edit
- group edit

forms look normal and have equal height with other fields like dropdown lists and buttons.
![4](https://user-images.githubusercontent.com/5399964/105524043-2f46af00-5cf0-11eb-8e0e-95d74325f544.png)

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
1. In 2.6.3 all LineEdit fields have minimum available heights to fit symbols.

![3](https://user-images.githubusercontent.com/5399964/105524097-3c639e00-5cf0-11eb-817f-03b6dfea22a1.png)

## Context
[NOTE]: # ( Give us any additional information you may have. )
My setup:
- archlinux
- cinnamon
- [materia gtk theme](https://archlinux.org/packages/community/any/materia-gtk-theme/)
- kvantum
- [materia kvantum theme](https://archlinux.org/packages/community/any/kvantum-theme-materia/)

[NOTE]: # ( Paste debug info from Help → About here )
1. KeePassXC - Version 2.6.2
  Revision: e9b9582
2. KeePassXC - Version 2.6.3
  Revision: beae186

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: Cinnamon
Windowing System: X11

**Comment by AKorezin** [comment]
@droidmonkey won't fix?

**Comment by droidmonkey** [comment]
Use our themes
