### ISSUE TITLE
Global Auto-Type Shortcut key stops working

### ISSUE THREAD

**Issue by DuncanFairley** [keepassxreboot/keepassxc#5985]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
My global auto-type shortcut key works, and then doesn't after a few hours, randomly. 

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Tools > Settings > Auto-Type
2.  Set Global Auto-Type shortcut to Ctrl+Alt+A

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
For Ctrl+Alt+A to stay in the box

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
After releasing the keys, the input box becomes blank

## Context
[NOTE]: # ( Give us any additional information you may have. )
I then entered Ctrl+Alt+S and it allowed it. It worked for a few hours, but then it stopped working. When I opened the settings back up, the box was now red:
![image](https://user-images.githubusercontent.com/1350420/105546246-fee02000-5cb1-11eb-8a4c-dae714a29f78.png)

I then clicked the red input and it would still not let me use Ctrl+Alt+A but also now not let me use Ctrl+Alt+S either. It's also happening to my coworker for the past couple weeks, and he just changes to a new shortcut each time.  He's on version 2.6.2 still. 

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.3
Revision: beae186
Qt 5.15.2
Debugging mode is disabled.
Operating system: Windows 10 Version 2004
CPU architecture: x86_64
Kernel: winnt 10.0.19041
Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
Cryptographic libraries:
- libgcrypt 1.8.7

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 10 2004

**Comment by droidmonkey** [comment]
Do you have security software installed (anti virus, etc)? Sounds like you are in an office environment.

**Comment by DuncanFairley** [comment]
Only Windows Defender. Nothing 3rd party.

**Comment by droidmonkey** [comment]
Group policy settings that restrict global hotkeys?

**Comment by VitalerHummer** [comment]
I have the exact same problem, also no security software (apart from windows defender) and no grou policies (personal device).

**Comment by droidmonkey** [comment]
For the record I cannot replicate this, however I am on Windows 10 2009.

**Comment by Mogost** [comment]
The same thing, and this issue is definitely not related to Group Policy or security settings.

**Comment by Mogost** [comment]
I noticed that a reboot helped. And I was able to set the old keyboard shortcut.
+ the problem occurred after an update ещ 2.6.3, after which I did not reboot.

**Comment by droidmonkey** [comment]
Let us know if it comes back. At this point we have not made any changes in the 2.6 baseline that would affect keyboard shortcut like this.

**Comment by DuncanFairley** [comment]
My coworker and I upgraded windows from 10.0.19041.264 to 10.0.19041.746 and the issue no longer occurs. It might very well have been the reboot that fixed it though.

**Comment by 534n0** [comment]
I've encountered this exact behavior too since the first time I installed KeePassXC. It's been more than a year. I always update Windows regularly (currently at 20H2). Reboot can fix it temporarily, but it will come back again randomly. I'm using Alt+Shift+P as the shortcut.

**Comment by Admadhav** [comment]
Same with me .seone post a fix please

**Comment by rocky7x** [comment]
I am on Windows 11 and have the same issue. Please check.

**Comment by r3times** [comment]
I've just run into this issue on Xubuntu 22.04, with Ctrl+Alt+z having worked perfectly until ten minutes ago. The same details as the OP, my previous shortcut highlighted in red, Keepassxc now letting me choose any combination of unassigned shortcuts except Ctrl+Alt+z.

Apologies if a closed issue isn't the right place for this, I can post anew if so advised.


KeePassXC - Version 2.7.4
Revision: 63b2394

Qt 5.12.8
Debugging mode is disabled.

Operating system: Ubuntu 20.04.5 LTS
CPU architecture: x86_64
Kernel: linux 5.15.0-60-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.12.1

**Comment by droidmonkey** [comment]
> having worked perfectly until ten minutes

Did anything about your keepassxc installation ALSO change 10 minutes ago?  If not, we are definitely not to blame. 

Hover over the red field to see the error message.

**Comment by r3times** [comment]
> Did anything about your keepassxc installation ALSO change 10 minutes ago? If not, we are definitely not to blame.

Nothing in relation to the installation changed - the database was saved and closed, reopened a few minutes later with my preferred auto-type no longer working. Might it be related, somehow, that all the columns I had previously resized or hidden had also returned to their defaults?

> Hover over the red field to see the error message.

Trying to reassign the shortcut removed the red highlight, so no error message appears. As the OP stated, it simply blanks the field until I choose an alternative.

**Comment by droidmonkey** [comment]
I'm not sure but there are no systemic issues with our shortcut assignment code. Any problems are entirely local to your machine unfortunately.

**Comment by jmssil** [comment]
I just got this issue after updating to 2.7.5. Previous Ctrl+Alt++A shortcut stopped working. Can only define a different one. Will reboot to see if it fixes.

**Comment by jmssil** [comment]
> I just got this issue after updating to 2.7.5. Previous Ctrl+Alt++A shortcut stopped working. Can only define a different one. Will reboot to see if it fixes.

No reboot was needed. There was a process of KeePassXC running intensively since the update. I killed it and started a new one and it was fixed.

Seems like the first instance of the program (the one that was running intensively) was preventing the other one to use the same shortcut, which makes sense.

**Comment by fredless** [comment]
> a process of KeePassXC running

same exact thing here. I had 3 instances running, killing older keepassxc process allowed the shortcut to be reset to the default. and also made by browser extension start working again.

**Comment by stinos** [comment]
> same exact thing here

Confirmed. I don't know where the other instances suddenly came from, there was no update and I don't usually close KeepasXC, but closing them makes the shortcut available again.
