### ISSUE TITLE
Key exchange was not successful when KeePass started via AutoHotkey

### ISSUE THREAD

**Issue by gene-pavlovsky** [keepassxreboot/keepassxc#5986]
## Overview
When I start KeePassXC via an AutoHotkey script, both Chrome and Firefox are not able to connect to KeePass.
An error is shown: "Key exchange was not successful"

When KeePass is started using a shortcut in the Windows Start Menu, both browsers are able to connect.

## Steps to Reproduce
1. Install AutoHotkey ([link](https://www.autohotkey.com/))
2. Find or create the default `AutoHotkey.ahk` script ([info](https://www.autohotkey.com/docs/FAQ.htm#DefaultScript))
3. Add this line to `AutoHotkey.ahk`: `#k::Run C:\Program Files\KeePassXC\KeePassXC.exe`
4. Run AutoHotkey
5. Make sure KeePassXC is not running
6. Press `Win`+`K` to run KeePassXC
7. Try connecting to KeePassXC using Firefox or Chrome

## Expected Behavior
Everything works

## Actual Behavior
Key exchange was not successful

## Context
Everything works correctly if KeePassXC is started normally via Windows Start Menu.
Observing the process tree using Process Explorer, I can see that in both cases KeePassXC runs under my regular user account. The only difference I can see is that when started via AutoHotkey, the KeepassXC process is a child of the AutoHotkey process. When KeePassXC is started normally, it doesn't have a parent process. Maybe this is relevant.

AutoHotkey 1.1.33.02
FireFox 84.0.2 or Chrome 88.0.4324.104

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.6.3
Revision: beae186

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 10 Pro 10.0.19042 Build 19042

**Comment by droidmonkey** [comment]
We don't support this method of running. You should fork the process so that it is not a child of autohotkey.

**Comment by droidmonkey** [comment]
You might have to have autohotkey call a bash script that starts keepassxc as a forked process (ie, not a child).

**Comment by gene-pavlovsky** [comment]
@droidmonkey I'm just wondering why it works fine on my other laptop that has Win7

**Comment by droidmonkey** [comment]
I have no idea and no way to debug that

**Comment by gene-pavlovsky** [comment]
@droidmonkey As a (non-Windows) programmer, I'm curious, why being a child of other process affects how browser integration works (or not)?

I can confirm that modifying the AutoHotkey code to start KeePassXC in it's own process tree does fix the issue.
I used the solution described in [this post](https://www.autohotkey.com/boards/viewtopic.php?p=47347&sid=4972f6d93f6ebcbd6ef7a3ee1a66935b#p47347).

Relevant quote:

> Installer.ahk in the AutoHotkey program folder contains a function called ShellRun which uses Explorer to launch an executable/file. (The installer uses it to launch AutoHotkey without admin privileges when UAC is enabled.)

**Comment by droidmonkey** [comment]
No clue but glad you fixed it
