### ISSUE TITLE
TOTP - View prevent closing database after inactivity

### ISSUE THREAD

**Issue by frank-github** [keepassxreboot/keepassxc#5987]
## Overview
Database setting: automatically closing after specified inactivity limit 
Open TOTP Windows prevent closing database

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Open TOTP view for an database entry
2. TOKEN shown and refresh every xx seconds (30s in my case)
3. database never been closed automaticlly

## Expected Behavior
[NOTE]: #  database should be closed after specified inactivity setting

## Actual Behavior
[NOTE]: # TOTP generated Token is refresh again and again, database never closed

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.5.4
Revision: dcca5aa

Qt 5.11.3
Diagnosemodus disabled

Betriebssystem: Debian GNU/Linux 10 (buster)
CPU-Architektur: x86_64
Kernel: linux 4.19.0-13-amd64

Aktivierte Erweiterungen:
- Auto-Type
- Browser-Integration
- SSH-Agent
- KeeShare (nur unbestätigtes Teilen)
- YubiKey
- Secret-Service-Integration

Kryptographische Bibliotheken:
 libgcrypt 1.8.4

Desktop Env: Gnome
Windowing System: X11

**Comment by droidmonkey** [comment]
You are very out of date

**Comment by frank-github** [comment]
very out of date? 
2.5.4 is the actual package for debian buster packports

**Comment by droidmonkey** [comment]
Yah that doesn't mean much. We are on 2.6.3

**Comment by frank-github** [comment]
but I can't update to this 2.6.3 because of unresolved dependencies :-(
any plans of update the debian buster backports?

**Comment by droidmonkey** [comment]
Use our appimage or snap

**Comment by frank-github** [comment]
okay, I did get this appImage a try and it fixed this problem :-)
