### ISSUE TITLE
Error Message: Error opening database: Invalid Header-Data Length

### ISSUE THREAD

**Issue by gregorwolf2** [keepassxreboot/keepassxc#5988]
Hi
I wanted to open my keepassxc file on a mac 10.15.7.
I get an error message tin red background on the top, after I entered my password for the DB, telling me: 
Error opening database: Invalid Header-Data Length. 
Now I cant open the DB and cannot access any of my passwords. How can I fix this?
Thanks in advance.
G. W.

**Comment by droidmonkey** [comment]
Your database file is corrupt. Transfer it again.

**Comment by gregorwolf2** [comment]
What does it mean: Transfer it again?

**Comment by droidmonkey** [comment]
The way you phrased your situation it sounds like you were using a different computer beforehand.

**Comment by gregorwolf2** [comment]
then I phrased it wrongly. It was on a USB Stick as always before.

**Comment by droidmonkey** [comment]
Then it's definitely corrupt. USB sticks are notorious for corrupting data.
