### ISSUE TITLE
How do i get started with development?

### ISSUE THREAD

**Issue by ToKaTpoHb** [keepassxreboot/keepassxc#599]
Basically, can you give more information about what IDE i could use (QT Creator or similar), what steps i should do to understand more whats going in in code etc...

**Comment by phoerious** [comment]
Most technical stuff is in the Wiki: https://github.com/keepassxreboot/keepassxc/wiki
As IDE you can use whatever you want. Most of use use QtCreator or something similar (I suppose @weslly  is using Xcode on macOS). I also used KDevelop for some time and will give CLion another try once they improve their Qt compatibility. But even Vim is possible.

**Comment by ToKaTpoHb** [comment]
Ok, wiki not really helps.

**Comment by ToKaTpoHb** [comment]
I forgot to tell, what should i learn to start helping with this project? (c++, OOP, ???)

**Comment by phoerious** [comment]
Modern C++, Qt5. OOP is a necessary basic concept.

**Comment by droidmonkey** [comment]
My personal recommendation is to learn the basics and help out a small project. Once you are comfortable you can come back and help us. We are a very mature and very complex project that will be incredibly daunting to beginners (and likely not help you succeed).
