### ISSUE TITLE
While adding second URL, tab changes to SSH Keys

### ISSUE THREAD

**Issue by kurwa-69420** [keepassxreboot/keepassxc#5990]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
While adding second URL to entry, tab changes to SSH keys after clicking apply

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
Requires: Entry with SSH Key, SSH agent integration disabled
1. Create new entry
2. Fill information (username, password, URL, notes)
3. Go to Browser Integration
4. Add another URL
5. Click Apply

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Show additional URLs tab instead of SSH.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Instead of showing Additional URLs tab, it shows SSH Keys.

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.3
Revision: beae186

Qt 5.15.2
Debugging mode is disabled.

Operating system: Windows 10 Version 1909
CPU architecture: x86_64
Kernel: winnt 10.0.18363

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
- libgcrypt 1.8.7

**Comment by droidmonkey** [comment]
Cannot reproduce
