### ISSUE TITLE
Export Individual Folders / Export as .kdbx File

### ISSUE THREAD

**Issue by sixsox** [keepassxreboot/keepassxc#5992]
## Summary
Allow individual folders to be exported.
Allow export to .kdbx file.

## Examples
In the folder tree, right-click on a folder and select "export folder" from context menu.
OR
In the application menu select Database > Export > "Current folder ..."

## Context
This would be a quick method for extracting a smaller subset from a larger 'master' password store.
Examples:
Sharing 'common' passwords within a group (family, office, etc)
Extracting only a subset of passwords for use on a mobile device.

**Comment by droidmonkey** [comment]
Dup #1940
