### ISSUE TITLE
Link kdbx Files within kdbx Files

### ISSUE THREAD

**Issue by sixsox** [keepassxreboot/keepassxc#5993]
## Summary
Open one or more kdbx files within another kdbx file. 
Allows access to several kdbx files through one 'hub' kdbx file.
The 'hub' kdbx file stores the credentials for the linked kdbx files and also shows their contents within its own hierarchy.

## Examples
File Menu: Database > Link External Database File
The linked external database would then show up as group within the folder hierarchy.

## Context
This would allow having a shared kdbx file with common credentials accessed by several 'hubs'.
AND OR
Instead of saving different types of credential to groups, it would be possible to save different types of credentials to individual kdbx files with very strong passwords. The hub file might then have a password that is humanly possible to remember. From the outside it would not be possible to tell which of the kdbx files is used as hub. 
AND OR
'Hub' files act as proxies or gateways to the kdbx files containing the actual credentials. Different 'hub' files allow access to different sets of credential groups.

**Comment by droidmonkey** [comment]
Already possible, read the user manual for AutoOpen and KeeShare
