### ISSUE TITLE
Can not use Ctrl-F9 auto-type shortcut after 2.6.3

### ISSUE THREAD

**Issue by Mogost** [keepassxreboot/keepassxc#5994]
After upgrading to version 2.6.3, I cannot use the Ctrl-F9 auto-type keyboard shortcut. This keyboard shortcut worked on previous versions.
When I try to set Ctrl-F9 as a auto-type shortcut, the field turns pink, however Ctrl-F8 is set fine.

KeePassXC - 2.6.3
Revision: beae186

Operating System: Windows

**Comment by droidmonkey** [comment]
We haven't changed any auto type code in the past 3 versions.

**Comment by droidmonkey** [comment]
You probably have the same problem as #5985

**Comment by Mogost** [comment]
I don't know what caused it.
But for some reason, the previously working keyboard shortcut broke.
I can set the shortcut Ctrl-F8 just fine, but not Ctrl-F9.
![image](https://user-images.githubusercontent.com/721963/105706212-51c00e80-5f22-11eb-9d50-0c6278d23613.png)

**Comment by droidmonkey** [comment]
closing as duplicate
