### ISSUE TITLE
Hide passwords shortcut doesn't work (Ctrl + Shift + c )

### ISSUE THREAD

**Issue by YosypC** [keepassxreboot/keepassxc#5995]
## Overview
Pressing the shortcut in the main screen doesn't toggle the option. Manually going into View -> Hide passwords does work.
Pressing Ctrl + Shift + b toggles the Usernames as intended.

## Steps to Reproduce
Self explanatory.

## Expected Behavior
Hiding / unhiding the passwords in the view when shortcut is executed.

## Actual Behavior
Doesn't affect the current option and leaves it as is.

## Context
[NOTE]: #
KeePassXC Version 2.6.3
Revision: beae186

[NOTE]: #
Operating System: : Windows 10 Pro Version 2009
Build no. 19042.746

**Comment by droidmonkey** [comment]
That shortcut was removed a while ago because it was triggered accidentally by lots of people. It's not coming back.
