### ISSUE TITLE
Cant Verify Signature - (not tech proficient)

### ISSUE THREAD

**Issue by PTillman44** [keepassxreboot/keepassxc#5996]
I am unable to verify the signature of keepassxc. 
Yesterday, I downloaded, but did not install, KeepassXC. 
Today, I installed Homebrew via terminal. 
Then I installed GnuPG.
Then I unsuccessfully attempted to retrieve the Public Key by importing via terminal from a Keyserver.
Then I successfully retireved the public key from the KeepassXC website. 
Then I tried to verify the key using "gpg --verify KeePassXC-*.sig" but received the error "gpg: can't open `KeePassXC-*.sig': No such file or directory"
Then, in an effort to redownload via a new method, I ran the command "brew install --cask keepassxc" in Terminal. 
I assumed this would allow the file to download but not install until after I verified the download and then approved the install. 
So, is there a way to verify this download? Do i need to uninstall and reinstall? are there other actions that I should take? I have saved the Terminal session for your review if you would like. Do I need to omit any information from the terminal session for security? if so, what?

**Comment by droidmonkey** [comment]
You don't really need to do any of that. The download for macOS is signed by one of our lead developers. If you really want to verify the download just follow these instructions: https://keepassxc.org/verifying-signatures/

**Comment by PTillman44** [comment]
Thank you.
