### ISSUE TITLE
History for some entries are not showing updates 

### ISSUE THREAD

**Issue by whidbeytech** [keepassxreboot/keepassxc#5997]
I have an example of a KPXC entry (probably multiple of them, I haven't looked yet) which shows a number of what appear to be identical history items from the original creation date of the entry but no history items thereafter. I changed the password for the KPXC entry today (20210125) and then by circumstance was required to look for the original immediately thereafter, and the original was not available to me through the history items which were all dated 20210107.

MacOS 10.15.7
KeepassXC 2.6.3
Language: US English

Thanks for all the great work on this product, all.

**Comment by droidmonkey** [comment]
Needless to say this is not reproducible. If it were, we would never pass our automated tests. Please provide more information as to the circumstances that this occurs. Can you reproduce this with a brand new database?
