### ISSUE TITLE
Keyboard navigation between multiple database tabs on mac OS

### ISSUE THREAD

**Issue by sts10** [keepassxreboot/keepassxc#600]
Feature request: Provide keyboard shortcuts, like Cmd/Ctrl + [num], to navigate between multiple databases while using mac OS. 

## Expected Behavior

Let's say I have database A open in my first KeePassXC tab and database B open in my second KeePassXC tab. When I want to switch from database A to database B, I'd love to be able to hit `Command + 2` or `Control + Tab` or `Command + }` to quickly jump to the second tab, database B. 

I know that currently on Ubuntu `Control + Tab` and `Shift + Control + Tab` navigate tabs left and right, but those shortcuts aren't working on mac OS for me. 

## Current Behavior

On macOS I can't find any keyboard shortcuts for navigating between tabs.  

## Possible Solution

In addition to the functionality described about in the Expected Behavior section, it'd be nice if when users have multiple database tabs open, the keyboard shortcut for navigating to a given database tab be displayed in the tab itself. [iTerm2 does this](http://imgur.com/a/Vzc0j). If we think that would clutter the tabs too much, maybe these keyboard shortcuts could only be displayed when the user holds down their OS's meta key.

## Steps to Reproduce (for bugs)
1. Open two or more databases in one KeePassXC session. Be on the first tab.
2. Hit `Command + 2` or `Control + Tab` or `Command + }`
3. Nothing happens. User stays in same tab.

## Your Environment

* KeePassXC version/commit used: 2.1.4 cb283bb95ae559d044415f426f841c27bff383f0
* Qt version (e.g. Qt 5.3): 5.8.0
* libgcrypt 1.7.6
* Operating System and version: Mac OS 10.10.5

**Comment by tomhundt-navera** [comment]
**Workaround:**  On Mac OSX, using BetterTouchTool, I set up Cmd+1, Cmd+2, Cmd+3 to activate a series of keyboard movements, starting with Ctrl-F2 (move focus to the menu bar -- this is enabled in System Preferences > Keyboard > Shortcuts), then two right-arrows (moves to Database menu), three down-arrows (moves to Recent Databases), one right-arrow (moves into submenu, listing the recent databases -- which also correspond to the ones I have open), then either zero/one/two down-arrows (moves to the 1st/2nd/3rd database name) and finally carriage return (activates it).  This works whether the databases are locked or not.

Needless to say, this is a total kludge.  Would much rather have native support :-)

**Comment by tomhundt** [comment]
BTW on Finder (and Chrome), Ctrl+Tab cycles through the tabs.

**Comment by droidmonkey** [comment]
This should be closed as it is implemented in 2.4.0 (this was a duplicate issue). CTRL+TAB is registered as a shortcut in KeePassXC for switching tabs, but MacOS doesn't recognize it (perhaps another Qt bug). We also register CTRL+PGUP and CTRL+PGDN to switch tabs.
