### ISSUE TITLE
Entries can no longer be moved to other groups

### ISSUE THREAD

**Issue by Ralffe** [keepassxreboot/keepassxc#6000]
## Steps to Reproduce
Unfortunately, a created entry can no longer be moved to another group. When sorting the entries it was just possible, now it doesn't work anymore.

## Expected Behavior
Entries should be able to be moved to other groups with the mouse.

## Actual Behavior
Entries can no longer be moved to other groups.

## Debug-Info
KeePassXC - Version 2.6.3
Revision: beae186

Qt 5.15.1
Diagnostic mode is disabled.

Operating system: macOS 10.15
CPU architecture: x86_64
Kernel: darwin 19.6.0

Enabled extensions:
- Auto-Type
- Browser integration
- SSH agent
- KeeShare (confirmed and unconfirmed sharing)
- YubiKey
- TouchID

Cryptographic libraries:
- libgcrypt 1.8.6

Translated with www.DeepL.com/Translator (free version)

**Comment by phoerious** [comment]
See #5636
