### ISSUE TITLE
UX : Delete Entry in Database Reports

### ISSUE THREAD

**Issue by webafrancois** [keepassxreboot/keepassxc#6005]
## Summary
How can I simply delete an entry in the database reports ?

## Examples
* When I look at the database Reports, I see some old weak passwords than would be deleted. I can simply modify this entry and it's a great option. But I cannot delete it in the interface.
* I have to quit database reports, find the obsolete entry, delete it and return to the database reports, to find the next obsolete entry.

## Enhancement - UX
It would be useful to have an option to delete some entry in the database reports.

**Comment by droidmonkey** [comment]
Good idea!

**Comment by droidmonkey** [comment]
Duplicate of #4986
