### ISSUE TITLE
TOTP and attachment icons are black after #5851

### ISSUE THREAD

**Issue by yan12125** [keepassxreboot/keepassxc#6006]
## Overview
After #5851, TOTP and attachment icons in the entry view are painted as a black rectangle. `git bisect` indicates 80c1b9be6a09cee67411840ecde129bcab70ebe1 to be the first bad commit. The issue can be reproduced on all themes - classic, dark and light.

I'm not sure if this is the same issue as the one mentioned in this comment: https://github.com/keepassxreboot/keepassxc/pull/5989#issuecomment-766796079. Created anyway for tracking.

> It still does not fix the paperclip and clock icon showing up as filled in blocks on the entry list.

## Steps to Reproduce
1. Create an entry with an attachment or TOTP settings

## Expected Behavior
![圖片](https://user-images.githubusercontent.com/1937689/106088093-41957280-6160-11eb-8453-27994cad4b98.png)
If I build from 37dab85df7e196c5596dd42d7fe09b95284507bd (the parent commit of 80c1b9be6a09cee67411840ecde129bcab70ebe1), or commenting out https://github.com/keepassxreboot/keepassxc/commit/80c1b9be6a09cee67411840ecde129bcab70ebe1#diff-3ee027a092936d0712f76a2bb9a8d29df8399ba778d92b615c1213d2baab3a18R141, icons are painted normally.

## Actual Behavior
![圖片](https://user-images.githubusercontent.com/1937689/106088155-5d991400-6160-11eb-9e14-8a46db8c6ff5.png)

## Context
KeePassXC - Version 2.7.0-snapshot
Build Type: Snapshot
Revision: 9a7b20c

Qt 5.15.2
Debugging mode is enabled.

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 5.10.5-arch1-1

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (only unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.9.0-unknown

Operating System: Arch Linux
Desktop Env: LXQt+xfwm4
Windowing System: X11

**Comment by droidmonkey** [comment]
Yah we know, its related to the work done in icons.cpp.

**Comment by yan12125** [comment]
Thanks for confirmation. Mind to shed some light on the rationale behind those `painter->fillRect` invocations? I'm not sure how macOS works, but they seem unneeded on Linux (and maybe Windows).

**Comment by phoerious** [comment]
fillRect is necessary for recolouring the icon to adapt to light/dark themes. The issue is somewhere else and I submitted a fix for it.

**Comment by yan12125** [comment]
Thanks for explanations and the fix! I can confirm icons work with the latest develop commit (33e6da33cadaf92d017103d46a2ba3b3716665de).
