### ISSUE TITLE
keepassxc.cli: cannot open x.kdbx: not a plain file

### ISSUE THREAD

**Issue by Lonerider2010** [keepassxreboot/keepassxc#6007]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
Tried to open the keepass database x.kdbx with the keepassxc.cli (snap), but it failed with "x.kdbx: not a plain file".

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Install keepassxc via snap.
2. Open database with 'keepassxc.cli open x.kdbx'
3. Error message "x.kdbx not a plain file"

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
keepassxc.cli should open the database, as the gui version does.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Cannot open the database

## Context
[NOTE]: # ( Give us any additional information you may have. )
Running keepassxc installed with snap on Xubuntu 20.10 on arm64 (Raspberry Pi 4).

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.6.3
Revision: beae186
Distribution: Snap

[NOTE]: # ( Pick choices based on your environment )
Operating System: Xubuntu 20.10
Desktop Env: XFCE
Windowing System: X11

Betriebssystem: Ubuntu Core 18
CPU-Architektur: arm64
Kernel: linux 5.8.0-1010-raspi

**Comment by droidmonkey** [comment]
How is this x.kdbx stored? In your home directory? On a network share? This is likely an issue with snap sandboxing.

**Comment by Lonerider2010** [comment]
The database file is stored on a network drive, mounted to /media. So I executed 
`sudo snap connect keepassxc:removable-media` in order to get access to the database file.
That works fine for me. How can I make this working for keepassxc.cli?

**Comment by droidmonkey** [comment]
Hmmm I wonder if this is because the cli does not have network plug access. It does have removable media plug access. Have you tried `sudo snap connect keepassxc.cli:removable-media`

**Comment by Lonerider2010** [comment]
This leads to the error message
`snap "keepassxc.cli" has no plug named "removable-media"`.

**Comment by droidmonkey** [comment]
This seems like a snapd bug to me
