### ISSUE TITLE
Keepassxc replaces the 1st character of username when using Auto-type (Wayland + specific websites)

### ISSUE THREAD

**Issue by Saroumane** [keepassxreboot/keepassxc#6009]
## Overview
Under specific conditions, Keepassxc replaces the 1st character of username when using Auto-type.
Conditions :
- Wayland
- specific Websites

## Steps to Reproduce
1. Go to https://***** (banking website, can disclose privately)
2. Type the key combination to trigger Auto-type in username field. (My custom Auto-type is very basic : {USERNAME}  )

## Expected Behavior
I expect the username to be filled in username field without alteration

## Actual Behavior
The first character of the username (the number **3**) is replaced by the character quote (**"**).
I don't know if it's a pure coincidence, but on my french keyboard, **3** and **"** are on the same key. (first row under function keys, 4th key from the left)

## Context
I don't reproduce the problem under X, only with Wayland.
I saw the problem on other websites (I don't remember which ones)
My custom Auto-type is not guilty, I reproduce the problem with default Auto-type.

## Workaround
Use a custom Auto-type and add {CLEARFIELD} before {USERNAME}.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.6.1
Revision: 9a35bba

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux (Ubuntu)
Desktop Env: Gnome
Windowing System: Wayland

**Comment by droidmonkey** [comment]
#324

**Comment by Saroumane** [comment]
Interesting, but : 
- why do I have the problem only with Wayland, not X ?
- why the problem does not happen for every "3" I use in usernames ?
- why do I have this problem whereas I already apply your workaround ( https://github.com/keepassxreboot/keepassxc/issues/324#issuecomment-735251112 ) : I have a "sleep 30" in the autostart gnome script that launches keepassxc
- and last but not least, why my  workaround (to add {CLEARFIELD}) works ?

Does not really sounds like a duplicate to me, but you are the expert :)

**Comment by droidmonkey** [comment]
You aren't using Wayland if you are using autotype. You are using X11 connected to Wayland through xwayland. The error could be in that interface boundary, not sure. The error could also be with your browser, Firefox has been known to eat keys and screw up autotype if the delay between keystrokes is too low. You can try increasing the keystroke delay in the autotype settings.

**Comment by Saroumane** [comment]
> You aren't using Wayland if you are using autotype (in the backend). You are using X11 connected to Wayland through xwayland.

Indeed.
> The error could be in that interface boundary, not sure. The error could also be with your browser, Firefox has been known to eat keys and screw up autotype if the delay between keystrokes is too low. 

I use Chromium.
>You can try increasing the keystroke delay in the autotype settings.

Already tried, no success. But that's OK, I'll stick with {CLEARFIELD}
By the way, thanks for all the good work you have done for keepassxc. (Out of scope : as **droid**monkey do you recommend KeePassDroid or KeePassDX on android ?)

**Comment by droidmonkey** [comment]
I use KeePassDX, it is a modern interface and matured quickly

**Comment by droidmonkey** [comment]
Reopened this to take another look, but it might be very unique to your system.

**Comment by stefan123t** [comment]
@Saroumane what is the keyboard layout setting on your Desktop environment ?
Do you have another keyboard layout configured besides French/AZERTY ?
How is keyboard layout switching configured (per window or global Alt-Shift) ?
What are the results of `setxkbmap -print -verbose 10 | grep '\(layout\|xkb_symbols\)'` ?
Kind regards,
Stefan

**Comment by Saroumane** [comment]
@stefan123t 
No switching needed, only one keyboard : Ubuntu/Gnome builtin "French (AZERTY)"  (the most used French keyboard)

![image](https://user-images.githubusercontent.com/22261137/110709945-58b68e00-81fd-11eb-8e5d-e472da9921c0.png)

```
$ setxkbmap -print -verbose 10 | grep '\(layout\|xkb_symbols\)'
layout:     us
	xkb_symbols   { include "pc+us+inet(evdev)"	};
```

**Comment by stefan123t** [comment]
@Saroumane funny that it says in setxkbmap you are using Englisch (US) / pc+us but the Gnome config clearly says your input source being French (AZERTY).
This is a contradiction and it may be explained the way @droidmonkey pointed to, i.e. with the path over xwayland there might be a need to switch between those keyboard layouts, which is replacing your first character ?

**Comment by Saroumane** [comment]
Well done, you found the guilty setting.
I did :
$ setxkbmap fr
$ setxkbmap -print -verbose 10 | grep '\(layout\|xkb_symbols\)'
layout:     fr
	xkb_symbols   { include "pc+fr+inet(evdev)"	};

then restarted keepassxc, and the problem is solved, no need to {CLEARFIELD} anymore.

To explain the context : my general strategy regarding lang/locales/layout etc is :
- keep language settings with their "vanilla" values : `Language : US` in Gnome, `LANG="en_US.UTF-8"`, etc
- locales (LC*) set to ` "fr_FR.UTF-8"`
- input keyboard layout set to match physical keyboard (so French "AZERTY")
All is set with Gnome Settings UI
So I never paid attention to `setxkbmap`

Do you think I should open a bug in Gnome, (because Gnome UI for "Input sources" forgets to set setxkbmap ?)

**Comment by stefan123t** [comment]
@Saroumane while I second your motion to keep everything in C / ASCII / en_US.UTF-8 for interoperability and ease of finding error codes I do not know why it does not update the setxkbmap in your place. I assume the native Gnome Input Sources does something different from the Linux Mint > Preferences > System Settings > Keyboard. So yes, it should be worthwhile to raise the issue upstream in Gnome especially with the additional xwayland layer in the play.

**Comment by Saroumane** [comment]
As a permanent workaround, I tried to put `setxkbmap fr`  in `/etc/rc.local `or `~/.profile` but it had no effect.
Any other idea ?
