### ISSUE TITLE
KeePassXC removed all my passwords without move them to trash

### ISSUE THREAD

**Issue by atiris** [keepassxreboot/keepassxc#6013]
## Overview

KeePassXC permanently removed all my passwords (or I did something unexpected, but I really don't know what, in any case i expect any deleted password record in Trash)

## Steps to Reproduce

Sorry. Despite several attempts to repeat, I was unable to repeat the process so that the problem occurred again :(

**I understand that without steps to repeat the problem, this report is not very important, but I entered it here to make this situation traceable, and if it is repeated to someone, we may find a problem.**

It occurred in this case:
I had a kdbx file with several groups and passwords stored locally. I was trying to add entries from a shared kdbx file from network storage (example path: \\server\drive$\passwd\file.kdbx). Unfortunately, I don't know exactly what activity I did last, but it was definitely a modification in KeeShare. After this adjustment in group and click to OK, all records (not only from group but from all database) were gone, But they were not in the trash either. The database was saved and there was no recovery option. 

Final state of my database file is this (there is no password record in entire file now):

![Snimka](https://user-images.githubusercontent.com/10474618/106264541-137a6600-6226-11eb-8ec3-10468299e90f.png)

## Expected Behavior

Any change in database which lead to remove record move this record to Recycle Bin.

## Context

**Debug info:**
KeePassXC - Version 2.6.3
Revision: beae186

Qt 5.15.2
Debugging mode is disabled.

Operating system: Windows 10 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.19042

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
- libgcrypt 1.8.7

**Comment by phoerious** [comment]
You may want to check your settings. The trash can be turned off.

**Comment by atiris** [comment]
Hello. Yes, I know about this option, I have absolutely the trash enabled and as you can see on the screenshot, it was enabled even when it happened. Recycle Bin is in my language Kôš.

**Comment by droidmonkey** [comment]
This is a keeshare induced bug, but I thought it was fixed way back when we introduced keeshare.

**Comment by droidmonkey** [comment]
#6477 captures this issue better.

**Comment by tupo2** [comment]
> You may want to check your settings. The trash can be turned off.

Hi,

Where is located this option? I only find the `Move entries to recycle bin without confirmation` under `Security`.
I have KeePassXC 2.7.4.

**Comment by tupo2** [comment]
Found. It's in `Database` > `Database Settings`
