### ISSUE TITLE
Setup for daily database backups, or some advanced form of backup

### ISSUE THREAD

**Issue by atiris** [keepassxreboot/keepassxc#6014]
## Summary

Would it be possible to set the program to create daily backups of database files, or at least more than one last backup? 

When the file is opened, it checks whether there is a backup for today, and if not, it creates it in the database folder, just as it creates a backup of the previous state. With configuration how many days back to maintain backups.

And some form of protection / backup should be turned on by default after clean install of keepassXC.

However, probably it is more likely to use some external backup tool. If this is the recommended procedure, can you recommend any such tool?

## Examples

So, with settings for backup:
- daily with time code like: yyyy-mm-dd
- continuously for 3 changes

After open file a.kdbx it create
a.2021-01-20.kdbx   (if such a file does not exist, and possibly delete older files that older than the given number?)
After save a.kdbx during this day XC create next file in sequence which does not exists
a.old.1.kdbx ... a.old.2.kdbx ... a.old.3.kdbx ... 
So if there is a.old.2542.kdbx, a.old.2543.kdbx and a.old.2544.kdbx, after save XC create a.old.2545.kdbx and delete a.old.2542.kdbx

## Context

I had an unpleasant experience with deleting data, described in more detail in this [bug](<https://github.com/keepassxreboot/keepassxc/issues/6013>)

**Comment by droidmonkey** [comment]
We have discussed this before. You don't want the same application handling your backups and primary data. We recommend cloud storage or personal storage with version history (nextcloud, syncthing)

**Comment by atiris** [comment]
Ok, thanks. I'm sorry, I couldn't find the previous discussion.
