### ISSUE TITLE
TOTP placeholder not work

### ISSUE THREAD

**Issue by mixman68** [keepassxreboot/keepassxc#6015]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
I have this autotype sequence {USERNAME}{TAB}{PASSWORD}{TAB}{TOTP}

username and password successfully replaced, TOTP replaced by empty

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Open a text editor
2. Choose an entry with TOTP and this key sequence {USERNAME}{TAB}{PASSWORD}{TAB}{TOTP}
3. Autotype
4. Check output

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
TOTP filled

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
TOTP empty

## Context
[NOTE]: # ( Give us any additional information you may have. )
Autotype

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.3.6

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows/macOS

**Comment by mixman68** [comment]
I have found why this.

The custom pattern defined in Window capture not triggered

**Comment by droidmonkey** [comment]
You are on an ancient version of keepassxc
