### ISSUE TITLE
After closing the preview panel with X button, menu item "Show Preview Panel" is still checked

### ISSUE THREAD

**Issue by okoetter** [keepassxreboot/keepassxc#6017]
## Overview
After closing the preview panel by clicking the X button on the top right of the preview panel, the menu item "Show Preview Panel" is still checked. You have to select it twice to show the panel again.

## Steps to Reproduce
1. Be sure to view the preview panel
2. Click the X button on the top right of the preview panel
3. Look into the "View" menu: "Show Preview Panel" is checked

## Expected Behavior
Look into the "View" menu: "Show Preview Panel" is **not** checked

## Actual Behavior
Look into the "View" menu: "Show Preview Panel" is checked.

## Context
KeePassXC - Version 2.6.3
Revision: beae186

Qt 5.15.2
Debugging mode is disabled.

Operating system: Windows 10 Version 1909
CPU architecture: x86_64
Kernel: winnt 10.0.18363

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
- libgcrypt 1.8.7

**Comment by droidmonkey** [comment]
That's cause that menu item means it's enabled not that it's visible

**Comment by okoetter** [comment]
Hmmm... ok. 
And what's the difference for the average user? And how do I make it visible again after clicking on the x button? 
Sorry, no offense, but this is bad UX.

**Comment by phoerious** [comment]
Unless it is not disabled, it will pop up again when you select another entry. The panel as it is now will be reworked entirely in the next major release, so no need to track this issue here.
