### ISSUE TITLE
Theme does not change after changing system colors without restart since 2.5

### ISSUE THREAD

**Issue by wsid3** [keepassxreboot/keepassxc#6019]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
Hi!
Application interface color does not change instantly when changing system colors to a dark color in KDE Plasma (app downloaded from Manjaro repository). It only works if I restart the app. Happens with automatic as well as classic theme. My other Qt apps changes colors without restarting. I have set up my environment to change system colors to dark at a specific time (like an automatic night mode) and the KeePassXC client runs automatically on boot in the system tray and it's an inconvinience because I always have to restart the app and type the master password again when the dark mode starts.
It worked as expected before the 2.5 update. I also tested these 2 other configurations (apps downloaded from repos): 
(1): app version: 2.4.3, Qt version: 5.15.2 (KDE Neon Testing)
(2): app version: 2.3.1, Qt version: 5.9.5 (Kubuntu 18.04.5),
and they worked properly, so Qt version does not seem to affect this problem.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. launch KeePassXC
2. change to 'Breeze dark' in KDE Plasma system settings > appearance > colors

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Interface of KeePassXC changes to dark theme.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Interface of KeePassXC does not properly change to dark theme.
![Screenshot_20210129_130635](https://user-images.githubusercontent.com/66201465/106273513-1a5ba580-6233-11eb-8cb1-389dc1fa9ac7.png)
![Screenshot_20210129_131007](https://user-images.githubusercontent.com/66201465/106273700-6575b880-6233-11eb-96dc-e5ddedb4b8b1.png)

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.3
Revision: beae186

Qt 5.15.2
Debugging mode is disabled.

Operating system: Manjaro Linux
CPU architecture: x86_64
Kernel: linux 5.4.89-1-MANJARO

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- libgcrypt 1.8.7

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: KDE
Windowing System: X11

**Comment by phoerious** [comment]
We are not doing anything special here, particularly not if you are using the classic theme.

**Comment by da2x** [comment]
Same issue on macOS.
![dark-mode](https://user-images.githubusercontent.com/1102886/109733545-92fdab00-7bbf-11eb-83c1-99992e72c723.png)

**Comment by phoerious** [comment]
I cannot reproduce that at all. Make sure you have the latest version (2.6.4) and are not using the "Classic" theme.

**Comment by phoerious** [comment]
I am pretty sure you are using an old version. Theme switching was fixed on the develop branch and we backported it to 2.6.4.

**Comment by da2x** [comment]
> I am pretty sure you are using an old version. Theme switching was fixed on the develop branch and we backported it to 2.6.4.

The App menu: About says version 2.6.4. Selecting the app in Finder and pressing Cmd+i says version 2.6.4.

The same thing happens if I create a new user account on my Mac, downloading version 2.6.4 from [https://github.com/keepassxreboot/keepassxc/releases/download/**2.6.4**/KeePassXC-**2.6.4**-x86_64.dmg](https://github.com/keepassxreboot/keepassxc/releases/download/2.6.4/KeePassXC-2.6.4-x86_64.dmg), dragging it to ~/Applications, and launch KeePassXC in Light mode, and then switch the OS to dark from System preferences: General: Appearance.

**Comment by droidmonkey** [comment]
The default setting is definitely not classic, it is automatic.

**Comment by phoerious** [comment]
The Classic theme is for Qt to fix. It's fundamentally broken and we cannot fix it. Use "Automatic" instead, which is the default.
