### ISSUE TITLE
KeePassXC does not save new entries

### ISSUE THREAD

**Issue by lostados** [keepassxreboot/keepassxc#6020]
When I tried to include a new entry in KeePassXC today, I got the following error message:
"Writing the database failed: permission denied".
Please help: I could not find a way to redress this issue. It is altogether new, I had never had any problem with KeePass. I used it the last time some 2-3 days ago and I do not remember doing any changes to it.
I enclose a snapshot of the two error messages I got today.
I run Linux/Ubuntu Mate 20.10.

![Keepass error message](https://user-images.githubusercontent.com/51658350/106321090-91ecfd00-6252-11eb-98f8-bbcd3ed44354.png)
![Keepass message on closing](https://user-images.githubusercontent.com/51658350/106321101-987b7480-6252-11eb-83ce-a3820814dac8.png)

**Comment by droidmonkey** [comment]
Seems like something else is holding the file open, that is a file system error. Restart your computer.

**Comment by lostados** [comment]
You can't be serious! How come you closed the issue before hearing my reaction!!!

Unfortunately, it was not so: computer was shut and restarted a couple of times and the issue is still there.

**Comment by droidmonkey** [comment]
This isn't a problem with keepassxc. It's a file error, check your permissions and other basic settings.

**Comment by lostados** [comment]
Thank you. You are an expert and I am just a common-or-garden user - a 75-year-old user. Keepassxc did work for a while, now it no longer works. Whatever happened, I no longer feel safe about it, so the best thing is to do a complete uninstall.
Best

**Comment by droidmonkey** [comment]
Best of luck to you
