### ISSUE TITLE
KeePassXC does not save new entries (2nd attempt)

### ISSUE THREAD

**Issue by lostados** [keepassxreboot/keepassxc#6023]
When I tried to include a new entry in KeePassXC today, I got the following error message:
"Writing the database failed: permission denied".
Please help: I could not find a way to redress this issue. It is altogether new, I had never had any problem with KeePass. I used it the last time some 2-3 days ago and I do not remember doing any changes to it.
I enclose a snapshot of the two error messages I got today.
I run Linux/Ubuntu Mate 20.10.

**I sent this message yesterday and had the following reaction:

"Seems like something else is holding the file open, that is a file system error. Restart your computer".

The issue was closed before I had time to react. IT IS OF COURSE STILL THERE.

Very insecure now as to using KeePassXC**

![Keepass error message](https://user-images.githubusercontent.com/51658350/106354391-4b3de800-62d0-11eb-826b-54b5c2b00d5d.png)
![Keepass message on closing](https://user-images.githubusercontent.com/51658350/106354395-4f6a0580-62d0-11eb-9aaa-67e9b40cccd3.png)

**Comment by phoerious** [comment]
We know which error messages we programmed into KeePassXC and this ain't one of them. The message comes directly from the file system and the fact that your database is some temporary file in /tmp lets me assume that you are trying to use it from some sort of file system abstraction layer, which we do not control.

**Comment by lostados** [comment]
Don't worry. Problem solved: I gave up and uninstalled KeePassXC. I do not think it is safe to use it.

**Comment by droidmonkey** [comment]
The temporary file means he is using non-safe saves. The error occurs when Qt cannot remove the existing database file prior to copying the temp one into its place. It leaves the temp file where it is to prevent data loss.
