### ISSUE TITLE
Allow to change timestamp of entries

### ISSUE THREAD

**Issue by soybeansrabbitowl** [keepassxreboot/keepassxc#6024]
## Summary
The new feature is to change the timestamps of entries.

- Modified
- Created
- Accesed

## Examples

Here is an example how it could look like.

There is a plugin for KeePass (Windows).
https://github.com/JanisEst/KeePassTimestampChanger

KeePassTimestampChanger

![68747470733a2f2f61626c6f61642e64652f696d672f6b3135737369352e6a7067](https://user-images.githubusercontent.com/78264930/106358342-fa4be500-630b-11eb-8cc2-cda2241a4199.jpg)
![68747470733a2f2f61626c6f61642e64652f696d672f6b3230717362732e6a7067](https://user-images.githubusercontent.com/78264930/106358343-fc15a880-630b-11eb-862b-492429e7cb51.jpg)

## Context
I have created over 300 logins but the timestamps are wrong and I want to change it.

**Comment by droidmonkey** [comment]
Sorry but this does not make sense. Are you going to go one by one changing timestamps? The only one that would matter would be "created" since modified is changed every time you.. modify.. the entry.

**Comment by soybeansrabbitowl** [comment]
Supporting all timestamps is better so I can manage my login better, easier and faster.

Created timestamp is the most important of all for me, but the others are important too.

**Comment by droidmonkey** [comment]
We won't be implementing this
