### ISSUE TITLE
When opeing url, defaut to HTTPS instaed of HTTP

### ISSUE THREAD

**Issue by mooms06** [keepassxreboot/keepassxc#6025]
Currently, if I have an entry for `www.example.com`, KeepassXC tries to open the url `http://www.example.com` it should be `https://www.example.com`

**Comment by droidmonkey** [comment]
We send the url as written to your operating system to open, we won't be changing that behavior.

**Comment by mooms06** [comment]
How can I change the behavior of my OS then ? I use Windows 10.

**Comment by droidmonkey** [comment]
it's really up to the website itself. I tested a handful of urls and they all automatically up-converted to https. Just add https to the front.
