### ISSUE TITLE
Use Show Window in tray menu instead of Toggle Window

### ISSUE THREAD

**Issue by Lantizia** [keepassxreboot/keepassxc#6026]
So this feature request is solely about the menu that appears when you either...

- click the KeePassXC icon in your Linux "indicator" area
- click the KeePassXC icon in your macOS "status menus" area
- right click the KeePassXC icon in your Windows "notification" area
- right click the KeePassXC icon in your Linux "notification" area

In short... **TRAY ICON MENU** :)

![image](https://user-images.githubusercontent.com/10448369/106357344-873b7200-62fd-11eb-8250-2e388d437a25.png)

### The burning question...
Does anyone here actually find themselves opening this menu with the intention of using it to **HIDE** the KeePassXC window by using '**Toggle window**' ?

### Thoughts...
I'd suspect most of us might go into this menu to **SHOW** the KeePassXC window (whether minimised or hidden).... but I'd imagine it's barely ever used to actually hide it.  When most people experience a window in their way... they're going to just close or minimise it.  They're unlikely to use a special 3rd option tucked away in a menu which is separated from the window that they're actually trying to get rid of.

If like me you've got options 'Minimise instead of app exit' and 'Hide window to system tray when minimised' enabled.  Then if you've not realised the main window is already on the desktop... but just behind other windows... then you end up using the 'Toggle window' option twice to show it.

Basically I wish this option was instead simply '**Show window**'.  In other words...
- If it's on the desktop: bring it to the front
- If it's minimised: then restore it
- If it's hidden: then unhide it

KeePassXC isn't alone in having a toggle like this as [Deluge](https://deluge-torrent.org/) has got effectively the same option in their equivalent menu called '✓ Show Deluge' menu option (the ✓ appearing/disappearing when toggled).  

However a good example would be [Shutter](https://shutter-project.org/), which has a 'Show main window' option in their equivalent menu which does exactly what I am proposing.  Another good example is the default [indicator](https://launchpad.net/indicator-sound) for volume control that does it with its 'Sound Settings...' option (although that window can't minimise, so a slightly different scenario).

Minor extra thoughts (I can file these separately if needed)...

- About once in every 3 days I'm accidentally misclicking 'Toggle window' and instead click 'Lock Databases'.  Which is obviously annoying to then need to type two veeeery long passwords to reopen my databases!  I'd hate to think what someone with less mobility goes through.  Maybe put a spacer between these two options... or a confirmation dialog upon a request to lock databases?
- Also since this menu is very sparse... it might be an idea to add some more useful things to it.  Since I'm forced to use a [perverted](https://pleasantsolutions.com/passwordserver) version of the original KeePass too (for work reasons)... I use an [indicator](https://github.com/dlech/Keebuntu) which works with it.  That has the same menu entries except it also has 'Password Generator' and also 'Settings'... which I think both could be very handy to have (especially the former).

**Comment by droidmonkey** [comment]
This is the weirdest thing to write 10 paragraphs about.

**Comment by Lantizia** [comment]
Yeah I was going to say something along those lines on IRC :)  It speaks for itself!

**Comment by Asherathe** [comment]
FYI, on Peppermint 10 Respin, based on Ubuntu 18.04, right-clicking the icon brings up the menu and clicking shows or hides the window.

**Comment by droidmonkey** [comment]
Yes that's by design

**Comment by Mandymoore680** [comment]
????

**Comment by Lantizia** [comment]
> FYI, on Peppermint 10 Respin, based on Ubuntu 18.04, right-clicking the icon brings up the menu and clicking shows or hides the window.

I'd never heard of this distribution... confusingly the web site mentions Cinnamon, Xfce and LXDE?  (any ideas what Desktop Environment your particular installation is running?)

I'd presume since it supports right clicking that this is a 'notification' icon rather than an system 'indicator'.  

The system 'indicators' (much like the macOS menu bar icons) only support left clicking and doing that will always open up the menu in question.

**Comment by Asherathe** [comment]
> I'd never heard of this distribution... confusingly the web site mentions Cinnamon, Xfce and LXDE? (any ideas what Desktop Environment your particular installation is running?)

It's been around for 10 years, but doesn't seem like it's ever been especially well-known. The DE is a hybrid. The bottom panel and notification area come from XFCE 4.

> I'd presume since it supports right clicking that this is a 'notification' icon rather than an system 'indicator'.

 Yep, that's right.

> The system 'indicators' (much like the macOS menu bar icons) only support left clicking and doing that will always open up the menu in question.

That explains why there is a "toggle window" option, which I've wondered. Your idea makes perfect sense to me.

**Comment by Lantizia** [comment]
Interestingly I've just noticed in the [announcement of Xfce 4.16](https://www.xfce.org/about/news/?post=1608595200) (came out in December) it mentions...

> We added a new plugin to the panel dubbed "statustray" which combines both StatusNotifier and legacy Systray items. 

As far as I can tell this means both the "notification" area and application & system "indicators" get merged in to the one area.

Which makes me wonder how KeePassXC knows if it should be making one, the other or both?

**Comment by droidmonkey** [comment]
That's up to Qt to figure out.

**Comment by droidmonkey** [comment]
Tracking this in #149
