### ISSUE TITLE
"Accessed" time is not updated when I use only this function "Copy Username, Copy Password"

### ISSUE THREAD

**Issue by soybeansrabbitowl** [keepassxreboot/keepassxc#6027]
## Overview
The "Accessed" timestamp does not update when users perform the appropriate function that it needs to happen.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Create an entry with user name and password.
2. Wait 1 minute.
3. Now copy the username and password e.g via context menu.
4. See in the column under "Accessed" it was not updated. In this case it uses the same time as "Modified".

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
"Accessed" time is updated when users perform the corresponding function so that it works. Examples are Copy username and password or Open the entry.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Accessed time is not updated.

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.3
Revision: beae186

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows
Desktop Env:
Windowing System:

**Comment by droidmonkey** [comment]
#2005
