### ISSUE TITLE
Don't change file creation time on database save

### ISSUE THREAD

**Issue by soybeansrabbitowl** [keepassxreboot/keepassxc#6028]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
The option "Safely save database files" on Windows 10 makes a behavior for already created .kdbx file which is not typical for Windows world. When the database is modified, for example, an entry is added and then saved. Then the creation time of the file itself must not be set to current time.

The behavior in Windows is like this by default, if for example an already created .txt file is opened, edited and saved. Then only modified and access time is updated to current time. Creation time is not updated.

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )
On Windows 10, for example, it can be tested with the standard text editor.

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
It is unfamiliar and feels strange when KeePassXC behaves differently by default than other Windows software.

**Comment by droidmonkey** [comment]
We are not opening the file, writing, and closing it. The file is in fact being replaced by a new file. This is a standard Qt function called QSaveFile and we don't have control over the process.

**Comment by soybeansrabbitowl** [comment]
> We are not opening the file, writing, and closing it. The file is in fact being replaced by a new file. This is a standard Qt function called QSaveFile and we don't have control over the process.

Can you help me where to report the behavior so that it is fixed in general? Where do I report it and what details should I add or is it enough to send this report from?

**Comment by droidmonkey** [comment]
They won't fix / change the behavior, I looked it up already. I suppose we could capture the created time before save and apply that time after save.

**Comment by soybeansrabbitowl** [comment]
> They won't fix / change the behavior, I looked it up already. I suppose we could capture the created time before save and apply that time after save.

Good idea that solves the problem.
