### ISSUE TITLE
Add "Change Website Password" feature to database reports

### ISSUE THREAD

**Issue by ghost** [keepassxreboot/keepassxc#6032]
## Summary
Looking for an efficient workflow to fix and correct weak passwords while in the database reports view.

## Examples
I recently migrated to keepassxc and I am currently using the database reports features to fix some of my neglected passwords.
My current work flow is to close the reports tab and go delete duplicate entries then back again to reports just like issue#6005.
I also have many passwords that I need change, I double click on the entry from the reports, go to the url field, ctrl+a, ctrl+c, move to browser (alt+tab), open new tab (ctrl+t), paste (ctrl+v) and hit (enter), then proceed with password change.

## Enhancement - UX
Add a shortcut in the health check view that will open the url in a browser while simultaneously opening the password entry in edit mode? I wouldn't mind if ctrl+shift+u did that by default while in healthcheck mode. this shortcut could be configured in the settings to also bring up the password generator dialog, eliminating having to press (ctrl+g) when the user gets back to keepass. 
Another suggestion would be to add an option to show a quick health check score column in the regular database view.

**Comment by droidmonkey** [comment]
This should be coupled with using https://github.com/apple/password-manager-resources

**Comment by agamalce** [comment]
That's even better. Maybe we could go an extra step and have the browser extension auto change and save the password.
That being said, this list of urls still has a long way to go so maybe a ChangePasswordURL attribute can be specified and used to customize/override entries?
Thank you for your hard work.
