### ISSUE TITLE
Use "last access" to identy stale accounts/entrys

### ISSUE THREAD

**Issue by loeffelpan** [keepassxreboot/keepassxc#6035]
Hi.

I'm wondering about the difference between database fields "last modified" and "last access".
When will KeePassXC write these attributes?

Last modified is simly clear.
But in my database every entry shows the same timestamp on both attributed.

Is it possible to write "last access" on performing autotype (or accessing via browser extension)?
Would be fine to identify stale credential and delete them from database if no longer used.

Cheers,
Jan

**Comment by droidmonkey** [comment]
See #2005
