### ISSUE TITLE
Search through all opened databases

### ISSUE THREAD

**Issue by MrFrank17** [keepassxreboot/keepassxc#6036]
Hi,

I am using AutoOpen, so I have several opened databases.
Searching works only within the active one. Is it possible to search through all open databases?

Thanks
Frank

**Comment by droidmonkey** [comment]
Duplicate request

**Comment by dreua** [comment]
Could someone post the link to this duplicate here? I seem unable to find it.

**Comment by LifeSteala** [comment]
@dreua - I believe it is this issue:
https://github.com/keepassxreboot/keepassxc/issues/7269

**Comment by UnePierre** [comment]
Yeah, similar.
I think such a search feature in the main application would be appreciated, too.
