### ISSUE TITLE
Problem Auto unloading keys form ssh-agent

### ISSUE THREAD

**Issue by agamalce** [keepassxreboot/keepassxc#6037]
## Overview
The following scenario has the database loaded with multiple encrypted keys. Only one key is selected to be added when database is opened, and removed when database is closed. The key gets added, but not removed on database close or application exit.

## Steps to Reproduce
1. add an encrypted ssh key to the DB and select "Add key to agent when database is opened/unlocked" and "Remove key from agent when database is close/locked"
2. log off and back in to start with a clean ssh-agent. run "ssh-add -l" the key shouldn't be loaded.
3. unlock the keypassxc database and run "ssh-add -l"
4. lock the database and run "ssh-add -l"
5. close the database and run "ssh-add -l"
6. exit keepassxc and run "ssh-add -l"

## Expected Behavior
the key should get unloaded from the ssh-agent cache

## Actual Behavior
the doesn't get unloaded

## Context
What worked for me was navigating in keepassxc to the entry, and manually choose "Remove from agent" and that only works before exiting keepassxc. If I restart keepassxc "Remove from agent" doesn't work  and it seems that keepassxc loses the reference for the key and is unable to unload it from the again.

KeePassXC - Version 2.6.3
Revision: beae186
Distribution: AppImage

Qt 5.15.2
Debugging mode is disabled.

Operating system: GalliumOS 3.1
CPU architecture: x86_64
Kernel: linux 4.16.18-galliumos

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- libgcrypt 1.8.1

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: XFCE
Windowing System: X11

**Comment by droidmonkey** [comment]
#5935
