### ISSUE TITLE
Add default configuration for password generator

### ISSUE THREAD

**Issue by webafrancois** [keepassxreboot/keepassxc#6038]
## Summary
Actually, when a password must be changed, the password generation configuration, uses the same as the previous password : same length = same entropy).
When I want to change weak passwords, I need for every password to change manually the password generator length (like 32 letters-digits).
I suggest to add a default configuration in option to save or force the default configuration (password default length, letters, digits...).

## Examples
In Options Menu / Security, Add "Password Generator Options "
* default configuration : same screen as the password generator.
* force it every generation (or not, with a check box)

**Comment by droidmonkey** [comment]
This is better merged with #2628
