### ISSUE TITLE
Unexpected key filename extension

### ISSUE THREAD

**Issue by gyli** [keepassxreboot/keepassxc#6040]
## Overview
When generating a key file, the file name suffix is ".keyx;", ending with semicolon

## Steps to Reproduce
1. Create a new DB or change current DB security
2. Generate a new key file, input the file name
3. Check the generated key file, the file name suffix is "<name>.keyx;"

## Expected Behavior
The filename extension should be ".keyx" or ".key". Maybe better with separated options when generating the file?

## Actual Behavior
File name suffix is ".keyx;", ending with semicolon

## Context

KeePassXC - Version 2.6.3
Revision: beae186

Qt 5.15.1
Debugging mode is disabled.

Operating system: macOS 10.15
CPU architecture: x86_64
Kernel: darwin 19.6.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
- libgcrypt 1.8.6

Operating System: macOS

**Comment by retifrav** [comment]
I got the same issue just now on Mac OS 11.6.2 (x86_64) with KeePass XC 2.6.6. Should I create a new bugreport for it, or is it better to re-open this one?

One more detail, to delete this file I have to enter my system administrator password, even though KeePass XC was launched under a regular non-admin user.

**Comment by droidmonkey** [comment]
This is fixed already for the next version
