### ISSUE TITLE
MacOS Catalina 10.15 incompatible since 2.6.4

### ISSUE THREAD

**Issue by cy4n** [keepassxreboot/keepassxc#6041]
## Overview
as of todays update to 2.6.4 KeepassXC does not launch any more in MacOS Catalina
Shows popup:
![image](https://user-images.githubusercontent.com/1135762/106433875-0ef5bd80-6471-11eb-8198-ac41e8756a85.png)

## Steps to Reproduce
1. open keepassxc 2.6.4. in MacOS 10.15.7
2. 
3. 

## Expected Behavior
app starts.

## Actual Behavior
app cant start

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.6.4 (i guess, KeePassXC.app changet Feb 1, 2021
Revision: REVISION

Operating System: macOS

**Comment by phoerious** [comment]
Are you sure you have the correct version downloaded and not the arm64 build?

**Comment by cy4n** [comment]
i didnt actually download anything, it probably came with the update mechanism? :-O

**Comment by cy4n** [comment]
hey @phoerious nice catch, something went wrong with our company patch management, they are already fixing it for the non-arm macs. thank you

**Comment by phoerious** [comment]
We don't do any auto updates, we only notify you if there is one available. I just checked, the new version has the same deployment target set as the old one. If anything, it should be more compatible, because I also rebuilt all dependencies to have 10.13 as their target.

**Comment by Mandymoore680** [comment]
Thanks

**Comment by phoerious** [comment]
My guess would be they just grepped for `KeePassXC-*.dmg` and took the first file name in the list, which is `-arm64`. :-)
