### ISSUE TITLE
Cannot connect KeePassXC-browser

### ISSUE THREAD

**Issue by Stephan-P** [keepassxreboot/keepassxc#6042]
Upon return from 5 weeks offline and upgrading KPXC to v2.6.4 I find that browser integration with both Vivaldi and Edge browsers is failing. 

I've tried without success:
- Disable/enable browser integration in KPXC and restart KPXC
- Remove connected databases from KPXC-Browser and try to connect to KPXC
- Remove/reinstall KPXC-Browser extension from both browsers

In any case, the function "Connect" in KPXC-Browser does not cause any effect. It simply doesn't do a thing.

Is there a way to reset the browser integration and remove any possible remaining pieces of data that may now include stray pointers?

=================

KeePassXC - unknown
KeePassXC-Browser - 1.7.5
Operating system: Win64
Browser: Chrome/Chromium 88.0.4324.99

=================

KeePassXC - Versie 2.6.4
Revisie: 34a78f0

Qt 5.15.2
De foutopsporingsmodus is uitgeschakeld.

Besturingssysteem: Windows 10 Version 2009
CPU-architectuur: x86_64
Kernelversie: winnt 10.0.19042

Geactiveerde extensies:
- Auto-type
- Browserintegratie
- SSH-agent
- KeeShare (getekend en ongetekend delen)
- YubiKey

Cryptografische bibliotheken:
- libgcrypt 1.9.1-unknown

**Comment by droidmonkey** [comment]
Go to database settings in keepassxc (Database-> Settings) and click the browser integration category. Then clear out the encryption keys in there. You can also go to application settings and make sure the browsers are setup properly.

**Comment by F3000** [comment]
Have the same issue with the new Mac M1 version 2.6.4 

I'm using MS Edge and can't connect to the database .

I have tried the hint above but no success . 

Every time I click "connect" the browser extension says "key Exchange was not successful "

**Comment by floeschie** [comment]
> Have the same issue with the new Mac M1 version 2.6.4
> 
> I'm using MS Edge and can't connect to the database .
> 
> I have tried the hint above but no success .
> 
> Every time I click "connect" the browser extension says "key Exchange was not successful "

Same here, since I upgradet KeePassXC to version 2.6.4 via HomeBew this morning. As soon as the upgrade was done, none of my browsers (Chrome, Firefox) is able to connect to the database anymore.

- MacOS Big Sur
- Firefox 85.0
- Chrome Version 88.0.4324.96 (Official Build) (arm64)
- KeePassXC Chrome Browser Plugin 1.7.5

**Comment by droidmonkey** [comment]
For macOS you probably need to restart your browser or computer. New software causes all sorts of problems for macOS.

**Comment by floeschie** [comment]
> For macOS you probably need to restart your browser or computer. New software causes all sorts of problems for macOS. Their software security settings often cause random things to fail on upgrade without restarting.

Already did that... 🤷

**Comment by Stephan-P** [comment]
> Go to database settings in keepassxc (Database-> Settings) and click the browser integration category. Then clear out the encryption keys in there. 

That did the trick. Not immediately, though. I had to click the button "Connect" a couple of times before the connection was actually re-established.

**Comment by floeschie** [comment]
> For macOS you probably need to restart your browser or computer. New software causes all sorts of problems for macOS. Their software security settings often cause random things to fail on upgrade without restarting.

Not sure if this is related: When I try to run keepassxc-cli and keepassxc-proxy from the command line (Terminal), I get this error:

```
% cd /Applications/KeePassXC.app/Contents/MacOS

% ./keepassxc-cli 
dyld: Library not loaded: /opt/homebrew/opt/libgpg-error/lib/libgpg-error.0.dylib
  Referenced from: /Applications/KeePassXC.app/Contents/MacOS/./keepassxc-cli
  Reason: image not found
zsh: abort      ./keepassxc-cli

% ./keepassxc-proxy
dyld: Library not loaded: /opt/homebrew/opt/qt/lib/QtNetwork.framework/Versions/5/QtNetwork
  Referenced from: /Applications/KeePassXC.app/Contents/MacOS/./keepassxc-proxy
  Reason: image not found
zsh: abort      ./keepassxc-proxy
```

So I thought it might be an issue with the HomeBrew cask and removed it. Then I downloaded the latest stable DMG file for Apple Silicon from the website, but could not install because I got an error message "KeePassXC os damaged and cannot be opened".

So I assume something is broken within the MacOS build?

**Comment by droidmonkey** [comment]
Yah that's absolutely related

**Comment by phoerious** [comment]
Gosh, yet another reason why Homebrew moving everything from /usr/local to /opt/homebrew was a TERRIBLE idea.

**Comment by floeschie** [comment]
> Gosh, yet another reason why Homebrew moving everything from /usr/local to /opt/homebrew was a TERRIBLE idea.

I have no problem installing KeePassXC without HomeBrew, even though I prefer to install software this way. However, the DMG file seems to be broken as well:

![Bildschirmfoto 2021-02-01 um 15 59 10](https://user-images.githubusercontent.com/1119719/106475657-7843f380-64a6-11eb-934c-7e22a26c15d5.png)

**Comment by phoerious** [comment]
Please try redownloading the build from the website and see if it works for you: https://keepassxc.org/download/#mac

**Comment by duminduweera** [comment]
I've installed the v2.6.4-2 and this seems to fix the issue.

**Comment by F3000** [comment]
> > Gosh, yet another reason why Homebrew moving everything from /usr/local to /opt/homebrew was a TERRIBLE idea.
> 
> I have no problem installing KeePassXC without HomeBrew, even though I prefer to install software this way. However, the DMG file seems to be broken as well:
> 
> ![Bildschirmfoto 2021-02-01 um 15 59 10](https://user-images.githubusercontent.com/1119719/106475657-7843f380-64a6-11eb-934c-7e22a26c15d5.png)
> 
> SHA256 checksums match.

Workaround : mount the installer -> copy the program to desktop. -> copy it in program folder . 
I see this “bug” also in the last version

**Comment by F3000** [comment]
> I've installed the v2.6.4-2 and this seems to fix the issue.

Also the connection issue ?

**Comment by floeschie** [comment]
The issue is not fixed. Neither can I install the DMG file (v2.6.4-2) nor can I connect the browser plugin. Should I open a new issue?

**Comment by F3000** [comment]
> The issue is not fixed. Neither can I install the DMG file (v2.6.4-2) nor can I connect the browser plugin. Should I open a new issue?

Have you tried out my workaround ?

**Comment by floeschie** [comment]
No not yet. I wouldn't consider a workaround as a generic solution for this issue...

**Comment by phoerious** [comment]
We seem to be mixing things up here. 2.6.4-2 is for ARM Macs and fixed the rpath issue with the CLI and browser integration. For everything else, we need more information.

**Comment by floeschie** [comment]
> We seem to be mixing things up here. 2.6.4-2 is for ARM Macs and fixed the rpath issue with the CLI and browser integration. For everything else, we need more information.

I'm using a MacBookPro M1. Currently I don't have KeePassXC installed. So basically it's a fresh start.

- I cannot install KeePassXC via DMG (v2.6.4-2) because I get a warning (see https://github.com/keepassxreboot/keepassxc/issues/6042#issuecomment-770919885)
- I can install KeePassXC via `brew install keepassxc`, but this results in the behavior I described in https://github.com/keepassxreboot/keepassxc/issues/6042#issuecomment-770855906

Either way, I have no idea how to get KeePassXC Browser Integration running on my M1 Mac.

**Comment by phoerious** [comment]
Try a reboot and if it persists, try clearing extended file attributes from either the DMG or the installed application:

```
xattr -cr /Applications/KeePassXC.app
```

**Comment by floeschie** [comment]
> Try a reboot and if it persists, try clearing extended file attributes from either the DMG or the installed application:
> 
> ```
> xattr -cr /Applications/KeePassXC.app
> ```

OK, so here is what I did:

1. Removed any KeePassXC app from the system
2. Reboot
2. Download KeePassXC DMG v2.6.4-2 from the website
2. Mount the DMG (double click) - no drag'n'drop!
3. Open Terminal
4. Run the command @phoerious proposed in https://github.com/keepassxreboot/keepassxc/issues/6042#issuecomment-771494084: `xattr -cr /Volumes/KeePassXC/KeePassXC.app`
5. Head back to the Finder window that opens after double clicking on the DMG
6. Drag & drop KeePassXC on the Applications folder icon

Result: KeePass is installed and browser integration works again 👍 

Wondering what the `xattr` command changed? Was there something wrong on my machine specifically?

**Comment by phoerious** [comment]
Probably. It's normal for macOS or Chrome to add the com.apple.quarantine attribute, but that should only ask for confirmation before running an application.

**Comment by Saj5h7** [comment]
@phoerious @floeschie Solution worked, thank you.

**Comment by F3000** [comment]
Installed the new version (-2) in my MBA M1 and now the browser works again . Thanks
