### ISSUE TITLE
Running keepassxc-cli in console

### ISSUE THREAD

**Issue by abourree** [keepassxreboot/keepassxc#6046]
## Overview
I want to run keepassxc-cli on a Linux server in a console (no DISPLAY)

## Steps to Reproduce
1. `./KeePassXC-2.6.4-x86_64.AppImage cli --version`

## Expected Behavior
I expect that keypass-cli doesn't depend on Qt or other X library

## Actual Behavior
```
./KeePassXC-2.6.4-x86_64.AppImage cli --version
keepassxc-cli: /lib64/libstdc++.so.6: version \`CXXABI_1.3.9' not found (required by /tmp/.mount_KeePasetQdQO/usr/lib/libQt5Svg.so.5)
keepassxc-cli: /lib64/libstdc++.so.6: version \`CXXABI_1.3.9' not found (required by /tmp/.mount_KeePasetQdQO/usr/lib/libQt5Concurrent.so.5)
keepassxc-cli: /lib64/libstdc++.so.6: version \`CXXABI_1.3.9' not found (required by /tmp/.mount_KeePasetQdQO/usr/lib/libQt5Network.so.5)
keepassxc-cli: /lib64/libstdc++.so.6: version \`CXXABI_1.3.9' not found (required by /tmp/.mount_KeePasetQdQO/usr/lib/libQt5Widgets.so.5)
keepassxc-cli: /lib64/libstdc++.so.6: version \`CXXABI_1.3.9' not found (required by /tmp/.mount_KeePasetQdQO/usr/lib/libQt5Gui.so.5)
keepassxc-cli: /lib64/libstdc++.so.6: version \`CXXABI_1.3.9' not found (required by /tmp/.mount_KeePasetQdQO/usr/lib/libQt5DBus.so.5)
keepassxc-cli: /lib64/libstdc++.so.6: version \`GLIBCXX_3.4.21' not found (required by /tmp/.mount_KeePasetQdQO/usr/lib/libQt5Core.so.5)
keepassxc-cli: /lib64/libstdc++.so.6: version \`CXXABI_1.3.8' not found (required by /tmp/.mount_KeePasetQdQO/usr/lib/libQt5Core.so.5)
keepassxc-cli: /lib64/libstdc++.so.6: version \`CXXABI_1.3.9' not found (required by /tmp/.mount_KeePasetQdQO/usr/lib/libQt5Core.so.5)
keepassxc-cli: /lib64/libstdc++.so.6: version \`CXXABI_1.3.8' not found (required by /tmp/.mount_KeePasetQdQO/usr/lib/libicui18n.so.55)
keepassxc-cli: /lib64/libstdc++.so.6: version \`CXXABI_1.3.8' not found (required by /tmp/.mount_KeePasetQdQO/usr/lib/libicuuc.so.55)
```

## Context
I'm not root on the server and I like to use password from my KeePassXC database

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC-2.6.4-x86_64.AppImage
Revision: 2.6.4

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: tty
Windowing System: xterm

**Comment by phoerious** [comment]
Your server is probably some sort of RHEL or CentOS. The libstdc++ version is too old to run the AppImage. You can only compile a version yourself.

**Comment by abourree** [comment]
Thanks @phoerious 
Yes my system is CentOS Linux release 7.8.2003 which is old
I just find that Appimage must be compiled with a system not newer than target system to run it on.
I will compile myself and see

**Comment by phoerious** [comment]
We are already compiling on 16.04, which is going to be EOL soon. We cannot go any further back than that.
