### ISSUE TITLE
Unable to open PDF attachment ("Encountered a sharing violation ...")

### ISSUE THREAD

**Issue by Shredder** [keepassxreboot/keepassxc#6048]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

When trying to open a PDF attachment of an entry, the PDF viewer (Foxit Reader) loads up, but doesn't display the file, but a pop-up error message occurs about a "sharing violation". Saving to file (via the "Save" button), then opening in the same program works ok.

When using another PDF viewer than Foxit Reader (I tried Microsoft Edge and Sumatra PDF), the issue does not occur.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Save a PDF file as attachment to an entry in KeepassXC. (Mine is a single page and about 500 kB in size. It loads ok in my systems built-in PDF viewer.)
2. Save the entry.
3. Click on "Open" under the entry's "Advanced" tab to open the PDF file in the system's default PDF viewer (Foxit Reader in my case).

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

The PDF viewer should open and display the file.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

The PDF viewer (Foxit Reader) starts up and shows a pop-up with the message: "Encountered a sharing violation while accessing C:\Users\<username>\AppData\Local\Temp\sYKQpF.<filename>.pdf. Perhaps KeePassXC keeps the temporary file locked after writing it, and Foxit Reader has issues with that?

## Context
[NOTE]: # ( Give us any additional information you may have. )

When using another PDF viewer than Foxit Reader (I tried Microsoft Edge and Sumatra PDF), the issue does not occur.

Also, if I use "Save" instead of "Open" in KeepassXC to save the PDF file to a directory, then open this file (e.g., double-clicking on it in Windows Explorer), it loads up ok in the same PDF viewer.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.6.4
Revision: 34a78f0

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 10
Desktop Env: Windows 10
Windowing System: Windows 10

**Comment by droidmonkey** [comment]
#2400
