### ISSUE TITLE
SSH-Agent - "remove key from agent after" does not work OpenSSH / Pageant 2.6.4

### ISSUE THREAD

**Issue by DunklerPhoenix** [keepassxreboot/keepassxc#6051]
## Overview
I have an server entry in my database with an ed25519 key. 
The function "remove key from agent after" does not work. 
It doesn't matter if I use Pageant or OpenSSH.
There are some error messages, but the come only direct after unlocking the database.

Pageant: "Agent refused this identity"
![RLidt9mks9](https://user-images.githubusercontent.com/1261305/106523194-076dfd00-64e1-11eb-8413-a6a4dd93af8e.png)
OpenSSH: "Agent protocol error"
![1C7LRPUWdK](https://user-images.githubusercontent.com/1261305/106523191-06d56680-64e1-11eb-951b-584f1f6afaf3.png)

## Steps to Reproduce
1. create an database entry with ssh key (I use an ed25519 key)
2. enable autoadd + autoremove + remove key from agent after (60s for me)
3. lock database
4. unlock database 
5. see the error

## Expected Behavior
Keys get added minimum at one of both services

## Actual Behavior
Keys don't get added

## Context
KeePassXC - Version 2.6.4
Revision: 34a78f0

Qt 5.15.2
Debugging mode is disabled.

Operating system: Windows 10 Version 1909
CPU architecture: x86_64
Kernel: winnt 10.0.18363
OpenSSH Client: Windows 10 internal
Pageant: Release 0.71

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey <- That's a lie - I don't use it

Cryptographic libraries:
- libgcrypt 1.9.1-unknown

**Comment by Mephysto666** [comment]
Same for me with 

KeePassXC - Version 2.6.3
Revision: beae186

Qt 5.15.2
Debugging mode is disabled.

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 5.10.11-arch1-1

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- libgcrypt 1.9.1-unknown

Remove key from agent after (60s for me) not enabled for me.

Very kind regards.

**Comment by hifi** [comment]
The error that you get with Pageant shows the real reason that on Windows lifetime constraints are not supported, not even with OpenSSH as far as I know. We don't disable them in KeePassXC if some day one of them starts supporting them.

@Mephysto666 You may be hitting a 2.6.3 specific bug, can you try upgrading to 2.6.4?

**Comment by DunklerPhoenix** [comment]
Ah good to know, but it would be nice to add a litte information field to this function. 
Or ist it maybe possible to check the support of this function while enabling the setting?

**Comment by Mephysto666** [comment]
> The error that you get with Pageant shows the real reason that on Windows lifetime constraints are not supported, not even with OpenSSH as far as I know. We don't disable them in KeePassXC if some day one of them starts supporting them.
> 
> @Mephysto666 You may be hitting a 2.6.3 specific bug, can you try upgrading to 2.6.4?

Version 2.6.4 is still not in Arch repos at the moment, I will update as soon as possible.

**Comment by hifi** [comment]
> Ah good to know, but it would be nice to add a litte information field to this function.

We could at least add more information to the official documentation that this functionality is currently unsupported on Windows due to Pageant and OpenSSH for Windows.

> Or ist it maybe possible to check the support of this function while enabling the setting?

Technically the only way we could test this would be to generate a temporary key on-the-fly and try adding it to agent with different settings and I don't think it's worth adding that much code. I'd suggest getting in contact with the team that manages OpenSSH for Windows to add that functionality - Pageant is probably dead, though.

> I saw the info in the Pageant error message and I thought in this moment that OpenSSH must support it.

Upstream OpenSSH does support it but for some reason the official Microsoft builds don't have either of the functionalities enabled.

> Yesterday I was about 2h trying many different settings and key, because I didn't understand why the keys don't get added to the agents until I enables the auto-add :D )

You don't get the same message when you click the add button in the settings page?

**Comment by DunklerPhoenix** [comment]
> We could at least add more information to the official documentation that this functionality is currently unsupported on Windows due to Pageant and OpenSSH for Windows.

This would be great!

>  I don't think it's worth adding that much code

An information in the documentation is enough I think

> Upstream OpenSSH does support it 

Yeah another reason to kick out as many Windows internal services as possible :D

> You don't get the same message when you click the add button in the settings page?

I only get it while unlocking the database. 
Not while:
- STRG + H
- Rightclick -> Add Key
- saving the agent settings

**Comment by Mephysto666** [comment]
> The error that you get with Pageant shows the real reason that on Windows lifetime constraints are not supported, not even with OpenSSH as far as I know. We don't disable them in KeePassXC if some day one of them starts supporting them.
> 
> @Mephysto666 You may be hitting a 2.6.3 specific bug, can you try upgrading to 2.6.4?

After update to 2.6.4 issue are no longer present.

Thank you very much.

Meph

**Comment by droidmonkey** [comment]
still an issue @hifi ?

**Comment by hifi** [comment]
We have updated the FAQ thanks to a contributor so I think if someone still has issues with 2.7 that isn't covered by our FAQ we just update it instead. Closing, thanks all!
