### ISSUE TITLE
1Password OpVault import error

### ISSUE THREAD

**Issue by Tonimara** [keepassxreboot/keepassxc#6052]
## Overview
Import of *.opvault file error message "Read Database did not produce an instance
Unable to decode masterKey: Malformed OpData01 due to a failed HMAC"

## Steps to Reproduce
1.  1Password6 or 1Password7 on MacOS BigSur: used Sync function into folder to produce opvault file
2. use import function of keepassxc to import
3. no problem so select the opvault file
4. error message after entering of the master key
"Read Database did not produce an instance
Unable to decode masterKey: Malformed OpData01 due to a failed HMAC"

[NOTE]:
KeePassXC - 2.6.4
Revision: 34a78f0
KeePassXC - Version 2.6.4
Revision: 34a78f0

Qt 5.15.2
Diagnosemodus ist deaktiviert.
Betriebssystem: macOS 11.1
CPU-Architektur: x86_64
Kernel: darwin 20.2.0
Aktivierte Erweiterungen:
- Auto-Type
- Browser-Integration
- SSH-Agent
- KeeShare (bestätigtes und unbestätigtes Teilen)
- YubiKey
- TouchID
Kryptographische Bibliotheken:
- libgcrypt 1.9.1
![Bild 02 02 21](https://user-images.githubusercontent.com/48173130/106567556-4c6e4f80-6532-11eb-9c7a-f9bd717ce9ec.jpg)

**Comment by Tonimara** [comment]
Solved the problem by changing the password in 1Password7 - I tried a simple alpha-numeric password, and the import worked fine. Hope that helps others with the same problem.

**Comment by MPC7500** [comment]
Hello,

I am opening the ticket again. I think I found the bug (if it is a bug at all).

When you create the OpenVault folder with 1Password it is called <1password.openvault>.

Then when you import it, the error message appears as above.

I have changed this folder name to <.openvault>.

After that everything worked as expected.

**Comment by droidmonkey** [comment]
This is a known problem on macos and we can't do much about it. It will work if you uninstall one password because it deregisters the custom handling of the folder.

**Comment by zeezw1** [comment]
> This is a known problem on macos and we can't do much about it. It will work if you uninstall one password because it deregisters the custom handling of the folder.

I have the same problem on Windows 10
