### ISSUE TITLE
AutoType from keyboard does not work

### ISSUE THREAD

**Issue by jaycarlinux** [keepassxreboot/keepassxc#6056]
## Overview
Applimage Version 2.6.4 (Linux) on 2 PCs. Auto-type shortcut from keyboard does not populate the user-id/password fields. Using the auto-type from the (keyboard) icon lines is okay. Further- when the Tools-Settings-Auto-type-Global Auto-type shortcut: is removed. CTL+SHFT+V is retyped, corrects the issue only for that session.
## Steps to Reproduce
1. Open KeepassXC highlight selected line keyboard CTL+SHFT+U 
2. move cursor to user-id field, back to Keepassxc window keyboard CTL+SHFT+V

## Expected Behavior
user-id & password fields are populated and URL opens

## Actual Behavior
Nothing, KeepassXC screen remains in front

## Context
[NOTE]: # ( Give us any additional information you may have. )

[KeePassXC - Version 2.6.4
Revision: 34a78f0
Distribution: AppImage

Qt 5.15.2
Debugging mode is disabled.

Operating system: Linux Mint 20.1
CPU architecture: x86_64
Kernel: linux 5.8.0-29-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- libgcrypt 1.8.1

Operating System: Linux
Desktop Env: Cinnamon
windowing system: X11

**Comment by droidmonkey** [comment]
Are you setting your global autotype shortcut to Ctrl+Shift+V? Don't do that.

**Comment by jaycarlinux** [comment]
ok I won't do that anymore. How do I solve my issue with the built in autotype failure?

**Comment by droidmonkey** [comment]
Can you please describe your problem in a different way? It is hard to understand what it is from your original post.

**Comment by jaycarlinux** [comment]
Jonathan.Thanks in advance for helping with this issue.
Open Keepassxc 2.6.4 (applimage) enter password, database displays, select item to open, ALT+SHFT+Uopens browser, place cursor in user-id field, ALT+TAB to bring KeepassXC in top window, ALT+SHFT+Vfrom keyboard nothing happens.But if I select the keyboard icon (the perform auto-type icon) the browser becomes the top window,the user-id and password field are populated and the URL opens. (normal and expected result)I prefer to keyboard the ALT+SHFT+V rather than selecting the icon with the mouse.I do not use browser integration.  Further, just upgraded to 2.6.4, this issue was not present in2.6.2.or 2.6.3
Thanks again


    On Tuesday, February 2, 2021, 08:23:52 PM EST, Jonathan White <notifications@github.com> wrote:  
 
 


Can you please describe your problem in a different way? It is hard to understand what it is from your original post.

**Comment by droidmonkey** [comment]
The shortcut to perform "entry level autotype" is Ctrl+Shift+V. Not Alt..

**Comment by jaycarlinux** [comment]
Jonathon
Obviously your correct. That's my typo, CTL+SHFT+V does not
Execute auto-type
Thanks
Jay

**Comment by jaycarlinux** [comment]
I have corrected this issue, the settings>general Autotype tab was populated
with CTL+SHFT+V, as soon as I deleted the entry, leaving it blank/empty all
returned to normal.
Thanks
