### ISSUE TITLE
Windows: window requesting credentials freezes; crash on exit

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [keepassxreboot/keepassxc#6057]
## Overview

After entering my master password into the window that asks for it, that window becomes unresponsive, such that all that can be done with it, is to close it. After closing it, exiting KeePassXC via the system tray produces this:

![image](https://user-images.githubusercontent.com/47056543/106668546-4b750680-65a2-11eb-8c47-0c83122f446a.png)

## Steps to Reproduce
The problem is intermittent. When it occurs, it occurs thusly:
1.  Launch KeePassXC to system tray.
2.  Invoke KeePassXC with a keyboard shortcut, when using a web browser (namely, Firefox).
3. Try to close the application (using its tray menu) after the freeze occasioned by 3.

## Expected Behavior
No freeze, no crash.

## Actual Behavior
See above.

## Context

KeePassXC - Version 2.6.2
Revision: e9b9582

Qt 5.15.1
Debugging mode is disabled.

Operating system: Windows 10 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.19042

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.6

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 10, 2009.

**Comment by droidmonkey** [comment]
Update your keepassxc

**Comment by LinuxOnTheDesktop** [comment]
OK, though, having found the relevant changelogs, nothing in them suggests that the problem at issue has been fixed. And you should consider augmenting [your documents page](https://keepassxc.org/docs/) with a link to changelogs.

**Comment by droidmonkey** [comment]
If you reproduce it on the latest version we'll talk

**Comment by LinuxOnTheDesktop** [comment]
The problem _does_ occur on KeepassXC 2.6.4.

**Comment by droidmonkey** [comment]
I'll need a stack trace to do anything. You can run a snapshot build https://snapshot.keepassxc.org or build in debug.

**Comment by LinuxOnTheDesktop** [comment]
Tell me which build to use.

I presume that I must await the problem before capturing the trace.

I need instructions on how to generate and submit the trace.

Note: my tone would be warmer were yours to be so.

**Comment by droidmonkey** [comment]
Here is how you can get crash dumps: https://docs.microsoft.com/en-us/windows/win32/wer/collecting-user-mode-dumps

Any snapshot version will work, I recommend using the latest. The snapshots track develop branch so they are very different from 2.6.4, but if it doesn't crash in develop then I'd consider the problem fixed.

**Comment by droidmonkey** [comment]
@LinuxOnTheDesktop did you reproduce this issue?

**Comment by succeedmr123** [comment]
@droidmonkey  @LinuxOnTheDesktop 

> 
> 
> The problem _does_ occur on KeepassXC 2.6.4.

Team, confirming behaviour on my production machine as well in more than few occasion, as described by @LinuxOnTheDesktop  (flaky behaviour)

(In my use case,  the window with error pops out rarely only as I run production environment and, understandably, normally am not in a position to wait loong 'til seemingly frozen login procedure throws out an error (instead of the expected: usual swift unlock)).

Additional environment remarks - it happens most often when it is already started but was unlocked-locked many times and locked again, windows was put to sleep and back (no memory corruption - checked with memtest) - in other words - production system regular operation.

I see the instructions to send the snapshot - when I will have idle time what I can offer is to run some test database in lock&unlock cycles and dump a snapshot when it freeze.

**Comment by LinuxOnTheDesktop** [comment]
I have some testing. In that testing - and indeed for a while before that, I think - KeePassXC does not crash but the credentials window does freeze after I have entered my password.

Here is what my testing discovered.

1. _A new database does not hang_. If I use as my active database an entirely new database, containing only one (newly created) entry, then there is no hang.
2. _A file-coped database hangs_. If I use my file manager to copy my existing (old) database to a new file, and then use that new file as my database, the hang occurs.
3. _Changing the encryption does not prevent the hang_. If I change the encryption settings on my existing database - for, I found that the existing settings were far from what are currently the defaults - then that does not help either (though of course I could not try every possible combination of encryption settings).

Is there some sort of debugging that I can turn on and that might help us see what the problem is?

**Comment by droidmonkey** [comment]
Now that 2.7.0 beta is out you should try to reproduce on there. I'm closing this until an actual reproduction method is determined.

**Comment by LinuxOnTheDesktop** [comment]
The bad news: the problem occurs on the beta.

The good news: perhaps we have a clue - there were two password boxes, as in [this other bug report (2677](https://github.com/keepassxreboot/keepassxc/issues/2677)).

**Comment by droidmonkey** [comment]
That is expected.  this is absolutely something unique with your database. It would be great to narrow that down

**Comment by LinuxOnTheDesktop** [comment]
> That is expected. this is absolutely something unique with your database. 

I am sorry, but _what_ is expected? The simultaneous showing of two password boxes?

**Comment by droidmonkey** [comment]
Yes
