### ISSUE TITLE
v2.6.4: Tray icon option "Monochrome (dark)" has disappeared

### ISSUE THREAD

**Issue by TheWirv** [keepassxreboot/keepassxc#6058]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
Hi, as the title suggests, since the most recent update, the "Monochrome (dark)" option for the tray icon type has disappeared. I assume this is connected to the new adaptation to dark/light OS themes feature. As you can see in the second image, it also (correctly, as per the setting at least) shows the light icon, although my Windows is set to dark mode.

![tray-icon](https://user-images.githubusercontent.com/4397989/106672721-d0ffb300-65b0-11eb-8087-c1c9035724e8.png)
![tray-icon2](https://user-images.githubusercontent.com/4397989/106672675-b75e6b80-65b0-11eb-8bf2-cb23bff9c94a.png)

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Upgrade to v2.6.4
2. Check Settings > General

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Adapt the tray icon to the OS theme as well.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
The "Monochrome (dark)" option has just disappeared.

## Context
[NOTE]: # ( Give us any additional information you may have. )
See the top.

## Debug info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.4
Revision: 34a78f0

Qt 5.15.2
Debugging mode is disabled.

Operating system: Windows 10 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.19042

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
- libgcrypt 1.9.1-unknown

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 10; most recent updates

**Comment by droidmonkey** [comment]
I'm not sure why you want a dark icon on a dark Taskbar. Please explain.

**Comment by phoerious** [comment]
Yeah, this is an intentional change. Leaving the selection between dark and light to the user was a crutch that was never supposed to stay in the application forever.

**Comment by TheWirv** [comment]
Damn, gyus. Now it has dawned on me. This does makes sense, sorry. I actually thought "Monochrome (dark)" is the icon for a dark theme, and not the _dark icon for a light theme_. But that makes sense, as I said.

I guess, I just liked the "Monochrome (dark)" icon better, and that's why I miss it. I thought it was really cool that it was actually monochrome in the sense that it was plain black when the db was locked and white when it was open. It kind of fit better into the whole "flat design" paradigm, in contract to the icon in the screenshot at the top. I don't know, it's just preference.

Still, thanks for bearing with me, and the clarification. 😅

**Comment by phoerious** [comment]
I doubt that you liked it better on your dark task bar, because it would have been almost entirely invisible. That said, the icons haven't changed and are as flat as pancake. We just don't burden the user anymore with picking the correct one. If you like to be burdened, switch over to Linux, we haven't patched it out there yet.

**Comment by TheWirv** [comment]
Not to start a redundant discussion here, but you "doubt that I liked it better"? Why? I said, I liked it better, meaning just that: I liked it better. That's a personal opinion, there shouldn't be any doubt about that. Granted, the icon _was_ indeed barely visible when the database was locked, but that's rarely the case anyway on my personal PC. Yet, somehow I liked the design of that icon more than this one.

And no, I'm not gonna switch to Linux. But thanks for caring about me potentially carrying heavy burdens while going through this world.

**Comment by phoerious** [comment]
Monochrome (dark) was always dark and barely visible, no matter the state of your application.

**Comment by TheWirv** [comment]
Huh, interesting take...

| ![dark_unlocked](https://user-images.githubusercontent.com/4397989/106727878-3339d180-660c-11eb-8723-24de1cdc0801.png) | ![dark_locked](https://user-images.githubusercontent.com/4397989/106727886-359c2b80-660c-11eb-8577-56cbb7bf815f.png) | ![light_unlocked](https://user-images.githubusercontent.com/4397989/106727892-3765ef00-660c-11eb-9eb2-2e29262171ac.png) | ![light_locked](https://user-images.githubusercontent.com/4397989/106727897-392fb280-660c-11eb-98e8-e72f14b87ff9.png) |
| :----------: | :----------: | :----------: | :----------: |
| Monochrome (dark); unlocked | Monochrome (dark); locked | Monochrome (light); unlocked | Monochrome (light); locked |

As I said, in my personal opinion the "Monochrome (dark)" icon looks way cooler, but who am I to judge.

**Comment by phoerious** [comment]
You have some buggy behaviour on your system. The first icon got is a black icon just like the second that got inverted somehow.

**Comment by TheWirv** [comment]
I mean, if you say so. You wrote the thing, not me; and I suppose you know it in and out, and that every new release is tested thouroughly on every supported system. So I guess it surely might be my system's fault, yeah.
