### ISSUE TITLE
Search Ctrl+f stopped working in 2.6.4

### ISSUE THREAD

**Issue by mhow2** [keepassxreboot/keepassxc#6061]
## Overview
I cannot search with Ctrl+F anymore

## Steps to Reproduce
Open a database and hit Ctrl+F

## Expected Behavior
A search text area appears

## Actual Behavior
Nothing happen at all

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.4
Revision: 34a78f0

Qt 5.12.8
Debugging mode is disabled.

Operating system: Ubuntu 20.04.2 LTS
CPU architecture: x86_64
Kernel: linux 5.8.0-41-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- libgcrypt 1.8.5

[NOTE]: # ( Pick choices based on your environment )
Operating System: GNU/Linux
Desktop Env: Gnome
Windowing System: X11

**Comment by mhow2** [comment]
Tried with `UBUNTU_MENUPROXY='' keepassxc` with no more success.

**Comment by droidmonkey** [comment]
Make sure the window is wide enough to show the search bar.

**Comment by mhow2** [comment]
@droidmonkey : I could propose a PR to add this to the FAQ. Could you tell me which file I should modify to update https://keepassxc.org/docs/#faq-ubuntushortcuts ?

**Comment by droidmonkey** [comment]
You could add a note it the search section of https://github.com/keepassxreboot/keepassxc/blob/develop/docs/topics/DatabaseOperations.adoc

**Comment by mhow2** [comment]
Is it the best place ? BTW I face the issue when I changed the UI settings for buttons to "Text only".

**Comment by droidmonkey** [comment]
Yes we know, adding any text to the toolbar icons causing the search bar to go into overflow. There is an issue tracking support for a detached search bar. I don't think we need documentation for this, it doesn't come up often and people rarely read any of it.
