### ISSUE TITLE
Entering letters with accents using compose key for password not working if password is hidden

### ISSUE THREAD

**Issue by GC-repeat** [keepassxreboot/keepassxc#6062]
## Overview
Entering a letter with an accent using compose key ("Ralt + accent + letter" in my case) for the database password or entering a custom entry password does not work if the password is hidden. It does work after pressing "Toggle password" but usually on the second try.

## Steps to Reproduce
1. Open database or create new entry
2. Enter an accented letter using compose key for example "á" as "Ralt + ' + a"
3. Toggling password here shows "'a" instead of "á"
4. While password is shown, repeat step 2. 
5. If step 4 resulted in "'a" repeat step 2 again and "á" should be obtained.

## Expected Behavior
Entering a letter with an accent using compose key should work either password is shown or hidden and on the first try.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
When the password is hidden using compose key to enter a letter with accent outputs the accent then the letter instead of the letter with accent.

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.1
Revision: 9a35bba

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (only unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.5

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: Regolith Desktop
Windowing System: X11

**Comment by droidmonkey** [comment]
Qt bug, duplicate
