### ISSUE TITLE
Search does not find groups

### ISSUE THREAD

**Issue by hubgitti** [keepassxreboot/keepassxc#6063]
## Overview
On searching groups are not found

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Type a keyword in the search box
2. Groups with that name are not found
3. 

## Expected Behavior
Groups having the name of the search key word should be found

## Actual Behavior
Groups having the name of the search key word are not found

KeePassXC - 2.6.2
Revision: e9b9582

Operating System:Debian Linux
Desktop Env: Gnome
Windowing System: Wayland

**Comment by phoerious** [comment]
Prefix your search query with `group:`.

**Comment by thomas-mc-work** [comment]
Is there a reason to have a separate prefix for group search? My use case is often "just search for that string, wheresoever". The "original" KeePass shows the same behavior.

**Comment by tredondo** [comment]
> Is there a reason to have a separate prefix for group search?

I don't see one. I think groups and attributes should be searched by default: #4696

A bigger problem is that it's impossible to search in group notes. Prefixing the query with `group:` doesn't help. #7165
