### ISSUE TITLE
TOTP QR code does not use defined issuer

### ISSUE THREAD

**Issue by rossifw** [keepassxreboot/keepassxc#6066]
## Overview
[TIP]: # (DO NOT include screenshots of your current database!)
[NOTE]: # (Give a BRIEF summary about your problem)
The option "Show QR Code" does not show the configured Issuer

## Steps to Reproduce
[NOTE]: # (Provide a simple set of steps to reproduce this bug.)
1. Create a new entry
![image](https://user-images.githubusercontent.com/11152752/106791075-385e4700-6633-11eb-8d05-e9671571d60b.png)
![image](https://user-images.githubusercontent.com/11152752/106791169-575cd900-6633-11eb-8da6-3547182b96c8.png)
![image](https://user-images.githubusercontent.com/11152752/106791217-66438b80-6633-11eb-9774-a35070215fdf.png)
>OTP Test ```otpauth://totp/Twitter:Teste?secret=ABSWY3DPEHPK3PXP&period=30&digits=6&issuer=Twitter``` 

2. Display QR Code
![image](https://user-images.githubusercontent.com/11152752/106791807-2b8e2300-6634-11eb-9639-b2af8de4dbea.png)
![image](https://user-images.githubusercontent.com/11152752/106791996-655f2980-6634-11eb-96d0-c98ace5e5302.png)
> QR code ```otpauth://totp/KeePassXC:teste?secret=ABSWY3DPEHPK3PXP&period=30&digits=6&issuer=KeePassXC```

## Expected Behavior
[NOTE]: # (Tell us what you expected to happen)
The same value as the OTP key was expected

## Actual Behavior
[NOTE]: # (Tell us what actually happens)
The string has been changed
```
otpauth://totp/Twitter:Teste?secret=ABSWY3DPEHPK3PXP&period=30&digits=6&issuer=Twitter
otpauth://totp/KeePassXC:teste?secret=ABSWY3DPEHPK3PXP&period=30&digits=6&issuer=KeePassXC
```

[NOTE]: # (Paste debug info from Help → About here)
KeePassXC - VERSION
Revision: REVISION

```
KeePassXC - Versão 2.6.4
Revisão: 34a78f0

Qt 5.15.2
Modo de debug desativado.

Sistema operacional: Windows 10 Version 2009
Arquitetura da CPU: x86_64
Kernel: winnt 10.0.19042

Extensões habilitadas:
- Auto-Digitar
- Integração com o Navegador
- Agente SSH
- KeeShare (compartilhamento assinado e não assinado)
- YubiKey

Bibliotecas de criptografia:
- libgcrypt 1.9.1-unknown
```

[NOTE]: # (Pick choices based on your environment)
Operating System: **Windows** ~/ Linux / macOS~
~Desktop Env: Gnome / KDE / XFCE / Mate / Cinnamon~
~Windowing System: X11 / Wayland~

**Comment by droidmonkey** [comment]
You need to set the title of the entry to Twitter instead of it being blank.
