### ISSUE TITLE
Make "email" a new default value for new entrys and custom default values

### ISSUE THREAD

**Issue by Agglutinator** [keepassxreboot/keepassxc#6067]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
There should be default value for entrys with the name "email".
Since you will need an email for allmost all online registrations this a necessary value for most entries.

In general there should be a option to create new default values so you dont have to create them again every time

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )
I want to make a new entry in KeePassXC for a random website.
There are existing default values named "title, username, passwort, url and notes"
There is no value for email adresses. So I have to create a custom value for that each time i make a new entry.
This is annoying and takes extra steps. Since you need this value most of the times this should be default

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
When you add a new entry there are pre-existing values like "title, username, password, url and notes"
The obvious thing that is missing here is the value "email"
For 99% of entries i want to put a email for registration. Why is this not a default value?
Instead i have to put a custom value tag each time i make a new entry.

It should behave like the password manager "Enpass".
There is a standard value called "E-mail" and you can easily enter other custom values for the entry

**Comment by droidmonkey** [comment]
This will be implemented with #863
