### ISSUE TITLE
keepassx: Cant change keyboard layout after i accidently try to autotype greek

### ISSUE THREAD

**Issue by vjbyrmtd** [keepassxreboot/keepassxc#607]
## Expected Behavior
I expected that the keyboard shortcat for layout would work

## Current Behavior
Couldnt change layout using the keyboard shortcut after using autotype

## Steps to Reproduce (for bugs)
1.I open my computer. 
2.I tried to login using autotype 
3.I forgot that at the time i tried the autotype combination i had the greek layout
4.Keepassx enter the password and login with greek characters.
5.When i realized that i tried to change the layout but it didnt change.(using the keyboard shortcat)
6.It happens everytime i follow the upper sequence

## Your Environment

* KeePassXC version/commit used: (can be found under Help -> About)
* Qt version (e.g. Qt 5.3): 5.7.1
* Compiler (e.g. Clang++3.6.0): gcc 6.3.0-4
* Operating System and version: Debian testing (stretch)

**Comment by TheZ3ro** [comment]
@vjbyrmtd why did you closed this? Did you solve it?
