### ISSUE TITLE
[feature_request] Customizable TOTP field names like KeeTrayTOTP in KeePass

### ISSUE THREAD

**Issue by tty7tyil** [keepassxreboot/keepassxc#6071]
## Summary
KeeTrayTOTP in KeePass has the ability to use custom field names for totp seed and specifications, other clients won’t recognize the customized fields.  Extend the settings to let the user specify these field names should do the job.

## Context
Extended description: Kunzisoft/KeePassDX#886

**Comment by droidmonkey** [comment]
We won't be implementing any more totp fields besides what exists currently.

**Comment by tty7tyil** [comment]
Thanks, that make sense.  KeeTrayTOTP/KeeTrayTOTP#110

**Comment by tty7tyil** [comment]
> 
> 
> We won't be implementing any more totp fields besides what exists currently. KeeTray can standardize on their end instead of inventing a new standard.

In fact KeeTray just inherited this from the old TrayTOTP.
