### ISSUE TITLE
Database is damaged everytime on iCloud

### ISSUE THREAD

**Issue by Fragden** [keepassxreboot/keepassxc#6072]
Hallo,

I have the following issue:

> I export the passwords from Firefox into a csv-file
> Create new database in KeePass XC by importing the csv-file
> For a while I can use the database.
> Then the main database file disappears and several files with different extensions are created (like: database.kdbx.GOxkHe, database.kdbx.mQmmDC, etc.)

I though that they are temporary files and if I close the programm, they would disappear and I could see my main database file. But it is not the case. they remain there and I cannot open the database anymore. 

Can anybody help me please? 

Cheers
Rabon

**Comment by phoerious** [comment]
Go to settings and disabled safe saving.

**Comment by Fragden** [comment]
Thank you very much for the quick answer. It seems to be the solution.
