### ISSUE TITLE
Add G and 6 to the list of look-alike characters

### ISSUE THREAD

**Issue by adriandelgado** [keepassxreboot/keepassxc#6075]
The password generator has a very useful feature: Exclude look-alike characters

Currently the list of excluded characters is: "01IlO|".

I always add G and 6 to the "Do not include" list because I've had to re-enter a password before due to the similarity. It would be great if they are excluded by default when selecting the checkbox.

**Comment by Thulium-Drake** [comment]
While you're at it, you might also include 8 and B then, some fonts _really_ make them look the same :-)

**Comment by adriandelgado** [comment]
Thanks @brandon-atkinson !
However, I think this doesn't update the UI or the translations.

**Comment by droidmonkey** [comment]
Translations are handled by transifex
