### ISSUE TITLE
Crash at Windows 10 unlock screen 

### ISSUE THREAD

**Issue by serial02** [keepassxreboot/keepassxc#6076]
Hello Keepassxc Team

After returning from the Windows 10 V20H2 rest screen, the following error message appears in the Keepassxc version 2.6.4 application.

![WhatsApp Image 2021-02-04 at 20 02 44](https://user-images.githubusercontent.com/32621790/106967142-61f79b00-6725-11eb-960d-74486cdbbc68.jpeg)

64-bit operating system
Installed Memory: 8.00 GB (usable: 7.74 GB)
Processor: Intel (R) Core (TM) i3 CPU 540 @ 3.07GHz 3.07 GHz

**Comment by droidmonkey** [comment]
Haven't ever seen that befofe

**Comment by serial02** [comment]
> Haven't ever seen that before

Not also (!) I thought it was a problem in the machine's memory, but I tested it with updated mentest and there are no errors. If you need any more information just let me know.

**Comment by droidmonkey** [comment]
Does this happen after sleep/hibernate or just when the screen is locked?

**Comment by serial02** [comment]
> Does this happen after sleep/hibernate or just when the screen is locked?

I believe it is after hibernation, because sometimes I return after a few hours and this situation happens.
I tap the mouse and this message appears shortly thereafter.

**Comment by Tremolo4** [comment]
I just had this issue for the first time. KeePassXC crashed with an access violation directly after resuming to lock screen from either hibernate or sleep (probably hibernate, but can't recall for sure). My PC regularly sleeps-then-hibernates with keepassxc open, but this is the first time it crashed.

![Screenshot 2021-04-22 204431](https://user-images.githubusercontent.com/818793/115769445-d993a880-a3ab-11eb-8d4b-fd482320cbcd.png)

**Comment by Tremolo4** [comment]
FWIW, since my last comment, I had a crash like this maybe 1 or 2 more times, so it seems to not be fixed. But I appreciate that it's practically impossible to debug and not a real problem due to its rareness.

**Comment by droidmonkey** [comment]
Correct, we can only really entertain these reports with a stack trace. Otherwise we just note that its out there and look for it ourselves. I have _never_ had KPXC crash on me on startup, unlock, unsleep, etc.

**Comment by Tremolo4** [comment]
Does a KeePassXC debug build log stack traces on its own or would I have to run it with a debugger attached?

**Comment by droidmonkey** [comment]
Yes a debug build will do memdmp for crashes so should be usable.

**Comment by Tremolo4** [comment]
Nice, thanks for the info! I'll build it when I have the time and will report if it ever crashes again.

**Comment by mgomersbach** [comment]
I also have this on windows 11, consistently and repeatedly after hibernate.
Not a memory error.  On different installs.

What do you need from me, or what do I need to deliver to not let this issue get discarded as "it's out there"?

**Comment by droidmonkey** [comment]
Try a snapshot build first: https://snapshot.keepassxc.org
