### ISSUE TITLE
Software Update dialog appears on primary desktop not desktop where KeepassXC is running

### ISSUE THREAD

**Issue by skypanther** [keepassxreboot/keepassxc#6078]
## Overview

MacOS Catalina (10.15.7) using multiple desktops (aka "Spaces")

The Software Update Is Available dialog always appears on Desktop 1 regardless of which screen KeePassXC is running on. This is often not obvious as the dialog can get lost behind other windows as you switch between apps. You go to KeePassXC and attempt to unlock the database and as soon as you click the window, you're switched back to desktop 1. But that doesn't bring the update dialog to the front.

## Steps to Reproduce

1. Switch to something other than Desktop 1 on your Mac
2. Open and older versionn of KeePassXC.
3. Wait for whatever delay there is before the Update Available dialog shows up. It will be on Desktop 1

## Expected Behavior

The dialog would appear on the same desktop where KeePassXC is running.

## Actual Behavior

The dialog shows up on Desktop 1

## Context

Note: By spaces, I mean Mac's virtual screens not an external monitor. Though, the bug also happens if you have multiple spaces on an external monitor. Regardless of physical monitors, the update dialog appears on the primary desktop, "Desktop 1", wherever that virtual desktop is located (internal or external monitor).

KeePassXC - Version 2.6.3 -- though this has been happening for quite some time across versions
Revision: beae186

Operating System: MacOS Catalina (10.15.7)

**Comment by phoerious** [comment]
Is this still an issue?

**Comment by skypanther** [comment]
I don't believe this is still an issue. I've received the update prompt on the correct screen on both my work and home Macs. Thanks!
