### ISSUE TITLE
Upgrading to v2.6.4 made SSH agent to throw error

### ISSUE THREAD

**Issue by sundowndev** [keepassxreboot/keepassxc#6082]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

I was using the v2.6.2 for a while now with the SSH agent. Today I decided to upgrade to v2.6.4, restarted the app then the ssh agent stopped working.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Use ssh plugin with v2.6.2
2. Upgrade to v2.6.4
3. Try to use ssh plugin again

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

SSH-agent to load private key from KeepassXC.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

Adding the key fails with the error "Error connecting to ssh agent" (translated from french) 

## Context
[NOTE]: # ( Give us any additional information you may have. )

I tried rollbacking to v2.6.2 but the error still persist. I also tried to disable/enable SSH plugin, and restarting my computer, it didn't solve the issue.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.6.4 (using Snap package)
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux Ubuntu LTS 20.04.2 x86_64
Desktop Env: Gnome

**Comment by droidmonkey** [comment]
You can't use ssh agent with the snap package

**Comment by sundowndev** [comment]
Alright, installing the Ubuntu pkg solved the issue ` sudo apt install keepassxc `.

Weird thing is I've used SSH agent with the snap package for almost 6 months, and it stopped working from day to day.

**Comment by dazinator** [comment]
I had the same problem getting started on ubuntu.
I first read through the FAQ with respect to this feature, and couldn't see anything wrong, ssh-agent was running, all seemed legitimate. Further searching lead me here. So to confirm:

`sudo snap remove keepassxc`

followed by 

`sudo apt install keepassxc`

has resolved the issue, however it looks like a very different version of keepassxc that I am running this way - but it has all the features I am not too fussed :-)

If this is a known issue, it might be worth adding this to the FAQ: https://keepassxc.org/docs/#faq-ssh-agent-errors
