### ISSUE TITLE
TOTP Setup: invalid pin code

### ISSUE THREAD

**Issue by andim202** [keepassxreboot/keepassxc#6083]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

Hi! Recently I am having problems using TOTP in KeePassXC. I tried typing in the secret manually and copying it from the clipboard. Whenever I tried to setup TOTP, the provided pin code was invalid. To verify if the code may be correct, I rechecked with my Smartphone (KeePass2Android 1.08d-r5 is installed there) and the codes didn't match...

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Setup TOTP Authentication on some online account
2. Copy secret to KeePassXC and see the pin code
3. Compare pin code to another application (Google Authenticator or similar)

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

Am I thinking wrong, or should all pin codes match ? No matter which device it should be the same code, right?

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

All codes from KeePassXC differ from the ones in Google Authenticator (or KeePass2Android)

## Context
[NOTE]: # ( Give us any additional information you may have. )

I already tried to download the KeePass Database from my smartphone and use it on my desktop (maybe the Database was corruputed) but the same result...  

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.6.4 and 2.6.3 and 2.6.2
Revision: 1

[NOTE]: # ( Pick choices based on your environment )
Operating System: ~~Windows~~/Linux/~~macOS~~
Desktop Env: ~~Gnome~~/~~KDE~~/~~XFCE~~/~~Mate~~/Cinnamon
Windowing System: X11/~~Wayland~~

**Comment by droidmonkey** [comment]
Make sure your computer time is synced to an online service. You are probably off by a minute or more.
