### ISSUE TITLE
Icons missing

### ISSUE THREAD

**Issue by popelop** [keepassxreboot/keepassxc#6084]
## Overview
looks exactly similar to #4963
![image](https://user-images.githubusercontent.com/74146255/107314731-9953a800-6a95-11eb-9efd-c83d1a9bf424.png)

##Context
KeepassXC 2.6.4 from the official PPA
Linux Mint 20.1 Cinnamon fresh install
Qt 5.12.8

**Comment by droidmonkey** [comment]
https://github.com/keepassxreboot/keepassxc/issues/4963#issuecomment-655584345
