### ISSUE TITLE
Auto-Type shortcut not working on Windows 10

### ISSUE THREAD

**Issue by ScottinCanada** [keepassxreboot/keepassxc#6086]
## Overview
KeePassXC 2.6.4 using Windows 10. The Auto-Type shortcut does not work properly. It just does a paste. The Auto-Type icon on the keyboard works correctly. If I right click a URL entry and click on the "Perform Auto-Type " context menu item, that also works fine. If I press Ctrl+Shift+V, all I get is a paste function from the last thing copied into the Windows clipboard.

## Steps to Reproduce
1. Open a website to the login screen.
2. Make sure the cursor is positioned in the login field.
3. Press Ctrl+Shift+V
4. The contents of the Windows clipboard appears in the login field, nothing more happens.

## Expected Behavior
Login with the correct user id and password. This does happen correctly when using other controls such as the toolbar icon or right click menu item.

## Actual Behavior
It merely does a Windows "paste" function.

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.4
Revision: 34a78f0
 
[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 10

**Comment by droidmonkey** [comment]
You need to configure your global autotype shortcut if you want to use the feature from outside the application. Explained in the documentation: https://keepassxc.org/docs/KeePassXC_UserGuide.html#_configure_global_auto_type

**Comment by ScottinCanada** [comment]
Thanks for the reply. I do have the global autotype set up for ALT+SHIFT+A, and that works fine. What I'm having a problem with is "Entry Level Autotype". Quoting from the documentation:

"You can perform Entry-Level Auto-Type from the toolbar icon (A), entry context menu (B), or by pressing Ctrl+Shift+V."

For me, the toolbar icon and the context menu work fine. It is the shortcut Ctrl+Shift+V that does not work at all.

Hope this helps to clarify.

**Comment by droidmonkey** [comment]
If you are using a third party clipboard tool it might be overriding the Ctrl+Shift+V shortcut. It works fine on all platforms.

**Comment by ScottinCanada** [comment]
OK, to my knowledge I am not using a third party tool, but maybe something is installed that I'm not aware of. If nobody else has the same complaint, it must be local to my machine. Thanks for getting back to me.
