### ISSUE TITLE
CLI should output passwords so there are not viewable but copyable

### ISSUE THREAD

**Issue by michaelkebe** [keepassxreboot/keepassxc#6088]
## Summary
The show command should print passwords e.g. red on red with the help of ANSI colors.
Copy Pasting is possible, but neither screenshots nor photos/videos will reveal the password.

## Examples
![keepassxc_cli_red_on_red](https://user-images.githubusercontent.com/74952/107364365-a4c9c200-6adb-11eb-934e-acb45e146faa.png)

**Comment by phoerious** [comment]
It will become visible when you select the password for copy-paste. I don't think we'll implement this.

**Comment by michaelkebe** [comment]
It depends on the Terminal and/or SSH Client.

I think it is better to be secure by default. I think it should be opt-out.

**Comment by droidmonkey** [comment]
I like the idea but not the color choice. Just use foreground on foreground.

**Comment by michaelkebe** [comment]
@droidmonkey That's right. But it should be clear, where to start and end the copy.

**Comment by phoerious** [comment]
Foreground/Foreground would make that clear.

**Comment by shemeshg** [comment]
I'm not security expect,
but then If someone will `tee -a| col -b` your session or just the executable, he would still see your password without you knowing it...

maybe alternative would be like in 
http://www.paulgriffiths.net/program/c/srcs/curhellosrc.html
with 
 mvaddstr(13, 33, "Hello, world password!");
getch();
 mvaddstr(13, 33, "                                       ");

This way `./myExeThatPrintPasswords|tee -a|col -b` 
would yield nothing.
Also Your terminal (iterm2/terminal) would keep nothing

Another option might be <dialog.h>, and after  dialog_ok("password", "your password")
clear the screen again, or overwrite it with other dialog

**Comment by droidmonkey** [comment]
If you don't want to have a risk of exposure don't use the cli tools. Obfuscation is generally a waste of time.

**Comment by danieldjewell** [comment]
I would tend to agree with @droidmonkey ... Security through Obfuscation (AKA security through obscurity) is quite often not really any security - a false sense of security. 

@shemeshg pointed out a relevant flaw... what about software that monitors memory or the clipboard? Forget key-loggers, the password is right in a shared memory buffer: the clipboard.

Passwords will *always* have this exact fatal flaw. I do not think it would be wise to spend resources developing a feature that provides a minimal-to-zero security benefit. 

@michaelkebe I do not mean to come across as harsh, your idea is good - on the surface. But given the many pre-existing methods that can be utilized to capture the password, I do not think that *visually* obscuring the password would offer much tangible benefit - unless someone walks by and takes a picture of your screen with a smartphone. (The password is presumably so complex that a human would have a difficult time memorizing it in a glance.)

If you're that concerned, the most secure thing we have in our arsenals is probably well implemented smart card authentication.

**Comment by droidmonkey** [comment]
We will not be implementing this.
