### ISSUE TITLE
Trigger autotype from command line

### ISSUE THREAD

**Issue by droidmonkey** [keepassxreboot/keepassxc#609]
## Feature request

KeePassXC should support a command line flag ```--autotype``` and login credentials as necessary to allow invoking an autotype command directly from a desktop global key combination.

e.g. in Gnome > Settings > Keyboard > Shortcuts, add Ctrl-Alt-A and bind it to
```
/usr/bin/keepassxc --autotype --keyfile mykeyfile
```
See original comment:
https://github.com/keepassxreboot/keepassxc/issues/99#issuecomment-273027934

This would utilize the new Single Instance behavior to automatically start or raise an instance.

## Context

This feature is meant to overcome autotype obstacles found in Wayland. It also allows the user to quickly access the necessary action with a global keyboard shortcut.

**Comment by arigit** [comment]
Chiming in - looking forward to this

**Comment by jeroen7s** [comment]
it would still need to find a way to detect the window title name and select the correct entry, right?

**Comment by TheZ3ro** [comment]
@jeroen7s yes, of course

**Comment by droidmonkey** [comment]
We will not be implementing this
