### ISSUE TITLE
Copy entries between databases

### ISSUE THREAD

**Issue by rmsppu** [keepassxreboot/keepassxc#6093]
## Summary
If a user has multiple databases open, allow copying (ie., "clone") between databases.

## Context
Use cases: One database is a subset of another (ie., I've got a database of system administration passwords, and the "network admin" db is a subset. I've got a database of personal passwords, but the database of "Streaming media sites and household automation" is a subset, shared with my wife).

In these cases, a new entry (ie., Cisco Nexus router, or Netflix) would be added to the primary database, then copied to the subset.

The databases themselves aren't linked and don't share passwords. Users of the subset would not necessarily have passwords to (or knowledge of) the superset db.

Having both DBs open at once in the GUI application both ensures that the person making the copy has the authority and eliminates the insecurity of exporting a database unencrypted then reimporting the data, and eliminates the potential errors in manually recreating an entry.

## Related To
This feature request may be merged with https://github.com/keepassxreboot/keepassxc/issues/5204

**Comment by droidmonkey** [comment]
Your use case is what KeeShare is all about.
 https://keepassxc.org/docs/KeePassXC_UserGuide.html#_database_sharing_with_keeshare
