### ISSUE TITLE
Enable selection of entries to export

### ISSUE THREAD

**Issue by rmsppu** [keepassxreboot/keepassxc#6094]
## Summary
Allow the selection of entries to export, rather than an entire database.

## Use Cases
A business or family member may keep a master database, distributing a subset to individuals. For example, an IT director may have a KeepassDB of all server, network switch, and database passwords, distributing only parts to different people.

## Examples
After selecting "Export", a checkbox would appear next to each DB folder and entry. Only selected entries (or "All") would be exported.

In the following example,  all of the "Household" and "Locks" entries, the password entry for HBO, and the entry for the MediaWiki WikiAdmin would be exported.

![Screenshot_20210209_175618](https://user-images.githubusercontent.com/4388288/107441547-6811c100-6b03-11eb-9502-5ca42f745e24.png)

**Comment by droidmonkey** [comment]
Duplicate
