### ISSUE TITLE
Switching active database when using two browser profiles causing disconnection

### ISSUE THREAD

**Issue by MathPlayer** [keepassxreboot/keepassxc#6095]
## Overview
  I have separate personal and work passwords and I cannot use them properly from two separate browser profiles of the same browser.
  This is either a bug with the app, with the browser extension or both.
   
## Steps to Reproduce
1. Create 2 browser profiles: `ProfilePersonal` and `ProfileWork`.
2. Install KeePassXC-browser extension on both profiles.
2. Create 2 databases in the KeePassXC app: `PasswordsPersonal` and `PasswordsWork`.
3. Connect the browser extension from `ProfilePersonal` to the `PasswordsPersonal` database.
4. Connect the browser extension from `ProfileWork` to the `PasswordsWork` database.
5. Open both databases in KeePassXC app.
5. Save `user`/`password` credentials for a website (for the sake of example`https://lichess.org/login`) in `PasswordsPersonal`.
6. Leave the active database tab in the KeePassXC app on `PasswordsWork`.
7. Using the `ProfilePersonal` profile in browser, navigate to `https://lichess.org/login`.

## Expected Behavior
KeePassXC-browser extension offers `user`/`password` as autocomplete login from `PasswordsPersonal`.

## Actual Behavior
KeePassXC-browser does not detect the connection to `PasswordsPersonal`.
Note: My gut feeling says the browser extension asks the app for DBs, but the app checks only for the active tab and not for all opened databases.

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.3
Revision: beae186

Qt 5.15.1
Debugging mode is disabled.

Operating system: macOS 10.15
CPU architecture: x86_64
Kernel: darwin 19.6.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
- libgcrypt 1.8.6

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS Catalina 10.15.7
Browser: Microsoft Edge 88.0.705.56

**Comment by droidmonkey** [comment]
This is by design. If you want to search all unlocked databases set that option in the browser settings to enabled.

**Comment by MathPlayer** [comment]
I enabled the setting and everything worked well instantly.
Yet... there is still a bug on it. With setting on, the problem still reproduces after coming back from sleep/restarts.

## Steps to Reproduce:
- Set up as in the first comment.
- Enable the aforementioned setting.
- Do restart or sleep/resume.
- Leave `DatabaseX` as active tab.
- Open a login website in `ProfileY`.

## Expected behavior:
- Autocomplete kicks in from `DatabaseY`.

## Actual behavior
- Browser extension in `ProfileY` does not detect any database.

**Comment by droidmonkey** [comment]
I don't follow the sequence above, X Y very confusing. Can you lay it out in screenshots or very explicit? Are both databases unlocked?

**Comment by MathPlayer** [comment]
Here is a recording summarizing all the above. Some notes:
- Top left is my personal browser profile, bottom left is my work browser profile. They are connected only to their corresponding database and with different names.
- Both databases are populated (e.g. have passwords in their `KeePassXC-Browser Passwords` group), yet I selected the root folder to not show any entries while recording. This does not impact the bug.
- The final part can also be done in the other profile with the same results.

https://user-images.githubusercontent.com/1119787/108175353-f50ada80-7100-11eb-9316-84b0fdec5f69.mov

**Comment by droidmonkey** [comment]
Got it! Will investigate that issue.

**Comment by varjolintu** [comment]
@MathPlayer Browser extension must be connected to both databases. Seems you haven't connected your WorkPasswords database to you personal browser profile. You'll have to do that if you want to use both Passwords and WorkPasswords databases from your personal profile. Have I understood this correctly?

**Comment by MathPlayer** [comment]
Why is it a must for browser extension in my personal profile to be connected to both databases?
The dropbox credentials are stored in the Passwords database, not in the WorkPasswords database.
FWIW the bug is about the fact that the setting to search in all databases is not really searching in all databases but only in the active (e.g. shown as active tab) one.

**Comment by varjolintu** [comment]
Searching from all databases means searching from all _connected_ databases. Otherwise it would be a security issue if you could get credentials from a database that is not even connected to the extension.

**Comment by MathPlayer** [comment]
I feel we're still not on the same page.
In the recording, the Passwords database is connected to the personal browser profile to top left.
The Passwords database has a password for Dropbox.
When the Password database is the active tab in the KeePassXC app, the browser extension from the personal profile detects a connection to the Passwords database and can get the password for autofill.
When the Password database is not the active tab in the KeePassXC app, the browser extension from the personal profile cannot detect it is connected to the Password database. This is what I think is not working as intended.

**Comment by varjolintu** [comment]
@MathPlayer Ah I see. Sorry for the confusion. This feature really needs an update.

**Comment by MathPlayer** [comment]
One extra detail: this issue also happens when using two different browsers (instead of two profiles of the same browser as reported initially)

**Comment by droidmonkey** [comment]
@varjolintu still a problem? I think we fixed this.

**Comment by varjolintu** [comment]
@droidmonkey Should be fixed yes.
