### ISSUE TITLE
MacOS dmg: gpg key expired warning

### ISSUE THREAD

**Issue by ninjacoda** [keepassxreboot/keepassxc#6096]
## Overview
I tried to verify the download of the MacOS dmg version of KeePassXC using gpg, as explained on https://keepassxc.org/verifying-signatures/. The signature seems correct, but I got a key expiration warning. (I assume gpg was complaining about the KeePassXC key, not mine...) The sha256 check for the dmg returns a match.

## Steps to Reproduce
```
$ gpg --verify KeePassXC-*.sig
gpg: die unterzeichneten Daten sind wohl in 'KeePassXC-2.6.4-x86_64.dmg'
gpg: Signatur vom Mo  1 Feb 01:37:47 2021 CET
gpg:                mittels RSA-Schlüssel C1E4CBA3AD78D3AFD894F9E0B7A66F03B59076A8
gpg: Korrekte Signatur von "KeePassXC Release <release@keepassxc.org>" [unbekannt]
gpg: Hinweis: Dieser Schlüssel ist verfallen!
Haupt-Fingerabdruck  = BF5A 669F 2272 CF43 24C1  FDA8 CFB4 C216 6397 D0D2
Unter-Fingerabdruck  = C1E4 CBA3 AD78 D3AF D894  F9E0 B7A6 6F03 B590 76A8
```

That translates to 
```
gpg: Correct signature for "KeePassXC Release <release@keepassxc.org>" [unknown]
gpg: Note: This key has expired!
```

I then tried to update the key (without really knowing how; I figured getting it again from the key server should do the trick):
```
$ gpg --keyserver keys.openpgp.org --recv-keys CFB4C2166397D0D2
gpg: Empfangen vom Schlüsselserver fehlgeschlagen: Network is unreachable
```

This translates to

```
gpg: Receiving from key server failed: Network is unreachable
```

## Expected Behavior
No key expired warning.
Successful import of key from server (or a warning that it already exists).

## Actual Behavior
Key expired warning.
Network is unreachable error.

## Context
The Mac is connected to the internet, and that connection is working fine.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.6.4

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS

**Comment by phoerious** [comment]
You have a network issue, nothing we can do. Run `gpg --refresh-keys` when you have sorted it out.

**Comment by ninjacoda** [comment]
That command didn't work, too - but the network issue comment kind of did help:

```
$ gpg --refresh-keys
<...>
gpg: Refresh vom Schlüsselserver fehlgeschlagen: Network is unreachable
```

```
gpg: Refersh from keyserver failed: Network is unreachable
```

Turns out that gpg may have an issue with [IPv6](https://github.com/rvm/rvm/issues/4215#issuecomment-435221616) (and at least for the keys.gnupg.net keyserver, [DNS issues](https://github.com/rvm/rvm/issues/4215#issuecomment-450057754)). Once I [configured dirmngr to use `standard-resolver`](https://github.com/rvm/rvm/issues/4215#issuecomment-504258908) and [restarted it](https://github.com/rvm/rvm/issues/4215#issuecomment-486609350), gpg was able to reach the servers again.

Leaving this here in case someone else runs into similar issues. :)
