### ISSUE TITLE
won't hide to tray at startup

### ISSUE THREAD

**Issue by Thomberger** [keepassxreboot/keepassxc#6099]
## Overview
After an automatic start of keepass xc after log in (with GNOME Tweaks), window will not hide to tray and only minimize even with settings correctly done. The behavior only shows up with automatic start, everything is correct with a manual start of keepass xc.

## Steps to Reproduce
1. Restart the computer with Keepass xc automatically starting after log in 
2. Connect database and try to close window (to hide it to tray)

## Expected Behavior
Window should hide and minimize to tray normally

## Actual Behavior
Window only minimize but don't hide to tray

# Debug Info
KeePassXC - Version 2.4.3
Revision: 5d6ef0c

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux Ubuntu 20.04.2 LTS
Desktop Env: Gnome
Windowing System: X11

**Comment by droidmonkey** [comment]
Need to update that has been fixed. We are on 2.6.4 now.
