### ISSUE TITLE
Hide/Show OTP 

### ISSUE THREAD

**Issue by gabeweb** [keepassxreboot/keepassxc#6100]
## Summary

Currently KeepassXC shows OTP codes while you have the preview of an element in question. When changing to another item, the view of the generated OTP code is deactivated again.

## Context

I propose an option to activate / deactivate the preview of the OTP codes, along with an animated indicator as a kind of "countdown". Likewise, a configurable column to show the OTP codes of the elements by folders (as in Keepass).

**Comment by droidmonkey** [comment]
The current preview/edit interface is going to be completely redone for the next version. We already have a TOTP column that when double clicked copies the current code to clipboard.
