### ISSUE TITLE
HTML non interpreted in the secret service tab

### ISSUE THREAD

**Issue by x0rld** [keepassxreboot/keepassxc#6102]
## Overview
there is the html tags when I go in secret service integration

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. setup gnome keyring or anything
2. go in parameter and "secret service"
3. the warning is not interpreted as html

## Expected Behavior
the text between the tags should have the html applied

## Actual Behavior
![image](https://user-images.githubusercontent.com/45242856/107617968-14ad8900-6c51-11eb-8820-b6dcd53c4b92.png)

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.4
Révision : 34a78f0

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: Gnome 3.38.3
Windowing System: X11

**Comment by droidmonkey** [comment]
This is a translation failure, needs to be fixed over in transifex. What language is that?

**Comment by phoerious** [comment]
It's French. I believe it's not really a problem with the translation, though: https://www.transifex.com/keepassxc/keepassxc/translate/#fr/keepassxc/291402725?q=translation%3Asecret+text%3Aservice

**Comment by droidmonkey** [comment]
The starting tag is broken, but this works fine for me on develop in English

**Comment by phoerious** [comment]
Qt's HTML/plaintext auto detection is pretty wonky at times. IIRC, a literal newline instead of a <br> tag is enough to switch to plaintext mode.

**Comment by droidmonkey** [comment]
Confirmed, this was an issue with the French translation.
