### ISSUE TITLE
How to export group?

### ISSUE THREAD

**Issue by wijde** [keepassxreboot/keepassxc#6103]
Can you please tell me how to export the group?

**Comment by droidmonkey** [comment]
https://keepassxc.org/docs/KeePassXC_UserGuide.html#_exporting_databases

To share a group:
https://keepassxc.org/docs/KeePassXC_UserGuide.html#_database_sharing_with_keeshare

**Comment by wijde** [comment]
I think it would be great if it would be great if there was an opportunity through the GUI to right-click to make group exports. I think this feature will be useful and useful to many. there is no information about what you can do simple exports without sharing with one click. if it can be implemented architecturally, it will be a very useful feature

**Comment by droidmonkey** [comment]
#1940
