### ISSUE TITLE
Move a record from one database to another

### ISSUE THREAD

**Issue by jurgenhaas** [keepassxreboot/keepassxc#6104]
## Summary

Was looking around but wasn't able to find anything related to this: when I have 2 databases opened in my client and want to move one of the items from one database to the other, I currently have to copy and paste each field individually. Is it possible to offer such a move (or copy) of a record from one to the other?

**Comment by droidmonkey** [comment]
Drag and drop.

**Comment by jurgenhaas** [comment]
Amazing, works like a charm.
