### ISSUE TITLE
error "settings need to be moved" is repeated but unclear what to do

### ISSUE THREAD

**Issue by andrewufrank** [keepassxreboot/keepassxc#6110]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # 
I receive repeatedly the message: 
```
Your KeePassXC-Browser settings need to be moved into the database settings.
This is necessary to maintain your current browser connections.
Would you like to migrate your existing settings now?
```

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. I say YES
2. the next error is
    `The active database does not contain an entry with KeePassHTTP attributes.`
3. Nothing happens after this. 
4. But the initial error is repeated next time the dabase is opened.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
I expect to get an information what needs to be done to correct the error (or no error message, if a correction is not required)

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
error is repeated each open db 

## Context
[NOTE]: # ( Give us any additional information you may have. )
I assume I have connect the first time the browser with a different database, which I do not open anymore.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.1
Revision: 9a35bba

Qt 5.14.2
Debugging mode is disabled.

Operating system: Ubuntu 20.10
CPU architecture: arm64
Kernel: linux 5.8.0-1015-raspi

Enabled extensions:
- Auto-Type
- Browser Integration -- with firefox
- SSH Agent -- not enabled
- KeeShare (only unsigned sharing) -- not enabled
- YubiKey  -- not used 
- Secret Service Integration
   i have a warning: Warning: Another secret service is running (PID: 1330, Executable: /usr/bin/gnome-keyring-daemon).
Please stop/remove it before re-enabling the Secret Service Integration.

Cryptographic libraries:
 libgcrypt 1.8.5

[NOTE]: # ( Pick choices based on your environment )
Operating System: linux ubuntu mate
Desktop Env: mate
Windowing System: X11

**Comment by droidmonkey** [comment]
Update to 2.6.4
