### ISSUE TITLE
Add `Ctrl+Enter` to confirm password generator

### ISSUE THREAD

**Issue by SeerLite** [keepassxreboot/keepassxc#6111]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )

Pressing the Enter key in the password generator dialog currently does nothing, while it could confirm the dialog and add it to the entry that's being edited (like clicking "Apply Password").

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
A workaround right now is to press Shift + Tab (to select Apply Password) and _then_ Enter, but that's not intuitive. Keyboard navigation would be a lot smoother with just having to press Enter.

**Comment by droidmonkey** [comment]
The keyboard shortcut to apply the password is `Ctrl+S`, this is intentionally not `Enter` to prevent accidently applying the password when you meant to do something else in the GUI. I suppose we could add `Ctrl+Enter` as a shortcut.

**Comment by SeerLite** [comment]
Woah, I didn't know about that one. I personally wouldn't mind not having a way to do it with `Enter` or `Ctrl+Enter`, I just wanted a quick way to do it. It's just that `Ctrl+S` wasn't documented anywhere (unless I missed it). Thanks a lot!
