### ISSUE TITLE
Dupes on saving via WebDav (in Nextcloud)

### ISSUE THREAD

**Issue by loeffelpan** [keepassxreboot/keepassxc#6112]
Don‘t if this can be related to KeePassXC, but I want to try. Please take look at https://github.com/nextcloud/ios/issues/1538 and see my issue.

There are dupes in iOS files app when using nextcloud app/integration and this is breaking KeePassium. KeePassium can be not faulty, because their file handling is due to iOS files app. Same thing happens _with KeePass Client as well_. But _not with other file types_ (e. g. TXT saved on nextcloud and changed with Notepad from Windows), which means that this couldn‘t ne related with nextcloud iOS app.
_Changing „safely save“ option in KeepassXC doesn’t change behaviour._

Any idea?
Could this be related to the way how KeePass database files are saved?

**Comment by droidmonkey** [comment]
This is because keepass and keepassxc always writes a new file instead of writing into the existing one. That prevents non-atomic saving problems. NextCloud should be filtering their recent files list by file pointers that actually exist. This is not a keepassxc problem.

**Comment by loeffelpan** [comment]
Thanks, I will go forward with the issue in nextcloud/ios.

Just for understanding: Isn‘t this what „deactivate safely save“ option is for? To avoid that a new file is written? But changing that option doesn‘t change behaviour.

**Comment by droidmonkey** [comment]
No, unsafe saves create a temporary file locally then move it in place after deleting the original file.

**Comment by loeffelpan** [comment]
@droidmonkey 
What about an option like in the original KeePass: "Use file transactions for writing databases" option in Tools → Options → tab Advanced.

With this option disabled I could workaround that (nextcloud) issue.

**Comment by droidmonkey** [comment]
I think you are referring to the "very unsafe save" option in keepass, that write directly to the existing file.

**Comment by loeffelpan** [comment]
Yes, are the plans to implement that in KeePassXC?

**Comment by droidmonkey** [comment]
I could consider it, especially if you are saving to cloud storage with version control.
