### ISSUE TITLE
Credit icons8.com in about window

### ISSUE THREAD

**Issue by digitalteg** [keepassxreboot/keepassxc#6115]
Expected to see credit given to icons8.com in about window

## Steps to Reproduce
1. Open Help/About

## Expected Behavior
Expected to see credit given to icons8.com for database icons included in keepassxc

## Actual Behavior
Did not see credit given to icons8.com for database icons included in keepassxc

## Context
https://github.com/keepassxreboot/keepassxc/pull/4699

Debug Info:
KeePassXC - Version 2.6.4
Revision: 34a78f0
Distribution: AppImage

Qt 5.15.2
Debugging mode is disabled.

Operating system: Devuan GNU/Linux 3 (beowulf)
CPU architecture: x86_64
Kernel: linux 4.19.0-12-amd64

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- libgcrypt 1.8.1

Operating System: Linux
Desktop Env: KDE
Windowing System: X11

**Comment by droidmonkey** [comment]
All icons were derived from https://github.com/icons8/flat-color-icons which requires no credits. Also a good number were subsequently modified by me or created by me from scratch.
