### ISSUE TITLE
`keepassxc-cli clip` problem pasting specific character

### ISSUE THREAD

**Issue by rpolve** [keepassxreboot/keepassxc#6119]
# version

5.10.15-arch1-1 x86_64 GNU/Linux
keepassxc 2.6.4-1
xclip 0.13-3

# problem

for any entry containing the pound sign **£** (hexa-decimal: A3), pasting from clipboard after having used `keepassxc-cli clip` outputs binary data instead of plain text.

# notes

- in the GUI, selecting the entry and pressing <Ctrl+C> does not produce the same issue
- autotype does not have any problem with **£**
- there might be other characters behaving similarly, I apologize if I haven't tried to find them

**Comment by droidmonkey** [comment]
Might this have something to do with the encoding used in your terminal? It could be us as well, just a thought.

**Comment by rpolve** [comment]
Does this answer your question Jonathan?

```
$ locale charmap
UTF-8
```

Also I'm not using it interactively (i.e. I'm not in the terminal when
this happens). Not sure this is relevant info though.

**Comment by droidmonkey** [comment]
This is a problem with the way we pass arguments to xclip, we use latin1() instead of utf8()...
