### ISSUE TITLE
 KeePassXC 2.6.4 crashes after I've entered my passphrase

### ISSUE THREAD

**Issue by ericxuo** [keepassxreboot/keepassxc#6120]
Hi,

I'm using the AppImage version 2.6.4 of KeePassXC.
It works very well except if I start the executable from an icon on my KDE desktop.
In other words, if I run :
./KeePassXC => it works.
If I double-click on an Icon on my KDE desktop, it fails **when I enter my passphrase** to open my database.
The error message I get is the following :
libgcc_s.so.1 must be installed for pthread_cancel to work

Note : the problem is the same if I double-click on the KeePassXC icon under Krusader.

I have no issue at all when I do the same with the AppImage version 2.6.2.

I've tried to compile from the source (and from the git repository) but it fails with : 
/home/xuo/Téléchargements/keepassxc/keepassxc-2.6.4/keepassxc/src/gui/MainWindow.cpp:1578:5: error: « TouchID » has not been declared
     TouchID::getInstance().reset();

I've removed the YubiKey from the compilation as I couldn't get "cmake .." to pass.

Do you have any idea to solve any of these issues ?

Regards.

Xuo.

Linux Mageia 7
X11
KDE

**Comment by droidmonkey** [comment]
Why does TouchID try to compile on your Linux machine? That is for macOS and guarded as such.

The first issue is interesting, it's almost like the working directory is all off when you launch from desktop shortcut. Where is the appimage actually stored?

**Comment by ericxuo** [comment]
Hi,

Thank you for your answer.
1) Here are the commands I've run :
git clone https://github.com/keepassxreboot/keepassxc.git
mkdir build
cd build
mkdir ../install
cmake -DWITH_XC_AUTOTYPE=ON -DWITH_XC_YUBIKEY=OFF -DWITH_XC_BROWSER=ON -DWITH_XC_NETWORKING=ON -DWITH_XC_SSHAGENT=ON -DWITH_XC_TOUCHID=ON -DWITH_XC_FDOSECRETS=ON -DWITH_XC_KEESHARE=ON -DWITH_XC_KEESHARE_SECURE=ON -DCMAKE_INSTALL_PREFIX=../install ..
make
Why It tries to compile TouchID on a linux machine ? I should probably set :  
-DWITH_XC_TOUCHID=OFF

2) The appImage is located in a directory (/mnt/Softs/bin) where : 
drwxr-xr-x  3 xuo users     4096 févr. 13 21:28 .
lrwxrwxrwx  1 xuo users       31 févr. 13 20:22 KeePassXC -> KeePassXC-2.6.4-x86_64.AppImage
-rwxr-xr-x  1 xuo users 34369576 déc.  22 15:53 KeePassXC-2.6.2-x86_64.AppImage
-rwxr-xr-x  1 xuo users 35587264 févr. 13 18:46 KeePassXC-2.6.4-x86_64.AppImage

The icon properties contain : 
Command : /mnt/Softs/bin/KeePassXC

If I change the symlink to point to KeePassXC-2.6.2-x86_64.AppImage, then I do not have any problem.

Regards.

Xuo.

**Comment by droidmonkey** [comment]
Is /mnt/Softs a network share or usb device?

**Comment by ericxuo** [comment]
Hi,

/mnt/Softs is an nfs automount.
# df
serveur:/export2/Softs   961302528 597482496  314964992  66% /automount/Softs

 # ls -als /mnt
drwxr-xr-x  3 root root 4096 oct.  30 21:42 .
drwxr-xr-x 26 root root 4096 déc.   5 15:42 ..
lrwxrwxrwx  1 root root   18 juin  16  2018 Serveur -> /automount/Serveur
lrwxrwxrwx  1 root root   17 juin  16  2018 Shared -> /automount/Shared

/etc/autofs/auto.misc : 
Softs           -fstype=nfs,nosuid      serveur:/export2/Softs

Using -DWITH_XC_ALL=ON does work (cmake fails) because of a Yubikey issue than I could not solve.

Regards.

Xuo.

**Comment by droidmonkey** [comment]
Does it crash if you store the appimage on your local partition and access it through the desktop shortcut?

**Comment by ericxuo** [comment]
Hi,

Yes, I get exactly the same issue.
I wrote something wrong in my previous post :
Using -DWITH_XC_ALL=ON does **not** work (cmake fails) because of a Yubikey issue than I could not solve.

Xuo.

**Comment by droidmonkey** [comment]
You probably need the ykpers dev libraries, make sure you are following the build instructions. https://github.com/keepassxreboot/keepassxc/wiki/Set-up-Build-Environment-on-Linux

**Comment by ericxuo** [comment]
Hi,

I have found on rpmfind.net an ykpers rpm package for Mageia (no lib64ykpers-devel or something like that). 
cmake -DWITH_XC_ALL=ON .. still fails with : 
Could NOT find YubiKey (missing: YUBIKEY_LIBRARIES YUBIKEY_INCLUDE_DIRS)

this is the reason why I have followed : 
	  -DWITH_XC_AUTOTYPE=[ON|OFF] Enable/Disable Auto-Type (default: ON)
	  **-DWITH_XC_YUBIKEY=[ON|OFF] Enable/Disable YubiKey HMAC-SHA1 authentication support (default: OFF)**
	  -DWITH_XC_BROWSER=[ON|OFF] Enable/Disable KeePassXC-Browser extension support (default: OFF)
	  -DWITH_XC_NETWORKING=[ON|OFF] Enable/Disable Networking support (e.g., favicon downloading) (default: OFF)
	  -DWITH_XC_SSHAGENT=[ON|OFF] Enable/Disable SSHAgent support (default: OFF)
	  -DWITH_XC_TOUCHID=[ON|OFF] (macOS Only) Enable/Disable Touch ID unlock (default:OFF)
	  -DWITH_XC_FDOSECRETS=[ON|OFF] (Linux Only) Enable/Disable Freedesktop.org Secrets Service support (default:OFF)
	  -DWITH_XC_KEESHARE=[ON|OFF] Enable/Disable KeeShare group synchronization extension (default: OFF)
	  -DWITH_XC_KEESHARE_SECURE=[ON|OFF] Enable/Disable KeeShare signed containers, requires libquazip5 (default: OFF)
	  **-DWITH_XC_ALL=[ON|OFF] Enable/Disable compiling all plugins above (default: OFF)**


Xuo.

**Comment by ericxuo** [comment]
Hi,

I could compile KeePassXC-2.6.4 and make it work by double-clicking on its icon on my KDE desktop.
I've used : 
cmake -DCMAKE_INSTALL_PREFIX=../install ..
=> Remove the -DWITH_XC_ALL=ON argument.

For the appImage, I still don't know the reason why it fails. I thought that an appImage file was containing 100% of the libs, files, ... that the application needed. So, I don't see why it fails if it is really 100% standalone and independent of what is around. But I'm probably/certainly wrong.

Xuo.

**Comment by droidmonkey** [comment]
AppImages are not 100% standalone, they are close though.

**Comment by ericxuo** [comment]
Thank you for your help and explanations. If you have more ideas to find the reason why the appImage fails with : 
libgcc_s.so.1 must be installed for pthread_cancel to work
do not hesitate to ask me to make some more trials.
Is it possible to make an appImage with a -debug parameter ? It could help to find the issue.

Regards.

Xuo.

**Comment by ericxuo** [comment]
Hi,

Some more stuff : 
\# ldd keepassxc_2.6.4 | grep libgcc
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f2318460000)
\# ldconfig -v | grep libgcc
        libgcc_s.so.1 -> libgcc_s_32.so
        libgccpp.so.1 -> libgccpp.so.1.3.1
        libgcc_s.so.1 -> libgcc_s-8.4.0.so.1
I've removed the warnings.
What I don't understand is that I have to pointers for libgcc_s.so.1.

Xuo.

**Comment by droidmonkey** [comment]
Sure you have libgcc installed but it doesn't seem to have the symbol named "pthread_cancel"
