### ISSUE TITLE
Snap page should give hints about the common Snap issues

### ISSUE THREAD

**Issue by alexanderadam** [keepassxreboot/keepassxc#6122]
Currently [the Snap page shows unparsed Markdown](https://snapcraft.io/keepassxc) of the README.

Apart from the broken formatting which impairs readability it also lacks hints to [the KeePassXC-Browser Helper Script](https://raw.githubusercontent.com/keepassxreboot/keepassxc/master/utils/keepassxc-snap-helper.sh) and [the AppArmor fix regarding the log SPAM](https://github.com/keepassxreboot/keepassxc/issues/3096#issuecomment-517974625) (`audit: type=1400 audit(….…:…): apparmor="DENIED" operation="open" profile="snap.keepassxc.proxy" name="/snap/core/…/usr/share/locale/en_GB/LC_MESSAGES/snappy.mo" pid=… comm="snap-exec" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0`).

I'm very sure that these should be of interest for the Snap users, thus it would be great if these could be added to the Snap documentation page.

**PS:** Thank you so much for KeePassXC and the browser extension. :pray: 
**PPS:** The AppArmor fix should probably added to [the Snap part of KeePassXC website](https://keepassxc.org/download/#linux) as well.

**Comment by droidmonkey** [comment]
AppArmor that you place on your browser technically has nothing to do with the snap deployment, but it would be good to add an FAQ for it. I'm not sure how the Readme got placed on the snap page, it used to be normal text.
