### ISSUE TITLE
Import entries from OTP key-uri file

### ISSUE THREAD

**Issue by vbauchart** [keepassxreboot/keepassxc#6125]
# Use Case

I use FreeOTP (or any Smartphone app that support export to key-uri file) and I want to import entries to KeepassXC for backup purpose

# Current state

Currently, I have to export in Key-Uri standard format (as in https://github.com/google/google-authenticator/wiki/Key-Uri-Format ), then manually create entry in KeypassXC:
1. create new entry
2. Read the name from key-uri and paste it into "`Title`" field
3. Read the email from key-uri and paste it into "`User`" field
3. click on "`Advanced`" tab
4. click on menu "Entries"->"TOTP"->"Setup TOTP"
5. Read the Key from key-uri and paste it into "`Secret Key`" field
6. Read the period, Algorithm and digits from key-uri and use widgets to set period, Algorithm and digits
7. save
8. Go back to 1.

# Requested improvement

When I backup lot of key-uri, this can be long. So I propose the following improvement:
1. New menu "Import->Import Key-uri file" to import a file containing 1 line per key-uri
2. Create all entries in KeypassXC with fields imported from the file : `Title`, `User`, `otp` properties

**Comment by droidmonkey** [comment]
The problem with Key-URI format is that almost all fields are optional, there is no guarantee you will have Title or Username fields. I don't think an imported is very useful in this case. FWIW, you can easily add TOTP by just created an advanced attribute named otp and pasting the key-uri as the value. You don't need to use the TOTP setup dialog.

**Comment by droidmonkey** [comment]
This won't be implemented, if you have a key-uri just create an `otp` attribute and paste it in there. Otherwise extract the secret key and configure TOTP as normal.

**Comment by TheGrave** [comment]
Here is a possible workaround (I haven't tested it):

https://gitlab.com/stavros/freeotp-to-andotp-migrator
