### ISSUE TITLE
Lock Databases via keepassxc Command Line flag

### ISSUE THREAD

**Issue by h4ckerle** [keepassxreboot/keepassxc#6126]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
I would like to lock the Database in the visual client via the cli.

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )
Script the locking of the database

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
I wanted the option to have my database locked whenever my door contact is opened so that I won't have any open databases either if I forgot to lock the database or someone  enters my room unexpectedly.

**Comment by droidmonkey** [comment]
The CLI does not communicate with the GUI at all. #4513

**Comment by h4ckerle** [comment]
It does not? Why is this then working: keepassxc --keyfile Sync/lkeyfile Sync/Main.kdbx --pw-stdin

**Comment by droidmonkey** [comment]
Oh you mean that command line, nevermind

**Comment by fganzer** [comment]
I agree, locking/unlocking a database in the GUI from commandline would be nice. [Until that's implemented I followed this guide utilizing D-BUS to achieve exactly that.](https://grabski.me/tech,/linux/2020/09/02/automatically-unlock-keepassxc-on-startup-and-after-lock-screen/)

**Comment by sniff-numeral** [comment]
I agree, it would be nice to lock/unlock a database in the GUI from commandline, especially by making use of "--pw-stdin". [Until that's implemented you can use this workaround utilizing D-Bus.](https://grabski.me/tech,/linux/2020/09/02/automatically-unlock-keepassxc-on-startup-and-after-lock-screen/)

**Comment by lomik31** [comment]
I would like keepassxc not to start a new window when using this command, but still run in the tray.
