### ISSUE TITLE
[Linux] Half dark mode on start

### ISSUE THREAD

**Issue by Aikatsui** [keepassxreboot/keepassxc#6127]
#### Steps to Reproduce
1. Set dark mode and quite application (should not run on background)
2. Open keepassxc then can be see half dark mode

![ksnip_20210215-040347](https://user-images.githubusercontent.com/63988538/107987511-c279b880-7000-11eb-8ac4-3f458fa34a3b.png)

Solution: View --> Theme --> select dark mode again (even it already has selected)
Troubleshoot: `apt reinstall keepassxc`

Ubuntu 20.04.02 Gnome X11
KeePassXC 2.6.4 34a78f0

**Comment by droidmonkey** [comment]
You are probably running under qt5ct, that conflicts quite a bit with our themes.
