### ISSUE TITLE
Set default timeout of keepassxc-cli 'clip' to 10 seconds

### ISSUE THREAD

**Issue by shemeshg** [keepassxreboot/keepassxc#6128]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
keepassxc-cli: 'clip' is not automatically cleared after N seconds

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. keepassxc-cli open /tmp/testdb
2. clip "test entry"
3. Cmd->V see that Past Works.
4. wait 15sec or more
5. Cmd->V see that Past still Works.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
.After 15sec or more
Clipboard should be auto cleared like in the GUI.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
I can past long after the 
clip "test entry"

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.4
Revision: 34a78f0

Qt 5.15.2
Debugging mode is disabled.

Operating system: macOS 11.2
CPU architecture: x86_64
Kernel: darwin 20.3.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
- libgcrypt 1.9.1

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS

**Comment by droidmonkey** [comment]
Did you set a timeout? https://github.com/keepassxreboot/keepassxc/blob/75e4329c80ab93c6c05ca8042684d49ca4893cfc/src/cli/Clip.cpp#L58

**Comment by shemeshg** [comment]
I See it now:
"timeout                        Timeout in seconds before clearing the
                                 clipboard."

No I was not aware, it was required
So I guess it is not a bug....

But, it is a bit scary that timeout is infinite by default,
Maybe default of int timeoutSeconds = 0; could be int timeoutSeconds = 7;
To avoid clumsy users not aware of that...

**Comment by droidmonkey** [comment]
I also do not like that the default is not secure. I will make this change and attribute it to this issue. Default should be 10 seconds, same as GUI. Setting `--timeout 0` would be for infinite.

**Comment by droidmonkey** [comment]
Sorry timeout is a positional argument, not --timeout.
