### ISSUE TITLE
Add 2FA recovery key and SSH key field as a standard database field

### ISSUE THREAD

**Issue by hoelderlin2368** [keepassxreboot/keepassxc#6129]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: #

Currently there seem to be no dedicated field for 2FA recovery keys and SSH keys in KeepassXC entries with newly created databases. I can also not find any easy to use feature to add additional global customs fields manually under settings.

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )

## Context
[NOTE]: # 

It is not useful to use the notes field for this purpose since more and more websites and platforms implement 2FA features as default. The recovery key is therefore needed to recover lost 2FA apps or devices. A standard field in KeepassXC would help standardize exports before each user starts creating custom fields if that is even possible right now.

**Comment by hoelderlin2368** [comment]
Not sure why users require templates for standard use behavior. Creation of some new standard fields to cover day to day use sounds a lot easier to me.

**Comment by droidmonkey** [comment]
You can use advanced attributes right now if you want
