### ISSUE TITLE
Window resize in compact mode to the minimum resizable by the user

### ISSUE THREAD

**Issue by i-srinivas** [keepassxreboot/keepassxc#6130]
## Overview
Over the years I have used Keepass and keepassx. The smaller main window helps users to see the target windows like a web browser and keepassxc window visible without taking too much screen real estate. 

The default min. fixed width of keepassxc window to 800px blocks the view and user should be able to make a choice to resize the window as he/she desires.

The prev. issue and related issues are #5243 #5014 #2198 #5837 

## Steps to Reproduce

Pre-requiste: Download the latest release v2.6.4
1. Install the latest release build on target platform (Window 10, Debian 10/Buster, Mac OS 10.13)
2. Try to resize the Main window to minimum
3. Select the menu 'View > Compact Mode'
4.Try to resize the main window to minimum

## Expected Behavior
From UX perspective the option to resize main window is more user friendly and leaving up to the user to see the best screen usage. After looking at the history of the prev. user requests related to the feature, here are few suggestions

1) Keep the UI inline with keepass, atleast in Compact View mode or add an Expert View mode. I recommend using the compact view mode.

2) Move the search bar in toolbar to drop down or float or re-order items rather than hide. KeepassX shows the search bar when clicked below the toolbar

![image](https://user-images.githubusercontent.com/22220365/108083983-8bb79880-7028-11eb-8de4-da5392ccac91.png)

Suggest we maintain the keepassx functionality

3) Move preview/notes panel to use larger screen estate as below (keepass app)

![image](https://user-images.githubusercontent.com/22220365/108083166-a63d4200-7027-11eb-9f03-d078aa870006.png)

![image](https://user-images.githubusercontent.com/22220365/108083629-25327a80-7028-11eb-9976-a3566733c979.png)

Suggest, we keep the original keepass functionality.

4) In Compact view mode, skip the database selection entry view 

![image](https://user-images.githubusercontent.com/22220365/108083554-0cc26000-7028-11eb-82e8-12bf1f0cee72.png)

Note: KeepassXC screenshots are from modified local dev. snapshot build with latest code from developer branch 

## Actual Behavior
The Main window is not resizable below 800px width.

## Context
[NOTE]: # ( Give us any additional information you may have. )
New KeePassXC user, coming from KeePass, KeePassX, PasswordSafe

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.6.4
Revision: 34a78f0

Operating System: Windows 10, Debian 10/buster with Mate, macOS 10.13 (High Sierra)
Desktop Env: Window 10, Linux - Mate, MacOSX
Linux Windowing System: X11 on Mate

KeePassX - v.2.0.3 (Debian Linux 10/Buster)
KeePass - v2.35 (Windows 10)

PS: I am happy to work on the dev. issue, if we agree to proceed

**Comment by droidmonkey** [comment]
Curious, what is your screen resolution and physical screen size?

**Comment by i-srinivas** [comment]
I use various devices, below are the most used device screens

1600x900 - 17.3 inch display
1920x1200 - 17 inch
2560x1080 - 34 inch wide

**Comment by jesseruth** [comment]
Hey I am encountering a similar issue.
I am unable to see any of the dialog options on the lowest part of the UI. I understand that I have a custom screen resolution but I require the larger texts and display.
I am on ubuntu dell xps 13. The laptop has a 4k display but I have scaling set to 200% and font scaling factor set to 1.5. 
my resolution is
3840 x 2160
![image](https://user-images.githubusercontent.com/4072648/108445504-5cb04b00-7211-11eb-945d-574bc8df3d3e.png)

**Comment by droidmonkey** [comment]
Screenshot please, be sure not to expose any sensitive information.

**Comment by jesseruth** [comment]
Thanks I looked twice and then again when you commented.
I was just curious if I could get this to work and changing these values fixed it for me:
https://github.com/keepassxreboot/keepassxc/pull/6149

**Comment by droidmonkey** [comment]
I am not sure why you cannot just shrink the window vertically? You can also just maximize the window and it will show everything. The current minimum height is set to 600px.

**Comment by i-srinivas** [comment]
The issue is generic, happens in all platforms - Windows, Mac, Linux  (Debian 10/Mate)

**Comment by droidmonkey** [comment]
BTW, this is directly a result of KeePassXC running as a snap and having a screen scale factor of 200% or higher on Ubuntu. I reproduced readily on Ubuntu 20.04. I need to package the snap with a more modern version of Qt...

![image](https://user-images.githubusercontent.com/2809491/110247614-178f5700-7f3b-11eb-8c34-2abae81a8c54.png)

**Comment by ashjoubert** [comment]
This issue is *not* fixed by #6149, which changes minimum *vertical* size not *horizontal* size. Main window minimum *width* is still 800, which is more than a third of screen width on 1080p displays and almost two thirds of screen width on 720p displays. Please let users resize the main window to a size that works for them. Tested in Compact Mode with Classic (Platform-native) theme on Debian/sid keepassxc 2.6.6+dfsg.1-1.

**Comment by 0xpr03** [comment]
Yep, please let us half-size this on a typical 14" 1080p display. The minimum width is really annoying. (Windows here)

**Comment by RENANZG** [comment]
Really annoying...
```
user@debian:~$ xrandr --listactivemonitors 
Monitors: 1
 0: +*eDP-1 1366/309x768/173+0+0  eDP-1
user@debian:~$ inxi -b
System:
  Host: debian Kernel: 6.1.0-12-amd64 arch: x86_64 bits: 64
    Desktop: LXQt v: 1.2.1 Distro: Debian GNU/Linux 12 (bookworm)
(...)
Display: x11 server: X.Org v: 1.21.1.7 driver: X:
    loaded: modesetting unloaded: fbdev,vesa dri: iris gpu: i915
    resolution: 1366x768~60Hz
```
![screen-2023-09-14-11-27-29](https://github.com/keepassxreboot/keepassxc/assets/53377291/95dfa16a-e2c3-4ba0-b1b4-4fa4b3043807)
