### ISSUE TITLE
Password entered twice.

### ISSUE THREAD

**Issue by BackuPs** [keepassxreboot/keepassxc#6132]
When using autotype with code like this.

{CLEARFIELD}{USERNAME}{TAB}{CLEARFIELD}{PASSWORD}{TAB}{TAB}{CLEARFIELD}{S:AuthCode}{ENTER}

In firefox it happens that the password is entered twice in the firefox connection. Havent tested any other browser.  It starts happening after editing the custom autotype is modified and saved.

If i close keepassxc completely and start again it is ok.  I am using the portable. version

If i use the keepass insert not autotype the password is entered correctly and only once.

Also why do i have to reconnect again and again to the database in firefox.

It would be nice if keepassxc would detect extra field automatically and stores  them and its connection like keepass does. And it should not enter the password twice.  There is only one password in the database for the entry.

and other request is please add the autotype call ability to the browser right click menu !  This also works flawlessly in keepass but not in keepassxc.

I reverted to keepass as this is so buggy that it is unworkable.

**Comment by droidmonkey** [comment]
Don't use the browser extension AND Auto-Type. Pick one or the other.

**Comment by BackuPs** [comment]
I am using auto type..... and it is entering the password twice !!  I am not using the browser extension. Why are you closing this ticket?  It is a bug !

i will stay at keepass. What a weird and abrupt support  is this !  dont have  a nice day !

**Comment by droidmonkey** [comment]
There is no way that autotype is typing the password twice with that sequence. There must be some form of auto fill occurring either from Firefox internal password manager or some other source.

**Comment by BackuPs** [comment]
then explain to me why that it starts happening after editing the auto type string.  I need to close keepassxc and restart it and then it is ok.

There are no  extensions loaded in FF.

**Comment by droidmonkey** [comment]
Then what are you connecting to keepassxc?

**Comment by BackuPs** [comment]
i had multiple questions

1)  the issue reported double password.

2) it would be nice if the keepassbrowser connection is installed that it can handle multiple fields not just 2 (name and password). It should follow the setting for auto type set in that saved connection !  Enlight me if that is possible as i can not find it.

3) it would be nice if one can call the auto type sequence from the right click drop down keepassxc menu in the browser for the saved url. this way it can handle more then 2 fields.

I can do these with keepass without any issues. But not in keepassxc

**Comment by droidmonkey** [comment]
You are getting a double password because the browser extension is filling the username and password, then you are using Auto-Type to fill in the username and password. Likely when Auto-Type presses TAB it is causing the extension to fill in the password again and autotype is typing it afterwards. Thus, you need to disable use of the extension for this website, or only use autotype for the authcode. 

You can setup the KeePassXC browser extension to fill in additional fields by following these instructions: https://keepassxc.org/docs/#faq-browser-string-fields

**Comment by BackuPs** [comment]
I tried that help and i get this  but i dont need TOTP..... i need the 3rd field... no matter what i try i can not get this to work.  I have read the manual before even posting here and ran into the issue for hours now. Something that should be so simple is not easy to achieve,..

Is there a video tutorial somewhere?  thank you !

![afbeelding](https://user-images.githubusercontent.com/6078370/108229168-d7109a80-713f-11eb-884e-b1bfe316d6df.png)

**Comment by droidmonkey** [comment]
![image](https://user-images.githubusercontent.com/2809491/108236781-4624c980-7115-11eb-9b3e-8adb1bf4f79b.png)

You need to skip the TOTP selection, then on step 4 (see above) click to add the first string field.

**Comment by BackuPs** [comment]
i did skip the totp and get the textfield #1,  and i saved the field bindings. But if i return and have click the keepassxc button the field is not filled with any value.  That is my problem..  

I did create a additional field and named it KPH:Authorization code and set its value, but it is not used. Why?

![afbeelding](https://user-images.githubusercontent.com/6078370/108248402-177a1380-7154-11eb-9361-6f6242edb0b9.png)

**Comment by BackuPs** [comment]
There has to be a space between KPH: and the name field !!!  That solved the issue. But may i suggest to rewrite the documentation a bit as this is most certainly unclear.

 Pfff. Thank you for your patience.

**Comment by droidmonkey** [comment]
Yes agree the docs are terrible on this, it is on our todo list
