### ISSUE TITLE
Upon KeePassXC-PassIFox-Firefox - source of password storage changes in Firefox, so Firefox-based passwords hidden. Migration description needed.

### ISSUE THREAD

**Issue by Anton-Latukha** [keepassxreboot/keepassxc#614]
## Expected Behavior

On connecting KeePassXC to Firefox, get Firefox passwords imported if it possible.

Or at least make a great disclaimer placed on my face, that this action is going to slaughter all my Firefox passwords.

## Current Behavior

All my passwords are gone.

Besides that connection and mutual work KeePassXC - Firefox looks to work great.

## Possible Solution

Make a big-fat warning that **"Firefox stored passwords are going to disappear."**.

Even better - work cross team to make proper import with PassIFox (maybe it is Firefox behavior).

## Steps to Reproduce (for bugs)

1. Install Firefox (Beta 54.0b12)
2. (optional) Install Firefox best master password add-on [Master Password+](https://addons.mozilla.org/en-US/firefox/addon/master-password/). Configure it so it requests password at start. 
3. Have a Firefox account linked to Firefox.
4. Populate Firefox storage with passwords
5. Setup KeePassXC
6. Enable HTTP feature
7. Install PassIFox in Firefox
8. Restart Firefox
9. Connect PassIFox to KeePassXC
10. Profit! - Passwords are gone from Firefox

## Context

How I affected. Once more. All my passwords are gone.

And Firefox sync is propagating that, destroying all my passwords on all devices I have.
I disabled network on my phone. At least I save them on my phone for now (FF mobile can view stored passwords).

Funny side-note:
I am from Ukraine and had a registering mail and also major mail on Yandex. It is blocked in our country on ISP levels, happened recently. So if I now need to recreate forgotten passwords I need to sit in Tor network. Thanks I figured-out I can just not use my phone.

## Your Environment

* KeePassXC version: 2.1.4
* Firefox (Beta 54.0b12)
* Firefox add-on PassIFox (1.22)

### Additional
* Operating System and version: Arch Linux, Kernel 4.11.2.
* Qt version: 5.8.0
* Compiler: --- (KeePassXC installed from community package)
* Firefox add-on Master Password+ (1.23)

**Comment by Anton-Latukha** [comment]
KeePassXC crashed on me while I was choosing Icons.
I opened /usr/bin, and I have a lot of binaries there (5670).
It may be KDE file menu crashed KeePassXC.

Result is - DB is corrupted. I have muscle memory on that master password I chose for DB now.

=======

1. I removed PassIFox.
2. Disabled Master Password+
3. Restarted Firefox
4. No passwords in Firefox
5. Disabled Firefox master password
6. All my passwords suddenly reappeared

**Comment by weslly** [comment]
I'm pretty sure KeepassXC can't delete your Firefox keychain, since it only provides the API to the Keepass-HTTP protocol. Only the passifox addon has access to your browser passwords.

You should report this to the [passifox repository](https://github.com/pfn/passifox) instead.

**Comment by Anton-Latukha** [comment]
Can you wait for a moment.

It is not a passifox or KeePassXC.

It is Firefox behavior.
They done sourcing of passwords some versions ago. And password can be provided only from one (chosen) source.

So it is basically changing they internal source, to PassIFox source. And PassIFox source has no passwords in it (in DB).

After I disable PassIFox - passwords come back.

**Comment by Anton-Latukha** [comment]
I found a way to import passwords from Firefox:

1. Install Password Explorer addon and export passwords to XML or CSV.
2. Imported XML with KeePass.
3. Exported with KeePass to KeePassX 2.x DB.
4. Imported KeePassX 2.x DB to KeePassXC.
5. Everything works, passwords shown up in PassIFox source.

**Comment by Anton-Latukha** [comment]
So, if KeePassXC had import from Password Explorer XML or CSV feature - it can be done more directly.

**Comment by Anton-Latukha** [comment]
As mentioned #533, CSV import must arrive in 2.2.

So I hope my info helps.
