### ISSUE TITLE
make it possible to open multiple databases from the command line minimized and keep them open and available

### ISSUE THREAD

**Issue by tuxcrafter** [keepassxreboot/keepassxc#6143]
KeePassXC-Browser 1.7.6
KeePassXC 2.6.4

1. Please make it possible to open multiple databases from the command line and keep them open and available. I would suggest adding an additional command line option: --background or --daemon or --load. 

The trick is knowing which key goes with which database that is why I suggest being able to add a database/key single command and add talk to a running process and add them in an open state.

keepassxc /path/to/database01.kdbx -k /home/jdoe/keyfile01.key --background --minimized
keepassxc /path/to/database02.kdbx -k /home/jdoe/keyfile02.key --background --minimized
keepassxc /path/to/database03.kdbx -k /home/jdoe/keyfile03.key --background --minimized

2. Please make the MinimizeOnStartup an command line option, so I can script the start of the application as minimized but when the user loads the application manually it starts normally and not minimized.

I will donate an other 150 euro if the above features get implemented in the KeePassXC 2.6.5 release.

Jelle de Jong

**Comment by droidmonkey** [comment]
Captured in #2089
