### ISSUE TITLE
Implement SSH agent on Windows

### ISSUE THREAD

**Issue by CzBiX** [keepassxreboot/keepassxc#6145]
## Summary
Implement SSH agent on Windows, so we can get rid of peagent(already dead?).

## Examples
reference: https://github.com/dlech/SshAgentLib/blob/master/SshAgentLib/PageantAgent.cs

## Context
Pageant does not support confirm-on-use or automatic removal of key after a timeout.

**Comment by droidmonkey** [comment]
We do have ssh agent on Windows, and we do support OpenSSH for Windows.

**Comment by CzBiX** [comment]
AFAIK, KeePassXC only support agent client mode. I still need to run pagent to make it works.

**Comment by droidmonkey** [comment]
That is outside the scope of our application. We are not an actual ssh agent on any platform. Recommend using the built in windows 10 openssh agent.

**Comment by CzBiX** [comment]
Thanks for your advice. I switched to windows openssh agent now.
But some of softwares i'm using support `pageant` only.
Maybe what I need is https://github.com/buptczq/WinCryptSSHAgent.

**Comment by droidmonkey** [comment]
That looks pretty neat!

**Comment by CzBiX** [comment]
I submitted some PRs, made the [WinCryptSSHAgent ](https://github.com/buptczq/WinCryptSSHAgent)become a complete SSH agent.
the guys who looking for alternatives to windows 10 openssh agent can have a look at it.

@droidmonkey We may can close this issue now. As I think, it's not a good idea to implement all of these ssh agent implementations by KeePassXC. it's better to let others to handle it.

**Comment by droidmonkey** [comment]
Our thoughts as well
