### ISSUE TITLE
Bug: Reference is not resolved after cloning an entry

### ISSUE THREAD

**Issue by ftes** [keepassxreboot/keepassxc#615]
#370 adds support for references.

However, after cloning an entry and generating references, these references are not resolved on _copy to clipboard_, _http_ and _auto type_.

The problem seems to be that the UUID in the reference is uppercase, while the UUID of the source entry is lowercase. This breaks the resolving of the reference.

See https://github.com/keepassxreboot/keepassxc/pull/370#pullrequestreview-41435996

## Workaround
Manually edit the reference so that the UUID is lowercase. Then resolving works as expected.

## Expected Behavior
References in a cloned entry should be resolved when copying/auto-typing etc.

## Current Behavior
When copying/auto-typing referenced fields, the reference itself is output. E.g. after copying a password field the clipboard holds `{REF:P@I:8266fe15f28dc2be0698b26ac9d785f8}`.

## Possible Solution
Use same case (uppercase/lowercase) for UUIDs when
- generating fresh UUIDs for new entries and
- references that include UUIDs to existing references

## Steps to Reproduce (for bugs)
1. create a new entry
2. clone the new entry and select _Replace username and password with references_ in dialog
3. do a `Ctrl+c` on the cloned entry (copy password to clipboard)
4. inspect the clipboard content

**Comment by ftes** [comment]
@mrrsm maybe you have an idea for an easy fix.

**Comment by TheZ3ro** [comment]
I cannot reproduce this with xUbuntu on the latest develop version.
Using both uppercase and lowercase hex UUID is fine for me.

**Comment by ftes** [comment]
@TheZ3ro thanks for checking.
Update from my side: after reinstalling everything works for me now (switched back and forth between [AUR version](https://aur.archlinux.org/packages/keepassxc-git/) which uses `develop` branch and the [official Arch repo](https://www.archlinux.org/packages/community/x86_64/keepassxc/)).

Maybe this happened due to some weird intermediate state that a reboot would also have fixed. I will keep an eye on it and close the issue for now.

**Comment by TheZ3ro** [comment]
Ok thanks @ftes anyway for the report :wink:
