### ISSUE TITLE
Option to automatically empty recycle bin after set time interval

### ISSUE THREAD

**Issue by Backspaze** [keepassxreboot/keepassxc#6150]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
An option to automatically empty recycle bin after set time interval, it could either be set by editing the recycle bin group or in the database settings.

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )
Configure the settings to empty the recycle bin after 30, 90 or 365 days, or a custom time interval with granular controls, maybe even down to the minute, like the setting for expiry date.

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
To automate a albeit easy but tedious task to perform, and practically every other application I know of has a setting for this so it would bring feature parity with what users might expect when coming from other platforms.

**Comment by droidmonkey** [comment]
Good idea 💡

**Comment by droidmonkey** [comment]
We won't be implementing this, we never want to be in a position of automatically deleting data.

**Comment by Backspaze** [comment]
That's too bad. I don't really see the issue as long as the feature would be an opt-in feature, so nothing gets deleted automatically unless one enables the feature. There could even be one or more warnings popping up when one does enable the feature, to help avoid that it's enabled by mistake.

**Comment by joshhansen** [comment]
Just today I was looking for such a feature. There is perhaps also a security risk to letting stale entries accumulate indefinitely---I see that my recycle bin contains 187 entries! As the modification date seems to reflect the date the item was "recycled" this can be implemented manually, yet I would very much appreciate an automated method. Thanks for considering.
