### ISSUE TITLE
Navigation panel should have different defaults for maximised window and Window mode

### ISSUE THREAD

**Issue by dareducky** [keepassxreboot/keepassxc#6152]
## Overview
Set KeePassXC to Window Mode (i.e. not maximized / Restore Down button) and drag the left navigation panel to the limit of your group label. Now click maximize window (Window maximized). The left navigation panel now is huge as it expand with the maximized window.

Now that your screen is maximized, adjust again your navigation panel column so that its on the limit of your group labels. try to go back to window mode. The left navigation panel now is hidding the group labels.

## Issue 1:
1. Maximize window
2. Adjust the left navigation pannel so that the column is on the edge of your group labels
![Max 2](https://user-images.githubusercontent.com/76420385/108543284-a194ba00-72c3-11eb-8ee4-c79d14d87050.png)
3. Click Restore Down
4. Now the left panel is barely visible.
![Min 2](https://user-images.githubusercontent.com/76420385/108543360-ba9d6b00-72c3-11eb-80b0-63a5be299682.png)

## Issue 2 (inverted problem):
1. Window mode
2. Adjust the left navigation pannel so that the column is on the edge of your group labels
![Min 1](https://user-images.githubusercontent.com/76420385/108543407-cdb03b00-72c3-11eb-9f31-dabeacedbff6.png)
3. Click Maximize 
4. Now the left panel is huge
![Max 1](https://user-images.githubusercontent.com/76420385/108543415-d274ef00-72c3-11eb-9257-243954c3c249.png)

## Expected Behavior
The left column bar should be aware of changes on window size. Maybe through an option to autoresize said column based on available group directories name lenght?

  
## Actual Behavior
See Issue 1 and 2

## Context

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.6.4

[NOTE]: # 
Operating System: Windows

**Comment by droidmonkey** [comment]
It's set to a _proportion_ of the window size, not a fixed width. So it occupies (for example) 10% of the screen width. The actual width is wider or narrower based of the window size.

**Comment by gagarine** [comment]
You can manually set the columns to "fit to windows" using a right click on the columns header.
<img width="374" alt="image" src="https://user-images.githubusercontent.com/164074/185360839-8c6fcb87-ac6d-435f-b03a-9282c2d475f4.png">

But the columns will keep a fixed size when the windows is resized, living a gab on the right when making the windows bigger or a scrollbar when making it smaller (at least on MacOS).

As a quick fix (for 2.7.x :)) could it be possible to automatically run "fit to windows" when the windows is resized?
