### ISSUE TITLE
KeePassXC on macOS Sierra

### ISSUE THREAD

**Issue by pienisieni** [keepassxreboot/keepassxc#6156]
What is the last working [version](https://github.com/keepassxreboot/keepassxc/releases) of KeePassXC for the most recent version of macOS Sierra (10.12.6)?

I've tried 2.6.4 (as well as 2.6.0) but get this error message on launch:

> You have macOS 10.12.6. The application requires macOS 10.13 or later.

I am unable to upgrade macOS to 10.13+ (High Sierra, Mojave, Catalina or Big Sur)..
trying to see if it's viable to still run this. TY.

![Blank_Skitch_Document](https://user-images.githubusercontent.com/9020358/108593269-2233e300-73b6-11eb-8629-5a7a4795ef7c.png)

**Comment by droidmonkey** [comment]
https://github.com/keepassxreboot/keepassxc/releases/tag/2.5.4

This is the last version with Sierra support

**Comment by tenzap** [comment]
If you use https://www.macports.org, there you will find 2.6.6 (for osx version >= 10.7)
