### ISSUE TITLE
Capability to hide the "Group" column while searching

### ISSUE THREAD

**Issue by gagarine** [keepassxreboot/keepassxc#6163]
## Summary
I'm not using the group feature, all my password are in the "root" group. I would like to be able to hide the group column on the list like any other columns.

![Screenshot 2021-02-21 at 19 20 49](https://user-images.githubusercontent.com/164074/108634453-eeba8c80-7479-11eb-9772-15b989dbb80e.png)

**Comment by droidmonkey** [comment]
That is just for searching

**Comment by CzBiX** [comment]
I used group feature, but all name of my entry are different.
show group name in searching result is useless for me too.

**Comment by gagarine** [comment]
The issue could eventually be changed to: "display same columns in research that the columns set in list mode"?
