### ISSUE TITLE
Ability to have export to HTML File Alphabetized

### ISSUE THREAD

**Issue by uffbros** [keepassxreboot/keepassxc#6164]
I would like to be able to export the database to HTML that would alphabetize the HTML file list. It just randomizes them now.

It would much easier to find the entry I want if it was in order.

**Comment by droidmonkey** [comment]
Good point, they are actually written in "Natural Order" which is essentially the order they were created in the database.

**Comment by libklein** [comment]
I've been working on an PR and was wondering how we should approach this. Should be list all entries in alphabetical order (i.e., as a large list) or should be keep the group view? I've implemented the latter - i.e. entries/groups are sorted recursively.

**Comment by droidmonkey** [comment]
Prefer the latter
