### ISSUE TITLE
Auto clean cache files on database lock?

### ISSUE THREAD

**Issue by MobCat** [keepassxreboot/keepassxc#6165]
Hi, sorry i'm new to KeePassXC so sorry if this comes off more as a support ticket rather then a feature request.
I was wondering if there is a setting or function to automatically delete files in "C:\Windows\Temp" when no longer in use in my case as i'm not sure what other cache files other OSs uses.

So I can store a file in my password database in advanced options. grate.
Lets just say it's "login instructions.txt"
So I click on the entry, go down to advanced, click on login instructions.txt and click open.
It decrypts the file to "C:\Windows\Temp\lKGlfe.login instructions.txt" and opens it in notepad++, all fine there.
However when I close notepad++ when i'm done with the file, KeePassXC doesn't acknowledge the file is no longer in use that i'v closed notepad++ so the file is still saved in temp.
If I lock my database file KeePassXC doesn't do a cache / temp clean soo all the files are still located in temp. including whatever "keepassxc-MobCat.lock" is. 
Only when I close the KeePassXC program entirely then it cleans it's cache files.
Am I missing a "Clean cache and temp files on database lock" or "delete files when closed" setting somewhere or does all cache files just live in temp regardless of if the database is locked or not?

**Comment by droidmonkey** [comment]
Welcome! It is odd that files are being written to the system temp, they should be written to c:/users/MobCat/AppData/Local/temp

**Comment by MobCat** [comment]
Yeah might be a bug then??? Or I'm doing something wrong? It's running in portable mode off a usb stick if that helps any.
Also KeePassXC is not saving any changes made to attached files either. Might be because it's decrypting them to the wrong location maybe?

**Comment by droidmonkey** [comment]
See the linked issue above. If you are doing a lot of work with files you should use cryptomator instead.

**Comment by MobCat** [comment]
Windows 7 SP1 64-bit (Yeah I know... Don't ask... It just works for me and I know enough not to nuke it with junk)
But yeah I should try this out on my windows 10 laptop as well then..
My bad password management before this was txt files with passwords and process instructions and command variables and such all kinda rolled into one. Makes transitioning easier when I can just bake some of that txt file into the password file.
I'll have a look at cryptomator thanks. But yeah i'm kinda an odd case dont trust cloud anything (to easy for it to just go missing one day) and everything I do is txt files but yeah inbuilt txt reader would be nice. Then it doesn't have to save and open anything. someone in the linked issue was talking about og keepass could open jpgs with an inbuilt viewer.. that's kinda overkill imo though..

Lol my dream program is just encrypted text files but yeah never could find a nice windows way of doing that... Everyone is like do linux commands -__-'

**Comment by droidmonkey** [comment]
Gonna close this because #2400 handles the attachment issues. I strongly recommend moving the text file data into actual entries so you can take advantage of Auto-Type and browser extension instead of copy / paste. You should also not store your database on a USB stick, high probability of corruption of data.

**Comment by MobCat** [comment]
Thanks for your help. Think i'm going to store normal password stuff in KeePassXC and keep all the very detailed process instructions and command variables in a Cryptomator vault as it doesn't seem like KeePassXC has a very robust notes function, and that's totally fine.
The USB stick is just for convenience. Don't like / sometimes can't use in some locations google drive or dropbox so I just take the USB stick places. USB stick is backed up to a NAS regularly and that NAS is backed up to a bigger NAS even more regularly.
