### ISSUE TITLE
Allow CSV importing TOTP as bare secret keys 

### ISSUE THREAD

**Issue by orion78fr** [keepassxreboot/keepassxc#6167]
## Overview
Importing a CSV containing TOTP secrets doesn't work.

## Steps to Reproduce
1. File -> Import -> CSV
2. Select the CSV
3. Create the database
4. Associate the fields, including TOTP secrets
![image](https://user-images.githubusercontent.com/8122888/108771894-914b3c00-755c-11eb-88a5-7e88d8b74295.png)

## Expected Behavior
TOTP secrets are imported into the new database.

## Actual Behavior
TOTP secrets are not imported. 
![image](https://user-images.githubusercontent.com/8122888/108772196-fdc63b00-755c-11eb-8254-848082a7f742.png)

## Context
I extracted them manually from Lastpass Authenticator. It may have formatting issues but it generates correctly the TOTPs for those I tested when I add it manually to an existing entry.

KeePassXC - Version 2.6.4
Revision : 34a78f0

Operating System: Windows

**Comment by droidmonkey** [comment]
You need to form them in [key uri format](https://github.com/google/google-authenticator/wiki/Key-Uri-Format). Example: 
```
otpauth://totp/Example:alice@google.com?secret=JBSWY3DPEHPK3PXP
```

**Comment by orion78fr** [comment]
Oh that's probably explains why it didn't work, right...

By the way, my data doesn't have header, I just censored the website (mainly because it's a "competitor" of Keepass).
I copy / pasted my ~20 secrets just after posting this though.

**Comment by droidmonkey** [comment]
Gotcha, I was looking at it cross eyed
