### ISSUE TITLE
macOS Close (⌘W) Windows NOT Close Database

### ISSUE THREAD

**Issue by nmajin** [keepassxreboot/keepassxc#6168]
## Summary
Almost every MacOS application has the keyboard shortcut of "⌘W" to close the Window, so could this be changed instead of closing the database (current configuration)?

## Examples
N/A

## Context
Personally, I like closing the window so the app stays in my status bar and not in my dock, which Hide unfortunately keeps it there.

**Comment by droidmonkey** [comment]
#2672
