### ISSUE TITLE
Crashes when using auto-type

### ISSUE THREAD

**Issue by sabretus** [keepassxreboot/keepassxc#6171]
## Overview
Sometimes Keepassxc crashes on macOS when using a shortcut to auto-type password

## Steps to Reproduce
1. Use Keepassxc with auto-type on for a while
2. After 2-3 days it crashes if the auto-type shortcut used

## Expected Behavior
The app works without crashes

## Context
I have 2 DB's opened at the same time. One protected with a password and another protected with YubiKey

KeePassXC - 2.6.3
Revision: beae186
Operating System: macOS 11.2
CPU architecture: x86_64
Kernel: darwin 20.3.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
- libgcrypt 1.8.6

**Comment by phoerious** [comment]
Can you please test this with on of our snapshot builds? We reworked Auto-Type basically from the ground up: https://snapshot.keepassxc.org/latest/
