### ISSUE TITLE
Ask for unlock when accessing SSH key

### ISSUE THREAD

**Issue by Programie** [keepassxreboot/keepassxc#6172]
KeePassXC supports adding SSH keys to a running SSH agent while opening the database and remove them after closing the database. That's fine.

But, one thing that is a bit annoying is if you just want to SSH to a server and forgot to unlock your database first. In that case, the server will refuse the connection and I have to manually unlock my database and reconnect to the SSH server.

It would be easier if KeePassXC would ask to unlock the database. While unlocking the database, the SSH connection should just wait for KeePassXC to provide the SSH key.

**Comment by droidmonkey** [comment]
There is no way to know you need an ssh key, that is not how the ssh-agent works.
