### ISSUE TITLE
Create an option for « Don’t use this entry for HTTP Basic Auth »

### ISSUE THREAD

**Issue by eromawyn** [keepassxreboot/keepassxc#6173]
I use wordpress to keep some kind of a diary. Accessing this wordpress is protected by HTTP AUTH. Not very private things, but not the kind which should be public. Then to update the diary, I have a wordpress login/pass couple.

I also use KeepassXC to store these passwords, and I have installed KeepassXC-Browser. The Wordpress password is marked with « Use this entry only with HTTP Basic Auth ». 

### So what happens when I go to this page ?  ###
- I get the strange behaviour of nothing happening because, well, HTTP AUTH has multiple credentials in KeepassXC, as long as I don’t click on KeepassXC-Browser icon (known issue), since it gets both HTTP Auth and Wordpress password.
- But if I want to login to wordpress, KeepassXC-Browser receives the correct answer, since the other one is checked as « Use this entry only with HTTP Basic Auth ». So I don’t need to choose the correct one.

### What should happen ? ###
- KeepassXC-Browser should query KeepassXC, and see only one credential valid in HTTP Auth context, and automatically use this one.
- When I want to login to wordpress, it’s already working fine :) 

### Solution ###
There is currently only an option for marking entries with « Use this entry only with HTTP Basic Auth ». There should also be an option for « Don’t use this entry for HTTP Basic Auth », or a selector which allows choosing « HTTP Auth / Web Form » context, or some other way to do that choice.

**Comment by droidmonkey** [comment]
I thought this was done already? Which version are you running?

**Comment by eromawyn** [comment]
I use KeepassXC 2.6.4 (installed with chocolatey) and KeepassXC-Browser 1.7.6 on Brave Browser.

**Comment by droidmonkey** [comment]
#5394, we can likely backport this to 2.6.5
