### ISSUE TITLE
ui control elements for Auto-Type should reflect the actual state (disabled/enabled)

### ISSUE THREAD

**Issue by wereia** [keepassxreboot/keepassxc#6184]
## Summary
Auto-Type is great, but also a danger to leak information by human error. 
I disable Auto-Type for most entries, but I have to check in the settings if it's active or not. 

I would like it a lot when the state is visible in the ui. Just a simple observer for the state. 

Auto-Type disabled for an entry would result in:
- Button in the toolbar has a disabled state (grey shade or something)
- Context menu entry for Perform Auto-Type has a disabled state (grey front instead of black)

I would find the visual feedback very helpful to quickly see if the entry is configured like I want. And to and be sure (while operating) that everything is alright with the entry and that I can't actually clicking anything unwanted by accident.

**Comment by droidmonkey** [comment]
This is no longer the case after #5864
