### ISSUE TITLE
Option to disable/lock Entry-Level Auto-Type completely, while still having global Auto-Type

### ISSUE THREAD

**Issue by wereia** [keepassxreboot/keepassxc#6185]
## Summary
Global Auto-Type is much more secure in my opinion. The Entry-Level Auto-Type writes to the last focus directly. One wrong click in the ui late at night is enough, while you have to confirm multiple levels for the global Auto-Type. 

- I really wish I could either lock (via checkbox in the ui or so) Entry-Level Auto-Type, so that it can't be performed.
- Or to disable Entry-Level Auto-Type completely via setting.

Not sure what I like better of these both options. 

In both cases I would like to keeping the possibility to use global Auto-Type as an option.

I think the use-cases are clear where accidents can happen, aren't they? You manage your passwords late at night, just doing a mistake and your data is written in your chat tool or something. I would love to not have this tension or checking all the time that my last focus was in a non problematic target ;-), when I'm using KeypassXC, which I really admire otherwise.

**Comment by droidmonkey** [comment]
This was taken care of in #5864. If "Always ask before Auto-Type" is enabled then entry level Auto-Type shows a question dialog prior to starting.

**Comment by wereia** [comment]
Thanks for replying. The dialog is a great idea! 

To be frank, I still would like to have an option in addition to disable entry level auto-type completely though. 

But really looking forward to v2.7 with all these nice enhancements!

**Comment by wereia** [comment]
@droidmonkey

Just interested, no bad intentions. All the Auto-Type things in v2.7 sounds really awesome and makes a lot of sense. 

But is there a reason why a simple disable Entry Level Auto-Type option is not wanted for the paranoid people out there? It's a simple option you have in the Keypass 2.X. I switched from it to KXC, because KXC is nicer and I'm using more Linux these days. I was used to this option. Maybe that's why I'm a bit of a pita on that topic. ;-)

I'm certain you will find as many different workflows as you have users, and a simple option would be a blessing for those who would like to exclude this possibility from their mind. Searching the issue tracker it seems that I'm not the only one with this wish. 

cheers

**Comment by droidmonkey** [comment]
I'd consider it

**Comment by hifi** [comment]
To protect IM etc. windows you can also make the default sequence *not* include the last `{ENTER}` and hit it manually yourself. This prevents most accidental submits.

**Comment by droidmonkey** [comment]
You can do that from the root group without any code changes

**Comment by droidmonkey** [comment]
In 2.7.0 we explicitly ask if you would like to continue with entry-level Auto-Type. I consider this enough protection from the feature and will not implement an option to disable it (too many linkages to the feature).
