### ISSUE TITLE
Group sorting: alphabetical sorting does not persist

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [keepassxreboot/keepassxc#6186]
## Overview

if you enable alphabetical sorting and then add a new item, it does not appear in it correct alphabetical place

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Run the program.
2. Have some groups.
3. Add a group called 'aaa_test'
4. See where the new group appears
5. . . and be surprised).
5. Enable alphabetical sorting.
6. Add a new group called 'aaa_test2'.
7. Be surprised where the new group appears.
8. Be forced to tell the program, _again_, to sort.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
No step 5. No step 7.

## Actual Behavior
As in, 'Steps to reproduce'.

## Context
Cf. #3225.
I am filing this present report as a bug - not a feature request - because, as I mean to have shown: the current behaviour is strongly counter-intuitive and it can lead to the user making mistakes.

KeePassXC - Version 2.6.4
Revision: 34a78f0

Qt 5.12.8
Debugging mode is disabled.

Operating system: Linux Mint 20.1
CPU architecture: x86_64
Kernel: linux 5.8.0-44-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- libgcrypt 1.8.5

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: Cinnamon
Windowing System: X11

**Comment by droidmonkey** [comment]
Why would you be surprised? The sorting is an action, not a state. There is no indication that it is a state. We also have no  desire to make it that way, most people like to position their groups absolutely.

**Comment by LinuxOnTheDesktop** [comment]
> Why would you be surprised? The sorting is an action, not a state.

I was surprised because file managers (such as PcManFM, Nemo, and Windows File Explorer) treat sorting as a state.

> There is no indication that it is a state.

Nor so far as I can see is there any indication that it is an action.

> We also have no desire to make it that way, most people like to position their groups absolutely.

If you are confident that most people like it that way, then you might still consider an _option_ to make the dissenters happy.

**Comment by droidmonkey** [comment]
If it was a state there would be a checkbox consistent with the rest of the menu options (see view menu).

**Comment by LinuxOnTheDesktop** [comment]
OK, though one there seems no visible difference between a tickable-but-unticked option and an untickable option. But even if we, er, cross off that point, I have still given you a reason for my surprise and suggested that you could make sort-as-state into an option.

**Comment by droidmonkey** [comment]
It is not a good use of an option or coding time. Just sort the groups again after making a new one if you want them alphabetical. Does the option apply to all groups or just certain ones and their decedents? The existing sorting actions cover all cases and are easily accessible.
