### ISSUE TITLE
Clicking the pencil icon should edit the focused item

### ISSUE THREAD

**Issue by tredondo** [keepassxreboot/keepassxc#6188]
## Overview
I expected that clicking the :pencil2: icon while a group is focused, would edit that group. Instead, it edits the first entry from the group.

## Steps to Reproduce
1. Click on a group
2. Click on the pencil/edit icon

![Clicking the pencil icon should edit the focused item, not the entry](https://user-images.githubusercontent.com/10043369/109284111-95c55e00-77c3-11eb-9a7c-bf65818e6bc4.gif)

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.4
Revision: 34a78f0

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: KDE
Windowing System: X11

**Comment by droidmonkey** [comment]
Those icons are only for entries. If you hover over the icon it will show a tooltip. We won't be changing this behavior, thank you.
