### ISSUE TITLE
Database Security -> Advanced Settings checkbox not clickable

### ISSUE THREAD

**Issue by Sebi2020** [keepassxreboot/keepassxc#6190]
## Version
OS: Windows
Version: 2.6.4

## Expected behaviour:
After opening settings I should be able to change advanced settings by clicking the "advanced settings checkbox" in the lower left corner of the settings dialog.

## Current behaviour:
The checkbox is grayed out (disabled) making it impossible to open the advanced settings.

## Suggestion:
If you only provide advanced settings for encryption, you should consider to move the checkbox away from the statusbar into the "Encryption Settings" panel, because the current UI design creates the impression this checkbox has a global effect on the entire settings dialog.
Screenshot:
![image](https://user-images.githubusercontent.com/1862664/109360485-9c1d0e00-7887-11eb-9157-f50e512c4635.png)

**Comment by droidmonkey** [comment]
It's only meant for security, I agree it is awkward at best.

**Comment by droidmonkey** [comment]
Already being worked, closing this issue.
