### ISSUE TITLE
KeepassXC Crashed after adding secondary url advanced entry

### ISSUE THREAD

**Issue by delize** [keepassxreboot/keepassxc#6193]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
KeepassXC Crash

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )

This is not specific steps to reproduce, but, this is what caused the crash.
1. Open entry
2. Go to Advanced
3. Add secondary field url
3. Add url-address to secondary new 'url' field.

## Expected Behavior
Don't crash.

## Actual Behavior
After adding entry, database saved and UI crashed. UI was non-responsive and had to force quit the app twice to kill it.

## Context
[NOTE]: # ( Give us any additional information you may have. )

Database file is hosted on a Google Shared Drive.

```
KeePassXC - Version 2.6.4
Revision: 34a78f0

Qt 5.15.2
Debugging mode is disabled.

Operating system: macOS 10.15
CPU architecture: x86_64
Kernel: darwin 19.6.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
- libgcrypt 1.9.1

```
[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS

Attached log/dump of issue:
[keepassxc_crash.log](https://github.com/keepassxreboot/keepassxc/files/6053281/keepassxc_crash.log)

**Comment by droidmonkey** [comment]
Can you reproduce it reliably? Can you run a snapshot build https://snapshot.keepassxc.org and reproduce it? The snapshot will provide a readable stack trace to see where things are going wrong.

**Comment by delize** [comment]
> Where are you saving the file to (hard drive, icloud, usb stick)?

>> Database file is hosted on a Google Shared Drive.

I can't reproduce it reliably, if I do it again, the crash doesn't occur, and I can't find any stallout issues in system log (was trying to trace it to issues with Google Drive, or maybe the OS.

**Comment by droidmonkey** [comment]
Your stack trace does point to possibly multiple event loops being entered as a result of aynctask. Although I fixed that problem back in 2.6.2.

**Comment by delize** [comment]
I am not sure if this is a similar crash issue, and if not, I can create a new issue.

What happened was I was updating an entry in Chrome, saved via the browser plugin, and then reloaded a page. At that point, it said the DB needed to be merged (not sure why as I hadn't saved anything from an external machine). This is on version 2.6.4

[keepassxc-crash.log](https://github.com/keepassxreboot/keepassxc/files/6229103/keepassxc-crash.log)

**Comment by fertkir** [comment]
Fedora 37, also experiencing segmentation fault in both native & flatpak packages.
Here's what I've got from gdb:

```
Thread 343 "Thread (pooled)" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffabfff6c0 (LWP 13527)]
0x0000555555696fdd in Database::setKey (this=0x555557158450, key=..., updateChangedTime=<optimized out>, updateTransformSalt=<optimized out>, transformKey=<optimized out>) at /usr/src/debug/keepassxc-2.7.4-2.fc37.x86_64/src/core/Database.cpp:823
823         m_data.transformedDatabaseKey->setRawKey(transformedDatabaseKey);
Missing separate debuginfos, use: dnf debuginfo-install cairo-1.17.6-2.fc37.x86_64 pango-1.50.12-1.fc37.x86_64
```
