### ISSUE TITLE
FireFox / LibreWolf Browser Extension Does Not Connect Properly

### ISSUE THREAD

**Issue by ThisNekoGuy** [keepassxreboot/keepassxc#6194]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
I use LibreWolf (A modern fork of FireFox Quantum) and the extension behaves a bit wonky with connecting to the local database

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Install LibreWolf and KeePassXC
2. Enable linking between the two (FireFox button in the client app, to be clear, since LibreWolf isn't an option)
3. Attempting to connect the browser extension to the database fails or otherwise struggles to stay connected

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
A seamless connection between the two and the extension doesn't easily lose connection to the database

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
```"Key exchange was not successful"``` error messages or ```"check that browser integration is enabled"``` errors
KeePassXC then silently crashes(?) - The system tray icon disappears

## Context
[NOTE]: # ( Give us any additional information you may have. )
I had ```Lock databases after minimizing the window``` enabled

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.4
Revision: 34a78f0

[NOTE]: # ( Pick choices based on your environment )
Operating System: Arch Linux
Desktop Env: KDE
Windowing System: X11

**Comment by droidmonkey** [comment]
Use the custom browser option under the advanced settings of the browser plugin settings in keepassxc.

**Comment by ThisNekoGuy** [comment]
Ah, it seems to work
I don't see the location for what's suggested in the custom configuration field for LibreWolf specifically
(```~/.custom/config/librewolf/native-messaging-hosts/```)

However, the issue seemed to be that I actually hadn't noticed that I didn't have ```close to tray``` enabled, so KeePassXC was just terminating the process because it thought it was done :laughing:

**Comment by droidmonkey** [comment]
Great!
