### ISSUE TITLE
Last used database not being opened

### ISSUE THREAD

**Issue by Zeratul2k** [keepassxreboot/keepassxc#6195]
## Overview
First of all, thanks for the great program! I'm running it on Windows 10 and so far I've only found this issue. I have KeePassXC set to remember and load the last used database, as well as automatically launch on boot. After a restart, KeePassXC is not loading up the last used database.

## Steps to Reproduce
1. Have the settings set up as outlined in the attached images.
2. Reboot Windows.

## Expected Behavior
The last used database should be loaded automatically.

## Actual Behavior
Have to select the database again (it's at least saved in the recently used list, but NOT loaded).

## Context
The database file is in a folder inside the User's Documents and the issue is happening in two different Windows 10 computers with very similar setups.

KeePassXC - Version 2.6.4
Revision: 34a78f0

Qt 5.15.2
Debugging mode is disabled.

Operating system: Windows 10 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.19042

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
- libgcrypt 1.9.1-unknown
![User interface](https://user-images.githubusercontent.com/826347/109371350-7a655c00-7872-11eb-8bf6-40c2e912191a.png)
![Startup options](https://user-images.githubusercontent.com/826347/109371351-7afdf280-7872-11eb-8d16-50cbf5ab25ed.png)

**Comment by droidmonkey** [comment]
Are you just quitting keepassxc with the database open/locked or are you closing the database (ie, the welcome screen shows) then quitting keepassxc? This is not an issue for me or anyone else so far.

**Comment by Zeratul2k** [comment]
I'm shutting down/rebooting the computer with the database and KeePassXC itself still open. I don't usually close every single app when I'm going to shut down.

**Comment by mibcat** [comment]
Same behavior on my Linux Mint system. I therefore went back to version 2.6.2  which is working as expected.

Regarding 2.6.4: 
- there is no difference if the database is closed or not before the program is terminated.
- I'm using the app image.

**Comment by Zeratul2k** [comment]
mibcat's comment made me go and try a previous version to see if it still happened.

Removed 2.6.4 then installed 2.6.3, which behaved as expected, opening the database after a program exit/reboot. Then tried updating back to 2.6.4 WITHOUT uninstalling 2.6.3, and it seems to be working at the moment. I'll try again using a VM, but so far it seems the issue presents itself with a fresh 2.6.4 install only.

**Comment by Zeratul2k** [comment]
Did the test on a VM as I mentioned on my last comment. Installed 2.6.4 on a fresh install of Windows 10 and couldn't reproduce the error. I'm currently scratching my head trying to understand what could have caused the same erroneous behavior in 2 different computers. Thankfully, I've only corrected the issue in 1 of them so far, so if anyone wants to help me investigate, I can give it a try. If not, I think this can be closed.

**Comment by droidmonkey** [comment]
Does the error occur when you start keepassxc normally or only when it's auto started on login?
