### ISSUE TITLE
Mouse cursor doesn't change to resizer icon in KDE Plasma Breeze

### ISSUE THREAD

**Issue by tredondo** [keepassxreboot/keepassxc#6197]
## Overview
I expected when mousing over the column divider, to see a cursor in the shape of a resize icon. The cursor doesn't change shape. This is with the default Plasma style and cursors, Breeze.

![Cursor doesn't take resizer shape in KDE Plasma](https://user-images.githubusercontent.com/10043369/109385608-2c178380-7899-11eb-9e03-07b9c3acfe53.gif)

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.4
Revision: 34a78f0

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: KDE
Windowing System: X11

**Comment by droidmonkey** [comment]
This behavior is defined by qt not by us. It's most likely your environment though.

**Comment by tredondo** [comment]
I can see the resizer over Dolphin columns. What debug information can I provide?
Qt 5.15.2  
KDE Frameworks 5.79.0

**Comment by droidmonkey** [comment]
Are you running keepassxc as a snap or flatpak or appimage?

**Comment by tredondo** [comment]
Compiled from source. A possibly related issue is that if I set a shortcut key in the KDE menu editor (Command `/home/arond/.local/usr/local/bin/keepassxc`, no other special settings), it doesn't launch or bring to the foreground KeePassXC, no matter what the shortcut is. Other apps do respond to those shortcut keys (e.g. Firefox), and launching KeePassXC from the launcher based on that menu item does work.

**Comment by droidmonkey** [comment]
This is not something we are able to fix. Please file a bug report with Qt.
