### ISSUE TITLE
Unable to select database that's filename starts with dot on macOS Big Sur

### ISSUE THREAD

**Issue by maximko** [keepassxreboot/keepassxc#6198]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Try to open a database
2. Navigate to a file starts with dot (hidden file)
3. File is grayed out so cannot be selected and opened

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
I expect to select any file regardless of its filename.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Unable to select any file that's filename starts with dot (hidden file) because file is grayed out in file selection dialog.
![image](https://user-images.githubusercontent.com/633363/109390702-42b6ec80-7924-11eb-9f8c-263f1aca8e3f.png)

## Context
[NOTE]: # ( Give us any additional information you may have. )
I use hidden database and key files and I can't open it in recent versions of KeePassXC.

KeePassXC - Version 2.6.2
Revision: e9b9582

Operating System: macOS Big Sur (any version)

**Comment by droidmonkey** [comment]
#5296
