### ISSUE TITLE
Add Option for Changing Name & Location Of Backup

### ISSUE THREAD

**Issue by MattTheTechLV** [keepassxreboot/keepassxc#6199]
## Summary
I know that this has been asked for before, and I also know the Thread always ends up getting swarmed with people who would prefer a more robust backup system in KeePassXC. I completely Understand the reasons for keeping KeePassXC focused on what is was designed for, and leaving the more feature rich backup system to a Program tailored to that.

It just would be EXTREMELY helpful if we could be given the option within KeePassXC to Change the Location of the Database Autobackup, and Change the Name Of the Database Autobackup. There are multiple reasons I keep running into needing this, and I don't want to make this Post an Essay, but just to be able to specify at the very least a different name for the Autobackup, and if possible a different location as well, that would be incredibly helpful.

There is no need to make the autobackup feature more robust in terms of allowing it to save multiple versions, I completely understand that would create other issues, but with just the One Overwritten Auto Backup we get, just to be able to specify the Location it backs up to, and the Name it Uses, gives us so much more flexibility for implementing our own backup system, and I am hoping that wouldn't be too much of a pain to add. 

I know there are more than a few of us who want the ability just to do this, and then our own backup systems that we implement can take over from there. I understand time is money, and its been a while since I donated, so I will drop a $20 in the bucket, I know thats not much but I am hoping a few others who want this feature will do too, and hopefully make this diversion worth your time.

Thank You for an awesome Product!

## Examples
I took this from someone who asked for this feature before and added a word to it.

![KeePassXC Backup Name and Location Suggestion](https://user-images.githubusercontent.com/61740449/109394774-8b978280-78dd-11eb-8864-60a2963941c5.png)

## Context

There are more than a dozen different scenarios where this would come in handy, but for just one example, having One Database Stored on a Network Share Locally, where a few different Workstations access from the same file, and You want each Workstation to have the ability to autobackup, but since all autobackups will carry the same name in the same location, you get an error every time a change is made because the file already exists. There are other ways around this issue, this is just 1 scenario. Another is wanting to have a folder Other than your Database Folder Monitored by your backup solution For it to take the backups in that folder and catalog them, without also cataloging the main database every time. And the ability to be able to change the name allows a ton more possibilities. I know there are other ways to go about this, but having this one feature would help so much. Thank You for your consideration. I will actually shut up now.

**Comment by droidmonkey** [comment]
#3279

**Comment by MattTheTechLV** [comment]
Sorry, does this mean you don't find this idea worthwhile? Since the Other Thread was closed I thought it best to open a new One. I know that one got hijacked with people begging for Things you aren't interested in implimenting, but having just this one Feature would be amazing. Still going to donate, still love the product, just would love for this to be considered.

**Comment by droidmonkey** [comment]
The one I linked is open

**Comment by droidmonkey** [comment]
Thank you for your support, just don't need multiple issues for the same feature or bug. I tend to rapidly clean issues to prevent bloat in our issue list. Your feedback above will be incorporated into the feature.

**Comment by MattTheTechLV** [comment]
> The one I linked is open and slated for inclusion in 2.7.0.

I did not realize that, I clicked it and I thought I saw it was that same closed thread, but I am probably just blind. Appreciate it! (So we will be able to Change the Location and Filename?)

And Its my pleasure to support, you do great work!

**Comment by d-faure** [comment]
In the same mood (but this should be a rather limited modification), couldn't the last chosen location for manually triggered database backup made persist?

For now, when I choose to "Merge from Database...", the last used location is kept in the file selector, and merging is quite comfortable for getting updates from the same source.

This is sadly not the case when making backup, the proposed directory being always the one of the last used database.
