### ISSUE TITLE
Additional attributes GUI does not scale on linux

### ISSUE THREAD

**Issue by Elyjax** [keepassxreboot/keepassxc#620]
## Expected Behavior
The left box should scale to display the full name of the attribute. This is the case on Windows.

## Current Behavior
There is no scale and no way to increase the size of the box thus it is difficult to read entries name.

![keepassxc](https://cloud.githubusercontent.com/assets/6034697/26755145/c4de2074-4887-11e7-860d-a5070c7b514a.png)

## Your Environment

* KeePassXC version/commit used: 2.1.4
* Qt version : 5.8.0
* Operating System and version: Arch Linux

**Comment by TheZ3ro** [comment]
I can't find the issue but I'm pretty sure this is fixed in develop. @droidmonkey can you confirm?

**Comment by Elyjax** [comment]
I have just built keepassxc with the latest commit and the problem is indeed resolved :).
By the way, I noticed some UI improvements. Keep up the great work !

**Comment by TheZ3ro** [comment]
Thanks! :)
