### ISSUE TITLE
Use Drag/Drop to target entry-level Auto-Type

### ISSUE THREAD

**Issue by wereia** [keepassxreboot/keepassxc#6201]
## Summary
Just an moonshot idea. What about to use drag&drop to perform 'entry level auto-type' instead of using the last focus? 

This could be more straight forward from the workflow, like copy&paste, but without the risk if a system clipboard. 

Using the last focus is something which I never feel 100% comfortable with. Especially web sites can change the focus while your on the page as a normal function of their site. 

I'm not sure if this is possibly technically. But I image it this way

1. 'drag' on entry in KeypassXC
2. 'drop' over an input filed in a certain window
3. the window and input gets focused and auto-type is performed

My workflow for a web site would be this:
- have your web site open
- open KeypassXC
- drag on entry into from KeypassXC into the desired input field on the web site
- password is typed into the field

Instead of:
- have your web site open
- open KeypassXC
- click in input field on the web site
- bring KeypassXC in front
- perform 'entry level auto-type'
- focus is switched to the web site and password is typed into the field

Besides technical questions. One downside could be that it's more difficult or not possible to show a dialog (introduced in v2.7) to confirm the 'entry level auto-type' (against human error), compared to the last focus method? 

On the one hand, drag&drop is not know to be the least error prone action, but on the other hand it will be straight forward and not using focus targets 'of the past'. But as said. It's a moonshot and not a well thought out suggestion.

**Comment by droidmonkey** [comment]
I don't think this is possible just by the nature of how drag/drop works. On a drag start, the sending application builds a mime data package. On drop the receiving application unpacks the mime data package and transfers the data. There is no communication btwn the two apps.

**Comment by wereia** [comment]
All right, seems not like a good idea then. Thanks for thinking about it anyhow. Just wanted to pass the idea one time.
