### ISSUE TITLE
Created and modified time not preserved when drag/drop entries & groups

### ISSUE THREAD

**Issue by dfv54gdmsnsecfzsmfwhermkml** [keepassxreboot/keepassxc#6202]
## Overview
When entries are moved from first database to second database, the created and modified times are not preserved.

## Steps to Reproduce
1. Create 2 keepass databases with the default setting.

2. Create on first keepass database an entry and 1 minute later modify this entry. now you have 2 different time under Created and Modified.

3. Open the second database and move the entry from first database to second database.

4. The moved entry has now the current transfer time under created and modified.

## Expected Behavior
The moved entry has the original created and modified time and not the transfer time is taken.

## Actual Behavior
The moved entry has now the current transfer time under created and modified.

## Context
[NOTE]: # ( Give us any additional information you may have. )
The same problem happens even if I don't move but copy with Ctrl key.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC -  Version 2.6.4
Revision: 34a78f0

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 8/10
Desktop Env: xxx
Windowing System: xxx

**Comment by droidmonkey** [comment]
This also affects drags between groups of the same database
