### ISSUE TITLE
2.6.4 crashes on startup on macos Catalina (10.15.6), x86

### ISSUE THREAD

**Issue by DanielManhattan** [keepassxreboot/keepassxc#6203]
## Overview

KeepassXC 2.6.4 on macos Catalina 10.15.6 (19G73) on x86 macbook pro 6,2 crashes when launched. The problem seems to be related to code signing (see context for more info).

## Steps to Reproduce

1. Start KeepassXC 2.6.4 on macos Catalina 10.15.6 (19G73) on x86 macbook pro 6,2.

## Expected Behavior

KeepassXC launches.

## Actual Behavior

The program crashes.

## Context

I've updated KeepassXC from 2.6.1 to 2.6.4 on macos Catalina (10.15.6 (19G73)) through homebrew. Launching the application does not start it. Instead, a native macos popup "KeepassXC quit unexpectedly." is presented after ~10s delay. Looking at "Console" application's crash report log for KeepassXC entry, exception type is specified as "EXC_CRASH (Code Signature Invalid)", exception codes is "0x0000000000000000, 0x0000000000000000", exception note is "EXC_CORPSE_NOTIFY", termination reason is "Namespace CODESIGNING, Code 0x1".

Redownloading the x86 binary through the website and installing that results in the same problem and the same "Console" crash report output.

The hardware is macbook pro 6,2 (mid-2010) with macos Catalina installed with the help of "macos Catalina patcher" (it allows installing news macos versions on older, officially unsupported macs, as in this case).

KeePassXC - 2.6.4
Revision: none

Operating System: macos Catalina (10.15.6 (19G73))

**Comment by DanielManhattan** [comment]
Addendum:

I've tried earlier versions of KeepassXC on the aforementioned system (the tagged releases on GitHub). The latest version that worked was only 2.5.3, all the newer ones failed to launch with exactly the same log info. I've also checked 2.5.1, that also worked. Could the bug be related to the pull request #4564?

**Comment by droidmonkey** [comment]
I can assure you we won't have a crash on all macs since that pr. Completely remove the application and install from scratch. Make sure you restart as well to be sure.
