### ISSUE TITLE
Brave Browser Integration - how to enable?

### ISSUE THREAD

**Issue by PW2000** [keepassxreboot/keepassxc#6212]
Hi.  Using the Brave Browser on Mac (Big Sur) and KeePassXC latest version.

Have checked the box to enable Brave Browser but I keep getting the message:

`Cannot connect to KeePassXC. Check that browser integration is enabled in KeePassXC settings.`

I've tried using a Custom path, and entered the location of the org.keepassxc.keepassxc_browser.json file, restarted both Brave and KeePassXC, but still Brave won't connect with KeepassXC.

What am I missing?

Thank you.

**Comment by droidmonkey** [comment]
Choose chromium instead

**Comment by grzegorz-borczuch** [comment]
> Brave switched their configuration location on some platforms.

@droidmonkey Would it be possible to add some note about this fact to online support/FAQ of KeePassXC?

**Comment by droidmonkey** [comment]
Yah we can add it to the wiki troubleshooting page. We aren't going to "fix" it since Brave can suddenly decide to use their own folder again. It's better to give both options via the two checkboxes.

**Comment by droidmonkey** [comment]
I added it here https://github.com/keepassxreboot/keepassxc-browser/wiki/Troubleshooting-guide#macos
