### ISSUE TITLE
Edit-entry dialog ignores Home,End keys on MacOS.

### ISSUE THREAD

**Issue by Huge** [keepassxreboot/keepassxc#6213]
## Overview
Edit entry dialog ignores home/end keys on MacOS( Big Sur).

## Steps to Reproduce
1. Open entry with name consisted of multiple words. 
2. Arrow keys move cursor, home/end does nothing.

## Expected Behavior
Move to start/end of the line

**Comment by droidmonkey** [comment]
This is a qt bug
