### ISSUE TITLE
--pw-stdin doesn't work on Linux

### ISSUE THREAD

**Issue by 532910** [keepassxreboot/keepassxc#6214]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
I'm trying to unlock it with pass:
```
% pass keepass | keepassxc --pw-stdin db.kdbx
```
But `echo` also could be used to replicate this:
```
% echo secret | keepassxc --pw-stdin db.kdbx
```
or:
```
% keepassxc --pw-stdin db.kdbx
Database password:
type_password_here_and_hit_return
```

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Opened database

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Just a greeting window:
![image](https://user-images.githubusercontent.com/14617699/109660020-6c1c8600-7b79-11eb-8c18-4c1ba42e2936.png)
and clicking the db just asks for the password:
![image](https://user-images.githubusercontent.com/14617699/109660193-a128d880-7b79-11eb-9bc1-e4cc513673fb.png)

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC 2.6.2 from debian sid
Revision: e9b9582

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: i3
Windowing System: X11

**Comment by droidmonkey** [comment]
Provide the full path to the database on the command line.

**Comment by 532910** [comment]
My fault! It looks like I provided the wrong path.
