### ISSUE TITLE
Import & Read Encrypted TOTP .JSON File Fromat (Aegis)

### ISSUE THREAD

**Issue by giwrgosmant** [keepassxreboot/keepassxc#6218]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
Hello,
I am using [Aegis Authenticator](https://github.com/beemdevelopment/Aegis) as 2 Step Authenticator (TOTP) in my Android. I can export the vault in encrypted .JSON file format so If I switch or format my device, to be able to restore everything without have to set everything again.
My suggested feature is, if it's possible KeePassXC to can be create a section and on this section to be able to import and read these encrypted .JSON files format from the Aegis so I can see and use the codes from my Desktop.

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )
Something like that: 
![2021-03-02 21_05_44-screenshot7 png (PNG εικόνα, 1320 × 2640 εικονοστοιχεία) - Σε κλίμακα (49%)](https://user-images.githubusercontent.com/51835189/109701020-3b4d4880-7b9b-11eb-8f7d-e468849bbe5b.png)

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
I will be able to check my TOTP from KeePassXC without having to look on my Android device when I am on my Desktop.

**Comment by droidmonkey** [comment]
Is there a published spec for this encrypted json?

**Comment by giwrgosmant** [comment]
> 
> 
> Is there a published spec for this encrypted json?

I am not relevant with coding but I know the vault is encrypted with AES-256-GCM.
The code can be found [here](https://github.com/beemdevelopment/Aegis), more specific [here](https://github.com/beemdevelopment/Aegis/tree/master/app/src/main/java/com/beemdevelopment/aegis), if you want to take a look since I don't have the knowledge for this.
I can also contact the dev of Aegis and ask him about the spec of the encrypted json.

**Comment by alexbakker** [comment]
We received an email from @giwrgosmant, asking us to chime in here and provide some details. Aegis' vault format is documented here: https://github.com/beemdevelopment/Aegis/blob/master/docs/vault.md. Happy to answer questions if any come up.

**Comment by droidmonkey** [comment]
Interesting cipher choice. This will require the transition to Botan to support.

**Comment by droidmonkey** [comment]
We won't be implementing this.

**Comment by beyond9thousand** [comment]
If its an unencrypted `.json` file, what then? Is it possible to import the TOTP list?

**Comment by droidmonkey** [comment]
You have to convert it to csv

**Comment by regisb** [comment]
To anyone stumbling on this... I don't know how to format a CSV file for import in Keepassxc, but decrypting an encrypted Aegis backup is pretty easy with the following script: https://github.com/beemdevelopment/Aegis/blob/master/docs/decrypt.py

**Comment by Ember-ruby** [comment]
> You have to convert it to csv

would importing at least the decrypted version be considered
