### ISSUE TITLE
Snapshot version doesn't notify abount new released versions.

### ISSUE THREAD

**Issue by pmajkutewicz** [keepassxreboot/keepassxc#6220]
## Overview
I had snapshot version of KeePassXC... after like month or two using it I've clicked "Check for updates" - no updates found.
After going on main page I've founded out that ther is already 2.6.4.

IMO "Check for update" should show available update to relased version.

## Steps to Reproduce
1. Download snapshot version
2. Wait for new release
3. Click Help -> check for updates

## Expected Behavior
Should notify me about new version.

## Actual Behavior
No new updates

## Context
I'm using AppImage.

[NOTE]:
Operating System: Linux
Desktop Env: Cinnamon
Windowing System: X11

**Comment by droidmonkey** [comment]
Which version of the snapshot were you using?

**Comment by pmajkutewicz** [comment]
@droidmonkey Oh... forgot about this. Sorry.
What I'm expecting (it may be something unusual)
- I'm downloading snapshot version (cause I want to get feature that I'm interested) (not that I'm snapshot user and wan't latest and greatest)
- I'm expecting that I'll be informed that there was release of stable version with that feature. - so I'm able to back to stable branch again.

Agree that info about new snapshot is pointless. But info that new "normal" version was released is important for me. After that I'll be able to back to stable versions of software.

I believe that for snapshot users information that new "stable" version is available will not be annoying.
