### ISSUE TITLE
Browser integration fails repeatedly after two or three uses.

### ISSUE THREAD

**Issue by iansebryk** [keepassxreboot/keepassxc#6224]
## Overview
using Firefox DevEd with the KeePassXC-Browser plugin.  it has become virtually useless as it will just stop working after two or three uses.  no error messages, no popups, nothing.  i cannot even force it to fill in entries via the right-click menu.  the icon indicates it is activated, it is connect to the database, and the authorization window still pops up from time to time.  but no credentials are entered.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. unlock database
2. click green key button on right of input field to enter login information (as usual)
3. works twice, maybe thrice, but after that... it does nothing.

## Expected Behavior
i expect it to enter the saved credentials!

## Actual Behavior
it does nothing.

## Context
i have tried everything.  locked, unlocked, browser refresh, relaunch... all fail.  it just stops working.  this happens in Firefox DevEd, Firefox Nightly, and just plain Firefox.  this has been an odd problem for a while now, but i've recently been using it much more frequently for work and it's now unbearable.

occasionally, i will reload a page in frustration and it will magically start working again.

i've also found that unless the URL is *exactly* identical, it won't work either.  wildcards would be nice...
eg.  https://somesite.com/login    ->  works
       https://somesite.com/login?blahblahblah   ->  fails utterly

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.6.4
Revision: 34a78f0

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 10 Pro

**Comment by droidmonkey** [comment]
Need more specific details to understand where the failure lies. It is not true that the url needs to be exact, just the domain and subdomain. Http vs https also matters

**Comment by iansebryk** [comment]
not sure how to answer that...  what specifics are you looking for?  i can't give you actual URLs because of security.  are you looking for workflow? other addons?  this is frustrating in that i literally don't know what else to add.  it just stops working...  :P  and i've tried several flavours of Firefox to the same end result.  why it stops, i have no idea.  and there's no rhyme or reason to the URLs either.  the same site i can get credentials for just fine one minute, 20mins later just won't.  restarting browser often works, but not always... maybe i'm haunted??  lol.

i understand that you need more details, but i don't know what else i can give you other than a description of how i use it.  the tools are the same: KeePassXC and it's brower plugin.  and i appreciate the insanity of asking you to help me get you information...

exact URLs are sometimes the only way i can get this to work most of the time.  it doesn't recognize modals very well, or at least it breaks most often with modals.  the icon shows up in the input fields, but it almost never fills in correctly.  the haunted theory is beginning to look more valid...  :P

anyway.  i'll try and be more observant while i develop and if you think of anything specific... *sigh*

**Comment by droidmonkey** [comment]
Exact urls is very important for us to see if it is a website issue. If you can't provide then you'll have to self service. You could also provide the console output from the browser developer tools when it fails to provide credentials so we can see any errors or warnings from the extension. Would you be able to diagnose your own problem with the information provided thus far?

**Comment by varjolintu** [comment]
Is there any Anti-Virus or Anti-Malware software that could interfere with the extension's Native Messaging API?

And actually I'd recommend using simpler URL's like `https://login.example.com` or `https://example.com/login/page` and not exact URL's with different paths etc.

**Comment by iansebryk** [comment]
i'll keep a log over the next several weeks and filter out secure URLs.  hopefully we can get this sorted.  thanks for being clear about what you're needing.  i'll do my best to provide.

**Comment by droidmonkey** [comment]
Any update?

**Comment by doomsy** [comment]
I too have observed this behaviour (though using Brave with chrome extension, on OSX). My initial thoughts are that the browser is disconnecting from the database. Restarting the browser or reloading the plugin seem to reconnect. I'll post more if I figure out anything more specific.
