### ISSUE TITLE
Get DB file location from an environment variable

### ISSUE THREAD

**Issue by den-is** [keepassxreboot/keepassxc#6225]
## Summary
Instead of typing path to database each time on CLI it might be convenient to get the path to a database file using an environment variable.
IMO, first of all, it is secure; the path to the database is not stored in CLI history.
But the actual story is that I use different databases for different projects.
And it will be easier to determine DB using env vars per project - in that case, [direnv](https://github.com/direnv/direnv) project is especially useful.

## Examples
```sh
export KEEPASSXC_DB="~/path/to/db"
keepassxc-cli clip site1/maindb
```

**Comment by droidmonkey** [comment]
```
export DB1="passwords.kdbx"
keepassxc-cli clip $DB1 entry1

**Comment by rvl** [comment]
That solution is less usable if you need to use more options such as `--yubikey` or `--key-file`.

I ended up writing a wrapper script:
```bash
#!/usr/bin/env bash

# Inserts $KEEPASSXC_YUBIKEY and $KEEPASSXC_DATABASE into the
# keepassx-cli command line, if they are set.

db_cmds=(add analyze clip db-info edit export import locate ls mkdir mv rm rmdir show)

needs_db() {
  local cmd
  for cmd in "${db_cmds[@]}"; do [ "$cmd" = "$1" ] && return 0; done
  return 1
}

args=()
for arg in "$@"; do
  args+=( "$arg" )
  if needs_db "$arg"; then
    if [ -n "$KEEPASSXC_YUBIKEY" ]; then
      args+=( "--yubikey" "$KEEPASSXC_YUBIKEY" )
    fi
    if [ -n "$KEEPASSXC_DATABASE" ]; then
      args+=("$KEEPASSXC_DATABASE")
    fi
  fi
done

exec keepassxc-cli "${args[@]}"
```

**Comment by droidmonkey** [comment]
You could also just combine the yubikey and key file options with the DB1 env var...

`export DB1="database.kdbx --yubikey 2 --key-file key.keyx`

**Comment by den-is** [comment]
First of all, I absolutely appreciate the work and energy you put into that incredible and vital product. But I want to express my opinion regarding such feature requests and responses. No offense, please.
While working with hundreds of CLI apps on daily basis, and seen thousands throughout my career in the field, I know how to hack arguments into CLI and use crutches to achieve desirable goals.
The same above experience gives me a feeling (probably biased) on if how modern CLI tools should look like, behave and interact with a user. KeePassXC CLI looks like a tool from the 90s.
There was a very similar request to provide ENV_VAR for DB password that was declined with better legit arguments regarding security issues of such method.

I sincerely sorry, that I'm no able to contribute actual code PR instead above rant. But a review is a review.
Feel free to close the ticket, if it is not appropriate.

**Comment by droidmonkey** [comment]
Can you name a couple of the modern amazing cli tools that you have used so we can glean some insight into what makes them so amazing? I didn't close this request because it has some validity, but you can clearly achieve your end goal with existing shell capability. Not sure what's wrong with that at all.

**Comment by droidmonkey** [comment]
I recognize that our cli output is not good compared to other tools using tables and colors and other special methods. That are definitely needs improvement to come up to a modern standard. I want to focus on the input side of the house, I am genuinely curious what you have seen across the tools you used and what makes the best ones so special.

**Comment by rvl** [comment]
I would like to second @den-is - I too appreciate the work and energy that @droidmonkey and all other contributors have put into this tool. It's not an understatement to say that keepassxc is one of the foundation stones of my online security.

The `$DB1` solution works, and actually I did not consider using an env variable containing multiple args.

But I think it would be easier for the user who is typing lots of keepassxc-cli commands if they did not even need to put `$DB1` on the command line. In my situation, I only have one database, so I would like to configure it globally -- e.g. in `~/.profile`.

A common successful CLI which works like this is `git` (although in general, the git UI is not especially easy). You can configure the database with the `--git-dir=<path>` option or the `GIT_DIR` environment variable ([ref](https://git-scm.com/book/en/v2/Git-Internals-Environment-Variables)).

In any case, this isn't high priority for _me_. I have my wrapper script, which works.

**Comment by den-is** [comment]
@droidmonkey git, ansible, various hashicorp projects, Kubernetes binaries, most of the cloud-native apps, web frameworks Laravel, Django, ... etc. The list is virtually endless.

**Comment by phoerious** [comment]
I don't think we will implement this. You can always use environment variables on the cmdline itself or use xargs etc.
