### ISSUE TITLE
Corrupted database with no reason

### ISSUE THREAD

**Issue by deoomen** [keepassxreboot/keepassxc#6226]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
I'm using KeePassXC for years and never encountered a problem. But now after using same kdbx file for almost half year it won't open. I'm 100% sure that password is correct. Tried on same machine with two backups (one from pendrive, one from google drive) and same issue. Database won't open. I also tried on other machine with the same kdbx file (one original and two backups) with no luck.
I have seen a few similar reports that were closed with suspected processor or RAM problems, so it will probably be similar here, but I still report that something like this occurs.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Create database.
2. Use it every day.
3. One day everything blow up.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Unlock database.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Showing error: 
"Error while reading the database: Invalid credentials were provided, please try again.
If this reoccurs, then your database file may be corrupt. (HMAC mismatch)"

## Context
[NOTE]: # ( Give us any additional information you may have. )
1st machine: i5 8gen, 16 GB RAM, Ubuntu 20.04.
2nd machine: i5 4gen, 16 RAM, Ubuntu 20.04.
Original kdbx file: used every day.
First backup: backuped 2 weeks ago.
Second backup: backuped 2 month ago.
All three files are dead.
Also tried with KeePassXC v2.6.3 but no luck.
Maybe some problem is with chars used in password? I have got one nonstandard char: `ł`.
Yesterday I shutdown my system without closing KeePassXC window also database was unlocked.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.4
Revision: 34a78f0

Qt 5.12.8
Debugging mode is disabled.

Operating system: Ubuntu 20.04.2 LTS
CPU architecture: x86_64
Kernel: linux 5.8.0-44-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- libgcrypt 1.8.5

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux - Ubuntu 20.04
Desktop Env: Gnome

**Comment by droidmonkey** [comment]
Database stored on USB thumbdrive?

**Comment by deoomen** [comment]
One copy is stored on USB drive, another one in cloud (manual sync by copy-paste).
Yea, the very first copy on Gdrive works (of course without many passwords added after...). But all others are broken. I emphasize that a few days ago everything was working fine. "Broken" databases won't open on any other devices (tried on phone and one more PC).

**Comment by phoerious** [comment]
So the one on the thumb drive is broken? That's 99% the thumb drive's fault.

**Comment by droidmonkey** [comment]
There is nothing further we can do here, recommend retrying your Google drive backups to see if you can get a more recent copy.

**Comment by deoomen** [comment]
Sorry for late answer. I was busy. 
No. It was not fault of thumb drive. All others copies also do not work. Except the first one from Google drive file history.

**Comment by ralaud** [comment]
Hi, sadly I got the same error today, I was using the same database since a year.

I did only set a password for encryption. I did set up a 5 minute time limit for automatically closing the database. After like 10 minutes I had to look up a password again and I got the HMAC mismatch error..
While I was working, I did not reboot my pc and was not updating my system. Before the database closed, I just added few new accounts.

KeePassXC - Version 2.6.4
Revision: 34a78f0

Qt 5.12.7
Debugging mode is disabled.

Operating system: openSUSE Leap 15.2
Desktop Env: KDE
CPU architecture: x86_64
Kernel: linux 5.3.18-lp152.75-preempt

Enabled extensions:
- Auto-Type
- Browser-Integration
- SSH-Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret-Service-Integration

Cryptographic libraries:
- libgcrypt 1.8.2

**Comment by droidmonkey** [comment]
In all my debugging and abusing of keepassxc I have never corrupted my demo database. The most likely cause of "corruption" is actually an invalid password. Unless you have bad RAM (seen that) or a USB thumb drive that fails to write data properly.
