### ISSUE TITLE
Auto-type not working on different keyboard layout

### ISSUE THREAD

**Issue by aardbol** [keepassxreboot/keepassxc#6227]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
Auto-type types wrong characters as if it's using a different keyboard layout

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Have two different keyboard layouts: one qwerty (laptop keyboard), one azerty (attached keyboard)
2. Set kb layout to azerty
3. Perform auto-type and see that wrong characters are entered in the fields
4. Set kb layout back to qwerty and do it again: it works

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
auto-type should enter the characters as how they are stored in the database

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION
Revision: REVISION
`KeePassXC - Version 2.6.4
Revision: 34a78f0

Qt 5.15.2
Debugging mode is disabled.

Operating system: Manjaro Linux
CPU architecture: x86_64
Kernel: linux 5.10.19-1-MANJARO

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- libgcrypt 1.9.2-unknown
`

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: KDE
Windowing System: X11

**Comment by hifi** [comment]
#6247 should fix this. If you have the possibility to test it would appreciate that a lot.

**Comment by aardbol** [comment]
I would, but I'm not sure what and how to test though

**Comment by hifi** [comment]
Added an AppImage for testing available from the PR comments. Thanks.
