### ISSUE TITLE
[Feature Request] Show expired passwords on database open

### ISSUE THREAD

**Issue by teldon** [keepassxreboot/keepassxc#623]
Could you please add an option to show a list of expired passwords when you open a database?  It's nice to know if any of the passwords I've set to expire have.

**Comment by TheZ3ro** [comment]
This is related to #551, adding for the wishlist for 2.3.0

**Comment by teldon** [comment]
Thanks.

**Comment by droidmonkey** [comment]
I like this idea! Perhaps this would be better handled as a special search that dynamically found and displayed expired entries on the push of a button.

**Comment by droidmonkey** [comment]
Closed in favor of #551

**Comment by ba32107** [comment]
Hi!

I badly need this feature. It was closed almost a year ago, but #551 is still not implemented. Can we have this feature meanwhile?

Thanks,
Balazs
