### ISSUE TITLE
KeePassXC-Browser and Firejail fail with AppImage

### ISSUE THREAD

**Issue by nidamanx** [keepassxreboot/keepassxc#6230]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. start KeePassXC
2. start Firefox or Chromium with KeePassXC-Browser (associated in KeePassXC)
3. try to get a password from the database

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
All should work as in installation from Debian repository
Versiion 2.5.4+dfsg.1-1~bpo10+1

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

Error from KeePassXC-Browser in web browser 

> KeePassXC-Browser has encountered an error:
> Message encryption failed. Is KeePassXC running?

After pushing Reload Button

> KeePassXC-Browser has encountered an error:
> Key exchange was not successful.

## Context
[NOTE]: # ( Give us any additional information you may have. )
All is fine if I use KeepassXC from Debian repository
Versiion 2.5.4+dfsg.1-1~bpo10+1

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.4
Revision: 34a78f0
Distribution: AppImage
KeePassXC-Browser - Version 1.7.6

[NOTE]: # ( Pick choices based on your environment )
Operating System: Debian 10 GNU/Linux
Desktop Env: Gnome
Windowing System: X11

**Comment by nidamanx** [comment]
Found a solution.
Disable and enable again all browsers integration in KeePassXC

**Comment by phoerious** [comment]
It may fail if you move the AppImage to a different place. Restart should fix that.

**Comment by nidamanx** [comment]
Thanks!
It was the first time I used this app as a AppImage,

By the way, I'm having problems integrating firejail
If I use firejail for KeePassXC and Firefox and/or Chromium, plugin fails to connect to the database.
If I use only KeepassXC in firejail and web browsers free, all is fine.
Could it be a socket problem? Where is it? in /tmp?
If we will find a solution, I will submit the correct profile to firejail

**Comment by phoerious** [comment]
The socket should be in $XDG_RUNTIME_DIR.

**Comment by nidamanx** [comment]
For normal .deb install, yes. But for AppImage I can see
`$XDG_RUNTIME_DIR/org.keepassxc.KeePassXC.BrowserServer`
and 
`/tmp/keepassxc-username.lock`
`/tmp/keepassxc-username.socket`
Can you confirm, please?

**Comment by phoerious** [comment]
The ones in /tmp are only for single-instance mode and have nothing to do with the browser extension.

**Comment by nidamanx** [comment]
So, I cannot find the socket.
Where else could it be?

**Comment by phoerious** [comment]
The browser needs to be able to start keepassxc-proxy, which will create the socket.

**Comment by nidamanx** [comment]
So, something more clear.
We have:
`$XDG_RUNTIME_DIR/org.keepassxc.KeePassXC.BrowserServer`
And this is exactly as the .deb version (and all is fully working with deb).

I think the plugin needs to reach a part inside the AppImage
Debugging I got and error in browser "Cannot mount AppImage, please check your FUSE setup"
I already have FUSE loaded in modules, but I could see the mount in /tmp only in I mount manually.
Maybe something related to this? 
[AppImageKit](https://github.com/AppImage/AppImageKit/wiki/FUSE)

**Comment by phoerious** [comment]
The AppImage needz to be started twice. Once by you and once by the browser, but with a different entry point.

**Comment by tomm87** [comment]
@nidamanx and others with the same problem:

If you still can't use the KeePassXC web browser extension in a Firejailed Firefox, the workaround at #11021 might help.
