### ISSUE TITLE
"Always on Top" setting automatic disabled after closing KeePassXC

### ISSUE THREAD

**Issue by giwrgosmant** [keepassxreboot/keepassxc#6231]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
"Always on Top" setting, automatic disabled after closing KeePassXC.
![Always_on_Top](https://user-images.githubusercontent.com/51835189/110140874-3bd52180-7ddd-11eb-960b-e6347597e357.png)

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Enable Always on Top (View > Always on Top)
2. Close KeePassXC
3. Open KeePassXC and "Always on Top" is disabled.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Always on Top should stay enabled.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Always on Top automatic disabled after closing KeePassXC.
## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.4 (Portable)
Revision: 34a78f0

Qt 5.15.2
Debugging mode is disabled.

Operating system: Windows 10 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.19042

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
- libgcrypt 1.9.1-unknown

**Comment by phoerious** [comment]
I don't think it makes to much sense to persist this setting. What do you think, @droidmonkey?

**Comment by giwrgosmant** [comment]
> 
> 
> I don't think it makes to much sense to persist this setting. What do you think, @droidmonkey?

It's useful for me, while manually fill account credentials. I double click on the URL of entry to open it, then double click on pass and copy - paste and then username and copy paste.
Always on Top help me to have the KeePassXC always in view while doing the steps above.

**Comment by phoerious** [comment]
That's why there is a shortcut for enable the setting quickly. Most Linux WMs also have the feature built-in, so this is mostly for Windows and macOS. Making the setting persistent would certainly confuse users who enabled it accidentally or forgot they did it.

**Comment by giwrgosmant** [comment]
> 
> 
> That's why there is a shortcut for enable the setting quickly. Most Linux WMs also have the feature built-in, so this is mostly for Windows and macOS. Making the setting persistent would certainly confuse users who enabled it accidentally or forgot they did it.

Don't get me wrong, but it doesn't make sense. If you think this way, the same goes for the other settings too but other settings persist.

**Comment by phoerious** [comment]
No, always on top is a temporary override, not something that should persist IMHO. It changes the behaviour of the window in a way that is not obvious if not enabled explicitly. Pressing the shortcut when you need it, should be easy enough.

**Comment by giwrgosmant** [comment]
> 
> 
> No, always on top is a temporary override, not something that should persist IMHO. It changes the behaviour of the window in a way that is not obvious if not enabled explicitly. Pressing the shortcut when you need it, should be easy enough.

It's easy but not comfortable when I have to do this every time I open KeePassXC. Since this option is available, give us the option to make it persist like in KeePass.
I don't think it's so easy for a user to be confused just from this setting. There are more other settings a user can be confused.
Anyways it's just my opinion 🤓

**Comment by libklein** [comment]
Regardless of the persistence of "always on top", should the setting if it stays non-persistent, for the sake of consistency, not be moved/separated from the other settings in the View submenu? Other settings in the same group, like "Show Toolbar" are persistent. I can see how that would confuse users.

**Comment by giwrgosmant** [comment]
> 
> 
> Regardless of the persistence of "always on top", should the setting if it stays non-persistent, for the sake of consistency, not be moved/separated from the other settings in the View submenu? Other settings in the same group, like "Show Toolbar" are persistent. I can see how that would confuse users.

I think it's in the right place in View submenu. It's just doesn't make sense to me, other settings there persist but Always on Top not. I agree somehow this can confuse the users, as I was confused at first.

**Comment by DimMan88** [comment]
> 
> 
> I don't think it makes to much sense to persist this setting. What do you think, @droidmonkey?

Then remove it.! 
Jesus....lazy people......

**Comment by droidmonkey** [comment]
The decision to not persist was deliberate. I agree it is confusing that it does not persist amongst the other settings. I don't really care either way, it is at least obvious that the setting is enabled because the window will not fall behind others. The correction is trivial as well.

**Comment by giwrgosmant** [comment]
> 
> 
> The decision to not persist was deliberate. I agree it is confusing that it does not persist amongst the other settings. I don't really care either way, it is at least obvious that the setting is enabled because the window will not fall behind others. The correction is trivial as well.

I see now, you made it like this, in purpose.
However the correction it's not trivial at least for me, since it will save time while I am in rush to login somewhere fast and it will not be so "annoying" to enabling this every single time I open KeePassXC.

**Comment by phoerious** [comment]
I don't think we will change the behaviour of this feature, so I'm closing this.

**Comment by mantlabs** [comment]
I agree. The nature of always on top should be persisted like in KeePass. The confusion is mostly caused from the current functionality. We could do it with an additional option and let the user decide how it will behave. Therefore, I made a [pull request (#6203)](https://github.com/keepassxreboot/keepassxc/pull/6236) to add that additional option in Settings, which you can approve or not @droidmonkey @phoerious. Let me know what do you think.

Regards,
mantlabs
