### ISSUE TITLE
No database compatibility between keepassxc 2.3.4 and keepassxc 2.6.4.

### ISSUE THREAD

**Issue by Sidicas** [keepassxreboot/keepassxc#6235]
## Overview
Unable to share keepass2xc database between Linux and Windows PCs.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Ran apt-get install keepass2xc from Debian stable which installed linux keepassxc 2.3.4.
2. Created a database, saved some passwords in it. Closed it, opens it, enter master password, works fine.  
3. Downloaded keepassxc 2.6.4 for Windows which is the only version available.
4. Tried to open the database and it always fails.
5. Created a new database in keepassxc 2.6.4 for Windows.
6. Copied it over to Linux
7. Fails to open in Linux keepassxc 2.3.4.

## Expected Behavior
I thought I would be able to share the keepassxc database between these pcs.

## Context
Latest KeePassXC for Debian stable is 2.3.4.
Download page for Windows only provides KeePassXC for Windows version 2.6.4.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.6.4 and 2.3.4.

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows/Linux
Desktop Env: KDE
Windowing System: X11

**Comment by droidmonkey** [comment]
There is really no reason why those two versions wouldn't work together. However you can easily download the windows 2.3.4 package here: https://github.com/keepassxreboot/keepassxc/releases/tag/2.3.4

The better choice is to run the appimage or snap package on Debian to get 2.6.4.

**Comment by Sidicas** [comment]
I figured it out, the tool I was using to synchronize the file between the PCs was creating 0 byte files on destination if it didn't exist.  Works with rsync or network share mount.
