### ISSUE TITLE
cmd:// URL not working with snap

### ISSUE THREAD

**Issue by dagbj** [keepassxreboot/keepassxc#6238]
## Overview
This is a duplicate/aditional information to these cases:
https://github.com/keepassxreboot/keepassxc/issues/2891 **Windows**
https://github.com/keepassxreboot/keepassxc/issues/6087 **MacOS**

My system is `Ubuntu 20.04.2 LTS`, and KeepassXC is installed with Snap.

## Steps to Reproduce
The steps are similar to those other reports.
Creating an URL like: `cmd://gnome-terminal -- ssh 10.2.1.1` 

## Expected Behavior
A new window with a ssh session opened

## Actual Behavior
Aparently nothing.

## Context
Using a "normal" URL does work.

So I did some digging around this. The version of KeepassXC installed when i tried this was:
```
KeePassXC - Versjon 2.6.4
Revisjon: 34a78f0
Distribusjon: Snap

Qt 5.9.5
Debugging mode is disabled.

Operativsystem: Ubuntu Core 18
CPU-arkitektur: x86_64
Kjerne: linux 5.4.0-66-generic

Aktive utvidelser:
- Autoskriv
- Nettlesertillegg
- SSH-agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- libgcrypt 1.8.1
```

I downloaded source and built the application with these parameters:

```
cmake -DCMAKE_INSTALL_PREFIX=/usr\
 -DWITH_XC_UPDATECHECK=OFF\
 -DWITH_XC_DOCS=OFF\
 -DWITH_XC_BROWSER=ON\
 -DWITH_XC_SSHAGENT=ON\
 -DWITH_XC_KEESHARE=ON\
 -DWITH_XC_YUBIKEY=ON\
 -DWITH_XC_FDOSECRETS=ON\
 ..
```

And gives me this information Help → About → debuginfo

```
KeePassXC - Versjon 2.6.4
Revisjon: 34a78f0

Qt 5.12.8
Debugging mode is disabled.

Operativsystem: Ubuntu 20.04.2 LTS
CPU-arkitektur: x86_64
Kjerne: linux 5.4.0-66-generic

Aktive utvidelser:
- Autoskriv
- Nettlesertillegg
- SSH-agent
- KeeShare (only unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- libgcrypt 1.8.5
```
I did not install this on my system, but rather ran it from my build-area.

**This version did launch the application as expected.**

My next step was to try upgrading to the beta version:
`sudo snap refresh keepassxc --beta`

Giving me this debug info:

```
KeePassXC - Versjon 2.7.0
Revisjon: bc08913
Distribusjon: Snap

Qt 5.9.5
Debugging mode is disabled.

Operativsystem: Ubuntu Core 18
CPU-arkitektur: x86_64
Kjerne: linux 5.4.0-66-generic

Aktive utvidelser:
- Autoskriv
- Nettlesertillegg
- SSH-agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- libgcrypt 1.8.1
```

This version did not work

## Summary ##

Snap 2.6.4: **Fail**
Local 2.6.4: **OK**
Snap 2.7.0: **Fail**

I hope that this is of help solving the problem.

**Comment by droidmonkey** [comment]
This is a limitation of the snap sandbox
