### ISSUE TITLE
Database saves on exit without any data changes

### ISSUE THREAD

**Issue by affinityv** [keepassxreboot/keepassxc#6239]
## Overview
KP will save on exit even when zero data changes have been made.
The DB file size is not the same as the pre-saved DB file either

## Steps to Reproduce
1. Open database,
2. navigate group entries, open up groups to sub-groups
   - no entries opened or anything else, that's enough
3. Exit KP, again, without ANY data changes and KP will save to the file on exit.

I've exported data to CSV for pre-saved and post-saved DBs, the CSVs both have the same sha256sum

## Expected Behavior
If no data changes, DO NOT save or overwrite the DB file.

## Actual Behavior
DB file is overwritten, new size, new timestamp; no data changes as evidence from CSV exports

## Context
This is been an ongoing problem, but I'm now annoyed enough to report it and can't believe that this still happens after multiple version updates.

## Debug Info
KeePassXC - Version 2.6.4
Revision: 34a78f0
Distribution: AppImage

Qt 5.15.2
Debugging mode is disabled.

Operating system: Debian GNU/Linux 9 (stretch)
CPU architecture: x86_64
Kernel: linux 4.19.0-5-amd64

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- libgcrypt 1.8.1

**Comment by droidmonkey** [comment]
This is by design. There are certain non-data changes that are saved on exit such as group expand/collapse and entry order postion (if using natural order sorting).

**Comment by affinityv** [comment]
Okay, can KP work with a read only database?  I can make it writable when there really is a change.

**Comment by affinityv** [comment]
Also, the "by design" choice is horrible to me, can you at least make it an option to NOT do that?

**Comment by droidmonkey** [comment]
Not sure what the problem is here, you want the state of your database saved or not? It used to save every time, not just on close. It also used to prompt to save due to non data changes which is even worse. The suggested setting would be something akin to "Disgard non-data changes on exit", doesn't sound like anyone would want that to actually happen. 

A proper read-only mode would be best but is tracked elsewhere on this issue list.

**Comment by affinityv** [comment]
Any state information, IMHO, doesn't really belong in the DB file; there is an INI file in the .config area, that could save sate if necessary.

Depending on how much data this is, perhaps it could be a "special" separate file in the DB location, like a supporting non-data DB file or something, the same way as we can have key files separate to the actual DB file

Is there any good doco describing what is non-data related that is currently stored within the DB itself?  And perhaps why it is there?

A "read-only mode?  Not really, I want to be able save actual data changes whenever I want, I just don't want KP to do it behind my back.  I manage archives of older KP dB files, probably saved quite a few that have no data differences.

What I normally do on machines running the original V2 KP from keepass.info is to choose an entry that will be active on startup and save the DB, then the DB never gets saved again until there are actual changes to data.

**Comment by affinityv** [comment]
btw How do you handle multiple people using the same DB?  Reloading on change, you are reloading someone else's state?

**Comment by droidmonkey** [comment]
The saving of state in the database is a requirement from KeePass2, we didn't invent that idea or requirement. The same thing is happening over on original KeePass as well, perhaps not as persistently as us. And yes, when you share a database the state is shared as well.

**Comment by affinityv** [comment]
I can open and close a KeePass2 DB time and time again and the file hasn't changed for some times many weeks and even months.  So KeePass2 is doing this differently.

**Comment by affinityv** [comment]
What exactly is this "state" information?

**Comment by droidmonkey** [comment]
There is only two: Group expanded state and entry natural order position
KeePass2 does not auto-save the group expanded state on exit, so next time you open the database it reverts back to whatever was saved before. 
KeePass2 does mark the database dirty (needs a save) when reordering entries.

**Comment by droidmonkey** [comment]
BTW, this setting already exists, silly me:

![image](https://user-images.githubusercontent.com/2809491/110255377-546e4480-7f61-11eb-8e66-3ba4069e497e.png)

**Comment by affinityv** [comment]
Great, made the change to settings, all good now, never had that value in the keepass.ini file, it's there now.

That state data, is there any reason it cannot be saved to the INI file instead of the DB, that would be less harmful and more useful?

**Comment by droidmonkey** [comment]
That is just not how the database system operates and would break compatibility and behavior across computers and programs.

**Comment by phoerious** [comment]
Saving it to the INI would leak meta data about your groups end entries and it would get out of sync as soon as the database changes on another system.

**Comment by affinityv** [comment]
> Saving it to the INI would leak meta data about your groups end entries and it would get out of sync as soon as the database changes on another system.

It could be encrypted data in the INI file, no need to give away meta data.  If the data is decrypted and it's not valid, ignore it as it's not very important data anyway being just the "Group expanded state and entry natural order position"
