### ISSUE TITLE
Cannot save database on Android device connected via USB

### ISSUE THREAD

**Issue by SCBuergel** [keepassxreboot/keepassxc#6240]
## Overview
I am using keepass on my Android device and also on my laptop. When trying to sync to Android from my laptop I cannot save the database file.

## Steps to Reproduce
1. Connect Android phone via USB to laptop
2. Change `USE USB FOR` to `File transfer / Android Auto`
3. Open the Keepass db file from Android on Laptop, in my case file is located on `/run/user/1000/gvfs/mtp\:host\=REDACTED/Internal\ shared\ storage/Keepass/keepass.kdbx` - this works, reading the db does not cause issues
4. `Save database as...` and calling it e.g. `keepass2.kdbx` fails with `Writing the database failed: Input/output error`
5. The same happens when trying to merge another database

## Expected Behavior
In the last 2 steps above I expected to write the (merged) database onto my Android device.

## Actual Behavior
Storing file on Android fails with `Writing the database failed: Input/output error`.

## Context
Ensuring that I can actually write to the folder as the same user who is running KeepassXC:
```
$ cd /run/user/1000/gvfs/mtp\:host\=REDACTED/Internal\ shared\ storage/Keepass/
$ echo "test" >> newfile.txt
$ ls -lash
total 2.5K
   0 drwx------ 1 seb seb    0 Mar  7 18:37 .
   0 drwx------ 1 seb seb    0 Jan  1  1970 ..
2.5K -rw------- 1 seb seb 2.2K Mar  7 18:25 keepass.kdbx
 512 -rw------- 1 seb seb    5 Mar  7 19:04 newfile.txt
```

Version info:
```
KeePassXC - Version 2.4.3
Revision: 5d6ef0c

Qt 5.12.8
Debugging mode is disabled.

Operating system: Ubuntu 20.04.2 LTS
CPU architecture: x86_64
Kernel: linux 5.8.0-44-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (only unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.5
```

Operating System: Ubuntu Ubuntu 20.04.2 LTS x64

**Comment by droidmonkey** [comment]
This is an issue with gvfs and a duplicate.
