### ISSUE TITLE
cli throws libpng-warnings about "incorrect sRGB profile"

### ISSUE THREAD

**Issue by pflakus** [keepassxreboot/keepassxc#6241]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
A libpng-warning appears, whenever I execute cli-commands that access my Passwords-vault.

I assume that it must be related to some corrupted favicon, but I don't know how to identify the offending entry(-s) in my vault. Hence I can't give specifics about how to reproduce this scenario. (Feel free to give me pointers how to narrow down the issue, if there is a way.)

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Create login-entry with URL that has a faulty favicon. (presumably, see above)
2. Tell the application to download favicons for that entry.
3. Run any cli-command that accesses the vault. (`ls`, `show`, etc.)

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

To get the expected output, without any libpng-warnings in the stderr.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

The respective commands throw a few warnings in the stderr, before returning the expected output. (The actual functions are not inhibited, afaict so far...)

Here's an example of the type error messages I see:

    $ keepassxc-cli ls Passwords.kdbx
    Enter password to unlock Passwords.kdbx: 
    libpng warning: iCCP: known incorrect sRGB profile
    libpng warning: iCCP: known incorrect sRGB profile
    Login/
    Personal/
    Devices/

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.4
Revision: 34a78f0

Qt 5.15.2
Debugging mode is disabled.

Operating system: Manjaro Linux
CPU architecture: x86_64
Kernel: linux 5.11.1-1-MANJARO

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- libgcrypt 1.9.2-unknown

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: KDE
Windowing System: X11

**Comment by droidmonkey** [comment]
This is going to be a thing of the past in 2.7.0 with moving all gui operations outside the cli. Additionally this is a warning, not an error. This happens when a favicon is saved with a wonky color palette. Perhaps from a different application.
