### ISSUE TITLE
app cannot be launched while offline

### ISSUE THREAD

**Issue by ajay-gh** [keepassxreboot/keepassxc#6243]
## Steps to Reproduce
1. go offline 
2. launch kpXC
3. 

## Expected Behavior
keepassXC starts and shows UI
it is not acceptable that network access determines whether user can or cannot access his passwords 

## Actual Behavior
nothing (os-x taskbar shows a bouncing icon), app does not launch
force quit and restart will not help
force quit and restart will help after you go online

## Context
this behavior seems new in v2.6.4 (may be a little earlier) 

KeePassXC - v 2.6.4 for Mac

Operating System: Mojave fully up-to-date
Desktop Env: n/a
Windowing System: n/a

**Comment by droidmonkey** [comment]
There is no such requirement.

**Comment by ajay-gh** [comment]
Sorry, brevity for all it is worth,  
but the statement "There is no such requirement." is ambiguous. Do you mean my observation is correct (it requires network access), but this is what the devs want ? Or does it mean, my observation is wrong (kpXC doesn't need network access) ?

**Comment by droidmonkey** [comment]
There is no requirement for network access, nothing in our program depends on network connectivity to run. Perhaps macOS itself requires network access to perform validation of a new programs, but that is not on us.
