### ISSUE TITLE
KeepassXC 2.6.4 installed with APT in Ubuntu does not load ssh-agent

### ISSUE THREAD

**Issue by abacao** [keepassxreboot/keepassxc#6244]
SSH-Agent in KeepassXC 2.6.4 does not work

```
$ keepassxc -v
KeePassXC 2.6.4
$ keepassxc &    
[1] 33965
$ ssh  ssh-add -l
The agent has no identities.
```

AppImage is currently working.

**Comment by droidmonkey** [comment]
the apt version is not 2.6.4 so you are definitely running the snap version.

**Comment by abacao** [comment]
@droidmonkey Can you please clarify?

```
whereis keepassxc
keepassxc: /usr/bin/keepassxc /usr/lib/x86_64-linux-gnu/keepassxc /usr/share/keepassxc /usr/share/man/man1/keepassxc.1.gz
```

I have installed keepassxc with: 
```
apt install keepassxc
```

 available by having a repo 
```
deb http://ppa.launchpad.net/phoerious/keepassxc/ubuntu/ groovy main

```

I'm sure I'm not using the snap version

**Comment by droidmonkey** [comment]
Sorry didn't realize you were using the ppa.

**Comment by abacao** [comment]
In case of this happens to anyone, check if your SSH_AUTH_SOCK is correctly configured in KeepassXC.

No bug. Confirm working as intended.

**Comment by droidmonkey** [comment]
Great thanks for the report back!
