### ISSUE TITLE
KeePassXC 2.6.x will not keep full-screen setting on Mac

### ISSUE THREAD

**Issue by le-jawa** [keepassxreboot/keepassxc#6245]
## Overview
KeePassXC isn't holding its screen geometry settings when it's closed and later re-opened.  I run KeePassXC full screen, and I close it cleanly.  The next time I reopen it, it opens as a window on the current virtual desktop, instead of opening full-screen.  This used to work properly, but changed somewhere in 2.6.x.  I'm running it on a Mac with macOS 11.2.2 installed.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. In System Preferences, click "Mission Control", and make sure that "Automatically rearrange Spaces based on most recent use" is checked
2. On the dock bar, right-click on the KeePassXC icon, go to Options, then under "Assign to" click "This desktop" (if you're only using one monitor) or "Desktop 1" (if you're using multiple monitors.). 
3. Open KeePassXC 
4. Click the green traffic light (the full-screen button)
4. Once it's full-screen, close KeePassXC.
5. Repeat step 3.  The app does not keep the "full-screen" setting and will re-open as a window on the current desktop.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
When step 3 above is repeated, the app should open to its last screen setting; in this case, that's full-screen.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
The app does not keep the "full-screen" setting and will re-open as a window on the current desktop.

## Context
[NOTE]: # ( Give us any additional information you may have. 
-  MacBook Air (Early 2014)
-  Built-in Display: 1440x900
-  Second Display: 1920x1024 acer K242HL
- Second display is an extension, not a mirror
- Display is connected to the Thunderbolt 2 port via a DVI-Thunderbolt adapter
- 3 virtual desktops on each screen, not including apps running full-screen
- KeePassXC is "kept" on display 1 (the built-in display)
- Dock bar is set to hide automatically

Run 

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.6.4
Revision: 34a78f0

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS 11.2.2
No modifications to the underlying X system - "factory default"

**Comment by phoerious** [comment]
Probably related to #2653.

**Comment by droidmonkey** [comment]
Works in 2.7.0
