### ISSUE TITLE
Keepass lost unsaved data on auto-close database

### ISSUE THREAD

**Issue by JayDi85** [keepassxreboot/keepassxc#6246]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
Keepass doesn't save/keep unsaved data on auto-closing database.

## Steps to Reproduce
1. Enable auto-close database by timeout;
2. Open database
3. Add new record and enter some data in the form. But do not close it. It's a standard use case: create new password for new website, copy password it to the service but forget to save it in database;
4. Wait for timeout -- keepass must ask about unsaved data before closing;
5. Whatever you choose -- all your opened data will be lost (colored cancel button keep nothing in db, gray cancel button keep empty record without filled fields).

## Expected Behavior
Must save unsaved data on auto-close database or cancel a closing;

## Actual Behavior
Lost unsaved data from the form.

## Context
Problem dialog example. It's in russian but keep eye at buttons -- both buttons don't help in auto-closing use case (unsaved data will be lost in any choices):
![shot_210308_112247](https://user-images.githubusercontent.com/8344157/110365329-57029400-805e-11eb-9eb1-4dc13386e6cc.png)

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.6.1
Revision: 9a35bba
Operating System: Windows
Desktop Env: not linux
Windowing System: not linux

**Comment by droidmonkey** [comment]
Upgrade to 2.6.4 I'm pretty sure this was fixed.
