### ISSUE TITLE
Auto-type on ubuntu 20.04 not working

### ISSUE THREAD

**Issue by yuperi** [keepassxreboot/keepassxc#6248]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
Some garbage in the paste

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. [In video](https://ufile.io/1q7itr90)

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.4
Revision: 34a78f0

Qt 5.12.8
Debugging mode is disabled.

Operating system: Ubuntu 20.04.2 LTS
CPU architecture: x86_64
Kernel: linux 5.4.0-66-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- libgcrypt 1.8.5

[NOTE]: # ( Pick choices based on your environment )
Desktop Env: Gnome
Windowing System: X11

**Comment by droidmonkey** [comment]
You might need to increase the default start delay in the Auto-Type application settings.

**Comment by yuperi** [comment]
Same garbage
[Video1](https://ufile.io/knt75yya)

**Comment by hifi** [comment]
#6247 possibly fixes this issue. If you are able to test the PR I would appreciate it a lot.

**Comment by yuperi** [comment]
If you could provide me bin, I could test

**Comment by hifi** [comment]
Added an AppImage to the PR for testing.

**Comment by yuperi** [comment]
I've got in cmd
Active window changed, interrupting auto-type.

**Comment by yuperi** [comment]
+
Without additional menu I got notthing(ctrl+shift+v)
Global auto-type working as expected. Thank you
