### ISSUE TITLE
KeePassXC does not follow systems icon theme

### ISSUE THREAD

**Issue by exeqtion** [keepassxreboot/keepassxc#6255]
## Overview
Hi, KeePassXC does not follow the correct qt icon theme, but it does follow the correct qt (style/platform) theme.
For example see the screenshot below all the applications (Carla, Radeon Profile, Steam and qBittorrent) follow the correct icon theme except KeePassXC, and it is just not related to tray icon but all icons in KeePassXC.
![image](https://user-images.githubusercontent.com/67519576/110499116-d8563700-80ef-11eb-812d-f116717e1e8c.png)

## Steps to Reproduce
Open the KeePassXC normally. 

## Expected Behaviour
![Untitled](https://user-images.githubusercontent.com/67519576/110502935-90d1aa00-80f3-11eb-9c78-f6e11f3ffb9e.png)
The default file picker of qBittorrent which uses qt 5.

## Actual Behaviour
![image](https://user-images.githubusercontent.com/67519576/110501605-41d74500-80f2-11eb-8039-d91004fb035b.png)
The default file picker of KeePassXC which also uses qt 5. Notice the folder icons. 

## Context
I think this is due to KeePassXC uses its own icons for everything (toolbox, tray icon and file picker) and if it does not find the icon (e.g. in file picker icon of folders) it uses the default icon theme instead of using systems overridden icon theme.

KeePassXC - Version 2.6.4
Revision: 34a78f0
Operating system: Gentoo/Linux
Desktop Env: Awesome WM
Windowing System: X11

**Comment by droidmonkey** [comment]
Using the snap build?

**Comment by exeqtion** [comment]
> Using the snap build?

Nope.

**Comment by droidmonkey** [comment]
Appimage?

**Comment by exeqtion** [comment]
Nah, I installed it from the official gentoo repo.

**Comment by droidmonkey** [comment]
We don't impose an icon set for the file picker, but we do use our own icons for everything else (by design). Usually the file picker theme is different with snap packages. The file picker is from Qt and really from the system itself. There is no obvious reason why it would look different.

**Comment by exeqtion** [comment]
I think the problem is it uses built-in icons provided by qt instead of using systems overridden value. #6003 
![1615388756](https://user-images.githubusercontent.com/67519576/110650296-5418b800-81b2-11eb-9b1b-d1265548f427.png)
I think default behaviour should be using the systems overridden icons then its own icons and finally default/provided by qt icons.
