### ISSUE TITLE
Kdbx file synced from Nextcloud corrupted only on my Linux machine (HMAC)

### ISSUE THREAD

**Issue by leifadev** [keepassxreboot/keepassxc#6256]
## Overview
My database file synced from Nextcloud installed on my Linux Mint box can't be opened by KeePassXC. Giving the following error
```Error while reading the database: Invalid credentials were provided, please try again.
If this reoccurs, then your database file may be corrupt. (HMAC mismatch)"
```
I am definitely using the right password and generated key. **I cant open it regardless if it is being synced with Nextcloud or not**.

## Steps to Reproduce
1. On per se Windows 10 PC and Linux Mint install Nextcloud, sign in, and let the stored cloud db file sync into the OS file system with it's Nextcloud folder assigned for syncing (like dropbox).
2. Open the file on windows, macOS, and iOS freely with no problems (iOS is Keepassium)
3. Launch keepassXC installed once from Snap and APT
4. Open exsisting database from the Nextcloud folder (pinned on my File managers sidebar) and receieve error shown in the above code block.

## Expected Behavior
On step 4, the database file (.kdbx) should have opened successfully just as on all other OS'.

## Actual Behavior
Receive error shown in the above code block.

## Context
I cant exactly remember which OS/Device I created the db on if that matters. **I cant open it regardless if it is being synced with Nextcloud or not**.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.4.3
Revision: 5d6ef0c
```
Qt 5.12.8
Debugging mode is disabled.

Operating system: Linux Mint 20.1
CPU architecture: x86_64
Kernel: linux 5.4.0-66-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (only unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.5
```

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux Mint 20.1
Desktop Env: Cinnamon
Windowing System: X11

**Comment by leifadev** [comment]
I will now, how would I do that or what website would be easy gen?

**Comment by droidmonkey** [comment]
On Linux you can use shasum256 or md5. On windows you can use a third party program.

**Comment by leifadev** [comment]
The hash for the file is: `def8c70dc6aa70e0617ebe89ec23c0bd` What should I do this to check?

**Comment by droidmonkey** [comment]
You compare that hash on both platforms to confirm the file is the same, we don't need the hash this isn't for us. This would tell you if the same database file is on your windows and Linux machines.

**Comment by leifadev** [comment]
The windows hash vs my Linux and macbook air hashes are different, is this a softwarthing with macOS and windows? Or maybe even Unix systems?

If the hashes are different what should I do? I saw no repair button anyshee

**Comment by droidmonkey** [comment]
That means your nextcloud synching is not working

**Comment by leifadev** [comment]
So for example its syncing to other devises except Linux?
Secondly, if so by chance would you know some advice about this?

**Comment by droidmonkey** [comment]
@phoerious any nextcloud advice?

**Comment by phoerious** [comment]
Not really, no. Make sure your sync status is clean on all devices and force a resync if not.

**Comment by leifadev** [comment]
Got it, yeah good idea to do that, I will let you know later when you can close this thread

**Comment by leifadev** [comment]
Btw what and how do you mean by force syncning

**Comment by droidmonkey** [comment]
I think its time to take this over the the nextcloud board and/or their documentation: https://docs.nextcloud.com/

**Comment by leifadev** [comment]
**Solved!**
It was simply an issue/bug with KeePassXC's version. Mine was wayy out of date. I am on the newest one (2.6.4) and it works!
This was mostly in the first place having ignorance with different package managers maintaining KeePassXC's version.

**Comment by droidmonkey** [comment]
Awesome news
