### ISSUE TITLE
Password Security Feature - Password - Check which accounts share the same (or a similar) password

### ISSUE THREAD

**Issue by wolphyx** [keepassxreboot/keepassxc#6259]
## Summary
When people start using password managers like KeepassXC, they might have a plethora of existing accounts and passwords already, many of which might share the same or similar passwords to be able to keep them in mind at all.
For optimal security, ideally every account should have a unique long password, of course.

So I want to suggest the implementation of a tool that checks the currently opened database for account-entries with the same (or too similar, done by a string similarity coefficient) passwords. This way, the user can easily identify security risks and change the respective passwords.

The functionality could maybe even be generalized to include a check for too short passwords (where the password length is falling under a threshold of what can be easily brute-forced) or to check for passwords which do not at least include specific character types (e. g. which do not fulfill the requirements of the password generator).

## Examples
1. User clicks on Tools-> Password Security Check
2. Window pops up with list of accounts sharing the same/a similar password (or one of the other characteristics mentioned above)
3. User can click on an entry to open the edit window and change the password accordingly.

## Context
Like said in the introduction, this would be handy for people with a lot of accounts & passwords they previously only kept in mind and used shortcuts to remember them, at the expense of password security. After they entered their accounts, they could easily check for security issues so that they not only use KeepassXC as a password manager, but use it the right way and to the full extent of its capabilities. In a way, it's a kind of migration feature to a "password manager lifestyle".

**Comment by droidmonkey** [comment]
Well you are in luck because this tool already exists in the program, go to Database -> Database Reports. We even have Have I Been Pwned checks as well. Similar password checks is an already requested feature.
