### ISSUE TITLE
[RFE] keepassxc-cli diff - diffing two databases

### ISSUE THREAD

**Issue by jirib** [keepassxreboot/keepassxc#6264]
Possibility to see difference between two databases would be handy, eg. I used `syncthing` and I ended with a lot of `<keepassxc_db_file>.sync-conflict-<data>-<random>.kdbx` files. Not sure about the output but maybe something like following output from `daff` would be enough.

![`daff`'s output](https://camo.githubusercontent.com/d98936414000df86f5665943dbb9ea91bb8c7c6ca5366fac848762333e2a0063/687474703a2f2f7061756c6669747a2e6769746875622e696f2f646166662d646f632f696d616765732f646166665f76735f646966662e706e67)

**Comment by droidmonkey** [comment]
Does the `keepassxc-cli merge --dry-run` command work for you? This prints a list of changes that would be made during a merge operation.

**Comment by jirib** [comment]
Thank for tip. Unfortunatelly IMO a `diff`-like output should be more human readable, `keepassxc-cli merge --dry-run <db1> <db2>` is not that.

**Comment by droidmonkey** [comment]
Well a kdbx file is not a plain text file. It is not like line 1 doesn't match line 2. So not sure how we could make it any easier.

**Comment by jirib** [comment]
Well, the screenshot above shows diff between two CSV files, and keepassxc can export to CSV.

**Comment by droidmonkey** [comment]
We would never do that. There is so much more to a database then what is exported to csv.

**Comment by jirib** [comment]
ACK

**Comment by mmahmoudian** [comment]
@droidmonkey Sorry for necrobumping. I just had one database that was synced to another computer and I didn't know if they diverged or not, so I used ` keepassxc-cli merge --dry-run --same-credentials db-local.kdbx db-remote.kdbx` and I almost got what I needed, but I also think the current state is not very readable. 


![image](https://github.com/keepassxreboot/keepassxc/assets/390889/8092be2e-f968-4ff7-a8d2-ccebb8337b60)


Would it be feasible to add the following:
1. actions be listed in a table format (example below)
2. specify which file is the "newer source" (newer can be based on file modification time or internal variable in databases)
3. use some sort of color coding. For instance `--color=always`

```console
❯  keepassxc-cli merge --dry-run --same-credentials db-local.kdbx db-remote.kdbx
Enter password to unlock db-local.kdbx

| Action                               | what      | hash               |
|--------------------------------------|-----------|--------------------|
| Overwriting                          | blah blah | [814h814h814h814h] |
| '_ Synchronizing from newer source   | blah blah | [814h814h814h814h] |
|   '_ Creating missing                | blah blah | [814h814h814h814h] |
|   '_ Creating missing                | blah blah | [814h814h814h814h] |

Database was not modified by merge operation.
```

If you are ok with such proposal and don't want it in this thread, I can transfer this to a new feature request.

**Comment by droidmonkey** [comment]
See this PR where any changes to this should be implemented: #10173

**Comment by mmahmoudian** [comment]
@droidmonkey This is very very nice. It actually contains some of the stuff I liked to propose but I kept them out to avoid y suggestion to be dismissed due to complexity. These said, it seems #10173 is only aiming at GUI and [the improvements are not carried over to CLI](https://github.com/keepassxreboot/keepassxc/pull/10173/files#diff-590d6a5a30a7f6214861d534bc11634569ca5fa72a981fbd82225f776258d883) at least until [00f98b3](https://github.com/keepassxreboot/keepassxc/commit/00f98b3a6869d33296e561613da0b79cdd49804e) commit. Shall I suggest CLI improvement in that PR as well? (My C++ is not good enough to submit a patch).

**Comment by droidmonkey** [comment]
Yes, suggest any desired changes in the PR
