### ISSUE TITLE
Autotype only enters password when using global shortcut

### ISSUE THREAD

**Issue by JSB22** [keepassxreboot/keepassxc#6266]
## Overview
Im pretty new to KeypassXC but I already fell in love with it.
Thanks for the work!

When I use the global shortcut to autotype my login it only writes the password.
Even if I select a username field.

## Steps to Reproduce
1. I saved my Ableton Login in Keepass
I used the username field for my mail and the password field for my password and saved https://www.ableton.com/ as weblink
2. I made sure that I use that the autotype config of the group is {USERNAME}{TAB}{PASSWORD}{ENTER}
3. i select the username field and use global shortcut to autotype -> enters password in clear text into the username field.
4. i right click the abelton login in keepass and select auto-fill -> works as intended: first username then password

## Expected Behavior
I would think that the global shortcut should use the same autofill mechanics as the one you get in the menu

## Actual Behavior
Using the global shortcut only my password is being entered

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.4
Revision: 34a78f0

Qt 5.15.2
Diagnosemodus ist deaktiviert.

Betriebssystem: macOS 11.2
CPU-Architektur: x86_64
Kernel: darwin 20.3.0

Aktivierte Erweiterungen:
- Auto-Type
- Browser-Integration
- SSH-Agent
- KeeShare (bestätigtes und unbestätigtes Teilen)
- YubiKey
- TouchID

Kryptographische Bibliotheken:
- libgcrypt 1.9.1

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS Big Sur Version 11.2.2
Desktop Env: ?
Windowing System: ?
Hardware: MacBook Pro 2018

**Comment by droidmonkey** [comment]
Did you define a window association?

**Comment by JSB22** [comment]
To be totally honest im not sure what you mean :s

All the boxed in the AutoType settings are selected if this helps

**Comment by droidmonkey** [comment]
https://keepassxc.org/docs/KeePassXC_UserGuide.html#_configure_auto_type_sequences

**Comment by JSB22** [comment]
I assigned a window but the problem remains

**Comment by JSB22** [comment]
I deleted my old entry and made a new one and now it works.
Dont know why since they are the same but im fine with that.

Thanks for the help eitherway
