### ISSUE TITLE
Not Keeping Column Settings After Reboot

### ISSUE THREAD

**Issue by Headhurtz** [keepassxreboot/keepassxc#6267]
## Overview
After choosing which columns to display and in what order, my choices are forgotten and reset to default after a reboot.

## Steps to Reproduce

1. Log in and wait for main screen to load
2. Right-click column headers and check or uncheck which columns to display
3. Drag and drop columns in preferred order

## Expected Behavior
Program will retain these settings [Title; URL; Date Accessed] after exiting

## Actual Behavior
Works as expected if program is closed and reopened _during current session_.
However, loses its memory if laptop is powered off and on again 

## Context

KeePassXC - Version 2.6.4
Revision: 34a78f0
Distribution: Snap

Qt 5.9.5
Debugging mode is disabled.

Operating system: Ubuntu Core 18
CPU architecture: x86_64
Kernel: linux 5.4.0-66-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- libgcrypt 1.8.1

Operating System: Xubuntu 20.04
Desktop Env: XFCE
Windowing System: X11/Wayland

**Comment by droidmonkey** [comment]
You have you ~/.cache folder mounted to a ram disk. Either don't do that or use the --localconfig command line option.

**Comment by Headhurtz** [comment]
@droidmonkey : Thank you very much for your prompt reply and suggestion! Sorry I took so long to check back here.

The issue I was encountering has resolved itself. The column settings now "stick". I don't know what the issue was; Perhaps I had corrupted something by logging off and shutting down while it was writing to disk.

Thanks again!

**Comment by droidmonkey** [comment]
Awesome glad to hear it works!
