### ISSUE TITLE
Allow entry to match multiple titles

### ISSUE THREAD

**Issue by junibegood** [keepassxreboot/keepassxc#6268]
## Summary
Allow the same entry to be used in multiple windows with different titles. This could be achieved by detecting usage of  the | character in the "Title" attribute. Or alternatively, it that's easier to develop, maybe as additional attributes, something similar to providing additional URLs for browser integration.

## Examples

![Screenshot_2021-03-12_09-36-58](https://user-images.githubusercontent.com/10098225/110914655-f2be2980-8316-11eb-95ae-3a13def6215f.png)

This entry would match a window with either "Authentication" or "Password" in the title

## Context
One use case is Nexcloud integration in Thunderbird. Thunderbird requires authentication for each Nextcloud feature you use (calendar, contact list, task list...) separately, in popup windows with various titles that never contain the name "Thunderbird". Right now, this means one entry for each possible title in KeePasXC. But the login / password combination is the same for all features in a Nextcloud account, so this entries should not be necessary.

I realize this use case is more a limitation of Thunderbird than a limitation of KeepassXC, but I believe this feature could be useful in many other situations nonetheless.

**Comment by droidmonkey** [comment]
Use the aurotype window association feature. It is in the user guide.

**Comment by junibegood** [comment]
I had missed this feature, sorry. It works like a charm !
