### ISSUE TITLE
Not a KeePass database

### ISSUE THREAD

**Issue by ddelic** [keepassxreboot/keepassxc#6269]
## Overview
Can not open my database any more. When typing in the password getting the following error: Unable to open database. Not a KeePass database. It is a KeePass database that I am (or was) using for almost a year. I have done no significant changes, did not rename, copy, move the database file. Did not change the password.

## Steps to Reproduce
Use KeePass for longer time on Linux Mint.

## Expected Behavior
Open my database.

## Actual Behavior
Not opening my database with above mentioned message. A bit of anger and despair, wishing I was still writing down passwords on paper.

## Context

Linux Mint 20.1 Cinnamon
KeePassXC - 2.0.3
Revision: 1682ab90243e

Operating System: Linux Mint 20.1 
Desktop Env: Cinnamon
Windowing System: X11/Wayland

**Comment by droidmonkey** [comment]
Where you store the file? USB drive? This means the magic bytes at the start of the file are wrong. Your database may not be fully corrupt, but it is unlikely you'll be able to decrypt it.

**Comment by ddelic** [comment]
Thanks. Looks like I am barking on a wrong tree now, sorry for that, I am using another program: KeePassX. 
I ll close this, sorry for any inconvenience.

**Comment by droidmonkey** [comment]
You should use our program. KeePassX is no longer maintained.
