### ISSUE TITLE
[feature] Allow only 1 instance of the program option

### ISSUE THREAD

**Issue by sanyarnd** [keepassxreboot/keepassxc#627]
It'd be nice to see an option for that, because without it, traying to system menu looks incomplete: to open the window, you have to use a mouse, rather that system hotkeys.

**Comment by droidmonkey** [comment]
Already implemented in #510 please search next time.

**Comment by SRGOM** [comment]
I don't see this option in my 2.2.0 release. Where should I be looking? settings doesn't have it. And everytime i start a new instance starts.

**Comment by phoerious** [comment]
Should work out of the box. Which operating system are you using?

**Comment by SRGOM** [comment]
Arch, native package (not snap or appimage).

**Comment by SRGOM** [comment]
Just to make sure we're talking about the same thing:

/bin/keepassx &
/bin/keepassx & 

show me two keepass instances in the tray without any action.

**Comment by SRGOM** [comment]
Weird, the appimage works fine, allowing only single instance. Also there is an alt-key for the databases menu. I'm thinking the Arch package is the problem

**Comment by TheZ3ro** [comment]
Are you using keepassxc or keepassx?

**Comment by SRGOM** [comment]
My bad, I mistyped the program name above. 
My (another) bad, I checked that Arch repository was updated with the latest version, did a `pacman --sync --refresh --sysupgrade` realizing only now that keepassxc is still old. Sorry!

**Comment by SRGOM** [comment]
Either I'm dumb or flattr doesn't accept new logins.

**Comment by phoerious** [comment]
With Flattr I can't help, sorry. Your other problem, is it solved then?

**Comment by SRGOM** [comment]
Yes, it's solved now, thank you and sorry for the bother. You guys might want to add a bitcoin addr in the meanwhile.
