### ISSUE TITLE
Auto-type input lost / not entered into the password window

### ISSUE THREAD

**Issue by udopt** [keepassxreboot/keepassxc#6273]
## Overview

When using auto-type in [Hibiscus](https://www.willuhn.de/products/hibiscus/) or Thunderbird, sometimes the input is lost / not entered into the password window. I suspect that at the moment where KeePassXC performs the typing the focus is not anymore on the window.

## Steps to Reproduce
1. Open password dialogue in either Hibiscus or Thunderbird (for those specific programs, KeePassXC is configured to only enter the password).
2. Press key combination for auto-type.

## Expected Behavior
Password is entered correctly into to window.

## Actual Behavior
Password is **not** entered into the window, sometimes seemingly triggering shortcut actions.

## Workaround
After pressing the key combination for auto-type, quickly single-click into the password box to ensure focus.

## Context
KeePassXC - Version 2.4.3
Revision: 5d6ef0c

Operating System: Ubuntu 20.04
Desktop Env: XFCE
Windowing System: X11

**Comment by hifi** [comment]
You may want to increase Auto-Type start delay and typing delay in Settings -> General -> Auto-Type.

**Comment by udopt** [comment]
Thank you for the tip, unfortunately, this did not help. It seems that after the key combination for auto-type the focus is moved from KeePassXC back to the original application - but not back to the separate window with the password field (no blinking cursor inside the password area, title bar of the main application window shows focus instead of the password window).

**Comment by hifi** [comment]
Right, modal dialogs may work slightly differently and when KeePassXC is re-focusing the window the parent window might do something funky and remove the focus from the input field inside the dialog. It may also be due to focus-follows-mouse settings if the focus is somehow mixed up.

I'm not sure if this is fixable on our side at all but if I can reproduce it with Thunderbird for example I could possibly look into it. You may be able to workaround it by adding additional delay to the pattern itself and some keys like `{TAB}` to try to move the focus properly but it is of course error prone.

**Comment by droidmonkey** [comment]
Does this occur when you are just alt-tabbing between windows? If so then this bug belongs with the application not keepassxc.

**Comment by udopt** [comment]
@hifi For Thunderbird, I use a master password. If you auto-type the master directly upon starting (when there is no main application window yet), auto-type works. If there is already a main application window, the problem occurs as described.

@droidmonkey No, this problem does not occur when alt-tabbing between windows.

**Comment by udopt** [comment]
Is there any more information I can provide?

**Comment by droidmonkey** [comment]
No, this is just hyper specific and likely won't be addressed specifically by our team. I am not even sure how to reproduce this use case since I don't use thunderbird and don't know what exact conditions trigger the pop-up you are using.
