### ISSUE TITLE
Tray icon not themed correctly after update to 2.6.4

### ISSUE THREAD

**Issue by mx1up** [keepassxreboot/keepassxc#6275]
## Overview
after updating to 2.6.4, I have a light themed tray icon in a light themed desktop environment which makes the icon barely readable. I did not experience this problem with previous upgrades.
![image](https://user-images.githubusercontent.com/178714/111035237-ba534400-8419-11eb-9ab3-403ce37b7fca.png)
I did a lot of package updates, so maybe also a Qt update has been installed.

## Steps to Reproduce
1. use light DE theme
2. upgrade keepassxc to 2.6.4
3. start up and check tray icon

## Expected Behavior
dark tray icon for light theme

## Actual Behavior
light tray icon for light theme

## Context
i performed a dist upgrade on opensuse tumbleweed, so other packages have been updated as well.

KeePassXC - Version 2.6.4
Revision: 34a78f0

Qt 5.15.2
Debugging mode is disabled.

Operating system: openSUSE Tumbleweed
CPU architecture: x86_64
Kernel: linux 5.10.16-1-default

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (only unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- libgcrypt 1.9.2-unknown

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: KDE
Windowing System: X11

**Comment by droidmonkey** [comment]
Just choose the monochrome dark icon from the application settings.
