### ISSUE TITLE
Fractional scaling with Ubuntu 20.10 Gnome Wayland session is blurry

### ISSUE THREAD

**Issue by almereyda** [keepassxreboot/keepassxc#6276]
## Overview

Continuing the experience from #2993, there is an issue with font and UI blurring in fractional scaling enabled Wayland sessions in Ubuntu 20.10.

## Steps to Reproduce

1. Install KeepassXC onto an Ubuntu 20.10 machine that uses the Gnome Wayland session.
2. Enable fractional scaling following the hints in https://blog.szypowi.cz/en/post/ubuntu-wayland/, like:  
  `$ gsettings set org.gnome.mutter experimental-features "['scale-monitor-framebuffer']"`
3. Run `keepassxc` and see it blurred, using XWayland.
4. Run `QT_ENABLE_HIGHDPI_SCALING=True keepassxc` and find it blurred.
5. Run `QT_QPA_PLATFORM=wayland keepassxc` to find it fail to load.
6. Install additional dependencies for the application package with `apt install qtwayland5`.
7. Run `QT_QPA_PLATFORM=wayland keepassxc` and be happy with what you see.

## Expected Behavior

- KeepassXC figures the sharpest font-rendering and thus window composition strategy by itself.
- The Ubuntu packaging recognises the upstream dependency to the Qt5 Wayland platform with a suggested or hard dependency in the distribution.

## Actual Behavior

Following the tip in the previous issue to try running KeepassXC with

```
$ QT_ENABLE_HIGHDPI_SCALING=True keepassxc
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
```

led to the discovery, that

    $ QT_QPA_PLATFORM=wayland keepassxc       

might lead to clearer fonts by using native Wayland composition. Yet it hints at us:

```
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, xcb.

[1]    259100 abort (core dumped)  QT_QPA_PLATFORM=wayland keepassxc
```

which means the Qt5 wayland platform is not available. Introducing it with

    $ apt install qtwayland5

and starting KeepassXC similarily again, will lead to sufficient scenario that begins with a little confusing message, since the requested flag is provided.

```
$ QT_QPA_PLATFORM=wayland keepassxc
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
QSocketNotifier: Can only be used with threads started with QThread
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
```

## Context

Wayland on Gnome is not frequently used yet on Ubuntu, but will turn standard with the next release in the upcoming April cycle.

References:

* [Ubuntu 21.04 Will Try To Use Wayland By Default - Phoronix](https://www.phoronix.com/scan.php?page=news_item&px=Ubuntu-21.04-Wayland-Default)
* [The Work Ahead For Ubuntu 21.04 To Switch To Wayland By Default - Phoronix](https://www.phoronix.com/scan.php?page=news_item&px=Ubuntu-21.04-Wayland-Plans)

```
KeePassXC - Version 2.6.4
Revision: 34a78f0

Qt 5.14.2
Diagnosemodus ist deaktiviert.

Betriebssystem: Ubuntu 20.10
CPU-Architektur: x86_64
Kernel: linux 5.8.0-44-generic

Aktivierte Erweiterungen:
- Auto-Type
- Browser-Integration
- SSH-Agent
- KeeShare (bestätigtes und unbestätigtes Teilen)
- YubiKey
- Secret-Service-Integration

Kryptographische Bibliotheken:
- libgcrypt 1.8.5
```

Operating System: Linux
Desktop Env: Gnome
Windowing System: Wayland

**Comment by droidmonkey** [comment]
Do you experience this in other qt apps?

**Comment by droidmonkey** [comment]
First off you are using experimental settings. Secondly, blurring would be the fault of the compositor and not the application. Blurring means the application is being rendered at 100% and then increased in size to 150%.

You could try this Qt environment variable: `QT_SCALE_FACTOR_ROUNDING_POLICY=PassThrough`

**Comment by xrammit** [comment]
@droidmonkey I experienced the exact same issue @almereyda described with my system (Ubuntu 21.10, Gnome 40, Wayland). As wayland is now the default windowing system in Ubuntu and will also be the default in the upcoming Ubuntu 22.04 LTS and fractional scaling is no longer an experimental setting, a lot of users will experience the blurry KeepassXC GUI.

Is there a reason why you can not add the Qt wayland platform plugin (e.g. package `qtwayland5` for Ubuntu) as a dependency to the deb? The wayland platform plugin is already defined as a plugin for the KeepassXC snap package build as far as I can see,

I'm also wondering why KeepassXC does not run as a native wayland application on systems using wayland as windowing system?

**Comment by droidmonkey** [comment]
@xrammit the support for fractional scaling is not a KeePassXC concern. That support comes from Qt. If the deb package needs to rely on qtwayland5 then you need to let the deb maintainers know that. We do not maintain packages provided by downstream repositories. 

One of the main reasons we try not to run as a native Wayland application is because Auto-Type is totally non-functional under Wayland and the Qt Wayland plugin has been rather buggy up until very recently.
