### ISSUE TITLE
TouchID doesn't work on version built from source

### ISSUE THREAD

**Issue by ostrolucky** [keepassxreboot/keepassxc#6278]
When KeepassXC is built from source, TouchID doesn't work. This makes it difficult to contribute touchid related work. It works with official version, though.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Open database with "TouchID for Quick Unlock" checked
2. Lock database
3. Press enter

## Expected Behavior
TouchID prompt should be displayed

## Actual Behavior
Window with message
> Unlocking the database failed and you did not enter a password.
> Do you want to retry with an "empty" password instead?

## Context
KeePassXC - 2.7.0-snapshot
Revision: 8b8fb95

KeepassXC has been compiled with `cmake -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/qt@5/5.15.2/lib/cmake -DWITH_XC_TOUCHID=ON ..`

**Comment by droidmonkey** [comment]
You need to sign the app in order to use TouchID. This is a macOS limitation.
