### ISSUE TITLE
Rare DPI scaling bug when re-enabling high DPI displays on windows

### ISSUE THREAD

**Issue by 0xpr03** [keepassxreboot/keepassxc#6282]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
If keepassxc is opened on a high-DPI screen in windows and the screen is disabled and then re-enabled after some time, KeePassXC does not re-scale.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
0. 1x 1080p screen, 1x 4k
1. Open KeePassXC on high-DPI display
2. Disable the 1080p one
3. (Open a video in fullscreen on the 4k ?!)
2. Disable display (turn it off/switch source?)
3. Re-Enable everything after some time

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Scaling is correctly, mouse focus is correctly on point with visual cursor.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
KeePassXC looks like this, it'll re-scale if you move it to a low-DPI display and back. The window size shows how big the correct scaling would look like.

Actual Mouse-Pointer focus is also shifted by ~10mm.

![keepass_report](https://user-images.githubusercontent.com/1280209/111070507-5e002b00-84d2-11eb-8c42-b3f69e7d12af.png)

## Context
[NOTE]: # ( Give us any additional information you may have. )
It's kinda hard to reproduce and at least the second time I'm trying to open an issue about it. The current report includes having 1x 1080p display and 1x 4k display, having keepassXC on the 4k one, starting a fullscreen video on it, turning the display off and coming back after some hours.

[NOTE]: # ( Paste debug info from Help → About here )
```
KeePassXC - Version 2.6.4
Revision: 34a78f0

Qt 5.15.2
Diagnosemodus ist deaktiviert.

Betriebssystem: Windows 10 Version 2009
CPU-Architektur: x86_64
Kernel: winnt 10.0.19042

Aktivierte Erweiterungen:
- Auto-Type
- Browser-Integration
- SSH-Agent
- KeeShare (bestätigtes und unbestätigtes Teilen)
- YubiKey

Kryptographische Bibliotheken:
- libgcrypt 1.9.1-unknown
```

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 10

**Comment by 0xpr03** [comment]
This is what happens if I shorten the size of the window.

![keepass_report2](https://user-images.githubusercontent.com/1280209/111070588-bafbe100-84d2-11eb-8a56-54824406f15f.png)

**Comment by droidmonkey** [comment]
This is a qt bug please report to them: bugreports.qt.io
