### ISSUE TITLE
KeePassXC extension in Firefox blocks access to password fields

### ISSUE THREAD

**Issue by LinAGKar** [keepassxreboot/keepassxc#6283]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Have the KeePassXC extension in Firefox, connected to KeePassXC extension
2. Got to a site where KeePassXC fills in the password
3. Try to edit the password

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
When you click the password field, KeePassXC instantly moves the focus away from it, making it impossible to edit it.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
It should be possible to edit the password.

## Context
[NOTE]: # ( Give us any additional information you may have. )
Firefox 86.0

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.6.4
Revision: 34a78f0

[NOTE]: # ( Pick choices based on your environment )
Operating System: OpenSUSE Tumbleweed
Desktop Env: KDE
Windowing System: X11

**Comment by droidmonkey** [comment]
This was recently fixed in the extension, will be in the next release.
