### ISSUE TITLE
autofill dosn't allow to stay in a username field, but jumps to the password section, if entry for the website exists

### ISSUE THREAD

**Issue by aisbergde** [keepassxreboot/keepassxc#6284]
## Overview

Often I have this issue:
- I want to enter new or additional login data for a site, where some other login data is already stored in keepassxc
- But it is not possible to enter a new username, because keepassxc jumps to a password field when I try to enter something into the name field. I can't find any way to exit the password filed and to get into the username field

## Steps to Reproduce

1. use any site where you can register and where you was registered before (for example https://sourceforge.net/user/registration) 
2. try to enter something into the "username" field
3. this is not possible, because the cursor jumps to the "confirm password" field and wants to select an existing entry

## Expected Behavior

it should be possible to stay in the username field, for example to press esc when in the password field to be able to move to the username field. Or there should be an easy option to disable keepassxc for a moment to enable later again.

I tried:
- close keepassxc database to disable the browser magic => it doesn't work, input still jumps from username to password section
- using a different browser where the keepassxc extension is not installed or is disabled and try to register there
- disable keepassxc in the browser and enable later

## Actual Behavior

see above

## Context

KeePassXC - Version 2.6.4
Revision: 34a78f0

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows

**Comment by droidmonkey** [comment]
Thus was literally just reported and closed as duplicate. It's fixed in the upcoming version of the extension.
