### ISSUE TITLE
Not Opening Last File

### ISSUE THREAD

**Issue by shdawson** [keepassxreboot/keepassxc#6285]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
Hi,

Just upgraded to 2.0.3.

Not opening last used file. I am prompted to select a file. I have enabled this feature in settings.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. See above.
2. 
3. 

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
The last used file to be opened, where I then enter the password and proceed to use KeePassX.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
I am prompted to select a file.

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.0.3
Revision: 2.0.3

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows/Linux/macOS
Desktop Env: Gnome/KDE/XFCE/Mate/Cinnamon
Windowing System: X11/Wayland

LINUX

**Comment by droidmonkey** [comment]
We don't have a 2.0.3, are you using keepassx?

**Comment by shdawson** [comment]
Attached.
      
      Where do I need to post the bug?
      
      
      -SHD
    
    
      
      
    
    On 3/14/21 4:57 PM, Jonathan White
      wrote:
    
    
      
      We don't have a 2.0.3, are you using keepassx?
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view it on GitHub, or unsubscribe.
      [
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/keepassxreboot/keepassxc/issues/6285#issuecomment-798978441",
"url": "https://github.com/keepassxreboot/keepassxc/issues/6285#issuecomment-798978441",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by droidmonkey** [comment]
KeePassX is not maintained. You should install our program, KeePassXC

**Comment by shdawson** [comment]
Thank you.
      
      I have now installed KeePassXC.
      
      
      Kindest Regards,
      -S
    
    
      
    
    On 3/14/21 5:42 PM, Jonathan White
      wrote:
    
    
      
      KeePassX is not maintained. You should install our program,
        KeePassXC
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view it on GitHub, or unsubscribe.
      [
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/keepassxreboot/keepassxc/issues/6285#issuecomment-798985246",
"url": "https://github.com/keepassxreboot/keepassxc/issues/6285#issuecomment-798985246",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
