### ISSUE TITLE
Passthrough autofill login through RDP / LogMeIn to Program?

### ISSUE THREAD

**Issue by Meza100** [keepassxreboot/keepassxc#6287]
## Summary
Hello together,

I already created an entry with login and password for a program, which is only accessible via RDP on a server or via LogMeIn on a server. The settings for the autofill won't show the program window in KeepassXC. It's understandable, because the program is started on the server and not on the local client. Maybe is there a way to make this running?

## Examples
Example 1:
- Connect to a server via RDP.
- Start a program.
- Autofill the login-information.

Example 2:
- Connect to a server via LogMeIn.
- Start a program.
- Autofill the login-information.

## Context
This feature would be brilliant, because I have home-office and this is my workflow, which it won't be changed. I think, that this workflow will, due to corona-virus, used often.

## Another solution:
Maybe it is possible to passthrough the program windows to the local client, so that KeepassXC could recognise these windows.

Thank you!

**Comment by droidmonkey** [comment]
This is not possible. You can use entry level Auto-Type to select the rdp process and type in the selected window.
