### ISSUE TITLE
Double-clicking on the username should edit the entry

### ISSUE THREAD

**Issue by tredondo** [keepassxreboot/keepassxc#6289]
Double clicking on most columns of an entry, does something: on URL it launches it in a browser, on Title, Modified, Size, it edits the entry. But double-clicking the username does nothing.

KeePassXC - Version 2.6.4
Revision: 34a78f0

Qt 5.15.2
Debugging mode is disabled.

Operating system: KDE neon User Edition 5.21
CPU architecture: x86_64
Kernel: linux 5.4.0-66-generic

**Comment by droidmonkey** [comment]
It copies the username to the clipboard.
