### ISSUE TITLE
Overlapping password management icons under some circumstances

### ISSUE THREAD

**Issue by dajnz** [keepassxreboot/keepassxc#6290]
## Overview

All password management icons (**Generate password**, **Toggle password**, **Password match**, **Password do not match**) are getting overlapped and unable to use. Because of the same location for all the icons clicking always trigger **Generate password** action likely due to the icon for it is the topmost one when the icons are overlapped.

This issue detected on unlock screen and entry editing screen. See example screen-shots below.

## Steps to Reproduce
1. Run the KeePassXC;
2. If you have multiple KeePassXC databases previously opened/used, the first one (on the 1st tab) will be look OK, but others will have the issue;
3. Unlock a KeePassXC database;
4. Double-click any existing entry to open entry editing screen, the icons will be overlapped; 

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
![icons-issue-1-expected](https://user-images.githubusercontent.com/11261945/111296635-c0396700-865d-11eb-9ace-7fff43896148.png)

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
![icons-issue-1-actual](https://user-images.githubusercontent.com/11261945/111296657-c62f4800-865d-11eb-90ee-417de3d87402.png)
![icons-issue-2-actual](https://user-images.githubusercontent.com/11261945/111296670-caf3fc00-865d-11eb-8eb1-59b1b6931288.png)

## Context
As I noticed, if to expand or collapse a KeePassXC window the issue disappears for entry editing screen but not for unlock screen.

**System information**:

KeePassXC - Version 2.6.4
Revision: 34a78f0

Qt 5.5.1
Debugging mode is disabled.

Operating system: Ubuntu 16.04.7 LTS
CPU architecture: x86_64
Kernel: linux 4.4.0-204-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- libgcrypt 1.8.1

Operating System: Linux
Desktop Env: KDE
Windowing System: X11

**Comment by droidmonkey** [comment]
This is a qt bug, use the snap or appimage to fix this.
