### ISSUE TITLE
Trayicon is missing

### ISSUE THREAD

**Issue by danielporto** [keepassxreboot/keepassxc#6291]
## Overview
The tray icon is missing after installation. There is no option to enable/disable it.
Using Big Sur 11.2.3 on mac M1 

KeePassXC - Version 2.6.4
Revision: b93fbd1

Qt 5.15.2
Debugging mode is disabled.

Operating system: macOS 11.2
CPU architecture: arm64
Kernel: darwin 20.3.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (only unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
- libgcrypt 1.9.1

**Comment by droidmonkey** [comment]
The option is under application settings, scroll to the bottom

**Comment by danielporto** [comment]
Man I few stupid hahaha!
fixed
