### ISSUE TITLE
Twitter TOTP are wrong.

### ISSUE THREAD

**Issue by YuvrajRaghuvanshiS** [keepassxreboot/keepassxc#6292]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
Twitter TOTP does not work when created with KeePassXC either if it is a newly generated one or old one. I have tried copying kdbx file from my android where I use KeePassDX but that didn't work either. TOTP works when created with keepassdx on android but same kdbx file does not produce same totp on desktop.

## Context
[NOTE]: # ( Give us any additional information you may have. )
I have tried all custom settings while creating totp with no success

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.4
Revision: 34a78f0

Qt 5.15.2
Debugging mode is disabled.

Operating system: Windows 10 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.19042

**Comment by droidmonkey** [comment]
Sync your system time
