### ISSUE TITLE
Multiple OTP

### ISSUE THREAD

**Issue by johnrichardrinehart** [keepassxreboot/keepassxc#6293]
Currently, KeepassXC only supports a single OTP per entry. But, I have accounts with sites that have multiple 2FAs for different actions in the site.

**Comment by droidmonkey** [comment]
I like this and I don't like this. It is a niche feature for sure. The problem is it imposes significant UI changes and also backend code changes. I don't think this will get implemented,  but maybe after we overhaul the entry view.

**Comment by johnrichardrinehart** [comment]
Fair enough. Leave it open in case someone wants to implement?

**Comment by johnrichardrinehart** [comment]
@droidmonkey This issue was closed as "completed" couldn't find the PR/commit/release where this feature was implemented. Did I fail to find it or does "completed" mean something different than "implemented"?

Thank you.

**Comment by droidmonkey** [comment]
Just a github quirk, this is not being implemented

**Comment by soredake** [comment]
> Just a github quirk, this is not being implemented 

Better to close this as "wontfix" rather then "completed"

**Comment by droidmonkey** [comment]
It's just closed. There is no other choice, thanks

**Comment by soredake** [comment]
@droidmonkey there *is* choice
![изображение](https://github.com/keepassxreboot/keepassxc/assets/5204968/4edeb8be-ec25-471f-a5fa-3a5492e1f91c)

**Comment by droidmonkey** [comment]
Interesting, well doesn't really matter at the end of the day
