### ISSUE TITLE
iOS Simulator replaces password's characters by 'a'

### ISSUE THREAD

**Issue by stefan-sedlak** [keepassxreboot/keepassxc#6295]
## Overview
iOS Simulator replaces password's characters by 'a'.
It is caused by incorrect Key Code sent by KeePassXC.

You can verify the issue with iOS Simulator or utility [Key Codes](https://manytricks.com/keycodes/)

## Steps to Reproduce
1. move focus to  iOS Simulator text field or utility Key Code
2. trigger global shortcut to autotype password
3. select password

## Expected Behavior
There is correct password in iOS Simulator text field
There are correct Keys/Key Code in utility Key Code

## Actual Behavior
All characters are replaced with 'a' in iOS Simulator text field.
All key events have incorrect Keys.

## Context
All key events displayed in utility Key Codes have:
- Key Code set to 0x0
- Modifiers set to 0x0 and
- Keys is interpreted as 'A' - I do not know reason  I guess lowest visible key is 4 - A

KeePassXC - Version 2.6.4
Revision: 34a78f0

Qt 5.15.2
Debugging mode is disabled.

Operating system: macOS 11.2
CPU architecture: x86_64
Kernel: darwin 20.3.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
- libgcrypt 1.9.1

Operating System: macOS

**Comment by droidmonkey** [comment]
This is most likely the exact same bug as #1833
