### ISSUE TITLE
Favicon download process issues

### ISSUE THREAD

**Issue by ghost** [keepassxreboot/keepassxc#6298]
## Overview

I have a couple of issues with the download process of favicons. Some could be considered feature requests, however they lean more on the bug report side.

(1) The download process bar shows the full URL. This is confusing as I would assume the downloader will try that URL exactly (which may be privacy-concerning). Instead, the source code will only try the FQDN and second-level domain. I think this should be reflected in the UI; showing only the URLs that are actually accessed. This should also be true if Duck Duck Go is used, showing the DDG URL instead of the entry's URL.

(2) I had many download problems behind my proxy. Clicking the close button results in an application crash. Do not remember whether clicking the cancel button did the same. But anyway, a long list of downloads can only be aborted as a whole and any already downloaded icons are lost if you click cancel/close. This is espescially annoying if you waited a few minutes of seemingly no progress (presumably because of the proxy).

(3) It seems the download stalls at some point or for some domains. I had to wait a few minutes for just 10 domains. And that was regardless of whether I used Duck Duck Go or not.

(4) I think this is technically a feature request: 
Instead of just trying `example.org/favicon.ico`, I wish the downloader would also parse the head of the html. Explicitly searching for `<link rel="shortcut icon" …` (also with rel: `icon`, `apple-touch-icon`, and `apple-touch-icon-precomposed`)

(5) This point may be connected to (2) and (3): It seems the download is performed sequentially? Parallelizing all requests could improve the download speed. But I do not know whether that is already the case.

## Steps to Reproduce
see above

## Expected Behavior
see above

## Actual Behavior
see above

## Context
see above

KeePassXC - Version 2.6.4
Revision: b93fbd1

Operating System: macOS
Desktop Env: –
Windowing System: ?

**Comment by droidmonkey** [comment]
Downloads are done in parallel

**Comment by emiliopedrollo** [comment]
Now with dark theme the application could look for `example.com/favicon-dark.ico` before the conventional url to fetch dark mode favicons (like what browsers do)
