### ISSUE TITLE
Strange icons if no database selected

### ISSUE THREAD

**Issue by cooperbang** [keepassxreboot/keepassxc#6299]
## Overview
If no database is selected KeePassXC shows strange icons in KeePassXC taskbar and menus.

## Steps to Reproduce
1. Fresh install of KeePassXC or Clear Database History
2. Open KeePassXC
3. No Database is selected

## Expected Behavior
All icons should be displayed correctly

## Actual Behavior
Icons e.g. for "open database" and "save database" look strange (just black and gray), also icons in menus...

KeePassXC - 2.6.4
Revision: 34a78f0

Operating System: Fedora Linux 33
Desktop Env: Gnome
Windowing System: Wayland

![KeePassXC](https://user-images.githubusercontent.com/75366896/111511562-294cd780-874f-11eb-90c9-8538f041b7ca.png)
![KeePassXC_menu](https://user-images.githubusercontent.com/75366896/111514258-d9bbdb00-8751-11eb-8210-6b2ef5a48dd9.png)

**Comment by phoerious** [comment]
See #5029

**Comment by cooperbang** [comment]
I don‘t think that https://github.com/keepassxreboot/keepassxc/issues/5029 is the same problem.

I don‘t have a 3rd party icon-set and don‘t use HiDPI.

**Comment by phoerious** [comment]
Still same issue. See #4963.

**Comment by cooperbang** [comment]
Sorry, if I take it up again...

As you can see in my screen recording (https://file.io/1Zb1t60apkoE), the icons turn correct after opening and closing "Help" --> "About"  Window.
In my opinion this is not the same issue as https://github.com/keepassxreboot/keepassxc/issues/4963 or https://github.com/keepassxreboot/keepassxc/issues/5029.

**Comment by phoerious** [comment]
This is not a KeePassXC issue. It's an issue of your Qt platform theme.

**Comment by cooperbang** [comment]
> This is not a KeePassXC issue. It's an issue of your Qt platform theme.

https://github.com/FedoraQt/QGnomePlatform/issues/81#issuecomment-819412261
`This is most definitely not a bug in QGnomePlatform, but looks like a bug in the app itself or Qt Wayland.`

**Comment by droidmonkey** [comment]
Considering we have no problems on X11 it is most likely Qt Wayland causing the fault. We have many other problems reported with users on Fedora 33 running Wayland on Gnome. Other Qt apps impacted as well.
