### ISSUE TITLE
[FR] Spell checking in the Notes field

### ISSUE THREAD

**Issue by tredondo** [keepassxreboot/keepassxc#6300]
Would it be possible to have spell checking in the Notes field?

I have significantly-sized notes for quite a few of my entries (personal details, various procedures, history of accounts etc.) and it would help to have them spell checked.

**Comment by droidmonkey** [comment]
Qt doesn't have a built in spell check feature so I am going to go with no. This is outside the scope of a password manager.

**Comment by tredondo** [comment]
I've just realized that it's also impossible to search in the Notes.

I have some notes for my bank entry, including account details, date of opening, registered address, PINs for several cards etc. I'd love to be able to search for, for example, the last 4 digits of a card, and see the PIN that I wrote down in the notes for it.

Is there any way to make text fields searchable?

(I know the general search does find entries whose notes contain the keyword; but it doesn't select where in the Notes that keyword was found)

**Comment by droidmonkey** [comment]
It is a feature request on the board

**Comment by michaelk83** [comment]
> This is outside the scope of a password manager.

@droidmonkey , a number of people have so far [requested search within the notes](https://github.com/keepassxreboot/keepassxc/issues/4864) (also [#3497](https://github.com/keepassxreboot/keepassxc/issues/3497#issuecomment-564453577) and others), there was an [older request for secure notes](https://github.com/keepassxreboot/keepassxc/issues/5202), and I've seen several users who appear to use the notes field for longer documents. Adding to that this spell-check request, would you consider some time in the future implementing a *separate* secure editor tool within the KPXC ecosystem (same as you have the browser plugin and some other pieces)?

The MVP would "only" need the following:
- A large, resizable text area (separate window from KPXC).
- Launch from an open entry in KPXC, so it doesn't need its own entry browser and so forth.
- Open and save as attachments in the existing .kdbx entry.
- Most importantly, the same memory- and other applicable protections as KPXC itself.

Later this can be enhanced to work with the notes field, search text, replace text, and eventually spell checking (there are some open source packages for that). It could eventually have basic formatting tools based on the .adoc format, and maybe a formatted view tab, but those are low priority.

I did a quick Google search. There are a number of "secure" editors available, but their security is questionable (and varies), and of course, they don't support .kdbx files. I got the impression that some of the other password managers do support something similar. Finally, KPXC itself is already more than *just* a password manager, as it can also handle SSH keys, certificates, and other attachments.

Should I post a separate FR to track this and gather feedback from other users?

---

> I have some notes for my bank entry, including account details, date of opening, registered address, PINs for several cards etc. I'd love to be able to search for, for example, the last 4 digits of a card, and see the PIN that I wrote down in the notes for it.

@tredondo , when [entry templates](https://github.com/keepassxreboot/keepassxc/issues/863) are implemented, most of that can be moved to the appropriate type of entries (bank account, credit card, ...). For now you can use [advanced search](https://keepassxc.org/docs/KeePassXC_UserGuide.html#_searching_the_database) to at least find the relevant entries (but as you wrote, it doesn't mark the matching part).

**Comment by droidmonkey** [comment]
See #2104

**Comment by michaelk83** [comment]
Thanks. Digging deeper, #2400 and #3383 are also relevant. Perhaps this should at least be added to the FAQ:

> Why is there no search inside the Notes field? How can I handle long secure documents in KeePassXC?
> - For large documents or long notes, use a .txt/.adoc/etc attachment, not the Notes field.
> - Associate that file type with an external editor such as [QOwnNotes](https://github.com/pbek/QOwnNotes).
> - You can open and edit the attachment from the [attachments interface](https://keepassxc.org/docs/KeePassXC_UserGuide.html#_attachments). This will use the external editor, and securely delete the temporary file when done.

Btw, are attachments included in the entry search?

My only remaining concern is the security protections of the external editor. Memory/ptrace access, core dumps, various temporary and backup files, and so forth. If this was part of the KPXC ecosystem, I can be reasonably sure that it will be handled correctly. With a 3rd party editor - not so much.

It doesn't need to be fancy to be useful. If it's kept in a separate repository, it won't pollute the main KPXC code, and any fancier features can come primarily from PRs. But anyway, this would be more or less covered by #3383.

**Comment by droidmonkey** [comment]
Once the core kdbxlib is separated out this  old be much easier to segment into a separate app. The kdbx xml file format is not conducive to a note taking experience. Version control would be high up on my list of desires. Merging is also a problem here. So a new or more common inner file format (post-decryption) would be highly desirable.

**Comment by tredondo** [comment]
> The MVP would "only" need the following

Agree that's scope creep.

The *only* thing I need from a search in the Notes field is to [highlight the results](https://github.com/keepassxreboot/keepassxc/issues/4864#issuecomment-938118252). Nothing more. Not even case-insensitive search.
