### ISSUE TITLE
Import from LastPass Button

### ISSUE THREAD

**Issue by melroy89** [keepassxreboot/keepassxc#6301]
## Summary

Create a dedicated import button for importing CSV file from LastPass.

## Examples

Just add an additional button, at the bottom next to KeePass:

![image](https://user-images.githubusercontent.com/628926/111550948-73e64800-877f-11eb-9b61-1d4cc2df5c27.png)

## Context

LastPass is now very limited, can only be used on 1 single device (either desktops or mobile), the sync is gone.

People are from this day on-wards searching for alternatives like KeePassXC. Thus, make the migration process as easy as possible, please!

Currently, people need to select the right CSV columns in order to import the data correctly, see [this blog post for example](https://blog.paranoidpenguin.net/2018/12/migrating-from-lastpass-to-keepassxc/).

Regards,
Melroy van den Berg

**Comment by droidmonkey** [comment]
There is no need for this button, lastpass exports csv which there is a button for and an import wizard to help align the fields.

**Comment by danger89** [comment]
Yes, that is also stated in my description. My point is, I would rather limit this import wizard complexity.

So the end-user don't need to think about selecting the right columns and more. Lowering the risk of mistakes during the import & most importantly have a smooth migration from LastPass to KeePass.

Again, more and more users are now searching for alternatives after lastpass changed their free product.

**Comment by droidmonkey** [comment]
The better placement for this would be in the actual CSV Import wizard to choose known alignment options and auto select those in the drop downs. Either way this process is incredibly easy and it is obvious which data goes where when you do the import. We really don't want to be in the business of making sure every vendor's custom csv format works all the time.

**Comment by danger89** [comment]
Therefor just limit it now to lastpass
