### ISSUE TITLE
opvault import picks wrong field for title of additional attributes

### ISSUE THREAD

**Issue by jnprbill** [keepassxreboot/keepassxc#6303]
When importing an opvault database, the text description of additional attributes are not imported correctly.  It picks an alphanumeric identifier for this field instead of the user configured plain text title.  The corresponding stored secret value imports correctly.

Example:  a custom field in 1Password named "Mother's Maiden Name" = "smith" imports as "9BA3C8BD97208B99_66E1" = "smith".

This is Keepassxc 2.6.4 on MacOS importing an opvault from 1Password 7.7.

**Comment by jnprbill** [comment]
Cannot reproduce with the original freddy.opvault provided by 1password.  Keepassxc imports custom fields correctly.  Verified with "company's FTP" login after opening the vault with 1Password 7.

However, when creating a new custom field in the existing "company's FTP" login, the new field titled "path2" synced as title 7E376C5715D14095965E5A7D5B47E626 while the original "path" field remained correctly imported.  Only the attribute name is impacted.

I can reproduce this issue with the keepassxc.opvault sample.  The only item with a custom field was the note.  

It appears something has changed in 1Password since freddy was created.

**Comment by droidmonkey** [comment]
Can you point to exactly which entry in keepassxc demo is failed? It's been a while since I touched this

**Comment by jnprbill** [comment]
"Secure Note".   "Custom Section - details" imports as "Custom Section_rg5t57rn5y4i3ue36u2n2havlq".

**Comment by droidmonkey** [comment]
I ran this through the debugger, the problem is that 1Password is not consistent with how field names are stored. Each section field has 4 parts (K, N, T, V) which correspond to "Kind", "Name", "Text", "Value". Custom fields add junk data to the name and the actual field name in text. Normal fields have valid data in Name and Text. We should actually be using the Text field in this context, so I am making that change.

**Comment by jnprbill** [comment]
Thanks,  I will build this tomorrow and test with a complex data set.

**Comment by jnprbill** [comment]
I tested with the included test data and the problem was resolved.  However, there was no change in my data set synced from 1Password 7.8 for MacOS.  The problem recurred.  I will try to figure out the difference between the two opvault files and look at the code, now that I know where to look.

**Comment by droidmonkey** [comment]
Can you make a sample opvault from that version for testing?

**Comment by jnprbill** [comment]
Not sure if it's okay to attach it here or if you need it somewhere else.  Passphrase = a.  

I used the 1Password *copy* function to copy a record created in 2011 into the sample vault.  Your fix corrected the field name upon import.  However, the section name has the original problem - showing the section N value.

I created a new record in the sample vault.  No issue with the import at all.  

[sample.zip](https://github.com/keepassxreboot/keepassxc/files/6201908/sample.zip)

**Comment by droidmonkey** [comment]
OK, I updated the PR with a fix for section names as well. Give that a try, and thank you for the sample database!

**Comment by jnprbill** [comment]
That worked great.  Thank you!

Since my database was originally in the Agilebits keychain format and imported to opvault in whatever version that first became available, it seems 1Password changed how that field was used without documenting it.
