### ISSUE TITLE
Username in detail pane shown while hide username is active

### ISSUE THREAD

**Issue by TrusterX** [keepassxreboot/keepassxc#6306]
## Overview

The user name is displayed even though hide username has been activated in the view.

## Steps to Reproduce

1. Open KeepassXC
2. click View → Hide Usernames
3. select an entry
4. view the Detail Pane

## Expected Behavior
The user name should also be hidden in the detail pane.

## Actual Behavior
The user name will displayed in the detail view:
![image](https://user-images.githubusercontent.com/6065454/111802745-a3f03100-88ce-11eb-9909-a2801e1d4569.png)

KeePassXC - Version 2.6.4
Revision: 34a78f0

Operating System: Fedora 33 Gnome X11

**Comment by BurninLeo** [comment]
Seems that this got buggier in version 2.6.6 ... now the password is displayed while the username is (still) hidden :)

![grafik](https://user-images.githubusercontent.com/15062876/144673870-44d380a7-f95c-4d6d-9c26-81af4ad5f302.png)

**Comment by droidmonkey** [comment]
Check out the view menu to fix your settings.

**Comment by BurninLeo** [comment]
Thanks @droidmonkey, I did not look into the "view" menu before. Also I found the option there to display the user names (the option to hide them has been checked for whatever reason). This reduces this issues' relevance a lot. Maybe just an issue of defaults? Or may I hit the wrong hotkey when I wanted to copy a password, once?

Actually, I would not have expected such a setting at all. Who would think up such a setting? If I do not want to show the passwords, I simply hide the column (as I did before). I just enabled the column out of interest and stepped over the passwords. Honestly, a colum with bullets only is somewhat ... only taking up space? 😄 

Anyway, its good to know that there is simply a setting to solve the issue, at least in 2.6.6. Thanks a lot!

**Comment by droidmonkey** [comment]
The setting always existed, the default is to hide them. The column of dots is useful to know you have a password set and if you double click the dots it'll be copied to the clipboard.

**Comment by phoerious** [comment]
These are two different settings. Password hiding in the entry preview panel is controlled by a separate setting in the security options. I don't think this makes much sense. View->Hide Passwords/Usernames should apply to everything. We won't change this behaviour in 2.7.x, but this is probably a decent TODO for 2.8.0.

**Comment by bk3355550-create** [comment]
username hidden how to see it

**Comment by bk3355550-create** [comment]
Quh*************@gmail.com
