### ISSUE TITLE
forbid plain password view per user group

### ISSUE THREAD

**Issue by steveqwe** [keepassxreboot/keepassxc#6307]
## Summary
[TIP]:  # additional password database access with plain passwords hidden
[NOTE]: # It would help really a lot for team work if you could specify in configuration of each user or user group if it can see the plain text version of a password.
1. you would need to update the "Database Credentials" settings to store at least two passwords - one for admin who has unrestricted view and one for a user which can use database but cannot display the passwords as a plain text.
2. you would have to hide the "shoe plain password" for such user.

## Examples
[NOTE]: # In the site detail the "show plain password" would be missing for non admin user.
![hide plain password](https://user-images.githubusercontent.com/12518549/111840111-30fdaf00-88fc-11eb-920b-88f54b11e1cd.png)

## Context
[NOTE]: # Simple demand, I need to let users connect to various sites without revealing the password to them. They do not need to know the password for their work just to login successfully.

**Comment by droidmonkey** [comment]
Unfortunately this is not the tool for you if that is the use case. KeePass, and by extension KeePassXC, does not have internal restrictions on data after the database is unlocked. Added visual blocks is a waste of time and does not improve security or keep your data safe. Anyone can export the database, copy/paste into notepad, Auto-Type into notepad, etc etc.
