### ISSUE TITLE
Crash when editing and saving the free form text field.

### ISSUE THREAD

**Issue by fernando-mc** [keepassxreboot/keepassxc#631]
## Expected Behavior

The application saves entries after editing and allows me to open edit them without crashing the application.

## Current Behavior

Program closes instead of saving an entry when pressing OK from the edit entry view.

## Possible Solution

Not sure the reason for the bug but the workaround it just to reopen the DB.

## Steps to Reproduce (for bugs)

1. Searching for an entry
2. Find two related entries
3. Open one and edit the Notes text field
4. Cut a medium snippet of text (50ish chars) from Notes, removing the characters
5. Click OK
6. Program closes

I can provide crash reports as needed.

## Context

Trying to save and edit databases is a little annoying because this happens often enough I have to restart my application several times just to make changes to one or two entries.

## Your Environment

* KeePassXC version/commit used: (can be found under Help -> About)
* Qt version (e.g. Qt 5.3): Qt 5.8.0
* Compiler (e.g. Clang++3.6.0): Unclear. libgcrypt 1.7.6 is listed below Qt version.
* Operating System and version: OS X El Capitan - 10.11.6

**Comment by weslly** [comment]
I've tried several times but couldn't reproduce this. 

How often does this happen? Do you have auto-save enabled?

**Comment by fernando-mc** [comment]
Current general settings:
<img width="784" alt="screen shot 2017-06-10 at 2 34 33 pm" src="https://user-images.githubusercontent.com/6182464/27006502-f761656c-4de9-11e7-9ccf-f77aa41ccd9a.png">

I can consistently reproduce this. Try with these steps:

1. Open a db with many entires (might not be required but mine has many)
2. Search for an entry (in this case my search yields two results
3. Enter a string into the notes field (at least 100 chars) . Cut and paste that string
4. Close entry with OK
5. Save
6. Potentially repeat with another entry from the search.

It doesn't happen on every save or edit, but maybe 1/4. If I do it a few times it will crash though.

@weslly would crash logs be useful in this case?

**Comment by fernando-mc** [comment]
From the Crash logs: 
```
Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       EXC_I386_GPFLT
Exception Note:        EXC_CORPSE_NOTIFY
```

**Comment by TheZ3ro** [comment]
@fernando-mc can you create a new DB and try reproducing on that? If the same thing happen upload that db here, thanks

**Comment by fernando-mc** [comment]
@TheZ3ro Had to compress it becuase github doesn't support uploading the db by itself. The DB password is `password`
[error_testdb.kdbx.zip](https://github.com/keepassxreboot/keepassxc/files/1066134/error_testdb.kdbx.zip)

Confirmed this happens in the test DB. I'll send you a video example for the reproduction steps.

**Comment by fernando-mc** [comment]
Demo video:
[error_demo.zip](https://github.com/keepassxreboot/keepassxc/files/1066137/error_demo.zip)

Editing my reproduction steps. It appears you have to edit and save the same entry.

**Comment by weslly** [comment]
I can reproduce it now, but it only crashes on v2.1.4, I couldn't reproduce it with the development branch build. It was either fixed by a commit after v2.1.4 or by Qt 5.9 LTS. 

Let's leave this open until v2.2.0 is out so you can test it again.

**Comment by fernando-mc** [comment]
@weslly Sounds good, thanks!

What's the best way to trigger a notification on this when that happens?

**Comment by weslly** [comment]
@fernando-mc v2.2.0 should be out soon, I'll mention you in this issue when it gets released.

**Comment by fernando-mc** [comment]
@weslly Awesome. Thank you!

**Comment by weslly** [comment]
@fernando-mc 2.2.0 is out, can you try it now?

**Comment by fernando-mc** [comment]
@weslly Updates look great. Unfortunately I verified this issue is persisting in 2.2.0.

It's kind of a weird edge-case so I'd understand if this is not prioritized in terms of development.

**Comment by weslly** [comment]
@fernando-mc Can you check if the issue persists in the v2.3 beta?

**Comment by fernando-mc** [comment]
@weslly You can close this - I moved off of OS X and can't even reproduce it with 2.2.0 anymore.

Also it's a super edge case.
