### ISSUE TITLE
Permission denied error when saving (writing) KeePass DB file on macOS Catalina (10.15.7)

### ISSUE THREAD

**Issue by pragma2k** [keepassxreboot/keepassxc#6310]
I can open my DB file, so reading is not a problem, but when I try to save it after making any change, I get a permission denied error.

The file's standard permissions are ugo=rwx (777), and there are a couple of other users in the "extended" (macOS-specific) ACL that also have full read-write access. The containing directory of the file also has 777 standard permission, with no "extended" ACL at all.

There are no deny permissions or restrictions of any kind on the file, the containing directory, or any level above it.

Debug Info:
KeePassXC - Version 2.6.4
Revision: 34a78f0

Qt 5.15.2
Debugging mode is disabled.

Operating system: macOS 10.15
CPU architecture: x86_64
Kernel: darwin 19.6.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
- libgcrypt 1.9.1

**Comment by droidmonkey** [comment]
This is 100% a permissions problem. I'm not sure what we could do for you in this situation?

**Comment by droidmonkey** [comment]
Have you tried saving something else to that folder? (Like a text document) Have you tried disabling safe saves within keepassxc settings?
