### ISSUE TITLE
"Copy password" button copies the original password the entity had when it was opened

### ISSUE THREAD

**Issue by raffaem** [keepassxreboot/keepassxc#6313]
## Overview
The "Copy password" button
![image](https://user-images.githubusercontent.com/54762742/111871270-4e2c8f00-8989-11eb-9427-3b60efe103fa.png)
Copies the password the entity had when it was opened.  If you change the password, the old one is copied.

For new entities, it doesn't copy anything, even after to establish a password by "Generate password" button
![image](https://user-images.githubusercontent.com/54762742/111871292-6e5c4e00-8989-11eb-821a-7ed56101d723.png)

## Steps to Reproduce
1. Create a new entity
2. Generate a password
3. Click the "copy password" button in the toolbar

## Expected Behavior
The generated password should be copied

## Actual Behavior
Nothing is copied

## Context
NA

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.4
Revision: 34a78f0

Qt 5.14.2
Debugging mode is disabled.

Operating system: Ubuntu 20.10
CPU architecture: x86_64
Kernel: linux 5.8.0-45-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- libgcrypt 1.8.5

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: Gnome
Windowing System: X11

**Comment by droidmonkey** [comment]
I can't decide if this is actually a bug or not. It is definitely a UX issue, but technically you have not committed the changes to an entry if you have not pressed apply or OK. The data drawn from those buttons is of the underlying entry, not the UI.

**Comment by raffaelemancuso** [comment]
ok good to know the correct way to handle this

**Comment by derek-v-s** [comment]
@raffaem @droidmonkey I suggest re-opening this. I did two password resets on an account before figuring out this was the problem. If copying directly from the password UI entry is inconsistent with the overall design, then maybe disable the copy password button after the entry has been changed, and enable it after the apply button has been pressed.

**Comment by droidmonkey** [comment]
Dude this is 4 years old. Make sure you are running 2.7.10

**Comment by derek-v-s** [comment]
Ah. Ubuntu 24.04.2 LTS provides version 2.7.6. Can you link to the commit that addressed this?

**Comment by droidmonkey** [comment]
https://github.com/keepassxreboot/keepassxc/pull/10853

**Comment by derek-v-s** [comment]
Thank you! 😎
