### ISSUE TITLE
Preview panel doesn't refresh if entry is moved into another db

### ISSUE THREAD

**Issue by drasar** [keepassxreboot/keepassxc#6316]
## Overview
If I have a focus on a password entry in the db, then I can see its preview in the Preview Panel. That's correct. But if I move that entry into another db, then I can see that item still in the Preview Panel of the original db.

Furthermore, If I click e.g. the "eye button" in that panel, then application crashes (Segmentation fault).

## Steps to Reproduce
1. Create empty DB1 and DB2.
2. Create ITEM0[12] entries in DB2.
3. Click ITEM02 - then you can see its preview in the Preview Panel (must be enabled in the View menu).
4. Move ITEM02 from DB2 to DB1 (drag & drop).
5. Go back to DB2 - ITEM02 will leave in the the Preview Panel
6. Click the "eye button" in the Preview Panel -> app crashes

## Expected Behavior
Preview Panel in DB2 should be refreshed when ITEM02 is moved into DB1. I guess that this will be achieved by the focus change to a different (existing) item.

## Actual Behavior
ITEM02 leaves in the Preview Panel of DB2 after its move into DB1.

## Screenshot
![obrazek](https://user-images.githubusercontent.com/2562023/111919447-4f91b080-8a8a-11eb-8080-d644429f4dd8.png)

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.2
Revision: e9b9582

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: XFCE
Windowing System: X11

**Comment by droidmonkey** [comment]
This was fixed in 2.6.3
