### ISSUE TITLE
KeePassXC doesn't appear in alt-tab until you enter and exit Overview

### ISSUE THREAD

**Issue by puelp** [keepassxreboot/keepassxc#6321]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. start KeePassXC
2. press alt-tab

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
KeePassXC should be in the alt-tab list.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
KeePassXC is NOT in the alt-tab list.

And that causes wonky stuff to happen, like the last window (that was in focus before KeePassXC was started) being treated as the 'current' window, so when you press alt-tab, the SECOND-to-last window gets brought up.

Temporary workaround:
1. press the Super/Windows key and enter GNOME's overview mode
2. exit the overview mode
3. now for some reason KeePassXC is in the alt-tab list, all fine and dandy.

## Context
[NOTE]: # ( Give us any additional information you may have. )
Fedora 33, GNOME 3.38.4 desktop environment, Wayland.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.4
Revision: 34a78f0

Qt 5.15.2
Debugging mode is disabled.

Operating system: Fedora 33 (Workstation Edition)
CPU architecture: x86_64
Kernel: linux 5.11.7-200.fc33.x86_64

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- libgcrypt 1.8.7

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: Gnome
Windowing System: Wayland

**Comment by droidmonkey** [comment]
Do you have anything related to deepin installed?

**Comment by puelp** [comment]
Nothing related to Deepin.

I didn't change much from the Fedora 33 GNOME defaults. No other DEs and only a handful of third-party applications installed.

**Comment by droidmonkey** [comment]
Make sure this loading indicator goes away before you test again. Once this indicator went away then KeePassXC showed up in the Alt+Tab list. This doesn't seem to be related to KeePassXC at all.

![image](https://user-images.githubusercontent.com/2809491/112226936-3feaa700-8c05-11eb-8a0f-c5c8d3767747.png)

**Comment by puelp** [comment]
I see. That indeed is the case.

However, no other program suffers from this issue. Maybe a library that KeePassXC is using is the cause?

**Comment by droidmonkey** [comment]
Everything about Fedora 33 seems broken to me from our app perspective. Definitely the number one problematic Linux variant right now.

**Comment by droidmonkey** [comment]
There is nothing we can do about this issue

**Comment by puelp** [comment]
So what can be done to fix the issue? To which project should I report this issue?

I imagine the fact that it's a Fedora-specific issue narrows the field a bit?

**Comment by puelp** [comment]
So what can be done to fix the issue? To which project should I report this issue?

I imagine the fact that it's a Fedora-specific issue narrows the field a bit?

**Comment by droidmonkey** [comment]
It does it need to be fixed? It shows up in alt tab list once the indicator goes away. What that indicator is representing I have no idea. This only happens on Fedora 33, Gnome, Wayland.
