### ISSUE TITLE
KeePassXC do not start on centos 8

### ISSUE THREAD

**Issue by device-x** [keepassxreboot/keepassxc#6322]
## Overview
KeePassXC do not start on centos 8 with errors 

```
QSocketNotifier: Can only be used with threads started with QThread
QObject::connect: No such signal QPlatformNativeInterface::systemTrayWindowChanged(QScreen*)
```
It was happens after update
```
    Upgrade  keepassxc-2.6.4-1.el8.x86_64                                            @epel
    Upgraded keepassxc-2.6.3-2.el8.x86_64                                            @@System
```

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.6.4

[NOTE]: # ( Pick choices based on your environment )
Operating System: CentOS Linux release 8.3.2011
Desktop Env: Gnome 
Windowing System: Wayland

**Comment by device-x** [comment]
I find keepassxc-2.6.3-2.el8.x86_64.rpm - it works fine

**Comment by droidmonkey** [comment]
Those aren't errors, just warnings. We don't maintain the centos package, please file a report with the package maintainer.
