### ISSUE TITLE
Cannot access to useful directories (/media, /mnt...) with v2.6.4: "permission denied"

### ISSUE THREAD

**Issue by l0f4r0** [keepassxreboot/keepassxc#6324]
## Overview
Since I've upgraded to KeePassXC 2.6.4, I cannot access to my .kdbx on /media anymore ("permission denied")

## Steps to Reproduce
1. Upgrade to KeePassXC 2.6.4 from 2.6.3
2. Click on "Open a database"...
3. A popup displays the following error message: "Could not read the contents of media. Error opening directory '/media': Permission denied"

## Expected Behavior
Access to /media so I can select my usual database to be opened by KeePassXC

## Actual Behavior
Error message: "Could not read the contents of media. Error opening directory '/media': Permission denied"

NB: Other directories are not accessible as well (/etc, /mnt...). /home is OK

## Context
Everything worked fine under KeePassXC 2.6.3
I've not upgraded anything else

Please note that my .kdbx file is located inside a Veracrypt container mounted on /media/veracrypt1
That's why I need to access /media from KeePassXC (not an issue before today)

I've tried via CLI as well:
```
keepassxc /media/veracrypt1/database.kdbx
Qt: Session management error: Authentication Rejected, reason : None of the authentication protocols specified are supported and host-based authentication failed
```
Here are the permissions:
```
namei -l /media/veracrypt1/database.kdbx
f: /media/veracrypt1/database.kdbx
drwxr-xr-x root   root   /
drwxr-xr-x root   root   media
drwx------ l0f4r0 l0f4r0 veracrypt1
-rwx------ l0f4r0 l0f4r0 database.kdbx
```

## Debug info
KeePassXC - Version 2.6.4
Revision : 34a78f0
Distribution : Snap
Qt 5.9.5
Debug mode is deactivated

Architecture : x86_64
Kernel : linux 5.10.0-0.bpo.3-amd64

Operating System: Linux (Debian 10)
Desktop Env: XFCE
Windowing System: X11

**Comment by droidmonkey** [comment]
Please read our FAQ about snaps. Located at https://keepassxc.org/docs

**Comment by l0f4r0** [comment]
Thanks a lot for pointing me to the FAQ!

After investigation, this behavior seems normal for snaps so I've configured the following:
`sudo snap connect keepassxc:removable-media`
and it works now :)

My previous version (2.6.3) was already a snap and I don't think I ever connected the plug removable-media (I was not even aware of it).
So why do I experience this behavior only now starting from 2.6.4? Is the application packaged or built differently?

**Comment by droidmonkey** [comment]
Nothing changed with exception of using a different compression method which is not relevant
