### ISSUE TITLE
TOTP for securing your KeePassXC database

### ISSUE THREAD

**Issue by QuAzI** [keepassxreboot/keepassxc#6325]
As it is too easy to get Password+File in compromised system and YubiKey is not distributed enough and may raise questions and can't be used with phone (KeePassDroid n other forks) it would be nice to have TOTP solution.
The same way TOTP should be required only first time when you try to open container with specific path from current user and then this part of key should be encrypted with machine id as salt and stored in depth of user settings.

**Comment by droidmonkey** [comment]
This is not possible. If you want a second factor you can use a YubiKey or OnlyKey or a key file that you store separately from the database.

**Comment by QuAzI** [comment]
I want THIRD factor without a highly specialized device that attracts extraneous attention. As example in some countries you can have problems even with government if they found non licensed crypto devices. Also this devices you can't buy locally

**Comment by droidmonkey** [comment]
It's not possible to use TOTP in this manner. Please read on other issues requesting this feature.
