### ISSUE TITLE
command+F doesn't work correctly 

### ISSUE THREAD

**Issue by matthijsbro** [keepassxreboot/keepassxc#6326]
## Overview
When the search bar is not visible in the toolbar, cmd+F does not activate search. The window is standard not wide enough to show it, you have to resize the window. The search bar cannot be placed to the front of the toolbar. 
(what does movable toolbar option do by the way?)

## Steps to Reproduce
1. Open Keypass
2. cmd+F while search bar is not visible
3. type something to search

## Expected Behavior
When you start typing after cmd+F searching starts.

## Actual Behavior
nothing happens

KeePassXC - 2.6.4
Revision: 34a78f0

Operating System: macOS 11.2.3

**Comment by droidmonkey** [comment]
Fixed already for next version
