### ISSUE TITLE
Invalid credentials provided, HMAC mismatch via GUI but ok with CLI

### ISSUE THREAD

**Issue by karawitan** [keepassxreboot/keepassxc#6328]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
Opening db.kdbx via GUI, gives error "Invalid credentials provided", (HMAC mismatch). But "keepassxc-cli ls db.kdbx" works with the same password.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1.  Open a database.kdbx with keepassxc (GUI)
2.  Type the password

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
1. The database may be opened sucessfully with GUI

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
3.  Error message is shown
```
"Error while reading the database: Invalid credentials were provided, please try again.
If this reoccurs, then your database file may be corrupt. (HMAC mismatch)"
```

## Context
[NOTE]: # ( Give us any additional information you may have. )
The db.kdbx was created using the keepassxc, same version AFAIK.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.1
Revision: 9a35bba

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: Gnome
Windowing System: Wayland

**Comment by karawitan** [comment]
no, gui do not unlock when the password is visible, thanks for trying to help :-)

**Comment by droidmonkey** [comment]
Then you are either not opening the same database file or you are mistyped your password. I assume you are not using a key file or yubikey.

**Comment by karawitan** [comment]
Ok many thanks to your help, indeed, it turns out that I had mistakenly choosen a keyfile. When emptying the "Key File:" field, everything is now working great !
