### ISSUE TITLE
Segmentation fault on Ubuntu 20.04 Snap

### ISSUE THREAD

**Issue by lapisdecor** [keepassxreboot/keepassxc#6329]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
Segmentation fault when starting Ubuntu snap

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
```
luis@u18:~$ keepassxc

(keepassxc:4554): Gtk-WARNING **: 17:23:12.605: Theme parsing error: gtk.css:1566:23: 'font-feature-settings' is not a valid property name

(keepassxc:4554): Gtk-WARNING **: 17:23:12.618: Theme parsing error: gtk.css:3616:25: 'font-feature-settings' is not a valid property name

(keepassxc:4554): Gtk-WARNING **: 17:23:12.620: Theme parsing error: gtk.css:4078:23: 'font-feature-settings' is not a valid property name
Gtk-Message: 17:23:12.671: Failed to load module "canberra-gtk-module"
Gtk-Message: 17:23:12.674: Failed to load module "canberra-gtk-module"
Qt: Session management error: Could not open network socket
Fontconfig warning: FcPattern object weight does not accept value [0 210)
Falha de segmentação
```

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
it should open the app

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Segmentation fault

## Context
[NOTE]: # ( Give us any additional information you may have. )
it was working yesterday

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION (snap version)
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows/Linux/macOS
Linux
Desktop Env: Gnome/KDE/XFCE/Mate/Cinnamon
Gnome
Windowing System: X11/Wayland
X11

**Comment by lapisdecor** [comment]
I was able to start it with:
`sudo rm /var/cache/fontconfig/*
rm ~/.cache/fontconfig/*
fc-cache -r`

**Comment by droidmonkey** [comment]
This is a known issue with snaps, not keepassxc
