### ISSUE TITLE
Touch ID does not work with M1 MacBook Pro.

### ISSUE THREAD

**Issue by brainard52** [keepassxreboot/keepassxc#6330]
## Overview
I am unable to unlock my database with Touch ID after checking the "TouchID for Quick Unlock" box. 

## Steps to Reproduce
1. Launch KeepassXC
2. Check the "TouchID for Quick Unlock" box
3. Unlock database with passphrase
4. Close the database
5. Place registered fingerprint on Touch ID sensor

## Expected Behavior
After completing steps 1-5 under "Steps to Reproduce", the database should unlock

## Actual Behavior
After completing steps 1-5 under "Steps to Reproduce", the database does not unlock. The interface gives no indication that any action had been taken at all. 

## Context
<img width="780" alt="Screen Shot 2021-03-23 at 10 52 28 AM" src="https://user-images.githubusercontent.com/1023838/112194209-df884500-8bc5-11eb-92ea-41738703028b.png">
<img width="912" alt="Screen Shot 2021-03-23 at 10 52 55 AM" src="https://user-images.githubusercontent.com/1023838/112194280-edd66100-8bc5-11eb-8585-0a0419cf39e7.png">
<img width="780" alt="Screen Shot 2021-03-23 at 10 53 32 AM" src="https://user-images.githubusercontent.com/1023838/112194376-047cb800-8bc6-11eb-8b9c-7092d081287d.png">

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.4
Revision: b93fbd1

Qt 5.15.2
Debugging mode is disabled.

Operating system: macOS 11.2
CPU architecture: arm64
Kernel: darwin 20.3.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (only unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
- libgcrypt 1.9.1

Operating System: macOS 11.2.3 (20D91) on MacBookPro17,1

**Comment by droidmonkey** [comment]
After locking the database, you need to check the box and press unlock. Then the fingerprint request dialog will appear.

**Comment by brainard52** [comment]
Is it supposed to require my password when I start keepass?

**Comment by droidmonkey** [comment]
Yes, TouchID unlock is only after the intial unlock up until KeePassXC is shut down. Afterwards you need to enter the full password again.
