### ISSUE TITLE
Compatibility with qt5ct user style sheets

### ISSUE THREAD

**Issue by jlindgren90** [keepassxreboot/keepassxc#6336]
## Summary
When using the Classic / Platform-native theme, user style sheets configured in `qt5ct` currently don't have any effect in KeePassXC. This is because KeePassXC sets its own application-wide style sheet (`classicstyle.qss`).

I'm wondering how difficult it would be to avoid using an application-wide style sheet in the Classic / Platform-native theme, and only apply style sheets to the widgets that need them (e.g. `DatabaseOpenWidget` and `DatabaseWidget`). This would allow user style sheets set in `qt5ct` to continue working.

(There are also global padding overrides for `QToolTip` and `QLineEdit` in `classicstyle.qss`. I'm not sure why those are there.)

## Examples
I don't have any working prototype, but I did a quick test of removing the `setStyleSheet` call in `Application.cpp`, and verified that my user styles took effect.

## Context
I am using Qt 5's built-in Fusion theme with a custom color palette and a few style sheet tweaks to make it into a decent dark theme. Without the style sheet tweaks, some UI elements (particularly menus) of KeePassXC have pretty low contrast in the Classic / Platform-native theme.

This is certainly a low-priority item, especially since KeePassXC includes its own dark theme already.

**Comment by cooperbang** [comment]
I´m wondering if the same applies to QGnomePlatform? 
There also are problems with icons and Title Bars in combination with KeePassXC.

**Comment by jlindgren90** [comment]
I don't anything about QGnomePlatform. I did find a way to fix this on the `qt5ct` side, though:
https://sourceforge.net/p/qt5ct/tickets/86/

**Comment by droidmonkey** [comment]
Great that is the much better option and would fix other applications in the same situation.
