### ISSUE TITLE
Sort group for Auto-Type is from Z to A (Please turn from A to Z)

### ISSUE THREAD

**Issue by LHBL2003** [keepassxreboot/keepassxc#6341]
EN: Improvement: 
Please specify the sorting for the Auto Type for the Group column from A to Z. (For "Select the entry for Auto-Type")

Reason:
The entries are currently sorted from Z to A. So you have to create a folder "X_General", for example, so that the results are above.
"_Generally" is also at the bottom, although it should be at the top.
You can change the sorting temporarily, but you have to repeat this every time.

Thank you

-------------------------------------
DE: Verbesserung: 
Bitte die Sortierung beim Auto Type für die Spalte Group von A bis Z festlegen. (Bei "Wählen Sie den Eintrag für Auto-Type")

Grund:
Aktuell werden die Einträge von Z nach A sortiert. Somit muss man sich z.B. einen ordner "X_Allgemein" anlegen, damit die Ergebnisse oben sind.
Auch "_Allmein" ist ganz unten, obwohl es oben stehen müsste.
Mann kann die Sortierung temporär ändern, muss dies aber jedes mal wiederholen.

Danke

**Comment by droidmonkey** [comment]
Already fixed
