### ISSUE TITLE
Key database being corrupted?

### ISSUE THREAD

**Issue by Gooberpatrol66** [keepassxreboot/keepassxc#6342]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
Adding new entries will cause unexpected things to happen after the program is closed and re-opened, like the new entry will disappear, or existing entries will disappear, or entries will move between folders.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. make a new entry
2. close keepass
3. open it again

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

## Context
[NOTE]: # ( Give us any additional information you may have. )
Qt 5.15.2
Debugging mode is disabled.

Operating system: Gentoo/Linux
CPU architecture: x86_64
Kernel: linux 5.10.10-x86_64

Enabled extensions:
- SSH Agent
- Secret Service Integration

Cryptographic libraries:
- libgcrypt 1.8.6

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.6.3
Revision: beae186

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: KDE
Windowing System: X11

**Comment by droidmonkey** [comment]
Are you sharing your database with others? Are you storing it in a way that it could be getting overwritten with a previous version?

**Comment by Gooberpatrol66** [comment]
The database is on an NFS share, but I am the only person with access to it. The problem happens even when the share is only mounted by one computer at a time.

**Comment by droidmonkey** [comment]
Does this happen when you use a locally stored database?

**Comment by Gooberpatrol66** [comment]
I'm not sure.

**Comment by Gooberpatrol66** [comment]
I have imported a .csv from a backup database into a new test database on my local hard disk, and when i close the database and reopen it, nearly all of the entries disappear.

**Comment by droidmonkey** [comment]
Needless to say you are the only person experiencing this problem. Have you tried to use our appimage to isloate the problem?

**Comment by IanBurry** [comment]
He's not the only one noticing this behavior. I've suspected it for months now, so I started taking screen shots whenever I added a new entry and I can see that entries will disappear over time

**Comment by droidmonkey** [comment]
If this were true then out unit tests would never pass....

**Comment by droidmonkey** [comment]
Let us know if you can define a simple reproducible process for this.
