### ISSUE TITLE
Recent databases functionaly ineffective due to absolute path being saved instead of symlink

### ISSUE THREAD

**Issue by Fitzsimmons** [keepassxreboot/keepassxc#6345]
## Overview
I store my database inside keybase filesystem, which is exposed on linux via an ephemeral path in `/run/user/...` which changes on each boot. However, keybase provides a consistent symlinked file path on `/keybase/...`. Unfortunately KeePassXC is dereferencing that symlink to its absolute path when I load, which is fine once, but not when I relaunch the app after a restart:

![image](https://user-images.githubusercontent.com/418066/112645478-e3fa6b00-8e1c-11eb-9dff-388cac4238f2.png)

The recent databases functionality is not effective for me because KeePassXC does not save a file path that remains consistent.

## Steps to Reproduce
1. Create a symlink to a KeePassXC database
2. Open that database in KeePassXC via its symlink
3. Close KeePassXC
3. Change the location of the database file and also update the symlink to point to the new path

## Expected Behavior
1. Upon reopening KeePassXC, it has stored the path to the symlink instead of the absolute path, making it possible to reopen the database from saved history

## Actual Behavior
1. Upon reopening KeePassXC, the same database cannot be loaded from history and must be manually selected from the file dialog again

## Context
```KeePassXC - Version 2.6.4
Revision: 34a78f0
Distribution: Flatpak

Qt 5.15.2
Debugging mode is disabled.

Operating system: KDE Flatpak runtime
CPU architecture: x86_64
Kernel: linux 5.8.0-7642-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
- libgcrypt 1.8.7
```

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: Gnome
Windowing System: X11

**Comment by droidmonkey** [comment]
#5209
