### ISSUE TITLE
Sort passwords by 'Most recently copied to cliboard'

### ISSUE THREAD

**Issue by puelp** [keepassxreboot/keepassxc#6349]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
Ability to sort the password list by 'Most recently copied to clipboard', allowing you to see at a glance which passwords you most recently used and making it easy to speedily access them.

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )
It would be similar to the Modified or Accessed columns. It would sort by the date when the password was last copied to clipboard, and display said date in the column.

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
It would be useful for people like me who have a ton of passwords but are too busy or too perfectionist-anxious to try to organize their unwieldy number of passwords. This option would provide a nice middle-ground between organization and accessibility.

**Comment by droidmonkey** [comment]
We are not going to do this our track this data point, sorry.

**Comment by puelp** [comment]
May I ask why?

**Comment by droidmonkey** [comment]
See #2005
