### ISSUE TITLE
Lock individual databases

### ISSUE THREAD

**Issue by adatum** [keepassxreboot/keepassxc#635]
Currently, there is a button on the toolbar to lock all databases. Sometimes it is useful to lock one or more databases, but not all, similar to how there is the option to close individual databases. 

A menu item under "Databases" to lock that database would be great. Optionally, the "Lock databases" button on the toolbar could have a drop down option to choose to lock all or just the currently viewed database.

**Comment by Hativ** [comment]
I think that is an important feature. If I do not need one (of about 4-5) databases I would like to lock that one - only that one.

Additionally, in the german translation the button title is singular ("Datenbank sperren" instead of "Datenbank**en** sperren"), what often annoyes me if I forget the wrong behaviour/naming.

**Comment by erikvanoosten** [comment]
@Hativ You can create an account on https://www.transifex.com/keepassxc/keepassxc and change the translation. It is quite quick and easy to update a translation.

**Comment by chron-isch** [comment]
I would even go one step further and request database specific lock-timeouts.

With the introduction of freedesktop.secrets.service support it's has more or less become necessary to keep at least one database open (or evolution, networkmanager and a host of other applications will complain about missing password after a while).

Obviously I don't like having ALL my passwords(like crypto keys, work passwords, and so on) exposed so I would like to split it up into multiple databases with diffrent lock-timeouts or in case of the fredesktop.secrets.service database no lock-timeout at all and just lock it when the session is locked or the lid is closed.

**Comment by octo-pito** [comment]
Being able to lock individual database is especially important when you handle SSH keys for GitHub using KeePassXC, eg. switching between personal/professional accounts. As for now, I use the workaround of locking all, then unlocking only the one I want.

**Comment by droidmonkey** [comment]
Implemented in 2.7.0

**Comment by adatum** [comment]
> Implemented in 2.7.0

@droidmonkey 
That's great! Thank you so much for the efforts of maintaining and improving this awesome password manager!
