### ISSUE TITLE
X11 Auto-Type breaks layout switch if Num Lock is on

### ISSUE THREAD

**Issue by hifi** [keepassxreboot/keepassxc#6350]
## Overview
Only if Num Lock is ON layout switching will get stuck after Auto Type is performed if some modifiers are used to generate a special character. Toggling Num Lock off/on will restore layout toggle. Performing Auto Type with Num Lock OFF will not trigger this.

Many thanks to @stefan123t for figuring out how to consistently recover from this as it also gave a way to consistently reproduce it!

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. `setxkbmap eu,fi -option grp:alt_shift_toggle`
2. Create a pattern that has `½` in it (exists in FI layout)
2. Make sure Num Lock is ON
3. Perform Auto Type with  the pattern

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
X11 is not a broken mess :hankey: 

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Layout toggle (alt-shift) does not work.

**Comment by stefan123t** [comment]
Dear @hifi
I was only able to recover using NumLock twice/thrice.
Maybe you can add an example pattern that will trigger the error. I suspect it should be a symbol which can be reached using Shift+<one of the number keys 1234567890 above the characters>.
But you seem to be able to know more, I was not yet able to reproduce the issue at will.
Kind regards,
Stefan

**Comment by stefan123t** [comment]
I see you sent in a couple of changes. Is there any hash I could rebuilt from, that draws in all your fixes for a local test in the coming weeks ?

**Comment by hifi** [comment]
The repro steps in this issue were the ones I could reliably brick Alt-Shift toggling and only recover with Num Lock. It may be that with some other combinations it gets bricked even more but I suspect I've now completely fixed this as we will avoid trying to release any modifiers (including Num Lock). The character in question caused the issue but not many others. It's important to have the specific layouts in use so that it will pick the right modifier combination that will break switching.

Even though there's a related PR for #6351 it should work standalone already for testing the stuck Alt-Shift combination. So if you're able to build it like it stands you shouldn't hit the issue anymore if my fix is correct. I will rebase it when the related PR is merged so it doesn't abort silently if some modifiers are held down.

**Comment by stefan123t** [comment]
@hifi did you also test for someone using CapsLock in ALLCAPS mode ?
I should probably get your fix and give it a try myself, though.

**Comment by orl0** [comment]
@hifi I'm not sure if my findings are useful anymore, since this bug is considered to be fixed on develop branch, but I'll leave it here just in case.

There is some interesting behavior in reproducing this bug:
- you should have **_only two_** layouts
- you should call Auto-Type from your **_second_** layout

If you change the first step from
> 1. `setxkbmap eu,fi -option grp:alt_shift_toggle`

to `setxkbmap us,eu,fi -option grp:alt_shift_toggle` (for example)
you will not have this bug.

**Comment by hifi** [comment]
@orl0 Are these findings with the current develop version or the previous stable? If they are with develop it's relevant but if with a release then the code has changed so much nothing tested with it is useful anymore.

If you can reproduce any issues with a current snapshot please file a new bug. 

Thanks!

**Comment by hifi** [comment]
@stefan123t You mean just Caps Lock on or a special kind of caps? With just Caps Lock on it should fail and complain.

**Comment by stefan123t** [comment]
@hifi, still didn't build your PR, shame on me.

Regarding the reproduction path, I do not have 1/2 symbol in any of my username/passwords combos frequently used.
Only thing I could imagine is the @ symbol which is on AltGr + Q on the german keyboard layout.
Hence when I am using Auto-Type with the german keyboard layout (being my second) your code may find the @ symbol on the Mod2 (AltGr) keymap.
Is that enought to trigger the problem with the Modifier for NumLock being in an odd state ?

Also regarding the proposed fix, does it simply not allow using Auto-Type while I have NumLock on ?
Actually I have setup my system with NumLock on by default, hence I would need to turn NumLock off to use Auto-Type, isn't it ?

**Comment by hifi** [comment]
The fix has already been merged and it doesn't affect Num Lock. You can just use a recent snapshot AppImage from [here ](https://snapshot.keepassxc.org/) to test
