### ISSUE TITLE
src/gui/styles/base/BaseStyle.cpp uses QOperatingSystemVersion from qt5.9, but Qt version checks only for 5.2.0

### ISSUE THREAD

**Issue by nieder** [keepassxreboot/keepassxc#6352]
## Overview
src/gui/styles/base/BaseStyle.cpp uses QOperatingSystemVersion, but CMakeLists.txt only asks for Qt5 >= 5.2.0
https://github.com/keepassxreboot/keepassxc/blob/b9ea6fd2e717ffe558c37f4a446e8a90dd9fafb4/src/gui/styles/base/BaseStyle.cpp#L55-L57
...
https://github.com/keepassxreboot/keepassxc/blob/b9ea6fd2e717ffe558c37f4a446e8a90dd9fafb4/src/gui/styles/base/BaseStyle.cpp#L296

QOperatingSystemVersion was introduced in 5.9
https://doc.qt.io/qt-5/qoperatingsystemversion.html

## Steps to Reproduce
Build keepassxc-2.6.4 with Qt5.7 present

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

## Actual Behavior
```
cd /src/keepassxc-2.6.4/finkbuild/src && /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -DKEEPASSX_BUILDING_CORE -DQT_CONCURRENT_LIB -DQT_CORE_LIB -DQT_GUI_LIB -DQT_MACEXTRAS_LIB -DQT_NETWORK_LIB -DQT_NO_CAST_TO_ASCII -DQT_NO_DEBUG -DQT_NO_DEPRECATED_WARNINGS -DQT_NO_EXCEPTIONS -DQT_STRICT_ITERATORS -DQT_SVG_LIB -DQT_WIDGETS_LIB -DWITH_APP_BUNDLE -I/src/keepassxc-2.6.4/finkbuild/src/keepassx_core_autogen/include -I/src/keepassxc-2.6.4/src -I/src/keepassxc-2.6.4/finkbuild/src -I/src/keepassxc-2.6.4/src/zxcvbn -isystem /sw/include -iframework /sw/lib/qt5-mac/lib -isystem /sw/lib/qt5-mac/lib/QtCore.framework/Headers -isystem /sw/lib/qt5-mac/share/qt5/mkspecs/macx-g++ -isystem /sw/lib/qt5-mac/lib/QtWidgets.framework/Headers -isystem /sw/lib/qt5-mac/lib/QtGui.framework/Headers -isystem /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/OpenGL.framework/Headers -isystem /sw/lib/qt5-mac/lib/QtSvg.framework/Headers -isystem /sw/lib/qt5-mac/lib/QtConcurrent.framework/Headers -isystem /sw/lib/qt5-mac/lib/QtNetwork.framework/Headers -isystem /sw/lib/qt5-mac/lib/QtMacExtras.framework/Headers -fno-common -Wall -Wextra -Wundef -Wpointer-arith -Wno-long-long -Wformat=2 -Wmissing-format-attribute -fvisibility=hidden -fvisibility-inlines-hidden -fstack-protector-strong -fno-exceptions -fno-rtti -Wnon-virtual-dtor -Wold-style-cast -Woverloaded-virtual -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -Werror=format-security -Wcast-align -std=c++11 -fsized-deallocation -stdlib=libc++ -Wno-deprecated-declarations -O3 -DNDEBUG -fPIC -std=gnu++11 -o CMakeFiles/keepassx_core.dir/gui/styles/base/BaseStyle.cpp.o -c /src/keepassxc-2.6.4/src/gui/styles/base/BaseStyle.cpp
/src/keepassxc-2.6.4/src/gui/styles/base/BaseStyle.cpp:56:10: fatal error: 'QOperatingSystemVersion' file not found
#include <QOperatingSystemVersion>
         ^~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

## Context
I'm using Qt5.7.
It would be great if the usage of QOperatingSystemVersion could be made conditional on the Qt5 version being used, but if not, the compile time check for Qt5 should check for 5.9 or greater.

Also, according to https://doc.qt.io/qt-5/qoperatingsystemversion.html#MacOSBigSur-var, `QOperatingSystemVersion::MacOSBigSur` (how QOperatingSystemVersion is actually being used) wasn't introduced until Qt 6.0 and is only present in Qt5.15.1, Qt5.12.10, but not Qt5.9.9 (the current available non-commercial downloads).

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.6.4 being built from source

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS 10.13.6

**Comment by droidmonkey** [comment]
We don't support such an old version of Qt5 on macOS, you'll have to patch this out yourself.

**Comment by nieder** [comment]
Fair enough on not supporting Qt5.7, but the Qt5 version check is broken then.

**Comment by droidmonkey** [comment]
That version check is only for Linux OS. Every other platform we assume latest available Qt.

**Comment by ryandesign** [comment]
> We don't support such an old version of Qt5 on macOS

> That version check is only for Linux OS. Every other platform we assume latest available Qt.

This is a nonsensical response. It is reasonable for a user to expect dependency version checks on any OS.

Qt 5.7 *is* the latest available Qt on some older versions of macOS. Please specify in your CMakeLists.txt and in documentation what the earliest supported version of Qt is.

As one datapoint, I was able to build KeePassXC 2.7.7 on OS X 10.9 (using Qt 5.8) and later but not on Mac OS X 10.8 (using Qt 5.7) or earlier.

**Comment by droidmonkey** [comment]
Feel free to comment out the offending code and build to your hearts content. This project general moves _forward_ and actively abandons unsupported, buggy, and/or otherwise outdated dependencies and operating systems. Noted that we need to document the minimum qt version.
