### ISSUE TITLE
Systemwide Hotkey for showing keepass window

### ISSUE THREAD

**Issue by Zailux** [keepassxreboot/keepassxc#6354]
## Summary
System-wide hotkey for showing the keepass window.

Refer to Keepass (standard) --> systemwide hotkeys: show keepass window. 

## Context
Well I just wanted to switch from keepass to keepassxc and i thought that overall you guys did great job. But this simple feature was kind of missing for me. Because I often want to open keepass just for looking into some PW. And having to click to open the application is kinda annoying, when I am used to the "luxury" of opening it via shortcut.

**Comment by droidmonkey** [comment]
Already requested and in the works
