### ISSUE TITLE
Show the timestamp of only the database when it was created

### ISSUE THREAD

**Issue by ghost** [keepassxreboot/keepassxc#6356]
## Summary
Hello, is it possible for keepass database file to display when the database was created?

If this function does not exist, can it be added as an optional function? I would like to know when I created the database.

Under database statistics I have not found any info.

## Examples
An idea is under database statistics, add this:

Datebase created: 03/27/2021 11:00:25 PM

how can the user activate it
1. first open KeePassXC
2. activate the option save database creation time
3. create a new database

it should also be possible to change the database timestamp, for example if it is wrong.

## Context
Originally I know this function from an app on the smartphone that saves the created time in the file name. but I do not like this solution and would rather in a clear method and can also quickly change it.

**Comment by pcolby** [comment]
Hi @ghost, the _Last saved_ stat comes from the filesystem's modification timestamp, so strictly speaking, the database wasn't necessarily "saved" by KeePassXC (it could have been moved, touched, copied, etc).

In the same way, it would be very easy to add the filesystem's creation timestamp, which similarly, would not strictly state when KeePassXC "created" the database, but rather when the database file arrived on the filesystem (eg it could have been copied from somewhere else, and would reflect the copy time).  If this is good enough, then I can throw together a quick PR sometime in the next few days :)

> it should also be possible to change the database timestamp, for example if it is wrong.

That would not be possible via KeePassXC itself (assuming the filesystem timestamps approach above). You would need to use some other utility to change the creation timestamp on the filesystem itself, which would be OS and FS type dependant, and not always possible.

Cheers.

**Comment by droidmonkey** [comment]
The date time of when the database was created is the created time of the root group. The file time should not play into this at all.

**Comment by pcolby** [comment]
Thanks @droidmonkey, I'm not familiar with the internal db structure yet, was just looking at how the existing _Last saved_ stat is fetched. Your suggestion sounds much more useful. Cheers.
