### ISSUE TITLE
Auto-Type types wrong password on different keyboard layouts

### ISSUE THREAD

**Issue by 7ritn** [keepassxreboot/keepassxc#6358]
## Overview
Auto Type types the wrong password, when using a different keybard layout

## Steps to Reproduce
1. Use a different keyboard layout than US
2. Create a password containing characters which differ between the US and the other keyboard layout
3. Use auto type

## Expected Behavior
I expect the auto type to type the correct password

## Actual Behavior
When the US keyboard layout is active the password and username are typed corrected. However when a different keyboard layout (like DE) is active a wrong password is typed

## Context
It seems like Keypassxc seems to always type in US layout even when a different layout is active, this results in a wrong auto type. For example the DE Version has as 2-Shift Character the ", however the US layout has the @ at this position. So autotype will type an " when I have a @ in my password, if I'm on the DE layout. Everything works fine when I'm on the US layout.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.4
Revision: 34a78f0

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: KDE
Windowing System: X11

**Comment by hifi** [comment]
This has been fixed in develop and will be fixed in 2.7.0. You can try a snapshot build from https://snapshot.keepassxc.org/latest/

Thanks.
