### ISSUE TITLE
Consider officially supporting Flatpak

### ISSUE THREAD

**Issue by ssokolow** [keepassxreboot/keepassxc#6359]
As someone who can't stand various architectural details and performance characteristics of the snappy packaging system, and who is considering migrating from Kubuntu to Mint or Debian as it becomes more difficult to rip out snap components from a \*buntu install, I'd like to request that you officially support Flatpak for the following reasons:

1. For something as important as a password manager, I'm only going to run either an official release or a distro release, which currently leaves my choices at APT, Appimage, or the snap.
2. As I said before, snappy is unacceptable, which limits me to APT or Appimage.
3. I'd prefer automatic security updates through an existing centralized updates system, which rules out Appimage, leaving only the distro repos or the PPA.
4. I'd like a system with an Android-esque manifest-based sandboxing system, which rules out the distro repos and PPA, leaving an empty set.

My ideal situation would be running a trusted Flatpak release and using Flatseal to lock down the permissions further. (eg. Disabling network access to make it more difficult for a compromized build to exfiltrate credentials and then going back to my Mono+Keepass habit of manually downloading favicons with the browser and opening them with a file picker, since creating new accounts is infrequent enough to not merit the reduced defense in depth.)

As-is, all I can really do is attempt to approximate what Flatpak's sandboxing does by running the distro or PPA release inside Firejail.

**Comment by hifi** [comment]
We have discussed about endorsing Flatpak as it also solves some integration issues we've had with Snaps but we don't have a decision on this yet. I fully support moving from Snaps to Flatpak.

**Comment by droidmonkey** [comment]
This is a duplicate

**Comment by ssokolow** [comment]
@droidmonkey Ahh. Sorry. 

I'm currently struglling with sleep issues and, aside from the bunch of corrected words visible in the edit history, I guess "I'm about to try to get a few more hours" means I missed that while searching for existing issues.

**Comment by droidmonkey** [comment]
No problems, it's been on my long todo list for a while
