### ISSUE TITLE
Open database reloads if file is overwritten

### ISSUE THREAD

**Issue by yashton** [keepassxreboot/keepassxc#6360]
## Overview
If you have a database open, and you overwrite the underlying file, the application will reload the file unlocked with the updated contents without prompting. If you overwrite with a database file that does not match the password, the current file is rewritten to disk.
I do not know if this is a potential security issue, but the behavior surprised me.

## Steps to Reproduce
1. Open a database file secured by password.
2. Overwrite the database file with another file with the same password. I first encountered this with a newer version of the database file I had loaded, but experimenting shows that it will load a completely different new file.

## Expected Behavior
I expect the open file to be invalidated, a message shown saying the file has changed on disk, and a prompt to open the new file  with password prompt, regardless of if the current file shares a password.

## Actual Behavior
The application reloads the file if the new file has the same password, staying open with the entries updating.

If the password on the new file does not match, the application shows the standard error for incorrect password, 
> Could not open the new database file while attempting to autoreload.
> Error: Error while reading the database: Invalid credentials were provided, please try again.
> If this reoccurs, then your database file may be corrupt. (HMAC mismatch)

The file on disk is then overwritten with the currently loaded data.

## Context
KeePassXC - Version 2.6.2
Revision: e9b9582

Qt 5.15.2
Debugging mode is disabled.

Operating system: Debian GNU/Linux bullseye/sid
CPU architecture: x86_64
Kernel: linux 5.10.0-4-amd64

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (only unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.8

**Comment by droidmonkey** [comment]
This behavior is by design, but is also configurable in the application settings. There is already an issue about the password change issue.
