### ISSUE TITLE
Open entry from url in current database

### ISSUE THREAD

**Issue by mvenghaus** [keepassxreboot/keepassxc#6362]
## Summary
We've have an online wiki but don't want sensitive data in it. So it would be nice if we can trigger to show or search entry via Url (maybe via xgd-open).

## Examples
keepassxc --show-entry /path/to/entry
keepassxc --locate-entry /path/to/entry

When it only triggers gui actions it should not be relevant to security issues.

## Context
If you can just click to open the entries it would save some time when you have a shared project database. It comes in handy when you have access data where you are not able to use autofill. (Api Keys, etc..)

**Comment by droidmonkey** [comment]
#5369 is relevant and probably a better option
