### ISSUE TITLE
Keepassxc 2.6.4 crashes on 2011 MacBook Pro running Catalina

### ISSUE THREAD

**Issue by davidekelly** [keepassxreboot/keepassxc#6366]
Hi,
I'm running macOS Catalina (10.15.7) on a 17" MacBook Pro (MBP) with quad-core i7 CPU and 16GB RAM. The MBP has it's discrete AMD GPU disabled (cut track on logic board) in order to run Catalina via the custom Catalina patcher from "dosdude1" (http://dosdude1.com/catalina/). Hence this is a non-standard, non-Apple-supported configuration. However, the vast majority of software runs happily (e.g. including Microsoft Office 2019, but not Apple's latest GarageBand, etc, that require Metal support).

To reproduce the problem, all that is required is to install and run Keepassxc 2.6.4. (I also tried installing Keepassxc 2.6.4 via the "brew" package manager on macOS, but Keepassxc still crashed in the identical manner.)

Ideally, Keepassxc 2.6.4 should run normally on my non-standard configuration.

Instead, it crashes, with the following dump information to be send to Apple:

Process:               KeePassXC [1178]
Path:                  /Applications/KeePassXC.app/Contents/MacOS/KeePassXC
Identifier:            org.keepassxc.keepassxc
Version:               ???
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           KeePassXC [1178]
User ID:               502

Date/Time:             2021-04-05 13:07:58.471 +1000
OS Version:            Mac OS X 10.15.7 (19H2)
Report Version:        12
Anonymous UUID:        DC38A8AF-7CA5-DF40-1ED9-E7C35D90E9B9

Sleep/Wake UUID:       C8694AA6-9A3E-4150-8A83-9250884B5805

Time Awake Since Boot: 2300 seconds
Time Since Wake:       210 seconds

System Integrity Protection: disabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (Code Signature Invalid)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace CODESIGNING, Code 0x1

kernel messages:

VM Regions Near 0 (cr2):
--> 
    __TEXT                 000000010194e000-0000000101d46000 [ 4064K] r-x/r-x SM=COW  

Thread 0 Crashed:
0                                	0x000000010419b000 _dyld_start + 0

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0x0000000000000000  rcx: 0x0000000000000000  rdx: 0x0000000000000000
  rdi: 0x0000000000000000  rsi: 0x0000000000000000  rbp: 0x0000000000000000  rsp: 0x00007ffeee2b1c08
   r8: 0x0000000000000000   r9: 0x0000000000000000  r10: 0x0000000000000000  r11: 0x0000000000000000
  r12: 0x0000000000000000  r13: 0x0000000000000000  r14: 0x0000000000000000  r15: 0x0000000000000000
  rip: 0x000000010419b000  rfl: 0x0000000000000200  cr2: 0x0000000000000000
  
Logical CPU:     0
Error Code:      0x00000000
Trap Number:     0

Binary Images:
       0x10194e000 -        0x101d45fff + (0) <AB3C08BF-C2B8-3D1F-B662-D0B34E893F60> 
       0x10419a000 -        0x10422bf47 + (750.6) <1D318D60-C9B0-3511-BE9C-82AFD2EF930D> 

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 1101
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=5220K resident=0K(0%) swapped_out_or_unallocated=5220K(100%)
Writable regions: Total=8404K written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=8404K(100%)
 
                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
STACK GUARD                       56.0M        1 
Stack                             8192K        1 
__DATA                             392K        3 
__DATA_CONST                        20K        1 
__LINKEDIT                         576K        3 
__TEXT                            4648K        2 
shared memory                        8K        2 
===========                     =======  ======= 
TOTAL                             69.5M       13 

Model: MacBookPro8,3, BootROM 87.0.0.0.0, 4 processors, Quad-Core Intel Core i7, 2.4 GHz, 16 GB, SMC 1.70f6
Graphics: kHW_IntelHD3000Item, Intel HD Graphics 3000, spdisplays_builtin
Memory Module: BANK 0/DIMM0, 8 GB, DDR3, 1333 MHz, 0x029E, 0x434D5341384758334D314131333333433920
Memory Module: BANK 1/DIMM0, 8 GB, DDR3, 1333 MHz, 0x029E, 0x434D5341384758334D314131333333433920
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0xD6), Broadcom BCM43xx 1.0 (5.106.98.102.31)
Bluetooth: Version 7.0.6f7, 3 services, 27 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en1
Serial ATA Device: SAMSUNG SSD 830 Series, 512.11 GB
Serial ATA Device: MATSHITADVD-R   UJ-8A8
USB Device: USB 2.0 Bus
USB Device: Hub
USB Device: IR Receiver
USB Device: USB 2.0 Bus
USB Device: FaceTime HD Camera (Built-in)
USB Device: Hub
USB Device: Apple Internal Keyboard / Trackpad
USB Device: BRCM2070 Hub

I know my MBP config is not supported by Apple, but it would be greatly appreciated if it could be supported by Keepassxc.

Thank you.

**Comment by droidmonkey** [comment]
Termination Reason: Namespace CODESIGNING, Code 0x1

You'll have to figure this one out on your own, this is not our error

**Comment by raoulbhatia** [comment]
@davidekelly @droidmonkey I ran into the same issue.

I was able to resolve it by installing the latest 2.7.0 snapshot build from https://snapshot.keepassxc.org/

Raoul

**Comment by droidmonkey** [comment]
That one is not signed

**Comment by yaomtc** [comment]
I'm in the same boat here, running unofficial MacOS Catalina on a late 2011 Macbook Pro. The stable, signed build of KeePassXC does not work for me, while the snapshot build does. I wonder why.

Is 2.7.1-snapshot basically the same as 2.7.1, with the same risk of corruption, or lack thereof?

**Comment by phoerious** [comment]
The snapshots are tested less and may contain bugs.
