### ISSUE TITLE
The {PICKCHARS} placeholder doesn't work in Gnome on Ubuntu 20.04.

### ISSUE THREAD

**Issue by enroto** [keepassxreboot/keepassxc#6368]
## Overview

[NOTE]: The {PICKCHARS} placeholder doesn't work in Gnome, X11,on Ubuntu 20.04.

## Steps to Reproduce
[NOTE]: 
1. Configure an entry with Auto-Type placeholder {PICKCHARS}
2. Select the entry and use keyboard shortcut Shift+Ctrl+V
3. No pick chars window appears

## Expected Behavior
[NOTE]: Expected to see a pick chars window.

## Actual Behavior
[NOTE]: No pick chars window appears

## Context
[NOTE]: N/A

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.4
Revision: 34a78f0

Qt 5.12.8
Debugging mode is disabled.

Operating system: Ubuntu 20.04.2 LTS
CPU architecture: x86_64
Kernel: linux 5.4.0-70-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- libgcrypt 1.8.5

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux Ubuntu 20.04
Desktop Env: Gnome
Windowing System: X11

**Comment by droidmonkey** [comment]
It is going to be part of 2.7.0 release.

**Comment by enroto** [comment]
Understood! Thank you for the great work you are all doing.
