### ISSUE TITLE
Always show Auto-Type sequence

### ISSUE THREAD

**Issue by VibrantTreeStump** [keepassxreboot/keepassxc#6369]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )

I want to suggest an option to always show the Auto-Type sequence for all entries in the Auto-Type window.
Currently they are only shown if you have 2 or more accounts for the site you're visiting and you have set up different sequences for the entries.

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )

![Auto-Type](https://user-images.githubusercontent.com/82000085/113636829-9202e200-9673-11eb-801c-c45e6ec4f267.PNG)

When pressing Ctrl+Alt+A (or whatever other shortcut you have set up for global Auto-Type) the window shown above opens up and shows the relevant entries to the site you're visiting, giving you only the following information: 

- Group
- Title
- Username
- (Sequence): Currently only shown if you have 2 or more accounts for the site you're visiting and you have set up different sequences for the entries

To make sure that you're remembering the sequence you set up for the entry you're about to use correctly, you currently have to open the main window again and look it up here

![Auto-Type2](https://user-images.githubusercontent.com/82000085/113636880-a6df7580-9673-11eb-81c0-a64920c0cc6a.PNG)

otherwise you run the risk of accidentally typing the password into the "Username" field.

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )

Suppose I am sure that I didn't set up a custom Auto-Type sequence for the entry I'm about to use - in my mind, the sequence therefore is {USERNAME}{TAB}{PASSWORD}{ENTER}.
I now press Ctrl+Alt+A with the cursor inside the "Username" field and select the entry without checking inside the main window again. In reality I have set up the custom sequence {PASSWORD}{ENTER} for the entry, so now KeepassXC is typing my password into the Username field - that's bad.

This risk would be prevented in a very convenient way if the sequence was always shown in the Auto-Type window.

It should (always) look like this:

![Auto-Type3](https://user-images.githubusercontent.com/82000085/113637363-b612f300-9674-11eb-8af0-7a936bc00e28.PNG)

**Comment by droidmonkey** [comment]
Already fixed for 2.7.0

**Comment by VibrantTreeStump** [comment]
Oh, okay. Sorry then. Do you already know when 2.7.0 is going to be released?

**Comment by VibrantTreeStump** [comment]
> 
> 
> Already fixed for 2.7.0

Oh, okay. Sorry then. Do you already know when 2.7.0 is going to be released?

**Comment by droidmonkey** [comment]
When is ready
