### ISSUE TITLE
Bidirectional Merge/Synchronization

### ISSUE THREAD

**Issue by Talkarcabbage** [keepassxreboot/keepassxc#637]
## Expected Behavior
Bidirectional merge/synchronization

Does the current implementation support *bidirectional* merges/synchronization? If for instance, you store a local copy and a Dropbox copy separately (both available locally, though) and open the local copy and add a new entry, is there a way to merge the local copy's new entry into the Dropbox file (as well as pulling in any changes that are present in the Dropbox file but not yet the local copy, in either one or two steps)? I didn't see it anywhere in the menus and merge only seemed to affect the open database rather than both.

Asking due to the situation noted here http://keepass.info/help/kb/trigger_examples.html in the "Synchronizing with Dropbox..." section (sorry I can't link to that section specifically). At some point I had an issue with Dropbox overwriting with an older copy and dropping some of the changes (and adding a conflict file).

I saw a few issues that were related, but none seemed to address this directly. Apologies if this is a duplicate.

Final question, though it might belong in its own issue, is it possible for merges to assume both databases use the same password&/key and to only ask if the password&/key don't match?

**Comment by droidmonkey** [comment]
This feature does not exist, yet. It is a bit of an edge case though. Why not just use the copy directly from Dropbox?

**Comment by Talkarcabbage** [comment]
I probably should have included a tl;dr in the post.
Direct Dropbox files can cause data loss. Had it happen personally (and saw it described on keepass.info above) which is why I started using sync on keepass.

**Comment by tohn** [comment]
Thanks @Talkarcabbage, this is what I meant with my comment [here](https://github.com/keepassxreboot/keepassxc/issues/90#issuecomment-309028224). 👍

**Comment by nilbus** [comment]
> At some point I had an issue with Dropbox overwriting with an older copy and dropping some of the changes (and adding a conflict file).

To resolve this, could you open one of the copies, merge the other, and then save onto the dropbox copy?

> I didn't see it anywhere in the menus and merge only seemed to affect the open database rather than both.

Could you just replace the dropbox copy with the local copy after merging and saving?

**Comment by Talkarcabbage** [comment]
I _believe_ that would have an equivalent effect, assuming the local copy ends up fully "up to date" first.

**Comment by jeroen7s** [comment]
seems like what you're trying to do is explained in: #90 
also on your original post, you can link to the section on keepass' website by adding #dbsync to the end of the url

**Comment by louib** [comment]
@Talkarcabbage 

> Final question, though it might belong in its own issue, is it possible for merges to assume both databases use the same password&/key and to only ask if the password&/key don't match?

If you use the CLI, you can use the `-s` or `--same-credentials` option to use the same password/keyfile for both database files. I'm not sure you can achieve the same thing from the GUI though.

```
keepassxc-cli merge db1.kdbx db2.kdbx --same-credentials
```

**Comment by droidmonkey** [comment]
Covered by #90, closing.
