### ISSUE TITLE
Inner header corrupt??

### ISSUE THREAD

**Issue by crogonint** [keepassxreboot/keepassxc#6375]
## Overview
This is strictly for whomever is troubleshooting people having issues with corrupt databases. 

"Error while reading the database: Invalid inner header id size"

This happened to me. I was clued in to the cause when I tried to copy the database to the actual hard drive. I got some silly error about how it couldn't copy it. I closed the secure connection, and reopened it, and the database opened as normal. Nothing was actually corrupt at all.

I DID take it as a wake up call, and went ahead and synced the database to cloud storage.

There MAY have a completely different issue which can cause this error, but I hope this helps. :)

**Comment by droidmonkey** [comment]
Thank you, nothing to do here though
