### ISSUE TITLE
ICON SIZE IS MASSIVE

### ISSUE THREAD

**Issue by webdawg** [keepassxreboot/keepassxc#6376]
## Overview
The icons are so big, the software is unusable:
XFCE

![image](https://user-images.githubusercontent.com/1071152/113897402-d2a84b80-9798-11eb-9ac5-e3d6d871c690.png)

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Open database
2. 
3. 

## Expected Behavior
[NOTE]:  Can I just adjust icon sizes myself?

## Actual Behavior
[NOTE]: I saw you adjusted icon stuff, but this is just crazy at this point.  I have thousands, and thousands of passwords, and now I can fix like 10 on a 1600x1200 screen.

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.6.4
Revision: Archlinux upgraded this morning

[NOTE]: # ( Pick choices based on your environment )
Operating System: Archlinux
Desktop Env: XFCE
Windowing System: X11

**Comment by droidmonkey** [comment]
Pinned issue
