### ISSUE TITLE
Update SSH Agent documentation for PuttyGen key creation 

### ISSUE THREAD

**Issue by Colbix** [keepassxreboot/keepassxc#6378]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
May I request your document webpage be updated to reflect the Puttygen method of generating keys is not supported? I reviewed the comments from prior issues opened, see below. Having your webpage updated would help other users looking for a solution and prevent users from struggling to follow the webpage instructions. Thank you for your attention.

Reference:
https://keepassxc.org/docs/KeePassXC_UserGuide.html#_generating_a_key_to_use_with_keepassxc

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
Pertaining to #5884 and #1783.

**Comment by droidmonkey** [comment]
It's literally in the first paragraph:

KeePassXC only supports keys in the OpenSSH format. On Windows, PuTTYgen saves keys in its own format by default and you will need to convert them to OpenSSH format before being used.

**Comment by Colbix** [comment]
@droidmonkey I understand that however the instructions to export from Puttygen do not indicate the only way to import the key is to not have a password set. Step 2 reads "Set the password you used for the key file in the password field.", and if you do that KeypassXC will generate the error.

**Comment by droidmonkey** [comment]
You are absolutely correct, the documentation should say to choose the "Export OpenSSH Key (Force new file format)"
