### ISSUE TITLE
User is swaped with another entry when using browser integration

### ISSUE THREAD

**Issue by shanks1337** [keepassxreboot/keepassxc#6380]
## Overview
Browser integration swaps user with another entry. 

When the website instagram.com is opend and I click on the browser itegration icon to select which entry I want to use from the drop down menu, the browser integration doesn't enter the corrent user (E-Mail-Adress in this case). 

## Steps to Reproduce
1. KeePassXC database is unlocked
2. open with firefox https://www.instagram.com/ (note: no cookies, not logged in)
3. click on the browser icon of "KeePassXC-Browser" add-on 
4.  select the the name of the entry #1 out of two possible entrys in the drop down list
5.  user and password appear in the login felds
6.  I press on 'reveal (password)' on the instagram website

## Expected Behavior
user is from entry #1 and password is from entry #1  
USER1 / PASSWORD1

## Actual Behavior
user is from entry #2 and password is from entry #1
USER2 / PASSWORD1

## Context
If I select the name of entry #2 from the drop down list I have the same result: user is from entry #1 and password is from entry #2.
USER1 / PASSWORD2

I have only two entry in the database for this website (instagram.com)

This odd behaviour I've only observed for this website (instagram.com). For now it's 100% reproducible with my current set up and I have not attempted to 'fix' it in any way so I won't 'break' the bug and it stays reproducible. 

KeePassXC - Version 2.6.4
Revision: 34a78f0

Operating System: Windows 8.1 Pro N
Firefox: 87.0 (64-Bit)
Add-on "KeePassXC-Browser": 1.7.7

**Comment by droidmonkey** [comment]
Recommend deleting the second entry and recreate a fresh one.

**Comment by varjolintu** [comment]
This should be already fixed with https://github.com/keepassxreboot/keepassxc-browser/pull/1296.
