### ISSUE TITLE
integration of "have I been pawned" 

### ISSUE THREAD

**Issue by rezad1393** [keepassxreboot/keepassxc#6383]
## Summary
integrate "have I been pawned" website(service?) to check for hacked emails accounts used on websites.

this makes it very easy to find accounts that have been hacked and then user can decide what to do with it.

**Comment by droidmonkey** [comment]
This isna duplicate and HIBP has been integrated to check your passwords. The email service is not free.

**Comment by rezad1393** [comment]
where is the integration?
I cant find it.

**Comment by phoerious** [comment]
Go to Database->Database Reports.
