### ISSUE TITLE
Modifying/saving database causes KeePassXC to soft lock

### ISSUE THREAD

**Issue by klosteinmann** [keepassxreboot/keepassxc#6387]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # (  )
Upon saving and or modifying the database laying on a nextcloud instace in my case eCloud. The program locks itself down preventing me from any change until the previous is applied  I can still access the help menu and other parts of the program.

## Steps to Reproduce
[NOTE]: # (  )
0. Run KeePassXC
1. Open your Keydatabase mounted via Ubuntus Service for Nextcloud integration
2. Save or modify the keys so that KeePass had to process that action.
3.  ?
4.  Profit. I mean bug whatever it's timeout to the server who knows what happens here.

## Expected Behavior
[NOTE]: # (  )
Program should process the action and let me continue working on the database.

## Actual Behavior
[NOTE]: # (  )
I am stuck in a locked state waiting for the program to process the action.

## Context
[NOTE]: # (  )
Might be due my setup as me KeePassXC 2.7.0 via Snap Package more noticeable on 2.6.4
Don't have any newbie user don't know where logs are stored yet.

**Gonna update** for further information. Such as when used offline do these changes apply so I could at least tell you if it is an issue with the program or the service/server I use to store my key file.

**When did this problem starting occurring?** A week ago or so  I switched from Windows to Linux. At first I just used the normal software center (refering to it now on as sc*) to install KeePassXC first I accidentality installed the community version which was a bit behind I uninstalled it via sc* and wanted to instead install KeePassXC via PPA I had troubles installing the program that way. So I went for the sc* again using this time the newer official package 2.6.4. Under the old community version I did not have the issue.

Force quitting the program via super+shift+q is I guess prevented in order to save the database from corruption.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.0
Revision: 86ddd70
Distribution: Snap

Qt 5.9.5
Diagnosemodus ist deaktiviert.

Activated extensions:
- Auto-Type
- Browser-Integration
- SSH-Agent
- KeeShare (bestätigtes und unbestätigtes Teilen)
- YubiKey
- Secret-Service-Integration

Cryptographic Libarys:
- libgcrypt 1.8.1

[NOTE]: # ( Pick choices based on your environment )
Operating system: Ubuntu Core 18
CPU-Architecture: x86_64
Kernel: linux 5.8.0-48-generic
Window system: I'm guessing it Ubuntu 20.04 LTS runs still on Xorg.

**Comment by droidmonkey** [comment]
You have too much going on here. Use the last stable version of keepassxc. Make sure your encryption settings are not set too high causing long save times. Make sure you aren't storing huge files in your attachments.
