### ISSUE TITLE
macos blocks pasteing password till the clipboard is clear

### ISSUE THREAD

**Issue by clexp** [keepassxreboot/keepassxc#6388]
## Main function of keepassxc obstructed by 'security' switch?
Open KeepassXC.  Will copy to clipboard but blocks pasteing to login entries, with the 'waiting' daisy wheel, for 10 seconds till clipboard clear times out, then waiting daisy wheel disappears and can paste, but pastes nothing, as you would expect from an empty clipboard.  

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. macOS big sur
2. latest keepassXC
3. password file on usb stick
4. keepass open and file accessible and read in.  
5. website open at login page
6. copy password to clipboard
7. got to webpage password box, click in box
8. press paste
9. waiting daisy wheel appears until 10s after copied to clipboard
10. daisy wheel disappears, and can now paste an empty clipboard

## Expected Behavior
6. copy password to clipboard
7. got to webpage password box, click in box
8. press paste
9. pastes in password
10. clipboard cleared at 10s

## Actual Behavior
see Steps to Reproduce

## Context
* New macbook pro M1
* installed latest keepassXC as binary bundle (not installed homebrew succcessfully yet)
* usb stick formated to exfat for linux/apple compatibility.  

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.5.4
Revision: b93fbd1
Qt 5.12.2
Debuging mode disabled
macos 11.0
cpu arm64
kernal darwin 20.1.0
extensions
-sutotype
-browser integrtion
-SSH agent
-keeshare (onlyunsigned sharing)
-yubikey
-touchID
cryyptographic libraries
-libgcrypt 1.9.1

[NOTE]: # ( Pick choices based on your environment )
Operating System: Macos

Solving my own problem:
I think macos now is using the metadate differently, it is assuming that the "password" flag means passwords must not be sent from one program to another.  I feel like there may be a settind in MacOS to make a program specific setting.  I am new to Mac as of 2 weeks ago after 20 year of dual booting win/linux.

**Comment by droidmonkey** [comment]
Update to 2.6.4. Recommend also using Auto-Type or the browser extension instead of clipboard.

**Comment by clexp** [comment]
Hi, Thanks for such a quick response, sorry I did not share enough detail.  This is specific to safari, in Brave browser on the macbook it is fine.  It also also ok in firefox.  I can't see a browser extension listed in the safari extension page for keepassXC.  Not sure what you mean by autotype, have you got a favourite link I can go to? The 'About' page for KeepassXC says autotype is bing used...?

**Comment by clexp** [comment]
Sorry about the bug label.

**Comment by droidmonkey** [comment]
Take a look at our documentation: https://keepassxc.org/docs/KeePassXC_UserGuide.html#_auto_type

I'll see if I can reproduce the issue in safari.

**Comment by droidmonkey** [comment]
I cannot replicate this behavior on Safari 14.03 running macOS 11.2.3

**Comment by clexp** [comment]
Thanks for giving it some time and attention.  Thanks for the link about auto type.  

Auto type seems like a good option.  In some instances it drafted in the usernames and details fully, in other instances it reported "no record known", where there was one,  in that case it reported looking for a generic "username' field rather than a specific website user detail record. 

Autotype also went to a permissions dialogue box asking for permission for KeePassXC to make changes to the computer.  But it did this every time I tried a new record.  

Then shortly after this the problem resolved.  I can't replicate it now either.  
===
I think this happened before.  It just went away and came back on a reboot. 
I am really thankful for your time on this, and as I learn a bit more Mac and better/(less bad) error reporting I will post again.  I really like KeepassXC used it a long time on all platforms now, demand all my family use it and made a donation.

**Comment by droidmonkey** [comment]
The permissions boxes are normal and they randomly reset after a system upgrade. Usually a reboot solves issues. I'm gonna close this for now, feel free to reply or open a new issue if you find something else.
