### ISSUE TITLE
In auto-type pop-up dialogue: show the Auto-type sequence that will be used

### ISSUE THREAD

**Issue by Jasha10** [keepassxreboot/keepassxc#6389]
## Summary
I'd like to see, in the auto-type pop-up window (where you select which credentials will be used), a column displaying the auto-type sequence that will be used.

## Context
Often times websites update their login fields. For example, perhaps `{USERNAME}{TAB}{PASSWORD}{ENTER}` was necessary, but today you need two tabs instead of one (`{TAB}{TAB}`). Showing the auto-type sequence that will be used would make it much easier to confirm that your password or other sensitive information will not be entered in the wrong place!

**Comment by droidmonkey** [comment]
Already done for 2.7.0
