### ISSUE TITLE
Corrupted database after saving locked db

### ISSUE THREAD

**Issue by SammysHP** [keepassxreboot/keepassxc#639]
## Expected Behavior
Locked database cannot be stored (because it is already locked)

## Current Behavior
KeePassXC asks to store a modified, locked database. If you select "yes", the database is corrupted afterwards.

## Steps to Reproduce (for bugs)
1. Open database from KeePassX2 for the first time
1. Lock database
1. KeePassXC asks to save changes (which changes?). Select "no"
1. Close KeePassXC, it asks again to save changes (to locked database)
1. Select "yes", the database is corrupted ("Invalid transform seed size")

## Your Environment
KeePassXC 2.1.4, Arch Linux

Configuration:
![20170613_194201](https://user-images.githubusercontent.com/922874/27096220-97fa2e9a-5070-11e7-9cde-f39cf1212b45.png)

**Comment by droidmonkey** [comment]
Yikes, if confirmed this is very bad. Is there a hard requirement to meet step 1 (db from keepassx2) or is it on all databases.

**Comment by SammysHP** [comment]
I'll try with a new database, give me some minutes.

**Comment by SammysHP** [comment]
OK, it is even worse. I was not able to reproduce "DB from keepassx2 was modified without actual changes", but I have a minimal example to reproduce the issue:

1. Open DB
1. Modify something
1. Lock DB, keepassxc asks to save DB
1. Select "Close without saving"
1. DB is now locked, title still contains the * which indicates that it is modified.
1. Close DB, again it asks to save
1. Select "yes", the database is now corrupted (hopefully because the password was not in the cache anymore)

**Comment by droidmonkey** [comment]
Through my testing I have found that this issue is not reproducible on the develop branch. Seeing that we are looking to release v2.2.0 very soon I will not issue a new third digit release just for this one.

**Comment by SammysHP** [comment]
Indeed, it is fixed in the develop branch.
