### ISSUE TITLE
Can't open a DB created with windows Keypass 2.47 using Linux Keypassxc 2.6.4

### ISSUE THREAD

**Issue by Julescs0** [keepassxreboot/keepassxc#6390]
Hi,

I have a database that I can open using keepass in windows but not with keypassxc on linux. The database uses a 40 character password and also a key file present on separate USB devices. I have checked the password and key but nothing is different. I can read the database and keyfile from the linux usb locations on command line so there is nothing wrong there. There is also a work factor added which normally takes about 3-5 minutes.

I have also viewed the password, compared visually and retested a number of times but still not working. Neither file is corrupt as keepass can open the database using the same files.

Error is - Error while reading database: Invalid credentials were provided, please try again. If this reoccurs, then your database file maybe corrupt.

Is there a version mismatch somehow?

Thanks,
Julian

**Comment by droidmonkey** [comment]
3 - 5 minutes to decrypt the database?

**Comment by droidmonkey** [comment]
I just tested databases between KeePass 2.47 and KeePassXC. It worked perfectly. The most likely problem is mistyped credentials.

**Comment by Julescs0** [comment]
Thanks for testing. Unfortunately, there is more to this issue somewhere. Firstly, I'm not that bad a tester as I work in software myself and wouldn't trouble you if I hadn't thoroughly ruled that out. Point being, I am not just a typical end user here (not taking it personally either as of course as just interested in the cause and solving it). As mentioned already above, the same credentials, key file and database have been checked also visually multiple times and the issue remains. I have even cut and past the exact password plus visual check (on top of multiple typing tests and visual checks). I get the same error every time. There is no way the credentials are different, so current conclusion is not correct. So something is not right somewhere and different between your test case and my situation. I installed keepassxs via zypper in OpenSUSE, so I'm wondering what else can be the cause.

**Comment by Julescs0** [comment]
@droidmonkey Can you reopen this and help me find the actual cause?

**Comment by Julescs0** [comment]
> 
> 
> 3 - 5 minutes to decrypt the database?

Yes, a work factor added (keepass options) specifically to make it near impossible to brute force attack.

**Comment by droidmonkey** [comment]
Is that from a plugin?

**Comment by Julescs0** [comment]
> 
> 
> Is that from a plugin? A delay of 1-5 _seconds_ makes it impossible to brute force, especially when using Argon2.

See "Protection against Dictionary Attacks" under https://keepass.info/help/base/security.html. This is a built in feature I believe. Nothing to do with plugins.

**Comment by droidmonkey** [comment]
Set it back to 1 second and see if your issue persists. You are well outside the normal operating mode of the application at 3-5 minutes.

**Comment by Julescs0** [comment]
Ok, I'll test that... Yes, I used extreme settings as this is an ultra secure db that contains highly sensitive data and access is expected to be 1-2 per year or on death (hope that doesn't come too soon)...

![image](https://user-images.githubusercontent.com/11554466/114391680-0f5cb400-9b98-11eb-9457-35f1f4b33597.png)

**Comment by Julescs0** [comment]
Yes, I can confirm that is the issue. Anyway to improve this, at minimum to give a sensible exception or to support a longer work factor?

**Comment by droidmonkey** [comment]
5 seconds if you must. There is no reason at all for longer.

**Comment by Julescs0** [comment]
> 
> 
> 5 seconds if you must. There is no reason at all for longer.

Ok, no problem. I'll stop using keepassxc. I understand your point though. Thanks.
