### ISSUE TITLE
keepass-2.47: Ticks must be between DateTime.MinValue.Ticks and DateTime.MaxValue.Ticks. Parameter name: ticks

### ISSUE THREAD

**Issue by mmokrejs** [keepassxreboot/keepassxc#6391]
Hi,
  I had a database created by keepass-2.42.1 with a separate keyfile, see https://sourceforge.net/p/keepass/bugs/1872/  . I thought I shall try keepassXC instead. KeepassXC kept complaining it is in an old format which maybe will not be supported in future. The conversion window was confusing. It does not make it clear one has to browse for the old (current keyfile, see 
![keepassxc_regenerate_keyfile](https://user-images.githubusercontent.com/3297852/114266014-3c706180-99f4-11eb-81b6-49961c438cf2.png)
) to be re-generated, the next window in the Browse file says "Select a keyfile" instead of "Select an existing keyfile", you select it, than one is suposed to click `Generate`, then to type in a new filename (the window should be named "Set a new filename for a keyfile"). In the end, I figured out and did these steps.

  Now, I cannot open the database in Keepass-2.43. Is this a new incompatibility introduced or just a new bug? What's the point making user migrate away from KeePass to KeePassXC?

![Keepass_2 47_cannot_open_new_keyfile_from_KeepassXC](https://user-images.githubusercontent.com/3297852/114265882-902e7b00-99f3-11eb-9b93-b68cf96562ac.png)

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.6.4
keepass-2.47

[NOTE]: # ( Pick choices based on your environment )
Operating System: Gentoo Linux
Desktop Env: XFCE
Windowing System: X11

**Comment by droidmonkey** [comment]
Keepass is on version 2.47 so you are many versions out of date. There is no bug here for KeePassXC.

**Comment by mmokrejs** [comment]
Sorry, I fixed one typo of the version number stated above although elsewhere it was correct. I do have latest KeepassXC and Keepass. The masterkey created by KeepassXC cannot be used by Keepass. Please re-read this once again.

**Comment by droidmonkey** [comment]
I just did the following:

1) Create database with KeePass 2.47, set password and create key file (version 1.0)
2) Open database in KeePassXC, receive legacy key file warning
3) In KeePassXC, went to Database Security and generated new key file, saved database
4) In KeePass 2.47, locked and opened database with password and new key file

Received no such error as described and everything worked without issue.

**Comment by mmokrejs** [comment]
Hmm, that's weird. Could it be an older format was created using keepass-2.42.1? BTW, I see the keyfile.key was in XML format and the key was under `KeyFile.Key.Data` tag. Those created by KeepassXC are just 128 bytes long blobs.

**Comment by mmokrejs** [comment]
Needless to say KeePass complains about the database kdbx file and not the keyfile itself, true. I inow I should probably talk to KeePass people but I felt you might know better what incompatibility could have arisen from the keyfile change (whatever you call `legacy`).

**Comment by droidmonkey** [comment]
There is no incompatibility with the key files that I found. The error message you see I think has nothing to do with key files. You should file a report with KeePass, but since you started with such an old version they may tell you it's not a problem anymore.
