### ISSUE TITLE
Allow moving entries between different databases

### ISSUE THREAD

**Issue by mmokrejs** [keepassxreboot/keepassxc#6397]
I have two datases, one for sharing between computers and another probably to be housed only on one system. I had so far all data in a single database. I created a second-one and I realized that I cannot move entries from one databse into the other, new one. Do I really have to re-type the data or export whole database nr. one into CSV, delete most lines and then import it into database nr. two?

Can't I even export just a few entries? Can't the CSV be at least encrypted before writing to a disk? Could it be piped straight into keepassxc into the new database? Whatver, what would help me to move a dozen of tough-to-retype entries.

I know, a feature request for some future. Thnak you to those willing to take a crack at it once.

**Comment by droidmonkey** [comment]
To move, just drag an entry to the other database and drop it on the desired group. To copy, drag then press and hold CTRL, drop on desired group.

**Comment by droidmonkey** [comment]
A more direct method has been requested in #2074. Closing as duplicate.

**Comment by mmokrejs** [comment]
Thank you for explanation how to handle it. So I conclude the interface is really not intuitive. I have two tabs, each per databse. If I move an entry with mouse and keep it for a loooong while about the tab of the other databse, indeed the GUI then show tree of the other databse and, once I move the entry over the root folder, I can move it there. Some hover() messages popping up could navigate me what I am doing.

Would right click "Move entry" in the context menu exist it would at least make me aware of this functionality (like Copy, Duplicate, Delete, New already exist). The manual does not say anywhere how to move an entry to another database.
