### ISSUE TITLE
[Auto-Type] Increase max inter-key delay to 300 ms

### ISSUE THREAD

**Issue by Pomianowski** [keepassxreboot/keepassxc#6398]
## Overview
The new functionality has many advantages due to the fact that almost every bank in Poland uses these terrible single letters passwords. In any case, several banks introduce delays between each letter being entered.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Download the KeePassXC 2.7.0-snapshot (805574c)
2. Create a new sequence from pickchars, e.g. {DELAY 2000}{DELAY=100}{PICKCHARS}{ENTER}
3. The bank in protection against bots introduces a delay between each letter of the password. The 100ms delay is way too fast. Login failed.

## Expected Behavior
Entering characters slowly.

## Actual Behavior
Very fast typing of characters, preventing proper logging in.

## Solution
Functionality {PICKCHARSDELAY = 500} for adding extra delay.
or
If the user has {DELAY = 1000} and {PICKCHARS}, only pickchars are affected.

## System
KeePassXC - 2.7.0-snapshot
Revision: 805574c
Operating System: Windows 10.0.19042 Build 19042
Desktop Env: Windows NT X64

**Comment by droidmonkey** [comment]
Great find! I did not implement the DELAY= command correctly in my refactor. It only ever uses to initial starting delay as the inter-keypress delay. That is a bug.

**Comment by Pomianowski** [comment]
> Great find! I did not implement the DELAY= command correctly in my refactor. It only ever uses to initial starting delay as the inter-keypress delay. That is a bug.

Hi, thank you for your quick reply. But the delay itself doesn't quite fix it.
If we enter more than 100, KeePass says it's a error - because we can use a maximum delay of 100ms. This is definitely not enough, because in the case of https://login.ingbank.pl/mojeing/app/#login, about 250ms should be appropriate. Or even more

**Comment by droidmonkey** [comment]
OK sorry I was looking at the code on mobile and missed that we moved delay into the key typing itself, which is correct. Your actual problem is you need an inter-key delay of longer than 100 ms. We can increase the max delay to 300 ms.

**Comment by droidmonkey** [comment]
I upped it to 500 just to be safe.

**Comment by Pomianowski** [comment]
> I upped it to 500 just to be safe.

Thank you for solving the bug so quickly! If you could just take a peek at #6399 it would be great.
