### ISSUE TITLE
Clear password input after switching tab

### ISSUE THREAD

**Issue by xf-** [keepassxreboot/keepassxc#640]
## Expected Behavior

Keepassxc should clear the password input on inactive tabs.

## Current Behavior

I switch the tab and password will still be present after i go back with option for plain text.

## Possible Solution

Clear password on inactive tabs

## Context

I use multiple files splitted into tabs in UI. After i start to type a password and order of the tabs has changed, i will switch to correct database and maybe forget to clear password. 

## Your Environment

* KeePassXC version/commit used: 5.1.4 - git build last week

**Comment by droidmonkey** [comment]
I am really not sure what the issue is. Can you maybe explain it using screenshots?

**Comment by xf-** [comment]
You have all the security feature like autolock, but if i start to type a password for a xdbx and switch the tab the password will remain and can be viewed in plain text.

**Comment by TheZ3ro** [comment]
@xf- tell me if I'm right:

You have 2 DB opened (so let's say 2 tab)
- in the first tab you add a new entry
- click the button to see the password field in plain text
- start typing the password
- change the tab to the other database
- change the tab to the first database
- the password is still there in plain text

**Comment by xf-** [comment]
![image](https://user-images.githubusercontent.com/1295633/27146064-5022e49a-5138-11e7-893e-5ec35875c425.png)
I forget the first password (i'm in a hurry) and will remain accassable

![image](https://user-images.githubusercontent.com/1295633/27146116-7751cb9e-5138-11e7-8d31-7d840ac4016d.png)


I fo

**Comment by droidmonkey** [comment]
I do not agree that this is a problem. I personally find it incredibly annoying when fields are blanked for benign reasons.
