### ISSUE TITLE
Export: Group Only

### ISSUE THREAD

**Issue by Forshock** [keepassxreboot/keepassxc#6402]
Allow export of only specific group.
Right-click menu option or the like, to export only the selected.

Current export is for entire database

**Comment by droidmonkey** [comment]
Duplicate of #1940

**Comment by Forshock** [comment]
Not exactly...
Being able to simply export to a CSV for use within another manager or for archiving.
This Keeshare process seems much more complicated than necessary for such a simple task.
There is already an export function, which can surely be done with Keeshare, but it isnt the same thing.

**Comment by droidmonkey** [comment]
That request has nothing to do with keeshare. That was just a comment.

**Comment by Forshock** [comment]
> That request has nothing to do with keeshare. That was just a comment.

Im not sure I follow?

The suggested duplicate entry ends with setting up Keeshare for sharing specific groups/entries.
Reviewed the User Guide, the only export option is the entire database.

**Comment by droidmonkey** [comment]
The request itself is for exporting a selection of entries or groups to another database... or csv file... or html. If you want to set a group as a shared database that is keeshare, just ignore the last two comments on that report.
