### ISSUE TITLE
Unresponsive to keyboard input when Adding entry

### ISSUE THREAD

**Issue by rvernica** [keepassxreboot/keepassxc#6403]
## Overview

I'm trying to manually add an entry to the database. In the _Add entry_ screen, the keyboard is unresponsive. I set the prompt on the _Title_, _Username_, or _URL_ but the characters I type on the keyboard don't appear in the fields. If I keep a key pressed for a long time, the character eventually appears, but it takes about five seconds for each character. The _Password_ field seems to be the only one that is responsive at the expected speed. There seems to be the same problem for _Edit entry_

KeePassXC - Version 2.6.4
Revision: 34a78f0
Operating System: Linux
Desktop Env: Gnome
Windowing System: Wayland (Fedora 33)
Firefox 87.0
KeePassXC-Browser 1.7.8.1

**Comment by rvernica** [comment]
I tried closing Firefox but that did not help.

I tried restarting KeePassXC and that help. The fields in _Add/Edit entry_ screen are now responsive. I would guess that KeePassXC got in a hanged state and no input worked in any of the text fields.

**Comment by droidmonkey** [comment]
See #5608, this is a problem with package conflict in Fedora 33.
