### ISSUE TITLE
Unlock Multiple Databases Using The Same Credentials, With One Authentication

### ISSUE THREAD

**Issue by grravity** [keepassxreboot/keepassxc#6404]
## Summary
Suggesting the ability to unlock multiple database files using the same credentials, with a one time authentication. 

## Context
For example, if I have two databases and they both use the same password and key-file (in theory this can be considered a security risk, however I think that should be left up to the user to decide.), they can simply select database one and two, and then type the password, select the key-file, etc. then it unlocks them both at once. 
This would make it significantly easier than needing to manually re-type the password twice in a row, just to open both databases.

**Comment by droidmonkey** [comment]
Use auto open: https://keepassxc.org/docs/KeePassXC_UserGuide.html#_automatic_database_opening

**Comment by seniorm0ment** [comment]
Thank you! This is great.
