### ISSUE TITLE
Unlocking A DB In Background Takes Away Focus From Password Field In Another DB Tab

### ISSUE THREAD

**Issue by seniorm0ment** [keepassxreboot/keepassxc#6405]
## Overview
Not sure if a bug, or intended by design. I guess both are reasonable to assume.
When unlocking one database, then you tab to another database, if the first one is still unlocking (due to the nature of decryption time values, encryption methods, etc. it can take up to a few seconds). Once it unlocks in the background, it takes away focus of the password field from the currently typing database (second db), and presumes focus on the first. 

This basically means if you're typing the password to database two, while the first is unlocking still, once the first unlocks, it cuts off your typing in the second database and you have to re-click on the enter password field.

## Steps to Reproduce
1. Have two databases open (locked). You may need to set decryption time value to 5s (max).
2.  Enter credentials for first database, click ok to unlock.
3.  While it's unlocking, switch to the second database tab and start typing anything, once the first database unlocks it cuts off text.

## Expected Behavior
I expect it to simply unlock, without taking away focus.

## Actual Behavior
It takes away focus of the second database password box, and cuts off the typing, requiring the user to re-click the enter password box.

## Debug 
KeePassXC - 2.6.4
Revision: 34a78f0

Operating System: Artix Linux, Windows 10
Desktop Env: dwm (Artix Linux)
Windowing System:  X11 (Artix Linux)

**Comment by droidmonkey** [comment]
#6372
