### ISSUE TITLE
Homepage, FAQ: Broken yubico link

### ISSUE THREAD

**Issue by Jade64** [keepassxreboot/keepassxc#6407]
## Overview
Link to video does not work.

https://keepassxc.org/docs/#faq-yubikey-2fa
Question: How do I configure my YubiKey / OnlyKey for use with KeePassXC?
I would need this answer but it is hidden in a video link that does not work:
https://www.yubico.com/products/services-software/challenge-response/

## Expected Behaviour
Either explain it directly or repair the link.
Thank you!

**Comment by droidmonkey** [comment]
This is fixed
