### ISSUE TITLE
[feature requests]

### ISSUE THREAD

**Issue by b3wii** [keepassxreboot/keepassxc#6408]
Hi, thanx for this useful program. Two things are really annoying:

1. The username is hidden lke the password in default list view which makes your life hard if you have multiple accounts with the same entry name.
2.  Copy username and password should be first in the list when you right-click on a record in default list view.

**Comment by droidmonkey** [comment]
1. Ctrl+Shift+B or go to View -> Hide usernames
2. We don't encourage copy/paste, use Auto-Type as much as possible. You can also use keyboard shortcuts or double click the username / password fields in the entry view to copy to clipboard.

**Comment by b3wii** [comment]
>     1. Ctrl+Shift+B or go to View -> Hide usernames
> 
>     2. We don't encourage copy/paste, use Auto-Type as much as possible. You can also use keyboard shortcuts or double click the username / password fields in the entry view to copy to clipboard.

Ok. Thank you!
