### ISSUE TITLE
Microsoft Edge disabled on Linux

### ISSUE THREAD

**Issue by paulchubatyy** [keepassxreboot/keepassxc#6409]
## Overview
When enabling browser integration with KeepassXC, Microsoft edge is not available for selection because the checkbox is disabled.

## Steps to Reproduce

1. Install [KeepassXC extension](https://microsoftedge.microsoft.com/addons/detail/keepassxcbrowser/pdffhmdngciaglkoonimfcmckehcpafo) to Microsoft Edge dev build on linux
2. Open `Browser Integration` tab on Settings
3. See `Edge` checkbox being disabled

## Expected Behavior

`Edge` checkbox is available for selection

## Actual Behavior
![image](https://user-images.githubusercontent.com/98631/114749322-ad22c100-9d07-11eb-93fb-ff74cfcf43c8.png)

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.4
Revision: 34a78f0

Qt 5.14.2
Debugging mode is disabled.

Operating system: Pop!_OS 20.10
CPU architecture: x86_64
Kernel: linux 5.11.0-7612-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- libgcrypt 1.8.5

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: Gnome
Windowing System: X11

**Comment by droidmonkey** [comment]
Edge is still in Beta on Linux. Use the custom browser option under advanced settings if you want to try Edge out.

**Comment by carestad** [comment]
Edge was [very recently released with a stable version for linux](https://www.omgubuntu.co.uk/2021/10/microsoft-edge-for-linux-now-stable). Could this perhaps be considered now? :grinning:

**Comment by droidmonkey** [comment]
Sure can @varjolintu
