### ISSUE TITLE
Solve "No keyboards shortcuts in QT apps" for the snap

### ISSUE THREAD

**Issue by pachulo** [keepassxreboot/keepassxc#641]
## Expected Behavior

All keybaord shortcuts should work, not only those attached to actions present in the menubar.

## Current Behavior

In the snap version of keepassxc the keyboard shortcuts for actions attached only to the menubar (i.e. and not also to the toolbar) do not work.
The problem was with QT libraries, and is now solved in Xenial repos: https://bugs.launchpad.net/appmenu-qt5/+bug/1380702
## Possible Solution

Just compiling the snap again will do, because it will be using the recently updated packages from Xenial repos.
I've tried to do myself and now the shortcuts are working.

## Steps to Reproduce (for bugs)

1. Try to copy the URL of an entity with the keyboard shortcut (Ctrl+Alt+U)

## Your Environment

* Qt version (e.g. Qt 5.3): 5.5
* Operating System and version: Ubuntu 16.04

**Comment by droidmonkey** [comment]
This works in the 2.2.0 snap I just uploaded. The only shortcut that does not work is CTRL+U due to a dbus failure. Currently trying to resolve that in #418
