### ISSUE TITLE
Right-click context menu appears on wrong monitor after laptop sleep

### ISSUE THREAD

**Issue by thenickname** [keepassxreboot/keepassxc#6411]
## Overview

On a Macbook with external monitor attached: Once sleep kicks in (or probably just screen locks after a while) and then after waking up the computer again, the right-click menu will always appear on the laptop screen. Regardless whether the main window is on the laptop screen or on the external monitor.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Start KeePassXC on a laptop that has an external monitor attached to it (in my case a Macbook)
2. Put the laptop to sleep and wait until the external monitor goes into stand by
3. Wake the laptop up again
4. Make a right-click to show a context menu in KeePassXC

Note: I couldn't reproduce this error reliably. Sometimes after waking up everything just works fine. Other times the context menu will appear on the wrong monitor. Maybe it makes a difference, whether the laptop goes to sleep by itself or if I put it to sleep deliberately 🤷‍♂️

## Expected Behavior
The right-click menu always appears in place, exactly where I clicked and also where the window currently is. If the window is placed on the external monitor, then also the menu should appear on the external monitor.

## Actual Behavior
The right-click menu will appear on the laptop monitor, even if the actual application window is on the external monitor.

## Context
KeePassXC - Version 2.6.4
Revision: b93fbd1

Qt 5.15.2
Debugging mode is disabled.

Operating system: macOS 11.2
CPU architecture: arm64
Kernel: darwin 20.3.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (only unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
- libgcrypt 1.9.1

Operating System: macOS BigSur

**Comment by droidmonkey** [comment]
Does this happen only when the app is maximized or touching the edge of the screen? If so it's a qt bug.

**Comment by LecrisUT** [comment]
Actually I've got a similar issue on various apps, not sure where it comes from, e.g. TexStudio also. The issue I find is any window opened on the secondary monitor will not appear. If I zoom out to the desktop selection screen and back, the window appears on the main screen. It's annoying, but it might not be due to the app implementation, probably just back-end issue.

**Comment by thenickname** [comment]
> Does this happen only when the app is maximized or touching the edge of the screen? If so it's a qt bug.

no, it also happens if the window is not maximized and not touching the edge of the screen.

**Comment by thenickname** [comment]
a small addition: this bug occurs not only with context menus, but also with hover tool tips. They show up on the wrong screen.

**Comment by droidmonkey** [comment]
This is most definitely a qt bug

**Comment by thenickname** [comment]
So if it's a qt bug is it still okay for the bug to be documented here? Should qt get notified?

**Comment by droidmonkey** [comment]
A bug report should be opened on https://bugreport.qt.io. I prefer to not keep it open here since it isn't our code causing the problem.

**Comment by thenickname** [comment]
I have reported the bug to the Qt project: https://bugreports.qt.io/browse/QTBUG-93364
