### ISSUE TITLE
Yubico Key - Same issue with 2 different keys

### ISSUE THREAD

**Issue by piraterx** [keepassxreboot/keepassxc#6412]
I have yubico NFC 5 and USB C. I use them with other website and it works. It doesn't somehow works with keepassxc. Before posting, I used with bitwarden, and it works.

**Comment by droidmonkey** [comment]
Did you configure a slot for challenge response? https://keepassxc.org/docs/#faq-yubikey-howto

**Comment by piraterx** [comment]
It did worked. I thought it will be as easy as other website, I use where I just touch button and it works.
