### ISSUE TITLE
YubiKey challenge-response broken in develop

### ISSUE THREAD

**Issue by buggie5432** [keepassxreboot/keepassxc#6420]
## Overview

It appears that the Botan switch somehow broke the YubiKey challenge-response feature.

## Steps to Reproduce

1. Build 86ddd702fb6da4e236cc48937c5eb205aed86239 (commit before Botan implementation)
2. Create a database with YubiKey challenge-response
3. Close and reopen database to confirm it works
4. Build any commit starting from 80809ace677a920b62be2259c1156d419adcdb97 currently up to 805574cac1c5295b37541c67d150eaf247e845b2
5. Try to open the database from step 2 again.

## Expected Behavior

I expect the challenge-response to work on databases created pre-Botan.

## Actual Behavior

The challenge-response does not work on databases created pre-Botan.

## Context

Haven't been able to pinpoint the source of the issue, but I can tell that the inverse case is also broken. Post-Botan databases can't be opened with the YubiKey challenge-response in pre-Botan builds.

Operating System: Linux
Desktop Env: XFCE
Windowing System: X11

**Comment by buggie5432** [comment]
I realize that develop shouldn't be considered stable, but I couldn't find anything in the Botan PR mentioning that this still needs to be fixed.

**Comment by droidmonkey** [comment]
Uh oh! I could have swore I tested this. Probably a simple fix, thank you for reporting.
