### ISSUE TITLE
Freeze upon 'Merge Request' for unsaved changes

### ISSUE THREAD

**Issue by AJJLagerweij** [keepassxreboot/keepassxc#6421]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
Once in a while I get a KeePassXC pop-up window (shown below) asking me to merge the unsaved changes into the database before it saves. When I press 'Discard' or 'Merge' (Samenvoegen) the pop-up closes but KeePassXC freezes. I have to force quit it, to get it working again. The file is shared through Synology Drive and I'm also using KeeShare.

![afbeelding](https://user-images.githubusercontent.com/31255888/115137569-829a7600-a02f-11eb-990e-a9a5f6ec5693.png)
Translation:
"**Merge Request**
The database file has changed and there are unsaved changes. Do you want to merge these changes?
**Discard** or **Merge**"

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Create a *.kdbx database and *.kdbx.share shared database on a Synology NAS.
2. Share the folder with your pc using Synology drive. (this creates a local copy)
3. I tried tinkering with the storage settings, a.o. the autosave option could cause issues and duplicates. Currently my storage settings are:
    - [ ] Autosave after every change
    - [x] Autosave when locking database
    - [x] Autosave non-data changes when locking database
    - [ ] Backup database file before saving
    - [x] Auto reload the database when externally modified
    - [ ] Safely save database files
4. Open the database for a browser use of the database, do not edit the database itself, just use the KeePassXC-browser plugin .
5. Wait for the database to lock due to inactivity.
6. Sometimes this will give a "Merge Request" pop-up (I see it 3/4 times a week) if it does it will always crash.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
I expect it to merge or discard and no freeze.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
The pop-up closes, but KeePassXC freezes.

## My thoughts and detailed questions.
I'm not surprised that a shared drive from the NAS can cause issues to the saving behaviour, especially in combination with a shared database file.
Hence I'm not surprised by the "Merge Request" messages but I did not expect that to cause freezes.
It might very well be that one of my settings is not optimal.

As a result I have the following questions that might help me figure out what is going on:
1. What do the save options do exactly? The [User Guide](https://keepassxc.org/docs/KeePassXC_UserGuide.html#_storing_a_database_file) does not discuss them in detail. Especially for options like 'Safely save database' it is unclear what it actually changes, similarly I'm not sure what 'non-data changes' are (Autosave non-data change option). It is likely that I'm doing something wrong because my lack of understanding of some options). Is there a way to store the database in a way that is less likely to cause the entire "Merge Request" pop-up.
2. Is there a way that I can monitor what KeePassXC is doing, such that I can catch in a more detailed way what it is freezing upon?

## Context
[NOTE]: # ( Give us any additional information you may have. )
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Versie 2.6.4
Revisie: 34a78f0

Qt 5.12.8
De foutopsporingsmodus is uitgeschakeld.

Besturingssysteem: Ubuntu 20.04.2 LTS
CPU-architectuur: x86_64
Kernelversie: linux 5.8.0-49-generic

Geactiveerde extensies:
- Auto-type
- Browserintegratie
- SSH-agent
- KeeShare (getekend en ongetekend delen)
- YubiKey
- Integratie van geheime diensten

Cryptografische bibliotheken:
- libgcrypt 1.8.5

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux (Ubuntu 20.04)
Desktop Env: Gnome
Windowing System: X11

**Comment by droidmonkey** [comment]
We are discussing this very problem over here: https://github.com/keepassxreboot/keepassxc/issues/5637#issuecomment-821812042
