### ISSUE TITLE
CLI: Multiple entries with same Title value 

### ISSUE THREAD

**Issue by catleeball** [keepassxreboot/keepassxc#6424]
## Overview

When using `keepassxc-cli show pw.kdbx $TITLE`, only the first entry matching `$TITLE` is printed. Databases may contain multiple unique records with the same title, but there doesn't seem to be a way to print all matches, or to filter down to a certain entry.

This can happen in scenarios where someone has multiple accounts on a site all titled "Foo Site", but with different usernames, passwords, etc.

## Steps to Reproduce

1. Have a kdbx database with >1 `<Entry>` that has the same values for `<key>Title</key>`
2. Run `keepassxc-cli show "Non-Unique Title"`
3. Get only the output of the first entry appearing in the database

## Expected Behavior

Expected behavior is all Entries matching a given Title key will be printed.

Additionally, it would be nice to search the database on several fields, for example something like:

```
keepassxc-cli show --title="Foo Site" --username="Cat"
```

## Actual Behavior

Only the first entry is printed, and no CLI way to access other entries of same title (that I know of).

## Context

I don't have a GUI session on this machine, so I'm not sure how to access the debug menu's info. It was installed through apt on Ubuntu, here's some info:

```
$ keepassxc-cli --version
2.4.3

$ apt info keepassxc
Package: keepassxc
Version: 2.4.3+dfsg.1-1build1
Priority: optional
Section: universe/utils
Origin: Ubuntu
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Julian Andres Klode <jak@debian.org>
```

- Operating System: Linux, Ubuntu 20.10, `$ uname -a  \n  Linux bip 5.8.0-50-generic #56~20.04.1-Ubuntu SMP Mon Apr 12 21:46:35 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
- Desktop Env: None, accessing over SSH
- Windowing System: N/A

Thanks!

**Comment by droidmonkey** [comment]
Duplicate #3720
