### ISSUE TITLE
Incorrect T0TP sync

### ISSUE THREAD

**Issue by EdgeLord836** [keepassxreboot/keepassxc#6426]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Open kdbx in dropbox via Stronbox on IOS & macOS
2. Open kdbx in dropbox via KeepassXC on PC
3. Different 0TP sync across, with KeepassXC being incorrect.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
 I expected the same OTP on both platforms.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Instead I see 2 different OTP with the one on KeepassXC being incorrect.

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.4
Revision: 34a78f0

[NOTE]: # ( Pick choices based on your environment )
Operating system: Windows 10 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.19042

**Comment by droidmonkey** [comment]
Sync your time on your computer
