### ISSUE TITLE
gpw - generates pronounceable passwords

### ISSUE THREAD

**Issue by nudnyzjeb** [keepassxreboot/keepassxc#6427]
## Examples
please add gpw or similar utility for generating "Anonymous" type of usernames sir
https://www.multicians.org/thvv/tvvtools.html#gpw
thank you please

**Comment by droidmonkey** [comment]
Please use the passphrase generator for your purposes. We are not going to implement additional generators beyond what we currently have.

**Comment by nudnyzjeb** [comment]
excuse me, it's a PRONOUNCEABLE generator
password generator would just output "jkjhkloi" strings

**Comment by nudnyzjeb** [comment]
besides, where is my "Apply Username" buttom

**Comment by droidmonkey** [comment]
Copy and paste from the passphrase generator if you need to. There is no real reason to generate a username.
