### ISSUE TITLE
Weigh/prioritize search results that match the title field

### ISSUE THREAD

**Issue by tredondo** [keepassxreboot/keepassxc#6430]
## Summary
I'm often searching for an entry of my bank, which has only two characters. The results include several entries, which only have those characters in the title, while the entry for my bank appears somewhere in the middle. No big deal, just that it adds a few keystrokes to navigate to the desired entry, and I can't muscle-memorize it because the number of intervening entries may change in the future as I add entries.

## Examples
Here, you can see how the first search result for "hyp" is not the entry with "hyp" in the title.
![image](https://user-images.githubusercontent.com/10043369/115345440-8373fa80-a14a-11eb-8f2c-8a0006679be6.png)

## Context
Just trying to log into a frequently-used application as quickly as possible. If it were possible to assign a higher search weight to the `Title` field, that would make the desired entry show up first in the search results, so Ctrl+F, `<...>`, Enter, Ctrl+Shift+V would work right away.

**Comment by droidmonkey** [comment]
The concept of a "search score" has been brought up before. It is much more challenging then just seeing how close the title is. Depends on what your searching for.

For your use case there are two options that you can do today:
1. Use a title search: `t:hyp`
2. Add a unique sequence to the bank title that bounds the search more. Also multiple words are treated as "and" so `hyp bank` must match both words.
