### ISSUE TITLE
Fatal error when changing password - windows 10 - 

### ISSUE THREAD

**Issue by koenlapauw** [keepassxreboot/keepassxc#6432]
I get following error when changing the password of an existing database 
![Knipsel](https://user-images.githubusercontent.com/70053534/115424921-6cdbab00-a1ff-11eb-94b2-eb2f6eac0dae.PNG)

**Comment by droidmonkey** [comment]
Please include the debug information in the about window.

**Comment by koenlapauw** [comment]
***@***.***D7367D.0A774700]
Met vriendelijke groeten,

Koen LAPAUW
Director

CAPITO NV – Boerderijstraat 76B – 8500 Kortrijk – Tel : +32 56 20 38 26

Van: Jonathan White ***@***.***>
Verzonden: dinsdag 20 april 2021 17:55
Aan: keepassxreboot/keepassxc ***@***.***>
CC: Koen Lapauw ***@***.***>; Author ***@***.***>
Onderwerp: Re: [keepassxreboot/keepassxc] Fatal error when changing password - windows 10 - (#6432)


Please include the debug information in the about window.
