### ISSUE TITLE
GUI of the app is waay too small (DPI scaling doesn't work)

### ISSUE THREAD

**Issue by danger89** [keepassxreboot/keepassxc#6436]
## Overview

When using high resolution sceen resolutions. You may want to scale up the user-interface. THis actually works great with all my apllications! Except KeepassXC :(((.

Its unworkable, I don't understand the problem since I thought that all Qt apps scales well automatically. 

## Steps to Reproduce
1. Use Linux Mint 
2. Use a 4K scree (not required)
3. Enable user-interface scaling (Hi-DPI)

Display Settings:
![image](https://user-images.githubusercontent.com/628926/115628112-64b76480-a300-11eb-9151-5dac9f0cd78d.png)

## Expected Behavior

I expect the GUI to scale accordingly automatically, just like other applications like Firefox, GTK apps, QT apps, ..

## Actual Behavior

Well if words doesn't say enough, see this (its unreadable for me):
![image](https://user-images.githubusercontent.com/628926/115628512-0c349700-a301-11eb-9816-2ef756696bf8.png)

Do you notice the small window in the center, this should be KeepPassXC 🍰 

## Context
KeePassXC 2.6.4
Operating System: Linux
Desktop Env: Cinnamon
Windowing System: X11

**Comment by danger89** [comment]
Its fully unusable. I think Qt should be able to deal with this without any effort. I don't understand this issue.

**Comment by droidmonkey** [comment]
You are probably using the snap which doesn't scale. Use the appimage.

**Comment by danger89** [comment]
Actually I'm using the official ppa (Deb) file.

**Comment by droidmonkey** [comment]
See here https://doc.qt.io/qt-5/highdpi.html#high-dpi-support-in-qt
