### ISSUE TITLE
Yubikey Support via MS RDP

### ISSUE THREAD

**Issue by cht47** [keepassxreboot/keepassxc#6439]
Hello, 
I'm currently working on a project to secure the passwords of our employees. As long user of KeePass and KeePassXC I'm planning to rollout it company wide. For additional security we bought some Yubikeys 5 NFC and I programmed the Slot 2 with HMAC-SHA1 which works fine in normal use case.
But because of Covid-19 most employees are in HomeOffice. Some have notebooks, so no issue there but some use their personal PC and connect via VPN and RDP to their company PC. 
What I did was enabling Smartcard in the Remote Settings:
![image](https://user-images.githubusercontent.com/2283180/115684826-f7cfb900-a357-11eb-8fa7-24accbd8752c.png)

Which seems to work with the newer Yubikey applications like Authenticator, even the button press is working. 
The Yubikey Manager finds the Yubikey and shows a serial, but you can't config everything. 
The old Personalization Tool doesn't find the Yubikey at all. 
So I guess they changed the API in their new applications 
![image](https://user-images.githubusercontent.com/2283180/115688466-7c700680-a35b-11eb-9a23-24380404901c.png)

Did I miss something in the configuration / settings or is the keepass implementation like the personalization tool? I don't know anything about the yubikey API.

It would be cool if someone could lead me to a workaround or is there any change planned?

**Comment by droidmonkey** [comment]
We use the yubikey personalization code base, unfortunately. It is rather terrible so I wonder what they did to improve it in their new tool.

**Comment by droidmonkey** [comment]
Is there an option in RDP to share a specific USB interface versus a smart card? It could be presenting the yubikey as a pkcs#11 device instead of a HID device.

**Comment by cht47** [comment]
Only the ressources shown in the first screen. smartcards, ports, drives, some videorecording devices and additional supported plug & play devices, which I tried but doesn't seem to make any difference. 

It would probably be easier to support TOTP for the DB (does that make sense for a local application?) systemtime must be correct then, but would enable 2FA with Yubikey OTP and every smartphone auth.

**Comment by droidmonkey** [comment]
You can't do totp client side,  the secret needs to be accessible which defeats the purpose

**Comment by droidmonkey** [comment]
I don't think this is even possible without sharing the USB interface itself. What you are seeing in the modern yubikey tool is a subset of features based off of a smart card interface. Challenge response uses raw USB transactions to work.

**Comment by cht47** [comment]
> I don't think this is even possible without sharing the USB interface itself. What you are seeing in the modern yubikey tool is a subset of features based off of a smart card interface. Challenge response uses raw USB transactions to work.

Thanks for the input, with that I've searched for other solutions to passtrough the whole USB device and its working:

![image](https://user-images.githubusercontent.com/2283180/115876917-2d9f9b00-a447-11eb-91c2-586530c26b48.png)

The trick is to activate RemoteFX and to add the GUIDs from the Yubikey to the client registry. After that you can select the yubikey.
![image](https://user-images.githubusercontent.com/2283180/115877137-65a6de00-a447-11eb-8c4a-5f59de702056.png)

From what I found, its easier with VMware remote desktop. 

I used this article as guide
https://queensidecastle.com/guides/use-a-yubikey-remotely-over-rdp
PS: I have to test his update with no longer working. My client is up to date, but the VM I used for testing is an LTSB Windows 10. It did not work with a new Server 2016
Hopefully it will work with my private PC which is also up to date.

Anyway, it seems to be an Microsoft limitation which you can't solve on the software end. Thanks for the help

Best regards

**Comment by droidmonkey** [comment]
That's awesome

**Comment by cht47** [comment]
for the sake of completeness, It's also working with an up to date windows 10 to another windows 10 via VPN and MS RDP. 
Sometimes you have to press reload in KeePassXC because the Yubikey doesn't get recognized. Maybe timeout? And I get the blue badge that I have to press the Yubikey button (which I have not programmed) but it disappears instantly and the DB is open.
It seems higher latency could be a problem but it works :)

**Comment by droidmonkey** [comment]
The press button banner shows if the challenge response is not completed within a certain amount of time. It's a fail safe user message can he safely ignored.

**Comment by TheOneRing** [comment]
Hm sadly my rdp client runs on a mac so the suggested solution does not work.
I can only forward smart cards and the yubico authenticator can actually access it.
![image](https://user-images.githubusercontent.com/200626/118357467-a5f70900-b57a-11eb-83ed-922e76bf9cfd.png)
