### ISSUE TITLE
in a snap, open dialog crashes keepassxc 2.6.4

### ISSUE THREAD

**Issue by jzacsh** [keepassxreboot/keepassxc#6446]
## Overview

ctrl+o crashes keepassxc immediately, but `keepassxc mydb.kdbx` works

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )

0. _pre-req_/background: **prefer snap**

    - a. `sudo apt install keepassxc` (`2.4.3+dfsg.1-1build1` was the version, per `apt show` output)
    - b. use keepassxc (no issues)
    - c. get warning that keepassxc is old (or maybe warning is in the Chrome browser integration?)
    - d. go to https://keepassxc.org/download
    - e. use `sudo apt remove keepassxc && sudo snap install keepassxc`
    - f. `keepassxc --version` says `2.6.4` (after warnings<sup>1</sup> every interaction generates)

1. open keepassxc (either via `/snap/bin/keepassxc` or gnome desktop icon)
2. launch open dialog (to pick a database) - all methods have same behavior _(eg `ctrl+o`, open-folder icon, "open existing database" button in middle of screen, etc.)_
3. keepassxc disappears

## Expected Behavior

step (3) should have been a file-picker dialog.

## Actual Behavior

step (3) keepassxc appears to close

### error logs

my running `journalctl --pager-end --follow --catalog` shows these entries:

```
Apr 23 07:47:23 finna keepassxc[54802]: Cannot open pixbuf loader module file '/home/myusername/.cache//gdk-pixbuf-loaders.cache': No such file or directory

                                        This likely means that your installation is broken.
                                        Try running the command
                                          gdk-pixbuf-query-loaders > /home/myusername/.cache//gdk-pixbuf-loaders.cache
                                        to make things work again for the time being.
Apr 23 07:47:23 finna keepassxc[54802]: Could not load a pixbuf from icon theme.
                                        This may indicate that pixbuf loaders or the mime database could not be found.
Apr 23 07:47:23 finna gnome-shell[54802]: **
Apr 23 07:47:23 finna gnome-shell[54802]: Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /snap/keepassxc/1309/data-dir/icons/Adwaita/16x16/status/image-missing.png: Unrecognized image file format (gdk-pixbuf-error-quark, 3)
Apr 23 07:47:23 finna keepassxc[54802]: Cannot open pixbuf loader module file '/home/myusername/.cache//gdk-pixbuf-loaders.cache': No such file or directory

                                        This likely means that your installation is broken.
                                        Try running the command
                                          gdk-pixbuf-query-loaders > /home/myusername/.cache//gdk-pixbuf-loaders.cache
                                        to make things work again for the time being.
Apr 23 07:47:23 finna systemd[1450]: snap.keepassxc.keepassxc.b92bb3c3-73e5-4f52-8552-b3b8543680f3.scope: Succeeded.
```

I'd try `gdk-pixbuf-query-loaders` but it's not in my `$PATH` and unsure what it is. Also I'm guessing it needs to be run in the snap's own container? This is where I stopped.

### workaround: CLI passing DB as argument

I can successfully work around this bug by just doing `keepassxc mydb.kdbx` and I can complete my tasks (just avoid hitting the open dialog). Interestingly, I see all the same log output as above (in the terminal where I launched keepassxc), but only this one shows up a the time of the crash:

```
Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /snap/keepassxc/1309/data-dir/icons/Adwaita/16x16/status/image-missing.png: Unrecognized image file format (gdk-pixbuf-error-quark, 3)
Aborted
```

### "Help → About" output

```
KeePassXC - Version 2.6.4
Revision: 34a78f0
Distribution: Snap

Qt 5.9.5
Debugging mode is disabled.

Operating system: Linux 5.11.0-7612-generic
CPU architecture: x86_64
Kernel: linux 5.11.0-7612-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- libgcrypt 1.8.1
```

Operating System: Linux
Desktop Env: Gnome
Windowing System: X11
Distribution: Pop OS

----

<sup>1</sup> here are the warnings i'm seeing with every interaction, it seems:
```
$ keepassxc --version
/snap/keepassxc/1309/bin/desktop-launch: line 474: /home/myusername/.cache//gdk-pixbuf-loaders.cache: Permission denied
Gtk-Message: 07:37:04.965: Failed to load module "appmenu-gtk-module"

(keepassxc:47265): GdkPixbuf-WARNING **: 07:37:04.972: Cannot open pixbuf loader module file '/home/myusername/.cache//gdk-pixbuf-loaders.cache': No such file or directory

This likely means that your installation is broken.
Try running the command
  gdk-pixbuf-query-loaders > /home/myusername/.cache//gdk-pixbuf-loaders.cache
to make things work again for the time being.
Gtk-Message: 07:37:04.987: Failed to load module "canberra-gtk-module"
Gtk-Message: 07:37:04.989: Failed to load module "canberra-gtk-module"
Qt: Session management error: Could not open network socket
KeePassXC 2.6.4
```

**Comment by droidmonkey** [comment]
This isn't our bug

**Comment by jzacsh** [comment]
yup, agreed, i actually just ran into this with thunderbird too. sorry for the noise
