### ISSUE TITLE
Allow viewing of custom fields in the main window

### ISSUE THREAD

**Issue by roweger** [keepassxreboot/keepassxc#6447]
Original KeePass allows the inclusion of custom fields and additional info as their own columns in the viewing window. 
It looks like KeePassXC doesn't have this capability. Is this something that could be implemented?

![keepass columns](https://user-images.githubusercontent.com/20942184/115946585-0cef3980-a477-11eb-8cf2-06d14dae6669.PNG)

**Comment by droidmonkey** [comment]
#1493
