### ISSUE TITLE
Browser integration is poor

### ISSUE THREAD

**Issue by marco-brandizi** [keepassxreboot/keepassxc#6448]
## Summary
I'm trying to work with the Chrome and Firefox KeePassXC integration and I've to say the user experience with it is very poor.

## Examples
I see the worst in two things:

- it's not possible to set URL patterns or multiple URLs to match. If one web site, or a company has multiple routes to authenticate with the same account, eg, foo.com/login, foo.com/authenticatedRequest, another.service.foo.com/login, it's impossible to make KeePassXC understanding it's the same account, the only way seems to be duplicating the same entry. It should be possible to use multiple URLs in the database entry and/or regular expressions (I'd be fine with using the `|` operator with REs to specify multiple URLs in one string only).

- When I start using the web extension with the web button, it tries to see if KeePassXC is open and, if not, it yields an error. Even worse, if KeePassXC is already open, but on the wrong database (I keep one for web accounts and another for more critical stuff), there is no way to switch to another DB apart from cancelling the operation, going back to the browser and repeating everything. I think the extension could be separated from the desktop app completely, it would just need to open the same .kdbx, possibly after the user selected its path.

**Comment by droidmonkey** [comment]
You did not include your KeePassXC version or operating system so I am not sure if you are using an old version or not, but:

- In the example provided, all those URLs share the same parent domain so you can just store the url as `https://foo.com`. The path part of the URL is not relevant unless you have best matching credentials enabled in the browser settings. Alternatively, you can easily add additional URL's in the entry edit browser tab:
![image](https://user-images.githubusercontent.com/2809491/115960057-4490cc80-a4dd-11eb-94a2-34933de9d71d.png)

- This is a security feature that can be somewhat confusing to new users. The browser integration is, by default, only allowed to search the current active database. If you want it to search all unlocked databases then just enable this setting:
![image](https://user-images.githubusercontent.com/2809491/115960111-77d35b80-a4dd-11eb-8831-b973f8bf9125.png)

This is all nicely covered in our documentation: https://keepassxc.org/docs/KeePassXC_UserGuide.html#_setup_browser_integration

**Comment by marco-brandizi** [comment]
@droidmonkey, thanks for your quick answer, though, peraphs, closing the issue didn't need to be so quick.

I'm using 2.6.4

I discovered it works by domain, I remember it wasn't always working.

I also discovered the additional URLs feature, which is good.

As for "Search in all opened databases", while this is a good workaround, I'd like a smoother workflow: currently, I have to first open the KeePassXC, then reopen the database from the browser button, then authenticate, then I didn't get when I need to re-detect login fields, and eventually, I can use the auto-fill feature.

Ideally, the browser integration could just read a .kdbx file (either locally or from a URL). If this interaction with the app is needed, opening the app when it's not running would help.

Back to "Search in all opened databases", if I keep this option off, when I select "reopen database", I'm forced to reopen the one that was selected in the app, but I'd prefer to configure which one should be selected for opening, since, as you say, it's more secure to keep multiple .kbdx files separated.

**Comment by droidmonkey** [comment]
We are never going to directly open kdbx files with the extension. That is off the table for us.

The workflow for choosing databases and such is being worked over on the extension side so this issue it not needed to track it. 

Thank you for your suggestions.
