### ISSUE TITLE
Using keepassxc-cli password in shell script

### ISSUE THREAD

**Issue by jagrg** [keepassxreboot/keepassxc#6450]
Hello, I'm wanting to use keepassxc-cli in a shell script, but I'm not sure if it's safe to use an encrypted password file. For example:
```
PASSWORD=$(gpg --decrypt $HOME/.passfile.gpg 2> /dev/null)
echo "$PASSWORD" | keepassxc-cli ls -q -R -f /path/to/db -k /path/to/keyfile | fzf
```
And is it safe/safer to use read with the -s (no echo) option instead? For example:
```
IFS= read -s -p "Password: " PASSWORD
echo "$PASSWORD" | keepassxc-cli ls -q -R -f /path/to/db -k /path/to/keyfile | fzf
```
Or is there some other way of doing this? This would make it easy to fuzzy find entries and assign keys to run keepassxc-cli commands from the fzf menu. Thanks for the guidance.

**Comment by Inesgor** [comment]
I like this idea. How about using gpg to make it (probably) even more secure?
Something like: `echo "$(gpg -d /path/to/pass.gpg)" | keepassxc-cli ls -q -R -f`
Additionally one can use pinentry-curses in gpg.conf to not leave the console.
