### ISSUE TITLE
Dependency is not satisfiable: libqt5core5a <=5.3.0

### ISSUE THREAD

**Issue by Mukrosz** [keepassxreboot/keepassxc#646]
Hi there,

I am trying to install [KeepassXC 2.1.4-1](https://github.com/magkopian/keepassxc-debian/releases) on Linux Mint 17.3.
I get and error message: 

> Dependency is not satisfiable: libqt5core5a <=5.3.0

I checked my libqt5 version and it is: 5.2.1

How or where from could I have it updated?

Many thanks!

**Comment by droidmonkey** [comment]
Wow that is a really old version of Mint. You should strongly consider upgrading your os version.

**Comment by phoerious** [comment]
What version (and from where) are you trying to install?

Also please don't delete the issue template.

**Comment by Mukrosz** [comment]
Thanks for your response! My apologies for removing the template.
I am attempting to install version 2.1.4-1 amd 64 from .DEB. 
Exact location is: https://github.com/magkopian/keepassxc-debian/releases/download/2.1.4-1/keepassxc_2.1.4-1_amd64_stable.deb

For reference, I also have a Linux Mint 18 which had no issue installing the exact same package.

**Comment by droidmonkey** [comment]
The simple reason is because Mint 17.3 does not provide the version of qt that we require. You will have to compile the program yourself with your version of qt to use it.

**Comment by phoerious** [comment]
"We" is not quite right. The DEBs are third-party builds (although listed on our website). I'm not quite sure what version of Qt they were compiled with, but apparently it's something like 5.2 or 5.3. Our AppImage is compiled with 5.8 and should run regardless of what Qt version you have on your system. The alternative would be to compile it yourself.

**Comment by Mukrosz** [comment]
Thanks for the comments.
I cannot call myself a linux power user so AppImage is alien to me, so I'll have to research it and see if that can be used on Linux Mint. Either that or compile QT like you guys outlined.

Thank you for pointing me in the right direction.

**Comment by phoerious** [comment]
AppImages should run on almost any GNU/Linux system. Just download it, make it executable and then start it. No installation required.
