### ISSUE TITLE
hidden notes reappear when you select a entry without notes

### ISSUE THREAD

**Issue by raplover** [keepassxreboot/keepassxc#6461]
## Overview
if you hide your notes via settings/security and view a entry with notes in it you have to click to see the note. When you then go to a entry without notes and click on it you see the notes of the other entry. This doesnt happen when you go to a entry with a note in it. Also do entrys without notes then keep the eye and dot's for notes, this stays then on all entrys without notes until you click to see a note without entry.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. go to settings/security/hide notes by standart
2. go to a entry with notes in it, click on the eye to see it
3. click directly to another entry without notes in it and you see the notes of the other entry
4. click on other entrys without notes and you will still see the last note.
5. click on the eye on other entry without notes and the last note will disappear
6. now the "fake dots" of all entrys without notes also disappear
7. once you just click on a entry with notes, the "fake dots" reappear on entrys without notes

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
- when you leave a entry with hidden notes they shouldnt reappear  somewhere else
- entrys without notes should not show any "fake dots" or even not the eye for seeing notes

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.6.4
Revision: 34a78f0

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 10

**Comment by michaelk83** [comment]
Duplicate of #5571 ?

**Comment by droidmonkey** [comment]
Agree closing the other
