### ISSUE TITLE
Auto-Type {CLEARFIELD} is not working on 2.7.0

### ISSUE THREAD

**Issue by Weltraumpenner** [keepassxreboot/keepassxc#6463]
## Overview
Today I updated to 2.7.0-snapshot, because 2.6.x was crashing while doing auto-type quite frequently.
On 2.7.0 the {CLEARFIELD} command is not working anymore.

## Steps to Reproduce
1. Add Auto-Type-Sequenz with {CLEARFIELD}. E.g.: {CLEARFIELD}{USERNAME}{TAB}{PASSWORD}{ENTER}
2. Use Auto-Type 

## Expected Behavior
{CLEARFIELD} should clear the whole, first input-field.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
{CLEARFIELD} is only deleting the last letter of the text in the first input-field.

## Context
Tried on MacBook Pro, Firefox 88.0  and Safari.

[NOTE]: # 
KeePassXC - Version 2.7.0-snapshot
Build Typ: Snapshot
Revision: 8a7be10

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS Big Sur 11.3 (20E232)

**Comment by Weltraumpenner** [comment]
This issue is resolved in newer versions of KeePassXC.

**Comment by Jan-Brugger** [comment]
Same issue is happening again.

**Comment by droidmonkey** [comment]
Confirmed this is broken

**Comment by schwantuschke** [comment]
Yes {CLEARFIELD} deletes only the last character, not the whole input field.

**Comment by JanJK2011** [comment]
I am facing the same issue in v2.7.1. (MacBook Pro, macOS Monterey 12.4)

**Comment by droidmonkey** [comment]
I figured out what's wrong... this is my fault... although the Apple docs say you should send a modifier key and then the actual key (eg, CMD then A)... that is a total lie. I have to fix my code that handles Auto-Type modifiers like +, ^, % etc to make Clearfield work again.

**Comment by klassm** [comment]
Should this work by now? I just tried on 2.7.4 - and it still seems to be broken  ☹️

**Comment by crchapma** [comment]
> Should this work by now? I just tried on 2.7.4 - and it still seems to be broken  ☹️

Same here. 2.7.4, Running Ventura 13.1

**Comment by pstueck** [comment]
now on 2.7.6 and the fields are still not cleared … at least with [SQuirreL](http://www.squirrelsql.org/) and on web server logins.  
Right now the content of the field is not touched at all. 

Ubuntu 22.04, X11 here.  
`Linux ******* 6.2.0-36-generic #37~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Mon Oct  9 15:34:04 UTC 2 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by ThermoMan** [comment]
Same problem here when pasting into Remote Desktop.
local machine
Windows 10
KeePass 2.5.6
remote machine
Ubuntu 22

Override URL is: `cmd://"mstsc.exe"  /w:1880 /h:1040 /v:{URL} /prompt`
Auto-Type is `{TAB 4}{CLEARFIELD}{USERNAME}{TAB}{PASSWORD}{ENTER}`
The TAB 4 places the cursor at the end of the pre-filled in field and then only deletes the last character in that field.
