### ISSUE TITLE
Chrome plugin can't connect to database

### ISSUE THREAD

**Issue by jalles76** [keepassxreboot/keepassxc#6466]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

Connecting from Chrome plugin to KeePassXC fails with

"Cannot connect to KeePassXC. Check that browser integration is enabled in KeePassXC settings."

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Start KeePassXC
2. Start Chrome
3. Click Plugin Button

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Connection to unlocked KeePassXC database

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

"Cannot connect to KeePassXC. Check that browser integration is enabled in KeePassXC settings."

Clicking "Reload" yields "Key exchange was not successful."

## Context
[NOTE]: # ( Give us any additional information you may have. )

Browser integration is enabled.
No stored keys in "Browser Integration"

HKEY_CURRENT_USER\SOFTWARE\Google\Chrome\NativeMessagingHosts\org.keepassxc.keepassxc_browser
is set to C:/Users/jalles/AppData/Local/KeePassXC/org.keepassxc.keepassxc_browser_brave.json

Allowed origin extension ID matches Chrome extension.

I can't be sure but I suspect the proxy process isn't started (correctly). No endpoint security apart from Windows Defender running. Manually running keepassxc-proxy.exe with argument chrome-extension://oboonakemofpalcgghocfoadofidjkkk/ does not help.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.6.4
Revision: REVISION 34a78f0

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows
Google Chrome 90.0.4430.93
KeePassXC-Browser Version: 1.7.8.1

**Comment by droidmonkey** [comment]
Do you have the chrome checkbox checked out the brave checkbox?

**Comment by jalles76** [comment]
Chrome, Vivaldi and Brave are one checkbox (which is checked). The contents of the .json files for Chrome, Brave and Vivaldi are identical.
