### ISSUE TITLE
Virtual Hardware Keys

### ISSUE THREAD

**Issue by nkiki** [keepassxreboot/keepassxc#6467]
## Summary
「Virtual Hardware Keys can be used in AutoFill mode or for emergency recovery scenarios when the original Hardware key is lost.  」

## Examples
 
![image](https://user-images.githubusercontent.com/61766044/116772872-6dd4ce00-aa84-11eb-860d-4cf8be83340b.png)
![image](https://user-images.githubusercontent.com/61766044/116772875-73321880-aa84-11eb-84c5-de8b7d784dfc.png)

## Context
I had been used Strongbox for a while ,  I really like this **(Virtual Hardware Keys)** feature and think it might be best  we could had it on KeepassXC

**Comment by droidmonkey** [comment]
That is pretty much what a key file is. There is already a request for recovery options of yubikey by supplying the original seed value.

**Comment by grrrrraham** [comment]
Request re-opening this. Yes it's pretty much what a key file is. However there are a few key advantages:

— the virtual hardware key is dynamic based on the seed of the updated Keepass DB. So unlike a keyfile the virtual hardware key changes everytime the DB is updated
— the virtual hardware key is protected on a hardware device (Yubikey) and does not need to be stored anywhere else
— it allows the Keepass DB to be protected by Yubikey and provides flexibility in not requiring the Yubikey to be plugged in at all times on the device where the virtual hardware key is enabled.

**Comment by Damariobros** [comment]
In Strongbox, the virtual hardware key is kept in the Secure Enclave. You can't do that with a key file. You can't store a key file in the Secure Enclave, or the TPM, or the TITAN chip, or whatever other security chip your device has. And as mentioned before, it provides the same dynamic functionality as a YubiKey, something a key file also doesn't do.

I can see a number of uses for this. Recovery from a lost YubiKey, binding the vault to the device hardware, or use with autofill in iOS which doesn't let you use your hardware key.

I would like this feature as it would allow me to achieve device-bound passkeys that aren't on a YubiKey, a function which is virtually nonexistent outside of some corporate environments.
