### ISSUE TITLE
Feature Suggestion - Improved Security - Incognito Mode

### ISSUE THREAD

**Issue by 0xWhoa** [keepassxreboot/keepassxc#6472]
## Summary
Would be nice if the DB file wouldn't have any headers that identifies it as a KeePassXC DB file.
Perhaps a new "incognito" mode/configuration that hides everything the user is doing including disabling features such as "recent DB used" or other breadcrumbs the app may leave behind that would help an attacker find the KeePassXC DB file.

## Context
I personally like to hide my important files as different formats within a haystack of many other files.
This wouldn't work if an attacker can scan all files for signatures of KeePassXC DB file.
As well as this wouldn't work if the attacker can see the recently opened DBs (or when opening a DB the last used folder popup first).
I think an "incognito" mode/feature would be a good layer of security-by-obscurity on top of the main layer of encryption, and I'm sure some attackers will be fooled by it.

**Comment by droidmonkey** [comment]
There is no benefit to this, incognito mode is a myth and doesn't add protection.
