### ISSUE TITLE
KeepassXC doesn't start on MAC os 11.3 Bigsur

### ISSUE THREAD

**Issue by securigeek** [keepassxreboot/keepassxc#6474]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Installed the .dmg file 
2. Ran the application 
3. Error at startup 

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

## Context
[NOTE]: # WHenever I launch the application it says keepassxc not supported by your mac 

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.6.4.2
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS big sur 11.3

**Comment by droidmonkey** [comment]
Screenshot of error please

**Comment by securigeek** [comment]
Here it is:

**Comment by droidmonkey** [comment]
Screenshot did not attach, please do it directly on github

**Comment by maade7** [comment]
Same issue.
<img width="667" alt="Screen Shot 2021-05-03 at 12 44 32 PM" src="https://user-images.githubusercontent.com/23218239/116905795-76a4db80-ac0d-11eb-8b99-21c4c2b0255d.png">

**Comment by droidmonkey** [comment]
ping @phoerious

**Comment by phoerious** [comment]
We are seeing this every now and then, but there is no apparent reason for it.

**Comment by ricovandevin** [comment]
I can confirm the issue with KeePassXC 2.6.4 on macOS 11.3.1.

<img width="265" alt="Screenshot 2021-05-04 at 14 05 35" src="https://user-images.githubusercontent.com/5457818/117004284-2cdbf400-ace6-11eb-8055-8522faf38a3c.png">

KeePassXC 2.6.3 works ok.

**Comment by phoerious** [comment]
Is that an Intel or M1 Mac? For Intel, you need to download the amd64 build, for M1, the arm64 build.

**Comment by gerritgriebel** [comment]
I tried to install 2.6.6 (Intel on macOS 13.3.1) today and it failed with "KeePassXC.app is damaged and can't be opened. You should move it to the Trash." I recovered to previously installed 2.6.4. What is causing the problem?

**Comment by droidmonkey** [comment]
From the screenshot it appears the user was trying to run the application directly from the DMG. Did you drag/drop to the applications folder and then run the app?

**Comment by gerritgriebel** [comment]
I did drag and drop the app into /Applications and replaced 2.6.4 version

**Comment by michaelk83** [comment]
> From the screenshot it appears the user was trying to run the application directly from the DMG

The screenshot was from another user.

@gerritgriebel Make sure you downloaded the correct DMG. For Intel you need the x86_64 version. Same as [#6638](https://github.com/keepassxreboot/keepassxc/issues/6638#issuecomment-861925499).

@droidmonkey Maybe this should be added to the FAQ and Getting Started guide? This comes up a lot, it's too easy to mistake the arm version for an amd version (which doesn't exist), and the x86_64 version is way down the list while the arm version is at the top. Some users may not even see that there are two of them.

Maybe from next version, name them KeePassXC-[version]-**mac**-[platform].dmg, so they'd be listed together.  
Also would be nice to have links to the Linux versions (snap and ppa?) from the release page.

**Comment by phoerious** [comment]
On the website, the two versions are already rather distinguishable I would say. This is rather a problem of people who download directly from the GitHub releases page.

In the future, we are probably going to release one unified bundle for both platforms even if it means larger binaries.

**Comment by droidmonkey** [comment]
> > From the screenshot it appears the user was trying to run the application directly from the DMG
> 
> The screenshot was from another user.
> 
Fully aware. I was comparing that users experience to the new users experience.

**Comment by gerritgriebel** [comment]
2.6.6. worked today, download file was exactly the same as old ones in my ~/Download folder. I have no idea why I was getting "KeePassXC.app is damaged".
