### ISSUE TITLE
Export CSV does not include OTPs, extra fields, or attached files

### ISSUE THREAD

**Issue by catleeball** [keepassxreboot/keepassxc#6476]
## Overview

When exporting a keepass database to CSV, extra fields added to entries including OTP info is not included in the CSV file. Additional fields are present in HTML exports.

Neither export method seems to include files attached to entries.

## Steps to Reproduce

1. Create a database
2. Add additional string fields to entries
3. Add a time-based OTP to some entries
4. Attach files to some entries
5. Export database via KeepassXC to CSV and HTML
6. Note that the extra fields are missing from CSV and present in HTML exports.
7. Note that attached files are not exported in either case

## Expected Behavior

1. Exported CSV file will contain extra fields
2. Attached files can be exported (maybe optionally?)

## Actual Behavior

Extra fields are not present in exported CSVs. Attached files are not extracted in either database dump.

## Context

It's important for long-term interoperability for all data stored in kdbx files to be exported.

> KeePassXC: 2.6.2
> Revision: e9b9582
> Operating System: macOS

Thanks!

**Comment by droidmonkey** [comment]
Update to 2.6.4
