### ISSUE TITLE
FAQ - Security instructions slightly incorrect

### ISSUE THREAD

**Issue by JohnLGalt** [keepassxreboot/keepassxc#6478]
This is an easy fix, just wanted to point it out.  I suspect that this issue will be fixed and closed quickly ;D

## Overview
In https://keepassxc.org/docs/#faq-security-kdbx4 the instructions to migrate database to KBDX 4 in the first question's answer are slightly incorrect (or, rather, could be better written to be more correct).

## Steps to Reproduce
1. Go to https://keepassxc.org/docs/#faq-security-kdbx4
2. Read the first Q and the answer
3. Try to go to **Database / Database settings**, select **Encryption** 

## Expected Behavior
I expect to see it there directly upon opening **Database Settings**

## Actual Behavior
It's not there.  After opening **Database Settings**, you have to click on the **Security** entry on the _left nav bar_, then click on **Encryption Settings** _tab_ to accomplish the steps.

## Context
Uh, https://keepassxc.org/docs/#faq-security-kdbx4

Info about app (though technically irrelevant)
KeePassXC - Version 2.6.4
Revision: 34a78f0

Operating System: Windows/Linux/macOS (technically on the web)

**Comment by droidmonkey** [comment]
fixed it
