### ISSUE TITLE
FdoSecrets: support for multiple collections

### ISSUE THREAD

**Issue by michaelk83** [keepassxreboot/keepassxc#6483]
This is half bug half new feature.

According to the [Secret Service plugin readme](https://github.com/keepassxreboot/keepassxc/tree/develop/src/fdosecrets#architecture), only one collection per DB is currently supported:
> There is one and only one `FdoSecrets::Collection` per opened database tab

But the spec explicitly states that *multiple* collections should be supported. E.g. in [chapter 3: Collection and Items](https://specifications.freedesktop.org/secret-service/latest/ch03.html):
> Client applications with special needs can create a new collection by calling the [`CreateCollection()`](https://specifications.freedesktop.org/secret-service/latest/re01.html#org.freedesktop.Secret.Service.CreateCollection) method on the Service interface.

## Steps to Reproduce
1. After enabling Secret Service integration, Attempt to create a non-default collection with a DBus call to `org.freedesktop.Secret.Service.CreateCollection()`.
1. In the KPXC GUI, attempt to expose more than one group to Secret Service.
1. In the KPXC GUI, when exposing a group to Secret Service, attempt to set a custom alias for the corresponding collection.

## Expected Behavior
1. It should be possible to create multiple collections with distinct aliases via DBus. Each collection should be represented by a separate exposed group in the DB (new groups should be created as needed).
1. It should be possible to expose multiple separate groups. Each top-level exposed group should correspond to a separate Secret Service collection.
1. It should be possible to specify a custom alias for each collection (exposed group).

## Actual Behavior
Presumably:

1. The `CreateCollection()` DBus call fails to create custom collections.
1. No such option exists. Only one group can be exposed.
1. No such option exists. Only the "default" alias is supported.

## Context
This is a minor use case at the moment, but may become more important if we want to import databases from KWallet or especially from GNOME Keyring (allowing users to migrate to KPXC). For example, according to [gnome-keyring/issues/24](https://gitlab.gnome.org/GNOME/gnome-keyring/-/issues/24), GNOME Keyring creates at least an additional `login` collection besides the `default` one.

## Additional Info
KeePassXC version: 2.6.4, 2.7.0 (not actually tested)
Operating System: Linux

**Comment by Aetf** [comment]
KPXC implements full spec and already supports multiple collections: you can open multiple databases and each one will be exposed as one collection. That's the foundational design decision of the fdosecrets plugin in KPXC.

And your requested behaviors are already implemented:
- `CreateCollection` DBus call will create a new database correctly.
- `SetAlias` DBus call will create the desired alias.

In addition, the currently focused database tab will be the `default` collection. So there's no issue with GNOME Keyring because the `login` collection can be the `default` collection at the same time.

**Comment by michaelk83** [comment]
At least for the use case of import from KWallet or Gnome Keyring, I think it makes sense to have all the imported collections in the same DB, assuming they were a single DB in the origin. (Granted, such import isn't possible yet, so this is hypothetical.)

> That's the foundational design decision of the fdosecrets plugin in KPXC.

Can you explain why this decision was made? (Why a separate DB for each collection?) Thanks.

**Comment by Aetf** [comment]
In spec:
> A group of items together form a collection. A collection is similar in concept to the terms 'keyring' or 'wallet'.

So I think a collection maps naturally to a database.

> At least for the use case of import from KWallet or Gnome Keyring, I think it makes sense to have all the imported collections in the same DB, assuming they were a single DB in the origin. (Granted, such import isn't possible yet, so this is hypothetical.)

It's already possible to have all items in one DB. For example, if you manually import items from the Gnome Keyring `login` collection into a new KPXC database `login.kdbx` or an existing database, and keep that database the focused tab in KPXC, it will be available as the `default` collection as well as `login` (plus any other alias you set via DBus).

**Comment by michaelk83** [comment]
I honestly don't know the details of Gnome Keyring, so you may be right that the existing features are enough. But KWallet DBs have a more hierarchical structure. Looking at my own wallet, first, there's a folder for each application. Then within each folder, there is:
- A `Passwords` map, which can have multiple password key-value pairs. For example, Kopete has a separate password entry for each IM protocol that Kopete supports.
- A `Maps` collection, which can have multiple maps, and each map can have multiple key-value pairs. For example, Network Manager has a map for each connection UUID (at least, I *think* those are connections...).
- `Binary Data` and `Unknown` entries, which are not used in my case.

How would that be handled if imported?

I've always assumed that each such app folder would map to a collection, and then each key-value pair is an item. Hmm.. but on 2nd thought, the actual question is how would each app map its own data when migrated to FdoSecrtes? It's not something we can tell in advance.

I guess the best course of action would be to look at how `QtKeyChain` writes the same data to the KWallet backend vs to the Gnome Keyring backend. That can be considered the de-facto "standard" mapping for KDE, since KDE apps are supposed to be migrating to `QtKeyChain`.

Btw, if you want to try implementing such an import, I was thinking of using the DBus APIs in both cases. For Gnome Keyring, it's the same FdoSecrets API, so it can probably reuse at least some of the existing KPXC FdoSecrets code. The difference is that the current code is in server mode, and the import would need to be client mode. And it only needs the read calls. No need to write into Gnome Keyring.

For a KWallet import, I was thinking of using the KWallet Dbus API (also client mode and only the read calls). It can probably reuse some of the Gnome Keyring import code, after that is implemented. The logic would be mostly the same, just different call and item mappings.

**Comment by Aetf** [comment]
Usually applications will attach a `service: xxx` attribute when they store items using fdosecrets API. That's not the standard, but it's what `libsecret` and python `secretstorage` is doing.

And I feel importing KWallet doesn't make sense (at least for entries created automatically by applications).
The format is really free form and the app is free to use a different format than the one it's using in KWallet.

So the best idea is probably to let the application itself handle saving data into fdosecrets (i.e. simply remove KWallet and enable fdosecrets and reenter passwords in app) rather than trying to do guesswork.

And for apps that don't support fdosecrets, there's no need to import in the first place.

Anyway, I have no intention to implement such import and I believe there's no need to have such functionality in KPXC, either. It can be easily implemented using some scripts.

**Comment by michaelk83** [comment]
If the KWallet import follows the `QtKeyChain` mapping, then I think it should work. KDE apps are supposed to be migrating to `QtKeyChain`, not to FdoSecrets directly. If a user has a lot of passwords, re-entering them manually is a drag, so an automated import would make sense if it works.

But anyway, I like the external scripts idea.
