### ISSUE TITLE
Autotype is not working

### ISSUE THREAD

**Issue by theking2** [keepassxreboot/keepassxc#6485]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

## Steps to Reproduce

1. Create an entry with logon name and password
2. Open an application or website logon screen
3. Richt click the entry and select Auto type (in my German installation this is called "Führe Auto-Type-Sequenz aus"

## Expected Behavior
Username and Password are typed in the desginated fields

## Actual Behavior
Nothing

## Context
Happens on all entries)

KeePassXC - 2.6.4
Revision: 34a78f0

[NOTE]: # ( Pick choices based on your environment )
Operating System: Fedora 34
Desktop Env: Gnome 4
Windowing System: X11/Wayland

**Comment by droidmonkey** [comment]
You are running on Wayland which does not support Auto-Type. Your browser is likely using Wayland and keepassxc is running under X11 through xwayland
