### ISSUE TITLE
package for keepassxc-cli

### ISSUE THREAD

**Issue by tessus** [keepassxreboot/keepassxc#6486]
## Summary
When running a headless server, all the GUI related code and dependencies are really not wanted.

In such a case only the binary `keepassxc-cli` is needed and its libraries. I do not care about qt5 or X or anything else for that matter.

Is there any chance you could provide a separate rpm package for the cli version? If not, what about a static binary that I can just copy to the server?

**Comment by droidmonkey** [comment]
The is being worked on already, we are extracting all gui code / dependencies for 2.7.0 so the cli can be built and deployed without it.

**Comment by tessus** [comment]
Awesome. This is great news. Thanks for the info and sorry for the noise.

**Comment by tessus** [comment]
ok, so 2.7.1 is out, but I can't find any cli package or did I miss it? @droidmonkey 

The only package I can find is:

```
Installing:
 keepassxc
Installing dependencies:
 botan2
 glx-utils
 libevdev
 libinput
 libwacom
 libwacom-data
 libxkbcommon-x11
 minizip
 mtdev
 pcre2-utf16
 qt-settings
 qt5-qtbase
 qt5-qtbase-common
 qt5-qtbase-gui
 qt5-qtsvg
 qt5-qtx11extras
 xcb-util
 xcb-util-image
 xcb-util-keysyms
 xcb-util-renderutil
 xcb-util-wm
```

P.S.: Also, can you please reference the issue for which this is a duplicate?

**Comment by droidmonkey** [comment]
We don't distribute packages, file a request with your distro manager for a cli only build. You still need to have qt5 dependencies though.

@Germano0 is the rpm packaging wizard.

**Comment by tessus** [comment]
I was asking because I didn't see any information on how to build the cli application without having the dependencies I mentioned in my first comment. I don't need a package. I only need a way to build the cli without being linked to GUI libs.

I checked the BUILD information, the wiki, and `CMakeLists.txt`. There is no option to build the cli.

When I build it as described (basically the entire app which includes the cli), the resulting cli is still linked with qt5 and xcb libraries.

So, getting back to your comment:

> so the cli can be built and deployed without it.

How can I build it without the GUI?

**Comment by droidmonkey** [comment]
You should just be able to do `make keepassxc-cli`

qt libs are a requirement regardless of cli only or not. You just don't need qt5-gui

**Comment by Germano0** [comment]
I already talked to developers about creating a CLI only package. The outcome of the discussion was that we could not get rid of all graphic libraries, and moreover trying to do such changes on the spec file requires a lot of time and tests and I don't have time at the moment, and I don't plan to do it in the future.

**Comment by tessus** [comment]
@Germano0 No worries. I can build the binary myself. I just thought there was a package available. All good.

@droidmonkey I am sorry to drag this out and please forgive my ignorance. I thought that QT5 and xcb (client side X11) are specifically for GUI applications. Afaik qt5 is not a wrapper for ncurses, nor is even ncurses used in the cli app. So I don't understand why the cli application requires these libraries.
You said in your previous comment that you are extracting all GUI code. So why is qt5 needed? If you told me that you didn't extract all the GUI code, this would be fine too. At least then it makes sense and I'd understand what is going on.
Although in this case I'd hope that you still extract the rest of the GUI code at one point in the future. I hope you understand my point of view as well. I ran ltrace on the `keepassxc-cli` and none of these libraries are actually loaded. They only seem to be linked.

**Comment by droidmonkey** [comment]
Qt5 is a framework. It has a gui portion, but it is FAR more than that.
