### ISSUE TITLE
keepassxc-cli doesn't handle --help and --version options correctly

### ISSUE THREAD

**Issue by sainaen** [keepassxreboot/keepassxc#649]
It's of course less problematic for the `--help`, because help message will be displayed when a command is not recognized anyway.

There's also an issue with the app name in the help message: because `argv` and `argc` are [modified](https://github.com/keepassxreboot/keepassxc/blob/a53b111182a427824dcd7721bbecbe43b7bb676f/src/cli/keepassxc-cli.cpp#L81) before `commandName` is [checked](https://github.com/keepassxreboot/keepassxc/blob/a53b111182a427824dcd7721bbecbe43b7bb676f/src/cli/keepassxc-cli.cpp#L86), a `QCoreApplication` [gets](https://github.com/keepassxreboot/keepassxc/blob/a53b111182a427824dcd7721bbecbe43b7bb676f/src/cli/keepassxc-cli.cpp#L106), for example, `--help` as a first element in `argv` where a name of executable would normally be.

## Expected Behavior
When option `-v`/`--version` is passed keepassxc-cli should print out its version.

## Current Behavior
It prints out `Invalid command -v.` and a help message that has wrong executable name in the 'Usage' line:

```
$ ./keepassxc-cli --version
Invalid command --version.
Usage: --version [options] command
KeePassXC command line interface.
...
```

## Steps to Reproduce
1. Run `keepassxc-cli --version` or, for example, `keepassxc-cli -h`

## Your Environment
* KeePassXC version used: commit f817eaa
* Qt version: 5.7.1
* Compiler: gcc 6.3.0 (though I'm not sure I checked this correctly)
* Operating System and version: Debian Testing/Sid 4.9.0-3-amd64

**Comment by sainaen** [comment]
Also discovered that even if invalid command provided, exit code is still 0, because it is set by `parser.showHelp()` (it has `exitCode` arg with default value 0, [docs](http://doc.qt.io/qt-5/qcommandlineparser.html#showHelp)) and not by return from the `main()`:
```
❱ ./keepassxc-cli wrong-command > /dev/null ; echo "Exit code: $?"
Invalid command wrong-command.
Exit code: 0
```

Should I create a separate issue? It seems almost too trivial.

**Comment by louib** [comment]
@sainaen no need for a seperate issue, I'll fix it in the same PR. Thanks for the bug report btw!
