### ISSUE TITLE
Writing the database failed: Could not save, database has not been initialized!

### ISSUE THREAD

**Issue by andrei-belkin** [keepassxreboot/keepassxc#6492]
Hello,

I synced my database from KeePassDX (Android) to KeePassXC (Linux) and I can't save it in KeePassXC. I wanted to create a new entry, but when I try to save the database, I constantly get the error "Writing the database failed: Could not save, database has not been initialized!".

Database format: KDBX 3.1
Error message: "Writing the database failed: Could not save, database has not been initialized!"

Everything works fine on Android, in KeePassDX.

If anyone could please provide with some documentation, support or advice, I'd be very thankful.

If some other information about the database is required, I'll be happy to provide.

Thank you.
Andrei.

**Comment by droidmonkey** [comment]
That error means you don't have any credentials associated with your database. That is a very internal error and I'm surprised you can open it at all.

**Comment by andrei-belkin** [comment]
> That error means you don't have any credentials associated with your database. That is a very internal error and I'm surprised you can open it at all.
> 
> Try migrating it to kdbx 4 and then saving.

@droidmonkey 

Thank you, it worked =) Actually, I simply set a password on the DB and everything went back to normal. I also switched to the KDBX 4 format, just in case.

Strange, I used this same DB without credentials (username or password) in KeePassXC before and it worked perfectly. But okay =)

Thanks!
Andrei.

**Comment by droidmonkey** [comment]
Great!

**Comment by aubreyz** [comment]
I had the same issue here and for the same reason - I created a test database in Keepass DX without a password. It opened perfectly well in DX and XC but would not save in XC -- with this error. If this is the only reason (or most likely reason) for this error, I think it would be worth adding a few words to the error message to point that out as a possible cause. 

I can see some circumstances folk might be creating a password free database (or working on one from elsewhere), like preparing templates and it is worth saving them some time having to puzzle over it for hours.
