### ISSUE TITLE
Database locks on screen blank rather than screen lock on Linux/Gnome

### ISSUE THREAD

**Issue by feeblor** [keepassxreboot/keepassxc#6493]
## Overview

The settings imply the database will lock when the screen locks, but it actually locks when the screen blanks, which is not the same thing.  (Ubuntu 20.04/Gnome Linux)

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Activate setting "Lock databases when session is locked or lid is closed" under Security,
2. In Gnome settings, under Privacy > Screen Lock, set a value for "Blank Screen Delay", activate "Automatic Screen Lock", and set a value for "Automatic Screen Lock Delay", so the session will lock several minutes *after* the screen blanks.
3. Unlock the password database, then allow the screen to blank, but not lock.

## Expected Behavior

The database should not lock.

## Actual Behavior

The database locks.

## Context

I understand it would be a security risk to change existing behaviour to make it less secure, but it would be nice to have a settings option to respect actual screen lock rather than just screen blank.  My database locks waaaay too much!  Maybe this should be a feature request, but it does seem like a bug that locking is triggered screen blank rather than lock, even if that bug can't be fixed now for security reasons. Let me know if I should open a feature request instead. Thanks.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.4.3
Revision: 5d6ef0c

Qt 5.12.8
Debugging mode is disabled.

Operating system: Ubuntu 20.04.2 LTS
CPU architecture: x86_64
Kernel: linux 5.4.0-72-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (only unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.5

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: Gnome
Windowing System: X11

**Comment by droidmonkey** [comment]
You are using a very old version of keepassxc. Also we listen for specific signals from the desktop env and if it is sending a lock signal on screen off then there is nothing we can do about that.

**Comment by feeblor** [comment]
Thanks.  I did some checking on my system with dbus-monitor and found that the lock signal wasn't even being emitted properly, possibly related to this issue:

https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/741

So I doubt this is fixable on your end, at least for my system, given the current state of dbus signals.  Cheers.

**Comment by droidmonkey** [comment]
For reference this is the file that drives what dbus signals we listen for: https://www.github.com/keepassxreboot/keepassxc/tree/develop/src%2Fgui%2Fosutils%2Fnixutils%2FScreenLockListenerDBus.cpp

**Comment by michaelk83** [comment]
And speaking of DBus, if you're somewhat techy, you can write a script to lock KPXC on any custom condition, using its own [DBus interface](https://github.com/keepassxreboot/keepassxc/wiki/Using-DBus-with-KeePassXC):
```
qdbus org.keepassxc.KeePassXC.MainWindow /keepassxc org.keepassxc.KeePassXC.MainWindow.lockAllDatabases
```

**Comment by xyxyxoxo** [comment]
I can confirm this. Also on Ubuntu 20.04 LTS. Under the same scenario, the _LockedHint_ property is being set by GNOME even when screen is just being blanked. And the _locked_ signal doesn't even fire in DBus (although the _unlocked_ signal does).

So this is a GNOME problem.

https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/741
https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/351
