### ISSUE TITLE
Spaces after comma and period do not render properly in text fields

### ISSUE THREAD

**Issue by NReilingh** [keepassxreboot/keepassxc#6494]
## Overview

Non-fixed-width text fields do not properly render comma-space or period-space combinations. The space appears to have a width of one pixel, and when seeking back and forth across the combination with the arrow keys, the insertion point moves as though the one-pixel space appears _before_ the punctuation.

![Screen Capture demonstrating the issue in the notes field of an item](https://user-images.githubusercontent.com/2458645/117239784-6a7f7080-adfd-11eb-87b5-d9a67f4a0c87.gif)

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Put the insertion point in any non-fixed-width text field (anything except a password field in my testing, i.e. the title, username, or notes field of an item, or the search bar
2. Type a period or comma followed by a space
3. Observe character render and selection widths by using the arrow keys and shift-arrow keys to navigate across the two characters and select them individually.

I'm inventing these following terms because I am not a typographer:
* Character render width: When adding a character _a_ in front of (to the left of) an existing character _b_, the number of pixels that the rendered position of character b will shift by is the render width of character _a_.
* Character selection width: the number of pixels that a character advances the insertion point by, or the width of the selection highlight for that character.

Users expect character render width and character selection width to be basically the same, or to have similar qualities, even when ligatures are being used.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
The punctuation character retains the selection width it had before the space was added, and the space character's render and selection width both begin after the punctuation character's render width.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
The space character's render and selection width appear to completely overlap the punctuation character's, and the selection width of the punctuation character is now approximately one pixel (the selection highlight for the punctuation character is zero pixels wide).

## Context

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.4
Revision: b93fbd1

Qt 5.15.2
Debugging mode is disabled.

Operating system: macOS 11.2
CPU architecture: arm64
Kernel: darwin 20.3.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (only unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
- libgcrypt 1.9.1

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS 11.2.3
MacBook Air (M1, 2020) and Mac mini (2018)
Reproduced on both Retina and non-Retina displays
en-US localization
KeePassXC installed via homebrew cask

**Comment by NReilingh** [comment]
Rendering behavior also appears to affect text in informational dialog boxes.

**Comment by droidmonkey** [comment]
We don't do anything with font rendering so it's either your font or Qt.

**Comment by droidmonkey** [comment]
@phoerious maybe time to pick a new default font on mac?

**Comment by felker** [comment]
Has this been reported in Qt?

**Comment by NReilingh** [comment]
@felker Would love to follow it if so, but I'm not readily able to isolate this kind of behavior at the framework level. If anyone does, I would hope they would track any updates they can share on this issue.

I managed to find the Qt bugtracker and found a few possibly relevant issues:

https://bugreports.qt.io/browse/QTBUG-88495?jql=project%20%3D%20QTBUG%20AND%20component%20%3D%20%22GUI%3A%20Text%20handling%22%20AND%20text%20~%20%22comma%22

One in particular is marked as being specific to Big Sur, affecting Qt 5.15.1, fixed in 5.15.3. I'm not sure what is used by KeePassXC, but I'm suspicious of the issue being limited just to Big Sur.

This post may also be helpful: https://codereview.qt-project.org/c/qt/qtbase/+/322102

**Comment by felker** [comment]
Text rendering seems improved for me on macOS with the 2.7.3 release. Anyone else?

**Comment by droidmonkey** [comment]
#randomness ....

**Comment by NReilingh** [comment]
@felker Yes, I think you're right.
