### ISSUE TITLE
Sort function should place recycling bin at the very bottom of the list

### ISSUE THREAD

**Issue by tgucci** [keepassxreboot/keepassxc#6495]
## Summary
[TIP]:  # Sort function should place recycling bin at the very bottom of the list
[NOTE]: # ( Provide a brief overview of what the new feature is all about )

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )

**Comment by markalston** [comment]
Agreed.  The search function is semi useless when the results are mostly filled with backup entries.

**Comment by t214c** [comment]
In v 2.7.11 it is not shown at the very bottom. Group beginning with T is below it when selecting sort A-Z.
