### ISSUE TITLE
Support central secret-manager such as Openstack Barbican or Hashicorp VAULT.

### ISSUE THREAD

**Issue by ArKam** [keepassxreboot/keepassxc#6496]
## Summary
Option for KeepassXC client to generate synced local KBDX database from a central secret manager such as Openstack Barbican or Hashicorp VAULT.

## Examples
1°/ - Additionally to local KBDX location, the KPXC client allow user to point out to a remote central secret-manager endpoint URL.

2°/ - KPXC client verify if any local KBDX already reference the remote endpoint.
2.1°/ - If existing references are found, KPXC ask for what to do (overwrite or abandon).
2.2°/ - If no existing references are found, KPXC create a new special KBDX database locally that will support remote/shared synced password.

3°/ - When a user add a new secret, he can type it as local/personal unsynced, by default the new secret is remote/shared synced type.
4°/ - For offline support, secrets should be synced locally and resynced (with conflict management) each time KPXC client get access to the endpoint.

Of course this is just a basic workflow that I'm sure others could improve.

## Context
When you're part of a team, you've got both, personal and shared secrets to manage.
Currently, if you want your team to be able to use shared secret, you've to use your central secret manager or publish you "central kbdx" somewhere, however, with time passing by, people start having drift between the central file and their own local copy of it.
It would be nice to get a new kind of database that would gain ability to manage both, local/personal unsynced secret AND remote/shared synced secrets.

**Comment by droidmonkey** [comment]
We won't be implementing this.
