### ISSUE TITLE
Chase.com Fill Credentials Error 

### ISSUE THREAD

**Issue by Jimmy-Py** [keepassxreboot/keepassxc#6505]
When I visit chase.com and click the little KeePassXC icon (from the firefox extension) that appears in the username field, it does not work. I have the credentials for chase.com stored in my database, associated with the URL. All my other accounts on other websites function fine. Any tips?

**Comment by JohnLGalt** [comment]
Did you try using the "Redect login fields" to manually select the fields and see if it then populates?

**Comment by droidmonkey** [comment]
Chase has purposefully broken their site for copy/paste and password managers. This isn't anything we can fix readily.

**Comment by Jimmy-Py** [comment]
> Chase has purposefully broken their site for copy/paste and password managers. This isn't anything we can fix readily. You will have to use Auto-Type for this site.

Amazing. Any idea how they think that makes their clients safer? Also, I'm able to past in my password after copying it from KeePass, just not by clicking browser extension button.
