### ISSUE TITLE
KeePassXC can't remeber last Database

### ISSUE THREAD

**Issue by framedr0p** [keepassxreboot/keepassxc#6506]
## Overview
For some reason my KeePassXC installation doesn't remember the last opend Database after reboot. If i close the application wihtout rebooting the last opend database is loaded after startign KeePassXC. The option `OpenPreviousDatabasesOnStartup=true` and `RememberLastDatabases=true` is set in the keepassxc.ini and i can see the checked checkbox "Remeber last databases" and "Load previous databases on startup" in my settings.

### General section of my keepassxc.ini
`[General]`
`AutoReloadOnChange=true`
`AutoSaveAfterEveryChange=true`
`AutoSaveOnExit=true`
`AutoTypeDelay=25`
`AutoTypeEntryTitleMatch=true`
`AutoTypeEntryURLMatch=true`
`AutoTypeStartDelay=500`
`BackupBeforeSave=false`
`ConfigVersion=1`
`DropToBackgroundOnCopy=false`
`FaviconDownloadTimeout=10`
`GlobalAutoTypeKey=0`
`GlobalAutoTypeModifiers=0`
`HideWindowOnCopy=false`
`MinimizeAfterUnlock=false`
`MinimizeOnCopy=true`
`MinimizeOnOpenUrl=false`
`OpenPreviousDatabasesOnStartup=true`
`RememberLastDatabases=true`
`RememberLastKeyFiles=false`
`SingleInstance=true`
`UpdateCheckMessageShown=true`
`UseAtomicSaves=false`
`UseGroupIconOnEntryCreation=true`

### Context
KeePassXC - Version 2.6.4
Revision: 34a78f0

Qt 5.15.2
Debugging mode is disabled.

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 5.12.1-zen2-1-zen

Enabled extensions:
Auto-Type
Browser Integration
SSH Agent
KeeShare (signed and unsigned sharing)
YubiKey
Secret Service Integration
Cryptographic libraries:

libgcrypt 1.9.3-unknown

Operating System: Linux
Desktop Env: Xfce 4.16
Windowing System: X11
WM: Xfwm4

**Comment by droidmonkey** [comment]
You most likely have your ~/.cache directory mounted as a RAM disk. You either need to do one of the following: 
1. Open KPXC with command line switch `--localconfig <localconfig>`
2. Set environment variable `KPXC_CONFIG_LOCAL` to the path you want to use
3. Stop using ram disk for .cache
