### ISSUE TITLE
Increase security: If entry doesn't have a username ask if that is fine before Auto-Type

### ISSUE THREAD

**Issue by GuybrushX** [keepassxreboot/keepassxc#6508]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
I created a new entry without a username (new account on a website). I forgot to enter the username or sometimes you choose the username later or you really don't need a username. After activating the account I tried to log in -> the website asked for username + password. I used Auto-Type via a shortcut and it typed in the password as my username. VERY BAD! The browser has saved the password as my username now and the password also appears in the website in plaintext probably.

So I would ask to add a confirmation dialog which is asking if this is what I really want with an option like "Don't ask again for this entry". So if the username is missing I can't accidentally Auto-Type the password as the username and only the first time I need to confirm or fix it.

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )
Please see above.

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
Mainly security! And to avoid human errors like the one I mentioned above.

**Comment by droidmonkey** [comment]
This was already done on the develop branch. A dialog confirms you want to perform Auto-Type.
