### ISSUE TITLE
KeePassXC does not read password from clipboard after locked out of inactivity

### ISSUE THREAD

**Issue by Dyrimon** [keepassxreboot/keepassxc#6510]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
KeePassXC fails to read anything from clipboard after it locks out of inactivity. Closing the application and reopening fixes it temporarily. The issue reappears after timeout. Manually typing the password in the input box works.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Open KeePassXC and select database to open
2. Enter database password and open it
3. Wait for the application to be locked out after designated timeout (in my case it was 600 sec)
4. Copy the database password from text file/password manager and paste in the input box
5. KeePassXC will not take any input and all options from the right-click context menu are greyed out. As it seems KeePassXC does not think anything is in the clipboard
6. Close the application and reopen it.
7. Follow step 4, this time it will work
8. Wait for timeout again and repeat step 4, it will fail again

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
KeePassXC should take password from clipboard even after it is locked.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
KeePassXC does not take password if locked out after inactivity.

## Context
[NOTE]: # ( Give us any additional information you may have. )
KeePassXC is installed from the official Fedora repository. This issue is also reproducible in the AppImage. Initially I've thought the KDE clipboard manager `klipper` is doing this, but disabling `klipper` has no effect. The copied password can be pasted anywhere except KeePassXC, so I do not think it's a system issue.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.4
Revision: 34a78f0

[NOTE]: # ( Pick choices based on your environment )
Qt 5.15.2
Debugging mode is disabled.

Operating system: Fedora 34
CPU architecture: x86_64
Kernel: linux 5.11.18-300.fc34.x86_64
Desktop Environment: KDE Plasma
Windowing System: Wayland

**Comment by droidmonkey** [comment]
It's probably a qt issue

**Comment by Dyrimon** [comment]
Update: I've just tested this with Plasma X11, and the issue is not present there. So it's definitely a Wayland issue.

**Comment by JohnLGalt** [comment]
Odd.  Because I ran into it today on Windows 10 as well.  Entry was there, it had asked me in the past to make sure it was usable, but 0 interaction with the website.  Closed it out and re-opened and all of a sudden it's ready to enter fields.

This was immediately after unlocking the machine after being away for a bit of time (it doesn't actually go to sleep / hibernate, just locks the desktop, requiring my PW / PIN to unlock, and I Have CTRL ALT DEL (secure desktop) enabled as well.

@droidmonkey - should I make a separate issue for this seeing as I am on Windows?

**Comment by droidmonkey** [comment]
You are referring to something completely different.

**Comment by wcasanova** [comment]
Same problem with Plasma and Wayland, for the moment it is enough to edit the desktop file 
`QT_QPA_PLATFORM=xcb keepassxc %f`

**Comment by droidmonkey** [comment]
Closing this since all Wayland specific issues are related to qwayland platform. File the bug with Qt at https://bugreports.qt.io

**Comment by Dyrimon** [comment]
> Same problem with Plasma and Wayland, for the moment it is enough to edit the desktop file `QT_QPA_PLATFORM=xcb keepassxc %f`

Hi, sorry to bother, but I didn't understand what desktop file you're talking about. To which file should I add this line? Thanks.

**Comment by Dyrimon** [comment]
@droidmonkey It seems [someone has reported this issue to Qt](https://bugreports.qt.io/browse/QTBUG-102755) but the developers of the Qt project needs more feedback from the [KeePassXC devlopers themselves](https://bugreports.qt.io/browse/QTBUG-102755?focusedCommentId=659574&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-659574).

**Comment by droidmonkey** [comment]
Not going to comment, we have nothing to say on the matter.
