### ISSUE TITLE
keepassxc-cli fails on apple silicon

### ISSUE THREAD

**Issue by pasloc** [keepassxreboot/keepassxc#6515]
## Overview
keepassxc-cli always crashes on big sur and apple silicon with message:

> dyld: Library not loaded: /opt/homebrew/opt/libgpg-error/lib/libgpg-error.0.dylib
>   Referenced from: /opt/homebrew/bin/keepassxc-cli
>   Reason: no suitable image found.  Did find:
> 	/opt/homebrew/opt/libgpg-error/lib/libgpg-error.0.dylib: code signature in (/opt/homebrew/opt/libgpg-error/lib/libgpg-error.0.dylib) not valid for use in process using Library Validation: mapped file has no Team ID and is not a platform binary (signed with custom identity or adhoc?)
> 	/opt/homebrew/opt/libgpg-error/lib/libgpg-error.0.dylib: stat() failed with errno=1

## Steps to Reproduce
1. Install KeepassXC via homebrew
2. launch keepass-cli in terminal

## Expected Behavior
It shouldn't crash.

## Actual Behavior
It's crashing

KeePassXC - 2.6.4
Revision: 34a78f0

Operating System: macOS

**Comment by droidmonkey** [comment]
Wait a minute, we don't deploy the cli as a stand alone executable. It should be loaded from the KeePassXC.app installed by the dmg. How did you install that cli program?

**Comment by pasloc** [comment]
I installed KeepassXC via homebrew. This morning I removed the homebrew version and replaced it with the DMG download from the webpage. The cli tool works now, but it didn't work when it was installed via homebrew.

**Comment by stonerl** [comment]
The homebrew formula soft links the cli binary:

```
keepassxc-cli -> /Applications/KeePassXC.app/Contents/MacOS/keepassxc-cli
```

**Comment by stonerl** [comment]
@pasloc BTW which dmg did you Download? **KeePassXC-2.6.4-2-arm64.dmg** or **KeePassXC-2.6.4-arm64.dmg** homebrew install from the first one.

@droidmonkey why are there two arm64 packages?

**Comment by droidmonkey** [comment]
This bug report needs to be filed with brew. 

There should only be the -2 package, I think the first one is broken. @phoerious
