### ISSUE TITLE
Keepassxc can't Auto-Type password in QQ

### ISSUE THREAD

**Issue by Maasea** [keepassxreboot/keepassxc#6516]
## Overview
When I use Keepassxc to auto fill QQ, the username is working well, but password can not auto fill.
I use {CLEARFIELD}{USERNAME}{TAB}{PASSWORD}{ENTER}.
Another applications are working well.
I try Keepass to fill QQ, It works. 

## Steps to Reproduce
1. I use Shortcut Keys to fill
2. username fill well and auto tap to password Column
3. password can't fill 

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.6.4
Revision: 34a78f0

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 10 20H2

**Comment by droidmonkey** [comment]
Try using our snapshot https://snapshot.keepassxc.org we made several major changes to Auto-Type.

**Comment by Maasea** [comment]
> Try using our snapshot https://snapshot.keepassxc.org we made several major changes to Auto-Type.
> 
> Note to self: QQ is Tencent instant messenger

I try the latest version in snapshot, and It still can't auto-type password.
For another things, can browser extension match simple domain, for example, password for account.google.com also can use to www.google.com.

**Comment by droidmonkey** [comment]
No, we don't match across or up subdomains, set the url to google.com to match all subdomains.

**Comment by andeaker** [comment]
Yes, I also encountered this problem.  
It seems that the QQ login interface is caused by the nesting of two different programs. 

 It would be great if this problem can be solved!

**Comment by droidmonkey** [comment]
We won't be doing anything about this issue, please raise the problem to QQ developers or determine the key sequence needed to switch between the username and password fields.
