### ISSUE TITLE
Copying sensitive text doesn’t set clipboard history hints in all situations

### ISSUE THREAD

**Issue by da2x** [keepassxreboot/keepassxc#6518]
## Overview
KeePassXC fails to warn clipboard managers and cloud sync to exclude copied data depending on the method used to copy it from KeePassXC.

## Steps to Reproduce
1. Create an entry in a KeePassXC database.
2. Select it in the UI.
3. Right-click on it and choose copy username.
4. Paste it into [Clipboard Viewer.app](https://langui.net/clipboard-viewer/) and confirm presence of `org.nspasteboard.ConcealedType`.
5. In KeePassXC, double click on the username (in the preview panel) to select it, and press Command–C (or-right click the selection and copy).
6. Repeat step 4.
7. Back in KeePassXC, edit the entry, click to focus the username field, and press Command–A and then Command–C (or-right click the selection and copy).
8. Repeat step 4.

## Expected Behavior
Step four should pass regardless of the method used to copy data from KeePassXC.

## Actual Behavior
It only passes in the first instance.

## Context
The behavior might possibly be the same on Linux with `x-kde-passwordManagerHint` missing there and `ExcludeClipboardContentFromMonitorProcessing` missing on Windows 10.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.6.4
Revision: 34a78f0

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS

**Comment by droidmonkey** [comment]
The second behavior is out of our control, that is standard os handling of text data

**Comment by da2x** [comment]
AFAIU, macOS apps can take control over this through https://developer.apple.com/documentation/appkit/nspasteboardwriting

**Comment by droidmonkey** [comment]
That is not what I am referring to. The right click context menu that shows copy/paste/select all/etc is generated outside of keepasxc. In order to intercept the copy action on that menu we would essentially have to reimplement it for each text input field. We are not going to do that.

**Comment by droidmonkey** [comment]
This is not an issue we will correct.

**Comment by Chealer** [comment]
This persists in 2.7.11.

@da2x:
Does this affect anything other than usernames?
Step #4 is confusing. I recommend splitting it in 2 steps:
4. Paste it into [Clipboard Viewer](https://langui.net/clipboard-viewer/) 
5. Inspect whether `org.nspasteboard.ConcealedType` is present.

<details>
  <summary>License</summary>
This comment and any other from myself on this ticket is offered under the terms of CC0 1.0.
</details>
