### ISSUE TITLE
Support for .ovpn, .key, .crt files on disk

### ISSUE THREAD

**Issue by bitshiftnetau** [keepassxreboot/keepassxc#6521]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
It would be great if keepassxc could store .ovpn files, pub/priv certificates, and pub/priv keys without the need to use the notes section and then recopy out the certificate to a file. 

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )
Perhaps we would attach the files or directories holding these sensitive files, and it would somehow encrypt them along with the database. I'm not sure what this would look like or where to even begin. Compressing the files down and perhaps storing the resulting data into the value store?

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
It's vital really. Surprised no-one has raised this before, which must indicate a better solution exists and I simply haven't learned it yet. Sure there is the ssh key agent and that's a really great addition, but it doesn't have features for mutual authentication and we are also using other types of sensitive files that grant access. Yes, we have extra layers of security there i.e. IAM federated access, but things like client certs/keys and .ovpn files just sit in my root atm and I'm looking at options for manually en/decrypting... super boring.

**Comment by droidmonkey** [comment]
Attachments are on the advanced tab

**Comment by bitshiftnetau** [comment]
Thanks @droidmonkey but that's not what I mean. If I delete the files on the disk, it will delete the data from the attachment. I mean something like VeraCrypt which can encrypt folders and files along with my passwords etc. 

Maybe I'll just use VeraCrypt for now but it would be great if this kind of feature were added to keepassxc. Thanks again!

**Comment by droidmonkey** [comment]
That's not true at all. Attachments are stored in the database along with everything else.

**Comment by bitshiftnetau** [comment]
Then how come when I delete the file from the folder after just adding as an attachment, does the data inside the database version of the file disappear?

**Comment by bitshiftnetau** [comment]
Yep, apologies I was doing it wrong. Thanks again.

**Comment by droidmonkey** [comment]
Did you save your database? There is no linkage to the file at all once attached.

**Comment by droidmonkey** [comment]
There is no linkage to the file at all once attached. You could have a corrupt database from another program, we've seen issues with attachments in the past.

**Comment by bitshiftnetau** [comment]
No luckily I was just a big dumb idiot that opened the already attached
file inside the database, added text, then assumed that was saved to the
file on disk. It was not.

I see how it works now, this is awesome!
