### ISSUE TITLE
Allows changes to write protected database, discards changes silently on exit

### ISSUE THREAD

**Issue by Sprinterfreak** [keepassxreboot/keepassxc#6522]
KeePassXC 2.4.3 from Ubuntu repositories silently discards data.
This results in dataloss and locked out accounts.

Steps to reproduce:
1. Open a database file from gvfs mounted samba share on Ubuntu 20.04
    KeePassXC opens the database as [write protected] (I think because of #4856)
2. Change/Add some items (passwords)
3. Close KeePassXC - just exits immediately
4. Open database in KeePassXC again and see Your changes had not been saved.

## Expected Behavior
KeePassXC must either not allow any changes to as [write protected] opened database or at least throw a warning if changes have been made, to "save as" before app exit.

## Actual Behavior
All changes done to the database are silently discarded on KeePassXC exit.

**Comment by droidmonkey** [comment]
We got rid of "read only" mode in later versions.
