### ISSUE TITLE
Edit multiple entries at once, like KeePass' "Edit Entry (Quick)" menu

### ISSUE THREAD

**Issue by PrSunflower** [keepassxreboot/keepassxc#6527]
_Notice: Hi! I searched for duplicates but I didn't find any. If there are please tell me and I will close this issue 🙂_

## Summary

I wanted to change the icon of multiple entries at once but I couldn't find a way to do it in KeePassXC.

## Examples

I was able to do it with KeePass:

![Screenshot 2021-05-15 220950](https://user-images.githubusercontent.com/59576952/118374200-d9ae4f00-b5cb-11eb-92d5-2d942a488d6f.png)

The icon of my selected entries was changed:

![Screenshot 2021-05-15 221038](https://user-images.githubusercontent.com/59576952/118374210-ea5ec500-b5cb-11eb-9fff-5c4d7608ff6e.png)

## Context

I think it is a very useful feature and as the original KeePass supports it I would appreciate it if it could be implemented in KeePassXC 🙂

## 💚 you!

I'm always amazed to see how far the free/open-source community can go when they're determined. Thank you to all devs and collaborators for this wonderful port 😊

**Comment by droidmonkey** [comment]
Hi, you're very welcome, we love this stuff! This is a duplicate request. You can set the icons of an entire group of entries by editing the group and setting the icon while choosing "Apply to all children".

**Comment by PrSunflower** [comment]
Thank you for your reply! Alright then thanks for telling me about the duplicate.

Ok thanks for the tip, I didn't want to look how to do that either because I wanted 6 entries to keep their respective icons.

**Comment by droidmonkey** [comment]
Just make a new group, dump the entries in there, set icon, move them back
