### ISSUE TITLE
"Integrated" SSH Confirmation Dialog

### ISSUE THREAD

**Issue by ModProg** [keepassxreboot/keepassxc#6528]
## Summary
When ticking "Require user confirmation when this key is used" `ssh-askpass` is used to confirm. A better experience would be if Keepass would open it's own window to confirm (Maybe make it optional for users that like/need the `ssh-askpass` dialog).
This would also be good for new users that currently would just see the error message from #2606.

## Examples
Something like the Dialog for Browser Logins:
![image](https://user-images.githubusercontent.com/11978847/118376296-70c4d800-b5c7-11eb-9afc-de4040728cce.png)
Mockup:
![image](https://user-images.githubusercontent.com/11978847/118376513-a5855f00-b5c8-11eb-91fe-0903b48f369b.png)

**Comment by droidmonkey** [comment]
This isn't possible because there is no communication back to keepassxc. The ssh agent only accepts key data and we tell it to ask for confirmation. There is no back talk to keepassxc after that.

**Comment by karolyi** [comment]
@droidmonkey you can set the SSH_ASKPASS value to something keepassxc provides, or symlink that binary outright into `/usr/lib/ssh/ssh-askpass`, the default path.

I don't see why it shouldn't be able to solve this issue that way.

**Comment by smurfix** [comment]
Alternately you can ask `ssh-agent` to open its confirmation dialog. `ssh-add` has the `-c` option for that. keepassxc can send that option along. Just tell it to do so.

**Comment by droidmonkey** [comment]
We don't call the cli, we use the socket

**Comment by smurfix** [comment]
> We don't call the cli, we use the socket

I know, that was just meant as an example. In any case, in case somebody (like me …) stumbles on to this via web search: Keepassxc already has the requisite checkbox.
