### ISSUE TITLE
Modifiers not working in auto-type sequence

### ISSUE THREAD

**Issue by AdamPS** [keepassxreboot/keepassxc#6531]
## Overview
Modifiers not working in auto-type sequence.

Using [Docs here](https://keepassxc.org/docs/KeePassXC_UserGuide.html#_configure_auto_type_sequences)

## Steps to Reproduce
1. Create an entry with a custom auto-type sequence of "+a"
2. Trigger the entry

## Expected Behavior
Typing "A"

## Actual Behavior
Typing "+a"

## Context

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.4
Revision: 34a78f0

Qt 5.12.8
Debugging mode is disabled.

Operating system: Ubuntu 20.04.2 LTS
CPU architecture: x86_64
Kernel: linux 5.4.0-73-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- libgcrypt 1.8.5

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: Gnome
Windowing System: X11

**Comment by droidmonkey** [comment]
Implemented in develop already

**Comment by AdamPS** [comment]
Thanks, sorry I didn't spot that myself

**Comment by AdamPS** [comment]
I upgraded to 2.6.5 today and didn't get the fix  Is there any documentation of how the branches are used plesae?  Is there any way for me to get develop other than building myself?  Many thanks.

**Comment by droidmonkey** [comment]
https://snapshot.keepassxc.org

**Comment by AdamPS** [comment]
Great thanks
