### ISSUE TITLE
Auto-type reference syntax not working

### ISSUE THREAD

**Issue by afonsoc12** [keepassxreboot/keepassxc#6532]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
Auto-type reference syntax not working on macOS

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Define custom autotype sequence with `{REF:P@I:<UUID>}{ENTER}` 

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Should auto-type the referenced password

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Shows error message: `{REF:P@I:84E<Characters removed>3CC5843}{ENTER}`

## Context
[NOTE]: # ( Give us any additional information you may have. )
I have migrated from Macpass to KeepassXC. I have tried referencing passwords in auto-type sequence, with entries created by either KXC or Macpass, but didn't work in neither of the cases. I have also tested the UUID with upper/lower case, still no luck

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.4
Revision: 34a78f0

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS Catalina 10.15.7

**Comment by droidmonkey** [comment]
Available on develop branch will be part of 2.7.0
