### ISSUE TITLE
Recognition of URL_1, URL_2, URL_3 attributes, like KeePassDX on android has

### ISSUE THREAD

**Issue by godSaysHODL** [keepassxreboot/keepassxc#6533]
hello. On my keepassDX phone app, the additional attributes URL_1, URL_2, URL_3, etc work to serve up multiple URLs that a password is working for. On the Desktop KeePassXC, I cannot find a way to have multiple URLs recognized. Any suggestions?

**Comment by grivanov** [comment]
I believe you're looking for this: https://keepassxc.org/docs/KeePassXC_UserGuide.html#_advanced_usage

It's an option with the browser integration plugin, which have to be enabled and then you can add additional URLs for an entry.
