### ISSUE TITLE
Tiny Notes Text

### ISSUE THREAD

**Issue by mnpenner** [keepassxreboot/keepassxc#6535]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

The "Notes" text field is very tiny.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Open KeepassXC
2. Open an entry
3. Put some text in the Notes field

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

Normal sized text. The same as the Title, Username, and URL would be fine.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

It's like a quarter of the other text. Very hard to read.

![image](https://user-images.githubusercontent.com/1112998/118718181-cd98dc00-b7db-11eb-99f4-e14d416dcc2d.png)

## Context
[NOTE]: # ( Give us any additional information you may have. )

I have a 4K display scaled to 150% and a 1080p display scaled to 100%. I think this confuses some apps/certain text fields but I tried fiddling with the Windows 10 compatibility options and that didn't help.

[NOTE]: # ( Paste debug info from Help → About here )

KeePassXC - Version 2.6.4
Revision: 34a78f0

Qt 5.15.2
Debugging mode is disabled.

Operating system: Windows 10 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.19042

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
- libgcrypt 1.9.1-unknown

**Comment by droidmonkey** [comment]
This week be fixed in 2.6.5, already in pipeline
