### ISSUE TITLE
How likely is database corruption?

### ISSUE THREAD

**Issue by macruspareto** [keepassxreboot/keepassxc#6538]
I used to store my passwords in txt files in Truecrypt (then Veracrypt) container.
For 10+ years I had accidental reboots, BSoDs, dirty unmounts, power loss but the container has never got rendered inaccessible/damaged. Very fail-safe.

How fault-tolerant is the KeePass design?
After every change, I backup my .kdbx in three separate locations (USB and NAS), with older copies aswell so I could rollback.

But still, in your opinion, is there a risk of database corruption? Mainly due to file I/O, overwriting and re-encrypting, improper unmounting etc?

**Comment by droidmonkey** [comment]
I've been using keepassxc since 2016, keepass2 before that. Since developing keepassxc I've eaten my own dog food and run on develop snapshots. I store my db in onedrive and use keepassdx on mobile. I have never once had a corrupt or inaccessible database.
