### ISSUE TITLE
Issues with Browser Integration-Advanced dialogue

### ISSUE THREAD

**Issue by rogercreagh** [keepassxreboot/keepassxc#6542]
## Overview
Five related issues - solving one may also solve one or more others with different implications

## Steps to Reproduce
1. Open Settings
2. Select Browser Integration
3. Open Advanced Tab
4. Check the Use Custom Browser Config Location Button

a) the hint given in the config location box shows
`~/.custom/config/Mozilla/native-messaging-hosts`
This is unlikely to be correct - more likely to be `~/.config/...`

b) entering a location starting with `~/` is not correctly parsed.
Instead of mapping `~/` to the current user home directory it *creates* a folder called `~` in the users home directory.
So the example in the hint creates a new folder `/home/roger/~/.custom/config/Mozilla/native-messaging-hosts`

In order for the correct location to be used the full path from root must be entered - this conflicts with the information given in the hint. eg on Ubuntu `/home/roger/.config/microsoft-edge-beta/NativeMessagingHosts/` works ok

c) The dropdown selector for Browser type (Firefox | Chromium) doesn't appear to do anything

d) The [ Browse... ] button starts from `/usr/bin` instead of a more likely location for the `native-messaging-hosts` folder
eg `~/.config` where "~" is the user home directory.

e) There is no indication that a custom location has already been set

## Expected Behavior
 a) The hint should either be `eg: ~/.config/[BrowserName]/native-messaging-hosts/` if `~` is going to be parsed correctly 
or give `eg /home/[Username]/.config/[BrowserName]/native-messaging-hosts/` as the hint if the "~" is not going to map to the user home directory

b) either `~/` in the Config location should be parsed or the hint shouldn't imply that it can be used. It should not simply create a new folder in the user home directory unless it is going to be used by keepassxc and the browser

c) If there are really only two possible Browser types then there should be some way of showing what is different between them. Different browsers of by Chromium will use their own separate config folders and it should be possible to have separate custom config locations for each separate browser of type Chromium

d) the browse button could more usefully start from `~/.config` (where `~` actually is the user home directory!)

e) it would be helpful if custom locations have already been set, then these could be listed under the location entry box together with the browser name.

## Actual Behaviour
See above

## Context

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.4
Revision: 34a78f0

Qt 5.12.8
Debugging mode is disabled.

Operating system: Ubuntu 20.04.2 LTS
CPU architecture: x86_64
Kernel: linux 5.4.0-72-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- libgcrypt 1.8.5

[NOTE]: # ( Pick choices based on your environment )
Operating System: /Linux/ (ubuntu 20.04.2)
Desktop Env: Gnome
Windowing System: X11/

**Comment by droidmonkey** [comment]
Browser type changes the JSON output because they look for different fields.

**Comment by michaelk83** [comment]
> b) either `~/` in the Config location should be parsed or the hint shouldn't imply that it can be used.

I think it's important that `~` would be parsed correctly, because most Linux users are used to using `~` as a shorthand for their home folder. Even if the hint won't mention it, they'll still expect it to work.

**Comment by droidmonkey** [comment]
Yah that's the real bug here
