### ISSUE TITLE
Autotype Search when no matching entry was found

### ISSUE THREAD

**Issue by newhinton** [keepassxreboot/keepassxc#6543]
## Summary
When the autotype is triggered and no matching entry was found, the autotype aborts. This can be frustrating, since the user has to manually prepare each entry before beeing able to use it. 

To solve this issue i propose the follwing solution:
When no entry was found, a window with a searchbar and a list of all items matching the search should be shown. The user can then select or abort the autotype via enter or escape

## Examples
The keeweb-application has this feature as it's main way to type passwords.
![grafik](https://user-images.githubusercontent.com/25279821/119052937-a30a7700-b9c5-11eb-933b-516422db9bd6.png)
(this is a demo database provided by keeweb)

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
I am currently suggesting this application to users who have not used password managers before.Preparing and "fixing" entries on a regular basis is not likely to happen, also it would be way easier to present a search when no match was found.

**Comment by droidmonkey** [comment]
Already implemented in develop branch
