### ISSUE TITLE
Favicon download fails

### ISSUE THREAD

**Issue by dhanak** [keepassxreboot/keepassxc#6544]
## Overview
I'm using KeePassXC v2.6.4, as an AppImage application, on debian buster. (Even buster-backports has a pretty outdated version of keepass as a deb package.) It works perfectly as expected, except for the favicon downloads, which "reliably" fails each and every time, for every domain I've tried.

This happens with and without the DuckDuckGo option, it happens using Ctrl-Shift-D on an existing entry and it happens when pressing the "Download favicon" button on the icon tab of an entry.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. download KeePassXC-2.6.4-x86_64.AppImage
2. add an entry for, e.g., https://google.com/
3. in the icons tab, press "download favicon"
4. observe the red banner

## Expected Behavior
Favicon is downloaded and added to the database.

## Actual Behavior
Favicon download fails.

## Context
I'm running the AppImage in a regular, natively installed debian instance, without root privileges. There is no lxc or docker containers, virtual machines, firejail or any other sort of sandboxing or virtualization. The sites I've tried open in a browser, favicon.ico exists in their root folder, DuckDuckGo shows their icons fine.

KeePassXC - Version 2.6.4
Revision: 34a78f0
Distribution: AppImage

Operating System: Linux debian buster
Desktop Env: Gnome
Windowing System: X11

Help would be appreciated!

**Comment by droidmonkey** [comment]
#4219 is why this is happening. Closing as a duplicate. You'll have to use the snap or native install to download favicons on Debian.

**Comment by dhanak** [comment]
@droidmonkey, thanks, that explains it of course. I suspected it was some AppImage specific issue.

Just a thought, though: if there was an option to use an external program to fetch the favicon, e.g., curl, then this iisue could easily be circumvented. WDYT?

**Comment by droidmonkey** [comment]
That's not a bad idea actually. We could do that for all network requests from the appimage. Thank you! Will add that to the other ticket.

**Comment by compilin** [comment]
I'm having the same issue (every favicon download fails) but I'm not sure if in my case it's related to #4219, for two reasons : it always fails not just for HTTPS entries but HTTP ones as well, and I'm not getting any SSL error in the terminal
Using AppImage 2.6.6 on Debian 10

**Comment by droidmonkey** [comment]
#4219 tracks this
