### ISSUE TITLE
Health Check Score field sorted alphabetically not numerically

### ISSUE THREAD

**Issue by klieret** [keepassxreboot/keepassxc#6551]
## Overview

Sorting by score in the health check tab to single out the weakest passwords is not possible, because the scores get sorted alphabetically as strings, not as numbers. E.g. "-1, -13, 1, 12, 13, 2" instead of "-13, -1, 1, 2, 12, 13"  

## Steps to Reproduce

1. Database > Database Reports > Health Check
2. Click on "Score" to sort by score

[NOTE]: # ( Paste debug info from Help → About here )

KeePassXC - Version 2.6.0
Revision: 0765954

Qt 5.12.4
Debugging mode is disabled.

Operating system: Ubuntu 19.10
CPU architecture: x86_64
Kernel: linux 5.3.0-64-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.4

[NOTE]: # ( Pick choices based on your environment )
Operating  Linux
Desktop Env: Gnome
Windowing System: X11

**Comment by droidmonkey** [comment]
That is fixed in later versions of 2.6, we are on 2.6.4

**Comment by klieret** [comment]
I see, thanks a lot!  :+1:
