### ISSUE TITLE
KeepassXC does not work with backup YubiKey programmed with the same secret.

### ISSUE THREAD

**Issue by gordonbrice** [keepassxreboot/keepassxc#6552]
Programmed 2 YubiKeys with the same secret, KeepassXC only works with 1.  Each YubiKey has a different serial number. Seems that different serial number causing a problem.

**Comment by droidmonkey** [comment]
You are either using the wrong slot or the secret is not the same.

**Comment by gordonbrice** [comment]
You are correct, this is not an issue.
