### ISSUE TITLE
Contrast text color based on entry background color

### ISSUE THREAD

**Issue by newhinton** [keepassxreboot/keepassxc#6553]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
If an entry has a background color, it can make text unreadable when a dark or light color is used. (depending on the used theme)
Also, coloring the full line can be quite overwhelming. Maybe it would be a good idea to add a column "background color" to the available columns, and if that is added to the displayed columns, a colored dot fills this column and the row does not get colored.
(I know about the text-color, and while that solves this issue, it can be tedious)
## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )
![grafik](https://user-images.githubusercontent.com/25279821/119253146-225b9e80-bbb0-11eb-8b4c-94081ff62ab9.png)
(I used the totp columm for the dot, and it should be either a colored row or the dot, not both)

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
I don't know if this would be a truly useful addition, it could make the ui a bit more clear and easy to read

**Comment by michaelk83** [comment]
This is about the main list view, correct?

The health check report has this:
![healthcheck](https://user-images.githubusercontent.com/867299/118717248-1bd2cd00-b826-11eb-8706-b3a823f8108a.png)

**Comment by newhinton** [comment]
yes, it's about the main list, but with the background-color instead of a health check

**Comment by droidmonkey** [comment]
The entry background color is an afterthought and definitely conflicts with theming, it's a carry over from original keepass. The text color should contrast with the background color so that is a ui bug. I kind of like the idea of a color column, but the utility is very limited. We are working on the tags feature which will add another way to differentiate entries as well.

**Comment by newhinton** [comment]
I tried to do it myself and create a pr, but i am not used to qt/c++
If you could give me hints where to start, maybe i can figure this out

**Comment by droidmonkey** [comment]
We'll take care of it.

**Comment by newhinton** [comment]
@droidmonkey Any news? I could still try creating that bubble if you want me to! :)

**Comment by newhinton** [comment]
~~I have archieved the desired style with changing the password-strength column, however, adding a new Column to the EntryModel::ModelColumn-Enum (and all the switch-statements) does not add a new column.~~

~~How do i duplicate a row in the column-head, preferably the password-strenght one?~~

Edit: I found out that i needed to increment the column-count in the EntryModel::columnCount-method
