### ISSUE TITLE
KeePassXC is crashing because of memory problem

### ISSUE THREAD

**Issue by DunklerPhoenix** [keepassxreboot/keepassxc#6554]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
After 10 to 15 min KeepassXC is crashing with the following message. I didn't change anything exept I updated Windows.
![8kNtZjLvwl](https://user-images.githubusercontent.com/1261305/119255630-1fb37600-bbbd-11eb-8aa7-653a2377e782.png)

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Can't reproduce, cause I don't know the error

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
KPXC should not crash

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
KPXC is crashing

## Context
[NOTE]: # ( Give us any additional information you may have. )
I load the DB and the key from a mounted Google Drive through official Google Drive client.

KeePassXC - Version 2.6.4
Revision: 34a78f0

Qt 5.15.2
Diagnosemodus ist deaktiviert.

Betriebssystem: Windows 10 Version 1909
CPU-Architektur: x86_64
Kernel: winnt 10.0.18363

Aktivierte Erweiterungen:
- Auto-Type
- Browser-Integration
- SSH-Agent
- KeeShare (bestätigtes und unbestätigtes Teilen)
- YubiKey

Kryptographische Bibliotheken:
- libgcrypt 1.9.1-unknown

**Comment by droidmonkey** [comment]
Try moving the db and key outside the Google drive folder just to make sure. Also try reinstalling or running one of our develop snapshots to see if it persists. https://snapshot.keepassxc.org/latest

**Comment by DunklerPhoenix** [comment]
Started from Harddrive: still crashing.
Installing now Dev-Snapshot

**Comment by DunklerPhoenix** [comment]
Still crashing with dev version. :/

Are there any informations I can give to you?

btw: I using KeepassXC-Browser:

----
KeePassXC - 2.7.0-snapshot
KeePassXC-Browser - 1.7.8.1
Operating system: Win64
Browser: Chrome/Chromium 91.0.4472.69
----

and I use the ssh agent feature

**Comment by droidmonkey** [comment]
Disable all features and see what happens. This is a unique behavior with your computer. You could be having a negative interaction after your Windows update to... something??

**Comment by DunklerPhoenix** [comment]
I removed all KeePassXC folders from Appdata and started the portable version from the snapshot site after I killed all processes from KeepassXC. 

Still crashing

**Comment by droidmonkey** [comment]
At this time you will need to capture a crash dump to determine what is going on. Read here for info on how to enable dump collection: https://docs.microsoft.com/en-us/windows/win32/wer/collecting-user-mode-dumps

**Comment by DunklerPhoenix** [comment]
Hm.. It doesn't generate any dumpfiles. 

I even removed the dumptools which prevent the generation under:
Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\AeDebug

![0Nofi6g9zg](https://user-images.githubusercontent.com/1261305/119274669-6df26480-bc11-11eb-9437-142b5d8d8bcb.png)
![c0HomM8YrH](https://user-images.githubusercontent.com/1261305/119274673-6f239180-bc11-11eb-90fa-66baa563cc41.png)

**Comment by droidmonkey** [comment]
This might be because we disable crash dumps when in release mode, even if debug symbols are made available. You'll have to build the application yourself and run a debugger. Otherwise will have to build a custom full debug build for you.

**Comment by DunklerPhoenix** [comment]
dang it.
I'm sorry I don't have any developer tools on my devices. I'm an advanced user, but I don't know anything about development environments ^^

**Comment by droidmonkey** [comment]
Here is a full on portable debug build on the latest develop branch commit: https://drive.google.com/file/d/1_DwANGAv9zXvXz6jHDdw_26bh7FdeJQW/view?usp=sharing

**Comment by Hannah-Bee** [comment]
@DunklerPhoenix, do you use KeeShare?
Get the same crash error message, when KeePassXC jumps into the KeeShare loop (reported bug, see issue #6526 )

**Comment by DunklerPhoenix** [comment]
Ahh sorry had too much to do in the last days and forgot to answer. XD 

The debug build is not crashing. What is really strange. I even import my config.

No I don't actively use keyshare. Neither the import nor export checkbox are checked.

**Comment by droidmonkey** [comment]
Of course it doesn't crash, lol. Performance anxiety

I am fairly certain this is a crash induced by something on your system and not the program itself. Otherwise everyone would be crashing all the time.

**Comment by DunklerPhoenix** [comment]
¯\_( ͡° ͜ʖ ͡°)_/¯ I'll close this issue. It's not really reproducable

Thanks for your time. Have a great day

**Comment by michaelk83** [comment]
You can try with a fresh DB to see if the problem is with the file. If it still crashes, maybe roll back the Windows update to see if that solves it. There should be an automatic restore point.
