### ISSUE TITLE
CMD:// doesn't work in Fedora 33

### ISSUE THREAD

**Issue by josevnz** [keepassxreboot/keepassxc#6555]
## Overview

Hello,

When you try to use CMD:// to run a shell script or external command it fails

## Steps to Reproduce

1. Create a new entry 
2. On the URL call your script (make sure the full path works on the Bash command line first): CMD:///home/josevnz/bin/myscript.sh
3. Try to execute script. No error on the GUI but if you are lucky enough to start KeePassXC from a terminal window you will see this: 
```
io: cmd:///home/josevnz/bin/myscript.sh: The specified location is not supported
```

## Expected Behavior
Run the script from Bash

## Actual Behavior

```
io: cmd:///home/josevnz/bin/myscript.sh: The specified location is not supported
```

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.4
Revision: 34a78f0

Qt 5.15.2
Debugging mode is disabled.

Operating system: Fedora 33 (Workstation Edition)
CPU architecture: x86_64
Kernel: linux 5.11.21-200.fc33.x86_64

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- libgcrypt 1.8.7

[NOTE]: #
Operating System: Linux dmaf5 5.11.21-200.fc33.x86_64 #1 SMP Sat May 15 20:31:00 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux (Fedora 33)
Desktop Env: Gnome
Windowing System: X11/Wayland

**Comment by josevnz** [comment]
I was looking for more details on https://keepass.info/help/base/autourl.html or even on gio error but could not find anything useful. In all honesty it seems an Gnome issue and not a KeepassXC. This command also fails:
```
xdg-open CMD:///home/josevnz/bin/myscript.sh
io: CMD:///home/josevnz/bin/myscript.sh: The specified location is not supported
```

**Comment by droidmonkey** [comment]
Don't use three slashes.

**Comment by josevnz** [comment]
You are %100 correct, I changed cmd:// following your suggestion and works like a charm.
Thanks for looking into this!
--Jose
