### ISSUE TITLE
Make the OTP expiration time visible in the preview panel

### ISSUE THREAD

**Issue by ghost** [keepassxreboot/keepassxc#6556]
## Summary
Currently, KeePassXC does not display the seconds remaining for the OTP to expire.

## Examples
There could be a countdown showing the seconds like 641 245 (12), 641 245 (11), 641 245 (10)...

## Context
Is not possible to know if the OTP is about to expire (3 seconds, 2 seconds) etc, making the user to re-enter the next OTP to successfully login.

**Comment by droidmonkey** [comment]
We show this information in the totp display dialog, but not in the preview panel. The preview panel also lacks a copy button.

**Comment by FiloSpaTeam** [comment]
I'm working on this feature. An example (implemented but not pushed):
![Schermata da 2021-05-28 19-16-23](https://user-images.githubusercontent.com/2974561/120019898-4b819200-bfe9-11eb-9bdd-abaf4a2edbbe.png)

U can toggle visibily and copy text.

**Comment by lyrebird-sound-cloning-system** [comment]
> I'm working on this feature. An example (implemented but not pushed):
> ![Schermata da 2021-05-28 19-16-23](https://user-images.githubusercontent.com/2974561/120019898-4b819200-bfe9-11eb-9bdd-abaf4a2edbbe.png)
> 
> U can toggle visibily and copy text.

Very great! I think the expiration time could be shown next to the ***** characters, because currently it's too far. Also, this creates an inconsistency, because all of the elements that have an spacement are sections (they even have a bolder font).

**Comment by FiloSpaTeam** [comment]
> > I'm working on this feature. An example (implemented but not pushed):
> > ![Schermata da 2021-05-28 19-16-23](https://user-images.githubusercontent.com/2974561/120019898-4b819200-bfe9-11eb-9bdd-abaf4a2edbbe.png)
> > U can toggle visibily and copy text.
> 
> Very great! I think the expiration time could be shown next to the ***** characters, because currently it's too far. Also, this creates an inconsistency, because all of the elements that have an spacement are sections (they even have a bolder font).

Ok i'll fix the space and insert a copy-to-clipboard button near to.

**Comment by FiloSpaTeam** [comment]
NO OTP Version
![Schermata da 2021-05-29 10-39-41](https://user-images.githubusercontent.com/2974561/120063976-3d278a80-c06a-11eb-9cd6-b1470acd47c3.png)

OTP Version
![Schermata da 2021-05-29 10-39-51](https://user-images.githubusercontent.com/2974561/120063984-44e72f00-c06a-11eb-821a-c392452ff65c.png)
