### ISSUE TITLE
Exculding groups from database reports 

### ISSUE THREAD

**Issue by Kevin95Jo** [keepassxreboot/keepassxc#6561]
I suggest an option, to exclude complete groups from database reports, not only single entries.
See attached Screenshot for the Option I'am talking about.

![exclude_entry](https://user-images.githubusercontent.com/35923166/119506823-93e14b80-bd6e-11eb-9ecd-d4e32570638c.png)

**Comment by droidmonkey** [comment]
We have rejected that as an option since the reports operate on the entry level and setting that option on a group can have undesirable effects. We have another issue to set exclusion on multiple entries at once which is the desired direction.
