### ISSUE TITLE
Allow copying the OTP to the clipboard by clicking in a button

### ISSUE THREAD

**Issue by lyrebird-sound-cloning-system** [keepassxreboot/keepassxc#6568]
## Summary
Currently, KeePassXC does not allow to copy the OTP.

## Examples
There could be an button, next to the OTP. It could be an icon-only button.

## Context
This feature would speed up 2FA.

**Comment by droidmonkey** [comment]
This is a duplicate request. Also you can double click the little stopwatch icon in the entry list to copy the otp or use the keyboard shortcut (Ctrl + T)

**Comment by lyrebird-sound-cloning-system** [comment]
Understood. Is this a duplicate of https://github.com/keepassxreboot/keepassxc/issues/6556? I filed this feature request because I didn't know I could suggest two features in the same report.
