### ISSUE TITLE
keepassxc snap fails to run on ubuntu 16.04.2

### ISSUE THREAD

**Issue by rhetr** [keepassxreboot/keepassxc#657]
I tried installing keepassxc via `sudo snap install keepassxc` and running it but I get this error:
```
cannot perform operation: mount /var/lib/snapd/hostfs/var/lib/lxd /var/lib/lxd -o nosuid,nodev,noexec,rbind,rslave: Permission denied
```
from `journalctl -f`:
```
Jun 21 15:37:46 ERIS keepassxc[5376]: cmd.go:114: DEBUG: not restarting into "/snap/core/current/usr/bin/snap" ([VERSION=2.24 2.24]): older than "/usr/bin/snap" (2.25)
Jun 21 15:37:46 ERIS audit[5376]: AVC apparmor="DENIED" operation="mount" info="failed srcname match" error=-13 profile="/usr/lib/snapd/snap-confine" name="/var/lib/lxd/" pid=5376 comm="snap-confine" srcname="/home/lxd/" flags="rw, rbind"
Jun 21 15:37:46 ERIS kernel: audit: type=1400 audit(1498073866.401:34): apparmor="DENIED" operation="mount" info="failed srcname match" error=-13 profile="/usr/lib/snapd/snap-confine" name="/var/lib/lxd/" pid=5376 comm="snap-confine" srcname="/home/lxd/" flags="rw, rbind"
```

Following https://github.com/keepassxreboot/keepassxc/issues/581 i rebooted my computer but that didn't help. I also tried running `sudo keepassxc` to no avail.

## Steps to Reproduce (for bugs)
1. `sudo snap install keepassxc` on ubuntu 16.04.2
2. run `keepassxc` in terminal

## Your Environment
* Operating System and version: ubuntu 16.04.2

**Comment by droidmonkey** [comment]
Do any other snaps work for you? Have you tried loading it directly from the Ubuntu Store?

**Comment by rhetr** [comment]
good point, i had at some point in the past moved `/var/lib/lxd` to another drive and symlinked it. I moved it back and it works now.
