### ISSUE TITLE
libpng warning when using cli

### ISSUE THREAD

**Issue by Stig124** [keepassxreboot/keepassxc#6570]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
When running a command on cli, I randomly get 

```
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
```

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1.  Run a CLI command

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
No warnings

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Warnings

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )

KeePassXC - Version 2.6.4
Revision: 34a78f0

Qt 5.15.2
Debugging mode is disabled.

Operating system: openSUSE Tumbleweed
CPU architecture: x86_64
Kernel: linux 5.12.4-1-default

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (only unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- libgcrypt 1.9.3-unknown

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: i3wm
Windowing System: X11

**Comment by droidmonkey** [comment]
Thus means you have an old database with bad custom icons. Just a warning though nothing well fix.

**Comment by basbebe** [comment]
is there a way to suppress this warning or find out which icons cause this?
It makes it difficult to use in scripts which rely on the output, e.g. mutt password prompt.
if I redirect stderr (`keepassxc-cli show ~/MYPASSWORDS.kdbx -y 1:12345678 PASSWDTITLE 2> /dev/null`), the password and yubikey prompts also will be suppressed.

**Comment by michaelk83** [comment]
`keepassxc-cli ... | grep -v libpng`
https://stackoverflow.com/a/4373691/15047974

**Comment by scross01** [comment]
Is there a way to identify which icons are causing the `libpng warning: iCCP: known incorrect sRGB profile` warning? Seems like the best fix would be to remove those custom icons

**Comment by droidmonkey** [comment]
No, we can't see this warning from within the application code so we have no idea it happens
