### ISSUE TITLE
[Proposal] TotpDialog.ui removal in favor of #6556

### ISSUE THREAD

**Issue by FiloSpaTeam** [keepassxreboot/keepassxc#6579]
## Summary
[NOTE]: Due to #6556 I did a fix that includes all functionalities of TotpDialog.ui in the preview panel. What you think if I refactor the code and remove TotpDialog?
Now you can copy totp with the button too.

## Examples
![Schermata da 2021-05-29 10-39-51](https://user-images.githubusercontent.com/2974561/120191236-fc6e7380-c219-11eb-99b5-7fef5c9026ff.png)

## Context
[NOTE]: Just a cleaner code and more usable totp

**Comment by droidmonkey** [comment]
You need to open a PR to discuss code. I don't like the otp below the notes, the notes are meant to expand with the height of the preview panel. Move It above expiration.

**Comment by FiloSpaTeam** [comment]
> You need to open a PR to discuss code. I don't like the otp below the notes, the notes are meant to expand with the height of the preview panel. Move It above expiration.
> 
> Instead of a dedicated copy button it should copy on double click of the totp numbers. It's rather cluttered atm.

Ok so just to resume:
- Move the "OTP Widget Line" above the "Expiration" Line
- Change the copy to clipboard function
- Open a Pull Request
