### ISSUE TITLE
Database stays unlocked when session is locked

### ISSUE THREAD

**Issue by michcio1234** [keepassxreboot/keepassxc#6581]
## Overview
Database stays unlocked when I lock my session (whether via lid-close or just locking the screen).

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Unlock the database
2. Lock your screen
3. Unlock your screen

## Expected Behavior
The database should be locked after the session is locked and unlocked again.

## Actual Behavior
The database stays unlocked.

## Context
[NOTE]: # ( Give us any additional information you may have. )
I'm running Linux Mint 19.3
with Cinnamon 4.4.8
KeePassXC installed via snap.
I do have the relevant checkbox toggled in settings.

[NOTE]: # ( Paste debug info from Help → About here )
```
KeePassXC - Version 2.6.4
Revision: 34a78f0
Distribution: Snap

Qt 5.9.5
Debugging mode is disabled.

Operating system: Ubuntu Core 18
CPU architecture: x86_64
Kernel: linux 5.4.0-73-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- libgcrypt 1.8.1
```
[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: Cinnamon
Windowing System: X11

Related issue: https://github.com/keepassxreboot/keepassxc/issues/5757

**Comment by michaelk83** [comment]
Possibly related to #6493, and maybe #721.

**Comment by droidmonkey** [comment]
Make sure you have a lock screen that supports dbus messaging.  You are using a very old version of Linux. This is not something we'll be investigating since it works everywhere we have tested (minor exceptions noted).

**Comment by michcio1234** [comment]
Is Mint 19.3 considered "very old"? O.o

**Comment by droidmonkey** [comment]
Mint 19.3 is based on Ubuntu 18.04.3

**Comment by michcio1234** [comment]
Alright, thanks for the tip anyway.

**Comment by hackel** [comment]
I just experienced this on Ubuntu 21.04.  My computer had been sleeping for ~24 hours.  I opened it up, and much to my surprise I was able to see a password in Firefox and discovered that KeePassXC was indeed unlocked.  It might be some kind of race condition with gnome-shell, but it makes me nervous.  Unfortunately I cannot reproduce the issue to capture much useful information, which is why I'm not bothering to create a new bug report.  

I have both "lock when session is locked or lid is closed" and "lock databases after inactivity of 3600 sec" enabled and neither one triggered in this case.

I found these denial messages in my journal from the suspend yesterday that might be relevant.

```
Jul 01 13:40:05 xps audit[1411]: USER_AVC pid=1411 uid=105 auid=4294967295 ses=4294967295 subj=unconfined msg='apparmor="DENIED" operation="dbus_signal"  bus="system" path="/org/freedesktop/login1" interface="org.freedesktop.login1.Manager" member="PrepareForSleep" name=":1.3" mask="receive" pid=377522 label="snap.keepassxc.keepassxc" peer_pid=1452 peer_label="unconfined"
                                  exe="/usr/bin/dbus-daemon" sauid=105 hostname=? addr=? terminal=?'
Jul 01 13:40:05 xps audit[1411]: USER_AVC pid=1411 uid=105 auid=4294967295 ses=4294967295 subj=unconfined msg='apparmor="DENIED" operation="dbus_signal"  bus="system" path="/org/freedesktop/login1" interface="org.freedesktop.login1.Manager" member="PrepareForSleep" name=":1.3" mask="receive" pid=307226 label="snap.signal-desktop.signal-desktop" peer_pid=1452 peer_label="unconfined"
                                  exe="/usr/bin/dbus-daemon" sauid=105 hostname=? addr=? terminal=?'
Jul 01 13:40:05 xps systemd-logind[1452]: Suspending...
Jul 01 13:40:05 xps systemd-logind[1452]: Lid closed.
```

```
KeePassXC - Version 2.6.6
Revision: 9c108b9
Distribution: Snap

Qt 5.9.5
Debugging mode is disabled.

Operating system: Ubuntu Core 18
CPU architecture: x86_64
Kernel: linux 5.11.0-18-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- libgcrypt 1.8.1
```

**Comment by michcio1234** [comment]
@droidmonkey I made sure that my system does emit a proper dbus message. I found this in dbus logs:
```
signal time=1652863087.501549 sender=:1.6 -> destination=(null destination) serial=6708 path=/org/gnome/SessionManager/Presence; interface=org.gnome.SessionManager.Presence; member=StatusChanged
   uint32 3
error time=1652863087.501582 sender=org.freedesktop.DBus -> destination=:1.6 error_name=org.freedesktop.DBus.Error.AccessDenied reply_serial=6708
   string "An AppArmor policy prevents this sender from sending this message to this recipient; type="signal", sender=":1.6" (uid=1000 pid=1635 comm="cinnamon-session --session cinnamon " label="unconfined") interface="org.gnome.SessionManager.Presence" member="StatusChanged" error name="(unset)" requested_reply="0" destination="org.freedesktop.DBus" (uid=1000 pid=264894 comm="/snap/keepassxc/1563/usr/bin/keepassxc " label="snap.keepassxc.keepassxc (enforce)")"
```
Looks like the system emits the message, but for some reason cannot send to to Keepass, right? I'll dig deeper, but maybe you have an idea what may cause this?

**Comment by michcio1234** [comment]
This issue is a _possible_ duplicate of https://github.com/keepassxreboot/keepassxc/issues/2951, but I am not sure.

**Comment by droidmonkey** [comment]
Ahhh the snap... we do hook into dbus so not sure why its blocking the message.

**Comment by michcio1234** [comment]
In the meantime I have updated my system. The issue persists. Not sure though how it would work with a fresh OS installation, but I don't feel like trying. ^^
```
KeePassXC - Version 2.7.1
Revision: 5916a8f
Distribution: Snap

Qt 5.15.3
Debugging mode is disabled.

Operating system: Ubuntu Core 20
CPU architecture: x86_64
Kernel: linux 5.4.0-109-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.12.1
```

**Comment by droidmonkey** [comment]
We are not going to expend time to fix this, use the flatpak verison.
