### ISSUE TITLE
Edited entry hangs program, after sleep 

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [keepassxreboot/keepassxc#6582]
## Overview

![image](https://user-images.githubusercontent.com/47056543/120300573-f7fe9500-c2c3-11eb-91ba-0b53fa94c119.png)

Neither window is closable or even moveble and I cannot seem to access any part of KeePassXC. Hence I fear I will lose the entry that I was editing.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
I think (I will test if I have time):

1. Start to edit an entry
2. Let the computer sleep
3. Awake the computer

## Expected Behavior

I should still be able to interact with the program.

## Actual Behavior

I cannot interact with the program.

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.4
Revision: 34a78f0

Qt 5.15.2
Debugging mode is disabled.

Operating system: Windows 10 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.19042

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
- libgcrypt 1.9.1-unknown

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows

**Comment by LinuxOnTheDesktop** [comment]
The problem remains present on a later version of KeePassXC, namely, version 2.7.0-snapshot.

**Comment by droidmonkey** [comment]
This is a duplicate, we know that the message pop-ups appear on lock with unsaved changes.

**Comment by droidmonkey** [comment]
Nevermind I see the real issue is multiple messages appearing causing model lockup.

**Comment by LinuxOnTheDesktop** [comment]
This rather irritating bug - whereby on Windows KeePassXC freezes when the PC awakes - seems related to #5286 and perhaps to #5415. I will try the latest snapshot build (KeePassXC-2.7.0-snapshot-Win64.msi) and see whether it contains the bug.

**Comment by LinuxOnTheDesktop** [comment]
Datapoint: just now I had the same problem - or rather or at least KeePassXC hanging after I'd entered the master password - on KeePassXC-2.7.0-snapshot-Win64.msi.

**Comment by droidmonkey** [comment]
This is most likely a problem induced by your specific database or an external program like anti-virus for example. I resume from sleep every single day using the 2.7.0 snapshot and have never crashed ever. 

Can you reproduce this with a brand new database file?

**Comment by LinuxOnTheDesktop** [comment]
@droidmonkey

Thanks. I suspect anti-virus is not at issue - because I had the problem when I used Windows Defender and I have the problem now that I use ESET. Still, I can tell ESET to ignore the KeePassXC process.

My specific database: well, if that's the cause then it is a bug, no? Compare also the other two bugs that I mentioned above; and perhaps cf. further perhaps #5199 and #6755. Also, I am afraid that, given the intermittent nature of the problem (it occurs sometimes after sleep and also, perhaps, occasionally at other times), testing with a new database would be too inconvenient. (For, it would mean a fair amount of time without being able to use my own database.)

Is there some data I could gather that would help diagnose the problem?

**Comment by droidmonkey** [comment]
No offense but if you aren't willing to do minimal troubleshooting to isolate the issue then I'm not going to make it a priority either. I cannot replicate these problems, so I need people who can to figure out what special sauce causes it to happen.

**Comment by LinuxOnTheDesktop** [comment]
> if you aren't willing to do minimal troubleshooting to isolate the issue

Well, to quote myself: 'given the intermittent nature of the problem (it occurs sometimes after sleep and also, perhaps, occasionally at other times), testing with a new database would be too inconvenient. (For, it would mean a fair amount of time without being able to use my own database.)'

Anyhow: you suggested that the problem might be my anti-virus; so, I have excluded the database directory, and KeePassXC.exe, from being examined by my anti-virus (that anti-virus being ESET). I will report back about whether that prevents the hang. If it does not, then I will consider foregoing my database for a few days, which is what your other suggestion amounts to.

**Comment by LinuxOnTheDesktop** [comment]
OK; the problem reoccurred - after four days - even once I had set up the anti-virus exclusions. So now I have to consider whether I can test with a fresh database - without going four days without the use of my main database. I suppose I could load a blank database before (and only before) the computer goes to sleep.

**Comment by droidmonkey** [comment]
Same as #7660
