### ISSUE TITLE
Adjustable or secondary theme (classic?) with less wasted space

### ISSUE THREAD

**Issue by cramsvik** [keepassxreboot/keepassxc#6585]
## Summary
The current design (2.6.4) has a very "airy" layout causing a lot of scrolling and poor oversight. It also causes the search field to be hidden unless the window is very large.

## Examples
Current:
<img width="1314" alt="before" src="https://user-images.githubusercontent.com/7917520/120438103-38701880-c381-11eb-9d4f-f95a81ecb7ff.png">

Desired result:
<img width="1314" alt="after" src="https://user-images.githubusercontent.com/7917520/120438162-4e7dd900-c381-11eb-808e-9f045e3272e8.png">

## Context
I deal with a lot of entries on a daily basis, and scrolling up and down to get to them wastes a lot of time and puts a strain on the finger operating the scroll wheel.

**Comment by droidmonkey** [comment]
In the menu bar, View -> Compact mode
The search bar problem is fixed in 2.6.5 coming out this week.
