### ISSUE TITLE
No more cursor in text fields :[

### ISSUE THREAD

**Issue by GMTSE** [keepassxreboot/keepassxc#6587]
## Overview

When a DB is opened and a text/password field is selected, I can't see where I'm typing because the cursor never shows up...

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Open KeepassXC
2. Open a DB
3. Select a text field
4. Type something
5. Clic somewhere in the typed text  (or move left a few times with keyboard arrows)

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

I should see the cursor where I'm supposed to insert text

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

I see the green surrounding around the text field so I kno it's selected, but there's no cursor showing. I can type stuff and then discover were the cursor is supposed to appear, but where it does not :{

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )

KeePassXC - Version 2.6.4
Revision: 34a78f0

Qt 5.12.8
Debugging mode is disabled.

Operating system: Linux Mint 20
CPU architecture: x86_64
Kernel: linux 5.4.0-73-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- libgcrypt 1.8.5

**Comment by droidmonkey** [comment]
This isn't our bug, it's Qt

**Comment by aeschbacher** [comment]
It's hitting again : version 2.7.4 (Debian Bookworm). 

I understand it might be caused by Qt, but any hint about how to fix would be useful. 

It is somehow bound to the environment though: on 3 different machines with exactly the same version of KeePassXC and Debian 12, only one is affected.
