### ISSUE TITLE
Lockups in SwayWM on Wayland

### ISSUE THREAD

**Issue by jahway603** [keepassxreboot/keepassxc#6588]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
When running KeePassXC 2.6.4 on Arch Linux with the Sway Windows Manager (SwayWM) on Wayland, it will randomly lock up  & become unresponsive and only a "kill -9" will let it close.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Open KeePassXC.
2. Keep KeePassXC running.
3. Go to use KeePassXC and it becomes unresponsive. Unfortunately having trouble determining exactly when or what causes this as it has both happened shortly after opening the application as well as having the application running for quite some time.
4. Then have to find the pid and "kill -9 pid".
5. Then can re-open KeePassXC and it will then work, until this issue happens again.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
I expect that it will not hang up and that it will always be responsive.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
The app hangs up and I am not able to determine why. Then it has to be force killed and restarted to function.

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.4
Revision: 34a78f0

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux (Arch)
Desktop Env: SwayWM
Windowing System: Wayland

**Comment by droidmonkey** [comment]
Only on Wayland?

**Comment by jahway603** [comment]
> Only on Wayland?

All my systems run Wayland now & I have experienced this on two different systems both running SwayWM. I don't have any X.org systems to see if this occurs there or not.

**Comment by tezkerek** [comment]
OBS has a similar problem: https://github.com/obsproject/obs-studio/issues/4295. [Someone](https://github.com/obsproject/obs-studio/issues/4295#issuecomment-790902417) backported a fix from Qt 6.2 in Qt 5.

I'm also on Sway, and with that [AUR package](https://aur.archlinux.org/packages/qt5-wayland-bugfixport-git) installed, I don't get any crashes in OBS or KeepassXC. @jahway603 if you're on Arch, you could try the AUR package and see if it fixes the issue.
