### ISSUE TITLE
Error building from source v2.7.0

### ISSUE THREAD

**Issue by avma** [keepassxreboot/keepassxc#6590]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
Error building from source.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. clone repo from git
2. cmake -DWITH_XC_ALL=ON -DCMAKE_BUILD_TYPE=Release ..
3. or
3. cmake -GNinja ..

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
complet build and install

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
process end with the following error:
```
CMake Error at /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find Botan2 (missing: BOTAN2_LIBRARY BOTAN2_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindBotan2.cmake:91 (find_package_handle_standard_args)
  CMakeLists.txt:445 (find_package)
```
```
-- Configuring incomplete, errors occurred!
See also "/home/avi/git/keepassxc/build/CMakeFiles/CMakeOutput.log".
See also "/home/avi/git/keepassxc/build/CMakeFiles/CMakeError.log".
```

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System:Linux mint 20.1
Desktop Cinnamon
Windowing System: X11

**Comment by droidmonkey** [comment]
Install botan libraries

**Comment by avma** [comment]
I did, before and afters ends with the same error.

**Comment by droidmonkey** [comment]
You need `libbotan-2-dev`

**Comment by avma** [comment]
ok thanks
