### ISSUE TITLE
Windows v2.6.4: Can't send "OK" with "Shift+Enter"

### ISSUE THREAD

**Issue by dksher** [keepassxreboot/keepassxc#6592]
## Overview
On "Unlock KeePassXC Database" screen, I can't send "OK" with "Shift+Enter".

## Steps to Reproduce
1. Launch KeePassXC (Windows v2.6.4) and open "Unlock KeePassXC Database" screen
2. Enter the master password and press "Shift+Enter"

## Expected Behavior
The database has been opened.

## Actual Behavior
"Shift+Enter" can't send "OK" and nothing happens.

## Context
This is problematic when the last character of the master password is an uppercase or a symbol, because I often press Enter with Shift to send OK in this case.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION 2.6.4
Revision: REVISION 34a78f0

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows

**Comment by dksher** [comment]
I noticed that "Shift+Enter" can't send "OK" not only on "Unlock KeePassXC Database" screen but also every screen of KeePassXC (New entry, Settings, etc.)

**Comment by droidmonkey** [comment]
Shift+Enter is not a standard shortcut. Use Ctrl+Enter

**Comment by dksher** [comment]
> Shift+Enter is not a standard shortcut. Use Ctrl+Enter. We won't be implementing Shift+Enter.

I think "send OK" was a bad explanation. What I want to do is to input the master password and unlock the KeePass database when I press Shift+Enter instead of Enter on "Unlock KeePassXC Database" screen.

![kpxc](https://user-images.githubusercontent.com/813832/120916267-a4d17b80-c6e3-11eb-9ad4-33f81752a6d1.png)

I believe 99.9% of Windows software treat "Shift+Enter" as "Enter", however, KeePassXC doesn't. (Is this intended?)

**Comment by dksher** [comment]
I guess I should create a new issue about this.

**Comment by droidmonkey** [comment]
Please do not. We are not going to implement it.

**Comment by dksher** [comment]
On the "Unlock KeePassXC Database" screen, "Shift+NumPadEnter" does work and "Shift+Enter" doesn't. Do you mean this is intended behavior?

**Comment by droidmonkey** [comment]
The two shortcuts that submit the form are Enter and Ctrl+Enter. It is perhaps a coincidence that Shift+NumPadEnter works as well. Shift+Enter is used as a line break insertion in text editor fields. It is not a standard shortcut for submitting information. Go ahead and try using it to submit a commit here in GitHub.

**Comment by FloPinguin** [comment]
I also have this "problem". Last two characters of my password are uppercase and for some reason I always press Shift+Enter to submit the password. Then I have to retry without Shift. 
It wouldn't hurt to just allow submitting the form with Enter, ignoring key combinations (Like KeePass without XC does).
