### ISSUE TITLE
Input of ^ (circumflex) in masterpassword-field only works when password is visible 

### ISSUE THREAD

**Issue by fuenfnull** [keepassxreboot/keepassxc#6595]
## Overview
I'm using masterpasswords with ^ (circumflex) and everything works when using keepassxc for Windows.
But under macOS (11.3 but also with previous releases) I'm not able to type the correct masterpassword containing the letter ^ (circumflex) when the letters are replaced by dots.
When changing the inputfield to show the password everything works well.
Sample password: q*l^2/8 results in 
q*l2/8 with invisible password. Consequently the database will not open.
<img width="732" alt="Bildschirmfoto 2021-06-06 um 20 07 57" src="https://user-images.githubusercontent.com/17235271/120935408-e9204400-c702-11eb-84cb-6dd21ca4136d.png">

KeePassXC - Version 2.6.4
Revision: 34a78f0

[NOTE]: 
Operating System: macOS

**Comment by droidmonkey** [comment]
This is a qt bug
