### ISSUE TITLE
Fix font size differences in about dialog between Mac/Linux/Win

### ISSUE THREAD

**Issue by droidmonkey** [keepassxreboot/keepassxc#660]
## Expected Behavior

Font sizes should be uniform across platforms. The issue arises due to the default font and font size being different on each platform. Any hardcoded font sizes will naturally conflict with this default.

Originated in #629. 

## Current Behavior

Font sizes in the about dialog are different on every platform.

## Possible Solution

* Setup a style sheet for each platform that HTML elements can pull from to set uniform font sizes.
* Programmatically set the font size in HTML elements based on the detected default font size.

**Comment by weslly** [comment]
@droidmonkey Looks fine for me

![image](https://user-images.githubusercontent.com/107672/45958095-ecc01b00-bfec-11e8-9e0c-cb52e74fa321.png)
![image](https://user-images.githubusercontent.com/107672/45958167-1c6f2300-bfed-11e8-898f-650d982569d5.png)
