### ISSUE TITLE
Ctrl + F no longer jumps to search after Update to 2.6.5

### ISSUE THREAD

**Issue by jhard** [keepassxreboot/keepassxc#6600]
Ubuntu 20.04, after updating to 2.6.5, Ctrl + F no longer works while in keepassxc. I can click into the search field with the mouse and typing + searching works fine, I just cannot navigate to it by pressing Ctrl + F.

Ctrl + F works in other programs, so it appears not to be a global hotkey being taken over. I've tried reopening keepassxc, but have not found success.

Given that there's not a lot of noise about it here, it seems to affect few people (might be just me). Anything I can try to find out what's interfering?

KeePassXC - Version 2.6.5
Revision: 2b262c5

Qt 5.12.8
Debugging mode is disabled.

Operating system: Ubuntu 20.04.2 LTS
CPU architecture: x86_64
Kernel: linux 5.4.0-74-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- libgcrypt 1.8.5

Operating System: Linux
Desktop Env: KDE
Windowing System: X12

**Comment by droidmonkey** [comment]
This is a test case so not sure what's going on

**Comment by jhard** [comment]
I've just tested with the AppImage of 2.6.4, which still works well. The AppImage for 2.6.5 does not, which at least rules out it being an issue with the ppa version.
I will try to run it on another machine tomorrow to see whether I can reproduce it.
Is there any additional diagnostics I can run? Is there an option to change the hotkeys?

**Comment by droidmonkey** [comment]
Confirmed this is a bug
