### ISSUE TITLE
Unable to Use YubiKey5 FIPS Challenge-Response because KeePassXC doesn't recognize

### ISSUE THREAD

**Issue by mh4it** [keepassxreboot/keepassxc#6605]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
When I use KeePassXC to make a new database, or modify an existing, I attempt to use a YubiKey Challenge Response and it is not detected by KeePassXC.  This occurred for me in Devuan and I just assumed it was Devuan, then I tested with ParrotOS, and also MXLinux.  It seems almost like the 2nd Slot is not being properly accessed by a long press as it is setup in the manager.
Could this be a Debian specific issue.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Create New KeePassXC database
2. Attempt to add a YubiKey Challenge-Response
3. Notice that the hardware key is not detected

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
I should be able to use bot Challenge-Response and also a static password with KeePassXC

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
I can't use Challenge-Response

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows/Linux/macOS
Desktop Env: Gnome/KDE/XFCE/Mate/Cinnamon
Windowing System: X11/Wayland

**Comment by droidmonkey** [comment]
Make sure you are on 2.6.4 version. If the yubikey is detected then you just didn't setup the second slot correctly. If it's not detected st all then you likely need to install udev rules for yubikey to use without root. If you are using the snap then you need to connect the raw-usb plug. Either way, this isn't on us it works perfectly and is well tested.
