### ISSUE TITLE
"Save Database" is disabled even for a mutated database and changes no longer indicated by asterisk in header bar

### ISSUE THREAD

**Issue by sphuber** [keepassxreboot/keepassxc#6608]
## Overview
Since I upgraded to v2.6.5 (don't remember from which version I came) changes in an open database no longer seem to be recognized. If I added an entry or modified an existing one, the header bar would indicate this by adding an asterisk (`*`) in the title name. Now this no longer happens. In addition, the "Save Database (Ctrl + S)" option from the "File" menu is disabled, as in it is greyed out and I cannot click it. I am forced to save the modified database by using "Save Database As" and overwriting the existing database file.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Open an existing database
2. Add or modify an existing entry
3. Try to select "Save Database" from the "File" menu

## Expected Behavior
I expect changes in the database to be indicated by an asterisk in the header title and I can save the changes by using "Save Database"

## Actual Behavior
Changes are not noticed and "Save Database" is disabled.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.6.5
Revision: 2b262c5

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: Gnome
Windowing System: X11/Wayland

**Comment by droidmonkey** [comment]
You probably have auto save after every change enabled.
