### ISSUE TITLE
[Feature] Move TOTP Field To Be Alongside Other Fields

### ISSUE THREAD

**Issue by seniorm0ment** [keepassxreboot/keepassxc#6610]
Requesting the TOTP field be moved up and become a full feature field (edit button, copy button, etc) with the other fields (password, username, url, etc) for better visibility and easier access.
It is a bit out of place being in the corner.

**Comment by droidmonkey** [comment]
It's in the context menus and in the columns of the entry view and in the entry preview. We won't be putting it anywhere else.
