### ISSUE TITLE
[Feature] E-Mail Field & Option To Swap Username w E-Mail

### ISSUE THREAD

**Issue by seniorm0ment** [keepassxreboot/keepassxc#6611]
Requesting a field to place an e-mail so the user can know what e-mail is associated to that account.

Also suggesting the ability to set a toggle on the username field that can switch to e-mail bscause some websites don't use usernames, but use an e-mail as the username. A minor thing, but just nice for organization.

**Comment by droidmonkey** [comment]
Search please, been requested many times.

**Comment by h-h-h-h** [comment]
See https://github.com/keepassxreboot/keepassxc/issues/3284#issuecomment-502908393
