### ISSUE TITLE
Sort by password entropy to know the weakest password currently in use

### ISSUE THREAD

**Issue by Rex-0x7CB** [keepassxreboot/keepassxc#6613]
## Summary
As the title suggests, it'd be great to know the weakest password in use. 

## Context
Currently, there's no way to figure which password is the weakest in the database as long as they are categorized "Good" and above. It'd still be great to know the credentials that require more attention than the others.

**Comment by droidmonkey** [comment]
A rating of good really means unbreakable, there is really no reason for additional fidelity beyond that.
