### ISSUE TITLE
Option to unlock other available databases for autotype

### ISSUE THREAD

**Issue by quelbs** [keepassxreboot/keepassxc#6616]
## Summary
If you have multiple databases you need to activate the main window to unlock other databases than the one used at last. Currently the autotype feature only offers to unlock the most recently used database. It would be nice to have an option to unlock other available databases from the autotype / not found dialogs.
It could also be an "unlock other database" button in the autotype dialog, if there are locked databases in the application.
If no entries are found in the currently unlocked database(s) it would be nice to also have an option to unlock available, locked databases in the "no entries found" dialog.

## Examples
Both dialogs do have a button (Abort or OK) on the bottom right, so it might be an option to put another button on the bottom left?

**Comment by droidmonkey** [comment]
This is a duplicate request and there is an open pr for this as well
