### ISSUE TITLE
TOTPs do not work for some sites

### ISSUE THREAD

**Issue by jorellaf** [keepassxreboot/keepassxc#6618]
## Overview
[NOTE]: Some TOTP codes for some websites do not seem to work, even though they were configured correctly.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1.  Set up TOTP.
2. Set time and date on Windows. NTP time.windows.com with manual (and correct) time zone, automatic DST (summer time is on right now).
3. Set up TOTP for an ORCiD account.

## Expected Behavior
[NOTE]: TOTP code is correct and allows me to log in.

## Actual Behavior
[NOTE]: TOTP code is incorrect.

## Context
[NOTE]: Versions 2.6.2 to 2.6.4.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.4
Revision: 34a78f0

Qt 5.15.2
Debugging mode is disabled.

Operating system: Windows 10 Version 2004
CPU architecture: x86_64
Kernel: winnt 10.0.19041

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
- libgcrypt 1.9.1-unknown

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 10

**Comment by droidmonkey** [comment]
This is definitely not our application. You must have entered the wrong key or the server time is off from your computer.

**Comment by droidmonkey** [comment]
The only other issue is if you have multiple accounts for the same site, sometimes the browser extension can give you the wrong totp code for the account you select.

**Comment by jorellaf** [comment]
I re-set-up the TOTP for my ORCiD account, and now it matches my other authenticator app, and I am able to log in. I am not sure why it did not before, since I followed the same process.

**Comment by droidmonkey** [comment]
You may have double pasted the key
