### ISSUE TITLE
Remember last used backup location

### ISSUE THREAD

**Issue by d-faure** [keepassxreboot/keepassxc#6619]
In the same mood as #3279 (but this should be a rather limited modification), couldn't simply the last chosen location for manually triggered database backup made persist?

For now, when I choose to "Merge from Database...", the last used location is kept in the file selector, and merging is quite comfortable for getting updates from the same source.

This is sadly not the case when making backup, the proposed directory being always the one of the last used database.

_Originally posted by @d-faure in https://github.com/keepassxreboot/keepassxc/issues/6199#issuecomment-845724769_

**Comment by droidmonkey** [comment]
You mean for the save database backup menu choice?

**Comment by d-faure** [comment]
Yep. That's it.
