### ISSUE TITLE
Possibility to sort entries manually

### ISSUE THREAD

**Issue by Arnobius** [keepassxreboot/keepassxc#6620]
I used KeePass on Windows but switched to Linux a few weeks ago. Now I am very happy with KeePassXC apart from one thing: I didn't find any way to sort my entries manually.

For example I can click on 'Title', 'Username', 'URL' and so on to sort it. But I seem to not be able to move my entries within a group up and down as I wish to. The windows version allows me to move it with a right click or with ALT + ARROW. Neither does this work in KeePassXC nor did I found another way to do it.

Did I just oversee the function or does the program lack it?

**Comment by droidmonkey** [comment]
Click the sort column twice to remove sorting which allows for manual sort.

**Comment by Arnobius** [comment]
This does not work. No matter how often I click on a header it just changes the order (header arrow up or down). There is no way of removing the sorting through clicking on a header.

Are you sure that this is working in KeePassXC? Mine is fully updated and I am using it on Linux Mint 20.1 Cinnamon.

**Comment by droidmonkey** [comment]
If you are running a version less than 2.6.0 then the feature wasn't implemented yet. 2.6.0 and above has the feature.

**Comment by Arnobius** [comment]
Ah, thank you!
Well, I have 2.4.3 but when I type in "sudo apt install keepassxc" (like the website tells), it says that I already have the latest version.

Do I maybe lack a specific repository?

Sorry for the noob answers, I am new to Linux.

**Comment by droidmonkey** [comment]
You have the latest version for the repository you are pulling from. Mint, Ubuntu, Debian tend to freeze their software versions. Grab the appimage from our downloads page or use the ppa from there to stay at the latest: https://keepassxc.org/download

**Comment by Arnobius** [comment]
That worked absolutely fine for me. Thank you so much for your advice and for your work with this program!
