### ISSUE TITLE
Database kdbx file gone / missing / deleted after crash

### ISSUE THREAD

**Issue by guessrrRUS** [keepassxreboot/keepassxc#6622]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
KeePassXC crashes, database file deleted after program restart

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Have KeePassXC run as portable from shared folder on different device from network
2. Open database file from subfolder of the KeePassXC folder on shared space with master pw + yubikee challenge response (with yubikee touch confirmation)
3. Let it idle in background for x time
4. Update an entry
5. Touch your yubikee when getting prompted
6. Watch the window just disappear
7. Restart KeePassXC

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
I expected for the database file to still be present after a crash and just go back to where I was.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Prompt orange message at the top telling me that the file isn't there and can't be opened.
I checked and truly, my database file isn't there anymore. Just my backup (sidenote: from more than 10 days ago, outdated *sigh*)

## Context
[NOTE]: # ( Give us any additional information you may have. )
KeePassXC crashed a few times with my current setup already. Sometimes after a lot of time for the program in idle mode and then suddenly after I try to change an entry. One time it also crashed just after a restart because of a crash.
However I can not reproduce a crash, so a particular pattern is missing.
The db disappeared with me not having Safe saving database files enabled.

KeePassXC - Version 2.6.4
Revision: 34a78f0

Qt 5.15.2
Debugging mode is disabled.

Operating system: Windows 10 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.19042

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
- libgcrypt 1.9.1-unknown

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows
KeePassXC being stored on fritzbox on NAS

**Comment by droidmonkey** [comment]
Your storage is to blame for the crashing and the file loss. Don't run keepassxc from a network share and use safe file saves.
