### ISSUE TITLE
keep ass.

### ISSUE THREAD

**Issue by PurpShell** [keepassxreboot/keepassxc#6624]
## Summary
just keep ass

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )
it's a meme

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
you can close this issue, I successfully made a meme.

**Comment by droidmonkey** [comment]
![Raf57ff165826bd8591861b0dfbc1ebe4.jpeg](https://user-images.githubusercontent.com/2809491/121743564-84ccfe00-cacf-11eb-80fe-2feff56fd969.jpeg)
