### ISSUE TITLE
Allow for comfortable displaying of master password using tab key

### ISSUE THREAD

**Issue by pilsnerbeer** [keepassxreboot/keepassxc#6625]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )

This will sound stupid but I really enjoyed and always used the 'display password' when opening my database. My master password is obviously very long and very complicated and I get it wrong 9/10 times if I don't see it as I type it (or if I type it real slow). 
On Keepass 2, I would start typing my password and immediately hit TAB and SPACE to SELECT and TOGGLE the 'display password' function so I can see what I am typing:

![Screenshot_2](https://user-images.githubusercontent.com/36133540/121748003-2c622480-cb00-11eb-89eb-d74e75212217.png)

when I switched to KeePassXC, I noticed that toggling 'display password' is not possible using keyboard keys but must be done so using mouse, which I don't like as much. I know its a weird feature to ask for but I would like to be able to toggle this using tab/space combo.

![Screenshot_1](https://user-images.githubusercontent.com/36133540/121748132-62070d80-cb00-11eb-8727-98c87e16e211.png)

**Comment by droidmonkey** [comment]
Ctrl + H
