### ISSUE TITLE
FIX - Program don't save history on fresh start - Linux (systemd)

### ISSUE THREAD

**Issue by eldes777** [keepassxreboot/keepassxc#6626]
**Problem:** 
The program by default store user configuration on cache directory (flushed at every reboot)

In order to **KeePassXC** save our history of database and keys it's needed the following solution.
**Store KeePass.ini on other place, not temporal.**

**My solution:** 
Build a systemd service to relocate our .ini on other place at every reboot and make a systemlink into it.

**Step-By-Step**

**1)** Open your favourite terminal app

**2)** Login as root

**3)** Go to /etc/systemd/system 

**4)** Run: Touch keepassxc.service

**5)** Copy the content attached >> keepassxc.service
[keepassxc.service.txt](https://github.com/keepassxreboot/keepassxc/files/6641119/keepassxc.service.txt)

**6)** Run: systemctl deamon-reload

**7)** Enable our service: systemctl enable keepassxc.service

**8)** Reboot your PC and enjoy your KeePassXC with history!

**Comment by droidmonkey** [comment]
Or just set where your local config is stored: https://keepassxc.org/docs/KeePassXC_UserGuide.html#_command_line_options
