### ISSUE TITLE
"Launch at system startup" automatically turns on after every update

### ISSUE THREAD

**Issue by opusforlife2** [keepassxreboot/keepassxc#6627]
## Overview

I have the option to launch at system startup off. But after every update, the app reverts to launching at system startup. As a result, I need to turn the option off after every update.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Turn off launch at system startup.
2. Update the app.
3. Reboot the OS.

## Expected Behavior

The setting to launch at system startup should stay turned off even after updates.

## Actual Behavior

It turns on automatically.

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.6.5

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 7

**Comment by droidmonkey** [comment]
Are you using the portable version?

**Comment by droidmonkey** [comment]
I see, we auto-select the start on login checkbox in the installer sequence. We should not check it if the product is already installed and you have not enabled that option.

![image](https://user-images.githubusercontent.com/2809491/121807568-a8ed2400-cc22-11eb-9237-e104b0724822.png)

**Comment by opusforlife2** [comment]
Oh. Now I get why I was confused. I use Chocolatey, which prefers silent installs of software.
