### ISSUE TITLE
keepassxc will not open for  non root user

### ISSUE THREAD

**Issue by error13** [keepassxreboot/keepassxc#6628]
### Overview
keepassxc will not open for  non root user:
    but opens a expected  as root as well as in cli  non root
        was working fine for none root users
            now just get spinner 
### Steps to Reproduce
try to open keepassxc in usual manner click desktop icon or try to open a existing data base from dir
### Expected Behavior
keepassxc opens or opens a  existing data base
### Actual Behavior
 non root user just get a spinner program never opens.
### logs state:
Jun 13 11:52:41 mint kernel: [3622667.411478] traps: keepassxc[1653] trap divide error ip:7f17e08aeeda sp:7fff610e8b50 error:0 in libQt5XcbQpa.so.5.5.1[7f17e0864000+e0000]
Jun 13 12:08:09 mint kernel: [3623594.861403] traps: keepassxc[17244] trap divide error ip:7f8709e16eda sp:7ffc4d428e50 error:0 in libQt5XcbQpa.so.5.5.1[7f8709dcc000+e0000]
Jun 13 12:11:46 mint kernel: [3623811.718961] traps: keepassxc[20900] trap divide error ip:7fb340356eda sp:7fff36a84650 error:0 in libQt5XcbQpa.so.5.5.1[7fb34030c000+e0000]
Jun 13 12:14:01 mint kernel: [3623947.467217] traps: keepassxc[23549] trap divide error ip:7f8100886eda sp:7fff7303cc40 error:0 in libQt5XcbQpa.so.5.5.1[7f810083c000+e0000]
Jun 13 12:20:19 mint kernel: [3624324.630946] traps: keepassxc[29798] trap divide error ip:7f43f5206eda sp:7ffe04f32640 error:0 in libQt5XcbQpa.so.5.5.1[7f43f51bc000+e0000]

### Context
KeePassXC - Version 2.6.6
Revision: 9c108b9

Qt 5.5.1
Debugging mode is disabled.

Operating system: Linux Mint 18.3
CPU architecture: x86_64
Kernel: linux 4.8.0-53-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- libgcrypt 1.8.1

**Comment by droidmonkey** [comment]
The error actually occurs in libQt5XcbQpa.so.5.5.1

**Comment by phoerious** [comment]
Please try the AppImage. You are running on Qt 5.5, so your underlying base system is probably Ubuntu Xenial, which is pretty much EOL.

**Comment by droidmonkey** [comment]
Gonna close this since it's not on us
