### ISSUE TITLE
Title bar icon showing poorly

### ISSUE THREAD

**Issue by ghost** [keepassxreboot/keepassxc#6629]
## Overview
[TIP]: On MacOS the title bar icon looks very resized = jaggy
[NOTE]: see screenshot

## Steps to Reproduce
[NOTE]:
1. Get MacOS version on a non-Retina display
2. Launch the app.
3. Observe :-)

## Expected Behavior
[NOTE]: custom sized, clean looking icon

## Actual Behavior
[NOTE]: see screenshot

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.6.6
Revision: 2.6.6

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS
Desktop Env: macOS
Windowing System: non-Retina output

**Comment by ghost** [comment]
![Bildschirmfoto 2021-06-13 um 16 48 20](https://user-images.githubusercontent.com/66566922/121825589-29824380-cc68-11eb-92dc-1eb492b60411.png)

**Comment by bonitoman** [comment]
On Mac and Retina Display, it is even worse on an inactive screen. There the icon is compressed vertically.

Icon on active screen (with icon type monochrome):
![Icon Mac on active window](https://user-images.githubusercontent.com/4063700/144113455-ad9c5ff4-7607-4ec7-8796-19703ceeac50.png)

Icon on inactive screen (with icon type monochrome):
<img width="45" alt="Icon Mac on inactive window" src="https://user-images.githubusercontent.com/4063700/144113472-c121edfa-4faf-4cba-8513-1dbd2621c44d.png">

**Comment by droidmonkey** [comment]
This is a qt bug, nothing we can do about it unfortunately.

**Comment by phoerious** [comment]
I wonder if this is somehow dependent on the macOS version. On my system, it isn't perfect and you can clearly see jagged edges on a scaled-up screenshot, but it's absolutely fine at normal sizes.

![image](https://user-images.githubusercontent.com/911270/144140803-d2b092a5-819f-4fe4-880f-f2f067b5a452.png)

**Comment by droidmonkey** [comment]
Clearly the rendering of the svg to whatever is causing artifacts and sizing problems.

**Comment by droidmonkey** [comment]
@phoerious is this still a problem?

**Comment by michaelblyons** [comment]
v2.6.6 On a retina screen, mine looks like @phoerius's, which I would not consider to be a problem. If I drag the window to an alternative screen, it looks like @coderslagoon's screenshot.

I also still see the squashed version of the system tray for inactive screens like @aheinzer.

**Comment by droidmonkey** [comment]
the squashed version is a Qt bug. Although it would seem like this is all a Qt bug.

**Comment by phoerious** [comment]
Hard to tell. Looks mostly fine to me on a Retina display at least.

**Comment by slagiewka** [comment]
I just updated from 2.7.1 to 2.7.4 and I can report that the [squashed icon](https://github.com/keepassxreboot/keepassxc/issues/6629#issuecomment-982944802) is now gone and it shows properly. It also seems as it's slightly smaller and it fits the menu bar perfectly. Previously it seemed a bit off compared to other icons 😉

**Comment by bonitoman** [comment]
As the original submitter of this ticket, I can confirm that the icons are now displayed correctly with version 2.7.4.
Thank you very much!
