### ISSUE TITLE
Segfault on window resize (Linux)

### ISSUE THREAD

**Issue by wohali** [keepassxreboot/keepassxc#6631]
## Overview

Resizing the window on a very high DPI monitor causes a crash, a segmentation fault with the following error:

```
qt.qpa.xcb: xcb_shm_create_segment() can't be called for size 17178820624, maximumallowed size is 4294967295
```

## Steps to Reproduce
1. Start keepassxc v2.6.6 on a monitor with a very high resolution such as 3840x2160
2. Un-maximize the default maximized window.
3. Use the window manager to resize the window.

## Expected Behavior
Resizing the window should not crash.

## Actual Behavior
Crash with:

```
qt.qpa.xcb: xcb_shm_create_segment() can't be called for size 17178820624, maximumallowed size is 4294967295
```

KeePassXC - Version 2.6.6
Revision: 9c108b9
Distribution: AppImage

Qt 5.15.2
Debugging mode is disabled.

Operating system: Debian GNU/Linux 11 (bullseye)
CPU architecture: x86_64
Kernel: linux 5.10.0-7-amd64

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- libgcrypt 1.8.1

Operating System: Linux
Desktop Env: fluxbox (no desktop environment at all)
Windowing System: X11

**Comment by droidmonkey** [comment]
This appears to be a Qt bug

**Comment by wohali** [comment]
FYI I note that the app always is coming up maximixed, and while I can un-maximize the app, the window stays at 3840x2160.

If I can work out how to get a core dump out of the app I'll happily post a gdb stacktrace.

**Comment by droidmonkey** [comment]
Probably directly related to fluxbox. This is definitely a qt problem since it is crashing in qt code. We won't be looking into this on our end. 

FWIW, have you seen this on other versions of KeePassXC?

**Comment by wohali** [comment]
Brand new with 2.6.6, wasn't seeing it with 2.6.4.

**Comment by phoerious** [comment]
Try starting the AppImage with
```
QT_QPA_PLATFORMTHEME= ./KeePassXC.*.AppImage
```

**Comment by wohali** [comment]
That didn't work, but this did:

```
QT_AUTO_SCREEN_SCALE_FACTOR=0 QT_SCALE_FACTOR=1 path/to/keepassxc
```

This results in an ugly UI, with incorrectly calculated widget sizes, unless the "classic" theme is selected - but that's a sacrifice I'm willing to make for now. I also did a full compile from `master` here, but ultimately it didn't prove necessary as I received the exact same error messages.

Sources I found that helped (the second link is especially informative as to how broken HiDPI is under Qt):

* https://www.linuxquestions.org/questions/slackware-14/calibre-5-8-1-on-current-seg-fault-qt-qpa-xcb-xcb_shm_create_segment-4175687591/
* https://bugreports.qt.io/browse/QTBUG-93067 (filed upstream with QT, apparently setting `Qt::AA_EnableHighDpiScaling` and `Qt::AA_UseHighDpiPixmaps` causes the issue, though commenting these out in `src/main.cpp` didn't resolve the issue)
* https://github.com/qutebrowser/qutebrowser/issues/5211#issuecomment-583682944

**Comment by droidmonkey** [comment]
Thanks for the report back. Closing this since it's obviously on Qt's side.
