### ISSUE TITLE
[Bug] 1 year expiration button issue in French

### ISSUE THREAD

**Issue by LetMeR00t** [keepassxreboot/keepassxc#6632]
Hi,

Everything is said on the title, it seems that there is an issue in the french language with the expiration button "1 year" as you can see on the screenshot.

I'm using KeepassXC v2.6.6

![image](https://user-images.githubusercontent.com/10530375/121858199-a6f49500-ccf6-11eb-9e6f-61e442310a9e.png)

Thank you

**Comment by orion78fr** [comment]
Note that this is fixed in the develop branch (7cb2991a)
![keepass](https://user-images.githubusercontent.com/8122888/121932157-d205d580-cd44-11eb-9227-6e428b02f241.JPG)

**Comment by droidmonkey** [comment]
This is a translation issue that needs to be fixed on transifex.com.
