### ISSUE TITLE
Handle username and password on different pages

### ISSUE THREAD

**Issue by dnai05** [keepassxreboot/keepassxc#6633]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
More sites have username and password fields on different pages. KeePassXC handles sites with username only but not this.

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )
![image](https://user-images.githubusercontent.com/85871268/121868119-328c1700-cd33-11eb-9269-d649fee91778.png)

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )

**Comment by droidmonkey** [comment]
Set the page as having username only fields in the browser extension settings. Some sites are just not possible to work with for one reason or another.
