### ISSUE TITLE
KeePassXC database gets completely corrupted and emptied-out when disk space fills up

### ISSUE THREAD

**Issue by kashyapc** [keepassxreboot/keepassxc#6634]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

First of all, thank you for KeePassXC.  Unfortunately, my experience today was utterly horrific:  

This morning I noticed my /home partition—where I keep the KeePassXC database file—was full; once I noticed it, I cleaned it up and made more space available.  Then I routinely logged into KeePassXC, but it failed with: `Error while reading the database: Failed to read database file`

Surprised, I ran `file /path/to/db`, and was aghast when I saw this!:

    $> file /home/user1/keepassx-1.kdbx 
    /home/user1/keepassx-1.kdbx : empty

    $> du -sh /home/user1/keepassx-1.kdbx 
    0	/home/user1/keepassx-1.kdbx 

The database file got _completely_ emptied out by KeePassXC. :-(

Now, fortunately, I take back-ups, and have a backup of the DB from 09March2021. So I restored that backup.  But, as you can imagine, there's still some damage, as I lost last 3 months of stored passwords.

------
I wondered if any _other_ Linux process could have done this overwriting; but it's unlikely. I guess what happened was KeePassXC tried to rewrite the database for "some reason" (which could be what, exactly?), and in the process bungled it up.

Why did KeePassXC overwrite the original file when there's no disk space?  The results are catastrophic.  A safer way could've been: when overwriting, use a _new_ DB file, and only when that file was written safely, then rename the older file to this new one.

But either way, this is really distressing, as you can imagine.

## Steps to Reproduce

I haven't reproduced this twice, as this is too cumbersome to try. But this is how I noticed it:

1. Take backup of your database file (e.g. `~/home/user1/keepassx-1.kdbx`)
2. Fill up your /home partition to max utilization
3. Try to log into KeePassXC
3. Hopefully it reproduces.

## Expected Behavior

The KeePassXC database file _not_ be corrupted!

## Actual Behavior

The KeePassXC database file gets completely emptied out and is rendered useless.

## Context
As noted earlier, my /home disk has was completely filled up.  And I cleaned it up when I noticed it.  I _think_ the time-window during which there was no space on the disk is when KeePassXC tried to overwrite the DB file.

## Version Info

- KeePassXC - ~~keepassx-2.0.3-11.fc33.x86_64~~

  [EDIT: I gave the unmaintained "keepassx" version accidentally as the RPM package was on my system; but I was indeed using KeePassXC; and here's the version: **keepassxc-2.6.4-2.fc33.x86_64**.  Sorry for the mix-up]

- Operating System: Linux; Fedora 33
- Desktop Env: GNOME
- Windowing System: Wayland

**Comment by droidmonkey** [comment]
> A safer way could've been: when overwriting, use a new DB file, and only when that file was written safely, then rename the older file to this new one.

That is exactly what we do.


> keepassx-2.0.3-11.fc33.x86_64

You are not running KeePassXC.

Sorry to hear about this but this wouldn't have been a problem if you were running KeePassXC. The original KeePassX stopped development around 2015 time frame.

**Comment by kashyapc** [comment]
Errr, I made a bad copy/paste mistake: I *was* using KeePassXC —I just pasted wrong package version :-(  I just had 'keepassx' package as well, sitting dormant.

This is the version of KeePassXC that I'm using:

keepassxc-2.6.4-2.fc33.x86_64

Please re-open this bug.

**Comment by kashyapc** [comment]
There's no conclusion yet here; I realize, a reproducer would be really be useful (but it's going to be really time-consuming to prepare one).

Some related discussion from the upstream IRC channel:

    < kashyap> droidmonkey[m]: Could it be possible that KeePassXC missed an error?
    < droidmonkey[m]> Qt would have missed it.  We just tell Qt to write the file, it figures out all the particulars including space
 
    < droidmonkey[m]> If you didn't actually save your database during the time the partition was 100% full then it couldn't have been us
    < droidmonkey[m]> Merely opening the database will not cause a write operation, it is opened as a read only operation
    < droidmonkey[m]> To confirm, do you have safe saves enabled in your settings?
    < kashyap> droidmonkey[m]: "Safely save database files" checkbox is enabled
    < droidmonkey[m]> That is the write file then rename into place.  It's an atomic transaction

**Comment by droidmonkey** [comment]
You should be able to reproduce by creating a very small ram disk container, mounting it, and fill it with random data and a database. 

dd /dev/random /mnt/test/fillerfile ....

**Comment by droidmonkey** [comment]
This appears to have been an anomaly and likely not caused by us given the total conversation above.

**Comment by wsowens** [comment]
I don't expect a fix or a reply here because this is outside KeePassXC's control. But I experienced the same issue and just want to document for anyone else who stumbles on page.

### Version Info
- KeePassXC - keepassxc.x86_64.2.6.4-2.fc33  
- Operating System: Linux; Fedora 33
- Desktop Environment: sway
- Windowing System: Wayland

### Description

I had a Wayland error log fill up all of the all of the disk space on my home partition while I had keepass open. I tried saving, got the "can't write to disk" warning and then was prompted to remove the safety lock. I _stupidly_ said yes because I didn't realize my home partition was full, tried to save again, of course no luck. Ultimately had to hard reboot, which seems to have cleared the backup file in /tmp in the process. The original file is totally wiped:
```
$> file ~/database.kdbx
/home/user1/database.kdbx: empty

$ du -sh ~/database.kdbx
0       /home/user1/database.kdbx
```

As I said above, I don't expect a response from anyone here. Thank you for your work on this project, it's really be useful to me!

**Comment by phoerious** [comment]
Ouch. Did you use one of the alternate save modes? The standard mode should create a temporary hidden savefile next to the original KDBX file and rename it only after the save process was successful.
