### ISSUE TITLE
Auto-Type presets in dropdown menu

### ISSUE THREAD

**Issue by apfelchips** [keepassxreboot/keepassxc#6635]
## Summary
Add some common defaults for the Auto-Type Field via a dropdown menu, simmilar to how autocompletion of window title: works
![image](https://user-images.githubusercontent.com/6919384/121885883-38b6cf00-cd04-11eb-8ff2-d33670d97f0f.png)

## Examples

__Normal__
`{CLEARFIELD}{USERNAME}{TAB}{CLEARFIELD}{PASSWORD}{ENTER}`

__Normal + TOTP__
`{CLEARFIELD}{USERNAME}{TAB}{CLEARFIELD}{PASSWORD}{ENTER}{DELAY 2500}{TOTP}{ENTER}`

__Multistep__
`{CLEARFIELD}{USERNAME}{ENTER}{DELAY 2500}{CLEARFIELD}{PASSWORD}{ENTER}`

__Multistep + TOTP__
`{CLEARFIELD}{USERNAME}{ENTER}{DELAY 2500}{CLEARFIELD}{PASSWORD}{ENTER}{DELAY 2500}{CLEARFIELD}{TOTP}{ENTER}`

## Context
Currently I have to copy&paste these values from a note entry, would be nice if they'd be suggested in a dropdown menu for easy access

Also why is `{USERNAME}{TAB}{PASSWORD}{ENTER}` the default for auto-type, why not `{CLEARFIELD}{USERNAME}{TAB}{CLEARFIELD}{PASSWORD}{ENTER}` users might not know about the `{CLEARFIELD}` feature

**Comment by droidmonkey** [comment]
You can make that your own default by changing the root group's default Auto-Type sequence. 

Good idea on the commonly used options.

**Comment by apfelchips** [comment]
I already did that on my root Group. 👍.
I'm suggesting to make it default for everyone, since it's pretty non invasive and should be useful for everyone , though I have experienced problems with some oddball login forms, so maybe just make it a suggestion and keep the default.

**Comment by droidmonkey** [comment]
We will focus on #8276 instead
