### ISSUE TITLE
Export selected database entries to CSV/HTML

### ISSUE THREAD

**Issue by Oliver-Habersetzer** [keepassxreboot/keepassxc#6636]
## Summary

Add a feature where the user can select either some entries or groups which are then exported via `Database->Export selected->CSV` or `->HTML`.
Alternatively, after clicking `CSV` or `HTML` in the current implementation, a popup with a tree view for selecting entries and groups could show up.
For all selected groups, all child groups and entries may be exported.

## Context

In my usecase, I sometimes have to send my colleagues some of our passwords but they don't use keepass for some reason ;). So I can't send them the keepass file.
I'd rather not export everything, then open the CSV in a text editor to remove my personal stuff carefully (without missing anything hopefully). I fear the initial data might leave traces on my drive which could be restored with data recovery techniques.
I'm aware that multiple keepass databases could be a solution here but not all of my colleagues are allowed to have all of the logins - so the problem still persists even if I did that.

**Comment by droidmonkey** [comment]
Duplicate request, thank you

**Comment by Oliver-Habersetzer** [comment]
I'm sorry about that - I didn't find the issue. Sorry for wasting your time

**Comment by droidmonkey** [comment]
#1940 for reference
