### ISSUE TITLE
Under Firejail, links don't open in browser

### ISSUE THREAD

**Issue by BillDietrich** [keepassxreboot/keepassxc#6637]
## Overview
If I run KeePassXC under Firejail, I can open the database and all looks well.  But then clicking on the URL associated with an entry, or highlighting the entry and pressing Ctrl+Shift+U to open the link, does nothing.

## Steps to Reproduce
1. On Linux CLI, run "firejail keepassxc DBNAME"
2. Database opens.
3. Select an entry.
4. Click on URL associated with entry.
5. On CLI, see message "Unable to detect a web browser to launch 'http...'"

## Expected Behavior
URL should be sent to browser, which should open it.

## Actual Behavior
Error message as given above.

## Notes:
KeePassXC and Firefox are natively installed; no appimage, snap, flatpak.
No KP browser extension installed or browser integration enabled.
KP and links etc work fine if Firejail not used.

## Environment:
KeePassXC - 2.6.4 native installed
KeePassXC - Version 2.6.4
Revision: 34a78f0

Qt 5.15.2
Debugging mode is disabled.

Operating system: Fedora 34 (KDE Plasma)
CPU architecture: x86_64
Kernel: linux 5.12.9-300.fc34.x86_64

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- libgcrypt 1.9.3-unknown

Operating System: Linux Fedora 34
Desktop Env: KDE
Windowing System: X11

Firejail: version 0.9.64.4

I tried all kinds of tweaks to the Firejail profile for KeePassXC, nothing fixed the problem.  But I'm no expert at Firejail.

**Comment by droidmonkey** [comment]
You need to allow access to open a url. This isn't something we provide support for.

**Comment by BillDietrich** [comment]
Yes, I'm finding ways to fix it on the Firejail side.  https://github.com/netblue30/firejail/issues/3329
