### ISSUE TITLE
2.6.6 release wont open on macOS Catalina

### ISSUE THREAD

**Issue by dbr** [keepassxreboot/keepassxc#6638]
## Overview
- KeepassKC 2.6.6 appears to require macOS 11 (Big Sur) - "You have macOS 10.15.7. The application requires macOS 11.0 or later."
- 2.6.0 ran on macOS 10.15 (Catalina)

This seems surprising as OS support was dropped in a patch version, and not mentioned in the release notes - which makes me think it may be accidental?

## Steps to Reproduce
- Try to open 2.6.6 on macOS Catalina

## Expected Behavior
I'd expect either:

- KeepassKC would run on Catalina
- Or, the dropping of support to be mentioned in the release notes (and probably happen in a 2.7 release rather than a patch)

## Context
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.6.0 and 2.6.6

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS 10.15

**Comment by droidmonkey** [comment]
@phoerious

**Comment by phoerious** [comment]
What architecture are you on?

**Comment by dbr** [comment]
Oh! This is an old-ish Intel Macbook Pro (not M1)

**Comment by varjolintu** [comment]
Strange. I have no problems opening 2.6.6 with Catalina (10.15.7) or Mojave (10.14.6).

**Comment by phoerious** [comment]
Make sure you have the latest build. Before we announced the release we had a broken build that has been replaced.

**Comment by dbr** [comment]
Gah sorry, my mistake. I had downloaded the wrong DMG - I misread `arm64` as `amd64` (when I actually wanted the `x86_64` DMG)
