### ISSUE TITLE
Attribute preview window is empty

### ISSUE THREAD

**Issue by lamejack** [keepassxreboot/keepassxc#6639]
## Overview
Attribute preview window is empty when application is set to Russian language in version 2.6.6. English version is working correctly. 
![Снимок экрана 2021-06-15 182756](https://user-images.githubusercontent.com/29841064/122037729-74868d00-ce07-11eb-8284-74a3b027ea4f.png)

## Steps to Reproduce
1. Change language to Russian
2. Open database
3. Open attributes preview in advanced menu

## Expected Behavior
Attribute preview should be filled.

## Actual Behavior
Attribute preview window is empty.

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.6.6

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 10 32 bit

**Comment by droidmonkey** [comment]
The translator blew away critical pieces of the translation, I just reverted it. This isn't a problem in develop branch since we completely overhauled this dialog.
