### ISSUE TITLE
Probleme d'ouverture de mon fichier KDBX

### ISSUE THREAD

**Issue by thierry956** [keepassxreboot/keepassxc#6640]
## Overview
Bonjour , 
Avant je vous parle en français
Mon probleme est que je n'arrive plus à ouvrir mon fichier de base ,j'ai la version 2.6.6 et  çà affiche "erreur de lecture de la base de donnée .Le fichier de la base de donnée pourrait etre corrompu

## Steps to Reproduce

  Je viens vers vous car j'ai un gros soucis ,c'est que mon fichier .kdbx ne s'ouvre plus suite à la mise à jour à 2.6.4 depuis la semaine dernière et j'ai essayé de réinstaller la version 2.6.1 et il me dit que le fichier est corrompu alors qu'il fonctionnait très bien.Pourriez vous me donner une solution car toutes mes données sont à l'intérieur et depuis plus de 3 ans que je suis avec vos logiciel auquel j'ai une entière confiance sauf que là je suis bien paniqué car j'ai toujours fait une copie sur mes 2 disques durs  et aucun des 2 fichiers ne s'ouvrent.Je compte sur vous pour résoudre mon problème.

## Expected Behavior
[NOTE]: # J'aimerai récupérer mes mots de passe qui sont très important 

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION 2.6.6
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows/
Desktop Env: Gnome/KDE/XFCE/Mate/Cinnamon
Windowing System: X11/Wayland

**Comment by droidmonkey** [comment]
Are you using a key file or yubikey to open your database?

Are you storing your database on a USB thumb drive?

Are you sure you are typing your password correctly? 

Have you changed your credentials recently?

**Comment by thierry956** [comment]
Bonjour,non j'ai un seul mot de passe qui fort.Je n'ai jamais utilisé de
clé USB pour mettre mes données dessus .Concernant mon mot de passe ,j'ai
toujours eu le même depuis plus de 10 ans ans avec d'autres mots de passe
comme Passbox aparavant.
Je n'ai jamais changé mon mot de passe qui est assez grand et fort
.J'espère que cela pourra vous aider et je compte sur vous pour résoudre ce
problème .Je vous remercie à l'avance

Le mar. 15 juin 2021 à 18:24, Jonathan White ***@***.***> a
écrit :

**Comment by droidmonkey** [comment]
There is nothing we can do to actually help you. I hope you kept backups of your database.
