### ISSUE TITLE
KeePassxc changes the DB filename when I use the app in Ubuntu with Google drive

### ISSUE THREAD

**Issue by pic172** [keepassxreboot/keepassxc#6641]
## Overview
I'm using Pop_OS and the file system has a network drive for Google Drive.  I'm using G-Drive to sync the KeePass DB to all my devices, but when I use KeePass to open a DB in G-Drive on Ubuntu, it changes the file name to a long alpha numeric string when I close the file. 

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. sync GNOME with G-Drive
2. open KeePassxc and opena DB from the network G-drive location
3. Make any changes to the DB and save the file
4. the file will be renamed with a long alphnumeric string.  

## Expected Behavior
I expect the DB filename to remain unchanged. 

## Actual Behavior
Changes the file name

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.1
Revision: 9a35bba

Qt 5.14.2
Debugging mode is disabled.

Operating system: Pop!_OS 20.10
CPU architecture: x86_64
Kernel: linux 5.11.0-7614-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (only unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.5

**Comment by droidmonkey** [comment]
This is fixed for next major version #6594
