### ISSUE TITLE
KeePassXC Not Filling in Username or Password Fields

### ISSUE THREAD

**Issue by dejaboom** [keepassxreboot/keepassxc#6642]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

## Brief Summary
Stored my login credentials for my company's Salesforce website so it would autofill.
URL:  https://procurementpartners.lightning.force.com/lightning/page/home

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Go to the URL referenced above & no username or password autofills in the appropriate fields

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
The username & password should fill in automatically since they are stored in my database.  All other sites I have stored in my KeePassXC database autofill as they should.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Nothing autofills; no username nor password

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION 2.6.6

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 10 Home (64-bit)

**Comment by droidmonkey** [comment]
Make sure the url for the entry is actually: https://procurementpartners.my.salesforce.com

**Comment by dejaboom** [comment]
I have updated the URL as you suggested, however the password is still not filling in the related field (nothing fills in for that field).  Please advise.

**Comment by dejaboom** [comment]
> Make sure the url for the entry is actually: https://procurementpartners.my.salesforce.com

@droidmonkey I have updated the URL as you suggested, however the password is still not filling in the related field (nothing fills in for that field).  Please advise.

**Comment by droidmonkey** [comment]
I tested it on my end and it worked. Have you denied the credentials from being sent to the browser?

**Comment by dejaboom** [comment]
@droidmonkey I don't know how I would deny credentials from being sent to the browser.  I have tested this on both Google Chrome (version 91.0.4472.106 (Official Build) (64-bit)) & Opera (version 77.0.4054.80) with both browsers using the KeePassXC-Browser extension (version 1.7.8.1).  I have attached PDFs of screenshots of both browsers' about page, displaying their version as well as the KeePassXC-Browser extension for each with the settings.  I am also including PDFs of the screenshots of what I am receiving on the login page for Salesforce in each browser (I edited / cut out my username for obvious security reasons, but that field is the only one showing up).  And finally, I am also including a PDF of the screenshots of my KeePassXC 2.6.6 application's settings only (don't worry, no database info of mine is included).
[Google Chrome & KeePassXC-Browser Extension Settings.pdf](https://github.com/keepassxreboot/keepassxc/files/6667717/Google.Chrome.KeePassXC-Browser.Extension.Settings.pdf)
[Google Chrome - Salesforce Login Page Results.pdf](https://github.com/keepassxreboot/keepassxc/files/6667718/Google.Chrome.-.Salesforce.Login.Page.Results.pdf)
[Opera & KeePassXC-Browser Extension Settings.pdf](https://github.com/keepassxreboot/keepassxc/files/6667719/Opera.KeePassXC-Browser.Extension.Settings.pdf)
[Opera - Salesforce Login Page Results.pdf](https://github.com/keepassxreboot/keepassxc/files/6667720/Opera.-.Salesforce.Login.Page.Results.pdf)
[KeePassXC 2.6.6 (Settings Only).pdf](https://github.com/keepassxreboot/keepassxc/files/6667721/KeePassXC.2.6.6.Settings.Only.pdf)

**Comment by droidmonkey** [comment]
I just tested it again, worked pretty good. You may have to choose custom login fields, make sure you are totally logged out (no saved username), or enable username-only detection in the browser extension settings.

![image](https://user-images.githubusercontent.com/2809491/122391557-25447780-cf41-11eb-8672-07e0c40871b6.png)
