### ISSUE TITLE
List menu on more than one screen

### ISSUE THREAD

**Issue by Pioxis** [keepassxreboot/keepassxc#6643]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
![Zrzut ekranu z 2021-06-16 09-40-26](https://user-images.githubusercontent.com/12051229/122179438-cff85f80-ce87-11eb-96da-8e5e9948ed5c.png)

[NOTE]: # ( Give a BRIEF summary about your problem )
If I have my screens set in positions like as at the screenshot then list menu is appearing to the main screen on the left. Not to the left screen position.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Set screens one higher than main screen in settings of screens on Ubuntu
2. Open KeePassXC (from SNAP)
3. Press one of menu buttons to open some list

## Additional info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION 2.6.6
Revision: REVISION 9c108b9

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: Gnome
Windowing System: X11

**Comment by droidmonkey** [comment]
This is a qt bug
