### ISSUE TITLE
Wrong 2fa TOTP key on Win10x64

### ISSUE THREAD

**Issue by dark46** [keepassxreboot/keepassxc#6646]
## Steps to Reproduce
1.  Add standart rfc6238 secret key on Win10x64 and (mobile or macos) version KeepassXC

## Expected Behavior
Generated key on Win10x64 is match with MacOS and Android version Keepass.

## Actual Behavior
Generated 2fa key from Win10x64 different  Macos or Android version.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.6.6
Revision: 9c108b9

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 10 x64

Base file .kdbx is match on win/macos/android

**Comment by droidmonkey** [comment]
Sync your computer time
