### ISSUE TITLE
Unappropriate config directory on macOS

### ISSUE THREAD

**Issue by ammnt** [keepassxreboot/keepassxc#6647]
Hello, Dear Team!😊

Thank you for the great app! I use the application for macOS and noticed that the configuration file `keepassxc.ini` is stored in the caches directory:
`~/Libraries/Caches/KeePassXC`

This is not very correct because when the cache is cleaned manually or by third-party programs, all settings are reset. Please think about moving it to a more appropriate directory. For example:
`~/Libraries/Preferences/KeePassXC`

Thank you!
Cheers!🤟🏼

**Comment by michaelk83** [comment]
Related to #6626 and #6506 for Linux. Default location is `~/.cache` accroding to those issues, not `~/.config`.

**Comment by Okeanos** [comment]
The path prefix is actually `~/Library` (not `~/Libraries`). That aside the `~/Library/Caches/KeePassXC/keepassxc.ini` only holds runtime information such as "Last Active Database" and "Check for Updates Next Check". A valid use case.

The actual configuration, i.e. what a user would change via the preferences, semi-correctly resides in `~/Library/Application Support/KeePassXC/keepassxc.ini`. 

Interestingly, there's also a file at `~/Library/Preferences/org.keepassxc.keepassxc.plist` where one might expect the actual user configuration, however, that appears to only contain macOS specific information about the (last) window location.

I think it would make sense to move `~/Library/Application Support/KeePassXC/keepassxc.ini` to `~/Library/Preferences/KeePassXC/keepassxc.ini` and not use `Application Support` at all – that's usually reserved for additional/complementary stuff like plugins, style/theme information, or other additional resources that may supplement the application.

This would centralise the configuration at the correct base directory and also keep macOS specifics separate from the cross-platform preferences.

**Comment by droidmonkey** [comment]
Qt kinda screws up here because they define the "AppDataLocation" on Windows as the roaming appdata folder, and on macOS it is the application support folder. They define "AppConfigLocation" as the preferences folder on macOS, but the local appdata folder on Windows.

At the end of the day it doesn't matter where the config settings are stored on macOS, both preferences and application support are treated equally by the operating system.

We aren't going to make any changes here at this time.

**Comment by phoerious** [comment]
The file in Caches are your local settings. The actual application settings are in the right place.
