### ISSUE TITLE
Segmentation fault when launching as snap on Manjaro

### ISSUE THREAD

**Issue by cnmicha** [keepassxreboot/keepassxc#6649]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
When launching the snap version, it crashes with a segmentation fault.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. `# snap install keepassxc`
2. `$ snap run keepassxc`

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
No crash on application start

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

A segmentation fault happens before the window opens.

```
$ snap run keepassxc
WARNING: cgroup v2 is not fully supported yet, proceeding with partial confinement
Gtk-Message: 01:50:50.270: Failed to load module "xapp-gtk3-module"

(keepassxc:11647): dbind-WARNING **: 01:50:50.306: Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-5VZ3BGI5JF: No such file or directory
Gtk-Message: 01:50:50.421: Failed to load module "canberra-gtk-module"
Gtk-Message: 01:50:50.428: Failed to load module "canberra-gtk-module"
Qt: Session management error: None of the authentication protocols specified are supported
Fontconfig warning: FcPattern object weight does not accept value [40 210)
Segmentation fault
```

## Context
[NOTE]: # ( Give us any additional information you may have. )

Snap version 2.6.6 and 2.6.5 have the issue. AppImage and the version packaged for Manjaro work fine. Other snaps work fine as well.

```
$ uname -a
Linux TP-M 5.10.42-1-MANJARO #1 SMP PREEMPT Thu Jun 3 14:37:11 UTC 2021 x86_64 GNU/Linux
```

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.6.6, 2.6.5 (snap packages only)

[NOTE]: # ( Pick choices based on your environment )
Operating System: Manjaro Linux
Desktop Env: Gnome
Windowing System: X11

**Comment by droidmonkey** [comment]
see #5150

**Comment by cnmicha** [comment]
I already tried that, but unfortunately without luck. Still a segmentation fault.

**Comment by droidmonkey** [comment]
If you cleared your fontcache then there is not much else we can do. Recommend just using the appimage or ppa.
