### ISSUE TITLE
segmentation fault when merging without existing database (GUI)

### ISSUE THREAD

**Issue by initbar** [keepassxreboot/keepassxc#665]
## Expected Behavior

Not merge when there is no opened database or handle segfault.

## Current Behavior

![log](https://user-images.githubusercontent.com/12630151/27524634-c7d05674-5a04-11e7-9d3d-c153b4369859.png)

## Steps to Reproduce (for bugs)
1. Start keepassxc
2. Click "Database" -> "Merge from KeePassX database"
3. Open existing keepass database.

## Environment
* **Linux** - `Linux xinu 4.10.0-24-generic #28-Ubuntu SMP Wed Jun 14 08:14:34 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`

* **KeepassXC** - `keepassxc 2.1.4-stable`

![log2](https://user-images.githubusercontent.com/12630151/27524656-0b29d328-5a05-11e7-89d0-4b648bfc2862.png)

**Comment by phoerious** [comment]
Please try again with KeePassXC 2.2.0 and report back if the problem still exists there.
