### ISSUE TITLE
App Images for Raspberry Pi armhf and arm64

### ISSUE THREAD

**Issue by SmithTech00** [keepassxreboot/keepassxc#6651]
Can you add App Images for Raspberry Pi armhf and arm64?

Thank You,
John Smith

## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )

**Comment by droidmonkey** [comment]
The snap package includes arm builds.

**Comment by droidmonkey** [comment]
Use the flatpak distribution.

**Comment by mlavi** [comment]
1. https://keepassxc.org/download/#linux
2. Click on the turn down arrow for "Other Official Linux Packages" to reveal Snap and Flatpak instructions
3. More detail: https://snapcraft.io/keepassxc and https://flathub.org/apps/org.keepassxc.KeePassXC
