### ISSUE TITLE
Set-up-Build-Environment-on-macOS wikipage 

### ISSUE THREAD

**Issue by shemeshg** [keepassxreboot/keepassxc#6655]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
IT IS NOT ABUG, just something to make Mac users easier if added to the Wiki page

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. brew install libqrencode
2. Open CtCreator, it will not find the .h file
3. Install using vcpkg and all is ok

* It is only when using the QtCreator, The deployment script works perfectly fine *

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
1. Open CtCreator and building project would be ok

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
1. when using the homebrew lib "libqrencode", the FIND_PACKAGE did not worked correctly.

# Here it is how it worked for me
```
% git clone https://github.com/keepassxreboot/keepassxc.git
% cd keepassxc
```
- Add to QtCreator->Projects->initial cmake parameters
```  
-DCMAKE_TOOLCHAIN_FILE=<vcpkg folder>/scripts/buildsystems/vcpkg.cmake
```
 - Close QtCreator
```
% brew install cmake

% brew install argon2
% brew install asciidoctor
% brew install libyubikey
% brew install ykpers
% brew install libgcrypt
% brew install quazip
% brew install botan
```
- create  vcpkg.json at root of project folder
or manually vcpkg install "libqrencode" "libsodium"
```
{
  "name": "example",
  "version-string": "0.0.1",
  "dependencies": [
    "libqrencode","libsodium"
  ]
}
```
- ReOpen QtCreator

**Comment by droidmonkey** [comment]
It works fine for me, make sure you have the right symlinks setup after the brew install. Libsodium is not needed anymore for develop branch.
