### ISSUE TITLE
KeepassXC 2.6.6 not verified on MacOS 11.4 Intel

### ISSUE THREAD

**Issue by mpasquazzo** [keepassxreboot/keepassxc#6656]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Installing XkeepassXC on my mac OS 11.4 INtel I get a popup windows when trying to copy the exceutable in the application directory
![kepassCerr](https://user-images.githubusercontent.com/86224227/122722039-9356aa80-d271-11eb-856a-652900cd90e8.jpg)

2. The error is: KeepassXC is damaged and cannot be installed you should move in the waste basket
3. 

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.6.6

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS 11.4 Big Sur

**Comment by droidmonkey** [comment]
Re download the dmg. Make sure you are installing intel on Intel and arm on m1.

**Comment by mpasquazzo** [comment]
Thanks for your answer.

I downloaded this: KeePassXC-2.6.6-x86_64.dmg I think it's correct, isn't it?

Regards

**Comment by mpasquazzo** [comment]
I resolved just asking my mac to open the downloaded app, but the message I get was wrong.

Your answer was not correct. you have to change something in ur code to let the mac message clear

Thanks for your great sw but not easy to install

Regards

**Comment by droidmonkey** [comment]
That is not true at all, sorry you had trouble though
