### ISSUE TITLE
In the search results view, the password field is not masked.

### ISSUE THREAD

**Issue by michalklimowicz** [keepassxreboot/keepassxc#6657]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Search for any record from the database
2. Display of password field must be enabled (PPM on the column list)
3. The password is displayed in plain text and the login is masked.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
The password should be masked

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
The password is displayed in plain text in the search results view. The same problem occurs in the normal database results view.

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.6.6
Revision: 9c108b9

[NOTE]: # ( Pick choices based on your environment )
Operating system: Windows 10 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.19043

**Comment by droidmonkey** [comment]
View menu -> uncheck show password
