### ISSUE TITLE
Autotype does not work on Ubuntu wayland

### ISSUE THREAD

**Issue by RHOOPH** [keepassxreboot/keepassxc#6658]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
Auto-Type does not work on ubuntu 21.04 when widowing system is set to Wayland. However when set to x11 , works as expected.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Select an entry
2. Hit Auto-Type(either UI button or Keyboard Shortcut)

## Expected Behaviour
[NOTE]: # ( Tell us what you expected to happen )
1. Minimize KeepassXC window and type out the entry.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
1. Minimizes KepassXC window and does nothing.

## Context
[NOTE]: # ( Give us any additional information you may have. )
Probably has something to do with how Wayland treats input devices like keyboard/touchpad.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.6
Revision: 9c108b9
Distribution: Snap

Qt 5.9.5
Debugging mode is disabled.

Operating system: Ubuntu Core 18
CPU architecture: x86_64
Kernel: linux 5.11.0-18-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- libgcrypt 1.8.1

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux/Ubuntu 21.04
Desktop Env: Gnome 3.38.5
Windowing System: Wayland

**Comment by fabianski7** [comment]
https://github.com/keepassxreboot/keepassxc/issues/2281
