### ISSUE TITLE
AppImage doesn't run on Fedora 25; version `Qt_5.9' not found

### ISSUE THREAD

**Issue by wjt** [keepassxreboot/keepassxc#666]
## Expected Behaviour

```
$ chmod +x ./Downloads/KeePassXC-2.2.0-x86_64.AppImage
$ ./Downloads/KeePassXC-2.2.0-x86_64.AppImage
# app runs
```

## Current Behaviour

```
$ ./Downloads/KeePassXC-2.2.0-x86_64.AppImage
keepassxc: /lib64/libQt5Core.so.5: version `Qt_5.9' not found (required by keepassxc)
```

Perhaps it is using my system Qt rather than the bundled one?

## Steps to Reproduce (for bugs)

1. Use a Fedora 25 system
2. [Download official AppImage](https://keepassxc.org/download)
3. `chmod +x ./Downloads/KeePassXC-2.2.0-x86_64.AppImage`
4. `./Downloads/KeePassXC-2.2.0-x86_64.AppImage`

## Context

Although KeepAssXC is packaged for Fedora (and the package works), I saw it had an AppImage and wanted to try it. The premise of AppImage is “Linux apps that run anywhere”, so perhaps this one is not built correctly?
## Your Environment

* KeePassXC version/commit used: 2.2.0-x86_64 (can't check Help/About, app doesn't run)
* Qt version (e.g. Qt 5.3): ```rpm -qf /lib64/libQt5Core.so.5``` → ```qt5-qtbase-5.7.1-16.fc25.x86_64``` but I believe the AppImage is meant to bundle its own dependencies?
* Compiler (e.g. Clang++3.6.0): n/a
* Operating System and version: Fedora 25 x86_64

**Comment by phoerious** [comment]
I can confirm the problem. Will try to fix it asap. Not sure why Qt 5.9 isn't part of the AppImage. Probably some build script bug.

**Comment by phoerious** [comment]
The problem is an outdated path in the AppImage startup script. In the meantime, you can run it like is as a workaround:

```
LD_LIBRARY_PATH="../opt/qt59/lib" ./KeePassXC-2.2.0-x86_64.bin
```

**Comment by wjt** [comment]
Yep, `LD_LIBRARY_PATH="../opt/qt59/lib" ./Downloads/KeePassXC-2.2.0-x86_64.AppImage` works

**Comment by kronos29296** [comment]
I have the same problem in Ubuntu 17.04. Hope it gets fixed soon.

**Comment by phoerious** [comment]
I updated the AppImage. Can you please test it and report back?

**Comment by kronos29296** [comment]
Works fine now

**Comment by phoerious** [comment]
Great!
