### ISSUE TITLE
Suggest existing string field names when adding new string fields

### ISSUE THREAD

**Issue by neatgz** [keepassxreboot/keepassxc#6660]
## Summary

Many Items had String Fields, and most of them had the same String Field Names, such as “Two-factor Security SMS number”, “Payment password(different from Login Password)”, “Sync Security keys”, “Two-factor Recovery codes” and so on.

Every time when I add a new Item and click the Add String Field button, I have to fill in the same Field Name again and again.
This is so inconvenient!

## Examples

Keepass works well in this regard, here is the screenshot. But I really want to use Keepass XC. That is why I fill in the Feature Request.
![Snipaste_2021-06-23_08-46-37](https://user-images.githubusercontent.com/22790906/123019109-68e82700-d402-11eb-8503-a015ccdb286d.png)

## Context

How about to do like this:
When I add a new Item and click the Add String Field button. then, I can fill in a new Name or Choose an old Name that Old Items already had.
Thanks a lot!

**Comment by droidmonkey** [comment]
Duplicate of #5502
