### ISSUE TITLE
keepassxc will not start, no errors given

### ISSUE THREAD

**Issue by dmw73** [keepassxreboot/keepassxc#6661]
## Overview
The keepassxc application does not launch, either from command-line or from KDE menu.  
Have also tried the app image: KeePassXC-2.6.6-x86_64.AppImage, same thing.
Not seeing any error messages.

## Steps to Reproduce
1. click Keepassxc icon from KDE menu
2. nothing happens
3. run command keepassxc from CLI
4. nothing happens

## Expected Behavior
Application should launch

## Actual Behavior
Absolutely nothing happens!

## Context
It used to work on this system.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC 2.6.6
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux, openSUSE Tumbleweed 20210611
Desktop Env: KDE Plasma 5.22.0
Windowing System: X11  
Kernel: kernel 5.12.4-2

**Comment by droidmonkey** [comment]
Definitely something wrong with your system. Without error messages or anything we cannot assist. Closing unless provided.

**Comment by droidmonkey** [comment]
Definitely something wrong with your system. Without error messages or anything we cannot assist. Closing unless provided.

**Comment by dmw73** [comment]
I need some help to perform some troubleshooting or gathering of helpful information.  I don't know what else to provide; there is zero output.  Please don't close this out.  I have a bunch of credentials locked in the database that I can't open.  This is urgent.

**Comment by droidmonkey** [comment]
Try the snap or flatpak deployment? Use a Linux live boot image? Another computer? 

We cannot assist you without data, we don't have a clue where to start since this is only happening on your system.
