### ISSUE TITLE
keepassxc will not start, no errors given

### ISSUE THREAD

**Issue by dmw73** [keepassxreboot/keepassxc#6662]
**I am reposting this because the first post was prematurely closed out.  Please do not close this ticket until we can have some dialog about what to do here.  I need some help to perform some troubleshooting or gathering of helpful information. I don't know what else to provide; there is zero output. Please don't close this out. I have a bunch of credentials locked in the database that I can't open. This is urgent.**

Overview

The keepassxc application does not launch, either from command-line or from KDE menu.
Have also tried the app image: KeePassXC-2.6.6-x86_64.AppImage, same thing.
Not seeing any error messages.
Steps to Reproduce

    click Keepassxc icon from KDE menu
    nothing happens
    run command keepassxc from CLI
    nothing happens

Expected Behavior

Application should launch
Actual Behavior

Absolutely nothing happens!
Context

It used to work on this system.

KeePassXC 2.6.6
Revision: REVISION

Operating System: Linux, openSUSE Tumbleweed 20210611
Desktop Env: KDE Plasma 5.22.0
Windowing System: X11
Kernel: kernel 5.12.4-2

**Comment by dmw73** [comment]
Ran keepassxc from gdb.  Not much info.  What else to try?

```
[New Thread 0x7ffff2cc8640 (LWP 31040)]
Downloading separate debug info for /lib64/libXcursor.so.1...
Downloading separate debug info for /lib64/libXrender.so.1...
Downloading separate debug info for /lib64/libXfixes.so.3...
Downloading separate debug info for /lib64/libQt5QuickControls2.so.5...
Downloading separate debug info for /home/shamrock/.cache/debuginfod_client/94bbf01689d3b0e6cff49499e1eb545c1d395488/debuginfo...
Downloading separate debug info for /lib64/libQt5X11Extras.so.5...
Downloading separate debug info for /lib64/libQt5Xml.so.5...
Downloading separate debug info for /lib64/libcanberra.so.0...
Downloading separate debug info for /lib64/libQt5TextToSpeech.so.5...
Downloading separate debug info for /lib64/libdbusmenu-qt5.so.2...
Downloading separate debug info for /lib64/libwayland-client.so.0...
Downloading separate debug info for /lib64/libQt5Quick.so.5...
Downloading separate debug info for /lib64/libQt5Qml.so.5...
Downloading separate debug info for /lib64/libQt5QuickTemplates2.so.5...
Downloading separate debug info for /lib64/libacl.so.1...
Downloading separate debug info for /lib64/libQt5PrintSupport.so.5...
Downloading separate debug info for /lib64/libQt5WaylandClient.so.5...
Downloading separate debug info for /lib64/libvorbisfile.so.3...
Downloading separate debug info for /lib64/libltdl.so.7...
Downloading separate debug info for /lib64/libffi.so.8...
Downloading separate debug info for /lib64/libQt5QmlModels.so.5...
Downloading separate debug info for /lib64/libwayland-cursor.so.0...
Downloading separate debug info for /lib64/libvorbis.so.0...
Downloading separate debug info for /lib64/libogg.so.0...
Downloading separate debug info for /usr/lib64/qt5/plugins/platforminputcontexts/libibusplatforminputcontextplugin.so...
[New Thread 0x7fffebfff640 (LWP 31792)]
Cannot find user-level thread for LWP 29357: generic error
(gdb) 
```

**Comment by dmw73** [comment]
From CLI:
KeePassXC-2.6.6-x86_64.AppImage  does not launch, and no output is given.
KeePassXC-2.6.0-x86_64.AppImage  does not launch, and no output is given.
**KeePassXC-2.5.0-x86_64.AppImage DOES launch and acts perfectly fine.**

**Comment by droidmonkey** [comment]
Since the 2.5.0 appimage works for you just use that until you figure out why the other ones are failing. We do not provide customer support and this isn't a customer service desk. If you can isolate why this issue is occurring in your specific environment then maybe we can fix it.

You can also use the original keepass2 application to open your database, we are fully compatible.

**Comment by droidmonkey** [comment]
Another thing that might be happening is you have the tray icon enabled, minimize on startup enabled, and minimize to system tray enabled. It could be starting fine but "hidden" in your tray. Delete your `~/.cache/keepassxc/keepassxc.ini` and `~/.config/keepassxc/keepassxc.ini`

**Comment by ObserverOfTime** [comment]
I had the same issue on KDE with v2.6.4 from the Arch repos but it seems to have been solved after a reboot. :thinking:

**Comment by dmw73** [comment]
Yes I had removed the cache and config directories, also tried rebooting.  And verified that when launched, it does not appear minimized.  It is truly strange behavior.  No other applications on my system behave in that manner.  And keepassxc used to work fine.  I have a stock openSUSE Tumbleweed machine, no weird customization.    I would like to provide some sort of error log or debugging info, but I am unsure of how to generate it.  I was hoping that someone could tell me how to generate logging.  I would be happy to post this to another forum where troubleshooting assistance is provided, if this is not the appropriate place.  However I wasn't able to find anything like that either.  

If there is another support forum where I should post for troubleshooting help, please let me know.

**Comment by droidmonkey** [comment]
We don't have a support forum, but we do have IRC/matrix (links posted in readme). You'll be talking to the same folks though. 

I want to verify you tried other alternatives: snap package, flatpak, ppa.

You can also do an strace to see if there is a hang or block happening when opening files or libraries: `sudo strace keepassxc`

**Comment by michaelk83** [comment]
As a last resort, you can try [building from source](https://github.com/keepassxreboot/keepassxc/wiki/Building-KeePassXC) and attach a debugger. Or maybe grab the latest [snapshot](https://snapshot.keepassxc.org/). AFAIK, the releases limit debugging for security reasons.

**Comment by dmw73** [comment]
I downloaded the snapshot appImage (KeePassXC-2.7.0-snapshot-x86_64.AppImage) and it had the same issue.  
I am attempting to compile the source code using instructions here: https://github.com/keepassxreboot/keepassxc/wiki/Building-KeePassXC.  This is taking some time because I don't have all the dependencies and I'm not a developer so I'm fumbling along.  I did try to set up the environment using the instructions at https://github.com/keepassxreboot/keepassxc/wiki/Set-up-Build-Environment-on-Linux.

However, I discovered something weird.  If I launch keepassxc using strace, after a slight delay, it will launch and run.  This might indicate that strace is introducing a delay of some sort  that is preventing a race condition from happening.  Just a guess; I'm not a coder.  Does that offer any helpful clue?

**Comment by droidmonkey** [comment]
Not without the strace output.

**Comment by dmw73** [comment]
Attaching the output of this command:
strace keepassxc > strace.out 2>&1

Note that keepassxc did not open when launched this time.  

[strace.out.gz](https://github.com/keepassxreboot/keepassxc/files/6710541/strace.out.gz)

**Comment by droidmonkey** [comment]
Check that your XDG home dir is set correctly.  You have a ton of file not found errors

**Comment by dmw73** [comment]
These XDG dirs look fine, these are valid:

```
> cat .config/user-dirs.dirs 
# This file is written by xdg-user-dirs-update
# If you want to change or add directories, just edit the line you're
# interested in. All local changes will be retained on the next run.
# Format is XDG_xxx_DIR="$HOME/yyy", where yyy is a shell-escaped
# homedir-relative path, or XDG_xxx_DIR="/yyy", where /yyy is an
# absolute path. No other format is supported.
# 
XDG_DESKTOP_DIR="$HOME/Desktop"
XDG_DOWNLOAD_DIR="$HOME/Downloads"
XDG_TEMPLATES_DIR="$HOME/Templates"
XDG_PUBLICSHARE_DIR="$HOME/Public"
XDG_DOCUMENTS_DIR="$HOME/Documents"
XDG_MUSIC_DIR="$HOME/Music"
XDG_PICTURES_DIR="$HOME/Pictures"
XDG_VIDEOS_DIR="$HOME/Videos"
```

And $HOME is correct.

I manually ran /usr/bin/xdg-user-dirs-update just to be certain.


Going through the strace output I sent earlier, it ends with this:

```
openat(AT_FDCWD, 0x7ffe4e69e4a0, O_RDONLY|O_CLOEXEC) = 18
read(18, 
```

And that identifier first appears here:

`statx(AT_FDCWD, "/usr/etc/xdg/breezerc", AT_STATX_SYNC_AS_STAT, STATX_ALL, 0x7ffe4e69e4a0) = -1 ENOENT (No such file or directory)`

My system does have /usr/etc/xdg but obviously there is no file named breezerc inside.  I tried creating a blank breezerc but it didn't fix the issue.

So I repeated the strace keepassxc command and watched the process hang here:

```
openat(AT_FDCWD, 0x7fffacb0ec60, O_RDONLY|O_CLOEXEC) = 18
read(18, 
```

Once again, the file identifier is referring to breezerc but this time in the user's .config directory.

**Comment by ObserverOfTime** [comment]
It seems to me that KDE is just looking for its config files in several locations and the errors can be ignored.

**Comment by michaelk83** [comment]
`breezerc` is the Breeze theme config. Breeze is the default KDE theme, I think. Try reinstalling the theme, just in case.

@droidmonkey Is there a way to change KPXC's theme choice without launching KPXC? If the theme is not installed, it's probably not finding the icons, at least.

**Comment by droidmonkey** [comment]
Deleting the config files resets to our own theme. Only classic theme would use breeze.

**Comment by dmw73** [comment]
I looked into deleting the Breeze theme package but apparently the entire plasma workspace depends on it, so it was a no-go.  I did switch over to the Breeze theme in KDE settings; it seems to work fine.  I also tried a few other themes and all seem to work fine.  

I see the following in the strace output now:
```
access("/home/user/.config/breezerc", F_OK) = 0
readlink("/home", 0x7fff2d9b2320, 1023) = -1 EINVAL (Invalid argument)
readlink("/home/user", 0x7fff2d9b2320, 1023) = -1 EINVAL (Invalid argument)
readlink("/home/user/.config", 0x7fff2d9b2320, 1023) = -1 EINVAL (Invalid argument)
readlink("/home/user/.config/breezerc", 0x7fff2d9b2320, 1023) = -1 EINVAL (Invalid argument)
access("/home/user/.config/breezerc", F_OK) = 0
access("/home/user/.config/breezerc", W_OK) = 0
```

I suppose the first question is, should keepassxc fail to load if there is an issue with the KDE theme package?  Is this expected behavior?

Every time I attempt to launch keepassxc, the last line of strace output shows this:
```
openat(AT_FDCWD, 0x7fff2d9b2b80, O_RDONLY|O_CLOEXEC) = 18
read(18, 
```

It is hanging at that point each time.  Is this expected?

Could anyone offer a keepassxc config file that I could try?  Something that would change its theme?  I don't have an example file on hand.

What else could I try?

**Comment by droidmonkey** [comment]
We don't depend on anything from breeze. And that wouldn't cause a total failure to launch anyway.

**Comment by michaelk83** [comment]
> I looked into deleting the Breeze theme package but apparently the entire plasma workspace depends on it, so it was a no-go.

You don't need to delete it to reinstall it. The idea was that if the theme config file is missing or messed up, reinstalling it may fix that. But if the theme is working, that's probably not the case, anyway.

> Every time I attempt to launch keepassxc, the last line of strace output shows this:

It looks like it's hanging in the middle of the `read()` call. Maybe some other function call that's being passed to the 2nd parameter? I don't know where that is in the code, though.
(edit: Though, anything that's passed *into* the `read()` function should be invoked before `read()` itself. If that hangs, `read()` wouldn't have been called yet. So I really don't know how to interpret this kind of output. strace itself crashing, maybe?)

**Comment by dmw73** [comment]
I don't see strace itself crashing.  I have to kill -9 both strace and keepassxc when the hanging condition happens.  

I also tried launching keepassxc while logged in as root, same thing happens.

**Comment by michaelk83** [comment]
I should've said "hang" instead of "crash".

https://unix.stackexchange.com/q/166541/455274 might give you some more ideas, if you want to keep pursuing this. In the end, your best bet may be compiling from source, and running that through a debugger. Running the development snapshot through a debugger might work too. But since you said you're not a developer, I don't know if you'll be to make sense of it. Since you can access your DB though 2.5.0 and other Keepass variants, this may not be worth your time.

**Comment by dmw73** [comment]
Thanks, I do want to solve this, so I'll try some of the debugging techniques in that article you mentioned.

Here's the output from eu-stack up to the point keepassxc hangs:
```
# eu-stack -id -p 20808
PID 20808 - process
TID 20808:
#0  0x00007fae2d8f12fc __read
#1  0x00007fae2d7a9be5 initialize_device
#2  0x00007fae2d7ac148 linux_enumerate_device
#3  0x00007fae2d7ac87d op_init
#4  0x00007fae2d7ab58e libusb_init
#5  0x00007fae2f646c90 yk_init
#6  0x000055f16cbdf560 _ZN7YubiKeyC2Ev
#7  0x000055f16cbdf6fb _ZN7YubiKey8instanceEv
#8  0x000055f16cc70330 _ZN18DatabaseOpenWidgetC2EP7QWidget
#9  0x000055f16cca2632 _ZN18DatabaseOpenDialogC2EP7QWidget
#10 0x000055f16cc74860 _ZN17DatabaseTabWidgetC2EP7QWidget
#11 0x000055f16cbbbfb8 _ZN13Ui_MainWindow7setupUiEP11QMainWindow
#12 0x000055f16cbb12fa _ZN10MainWindowC2Ev
#13 0x000055f16cb90d2b main
#14 0x00007fae2d827b35 __libc_start_main
#15 0x000055f16cb9b04e _start
TID 20811:
#0  0x00007fae2d8f559f __poll
#1  0x00007fae2c901892 _xcb_conn_wait.part.0
#2  0x00007fae2c9032ac xcb_wait_for_event
#3  0x00007fae2a659cc0 _ZN14QXcbEventQueue3runEv
#4  0x00007fae2e13bc21 _ZN14QThreadPrivate5startEPv
#5  0x00007fae2d7e6259 start_thread
#6  0x00007fae2d9002b3 __clone
TID 20812:
#0  0x00007fae2d8f559f __poll
#1  0x00007fae2c9c6b2e g_main_context_poll
#2  0x00007fae2c9c6b2e g_main_context_iterate
#3  0x00007fae2c9c6c4f g_main_context_iteration
#4  0x00007fae2e3770f4 _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE
#5  0x00007fae2e31e4bb _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE
#6  0x00007fae2e13aaee _ZN7QThread4execEv
#7  0x00007fae2dfca287 _ZN22QDBusConnectionManager3runEv
#8  0x00007fae2e13bc21 _ZN14QThreadPrivate5startEPv
#9  0x00007fae2d7e6259 start_thread
#10 0x00007fae2d9002b3 __clone
TID 20816:
#0  0x00007fae2d8f559f __poll
#1  0x00007fae2d7ad02e linux_udev_event_thread_main
#2  0x00007fae2d7e6259 start_thread
#3  0x00007fae2d9002b3 __clone

```

**Comment by droidmonkey** [comment]
You are hanging in your usb reading. That would be libusb version 0.x or 1.0.

**Comment by michaelk83** [comment]
Does look like it. Some things to try:
- Disable the YubiKey extension (you can do it in 2.5.0 then use the resulting config file with the new version).
- Try disconnecting or moving around your USB devices.
- Check the journal for USB errors: `journalctl | grep -i usb | grep -iE 'fail|error|warning'`, and fix those.
- Update libusb.
- Update the kernel.

**Comment by dmw73** [comment]
I'm looking around for the option to disable YubiKey, not finding it thus far.  

I see older usb errors in the journal but none from yesterday or today.

But now I've observed something **very** strange:

1. I launch keepassxc from command-line.  The UI doesn't appear and the process is hung.
2. I run this command: eu-stack -id -p <PID of keepassxc>.  The stack is printed, as expected.
3. I run that same eu-stack command once more.  This time, the keepassxc UI launches (installed version 2.6.6), and the program runs normally without a hitch!  

I have repeated that sequence 3 times and it reproduces the same behavior each time.  For whatever reason, running eu-stack TWICE causes the program to run and launch!

**Comment by michaelk83** [comment]
Put it in a script, and leave it at that?

If it's really the USB, my guess is either a faulty device or a faulty port. Or maybe a  kernel bug. Probably some change in the YubiKey handling since 2.5.0 causes it to mess up. But this whole issue is really weird.
