### ISSUE TITLE
Snapshot 195210 Scaling issue in copy attribute, TOTP context menus

### ISSUE THREAD

**Issue by JohnLGalt** [keepassxreboot/keepassxc#6664]
## Overview
[NOTE]: # ( Give a BRIEF summary about your problem )
Using the latest dev snapshot portable on Windows.  Dual monitor setup a 1080p monitor and a 4K monitor.  Enabled DPI Scaling 150% on 4K monitor, none on 1080 p monitor.  Regardless of which monitor KPXC 2.7.0 snapshot is on, both of those context menus are disproportionately scaled (entirely too large or too small relative to rest of the window).

This does not happen with other menus from entry right click, only these two.  E.G. Perform Auto-type context menu always scales same relative to main window).

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. DL and Extract Dev snapshot 195210 to any folder, run KPXC and open database.
2. Attempt to use Copy Attribute or TOTP context menu from right click on any entry
3. Menu is over scaled  or under scaled.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
I expect to see those two context menus to be scaled at the same size as everything else.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Menu is over scaled  or under scaled.

## Context
[NOTE]: # ( Give us any additional information you may have. )
If you view the same menus from the Entries menu at the top of the window,. the menus are scaled normally.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.0-snapshot
Revision: 724f691

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 10 x64 Pro 21H1 (19043.1081)

Screenshots:

Normal scaling from Entries menu (same entry was used for all three images, so you can see what it is supposed to look like in the first image.  Over-scaling occurs on 1080p monitor, under-scaling occurs on 4K monitor).

<img width="88" alt="Scaling 02" src="https://user-images.githubusercontent.com/7432512/123160344-0f045300-d43c-11eb-9093-a27f5659192d.png">

Over-scaling:

<img width="88" alt="Scaling 01" src="https://user-images.githubusercontent.com/7432512/123160379-19bee800-d43c-11eb-87b3-05eb915c74c4.png">

Under-scaling:

![Scaling 03](https://user-images.githubusercontent.com/7432512/123160516-4bd04a00-d43c-11eb-9d2d-1fe2b99d7cf2.png)

(In this image it might seem normal, but that is from a 4K monitor and the entire image is *supposed* to be the menu, as you can see it is shrunken in the allotted space).

## Debug Info
```
KeePassXC - Version 2.7.0-snapshot
Build Type: Snapshot
Revision: 724f691

Qt 5.15.2
Debugging mode is disabled.

Operating system: Windows 10 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.19043

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
- Botan 2.17.3
```

**Comment by droidmonkey** [comment]
Qt issue please submit to bugreports.qt.io

**Comment by droidmonkey** [comment]
You might also want to try QT_SCREEN_SCALE_FACTORS. 


https://doc.qt.io/qt-5/highdpi.html#high-dpi-support-in-qt

**Comment by JohnLGalt** [comment]
Thanks for the heads up.  I figured it was qt.
