### ISSUE TITLE
Large file attachment.

### ISSUE THREAD

**Issue by tailot** [keepassxreboot/keepassxc#6668]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
Allow attachment of large files.

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )
![9467A6CC-718F-492A-82C7-0E3EDEE7BE1F](https://user-images.githubusercontent.com/40148896/123391840-b4363d00-d59c-11eb-9f37-a002f4216750.jpg)

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
Security reasons!

**Comment by droidmonkey** [comment]
You can do it but that is definitely not the way keepass databases are used. Used cryptomator or veracrypt to store large files.
