### ISSUE TITLE
GUI improvement in entries list

### ISSUE THREAD

**Issue by cedws** [keepassxreboot/keepassxc#6670]
## Summary
I am asking for an improvement to the entries list to make it more clear where the user needs to click to open an entry.

I'm on KeePassXC 2.6.6 and I often get frustrated that when I try to open an entry, I instead copy credentials to my clipboard instead or open the associated URL by accident. This is because there is no clear place to click to open an entry.

The only reliable way to open an entry is with `Right Click > Edit Entry...`, but this isn't intuitive to everybody because it's a GUI application, so point and click is the main mode of interaction.

I also think it's not clear enough that double clicking the `Username` copies to clipboard. A little bit of text appears on the bottom right to indicate that the clipboard will be cleared, but that requires a keen eye to spot. Someone who isn't experienced with KXC interface may think the program is frozen or that they are doing something wrong.

## Examples
Unfortunately I cannot propose an improvement because my design skills are terrible and I'd only make it worse. Sorry.

This shows where the user can click to actually open an entry:

![image](https://user-images.githubusercontent.com/38229097/123527872-0b422c00-d6db-11eb-8a79-eefb535dca1b.png)

**Comment by droidmonkey** [comment]
On develop branch, the copy on double click  can be disabled in the application security settings. That means more fields open the entry on double click. This setting is set to disable the double click behavior by default.

**Comment by michaelk83** [comment]
I the duplicate is of #5910? I'll post some ideas there.
