### ISSUE TITLE
GPG Signature invalide

### ISSUE THREAD

**Issue by lasscap** [keepassxreboot/keepassxc#6672]
I just wanted to download the new version of Keepass and checked its GPG signature. I get the responce that the signature is untrusted. See attachment.
<img width="716" alt="image" src="https://user-images.githubusercontent.com/47210775/123540765-f26c6180-d740-11eb-8d81-116af7ad679c.png">

**Comment by droidmonkey** [comment]
It won't be trusted if you don't trust it... that's how gpg works
