### ISSUE TITLE
Modifier Keys (+, ^, %) don't work in Auto-Type

### ISSUE THREAD

**Issue by flatline-studios** [keepassxreboot/keepassxc#6673]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
The Auto-Type modifier keys, mentioned at: https://keepass.info/help/base/autotype.html - Don't work as they should.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Add Auto-Type for an entry
2. Use something like: `{TAB}+{TAB}`

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Should result in `TAB` being sent, then `SHIFT+TAB`.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Results in: `TAB` `+` `TAB`, being sent instead.

## Context
[NOTE]: # ( Give us any additional information you may have. )
N/A

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.6
Revision: 9c108b9

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows

**Comment by droidmonkey** [comment]
Implemented on develop branch
