### ISSUE TITLE
Add a way to choose between single or double click for showing the main window

### ISSUE THREAD

**Issue by tgucci** [keepassxreboot/keepassxc#6674]
## Summary
Please, add a checkbox to choose between single or double click for showing the main window from the system tray

## Context
My unique circumstance is that almost all programs do show on a double-click, and not on a single click. Either that, or there is a way for me to change it in the settings and it only appears to me that it is that way.

**Comment by droidmonkey** [comment]
Depending on the platform (windows, Linux, Mac) we toggle the window visibility on click and double click. They are the same action. Which platform are you using? If Linux, which desktop environment?

**Comment by tgucci** [comment]
The platform I use is Windows, and both variants are common here.
