### ISSUE TITLE
'Sync' plugin password generator with app settings/rules

### ISSUE THREAD

**Issue by Gomido** [keepassxreboot/keepassxc#6676]
## Summary
Recently, I started using the password generator in the application, I noticed that despite the selected options in the application, the browser cannot generate the password that we have set in the generator. Despite the rules, it generates passwords with every possible character.

## Examples
We choose in the app so that the password does not have special characters
https://i.imgur.com/A0nC8OB.gif
The application generates passwords from only letters / numbers.
We enter the browser, select the field with the password and generate it. 
The plugin generates a password with every character it can give, it doesn't respect our rules from the application.
https://i.imgur.com/az4piEZ.gif

**Comment by droidmonkey** [comment]
Already done in develop branch
