### ISSUE TITLE
Moving an entry or a group to another database should keep track of this change in the original database

### ISSUE THREAD

**Issue by Cor-J** [keepassxreboot/keepassxc#6677]
## Overview
When a group or an entry is moved from a database "MyDB.kdbx" to a database "OtherDB.kdbx", it is silently deleted from the database "MyDB" without showing in trash.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Open "MyDB.kdbx"
2. Open "OtherDB.kdbx"
2. drag and drop a group or an entry from "MyDB.kdbx" to "OtherDB.kdbx"

The group/entry is deleted from "MyDB.kdbx", but not shown in the bin.

## Expected Behavior
The group/entry moved out of  "MyDB.kdbx" should appear in the trash of this database.

## Actual Behavior
The group/entry is silently deleted from the database.

## Context

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.6
Revision: 9c108b9

Qt 5.15.2
Debugging mode disabled

OS : Windows 10 Version 2009 x86_64
Kernel: winnt 10.0.19043

Plugins:
- Autotype
- browser integration
- SSH agent
- KeeShare
- YubiKey

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 10 Pro

**Comment by droidmonkey** [comment]
This is expected behavior. You are moving the entry not deleting it. No information is lost unless you don't save the destination database.
