### ISSUE TITLE
Commandline functionality missing (snap)

### ISSUE THREAD

**Issue by paranoidi** [keepassxreboot/keepassxc#668]
Installed 2.2.0 snap in ubuntu 16.04. Tried to find commandline documentation without success. Used command:

```
$ keepassxc --help
QXcbConnection: Could not connect to display
Aborted
```

which was very confusing, why is it connecting to something and failing without clear explanation.

In IRC someone said to use ```keepassxc-cli``` but no such command is packaged in the snap?

## Expected Behavior

Please provide CLI documentation. Expected CLI to work.

## Current Behavior

CLI command missing

## Possible Solution

Include CLI command to snap package

## Steps to Reproduce (for bugs)

1. sudo snap install keepassxc
2. keepassxc-cli
3. command not found

## Context

Major annoyance ...

## Your Environment

* KeePassXC version/commit used: (can be found under Help -> About)
* Qt version (e.g. Qt 5.3): 
* Compiler (e.g. Clang++3.6.0): 
* Operating System and version: 

Ubuntu 16.04 server

**Comment by phoerious** [comment]
The single-binary distributions (i.e. Snap and AppImage) don't expose their CLI interface at the moment. You can, however, unpack the AppImage and use the cli tool from there.

**Comment by paranoidi** [comment]
@TheZ3ro What's the use for CLI then? Sounds like I need to keep using the perl based commandline tool which is not too great. Please update your site to reflect this limitation/information.

**Comment by TheZ3ro** [comment]
@paranoidi What do you mean? What should I update? Right now for using the cli you need to compile it manually the call `keepassxc-cli`. Right now it's not distributed in the snap/appimage/dmg (and this is our fault)

**Comment by louib** [comment]
@paranoidi  The CLI right now is still limited. I'm currently working on a more complete interactive shell, covering most of the commands in the `kpcli` perl script. You can follow [this PR](https://github.com/keepassxreboot/keepassxc/pull/684) for more info.

**Comment by jD91mZM2** [comment]
Any updates on this? I just saw 1Password's CLI thing, and I wanted to see if KeePass had one...

**Comment by TheZ3ro** [comment]
@jD91mZM2 KeePassXC has one, but ATM you need to compile it yourself and the only available documentation is the manpage

**Comment by jD91mZM2** [comment]
Mhm... Would be epic if it was in the snap package :+1:

**Comment by TheZ3ro** [comment]
@jD91mZM2 yup, in the next minor version it will be available :smile:

**Comment by riqpe** [comment]
Piggybacking on this case, the same functionality should also be exposed through the Appimage for other platforms, without requiring its unpacking.
