### ISSUE TITLE
https://keepassxc.org/ website is down

### ISSUE THREAD

**Issue by dazzag24** [keepassxreboot/keepassxc#6685]
https://keepassxc.org/ is unavailable right now.

**Comment by xychix** [comment]
Site seems back up but certificates are broken
![image](https://user-images.githubusercontent.com/307655/123813084-e5906f00-d8f4-11eb-87dd-d7952632db18.png)

**Comment by droidmonkey** [comment]
Our hosting provider suffered a massive data center outage. We redirected the page back to github which breaks tls until everything syncs up.

**Comment by GeorgelT** [comment]
I just recommended your password manager and did a quick google search, please fix your SSL certificate. Looks very bad when making a recomandation.

**Comment by droidmonkey** [comment]
We can't control this...
