### ISSUE TITLE
Cross-platform FdoSecrets?

### ISSUE THREAD

**Issue by michaelk83** [keepassxreboot/keepassxc#6686]
## Summary
On Linux, the FdoSecrets integration works by exposing an interface on DBus. It is disabled on MacOS and Windows. However, it's technically possible to install DBus on MacOS ([ref1](https://stackoverflow.com/a/4969405/15047974), [ref2](https://gist.github.com/berkin/b2139360393c93eebc35fa298fc859bc)) and may be possible to install on Windows WSL ([ref3](https://github.com/microsoft/WSL/issues/376#issuecomment-292591984), [ref4](https://www.reddit.com/r/Windows10/comments/4rsmzp/bash_on_windows_getting_dbus_and_x_server_working/), [ref5](https://www.reddit.com/r/bashonubuntuonwindows/comments/9l46br/asking_wsl_ubuntu_1804_dbus_fix_updated/)). Would it be possible to enable FdoSecrets under those circumstances?

I suppose Windows WSL would still count as "Linux" this purpose?

## Context
This could be useful for scripting and automation tasks, as I noted in [#1483 (comment)](https://github.com/keepassxreboot/keepassxc/issues/1483#issuecomment-870733549).

@Aetf , thoughts?

**Comment by Aetf** [comment]
Hmm, there are a few places in the code assuming a Linux environment (mostly getting PID from the client). Also, I can't test it on those OSes.

But PRs that make the code more portable in general are welcome.

**Comment by droidmonkey** [comment]
You run keepassxc through WSL, done. What would you talk to on macOS? There would need to be fdosecrets aware consumers installed. This is a "won't implement" for me.

**Comment by michaelk83** [comment]
> What would you talk to on macOS?

Assuming the use case is scripting, then whatever scripts the users write. I assume one can install `libsecret` and python on MacOS, but even if not, such scripts can use the FdoSecrets DBus interface directly (along with KPXC's main DBus interface).
 
Anyway, this was more of a "crazy thought" / what-if.

**Comment by droidmonkey** [comment]
You're much better off using keepassxc-cli in scripts
