### ISSUE TITLE
KeepassXC v2.6.4, v2.6.6 Failed to read database (Saved by Strongbox)

### ISSUE THREAD

**Issue by Epic-1** [keepassxreboot/keepassxc#6687]
KeepassXC macOS v11.4 fails to read database files saved by StrongBox Pro v1.52.22 on iOS.  Keepass v2.48.1 (orig) on PC is able to read the files OK.  Files (re)saved in Keepass v2.48.1 PC do open in KeepassXC macOS.

Note sure where the discrepancy lies (KeepassXC or StrongBox so I post ticket with both apps.
![image](https://user-images.githubusercontent.com/17281521/123849126-10bb9400-d8de-11eb-8dea-0334e0520514.png)

**Comment by droidmonkey** [comment]
Discrepancy is in your file share. Make sure you have proper permissions set to read files from it. The error you see is a file system error. Could also be an error where another program has read lock on the file.
