### ISSUE TITLE
Frequent Auto-Type crashes after some idle time with minimized app. Works after immediate application restart.

### ISSUE THREAD

**Issue by gith-account** [keepassxreboot/keepassxc#6688]
## Overview
KeepassXC 2.6.6 on macOS Mojave 10.14.6 keeps crashing on a Macbook Pro Retina 13'' 2015 whenever Auto-Type is performed after some idle time with the application minimized. The crashes happen when the application is about to fill in the data. When reopened immediately after the crash, the application works as expected for some time. Apparently this does not affect everyone or else there would be more complaints.

## Steps to Reproduce

1. Open KeepassXC
2. Minimize the application
3. Perform Auto-Type after some idle time
4. Crash
5. Reopen app
6. Perform Auto-Type immediately after
7. Works

## Expected Behavior

Auto-Type without crashing

## Actual Behavior

Application crashes during Auto-Type following some idle time with the application minimized

## Context

KeePassXC - Version 2.6.6
Revision: 386b79a
Keepass 2 database (size 259KB, password protected)

Qt 5.15.2
Debugging mode is disabled.

Operating system: macOS Mojave (10.14.6)
CPU architecture: x86_64
Kernel: darwin 18.7.0

Enabled extensions:
- Auto-Type
- Browser Integration ("Enable browser integration" is turned off in the application)
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
- libgcrypt 1.9.3

**Comment by droidmonkey** [comment]
Will need a crash dump or debug stack trace to track it down. Can you try running the develop snapshot to see if it persists? We did major overhaul of Auto-Type code.

 https://snapshot.keepassxc.org

**Comment by gith-account** [comment]
> Can you try running the develop snapshot to see if it persists? We did major overhaul of Auto-Type code.
> https://snapshot.keepassxc.org

I have installed it and will let you know if the problem persists. Thanks.

**Update:**

With version 2.7.0-snapshot, revision 724f691, auto-type with the global auto-type shortcut does not work when the app is minimized to the dock with the database locked. The app will come to the foreground and offer a list of matching entries after unlocking the database but fail to actually perform the auto-type.

It seems to work when the app is either minimized to the status menu only or not minimized.

I usually have the app minimized to the dock, thus with this overlaid new problem I cannot tell if the previously described crashes are still occurring. They do not seem to happen with version 2.7.0-snapshot, revision 724f691 and the app minimized to the status menu only.
