### ISSUE TITLE
Snap does not open db in a dot folder

### ISSUE THREAD

**Issue by kronos29296** [keepassxreboot/keepassxc#669]
I installed the snap for keepassxc since the appimage has a launch bug. The snap opens but does not launch my db which is in a dot folder of my home directory. I tried putting in another folder and it opens just fine. When I use Keepass 2.35 it opens the db without a problem from the same folder.

## Expected Behavior
Keepassxc should open the kdbx db regardless of the location. When i used the previous version appimage I did not run into such a problem

## Current Behavior
Keepassxc does not open database which is stored in ~/.kpassfiles directory. It is not even listed when I open the directory. If I enter the full filename in the Open box It shows permission denied.

## Possible Solution
It somehow seems to a problem with snap. (Maybe limited permissions because of snap package security reasons)

## Steps to Reproduce (for bugs)
1.Create a folder starting with . in its name
2.Create a db or open a db from this directory
3.Keepassxc shows permission denied

## Context
I use a dot folder to hide the existence of my password database. Security through obscurity but Keepassxc snap fails to open it.

## Your Environment
* KeePassXC version/commit used: 2.2.0
* Qt version (e.g. Qt 5.3): Version in snap
* Compiler (e.g. Clang++3.6.0): Version in snap
* Operating System and version: Ubuntu 17.04

**Comment by phoerious** [comment]
I am pretty sure there is more to it and this is not a bug in KeePassXC directly. There is no reason why opening files from dot folders shouldn't work (and I also just tested it and it does work). Do you have all the needed permissions for accessing the folder? Is the folder on an external drive? Did you enter the name correctly (you can use right click->show hidden files in the open dialog).

**Comment by kronos29296** [comment]
It somehow opens with normal keepass and works fine. It even worked with the appimage of previous version. I tried to create a new db in the same folder but It also doesn't work. Don't know why.

**Comment by phoerious** [comment]
Can you check the permissions of the file and folder and please also answer the other questions above?

**Comment by TheZ3ro** [comment]
Yes, probably it's a snap bug

**Comment by phoerious** [comment]
Maybe, but hard to tell without more information. I can't reproduce the problem.

**Comment by kronos29296** [comment]
I created a new folder named .kthings and tried to create a new database but the problem persists. I don't have any other snaps installed so I don't know where the problem lies.
The problem doesn't happen if the parent directory is in a normal directory like Downloads or Desktop. This happens only if the parent folder (.kthings) is directly in the Home directory. Hope this helps.

**Comment by kronos29296** [comment]
I tried to open with the Appimage and it opens perfectly (used the workaround for qt5.9). So most probably a problem with the snap itself or snap (the thing not keepassxc)

**Comment by vickrum** [comment]
Same issue here. It does appear to be a snap issue. The `:home` interface doesn't allow access to hidden directories: https://snapcraft.io/docs/reference/interfaces. It's being discussed in the snap bug tracker: https://bugs.launchpad.net/snappy/+bug/1607067.

If support is eventually added to snap, it'd be great to see this functionality added to keepassxc too (assuming it'd require changes on this end).

The only thing I can see to do here is with the UX; the "Show hidden files" context menu option is perhaps misleading for snap users.

**Comment by DragoonAethis** [comment]
Snap [sandboxes apps](https://docs.ubuntu.com/core/en/guides/intro/security) and [limits app access to hidden directories in your home directory by default](https://github.com/snapcore/snapd/wiki/Interfaces).

**Comment by kronos29296** [comment]
Thanks for the clarification.

**Comment by Satlinker** [comment]
Hi, same problem with keepassxc 2.7.10 (no snap) in cachyos with a separate home partition. I cannot see the hidden folders in the home partition when I want to open the database. If I type in the hidden path manually the open button does not work. Permissions are set to user (me).
In an ubuntu installation without separate home partition it works.

**Comment by droidmonkey** [comment]
sounds like a cachyos problem.......

**Comment by Satlinker** [comment]
No, because with other programs it works. It also works with a link in a not-hidden directory to the hidden database, so its the build-in file-explorer.

**Comment by droidmonkey** [comment]
We don't use a built in file explorer

**Comment by Satlinker** [comment]
No hidden files in the database open screen, I called it explorer:

![Image](https://github.com/user-attachments/assets/50f32d29-7a71-438c-ac5b-9048b1709799)

**Comment by droidmonkey** [comment]
That is from your OS. You might have to press Ctrl+H to show hidden files.

**Comment by Satlinker** [comment]
Thank you.
Could it be one of those Wayland things? (I start with -platform xcb). I guess that's also the reason why other things don't work anymore:
Auto-Type doesn't recognize the window title anymore and displays a password list to choose from.
