### ISSUE TITLE
Input troubles with multiple displays

### ISSUE THREAD

**Issue by QuAzI** [keepassxreboot/keepassxc#6692]
Regularly I have a problems when KeePassXC shown not on default display.
I have a laptop with win10 and 15.6" [1920x1080px, 125% scale] display. And two additional displays [1920x1080px, 100% scale].
Sometimes I take take laptop with self into other room and additional displays are switched off. After hours of work I can see that I can't input something into KeePassXC or copy pass while it not on default laptop display.

**Comment by droidmonkey** [comment]
This would be a Qt bug, please report it at https://bugreports.qt.io
