### ISSUE TITLE
Autotype special keys like ctrl or command are not working on macos

### ISSUE THREAD

**Issue by MmAtBosch** [keepassxreboot/keepassxc#6695]
## Overview
I want to use special keys like ctrl or command to do shortcuts like ctrl+a or command+l to navigate inside of my browser using autotype.
In Keepass on Windows i just used "^l" for example to go to my adress bar.

Sadly this seems not work in KeepassXC on Macos even it´s document [here](https://keepassxc.org/docs/KeePassXC_UserGuide.html#_configure_auto_type_sequences):
> A complete list of supported actions and placeholders can be found at KeePass Auto-Type Action Codes and KeePass Placeholders

https://keepass.info/help/base/autotype.html#autoseq
<img width="531" alt="Auto-Type - KeePass 2021-07-01 12-36-29" src="https://user-images.githubusercontent.com/48314408/124111022-20b3af00-da69-11eb-9029-630995643cfd.png">

## Steps to Reproduce
1. Just create an entry and edit the autotype sequence to: %l 
2. and execute the autotype inside your browser(chrome in my case, but shouldn´t mater)

## Expected Behavior
In my understanding this should result in alt+l meaning command+l in macos and focusing to adress bar.

## Actual Behavior
it is simply typing %l

## Context
Using macOS BigSur

KeePassXC - 2.6.6
Revision: 386b79a

Operating System: macOS

**Comment by droidmonkey** [comment]
Feature will be in 2.7.0, use a snapshot of develop at  https://snapshot.keepassxc.org to use it now

**Comment by MmAtBosch** [comment]
awesome 🤗  thank you!

**Comment by MmAtBosch** [comment]
i just downloaded the latest 2.7 snapshot and gave it a try. sadly it doesn´t work either.
is it not implemented yet? or is there an updated documentation regarding?

**Comment by droidmonkey** [comment]
Hmmmm could be because macos switches the controls around from Linux and Windows (Cmd vs Ctrl). Might be an actual bug here!

**Comment by MmAtBosch** [comment]
let me know if i can help somehow!

**Comment by droidmonkey** [comment]
Thank you for posting this because I just found that there was a bug in general with the regular expression I used to detect these modifier keys. This prevented their use on all platforms! I also needed to fix the sending of keys on Windows, so this was overall an excellent bug fix report.

**Comment by MmAtBosch** [comment]
> Thank you for posting this because I just found that there was a bug in general with the regular expression I used to detect these modifier keys. This prevented their use on all platforms! I also needed to fix the sending of keys on Windows, so this was overall an excellent bug fix report.

Glad to hear this :)
Im curious about the new version, as i´m also experience another issue in the meantime, when i´m working with my Azure VMs and trying to login there.
