### ISSUE TITLE
TOTP not working as intended

### ISSUE THREAD

**Issue by ghost** [keepassxreboot/keepassxc#6697]
I've found that in many cases (and different apps too), TOTP isn't working as intended. It shows a "future" code. For example, in KPXC it shows <code1> while in AndOTP shows <code0>. Then AndOTP shows <code1> when in KPXC it still has a bit to expire (so if you use the TOTP then it would work), and then KPXC would change to <code2>.

It has happened to me with reddit and other places, I've checked the code of the OTP configuration and they are the same.

**Comment by droidmonkey** [comment]
Sync your computer time
