### ISSUE TITLE
Attachment lives even if database is locked

### ISSUE THREAD

**Issue by DuckDuckWhale** [keepassxreboot/keepassxc#6698]
## Overview

Extracted attachments are not removed until the window is closed, giving the false sense of security.

## Steps to Reproduce
1. Add attachment (an image will do)
2. Open file & containing folder
3. Lock database
4. Check containing folder and see the file is still there

## Expected Behavior
Extracted attachments are removed as soon as the database is locked.

## Actual Behavior
Extracted attachments are not removed until the window is closed.

## Context
- KeePassXC - 2.6.2
- Operating System: Ubuntu 21.04
- Desktop Env: Gnome
- Windowing System: X11

**Comment by droidmonkey** [comment]
Fixed by #6606, this is a duplicate
