### ISSUE TITLE
"keepassxc-cli open" help improvement

### ISSUE THREAD

**Issue by jaker-dotcom** [keepassxreboot/keepassxc#6699]
## Summary
This is about mentioning shell-like interactive mode when doing keepassxc-cli help. 

## Examples
Available commands:
open                    Open a database in interactive mode.

instead of current:
open                    Open a database.

## Context
Well admittedly I was pretty confused that it would ask me to enter the password for every action. Since help menu doesn't mention interactive mode at all I quickly was about to give pass (another cli pwd manager) a try. 

I would have mentioned this in the help text file but couldn't locate it in this repo.

**Comment by droidmonkey** [comment]
This is documented in the man page:

open [options] <database>

Opens the given database in a shell-style interactive mode. This is useful for performing multiple operations on a single database (e.g. ls followed by show).
