### ISSUE TITLE
Opening a group tree marks the database as modified

### ISSUE THREAD

**Issue by pietermj** [keepassxreboot/keepassxc#670]
On windows 7x64, simply opening or closing a group tree marks the db as modified.

KeePassXC version 2.2.0, revision caa49a8ef3ee28ed478192389b21d61107b3b8e0.

The same bug already existed in keepassx 2.0.2, revision 3679b2170142c14362fa75e990ef85b80b1b1b46.

![keepassxcmodified](https://user-images.githubusercontent.com/24895360/27537639-05ce83a4-5a75-11e7-8c8f-76e276495199.gif)

**Comment by phoerious** [comment]
KeePassXC 2.2.0 has a new option to turn off this behavior. You may want to check that out.
