### ISSUE TITLE
Where is the randomness coming from?

### ISSUE THREAD

**Issue by AndreiMihalea** [keepassxreboot/keepassxc#6700]
Hello,

I am wondering where the "randomness" comes from when a password is generated. Looking at the code (`keepassxc/src/crypto/Random.cpp`), I see there are two possibilities:

- system rng (like /dev/urandom)
- auto rng

Therefore, I was trying to check the accesses to the `/dev/urandom` on my ubuntu machine, using the following command:
`sudo inotifywait /dev/urandom -mr`

However, nothing appears when I am generating a new password with the password generator.

I have also written a small piece of code that generates random numbers similarly to what it is found in `keepassxc/src/crypto/Random.cpp`, then used it to generate 36 random numbers, simulating an alphabet of 128 characters, similarly to how passwords are generated in `keepassxc/src/core/PasswordGenerator.cpp`. This is my code 

```
#include <botan/auto_rng.h>
#include <botan/system_rng.h>

#include <QByteArray>
#include <QScopedPointer>
#include <QSharedPointer>

#include <botan/rng.h>

#define QUINT32_MAX 4294967295U

QSharedPointer<Botan::RandomNumberGenerator> m_rng;

void randomize(QByteArray& ba)
{
    m_rng->randomize(reinterpret_cast<uint8_t*>(ba.data()), ba.size());
}

quint32 randomUInt(quint32 limit)
{
    Q_ASSERT(limit <= QUINT32_MAX);
    if (limit == 0) {
        return 0;
    }

    quint32 rand;
    const quint32 ceil = QUINT32_MAX - (QUINT32_MAX % limit) - 1;

    // To avoid modulo bias make sure rand is below the largest number where rand%limit==0
    do {
        m_rng->randomize(reinterpret_cast<uint8_t*>(&rand), 4);
    } while (rand > ceil);

    return (rand % limit);
}


int main()
{

	#if defined(BOTAN_HAS_SYSTEM_RNG)
		m_rng.reset(new Botan::System_RNG);
	#else
		m_rng.reset(new Botan::AutoSeeded_RNG);
	#endif

	for (int i = 0; i < 36; i++) {
            int pos = randomUInt(static_cast<quint32>(128));
        }


	return 0;
}
```

This time, when I watch the accesses in `/dev/urandom` with `sudo inotifywait /dev/urandom -mr`, I can see the following:
```
/dev/urandom OPEN 
/dev/urandom ACCESS 
/dev/urandom ACCESS 
/dev/urandom ACCESS 
/dev/urandom ACCESS 
/dev/urandom ACCESS 
/dev/urandom ACCESS 
/dev/urandom ACCESS 
/dev/urandom ACCESS 
/dev/urandom ACCESS 
/dev/urandom ACCESS 
/dev/urandom CLOSE_WRITE,CLOSE
```

So, my question is where does the rng for the password generator take its "randomness" if not `/dev/urandom` and why doesn't it use `/dev/urandom` if it is available?

**Comment by droidmonkey** [comment]
Take a read on the Botan documentation: https://botan.randombit.net/handbook/api_ref/rng.html#rng-types

**Comment by AndreiMihalea** [comment]
Thank you for the answer, but that's basically and I am still a bit confused. According to that, botan should use the system RNG, and as I stated, my piece of code accesses the `/dev/urandom`, as expected. However, I still don't understand why whenever I am generating a password using KeepassXC, there is no single access to `/dev/urandom`.

There is this line in `keepassxc/src/core/PasswordGenerator.cpp`:
`int pos = randomGen()->randomUInt(static_cast<quint32>(passwordChars.size()));`

This means calls will be made to `rng->randomize` and `randomize` is defined in botan as:
```
void System_RNG_Impl::randomize(uint8_t buf[], size_t len)
   {
   while(len)
      {
      ssize_t got = ::read(m_fd, buf, len);

      if(got < 0)
         {
         if(errno == EINTR)
            continue;
         throw System_Error("System_RNG read failed", errno);
         }
      if(got == 0)
         throw System_Error("System_RNG EOF on device"); // ?!?

      buf += got;
      len -= got;
      }
   }
```
Meaning each time this call happens, a read will be made from the system rng device (`/dev/urandom` in my case)

**Comment by droidmonkey** [comment]
Are you using keepassxc develop branch as a snapshot or self compiled?

**Comment by AndreiMihalea** [comment]
Ah, yes, this is the issue. I was using the version installed with snap, which is probably the latest release, without realizing it doesn't have the botan changes yet. 
Thank you.
