### ISSUE TITLE
Windows 10 - No hardware key detected while running standard (not as administrator)

### ISSUE THREAD

**Issue by ShivekXR** [keepassxreboot/keepassxc#6702]
## Overview
KeePassXC doesn't detect hardware key (YubiKey 5**C** NFC) while not running as administrator.

## Steps to Reproduce
1. Plug in YubiKey 5C NFC to USB-C slot in your PC.
2. Open KeePassXC without running as administrator.
3. No hardware keys detected even if the refresh button is clicked.

Doesn't matter if plug YubiKey as a first or second step.

## Expected Behavior
I would like to select Hardware keys without running as administrator.

## Actual Behavior
There is "No hardware keys detected" in the Hardware Key dropdown list.

## Context
KeePassXC doesn't detect hardware key (YubiKey 5**C** NFC) while running standard. "No hardware keys detected" warning in the dropdown list. Clicking the Refresh button doesn't help. Luckily when I run KeePassXC as administrator, the app is able to fetch YubiKey slots and I can open my database.

On MacOS I had to give some permissions to get it working but no clue what to do on Windows.

However the solution helps me partially - I am able to open my database, get any password, but while running as administrator I can't use SSH agents - I have every possible error. Not sure how it is connected to this issue, so I filled other ticket: https://github.com/keepassxreboot/keepassxc/issues/6703

KeePassXC - Version 2.6.6
Revision: 9c108b9

Qt 5.15.2
Debugging mode is disabled.

Operating system: Windows 10 Version 2004
CPU architecture: x86_64
Kernel: winnt 10.0.19041

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
- libgcrypt 1.9.2-unknown

Operating System: Windows 10 Pro

**Comment by droidmonkey** [comment]
This is something wrong with your system not keepassxc. See if you can find your key as a standard user from the yuibkey tools themselves.

**Comment by locksec** [comment]
I have the same issue with my Yubikey 5 NFC

KeePassXC - Version 2.6.6
OS: Windows 10 Pro

No hardware keys detected.

It's working elsewhere and shows in Yubikey Manager.
