### ISSUE TITLE
Windows 10 - SSH Agent doesn't work while running as administrator

### ISSUE THREAD

**Issue by ShivekXR** [keepassxreboot/keepassxc#6703]
## Overview
If I open KeePassXC (right click on the app) as administrator, it can't establish connection with the SSH Agent.

## Steps to Reproduce
1. Open KeePassXC (rigth click) as and administrator.
2. Go to the Settings > SSH Agent
3. Check the message over the "Enable SSH Agent integration" checkbox.

## Expected Behavior
I expected the green **SSH Agent connection is working!** message. Like it is shown while not running as administrator.

## Actual Behavior
The red **Agent protocol error** is shown over the "Enable SSH Agent integration" checkbox.

## Context
If I run as administrator and log in to my database successfully I still can't add my SSH keys to the Agent. Even if I manually right click the entry or go to the entry SSH options, nothing works. There were various other red errors like "Agent connection failed" or "No agent running" but that is not true as I can quickly swap and run it as standard. The keys in PuTTy are loaded every time while running KeePass normally, but I can't manage to do that in admin mode.

PuTTy Pageant

Release 0.70.2-Sourcetree

Build platform: 32-bit Windows
Compiler: Visual Studio 2015 / MSVC++ 14.0 (_MSC_VER=1900)
Source commit: c31e8c714729b8e4fe263e112db636e3929a3f72

---------------------------------

KeePassXC - Version 2.6.6
Revision: 9c108b9

Qt 5.15.2
Debugging mode is disabled.

Operating system: Windows 10 Version 2004
CPU architecture: x86_64
Kernel: winnt 10.0.19041

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
- libgcrypt 1.9.2-unknown

Operating System: Windows 10 Pro

**Comment by droidmonkey** [comment]
You need to run paegent or OpenSSH agent as administrator as well.

**Comment by ShivekXR** [comment]
When I run Pageant as administrator, KeePass finally see the SSH agent. **Thank you!**
@droidmonkey I have a side question - is it because of some sandbox mechanism?

**Comment by droidmonkey** [comment]
Just how ssh agent works, per user
