### ISSUE TITLE
delete temporary files associated with entry attachments

### ISSUE THREAD

**Issue by cyclops1530** [keepassxreboot/keepassxc#6704]
when editing or viewing an entry attachment, the temporary file should be securely deleted once complete

**Comment by droidmonkey** [comment]
already coded, waiting for merge #6606

**Comment by sidmint** [comment]
I have a question regarding this fix: Does this fix wipes the attachment by overwriting its location on disk so that it's not recoverable by software tools? Or it just makes sure the file is deleted the normal way?
