### ISSUE TITLE
View / Always on Top interferes with data entry

### ISSUE THREAD

**Issue by victor-david** [keepassxreboot/keepassxc#6705]
## Overview
When the app is set to be _always on top_, and you edit an entry that has a long delay in its auto-type, upon clicking **OK** on the Edit entry screen, a confirmation dialog (_This has a long delay, are you sure?_)  appears _behind_  the main window. This makes it difficult / impossible to answer the dialog. I could not get the dialog to the point where I could answer it because the main window keeps jumping to the top. I finally went to the task bar, right clicked on the KeePassXC icon, and selected Close all windows. This closed the dialog (only), and I was able to proceed.

## Steps to Reproduce
1. Select View / Always on top.
2. Edit an entry that has a long auto-type delay (not sure what the threshold is. Mine is 10000)
3. Click OK to close the edit entry

## Expected Behavior
The edit entry closes normally or at least the confirmation dialog appears above, not behind, the main window.

## Actual Behavior
At first I thought the app had locked up because I didn't know there was a modal dialog stuck behind the main window. Then I noticed the task bar had multiples for KeePassXC and I was able to use TAB to cycle, but I couldn't select the dialog because the main window keeps winning the _who's on top_ battle.

## Related: Like to see
I'd like to see an option to turn off the _Long delay are you sure?_ dialog. It pops up when I use this entry for auto-type. Unfortunately, the web site in question is quite a pain. It doesn't allow you to copy/paste credentials, and the browser extension triggers a _No can do, call customer support_ dialog. My only options are to type my credentials manually, or use the auto-type feature. However, there's a separate screen for user name, followed by (sometimes painfully slow) screen for the password. Hence, the long delay in my auto-type.

## Context
KeePassXC - Version 2.6.6

Qt 5.15.2
Debugging mode is disabled.

Operating system: Windows 7 Version 6.1 (Build 7601: SP 1)
CPU architecture: x86_64
Kernel: winnt 6.1.7601

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
- libgcrypt 1.9.2-unknown

**Comment by droidmonkey** [comment]
This is not an issue on develop branch, closing as a result.

**Comment by victor-david** [comment]
@droidmonkey - Hi, I don't quite understand. Does this mean the issue has already been fixed and will appear in a later release? Or it's not reproducible?

**Comment by droidmonkey** [comment]
Yes its already fixed and will be part of 2.7.0

**Comment by victor-david** [comment]
Thanks much for the update. Appreciate it. I'm brand new to KeepassXC (been using Keepass original). Really nice job, I like it a lot.

**Comment by droidmonkey** [comment]
Thank you! If you want to try the next release you can use one of our snapshot builds: https://snapshot.keepassxc.org/latest
