### ISSUE TITLE
KeePassXC has a problem while saving the database (using Tails)

### ISSUE THREAD

**Issue by desertcod98** [keepassxreboot/keepassxc#6710]
Overview: 
I am using the version of KeePassXC included in the last version of Tails (updating it did not fix the issue). Basically what happens is that when I open the database (stored in the persistent partition) and I add a new entry, after saving KeePassXC will create a backup of the database (Passwords.old.kdbx) that contains the entries as they are expected, but in the Password.kdbx database the old entries get deleted, while only the newly created entry before saving remains.

Steps to Reproduce:
1. Open database
2. Add entry
3. Save the database
4. Close KeePassXC
5. Open KeePassXC
6. Open the database

Expected Behavior:
Both the new and the old entries are in the database

Actual Behavior:
Only the newest entry remains in the database

Context
I am on Tails, I have saved the database on the persistent partition (Trying to use the volume on a non persistent folder does not solve the issue), doing 'sudo apt update' and 'sudo apt upgrade' did not solve the issue.
The old entries remain in the Passwords.old.kdbx file, but only the newest can be found in Passwords.kdbx

KeePassXC - 2.5.4
Revision: dcca5aa

Operating System: Linux
Desktop Env: Gnome
Windowing System: I do not know :(

First entry created:
![1](https://user-images.githubusercontent.com/86979268/124506122-83cf7980-ddba-11eb-98d7-3402e9ddb6c1.png)

Second entry created:
![2](https://user-images.githubusercontent.com/86979268/124506123-84681000-ddba-11eb-8737-37ccd3e55ca6.png)

Closed KeePassXC and reopened it:
![3](https://user-images.githubusercontent.com/86979268/124506124-8500a680-ddba-11eb-83c0-6fbd2d2c1d48.png)

Only the newest entry remains:
![4](https://user-images.githubusercontent.com/86979268/124506126-85993d00-ddba-11eb-8b6b-75b0ebef1851.png)

**Comment by droidmonkey** [comment]
Use our appimage with the latest version to see if the problem persists.

**Comment by desertcod98** [comment]
using the last appimage fixes the problem! thank you
