### ISSUE TITLE
Remmina doesn't access passwords on reboot.

### ISSUE THREAD

**Issue by ghost** [keepassxreboot/keepassxc#6713]
## Overview
Remmina can't access the database

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Enable secret service, grant access to a folder within the databse for the secret service, install remmina and reboot
2. Unlock the database
3. Start Remmina and try to perform an action that requires password storage

## Expected Behavior

A new entry should be created when creating a new connection in Remmina. When opening an existing connection, Remmina should get the credential from Keepass.

## Actual Behavior
Remmina fails to communicate with Keepass. No new entries are created and existing credentials aren't pulled. Remmina is not listed among the applications using the database in Keepass.

## Context
Removing access to the relevant database folder, then granting it again and restarting remmina fixes the problem until next reboot.

I can still interact with the database via the secret service API through the CLI (the standard CLI for SS, forget what it's called). So it's a remmina issue - BUT it's also a Keepass issue because Gnome Keyring doesn't have this problem with remmina.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.6.4

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux (latest)
Desktop Env: KDE (latest)
Windowing System: X11

**Comment by droidmonkey** [comment]
Please try our develop snapshot, we made significant changes to this service already. https://snapshot.keepassxc.org

**Comment by Aetf** [comment]
dbus log while reproducing the issue?

```
dbus-monitor "destination=org.freedesktop.secrets" "sender=org.freedesktop.secrets"
```
