### ISSUE TITLE
KDBX version advise

### ISSUE THREAD

**Issue by dnai05** [keepassxreboot/keepassxc#6714]
KeePass is using KDBX 4.1 from 5-Jul-2021. From the issues log it seems that KeePassXC will not be compatible with KDBX 4.1 until v2.7 is released. I feel it will be useful to know which version of KDBX we can use with each released version of XC. For example, if I download XC v2.6.6 I don't know which version of KDBX I can connect to. Would it work with a database created by KeePass v2.48 which uses KDBX 4.1?

**Comment by droidmonkey** [comment]
We support kdbx 4.0 and 3.1, same as before.
