### ISSUE TITLE
Show timestamp with seconds in the column and under History

### ISSUE THREAD

**Issue by plorerfisfct** [keepassxreboot/keepassxc#6716]
## Summary
The timestamps in the column and under History do not show seconds.

![1](https://user-images.githubusercontent.com/87186277/125105706-08820680-e0df-11eb-8a06-b841399f3813.PNG)
![2](https://user-images.githubusercontent.com/87186277/125105715-0ae46080-e0df-11eb-89e8-07dd9c7ca58d.PNG)

## Examples
Only under Properties the seconds are displayed.
![3](https://user-images.githubusercontent.com/87186277/125105783-25b6d500-e0df-11eb-88a1-6acca0ffd254.PNG)

## Context
It would be easier to find my entries.

**Comment by droidmonkey** [comment]
This is based on your locale settings in your operating system.

**Comment by plorerfisfct** [comment]
> 
> 
> This is based on your locale settings in your operating system.

Thanks for the answer. Do you know how I can change this? I use Windows 8.1 and Windows 10.

**Comment by droidmonkey** [comment]
https://www.windowscentral.com/how-change-date-and-time-formats-windows-10

**Comment by plorerfisfct** [comment]
> 
> 
> https://www.windowscentral.com/how-change-date-and-time-formats-windows-10

I just tried it and it does not work. I entered HH:mm:ss. What am I doing wrong? Does it work for you?

**Comment by droidmonkey** [comment]
Are you changing the short format? You'll need to restart the program as well. Possibly even log off and back on again.

**Comment by plorerfisfct** [comment]
> 
> 
> Are you changing the short format? You'll need to restart the program as well. Possibly even log off and back on again.

Yes the short time has been changed and have also restarted KeePassXC and Windows system it does not work.

I noticed one thing at the bottom it says this here

s = second (long time only)

That means the short time does not support this, so Windows system does not support seconds for short time. You can enter ss, but in the user interface for example in File Explorer no seconds is displayed.

Would it be possible to add an extra option only for the KeePassXC Windows version that displays seconds?

**Comment by droidmonkey** [comment]
It's possible, yes

**Comment by michaelk83** [comment]
> Would it be possible to add an extra option only for the KeePassXC Windows version that displays seconds?

This would be covered by #2155 , wouldn't it?

**Comment by droidmonkey** [comment]
Yes it sure does
