### ISSUE TITLE
editing a note / a group taking 5 seconds

### ISSUE THREAD

**Issue by AdvisedlyAlburn** [keepassxreboot/keepassxc#6718]
Version : 2.6.6
OS : MacOS 11.4

Example : if I edit the note and click on "save" I'll have to wait 5 seconds. 

More details : 
- Creating a note / editing it / moving it takes 5 seconds. I have maybe 200 passwords. I have around 50 passwords which contain attachments of 1 MB. It's becoming worse and worse the more passwords I add, but it seems that it's especially since I've started to add attachments to some passwords. 
- There is NOT this problem if I edit a note and click "cancel"
- Creating / editing a new group takes 5 seconds on my computer. I have around 40 groups. Deepest nested level is 4 : Root > group A > group B > group C > group D

Please fix this, it's my favorite open source software I even gave it the honor to launch at my computer startup (only a select few apps get this privilege)

**Comment by droidmonkey** [comment]
Do you have your encryption settings to take 5 seconds?

**Comment by AdvisedlyAlburn** [comment]
@droidmonkey Is it this setting? It's at 1s

<img width="1263" alt="Screenshot 2021-07-09 at 20 34 02" src="https://user-images.githubusercontent.com/81878176/125121981-0aef5b00-e0f5-11eb-9118-98babcb71fd2.png">

**Comment by droidmonkey** [comment]
Yes that's the setting. If saving is taking too long then you either need to make your database smaller (remove attachments) or save locally to your device. Not sure if you are saving to a network share or not. A ~50MB database shouldn't take 5 seconds to save, however. There really isn't anything for us to "fix".

**Comment by AdvisedlyAlburn** [comment]
- It's saved on a local folder on my mac. This folder is synced with nextcloud, not sure if it's important. 
- Got it that I should remove attachments but this feature is very useful. KeepassXC allows me to create an identity isolated in a group and I can create a guy named Bob for example and create a life around him, add pictures as attachments etc. All is centralized, if I want to change something I just have to go to the group dedicated to the identity.

**Comment by droidmonkey** [comment]
Keepass databases are not optimized to store large  files. For better or worse we follow this standard. Storing files should be done with Cryptomator or VeraCrypt.

**Comment by AdvisedlyAlburn** [comment]
Isn't it possible to change encryption type for attachments? (new feature)

**Comment by droidmonkey** [comment]
No because that breaks compatibility with keepass. 

You could disable "save after every change" which will prevent you having to wait every time you do something to your database. 

There isn't anything for us to do here so I am closing this issue.
