### ISSUE TITLE
When sorting groups, do place the Recycle Bin at the very bottom of the list

### ISSUE THREAD

**Issue by tgucci** [keepassxreboot/keepassxc#6719]
Well, I guess the title speaks volumes. Having the Recycle Bin in the midst of your list of secrets entries does not make a lot of sense, other than causing annoyance and confusion. In my opinion, it would be more appropriate if, when sorting groups A-Z, the Recycle Bin is placed at the very bottom of the list of groups.

Thanks for considering this feature request and
thanks for this epic fork of a great Project.

tgucci

**Comment by droidmonkey** [comment]
#6495
