### ISSUE TITLE
Convert Online Help into a Wiki

### ISSUE THREAD

**Issue by tgucci** [keepassxreboot/keepassxc#6722]
Nothing is more frustrating than opening online help of *a FOSS* project and discover the provided help is a developer maintained page that is not editable. Unfortunately, this is the case with KeePassXC.

Please consider converting the Online Help for KeePassXC into a Wiki.

If there is a wish for it, I would personally undertake the task of converting the current Online Help into a Wiki (I would even host it, if desired. High quality hosting facilities are available and the whole thing would be a contribution, of course).

**Comment by droidmonkey** [comment]
Feel free to contribute to our _official_ documentation: https://github.com/keepassxreboot/keepassxc/tree/develop/docs%2Ftopics

**Comment by tgucci** [comment]
Dear Sir!

You don't see the benefits for the user (user friendliness) to have this information organized in a wiki? And without the need for using potentially proprietary word processors? And checking them out after editing them in it?

Especially if I am offering to organize (even the docx files) in a Wiki? Of course I would hand the product over to you for maintaining (if desired). You may even choose what Wiki I use.

Regards

**Comment by droidmonkey** [comment]
We have absolutely no interest in a freely edited wiki. Everything we do is through git and controlled by the project maintainers. 

All of our documentation is in plain text using asciidoc. You can use whatever text editor you please.

**Comment by tgucci** [comment]
Would you mind explaining why not? Is not the whole Wiki concept a story of success? For both users and maintainers (of static help pages)?
