### ISSUE TITLE
Database locking at user switch in macOS is not configurable

### ISSUE THREAD

**Issue by pimswj1** [keepassxreboot/keepassxc#6726]
## Overview
With release 2.4.2 bug  #2642 was fixed, so database was properly locked hereafter when switching users in macOS
It seems that this behavior is not dependent on setting "Lock databases when session is locked or lid is closed" in KeePassXC Security Preferences. I don't know if that is by design, or bug.

## Steps to Reproduce
- Login as user A, start KeePassXC, and verify that database is unlocked.
- Switch from user A to B (via menu bar), and login as B
- Switch back from B to A (via menu bar), and login as A again. The database is now locked.

## Expected Behavior
I would expect KeePassXC not lock database when referred setting is NOT checked.

## Actual Behavior
Database is always locked after switching users forth and back (independent of referred setting)

## Context
I use home (without KeePassXC) and work account (with KeePassXC), and switch several times a day between both users. Now I have to manually enter password each time when switching to work account. I would prefer to enter password only once a day (imo. this would be a acceptable trade-off between security and convenience).

## Debug info
KeePassXC - Version 2.6.6
Revision: 386b79a

Qt 5.15.2
Debugging mode is disabled.

Operating system: macOS 11.4
CPU architecture: x86_64
Kernel: darwin 20.5.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
- libgcrypt 1.9.3

**Comment by randallkn** [comment]
I think this change is worthy of a release!
