### ISSUE TITLE
fuzzy password entry (unlock)

### ISSUE THREAD

**Issue by kevinlawler** [keepassxreboot/keepassxc#6729]
## Summary
(Inspired by how swipe phone keyboards error-correct.) This applies especially to passphrases consisting of multiple dictionary words versus but also to passwords of random special and non-special characters.

On a failed attempt a database should attempt to unlock by exhausting strings within a small edit distance of the input string.

For example, if one of the words in my passphrase is "feature" and I instead type "faeture", the database should still unlock.

**Comment by droidmonkey** [comment]
Absolutely not, sorry this is not a good idea.

**Comment by kevinlawler** [comment]
Based on what rationale? This makes it easier to use high entropy passphrases. The low entropy model is already broken, but could still be made opt-in for those instances.

**Comment by droidmonkey** [comment]
Every unlock attempt incurs the key derivation delay (1 second by default). Given nearly unlimited trials for any reasonably long password this would cause the application to essentially deadlock in the hopes of fixing your typo.

**Comment by kevinlawler** [comment]
I see. I assume the delay you reference is from key stretching and not from a kind of simple timer that could be sidestepped. I have long been opposed to key stretching, though it is a bad idea so entrenched in the field now that it would take great effort to reverse opinions. This also is not the place to do it.

As far as routing around, it could be possible in the case of misspelled dictionary words. The swipe keyboards on the latest phones do this well. That is, they really only need 1 additional guess or perhaps small c ~ 4 and not a large O(1). So really you could get away with one or a small number of additional guesses, parallelizing if necessary. The extra seconds would not be noticeable compared to the unhappy path of rejecting incorrect user input. Because of the reliance on language correction I don't ask for this feature to be implemented, or expect to see it on any near time frame. I do suspect the field will move in this direction eventually, as I observe unlocking databases on the phone to work surprisingly better than on the notebook, because it reduces the odds that dictionary words were typed incorrectly.

Perhaps there is an OS-supported plugin at the UI text field level that would correct misspelled words. Then it could be enabled for database files which use dictionary seed phrases.

**Comment by droidmonkey** [comment]
You are making a huge assumption that the database credential is a combination of dictionary words. This definitely does not hold true for all cases. It also assumes there is no deliberate typo or injection of entropy (capital letters,  numbers etc). Overall we are not in the business of assuming the user made a mistake and attempting to overcome it by some complicated set of algorithms,  that is usually where security vulnerabilities start to creep in.

Regarding key derivation (stretching), there is no downside to this method when using a robust algorithm. We default to Argon2 which is proven to be incredibly resilient to attacks. Why do you suggest this is a bad technique? The alternative is what? No key derivation leading to brute force attempts?
