### ISSUE TITLE
gpg 

### ISSUE THREAD

**Issue by FranciscoG** [keepassxreboot/keepassxc#673]
https://keepassxc.org/verifying-signatures

gpg --fetch-keys https://keepassxc.org/keepassxc_master_signing_key.asc

gpg --verify KeePassXC-2.2.0.dmg.sig
gpg --verify KeePassXC-$VERSION-x86_64.AppImage.sig
```
pg: assuming signed data in 'KeePassXC-2.2.0.dmg'
gpg: Signature made Sun Jun 25 19:55:34 2017 EDT
gpg:                using RSA key C1E4CBA3AD78D3AFD894F9E0B7A66F03B59076A8
gpg: Good signature from "KeePassXC Release <release@keepassxc.org>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: BF5A 669F 2272 CF43 24C1  FDA8 CFB4 C216 6397 D0D2
     Subkey fingerprint: C1E4 CBA3 AD78 D3AF D894  F9E0 B7A6 6F03 B590 76A8
francisco.gutierrez1 in ~/Downloads $ gpg --keyserver pool.sks-keyservers.net --recv-keys 0xBF5A669F2272CF4324C1FDA8CFB4C2166397D0D2
```

shasum -a 256 -c KeePassXC-2.2.0.dmg.DIGEST
KeePassXC-2.2.0.dmg: OK

**Comment by phoerious** [comment]
The signature is fine ("Good signature"). Just just haven't trusted our public key.

I suppose we need to update our website with clearer instructions. You are not the first one to ask this one.

**Comment by FranciscoG** [comment]
sorry this got accidentally posted for some reason before I could finish writing (hit a wrong key).  my full issue was posted [https://github.com/keepassxreboot/keepassxc/issues/674](here) but either way you answered my question.  thanks!

**Comment by phoerious** [comment]
Just make sure the fingerprint is correct and it says "good signature". If you [trust our master key](https://www.gnupg.org/gph/en/manual/x334.html), the warnings will go away, but really important are only those two things: finger print and signature validity.

**Comment by sts10** [comment]
FYI the [Qubes OS page on verifying signatures](https://www.qubes-os.org/security/verifying-signatures/) (which KeePassXC's [verifying signatures how-to](https://keepassxc.org/verifying-signatures) already has a link to) discusses the key trust aspect of the process decently well.
