### ISSUE TITLE
Synchronize same user/password between several databases

### ISSUE THREAD

**Issue by LetMeR00t** [keepassxreboot/keepassxc#6730]
## Summary
This is a new feature for the product of what I imagine. One big feature of KeepassXC is to open several databases at the same time. It would be great to have the possibility to somehow synchronize same user/password between several databases. 

## Examples
Just a pop-up when the entry is changed if other entries are found in other databases and if so, ask if synchronization should be done.
Or, we can also imagine some parameter that says "synchronize this entry with another one in another database" and then choose the according entry and when changes happens on one entry, the other ones is automatically updated

## Context
I have several databases on my computer but they are separated and used by different people elsewhere and I assume that it would be great to somehow say that if you are modifying an entry, check if the same combinaison user/password exists in the same database (weird as you have references) or in the other opened databases. Then, propose to synchronize the changes.
For the moment, we have to made the changes manually for the same user/password entries placed in several databases. No synchronisation/automatic detection of same combinaison of user/password is done.

**Comment by droidmonkey** [comment]
Use keeshare, see the user guide for more information.
