### ISSUE TITLE
gpg "warning"

### ISSUE THREAD

**Issue by FranciscoG** [keepassxreboot/keepassxc#674]
I'm sure this is nothing but I just wanted to ask either way because I'm not very familiar with checking downloads via gpg.  When I checked the DMG via gpg I saw this warning in the results.  Is this something that I need to be concerned about?  thanks!

**gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.**

I followed the steps outlined here: https://keepassxc.org/verifying-signatures

specifically choosing this method to import the public master key:
`gpg --fetch-keys https://keepassxc.org/keepassxc_master_signing_key.asc`

When I ran this command:
```
$ gpg --verify KeePassXC-2.2.0.dmg.sig
```

I got this:
```
gpg: assuming signed data in 'KeePassXC-2.2.0.dmg'
gpg: Signature made Sun Jun 25 19:55:34 2017 EDT
gpg:                using RSA key C1E4CBA3AD78D3AFD894F9E0B7A66F03B59076A8
gpg: Good signature from "KeePassXC Release <release@keepassxc.org>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: BF5A 669F 2272 CF43 24C1  FDA8 CFB4 C216 6397 D0D2
     Subkey fingerprint: C1E4 CBA3 AD78 D3AF D894  F9E0 B7A6 6F03 B590 76A8
francisco.gutierrez1 in ~/Downloads $ gpg --keyserver pool.sks-keyservers.net --recv-keys 0xBF5A669F2272CF4324C1FDA8CFB4C2166397D0D2
```

The shasum check was ok.
```
$ shasum -a 256 -c KeePassXC-2.2.0.dmg.DIGEST
KeePassXC-2.2.0.dmg: OK
```

**Comment by FranciscoG** [comment]
ooops this got posted twice for some reason

**Comment by phoerious** [comment]
Well, thanks for reformulating your question with more words, but no need. :-) -> 673
