### ISSUE TITLE
browser integration with sandboxing enabled

### ISSUE THREAD

**Issue by D0nnieD4rk0** [keepassxreboot/keepassxc#6740]
recently started playing around with firejail and im wondering what files/binaries are required to be whitelisted for the browser extension to see the client

**Comment by droidmonkey** [comment]
You need to allow the browser to start the proxy application and connect to the local socket. Socket location can be found at https://github.com/keepassxreboot/keepassxc/blob/089c8df01d1676abb6d084edf4da7038bc0d9be2/src/browser/BrowserShared.cpp#L34

Your best bet is to strace your browser and look for failures.
