### ISSUE TITLE
Documentation problem: the user guide leaves it unclear whether the URL field allows multiple entries

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [keepassxreboot/keepassxc#6742]
So far as I can tell, the [user guide](https://keepassxc.org/docs/KeePassXC_UserGuide.html) leaves it unclear whether one can enter multiple URLs within the URL field of a KeePassXC record. The URL field turns red when in various ways I try to enter more than one URL, so perhaps one cannot do that - and must instead use what the guide calls 'references'. I feel the guide should make such matters clear.

**Comment by droidmonkey** [comment]
You put additional urls under the browser settings. The user guide makes no mention of putting multiple urls into the url field.

**Comment by LinuxOnTheDesktop** [comment]
> You put additional urls under the browser settings. 

But where are those settings?

> The user guide makes no mention of putting multiple urls into the url field.

Indeed. Nor does it say that one cannot do that - even though it is fairly natural thing to want to do.

**Comment by droidmonkey** [comment]
The field title is "URL:". Browser settings are found when editing the entry, on the left side there should be a browser option unless you have disabled browser integration. Browser integration is the only thing that uses multiple urls. 

https://keepassxc.org/docs/KeePassXC_UserGuide.html#_advanced_usage

**Comment by LinuxOnTheDesktop** [comment]
This infelicity remains:

> Nor does it say that one cannot do that - even though it is fairly natural thing to want to do.
