### ISSUE TITLE
False positive autotype match

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [keepassxreboot/keepassxc#6743]
## Overview

Autotype offers two 'fills' for a website, even though only one fill matches.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Visit https://old.reddit.com/.
2. Have an autotype entry for the URL `https://old.reddit.com/`
3. Have an autotype entry for the URL `http://philpapers.org/`
4. Press the autotype keyboard shortcut.
5. See that the program asks you to choose between the credentials at issue in 2 and 3.

## Expected Behavior
Only the credentials for the relevant website (see, above, 1 and 2) should be offered.

## Actual Behavior
See 5 above.

## Context

KeePassXC - Version 2.7.0-snapshot
Build Type: Snapshot
Revision: 9b2b861

Qt 5.15.2
Debugging mode is disabled.

Operating system: Windows 10 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.19043

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
- Botan 2.17.3

EDIT: This problems seems to be a regression: I did not have the problem with the release as against 'snapshot' version of KeePassXC.

**Comment by droidmonkey** [comment]
Auto-Type doesn't look in the url field UNLESS you enable match domain in window title. In which case it trys to match the entry url with a domain that appears in the window title. 

You need to provide your autotype settings for each entry. What is set for the window title matching? 

This could be #6413 but can't tell based on your report.

**Comment by LinuxOnTheDesktop** [comment]
The window title matching option - I take it that what is at issue is shown in the following two screenshots. (You might want to note that I had to take these screenshot on Linux; on Windows, three different screenshoters failed to register the KeePassXC window.)

![image](https://user-images.githubusercontent.com/47056543/126072874-f737b3e4-789d-4187-af63-7bfbdf7380ce.png)

![image](https://user-images.githubusercontent.com/47056543/126072880-b487e02b-7b68-4e20-9afb-5525b0c9e9bc.png)

Perhaps the second of those two entries is problematic.

**Comment by droidmonkey** [comment]
We disable screenshot by default on windows and Mac (not possible on linux). You can enable them using command line switch.

The definition of "Mozilla Firefox" for the the second screenshot is your problem.

**Comment by LinuxOnTheDesktop** [comment]
I take it then that I should entirely remove the 'Mozilla Firefox' window association. I have done that.
