### ISSUE TITLE
Flattened icon in menu bar

### ISSUE THREAD

**Issue by pabroux** [keepassxreboot/keepassxc#6745]
## Flattened icon in menu bar
Hello everyone,

First, thank you for your great work.

Second, my bug is about the icon in the menu bar. When I am focusing another screen (dual screen), the icon in the other screen become flatten. Nothing to worry about but it'll be great to solve it.

## Steps to Reproduce
1. Reduce KeePassXC (cmd+M on MacOS);
2. Select another device/screen.

## Expected Behavior
Having both icons with the same size (not flatten). No matter which device/screen is selected.

## Actual Behavior
Here is what I get:
<img alt="Screenshot 2021-07-19 at 9 57 52 AM" src="https://user-images.githubusercontent.com/72023070/126124165-ba2fb21a-0017-49c3-902a-7d03f833501f.png">

The icon is flattened compare to the other screen (focused one):
![Screenshot 2021-07-19 at 9 57 43 AM](https://user-images.githubusercontent.com/72023070/126123925-7e0eea2c-bfa5-411a-8b20-712447c2833b.png)

## Context
KeePassXC - Version 2.6.6
Revision: 386b79a

Qt 5.15.2
Debugging mode is disabled.

Operating system: macOS 11.4
CPU architecture: arm64
Kernel: darwin 20.5.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (only unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
- libgcrypt 1.9.3

Operating System: macOS Big Sur 11.4 M1

**Comment by droidmonkey** [comment]
This is a Qt bug on mac that we gave no control over unfortunately. It was reported before and reported to Qt.

**Comment by pabroux** [comment]
Ok, my bad. Thank you.
