### ISSUE TITLE
Browser integration with multiple browsers

### ISSUE THREAD

**Issue by parabolapersuader** [keepassxreboot/keepassxc#6746]
I run KeePassXC 2.6.6 from the PPA. And I also run a few variations of Firefox:
- Firefox (from .deb)
- TorBrowser
- Firefox (flatpak)
- LibreWolf (flatpak)

The system install is handled painlessly by KeePassXC. Which I can't say about the others.

There was a way to specify one particular path, which meant choosing a second browser that could have the Browser Integration. Now, when I rechecked the menus for this ticket I notice I can't even find the filed in which I could specify one particular path for the Browser integration. And there is a Tor Browser option, but the app probably expects a system install and looking only for the default paths.

How can I have more than one (it used to be two) browsers connected to the running KeePassXC instance?

**Comment by droidmonkey** [comment]
For each of the non system browsers you will need to manually deploy the native messaging json configuration file. We let you specify one custom browser, beyond that it must be done manually. Consult your browsers documentation for where to place the file.
