### ISSUE TITLE
KeePassXC public key cannot be retrieved

### ISSUE THREAD

**Issue by walt-r** [keepassxreboot/keepassxc#6748]
## Overview
I am trying to verify the latest download of KeepassXC. I get an error when I attempt to retrieve the public key.

## Steps to Reproduce
I tried both the methods described at https://keepassxc.org/verifying-signatures/

## Expected Behavior
retrieval of public key

## Actual Behavior
% gpg --fetch-keys https://keepassxc.org/keepassxc_master_signing_key.asc
gpg: requesting key from 'https://keepassxc.org/keepassxc_master_signing_key.asc'
gpg: WARNING: unable to fetch URI https://keepassxc.org/keepassxc_master_signing_key.asc: General error

% gpg --keyserver keys.openpgp.org --recv-keys CFB4C2166397D0D2
gpg: keyserver receive failed: General error

## Context
I'm downloading version KeePassXC-2.6.6-x86_64.dmg onto my macbook pro running MacOS 10.15.7
I'm using iTerm2 terminal
Z-Shell: zsh 5.7.1 (x86_64-apple-darwin19.0)

**Comment by droidmonkey** [comment]
Seems like an issue with your gpg client. Also it is unnecessary to do that for macOS. The application is signed by our developer certificates and notarized by Apple.
