### ISSUE TITLE
on narrow screen widths, it's hard to use

### ISSUE THREAD

**Issue by earboxer** [keepassxreboot/keepassxc#6749]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. launch app on a device with a narrow screen (such as a pinephone running phosh, with 
2. log in to database
3. notice how the categories sidebar doesn't collapse, takes up much of the screen

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
the window should resize and the sidebar should collapse for smaller windows

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
it doesn't look nice, and is barely usable on a linux phone.

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.6.4
Revision: 34a78f0

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: phosh
Windowing System: Wayland

**Comment by droidmonkey** [comment]
See #5676

**Comment by Keksimus69** [comment]
Sorry to necro this, but if you run `$ scale-to-fit org.keepassxc.KeePassXC true` it will force the application to scale to the screen. Works really well on my device. I've tested it on Phosh with 250% scaling and the horizontal screen resolution on my device is 1080 pixels. Not sure how good it will look on a PinePhone cause of the lower resolution and slightly smaller screen, but it might help.
