### ISSUE TITLE
KeeShare groups bulk password change [w. conditions]

### ISSUE THREAD

**Issue by yi0n** [keepassxreboot/keepassxc#6753]
## Summary
Change each password of a group of KeeShare databases with certain conditions:
a) random password for each entry
b) the same password for all entries

Additional feature on top: Send the new password(s) by a transport channel (Mail, Telegram/Signal, ...) to a specific person (by direct input or by reading an extra fieldset in each entry)

## Context
I administer different databases, where hierarchical groups are being "exported".
In one database I have familiy members, some coworkers and friends as groupnames. Each one has subgroups (public, cloud and local).
Public (KeeShare-DB in export mode) exposed to the internet from the homeserver.
Cloud (KeeShare-DB in export mode) synced by a sync-app to a cloud storage.
Local (KeeShare-DB in syncronization mode) only available on the local network.
Changing and informing the person about the new password for each KeeShare-DB is time consuming.
Is something like a bulk change with different kind of depth (group/entry-wise) possible?

**Comment by droidmonkey** [comment]
You want to change the password for the shared group, correct?
