### ISSUE TITLE
Application hangs, won't open if previously database network location unavailable

### ISSUE THREAD

**Issue by sovamind** [keepassxreboot/keepassxc#6755]
## Overview
Starting in the last few versions I've noticed that the application will hang and not start properly if the network location where my Keepass DB is located is unavailable.  This happens most frequently when I'm using the database that is on our company file server and I'm not connected to the VPN.

## Steps to Reproduce
1.  Open a database on a network share (mapped drive)
2.  Close Keepass XC
3.  Make the network share inaccessible (my case disconnect from VPN)
4.  Open Keepass XC, it will hang and never finish starting up.

## Expected Behavior
Application should start and either give an error about being unable to locate the DB or just close the tab for the additional DB and have the user manually reopen it.

## Actual Behavior
Keepass XC doesn't finish starting and is left hung with a white window.  Cannot close or kill it with Task Manager.  Only way to fix it is to reconnect the network drive (VPN) then it will finish starting up.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.6.6

Operating System: Windows
Desktop Env: Windows 10

**Comment by droidmonkey** [comment]
I couldn't replicate this. I have a network share mounted to Z:/, loaded a database from it and unlocked it, closed app, disconnected network, reopened app and I got the expected error message:

![image](https://user-images.githubusercontent.com/2809491/126827600-02c26136-37dd-430a-ba47-095e2170b0fc.png)

Can you be more explicit on how you are loading the database if different then this?

**Comment by sovamind** [comment]
Did you leave your network share mounted but inaccessible?   The share needs to still be mapped, but not able to respond, such as when the VPN connection or server is down.  Try using your network drive location but then unplugging the server.  That should reproduce it.

**Comment by sovamind** [comment]
We've had to turn off the "reconnect to databases" option in settings to avoid this bug.

**Comment by sovamind** [comment]
Here is video of the issues: https://1drv.ms/v/s!Anyyfj9UbKyouaQFMWl0OHpJRnPcfQ?e=dCweCr

In the video:
1) I show how with the application fully closed, I can open it with the VPN running, with no issue.
2) I then quite the application, disconnect from VPN, and try and open it.
3) Application won't load and becomes non-responsive.
4) I then reconnect to the VPN, then the app finishes loading and starts working properly.

**Comment by TheHeroBrine422** [comment]
I am having this issue in the exact same context. server goes down, keepassXC completely freezes to white screen.

**Comment by sovamind** [comment]
I don't believe this was ever fully fixed. We had to move to using private cloud storage that syncs files to the local disc. However, this has proven to create sync issues between KeepassXC and the cloud sync. Using the "move file into position" save option fixes the sync issues but means that the version control for the file in the cloud storage doesn't work as the file is constantly replaced and at version 1.0

**Comment by droidmonkey** [comment]
That is definitely a limitation of your cloud storage solution (client side). Use direct write saves to maintain the inode/fd so that its version control doesn't see it as a new file. Our saves work totally fine with mainstream solutions like Google drive, OneDrive, Syncthing, etc.

**Comment by TheHeroBrine422** [comment]
For me I am using a samba share on windows. So I use a path like \\192.168.1.1\keepass_file



Honestly since I am a dev I might just try to figure out a fix myself and make a PR at some point. The passwords to my server are in a local keepass database, so anytime my server goes down it makes things painful. I figured out to use Strongbox on my Mac to access it since KeepassXC just won't work.
