### ISSUE TITLE
minimize after unlocking vs. lock after minimizing -> impossible to keep database open

### ISSUE THREAD

**Issue by sniff-numeral** [keepassxreboot/keepassxc#6757]
## Overview
Activating the settings "Minimize window after unlocking databases" and "Lock databases after minimizing the window" at the same time will make it impossible to keep a database open.

## Steps to Reproduce
1. Settings -> General -> Basic Settings -> Startup -> Check "Minimize window after unlocking databases"
2. Settings -> Security -> Convenience -> Check "Lock databases after minimizing the window"
3. If a user opens a database, the window will automatically minimize and therefore open databases will be locked.

## Expected Behavior
Maybe make it impossible to activate both settings together with an additional warning/explanation for the user.

## Context
KeePassXC - Version 2.6.6
Revision: 9c108b9

Qt 5.15.2
Debugging mode is disabled.

Operating system: Manjaro Linux
CPU architecture: x86_64
Kernel: linux 5.10.49-1-MANJARO

**Comment by droidmonkey** [comment]
I've always found lock after minimizing to be a silly setting. It also cause issues with copy to clipboard if it's enabled. I'm in favor of removing it entirely. We have a timeout lock for a reason.

**Comment by sniff-numeral** [comment]
To me it just doesn't make sense why the database shouln't be locked after minimizing. In my use case, Keepass is always minimized and databases closed in the systray. Logins are mostly required by the web browser and handled by the KeePassXC-Browser addon. I only open Keepass manually to copy&paste. It's set to bring the window to the background when something is copied. After I'm done with copy&paste I close/minimize the window back to tray. I very much expect the database to be closed after that, because it's just not needed for a while. The timeout function is only used as a backup, in case I forget to close the database manually. But I see, it causes some trouble in other scenarios.
