### ISSUE TITLE
KeePassXC slow to launch on macOS

### ISSUE THREAD

**Issue by lapcat** [keepassxreboot/keepassxc#6758]
KeyPassXC is slow to launch on every launch. I'm using KeyPassXC 2.6.6 Revision 386b79a on macOS 10.14.6 Mojave.

If I launch it from Terminal with /Applications/KeePassXC.app/Contents/MacOS/KeePassXC I see the following message:

`qt.qpa.fonts: Populating font family aliases took 877 ms. Replace uses of missing font family "Monospace" with one that exists to avoid this cost.`

**Comment by shemeshg** [comment]
Confirmed in Prod
However In develop it is ok (solved)

```
QFont Font::fixedFont()
   // Qt doesn't choose a monospace font correctly on macOS
    fixedFont = QFontDatabase().font("Menlo", fixedFont.styleName(), fixedFont.pointSize());
```

Anyway, it is endless chase, 

See
https://forum.qt.io/topic/119302/missing-font-family-warning-on-macos/3


because now we have

```
qt.qpa.fonts: Populating font family aliases took 313 ms. Replace uses of missing font family "Roboto-bold,roboto" with one that exists to avoid this cost.
```

because of C29_*._Term.svg and C30_konsole.svg.

**Comment by droidmonkey** [comment]
Yes we did fix font loading in develop, but that was also backported to 2.6.5. So this also triggers when loading fonts in an SVG? That is nuts... we will need to clean out the SVG font names then.
