### ISSUE TITLE
Ubuntu apt not updating to 2.6.6 from 2.4.3

### ISSUE THREAD

**Issue by rmah13** [keepassxreboot/keepassxc#6759]
I just solved my Keepassxc snap / browser sandboxing issue by downloading Keepassxc through apt (browsers are snap). When I restarted the browser per the instructions after installing through apt, the browser extension alerts me that the version is 2.4.3 and will not allow me to copy and paste usernames/passwords. 

I tried running apt update / apt upgrade and Ubuntu 20.04 gnome is not recognizing/pushing keepassxc 2.6.6. 

New to Linux so it's possible there's other steps I'm missing?

**Comment by rmah13** [comment]
KeePassXC - 2.4.3
KeePassXC-Browser - 1.7.8.1
Operating system: Linux x86_64
Browser: Chrome/Chromium 91.0.4472.164

**Comment by droidmonkey** [comment]
You cannot use a snap based browser with keepassxc browser integration. The browser must be natively installed at this time.

Use our appimage or snap package to easily get the latest version of keepassxc. You can also use our ppa to get it natively. See our dowoads page for the options: https://keepassxc.org/download/#linux
