### ISSUE TITLE
Generate and validate BIP39-compatible seeds

### ISSUE THREAD

**Issue by sowbug** [keepassxreboot/keepassxc#676]
https://github.com/bitcoin/bips/blob/master/bip-0039.mediawiki

These are like Diceware, but a little less dense (11 bits per word rather than ~13), and they have a checksum so it's easy to validate them. This is a Bitcoin thing, but they're generally useful as long memorable passphrases.

**Comment by droidmonkey** [comment]
We won't be incorporating this.

**Comment by sowbug** [comment]
Thanks for considering it.

**Comment by yu-alvin** [comment]
@sowbug You can add your own wordlists in the (KeePassXC Program Folder)/share/wordlists. Just throw the BIP39 words into a file and drag them into the folder.

**Comment by sowbug** [comment]
Thanks. That's a good start. BIP39 follows a format that includes a
checksum word, so it's very unlikely a random set of words would be valid,
but your approach will still make for legible and easy-to-type passphrases.
