### ISSUE TITLE
Search result showing password

### ISSUE THREAD

**Issue by sagaban** [keepassxreboot/keepassxc#6763]
## Overview
Username is obfuscated and password is being shown when searching for a specific entry
![image](https://user-images.githubusercontent.com/5540774/126847513-0a3b4cc7-027c-4f0d-94d9-9949e0485e28.png)

## Steps to Reproduce
1.  Open the app
2.  Search for an entry
3. Take a look at the search result

## Expected Behavior
Username should be shown, and password obfuscated in the search result

## Actual Behavior
Username is obfuscated and password is being shown when searching for a specific entry

## Context
Linux version (Linux Mint 20.2 Uma base: Ubuntu 20.04 focal) using a password and a key file.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.6
Revision: 9c108b9

Qt 5.12.8
Debugging mode is disabled.

Operating system: Linux Mint 20.2
CPU architecture: x86_64
Kernel: linux 5.4.0-80-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- libgcrypt 1.8.5

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: Cinnamon
Windowing System: X11

**Comment by droidmonkey** [comment]
View -> Show passwords (make sure it's unchecked)
