### ISSUE TITLE
Hebrew Translation

### ISSUE THREAD

**Issue by avma** [keepassxreboot/keepassxc#6764]
## Summary
Hi,
I translated all strings into Hebrew (program and web 100% done) however, while running the program in Hebrew, I noticed quite a few untranslated phrases, so probably the source needs an update.
Also it would be nice I you could pull Hebrew from transifex...
My Regards
Avi

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )
![2021-07-25_10-14](https://user-images.githubusercontent.com/7680483/126891016-5f86b489-41c3-4439-91d8-859c612f1ef3.png)
![2021-07-25_10-16](https://user-images.githubusercontent.com/7680483/126891017-5b030228-3cae-48e3-939b-fe460392a3e8.png)

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )

**Comment by droidmonkey** [comment]
That is done on release of a version. You can manually download the translator file and replace it in your install if you like.

**Comment by avma** [comment]
Right, this was **after** I downloaded the latest 100% translated (by me) Hebrew **.ts**  file from **transifex**, compiled it to **.qm** and placed it in `'/usr/local/share/keepassxc/translations'`. 
As you can notice in the above screenshots, there are still untranslated phrases (these are but a few examples, there are more..) although  **transifex** states 100% for Hebrew. 
Is it possible that the current .ts file on transifex does not contain ALL translatable strings?

**Comment by droidmonkey** [comment]
Are you running version 2.6.6 or a develop snapshot?

**Comment by avma** [comment]
Here are the debug information:
KeePassXC -  2.7.0-snapshot
 Snapshot
 f770edb
Qt 5.12.8
debug mod off.
 Linux Mint 20.2
 CPU: x86_64
 linux kernel 5.8.0-63-generic
enabled extensiond:
- auto-type
- keepasscx-browser
- agent SSH
- KeeShare (signed and unsigend)
- YubiKey
- secret aigent
cipher library :
- Botan 2.12.1

**Comment by droidmonkey** [comment]
Just to be sure, you downloaded the final translation for keepassxc_2.7 ?

**Comment by avma** [comment]
OK this is what i found out (and fixed) this morning...
Downloaded the latest translated keepassx_en_2.7.ts  from transfix again and opened it this time with **QT linguist**. looks like transfix is failing to perform all check and validations (accelerators, periods (.), double space, etc') but QT linguist grabbed all that so it was not that hard to fix.
Now all looks good now (see attached), my guessing is this has something to do with the **accelerators**.
![2021-07-26_14-36](https://user-images.githubusercontent.com/7680483/126982773-c8cb8498-04ff-4291-a8ef-b8a6a110abf4.png)
BTW
I'm using transfix to translate other projects too  (MusicBrainz picard is one example) and never had problems with failing accelerators...

**Comment by droidmonkey** [comment]
Are accelerators a Hebrew feature?

**Comment by avma** [comment]
Keyboard accelerators? They are used the same way as in English
