### ISSUE TITLE
Clear LastDir setting when remember databases is disabled

### ISSUE THREAD

**Issue by chaserene** [keepassxreboot/keepassxc#6765]
## Summary
currently KeePassXC remembers the folder of the last used database, and this information persists even through application restarts (not just within a session as #2314 implies, though that issue is 3 years old so the behavior might have changed since then).

please create an option to control whether KeePassXC remembers the last used directory. if this option is turned off, forget the last used location as soon as the file picker is closed, such that when the file picker opens again, it starts in a default location, like the user's home directory.

## Examples
add a tick box in Tools -> Settings -> General -> Basic settings -> Startup, e.g. "Remember previously used database location". I'd also recommend to set this option to be off by default.

## Context
the application shouldn't necessarily reveal the user's password database file to an intruder. not remembering previously used databases is a right step toward this, but insufficient since most people use a single database, so location identifies the file.

**Comment by droidmonkey** [comment]
This is already an option on the application settings

**Comment by chaserene** [comment]
@droidmonkey where? because there is no such setting in Tools -> Settings -> General -> Basic settings -> Startup, and that's where I would look for it. I can control only whether the databases are remembered or not. their location is remembered regardless.

I'm using 2.6.6.

**Comment by droidmonkey** [comment]
Ok I see the problem, the configuration setting "LastDir" is not cleared out when the setting to remember the last databases is disabled.
