### ISSUE TITLE
KeePassXC US Intl special characters wronlgy handled (seems new error in Qt)

### ISSUE THREAD

**Issue by tobias-weiss** [keepassxreboot/keepassxc#6767]
## Overview

When unlocking the database, certain characters (i.e. ") is not recognized but only as whitespace. To circumvent the problem I have to make the password input visible.

References:
https://github.com/keepassxreboot/keepassxc/issues/5517
https://github.com/keepassxreboot/keepassxc/issues/918

As last comment in #918 indicates the problem with QT re-appeared.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
please see beforementioned issues

## Expected Behavior
use US Intl keyboard layout wtihout problems

## Actual Behavior
I have to unhide my password entries or avoid certain characters in my passphrases.

## Context

Debian Bullseye ships Qt 5.15.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.6.2
Revision:  e9b9582

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux Debian Bullseye
Desktop Env: Gnome
Windowing System: X11/Wayland

**Comment by tobias-weiss** [comment]
Could you please kindly indicate to where to file the Qt bug? Or do you know if they already aware about this?

**Comment by droidmonkey** [comment]
It's already filed with qt

**Comment by tobias-weiss** [comment]
Thank you.
