### ISSUE TITLE
Double tab on latest Chrome

### ISSUE THREAD

**Issue by rldleblanc** [keepassxreboot/keepassxc#6768]
It appears that Google Chrome 92.0.4515.107 on Debian Linux bullseye is causing a double tab to be entered when preforming autotype. The behavior is not seen in FireFox or Kate.

## Steps to Reproduce
Open up Google Chrome to webpage, perform autotype (after entering username, it performs two tabs instead of one as shown in the AutoType settings).

## Expected Behavior
Only one tab is entered as sepecified in the AutoType settings.

## Actual Behavior
Two tabs are entered for one TAB entry in the AutoType

## Context
Worked fine before the last Chrome update, continues to work fine on FireFox, there are no Keepassxc browser extensions intstalled.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.2
Revision: e9b9582

Qt 5.15.2
Debugging mode is disabled.

Operating system: Debian GNU/Linux 11 (bullseye)
CPU architecture: x86_64
Kernel: linux 5.10.0-8-amd64

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (only unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.8

[NOTE]: # ( Pick choices based on your environment )
Operating System: Debian Bullseye
Desktop Env: KDE
Windowing System: X11

**Comment by droidmonkey** [comment]
Change the Auto-Type typing speed (slow it down). Otherwise there is nothing we would do to "correct" this.

**Comment by lkblkb** [comment]
@droidmonkey Thanks for the tip - how slow should we set it? It still gives me 2 tabs at 100ms typing speed.

My system is very similar to the user above, although I am using Manjaro (Arch) with KDE & X11

**Comment by droidmonkey** [comment]
That's as slow as you can go, this was a problem with Firefox in the past and slowing the type speed fixed it. Since this was clearly introduced by an update to Chrome we don't own this bug.

**Comment by lkblkb** [comment]
Understood, thanks!

Chrome updates messed with ibus input as well. Very annoying.

**Comment by lostfictions** [comment]
Hi, this is a wontfix/won't investigate then? I know it's an upstream issue, but unfortunately if there's no sign of this being fixed on the Chrome side and no adaptation planned for KeePassXC it's easier for me to migrate off of the latter to another password manager than off of Chrome.

**Comment by droidmonkey** [comment]
Why would we have to work around an issue that Chrome introduced? What if Chrome fixes the problem and our work around now breaks autotype again requiring another patch fix? Given this seems like a fundamental problem it will affect all password managers with Auto-Type capability. You could use the browser extension which is highly capable and secure.

**Comment by rldleblanc** [comment]
The issue seems to be resolved with Chrome 92.0.4515.131.
