### ISSUE TITLE
Auto-Type Sequences: fails to recognize {TAB}

### ISSUE THREAD

**Issue by hinell** [keepassxreboot/keepassxc#6770]
## Overview
When focusing Google Chrome browser, focusing KPXC and hitting the default `Ctrl + Shift + V` it DOESN'T fill in with `{TAB}` key present in Auto-Type Sequence e.g.:
`{USERNAME}{TAB}{PASSWORD}{ENTER}`

## Steps to Reproduce
1. Create new entry with random login/password sequences
2. Set Auto-Type Sequences to: `{USERNAME}{TAB}{PASSWORD}{ENTER}`
3. Focus some window Google Chrome with form to fill
4. Focus KeePassXC
5. Hit `Ctrl + Shift + V`

## Expected Behavior
Recognizes `{TAB}` config

## Actual Behavior
Ignores `{TAB}` config

## Context

* Browser integration doesn't affect the issue: I've tried it with both enabled and disabled.
* Debugging with `xenv` show that `tab` button is actually pressed:
 ```
...
KeyPress event, serial 41, synthetic NO, window 0x7800001,
    ....
    state 0x10, keycode 23 (keysym 0xff09, Tab), same_screen YES,
    ....

KeyRelease event, serial 41, synthetic NO, window 0x7800001,
    ....
    state 0x10, keycode 23 (keysym 0xff09, Tab), same_screen YES,
    ....
```

## Workaround
* If `{TAB}` is replaced by `{ENTER}` it actually works
## Versions
KeePassXC - 2.6.1 - 2.6.6 
Revision: 9a35bba
Operating System: Linux/Kubuntu 20.10
Desktop Env: KDE
Windowing System: X11
```
Qt 5.14.2
Debugging mode is disabled.

Operating system: Ubuntu 20.10
CPU architecture: x86_64
Kernel: linux 5.4.0-53-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (only unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.5
```

**Comment by droidmonkey** [comment]
#6768
