### ISSUE TITLE
Copy entries between opened databases

### ISSUE THREAD

**Issue by MrFrank17** [keepassxreboot/keepassxc#6771]
Hi,

I have found no way to copy an entry form one opened database into another one, using KeePassXC 2.6.6.
In case I have overlooked this functionality, please let me know. Otherwise I would like to propose it as a new feature.
My use case is working with child databases and from time to time I would like to move entries.

Thanks
Frank

**Comment by droidmonkey** [comment]
Click, drag, hold CTRL, drop onto a group in the other database

**Comment by droidmonkey** [comment]
Also an easier, menu driven way to do this is already requested. Thank you!

**Comment by MrFrank17** [comment]
Thanks!
