### ISSUE TITLE
Search by password

### ISSUE THREAD

**Issue by andcoz** [keepassxreboot/keepassxc#6774]
## Summary
As a user, I want to search for an entry by the password field.

## Context
In recent years, the use of passwords, gathered by some data breaches, to blackmail a user is growing.

I got one of these blackmails that, among other things, said that my password was "some string". Unluckily, I use random passwords for each site, so I cannot recall where I used that "some string" password.

It would be helpful to search in Keepassxc where I used that password to get additional info on the password data breach source.

**Comment by droidmonkey** [comment]
Use the "password:" prefix in your search. https://keepassxc.org/docs/KeePassXC_UserGuide.html#_searching_the_database
