### ISSUE TITLE
Make the titlebar dark when dark mode is enabled (Windows)

### ISSUE THREAD

**Issue by semi-transparent-dodecahedron** [keepassxreboot/keepassxc#6775]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
A dark titlebar when dark mode is enabled.

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )
![img](https://user-images.githubusercontent.com/88071143/127260907-7957cb57-0dc8-4c2d-bbff-9e79710c46ae.jpeg)
![img(1)](https://user-images.githubusercontent.com/88071143/127261017-34ed4936-03aa-4ce3-9b3a-a73538c3fd84.jpeg)

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
The white titlebar greats a visual disruption and also hurts the eye if dark mode is enabled in other places such as in Windows shell, browser etc.

## Possible implementation
There is an API (undocumented) introduced in W10 v1809 that changes the titlebar color for Win32 apps:
https://github.com/ysc3839/win32-darkmode/blob/cc26549b65b25d6f3168a80238792545bd401271/win32-darkmode/DarkMode.h#L107

**Comment by phoerious** [comment]
This is a known issue and we haven't really found a way to make it work with the Win32 API and Msys2. I'll check if the proposed solution works, but so far all attempts have failed or would have required us to draw our own title bars entirely.

**Comment by droidmonkey** [comment]
Could be possible when we go to visual studio

**Comment by phoerious** [comment]
UWP/XAML apps have all the APIs for this kind of stuff. Win32 is more restricted, but with access to the full WinRT API it could be easier.

**Comment by redudant-overflowing** [comment]
I think it's public now: https://docs.microsoft.com/en-us/windows/apps/design/shell/title-bar

**Comment by redudant-overflowing** [comment]
I just saw in a Reddit thread that the dark titlebar support is publicly available in the Windows 11 SDK and that the documentation will be updated soon: https://www.reddit.com/r/Windows11/comments/qw7o69/comment/hl1tibg/

**Comment by phoerious** [comment]
I tried out the APIs, but something doesn't work. No matter what I do, the titlebar stays white. Maybe Qt is interfering somewhere.

**Comment by droidmonkey** [comment]
@phoerious might be able to give this another go with the WinRT API's.

**Comment by phoerious** [comment]
I was able to do change the title bar colour with the Win32 API, but only to pure black, which looked even more out of place than leaving it white. Does WinRT allow custom colours or do we have to render CSDs?

**Comment by droidmonkey** [comment]
Could be buried somewhere in here: https://docs.microsoft.com/en-us/uwp/api/windows.ui?view=winrt-22000

But this might also require a CoreWindow to be created... which we cannot do with Qt.

**Comment by segevfiner** [comment]
> Qt 5.15, at least, might support it via a darkmode=1 argument to the Windows platform plugin ([QGuiApplication - Platform-Specific Arguments](https://doc.qt.io/qt-5/qguiapplication.html#platform-specific-arguments)), you can launch KeePassXC with -platform windows:darkmode=1 to enable it. But it would be nice to enable it by default. Perhaps via [qt.conf](https://doc.qt.io/qt-5/qt-conf.html#configuring-arguments-to-the-platform-plugins)? (It's probably not enabled by default since Qt Widgets doesn't come with a native dark mode style. It is something KeePassXC implemented)
>
> I'm not sure whether Qt 6 has added native support for this or enabled this by default for Qt Widgets since Qt 5.15.
&ndash; https://github.com/keepassxreboot/keepassxc/issues/7782#issue-1191039285

From the duplicate issue I opened. (Damn search...)

This is how this can be implemented, by just adding a key to `qt.conf`:
```ini
[Platforms]
WindowsArguments = darkmode=1
```

(I only tested using the CLI approach for setting this)

**Comment by EricLauber** [comment]
Just commenting to act as an upvote and track the issue.

**Comment by phoerious** [comment]
We haven't done anything in this regard, because the Win32 dark mode is pretty useless. The only option Windows provides via the old API is a pitch black title bar.

**Comment by JohnLGalt** [comment]
Gotta love Windows.....

**Comment by segevfiner** [comment]
But KeePassXC has added it's own dark mode. Just adding what I listed in https://github.com/keepassxreboot/keepassxc/issues/6775#issuecomment-1087320697 will also make the title bar dark for completion.

**Comment by phoerious** [comment]
The dark Windows title bar doesn't match our dark theme in the slightest.

**Comment by segevfiner** [comment]
Not surprising, but isn't this still better than a light one when the rest of the app is dark...?

**Comment by phoerious** [comment]
I would say no. It looks quite out of place, actually.

**Comment by leowinterde** [comment]
I will be happy to have a dark mode that is not optimal, better than burn-in on my oled from the bright white titlebar.

**Comment by droidmonkey** [comment]
Without this qt.conf the titlebar is white when you do not use your accent color for titlebars. This setting is possible in Windows 11 (don't remember windows 10 at this point). Adding the qt.conf settings above has no affect if the below setting is activated, so I think adding the qt.conf is a win win.

![image](https://user-images.githubusercontent.com/2809491/192030910-2cbf7160-b681-4ce5-86f6-34094c3e5a2c.png)

**Comment by Renegade-Master** [comment]
> Without this qt.conf the titlebar is white when you do not use your accent color for titlebars. This setting is possible in Windows 11 (don't remember windows 10 at this point). Adding the qt.conf settings above has no affect if the below setting is activated, so I think adding the qt.conf is a win win.
> 
> ![image](https://user-images.githubusercontent.com/2809491/192030910-2cbf7160-b681-4ce5-86f6-34094c3e5a2c.png)

Just because you didn't show the Win10 menu version, here it is for anyone else:
![image](https://user-images.githubusercontent.com/24991145/197535900-556686c1-5563-42a4-8d8a-7c1143ba634b.png)
