### ISSUE TITLE
Ditch the KeePassXC folder in the start menu

### ISSUE THREAD

**Issue by semi-transparent-dodecahedron** [keepassxreboot/keepassxc#6777]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
The KeePassXC shortcut in the All apps lists is unnecessarily hidden under a KeePassXC folder, which has only this shortcut. Microsoft updated the start menu logic in Windows 10 21H2, if I recall, so folders that only have one item will be automatically hidden and the shortcut will be shown out of the folder. However, some users might not get 21H2 due to upgrade blocks (driver out of support, incompatible program, etc).
![image](https://user-images.githubusercontent.com/88071143/127264441-2fe9a8fc-cc06-43ff-8ac9-6d073f335dea.png)

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )
N/A

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
Without the folder, the KeePassXC shortcut can be clicked faster.

**Comment by droidmonkey** [comment]
We are adding shortcuts to documentation in the next release
