### ISSUE TITLE
kdbx 3 database is very slow to open

### ISSUE THREAD

**Issue by atttx123** [keepassxreboot/keepassxc#6778]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

`keepassxc-cli` use 4 seconds to open a 120KB database

![image](https://user-images.githubusercontent.com/1284339/127288074-98049417-9f7a-4e5d-a14e-3fc0363bed16.png)

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

`MacPass` on the same machine open database less than 2 seconds

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.6.6
Revision: 386b79a

[NOTE]: # ( Pick choices based on your environment )
Operating system: macOS 11.4
CPU architecture: x86_64
Kernel: darwin 20.5.0

Qt 5.15.2
Debugging mode is disabled.

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
- libgcrypt 1.9.3

**Comment by droidmonkey** [comment]
Not sure what to do here.

**Comment by atttx123** [comment]
> Not sure what to do here.

@droidmonkey YOU NEED A PERFORMANCE PROFILE!!!!!

Open a lite 120KB file on SSD use 4 seconds, is TOO SLOW.....

`MacPass` open the same file on the same machine less than 1 second

**Comment by phoerious** [comment]
The database size is nothing to do with how long it takes to open the database. That is mostly up to how many rounds you choose for your KDF. Try saving it with a different profile.

**Comment by atttx123** [comment]
> The database size is nothing to do with how long it takes to open the database. That is mostly up to how many rounds you choose for your KDF. Try saving it with a different profile.

This does not explain why other programs （MacPass、Keepass） do not have such a large delay.

**Comment by droidmonkey** [comment]
Do you have this delay when using the regular gui or just in the cli?

**Comment by atttx123** [comment]
> Do you have this delay when using the regular gui or just in the cli?

the gui mode use 2 seconds to unlock the database, see the movie file below

https://user-images.githubusercontent.com/1284339/127474663-d2484ece-b5e4-49ff-b970-29990e27f2a3.mov

**Comment by droidmonkey** [comment]
Can you confirm your KDF settings please? Do you have any unique features in your database? Excessive references to other entries or a huge amount of custom icons? How many entries total are in the database?

**Comment by atttx123** [comment]
> Can you confirm your KDF settings please? Do you have any unique features in your database? Excessive references to other entries or a huge amount of custom icons? How many entries total are in the database?

- no unique features, just a database created by `MacPass`
- no custome icons
- only text entry, no attachments

- sorry , i do not know how to see the KDF settings

**Comment by droidmonkey** [comment]
Using KeePassXC only, can you export the database to csv then import that into a new database? I want to remove the macpass aspect to see if the issue started with them. See if the unlock time remains.

To see the KDF settings go to Database -> Database Security, then choose the encryption tab. You might have to select the advanced checkbox in the lower left corner as well.

**Comment by atttx123** [comment]
use the `Macpss` to open same database on same machine, please see the movie blow

https://user-images.githubusercontent.com/1284339/127476197-3f6375ad-0bb6-4dee-8db8-462292d29a62.mov

**Comment by atttx123** [comment]
> Using KeePassXC only, can you export the database to csv then import that into a new database? I want to remove the macpass aspect to see if the issue started with them. See if the unlock time remains.

![image](https://user-images.githubusercontent.com/1284339/127477323-8ef51647-0ecf-490d-aefc-ee6b4becfd9e.png)
reimport solved the problem, this is the macpass problem

> To see the KDF settings go to Database -> Database Security, then choose the encryption tab. You might have to select the advanced checkbox in the lower left corner as well.

the `advanced checkbox` is unavailable.
![image](https://user-images.githubusercontent.com/1284339/127477727-fcce524a-2961-49f4-9644-32852795c84f.png)

**Comment by droidmonkey** [comment]
You need to be on the security tab.  Those settings are only relevant to the macpass created database.

**Comment by atttx123** [comment]
KDF settings
![image](https://user-images.githubusercontent.com/1284339/127479071-e2f4a18c-05c1-4cd3-86fb-bdb269296166.png)

**Comment by droidmonkey** [comment]
I figured it was a kdbx 3 database (old standard). I'm surprised macpass can unlock that so fast with 13 million rounds on the kdf. Makes you wonder... 

If you click the one second benchmark button what number does keepassxc give you?

Sorry for all the questions trying to narrow where the problem is and potential major security flaw in macpass. It could also be that macpass is caching the transformed key in the macos key store, which is also a security issue without explicit prompting to the user.

**Comment by atttx123** [comment]
> If you click the one second benchmark button what number does keepassxc give you?
> 

8~9 million

![image](https://user-images.githubusercontent.com/1284339/127480477-3298e9f3-003d-4e4a-827a-15094d103aba.png)

**Comment by droidmonkey** [comment]
Makes sense. Ok well that is "interesting" we aren't going to pursue this any further. Seems like it's a default KDF difference with macpass and they must be caching the transformed key somewhere to get a near instant unlock speed. Was it "slow" to unlock the first time?

**Comment by atttx123** [comment]
> Was it "slow" to unlock the first time?

For a kdbx 3 database：
- 8 million round cost 2.9 seconds
- 5 million round cost 2.1 seconds
- 3 million round cost 1.1 seconds

I'm not sure why there is such a big difference from the benchmark value

**Comment by droidmonkey** [comment]
The benchmark is calculated very strangely in v2.6.6 and below. We updated that calculation in v2.7.0 with our move to Botan crypto library.

**Comment by atttx123** [comment]
Understand, thank you for your patience, I will update the title to make the information clearer and close this issue.

Solved by upgrading the database KDF to kdbx 4
![image](https://user-images.githubusercontent.com/1284339/127485438-02a64e7f-6c14-47e3-9fe0-92c33d96602e.png)

**Comment by phoerious** [comment]
900 rounds of Argon2 at 1MiB? Please use something more sensible that actually consumes some memory. With a bit more than that, 900 rounds should take forever.

**Comment by atttx123** [comment]
> 900 rounds of Argon2 at 1MiB? Please use something more sensible that actually consumes some memory. With a bit more than that, 900 rounds should take forever.

I don’t know the details of this algorithm, but I tested the default value kpassxc give, and its speed is a bit slow

- 50 rounds, 64MiB, 2 threads, cost 2 seconds

**Comment by droidmonkey** [comment]
Just half the rounds to get to 1 sec. Leave the memory and threads alone

**Comment by atttx123** [comment]
![image](https://user-images.githubusercontent.com/1284339/127493496-06f41959-30a6-418a-a8d9-b4fd0bc6de01.png)
 cost 0.9 second

**Comment by phoerious** [comment]
The slowdown is expected and a feature that enhances the security of your password file. In fact, the only reason why we use a KDF is to slow things down so an attacker cannot guess billions of different master passwords per second. What decryption time is acceptable to you depends on your personal security profile.

**Comment by atttx123** [comment]
😂
You can't have your cake and eat it.
鱼与熊掌不可得兼

**Comment by phoerious** [comment]
No idea what it is that you want to tell me.

**Comment by kolAflash** [comment]
I understand why delay is needed for security reasons, and this can't be changed. But I have three ideas which might nevertheless help.

&nbsp;

# 1. Delay before Password

Are we just talking about delay after entering the password, or also about delay before entering the password?

I recognized, that even before entering the password there's also a 1-2 second delay on a modern CPU (Ryzen 3500U).
This is the time between selecting a KBDX 3.1 file to open and the password dialog being displayed.
(database compression enabled, decryption time set to 1.0 s, KeePassXC-2.6.2 by Debian-11)

I'll call this phase "database selection" to distinguish it from "database decryption".
_(question: is the database already being fully read to memory/RAM before the password is being entered?)_

As far as I understand encryption, "rounds" apply after entering the password, not before. But maybe this is some encryption/decryption detail I don't fully understand.

&nbsp;

# 2. UI informing the User

Maybe something can be done to make this less irritating for the users. The first thing which comes to my mind is a progress bar. Before the password dialog, as well as after the password dialog when decrypting.

&nbsp;

# 3. Opening multiple Databases

An additional problem is, that these times add up if multiple databases are being used.

KeePassXC-2.6.2 seems to be set to `Load previously open databases on startup` by default. And I actually think that's good. But it adds up the delay "database selection" delay of different databases. And the user can do nothing in KeePassXC until this delay has passed for all databases. I use 4 databases regularly, so the time already multiplies by 4.

I also use the [AutoOpen](https://keepassxc.org/docs/KeePassXC_UserGuide.html#_automatic_database_opening) feature to open the other 3 databases from the first one.

So also for selecting / decrypting multiple databases a nice progress bar would help.

Additionally it would help if the tabs for all databases open instantly at KeePassXC startup (before entering the password). And the password field is just being disabled until whatever is being done in background (most favorably in another thread) has completed. This would make the UI behave more calm, than if one database opens up after another with some delay in between each. Also the user could already use the UI and do something else like selecting a completely different database. (selecting => open database, not yet decrypting)

**Comment by phoerious** [comment]
There is no delay on our side before opening the database, but Linux file pickers seem to take a while to load sometimes (which is an issue with the file picker). Maybe that's what you are experiencing.

**Comment by kolAflash** [comment]
@phoerious  
The delay is also happening if I open a file from the list of recent files.

Reproduced on Debian-11 and openSUSE-15.4.
