### ISSUE TITLE
T-REPLACE-RX not working with REF in username

### ISSUE THREAD

**Issue by devrandom0** [keepassxreboot/keepassxc#6779]
## Overview
If I fill the username field with something like `{T-REPLACE-RX:!{REF:U@I:UUID}!(.+)@.+!$1!}`, it doesn't fill correct username.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Fill username with: `{T-REPLACE-RX:!{REF:U@I:UUID}!(.+)@.+!$1!}`
2. Open the URL that you want to fill in username
3. You see this text: `{T-REPLACE-RX:!{REF:U@I:UUID}!(.+)@.+!$1!}` instead of the correct username

## Expected Behavior
Shows the correct username

## Actual Behavior
It shows `{T-REPLACE-RX:!{REF:U@I:UUID}!(.+)@.+!$1!}`

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.6.6
Revision: 386b79a

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS

**Comment by droidmonkey** [comment]
Feature won't be available until 2.7.0
