### ISSUE TITLE
No favicon download for HTTPS websites

### ISSUE THREAD

**Issue by yeeeargh** [keepassxreboot/keepassxc#678]
## Expected Behavior
After clicking "Download favicon" the icon gets downloaded and selected for the entry.

## Current Behavior
If there's a HTTP URL in the URL field the icon downloads as expected. If the URL uses HTTPS the following error message occurs: "Unable to fetch favicon"

## Steps to Reproduce (for bugs)

1. Create a new entry with a HTTP URL which doesn't redirect to HTTPS, e.g. http://www.foobar2000.org/
2. Click "Download favicon" in the icon tab
3. Change the URL to HTTPS, e.g. https://www.foobar2000.org/
4. Try to download the favicon again

## Your Environment

* KeePassXC - Version 2.2.0 / Revision: caa49a8ef3ee28ed478192389b21d61107b3b8e0
* Qt 5.9.0
* Operating System and version: Windows 10 x64 (10.0.15063)

**Comment by TheZ3ro** [comment]
Strictly related to #240

**Comment by magkopian** [comment]
Just wanted to say that I'm currently on Debian Stable running KeePassXC version 2.2.0 and I can't reproduce, works fine for me.

**Comment by yeeeargh** [comment]
I could reproduce it on a different pc with x64. After that I tried the x86 version and on that version I couldn't reproduce it. 

## Environment 1: Issue occurs
* KeePassXC - Version 2.2.0 / Revision: caa49a8ef3ee28ed478192389b21d61107b3b8e0 / x64 installed
* Qt 5.9.0
* Operating System and version: Windows 10 x64 (10.0.15063)

## Environment 2: Issue occurs
* KeePassXC - Version 2.2.0 / Revision: caa49a8ef3ee28ed478192389b21d61107b3b8e0 / x64 portable
* Qt 5.9.0
* Operating System and version: Windows 10 x64 (10.0.14393)

## Environment 3: Working
* KeePassXC - Version 2.2.0 / Revision: caa49a8ef3ee28ed478192389b21d61107b3b8e0 / x86 portable
* Qt 5.9.0
* Operating System and version: Windows 10 x64 (10.0.15063)

**Comment by TheZ3ro** [comment]
Maybe this is Windows-only?

**Comment by yeeeargh** [comment]
Note that I tested the portable 32 bit version for Windows where the bug didn't occur. It only occurred with a installed or portable 64 bit version.
I can't test it on a Linux or OSX machine, so I don't know if there's a problem with x64 in general or just x64 on Windows

**Comment by TheZ3ro** [comment]
@yeeeargh This is still an Issue? I can't reproduce this after #719

**Comment by FrozenChen** [comment]
I can still reproduce this same behaviour on latest release on windows 10.
Works as intended on ‎linux Manjaro 18.0.2
### Your Environment
KeePassXC - Version 2.3.4
Revision: 6fe821c

Libraries:
- Qt 5.11.1
- libgcrypt 1.8.3

Operating system: Windows 10 (10.0)
CPU architecture: x86_64
Kernel: winnt 10.0.17763

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by pezcode** [comment]
I'm seeing the same problem. Favicon download works for HTTP, for HTTPS it gives me a red "Unable to fetch favicon" and then one or more dialogs with Download Progress stuck at 0%. Google fallback option shows the same behaviour.

Win 10 Pro 1809 64-bit
KeePassXC 2.3.4

**Comment by droidmonkey** [comment]
This is fixed in 2.4.0, will be released as beta 2 soonish
