### ISSUE TITLE
(make it easy to) add dictionaries in other languages than english for passphrase generation

### ISSUE THREAD

**Issue by bikepunk** [keepassxreboot/keepassxc#6780]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )

For now there is no interface to add dictionaries for passphrase generation.
Having a button to add dictionaries would be neat.

Shipping more than English dictionary would be useful for non English speakers

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )

The passphrase is usefull when you need to remember it. It's easier to remember a passphrase in your native language.

more languages would increase enthropy

**Comment by bikepunk** [comment]
mentioned here : https://github.com/keepassxreboot/keepassxc/issues/4209#issuecomment-832146221

**Comment by droidmonkey** [comment]
#989
