### ISSUE TITLE
Can't use shift (+) with AutoType

### ISSUE THREAD

**Issue by user23498723452** [keepassxreboot/keepassxc#6781]
## Overview
[NOTE]: #
I am unable to use the shift key modifier (+) for AutoType.  It ignores the plus symbol, even though it doesn't warn about the syntax.
I tried using Chrome and Firefox (both latest versions), as well as testing on multiple websites from different companies.  It seems more likely that the Shift modifier in KeePassXC is broken vs multiple sites simultaneously breaking usage of Shift.

Plus Shift-Tab can be manually entered in the browser for all impacted sites.

## Steps to Reproduce
[NOTE]: # 
1.  Create a password with autotype that uses the Shift modifier
2.  Go to any site and use the same sequence (no need to perform an actual login)
3.  Note that the Shift modifier doesn't take effect and instead performs a regular Tab.

## Expected Behavior
The Shift-Tab keystroke should be performed, which tabs "backwards".

## Actual Behavior
Instead the Shift is ignored and only a forward tab can be performed, breaking basic commands required by many sites.

## Context
Regular user for years

KeePassXC - Version 2.6.4
Revision: 34a78f0
Distribution: AppImage

Operating System: Ubuntu 18.04 LTS
Desktop Env: default
Windowing System: default

**Comment by droidmonkey** [comment]
Will be released with version 2.7.0
