### ISSUE TITLE
Select TOTP Field Reference in {REF:<FIELD>@<SEARCH_IN>:<SEARCH_TEXT>} Sequence Input forms

### ISSUE THREAD

**Issue by stefan123t** [keepassxreboot/keepassxc#6782]
## Summary
I would like to create a combined sequence entry for Username+Password and subsequent TOTP challenge entry form.

## Examples
I have two entries in my KeepassXC Database:
1. Username/password with `{USERNAME}{TAB}{PASSWORD}{ENTER}`
2. TOTP secret/token with `{TOTP}{ENTER}`

I would like to create either a new or modify the first entries autotype sequence by adding the TOTP secret of the second entry:
`{USERNAME}{TAB}{PASSWORD}{ENTER}{DELAY 3000}{REF:<FIELD>@<SEARCH_IN>:<SEARCH_TEXT>}{ENTER}`

It is usually difficult to find out the correct `{REF:<FIELD>@<SEARCH_IN>:<SEARCH_TEXT>}` value for other entries.
It would be much easier if we had a (right click menu) to select/copy the reference field URL for attributes of another entry. 

I already assume that I will have to add a Password field reference to my second entry as a workaround, because there is AFAIK no `TOTP` field defined yet. Still constructing and finding the correct Password field reference for any entry to be entered into another entries sequence is a difficult and trial / error process until the right REFerence Field URL is determined.

## Context
Configuring Auto-Type Sequence in the dialog usually requires reading the documentation sections under
[Auto-Type](https://keepassxc.org/docs/KeePassXC_UserGuide.html#_auto_type) and
[Modifiers and Fields](https://keepassxc.org/docs/KeePassXC_UserGuide.html#_modifiers_and_fields)

The dialog could be extended to have some `{COMMAND}` completion while it also has plenty of space under the
![image](https://user-images.githubusercontent.com/11159753/127456662-8d650d38-06fd-4d1e-8b21-ea61408b812a.png)

_[ ] use a specific sequence for this association_
input box to add those two documentation links or other information for the feature requested here.

Similar to such a direct sequence input helper / command completion one could also simply add a right click menu option to each KeepassXC entry under the 
Copy Username
Copy Password
Copy Attribute > Title
Copy Attribute > URL
Copy Attribute > Notes
![image](https://user-images.githubusercontent.com/11159753/127457453-e868e53a-65f5-4bfe-9bff-c4d55c16f34e.png)

e.g.
Copy Field Reference > Password
Copy Field Reference > TOTP
Copy Field Reference > Username 
...

this would yield the above `{REF:<FIELD>@<SEARCH_IN>:<SEARCH_TEXT>}` in copy/clipboard buffer filled with the `SEARCH_IN` and `SEARCH_TEXT` being correctly set for the KeepassXC entry selected in right click mode and the `FIELD` (e.g. `P` for Password, note that `T` for "TOTP" is already assigned to Title, `U` for Username) chosen from the submenu.

I also do not know if and which of the following field references and placeholders from the KeePass 2.x series are actually also supported within KeePassXC, eg. `{TIMEOTP}` or `{HMACOTP}` and `{T-REPLACE-RX:/Text/Search/Replace/}` ?

[KeePass Field References](https://keepass.info/help/base/fieldrefs.html)
[KeePass Placeholders](https://keepass.info/help/base/placeholders.html)

**Comment by droidmonkey** [comment]
I'm not sure what your overall goal is here. Are you making a special Auto-Type entry that is referencing information from several other entries??

Why are you splitting the totp information into a separate entry? That is not necessary.

The advanced autotype fields will be available in 2.7.0.

**Comment by stefan123t** [comment]
@droidmonkey thanks for your quick response, I have both a username/password entry and an TOTP secret entry.
I am unaware that I can have both a password and a TOTP secret in one entry.
![image](https://user-images.githubusercontent.com/11159753/127466030-995c0485-0c82-4c7d-a3d1-46a38b70038b.png)

How would you do that as I have to enter the TOTP secret into the "password" field of the TOTP entry ?

1. As mentioned I can probably workaround the missing TOTP reference field by reversing the logical order and adding the username/password references in the TOTP autotype sequence as described in #6462.
2. Please decide with @kasonnara whether you want to implement / include any of the copy reference field {REF:...} syntax I suggested above in #5900 
3. Also please consider the command/reference field completion or the follow reference field link feature from #5802 and my feature request into #5900.

Please feel free to close this feature request if you think this all is sufficiently described by #6462 and #5900.
I found them only afterwards changing my search query for any such issues to `is:issue {REF:`

And yes, I am using a somewhat older nightly build of 2.7.0, since that fixes the dreaded keyboard switching many thanks to you and hifi!

Please let me know if you have anything in that area that you want me to test / verify in the Reference field area ?
I would be willing to install a newer nightly build anytime.

Best regards, Stefan

**Comment by stefan123t** [comment]
@droidmonkey as described in my answer to #6462 the following works for me:

Instead of my human approach in the first username/password entry (UUID1):
`{USERNAME}{TAB}{PASSWORD}{ENTER}{DELAY 3000}{REF:<TOTP_FIELD_IDENTIFIER?>@<UUID2>}{ENTER}`

I can use e.g. the following auto-type sequence in my second TOTP entry (UUID2)
`{REF:U@<UUID1>}{TAB}{REF:P@<UUID1>}{ENTER}{DELAY 3000}{TOTP}{ENTER}`

I can get the References to the Username/Password field by using the Clone Entry... Ctrl-K Option from the right-click menu of an existing entry and checking the following under Clone Entry Options.
![image](https://user-images.githubusercontent.com/11159753/127470774-8ce09070-286f-404d-b516-47c571d6a77c.png)

_[x] Replace username and password with references_

Now I can edit the newly cloned entry and copy the two username and password references to my second TOTP entries auto-type sequence.
![image](https://user-images.githubusercontent.com/11159753/127471168-b87d04d5-4a0e-4d70-9c97-93e0514e86af.png)

Username: `{REF:U@I:<UUID1>}`
Password: `{REF:P@I:<UUID1>}`

After editing the Auto-type sequence of my TOTP entry as specified above, I can again remove the cloned Username/Password entry, which I only needed to figure out the Reference Field URLs for Username/Password.

That is why I voted for a copy reference field menu for each entry.

**Comment by stefan123t** [comment]
I found another hint to the UUID on the properties tab of the entry:
![image](https://user-images.githubusercontent.com/11159753/127471942-2e80eaf7-139d-44ad-a215-420189ac376a.png)

Still constructing the correct `{REF:<FIELD>@<UUID>}` reference field URLs requires reading the documentation and figuring out the correct `FIELD` and `UUID` settings for the wanted attribute.
The three most common attributes are most likely Password, Username and a current TOTP token.

**Comment by droidmonkey** [comment]
You don't place the totp secret in the password field. Select the entry you want to add totp to, right click, TOTP -> Setup TOTP...

Then put your secret in the dialog that appears, press ok. 

You do this all in one entry. No references needed. Closing this as the other linked issues cover your other requests.
