### ISSUE TITLE
Windows - SSH Agent integration failure - incompatibility with PPK key file format, which is needed by pagent (Putty agent)

### ISSUE THREAD

**Issue by ageorgiev-bg** [keepassxreboot/keepassxc#6784]
## Overview
In Windows (using "Enable SSH Agent Integration") when trying to add SSH key in an entry to use with pagent (Putty agent) I receive failure message as the app doesn't accept PPK file format keys, but only OpenSSH. However Putty agent (pagent) uses ONLY ppk file format keys

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1.  Enable SSH Agent integration via Tools -> Settings -> SSH Agent -> Enable SSH Agent Integration.
2. Create a new entry, go to SSH_Agent and Add OpenSSH key as attachment, try "add to agent" (should fail first here or use 3). 
3.  Save the entry and right click on it "Add key to SSH Agent"

## Expected Behavior
I would expect for it to add the key to pagent

## Actual Behavior
Failure message

## Context
When  "Enable SSH Agent Integration" you should not allow "OpenSSH" key file format in Windows, as pagent supports only ppk key file format. So PPK file format for keys should be the only usable format for SSH keys if used with "Enable SSH Agent Integration".

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.6.6
Revision: 9c108b9

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 8.1 Enterprise
Desktop Env: -
Windowing System: X11

**Comment by droidmonkey** [comment]
You need to convert the key to openssh format to use it with KeepassXC, see the putty subsection of the user guide: https://keepassxc.org/docs/KeePassXC_UserGuide.html#_generating_a_key_to_use_with_keepassxc

**Comment by ageorgiev-bg** [comment]
@droidmonkey  It appears that it started working - I tested the same situation and now KeepasXC is able to inject the key. Not sure why this wasn't working the first time. Thanks! (I literally didn't change anything just tried again)
