### ISSUE TITLE
Possibility to auto open a fixed database

### ISSUE THREAD

**Issue by konraifen88** [keepassxreboot/keepassxc#6785]
I recently switched from Keepass2 to KeepassXC and have one missing feature. I do not know if I didn't find the correct setting or if it simply does not exist. The only "config" I've found is the `--config ` command line option which I currently use for all my shortcuts, but I think that I have to apply the configuration again after installing an update.

## Whats the problem
I have multiple Databases in use, which are loaded with the [AutoOpen](https://keepassxc.org/docs/KeePassXC_UserGuide.html#_automatic_database_opening) feature. Or better: I open my private database, which opens my work database which opens multiple shared databases. 
When I open KeepassXC with this setup, all the databases are opened as tabs (locked), but the one to initially enter the password switches between all "opened" databases.

## What I want to do
I want to have the possibility to set a fix database. Best way would be with an configuration file or by environment variable. In Keepass2 I was able to create an `KeePass.config.enforced.xml` and set the `LastUsedFile` to force open a specific database at start.

**Comment by droidmonkey** [comment]
You could disable remembering open databases and setup your shortcut to open your private database in launch. I believe this will work even without disabling that setting because the passed database file will be focused.

**Comment by konraifen88** [comment]
Thanks for the quick answer. I will give it a try. I missed the argument when reading the documentation 🙈
