### ISSUE TITLE
Nvidia.com totp not working

### ISSUE THREAD

**Issue by tazihad** [keepassxreboot/keepassxc#6786]
## Overview
Totp for nbidia.com not working 
Error: You have entered an invalid secret key. The key must be in Base32 format.

## Steps to Reproduce

1. https://www.nvidia.com/en-us/account/
2. enable 2fa
3. The will give formated like this:  
`PJTG  45CE  K5WU  EX2J KVVD  SYJX  M5FH  Q5DY`
4. Works on Google auth

## Expected Behavior
It should work by default

## Actual Behavior
It doesn't recognize code

[NOTE]:
KeePassXC - Version 2.6.6
Revision: 9c108b9

Qt 5.15.2
Debugging mode is disabled.

Operating system: Windows 10 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.19043

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
- libgcrypt 1.9.2-unknown

[NOTE]: 
Operating System: Windows 10

**Comment by droidmonkey** [comment]
Remove the spaces, this is a duplicate
