### ISSUE TITLE
CMake Error at CMakeLists.txt:229 (add_feature_info)

### ISSUE THREAD

**Issue by botscholar-scott** [keepassxreboot/keepassxc#6787]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
When I run  cmake -DWITH_XC_ALL=ON -DCMAKE_BUILD_TYPE=Release ..  I receive an error.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Installed MinGW64 and setup build environment per instructions [1] and [2] including the yubikey libraries.
2. clone repo
3. in `src` directory followed the build steps outlined here [3], [4]
4. I ran `-DWITH_XC_ALL=ON -DCMAKE_BUILD_TYPE=Release ..` and it did a bunch of things and error-ed out.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
It would build the project.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
$ cmake -DWITH_XC_ALL=ON -DCMAKE_BUILD_TYPE=Release ..
CMake Warning (dev) in CMakeLists.txt:
  No project() command is present.  The top-level CMakeLists.txt file must
  contain a literal, direct call to the project() command.  Add a line of
  code such as

    project(ProjectName)

  near the top of the file, but after cmake_minimum_required().

  CMake is pretending there is a "project(Project)" command on the first
  line.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Error at CMakeLists.txt:229 (add_feature_info):
  Unknown CMake command "add_feature_info".

CMake Warning (dev) in CMakeLists.txt:
  No cmake_minimum_required command is present.  A line of code such as

    cmake_minimum_required(VERSION 3.21)

  should be added at the top of the file.  The version specified may be lower
  if you wish to support older CMake versions for this project.  For more
  information run "cmake --help-policy CMP0000".
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring incomplete, errors occurred!
See also "C:/msys64/home/Scott/src/GITROOT/keepassxc/src/build/CMakeFiles/CMakeOutput.log"

## Context
[NOTE]: # ( Give us any additional information you may have. )
$ git log -1
commit 9c108b95100bfa3b172edcfd5754aa2e831a3221 (HEAD -> master, tag: 2.6.6, origin/master)
Merge: 2b262c5b 596821ca
Author: Jonathan White <support@dmapps.us>
Date:   Fri Jun 11 22:13:52 2021 -0400

    Release 2.6.6

    Fixed

    - Fix focusing search when pressing hotkey [#6603]
    - Trim whitespace from TOTP key input prior to processing [#6604]
    - Fix building on macOS [#6598]
    - Resolve compiler warnings for unused return values [#6607]

I see this on line 29 when I `cat -n ../CMakeLists.txt`:
 29      include_directories(${CMAKE_CURRENT_SOURCE_DIR}/zxcvbn)

My CMake version is:
$ cmake --version
cmake version 3.21.1

CMake suite maintained and supported by Kitware (kitware.com/cmake).

[NOTE]: # ( Paste debug info from Help → About here )

Revision: 9c108b95100bfa3b172edcfd5754aa2e831a3221 (HEAD -> master, tag: 2.6.6, origin/master)

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows
Desktop Env: Windows 10
Windowing System: Windows

[1]  https://github.com/keepassxreboot/keepassxc/wiki/Set-up-Build-Environment-on-Windows
[2] https://www.msys2.org/
[3] https://github.com/keepassxreboot/keepassxc/wiki/Building-KeePassXC#windows
[4] https://github.com/keepassxreboot/keepassxc/blob/develop/INSTALL.md

**Comment by droidmonkey** [comment]
You need to put your build folder in the root keepassxc folder, not src
