### ISSUE TITLE
HTML Entities are double encoded in entry detail view

### ISSUE THREAD

**Issue by lopopolo** [keepassxreboot/keepassxc#679]
## Expected Behavior

Display text with ampersands as eg, `AT&T`

## Current Behavior

Display text with ampersands as `AT&amp;T`
<img width="258" alt="screen shot 2017-06-26 at 10 50 57 am" src="https://user-images.githubusercontent.com/860434/27552794-875dde28-5a5d-11e7-8cdf-88c917d71165.png">

## Steps to Reproduce (for bugs)

1. Create password entry
2. Insert a name with an ampersand
3. close detail pane
4. reopen detail pane

## Your Environment

KeePassXC - Version 2.2.0
Revision: caa49a8ef3ee28ed478192389b21d61107b3b8e0

Libraries:
- Qt 5.9.0
- libgcrypt 1.7.7

Operating system: macOS Sierra (10.12)
CPU architecture: x86_64
Kernel: darwin 16.6.0

Enabled extensions:
- KeePassHTTP
- Auto-Type
- YubiKey

**Comment by lopopolo** [comment]
or perhaps the strings aren't being **decoded** when deserialized from the XML?

**Comment by phoerious** [comment]
I think it's rather an issue with Qt's wird "guessing" of whether to display a label as HTML or not. We explicitly escape that string because otherwise HTML tags are parsed. I suppose we need to explicitly set the text format of that label.
