### ISSUE TITLE
CMake Error running command from INSTALL.md

### ISSUE THREAD

**Issue by botscholar-scott** [keepassxreboot/keepassxc#6790]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
I'm trying to build for the first time and after following the setup instructions [1] (including installing the Yubikey libs) and then trying cmake command from [2] I receive the following error,

CMake Error: CMake was unable to find a build program corresponding to "Ninja". 

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Setup MSYS64 and setup guide for Windows [3], [1] installing all dependencies/prerequisites.
2. At root folder `mkdir build`
3. `cd build`
4. 
```
Scott@Scott-PC MINGW64 ~/src/GITROOT/keepassxc/build
$ cmake -DWITH_XC_ALL=ON -DCMAKE_BUILD_TYPE=Release ..
```

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Cmake completes without error

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
-- Building for: Ninja
CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
See also "C:/msys64/home/Scott/src/GITROOT/keepassxc/build/CMakeFiles/CMakeOutput.log".

## Context
[NOTE]: # ( Give us any additional information you may have. )
I also tried the command listed here [4] and received a slightly different error,

```
Scott@Scott-PC MINGW64 ~/src/GITROOT/keepassxc/build
$ cmake -G"MSYS Makefiles" -DWITH_XC_ALL=ON -DCMAKE_BUILD_TYPE=Release ..
CMake Error: Error: generator : MSYS Makefiles
Does not match the generator used previously: Ninja
Either remove the CMakeCache.txt file and CMakeFiles directory or choose a different binary directory.
```

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION
Revision: 
Scott@Scott-PC MINGW64 ~/src/GITROOT/keepassxc/build
$ git log -1
commit 9c108b95100bfa3b172edcfd5754aa2e831a3221 (HEAD -> master, tag: 2.6.6, origin/master)
Merge: 2b262c5b 596821ca
Author: Jonathan White <support@dmapps.us>
Date:   Fri Jun 11 22:13:52 2021 -0400

    Release 2.6.6

    Fixed

    - Fix focusing search when pressing hotkey [#6603]
    - Trim whitespace from TOTP key input prior to processing [#6604]
    - Fix building on macOS [#6598]
    - Resolve compiler warnings for unused return values [#6607]

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 10
Desktop Env: Windows
Windowing System: Windows

[1] https://github.com/keepassxreboot/keepassxc/wiki/Set-up-Build-Environment-on-Windows
[2] https://github.com/keepassxreboot/keepassxc/blob/develop/INSTALL.md
[3] https://www.msys2.org/
[4] https://github.com/keepassxreboot/keepassxc/wiki/Building-KeePassXC#windows

**Comment by droidmonkey** [comment]
You need to remove all files in the build directory before changing the generator. It says that in the message that you pasted...

> Either remove the CMakeCache.txt file and CMakeFiles directory or choose a different binary

**Comment by botscholar-scott** [comment]
I made the build directory the step before I changed into it and ran that cmake command.

**Comment by botscholar-scott** [comment]
```
Scott@Scott-PC MINGW64 ~/src/GITROOT/keepassxc
$ git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean

Scott@Scott-PC MINGW64 ~/src/GITROOT/keepassxc
$ ls -l
total 324
-rw-r--r-- 1 Scott Scott 42710 Jul 30 19:25 CHANGELOG.md
-rw-r--r-- 1 Scott Scott 18642 Jul 30 19:25 CMakeLists.txt
-rw-r--r-- 1 Scott Scott 10821 Jul 30 19:25 COPYING
-rw-r--r-- 1 Scott Scott  6533 Jul 30 15:17 INSTALL.md
-rw-r--r-- 1 Scott Scott  1327 Jul 30 15:17 LICENSE.BSD
-rw-r--r-- 1 Scott Scott  6896 Jul 30 15:17 LICENSE.CC0
-rw-r--r-- 1 Scott Scott 17987 Jul 30 15:17 LICENSE.GPL-2
-rw-r--r-- 1 Scott Scott 35068 Jul 30 15:17 LICENSE.GPL-3
-rw-r--r-- 1 Scott Scott 26521 Jul 30 15:17 LICENSE.LGPL-2.1
-rw-r--r-- 1 Scott Scott  7651 Jul 30 15:17 LICENSE.LGPL-3
-rw-r--r-- 1 Scott Scott  1046 Jul 30 15:17 LICENSE.MIT
-rw-r--r-- 1 Scott Scott  1141 Jul 30 15:17 LICENSE.NOKIA-LGPL-EXCEPTION
-rw-r--r-- 1 Scott Scott  4567 Jul 30 15:17 LICENSE.OFL
-rw-r--r-- 1 Scott Scott  4264 Jul 30 19:25 README.md
drwxr-xr-x 1 Scott Scott     0 Jul 30 19:25 cmake
drwxr-xr-x 1 Scott Scott     0 Jul 30 19:25 docs
-rwxr-xr-x 1 Scott Scott 45071 Jul 30 19:25 release-tool
drwxr-xr-x 1 Scott Scott     0 Jul 30 19:25 share
drwxr-xr-x 1 Scott Scott     0 Jul 30 19:25 snap
-rw-r--r-- 1 Scott Scott   673 Jul 30 15:17 sonar-project.properties
drwxr-xr-x 1 Scott Scott     0 Jul 31 14:30 src
drwxr-xr-x 1 Scott Scott     0 Jul 30 19:25 tests
drwxr-xr-x 1 Scott Scott     0 Jul 30 15:17 utils

Scott@Scott-PC MINGW64 ~/src/GITROOT/keepassxc
$ mkdir build

Scott@Scott-PC MINGW64 ~/src/GITROOT/keepassxc
$ cd build

Scott@Scott-PC MINGW64 ~/src/GITROOT/keepassxc/build
$ cmake -DWITH_XC_ALL=ON -DCMAKE_BUILD_TYPE=Release ..
-- Building for: Ninja
CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
See also "C:/msys64/home/Scott/src/GITROOT/keepassxc/build/CMakeFiles/CMakeOutput.log".

Scott@Scott-PC MINGW64 ~/src/GITROOT/keepassxc/build
$
```

**Comment by botscholar-scott** [comment]
Could you please explain what I'm not doing according to your posted directions?

**Comment by droidmonkey** [comment]
`cmake -G "MSYS Makefiles" -DWITH_XC_ALL=ON`

If you want to use Ninja you need to install it into MSYS.

**Comment by botscholar-scott** [comment]
I have zero preference to the tools used. I'm just trying to follow the instructions.

**Comment by droidmonkey** [comment]
Well you aren't following them because you didn't include the generator option.

**Comment by botscholar-scott** [comment]
Thanks. I was mistakenly following the steps here [1] which don't mention that generator option.

```
mkdir build
cd build
cmake -DWITH_XC_ALL=ON ..
make
```

[1] https://github.com/keepassxreboot/keepassxc/blob/develop/INSTALL.md

**Comment by botscholar-scott** [comment]
I recursively removed the directory, recloned the repo, re-made a build folder and did the cmake command you posted above with one minor addition and then it completed fine and my make is building.

```
cmake -G "MSYS Makefiles" -DWITH_XC_ALL=ON ..
```

**Comment by droidmonkey** [comment]
It is mentioned in the install.md right after those generic commands

> If you are on Windows, you may have to add -G "MSYS Makefiles" to the beginning of the cmake command. See the Windows Build Instructions for more information
