### ISSUE TITLE
Keepassxc Process frozen in D State

### ISSUE THREAD

**Issue by MrCybertux** [keepassxreboot/keepassxc#6796]
Hi,

I have the Problem that KeepassXC stops reacting at some point.
Trying to kill does not help closing the process.
The parent becomes a zombie and the child process is in D.  
SIGTERM or SIGKILL don't do anything.
I work in IT support so if i am on a Call and this happens i cant do anything with our Systems for the Customer.

![image](https://user-images.githubusercontent.com/67368875/127852619-5d1fabee-95ef-4d42-b574-7559f27e0ae9.png)

OS: Parrot OS 4.11
Harware: Lenovo Yoga x380

regards 

Mr Cybertux

**Comment by droidmonkey** [comment]
1.2 GB of ram? Why are there two processes running? There is a lot wrong here and nothing much we can do about it. Use our appimage or snap package. You can also try our snapshot of develop branch https://snapshot.keepassxc.org
