### ISSUE TITLE
Potential security issue with secret service

### ISSUE THREAD

**Issue by faximilie** [keepassxreboot/keepassxc#6802]
## Overview
Applications can create secret service entries that use the `{REF:P@I:1234567890ABCDEF}` feature to extract sensitive data from outside the "Exposed database groups" if the ID of an entry is known

This is fairly low risk, but I thought I'd bring it up.

## Steps to Reproduce
1. Determine the ID of an entry
2. Store a secret:  `echo '{REF:P@I:<INSERT_ID_HERE>}' | secret-tool  store --label='test' test_key test_value`
3. Retrieve secret: `secret-tool lookup test_key test_value`

## Expected Behavior
There should be some protection from either inserting a ref or reading a ref from the Secrets Store.
Ideally there should be some user intervention required for entries exposed via the Secret Store to use a ref, like a confirmation or toggle to enable for each entry.

## Actual Behavior
You can just extract secrets from outside the exposed group, if you know the ID.

## Context
I personally use refs in my Secret Store to copy certain entries that update often without ruining my organization, so I think disabling the use of them in the exposed group would be a bad choice.

KeePassXC - 2.6.4
Revision: 34a78f0

Operating System: Linux
Desktop Env: None
Windowing System: X11

**Comment by droidmonkey** [comment]
Given that your need to basically guess a specific uuid, this is a very theoretical attack. If you know a specific uuid then it is reasonable to assume you already have access to the database and can just directly retrieve the sensitive data. 

As you mentioned, fixing this would break actual useful functionality for no gain in security. I could agree to not allowing third party programs to set values that are refs.

**Comment by faximilie** [comment]
I agree, it's a very theoretical attack.

A simple and quick fix would be to re-use [`EntryAttributes::matchReference`](https://github.com/keepassxreboot/keepassxc/blob/9b2b861a2af451eb160c3771db6453deb90cf792/src/core/EntryAttributes.cpp#L288) to check upon creation of a secret from Secret Service. 

I'll see if I can't get that started.

**Comment by faximilie** [comment]
Update, after some testing I was able to extract my Google password by simply using the Title search in ref. Luckily this needs to be an exact case sensitive match, same goes for URL.

```bash
echo '{REF:P@T:Google}' | secret-tool  store --label='test' test_key test_value
secret-tool lookup test_key test_value
```

Suddenly a little less theoretical if a malicious application can just iterate through common service names, and exfiltrate sensitive information from an unlocked database, where the user expects it to be limited to a specific folder.

However if the notification for Secret Service is enabled it is a noisy attack to iterate over common services.

Functions that allow setting attributes that evaluate refs:
- [`Item::setAttributes`](https://github.com/keepassxreboot/keepassxc/blob/0921bf2d61633531e20c45774eb9d24c153523eb/src/fdosecrets/objects/Item.cpp#L116) - Only for `URL`, `Title`, `UserName`, `Notes`
- [`Item::setSecret`](https://github.com/keepassxreboot/keepassxc/blob/0921bf2d61633531e20c45774eb9d24c153523eb/src/fdosecrets/objects/Item.cpp#L260)
- [`Item::setLabel`](https://github.com/keepassxreboot/keepassxc/blob/0921bf2d61633531e20c45774eb9d24c153523eb/src/fdosecrets/objects/Item.cpp#L162)

**Comment by droidmonkey** [comment]
Still good to block creating refs through secret service interface. Great find!
