### ISSUE TITLE
 Error copying password to clipboard with certain program settings

### ISSUE THREAD

**Issue by SergeyIS89** [keepassxreboot/keepassxc#6803]
Hello! As a user of your program, I want to thank you for such a wonderful program and its functionality. I found the item to work incorrectly "Hide window when copying to clipboard",  here is the full path: Tools - Settings - General - Basic Settings - Entry Management - Hide window when copying to clipboard - Minimise. 
When I copy the password to the clipboard, the program is minimized and logged out, but the password is not copied to the clipboard and the clipboard is absolutely clean. I repeated this experience several times.
If you uncheck the "Hide window when copying to clipboard" checkbox, the password is correctly copied to the clipboard and held there for 10 seconds. Thank you in advance for considering my problem!

Debug info:
KeePassXC - Version 2.6.6
Revision: 9c108b9

Qt 5.15.2
Debugging mode is disabled.

Operating system: Windows 7 Version 6.1 (Build 7601: SP 1)
CPU architecture: x86_64
Kernel: winnt 6.1.7601

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
- libgcrypt 1.9.2-unknown

**Comment by droidmonkey** [comment]
Don't enable "Lock database on minimize" in the security settings tab. This is a duplicate report thank you.

**Comment by SergeyIS89** [comment]
Thanks for answering my question!
