### ISSUE TITLE
File open dialog boxes do not display

### ISSUE THREAD

**Issue by le-jawa** [keepassxreboot/keepassxc#6806]
When I use the Open Database command from the menu or toolbar, or if I use the browse button to find a key file, the dialog box for browsing to the file does not appear, except for the combo box allowing me to choose the file type.  The box is open however, as I can hit "Esc" and the box closes: the file type combo box disappears, and I can interact with KeepassXC as normal.  When the invisible dialog box is open, I cannot interact with the rest of the interface (as expected).

Originally, this only happened when the app was open full-screen.  Now it happens regardless of screen geometry.  I believe this changed after the last update, but I'm not certain.
Screenshot below:

![KeepassXC invisible dialog box](https://user-images.githubusercontent.com/19916394/128080494-1de2af91-a7ef-467c-8c63-67682997bd33.png)

This is on a 2017 Macbook Air
KeepassXC 2.6.6
macOS 11.5.1

Thank you!

**Comment by droidmonkey** [comment]
This appears to be a problem with your system. We show the systems file dialog box.

**Comment by le-jawa** [comment]
It looks like you're right; I tried it out on an identical system and had no trouble on that one.  This should be fun...
