### ISSUE TITLE
Auto-Type macOS Dual Monitor Focus Issue

### ISSUE THREAD

**Issue by nmajin** [keepassxreboot/keepassxc#6807]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

Auto-Type loses focus on the window if it's in another monitor; it will continue to only go to the left (primary) monitor, and it gets into this state sporadically, so it does work properly (obeys the window I would like the Auto-Type to work on) at times. If I drag the window over to monitor 1, where it appears Auto-Type wants to continue to work on, then it works, but it doesn't work on monitor 2.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Keyboard shortcut to launch Auto-Type to fill username and password on monitor 2
2. Choose the entry
3. Auto-Type fills out on random window on monitor 1

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

Expect the Auto-Type to go after the window I initiated the keyboard shortcut on instead of always going to monitor 1.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

Autofills the username and password from my picked entry always on monitor 1 (left monitor in this case, which is always my primary on macOS)

## Context
[NOTE]: # ( Give us any additional information you may have. )

I have to reboot macOS in order to fix the issue, restarting the app does not resolve the issue.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.6
Revision: 386b79a

Qt 5.15.2
Debugging mode is disabled.

Operating system: macOS 11.4
CPU architecture: x86_64
Kernel: darwin 20.5.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
- libgcrypt 1.9.3

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS

**Comment by droidmonkey** [comment]
#6762
