### ISSUE TITLE
Documentation Error: How to retrieve KeePassXC public GPG key

### ISSUE THREAD

**Issue by HUGHUSR** [keepassxreboot/keepassxc#6808]
Yes, this is trivial, but if you want to have people verify their downloads, a documentation error on how to accomplish that is not helpful.

From this webpage: `https://keepassxc.org/verifying-signatures`

It says:

The KeePassXC public key can be retrieved in any of the ways shown below:
From a keyserver:

`gpg --keyserver keys.openpgp.org --recv-keys CFB4C2166397D0D2`

But, when I attempt pull your key from openpgp.org, it doesn't find it...

`$ gpg --keyserver keys.openpgp.org --recv-keys CFB4C2166397D0D2
gpg: requesting key 6397D0D2 from hkp server keys.openpgp.org
gpgkeys: key CFB4C2166397D0D2 not found on keyserver
gpg: no valid OpenPGP data found.
gpg: Total number processed: 0`

Yes, I found the key elsewhere... so this is not for me, but for others.

IHTH!

**Comment by droidmonkey** [comment]
It is there: https://keys.openpgp.org/search?q=CFB4C2166397D0D2 linked to release (at) keepassxc.org https://keys.openpgp.org/search?q=release%40keepassxc.org
