### ISSUE TITLE
Creation of passwords according to the "password card principle

### ISSUE THREAD

**Issue by linux-lukas** [keepassxreboot/keepassxc#6809]
## Summary
**DO NOT include screenshots of your actual database!**
*Provide a brief overview of what the new feature is all about*
The (optional) creation of passwords according to the "password card principle" in order to provide people, especially those who are not so technically inclined, with an easy way to generate passwords that they can also derive.

## Examples
*Show us a picture or mock-up of your proposal*

## Context
*Why does this feature matter to you? What unique circumstances do you have? )*

I would anticipate that people would be more likely to consider using KeePassXC as a password manager if password creation was implemented according to the password card principle.

**Comment by droidmonkey** [comment]
What is this principle and why is it easier

**Comment by linux-lukas** [comment]
> What is this principle and why is it easier

There is a table that shows horizontally as the first row in packs of three the letters of the alphabet.

In the vertical first row are the numbers from 1 to 10, for example. 

Next to and below the rows are combinations of letters, numbers and special characters in packs of three.

Now the person goes and wants to generate a password for Mastodon using the password card principle and takes the word "Mastodon" as a keyword.

Now you go through each letter of the keyword from 1 to 10 and make a note for the respective position (e.g. for the first letter of Mastodon you would look at what is written in the first line for "mno" and make a note of that. If you have more letters than numbers (i.e. greater than 10, for example), then you start again.

I hope that I have been able to explain the principle behind password cards in a reasonably understandable way.

**Comment by droidmonkey** [comment]
No thank you, that is the antithesis of a password manager.
