### ISSUE TITLE
Inactivity timeout does not work properly

### ISSUE THREAD

**Issue by quicktrick** [keepassxreboot/keepassxc#6811]
I set the timeout to 7200 sec, but KeePassXC locks the database about 1 hour after login, regardless of activity. This is very annoying. It always worked like that.

KeePassXC - Version 2.6.6
Revision: 9c108b9

Qt 5.15.2
Debugging mode is disabled.

Operating system: Windows 10 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.19042

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
- libgcrypt 1.9.2-unknown

**Comment by bensonrlee** [comment]
I also experience the same behavior.  I set the timeout to 10 hours (36,000 seconds) but it locks itself automatically after some inactivity, which I am unable to ascertain yet how many minutes, but certainly not exceeding 2 hours.

**Comment by SynapseScribe** [comment]
subscribed. Any updates?

**Comment by SynapseScribe** [comment]
Hi. When will the new version be released? Thank you!

**Comment by droidmonkey** [comment]
2.7.0 final will be released today or tomorrow.
