### ISSUE TITLE
KeePassXC opening as superuser

### ISSUE THREAD

**Issue by dpotter4** [keepassxreboot/keepassxc#6812]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
I have installed a Flatpak version of KeePassXC. The version is KeePassXC 2.6.6. When I open KeePassXC, the title bar indicates that KeePassXC is running as the superuser. I do not get this behaviour with other Flatpak applications that I have installed.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Open KeePassXC (flatpak version).
2. 
3. 

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
KeePassXC should open with only normal user privileges.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
When I open KeePassXC, the title bar indicates that KeePassXC is running as the superuser

## Context
[NOTE]: # ( Give us any additional information you may have. )
I am running this on the Mate desktop under MX Linux

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION KeePassXC 2.6.6 (flatpak)
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows/Linux/macOS Linux
Desktop Env: Gnome/KDE/XFCE/Mate/Cinnamon Mate
Windowing System: X11/Wayland X11

**Comment by droidmonkey** [comment]
We don't currently support the flatpak deployment. There is also no way keepassxc is launching as superuser without a sudo or su command being used. Not sure what desktop env you are using, I've never used one that indicates "superuser" in the title bar.
