### ISSUE TITLE
Is the KeePassXC database format "plausibly deniable"?

### ISSUE THREAD

**Issue by return999** [keepassxreboot/keepassxc#6815]
Can someone tell by looking at a KeePassXC database file that it is indeed a KeePassXC database (I saved it without an extension)? I saved it using the KDBX 4.0 format. If yes, maybe this could be changed to make it indistinguishable from raw data (and this could satisfy those users like this one: https://github.com/keepassxreboot/keepassxc/issues/1751 - I know it could be placed inside some encrypted container but this adds unnecessary complications).

**Comment by droidmonkey** [comment]
Yes it necessarily has an unencrypted header that contains the data necessary to decrypt once the proper credentials are provided. We are not changing that as it is the kdbx standard, nor could we without completely breaking compatibility with other clients.
