### ISSUE TITLE
Databases remain open after lid is closed

### ISSUE THREAD

**Issue by pavelsaman** [keepassxreboot/keepassxc#6816]
## Overview

Databases are not locked when lid is closed.

## Steps to Reproduce

1. Check "Lock databases when session is locked or lid is closed" in settings
2. Close the lid
3. After opening the lid, the databases will still be open

## Expected Behavior

Databases get locked when the lid is closed.

## Actual Behavior

Databases remain unlocked.

## Context

I use xfce4 and no screensaver.
I can check that the lid status is closed by running the following command before closing the lid:

```
$ for i in {1..10}; do cat /proc/acpi/button/lid/LID/state; sleep 3; done
```

after opening the lid, I can see the status of the lid has changed:

```
state:      open
state:      open
state:      closed
state:      closed
state:      open
^C
```

```
KeePassXC - Version 2.6.6
Revision: 9c108b9

Qt 5.15.2
Debugging mode is disabled.

Operating system: Artix Linux
CPU architecture: x86_64
Kernel: linux 5.13.6-artix1-1

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- libgcrypt 1.9.3-unknown
```

Operating System: Linux
Desktop Env: xfce
Windowing System: X11

**Comment by droidmonkey** [comment]
See #4969.

**Comment by pavelsaman** [comment]
> See #4969.

I have seen that. It talks about xfce screensaver which I don't use. If that bug applies to my situation as well, then my bug can be closed of course.

**Comment by droidmonkey** [comment]
Yes it's the same reason. You need to send the appropriate dbus message to keepassxc to trigger the lock. If your lid close doesn't send that message then we'll never know it happens. You can achieve that in a couple ways but I don't have them handy atm.
