### ISSUE TITLE
Security: Clear entered master password after inactivity

### ISSUE THREAD

**Issue by plaa** [keepassxreboot/keepassxc#6817]
## Summary
I yesterday accidentally entered my master password but for some reason forgot to press enter.  Today, KeePassXC was patiently waiting for someone to press enter and the database was open.

For security, KeePassXC should clear the master password field after 1-2 minutes of inactivity.

**Comment by droidmonkey** [comment]
Using this one instead of #2335

**Comment by droidmonkey** [comment]
This is implemented

**Comment by QuestionMarkT** [comment]
Hey, can this be disabled somehow? It's annoying to me, I enter my long master password, then switch to other computer, then after a few mins when I want to correct password (as I entered incorrectly) it's already gone and I have to retype everything
