### ISSUE TITLE
Get this error message "The instruction at 0x000000004443002 referenced memory at 0x000000000000000000C. The memory could not be written. Click on OK to terminate the program."

### ISSUE THREAD

**Issue by Deeltjes** [keepassxreboot/keepassxc#6818]
## Overview
Get this error message "The instruction at 0x000000004443002 referenced memory at 0x000000000000000000C. The memory could not be written. Click on OK to terminate the program."

## Steps to Reproduce
1. Start KeePassXC
2. Crashes

## Expected Behavior
Application start.

## Actual Behavior
Application crash. Windows offers to debug the program.

[NOTE]:
KeePassXC - 2.6.6
Revision: {BC0E4D61-153A-4485-8A3F-AC23148A2A07}

[NOTE]:
Operating System: Windows 10
Version: 10.0.19043 Build 19043

[NOTE]:
Resolution (temporary I presume):
Revert to KeePassXC - 2.6.5

**Comment by droidmonkey** [comment]
Unfortunately that won't help us. What were you doing when that happened? First time seeing this in this version? Does it happen when using a snapshot build? https://snapshot.keepassxc.org

**Comment by Deeltjes** [comment]
I'm trying to replicate is. Unsuccessfully. I installed KeePassXC 2.6.6 using the installer file I downloaded earlier. Now it keeps working. Strange.
