### ISSUE TITLE
Does not work with firejail (Keepassx does work)

### ISSUE THREAD

**Issue by t4777sd** [keepassxreboot/keepassxc#682]
Running keepass installed via snap does not work with firejail. Here is the results:

firejail --noprofile /snap/bin/keepassxc
Parent pid 8990, child pid 8991
Child process initialized in 39.31 ms
cannot bind-mount the mount namespace file /proc/2/ns/mnt -> keepassxc.mnt: Permission denied
support process for mount namespace capture exited abnormally

## Expected Behavior
Software runs

## Current Behavior
Software exxits

## Possible Solution
Not sure

## Steps to Reproduce (for bugs)
Install latest firejail. Install latest keepassxc. Run with firejail and it does not work. Keepassx does work.

## Context
Cannot run keepassxc in a secure way.

## Your Environment
* KeePassXC version: Latest release
* Ubuntu 16.04
* Latest firejail

**Comment by phoerious** [comment]
I don't think this is a KeePassXC problem. You are trying to sandbox Snap which needs to do some background magic such as mounting loop devices. I don't think that works like you want it to. Besides, I don't see why you would want to sandbox our Snap package with Firejail in the first place when the Snap daemon itself already provides a sandbox around KeePassXC.

**Comment by t4777sd** [comment]
This is the first snap application I have installed, but looking at the snap.yaml it appears that keepassxc is requesting network access. As you can imagine, that is a pretty big security flaw in a password application, so firejail is necessary to ensure things like this get denied.

**Comment by phoerious** [comment]
It's not a flaw, but if you don't like it, you can disconnect the network and network-bind plugs eliminating the need for another sandbox wrapper.

**Comment by t4777sd** [comment]
Why is a password app needing network connection in the first place?

**Comment by phoerious** [comment]
We need the network plug for fetching favicons and the network-bind plug for providing an KeePassHTTP interface.

**Comment by droidmonkey** [comment]
We also use network to establish single instance. And like phoerious said you can simply "unplug" the network plugs using "snap interface" method.

**Comment by TheZ3ro** [comment]
Or you can compile it yourself without HTTP plugin

**Comment by t4777sd** [comment]
Thanks guys. I will just use a non-snap version that can work with firejail. Btw, the program is amazing. You guys have done a great job in creating a better program, communication, etc. Really an awesome open source team!
