### ISSUE TITLE
Autotype does not execute in Fedora 34 Workstation

### ISSUE THREAD

**Issue by KeivaOG** [keepassxreboot/keepassxc#6826]
## Overview
When attempting to use autotype, the action is not performed.  Neither the global shortcut, keyboard shortcut from within KPXC, nor the autotype toolbar button works.  It is not executed for any website or on any KPXC entry.

## Steps to Reproduce

**From within KPXC**
1. Open KPXC with master password.  No key file used.
2. Search for and select entry.
3. Key in shortcut CTRL-SHIFT V to perform autotype -OR- press toolbar button.

**From Firefox (using global shortcut)**
1. Navigate to website.
2. If necessary, click to place cursor in Username field.
3. Key in global shortcut (CTRL-ALT-SHIFT V).

## Expected Behavior
When entering the shortcut or clicking the button, KPXC should minimize and enter the username and password combo as specified in the entry's autotype sequence.

For instance, if I am in KPXC and select an entry, when I press CTRL-SHIFT V, the app should minimize and begin performing the autotype sequence.

## Actual Behavior
After keying in the shortcut or pushing the toolbar button, the KPXC window minimizes, but the username and password are not typed.  

## Context
When opening KPXC from the command line, no errors are reported in the terminal.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.6
Revision: 9c108b9

Qt 5.15.2
Debugging mode is disabled.

Operating system: Fedora 34 (Workstation Edition)
CPU architecture: x86_64
Kernel: linux 5.13.8-200.fc34.x86_64

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- libgcrypt 1.9.3-unknown

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: Gnome
Windowing System: Wayland

**Comment by droidmonkey** [comment]
Autotype will not work on Wayland unless both keepassxc and the target window are actually running on x11
