### ISSUE TITLE
ctrl+shift+a cannot be set as global auto-type shortcut from gui

### ISSUE THREAD

**Issue by ion201** [keepassxreboot/keepassxc#6827]
## Overview
Trying to set the global auto-type shortcut to ctrl+shift+a triggers the new shortcut "always on top", which messes up the input box, making it impossible to set this as the auto-type shortcut. Adding the following lines directly to `keepassxc.ini` is a suitable workaround:

```
GlobalAutoTypeKey=65
GlobalAutoTypeModifiers=100663296
```

## Steps to Reproduce
1. Open the auto-type settings
2. Select the "Global Auto-type shortcut" box
3. Try to make the shortcut ctrl+shift+a

## Expected Behavior
The auto-type shortcut should become ctrl+shift+a and the existing "always on top" shortcut should be masked when the settings are applied.

## Actual Behavior
The window flashes to the background for a brief second and the shortcut box is not filled correctly, making it impossible to set from the gui.

## Version info
KeePassXC - Version 2.6.6
Revision: 9c108b9

Qt 5.15.2
Debugging mode is disabled.

Operating system: Arch Linux + cinnamon and windows 10

**Comment by droidmonkey** [comment]
Generally speaking a Ctrl + Shift combo is not a good choice for a global shortcut since those are captured by many applications. Recommend Ctrl + Alt instead.

**Comment by amccombsahce** [comment]
using KeePassXC 2.4.3 on Ubuntu 20.04
I tried to set Ctrl + Alt + A , but KeePassXC would not allow it.

**Comment by ion201** [comment]
> Generally speaking a Ctrl + Shift combo is not a good choice for a global shortcut since those are captured by many applications. Recommend Ctrl + Alt instead.

Counterpoint, ctrl+alt can have different behavior on windows depending on your keyboard layout: https://docs.microsoft.com/en-us/windows/win32/uxguide/inter-keyboard#choosing-shortcut-keys-what-not-to-do

> Don't use Ctrl+Alt combinations, because Windows interprets this combination in some language versions as an AltGR key, which generates alphanumeric characters.

But anyway, the issue is not that I want ctrl+shift+a specifically, but that hitting ctrl+shift+a there results in unexpected behavior. If you're setting a keyboard shortcut, it visually appears that the shortcut field is capturing the keyboard output so it is very confusing when those keyboard inputs have the side-effect behavior of triggering unrelated shortcuts.

**Comment by droidmonkey** [comment]
Yah understand the general issue, and certainly not limited to always on top either.
