### ISSUE TITLE
Keepassxc on Linux Mint - where is it installed

### ISSUE THREAD

**Issue by pwilliamson19** [keepassxreboot/keepassxc#6830]
## Overview
This may be a non-question, but I'm new to Linux and just trying to get all my essential software running before migrating from Windows.
Installed Keepassxc on Linux Mint 20 using SNAP, as per instructions on the website . Appeared to run OK but no icon appeared on desktop and I can't see where the program has been installed in the filing system.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1.sudo rm /etc/apt/preferences.d/nosnap.pref
sudo apt update
sudo apt install snapd
sudo snap install keepassxc

 sudo snap install keepassxc
2. 
3. 

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows/Linux/macOS
Desktop Env: Gnome/KDE/XFCE/Mate/Cinnamon
Windowing System: X11/Wayland

**Comment by droidmonkey** [comment]
Should be runnable from /snap/bin/keepassxc

**Comment by pwilliamson19** [comment]
I've found it. Also found it in the Software Manager which is easier to work with. Thanks
