### ISSUE TITLE
After repeated use of auto-type, keyboard switching stops working for all applications and the system.

### ISSUE THREAD

**Issue by mastezont** [keepassxreboot/keepassxc#6831]
After repeated use of auto-type, keyboard switching stops working for all applications and the system.

Open Google Chrome (92.0.4515.131) and go to sites with authorization. Use auto-type to fill in authorization forms  by pressing the auto-type button in KeePassXC. After a random amount of using the auto-type, switching between layouts (English (American) and Russian) using the key combination (ALT+SHIFT or CTRL+SHIFT, etc.) stops working in any applications and system.

KeePassXC - Version 2.6.6
Revision: 9c108b9

Qt 5.12.8
Debug mode is off.

Operating system: Linux Mint 20.2
CPU architecture: x86_64
Kernel: linux 5.4.0-80-generic

Included extensions:
- Auto input
- Browser integration
- SSH agent
- KeeShare (access with and without signatures)
- YubiKey
- Integration with Secret Service

Cryptographic libraries:
- libgcrypt 1.8.5

[NOTE]: 
Operating System: Linux Mint 20.2 (the main language of the system is Russian)
Desktop Env: Cinnamon
Windowing System: X11 (?)

**Comment by droidmonkey** [comment]
This is fixed on develop branch, will be released with 2.7.0
