### ISSUE TITLE
Auto dialog focus cause loss of data.

### ISSUE THREAD

**Issue by bjwest** [keepassxreboot/keepassxc#6834]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
I was creating a new entry and had most of the pertinent information filled out in the Add Entry form.  While I was waiting on an email for some info I needed for that entry, I was typing in a forum when the inactivity timer kicked in.  The dialog asking me if I wanted to save the data or not popped up on another screen and took focus.  I was in the middle of typing and the dialog took my keystrokes as input and locked KeePassXC, deleting all the data I'd just entered.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Have KeePassXC open with new or edited data that has yet to be saved.
2. Be typing in another window when the inactivity timer triggers
3. 

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
KeePassXC waits patiently for me to give its dialog focus and select the option of my choice.  A forced notification sound would be nice as well, seeing as how KDE no longer has default notification sounds on most things.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
KeePassXC's dialog takes focus and takes the first recognized key as input.

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.6
Revision: 9c108b9

[NOTE]: # ( Pick choices based on your environment )
Operating System: KDE neon 5.22
KDE Plasma Version: 5.22.4
KDE Frameworks Version: 5.84.0
Qt Version: 5.15.3
Kernel Version: 5.11.0-25-generic (64-bit)
Graphics Platform: X11

**Comment by droidmonkey** [comment]
There is nothing we will do about this. KDE must be forcing the focus when a dialog opens, we do not force focus in this event. Recommend saving your data often.
