### ISSUE TITLE
Ctrl+Tab as keyboard shortcut for switching tabs on macOS

### ISSUE THREAD

**Issue by dancojocaru2000** [keepassxreboot/keepassxc#6835]
## Summary
Similar to web browsers, it would be nice to be able to switch tabs using Ctrl+Tab and Ctrl+Shift+Tab.

**Comment by droidmonkey** [comment]
This is already possible, what OS are you using?

We also support Alt+[#] (or Ctrl+[#] on Linux) to select the [#] tab.

**Comment by dancojocaru2000** [comment]
You're right, I just checked on Linux and it works.

This is a macOS only issue then.

**Comment by droidmonkey** [comment]
If I recall we could not get this to work on macOS (Qt or OS limitation). The keyboard shortcut is Ctrl+PgUp/PgDn

**Comment by dancojocaru2000** [comment]
It doesn't sound like it would be an OS issue since all web browsers, Safari included, use Ctrl+Tab.

**Comment by droidmonkey** [comment]
This was discussed before in #2008

**Comment by droidmonkey** [comment]
Since this doesn't seem possible with Qt (we've tried several times), closing.
