### ISSUE TITLE
Opening an entry to view password and the pressing cancel often crashes keepassxc

### ISSUE THREAD

**Issue by ralfstrandell** [keepassxreboot/keepassxc#6836]
Summary: I view the password (by double clicking the entry) and then click cancel and the app just goes away.

Steps to reproduce:
1. Run KeepassXC on current Debian stable, XFCE
2. Double click on a password entry to view the password
3. Click (e.g.) on cancel to return to main view.
4. The application often crashes.

Expected behaviour:
Return to main view.

Actual behaviour:
User interface gone.

Context:
Note 1: This problem is quite frequent, but does not always happen.
Note 2: Password file is synchronized to cloud by another app (but I did press cancel - no change!)
Note 3: KeePassXC - Version 2.3.4 Revision: 6fe821c
Note 4: Debian stable: 4.19.0-17-amd64 #1 SMP Debian 4.19.194-3 (2021-07-18) x86_64 GNU/Linux
Note 5: Desktop Env: XFCE
Note 6: Windowing system: X11

**Comment by droidmonkey** [comment]
We are on version 2.6.6 at this point, you'll need to upgrade using the snap distribution, appimage, or ppa.
