### ISSUE TITLE
When creating or editing entry, Setup TOTP reset fields to original state

### ISSUE THREAD

**Issue by woowoo803** [keepassxreboot/keepassxc#6838]
## Overview
When manually creating a new login with TOTP, on completion of the "setup TOTP" step it wipes other information entered previously.  Note this only happens with a new entry, if adding TOTP to an existing entry it does not happen.

## Steps to Reproduce
1. Start a new login entry
2. Enter title, username, password, URL
3. Click Entries -> TOTP -> Set up TOTP
4. Enter a TOTP code etc.
5. Click OK
6. Title through URL entered previously are wiped.

## Expected Behavior
Set up of TOTP should leave previous entries intact

## Actual Behavior
When the Set up TOTP step is complete and click on Ok (within the TOTP pop-up) the Title through URL entries are wiped

## Context
This only happens with a new entry, so when the Title through URL information is entered just before selecting Set up TOTP.  If Set up TOTP is used with an existing entry this does not occur.

[NOTE]:
KeePassXC - VERSION 2.6.6
Revision: REVISION 9c108b9

[NOTE]:
Operating System: Windows

**Comment by droidmonkey** [comment]
Found it, we were reloading data from the entry if it was modified outside of the edit widget. This doesn't make sense when creating a new entry (all data is blank), so when TOTP was set it triggered the modified signal on the empty entry and blanks out the fields. Adding a creation guard to that signal fixed the problem.

**Comment by droidmonkey** [comment]
Oof nevermind, the fix to this will require the much dreaded complete rewrite to the edit entry widget.

**Comment by michaelk83** [comment]
> The fix to this will require the much dreaded complete rewrite to the edit entry widget.

I don't know if such a rewrite would be part of #8228 for 2.8.0 (?), but if not, a quick workaround would be to check for unsaved changes before starting the TOTP setup, and prompt the user to save first.
