### ISSUE TITLE
Minimum Password Entropy Option

### ISSUE THREAD

**Issue by Coderdude112** [keepassxreboot/keepassxc#6839]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
It would be nice to include an option in the password generator to only give passwords generated with at least X amount of entropy.

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )
Including a small numerical input box when the advanced option is checked on the password generator would be an easy way of adding this functionality to the UI.

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
I try to keep my passwords above a certain entropy for security reasons, along with other things. Having KeepassXC generate passwords that are at least above the entropy requirement would save time on my end from clicking the regenerate button until a password is generated with the minimum entropy met.

**Comment by droidmonkey** [comment]
This is very similar to #5785. Entropy is just a theoretical calculation. The only thing that really matters at the end of the day is password length. If you are using 15 or more characters it doesn't matter what options you choose.

**Comment by Coderdude112** [comment]
So is the entropy measurement just for information then?

**Comment by droidmonkey** [comment]
That's correct, it's a fuzzy measure of the "randomness" of the password. Anything in the good or great range is completely uncrackable.
