### ISSUE TITLE
Hide username in entry preview panel when hidden in entry list

### ISSUE THREAD

**Issue by Skull31** [keepassxreboot/keepassxc#6840]
## Summary
Add button to hide username when viewing an entry.

## Examples
Add button to hide username same as for password:
![image](https://user-images.githubusercontent.com/8089916/129479275-291b69ef-6fca-483a-9e0e-64b4f3845ab0.png)

## Context
There is an option to hide username in the list. It would be great if there was an option to hide it also in the popup view (when clicking on entry).
I am sharing my screen a lot and sometimes it would be great if everything was hidden, not just passwords.

**Comment by droidmonkey** [comment]
There is such an option and it's enabled by default.

**Comment by droidmonkey** [comment]
Your title did not match your request. In the meantime you can disable showing the preview panel from the View menu.

**Comment by droidmonkey** [comment]
#6306
