### ISSUE TITLE
KConfigIni errors in system log when opening database

### ISSUE THREAD

**Issue by BillDietrich** [keepassxreboot/keepassxc#6843]
## Overview
While investigating an issue, I noticed that my system log (journalctl) is showing a lot of errors when I launch KeePassXC and open the password database.  I don't know how long this has been happening; the application and database seem to work okay.  How can I fix these errors ?  Are they bugs ?

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Launch KeePassXC and open password database.
2. Open a terminal / CLI window.
3. journalctl --since=today | grep KConfigIni | head
4. Output shows:
```
Aug 16 10:51:05 laptop2 kcminit_startup[3080]: kf.config.core: "KConfigIni: In file /usr/share/kservices5/searchproviders/rae.desktop, line 94: " "Invalid escape sequence \"\\{\"."
Aug 16 10:51:05 laptop2 kded5[3076]: kf.config.core: "KConfigIni: In file /usr/share/kservices5/searchproviders/rae.desktop, line 94: " "Invalid escape sequence \"\\{\"."
Aug 16 10:51:23 laptop2 plasmashell[3158]: kf.config.core: "KConfigIni: In file /usr/share/kservices5/searchproviders/rae.desktop, line 94: " "Invalid escape sequence \"\\{\"."
Aug 16 10:51:23 laptop2 plasmashell[3158]: kf.config.core: "KConfigIni: In file /usr/share/kservices5/searchproviders/rae.desktop, line 94: " "Invalid escape sequence \"\\{\"."
Aug 16 10:51:26 laptop2 plasmashell[3158]: kf.config.core: "KConfigIni: In file /home/user1/something/KeePassDatabase.kdbx, line 1: " Invalid entry (missing '=')
Aug 16 10:51:26 laptop2 plasmashell[3158]: kf.config.core: "KConfigIni: In file /home/user1/something/KeePassDatabase.kdbx, line 2: " Invalid entry (missing '=')
Aug 16 10:51:26 laptop2 plasmashell[3158]: kf.config.core: "KConfigIni: In file /home/user1/something/KeePassDatabase.kdbx, line 4: " Invalid entry (missing ']')
Aug 16 10:51:26 laptop2 plasmashell[3158]: kf.config.core: "KConfigIni: In file /home/user1/something/KeePassDatabase.kdbx, line 5: " Invalid entry (missing '=')
Aug 16 10:51:26 laptop2 plasmashell[3158]: kf.config.core: "KConfigIni: In file /home/user1/something/KeePassDatabase.kdbx, line 7: " Invalid entry (missing '=')
Aug 16 10:51:26 laptop2 plasmashell[3158]: kf.config.core: "KConfigIni: In file /home/user1/something/KeePassDatabase.kdbx, line 8: " Invalid entry (missing ']')
```
There are hundreds or thousands more of such lines.

I do have various binary attachment files (images, etc) stored in my database.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.6
Revision: 9c108b9

Qt 5.15.2
Debugging mode is disabled.

Operating system: Fedora 34 (KDE Plasma)
CPU architecture: x86_64
Kernel: linux 5.13.9-200.fc34.x86_64

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- libgcrypt 1.9.3-unknown

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: KDE
Windowing System: X11

**Comment by droidmonkey** [comment]
That is plasmashell trying to open your database as a config file. You probably have a file association issue going on. This is NOT keepassxc.

**Comment by BillDietrich** [comment]
Okay, I had a KDE shortcut that ran "keepassxc databasefilename".  I'll try it without the filename.
