### ISSUE TITLE
Firejail causes KeePassXC delay, maybe only with WIreGuard VPN

### ISSUE THREAD

**Issue by BillDietrich** [keepassxreboot/keepassxc#6844]
I switched from using OpenVPN protocol to using WireGuard protocol, with Windscribe VPN.  After doing that, clicking on a link in KeePassXC, or doing ctrl-shift-U to open a site, now had a 10-15 second delay before switching to the browser window.

At first I though it was a DNS error, or a KeePassXC bug.  But then I realized I was running KeePassXC inside Firejail, and journalctl was showing some error in kde-open5 that took 5 seconds to time out, and maybe some other KDE-related errors.  So I stopped using Firejail for KeePassXC, and now there is no delay when using WireGuard.

I don't understand why this would be different for OpenVPN and WireGuard, or how to fix the Firejail profile for KeePassXC to work properly with WireGuard.  I don't know if this should be documented somewhere, or reported as a bug to Firejail, or what.

My system info:

KeePassXC - Version 2.6.6
Revision: 9c108b9

Qt 5.15.2
Debugging mode is disabled.

Operating system: Fedora 34 (KDE Plasma)
CPU architecture: x86_64
Kernel: linux 5.13.9-200.fc34.x86_64

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- libgcrypt 1.9.3-unknown

X11 windowing.

**Comment by droidmonkey** [comment]
We don't endorse any firejail profiles for keepassxc, this isn't our bug. You probably need to allow access to something kde-open5 is trying to use,  although technically you should be outside firejail at that point. This could also be your VPN forcing a connection to be established before opening the browser.

**Comment by BillDietrich** [comment]
Yes, just wanted to get it documented in case someone else hits same problem.

**Comment by BillDietrich** [comment]
Any idea why this would be different for WireGuard as opposed to OpenVPN ?

**Comment by droidmonkey** [comment]
Have no idea
