### ISSUE TITLE
Can't unlock database when using version 1 XML key files

### ISSUE THREAD

**Issue by MarcFC** [keepassxreboot/keepassxc#6845]
## Overview
Database with version 1 XML key file can be opened with v2.6.2, but can't be opened with v2.6.3. When using v.2.6.3 error message shows "Failed to open key file: Unexpected key file data! Key file may be corrupt.".

## Steps to Reproduce
1. Install v2.6.2
2. Open database and select key file
3. Enter password and click OK: database unlocked successfully
4. Install v2.6.3
5. Open database and select key file
6. Enter password and click OK: database unlocked failed. Error: "Failed to open key file: Unexpected key file data! Key file may be corrupt."

## Expected Behavior
[Using v2.6.3]
1. Open database and select key file
2. See the message: "WARNING: You are using an old key file format which KeePassXC may stop supporting in the future. Please consider generating a new key file."
3. Enter password
4. Click OK
5. Unlock database successfully

## Actual Behavior
[Using v2.6.3]
1. Open database and select key file
2. Enter password
3. Click OK
4. Unlock database fails. Error: "Failed to open key file: Unexpected key file data! Key file may be corrupt."

## Context
KeePassXC - Version 2.6.3
Revision: beae186
Operating System: macOS 10.15

**Comment by droidmonkey** [comment]
You have a corrupt key file. We added checks to the format of the file and enforce those now. Look at your key file and make sure it doesn't look mangled.

**Comment by droidmonkey** [comment]
See #5924
