### ISSUE TITLE
Easy way to see which entries are connected to browser

### ISSUE THREAD

**Issue by darix** [keepassxreboot/keepassxc#6847]
## Summary
Maybe as part of the database report
This would make it easy to review if a browser really only has access to the entries it should have.

**Comment by droidmonkey** [comment]
Good idea for browser integration @varjolintu

**Comment by varjolintu** [comment]
This would probably need a new tab page for the browser extension. Not sure if it's wise to bloat any of the current pages, which already show a bit different data than this.

**Comment by droidmonkey** [comment]
New page to the reports widget I suppose.

**Comment by varjolintu** [comment]
A few things to consider:
Entries that have been used with the extension without remembering any settings using Browser Access Confirmation dialog are also accessible. Should we also count all entries with a URL and group/entry settings that allow the entry to be used by the extension?

**Comment by michaelk83** [comment]
You could show a few distinct levels, maybe color-coded similar to password quality: has URL, has browser settings, accessed recently, etc.

**Comment by varjolintu** [comment]
AFAIK the last access time doesn't tell you has the entry been accessed manually, from Auto-Type, from extension etc.. It's just the last accessed time. So that's probably not usable for this kind of data.

**Comment by droidmonkey** [comment]
Last accessed is the same as modified, we should probably just remove that from the gui since it is misleading. This request, IMO, is only focused on those entire that have been explicitly allowed or denied access to the browser extension (ie, has browser extension custom data fields).

This is also rather unnecessary after we merged the group settings for browser since you can setup a specific group that is accessible to the extension and block all others.

**Comment by varjolintu** [comment]
Just an update: this is now under progress.

**Comment by varjolintu** [comment]
Anything else needed for this? Any extra filters etc? Now it shows if entries have a URL and Browser Integration settings in th custom data.

<img width="965" alt="Screenshot 2021-10-24 at 15 35 12" src="https://user-images.githubusercontent.com/24570482/138594421-e2e93a5c-76db-4c1e-9040-712434c50112.png">

**Comment by droidmonkey** [comment]
Can you show the URL's for each entry in a column (ie, join all the URL attributes together into a list)

**Comment by varjolintu** [comment]
> Can you show the URL's for each entry in a column (ie, join all the URL attributes together into a list)

Good idea.

**Comment by droidmonkey** [comment]
also to be consistent with the other reports, the path should be to the far left. Actually replacing the "URL" column color with the URL list would be perfect. Not sure what "Set" is supposed to mean, that column may need some explaining.

**Comment by varjolintu** [comment]
> also to be consistent with the other reports, the path should be to the far left. Actually replacing the "URL" column color with the URL list would be perfect. Not sure what "Set" is supposed to mean, that column may need some explaining.

Replacing the URL column could be even better. Still, I'm not sure if it's easier and quicker to see entries with URL's using these kind of coloured boxes. Gotta think this over.

"Set" is just short for "Settings". It's not the final text, and I haven't figured out what it should be, considering translations etc. When a row is selected, the content changes to "true" or "false" and tooltips will give a longer explanation.

**Comment by darix** [comment]
Maybe a drop down to select only one browser? "show me all entries that my firefox can access"

**Comment by droidmonkey** [comment]
Entries aren't bound to browsers, they are bound to sites. The browser connection gives the extension access to all entries that are allowed regardless of underlying browser.

**Comment by darix** [comment]
uhm IIRC you can say "allow this entry for this browser from now on"

so this should be stored somewhere no?

**Comment by droidmonkey** [comment]
That is allow this entry for this _site_

**Comment by darix** [comment]
Well yeah and if you read the initial post of this feature request it was to be able to see which browser can access which site :)

**Comment by varjolintu** [comment]
Decided to modify things a little bit:
- Added a checkbox to show only entries with URL(s) set
- First column now shows a list of URLs
- Second and third column shows Allowed and Denied URL(s)

<img width="1240" alt="Screenshot 2021-11-28 at 17 52 21" src="https://user-images.githubusercontent.com/24570482/143775972-863a09d3-3f54-4977-903d-b325827d011e.png">

Anything more to add or modify? Gonna make a PR soon :)
