### ISSUE TITLE
MacOS 10.13 KeePassXC-2.6.6 image not recognized

### ISSUE THREAD

**Issue by markNZed** [keepassxreboot/keepassxc#6848]
## Overview
Disk image from https://github.com/keepassxreboot/keepassxc/releases/download/2.6.6/KeePassXC-2.6.6-x86_64.dmg results in warning "The following disk images couldn't be opened" reason "image not recognized"

So I cannot upgrade to 2.6.6

## Steps to Reproduce
1. Download and try to install 2.6.6 on MacOS 10.13.6

## Expected Behavior
Installer to run

## Actual Behavior
Warning "The following disk images couldn't be opened" reason "image not recognized"

## Context
I could download the ARM64 version of the image and it does not give that warning (of course it doe not work because I'm on an x86 machine)

Operating System: macOS

**Comment by droidmonkey** [comment]
Re-download the dmg. This is shown when the dmg is corrupted. It is certainly not corrupted on our side.

**Comment by markNZed** [comment]
You are right.  I had downloaded it twice and got the same error. I did not get that error downloading the ARM64 version. I just tried downloading it again and it worked. Thanks.
