### ISSUE TITLE
[Feature Request] Multilingual diceware

### ISSUE THREAD

**Issue by chrpinedo** [keepassxreboot/keepassxc#685]
Be able to choose the language of the generated diceware passphrase.

## Expected Behavior
When the diceware passphare is going to be generated it would be interesting to be able to choose the language to use. Keepassxc could provide world lists for different languages or it could allow loading new word lists for different languages. Perhaps, the first approach (word lists provided by KeepassXC) could be more secure.

For example, this is the official diceware world list for Spanish: http://world.std.com/~reinhold/diceware_espanol/DW-Espanol-1.txt

## Current Behavior
Nowadays, version 2.2.0, the only options to generate the diceware passphrase are the number of words and the separation between words. This feature would add one additional option: the language.

## One step ahead...
Could it be interesting to provide multilingual diceware passphrases?? This is, to select multiple languages when the passphrase is going to be generated?? It could provide a better entropy for a passphrase with the same number of words and It could be interesting for people who know more than one language.

**Comment by phoerious** [comment]
You can already use your own word lists. Just put them in share/wordlists.

**Comment by chrpinedo** [comment]
Should I overwrite the already provided "eff_large.wordlist" file or add an additional file? In case of having multiple files how is the wordlist selected? Thanks,

**Comment by phoerious** [comment]
Just add it next to the existing file. You can choose which list to use from the user interface.

**Comment by chrpinedo** [comment]
yes it is working great and I create some AUR packages in Arch Linux to install new wordlists (https://aur.archlinux.org/packages/keepassxc-wordlist-spanish/ https://aur.archlinux.org/packages/keepassxc-wordlist-eyeware/). Thanks!

**Comment by rodoviario** [comment]
I want to do the same thing, but I have de appimage for linux64, and dont have a clue on where to find the share folder mentioned. Is there a way/feature to add the option for custom wordlist file directly on the password generator window?

**Comment by ventolinmono** [comment]
@rodoviario The folder on Debian is on /usr/share/keepassxc/wordlists
