### ISSUE TITLE
[Bug & Enhancement] Obliviance to the path of database

### ISSUE THREAD

**Issue by lifehome** [keepassxreboot/keepassxc#6853]
## Overview
With unchecking the box of "remembering" last used database, KeePassXC should **not** remember what was the last database it opened, **nor** it should remember where it locates.

<img width="390" alt="螢幕截圖 2021-08-19 13 56 13" src="https://user-images.githubusercontent.com/1886237/130015672-8118cb77-8638-4c79-81ad-6ddad75f8475.png">

However, as of KeePassXC 2.6.6 (macOS), when a user locks and closes a database, regardless the storage destination is a removable device, or local home directory, KeePassXC will open the last location where the database was located in.

This is not a privacy-oriented design, and violates the meaning of unchecking the configuration boxes shown above.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Open a database in KeePassXC 2.6.6
2. Close the database, or just quit KeePassXC
3. Now reopen the program and click "Open Database" button, and you will be directed to the last location the database was located in.

or

1. Open a database in KeePassXC 2.6.6
2. Close the database, or just quit KeePassXC
3. `cat ~/Library/Caches/KeePassXC/keepassxc.ini` and see the saved `LastDir` is the actual location of our last opened database location

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
KeePassXC should open either the current user home directory, or anywhere else.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
KeePassXC opened the last known location of the database.

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.6.6
Revision: 386b79a

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS 11.5.1
Desktop Env: Finder
Windowing System: The very magical X11 by Apple

**Comment by droidmonkey** [comment]
Already fixed in #6711
