### ISSUE TITLE
Cannot snap v2.6.6 to one side of desktop [Linux/XFCE]

### ISSUE THREAD

**Issue by aaryan-rampal** [keepassxreboot/keepassxc#6856]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Use `sudo snap install keepassxc` to install the latest version (or add the `phoerious/keepassxc` ppa and install using apt).
2. Open the application 
3. Try to drag it to one side of the desktop

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
It should 'snap' to that one side of the desktop, allowing you to view two applications side by side.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
It doesn't snap, it just proceeds to move out of view of the monitor.

## Context
[NOTE]: # ( Give us any additional information you may have. )

KeePassXC - Version 2.6.6
Revision: 9c108b9
Distribution: Snap

Qt 5.9.5
Debugging mode is disabled.

Operating system: Ubuntu Core 18
CPU architecture: x86_64
Kernel: linux 5.11.0-27-generic
Desktop Env: XFCE

Cryptographic libraries:
- libgcrypt 1.8.1

For what it's worth, I have a feeling it may have something to do with the minimum size limit Keepass has. I remember in Windows, you can't narrow the application after a certain width is achieved.

It snaps on v2.4.3 which is the default keepassxc in the apt store without adding a ppa. Only problem with using that version is it doesn't support dark mode.

**Comment by droidmonkey** [comment]
Works perfectly fine for me, tested in a virtual machine.

**Comment by aaryan-rampal** [comment]
Did you use the XFCE desktop environment? It works well in gnome for me but it produces this bug in xfce.

**Comment by droidmonkey** [comment]
Yes I did use xfce

**Comment by aaryan-rampal** [comment]
Huh, weird. Well, thanks for checking it out anyways.
