### ISSUE TITLE
Custom Sorting of Attributes in a particular entry

### ISSUE THREAD

**Issue by Lumenbolt** [keepassxreboot/keepassxc#6859]
## Summary
It'd be great to have an option to arrange attributes in any arbitrary order, instead of having it automatically sort alphabetically.

## Examples
This is what any entry's attributes would look like now:

![2021-08-21_03-57](https://user-images.githubusercontent.com/63922865/130305808-1c6e138f-8f58-45f7-901f-81ed16dfb296.png)

Would be great to have a way to arrange it, say E above B or so on...
 
## Context

This feature would be of great help if, say, I have to note down a form/document as an entry and each field of the form would correspond to an attribute and having it automatically sorted alphabetically would mess up the order of the form/document.
I was personally quite bummed out to find there was no way to arrange them in an order I wanted it to, which is a basic yet quite nifty feature in a password manager/vault.

**Comment by droidmonkey** [comment]
Prepend the attribute with a number to sort them in the order you want, for now. It is unlikely we'll add this feature since custom entry layouts is supposed to handle this problem way more elegantly.

**Comment by Lumenbolt** [comment]
> custom entry layouts is supposed to handle this problem way more elegantly.

Oh, I never knew we could customize entry layouts, is there a wiki/article on this feature I could know more about?

**Comment by droidmonkey** [comment]
That isn't implemented yet but it's a major feature we are interested in making happen

**Comment by Lumenbolt** [comment]
Great, looking forward to this major feature!

**Comment by droidmonkey** [comment]
#863 if you are curious
