### ISSUE TITLE
Reveal protected attribute(s) on "bottom panel"

### ISSUE THREAD

**Issue by Lumenbolt** [keepassxreboot/keepassxc#6860]
## Summary
It'd be helpful to "temporarily" reveal protected attribute(s) on the panel below the list of entries, just the way there is an option to reveal the password of the selected entry.

## Examples
This is what the bottom panel looks like for protected attributes:

![2021-08-21_04-32](https://user-images.githubusercontent.com/63922865/130306337-53af992c-0ba9-487a-876a-8f76defafc0c.png)

It'd be helpful to have a button beside the attribute to reveal it, just as it is in the case of the password:

![2021-08-21_04-33](https://user-images.githubusercontent.com/63922865/130306376-0ecf421f-0b92-440f-8b6d-efa7bad74c4e.png)

## Context

Would help to quickly access a protected attribute instead of having to open "edit entry" tab of the particular entry.
E.g CVV of a credit card, etc..

**Comment by droidmonkey** [comment]
This is already implemented #6512
