### ISSUE TITLE
Auto-Type broken when there's some window "always on top"

### ISSUE THREAD

**Issue by dasdadaadasdadads** [keepassxreboot/keepassxc#6863]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
Auto-Type always types in the window which is "Always on Top".

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Open some window (Gnome), and check "Always on Top",
2. open the login page of your email,
3. open KPXC and Auto-Type.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Auto-Type on the login page of my email.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Auto-Types on the Window which is always on top.

## Context
[NOTE]: # ( Give us any additional information you may have. )
/

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.6.2
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: Gnome
Windowing System: IDK

**Comment by hifi** [comment]
Try using the global Auto-Type shortcut as it should preserve focus.

**Comment by droidmonkey** [comment]
No longer a problem in 2.7.0
