### ISSUE TITLE
Add import password from webbrowser

### ISSUE THREAD

**Issue by MatiasMovie** [keepassxreboot/keepassxc#6872]
Summary
Add import password from webbrowser like chrome, firefox, vivaldi etc.

Context
I think it is important because of security, CSV is not secured in any way so if someone forgets a file or some software will steal documents, someone unauthorized access to passwords

**Comment by droidmonkey** [comment]
The only way to do this is with CSV or directly reading the cahced password store from the browser. We are not going to implement the second option, I don't even think that is feasible anymore. CSV is the only way.
