### ISSUE TITLE
Drag and Drop folder or Entry from another window or multi folder selection from single instance

### ISSUE THREAD

**Issue by zackmark29** [keepassxreboot/keepassxc#6873]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )

Is it possible to add drag and drop from another window? 
Because I have old database and I want to organize them and put them in new database. 

Although I could just import the old database to my latest database or window. I can drag and drop them from old to new database but it can only select single folder. It will be nice if you can add multi folder selection :) 

Thank you so much.

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )

**Comment by droidmonkey** [comment]
Drag and drop between tabs is already possible. Hover over the destination tab to select that database. Multi select won't happen for various reasons. We have another issue requesting a context menu item to copy/ move items between open databases. Your best bet it to use the merge feature.
