### ISSUE TITLE
Use of swung dash / Tilde "~" in password-fields is only possible when the password is visible

### ISSUE THREAD

**Issue by moe5k** [keepassxreboot/keepassxc#6875]
## Overview
Use of swung dash / Tilde "~" in password-fields is only possible when the password is visible.
It simple does not appear.

## Steps to Reproduce
Just try to type a "~" in the any password field while the password is invisible.
May be it is only an issue in MacOS because of the Shortcut (Option + n) to create that sign.

## Expected Behavior
normal use of the sign "~"

## Actual Behavior
The sign does not appear while the password is hidden.

## Context
no extra infos need

[KeePassXC - Version 2.6.6
Revision: 386b79a

Qt 5.15.2
Diagnosemodus ist deaktiviert.

Betriebssystem: macOS 11.2
CPU-Architektur: x86_64
Kernel: darwin 20.3.0

Aktivierte Erweiterungen:
- Auto-Type
- Browser-Integration
- SSH-Agent
- KeeShare (bestätigtes und unbestätigtes Teilen)
- YubiKey
- TouchID

Kryptographische Bibliotheken:
- libgcrypt 1.9.3

**Comment by droidmonkey** [comment]
This is a Qt bug that has been reported to them already.
