### ISSUE TITLE
Add instruction on how to verify appimage (feature request)

### ISSUE THREAD

**Issue by Nurmagoz** [keepassxreboot/keepassxc#6877]
https://keepassxc.org/download/

appimage has gpg and sha256 but no instruction on how to verify it.

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )

This will ease the verification on new users/comers.

**Comment by droidmonkey** [comment]
Linked at the bottom of the download page: https://keepassxc.org/verifying-signatures/
