### ISSUE TITLE
EXPORT : include attachement/joined files and advanced attribute data too

### ISSUE THREAD

**Issue by mmtsuchi** [keepassxreboot/keepassxc#6878]
## Summary
**Actually (version 2.6.6), export database function only exports primary data** ("Group","Title","Username","Password","URL","Notes","TOTP","Icon","Last Modified","Created")
But it would be nice if it **includes attachment/joined files and advanced attribute data too**

## Context
Lossless  Export/Import database

Regards

**Comment by droidmonkey** [comment]
That is not the purpose of export. You cannot include attachments in a csv file. Advanced attributes are exported in html, exporting them in csv is already a requested feature. However we likely won't support reimport of them.
