### ISSUE TITLE
Load previously uses databases - doesn't work anymore

### ISSUE THREAD

**Issue by mathew-cook** [keepassxreboot/keepassxc#6879]
Hi,
the setting "Load previously uses databases" doesn't work anymore.
The database is not loaded, although there is only one database.
Before that worked, the database log in mask was call up immediately.

Please take a look at the screenshots.
Many thanks!

![Screenshot_1](https://user-images.githubusercontent.com/67975307/131226893-d96c5bfd-2c36-4d38-a743-af8ca5bd2df7.png)
![Screenshot_2](https://user-images.githubusercontent.com/67975307/131226894-bec7f296-620d-479a-9718-22ce2f82d9c3.png)

------------------------
KeePassXC-2.6.6-Win64-portable.zip
Operating System: Windows 10
Windowing System: X11/Wayland

**Comment by droidmonkey** [comment]
It does work, make sure the database is actually in the same location and accessible. Also make sure the database is actually "loaded" when closing the application. If you see the welcome screen when closing then it will NOT load a database.
