### ISSUE TITLE
End-User License Agreement contains license sample with sample names

### ISSUE THREAD

**Issue by luciash** [keepassxreboot/keepassxc#6880]
LOL, that confirms nobody is reading the license agreements:
![image](https://user-images.githubusercontent.com/4555037/131307088-adf307c4-8849-41a8-a5cf-7322c6e3c369.png)

**Comment by phoerious** [comment]
That's an addendum to the GPLv2 and shows an example of how you could add a proper copyright notice to your own program.

"How to Apply These Terms to Your New Programs"

**Comment by luciash** [comment]
I understand, but I don't see any reason why to include that addendum - it's confusing at least when you scroll down and read that. But as you wish. 😉
