### ISSUE TITLE
Auto-Type modifier keys are ignored

### ISSUE THREAD

**Issue by relikd** [keepassxreboot/keepassxc#6881]
## Overview

There seems to be a problem performing a Shift-Tab key combo.
According to the docs at [keepassxc.org][1] (which has a references to [keepass.info][2] "Special Keys"), the key code should be one of:

key|code
----|---
Shift | +
Ctrl | ^
Alt | %

Which, if I understand it correctly, implies that `+{TAB}{USERNAME}` should modify the tab key. Namely performing a Shift-Tab to select the previous (HTML) form field.

[1]: https://keepassxc.org/docs/KeePassXC_UserGuide.html#_configure_auto_type_sequences
[2]: https://keepass.info/help/base/autotype.html#autoseq

## Steps to Reproduce
1. create a new key entry
2. insert a custom auto-type value: `+{TAB}{USERNAME}` 
3. test it on any form field (put the cursor in the second field)

## Expected Behavior
According to the documentation the modifier flag should perform a Shift-Tab

## Actual Behavior
The shift is ignored and instead a plus sign (`+`) is inserted in the current field.

## Context
KeePassXC - Version 2.6.4 and 2.6.6 tested
Revision: 386b79a
Operating System: macOS 10.15

**Comment by droidmonkey** [comment]
Implemented in develop branch
