### ISSUE TITLE
Global Hot Key Alt-Ctrl-Ins works on Windows but does not work on Debian

### ISSUE THREAD

**Issue by ceving** [keepassxreboot/keepassxc#6882]
## Overview
On Windows I use the global hot-key `Alt-Ctrl-Ins`. This works fine. But on Debian 11 this does not work, although other keys like `Alt-Ctrl-#` do work on Debian.

## Steps to Reproduce
1. Set global hot key to Alt-Ctrl-Ins
2. Do auto-type in Firefox 91.0.2

## Expected Behavior
Auto-type should happen.

## Actual Behavior
Nothing happens.

## Context
Debian 11
X.Org X Server 1.20.11
Xinput xim
Fluxbox 1.3.5
Firefox 81.0.2

KeePassXC - Version 2.6.2
Revision: e9b9582

Qt 5.15.2
Debugging mode is disabled.

Operating system: Debian GNU/Linux 11 (bullseye)
CPU architecture: x86_64
Kernel: linux 4.19.0-17-amd64

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (only unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.8

**Comment by droidmonkey** [comment]
Unfortunately it is not possible then. It could be mapped to anther global shortcut or reserved by the operating system.

**Comment by ceving** [comment]
What a waste of time to collect all information for the bug report.

**Comment by droidmonkey** [comment]
Think of the time we spend even attempting to replicate your environment to even maybe try to reproduce the issue....
