### ISSUE TITLE
TOTP pop-up windows have unusable "?" button in header

### ISSUE THREAD

**Issue by selivan** [keepassxreboot/keepassxc#6884]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

TOTP pop-up windows("Show TOTP", "Show QR Code", "Set up TOTP")  have  unusable "?" button in header. It changes mouse cursor to 🚫 sign. It does not show any help tips when you hover or clock on any part of window.

I guess it should not be there at all, some default artifact from GUI design software.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Open context menu on an entry without TOTP
2. Select TOTP -> "Set up TOTP"
3. Click "?" button in header

or

1. Open context menu on an entry with TOTP
2. Select TOTP -> "Show QR Code" or TOTP -> "Set up TOTP"
3. Click "?" button in header

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

It should show some help on hover or click on window elements.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

It does nothing except changing cursor to 🚫 sign until next mouse click.

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.6.6
Revision: 9c108b9

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 10
Desktop Env: -
Windowing System: -

**Comment by tunbridgep** [comment]
![image](https://user-images.githubusercontent.com/31608726/132078837-a9d0b21c-3ff3-4a68-8388-223af106e253.png)

Interestingly, as someone using a Tiling WM that doesn't show window borders, I have the opposite problem in that I can't get help anywhere else since no window has a help button.
