### ISSUE TITLE
Automatically export files from the Database.

### ISSUE THREAD

**Issue by zandercodes** [keepassxreboot/keepassxc#6885]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
Automatically export files from the database and delete the exported file when the database is closed.

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )
For example, I want to decrypt a Veracrypt container with a key file, but the key file is in the KeePassXC database. Therefore, there should be a way to export files automatically when the database is opened.

Another example is, in the database there is a license file for a program that should not be used unprotected. There again it makes sense to be able to export the file automatically from the database and delete it after closing the database.

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
I want to automatically export files stored in the KeePassXC database to a specific folder to use these files in other programs.
After closing the program, the file in the folder should be deleted.
Unfortunately I have not found a plugin where this is possible.

**Comment by droidmonkey** [comment]
At first blush this seems dangerous and we likely will not implement it.

**Comment by phoerious** [comment]
Not going to implement that. Use the CLI if you want to extract stuff from your database.

**Comment by zandercodes** [comment]
Okay thanks

**Comment by droidmonkey** [comment]
Recommend ditching the key file for your Luks and use a very strong/long password instead. Then you can just Auto-Type that password directly from keepassxc. There is no real benefit to a key file over a long, complex password.
