### ISSUE TITLE
[Browser Protocol] Request to delete entry in database

### ISSUE THREAD

**Issue by purejava** [keepassxreboot/keepassxc#6887]
## Summary
Whereas third party applications are allowed to access and change a KeePassXC database via KeePassXCs built-in proxy, the protocol does not provide a request to **delete** entries in the database.

Deleting an entry could be secured the same way adding a new group is protected: bring KeePassXC to the foreground and show a pop-up, that asks to confirm deleting the entry.

**Comment by varjolintu** [comment]
This will only work when using an entry UUID.

**Comment by purejava** [comment]
Sounds perfect to me.
