### ISSUE TITLE
Dynamically set expiry dates

### ISSUE THREAD

**Issue by tunbridgep** [keepassxreboot/keepassxc#6890]
## Summary
I generally find that I forget to set expiry dates for my passwords when adding them, and when I do it's tedious because I have to always set a date every time I reset it. Setting an expiry for anything outside the options provided by the dropdown is annoying as I have to play with a date picker and do maths every time I change the password. I feel that this is actively disincentivising me from using the password expiry feature.

I believe that, by making this feature easier to use (even automatic), we can encourage more usage of the feature, especially among new users, which I feel will encourage people to change their passwords more often.

## Implementation
I propose something like this:

- The "Expires" checkbox is replaced with a dropdown with 3 options: `Never Expires`, `Set Expiry Date` and `Relative Expiry Date`. When on `Relative Expiry`, the expiry date input box changes to a relative date input
- Every time the password is changed, upon closing/saving the entry, the expiry date will be automatically updated to the current date + the relative date.
- Leaving the relative date field blank will inherit the relative date from the parent (or a global database setting if it has no parents or all of its parents are set to inherit)
- Changing the setting won't remove the last set expiry date, but it won't set it anymore when saving.

## Examples
I have an entry for my banking. I want the password to expire every month as it's a critical password. In order to help me to remember to reset it, I turn on relative expiry. Every time I update the password field, upon saving the entry the expiry is automatically set to 1 month in the future.

I have a group of entries for "Work passwords". My employer has an IT policy that forcibly sets all passwords to expire every month. I set my passwords to expire on the 26th of each month, which will set it to expire in KeepassXC 2 days before I am locked out.

## Extra Ideas
I think this would work well with some way of showing notifications of password expiry (such as a red banner at the top of the KeepassXC window) for entries where expiry is deemed "important", such as systems where we will be locked out on the expiry date.

## Additional Information
I have been meaning to explore Qt anyway, so if this idea is considered and the discussion on this ticket is going in a positive direction, I might try tackling it as a first issue, as long as it's not too complicated and as long as the main developers are okay with me doing that.

**Comment by droidmonkey** [comment]
#6456, add your additional ideas to that pull request so it can be incorporated
