### ISSUE TITLE
Checkbox "Update native messaging manifest files at startup" does not work

### ISSUE THREAD

**Issue by QuantumQuill** [keepassxreboot/keepassxc#6891]
Steps to reproduce:

1. Settings >> Browser Integration >> Advanced >> deactivate checkbox "Update native messaging manifest files at startup"
2. Close KeePassXC
2. change chrome-extension ID in file `org.keepassxc.keepassxc_browser.json` in the folder `/Users/user/Library/Application Support/Chromium/NativeMessagingHosts`, save the file and close the text editor
3.  Open KeePassXC
4. check the json file: you will see the file was reset to the old chrome-extension IDs 

KeePassXC v2.6.6

Alternatively I tried to use the function "Use a custom browser configuration location" in a custom folder. The result was the same. The file is getting reset.

**Comment by droidmonkey** [comment]
@varjolintu still broken?

**Comment by varjolintu** [comment]
@droidmonkey Cannot reproduce.
