### ISSUE TITLE
Browser Integration - "best-matching credentials": increased priority for matching parent URLs

### ISSUE THREAD

**Issue by m5w6** [keepassxreboot/keepassxc#6892]
## Summary
Please give URLs in the browser integration a new priority between "exact match" and "match without path" when the path of the password entry is a parent directory of the site/form URL.

## Examples
Following patch seems to solve my problem, but maybe you have a better idea:

```
diff -urpN a/src/browser/BrowserService.cpp b/src/browser/BrowserService.cpp
--- a/src/browser/BrowserService.cpp	2021-06-12 04:13:52.000000000 +0200
+++ b/src/browser/BrowserService.cpp	2021-09-04 19:15:10.205571320 +0200
@@ -956,10 +956,10 @@ int BrowserService::sortPriority(const Q
 
         // Match without path (ie, FQDN match), form url prioritizes lower than site url
         if (url.host() == siteUrl.host()) {
-            return 80;
+            return url.isParentOf(siteUrl) ? 85 : 80;
         }
         if (url.host() == formUrl.host()) {
-            return 70;
+            return url.isParentOf(formUrl) ? 75 : 70;
         }
 
         // Site/form url ends with given url (subdomain mismatch)
```

## Context
I have a website with lots of separate applications in different subdirectories:

* https://www.example.net/a/
* https://www.example.net/b/
* https://www.example.net/c/
* …
* https://www.example.net/special/
* https://www.example.net/anotherSpecial/

Most of the applications (`a`, `b`, `c`, …) can be used with the same credentials with the exception of a few applications that each need different credentials (here: `special` and `anotherSpecial`).

Currently I have these entries:
1. `sharedUser` with url https://www.example.net/
2. `specialUserA` with url https://www.example.net/special/
3. `specialUserB` with url https://www.example.net/anotherSpecial/

Listing each site for `sharedUser` would be too much effort – the list changes often and would be very long.

With "Return only best-matching credentials" I already see only `specialUserA` in https://www.example.net/special/ and `specialUserB` in https://www.example.net/anotherSpecial/ – that's fine. But when going to https://www.example.net/a/ the browser offers all three credentials.

It would be helpful if a matching parent directory (`/` vs `/a/`) is a "better match" than a host-only match with completely different paths (`/special/` vs `/a/`).

An even better but probably more complex solution would also compare the number of matching parents so that for the site/form url https://www.example.net/a/b/c/d/e/ the entry with url https://www.example.net/a/b/c/ is a "better match" than an entry with url https://www.example.net/a/. :wink: But the simple solution would currently be sufficient for me. :grin:

**Comment by droidmonkey** [comment]
This is a very specific use case and situation. Since your proposed change doesn't affect anything else this is acceptable to me. Anything else would likely break other workflow. Can you submit a pr with your patch?
