### ISSUE TITLE
Add ability to sort groups in alphabetical order

### ISSUE THREAD

**Issue by fourzerofour** [keepassxreboot/keepassxc#69]
Can we have a simple function that let you sort groups in alphabetical order?

**Comment by droidmonkey** [comment]
Do you mind showing us how you are currently using groups? This would only seem useful if you had many dozens of groups, which is unlikely to the average user.

You can already drag/drop groups into a particular order. Do you envision this being an option in the right click context menu? (ie "Sort Groups A-Z")

Also, please reformat your issue into the template format that we provide, thank you.

**Comment by phoerious** [comment]
Closing due to lack of feedback.

**Comment by javenschuetz** [comment]
an example use case: the data set was imported from another password manager and during that process many groups were made. The group breakdown is alright, so you want to keep it but since its not sortable its hard to find amazon.ca vs amazon.com vs aws.amazon.com

<img width="243" alt="screen shot 2017-11-19 at 19 43 28" src="https://user-images.githubusercontent.com/25443990/32999899-03424872-cd62-11e7-8f85-4d7f7fdcf9d6.png">

**Comment by droidmonkey** [comment]
CTRL+F -> Type in "amazon"

**Comment by AlainBenbassat** [comment]
+1 for the possibility to sort (sub)groups. Our use case: we have a group "Customers" that contains subgroups for each customer. Would be nice if that list was in alphabetical order. Thank you for taking this feature in consideration.

**Comment by chuinul** [comment]
I might have some time to work on this. What would be the specifications?

A `Sort by` option when right-clicking on a group which have subgroups seems sensible to me. We could offer several sorting options, as Keepass2Android for example:
- Keep default order (from the XML, I guess)
- Sort by name
- Sort by modification date
- Sort by creation date

Ideally, users should be able to choose different sorting order for different subgroups. Those preferences should be saved in the settings. I don't know how this can be efficiently achieved if the sort order can be set independently for each subgroup but this is what Keepass2Android does.

At last, I suppose sorting should not alter the XML, except when drag'n'dropping from the default order.

@droidmonkey what would you like me to implement?

**Comment by droidmonkey** [comment]
I say keep it simple, right click -> sort -> A-Z / Z-A

**Comment by AlainBenbassat** [comment]
right-click A-Z / Z-A is perfect!

**Comment by liamoreilly** [comment]
Does the Tree GUI Component/Widget not already have functionality to display children in sorted order?

**Comment by cjohansson** [comment]
I look forward to this feature as well, in one of my databases I have 50+ groups and it would be nice to have them sorted automatically

**Comment by brendoncrawford** [comment]
I am excited to hopefully see this happen.  I have a couple hundred groups, so it is becoming difficult to find them.  Thanks for all your work on this.

**Comment by droidmonkey** [comment]
@vosgus you are welcome to work on it. Would love to see your contribution!

**Comment by vosgus** [comment]
@droidmonkey I've done some work on this and currently it is possible to sort the groups by right clicking and selecting "Sort groups A-Z" (and Z-A). Right now it seems to be sorting the whole tree at once, including subgroups. Do you think it should be possible to sort individual groups and their subgroups or is it enough that the whole tree gets sorted at once? 

I also noticed that if you enable the header you get a small arrow that is clickable that will also sort the tree. Would it makes sense to enable the header just to show that arrow or should it be kept hidden?

**Comment by droidmonkey** [comment]
That's an option, perhaps call the column "Group". If you provide screenshots of it, we can discuss.

As for sorting, I would expect it to work such that if I right click a subgroup it only sorts below that subgroup. Right clicking the root folder sorts everything. This would not be possible with the header sort method

**Comment by vosgus** [comment]
Ok I see now how the right click sort should be implemented. So now clicking the root and using the header to sort would work the same way? I can provide some screenshots after I get the right click sort working correctly.

**Comment by ba32107** [comment]
Hello,

Is @vosgus still working on this? If not, I'd be happy to take a look into it.

Thanks
Balazs

**Comment by droidmonkey** [comment]
There is a bounty attached!

**Comment by ba32107** [comment]
I have almost completed this feature, sorting works A-Z / Z-A for groups. Subgroups are individually sorted.

There is one caveat though, the sorting is not persistent, meaning if you add a new entry, it won't be automatically sorted. It's a one-off action. Hope this is fine!

I am still working on tests, and will submit a PR in the next few days. Hopefully this feature can make 2.5.0!
