### ISSUE TITLE
KeePassXC closes database when Syncthing changes it

### ISSUE THREAD

**Issue by gianmarcogg03** [keepassxreboot/keepassxc#6900]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
I sync my KeePass database file with my devices via Syncthing and KeePassXC closes the database when changes are synced, so when I want to autocomplete something on my browser I need to open KeePassXC, which opens the main screen, choose the database, unlock it again and most times I also need to copy and paste the credentials manually because the browser plugin won't autocomplete them. 

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Have your database synced and get a modification
2. Try autocompleting something in the browser

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Should show the credentials of the current website.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Doesn't do anything and when you open KeePassXC it doesn't show the password screen right away.

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.6.6
Revision: 9c108b9

[NOTE]: # ( Pick choices based on your environment )
Operating System: Arch Linux
Desktop Env: KDE Plasma 5.22.4
Windowing System: X11

**Comment by droidmonkey** [comment]
> KeePassXC closes the database when changes are synced

There is no function that would do this in the code. The database just closes? Keepassxc closes?

**Comment by gianmarcogg03** [comment]
The database closes, not KeePassXC.

Instead of getting this...
![2021-09-06_19-17](https://user-images.githubusercontent.com/28053717/132248357-d59130d3-a501-4f5b-a1be-80688ce35d2e.png)
I get this...
![2021-09-06_19-16](https://user-images.githubusercontent.com/28053717/132248382-8bd26e0d-5195-4383-9c6e-c889c3e2df19.png)

**Comment by droidmonkey** [comment]
There is no way that can happen from a file sync operation. Worst case the database would lock. Please describe the sequence of events exactly. Is keepassxc open the entire time?

**Comment by gianmarcogg03** [comment]
Yes, it's always open.

**Comment by gxwum7** [comment]
I use Arch + KDE too and when I tried to reproduce the problem, it worked as expected, keepassxc updated the database automatically. You probably have a problem unrelated to keepassxc or the reason you specified is not the problem. By the way for your browser auto filling problem use an addon like [this](https://addons.mozilla.org/en-US/firefox/addon/keepass-helper-url-in-title/) and enable "Use entry URL to match windows for global Auto-Type" in the auto type settings, so that the keepassxc program could auto fill directly instead of using a plugin.
