### ISSUE TITLE
[Unconfirmed] Keyboard is disabled after typing into search bar

### ISSUE THREAD

**Issue by iceq2** [keepassxreboot/keepassxc#6902]
Okay, this is very strange: 
1- During normal use of WIndows 10 (up-to-date), the keyboard keys suddenly stop working.
This happens everywhere, in ALL browsers, all Windows applications, even in Windows search bar, file explorer, and so on.
It started to happen since about a month ago.

2- Other keys like Enter, Tab, Alt, NumLock, Scroll-Lock, etc, continue working normally. Letters and numbers do NOT.
3- That said, strangely, they still work in certain fillable fields, like a website log-in field.
4- Tried different keyboards ; same issue ; re-installed drivers ; same issue. 
5- After some time, it became clear that the problem is triggered when I start typing something in KeepassXC's search bar.
Meaning: I am in a browser window and I can type normally. The moment I start typing in KXC's search bar, the keys are somehow locked and they stop responding ! 
6- I can't also seem to find a working solution to this. But from some experiments, it seems that going to any fillable field in the browser (a log-in field, for example), and starting to type there, then the keys start responding again in the other windows / applications. 

Again, both Windows 10 and KXC are up to date. 

Windows 10 Pro 10.0.19043

**Comment by droidmonkey** [comment]
This is definitely not our bug. In other words, you are the only person ever to have this happen.

**Comment by droidmonkey** [comment]
https://answers.microsoft.com/en-us/windows/forum/all/keyboard-stop-working-only-letter-and-number/0d828147-7f39-4d58-9589-36fd3a63fdc2

**Comment by iceq2** [comment]
> https://answers.microsoft.com/en-us/windows/forum/all/keyboard-stop-working-only-letter-and-number/0d828147-7f39-4d58-9589-36fd3a63fdc2

Thanks mate.
I already saw that topic and many others. I did restart the PC several times, nothing helped.
It's extremely weird indeed. Seems that I have some combination of apps installed that cause this issue, but just not sure how I can figure it out.

**Comment by droidmonkey** [comment]
Remove keepassxc and see if it persists. You can run our portable version or just use original keepass to confirm or deny we are involved. Did you even update our change keepassxc in the month prior that this started happening?
