### ISSUE TITLE
Inherited background color for "Unlock Database" dialog can have very bad contrast

### ISSUE THREAD

**Issue by klorax** [keepassxreboot/keepassxc#6905]
## Overview
The inner background color in the "Unlock Database" dialog inherits its color from the window background color (at least in KDE Plasma on GNU+Linux with the default KDE QT "widget engine" Breeze). This seems to work fine with light themes and themes that are not "too" dark.

The inherited inner background color is lighter than the window background color, however there seem to be a point were it becomes much lighter, so much so that it can be difficult to read the text due to bad contrast.

## Steps to Reproduce
For example, with the window background color `#001e00` the inner background color is `#004100`:

![keepass_good](https://user-images.githubusercontent.com/31596164/132547794-fc6d4332-130d-4484-9be5-c2c2a739f02e.png)

However, when darkening the background color with just one "step" to `#001d00` the inner background color becomes **_much_** lighter `#00cc00`:

![keepass_bad](https://user-images.githubusercontent.com/31596164/132548286-f0020fc0-9f4a-44f1-ac81-0a1331fbe53c.png)

The background color `#001f00` causes the inner background color to be `#004200`. So one would expect the color at `#001d00` to be `#004000`.

## Expected Behavior
The background color `#001d00` causes the inner background color to be `#004000`.

## Actual Behavior
The background color `#001d00` causes the inner background color to be `#00cc00`.

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.6
Revision: 9c108b9

Qt 5.15.2
Debugging mode is disabled.

Operating system: Manjaro Linux
CPU architecture: x86_64
Kernel: linux 5.14.0-0-MANJARO

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- libgcrypt 1.9.4-unknown

Operating System: Linux
Desktop Env: KDE
Windowing System: X11

**Comment by phoerious** [comment]
Please use one of our provided themes. We cannot cater for every custom colour scheme out there.

**Comment by klorax** [comment]
Of course that is a solution, but you do realize there is a break point for dark themes that one "step" darker makes or breaks the all those themes?

This is not one specific theme that breaks, but a whole set of themes that seem to work perfectly in most other places (100 % of what I have come across). Seems like a _**bug in the inheritance**_ where all of a sudden it becomes lighter instead of darker.

For example, any black theme would have the extremely bright `#aeaeae` inner background color:
![keepass_black](https://user-images.githubusercontent.com/31596164/132552648-74d876a5-8c77-4a70-a3cf-6237eb07a5ab.png)

**Comment by droidmonkey** [comment]
Please report this bug to Qt. The classic theme and color modifications are handled entirely by Qt code. https://bugreports.qt.io

**Comment by klorax** [comment]
After browsing the code a bit (not very familiar with C++ or Qt) it might have something to do with:
[`adjustLightness`](https://github.com/keepassxreboot/keepassxc/blob/2423bede60914740854ceb37034464ff4ff09f89/src/gui/styles/base/BaseStyle.cpp#L177) which uses [`Phantom`](https://github.com/keepassxreboot/keepassxc/blob/e6798112be41e156a70e659747aea08eb089ad3e/src/gui/styles/base/phantomcolor.cpp) which seems to be a port of [`hsluv-c`](https://github.com/hsluv/hsluv-c/blob/59539e04a6fa648935cbe57c2104041f23136c4a/src/hsluv.c).

**_Edit:_** 
> Please report this bug to Qt. The classic theme and color modifications are handled entirely by Qt code. https://bugreports.qt.io

Ok, if this is Qt and not `Phantom` which I speculated about above, then could you please direct me to the code to help the reporting? Thanks!

**Comment by droidmonkey** [comment]
There is no way you are overriding one of our themes (Dark and Light) unless you are hacking the platform code. So you must be using the classic theme which is NOT Phantom and is pure Qt code.

**Comment by klorax** [comment]
Yes, indeed, I am using "classic" theme. Ok, then it is Qt. Any idea where this call to the Qt code could be?

**Comment by droidmonkey** [comment]
Probably in the QCommonStyle class, that's why a bug report should be filed with them if you want this addressed.

**Comment by klorax** [comment]
Thanks for taking the time to track this down. I have [reported this at the Qt bug tracker](https://bugreports.qt.io/browse/QTBUG-96354).
