### ISSUE TITLE
On Ubuntu 21.04, keepassxc, freshly installed from snap, version 2.6.6, will not open due to xapp-gtk3-module error

### ISSUE THREAD

**Issue by digitalrhizome** [keepassxreboot/keepassxc#6906]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
keepassxc
Gtk-Message: 21:23:45.912: Failed to load module "xapp-gtk3-module"

(keepassxc:273389): dbind-WARNING **: 21:23:45.918: Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-DohSXdj51w: No such file or directory
Gtk-Message: 21:23:45.936: Failed to load module "colorreload-gtk-module"
Gtk-Message: 21:23:45.936: Failed to load module "window-decorations-gtk-module"
Qt: Session management error: Could not open network socket
Fontconfig warning: FcPattern object weight does not accept value [40 200)
Segmentation fault

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. On Ubuntu 21.04, install snap version of keepassxc.
2. See error when you attempt to load from terminal. Any launch from krunner fails silently. 
3. 

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Keepassxc opens

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Keepassxc fails to open, segmentation fault

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.6.6
Revision: 1522

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux (Ubuntu Studio 21.04)
Desktop Env: Plasma5
Windowing System: X11/Wayland

**Comment by digitalrhizome** [comment]
I removed the snap from my system, after several attempts to get it running. 
I installed the 2.6.2 from Ubuntu repos, then I added the current version repo
at https://launchpad.net/~phoerious/+archive/ubuntu/keepassxc, 
and this installed 2.6.6 properly. 

The snap is broken on my system. 
I have several other Ubuntu 21.04 variants, I will try on a VM with stock 21.04 and see what happens tomorrow.

**Comment by phoerious** [comment]
Sorry, but this is not something we can fix. There is something fundamentally broken on your system. Please try our PPA instead: https://launchpad.net/~phoerious/+archive/ubuntu/keepassxc

**Comment by droidmonkey** [comment]
https://github.com/keepassxreboot/keepassxc/issues/5150#issuecomment-723481758

**Comment by digitalrhizome** [comment]
:phoerious: _ just reproduced this on a fresh 21.04 Ubuntu Studio install._
Your assertion, "there is something fundamentally broken on your system," is categorically false. One of the most annoying things about reporting issues, is such comments. I've read the #5150 segmentation fault issue referred to by droidmonkey. There is logical reasons why this occurs with the snap, and I intend to find out, even if "phoerious" is not interested. I will post my results here and on the Techpraxis SPC bug reporting website in the next few hours. KeepassXC is a vital part of many people's infrastructure worldwide, and some attention to figuring out why 2.6.6 would fail, when KeepassXC snap worked flawlessly in the past year, is worth doing to eliminate the "hands shrugged, I dunno" -- knowledge is better than ignorance.

**Comment by droidmonkey** [comment]
The fact that this is fixed by doing something completely unrelated to snaps and keepassxc by definition means it is not a keepassxc problem. Here is a direct link to the solution:

https://github.com/dbeaver/dbeaver/issues/9307#issuecomment-702426109

**Comment by phoerious** [comment]
We do not use nor control "xapp-gtk3-module", so by definition, this is not a KeePassXC problem. So if the problem is reproducible on other systems, it's most likely an Ubuntu bug.

**Comment by droidmonkey** [comment]
You can read all about why fontconfig cache is broken for all snaps here: https://forum.snapcraft.io/t/snapped-app-not-loading-fonts-on-fedora-and-arch/12484/106

This has nothing to do with those gtk errors
