### ISSUE TITLE
LibreWolf Browser Integration

### ISSUE THREAD

**Issue by CuriousApe2020** [keepassxreboot/keepassxc#6907]
I request for KeepassXC to integrate with LibreWolf a fork of Firefox, the Firefox Extension "works" but doesn't get recognized by KeepassXC. Currently the workaround on Linux is to link ~/.mozilla/native-messaging-hosts to ~/.librewolf/native-messaging-hosts.

**Comment by droidmonkey** [comment]
Use the custom browser configuration.

**Comment by Mayurifag** [comment]
**Update: skip my answer, use custom browser integration solution from below answers**

Thats kinda sad that this won't be fixed. I had my librewolf browser with keepassxc-browser not to be working on linux with keepassxc. 

It was spamming message "Key exchange was not successful." everywhere without any meaningful messages.

Only this issue helped me to fastfix it:

```sh
ln -s ~/.mozilla/native-messaging-hosts ~/.librewolf/native-messaging-hosts
```

Thats not a good solution, but I still want keepassxc developers or browser extension devs to fix it for librewolf users.

However, Librewolf and keepassxc browser on windows works fine.

**Comment by droidmonkey** [comment]
Use the custom browser option in the advanced settings...

**Comment by peepo5** [comment]
![image](https://user-images.githubusercontent.com/72892531/148112939-88aaa06a-5890-44e7-ae21-f7c497582dec.png)
where

**Comment by droidmonkey** [comment]
You need version 2.6.6, you are running an ancient version of keepassxc

**Comment by peepo5** [comment]
ubuntu repos trash like usual?

**Comment by droidmonkey** [comment]
https://keepassxc.org/download lots of options

**Comment by peepo5** [comment]
i think the outdated ubuntu version should be removed

**Comment by hockeymikey** [comment]
> Use the custom browser option in the advanced settings...

Not a solution if one wants to use multiple custom browsers.

**Comment by droidmonkey** [comment]
Use symlinks

**Comment by hockeymikey** [comment]
> Use symlinks

Or provide more options. It really isn't that difficult.

**Comment by droidmonkey** [comment]
I've sent your feedback to upper management for consideration.

**Comment by Diapolo10** [comment]
From the looks of it this shouldn't be a difficult fix, it's just an extra profile to the snap helper script.

I was actually setting up a new laptop yesterday and gave Librewolf a go, but went back to Firefox after finding out the browser plugin didn't work natively with it. Which is a shame.

I'd be down to fixing the problem myself if I'm given approval. Should take a couple hours at most.

**Comment by droidmonkey** [comment]
I'd consider it for the snap install script... with the caveat that we don't provide any guarantees for alt browsers.

**Comment by ghost** [comment]
This is creating a directory in `~/~/native-messaging-hosts` where the first tilde is substituted and the second one isn't.
Config Location: `~/.librewolf/native-messaging-hosts`

**Comment by iriki** [comment]
Why is everyone stating that it doesn't work? I've ditched Firefox and only use Librewolf, and only had to:

1) create empty directory `~/.librewolf/native-messaging-hosts`
2) Go to `Browser Integration`, `Advanced`and manually fill in the `Config Location` with the same folder you've created in step 1: `~/.librewolf/native-messaging-hosts`

I've also find out that, in order to "remove" the old firefox association, the easiest way for me was to move the keefile to another folder, and opening it again in KeePassXC.

**Comment by droidmonkey** [comment]
You shouldn't even have to do step 1!

**Comment by iriki** [comment]
I had to create that empty folder on **all** my Linux boxes or else it wouldn't work.

**Comment by droidmonkey** [comment]
Noted, that would be a bug then, we should create the folder path @varjolintu

**Comment by puzzlled** [comment]
I had this same problem, running Manjaro.  Tried enabling custom browser but no change until I created the empty folder
~/.librewolf/native-messaging-hosts
and then it worked right away.  I've been trying to get this set up on a few Manjaro machines as I'd like to migrate to it and this issue almost had me moving on to a different option.  Fortunately I found this page so now perhaps I can stick with it.
It really does seem to be a bug that shouldn't be too difficult to fix and it might be a good idea to accept Librewolf as a standard option instead of custom since people who use it are after the privacy & security it offers, and privacy is what keepassxc is all about.

**Comment by varjolintu** [comment]
Didn't we have a pull request for supporting this? It has just disappeared.

**Comment by float3** [comment]
[    // TODO: Custom browser is disabled on Windows](https://github.com/keepassxreboot/keepassxc/blob/12be175d583fbfac5a7b6b250a3bb5f792925285/src/browser/BrowserSettingsWidget.cpp#L61)

**Comment by katullo** [comment]
Why is this closed? Browser extension still doesn't work on LibreWolf.

**Comment by varjolintu** [comment]
@katullo11 You can use the Custom Browser feature to enable this.

**Comment by katullo11** [comment]
<img width="495" alt="immagine" src="https://user-images.githubusercontent.com/129339155/230609302-1d242919-eb2b-4f85-a6e7-5ee4337c71f0.png">
you mean this one?

**Comment by katullo11** [comment]
<img width="503" alt="Screenshot 2023-04-07 alle 14 33 19" src="https://user-images.githubusercontent.com/129339155/230609464-c3e879e6-2579-45b4-a19d-75b53a68dee1.png">
you mean this one?

**Comment by katullo** [comment]
I can't screenshot, but do you mean the one that sets the custom path? If yes, what should I do?

**Comment by varjolintu** [comment]
Enable the Custom Browser setting from Browser Integration's Advanced Tab. Keep the browser type as Firefox and add the path to following (depending on your OS of course):
`~/.librewolf/native-messaging-hosts`

**Comment by katullo** [comment]
Still doesn't work. I'm sorry but I'm not really that advanced, I'm on macOS and I have installed librewolf via Homebrew if that helps in any way.

**Comment by varjolintu** [comment]
The path for macOS is probably `~/Library/Application Support/Librewolf/NativeMessagingHosts` or similar. Check the correct Librewolf path under `~/Library/Application Support/`.

**Comment by katullo** [comment]
It worked! Thanks a lot!

**Comment by fliegentoeter** [comment]
Does not work for me unfortunalty...
Running Manjaro and was able to use custom browser settings and even choose ~/.librewolf/native-messaging-hosts
But The Addon in Librewolf is unable to connect...
Seems like i have to stay on Firefox for now.

**Comment by float3** [comment]
> Does not work for me unfortunalty...
> Running Manjaro and was able to use custom browser settings and even choose ~/.librewolf/native-messaging-hosts
> But The Addon in Librewolf is unable to connect...
> Seems like i have to stay on Firefox for now.

Did you also create that folder?

**Comment by fliegentoeter** [comment]
Its there, even a keepassxc file is in there...
![Bildschirmfoto vom 2023-04-12 19-15-13](https://user-images.githubusercontent.com/8972985/231533916-8bc18fe1-bf47-4195-b097-57593078d36a.png)

**Comment by fliegentoeter** [comment]
Its there, even a keepassxc file is in there...
![Bildschirmfoto vom 2023-04-12 19-15-13](https://user-images.githubusercontent.com/8972985/231533916-8bc18fe1-bf47-4195-b097-57593078d36a.png)

**Comment by Stoxis** [comment]
> Why is everyone stating that it doesn't work? I've ditched Firefox and only use Librewolf, and only had to:
> 
>     1. create empty directory `~/.librewolf/native-messaging-hosts`
> 
>     2. Go to `Browser Integration`, `Advanced`and manually fill in the `Config Location` with the same folder you've created in step 1: `~/.librewolf/native-messaging-hosts`
> 
> 
> I've also find out that, in order to "remove" the old firefox association, the easiest way for me was to move the keefile to another folder, and opening it again in KeePassXC.

This solution solved my issue with connecting KeePassXC to Librewolf.

**Comment by nikmax42** [comment]
> > Why is everyone stating that it doesn't work? I've ditched Firefox and only use Librewolf, and only had to:
> > ```
> > 1. create empty directory `~/.librewolf/native-messaging-hosts`
> > 
> > 2. Go to `Browser Integration`, `Advanced`and manually fill in the `Config Location` with the same folder you've created in step 1: `~/.librewolf/native-messaging-hosts`
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I've also find out that, in order to "remove" the old firefox association, the easiest way for me was to move the keefile to another folder, and opening it again in KeePassXC.
> 
> This solution solved my issue with connecting KeePassXC to Librewolf.

Still doesn't work for me. 
UPD. Maybe beacause keepassxc-proxy not running: `segmentation fault (core dumped)  keepassxc-proxy`
UPD2. It helps after system update and/or reboot

**Comment by Jaaannis** [comment]
my solution for this was, do not use flatpak...
I installed keepassxc with apt install... an everything works like described in post 
Greetings

> Why is everyone stating that it doesn't work? I've ditched Firefox and only use Librewolf, and only had to:
> 
>     1. create empty directory `~/.librewolf/native-messaging-hosts`
> 
>     2. Go to `Browser Integration`, `Advanced`and manually fill in the `Config Location` with the same folder you've created in step 1: `~/.librewolf/native-messaging-hosts`
> 
> 
> I've also find out that, in order to "remove" the old firefox association, the easiest way for me was to move the keefile to another folder, and opening it again in KeePassXC.

**Comment by fazer1** [comment]
What can I do, if I am on a windows machine? The keypass json on windows is only in this directory:
C:\Users\user\AppData\Local\KeePassXC
org.keepassxc.keepassxc_browser_firefox.json
org.keepassxc.keepassxc_browser_tor-browser.json

"~/.mozilla/native-messaging-hosts" does not exist

**Comment by varjolintu** [comment]
> What can I do, if I am on a windows machine? The keypass json on windows is only in this directory: C:\Users\user\AppData\Local\KeePassXC org.keepassxc.keepassxc_browser_firefox.json org.keepassxc.keepassxc_browser_tor-browser.json
> 
> "~/.mozilla/native-messaging-hosts" does not exist

Go to the LibreWolf's registry and add a path to that JSON file. You can take a look at how other browser configure it.

**Comment by odkr** [comment]
Just a note for those of us on macOS: The correct "config location" is `~/Library/Application Support/librewolf/NativeMessagingHosts`.

**Comment by vinovod** [comment]
> Just a note for those of us on macOS: The correct "config location" is `~/Library/Application Support/librewolf/NativeMessagingHosts`.

Thank you, it has just saved a lot of time :)

**Comment by sebadrude** [comment]
Hi,
this does not work any more, it seems.  I am on Linux Mint 22 Cinnamon.  I followed the instructions:
1. created ~/.librewolf/native-messaging-hosts/
2. added that path in Settings > Browser Integration > Advanced > Config Location  (Browser Type: Firefox)
3. moved my database to a different location 
4. rebooted
5. opened my keepassxc database

When clicking on the keepassxc-browser addon icon in LibreWolf, I still get "KeePassXC-Browser has encountered an error: Cannot connect to KeePassXC. Check that browser integration is enabled in KeePassXC settings. "
What am I missing?

**Comment by varjolintu** [comment]
@sebadrude Use the troubleshooting guide to check if the path is correct: https://github.com/keepassxreboot/keepassxc-browser/wiki/Troubleshooting-guide#find-the-native-messaging-configuration-path-with-strace

Also, how is Librewolf installed? Just a normal .deb?

**Comment by sebadrude** [comment]
Thanks, dear @varjolintu.  After I saw your message, I remember having seen that the FlatPack LibreWolf package that came with Linux Mint 22 can cause this kind of trouble.  I tried installing the original Debian distribution instead, and things worked.
Thanks also for pointing me at the helpful Wiki-page!  
Greetings from the tropics to the long days far up in the north!

**Comment by wandrey7** [comment]
> **Update: skip my answer, use custom browser integration solution from below answers**
> 
> Thats kinda sad that this won't be fixed. I had my librewolf browser with keepassxc-browser not to be working on linux with keepassxc.
> 
> It was spamming message "Key exchange was not successful." everywhere without any meaningful messages.
> 
> Only this issue helped me to fastfix it:
> 
> ln -s ~/.mozilla/native-messaging-hosts ~/.librewolf/native-messaging-hosts
> 
> Thats not a good solution, but I still want keepassxc developers or browser extension devs to fix it for librewolf users.
> 
> However, Librewolf and keepassxc browser on windows works fine.


Working perfectly, thank you

**Comment by jytou** [comment]
No need to link the directories, this works just fine:
```
mkdir -p ~/.librewolf/native-messaging-hosts
cp ~/.mozilla/native-messaging-hosts/org.keepassxc.keepassxc_browser.json ~/.librewolf/native-messaging-hosts
```
That file doesn't contain much - just the necessary information to link with keepassxc.

**Comment by pang-alfil** [comment]
Neither creating the symlink, nor copying the file, work in a fresh librewolf installation. Those approaches only work if you're moving from an existing firefox user.
I think a better solution, like creating the 

```
~/.librewolf/native-messaging-hosts/org.keepassxc.keepassxc_browser.json
```

is needed.

Meanwhile, these are the contents, for those who want to create manually:

```
{
    "allowed_extensions": [
        "keepassxc-browser@keepassxc.org"
    ],
    "description": "KeePassXC integration with native messaging support",
    "name": "org.keepassxc.keepassxc_browser",
    "path": "/usr/bin/keepassxc-proxy",
    "type": "stdio"
}
```

**Comment by varjolintu** [comment]
The best solution is to use the KeePassXC's own Custom Browser feature and use `~/.librewolf/native-messaging-hosts/` as the path.

**Comment by MorsMortium** [comment]
Could be another checkmark for LibreWolf added? There are a bunch of chromium based browsers there and even a Tor one. I think LibreWolf is popular enough to be there, and with the recent FireFox ToS there are many people migrating, for whom this option would be helpful.

**Comment by varjolintu** [comment]
> Could be another checkmark for LibreWolf added? There are a bunch of chromium based browsers there and even a Tor one. I think LibreWolf is popular enough to be there, and with the recent FireFox ToS there are many people migrating, for whom this option would be helpful.

LibreWolf is just one of the many forks, and we have the Custom Browser feature meant for those.

**Comment by Cybyst** [comment]
> No need to link the directories, this works just fine:
> 
> ```
> mkdir -p ~/.librewolf/native-messaging-hosts
> cp ~/.mozilla/native-messaging-hosts/org.keepassxc.keepassxc_browser.json ~/.librewolf/native-messaging-hosts
> ```
> 
> That file doesn't contain much - just the necessary information to link with keepassxc.

Bingo.

Thanks jytou.

This solved the problem for me.

With the bonus effect that, so far, this solution seems to allow simultaneous KeePassXC integration with both LibreWolf *and* Vivaldi.

Perfect.

**Comment by c2qd** [comment]
In my environment, I was able to connect KeePassXC by extracting the `librewolf-136.0.2-1-linux-x86_64-package.tar.xz` downloaded from https://codeberg.org/librewolf/bsys6/releases and running the librewolf inside.

**Comment by jeromedje49** [comment]
Hi !
I installed Zorin OS a few days ago, I'm a newbie in Linux world :)

I installed LibreWolf, keepassXC and keepassXC-brower.
Then I followed the different steps (creating .librewolf/native-messaging-hosts, and set Custom Browser in keepassXC to ~/.librewolf/native-messaging-hosts)

But the keepassxc-browser extension still mentions the error "KeePassXC-Browser has encountered an error: Cannot connect to KeePassXC. Check that browser integration is enabled in KeePassXC settings."

Being newbie, I don't know what I can do further.

Thanks for your help :)

**Comment by varjolintu** [comment]
> Hi ! I installed Zorin OS a few days ago, I'm a newbie in Linux world :)
> 
> I installed LibreWolf, keepassXC and keepassXC-brower. Then I followed the different steps (creating .librewolf/native-messaging-hosts, and set Custom Browser in keepassXC to ~/.librewolf/native-messaging-hosts)
> 
> But the keepassxc-browser extension still mentions the error "KeePassXC-Browser has encountered an error: Cannot connect to KeePassXC. Check that browser integration is enabled in KeePassXC settings."
> 
> Being newbie, I don't know what I can do further.
> 
> Thanks for your help :)

Try your luck and enable the normal Firefox support in KeePassXC? If that doesn't work, try the same that has been suggested in the thread before to find the correct path:
https://github.com/keepassxreboot/keepassxc-browser/wiki/Troubleshooting-guide#find-the-native-messaging-configuration-path-with-strace

**Comment by jeromedje49** [comment]
Thanks for your help.
I used sudo strace -f -p $(pgrep firefox) 2>&1 | grep keepass
Then press Enter
Then open LibreWolf, clicked on "Restart" on the extension.
The thread mentions : "That should trigger the Native Messaging to open the script file. You should see a line similar to this:" but nothing happens :/

**Comment by varjolintu** [comment]
@jeromedje49 Read the rest of the guide text..

**Comment by jeromedje49** [comment]
As I said, I'm just a begginer and do not understand, for now, how installations of apps work.
After many searches, I finally found that I installed Librewolf through "Logiciels" ("Softwares" ?) manager, provided by ZorinOS.
And found that it was installed in Flatpak.
I removed Librewolf, and tried to install the Debian version.
But I encountered 403 errors through the terminal.

I didn't want to, but AI helped me : Debian Repository was obsolete...

If it can help : 

sudo rm -f \
/etc/apt/sources.list.d/librewolf.sources \
/etc/apt/keyrings/librewolf.gpg \
/etc/apt/preferences.d/librewolf.pref \
/etc/apt/sources.list.d/librewolf.list \
/etc/apt/trusted.gpg.d/librewolf.gpg

sudo apt update && sudo apt install extrepo -y

sudo apt --allow-releaseinfo-change update

sudo apt install librewolf -y

**Comment by varjolintu** [comment]
@jeromedje49  Flatpak browsers are not supported.

**Comment by jeromedje49** [comment]
Yes, that's what I read in the guide, but did not even know how Librewolf was installed ^^
When I saw this, I uninstalled the flatpak version and reinstalled Librewolf in Debian.
And now it works

**Comment by varjolintu** [comment]
> Yes, that's what I read in the guide, but did not even know how Librewolf was installed ^^ When I saw this, I uninstalled the flatpak version and reinstalled Librewolf in Debian. And now it works

Glad you found a solution! I missed that in your previous message. I thought there was still some issues.
