### ISSUE TITLE
Add an option for data exchange of groups and entries. 

### ISSUE THREAD

**Issue by clicky6** [keepassxreboot/keepassxc#6909]
Add an option for data exchange of entries and groups like it is present in Kee pass it helps in copying and pasting entries into the another database. This features helps when we are managing multiple databases and we have to copy and paste some entry then we don't have to create new entry and put in all things, we can directly copy and paste the entry or group in 2 clicks.

Also add an option to export single entries or groups this helps when we have to give someone else some entry or some entries or group or some groups so we don't have to create a whole new database for that.

![96](https://user-images.githubusercontent.com/89839714/132946832-a978f798-39bd-4d1a-b926-69c7a8a511a9.png)

![97](https://user-images.githubusercontent.com/89839714/132946835-e98364ab-7949-4312-abb7-7dba6aeb915d.png)

These options should be given it helps in managing many databases more easily.

**Comment by droidmonkey** [comment]
These are duplicate requests to others on the board. You can also easily drag and drop entries between groups and open databases.

**Comment by clicky6** [comment]
@droidmonkey But there isn't an option to export individual or some groups and entries?

**Comment by droidmonkey** [comment]
It's already a feature request
