### ISSUE TITLE
Detect Hardware Keys not working with yubikey 5 NFC

### ISSUE THREAD

**Issue by seyler84** [keepassxreboot/keepassxc#6910]
hello
I have a two YubiKeys 5 NFC (5.2.7) [OTP+FIDO+CCID]
My operation system is Ubuntu 21.04  and KeePassXC 2.6.6.
Details:
KeePassXC - Wersja 2.6.6
Rewizja: 9c108b9
Dystrybucja: Snap
Qt 5.9.5
Tryb debugowania jest wyłączony.
Operation system: Ubuntu Core 18
Arch processor: x86_64
kernel: linux 5.11.0-34-generic

Unfortunately my yubikey it isn't detect in my KeepassXC.
I configure yubikey for HMAC-SHA1 but not working.
My yubikey is detected in my operation system.
lsusb and "ykman list"  detected my yubikey too.
What else can i check?
Sorry, but my english it's not the best.

**Comment by droidmonkey** [comment]
Install the udev rules for yubikey. libyubikey-udev

**Comment by seyler84** [comment]
I have installed
```
root@Solaris:/home/gorzyp# apt-cache policy  libyubikey-udev
libyubikey-udev:
  Zainstalowana: 1.20.0-3
  Kandydująca:   1.20.0-3
  Tabela wersji:
 *** 1.20.0-3 500
        500 http://pl.archive.ubuntu.com/ubuntu hirsute/universe amd64 Packages
        500 http://pl.archive.ubuntu.com/ubuntu hirsute/universe i386 Packages
        100 /var/lib/dpkg/status

```
[](https://pasteboard.co/SPTpyR9g9gs0.png)

**Comment by droidmonkey** [comment]
Oh you are using the snap, you need to enable raw-usb permissions. https://keepassxc.org/docs/#faq-appsnap-yubikey

**Comment by seyler84** [comment]
It works. Thx :)
