### ISSUE TITLE
Auto database locking stopped work with slock or/and when lid is closed

### ISSUE THREAD

**Issue by asakura42** [keepassxreboot/keepassxc#6913]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

All was ok, but now automatic database locking when session is locked doesn't work. Locking database after minimizing window still works.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1.  Install Arch Linux
2. Install `slock`
3. Open database
4. Lock session

[NOTE]: # ( Paste debug info from Help → About here )
```
KeePassXC - Version 2.6.6
Revision: 9c108b9

Qt 5.15.2
Debugging mode is disabled.

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 5.13.13-arch1-1

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- libgcrypt 1.9.4-unknown
```

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: No, I use i3wm
Windowing System: X11

**Comment by phoerious** [comment]
This is a problem with your window manager. i3 doesn't send the proper DBus signals for that to work. We can't help you with that, unfortunately.
