### ISSUE TITLE
Auto Login

### ISSUE THREAD

**Issue by tonypachino** [keepassxreboot/keepassxc#6918]
## Summary
Why don't you make it to work like a lastpass, make an addon for browser and when i click on addon icon in browser i can type and search for a website and when i click on website name it automatically go to that website insert username and password and automatically login (press enter)
or when i search in the database in the app, when i click on website name, let it do the same as i explained above.

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
it makes my life easier.

**Comment by droidmonkey** [comment]
We quite literally have that already
