### ISSUE TITLE
Title is used to identify the window for Auto-Type which makes it hard to find the entry you are looking for.

### ISSUE THREAD

**Issue by anonymous133** [keepassxreboot/keepassxc#6919]
## Summary
Most of the time the Title is no longer usable to identify the service for which the entry is when you want to use Auto-Type.

## Examples

The title is used to identify the window for Auto-Type. But many sites have cryptic window names for the login windows so that often the title in the keepass database becomes nonsensical to identify the service behind it. Like on Interactivebrokers.co.uk I have to set the title to "Login — Mozilla Firefox".

Now I have to either put the name of the website in the URL or in the notes so that I can at least find it via the search.
![screenshot](https://user-images.githubusercontent.com/47555412/133619811-f37ae665-8ff2-4870-ae8c-529d685ac4c9.png)

## Context
If you put "Login — Mozilla Firefox" in the title you can't easily tell anymore from the list view for which service that entry is.

A good solution to me would be to have besides the Title field another field where you can put in the name of the window that the Auto-Type should look out for. Maybe with a tool that can detect the windows name when you click on it.

Or is what I do not best practice?

Thank you for your work!

**Comment by droidmonkey** [comment]
Read the docs please...

https://keepassxc.org/docs/KeePassXC_UserGuide.html#_auto_type

**Comment by anonymous133** [comment]
I just read the auto type doc but I seam to encounter a bug.. I deactivated the checkbox for Use entry title like this:

![screenshot](https://user-images.githubusercontent.com/47555412/133658849-a32f5de7-6716-44fd-8377-ceaa582c7dd3.png)

But even after a restart the when I press the Meta+. key it presents the error:

![screenshot](https://user-images.githubusercontent.com/47555412/133658981-b9fbb47d-97fb-4d2f-a3b2-0cf9607e9259.png)

So as if the global Auto-Type shortcut ignores the checkbox setting. I've restarted Keypass but still this behavior persists. 

When I use "Perform Auto-Type" from the context menu it correctly enters the Username and Password.

Can you confirm this? 

Thank you!
