### ISSUE TITLE
Cloning entry naming inconsistency

### ISSUE THREAD

**Issue by vsvyatski** [keepassxreboot/keepassxc#692]
## Expected Behavior
When one clones an entry of a database, the dialog with options is shown. The first option says **Append ' - Copy' to title**. I expect this exact text to be added, e.g. if my record is titled **blah** it should become **blah - Copy**.

## Current Behavior
The text **- Clone** is actually added to a newly created entry. Using the same example from above the newly created entry becomes **blah - Clone**. We have some sort of an inconsistency here, i.e. the program declares one thing but actually does a slightly different one.

## Possible Solution
We should stick to either  **- Copy** or **- Clone** in both the dialog and the code that clones an entry.

## Steps to Reproduce (for bugs)

1. Open or create a new database so that it has an entry in it.
2. Right-click on the entry and select **Clone entry**.
3. When the **Clone options** dialog emerges make sure the option **Append ' - Copy' to title** is checked. Click **OK**.
4. Observe the inconsistent result in a newly cloned entry title.

## Context
Well, the application doesn't crash, it can be used. But I believe that declaring one thing and doing another in practice is not good.

## Your Environment
* KeePassXC version/commit used: 2.2.0/caa49a8ef3ee28ed478192389b21d61107b3b8e0
* Qt version (e.g. Qt 5.3): 5.5.1
* Compiler (e.g. Clang++3.6.0): gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609
* Operating System and version: Linux Mint 18.1 Serena Cinnamon Edition

**Comment by TheZ3ro** [comment]
Wow! Nobody noticed this since KeePassX.

Edit:

**Comment by vsvyatski** [comment]
This issue is no longer present in 2.4.1.
