### ISSUE TITLE
Global Auto-Type shortcut does not respect the setting 'Use entry URL.." and instead always searches fo Window Title

### ISSUE THREAD

**Issue by anonymous133** [keepassxreboot/keepassxc#6921]
## Steps to Reproduce
[NOTE]: 
1. Use these settings
![screenshot](https://user-images.githubusercontent.com/47555412/133662581-be0361e8-0713-4b86-bf5b-4a09d1dc73e4.png)

2. Go to a website you have an account saved and press the Global Auto-Type shortcut key.
3. The Global Auto-Type shortcut searches the database for the Title and ignores the 'Use entry URL' setting from step 1

## Expected Behavior

I'd expect that the Global Auto-Type shortcut respects the setting that it should look for the URL as well.

## Actual Behavior
Global Auto-Type searches the window title in the database regardless of setting.

## Context
The documentation says "When the Global Auto-Type hotkey is pressed, KeePassXC will search your database for entries matching the current selected window title."

So I'd like to request the feature that Global Auto-Type shortcut respects the setting which field in the database it should look for.

Thank you!

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.6.6
Operating System: Linux
Desktop Env: i3
Windowing System: X11

**Comment by droidmonkey** [comment]
The url must be present in the window title to be used. 

"KeePassXC will search your database for entries matching the **current selected window title.**"

**Comment by anonymous133** [comment]
@droidmonkey 
Oh I thought Keepass can read out the URL of a browser window and match it to the database? Because the other way around this seems to be the case with 'Perfom Auto-Type'?

By that you could use the Auto-Type shortcut and wouldn't need to look up the entry manually anymore to 'Perform Auto-Type'

**Comment by droidmonkey** [comment]
No we cannot read the url if it is not in the window title.

**Comment by anonymous133** [comment]
@droidmonkey 
Than I misunderstood how this function works. Thank you for your patience :)

**Comment by droidmonkey** [comment]
No worries, that has confused others in the past as well.
