### ISSUE TITLE
Entry sorting not triggered on edit

### ISSUE THREAD

**Issue by d-faure** [keepassxreboot/keepassxc#6924]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
Once back to group entries view from an edited entry, the sort order of the related entry list hasn't been refreshed.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. In a group view containing several entries, make sure the "Modified" column is activated and select it as the entry sorting criterium.
2. Edit an entry with an "old" modification date, and validate to have it's modification timestamp becoming sooner as every others.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
The edited entry should be at the proper place in the list according to the sort direction (top or bottom while sorting on "Modified" column)

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
The entry is still at the same position

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.6
Revision: 9c108b9

Qt 5.15.2
Debugging mode is disabled.

Operating system: Windows 8.1 Version 6.3 (Build 9600)
CPU architecture: x86_64
Kernel: winnt 6.3.9600

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
- libgcrypt 1.9.2-unknown

**Comment by pruthig** [comment]
Just to add
I am not able to reproduce it on Windows 10 Version10.0.18363

**Comment by droidmonkey** [comment]
Yah I'm pretty sure this is not a bug.

**Comment by droidmonkey** [comment]
Yup works perfectly fine.

**Comment by d-faure** [comment]
My exact usage path was:

1. Have a group of entries ordered by last modification time.
2. Select one entry not at the top or bottom, ie. not last modified recently and edit it.
3. Check+Uncheck the expiration time toggle, which would change the expiration time but keep the expiration sensibility flag.
4. Validate your edit.

While returning to the list of entries, the edited entry should be found on top or bottom of the list, but it is not the case.

**Comment by droidmonkey** [comment]
Wait so the expiration flag starts unchecked and remains unchecked after you are done? If so then you have made no edits.

**Comment by d-faure** [comment]
In theory yes, nothing changed, with the except that on the edit screen, as soon as you check the expiration flag the expiration date is reset to current date and the unchecking is just disabling the field and doesn't touch the value itself.
So practically, validating the form let the record modified and the list should be resorted accordingly.
The behavior itself is interesting, as it gives you a way to touch an entry without having to explicitly have to edit it.
The topic is just to get a refresh triggered on the entry list when one of them have been edited.

**Comment by droidmonkey** [comment]
If the expiration checkbox starts unchecked and ends unchecked then it is irrelevant what date is in the box because NOTHING is changed on the entry.  You aren't "touching" an entry by doing what you did. Add a space to the notes field if you want to touch an entry.

**Comment by d-faure** [comment]
You're surely right, but this is not the behavior I have now in the code.
Here's a group of 2 entries sequentially created (1, then 2) and ordered by last modified time:
![KeePassXC 2021-10-07 163706](https://user-images.githubusercontent.com/1654767/136407446-67883a47-fc67-41cc-95a3-d7bef3092f4c.png)
Once I've edited the first entry, with just a check/uncheck of the expiry flag and validated modification with OK, I get:
![KeePassXC 2021-10-07 163907](https://user-images.githubusercontent.com/1654767/136408138-059dedaa-1714-4fe6-bfd3-ff823d0262fe.png)
Which shows that the group hasn't been reordered. That's it.
