### ISSUE TITLE
Setting/Toggle -- Double-click URL launch browser

### ISSUE THREAD

**Issue by grantthomas** [keepassxreboot/keepassxc#6926]
## Summary
Allow double clicking on the URL field to copy to clipboard instead of launching browser

## Examples
Current behavior is to automatically launch a browser when valid URL or IP address is in URL field.

## Context
I administer many remote servers and systems through various VM, RDP, VPN platforms, and maintain a global keepass DB on my main workstation.
Almost exclusively, when I need a URL from keepass, it is to paste into a remote system, not my workstation where keepassxc is running.

When I do not need a URL for a remote system, I want the URL to be available to the browser of my choice -- not the global system browser as I keep work and personal tasks in separate browser / profiles.

**Comment by droidmonkey** [comment]
You can use Ctrl+U in the meantime to copy url into clipboard.

**Comment by grantthomas** [comment]
Thanks for the tip,
I also see some dedicated buttons in the toolbar for copying the URL.

**Comment by droidmonkey** [comment]
Yup, given all that a dedicated setting to change this behavior is unlikely to happen.

**Comment by grantthomas** [comment]
Bummer, but understood.

**Comment by Shayan-To** [comment]
I would really love to see this happen. I use multiple browsers, and it is very annoying that I cannot copy the URL with double click, like it can be done with other fields.

Is there any workaround? Can a plugin change the behavior?

**Comment by joh-klein** [comment]
I really miss this feature as well :( – I just changed to KeePassXC because of the better (i.e. existing) touch-id support from macPass (which had a setting for this). Like OP I rarely need the URL to be opened in my default browser – I use a number of different browsers (and private sessions) for different clients, which makes the "Open URL in browser" quite useless …

**Comment by dmaslenko** [comment]
Seems, it is duplicated with #4717.
