### ISSUE TITLE
Entry icon fetching doesn't work as expected on subdomains

### ISSUE THREAD

**Issue by pandruszkow** [keepassxreboot/keepassxc#6929]
## Overview
KeePassXC does not behave as expected when fetching entry icons. Where the different subdomains do not have the same favicon, it should be possible to handle that when the icons are being fetched.

For example, given example.com with two subdomains, there might be three distinct favicons to capture:

* git.example.com - has the default favicon used by the Git hosting service deployed there
* custservice.example.com - has the default favicon used by the customer service/ticket tracker software deployed at that address
* example.com - has a custom favicon based on example.com's company logo

## Steps to Reproduce
1. Go to `subdomain1.example.com`
2. Sign in, capture password entry
3. Click **Download favicon**
4. Go to `subdomain2.example.com`
5. Sign in, capture password entry
6. Click **Download favicon**

## Expected Behavior
Proposed behaviour:

KeePassXC detects that `subdomain1` and `subdomain2` may have differing favicons despite sharing the root domain name. It downloads the favicon for `subdomain2`. It compares the two favicons. If the favicons are identical or nearly the same (differing by a few pixels or shades of colour), the downloaded favicon for `subdomain2` is discarded and the original favicon for `subdomain1` is used instead to avoid duplication.

Simpler implementation:

KeePassXC detects that it already has a favicon on record for `subdomain1`. It displays the current "Existing favicon selected" prompt, but also presents some way to override the prompt and download the favicon anyway, even if it's duplicated.

## Actual Behavior
KeePassXC displays a banner with the message "Existing favicon selected", and does not allow an attempt to download the favicon anyway.

## Context
This may be useful to visually distinguish entries in the same group.

KeePassXC - Version 2.6.6
Revision: 9c108b9

Operating System: Linux
Desktop Env: Gnome
Windowing System: X11

**Comment by droidmonkey** [comment]
We compare a hash of the bytes of the favicon so if you are getting the message that it already exists then it is literally the same. We won't be implementing any additional logic behind favicons.

**Comment by droidmonkey** [comment]
Also #6614

**Comment by Clindbergh** [comment]
I have the same problem. Consider this use case: I set up an entry for company.com for the public website hosted with wordpress. Later I add new entries for gitlab.company.com and confluence.company.com. When I try downloading icons for these new entries they all receive the already downloaded (wrong) wordpress icon from the main domain.
