### ISSUE TITLE
Expiration preset `1 year` not well translated in french

### ISSUE THREAD

**Issue by joelroyer** [keepassxreboot/keepassxc#6931]
## Overview
French translation of expiration presets have a mistake. 

## Steps to Reproduce
1. Go to Settings and set the language to French
2. Open any entry and enable expiration
3. Open preset choices and see french translation for `1 year`

## Expected Behavior
The preset `1 year` in french must be `1 an` instead of `% an`.

## Actual Behavior
The preset `1 year` in french is `% an`.

## Context

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.6
Revision: 9c108b9
Distribution: Snap

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux (CentOS 7)
Desktop Env: Gnome
Windowing System: X11 (not sure)

Same behavior with Windows 10 and KeePassXC - Version 2.6.6

**Comment by droidmonkey** [comment]
Head over to transifex.com to correct please.

**Comment by joelroyer** [comment]
> Head over to transifex.com to correct please.

I am not sure I understand your answer.  is this a bug with the Transifex application?

**Comment by droidmonkey** [comment]
No, transifex is where translations are done.

**Comment by joelroyer** [comment]
I've checked translation on Transiflex and it was good.
So translation is not the problem.

This is what I see :
![image](https://user-images.githubusercontent.com/23218224/135077056-5fb9932b-4761-4793-8e33-c0bdba15413f.png)

**Comment by droidmonkey** [comment]
The translation should be `%1 an`. It probably isn't merged into the deployed baseline yet if it's correct on transifex.

**Comment by joelroyer** [comment]
Okay. Updated in 2.7.x.
2.6.x is fixed and can't be revised.
