### ISSUE TITLE
keyborad shortcuts (configurable) to switch between database panes

### ISSUE THREAD

**Issue by mq2195** [keepassxreboot/keepassxc#6932]
## Summary
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
When using multiple databases (all of them are locked), when clicking keepassxc icon in internet browser a password dialog for database will show up, but it is dialog for first or last used database. I would like to be able to switch which database will be unlocked with keyboard (now I have to use mouse).
So: two keyboard shortcuts (next/prev) for switching active/current database (at unlocking time).

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )
https://ibb.co/sv3YMcs

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
I am heavy linux/terminal (tmux) user. That is why switching  windows/panes with keyboard is natural to me.

Thank you for great software. Big fan here.

**Comment by droidmonkey** [comment]
This feature has been merged into develop and will be available in version 2.7.0
