### ISSUE TITLE
TOTP easy copy

### ISSUE THREAD

**Issue by adelpourmand** [keepassxreboot/keepassxc#6935]
Hello there,
Thank you for your great software. I wish keepass XC could have an icon in its toolbar (like copy username and copy password) so that I can easily copy TOTP and paste is it the browser. Currently I have to find the entry and then pressing right click and find TOTP and copy it which is time-consuming and nerve racking. 

Best
 - Adel

**Comment by droidmonkey** [comment]
Either double click the clock icon in the entry row or use the keyboard shortcut Ctrl + T.

https://keepassxc.org/docs/KeePassXC_UserGuide.html#_keyboard_shortcuts
