### ISSUE TITLE
KeepassXC apparently running but not accessible - Linux Mint/Cinnamon

### ISSUE THREAD

**Issue by pwilliamson19** [keepassxreboot/keepassxc#6936]
I have Keepass set up to start automatically (via Startup Applications)
Minimise at Application Startup
Show System Tray Icon

Sometimes, when I left-click the tray icon after startup but before opening the database something flashes up on the screen and then disappears, but KeepassXC does not appear. And when I subsequently click the tray icon nothing happens. So I can't get in to open/view/edit the database

Autotype still works OK. And after doing an autotype and opening the database I can get KeepassXC on the screen using a left-click on the tray icon.

If I start it manually and minimise it to the tray it seems to be OK.

KeepassXC 2.4.3
Linux Mint 20.2
Cinnamon 5.0.5
![Keepass](https://user-images.githubusercontent.com/40455915/134520270-91e6165d-8a1a-486a-aea2-a116e1beabfd.png)

![Keepass 2](https://user-images.githubusercontent.com/40455915/134520512-229c1372-6968-4281-a05b-e730d539fa45.png)

**Comment by droidmonkey** [comment]
This is fixed in more recent version of keepassxc.
