### ISSUE TITLE
Add LibreSSL support

### ISSUE THREAD

**Issue by WSLUser** [keepassxreboot/keepassxc#6937]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )

LibreSSL has far less vulns associated than OpenSSL and does maintain compatibility to a certain degree with certain versions of OpenSSL. It is unlikely this application is using some OpenSSL feature that can't be replaced  by LibreSSL. Biggest advantage to this keeping from having to update every time OpenSSL has a CVE when LibreSSL does not.  Furthermore, the native Win32-OpenSSH provided by Microsoft uses LibreSSL, which on Windows, should be used by default by this application for applicable scenarios (like the SSH Agent extension).

The Powershell team at Microsoft keeps a easy to consume fork [here](https://github.com/PowerShell/LibreSSL) which they keep up with upstream after a release appears stable enough for them.
## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
I want this application to be even more secure and not have old cruft that's part of OpenSSL bogging it down.

**Comment by droidmonkey** [comment]
I don't see the value in this from the effort required to make it happen. The only thing openssl is used for is limited network requests that go through Qt. This would be favicon downloads, hibp reports, and update check. SSH Agent does not use SSL. To use LibreSSL would require compiling Qt with that dependency which is definitely not something we want to take on and certainly not even possible with Linux distros that control the packages.
