### ISSUE TITLE
Check for updates

### ISSUE THREAD

**Issue by weslly** [keepassxreboot/keepassxc#694]
## Expected Behavior
Check for updates when the application starts and notify the user when there's a new release available to download.

## Possible Solution
Check the [Github API](https://api.github.com/repos/keepassxreboot/keepassxc/releases/latest) for releases and notify the user if there's a new release available.

We can ask the user if he wants to enable this feature on the first run and make it "toggleable" in the settings.

It should be possible to enable/disable this feature with a compiler flag, since package managers have their own updates.

**Comment by droidmonkey** [comment]
@weslly do you want to work on this?

**Comment by weslly** [comment]
Yes, I'll take a look at it this week
