### ISSUE TITLE
SUGGESTION allow wildcard, or regex in URL for matching with browser plugin

### ISSUE THREAD

**Issue by Madydri** [keepassxreboot/keepassxc#6940]
## Summary
When using login via "Sign in with....", there is in the URL most of the times an indication of the actual site
If we could put in the URL wildcards, or even use a regex, it could be possible in the browser plugin to only show the "Sign in with" accounts that are linked to the site using it.

## Examples
https://accounts.google.com/o/oauth2/auth/identifier? .... &redirect_uri=https%3A%2F%2Flogin.tailscale.com....
In this case only the google accounts used for the site login.tailscale.com should be showed in the browser plugin

## Context
Using different "Sign in with...." accounts, mostly only 1 is relevant for a site.
Now it is difficult to use the URL-matching, as the URL of the "Sign in by..." sites have some content that change at each use : so URL matching can now not find the pertinent entry

**Comment by droidmonkey** [comment]
This is a duplicate request

**Comment by droidmonkey** [comment]
For your particular use case, set the url in the entry to that exact url you pasted and enable "only return best matching credentials" in the browser integration settings.
