### ISSUE TITLE
Secret Service will not be able to return any entries if the exposed group has search disabled

### ISSUE THREAD

**Issue by alaviss** [keepassxreboot/keepassxc#6942]
## Overview
If the exposed group has searching disabled, then apps will not be able to look for secrets.

## Steps to Reproduce
1. Create a new group called "Keyring", with "Search" set to "Disabled".
2. Enable Secret Service and expose "Keyring".
3. Run `secret-tool store --label=test attr test` and enter any password.
4. Run `secret-tool lookup attr test`

## Expected Behavior
The entered password is returned.

## Actual Behavior
Nothing is returned, `secret-tool` exit with status code 1 (entry not found).

## Context
KeePassXC - Version 2.6.6

Qt 5.15.2
Debugging mode is disabled.

Operating system: Gentoo/Linux
CPU architecture: x86_64
Kernel: linux 5.14.6-zen1

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- Secret Service Integration

Cryptographic libraries:
- libgcrypt 1.9.4-unknown

Operating System: Linux
Desktop Env: Gnome
Windowing System: Wayland

**Comment by Aetf** [comment]
Hmm should be an easy fix by setting `forceSearch` to `true` when searching
