### ISSUE TITLE
stuck in endless saving cycle

### ISSUE THREAD

**Issue by safarirat** [keepassxreboot/keepassxc#6944]
## Overview
After saving db with rclone to dropbox, keepassxc stuck in endless saving cycle.

## Steps to Reproduce
1.  rclone db to web (?)
2.  create a new entry
3.  interface lagged 
4.  try save/exit/lock app say "Ошибка при записи базы данных: Сохранение базы данных уже выполняется" (sorry cant change lang)

## Expected Behavior
Use db after copy a file

## Actual Behavior
app cant lock and i need to export csv to update db with new entry.

## Context
i try reproduce but now it work ok 😒 csv export saved all my data, so whatever.

KeePassXC - 2.6.6
Revision: 9c108b9

Operating System: Windows

**Comment by droidmonkey** [comment]
known issue that is being addressed already thank you. This can happen when the database is "modified" continuously by an external application and auto-save on every change causes further modifications. Basically the two apps are competing with each other.
