### ISSUE TITLE
open second database from terminal

### ISSUE THREAD

**Issue by puchrojo** [keepassxreboot/keepassxc#695]
You can't open a second database from terminal. Only ober menu open.

## Current Behavior
1. open one database from terminal (or other method)
2. try to open a second database from terminal. You get this message:
"Another instance of KeePassXC is already running."
The program are now on foreground, but not asking for the password.

## Expected Behavior
2.  try to open a second database and the Program ask fro the password and open the database. 
     If the database are already open jump to the tab for the database. 

## Context
It is not a great problem, but that is one the thinks that I miss on keepass2. I work daily with 4 database and sometimes with more. I have a alias for every database and now they don't work. 

## Your Environment
KeePassXC - Version 2.2.0
Revision: caa49a8ef3ee28ed478192389b21d61107b3b8e0

Libraries:
- Qt 5.5.1
- libgcrypt 1.6.5

Enabled extensions:
- KeePassHTTP
- Auto-Type
- YubiKey

Operating System and version: Linux Mint 18.1 Serena Release with Debian old-stable Package.

**Comment by droidmonkey** [comment]
Oh nice find, another unintended casualty of single instance

**Comment by phoerious** [comment]
We need to rework the single instance stuff a little. When I open a second instance in debug mode, my normal non-debug mode instance is still being raised to the foreground which is really annoying.

**Comment by droidmonkey** [comment]
Oh yes agreed
