### ISSUE TITLE
No indication that password is longer than visible part

### ISSUE THREAD

**Issue by tredondo** [keepassxreboot/keepassxc#6952]
## Overview
When displaying longer passwords, such as BIP39 seed phrases, the app doesn't indicate there's more to the password than what's seen. Only attempting to select the password with the mouse will reveal it's longer than what was initially displayed.

Screenshot of discarded seed phrase:
![image](https://user-images.githubusercontent.com/10043369/134824115-49d542b1-db3f-41ec-ad7a-3cc09822bd23.png)

If the user types only the visible seed words and there are others beyond those shown, a false freakout might occur.

KeePassXC - 2.6.6
Revision: 9c108b9
Operating System: Linux
Desktop Env: KDE
Windowing System: X11

**Comment by droidmonkey** [comment]
This is a preview, we can't show an indication (like a .... at the end) without preventing you from selecting the entire line (ie, it will get cut off). This is a won't fix unfortunately.

**Comment by michaelk83** [comment]
You can place the ... in a separate label, still keeping the passphrase as is.

**Comment by droidmonkey** [comment]
No that is not a good way to handle this. If anything we could make these multi line, but that has its own problems. I'll take a gander at Qt native options but this will likely not be changed. It's an edge case.

**Comment by tredondo** [comment]
I was also thinking of an indicator separate from the password, but that would probably involve estimating the total vs. displayed length of the password in pixels.

**Comment by droidmonkey** [comment]
We could show a pixmap aligned to the right within the label that has an arrow or similar type indicator. Determining if there is overflow is definitely the hard part. That also changes as you select text and it scrolls over.

**Comment by phoerious** [comment]
I think we should generally think about line-wrapping long passwords. The password edit field has the same issue, which could lock users out of their accounts if they are not aware of it.

**Comment by tredondo** [comment]
@droidmonkey what was the resolution for this closed issue?

**Comment by droidmonkey** [comment]
We aren't going to make any changes, it is not worth the UI headaches that get incurred. Sometime in the future we might have an action hover row that would include a copy button, that to me is the most elegant solution.
