### ISSUE TITLE
Dark Theme not working with KeePassXC 2.6.6 snap

### ISSUE THREAD

**Issue by Jaz-z** [keepassxreboot/keepassxc#6953]
## Overview
[NOTE]: # ( Give a BRIEF summary about your problem )
KeePassXC 2.6.6 - source snap does not follow general window themes

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Install a dark theme
2. customise window decorations for dark theme
3. Install KeePassXC 2.6.6 to compare also install KeePassXC 2.4.3
4. Check the colours in windows to compare with global theme and window settings

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
The theme in my desktop is a dark theme where inside windows have dark grey background with greyish white fonts KeePassXC 2.6.6 should display similar background and font colours

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
KeePassXC 2.6.6 displays a white background with black fonts

## Context
[NOTE]: # ( Give us any additional information you may have. )
In software depository (discover) for Kubuntu there are two KeePassXC apps:
a)
Version: 2.6.6
Author: Jonathan White
Source: Snap

B)
Version: 2.4.3+dfsg.1-1build1, released on 12/06/2019
author: KeePassXC team
Source: Ubuntu-focal-universe (Ubunut 20.4.3)

The theme in my desktop is a dark theme where inside windows have dark grey background with greyish white fonts
KeePassXC 2.4.3 follows the global theme correctly, KeePassXC 2.6.6 displays a white background with black fonts

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.6
Revision: 9c108b9
Distribution: Snap

Qt 5.9.5
Debugging mode is disabled.

Operating system: Ubuntu Core 18
CPU architecture: x86_64
Kernel: linux 5.4.0-86-generic

Enabled extensions:
- Auto-Type
- Browser Integration     (in settings this is not enabled but in about it shows as enabled!)
- SSH Agent     (in settings this is not enabled but in about it shows as enabled!)
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration   (in settings this is not enabled but in about it shows as enabled!)

Cryptographic libraries:
- libgcrypt 1.8.1

---------------------

KeePassXC - Version 2.4.3
Revision: 5d6ef0c

Qt 5.12.8
Debugging mode is disabled.

Operating system: Ubuntu 20.04.3 LTS
CPU architecture: x86_64
Kernel: linux 5.4.0-86-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (only unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.5

----------------------------------

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux   Kubuntu 20.04
Desktop Env: KDE Plasma Version: 5.18.5
Windowing System: xcb

KDE Frameworks Version: 5.68.0
Qt Version: 5.12.8

![KeePassXC_Compare_Dark_Theme_Issue](https://user-images.githubusercontent.com/73505939/134826520-1ab8de64-37b2-4326-a6b5-b017b6f554ce.png)

**Comment by droidmonkey** [comment]
Put the 2.6.6 version in classic theme or our own dark theme from the view menu.

**Comment by droidmonkey** [comment]
Put the 2.6.6 version in classic theme or our own dark theme from the view menu.

**Comment by Jaz-z** [comment]
Thank you again

Classic (platform native) doesn't change it (does not follow the global 
theme) and the background remains white.

KeePassXC dark theme works, but it is as you say the application's own 
dark theme which is different to the desktop's global theme; KeePassXC's 
dark theme is not the best option for my needs.

_Unrelated topic:_

I probably misunderstand, but I hope you noticed my notes in the debug 
information, about setting options showing not enabled in settings but 
showing enabled in the debug information copied from the help menu / about.

**Comment by droidmonkey** [comment]
Snaps don't integrate well with some desktops. Recommend using our appimage or ppa if you want tighter theme integration.

**Comment by phoerious** [comment]
PPA rather. AppImage has the same problem.

**Comment by Jaz-z** [comment]
Thank you
