### ISSUE TITLE
Improve general usage documentation

### ISSUE THREAD

**Issue by TheZ3ro** [keepassxreboot/keepassxc#696]
Many useful feature are not documented anywere. 
We need to write some proper documentation for the general usage of KeePassXC

for example: https://github.com/keepassxreboot/keepassxc/pull/127#issuecomment-311462557

Like we said in the other Issue:

>  Another feedback we got from the 2.2.0 release is that the documentation for the project is lacking. With this new feature, I'd like to add documentation for the CLI tools we have. What's the plan for us to document the project? The Wiki would be nice, but it's impossible to open PRs on the wiki :(

> Yup, I was thinking about documentation as well.
We can open a new repository called wiki and then we can make a script that pushes wiki/master over https://github.com/keepassxreboot/keepassxc.wiki.git for every new commit in wiki/master with a hook like @phoerious did for the website

We should add also a link to docs in the Help toolbar

**Comment by sts10** [comment]
I don't know if this is helpful or if it's been done elsewhere in a superior way, but I took [a quick stab at a blog post explaining the basics of using KeePassXC](https://sts10.github.io/post/keepassxc-setup-guide/)-- here's the [raw markdown](https://github.com/sts10/blog-hugo/blob/master/content/post/keepassxc-setup-guide.md) and [the static images and GIFs I made and used](https://github.com/sts10/blog-hugo/tree/master/static/img). I'd be happy to submit it (or a version of it) to this forthcoming wiki for editing!

Though maybe you guys will want to prioritize documentation of features that XC adds to the KeePass ecosystem?-- things like setting up the YubiKey challenge and response, setting the number of transform rounds, a simplified guide to verifying the signature on a release, etc.

**Comment by TheZ3ro** [comment]
@sts10 I like this guide! It's very useful for first-time users, I will open a new repository for the wiki asap

**Comment by phoerious** [comment]
I think we should host the wiki on the main website and not on GitHub. The GitHub wiki is good for developer documentation, but the end user stuff should be on the website.

**Comment by TheZ3ro** [comment]
Ok, I agree

**Comment by louib** [comment]
I'd really like to have the documentation directly in the repo. My argument for it would be that the documentation can be updated at the same time new features are added or existing features change. Right now, we have a checkbox in the PR template for updating the documentation according to the changes, but we can't really enforce it in the context of the PR itself. Having the documentation in the repo itself would allow us to enforce this when reviewing the PRs.

That being said, I think all of that documentation should also be available to the end user on the website, so for this solution to work, we'd need to generate periodically the user guide section of the website from the documentation in the repo.

**Comment by TheZ3ro** [comment]
We can use the website repository for documentation, that just need some little changes in the jekyll template

**Comment by schiorean** [comment]
Looks like https://github.com/keepassxreboot/keepassxc/issues/1024 was quickly closed.  

> The exact steps are described on our website.

True I have no clear idea how to use gpg to verify a release (and considering this app will be able to see my most sensitive data I consider verification of each release a prerequisite), but a novice like found no help in the steps detailed here https://keepassxc.org/verifying-signatures. And I still have no idea how to get to a .sig file mentioned in this guide. 

All in all, I think this is a big miss in documentation.

**Comment by affinityv** [comment]
@schiorean I'm sure you know from other posts, but for others, the sig link is currently next to the digest link on the download page; there are two links separated by spaces and a dash.

**Comment by TheZ3ro** [comment]
@sts10 I think I will work on the documentation in the next few days :wink:

**Comment by TheZ3ro** [comment]
We should add also a link to docs in the Help toolbar

**Comment by weslly** [comment]
@TheZ3ro that would solve #827

**Comment by hifi** [comment]
What about in Qt help? http://doc.qt.io/qt-5/qthelp-framework.html

It would be rather nice if the docs could be embedded in the application for offline use. It also helps developing documentation along with code changes. I don't know if the HTML files are generic enough to be uploaded to the website as well.

**Comment by TheZ3ro** [comment]
I don't know, seems pretty time consuming. With Jekyll and the website we can write markdown docs and compile them with the website layout

**Comment by droidmonkey** [comment]
You can likely just open rendered offline HTML in the user's browser of choice. Deploy the html docs.

**Comment by Mogost** [comment]
[Changelog on wiki](https://github.com/keepassxreboot/keepassxc/wiki/KeePassXC-Changelog) that is used on [website](https://keepassxc.org/project) is outdated.

**Comment by phoerious** [comment]
@Mogost Fixed.
