### ISSUE TITLE
How to prevent autofill via http plugin?

### ISSUE THREAD

**Issue by Losiara** [keepassxreboot/keepassxc#697]
## Expected Behavior
When page open where there is saved password, keepasxc waits for user command to fill fields

## Current Behavior
If url detected, fields autofilled anyway

## Possible Solution
Add some options to json in setup area of http plugin to prevent autofill.

## Your Environment
kepassxc 2.2.0

**Comment by phoerious** [comment]
The browser plugins are not maintained by us. Please report the issue directly to PassIFox and chromeIPass.

We have a successor browser integration called keepassxc-browser in the works, which will not autofill login fields.
