### ISSUE TITLE
Combination of a yubikey passphrase and yubikey challenge response doesn't work. 

### ISSUE THREAD

**Issue by themasch** [keepassxreboot/keepassxc#698]
I used to use a passphrase which combined manually entered sequence with the passphrase stored on the yubikey. I type the first ~15 characters, then press the button on the key to enter the rest. 

## Expected Behavior
I enter my passphrase, let the yubikey "enter" his passphrase, the yubikey sends [enter], keepassxy should set the key in CR-Mode and ask me to press the button on the yubikey. 

## Current Behavior
The yubikey is either in "passphrase-mode" or in "CR-mode". When I tick the cr-checkbox or click the "refresh" button it seems to put the key in cr-mode, when I pull the key and put it in again its back to passphrase mode. When its in CR-mode, it won't generate the passphrase, when in passphrase-mode the CR failes.

## Possible Solution
Maybe keepass should set the key to CR-mode right before asking the user to press the button?

## Context
There was a plugin for the old keepass which worked with a combination like this, which makes me guess that it should be technical possible. I don't know much about how the key acutally works though, so I might be wrong. 

## Your Environment
* KeePassXC version/commit used: 2.2.0 /  caa49a8ef3ee28ed478192389b21d61107b3b8e0
* libyubikey: 1.13
* Qt version: 5.7.1 
* Compiler: gcc 4.9.4
* Operating System and version: gentoo linux, kernel 4.4.

**Comment by sainaen** [comment]
KeePassXC seems to keep YubiKey in this “CR mode” after unlock too, so as @CRCinAU [reported](https://github.com/keepassxreboot/keepassxc/issues/712#issuecomment-313309689) in other thread:

> When the C/R happens, and after you have unlocked your KP database, I find that the slot 1 function no longer works until I replug the Yubikey.

I think in light of this, I'd consider this a bug, not a feature to be implemented: *“A YubiKey should be 'aquired' right before a challenge-response performed and 'released' immediately after that.”*

[I've tried](https://github.com/sainaen/keepassxc/commit/7a9d30914e9298d4d7edd72eb5b6dd1e1f35f6fc) adding a `YubiKey::instance()->deinit()` at the end of the `YkChallengeResponseKey::challenge()` and it fixes part of the issue allowing to use slot 1 after unlock/save, but I don't know full implications of doing this and I wasn't able to make `YubiKey::detect()` also call `deinit()` without some weird side effects.

I'll try to work on this a bit more, but if anyone more experienced want to jump in, please go ahead.

**Comment by droidmonkey** [comment]
I am not seeing this behavior at all. I can enter the first part of the password, hold the button to activate "Slot 2" which enters the later part of the password, then hit enter to use C/R in slot 1.

**Comment by sainaen** [comment]
@droidmonkey 
Yes, because that's not the problematic sequence. Try to use your second slot *after* you've unlocked DB.

**Comment by themasch** [comment]
I'm using a yubikey neo. 
When I plug my key in, start keepassxc, it opens my db and scans for keys. 
It detects my key, ticks the "Challenge Response" checkbox. 
After focusing the Password box, I press the button on the yubikey. Nothing happens. 

When I pull the key, and insert it again, I can use the button to generate a password, but the challenge response mode failed. "Unable to issue challenge-response". 

After pressing "refresh" and entering my normal password, the challenge response works. 

I guess it could work if I press refresh after the key entered the password, but it automatically sends a [enter] after entering the password. 

I'll check the manager tool if changing the slots or something like that might help.

**Comment by droidmonkey** [comment]
I can use my key (neo)  in any application to enter a static password on long press no matter whats going on in keepassxc. I would need more specific setup and sequence info to replicate if at all possible.
