### ISSUE TITLE
Need Import CSV after I have create an database already.

### ISSUE THREAD

**Issue by zhouyijiaren** [keepassxreboot/keepassxc#6985]
## Summary
I need a function to import CSV data to kdbx

I know that we can start with a CSV file. But I have used kdbx file from a long time, and I want to import CSV data from Google account.

**Comment by phoerious** [comment]
You can import a CVS to a new file and merge the new KDBX into your old KDBX.

**Comment by droidmonkey** [comment]
This is a duplicate request. Frankly I don't think it's a good idea to merge a csv directly into an existing database anyway. Importing into a new database let's you groom the created entries and make sure it looks good before polluting your existing database. Then do a simple merge operation into your existing database.

**Comment by zhouyijiaren** [comment]
@droidmonkey @phoerious   Thank you very much, It is useful
