### ISSUE TITLE
Set BrowserOnlyHttpAuth through CLI

### ISSUE THREAD

**Issue by guradia** [keepassxreboot/keepassxc#6986]
## Summary
Currently it's the BrowserOnlyHttpAuth flag i seem to be unable to edit.
Overall i wish to edit a complete entry or even define any possible Setting a KeePass-DB has to offer.

## Context
While setting up Hosting-Environments, and for example Wordpresses, i would like to share autogenerated credentials with co-workers (and myself without having to manually fill up my KeePass-DB)

So far, adding new Logins is successfull and working as expected. And of course i can add HTTP-Auths as simple credentials for the same URLs, too. But organizing them into HTTP-Auth and Non-HTTP-Auth has to be done manually.

**Comment by droidmonkey** [comment]
This is better handled by the upcoming group-enforced browser options. You can create a group that forces HTTP-Auth and Non-HTTP-Auth and create your entries in the appropriate group to automatically get those settings. See #4180
