### ISSUE TITLE
Make the 25ms delay in autotype overridable 

### ISSUE THREAD

**Issue by TheZ3ro** [keepassxreboot/keepassxc#699]
With #550 we have introduced a small delay in autotype for Linux (and before that, for other platforms).
This delay is fixed and hardcoded to 25ms.

Some users can't use autotype since it's very slow and have very long email-passwords (like for example https://github.com/keepassxreboot/keepassxc/issues/128#issuecomment-311241590)

## Possible Solution
- Make the hardcoded delay overridable by the `{DELAY=n}` keyword
- Add an autotype setting for this global delay [**preferred**] (like suggested in https://github.com/keepassxreboot/keepassxc/issues/128#issuecomment-303871493)

The default setting will still be 25ms but we are giving users the option to change this value accordingly to their needs

@hifi asked to assign this to him, I can't since he's not in the Github team so I will assign this to myself

**Comment by hifi** [comment]
@TheZ3ro This can be closed.
