### ISSUE TITLE
Enable searchfield when entry is opened

### ISSUE THREAD

**Issue by remcokalf** [keepassxreboot/keepassxc#6997]
## Summary
When an entry is open, the searchbox is greyed out. It would be very useful to be able to search again right away, instead of clicking Cancel or Escape. 

## Context
I navigate my entries almost exclusively by search. It is cumbersome to have to click Cancel or Esc all the time to start the next search, even if you just look up something and don't make any changes. I can't think of a reason to lock search when an entry is open. Unless maybe if you are editing it and there are unsaved changes. Or if there would be confusion about what the scope of search is (the open entry or all entries). Maybe there are valid reasons I am not aware of.

This last remark touches on another feature request I have: search within an entry, specifically within the Notes field.

**Comment by droidmonkey** [comment]
This behavior won't change specifically because you are editing an entry when it is opened.
