### ISSUE TITLE
Feature request: Keep old database versions

### ISSUE THREAD

**Issue by rodoviario** [keepassxreboot/keepassxc#700]
It will be nice to have an automatic database backup (a funcionality that exists as plugin in keepass2)

## Expected Behavior

Every time yo save the database the old version is saved with the date appended at the end of the filename
It automtically keeps in a selectable number of files (let say, onli 5 copies)

## Current Behavior

There is no automatic backup funcionality nor support for backup plugins

## Possible Solution

Add support for plugins
Reproduce plugin behaviour in the core (better to keep the portable version)

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

I am starting to use keepasxc as the main keepass (instead of the installed and unportable keepass2), but the lack of backup funcionality makes me keep using the installed one too.

## Your Environment

* KeePassXC version/commit used: (can be found under Help -> About)
Version 2.20 linux portable

* Qt version (e.g. Qt 5.3): 
* Compiler (e.g. Clang++3.6.0): 
* Operating System and version: 
Linux Mint 18.1 (based on Ubuntu 16.04 LTS)

**Comment by droidmonkey** [comment]
Besides database corruption i don't understand the need for this. Every entry already has a history of changes. If you are concerned about corruption, i wouldnt want the application which could cause the corruption to do my backups. Use cron and rsync for that purpose.

**Comment by rodoviario** [comment]
I see your point, and you are mostly right.

But beside corruption, it protects me from human error (mostly mine, but also mi wife's). If we mistakenly delete entries (not update, but delete) and save, its good to know that the previous database version is there. Anyway I can do backups outside the program, and the most valuable thing is the (new) portability for the linux version. I can carry it with me in the phone, with executables for linux and windows, and use it in other places than my home.

I will close the issue and follow your advice to keep copies automatically from outside the program

**Comment by jeroen7s** [comment]
@rodoviario even deleted entries should appear in the trashbin folder as far as i'm aware, so it doesn't show up in searches/autofill, but is still available for recovery when it was accidentaly deleted.
unless you also delete it from the trash bin which i think is a useless thing to do
