### ISSUE TITLE
Global Auto-Type Responses With Title Matches

### ISSUE THREAD

**Issue by bonn2** [keepassxreboot/keepassxc#7009]
## Summary
When using global auto-type on a window with a title match the first response should be the one that is for that window title.

## Examples
This is a screenshot of the menu that opens when hitting your global auto-type hotkey in a window with a custom auto-type sequence saved.
![Example](https://user-images.githubusercontent.com/42011672/135695339-39a71425-0a49-404d-9bc5-698387ce52f6.png)
The first (default selected) option is the default group imposed auto-type sequence, while the second not selected option is the custom auto-type for this window.

## Context
I propose that auto-type sequences that are made specifically for the window should be the first in the list instead of the group default. This would allow you to more quickly login to windows with custom auto-type sequences because you will just need to hit enter rather than arrowing down or using your mouse.

**Comment by droidmonkey** [comment]
So you are matching the entry based on the entry's title and a custom window title definition? Interesting, good suggestion.

**Comment by libklein** [comment]
How should we approach this when several groups/entries match? Should we keep the ordering by group name and use a second-level ordering according to priority?

**Comment by droidmonkey** [comment]
We should order, by default, as follows:
1. Group name
2. Entry title
3. Custom window sequences
4. Entry sequence (whether inherited by the group or Custom to the entry)

Another way would be to calculate the "closeness" of the window title match and sort based on that parameter instead of group/entry sorting.

**Comment by droidmonkey** [comment]
No longer a problem in 2.7.0
