### ISSUE TITLE
[Feature Request] Unlock dialog when in Secret-Service-Integration mode

### ISSUE THREAD

**Issue by bidlocode** [keepassxreboot/keepassxc#7012]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
Now if database is in locked state it just silently acts like there's no saved passwords. The request is for optional setting to show unlock dialog when other program looking up secret-service for passwds. So you have optional 'show popup' or default behavior like it's right now.

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )
You are using gpg to sign a file. gpg is trying to access signing key so that gpg-agent is looking up saved passwords in secret-service. Keepassx shows popup to unlock the db. You unlock the db, gpg gets saved password. 
(Right now if db is locked it just moves on)

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
Makes overall experience of password management more uniform and universal.

**Comment by droidmonkey** [comment]
#6943
