### ISSUE TITLE
Optional feature to allow me to hack my own database should I choose too

### ISSUE THREAD

**Issue by RenatoLopes771** [keepassxreboot/keepassxc#7018]
## Summary
So basically some of us tend to forget our passwords. I think it would be a cool thing if we could create a hackable database. This is just like the normal database except we can "hack" it. I don't know how keepass works so I don't know how you guys want this.

How secure or insecure would your database be at this point? Well if someone with ill intent has physical access to your device, then he also gets all your passwords. On all other scenarios it would be around the same thing (eg lending the device to a family member).

If we could set a timer on how "long" the database should take to hack would also be nice.

## Context
Keepass is a great password manager however some of us are still willing to let go some security for convenience. At the end of the day it should be the choice of the user.

**Comment by droidmonkey** [comment]
No thank you

**Comment by michaelk83** [comment]
> some of us are still willing to let go some security for convenience

Use a passphrase that you can remember. You can set the length as convenient and have KPXC generate it for you. Shorter = easier to remember, longer = more secure (up to the point where it doesn't matter anymore).
