### ISSUE TITLE
Auto type not "translating" keys

### ISSUE THREAD

**Issue by vikke1234** [keepassxreboot/keepassxc#7019]
## Overview
Might be duplicate of #324, but if I use dvorak it will type everything wrong. For example if the username is "username" it would write "go.pbam." instead. 

## Steps to Reproduce
1. enable dvorak keyboard layout
2. autotype

## Expected Behavior
That it would correctly type the username/password

## Actual Behavior
It essentially presses the keys that were on an qwerty keyboard and doesn't correctly well "translate" them to the current layout.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.6
Revision: 9c108b9

Qt 5.15.2
Debugging mode is disabled.

Operating system: Manjaro Linux
CPU architecture: x86_64
Kernel: linux 5.13.19-2-MANJARO

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- libgcrypt 1.9.4-unknown

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: KDE
Windowing System: X11

**Comment by droidmonkey** [comment]
Yes this is a duplicate. Use the develop snapshot to get the code that was merged. Https://snapshot.keepassxc.org

**Comment by vikke1234** [comment]
do you happen to know when it will come to the stable version?

**Comment by droidmonkey** [comment]
2.7.0

**Comment by vikke1234** [comment]
oh, so it will be a while then I suppose

**Comment by droidmonkey** [comment]
We are aiming for this year, getting closer by the week. The snapshot works great, I've been running on develop branch for 6 months now.

**Comment by vikke1234** [comment]
alright cool, thanks for the info
