### ISSUE TITLE
KeepassXC does not start on system startup

### ISSUE THREAD

**Issue by kropkrop** [keepassxreboot/keepassxc#7021]
## Overview
Hello everyone,

like the title says: the option for starting after the system boot is checked but I always have to open KeepassXC manually. I'm currently using Zorin OS. Anyone else having this issue?

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION 2.6.6
Revision: 9c108b9
Distribution: Flatpak

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: Zorin OS (Gnome, I assume?)
Windowing System: ???

**Comment by phoerious** [comment]
This is most likely a problem with the Flatpak distribution. Please check with the maintainer of the Flatpak package.

**Comment by droidmonkey** [comment]
Probably similar to #7005
