### ISSUE TITLE
Manually insert favicons

### ISSUE THREAD

**Issue by enricogandini** [keepassxreboot/keepassxc#7023]
## Question
Is it possible to manually insert a favicon? I was not able to figure out how to do that, so I assume that it is not possible.

## Context
It would be nice to manually insert an icon for a given entry. It would be useful if both the default favicon search and the DuckDuckGo-powered favicon search failed. Or if an user wanted to insert a personal icon for a resource that is not online.

**Comment by droidmonkey** [comment]
It is done on the icons page when editing an entry.
