### ISSUE TITLE
DB is kept open if you close laptop whilst the save dialog is visible

### ISSUE THREAD

**Issue by sketchbuch** [keepassxreboot/keepassxc#7026]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

Normally if the laptop sleeps/suspends keepassxc requires the database password again, but if it suspended whilst the save dialog is visible (because you made changes to an entry) the database is still open if you awaken the laptop. Not sure if this is a bug or expected behaviour.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Modify an entry
2. Try and close the entry so that the save dialog appears
3. Close laptop
4. Open laptop - keepassxc is still useable and database is unlocked. Normally after reopening the laptop you need to enter the db password again.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

I was expecting to be asked for a pw again upon reopening the laptop

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

Keepassxc holds the db open waiting for you to decide upon a save action

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION 2.66
Revision: REVISION 9c108b9

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux (Ubuntu 20.04)
Desktop Env: Gnome
Windowing System: X11

**Comment by droidmonkey** [comment]
Thank you for the report, we are aware and this is a duplicate issue. The problem should be addressed in 2.7.0
