### ISSUE TITLE
Attachment Locked for Editing

### ISSUE THREAD

**Issue by raywood1** [keepassxreboot/keepassxc#7034]
*** PROBLEM ***

I open an Excel spreadsheet saved as an attachment. I get this:

> File in Use
>
> VcGbNB.Filename.xls is locked for editing
> by [username]
> Open 'Read-Only' or click 'Notify' to open read-only and receive notification when the document is no longer in use.

I don't get that when opening the database and the attachment in KeePass 2.48.1 x64. It just opens the spreadsheet as expected: I can edit and save it.

*** USING ***

KeePassXC - Version 2.6.2
Revision: e9b9582

Qt 5.15.1
Debugging mode is disabled.

Operating system: Windows 10 Version 2004
CPU architecture: x86_64
Kernel: winnt 10.0.19041

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.6

**Comment by phoerious** [comment]
This is kost likely fixed in the upcoming 2.7 release. You may want to try out a snapshot from https://snapshot.keepassxc.org
