### ISSUE TITLE
Seemingly there is no way to get autotype to log into the John Lewis website

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [keepassxreboot/keepassxc#7038]
## Overview

Seemingly there is no way to get autotype to log into the John Lewis website: having autofilled the username, no key press - but only moving the pointer with the mouse (or with a touchpad, etc.) seems to suffice to get one into the password box. This may be a limitation of the John Lewis website, but it would be nice were Keepassxc able to handle that site.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Try to create a working autotype entry for https://www.johnlewis.com/sso/browse/login

## Expected Behavior
Autofills that result in a login.

## Actual Behavior
The password appears in the 'email' (a.k.a. username) box, or else nowhere, depending on what combination of {tab} etc. once has specified.

## Context

KeePassXC - Version 2.6.6
Revision: 9c108b9

Qt 5.15.2
Debugging mode is disabled.

Operating system: Windows 10 Version 2009 [but I think the problem affects the Linux version of Keepassxc as well).
CPU architecture: x86_64
Kernel: winnt 10.0.19043

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
- libgcrypt 1.9.2-unknown

**Comment by droidmonkey** [comment]
Could not replicate, I autotyped {USERNAME}{TAB}{PASSWORD}{ENTER} without any problem

**Comment by LinuxOnTheDesktop** [comment]
Thank you. Seemingly it is not a KeePassXC problem but rather - I discover - a problem with the ['I don't care about cookies' Firefox extension](https://www.i-dont-care-about-cookies.eu/).
