### ISSUE TITLE
Option to show all entries in Global Autotype

### ISSUE THREAD

**Issue by PoisonFrog** [keepassxreboot/keepassxc#7042]
I think there should be an **option** to show all your database entries in global autotype instead of trying to match entries by window title or url. 

Also, there should be a way to use hotkeys for custom autotypes. For example: I press the global autotype hotkey and I select the login I want and if I press ENTER it will type {USERNAME}{TAB}{PASSWORD} because that is my default, but there are times I just want to type the username and not the password or just the TOTP. I should be able to configure a hotkey for just the username that could be SHIFT + ENTER and another hotkey for password only that could be ALT + ENTER for example. So if I press the global autotype hotkey and I select the entry and then I press SHIFT + ENTER it would type just the username.

The reason for the first suggestion is that title and url matching doesn't always work, sometimes it is a chore to deal with it and for some people it would be better to just show all entries and quickly search for the right one. The reason for the second suggestion is to save time and deal with websites that ask for username/email first and ask for password only after you identify yourself and to make it easier to deal with TOTP autotype.

**Comment by droidmonkey** [comment]
Already implemented will be in 2.7.0
