### ISSUE TITLE
UX: unsupported auto-type syntax prevents me from modifying any entry

### ISSUE THREAD

**Issue by melon-masou** [keepassxreboot/keepassxc#7046]
## Summary
I have a database-global Auto-Type sequence which works well in keepass. It uses a plugin-defined syntax provided by https://github.com/xatupal/AutoTypeSplitter, which is not supported by keepassxc.
What matters is that when I tried to edit any entry, keepassxc will validate the inherited Auto-Type sequence, which cannot pass obviously and told "The Syntax of your Auto-Type statement is incorrect!". It means that unless I modify the unsupported Auto-Type sequence, I am unable to edit any entries!

## suggestion
One of the three solutions will solve the problem:
(1)Do not validate the inherited Auto-Type sequence when editing entry, which should be validated in parent group.
(2)Provide an setting option to disable the validation
(3)Make the validation failure skippable while editing entries.

## Context
I think Auto-Type sequence is not a critical field for a keepass database. It should not affect the basic operation like just modify a password. And for me, this improvement makes keepassxc usable for me, while keeping old routines in other platform unchanged.

**Comment by droidmonkey** [comment]
This is fixed in the next version, you can ignore the validation check. You can use this now as a snapshot: https://snapshot.keepassxc.org
