### ISSUE TITLE
snap segfaults

### ISSUE THREAD

**Issue by twt2** [keepassxreboot/keepassxc#7047]
## Overview
Just upgraded to Ubuntu 21.10 "Impish" and couldn't find the impish build in the PPA so I removed old one (mistake!) and tried the snap. When I try to run snap I get a segmentation fault error.

[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. $ snap install keepassxc
keepassxc 2.6.6 from Jonathan White (keepassxreboot) installed
$
2. $ which keepassxc
/snap/bin/keepassxc
3. $ keepassxc
Gtk-Message: 18:00:24.217: Failed to load module "xapp-gtk3-module"

(keepassxc:20891): dbind-WARNING **: 18:00:24.227: Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-fGOyBEibMJ: No such file or directory

(keepassxc:20891): Gtk-WARNING **: 18:00:24.235: Theme parsing error: gtk.css:1428:23: 'font-feature-settings' is not a valid property name

(keepassxc:20891): Gtk-WARNING **: 18:00:24.239: Theme parsing error: gtk.css:3318:25: 'font-feature-settings' is not a valid property name

(keepassxc:20891): Gtk-WARNING **: 18:00:24.240: Theme parsing error: gtk.css:3780:23: 'font-feature-settings' is not a valid property name
Gtk-Message: 18:00:24.305: Failed to load module "canberra-gtk-module"
Gtk-Message: 18:00:24.307: Failed to load module "canberra-gtk-module"
Qt: Session management error: Could not open network socket
Fontconfig warning: FcPattern object weight does not accept value [40 200)
Segmentation fault
$ 

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.6.6
Revision: ?

[NOTE]: # ( Pick choices based on your environment )
Operating System: Unbuntu Linux 21.10 "Impish"
Desktop Env: Gnome
Windowing System: X11 or Wayland (segfault in both)

**Comment by twt2** [comment]
I saw snapcraft has a "2.7.0" build from April so I tried it, and the result was the same

I installed keepassxc snap in a 21.04 "Hirsute" virtualbox VM and it worked
I installed keepassxc snap in a 21.10 "Impish" virtualbox VM and it worked
SO presumably there's something very different about my (newly upgraded) Impish laptop

**Comment by droidmonkey** [comment]
https://github.com/keepassxreboot/keepassxc/issues/6329#issuecomment-805092856

**Comment by michaelk83** [comment]
You should be able to reinstall the hirsute PPA build. It doesn't have to match the release name, as long as all the dependencies are satisfied.

@phoerious Impish was officially released yesterday, so maybe time to update the PPA?
