### ISSUE TITLE
KeePassXC-Browser with Firefox as snap

### ISSUE THREAD

**Issue by Ravinou** [keepassxreboot/keepassxc#7053]
Ubuntu 21.10 **makes Firefox snap default** since the launch (4 days ago) : https://www.omgubuntu.co.uk/2021/09/ubuntu-makes-firefox-snap-default

I have KeePass installed as Snap too. KeePassXC-Browser doesn't work anymore. Is it possible to have a temporary fix ? (even manual tweak)

![Capture d’écran de 2021-10-18 11-06-23](https://user-images.githubusercontent.com/39600829/137703264-9cea6b25-cb29-4465-830d-aafb2f9244ca.png)

Ubuntu is very used so a lot of users are certainly in this case.
_And please, this is not the place for a discussion about snap is good or not..._

Thanks

**Comment by droidmonkey** [comment]
You'll have have to use Auto-Type. This is discussed in other issues.

**Comment by Mannshoch** [comment]
Something is coming.
https://www.omgubuntu.co.uk/2022/07/ubuntu-devs-fix-another-frustrating-firefox-snap-flaw
Firefox Snap beta and Gnome shell extension are working now. The whole thing is still beta.
