### ISSUE TITLE
Attachment overwritten without warning

### ISSUE THREAD

**Issue by sts10** [keepassxreboot/keepassxc#7054]
## Overview
When attaching a new file as an attachment with the same name as a current attachment, old attachment is overwritten with warning.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Attach foo.txt to an entry
2. Create a new file called `foo.txt`
3. Attach new `foo.txt` to the entry.

## Expected Behavior
I was expecting a dialog warning that original attachment would be overwritten, and a choice of what I want to do.

## Actual Behavior
Appears that old file is overwritten without any dialog or information.

## Context

My story here is that I have a service that I pay for yearly. I get a confirmation document (receipt) each year. I like to collect each receipt in my KeePass database. Unfortunately, the file name of the receipt is always the same each year. So it's easy to overwrite the 2021 document with the new 2022 document, which I just did.

## Debug info
KeePassXC - Version 2.6.6
Revision: 386b79a

Qt 5.15.2
Debugging mode is disabled.

Operating system: macOS Mojave (10.14)
CPU architecture: x86_64
Kernel: darwin 18.7.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
- libgcrypt 1.9.3

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS

**Comment by libklein** [comment]
Should we just address this with a simple confirmation dialog?

**Comment by droidmonkey** [comment]
Yup
