### ISSUE TITLE
Add ability to make passphrases CamelCase

### ISSUE THREAD

**Issue by oscardssmith** [keepassxreboot/keepassxc#7056]
## Summary
currently passphrases are generated likethiswithnocleardelimination. This is harder to read than other formats that have more clear word delimiters. The word separator field gives a mechanism to do something like this (ie snake_case), but it isn't the easiest to type.

I think the place to do this is a checkbox below the word separator field of the passphrase generator dialogue.

**Comment by droidmonkey** [comment]
This is already a feature #3172

**Comment by oscardssmith** [comment]
Apologies for the dup. my google-fu failed me.
