### ISSUE TITLE
Clicking password in preview panel switches to group view

### ISSUE THREAD

**Issue by wolframroesler** [keepassxreboot/keepassxc#7061]
## Overview

Clicking an entry's password in the preview panel switches the preview panel to "group view", hiding the entry details.

## Steps to Reproduce

1. Click an entry
1. Click the password in the preview panel

## Expected Behavior

The preview panel should continue displaying the entry.

## Actual Behavior

The preview panel displays the group the entry is in.

![simplescreenrecorder-2021-10-20_13 19 11](https://user-images.githubusercontent.com/25565229/138084483-99f46b4b-d50a-41cb-9cab-6d1cca05082a.gif)

## Context

KeePassXC - 2.6.3
Build Type: Snapshot
Revision: 3ecc0c7

Qt 5.15.2
Debugging mode is disabled.

Operating system: Pop!_OS 21.04
CPU architecture: x86_64
Kernel: linux 5.13.0-7614-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.17.3

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: Gnome
Windowing System: X11

**Comment by droidmonkey** [comment]
You are on an old version that looks self built. Very old actually since you are using botan and it says 2.6.3.

**Comment by wolframroesler** [comment]
Self-built, yes, but on the current develop, pulled today. The HEAD commit is:

```
$ git show HEAD
commit 3ecc0c70e233dc3353cd1ff202b19cfb06b5b508 (HEAD -> develop, upstream/develop)
Author: Andreas Schneider <asn@cryptomilk.org>
Date:   Wed Oct 13 15:15:59 2021 +0200

    cmake: Fix position independent code with LTO
    
    Fixes #7044
```

cmake options are `-DWITH_XC_ALL=ON -DCMAKE_BUILD_TYPE=Release`. I was using `-DOVERRIDE_VERSION` based on `git describe`. Built it again without the version override and it now says

```
KeePassXC - Version 2.7.0-snapshot
Build Type: Snapshot
Revision: 3ecc0c7
```

No idea why what Botan is or why it's being used. :)

**Comment by droidmonkey** [comment]
I cannot replicate this on Windows 10 or macOS.

**Comment by droidmonkey** [comment]
This PR introduced the problem: https://github.com/keepassxreboot/keepassxc/pull/7041

**Comment by gabeweb** [comment]
Hi, I'm on Windows 10 and Ubuntu.

The latest "snapshot" versions have the behavior described previously, when clicking on the preview panel it automatically shows the list of entries, it does not allow you to do anything, or select the text of the notes in the panel, nor open the files attachments.

In order to do that I then have to double click on the entry (edit) and select the text of the notes or open the attached files when I need it.
