### ISSUE TITLE
Autotype does not work with OpenVPN

### ISSUE THREAD

**Issue by funnym0nk3y** [keepassxreboot/keepassxc#7062]
## Overview
When using the AutoType feature with KeepassXC the selection of the entry works just fine, but when selectin the entry nothing gets typed into the corresponding fields. This is specific to OpenVPN as it works with Netflix. 

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Prepare an entry to match the window name. 
2. Select `Alt + Shift + A` as global shortcut
3. Run OpenVPN connect
4. Select field username
4. Press shortcut
5. Choose entry

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Credentials get typed

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Nothing happens. The selection dialog closes, but nothing is typed. 

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.6
Revision: 9c108b9

Qt 5.15.2
Diagnosemodus ist deaktiviert.

Betriebssystem: Windows 10 Version 2009
CPU-Architektur: x86_64
Kernel: winnt 10.0.19043

Aktivierte Erweiterungen:
- Auto-Type
- Browser-Integration
- SSH-Agent
- KeeShare (bestätigtes und unbestätigtes Teilen)
- YubiKey

Kryptographische Bibliotheken:
- libgcrypt 1.9.2-unknown

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows

**Comment by droidmonkey** [comment]
Please try our snapshot build: https://snapshot.keepassxc.org 

You can download the portable version to not impact your currently installed version. Make sure your installed keepassxc is exited prior to testing.

**Comment by funnym0nk3y** [comment]
The issue still persists with the latest snapshot.

**Comment by nagromc** [comment]
Please note it _does_ work with OpenVPN **2.x**, but does **not** with OpenVPN **3.x**

**Comment by droidmonkey** [comment]
Then this seems like an open VPN bug to me. Make sure the text field is focused when attempting Auto-Type.

**Comment by droidmonkey** [comment]
Worked for me testing with 2.7.0 and OpenVPN 3.3.x
