### ISSUE TITLE
Writing the database failed. Destination file exists

### ISSUE THREAD

**Issue by demichev78** [keepassxreboot/keepassxc#7063]
## Overview
KeepassXC 2.6.6 is installed as a downloadable package. 
OS: Windows 10
Database changes are saved perfectly normal once a database is open, however, after some time (could be several hours) and windows wake ups the application keeps saying that changes cannot be saved because destination file exists.
Made an attempt to save to a new destination (e.g. \Documents or \Desktop windows folder), but the result is the same.
Once KeepassXC app is restarted and database is reopened, all the changes can be saved to an existing database with no issues. This means that the app has adequate permissions to write.

## Steps to Reproduce
1.  Open a database from an existing file. E.g. c:\KeepassDatabases\personal.kdbx
2. Keep KeepassXC running for 6 hours. Make sure Windows can fall asleep during this period
3. Wake up windows. 
4. Unlock the database in KeepassXC
5. Introduce a change to the database
6. Make an attempt to save changes to c:\KeepassDatabases\personal.kdbx

## Expected Behavior
- Database changes should be saved to c:\KeepassDatabases\personal.kdbx

## Actual Behavior
- An error message is displayed by KeepassXC: Writing the database failed. Destination file exists.  c:\KeepassDatabases\personal.yauWuWY
- Making an attempt to save to Documents folder produces the same message but difference path:  Writing the database failed. Destination file exists.  c:\....\personal.yauWuWY
- Making an attempt to save to Desktop folder is a success and results in no exceptions thrown

## Context
Saving the changes to the database after keepassxc running for several hours

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.6
Revision: 9c108b9

Qt 5.15.2
Debugging mode is disabled.

Operating system: Windows 10 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.19043

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
- libgcrypt 1.9.2-unknown

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 10
Desktop Env: Windows 10
Windowing System: Windows 10

**Comment by droidmonkey** [comment]
This is a problem with your computer setup. Probably permissions related or other processes holding a lock on files (OneDrive sync?). This is not a keepassxc problem.

**Comment by dvschwab** [comment]
I am having the same problem on Ubuntu 22.04 (jammy). Every time, I have to create a new database. I don't know if this is a lock file issue or not, but I've re-installed it several times, and it keeps happening. It probably is a problem with my setup, but all I did was run the installer like I was supposed to, so the setup should be correct. I'm using KeypassXC 2.7.6.
