### ISSUE TITLE
Pick window where AutoType has to happen

### ISSUE THREAD

**Issue by MKobek** [keepassxreboot/keepassxc#7066]
## Summary
We need the feature to pick the application / windows manually in which autotype will be executed. Windowtitles do not work in multi-VDI and remote desktop sessions.

## Context
While we work with multiple VDI (Citrix and RDS) and within them with RDP and SSH connections again, the AutoType feature based on Windows Titles or simply the last window does not work. 1Password on the other hand, does present a windows with a list of all windows so a user can decide, into which Username and Password has to be pasted/executed.

We also consider to invest into a freelance developer to get that integrated one way or another but we do not wan't to build a Frankenstein version for our purpse. We would be appreciated if that could be integrated as a feature or plugin so it becomes part of the final product and is available to everybody with similar requirements. 

In 1Password it does look like that, separated by username and password:
![Unbenannt](https://user-images.githubusercontent.com/67360178/138340658-65c19fdc-920c-48f0-99a1-33b542c39e71.PNG)

**Comment by droidmonkey** [comment]
We have made significant improvements to Auto-Type recently. Please try snapshot build with the new "search database" feature: https://snapshot.keepassxc.org 

As for this request, I am not sure what you are asking for? We already support arbitrary window matching patterns which should work for your purposes. If you are trying to find windows that are within a VDI or Citrox session, well that is impossible from the host computer. 

Please review our Auto-Type documentation for details: https://keepassxc.org/docs/KeePassXC_UserGuide.html#_auto_type

**Comment by droidmonkey** [comment]
This also appears to duplicate #7037 request.

**Comment by hifi** [comment]
Definitely looks like #7037 is exactly this. It should be fairly flexible what it can do and reuses existing UI idioms we have.

I was quite verbose in that how it should be implemented so if you have spare developer resources I'd be happy to mentor the work at least partially.

**Comment by droidmonkey** [comment]
Closing this as duplicate
