### ISSUE TITLE
CERTIFICATION CSPN/HDS

### ISSUE THREAD

**Issue by legolass73** [keepassxreboot/keepassxc#7067]
Hello,

I am a hospital IT technician, we want to deploy KeepassXC to our agents because it seems more pleasant to use (interface more beautiful because less barbaric / aggressive than that of Keepass). Since we are in a hospital, we have confidential health data and we want to use HDS / CSPN certified software.
therefore I would like to know if you have planned that KeepassXC evening CSPN certified by ANSSI (ssi.gouv.fr) and / or HDS (esante.gouv.fr) so that hospitals and / or public or even private institutions can use KeepassXC ensuring the safety of the product.

**Comment by droidmonkey** [comment]
HDS is mainly for data storage and is not applicable to locally hosted applications like KeePassXC. You store your database in your own HDS approved storage system. 

CSPN seems more appropriate, but we have no intention of getting any certification of this nature. These certs generally cost a lot of money, require constant reapplication, and are generally incompatible with open source software. The equivalent cert for the US would be a FIPS certification.

Do you have the list of requirements for CSPN? It was hard to find for me. Generally open source products will just declare they are in compliance or meet the standards and not actually obtain the designation.

**Comment by legolass73** [comment]
Hello,

All the information is available at this address in case:
https://www.ssi.gouv.fr/administration/produits-certifies/cspn/les-procedures-formulaires-et-methodologies/
there are documents in French but also in English.

from what I read, the CSPN certification are valid for a given version, after nothing prevents requesting a new certification for a new version.

I have absolutely no idea the price of such certification.
I understand very well that open source apps are generally incompatible with this kind of certification.

**Comment by droidmonkey** [comment]
Geeeeeezzzz, just an example case:

> CSPN is a pretty lightweight certification process that lasts up to 8 weeks and costs between 25 thousand and 35 thousand euros.

https://www.redalertlabs.com/blog/national-security-certifications-for-it-iot-products-don-t-get-lost#:~:text=CSPN%20is%20a%20pretty%20lightweight%20certification%20process%20that,based%20on%20the%20standard%20created%20by%20the%20ANSSI.

I'll take a glance at the cert requirements and see if we have any glaring problems.

**Comment by droidmonkey** [comment]
Closing as we won't be doing anything with this.
