### ISSUE TITLE
cannot decrypt keepass db

### ISSUE THREAD

**Issue by SynapseScribe** [keepassxreboot/keepassxc#7070]
keepassxc 2.6.2 e9b9582 x64 on ubuntu 21.04 x64
keepass 2.49 x64 on windows 11 x64 21H2 22000.258

To reproduce:
1. create a db with keepass (on windows) with password + key file
2. try to decrypt in ubuntu with keepassxc (installed by apt install keepassxc) using password+key file

I get error:
Error while reading the database: Invalid credentials were provided, please try again.
If this reoccurs, then your database file may be corrupt.

**Comment by droidmonkey** [comment]
Upgrade to 2.6.6, you are probably using the new key file format.

**Comment by SynapseScribe** [comment]
2.6.2 is the one present in the official ubuntu repo. If the bug was fixed later, maybe the repo should be updated to use a more recent version

**Comment by droidmonkey** [comment]
We don't control what is in the ubuntu repo. You can use our ppa, download the appimage, or use the snap. This isn't a bug, KeePass introduced a new key file format and we supported it in a newer version of KeePassXC.
