### ISSUE TITLE
Broken build due to a comparison of integers of different signs

### ISSUE THREAD

**Issue by xvallspl** [keepassxreboot/keepassxc#7072]
## Overview
The develop branch can't be built due to a comparison of integers of different signs in /src/keys/drivers/YubiKeyInterfacePCSC.cpp. 

## Output

keepassxc/src/keys/drivers/YubiKeyInterfacePCSC.cpp:74:16: error: comparison of integers of different signs: 'int' and 'unsigned int' [-Werror,-Wsign-compare]
        if (rv == SCARD_E_SERVICE_STOPPED) {
            ~~ ^  ~~~~~~~~~~~~~~~~~~~~~~~

## Context

Error related to the [winscard.h](https://github.com/rhvall/SmartCard/blob/master/OtherSources/Libraries/libiBSReader/winscard.h) header.

The rv variable represents a return value from  [SCardIsValidContext(context)](https://github.com/rhvall/SmartCard/blob/d9ba1ff2d0be1858c72a25e771b4b424a0f2b109/OtherSources/Libraries/libiBSReader/winscard.h#L49), whose [return type is int](https://github.com/rhvall/SmartCard/blob/d9ba1ff2d0be1858c72a25e771b4b424a0f2b109/OtherSources/Libraries/libiBSReader/wintypes.h#L34) and the line causing the problem is simply a return value check against an error code. There are several ones in the same function, but only this one raises the different sign integer comparison error when [all the error codes are defined the same ](https://github.com/rhvall/SmartCard/blob/d9ba1ff2d0be1858c72a25e771b4b424a0f2b109/OtherSources/Libraries/libiBSReader/winscard.h#L100) and the define does not declare unsigned or signed value.

Operating System: macOS

**Comment by xvallspl** [comment]
I could open a PR with a patch casting one of the two members of the comparison to the type of the other, but I see that as a hack that doesn't fix the underlying issue (which I have no idea how to deal with)

**Comment by droidmonkey** [comment]
I fixed it by declaring `RETVAL rv = SCardIsValidContext` instead of using `auto`. This worked on all platforms. I think there is a bug in the pcsclite.h on macOS... every other platform explicitly casts the error codes to the return value of the functions except on macOS.

I committed the fix directly to develop branch.
