### ISSUE TITLE
Rename Database Menu --> File on Mac

### ISSUE THREAD

**Issue by elharo** [keepassxreboot/keepassxc#7074]
At least on the Mac, users expect applications to have a File menu to the right of the application menu. This is part of Apple's human interface guidelines: https://developer.apple.com/design/human-interface-guidelines/macos/menus/menu-bar-menus/#file-menu

Furthermore, seriously consider renaming and removing "database" in the UI to "file". Database is a programmer and implementation centric term. It confuses and scares non-technical users. "File" isn't perfect, but it's at least somewhat standard and less scary.

E.g. New Database... should be "New...". "Open Database..." should be "Open...". This is all in keeping with standard Mac UI behavior and guidelines. It might be a good idea for other platforms as well, though I'm not as familiar with them.

**Comment by droidmonkey** [comment]
No thank you, the names are there for a reason.
