### ISSUE TITLE
Rename Entry to Account

### ISSUE THREAD

**Issue by elharo** [keepassxreboot/keepassxc#7075]
"Database" is bad for non-technical users. "Entry" is awful. Non-technical users do not understand this term. It exposes implementation details in the UI. I suggest using the word "Account" (localized as needed) instead, which more closely matches user mental model of passwords.

**Comment by droidmonkey** [comment]
No thank you, these are named for a reason.

**Comment by michaelk83** [comment]
Not every entry is necessarily an account. See #863.
