### ISSUE TITLE
Add standard Edit menu 

### ISSUE THREAD

**Issue by elharo** [keepassxreboot/keepassxc#7076]
At least on the Mac, and likely on other platforms as well, users expect to find an edit menu with Undo, redo, cut, copy, paste, and delete menu items: https://developer.apple.com/design/human-interface-guidelines/macos/menus/menu-bar-menus/#edit-menu

This is important. UI research has shown that many, probably most, users do not know keyboard shortcuts like Command/Ctrl-X and never use the context (right-click) menu. Possibly this can be combined with a renamed Entries menu.

**Comment by droidmonkey** [comment]
We have no purpose for an edit menu. These functions are found in the respective menus of what you are interacting with.
