### ISSUE TITLE
Cleanup new database encryption settings tab

### ISSUE THREAD

**Issue by elharo** [keepassxreboot/keepassxc#7077]
This dialog is unnecessary and confusing to most non-technical users. Hide it behind an advanced settings button and that's one less step for people to set up a new database. 

![image](https://user-images.githubusercontent.com/1005544/138557400-fc039f7f-7c8e-474d-ba3d-b92a57d2155d.png)

**Comment by droidmonkey** [comment]
This dialog should stay since it is important step, but we can definitely reduce it to just the encryption time setting. Hide everything else behind the advanced settings. Creating a database is a very rare occasion and I'm not concerned by the number of steps.

**Comment by michaelk83** [comment]
Minor nitpick: there's a space missing after some of the punctuation in this screenshot: after "encryption settings.", after "Don't worry,", and after "more protection,".

**Comment by droidmonkey** [comment]
Being addressed by #6513
