### ISSUE TITLE
Rename Title to Site

### ISSUE THREAD

**Issue by elharo** [keepassxreboot/keepassxc#7078]
In this dialog "Title" likely and unneccessarily exposes a field name from the underlying database into the UI:

![image](https://user-images.githubusercontent.com/1005544/138557608-6e760032-24dd-414e-8b6f-5db9b70513bd.png)
 
A less generic and more context appropriate word would work better here. "Site" or "Site Name"  might work. Possibly there's a better one.

**Comment by michaelk83** [comment]
As with #7075 , not every entry corresponds to an online account. There could be entries for offline applications and many other things. Title is used as a general user-facing identifier.
