### ISSUE TITLE
Generate Password Icon is inobvious

### ISSUE THREAD

**Issue by elharo** [keepassxreboot/keepassxc#7079]
I had to look hard to find this. I guess it's supposed to be a die? It's too small to really tell, not that making it larger would make it that much better. There should be a button with the label "Create password." The UI principle in play here is to prefer words to icons. https://ux.stackexchange.com/questions/1795/when-to-use-icons-vs-icons-with-text-vs-just-text-links 

![image](https://user-images.githubusercontent.com/1005544/138557722-b1b0be6e-6570-4f87-8252-eb702718d635.png)

**Comment by elharo** [comment]
I could file a similar bug for the reveal password icon to the right.

**Comment by droidmonkey** [comment]
That particular dice icon is pretty bad, I agree. Words would be a bad choice in this case since it clutter the display.

**Comment by michaelk83** [comment]
Agree that the dice icon can be hard to discover for a new user (related to #6323), but replacing it with a text button would just add unnecessary and ugly clutter. A better suggestion might be to show a popup hint next to it, when creating a new entry: "Click here to create a password."

The eye icon is standard for hidden fields at least in several variants of KeePass, and likely in many other apps; as well as online.

**Comment by hifi** [comment]
Would a round arrow be better, like a refresh icon?

**Comment by michaelk83** [comment]
The dice is consistent with the global password generator. Refresh makes some sense when renewing passwords, less so when creating the first one. Even when renewing, this opens the generator dialog, so "refresh" doesn't seem quite appropriate. Usually you'd expect refresh to be something quick with no further user interaction. But I think the bigger issue is visibility.

Another idea, may be an inline text link or button inside the field:
`Password: [.....................| Generate | <o>]`
This would improve both visibility and clarity without adding too much external clutter.

**Comment by michaelk83** [comment]
Or maybe just replace the whole field with a Generate button when there is no password yet, and with a Renew button when it's about to expire or already expired (same button, just different label). But there should still be some way to enter it manually for legacy passwords and things like PIN codes and physical lock combinations.

Maybe with an edit icon for the manual entry, which would just replace the buttons with the field again:  
`Password: [Generate][✎]` (new)  
`Password: [  Renew  ][✎]` (expired)

**Comment by droidmonkey** [comment]
At this point changing the icon might be more harmful then leaving it alone. We have great documentation and hovering over it provides a tooltip. Going to go with a wontfix on this one for now.
