### ISSUE TITLE
On the Mac "New" file is Command-N, not Command-Shift-N

### ISSUE THREAD

**Issue by elharo** [keepassxreboot/keepassxc#7081]
![image](https://user-images.githubusercontent.com/1005544/138557969-260ab51c-ad47-445e-9d5e-bc09155fbd8d.png)

Command-N is used for New Entry but that's contrary to Mac guidelines and user expectations. Command-N creates a new document, not a new entry in an existing document. 

https://developer.apple.com/design/human-interface-guidelines/macos/user-interaction/keyboard/

**Comment by droidmonkey** [comment]
This is on purpose.

**Comment by michaelk83** [comment]
@droidmonkey is very terse, but to explain: creating entries (and otherwise working with entries) is by far much more common in a password manager than creating databases. You can think of entries as the main documents here, and the database as a *collection* (or directory) of documents.
