### ISSUE TITLE
macOS 10.15 Catalina: Yubikey 5 NFC is not detected

### ISSUE THREAD

**Issue by Vertux** [keepassxreboot/keepassxc#7082]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
I am running KeePassXC for many years on MacOS without issues. Since I bought a new YubiKey 5 NFC, KeePassXC does not detect the the YubiKey anymore (Hint: It works fine with my old YubiKey 4). All other applications like YubiKey Manager, Bitwarden etc. got no issues with the new YubiKey 5 NFC, so it is not broken.

As you can see it is added under "Input-Monitoring". I have reinstalled it a couple of times. Restarted the iMac. And I have used different USB-Ports, but without success. It is pretty weird, that the YubiKey 4 works fine.
<img width="742" alt="Bildschirmfoto 2021-10-24 um 12 05 04" src="https://user-images.githubusercontent.com/10457918/138589657-a72e99b4-31a6-4e8f-b504-5c06e374c149.png">
## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Start KeePassXC
2. Open a database
3. The hardwarekey field is unpopulated, a reload does not help
<img width="651" alt="Bildschirmfoto 2021-10-24 um 12 18 54" src="https://user-images.githubusercontent.com/10457918/138589791-a88fcd03-cf84-451f-a5e6-8716ce8a50cd.png">

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
The YubiKey 5 NFC is detected by KeePassXC

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
The YubiKey 5 NFC is NOT detected by KeePassXC (but by other applications)

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - v2.6.6
Revision: Revision: 386b79a

[NOTE]: # ( Pick choices based on your environment )
Operating System: MacOS 10.15.7

**Comment by droidmonkey** [comment]
Did you configure a slot for HMAC-SHA1? Does the activity light blink at all when you press refresh? Are you using it as a USB or NFC?

**Comment by Vertux** [comment]
> Did you configure a slot for HMAC-SHA1? Does the activity light blink at all when you press refresh? Are you using it as a USB or NFC?

1.  You make me thinking. I was pretty sure that both keys are properly configured, but if I do a Challenge-Response check with the tools in the YubiKey Personalization Tool, it does not work. The interesting question is: Why does both YubiKeys work with KeePassXC on my other PCs/Laptops? Unfortunately there is no way to check how the slots are configured/programmed.
2. It lights up for 3sec and then it turns off again, it does not blink.
3. I use it as USB device on an iMac

**Comment by droidmonkey** [comment]
If the yubikey 5 works fine on the other computer then that is strange. This may also be a bug in the macos implementation of the ykpers library, but that is not likely.

**Comment by Vertux** [comment]
> If the yubikey 5 works fine on the other computer then that is strange. This may also be a bug in the macos implementation of the ykpers library, but that is not likely.

If I have time I am gonna test both YubiKeys on a Windows PC. I am curious, if I get different results there.

**Comment by droidmonkey** [comment]
Try this again with 2.7.0
