### ISSUE TITLE
Hotkeys for alternative Type Sequences in Global Autotype

### ISSUE THREAD

**Issue by PoisonFrog** [keepassxreboot/keepassxc#7084]
The new Global Autotype in KeePassXC 2.7 is great, but it is lacking hotkeys for alternative type sequences and I believe this feature would improve convenience and speed.

Right now we can select/search for the entry we want to autotype and press ENTER and it will perform the default autotype sequence, which is the expected behavior, but it would be nice to be able to use a shortcut like SHIFT/ALT/META + ENTER to type just the {USERNAME}, {PASSWORD} or {TOTP} instead of the default sequence. 3 alternative type sequences would be enough for almost all use cases in my opinion. 

This feature would be very useful for websites that ask for email/username before asking for passwords and for TOTP autotype. We can do this in KeePassXC 2.7 using the mouse but it is definitely slower and inconvenient for keyboard centric people.

**Comment by droidmonkey** [comment]
This is a duplicate request. Within the new Auto-Type selection dialog you can press CTRL+1/2/3 to type just username, password, and totp respectively.
