### ISSUE TITLE
Cancel auto-type when target window changes

### ISSUE THREAD

**Issue by dwettstein** [keepassxreboot/keepassxc#7085]
## Summary
The original KeePass application has some options to cancel auto-type (sending) when the target window changes.

![image](https://user-images.githubusercontent.com/412133/138877899-3cca3768-6cb6-45e0-afac-d1cbfd8005e5.png)

## Context
IMO, this is an important feature to avoid leaking your password after a unwanted/unexpected window change. I wouldn't even add a setting about it, but do that per default.

**Comment by droidmonkey** [comment]
We don't cancel when just the title changes on the same window you are typing into because it has unintended side effects. This is discussed elsewhere.

**Comment by droidmonkey** [comment]
I can't find the previous discussion, but we aren't going to implement that control since it can cause problems with windows that randomly change their title (like adding an asterisk for unsaved changes) or browser windows where the website is changing the title constantly.

**Comment by dwettstein** [comment]
I agree with you regarding the title change. However, when the whole window changes, auto-type should cancel.
I haven't found any issue or discussion regarding this, thus I created this one.

**Comment by droidmonkey** [comment]
We already cancel Auto-Type when the whole window changes.

**Comment by dwettstein** [comment]
Oh, it's my fault, sorry. I thought I observed it differently. However, I have just verified that auto-type is cancelled when the window changes. Thanks! 👍
