### ISSUE TITLE
Autofill from Code as well

### ISSUE THREAD

**Issue by NN---** [keepassxreboot/keepassxc#7086]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
Several websites have user , password and code.
KeePassXC is able to fill user and password but doesn't have an ability to fill the code from additional attributes.

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )

```
User: 
[____]

Pass:
[____]

Code:
[____]
```

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )

**Comment by JohnLGalt** [comment]
Check out the User Guide: Advanced Entry Options:

https://keepassxc.org/docs/KeePassXC_UserGuide.html#_advanced_entry_options

As well as the Auto Type section:

https://keepassxc.org/docs/KeePassXC_UserGuide.html#_auto_type

**Comment by NN---** [comment]
Thanks
I'll check this.

**Comment by droidmonkey** [comment]
Yup this is already possible. Also the browser extension allows this too, see our FAQ: https://keepassxc.org/docs/#faq-browser-string-fields

**Comment by NN---** [comment]
@droidmonkey Thank you very much !
It took a while to use this feature correctly.
The auto type didn't work without page refresh.
