### ISSUE TITLE
Add Repeat Password On Blind Entry Inside of Generate Password Dialog

### ISSUE THREAD

**Issue by webdawg** [keepassxreboot/keepassxc#7087]
## Summary
https://github.com/keepassxreboot/keepassxc/issues/5168

## Context
I understand why you locked that thread.  I don't think someone chiming in talking about forking because of a feature request argument is that great.  My apologies for that on behalf of anyone.  Opensource coding is a thankless job.

I think the use case for the double password entry was for when you want to manually enter a password in a database, but not screen-share it?  How is this a bad use case?

It seems double entry has been removed from the password generation completely, and the Require password repeat when visible does nothing?

I actually came here looking because one of my users hated the double entry 'requirement'.  Saw this thread, and I am now submitting this.

Can you add a 'manual' or 'blind' tab to "Generate Password' that can/cant be viewed, but makes you enter the password twice?

I use very long drive encryption passphrases to unlock systems during cold boot, and I have some use cases where I would NEVER want them to be see on any active screen, but would want to know that they were stored correctly inside of keepass.

I am willing to bet there are people in this world that take a few mins to enter a password.  Very, Very long.

I saw the complaints about forcing people to enter passwords twice (other ancient threads), and I can see how being able to turn that off, or in this implementation disabled all together is a good choice.  I can also see how it can clutter the UI.

I still believe that it is a feature that is 100% valid.  To answer a question that was brought up on the 'bug' thread:

I would rather attempt to enter my super long password 50 times in the dark, and verify that it was manually entered correctly by software, then reveal it.

I think people with disabilities may appreciate the implementation method I am talking about also.  I know some people have trouble typing correctly, and still would like to enjoy this feature, and the use case I am describing.

I know that keepass is not an end all be all, but combined with the proper end point scenario, this feature still has merit.

**Comment by droidmonkey** [comment]
Seriously?
