### ISSUE TITLE
Attributes are missing (пропали атрибуты) 

### ISSUE THREAD

**Issue by JediXKnight** [keepassxreboot/keepassxc#7088]
## Overview
When activating the Russian language in the program, my records began to display attributes incorrectly. This happened a few updates ago.
Either there is no information at all, or there is but a part and it is not displayed as a column. Most of the entries simply don't have it until I turn on English.
![image](https://user-images.githubusercontent.com/26658085/139084458-36a06e1f-50c4-4e0f-816d-a8b6940e08b8.png)
The fact that the problem is solved by switching to English, I noticed only now

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Go to settings set the language to Russian or system default
2. To see that the records have lost attributes

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
![image](https://user-images.githubusercontent.com/26658085/139087424-848a20ab-7f23-4663-bebe-7e1e0b638157.png)

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
![image](https://user-images.githubusercontent.com/26658085/139087334-8d538e87-9534-4acc-af95-1297513dbc69.png)
![image](https://user-images.githubusercontent.com/26658085/139087257-d5d780de-65a5-47fc-9314-035c643f5af6.png)

## Context
[NOTE]: # ( Give us any additional information you may have. )
The difference is whether to create attributes in a new database or in a new record, they are not displayed at all in Russian, in old records you can see what happens in the screenshots.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.6
Revision: 9c108b9

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 10 Pro x64

**Comment by droidmonkey** [comment]
Most likely a translation error.

**Comment by droidmonkey** [comment]
No longer an issue on 2.7.0
