### ISSUE TITLE
Having Auto-Type mother/micromanage me with "This Auto-Type command contains very slow key presses.  Do you really want to proceed?" breaks the intended Auto-Type functionality.

### ISSUE THREAD

**Issue by Entreprenerdz** [keepassxreboot/keepassxc#7092]
I had found some documentation from the keepass.info website (not sure if connected or not) about how one could remove the browser plug-in completely by using auto-type.  I thought it was far fetched but ran through an example and by golly, it worked!  So with the ability to remove yet another potential vulnerability from my attack surface, I moved to implement all web logins as Auto-Types.

Until I hit one web site that is username, submit, password, submit, TOTP, submit, where the last can take up to 3 seconds to load.  So I put in the longer delay and now when I hit the auto-type hotkey, I get this.
<img width="415" alt="image" src="https://user-images.githubusercontent.com/17835969/139245787-cbfbafc6-f901-4df8-999a-40629bffbf3d.png">

which completely stops the auto-type process (given that I have to switch to it and answer) and it won't then switch back to my browser and do the auto-typing.

If you're concerned about a 3 year delay, I'd say 60 seconds would be reasonable, but for increased usability, set the max at 10 minutes!  I guarantee you that anyone that makes a mistake once, will never make that mistake and shouldn't need confirmation windows popping up to verify.  Checkbox to disable at the very least.

And while you're at it, do the same for Delete.  With "Take a backup before updating" and personal backups, I would totally utilize a checkbox to disable the verification, which in my opinion is for a n00b user, and they're all sucking their thumbs and using BitWarden cuz it doesn' t hurt their brain like KP does.

Thanks.  Love the product.  (rich notes box please.  would love to paste images in there instead of save/attach/delete everytime)

**Comment by droidmonkey** [comment]
You used the wrong delay (blame keepass original for this shit). Use {DELAY ##} to add a pause in running. {DELAY=##} changes the delay between typing each character. 

Read more here https://keepassxc.org/docs/KeePassXC_UserGuide.html#_configure_auto_type_sequences
