### ISSUE TITLE
Make links in "Notes" clickable

### ISSUE THREAD

**Issue by oliver-gramberg** [keepassxreboot/keepassxc#7093]
KeePass 2, maybe in cooperation with one if its plugins, recognizes URLs in the "Notes" field and makes them into links: shown in blue and underlined, clickable.

**Comment by droidmonkey** [comment]
This is already a feature within the entry preview widget. I doubt we will add this to the entry editing widget since it would make editing more difficult.

**Comment by Anubis-105** [comment]
[droidmonkey](https://github.com/droidmonkey) commented [on 28 Oct 2021](https://github.com/keepassxreboot/keepassxc/issues/7093#issuecomment-953976912)
> This is already a feature within the entry preview widget.

How to use this?
Do you need to format this in a certain way?

Is there also the possibility to use referencing links in the notes as it is possible with KeePass?

Screenshot:
Hyperlink (URL) number [1] works.
Hyperlink (URL) number [2] does not work.

![KeePassXC-Notes-Clickable](https://user-images.githubusercontent.com/49913906/160547850-b0ca59c8-1708-4359-aa12-765794a3fa23.png)

There are other articles about this:
https://github.com/keepassxreboot/keepassxc/issues/7093
https://github.com/keepassxreboot/keepassxc/issues/3511
https://github.com/keepassxreboot/keepassxc/issues/5369
https://github.com/keepassxreboot/keepassxc/issues/1057
