### ISSUE TITLE
Autostart Windows not working

### ISSUE THREAD

**Issue by cp-deha** [keepassxreboot/keepassxc#7094]
In KeyPassXC Settings, the option "Automatically launch KeePassXC at system startup"
is not working as expected.

## Steps to Reproduce
1. Install KeyPassXC new on same Windows version
2. Enable/Disable/Enable setting as deescribed.
3. You will never see KeePassXC coming up on system startup.

## Expected Behavior
After system startup open window like Skype, Mattermost, aso.

## Actual Behavior
KeePassXC needs to be started manually.
Not starting automatically as expected neither with system startup or latest with browser startup.

## Context
No further context.

KeePassXC - Version 2.6.6
Revision: 9c108b9

Qt 5.15.2
Diagnosemodus ist deaktiviert.

Betriebssystem: Windows 10 Version 2009
CPU-Architektur: x86_64
Kernel: winnt 10.0.19043

Aktivierte Erweiterungen:
- Auto-Type
- Browser-Integration
- SSH-Agent
- KeeShare (bestätigtes und unbestätigtes Teilen)
- YubiKey

Kryptographische Bibliotheken:
- libgcrypt 1.9.2-unknown

**Comment by JohnLGalt** [comment]
Can you verify that you have not set it to not start up (aka disabled) in the Startup tab of Task Manager (Windows 10+)?

**Comment by cp-deha** [comment]
In the TaskManager, the application is listed and enabled.
Would it help to enable the debug logging? How to enable the debug logging?

**Comment by droidmonkey** [comment]
If that is the case then make sure you haven't enabled minimize on launch and minize to tray settings. It could be starting and being hidden. This isn't a keepassxc bug if it is enabled in your task manager, we set the registry key correctly. And fwiw this works perfectly fine for everyone else running windows.
