### ISSUE TITLE
OTP period larger then 60 sec

### ISSUE THREAD

**Issue by noodles101** [keepassxreboot/keepassxc#7095]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

I'm unable to store TOTP settings (otp) with an larger period than 60 seconds.

I need at least 86400 seconds.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.6.6
Revision: 9c108b9

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 10 Version 2009
Desktop Env: x86_64
Windowing System: 10.0.19043

**Comment by droidmonkey** [comment]
Change the advanced attributes manually then. That is an absurd value (1 day).

**Comment by noodles101** [comment]
That does not work. KeePassXC does generate every 60 seconds a new code. Not in the defined period time.

I know this is a big period time but I‘ve got this from the QR code.

FreeOTP app on my iPhone generate the right numbers.
Am 29. Okt. 2021, 13:40 +0200 schrieb Jonathan White ***@***.***>:

**Comment by JohnLGalt** [comment]
Did you try completely removing the OTP from that entry and then setting it up again with advanced options?

**Comment by noodles101** [comment]
Yes of course. I’ve verified it with FreeOTP witch is recommended by the provider.

**Comment by droidmonkey** [comment]
I think we do aggressive input validation and clamp the time to 60 seconds. Would have to remove that to make it work. 

Yup: https://github.com/keepassxreboot/keepassxc/blob/develop/src/totp/totp.cpp#L117

**Comment by noodles101** [comment]
here is the otp url that I've got (anonymised): 
`otpauth://totp/title%20%28Nr%29:user.name%40service.website?secret=JBXWE4BXHFDHQVCMOJ4XA5TKNRRW3ODM&digits=6&algorithm=SHA256&period=86400`

**Comment by cmorrison31** [comment]
I also have interest in a period larger than 60 seconds. The period configuration is outside of my control otherwise I'd adjust it lower (in my case it's 90 seconds). I've read through rfc6238 and I don't see any limit on what the period can be. 30 seconds is recommended but that's all the document seems to say.

**Comment by dottif** [comment]
> I think we do aggressive input validation and clamp the time to 60 seconds. Would have to remove that to make it work.
> 
> Yup: https://github.com/keepassxreboot/keepassxc/blob/develop/src/totp/totp.cpp#L117

I changed the upper bound from `60` to `UINT_MAX` and it works fine.
Then also the limit in the GUI should be incremented to a reasonable number (at least to 120 seconds). https://github.com/keepassxreboot/keepassxc/blob/2423bede60914740854ceb37034464ff4ff09f89/src/gui/TotpSetupDialog.ui#L166
As mentioned in https://github.com/keepassxreboot/keepassxc/issues/7374 there are some services that require 120s.

Other apps set the limit to 900 seconds https://github.com/Kunzisoft/KeePassDX/blob/ef836e8b842af216ef758b14feb4bde4e7f82ecb/app/src/main/java/com/kunzisoft/keepass/otp/OtpElement.kt#L214
or to the maximum integer https://github.com/beemdevelopment/Aegis/blob/b0e8d041d066a617b69912b675316c6ff89b2d42/app/src/main/java/com/beemdevelopment/aegis/otp/TotpInfo.java#L73

**Comment by DonPicciotto** [comment]
I really need this feature too. Every government app in my country use a 120s TOTP

**Comment by noisemaker00** [comment]
Hi, I've the same problem: I need a very long OTP duration (43200 seconds, not for my choice).
Is it possible to have this change released as an hotfix before the new major release?
