### ISSUE TITLE
"KeePassXC can't be opened" on Mac OS Monterey

### ISSUE THREAD

**Issue by ec52569n** [keepassxreboot/keepassxc#7096]
Hi friends. After updating to Mac OS Monterey today, every time I try to open KeePassXC, I get the 'The application "KeePassXC" can't be opened dialogue window. I can't open my database backup either.

Just a few notes from the crash report -

OS version: macOS 12.0.1 (21A559)
Report version: 104
Exception Type: EXC_CRASH (SIGKILL (Code Signature Invalid))
Exception Codes: 0x0000000000000000, 0x0000000000000000
Exception Note: EXC_CORPSE_NOTIFY
Thread 0 crashed with x86 Thread State (64-bit)

Any thoughts?

Thanks!

**Comment by ec52569n** [comment]
Uninstall and reinstall worked like a charm but perhaps it is a bug to look into for Monterey

**Comment by droidmonkey** [comment]
Not a bug in our end.
