### ISSUE TITLE
Association dialog hangs on keyDialog.activateWindow() when triggered via external Java app

### ISSUE THREAD

**Issue by purejava** [keepassxreboot/keepassxc#7099]
## Overview
The base setting is not KeePassXC with a browser extension, but KeePassXC in conjunction with [Cryptomator](https://github.com/cryptomator/cryptomator/) and [keepassxc-cryptomator](https://github.com/purejava/keepassxc-cryptomator).

[keepassxc-cryptomator #4](https://github.com/purejava/keepassxc-cryptomator/issues/4) describes the following problem: 

Cryptomator talks to KeePassXC by pressing on a vault on the left of the Cryptomator UI. It sends an `associate` request to KeePassXC, but the association dialog fails to come up properly.

That's best shown in this video, which is too big to paste it here: https://my.hidrive.com/lnk/4nCFnbfE

It's important to note that this only happens, when the association dialog was never shown properly, e.g. by a browser extension, so it therefore can be reproduced on a Windows installed from scratch. 

The moment the association dialog fails to come up properly, I halted gdb and made it show the current executed statement, which is:
https://github.com/keepassxreboot/keepassxc/blob/20db504c3af80a5765afa66824dc3e69c1a0bb59/src/browser/BrowserService.cpp#L364
<img width="2048" alt="Bildschirmfoto 2021-10-31 um 15 25 32" src="https://user-images.githubusercontent.com/1822238/139591842-6a006c95-76f0-462d-a05c-b1947a46a591.png">

Commenting out `keyDialog.activateWindow()` and re-compiling KeePassXC does bring up the association dialog and solves the issue mentioned above.
KeePassXC still works as expected without the statement.

I consider this to be a Qt bug in conjunction with a Java appplication.

Can we drop the `keyDialog.activateWindow()` statement?
## Steps to Reproduce
1. Get a Windows 10 or 11, where the association dialog never came up
2. Use KeePassXC 2.6.6, Cryptomator 1.6.1 and keepassxc-cryptomator jar 0.0.3
3. Set "Store passwords with" to KeePassXC
4. Unlock the KeePassXC database
5. Click on a Cryptomator vault to start the keepassxc-cryptomator plugin associate Cryptomator to KeePassXC

## Expected Behavior
The association dialog is shown 

## Actual Behavior
The association dialog fails to come up properly

**Comment by droidmonkey** [comment]
Activate window is what brings it to the front and provides keyboard focus. Not sure why the jvm would cause a negative interaction there. Are you seeing any special always on top or anti window switching settings? 

https://doc.qt.io/qt-5/qwidget.html#activateWindow

I don't agree with what qt writes in there about windows, it surely does take the focus away from whichever window currently had it.

**Comment by purejava** [comment]
> Activate window is what brings it to the front and provides keyboard focus. Not sure why the jvm would cause a negative interaction there. Are you seeing any special always on top or anti window switching settings?

The issue doesn't show up on the JUnit tests that are provided with keepassxc-cryptomator, but when Cryptomator uses keepassxc-cryptomator and triggers the association dialog. As Cryptomator [also sets modality](https://github.com/cryptomator/cryptomator/blob/9b8661fe3cd2f39a2abb0107110d531dfa9352ab/src/main/java/org/cryptomator/ui/unlock/UnlockModule.java#L37-L51), it's these two not playing well with each other:
```java
        @Provides
	@UnlockWindow
	@UnlockScoped
	static Stage provideStage(StageFactory factory, @UnlockWindow Vault vault, @Named("unlockWindowOwner") Optional<Stage> owner) {
		Stage stage = factory.create();
		stage.setTitle(vault.getDisplayName());
		stage.setResizable(false);
		if (owner.isPresent()) {
			stage.initOwner(owner.get());
			stage.initModality(Modality.WINDOW_MODAL);
		} else {
			stage.initModality(Modality.APPLICATION_MODAL);
		}
		return stage;
	}
```

**Comment by droidmonkey** [comment]
Huzzah, well that is unfortunate. I can run some experiment to see if activate window is even necessary, but this is a quandary. Or, did you mean to imply that the keepassxc-cryptomater extension needs a code change?

**Comment by purejava** [comment]
No, I just wanted to clarify two points:

- Java based JUnit tests do work whereas Java based running Cryptomator using keepassxc-cryptomator plugin doesn't
- you asked for always on top settings in Cryptomator and it sets modality as shown above 

I wish I'd know the root cause for this issue but I've no idea at the moment.

**Comment by droidmonkey** [comment]
OK, so I ran this through a full debug session including Qt code. This gets hung up when calling SetForegroundWindow (Windows API) and I think the reason is because of the preceding code block (which does execute successfully) that sets the input to the Cryptomator window in order to trick windows into raising our window.

```
void QWindowsWindow::requestActivateWindow()
{
    qCDebug(lcQpaWindows) << __FUNCTION__ << this << window();
    // 'Active' state handling is based in focus since it needs to work for
    // child windows as well.
    if (m_data.hwnd) {
        const DWORD currentThread = GetCurrentThreadId();
        bool attached = false;
        DWORD foregroundThread = 0;

        // QTBUG-14062, QTBUG-37435: Windows normally only flashes the taskbar entry
        // when activating windows of inactive applications. Attach to the input of the
        // currently active window while setting the foreground window to always activate
        // the window when desired.
        if (QGuiApplication::applicationState() != Qt::ApplicationActive
            && QWindowsNativeInterface::windowActivationBehavior() == QWindowsWindowFunctions::AlwaysActivateWindow) {
            if (const HWND foregroundWindow = GetForegroundWindow()) {
                foregroundThread = GetWindowThreadProcessId(foregroundWindow, nullptr);
                if (foregroundThread && foregroundThread != currentThread)
                    attached = AttachThreadInput(foregroundThread, currentThread, TRUE) == TRUE;
                if (attached) {
                    if (!window()->flags().testFlag(Qt::WindowStaysOnBottomHint)
                        && !window()->flags().testFlag(Qt::WindowStaysOnTopHint)
                        && window()->type() != Qt::ToolTip) {
                        const UINT swpFlags = SWP_NOMOVE | SWP_NOSIZE | SWP_NOOWNERZORDER;
                        SetWindowPos(m_data.hwnd, HWND_TOPMOST, 0, 0, 0, 0, swpFlags);
                        SetWindowPos(m_data.hwnd, HWND_NOTOPMOST, 0, 0, 0, 0, swpFlags);
                    }
                }
            }
        }
        SetForegroundWindow(m_data.hwnd);  // <--- This is where the hang occurs
        SetFocus(m_data.hwnd);
        if (attached)
            AttachThreadInput(foregroundThread, currentThread, FALSE);
    }
}
```

My hypothesis is that because Cryptomator is BLOCKED from input, the SetForegroundWindow call fails to return. The Cryptomator-KeePassXC plugin needs to run the association request either in a new thread or run through and periodically retry the connection until successful.

https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-attachthreadinput

**Comment by purejava** [comment]
Thanks for debugging this that deeply.
I'll change the keepassxc-cryptomator plugin to become asynchronously, test again and report back.

**Comment by droidmonkey** [comment]
I still think there is a Qt bug here because you essentially deadlock two applications due to their workaround. They should run the SetForegroundWindow call in a new event thread and timeout if it doesn't finish to prevent locking the Qt application due to a misbehaving top level window. This is a super edge case wnen two apps depend on each other, but it obviously happened here.

**Comment by droidmonkey** [comment]
Any progress made on the cryptomator side?

**Comment by purejava** [comment]
None notable yet. I started imlementing the change for the keepassxc-cryptomator plugin, but did not find much time meanwhile.

**Comment by purejava** [comment]
> My hypothesis is that because Cryptomator is BLOCKED from input, the SetForegroundWindow call fails to return. The Cryptomator-KeePassXC plugin needs to run the association request either in a new thread or run through and periodically retry the connection until successful.

You were right and both are necessary. Changing the keepassxc-cryptomator  plugin to work asynchronously (see commit https://github.com/purejava/keepassxc-proxy-access/commit/fd45bc5c90f9caedffdd92da8d9eacc6716f61d6) still wasn't good enough, as it still hung on not bringing up the association dialog properly.

It took me a while to find a solution on how to ask KeePassXC for association, return to the UI main thread within keepassxc-cryptomator (which is required to bring up the dialog), but nevertheless process the result on what is entered within the dialog.

Testing is finished now and I'll release an update of keepassxc-cryptomator that contains the fix.

**Comment by droidmonkey** [comment]
I look forward to using this plugin in cryptomator!
