### ISSUE TITLE
Left-align Timeouts settings to match other settings (OS X)

### ISSUE THREAD

**Issue by sts10** [keepassxreboot/keepassxc#710]
Totally an aesthetic thing, but I just realized that, on Mac OS X, the "Timeouts" settings are oddly center aligned. All other settings appear to left-align, even the "Convenience" settings right underneath them.

![keepassxc-set-lock-time](https://user-images.githubusercontent.com/4871664/27667260-9fa2ab80-5c47-11e7-8c0e-0e58c05cb8a4.png)

## Expected Behavior
The Timeouts settings should also be left aligned. All other settings appear to be left-aligned. And on Linux the Timeouts settings are also left-aligned (they look great by the way). 

## Current Behavior
They're center-aligned

## Steps to Reproduce (for bugs)

1. Install v 2.2.0 on OS X 10.10 
2. Go to Preferences > Security
3. Observe the odd alignment 

## Your Environment
KeePassXC - Version 2.2.0
Revision: caa49a8ef3ee28ed478192389b21d61107b3b8e0

Libraries:
- Qt 5.9.0
- libgcrypt 1.7.7

Operating system: OS X Yosemite (10.10)
CPU architecture: x86_64
Kernel: darwin 14.5.0

Enabled extensions:
- KeePassHTTP
- Auto-Type
- YubiKey

**Comment by phoerious** [comment]
The difference between the two groups is that the first contains check boxes and labels which are associated with number input fields, whereas the second group only has check boxes. Therefore the first group is aligned around a center axis, so the number fields are left-aligned.
