### ISSUE TITLE
Title of database's - duplicated

### ISSUE THREAD

**Issue by gino89baci** [keepassxreboot/keepassxc#7102]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. open 2 database with different title 
2. put in "stop" macbook, and reopen the app

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
title's of database's remain different

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
title's of database's now, are the same

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.6.6
Revision: 386b79a

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS Monterey 12.1
Architettura CPU: arm64
Kernel: darwin 21.2.0

**Comment by droidmonkey** [comment]
Please rephrase what you are talking about or include a screenshot.

**Comment by gino89baci** [comment]
![Schermata 2021-11-02 alle 09 25 39](https://user-images.githubusercontent.com/93574953/139811334-cc515f64-fc5a-4077-aa87-460988f259bf.JPG)
![Schermata 2021-11-02 alle 09 25 53](https://user-images.githubusercontent.com/93574953/139811336-bb582cf3-98cb-4f67-a8d0-f8ddf72aab6b.JPG)

**Comment by droidmonkey** [comment]
At the top of the screen, click Database then Database Settings. You can change the name of the database there.

**Comment by gino89baci** [comment]
ok, it's work. sorry but maybe the new db tooks name from the old .

Thanks

**Comment by droidmonkey** [comment]
Yes if you copy the database file then it will have the same name. Recommend also going to the database settings and the browser tab and reset the database uuid.
