### ISSUE TITLE
[doc] improve the guide for macOS

### ISSUE THREAD

**Issue by wxiaoguang** [keepassxreboot/keepassxc#7105]
I tried to build KeePassXC on macOS, the guide `Set up Build Environment on macOS` https://github.com/keepassxreboot/keepassxc/wiki/Set-up-Build-Environment-on-macOS can be improved:

1. Directory layout of brew-installed`qt5`  is: `/usr/local/opt/qt5` and `/usr/local/opt/qt@5`, no `/usr/local/opt/qt`, so the path `/usr/local/opt/qt/lib/cmake` used by cmake is invalid. Two solutions:
    * developers do `ln -s qt5 qt` in `/usr/local/opt`
    * update CMakeLists.txt to search `/usr/local/opt/qt5`

2. KeepPassXC depends on `botan2` (not mentioned in the guide), so developers should also do `brew install botan`

**Comment by varjolintu** [comment]
It also works correctly if cmake is used with `-DCMAKE_PREFIX_PATH=/usr/local/opt/qt@5/lib/cmake/Qt5/`.
