### ISSUE TITLE
Main UI size make smaller or add "most recent" feature

### ISSUE THREAD

**Issue by Oldtimmer48** [keepassxreboot/keepassxc#7107]
I have hundreds of entries in my KeePassX database, split across many many folders. I find myself using only one or two, many times in a typical day (I work in IT as a sql server developer). 

My sequence to do this is:- 
1. click the system tray, 
2. find the icon to show the UI, 
3. then ctrl+C on the entry I need the pw for.
repeat, fifty times a day

I'd like to just do 3 above, by keeping the UI open on my desktop but I need the have it really small as I need the screen space.
But I find the UI sizing is limited to a quite large size, can it be smaller?
Or a feature on the system tray icon for "most recent entries"?

**Comment by droidmonkey** [comment]
We have improved the sizing of the UI in recent versions. Make sure you are running 2.6.6. You can also enable compact mode from the view menu and disable the preview panel. I recommend looking into Auto-Type as that will ultimately allow you to keep the app in the tray and use a global shortcut. Read more here: https://keepassxc.org/docs/KeePassXC_UserGuide.html#_auto_type
