### ISSUE TITLE
Additional "2FA" feature with Cert/

### ISSUE THREAD

**Issue by konzeptplus-gmbh** [keepassxreboot/keepassxc#7108]
## Using the YubiKey / Feitian-Key or any PIV-Tool as 2FA with Cert.

Currently you can use a YubiKey / OnlyKey for a "2FA" aka hardening a set PW. 
As the challenge response is ok but not ideal and there is no true way to use FIDO2 if you do not run a RelayingParty within the Application we see a hugh potential in using the "old" Cert methode as it is used in any PIV/SmartCart environment using the YubiKey / NitroKey / Feitian or any other Hardwaretoken that can use x509V2 or V3, RSA K2/K4. 

## Context
As YubiKey Partner and DEV + Integrationpartner of Feitian, NitroKey and Identiv we belive that this feature would help to use this Product also in the SMB Market to have it spread. 

Thanks and let me know your thoughts.

**Comment by droidmonkey** [comment]
Duplicate request. Search for nitrokey and pkcs#11.
