### ISSUE TITLE
Title textbox not focused if Add Entry is started while database is still saving previous changes.

### ISSUE THREAD

**Issue by oturpe** [keepassxreboot/keepassxc#7109]
## Overview
I was entering a list of about 100 entries from a piece of paper.
To get done with it quickly,
I learned to use keyboard shortcuts effectively.
So right after saving one entry,
immediately on return to database index view,
I pressed Ctrl-N to open the Add Entry view.
Normally, Add Entry opened with Title's textbox focused,
so that I could start entering data right away.
But sometimes, I was so fast
that Add Entry opened before the previous change was saved.
(There are some visual cues in the index view
that changes are still being saved,
such as everything being greyed out,
and `*` showing up in the window title.)
In such situation,
Add Entry shows up as normal,
but a brief moment later
(presumably when the save operation completes in the background)
the Title textbox focus is lost.
This makes it more difficult to enter many entries in quick succession.

## Steps to Reproduce
1. Open a database
2. Add Entry, enter some data, OK
3. Really quickly after the database index page opens, press Ctrl-N.

## Expected Behavior
Add Entry opens,
Title textbox is focused,
the focus stays there unless the user does something to move the focus.

## Actual Behavior
Title textbox is initially focused,
quickly the focus is lost.

## Context
KeePassXC - Version 2.6.6
Revision: 9c108b9

Qt 5.15.2
Debugging mode is disabled.

Operating system: Fedora Linux 35 (Workstation Edition)
CPU architecture: x86_64
Kernel: linux 5.14.14-300.fc35.x86_64

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- libgcrypt 1.9.4-unknown

**Comment by droidmonkey** [comment]
Recommend disabling auto save when doing many changes at once, then re-enable when completed.

**Comment by oturpe** [comment]
> Recommend disabling auto save when doing many changes at once, then re-enable when completed.

Ah, nice. I was not aware of that option.
That is good advice.
Of course the problem can still be reproduced with a bit different steps,
but I am quite certain I would have never ran into it without auto-save.
