### ISSUE TITLE
Support Challenge-response

### ISSUE THREAD

**Issue by XiyuanLiu-1993** [keepassxreboot/keepassxc#7110]
I am a developer of Security key, our product have HMAC-SHA1 Challenge-Response(Not Yubikey), but it does not support KeePassXC, so what should I do to let KeePassXC be compatible with our product's Challenge-Response function? Thank you!

**Comment by droidmonkey** [comment]
Do you support the yubikey interface protocol? You need to comply with the USB interface data flow that is stipulated in the following library: https://github.com/keepassxreboot/keepassxc/blob/7811f10dba8a43d2b440ee193d14db55c9d72e31/src/thirdparty/ykcore/ykcore.c#L370

We cannot provide any support or assistance beyond pointing this out.
