### ISSUE TITLE
Crash on save in 2.6.6

### ISSUE THREAD

**Issue by 4SiB** [keepassxreboot/keepassxc#7113]
## Overview
Second database write it cannot be saved/sync. I close it. KeePass still show me a mouse hourglass icon, I close KeePassXC from systray and have a crash of app.

```
---------------------------
KeePassXC: Windows - Błąd aplikacji
---------------------------
Instrukcja w 0x00007FF6FFCFD006 odwołała się do pamięci pod adresem 0x0000000000000000. Pamięć nie może być read.


Kliknij przycisk OK, aby przerwać działanie aplikacji
---------------------------
OK   
---------------------------
```

![image](https://user-images.githubusercontent.com/18070741/140885856-ca4ae336-a034-451f-a4d3-1a58ccac1bf8.png)

```
KeePassXC - Wersja 2.6.6
Rewizja: 9c108b9
Operating System: Windows 10
```

**Comment by droidmonkey** [comment]
Unfortunately cannot do anything with this information besides knowing it is a null pointer crash. Please check our latest snapshot build to see if it still happens: https://snapshot.keepassxc.org
