### ISSUE TITLE
Password erro after 2.6.6 upgrade

### ISSUE THREAD

**Issue by EphrahimO** [keepassxreboot/keepassxc#7115]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Error while reading the database: Invalid credentials were provided, please try again.
If this reoccurs, then your database file may be corrupt. (HMAC mismatch) That's the error I'm getting after entering my password.
![image](https://user-images.githubusercontent.com/94082880/141203071-34358e17-7385-4d71-a765-c6e0aa592e6c.png)

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. ENTER PASSWORD
2. Error while reading the database: Invalid credentials were provided, please try again.
If this reoccurs, then your database file may be corrupt. (HMAC mismatch)
3. 
![image](https://user-images.githubusercontent.com/94082880/141203053-be78e596-5fee-4814-ba6e-27c4fff5645c.png)

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
LOG IN AFTER ENTERING PASSWORD

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Error while reading the database: Invalid credentials were provided, please try again.
If this reoccurs, then your database file may be corrupt. (HMAC mismatch)

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.6.6
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows
Desktop Env: Gnome/KDE/XFCE/Mate/Cinnamon
Windowing System: WINDOWS 10

**Comment by droidmonkey** [comment]
What version did you upgrade from?

**Comment by EphrahimO** [comment]
I believe 2.6.1

**Comment by droidmonkey** [comment]
Unfortunately there is not much we can do for you. Make sure you are typing in the password correctly.
