### ISSUE TITLE
The app icon in the tray on Linux Mate looks disproportionately stretched

### ISSUE THREAD

**Issue by in-him** [keepassxreboot/keepassxc#7116]
## Overview
The application icon is rendered disproportionately stretched, that is oval shaped in the tray of my Linux Mate desktop (note that the panel height is greater than the default one).

## Steps to Reproduce
1. Install the latest KeepassXC on a Linux Mate desktop (I am running it on a Linux Mint distro);
2. Increase the height of the bottom panel to 35px;
3. Open the KeepassXC application to see the icon in the tray. 

## Expected Behavior
The icon shape is all proportionately round

## Actual Behavior
The icon has an oval shape, stretched from top to bottom.

## Context
Here is what it actually looks like:
![ZpQ8Y](https://user-images.githubusercontent.com/93139980/141250702-2bc4016a-285b-48ce-9620-7fbe02fbb703.png)

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.6.6
Revision: 9c108b9

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux Mint 20.2
Desktop Env: Mate
Windowing System: X11

**Comment by droidmonkey** [comment]
This isn't our bug, we just provide an icon (in this case an svg) to Qt to display. This is a bug with them and/or Mate.

**Comment by droidmonkey** [comment]
https://github.com/mate-desktop/mate-panel/issues/519
