### ISSUE TITLE
Flatpak Release Request plz

### ISSUE THREAD

**Issue by xmready** [keepassxreboot/keepassxc#7120]
## Summary
I want to see KeePassXC released as a Flatpak in addition to (or instead of) Snaps.

## Context
Snaps are much slower to start when compared to Flatpaks. The Snap environment unfairly limits users to certain distributions. Snaps have more trouble interacting with local directories than Flatpaks do, unless you tinker with your system. As a Debian user who doesn't want snapd, having the latest release entails adding the PPA for hirsute manually and changing the .list file as my system upgrades.

**Comment by droidmonkey** [comment]
https://www.flathub.org/apps/details/org.keepassxc.KeePassXC

**Comment by xmready** [comment]
> https://www.flathub.org/apps/details/org.keepassxc.KeePassXC

I apologize, I did not see KeePassXC when I searched "keepass" on flathub. It doesn't come up using their search bar unless you type exactly "keepassxc". Thank you very much, KeePassXC rocks!

**Comment by droidmonkey** [comment]
That is interesting, pretty terrible search!

**Comment by phoerious** [comment]
Quite clearly no prefix search or sub word tokenization.
