### ISSUE TITLE
Lost ability to use network features

### ISSUE THREAD

**Issue by nlime** [keepassxreboot/keepassxc#7126]
![keepass_1](https://user-images.githubusercontent.com/59861893/141677502-53561c25-bfd5-4e1c-83e1-9880e68d7f6b.png)
![keepass_2](https://user-images.githubusercontent.com/59861893/141677504-6566bcdd-1e8c-44ad-a283-62ff35e9677c.png)
![keepass_3](https://user-images.githubusercontent.com/59861893/141677505-e3c723e8-e3f1-4e7d-b288-d1393287d42f.png)
What could be the problem?
A week ago everything was fine

**Comment by droidmonkey** [comment]
Provide the debug info tab contents please. Looks like you blocked network access to keepassxc.

**Comment by nlime** [comment]
> Provide the debug info tab contents please. Looks like you blocked network access to keepassxc.

KeePassXC - Version 2.6.6
Revision: 9c108b9
Distribution: AppImage

Qt 5.15.2
Debugging mode is disabled.

Operating system: Linux Mint 20.2
CPU architecture: x86_64
Kernel: linux 5.4.0-90-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- libgcrypt 1.8.1

**Comment by droidmonkey** [comment]
AppImage has fundamental problems with SSL certs. Please see #4219 and #4965 for more information.
