### ISSUE TITLE
The list of all groups and entries

### ISSUE THREAD

**Issue by JKozarac22** [keepassxreboot/keepassxc#7130]
Hello!

I would like to suggest something. Can you make an option that when user clicks on ROOT on the left, the all groups and entries are listed on the right like the 'basic' KeePass tool does it?

a) KeePassXC
![image](https://user-images.githubusercontent.com/18213463/141943038-b47b6f8b-928a-41f6-bf25-b399e484f1bc.png)

b) 'Basic' KeePass
![image](https://user-images.githubusercontent.com/18213463/141943113-785caa40-28a8-403a-8f93-9b86e23b8813.png)

Thank you!

**Comment by droidmonkey** [comment]
#1018
