### ISSUE TITLE
Failed to start snap.keepassxc.proxy

### ISSUE THREAD

**Issue by antonio-petricca** [keepassxreboot/keepassxc#7132]
## Overview

My journal  logs many entries with the error message `Failed to start snap.keepassxc.proxy`.

## Steps to Reproduce

It happens in background.

## Expected Behavior

A clean journal.

## Actual Behavior

`Failed to start snap.keepassxc.proxy` logged many times in journal.

KeePassXC - 2.6.6 (SNAP)

Operating System: Linux Mint 19.3 (Ubuntu 18.04)
Desktop Env: Mate

**Comment by droidmonkey** [comment]
snap.keepassxc.proxy is not a program, but keepassxc.proxy is. Check that you don't have a browser native messaging that is misconfigured. This isn't on us.
