### ISSUE TITLE
KeePassXC-Browser addon for Firefox breaks Facebook video controls

### ISSUE THREAD

**Issue by jarredou** [keepassxreboot/keepassxc#7135]
## Overview
Firefox addon breaks Facebook video controls

## Steps to Reproduce
1. Go to facebook with desktop PC with Firefox addon
2. Launch a video 
3. Click on the volume
The control is now f*cked, every move made with the mouse will affect volume, you have to refresh the whole page to exit the bug.

Same thing happens with other controls

## Expected Behavior
[NOTE]: Normal video controls.

## Actual Behavior
[NOTE]: F*cked up video controls.

## Context
[NOTE]: I've disable all my other addons, it is only happening with KeePassXC-Browser addon

KeePassXC - VERSION 1.7.10
Operating System: Windows 7 64 bits
Firefox Developer 95.0b7 (64 bits)

**Comment by taras-slapdash** [comment]
Similar behaviour observed in Chrome on macOS. 
KeePassXC - v1.7.10.

On the GIF, you can see me connecting my [Notion](https://notion.so/) account to [Slapdash](https://slapdash.com/). The Notion page is opened in a small popup window and the page isn't interact-able – buttons can't be pressed. 

When I disable the KeePassXC extension, everything works as normal. 


![CleanShot 2021-11-17 at 13 20 17](https://user-images.githubusercontent.com/57078134/142208433-997e8ae8-da49-498b-bd4e-f519af885c9e.gif)

**Comment by Guisch** [comment]
Hey 🖖🏻 

KeePassXC - v1.7.10 on 2 different chrome profiles

Same issue for me on both Notion and Facebook Video. It's just look like that at some point the mouse cursor stays clicked down.

Issue solved by disabling the extension.

**Comment by droidmonkey** [comment]
This is now fixed
