### ISSUE TITLE
KeePassXC-Browser Chrome extension breaks mouse events (?)

### ISSUE THREAD

**Issue by consoleaf** [keepassxreboot/keepassxc#7136]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

Not quite sure how to title this issue, but I've encountered it with DevExpress' DataGrid when it breaks the column resize behavior.
Confirmed that this only happens when the KeePassXC extension is active

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Open this codesandbox: https://4rjlm85k09.csb.app
2. Try resizing any column

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Columns would be resized while the LMB is held down

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Columns only start resizing after the LMB is released, and they never "let go" until you refresh the page (presumably, something wrong with mousedown/up events?)

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - unknown
KeePassXC-Browser - 1.7.10
Operating system: Win64
Browser: Chrome/Chromium 94.0.4606.114

**Comment by droidmonkey** [comment]
has been fixed
