### ISSUE TITLE
KeyPassXC-Browser in Chrome interferes with mouse events

### ISSUE THREAD

**Issue by alexvorndran** [keepassxreboot/keepassxc#7141]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

Since updating Google Chrome to the latest release version (96.0.4664.45) on Linux Mint 19.3, KeyPassXC-Browser seems to interfere with some mouse events.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Start Google Chrome with active KeyPassXC extension.
2. Navigate to https://codesandbox.io/s/xp9p7272m4 (CodeSandbox of the [re-resizeable](https://github.com/bokuweb/re-resizable#codesandbox) npm package)
3. Click and drag the lower left corner of the example object.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Resizing stops if I release the left mouse button.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Resizing continues even after I have released the left mouse button.

## Context
[NOTE]: # ( Give us any additional information you may have. )
I can force the expected behavior when I don't allow KeePassXC to operate in Incognito mode, open a new Incognito window, and then follow the steps from above. It also works on my other Windows laptop with the exact same version of Google Chrome, but no KeyPassXC extension installed.

I actually first observed this in some other code that uses re-resizable. Following the call stack with Chrome's Developer tools lead me keepassxc-browser.js somewhere around line 1963 IIRC, where a `MutationObserver` and also some mouseup event handling seems to take place.

[NOTE]: # ( Paste debug info from Help → About here )

```none
KeePassXC - Version 2.6.6
Revision: 9c108b9
Distribution: AppImage

Qt 5.15.2
Debugging mode is disabled.

Operating system: Linux Mint 19.3
CPU architecture: x86_64
Kernel: linux 5.4.0-66-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- libgcrypt 1.8.1
```

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: Cinnamon
Windowing System: X11

**Comment by droidmonkey** [comment]
This was fixed we are trying to get it through the chrome store process...

**Comment by alexvorndran** [comment]
Ah, I see. Somehow I missed #7136 while searching prior to posting this bug report.

Glad to know a fix is on the way.

**Comment by droidmonkey** [comment]
Heh and the 25 other ones in the browser extension repo :wink:

**Comment by alexvorndran** [comment]
Not one of my better moments, I guess. :confused: 

Nevertheless, thanks for your quick response.
