### ISSUE TITLE
Please add setting for vertical scrollbar width

### ISSUE THREAD

**Issue by BillDietrich** [keepassxreboot/keepassxc#7142]
In Tools / Settings / Basic Settings / User Interface, please add a way to set vertical scrollbar's width (a number of pixels), plus an option to use the system default.  Thank you.  I'm using keepassxc 2.6.6 on Linux.

**Comment by phoerious** [comment]
Sorry, but we are not going to add a setting for that. If you want to use the system's default theme, change that in the settings or View menu.

**Comment by BillDietrich** [comment]
> If you want to use the system's default theme, change that in the settings or View menu.

Using "View / Theme / Classic (platform-native)" does not affect scrollbar width, at least in my system (Manjaro 21 Xfce).

I don't know what you mean by "change that in the settings".  It's not in Settings as far as I can see.

**Comment by phoerious** [comment]
I meant the theme. But don't have an entry in the settings anymore, that's right.
When you use the classic theme, KeePassXC uses your system's standard scrollbar width and theme. If that is too small, then it's an issue with your system's Qt theme and nothing we can fix.

**Comment by BillDietrich** [comment]
I have changed the system theme (GTK2 and GTK3) to have wider scrollbars.  Apps such as Terminal and the file manager reflect the changes.  But KeePassXC does not.

**Comment by phoerious** [comment]
KeePassXC uses Qt, so you need to adjust your Qt theme.

**Comment by michaelk83** [comment]
You can make Qt use the GTK theme, but it can get a little tricky. See e.g. https://askubuntu.com/questions/910012/how-can-i-get-qt5-applications-to-use-the-gtk-theme-in-ubuntu-17-04

**Comment by BillDietrich** [comment]
This DE doesn't use Qt.  Can I put a config file somewhere to set Qt parameters ?

**Comment by droidmonkey** [comment]
[Qt5ct](https://sourceforge.net/projects/qt5ct/)

**Comment by BillDietrich** [comment]
> Qt5ct

Thanks, I think that did it.  In qt5ct, set Appearance / Standard Dialogs to "GTK2".
