### ISSUE TITLE
KeePassXC blocks Binance Login Security Verification

### ISSUE THREAD

**Issue by awalczyk5** [keepassxreboot/keepassxc#7143]
## Overview
I can't pass Binance Login verification because "puzzle" is not detected by it. When I disable KeePassXC it works properly.

## Steps to Reproduce

1. Go to page binance.com and login with your data
2. Security Verification pop-up appears
3. Here's the bug - you cannot complete verification. It doesn't detect puzzle in right place.

## Expected Behavior
I expect verificator to detect that puzzle is in the right place

## Actual Behavior
Puzzle in pop-up is hovering over the right place and nothing happens. When I disable KeePassXC it works properly.

## Context
Plugin: KeePassXC-Browser
Browser: Chrome 95.0.4638.69
Operating System: Windows 10

**Comment by awalczyk5** [comment]
@droidmonkey I don't get it why you've closed it. I can't find similar topic on github.

**Comment by droidmonkey** [comment]
Check out the last 10 closed issues and the browser extension board
