### ISSUE TITLE
Link KeePass Entries (NOT what you think)

### ISSUE THREAD

**Issue by JesGeiger** [keepassxreboot/keepassxc#7144]
If this is already listed, let me know and I'll hop on that thread.
If this already exists, I can't find it in any documentation.

I would like the ability to link related entries in KeePassXC.  This is **NOT** about using field references to the same UN / PW for multiple entries.  I am talking about some type of internal hyperlink from one entry to another.

EX: I have an entry for my debit card info (number, CVV, PIN, etc). I have a separate entry for the actual bank login info.  I would like to add a link between the 2 so that when I view the credit card, I can click on a hyperlink to jump to the bank entry, and vice versa (2-way is user specified, some items can be linked 1-way).

A comparison would be the 1Password "Related Items" function.  I currently create a custom attribute named "See Also" and use the title UUID as the value which at least shows me what to search for, but it isn't a hyperlink.  I know the actual URL field has additional capabilities with running system commands and opening files, and I can get the UUID reference to show correctly, but of course clicking it doesn't do anything.

![image](https://user-images.githubusercontent.com/82459390/142486624-40494980-bc5b-476c-9fcc-64bb3913311e.png)
![image](https://user-images.githubusercontent.com/82459390/142486710-8295582f-97e7-495d-9159-cab7f276343e.png)

**Comment by droidmonkey** [comment]
See #5369
