### ISSUE TITLE
CAPS Lock - Regression & new BUG (with Auto-Type)

### ISSUE THREAD

**Issue by rgloor** [keepassxreboot/keepassxc#715]
Caps Lock Problem / wrong behavior in and after Auto-Type

## Expected Behavior
A few month ago, there was a fix, that would prevent wrong Data-Entry in case caps lock was active (ON) when initiating/using Auto-Type.

## Current Behavior

Now with the latest version, there is a double change:
a) Regression
The caps lock fix is "reverted" (not working any more). So if caps lock is active when using Auto-Type, all entered letters are in wrong case (small case letters are big/capital letters, and capital letters are small)
b) new bug part
Now, when one uses Auto-Type (presses the short key for Auto-Type and selects the entry), and then sees that everything is entered in big letters. -> One presses the caps lock key to dis-activate it (set it to OFF).
However, at the next Auto-Type attempt, data are still entered in wrong case (capital/small)!
Pressing caps lock again, trying again. Still all letters in wrong case!

## Steps to Reproduce (for bugs)

1. Switch Caps Lock on
2. use Auto-Type 
3. -> Data entry in changed case, small=capital, capital=small
4. press Caps Lock once
5. use Auto-Type again
6. -> Caps Lock has not changed!

## Further Testing the Issue
In order to further track down the issue,  I have created a test DB-Entry for my text editor (kwrite). Then I did some variations of using caps lock with the following findings:

1.) Caps lock toggling without Auto-Type
When I type normal (small caps), then press caps lock once, it changes to capital letters, I press caps lock again, it changes back to small letters.

2.) Caps lock toggling with Auto-Type
However, when I press caps lock once (to ON / capital letters), then initiate Auto-Type (by short cut), it enters everything in changed caps (small to capital, capital to small). (Regression -> fix not working)
When I now (AFTER using Auto-Type) press the caps lock once, it remains in activated state (remains ON). No matter if I now enter data by Auto-Type or manually through the keyboard. 
Only pressing caps lock a second time (two times AFTER using Auto-Type) dis-activates the caps lock.

This issue requiring two times the caps lock key, only happens when caps lock is activated (ON) before using auto-type.
When caps lock is off, after auto-type, a single caps lock press is enough to toggle the status of caps lock (OFF/ON).

-> So handling of caps lock is messed up. AND influences the functionality of the caps lock key after usage of Auto-Type.

## Debug Info

KeePassXC - Version 2.2.0
Revision: caa49a8ef3ee28ed478192389b21d61107b3b8e0

Bibliotheken:
- Qt 5.6.1
- libgcrypt 1.6.1

Betriebssystem: openSUSE Leap 42.2
CPU-Architektur: x86_64
Kernel: linux 4.4.73-18.17-default

Aktivierte Erweiterungen:
- KeePassHTTP   (KeePassHTTP-Server not activated)
- Auto-Type
- YubiKey

**Comment by phoerious** [comment]
We never had such a caps lock protection feature. At least not that I can remember. Are you sure, that wasn't rather some platform-specific Qt feature?

**Comment by rgloor** [comment]
@phoerious
Sorry. I thought it was here. Where after some troubles with Caps Lock, there was a fix: Which checked if Caps Lock is on, and if it was, it toggled it OFF, entered Data, and then toggled it ON again (to restore previous state).
But it might have been somewhere "upstream" (KeePass or KeePassX), Sorry then.
