### ISSUE TITLE
Add username generator

### ISSUE THREAD

**Issue by tenzap** [keepassxreboot/keepassxc#7151]
Just like the password generator, would it be possible to implement a username generator?

There are various possibilities. For example, it could be:
- almost random → if it searched in a search engine, then one would almost be sure to get it as a result
- a very common word or mix of words (in any language) what would prevent it from coming out in the first results when "googled"

**Comment by droidmonkey** [comment]
This has been requested previously, we are not implementing it. Just use the passphrase generator if you want to make a random username.
