### ISSUE TITLE
Open popup (e.g. available update) seems to contribute to corrupting database on laptop sleep on MacOS 

### ISSUE THREAD

**Issue by firxworx** [keepassxreboot/keepassxc#7157]
## Overview

I have had a freakish number of corrupt database issues with MacOS but not on my PC versions.

With apologies I do not have confirmed replication... However I wanted to report the issue in case other users are finding a similar experience.

I anecdotally noticed that the problem seems to manifest when KeePassXC didn't appear to properly close + save the database before the laptop goes to sleep, and on wake/resume, I see a blip and it then shows the locked / auth screen and often this means the database will be corrupted. 

I anecdotally notice the issue happens around when there's a new update for KeePassXC. I think an open popup/modal (which appears when there's a new update available) might have something to do with it. 

If a contributor is tooled up for dev and can trigger a popup or other event that might prevent KeePassXC from properly saving + closing any open database and can give it a shot on MacOS, it would be interesting to see if they could replicate these conditions and confirm or deny the existence of an issue here.

Operating System: MacOS
Versions: any recent versions of KeePassXC

**Comment by droidmonkey** [comment]
Have you confirmed that the file is actually being written to when you wake from sleep? Pop-ups generally block locking the database. The update check is such a rare occurrence and really has nothing to do with the saving. The more likely scenario is failed sync, drive writes, or faulty memory.
