### ISSUE TITLE
RPC support?

### ISSUE THREAD

**Issue by rezad1393** [keepassxreboot/keepassxc#716]
does keepassxc support keepassRPC?

**Comment by phoerious** [comment]
No. We support KeePassHTTP (i.e., PassIFox, chromeIPass and passafari) and we will support a more modern and secure alternative called keepassxc-browser in the future.

**Comment by rezad1393** [comment]
deos KeePassHTTP allow adding and entries?

**Comment by droidmonkey** [comment]
Yes
