### ISSUE TITLE
double click no longer opens browser

### ISSUE THREAD

**Issue by yp65** [keepassxreboot/keepassxc#7162]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. 
2. 
3. 

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Open browser

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
double click no longer opens the browser

## Context
[NOTE]: # ( Give us any additional information you may have. )
when I double click on the url it no longer opens the browser automatically

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows/Linux/macOS
Desktop Env: Gnome/KDE/XFCE/Mate/Cinnamon
Windowing System: X11/Wayland

**Comment by droidmonkey** [comment]
Please fill out the entire issue template. There is no way we can help you without knowing all the background and operating system data. Did it work before and now broken? Extremely unlikely this is a keepassxc problem. This will be closed without additional info.
