### ISSUE TITLE
macOS: autofill AirPort network passwords?

### ISSUE THREAD

**Issue by jason5122** [keepassxreboot/keepassxc#7163]
Hi, this is actually more of a question than a feature request, but the feature request issue template seemed to be the closest I could get. Has anyone found a way to integrate KeepassXC with macOS's Wi-Fi passwords?

I'm talking about something more native than autotype: something native like `SSH_ASKPASS` (the Wi-Fi equivalent) is what I'm looking for. Thanks for reading! Feel free to close this whenever.

**Comment by droidmonkey** [comment]
Does Auto-Type not work?

**Comment by jason5122** [comment]
It does, but I was curious if there was a better solution/API. I used autotype before I found out about the browser extension and before I found out about `SSH_ASKPASS` for example.
