### ISSUE TITLE
The tray icon is stretched in GNOME 41.

### ISSUE THREAD

**Issue by matj1** [keepassxreboot/keepassxc#7164]
## Overview

After updating GNOME to 41, the KeepassXC tray icon is stretched wide and has visible scaling artifacts.

That's how it looks:
![KeepassXC panel](https://user-images.githubusercontent.com/22873928/143240796-015268f2-ff3c-468b-96fc-b875f24f06bd.png)

It didn't happen before updating to GNOME 41 and no other tray icon is stretched like that. The icon is displayed only if the GNOME extension [AppIndicator and KStatusNotifierItem Support](https://github.com/ubuntu/gnome-shell-extension-appindicator) is enabled, so it may be a problem with the extension, not GNOME directly.

## Steps to Reproduce

1. Have GNOME 41.1 on Manjaro and KeepassXC installed.
2. Have AppIndicator and KStatusNotifierItem Support enabled. (That's by default on Manjaro with GNOME.)
2. Have KeepassXC open and the tray icon enabled.

## Expected Behavior

The icon would be circular and without scaling artifacts, like this (which is the result of my attempt to fix it):
![KeepassXC icon](https://user-images.githubusercontent.com/22873928/143243459-d76e3af2-866d-4435-930e-58aaf5b96abb.png)

## Actual Behavior

The icon is stretched wide and has scaling artifacts.

## Context

KeePassXC - 2.6.6  
Revision: 9c108b9

Operating System: Linux – Manjaro
Desktop Env: GNOME 41.1
Windowing System: Wayland

**Comment by droidmonkey** [comment]
Please report this to the extension, this isn't on us. 

Andddd just that easy https://github.com/ubuntu/gnome-shell-extension-appindicator/issues/319
