### ISSUE TITLE
Unable to change theme

### ISSUE THREAD

**Issue by w-canvas** [keepassxreboot/keepassxc#7167]
## Overview
I'm unable to switch the theme to "dark". The "view" menu is not vissible.

## Steps to Reproduce
1. install KeePassXC with apt package manager
2. run application

## Expected Behavior
User guide states there should be a "view" menu (between the "tools" and "help" menus) where the theme may be selected. It also states that theme should automaticaly follow the system which is currently set to "dark".

## Actual Behavior
View menu is not visible on the application, and interface is light themed.

## Context
new installation of keepass on ubuntu 20.04 with cinnamon

current system theme is set to "dark".

KeePassXC - Version 2.4.3
Revision: 5d6ef0c

Qt 5.12.8
Debugging mode is disabled.

Operating system: Ubuntu 20.04.3 LTS
CPU architecture: x86_64
Kernel: linux 5.11.0-40-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (only unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.5

Operating System: Linux
Desktop Env: Cinnamon
Windowing System: X11

**Comment by phoerious** [comment]
Your version is ancient. Use our PPA to update your installation.
