### ISSUE TITLE
Unable to write to keepassxc.ini

### ISSUE THREAD

**Issue by gigaSproule** [keepassxreboot/keepassxc#717]
When opening the settings for keepassxc (installed via snap), it complains that it can't write to the `keepassxc.ini` file. I'm guessing this is due to the fact that the file is under `$HOME/.config/keepassxc/` (and snap apps can't access it? https://bugs.launchpad.net/snappy/+bug/1607067) or because snap apps can only write to it's own space (`$HOME/snap/keepassxc`)?

## Expected Behavior
Settings should be written to `keepassxc.ini` file.

## Current Behavior
Settings are not written to `keepassxc.ini` file.

## Possible Solution
Change the location of the `keepassxc.ini` file to be somewhere else for snap variants?

## Steps to Reproduce (for bugs)
1. Install keepassxc via snap (`sudo snap install keepasxc`)
2. Go to `Tools > Settings`
3. An error will appear at the top of the window stating it can't access `keepassxc.ini`

## Context
The main issue I have is that I can't turn on keeassxc http

## Debug Info
KeePassXC - 2.2.0

Operating system: Lubuntu 17.04
CPU architecture: x64

**Comment by droidmonkey** [comment]
I don't experience this issue (nor anyone else that has used the snap). Can you confirm that you don't have any permissions issues with the snap storage directory. We have permission to access the user home directory.

**Comment by gigaSproule** [comment]
I did check that. I tried deleting the `keepassxc.ini` file and when that didn't work, tried deleting `$HOME/.config/keepassx`, which also didn't work. I tried re-creating the directory, but again to know avail.

What are the expected permissions? It might be worth noting that I tried the snap version after I had the deb installed, but uninstall ed to try the snap version, so that could have done something.

I'll try it on another machine, in case it's a one off oddity.

**Comment by mattsches** [comment]
Same here, installed via snap, affected config file has `664` permissions: `~/snap/keepassxc/23/.config/keepassxc/keepassxc.ini`

Version info:
```
KeePassXC - Version 2.2.0
Revision: 9a7e6850d6b79c47c2d46d99fdaf433c2ff13716

Libraries:
- Qt 5.7.1
- libgcrypt 1.7.6-beta

Operating system: Ubuntu Core 16
CPU architecture: x86_64
Kernel: linux 4.11.1-041101-generic

Enabled extensions:
- KeePassHTTP
- Auto-Type
- YubiKey
```
