### ISSUE TITLE
Password generation from fields does not obey word case option.

### ISSUE THREAD

**Issue by blu28** [keepassxreboot/keepassxc#7171]
## Overview
[NOTE]: # I have my password generator set up to generate a passphrase of multiple words, and word case is set to "Title Case". When I generate a password from within the KeepPassXC UI it works perfectly. However, when I am creating a new account in the browser and click on "password generator", whether the icon is displayed directly in the field or if I right click and click through the context menu to the password generator, the password generated is all lower case. It obeys all of the rest of the setting, just not the word case option.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. In the UI, set the password generator to generate a passphrase and set word case to "Title Case"
2. Generate a password in the UI, verify all words are capitalized.
3. Generate a password in the browser, see all words are lowercase.

## Expected Behavior
[NOTE]: # Generating passphrases in the browser should be the same as with the UI.

## Actual Behavior
[NOTE]: # The browser ignores the word case option.

[NOTE]: # 
KeePassXC - Version 2.6.6
Revision: 9c108b9

[NOTE]: # 
Operating System: Windows
Browser: Version 96.0.4664.45 (Official Build) (64-bit)

**Comment by droidmonkey** [comment]
Fixed with #6529
