### ISSUE TITLE
Optionally add additional attributes as columns to the list of entries

### ISSUE THREAD

**Issue by fnordiff** [keepassxreboot/keepassxc#7172]
## Summary
I'd like to add "Additional Attributes" as columns to the "List of Entries" and "List of Search Results".

## Example: columns of my KeePass2 configuration (e-mail is an additional attribute) 
Title, User name, Password, URL, E-mail, Last Password Modification, Notes

## Context
Currently I am using KeePass2 with Mono. KeePass2 has this option (View > Configure Columns... ). I use it to display e-mail addresses. 

Many of my accounts have an email address, but not all. Some of them have username=e-mail, but not all. Since i use several different email addresses i want to keep track of them. So I have a custom field called "e-mail" in KeePass2 and I assign it to every account that has an assigned e-mail address. Displaying this field in a column gives my an overview of where I am using which e-mail address. As a side effect, I can sort by e-mail. If the additional attribute does not exist for an entry, the field is left blank.

Alternatively, there could be a standard "e-mail" field such as "URL" for every entry. But I can imagine that this would require a change in the database structure. I would be happy if I could display at least one column with an additional attribute in the lists.

**Comment by droidmonkey** [comment]
This is a duplicate request

**Comment by fnordiff** [comment]
#1493
