### ISSUE TITLE
Crash on merge (network share, windows, 2.6.6)

### ISSUE THREAD

**Issue by 4SiB** [keepassxreboot/keepassxc#7175]
## Overview
KeePassXC Crash.

## Steps to Reproduce
1. Work with open database few days
2. CTRL-K > OK to clone one entry and KeePassXC instant show question if Merge "PL: SCAL" the database > YES.
3. Freez per few minutes then I close the app.

## Expected Behavior
KeePassXC on my change he ask about merge and should do this merge with success. Just work correctly.

## Actual Behavior
I run KeePassXC and just work with it.
I hope he have all my entry what I have before.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Wersja 2.6.6
Rewizja: 9c108b9

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 10 (21H2)

**Comment by 4SiB** [comment]
DataBase file is at \\\\10.5.1.2\... shared resource and i have access to it, can work with this drive.

This is like what I see:

![image](https://user-images.githubusercontent.com/18070741/143565229-cf6511bf-48b9-43ce-839a-6d2711a2f198.png)


Windows EventLog not have any entry from KeePassXC.
I not have any logs etc. to share you. If you have any method to enable operating logs of application then YES I ALLOW AND I DO THAT but I not know if this is possible to debug that problem more in future.

This is SECOND TIME that problem.
First time I loose few entry in database !

**Comment by 4SiB** [comment]
Current settings in KeePassXC :
![image](https://user-images.githubusercontent.com/18070741/143564437-3d070dc1-d113-47e5-8ee3-2d1ced9b450a.png)

Question:
At this KP database file works 2 persons remotely, I and friend we should have here in settings the same settings ?
We should enable that:
* Backup database file before saving
* Safely save database files
?

Thanks for answer.

**Comment by droidmonkey** [comment]
See if it still happens when using a snapshot build: https://snapshot.keepassxc.org

**Comment by michaelk83** [comment]
> DataBase file is at `\\10.5.1.2`

Network drive? That may be part of the problem.
edit: Just noticed #7113 from the same user. So the crashes are not only on merge. Makes me suspect the network drive even more.

**Comment by droidmonkey** [comment]
The application shouldn't crash regardless of where it is stored. There are confounding factors here, could be numerous areas of fault.

**Comment by 4SiB** [comment]
Installed:
KeePassXC - Version 2.7.0-snapshot
Build Type: Snapshot
Revision: d3b28f8

I have enabled in Options > File Management:
* backup database file before saving
* Use alternative saving method... Temporary file moved into place

I cannot do a screenshot of this settings because KP is auto-hide now. I can disable this ?

My crash/frezz problem before was 17days ago, reported here: https://github.com/keepassxreboot/keepassxc/issues/7113

**Comment by droidmonkey** [comment]
No need for screenshots. See if you can reproduce the problem.

**Comment by 4SiB** [comment]
Update: 
My PC today works with KeePassXC per VPN as always. I work on remote FileServer etc. all are ok. I sleep PC and go to next customer and again work as always.

When I try run KeePassXC this show me a Merge popup (I not know when that popup show, maybe even before, from previouse customer. When I sure that I have vpn and access to share (by script who create test file and give me feedback, all good) I press Merge nad KeePassXC just close main window, close a tray icon. I must run KeePassXC, unlock database and all works ok (I hope).

When I see Merge popup then I can do some stuff if possible, like .pcap dump etc if you want.

**Comment by 4SiB** [comment]
I can reproduce that problem.
Seams it's easy.

Both PC with v2.6.6
MyPC open DB, create folders or entry - this is autosave done, clone or create a new entry do autosave without any problem and I do nothing more, still have a DB open.
SecondPC open the same DB, he not see my new entry.
MyPC, I check, I not see any my new entry. I close DB and see error who is show at merged case.
All entry lost !.

Summary, v2.6.6 cannot be used on production when 2 people use the same DB file at one time .

Installed again BETA, this time i disable autosave and will press this manualy.
KeePassXC - Version 2.7.0-snapshot
Build Type: Snapshot
Revision: https://github.com/keepassxreboot/keepassxc/commit/d3b28f86515df73194d1102253b739b51b1909f5
