### ISSUE TITLE
Importing csv into firefox from keepass

### ISSUE THREAD

**Issue by droidus** [keepassxreboot/keepassxc#7178]
I am running Firefox 94.  I am also running KeepassXC 2.6.6.  I attempted to export the csv from keepass, then import into firefox, but got this error message (see attached image).
Is there a program that will convert it into the right format? 
![2021-11-26_09-42](https://user-images.githubusercontent.com/1126338/143597954-346505fd-cf1c-4b9c-a290-e5c6fa66d330.png)

**Comment by droidmonkey** [comment]
You'll need to edit the file to match what Firefox needs. Use OpenOffice or Excel.

**Comment by Oymate** [comment]
@droidmonkey should there be a custom setting to import firefox password .csv files?

**Comment by Oymate** [comment]
It seems you do not want to integrate the importing feature into the app. Can you point me to a script that can do this conversion cleanly?

**Comment by droidmonkey** [comment]
We have a very robust csv importer that let's you configure all the options necessary. There is a bug in the created/modified dates due to Firefox using millisecond Unix time that is now fixed.
