### ISSUE TITLE
[Feature request] Passphrase generator: Option to generate randomly UPPERCASE and lowercase words, as well as padding digits and symbols

### ISSUE THREAD

**Issue by ghost** [keepassxreboot/keepassxc#7181]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )

The website `https://xkpasswd.net/s/` allows generating passphrases that BOTH contains randomly ALL UPPERCASED and lowercased words, I think KeepassXC should too.

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )

Example for excellent passphrase:
Structure:`P` `P` `D` `D` `S` `word` `S` `word` `S` `word` `S` `word` `S` `word` `S` `word` `S` `word` `S` `word` `S` `D` `D` `P` `P`

Where:
`P` = Padding symbol
`D` = Padding digit
`S` = Separator

An example passphrase in the above structure (a mock up one of course)
`??63_division_PROBABLY_scotland_STATEMENT_suggested_KENTUCKY_describe_DETERMINE_31??`

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )

This allows more bits of both blind and seen entropy, as well as increasing the difficulty of bruteforce and dictionary cracking sinces the randomness of cases, as well as paddings are impossible for the attacker to guess.

Users will have more options to choose what kind of passphrase they want to generate.

**Comment by droidmonkey** [comment]
This is the opposite of what you want to do with a passphrase generator. The whole point of a passphrase is to be easy to remember while providing entropy through the sheer number of word choices possible. See https://github.com/keepassxreboot/keepassxc/issues/5467

**Comment by ghost** [comment]
Understood. Sorry about that.
I will continue supporting your project.
