### ISSUE TITLE
Add option to disable window minimization with Entry-Level Auto-Type

### ISSUE THREAD

**Issue by friend18** [keepassxreboot/keepassxc#7182]
## Summary
Add option to disable window minimization with Entry-Level Auto-Type

## Examples
N/A

## Context
I have a frequently-accessed web-accessed account that requires both UserName/PassWord and TOTP -- in that order -- for authorization.

When I use Entry-Level Auto-Type, enabling the Auto-Type sequence (by clicking on the "Perform Auto-Type" glyph) also minimizes the KeePassXC window.  So I immediately have to go to the icon representing the minimized window, double-click it to UNiconify, move the cursor back to that window, then enter Ctrl-T to get the TOTP value copied, etc.

My request is to have an option (could be per-database entry, not global) to *disable* minimizing the KeePassXC window when Entry-Level Auto-Type is used.

If there already is some way of doing this, I was unable to find it in the documentation.

**Comment by droidmonkey** [comment]
#3457, this is also much better in the upcoming 2.7.0, using the global Auto-Type shortcut will enable searching the database and automatically choosing the last used entry if shown again within 30 seconds.
