### ISSUE TITLE
Auto type stopped working 

### ISSUE THREAD

**Issue by peter099** [keepassxreboot/keepassxc#7183]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
The auto type keyboard shortcut stopped working.  And even if i click on "Perform auto type sequence" in context menu nothing happens. 

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1.  Open website login page.
2.  Press ctrl+shift+v
3.  Nothing happens. 

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
To fill user and password. 

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Nothing happens.

## Context
[NOTE]: # ( Give us any additional information you may have. )
The auto type shortcut worked, but suddenly stopped working. I don't know why. 

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.6.6
Revision: 9c108b9

[NOTE]: # ( Pick choices based on your environment )
Operating System: MX Linux
Desktop Env: XFCE
Windowing System: X11

**Comment by droidmonkey** [comment]
Are you using wayland?

**Comment by peter099** [comment]
No, X11. 

Also, if i open the 'settings' in 'General' the autotype tab is missing. I don't know if some update didn't break something.

**Comment by droidmonkey** [comment]
If the Auto-Type settings tab is missing then either the shared library got removed from your system or you are running keepassxc on Wayland.

**Comment by peter099** [comment]
What is the name of the shared library? I will installed again.

**Comment by droidmonkey** [comment]
Just reinstall keepassxc

**Comment by peter099** [comment]
I did reinstall keepassxc but the auto type tab is still missing.

**Comment by droidmonkey** [comment]
Then you are running Wayland or something is preventing us from loading the auto type library. Try using our appimage or snap distribution.

**Comment by peter099** [comment]
I already said i am not running wayland, and i don't think mx linux xfce even has wayland support. What is the name of the library so i can check if it is installed?

**Comment by peter099** [comment]
After restarting my pc the autotype tab appeared. Probably some update required restarting my pc which i haven't done for few days.
