### ISSUE TITLE
Hang when "Save Database Backup"

### ISSUE THREAD

**Issue by digimeas** [keepassxreboot/keepassxc#7187]
Hi! KPXC is great
Flatpak version on Mint
KPXC hangs when I click the "Save Database Backup" menu.
Is that due to the Flatpak VM? or something else?
Thanks
Doug

**Comment by droidmonkey** [comment]
Please try our appimage to confirm if it's a flatpak problem.

**Comment by digimeas** [comment]
Hi droldmonkey!

Just Flatpak, I guess

Thanks
Doug
