### ISSUE TITLE
error while loading shared libraries: libqrencode.so.4 and libargon2.so.1 on Ubuntu 18

### ISSUE THREAD

**Issue by tredondo** [keepassxreboot/keepassxc#7190]
I've [set up the build environment on Linux](https://github.com/keepassxreboot/keepassxc/wiki/Set-up-Build-Environment-on-Linux), but it's an Ubuntu 18.

https://github.com/keepassxreboot/keepassxc/wiki/Set-up-Build-Environment-on-Linux#install-the-required-dependencies says

> Ubuntu 18.04 and below replace libargon2-dev with libargon2-0-dev

Maybe those Ubuntu 18.04 instructions should include how to install ibqrencode-dev 4. Mine was already the newest version (3.4.4-1build1). I was able to install these [`.deb`s](https://launchpad.net/ubuntu/+source/qrencode) and apparently that worked, but then I got

    error while loading shared libraries: libargon2.so.1: cannot open shared object file: No such file or directory

I had already installed that library. "libargon2-0-dev is already the newest version (0~20161029-1.1).".

**Comment by phoerious** [comment]
That's a runtime path configuration issue on your system. If you can compile and link, but not execute the binary, check your loading paths.

If this is a pre-compiled version, then you are using the wrong binary and you have to use one that was compiled on 18.04 instead.
