### ISSUE TITLE
Allow having a separate secrets database running

### ISSUE THREAD

**Issue by fishman** [keepassxreboot/keepassxc#7191]
## Summary

A lot of apps such as electron apps will constantly write and load to the freedesktop secrets service and lockup if they can't access the service. Another issue that happens with these constant writes is that databases are constantly out of sync.

By allowing a separate database for the freedesktop secrets. The secrets can stay unlocked longer than the normal database.

**Comment by droidmonkey** [comment]
Why not just use two databases within keepassxc? I don't really understand your request though.

**Comment by fishman** [comment]
The problem is that they don't have separate lock policies. So there it's quite inconvenient to have them separate if they lock at the same interval. Several gnome apps just hang if the database locks and it's easy not to notice it happening. Whereas for the normal database you probably don't want to keep it unlocked for too long.

**Comment by droidmonkey** [comment]
This is very similar to #2224. Also, several major improvements were made to fdosecrets for 2.7.0. This includes asking to unlock a database if its locked. Not perfect, but better workflow for sure. We won't introduce specific database security settings just for fdo.
