### ISSUE TITLE
Document how to setup and use TOTP in the user guide

### ISSUE THREAD

**Issue by cquike** [keepassxreboot/keepassxc#7192]
## Overview

I am trying to show some potential users in my organization how to use KeePassXC for TOTP. However there is no official documentation in the user guide https://keepassxc.org/docs/KeePassXC_UserGuide.html. Or at least I couldn't find it...
I know one can find places in Internet that show how to do it, but it is difficult to convince an organization to use KeePassXC if it cannot rely on official documentation from the project.
 
It would be great if this information is added to the user's guide.

**Comment by stefan123t** [comment]
@cquike I have been struggling to use TOTP for my own purposes, but somehow solved this with the results of discussion in #6782
Maybe you can extract the necessary steps for your use case and provide the developers with a proposal for your use-case ?
Kind regards,
Stefan

**Comment by BombJovi** [comment]
Hello! I think another great idea to include in the documentation for this user guide is to include a compiled list of all the platforms that utilize the TOTP via the secret key method for two-factor authorization (such as Facebook, Amazon, Reddit, etc.)

Not every platform/app uses the same method for two-step verification. It's been my experience that most platforms use SMS or e-mail a one-time password to verify.

I'm still pretty new to using Keepassxc so I'm not sure if I am going about it the wrong way but it appears that not every log-in/entry in KeepassXC can also have an associated Temporary on-time password authenitcator. (i.e. Steam has Steamguard - and I don't think it's possible to use a third-party authenticator like KeepassXC for this scenario, but I'm not entirely sure about this?)

Sorry if this is not the correct place to post this issue/feature request but it may be relevant to this topic.

What do you guys think?

**Comment by droidmonkey** [comment]
No, that is far outside our scope. You can get that information from https://2fa.directory/

**Comment by BombJovi** [comment]
Oh neat! Didn't know that website existed. Exactly what I was looking for : )
Thanks for the link!

**Comment by buhtz** [comment]
Why was this closed? If there was a solution please link to it.

**Comment by michaelk83** [comment]
The user guide was linked to in the OP. You can find the requested information there.
https://keepassxc.org/docs/KeePassXC_UserGuide#_adding_totp_to_an_entry

**Comment by buhtz** [comment]
> The user guide was linked to in the OP.

I didn't asked for the whole user guide. This is not a support question.

> https://keepassxc.org/docs/KeePassXC_UserGuide#_adding_totp_to_an_entry

That URL (not the content behind it) is the info I was looking for because I would like to know if and how the Issue was solved. It wasn't clear from the closing message.

**Comment by michaelk83** [comment]
> I didn't asked for the whole user guide.

There are clear heading links in the guide, and you can use text search.

> I would like to know if and how the Issue was solved. It wasn't clear from the closing message.

Issue asked for documentation. The documentation was updated. You can see that in the PR link title just above the closing message: "Update all documentation for 2.7.0 #7533" (and you can see on the right that that PR was merged).

**Comment by buhtz** [comment]
> > I didn't asked for the whole user guide.
> 
> There are clear heading links in the guide, and you can use text search.

But I don't want to read docu because I don't ask a support question. That issue is about developing the docu.

> Issue asked for documentation. The documentation was updated. You can see that in the PR link title just above the closing message: "Update all documentation for 2.7.0 #7533" (and you can see on the right that that PR was merged).

The PR is not atomic and involves a lot of other docu topics/issues. It is not clear where the modification this issue is related was done.

If you want to attract external contributors I would recommend to be more transparent about your workflow.

**Comment by michaelk83** [comment]
It took me less than a minute to find that link, which you could find yourself with a bit more effort. All the information is there. If you want to be developing anything, then you need to put in the effort to look through the links and documentation and code if necessary to find what you need. It is not other people's job to spoonfeed you the information you're looking for.
