### ISSUE TITLE
-DKEEPASSXC_DIST_TYPE=AppImage doesn't generate an appimage file

### ISSUE THREAD

**Issue by tredondo** [keepassxreboot/keepassxc#7193]
## Overview
I've checked out the `master` branch, and tried to build an AppImage per [these instructions](https://github.com/keepassxreboot/keepassxc/wiki/Building-KeePassXC#build-options):

## Steps to Reproduce
 ```
$cmake -DWITH_XC_YUBIKEY=ON -DWITH_XC_BROWSER=ON -DWITH_XC_NETWORKING=OFF -DWITH_XC_SSHAGENT=ON -DWITH_XC_KEESHARE=OFF -DWITH_XC_KEESHARE_SECURE=OFF -DWITH_XC_UPDATECHECK=OFF -DWITH_TESTS=OFF -DWITH_GUI_TESTS=OFF -DCMAKE_BUILD_TYPE=Release -DKEEPASSXC_DIST_TYPE=AppImage ..
-- Found Git HEAD Revision: 9c108b9

-- Setting up build for KeePassXC v2.6.6

-- Including translations...

-- Using asciidoctor: /usr/bin/asciidoctor
-- Enabled features:
 * Auto-Type, Automatic password typing
 * KeePassXC-Browser, Browser integration with KeePassXC-Browser
 * SSHAgent, SSH agent integration compatible with KeeAgent
 * YubiKey, YubiKey HMAC-SHA1 challenge-response

-- Disabled features:
 * Networking, Compile KeePassXC with network access code (e.g. for downloading website icons)
 * KeeShare, Sharing integration with KeeShare (requires quazip5 for secure containers)
 * UpdateCheck, Automatic update checking
 * FdoSecrets, Implement freedesktop.org Secret Storage Spec server side API.

-- Configuring done
-- Generating done
-- Build files have been written to: /home/tredondo/keepassxc/build
$ make
[...]
$ ls -R * | grep app  # no output
```

Instead, I get the regular binary in `src/keepassxc`.

I tried replacing the `-DKEEPASSXC_DIST_TYPE=AppImage` option with `-DMAKE_DIST_TYPE=AppImage` just in case [the wiki page was outdated](https://github.com/keepassxreboot/keepassxc/pull/6951#issuecomment-983942366), but then cmake issued a warning that the variable `MAKE_DIST_TYPE` was not used by the project.

**Comment by droidmonkey** [comment]
You need to use the release tool to build an appimage. This is documented in the build instructions wiki. 

https://github.com/keepassxreboot/keepassxc/wiki/Building-KeePassXC#building-inside-a-docker-container

**Comment by phoerious** [comment]
That flag is only for setting the reported build type in the About dialogue. use the release-tool for actually building one.
