### ISSUE TITLE
Feature: Add character-position numbered password view (monospace, rules)

### ISSUE THREAD

**Issue by bms** [keepassxreboot/keepassxc#72]
A number of web sites -- e.g. banking, financial etc. -- don't outright request a password, but instead ask for a series of numbered characters from it.

It would be very useful to have a password view which allows this, e.g. using a monospaced font, ruler cells, and numbers for character positions. Then, at a glance, one can see what characters need to be entered to respond to the challenge.

**Comment by droidmonkey** [comment]
This just seems user hostile! Which bank/institution enforces such a draconian policy?

**Comment by bms** [comment]
Well, my current UK personal bank for one -- the Co-Operative. I pull statements from it into GnuCash in OFX using a JS scriptlet, which knows how to parse their statement DOMs, as they only have CSV download and I need tagging.

So I'm following the keepassx-http plugin stuff here with interest.

The GnuCash engine is built in Lisp believe it or not... but it can call out for things like the German HBCI, which blows away other finance program integration I've seen; it can execute online payments from the app totally automatically.

That said, the Co-Op is not the only 'major site' I've seen that do this. My business bank (another major UK retail bank) also do this with password usage.

My guess implementing a feature like this would actually need fairly tight integration with the browser, to detect when these fractional password requests are being made (perhaps by observing the DOM and keywords, like Chrome I believe does) with some bayesian filtering to be 'sure' it's a request for a fractional password field.

The keepass http extraction stuff I haven't looked at, but is why I've been watching here (I currently use KeePassX where possible, on MacOS and Mint; I run nothing critical on Windows now, but would be useful to 'plug in' there).

I'm actually trying to get my head around YubiKey Neo protocol vs device compatibility. It may be that  OpenPGP is the most portable device-side app to use for secure credential storage.

Whilst PIV is really good for quickly integrating to build X.509 in-house based on PIV and PKCS#11, it isn't well exposed on mobile devices. Apple won't open their NFC, but OpenPGP authentication is readily available for Android in the form of OpenKeychain.

Lacking in all of this is a way to store the Keepass DB on a device like this, which I am sure may be possible in some cases, beyond just pushing to a storage target which they might expose.

HID etc do produce such devices. Check them out on SmartcardFocus.com which I found linked off the OpenPGP notes on smart cards.

**Comment by droidmonkey** [comment]
@TheZ3ro this might be a nice thing to add to your list when you work on the password strength meter... to also think about how to integrate a positional display.

**Comment by TheZ3ro** [comment]
I think that we can do this with a proper UI for the 2.2.0 version. But will it be usefull?

**Comment by droidmonkey** [comment]
Useful to some, v2.2 is good target

**Comment by bms** [comment]
Oh, data point -- the Verified By Visa and Mastercard 3D Secure schemes use positional character challenges, for Cardholder Not Present (online) transacations...

**Comment by droidmonkey** [comment]
Closing in favor of #725
