### ISSUE TITLE
Password shown in plain text while user name is obfuscated

### ISSUE THREAD

**Issue by conqp** [keepassxreboot/keepassxc#7201]
## Overview
KeePassXC 2.6.6 shows obfuscated user names, but shows passwords in plain text in the list view.

## Steps to Reproduce
See list in KeePassXC 2.6.6

## Expected Behavior
Other way around: obfuscate password, but show user name in plain text.

## Actual Behavior
see above.

## Context
KeePassXC 2.6.6
Arch Linux (vanilla), up-to-date.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.6.6
Revision: 1

[NOTE]: # ( Pick choices based on your environment )
Operating System: Arch Linux (vanilla)
Desktop Env: Gnome
Windowing System: Wayland

Screenshots:
[1] https://nextcloud.richard-neumann.de/s/Kd3ynTrAa29m9eG
[2] https://nextcloud.richard-neumann.de/s/jEKXNY44E2tgrDp

**Comment by droidmonkey** [comment]
Use the view menu.

**Comment by conqp** [comment]
FML. Sorry for the noise.
FWIW looking at the keyboard shortcuts  this might have resulted from my habit of copying from a gnome-terminal with Ctrl+Shift+C. That would explain why I inadvertently changed the settings.
