### ISSUE TITLE
[Feature Request] Add an option that makes an user have to push the button on their yubikey or onlykey for a TOTP code for key-enabled database

### ISSUE THREAD

**Issue by ShapeShifter499** [keepassxreboot/keepassxc#7203]
## Summary
An option one can set up that requires a user to tap their yubikey or onekey to get a TOTP requiring a user to enter their passphrase to change the setting when they use a database that is tied with a yubikey or onlykey.

## Example
Similar to how you can enable in Yubico Authenticator an option that requires you to tap on the key to get a code.

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )

Matters to me because it gives a person an extra moment to really think about when and why they're entering the TOTP code.  

I think it also could help in cases where a person who has unlocked their database and didn't realize or forgot it was still open. One could walk away with their key and if a nefarious party swooped in to use the database they still couldn't get into certain sites because of TOTP / 2FA   

And yes I know the better solution would be to just make sure you close the database but still better than nothing.

**Comment by droidmonkey** [comment]
This doesn't make much sense to me. So only for TOTP output (copy to clipboard, Auto-Type, casual viewing , browser integration) you want an option to force a user to touch their yubikey, if configured, or reenter their password if not. Unfortunately that is very onerous and causes all sorts of unintended side effects and terrible user experience. So yes, the answer is to make sure to lock your database if you are leaving it unattended. 

Put another way, if I am a nefarious actor swooping into your unlocked work station... I don't give a crap about your totp code. I am just going to plug a USB stick in, go to Database -> Export as CSV -> save to stick. Walk away casually. See #5403

**Comment by ShapeShifter499** [comment]
I didn't mean to reenter the password to get the TOTP, I meant to prevent the TOTP setting from being changed or deleted.

But I didn't even think of the idea that if it is unlocked, even with the key removed, that one could export.

**Comment by ShapeShifter499** [comment]
@droidmonkey see the comment I just left on that other issue. What do you think about that?

**Comment by droidmonkey** [comment]
Yah closing this request, changing information is not going to be protected by any second factor once the database is unlocked.
