### ISSUE TITLE
YubiKey getting ejected on KeepassXC open

### ISSUE THREAD

**Issue by robin-checkmk** [keepassxreboot/keepassxc#7207]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
My colleagues and I are using udev rules to lock our devices when a YubiKey is disconnected from the system.
Upon opening the KeepassXC application the YubiKey seems to be ejected, as the system gets locked.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Add `ACTION=="remove", ATTRS{idVendor}=="1050", RUN+="/bin/sh -c '/bin/loginctl lock-sessions'"` to `/etc/udev/rules.d/yubikey.rules` and run `udevadm control --reload-rules`
2. Open KeepassXC application
3. Unlock the locked screen

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
KeepassXC should not cause the YubiKey to be ejected.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
KeepassXC triggers the ejection of the YubiKey.

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.4.3
Revision: 5d6ef0c

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: Gnome
Windowing System: X11

Possibly relevant logs:
```
Dez 06 07:23:56 hostname systemd[8394]: Started Application launched by gnome-shell.
Dez 06 07:23:57 hostname org.keepassxc.KeePassXC.desktop[13404]: QObject::startTimer: Timers cannot have negative intervals
Dez 06 07:23:57 hostname /usr/lib/gdm3/gdm-x-session[8493]: (II) config/udev: removing device Yubico YubiKey OTP+FIDO+CCID
Dez 06 07:23:57 hostname /usr/lib/gdm3/gdm-x-session[8493]: (**) Option "fd" "110"
Dez 06 07:23:57 hostname /usr/lib/gdm3/gdm-x-session[8493]: (II) event22 - Yubico YubiKey OTP+FIDO+CCID: device removed
Dez 06 07:23:57 hostname /usr/lib/gdm3/gdm-x-session[8493]: (II) UnloadModule: "libinput"
Dez 06 07:23:57 hostname /usr/lib/gdm3/gdm-x-session[8493]: (II) systemd-logind: releasing fd for 13:86
```

**Comment by droidmonkey** [comment]
You're using a very old version of keepassxc. Update to 2.6.6 (appimage, ppa, snap ,etc) or try our snapshot at https://snapshot.keepassxc.org 

We have done a lot of work around yubikeys since 2.4.3

Note: if you are using an old yubikey neo, those suck and have a lot of bugs in the firmware, get a new one.

**Comment by robin-checkmk** [comment]
Thanks so much for that lightning-fast answer!

We tried both the snap and the PPA installation with 2.6.6 and can confirm the bug is fixed with both installation options.
