### ISSUE TITLE
Allow copying of passwords without  revealing them.

### ISSUE THREAD

**Issue by ghost** [keepassxreboot/keepassxc#7208]
## Summary
When copying passwords you need to reveal the password to select it and copy it. Selecting dots literally copies the dots. This is an issue if you are in a public place and need to copy password without others seeing. Also an issue if need to login into a  site with screen shared.

## Examples
Either have a button to copy the password or allow selection of the password dots to actually copy password itself.

## Context
Would prefer to be able to copy paste passwords without making them visible. Public places or having to login during a screen share. Would become more convenient.

**Comment by droidmonkey** [comment]
You have a lot of options. Please read the user guide. Double clicking the dots will also copy the password, same with username. However you should be using Auto-Type or browser extension instead. We have a plethora of keyboard shortcuts. Check out the guide, it also comes installed with keepassxc for offline reference. 

https://keepassxc.org/docs/KeePassXC_UserGuide.html

**Comment by ghost** [comment]
thanks
