### ISSUE TITLE
Smart Lock

### ISSUE THREAD

**Issue by pmcl77** [keepassxreboot/keepassxc#7210]
## Summary
It would be a great feature, to have a smart lock functionality. 

## Examples
Depending on what is possible some ideas could be
Do not lock database if computer is
- connected to home network (e.g. wifi or network name)
- connected to a specific bluetooth device

## Context
When I am at home, there is (hardly) any risk, anyone accessing my computer. I would like to leave the database unlocked, when I am home, so that I don't have to unlock it every time I reopen my session. I am reluctant to change setting like "lock when session is locked" because I fear to forget changing the settings when I leave home. This feature would be especially useful when using the browser extension, as now I  always need to switch from my browser to keepass XC, unlock the database, return to the browser and reload the page.

I am using Keepass XC mainly on a macbook M1 with Mac OS Big Sur but also use it on a windows machine.

**Comment by heylix** [comment]
> I am reluctant to change setting like "lock when session is locked" because I fear to forget changing the settings when I leave home.

Why change it at all? You can just not lock your PC while at home.

**Comment by hifi** [comment]
This would require non-trivial amount of integration per every supported platform even to detect the connected wifi network.

I'd suggest to write a script that is called on desktop lock which would check these things and call `keepassxc --lock` if your safe location detection fails.

**Comment by droidmonkey** [comment]
This adds an incredible amount of complexity and logic and platform integration that we are not willing to do at this time. Perhaps a better idea is to have security settings that change based on the current date/time. For example, on weekends and evenings extend the lock timeout significantly. During weekday business hours make it much lower.

Even then, it adds some unpredictability and complexity that are generally _undesired_ in a security critical application.

**Comment by phoerious** [comment]
Going to close this, since I do not expect us to implement it any time soon. As already mentioned, it would add a lot of extra complexity that we don't want to have in a password manager. It's easier with native platform SDKs like the Android or iOS SDK, because they support things like that out of the box, but for a cross-platform C++ application, there's a lot more involved.

**Comment by pmcl77** [comment]
Thanks for all the good feedback, I completely understand it's complex and the point about not having this in a security related app makes a lot of sense!

**Comment by pmcl77** [comment]
Just a question: would there be a way to unlock the db from the browser extension with biometrics?

**Comment by droidmonkey** [comment]
Biometrics is coming to windows and Linux, but you can already use TouchID on mac today.

**Comment by pmcl77** [comment]
Yes, I am using touchid on my macbook air... would be great to unlock from the browserextension, but I don't know if that would be even possible.

**Comment by droidmonkey** [comment]
You can request an unlock from the browser extension that shows the unlock prompt from keepassxc. Doing it directly through the extension itself is very insecure which is why we don't.
