### ISSUE TITLE
KeepassXC Signing key certificate is expired

### ISSUE THREAD

**Issue by Sebi2020** [keepassxreboot/keepassxc#7213]
The KeePassXC PGP certificate cannot be imported anymore, cause the certificate is no longer valid (gpg refuses to import expired certificates). This makes it impossible to test the downloaded binary against the signing certificate. I followed the instructions on the website https://keepassxc.org/verifying-signatures/

Error from GPG (German, but says what I've written above:
```
C:\Users\Admin>gpg --fetch-keys https://keepassxc.org/keepassxc_master_signing_key.asc
gpg: fordere Schlüssel von https://keepassxc.org/keepassxc_master_signing_key.asc an
gpg: WARNUNG: die URI https://keepassxc.org/keepassxc_master_signing_key.asc kann nicht geholt werden: Zertifikat abgelaufen

**Comment by droidmonkey** [comment]
It is not, you need to perform `gpg --refresh-keys`

**Comment by Sebi2020** [comment]
@droidmonkey I exactly followed the instructions and it does not work! Please try it yourself before saying it isn't. `gpg --refresh-keys` makes no sense, if you have no keys to refresh!!

**Comment by droidmonkey** [comment]
I replicated the error on gpg4win, but it is not us....

Cert pulls work perfectly under Ubuntu
![image](https://user-images.githubusercontent.com/2809491/145307569-fc94990f-bf34-479d-a364-c6f4be761af5.png)

Running a simple refresh keys on Gpg4Win doesn't work:
![image](https://user-images.githubusercontent.com/2809491/145307636-f5231612-35e2-40fb-8b99-bc90147a85b5.png)

I can't get it to cough up anymore details, it is fundamentally broken.

**Comment by Sebi2020** [comment]
@droidmonkey Thanks for the information!  I used a Gpg4Win client too. Looks like I should change my GPG package/installation. 
Found this on the Gpg4Win page: https://lists.wald.intevation.org/pipermail/gpg4win-announce/2021-October/000093.html

**Comment by droidmonkey** [comment]
Wow I couldn't find that even after searching real hard. They really need to either put out v4 or update v3.1.6 with this.
