### ISSUE TITLE
Auto-type intermittently doesn't work

### ISSUE THREAD

**Issue by kuba-orlik** [keepassxreboot/keepassxc#7218]
## Overview

When triggering auto-type with an entry that has the URL field set up, the KeepassXC window hides itself, but it doesn't enter the password.

## Steps to Reproduce

1. Create an entry with a username, password and a URL
2. Go to the login form in the app/browser
3. Go back to KeepassXC, highlight the entry, right-click, `Perform auto entry > ` pick any option

## Expected Behavior
The KeepassXC window should hide itself and enter the password to the form in the previous window

## Actual Behavior
The KeepassXC window hides itself, focuses the previous window, but doesn't enter the password

## Context

When I empty the URL field for the given entry, auto-type works correctly.

I have disabled the "Use entry title to match windows for global auto-type" and "use entry URL to match windows for global auto-type" in the settings

KeePassXC - Version 2.7.0-snapshot
Build Type: Snapshot
Revision: d16fc2d

Qt 5.15.2
Debugging mode is disabled.

Operating system: Manjaro Linux
CPU architecture: x86_64
Kernel: linux 5.10.79-1-MANJARO

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (only unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.18.2

Operating System: Linux
Desktop Env: Gnome
Windowing System: X11

**Comment by droidmonkey** [comment]
Which website are you attempting to use? The presence of a URL has no bearing on entry level Auto-Type.

**Comment by kuba-orlik** [comment]
After further investigation I take back what I've said about the issue being connected to the url entry. It just seems that the auto-type functionality just sometimes refuses to work, and triggering it multiple times or shifting windows around makes it eventually "click"

**Comment by droidmonkey** [comment]
OK, can you determine a pattern?

**Comment by kuba-orlik** [comment]
Not yet - will keep an eye on that

**Comment by droidmonkey** [comment]
Closing this, please let us know if the latest snapshot still causes problems.
