### ISSUE TITLE
Generate QR code with TOTP settings

### ISSUE THREAD

**Issue by sorcix** [keepassxreboot/keepassxc#722]
## Expected Behavior
The TOTP menu contains an option to generate a QR code for me to import the TOTP key/settings to an authenticator app on my phone.

## Current Behavior
The TOTP menu only shows TOTP codes and plaintext settings. I have to type the secret key manually if I want to add it on my phone.

## Possible Solution
Generate a QR code inside the app, or (less secure) open a browser window to:

```
https://chart.googleapis.com/chart?chs=256x256&cht=qr&chl=otpauth://totp/name?secretkey
```

## Context
Since 2.2 KeepassXC contains my TOTP secrets. I want to export the most used ones to an app on my phone.

**Comment by droidmonkey** [comment]
I wish the Google Authenticator app would let me export the loaded TOTP codes I already have...

**Comment by yan12125** [comment]
If you use Android, my fork of KeepassDroid is worth a try - https://github.com/yan12125/keepassdroid/tree/totp. I add a notification item that generates TOTP codes.

**Comment by weslly** [comment]
Not exactly what you are asking, but Keepass2Android can generate codes for TOTP entries added on KeepassXC, so you can use it as an alternative to Google Authenticator.

**Comment by sorcix** [comment]
I'm on Android so this actually is a solution for me. 👍

**Comment by weslly** [comment]
@sorcix nice! closing this one
