### ISSUE TITLE
Special characters (tildes) on passwords can't be written with the hidden password mode

### ISSUE THREAD

**Issue by picajoso** [keepassxreboot/keepassxc#7224]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

After launching KeepassXC the database loads and the app asks you for the password to open that database. The password is then introduced while you only see asterisks with each character typed. I have passwords with special  characters in Spanish (tildes on our vowels -> á, é, í, ó, ú) and if I try to type then with that 'hidden password mode', those characters aren't registered with their tilde. An 'á' is transformed to an 'a', and the password doesn't work. 

I have to deactivate the hidden password mode and see what I type as I type it (no asterisks) to be able to introduce those special characters to be able to open that database.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Set a password for a database with special characters like the vowels with tildes in Spanish.
2. Open that database and try to enter the password normally with asterisks showing as you type.
3. The password doesn't work because the tildes are ignored. 

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

The password written while on hidden password mode should work. You shoulnd't need to enable the 'unhidden password mode' to enter the password and start using KeePassXC with your database.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

As I've mentioned, the password with special characters doesn't open the database if you type it with the hidden password mode.

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.6.6
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS Monterey
Computer: Mac mini M1

**Comment by droidmonkey** [comment]
This is a Qt bug,  been reported to them.

**Comment by picajoso** [comment]
Great, thank you. Have you got the link to that bug to follow that conversation? Just out of curiosity.

**Comment by droidmonkey** [comment]
https://github.com/keepassxreboot/keepassxc/issues/1877 first reported to us and https://bugreports.qt.io/browse/QTBUG-73363 is the Qt bug report, still open.

**Comment by picajoso** [comment]
Thank you again.

**Comment by ghost** [comment]
This problem persists on version 2.7.1.  When I try entering a word with a tilde keepassxc do not recognize it but if I make the password visible instead of dots I can put the tilde without any problem. Is there any solution?

**Comment by ghost** [comment]
Has this been solved? I have the last version and continue to have the same issue.

**Comment by picajoso** [comment]
Not to my knowledge.
