### ISSUE TITLE
DB not loading with v2 keyfile created by keepass v2.49

### ISSUE THREAD

**Issue by Epic-1** [keepassxreboot/keepassxc#7225]
Tested on v2.6.4 and v2.6.6

Generated new keyfile.keyx v2 xml in keepass v2.49, updated database security and saved in keepass v2.49 on PC.
Params:  Argon2d, ChaCha20.

db loads fine in Keepass v2.49 and also Strongbox on iOS with new key.

KeepassXC on Mac throughs a Invalid Credentials provided (HMAC mismatch).

**Comment by droidmonkey** [comment]
Make sure the database on your Mac is the one that you updated to use the keyfile. I can guarantee the key file works across all platforms and between KeePass2 and mobile apps.

**Comment by Epic-1** [comment]
The db is stored at a central location accessed via webdav and sftp.  I used a usb stick to test the db and it worked.  Seems there is a problem with webdav on OSX Monterey that wasn't there in Big Sur.

Thanks for the quick follow up.
