### ISSUE TITLE
Unable to open specific Keepass-managed .kdbx database

### ISSUE THREAD

**Issue by Wolfenswan** [keepassxreboot/keepassxc#7229]
## Overview
KeepassXC is unable to open an existing .kdbx database which I've been using with Keepass. The error provided claims "wrong credentials"/"possible corruption". The database works without issues in Keepass and KeepassX. KeepassXC does have no issues opening databases newly created by Keepass. Exporting the file from within Keepass or clearing it of entries does not prevent the issue.

## Steps to Reproduce
No general reproduction possible, only specific .kdbx appears to be broken.
Happy to provide log-entries (if possible) or an emptied copy of the file in question.

## Expected Behavior
Open & read the .kdbx as in Keepass.
Or provide a specific reason on why the database is not compatible.

## Actual Behavior
Opening the database fails, claiming the credentials are invalid or the file might be corrupted.

## Additional Info
The file can be opened without issues using both Keepass and KeepassX.
To test whether it was a general fault, I created a new, empty .kdbx using Keepass. No issues.
To test whether a specific entry was the culprit, I created a copy of the broken database and deleted all entries. No improvement.
I ultimately did manage to "port" my database by creating a new database using KeepassXC, open it in Keepass and importing all data from the old database.

KeePassXC - 2.6.6
Revision: 9c108b9

Operating System: Tested on Windows & Ubuntu (Gnome)

**Comment by droidmonkey** [comment]
You can provide the empty, broken database for our investigation. However the hmac error is rather precise, it means the header can't even be decrypted because the file is corrupted or the credentials were wrong. We haven't even got to the guts of the database at that point.

**Comment by Wolfenswan** [comment]
As said, the credentials are correct and the database works fine in Keepass/KeepassX, so from my superficial knowledge I wasn't sure where I could begin "uncorrupting" the file. Should I mail the emptied database to a specific address?

**Comment by droidmonkey** [comment]
team@keepassxc.org please

**Comment by droidmonkey** [comment]
I upconverted your broken database to KDBX4 in KeePass and everything worked. I think it was just completely broken from KeePass OR KeePass2Android. Convert the database in KeePass by going to File -> Database Settings -> Security -> Choose Argon2d as the KDF. Save the database and you'll be able to open in KeePassXC.
