### ISSUE TITLE
Sign macOS releases for Gatekeeper support

### ISSUE THREAD

**Issue by williamtheaker** [keepassxreboot/keepassxc#723]
## Current Behavior
When double clicking on KeePassXC.app, the application fails to open if Gatekeeper has been disabled in macOS. A system popup states "KeePassXC" can't be opened because it is from an unidentified developer

## Expected Behavior

Application passes code signing check and executes without user intervention.

## Possible Solution

Fixing this requires an Apple Developer account which costs $100/year. Users could be told to disable Gatekeeper or whitelist KeePassXC, but that's not ideal.

https://developer.apple.com/library/content/documentation/Security/Conceptual/CodeSigningGuide/Introduction/Introduction.html
https://support.apple.com/en-ie/HT202491

**Comment by phoerious** [comment]
have a valid certificate which we use for signing our Windows binaries. Unfortunately, Apple only supports Apple certificates. Dick move from their side.

**Comment by mritun** [comment]
I won't comment on Apple's business decisions, but I can pitch-in for a certificate.

**Comment by phoerious** [comment]
Help is always appreciated.

**Comment by christianbalzer** [comment]
Is a signed version in progress now? :)

**Comment by phoerious** [comment]
Not yet. But we will have one in the foreseeable future.

**Comment by droidmonkey** [comment]
The latest release, 2.2.4, has been signed by our key!
