### ISSUE TITLE
References not getting resolved via FreeDesktop secret service

### ISSUE THREAD

**Issue by laalsaas** [keepassxreboot/keepassxc#7231]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
When quering an entry of the DB via Freedesktop's secret service API via it's attributes, and that attribute contains a reference, the reference doesn't get "resolved", meaning the you can't access it by the value of the reference, but only via the text which declares the reference. 

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Enable secret service integration.
2. Create a sample entry with a title and a Password.
3. Add an attribute called `title`, which is a reference i.e. to the title of the entry (`{REF:T@I:<UUID>}`).
4. Make sure the group that entry belongs to is exposed via freedesktop secret service.
5. Try to query the password via its attribute `title` and its value, the title of the entry:
`secret-tool lookup title "<Title>"` -> not working.
6. Try to query the password of that enty via the literal value of the attribute `title`: `secret-tool lookup title "{REF:T@I:<UUID>}"` -> works.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Step 5 should work, Step 6 shouldn't, the reference should get resolved.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Step 5 doesn't work, Step 6 does, the reference isn't resolved.

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.6

Qt 5.15.3
Debugging mode is disabled.

Operating system: NixOS 21.11 (Porcupine)
CPU architecture: x86_64
Kernel: linux 5.10.81

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- libgcrypt 1.9.4

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: i3
Windowing System: X11

**Comment by droidmonkey** [comment]
This has been fixed in the upcoming 2.7.0 release already.
