### ISSUE TITLE
Generate list of passwords

### ISSUE THREAD

**Issue by gkvdvaart** [keepassxreboot/keepassxc#7235]
## Summary
Like in Keepass2 I would like to be able to generate a list of passwords rather than just one example.

## Examples
Set passwordoptions
![image](https://user-images.githubusercontent.com/31079313/146337692-8bdea6ad-236c-40b1-ac10-792ae1e2abc1.png)

List generated examples based on the settings from the previous screen
![image](https://user-images.githubusercontent.com/31079313/146337745-edbdbfa5-dcbd-4e48-8395-b8392dbc8731.png)

## Context
We manage some systems where we need to create passwords for new users. Unfortunately these systems do not support for connection to our IAM tool of forced passwordresets after login. To prevent too obvious passwords we need generated passwords.

**Comment by krugerk** [comment]
Hello @gkvdvaart ,
I just saw your post here and thought I might reply.

From the looks of it, you would like to use XC to generate several passwords at a time. It looks like you would like to do this from the GUI.

The command line interface, keepassxc-cli, provides a generate command which will generate a new, random password. 

```bash
$ keepassxc-cli generate
Z1AbGfVMkEegRHDX5Je5FgCrsipkiL6e
```

The generate command also accepts several parameters for influencing the output: adjusting length, excluding some characters, and assuring characters from particular sets.

```bash
$ keepassxc-cli generate --help
Usage: keepassxc-cli generate [options]
Generate a new random password.

Options:
  -q, --quiet            Silence password prompt and other secondary outputs.
  -L, --length <length>  Length of the generated password
  -l, --lower            Use lowercase characters
  -U, --upper            Use uppercase characters
  -n, --numeric          Use numbers
  -s, --special          Use special characters
  -e, --extended         Use extended ASCII
  -x, --exclude <chars>  Exclude character set
  --exclude-similar      Exclude similar looking characters
  --every-group          Include characters from every selected group
  -h, --help             Display this help.
```


If you need twenty such passwords in one go, it should be easy enough to loop over for the twenty passwords:

```bash
$ for iteration in {1..20}; do keepassxc-cli generate; done                                                                                 
d4e8s8TkrC3CAkyJ3snKjAgPiOgJ7Xjg
7eph9XNhtrJcYA0uO7SptTvxlox956Qv
MgB0hPeDwJrloCD0vs9NghQ8BN32Qs7J
7KVY9mRXKEOpNUghEgXLKZePglXuBjM1
iEXWcGbhT9VQmbCr7ugsah7VTeQOcIvV
UT6QHtJLr0YRM1PBX1z2wbke9Ata3AVf
2W8TUI3ifc6fOgN1hcubvogDgPcQuEUS
6u2o7tCQTdRQLffMmjM9JAC5k9QPXhHp
KwPZe5n64h2uZGjjYmoWIy58D1Iagrg1
GqTSYtWGJpLuib7iMzUo65zFDuu2v1Uo
Ax81GeDsDNMq2Th88UbYgYeNt35a8l9i
kuYZ7VzXtW1pCWQm5DW6Y4gVk7BHFwqf
3kbncO4kSQ1hZeYIf5JVHNKLBamSXPb2
UZUEuqBgRDw8sHGXbcZ3nNro4FkabW9v
jGOGxQNsWS5oiQGDVSqR9Ki2N0wlkalU
HCGpvGUH12zBObztEowjTCy4XClNkGTA
x5uDbJFYvGvKUZDSgfxWdovN2ZwDb5iM
6HDRTTsmq6eyWiPPMfogWHuafbGsg3Tn
HI210fN91481s1vyNL5xf05oblJ3ahjL
Opq9qWUgW12k6qEbXgVJ9WeXcE3c5yIb
```



Might this work for you?
Which other features might you like besides these?

**Comment by gkvdvaart** [comment]
Thnx @krugerk 
After fiddling with some old-fashioned batch-script I have a workaround that suits my needs for now.

**Comment by smbsid** [comment]
For people using PowerShell, you can use this command to generate a list of 10 passwords for example:
foreach($i in 1..10) { .\keepassxc-cli.exe generate -l -U -n -L 9 -c '%@&$' --exclude-similar}
