### ISSUE TITLE
Database window titlebar showing incorrect filename and without pathname

### ISSUE THREAD

**Issue by wjdodd** [keepassxreboot/keepassxc#7236]
I imported my KeePassX database, which was stored in a file with filename <name> (not shown for security). I saved the resulting KeePassXC database with a new filename <NEWdifferentname>. However, when I open <NEWdifferentname> in KeePassXC, the caption in the database window title bar is "<name> - KeePassXC" (i.e., the name of the imported KeePassX file), not "<NEWdifferentname> - KeePassXC". This is alarming to me as a possible new user of KeePassXC because I cannot be sure I am using the new file and won't overwrite my current KeePassX database. Further, the KeePassX title bar showed the full pathname to the file in use; KeePassXC should do the same or at least offer this as an option, because it helps the user be sure the correct file is in use. I am using the version 2.6.6 AppImage under Debian.

**Comment by droidmonkey** [comment]
We show the file path before you even unlock the database. The title pulls from the database name configured in the database settings. Set it to something that makes sense. I belive it you leave that blank we will show the filename. We aren't going to change this behavior.

**Comment by droidmonkey** [comment]
Confirmed if the database name is blank we show the file name. https://github.com/keepassxreboot/keepassxc/blob/develop/src/gui/DatabaseTabWidget.cpp#L586
