### ISSUE TITLE
Upgraded to Monterey - KeePassXC is not supported

### ISSUE THREAD

**Issue by ofarrellk** [keepassxreboot/keepassxc#7238]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

Upgraded Mac to Monterey ... now receiving

You can’t open the application “KeePassXC” because this application is not supported on this Mac.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. upgrade to monterey
2. attempt to open KeePassXc
3. 

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

Expect app to open

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

App does not open, get message - You can’t open the application “KeePassXC” because this application is not supported on this Mac.

## Context
[NOTE]: # ( Give us any additional information you may have. )

Tried removing and reinstalling, no luck

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION
Revision: REVISION

Not able to show About, but tried installing  Binary bundle (macOS 11.1+)

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS

Also tried - brew install --cask keepassxc
but get the message - /usr/local/Homebrew/Library/Homebrew/os/mac/version.rb:32:in `block in from_symbol': unknown or unsupported macOS version: :dunno (MacOSVersionError)

**Comment by droidmonkey** [comment]
Interesting, the brew error is from brew not from us.

**Comment by phoerious** [comment]
I'm using KeePassXC on 11.1 without any issues. There must be something else going on. Be sure to download for the correct target architecture.

**Comment by ofarrellk** [comment]
I'm on Mac OS 12.1, worked fine on 11.x

**Comment by ofarrellk** [comment]
Update: I tried DMG Installer (Intel) V2.6.6 and that worked.  So, reinstalling with the appropriate version was all I needed.  Thanks.

**Comment by gaeldb** [comment]
Same problem.
Fixed after `brew upgrade keepassxc`
