### ISSUE TITLE
Crash when closing tab during password processing

### ISSUE THREAD

**Issue by Semnodime** [keepassxreboot/keepassxc#7239]
## Overview
KeepassXC crashes when a database tab is closed while it attempts to open it (key derivation function processing in progress).

## Steps to Reproduce
1.  Two Database tabs
2.  Enter wrong password into database tab
3. While password is processed, close tab
4. Short wait period (till end of key derivation function) ~0.1-2s

## Expected Behavior
No crash.

## Actual Behavior
Crash. App closes.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.6.6
Revision: unknown

Operating System: Linux Mint 21
Desktop Env: Cinnamon
Windowing System: X11

**Comment by droidmonkey** [comment]
This is still a problem and made slightly worse with Quick Unlock.
