### ISSUE TITLE
KeePassXC detects itself as a other running secret service

### ISSUE THREAD

**Issue by UOBW** [keepassxreboot/keepassxc#7240]
### Overview
I'm new to KeePassXC (I migrated a few weeks ago from the firefox buid-in password manager), so maybe I just overlooked something obvious, but I don't think so. The bug is, that KeePassXC detects itself as a other running secret service. So when I navigate to Settings/Secret Service Integration I get the following message:
![Screenshot](https://user-images.githubusercontent.com/76259564/147058910-7f193289-48d9-4607-af31-3219c2a2b1df.png)
It's not a really big problem, just kill the pid from the message and everything works great, but it is annoying, that you have to kill the other process before you can change the settings.

### Steps to reproduce

1. Enable the Secret Service Integration
2. Relogin to restart your session

### Expected behavior
That I can edit the settings.

### Actual Behavior
You can't edit the Secret Service settings without killing the other process.

### Context
KeePassXC - Version 2.6.6
Revision: 9c108b9

Qt 5.15.2
Debugging mode is disabled.

Operating system: Ubuntu 21.10
OS Type: 64-bit
Hardware Model: ASUSTeK Computer Inc. K50IJ
Memory: 3,8 GiB
Processor: Pentium(R) Dual-Core CPU T4300 @ 2.10GHz × 2 
Graphics: Intel® Mobile GM45 Express Chipset
Disk Capacity: 320,1 GB
GNOME Version: 40.4.0
Windowing System: Wayland
CPU architecture: x86_64
Kernel: linux 5.13.0-22-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- libgcrypt 1.8.8

Thanks.

**Comment by droidmonkey** [comment]
Are you starting keepassxc twice? If you kill the other process and the one showing you that message doesn't disappear then you are. Make sure you don't have both a snap version and a natively installed version running at startup (for example)

**Comment by UOBW** [comment]
It seems like it starts itself at startup and then I start it again so it runs twice. But the desktop entry should just tell the already running process to show the window. So I have no idea why this happens.

**Comment by droidmonkey** [comment]
You are most likely running the snap and the native app separately. They don't have any way to talk to each other. You need to fix that on your end, recommend uninstalling one of the installs or not starting it a second time.

**Comment by UOBW** [comment]
I've checked it and have no two instances installed (which -a keepassxc returned /use/bin/keepassxc and /bin/keepassxc), but the bug has solved itself and doesn't occurs anymore.
