### ISSUE TITLE
bug: line breaks in "notes" fields are not handled in CSV export

### ISSUE THREAD

**Issue by monperrus** [keepassxreboot/keepassxc#7243]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
I'm exporting a database with lots of entries with a "notes" field. This field often contains line breaks / newlines.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Create an entry with a multiline "notes" field
2. Export it to CSV

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
The CSV is well-formed and can be imported again

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
The CSV file is broken and cannot be imported

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.6.6
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: XFCE
Windowing System: X11

**Comment by fluks** [comment]
Can't replicate this on develop branch.

**Comment by droidmonkey** [comment]
Agree this is not a problem
