### ISSUE TITLE
Unable to verify download 

### ISSUE THREAD

**Issue by AGlymph** [keepassxreboot/keepassxc#7248]
## Overview
New to KeepassXC and trying to install for the first time. Attempted to verify download both by gpg and Windows User Account. 

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Run either gpg commands found on Verify download page in Powershell
2. Open installer in Windows

## Expected Behavior
Expected to be prompted by Windows User Control to allow install, but was not. 
Run gpg command be met with the proper cerfication confirmation. 

## Actual Behavior
gpg reply message: Certificate expired
No Windows User control verification pop up. 

## Context
Other apps I installed recently do prompt the User Control pop up. 

Also, I don't know GNU license agreements, but when I got to the GNU agreement at the bottom there are the terms "James Hacker" and "President of Vice". Seems strange to me, but hopefully these are jokes I just don't get. 

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.6.6

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 10

**Comment by droidmonkey** [comment]
Gpg4Win has a bug in it that prevents proper certificate verification. That was discovered and discussed here: https://github.com/keepassxreboot/keepassxc/issues/7213

You will receive the elevation prompt after you choose your install options and before anything is actually installed.
