### ISSUE TITLE
YubiKey Bio Integration

### ISSUE THREAD

**Issue by WildDogOne** [keepassxreboot/keepassxc#7251]
## Summary
At the moment KeepassXC is not compatible with YubiKey Bio [Documentation](https://support.yubico.com/hc/en-us/articles/360013779759-Using-Your-YubiKey-with-KeePass)
This may have to do with the fact that Keepass uses OTP for authentication afaik.
However the Biometric version of YubiKey only supports FIDO2

## Context
I personally think it would be important to have support for the biometric version of YubiKey as they bring in another security factor towards authentication against KeepassXC

**Comment by mlavi** [comment]
I recently got one too, but just read https://keepassxc.org/docs/#faq-yubikey-why-hmac-sha1

**Comment by droidmonkey** [comment]
We won't be integrating with the "bio" version, that does not support HMAC-SHA1.

**Comment by cytoCarl** [comment]
I sure wish I had known about bio not working with keepassxc and I would've ordered some other yubico product that did. All I saw at first was the blog that it did support it... just not the fine print.

**Comment by WildDogOne** [comment]
story of my life @cytoCarl

**Comment by scaljeri** [comment]
Is this still the case?
