### ISSUE TITLE
Use mimalloc with security mitigations enabled

### ISSUE THREAD

**Issue by adolfogc** [keepassxreboot/keepassxc#7255]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
[mimalloc](https://github.com/microsoft/mimalloc) is a custom memory allocator that comes with various security mitigations implemented,  from their README:

> mimalloc can be built in secure mode, adding guard pages, randomized allocation, encrypted free lists, etc. to protect against various heap vulnerabilities. The performance penalty is usually around 10% on average over our benchmarks.

And from their CMakeLists.txt:

> Use full security mitigations (like guard pages, allocation randomization, double-free mitigation, and free-list corruption detection)

It has support for C++, integrates with CMake and can statically/dynamically override malloc and new.

**Comment by droidmonkey** [comment]
What is the benefit over our existing use of high entropy ASLR, control flow guards, and secure memory erase? Not a fan of adding another dependency and library for memory management.

**Comment by adolfogc** [comment]
Hi @droidmonkey, thanks for the information. It's been long since I've worked with the codebase, so I wasn't aware of those aspects.
