### ISSUE TITLE
keepassxc-cli returns "PROTECTED" value of the password field of an entry

### ISSUE THREAD

**Issue by ghost** [keepassxreboot/keepassxc#7256]
## Overview
What I want to do is to get the password from an entry from the command line. The same method worked just fine one of the previous versions of keepassxc, now I get "PROTECTED" value instead of particular password. The database itself works perfectly fine.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. keepassxc-cli show ~/database.kdbx entry_name

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

I expect to get the password of an entry "entry_name"

## Actual Behavior

```
Enter password to unlock ~/database.kdbx: 
Title: entry_name
UserName: 
Password: PROTECTED
URL: 
Notes:
``` 

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.6.6
Revision: 9c108b9

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: Openbox

**Comment by ghost** [comment]
ok, I found solution myself - I needed to add -s parameter to my command, after show. Please close that issue.

**Comment by droidmonkey** [comment]
https://github.com/keepassxreboot/keepassxc/blob/develop/docs/man/keepassxc-cli.1.adoc#L255
