### ISSUE TITLE
Keepassxc crashes when attempting to download favicons

### ISSUE THREAD

**Issue by ghost** [keepassxreboot/keepassxc#7258]
## Expected Behavior

Hi ! 
KeepassXC crashes when I attempt to download some favicons. Some work fine, and others crash the app.
I first tried batch dowloading for all entries by selecting them all. I thought that was what crashed it, but it also crashes when downloading icons for entries one at a time.
## Steps to Reproduce (for bugs)

1. Right click an entry
2. Choose download icon

## Debug info
KeePassXC - Version 2.6.6
Revision: 9c108b9

Qt 5.15.2
Debugging mode is disabled.

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 5.15.12-arch1-1

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- libgcrypt 1.9.4-unknown

Happy new year everyone !

**Comment by droidmonkey** [comment]
What is the site?

**Comment by ghost** [comment]
Hi,

It happens for multiple sites. It looks like some kind of timeout issue, if I try again a couple times I sometimes get the "favicon not found" message. Other times it just displays a black square and then eventually crashes. 
![Capture d’écran de 2022-01-02 21-15-46](https://user-images.githubusercontent.com/25869334/147888442-330ea37e-ed6d-4132-8880-770be511f650.png)
![Capture d’écran de 2022-01-02 21-16-44](https://user-images.githubusercontent.com/25869334/147888445-7fd86039-f0c1-447b-8fc6-0a7207ae46fa.png)

Also tried switching to the duckduckgo service but the result is the same. 
Funny that it just works for some site. An example site that crashes it is http://customer.rueducommerce.fr. It doesn't exist anymore, but is still shouldn't crash

**Comment by droidmonkey** [comment]
I cannot replicate this on develop branch in Windows. That window is actually not a crash window, that is a not responding window. If you let it continue (Attendre) does it actually crash? I do note that the window does become non-responsive under Windows, but it does not crash.

**Comment by ghost** [comment]
I did try to wait it out, but the "not responding" popup keeps popping up, and nothing happens.

**Comment by droidmonkey** [comment]
I did notice that clicking the download button on Linux causes an infinite loop of trying to download the icon. Will dig deeper into this one.

**Comment by ghost** [comment]
Happy to help in testing if needed.

**Comment by droidmonkey** [comment]
this was fixed
