### ISSUE TITLE
Autotype use wrong keyboard layout

### ISSUE THREAD

**Issue by forrest96er** [keepassxreboot/keepassxc#7259]
## Overview
auto-type do not work if system default keyboard is to US but window layout of keepass is set to different layout. 

## Steps to Reproduce

1. set system default keyboard to us
2. set keyboard of keepass window and window of destination ( login etc.) to german
3.  choose one or more characters in  username/ password  string that differ from us layout  ( for example @ )
4. use the auto type feature 
5. now all characters that differ from us layout, will be replaced with the us ones   ( @ becomes " ... )

## Expected Behavior
no change of characters 
keepass should use keepass window keyboard for auto type

## Actual Behavior
change of characters
keepass uses system default keyboard for auto type

KeePassXC - 2.6.6
Revision: 9c108b9

Operating System: Linux  ( not tested on other OS)
Desktop Env: Cinnamon
Windowing System: X11

**Comment by droidmonkey** [comment]
This is fixed in develop branch already
