### ISSUE TITLE
Feature Request: Add custom icon from URL

### ISSUE THREAD

**Issue by magkopian** [keepassxreboot/keepassxc#726]
It would be nice if there was an option for adding an icon by providing a direct URL to it, as an alternative to adding it from a local file.

## Expected Behavior
There should be a way for the user to add a custom icon from a direct URL in addition to adding one from a local file.

## Current Behavior
There is currently no way to add a custom icon directly from a specific URL, but only from a local file.

## Possible Solution
Adding a forth button with the label "Add custom icon from URL", which will open a dialogue box prompting the using to enter the URL to the icon, would be perfect in my option.

## Steps to Reproduce (for bugs)
Not applicable.

## Context
Occasionally, I find websites where the favicon downloading fails, because the icon is kept in a non standard location and is only referenced in HTML. In those cases, finding the actual URL to the favicon at least for me is just a matter of seconds, after looking at the HTML code. But having to download it locally first in order to add it later, is kind of tedious.

Such a feature, also allows the usage of arbitrary images from the web as icons for entries and groups, without necessarily having to be favicons of websites. Especially for groups, if you want to use the favicon of a website as its icon, there is no way to fetch it directly from the web as groups don't have a URL property. The only workaround to this, is to create a dummy entry with the URL to the website, download the favicon so it will be stored to the database, skip saving the entry and finally add the icon to the group.

## Debug Info
KeePassXC - Version 2.2.0 (Debian Package)
Revision: caa49a8ef3ee28ed478192389b21d61107b3b8e0

Libraries:
- Qt 5.7.1
- libgcrypt 1.7.6-beta

Operating system: Debian GNU/Linux 9 (stretch)
CPU architecture: x86_64
Kernel: linux 4.9.0-3-amd64

Enabled extensions:
- KeePassHTTP
- Auto-Type
- YubiKey

**Comment by hifi** [comment]
I was rather thinking of having an actual HTML parser that would pull the `<link rel="icon">` info like a browser would. It's more common these days to have that in favor of the old favicon.

Would depending on libxml2 be bad? It would probably be rather trivial to parse HTML documents with it (AFAIK it has HTML mode) and find the necessary tag making the icon downloader more robust.

1. Download the page, parse and search for link icon, try downloading that if present (make a good guess which one if many, try all until one works)
2. Try `favicon.ico`
3. Try `/favicon.ico`

**Comment by magkopian** [comment]
@hifi This has already been [discussed](https://github.com/keepassxreboot/keepassxc/issues/32#issuecomment-252090527) in the past, and we all agreed that pulling an actual HTML parser as a dependency for something that its mail purpose is to be a password manager is a bit too much. 

Also, the occasional failure of the favicon download is not the only reason I made this feature request, there are at least two more use case. First, for allowing the usage for arbitrary images found on the web to be used as icons, and second for making the addition of a custom icon to a group easier as groups lack of a URL property.

**Comment by hifi** [comment]
Maybe that is where a proper user manageable plugin architecture would help to keep the main program slim and outsource the ugly bits.

On topic: what if instead of a new button the icon download button always opens up a dialog where you select either "[X] Try to download the icon automatically" or you type in the url?

**Comment by magkopian** [comment]
@hifi That also a nice idea, or possibly when pressing the "Add custom icon" to ask the user whether they want to add an icon from a local file or a URL.

**Comment by droidmonkey** [comment]
Closing this in favor of #1459
