### ISSUE TITLE
Increasing Font Size

### ISSUE THREAD

**Issue by nogueira13** [keepassxreboot/keepassxc#7260]
## Summary
I am a very often user of keepassxc and I can't find in configuration options how to increase the font size. The letters are foo small

## Context
I think that persons that have some visual deficiency have to use a magnifying glass to read the screen's information..  

![Small_letters_in_the_screen](https://user-images.githubusercontent.com/22840704/148075332-bc403c0e-25d3-43a5-9de8-f1444b8db226.png)

**Comment by droidmonkey** [comment]
We use the same font size that your system uses, or at least what Qt thinks is the system font size. You probably need to upscale the UI, try using one of these environment variables to properly scale the UI to your screen size (this is a notorious problem on Linux with Qt): https://doc.qt.io/qt-5/highdpi.html#high-dpi-support-in-qt

**Comment by droidmonkey** [comment]
#6822

**Comment by venkatarangan** [comment]
As said above, to increase the font size for KeepassXC in Windows 11, I followed the suggestion said in https://github.com/keepassxreboot/keepassxc/issues/621. 

It is to, set environment variable to a magnification factor.  I used the following command from windows terminal:
SETX QT_SCALE_FACTOR 1.25
