### ISSUE TITLE
Database unlock password text box does not recognise caret character (^)

### ISSUE THREAD

**Issue by ReneErlerTUC** [keepassxreboot/keepassxc#7261]
Hi,
when typing in the password in the text box to unlock the database it does not recognise the ^-character. Thus it is not possible to unlock a database which is protected with a password containing this character.

## Steps to Reproduce
1. Open up KeePassXC
2. Put the cursor into the database unlock password text box
3. Press the caret key on your keyboard. This is located right below the esc key on my German QWERTZ keyboard (see keyboard info below)
4. Caret character not showing up in the text box

## Expected Behavior
I expect pressing the caret key on my keyboard to produce a caret character in the text box.

## Actual Behavior
Pressing the caret key on my keyboard just does nothing. The keystroke is just ignored.

## Context
A workaround is by clicking the little eye icon to make the password in the text box visible. In that case - strangely - the text box recognises the caret key.

## Debug Info
KeePassXC - Version 2.6.6
Revision: 386b79a

Qt 5.15.2
Diagnosemodus ist deaktiviert.

Betriebssystem: macOS 11.6
CPU-Architektur: arm64
Kernel: darwin 20.6.0

Aktivierte Erweiterungen:
- Auto-Type
- Browser-Integration
- SSH-Agent
- KeeShare (nur unbestätigtes Teilen)
- YubiKey
- TouchID

Kryptographische Bibliotheken:
- libgcrypt 1.9.3

Operating System: macOS 11.6.1
Keyboard: Built-in physical German QWERTZ keyboard in MacBook Air M1 2020

**Comment by droidmonkey** [comment]
This is a qt bug, and a duplicate report

**Comment by ReneErlerTUC** [comment]
Ah ok, I tried to search the issues before reporting, but couldn't find anything. Sorry for the duplicate.
