### ISSUE TITLE
AutoType with locked database doesn't work

### ISSUE THREAD

**Issue by Tommy-01** [keepassxreboot/keepassxc#7262]
## Overview
When the User utilize the global Autotype shortkey, nothing happens, when the Database is locked.

## Steps to Reproduce
1. Lock the Database
2. Focus the Website with the input field
3. press the global Autotype shortkey

## Expected Behavior
The Keepass login field comes up to unlock the Database.

## Actual Behavior
Nothing happens, when the Database is locked and the global Autotype shortkey is pressed.

KeePassXC - 2.6.6
Revision: 9c108b9
Distribution: AppImage

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux Mint 20.02
Desktop Env: Cinnamon

**Comment by droidmonkey** [comment]
Are you sure the browser isn't trapping the shortcut key you defined? This does work, I promise. Try on another app like Text Editor.

**Comment by droidmonkey** [comment]
Also try our snapshot build which has made many changes to Auto-Type: https://snapshot.keepassxc.org

**Comment by Tommy-01** [comment]
> Are you sure the browser isn't trapping the shortcut key you defined? This does work, I promise. Try on another app like Text Editor.

I try two Text Editors, but sadly nothing happens.
It only works, when the DB is unlocked.
Then it also works with the Browser (Firefox).

**Comment by Tommy-01** [comment]
> Also try our snapshot build which has made many changes to Auto-Type: https://snapshot.keepassxc.org

Same behavior with the latest Snapshot. Tried on two Linux Mint Machines.

**Comment by Tommy-01** [comment]
KeePassXC - 2.6.6
Revision: 9c108b9
Distribution: AppImage

Ok, i played a little.. maybe there is an problem with the kind of locking the DB.

What i tried..
Case 1:
- start KeePass
- Use the global AutoType Shortkey
--> nothing happens
- unlock the db
- lock it with "Database --> Lock Database (STRG+W)"
- Use the global AutoType Shortkey
--> nothing happens

Case 2:
- start KeePass
- Use the global AutoType Shortkey
--> nothing happens
- unlock the db
- lock it with the right click menu in the tray
- Use the global AutoType Shortkey
--> its working!

Repeat Case 1
-> its still not working

**Comment by Tommy-01** [comment]
Sry, i think i got it!
To use the global AutoType shortkey, there must be an DB selected.
I thought "global" means, this works for every DB so you dont have to select one before using the global shortkey.

**Comment by droidmonkey** [comment]
You closed the database with Ctrl+w, not lock it. Ctrl+L locks it or the padlock icon in toolbar.
