### ISSUE TITLE
KeePassXC TOTP not working with some websites.

### ISSUE THREAD

**Issue by clicky6** [keepassxreboot/keepassxc#7265]
KeePassXC TOTP not working with some websites like Proton Mail.

Windows 11

**Comment by droidmonkey** [comment]
Make sure your system time is synchronized with a time source (time.windows.com). Are you referring to the browser extension being unable to fill totp fields? Or the totp itself being wrong?

**Comment by 0xpr03** [comment]
> Are you referring to the browser extension being unable to fill totp fields? 

Sorry for the noise but that does happen sometimes (and for some websites it never works), I just don't see a reason to report it, as it's 99% the website.. So my guess is that it's about websites and the plugin.

**Comment by clicky6** [comment]
@droidmonkey 
TOTP itself being wrong.
And I don't use the browser extension.

**Comment by droidmonkey** [comment]
Then you need to sync your computer time and verify the secret is correct.

**Comment by clicky6** [comment]
The problem was with time syncing.
THANKS...
