### ISSUE TITLE
Entry specific auto-type hotkey

### ISSUE THREAD

**Issue by epmsmid** [keepassxreboot/keepassxc#7267]
## Summary
When applications use a centralised authentication server, different applications can use the same username/password.
If an auto-type hotkey can be specified for an entry, you can define one entry for those applications and easily start auto-typing.  
(For KeePass the HotKeyEnabler plugin provides this feature.)

**Comment by droidmonkey** [comment]
Recommend using the window association feature of Auto-Type on the entry itself to achieve this behavior. In the next release we also made significant improvements to the Auto-Type selection dialog allowing you to search for an entry.

**Comment by epmsmid** [comment]
Window association can be an option in some cases. There are also cases when there is no appropriate title. This can be the case for e.g. command-line applications like SSH.

**Comment by hifi** [comment]
The search feature covers that nicely. You can also associate terminal window titles for SSH passwords.

It's also highly recommended to use SSH keys where possible eliminating the need to type a password.
