### ISSUE TITLE
Windows opening Welcome screen creates .kdbx file

### ISSUE THREAD

**Issue by JRSav** [keepassxreboot/keepassxc#727]
## Expected Behavior
  This is based on Windows 10 1703. 
   The database file created in the opening Welcome screen and/or drop down menu should be a .kdb file.

## Current Behavior
  Both the welcoming screen "Create New Database" and the drop down "Database" menu defaults to creating a .kdbx database. Keypassxc **does not** read .kdbx files.
  Once past the opening Welcome screen the default file creation changes to .kdb.

## Possible Solution
  Change the default file extension created by the opening screen. Once past the opening Welcome screen the default file creation changes to .kdb.

## Steps to Reproduce (for bugs)
1. I verified twice by uninstalling Keypassxc. 
2. Delete database.
3. Run CCleaner to clean registry.
4. Reinstall.

## Context
  A lay person would not be able to open the database they created on the initial Welcoming screen. I'm sure it would discourage many Windows users.

## Debug Info
KeePassXC - Ver 2.20 Win64
Revision: 

Libraries:
- 

Operating system: Windows 10 1703
CPU architecture: 
Kernel: 

Enabled extensions:
- None

**Comment by TheZ3ro** [comment]
KeePassXC does read kdbx files. When I try to create a new database (both from the welcome screen and from the icon) it select only the kdbx format.

**Comment by phoerious** [comment]
I'm really not quite sure what you are talking about. KeePassXC, in fact, reads nothing else but KDBX files. A KDB file can only be read through the import function which, in turn, creates a KDBX from it.

**Comment by JRSav** [comment]
I had a prior copy of Keepass ver1.29 on my system. There must have been crosstalk between the two . Sorry for the interruption.

**Comment by phoerious** [comment]
KeePass is a totally different application.
