### ISSUE TITLE
Copy entries and folders from one database to another

### ISSUE THREAD

**Issue by Gabro86** [keepassxreboot/keepassxc#7272]
## Summary
I would like to copy password entries and folders from one database to another. Right now I can only move password entries and folders from one database to another, but the moved entry or folder is deleted from the source database.

## Context
Let's say a user has multiple databases for different purposes, e.g. one database for work and one personal one. Now the user opens up two databases in KeePass XC. KeePass XC shows two tabs, one for each database. Now the user wants to copy one password from one database to the other. Right now the user needs to duplicate the password entry and move the duplicate password entry to the other database. This would be a lot easier if KeePass XC would have a way to copy the password entry to the clipboard, so that the user can paste it into the other database.

**Comment by droidmonkey** [comment]
Click and drag, then hold CTRL, then drop where you want it. A copy will be made. There are already requests on here for a better way to do that. Thank you!

**Comment by zackmark29** [comment]
About to ask this also. Hopefully there will be an option in the settings to enable drag and drop without pressing CTRL
