### ISSUE TITLE
Buttons to add/edit attachments "squished", illegible

### ISSUE THREAD

**Issue by sts10** [keepassxreboot/keepassxc#7276]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
Trying to add an attachment to a KeePass entry. For some reason, the 4 buttons are squished so much that I can't read what they do!

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Edit an existing KeePass entry in KeePassXC 2.6.6
2. Navigate to the Advanced tab
3. Look at Attachments sections

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Expect to be able to read the buttons to add an attachment

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
The buttons are "squished" so much that I can't read the labels on the buttons, even when I made KeePassXC full screen.

![attachment-buttons-squished](https://user-images.githubusercontent.com/4871664/148832822-c966ddb5-a058-4a64-9c97-d0ef6fe030ac.png)

## Context
[NOTE]: # ( Give us any additional information you may have. )
Maybe it's something on my system?! Cuz I'd imagine this would have been caught and fixed a while ago if it was a widespread issue?

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.6
Revision: 9c108b9
Distribution: Snap

Qt 5.9.5
Debugging mode is disabled.

Operating system: Ubuntu Core 18
CPU architecture: x86_64
Kernel: linux 5.15.8-76051508-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- libgcrypt 1.8.1

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: KDE
Windowing System: X11 I think

**Comment by droidmonkey** [comment]
This was fixed in this PR: https://github.com/keepassxreboot/keepassxc/pull/6606

Will be out with 2.7.0
