### ISSUE TITLE
Invalidate shared passwords (via keyshare)

### ISSUE THREAD

**Issue by xstable** [keepassxreboot/keepassxc#7280]
## Summary
If 2 Databases are connected this way:
- 1st DB = only export
- 2nd DB = only import
It would be awesome, if it would be possible to in-validate shared collections by the master (1st db). 
So if user in db1 change PW, 2nd db should notice this, and should be fully erased.

The Idea behind that is if you have an Agency and work with many freelancers, you could create sharings for a group of (or each single ) freelancer. If he left the Projekt, you invalidate his Password-Access and even the passwords saved at his side shouldn't be shown anymore.

If I understand in right way, currently you can save the password, but even if the 2nd DB didn't get all new changes, the old passwords still available there, right?!

What you you think about this feature?

**Comment by droidmonkey** [comment]
This is not possible in an offline password manager. By definition, everyone has a copy of the database, and can thus do whatever they want with it, provided they have access credentials. If you share credentials with anyone, you must revoke/reset those credentials. Merely cutting them off from the shared database is meaningless.
