### ISSUE TITLE
Ability to change/disable keyboard shortcuts / hotkeys / accelerators

### ISSUE THREAD

**Issue by Pysis868** [keepassxreboot/keepassxc#7283]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
In title.

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )
New options entry displaying a table/list grid view, similar to what is found on https://keepassxc.org/docs/KeePassXC_GettingStarted.html#_keyboard_shortcuts, with input boxes to set new keys, and X buttons to disable.

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
Tired of closing a database when wanting to edit an entry..

**Comment by droidmonkey** [comment]
This is a duplicate request. To edit an entry you can also just press enter.

**Comment by Pysis868** [comment]
Where is the original issue?
Also, there are incorrect behaviors depending on which part of the entry line is focused when you press that key, such as copying information instead.

**Comment by droidmonkey** [comment]
#2689

Use github search feature in the future please https://github.com/keepassxreboot/keepassxc/issues?q=is%3Aissue+is%3Aopen+change+keyboard+shortcuts

**Comment by Pysis868** [comment]
Did, just way too many log history posts.

**Comment by Pysis868** [comment]
Seems "shortcuts" or "hotkeys" needed more terms then.
