### ISSUE TITLE
backup and *restore* to paper (binary)

### ISSUE THREAD

**Issue by 3dGrabber** [keepassxreboot/keepassxc#7286]
## Summary
- Ability to print a .kdbx to paper as one big matrix barcode
- Ability to restore a .kbdx from paper using a scanner or photograph (the latter must be high-res)

## Examples
I already do this using an aptly named program called [Paperback](https://ollydbg.de/Paperbak/).
It would be nice to have this functionality integrated into keepassxc.
Paperback is open-source and has a compatible license (GPL).

![IMG_0555](https://user-images.githubusercontent.com/3806963/149343079-d5ed191e-5c18-4285-9b9a-2d402aca2c25.jpg)

## Context
I am aware that keepassxc already has a feature to print the .kbdx to paper as plain text.
The feature has its merits, and I am not arguing to replace it 
("You might die, your spouse might need your data").
The proposed feature would add the possibility to create a physical backup of the .kdbx.
The print-out can be kept around without worries of unwanted access.
It is just a physical incarnation of the .kdbx file which is encrypted and as such not usable without the master key.

**Comment by droidmonkey** [comment]
This is silly, sorry. We have export to html and csv. You can export the xml using cli. You can write down your credentials for your spouse. Dealing with scanning a huge qr code is not useful. We won't be implementing this.
