### ISSUE TITLE
Improve user feedback when adding duplicate additional URL

### ISSUE THREAD

**Issue by fwdekker** [keepassxreboot/keepassxc#7287]
## Overview
I have an entry that has more than a dozen additional URLs. Today, I tried adding a new URL to that entry but it didn't work. It took me two minutes to realise that KPXC wasn't bugging out, but that the URL was already in there. I think KPXC should communicate what happened to the user in a different way.

## Steps to Reproduce
1. Create an entry.
2. Go to the "Browser Integration" tab.
3. Under "Additional URLs", add a URL, say "https://keepassxc.org/".
4. Under "Additional URLs", add the exact same URL again.

## Actual Behavior
The second URL that is added is immediately replaced by "&lt;empty URL>". (KPXC does not tell the user why. The user is now probably confused.)

## Expected Behavior
KPXC informs the user that the new entry is a duplicate and will not be stored. (Personally, I think a balloon tooltip would suffice, or maybe replacing the URL not by "&lt;empty URL>" but by "&lt;duplicate URL>"? If that doesn't work, maybe a modal dialog?)

## Context
I'll admit that maybe I don't really need the entry to have a dozen additional URLs, since they're all subdomains of the same domain, so I could just use a single entry. But I'm sure there's other users out there with better reasons for having so many additional URLs.

KeePassXC - Version 2.6.6
Revision: 9c108b9

Operating System: Linux, Debian bookworm (testing)
Desktop Env: KDE
Windowing System: X11

**Comment by varjolintu** [comment]
Good idea!
