### ISSUE TITLE
Auto-Type caps-key filtering

### ISSUE THREAD

**Issue by JLT032** [keepassxreboot/keepassxc#7288]
## Summary
Using auto-type with some terminal emulators shows something awkward at hand. While the keyboards are both set to the same keyboard lay-out the auto-type text appears to be in a different keyboard layout.

It is unclear what is the root cause but it seems the password auto-type is doing something special with cApS which causes quite a bit of annoyance to get right and breaks after without a definable cause.

## Examples
auto-typing a password containing numbers has them print as the key above the number, so for a belgian or french keyboard the 9 becomes a ç the 2 becomes a é and so on.

## Context
I'm tri-lingual and use even more keyboard lay-outs

**Comment by droidmonkey** [comment]
This is fixed in the develop branch. Please try a snapshot build https://snapshot.keepassxc.org

**Comment by JLT032** [comment]
Thanks for the update, i don't use Snap at all and have no intention to use it.When will this be available as a release ?

**Comment by droidmonkey** [comment]
We are working on finalizing it right now. You can also use the appimage.

**Comment by JLT032** [comment]
Thanks again. I've compiled release/2.7.0, now auto-type doesn't work anymore.

**Comment by droidmonkey** [comment]
Why not use an appimage snapshot?

**Comment by JLT032** [comment]
I don't endorse the formats as i consider them bad practice.

Somehow after a restart the auto-type now works. I compiled keepassxc from source.
