### ISSUE TITLE
issue with "load previously open databases on startup" on Windows platform

### ISSUE THREAD

**Issue by tr1234g** [keepassxreboot/keepassxc#7289]
I'm using latest KeepassXC 2.6.6 (64-bit) for Windows platform, downloaded from https://keepassxc.org/download/

I have only 1 database and have set the following options in `%APPDATA%\KeepassXC\keepassxc.ini` `[General] `section:
```
OpenPreviousDatabasesOnStartup=true
RememberLastDatabases=true
RememberLastKeyFiles=true
```

The problem is that every once in a while KeepassXC seems to "forget" the last selected database and then I've first to manually select the last and only one database before I can enter my database password.

When this issue happens, I've recognized that the variables in `%LOCALAPPDATA%\KeepassXC\keepassxc.ini`
have changed from formerly:
```
[General]
LastDatabases=C:\\Users\\username\\Documents\\pwd\\mydb.kdbx
LastKeyFiles=@Variant(\0\0\0\x1c\0\0\0\0)
LastChallengeResponse=@Variant(\0\0\0\x1c\0\0\0\0)
LastOpenedDatabases=C:\\Users\\username\\Documents\\pwd\\mydb.kdbx
LastActiveDatabase=C:\\Users\\username\\Documents\\pwd\\mydb.kdbx
```

to:
```
[General]
LastDatabases=C:\\Users\\username\\Documents\\pwd\\mydb.kdbx
LastKeyFiles=@Variant(\0\0\0\x1c\0\0\0\0)
LastChallengeResponse=@Variant(\0\0\0\x1c\0\0\0\0)
LastOpenedDatabases=@Invalid()
```

I've no clue when this exactly happens, but it might be related to rebooting Windows.
Nevertheless, I've discovered a scenario how to reproduce this issue in a different way:
When you're prompted for the database password, simply press the `<Esc>` key and close KeepassXC. This leads to the above mentioned changes in `%LOCALAPPDATA%\KeepassXC\keepassxc.ini` and when starting KeepassXC next time it has forgotten the active database.
I'd like to suggest to change that behaviour, because when only 1 recent database is listed, why not safely considering that a user normally prefers this one to automatically be opened next time, when the variable `OpenPreviousDatabasesOnStartup` ist set to `true`.

**Comment by droidmonkey** [comment]
This is by design. When you press esc or ctrl+w you CLOSE the database. If you exit keepassxc with the welcome screen showing you will start keepassxc with the welcome screen showing.

**Comment by tr1234g** [comment]
Sorry, but it seems that you've misunderstood my problem description.
I do NEVER press `<Esc>` or `<CTRL>+<w>` !
This was only an example how I could trigger the same behaviour.
I always leave the database open, but nevertheless the problem occurs every once in a while and I do not know the root cause yet. The only thing I can tell you so far is that it might be related to rebooting Windows.
Please advise how to troubleshoot further.
Thanks.

**Comment by droidmonkey** [comment]
You must be closing the database before exiting keepassxc. I leave one database open in my keepassxc on windows and it has never forgotten. Going on 5 years now.
