### ISSUE TITLE
Support OpenYOLO

### ISSUE THREAD

**Issue by nolaviz** [keepassxreboot/keepassxc#729]
## Expected Behavior

KeePassXC should integrate with arbitrary Android apps using the OpenYOLO protocol.

## Current Behavior

KeePassXC needs to use plug-ins (or the insecure KeePassHTTP) to integrate with browsers, and cannot be used at all to secure sign-in for third-party apps.

## Possible Solution

Integrate the [OpenYOLO reference implementation](https://github.com/openid/OpenYOLO-Android).

**Comment by droidmonkey** [comment]
Im not sure how openyolo applies to us, we are not an Android app. Furthermore they state that their api is not stable yet.
