### ISSUE TITLE
[SOLVED] Diacritic mark (compound char) inside password doesn't work without display password

### ISSUE THREAD

**Issue by CoinK0in** [keepassxreboot/keepassxc#7291]
Hey,

## Overview
I have a problem with the decryption password of an archive, which is composed of 'Diacritic' marks. 
For example, a password containing an `ï` character, who is composed with an `¨` char + `i` char. _(Latin9 azerty, FR keyboard)_
When enter my password with this character the archive is not opened cause the password is invalid.

If I display the password while I enter it, the char `ï` composed of the keyboard keys `((Maj+^)+i)`, I get an `ï` _(Latin9 azerty, FR keyboard)_.
When I do the same thing to open my KeepassXC archive, **WITHOUT** displaying the password, then the `ï` become an classic `i`.
It seems that all the "diacritic mark" are not supported by the password field, when this one is not displayed. 

## Steps to Reproduce
Set master password of an archive as `abcï123`.
Open the archive and try to type de password, result as an invalid password.
If you just enter a password and display it before send, you should show `abci123`.
If you set display password, type the password, the result must be `abcï123` and your password work as expected.

## Expected Behavior
I would like to be able to use "compound" UTF-8 characters in my passwords. (Diacritic marks)
And that when I enter it's (Diacritic char) without toggle "display my password", it works. 

## Actual Behavior
Using a compound character (diacritic marks) in a password (like `ï`) does not decrypt the archive.
If you doesn't display the password, when you enter it to decrypt the archive. Cause `ï` become `i`.
If you copy/paste the diacritic char `ï` without display the password, it work as expected.

## Context
Diacritic mark -> https://en.wikipedia.org/wiki/Diacritic
If you display it before you enter de password, when you enter the first char `¨` (Maj + ^) you can see the prompt display the `¨` char with an underscore under him. And when you press the `i` char, the prompt immediately display the final char `ï`.

KeePassXC version 2.6.6 Revision 9c108b9, but i also have the same problem with previous versions.
Operating System: Ubuntu 20.04.3 LTS (Focal)
Desktop Env: Gnome version 3.36.8, but is also have the same problem with Gnome 3+ versions.
Local env keyboard and setup : 
```bash
$ localectl
   System Locale: LANG=fr_FR.UTF-8
       VC Keymap: n/a
      X11 Layout: fr
       X11 Model: pc105
     X11 Variant: azerty
$ setxkbmap -query
rules:      evdev
model:      pc105
layout:     fr,fr
variant:    azerty,oss
$ cat /etc/default/keyboard
# KEYBOARD CONFIGURATION FILE
# Consult the keyboard(5) manual page.
XKBMODEL="pc105"
XKBLAYOUT="fr"
XKBVARIANT="azerty"
XKBOPTIONS=""
BACKSPACE="guess"
```
Fell free to ask me any others informations that's needed or helpful for fix this.
If you have any suggestions / modification of my configuration for bypass this "problem" I also take it too.
Thank's you :)

**Comment by droidmonkey** [comment]
Qt bug, reported to them

**Comment by CoinK0in** [comment]
Found a work around to my problem by running  `QT_IM_MODULE=xim keepassxc` to start KeePassXC.
Diacritic mark are now supported and work as expected.
