### ISSUE TITLE
Tray icon on inactive (secondary) monitor on macOS is halved

### ISSUE THREAD

**Issue by woj-tek** [keepassxreboot/keepassxc#7294]
## Overview
On MBP with macOS Monterey with external monitor, KPXC icon on secondary, currently not-focused monitor, the icon is squashed / compressed / halved:

Focused display:
![Captura de pantalla 2022-01-17 a las 11 40 11](https://user-images.githubusercontent.com/724413/149754678-ee93b3b8-a80d-47f1-8830-c41cb8456d24.png)

Unfocused display:
![Captura de pantalla 2022-01-17 a las 11 41 02](https://user-images.githubusercontent.com/724413/149754811-614091cf-9ed7-40e7-a22b-928caef8528d.png)

## Steps to Reproduce
1. Just start the application and make sure that tray icon option is enabled

## Expected Behavior
Both icons should be displayed in the same size

## Actual Behavior
Unfocused display icon is not correct.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.6
Revision: 386b79a

Qt 5.15.2
Debugging mode is disabled.

Operating system: macOS 12.1
CPU architecture: arm64
Kernel: darwin 21.2.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (only unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
- libgcrypt 1.9.3

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS Monterey
Desktop Env: n/a
Windowing System: n/a

**Comment by droidmonkey** [comment]
This is a Qt bug and #6074

**Comment by woj-tek** [comment]
My bad. I searched and saw that issue but didn't know it's Qt issue.

**Comment by droidmonkey** [comment]
I'm not sure why it is closed though, it still affects 5.15.2 but it appears they fixed it in 6.1.0. https://bugreports.qt.io/browse/QTBUG-88600
