### ISSUE TITLE
Unlocking should force focus and forcibly put window to foreground (and stay there)

### ISSUE THREAD

**Issue by branleb** [keepassxreboot/keepassxc#7295]
## Overview
When the unlocking is active (and especially if the password input field has focus), the window should stay forcibly in foreground with input focus forced.
Unfortunately, that is not the case. Other Applications can steal the windows Input Focus (at least on Linux with KDE).
This can lead to information security breaches because parts of a password currently beeing typed in can be spilled to another application which gets pushed to the foreground. Especially during startup/after login if autorun is active this a common scenario, even more so if keepassxc is the active freedesktop secret service.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Start KeepassXC
2. Start typing in the password for a database
3. have some other application open an input focused window 

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Focus stays on password input 

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Other Application steals input focus

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.6.6
Revision: ?

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: KDE
Windowing System: X11

**Comment by droidmonkey** [comment]
That is the responsibility of the desktop environment. Individual applications _cannot prevent_ focus stealing. You can enable Always On Top from the view menu, but that will NOT prevent focus stealing. What you want is to set your KDE window control feature:

![image](https://user-images.githubusercontent.com/2809491/149794262-deb33f9e-20d8-4b7b-a5af-a430218401c7.png)

**Comment by branleb** [comment]
> That is the responsibility of the desktop environment. Individual applications _cannot prevent_ focus stealing. 

Aside from the DE specific behaviour setting you mentioned: 
Other Password Managers like e.g. gnome keyring manager manage to this, so they apparently setup their window properties in a way that requests exactly this behaviour from the OS. Which can and should be expected from software handling sensitive authentication data input.

So this is still a unwanted and unexpected behaviour from a users perspective and therefore a bug from my point of view.
