### ISSUE TITLE
when creating pw a lower case l appears as a 1

### ISSUE THREAD

**Issue by estespark40** [keepassxreboot/keepassxc#7298]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. type lower case l in password area when creating a new entry
2. it appears as 1 (number 1) not l
3. when cut and pasted to site pw box it is seen correctly as l and opens site
4. cut and paste pw to note area of the new entry and it appears as l as intended
5. upper case L works as expected
6. typing lower case l in name box or note area appears as it should

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )lower case l should be l  not 1

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
lower case l typed in password box is seen as a 1

## Context
[NOTE]: # ( Give us any additional information you may have. )
going back over years of pass words shows that this has always happened
have used keepassxc for years with Win 7   Win 8  and  Win 10

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION  2.6.6
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows/Linux/macOS     Win 7    Win 8   Win 10
Desktop Env: Gnome/KDE/XFCE/Mate/Cinnamon
Windowing System: X11/Wayland

**Comment by droidmonkey** [comment]
Ummm it's an l, monospace font. A 1 has a bottom line.

**Comment by estespark40** [comment]
mmmmmm  it does have a line on the bottom in the
app.

01/17/22 22:45:30, Jonathan White ***@***.***>:

Ummm it's an l, monospace font. A 1 has a bottom line.
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
