### ISSUE TITLE
Generate CLI does not exclude " even when this char is excluded

### ISSUE THREAD

**Issue by gkvdvaart** [keepassxreboot/keepassxc#7299]
## Overview
Generating passwords via the CLI generate command and excluding some chars does not exclude all the excluded chars

## Steps to Reproduce
1.  keepassxc-cli generate -L 27 -l -U -n -s --exclude `,',",;,:,$,@

## Expected Behavior
Passwords without the excluded chars

## Actual Behavior
Passwords do contain "
ie b8g#{Y4LRYtAE&{{o~B"I!-qLg)

# ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.4
Revision: 34a78f0

# ( Pick choices based on your environment )
Operating System: Windows 10

**Comment by droidmonkey** [comment]
You need to escape the quote character on the cli. `^"` on Windows or wrap in single quotes on Linux `'"'`
