### ISSUE TITLE
Plans for mobile App?

### ISSUE THREAD

**Issue by matthiasballreich** [keepassxreboot/keepassxc#7301]
Are the plans for providing a mobile app of KeePassXC for primary iOS (and maybe Android)?
There are some apps on the market, but the most apps of these did not provide the functionalities KeePassXC provides, so just the question if there are any plans in this way?

**Comment by droidmonkey** [comment]
No we have no plans, there are excellent mobile apps already made that are fully compatible with kdbx format and keepassxc. We have an FAQ on our website that addresses this. https://keepassxc.org/docs/#faq-platform-mobile
