### ISSUE TITLE
Server seems to lock the database file and prevents any changes

### ISSUE THREAD

**Issue by johnvirg** [keepassxreboot/keepassxc#7302]
## Overview
After some time of sharing a .kdbx file on a Windows network share with a few people keeping the database open at the same time throughout the day, we start getting "Writing the database failed: Destination file exists" errors.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Put the .kdbx file on a Windows server network share
2. Share out the file in a folder with modify permissions
3. Connect to the share and open the .kdbx file
4. Use the .kdbx this way, concurrently, amongst a handful of people
5. Make modifications to the database over time
6. Eventually, someone gets the "Writing the database failed: Destination file exists" error comes up
7. No one can edit the .kdbx anymore
8. On the server, if we try to rename or delete the file, the operating system says "The action can't be completed because the file is open in System" - The System process is Kernel-level. No file handles show up for the .kdbx file on the server.
9. Reboot the server
10. Problem resolved temporarily, but comes back

## Expected Behavior
When sharing a file with multiple users that there will be no issues sharing the file and syncing if everyone is using KeepassXC.

## Actual Behavior
See steps to reproduce above.

## Context
Client O/S: Windows 10 and Windows 11; Wired and wifi access to server

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.6
Revision: 9c108b9

Qt 5.15.2
Debugging mode is disabled.

Operating system: Windows 10 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.22000

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
- libgcrypt 1.9.2-unknown

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows
Desktop Env: 
Windowing System:

**Comment by droidmonkey** [comment]
Most likely a virus scanning software locking up the file. We don't hold a handle to the file unless actively reading the file and for a brief moment (atomic op) when writing the file.

Try exempting the specific kdbx file or all kdbx files from real-time scanning.

**Comment by johnvirg** [comment]
We will try that and see how it goes. Thank you.
