### ISSUE TITLE
Import CSV File dialog tab order

### ISSUE THREAD

**Issue by ogmios-voice** [keepassxreboot/keepassxc#7304]
## Overview
Import CSV fields dialog: the tab order of the fields in the Column Association and Encoding sections are messed up.

## Steps to Reproduce
1. Menu: Database > Import > CSV FIle...
2. follow steps till Import CSV fields dialog appears
3. start pressing Tab to navigate through the fields + observe focus change

## Expected Behavior
Focus should cycle through the fields according to their perceptible order

## Actual Behavior
Focus jumps:
1. from Password to Codec
2. from "Consider '\' an escape Character" to URL
3. from TOTP to Created
4. from Created to Last Modified
5. from Last Modified to Icon
6. from Icon to OK (button)

## Context
KeePassXC - Version 2.6.6
Revision: 9c108b9
Qt 5.15.2
Operating system: Windows 10 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.19043

**Comment by droidmonkey** [comment]
Good catch, it sure is messed up
![image](https://user-images.githubusercontent.com/2809491/150055873-7c431972-e4ca-420e-b495-93be5d8788db.png)
