### ISSUE TITLE
Focus jumps when switching between multiple databases (tabs)

### ISSUE THREAD

**Issue by ogmios-voice** [keepassxreboot/keepassxc#7305]
## Overview
When switching between multiple databases (tabs), focus will jump both from the Groups tree and then the Entries list.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Open 2 databases
2. Select tab 1: select a group w/ at least one entry
3. Select tab 2: select a group w/ at least one entry
4. Select tab 1 again (either w/ mouse or by shortcut Ctrl+Tab): focus has jumped to the Entries list
5. Select tab 2: same as 4.
6. Select tab 1 yet again: focus has jumped to the General tab title in the Preview Panel.
7. Select tab 2: same as 6.

## Expected Behavior
Focus should stay on the selected component.

## Actual Behavior
See Steps to Reproduce

## Context
KeePassXC - Version 2.6.6
Revision: 9c108b9
Qt 5.15.2
Operating system: Windows 10 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.19043

**Comment by droidmonkey** [comment]
This is fixed by #8435
