### ISSUE TITLE
Keepassxc takes 30 seconds to load in brand new Linux Mint 20.3 install

### ISSUE THREAD

**Issue by tcsmedes-CE** [keepassxreboot/keepassxc#7308]
When I open Keepassxc either by clicking the icon or from the CLI it takes 30 to 45 seconds before the window appears.

Brand new install of Linux Mint 20.3 Cinnamon on Gen 7 i7 with 16gb RAM tried with both the stock 5.4 kernel and 5.13 kernel
Tried the Keepassxc install from base Mint repository and from PPA

user@workstation:~$ keepassxc
qt5ct: using qt5ct plugin
qt5ct: D-Bus global menu: no
qt5ct: palette support is disabled
qt5ct: custom style sheet is disabled

KeePassXC - Version 2.6.6
Revision: 9c108b9

Qt 5.12.8
Debugging mode is disabled.

Operating system: Linux Mint 20.3
CPU architecture: x86_64
Kernel: linux 5.13.0-27-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- libgcrypt 1.8.5

**Comment by droidmonkey** [comment]
Not sure what to tell you but this isn't the case anywhere I have tested the program. Snap installs tend to take a while on first start due to the way they unpack and load the filesystem.

**Comment by droidmonkey** [comment]
Recommend running an strace when launching KeePassXC to see which resource is holding up the loading.

**Comment by liar666** [comment]
Same issue here
HINT:  
```
$keepassxc
qt5ct: using qt5ct plugin
```
SOLUTION:
 ```
# apt purge qt5ct
```
https://forums.linuxmint.com/viewtopic.php?f=47&p=2131317
