### ISSUE TITLE
No Minimize on Password Copy

### ISSUE THREAD

**Issue by KitchM** [keepassxreboot/keepassxc#7309]
## Overview
Prior to my upgrade to Debian 11 and Xfce 4.16, KeePassXC would always minimize when copying a password so as to get out of the way for pasting into the browser.  It no longer does that.

## Steps to Reproduce
1 Click on the system tray icon and it opens up. 
2. Find password entry and right-click to copy.
3. Application does not minimize again.  Must manually force it.

## Expected Behavior
Should minimize on password copy.

## Actual Behavior
Does not minimize.

## Context
[NOTE]: # ( Give us any additional information you may have. )

KeePassXC - Version 2.6.2
Revision: e9b9582

Qt 5.15.2
Debugging mode is disabled.

Operating system: Debian GNU/Linux 11 (bullseye)
CPU architecture: x86_64
Kernel: linux 5.10.0-10-amd64

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (only unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.8

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: XFCE
Windowing System: X11

**Comment by droidmonkey** [comment]
Go to the application settings and enable minize on copy to clipboard.

**Comment by KitchM** [comment]
I was looking all over for what you wrote, and it was exactly what I had searched for before.

What I found after another detailed search was:
"Hide window when copying to clipboard"
Select "Minimize"

Thanks for prompting me to go over it again.  Non-intuitive language always catches us.
