### ISSUE TITLE
Decentr browser integration

### ISSUE THREAD

**Issue by Terramoto** [keepassxreboot/keepassxc#7316]
## Summary
Decentr is another chromium based browser, unfortunately upon install the keepassxc-browser extension i've notice it wasn't able to connect to the application.

**Comment by droidmonkey** [comment]
You'll need to setup a custom browser in the advanced browser settings. Look at the decentr documentation on where to place the native messaging file. We will not provide support for this browser.

**Comment by Terramoto** [comment]
> You'll need to setup a custom browser in the advanced browser settings. Look at the decentr documentation on where to place the native messaging file. We will not provide support for this browser.

Where are these settings located? Under 'Settings'  > 'Browser Integration' i can't find anywhere to setup a custom browser, same for 'database settings' > 'Browser Integration'

**Comment by droidmonkey** [comment]
Under the advanced tab for the browser integration settings of the application. You need keepassxc 2.6.0 or higher.

**Comment by Terramoto** [comment]
Hello,

Sorry, but i'm really struggling to find these:
![image](https://user-images.githubusercontent.com/5443354/150382827-e083f1a3-73f6-49e6-b687-6bdeea221f27.png)

Are you referring to "Use a custom proxy location:" option?

I've watched a vide on keepass and on other clients it looks like there's some added fields into the "Advanced" tab  but i don't seem to have those.

**Comment by droidmonkey** [comment]
The custom browser option is only available on mac and Linux. On windows you need to edit the registry for decentr to point to the Chrome native messaging file.

**Comment by envido32** [comment]
It took me a while to found the right key to edit on the registry for it to work on Windows 10 using Waterfox, you can use it as an example... I suppose for Decentr is very similar

```
Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\SOFTWARE\Waterfox\NativeMessagingHosts\org.keepassxc.keepassxc_browser]
@="%LOCALAPPDATA%\\KeePassXC\\org.keepassxc.keepassxc_browser_firefox.json"
```


This is what I suppose Decentr need but I have not test it, use at your own risk. 
On "Browser Integration" the "Chromium" option should be ON.

```
Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\SOFTWARE\Decentr\NativeMessagingHosts\org.keepassxc.keepassxc_browser]
@="%LOCALAPPDATA%\\KeePassXC\\org.keepassxc.keepassxc_browser_chromium.json"
```

If it still fails try changing 

%LocalAppData% = C:\\Users\\{YourUserName}\\AppData\\Local

**Comment by Terramoto** [comment]
Hello,

I believe i found the issue, Decentr looks into the chromium.json file for allowed extensions but instead of chrome-extension:// it uses decentr-extension:// and so it ends up failing with unsupported scheme message.

I also tried to modify the chromium.json file to include the lines to decentr-extension:// but whenever i re-open the app it overwrites it with the default values.

**Comment by droidmonkey** [comment]
Just unset the custom proxy setting and all the files and registry keys will remain in place

**Comment by droidmonkey** [comment]
You should file a bug with decentr because that is plain dumb.
