### ISSUE TITLE
Hardware key not detect issue on keepassxc in the firejail

### ISSUE THREAD

**Issue by miragy69** [keepassxreboot/keepassxc#7317]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
Keeppassxc can't detect any hardware key after get in the jail. Hardware serial number is detectable.
(Edited) Please reassign the label if needed.
## Temporary solution
The issue can be solved by commented out these applications under `/usr/lib/firejail/firecfg.config`. Then 
`# firecfg --clean && firecfg` for recreate links again 
![image](https://user-images.githubusercontent.com/75862210/150373591-e5763be4-eabd-4853-a8f7-68546ed9ff82.png)
for commenting out the keepassxc-proxy can solve the issue [#6230](https://github.com/keepassxreboot/keepassxc/issues/6230), i.e. you don't have to manually click reload on browser plugin for password autoloading.

## Looking for future support on firejail
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
It will make safer for running keepassxc in the firejail, if the above issue can be solved. Many thanks.

**Comment by droidmonkey** [comment]
We don't deploy a firejail profile. You'll have to discuss this with the team who built that profile.
