### ISSUE TITLE
Version Check Mismatch with Browser Extension

### ISSUE THREAD

**Issue by KitchM** [keepassxreboot/keepassxc#7318]
## Overview
The browser extension states that the version of KeePassXC is old.  One of the options for Debian is to use
`sudo apt-get install keepassxc`
But when using that, the latest is already installed.

## Steps to Reproduce
1. In browser select the KeePassXC icon
2. Read notice
3. 

## Expected Behavior
Browser should connect with database automatically.

## Actual Behavior
Does not connect

## Context
[NOTE]: # ( Give us any additional information you may have. )
KeePassXC - Version 2.6.2
Revision: e9b9582

Qt 5.15.2
Debugging mode is disabled.

Operating system: Debian GNU/Linux 11 (bullseye)
CPU architecture: x86_64
Kernel: linux 5.10.0-10-amd64

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (only unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.8

Operating System: Linux
Desktop Env: XFCE
Windowing System: X11

**Comment by droidmonkey** [comment]
Use the appimage, ppa, or snap package. If you don't want to do that then disable version checking in the browser extension settings.

**Comment by KitchM** [comment]
Thank you very much.  However, I could not find that option in the extension settings.
