### ISSUE TITLE
Auto-type window title unicode display issue

### ISSUE THREAD

**Issue by quinncomendant** [keepassxreboot/keepassxc#732]
I'm creating an auto-type window association for a website with the following title:

    <title>SC Admin ⧸ Login</title>

That `⧸` is not a normal forward slash, it is actually [U+29F8 (big solidus)](https://codepoints.net/U+29F8?lang=en). The website output is sent in UTF-8.

When I use KeePassXC 2.2.0 to create a new window association, in the *Window title* select menu, this appears (screenshot):

![screen shot 2017-07-02 at 13 17 26](https://user-images.githubusercontent.com/6884276/27767025-cac9a82e-5f29-11e7-8681-9aedc54929a3.png)

As you can see, the `⧸` character does not display correctly. Even so, the window does match correctly when executing the auto-type (but just to be sure, however, I'm using the regex `//SC Admin.*Login//`).

## Expected Behavior
Unicode characters should display correctly. 

## Current Behavior
The `⧸` unicode character looks messed up.

## Possible Solution
    ¯\_(ツ)_/¯

## Context
Because unicode support is complicated, this issue can be either a) a very minor bug with little consequence, or b) a flaw in the way KeePassXC handles multi-byte characters that may have deeper negative consequences. If the former, the bug should be easy to fix, otherwise, finding what is wrong here might expose more serious issues that would have a higher priority fixing.

## Debug Info

KeePassXC - Version 2.2.0
Revision: caa49a8ef3ee28ed478192389b21d61107b3b8e0

Libraries:
- Qt 5.9.0
- libgcrypt 1.7.7

Operating system: macOS Sierra (10.12)
CPU architecture: x86_64
Kernel: darwin 16.6.0

Enabled extensions:
- KeePassHTTP
- Auto-Type
- YubiKey

**Comment by weslly** [comment]
Seems to be a bug with Qt rendering instead:

![image](https://user-images.githubusercontent.com/107672/27767513-51d15eac-5ed0-11e7-8e46-3411e118e3c7.png)

I'm not sure if there's a way to fix it without actually patching Qt

**Comment by phoerious** [comment]
I suppose it's just a display issue. Maybe the font that Qt uses just doesn't support the character. When I view your bug report on Android, I also only see an empty box, even though the Noto font is usually pretty amazing with weird Unicode characters. So probably not a KeePassXC bug.

**Comment by weslly** [comment]
I tried showing this character in other Qt apps and it didn't work either

![image](https://user-images.githubusercontent.com/107672/27769116-443a3420-5ef9-11e7-9657-1b8a510e0232.png)

I'm closing this since it's a bug with Qt
