### ISSUE TITLE
Default preselected entry icon is folder instead of key

### ISSUE THREAD

**Issue by giwrgosmant** [keepassxreboot/keepassxc#7321]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
Default preselected entry icon is folder instead of key in my database.
## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Add new entry.
2. Go to settings of the entry in icon section.
3. Default icon is preselected folder.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
The default preselected icon of a new entry should be a key instead of folder.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
When I create a new entry in my database, the default icon is folder instead of key. The database created long ago with KeePass and I have this minor issue from the time I moved to KeePassXC.
I tested with new database created by KeePassXC and the default entry icon there is key, as it's should.

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.6
Revision: 9c108b9

Qt 5.15.2
Debugging mode is disabled.

Operating system: Windows 10 Version 2009 --------------------------------> **I have Windows 11 btw, I don't know why it's show Windows 10 in Debug Info**

CPU architecture: x86_64
Kernel: winnt 10.0.22000

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
- libgcrypt 1.9.2-unknown

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 11

**Comment by droidmonkey** [comment]
You have this setting enabled (it is by default):
![image](https://user-images.githubusercontent.com/2809491/150650263-99ee3a8e-05cf-453b-b3de-f13500fda1dc.png)

And your group icon is not the default group icon. The default group icon is the closed folder:
![image](https://user-images.githubusercontent.com/2809491/150650271-55228ff3-ba43-491d-bcde-8bdb69cc823d.png)

Unfortunately, we did not choose this convention or the ordering of the icons... that is chosen by KeePass original.

**Comment by giwrgosmant** [comment]
@droidmonkey Thank you very much mate! 🙂 You really saved me from annoying headache every time I added new entry.
