### ISSUE TITLE
Bug? View/Sacaling is smaller in ubuntu version than in the flapak one

### ISSUE THREAD

**Issue by ghost** [keepassxreboot/keepassxc#7323]
## Overview
I have tried both flatpak version and ubuntu versions. Both of them are Version 2.6.6 but in flatpak it looks better because fonts are considerably bigger than the ubuntu installation.

## Expected Behavior
Display keepassXC ubuntu as bigger as in the flatpak version.

## Context
KeePassXC - 2.6.6
Revision: REVISION
Operating System: Linux
Desktop Env: Cinnamon
Windowing System: X11

**Comment by droidmonkey** [comment]
https://doc.qt.io/qt-5/highdpi.html#high-dpi-support-in-qt
