### ISSUE TITLE
Cannot add ed25519-sk ssh key

### ISSUE THREAD

**Issue by Abh15h3k** [keepassxreboot/keepassxc#7328]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
cannot add ed25519-sk ssh key. (Yubikey 5 nano c)

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
(Step 1 in terminal, rest in KeePassXC)
1. generate ssh key `ssh-keygen -t ed25519-sk` (password-less key used)
2. create new entry
3.  go to ssh agent
4. select "External File" under private key and attempt to add `~/.ssh/id_ed25519_sk` via browse button

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
private keyfile gets accepted and public key shows up in the "Public Key" text field

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
error popup "Unknown key type: sk-ssh-ed25519@openssh.com"
![image](https://user-images.githubusercontent.com/40197742/150697052-78338e79-b74a-40fd-a50d-bb941f9d9754.png)

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.6
Revision: 386b79a

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS (2020 M1 MacBook Pro)
Desktop Env: N/A
Windowing System: N/A

**Comment by hifi** [comment]
Security key backed keys are implemented for the next release, 2.7.0. You can try a snapshot release or wait for the final one.

**Comment by Abh15h3k** [comment]
Thanks for the quick response!
