### ISSUE TITLE
No browser connection when switching from Light/Dark theme to Classic

### ISSUE THREAD

**Issue by ogmios-voice** [keepassxreboot/keepassxc#7331]
## Overview
While the browser can connect perfectly to KeePassXC when it is using the Light/Dark theme, it will not be able to connect to KeePassXC when it is using the Classic theme.
(Note: was tested only w/ the Dark theme.)

## Steps to Reproduce
1. Start KeePassXC w/ Light/Dark theme
2. Create a new database (while using the Light/Dark theme) -- not user about this requirement
3. Connect browser to KeePassXC
4. Switch KeePassXC to Classic theme + restart KeePassXC
5. Browser will be unable to connect to KeePassXC -- note: restarting the browser was not tested
6. Switch KeePassXC back to Light/Dark theme + restart KeePassXC
7. Browser is able to connect again to KeePassXC

## Expected Behavior
Themes should have no effect on connection.

## Actual Behavior
See Steps to Reproduce.

## Context
KeePassXC - Version 2.6.6
Revision: 9c108b9
Qt 5.15.2
Operating system: Windows 10 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.19043

Firefox 96.0.2 x64
KeePassXC-Browser 1.7.11

**Comment by droidmonkey** [comment]
There is absolutely no connection between the app theme and the browser extension. You need to do more testing.

**Comment by varjolintu** [comment]
Restarting KeePassXC might rewrite the scripts meant for Native Messaging. If you have done some manual tweaking, your files could've been overwritten.

**Comment by ogmios-voice** [comment]
All I did was to turn up the decryption time of the database. So I guess nothing relevant.
I've tried to reproduce the issue in more isolated circumstances, but I was unable to do so: it's working fine now.
The browser (both Firefox and Chrome) disconnects from KeePassXC from time to time w/o any reasonable explanation (the computer was on all the time, so no sleep, hibernate etc. in between), but for now I can reconnect to it at the very first request regardless of the active theme.

**Comment by varjolintu** [comment]
@ogmios-voice When the disconnect happens next time check if `keepassxc-proxy.exe` process is still running. There should be one process per browser. Some anti-virus or anti-malware software can sometimes shut it down or prevent it from launching.
