### ISSUE TITLE
Secret service integration failure

### ISSUE THREAD

**Issue by samueltardieu** [keepassxreboot/keepassxc#7332]
## Overview

Launching keepassxc configured with secret service integration gives: QDBusConnection: Could not emit signal org.freedesktop.Secret.Service.CollectionCreated: Marshalling failed: Invalid object path passed in arguments

## Steps to Reproduce

1. Configure Secret Service integration with a "SecretService" group 
2. Launch keepassxc from the console
3. Receive message `QDBusConnection: Could not emit signal org.freedesktop.Secret.Service.CollectionCreated: Marshalling failed: Invalid object path passed in arguments` even before the database password has been requested

## Expected Behavior

Secret service integration should work.

## Actual Behavior

Secret service integration does not work

## Context

KeePassXC - Version 2.6.6
Revision: 9c108b9

Qt 5.15.2
Debugging mode is disabled.

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 5.16.2-arch1-1

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- libgcrypt 1.9.4-unknown

**Comment by Aetf** [comment]
Hmm, looks like we somehow generated an invalid collection Dbus path.

What's your database file name? The initial collection Dbus path is derived from that.

Also, please share the log when running KeepassXC with `QDBUS_DEBUG=1` set in environment variable.

**Comment by samueltardieu** [comment]
The file name is `/home/sam/.secret-service.kdbx`. The log file is here: [log.txt](https://github.com/keepassxreboot/keepassxc/files/7937219/log.txt)

The initial dot in the file name seems to be the problem there.

**Comment by Aetf** [comment]
Ah yes. This has been fixed in #5660 (previous report https://github.com/keepassxreboot/keepassxc/issues/5279#issuecomment-720950420). But it's not released yet.

Closing this as duplicate. For now, renaming the file should work around the issue.
