### ISSUE TITLE
Add/Remove/Open/Save buttons for attachments squashed with small window size

### ISSUE THREAD

**Issue by flying-scottsman** [keepassxreboot/keepassxc#7333]
Using KeePassXC 2.6.6 on ArchLinux with Xfce desktop. **4K display resolution** (relevant?)

The _Add/Remove/Open/Save_ buttons for attachments on the _Advanced_ tab in the password edit dialogue are squashed vertically if the main KeePassXC window is too small. This results in unreadable button text.

As in other tabs, the dialogue is made scrollable if not enough space is available. Before scroll bars are offered, the part of the dialogue for _Attachments_ reduces its vertical size, along with the buttons. In contrast, the part for _Additional attributes_ in the same tab stays fixed in size if the window size is reduced.

Please see the attached two screenshots for illustration. The first one shows the squashed buttons with a small(er) window, the second screenshots shows a large(r) KeePassXC window with enough space to fit the entire dialogue.

By the way: **Thank you** for a very useful piece of software!

![Buttons "squashed"](https://user-images.githubusercontent.com/47442201/151021177-f6037f62-43f7-4128-9476-89e6e00b2f82.jpg)
![Buttons normal](https://user-images.githubusercontent.com/47442201/151021524-12a3db5f-46e2-4811-a00d-136c66f37b6e.jpg)

**Comment by droidmonkey** [comment]
This is fixed in develop
