### ISSUE TITLE
KeePassXC crashes when clicked "Reopen database" on KeePassXC-Browser (firefox) while attempting to open database.

### ISSUE THREAD

**Issue by Nielotz** [keepassxreboot/keepassxc#7334]
## Overview
KeePassXC with KeePassXC-Browser on firefox crashes when attempting to open database through addon while already opening database.

## Steps to Reproduce
1. Turn on KeePassXC.
2. Open any page in firefox.
3. Firefox - KeePassXC-Browser -> click "Reload" button.
4. Firefox - KeePassXC-Browser -> click "Reopen database" button.
5. Attempt to log in into database using any key.
6. While KeePassXC attempts to unlock - click again "Reopen database" button.

## Expected Behavior
Nothing?

## Actual Behavior
Window that asks for auth gets focus and already entered password disappears (input field is disabled). Few seconds later KeePassXC crashes.
![obraz](https://user-images.githubusercontent.com/22748793/151033238-0fc7adc5-dd83-4b81-b7bd-0d1526db449a.png)

## Context
[NOTE]: # ( Give us any additional information you may have. )

KeePassXC - Version 2.6.6
Revision: 9c108b9

Qt 5.15.2
Debugging mode is disabled.

Operating system: Windows 10 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.19044

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
- libgcrypt 1.9.2-unknown

KeePassXC-Browser - 1.7.11
Operating system: Win64
Browser: Mozilla Firefox 96.0

Operating System: Windows

**Comment by droidmonkey** [comment]
So the database is already in the unlocking process when you try to invoke another unlock?

**Comment by Nielotz** [comment]
Yes
edited: 
I don't know is it trying to unlock or just attempts to prompt for auth

**Comment by droidmonkey** [comment]
This is most likely the same bug as #7133

**Comment by varjolintu** [comment]
I have been unable to reproduce this.

**Comment by WofWca** [comment]
I can reproduce, with following steps:

1. Have only one DB (so, not the same steps as in #7133), make sure the DB is locked.
2. Open a website.
3. Click the KeepassXS icon near the login field. The prompt window will pop up.
4. Enter a password, press "Enter" to start unlocking.
5. Before the unlocking finishes, click the icon near the login field again.
6. 💥

**Comment by varjolintu** [comment]
@WofWca Created a database with 5 seconds decryption time and I got it reproduced. Not at the first time though. It needed a couple of tries.

**Comment by pci-auto** [comment]
I randomly have the same error message when I try to save an entry in the database.
I don't know if it can have an effect, but I usually have more than one database open at the same time.

**Comment by varjolintu** [comment]
> I randomly have the same error message when I try to save an entry in the database. I don't know if it can have an effect, but I usually have more than one database open at the same time.

Saving entry from KeePassXC directly or from the browser extension? This smells like a different bug.

**Comment by droidmonkey** [comment]
Same as #7660
