### ISSUE TITLE
Add way to not remember password generation settings

### ISSUE THREAD

**Issue by ygrange** [keepassxreboot/keepassxc#7336]
## Summary
I have my favourite standard for passwords (basically a long password with all character types). However many websites do not like this and I have to change my settings, making it shorter, changing character types. KeepassXC will then remember what I set up before. I can't really see what a good use case is for it to remember the settings and I'd rather have a way to configure what my default password policy is in stead of automatically applying the policy of a website with crappy security. 

## Examp
<img width="647" alt="Screenshot 2022-01-26 at 09 14 54" src="https://user-images.githubusercontent.com/6578686/151126818-9f2214a2-c173-41c2-8b26-255914a765e4.png">
les
﻿﻿Adding a simple check box with something like "remember settings" in the password generation screen would already be useful (sorry for the horrible mockup). 

## Context
I don't think my circumstance is particularly unique but it is quite hard to keep my passwords as safe as possible and whenever I encounter a website with very lax password policies (short, only letters and numbers), it can happen that the next few passwords I generate are following those same settings because I just quickly want to create one. I'd be surprised if that would be a problem uniquely to me :)

**Comment by droidmonkey** [comment]
This is very closely related to, and solved by, password profiles. I'm going to mark this as a duplicate request. #2628

**Comment by ygrange** [comment]
Thanks :). I wasn't really sure how to search for such a request in the issue tracker and was slightly worried this would be an obvious duplicate. I think this would certainle be solved by profiles, as long as there is also a 'default' one. I assume this one can be closed then?

**Comment by droidmonkey** [comment]
Yup, and I do plan to implement the profiles request, I would certainly use them and I share your frustrations!
