### ISSUE TITLE
Use monospaced font for passwords in entry view, if enabled

### ISSUE THREAD

**Issue by uiolee** [keepassxreboot/keepassxc#7337]
recommend monospaced font.

in list, some text look long and some text look short, but in fact they are the same length. 
I will recommend monospaced font in list view.

![list](https://github.com/keepassxreboot/keepassxc/assets/22849383/a28a8c2c-a99d-4ec4-9202-3b6a38727aae)

```
KeePassXC - Version 2.7.6
Revision: dd21def

Qt 5.15.10
Debugging mode is disabled.

Operating system: Windows 10 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.19044

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 2.19.3
```

**Comment by droidmonkey** [comment]
We already use a monospace font for passwords.

**Comment by uiolee** [comment]
> We already use a monospace font for passwords.

really, my ver is 2.6.6

![图片](https://user-images.githubusercontent.com/22849383/151285969-e5ffa34d-8cfd-4b90-8fe7-de8be9e0c100.png)

**Comment by cosmiczoo** [comment]
I too find the font reads ambiguously on Ubuntu Studio 21.10.  I have not changed the default theme. 
See attached picture.  The font appears to be monospaced but italic.

![image](https://user-images.githubusercontent.com/43783777/166145287-412fbcba-d401-4b4a-81c9-392b00eab379.png)

When I copy a password by hand say from the display on the PC screen to my mobile phone I prefer the most simple font, monospaced, not bolded, not italicised.  A font where similar looking characters are distinct:
1 l (lower case L), | (uppercase \) and | (altgr `) on UK keyboard
0 and O are clearly different
' (single quote) and ` (back-quote)

Some websites limit the number of tries.  With long passwords of random characters mistaking a character + finger-trouble can lock an account for a while.

**Comment by droidmonkey** [comment]
That means your system monospace font is selected to be an Italic variation. We don't do that, we just ask your system for the font to use.

**Comment by cosmiczoo** [comment]
You are correct.  It was a system setting in the default Global theme or something like that.
So glad the solution was trivial
My apologies for wasting your time.

**Comment by rextheleopard** [comment]
Windows x64 10.0.25169.1000 (clean profile)
Keepassxc 2.7.1-release (clean profile)

🆗Password field using monotype font.

Windows x64 10.0.25169.1000 (clean profile)
Keepassxc 2.7.1**-dev** (clean profile, from ci)

❌Password field using non-monotype system GUI font.

**Comment by rda0** [comment]
KeepassXC does not use a fixed width font on my system: Windows 10, v2.7.4 (MSI installer).
I am confused what the state is, as https://github.com/keepassxreboot/keepassxc/issues/2741#issuecomment-467232012 suggests `Consolas` is used on Windows.
Should passwords show in fixed width font?

**Comment by droidmonkey** [comment]
There was a bug when editing passwords that has been fixed for our next release

**Comment by tromlet** [comment]
I'm running v2.7.4 on Fedora 36, and do not have monospace fonts either when the passwords are revealed and when the passwords or concealed. I do not display the passwords in the columns.

**Comment by svkirillov** [comment]
I have the same issue on macOS.

**Comment by uiolee** [comment]
Still exists on v2.7.6

**Comment by phoerious** [comment]
You should not display passwords in the table view. We should, in fact, consider removing that column. You can view them in the preview panel, which uses monospace fonts.

**Comment by jmbreuer** [comment]
> You should not display passwords in the table view. We should, in fact, consider removing that column. You can view them in the preview panel, which uses monospace fonts.

Especially in open source software, I find it bad practice to want to presume how someone "should" or "should not" use it. They may be using it quite differently than you might imagine, and they're for sure much closer to their specific use case. Putting up a warning dialog (when unhiding the password column) saying that unconditionally displaying the password column in clear might not be such a great thing to do, that I'd be totally fine with.

Also, that column is providing **major** functionality now, even/especially when it is hidden: Double-clicking on the password of an entry line (whether the password is hidden with dots or not) puts it on the clipboard. Changing that would be **major** breakage IMO.
