### ISSUE TITLE
Auto-type auto enter

### ISSUE THREAD

**Issue by uiolee** [keepassxreboot/keepassxc#7338]
## Summary

auto-type will auto "enter", it's not useful.
many website will have captcha, auto "enter" will damage it.
in some website, "enter" maybe didn't link to login, but maybe link to regist or forget password. auto "enter" make us into wrong url.

suggest that a switch to choose auto "enter" or not.

**Comment by droidmonkey** [comment]
You can customize your Auto-Type patterns, please read the user guide.

**Comment by uiolee** [comment]
> You can customize your Auto-Type patterns, please read the user guide.

Thanks, i got it. i am sorry that i am focus on the menu - setting, haven't take a visit on the item and group's setting.
