### ISSUE TITLE
Cross-platform user loadable plugin support

### ISSUE THREAD

**Issue by hifi** [keepassxreboot/keepassxc#734]
User written plugins are a big part of the original KeePass and would mean a world to many users that would want to extend KeePassXC without knowing a complex native language like C++ (me included).

However, as far as I know, KeePass is exposing its internal C# API to plugins and that way plugin support is rather easy to achieve. Compiled C# code is platform and architecture agnostic so they have that going for them of out the box.

Second big issue is that where KeePass is a C# application using WinForms which is "just there" for plugins to use without exporting any additional API for that, Qt can't be "just used" from a scripting language as it would require some bindings the very least and sharing the runtime Qt library of KeePassXC might not be trivial.

One way to solve the GUI issue is to have a trivial API to add things like menu entries and simple dialogs but that might not be enough for many plugin developers.

## Expected Behavior
Loadable plugin interface in the GUI itself with full cross-platform support without recompiling plugins for each one. Ease of use and development.

## Current Behavior
Only compile time native extensions exist.

## Possible Solution
Use embedded scripting language to provide lightweight scripting interface into KeePassXC.

Lua is a popular language for adding scripting into a native application. It's very lightweight and is easy to pick up by anyone who's familiar with programming. If any scripting language would be embedded, Lua would be the ideal choice as it's a single library that can be statically linked if needed under the MIT license.

The C API to integrate Lua into an application is dead simple and I have done it in the past for multiple native applications.

With Lua or anything else, you would need to carefully craft an exposable API which requires a lot of boilerplate code to export complete classes and whatever is required for interoperability.

I would be more than happy to work towards embedded Lua with good game plan how to expose internal systems.

## Context
There is a high possibility of feature bloat creeping into KeePassXC and some of the solutions don't necessarily need to be in unsafe native code. It also helps prototyping new ideas that could be re-implemented as native C++ later (like keepassxc-browser).

**Comment by droidmonkey** [comment]
If anything i would use V8 since it integrates with a C++ interface. I've done extensive C++ integration using both LUA and Python... It is not fun at all.

**Comment by hifi** [comment]
The size is something to consider, though. V8 ain't light at around 15 MB give or take so it alone would be around twice the size of the complete KeePassXC package on Fedora where the shared Lua library is around 256k.

Otherwise JavaScript as a language wouldn't be bad at all. Everyone seems to know it these days.

**Comment by phoerious** [comment]
If (and that's a big if the moment) we implement some sort of plugin mechanism, it needs to be lightweight and not increase the overall size by some tens of megs. V8 is far too big.
I'd prefer either LUA or native Qt plugins.

**Comment by hifi** [comment]
The plugin system could be taken even further by having a signing system in place and a plugin portal to install such signed and verified plugins.

I'm probably going to try prototyping something with Lua if I have enough time and motivation with the assumption it will not be up to standards and never be merged in.

**Comment by louib** [comment]
I feel like we should seriously consider implementing this. A lot of the feature requests we get are features coming not from KeePass itself, but from some KeePass plugin, popular or not. I don't think we can afford implementing and maintaining all those features.

Investing time in a plugin architecture could allow us to offload a lot of the feature development while focusing on the maintenance of the core application.

That being said, I don't think anyone would be willing to step up and start working on this unless we're pretty fixed on what the plugin architecture should look like.

**Comment by hifi** [comment]
@louib I wrote something very crude for testing a bit after creating this issue: https://github.com/hifi/keepassxc/tree/lua-extension

**Comment by droidmonkey** [comment]
We discussed this in IRC a while back. Qt is really pushing their new javascript engine which is actually based off of v8 (they call it v4). It is very slick and directly integrated with Qt widgets.

**Comment by kvnxiao** [comment]
Is there any further discussion happening for this topic? Any chance of this happening? I'd love to be able to write a personalized "cloud storage" plugin that integrates with KeePassXC just so I don't have to deal with installing sync-ing clients on all my machines running different OS's.

**Comment by droidmonkey** [comment]
I would love to work on this but haven't had the time lately. I love script-based plugin interfaces.

**Comment by phoerious** [comment]
I would actually prefer exposing the KeePassXC-Browser API to external tools somehow.

**Comment by kvnxiao** [comment]
@phoerious I actually wonder about how smooth an integration would feel if utilizing the browser API for plugins / extensions.  How exactly would the interfacing work with the actual KeePassXC application?

What I originally imagined was something like a `Plugin` context drop down menu to control custom plugin options and settings. For example, a cloud storage plugin to directly sync and access a .pwd database.

**Comment by phoerious** [comment]
I was imagining extending the protocol so external programs can subscribe to be notified for certain things. It would not allow integration into the interface itself, but on the other hand, it provides a sane level of separation, so badly written or even malicious plugins cannot just do what they want without the user noticing.

**Comment by kvnxiao** [comment]
That doesn't sound pleasing to use if it were separated from the interface itself. Speaking from a user experience perspective, I wouldn't want to install a separate standalone application that acts as a plugin for the main application (if I interpreted your text correctly).

There is always a risk involved in encountering plugins made with malicious intent, regardless of how the architecture is set up in the back. It should be enough to have a clear statement that explains "third party plugin integrations can be dangerous, so be careful with what you choose."

**Comment by phoerious** [comment]
Plugins could still be installed via some one-click facility etc. They just can't directly integrate into the interface, making them more something like background services. I'd really like to have some strict separation of execution and memory space and that's easiest and most securely to achieve by running separate processes.

**Comment by madushan1000** [comment]
Hi, is there any progress on the plugin infrastructure? I would very much like to write something like keeanywhere so I can finally get rid of the google drive sync software.

**Comment by droidmonkey** [comment]
We are not going to support a plugin interface at this time or foreseeable future.

**Comment by hifi** [comment]
However, integrated cloud storage support would be an interesting PR for KeePassXC itself.

There are technical issues with that, though.

**Comment by madushan1000** [comment]
@hifi I just did some research on how to integrate google drive with keepassxc, It looks like keepassxc will have to maintain a google cloud project and google drive application to do that. Is this something you're willing to do? should I open another issue to discuss this?

**Comment by rocketraman** [comment]
> It looks like keepassxc will have to maintain a google cloud project and google drive application to do that. Is this something you're willing to do? should I open another issue to discuss this?

Another option is that users can create and use their own project. The way that the keepass plugin [KPGoogleSync](https://keepass.info/plugins.html#kpgsync) works is that it supports some "built-in" credentials, but can also sync to Google Drive via an owner-specified project as an entry in Keepass itself.

See https://github.com/walterpg/google-drive-sync/tree/master/doc#privacy-and-security and https://github.com/walterpg/google-drive-sync/tree/master/doc#configuration. It would be great if any integrated Google Drive storage support used the same (latter) mechanism for compatibility with KPGoogleSync.

**Comment by hifi** [comment]
We don't want to embed a revokable application key in the application itself. One workaround would be to fetch it online from keepassxc.org. Dropbox has said it should be okay for them.

If someone starts working on this they should create a generic interface where different cloud providers can be implemented.

Having an in-database custom credential is probably a good idea - though - it doesn't work initially so I'm a bit weary about that.

What I think would not be wasted work is to create the framework and single provider implementation with good UI integration and worry about credentials later but I cannot promise anything will be merged.

**Comment by madushan1000** [comment]
I've started some initial work on this, I'll put it on github when I have something working, I'm going in the oauth2 route(instead of app-specific password route, which I'm not sure goes along with google's TOS now) since you don't seem opposed to it in general. I'll get it working with an embedded token and then we can decide how to remotely fetch tokens or give the user ability to use their own token.

I think I'll be using parts of firebase c++ sdk(https://github.com/firebase/firebase-cpp-sdk), it's licensed apache v2. I hope this is compatible with your licensing model too.

**Comment by droidmonkey** [comment]
I'll be honest and frank, there is very little chance I'll allow this to be merged into our application.

**Comment by madushan1000** [comment]
oh, thanks for letting me know before I've stated any serious work :)

**Comment by rocketraman** [comment]
FWIW, I've scripted the missing functionality for Google Drive (or really, any backend supported by [rclone](https://rclone.org/)) syncing:

https://gist.github.com/rocketraman/820d94f2f9c8731a6f2d56cbc2ddb60f

This is lightly tested but so far it works for me. All it requires is bash and rclone.

**Comment by phoerious** [comment]
This is very unlikely to go anywhere. Closing.
