### ISSUE TITLE
TOTP Menu item disabled when no internet

### ISSUE THREAD

**Issue by geekwisdom** [keepassxreboot/keepassxc#7346]
I use a machine with a tight firewall policy that prevents pretty much any non-browser app from being able to access the Internet.

When using keepassxc, I have noticed that the TOTP menu becomes disabled. It seems that periodically the app checks for internet connection (for example to download favico) and when it does not detect a connection it disables 'internet menu items' like download favicon.

It also disables TOTP/MFA fill in, though this is not really necessary since this does not require an active internet connection to generate the codes.

**Comment by droidmonkey** [comment]
We don't do anything like that. Please post your debug information.
