### ISSUE TITLE
Anyone know how to make it work on this website

### ISSUE THREAD

**Issue by RexTC** [keepassxreboot/keepassxc#7347]
https://www.teeoff.com/customer/login-redirect
This website will not work with keepassxc but the browser's internal password manager have no issue locating user/password fields.
Any trick or it is keepassXC's bug/limitation?

Thanks for any suggestion or solution.
Rex

**Comment by droidmonkey** [comment]
Looks like the login is in an iframe from another site entirely. You need to add that other site to your entry's url list.

**Comment by varjolintu** [comment]
Add `https://my.golfid.io` as your entry URL. That's the iframe's source.
