### ISSUE TITLE
Download favicon for all entries without icon

### ISSUE THREAD

**Issue by kroka** [keepassxreboot/keepassxc#735]
## Expected Behavior

* _Tools > Download and set missing icons_
It will download the favicon and set it as symbol for each entry (for which no icon was defined, yet)

## Current Behavior

You have to download the favicon for every single entry.

## Context

Having a huge database without any custom icons set, this new feature would dramatically reduce manual effort.

_Update 2017/10/05:_ It might also be useful to add an option to force an update of existing favicons.

**Comment by Kusaha** [comment]
Yeah this feature would be really awesome (after they get around fixing the favicon fetching)

**Comment by TheZ3ro** [comment]
@kusaha what is the problem with favicon fetching?

**Comment by Kusaha** [comment]
@TheZ3ro 
When you try to get favicon from "https://*" URLs keepassxc always fails to fetch them, showing this error:
![2017-07-22_15-15-45_keepassxc](https://user-images.githubusercontent.com/7066695/28491394-d9bb39fc-6ef0-11e7-9434-2bba6bf0b7d3.jpg) 
but there's already a bug report of the same issue here: #678  
(Note: I'm using windows 10, and the 64bit version of keepassxc)

**Comment by sergeevabc** [comment]
@Kusaha, workaround is to use [Favicon downloader][1] plugin with original Keepass.

[1]: https://sourceforge.net/projects/keepass-favicon/

**Comment by tycho** [comment]
Just in case anyone else is having the same troubles I am...

For whatever reason I couldn't get the SourceForge mirrors to let me download the original Favicon downloader plugin for KeePass, so I'm using this plugin instead, which seems to work so far: https://github.com/navossoc/KeePass-Yet-Another-Favicon-Downloader

Looking forward to seeing this as a feature for KeePassXC so I can finally throw my old KeePass install away.

**Comment by JohnRobson** [comment]
I'm using KeePassXC 2.3.4 and I can't find this "favicon download" option. Where is this?

**Comment by sebast889** [comment]
An "Update all favicons" would also be useful. For first time downloading all favicons and for downloading and setting new favicons over old ones if there are any.

**Comment by varjolintu** [comment]
I opened a work-in-progress PR that you can try: https://github.com/keepassxreboot/keepassxc/pull/3169.

**Comment by zian92** [comment]
I did find a workaround: 

1. type * in the searchbar and it will list all the entries of your database. 
2. select all entries (e.g. ctrl + a)
3. right klick, last entry ist: download Favicons
This may take awhile to process all the entries but will soon start to download all icons

have fun! :)

**Comment by droidmonkey** [comment]
Recommend turning off auto saving before doing the above

**Comment by JohnRobson** [comment]
Maybe increase the "Favicon download timeout" to 60 sec.

**Comment by droidmonkey** [comment]
You can do that in the application settings

**Comment by machocam** [comment]
> I did find a workaround:
> 
>     1. type * in the searchbar and it will list all the entries of your database.
> 
>     2. select all entries (e.g. ctrl + a)
> 
>     3. right klick, last entry ist: download Favicons
>        This may take awhile to process all the entries but will soon start to download all icons
> 
> 
> have fun! :)

Not sure if there was an explicit feature built for this but this worked for me.

**Comment by Boldfor** [comment]
> Not sure if there was an explicit feature built for this but this worked for me.

Works great as a workaround!

**Comment by aetonsi** [comment]
Where is the functionality located? Is it `Entries`>`Download Favicons`? Is it recursive?
Because, for me, it doesn't do anything. I have only `Password Generator` and `Settings` under `Tools`....

**Comment by varjolintu** [comment]
@aetonsi Are you using "Use DuckDuckGo service to download website icons" from Application Settings -> Security?

**Comment by aetonsi** [comment]
@varjolintu yes i am. 
i also remember using this functionality to download all of the icons in my db, but i can't seem to find it anymore?

**Comment by droidmonkey** [comment]
If there is already a custom icon on an entry, then the bulk download feature will NOT replace that icon. You need to do an individual download to replace a custom icon.

**Comment by aetonsi** [comment]
> If there is already a custom icon on an entry, then the bulk download feature will NOT replace that icon. You need to do an individual download to replace a custom icon.

i understand that, i am asking, _where_ is this bulk download feature located? i thought it was under `Tools`, but maybe i don't remember correctly

**Comment by rugk** [comment]
@aetonsi Just select all/the entries you want to download, right-click and choose “download favicon”.

**Comment by aetonsi** [comment]
> @aetonsi Just select all/the entries you want to download, right-click and choose “download favicon”.

.. and do that in every single folder? or just in the tree on the left? if i do it on the root, nothing happens. if i do it on individual folders it works

**Comment by droidmonkey** [comment]
Do it in each folder (group).

**Comment by aetonsi** [comment]
Just so i understand, the `Download all favicons...` on a Group/folder does **not** recurse through subfolders?
I have tens of folders and multiple levels of subfolders, it would be unfeasible manually doing that.. for now i solved by searching `*` and selecting all _entries_ and doing `download favicons` on the entries themselves, but that's not very cool :\

**Comment by droidmonkey** [comment]
Using the group option should recurse down the folder tree. Like I said, however, that will not replace already existing downloaded icons. To do that you need to do the entry selection option. Searching for * and doing the download is cool 😎

**Comment by aetonsi** [comment]
Ok so it **should** recurse.. unluckily it doesn't, when i do it on the root group (the database). Nothing at all happens. No popup, no nothing.
It works, instead, on subfolders.
Is there a log or something i can check to look for errors?

**Comment by droidmonkey** [comment]
It does not recurse, although I can't decide if this is desired behavior or not. Recursing could be seen as a negative behavior. 

https://github.com/keepassxreboot/keepassxc/blob/develop/src/gui/DatabaseWidget.cpp#L852

**Comment by aetonsi** [comment]
Oh ok. So the `*` search trick is the only way to do it on the whole database, correct?

**Comment by droidmonkey** [comment]
Correct
