### ISSUE TITLE
Keepass installed on RDS server - login recovery not working

### ISSUE THREAD

**Issue by rsa31** [keepassxreboot/keepassxc#7351]
Hello,
We are using KeepassXC 2.6.6 on Windows 10 computers with the database on a shared network drive and the Mozilla Firefox web browser. Everything works perfectly.
When telecommuting, our users connect to a Microsoft Windows 2016 server RDS. From the RDS access, they have access to the shared network drive where the database is located.
KeepassXC 2.6.6 is installed on this RDS server with Mozilla Firefox version 91.5.0esr; in the user's RDS session, the KeepassXC Browser extension communicates well with the KeepassXC database and the login fields are well recognized.
Problem :
In the authentication forms, when we click on the green Keepass icon to automatically retrieve the credentials,nothing is retrieved and we don't get an error message.
Do you have any idea how to solve this problem?
With my thanks,
I wish you a nice day.
Best wishes,
[RSA31_KeepassXC_On_RDS.txt](https://github.com/keepassxreboot/keepassxc/files/7959528/RSA31_KeepassXC_On_RDS.txt)

**Comment by varjolintu** [comment]
Check the entry URL's. Those should match with minimum effort, for example use `https://site.com` or `https://sub.site.com/login` etc. and not a full URL with all paths etc.

Can you give an example about a site that doesn't work?

**Comment by rsa31** [comment]
Hello,
In fact, I have two databases and in the RDS session
In "Browser integration", the box "Search for matching IDs in all open databases" was not checked.
Thank you for your help.
I wish you a nice day
Best regards,
