### ISSUE TITLE
Save Entries History (old username/passwords)

### ISSUE THREAD

**Issue by APT-ZERO** [keepassxreboot/keepassxc#7353]
Hi

It's a great if you make KeePassXC save history of Entries
save when password / username / notes changed, what was the old data
when a user want to delete an attachment, ask if user want it to save in history or delete forever!

you can make it more more advanced, but it's important now to have old data, because we could change by mistake, or in future may we need to know our old password/username ...

**Comment by droidmonkey** [comment]
This happens already by default. Make sure your database settings (Database -> Database settings...) have history enabled.
