### ISSUE TITLE
Save draft and Lock/Close database

### ISSUE THREAD

**Issue by APT-ZERO** [keepassxreboot/keepassxc#7354]
HELLO

Please add new option to set, when Auto lock is enabled and time is over
Save draft and Lock database, instead of asking "You are editing an entry. Discard changes and lock anyway?"
and when we entered password again, resume

i'm not asking you to add this ability enabled by default, because may cause problems for users who adding big attachments to keepassxc
but it's a good option for most users

Also when user want to lock/close and also it's editing something, add this ability to save current changes as draft and continue

**Comment by droidmonkey** [comment]
Duplicate request.
