### ISSUE TITLE
Having issues with editing attachments

### ISSUE THREAD

**Issue by kokomo123** [keepassxreboot/keepassxc#7357]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
I'm currently having trouble with editing attachments on KeePassXC. I try to save and see if any changes were applied, but they aren't saving. 

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1.  Click attachment under entry
2. Open attachment, type in anything 
3. Save and close, open attachment again and see if it changed anything. 

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
I expected it to prompt me with do you want to merge changes from the temporary file of the actual attachment or discard changes and everything would work just fine. 

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
I go and edit the attachment by double clicking or clicking on the attachment with it opening up in Kate, I edit and save and close it. There aren't any pop up windows that are appearing or it saving changes I made on the attachment for the entry. 

## Context
[NOTE]: # ( Give us any additional information you may have. )
N/A at this time. Will edit if needed more info. 

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.6.6
Revision: 9c108b9

[NOTE]: # ( Pick choices based on your environment )
Operating System: Arch Linux 5.16.3-arch1-1
Desktop Env: KDE
Windowing System: X11

**Comment by droidmonkey** [comment]
This is implemented for the next version, 2.7.0
