### ISSUE TITLE
[Feature Request] Selective Auto-Type without duplicating entry

### ISSUE THREAD

**Issue by lcapriotti** [keepassxreboot/keepassxc#736]
Auto-Type sequence is fully customisable at the entry level, but there is only one auto-type sequence per entry.

## Expected Behavior
Be able to choose what information to use for the auto-type functionality upon need without setting up specific entries.

## Current Behavior
Only one auto-type setting is possible, ie a single field or combination (pwd or username & pwd, for example)

## Possible Solution
Allow creating more than one auto-type sequence, and if more than one is configured then the "Perform Auto_Type (Crtl-V)" entry should become a submenu with all defined sequences.

## Context
As there are sites that mandates typing username & password on some screens but only the password on others, auto-type can only be used on these sites by duplicating the related entries and customising the auto-type sequence. Not ideal.

## Debug Info
N/A

**Comment by weslly** [comment]
>but there is only one auto-type sequence per entry

Actually you can have more than one custom sequence per entry by using window title associations. You can get the title of the window or browser tab to create different sequences.

![image](https://user-images.githubusercontent.com/107672/27773051-18736110-5f47-11e7-9c7d-a495244d6349.png)

**Comment by droidmonkey** [comment]
Furthermore you can use entry cloning to setup multiple sequences per the same window.

**Comment by weslly** [comment]
Closing this since you can add multiple sequences with window associations and cloning/referenced entries, as @droidmonkey noted.

**Comment by Ian2020** [comment]
Would you consider re-opening? Cloning only copies username/password at the moment but for some logins more fields are needed. Also I would argue it is neater to have one entry per credential rather than multiple clones as well.

In addition some logins use the same window title across multiple pages meaning you need to choose on each page which auto-type sequence to use, you cannot distinguish by window.

A solution would also solve  #559

**Comment by zzflux** [comment]
> Would you consider re-opening? Cloning only copies username/password at the moment but for some logins more fields are needed. Also I would argue it is neater to have one entry per credential rather than multiple clones as well.
> 
> In addition some logins use the same window title across multiple pages meaning you need to choose on each page which auto-type sequence to use, you cannot distinguish by window.
> 
> A solution would also solve #559

This. More often than not, I'm dealing with web logins, so window title differentiation isn't going to work. There are many times I might need to type only one field or do something else non-standard. While it has been mentioned above as possible to achieve something like this by creating multiple entities that reference the original one (TIL references are possible), having entries such as "Yahoo-USERNAME/PASSWORD/ENTER", "YAHOO-USERNAME ONLY", etc. could cause a lot of clutter.

There are many relevant situations that come to mind:

Examples:
1. Signing up for a new service. I might have to put in a username (could auto-type, but not too much of a hassle to type it in manually just this once), some other personal info, then a password twice. If the password is auto-generated, I'd prefer to auto-type it, as manually transferring it would be cumbersome.
2. Services that ask to confirm a password e.g., to access secure settings. Here I'd like to auto-type just the password. 
3. Ditto for situations where services "remember" the account username but have been logged out for some reason.

Another big reason this would be nice is that the alternative is potentially less secure. The most obvious way to tackle the situations above is to copy the relevant information to the clipboard, but the clipboard is not known to be particularly secure. For example, KDE saves the full clipboard history by default.

Keepass 2.40 for Windows handles this pretty well: there's a sub-dropdown for custom autotype within the right click dropdown on every entry, and common situations, such as {USERNAME}{TAB}{PASSWORD} and {PASSWORD} are built-in. This is in addition to the (already implemented) configurable Ctrl+V autotype.

**Comment by Ian2020** [comment]
Since I commented this appears to have been fixed in that for one entry you can specify multiple auto-type entries with the same window title and you get to choose between them when activating global auto-type now (you did not before). At least that is the case for me on version 2.3.4.

**Comment by droidmonkey** [comment]
Yeah I thought that was possible now. I'll confirm and close if so.
