### ISSUE TITLE
Always modal, since ~Jan 20th, but no updates...

### ISSUE THREAD

**Issue by codingthat** [keepassxreboot/keepassxc#7360]
Hi, everyone!

Please forgive my cross-posting here—only doing so because [this Stack Exchange question](https://unix.stackexchange.com/questions/688306/keepassxc-suddenly-always-modal-possible-causes) isn't yielding any help.  I'm not convinced that KeePassXC is actually the source of the problem, but it's the only program doing this, and I have no idea why—I welcome your advice!

**Background:** KeePassXC 2.6.6 is the latest version from June.  My computer is newer than that, so this is the only version I've ever run on it, installed from `deb http://ppa.launchpad.net/phoerious/keepassxc/ubuntu focal main` from the start.  I'm running Linux Mint 20.3 (with MATE 1.26.0).  Everything was working fine until a few days ago.

**Problem:** For some reason, KeePassXC is now always modal:

- Alt-tabbing to another program (or clicking another program's taskbar button) gives the other program the focus (even the keyboard) but leaves KeePassXC on top.  I.e., I'm typing underneath the window I'm looking at.
- Even hitting the start button to bring up the Mint menu causes it to come up underneath KeePassXC.
- This is all true whether KeePassXC is fullscreen or not, and it doesn't matter if I'm in an entry, at the main list, or looking at search results.

**Workaround (not great---impedes normal workflow quite a bit):** Now the only way to get KeePassXC from covering other programs is to minimize it.

**Answers I *think* I've ruled out:**

- Since KeePassXC itself wasn't updated, I'm not sure it's the source of the problem, even though it's the only program exhibiting this behavior.
- One of [its dependencies][1] is Qt 5, but that (well, a bunch of `libqt5*` packages, but none of the other ones listed like `qtbase5`), according to `dpkg.log`, was last updated Jan 7th, quite a bit longer ago than when I believe the problem started happening (~Jan 20th).
- None of the other dependencies have been updated since Jan 7th.
- I haven't touched any of the settings within KeePassXC.
- Full cold boots do not fix the problem.

**Question:** What other system updates or changes could have broken it?

Thanks in advance!  :-)

  [1]: https://github.com/keepassxreboot/keepassxc/blob/develop/INSTALL.md#build-dependencies

**Comment by codingthat** [comment]
Never mind...apparently I must have hit the "Always on Top" shortcut at some point without realizing I had done so.  I didn't even know that option existed, and it's only in the View menu, not the settings.  Sorry!

**Comment by hemanti0503** [comment]
Still thank you for posting this issue (and your solution), @codingthat! Stopped me from opening my own issue. :)

I didn't know either, that this option existed (like you, I checked the settings before). Must have hit the shortcut accidentally.
