### ISSUE TITLE
referenced password don't work with alternative url

### ISSUE THREAD

**Issue by ThomKrue** [keepassxreboot/keepassxc#7361]
Password field is emtpy when using alternative URL in KeepassXC - only when username and password is REFerenced from another entry
## Expected Behavior
password should be filled in

## Current Behavior
plugin fills in username but no password
When i use the password without reference in KeepassXC the plugin can fill in the password

## Possible Solution
sorry, don't know

## Steps to Reproduce (for bugs)
1. Create keypassXC entry with username/password
2. Create a new entry with username and password referenced to first entry 
 aka {REF:U@I:76...} and {REF:U@PI:76...} (use id from first entry)
3. In the entry containing the referenced credentials add a url and alternative url
4. If using the alternative url, keypass browser plugin fills in the username but no password

## Debug info

KeePassXC - 2.6.6
KeePassXC-Browser - 1.7.11
Operating system: Linux
Browser: Firefox

**Comment by droidmonkey** [comment]
Your password reference syntax is not correct. It should be {REF:P@I:uuid}

https://keepassxc.org/docs/KeePassXC_UserGuide.html#_clone_an_entry

**Comment by ThomKrue** [comment]
Wow. How easy can it be ;-)
{REF:P@I:uuid} is correct.
Thanks for support!
