### ISSUE TITLE
KeePassXC in WASM

### ISSUE THREAD

**Issue by alensiljak** [keepassxreboot/keepassxc#7362]
## Summary
This may be wild imagination at this stage but I believe it will happen sooner rather than later. 
Has anyone tried to compile KeePassXC for Webassembly? 

Some hypothetical benefits would be easier multiplatform support, and even close-to-native parsing of kdbx databases in a browser. 

Naturally, not the whole GUI would run in a browser, and I'm not sure if GUI can run in another WASM engine, but the core database management library certainly should be compilable to WASM (fingers crossed). 

Any opinions, and hopefully experiments? 

## Context
Webassembly seems to be progressing fast and provides benefits of fast execution on various platforms, including the web browser. This, in effect, should simplify the distribution while providing near-native performance.

**Comment by alensiljak** [comment]
You may have already seen this: https://blog.1password.com/1password-x-may-2019-update/

1Password has been migrated to Wasm with huge improvements in performance.

The browser plugin could technically merge with the desktop app. The only issue being the synchronization of the database file.

**Comment by droidmonkey** [comment]
We have absolutely no interest in running the application from the browser. There would be no performance improvement over our compiled application. Moving over to wasm would likely require a complete recode and be not worthwhile. If you want to use keepass in a browser you should use KeeWeb.

**Comment by alensiljak** [comment]
That is not entirely true because a big part of keepassxc is the browser extension.
Besides that, this only answers a part of the question because webassembly is not meant only for running in a browser. Quite the contrary.
But ok. The tone of the answer is pretty clear. Thanks.

**Comment by phoerious** [comment]
KeePassXC is a cross-platform application already. Migrating to WASM wouldn't change that, but it would make everything slower.

**Comment by alensiljak** [comment]
> Migrating to WASM wouldn't change that, but it would make everything slower.

Meaning you have tried already?

**Comment by phoerious** [comment]
No, but web assembly simply will not be faster than native machine assembly. That said, I know that Qt has been successfully compiled to WASM in the past, so you may try that on your own volition, but we are not interested in supporting that.

**Comment by droidmonkey** [comment]
Sorry for being blunt earlier. The big problem we would face is all the os specific features we have built in likely wouldn't translate over to wasm. Even Auto-Type is likely not possible without a shim. In which case you might as well keep the current application. 

Running from the browser means you are sharing memory space with the browser, or at the very least under the control of the browser process. This leaves you vulnerable to various browser attacks. 

The browser extension is really light on code and processing functions. The most intense thing it does it monitor page changes and search for login fields. Other than that, most actions are actually happening in the keepassxc client application.

**Comment by alensiljak** [comment]
Sure, thanks. I was just wondering if it was worthwhile to explore this new area with an experiment or a discussion.
Based on the goals of wasm I'd say that there is a lot coming in the next year or two so the performance as well as other host abilities would improve. But this is all wishful thinking at this stage, considering the browser is the only decent wasm runtime (that I know of, at least) and manual optimizations are needed for performance tuning.
Thanks for the comments!

**Comment by alensiljak** [comment]
> Running from the browser means you are sharing memory space with the browser, or at the very least under the control of the browser process. This leaves you vulnerable to various browser attacks.

That's true. Interestingly, this characteristic is listed as the benefit as running wasm apps in a sandbox is supposed to be (more?) safe and trusted.
But as you mention, this being a desktop application, all this may not provide much benefit.

**Comment by droidmonkey** [comment]
Hehe depends on whose sandbox you are running in. Tech companies love to throw that term around, but you are still sharing memory under the same user account with the same permissions. That doesn't provide much in the way of actual sandboxing like you would get with a virtual machine.
