### ISSUE TITLE
Auto-type window is always tiny

### ISSUE THREAD

**Issue by DC7IA** [keepassxreboot/keepassxc#7365]
## Overview

Auto-Type window is always tiny:

![image](https://user-images.githubusercontent.com/26351852/151963748-1ccdc34a-69a9-4b29-8681-43438c97d1d8.png)

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Press Auto-Type key combination
2. window is tiny

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

Window is not tiny, you can actually see things and if resized opens at the same size.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

Window is always tiny.

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
```
KeePassXC - Version 2.6.6
Revision: 9c108b9

Qt 5.15.2
Debugging mode is disabled.

Operating system: Debian GNU/Linux bookworm/sid
CPU architecture: x86_64
Kernel: linux 5.15.0-3-amd64

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- libgcrypt 1.9.4
```

[NOTE]: # ( Pick choices based on your environment )
Operating System:  `Debian GNU/Linux` and `Ubuntu`
Desktop Env: Mate and `i3`
Windowing System: X11

**Comment by droidmonkey** [comment]
This is fixed in 2.7.0
