### ISSUE TITLE
New feature: URL Aliasing

### ISSUE THREAD

**Issue by MRSchexnayder** [keepassxreboot/keepassxc#7367]
In many scenario’s it is more and more common to find that a single credential is used for multiple services. For instance, in an SSO environment, the same credential is used for many different URL’s. Additionally some commercial services share a common user base but have multiple valid URL’s. 

Currently the only way to handle this scenario is to create duplicate entries and then use references to a common credential. This is the method I’m currently using. 

The feature would allow users to identify ‘alternate’ URL’s that should resolve to a single credential, overall reducing the number of entries needed.

**Comment by droidmonkey** [comment]
Use the additional urls feature under the browser settings tab when editing an entry. You need a newer version of keepassxc.
