### ISSUE TITLE
Add hour options (4, 8, 12, 16) to password expiration presets

### ISSUE THREAD

**Issue by Tspinler** [keepassxreboot/keepassxc#7369]
## Summary
Add options for expiring passwords after smaller increments such as 4 hours, 8 hours 12 hours etc.  Better yet, allow me to add custom presets to what I need.

## Examples
Expires after Presets: 4 hour, 8 hour, 12 hour, Custom

## Context
We use passwords that expire after 12 hours.

**Comment by droidmonkey** [comment]
This seems like a password that is issued to you by a centralized authentication service then. Is that true? If so you wouldn't necessarily want to mark it as expired by every 12 hours just refresh the password given and enter it into that same entry. Either way, you can manually edit the time field in the expired field to set the hours.

**Comment by Tspinler** [comment]
We use checkout IDs/passwords on a daily basis.  Our standard is 12 hour password expiration for most user IDs.  It would be useful if there were a preset for 12 hours.  I know i can modify the expiration time, but since I do this daily, a preset would be handy.

**Comment by schlimmchen** [comment]
Related to #4896.
