### ISSUE TITLE
auto-type freezes app when editing database entry

### ISSUE THREAD

**Issue by PeeTeeH** [keepassxreboot/keepassxc#7370]
## Overview
Performing auto-type configured for specific window while editing database entry freezes the app with no option to cancel auto-type

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. set up autotype related to specific window name, at least TWO different entries should refer to this window app so entry selection subwindow should open
2. in keepass xc config set up to ask for specific entry if multiple found
2. start editing any entry
3. wait till app tries to auto-close database by showing info about uncommited changes to database, leave it in the background
3. perform auto-type hotkey on window specified in database
4. Keepass XC 2.6.6 app freeze with no option to cancel auto-type or cancel

## Expected Behavior
Auto-type windows should enable exiting auto-type by pressing ESC or closing the window with X

## Actual Behavior
Auto-type entry-selection window stays open with no option 

## Context
Keepass is configured to ask for specific entry if multiple entries match auto-type parameters for specific entry. In my case I use auto-type for Thunderbird, on 2 different PCs, the same app window name but different credentials.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION 2.6.6
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 10
Desktop Env: generic windows 10, ENG with Polish locale

**Comment by droidmonkey** [comment]
Please try replicating with 2.7.0 snapshot, the whole autotype experience was overhauled. https://snapshot.keepassxc.org

Although the core problem may be that you have a modal dialog waiting for your input:

> wait till app tries to auto-close database by showing info about uncommited changes to database, leave it in the background

**Comment by PeeTeeH** [comment]
I used latest 2.7.0 snapshot.
While "Lock database?" prompt is open ("You are editing an entry. Discard changes and lock anyway?") auto-type works without problems.
After invoking auto-type shortcut, "lock database?" prompt disappears.  After auto-type, it re-appears in the background.

Problem is SOLVED in snapshot 2.7.0.
Thank you! Shall I close this bug for 2.6.6 now?

**Comment by droidmonkey** [comment]
Yup we are releasing 2.7.0 this month
