### ISSUE TITLE
Selecting Multiple Groups to Manipulate

### ISSUE THREAD

**Issue by 641i130** [keepassxreboot/keepassxc#7375]
## Summary
The functionality in the content side (stuff inside groups) isn't mirrored on the group side (ie, you need to select one group at a time to move or delete). 

I want to be able to select multiple folders and move/delete them easily. I have to do everything one at a time with the current version. 

I'd like to hold shift or control to select a large selection.

**Comment by droidmonkey** [comment]
Duplicate request
