### ISSUE TITLE
Copy URL in main context menu

### ISSUE THREAD

**Issue by Riko01** [keepassxreboot/keepassxc#7377]
## Summary
As, username, password and URL are the most copied options I would prefer to have the copy URL option in main context menu.

## Examples
![image](https://user-images.githubusercontent.com/12291869/152339115-9181bb58-03b7-4147-8fb8-fdb77159d64d.png)

## Context
I often have to copy the URL into different windows, withdrawing it to the main context menu would increase my comfort and save me extra clicks and moves.

**Comment by Anselm970** [comment]
Hi, have a look here: [https://github.com/keepassxreboot/keepassxc/issues/7377](url)

**Comment by Riko01** [comment]
Hello @Anselm970, the link points to this issue and the url in the link is incomplete.

**Comment by Anselm970** [comment]
> Hello @Anselm970, the link points to this issue and the url in the link is incomplete.

Sorry. I hope, this one works.

https://app.element.io/#/room/#keepassxc:mozilla.org/$FiVwHsYnbuVCMtFPu3tj7coXVspDM7jWbhD0m4lPpJw

**Comment by Riko01** [comment]
Thank you for the reference, seems the guy would appreciate the same thing as me. Copying URL from the top bar is nice, but if I use it often, having it in context menu is better for muscle memory.

**Comment by Squire4Hire** [comment]
I'd like this feature too. With the way browsers now operate with separated account control, copying the URL is the way to go. Opening a link into a default containment is pretty useless.
