### ISSUE TITLE
One Time Pad (Vernam Cipher) symmetric files encryption/decryption

### ISSUE THREAD

**Issue by noMrBBg** [keepassxreboot/keepassxc#7379]
Hi,
would it be possible for you to add a Vernam file encryption and decryption feature? I am looking for universal programs that work on any platform, and such programs are scattered and of suspect quality. I think this option could be hidden for advanced users.

1. generate a 700MiB file as a OTP key (TailsOS) in ramdisk (then copy to CD):
`openssl rand -out FILE.key 734003200`
or
`dd if=/dev/urandom of=FILE.key bs=734003200 count=1`

2. confidential files, e.g. placed in a .7z file (base file 100KiB)

3a. KeePassXC take OTP key, base file and create output (like .7z.otp), user could set "start at byte..." (position) in OTP key

3b. (Second computer) KeePassXC decrypts the .7z.otp file with the key.

The option with choosing a ready-made key is simple (XOR, 2 file in, 1 file out), and you could also implement key generation, etc. Some of the extra options could be consumed from the password generator.

There are some interesting implementations, below are some (and some clean UI).

- [Rijmenant's CT-46 OTP](http://users.telenet.be/d.rijmenants/ct46otp10.zip) (freeware, [simple GUI](https://raw.githubusercontent.com/noMrBBg/one/main/ct46-or8.png))
- [Solid Encryption 1.22](http://www.solid-programs.com/setup.exe) (trial, [great GUI](https://raw.githubusercontent.com/noMrBBg/one/main/se-or8.png))

Other:
- [osOTP](http://www.tcltk.info/programme/osotp/osotp.html) (GPL, Tcl/Tk, GUI)
- [Asencry 2.05](http://atripalda.homeip.net/downloads/sicurezza%20e%20privacy/sicurezza%20e%20privacy.htm) (freeware, GUI)
- [Crypt::OTP](https://metacpan.org/pod/Crypt::OTP) (perl)
- [mobilefish](https://www.mobilefish.com/services/one_time_pad/one_time_pad.php) (javascript, GUI)
- [finalcrypt](https://github.com/ron-from-nl/FinalCrypt/releases/tag/latest) (java, user tracking, GUI)
- [VernamFS](https://github.com/UW-APL-EIS/vernamfs) (BSD, C)
- [perfenc](https://sourceforge.net/projects/perfenc/) (GPL, C++)
- [fxor](https://github.com/abderraouf-adjal/fxor/blob/master/FAQ) (BSD, C)
- [OTP Gen](https://github.com/iworkinpixels/otp-gen) (Python)
- [onetime ](https://code.librehq.com/kfogel/onetime) (MIT, Python)

OTP is simple, but very powerful when used well. It seems that the use of OTP is out of project scope, but which password program, [encryption tool](https://sourceforge.net/p/veracrypt/discussion/features/thread/ceb3dd9955/) is as popular as KeePassXC?

You could name this option "Bullrun".

Take care

---

- [Khan Academy](https://youtu.be/FlIG3TvQCBQ)
- [The Modern Rogue](https://youtu.be/R5LqOqaBYG8)
- [Crypto Museum](https://www.cryptomuseum.com/crypto/otp/index.htm)
- [One-time-pad encryption](https://crypto.stackexchange.com/a/42749)
- [The Numbers Station (2013) trailer 📡🔑🔫](https://www.imdb.com/video/vi3395397401)
##### Dirk Rijmenants
- [Intro](http://users.telenet.be/d.rijmenants/en/onetimepad.htm)
- [Is One-time Pad History?](http://users.telenet.be/d.rijmenants/papers/is_one_time_pad_history.pdf)
- [The complete guide to secure communications with the one time pad cipher](http://users.telenet.be/d.rijmenants/papers/one_time_pad.pdf)
###### Other papers
- [One-Time Pad (OTP) Implementation in the Linux Kernel](https://www.ucalgary.ca/sites/default/files/teams/245/4.%20Shoukat-%20Mar%2020.pdf)
- [Theoretical and Practical Significance of One-Time-Pad Cryptography](https://www.csuohio.edu/sites/default/files/75%20A.pdf)
- [One-Time Pad & Kerckhoffs’ Principle](https://web.engr.oregonstate.edu/~rosulekm/crypto/chap1.pdf)

**Comment by droidmonkey** [comment]
You're welcome to do this as a fork of our program but we will not. OTP is more of a thought experiment then for any real production use. Modern stream ciphers with a randomized key and IV are far superior to any OTP implementation. KeePassXC is also not a file encryption program.
