### ISSUE TITLE
Add ability to open entries in a popup window

### ISSUE THREAD

**Issue by stysedo** [keepassxreboot/keepassxc#738]
Sorry, due to a slip of the hand, I accidentally created this post empty!
I'm editing it to fill it in...

I'd like to suggest an option to allow for entries and files to be opened in their own window instead of the current interface (at last in macOS) which seems to be 'single window.'

## Expected Behavior

Opening an entry would open it in its own window allowing us to have multiple entires open at a time. Opening a file would open it in its own window allowing us to view multiple files at once even having multiple entries open from different files simultaneously. 

## Current Behavior

Currently the GUI is what I would describe as, 'single window mode.'  Entries are viewed in the main window which limits us to viewing one entry at a time.  Files are opened as Tabs in the main window limiting us to viewing one file at a time.

## Context

I often need to refer to information stored in another entry or file while creating or viewing an entry.

**Comment by phoerious** [comment]
?

**Comment by stysedo** [comment]
Sorry, due to a slip of the hand, I accidentally created this post empty!
I've edited it to fill it in...

**Comment by droidmonkey** [comment]
@phoerious do you think this is valuable? I don't know if its worth the overhead or couple this with customized entry layouts.

**Comment by phoerious** [comment]
Sounds like a lot of extra work and handling of edge cases for a request I have heard exactly once so far.

**Comment by droidmonkey** [comment]
Agreed, closing

**Comment by marco-brandizi** [comment]
This is (was?) about allowing for opening multiple entries in a database, a feature that is useful in a number of cases (eg, migrating data from one service to another), and I can't see why it would be difficult to realise a behaviour that exists in many other desktop and web applications.

**Comment by Balls0fSteel** [comment]
Years later, I still wonder why this was closed. It's such a great feature of KeePass. I use it daily. Well, used. Unfortunately due to Authy killing their desktop app, I had to move to KeepassXC because it has native OTP support. But unfortunately, I am unable to open multiple entries at once anymore, which makes using the whole app and database very cumbersome.
