### ISSUE TITLE
Generated Steam TOTP invalid

### ISSUE THREAD

**Issue by mpldr** [keepassxreboot/keepassxc#7382]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
Keepass: 346ND
steamguard-cli: N4QD3

I think they should be equal.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Setup Steam TOTP
2. Compare code from app/generator with the one generated by KeepassXC
3. notice that they are different

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
I'd expect both codes to be the same, since TOTP generation is a deterministic process

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
The genereated codes do not match

## Context
[NOTE]: # ( Give us any additional information you may have. )
I have tried the procedure with both extracting from an android backup (after reenabling backupability of the steam app) and [steamguard-cli](https://github.com/dyc3/steamguard-cli), and since this happens with both, I assume Keepass to be the issue.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.6.6
Revision: 9c108b9

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: Sway
Windowing System: Wayland

**Comment by droidmonkey** [comment]
Sync your computer time

**Comment by mpldr** [comment]
My fault, I forgot to enable timesyncd after reinstalling the OS. Still curious why steamguard-cli got the correct code, but that's not part of this issue, thanks.

**Comment by droidmonkey** [comment]
They might pull time directly from a time source

**Comment by droidmonkey** [comment]
Yup they use the time provided by the steam api server to generate the code: https://github.com/dyc3/steamguard-cli/blob/c6bd5b5dc4831bc82600bd1af1f7aec8d3cc381b/src/main.rs#L494

**Comment by mpldr** [comment]
Then I'm glad that KeepassXC provides the localtime token instead of
phoning to some server without asking first.
