### ISSUE TITLE
Error and HMAC mismatch

### ISSUE THREAD

**Issue by ph13t0n** [keepassxreboot/keepassxc#7385]
Today, I have not access to my database file, with my passwords, emails, accounts, etc. inside of it. I am completely screwed over until I regain access to these files, as I used the handy KeePass Password generator included in the app.
I have noticed several other people have experienced this issue, and it seems it's still not fixed.

##Steps to Reproduce
Open KeePassXC.exe
Open my password database
Login with correct credentials + Key File
Receive HMAC mismatch error

## Expected Behavior
Open and be able to search and handle my credentials

## Actual Behavior
Error while reading the database: Invalid credentials were provided, please try again.
If this reoccurs, then your database file may be corrupt. (HMAC mismatch)

## Context
I´m a sad and a lonely person

[NOTE]:
KeePassXC - Version 2.6.6
Revision: 9c108b9

Qt 5.15.2
Debugging mode is disabled.

Operating system: Windows 10 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.19044

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
- libgcrypt 1.9.2-unknown

[NOTE]: #
Operating System: Windows
Windowing System: 10 version 2009

**Comment by droidmonkey** [comment]
Good day, we need more information to understand your problem.

1. Have you recently changed your database credentials? 
2. Have you updated your KeePassXC version?
3. Are you using any other keepass compatible applications at all?
4. Does it open on another computer? 
5. Are you storing your database on a USB thumb drive? Network drive? Synced with the cloud? 
6. Is the size of your database file what you expect it to be? Mind sharing that size (kb or mb)?

And finally, have you tried any of your database backups?

**Comment by zortos293** [comment]
same here

**Comment by ph13t0n** [comment]
Thanks for answer and sorry for the delay 
> 1. Have you recently changed your database credentials? 
Answer: not what I know, no. Tried to reconnect thru back-up from my NAS but my password is rejected.

> 2. Have you updated your KeePassXC version?
Answer: Yes, but I did that after the issue because I thought that should solve the issue. 

> 3. Are you using any other keepass compatible applications at all?
Answer: No

> 4. Does it open on another computer? 
Answer: My mobile, laptop and my main computer

> 5. Are you storing your database on a USB thumb drive? Network drive? Synced with the cloud? 
Answer: I have the database on my NAS and in the Google cloud, just because I need to have acces to the database. My NAS has only the back-up files.

> 6. Is the size of your database file what you expect it to be? Mind sharing that size (kb or mb)?
Answer: No worries - size does matter in the digital area. The file is 79.4 kb, but I noticed that the back-up file is only 1.6 kb, that's low. Interesting.

> And finally, have you tried any of your database backups?
Answer: Yes, I have done what I can imagine. But I'm not a techy guy.

**Comment by droidmonkey** [comment]
If it only fails to open on one computer, then that computer has a RAM problem. Try doing a ram test.

**Comment by cgbm** [comment]
I have the same issue since I updated to the latest version

**Comment by droidmonkey** [comment]
You probably need to update your keyfile from the older version.

**Comment by zortos293** [comment]
How

Op ma 14 feb. 2022 18:27 schreef Jonathan White ***@***.***>:

**Comment by cgbm** [comment]
> I have the same issue since I updated to the latest version

my sincere apologies, my memory betrayed me. it works all fine with v2.6.6. thank you very much for the super quick reply.

i will donate to the project!

**Comment by droidmonkey** [comment]
There is nothing we can do here so closing this.
