### ISSUE TITLE
CSV import: control characters for line breaks in notes are not respected

### ISSUE THREAD

**Issue by Se6** [keepassxreboot/keepassxc#7387]
Overview
-------------
Importing a CVS file with a note fields containing control characters like `\n` are not respected despite enabling "Consider \ an escape character" 

Steps to Reproduce
--------------------------
- Create a CSVfile which reads:
```
"group1","mytitlle","myusername","mypassword","www.example.com","line 1\nline 2\nline 3"
``` 
- Import it

Expected Behavior
-------------------------
To see in notes:
```
line 1
line 2
line 3
```

Actual Behavior
---------------------
The notes appears as:
```
line 1nline 2nline 3
```

Context
-----------
Linux.
Versions  2.4.3 and latest (2.7.0-snaphot)

Extra notes
---------------
I also tried with `\r\n` instead of `\n` with the same result.

**Comment by droidmonkey** [comment]
Generally speaking CSV parsers do not interpret escaped characters besides quotes. Does it work if you insert a literal newline?

**Comment by Se6** [comment]
You can not have a literal newline in a CSV file. 
This bug is also realated to #7243: "line breaks in "notes" fields are not handled in CSV export"
Indeed it produces a malformed CSV file....

We should be able to export to a CSV file and import it again and have all the fields the same. Currently that does not work properly for notes.

**Comment by droidmonkey** [comment]
See bullet point 6... https://datatracker.ietf.org/doc/html/rfc4180#section-2

> Fields containing line breaks (CRLF), double quotes, and commas should be enclosed in double-quotes.  For example:
> 
>       "aaa","b CRLF
>       bb","ccc" CRLF
>       zzz,yyy,xxx

**Comment by Se6** [comment]
You're absolutely right indeed! Thank you. 
I have managed to import properly with CSV like:
```
group1,mytitlle,myusername,mypassword,www.example.com,"line 1
line 2
line 3"
```
Thank you very much!
