### ISSUE TITLE
Accessing the credential store takes around 6 seconds .

### ISSUE THREAD

**Issue by yadneshMedhekar** [keepassxreboot/keepassxc#7390]
Accessing the credential store takes around 6 to 7 seconds .I have two questions generally how much time does it takes to access  and fetch  the credential store via a java library. And how can we reduce this time to milliseconds ?

**Comment by droidmonkey** [comment]
Not sure what you are referring to. If it is decrypting your database than you need to use less onerous settings for the key derivation. You can do this automatically in database security settings, move the slider down to 1 second for encryption time.
