### ISSUE TITLE
Add an option to change the window X from closing to minimizing.

### ISSUE THREAD

**Issue by ramit99** [keepassxreboot/keepassxc#7392]
I'll open the minimized window of keepassxc to search for an entry.
Next, via muscle memory, I'll "X" out of that window" once finished, instead of hitting the arrow to clear my search entry and then minimize keepassxc's window.

I'll discover what I did the next time I need keepassxc to perform an auto-fill.
I'll see in the browser, that keepassxc status is inactive and realize what I did, again.... and again, and again......
Need to fire keepassxc backup, unlock DB, and get my browsers to reattach to keepassxc.

I'm proposing keepassxc adopts what I've seen other programs do it that reside in the background waiting to be used, in their configuration settings, they offer to change the window X from close to minimize, and offer a "Close" in their menu bar selection, or context menu item for the icon when in the taskbar. So would be much tougher to accidentally close the keepassxc session than it is now.
TeamViewer is one that does this. It works well and wards off the X muscle memory.

Maybe also add a selection that the window "X" will also clear the search field while minimizing the keepassxc window.

**Comment by droidmonkey** [comment]
There is already this option, go to the bottom of the application settings.

**Comment by ramit99** [comment]
> There is already this option, go to the bottom of the application settings.

LOL -- I literally just found it, and came back to delete my request. I feel like an idiot after looking for it several times. Like the ketchup in the fridge I can't find.
