### ISSUE TITLE
Suggestions for custom field names

### ISSUE THREAD

**Issue by Offerel** [keepassxreboot/keepassxc#7395]
## Summary
Please add suggestion names for custom fields, based on existing entries. For example, i have an entry, with a custom field, where the name of the custom field = "E-Mail". I i now create another entry and add a custom field, i would like to choose a) from a list of field names, including "E-Mail" and b) choose a name i can type by my own.

## Context
I use custom fields a lot, with different field names. To avoid a real mess of different spellings for the same field name, i would like to re-use previously defined field names.

**Comment by droidmonkey** [comment]
#5502
