### ISSUE TITLE
Force immediate database file synchronization on storage hardware after saving.

### ISSUE THREAD

**Issue by abderraouf-adjal** [keepassxreboot/keepassxc#7398]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
Force immediate database file synchronization on storage hardware after saving.

## Examples
After database save action, run OS command `sync`.

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
Adding option in settings [immediate storage cache sync ON/OFF] to force immediate database file synchronization on storage hardware after saving is important for users who might experience events that might cause the saved database to never get saved correctly in the file system, because it can be in the storage cache memory and not yet committed to FS, for example those events might be:
- Power outage.
- Kernel panic.
- File system bug in cache mechanism.

**Comment by droidmonkey** [comment]
This is already done by Qt. We don't do any low level file operations.

**Comment by abderraouf-adjal** [comment]
To be done with Qt, at least the usage of `QIODevice::Unbuffered` in `QIODevice::OpenModeFlag` should be on, that will enable non-buffered I/O in [Database::performSave](https://github.com/keepassxreboot/keepassxc/blob/9c108b95100bfa3b172edcfd5754aa2e831a3221/src/core/Database.cpp#L282).

However, correct me if I'm wrong.
Thank you.

**Comment by droidmonkey** [comment]
That just means it writes directly to disk and not a temporary memory buffer before disk. When the file is closed or committed the buffer gets flushed to disk already.
