### ISSUE TITLE
A Cumulative view of all the entries irrespective of folder structure

### ISSUE THREAD

**Issue by Aravinth-Earth** [keepassxreboot/keepassxc#7399]
## A new temporary view/section (like a reporting), to list out all the entries sorted by last updated date
[NOTE]: # Enabling user to get a glimpse of how old their entries/passwords are (Similar to the sorting function within any folder/sub-folder structure we already have) across folders or in the entire database in single view

## Context
[NOTE]: # I basically want to change my password occasionally, But with my multi-level folder/sub-folder design, It's not easy to find out the older(est) entry across database to change it!!!

**Comment by droidmonkey** [comment]
Search for *

**Comment by Aravinth-Earth** [comment]
My bad, I didn't though this would be this simple :)
