### ISSUE TITLE
Copying username or password from an entry now broken

### ISSUE THREAD

**Issue by ioogithub** [keepassxreboot/keepassxc#7400]
Copying username or password for any entry does not work.

Click on a entry:
- right click, Copy Username (...nothing copied)
- Copy Password (...nothing copied)
- Ctrl + C (...nothing copied)

This copy operation still does work, however this turns a one step operation into a 5 step, so not ideal
1. Double clicking on an entry
2. clicking into the password field
3. typing Ctrl+H
4. highlighting the password
5. right clicking and selecting 'Copy' 

also we lose the ability to automatically clear the clipboard.

This happened after a recent system update. All other applications copy functions still work. I only see keepassxc affected.

Keepassxc: version 2.66
System: KDE Neon 5.24
Graphics Platform: X11
Kernel: Linux 5.11.0-34-generic x86_64

**Comment by droidmonkey** [comment]
Are you using Wayland? If so this would be a bug against Qt's qwayland not us.

**Comment by ioogithub** [comment]
I am using X11 as mentioned in the post.

I did try wayland when i first saw the issue to troubleshoot however I could not even run the application at all with wayland, I got several errors.

**Comment by droidmonkey** [comment]
This is not a problem with our application, per say, if you updated dependencies. Try using our snap or appimage to confirm it is in fact your system.

**Comment by ioogithub** [comment]
Thanks, I just installed the flatpack version and I can confirm that the copy function does not work with this version as well. I can go ahead and install the snap as well if it would be helpful.

Also, another area where it does not work is the copy password button in the Generate password window however if I click on the show password button, highlight the password and manually copy it, it does work. This is similar to the first report.

So if it isn't a problem with keepassxc but is instead a problem with a dependency that keepassxc uses to work then isn't the end result the same? The application function no longer works on this OS.

I have been testing all the other applications I have installed on my system with a copy functions but they all work as expected. I also tried to turn off the 'clear clipboard' feature but that did not have any effect.

What dependencies does the keepassxc copy function depend on where selecting text from a field and manually copying it works but the menu and buttons don't work.

**Comment by droidmonkey** [comment]
We use Qt to manage the clipboard. The operating system handles the case where you right click text and click copy. There is no way this is a problem within our code and only on your computer. Do you have some sort of managed clipboard enabled that might be misbehaving with our security meta data preventing copying to cloud service and history?

**Comment by ioogithub** [comment]
I am using Qt 5.15.3. I don't have any managed clipboard apps. KDE does have a 'Clipboard Contents' app where I can see the history of all objects copied to the clipboard. This app is running with default options, I have never configured it.

I have tested every application with a GUI installed and copying is working for all of them including wine applications. I can copy objects such as image files etc.

The only case that does not work is the copy buttons and right click menus in keepassxc.

I do see the message "Clearing the clipboard in x seconds..." when I perform the copy operation but the data never makes it to the clipboard.

Is there a log or debug mode or something else I can look at?

**Comment by droidmonkey** [comment]
What distribution are you using (Fedora, Ubuntu, etc)?

**Comment by ioogithub** [comment]
KDE Neon.

So I have upgraded again to version 5.24.1 and the problem disappeared. It must have been a library from the 5.24 upgrade. The ticket can be closed, thanks.
