### ISSUE TITLE
Sync Conflict with Nextcloud at every Database save through Desktop-App

### ISSUE THREAD

**Issue by muffinmaster1024** [keepassxreboot/keepassxc#7403]
Everytime the database is saved or autosaved it generates a file sync conflict with nextcloud. When updated or saved through Browser-Plugin this does not happen. 

I have my .kbdx stored in a folder that is synced through Nextcloud Desktop Client on Ubuntu 20.04 LTS. 
-Keepass 2.6.6 from flatpak
-Nextcloud 3.4.2 from apt

This happens since a few days.
On another machine where Nextcloud is installed through flatpak this does not happen. (When installing it through flatpak on this machine the problem persists)

**Comment by droidmonkey** [comment]
Compare the versions of nextcloud, this sounds like their bug. We just write files.

**Comment by muffinmaster1024** [comment]
Nextcloud version is 3.4.2 throughout

**Comment by droidmonkey** [comment]
Save the database as a new file (save as) and see if that file causes problems. If not just use that new file. This isn't a bug with keepassxc. You might also want to clear the local cache on the affected computer and resync from nextcloud.

**Comment by muffinmaster1024** [comment]
Saving as a new file solved the issue. Sometimes the solutions too simple to think of... Thanks a lot!
