### ISSUE TITLE
KeepassXC won't open on Ubuntu 20.04.1

### ISSUE THREAD

**Issue by obtusedev** [keepassxreboot/keepassxc#7406]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
KeepassXC snap won't open from command line or clicking on icon.
This is after uninstalling and reinstalling the snap package a couple of times.
Seems to be a recent issue since it worked around ~ 2days ago.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Click icon -> get loading spinner and nothing
2. Run keepassxc from cli -> gets error message below.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Be able to open KeepassXC from icon or command line.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
KeepassXC not opening from icon or command line.

## Context
[NOTE]: # ( Give us any additional information you may have. )
Here is the output when running from command line.
```
(keepassxc:7461): Gtk-WARNING **: 21:56:16.844: Theme parsing error: gtk.css:1418:23: 'font-feature-settings' is not a valid property name

(keepassxc:7461): Gtk-WARNING **: 21:56:16.849: Theme parsing error: gtk.css:3295:25: 'font-feature-settings' is not a valid property name

(keepassxc:7461): Gtk-WARNING **: 21:56:16.850: Theme parsing error: gtk.css:3757:23: 'font-feature-settings' is not a valid property name
Gtk-Message: 21:56:16.873: Failed to load module "canberra-gtk-module"
Gtk-Message: 21:56:16.875: Failed to load module "canberra-gtk-module"
Qt: Session management error: Could not open network socket
Fontconfig warning: FcPattern object weight does not accept value [40 200)
[1]    7461 segmentation fault  keepassxc
```

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.6.6
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: Ubuntu 20.04.1
Desktop Env: Gnome
Windowing System: X11/Wayland

**Comment by droidmonkey** [comment]
https://github.com/keepassxreboot/keepassxc/issues/6329#issuecomment-805092856
