### ISSUE TITLE
Drag-and-dropping entries between databases doesn't work on sway

### ISSUE THREAD

**Issue by UnkindPartition** [keepassxreboot/keepassxc#7409]
## Overview

I think I used to be able to drag-and-drop entries between databases opened in keepassxc tabs. That doesn't appear to work anymore.

Might be related to the window manager (sway); unfortunately I can't check with another WM right now.

## Steps to Reproduce

1. Open two different databases
2. Select an entry and drag it on top of the other database's tab

## Expected Behavior

The context should switch to the other database, and I should be able to copy or move the entry

## Actual Behavior

Nothing happens.

## Context

```
KeePassXC - Version 2.6.6
Revision: 9c108b9

Qt 5.15.2
Debugging mode is disabled.

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 5.16.8-arch1-1

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- libgcrypt 1.9.4-unknown
```

Operating System: Arch Linux
Desktop Env: Sway (sway-hidpi-git r6811.b223f702-1)
Windowing System: Wayland

**Comment by droidmonkey** [comment]
https://github.com/keepassxreboot/keepassxc/issues/3930#issuecomment-558188575
