### ISSUE TITLE
Show content of referenced notes

### ISSUE THREAD

**Issue by profhccaesar** [keepassxreboot/keepassxc#7410]
## Summary
It is possible to reference in the notes of an item the notes of another item using "{REF:N@I:...}".
This works very well with one drawback: the content of the referenced notes are never shown! The only possibility to get the content of the referenced note is to put it into the clipboard ("Copy attribute" -> "Notes").
![image](https://user-images.githubusercontent.com/17450059/153849477-bad3ef58-b84f-4497-aa93-5e8515e98f68.png)

It would be nice if the referenced notes may be shown within the application, e. g.:

- Resolving the references in the preview, see image above
- Or show a popup with the referenced notes when pointing to a refence with the mouse.

### Actual appearance of the preview area:
![image](https://user-images.githubusercontent.com/17450059/153846330-61b75e47-de69-4cff-8c16-572ea77bfd16.png)
### Proposed appearance of the preview area:
![image](https://user-images.githubusercontent.com/17450059/153846562-65c5deb8-c140-4871-8174-89d747aa177a.png)
### Alternative proposal:
![image](https://user-images.githubusercontent.com/17450059/153848661-b8c1bcb6-6a01-4d38-bef9-feefecfed69d.png)

## Context
Images above are pulled from KeepassXC 2.6.6 (Linux)
Notes of items contains often identical usage explanations e. g. It is cumbersome to each time copy the notes into an external editor to read it.

**Comment by adudek16** [comment]
I agree. The use of the reference is not helpful if you cannot locate what is being referenced.
