### ISSUE TITLE
Auto-type in macOS Monterey 12.2 does not work when recording indicator is on

### ISSUE THREAD

**Issue by teocasse** [keepassxreboot/keepassxc#7418]
## Overview
When the recording indicator in macOS Monterey 12.2 is active ("orange dot" in menu bar), auto-type does not work correctly anymore. No matter which window is currently active, auto-type will always fail with the message "Couldn't find an entry that matches the window title: StatusIndicator". It seems that when the recording indicator is active, "StatusIndicator" is erroneously identified as the window title. This makes impossible to use auto-type when the recording indicator is active (for instance during Zoom meetings).

## Steps to Reproduce
1. Start any app that uses the microphone.
2. Verify that the orange status indicator is active in the menu bar.
3. Invoke auto-type from any window. 

## Expected Behavior
Auto-type works correctly independently from the recording indicator status.

## Actual Behavior
Auto-type will fail with the message "Couldn't find an entry that matches the window title: StatusIndicator".

## Context
KeePassXC - 2.6.6
Operating System: macOS Monterey 12.2

**Comment by droidmonkey** [comment]
Seems like this should be filed with macos. Their status indicator program is erroneously changing the internal window title of every program that has focus.

**Comment by droidmonkey** [comment]
Here is the code that pulls the active window title:  
 ​    ​CFStringRef​ titleRef = ​static_cast​<​CFStringRef​>(::​CFDictionaryGetValue​(window, ​kCGWindowName​));

**Comment by teocasse** [comment]
thanks for the quick reply. A bug in monterey is the most likely explanation... unless (shooting in the dark here) the kCGWindowName API is deprecated in monterey and one is supposed to pull the active window title in a different way?

If this should be filed with apple, do you know how to do it? 

is there any solution I can adopt in the short term, or will auto-type not work during zoom meetings until this is fixed?

**Comment by droidmonkey** [comment]
You can use entry level Auto-Type (Cmd+Shift+V) when the desired entry is selected. This will type into the previously active window regardless of its title.

**Comment by cegeskov-ibm** [comment]
I can confirm (MacOS 12.2.1). I see the exact same issue both when in a call/huddle in Slack and when in a Webex meeting. Both trigger the "orange dot" microphone status.
Not sure I have colleagues still on Monterey 12.1 using KeePassXC to verify it still works there.
I would not know what or how to report the issue to Apple.
Autotype is a life-changing feature and is dearly missed! We use calls as a virtual office, so I am in a call/meeting most of the day when working from home. When having myriads of server passwords arranged in a tab hierarchy, entry-level is a workaround but a lot less attractive than full-blown autotype.

**Comment by droidmonkey** [comment]
@phoerious can we submit an escalated ticket still?

**Comment by phoerious** [comment]
Sure

**Comment by tuxmanu** [comment]
same on my side. 
12.2.1 when using MS teams...
keepassxc 2.6.6

**Comment by RickPennings** [comment]
The problem looks to be related to usage of the microphone or camera, rather than the target application. I was using Discord to have a videoconference, while I tried to auto-type in Safari. It didn't work due to the indicator. After hanging up, auto-type in Safari worked like a charm.

**Comment by teocasse** [comment]
Yes, that is already clear from the message regarding the window title. If the status indicator is active, no matter the application but auto type will fail.

**Comment by nof8** [comment]
Got the same issue, MacOS 12.2 (21D49)
Thanks for pointing out that it's due to the camera/mic on, I couldn't understand why it happens.

**Comment by fabiankle** [comment]
Thx for the infos! Happening to me while Webex is open.

**Comment by phoerious** [comment]
I can confirm that Auto-Type cannot match windows when the microphone is activated. Starting the FaceTime camera alone isn't enough, but joining a Discord voice channel is. In 2.7, this is less of an issue, because of the improved Auto-Type dialogue, but it's still an issue.

It's strange, though, that when I go to entry settings / Auto-Type, I still get correct window title suggestions when I want to add a new association.

EDIT: Actually, it's already enough to open the "Input" tab in the system audio preferences.
