### ISSUE TITLE
no auto-type functionality in flatpak

### ISSUE THREAD

**Issue by g33kdad** [keepassxreboot/keepassxc#7419]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

Auto-type is not present/not working

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. install flatpak
2. 
3. 

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
right-click on an entry, context menu provides an auto-type option or ctrl-shift-v performs the auto-type function

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
context menu has option "perform auto-type sequence >" but option does not expand; ctrl-shift-v has no effect

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.6.6
Revision: 9c108b9

text of debug info from Help --> About:
KeePassXC - Version 2.6.6
Revision: 9c108b9
Distribution: Flatpak

Qt 5.15.3
Debugging mode is disabled.

Operating system: KDE Flatpak runtime
CPU architecture: x86_64
Kernel: linux 5.16.8-200.fc35.x86_64

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
- libgcrypt 1.8.8

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux (Fedora SilverBlue 35)
Desktop Env: Gnome
Windowing System: Wayland

**Comment by ekasprzak** [comment]
It's somehow related to flatpak + wayland combo as it just works on Ubuntu 20.04 on Xorg (using KeePassXC flatpak)

**Comment by droidmonkey** [comment]
Auto-Type is not available for wayland

**Comment by ekasprzak** [comment]
#2281 some further discussion here

**Comment by g33kdad** [comment]
Thanks.

M
