### ISSUE TITLE
U+FEFF is prepended to the generated password.

### ISSUE THREAD

**Issue by ghost** [keepassxreboot/keepassxc#7420]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
Copying and pasting a password will contain invisible characters.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. I select the icon at the top to open the password generation screen.
2. Generates a 128-digit password, including extended ASCII.
3. Click on the clipboard icon and copy the password.
4. When I paste the copied password, U+FEFF is appended to the beginning.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
U+FEFF is not included

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Contains superfluous invisible characters

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.66
Revision: 386b79a

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS 10.15/darwin 19.6.0

**Comment by droidmonkey** [comment]
That looks like a UTF-16 BOM (byte order mark), where are you pasting the password? Does this happen if you do not use extended ascii?

**Comment by ghost** [comment]
> where are you pasting the password?

I pasted it into 1Password and the following websites.
https://www.marbacka.net/msearch/tool.php

This problem does not occur on Linux.
I'll look into the extended ascii when I have time.

**Comment by droidmonkey** [comment]
This is most likely not KeePassXC but a special clipboard application you have on macos. Could also be Mac trying to be smart and adding BOM to extended ascii text in clipboard.

**Comment by ghost** [comment]
I just investigated and found out that this problem occurs even if the file does not contain extended ASCII.
I'm not using any special clipboard application.

**Comment by phoerious** [comment]
I tried to reproduce the issue on macOS, but was unable to. Perhaps the target application doesn't understand UTF-16 properly.
