### ISSUE TITLE
Add "History Report" to reports page

### ISSUE THREAD

**Issue by tunbridgep** [keepassxreboot/keepassxc#7423]
## Summary
I would like a report added to the reports page which simply lists the entire history of the database in chronological order - every entry that was added, updated, etc.

## Context
I keep my database synchronised across multiple devices, and sometimes I will get a sync conflict if something hasn't synced for a long time. Being able to look at their database histories side by side would help me diagnose the problem when a simple merge won't work. It also helps give some visualisation over what changed recently, for the times when I go "hey my database file is synced. I wonder what I changed"

**Comment by droidmonkey** [comment]
#7176. I want this too!
