### ISSUE TITLE
Incorrect Generated Key extension: '.keyx;'

### ISSUE THREAD

**Issue by ahchienong** [keepassxreboot/keepassxc#7425]
Database > Database Security > Database Credentials > Change Key File > Generate

![image](https://user-images.githubusercontent.com/3302457/154650941-8ffcf7cb-d4e2-4e00-9a89-480044a9403e.png)

**Comment by droidmonkey** [comment]
That's the new key format from keepass

**Comment by droidmonkey** [comment]
This is fixed already for next version https://github.com/keepassxreboot/keepassxc/pull/7010

**Comment by ahchienong** [comment]
> This is fixed already for next version #7010

Grad to know that it's resolved in next version.
