### ISSUE TITLE
Auto-Type into RDP session

### ISSUE THREAD

**Issue by modernuser2017** [keepassxreboot/keepassxc#7428]
Hi there,

I'd like to suggest a new feature for KeePassXC. For my daily work Auto-Type is a very important feature. Unfortunately it's not possible to perform Auto-Type into an RDP session when you only have KeePassXC open on your host machine that initiated the RDP session.

Thanks in advance.

**Comment by droidmonkey** [comment]
This is implemented for the next major version

**Comment by sebma** [comment]
@droidmonkey Hi Jonathan, which version ? I'm using v2.7.4 and I cannot find the RDP integration options. 
Can you help me find them ?
Or did you mean it will be in the next v3 version ?

**Comment by droidmonkey** [comment]
If you are on windows then you cab use the {MODE=VIRTUAL} yah in your Auto-Type sequences for rdp or use the context menu in the Auto-Type selection dialog and select virtual keyboard.

**Comment by sebma** [comment]
@droidmonkey Thanks.

**Comment by modernuser2017** [comment]
@droidmonkey Thanks for that tip. I just tried it out. But unfortunately the Auto-Type with {MODE=VIRTUAL} didn't type the password correctly. For example it typed the digit 2 where there should be a " sign. Aditionally it omitted the last sign of the password. Do you have any idea why this happens? Can I do anything to fix that?

**Comment by droidmonkey** [comment]
I haven't a clue, typically rdp works fine without any special tricks. It might fail if you have two different keyboard layouts between the host machine and the remote one.

**Comment by modernuser2017** [comment]
Ok, the keyboard layouts are the same on host and remote machine. Interestingly it works with a 3rd-Party-Application (RoyalTS) but not with the direct RDP connection.
