### ISSUE TITLE
OpenSSH for Windows SSH Agent integration not working

### ISSUE THREAD

**Issue by Romern** [keepassxreboot/keepassxc#7429]
## Overview
KeepassXC does not add my SSH keys to the ssh agent, automatically nor manually.
When opening my database "Agent protocol error." is shown in red.
In the SSH Agent settings "SSH Agent connection is working" is shown in green.
The SSH Keys in the database do show up in my agent on my Linux machine when configured there.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Launch KeepassXC and unlock database
2. Run ``ssh-add -l``

## Expected Behavior
My SSH keys should be shown and no "Agent protocol error." in KeepassXC.

## Actual Behavior
No SSH keys are shown and "Agent protocol error." is shown in KeepassXC.

## Context

OpenSSH Authentication Agent is running and ``ssh-add -l`` is working correctly
"Use OpenSSH for Windows instead of Pageant" is ticked
OpenSSH_8.1p1 for Windows
KeePassXC - Version 2.6.6
Revision: 9c108b9

Qt 5.15.2
Debugging mode is disabled.

Operating system: Windows 10 Version 2009 **(this is wrong, i am using Windows 11)**
CPU architecture: x86_64
Kernel: winnt 10.0.22000

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
- libgcrypt 1.9.2-unknown

**Comment by hifi** [comment]
Do you have any constraints set for your keys like time or require confirmation? Windows agents don't yet support that and just refuse them.

**Comment by Romern** [comment]
Ah, that fixed it for now as a workaround, thanks @hifi . I simply had to 
1. Right click on the SSH key -> Edit Entry
2. SSH-Agent ->Untick Require user confirmation when this key is used.

Now I could either manually add the key to the agent, or restart keepassxc and the key was automatically added.
It would be good if in the future "Agent protocol error." would be more expressive, or to show a warning in the SSH Agent settings.

**Comment by hifi** [comment]
Indeed, we haven't yet decided how to make it more obvious and possibly add a setting to ignore the constraints on Windows while also leaving the possibility of Microsoft or PuTTy fixing it.
