### ISSUE TITLE
Menubar icon is squashed on the inactive screen

### ISSUE THREAD

**Issue by stffffn** [keepassxreboot/keepassxc#7431]
## Overview
The macOS menubar icon is squashed on the inactive screen.

<img width="250" alt="menubaricon" src="https://user-images.githubusercontent.com/16480903/154722051-dbe7ef7f-6f24-4019-bbc8-191faede392d.png">

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Connect your Macbook to an external monitor
2. The icon appears squashed on the inactive screen

It doesn't matter if KeePassXC is already running or if you start it after the monitor is already connected.

## Expected Behavior
The menubar icon is displayed the same, regardless of the screen state.

## Actual Behavior
The icon is displayed squashed on the inactive screen.

## Context
Tested on a Macbook Air M1 with an external monitor.  
Unfortunately, I don't know if this also happens on non-M1 Macbooks or M1-based Macs without an internal screen and at least two external monitors attached.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.6.6
Revision: 386b79a

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS 12.1 (21C52)

**Comment by droidmonkey** [comment]
known bug in Qt, thank you
