### ISSUE TITLE
Cannot open ssh://server-ip in Elementary OS 

### ISSUE THREAD

**Issue by Acsigen** [keepassxreboot/keepassxc#7433]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Set entry URL to: ssh://server.example.com
2. Click Open URL

## Expected Behavior
[NOTE]: # 
Open a terminal window and access the remote server through SSH.

## Actual Behavior
[NOTE]: #
I get an error message "No installed apps can open x-scheme-handler/ssh"

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.6.6
Revision: 9c108b9
Distribution: Flatpak

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux - Elementary OS
Desktop Env: Pantheon
Windowing System: X11
![image](https://user-images.githubusercontent.com/13287878/154817819-fe843ecc-922d-4813-b1f7-5dd6fb191bd5.png)

**Comment by droidmonkey** [comment]
You need to register the ssh protocol to open your command line. This is done on your os.
