### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by SynapseScribe** [keepassxreboot/keepassxc#7434]
It has been an year since last release, so I was wondering whether it is still actively developed and we can get a fresh new release.

**Comment by droidmonkey** [comment]
Your can see from our prs we are hard at work.

**Comment by SynapseScribe** [comment]
But can we get a new release? They should be more often, rather then adding buch of features prone to bugs in one shot

**Comment by droidmonkey** [comment]
You can try it out now at https://snapshot.keepassxc.org. We are two PRs away from release.

**Comment by SynapseScribe** [comment]
That's great news. I really love this app and wouldn't want it to lose momentum. Thank you!
