### ISSUE TITLE
Show password strength indicator in EditForm and General Tab

### ISSUE THREAD

**Issue by weilharter** [keepassxreboot/keepassxc#7437]
## Summary
A password strength indicator in EditEntryForm and below the Password (General tab) would be a cool feature

### Example from Strongbox(MacOS Keepass Client)

Edit View:

<img width="1149" alt="editview" src="https://user-images.githubusercontent.com/2322962/154971790-4fe17838-1e4e-424a-98c5-35f41e3bb9e4.png">

General Tab/Preview Pane:

<img width="1248" alt="generalinfo" src="https://user-images.githubusercontent.com/2322962/154971798-a0fe7f94-c98b-4ac7-a153-89cf718fb388.png">

**Comment by droidmonkey** [comment]
You can show the password strength as a column in the entry view right now. It should be elsewhere, agree.

**Comment by schlimmchen** [comment]
@droidmonkey Where exactly? Do you mean the database health check table?

**Comment by droidmonkey** [comment]
No in the main entry table. Right click the header and you can add it as a column. You need version 2.6.6

**Comment by schlimmchen** [comment]
It seems this was introduced *after* 2.6.6. I found that column immediately after firing up the current development snapshot AppImage.

@droidmonkey Any Feedback to the following mockups? @weilharter What did you have in mind (the context of your example screenshot of Strongbox is unclear)?

Copying the "entropy bar" from the password generator to the entry edit view:
![entry_edit_view](https://user-images.githubusercontent.com/3578416/154962600-017b56bb-af08-445e-8caf-d68b7beae7a0.png)

Adding the password strength indicator to the edit preview pane (where it is always visible):
![edit_preview_v1](https://user-images.githubusercontent.com/3578416/154962603-c3dd5908-cda9-453b-8aba-699caaefee6f.png)

Adding the password strength indicator with textual value in a new line of the preview pane (where it is always visible):
![edit_preview_v2](https://user-images.githubusercontent.com/3578416/154962604-1df83401-9479-4893-954d-2aa8c4012cd2.png)

**Comment by weilharter** [comment]
> What did you have in mind (the context of your example screenshot of Strongbox is unclear)?

Sorry for not checking the latest dev build. The entropy bar in Edit View looks perfect! That's exactly what I meant.

My Screenshot was showing the General Tab/Preview Pane-Equivalent of Strongbox Keepass Client. I just updated the issue with better Screenshots to show more context.

**Comment by michaelk83** [comment]
@schlimmchen I like the 1st version of the preview pane better. The color is enough to understand the strength without adding extra clutter. You can place the strength text in a tooltip of the strength indicator, along with the entropy. And same tooltip for the strength indicator in the table.

**Comment by schlimmchen** [comment]
> Sorry for not checking the latest dev build. The entropy bar in Edit View looks perfect! That's exactly what I meant.

Don't be sorry, what you see is just a mockup! The entropy bar is currently only used in the password generator widget, not in the entry edit view. What I found in the latest dev build is just the little colored square indicator in the list of entries for a group when enabling the respective column as droidmonkey suggested.

Thanks for updating the screenshots, those help.

**Comment by droidmonkey** [comment]
Adding the strength indicator to the PasswordEditWidget would be a nice addition that could be toggled internally based on use (hidden by default). Adding the entropy is unnecessary, it really doesn't mean much, but placing the "Password quality: Excellent" text to the far right of the quality color bar would be nice.
