### ISSUE TITLE
Can't see group structure on macOS

### ISSUE THREAD

**Issue by Benzinbruder** [keepassxreboot/keepassxc#7438]
## Overview
On my Mac I can't seem to open kdbx databases with a group structure.
On PC I use KeePassXC as well and I use a strctured file for my passwords.
When I open the same file on my Mac, the file is flattened.

At first I thought I was a victim of the problem [described in issue 3045](https://github.com/keepassxreboot/keepassxc/issues/3045), i.e. that group structure is not synced when syncing a .kdbx file with KeeShare. I recently synced my file between my Windows machine and my Mac and I flattened the file.

After manually re-structuring my entries and groups on my PC, I manually copied the file from my Windows maching to my Mac to test it there. The file still opens flat, i.e. without my group structure. This also happened after uninstalling and reinstalling KeePassXC on my Mac. 

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Edit and save a kdbx file on KeePassXC on your PC with a group structure. 
2. Manually transfer the kdbx file to a Mac.
3. Open the kdbx file with KeePassXC on the Mac.

## Expected Behavior
The group structure in the kdbx file should remain whether the file is opened with KeePassXC on the PC or on the Mac.

## Actual Behavior
Opening a kdbx file on a Mac seems to flatten the group structure in the kdbx file.
Syncing the file also flattens the structure when opening it on the PC.

## Context
I don't think further context is necessary.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.6
Revision: 386b79a

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 11 / macOS Monterey 12.1

**Comment by droidmonkey** [comment]
Are you saying the group panel on the left is gone or all the entries are dumped into the root group?

**Comment by Benzinbruder** [comment]
All entries seem to be dumped into the root group.

The group panel only shows one group / folder, which is named like the kdbx file.

**Comment by droidmonkey** [comment]
Did you disable the keeshare share on the group? Recommend creating a new kdbx file and drag and drop the entries from the old to the new.

**Comment by Benzinbruder** [comment]
Tried disabling KeeShare, but it had no effect.

In the meantime I have also started a new kdbx vom scratch on my PC and added groups for testing.
It seems as if that file can be read on my Mac without issues -> so the problem is obviously my (old) kdbx file.

Obviously I should have tried that before my initial post, as it now seems clear that the bug can't be reproduced.
Please excuse.


Are you suggesting that I start a new file on my Mac and replicate the group structure from my original file and then drag and drop the entries from the old file?

**Comment by droidmonkey** [comment]
No just use your new kdbx. This is definitely related to the same keeshare flattening issue. You can use kdbx file across all machines and it will be the same.
