### ISSUE TITLE
TouchID prompt not appearing on database unlock screen

### ISSUE THREAD

**Issue by orpheuslummis** [keepassxreboot/keepassxc#7440]
On the "Unlock KeepassXC Database" screen, the TouchID prompt doesn't appear.

[NOTE]:
KeePassXC - Version 2.6.6
Revision: 386b79a
macos 12.2.1 (latest as of February 2022)

**Comment by droidmonkey** [comment]
Feature is overhauled in 2.7.0

**Comment by orpheuslummis** [comment]
Amazing. Thank you

**Comment by tyleroconnell** [comment]
@droidmonkey for some reason I don't see a TouchID prompt (or a way to re-enable it in Settings) for Version 2.7.0 either (Revision: d7a9ef4)

**Comment by droidmonkey** [comment]
It's enabled by default if you have the required hardware. Once you unlock your database the first time, when you lock it again you'll see "unlock database" which will trigger the TouchID prompt. 

See the user guide for more info

**Comment by tyleroconnell** [comment]
Thanks for the quick reply and all of your work on the project @droidmonkey!

For anyone else stumbling on this issue, it seems version 2.7.0 had an issue recognizing TouchID hardware, at least for my laptop, that was fixed by 2.7.1 (Revision: 5916a8f).
