### ISSUE TITLE
[MSVC][std:c++latest] keepassxc failed to build with /std:c++latest on MSVC

### ISSUE THREAD

**Issue by QuellaZhang** [keepassxreboot/keepassxc#7443]
Hi All,

The MSVC team recently added keepassxc as part of RWC testing. And we found some errors when building keepassxc with '/std:c++latest'. We added `/D_HAS_DEPRECATED_RESULT_OF=1 /D_SILENCE_CXX17_RESULT_OF_DEPRECATION_WARNING` as workaround since they have been deprecated. Could you please help look at this issue? Thanks in advance.

**Repro steps:**

1. open VS2022 x64 Tools command
2. git clone https://github.com/microsoft/vcpkg.git F:\gitP\Microsoft\vcpkg
3. cd F:\gitP\Microsoft\vcpkg
4. bootstrap-vcpkg.bat
5. vcpkg.exe install --recurse botan zlib minizip libqrencode readline --triplet x64-windows --clean-after-build
6. git clone https://github.com/keepassxreboot/keepassxc.git F:\gitP\keepassxreboot\keepassxc
7. mkdir F:\gitP\keepassxreboot\keepassxc\build_amd64
8. cd F:\gitP\keepassxreboot\keepassxc\build_amd64 
9. set PATH=F:\tools\qt5\qt\5_15_2\msvc2019_64\bin;%PATH%
10. gem install asciidoctor
11. cmake -G "Visual Studio 16 2019" -A x64 -DCMAKE_SYSTEM_VERSION=10.0.18362.0 -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=F:\gitP\Microsoft\vcpkg\scripts\buildsystems\vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows ..
12. set _CL_= /std:c++latest
13. msbuild /m /p:Platform=x64 /p:Configuration=Release KeePassXC.sln /t:Rebuild

**Build log:** [build.log](https://github.com/keepassxreboot/keepassxc/files/8107724/build.log)

**Error info:**
F:\gitP\keepassxreboot\keepassxc\src\core/AsyncTask.h(37,19): error C2039: 'result_of': is not a member of 'std' 
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\include\future(37): message : see declaration of 'std' 
F:\gitP\keepassxreboot\keepassxc\src\core/AsyncTask.h(37,46): error C2653: 'result_of': is not a class or namespace name 
F:\gitP\keepassxreboot\keepassxc\src\core/AsyncTask.h(38,1): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
F:\gitP\keepassxreboot\keepassxc\src\core/AsyncTask.h(38,5): error C2061: syntax error: identifier 'waitForFuture'

**Comment by droidmonkey** [comment]
Why do you do step 13? We set the standard to C++17 in cmake.

**Comment by QuellaZhang** [comment]
> Why do you do step 13? We set the standard to C++17 in cmake.

Step 13 is just msbuild command. Did you mean step 12? Yes, `/std:c++latest` was added on our side, we did this to use this project to detect more compiler errors. We also test the `/permissive-` option.

**Comment by droidmonkey** [comment]
Yes I meant step 12, cross eyed. We don't support the latest C++ standard which is why you get those errors. You'll have to stick to c++17 for now.

**Comment by QuellaZhang** [comment]
Thanks for your reminder. Currently, we have added some workarounds for this issue.

If this project exposes more errors, we will disable it under /std:c++latest mode at some point.
