### ISSUE TITLE
Perform auto-type sends credential to "stay always on top" window instead to expected

### ISSUE THREAD

**Issue by de-jcup** [keepassxreboot/keepassxc#7444]
## Overview
When using `Perform auto-type` action on a selected entry, the former focused window does not get the credential data but instead a window which has been marked with "always stay on top". 

## Steps to Reproduce
1. Open a `Terminal`on a Linux Desktop (in my case Linux mint cinnamon) + mark it's window as "stay always on top" via right mouse button click on title + enabling checkbox
2. Open a text editor - e.g. `TextMate` - so it is focused
3. Switch to `KeePassXC`, select an entry containing credentials and press right mouse button and select `Perform auto-type`

## Expected Behavior
The former selected application (in my example `TextMate` shall receive the credentials)

## Actual Behavior
The credential output is sent to the "stay on top" application (in my example `Terminal`)

## Context
- OS Linux Mint 20.3 Cinnamon
- Cinnamon Version: 5.2.7
- Used default KeePassXC from origin apt sources

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.4.3
Revision: 5d6ef0c

Qt 5.12.8
Debugging mode is disabled.

Operating system: Linux Mint 20.3
CPU architecture: x86_64
Kernel: linux 5.4.0-100-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (only unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.5

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: Cinnamon
Windowing System: X11

**Comment by droidmonkey** [comment]
This is fixed in develop branch. The desired window is now explicitly focused instead of relying on minimize behavior. You are also using a very old version of KeePassXC.

**Comment by de-jcup** [comment]
> This is fixed in develop branch. The desired window is now explicitly focused instead of relying on minimize behavior. You are also using a very old version of KeePassXC.

Thank you very much. Yes indeed i am using a very old version... but unfortunately this is the version, which is coming from the Linux Mint update package manager...
