### ISSUE TITLE
Multiple password/pin/code fields with custom names 

### ISSUE THREAD

**Issue by myootnt** [keepassxreboot/keepassxc#7448]
## Summary
Allow adding additional password/PIN/code fields per entry with custom name and perhaps an option to include them on the context menu for copying.

## Examples
                                                               show on context menu
Password:      [***************                 ] X
PIN (Nano):    [*****                               ] X
Authenticator: [*************************   ]

## Context

I was setting up some logins at various sites today with TFA/MFA and ran into instances where there are multiple entries per login. Typically I just put those and other security-related bits such as recovery codes and security question answers in the Notes space and add a bunch of blank lines on top so it doesn't show in preview or in Edit Entry pane without scrolling (that's a different suggestion/issue.)
In my example above, the site has a password, I have a security key registered that is protected by a PIN and it also has Google Authenticator and the site very graciously gave me a setup code along with QR code. The code is worth securely saving but not worth taking up space on a context menu.

**Comment by droidmonkey** [comment]
Covered by #863. You can use advanced attributes today and plumb those up into the browser extension and Auto-Type.
