### ISSUE TITLE
REF only refers to values in current DB

### ISSUE THREAD

**Issue by spi43984** [keepassxreboot/keepassxc#7449]
## Overview
REF for username/password in other (but also already opened) DB does not work

## Steps to Reproduce
1. clone entry, create in clone REF: for username and password for original entry in same DB 
2. clone's username and password refer to correct values
3. move the clone to another also opened db
4. clone's username and password don't refer to correct values anymore, they're just empty

## Expected Behavior
For opened DB I'd expect the UUID used in REF to be unique and usable across different DBs

## Actual Behavior
REF to entries in different DB don't provide correct values

## Context
I open a master DB. In it a slave DB is additionally opened vi the Group AutoOpen. So if I open the master DB, the other one is "daisy chained". I'd like to use REF for entries not only in one DB but across different DBs.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.6.6
Revision: 9c108b9

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: Gnome
Windowing System: X11

**Comment by phoerious** [comment]
You have to create a clone without references for that to work. Individual databases don't know anything of each other and that's not going to change. Cross-database referencing would only work with databases that are opened within the same app in parallel and would stop working as soon as you close one of them (and there is no way to distinguish between temporarily and permanently broken UUIDs, so consistency checks are impossible).

**Comment by spi43984** [comment]
> ... Cross-database referencing would only work with databases that are opened within the same app in parallel and would stop working as soon as you close one of them ...

Right, that's why I wrote that the databeses are daisy chained and opened in the same app in parallel.
