### ISSUE TITLE
Generate PWs - text fields reversed in snapshot rev d10c5a4

### ISSUE THREAD

**Issue by JohnLGalt** [keepassxreboot/keepassxc#7451]
## Overview
When creating a new entry, using CTRL + G to open PW generator, `Also choose from` and `Do not include` text entry boxes are reversed. Entering text into `Also choose from` will prevent those chars from being used, and vice versa.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Create new entry
2. Click PW gen button / CTRL + G to open Generate Password dialog
3. Add "abcd" to `Do not include` and remove all other options, all subsequently generated passwords are comprised of "abcd"
4. Add "abcd" to `Also choose from` and all subsequently generated passwords will never include "abcd"
 

## Expected Behavior
Each text entry fields should follow it's respective label.

## Actual Behavior
The Text entry fields are reversed versus the labels.

## Context
Tried with both existing 400+ entry database and brand new, clean, _ad-hoc_ created **test** database. Reproducible 100% of the time.

## Debug info 
KeePassXC - Version 2.7.0-snapshot
Build Type: Snapshot
Revision: d10c5a4

Qt 5.15.2
Debugging mode is disabled.

Operating system: Windows 10 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.22000

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey

Cryptographic libraries:
- Botan 2.18.2

Portable version from https://snapshot.keepassxc.org/build-206937/

## System Info
Operating System: Windows 11 21Ha Build 22000.527 fully patched as of today.

## Supplemental info
Please let me know if I should try anything else. I typically grab the latest snapshot, and then extract into a directory on my data drive and use it directly from there. Today, I grabbed last week's build and deleted everything in the existing directory, and then extracted the build into the same directory as always.

**Comment by JohnLGalt** [comment]
Problem still exists in latest snapshot.

KeePassXC - Version 2.7.0-snapshot
Build Type: Snapshot
Revision: 4f07103

Qt 5.15.2
Debugging mode is disabled.

Operating system: Windows 10 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.22000

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey

Cryptographic libraries:
- Botan 2.18.2

**Comment by droidmonkey** [comment]
Yah why would it change we haven't even posted a pr for the fix?

**Comment by JohnLGalt** [comment]
My bad. Saw the new release and thought it might have been fixed.

**Comment by droidmonkey** [comment]
Fixed in f3b0fe46b4dc4438488fc3acf790a7b0123a2196
