### ISSUE TITLE
File chooser does not sort columns

### ISSUE THREAD

**Issue by martinpelikan** [keepassxreboot/keepassxc#7452]
## Overview
File chooser does not sort columns

## Steps to Reproduce
1. File -> Open Database (or Edit Entry -> Advanced -> Add Attachment)
2. Click any column (eg. date modified)

## Expected Behavior
Files should be sorted by their respective column

## Actual Behavior
UI does not register click, does not sort files

## Context
Possibly an issue of some QT default/fallback when not using a DE or system theme? Running keepass with `QT_QPA_PLATFORMTHEME=gtk3` gives me a different file chooser that supports sorting.

KeePassXC - Version 2.6.6
Revision: 9c108b9

Qt 5.15.2
Debugging mode is disabled.

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 5.16.10-arch1-1

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- libgcrypt 1.9.4-unknown

Windowing System: X11 + i3

**Comment by droidmonkey** [comment]
This isn't our bug, we don't manage the file picker.
