### ISSUE TITLE
Failure to create new Key for Database under Windows

### ISSUE THREAD

**Issue by PeetThesing** [keepassxreboot/keepassxc#7454]
While creating a new database it is not possible to create a new Key when I use Windows. When I click creating a Key, a window pops up to search a Key. 
I want to use password + key as security measures. 
I had this Problem on two different computers.

I did the same using Linux, and could create a new key without a problem. 

KeePassXC - 2.6.6

Operating System: Windows

**Comment by phoerious** [comment]
You mean a key file? The window that pops up is not for searching an existing key file, but for selecting where you want to store the newly generated one.
