### ISSUE TITLE
Multiuser yubikey problems with possible dataloss

### ISSUE THREAD

**Issue by xmeadow** [keepassxreboot/keepassxc#7455]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
Hello all,
following issue: we use KeepassXC as sysadmins and have a shared kdbx file in a SMB share. But with the introduction of Yubikeys we have a huge problem. When someone saves the kdbx-file, everyone who just opened the file has to save this change. If someone doesn't or waits too long the file will not be written. The mean thing is that the person who makes the change only sees it when he reopens the file. Before that the change is in the cache. This way we seem to have lost some access data over the last half year. We do have the backup function active - but that only helped us to a limited extent.
Best regards

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Two Clients open a yubikey enabled kdbx-file.
2. One of them (A) makes a change, the other (B) will be forced to "sign" the change.
3. If B doesn't apply the yubikey, the change is gone forever.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Multiple User should be able to work on a keefile.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Unexpected behaviour, lost changes appear.

## Context
Without yubikey enabled this behaviour didn't appear. We got all 3 factors for protection enabled (password, keyfile and yubikey)

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.6.6
Revision: 9c108b9

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows

**Comment by phoerious** [comment]
The Yubikey doesn't sign anything, it just derives a key from a challenge and a secret. If party A modifies the database and writes the changes to a shared drive, it should prompt a simple reload on party B's side. No data should be lost. Do you have your keys configured to require user interaction? In that case, B's database should be marked as stale, because it cannot be reloaded automatically. This state is indicated by the database contents being marked as unsaved.

**Comment by droidmonkey** [comment]
All yubikeys need the same secret. Otherwise you run into this issue https://github.com/keepassxreboot/keepassxc/issues/5290

Plus you'll constantly be unable to open someone else's database.

**Comment by xmeadow** [comment]
> Do you have your keys configured to require user interaction?

Yes thats the case exactly the behaviour. I didn't know that you can configure the keys that they dont need interaction. I guess its not handled by KeepassXC.

> All yubikeys need the same secret.

They have the same secrets.

**Comment by droidmonkey** [comment]
We handle user interaction, although I will need to test that the banner shows correctly on auto reload.

**Comment by phoerious** [comment]
I recommend you re-configure the keys to not require user interaction. The HMAC-SHA1 mode is supposed to be used non-interactively. Requiring user interaction does nothing except being annoying.

**Comment by xmeadow** [comment]
> I recommend you re-configure the keys to not require user interaction. The HMAC-SHA1 mode is supposed to be used non-interactively. Requiring user interaction does nothing except being annoying.

Thanks a lot, that seems to do the trick!
