### ISSUE TITLE
Don't prevent getting help on custom auto-type sequences

### ISSUE THREAD

**Issue by h-h-h-h** [keepassxreboot/keepassxc#7457]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

The help button for auto-type sequences is disabled by default, though receiving help should always be possible, not only after you technically committed yourself to use a custom auto-type sequence.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Edit a database entry that you never set a custom auto-type sequence for.
2. Go to the "Auto-Type" tab.
3. Press `?` button to see if desired endeavor is possible. Only then would it be reasonable to enable the custom auto-type sequence.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

Pressing the button should show me the help document.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

Pressing the button does nothing, because it's disabled, as long as you don't choose the radio button "Use custom Auto-Type sequence" first.

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.6
Revision: 9c108b9

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows
~~Desktop Env: Gnome/KDE/XFCE/Mate/Cinnamon~~
~~Windowing System: X11/Wayland~~

**Comment by droidmonkey** [comment]
Help -> User Guide

**Comment by h-h-h-h** [comment]
That answer doesn't address the issue.
