### ISSUE TITLE
Add an Option on an entry to set the folder icon

### ISSUE THREAD

**Issue by xf-** [keepassxreboot/keepassxc#7465]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )

At the moment, I need to edit the folder (no problem) and select and icon of a long list of similar icons (especially with background). At the moment around 400 small icons, Would be nice to use the project pages icon to set the project folder icon.

## Solution
Add a context menu entry "Apply icon to current folder".

**Comment by droidmonkey** [comment]
We won't be implementing this, it is not a frequent function and would just clutter the context menu.
