### ISSUE TITLE
Add 2fa.directory support in reports

### ISSUE THREAD

**Issue by xf-** [keepassxreboot/keepassxc#7466]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
Similar to haveibeenpwned.com, there is a service that shows websites 2fa possibilities hosted on GitHub.

Service
https://2fa.directory/de/

Entries JSON
https://github.com/2factorauth/twofactorauth/tree/master/entries

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )

Show TOTP support and maybe also some other 2fa way in the analysis. Some only support SMS or other way like hardware token. Would increase the security per entire a lot.

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
More and more services add 2fa, but old accounts had no option at register time. Manuel checking takes a long time, and you won't look every login into your profile. Nice list of missed 2fa TOTP would be nice.

**Comment by droidmonkey** [comment]
#4096

**Comment by xf-** [comment]
Nice, I only searched in issues closed & open and found nothing
