### ISSUE TITLE
Unexpected return to folder view after deleting expired entry

### ISSUE THREAD

**Issue by whisdol** [keepassxreboot/keepassxc#7467]
## Overview
When cleaning up expired database entries that are presented to the user after unlock, the user returns to the root folder after deleting the first one.

## Steps to Reproduce
1. Unlock database
2. Observe "expired" entries that are shown by default 
3. Delete one of the expired entries

## Expected Behavior
KeePassXC shows the other expired entries

## Actual Behavior
KeePassXC shows the root folder

## Context
This bug only occurs with the expired list shown after unlock, but does not occur when manually viewing the "Expired" database tag from the list of tags on the left.

KeePassXC - Version 2.7.0-snapshot
Build Type: Snapshot
Revision: 4f07103
Operating System: Windows

**Comment by droidmonkey** [comment]
Ooh good catch

**Comment by droidmonkey** [comment]
This will be harder to fix than expected, basically we are faking a search when showing the expired entries, but there is no actual search text. When the entry is deleted it refreshes the group view which causes the expired entries fake search to disappear. I will have to actually implement this as a true search to make it work. I had wanted to extend the `is:expired` search by adding a number to the end to allow for "within # days" like `is:expired-#`

**Comment by droidmonkey** [comment]
This was fixed in 2.7.3
