### ISSUE TITLE
Inconsistent highlighting in Database Tags menu

### ISSUE THREAD

**Issue by whisdol** [keepassxreboot/keepassxc#7468]
## Overview
The new "Database Tags" are not always highlighted when selected: after unlock and after deleting an entry.

#  After unlock
## Steps to Reproduce
1. Unlock Database
2. Observe list of "Expired" entries

## Expected Behavior
"Expired" tag in left menu is highlighted

## Actual Behavior
"Expired" tag in left menu is not highlighted

# After deleting an entry
## Steps to Reproduce
1. Unlock Database
2. Navigate to "Expired" tag in left menu
3. Delete an entry from the list

## Expected Behavior
"Expired" tag in left menu is still highlighted

## Actual Behavior
"Expired" tag in left menu is not highlighted, although the list is still filtered to this tag/attribute via the search field

## Context
KeePassXC - Version 2.7.0-snapshot
Build Type: Snapshot
Revision: 4f07103
Operating System: Windows

**Comment by droidmonkey** [comment]
This is unfortunately a qt "bug". I tried very hard to keep the selected row highlighted even after interacting with other fields but it sometimes just seems to forget. I conceded with this just being a UI issue and the real role of the tags selection is to quickly set the search field and you operate from there afterwards.

**Comment by droidmonkey** [comment]
This was fixed
