### ISSUE TITLE
encrypt database with pkcs11 and multiple keys

### ISSUE THREAD

**Issue by hadmut** [keepassxreboot/keepassxc#7469]
Hi,

I've seen that keepassxc supports encrypting a part of the encryption key with a yubikey configured to use HMAC-SHA1 Challenge Reponse. 

Besides the fact, that SHA1 is in general (not necessarily here as well) considered weak and obsoleted, this is a rather limited approach. 

It would be nice, if keepassxc could also use pkcs11 libraries to encrypt/decrypt the database. That way, yubikeys configured differently, and even other crypto devices, probably including TPM, could be used. 

Furthermore, it should be possible to use more than one key, e.g. to decrypt a database with the TPM keys or pkcs11-accessible keys in Yubikeys on a given set of computers, e.g. two home machines and two notebooks or something like that. 

This could also make it possible to have admin password databases accessible by a team of admins, each with a personal key. 

regards

**Comment by droidmonkey** [comment]
Duplicate request
