### ISSUE TITLE
Feature Request: 512 Bit Keys & Serpent Encryption Algorithm Support

### ISSUE THREAD

**Issue by vargas-peniel** [keepassxreboot/keepassxc#747]
## Description

Be able to choose between 256/512 bit key sizes, and have available the Serpent Encryption Algorithm in addition to the currently available ones.
## Expected Behavior

Have the ability to use the above mentioned key sizes and algorithms, in addition to the currently implemented ones.

## Context

The purpose of this feature is to further increase the security options available to the user, and at the same time increase the overall program security.

**Comment by weslly** [comment]
Both 512bit and Serpent keys are currently unsupported by the original KDBX format specification so adding those would prevent users from opening their database on Keepass 2.x and other Keepass compatible apps.

We plan to implement [KDBX 4 support](https://github.com/keepassxreboot/keepassxc/issues/148), so you can use Argon2 and ChaCha20 to improve your database security while still being able to open it on other apps.
