### ISSUE TITLE
Unable Command + Tab or Command + ` between windows when KeePassXC is maximized. 

### ISSUE THREAD

**Issue by cpena002** [keepassxreboot/keepassxc#7470]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
When the KeePassXC window is on focused, I'm unable to Command + ` between other applications. I have to either close or minimize the KeePassXC window. 

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. On Mac: Open two chrome windows. Open KeePassXC
2. While KeePassXC is maximized, change focus on one of the Chrome windows.  
3. While focus on one of the Chrome windows, press Command + ` to switch between chrome windows. You won't be able to. This happens with other apps too. Excel in my case. 
4. Minimize KeePassXC and you will be able to tab between two app windows using the Command + ` shortcut. 

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

I should be able to Command + ` between two app windows. 

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

While KeePassXC is maximized I can't tab between two app windows.

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION 2.6.6
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS
Desktop Env: 
Windowing System:

**Comment by cpena002** [comment]
It also happens when you try to Command + Tab between KeePassXC and another app. In my case Chrome.

**Comment by varjolintu** [comment]
I could not reproduce this with macOS Catalina. Switching to another application and back to/from fullscreen KeePassXC works normally. Also switching between application windows works.

**Comment by cpena002** [comment]
I'm on Big Sur 11.6.2

**Comment by varjolintu** [comment]
@cpena002 Same thing with Big Sur. Cannot reproduce it. Is there some application affecting to your keyboard shortcuts? You can also try KeePassXC 2.7.0 Beta 1 if it solves the problem.

**Comment by cpena002** [comment]
Here's a video showing the issue. 

https://user-images.githubusercontent.com/22306833/156961970-c51101f7-1877-4f8c-84d7-e4cff89dbd68.mp4

**Comment by droidmonkey** [comment]
View -> Always on Top. You need to turn that off.

**Comment by cpena002** [comment]
Well, damn. That was simple enough. Sorry for wasting your time.

**Comment by nkiki** [comment]
> View -> Always on Top. You need to turn that off.

tks！！
