### ISSUE TITLE
KeePassXC not working with hummingbird (and MacOS Accessibility APIs)

### ISSUE THREAD

**Issue by reagle** [keepassxreboot/keepassxc#7478]
## Overview

[Hummingbird](https://github.com/finestructure/Hummingbird) is not able to move and resize KeePassXC, likely because it is not supporting the standard MacOS Accessibility API. See finestructure/Hummingbird/issues/5

## Steps to Reproduce
1.  Install Hummingbird
2. Attempt to move or resize KeePassXC
3. You will see, instead, the last focussed window being changed.

KPXC 2.6.6  on macOS 12.2.1 21D62 arm64

**Comment by droidmonkey** [comment]
If anything this would be a qt issue, but there is nothing we are doing to change accessibility api.

**Comment by reagle** [comment]
The only other QT app I know I have installed and QBittorrent and it too has this problem. I know nothing about QT dev, could you help me file an issue there?

**Comment by droidmonkey** [comment]
https://bugreports.qt.io

**Comment by reagle** [comment]
I don't have an account there and know nothing about QT. It'd be great if you could push this upstream.

**Comment by droidmonkey** [comment]
I know nothing about hummingbird and do not have the time to replicate the issue for the bug report.
