### ISSUE TITLE
cursor disappearing on Ubuntu

### ISSUE THREAD

**Issue by SCBuergel** [keepassxreboot/keepassxc#7480]
## Overview
The Ubuntu UI is pretty quirky but it's hard to specify what makes the feeling so "bad" I'm trying to break it down in specifics. One issue is that the cursor at times disappears, that makes it pretty harder and to know where you're typing and overall decreases the UX.

Below I describe how this affects the search textbox but in fact this affects ALL text boxes including all text boxes in the edit view: Title, Username, Password, URL, etc

## Steps to Reproduce
(this problem is hard to reproduce and does not happen all the time)
1. start keepassxc
2. start typing in the "search" textbox, move the arrow keys around and see how there is no cursor

## Expected Behavior
I expect to see a cursor in the text boxes while I'm typing.

## Actual Behavior
No cursor visible.

## Context

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.6
Revision: 9c108b9
Distribution: Snap

Qt 5.9.5
Debugging mode is disabled.

Operating system: Ubuntu Core 18
CPU architecture: x86_64
Kernel: linux 5.13.0-30-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- libgcrypt 1.8.1

[NOTE]: # ( Pick choices based on your environment )
Operating System: Ubuntu 20.04
Desktop Env: Gnome

**Comment by phoerious** [comment]
The cursor disappearing while you are typing is most likely a platform feature. It's very common on all platforms that this happens. It should reappear as soon as you move the mouse. This behaviour is not KeePassXC-specific. The Chrome browser doesn't do it, but most applications do. Try Notepad on Windows, for example. If the cursor hovers over the input area while typing, it will disappear.

**Comment by droidmonkey** [comment]
Search the closed issues for "cursor" there are a bunch of old ones all attributed to desktop env or Qt bugs. We don't control the cursor visibility.
