### ISSUE TITLE
"Created" timestamp not in line with entry history for entries copied from one database to another

### ISSUE THREAD

**Issue by tx3eh8IUD1** [keepassxreboot/keepassxc#7482]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

## Steps to Reproduce
1. Copy an entry from one database to another (drag & drop)
2. Show "created" column in entries list
3. See that the "created" column shows time of drag & drop rather than when the item was actually created
4. Realize that neither "modified" nor "created" time was changed in the item history

## Expected Behavior
I would expect that the date and time from the history are shown in the entries list and not the time when an item was copied

## Actual Behavior
Entries list shows time of moving entry between databases as "creation time", without affecting the history - creating a mismatch between history and entry view

KeePassXC - Version 2.6.6
Revision: 9c108b9

Qt 5.15.2
Debugging mode is disabled.

Operating system: Windows 10 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.19044

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
- libgcrypt 1.9.2-unknown

**Comment by droidmonkey** [comment]
#6202
