### ISSUE TITLE
Attachment changes not saved

### ISSUE THREAD

**Issue by feeblor** [keepassxreboot/keepassxc#7485]
Version: 2.6.6 for Linux (Ubuntu 20.04)

When opening and editing an attachment, changes are not saved.  I attached a RTF file to an entry, opened it to LibreOffice Writer, made changes, saved it, closed it in Writer, and returned to KeePassXC.  When I opened it again, the changes were gone.  I tried hitting "ok" to write the entry to the database after making changes, but that did not work either.  

The user guide claims I should be able to "choose between importing or discarding the changes that you made to the temporary file".  I could not find where to make that choice.  (Please let me know if this is user error!)

**Comment by droidmonkey** [comment]
Feature of 2.7.0
