### ISSUE TITLE
Temp attachment files not deleted when entry closed or database locked, only when application terminates

### ISSUE THREAD

**Issue by feeblor** [keepassxreboot/keepassxc#7486]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Open entry
2. Open attachment to that entry (to external program)
3. Close attachment (in external program)
4. Close entry by hitting ok (or cancel)
5. Lock database
6. Quit KeePassXC

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

Ideally the temporary file created when opening the attachment would be scrubbed and deleted at the earliest possible opportunity, ie, when the entry is closed.  But it should certainly be scrubbed when the database is locked.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

The temporary file is not scrubbed until the KeePassXC is terminated.

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.6.6
Revision: 9c108b9

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: Gnome
Windowing System: X11

**Comment by droidmonkey** [comment]
Feature in 2.7.0
