### ISSUE TITLE
Portable keepassxc.ini do not work on Ubuntu with AppImage

### ISSUE THREAD

**Issue by fcore117** [keepassxreboot/keepassxc#749]
Tested version 2.2.0 appimage from portable ext4 usb drive keepassxc.ini reading and writing from own folder do not work or it is just appimage fault and only works with original binary?

**Comment by phoerious** [comment]
It would be great if you wouldn't delete the issue template.

Have you tried moving the keepassxc.ini file to the same folder as the AppImage?

**Comment by fcore117** [comment]
I could test more if it works, will empy keepassxc.ini work?

**Comment by phoerious** [comment]
It should, but you can also copy over your real keepassxc.ini from ~/.config/keepassxc/keepassxc.ini

**Comment by benoit-pierre** [comment]
What I've noticed when adding AppImage support to another application is that the standard provided `AppRun` launcher will [change the working directory on startup](https://github.com/AppImage/AppImageKit/blob/appimagetool/master/AppRun.c#L151). So:
* `./KeePassXC-2.2.0-x86_64.AppImage keepass.db` does not work
* but `./KeePassXC-2.2.0-x86_64.AppImage $PWD/keepass.db` does
* similarly, `./KeePassXC-2.2.0-x86_64.AppImage --config $PWD/keepassxc.ini` must be used (and it's not picked up by default)

**Comment by phoerious** [comment]
I was suspecting that. I suppose we should either fix that in KeePassXC or even better in our AppImage startup script.

**Comment by benoit-pierre** [comment]
The original working directory is available as the `OWD` environment variable. Alternatively, you could use a custom `AppRun` (like a bash script), this way you could also add an option allow using the embedded `keepassxc-cli` (as I don't think there's a way to use it with the current AppImage).

**Comment by phoerious** [comment]
Our AppImage recipse already generates a wrapper startup script that does a some of magic and fixes a few AppImage issues: https://github.com/keepassxreboot/keepassxc/blob/develop/AppImage-Recipe.sh#L74

**Comment by fcore117** [comment]
Thanks for taking care of it, Appimage is wonderful distribution way and no installation required.

**Comment by phoerious** [comment]
Closing this, since our AppImages have change significantly. Please reopen if this is still a problem.
