### ISSUE TITLE
Auto-type failed to input tilde as a last pasword's character

### ISSUE THREAD

**Issue by szymonesdev** [keepassxreboot/keepassxc#7491]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
I've noticed that regular and pick chars auto-type failed to input ~ as a last character

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Generate regular or pick chars auto-type password with ~ as a last character
2. Run auto-type of {password} or select ~ as last character in pick chars auto-type
3. Tilde won't appear until you press another key on keyboard

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Tilde should be inputed just as any character

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.0 Beta

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 10

**Comment by hifi** [comment]
Which keyboard layouts are enabled for you?

**Comment by droidmonkey** [comment]
Are you using a keyboard layout that is not EN-US?

**Comment by szymonesdev** [comment]
QWERTY/US/Polish language

**Comment by hifi** [comment]
I believe the issue is ~ on your active keyboard layout is a dead key. Can you confirm that you need to hit space or something if you actually type ~ yourself?

**Comment by szymonesdev** [comment]
Yes, I have to press another key to input tilde.

**Comment by ghost** [comment]
I have a similar issue. When i try entering a word with a tilde keepassxc do not recognize it but if I make the password visible instead of dots I can put the tilde without any problem.

**Comment by droidmonkey** [comment]
That's a totally different problem, and a qt bug to boot.

**Comment by droidmonkey** [comment]
This was fixed
