### ISSUE TITLE
Invisible "Personal certificate" UI

### ISSUE THREAD

**Issue by Galliver7** [keepassxreboot/keepassxc#7492]
## Overview
KeepassXC do not show "Personal ceritificate" UI on its setting.

## Steps to Reproduce
1. Open setting
2. Go to "keeshare"

## Expected Behavior
Showed "Personal certificate" UI

## Actual Behavior
Keepass do not show the UI seem like below:
<img width="1215" alt="スクリーンショット 2022-03-04 9 32 46" src="https://user-images.githubusercontent.com/8030470/156676790-fd34ee17-f932-444c-b78b-fa8a8ba9de5d.png">

It should be (from [User Guide](https://keepassxc.org/docs/KeePassXC_UserGuide.html)):
![index](https://user-images.githubusercontent.com/8030470/156677714-22114f99-b3a0-4ba5-a1ef-60d03d4d7ba9.png)

## Context
If it disabled for some environment, it is better to update user guide at least.
The screenshot is showing the UI, so very confusing.
https://keepassxc.org/docs/KeePassXC_UserGuide.html

Debug info
KeePassXC - Version 2.6.6
Revision: 386b79a

Qt 5.15.2
Debugging mode is disabled.

Operating system: macOS 12.2
CPU architecture: arm64
Kernel: darwin 21.3.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (only unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
- libgcrypt 1.9.3

## LOVE
Hope this issue could help you guys! 🥰
Much appreciate for all this project.

**Comment by droidmonkey** [comment]
This entire ui has been removed in 2.7.0
