### ISSUE TITLE
Feature request : Feature administration

### ISSUE THREAD

**Issue by hwkspam** [keepassxreboot/keepassxc#7494]
Dear KeepassXC-Team,

I read about a feature to administer multiple users by adding a special .ini file to the KeepassXC directory named:
KeePass.enforced.ini

But it seems that this feature never was a feature of KeepassXC in the first place - but a feature of the classic keepass : 
https://keepass.info/help/kb/config_enf.html

Are there other ways to administer multiple KPXC users so we can preconfigure/enable/disable features for our users?
Otherwise - are there plans to add such a feature in the future?

Thank you for your great work,
Oliver

**Comment by droidmonkey** [comment]
This is tracked by #2189
