### ISSUE TITLE
Conflict between Keepass, touchpad and Yubikey again

### ISSUE THREAD

**Issue by pascal06** [keepassxreboot/keepassxc#7496]
Hello everyone,
sorry in advance, I'm just a user of Ubuntu and Keepass, that means I'm not a computer engineer, even if I know embedded programming as I'm an electronic engineer. So, following my last issue (see #7189 ), I bought a knew computer, installed the last LTS version of Ubuntu 20.04... And I've got the same issue when I'm using KeepassXC with a Yubikey !
Please, I request your valuable help to understand this problem.
Thanks a lot for your comprehension in advance.

Pascal

**Comment by droidmonkey** [comment]
Please download and try the 2.7.0 beta build to see if it continues: https://github.com/keepassxreboot/keepassxc/releases/tag/2.7.0-beta1
