### ISSUE TITLE
Feature: Add support for basic references in autotype

### ISSUE THREAD

**Issue by meisanerd** [keepassxreboot/keepassxc#75]
In the source keypassx github, there is a pull request for adding some of the basic keepass references into autotype.  Is it possible to get that PR merged into this fork?
https://github.com/keepassx/keepassx/pull/184

## Expected Behavior
On Amazon.ca, I should be able to autotype/fill from ChromeIPass the records from amazon.com, as the u/p combo is stored as {REF:U@I:AMAZON.COM_UUID} and {REF:P@I:AMAZON.COM_UUID}

## Current Behavior
It sends the strings (ie: {REF:U@I:AMAZON.COM_UUID}) instead of the u/p specified in the amazon.com reference

## Possible Solution
Copy the pull request from the keepassx github and merge it in

## Context
Amazon.com and Amazon.ca both use the same credentials, but as they are using different URLs, they are seen as different sites to Keepass/KeepassX and ChromeIPass.  Keepass on Windows manages this by allowing you to create 2+ separate entries, one containing the real values, the other containing a reference via UUID to the first one (http://keepass.info/help/base/fieldrefs.html).

**Comment by TheZ3ro** [comment]
This should also have a nice GUI like discussed in https://github.com/keepassxreboot/keepassxc/issues/274

**Comment by mrrsm** [comment]
@TheZ3ro Is this something you are working on?  If not I can clean up my code for this and make a PR.

**Comment by droidmonkey** [comment]
Does it have a nice GUI interface as described in my last comment on #274?

**Comment by mrrsm** [comment]
My current changes create a popup when you clone an entry which gives you the option for references (along with a few other things). http://imgur.com/a/nYeYs
This works similar to how KeePass does it at least.

I should be able to change the edit entry page to pick a custom entry to reference as well if that is how you would like it to work.  At least in my use cases I rarely make a current entry a reference but instead create the reference on clone.

**Comment by TheZ3ro** [comment]
@mrrsm currently I'm not working on it. I like the clone with reference idea and if it's the KeePass behavior I think we should go for it. 
Unfortunately this is limited to Username and Password. I agree that most of the case that are the only useful field to reference but every field should be available for reference.
Maybe adding a nice gui/dialog for selecting references with a button next to the field should be the next step.

**Comment by droidmonkey** [comment]
@mrrsm that looks great and a good idea to put it with cloning.

**Comment by mrrsm** [comment]
So where would you want to have the settings for cloning other fields? I was looking into that last night and the only option that didn't seem too obtrusive was to define in the settings globally what fields will get transferred as references when you clone.  This would then turn the replace username/password with replace fields with references.  My use case is just for user/pass references and I mimicked what KeePass 2.x had however I agree it could probably be improved upon.
The final option would be me pushing what I have now and we can make a new task to add additional pieces as we determine how they should work.

**Comment by phoerious** [comment]
Make a PR with a couple of screenshots against develop and we'll work it out.

**Comment by TheZ3ro** [comment]
What I was saying is. The reference used with KeePass syntax (see first post) needs to be available in all the fields. 
If I enter in an entry URL `{REF:A@I:9831}` I expect to refer to the `9831` entry's URL.
The reference-parsing code should be enabled on all the entry's field. (like in https://github.com/keepassx/keepassx/pull/184/files)

Then when cloning user can automatically use reference.
