### ISSUE TITLE
number in passphrase PasswordGenerator 

### ISSUE THREAD

**Issue by legolass73** [keepassxreboot/keepassxc#7504]
## Summary
it would be wise to add the possibility of adding numbers of generation criteria to the generation of passphrase in order to improve the strength and complexity of the passphrase

## Examples
![image](https://user-images.githubusercontent.com/5279851/157058242-af9411fe-2042-4ad1-8cb0-9c1cfe934865.png)

## Context
in most current password policies, it now requires at least one or more numbers / numbers. for this I am obliged to add random figures on passphrase and therefore become very restrictive

**Comment by droidmonkey** [comment]
You can add them manually, this has been discussed before here. Passphrase is specifically not meant to be complex.
