### ISSUE TITLE
KeepassXC keeps crashing at startup

### ISSUE THREAD

**Issue by vfrigols** [keepassxreboot/keepassxc#7506]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
KeepassXC keeps crashing at startup. It worked correctly for some time, but has unexpectedly started to crash and doesn't start.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Start keepassxc
2. 
3. 

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Startup

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
It crashes. When starting from command line it gives the following messages (in Notes).

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION 2.6.6
Revision: REVISION
[1] 20360
(keepassxc:20360): Gtk-WARNING **: 19:28:33.970: Theme parsing error: gtk.css:1428:23: 'font-feature-settings' is not a valid property name
(keepassxc:20360): Gtk-WARNING **: 19:28:33.974: Theme parsing error: gtk.css:3318:25: 'font-feature-settings' is not a valid property name
(keepassxc:20360): Gtk-WARNING **: 19:28:33.976: Theme parsing error: gtk.css:3780:23: 'font-feature-settings' is not a valid property name
Gtk-Message: 19:28:34.038: Failed to load module "canberra-gtk-module"
Gtk-Message: 19:28:34.040: Failed to load module "canberra-gtk-module"
Qt: Session management error: Could not open network socket
Fontconfig warning: FcPattern object weight does not accept value [50 200)

[1]+  Segmentation fault      keepassxc

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: Gnome
Windowing System: X11

**Comment by droidmonkey** [comment]
https://github.com/keepassxreboot/keepassxc/issues/5150#issuecomment-863708339
