### ISSUE TITLE
KeePassHTTP returns items in the recycle bin

### ISSUE THREAD

**Issue by Ivan0xFF** [keepassxreboot/keepassxc#751]
KeePassXC with KeePassHTTP enabled will return all matching items, including ones in the recycle bin.

## Expected Behavior
Items in the Recycle Bin are ignored and not sent to the browser addon via KeePassHTTP

## Current Behavior
Items in the Recycle Bin are included in results sent to browser addon via KeePassHTTP

**Comment by PF93mc8y7erq92qTmTjJBysALa** [comment]
KeePassHTTP has been removed as of the 2.4.0 release (#1752).
