### ISSUE TITLE
KeepassXC failed to build with many error with MSVC on windows amd64

### ISSUE THREAD

**Issue by Vincent9802** [keepassxreboot/keepassxc#7514]
Hi All,

Environment:
VS 2019 + Windows Server 2019

KeepassXC failed to build with many error with MSVC on windows amd64. for example: error C2664: 'winrt::Windows::Storage::Streams::IBuffer winrt::Windows::Security::Cryptography::CryptographicBuffer::CreateFromByteArray(winrt::array_view<const uint8_t>)': cannot convert argument 1 from 'winrt::array_view<T>' to 'winrt::array_view<const uint8_t>'. It can be reproduced on latest version 4f07103 on develop branch. Could you please help look at this issue?

**Repro steps**:

1. git clone https://github.com/keepassxreboot/keepassxc F:\gitP\keepassxreboot\keepassxc
2. set VSCMD_SKIP_SENDTELEMETRY=1 & "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsDevCmd.bat" -host_arch=amd64 -arch=amd64
3. cd F:\gitP\Microsoft\vcpkg
4. vcpkg.exe install --recurse botan zlib minizip libqrencode readline --triplet x64-windows --clean-after-build 2>&1
5. create folder F:\gitP\keepassxreboot\keepassxc\build_amd64
6. cd F:\gitP\keepassxreboot\keepassxc\build_amd64
7. set PATH=F:\tools\qt5\qt\5_15_2\msvc2019_64\bin;%PATH%
8. gem install asciidoctor 2>&1
9. cmake -G "Visual Studio 16 2019" -A x64 -DCMAKE_SYSTEM_VERSION=10.0.18362.0 -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=F:\gitP\Microsoft\vcpkg\scripts\buildsystems\vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows .. 2>&1
10. msbuild /m /p:Platform=x64 /p:Configuration=Release KeePassXC.sln /t:Rebuild 2>&1

log: [build.zip](https://github.com/keepassxreboot/keepassxc/files/8221947/build.zip)

**Error info:**
         F:\gitP\keepassxreboot\keepassxc\src\winhello\WindowsHello.cpp(58,53): error C2664: 'winrt::Windows::Storage::Streams::IBuffer winrt::Windows::Security::Cryptography::CryptographicBuffer::CreateFromByteArray(winrt::array_view<const uint8_t>)': cannot convert argument 1 from 'winrt::array_view<T>' to 'winrt::array_view<const uint8_t>' [F:\gitP\keepassxreboot\keepassxc\build_amd64\src\keepassx_core.vcxproj]
         F:\gitP\keepassxreboot\keepassxc\src\winhello\WindowsHello.cpp(74,73): error C3536: 'challengeBuffer': cannot be used before it is initialized [F:\gitP\keepassxreboot\keepassxc\build_amd64\src\keepassx_core.vcxproj]
         F:\gitP\keepassxreboot\keepassxc\src\winhello\WindowsHello.cpp(86,9): error C3536: 'challengeBuffer': cannot be used before it is initialized [F:\gitP\keepassxreboot\keepassxc\build_amd64\src\keepassx_core.vcxproj]
         F:\gitP\keepassxreboot\keepassxc\src\winhello\WindowsHello.cpp(74,55): error C2664: 'winrt::Windows::Foundation::IAsyncOperation<winrt::Windows::Security::Credentials::KeyCredentialOperationResult> winrt::impl::consume_Windows_Security_Credentials_IKeyCredential<winrt::Windows::Security::Credentials::IKeyCredential>::RequestSignAsync(const winrt::Windows::Storage::Streams::IBuffer &) const': cannot convert argument 1 from 'int' to 'const winrt::Windows::Storage::Streams::IBuffer &' [F:\gitP\keepassxreboot\keepassxc\build_amd64\src\keepassx_core.vcxproj]
         F:\gitP\keepassxreboot\keepassxc\src\winhello\WindowsHello.cpp(74,24): error C2737: 'signature': const object must be initialized [F:\gitP\keepassxreboot\keepassxc\build_amd64\src\keepassx_core.vcxproj]
         F:\gitP\keepassxreboot\keepassxc\src\winhello\WindowsHello.cpp(86,9): error C3536: 'signature': cannot be used before it is initialized [F:\gitP\keepassxreboot\keepassxc\build_amd64\src\keepassx_core.vcxproj]
         F:\gitP\keepassxreboot\keepassxc\src\winhello\WindowsHello.cpp(81,24): error C2737: 'response': const object must be initialized [F:\gitP\keepassxreboot\keepassxc\build_amd64\src\keepassx_core.vcxproj]
         F:\gitP\keepassxreboot\keepassxc\src\winhello\WindowsHello.cpp(86,9): error C3536: 'response': cannot be used before it is initialized [F:\gitP\keepassxreboot\keepassxc\build_amd64\src\keepassx_core.vcxproj]

**Comment by droidmonkey** [comment]
You need the latest winrt. Install the latest version of the windows sdk (10.0.22000), I prefer windows 11 sdk. The name means nothing.
