### ISSUE TITLE
Right click stopped working

### ISSUE THREAD

**Issue by zeverson** [keepassxreboot/keepassxc#7516]
Running KeePassXC 2.6.6 on a MacBook Pro with macOS 12.2.1. 

This morning, right clicking an entry (such as to pull up and then copy an OTP) stopped working. Sometimes right clicking an entry would bring up a menu, but not  let me navigate to a sub menu (such as to access and copy an OTP). Other times it wouldn't bring up a menu at all. 

Problem happens with both the Magic Mouse and tracker built into the Mac. Right clicking works fine on all other apps. Thanks.

**Comment by varjolintu** [comment]
I've seen this a couple of times but have no idea why it happens. It's probably related to a popup that has been closed, but the focus is somehow messed up after that and the application cannot register right mouse clicks correctly.

**Comment by droidmonkey** [comment]
Perhaps relates to #3412

**Comment by zeverson** [comment]
Just uninstalled, rebooted, and installed again. Issue still exists.
