### ISSUE TITLE
Browser plugin not showing a specific entry

### ISSUE THREAD

**Issue by rocketraman** [keepassxreboot/keepassxc#7519]
## Overview
The Keepass-XC browser plugin does not seem to show a specific entry. The access prompt never comes up for the entry. "Hide this entry from the browser extension" is not checked for the entry.

## Steps to Reproduce
1. Unsure

I have this issue with a Google login. I have about 15 accounts, and I only notice one particular one does not work. Creating a new entry works fine, and comes up with the expected access control prompt. The access control prompt never comes up for the entry in question. The plugin properties do not have any allow or deny settings for the entry.

## Expected Behavior
I should see all entries.

## Actual Behavior
I see all except one.

## Context
KeePassXC - Version 2.6.6
Revision: 9c108b9

Qt 5.15.2
Debugging mode is disabled.

Operating system: Fedora Linux 35 (Thirty Five)
CPU architecture: x86_64
Kernel: linux 5.16.12-200.fc35.x86_64

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- libgcrypt 1.9.4-unknown

Desktop Env: KDE
Windowing System: X11

**Comment by droidmonkey** [comment]
You likely blocked that entry from showing.

**Comment by rocketraman** [comment]
> You likely blocked that entry from showing.

"Hide this entry from the browser extension" is not checked. Is there another way to block that I should check?

**Comment by rocketraman** [comment]
It does seem to be *something* with that entry though. When I create a new entry, I get a popup in the browser with the usual access prompt for the new entry. That never comes up for the missing entry.

**Comment by droidmonkey** [comment]
Go to the properties of that entry and delete the browser custom data

**Comment by rocketraman** [comment]
There is none:

![image](https://user-images.githubusercontent.com/53049/157750676-06293833-b4cc-44b6-a7ba-3bd6c7554683.png)

Tried deleting anyway and no effect.

**Comment by rocketraman** [comment]
OMG, I put `https://acccounts.google.com/` in the URL instead of `https://accounts.google.com/`. Yikes, sorry for the noise.

**Comment by droidmonkey** [comment]
that was what I was about to write
