### ISSUE TITLE
AutoType for Reddit not working (types in find bar instead)

### ISSUE THREAD

**Issue by rieje** [keepassxreboot/keepassxc#752]
## Expected Behavior
AutoType should work for Reddit.

## Current Behavior
It doesn't--username and password are entered to Firefox's find string bar on the bottom

## Steps to Reproduce (for bugs)
Use the default sequence `{USERNAME}{TAB}{PASSWORD}{ENTER}`.

## Context
Trying to set AutoType login for reddit. The default sequence, according to what I've read, works with KeePass but I'm not sure about KeePassXC (haven't found anyone complaining, so the problem is probably on my end. 

## Debug Info
KeePassXC - Version 2.2.0
Revision: caa49a8ef3ee28ed478192389b21d61107b3b8e0

Operating system: Arch Linux
CPU architecture: 64-bit
Linux Kernel: 4.11.7-1-1

**Comment by sts10** [comment]
Longshot attempt at clarification: Are you trying to sign in from [https://www.reddit.com/login](https://www.reddit.com/login) or from the login module thing: 

![screen shot 2017-07-05 at 11 18 14 pm](https://user-images.githubusercontent.com/4871664/27894147-6db95902-61d8-11e7-9d49-299b2d63c824.png)

The KeePassXC's default AutoType sequence works for me on the /login page; but I've yet to get AutoType to work with module pictured in the above screenshot.

**Comment by rieje** [comment]
@sts10 Oh yes... I wasn't even aware there was an alternative way to login. It works if I login  from the "main page." So I guess it's not really an issue then and someone can create a new one if they have a need to login from the "module." Thanks!
