### ISSUE TITLE
AppImage Signature Expired/Revoked

### ISSUE THREAD

**Issue by Spiralpine** [keepassxreboot/keepassxc#7522]
From https://github.com/keepassxreboot/keepassxc/releases/tag/2.6.6:
When trying to verify the KeePassXC-2.6.6-x86_64.AppImage.sig file for the KeePassXC-2.6.6-x86_64.AppImage file, I'm getting this:

user1@penguin:~/Applications/keepassxc-appimage$ gpg --verify --verbose --keyring vendors.gpg ./KeePassXC-2.6.6-x86_64.AppImage.sig
gpg: assuming signed data in './KeePassXC-2.6.6-x86_64.AppImage'
gpg: Signature made Sat 12 Jun 2021 09:41:51 AM EDT
gpg: using RSA key C1E4CBA3AD78D3AFD894F9E0B7A66F03B59076A8
gpg: Note: signature key AFF235EEFB5A2517 expired Thu 07 Jan 2021 01:49:30 PM EST
gpg: Note: signature key AFF235EEFB5A2517 has been revoked
gpg: using subkey B7A66F03B59076A8 instead of primary key CFB4C2166397D0D2
gpg: Note: signature key AFF235EEFB5A2517 expired Thu 07 Jan 2021 01:49:30 PM EST
gpg: Note: signature key AFF235EEFB5A2517 has been revoked
gpg: using subkey B7A66F03B59076A8 instead of primary key CFB4C2166397D0D2
gpg: using pgp trust model
gpg: Good signature from "KeePassXC Release [release@keepassxc.org](mailto:release@keepassxc.org)" [unknown]
gpg: Note: signature key AFF235EEFB5A2517 expired Thu 07 Jan 2021 01:49:30 PM EST
gpg: Note: signature key AFF235EEFB5A2517 has been revoked
gpg: using subkey B7A66F03B59076A8 instead of primary key CFB4C2166397D0D2
gpg: Note: signature key AFF235EEFB5A2517 expired Thu 07 Jan 2021 01:49:30 PM EST
gpg: Note: signature key AFF235EEFB5A2517 has been revoked
gpg: WARNING: This key is not certified with a trusted signature!
gpg: There is no indication that the signature belongs to the owner.
Primary key fingerprint: BF5A 669F 2272 CF43 24C1 FDA8 CFB4 C216 6397 D0D2
Subkey fingerprint: C1E4 CBA3 AD78 D3AF D894 F9E0 B7A6 6F03 B590 76A8
gpg: binary signature, digest algorithm SHA512, key algorithm rsa2048

**Comment by droidmonkey** [comment]
Update your keys `gpg --update-keys`

**Comment by droidmonkey** [comment]
Read carefully (also dont use verbose mode)

**gpg: using subkey B7A66F03B59076A8 instead of primary key CFB4C2166397D0D2
gpg: using pgp trust model
gpg: Good signature from "KeePassXC Release release@keepassxc.org" [unknown]**
