### ISSUE TITLE
Option to require possession of key file (raw key file of arbitrary size)

### ISSUE THREAD

**Issue by Agoristen** [keepassxreboot/keepassxc#7529]
## Summary
In a database with "key file" enabled, possession of key file is **not required**. It is enough to know the hash of the key file. 

There should be an option to require possession of the key by allowing any raw key file of any size to be used in generation of the final sha256 hash.

Specifically, instead of: 
`SHA-256(SHA-256(password), SHA-256(key file contents))`

It should do:
`SHA-256(SHA-256(password), key file contents)`

By requiring possession of the key file, an attacker needs to download the key file in full and hash it along with the password between each attempt. This will make attacks a lot harder. Especially if a key file of large size is used. 

In the current implementation, it is enough for an attacker to possess a list of hashes which can be quickly compared against. 

There should be an option to "require possession" for those who prefer physical possession of the file.

It is counter-intuitive that key file does not require you to hold the file when unlocking a database and could potentially be a security risk (Virus programs or other scanning tools checking and transferring hashes to compare against an online database, file sharing, etc) 

## Example of current situation

In this example I am downloading `KeePassXC-2.6.6-Win64.msi` and using it as key file. The sha256 of the file is:
`41AB0337BC630FE7C0F91B89E3FD868E75BA8C10E4BC6011AA5799F1A0A738E4`

After setting up the database:
1. Delete `KeePassXC-2.6.6-Win64.msi`
2. Create .txt file that only contains the sha256 hash: `41AB0337BC630FE7C0F91B89E3FD868E75BA8C10E4BC6011AA5799F1A0A738E4`
3. You can now login to database using the txt file (hash only) instead of the key file

Anyone can google this hash online and find plenty of pages where it is listed. There is no need to download the file. Bots traversing the web can collect these hashes. 

## Context

There's no obvious connection between a single individual and any random publicly available file online. It is also not feasible for an attacker to download "the entire internet" to test all files. By selecting a public file, e.g a Ubuntu 20.04 LTS image (which is also seeded as a torrent), the key file remains accessible to the individual in a disaster scenario where all local/offline copies are lost.

The key file could also be hosted somewhere more secluded, for example a file accessible through Wayback Machine or uploaded to a few cloud storages not directly tied to the user. 

Storing database in the cloud is common, but the key file should be stored in a separate location. For users who feel uncertain about their local environments this will give a sense of relief knowing that the key file is out there even if they don't have a backup in their own cloud storage.

This is especially useful for users who need to secure a database that is never connected to the internet.

**Comment by droidmonkey** [comment]
Use a Yubikey or OnlyKey if you want to prove possession. We are following the KDBX standard and cannot make changes to the key derivation. Also, don't use a file that is known public.

We also strongly recommend using a generated key file which stores the key hash within the keyfile itself. Knowing the hash of the file is not relevant in that scenario and is closer to "possession".

**Comment by Agoristen** [comment]
Yes, makes sense, but it doesn't solve my issue of needing to backup the key file. I'd rather it be available somewhere online. A Yubikey also requires a secret to be stored, which is the same issue. 

> Also, don't use a file that is known public.

Let's say I used a public file as my key file and told everyone about it, it would not reduce my security versus the current situation of not using a key file, correct?

I trust my password, the key file would just be extra, and having it be a public file that I can access from anywhere would be a convenience. No attacker would have any clue which file it is, so I really don't see why choosing a public file would be bad in my situation. Maybe it doesn't add much security, but it wouldn't make me worse off either. I am more fearful of losing the file and access to my database.

**Comment by droidmonkey** [comment]
1. The public file _could_ change, locking you out of your database. 
2. Public files are not random data. You are far more secure generating a key file, using the KeePassXC generate option, and storing it in an encrypted container in the cloud (backup) and wherever else locally. 
3. You are viewing key files as some form of second factor, they are not. You can get close by only storing the keyfile on a usb stick you only ever plug in when needed. A hardware key is a second factor, the secret never leaves the key. 

If you trust your password then that's really all you need. Adding a key file is no better than just making your password a little longer or more complex.

**Comment by Agoristen** [comment]
I understand it's not random, but in theory the options are endless (how many files are available on the web and how are you supposed to guess which file I have used?) and the file itself is also not random, but can have a lot of entropy depending on which file you choose. 

I will be using a file that won't change. The computer will never connect to the internet. The key file will only be placed on a USB and also never connected to the internet, but the backup will be on the internet, it just won't be uploaded by me. 

The database will be stored in personal cloud storage. 

I can understand in general it's not a good advice to use a public file for this, but in my case I don't see any downsides. Maybe no great upside, but no downside. Wouldn't you agree?
