### ISSUE TITLE
Auto-Type Type Sequence Button Drop Down Arrow Is Very Small - 2.7.0 and macOS

### ISSUE THREAD

**Issue by 2BeeOrNot** [keepassxreboot/keepassxc#7532]
Tried 2.7.0 beta on macOS 12.2.1. The Type Sequence button drop down arrow is very small and close to edge of button.
![KPXC Dwn Arrow](https://user-images.githubusercontent.com/63317977/158069228-4524f9a1-3971-4266-a4a4-a7bdfb3b481f.jpg)

I found this image in another post from Windows(?) and it is so much more visible.
![KPXC Dwn Arrow 2](https://user-images.githubusercontent.com/63317977/158069252-a6013906-3c79-42ab-bd18-36621052dabb.jpg)

Thanks for KPXC. If you ignore ignore the super geeky stuff here like D-Bus, SSH agent, secret service etc. it's a great password manager for macOS users.

**Comment by droidmonkey** [comment]
Looks like you are in classic mode theme. Set it to either the light or dark or automatic to use our theme. The classic theme is pure Qt so not our bug.
