### ISSUE TITLE
Cannot import Keeshare certificate

### ISSUE THREAD

**Issue by AlexGiroud** [keepassxreboot/keepassxc#7534]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
![image](https://user-images.githubusercontent.com/8853344/158190997-b92ed48c-28ac-4057-9ec3-474260040b3a.png)
Trust and ask button are bugged

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Open settings
2. Go to keeshare pane
3. Try to import trusted certificate

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
To be able to import a certificate

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Ui bugged, nothing in particular happens 
![image](https://user-images.githubusercontent.com/8853344/158191445-52facfa9-5b0a-4a4a-b986-ab0546a21bf1.png)

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.6
Revision: 9c108b9

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows/macOS

**Comment by droidmonkey** [comment]
Update to 2.7.0 that UI is gone
