### ISSUE TITLE
Add ability to quickly show protected attributes without having to edit the entry itself

### ISSUE THREAD

**Issue by goetzc** [keepassxreboot/keepassxc#7535]
## Summary
Right now, many steps are required to show any protected attribute, which requires _editing_ the entry itself.

## Context
It would be useful to be able to visualize the protected attributes in the preview panel. Probably after an additional user interaction, such as clicking on the `[PROTECTED]` text or clicking on an icon, such as 👁‍, 🔓, 🗝, etc. 

Currently, protected attributes cannot be read from the preview panel:
![image](https://user-images.githubusercontent.com/2220440/158245919-7987683b-3dae-4c47-9720-c82aab96ccbe.png)

**Comment by droidmonkey** [comment]
So quick that we implemented it in 2.7.0

**Comment by goetzc** [comment]
Nice! 

Thank you for your work on this nice application.
