### ISSUE TITLE
On a setup with per-monitor DPI scaling, entry context menus become larger upon opening a second time

### ISSUE THREAD

**Issue by gabechiarelli** [keepassxreboot/keepassxc#7536]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
When activating a nested context menu item a second time after the application has launched, the contents of the item become larger and overflow the boundaries of the sub-menu.

First time:
![Context Menu Before](https://user-images.githubusercontent.com/5751108/158449727-7003faa0-1621-4d27-b710-366f30e9ebdd.png)

Second time:
![Context Menu After](https://user-images.githubusercontent.com/5751108/158449745-285746a0-367b-4923-9ffb-dba450d032c3.png)

Display resolutions and DPI settings:
![Display 1 Settings](https://user-images.githubusercontent.com/5751108/158448186-4f8cdda9-671f-4f76-93ac-778bbf61d266.png)
![Display 2 Settings](https://user-images.githubusercontent.com/5751108/158448197-747d2650-21b8-489a-a2d5-a8f43d531c27.png)

(Example is running on display 2)

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Set primary display to 125% scaling and secondary display to 100% scaling.
1. Start a new instance of KeepassXC on the secondary display.
2. Open and unlock a database.
3. Right click an entry and select a nested context menu item such as Copy Attribute, TOTP, or Perform Auto-Type Sequence. The contents of this item will appear correctly sized at this point.
4. Remove the selection from the menu item in step 3 and select it again. The contents will now appear larger and overflow the boundaries of the sub-menu.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Contents of context menus should appear consistently sized between uses and relative to other UI elements

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Contents of context menus change size after the first time one is opened

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.6.6

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 10 Pro Build 19044.1586

**Comment by droidmonkey** [comment]
Known qt bug, there is nothing we can do about this.
