### ISSUE TITLE
Auto-Type: Support WIN keys like KeePass does

### ISSUE THREAD

**Issue by gitflo** [keepassxreboot/keepassxc#7537]
## Summary
The Auto-Type feature is really great, unfortunately support for the WIN keys is missing. Would be great to add this to KeePassXC, too.

## Examples
The original KeePass supportes the WIN keys as follows:
<html><body>

Windows Key | {WIN} (equ. to {LWIN})
-- | --
Windows Key: left, right | {LWIN}, {RWIN}

</body>
</html>

See https://keepass.info/help/base/autotype.html

**Comment by droidmonkey** [comment]
Supported in 2.7.0, use the # modifier. `#d` types WIN+D

**Comment by gitflo** [comment]
Lovely, thanks for pointing this out!
