### ISSUE TITLE
Missing space in export warning `unencrypted file.This`

### ISSUE THREAD

**Issue by jsoref** [keepassxreboot/keepassxc#7538]
Running [Release 2.6.6](https://github.com/keepassxreboot/keepassxc/releases/tag/2.6.6) view brew on macOS Monterey 12.2.1 (m1 chip -- this actually mattered for the last bug I fought)

![image](https://user-images.githubusercontent.com/2119212/158505178-bda93f92-e01b-4c84-a014-36fb34caba61.png)

https://github.com/keepassxreboot/keepassxc/blob/9b2b861a2af451eb160c3771db6453deb90cf792/src/gui/KMessageWidget.cpp#L85-L87

https://github.com/keepassxreboot/keepassxc/blob/9b2b861a2af451eb160c3771db6453deb90cf792/src/gui/KMessageWidget.cpp#L128-L140

https://github.com/keepassxreboot/keepassxc/blob/296cbf0df77020336060795a30fad87cd4994c90/src/gui/export/ExportDialog.cpp#L42-L43

https://github.com/keepassxreboot/keepassxc/blob/4f0710350fb53c25db6824f96961d8d17a29347c/share/translations/keepassxc_en.ts#L3941-L3942

Note: the results are worse for localizations.

Here's French fwiw:
![image](https://user-images.githubusercontent.com/2119212/158505880-a4c1a79e-718b-4839-967e-15d2aa8d7531.png)

And Russian:
![image](https://user-images.githubusercontent.com/2119212/158505982-7698cee5-2fbc-4155-ae41-bcfcc91d850a.png)

**Comment by droidmonkey** [comment]
There is a space in both the source text and translation text for the English US. 

https://github.com/keepassxreboot/keepassxc/blob/ed7acf358a6837a570cdff4bf25657fb1cb3b8c9/share/translations/keepassxc_en_US.ts#L2145

**Comment by jsoref** [comment]
The space is present, but it isn't rendered. Something is swallowing it.
