### ISSUE TITLE
Eyeball widget doesn't behave properly for RtL languages

### ISSUE THREAD

**Issue by jsoref** [keepassxreboot/keepassxc#7539]
## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
(Instructions are written assuming you're on macOS, using English as your language, have KeePassXC 2.6.6 installed, and have used it to open a database, such that when you launch it, you're prompted for a password to unlock a database)
1. Open `System Preferences.app`
2. Go to `Language & Region`
3. On the General Tab, click ➕  under `Preferred languages`
4. Type `arabic` into the 🔍  box
5. Click `العربية — Arabic`
6. Click `Add`
7. Click `Use Arabic`
8. If prompted to `Select input sources to add:`, click `Not Now`
9. Press `command`-`space`
10. Type `KeePass` (or enough to get the keepassxc application to appear in the magic box):
    ![image](https://user-images.githubusercontent.com/2119212/158506612-c83bb1bf-f1b6-485b-8d9d-550d7788151b.png)
11. Press `enter`
12. You should see a prompt to unlock a database, it should look approximately like this:
    ![image](https://user-images.githubusercontent.com/2119212/158506845-7a72a4da-f694-4dad-af47-13eea59941e9.png)
13. Focus the first field with an 👁️ 
14. press any alphanumeric key on your keyboard:
    ![image](https://user-images.githubusercontent.com/2119212/158506929-b575e7b6-f8d2-4f2d-aada-a904c88be0aa.png)

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
The eyeball shouldn't change sides just because there is or isn't a character in the field.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
The eyeball has jumped from:
![image](https://user-images.githubusercontent.com/2119212/158507034-2d0cd5da-8b00-4f45-ab7a-eb2ae2876afc.png)
to:
![image](https://user-images.githubusercontent.com/2119212/158506929-b575e7b6-f8d2-4f2d-aada-a904c88be0aa.png)

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.6
مراجعة: 386b79a

Qt 5.15.2
Debugging mode is disabled.

نظام التشغيل: macOS 12.2
معمارية المعالج: arm64
النواة: darwin 21.3.0

الإضافات المُفعلة:
-  نمط تلقائي
- تكامل المتصفح
- وكيل SSH
- KeeShare (only unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
- libgcrypt 1.9.3

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS

**Comment by droidmonkey** [comment]
This is a qt bug, not our program. Please report to https://bugreports.qt.io
