### ISSUE TITLE
grapic problem

### ISSUE THREAD

**Issue by PeterFristo** [keepassxreboot/keepassxc#7542]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # After disconnecting the notebook from the docking station, the graphic display is no longer correct. 
The main menu can no longer be controlled with the mouse and the lower part of the window is missing.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1.  release NB from docking
2.  select the running keepass windows
3. 

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
corrct this problem

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 10 21H1 (Build 19043.1466
![vorher](https://user-images.githubusercontent.com/101799649/158783894-545be03f-66e2-47a3-839a-f2a449a5b056.png)
![nachher](https://user-images.githubusercontent.com/101799649/158783916-67a9606e-b468-4028-8175-494096370066.png)

**Comment by PeterFristo** [comment]
When i select Ansicht-Immer oben it works normal!

**Comment by droidmonkey** [comment]
This would be a Qt bug, can't do anything about it. Good there is a workaround though. You probably could minimize and restore as well.
