### ISSUE TITLE
Crash on exit cannot read 0x00...050

### ISSUE THREAD

**Issue by xwcgilmore** [keepassxreboot/keepassxc#7543]
## Overview
Exiting program - popup window -
Message The instruction at 0x00007FF6310E1352 referenced memory at 0x0000000000000050. The memory could not be read. Click on OK to terminate the program 

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Exit program
2. Does not occur on every term of program
3. Random - not reproducible 

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Normal termination of program

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Memory error

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION 2.6.6
Revision: REVISION 9c108b9
Debug: Off

[NOTE]: # ( Pick choices based on your environment )
Operating System: Edition	Windows 10 Pro
Version	21H2
Installed on	‎Mon, ‎January ‎18, ‎2021
OS build	19044.1586
Experience	Windows Feature Experience Pack 120.2212.4170.0

**Comment by droidmonkey** [comment]
Are you able to run a debug build of the application?

**Comment by xwcgilmore** [comment]
> run a debug build

Have no idea how to

**Comment by hifi** [comment]
Also is this consistent on every exit? If it is you could try the 2.7.0 beta to see if it has the same behavior.

**Comment by xwcgilmore** [comment]
> Also is this consistent on every exit? If it is you could try the 2.7.0 beta to see if it has the same behavior.

Not consistent - random. I will try beta.

**Comment by droidmonkey** [comment]
Still having the issue on the beta?
