### ISSUE TITLE
Support for importing 1Password 1pux file format

### ISSUE THREAD

**Issue by changemenemo** [keepassxreboot/keepassxc#7545]
Hi,

no progress on importing 1puf extension database from 1password 8 or were you not aware of the changes? It's basically the same thing than before with small modifications

**Comment by droidmonkey** [comment]
Link to the spec?

**Comment by semicoleon** [comment]
I assume they meant "1pux" which appears to be the only non-csv way to export from 1password in version 8. It appears to be [documented here](https://support.1password.com/1pux-format/). It's a zip archive with a JSON file and attachment files

**Comment by droidmonkey** [comment]
OK that is great, but that is entirely different from the OPVault concept. In fact they share absolutely no relation to each other. At least this one is unencrypted and not spread amongst hundreds (slight exaggeration) of json files.

**Comment by possiblemeatball** [comment]
Is there any current progress towards supporting this format? For curiosity's sake, willing to contribute code, just seeking info

**Comment by droidmonkey** [comment]
No progress ~~and no intent to implement anytime soon~~. Well written and tested code welcome.

**Comment by notDavid** [comment]
Hi, so I'm guessing with the new `.1PUX` format, the section [Importing 1Password OPVault](https://keepassxc.org/docs/KeePassXC_UserGuide.html#_importing_1password_opvault) of the docs does not work anymore since 1Password 8 (or even 1Password 7) ?

Perhaps it would be a good idea to change these docs, to avoid confusion / people trying to figure out how to do it? :-)

I'm guessing the currently recommended method is to export to `.csv` ?

**Comment by droidmonkey** [comment]
They work fine, you need to export your 1Password database as an opvault though.

**Comment by notDavid** [comment]
@droidmonkey How? I can't pick this option (in 1Password 7 on macOS):

`1Password7 > File > Export > All items > ` :

<img width="343" alt="Screenshot 2022-09-03 at 14 53 38" src="https://user-images.githubusercontent.com/1530401/188271342-de08618c-b6e3-4bfa-b906-8944e84ecb09.png">

Also, i don't see it in the [1Password export docs](https://support.1password.com/export/)

**Comment by droidmonkey** [comment]
Looks like they completely removed all references to opvault in their documentation and in their app. You'll have to search reddit or somewhere to see if you can find the original location they are stored. An opvault is automatically created when you set 1Password to be locally unlockable.

**Comment by notDavid** [comment]
@droidmonkey 

1. I'm pretty sure the `opvault` / database is no longer stored locally at all. And by this i mean when using a 1Password account.

2. Perhaps this is still possible for users who did not opt-in to the 1Password cloud, and are still using local/iCloud accounts **while still using 1Password 7**.

Also i think in the latest 1Password 8, it is no longer possible to "**not** use a 1Password account". See for example [here](https://1password.community/discussion/129665/how-can-i-get-1password-8-on-mac-to-see-vault-in-icloud-used-by-iphone-and-ipad) :

> "1Password 8 only supports 1Password accounts, and doesn't support standalone vaults synced through iCloud, Dropbox, or other third party syncing services. Given this, you'd only be able to access your Personal vault in 1Password 8, not your Primary vault contained in iCloud. Generally speaking, we'd recommend migrating your data to your 1Password account"

**Comment by droidmonkey** [comment]
Yes looks like the 1PUX format had taken on new urgency. OPVault was a freaking mess anyway, 1PUX will be far easier to implement.

**Comment by DaveLeonard** [comment]
I agree, there is no other way to export data from 1Password 8 than the .1pux.

I found this gist maybe it could help you: [convert json from .1pux in csv](https://gist.github.com/kandhan-kuhan-t/7a74cb0f8d3de404cce7f97a6e8a13d6)

**Comment by Remus9oh7** [comment]
With the recent LastPass breach, I know several people wanting to move to KeePassXC from 1Password to remove the centralized attack surface. If there were a good time to have this available, now is it. Any updates / progress on this?

**Comment by droidmonkey** [comment]
The importer code is nearly done but not pretty or with test cases.

**Comment by Remus9oh7** [comment]
Sounds good, thanks for the update. I would offer to help, but I'm not sure I can - at least not with some hand holding. If there is a simple way to help, let me know. github.ujehm@simplelogin.com

**Comment by Skillkiller** [comment]
Any notable updates on the topic? Is there a public branch on this?

**Comment by droidmonkey** [comment]
You can start playing around with this branch but it does not implement everything for 1pux (icons and attachments) and introduces the new Import Wizard which is still WIP: https://github.com/keepassxreboot/keepassxc/tree/feature/1pux-import

![image](https://user-images.githubusercontent.com/2809491/219903080-305109a1-dbda-4c47-b4b3-9eed9ef071ec.png)

**Comment by tgwaste** [comment]
Can we get a test build for this please?

**Comment by Frodox** [comment]
@droidmonkey 🙏🏻

**Comment by droidmonkey** [comment]
Ok, here you go!! I signed this build so you know it came from me, you can check the keepassxc.exe properties to verify.

https://store.dmapps.us/KeePassXC-2.8.0-snapshot-Win64.zip

Instructions:

1. Open the new Import Wizard using `Database -> Import ... `
![image](https://user-images.githubusercontent.com/2809491/232631030-034611e4-1541-43fd-98dd-3d867e95b343.png)

3. Select the appropriate settings and your 1PUX file, press continue
![image](https://user-images.githubusercontent.com/2809491/232631152-a0e7c01e-e1ae-481a-876f-761ca2b0f88c.png)

5. Verify the import took and press done. Go through the new database creation wizard as usual.
![image](https://user-images.githubusercontent.com/2809491/232631092-c730683f-4bdc-4ace-a043-642da48cbd5a.png)

7. Verify your import, NOTE... attachments, icons, and some esoteric data elements are not implemented yet.
![image](https://user-images.githubusercontent.com/2809491/232631110-f5c7c449-f269-4d2c-a3ae-d81b5123d5f9.png)

**Comment by tgwaste** [comment]
Sorry.. I meant for mac.

**Comment by droidmonkey** [comment]
Mac Download: https://store.dmapps.us/KeePassXC-2.8.0-snapshot-x86_64.dmg

**Comment by tgwaste** [comment]
Works great, many thanks!

**Comment by bwl21** [comment]
is there also an build for apple silicon?

**Comment by phoerious** [comment]
You should be able to run x64 binaries also on ARM macs.

**Comment by bwl21** [comment]
@phoerious Indeed, this is what I do for now. the stuff looks great. I guess import of attachments will come. So I have to wait until then.

**Comment by isp** [comment]
@droidmonkey Can you share the linux version? Getting erros when using wine for the windows version you shared.

**Comment by ssbarnea** [comment]
While it did apparently load the 1pux file, I also got a big red banner "Writing the database failed: Could not save. Database has not been initialised!" and I am unable to save the loaded data, so basically "Save database as" is unable to succeed. I tried saving in different location same error.

I can live without attachment or icons, but I really need to make the switch as 1Password already froze my account.

**Comment by tgwaste** [comment]
You selected the OTHER import option right?

**Comment by ssbarnea** [comment]
@tgwaste Sorry, yep. I used "Import..." again and it works. Few minor bugs like default path being system root (read only), but the most important part worked. Hopefully by the end of the weekend I am KeePass converted.

**Comment by droidmonkey** [comment]
> default path being system root (read only),

What do you mean by this?

**Comment by ssbarnea** [comment]
The save file dialog does not have a valid default folder location and goes to "system root" on macos (basically the computer image), which is not really a location a user can save filters to.

A much better default value for the dialog would either `~/Documents` or even `~` as both of them are user writable.

![](https://sbarnea.com/ss/Screen-Shot-2023-05-14-14-55-36.95.png)

Please note that this bug is not liked to the 1pux import feature as it does reproduce with any new database creation. `machd` is the name of the system volume, clearly not something where a user would ever want to save data to.

**Comment by droidmonkey** [comment]
We do default to the user home directory. However we also remember the last used directory in the local config file. I think you have a junky setting in there that is causing your problem. It could be that you had used a directory that no longer exists and Qt then sends you to the file system root.

**Comment by robertaramar** [comment]
Is there a feature-branch-build for this for Linux somewhere? I'm also currently bothered by a locked 1password account and would like to transfer my stuff into KeePassXC. I tried today's snapshot (2.8.0) but that didn't offer the import wizard, yet.

**Comment by droidmonkey** [comment]
Yes, use this branch, I made lots of updates this weekend (still working on Bitwarden). I fixed attachment and icon importing for 1Password. https://github.com/keepassxreboot/keepassxc/tree/feature/1pux-import

**Comment by robertaramar** [comment]
OPUXReader.cpp#178 throws an error, input to qWarning is not a string.

**Comment by robertaramar** [comment]
I have entries with attachements which properly extract from the 1pux-file when unzipping manually. However, they do not appear when imported.
Shall I create a new issue for that?

**Comment by droidmonkey** [comment]
No don't make a new issue this is still under development. In order for me to figure out what is wrong I essentially need an excerpt from your export.data file in the 1pux/zip. If you are willing to find and provide the data I can fix the issue. 1PUX is barely documented... most of my work is based on a sample 1Password vault I made myself.

**Comment by robertaramar** [comment]
I extracted the entry with the attachments and obfuscated everything with value to me.
If you want me to re-test, please, let me know.
[test-with-attachment.1pux.zip](https://github.com/keepassxreboot/keepassxc/files/11535849/test-with-attachment.1pux.zip)

**Comment by droidmonkey** [comment]
Awesome thank you, this is the part I need to implement:

```
 "fields": [
                      {
                        "title": "",
                        "id": "ikfnyo5rc6wkjw3gsrjibnnl3a",
                        "value": {
                          "file": {
                            "fileName": "1644476070286-9706796e-ca0f-4e99-bcf4-79fd987d0baf.jpg",
                            "documentId": "m6ihzs7pozed5hn2o3knlmayfe",
                            "decryptedSize": 65534
                          }
                        },
```

**Comment by droidmonkey** [comment]
@robertaramar I added support for the file fields and it worked with your test 1pux. Can you give it a go with your real vault? 

Anything else seem amiss?

**Comment by robertaramar** [comment]
It works like a charm, Jonathan. Thank you very much.

**Comment by jonbreen2000** [comment]
Worked for me too! Thank you Jonathan !

**Comment by droidmonkey** [comment]
I'll get this PR buttoned up and posted for merging this weekend. Excited to bring this capability to the table.

**Comment by jby** [comment]
> @tgwaste Sorry, yep. I used "Import..." again and it works. Few minor bugs like default path being system root (read only), but the most important part worked. Hopefully by the end of the weekend I am KeePass converted.

I just downloaded the 2.8 for macOS and I'm getting this same error:
`Writing the database failed: Could not save. Database has not been initialised!`
No matter how many times I try to re-do the import from my 1pux-file, I'm unable to save it as a kbdx-file... :(

**Comment by mobiuscog** [comment]
@droidmonkey I just wanted to add a huge **Thank You** for this PR. It allowed me to migrate easily on Linux, after building, although I didn't have any special requirements.

The only problem I noticed was that TOTP 'keys' in 1Password, often are stored with additional metadata before the secret, so they need to be truncated to only the secret in KeepassXC (in 1Password, they often have some oauth/domain meta as a prefix, that ends with 'secret'). If everything at the start including 'secret' is removed, the remaining key works just fine - at least in my simple testing.

Not _all_ TOTP entries had this (I'm unsure why) so I had to check each manually.

**Comment by droidmonkey** [comment]
We read and store the otpauth url schema. Can you paste an example with a redacted secret?

I've also made several improvements to this code and haven't pushed them yet. While I was at it here I implemented Bitwarden unencrypted and encrypted json import as well.

**Comment by mobiuscog** [comment]
> We read and store the otpauth url schema. Can you paste an example with a redacted secret?

I don't have them any more, as I converted them all manually as I was switching over, and clearing down my 1password.

There were a number that had otpauth in the name, along with domain information and then the actual key, but the codes generated were wrong until I changed the key to just be the secret. I was checking those with the 2.7.5 release (I just used the PR build to do the import) so perhaps that makes a difference.

Maybe I did something else incorrect.

**Comment by mobiuscog** [comment]
@droidmonkey I found some backups. An example in the CSV export would be:
`otpauth://totp/Dropbox:redactedemail%40redacteddomain.redactedtld?secret=XXXXXXXXXXXXXXXXXXXX&period=30&algorithm=SHA1&digits=6&issuer=Dropbox`

If I click on 'Setup TOTP' and look at the secret key, it shows:
`otpauthtotpDropboxredactedemailredacteddomainredactedtldsecretXXXXXXXXXXXXXXXXXXXX`
which fails as the secret is just XXXXXXXXXXXXXXXXXXXX

If I edit the entry, under advanced, it shows:
`otpauth://totp/Dropbox:redactedemail%40redacteddomain.redactedtld?secret=otpauthtotpDropboxredactedemailredacteddomainredactedtldsecretXXXXXXXXXXXXXXXXXXXX%3D&period=30&digits=6&issuer=Dropbox`

The %3D at the end of the 'advanced' secret is also curious. Hopefully that helps.

**Comment by droidmonkey** [comment]
Looks like we need to sometimes do a url decode on load. The reason it is not working is because the %40 should be an @

This is what it should look like: `otpauth://totp/Example:alice@google.com?secret=JBSWY3DPEHPK3PXP&issuer=Example`

**Comment by Baki35** [comment]
Can we get a new test build for this please? 
Already using the last test build (thanks for that) for my 1Password exports but was wondering if there is a newer version?
