### ISSUE TITLE
Ability to duplicate a group of records

### ISSUE THREAD

**Issue by thejvmshid** [keepassxreboot/keepassxc#7547]
Hi guys!
First of all, thank you for your product.
Sometimes there is a need to duplicate multiple entries between directories. If there are 1-4 of them, it is not difficult to duplicate and transfer, although it is not convenient, to duplicate and transfer each entry. It would be great to be able to duplicate several records at once by grouping (highlighting). Or you can, for example, by holding the control keyboard, re-write to another directory, which subsequently automatically duplicates the records to another directory.

Best regards,
Jamshid Tursunov

**Comment by phoerious** [comment]
See #7548
