### ISSUE TITLE
Ability to duplicate a directory

### ISSUE THREAD

**Issue by thejvmshid** [keepassxreboot/keepassxc#7548]
Hi guys!

Often there is a need to duplicate entire directories, since the content (records) are the same. It is very painful when there is no such possibility. You have to create a directory, clone entries and drag and drop into a new folder.

Best regards,
Jamshid Tursunov

**Comment by phoerious** [comment]
You can hold Ctrl while dragging the folder as if you were to move it to another parent directory.

**Comment by thejvmshid** [comment]
Thank you for navigation.
It seems to me that there should also be an item in the drop-down menu that does exactly the same thing. because it is difficult to intuitively guess, or you have to climb into the documentation. it would be great if such an item was present in the drop-down menu.

Best regards,
Jamshid Tursunov

**Comment by droidmonkey** [comment]
2.7.0 has a clone directory feature. Right click the one you want to clone
