### ISSUE TITLE
Databases comparison / programmatic access to database

### ISSUE THREAD

**Issue by esantoro** [keepassxreboot/keepassxc#7549]
Hello,
I'm using Nextcloud to sync files across my computer, however it seems that there is a conflict among some files, two of which are versions of my keepassxc database file.

I was wondering if there's a canonical way to compare two databases in order to see what has changed. 

Otherwise, is there a way to see the latest changes to a sincle database? So far I've seen a health check, but that doesn't work for me, at minimum a change log would help me.

Otherwise: is there's a library I can use with some programming language so that I can hack together some kind of comparison? The bare minimum would be to be able to know which entries differ in any way (I can then inspect them manually since I've got the database passwords).

Thanks in advance!
-- 
Emanuele

**Comment by droidmonkey** [comment]
Use the keepassxc-cli merge command, it will show you what has changed. You can also do the merge in the gui, search for `*` and sort by modified date. This has been requested in another issue so closing this one as duplicate.

**Comment by esantoro** [comment]
Hello @droidmonkey and thank you for your reply. I did use `keepass-cli merge` command successfully a couple of times now.

However, I often see a number of log messages like this:

```
Entry of Udemy for business[XXXXXXXXXXXXX] contains conflicting changes - conflict resolution may lose data!
```

Should I get worried?  Is there anything to fix and if so, how do I fix these message?

Thank you,
-- 
Emanuele

**Comment by droidmonkey** [comment]
That message can be ignored. It gets triggered sometimes because of the custom data modified time comparison but no actual data is lost. Ran it through the debugger.
