### ISSUE TITLE
Wrong keyboard layout under X11

### ISSUE THREAD

**Issue by hydrargyrum** [keepassxreboot/keepassxc#7551]
## Overview

I have 2 keyboard layouts (configured using my desktop environment): french azerty and french bépo (dvorak-like).
When I use the autofill feature of keepassxc, it types stuff in an incorrect layout even if I'm using the secondary layout.

I'm guessing the same issue would occur with qwerty and dvorak.

## Steps to Reproduce

1. Have 2 keyboard layouts configured
2. Switch to secondary layout
3. Start keepassxc
4. Use autofill on any credential (ctrl-shift-v)

## Expected Behavior
The credentials are correctly filled.

## Actual Behavior
The credentials are incorrectly filled.

## Context

KeePassXC - Version 2.6.6
Revision : 9c108b9

Operating System: Debian Linux
Windowing System: X11

For example:
- in bépo, keysym "a" is on keycode 38
- in bépo, keysym "b" is on keycode 24
- in azerty, keysym "a" is on keycode 24

If a credential involves letter "a" and I'm using bépo, keepassxc will type "b", as if keepassxc used the keycode of the wrong layout, leading to a wrong keysym used.

In contrast, "xdotool type a" does the right thing.

**Comment by droidmonkey** [comment]
This is fixed in 2.7.0
