### ISSUE TITLE
Keepassxc fails to connect to database.

### ISSUE THREAD

**Issue by WoefulWrecker** [keepassxreboot/keepassxc#7552]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

Firefox and LibreWolf are having issue with KeePassxc (Version 1.7.11), I can install KeePassxc (Version 1.7.11) in the add-on extension, however it will not connect to the macOS KeePassxc.app (Version 2.6.6) by the connect button under "Connected Databases". Both Chrome and Brave have no issue with current version of Keepassxc.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1.  Install KeePassxc (Version 1.7.11) in both Firefox and LibreWolf
2.  Go to KeePassxc (Version 1.7.11) toolbar, click for the drop box.
3.  Go to Setting, the to section Connected Databases and click "Connect".

## Expected Behaviour
[NOTE]: # ( Tell us what you expected to happen )

Pop up Box asking for a name or label to apply to a new connection

## Actual Behaviour
[NOTE]: # ( Tell us what actually happens )

Nothing

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - unknown
KeePassXC-Browser - 1.7.11
KeePassxc.app (Version 2.6.6)
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
System Version:	macOS 11.5.1 (20G80)
Kernel Version:	Darwin 20.6.0
Boot Volume:	        macOS

Name 	               Firefox
Version                  98.0.1
Build ID                  20220313140707

Name 	               Firefox (LibreWolf)
Version                   98.0-1
Build ID                   20220309175145

**Comment by Redback813** [comment]
Fixed issue

**Comment by WoefulWrecker** [comment]
Fixed issue:

https://gitlab.com/librewolf-community/browser/macos/-/issues/51
