### ISSUE TITLE
Copy or auto-type additional attributes

### ISSUE THREAD

**Issue by schtibal** [keepassxreboot/keepassxc#7557]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
Ability to do either copy and/or autotype of additional attributes for ease of entry into web forms. 

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
For example, I have my credit card details stored in an entry, with the card number and CCV protected. I'd love to me able to click an icon next to the field to either copy my cc number to the clipboard, or to autotype it like a password.
Currently, I need to edit the entry, go to the Advanced tab, reveal the protected fields, then select, copy and paste. 

Aside from being a 7+ click operation, it is also less secure, as the ctrl-c clipboard copy does not take advantage of KeePassXC's clipboard timeout feature.

**Comment by droidmonkey** [comment]
Install 2.7.0. Then you can define additional Auto-Type sequences by going to the Auto-Type tab in the entry, add a window association, leave the window title blank, then set the custom sequence to be `{S:attribute-name}`. Now your advanced attributes will appear in the pick list for Auto-Type. 

You can easily copy additional attributes by right clicking the entry and go to the attributes submenu.

**Comment by northen-mindset** [comment]
> Then you can define additional Auto-Type sequences by going to the Auto-Type tab in the entry, add a window association, leave the window title blank, then set the custom sequence to be `{S:attribute-name}`. Now your advanced attributes will appear in the pick list for Auto-Type.

Where exactly should I see the option to auto-type an additional default sequences? I created one with an empty title, but cannot see this additional sequence neither in the entry context menu, nor in the toolbar dropdown, nor in the Global Auto-Type dialog.

Also, the documentation does not specify whether spaces in the attribute name should be escaped in the `{S:attribute name}` syntax. Can you please suggest?

KeePassXC v2.7.4
I've read https://keepassxc.org/docs/KeePassXC_UserGuide.html#_auto_type thoroughly.

**Comment by droidmonkey** [comment]
You know you are right, I have no idea how the (empty) works, I think there is a bug. You don't need to escape any characters in between the { } brackets.

**Comment by northen-mindset** [comment]
> I have no idea how the (empty) works, I think there is a bug.

Seems that #7391 has removed the support for empty titles in Window Assiciations and hence invalidated the following documentation: 

> Leave the window title blank to offer additional default Auto-Type sequences, such as custom attributes. 
> — https://github.com/keepassxreboot/keepassxc/blob/develop/docs/topics/AutoType.adoc

I've checked now, after changing the empty title to `*` this additional sequence appeared in the global auto-type dialog, but not in the entry context menu or the toolbar dropdown.

Perhaps, the documentation should have been changed in #7391.

**Comment by droidmonkey** [comment]
Nothing additional will appear in the entry context menu or toolbar dropdown, that isn't a feature.

I see what is happening now. If you leave the window title (empty) then the sequence will only show up when you do a SEARCH for the window in the auto-type select dialog. That is hyper confusing and this behavior makes no sense to me.

**Comment by michaelk83** [comment]
Shouldn't this be classified as an open bug, then?

**Comment by droidmonkey** [comment]
This is unrelated to this ticket, see below.
