### ISSUE TITLE
Support safe sharing of passwords

### ISSUE THREAD

**Issue by digulla** [keepassxreboot/keepassxc#7559]
## Summary
Allow to safely share credentials between a group of individuals.

The current approach (XML export) has two drawbacks:

- All entries are exported
- The exported file is plain text. Even if you delete the file afterwards, the passwords remain on the disk somewhere.

Rough outline of the process:

- Recipient creates an "import request" (basically a key pair with a random passphrase stored in the DB).
- He send the request (just the public key part) to supplier
- Supplier selects a subset of all entries in the DB for export
- During export, the public key is used to encrypt the dump.
- File is sent to recipient
- During import, the private key is located in the DB and the file is decrypted
- Recipient gets a list of entries that can be imported. Default is "import nothing" (safe default) or "name, user and password".

Use cases:

- Sharing credentials for test databases between software developers
- Support sharing initial password with users
- Sharing production passwords between DB and server admin

**Comment by droidmonkey** [comment]
https://keepassxc.org/docs/KeePassXC_UserGuide.html#_database_sharing_with_keeshare

How you decide to communicate the credentials to the shared database is up to you.
