### ISSUE TITLE
Allow to use the user/system theme icons for actions.

### ISSUE THREAD

**Issue by ghost** [keepassxreboot/keepassxc#756]
Hi, i installed the .deb for the version 2.2.0  (i used to use the mono-based keepass2) and noticed some icons on the toolbar and menu used my user icon theme (breeze-dark) and others don't, for example the "document-new" icon uses the breeze theme but the "entry-new" don't. Then i downloaded the code just for curiosity and by deleting a "false" argument on the calls to the function that loads the icon i made all the action icons in that file to use my user/system theme. I just changed lines like:
`m_ui->actionChangeMasterKey->setIcon(filePath()->icon("actions", "database-change-key", false));`
to:
`m_ui->actionChangeMasterKey->setIcon(filePath()->icon("actions", "database-change-key"));`

Because the default KDE theme seems to cover well most if not all of the icons i changed i think it looks better now. So i mostly opened this bug to ask if there's any problem to allow the program to load the icons from the user theme at least on linux for future releases. Thanks in advance for your attention.

Before:
![screenshot_20170706_183114](https://user-images.githubusercontent.com/29102827/27937261-591705aa-627b-11e7-8db1-891b8909ff70.png)

After:
![screenshot_20170706_184646](https://user-images.githubusercontent.com/29102827/27937279-7a9c5fe0-627b-11e7-9203-5b9157fd6d38.png)

This is the diff file:
[icons.txt](https://github.com/keepassxreboot/keepassxc/files/1129559/icons.txt)

KeePassXC - 2.2.0
Operating system: KDE Neon (Ubuntu 16.04)

**Comment by phoerious** [comment]
I'm really not sure why KeePassXC is forcing custom icons for all those actions. Apparently some weird KeePassX legacy.
We generally need new icons, but using system icons where possible is of course a good idea, too. However, I'm not certain if the icons for "new entry", "edit entry" and "delete entry" are ideal. I believe our current icons are more or less custom-made icons which we took over from KeePassX. The rest are all Oxygen icons (i.e. KDE4), so it's no surprise the new KDE 5 Breeze theme covers most of them.

**Comment by libookami** [comment]
I see, thanks a lot for your answer. It's a matter of subjectivity, i personally like the breeze icons a lot more than the ones shipped with the program but i could understand if you guys prefer to use custom icons. Regarding the themes i guess if the user decides to use an icon theme with non-intuitive icons is up to that person, i guess in general the default themes from the main desktop environments should be sane. I personally would like to use the icons from my theme but it's up to you guys. Keep doing a great work!

**Comment by magkopian** [comment]
I think there should be a setting so the user can decide whether they want to use the system icons, or the default icons included with the software. The reason for that, is because depending the icon theme you are using, some icons may not blend very well with the interface of the program or simply you might not like how your theme icons look on the interface of the program.

**Comment by phoerious** [comment]
Made a few experiments. Kinda like it. For the password generator I used the Breeze equivalent of the Oxygen "roll" icon we are using at the moment.

![screenshot_20170707_022134](https://user-images.githubusercontent.com/911270/27937944-12a14082-62bb-11e7-857e-1bdba42e6645.png)
![screenshot_20170707_022109](https://user-images.githubusercontent.com/911270/27937949-16169cda-62bb-11e7-8b95-3792df75e718.png)
![screenshot_20170707_022122](https://user-images.githubusercontent.com/911270/27937951-17ea45de-62bb-11e7-89f7-0f9ad6d1ab42.png)

@droidmonkey @TheZ3ro @weslly @louib What do you think? We could IMHO even replace the shipped icons with Breeze icons, so the default icons on non-KDE platforms look better out of the box. We would also solve HiDPI icon issues such as #548 then.

**Comment by libookami** [comment]
Yep, that's what i'm talking about. I like that a lot more.

**Comment by phoerious** [comment]
BTW I'm against making it an option. Either we force users to use our icons or we rely on the system theme. Both are sane choices Having an option for that is rather silly, though.

**Comment by magkopian** [comment]
@phoerious Relying on the system icon theme only is not a good idea in my opinion, because icons may be missing and this results to a mixed icon interface which may look really bad, or like in my case cause confusion (I constantly mix up the save and open buttons because they look very similar).

![keepassxc2](https://user-images.githubusercontent.com/1429068/27938322-ecaeee00-62c5-11e7-88b9-f0b6362abbd2.png)

If you think having an option is not a good idea, then I think the best would be to force the default icons of the program.

**Comment by droidmonkey** [comment]
I like the breeze icons, but there are certainly other icon sets that are fantastic. Perhaps it would be wise to use different icons are Mac/Linux/Win since each platform has different ways to represent actions. Just thinking outside the box here. I am of the opinion that we could ship different icon themes that are all high quality but serve different system themes.

**Comment by libookami** [comment]
I consider the positive side of allowing the user/system icon theme is that it helps for the application to look integrated (or at least not alien) with the rest of the system but that's just my opinion of course.

**Comment by phoerious** [comment]
@magkopian if you are having trouble distingusinging those icons you should probably change your icon theme. Icon names in Linux are more or less standardized and if we don't abuse icons for purposes they were not made for, we should get consistent results. Especially standard options such as save and open *SHOULD* IMHO adhere to platform standards and not come with looks the user isn't used to. 

Therefore I also strongly agree with @droidmonkey upon using different icons for different platforms (if we can find appropriate open source themes or manage to use the system's native icons, E.g from shell.dll). If we really change the shipped default icons, we should defer this to 2.3.0,though.

**Comment by magkopian** [comment]
@phoerious I'm using the [Papirus](https://github.com/PapirusDevelopmentTeam/papirus-icon-theme) icon theme which I believe is one of the most popular icon themes out there, and I really like how the application icons look in combination with the Arc theme on Gnome. The interface of KeePassXC is honestly the only thing I'm having issues with, so in my case I'd much rather use the default icons of the program than the system icons.

I believe that @droidmonkey has a point here though, shipping with different icon themes and allowing the user which one to choose is the best way to go in my opinion. This is also exactly what Filezilla does.

![filezilla_theme](https://user-images.githubusercontent.com/1429068/27960960-ce51c6ba-6335-11e7-884f-8641f4be82e0.png)

**Comment by weslly** [comment]
>Made a few experiments. Kinda like it. For the password generator I used the Breeze equivalent of the Oxygen "roll" icon we are using at the moment.
>![screenshot_20170707_022134](https://user-images.githubusercontent.com/911270/27937944-12a14082-62bb-11e7-857e-1bdba42e6645.png)

@phoerious It looks so much better! Would be nice to replace the current shipped icons with those.

And while we are at it, the search icon should have an small `v` caret to indicate you can click it to change search settings.

**Comment by phoerious** [comment]
I know there are apps which allow the user to change the icon theme. But I still find it kind of silly. Every other platform comes with standard icons, which apps are expected to use (especially macOS). Custom icons are only used for things for which there is no default icon or if the whole app somehow as a custom design (Adobe products, for instance). Why should that be different on Linux? The fact that the Papirus icons are barely recognizable is definitely a problem of that icon set and really suggest you file a bug report there. I do agree that the save and open icon are rather bad whereas the rest looks decent. But those are standard icons and should serve as such. If they don't, the icon theme is bad.

**Comment by TheZ3ro** [comment]
My two cents here: I think we should ship one set of icon (the KDE-Qt default like we are doing right now) and let the OS replace all the icons if the user is using a different icon theme.
Shipping >1 icon set is just adding complexity to the application. I don't like the system/user-icon option neither

**Comment by phoerious** [comment]
I don't think we actually need to ship more than one icon theme. We only need a more intelligent platform-specific icon lookup. On Linux it works out of the box on most systems, only macOS and Windows always fall back to our default icons. However, even those platforms come with standard icons which applications can use.

**Comment by weslly** [comment]
macOS standard icon set is actually quite limited https://developer.apple.com/macos/human-interface-guidelines/icons-and-images/system-icons/

**Comment by phoerious** [comment]
Well, there is probably no New/Open/Save, because those actions tend to be in the menu without an icon. But there are other icons that are quite common and users expect them instead of something custom-made.

**Comment by hifi** [comment]
My opinion is that having a consistent icon theme between platforms helps users to navigate the program and keeps it familiar. Even more so when you mix them in your daily routine. 

It's also easier to make or read instructions when the screenshots have the distinct icons everywhere. 

As it has been said no platform provide enough platform specific icons that would be immediately understood by the user it would be better to stick with custom ones but not have unique set for each platform.

**Comment by k4r7u** [comment]
I think hardcoded icons are actually a really bad idea (at least on a Linux system).
Maybe check for icons in the hicolor icons folder and if no are present use hardcoded fallback icons.
Or place the needed icons in the system icons folder during the installation like a lot other applications are doing it.
Below are screenshots of KeePassX with overwritten icons and KeePassXC on elementary OS.
![keepassx](https://user-images.githubusercontent.com/8782287/31275087-1574e52a-aa96-11e7-9bd5-ef086cc4e7a7.png)
![keepassxc](https://user-images.githubusercontent.com/8782287/31275088-15924430-aa96-11e7-9e1f-9640d1898e3f.png)

The same issue exists for me with the tray icon, which looks totally out of place.
Maybe provide an option for "power users/experts" to overwrite the icons in some way.
If adding an option to the settings menu is not wanted, what about a command line flag like --use-system-icons?
At the moment, while I prefer the advanced feature set of KeePassXC, not being able to modify the used icons is "forcing" me to still use KeePassX.

This is not meant as criticism as I totally honor the effort put into KeePassXC, but more as an idea to make KeePassXC more usable and better integrated in different distros.

**Comment by TheZ3ro** [comment]
Seems strange to me that KeePassX is working and KeePassXC isn't... I need to dive more into the code

**Comment by droidmonkey** [comment]
The whole icon loading/use code needs an overhaul
