### ISSUE TITLE
Invalid KeePassXC-2.7.0 Portable ZIP archive link

### ISSUE THREAD

**Issue by ogmios-voice** [keepassxreboot/keepassxc#7563]
On https://keepassxc.org/download/ the [Portable ZIP archive](https://github.com/keepassxreboot/keepassxc/releases/download/2.7.0/KeePassXC-2.7.0-Win64-Portable.zip) link is invalid.
On the [release page](https://github.com/keepassxreboot/keepassxc/releases) there's
no **KeePassXC-2.7.0-Win64-Portable.zip** (https://github.com/keepassxreboot/keepassxc/releases/download/2.7.0/KeePassXC-2.7.0-Win64-Portable.zip)
only **KeePassXC-2.7.0-Win64.zip** (https://github.com/keepassxreboot/keepassxc/releases/download/2.7.0/KeePassXC-2.7.0-Win64.zip).

**Comment by phoerious** [comment]
Fixed.
