### ISSUE TITLE
System Error: VCRUNTIME140_1.dll was not found

### ISSUE THREAD

**Issue by GhostWolf1512** [keepassxreboot/keepassxc#7564]
Updated to version 2.7.0 on Windows 11. When I try to lunch KeePassXC It throws an error saying "The code execution cannot proceed because VCRUNTIME140_1.dll was not found. Reinstalling the program may fix this problem." I have done a clean install and error is still showing.

**Comment by GhostWolf1512** [comment]
This is a very important Issue because I cannot get to my passwords now.

**Comment by phoerious** [comment]
Try installing the appropriate runtime library (x64) from here: https://docs.microsoft.com/en-US/cpp/windows/latest-supported-vc-redist?view=msvc-170#visual-studio-2015-2017-2019-and-2022

**Comment by GhostWolf1512** [comment]
After installing the library, I am able to open KeePassXC.

**Comment by phoerious** [comment]
@droidmonkey May need to check if this is installed and if not, install it alongside KeePassXC.

**Comment by droidmonkey** [comment]
What version of windows are you running? This hasn't been needed in a long time.

**Comment by GhostWolf1512** [comment]
Windows 11 Version 21H2 OS build 22000.556

**Comment by ChiaYen-Kan** [comment]
i try to upgrade to version 2.7.0 on Windows 7 and install VC runtime library,
but it can't work, and display miss "api-ms-win-core-kernel32-legacy-l1-1-0.dll"
how to run version 2.7.0 on Windows 7 ?

**Comment by droidmonkey** [comment]
Windows 7 is end of life for 2 years, we do not support running on that operating system.

**Comment by LRystrom** [comment]
I am having problems with new update as well. When I attempt to run KeepassXC I see a window momentarily appear on the screen then it disappears. The task manager shows that KeepassXC is still running. I tried installing the VC redist off the https://keepassxc.org/blog/2022-03-21-2.7.0-released/ page. After accepting an offer to repair, KeepassXC still was not coming up.

OS: Windows 10 Enterprise 20H2.

I uninstalled new the KeepassXC and then installed version 2.6.6 which runs with no problems. This makes me think it isn't a minimize-to-tray/minimize-on-startup issue.

**Comment by phoerious** [comment]
Sounds like you have minimize to tray enabled together with minimize on startup.

**Comment by Fernerph** [comment]
I had the same problem as the original issue together with
VCRUNTIME140.dll
MSVCP140.dll
on windows 10, version 10.0.19042 Build 19042. 

Removing three old runtime library versions from my system (no words for that) and installing the latest version as mentioned by @phoerious solved it for me too. Thanks for the help!

**Comment by jake9696** [comment]
I had the same problem on Windows 10 Home (version 21H2 build 19044.1586) and installing the visual studio runtime linked by [phoerious](https://github.com/phoerious) in their comment fixed it for me.

**Comment by FoxP** [comment]
I have following error on Windows 8.1 when starting KeepassXC : 

![image](https://user-images.githubusercontent.com/16615901/159977373-18a1928d-aed9-413b-8567-9ef8eb653887.png)

![image](https://user-images.githubusercontent.com/16615901/159979097-b191d35c-6f15-42f8-a524-904a943428d0.png)

**Comment by tobikster** [comment]
I faced the same issue (missing VCRUNTIME140.dll) while updating KeepassXC on Windows 10 Home.

My OS configuration:
- Version: 20H2
- Compilation: 19042.1526
- Features: Windows Feature Experience Pack 120.2212.4170.0

**Comment by phoerious** [comment]
Windows 7 and 8.1 are unsupported and will not work. @droidmonkey created a legacy build for those, which you can download from the GitHub releases page, but we won't support those indefinitely. https://github.com/keepassxreboot/keepassxc/releases/tag/2.7.0

**Comment by 0xpr03** [comment]
To clarify: Same issue here, completely new win10 installation, fresh MSI installer & portable. Failing due to various MSVC redist dlls missing.
Downloading the 2022 x64 [version](https://aka.ms/vs/17/release/vc_redist.x64.exe) fixed it for me.
