### ISSUE TITLE
Auto-Type shortcut not working on macOS when 'Always ask before performing Auto-Type' is deselected in 2.7.0

### ISSUE THREAD

**Issue by lollyP** [keepassxreboot/keepassxc#7565]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

Auto-Type via keyboard shortcut does not work in 2.7.0 on macOS when 'Always ask before performing Auto-Type' is deselected. The workaround is to select Perform Auto-Type from the menu or from the right-click dialog.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. (Following a clean install of KeePassXC)
2. Uncheck 'Always ask before performing Auto-Type' in Settings -> Auto-Type
3. Try to enact Auto-Type sequence by pressing the keyboard shortcut (in this case shift-cmd-v)

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

The Auto-Type sequence is performed

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

The Auto-Type sequence is not performed

## Context
[NOTE]: # ( Give us any additional information you may have. )

For confirmation of the problem, the test was performed on a clean install of KeePassXC

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.0
Revision: d7a9ef4

[NOTE]:
Operating System: macOS, v 12.3 (Monterey)

**Comment by yulet** [comment]
I have the same issue.

Version 12.3 (21E230)
MacBook Pro (16-inch, 2021)
Apple M1 Pro

KeePassXC - Version 2.7.0
Revision: d7a9ef4

Qt 5.15.2
Debugging mode is disabled.

Operating system: macOS 12.3
CPU architecture: arm64
Kernel: darwin 21.4.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 2.19.1

**Comment by droidmonkey** [comment]
This is most likely the same problem corrected by this PR: https://github.com/keepassxreboot/keepassxc/pull/7588

Will be in 2.7.1

**Comment by yulet** [comment]
Tried a snapshot build, it is working.

KeePassXC - Version 2.7.0-snapshot
Build Type: Snapshot
Revision: eac60b3

**Comment by lollyP** [comment]
> Tried a snapshot build, it is working.
> 
> KeePassXC - Version 2.7.0-snapshot Build Type: Snapshot Revision: [eac60b3](https://github.com/keepassxreboot/keepassxc/commit/eac60b3228b936c0d8bb0cb3152f6a721e1c0185)

Confirmed. Many thanks, @droidmonkey, for all your work on this project.

**Comment by sultanahamer** [comment]
When can we expect a release of this? This is a major usability issue that I am facing everyday after upgrade. Only work around I see work is by right clicking on the entry and selecting auto type.

Having that confirmation of auto type is more like a work around only for web pages but for desktop apps like rambox, its not working. Only right click and selecting auto type is the only option working.

**Comment by droidmonkey** [comment]
This weekend. Nothing stopping you from redownloading 2.6.6 and using that in the interim. You can also download a snapshot at https://snapshot.keepassxc.org

**Comment by sultanahamer** [comment]
@droidmonkey thanks for the quick confirmation. Will wait for it if its this weekend.
