### ISSUE TITLE
Windows Hello verification window does not appear upon first time unlocking after start

### ISSUE THREAD

**Issue by akuropka** [keepassxreboot/keepassxc#7570]
## Overview
Add support for Windows Hello (Quick Unlock) (https://github.com/keepassxreboot/keepassxc/pull/7384)

## Steps to Reproduce
1. Ensure Quick Unlock is enabled in Settings / database was once unlocked with Quick Unlock
2. Close KeePaxxXC
3. Restart KeePassXC

## Expected Behavior
The Windows Hello prompt appears for fingerprinting or PIN entry (similar to screenshot one in the mentioned pull request).
Atfer succeeding Windows Hello verification the database is unlocked.

## Actual Behavior
The common Unlock dialogue of KeePassXC appears (for entering password, etc.).
After unlocking within KeePassXC the Windows Hello prompt appears in addition and requires verification.

## Notes
If I lock afterwards the database in KeePassXC the unlock dialogue appears with the option using Windows Hello (similar to screenshot two and three in the mentioned pull request).

It is not clear to me where to set up the fourth topic in the pull request ("Don't set database unlock dialog as always on top.") or if it is of relevance here.

## Context
KeePassXC 2.7.0
Revision: d7a9ef4

Operating System: Windows
Version: 10.0.22579.1

**Comment by droidmonkey** [comment]
This is by design, we don't remember your quick unlock if you close the database or keepassxc. That will be implemented in a future release.

**Comment by akuropka** [comment]
Well noted, yet, it would have been helpful if this would have been mentioned in the settings (or at least in the PR) since I may be not the only one wondering. Keep up the good work!

**Comment by droidmonkey** [comment]
It's in the documentation: https://keepassxc.org/docs/KeePassXC_UserGuide.html#_quick_unlock

I can see how it does not _explicitly_ say you need to do a full unlock when relaunching the application. Either way we should be clearing that up in the next release or so.

**Comment by Splarkszter** [comment]
Just one question. Why is it enabled by default?

Windows Hello (and Touch ID too) have so many backdoors that even your neighbour can unlock it.

**Comment by droidmonkey** [comment]
Do you have a reference for that allegation?

**Comment by Splarkszter** [comment]
It's microsoft. lmao

**Comment by frostynumeral** [comment]
> This is by design, we don't remember your quick unlock if you close the database or keepassxc. That will be implemented in a future release.

I'd like to ask when are you planning this future release.

**Comment by cwittstock** [comment]
I know it's been two years. Nevertheless, I'd like to ask again: will it soon be possible to unlock the database without entering a password, using only Windows Hello?

**Comment by phoerious** [comment]
Not until 2.8 comes out.
