### ISSUE TITLE
KeePassXC 2.7 Access Request memory failing

### ISSUE THREAD

**Issue by CrfzdPQM6** [keepassxreboot/keepassxc#7572]
After upgrading from 2.6.6 to 2.7.0 on ArchLinux I'm encountering some unexpected behaviour.

I use `secret-tool` to access a secret stored in the KeePassXC secret service. However, every time I try to use the secret-tool to access the same secret, I am prompted to respond to the Access Request dialog. Each time, I click "Allow All & Future", but it keeps coming back. My naive guess is that it has something to do with the changing name of the requestor, e.g.:
```
/usr/bin/secret-tool (PID: 14337) is requesting access to the following entries:
...
```
(where the PID changes each time). Is that why KeePassXC keeps prompting me for a new permission each time?

Thanks for all the work!

**Comment by nbarrientos** [comment]
See https://github.com/keepassxreboot/keepassxc/issues/7571

**Comment by CrfzdPQM6** [comment]
:laughing: you beat me to it by 5 minutes. Thanks, @nbarrientos ! Glad someone else encountered the same problem. Will close this and watch your issue...
