### ISSUE TITLE
No default collection exposed for secret service in 2.7.0

### ISSUE THREAD

**Issue by jonasc** [keepassxreboot/keepassxc#7575]
## Overview
After updating to 2.7.0 the secret service integration does not seem to expose a default collection anymore (worked before).

## Steps to Reproduce
(1) In Python try this
~~~python
import secretstorage
conn = secretstorage.dbus_init()
collection = secretstorage.get_default_collection(conn)
~~~
(2) Or run in a shell
~~~bash
dbus-send --session --type=method_call --print-reply \
    --dest=org.freedesktop.secrets /org/freedesktop/secrets/aliases \
    org.freedesktop.DBus.Introspectable.Introspect
~~~

## Expected Behavior
(1) `collection` should contain the default (and only open) collection.
(2) Information about the default collection should be printed.

## Actual Behavior
(1) An error is thrown: `DBusErrorResponse: [org.freedesktop.DBus.Error.UnknownObject] ("No such object path '/org/freedesktop/secrets/aliases/default'",)`
(2) An error is shown: `Error org.freedesktop.DBus.Error.UnknownObject: No such object path '/org/freedesktop/secrets/aliases'`

## Context

Obtaining collections more directly (by name) works.
~~~bash
$ dbus-send --session --type=method_call --print-reply \
    --dest=org.freedesktop.secrets /org/freedesktop/secrets/collection/jonas \
    org.freedesktop.DBus.Introspectable.Introspect

method return time=1647950765.773902 sender=:1.222 -> destination=:1.362 serial=448 reply_serial=2
   string "<!DOCTYPE node PUBLIC "-//freedesktop//DTD D-BUS Object Introspection 1.0//EN"
"http://www.freedesktop.org/standards/dbus/1.0/introspect.dtd">
<node>

<interface name="org.freedesktop.Secret.Collection">
…
~~~

Interestingly in Python the following works:
~~~python
import secretstorage
conn = secretstorage.dbus_init()
collection = secretstorage.get_collection_by_alias(connection, "default")
~~~
So it seems that somehow there is a `default` alias somewhere? Does the `secretstorage` python module not adhere to the standard or KeePassXC or is it just something different (I don't know much about the details of the secret service).

KeePassXC - Version 2.7.0
Revision: d7a9ef4
Operating System: Linux
Desktop Env: sway
Windowing System: Wayland

**Comment by Aetf** [comment]
Can't reproduce using the same commit with the testing database
(https://github.com/keepassxreboot/keepassxc/blob/develop/tests/data/NewDatabase.kdbx).

@jonasc is there anything special with your database? Or are you exposing multiple ones? (Multiple databases shouldn't
matter, but just in case)

**Comment by jonasc** [comment]
So, with this test database I also can't reproduce the problem, that's good.

I do have two databases: the main one (let's call it A) which exposes the secret service entries and one (let's call it B) which is automatically opened when opening the first (via the auto open feature).

Interestingly, when opening the test database (call it C) together with A and B (or just A, no B) I can obtain a default collection without problem. The returned collection (in the given Python code) is the one from A or C depending on whose tab was focused more recently.

Closing B (leaving A and C open) does not change anything. Having only A open (so closing B after it was opened by A) leads to the same problem with no default collection.
Removing the auto open entry in A (more specifically, removing the URL to the file from the entry) and opening A again yields the problem with no default collection.

Enabling the secret service integration in B allows me to obtain the default collection from both A and B (no C open) again depending on which one was focused last.

It seems that there seems to be something special with my database A and I can only obtain a default collection if another database with secret service integration is open.

I thought maybe the problem could be that I have only one folder which I expose via Secret Service and not the whole database, so I changed the folder. This lead to warnings as seen below:
~~~
failed to register FdoSecrets::Item(0x557cf4af15c0) at "/org/freedesktop/secrets/collection/jonas/1fd75d555f5c41b1ace8aa2a5da6e309"
"Failed to register item on DBus at path '/org/freedesktop/secrets/collection/jonas/1fd75d555f5c41b1ace8aa2a5da6e309'"
QObject::connect(Group, Unknown): invalid nullptr parameter
QObject::connect(FdoSecrets::Item, FdoSecrets::Collection): invalid nullptr parameter
QObject::connect(FdoSecrets::Item, FdoSecrets::Collection): invalid nullptr parameter
~~~
Closing the database, reopening it, changing the folder again, crashing with a segmentation fault, and now I can change the folder freely, even select my original folder again and everything seems to work.

So it's weird, it works now and it's unsatisfying to not know what the actual problem was, but it seemed to be with my database.

**Comment by Aetf** [comment]
So it indeed looks like a corrupted database problem.

If you still have the coredump (check `coredumpctl`) for the segmentation fault, we can look further into what happened.
But otherwise I'm afraid there isn't much can be done.

**Comment by jonasc** [comment]
It seems that no coredumps were created… So yeah, I'll close this issue.

**Comment by Pacman99** [comment]
Was a proper solution to this ever found? I'm experiencing the same issue, where if I just expose a certain database `/org/freedesktop/secrets/aliases` doesn't exist. Is there any way to fix this? I don't know what about my database is causing this and I can't find any recent coredumps for keepassxc.

update: It seems like if I remove my AutoOpen group, the issue is fixed

**Comment by leo-b** [comment]
I am experiencing the same issue with keepassxc 2.7.9 on RockyLinux 9.5:

```python
python
>>> import secretstorage
>>> conn = secretstorage.dbus_init()
>>> secretstorage.get_default_collection(conn)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/bergolth/venv-3.9/lib64/python3.9/site-packages/secretstorage/collection.py", line 177, in get_default_collection
    return Collection(connection)
  File "/home/bergolth/venv-3.9/lib64/python3.9/site-packages/secretstorage/collection.py", line 45, in __init__
    self._collection.get_property('Label')
  File "/home/bergolth/venv-3.9/lib64/python3.9/site-packages/secretstorage/util.py", line 67, in get_property
    (signature, value), = self.send_and_get_reply(msg)
  File "/home/bergolth/venv-3.9/lib64/python3.9/site-packages/secretstorage/util.py", line 48, in send_and_get_reply
    raise DBusErrorResponse(resp_msg)
jeepney.wrappers.DBusErrorResponse: [org.freedesktop.DBus.Error.UnknownObject] ("No such object path '/org/freedesktop/secrets/aliases/default'",)
>>> secretstorage.get_collection_by_alias(conn, "default")
<secretstorage.collection.Collection object at 0x7f45e6173ca0>
```

I have two databases. Like @Pacman99 described, my second database (`male.kdbx`) is also opened via _AutoOpen_.

However only the first database is actually exposed to Secret Service:
![Image](https://github.com/user-attachments/assets/efdd7899-ec00-4e69-b365-6db90be5abf2)

It looks like some race condition.
In some cases, the `/org/freedesktop/secrets/aliases/default` collection is available but most of the time it isn't.

**Comment by leo-b** [comment]
> In some cases, the /org/freedesktop/secrets/aliases/default collection is available but most of the time it isn't.

If it doesn't work, the following object paths are available:
```
$ qdbus-qt5 org.freedesktop.secrets
/
/keepassxc
/org
/org/freedesktop
/org/freedesktop/secrets
/org/freedesktop/secrets/collection
/org/freedesktop/secrets/collection/leo
/org/freedesktop/secrets/collection/leo/0cda600e4ec74e8b8b66e8d20da26ec8
/org/freedesktop/secrets/collection/leo/1c740e34d22c469dbdce4f7b264fb431
/org/freedesktop/secrets/collection/leo/aa8c7a3df96c4e9db679b39277b71f53 
```

If database startup did work properly, the `aliases` path is also shown:
```
$ qdbus-qt5 org.freedesktop.secrets 
/
/keepassxc
/org
/org/freedesktop
/org/freedesktop/secrets
/org/freedesktop/secrets/aliases
/org/freedesktop/secrets/aliases/default
/org/freedesktop/secrets/collection
/org/freedesktop/secrets/collection/leo
/org/freedesktop/secrets/collection/leo/0cda600e4ec74e8b8b66e8d20da26ec8
/org/freedesktop/secrets/collection/leo/1c740e34d22c469dbdce4f7b264fb431
/org/freedesktop/secrets/collection/leo/aa8c7a3df96c4e9db679b39277b71f53
```

**Comment by llucax** [comment]
I just bumped into this issue. Restarting keepassxc solved it.

**Comment by ingenarel** [comment]
@llucax i have no clue why it works, but i was on the verge of losing my sanity and thankfully it works

**Comment by lgflorentino** [comment]
Seems like the database configured to be the SecretService database needs to be the **active** or selected database in keepassxc when the client is requesting access to it.

**Comment by llucax** [comment]
I had this again and restarting didn't work, but using `busctl --user tree org.freedesktop.secrets --no-pager` to get my collection name (tip, it is the `.kdbx` file name) did the trick, then I used `secret-tool store --collection="/org/freedesktop/secrets/collection/<my-collection-name>"` and it worked.

Is there any way to set a collection as the  "default" in keepassxc? I couldn't find any way to do it explicitly.

**Comment by droidmonkey** [comment]
The default collection is the currently focused database tab. There is a separate request to make that more explicit.

**Comment by llucax** [comment]
> The default collection is the currently focused database tab. There is a separate request to make that more explicit.

Then there is a bug, because I had the currently focused database tab and still getting the `No such object path '/org/freedesktop/secrets/aliases/default` error when trying to store a password using `secret-tool store`.

**Comment by droidmonkey** [comment]
https://github.com/keepassxreboot/keepassxc/issues/8611
