### ISSUE TITLE
Use entry TAGS to match windows for global Auto-Type

### ISSUE THREAD

**Issue by redactedscribe** [keepassxreboot/keepassxc#7577]
## Summary
Like titles and URLs, add an option to consider tags (new in 2.7.0) when matching a window for Auto-Type.

## Examples
Window title: GameLauncher
Entry title: Game's name
URL: not usually relevant to non-browser application
Tags: gamelauncher

## Context
Sometimes a window may be titled differently to what would be useful to title an entry and thus the auto-type will not match. If a tag was added that matched the window title, it would solve the issue with the suggested new option.

This is a feature I used and miss from the original KeePass. The only downside I can see if that the tags could get cluttered with less useful tags that are only meant to help with window matching. Perhaps some tags can be marked as hidden but still affect window matching? I.e. hidden from the tags list in the UI (unless an option to show hidden tags is enabled).

Thanks!

**Comment by droidmonkey** [comment]
You need to do this: https://keepassxc.org/docs/KeePassXC_UserGuide.html#_configure_auto_type_sequences

**Comment by redactedscribe** [comment]
A different suggestion then could be to allow Window Associations to be queried when making a database search so that one wouldn't need to add "gotomeeting" to a "LogMeIn" entry's window association _and_ to its tag/description/etc (the latter only so that it can appear via a search for "gotomeeting").

**Comment by redactedscribe** [comment]
I take it that this feature will not be considered then. The upside of the feature request would be that use of tags for this purpose would mean window associations would work across both KeePassXC and the original KeePass (I assume the Window Associations list is a KeePassXC-only feature).

A different suggestion then could be to allow Window Associations window titles to be queried when making a database search so that one wouldn't need to add "gotomeeting" to a "LogMeIn" entry's window association list _and_ to its tag/description/etc (the latter only so that an entry can appear via a search for "gotomeeting").
