### ISSUE TITLE
Missing File Version 2.7.0

### ISSUE THREAD

**Issue by gitusercodes** [keepassxreboot/keepassxc#7582]
If I run
https://github.com/keepassxreboot/keepassxc/releases/download/2.7.0/KeePassXC-2.7.0-Win64.zip
https://github.com/keepassxreboot/keepassxc/releases/download/2.7.0/KeePassXC-2.7.0-Win64.msi
on a Windows 8.1 and Windows 7 ESU Extended Support Update
it does not start because at once the error occurs
"Missing api-ms-win-core-kernel32-legacy-ansi-l1-1-0.dll" 

If I am copying manually from a Windows 10 the api-ms-win-core-kernel32-legacy-ansi-l1-1-0.dll
in the KeePassXC Folder it also fails

The last working version for Windows 8.1 and Windows 7 ESU seems
https://github.com/keepassxreboot/keepassxc/releases/download/2.6.6/KeePassXC-2.6.6-Win64-portable.zip
and
https://github.com/keepassxreboot/keepassxc/releases/download/2.6.6/KeePassXC-2.6.6-Win32-portable.zip

Can you please build also a portable 2.7.0 Version which works on Windows 8.1 and Windows 7 ESU ??

**Comment by droidmonkey** [comment]
Windows 7 is unsupported

**Comment by rclbrg** [comment]
Same issue on Windows Server 2012R2

**Comment by Tiffinini** [comment]
Is W8.1 unsupported too? Because I get the same error with that DLL in System32.

**Comment by Tiffinini** [comment]
> Windows 7 is unsupported


Is W8.1 unsupported too? Because I get the same error with that DLL in System32.

Edit: Anyone experiencing this issue on older Windows versions should check this: https://github.com/keepassxreboot/keepassxc/issues/7599#issuecomment-1076648750

**Comment by phoerious** [comment]
Yes. Neither are Windows releases that receive regular security updates by Microsoft anymore.

**Comment by Tiffinini** [comment]
> > Windows 7 is unsupported
> 
> Is W8.1 unsupported too? Because I get the same error with that DLL in System32.
> 
> Edit: Anyone experiencing this issue on older Windows versions should check this: [#7599 (comment)](https://github.com/keepassxreboot/keepassxc/issues/7599#issuecomment-1076648750)

8.1 enjoys security updates under the ESU program up until Jan 10 2023: https://docs.microsoft.com/en-us/lifecycle/products/windows-81.

It is still, for all intents and purposes, supported by MS from a security standpoint.

**Comment by phoerious** [comment]
It's not for the average user.
