### ISSUE TITLE
KeepassXC triggers Windows dictionary attack mitigation

### ISSUE THREAD

**Issue by mkrzywonski** [keepassxreboot/keepassxc#7583]
## Overview
Windows displays a security dialog after user enters master password in KeepassXC, after upgrading to version 2.7.0

## Steps to Reproduce
1. Upgrade KeepassXC to version 2.7.0
2. Open KeepassXC and enter master password
3. Windows Security dialog is displayed
4. Click [Cancel] and dialog disappears, KeepassXC opens successfully.
5. This behavior happens every time I enter my master password to unlock the database

## Expected Behavior
No Windows security dialog is displayed when unlocking database

## Actual Behavior
Windows security dialog is displayed when unlocking database

## Context
Windows Security dialog contents:
------------------------------------------------
Windows Security
Making Sure it's you
You've entered an incorrect PIN too many times.
To try again, restart your device.
I forgot my PIN
The dictionary attack mitigation is triggered and the provided authorization was ignored by the provider.
                                   [Cancel]
------------------------------------------------

KeePassXC - Version 2.7.0
Revision: d7a9ef4
Operating system: Windows 10 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.19043

![error](https://user-images.githubusercontent.com/48806744/159502819-2f7f2075-d147-4229-ba8c-9f06ee01b2eb.PNG)

**Comment by droidmonkey** [comment]
https://keepassxc.org/docs/KeePassXC_UserGuide.html#_quick_unlock

**Comment by mkrzywonski** [comment]
Thank you! It was the quick unlock setting.
