### ISSUE TITLE
Entry-level Auto-Type is broken in Gnome

### ISSUE THREAD

**Issue by droidmonkey** [keepassxreboot/keepassxc#7584]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
Cannot perform entry-level Auto-Type on Gnome.

**Comment by Nateowami** [comment]
Is there a workaround for this on Ubuntu 20.04.4 with Gnome? It doesn't appear that snap will allow downgrading to the previous version (`snap list keepassxc` lists only 2.7.0). The snap store shows channels stable, candidate, beta, and edge, but they're all at 2.7.0. And from the looks of it, milestone v2.7.1 is nowhere close to complete and won't be shipping anytime soon.

**Comment by droidmonkey** [comment]
2.7.1 will likely ship tomorrow once we clear out all the found issues. For now you can disable "Always ask before performing auto-type" in the auto-type application settings.

**Comment by Nateowami** [comment]
Wonderful to hear the next release will be quite soon. However, disabling "Always ask before performing auto-type" doesn't appear to actually solve the problem. It still logs "Active window changed, interrupting auto-type." Sometimes. I just got it to work several times in a row, whereas previously today it was never working. I'm not seeing any consistent pattern.

**Comment by droidmonkey** [comment]
It is a timing issue, you can use global auto-type. Define a global shortcut and then you can search your database for the entry you want to use

**Comment by l0f4r0** [comment]
It doesn't seem recommendation to use global auto-type is OK.
Indeed, I have one defined and it doesn't work (at least for me)...

Steps to reproduce:

1. I open a website inside a new tab
2. I type my KeepassXC shortcut for auto-type (CTRL+ALT+SHIFT+Y)
3. A dialog appears to let me choose the correct entry
4. I click on the right entry
5. Focus is given to my browser but **nothing happens**

I had no issue with previous KeepassXC vesions (<2.7.0).

Here are my infos:

> KeePassXC - Version 2.7.0
> Révision : 20c9ac1
> Canal : Snap
> Qt 5.15.3
> Operating System: Linux Debian 10 64bits
> Desktop Env: XFCE 4.12.5
> Windowing System: X11

**Comment by ghost** [comment]
Same here on Manjaro 21 with gnome 41 since the update to 2.7.0.
Ctrl+Shift+V make the keepass hidde but fields are not completed.
I have to complete fields with manual shortcuts.
Disable the warning message for autotype change nothing.

**Comment by droidmonkey** [comment]
Update to 2.7.1
