### ISSUE TITLE
Check for directory write permissions prior to entering portable mode

### ISSUE THREAD

**Issue by droidmonkey** [keepassxreboot/keepassxc#7585]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
https://github.com/Warzone2100/warzone2100/issues/2645

The .portable file should only be effective if the directory where keepassxc binary is stored is writable by the current user.

**Comment by phoerious** [comment]
What about the AppImage and standalone macOS appdirs?
