### ISSUE TITLE
KeePassXC-Browser extension can't unlock database

### ISSUE THREAD

**Issue by Programie** [keepassxreboot/keepassxc#7586]
## Overview
Whenever I try to unlock my KeePassXC database using the browser extension, KeePassXC asks me for the database password but does not unlock the database.

Manually opening the KeePassXC window and unlocking the database works. After that, also the browser extension is able to auto fill credentials. But the next time, the database is locked and tried to be unlocked by the browser extension again, the unlock does not work again.

I didn't had the issue with the previous version (2.6.0).

## Steps to Reproduce
1. Connect your browser with KeePassXC using the KeePassXC-Browser extension
2. Try to unlock the database by clicking on the KeePassXC-Browser icon
3. The "Unlock KeePassXC Database" window pops up
4. Enter your database password
5. The password is accepted, the window disappears but the database is still locked

## Expected Behavior
The database should be unlocked so browser auto fill is working.

## Actual Behavior
The database stays locked.

## Context

[NOTE]:
KeePassXC - Version 2.7.0
Revision: d7a9ef4

[NOTE]:
Operating System: Linux
Desktop Env: KDE
Windowing System: X11

**Comment by droidmonkey** [comment]
Do you have lock on minimize or similar setting enabled?

**Comment by Programie** [comment]
Yes, the setting is enabled and disabling "Lock on minimize" fixes the issue.

But why did it worked before?

**Comment by droidmonkey** [comment]
No clue, possibly broken or the window wasn't minimizing again after unlock. Either way, recommend just disabling that setting, it is terrible.

**Comment by Programie** [comment]
OK, thanks for the hint.
