### ISSUE TITLE
Wasted space on bottom of window.

### ISSUE THREAD

**Issue by bjwest** [keepassxreboot/keepassxc#7589]
## Overview

[NOTE]: # ( Give a BRIEF summary about your problem )
The unused Status Bar area on the bottom of the main window is a large portion of wasted space.

## Steps to Reproduce
1. Open KeePassXC and unlock database
2. Look at bottom of window
3. Notice Status Bar that doesn't appear to be used taking up a couple of text lines of space.

## Expected Behavior
If the Status Bar isn't used, it shouldn't be included in the window.

## Actual Behavior
Status Bar is present, but apparently not used.

## Context
The Status Bar also seems to be present on the unlock screen, but doesn't really interfere with anything there.  I'm not sure if it was present on the previous version or not, I noticed it while resizing the two panels in the main view on the left.  The database tags panel gets clipped on the bottom by the Status Bar.

KeePassXC - Version 2.7.0
Revision: d7a9ef4

Operating System: Linux
Desktop Env: KDE
Windowing System: X11

**Comment by droidmonkey** [comment]
We are using it now; it shows when the clipboard will be cleared. It will also show other information in the future. We will not be hiding it. Selectively showing it produces a poor experience.
