### ISSUE TITLE
SVG icons scaled inproportionally

### ISSUE THREAD

**Issue by agharbeia** [keepassxreboot/keepassxc#7592]
## Overview
When an SVG file is used as a custom icon for an entry or a group, the image is scaled, but inproportionally.

## Steps to Reproduce
1. Create a test group
2. In the group's properties clock the icon tab
3. Assign a custom icon by choosing an SVG file from your computer. For testing purposes, the image should have one dimention greater than the other.

## Expected Behavior
Wherever the icon is displayed, it should be scaled proportionally, maintaining the original aspect ratio.

## Actual Behavior
The image is distorted, by stretching one dimension to fit the required size of the icon's square in the UI.

KeePassXC - Version 2.7.0
Revision: d7a9ef4

Qt 5.12.8
Debugging mode is disabled.

Operating system: Ubuntu 20.04.4 LTS
CPU architecture: x86_64
Kernel: linux 5.13.0-35-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.12.1

**Comment by droidmonkey** [comment]
Your icon needs to be a square, otherwise it is forced into a square proportion. One way or another it's going to look terrible if it is not already in a square.

**Comment by t214c** [comment]
Can't this issue be better solved by filling the missing area to a square instead of distorting the image?

[icons-2.zip](https://github.com/user-attachments/files/24474761/icons-2.zip)
