### ISSUE TITLE
Windows install fails: Invalid Drive: E:\

### ISSUE THREAD

**Issue by fwinn** [keepassxreboot/keepassxc#7597]
I just downloaded the .msi setup file for updating to version 2.7.0 but every time I open it there's immediately a popup with the warning "Invalid Drive: E:\". I guess E: is the letter for connected USB Sticks but I don't have one plugged in and it doesn't let me choose another drive to install it on.
After closing the warning, the end screen appears ("KeePassXC Setup Wizard ended prematurely").

Windows 11 Version 21H2

**Comment by droidmonkey** [comment]
Make sure you are downloading from our download page: https://keepassxc.org/download

This is not a behavior we have in our installer.

**Comment by fwinn** [comment]
I downloaded it again, same error.
MD5 Checksum of the installer: 56b3177118345595ff1c1a8d18351d9f

**Comment by droidmonkey** [comment]
Did you install the program previously to the E drive?

**Comment by fwinn** [comment]
Given that E is not a normal drive in my PC, I don't think so. At least version 2.6.6 which I used until now is installed on D

**Comment by fwinn** [comment]
This is where it occurs for the first time in the log:

> MSI (c) (F0:10) [22:10:32:324]: Note: 1: 2262 2: Signature 3: -2147287038 
MSI (c) (F0:10) [22:10:32:324]: PROPERTY CHANGE: Adding INSTALL_ROOT property. Its value is 'E:\Programme_HDD\keepassxc\'.
AppSearch: 
MSI (c) (F0:10) [22:10:32:326]: Note: 1: 2262 2: Signature 3: -2147287038 
MSI (c) (F0:10) [22:10:32:326]: PROPERTY CHANGE: Adding AUTOSTARTPROGRAM_REGISTRY property. Its value is '"D:\Programme_HDD\keepassxc\KeePassXC.exe"'.
AppSearch:
