### ISSUE TITLE
Update download page to indicate that 2.7.0 supports Windows 10/11 64-bit only

### ISSUE THREAD

**Issue by JohnTHaller** [keepassxreboot/keepassxc#7599]
The 2.6.6 release of KeePassXC worked on Windows 7, 8, 10, and 11, both 32-bit and 64-bit. The 2.7.0 release only works on Windows 10/11 64-bit. That excludes about 15% or so of the Windows market, so it would probably alleviate some questions to specifically list that it requires Windows 10 or later on the download page and have the installer lock out installs on older versions of Windows.

**Comment by Packbat** [comment]
Can confirm that this is an issue - I on my Windows 7 machine was on my way into the bug tracker to find out why it crashed on boot after the update. There was no visible indication that Win7 support was dropped.

**Comment by droidmonkey** [comment]
**start rant**
That is 15% of the windows population who don't care one iota about their security. Windows 7 has been end of life (read ZERO security updates) for two years. You are a sitting duck to any drive by attack and software has and will be unable to run on the system. You should have no expectation that anything should work at this point, the fact that it does is only by coincidence.
**end rant**

We might be able to provide an installer built using MSYS2 that may work on Windows 8 and below. Until then you can continue to use 2.6.6 without issue.

**Comment by thinkpad4** [comment]
@droidmonkey I too would like a version of 2.7.0 that works on Windows 7 please

Thank you very much

**Comment by JohnTHaller** [comment]
> **start rant** That is 15% of the windows population who don't care one iota about their security. Windows 7 has been end of life (read ZERO security updates) for two years. You are a sitting duck to any drive by attack and software has and will be unable to run on the system. You should have no expectation that anything should work at this point, the fact that it does is only by coincidence. **end rant**

I'm aware and don't use it myself other than for testing apps for PortableApps.com builds. I also wasn't asking for Windows 7 or 32-bit builds. It would make life easier if it were clearer to end users that this is what's changed. An installer error on run and a notice on the page that 2.7.0 forward only supports Windows 10 64-bit and Windows 11 with a link to 2.6.6 and a suggestion of an alternative project that still gets updates on those older OSes like KeePass Pro.

Globally, there are a lot of folks that are using older hardware that doesn't even support Windows 10 who don't currently have the means to upgrade. I make a best effort to support users of older Windows versions who are in situations like that.

**Comment by droidmonkey** [comment]
We did put 32 bit downloads are deprecated on the downloads page. To be honest I had no idea that Windows 8 and below would be broken until people reported it as such. What grinds my gears is the potential lack of awareness regarding their current security situation in general. We actually didn't intentionally lock people out of 2.7.0, they just are on the wrong side of progress.

**Comment by Packbat** [comment]
I'm sorry, my reply was not clear.

Even knowing as little as I do about software development, I am aware that maintaining compatibility with old machines is progressively more and more expensive and is not always going to be a priority. I expect to find that software I use updates in ways that break Windows 7 compatibility. Libraries change, libraries are replaced, features added a decade ago reach a point where developers assume they are universal ... I get it. I deeply appreciate all the work that the KeePassXC team has been doing.

...but I would like to be told when things break. And that is the bug being reported: the documentation for the update fails to note that this is the update that breaks Windows 7 and Windows 8 compatibility. That's all.

**Comment by droidmonkey** [comment]
Can you try this version on Windows 7 please: https://github.com/keepassxreboot/keepassxc/releases/download/2.7.0/KeePassXC-2.7.0-Win64-LegacyWindows.msi

If this works I will update the downloads page.

**Comment by peter-fb** [comment]
I tried the legacy installer on Windows 8.1 (which Microsoft will support until 2023-01) and it worked. The installer stated two times that a reboot is required, so I rebooted and now everything seems to work fine. So thank you! :)

**Comment by JohnTHaller** [comment]
I can confirm that the LegacyWindows msi posted by droidmonkey works on the 64-bit versions of Windows 7, 8.0, 8.1, 10, and 11.

There is an error displayed when launching on Windows 7 as shown in the attached. It does not appear on other versions of Windows. I am running it within VirtualBox which may or may not be related.

![KeePassXCWin7Error](https://user-images.githubusercontent.com/8020860/159826300-84cc92c7-9e0f-4627-b35a-915258b9f183.jpg)

**Comment by droidmonkey** [comment]
Not a deal breaker, might be related to being in a VM, you can suppress that by launching with --allow-screenshots

**Comment by phoerious** [comment]
Holy shit. Windows 7 without Aero. That screenshot has "LEGACY" written all over it in ALLCAPS.

**Comment by JohnTHaller** [comment]
> Not a deal breaker, might be related to being in a VM, you can suppress that by launching with --allow-screenshots

I figured. Unfortunately, I don't have a Win7 machine to test on that's not in a VM. And the 8 - 11 machines are all in the same VirtualBox install using the same guest OS drivers, so not sure.

Are you going to replace the current Windows version with this legacy version or make it available as an option? What's the difference?

**Comment by phoerious** [comment]
The non-legacy version is built with the MS toolchain, which is the way to go forward. The legacy toolchain will eventually stop working when we start using features only available via MSVC.

**Comment by J-J-Chiarella** [comment]
I would appreciate the 32-bit build being available. If I'm at a work computer that runs Windows 10 in 32-bit mode, I like to have KeePassXC installed. I know that work devices are probably not that safe, but keeping a keepass password file for Spotify or other low-risk things available on a machine at work is useful. I use KeePassXC safely on my own devices, but it's convenient to copy-paste the keepass file onto a USB thumb drive and put it on my work computer. Some countries are also hopelessly stuck on older equipment. In 2018, South Korea still had many websites and government services only work on IE on Windows 7 at the latest. In 2022, some government websites still use a proprietary format for official documents instead of PDFs. Back in 2012, most university and school computers ran Windows XP.

I'm more sympathetic to abandoning older Mac versions. The customer base has shown its willingness to buy new things very often (look at even iOS vs. Android app sales), and Apple itself abandons older users at an alarming rate, and then there's the m68k -> PowerPC -> Intel x86 -> ARM transition in a couple decades.

Windows is in a special category. I don't like it, but it is what it is, and part of getting people off of Windows is going to involve having cross-platform software programs be available for them on Windows so that the switchover is less painful. Also, some of us have to use Windows but may need having those programs available.

**Comment by droidmonkey** [comment]
We are not building or delivering 32-bit from 2.7.0 onward. You can continue to use 2.6.6, however.

**Comment by comdm** [comment]
> Can you try this version on Windows 7 please: https://github.com/keepassxreboot/keepassxc/releases/download/2.7.0/KeePassXC-2.7.0-Win64-LegacyWindows.msi
> 
> If this works I will update the downloads page.

This Version works fine with Windows 8.1! Thanks, please update the downloadpage.

**Comment by JohnTHaller** [comment]
> I would appreciate the 32-bit build being available. If I'm at a work computer that runs Windows 10 in 32-bit mode, I like to have KeePassXC installed. I know that work devices are probably not that safe, but keeping a keepass password file for Spotify or other low-risk things available on a machine at work is useful. I use KeePassXC safely on my own devices, but it's convenient to copy-paste the keepass file onto a USB thumb drive and put it on my work computer. Some countries are also hopelessly stuck on older equipment. In 2018, South Korea still had many websites and government services only work on IE on Windows 7 at the latest. In 2022, some government websites still use a proprietary format for official documents instead of PDFs. Back in 2012, most university and school computers ran Windows XP.

If it's read only at work, you can either keep using 2.6.6 or use KeePass Pro since it can read the same kdbx file format.

I'm debating including the 2.6.6 32-bit version in the KeePassXC Portable package at PortableApps.com the way I do with other apps and have it automatically switch, but as this is a security app, it's unlikely.

**Comment by phoerious** [comment]
You should really update your screenshots on PortableApps.

**Comment by gz19880228** [comment]
> 

I can also confirm that the legacy version works on my machine with Windows 7 64bit.
