### ISSUE TITLE
Search help widget should explain "tag" field

### ISSUE THREAD

**Issue by sometimesfood** [keepassxreboot/keepassxc#7600]
## Summary
The list of fields in the search help widget should contain an entry for the "tag" field.

## Examples
I have not tested this, but something like this might do the job:
```diff
diff --git a/src/gui/SearchHelpWidget.ui b/src/gui/SearchHelpWidget.ui
index bd8731eb..1fed7698 100644
--- a/src/gui/SearchHelpWidget.ui
+++ b/src/gui/SearchHelpWidget.ui
@@ -214,6 +214,13 @@
           </property>
          </widget>
         </item>
+        <item row="4" column="0">
+         <widget class="QLabel" name="label_24">
+          <property name="text">
+           <string notr="true">tag</string>
+          </property>
+         </widget>
+        </item>
         <item row="0" column="1">
          <widget class="QLabel" name="label_5">
           <property name="text">
```

Note: I have not tested the change above, since I don't have access to a suitable development environment right now.

## Context
I really like the tag support in 2.7. Being able to search for entries with a specific tag is an important part of the tag feature. Adding "tag" to the list of fields in he search help widget would make it easier for users to find out how to search for a specific tag.

**Comment by droidmonkey** [comment]
You just click the tag on the lower left. I am going to be removing that search help in the future and replace it with an actual search builder like tool. https://keepassxc.org/docs/KeePassXC_UserGuide.html#_application_layout

**Comment by sometimesfood** [comment]
> You just click the tag on the lower left.

Sure, that works perfectly fine. I just thought it might be nice to include the tag field in the help widget for consistency's sake and to have a quick reference all in one place.

**Comment by droidmonkey** [comment]
Decided not to make a change here, searching for tags is trivial with the Searches and Tags view in the lower left
