### ISSUE TITLE
Double click on user/password opens entry, expected copy value to clipboard

### ISSUE THREAD

**Issue by xo3fn08a** [keepassxreboot/keepassxc#7601]
## Overview
Double click on user/password opens entry, expected copy value to clipboard

## Steps to Reproduce
1. Open database, find entry desired.
2. Double click on the user or password columns.

## Expected Behavior
Field value gets copied to the clipboard.

## Actual Behavior
As of 2.7.0 the entry gets opened for edit.

## Context
Installed from the repository: http://ppa.launchpad.net/phoerious/keepassxc/ubuntu  impish InRelease  

Help > Debug Info page:

KeePassXC - Version 2.7.0
Revision: d7a9ef4

Qt 5.15.2
Debugging mode is disabled.

Operating system: Ubuntu 21.10
CPU architecture: x86_64
Kernel: linux 5.13.0-35-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.17.3

**Comment by xo3fn08a** [comment]
Noticed the same behavior on Windows 10.

**Comment by droidmonkey** [comment]
It's a new setting. You can re-enable the old behavior in the application settings.

**Comment by PlamenOBM** [comment]
> It's a new setting. You can re-enable the old behavior in the application settings.

Could you please elaborate how to do this, as I've spent half hour looking for such setting

Edit: Found it
![2022-04-08_11-33](https://user-images.githubusercontent.com/16608326/162397452-17868508-58dc-4a52-bb52-cfee4d601e3e.png)

**Comment by lordloh** [comment]
I am on 2.7.10 on Windows 11

```
KeePassXC - Version 2.7.10
Revision: b342be4

Qt 5.15.11
Debugging mode is disabled.

Operating system: Windows 11 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.26100

Enabled extensions:
- Auto-Type
- Browser Integration
- Passkeys
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 3.1.1
```

And I do not see that setting.

Scceenshot...

![Image](https://github.com/user-attachments/assets/7bce3ac0-cb61-4206-9ff3-e0ea34f0bf07)

**Comment by droidmonkey** [comment]
It was moved to general settings page, near bottom

**Comment by lordloh** [comment]
> It was moved to general settings page, near bottom

Thank you.  I would not have found it without your tip :-)

![Image](https://github.com/user-attachments/assets/d4bcb868-8440-4a22-a0ad-f904284ac9c9)
