### ISSUE TITLE
Linux/snap cannot open or save attachments 

### ISSUE THREAD

**Issue by weskenny** [keepassxreboot/keepassxc#7604]
## Overview
I am no longer able open or save attachments in the latest KeepassXC (2.7.0) running in snap on top of the latest Ubuntu 20.04.
At some point in the past, this worked for me. Not sure when it stopped.

The dialog for saving the attachment looks similar to one you would see for "open": it requires you to specify a file to open, and doesn't give you an option to save the file in the current directory.

This screenshot shows the lack of options to save the attachment (you can select an existing file and click open, however it doesn't seem to do anything):
![save_attachments](https://user-images.githubusercontent.com/81018645/159629432-a27ea596-0e24-4929-9d59-86433c14fc5e.png)

If I deselect a file or directory using Control-Click, it won't let me click "Open":
![save_attachments_no_option](https://user-images.githubusercontent.com/81018645/159629607-34b364ae-04b3-4c13-b4cd-0c0cddad3c96.png)

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Find an existing entry that has attachments
2. Click _Open_
3. Click _Save_ and try to select a location.

## Expected Behavior
_Open_ should open the file using an editor like Vim
_Save_ should save the attachment(s)

## Actual Behavior
For _Open_, nothing happens.
For _Save_, you can try to select a location. You can only select a regular file (you can't select a directory as the final option), and then nothing seems to happen

## Context
I tried this under both Wayland and X11. Neither were able to open or save attachments.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.0
Revision: 20c9ac1
Distribution: Snap

Qt 5.15.3
Debugging mode is disabled.

Operating system: Ubuntu Core 20
CPU architecture: x86_64
Kernel: linux 5.4.0-105-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.12.1

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: Gnome
Windowing System: X11/Wayland (tried both)

**Comment by SCBuergel** [comment]
same here - got locked out of my attachments :-/

**Comment by droidmonkey** [comment]
You can always use our appimage or ppa in the meantime while we fix this.

**Comment by droidmonkey** [comment]
This is the same issue as https://github.com/keepassxreboot/keepassxc/issues/7607#issuecomment-1076801200
