### ISSUE TITLE
Autotype broken on Ubuntu 20 since last keepass update

### ISSUE THREAD

**Issue by avisecag** [keepassxreboot/keepassxc#7605]
## Overview
Yesterday evening KeePassXC seems to have updated on my Ubuntu (now 2.7.0, unfortunately no idea what version I was running before), today autotype is broken.

__Additional insights__
It would appear that this is *only* the case if the auto-type prompt is enabled. With the prompt disabled, everything works fine.

## Steps to Reproduce
1. Make sure "Always ask before performing auto-type" option is enabled in general settings.
1. Open a texteditor
2. Switch to KeePassXC
3. Select an entry, press ctrl-shift-v
4. On prompt "Perform Auto-Type into the previously active window?", click yes.

## Expected Behavior
Username and password appear in the text editor.

## Actual Behavior
KeePass minimises, but nothing is actually showing up in the text editor.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.0
Revision: 20c9ac1

[NOTE]: # ( Pick choices based on your environment )
Operating System: Ubuntu core 20
Desktop Env: Gnome (default)
Windowing System: X11

**Comment by andilge** [comment]
same bugous behaviour on Linux Mint

**Comment by in-in** [comment]
@avisecag 
![220821648023992](https://user-images.githubusercontent.com/8797432/159655846-21b0a222-2faa-4ed8-8ed9-2077bf91ef5a.png)

**Comment by avisecag** [comment]
@in-in 
Darn, didn't notice that second tab! :facepalm: 

And the **bestest** thing, after disabling the prompt, auto-type actually works again!! You might want to look into that...

**Comment by andilge** [comment]
ohw wow, interesting finding. 
**after disabling the prompt, auto-type actually works again**

I'm away form my personal computers with Linux Mint, can verify only in som e hours.

**Comment by ITler** [comment]
Just disabling the confirmation box does not help me.

The behavior for auto-type **seems** to have changed with the new version. It automatically uses the last active window. For my multi-monitor setup with i3 in conjunction with some specific applications that display the input window above another without disabling the underlying one, this is not helpful.
I would need to manually set the focus to the correct window before auto-type starts (delayed) typing. 

I would appreciate if another checkbox would be introduced to optionally switch between different behaviors

**Comment by BartoszBartmanski** [comment]
Does not work for me as well on Linux mint 20.3 with cinnamon desktop

Unchecking the "Always ask before performing Auto-Type" did not solve the issue

**Comment by cristi-t** [comment]
For me sometimes it works, sometimes it does not (after I disabled the prompt). Similar behavior in Gnome Ubuntu 20.04 and Gnome Ubuntu 18.04 VirtualBox.

**Comment by mpan-pl** [comment]
The same issue in Arch Linux, Xfce as the DE. The confirmation prompt and any filtering disabled. Sometimes Auto-Type works after switching between windows a few times or on 2nd or 3rd attempt, though I can’t find any particular pattern.

keepassxc 2.7.0, xfwm4 4.16.1, xorg-server 21.1.3

**Comment by droidmonkey** [comment]
This bug is already fixed, will be out in 2.7.1

**Comment by 365cycle** [comment]
This is not fixed. Workaround to switch off the confirmation still works. 
Debug info:

KeePassXC - Version 2.7.11
Revision: 01e5b6e
Distribution: Flatpak

Qt 5.15.18
Debugging mode is disabled.

Operating system: KDE Flatpak runtime
CPU architecture: x86_64
Kernel: linux 6.17.0-14-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- Passkeys
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 3.7.1

Linux Mint 22.3 - Cinnamon 64-bit 6.6.7
