### ISSUE TITLE
protocol-error for pageant on keepassxc 2.7

### ISSUE THREAD

**Issue by XtraLarge** [keepassxreboot/keepassxc#7606]
Hello,
i've updatend my system to keepassxc 2.7 portable. The Keepass database is the same before.
I checked that pageant version 0,76 is running und ssh-integration and pageant integration is checked.
After unlock my database the ssh keys are not imported and the keeepass settings ssh-interagation-panel shows a protocol-error.

**Comment by hifi** [comment]
Just to be sure, none of your keys have any constraints set like remove after the time or require confirmation?

**Comment by TomBaxter** [comment]
Are you using the snap install?

**Comment by XtraLarge** [comment]
I only checked to add den key on unlock and I use the official portable version.

**Comment by XtraLarge** [comment]
I've tried to install keepass with msi (64bit) .... and the import works!!! .... so only the portable version is affected! .... but please correct ist, because I synt the software and config between my clients.

**Comment by hifi** [comment]
Interesting, might be a mixup between running as Administrator and the normal user?

**Comment by XtraLarge** [comment]
No, i've started both, keepassxc and pageant with a simple click as a user.

**Comment by XtraLarge** [comment]
Sorry, you can close the issue. After a full reboot of my Windows System the portable Version 2.7 works without error. It seems that there are some libraries which will not be refreshed if Windows is not rebooted!

**Comment by creidhne-a16i** [comment]
This seems more like Windows/pageant bug than anything else. I have the same issue, and this seems to be somehow related to most recent Windows update... as this is the only thing that changed. I have a task that starts pageant as my user on boot, then when I start portable keepassXC, keys would get added. Since the update, this is no longer working correctly for whatever reason, and I have to manually restart pageant before it starts working again.

**Comment by creidhne-a16i** [comment]
To add to it - if the pageant is started through task scheduler, I get that error. If I start pageant manually, no such problem occurs and it all works. How exactly does KeepassXC communicate with pageant? How and why is task manager affecting it, any ideas?

**Comment by droidmonkey** [comment]
These are questions to raise with the pageant team. They probably are not registering the socket successfully due to timing of when it starts
