### ISSUE TITLE
Auto-type in i3 broken with new version 2.7.0

### ISSUE THREAD

**Issue by ITler** [keepassxreboot/keepassxc#7608]
### description
It **seems** the behavior for auto-type (`Ctrl+Shift+v`) has changed with the new version. It automatically types into the last active window. For my multi-monitor setup with **[i3](https://i3wm.org/)** ~in conjunction with some specific applications that display the input 'dialog' above another window but without disabling the underlying one~, auto-type seems to not be able to select the correct window/application and just types within keepassxc.

### unsuccessful mitigations
* I disabled the confirmation dialog for auto-type as suggested in #7605

### desire
I would need to be able to manually set the focus to the correct window before auto-type starts (delayed) typing instead of relying on keepassxc finding the correct window. 
I would appreciate if another checkbox would be introduced to optionally switch between the different behaviors

### system
```
KeePassXC - Version 2.7.0
Revision: d7a9ef4
installed via ppa:phoerious/keepassxc

Qt 5.12.8
Debugging mode is disabled.

Operating system: Ubuntu 20.04.4 LTS
CPU architecture: x86_64
Kernel: linux 5.4.0-105-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.12.1
```

**Comment by hifi** [comment]
What do you mean the behavior has changed? It should always type into the last active window after the dialog closes. What did it do before?

**Comment by ITler** [comment]
Hey @hifi

interesting.
So for me with i3 it never did. It seems that auto-type always typed to the window with the active focus, means the keepassxc never knew about the last active window. 
However with previous version I was able to manually set the desired window focus for (delayed) auto-typing (by moving the mouse or use a keyboard shortcut to select the proper workspace where the target window is in), which now is not working anymore.

Not sure if it is relevant, but I add it here... Using `Ctrl+Shift+U` for Open URL is (still) selecting the correct browser window on the correct workspace

**Comment by droidmonkey** [comment]
There is a bug with entry level Auto-Type, been fixed already.

**Comment by ITler** [comment]
confirmed working in 2.7.1
