### ISSUE TITLE
Disable selection on Auto-Type preview list

### ISSUE THREAD

**Issue by schoettl** [keepassxreboot/keepassxc#7611]
## Overview

In the new version 2.7.0, there is a preview area at the bottom for the selected item. The preview area now has an "Auto-Type" tab with a list. When I intend to delete an Auto-Type item from the list using the Delete key, the complete password item is deleted instead.

## Steps to Reproduce

1. select an item that has auto-type settings
2. switch to the auto-type tab in the preview area
3. press the delete key (!!deletes the whole password item!!)

## Expected Behavior

Safer behavior would be to swallow and not bubble the key delete event.

## Actual Behavior

The delete key seems to be handled by a global key event handler that deletes the item.

## Context

KeePassXC - 2.7.0
Revision: d7a9ef4
Operating System: Linux
Desktop Env: Xmonad
Windowing System: X11

**Comment by HusseinKabbout** [comment]
I don't think this is a bug. The button says `Delete Entry`, which I would interpret as "Delete entry in the database". If you want to manipulate the autotype settings, then you would have to go to the items settings.

![image](https://user-images.githubusercontent.com/31096104/163465174-55cd6b2c-5b36-473b-ac5b-1eb303b27b9f.png)

**Comment by droidmonkey** [comment]
Yah this isn't a bug. It's a preview pane, not an editing pane. By default the program asks before deleting anything. It may just be moved to the recycle bin.

**Comment by schoettl** [comment]
@HusseinKabbout I didn't mean the delete button, I mean the delete _key_ on the keyboard. I consider this as a usability bug: You select something in a list, you press the delete key – and then instead of the just selected item something different is deleted.

Also, KeePassXC does not ask me, if I really want to delete an item. I just tested this after resetting my settings to default.

A simple fix would be to make the preview list of auto-type items inactive i.e. unselectable. Selecting things there don't have an effect anyway, right?

**Comment by HusseinKabbout** [comment]
> Selecting things there don't have an effect anyway, right?

Yeah I think so, maybe turning this off might be more user friendly.

**Comment by schoettl** [comment]
> > Selecting things there don't have an effect anyway, right?
> 
> Yeah I think so, maybe turning this off might be more user friendly.

I think it would be a good option to turn it off. One can still see the auto-type options by clicking the auto-type button in the toolbar and that even has an useful effect ;)
