### ISSUE TITLE
KeeAgent is broken on v2.7.0

### ISSUE THREAD

**Issue by tolgahanakgun** [keepassxreboot/keepassxc#7613]
## Overview
KeeAgent is not working with v2.7.0. I was using KeeAgent v0.12.1 plugin with KeePass v2.5.0 (64-bit) as my SSH agent. This setup was working fine with v2.6.6. However, with the latest v2.7.0 update, it has stopped working.

Downgrading back to v2.6.6 solves the issue.

## Steps to Reproduce
1. Install KeePass v2.5.0 and add KeeAgent v0.12.1 plugin to KeePass.
2. Run KeePass, KeePassXC and KeeAgent
3. Enable SSH Agent Integration KeePassXC
4. Add an SSH key to your KeePassXC database
5. Try to add the SSH key to SSH agent.
6. You will see "No agent running, cannot add identity." in KeePassXC main windows

## Debug Info
```
KeePassXC - Version 2.7.0
Revision: d7a9ef4

Qt 5.15.3
Debugging mode is disabled.

Operating system: Windows 10 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.19042

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 2.18.1
```

**Comment by droidmonkey** [comment]
Do you have OpenSSH Agent or  Paegent running in windows?

**Comment by hifi** [comment]
Do you you have both agents enabled in KeePassXC settings, OpenSSH and Pageant?

**Comment by TomBaxter** [comment]
Are you using the snap install? There seem to be several new issues with the 2.7 snap. Possibly all related.

**Comment by droidmonkey** [comment]
You cannot use SSH Agent with Snap.... and no this is a Windows report.

**Comment by TomBaxter** [comment]
Oops. Sorry. I'll stop.

**Comment by tolgahanakgun** [comment]
- I run only KeeAgent.
- Only "Enable SSH Agent Integration" option is enabled
- I installed via this msi file [KeePassXC-2.7.0-Win64.msi](https://github.com/keepassxreboot/keepassxc/releases/download/2.7.0/KeePassXC-2.7.0-Win64.msi)

**Comment by FischLu** [comment]
> * I run only KeeAgent.
> 
>     * Only "Enable SSH Agent Integration" option is enabled
> 
>     * I installed via this msi file [KeePassXC-2.7.0-Win64.msi](https://github.com/keepassxreboot/keepassxc/releases/download/2.7.0/KeePassXC-2.7.0-Win64.msi)

if the v2.6.6 worked for you, I think you need to check "use Pageant" as well, as it was the default agent used in v2.6.6

**Comment by tolgahanakgun** [comment]
When I checked "Use Pageant", it worked. Thanks @FischLu. Adding KeeAgent to the options or adding KeeAgent to the Pageant option help to solve the confusion.
