### ISSUE TITLE
Bug in copy password to clipboard selection (Top center key selection)

### ISSUE THREAD

**Issue by GrapheneSlut** [keepassxreboot/keepassxc#7616]
1. Open dashboard
2. Select entry
3. Select key at top to copy password to clipboard
4. URL is copied to clipboard

## Expected Behavior
[NOTE]: # Password to clipboard

## Actual Behavior
[NOTE]: # URL copied to cliboard

## Context
[NOTE]: # Made sure to select key - confirmed URL was copying by viewing box. Repeated process. Sometimes got the URL sometimes the Password. 

KeePassXC - Version 2.7.0
Revision: 20c9ac1
Distribution: Snap

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux

**Comment by droidmonkey** [comment]
There is no way you can sometimes get a password and sometimes get a URL. Make sure you are clicking the KEY and they you don't have the URL as your password. I cannot reproduce this at all.

**Comment by GrapheneSlut** [comment]
Droidmonkey - This happens when I click the url in the bottom left of the screen. It takes me to the website, then  there is a border of dashes around the URL and I press the (key) button to copy password to clipboard, it copies the URL. I may be able to provide a video .

**Comment by droidmonkey** [comment]
You will definitely need to provide a video

**Comment by yasbow** [comment]
I can confirm GraphenSlut reported bug.
1. Select an entry in your database (the entry line background becomes dark green)
2. Click on the URL field (for example) in the lower frame, the entry line loses the focus and its background becomes light green
3. Select key at top of the GUI to have password in the clipboard
4. URL is copied to the clipboard and not the password as expected
But, if you select again the entry line between steps 2 and 3, the entry line takes the focus (and its background becomes dark green), then at step 4, the password is copied in the clipboard. 
It's the same issue if in step 3 you try to copy username : URL will be copied to clipboard. To copy username or password to clipboard, the entry line must be selected (dark green background).
