### ISSUE TITLE
Print entries

### ISSUE THREAD

**Issue by thyxNY** [keepassxreboot/keepassxc#7617]
I want to print specific entries. I have about 500 entries but some of them I want to print.
I want to:
- print specific entry (one or a few highlighted)
- print specific entries but only that with a specific flag

It is useful when I want to hide in save place a few of my printed entries.
Print dialog:
- title / user / note
- password (optional)
- one entry on page/more then one on page

**Comment by droidmonkey** [comment]
Export to HTML, print the HTML. We are not going to implement any other solution.

**Comment by thyxNY** [comment]
Yes, export to HTML is very good solution.
But is it possible to export only specific entries (highlighted or entries with specific attribute) ?
O want to print only about 20-30 entries from all 500.

**Comment by droidmonkey** [comment]
Not yet, that is tracked in another request

**Comment by thyxNY** [comment]
So I understand that maybe it will be in the next version? Great!
Could you give number of this request?

**Comment by droidmonkey** [comment]
#1940
