### ISSUE TITLE
Delete history of some entries

### ISSUE THREAD

**Issue by thyxNY** [keepassxreboot/keepassxc#7618]
I want to delete history of some highlighted entries (or all entries). Is it possible?

**Comment by droidmonkey** [comment]
Open the entry for editing, go to history tab, delete all.

**Comment by thyxNY** [comment]
How can I delete history of all my entries?

**Comment by droidmonkey** [comment]
Database -> Database Settings -> Set History to 0 or uncheck Max History Items

**Comment by thyxNY** [comment]
> Database -> Database Settings -> Set History to 0 or uncheck Max History Items

Yes, it's a good option for a new database. 
But for the existing database after changing these options and saving kdbx all records are still remains in history.

**Comment by smaczi** [comment]
So I understand that maybe it will be in the next version? Great!
Could you give number of this request?

**Comment by droidmonkey** [comment]
#1940

**Comment by schlimmchen** [comment]
> But for the existing database after changing these options and saving kdbx all records are still remains in history.

If you ticked "Max. history items" in the database settings general tab, set it to 0, and clicked OK, all history entries should be gone. At least that is what I would expect after coming the respective source code.

In any case, your particular request to purge all historic entries from a database is adressed in #7779 (set the max. age to 0 days - I hope that is sufficiently intuitive).

**Comment by thyxNY** [comment]
Yes, it works ;-)

I set clicking "Maximum number of history items" = No and the value is grayed out. Back then, nothing changed with the existing elements of history (all history preserved). 

I understand that I need to set "Max History Items" = Yes and set the value to = 0. Now is all correct and all history items are deleted.

Max History Items=No -> all history items preserved
Max History Items=Yes + Set History to 0 -> all history items deleted

I thought that setting Max History Items=No also deletes these entries...

**Comment by schlimmchen** [comment]
> I thought that setting Max History Items=No also deletes these entries...

Nope, that means "do not impose restriction on number of history entries". Glad we could clear that up.

Do you @thyxNY think this issue can be closed then? We did not yet address your wish to delete the history of a bunch of **selected** entries. I have to say I doubt that this is a useful feature. Please also look into #7779 where other "advanced" options for history cleanup are discussed.

**Comment by thyxNY** [comment]
@droidmonkey write:
> Database -> Database Settings -> Set History to 0 or uncheck Max History Items

So it is not the same ;-) 

Yes, you can close this issue! The most important thing is that I know how to do it ;-)

**Comment by droidmonkey** [comment]
Yah I was wrong, the checkbox is somewhat unintuitive from a clear history perspective

**Comment by schlimmchen** [comment]
That's a phrasing issue. Maybe the checkbox should be labeled "Limit the amount of history entries per entry to". What the second one should be labeled I don't even know because I don't understand if that limit is per entry or per database (and if it is per database what history entries are truncated if the limit is reached).

@droidmonkey Is that worth a separate issue? This one may be closed as confirmed by the author.

**Comment by droidmonkey** [comment]
Yes those deserve a new issue
