### ISSUE TITLE
the database opens in read-only mode

### ISSUE THREAD

**Issue by ksourdrille** [keepassxreboot/keepassxc#7619]
Hello to all,

I have a problem with keepassxc and the shared database, I shared my database from my computer (windows) and I want to access it from another computer (Virtual machine Ubuntu 20.04) but the problem is that the database is read-only, while I have put all the rights on the share.

Does anyone have an idea please?

Kélian

**Comment by droidmonkey** [comment]
If you are running a recent version of KeePassXC (>= 2.5) there is no such thing as read only mode. That means your permissions are not correct and we cannot help you there.

**Comment by ksourdrille** [comment]
ok thanks, I was in version 2.4.3, I took the version 2.7 all is good :)
