### ISSUE TITLE
Clipboard is not cleared after the specified time

### ISSUE THREAD

**Issue by wojciech-kopras** [keepassxreboot/keepassxc#762]
The clipboard is not cleared of my system after the specified time in Settings.
## Expected Behavior

In setting I have set to clean the clipboard after 10 s. So when I copy the password, after 10 s when I do Ctrl+V it shouldn't be there.

## Current Behavior

But I can do Ctrl+V for a much longer time than 10 s, and the password exists in clipboard. I don't know if it is cleared at all.

## Possible Solution

It worked in KeepassX, so it can be done also here.

## Steps to Reproduce (for bugs)

1.Open a database with passwords.
2.Give a mark and set timetout of 10 s in "Settings->Security->Timeouts".
3.Click "Ok"
4.Copy a password with "Ctrl+C".
5. Wait 10 s.
6. Paste the password in a text editor with "Ctrl+V".

## Context

It is security vulnerability.

## Debug Info

KeePassXC - Version 2.2.0
The same problem existed in v. 2.1.4, I hoped is got fixed in 2.2.0, but it isn't..
Libraries:
- Qt 5.9.0
- libgcrypt 1.6.1

Operating system: Ubuntu 14.04.1 LTS 
OS is actually: Linux Mint 17.2 KDE edition
CPU architecture: x86_64
Kernel: linux 3.13.0-37-generic

Enabled extensions:
- KeePassHTTP
- Auto-Type
- YubiKey

**Comment by phoerious** [comment]
You need to turn off clipboard protection in Klipper (or disable Klipper completely).

**Comment by jmbreuer** [comment]
Thanks, that could/should be made a very obvious hint, for example when the clipboard clear option is turned on. I was about to report the same bug and it was for the same reason.

Klipper came default with my install so I was not even much aware that something like that could be interfering.
