### ISSUE TITLE
KeePassXC 2.7.0 not launching on macOS 10.13.6

### ISSUE THREAD

**Issue by Diezoo** [keepassxreboot/keepassxc#7621]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
KeePassXC 2.7.0 not launching on macOS 10.13.6
Running on Intel Core 2 Duo

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Install KeePassXC-2.7.0-x86_64.dmg
2. Move .app to Application folder
3. Verification process completed with sucess
4. Double click on KeePassXC app (via Dock shortcut or real .app under Aplication folder)
5. KeePassXC is not launching; nothing append

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
1. Double click on KeePassXC app (via Dock shortcut or real .app under Aplication folder)
2. KeePassXC is launching

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
1. Double click on KeePassXC app (via Dock shortcut or real .app under Aplication folder)
2. KeePassXC is not launching; nothing append

## Context
[NOTE]: # ( Give us any additional information you may have. )
No issue with KeePassXC 2.6.6

[NOTE]: # ( Paste debug info from Help → About here )
Not possible to paste "Help -> About here" as KeePassXC is not launching

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS
Desktop Env: N/A
Windowing System: N/A

**Comment by droidmonkey** [comment]
High Sierra is no longer supported by mac

**Comment by Diezoo** [comment]
Yes. If High Sierra is no longer supported by KeePassXC 2.7.0, please update https://keepassxc.org/download/ page because "Binary bundle (macOS 10.13+)" is mentionned. Thx.

**Comment by phoerious** [comment]
The deployment target is set to 10.13 for x64 and 11 for arm64, so in theory it should work. But I have no way of checking what the lowest version is that actually works in practice. Perhaps that's also the Qt dependency, which I could not fully recompile with 10.13 as a target due to some Homebrew issues.

**Comment by phoerious** [comment]
I updated it to 10.15, which is three versions back, but I cannot check if it actually works there.

**Comment by minott** [comment]
My 2 cents on this issue... I'm currently using 10.13.6 and KeePassXC 2.7.0 works for me.
In order to try to replicate the issue, I created a new user account and downloaded again the latest version, I followed the steps mentioned above and had no problems at all.
Let me know if I should try something else, I would be happy to help you with that.

**Comment by phoerious** [comment]
Thanks, so it does work in general. Anyway, I'll leave the min version at 10.15. People being able to run it on something older see it as a bonus.

**Comment by droidmonkey** [comment]
Going to close this as it appears to be a localized issue to the user.

**Comment by daviewales** [comment]
Confirming that 2.7.1 does in fact work on 10.13.6. Please change the min version on the Download page back to 10.13, as seeing '10.15' prevented me from trying to upgrade to the latest version of KeePassXC until I saw minott's comment above.

**Comment by droidmonkey** [comment]
We only support 10.15 and above, that is why it's written there.

**Comment by daviewales** [comment]
By support, do you mean that you only accept bug reports for 10.15+?
It would be nice if the download page could be a bit clearer. Something like:

'Deployment target: 10.13, official support 10.15+'.

That would give me the confidence to try the build on my system, but I would also understand that I can't expect 10.13 specific bugs to be fixed.

**Comment by phoerious** [comment]
We have no way of testing old macOS releases. With 10.15 we can still assume sufficient backwards compatibility, but for 10.13 we cannot guarantee anything. If your macOS version is marked as unsupported and it works anyway, good for you. But if it's the other way round, we get many angry users.

**Comment by dgedgedge** [comment]
OK but when installing the application it refuses to run because of the release of OSX....
![Capture d’écran 2022-11-01 à 11 22 17](https://user-images.githubusercontent.com/17098018/199212677-bc72e572-72b7-4a55-9d3d-302da576b348.png)



Note: Release 2.7.4

**Comment by phoerious** [comment]
Your version is unsupported. Use macports if you need something built for a legacy version.

**Comment by cheesedasher** [comment]
> OK but when installing the application it refuses to run because of the release of OSX.... ![Capture d’écran 2022-11-01 à 11 22 17](https://user-images.githubusercontent.com/17098018/199212677-bc72e572-72b7-4a55-9d3d-302da576b348.png)
> 
> Note: Release 2.7.4

I'm on High Sierra 10.13.6 for specific applications I use. I have found the latest I can run is 2.7.1. I wouldn't recommend using the legacy macports.
