### ISSUE TITLE
Keepass 2.7.0 intermittently asking to unlock an ulocked database

### ISSUE THREAD

**Issue by ioogithub** [keepassxreboot/keepassxc#7624]
## Overview
Starting with version 2.7.0, when an app requests a password from keepassxc using secret service, a dialog box appears asking to unlock the keepass database however the database is already unlocked.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Open an app that needs to request a secret stored in keepassxs
2. A dialog box appears asking to unlock the keepass database, the password field is empty.
3. The database is already unlocked.

## Expected Behavior
Keepassxc should realize that the database is already unlocked and supply the secret as it did in previous versions.

## Actual Behavior
Keepassxc 2.7.0 now asks to unlock the database again and does not supply the secret.

## Context
Keepass worked perfectly in the previous versions. I did a distupdate and got this new version (2.7.0). The problem happens intermittently (not every time).

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.0
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: KDE Neon
Windowing System: X11

**Comment by droidmonkey** [comment]
duplicate

**Comment by ioogithub** [comment]
I can't find the issue report that is a duplicate of this one, can you link it?

Has a fix been issues or should I revert to the previous version?

**Comment by michaelk83** [comment]
Probably #7574 and possibly related to #7571 .
