### ISSUE TITLE
Macro key dont work for filling in fields

### ISSUE THREAD

**Issue by vampyren** [keepassxreboot/keepassxc#7625]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1.  Just use my Logitech G915 macro key on any field
2. Instead of the text it writes "vvvvvvvvvvvvvvvvvv" 
3. 

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
The macro key is set to type my email. This works in every other program except Keepassxc and actually also Enpass. 
Even in mSecure (another password manager) or any other program i use so far. I thought it was only enpass but now 
it happens here also.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

## Context
[NOTE]: # ( Give us any additional information you may have. )
I have Logitech G915 and can set actions for specific keys, like when i press F1 it type my password, F2 emulate key strokes like up or down etc....
The one i use now is simple, just adds a text i set to my F1 which is my email. 

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.0
Revision: d7a9ef4

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 11

**Comment by droidmonkey** [comment]
Happens in every input field? Qt bug if so, nothing we can do to fix that.

**Comment by vampyren** [comment]
> 

Yes tried all fields , even in search field.

**Comment by droidmonkey** [comment]
This is definitely a Qt bug
