### ISSUE TITLE
Auto-Type: modifier for WIN key not working

### ISSUE THREAD

**Issue by gitflo** [keepassxreboot/keepassxc#7626]
Hi,

just tested 2.7.0, the # modifier is not recognized at all, although promised here:

Supported in 2.7.0, use the # modifier. `#d` types WIN+D

_Originally posted by @droidmonkey in https://github.com/keepassxreboot/keepassxc/issues/7537#issuecomment-1068449818_

**Comment by droidmonkey** [comment]
Sure enough there is a bug here. Already fixed, will be in 2.7.1
