### ISSUE TITLE
Auto-type: sometimes not working properly on terminal

### ISSUE THREAD

**Issue by guidanoli** [keepassxreboot/keepassxc#7627]
## Overview

Auto-type sometimes not working on terminal.

## Steps to Reproduce
1. Make `git` request your credentials on a terminal
2. Have an entry selected on KeePassXC
3. Press Ctrl+Shift+V

## Expected Behavior
Credentials to be typed.

## Actual Behavior
Credentials were not typed.

## Context
This bug appeared when I upgraded from 2.6.6 to 2.7.0.

KeePassXC - Version 2.7.0
Revision: d7a9ef4

Qt 5.12.8
Debugging mode is disabled.

Operating system: Ubuntu 20.04.4 LTS
CPU architecture: x86_64
Kernel: linux 5.13.0-37-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.12.1

Operating System: Linux (Ubuntu 20.04 LTS)
Desktop Env: Gnome
Windowing System: X11

**Comment by cadmus-to** [comment]
I'm having similar problems as you. Do you get the same problem when typing the credentials into other software (e.g. a text editor)? It feels like the typing never actually occurs after the KeepassXC window minimises.

**Comment by droidmonkey** [comment]
Known issue, already corrected for 2.7.1. Use global Auto-Type or disable always confirm before performing Auto-Type in settings.

**Comment by guidanoli** [comment]
> Do you get the same problem when typing the credentials into other software (e.g. a text editor)?

I haven't tested this in large scale. This is a very inconsistent error. I seem to get better results when auto-typing into `gedit`.

**Comment by guidanoli** [comment]
> Use global Auto-Type or disable always confirm before performing Auto-Type in settings.

@droidmonkey I have disabled the "Always confirm" option. How do I use global Auto-type?

**Comment by droidmonkey** [comment]
Go go gadget manual: https://keepassxc.org/docs/KeePassXC_UserGuide.html#_auto_type
