### ISSUE TITLE
Add tags changes in 'Difference' tab in History

### ISSUE THREAD

**Issue by PatrickL546** [keepassxreboot/keepassxc#7632]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
Add tags changes in 'Difference' tab in History 

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )
![image](https://user-images.githubusercontent.com/75874561/159871848-e704d5b9-4dd2-4c0c-9a0c-606dc3a85a97.png)

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
I was adding tags and removed it, and I didn't see the changes in History when I looked at it.

**Comment by droidmonkey** [comment]
Good catch!
