### ISSUE TITLE
Build failures on Fedora 36 with KeepassXC develop branch

### ISSUE THREAD

**Issue by apollo13** [keepassxreboot/keepassxc#7633]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

After installing minizip-devel on Fedora 36 (minizip-3.0.2-6.fc36.src.rpm from upstream https://github.com/nmoinvaz/minizip) I get the following build failures

## Steps to Reproduce
1.  compile on fedora 36 :)

## Expected Behavior

Compile fine…

## Actual Behavior

```
[  9%] Building CXX object src/keeshare/CMakeFiles/keeshare.dir/ShareExport.cpp.o
/home/florian/sources/keepassxc/src/keeshare/ShareExport.cpp: In function ‘bool {anonymous}::writeZipFile(void*, const QString&, const QByteArray&)’:
/home/florian/sources/keepassxc/src/keeshare/ShareExport.cpp:111:9: error: ‘zipOpenNewFileInZip64’ was not declared in this scope; did you mean ‘zipOpenNewFileInZip_64’?
  111 |         zipOpenNewFileInZip64(zf,
      |         ^~~~~~~~~~~~~~~~~~~~~
      |         zipOpenNewFileInZip_64
```
also `Z_BEST_COMPRESSION` is undefined. Where from should I obtain minizip?

**Comment by apollo13** [comment]
Apparently the build only works against https://github.com/madler/zlib/tree/master/contrib/minizip and not the "fork" mentioned on https://www.winimage.com/zLibDll/minizip.html

**Comment by apollo13** [comment]
I can build on fedora using minizip-compat-devel -- I'll leave this open for the maintainers to decide which library is the wanted one. Sorry for the noise.

**Comment by droidmonkey** [comment]
The compat one is desired, will update the wiki. Minizip-ng is another ballgame. Really Fedora packaging dropped the ball here by not adding the -ng

**Comment by Germano0** [comment]
Thank you, now I am able to build KXC

**Comment by droidmonkey** [comment]
I updated the wiki

**Comment by Adadov** [comment]
I just did compile the RPM on F35.
You can find patches applied here: https://gist.github.com/Adadov/5222947aa68cc94c4a7cfc86e47dcec6
The

**Comment by Adadov** [comment]
I just made patches for spec file and ShareExport allowing 2.7.0 release to build on mock for Fedora 35 & 36.
You can find them here: https://gist.github.com/Adadov/5222947aa68cc94c4a7cfc86e47dcec6
Runs on Fedora 35, wasn't able to test run on Fedora 36
