### ISSUE TITLE
Autotype is broken in ver 2.7.0 for Ubuntu 20.04

### ISSUE THREAD

**Issue by GR5821** [keepassxreboot/keepassxc#7634]
## Overview
Autotype does not function in version 2.7.0.  The previous version worked just fine.
When going to a website that requires a user name and and password, the box is displayed.  When you go to KeepassXC and select autotype nothing is autotyped into the required box.  Am I missing something?

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. 
2. 
3. 

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows/Linux/macOS
Desktop Env: Gnome/KDE/XFCE/Mate/Cinnamon
Windowing System: X11/Wayland

**Comment by ravindragullapalli** [comment]
Happened to me too.

This happens if you enable Always ask before performing auto type. Uncheck that option if checked and try again. 

This worked for me.

![image](https://user-images.githubusercontent.com/3313079/159966679-4671935a-d781-40b5-8cd2-8260d39ed2b3.png)

**Comment by GR5821** [comment]
Yep, that works.  Thanks.

**Comment by koichirose** [comment]
It is the opposite for me.
Since updating to 2.7.0, it started asking me before performing Auto-Type. Auto-Type works with that option checked.

If I disable that option (which is my preference), Auto-Type does not work anymore if I use the keyboard shortcut.
It correctly switches to the previous application, but then it does not type anything.
It works if I right click on the entry - perform Auto-Type.

I'm using macOS 12.3.

**Comment by IzzySoft** [comment]
For me, regardless of whether "always ask" is checked or not, auto-type no longer works in console apps (i.e. via Ctrl-Shift-V; the KeepassXC window closes as if the auto-type sequence was sent, but nothing is typed).

On websites, double-clicking the entry seems to work.

I'm on Linux Mint 20.2 in case it matters (based on Ubuntu 20.04) – but I have similar problems at work with Windows-10 (using the portable version; there I downgraded to 2.6.6 again as 2.7.0 was not working with auto-type at all). Will check again on both systems once 2.7.1 is out (which is supposed to have this fixed).

**Comment by GR5821** [comment]
When will 2.7.1 be out?  If not soon, I am looking at going back to the previous version.

**Comment by tervor** [comment]
Seems to be related to #7584
