### ISSUE TITLE
After update from 2.6.6 on windows 10, window does not appear, preview black

### ISSUE THREAD

**Issue by v4k0nd** [keepassxreboot/keepassxc#7636]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
After update from 2.6.6 on windows 10 pc (which I am currently using with a remote desktop software), the window does not appear, only a black preview on the taskbar. 
This did not happen on my windows 10 laptop.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Have 2.6.6 on windows 10
2. Download 2.7.0 from main site
3. After update. only this shows up, no window, clicking on it does nothing: 
![image](https://user-images.githubusercontent.com/16004016/159991759-340dabf5-68a5-4e7e-a7b3-83e986221823.png)

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Full window appears

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Nothing visible on screen.

## Context
[NOTE]: # ( Give us any additional information you may have. )
I have downgraded to 2.6.6 via clicking the installer of 2.7.0 and selecting uninstall then right after installing 2.6.6. 
Then tried updating again, rebooted, still didnt work, then downgraded.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.0
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows
Desktop Env: 
Windowing System:

**Comment by droidmonkey** [comment]
Try the portable zip

**Comment by v4k0nd** [comment]
> Try the portable zip

Has the same result as above.

**Comment by droidmonkey** [comment]
Try this installer, doesn't use msvc libraries: https://github.com/keepassxreboot/keepassxc/releases/download/2.7.0/KeePassXC-2.7.0-Win64-LegacyWindows.msi

Want to narrow down the cause. 

If that still doesn't work, try removing your settings from AppData/local/keepassxc

**Comment by v4k0nd** [comment]
Got a new error after installing:
![image](https://user-images.githubusercontent.com/16004016/159999575-b9dd6217-0709-4112-b802-d7ee578a0b6d.png)

However after an uninstall and reboot, then install, I got the same no window, blank preview with the legacy too..

**Comment by v4k0nd** [comment]
Deleting my settings from `appdata/local/keepassxc` (while it is installed) did not help.
Should I have uninstalled keepassxc, then delete my settings, then reinstall?

**Comment by droidmonkey** [comment]
You seem to have much bigger problems at this point. This is beyond just our program

Last try, can you do this: https://keepassxc.org/docs/KeePassXC_UserGuide.html#_screenshot_security

**Comment by v4k0nd** [comment]
Very good guess, that fixes it. So I am remotely logged in to my main pc so I guess that is why I never see the window, but running  `.\KeePassXC.exe --allow-screencapture` launches it so that I can view it.

Now, all my other programs (and games) work perfectly while I am remotely logged in, so I never thought this could be a problem.

Was this feature not present on previous versions (lower than and including 2.6.6)? Since the previous version works just fine.

Edit # 1: changed the phrasing of what was the problem

**Comment by phoerious** [comment]
If you are using it remotely, then it probably does launch, you're just not seeing it without the flag.

**Comment by v4k0nd** [comment]
For anyone else trying to set this up so that the shortcut in the start menu launches keepassxc viewable through remote desktop software, append the `--allow-screencapture` to the end of the `target` field.

`"C:\Program Files\KeePassXC\KeePassXC.exe" --allow-screencapture`

![image](https://user-images.githubusercontent.com/16004016/160011496-67aae3f8-a23d-4f5d-8b66-a7c234dc1d60.png)

This only solves the "problem" if you open the program from the start menu.
If you want to run it on startup with this flag, check out this comment (requires registry edit): https://github.com/keepassxreboot/keepassxc/issues/7580#issuecomment-1076770856

**Comment by droidmonkey** [comment]
Make sure to include that very important detail (remote access) in the future ;-)

**Comment by v4k0nd** [comment]
**EDIT**: As of 2.7.5, there is an option in the GUI for allowing screencapture

I seem to come back to my comment often, when on a new machine I want to always allow screencapture (as the last line of my previous comment shows), but I forget where the keepassxc registry is.
So I created a powershell script to append `--allow-screencapture` to the correct registry key for me. 
_CAVEAT_: only works if you already set keepassxc to run on startup!

```powershell
$registryPath = "HKCU:\Software\Microsoft\Windows\CurrentVersion\Run"
$entryName = "KeePassXC"
$arguments = "--allow-screencapture"

$keePassEntry = Get-ItemProperty -Path $registryPath -Name $entryName -ErrorAction SilentlyContinue

if ($keePassEntry -ne $null) {
    $currentValue = $keePassEntry.$entryName
    if (-not $currentValue.Contains($arguments)) {
        $newValue = $currentValue + " " + $arguments
        Set-ItemProperty -Path $registryPath -Name $entryName -Value $newValue
        Write-Host "KeePassXC registry entry updated successfully."
    } else {
        Write-Host "KeePassXC registry entry already contains the --allow-screencapture flag."
    }
} else {
    Write-Host "KeePassXC entry not found in registry. Please make sure KeePassXC is installed and set to run at startup."
}
```

**Comment by tmfksoft** [comment]
Just ran into this myself, may be worth KeePass showing a warning message on startup to let the user know KeePass won't be visible while screen capturing. Left me and some colleagues scratching our heads for a while and just assumed it was a corrupted install.

We use KeePass on a virtual machine we access via VNC so we're unable to open KeePass and enable screencapture.

**Comment by manujarvinen** [comment]
> Just ran into this myself, may be worth KeePass showing a warning message on startup to let the user know KeePass won't be visible while screen capturing. Left me and some colleagues scratching our heads for a while and just assumed it was a corrupted install.

Same here, I was installing my system remotely and started thinking something was broken.
A warning message on startup would be nice.
Also, I couldn't close the program unless I went to task-manager and killed it. Which made me suspect it was broken even more.
