### ISSUE TITLE
choose in which webbrowser the url should be opened

### ISSUE THREAD

**Issue by cjs1976** [keepassxreboot/keepassxc#7644]
Hi,
KeePassXC is great, but I miss one particular feature of KeePass. The possibility to choose in which webbrowser the url should be opened. Maybe there is a chance to add such a feature in the future?
Thanks,
Christian
![25-03-2022_11-43-37](https://user-images.githubusercontent.com/20856775/160106900-52fb9e57-a82d-4633-ab26-d929627917de.jpg)
.

**Comment by droidmonkey** [comment]
Duplicate request
