### ISSUE TITLE
Fill Credentials: Select custom attribute on custom login fields list

### ISSUE THREAD

**Issue by chemedev** [keepassxreboot/keepassxc#7645]
## Summary
I'd like to add the custom attribute for an entry to the custom login fields detected via extension in the browser. Currently I can only chose between username, password and TOTP and the only way to fill the custom attribute is using global auto-type.

## Context
I have credentials with username, password and ID number but can only fill the first two fields with keepassxc.

**Comment by droidmonkey** [comment]
@varjolintu we need to document the KPH: syntax and workflow.

**Comment by varjolintu** [comment]
@droidmonkey I'm tempted to do a quick video about it.

**Comment by varjolintu** [comment]
@me-chell https://keepassxc.org/docs/#faq-browser-string-fields Take a look at this.

**Comment by chemedev** [comment]
Holy smoke! I didn't get that after discarding the TOTP I could choose to add more fields. Nevermind, I'll close this :)
