### ISSUE TITLE
Upgrading to 2.7.0 enables Quick Unlock without asking or notifying

### ISSUE THREAD

**Issue by xxyxxyxyx1** [keepassxreboot/keepassxc#7646]
## Overview
Yesterday I upgraded to version 2.7.0 of KeePassXC. Previously, I did not have Quick Unlock enabled. After the upgrade, it was enabled in the settings. There was no request or notification of the settings change; it just happened silently. 

I don't think it's reasonable to change a security-impacting setting without obtaining the user's permission or confirmation, and this setting significantly impacts security. Bad actors and law enforcement can compel users to unlock devices with biometrics fairly easily. It is a significant setting that should not change silently. 

While I have my macOS computer set to unlock by fingerprint (after password unlock on boot), this is a medium-security barrier. Compelling this unlock would not grant an attacker access to the really sensitive stuff: online accounts that always require sign-in, and legal documents stored as keepassxc attachments. I am sure this security model is not uncommon for keepassxc + macOS users. 

Please consider adding a notification, warning or request before automatically enabling this setting for users upgrading from an older version. Even though quick unlock may be a fine choice for many people, it impacts security. Thanks. 

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Update to 2.7.0

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
A prompt requesting permission to change the setting, a prompt suggesting to change the setting manually, or at least a warning that the setting will be enabled. 

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Quick unlock is silently enabled after the update. 

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.0
Revision: d7a9ef4

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS

**Comment by droidmonkey** [comment]
You can easily disable it in the security settings. And no, this does not decrease security.

**Comment by TinoDidriksen** [comment]
> And no, this does not decrease security.

This greatly decreases security. My Windows Hello login is a 4 digit PIN, while my database password is an actual complex password.

> You can easily disable it in the security settings.

What does this actually do? I'm in the same situation. I upgraded, unlocked, didn't really consider the implications of the Hello login, but then promptly disabled it when I had thought about it. But what does this mean now? Does Windows now have unlock credentials for my database permanently stored, even if not used? And if so, how can I remove that?

**Comment by phoerious** [comment]
> This greatly decreases security. My Windows Hello login is a 4 digit PIN, while my database password is an actual complex password.

Your database is still encrypted on disk and the 4-digit PIN only allows access to a database that is already in your main memory (i.e. it was unlocked previously). Windows also doesn't allow an arbitrary number of attempts in rapid fashion for bruteforcing the PIN.

> But what does this mean now? Does Windows now have unlock credentials for my database permanently stored, even if not used? And if so, how can I remove that?

Disabled means disabled. The credentials are removed when you lock your database or close KeePassXC.

**Comment by droidmonkey** [comment]
Y'all should try reading the documentation I wrote....... open the user guide

**Comment by TinoDidriksen** [comment]
> Y'all should try reading the documentation I wrote....... open the user guide

I did. I read https://keepassxc.org/docs/KeePassXC_UserGuide.html#_quick_unlock which says <q><i>your credentials can be securely stored to enable subsequent unlocking of your database through biometric authentication</i></q> but doesn't say anything about when the credentials are removed from the store. I read this as Windows Hello being a keystore that you store a copy of the key into for any future use, because I am familiar with keystores.

I even skimmed the code https://github.com/keepassxreboot/keepassxc/blob/develop/src/winhello/WindowsHello.cpp but saw no calls to `KeyCredentialManager::DeleteAsync()`.

Now that I have actually read up on Windows Hello and read the code (not just skimmed), I see that Hello is only used to encrypt an in-memory copy of the key and that this naturally goes away when the process ends.

But none of your answers says this. The credentials are clearly not removed when you lock the database - they're just held in a temporary differently encrypted place. If I enable Hello, unlock the database, manually lock the database, then next unlock will use Hello again. Wiping that requires closing the process.

So given that it's optional and there are no lasting security implications by having it enabled by default, then it's fine. At least for Hello - I haven't read up on how the other platforms are implemented.

**Comment by xxyxxyxyx1** [comment]
I read the Quick Unlock user guide before posting this. Here it is for easy reference:
[https://keepassxc.org/docs/KeePassXC_UserGuide.html#_quick_unlock](https://keepassxc.org/docs/KeePassXC_UserGuide.html#_quick_unlock)

Here are logical steps for why this decreases security. I tried to be clear in the OP, but I will try again. Please tell me which number contains an error. 

I have a database on macOS. I unlock it with a password, then close it using 'Database > Close Database'. 

1.  Prior to 2.7, this database could only be unlocked by typing the original password again. 
2. With 2.7, the closed database can be unlocked using only a fingerprint. 
3. In countries including the USA, law enforcement has the power to physically force a fingerprint device unlock. They have no such power to compel someone to reveal a remembered password. 
4. Point number 3 constitutes a decrease in security.

**Comment by droidmonkey** [comment]
If you are worried about 3, then you have two choices when unlocking for the first time: press CANCEL when prompted for the biometrics OR disable the feature. If you close the database then you will be required to re-enter your credentials again.

**Comment by WofWca** [comment]
> press CANCEL when prompted for the biometrics

They could physically stop me from doing that.

> OR disable the feature

It is possible to never discover that the feature got enabled. For example, if every morning I use the PC, then lock it (expecting the database to also get locked as I have "Lock databases when session is locked or lid is closed" enabled), then go to work, and then the PC powers off after a couple of hours of idling. So I would never  notice that when I lock the PC, the database can be unlocked with a PIN or a fingerprint. Let's say I tested it on a previous version, where it would require the password even if the PC didn't turn off.

Another example: me and my wife use the same Windows user account, but different databases. I leave and lock the PC (expecting the database to also get locked). Then my wife comes - boom - she can unlock my database with a PIN.

**Comment by Groxx** [comment]
Yeah, I'll throw in a "+1 do not like" too.  Optional weakening needs to be opt-in, not opt-out.

As far as weakening vs not: you leave fingerprints everywhere.  And biometrics hardware has a very-well-established history of not reliably rejecting artificial duplicates.  Biometrics are not passwords, I don't leave my password on sticky notes in coffee shops.  
I also use a different password for my laptop compared to my keepass store for exactly this kind of reason - my laptop is less dangerous to lose access to than my password store.  This ties those two actions together without first getting consent.

**Comment by droidmonkey** [comment]
It's an option disabled in mere seconds. If you are on windows you can even press CANCEL when the windows hello dialog shows and your credentials will not be saved. Working to make this a little more explicit, but at the end of the day you choose to use the feature or not.
