### ISSUE TITLE
Program Startup Showing Black Window/Frame

### ISSUE THREAD

**Issue by kaemitsu** [keepassxreboot/keepassxc#765]
### Issue Description
When starting the program, it displays a black window/frame on the left side of the GUI before displaying the database master password prompt window.
## Expected Behavior

The program should start just like KeePassX 2 does: without the black window/frame displaying, e.g.:
![keepassx](https://user-images.githubusercontent.com/30067080/28154960-6274a00e-677a-11e7-92f3-0ccfeac978c8.gif)

## Current Behavior

As described above, when the program is started it displays a black window/frame on the left side:
![keepassxc](https://user-images.githubusercontent.com/30067080/28155016-b1d6c24e-677a-11e7-92a4-d701c04e2ec3.gif)

## Possible Solution

Use the KeePassX 2 code as reference for this part of the program, comparing both codes to be able to detect what is causing such behavior in the program's GUI, and hopefully resolve this issue. This issue or bug could be caused by the new Qt5 libraries or some error in their configuration or in the code implementing them.

## Steps to Reproduce or Possible Requirements
1. Have installed the 3.24.2-1 version of the GNOME Desktop Environment (gnome-shell).
2. Open the program as usual: by pressing the program's icon and waiting for it to open.
3. After the program opens, before the database unlock window, the black window/frame is displayed.

## Context

Be able to use this program without seeing this black window/frame: with a more attractive, elegant and flawless program GUI startup.
## Debug Info

KeePassXC - Version 2.2.0
Revision: caa49a8ef3ee28ed478192389b21d61107b3b8e0

Libraries:
- Qt 5.9.1
- libgcrypt 1.7.8

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 4.4.52-1-lts

Enabled extensions:
- KeePassHTTP
- Auto-Type
- YubiKey

**Comment by kaemitsu** [comment]
Tried building from source and running the program to verify if the issue was resolved on the latest version of the source code in the repository; however, the issue is still present and the black window/frame keeps displaying on the program startup.

KeePassXC - Version 2.2.0
Revision: 99e3af8ff71c401a4854af353667da58bc37299f

**Comment by phoerious** [comment]
I'm not sure if we can fix this. Looks more like a Qt problem to me.

**Comment by kaemitsu** [comment]
I was thinking the same thing; since, KeePassX 2 uses Qt4 and KeePassXC Qt5, the problem could only be present on the newer version of the libraries, and not in the source code of the program itself.

I tried to look for the sourced file that contains the program's startup procedure; however, I could not find the code block responsible of the action.
