### ISSUE TITLE
Process to Downgrade after failed version update

### ISSUE THREAD

**Issue by sengsational** [keepassxreboot/keepassxc#7650]
## Overview
Steps to take to get previous version installed when the current version is broken, while keeping all data and settings.

## Steps to Reproduce
1. Attempt to install a new version
2. New version doesn't run properly
3. Download previous release
4. Installer says "A later version of KeePassXC is already installed.  Setup will now exit."

## Expected Behavior
Installer either gives you the option to override or installer "realizes" the current version is broken and allows downgrade.

## Actual Behavior
User is left with a broken version of the software, unable to load a previous, working version.

## Context
Operating System: Windows

**Comment by hifi** [comment]
Just uninstall the new version. It doesn't delete your databases.
