### ISSUE TITLE
KeePassXC-2.7.0-x86_64.AppImage crashes with error : keepassxc: symbol lookup error: /usr/lib64/libssl.so.1.1: undefined symbol: EVP_idea_cbc, version OPENSSL_1_1_0

### ISSUE THREAD

**Issue by rstaub77** [keepassxreboot/keepassxc#7651]
## Overview
New KeePassXC-2.7.0-x86_64.AppImage crashes right after launch.
Previous KeePassXC-2.6.6-x86_64.AppImage worked just fine.

## Steps to Reproduce
Just launch the image as an executable

## Expected Behavior
KeePassXC

## Actual Behavior
GUI shows up during a fraction of second, then the program crashes.
If launched from the console, here is what I get
~~~~sh
YubiKey: Failed to establish PCSC context.
YubiKey: PCSC interface is disabled or not initialized.
QObject::startTimer: Timers cannot have negative intervals
keepassxc: symbol lookup error: /usr/lib64/libssl.so.1.1: undefined symbol: EVP_idea_cbc, version OPENSSL_1_1_0
~~~~

## Context
Host system is an up to date Gentoo Linux.
AppImage should not depend on the hosting systme though, as it includes all the necessary files.
Embedded openssl seems to lack some built-time options.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.0
Revision: AppImage x64

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: Fluxbox
Windowing System: X11

**Comment by hifi** [comment]
I don't think our AppImage embeds OpenSSL for security reasons at the cost of compatibility.

**Comment by rstaub77** [comment]
You're right, the referenced file /usr/lib64/libssl.so.1.1 is the one installed on the host OS.
I understand the choice not to embed openssl in the AppImage.
What I am not sure of, is why/wether the symbol EVP_idea_cbc is absolutely necessary (no option to compile it on Gentoo, I cannot say if the missing symbol is deprecated or if it is not implemented in the current 1.1.0 branch as version n is the latest and the one that is installed).
For now, I guess I will have to compile KeePassXC with the provided Gentoo ebuild, and stop using the AppImage version.

**Comment by droidmonkey** [comment]
Qt uses the openssl library so that symbol is probably used somewhere in their code base.

**Comment by rstaub77** [comment]
Actually I am using other AppImages with QT dependance that work just fine.
I wonder if this bug should remain open, or if we accounter the limits of AppImage format.

**Comment by droidmonkey** [comment]
Depends on what version of qt they are built against

**Comment by hifi** [comment]
It depends on the build system what symbols and libraries are linked with the bundled libraries and binaries unless a completely static build is shipped.

Either the other AppImages you use bundle OpenSSL or you're just lucky with the versions and symbols.

I'm pretty sure most developers bundle everything for convenience.

**Comment by rstaub77** [comment]
I guess convenience is what is looked for regarding AppImage in the first place, but I understant the concerns about security with such a project like KeePassXC for which it is legitimate to focus on security first.
By the way, I just tried the latest dev build of duckstation "qt flavour" (QT used s 5.12.8), which works fine and does not seem to contain libssl*.
I will close this bug, as compiling KeePassXC on my Gentoo does not imply to add many dependancies (actually only one in addition to the program itself).
Thanks for your answers

**Comment by jhenin** [comment]
I'm suffering from the same issue on a Mageia 8 system. I understand the security concerns, but maybe the AppImage could be linked to a slightly older version of openssl to make it more compatible?

**Comment by droidmonkey** [comment]
Use the flatpak or snap instead.
