### ISSUE TITLE
pyton secretstorage return always the item as locked since 2.7.0

### ISSUE THREAD

**Issue by iopsthecloud** [keepassxreboot/keepassxc#7653]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. activate SSI on the database 
2. search for an item
3. check is the item is locked

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

I use KeepassXC as a secret manager instead of "gnome-keyring" since KeepassXC 2.6.6. Everything worked as expected with all my software and especially "vorta", a borg GUI. Vorta uses the python secrestorage "pkg" to retrieve the repository password.

Since KeepassXC 2.7.0 I have an exception raised in ``/usr/lib/python3/dist-packages/secretstorage/item.py`` at line 48, indeed the lib checks if the element is locked before trying to retrieve it.

By using "dbus-monitor" I see what the library returns as an exception. I have several databases (all open) but I have only one with the SSI service active and this one is "unlocked" at the time of my tests.

When performing the same test on a KeepassXC 2.6.6 version the result is expected with a "False" response.

Translated with www.DeepL.com/Translator (free version)

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

When python-secretstorage try to retrive the state of the lock for a specific item, I got "True" even if the database is unlock and the item seems to be visible.

## Context
[NOTE]: # ( Give us any additional information you may have. )

All others integrations seems to be ok.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.7

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: Gnome
Windowing System: X11

extract of DBus-monitor when failed
```
DBus.Properties; member=Get
   string "org.freedesktop.Secret.Item"
   string "Label"
method return time=1648225971.665882 sender=:1.99 -> destination=:1.184 serial=112 reply_serial=9
   variant       string "ssh://borg@X/X"
method call time=1648225971.667086 sender=:1.184 -> destination=org.freedesktop.secrets serial=10 path=/org/freedesktop/secrets/collection/keyring/65d2e05e079e4a33a41e0691cce3ace6; interface=org.freedesktop.DBus.Properties; member=Get
   string "org.freedesktop.Secret.Item"
   string "Locked"
method return time=1648225971.667615 sender=:1.99 -> destination=:1.184 serial=113 reply_serial=10
   variant       boolean true
```

extract of DBus-monitor when it works
```
method call time=1648226107.212511 sender=:1.264 -> destination=org.freedesktop.secrets serial=36 path=/org/freedesktop/secrets/collection/keyring/037017ad696a4ec186452617ff1a0e1c; interface=org.freedesktop.DBus.Properties; member=Get
   string "org.freedesktop.Secret.Item"
   string "Label"
method return time=1648226107.212896 sender=:1.83 -> destination=:1.264 serial=188 reply_serial=36
   variant       string "ssh://X/X"
method call time=1648226107.213767 sender=:1.264 -> destination=org.freedesktop.secrets serial=37 path=/org/freedesktop/secrets/collection/keyring/037017ad696a4ec186452617ff1a0e1c; interface=org.freedesktop.DBus.Properties; member=Get
   string "org.freedesktop.Secret.Item"
   string "Locked"
method return time=1648226107.214036 sender=:1.83 -> destination=:1.264 serial=189 reply_serial=37
   variant       boolean false

```

**Comment by Aetf** [comment]
This is the new "Confirm when passwords are retrieved by clients" feature you can find in Settings.

Per the [spec](https://specifications.freedesktop.org/secret-service/latest/ch08.html), individual items can be locked even if the database containing it is already unlocked. Clients (in this
case borg) are supposed to unlock the item (calling `item.unlock()` in python secretstorage) before using it.

KPXC uses individual item locking to implement prompt/authorization of individual clients.

As a workaround, you can disable "Confirm when passwords are retrieved by clients" to revert to 2.6.x behavior.

**Comment by iopsthecloud** [comment]
> This is the new "Confirm when passwords are retrieved by clients" feature you can find in Settings.
> 
> Per the [spec](https://specifications.freedesktop.org/secret-service/latest/ch08.html), individual items can be locked even if the database containing it is already unlocked. Clients (in this case borg) are supposed to unlock the item (calling `item.unlock()` in python secretstorage) before using it.
> 
> KPXC uses individual item locking to implement prompt/authorization of individual clients.
> 
> As a workaround, you can disable "Confirm when passwords are retrieved by clients" to revert to 2.6.x behavior.

I confirmed that do the job. Thanks a lot, I'll investigate if vorta try to unlock the entry before use it.
