### ISSUE TITLE
Extend Auto-Type selection window with filter search bar for all existing items

### ISSUE THREAD

**Issue by sandreas** [keepassxreboot/keepassxc#7654]
## Summary
I would like to suggest adding add a filter search bar for all existing items to look up  entries, that the Auto-Type feature did not match first but that I know do exist. 

Szenario without this feature:

- Pressing the Auto-Type shortcut does not find any match or only "unwanted" matches (because the title of the page changed or is non-unique)
- I Click `cancel` to stop the Auto-Type completely
- I open KeepassXC UI
- I am searching for the wanted item
- I copy the credentials manually
- I reopen the login window
- I paste the credentials manually

Scenario with the new feature:
- Pressing the Auto-Type shortcut does not find any match or only "unwanted" matches (because the title of the page changed or you)
- I use the new search bar to look up the correct item in the database, which then appears in the list of matches
- I click the wanted item, and Auto-Type proceeds

## Examples
![keepassxc_screenshot](https://user-images.githubusercontent.com/2050604/160199109-180421c9-f603-48b7-bb11-931e563df7b9.png)

## Context
Sometimes pages do not have a unique title or url that can be matched. Especially when I don't use the landing page directly but a subdomain page not referencing the login form correctly. This always leads to the "OK now I must cancel the whole Auto-Type thing" situation, instead of just having a little search bar like in the main window to lookup the item that I was looking for.

What do you think?

**Comment by droidmonkey** [comment]
I think it's an amazing idea, and you should update to 2.7.0 to use it immediately

**Comment by sandreas** [comment]
Awesome, I did totally miss that, sorry for wasting your time :-)
