### ISSUE TITLE
keepassxc-cli version 2.7.0 does not handle yubikey Ubuntu 20.04

### ISSUE THREAD

**Issue by MarcSchuhTNG** [keepassxreboot/keepassxc#7655]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
The bash command 
`keepassxc-cli show -s -y 2 $keepass_location "$entry_title"`
does not work since the upgrade to 2.7.0. 
I get the error message: 

> Error while reading the database: Unable to calculate database key: General: Could not find interface for hardware key with serial number 0. Please connect it to continue.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Ubuntu 20.04
2. Version 2.7.0
3. bash command `keepassxc-cli show -s -y 2 $keepass_location "$entry_title"`

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
I would like to get the password. 

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
I get the error message:

> Failed to issue challenge:  "General: Could not find interface for hardware key with serial number 0. Please connect it to continue."
Error while reading the database: Unable to calculate database key: General: Could not find interface for hardware key with serial number 0. Please connect it to continue.

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: Gnome
Windowing System: X11

**Comment by droidmonkey** [comment]
Already fixed will be in 2.7.1
