### ISSUE TITLE
Missing dll bug [v2.7.0]

### ISSUE THREAD

**Issue by cleo601** [keepassxreboot/keepassxc#7656]
When I try to run KeePassXC.exe on Windows 8.1 x64 after installing the MSI or Portable packages of version 2.7.0, I get the following error:

The program can't start because api-ms-win-core-kernel32-legacy-ansi-l1-1-0.dll is missing from your computer.
Try reinstalling the program to fix this problem.

I didn't have this issue with previous versions of KeePassXC.

KeePassXC version - 2.7.0
Operating System: Windows 8.1
Architecture: x64

**Comment by droidmonkey** [comment]
Use the legacy windows installer from the release page.
