### ISSUE TITLE
KeePassXC 2.7.0 fails to start,  ERROR: not connected to the kde-frameworks-5-qt-5-15-3-core20 content interface.

### ISSUE THREAD

**Issue by fcostin** [keepassxreboot/keepassxc#7657]
## Overview

KeePassXC 2.7.0 (previously installed as snap) now fails to launch in Ubuntu 21.10.

## Steps to Reproduce
1. open terminal and run `keepassxc`

## Expected Behavior

`keepassxc` launches and displays UI presenting user the option to open password database.

It was working for me one week ago (2022/03/19).

## Actual Behavior

`keepassxc` process does not show UI, immediately exits with exit code 1
the following error message is displayed:
```
ERROR: not connected to the kde-frameworks-5-qt-5-15-3-core20 content interface.
```

## Context
Operating System: Ubuntu 21.10 (64-bit)
Desktop Env: Gnome 40.4.0
Windowing System: Wayland

keepassxc previously installed as snap, details below:

```
$ snap info keepassxc
name:    keepassxc
summary: Community-driven port of the Windows application “KeePass Password
  Safe”
publisher: Jonathan White (keepassxreboot)
store-url: https://snapcraft.io/keepassxc
contact:   https://github.com/keepassxreboot/keepassxc
license:   unset
description: |
  KeePassXC is an application for people with extremely high demands on
  secure
  personal data management. It has a light interface, is cross-platform and
  published under the terms of the GNU General Public License.
commands:
  - keepassxc.cli
  - keepassxc
  - keepassxc.proxy
snap-id:      jf2HsR51rlftaREcwhtxiEcDc76gL4O6
tracking:     latest/stable
refresh-date: 3 days ago, at 07:09 AEDT
channels:
  latest/stable:    2.7.0 2022-03-22 (1541) 21MB -
  latest/candidate: 2.7.0 2022-03-22 (1541) 21MB -
  latest/beta:      2.7.0 2022-03-22 (1541) 21MB -
  latest/edge:      2.7.0 2022-03-23 (1546) 21MB -
installed:          2.7.0            (1541) 21MB -
```

**Comment by fcostin** [comment]
another user recently reported the same symptom at askubuntu: https://askubuntu.com/questions/1398928/keepassxc-just-stopped-running

**Comment by fcostin** [comment]
Here is a workaround until a fix is available -- tell snap to revert the installed version of keepassxc snap package to the previous stable version:

```
sudo snap revert keepassxc
```
this should succeed and display something like:
```
keepassxc reverted to 2.6.6
```

keepassxc 2.6.6 can launch normally and open the password database

**Comment by droidmonkey** [comment]
You need to install the kde framework. If it still doesn't work then your system can't use the snap unfortunately. 

https://askubuntu.com/questions/1360564/getting-error-not-connected-to-the-kde-frameworks-5-plug-content-when-trying-to

**Comment by fcostin** [comment]
Is it expected that this kind of thing breaks when snap auto-upgrades keepassxc snap release package from 2.6.6 to 2.7 without user intervention?

apologies if i have reported the issue to the wrong issue tracker, and this should be reported to some other issue tracker responsible for keepassxc snap packaging issues

**Comment by droidmonkey** [comment]
We switched to the modern way to package snaps. So this is a snapd, ubuntu bug.

**Comment by fcostin** [comment]
> We switched to the modern way to package snaps. So this is a snapd, ubuntu bug.

Thank you for following up. Yes, I agree, it may be an issue with snapd not installing new extension dependencies when auto refreshing a snap to latest stable version.  snap appears to install kde-neon extension correctly when you `snap install keepassxc` and get version 2.7.0, but snapd appears to fail to install kxe-neon extension when it auto updates keepassxc package,  and the new version of the package adds the new kde-neon extension.

I am not familiar with snapd, snap packaging, but had a read of some of the snapcraft docs.


I speculate that a sequence of events something like the following may have caused this issue:

1. (some weeks ago) i followed instructions on [keepassxc.org](https://keepassxc.org/) to install keepassxc as a snap. this installs latest stable release of keepassxc snap package, at the time keepassxc 2.6.6
2. keepassxc works, it is excellent tool
3. a new stable release of snap package keepassxc 2.7.0 was published
4. ubuntu 21.10's snapd decided to auto refresh keepassxc version
5. speculation: while refreshing keepassxc, snapd failed to install the kxe-neon extension (?)
6. keepassxc stopped working as dependency missing


I am not able to reproduce the above chain of events as I can't see any way to install old version of keepassxc after uninstalling it, can only install latest version from stable version. When initial state is that user has no keepassxc installed, installing latest version of keepassxc causes `kde-frameworks-5-qt-5-15-3-core20` to also be installed, so keepassxc works fine!

While I still had reverted keepassxc 2.6.6 installed, I tried the following and it left me with a working keepassxc 2.7.0:

```
<intial state: keepassxc 2.6.6 snap installed and working>
sudo snap refresh
sudo snap uninstall keepassxc
sudo snap install keepassxc
```

So again, suggests defect in behaviour of snap / snapd auto refresh , if auto refresh to upgrade gives different results from uninstall, reinstall.

**Comment by fcostin** [comment]
raised issue on snapd issue tracker linking to this one:  https://bugs.launchpad.net/snapd/+bug/1966531

**Comment by fcostin** [comment]
update:

```
<intial state: keepassxc 2.6.6 snap installed and working>
sudo snap refresh
sudo snap uninstall keepassxc
sudo snap install keepassxc
```

this results in a keepassxc 2.7.0 that is able to start and show a GUI, but is not able to show file chooser dialog to open an existing password db.  this appears to be another known issue https://github.com/keepassxreboot/keepassxc/issues/7607

**Comment by droidmonkey** [comment]
Tracked here: https://forum.snapcraft.io/t/file-chooser-doesnt-show-using-kde-neon-extension/29244

**Comment by john-parker** [comment]
After:

> sudo snap refresh

Rather than: 

> sudo snap uninstall keepassxc

Use "remove" rather than "uninstall":

> sudo snap remove keepassxc
> keepassxc removed
> sudo snap install keepassxc
> keepassxc 2.7.6 from Jonathan White (keepassxreboot) installed

**Comment by iGadget** [comment]
This is still an issue when upgrading to KeePassXC 2.7.8 (snap).
I have two machines here (running Pop!OS 22.04 and Ubuntu Studio 22.04) which both experienced the issue:
`ERROR: not connected to the kf5-5-113-qt-5-15-11-core22 content interface.`

It appears this dependency (newer version of the KDE Frameworks 5 package) is not automatically installed when upgrading KeePassXC. Manually installing the required package fixes the issue without the need to remove / uninstall / re-install KeePassXC:
`sudo snap install kf5-5-113-qt-5-15-11-core22`

I can imagine this will keep happening every time KeePassXC starts using a newer version of the KDE Frameworks 5 package.
So the title of this issue should be "KDE Frameworks 5 dependency not installed automatically when upgrading KeePassXC".

But of course the real question is - **why** isn't this required dependency installed automatically when upgrading KeePassXC (but *is* installed automatically when doing a fresh install) and how do we fix it?

**Comment by droidmonkey** [comment]
Sounds like a great bug report for the snap team

**Comment by iGadget** [comment]
Thanks for your fast reply, @droidmonkey !
> Sounds like a great bug report for the snap team

Ah, so there's nothing you can do to fix this on your end? More than willing to raise the heat on this issue, but the [existing one](https://bugs.launchpad.net/snapd/+bug/1966531) is apparently not getting that much attention, to put it mildly. What else can we do?

**Comment by droidmonkey** [comment]
Not sure, I have definitely mentally abandoned snaps. Flatpak is much more robust and certainly doesn't suffer from silly deployment errors like this. So I recommend switching to flatpak.

https://flathub.org/apps/org.keepassxc.KeePassXC

**Comment by iGadget** [comment]
I can understand your frustration with snaps, considering (a.o.) this issue. However, I've had my fair share of issues with Flatpak as well (i.e. apps refusing to start at some point with no apparent cause whatsoever, the only 'fix' being another(!) reboot of the system). And I'd prefer to keep my Ubuntu Studio system as clean as possible, so I'm a bit reluctant to add Flatpak there.

I've created (another) [post on the snapcraft.io forum](https://forum.snapcraft.io/t/dependencies-not-updated-installed-when-updating-snaps/40277), hopefully that'll attract some eyeballs.
