### ISSUE TITLE
System Error after installing KeePassXC version 2.7.0

### ISSUE THREAD

**Issue by brightlight3226** [keepassxreboot/keepassxc#7659]
I was using KeePassXC version 2.6.6 with no problems. I just installed the new version 2.7.0 However, when I tried to open the program I get the message "The program can't start because api-ms-win-core-kernel32-legacy-ansi-l1-1-0.dll is missing from your computer. Try reinstalling the program to fix this problem." I reinstalled and I updated the Microsoft Visual C++ Redistributable, but I still get the same system message. I am running Windows 8.1, 64bit. Is there a fix for this or perhaps you can provide a link so I can reinstall the 2.6.6 version? Thank you.

**Comment by droidmonkey** [comment]
Use the legacy windows installer. And please search the issue board next time.
