### ISSUE TITLE
Open File dialog not using xdg directories resp. GNOME file chooser

### ISSUE THREAD

**Issue by MasinAD** [keepassxreboot/keepassxc#766]
## Expected Behavior
When displaying the file chooser dialog it should use the desktop environment's file chooser.

## Current Behavior
Currently, on gnome-shell it uses the QT file chooser (?). KeePassX does it right.

## Steps to Reproduce (for bugs)

1. When using gnome-shell, open file

## Context
One of KeePassX biggest advantages in respect to KeePass 2 was its mostly flawless visual desktop integration.

## Debug Info
KeePassXC - Version 2.2.0
Revision: caa49a8ef3ee28ed478192389b21d61107b3b8e0

Bibliotheken:
- Qt 5.5.1
- libgcrypt 1.6.5

Aktivierte Erweiterungen:
- KeePassHTTP
- Auto-Type
- YubiKey

**Comment by phoerious** [comment]
Are you using the AppImage or Snap package?

**Comment by MasinAD** [comment]
I use the unofficial Debian package.

**Comment by robertclarkson** [comment]
Is this why I have directories missing when i try to open the keepass file?
![selection_999 019](https://user-images.githubusercontent.com/3826238/48233700-26bd7300-e41b-11e8-84cf-0465199bf2de.jpg)

**Comment by robertclarkson** [comment]
Is this why i have directories missing when I try to open the database file?
KeePassXC - Version 2.3.4
Revision: 2cc52a8
Distribution: Snap

Libraries:
- Qt 5.9.5
- libgcrypt 1.8.1

Operating system: Ubuntu Core 18
CPU architecture: x86_64
Kernel: linux 4.10.0-28-generic

![selection_999 019](https://user-images.githubusercontent.com/3826238/48233737-4eacd680-e41b-11e8-9562-eddd460e7b32.jpg)

**Comment by droidmonkey** [comment]
Shouldn't all these basic implemention details be handled by the core? Is there an open issue for snapd to implement this?
