### ISSUE TITLE
Crash when search clear timer executes while creating new entry

### ISSUE THREAD

**Issue by vampyren** [keepassxreboot/keepassxc#7660]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Can not, it just happened when i had the program open
2. 
3. 

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Not crash

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

## Context
[NOTE]: # ( Give us any additional information you may have. )
I minimize keepass when i dont use it, now when i opened it after a minute this error was shown. 
![image](https://user-images.githubusercontent.com/4087127/160217504-bd5a29dd-0812-4917-b6bf-58cc7472879e.png)

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.0
Revision: d7a9ef4

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 11 x64

**Comment by idanoo** [comment]
I have also noticed this issue on Linux. I had run it from terminal to get the output.. If you believe this is a separate issue I'm happy to re-raise. Also happy to provide any extra info as required.

I'll decrypt my db and then usually within a few minutes after minimizing it just force quits with no indication. Usually restarting it works fine for awhile but it doesn't seem to be triggered by anything in particular.

```
idanoo@arch ~ $ keepassxc
YubiKey: Failed to establish PCSC context.
YubiKey: PCSC interface is disabled or not initialized.
Segmentation fault
```

Debug Info:
```
KeePassXC - Version 2.7.0
Revision: d7a9ef4

Qt 5.15.3
Debugging mode is disabled.

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 5.16.16-arch1-1

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.19.1

```

**Comment by phoerious** [comment]
We need a stacktrace to debug this.

**Comment by vampyren** [comment]
It has not happened for me yet but if you need stacktrace  or anything please let me know how to get it for you.

**Comment by tobiaskitsune** [comment]
I get a similar error but under a different condition.
KeePassXC 2.7.0 Revision d7a9ef4 always crashes when I change a custom entry field under "advanced" and press save or apply.
 Operating system is Windows 11.
<img width="302" alt="crash" src="https://user-images.githubusercontent.com/65715227/160458586-062601d0-e8ac-4e62-9b1f-02e31ac9acf1.png">

**Comment by idanoo** [comment]
> We need a stacktrace to debug this.

Is there a guide on how to obtain a stack trace? I think I've replicated it by accessing the secret service several times in a row

**Comment by vampyren** [comment]
Exactly what i'm waiting for. Someone to tell us how to do it. Back in the day when i was developer there were tools or even build-in options to do it but now days i have no clue what is expected from me/us to provide. 
So please let us know so we can give you the info if the problem comes back. I can not reproduce it myself at the moment. But if i can i will help.

**Comment by michaelk83** [comment]
Found at https://github.com/keepassxreboot/keepassxc/issues/6193#issuecomment-786958209 :
> Can you run a snapshot build https://snapshot.keepassxc.org/ and reproduce it? The snapshot will provide a readable stack trace to see where things are going wrong.

**Comment by idanoo** [comment]
Running the snapshot crashed almost instantly but didn't provide any extra output compared to the latest version. I've run it with gdb + calling backtrace after Segmentation Fault and I got the following output. If there's any way to provide a better trace, please let me know!

This occurred when I clicked "Allow All & Future" on the Secret Service popup. (Which also asks every single time even when I click Future)

[gdb_keepassxc.txt](https://github.com/keepassxreboot/keepassxc/files/8387608/gdb_keepassxc.txt)

**Comment by michaelk83** [comment]
> Which also asks every single time even when I click Future

Probably https://github.com/keepassxreboot/keepassxc/issues/7571#issuecomment-1076921523 . Btw, this sounds like a different crash from the OP.

**Comment by phoerious** [comment]
> If there's any way to provide a better trace, please let me know!

That stacktrace is very... bare. I noticed that the CI strips debug symbols, which it shouldn't. I retriggered the snapshot build without stripping, but somehow it still does. Need to investigate.

**Comment by phoerious** [comment]
@idanoo I managed to tell linuxdeploy not to strip the binaries, so you can redownload the AppImage and try to get a useful stacktrace again: https://snapshot.keepassxc.org/latest/

**Comment by idanoo** [comment]
I've noticed after a fresh boot it almost always crashes after opening Evolution and clicking apply on Allow for the secret service popup.

Here is the latest trace:

[gdb_keepassxc_withdebug.txt](https://github.com/keepassxreboot/keepassxc/files/8393144/gdb_keepassxc_withdebug.txt)

```
QList<QDBusObjectPath>::node_construct (this=<optimized out>, t=..., n=0x55555e012920) at /opt/qt515/include/QtCore/qlist.h:465
465	/opt/qt515/include/QtCore/qlist.h: No such file or directory.
```

It seems like turning off the Confirmation popup for Secret Service seems to stop the SegFault.. I will keep this setting off and update if it seems to resolve it

**Comment by droidmonkey** [comment]
Excellent can work with that trace

**Comment by idanoo** [comment]
Just popping back to confirm that unticking "Confirm when passwords are retrieved by clients" has mitigated the issue for now. It may be different crash to the original poster here without a trace from them.

![image](https://user-images.githubusercontent.com/9691551/161414135-18fe262a-cd47-4f86-80f8-2d39e94bdf77.png)

**Comment by vampyren** [comment]
> Found at [#6193 (comment)](https://github.com/keepassxreboot/keepassxc/issues/6193#issuecomment-786958209) :
> 
> > Can you run a snapshot build https://snapshot.keepassxc.org/ and reproduce it? The snapshot will provide a readable stack trace to see where things are going wrong.

I cant even reproduce it now sadly. Tried allot too. 
I can rung the snapshot version incase something new comes up. IS the only difference the extra debug info in the build? (+ more fixes i guess)

**Comment by mrusme** [comment]
I'm having the same issue and I can seem to be able to reproduce it. [See here](https://github.com/vector-im/element-desktop/issues/688).

```
YubiKey: Failed to establish PCSC context.
YubiKey: PCSC interface is disabled or not initialized.
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
[1]    17843 segmentation fault  keepassxc
```

Unfortunately unticking "Confirm when passwords are retrieved by clients" doesn't help on my end, a client (element-desktop) is still seem to be unable to retrieve a key.

Edit: Added version information here as well

KeePassXC 2.7.1
Gentoo Linux

**Comment by mrusme** [comment]
I have tried recompiling KeePassXC multiple times, without yubikey, without ccache, yet it's still crashing whenever I open element-desktop (which tries to access its key).

Here is the dmesg output of the tries:

```
[14770.319281] keepassxc[24776]: segfault at 28 ip 000055e2820c3e60 sp 00007ffd4399d418 error 4 in keepassxc[55e281e25000+2ea000]
[14770.319288] Code: 89 c5 e9 23 11 d9 ff 90 66 90 48 8b 47 08 48 8d 3d 55 20 30 00 48 8b 70 10 e9 2c 63 d6 ff 66 66 2e 0f 1f 84 00 00 00 00 00 90 <48> 8b 56 28 48 89 f8 48 85 d2 74 24 8b 52 04 85 d2 74 1d 48 83 7e
[15072.491079] keepassxc[17843]: segfault at 28 ip 000055e0f9a50e60 sp 00007ffcf8739c78 error 4 in keepassxc[55e0f97b2000+2ea000]
[15072.491087] Code: 89 c5 e9 23 11 d9 ff 90 66 90 48 8b 47 08 48 8d 3d 55 20 30 00 48 8b 70 10 e9 2c 63 d6 ff 66 66 2e 0f 1f 84 00 00 00 00 00 90 <48> 8b 56 28 48 89 f8 48 85 d2 74 24 8b 52 04 85 d2 74 1d 48 83 7e
[16779.178523] keepassxc[4784]: segfault at 28 ip 0000563df889e7f0 sp 00007ffd32053628 error 4 in keepassxc[563df860c000+2dc000]
[16779.178532] Code: 89 c5 e9 01 ca d9 ff 90 66 90 48 8b 47 08 48 8d 3d e5 cb 2f 00 48 8b 70 10 e9 3c 28 d7 ff 66 66 2e 0f 1f 84 00 00 00 00 00 90 <48> 8b 56 28 48 89 f8 48 85 d2 74 24 8b 52 04 85 d2 74 1d 48 83 7e
[16928.710987] keepassxc[20684]: segfault at 28 ip 000055c0d53fbe60 sp 00007ffeeb34cdf8 error 4 in keepassxc[55c0d515d000+2ea000]
[16928.710997] Code: 89 c5 e9 23 11 d9 ff 90 66 90 48 8b 47 08 48 8d 3d 55 20 30 00 48 8b 70 10 e9 2c 63 d6 ff 66 66 2e 0f 1f 84 00 00 00 00 00 90 <48> 8b 56 28 48 89 f8 48 85 d2 74 24 8b 52 04 85 d2 74 1d 48 83 7e
```

**Comment by mrusme** [comment]
I have created a fresh database and tried all this again and KeepassXC is not crashing any longer. The previous version of KeepassXC that I was using with the previous database was [2.6.6](https://gitweb.gentoo.org/repo/gentoo.git/tree/app-admin/keepassxc/keepassxc-2.6.6.ebuild).

Edit: The database I was using with 2.6.6 was KDBX 4 with Argon2id.

**Comment by Vistaus** [comment]
I have the same issue on openSUSE Tumbleweed. It crashes with

```
& thefish @ localhost in ~/Downloads 0 [18:46:26]
~ keepassxc
YubiKey: Failed to establish PCSC context.
YubiKey: PCSC interface is disabled or not initialized.
fish: Job 1, 'keepassxc' terminated by signal SIGSEGV (Address boundary error)

& thefish @ localhost in ~/Downloads 0 [18:46:28]
~ 
```

KeePassXC version 2.7.1. My database was created with 2.7.1.
Tried both the openSUSE package and manually compiling, but they both crash.

I don't even know why it searches for a YubiKey as I don't even have one.

Edit: tried compiling with YubiKey support disabled, but it still crashes with a SIGSEGV.
keepassxc-cli seems to work, though.

**Comment by droidmonkey** [comment]
The two messages on yubikey mean nothing, ignore them.

**Comment by Vistaus** [comment]
I wish I could, but as you can see, it crashes with a SIGSEGV, so I can't even use KeePassXC.

**Comment by droidmonkey** [comment]
Yes I'm saying that has nothing to do with the yubikey messages. 

You all are likely hitting a Qt crash or some other distro specific problem. Unlikely this is a keepassxc crash since no other platform is experiencing it.

**Comment by skierpage** [comment]
I had a similar crash without doing anything. KeePassXC 2.7.1 on Windows 10 was running, I can't remember if minimized or not. When I returned to my PC, my Windows lock screen had a Windows crash alert on it. I was unsuccessful trying to take a screenshot of it, but in Event Viewer Windows Logs > System Source "Application popup" I found the same crash:
> Application popup: KeePassXC: Windows - Application Error : The instruction at 0x00007FFB0248F134 referenced memory at 0xFFFFFFFF00000062. The memory could not be read.
>
> Click on OK to terminate the program

I restarted KeePassXC for Windows and I think my last edit to the DB was saved. I'll install the [KeePassXC-2.7.1-snapshot-Win64.msi](https://snapshot.keepassxc.org/latest/KeePassXC-2.7.1-snapshot-Win64.msi).

**Comment by mrusme** [comment]
This has started happening again. :( I'm able to reproduce it.

```
YubiKey: Failed to establish PCSC context.
YubiKey: PCSC interface is disabled or not initialized.
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
[1]    24953 segmentation fault  keepassxc
```

```
[33271.509776] keepassxc[24953]: segfault at 28 ip 000055fdce5a8e60 sp 00007fff0be84008 error 4 in keepassxc[55fdce30a000+2ea000]
[33271.509790] Code: 89 c5 e9 23 11 d9 ff 90 66 90 48 8b 47 08 48 8d 3d 55 20 30 00 48 8b 70 10 e9 2c 63 d6 ff 66 66 2e 0f 1f 84 00 00 00 00 00 90 <48> 8b 56 28 48 89 f8 48 85 d2 74 24 8b 52 04 85 d2 74 1d 48
```

```
 ▲ ~ keepassxc --debug-info
KeePassXC - Version 2.7.1

Qt 5.15.4
Debugging mode is disabled.

Operating system: Gentoo Linux
CPU architecture: x86_64
Kernel: linux 5.17.7-gentoo

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.19.1
```

**Comment by michaelk83** [comment]
You're going to need to provide a stack trace - https://github.com/keepassxreboot/keepassxc/issues/7660#issuecomment-1084238615
(Run the latest snapshot through a debugger, I think.)
There have been some fixes, so the latest snapshot may not actually crash.

**Comment by fertkir** [comment]
Fedora 37, also experiencing segmentation fault in both native & flatpak packages.
Here's what I've got from gdb:

```
Thread 343 "Thread (pooled)" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffb2ffd6c0 (LWP 15567)]
0x0000555555696fdd in Database::setKey (this=0x555557158f60, key=..., updateChangedTime=<optimized out>, updateTransformSalt=<optimized out>, transformKey=<optimized out>) at /usr/src/debug/keepassxc-2.7.4-2.fc37.x86_64/src/core/Database.cpp:823
823         m_data.transformedDatabaseKey->setRawKey(transformedDatabaseKey);
```

The problem occurred because I was unlocking my database via dbus right on ScreenSaver ActiveChanged event. 
Solved by adding a 5 sec timeout between wakeup and database unlock.

**Comment by vampyren** [comment]
For me this has not happen for months so this is a none issue for me atleast. 
If anyone wants to continue the thread like @fertkir please do so.

**Comment by fertkir** [comment]
Actually a timeout didn't help. The app still crashes when I send openDatabase event through dbus.

The only workaround I see is to run keepassxc as a systemd service and restart it in case of a failure.

**Comment by fertkir** [comment]
I'll be a captain obvious if I say that it looks like in `m_data.transformedDatabaseKey->setRawKey(transformedDatabaseKey);` transformedDatabaseKey is deallocated before the call.
And it happens when I end the screensaver on my laptop. And having a timeout between the end of screensaver and openDatabase call sometimes prevents the segfault.

I'll try to find out where it happens, but I'm not a C++ developer at all, so I don't think I'll succeed.

**Comment by fertkir** [comment]
Can it be that here neither `if (!transformKey) {` nor `else if` is executed? So we end up with uninitialized `transformedDatabaseKey` being passed to `setRawKey()` call?
```c++
    QByteArray transformedDatabaseKey;

    if (!transformKey) {
        transformedDatabaseKey = QByteArray(oldTransformedDatabaseKey.rawKey());
    } else if (!key->transform(*m_data.kdf, transformedDatabaseKey, &m_keyError)) {
        return false;
    }

    m_data.key = key;
    if (!transformedDatabaseKey.isEmpty()) {
        m_data.transformedDatabaseKey->setRawKey(transformedDatabaseKey);
    }
```

**Comment by droidmonkey** [comment]
> QByteArray transformedDatabaseKey;

This isn't a pointer and won't cause the crash

> m_data.transformedDatabaseKey

If this isn't null checked then this could be the cause. It's unfortunate that this shares the same name as the local variable which is NOT a pointer.

**Comment by dreamsyntax** [comment]
Just adding, this just happened to me too while doing nothing on a "new entry" page... and of course I lost all my ways to recover the account :')

![keepass-why](https://user-images.githubusercontent.com/14857235/214508683-857de6e1-4f1a-43e0-be4a-68c829355ffe.jpg)

I thought I was clever taking a screenshot before the application crashed, so I would at least have the recovery phrases but keepassxc blocks that...


Edit:
Windows 10 22H2 build 19045.2486
KeePassXC 2.7.4

**Comment by droidmonkey** [comment]
Hmmmm, what were you doing just before doing nothing? This could also be (and probably is) a background thread misbehaving. That would explain the OP's issue and potentially yours. This issue is encumbered with a lot of noise of unrelated non-Windows crashes.

**Comment by LinuxOnTheDesktop** [comment]
Just now I had the same or a similar problem, on Windows 10 (Windows 10 Pro - 22H2 (2009: 19045)). I was entering text into the 'notes' field of a new entry and the program crashed to desktop (losing my text) with this error:

![image](https://user-images.githubusercontent.com/47056543/214649308-5f3a0c5d-d620-4492-99ed-6f093dda5e0f.png)

KeePassXC version: 2.7.4.

**Comment by dreamsyntax** [comment]
> Hmmmm, what were you doing just before doing nothing? This could also be (and probably is) a background thread misbehaving. That would explain the OP's issue and potentially yours. This issue is encumbered with a lot of noise of unrelated non-Windows crashes.

Same as the @LinuxOnTheDesktop effectively.

I had created a username/password for an account and was adding secret questions / recovery questions in the notes field.
I did not hit save in KeePassXC, returned to my browser to complete the recovery questions (Tabbed out to MS Edge), and then boom - KeePassXC error thrown - but I could still see the program info. Tried to screenshot (stupidly, should've grabbed a phone and taken a pic). Gotta love how the worst case scenario always manages to happen with crashes like these haha.

But yeah, many headaches ahead with support now as I try to convince them I am who I say I am.


If it matters, this was on a fresh OS install as of last week, with a fresh KeePassXC install too (2.7.4 msi, not from MS store).

**Comment by MattWeatherford** [comment]
I know exactly what I was doing, and its happened in the same place more than once. Its a weird edge case.
- I search for a credential, none shows up
- then  I create "new" to Create a new entry in keepassxc
- it autofills a field based on what my search was
 - entered some stuff, 
 
the entry was new, opened, unsaved, with autofill data & had not yet saved, was working in another window to gather more data to enter in the record when it crashed

thanks for a great product that lots of customers use!

**Comment by droidmonkey** [comment]
That is helpful!

**Comment by deutrino** [comment]
Just wanted to mention that after months of occasional seemingly random crashes on Linux (2.7.4-1ppa2~jammy1 installed from .deb), I finally realized that it's occasionally crashing when I leave the editor open for a new entry in the background for a while, same as mentioned in [this comment](https://github.com/keepassxreboot/keepassxc/issues/7660#issuecomment-1403220959)

**Comment by droidmonkey** [comment]
I tried leaving a new entry and an edited entry open for a long period of time while debugging and couldn't replicate this crash. @deutrino is it possible for you to run a debug build with gdb and see if you can replicate?

**Comment by oliversalzburg** [comment]
> I know exactly what I was doing, and its happened in the same place more than once. Its a weird edge case.
> 
>     * I search for a credential, none shows up
> 
>     * then  I create "new" to Create a new entry in keepassxc
> 
>     * it autofills a field based on what my search was
> 
>     * entered some stuff,
> 
> 
> the entry was new, opened, unsaved, with autofill data & had not yet saved, was working in another window to gather more data to enter in the record when it crashed
> 
> thanks for a great product that lots of customers use!

This sounds similar to the case I was experiencing. I also had a the details for an entry open and continued my work as usual. Probably used the browser plugin quite a bit to fill password fields. Then I wanted to do something in the KeePassXC GUI, returned to it, clicked OK on the entry details dialog, and then got the error message.

**Comment by droidmonkey** [comment]
GOT IT! When the clear search timer goes off and clears the search while creating a new entry a crash occurs here: https://github.com/keepassxreboot/keepassxc/blob/988bb9c1cdd0cdf76116c4c0caf89398342f3904/src/gui/EntryPreviewWidget.cpp#L556

Basically the search ends, the entry preview widget is updated with the current selected entry... which is your new entry, but because this new entry doesn't have a group it crashes with a nullptr.

**Comment by MattWeatherford** [comment]
Well done devs - great find !

**Comment by droidmonkey** [comment]
In the interim of an update, you can do two things to avoid this crash:

1. Disable the search clear timer in the security section of the application settings

2. Never create an entry while a search is active. Cancel the search first, then create an entry.
