### ISSUE TITLE
keypassxc snap distribution could offer extra channels for older versions

### ISSUE THREAD

**Issue by fcostin** [keepassxreboot/keepassxc#7661]
## Summary

keypassxc's snap distribution could offer extra channels to allow users to download old stable versions of the keypassxc snap package.  

## Examples

It'd be great if a user could do something like

```
sudo snap install keypassxc --channel=2.6.6/stable
```

to cause the previous stable snap package release of keypassxc version 2.6.6 be installed

This convention to prefix the channel with a version is used by some other projects with snap distributions, e.g. blender: `sudo snap refresh blender --channel=2.92/stable`

current behaviour:  `snap info keepassxc` shows the current selection of channels:
```
channels:
  latest/stable:    2.7.0 2022-03-22 (1541) 21MB -
  latest/candidate: 2.7.0 2022-03-22 (1541) 21MB -
  latest/beta:      2.7.0 2022-03-22 (1541) 21MB -
  latest/edge:      2.7.0 2022-03-23 (1546) 21MB -
``` 
This does not give users a way to install the previous stable release, v2.6.6, using snap.

## Context

In cases such as the recent keepassxc 2.7.0 release, where the new snap release does not work for some users and prevents access to password databases (e.g. https://github.com/keepassxreboot/keepassxc/issues/7607 ), being able to install an older working version using `snap` would allow keepassxc users to continue to access their password database with the older version of the software known to work on their system, and decouple the hard work of issue triage and bug fixing from immediate impact to users.

**Comment by droidmonkey** [comment]
We cannot do that, this requires snap admin (ubuntu) to do it and makes no sense for us. We offer appimage and ppa as alternative means of distribution.

**Comment by fcostin** [comment]
thank you, it is easy for me to switch to ppa distribution.
