### ISSUE TITLE
KeepassXC 2.7.0 on macOS autotype fails

### ISSUE THREAD

**Issue by piattj** [keepassxreboot/keepassxc#7664]
Running KeepassXC on macOS Monterey, M1 macBook. (Also reproduced the issue on a different mac). 
In prior versions, autotype worked flawlessly simply by clicking the autotype icon. In 2.7.0, that fails, and the target fields stay empty.
The only way(s) that autotype works is to select from the autotype icon dropdown menu, or right click on the entry and select there.

**Comment by tervor** [comment]
Seems to be related to #7584
