### ISSUE TITLE
[2.7.0] Does not start. No GUI

### ISSUE THREAD

**Issue by ckorn** [keepassxreboot/keepassxc#7667]
The new version 2.7.0 does not work here.
When I start it there is simply a black screen. Not even the context menu in the systray works.
It is also completely black. So I have to guess where quit is to exit the program.
I also already installed this:
https://aka.ms/vs/17/release/vc_redist.x64.exe
And rebooted the system.
The new version used to work when I first installed it.
After that there was an update of the nvidia drivers I think.
Driver version is 512.15.
Win10 version is 21H1 Build 19043.1586
I installed 2.6.2 again which works fine.

I cannot paste debug output because I do not see any GUI ^^

**Comment by droidmonkey** [comment]
https://keepassxc.org/docs/KeePassXC_UserGuide.html#_screenshot_security

**Comment by ckorn** [comment]
Oh wow thanks. So the issue was Steam Link.
Never would have guessed that.
Thanks. Works now.
