### ISSUE TITLE
existing search terms in search bar displayed even when keepassxc database is locked

### ISSUE THREAD

**Issue by mfc** [keepassxreboot/keepassxc#767]
existing search terms in the search bar displayed even when keepassxc database is locked. they should not be displayed when the database is locked.

## Expected Behavior
existing search terms in the search bar should not be displayed when the database is locked.

## Current Behavior
existing search terms in the search bar displayed even when keepassxc database is locked. 

## Steps to Reproduce (for bugs)
1. input a search term in search bar
2. lock database
3. search term is still visible

**Comment by weslly** [comment]
What version are you using?

**Comment by mfc** [comment]
2.1.4 (current keepassxc version in fedora 24), just upgraded to F25 which has 2.2.0 and it no longer happens.
