### ISSUE TITLE
2.7.0 shows blank window on Windows 10

### ISSUE THREAD

**Issue by chucku** [keepassxreboot/keepassxc#7671]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
KeePassXC 2.7.0 comes up with a blank (black) window on Windows 10.  

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Install version 2.7.0 (either standard or legacy) on win 10.  
2. Attempt to start it.  
3. A blank window is shown forever.  

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
KeePassXC should come up showing a window allowing me to unlock the database.  

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
KeePassXC 2.7.0 shows a blank (black) window on startup.  The application appears to otherwise be working, e.g. if I click on the top right corner of the black window it shows the <close> tip and closes the window.  

## Context
[NOTE]: # ( Give us any additional information you may have. )
I have been using KeePassXC on this system for several years without a problem.  I was using version 2.6.6 without a problem.  I have (hopefully temporarily) re-installed 2.6.6 and it works as expected.  

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - KeePassXC-2.7.0-Win64.msi & KeePassXC-2.7.0-Win64-LegacyWindows.msi 
Revision: unknown (downloaded 2022-03-26)

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 10 Home ver 21H2 build 19044.1620
Desktop Env: n/a
Windowing System: n/a

**Comment by droidmonkey** [comment]
https://keepassxc.org/docs/KeePassXC_UserGuide.html#_screenshot_security

**Comment by chucku** [comment]
Thanks for pointing that out.  That has fixed the issue.  
Is there any way of allowing screencapture if you have KeePassXC set up to start at boot time?  Other than killing it and starting it again from the start menu?

**Comment by phoerious** [comment]
Add the flag to the autostart entry.

**Comment by chucku** [comment]
That is the problem, isn't it.  Where is the autostart entry?  I have looked in all the usual places.  Even autoruns provides no assistance.

**Comment by phoerious** [comment]
Should be `[HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Run]` in the registry.

**Comment by chucku** [comment]
Thank you very much!  
Rule #1 of debugging — write down everything you do.  I actually checked that location but forgot that I had disabled autostart :( 
Thanks again...

**Comment by phoerious** [comment]
Lol, that PR #1 seems really popular. :-D
