### ISSUE TITLE
Database not re-locked after Auto-Type

### ISSUE THREAD

**Issue by clocken** [keepassxreboot/keepassxc#7674]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
Database is not re-locked after performing Auto-Type.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Activate option "Re-lock previously locked database after performing Auto-Type"
2. Have KeePassXC in tray with a locked database
3. Perform Auto-Type in a window
4. Unlock the database when asked

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Database is re-locked after performing Auto-Type

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Database stays unlocked after performing Auto-Type

## Context
[NOTE]: # ( Give us any additional information you may have. )
The feature has originally been requested in #152 and it worked with KeePassXC 2.6.6, so this bug has been introduced with the latest update to 2.7.0.
Current workaround is to set a lock-timeout in the security settings.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.0
Revision: d7a9ef4

Qt 5.12.8
Debugging mode is disabled.

Operating system: Ubuntu 20.04.4 LTS
CPU architecture: x86_64
Kernel: linux 5.13.0-37-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.12.1

**Comment by droidmonkey** [comment]
It is relocked after a set delay to allow for quick use of Auto-Type again. You can set that to zero in the Auto-Type settings.

**Comment by clocken** [comment]
> It is relocked after a set delay to allow for quick use of Auto-Type again. You can set that to zero in the Auto-Type settings.

Indeed, thanks for the clarification :)
