### ISSUE TITLE
Second Password for some Websites required.

### ISSUE THREAD

**Issue by ChrTall** [keepassxreboot/keepassxc#7676]
## Summary
Some Websites require an additional Password. Right now, it is not possible to store 2 Passwords for the same username.

## Examples

![Screenshot_20220326_175737](https://user-images.githubusercontent.com/55497425/160249670-1270af78-1dce-417e-b00b-33bf7db86845.png)

## Context
It would be a nice feature, even though it is just an edge case.

**Comment by varjolintu** [comment]
You can use String Fields for this.
Steps to do it:
- Open the extension popup and click Custom Login Fields button
- Select Username and Password field, skip TOTP field, and select a String Field after that. Confirm the selections.
- From KeePassXC side, edit your entry.
- Add a new Attribute, for example with name `KPH: Password 2`. The `KPH: ` at the start is what matters.
- Add your second password as the attribute's value.
- Refresh the web page and when you are filling the username, both passwords should be now filled.

Also, check from KeePassXC's Browser Integration settings (Advanced tab) that `Return advanced string fields which start  with "KPH: "` setting is enabled.

**Comment by ChrTall** [comment]
Thanks I was able to do what you described and it works great.
