### ISSUE TITLE
Double click on username and password fields does not copy the content to clipboard anymore

### ISSUE THREAD

**Issue by archont00** [keepassxreboot/keepassxc#7677]
## Overview

Keepassxc used to support "double click to copy" feature. E.g. older "fixed" issue confirms it:  https://github.com/keepassxreboot/keepassxc/issues/360

It has stopped working recently - instead, the item opens for editing.

## Steps to Reproduce
1. Select any item in Keepassxc and double click on username field

## Expected Behavior
The username gets copied to clipboard.

## Actual Behavior
The selected item opens for editing.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.0
Revision: d7a9ef4

Qt 5.15.3
Debugging mode is disabled.

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 5.16.16-arch1-1

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.19.1

**Comment by droidmonkey** [comment]
Go to settings to enable it.

**Comment by archont00** [comment]
For those searching the option: It is in the Security section.

**Comment by ChrisCSAP** [comment]
And the **bug** is actually that it is **not enabled** by default, so it is mimic the behaviour like before without need to Google it, isn't it?

**Comment by ChrisDeath** [comment]
And the **bug** is actually that it is **not enabled** by default, so it is mimic the behaviour like before without need to Google it, isn't it?

**Comment by michaelk83** [comment]
Not a bug. It was removed deliberately since it was deemed a bad design, and a confusing and inconsistent UI: #5910 (particularly [this](https://github.com/keepassxreboot/keepassxc/issues/5910#issuecomment-757887914) and [this](https://github.com/keepassxreboot/keepassxc/issues/5910#issuecomment-757915529) comments), https://github.com/keepassxreboot/keepassxc/issues/4384#issuecomment-592457647 , #6670 , #6289, and others.

Furthermore, it's a bit of security issue when stuff is copied to the clipboard when the user did not intend to and without a clear indication (not a huge issue, since the clipboard is cleared automatically, but still; there is a countdown shown, but it's easy to miss). It's also an annoyance when the browser is launched to open a URL when the user intended to edit the entry.

This is more appealing for a subset of experienced users. Those users can enable it in the options.

**Comment by droidmonkey** [comment]
To be clear, double click on url always opens the browser. Even when this setting is disabled. This only applies to username and password columns.

**Comment by ChrisDeath** [comment]
Okay, i can totally follow the security aspect, but not the change management. For users that upgrade it should be better stated in the upgrade notes (https://keepassxc.org/blog/2022-03-21-2.7.0-released/), that they have to revert to old and fine behaviour manually. And yes many will still struggle as the don't read the notes, but if they google then it can be found at least ;)

**Comment by droidmonkey** [comment]
![Screenshot_20220405-073618_GitHub.png](https://user-images.githubusercontent.com/2809491/161745617-9db59a0b-5655-4830-9df2-3697c2a27528.png)

**Comment by ChrisDeath** [comment]
yes, that are the GIT release notes but not the published ones. I know that you see it from the dev perspective. But please see it from normal user perspective: Something is not work in new release. He will go to google and type in "keepassxc 2.7.0" -> first entry the blog post and no reference at all to that specific GIT release notes. He may then tries "keepassxc 2.7.0 double click" -> he finds a bug, but only if someone was already so keen and created one (what many don't do). And maybe he finds the reddit post. But finally in that #6433 there is no advice for existing users that they need to enable it manually cause it will break by default the commonly known feature.
You guys are doing great on that tool and i am using it all day cause you did a great job. So please don't get me wrong on that! It is just that i want to make you aware of that behaviour changing things needs to be reflected in change management :)

**Comment by droidmonkey** [comment]
We can't possibly make every change an obvious one. There was no setting in the past, security dictates you "fail secure" therefore the default options will be the most secure. Also those release notes are linked at the bottom of the blog post:

![Screenshot_20220405-075158_Edge.png](https://user-images.githubusercontent.com/2809491/161748151-0eda5d08-1a5c-412d-9e45-822ea22068d9.png)

I'm not being combative but trying to show you that this was communicated in some way.

**Comment by Robotic-Brain** [comment]
"Comunicatd in SOME way" reminds me of the old "[...] All the planning charts and demolition orders have been on display at your local planning department in Alpha Centauri for 50 of your Earth years [...]"

Just a suggestion for future changes like this:
1. "Introduce new stuff and deprecate the feature": Whenever someone uses it, a message pops up: "Hey User! this feature will change in the future! Make sure to update your settings!"
2. Wait 2-3 releases or months - whichever is longer
3. "Actual remove/change": Change the default to the new default and remove the message.

This way you make sure all users affected by the change actually get the new information and everyone is happy.

**Comment by michaelk83** [comment]
> and everyone is happy

People are still going to complain just as much about the upcoming change. It takes more effort and code than it's worth.

**Comment by droidmonkey** [comment]
> This way you make sure all users affected by the change actually get the new information and everyone is happy

Oh man... that is some serious wishful thinking. Why would we go through all that trouble for such an inconsequential change, which is easily re-enabled, and was specifically complained about by a significant number of people (what prompted the change in the first place). Imagine the amount of work to do that for every single change. Not to mention the severe annoyance of a million popups every time you do something because it _may some day_ change.

**Comment by ChrisDeath** [comment]
Let me again explain, what is the case nower days: Your software got that much mature that it is used not only by security fanatics and computer nerds, but also by normal users that want to use it just day by day. These users are not really interessted in which encryption lib you are using or what SHA512 is. As this double click change was much more visible and really recongnizable in day work in front end, the change management should have been done better. What i would liked to see that if i type in in google "double click keepassxc" that i find your release notes where i see why it was gone and how to get it back.
These "significant number of people" are right on the security stuff...fine...but if the many-years feature is not working from now to next...that is much more annoying. And if you look for help, you can't find it easily... It is now in the user guide mentioned, but at the time where i was searching for it, it was not there i belive.
So i am only asking to have a significant usability change (yes it is) rated the same like your lib change.
