### ISSUE TITLE
No KeyAgent running on 2.7.0

### ISSUE THREAD

**Issue by cmdflow** [keepassxreboot/keepassxc#7679]
## Overview
KeyAgent is not recongnized with 2.7.0

## Steps to Reproduce
Open putty keyagent pageant, open KeePassXC, see result

## Expected Behavior
Should interact with KeyAgent

## Actual Behavior
no keyagent open

KeePassXC - VERSION
2.7.0

[NOTE]: # ( Pick choices based on your environment )
Windows 10

**Comment by droidmonkey** [comment]
Make sure you enabled that in the application settings.  This is a duplicate and not a bug.
