### ISSUE TITLE
Document minimum operating system requirements

### ISSUE THREAD

**Issue by jsha** [keepassxreboot/keepassxc#768]
At https://keepassxc.org/download, it's not clear what version of Windows is required. Could you add that information? Thanks!

**Comment by phoerious** [comment]
I actually don't know. I don't think any of us has something older than Windows 10. So Windows 10 is the officially supported version. It should run fine on Windows 7, but we can't really test it.

**Comment by weslly** [comment]
[KeepassX requires >= Vista](https://www.keepassx.org/downloads) (with a required security update) and I've been compiling and testing KeepassXC on a Windows 7 VM.

I'm not sure if anything that would break Vista compatibility was introduced on KeepassXC, but at least Windows 7 is guaranteed to run without any issue.

**Comment by phoerious** [comment]
Have you tested it on Visa? I know we had that on the website for some time as minimum required version. But that was only because KeePassX had that too. We removed it, because we could never verify if that was actually true.

**Comment by weslly** [comment]
@phoerious no, I only tested on Windows 7. But since Vista can't run KeepassX without a security update and nowadays [its market share](http://gs.statcounter.com/os-version-market-share/windows/desktop/worldwide) is so small we should probably just require Windows 7 or newer.

**Comment by phoerious** [comment]
I agree. But have you also tested the pre-compiled binaries?

**Comment by weslly** [comment]
@phoerious just tried it now:

![image](https://user-images.githubusercontent.com/107672/28217403-69b83832-688b-11e7-8951-358560729821.png)

**Comment by leonyu** [comment]
This might be relevant: 
https://doc.qt.io/qt-5/supported-platforms-and-configurations.html

**Comment by jsha** [comment]
Hi! Did this get fixed?

**Comment by droidmonkey** [comment]
We do document which version of macOS is required right on the download link. I will do a similar addition to the Windows download link.

**Comment by droidmonkey** [comment]
Done

**Comment by jsha** [comment]
So awesome, thank you!
