### ISSUE TITLE
2.7.0 - Some Sites - Autotype UI Now Shows Every Entry To Choose From

### ISSUE THREAD

**Issue by 0pLuS0** [keepassxreboot/keepassxc#7680]
## Overview
[NOTE]: # ( Give a BRIEF summary about your problem )

In version 2.6.6, at sites where if I had more than one account, the Autotype UI would only display those accounts to choose from. Now in 2.7.0, when I go to some sites, that I have several accounts at, the Autotype UI is showing every one of my entries to choose from.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Assign the keys ```Ctrl+Z``` to the Global Auto-Type shortcut
2. Go to a site where you have several accounts, press Ctrl Z to bring up the Autotype UI
3. Check if it now displays all of your entries in keepassxc to choose from

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Should only see a list in the Autotype UI for only the accounts you have at a particular site, not every entry being displayed to choose from.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Some sites where there is more than one account, the Autotype UI will show you every entry you have in keepassxc to choose from.

## Context
[NOTE]: # ( Give us any additional information you may have. )

I wonder if using the ESR version of Firefox is now causing this? But in the past, I used 2.6.6 also in Slackware with ESR versions of FF without seeing this issue.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.0
Revision: d7a9ef4

Qt 5.15.3
Debugging mode is disabled.

Operating system: Slackware 15.0 x86_64
CPU architecture: x86_64
Kernel: linux 5.15.28

Enabled extensions:
- Auto-Type

Cryptographic libraries:
- Botan 2.19.1

[NOTE]: # ( Pick choices based on your environment )
Operating System: ```Slackware 15.0```
Desktop Env: ```Openbox 3.6.1```
Windowing System: ```X11```
Browser: ```Firefox ESR 91.7.1```

**Comment by droidmonkey** [comment]
I assume you are really talking about Auto-Type and not browser integration.  If so, then you need to either define more specific window association or use the title and url matching feature. 

https://keepassxc.org/docs/KeePassXC_UserGuide.html#_configure_auto_type_sequences

**Comment by 0pLuS0** [comment]
@droidmonkey I don't understand why you closed this report, unless you are saying, that now in 2.7.0 we have to do something different than previous versions?

I've used keepassxc since this project started and I've never had this issue before. I'm not doing anything different with 2.7.0, than 2.6.6.

I never defined more specific window association or used the title and url matching feature before in any previous versions, I just left everything default and it worked.

The Autotype UI, is what I am talking about, what else would we be calling it?

This is a screen shot when I went to Protonmail, it shows me every entry.

![autotype_ui](https://user-images.githubusercontent.com/36190223/160304634-5142ef7d-24f9-4188-a846-d0e033730e40.jpg)

I don't see this as something the end-user needs to change, I'm seeing this as a ```Bug```, because this does not happen at every site I go to, that I have several accounts at, this only happens at some.

Go to ```Protonmail``` and ```Steam``` test and see if you also see this happening there?

So for some sites I have several accounts at, this is only happening at the moment, at Protonmail and Steam.

https://mail.protonmail.com/login

https://store.steampowered.com//login/?redir=0

THANKS

P.S. The only time in previous versions, that I defined more specific window association or used the title and url matching feature, is when, it would either not auto type in the user/password when I pressed Ctrl Z, saying it had no association, or it would never show the Autotype UI, when I pressed Ctrl Z on sites I had several accounts, otherwise I just left everything as default. But as I mentioned, in 2.6.0 I left everything on default settings, I never had to change anything.

**Comment by droidmonkey** [comment]
Read the user guide

**Comment by 0pLuS0** [comment]
So now I went back and added these changes for both of my Protonmail accounts.

![protonmail](https://user-images.githubusercontent.com/36190223/160306035-896ffade-8a6a-44f6-9d23-6540d489cc67.jpg)

I have seen in the past with some of the first releases of the project, where this was more common to do this, but as the project matured, it was my understanding, that if websites don't do anything odd, then it should work without these changes.

So I hope someone will please explain this, as I didn't have to do this in 2.6.6, and now I am doing this in 2.7.0, this is all I am explaining, that this worked in 2.6.6 without me making these changes and now 2.7.0 needs these changes.

hmm

THANKS

**Comment by phoerious** [comment]
If your window title is "Proton Account -- Mozilla Firefox", it is honestly to be expected that nothing is found (which means everything is returned for lack of a more specific entry), unless your entry is named the same, which I doubt. The correct association would be "Proton*".

I guess we could add some fuzzy default rules to ignore browser names at the end or keywords like "Account" (localised, I suppose) before we default to showing everything.

**Comment by droidmonkey** [comment]
He says he doesn't have window title matching turned on. It would match an entry titled Proton if he did.

**Comment by 0pLuS0** [comment]
Sorry if I didn't make this clear.

The only question I had concern over, is if there were changes in 2.7.0, where now I might need to define more specific window association or use the title and url matching, when I didn't have to do it before?

I just found it odd, that I have used keepassxc since the project started and I never had to do any of this in any previous versions till now, this is why I made the issue, to clarify this.

THANKS

**Comment by droidmonkey** [comment]
There is no way that was the case unless you had enabled match entries using entry title and/or url. By default Auto-Type doesn't match anything without this settings enabled. That behavior has not changed. What has changed is that instead of receiving a message that no entries can be found, we show you all entries with a search.

**Comment by 0pLuS0** [comment]
Let me ask it this way, everything worked in 2.6.6, so when I upgraded to 2.7.0, I assumed it would be the same, but I had to make changes.

So if it worked in 2.6.6, but it didn't in 2.7.0, what I've been trying to ask, sorry if you're not understanding, I'm asking, has anything changed in 2.7.0, that even though things worked in 2.6.6, doesn't mean it's the same now in 2.7.0, and I might now have to make these changes?

I understand how some times you have to make changes, I get this, I'm just trying to understand, by what I just asked, if things have changed in 2.7.0, where there might be some needed changes now...

THANKS

**Comment by 0pLuS0** [comment]
But the bigger question/picture here, is if it worked in 2.6.6, but it's not working in 2.7.0, that's what I'm wondering, because, if it should be working in 2.7.0, that's the problem in my mind, and why I filed the Bug Report, as to why it's not...

THANKS

P.S. Maybe 2.6.6 had a bug and it's corrected now, working as it should, because as I mentioned, I didn't make any changes for this to work, it just worked by default, I made no changes in KeePassXC 2.6.6. The screen shot I showed above, for the Window Association and title, I didn't have any of this in 2.6.6

**Comment by droidmonkey** [comment]
Please provide a screenshot of your Auto-Type settings page.

**Comment by 0pLuS0** [comment]
![autotype](https://user-images.githubusercontent.com/36190223/160521171-8558b4fe-52a1-4fbb-a9ba-9877930ce3dc.jpg)

**Comment by 0pLuS0** [comment]
I forgot about this issue, and today, noticed at this site the problem will occur.

https://account.protonvpn.com/login

It will show every entry I have to pick from with the Autotype UI.

I hope this is going to be fixed soon, it makes it difficult to have to scroll through all my entries to find the one I need to login with.

In the meantime, I added a Window Association; Proton VPN — Mozilla Firefox

But I've never had to add Window Associations before, in previous versions.

THANKS

**Comment by droidmonkey** [comment]
There is a search as well...

**Comment by 0pLuS0** [comment]
> There is a search as well...

I don't know what you're talking about?
