### ISSUE TITLE
After update, the new "Access Request" window incessantly bugs me. Please make it optional.

### ISSUE THREAD

**Issue by gnrlus** [keepassxreboot/keepassxc#7681]
Hi, I switched to KeepassXC because it was handy automating credentials with Secret Service integration. But now after this update (now 2.7.0) it constantly impedes my workflow having to click "Allow" because all my applications and scripts constantly need access. Oh this is horrible. It also does not remember my choice ever. I am going to need an option to disable this or I have no choice but to ditch this whole program. :(( I personally don't need that level of security. Please allow for variable security models and avoid the one-size-fits-all approach. I can't even uninstall Keepass right now if I wanted because all my chips are in it, and I'd have to first painstakingly transfer everything to some other solution. So until then, I'm stuck clicking "Allow" 3,000 times a day. Literally!

Thanks.

**Comment by droidmonkey** [comment]
Duplicate, you can disable it in settings

**Comment by gnrlus** [comment]
In 2.7.0? I searched and searched and could not find that setting. Could you point me to it please? For the time being I've reverted my package back to 2.6.6 and locked the version in Synaptic. Thanks. By the way, I do appreciate that you can make it request access if you really want the security; that's really cool. I might suggest making the per-process access request your highest security setting. An intermediate setting could be that it throws a system-wide access request only every n minutes that you specify. That would be ideal for me.

**Comment by michaelk83** [comment]
"Confirm when passwords are retrieved by clients"
https://github.com/keepassxreboot/keepassxc/issues/7571#issuecomment-1076921523

**Comment by gnrlus** [comment]
Hm, that setting seemed to do nothing for me. I will try again when I get a chance. I tried toggling all the checkboxes. Nothing worked.
