### ISSUE TITLE
After Update, it's taking 3x as long to decrypt database.

### ISSUE THREAD

**Issue by antrys** [keepassxreboot/keepassxc#7682]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
My Setup:  My decryption slider is cranked to max. (Says 5 seconds in interface)
I am using a keyfile.

After updating to 2.7 my database decrypt time went from 4 seconds to 13 seconds.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Open database with encryption set to max, using a keyfile.
2. 
3. 

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Open in 4-6 seconds.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Opens in ~13 seconds.

## Context
[NOTE]: # ( Give us any additional information you may have. )
I haven't changed anything else on my machine lately, other than regular Linux Mint Updates.

[NOTE]: # ( Paste debug info from Help → About here )

KeePassXC - Version 2.7.0
Revision: d7a9ef4

Qt 5.12.8
Debugging mode is disabled.

Operating system: Linux Mint 20.3
CPU architecture: x86_64
Kernel: linux 5.13.0-272201191901-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.12.1

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: Cinnamon
Windowing System: X11

**Comment by phoerious** [comment]
What are the encryption settings of your database?

**Comment by antrys** [comment]
Other that what I wrote on the very 2 lines of my OP all I can add is it's KDBX4 database.
I don't know what else I can add, based on what the interface gives.  What are you looking for specifically?

**Comment by phoerious** [comment]
Go to your database settings, check the "advanced" box in the lower left corner and check what encryption settings are set under "Security".

**Comment by antrys** [comment]
The "advanced" box is greyed out. I'm unable to select it.

**Comment by phoerious** [comment]
Not if you click on Security/Encryption Settings first.

**Comment by antrys** [comment]
Ah, Ok.

Algo: 256-AES
Derivation Function: AES-KDF (KDBX 4)
Transform Rounds: 169540232

**Comment by phoerious** [comment]
@droidmonkey @randombit Seems like we have some performance problems with AES as well here.

@antrys AES-KDF is not a very good key derivation function and you should change it to Argon2 (regardless of whether this is a bug or not). That should also make things faster again at a higher level of security if you benchmark it to the 4 seconds you had previously (or any other number of seconds you prefer).

**Comment by droidmonkey** [comment]
169 million rounds is insane. The AES KDF is literally just AES-256 performed #rounds against the key. The key is split in half with each half calculated in parallel. There is no optimizing it at all from what I can see. Maybe I screwed up the parallel aspect and it's really happening serially?

**Comment by antrys** [comment]
That may be, but still, what caused the sudden performance decrease?  Ill I've ever used is the basic slider, cranked up to the top.  Did the number of transforms magically grow somehow?  I haven't touched it in at-least a year, perhaps as many as 3 years?

Whoop, just read your edit after I posted.

**Comment by phoerious** [comment]
169 million rounds is a lot, but I tested it on 2.6.6 on my Ryzen and it was 4 seconds. I guess with hardware assistance it's doable?

**Comment by antrys** [comment]
So if I switch to Argon2d, it's saying 4s is ~2.2k transforms on my system.
That's a big difference, so I want make sure I'm understanding this correctly. 
Your saying 2.2k transforms of Argon2 is more secure that 160m AES-KDF transforms?

**Comment by phoerious** [comment]
2.2k rounds sounds massive. With 128MiB and 4 threads, you should have something like 124 or so.

**Comment by antrys** [comment]
@phoerious with 128MB & 4 threads it benchmarking at 16.  That's a lot different than 124. I'm on a Ryzen 5 1600

**Comment by phoerious** [comment]
@droidmonkey I tested the 169 million rounds on my system and it seems to be about twice the duration as in 2.6.6. So it may be that we screwed up the parallel computation. It should certainly not take more than 3x times.

@antrys sounds about right. 16 would be 1 second if you click on the button. Take that times 4 and you have 64, which is a lot actually. Your CPU may be slower than mine.

**Comment by phoerious** [comment]
Uhh, I see how you got to 2k. When I switch an AES-KDF database over to Argon2, it uses 1/1 for memory/parallelism, which is crap.

128MiB is a decent value I would say. Use the number of cores in your system as parallelism, or fewer if you want to open it on mobile devices.

**Comment by antrys** [comment]
@phoerious Ok, I just wanted to make sure I'm good. I'm not worried about [insert entity here] trying to hack it on a cell phone. lol

Edit: I've switched over to Argon2.  I don't think there's anything else I can constructively add to this issue.
Thanks for your help folks.

**Comment by droidmonkey** [comment]
Certainly highlighted a bug, thank you

**Comment by randombit** [comment]
@droidmonkey You need anything here from me at this point? No reason I know of to think Botan's AES would be slower than libgcrypt's, with or without hardware accel. Can investigate further if you think it worthwhile. My first guess is in your rewrite you added a heap allocation+deallocation per loop iteration of the KDF, or something like that.

**Comment by phoerious** [comment]
We'll check and let you know. Thanks!

**Comment by droidmonkey** [comment]
@randombit that was my thought as well, but I am iterating on the same data structure for each loop. I think this is me trying to run things in parallel and totally failing at doing that.

**Comment by randombit** [comment]
I think this is an apples-to-apples comparison, which doesn't quite capture how AES-KDF works but is the core loop AIUI:

```
#include <gcrypt.h>
#include <stdint.h>

int main()
   {
   const uint8_t key[32] = { 0 };
   uint8_t buf[32] = { 0 };

   gcry_cipher_hd_t handle;
   gcry_cipher_open(&handle, GCRY_CIPHER_AES256, GCRY_CIPHER_MODE_ECB, 0);

   gcry_cipher_setkey(handle, key, sizeof(key));

   for(size_t i = 0; i != 169540232; ++i)
      gcry_cipher_encrypt(handle, buf, sizeof(buf), buf, sizeof(buf));


   for(size_t i = 0; i != 32; ++i)
      printf("%02X", buf[i]);
   }
```

and

```
#include <botan/block_cipher.h>

int main()
   {
   auto aes256 = Botan::BlockCipher::create_or_throw("AES-256");

   const uint8_t key[32] = { 0 };
   uint8_t buf[32] = { 0 };

   aes256->set_key(key, sizeof(key));

   for(size_t i = 0; i != 169540232; ++i)
      aes256->encrypt_n(buf, buf, 2);

   for(size_t i = 0; i != 32; ++i)
      printf("%02X", buf[i]);
   }
```

Both progs print the same value. On my machine (x86_64 with AES-NI, GCC), Botan version takes 2.5 seconds, libgcrypt version 3.6 seconds. TBH that libgcrypt is appreciably slower here is weird to me.

**Comment by droidmonkey** [comment]
So ironically removing the parallel calculations and doing a straight 2-block encrypt like @randombit did above brings 2.7.0 back to parity with 2.6.6. I tested the two side by side and noticed an appreciable difference in the original code, same as @antrys. Removing the parallel calc immediately improves the performance, quite unintuitively.

**Comment by phoerious** [comment]
Does Botan have a static mutex or something that would prevent parallel execution?

**Comment by randombit** [comment]
There is a global mutex that guards a `mlock`ed memory pool, but it wouldn't affect parallelism in this case because we are careful to not heap allocate/free memory during tight loops (if nothing else because even `new`/`delete` are bad news for performance)

If you set an environment variable `BOTAN_MLOCK_POOL_SIZE` to `0` in `main` prior to invoking any library function you can disable this entirely.
