### ISSUE TITLE
Auto-Type no longer works

### ISSUE THREAD

**Issue by braunharald** [keepassxreboot/keepassxc#7684]
As usual, I first go to the login of the website I want to log into. Then I switch to KeyPassXC. If I use Auto-Type now, I am asked "Execute Auto-Type in the previously active window? I answer this with Yes. And unfortunately nothing happens!

Debug info:
KeePassXC - Version 2.7.0
Revision: d7a9ef4

Qt 5.12.8
Diagnostic mode is disabled.

Operating system: Ubuntu 20.04.4 LTS
CPU architecture: x86_64
Kernel: linux 5.4.0-105-generic

Enabled extensions:
- Auto-Type
- Browser integration
- SSH agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.12.1

With kind regards
Harald Braun

Translated with www.DeepL.com/Translator (free version)

**Comment by droidmonkey** [comment]
Duplicate and fixed for 2.7.1

**Comment by TxX8N8LN** [comment]
@braunharald , for me i need to go in configure global of Auto-Type and disable "Always ask before performing Auto-Type"
And now it's work like before
