### ISSUE TITLE
Option "Require password confirmation if visible" with no effect?

### ISSUE THREAD

**Issue by l0f4r0** [keepassxreboot/keepassxc#7685]
## Overview
In "Tools" > "Parameters", "Security" tab, there is an option called something like "Require password confirmation if visible".

It's checked for me but nowhere I can see any confirmation asked...

I cannot exactly remember but I believe it was available at some point in the past (except if I'm mistaking with KeepassX?): I had to retype the pasword one more time when clear/visible (2 password fields, one below the other).

## Steps to Reproduce
1. Check program security parameter "Require password confirmation if visible" 
2. Create a new entry
3. Type a password (visible mode)

## Expected Behavior
Ask for password confirmation when clear/visible

## Actual Behavior
No confirmation asked

## Context
> KeePassXC - Version 2.7.0
> Revision : d7a9ef4
> Canal : AppImage
> Operating System: Linux Debian 10 64bits
> Desktop Env: XFCE 4.12.5
> Windowing System: X11

**Comment by droidmonkey** [comment]
This only applies to the database password

**Comment by l0f4r0** [comment]
Ok, thanks for the quick feedback!

Can I suggest to add this feature for entries as well?
