### ISSUE TITLE
Keepass 2.7 not visible on remote VNC cession

### ISSUE THREAD

**Issue by OlivierDoucet** [keepassxreboot/keepassxc#7687]
## Overview
With keepassXC 2.7.0 version on windows system, when I open a VNC remote cession, the window of Keepass is not visible on the VNC windows
KeePassXC - VERSION 2.7
Remoted PC : Windows 10
PC of VNC cession :
 * Linux ubuntu with VNC Remmina 1.4.2 : the Keepass windows is not visible
 * Windows 10 with VNC viewer :  the Keepass windows is black

with keepass 2.6.6 all was OK

Best regards

**Comment by michaelk83** [comment]
https://keepassxc.org/docs/KeePassXC_UserGuide.html#_screenshot_security
There are a number of similar issues. Please use the search.

**Comment by willishoward** [comment]
It seems simple enough to add the --allow-screencapture option when running KeePassXC  from a command line, but where do you put the option for the autostart path in Windows 11?

**Comment by droidmonkey** [comment]
In the registry: `HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Run`

**Comment by willishoward** [comment]
Thanks for that. After some thought, I decided that I didn't want to always have this option selected. So, I left the registry as is. I added a batch file to the desktop that runs an enabled version as needed. It contains the following one line:
START "" "C:\Program Files\KeePassXC\KeePassXC.exe" --allow-screencapture

**Comment by OlivierDoucet** [comment]
Thank you for your advice, That works.
I think it could be better to add this new option on parameters menu
Best regards
