### ISSUE TITLE
Error while update install 2.7.0 version

### ISSUE THREAD

**Issue by sashaurch** [keepassxreboot/keepassxc#7688]
good afternoon
__When installing update version 2.7.0 downloaded from the official site "https://github.com/keepassxreboot/keepassxc/releases/download/2.7.0/KeePassXC-2.7.0-Win64.msi"

After completing the installation and trying to start the program, it gives an error: "The program cannot be started because vcruntime140_1.dll was not found on your computer. Please try to reinstall the program to fix this problem." But ...
After downloading this library, it gives an error ...: "The program cannot start because MSVCP 140_1.dll was not found on your computer. Please try reinstalling the program to fix this problem." After downloading this library, it gives ... "startup error ... 0x000000".

I had to roll back to version 2.6.6 which works fine.

Thank you in advance.   (27.03.2022)

**Comment by droidmonkey** [comment]
Check out the pinned issues.....
