### ISSUE TITLE
Allow choice of default browser in application settings

### ISSUE THREAD

**Issue by bowiechen** [keepassxreboot/keepassxc#7689]
## Summary
The current behavior of KeePassXC is to open the URL of an entry using the system's default browsers. We should add the ability to let users choose a default browser in application settings.

## Context
I use multiple browsers for different reasons, but the most notable example would be to have a work browser (with work-specific setup) and a personal browser. It's pretty annoying to have to open the entry and copy the URL into the non-default browser.

I have no experience working in this code base, but if this isn't too difficult, I'd love some guidance to make this happen!

**Comment by bowiechen** [comment]
@droidmonkey Can you attach the ticket that is duplicate of this one? I can subscribe to updates there.

**Comment by droidmonkey** [comment]
Its easy for you to find through searching. #4495
