### ISSUE TITLE
Improvement: KeePassHTTP should return selected only credential

### ISSUE THREAD

**Issue by mauron85** [keepassxreboot/keepassxc#769]
User experience can be improved when KeePassHTTP return selected only credential instead of all possible.

## Expected Behavior

Selected credential from `HTTP Confirm Access Dialog` should propagate also to the browser extensions.

## Current Behavior

`HTTP Confirm Access Dialog` display all matched credentials as a list. List items are clickable, meaning user can select single credential entry.

![image](https://user-images.githubusercontent.com/359450/28211948-7e4c39b0-689f-11e7-8b20-57f1102f6c03.png)

Currently selecting credential in dialog has no effect. 
As result user has to repeat same selection in the browser.

![image](https://user-images.githubusercontent.com/359450/28212408-8c60bcc2-68a1-11e7-983d-ae2d3c1f349a.png)

## Possible Solution

Adding some sort of flag to http "get-logins" response, with information which entry was selected.
Then browser extension can read this information and only display selected entry or fill username/password immediately.

To stay compatible I suggest adding new prop `IsSelected` into http post response, indicating entry was selected in HTTP dialog.
```
{
"Count":4,
"Entries":[{
    "Login":"Y76RwRTD04meC/aItgadRQ==",
    "Name":"81q2E88dhKzWRuh7n7jiRiJmtKXSZByshrvVd+7jGII=",
    "Password":"Y76RwRTD04meC/aItgadRQ==",
    "StringFields":null,
    "Uuid":"9m1kgbJnzr33Nb84/ce70pI6k/yoeqnQOcSo2/OdQwwJgBf1tOS3BdBMxAMsGF1l"
    "IsSelected": true
}]
...
}
```

**Comment by droidmonkey** [comment]
That dialog is just authorizing the transfer of the credentials from the database to the plug-in. The plugin takes it from there. This may still be an issue of providing all the suggested credentials instead of just the selected one though.

**Comment by mauron85** [comment]
A consider it more like UX problem then technical one. Even tough filtering which credentials will be passed to the browser directly in the dialog would be nice, I'll be more then happy with just information which username/password combo was selected in dialog.

**Comment by PF93mc8y7erq92qTmTjJBysALa** [comment]
KeePassHTTP was removed. As of 2.4.0 it is no longer part of KeePassXC. See #1752.
