### ISSUE TITLE
yubikey integration not working after upgrade to 2.7.0

### ISSUE THREAD

**Issue by cmek** [keepassxreboot/keepassxc#7690]
## Overview
It looks like yubikey integration no longer works after snap upgrade to 2.7.0. 

I'm getting the following error when starting keepassxc:
YubiKey: Failed to establish PCSC context.
YubiKey: PCSC interface is disabled or not initialized.

I'm also getting the same error message via cli:

"YubiKey: Failed to establish PCSC context.
YubiKey: PCSC interface is disabled or not initialized.
Failed to issue challenge:  "General: Could not find interface for hardware key with serial number 0. Please connect it to continue."
Error while reading the database: Unable to calculate database key: General: Could not find interface for hardware key with serial number 0. Please connect it to continue."

This could be somehow related to #7607 since that ticket mentions similar YubiKey related issues. Although I have no problems selecting the database file - the file selection pop up works fine but the "Hardware Key" dropdown menu shows no yubikeys available.

I have tried reinstalling with --classic but the result is the same. 

The problem actually started with the CLI only - I could no longer open the databases with keepassxc.cli while the GUI was still working. After removing the snap and installing again the GUI stopped working too.

## Steps to Reproduce
1. start keepasxc (installed from snap)
2. see that the "hardware key" has no yubikeys available in the dropdown menu

alternatively:
1. start keepassxc.cli: keepassxc.cli show -y 2 /path/to/passwords.kdbx $entry_name -a Password
2. see the following error message: 
"YubiKey: Failed to establish PCSC context.
YubiKey: PCSC interface is disabled or not initialized.
Failed to issue challenge:  "General: Could not find interface for hardware key with serial number 0. Please connect it to continue."
Error while reading the database: Unable to calculate database key: General: Could not find interface for hardware key with serial number 0. Please connect it to continue."

## Expected Behavior
yubikey should be visible in the dropdown menu in the GUI and should be working from the CLI. At least both worked with the previous version. :)

## Context

ubuntu 20.04 with i3wm

KeePassXC - Version 2.7.0
Revision: 20c9ac1
Distribution: Snap

Qt 5.15.3
Debugging mode is disabled.

Operating system: Ubuntu Core 20
CPU architecture: x86_64
Kernel: linux 5.13.0-35-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.12.1

Operating System: Linux - Ubuntu 20.04
Desktop Env: i3wm
Windowing System: X11

**Comment by cmek** [comment]
the GUI seems to be working fine with a locally snapcrafted versioni installed with these options:

`snap install keepassxc_2.7.0_amd64.snap --devmode --dangerous`

The CLI still complains about not being able to find the key. 

If I pass it without the serial number - "-y 2":

" YubiKey: Failed to establish PCSC context.
YubiKey: PCSC interface is disabled or not initialized.
Failed to issue challenge:  "General: Could not find interface for hardware key with serial number 0. Please connect it to continue."
Error while reading the database: Unable to calculate database key: General: Could not find interface for hardware key with serial number 0. Please connect it to continue."

or with it "-y 2:13792894":

YubiKey: Failed to establish PCSC context.
YubiKey: PCSC interface is disabled or not initialized.
Failed to issue challenge:  "General: Could not find interface for hardware key with serial number 13792894. Please connect it to continue."
Error while reading the database: Unable to calculate database key: General: Could not find interface for hardware key with serial number 13792894. Please connect it to continue.

The serial number is the same the GUI version is reporting, and the same one as reported by the yubikey tools.

**Comment by droidmonkey** [comment]
Yubikey was broken in cli, fixed for 2.7.1. Those messages you see are just warnings not errors. 

https://keepassxc.org/docs//#faq-appsnap-yubikey
