### ISSUE TITLE
Double click to copy to clipboard broken in latest update

### ISSUE THREAD

**Issue by Evaporate-Lunchtime** [keepassxreboot/keepassxc#7691]
## Overview
Double clicking in either the Password or Username fields of a given database entry now takes you to the Edit entry page instead of copying either the Username or the Password to clipboard, as it did before the update.

## Steps to Reproduce
1. Double click on either Username or Password field of a database entry.

## Expected Behavior
Expected username and password to be copied to clipboard when double clicking on the respective fields of a given database entry.

## Actual Behavior
Double clicking in either the Username field or the Password field now takes me to the Edit entry page for the given database entry.

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.0
Revision: d7a9ef4

Qt 5.15.3
Debugging mode is disabled.

Operating system: Windows 10 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.19044

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 2.18.1

[NOTE]: # ( Pick choices based on your environment )
Operating System:  
Edition	Windows 10 Pro
Version	21H2
OS build	19044.1586

**Comment by droidmonkey** [comment]
Enable it in security settings
