### ISSUE TITLE
2.7.0 does not run on current version of Mac (Monterey 12.2.1)

### ISSUE THREAD

**Issue by MissouriSpiff** [keepassxreboot/keepassxc#7692]
## Overview
[NOTE]: # ( Give a BRIEF summary about your problem )
I get this error message when attempting to run v 2.7.0 on Mac Monterey 12.2.1:
"You can’t open the application “KeePassXC.app” because this application is not supported on this Mac."

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Install keepassxc 2.7.0 by downloading, opening dmg, dragging app to Applications folder.
2. Attempt to run.
3. 

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Expected it to run like usual, like it did just before update of KeePassXC.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Did not run beyond producing error message.

## Context
[NOTE]: # ( Give us any additional information you may have. )
Can someone tell me where to find the last working version for Mac? 
MacbookPro laptop running Monterey. Updated KeePassXC from download here: https://keepassxc.org/download/
Choose Binary bundle (macOS 11.1+) DMG.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.0
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS Monterey 12.2.1
Desktop Env: 
Windowing System:

**Comment by droidmonkey** [comment]
Make sure you download the correct DMG for your mac. Either ARM (M1 Silicone) or x86 (Intel).
