### ISSUE TITLE
Even checkbox-enable-doubleclick-copy unchecked, it copies something. (Related #6433)

### ISSUE THREAD

**Issue by Galliver7** [keepassxreboot/keepassxc#7693]
## Overview
From the 2.7.0 feature, #6433 was added and works to turn off the copy when it's double-clicked. (Love this)
But it is copying something (maybe brank?), so I can see a countdown that notices the remaining time to clear which copied.
This practically brokes "Hide window when copying to clipboard" setting where setting -> General -> Entry management. I double-click an entry to open, but KeePass goes hidden because it's copied something.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Uncheck "Enable double click to copy the username/password entry columns", Where Settings -> Security -> Convenience
2. Check "Hide window when copying to clipboard", Where Settings -> General -> Entry management
3. At Entry view, double click some field.
4. KeePass goes Minimize/Drop to background

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
When an entry is double-clicked, KeePass doesn't copy something. Which makes KeePass doesn't Minimize/Drop to background.

## Actual Behavior
When an entry is double-clicked, KeePass copies something. Which makes KeePass goes Minimize/Drop to background.

## Context
[NOTE]: # ( Give us any additional information you may have. )
This confused who checks "Hide window when copying to clipboard". 
It seems #6433 has been broken, But I notice the clearing indicator is showing up, and the clipboard is empty.

![イメージ](https://user-images.githubusercontent.com/8030470/160331855-9e9df1d3-29eb-41b4-85da-8918c3cb5706.png)

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.0
Revision: d7a9ef4

[NOTE]: # ( Pick choices based on your environment )
Operating system: macOS 12.2
CPU architecture: arm64
Kernel: darwin 21.3.0

**Comment by phoerious** [comment]
What do you mean "breaks"? I cannot reproduce what you describe. When both options are checked, double click copies and minimises the window, if only minimise is checked, it prompts me to edit the entry on double click. So everything is as expected.

**Comment by Galliver7** [comment]
@phoerious 
Thanks for the reply.
I was shooting a video explaining the behavior of the issue and found that the application PopClip, which I usually use, was causing the strange behavior.
I tried again with PopClip stopped and the strange behavior did not stop.

I believe this is not a KeePass issue, an application compatibility issue, so please close this issue.

Thank you for your time.
Just to be sure, I have included a video of the behavior of the issue that occurs with PopClip running.

![keepass-report](https://user-images.githubusercontent.com/8030470/160355850-c9367235-ee3b-4b65-8791-c5efb3f93cc4.gif)

**Comment by droidmonkey** [comment]
That is very strange.
