### ISSUE TITLE
Since 2.7 I cannot double click to a name and a password to copy it 

### ISSUE THREAD

**Issue by tkoeck** [keepassxreboot/keepassxc#7694]
Since 2.7 I cannot double click to a name and a password to copy it. It just jumps in the entry.

What's going on?

**Comment by tkoeck** [comment]
The copy to clipboard doesn't work anymore. I rolled back to 2.66. The 2.7 doesn't seem to be usable.

**Comment by tkoeck** [comment]
Okay my fault. This seems to be a 'security option'. Still weird that it isn't mentioned after starting it the first time.

**Comment by liminspace** [comment]
@tkoeck  that feature was very usable. I cannot believe you removed it :(. please, move it into settings to have the opportunity to enable it

**Comment by tkoeck** [comment]
> @tkoeck that feature was very usable. I cannot believe you removed it :(. please, move it into settings to have the opportunity to enable it

I didn't remove anything. You should tell the coders directly. :)

**Comment by droidmonkey** [comment]
It is in the settings... security settings to be exact
