### ISSUE TITLE
Generate Password not working on browser after upgrade to 2.7.0

### ISSUE THREAD

**Issue by Kyshman** [keepassxreboot/keepassxc#7696]
## Overview
I recently upgraded to version 2.7.0. Everything seemed to work fine until I noticed that the password generate  ability on web pages seems to not work.

## Steps to Reproduce
Go to a web page with a password form either when changing password or crating a new password (Either **[Firefox 91.7.1esr (64-bit)]** or **[Microsoft Edge Version 99.0.1150.55 (Official build) (x86_64)]**)

1. KeePassXC 2.7.0 is open and database unlocked
2. KeepassXC-Browser extension is installed and connected to database
3. Go to password field
4. Click key icon or right click within password field --> select KeePassXC-Browser --> Show Password Generator

## Expected Behaviour
The Password Generator window should pop up to enable you to generate a new password, select its complexity and finally paste it into the password field or copy it into the clipboard

## Actual Behaviour
Instead of the Password Generator window popping up nothing happens

## Context
For situations where I need to generate a password am forced to go to the main KeepassXC window, go to Password Generator, generate a new password, copy into clipboard and finally paste it into the web page/password field. 

This adds a few extra steps into my work-flow that were not there before.

## KeePassXC Details
*KeePassXC:*  Version 2.7.0 (Installed via .DMG)
*Revision:* d7a9ef4

##OS Details
*Operating System:* macOS - Big Sur - 11.6.5 (20G527)

**Comment by droidmonkey** [comment]
Thank you this has been reported and being fixed at this time
