### ISSUE TITLE
Enable autotype to use mouse input

### ISSUE THREAD

**Issue by mame98** [keepassxreboot/keepassxc#7697]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )

For some use-cases, keys do not work to switch between the two input fields for username/password. For example some video-games I play have this problem. As the login-dialog is always at the same location, it could be a work-around to enable cursor events for auto-type.

I could not find anything related to this in the [documentation](https://keepassxc.org/docs/KeePassXC_UserGuide.html#_auto_type)

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )

One example I thought of:

```
{CLICK <X> <Y>}{USERNAME}{CLICK <X> <Y>}{PASSWORD}{ENTER}
```

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )

Some video games require me to click into the username/password boxes and do not support any keyboard buttons to switch between them.

**Comment by droidmonkey** [comment]
We cannot do that because we have no idea where to actually click to be successful. Your best solution is to add a `{DELAY 3000}` and you perform the clicking in between types.

**Comment by mame98** [comment]
I am not sure If I understand the problem. The user could provide x and y screen coordinates?

**Comment by droidmonkey** [comment]
There is no guarantee those coordinates will be consistent.

**Comment by mame98** [comment]
But for some applications they will be consistent. Especially for füll screen games.

**Comment by droidmonkey** [comment]
How do you know what the x/y coordinates are? This is just a whole lot of work for something easily solved with an existing delay feature.

**Comment by mame98** [comment]
I would get the coordinates by taking a screenshot and checking the pixel coordinates in something like GIMP.

I know that this is far from a user-friendly solution, but could be helpful as a workaround for cases like this.

But of course if you think that this is just too much implementation / maintenance work for such a specific use case, I will just use the delay function as suggested :+1:

**Comment by droidmonkey** [comment]
Yah it's just too cumbersome to be useful to the vast majority of users without some sort of workflow/picker tool which is yet more complexity.

**Comment by mame98** [comment]
Makes sense

Out of curiosity: If I would implement such a feature in the future, would you accept a merge request or would that still be to much maintenance work?

**Comment by droidmonkey** [comment]
We end up incurring the "maintenance" of it, including cross platform support. You can give it a go, well look at whatever you out together.
