### ISSUE TITLE
Change icon of all selected entries

### ISSUE THREAD

**Issue by reagle** [keepassxreboot/keepassxc#770]
I'd like to select a few entries and change all their icons at once. I figure this must be an option, but I can't figure out how to do it?

## Debug Info
keepassxc: 2.2.0
/usr/local/Caskroom/keepassxc/2.2.0 (68B)
From: https://github.com/caskroom/homebrew-cask/blob/master/Casks/keepassxc.rb

(There is no "Help → About here" menubar option.)

**Comment by rominf** [comment]
Related: #1314

**Comment by phoerious** [comment]
Duplicate of #735

**Comment by therealmaxmoon** [comment]
Is there a solution to this issue? Because the linked issues don't look like they are related to this one.

**Comment by droidmonkey** [comment]
You can do this though editing the group icon. You can select to have that icon propogate to the entries under the group
