### ISSUE TITLE
unable to permanently hide database tags pane

### ISSUE THREAD

**Issue by ghost** [keepassxreboot/keepassxc#7700]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

database tags pane under groups consistently opens, without a way to hide it permanently

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. open keepassxc
2. observe database tags section under password groups
3. drag the pane down to hide it
4. close keepassxc and reopen it
5. reopen the same database as before
6. see pane is back open

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

an option to never show this pane or dragging it to hide it permanently hides it

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

pane reopens constantly when reopening the database

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.0
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows
Desktop Env: n/a
Windowing System: n/a

**Comment by droidmonkey** [comment]
Hmmmm pretty sure I implemented that, I spent quite a bit of time making sure that worked. You seem to have skipped a lot of steps in your writeup. How do you go from dragging the panel down to reopen database?

**Comment by ghost** [comment]
sorry all i do at that stage is close keepass and reopen it. i can replicate it by closing and reopening just the database too

**Comment by droidmonkey** [comment]
This is the relevant code:

https://github.com/keepassxreboot/keepassxc/blob/fc5a07b46d05e5c258c7a2ccbbcc4acb25d6afab/src/gui/DatabaseWidget.cpp#L333

**Comment by droidmonkey** [comment]
I cannot replicate this at all. Make sure your config file is being properly saved.
