### ISSUE TITLE
Autofill no longer works

### ISSUE THREAD

**Issue by klabog** [keepassxreboot/keepassxc#7701]
## Overview

[NOTE]: # ( Give a BRIEF summary about your problem )
Since the last update, autofill function no longer works. It is not executed in the terminal nor on websites.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Open login or other page to insert user and or password
2. Open window with active keepassxc  and right click autofill
3. You are asked if you want to fill out dates in last active window (question which in my opinion is useless because you have no other alternative as to cancel)
4. Confirm
5. Click one of the available options
## Expected behaviour 
[NOTE]: # ( Tell us what you expected to happen )
Dates should be written like before update
## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Nothing is written in field of user nor password

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.0
Revision: d7a9ef4

Qt 5.12.8
Diagnosemodus ist deaktiviert.

Betriebssystem: Ubuntu 20.04.4 LTS
CPU-Architektur: x86_64
Kernel: linux 5.13.0-37-generic

Aktivierte Erweiterungen:
- Auto-Type
- Browser-Integration
- SSH-Agent
- KeeShare
- YubiKey
- Secret-Service-Integration

Kryptographische Bibliotheken:
- Botan 2.12.1

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: Gnome
Windowing System: X11/Wayland ?

**Comment by droidmonkey** [comment]
Fixed for 2.7.1
