### ISSUE TITLE
Having KeepassXC main window open breaks Moonlight streaming (DRM-protection)

### ISSUE THREAD

**Issue by wilhelmy-fielmann** [keepassxreboot/keepassxc#7702]
## Overview
Whenever you are trying to connect with Moonlight (PC-streaming software), and you have the KeepassXC main window open, the stream connection will fail, with a mention of DRM-protected content. If you already are in a successful streaming session, and then open the KeepassXC window, then the connection will immediately fail.

I'm guessing GeForce Gamestream will also fail as well.

Downgrading KeepassXC to v2.6.6 fixes this issue completely.

## Steps to Reproduce
1. Open KeepassXC window
2. Attempt to connect with Moonlight (any version)
3. Connection will fail (DRM error)

or

1. Ensure KeepassXC window is closed (not minimized)
2. Connect with Moonlight (any version)
3. Open KeepassXC window
4. Connection will fail (DRM error)

## Expected Behavior
Should not fail. I've used KeepassXC along with streaming for years before v2.7.0

## Context
Started happening when I updated from v2.6.x to v2.7.0. 

Nvidia drivers (or versions) do not affect this issue (I clean downgraded when troubleshooting)

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - v2.7.0
Revision: stable

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 10 x64 21H1

**Comment by droidmonkey** [comment]
https://keepassxc.org/docs/KeePassXC_UserGuide.html#_screenshot_security
