### ISSUE TITLE
Auto-Type Stutters Lags When Auto Filling In User/Pass

### ISSUE THREAD

**Issue by 0pLuS0** [keepassxreboot/keepassxc#7703]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

I use ```Ctrl+Z``` Global auto type shortcut, when I press Ctrl Z at a site to log in, and the AutoType UI pops up showing me the accounts to choose from, and I double click an entry, it then begins typing in the characters for the username and password, it's not smooth. It stops and starts, like it's lagging between characters. This varies at different sites, some sites it fills in the username and password smoother and faster, and at other sites, it will, as an example, type in a few characters, then stop, then start again and then stop, and do this every other character, constantly stoping and starting.

Most sites I go to, it takes typically 5-7 seconds for it to fill in my username and password.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Press Ctrl Z to bring up the Auto Type UI
2. Double Click on an entry
3. KeePassXC begins auto typing in the characters

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
I expect the auto typing/filling in of the characters to be smooth/fluid and quick

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
The auto typing/filling in of the characters, stutters and lags

## Context
[NOTE]: # ( Give us any additional information you may have. )
I lowered the settings in the Start and Typing delay, this did not have any effect.

```Is there any way I can make KeePassXC smoothly and quickly auto fill?```

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.0
Revision: d7a9ef4

Qt 5.15.3
Debugging mode is disabled.

Operating system: Slackware 15.0 x86_64
CPU architecture: x86_64
Kernel: linux 5.15.28

Enabled extensions:
- Auto-Type

Cryptographic libraries:
- Botan 2.19.1

[NOTE]: # ( Pick choices based on your environment )
Operating System: ```Slackware 15.0```
Desktop Env: ```Openbox 3.6.1```
Windowing System: ```X11```

THANKS

**Comment by droidmonkey** [comment]
Are you using a non English keyboard layout?

**Comment by 0pLuS0** [comment]
No...

I'm using a HyperX Alloy FPS Pro (87 Keys);

https://www.hyperxgaming.com/us/keyboards/alloy-fps-pro-mechanical-gaming-keyboard

P.S. I'm a gamer... LOL

**Comment by droidmonkey** [comment]
Not your physical keyboard, your keyboard layout in Linux. Are you using German, Polish, Russian, etc layout?

Also try typing into the text editor. If it doesn't stutter than it's the browser or web page doing dumb things.

**Comment by 0pLuS0** [comment]
standard us qwerty keyboard

Typing in an editor is fine, maybe bloody FF ESR version... hmm

**Comment by droidmonkey** [comment]
Going to close this, we have had issues with Firefox and Auto-Type in the past. If other apps don't have the problem its 99% Firefox being dumb.

**Comment by 0pLuS0** [comment]
I'm really sorry I opened this issue, I didn't realize the Chameleon addon I was using, with the option ```Protect keyboard fingerprint``` created this lag, I just didn't recall seeing it like this in the past, is why I never considered this addon.

So if anyone ever uses this addon in Firefox you can point them here;

https://sereneblue.github.io/chameleon/wiki/options

Thanks a lot for your time, keep up the great work!
