### ISSUE TITLE
problem solution VCRUNTIME140_1.dll  is no longer available from Microsoft! 

### ISSUE THREAD

**Issue by PADIXO** [keepassxreboot/keepassxc#7704]
Problem System Error: VCRUNTIME140_1.dll what not found #7564 still exists, and the problem solution https://github.com/keepassxreboot/keepassxc/issues/7564#issuecomment-1074842970 is no longer available from Microsoft! (Connection failed, Firefox cannot connect to the server on download.visualstudio.microsoft.com.)

**Comment by PADIXO** [comment]
Microsoft Windows 10 Pro x64
Version	10.0.19042 Build 19042

**Comment by phoerious** [comment]
The connection issue is on your side. The link is still up. In any case, no need to create a new issue report.
