### ISSUE TITLE
Support for MacOS's Touch Bar

### ISSUE THREAD

**Issue by cookieMr** [keepassxreboot/keepassxc#7709]
## Summary
Show the "👣 Unlock Database" button (to unlock the DB with a Mac's TouchID) on MacOS TouchBar.

## Examples
MacOS has a [Touch Bar (see wikipedia)](https://en.wikipedia.org/wiki/MacBook_Pro#Fourth_generation_(Touch_Bar)) and [a photo of a touch bar](https://en.wikipedia.org/wiki/MacBook_Pro#/media/File:Touch_bar_of_15%22_MacBook_pro.jpg).

## Context
TouchID is next to Touch Bar. Spotify integrates with MacOS Touch Bar really nicely.

**Comment by phoerious** [comment]
I don't think this is worth the effort. While my MBP still has one, the new models don't and it seems like Apple generally abandoned the concept.

**Comment by cookieMr** [comment]
In that case i am not replacing my Mac any time soon™.
