### ISSUE TITLE
macOS to Windows database sync issues.

### ISSUE THREAD

**Issue by impierced** [keepassxreboot/keepassxc#771]
## Expected Behavior

When saving changes in KeePassXC on macOS, any open copy on Windows should automatically update.

## Current Behavior

Saving changes in KeePassXC on macOS results in an error in KeePassXC on Windows of "Could not open the new database file while attempting to autoreload this database."

## Possible Solution

Only solution is to quit KeePassXC on Windows and thereby reload the database.

## Steps to Reproduce (for bugs)

1. Open a database in KeePassXC from a file server on macOS and on Windows at the same time.
2. Clone any entry in KeePassXC on macOS and save the database.
3. KeePassXC on Windows will report the error, "Could not open the new database file while attempting to autoreload this database."

What's interesting to note is that saving and automatic updating in KeePassXC from Windows to Windows, macOS to macOS, and Windows to macOS function as expected; the cloned entry shows up promptly.

## Context

Cross platform compatibility is critical for us and while database changes work from Windows to Windows, macOS to macOS , and Windows to macOS as expected, it would be great to have the same functionality for macOS to Windows.

## Debug Info

KeePassXC - 2.2.0
Revision: caa49a8ef3ee28ed478192389b21d61107b3b8e0

Libraries:
- qt 5.9.0
- libgcrypt 1.7.7

Operating system: mac OS Sierra (10.12)
CPU architecture: x86_64
Kernel: darwin 16.6.0

Operating system: Windows 10 (10.0)
CPU architecture: x86_64
Kernel: winnt 10.0.10586

Enabled extensions:
- KeePassHTTP
- Auto-Type
- YubiKey

**Comment by droidmonkey** [comment]
Are you using network shares?

**Comment by impierced** [comment]
Yes, Windows file server to be specific.

**Comment by leonyu** [comment]
Do you have a SMB 3.0 server? 

Have you tried increasing `MaxCmds` for the server? As the underlying call probably depends on `FindFirstChangeNotification` ([ref](https://www.goodreads.com/author_blog_posts/13591603-enterprise-smb-performance-reg-tweak))

I have dealt with a `inotify/FSEvents/FindFirstChangeNotification` issue before, it is quite challenging to get it working 100% as it depends on too many variables (OS kernel of both server and client, protocol version, server software, client software, consuming software)

**Comment by impierced** [comment]
Windows 2013 Server, with all clients using SMB 3.0.

Mac (new entry and file save) to Mac (auto propagates new entry) = fine
Windows (new entry and file save) to Windows (auto propagates new entry) = fine
Mac (new entry and file save) to Windows (auto propagates new entry) = error
Windows (new entry and file save) to Mac (auto propagates new entry) = sporadic behavior

**Comment by scic** [comment]
We also share a file with a NFS share. KeepassXC does also not detect if the file was changed by an other user. But this is somewhat expected since its "usual" that file watches are not shared over network file systems. It could be solved by actively polling the file at an interval but I think this is overkill.

Instead I would recommend to **just poll/check the file before a save operation**. Maybe show the merge dialog. This would solve the issue of overwriting a changed file. That this is a useful behavior is also motivated at: https://github.com/keepassxreboot/keepassxc/issues/90#issuecomment-305489388

BTW: *"Keepass 2"* also solves this issue with a file check before save.

**Comment by droidmonkey** [comment]
I think this is happening because SMB posts a file change and then yanks or locks the file while KPXC is trying to load it. There is definitely a UX issue here. Sorry for the data loss, I will add this to my priority list.

**Comment by droidmonkey** [comment]
This will be fixed with the fix for #2389
