### ISSUE TITLE
Attachment Open & Save Button Won't Work

### ISSUE THREAD

**Issue by Juan-Embid** [keepassxreboot/keepassxc#7711]
## Overview
The Open/Save buttons from attachments won't work as expected. Open button won't open the file and Save button won't save the file in a directory.

## Steps to Reproduce
1. Create a new entry
2. Fill it with information
3. Go to advance
4. Add attachment
5. Try adding a certificate file (.p12)
6. Apply changes & Ok
7. Now try opening it or saving it

## Expected Behavior
* Open button 
  * File to be open with default application or a window asking the application you want to use to open the file

* Save button
  * Save attachment window opens. Directory is selected and file is stored

## Actual Behavior
* Open button 
  * Dummy button. It won't do anything

* Save button
  * Save attachment window opens. Directory can't be selected, only files.

## Context
[NOTE]: # ( Give us any additional information you may have. )

## Debug info
| Option | Description |
| ----------- | ----------- |
| KeePassXC | Version 2.7.0 |
| Revision | 20c9ac1 |
| Distribution | Snap |
| Qt 5.15.3 | Debugging mode is disabled |
| Operating system | Ubuntu Core 20 |
| CPU architecture | x86_64 |
| Kernel | linux 5.13.0-37-generic |

Enabled extensions:
- [x] Auto-Type
- [x] Browser Integration
- [x] SSH Agent
- [x] KeeShare
- [x] YubiKey
- [x] Secret Service Integration

Cryptographic libraries:
- [x] Botan 2.12.1

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: Gnome
Windowing System: X11

**Comment by droidmonkey** [comment]
Snap bug

**Comment by jaylinski** [comment]
Is there any workaround? (Other than using the non-snap version?)

Is there a open issue in another project where I can track the progress of fixing this issue?

Edit: nevermind, duplicate of #7607.
