### ISSUE TITLE
UI on 2.7.0 for attachments and TOTP columns are too wide

### ISSUE THREAD

**Issue by paddylandau** [keepassxreboot/keepassxc#7714]
## Overview

The "attachments" and "TOTP" columns are extra-wide.

This is in the official PPA version; the snap version is still OK.

This is obviously low priority; it's more of a "papercut" than a full bug.

## Steps to Reproduce

1.  Open the KeePassXC app, and see the "attachments" and "TOTP" columns.
2.  They are too wide, and cannot be resized smaller.

## Expected Behavior

1. The "attachments" and "TOTP" columns should be smaller, because all they show is an icon.

## Actual Behavior

Screenshot from the snap version:
https://pasteboard.co/Zi9Qse1sp9E7.png

Screenshot from the PPA version:
https://pasteboard.co/wRd4chNpoUdb.png

### Debug info from the snap version

KeePassXC - Version 2.7.0
Revision: 20c9ac1
Distribution: Snap

Qt 5.15.3
Debugging mode is disabled.

Operating system: Ubuntu Core 20
CPU architecture: x86_64
Kernel: linux 5.13.0-37-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.12.1

### Debug info from the PPA version

KeePassXC - Version 2.7.0
Revision: d7a9ef4

Qt 5.12.8
Debugging mode is disabled.

Operating system: Ubuntu 20.04.4 LTS
CPU architecture: x86_64
Kernel: linux 5.13.0-37-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.12.1

## Environment

- Linux Ubuntu 20.04.4 LTS
- Gnome 3.36.8
- Windowing System X11

**Comment by droidmonkey** [comment]
I'm not sure how that's even possible, we set an explicit size on those columns. 

https://github.com/keepassxreboot/keepassxc/blob/develop/src/gui/entry/EntryView.cpp#L415

They do get resized a bit bigger if you are sorting from those columns to accommodate the sort arrow image.

**Comment by paddylandau** [comment]
> I'm not sure how that's even possible, we set an explicit size on those columns.

I'm not much of a programmer, so I struggle to understand that function, sorry.

I've just tried this in Lubuntu 20.04.4 LTS, and I get the same result.

Could it be to do with the fonts that are used? I presume that the snap version comes with the fonts included, whereas the PPA version uses the fonts included with the system. It there a way that I can test this?

**Comment by droidmonkey** [comment]
I have no idea, fonts shouldn't be a question in this matter because it's fixed width.

**Comment by paddylandau** [comment]
> I have no idea, fonts shouldn't be a question in this matter because it's fixed width.

Well, if I can do something to help figure this out, let me know. I would simply use the snap version, but I can't open files with it ("Open database" and "Open existing database" don't respond).

**Comment by droidmonkey** [comment]
I have an open support case with Ubuntu on the snap problems

**Comment by b-fett** [comment]
it very looks like it interfere with regular column minimal width. because my current width of that two columns equals other columns minimal width.
