### ISSUE TITLE
v2.7.0 - Can't find config file

### ISSUE THREAD

**Issue by jorgemillanayala** [keepassxreboot/keepassxc#7715]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
I just installed the portable Keypass v2.7.0 on top of former version 2.6.6
On opening KeyPass now I get a red line message saying:

Access error for config file C:/Program Files/KeePassXC/config/keepassxc.ini

Previuosly to ugrade the program I backed up the former version files, but there is no such file as keepassxc.ini within my backup files

I open the database manually and it works well, but the new version does not keep memory of recently opened databases.
Each time I open Keypass v2.7.0 it starts as if it were the first time and does not remember the database I was using.

I wish to find a way to build the config file: keepassxc.ini

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Install V.2.6.6
2. Decompress version 2.7.0 zip file and copy in the same directory as v.2.6.6
3. Open KeyPassXC

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Just to open the database as before.
Keep track of recently opened databases
Not get error message

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Just described

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.0
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 10

**Comment by droidmonkey** [comment]
You can't put the portable version in a restricted directory. Use the installer.

**Comment by phoerious** [comment]
Do you have a `.portable` file in your installation directory? If so, delete it.
