### ISSUE TITLE
Fix for KeePassXC 2.7.0 not working on Windows 8.1

### ISSUE THREAD

**Issue by ghost** [keepassxreboot/keepassxc#7717]
## Overview
KeePassXC version 2.7.0 revision d7a9ef4 does not work on Windows 8.1
Visual C++ 2022 Redistributable x64 and x86 is installed.

**This is very rough and temporary fix. I couldn't find debug symbols to produce something better.**
After fixing the missing symbols a breakpoint is reached at address 0x57B0FF25.
User interface appears to work fine if the popup is not interacted with.
Patching the executable resolves the error completely.

## Missing symbols
SetDllDirectoryA from api-ms-win-core-kernel32-legacy-ansi-l1-1-0.dll found in kernel32.dll
WaitNamedPipeA from api-ms-win-core-namedpipe-ansi-l1-1-0.dll found in kernel32.dll
LoadLibraryW from api-ms-win-core-libraryloader-l1-2-1.dll found in  kernel32.dll
LocalFree from api-ms-win-core-heap-l2-1-0.dll found in  kernel32.dll

## Patch to bypass the breakpoint
KeePassXC.exe(SHA256: 8C5C3CACED2F8A3B2DDF3F4C76AF45F6BCE997320E313D3852AA9EFC776C4469)
At location 0x13F319 replace 0x8B019085C0750BE89AF70800CC with 0x8B019085C0EB0BE89AF70800CC

**Comment by droidmonkey** [comment]
Search the issues, download the legacy windows installer
