### ISSUE TITLE
Incorrect SSH key comment (from attachments)

### ISSUE THREAD

**Issue by thePanz** [keepassxreboot/keepassxc#7718]
## Overview
Incorrect SSH key comment (from attachments) is shown in the "SSH Agent" section

## Steps to Reproduce
1. Generate an SSH key: `ssh-keygen -o -a 256 -t ed25519 -C "hello@webserver.com-2022-03-29"`
2. Create a new entry
3. under "Attachments": Add both public and private keys as attachment into an new entity
4. under "SSH Agent": choose the private key from the attachments
5. the "comment" section and the "public key" are showing the attachment name as the key comment, not the comment added originally at step 1

## Expected Behavior
At step (5): the comment should be `hello@webserver.com-2022-03-29`

## Actual Behavior
At step (5): the comment is the attachment name

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.0
Revision: d7a9ef4

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: KDE
Windowing System: X11

**Comment by thePanz** [comment]
Additional note: the correct SSH key comment is displayed if:
1. enter the details view of the entry from the main screen (the wrong comment is displayed)
2. click on "Add to agent" (the wrong comment is displayed)
3. wait few 1-2 seconds → the right comment is shown both on the "comment" and "Public key"

**Comment by phoerious** [comment]
The public key in KeePassXC is calculated directly from the private key and it seems like, the comment is also part of that, so it should be possible to display the correct comment.

**Comment by hifi** [comment]
This works as intended, the comment is in the encrypted portion of the key file and as long as its not decrypted it'll show the fallback default of the attachment name. The decrypt button is used to reveal the encrypted content - including the comment. Adding to agent has the same effect.

Also if you are adding the private key as an attachment it adds no additional security having a passphrase on the key and it only makes your database opening slower decrypting the key after decrypting the database. If the key is stored unencrypted it shows the correct comment without decryption.

**Comment by thePanz** [comment]
Thank you @hifi  for your inputs! :+1: 

> Also if you are adding the private key as an attachment it adds no additional security having a passphrase on the key and it only makes your database opening slower decrypting the key after decrypting the database. If the key is stored unencrypted it shows the correct comment without decryption.

Would it be great to have it documented! :)

**Comment by segevfiner** [comment]
@hifi The decrypt button is greyed out for some reason though. I can't click it to show the right comment, only "add to agent" causes the right comment to be shown.
