### ISSUE TITLE
File Missing 2.7.0

### ISSUE THREAD

**Issue by SincereUnsaddle** [keepassxreboot/keepassxc#7720]
Hi,
I use Windows 8.1 Pro and Installing Version 2.7.0 makes KeePassXC unusable: I get a message that
api-ms-win-core-kernel32-legacy-ansi-l1-1-0.dll is missing.
2.6.6 is working.
thanks!

**Comment by ccoenen** [comment]
the [release notes](https://keepassxc.org/blog/2022-03-21-2.7.0-released/) mention that one maybe needs the [Microsoft Visual C++ Redistributable](https://aka.ms/vs/17/release/vc_redist.x64.exe) - did you try that already?

**Comment by michaelk83** [comment]
@droidmonkey , may I suggest adding the following at the top of your issue templates:
`## Please check the pinned issues and use search before submitting a new issue.`

It seems too many people skip that step. Also, maybe update the [release notes](https://keepassxc.org/blog/2022-03-21-2.7.0-released/) with key known issues, and point people at the legacy build for Windows 7 and 8 (maybe add it to the download page?). Maybe that'll reduce some of the duplicates being reposted again and again...

**Comment by droidmonkey** [comment]
You can write all you want and people will totally ignore it.

**Comment by glockenstein** [comment]
But the missing file is not part of this redistributable or at least failed to load. Because I have installed this MSVC++ package and get the error too. But only at Windows 7. Windows 10 works.

**Comment by droidmonkey** [comment]
Use the legacy windows installer for windows 8 and below.

**Comment by glockenstein** [comment]
Ah thanks! That was helpful. Maybe there should be some notes at the download page.

**Comment by SincereUnsaddle** [comment]
The redistributable doesn't change anything. However there is now a legacy installer added on the download page https://keepassxc.org/download/ and that works :) Thanks for that!
