### ISSUE TITLE
KeeShare empty db

### ISSUE THREAD

**Issue by cdpb** [keepassxreboot/keepassxc#7721]
## Overview
[NOTE]:

I synchronize two keeshare folders via syncthing. After I discovered some conflicts between the devices I tried to merge the dbs by hand (as auto merging would crash my keepass instance, but that's another story). Anyway. I created another folder in KeePass with KeeShare (tested with import and sync) and pointed it to a .kdbx.share file from my backup (file size 16069).

In the log I get the following message:

```Synchronize /home/m8/KeeShare/.password-shared.kdbx.share shared-merge with Gemeinsame Passwörter```

file size goes down to 5000.. something and the share folder is empty.

What can I do in order to restore the KeeShare Folder from backup?

[NOTE]:
KeePassXC - 2.7.0 also in 2.6.6

[NOTE]: 
Operating System: Linux, Fedora Workstation
Desktop Env: Gnome
Windowing System: X11

**Comment by droidmonkey** [comment]
#6012 and #6477 are this same problem.

**Comment by cdpb** [comment]
I resolved it by restoring the main .kdbx plus the 2 .kdbx.share files from the same backup.
Another method that I tried successful is to export the whole db to csv, import it and set up KeeShare again.
