### ISSUE TITLE
Mac: Auto-Type select dialog not gaining focus

### ISSUE THREAD

**Issue by MrDoodlezz** [keepassxreboot/keepassxc#7722]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
The choice of which window or which dialogue is focused with the shortcut for Auto-Type seems random.
In 80-90% of cases, the dialogue for selecting the desired entry opens with the new search function, but the database also opens in the background and the focus for further keyboard input starts there, contrary to all expectations.

How the current release works:

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Navigate to any given login area.
2. Trigger Auto-Type.
3. Try navigating the entries in the dialogue.
4. Try to confirm the selected entry with Enter/Return.

## Expected Behavior (and of the previous release)
[NOTE]: # ( Tell us what you expected to happen )
_1. I trigger Auto-Type with the shortcut I have designated.
2. I am prompted to unlock (main password or Touch ID).
3. A dialogue with a selection of possible accounts/accesses/entries opens._
5. I can navigate between the entries in said dialogue with the arrow keys.
6. I can confirm the selected entry with Return/Enter and start the Auto-Type sequence.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
_1. I trigger Auto-Type with the shortcut I have designated.
2. I am prompted to unlock (main password or Touch ID).
3. A dialogue with a selection of possible accounts/accesses/entries opens.
4. The arrow keys are used to navigate between the entries in the main window in the background. 
5. Press Return/Enter to start the edit window of the selected entry instead of starting the Auto-Type sequence.

## Context
[NOTE]: # ( Give us any additional information you may have. )
I am working with a MacBook, macOS: 10.15.7 (19H1824)

[NOTE]: # ( Paste debug info from Help → About here ) – BTW: On Mac the _About_ option is hidden under »KeePassXC → About KeePassXC«, just for the sake of completeness. ;)
KeePassXC - Version 2.7.0
Revision: d7a9ef4

Qt 5.15.2
Diagnosemodus ist deaktiviert.

Betriebssystem: macOS 10.15
CPU-Architektur: x86_64
Kernel: darwin 19.6.0

Aktivierte Erweiterungen:
- Auto-Type
- Browser-Integration
- SSH-Agent
- KeeShare
- YubiKey
- Schnelle Entsperrung

Kryptographische Bibliotheken:
- Botan 2.19.1

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS

**Comment by MrDoodlezz** [comment]
Though I'm honestly not sure if this is a bug at all or if it's intentional.

**Comment by HUGHUSR** [comment]
This is the **same problem as bug #4863**.
It is a problem also in Mojave and BigSur.
This previously functioned properly in all versions of macOS.

**Comment by MrDoodlezz** [comment]
Nope, actually it’s not the same problem in my opinion!

1. I do **not** work with virtual desktops as described in #4863 _at all_ – all apps are running on the same desktop.
2. KeePassXC does **not** perform Auto-Type immediately as described in #4863.
3. The bug I described is related to the focus of the windows and dialogs of KeePassXC **itself** - it’s not about inserting credentials inside wrong windows/apps of the same name as described in #4863.

My second thought was maybe it’s because I use two monitors and occasionally one app is open on the other. But that was not the reason, the »bug« still occurs even when KeePassXC is running on the same monitor as the app.

**Comment by droidmonkey** [comment]
Would appreciate a screen recording of your problem

**Comment by MrDoodlezz** [comment]
> Would appreciate a screen recording of your problem

Will do asap, thanks for reconsidering it!

**Comment by MrDoodlezz** [comment]
Sorry for the delay in my feedback.

Today after further investigating I realised that the bug actually occurs when the database is **already unlocked**!
For example, if a second Auto-Type process is started _directly_ afterwards (or within the defined time until the next automatic lock) and the database is still open from the previous process.

## Updated Steps to Reproduce:

**1. Have the database already unlocked.** See example above why this might be the case.
2. Navigate to any given login area.
3. Trigger Auto-Type.
4. Try navigating the entries in the dialogue.
5. Try to confirm the selected entry with Enter/Return.

See my example clip [here](https://www.swisstransfer.com/d/396e27f4-0cbb-4a5d-9eae-ad93ab281cd8).

I thought maybe I could check the option "Re-lock previously locked database after performing Auto-Type", but the option doesn't seem to work either. In any case, even with the checkmark set, the database remains open for a certain time after Auto-Type instead of locking itself again. Or I simply misunderstand the option. :D

Thanks again and have a nice weekend

**Comment by droidmonkey** [comment]
The database will remain unlocked for the interval set by the "retype timeframe" setting which is just below it. That defaults to 15 seconds. This allows you to use the Auto-Type feature multiple times in a row without having to unlock your database every single time. 

As for the up/down arrows not working. Looks like your system is not giving keyboard focus to the Auto-Type pop-up window.

**Comment by MrDoodlezz** [comment]
Hey Jonathan,

ah, all right! I have now set the time for "Remember last typed entry for:" to 0 seconds – now everything works as expected or similar to how it worked before the latest release.
After each new unlocking of the database, I can now switch between the different accounts with the arrow keys in the new pop-up.
Afterwards, the database locks again immediately and I can continue with the next account/website/etc.

This **workaround** works for me for now – thanks for the tip.

It is up to you to decide whether this is still considered a bug and KeePassXC can focus the system on the new pop-up, or if you want to close it. 🤷‍♂️

**Comment by libcrypt0** [comment]
I'm experiencing this issue but I can't use the workaround, as I like to keep my database open for a long time. Unfortunately, the "move focus to the next window" (bound to command-escape for me) keyboard shortcut does not permit the auto-type window to become focused, when it should.

**Comment by MmAtBosch** [comment]
Same here, my database is always unlocked. running on monterey with keepassxc 2.7.1. i never get my focus on the auto-type window and can´t choose the correct entry via keyboard, which is very annoying.

Some versions before this always worked fine.

**Comment by libcrypt0** [comment]
For the moment, I'm using Keyboard Maestro to focus the required window with a shortcut, which necessitates permanently keeping KeePassXC in screen-recordable mode, which is obviously less desirable.  I would love to hear of a better solution.

**Comment by computoms** [comment]
If that can be of any help, it seems the issue on my machine comes from the type of field focused on in Safari when doing the auto-type shortcut. If the field is a "normal" textbox field, the focus of Keepass Auto-Type window is correctly set. But, if the field is a password field, it seems to prevent the focus to be released from the password field. 

You can see a demo here:

https://user-images.githubusercontent.com/40306976/169922257-8c047a4a-6e81-4485-8505-ded20bbb666e.mov

I am running macOS 12.3.1 with Safari 15.4.
I have the same behaviour with Firefox 100.0.1

**Comment by computoms** [comment]
Not sure it is related, but I do not know where to add this information elsewere: [this line](https://github.com/keepassxreboot/keepassxc/blob/a4d4adb1f61baf2bc447b4d5411497a3ef52aaaa/src/gui/Application.cpp#L215) generates an quasi-infinite event-loop: it calls `MainWindow::bringToFront()` which in turn calls `activateWindow()` which calls the `QEvent::ApplicationActivate` and so on. I do not think the line mentioned is necessary anymore (the application is brought to front anyway when clicking on the dock icon even without the line).

**Comment by droidmonkey** [comment]
Good find, that code in Application is 5 to 7 years old and most likely overcome by current methods.

**Comment by droidmonkey** [comment]
This doesn't appear to be caused by us, this seems to be a security (?) feature on macOS that prevents windows from stealing focus from password fields. There is nothing we can do about this as I tried a couple workarounds.

**Comment by MrDoodlezz** [comment]
> Hey Jonathan,
> 
> 
> 
> ah, all right! I have now set the time for "Remember last typed entry for:" to 0 seconds – now everything works as expected or similar to how it worked before the latest release.
> 
> After each new unlocking of the database, I can now switch between the different accounts with the arrow keys in the new pop-up.
> 
> Afterwards, the database locks again immediately and I can continue with the next account/website/etc.
> 
> 
> 
> This **workaround** works for me for now – thanks for the tip.
> 
> 
> 
> It is up to you to decide whether this is still considered a bug and KeePassXC can focus the system on the new pop-up, or if you want to close it. 🤷‍♂️

Thanks for the update! Even if it's not what we all probably hoped for.

In the meantime, I can manage well with the workaround I posted three months ago.

**Comment by konrad-sabre** [comment]
> ah, all right! I have now set the time for "Remember last typed entry for:" to 0 seconds – now everything works as expected or similar to how it worked before the latest release. 

This workaround works for me as well. Thank you for sharing.
I think it also means the issue is "fixable".

**Comment by konrad-sabre** [comment]
@droidmonkey - could you comment on why setting "Remember last typed entry for" to 0 seconds eliminates this issue?
And since it does - was closing it the right step?

**Comment by libcrypt0** [comment]
Just to amplify this situation a little, I have found that setting "remember last typed entry" to 0 seconds appears to help the problem on macOS 12, but it does not fix it on macOS 10.15.

**Comment by MrDoodlezz** [comment]
> Just to amplify this situation a little, I have found that setting "remember last typed entry" to 0 seconds appears to help the problem on macOS 12, but it does not fix it on macOS 10.15.

For me (OP) it certainly does!

**Comment by jgosmann** [comment]
I have the same issue and setting "remember last type entry" to 0 seconds does not solve the problem for me (macOS 13.6).

I think in theory it should fixable because it works fine with [MacPass](https://macpassapp.org/) which I'll probably be using instead.
