### ISSUE TITLE
Master password is not hidden when clicking unlock button (Regression)

### ISSUE THREAD

**Issue by coltrane42** [keepassxreboot/keepassxc#7724]
## Overview
Up until version 2.6.6, KeePassXC made sure that, in the database unlock window, if the master password visibility was toggled on, it would be toggled off when clicking the unlock button.

## Steps to Reproduce
1. Open a KeePassXC database
2. Type a password
3. Toggle password visibility ON
4. Click unlock button

## Expected Behavior
The password visibility should be toggled off during the unlocking procedure (and after, in case the unlocking fails).

## Actual Behavior
The password is still visible during the unresponsive period of database unlocking (and after, if the unlocking fails).

## Context
The rationale behind this is that during the unlocking procedure the window becomes unresponsive, potentially for a very long time (e.g. opening the database on a less powerful PC, or just wanting a long derivation time) during which the password could be shoulder-surfed.

KeePassXC - Version 2.7.0
Revision: d7a9ef4
Distribution: AppImage

Operative system: Linux Mint 20.3
CPU Architecture: x86_64
Kernel: linux 5.4.0-105-generic

**Comment by phoerious** [comment]
Interesting. This should definitely not happen.
