### ISSUE TITLE
Refocus database unlock dialog when unlock is requested and the dialog was already opened

### ISSUE THREAD

**Issue by jmetrius** [keepassxreboot/keepassxc#7727]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
Since 4f0710350fb53c25db6824f96961d8d17a29347c, the database unlock dialog is no longer always on top of other windows. While I believe that this is a reasonable change, there seems to be currently no logic in place to refocus this dialog when appropriate. An example for this is requesting database unlock from the browser with a password prompt as outlined below. The same issue occurs of the "Reopen database" button from the extension menu is used.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Open KeePassXC without unlocking your database
2. Open browser with the KeePassXC extension and navigate to a website with a password prompt
3. Click the grey KeePassXC icon that appears in the prompt to open a database unlock dialog
4. Ignore the dialog and switch back to your browser
5. Click the grey unlock button in the password prompt again

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
The KeePassXC window with the database unlock dialog should come back to the foreground

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Nothing happens. The database unlock dialog stays in the background.

## Context
[NOTE]: # ( Give us any additional information you may have. )
Arch Linux with GNOME 41, Wayland Session

[NOTE]: # ( Paste debug info from Help → About here )

KeePassXC - Version 2.7.0
Revision: d7a9ef4

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: Gnome
Windowing System: Wayland

**Comment by phoerious** [comment]
@droidmonkey I believe this is a result of the changes you made for Windows Hello.

**Comment by droidmonkey** [comment]
Yes that is correct

**Comment by droidmonkey** [comment]
I cannot replicate this on Windows nor Gnome.
