### ISSUE TITLE
Deleted

### ISSUE THREAD

**Issue by hj-collab** [keepassxreboot/keepassxc#7729]
Deleted.

**Comment by hj-collab** [comment]
@phoerious @droidmonkey Have this been completed? I noticed that you have replied here that all files are signed. https://github.com/keepassxreboot/keepassxc/issues/7953

If so then please mark this as completed.

**Comment by droidmonkey** [comment]
It was done for 2.7.1, and all subsequent releases. Only the msvc based releases will have signed dlls from third parties.
