### ISSUE TITLE
Compile keepassxc 2.7.0 from source on manjaro "unzip.h not found"

### ISSUE THREAD

**Issue by Staubgeborener** [keepassxreboot/keepassxc#7730]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. following [Set up Build Environment on Linux](https://github.com/keepassxreboot/keepassxc/wiki/Set-up-Build-Environment-on-Linux) and [Building KeePassXC](https://github.com/keepassxreboot/keepassxc/wiki/Building-KeePassXC#linux) like this:
2. `wget https://github.com/keepassxreboot/keepassxc/releases/download/2.7.0/keepassxc-2.7.0-src.tar.xz`
3. `tar xf keepassxc-2.7.0-src.tar.xz`
4. `mkdir build`
5. `cd build`
6. `cmake -DWITH_XC_ALL=ON -DCMAKE_BUILD_TYPE=Release ..`
7. run `make -j8` and see 

> [ 20%] Building CXX object src/cli/CMakeFiles/cli.dir/Clip.cpp.o
> /home/user/keepassxc/keepassxc-2.7.0/src/keeshare/ShareImport.cpp:24:10: schwerwiegender Fehler: unzip.h: Datei oder Verzeichnis nicht gefunden
>    24 | #include <unzip.h>
>       |          ^~~~~~~~~

8. after that run `make DESTDIR=~/.local install` and see

> [  9%] Building CXX object src/keeshare/CMakeFiles/keeshare.dir/ShareImport.cpp.o
> /home/user/keepassxc/keepassxc-2.7.0/src/keeshare/ShareImport.cpp:24:10: schwerwiegender Fehler: unzip.h: Datei oder Verzeichnis nicht gefunden
>    24 | #include <unzip.h>
>       |          ^~~~~~~~~
> Kompilierung beendet.
> make[2]: *** [src/keeshare/CMakeFiles/keeshare.dir/build.make:202: src/keeshare/CMakeFiles/keeshare.dir/ShareImport.cpp.o] Fehler 1
> make[1]: *** [CMakeFiles/Makefile2:1251: src/keeshare/CMakeFiles/keeshare.dir/all] Fehler 2
> make: *** [Makefile:146: all] Fehler 2

btw `schwerwiegender Fehler: unzip.h: Datei oder Verzeichnis nicht gefunden` means `fatal error: unzip.h: file or directory not found`

## Expected Behavior
compile keepassxc form source on linux manjaro without fatal error messages.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
see "Steps to Reproduce"

## Context
[NOTE]: # ( Give us any additional information you may have. )
System: `Linux version 5.9.16-1-MANJARO (builduser@LEGION) (gcc (GCC) 10.2.0, GNU ld (GNU Binutils) 2.35.1) #1 SMP PREEMPT Mon Dec 21 22:00:46 UTC 2020`

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.0

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux manjaro

**Comment by phoerious** [comment]
You need to install all required dependencies. You are missing minizip apparently.

**Comment by Staubgeborener** [comment]
> You need to install all required dependencies. You are missing minizip apparently.

i installed minizip like `sudo pacman -S minizip` and/or 
```
git clone https://aur.archlinux.org/minizip-git.git
cd minizip-git
makepkg
```
No error with tho two installations. But the error message is still the same.

i noticed that i already installed minizip like this
`sudo pacman -S qt5-base qt5-tools argon2 botan qrencode zlib asciidoctor readline \
    pcsclite libusb libxi libxtst qt5-x11extras minizip`

**Comment by phoerious** [comment]
@droidmonkey I wonder if the include shouldn't rather be `minizip/unzip.h`.

**Comment by Staubgeborener** [comment]
> @droidmonkey I wonder if the include shouldn't rather be `minizip/unzip.h`.

I can confirm this. `ShareImport.cpp` and `ShareExport.cpp` need `minizip/unzip.h` instead `unzip.h`. After changing those lines, I can run it without issues.

**Comment by droidmonkey** [comment]
CMake attempts to find the minizip header and adds the containing folder to the include directories.

**Comment by phoerious** [comment]
I think this is somewhat of a bug, though. The correct include should be `minizip/unzip.h` and if installed to the correct location, it wouldn't need extra include path magic.

**Comment by tenzap** [comment]
A maybe related issue is also reported here

https://trac.macports.org/ticket/64921

**Comment by droidmonkey** [comment]
This was fixed a while ago
