### ISSUE TITLE
no success with the installation of the appropriate runtime library (x64) from here: https://docs.microsoft.com/en-US/cpp/windows/latest-supported-vc-redist?view=msvc-170#visual-studio-2015-2017-2019-and-2022

### ISSUE THREAD

**Issue by PADIXO** [keepassxreboot/keepassxc#7732]
I am now signed in to Microsoft with a new account on https://my.visualstudio.com/, have booked a "Developer Plan" in the "Visual Studio Subscriptions" for the "Power Apps", set up a "free account" in the appcenter.ms. Nevertheless, I only get an error message under the link from https://aka.ms/vs/17/release/vc_redist.x64.exe. I'm not a power programmer and just wanted to use the KeePass app. Am I even right here, or is this not the help forum? In the app you will be referred here (?!?)

_Originally posted by @phoerious in https://github.com/keepassxreboot/keepassxc/issues/7564#issuecomment-1074842970_

**Comment by phoerious** [comment]
You don't need an account, you only need to download the file and install it.
