### ISSUE TITLE
"#" hash character and following are ignored in Auto-Type

### ISSUE THREAD

**Issue by abourree** [keepassxreboot/keepassxc#7733]
## Overview
Hash character and following characters are ignored in Auto-Type sequence

## Steps to Reproduce
1. I edit one entry with JDOE as user name and select 'Auto-Type'
2. I crete a new association for window '* - Notepad' with the specific sequence '{USERNAME}#{USERNAME}'
3. I open Notepad and press my Auto-Type shortcut

## Expected Behavior
I expect to have in Notepad windows:
JDOE#JDOE

## Actual Behavior
I have:
JDOE

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.0
Revision: d7a9ef4

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 10

**Comment by abourree** [comment]
I forget to explain workaround I found:
1. create attibute 'sharp' with value '#'
2. use sequence '{USERNAME}{S:sharp}{USERNAME}'

**Comment by droidmonkey** [comment]
You need to wrap that in braces `{#}`

**Comment by abourree** [comment]
Wrap in braces doesn't work with KeePassXC version 2.7.0
KeePassXC complains that # variable doesn't exist
