### ISSUE TITLE
2.7.0 AppImage can´t open or even show files with Umlaut in Open Dialog

### ISSUE THREAD

**Issue by Jackfritt** [keepassxreboot/keepassxc#7734]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
See above..

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. touch test.kdbx täst.kdbx
2. KeePassXC-2.7.0-x86_64.AppImage
3. Open existing Database and try to find the file täst.kdbx 

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
files with umlauts should be visible and usable... 2.6.x did it...

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
files with umlaut are not visible or usable..

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.0
Revision: d7a9ef4
Distribution: AppImage

Qt 5.15.2
Debugging mode is disabled.

Operating system: Debian GNU/Linux 11 (bullseye)
CPU architecture: x86_64
Kernel: linux 5.16.0-0.bpo.4-amd64

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.12.1

[NOTE]: # ( Pick choices based on your environment )
Operating System: Debian Bullseye
Desktop Env: KDE Plasma
Windowing System: X11

**Comment by Jackfritt** [comment]
2.7.4 AppImage bug still there. When compiled from git there is no problem... Maybe AppImage Problem?

**Comment by droidmonkey** [comment]
It is an appimage problem,  this is actually a duplicate
