### ISSUE TITLE
Windows Secutity window after user+password

### ISSUE THREAD

**Issue by thyxNY** [keepassxreboot/keepassxc#7737]
## Overview
Fresh install KeePassXC. After choosing keepass database and entering user+password I see a screen with windows security. But I can click X to close this popup and the database opens correctly.

![obraz](https://user-images.githubusercontent.com/73193311/160920093-fb7c4dc6-461c-4da3-91c1-5c90f81ebd6a.png)

## Steps to Reproduce
1. Chose database, enter user + password, click OK 
2. Screen apears
3. I can clink X (upper right corner) to close this popup

## Expected Behavior
Can I turn off this window?

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.9
Revision: d7a9ef4
Operating System: Windows 10 Home 21H2

**Comment by droidmonkey** [comment]
https://keepassxc.org/docs/KeePassXC_UserGuide.html#_quick_unlock

**Comment by thyxNY** [comment]
@droidmonkey Thanks for the info!
