### ISSUE TITLE
{#} doesn't allow to use hash in Auto-Type sequence

### ISSUE THREAD

**Issue by abourree** [keepassxreboot/keepassxc#7743]
## Overview
Workaround proposed in #7733 doesn't work

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. I edit one entry with JDOE as user name and select 'Auto-Type' 
2. I crete a new association for window '* - Notepad' with the specific sequence '{USERNAME}{#}{USERNAME}'
3. I open Notepad and press my Auto-Type shortcut

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
JDOE#JDOE

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
At step 2, when saving entry, KeepassXC complains that variable doesn't exist
When forcing save with {#}, step failed with same complain

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.0
Revision: d7a9ef4

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 10

**Comment by droidmonkey** [comment]
Whoops need to add it to this list https://github.com/keepassxreboot/keepassxc/blob/develop/src/autotype/AutoType.cpp#L87
