### ISSUE TITLE
2.7.0 breaks 'Perform Auto-Type' keyboard shortcut on mac arm64

### ISSUE THREAD

**Issue by xxyxxyxyx1** [keepassxreboot/keepassxc#7744]
## Overview
On macOS, 'Perform Auto-Type' can be triggered with the shortcut cmd-shift-v. This has worked on many versions up to and including 2.6.6. Now on version 2.7.0, this shortcut does not work anymore. 

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Select an entry
2. Type cmd-shift-v

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Auto-Type happens

## Actual Behavior
The keepassxc window is hidden, and the previous window is focused, as expected. But then nothing is typed. 

## Context
I can still use the mouse to perform autotype by doing:
right click > Perform Auto-Type > top entry
It is only the keyboard shortcut that is broken. 

After finding this problem, I re-installed version 2.6.6 in `~/Applications` and kept version 2.7.0 in `/Applications`. If I open the 2.6.6 app, the shortcut works, but if I open 2.7.0, it does not work. 

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.0
Revision: d7a9ef4

Qt 5.15.2
Debugging mode is disabled.

Operating system: macOS 12.3
CPU architecture: arm64
Kernel: darwin 21.4.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 2.19.1

**Comment by droidmonkey** [comment]
Known issue fixed for 2.7.1

**Comment by TxX8N8LN** [comment]
@xxyxxyxyx1 , for me i need to go in configure global of Auto-Type and disable "Always ask before performing Auto-Type"
And now it's work like before

**Comment by xxyxxyxyx1** [comment]
@TxX8N8LN, Thank you for the suggestion. Sadly, I have already unchecked this option. 

@droidmonke, Thank you for the update. I hope I didn't miss an existing issue when I searched before posting.
