### ISSUE TITLE
Attachment not changed

### ISSUE THREAD

**Issue by Benutzername** [keepassxreboot/keepassxc#7745]
Changing existing attachments does not work correctly. The already saved file remains unchanged.

**Comment by droidmonkey** [comment]
You will need to provide more information and give us your version number and all that as well

**Comment by Benutzername** [comment]
solved in

KeePassXC - Version 2.7.0
Revision: d7a9ef4

Qt 5.15.2
Diagnosemodus ist deaktiviert.

Betriebssystem: Ubuntu 21.10
CPU-Architektur: x86_64
Kernel: linux 5.13.0-39-generic

Aktivierte Erweiterungen:
- Auto-Type
- Browser-Integration
- SSH-Agent
- KeeShare
- YubiKey
- Secret-Service-Integration

Kryptographische Bibliotheken:
- Botan 2.17.3
