### ISSUE TITLE
Tag "Weak Password" for Ref User/Password

### ISSUE THREAD

**Issue by thyxNY** [keepassxreboot/keepassxc#7746]
## Overview
All saved password with Ref (in username /in password) is signed with "Weak Password" tag.

KeePassXC - Version 2.7.0
Revision: d7a9ef4
Operating System: Windows 10

**Comment by thyxNY** [comment]
I think that all my user/password with REF after changing KeePassXC from 2.6.6 to 2.7.0 is broken :-(
I made a new REF and is different from my old REF :-(

**Comment by droidmonkey** [comment]
Can you give an example of the old vs new ref? There is no personal data in a reference. We didn't change anything in regards to entry references for 2.7.0.

**Comment by thyxNY** [comment]
Old ref:
{REF:U@I:06265B35FB5644F3B9EA8A605F911327}
{REF:P@I:06265B35FB5644F3B9EA8A605F911327}

New Ref (created now in 2.7.0):
{REF:U@I:BC532256E87D41719ACCC1B04D6B4C4A}
{REF:P@I:BC532256E87D41719ACCC1B04D6B4C4A}

**Comment by thyxNY** [comment]
I installed version 2.6.6, restored a copy of the kdbx file from a month ago and .... I have a damaged REF there too. All my REF are broken. I don't know when it happened, I probably did something wrong, but I don't know when and how. It's probably my mistake.

Please close this issue.

**Comment by droidmonkey** [comment]
You probably deleted the referenced entry
