### ISSUE TITLE
[Feature] New UI/Theme

### ISSUE THREAD

**Issue by MafooHamhead** [keepassxreboot/keepassxc#775]
A new UI or theme for this application would just be wonderful. I obviously know it is more than likely not high on the priority list whatsoever, but... sadly a non-modern UI is what drives me away. Someone posted a UI/theme that looked amazing for KeePass' style applications on a forum. Sadly I cannot find the post, as I would give credit where it is due. It is also the same forum post I found out about KeeWeb.

![dvqwh6v](https://user-images.githubusercontent.com/20230889/28244729-d6b2692c-69c0-11e7-882d-851dcc2a02e1.png)

I've been using KeePass 2 for awhile now, but tried switching to LastPass/Dashlane. Too many issues with both of those that I found. I even tried KeeWeb, but the UI just doesn't settle well with me. 

The current UI/theme feels outdated still (no offense, the work you do is still great!). Customization is a huge part of KeePass' ecosystem with plugins. 

Hopefully you consider this type of idea. 👍

**Comment by phoerious** [comment]
The theme looks nice. But (almost) native platform integration has always been one of KeePassX(C)'s core features. There are lots of areas where we can improve things, but overall, the looks are not necessarily "dated". They are rather what applications on that platform look like. I understand that in times of web and mobile applications and Material design, people are getting used to different looks. But KeePassXC is a pure desktop application and should therefore integrate into the user's desktop. An application like the mockup above doesn't integrate into any platform.

**Comment by MafooHamhead** [comment]
Yea, I realize after creating this I should of addressed more so about the native platform integration. Obviously this limits the amount of code you have to write and doesn't over-complicate things. Which is great, don't get me wrong!

It definitely is about modern day use of web/mobile apps including Material style design and the like. I don't think KeePassXC looks 'dated' necessarily, so I sort of retract that statement. I think maybe it's more of the icons. They're a lot more Windows 7/Windows XP style in my opinion. I actually prefer KeePass 2's icons more so because they're smaller and 'flows' better I suppose.

The feature more or less that I would be requesting is a way to 'choose' if it could look like that, if possible. I'm not saying you're wrong or anything here, but your statement "_they are rather what applications on that platform look like_" can't really be the case for something like Windows 8/8.1/10. Nothing about the application says 'this is a Windows application to me' except if I was running Windows 7 or XP.

Again, I appreciate the work you guys put into this to provide more support for Linux/Mac/Windows compatibility. I'm just at a tug-of-war between functionality and aesthetics.

**Comment by phoerious** [comment]
Concerning the icon theme, there is already a discussion here: #756

**Comment by gagarine** [comment]
This one shouldn't be closed has a "wontfix"? I 100% agree their is multiple issue with the UX (icon, not  field not perfectly aligned or to long/short)  but it's not about a theme.

Say that, Qt application can have theme, but I think focusing on good default is better than giving the ability to change theme like in calibre.

**Comment by phoerious** [comment]
Can you post a screen shot where things are not perfectly aligned? We paid very close attention to that.

**Comment by gagarine** [comment]
Ok "perfectly aligned" is not the biggest problem I think (but still there is a problem with the alignment). What I mean is the alignment/grid is not visually pleasing ;). 

I quickly did some screenshot as an example. But I can take a bit longer to try to spot them all when I got some spare time. Also, sometimes can be aligned on pixels... but when you look at it, it doesn't feel aligned. This is what append with the login screen on the right.

![screen shot 2017-08-15 at 22 03 14](https://user-images.githubusercontent.com/164074/29333951-f2704d66-8205-11e7-9af2-2d441962580f.png)

![screen shot 2017-08-15 at 22 02 38](https://user-images.githubusercontent.com/164074/29334167-c4af2f9a-8206-11e7-899c-5b889ac1cff0.png)

![screen shot 2017-08-15 at 22 03 26](https://user-images.githubusercontent.com/164074/29334124-a5179f5a-8206-11e7-870d-dadfee158e90.png)

![screen shot 2017-08-15 at 22 02 05](https://user-images.githubusercontent.com/164074/29334363-6f795630-8207-11e7-8420-31511ecefa70.png)

**Comment by phoerious** [comment]
That is a Qt macOS bug (see https://bugreports.qt.io/browse/QTBUG-42457). We tried to mitigate it as much as possible, but we can't get it perfectly right without either screwing the layout completely on all other platforms or adding a stupid amount of custom code only for macOS.

**Comment by gagarine** [comment]
I understand. I think also than changing icon will make the app look way more modern than trying to fix minor misalignment on OSX... specially with hacks.

**Comment by phoerious** [comment]
We can try to optimize alignments a little further, but there isn't much room for improvement without an upstream fix. KeePassXC already looks a lot better on macOS than KeePassX did, but it's still a little rough around the edges compared to other platforms.

**Comment by droidmonkey** [comment]
Most of this has been implemented in 2.3.0, closing in favor of a more specific suggestion in the future.
