### ISSUE TITLE
Autotype broken with keyboard switching on linux

### ISSUE THREAD

**Issue by d-faure** [keepassxreboot/keepassxc#7754]
## Overview
On a host with an heterogeneous keyboard configuration (laptop with fr layout and usb keyboard with us layout), the Auto-Type feature doesn't seem to follow the desktop language switching.

## Steps to Reproduce
1. Make sure the selected keyboard layout the default one (the upper in the layout list, fr in this case) and perform an Auto-Type sequence in a neutral text editor.
2. Switch the keyboard layout (us) and perform the same Auto-Type sequence.

## Expected Behavior
Auto-Typed text shouldn't be altered by the active keyboard layout. The typed text should reflect the entry text.

## Actual Behavior
The Auto-Typed text translation to keystrokes doesn't take in account the keyboard layout change.

## Context
KeePassXC - Version 2.6.6
Revision: 9c108b9

Qt 5.15.2
Debugging mode is disabled.
Operating system: Debian GNU/Linux bookworm/sid
CPU architecture: x86_64
Kernel: linux 5.16.0-6-amd64

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- libgcrypt 1.9.4

**Comment by droidmonkey** [comment]
Upgrade to 2.7.0, it has been fixed. Be aware there is a bug for entry level Auto-Type that is fixed in upcoming 2.7.1
