### ISSUE TITLE
Window doesn't display

### ISSUE THREAD

**Issue by daveschroeter** [keepassxreboot/keepassxc#7756]
I'm on Windows 10 and 2.7.0 (also portable) launches but doesn't display the window (captures mouse and has a resizable 'ghost' window). Tried various DPI / compatibility options to no avail. 2.6.6 and all previous run fine. Nvidia GPU if that matters. Help!

**Comment by phoerious** [comment]
https://keepassxc.org/docs/KeePassXC_UserGuide.html#_screenshot_security
