### ISSUE TITLE
Perform Auto-Type

### ISSUE THREAD

**Issue by xortrike** [keepassxreboot/keepassxc#7757]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
Perform Auto-Type function is not work in 2.7.0

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Open web site or text edit.
2. Open KeePassXC (Alt + Tab).
3. Selecting record.
4. Enter Ctrl + Shift + V

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Login and password should be automatically entered.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
It switches to the last program and nothing else.

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.0
Revision: d7a9ef4

[NOTE]: # ( Pick choices based on your environment )
Operating system: Ubuntu 18.04.5 LTS
CPU architecture: x86_64
Kernel: linux 4.15.0-1096-oem

**Comment by droidmonkey** [comment]
It's a bug fixed in 2.7.1
