### ISSUE TITLE
Database Tags

### ISSUE THREAD

**Issue by xortrike** [keepassxreboot/keepassxc#7758]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
In KeePassXC 2.7.0, a block was added - Database Tags. This block is under the block with groups on the main page.

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )
![2022-04-01_14-41](https://user-images.githubusercontent.com/44906253/161256722-4fa05a40-da37-4a54-8ab5-0639a7a8539c.png)

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
I don't like this block and can't disable it.
Could you please add a configuration for disabling/hiding this block?

**Comment by droidmonkey** [comment]
Drag the splitter down to the bottom of the group view. It will be gone.
