### ISSUE TITLE
selectable backup path

### ISSUE THREAD

**Issue by Fr33man85** [keepassxreboot/keepassxc#7763]
Hi,

maybe it is a good idea to have a setting, in which we can define a "backup path".

We already have the option to create a backup Database in front of saving, but this is not realy helpfull, if the database is in same location (eg. USB-drive, whats getting lost or broken)
i would wish to have the ability to set a dedicated backup-path, maybe on a network drive, directly into a cloud storage or somewhere else.

what do you think? or is there maybe already such a plugin or setting?

greetings
Manuel

**Comment by droidmonkey** [comment]
Feature available in 2.7.0
