### ISSUE TITLE
Password not hidden when unlocking database

### ISSUE THREAD

**Issue by dqnk** [keepassxreboot/keepassxc#7765]
### When using the feature to preview password when unlocking the database, password is not hidden after clicking unlock button.
Being able to see the password while the database is unlocking is dangerous because someone could look over your shoulder and steal it. There is no need to show it while the database is unlocking (assuming you are using a long 5 second unlocking).

![image](https://user-images.githubusercontent.com/64268180/161374306-2bab9f2f-fdf1-487c-81d1-e17f4b01a396.png)
Note: aaaaaaaaaaaaaaaa is not my real password.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Enter password.
2. Click the button to reveal password.
3. Click unlock

## Expected Behavior
Password should hide when hitting the Unlock button.

## Actual Behavior
Password does not hide.

## Debug info
KeePassXC - Version 2.7.0
Revision: d7a9ef4

Qt 5.15.3
Debugging mode is disabled.

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 5.17.1-zen1-1-zen

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.19.1

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: Gnome
Windowing System: X11

**Comment by phoerious** [comment]
This is already fixed and will be part of the next release.
