### ISSUE TITLE
KeePassXC 2.7.0 fails to start on Win7 x64 due to missing DLL

### ISSUE THREAD

**Issue by gene-pavlovsky** [keepassxreboot/keepassxc#7768]
## Overview
Windows 7 x64, build 7601.
After updating KeePassXC to version 2.7.0, doesn't run, a dialog appears about a missing api-ms-win-core-kernel32-legacy-ansi-l1-1-0.dll.
After uninstalling and installing version 2.6.6 again, it works.

![2022-04-02 17_02_04-KeePassXC exe - System Error](https://user-images.githubusercontent.com/2841193/161389423-28174a54-b3b1-4c0c-b6a1-4669037c38b4.png)

**Comment by droidmonkey** [comment]
Download the legacy windows installer

**Comment by gene-pavlovsky** [comment]
Thanks, that worked. I could only found a link to that legacy installer on the GitHub releases page. There is no mention of it on https://keepassxc.org/download/
Perhaps would be nice to add it there, with a note on when the legacy installer is needed?

**Comment by leftdisconnected** [comment]
From what I can see, the KeePassXC home and documentation refers to Windows only as "Windows".  I apologize if I have missed it, but I did not see system requirements as I was checking release notes or downloading.  The downloads page should tell users what the minimum requirements are to avoid people making bug reports, wasting both your time and theirs.

It does warn that Win32 is not supported, so perhaps this should be modified to state that neither Win32 nor older versions of Win64 are supported.  I appreciate the team for continuing to build and support older Win64 releases, however.

Thanks to everyone involved with this project for their hard work; my feedback is meant to be constructive.

**Comment by phoerious** [comment]
Windows means "any supported version of Windows", i.e. Windows 10 and 11. Windows 8.1, 8, and 7 have been EOL for a while.

**Comment by michaelk83** [comment]
> Windows means "any supported version of Windows", i.e. Windows 10 and 11. Windows 8.1, 8, and 7 have been EOL for a while.

This doesn't seem to be obvious to most users, though. So I agree that this should be stated on the download page, and a link to the legacy build should also be included there while one is still available.

**Comment by leftdisconnected** [comment]
Thanks so much!  The downloads page indeed now displays relevant version information for Windows users.  While I understand the assumption that "Windows" means "supported" versions, it is actually quite common for software to work on most older, unsupported versions of Windows so I do think it appropriate to be specific.

All the best,

**Comment by S474N** [comment]
So downloaded:
https://github.com/keepassxreboot/keepassxc/releases/download/2.7.1/KeePassXC-2.7.1-Win64-LegacyWindows.zip

Unpacked and have this problem:
![image](https://user-images.githubusercontent.com/16512337/162685628-f74a62e9-b416-4378-a8f0-bed7a1e1b9ac.png)

**Comment by gene-pavlovsky** [comment]
Better open a new ticket (would make sense to mention this one in the new one)

**Comment by S474N** [comment]
Resolved with new fresh unpacked version with my config.
