### ISSUE TITLE
Print exported html - problem with Notes field

### ISSUE THREAD

**Issue by thyxNY** [keepassxreboot/keepassxc#7769]
After exporting HTML entries and printing everything is fine except "Notes". It does not fit on the printout and the sentences are truncated. Here is an example of a printed HTML:

![obraz](https://user-images.githubusercontent.com/73193311/161389890-ce91bd08-888e-4f3b-bdd6-a9ce63003787.png)

The suggestion is that the "Notes" field should be full-width something like that:

Notes:
XXXX xxxxx xxxxx xxxxx xxxxxx ....

eg.
![obraz](https://user-images.githubusercontent.com/73193311/161390270-2d3ee8aa-0498-4ccb-a681-c523545c7610.png)

When the "Notes" field is full width, everything will probably fit. 
Is it possible to add second HTML export with wider "Notes" field?

KeePassXC - 2.7.0
Operating System: Windows 10

**Comment by dmaslenko** [comment]
I was able to reproduce this issue on Linux Ubuntu 22.04.

### I created a test database with an entry:
![GivenLongTitleAndNotes](https://user-images.githubusercontent.com/121412908/212237582-495227c3-4261-4a7c-84a0-1c693eb2166e.png)

### Exported into the HTML page where he page got a horizontal scrolling:
![PageWidthIsMore1](https://user-images.githubusercontent.com/121412908/212237674-12a49d04-08f7-4b31-8b18-65b48e6f2284.png)

### The browser window size does not matter:
![PageWidthIsMore2](https://user-images.githubusercontent.com/121412908/212237743-662556ab-a6e0-4f77-832e-1ba55beb0ce6.png)

### The preview print page even has lost text:
![PrintingPageWidthIsMore](https://user-images.githubusercontent.com/121412908/212237815-9badb466-0e3f-42e4-bebb-1081cd5b194a.png)
