### ISSUE TITLE
AppImage LXDE Integration Problem

### ISSUE THREAD

**Issue by schnappijedi** [keepassxreboot/keepassxc#777]
AppImage unable to integrate on LXDE. Every time run AppImage given option to integrate but integration does not take place.

Is this likely an LXDE issue or something that could be corrected with the AppImage?

**Comment by phoerious** [comment]
I suppose you mean "integrate visually"?
That's an inherent AppImage problem and can't be solved. AppImages bundle all dependencies and therefore can't make use of your system's theme. If you want tighter integration, you should use a package that was built for your distribution specifically.

**Comment by schnappijedi** [comment]
Is there a way to remove the prompt for integration when opening an AppImage?

**Comment by phoerious** [comment]
Oh, you mean the prompt for adding an icon? There should be a checkbox to not show the dialog again.

**Comment by schnappijedi** [comment]
Not on LXDE. But this is an issue for the LXDE forum. Thanks.

**Comment by phoerious** [comment]
The dialog that is shown is platform-specific. So if it doesn't show that checkbox, it's indeed a platform issue.
