### ISSUE TITLE
AutoType not working in new Version

### ISSUE THREAD

**Issue by maxrdu** [keepassxreboot/keepassxc#7772]
## Overview
After updating to version 2.7.0 auto type for any entry does not work anymore.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1.  Update to version 2.7.0
2. Try to perform auto type
3. 
## Actual Behavior
When pressing Ctrl+Shift+V the window switches, however no characters are inserted.

## Context
[NOTE]: # ( Give us any additional information you may have. )
I'm using Ubuntu 20.04.4 with Gnome, entry title and url matching are turned off.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.0
Revision: d7a9ef4

Qt 5.12.8
Debugging mode is disabled.

Operating system: Ubuntu 20.04.4 LTS
CPU architecture: x86_64
Kernel: linux 5.13.0-39-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.12.1

**Comment by phoerious** [comment]
Known issue, will be fixed in 2.7.1. Use global Auto-Type in the meantime, much more powerful anyway.
