### ISSUE TITLE
Password window does not pop up in KDE

### ISSUE THREAD

**Issue by adkrz** [keepassxreboot/keepassxc#7773]
**Overview:**
When the KeePassXC (on Linux with KDE) is minimized and locked, then activated (by global AutoType hotkey or by browser extension), the password dialog does not show up in the front.

**Steps to reproduce:**
- start KeePassXC minimized to tray and locked
- Open Chrome or Firefox, browse to some login URL
- Press your configured global autotype combination or click the padlock icon from browser plugin

**Expected behavior:**
The password/keyfile entry dialog will pop up and be focused.

**Actual behavior:**
The dialog appears as a taskbar button, however no window is shown. One must click twice the taskbar button to minimize and restore the dialog.

**Workaround:**
Revert to version 2.6.6.

**System info:**
- Kubuntu 20.04.4 64-bit
- KDE Plasma 5.18.8
- KeePassXC 2.7.0 from official Ubuntu PPA

**Comment by michaelk83** [comment]
This might be a KDE Plasma or Qt bug, since I get the same behavior with some other dialogs. But there may be some system or Qt calls that KPXC can do to work around this.

(In my case, I'm seeing this when I try to close the Discover notifier from its tray icon menu. If I have some other window open, the close confirmation dialog will be hidden behind it.)

**Comment by hifi** [comment]
I confirmed this a while back but couldn't figure out what's the correct "fix" for this. Maybe we need to restore main window if it is minimized when the hotkey is pressed.

**Comment by droidmonkey** [comment]
#7771 fixes it

**Comment by hifi** [comment]
You sure about that? Auto-Type dialog already has that hint and it had the same behavior.

**Comment by droidmonkey** [comment]
Yes very sure,  that is the only change we made to the appearance of the unlock dialog
