### ISSUE TITLE
Default group when opening is Recycle Bin

### ISSUE THREAD

**Issue by valnar1** [keepassxreboot/keepassxc#7775]
## Overview
When opening KeePassXC 2.70, it defaults to the Recycle Bin.  I have to click on my preferred folder AND sort by name every time I open it.  This was not a problem with =< 2.66.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.70
Revision: d7a9ef4

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows

**Comment by droidmonkey** [comment]
The first time you open a database it opens to your top level (root) group. When you lock and unlock the database, it will open to the last focused group.

**Comment by valnar1** [comment]
It does not do that.  I used to yes, but not anymore.  Recycle Bin every time.
Updating/saving it in regular KeePass didn't fix it either.

**Comment by droidmonkey** [comment]
Uhhh did you delete your root group?

**Comment by valnar1** [comment]
I fixed it.  It showed expiring entries, not recycle bin.  That was new I guess? I turned it off. I will close this.  Thanks.
