### ISSUE TITLE
Include link to legacy windows installer on the downloads page

### ISSUE THREAD

**Issue by gene-pavlovsky** [keepassxreboot/keepassxc#7777]
Related to #7768

I think the download page for Windows should include a link to the legacy installer. The link to the regular installer should clearly state the Windows version requirement, with a mention to use the legacy installer otherwise. This way the user will be informed that the normal installer won't work for him, and will also learn about the existence of the legacy installer. At the moment this legacy installer is something one can only find out by looking at GitHub releases / getting a reply to a "it doesn't work for me" GitHub issue.

Additionally or alternatively, the regular (non-legacy) installer should check the Windows version and refuse to proceed with the installation, mentioning the need to download a legacy installer instead.

Appreciate your hard work :)

**Comment by droidmonkey** [comment]
done

**Comment by gene-pavlovsky** [comment]
Great, thank you!
