### ISSUE TITLE
Title bar remains in light mode in Windows 10 dark mode

### ISSUE THREAD

**Issue by segevfiner** [keepassxreboot/keepassxc#7782]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Set Windows 10 to dark mode.
2. Launch KeePassXC.
3. The UI switches to dark mode, but the title bar (AKA Window Decoration), remains in light mode.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Should switch the title bar (AKA Window Decoration) to dark mode. (Qt 5.15 at least might have support for this that isn't enabled by default, see [Context](#context) below),

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
The title bar (AKA Window Decoration) remains in light mode

## Context
[NOTE]: # ( Give us any additional information you may have. )
Qt 5.15, at least, might support it via a `darkmode=1` argument to the Windows platform plugin ([QGuiApplication - Platform-Specific Arguments](https://doc.qt.io/qt-5/qguiapplication.html#platform-specific-arguments)), you can launch KeePassXC with `-platform windows:darkmode=1` to enable it. But it would be nice to enable it by default. Perhaps via [qt.conf](https://doc.qt.io/qt-5/qt-conf.html#configuring-arguments-to-the-platform-plugins)? (It's probably not enabled by default since Qt Widgets doesn't come with a native dark mode style. It is something KeePassXC implemented)

I'm not sure whether Qt 6 has added native support for this or enabled this by default for Qt Widgets since Qt 5.15.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.0
Revision: d7a9ef4

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 10.0.19044.0 x64

**Comment by michaelk83** [comment]
#6775 , #5244
