### ISSUE TITLE
Implement copy/paste entries between containers

### ISSUE THREAD

**Issue by vitonsky** [keepassxreboot/keepassxc#7784]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
It's hard to manage 2 and more data base when i need to copy some entries from one DB to other, i have to:
- clone entry
- find cloned entry in master DB
- move this entry to other DB with press mouse and drag

And i have to do it for each entry. It's absolutely unusable for daily use. But this functional is very important to maintenance lightweight DB with lower security level.

We must simplify process of duplicating a entries between few DBs.

I suggest to implement copy/paste behavior with hotkeys for entries.
When i select one or few entries and press some hotkeys (ctrl+c for example) i will copy ENTRY and then i go to other tab with other DB, select folder and press some hotkeys (ctrl+v for example) and all entries from buffer should be insert there.

I will happy if you would implement this behavior as soon as possible.

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )

I have lightweight DB for smartphone and other devices which is not trusted and sometime i update this DB with entries from main DB. Now, the updating process is terrible for me. We must improve this for all people

**Comment by droidmonkey** [comment]
Already requested and you can do the following: click, drag, hold CTRL, drop into other database or group. A copy will be made instead of a move.

**Comment by vitonsky** [comment]
@droidmonkey give issue id with original feature request

**Comment by vitonsky** [comment]
@droidmonkey could you give me original issue number with feature request, to i subscribe on it?

**Comment by droidmonkey** [comment]
Easily searched with your summary terms. #172
