### ISSUE TITLE
TOTP : Show the code , put closer the abilities to see it, add TOTP to new entry

### ISSUE THREAD

**Issue by MembershipExcel** [keepassxreboot/keepassxc#7785]
## Summary
[NOTE]:
- Change TOTP icon to show TOTP (Which is on the far right and at 2/3 bottom screen) change it to the left OR inside "General tab" below password or as an added tab  with general, advance, auto-fill.

- And/or add a column to show TOTP. + add the possibility to copy the TOTP code with double click inside the column.

 NEW ENTRY : 
- Add the TOTP configuration in the new entry (below password)

- adding the TOTP code with Webcam (may require additional software, or maybe be redirecting to a website that could to this just to get the code)

## Context
[NOTE]: Keepass can serve as a good backup or manager for TOTP, there isn't a lot of software which show the QR code or the key available either on Desktop or mobile. Adding those feature could better serve this purpose

on bigger screen the TOTP icon is far from any entry, it also need 1-2 additional click

And adding the TOTP within the create new entry, reduce number of click and step to learn

## Type of change
- ✅ New feature (change that adds functionality)

**Comment by droidmonkey** [comment]
We already have multiple ways to get access to the generated TOTP Code:

![16490896787842107315692892489429.png](https://user-images.githubusercontent.com/2809491/161589628-0f75c1e6-9b61-484f-8b7a-7d24b2319e90.png)

There is also an open request to read TOTP info from a QR code. You can add TOTP to a new entry by clicking Entry -> TOTP -> Setup TOTP from the main menu. 

You can read more about how we implement TOTP here: https://keepassxc.org/docs/KeePassXC_UserGuide.html#_adding_totp_to_an_entry
