### ISSUE TITLE
AppImage cli broken in 2.7.0 ?

### ISSUE THREAD

**Issue by jorgheymans** [keepassxreboot/keepassxc#7788]
## Overview

Previously, i was able to make the AppImage echo a password entry on the commandline, now it fails with a yubikey error:
```
~> ~/Applications/KeePassXC.AppImage cli show -s -y 2 ~/tmp/test.kdbx test-pwd
Enter password to unlock /home/user/tmp/test.kdbx: 
YubiKey: Failed to establish PCSC context.
YubiKey: PCSC interface is disabled or not initialized.
Failed to issue challenge:  "General: Could not find interface for hardware key with serial number 0. Please connect it to continue."
Error while reading the database: Unable to calculate database key: General: Could not find interface for hardware key with serial number 0. Please connect it to continue.
```

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC 2.7.0
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: Gnome/KDE/XFCE/Mate/Cinnamon
Windowing System: X11

**Comment by droidmonkey** [comment]
This is known issue with yubikey and cli, fixed for 2.7.1
