### ISSUE TITLE
Wider Notes field

### ISSUE THREAD

**Issue by thyxNY** [keepassxreboot/keepassxc#7792]
When I edit a new entry all with the field "Notes" is fine:

![obraz](https://user-images.githubusercontent.com/73193311/161619436-457444ed-5e02-4a66-ab44-067a3ca0bdf2.png)

But on entry preview, I think that better move "Tags" one line up and then make "Notes" wider, like that: 

![obraz](https://user-images.githubusercontent.com/73193311/161620667-3ceebe14-7f6e-4cc0-a72b-92e233617b0b.png)

The right part is empty only because it is occupied by "Tags". I think that wider field "Notes" is better.

**Comment by phoerious** [comment]
The layout has already been updated to put the tags on a separate line for 2.7.1.

**Comment by thyxNY** [comment]
> The layout has already been updated to put the tags on a separate line for 2.7.1.

THX ;-) And then the "Notes" field will be wider?

**Comment by phoerious** [comment]
See #7767

**Comment by thyxNY** [comment]
> See #7767
YES YES YES ;-)

(can I make a screenshot from KeePassXC on Windows10? Is it possible? Any switch?)

**Comment by phoerious** [comment]
https://keepassxc.org/docs/KeePassXC_UserGuide.html#_screenshot_security

**Comment by thyxNY** [comment]
> https://keepassxc.org/docs/KeePassXC_UserGuide.html#_screenshot_security
THX!

Please close this issue and I will be waiting for 2.7.1 ;-)
