### ISSUE TITLE
Open File dialog does not appear on 2.7.0 installed from snap

### ISSUE THREAD

**Issue by hannes-ucsc** [keepassxreboot/keepassxc#7793]
Feel free to ignore and close this as evidence might be sparse.

To reproduce type Ctrl-O, or click Database - Open or click the Browse button (for key file) on the unlock dialog for an already open database. I would expect all of these actions to result in the display of a File Open dialog. In reality, nothing happens.

I *think* this started with 2.7.0 but am not sure.

I uninstalled the 2.7.0 snap and reinstalled via ppa and it started working again. The File Open dialog appears as expected.

**Comment by droidmonkey** [comment]
https://forum.snapcraft.io/t/file-chooser-doesnt-show-using-kde-neon-extension/29244/13
