### ISSUE TITLE
connection to browser under Linux broken -  a simple workaround (Ubuntu Studio 20.04 in this case)

### ISSUE THREAD

**Issue by succeedmr123** [keepassxreboot/keepassxc#7794]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

No link to DB, connection flaky and lost after FF updates.

Here I give you immediate solution via workaround at least for Database not connected  under Ubuntu Linux 20.04
It might be relevant  to KeepassXC itself and its proxy connector, hence the reason to add it here as a possible culprit of the detail when the conection is broken after e.g. FF update

SOLUTION: go to KeepassXC Tools/Settings, click Browser Integration and tick off "enable Browser Integration". Click OK. CLose, again go into menu Tools/... and this time Enable browser integration. You may notice that DB gets connected to FF, and frokm FF side it start functioning normally in this episode of investigation

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Update FF
2. Experience broken function of KeepassXC<->KeepassXC browser extension in many forms (no db connect, no forms suggested, etc)
3. Try the workaround suggested here on your system

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

Rock-solid, bulletproof function speeding up production environment effectivenes instead of getting stifled in technicalities

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

Broken function, taking days to find workaround via iterative fiddling with options and scenarions til sometimes a golden nugget as workarounds may be written here to share with everyone

## Context
[NOTE]: # ( Give us any additional information you may have. )

From time to time, systems you depend on for production work start to get in a way, significantly. Then you can not just ignore it as your workflow gets broken as well. Then, you look for solutions.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.0
Revision: d7a9ef4

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux , Ubuntu-Studio 20.04 LTS
Desktop Env: XFCE 4.16
Windowing System: X11

**Comment by droidmonkey** [comment]
You cannot use Firefox installed as a snap or flatpak. Confirm you have installed it natively and we can assist. Be aware that there are tons of these same issues with the same resolution.
