### ISSUE TITLE
Double click on username and password fields copy by double click is not enabled by default

### ISSUE THREAD

**Issue by ChrisDeath** [keepassxreboot/keepassxc#7796]
## Overview
Since version 2.7.0 the double click copy feature on user name or password is not enabled anymore by default. This means a 5 year old feature is removed from default behaviour and therefore irritating many users. They have to Google for the solution as it is easy to miss the feature flag in Security settings.

## Steps to Reproduce
1. You need to be a longterm user to recognize the issue.
1. Install KeepassXC 2.7.0
1. Double click on username

## Expected Behavior
By default it should be enabled to copy entries as otherwise many users default behaviour will be broken and are bothered with the need to enable it again actively!

## Actual Behavior
It is not enabled by default. And users think it is a bug, see issue https://github.com/keepassxreboot/keepassxc/issues/7677

KeePassXC - Version 2.7.0
Revision: [d7a9ef4](https://github.com/keepassxreboot/keepassxc/commit/d7a9ef493241421402cbe3aba2518e159c4a2dd8)

Qt 5.15.3
Debugging mode is disabled.

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 5.16.16-arch1-1

Enabled extensions:

   - Auto-Type
   - Browser Integration
   - SSH Agent
   - KeeShare
   - YubiKey
   - Secret Service Integration

Cryptographic libraries:

   - Botan 2.19.1

**Comment by michaelk83** [comment]
See https://github.com/keepassxreboot/keepassxc/issues/7677#issuecomment-1088469615
