### ISSUE TITLE
CTRL-C not working after URL clicks

### ISSUE THREAD

**Issue by thyxNY** [keepassxreboot/keepassxc#7799]
## Overview
CTRL-C not working after URL clicks

## Steps to Reproduce
1.Using a search engine, I found 5 lines
2.Switch to 3 lines
3.Click on URL, chrome opens with the page from url
4.Switch to KeePassXC, CTRL-B
5.Switch to Chrome, CRTL-V (user copied to browser)
6.Switch to KeePassXC, CTRL-C
7.Switch to chrome, CRTL-V (URL copied but password expected)
 
## Expected Behavior
CTRL-C from KeePassXC is expected to get password, not URL.

KeePassXC - 2.7.9
Operating System: Windows 10

**Comment by droidmonkey** [comment]
What do you mean by this:

> 1.Using a search engine, I found 5 lines
> 2.Switch to 3 lines

Also, make certain your password is not actually a url as well.

**Comment by thyxNY** [comment]
Searching isn't important. 
On any entry when I click in KeePassXC on URL focus is set on this URL. CTRL-B working OK but CTRL-C coping URL value, not password.

**Comment by thyxNY** [comment]
Before clicking on URL this looks like:
![obraz](https://user-images.githubusercontent.com/73193311/161756287-aa060626-518f-43a9-a3cc-bb71c44b247e.png)

After clicking on URL focus is set on URL:
![obraz](https://user-images.githubusercontent.com/73193311/161756262-db71c65b-b59a-4a6a-ba41-b83a5b2867c7.png)

**Comment by droidmonkey** [comment]
This is by design to allow you to copy the url. This is an unfortunate side effect of overloading the standard copy shortcut to copy passwords. You need to have your focus on the entry line item to copy the password.

**Comment by thyxNY** [comment]
Mostly I want to copy the user and password. If I wanted to copy the URL I can edit the entry and copy the URL to the clipboard. Or on entry preview, I can click right mouse button + "Copy link location". 

But now is a mismatch, CTRL-B can copy username but CTRL-C can copy URL or copy password. On entry preview, for me, CTRL-C must copy the password, not the URL.

**Comment by thyxNY** [comment]
In KeePassXC 2.6.6 this worked fine.

**Comment by droidmonkey** [comment]
At the end of the day we recommend you use the browser extension or Auto-Type instead of the clipboard. Either way, this was a bug in previous versions that we fixed. Ctrl+C now copies the current focused element instead of always copying the password. That is by design and won't be reverted back.

**Comment by thyxNY** [comment]
Mostly I use KeePassXC-Browser extension. But some pages require entering it manually.
It's a pity that now it works badly in the newer version.

Maybe it is worth asking other users about their preferences? In my opinion, it was better in 2.6.6.

**Comment by egor-tensin** [comment]
@droidmonkey Any way you could point to the specific commit/place in code where this was changed? I could then make my own Arch Linux package that reverts this.

**Comment by droidmonkey** [comment]
It's in DatabaseWidget the copyPassword function
