### ISSUE TITLE
Windows about dialog is very narrow

### ISSUE THREAD

**Issue by jsoref** [keepassxreboot/keepassxc#780]
About dialog is very narrow

## Expected Behavior

The about dialog should be reasonably sized (probably 3x as wide as it is today)

## Current Behavior

![image](https://user-images.githubusercontent.com/2119212/28250465-47fca2b6-6a37-11e7-8235-3e4c103641d8.png)

## Steps to Reproduce (for bugs)

1. Install KeePass XC on windows
2. Run it
3. Help>About

## Debug Info

KeePassXC - 2.2.0
Revision: caa49a8ef3ee28ed478192389b21d61107b3b8e0

Libraries:
- Qt 5.9.0
- libgcrypt 1.7.7

Operating system: Windows 10 (10.0)
CPU architecture: x86_64
Kernel: winnt 10.0.15063

Enabled extensions:
- KeePassHTTP
- Auto-Type
- YubiKey

**Comment by jsoref** [comment]
I should note, this is a dell laptop w/ resolution 3200x1800 (recommended) and font size 250% (recommended).

I'm less certain about whether this is relevant to this issue, but it wouldn't shock me if it is.
I suspect that the >100% scaling is relevant.

I'm not particularly used to using high resolution laptops....

**Comment by phoerious** [comment]
This is most likely due to DPI scaling.

**Comment by jlindgren90** [comment]
It's not specific to Windows.  On Linux at 128 dpi:
![keepass-about](https://user-images.githubusercontent.com/1244737/28487757-2a39c4ba-6e66-11e7-9968-cc369677785d.png)
