### ISSUE TITLE
Make KeepassXC suitable for 4K on Linux

### ISSUE THREAD

**Issue by MaximBar** [keepassxreboot/keepassxc#7801]
I have a 4K TV screen using Linux Mint and when I start this app, all text and interface is very very small.
Some apps actually run fine, but this one needs to be adjusted to 4K resolution.
The workaround is to run the app from command line via:
Exec=env QT_SCALE_FACTOR=3 /usr/bin/keepassxc
But it's not perfect.

**Comment by phoerious** [comment]
This not something we can fix. It's up to your Linux distribution / desktop environment to provide the correct resolution and pixel density data and up to Qt to scale the UI accordingly. It should work most of the time. If it doesn't, at least one of these two is doing something funky. There are previous reports about similar issues here on GitHub already.
