### ISSUE TITLE
Program crashed without raising error on Windows 11

### ISSUE THREAD

**Issue by aetb** [keepassxreboot/keepassxc#7802]
### Overview
Same issue as [here](https://github.com/keepassxreboot/keepassxc/issues/7760) but on Windows 11.

Upon updating to 2.7, the program crashes every time upon unlocking a database.

### Steps to reproduce
1. Open program
2. Unlock database
3. Crashes with no error message

**Comment by phoerious** [comment]
We can't really do anything with that report. Please provide more information or add information to existing bug reports if you think that you are experiencing the very same issue.
