### ISSUE TITLE
After new update, cannot copy paste from Attribute field

### ISSUE THREAD

**Issue by jdsk789** [keepassxreboot/keepassxc#7803]
Hello,

After updating to 2.7, I cannot copy directly from Advanced -> Attribute field like before. Please have a look at this issue

Also for MAC user, I cannot find a way to move around the entries like before, for example, move up or down the entry.

**Comment by droidmonkey** [comment]
![image](https://user-images.githubusercontent.com/2809491/161877784-a4ee66bb-e407-468e-8589-610184760612.png)

To move entries up and down you need to place the view in natural sort order (click the sort column until the arrow disappears). Then you can press Cmd+Alt+Up or Down to move entries.
