### ISSUE TITLE
Publicize pre-releases to attract more testers

### ISSUE THREAD

**Issue by michaelk83** [keepassxreboot/keepassxc#7804]
## Summary
List pre-releases on the [main download page](https://keepassxc.org/download/) and in the [blog](https://keepassxc.org/blog/), and if possible, also on the [main github page](https://github.com/keepassxreboot/keepassxc).

## Context
One of my lessons from the 2.7.0 release is that the beta pre-release didn't get enough people testing it. Many of the issues that should've been detected during beta popped up with the final release instead. The pre-release isn't listed on the main download page, isn't mentioned in the blog, and isn't listed on the main github page under "Releases" (you have to click the "Releases" link to see it). The only people who know that there's a pre-release out are those who are subscribed to the github issues.

Mentioning and linking to the pre-release in the above-mentioned locations should let more users know that a pre-release is out, and may attract more of them to test it.

**Other lessons:**
- List system requirements (at least OS version) clearly in the downloads page, and link to the legacy installer if there is one (as in #7777).
- Link to the full changelog more prominently. The very bottom of the blog post is too easy to miss, skip, or not even get to.

**Comment by droidmonkey** [comment]
We should include the last couple release changelogs in About -> Changelog. To be fair to us we did post on Twitter and Matrix looking for beta testers. We have a large following on Twitter and did receive several pre-release bugs. You can't possibly catch everything.

**Comment by phoerious** [comment]
I don't think this is really an issue. We had several thousand test users, but the final release will always attract more people and bugs will be discovered only later. That's an inherent property of rare effects.
