### ISSUE TITLE
Cmake -DWITH_XC_ALL=ON fails with missing Yubi lib on Debian

### ISSUE THREAD

**Issue by abuGit** [keepassxreboot/keepassxc#7808]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Followed https://github.com/keepassxreboot/keepassxc/issues
2. `cmake -DWITH_XC_ALL=ON` fails with error 'Yubi lib not found `

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
cmake should work

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
yubi libs (or parts) not found 

Could NOT find YubiKey (missing: YUBIKEY_LIBRARIES YUBIKEY_INCLUDE_DIRS)

even I installed 

    sudo apt install qtbase5-dev qtbase5-private-dev qttools5-dev qttools5-dev-tools \
      libqt5svg5-dev libargon2-dev libminizip-dev libbotan-2-dev libqrencode-dev \
      zlib1g-dev asciidoctor libreadline-dev libpcsclite-dev libusb-1.0-0-dev \
      libxi-dev libxtst-dev  libqt5x11extras5-dev

   Could NOT find YubiKey (missing: YUBIKEY_LIBRARIES YUBIKEY_INCLUDE_DIRS)

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )

    Could NOT find YubiKey (missing: YUBIKEY_LIBRARIES YUBIKEY_INCLUDE_DIRS)

KeePassXC - 2.6.6
Revision: 2.6.6

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: KDE
Windowing System: X11

**Comment by abuGit** [comment]
What worked for me is (the recommended):

    sudo apt build-dep keepass2 keepassxc keepass2-plugin-keepasshttp

This will find all libs and cmake finished successfully. 

(don't know if it is necessary to include keepass2)

**Comment by droidmonkey** [comment]
We are on 2.7.0 right now and the build instructions are for that version.
