### ISSUE TITLE
Password Quality label is cropped on Windows

### ISSUE THREAD

**Issue by jsoref** [keepassxreboot/keepassxc#781]
The label for the password quality indicator is cropped on Windows

## Expected Behavior

The tail of the "Q" in "Password Quality: Good" should be visible

## Current Behavior
![image](https://user-images.githubusercontent.com/2119212/28250488-f2261420-6a37-11e7-9482-bda94c35c023.png)

## Steps to Reproduce (for bugs)
1. Run KeePassXC
2. Tools>Password Generator
3. Look at the label below the colored bar below the password field

## Debug Info

KeePassXC - Version 2.2.0
Revision: caa49a8ef3ee28ed478192389b21d61107b3b8e0

Libraries:
- Qt 5.9.0
- libgcrypt 1.7.7

Operating system: Windows 10 (10.0)
CPU architecture: x86_64
Kernel: winnt 10.0.15063

Enabled extensions:
- KeePassHTTP
- Auto-Type
- YubiKey

**Comment by jsoref** [comment]
I should note, this is a dell laptop w/ resolution 3200x1800 (recommended) and font size 250% (recommended).

You probably don't need the high resolution, but I suspect that the >100% scaling is relevant.

I'm not particularly used to using high resolution laptops....

**Comment by droidmonkey** [comment]
I don't see this issue anymore in 2.3.1

**Comment by jsoref** [comment]
I still do:
![image](https://user-images.githubusercontent.com/2119212/37259463-0e0ba69c-255d-11e8-865d-04f5442d2284.png)

Actually, the toolbar has now shrunk. But, this is really the same as the other bugs about high-dpi
