### ISSUE TITLE
Global option to ask for an entry password confirmation when edited

### ISSUE THREAD

**Issue by l0f4r0** [keepassxreboot/keepassxc#7810]
## Summary
Add a global option to ask for an entry password confirmation when edited.

## Example of workflow
1. Create a new entry
2. Type in a password manually, either in plain form like 'mysuperpassword' or in secret form '***************'
3. Retype the same password just below in another field next to the first one
- If both passwords are the same, an indicator shows it's OK (for example, the background or border of the two fields becomes green) and the entry can be saved
- If not, an indicator shows they don't match (for example, the background or border of the two fields becomes red) and the user is invited to retry before (s)he can save the entry

## Context
This is a functionality I've already noticed on another password manager.
It's useful when entering passwords manually (not generating a password or copying/pasting one) so it reduces the risk of typo.

**Comment by l0f4r0** [comment]
Duplicate of which open issue/feature request please?

**Comment by droidmonkey** [comment]
#5168
