### ISSUE TITLE
Entry Preview: Notes height is truncated (2.7.1)

### ISSUE THREAD

**Issue by archetyped** [keepassxreboot/keepassxc#7811]
## Overview

The height of the notes field preview has been truncated in 2.7.1.

In v2.6, the height of the notes field preview expanded to use all available height in the preview pane.

## Steps to Reproduce
1. Install KeePassXC 2.7.1
2. View entry preview containing long note

## Expected Behavior

Note preview height should use all available space in preview pane.

### Example (v2.6.6)
![KPXC_Issue_Preview_Notes-Height_2 6 6](https://user-images.githubusercontent.com/3237917/162063733-e6500350-24be-4baa-b07a-906d9b70c48e.png)

## Actual Behavior

Note preview height is fixed and longer notes display scrollbars.

### Example (v2.7.1)
![KPXC_Issue_Preview_Notes-Height_2 7 1](https://user-images.githubusercontent.com/3237917/162063788-e827b321-7b87-4089-8858-5cdf213dc729.png)

## Context
[NOTE]: # ( Give us any additional information you may have. )

KeePassXC - Version 2.7.1
Revision: 5916a8f
Operating System: macOS 12.3

**Comment by droidmonkey** [comment]
Omg I hate qt layouts

**Comment by phoerious** [comment]
Didn't realise people were using KeePassXC as an ebook reader. 😂
