### ISSUE TITLE
KeePassXC 2.7.0 can’t be seen over remote desktop

### ISSUE THREAD

**Issue by MrWhipple** [keepassxreboot/keepassxc#7812]
KeePassXC 2.7.0 + Windows 10 Home & Windows 10 Pro

I use [Remote Utilities](https://www.remoteutilities.com/) as a remote desktop solution to connect between work and home PCs. Since installing KeePassXC 2.7.0, on the remote PC (in either direction) KeePassXC appears as a black rectangle. I can interact with it (move it, resize it, enter my password to unlock a database), but I just can’t see what I’m doing.

Has anyone else experienced this in a remote desktop situation?

![desktopremote-utilities-keepassxc-2 7 0](https://user-images.githubusercontent.com/20133497/162080545-1571573e-f902-42fe-bdf6-ba6da5124179.jpg)

**Comment by phoerious** [comment]
Please read the docs. https://keepassxc.org/docs/KeePassXC_UserGuide.html#_screenshot_security

**Comment by MrWhipple** [comment]
> Please read the docs. https://keepassxc.org/docs/KeePassXC_UserGuide.html#_screenshot_security

Thank you for the quick reply. I looked through the documentation, but I didn’t make the connection between screenshot/screen capture and using remote desktop. Perhaps you could add something about remote desktop to that section.

**Comment by Chrescht** [comment]
In tightvnc the window does not even show as black. Instead the window could show the text KeepassXC with the logo.

**Comment by dhtech636** [comment]
On the desktop KeepassXC shortcut > RIGHT click > Properties > Target: > Add (NOTE add a space THEN add) --allow-screencapture at the end of "C:\Program Files\KeePassXC\KeePassXC.exe" (It should look like "C:\Program Files\KeePassXC\KeePassXC.exe" --allow-screencapture) > Apply > OK

KeepassXC will now automatically open every time from your Remote Connection.

**Comment by elegktara37** [comment]
> On the desktop KeepassXC shortcut > RIGHT click > Properties > Target: > Add (NOTE add a space THEN add) --allow-screencapture at the end of "C:\Program Files\KeePassXC\KeePassXC.exe" (It should look like "C:\Program Files\KeePassXC\KeePassXC.exe" --allow-screencapture) > Apply > OK
> 
> KeepassXC will now automatically open every time from your Remote Connection.

Worked!!! Thanks
