### ISSUE TITLE
Make Sort-by-Title case-insensitive

### ISSUE THREAD

**Issue by knobhead** [keepassxreboot/keepassxc#7813]
Hi, 

Thanks for your great work! :blue_heart: 

## Overview
The alphabetical sorting of entries by title is case-sensitive. This is counter-intuitive¹, the sorting should mix upper- and lowercase letters, as long as its alphabetical.

## Steps to Reproduce
1. Have some entries with titles starting with lowercase and some with uppercase letters.
2. Click "Title" column header to sort them alphabetically

tada:
![Entries with capital first letters V, W and Z are sorted before those starting with lowercase a.](https://user-images.githubusercontent.com/6553961/162084928-87892e85-be33-4491-81cc-0897f2cfa49e.png)

## Expected Behavior

Don't sort upper-case letters first. Mix upper- and lowercase letters. (Or `lcase()` all titles internally before sorting). Result for the screenshot would be:

> ali
> all
> avc
> bet
> bik
> Vis
> Wa
> Zin

## Actual Behavior
Entries whose title starts with a capital letter are sorted alphabetically, then followed by those starting with lowercase letter.

KeePassXC - Version 2.7.0
Revision: d7a9ef4
Qt 5.15.3
Arch Linux

<details><summary>More Debug Info</summary>
<p>
Diagnosemodus ist deaktiviert.

CPU-Architektur: x86_64
Kernel: linux 5.17.1-arch1-1

Aktivierte Erweiterungen:
- Auto-Type
- Browser-Integration
- SSH-Agent
- KeeShare
- YubiKey
- Secret-Service-Integration

Kryptographische Bibliotheken:
- Botan 2.19.1

Kernel: linux 5.17.1-arch1-1

Aktivierte Erweiterungen:
- Auto-Type
- Browser-Integration
- SSH-Agent
- KeeShare
- YubiKey
- Secret-Service-Integration

Kryptographische Bibliotheken:
- Botan 2.19.1

</p>
</details>

¹ Yes, I know "intuitive" is pretty vague and ambiguous. When you are asked to iterate _the alphabet_, you neither ask "lower- oder uppercase alphabet?" nor start "shouting" ALL-CAPS LETTERS at the person who asked you. Catch my drift? :grin:

**Comment by droidmonkey** [comment]
https://github.com/keepassxreboot/keepassxc/blob/develop/src/gui/entry/EntryView.cpp#L70

Seems like we have a qt bug

**Comment by lyallp** [comment]
Personally, I like the strict Ascii sort sequence, Upper comes before lower... allows more flexible grouping.
Not all users come from Windows, where everything is case insensitive.
The ability to move entries manually using the Entries -> Move Up/Move Down, is a possible alternative.
However, it would be a good configuration option...
