### ISSUE TITLE
Failed release verification for 2.7.1 (DMG Intel)

### ISSUE THREAD

**Issue by alicroche** [keepassxreboot/keepassxc#7815]
Tried it twice with two different browsers, it failed each time. I'm on Catalina (MacOS 10.15.7)
- Download ok,
- Mounting DMG ok, 
- Then fails with message "KeePAssXC is damaged and can't be opened" (translated from french) when I drop KeePassXC icon on the Applications folder. SHA256 verification OK.

**Comment by droidmonkey** [comment]
Close your browsers before installing into applications. This is a weird issue with the proxy for the extension being left held open and invalidating the signatures.

**Comment by alicroche** [comment]
OK. Thanks. Confirmed.
