### ISSUE TITLE
KeePassXC cannot detect the Gnome Theme

### ISSUE THREAD

**Issue by izacarias** [keepassxreboot/keepassxc#7817]
## Overview
KeePassXP cannot auto-switch between Light and Dark themes in Gnome 42.0.

## Steps to Reproduce
1. Configure Gnome with the Light theme
2. Open KeePassXC
2. Go to Tools Menu -> Theme -> Automatic
3. Close KeePassXC
4. Configure Gnome with the Dark theme
5. Open KeePassXC
6. KeePassXC is still using the light theme

## Expected Behavior
KeePassXC should change to the Dark theme after restarting the application in Gnome using the dark theme.

## Actual Behavior
KeePassXC is still using the light theme doesn't matter the theme configured in Gnome.

## Context
Just Open the application after changing the Gnome theme (from Light to Dark)

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.6
Revision: 9c108b9

Qt 5.15.3
Debugging mode is disabled.

Operating system: Fedora Linux 36 (Workstation Edition Prerelease)
CPU architecture: x86_64
Kernel: linux 5.17.1-300.fc36.x86_64

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- libgcrypt 1.10.1-unknown

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux (Fedora Workstation 36)
Desktop Env: Gnome (42.0)
Windowing System: X11

**Comment by mnme** [comment]
Can confirm. There is an even more interesting behaviour when switching themes on-the-fly:

https://user-images.githubusercontent.com/2905118/162255422-678d1f4d-a5f1-4c9a-9463-5e0bd9930a87.mp4

KeePassXC correctly changes to dark but not back.

**Comment by vimpostor** [comment]
This is probably a Gnome bug and not a Keepass bug, as foreshadowed in https://github.com/keepassxreboot/keepassxc/pull/7422#issuecomment-1046729100

You can test this by running `qdbus org.freedesktop.portal.Desktop /org/freedesktop/portal/desktop org.freedesktop.portal.Settings.Read "org.freedesktop.appearance" "color-scheme"` while the light theme is selected. The correct result code would be `2 (Prefer light theme)`, but if Gnome implements the spec wrong it will return `0 (No preference)`.

If that is the case, please file a bug report in Gnome. I don't understand how one can get this implementation wrong in the first place: If the user explicitly chooses light theme, the user **obviously** wants to prefer light theme.

Gnome is then also blatantly lying to the user in the exposed settings: It says "Light" but it actually is a "No-preference" switch.

If Gnome wants to continue making themself the clown in the Linux world, they can continue doing that within the realms of their own DE, but please keep these horribly misguided ideological decisions out of the desktop independent specifications.

But then again, we don't know yet if this is actually just a bug (and hopefully not a deliberate decision), so I don't want to go off the rails yet.

**Comment by izacarias** [comment]
@vimpostor Thanks for the explanation.
The qdbus wasn't installed on my system, therefore I had installed it (`sudo dnf install qt`).

After that I performed the tests you suggested and it seems qdbus is only returning the values
0 -> light theme
1 -> dark theme

So yes, you are right and it isn't a KeePassXC bug, but a Gnome misbehaviour. 

Thanks!

**Comment by vimpostor** [comment]
I mean technically we could workaround the Gnome issue by just considering `no-preference` as `prefers-light`. But that would completely reduce the very reason for this setting ad absurdum, as one could have chosen `prefers-light` to begin with. Instead of reducing this setting to absurdity in all third-party applications, Gnome should just fix this in their own code.

I am curious though what Gnome has to say about this, does there exist a Gnome bug report already?

**Comment by izacarias** [comment]
Well... so weird
Setting the theme with 
`gsettings set org.gnome.desktop.interface color-scheme prefer-dark` and `gsettings set org.gnome.desktop.interface color-scheme prefer-light`, KeePassXC changes the themes accordingly. 

However, when I change the theme to dark in the Gnome Settings I get this:
```
gsettings get org.gnome.desktop.interface color-scheme
'prefer-dark'
```
Changing back to light theme, I get this:
```
gsettings get org.gnome.desktop.interface color-scheme
'default'
```
I'll will try to figure it out on where to report this to Gnome Team :) (I did not check whether a bug report already exists)

Btw, Thanks for this great software (KeePassXC)

**Comment by phoerious** [comment]
"default" seems to be a synonym for "light" then, at least in Gnome terminology.

**Comment by scollovati** [comment]
Just adding that Linux Mint with Cinnamon DE has this issue too.
