### ISSUE TITLE
In-browser pop-ups don't appear

### ISSUE THREAD

**Issue by ckykenken** [keepassxreboot/keepassxc#7818]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
I used to right-click in the password field to generate a password from the password generator pop-up, and after clicking "register" (or something similar), there should be a pop-up bar under the URL bar asking me whether I would like to save the password. However, the features seem to disappear since KPXC version 2.7, in all sites, all browsers with the extension installed.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
Right-click in password field > KeePassXC > show password generator

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
The password generator pop-up should appear

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Nothing happens after the operation

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.1
KeePassXC-Browser - 1.7.11
Operating system: Win64
Browser: Chrome/Chromium/Edge 100.0.4896.79

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows

**Comment by droidmonkey** [comment]
It's an extension bug that will be fixed in next release
