### ISSUE TITLE
[2.7.1] Cannot open existing database - Ubuntu 20.04.4 LTS

### ISSUE THREAD

**Issue by WebSchw** [keepassxreboot/keepassxc#7819]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
When opening keepass normally  (through search option, icon or console) the buttons "Open existing database" and "Import from XYZ" do not work. Opening an existing database only works through console with specifically providing the db path.
Once this db is listed in "Recent databases", clicking on it results in error "Failed to open MasterP.kdbx. It either does not exist or is not accessible."

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. open keepassxc
2a. click "Opening existing database"
2b. (Alternative) (if existing) click on recent database
3a. Nothing happens
3b. (Alternative) "Failed to open MasterP.kdbx. It either does not exist or is not accessible." error appears

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Open the existing database which worked in 2.7.0

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
see above

## Context
[NOTE]: # ( Give us any additional information you may have. )
fresh 2.7.1 install through snap on Ubuntu 20.04.4 LTS

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.1
Revision: 5916a8f
Distribution: Snap

Qt 5.15.3
Debugging mode is disabled.

Operating system: Ubuntu Core 20
CPU architecture: x86_64
Kernel: linux 5.11.0-051100-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.12.1

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: Gnome
Windowing System: no idea

**Comment by WebSchw** [comment]
Duplicate of which?

**Comment by droidmonkey** [comment]
Please use our nice `Distribution: Snap` label to see all the current known issues with snaps.
