### ISSUE TITLE
Yubikey only visible when running as root

### ISSUE THREAD

**Issue by bmharper** [keepassxreboot/keepassxc#7820]
## Overview

Starting today, KeepassXC 2.7.1 _is unable_ to see my Yubikeys (I have two: Neo and 4), when I'm running as an unprivileged user.
When running as root, KeepassXC _is able_ to see and use by Yubikeys.

I am using the PPA distribution (NOT the snap).

This has been working fine for years. I have no idea what caused this breakage.

## Steps to Reproduce
1. Open KeepassXC

## Expected Behavior
See my Yubikey in the `Hardware Key` dropdown

## Actual Behavior
`Hardware Key` dropdown is empty

## Context
KeePassXC - Version 2.7.1
Revision: 5916a8f

Qt 5.12.8
Debugging mode is disabled.

Operating system: Ubuntu 20.04.4 LTS
CPU architecture: x86_64
Kernel: linux 5.13.0-39-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.12.1

Operating System: Ubuntu 20.04
Desktop Env: Gnome
Windowing System: X11

**Comment by droidmonkey** [comment]
This means your udev rules are not allowing access to the yubikey. This isn't on us.

You need to install this: https://packages.ubuntu.com/focal/libyubikey-udev

Try rebooting as well if already installed.

**Comment by bmharper** [comment]
Thanks!

libyubikey-udev was missing.

I'll try creating a PR for adding this to the FAQ
