### ISSUE TITLE
fix a wrong link in wiki page

### ISSUE THREAD

**Issue by FischLu** [keepassxreboot/keepassxc#7822]
in the [Building KeePassXC](https://github.com/keepassxreboot/keepassxc/wiki/Building-KeePassXC) wiki page, the link of **Setup your build environment** of MacOS is not correct

<img width="532" alt="image" src="https://user-images.githubusercontent.com/10261662/162279464-26dd6ef6-cae9-41e5-9a2b-6904ce02e991.png">

Current it is 
https://github.com/keepassxreboot/keepassxc/wiki/Set-up-Build-Environment-on-OS-X

The correct one should be 
https://github.com/keepassxreboot/keepassxc/wiki/Set-up-Build-Environment-on-macOS

**Comment by droidmonkey** [comment]
Fixed thank you
