### ISSUE TITLE
Document backup syntax 

### ISSUE THREAD

**Issue by psyciknz** [keepassxreboot/keepassxc#7823]
## Summary
Is it possible to configure more in relation to the backups kept?  I'm trialing moving to keepassxc from keepass where I was a webdav (to nextcloud) user.  

My workflow is that I have my main DB on two machines, and I would sync to web dav on each change.
I like the "automatically reload upon external modification" so am trying that.   But would like to see home many backups can be stored and have them with date/time.

Are they current options, or is that a feature request.   I had a quick look through the code, and could only see DB_FILENAME a a replacement option.

**Comment by droidmonkey** [comment]
Hover over the setting field and it will show you the time option syntax. This needs to be documented in the user guide.

**Comment by psyciknz** [comment]
Thanks  thought I saw that but couldn't get it to show up again, and couldn't find anything in the docs about it.  There's a link it mentions, but it one of those annoying to re-type ones.

**Comment by alejandrop79** [comment]
it would be good to have date in the field name, with this option you can have daily backup of any database

**Comment by droidmonkey** [comment]
It's a feature already, you just need to add the placeholder {TIME}
