### ISSUE TITLE
Can't zoom with zoomit.exe

### ISSUE THREAD

**Issue by snowman** [keepassxreboot/keepassxc#7824]
when zooming in, the main window disappears (The window still there, but not showing them, like a transparent window, still receives mouse click)

[zoomit.exe - microsoft.com](https://docs.microsoft.com/en-us/sysinternals/downloads/zoomit)

**Comment by droidmonkey** [comment]
https://keepassxc.org/docs/KeePassXC_UserGuide.html#_screenshot_security
