### ISSUE TITLE
Issue #3688 seems to have reappeared

### ISSUE THREAD

**Issue by S3NTYN3L** [keepassxreboot/keepassxc#7827]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
Latest update to 2.7.1 seems to have broken whatever was done to correct issue #3688 in PR #3794.
Would you all be so kind as to look into this again?
Thanks in advance.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
Please refer to issue #3688 

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Please refer to issue #3688

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Changes made in PR #3794 seem to be broken now.

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.1
Revision: 5916a8f

Qt 5.12.8
Debugging mode is disabled.

Operating system: Linux Mint 20.3
CPU architecture: x86_64
Kernel: linux 5.4.0-107-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.12.1

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux Mint 20.3
Desktop Env: Cinnamon
Windowing System: X11

**Comment by droidmonkey** [comment]
Yah we decided to revert that behavior because it was very confusing. It's not be removed again. There is another request for customizing the columns of the selection dialog that is a better option.
