### ISSUE TITLE
KeePass doesn't open

### ISSUE THREAD

**Issue by julianheusel** [keepassxreboot/keepassxc#7829]
## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Install KeePass on Windows Server 2022 and set up a db on the server.
2. The db **can** be opened and edited on the server .
3. On a client pc (login as administrator) the db **can** be opened.
4. On a client pc with a normal user of the active directory the KeePass windows opens and gets minimized. If you hover on the icon in the windows taskbar you can see only a black window. The database **cannot** be opened.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
The database should open.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
The database will not open.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.1, 64bit

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 11 Pro

**Comment by phoerious** [comment]
https://keepassxc.org/docs/KeePassXC_UserGuide.html#_screenshot_security
