### ISSUE TITLE
FdoSecrets: No such object path '/org/freedesktop/secrets/aliases/default'

### ISSUE THREAD

**Issue by the-nic** [keepassxreboot/keepassxc#7832]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

## Steps to Reproduce
I am using visual studio code with [PostgreSQL](https://marketplace.visualstudio.com/items?itemName=ckolkman.vscode-postgres) extension. Passwords are stored in FdoSecrets
1. Create a connection
2. modify a connection with password
3. error is shown: No such object path '/org/freedesktop/secrets/aliases/default'

## Expected Behavior
Implementation of the the object path as specified in https://specifications.freedesktop.org/secret-service/latest/ch12.html

## Actual Behavior
`/org/freedesktop/secrets/aliases/default` seems to be missing

## Context

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.1
Revision: release

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: KDE
Windowing System: X11

**Comment by droidmonkey** [comment]
See https://github.com/keepassxreboot/keepassxc/issues/7575
