### ISSUE TITLE
Snap 2.7.1 - ERROR: not connected to the kde-frameworks-5-91-qt-5-15-3-core20 content interface

### ISSUE THREAD

**Issue by colinl** [keepassxreboot/keepassxc#7833]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
Starting keepassxc 2.7.1 (installed as snap) on Ubuntu 20.04 gives the error
ERROR: not connected to the kde-frameworks-5-91-qt-5-15-3-core20 content interface
snap list shows
keepassxc                          2.7.1                       1552   latest/stable    keepassxreboot

After reverting to 2.7.0 it works correctly, and fails again after upgrading to 2.7.1 again

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Start keepassxc after upgrade to 2.7.1

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Should open ok

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
ERROR: not connected to the kde-frameworks-5-91-qt-5-15-3-core20 content interface

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux Ubuntu 20.04
Desktop Env: Gnome
Windowing System: X11

**Comment by droidmonkey** [comment]
You need to reinstall from scratch. Your snap setup is not valid. Can also try installing the dependencies (core20 and kde framework) separately. Nothing changed in the snap file between 2.7.0 and 2.7.1

**Comment by colinl** [comment]
Thanks.  A re-install did indeed fix it.  Very odd (to say the least) that it showed the same symptom on two separate systems.
