### ISSUE TITLE
Global Auto-type and Browser extension behaviour changed

### ISSUE THREAD

**Issue by mkmephistopheles** [keepassxreboot/keepassxc#7834]
## Overview
It seems with the update to 2.7.1 the global Auto-type and the way the browser extension works was changed.
In previous versions i used global Autotype to actually unlock other keepassxc databases, based on a windowtitle like "database.kdbx [locked] - KeePassXC" and it worked just fine. This does not work anymore, the global auto-type dialogue just doesn't open at all.

With further testing i found out, that it seems to now only search for matching credentials in the one tab / database of keepassxc that is currently in focus. When attempting to perform autotype on a tab of a yet still locked DB (for which the needed credentials are saved in another unlocked DB in another tab) this of couse leads to no results at all. But not even the "no matching entries found" popup that previous versions had.

When trying to perform global auto-type in a window i have no matching entries for, but while the focus in keepassxc is on an actually unlocked DB, it will now just show **all entries of all unlocked** databases. In previous versions this threw the "no matching entries" popup. 

Feels like a massive security flaw in comparsion to the previously applied prefiltering and only showing results that might match based on window title or other set filters!

The global auto-type dialogue itself changed too, i now need to doubleclick an entry to perform autotype instead of single clicking it like previously.

Also the interaction with the browser extension now changed. Again if the focus in the keepaassxc app is on a yet still locked database, even if it is one that is not even connected to the browser extension, it will prompt me to unlock the DB, instead of looking for credentials in the e.g 5 actually unlocked databases that are all connected to the browser extension.

- - - - - - - - - - - - 

## Steps to Reproduce
1. manually unlock a DB that contains credentials to other DBs
2. open other DB as a tab in the same keepassxc window (single instance)
3. attempt to perform global autotype triggered by hotkey on other DB opened in step 2

## Expected Behavior
global autotype popup appears, letting me choose matching credentials from the previously unlocked other DB

## Actual Behavior
Autotype dialogue does not appear

- - - - - - - - - - - - 

## Steps to Reproduce
1. manually unlock several DBs that have entries with autotype sequences
2. switch focus to another, locked DB in the same keepassxc window (single instance)
3. switch focus to another application
4. attempt to perform global autotype triggered by hotkey on another application

## Expected Behavior
global autotype popup appears, letting me choose matching credentials from the previously unlocked other DB

## Actual Behavior
dialogue prompting me to unlock the one locked database appears, ignoring the several unlocked DBs and entries in them

- - - - - - - - - - - - 

## Steps to Reproduce
1. manually unlock several DBs that are connected to the browser extension
2. switch focus to another, locked DB that is not even connected to browser extension
3. attempt to use the browser extension to fill in credentials in the browser

## Expected Behavior
being able to actually choose and fill in credentials like in previous versions

## Actual Behavior
dialogue prompting me to unlock the one locked database appears, ignoring the several unlocked DBs and entries in them

- - - - - - - - - - - - 

## Steps to Reproduce
1. manually unlock one or several DBs that have entries with autotype sequences in them
2. switch focus to another application for which there are no matcing autotype entries in any of the unlocked databases
3. perform the global auto-type keyboard shortcut

## Expected Behavior
"no matching entries found" popup

## Actual Behavior
global autotype dialogue appears, showing absolutely each and every single entry that is in any of the unlocked databases

- - - - - - - - - - - - 

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.1
Revision: 5916a8f

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 10 Version 2009

**Comment by varjolintu** [comment]
It's a known issue with the browser extension that if KeePassXC is focused to a locked database, it's not working as expected. The fix is coming sooner or later.

**Comment by droidmonkey** [comment]
You cannot Auto-Type into the keepassxc window itself, that is explicitly blocked. Not changing. Use auto open feature (read the user guide).

There is no issue with showing all entries if no matches are found, it's still the keepassxc application... which already knows about all your entries. Read the user guide. 

You can simply press enter to perform the Auto-Type action chosen. Single click on a row to perform an action is generally an undesirable behavior. The workflow is slightly different but you'll find it far superior. 

For browser extension, enable "search all open databases" option in application settings.
