### ISSUE TITLE
Using XMonad Auto-Type opens main window and starts search

### ISSUE THREAD

**Issue by mwip** [keepassxreboot/keepassxc#7835]
# Problem description

On version 2.7.1 (and 2.7.0 for that matter), Auto-Type still is behaving strangely on my machines (both arch). Whenever I invoke Auto-Type through my global hotkey, the selection dialog opens as expected. Clicking "Type Sequence" or hitting `<Return/Enter>` opens the main KeePassXC dialog and starts searching using the credentials.

# Steps to reproduce

1. Unlock Database
2. Go to Window with Auto-Type title
3. Select entry
4. hit `Enter`

-> the main KeePassXC window opens, search is performed with the username/password of the selected Auto-Type sequence as the cursor is located in the search textbox.

# Expected behavior

Instead of opening the main window/dialog, the Auto-Type dialog should minimize to tray focusing the most recent window performing the Auto-Type.

This was the default behavior prior to 2.7.0

## System Info:
```shell
keepassxc --version  # Also opens main window...
KeePassXC 2.7.1 

uname -a
Linux andlang 5.17.1-zen1-1-zen #1 ZEN SMP PREEMPT Mon, 28 Mar 2022 21:56:46 +0000 x86_64 GNU/Linux
```
Window manager: `xmonad`
Sytemtray: `stalonetray`

I searched for any duplicates but did not find any that discussed this very issue. If I missed it, feel free to close.

**Comment by droidmonkey** [comment]
I'm going to need a screen recording of this behavior.

**Comment by hifi** [comment]
Xmonad is probably doing something funky.

**Comment by mwip** [comment]
@droidmonkey Thanks for investing your time into this. I prepared a screen recording that shows the current behavior.
![2022-04-09_keepassxc_bug_autotype](https://user-images.githubusercontent.com/29728338/162563754-0c8281d0-1fb1-4e0e-a979-9a4a0296e388.gif)

@hifi This could be true. I will investigate a bit with other WMs (e.g. Qtile, KDE) and report my findings.

**Comment by mwip** [comment]
@hifi as you expected, it might have something to do with Xmonad. I was not able to confirm it with Qtile.
![2022-04-09_keepassxc_bug_autotype_qtile](https://user-images.githubusercontent.com/29728338/162564913-daf8879c-bba8-4864-92f5-6bcf9584eb17.gif)

```
keepassxc --debug-info
KeePassXC - Version 2.7.1
Revision: 5916a8f

Qt 5.15.3
Debugging mode is disabled.

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 5.15.33-1-lts

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.19.1
```

```
qtile --version
0.21.0
```

Let me know how I can add any further helpful debug info.

**Comment by droidmonkey** [comment]
Closing this as it appears to be an Xmonad problem
