### ISSUE TITLE
KeePassXC avec Secret Service pour Sirikali et Vorta pour Borg

### ISSUE THREAD

**Issue by DominiqueFrt** [keepassxreboot/keepassxc#7837]
Operating System: Kubuntu 21.10
KDE Plasma Version: 5.24.4
KDE Frameworks Version: 5.92.0
Qt Version: 5.15.2
Kernel Version: 5.13.0-39-generic (64-bit)
Graphics Platform: X11
Processors: 8 × Intel® Core™ i7-2700K CPU @ 3.50GHz
Memory: 15.6 Gio of RAM
Graphics Processor: NVIDIA GeForce GT 710/PCIe/SSE2
____________________________________________________
KeePassXC 2.7.1

Ne fonctionne toujours pas avec Vorta pour Borg
Je ne peux pas modifier la basse de donnée utilisant secret service

![KeePassXC](https://user-images.githubusercontent.com/42612895/162496332-5c424f9c-e2d7-4d95-adc9-47be068057f2.png)
![KeePassXC2](https://user-images.githubusercontent.com/42612895/162496342-64a25320-eff7-434a-9750-36cf977b95bd.png)

Cordialement

**Comment by phoerious** [comment]
My French is rather low-level, but the message is about failing to save the database, not about secret service integration. I assume with "Borg" you are talking about the synchronization service? If yes, then press the "Deactivate" (Desactiver) button and try again.
