### ISSUE TITLE
Add black/white tray icon for Mac OS light/dark theme

### ISSUE THREAD

**Issue by r0ckarong** [keepassxreboot/keepassxc#784]
The current tray icon is colored. Modern Mac OS uses black/white icons in the light/dark theme variants of the operating system. Please include a check which one is active and display a suitable tray icon.

## Expected Behavior
Depending on the theme variant chosen 
Default or "Dark" (System Settings -> General -> "Use dark menu bar and Dock"

Display a black or white systray icon.

## Current Behavior
A colored icon is shown when the option for showing a system tray icon is activated.

![screen shot 2017-07-17 at 11 51 52](https://user-images.githubusercontent.com/4920542/28263503-4d093408-6ae7-11e7-868b-c998afddbc4a.png)
![screen shot 2017-07-17 at 11 52 05](https://user-images.githubusercontent.com/4920542/28263504-4d20ef1c-6ae7-11e7-8856-123cfaecf86c.png)

## Debug Info
KeePassXC - Version 2.2.0
Revision: caa49a8ef3ee28ed478192389b21d61107b3b8e0

Libraries:
- Qt 5.9.0
- libgcrypt 1.7.7

Operating system: macOS Sierra (10.12)
CPU architecture: x86_64
Kernel: darwin 16.6.0

Enabled extensions:
- KeePassHTTP
- Auto-Type
- YubiKey

**Comment by droidmonkey** [comment]
Added in 2.3.0
