### ISSUE TITLE
Document links to other database

### ISSUE THREAD

**Issue by Massimo-B** [keepassxreboot/keepassxc#7840]
## Summary
Please provide the option to have other databases linked.

## Context
I mainly use a local personal database and a list of other databases located on network mounts. The passwords for them I have stored in my personal database but I need to search, copy and paste those credentials, while choosing the other database from Database->Recent Databases.

It would be helpful to have 2 new features for that:
1. When opening another database from Recent Databases, the password could be fetched from the already opened personal database.
2. A new item type in my personal database, that has the password (or keyfile) and additionally the link to that other database for easier opening via that link.

I already tried all the KeeShare features, like importing the other database or syncing, but finally I don't like to store the other information in my database for secrecy reasons.

**Comment by droidmonkey** [comment]
Use auto open or set the url for the entry to kdbx://[path to database] and provide the password and keyfile in username. When you open the url it will open and unlock the database for you.

**Comment by Massimo-B** [comment]
URL kdbx://[path to database] and Password in the password field, that works fine. Thanks.
