### ISSUE TITLE
KeepassXC on Win11: Windows Security asking for additional authentication

### ISSUE THREAD

**Issue by gitthiy** [keepassxreboot/keepassxc#7841]
### Steps to reproduce
open keepass database
enter credentials of your database 
login to db is done
ISSUE:
Windows Security pop up appears (new in this version of keepass)
Option a) click on cancel - access to opened db will be granted
Option a) authenticate with windows credentials - access to opened db will be granted

This interaction is useless as keepass does not verify what happens inside of Windows Security pop up.

### Keepass Details
KeePassXC - Version 2.7.1
Revision: 5916a8f

Qt 5.15.3
Diagnosemodus ist deaktiviert.

Betriebssystem: Windows 10 Version 2009
CPU-Architektur: x86_64
Kernel: winnt 10.0.22000

Aktivierte Erweiterungen:
- Auto-Type
- Browser-Integration
- SSH-Agent
- KeeShare
- YubiKey
- Schnelle Entsperrung

Kryptographische Bibliotheken:
- Botan 2.18.1

### OS Details
Edition	Windows 11 Home
Version	21H2
Installiert am	‎06.‎10.‎2021
Betriebssystembuild	22000.556
Leistung	Windows Feature Experience Pack 1000.22000.556.0

**Comment by phoerious** [comment]
This is for quick unlock to allow you to open the database with your Windows PIN. You can either use it or disable it in the settings.

**Comment by gitthiy** [comment]
Thanks for hint, hm issue is that this security setting is not verified by keepass see as described in Option a)

**Comment by phoerious** [comment]
It is. The first prompt is only for storing a key in the operating system for later use.
