### ISSUE TITLE
Can no longer double-click password to load it in the clipboard

### ISSUE THREAD

**Issue by ssrobins** [keepassxreboot/keepassxc#7843]
## Overview
I used to be able to double-click on the password 'dots' in the Entry to load it in the clipboard, but in KeePassXC 2.70+ it stopped doing that.

## Steps to Reproduce
1. Open a database
2. In an existing Entry, double-click on the password 'dots'

## Expected Behavior
I expect the password to be loaded into the clipboard for a limited period of time that's counted down in the bottom status bar. 

## Actual Behavior
Instead, the Entry opens and no password is loaded into the clipboard.
To accomplish my goal, I have to click Cancel, right-click on the entry and select Copy Password.

## Context
KeePassXC - Version 2.7.1
Revision: 5916a8f
Operating System: Windows/macOS

KeePassXC is super useful, thanks for working on this project :)

**Comment by droidmonkey** [comment]
It's now a security setting, enable it in the application settings. Also please search the issues board.

**Comment by ssrobins** [comment]
Thanks for the response. I did search issues, but I neglected to remove the filter to only search open ones, sorry about that.
