### ISSUE TITLE
Password Generator Presets

### ISSUE THREAD

**Issue by ndpandit** [keepassxreboot/keepassxc#7844]
Password generator should have option to save and load configuration presets for all available options. 

## Examples
![Mock_up](https://user-images.githubusercontent.com/21022809/162607748-05200333-347e-4f68-847d-5bab5fb2e8d8.png)

## Context
Service providers, especially banks and financial services require their users to reset expired passwords. Every bank / service provider have their own password policy on length, allowed characters and non-allowed characters. Keepassxc user should be able to save password generator configuration presets so that he can simply select the generator preset for that bank / service which will save the time spent on setting all the options to match each individual unique bank / service password policy.

**Comment by Massimo-B** [comment]
Duplicate of #19.

**Comment by Massimo-B** [comment]
Duplicate of #2628.
