### ISSUE TITLE
Multiple -y flags are not supported by database keepassxc-cli commands

### ISSUE THREAD

**Issue by isindir** [keepassxreboot/keepassxc#7847]
## Summary

I have tried to use multiple `-y` options to specify multiple yubikeys and only the later `-y` took presedence.

Where I'd like to supply multiple yubikeys as I'm going to use `keepassxc-cli` with [chezmoi](https://www.chezmoi.io/) and potentially using different hardware keys indirectly.

## Examples

`keepassxc-cli db-info <full_path>/<file_name>.kdbx -y 2:<serial_key_1> -y 2:<serial_key_2>`

> this should try in sequence both (or more) keys and work with first it finds responding, but if none responded - show error message about all yubikeys passed via `-y` flags

## Context

Yubikey: Yubikey 5 NFC , Firmware: 5.4.3

KeePassXC - Version 2.7.0
Revision: d7a9ef4

Operating System: macOS Monterey 12.2.1 , Intel processor

In GUI everything works as expected.

**Comment by droidmonkey** [comment]
I don't really understand your use case. Are both keys able to unlock the database (same secret stored on both keys)? If so then just drop the serial number entirely (`-y 2`) and we'll use the first key in the usb chain. 

If the keys are actually different then this makes no sense to try to unlock a database with an invalid key.

We don't support multiple arguments anywhere on the cli so this would be a special case for a problem that (frankly) doesn't really exist.

**Comment by isindir** [comment]
@droidmonkey , I did not realise that `-y 2` means use the first one on the chain with the same secret, it was my use case.

Thanks for clarifying, no changes are needed than. Closing ticket

**Comment by isindir** [comment]
@droidmonkey , thank you for amazing tool and very quick response!

**Comment by droidmonkey** [comment]
No problems, if you have anymore questions or suggestions let us know!
