### ISSUE TITLE
[FEATURE REQUEST] longer database inactivity timeout

### ISSUE THREAD

**Issue by samuraiii** [keepassxreboot/keepassxc#785]
Database inactivity timeout should offer longer timeout than 9999 seconds.

## Expected Behavior
It would be nice to support at least 24 hours in my opinion.
I would for example be glad for around 10 hours (my average workday).

## Current Behavior
db lock itself after less than 3 hours

## Possible Solution
Also it would be nice to have "human readable" time definition.

## Steps to Reproduce (for bugs)
Open
1. Tools
2. Security
3. tick Lock databases after inactivit of
4. get up to 9999 sec

**Comment by phoerious** [comment]
I'm sorry, but this is not what the feature is meant for. It is meant for locking after n seconds of _inactivity_, not for locking n seconds after the database was opened.
A setting of 24 hours would mean the database would never lock, _unless_ you open it in the morning, don't touch it at all for the rest of the day and then come back to work next morning a minute late.

You should rather enable locking when you lock your session.
