### ISSUE TITLE
Auto-Type in KeePassXC iteself is not working anymore

### ISSUE THREAD

**Issue by fischmir** [keepassxreboot/keepassxc#7852]
## Overview
My architecture looks something like this:

[**Database1**]

- Uses a very complex/long password

[**Database2**]

- The corresponding keyfile is saved on my local machine
- This Database contains ONLY the password for Database1

So, in my routine I can encrypt Database2 easily, because it uses a keyfile. When opening Database1 afterwards I used the Auto-Type feature of keepass to "transfer" the password for Database1 from Database2.

The main-issue is, that my Auto-Type - command [Alt + A] is not working for KeePassXC itself. Instead of asking for auto-type, the Menu-Item "Database" is selected

## Steps to Reproduce
[NOTE]: # Build architecture above
1. Create a new Database "Database1.kdbx" with passwort '123' (this database can remain empty)
2. Create a new Database "Database2.kdbx" with keyfile
3. Add a Auto-Type-record in Database2 for Database1
4. Close everything
5. Open Database2.kdbx by using the keyfile
6. Open Database1.kdbx and press [Alt + A]
7. INstead of the auto-type window, Menuitem "DataBase" is highlighted

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
I expect to open the Auto-Type Windows

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
MenuItem "Database" is selected

## Context

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION: 
**I worked successfully as described above in 2.6.6**. It is not working anymore after I updated today to:

KeePassXC - Version 2.7.1
Revision: 5916a8f

Qt 5.15.3
Diagnosemodus ist deaktiviert.

Betriebssystem: Windows 10 Version 2009
CPU-Architektur: x86_64
Kernel: winnt 10.0.22000

Aktivierte Erweiterungen:
- Auto-Type
- Browser-Integration
- SSH-Agent
- KeeShare
- YubiKey
- Schnelle Entsperrung

Kryptographische Bibliotheken:
- Botan 2.18.1

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows/Linux/macOS
Desktop Env: Gnome/KDE/XFCE/Mate/Cinnamon
Windowing System: X11/Wayland

**Comment by droidmonkey** [comment]
This is by design, use auto open feature. Check out the user guide for more information.

**Comment by fischmir** [comment]
Worked like a charm, thanks.
