### ISSUE TITLE
DB does not lock with computer when secret service confirmation popup is active

### ISSUE THREAD

**Issue by frikilax** [keepassxreboot/keepassxc#7853]
## Overview
When a Secret Service popup is active to request confirmation for a secret use by an external program, locking the session won't lock the database.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. activate Secret Service integration, with notifications to confirm use. Also activate DB lock with session lock.
2. store at least a secret for a program
3. unlock database, start program requesting the secret
4. popup opens to confirm secret access, DO NOT CONFIRM
5. lock computer
6. unlock computer, popup is still showing, DB is still unlocked

## Expected Behavior
When locking the session, even when a popup is open for secret request, DB should still be locked and secret request be canceled/denied.

## Actual Behavior
When secret request is shown and session is locked, DB stays unlocked and request stays active through lock, unlocking session shows request and unlocked DB.

## Context
secret service integration + test done with VSCode, with github account integration

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.0
Révision : d7a9ef4

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux (Ubuntu 20.04)
Desktop Env: KDE
Windowing System: X11

**Comment by droidmonkey** [comment]
@aetf need to program the prompts to listen for database lock signal and close them. 

Might be high time to finally put in place the hard close of all modal dialogs and force save the database.

**Comment by droidmonkey** [comment]
This is fixed in 2.7.8
