### ISSUE TITLE
Applicartion Freeze on DB unlock since 2.7.1

### ISSUE THREAD

**Issue by tofuSCHNITZEL** [keepassxreboot/keepassxc#7854]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

with 2.7.0 my main database and all the autoopen linked ones open just fine. as soons as I update to 2.7.1 and unlock my main db the application freezes and I have to kill it with task manager.
it happens on all my devices

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. unlock database - application freezes 

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
application unlocking database and linked database without hanging like it did in 2.7.0

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
it freezes after unlocking the main database

## Context
[NOTE]: # ( Give us any additional information you may have. )
I have nested autoopen entries with relative urls and the use of {DB_DIR} in the url field.
works fine with 2.7.0

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.1
Revision: 5916a8f

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 11

**Comment by phoerious** [comment]
What are your encryption settings?

**Comment by tofuSCHNITZEL** [comment]
some were KDBX3 but I switched them to KDBX4 but still the same issue...
I can see that 5 of 7 linked DBs have [locked] in the tab as well as the Main DB - so two of the linked dbs got unlocked

**Comment by phoerious** [comment]
Try switching to Argon2 with an appropriate number of rounds and memory filling.

**Comment by tofuSCHNITZEL** [comment]
where should I do that? I have only the slider with decryption time... why is it working with 2.7.0 and with 2.7.1 on my other computer?

EDIT: sorry it happens on both devices...

**Comment by droidmonkey** [comment]
What are the cpu specs of each computer

**Comment by tofuSCHNITZEL** [comment]
Processor	11th Gen Intel(R) Core(TM) i5-1130G7 @ 1.10GHz, 1805 Mhz, 4 Core(s), 8 Logical Processor(s)
and
Processor	Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz, 3600 Mhz, 8 Core(s), 16 Logical Processor(s)

**Comment by Xeevis** [comment]
I don't think database is the culprit, I suspect it has something to do with configuration incompatibility between versions. After upgrading to 2.7.1 I had it freezing even when trying to open settings with no database loaded, also when trying to open database, downgrade to 2.7.0 would fix it. So I went to remove configuration files to have a clean slate and now 2.7.1 is working as well with all my databases.

Rename following folders (don't delete yet in case droidmonkey wants to debug the cause or in case this doesn't help)
```
%LocalAppData%\KeePassXC
%AppData%\KeePassXC
```

**Comment by droidmonkey** [comment]
Someone else had a config issue but we literally didn't change any code for configuration settings between versions. You're welcome to send your previous configuration files to team@keepassxc.org or upload them here.

**Comment by tofuSCHNITZEL** [comment]
okay I will try to reset the config and send the old one to you.

**Comment by JohnLGalt** [comment]
By chance do you have "Always on top" enabled for KPXC? If so, then the Windows Hello popup won't come in front of KPCX, and you'll never see it if KPXC is positioned in the right spot (usually close to center of your monitor).

Learned this the hard way when I accidentally enabled Always on top via shortcut.

**Comment by tofuSCHNITZEL** [comment]
no, this option was not enabled and quick unlock was disabled...

I had to delete
%LocalAppData%\KeePassXC

but as long as the ini in local was missing the
UsePageant=false
under
[SSHAgent]

it kept freezing on startup

so here is my current section:
```
[SSHAgent]
UseOpenSSH=true
Enabled=true
UsePageant=false
```

**Comment by droidmonkey** [comment]
@hifi see above 😑

**Comment by hifi** [comment]
Don't know what to say. Seems KeePassXC trying to find Pageant just freezes on that system.

Maybe there's a timeout missing from somewhere but that's really weird behavior. The only change between 2.7.0 and 2.7.1 is that Pageant is on by default and I would have expected the state of it would be in the ini file from 2.6/2.7 and not missing completely.
