### ISSUE TITLE
Corrupt download

### ISSUE THREAD

**Issue by NonoyaB** [keepassxreboot/keepassxc#7855]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
Mac download corrupted, Mac OS unable to open because it's corrupted

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. download
2. extract/copy to applications
3. attempt to start

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
app should start

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
app does not start, instead get system dialog indicating app is corrupted

## Context
[NOTE]: # ( Give us any additional information you may have. )
Downloaded several times, same result.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION
Revision: REVISION

latest

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows/Linux/macOS
Desktop Env: Gnome/KDE/XFCE/Mate/Cinnamon
Windowing System: X11/Wayland

**Comment by phoerious** [comment]
Kill any remaining keepassxc-proxy processes and try again.

**Comment by NonoyaB** [comment]
along with reboot, working now. thx.
