### ISSUE TITLE
Suggestion: Auto-type into a VM

### ISSUE THREAD

**Issue by nlguerra2003** [keepassxreboot/keepassxc#7858]
## Summary
That's it. I'd love to be able to use auto-type with VMware, for example. I've already tried to use auto-type but it doesn't work at all (the VM doesn't even get the inputs, it seems). Is this something you can contribute to or is it more VMware-related?

## Context
I work with VMware Workstation and it would be great for me to be able to use actual passwords for logins (to date I'm using crappy passwords or even the default ones for non-critical systems).

**Comment by droidmonkey** [comment]
Add `{MODE=VIRTUAL}` as the first block in a custom sequence or choose "Type using Virtual Keyboard" from the Auto-Type selection dialog. See more info in the user guide. (You need 2.7.x to use this feature)

**Comment by sebma** [comment]
@droidmonkey My Auto-type sequence to login into VMware Workstation VM's last user is `{MODE=VIRTUAL}{PASSWORD}{ENTER}` and it works just fine.

I also wanted to add CTRL+ALT+INSERT to unlock the VM with this Auto-type sequence `{MODE=VIRTUAL}^%{INSERT}{PASSWORD}{ENTER}` but that does not work.

How can I do this ?

**Comment by droidmonkey** [comment]
CTRL+ALT+INSERT is actually intercepted by the VMWare client and then transferred to the guest machine as CTRL+ALT+DELETE. You could try moving the mode virtual to _after_ the INSERT, but it might not be possible.
