### ISSUE TITLE
Application Error (memory dump) when adding a tag

### ISSUE THREAD

**Issue by scotgabriel** [keepassxreboot/keepassxc#7859]
## Overview
If I try to add any tags to an entry that has a REF(link) for the username and password, it immediately crashes and errors out.

## Steps to Reproduce
1. Clone an existing entry that has a username and a password entry (check mark "Replace Username and Password with References)
2. Open the new entry
3. Add a tag to the entry
4. crashes when I try to save

## Expected Behavior
Expected to be able to tag any entry in my db

## Actual Behavior
Application Error

## Context
I have tested on 2 different PC's, same results on both (same version of KeePassXC and windows on both)

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.0
Revision: d7a9ef4

Qt 5.15.3
Debugging mode is disabled.

Operating system: Windows 10 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.22000

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 2.18.1

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows
Desktop Env: Default
Windowing System: Default

**Comment by droidmonkey** [comment]
Update to 2.7.1

**Comment by scotgabriel** [comment]
I thought I was at the latest version, upgrading resolved.. thank you for the QUICK response!
