### ISSUE TITLE
Some buttons below it don't work on Ubuntu 22 beta

### ISSUE THREAD

**Issue by tinkermakar** [keepassxreboot/keepassxc#7861]
## Overview

`Open existing database` and the 3 other buttons below it don't work on Ubuntu 22 beta

## Steps to Reproduce

1. Install on Ubuntu 22 beta
2. Open the app
3. Press `Open Existing database`

## Expected Behavior

Upload menu pops up

## Actual Behavior

Nothing happens

## Context

OS: Ubuntu 22 beta
Desktop: Gnome 42, X11

KeePassXC - Version 2.7.1
Revision: 5916a8f
Distribution: Snap

Qt 5.15.3
Debugging mode is disabled.

Operating system: Ubuntu Core 20
CPU architecture: x86_64
Kernel: linux 5.15.0-25-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

**Comment by droidmonkey** [comment]
Tracked in another issue. Make sure you have xdg-desktop-portal and xdg-desktop-portal-gtk installed.
