### ISSUE TITLE
keepassxc-cli not found

### ISSUE THREAD

**Issue by f-x1-1** [keepassxreboot/keepassxc#7862]
I have keepassxc installed on my mac, I'm trying to integrate keepassxc with the Alfred app however it keeps displaying the following error "keepassxc-cli not found", also I have tried to find it in the finder, _**keepassxc-CLI**_ cant be found.

**Comment by droidmonkey** [comment]
How installed? What version?

**Comment by f-x1-1** [comment]
macOS: 12.3
Keepassxc: 2.7.1

I installed keepassxc from the official website.

**Comment by 2BeeOrNot** [comment]
It's in the app package. In finder right click on KeePassXC.app -> Show Package Contents
![KPXCcli](https://user-images.githubusercontent.com/63317977/162858470-564fe137-0bb9-4ee6-8af0-d5c5a2934d84.jpg)

In Terminal /Applications/keepassxc.app/contents/macos/keepassxc-cli
will display help screen

macOS: 12.3.1
KPXC: 2.7.1
