### ISSUE TITLE
Entropy doesn't change / passphrase

### ISSUE THREAD

**Issue by thyxNY** [keepassxreboot/keepassxc#7863]
After changing generated password entropy is still the same (passphrase).

## Steps to Reproduce
1. Generate a new password (passphrase)
2. Change generated password - entropy doesn't change
3. Click "Regenerate password" to generate a new passphrase - new password is generated but entropy doesn't change

![obraz](https://user-images.githubusercontent.com/73193311/162811583-07f19ca6-a450-4617-a7d8-29255665883b.png)

KeePassXC - Version 2.7.1
Revision: 5916a8f

Qt 5.15.3
Debugging mode is disabled.

Operating system: Windows 10 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.19044

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 2.18.1

**Comment by droidmonkey** [comment]
Passphrase is not a password. Entropy is calculated based on the number of distinct words chosen.
