### ISSUE TITLE
Upon startup login KeypassXC 2.7.1 Mac keeps asking for database

### ISSUE THREAD

**Issue by JayK84** [keepassxreboot/keepassxc#7865]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Shutdown computer
2. Turn on and login
3. Keepass loads at startup but asks to open database

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Automatically open program without having to open database

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Program upon startup asks to find and open a database

## Context
[NOTE]: # ( Give us any additional information you may have. )
This was not an issue on previous version KeePassXC 2.7.0 Mac

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.1
Revision: 5916a8f

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS
Desktop Env: NA
Windowing System: NA

**Comment by droidmonkey** [comment]
Did you turn off the option to remember previously opened databases?

**Comment by JayK84** [comment]
No I kept it the same. I installed the new version over the old one. Also
password strength and password columns have to keep getting re-enabled to
view.

**Comment by droidmonkey** [comment]
You have a corruption or something is being reset in your application configuration files. Delete the contents of ~/Library/Caches/KeePassXC and ~/Library/Application Support/KeePassXC

**Comment by JayK84** [comment]
Thanks that worked you can close the bug ticket

On Monday, April 11, 2022, Jonathan White ***@***.***> wrote:
> You have a corruption or something is being reset in your application
data folder. Delete the contents of ~/Library/Caches/KeePassXC and
~/Library/Application Support/KeePassXC
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.<
https://ci5.googleusercontent.com/proxy/-Xsc4g8hPvIgYIe7oWYwRSEib3b1ORAft4onRTtDv84l1JGS_5sPHWCJfjmLawb5aDBZrqcGa3QG2sMJ7__vroGt7S75j32LcmvWHiWfnub539h1ex-GfHjmG2y0anJJeCIFo5BbqCzQz5zGhwUu6vqh6nRFFJDnRg7dyCPbVwZYxH3U6tWm7kwDgQUOX3kyMe8_c1HzusM_tvpbFcblyc7TTas628T1q-txy8LPVQ=s0-d-e1-ft#https://github.com/notifications/beacon/AYVLJZDZYBEIANPM264IBCDVESWWBA5CNFSM5TEPHDYKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOIFHL54Y.gif>Message
ID: ***@***.***>

-- 
Jay Karl
