### ISSUE TITLE
Memory fault when cloning

### ISSUE THREAD

**Issue by nilskp** [keepassxreboot/keepassxc#7866]
## Overview
Whenever I try to clone an entry with references, it crashes on a memory fault.

## Steps to Reproduce
1. Clone entry
2. Check username/password as references
3. Uncheck copy history

## Expected Behavior
Not crash

## Actual Behavior
![image](https://user-images.githubusercontent.com/74843/162846225-29e358a2-f1c4-4167-a76b-023610b341bb.png)

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.0
Revision: d7a9ef4

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 10

**Comment by droidmonkey** [comment]
Update to 2.7.1
