### ISSUE TITLE
When copying from KeepassXC UTF BOM character is copied along with the password.

### ISSUE THREAD

**Issue by marat-turaev** [keepassxreboot/keepassxc#787]
When copying (for example) a password from KeepassXC on Mac OS, UTF-8 BOM gets copied into the clipboard along with the password. Luckily many apps sanitize clipboard and trim this extra BOM, but looks like java/swing apps (for example Intellij based) are pasting password along with BOM instead of just a password and user gets incorrect password. 

This may be related to the issue (not sure): https://bugreports.qt.io/browse/QTBUG-61562

Tested on KeePassXC - 2.2.0 Mac OS 10.11

**Comment by phoerious** [comment]
Well, as you already found out, this is a Qt bug and we can't really do anything about it. The only workaround would probably be compiling against Qt 5.8 instead of 5.9.
