### ISSUE TITLE
missing zlib1.dll

### ISSUE THREAD

**Issue by Moth-Tolias** [keepassxreboot/keepassxc#7870]
when installing via the "legacy" msi on windows 8.1, i get the following error:
"The program can't start because zlib1 is missing from your computer. Try resinstalling the program to fix this problem."

## Steps to Reproduce
1. install keepassXC on windows 8.1
2. observe that the installer completes successfully, and check "launch keepassXC"
3. observe that keepassXC fails to start and instead displays the aforementioned error

## Expected Behavior
keepassXC starts normally.

## Actual Behavior
keepassXC fails to start and instead displays the aforementioned error,

KeePassXC 2.7.1
Operating System: Windows 8.1

**Comment by droidmonkey** [comment]
Reinstall the program or use the portable version. The dll is in there

**Comment by Moth-Tolias** [comment]
huh, you're right. on a second attempt at install it worked. i wonder what went wrong the first time?

terribly sorry for the inconvenience!

**Comment by dgasaway** [comment]
FYI, the same just happened to me.  I upgraded from 2.6.x to 2.7.4, there was no zlib1.dll in the installation folder.  Found this bug report and ran the installer again, chose Repair, and now there is a zlib1.dll.
