### ISSUE TITLE
“Warning: Failed to prevent screenshots on a top level window!”

### ISSUE THREAD

**Issue by Balbaroo** [keepassxreboot/keepassxc#7872]
## Overview
Whenever the KeePassXC window is brought to the front, I get the following message: “Warning: Failed to prevent screenshots on a top level window!”

## Expected Behavior
No warning message.

## Actual Behavior
I get the warning message.

## Context
This behaviour is happening since 2.7.0.

KeePassXC - Version 2.7.1
Revision: 5916a8f

Operating System: Windows 7

**Comment by phoerious** [comment]
Windows 7 is not supported anymore. Strange that you are even able to run it in the first place. Are you using the legacy build? It's quite possible that you will see such errors with that build.

**Comment by Balbaroo** [comment]
Yes, I did use the legacy installer (64-bit, Windows 7/8/8.1).

My concern is that I’m not sure what to think about the warning, since it’s a security feature, i.e. _prevent screen capture_.
Is it possible that something malicious is blocking the feature?
I know there’s probably a very small percentage of Windows 7 users here, but still, I waited a few weeks, and no one seems to have this error, or the concern that should come with it.

Ultimately, I’m just trying to know if it’s a bug – or expected error – or something more serious on my side.

**Comment by phoerious** [comment]
It could also simply not be supported on Windows 7. Maybe @droidmonkey can tell you more.
If that's the case, you can probably get rid of the warning by starting KeePassXC with `--allow-screencapture`. https://keepassxc.org/docs/KeePassXC_UserGuide.html#_screenshot_security

**Comment by droidmonkey** [comment]
Windows 7 supports the function call, but not the security behavior. The blanking of the window contents is only supported on Windows 10 2004 and higher. You might have something hooking onto your top level windows that is intercepting calls which would cause this to return false. Use the command line flag to suppress the warning or upgrade your windows to a supported version.

**Comment by Balbaroo** [comment]
Thanks for the explanation, [@droidmonkey](https://github.com/droidmonkey).
So, as I understand it, even without the warning message, the capture protection is not working on Windows 7. At least, I’m being incidentally warned, but it is more specific to my case.

I’m sorry to insist – I’ll try to reach other Win 7/KeePassXC users about the warning –, but might this interception of calls have anything to do with malware actually taking screenshots on my system, or is it probably just a wider and more coincidental software interaction?
(FYI, I get the same behaviour in Windows safe mode.)

**Comment by alex-kerner-ext-orion** [comment]
@droidmonkey 
“Warning: Failed to prevent screenshots on a top level window!” - this is a very annoying window!
`--allow-screencapture` - it would be great to add this option to the visual settings.

**Comment by droidmonkey** [comment]
That's the point 😉

**Comment by WNG555** [comment]
Late to the party! Just thought I'd add to this for the original poster.....
I just updated to 2.7x with the legacy installer for Win 7, as you did. And began getting this same warning message flash up. Had the same concerns as you. But it seems to be consistent behavior, and I believe it's due to the explanation provided. So thank you for clarifying what's happening.
