### ISSUE TITLE
Adding unlock option to Keeshare

### ISSUE THREAD

**Issue by lfirewall1243** [keepassxreboot/keepassxc#7873]
Overview
KeepassXC is looping endless when a Keeshare file is openend on more than one Instance. Maybe an option which makes it possible to use Keeshare only on unlock of the Database would be nice.

Expected Behavior
Keeshare syncs without looping

Actual Behavior

Context

**Comment by droidmonkey** [comment]
Turn off auto saves and disable the circular keeshare reference you have set up. This is being tracked in another issue.
