### ISSUE TITLE
[2.7.1-Linux] builds fails with minizip 2.8.9, build success with minizip 1.2

### ISSUE THREAD

**Issue by Germano0** [keepassxreboot/keepassxc#7874]
hello, keepassxc co-maintainer in Fedora/RHEL/CentOS Stream here.
In ticket https://github.com/keepassxreboot/keepassxc/issues/7633 it has been fixed a problem with minizip 3.x and Fedora > 36
Hereby instead I would like to report the build failure on RHEL 8 / CentOS Stream 8, with `minizip 2.8.9` and `zlib 1.2.11`

```
/builddir/build/BUILD/keepassxc-2.7.1/src/keeshare/ShareExport.cpp: In function 'bool {anonymous}::writeZipFile(void*, const QString&, const QByteArray&)':
/builddir/build/BUILD/keepassxc-2.7.1/src/keeshare/ShareExport.cpp:126:31: error: 'Z_DEFLATED' was not declared in this scope
                               Z_DEFLATED,
                               ^~~~~~~~~~
/builddir/build/BUILD/keepassxc-2.7.1/src/keeshare/ShareExport.cpp:127:31: error: 'Z_BEST_COMPRESSION' was not declared in this scope
                               Z_BEST_COMPRESSION,
                               ^~~~~~~~~~~~~~~~~~
/builddir/build/BUILD/keepassxc-2.7.1/src/keeshare/ShareExport.cpp:127:31: note: suggested alternative: 'BOTAN_HAS_COMPRESSION'
                               Z_BEST_COMPRESSION,
                               ^~~~~~~~~~~~~~~~~~
                               BOTAN_HAS_COMPRESSION
/builddir/build/BUILD/keepassxc-2.7.1/src/keeshare/ShareExport.cpp:118:9: error: 'zipOpenNewFileInZip64' was not declared in this scope
         zipOpenNewFileInZip64(zf,
         ^~~~~~~~~~~~~~~~~~~~~
/builddir/build/BUILD/keepassxc-2.7.1/src/keeshare/ShareExport.cpp:118:9: note: suggested alternative: 'zipOpenNewFileInZip4'
         zipOpenNewFileInZip64(zf,
         ^~~~~~~~~~~~~~~~~~~~~
         zipOpenNewFileInZip4
```
from https://kojipkgs.fedoraproject.org//work/tasks/1617/85491617/build.log
all logs at https://koji.fedoraproject.org/koji/taskinfo?taskID=85491617

Instead, forcing the build against `minizip 1.2`, causes the build to complete without problems
logs: https://download.copr.fedorainfracloud.org/results/germano/keepassxc_el8_minizip1.2/epel-8-x86_64/04196363-keepassxc/

**Comment by droidmonkey** [comment]
Minizip 2.8.9 is actually minizip-ng...  totally different project. Clearly my trigger on whether it is using minizip-ng or not is not sufficient for all versions of minizip-ng. They neglected to define an MINIZIP-NG define....
