### ISSUE TITLE
Password showing as file name

### ISSUE THREAD

**Issue by clr100** [keepassxreboot/keepassxc#7875]
## Overview
I current use two files with KeePassXC. One file works fine. When I open the second file and enter the password, the file opens fine but the file name in the tab and in the top left next to the KeePassXC logo changes to the revealed password. So if someone were looking over my shoulder or if I shared a screenshot it would should the password for the file rather than the file name.

## Steps to Reproduce
Simply enter the password to open the file. Doesn't matter whether I double click the file name in Windows Explorer or use the drop down recently used files or click the tab with the file name while I am in the other file. Always same behavior.

## Expected Behavior
Should still show the actual file name and not the password.

## Actual Behavior
Password is revealed as the file name.

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.1

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 10

**Comment by droidmonkey** [comment]
You set your database name to your password for some reason. Go to Database -> Database Settings... then change the database name.

**Comment by clr100** [comment]
Thanks. Not sure how I managed to do that.
