### ISSUE TITLE
[feature request] specific per database auto-lock time out

### ISSUE THREAD

**Issue by Freeedim** [keepassxreboot/keepassxc#7879]
Hi there!

Thanks for the amazing job on KeepassXC.

I would love to be able to set a specific idle time before auto-lock, different for each database.

I know I will use a database A like 5 or 6 times in the day and would like it to remain open the whole day because it has a very long password (I cannot change or remove it for several reasons). On the other hand, I have another database B that has more sensitive data, and I would rather have that one auto-locked after 10 minutes.

While we're at it, it would also be great to be able to schedule auto-lock at a given time. For example, whatever the time is when I open my database A (be it 8am, 11am or something else), I would like it to auto-lock at 6pm; and in case the computer was sleeping or hibernating at 6pm, I would like database A to auto-lock whenever the computer resumes.

Thanks for reading.

**Comment by droidmonkey** [comment]
Duplicate to per database settings request

**Comment by DanielSiepmann** [comment]
To ease finding the issue, I guess you talk about https://github.com/keepassxreboot/keepassxc/issues/2224 ?
