### ISSUE TITLE
[Feature request] having different protections and ways to unlock a database

### ISSUE THREAD

**Issue by Freeedim** [keepassxreboot/keepassxc#7880]
## Summary
I would like to be able to open a database with, for example, password A, **or** passphrase B, **or** password C + key file K.key, **or** Yubikey 1/slot 1 etc.

## Examples
1. A same database would be unlockable by my Yubikey on a daily basis, but if I forget/lose/break my Yubikey, I have a backup passphrase that I know by heart, very long so inconvenient for daily use.
2. A key file is shared with users through a cloud to access a Keepass Share database (fully local on their computer or on another cloud), but if they have a problem connecting to the cloud and getting the key file, they can use a backup password/passphrase, or their manager's Yubikey, to access the keyring.
3. A user cannot access their unlock means (forgot password, forgot their Yubikey, destroyed or altered their key file...). If their manager's, IT's or colleague's password could be set as the backup unlock means, problem would be solved.

## Context
I guess we can find a workaround by playing with Keepass Share and have a shared whole database recovered by alternative means through the database receiving the shared database.

But I think it would be more convenient, elegant and neat to have it handled directly as a database security feature. For example, in the screen where the protections are set, currently only in a "AND" modality implying that all of the protections that are set must be unlocked to open the database, there could be a "OR" modality implying that either one group of "AND" protections or another would be required to unlock the database.

Thanks for reading

**Comment by droidmonkey** [comment]
We will not support this, it has been requested before, it is incompatible with keepass format.
