### ISSUE TITLE
Copy/paste notes to winword/outlook on windows

### ISSUE THREAD

**Issue by thyxNY** [keepassxreboot/keepassxc#7882]
Copy notes from the entry edit work correctly.
Copy notes from the entry preview adds strange signs (PSEP).

## Examples
![obraz](https://user-images.githubusercontent.com/73193311/163131633-bbbf436c-9c10-4d8c-b52e-83b260ce1c40.png)

## Context
Can CTRL-C work like on edit entry (without PSEP) ?

## Debug info
KeePassXC - Version 2.7.1
Revision: 5916a8f

Qt 5.15.3
Debugging mode is disabled.

Operating system: Windows 10 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.19044

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 2.18.1

**Comment by droidmonkey** [comment]
#7825
