### ISSUE TITLE
Insecure quick unlock feature using Windows Hello

### ISSUE THREAD

**Issue by DU-student** [keepassxreboot/keepassxc#7886]
## Overview

Password database improperly unlocks with quick unlock feature enabled bypassing security restrictions. 

## Steps to Reproduce

1. On Windows, enable security convenience feature, "Enable database quick unlock (Touch ID/Windows Hello)"
2. Lock database
3. Unlock database with credentials
4. When prompted by Windows Security window to verify identity, select "Cancel"

## Expected Behavior

Expects failed biometric authentication to default to a secure state and deny access to the password database when the feature is enabled. 

## Actual Behavior

With the "database quick unlock" feature enabled allows unauthorized access to password databases which would otherwise be restricted with Windows security biometrics. Applies to Windows Hello Face and PIN; not tested with Fingerprint. 

## Context

Bypass tested using the following credential methods: password only, password with key file, password with security key, password with key file and security key, key file only, key file and security key, and security only.

## Debug info from Help
KeePassXC - Version 2.7.1
Revision: 5916a8f

Qt 5.15.3
Debugging mode is disabled.

Operating system: Windows 10 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.19044

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 2.18.1

## Environment
Operating System: Windows 10 Pro, Version 21H2, Build 19044.1620

**Comment by droidmonkey** [comment]
Not correct. When you click cancel on the first prompt that means we won't setup quick unlock. Lock your database after that and you'll have to re enter your credentials as if it was the first time opening the database. 

How do you bypass authentication by providing your credentials?

**Comment by droidmonkey** [comment]
Please read: https://keepassxc.org/docs/KeePassXC_UserGuide.html#_quick_unlock

**Comment by phoerious** [comment]
The first prompt keeps confusing users. We need to rethink the flow here to avoid such misunderstandings.

**Comment by michaelk83** [comment]
I agree with others that it should be an opt-in. It's a convenience feature, which doesn't add anything to security, AIU. When the user enables it, you can immediately trigger that first prompt. It should be less confusing in that context. You can add some text near that setting, so the user would expect the prompt (or if possible, adjust the prompt text).
