### ISSUE TITLE
Allow adding global attributes in Entries through SETTINGS

### ISSUE THREAD

**Issue by 4world** [keepassxreboot/keepassxc#7887]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )

Login credentials often have multiple additional associated pieces of information such as:
  MOBILE NUMBER
  EMAIL ID
  ASSOCIATED PHYSICAL ADDRESS
  SECRET QUESTION & ITS ANSWER
  BANK ACCOUNT NO.
  CUSTOMER ID (different from account number)
etc.  

Currently, I have to click "ADVANCED" and then create Additional Attributes for each of my hundreds of entries for even common attributes like Mobile Number or Email.   If SETTINGS could allow creation of Global Attributes, these empty attributes would appear in all New Entries so only the unique value would need to be typed.

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )

Bank websites, crypto sites, credit card sites, etc. have lots of additional info associated with the account.  Sometimes, a Username can use either mobile number or email ID or a user ID.  It would be excellent to have all this in KeePassXC at one place -- I currently use a password protected Excel file to store all this info.

Current version of KeePassXC can store additional attributes through "Advanced" tab but one has to create even common attributes for each entry.  Just let users put their favorite Attributes under Settings so these would appear in all New entries.

**Comment by droidmonkey** [comment]
Tracked under the custom entry layout issue

**Comment by 4world** [comment]
Hi Jonathan,

I read a bit of [#863](https://github.com/keepassxreboot/keepassxc/issues/863) so a quick partial solution that would satisfy a lot of folks and not cause you too much development time is like the example sketch below ![attached example sketch.](https://user-images.githubusercontent.com/8074215/163293399-df8eeace-e6e8-434b-97fe-fc5779fa99fd.png)

Respectful salutations to contributors like yourself who volunteer their precious time for community -- your type of work is what will help the world reduce income and wealth gaps (opposite to what corporations are doing).  

Please acknowledge this message if you can since I don't know if you will get it because this ticket is marked as closed.  Thank you again for all your efforts.

- Ashim Jain

**Comment by droidmonkey** [comment]
Thank you for the suggestion, that is close to what I am planning for my eventual work on this feature. Where that works, it also "pollutes" every entry with those additional attributes. Rest easy in knowing I am gearing up for this feature.

**Comment by 4world** [comment]
It won't pollute every entry the way I described it.  Whatever is in the textbox gets "copied" ONLY to new entries created after changes to this part of Settings.  It does not affect entries already created before.

**Comment by droidmonkey** [comment]
I missed a new in there, meant to say every NEW entry.
