### ISSUE TITLE
Attachements will not open

### ISSUE THREAD

**Issue by cyclops1530** [keepassxreboot/keepassxc#7888]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

I used to be able to open an attachment for a keepassxc entry by simply double clicking on it.  This doesn't work anymore.  Neither does selecting the attachment and pressing the open button

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )

refer to overview

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

refer to overview

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

nothing happens

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.1
Revision: 5916a8f
Distribution: Snap

Qt 5.15.3
Debugging mode is disabled.

Operating system: Ubuntu Core 20
CPU architecture: x86_64
Kernel: linux 5.13.0-39-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.12.1

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux - Ubuntu 20.04
Desktop Env: Gnome
Windowing System: ubuntu/gnome default

**Comment by droidmonkey** [comment]
Known issue with snap on some configurations, tracked in another issue ticket. Use the appimage in the interim.
