### ISSUE TITLE
Password generator - support HEX-only character type

### ISSUE THREAD

**Issue by sim0nx** [keepassxreboot/keepassxc#789]
## Expected Behavior

There are some use cases where one is required to generate a password which only consists of HEX characters.
When generating a password in keepassxc, there should be a button with as label HEX, and if selected generates a password with only HEX characters.

## Current Behavior

Currently this is not at all possible thus one has to generate the password using some other tool.

## Possible Solution

When generating a password in keepassxc, there should be a button with as label HEX, and if selected generates a password with only HEX characters.

## Context

Generating OTP seeds is an example application for this.

**Comment by chuinul** [comment]
This is a good idea, but :

- I understand from #820 that the main goal is to keep the password generator as light as possible.
- I think a 'HEX' button is not a good solution. It would break the "paradigm" of the password generator where each button represent a class of characters that can be combined, and not already a combination of (sub)classes of characters. 
- We have to give the choice of generating lowercased or uppercased hexadecimal password (there are probably plenty of buggy and/or uselessly strict websites and softwares...).

I tried to implement something fulfilling those constrains (see screenshots). Do you think this is acceptable?

![image](https://user-images.githubusercontent.com/25458217/32845881-3028fa00-ca26-11e7-806d-317dbb34d22d.png)
![image](https://user-images.githubusercontent.com/25458217/32845960-614220b2-ca26-11e7-986b-5cf6311aa30a.png)

**Comment by sim0nx** [comment]
Yes I definitely think that your suggestion is an acceptable solution :-). Thank you!

IMHO you can leave the "upper/lower" radio buttons out, the "A-Z" "a-z" buttons make them redundant.

**Comment by droidmonkey** [comment]
Implemented in #1841 for release in 2.4

**Comment by sim0nx** [comment]
Great news! Thank you!
