### ISSUE TITLE
 unable to unlock kdbx file originated from keepass 2 running on windows in ubuntu keepassxc

### ISSUE THREAD

**Issue by ghost** [keepassxreboot/keepassxc#7891]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
so I started using keepass 2 on windows yesterday, I have ubuntu in dual boot, I had the kbdx files in a pendrive, which I tried to use in keepassxc in ubuntu, the kdbx file required a master password and a key to unlock, which I have in my pendrive and I have the password noted on a piece of paper kept inside my locked, I tried to unlock the data base using the .keyx file and the password in Ubuntu keepassxc and it lead to an error saying *view screen shot*
![image](https://user-images.githubusercontent.com/103628139/163332041-45b805e2-c2a2-4004-839f-cbf132a5eb53.png)
this says invalid credentials but the .keyx file and the same password is able to unlock that same database in windows keepass 2.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. in windows use keepass 2 to create a database with a key file and a master pass
2. copy the respective kdbx and keyx file in a pendrive
3. try to use the same kdbx and keyx file in ubuntu keepassxc along with the same master password
4.error displayed as in screenshot provided in Overview

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
to unlock the database and give access to the saved credentials 

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
throwing error saying invalid credentials and that database might be corrupt

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC in ubuntu- VERSION 2.4.3 
KeePass 2 in windows- VERSION 2.50 (64 bit)

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows/Linux

**Comment by droidmonkey** [comment]
Keepassxc must be newer than 2.6.0 to support keyx

**Comment by ghost** [comment]
> Keepassxc must be newer than 2.6.0 to support keyx

thank you so much, the issue is resovled after installing keepass 2.7.1
but it's weird cause I installed keepass using "apt install keepassxc" this morning, it should have been the latest package.

**Comment by droidmonkey** [comment]
Hahaha welcome to Ubuntu
