### ISSUE TITLE
Enable escape key to cancel Quick Unlock

### ISSUE THREAD

**Issue by OlivierMary** [keepassxreboot/keepassxc#7892]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )

Hi,

## Problem
In Quick Unlock database and Unlock Database if TouchId is enabled we have to click with mouse on "Cancel" button to get password input text if TouchId is inaccessible for any reason.

## Example
- If I use my laptop open all good I have access to TouchId and unlock faster than enter password.

- But, if I use my mac/laptop with external keyboard and screen I didn't have access to TouchId, cause I close my laptop.
So I have to left my keyboard to take the mouse and go click on cancel, and go back to keyboard to enter my password.

## Some proposals
- Keep both section in popup at same time by default (TouchId and 'Normal' unlock)
- Same but with option in preferences if needed
- ESC can switch TouchId to 'Normal' unlock, if already in 'Normal' unlock like actually that close popup

**Comment by droidmonkey** [comment]
Does pressing TAB then Enter (maybe space) not work for you?

**Comment by michaelk83** [comment]
It is usually expected that Esc triggers the Cancel button in dialogs.

**Comment by OlivierMary** [comment]
@droidmonkey 

Hum, that work but not intuitive.

@michaelk83 +1

**Comment by koichirose** [comment]
Possibly related: in my opinion it shouldn't even show the option to unlock with TouchID if the laptop lid is closed.

**Comment by OlivierMary** [comment]
@koichirose yes but don't know if possible to check it

**Comment by nanaya** [comment]
Not specifically about touchid but I think it would be nice if the lock screen gives option between quick unlock and password unlock, and keeping the quick unlock option even after unlocking using password.

In my use case it's for when I access keepassxc through remote desktop (windows) I need to use password unlock but when I'm back at my desktop I'd like to be able to use quick unlock without having to reenter the password again.

**Comment by foss-** [comment]
> Possibly related: in my opinion it shouldn't even show the option to unlock with TouchID if the laptop lid is closed.

Agreed. Detection whether lid is open or closed is possible and this 1Password unlock dialog instantly reflected the changed state. Screenshot is with lid closed. Once the lid is opened TouchID option is added back to the dialog.
![1](https://github.com/keepassxreboot/keepassxc/assets/5708172/9eb38858-95bd-4164-94c8-535de0418620)

**Comment by droidmonkey** [comment]
That is tracked on a separate issue. Thank you

**Comment by foss-** [comment]
Sorry, you are right. For reference: https://github.com/keepassxreboot/keepassxc/issues/8105
