### ISSUE TITLE
Notes field is not resized to full window size

### ISSUE THREAD

**Issue by thyxNY** [keepassxreboot/keepassxc#7893]
## Overview
Notes field is preview not resized to full window size

## Steps to Reproduce
1. Find entry with long notes field preview
2. Resize KeePassXC window

![obraz](https://user-images.githubusercontent.com/73193311/163344555-ff364908-af96-46a9-8681-3ca1e49b6b63.png)

[NOTE]:
KeePassXC - Version 2.7.1
Revision: 5916a8f

Qt 5.15.3
Debugging mode is disabled.

Operating system: Windows 10 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.19044

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 2.18.1

**Comment by thyxNY** [comment]
@droidmonkey Could you give me the issue (duplicate) number? Could it be in next KeePassXC 2.7.2 version?

**Comment by droidmonkey** [comment]
Please search its a recent issue
