### ISSUE TITLE
Auto-type moves window to other virtual desktop; Xfce4

### ISSUE THREAD

**Issue by Simplenuity** [keepassxreboot/keepassxc#7895]
## Overview
I've several desktops configured in Xfce. When I initiate auto-type in Keepassxc to transfer the content of two Keepassxc fields to an application window that is not located on the last virtual desktop then the window gets moved by two desktops to the right. If the window is located on the last virtual desktop it doesn't get moved anymore.

## Steps to Reproduce
1. Open a text editor or a suitable website NOT located on the last virtual desktop
2. Chose a suitable entry in Keepassxc and initiate auto-type

## Expected Behavior
The information of the two Keepassxc fields get typed into the selected window while the window remains on the original desktop.

## Actual Behavior
With each field typed the window is moved one desktop to the right

## Context

KeePassXC - Version 2.7.1
Revision: 5916a8f

Operating System: Linux Lite 4.x (Ubuntu 16.04 based)
Desktop Env: XFCE 4.12.4
Windowing System: X11

**Comment by droidmonkey** [comment]
Sounds like an xfce bug to me. We just ask for the window to be put into focus.

**Comment by Simplenuity** [comment]
Thanks for the quick reply. 
I'll follow up [on their side](https://gitlab.xfce.org/xfce/xfdesktop/-/issues/186) and report back if I hear back from them.
