### ISSUE TITLE
Suggestion UX : placement of buttons for large screen users : put them at left side of things

### ISSUE THREAD

**Issue by Madydri** [keepassxreboot/keepassxc#7900]
## Summary
I would suggest an option / or a choice to put buttons more to the left of the fields / screens, and not at the right.

## Examples
- To see the password (left in the field), you have to go far right to find the button for it
- To generate a password, idem
- to save a change in a card, you have to go far-right + far-botton... (even better)
- all select-list buttons are ... on the right

## Context
On large screens, I experience that as user I have to make big mouse movements to go from a card edit (mostly left-top) to the "OK - CANCEL - APPLY" buttons (right-bottom)

**Comment by droidmonkey** [comment]
Couple of keyboard shortcuts to help you out in the meantime:

Ctrl + H - Show/Hide password
Ctrl + G - Generate password
Ctrl + Enter - Save entry changes

**Comment by Madydri** [comment]
Indeed, I would use that more, and use a smaller screen, or reposition the window ;-) (i don't want to be sinic : this is indeed better as asking for a UX rewrite !)
Thanks.

**Comment by Madydri** [comment]
Intermediate could be to insert some Tool-tips (as there are so much apps with different shortcuts that it is not always easy to memorize them all....)

**Comment by droidmonkey** [comment]
There should be tooltips on the password field buttons

**Comment by Madydri** [comment]
Indeed they are.
Attached just some imagination ....
![IMG_20220418_083652](https://user-images.githubusercontent.com/70443803/163784972-5b2fdca4-ae22-4abd-9ec6-48e1289b9b99.jpg)

**Comment by michaelk83** [comment]
Honestly, these are weird. Just don't maximize the window.

**Comment by droidmonkey** [comment]
Yah those are very awkward. Honestly our application is not meant to be maximized on a 70 inch TV screen (slight exaggeration). In fact it's meant to not be shown as much as possible, global Auto-Type and browser extension should constitute 95% of your interactions after being configured and entries in place.

I don't see us making any specific changes for humongous displays, as such going to close this.

**Comment by Madydri** [comment]
No problem, it is already very good so as it is
