### ISSUE TITLE
Mac: does not grab screen focus with multiple monitors

### ISSUE THREAD

**Issue by FlorinAndrei** [keepassxreboot/keepassxc#7901]
## Overview
[NOTE]: On macOS, when using multiple screens, the Chrome browser is on the big monitor, waiting for a password, I launch KeePassXC and it pops onto the laptop screen, but it does not get the screen focus - so when I start typing the master KeePassXC password it goes actually into the browser, because the browser has the focus.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. macOS on a MacBook Pro with an external monitor
2. Run Chrome on the external monitor, waiting for a password to be typed in
3. Launch KeePassXC from the taskbar. KeePassXC is launched onto the laptop's own monitor
4. Start typing. All you type still goes to the browser. You have to click KeePassXC once to make it grab the focus.

## Expected Behavior
[NOTE]: I expect KeePassXC to grab the focus so when I start typing the master password to open the database, I type it into KeePassXC.

## Actual Behavior
[NOTE]: I start typing and the master password goes into the browser.

## Context
[NOTE]: MacBook Pro (15-inch, 2018) with an external LCD screen.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.1
Revision: 5916a8f

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS 12.1

**Comment by droidmonkey** [comment]
We can't force the operating system to give us focus, all we can do is ask for it. Are you using Auto-Type or browser extension to request a password from keepassxc?

**Comment by FlorinAndrei** [comment]
No, I do not. I copy/paste passwords from KeePassXC to the browser manually.

**Comment by droidmonkey** [comment]
Closing given my explanation above. Recommend using our Auto-Type or browser extension to improve your experience.
