### ISSUE TITLE
Pasting text into any field temporarily hangs the GUI + doesn't work

### ISSUE THREAD

**Issue by madebr** [keepassxreboot/keepassxc#7902]
## Overview

Pasting text into any field of an entry temporarily hangs the GUI.
After about 10 seconds, the GUI become accessible again.
No text is actually pasted.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Click on "Add a new entry"
2. Copy any text (e.g. the url of this issue)
3. Past the text into any field of the new entry

## Expected Behavior
The GUI remains responsive + the text is pasted.

## Actual Behavior
The GUI is temporarily not responsive + no text is pasted.

## Context
Pasting text into a password entry

NOTE:
KeePassXC - VERSION 2.6.6
Revision: keepassxc-2.6.6-5.fc34.x86_64

NOTE: 
Operating System: Fedora Linux
Desktop Env: Gnome
Windowing System: Wayland

**Comment by droidmonkey** [comment]
Definitely not our bug, this doesn't impact any platform I've ever tested on. Most likely a qwayland bug.

**Comment by madebr** [comment]
I"ve opened a ticket in Fedora's bug tracker: https://bugzilla.redhat.com/show_bug.cgi?id=2075863

Qt6 has much improved wayland support, so https://github.com/keepassxreboot/keepassxc/issues/7774 is a requirement.

**Comment by madebr** [comment]
Thanks for the quick analysis and also many thanks for maintaining this product.
I don't know what exactly fixed is, but running `dnf update` made it go away.
