### ISSUE TITLE
Password strength missing on several entries

### ISSUE THREAD

**Issue by IpsmLorem** [keepassxreboot/keepassxc#7905]
## Overview

I've several entries with a password set but without any password strength displayed.

KeePassXC - Version 2.7.1
Revision: 5916a8f

Qt 5.15.3
Debugging mode is disabled.

Operating system: Windows 10 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.19043

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 2.18.1

Operating System: Windows

**Comment by droidmonkey** [comment]
Did you "exclude from reports"?

**Comment by IpsmLorem** [comment]
> Did you "exclude from reports"?

Damn, you're right !

Thanx and my apologies.
