### ISSUE TITLE
Give the option to specify searches or fix the search function.

### ISSUE THREAD

**Issue by DriesMoo** [keepassxreboot/keepassxc#7907]
I was looking for my Gmail account.
By typing in "gmail" it brought up all the entries that use my gmail as a username. Same with searching "mail" btw. This is very unproductive imo.
I recommend either an option to just search using Name and Group names or an option (like discord does) to search within specific parameters. ie: "name", "username" or "group"

**Comment by droidmonkey** [comment]
Read the user guide on how to use the search feature
