### ISSUE TITLE
Autowrite not working properly

### ISSUE THREAD

**Issue by Mufdi** [keepassxreboot/keepassxc#7908]
## Overview
When you start the automatic typing from the browser, the username in question is correctly typed, but when going to the password, it gets stuck and ends up typing an incorrect password.

## Steps to Reproduce

1. I enter the web where I want to enter my credentials
2. I position myself in the corresponding box and type the direct access to automatic autowriting
3. The user is written and the password is written in parts, and ends up entering anything

## Expected Behavior
That the username and password are entered correctly, in addition to finishing the process by accessing the site.

## Actual Behavior
Only the username is written correctly, the password is written in parts and ends up typing anything.

## Context
I have tested with updated versions of Firefox and Brave browser. The problem has been going on for about two months. I noticed that KeePassXC has been updated a couple of times and the problem persists. There are a few times that the password does get spelled right, but it should be 1 out of 20 times. Also when autotyping only the password separately, the same thing happens.

KeePassXC - 2.7.1
Revision: 5916a8f

Operating System: Linux / Ubuntu 20.04.4 LTS
Desktop Env: Gnome 3.36.8
Windowing System: X11

**Comment by droidmonkey** [comment]
This is either a problem with the browser or the website itself. Either use the browser extension or try adding a delay between typing the username and password. We have seen this behavior in Firefox multiple times and it's definitely caused by Firefox.

**Comment by Mufdi** [comment]
> This is either a problem with the browser or the website itself. Either use the browser extension or try adding a delay between typing the username and password. We have seen this behavior in Firefox multiple times and it's definitely caused by Firefox.

Thanks for the answer, I will try with the extension, since that delay does exist and it continues to work in the same way. And I insist that it also happens when writing only the password. It also happens in the Brave browser, which uses Chromium as an engine. Greetings!

**Comment by droidmonkey** [comment]
You can test autotype in a plain text editor to confirm if it's us or them. If your password has special unicode characters or extended ascii that could cause problems when typing into the browser sometimes.

**Comment by Mufdi** [comment]
> You can test autotype in a plain text editor to confirm if it's us or them. If your password has special unicode characters or extended ascii that could cause problems when typing into the browser sometimes.

I did the test in a plain text editor and I realized that indeed the problem is generated with some special characters, specifically autotype replaces the "^" character with "&". This happened half 20 times I did the test in a plain text editor.

**Comment by droidmonkey** [comment]
Ok so you must be using an international keyboard and run into the bug that @hifi is fixing with dead keys.

**Comment by Mufdi** [comment]
> Ok so you must be using an international keyboard and run into the bug that @hifi is fixing with dead keys.

It's great that they are already correcting that bug, so I'll be attentive to the new versions, and yes, I use an international keyboard. Thank you!

**Comment by hifi** [comment]
#7881 is the tracking bug to get this fixed. Can you @Mufdi specify which keyboard layout you were using so I can test works after the necessary changes? Thanks.

**Comment by Mufdi** [comment]
> 

Perfect, I occupy a distribution in Latin American Spanish.

**Comment by Mufdi** [comment]
> #7881 is the tracking bug to get this fixed. Can you @Mufdi specify which keyboard layout you were using so I can test works after the necessary changes? Thanks. @hifi 

Sorry i forgot to mention you
