### ISSUE TITLE
Windows Hello unblock goes after Yubikey/Password

### ISSUE THREAD

**Issue by vinznsk** [keepassxreboot/keepassxc#7909]
Windows Hello / TouchID unblock is a bit confusing. It goes AFTER KeePass asks you to unblock your database with password and Yubikey. If we are trying to make life easier to QUICKLY unblock the system, KP shouldn't ask for Pass/Yubikey and just use biometric unblock only.

**Comment by droidmonkey** [comment]
Please read the user guide for more information. We use the operating system security framework to encrypt your credentials for future use. Right now we forget them when you close keepassxc or the database. In the future we will introduce the option to store them in the os key store to initially unlock your database.
