### ISSUE TITLE
Sensitive Information shown after minimizing

### ISSUE THREAD

**Issue by marcelatoffernet** [keepassxreboot/keepassxc#7910]
## Overview
When maximising a minimised instance, the details of the database are shown for a brief few milliseconds.

## Steps to Reproduce
1.  Enable "Lock database after minimising window"
2.  Minimise window
3.  Bring window back up.

## Expected Behaviour
The database should show the "unlock database" screen while window is being maximised

## Actual Behaviour
The logged-in screen is shown for a few brief milliseconds. This is undesirable because of prying eyes or potential screen grabs.

## Context
KeePassXC - VERSION 2.7.1
Operating System: macOS Monterey

**Comment by droidmonkey** [comment]
Screen grabs are not possible, we prevent them. This is an artifact of the operating system itself. It uses the last gui state just prior to minimize to show the animation. Nothing we can really do about it, same thing happens on windows.
