### ISSUE TITLE
Text input boxes not working. (Search bar, new entry form, etc.)

### ISSUE THREAD

**Issue by tati-frog** [keepassxreboot/keepassxc#7911]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

When I try to type on a text input, for example the search bar or the Title entry when creating a new entry in the database, it just doesn't type anything. This is happening since last keepassxc update from the fedora 35 repos.

The password entry for unlocking the database works fine tho.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Focus on any input text box.
2. Type.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

I expect the key to be handled and shown in the input box.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

The key doesn't get handled and doesn't appear in the input box.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.1
Revision: 5916a8f

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: Gnome
Windowing System: Wayland

**Comment by droidmonkey** [comment]
See https://github.com/keepassxreboot/keepassxc/issues/5608
