### ISSUE TITLE
KeepassXC shows black screen when remoting into computer with ScreenConnect.

### ISSUE THREAD

**Issue by discusfish99** [keepassxreboot/keepassxc#7914]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # When using ScreenConnect, Keepass won't display anything other than a black screen.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Remote into computer via ScreenConnect (latest version)
2. Try to open KeepassXC
3. If it does open, black screen, but I can interact with it.  IE, entering my master password or hitting the X button.

## Expected Behavior
[NOTE]: # Being able to view KeepassXC while using ScreenConnect.

## Actual Behavior
[NOTE]: # So when I need to remote into my home computer, I have been using ScreenConnect (Connectwise Control) for years.  The newest release of KeepassXC won't display when accessing the computer using ScreenConnect.  The app seems to be working as intended except the window for the app is always black but will accept input from mouse and keyboard.

## Context
[NOTE]: # I confirmed it seems to be this version, because rolling back to the previous release fixes the issue, but then I can't seem to use the browser integration (app is too old).  It works when physically accessing the device as well as via Remote Desktop.  If memory serves, ScreenConnect uses VNC for part of its backend in case that helps.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.1
Revision: 5916a8f

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 10 21H2
Desktop Env: N/A
Windowing System: N/A

**Comment by droidmonkey** [comment]
Read the user guide on screenshot security.

**Comment by endlessskyway** [comment]
This is the solution.

Start up KeepassXZ with the "--allow-screencapture" argument:

<path_of_executable>\KeePassXC.exe --allow-screencapture

Hiding the sceen by default is a seriously great security feature.  It blocks the view against screen recording on your own machine and against screen sharing.  I would like to implement it for other windows, but I haven't figured out how yet.

It's right to default to "hide", but it'd be nice to be able to change back and forth more easily and on the fly.

**Comment by endlessskyway** [comment]
This is the solution.

Start up KeepassXC with the "--allow-screencapture" argument:

<path_of_executable>\KeePassXC.exe --allow-screencapture

Hiding the sceen by default is a seriously great security feature.  It blocks the view against screen recording on your own machine and against screen sharing.  I would like to implement it for other windows, but I haven't figured out how yet.

It's right to default to "hide", but it'd be nice to be able to change back and forth more easily and on the fly.

**Comment by fellipe-barreto** [comment]
To allow sharescreen, click on toolbar: View >> allow screen capture. 

Be happy!
