### ISSUE TITLE
incorrect location of keepassxc-proxy (for firefox) on debian

### ISSUE THREAD

**Issue by pan64** [keepassxreboot/keepassxc#7917]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
Firefox cannot connect to keepassxc, because the location of the keepassxc-proxy is incorrect

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. in ~/.mozilla/native-messaging-host/org.keepassxc.keepassxc_browser.json you can find path=[keepassxc git dir]/build/src/keepassxc-proxy, but it is really located in [keepassxc git dir]/src/proxy, so the json file is incorrect.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
I had to move (link) the json file to the specified location to make it work

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
it worked after the manual fix

## Context
[NOTE]: # ( Give us any additional information you may have. )
somehow the modified json file was overwritten, so I cannot fix it.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.6.6 - 2.7.1
not installed, just built in a git clone.

[NOTE]: # ( Pick choices based on your environment )
Operating System: linux debian bullseye
Desktop Env: Gnome
Windowing System: Wayland

**Comment by droidmonkey** [comment]
You need to install the application to use the proxy, we don't support running it from the build directory. If you must, you can specify a custom proxy location in the browser advanced settings.
