### ISSUE TITLE
[Windows] [U2F] Windows Security (Key Confirmation) window below KeePassXC

### ISSUE THREAD

**Issue by pomianowski** [keepassxreboot/keepassxc#7925]
## Overview
![image](https://user-images.githubusercontent.com/13592821/164279482-b94d50a3-19b5-4429-8ac4-66bf62d4f4a2.png)

## Steps to Reproduce
1. Add a U2F key to your Windows Hello
2. Set Windows login with PIN
3. Add U2F key to KeePassXC database
4. Open the app and enter the password to the database
5. The U2F key confirmation window by Windows Security is below the Keepass application window.

 The user may think that something has crashed, but just a confirmation window is underneath

## Expected Behavior
The UAC / Windows Security window is Topmost above the KeePassXC window.

## Actual Behavior
The KeePassXC window is above all other windows, you can't have any above it.

KeePassXC - Version 2.7.1
Revision: 5916a8f
Windows 11 Education 64-bit (10.0, Build 22000) (22000.co_release.210604-1628)

**Comment by JohnLGalt** [comment]
Do you have KPXC set to "Always on top"?

View menu --> Always on top (shortcut CTRL + SHIFT + A

**Comment by pomianowski** [comment]
Hey @JohnLGalt, you're right, the app have **Always On Top**. But I think the UAC should be higher after all.
![image](https://user-images.githubusercontent.com/13592821/164318122-4d5b3952-bc1b-42cd-aa1c-ad77c25b9429.png)

**Comment by droidmonkey** [comment]
Do you have always on top enabled?

**Comment by droidmonkey** [comment]
always on top means always on top
