### ISSUE TITLE
AutoType not working with Firefox/Gnome

### ISSUE THREAD

**Issue by Offerel** [keepassxreboot/keepassxc#7926]
## Overview
I have re-installed Manjaro Linux and got a new KeepassXC version with this (2.70). If i use Firefox and load a login form, and i press the global AutoType Key, nothing happens in Firefox. But it works in Chromium. I don't know if this is a issue with Firefox, Manjaro, Gnome or KeepassXC.
 
## Steps to Reproduce
1. Load for example GitHub login page in Firefox
2. Press Global AutoType Hotkey
3. Nothing happens
4. Load the same page in Chromium
5. Press Global AutoType Hotkey
6. Credentials are filled in

## Expected Behavior
Global AutoType should work with all applications

KeePassXC - 2.7.0

Operating System: Manjaro Linux
Desktop Env: Gnome
Windowing System: Wayland

**Comment by droidmonkey** [comment]
We don't support auto-type on wayland. You probably are running chromium in x11 through xwayland.

**Comment by Offerel** [comment]
Since Wayland will replace X11 in some future, are there plans to support Wayland at some time or is this general not possible?

**Comment by droidmonkey** [comment]
There's a robust conversation about that on here. Search for auto-type wayland.
