### ISSUE TITLE
In the Linux environment (deepin), after using the keepassxc and keepassxc browser plug-ins, when using the global shortcut key to enter the account password, the system will be logged off. I don't know what the problem is?

### ISSUE THREAD

**Issue by coolxy** [keepassxreboot/keepassxc#7927]
In the Linux environment (deepin), after using the keepassxc and keepassxc browser plug-ins, when using the global shortcut key to enter the account password, the system will be logged off. I don't know what the problem is?

**Comment by droidmonkey** [comment]
You must have set the global auto type shortcut to one that logs off the computer. Choose a different one.
