### ISSUE TITLE
Behavior change with column sorting

### ISSUE THREAD

**Issue by ITler** [keepassxreboot/keepassxc#7928]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
Since 2.7.0 the columns are always sorted by `Created` rather than `Title` or whatever sorting order I chose in my last session. With every restart of keepassxc, I would have to adjust the sorting to my needs (by `Title`), manually.

## Expected Behavior
Remember last chosen column sort order before closing keepassxc (database)

## Actual Behavior
Database entries are always sorted by `Created` when opening database

## System env
```
KeePassXC - Version 2.7.1
Revision: 5916a8f

Qt 5.12.8
Debugging mode is disabled.

Operating system: Ubuntu 20.04.4 LTS
CPU architecture: x86_64
Kernel: linux 5.4.0-109-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.12.1
```

also for the previous release
```
KeePassXC - Version 2.7.0
Revision: d7a9ef4

Kernel: linux 5.4.0-105-generic
```

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: Gnome/i3
Windowing System: X11

**Comment by droidmonkey** [comment]
Make sure your ~/.cache folder is not ram mounted. If it is, you can change the location of the local config file. See here: https://keepassxc.org/docs/KeePassXC_UserGuide.html#_command_line_options

**Comment by ITler** [comment]
the ~/.cache folder is not ram mounted. Actually deleting the ini file did the trick for me.
