### ISSUE TITLE
^ can't insert via the keyboard, when the password is hidden

### ISSUE THREAD

**Issue by Maxil8318** [keepassxreboot/keepassxc#7929]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. ^  (Zirkumflex) - can't insert via the keyboard, when the password is hidden
2. 
3. 

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION: 2.7.1
Revision: 5916a8f

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS Monterey 12.3.1

**Comment by droidmonkey** [comment]
This is a qt bug, reported to them.
