### ISSUE TITLE
security reason for keepassxc vs anydesk

### ISSUE THREAD

**Issue by RANDOMLY-OBFUSCATED** [keepassxreboot/keepassxc#7931]
## Overview
keepassxc's window is not drawed on a distant pc (remote control, others are ok)
Can it be a security reason on keepassxc? An new option I don't know/find?

## Steps to Reproduce
1. take control over a distant PC
2. lauch keepassxc
3. -> no window in anydesk (localy ok)

## Expected Behavior
be able to view the window like any other

## Context
from
  * openSUSE 15.3 up to date with KDE on X
  * anydesk from their repo (6.1.1)

to
  * just unboxed win10
  * anydesk 7.0.0 from their web site
  * keepassxc up to date from chocolatey
  * no other AV than Win Defender at this time

**Comment by Nickoriginal** [comment]
See [this section in FAQ](https://keepassxc.org/docs/KeePassXC_GettingStarted.html#_screenshot_security) and [this](https://github.com/keepassxreboot/keepassxc/pull/6030#issue-797585271) comment in PR. Let me explain briefly: to see the window you must start KeePassXC with the `--allow-screencapture` command line flag every time. If you don't want to do this, you must downgrade to [2.6.6](https://github.com/keepassxreboot/keepassxc/releases/tag/2.6.6).

**Comment by RANDOMLY-OBFUSCATED** [comment]
thanks!
