### ISSUE TITLE
Unable to open the database. No root group.

### ISSUE THREAD

**Issue by livioavalle** [keepassxreboot/keepassxc#7934]
## Overview
I've just updated keepass version to 2.7.1 and now when trying to open my database it gives this error: 
`Unable to open the database. No root group.`
I tried to uninstall 2.7.1 and reinstall 2.7.0 and now it works, so it's not the database file but maybe a bug in the new release.

Operating System: Windows 10 Pro 21H2

**Comment by droidmonkey** [comment]
We did not touch the code responsible for opening databases between those two versions.

**Comment by livioavalle** [comment]
I can try to use the last version with the same file on another pc if is useful

**Comment by droidmonkey** [comment]
Just use the portable version

**Comment by livioavalle** [comment]
The 2.7.1 version portable works.

**Comment by droidmonkey** [comment]
Just reinstall 2.7.1 then, this was probably a strange transient error.
