### ISSUE TITLE
Unable to open nor save a database on snap version

### ISSUE THREAD

**Issue by sshilin** [keepassxreboot/keepassxc#7938]
## Overview
Can't open an existing database nor save a new one on Ubuntu 22.04 Live.

## Steps to Reproduce
1. Boot Ubuntu 22.04 Live (Try Ubuntu)
2. Install Keepassxc from Snap `sudo snap install keepassxc`

## Expected Behavior
1. Can open an existing database
2. Can save a new database

## Actual Behavior
1. Clicking "Open existing database" button does nothing
2. Clicking "Save database" button does nothing

## Context
KeePassXC - 2.7.1
Revision: 1552

Operating System: Ubuntu 22.04
Desktop Env: Gnome
Windowing System: X11

**Comment by droidmonkey** [comment]
It's a bug with the xdg portal, we are tracking this elsewhere. You can use the flatpak or appimage instead.
