### ISSUE TITLE
Window size not remembering in the database creation section

### ISSUE THREAD

**Issue by XTChrys** [keepassxreboot/keepassxc#7940]
Hi developers! I would like to report a small problem to the gui. In the database creation section, the window does not keep the custom size. In my language as you can see, if I don't zoom in, the drop down menu is truncated. In version 2.6.6 it was perfect.
Thank you in advance for your attention.

![example](https://user-images.githubusercontent.com/61419802/164886463-cd5270a4-a248-43a3-997f-5311b28407c5.gif)

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Open keepassXC in italian language
2. Create new database
3. Encryption section

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.1

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 10 21H2

**Comment by droidmonkey** [comment]
The translation probably changed slightly. We won't be remembering the size of the new database window, its standard and used very infrequently. As you can see the full text is visible, just on the second line.

![image](https://user-images.githubusercontent.com/2809491/164891843-a7817cc5-2ac4-4682-a7bf-13e1c76b5d7f.png)
