### ISSUE TITLE
KeePassXC 2.7.1 x64 portable regression - No Key Exchange - 2.7.0 x64 portable works fine

### ISSUE THREAD

**Issue by githubbapoopa** [keepassxreboot/keepassxc#7942]
KeePassXC 2.7.1 x64 portable + KeePass Browser Plugin 1.7.11 (or 1.7.12) don*t work together.

Error: Key Exchange not sucessfull (original german error "Schlüsselaustausch war nicht erfolgreich.")

Older KeePassXC 2.7.0 x64 portable + KeePass Browser Plugin 1.7.11 (or 1.7.12) work fine

## Steps to Reproduce

1.  Unzip and run KeePassXC 2.7.1 x64 portable
2. Install Browser Plugin 1.7.11 or 1.7.12
3. Klick the browser icon of KeePassXC plugin

System:
Win10 + Firefox 91.5.1 ESR portable + KeePassXC 2.7.1 x64 portable + KeePass Browser Plugin 1.7.11 (or 1.7.12)

**Comment by droidmonkey** [comment]
Enable always rewrite native messaging file in the browser integration settings. You installed your portable install in a different location.

**Comment by githubbapoopa** [comment]
Ok I had totally forgotten to enable browser integration, And I guess I'm not the only one who totally overlooked that setting looking at the reviews for the firefox plugin...

Why isn't Browser intergation enabled by default? Security reasons, I guess...

Native Messaging Manifest ist set to enabled by default.

By enabling browser integration KeePassXC 2.7.1 x64 portable + KeePass Browser Plugin 1.7.12 work fine.

Thanks.
