### ISSUE TITLE
[2.7.1] Challenge Response over NFC not recognized

### ISSUE THREAD

**Issue by UmBottesWillen** [keepassxreboot/keepassxc#7943]
### Overview
I've set up the Challenge-Response with a YubiKey, which works fine when the key is connected via USB. However the key does not get recognized by KeePassXC when it's connected via NFC.

The card reader and Windows (via the 'Device connected' sound) both confirm the connection via NFC if the key is placed upon the reader. No additional software to make the card reader work was installed.

### Context
KeePassXC - Version 2.7.1
Revision: 5916a8f

Qt 5.15.3
Diagnosemodus ist deaktiviert.

Betriebssystem: Windows 10 Version 2009
CPU-Architektur: x86_64
Kernel: winnt 10.0.19044

Aktivierte Erweiterungen:
- Auto-Type
- Browser-Integration
- SSH-Agent
- KeeShare
- YubiKey
- Schnelle Entsperrung

Kryptographische Bibliotheken:
- Botan 2.18.1

Hardware:
- YubiKey 5 NFC
- ACS ACR122U Card Reader

**Comment by droidmonkey** [comment]
When I tested this feature I used a ACR1252U, I don't believe the ACR122U is compatible with Yubikey.

![image](https://user-images.githubusercontent.com/2809491/164980163-2d0735e2-d816-4433-bd2f-d255b9e112e4.png)

https://www.amazon.com/ACR122U-Reader-Writer-Ntag213-Software/dp/B07KRKPWYC/ref=psdc_516872_t2_B01KIKBYAG

**Comment by StarGate01** [comment]
@UmBottesWillen
Make sure that your YubiKey has its NFC interface as well as its HMAC-SHA1 applet enabled, and that a secret is programmed to at least one slot.

According to the spec of the ACR122U (https://www.acs.com.hk/en/products/3/acr122u-usb-nfc-reader/), it "is compliant with both CCID and PC/SC", so it should work. Make sure the entries in the device manager look something like this:
![signal-2022-05-18-010528_001](https://user-images.githubusercontent.com/6362238/168926416-9c7e4c66-2e40-4a19-9e42-6cb3e244c283.png)

However, the ACR122U, especially the clones, sometimes contain subtle bugs.

You can also test your hardware using the Yubikey Authenticator Application, where you can configure a custom PC/SC reader in the settings.
