### ISSUE TITLE
Auto-Type does insert percent (%) characters as hashmarks (#)

### ISSUE THREAD

**Issue by LutzSparmann** [keepassxreboot/keepassxc#7944]
This happens on a windows sytem.
It ist the same behaviour whether I do the Auto-Type into a Chrome or a command prompt window.

I guess this happens because the % character is a substitution for pressing ALT.
But how do I "escape" this?

Lutz

**Comment by droidmonkey** [comment]
Use `{%}`

**Comment by LutzSparmann** [comment]
Thanks, I also had the Idea of kooking into the doku of KeePass and found it there just a minute ago myself.
How about describing it in the help (where the placeholders and Auto-Type actions are described)?

BTW. I liked the way KeePass provided these below the input field for the AutoType sequence definition
Lutz
