### ISSUE TITLE
Cannot copy attribute values from entry preview

### ISSUE THREAD

**Issue by shailen001** [keepassxreboot/keepassxc#7949]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
Previous versions had ability to highlight, and so to copy with mouse, the attributes in Advanced tab in Preview Panel. Now no text can be selected with a simple double mouse click and Ctrl-C. Have to right click on entry, Copy Attribute, and drill down menu. Much slower, much harder to follow across menus.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Create entry with Advanced attributes, save and close.
2. Go to entry, and Advanced tab inside Preview Panel.
3. Try and highlight any attributes. Not possible.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Should be able to select text with mouse cursor as before in Preview Panel. 

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Cannot highlight/select any text in Preview Panel.

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.0
Revision: d7a9ef4

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: XFCE
Windowing System: X1
![example_keepass_cannot_highlight_text](https://user-images.githubusercontent.com/54929814/165037653-987f350f-4b8a-4620-9e89-de298c82d1c4.png)
1

**Comment by droidmonkey** [comment]
Double clicking the value copies it to the clipboard.

**Comment by shailen001** [comment]
So doubling clicking on text copies it anyway (what I wanted). Before it would highlight it, so I didn't know it did this.

Thanks for clarifying.

**Comment by droidmonkey** [comment]
There is a bug though that I just fixed, the connection gets duplicated every time the preview pane is loaded with data. This causes a denial of service effectually if you double click a value
