### ISSUE TITLE
Minimize on close without using a tray icon

### ISSUE THREAD

**Issue by starquake** [keepassxreboot/keepassxc#795]
Please add the ability to allow minimizing the window when clicking on the close button without shutting down the app. This might sound contradictory but that's how most macOS apps work. The reasoning behind it is you close the window, but you do not quit the app. (Examples: Finder, Terminal, Safari, Chrome, Discord, Skype, Outlook, Word, Excel, Powerpoint, Spotify, XCode, Visual Studio Code)

## Expected Behavior

Click close should close the window, but keep the application running. (And probably leave the database unlocked)

## Current Behavior

When I click the close button it exits the application instead of keeping it running.

## Possible Solution

I would suggest to make the default behavior like other apps like described in Expected behavior. Optionally you could create settings to make it work this way.

## Steps to Reproduce (for bugs)

1. Open Keepass window
2. Click on the close button
3.
4.

## Context

For context see general summary. 

## Debug Info

KeePassXC - Version 2.2.0
Revision: caa49a8ef3ee28ed478192389b21d61107b3b8e0

Libraries:
- Qt 5.9.0
- libgcrypt 1.7.7

Operating system: macOS Sierra (10.12)
CPU architecture: x86_64
Kernel: darwin 16.6.0

Enabled extensions:
- KeePassHTTP
- Auto-Type
- YubiKey

**Comment by droidmonkey** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [#795 - minimize instead of close setting (without systray)](https://trello.com/c/B8rSP1sx/9-795-minimize-instead-of-close-setting-without-systray)
