### ISSUE TITLE
Menus get positioned away from the mouse cursor and GNOME top panel overlaps them

### ISSUE THREAD

**Issue by ghost** [keepassxreboot/keepassxc#7950]
## Overview
Can't access the other options from this menu, which is oddly positioned from the bottom to top:

![Screenshot from 2022-04-25 10-42-57](https://user-images.githubusercontent.com/99847968/165101706-c480e3e6-e739-4da1-a285-214e8b6f9f77.png)

This picture shows the issue in a very noticeable way:
![Screenshot from 2022-04-25 10-42-34](https://user-images.githubusercontent.com/99847968/165101713-66361d22-63f9-47c2-b668-59eef37c5651.png)

## Steps to Reproduce
Open a menu from the top bar or right click in something near the window titlebar.

## Expected Behavior
Menus not getting cropped.

## Actual Behavior
Menus get positioned away from the mouse cursor and GNOME top panel overlaps them.

## Context

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.1
Revision: 5916a8f

[NOTE]: # ( Pick choices based on your environment )
Operating System: Fedora 35
Desktop Env: GNOME
Windowing System: Wayland

**Comment by droidmonkey** [comment]
This is not a bug in our program. Those menus are shown by Qt and handled by Qt. Also cannot reproduce this in any way on any distro. Could most likely be a configuration or similar setting on your end.

**Comment by ghost** [comment]
> This is not a bug in our program. Those menus are shown by Qt and handled by Qt. Also cannot reproduce this in any way on any distro. Could most likely be a configuration or similar setting on your end.

Solved. I deleted the keepass and keepassxc folders in ~/.config and the keepassxc folder in ~/.cache. Odd!

**Comment by droidmonkey** [comment]
Could be related to the main window resizing we do to restore the window to its previous state prior to exit. Might not play well on Wayland.
