### ISSUE TITLE
Set a max-width for the search bar

### ISSUE THREAD

**Issue by ghost** [keepassxreboot/keepassxc#7951]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )

Search bar is too big. 

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )

![Screenshot from 2022-04-25 10-58-07](https://user-images.githubusercontent.com/99847968/165105279-ed13308b-33d1-4f72-b13b-5a3224b3cd1b.png)

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )

- The bigger the screen resolution is, the bigger is search bar.
- The current search bar creates unnecessary clutter in the top bar.

**Comment by droidmonkey** [comment]
For what purpose? The search bar occupies remaining space, it is not cluttering anything.
