### ISSUE TITLE
Right clicking in the titlebar doesn't show window options

### ISSUE THREAD

**Issue by ghost** [keepassxreboot/keepassxc#7957]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
When right clicking in the titlebar, the window options don't show. Also, the window lacks the shadow, giving the impression that the titlebar isn't native.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Right click in the titlebar.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
These window options should appear:

![Screenshot from 2022-04-25 23-15-28](https://user-images.githubusercontent.com/99847968/165206082-c584704f-8cbf-4acb-b991-7f8941470ad9.png)

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Nothing happens.

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.1
Revision: 5916a8f

[NOTE]: # ( Pick choices based on your environment )
Operating System: Fedora 35
Desktop Env: GNOME 41.5
Windowing System: Wayland

**Comment by droidmonkey** [comment]
Most likely because we are running through xwayland. Works fine on X11:

![image](https://user-images.githubusercontent.com/2809491/165208061-d41c1597-85c7-4528-b99f-04a019bcf278.png)

Either way we don't control this titlebar menu or the shadow.
