### ISSUE TITLE
Interferre with gamemode extension

### ISSUE THREAD

**Issue by lev741** [keepassxreboot/keepassxc#7961]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Gamemode extension enabled ( https://github.com/gicmo/gamemode-extension )
2. login keepassxc
3. keepassxc not react to keyboard, only mouse works

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Not respond to keyboard after login 

## Context
[NOTE]: # ( Give us any additional information you may have. )
This problem is started from 2.7 

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.1
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: Fedora Linux 35
Desktop Env: Gnome
Windowing System: Wayland

**Comment by droidmonkey** [comment]
#7959 and #5608

Sounds like the game mode extension is causing the interference, not us.
