### ISSUE TITLE
View number of selected entries and within a group/whole DB

### ISSUE THREAD

**Issue by grivanov** [keepassxreboot/keepassxc#7969]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
It will be great when selecting a bunch of entries, to see their total count (like when moving/reorganizing entries between groups). Also to have this metadata for each group and the whole database. Don't know if this is currently possible or just I couldn't find it.

**Comment by droidmonkey** [comment]
This is a duplicate request. For whole database count go to the database reports. The group count is requested for the status bar.

**Comment by grivanov** [comment]
Apologies, didn't find it :)
