### ISSUE TITLE
Changes to settings reversed if you try to open the settings when they are already visible

### ISSUE THREAD

**Issue by anewuser** [keepassxreboot/keepassxc#797]
1. Open the settings
2. Change some options
3. Click on `Tools - Settings` again before saving.

Your changes are reversed. "Settings" should be greyed-out in the menu to prevent this. 

## Debug Info
KeePassXC - Version 2.2.0
Revision: caa49a8ef3ee28ed478192389b21d61107b3b8e0

Libraries:
- Qt 5.9.0
- libgcrypt 1.7.7

Operating system: Windows 10 (10.0)
CPU architecture: x86_64
Kernel: winnt 10.0.15063

Enabled extensions:
- KeePassHTTP
- Auto-Type
- YubiKey

**Comment by droidmonkey** [comment]
Instead of graying out, clicking the option when the settings widget is already visible should simply do nothing.
