### ISSUE TITLE
Useless Auto-Type dialog opens after using the shortcut on a Window Association + specific sequence

### ISSUE THREAD

**Issue by notNSANE** [keepassxreboot/keepassxc#7972]
## Overview
When you press the Auto-Type hotkey on a window you have associated to KeePassXC, a dialog appears even if you have only one type of password preset.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Associate a specific window with a db entry in the Auto-Type options
2. Create a specific entry
3. Go to said window then press the hotkey to perform the Auto-Type

## Expected Behavior
Auto-Type performs without interruptions

## Actual Behavior
A useless window appears, and we need to manually select between two entries, and one of those is completely empty so it doesn't even work

## Context
-

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.1
Revision: 5916a8f

Qt 5.15.3
Debugging mode is disabled.

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 11

**Comment by droidmonkey** [comment]
Disable "always show Auto-Type confirmation dialog" in the application Auto-Type settings.

**Comment by notNSANE** [comment]
If you meant "Always ask before performing Auto-Type" in Tools > Settings General > Auto-Type (Tab) this is fully disabled and the dialog still appears @droidmonkey 

I fully searched the entire app for  "always show Auto-Type confirmation dialog" and the User Guide and there's no mention of this and I really can't find this option.

**Comment by droidmonkey** [comment]
Yes that is the setting I meant. If you still see the window that means you actually have multiple entries or multiple Auto-Type associations that match the window title.
