### ISSUE TITLE
KeepassXC requests two times database password and Windows password when starting up

### ISSUE THREAD

**Issue by itmonitor** [keepassxreboot/keepassxc#7973]
Since I updated to KeepassXC 2.7.1, it will request two times database password and Windows password when starting up.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Boot Windows 11 PC
2. Login into Windows 11
3. Click on KeepassXC 2.7.1 icon
4. It will open and I type the Keepass XC database password
5. It requests me the Windows login password, I type it
6. The Keepass XC window closes and is not in my taskbar
7. I click again on the Keepass XC icon
8. Keepass XC window does not open
9. I click a secon time on the Keepass XC icon
10. Keepass XC windo open, but requests me again the database password
11. I type the database password
12. It requests me again the Windows 11 login password
13. I type the Windows 11 password
14. Finally, the KeepassXC 2.7.1 window opens with the passwords in it and i can use it

## Expected Behavior
First thing: I never enabled the Windows 11 password request in keepassXC. It enabled this feature automatically when updating to the 2.7.1 version. Second: It requests two times the database and Windows 11 login password. I reinstall it, it will now work well, and requests me the database password and the Windows 11 login password only one time. But, after rebooting the PC the defective behaviour described above comes back. 
Please, let me know why the Windows login password feature was enabled inside KeepassXC even if I did not enabled it. Please, let me know if there is any risk, hack with my password database inside KeepassXC. thank you.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

## Context
[NOTE]: # ( Give us any additional information you may have. )
Edition	Windows 11 Pro
Version	21H2
Installed on	‎21/‎02/‎2022
OS build	22000.613
Experience	Windows Feature Experience Pack 1000.22000.613.0

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION 2.7.1
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Edition	Windows 11 Pro
Version	21H2
Installed on	‎21/‎02/‎2022
OS build	22000.613
Experience	Windows Feature Experience Pack 1000.22000.613.0

**Comment by droidmonkey** [comment]
This is quick unlock, take a read of the user guide for more information. You can disable it in the application security settings.

**Comment by keunes** [comment]
@droidmonkey I was just switched to Windows 11 by our IT person and I must say that this is a tat confusing. I just had a look at the documentation, and I think I understand now: after each first time the database is unlucked on system run, you're asked for the Windows Hello Pin. As long as the system doesn't restart, you don't need to type in the database password again, but can unlock via Windows Hello.

Is this understanding correct?

I think from the documentation it's not entirely clear what is "subsequent unlocking" and what is "initial database unlock". Once I understand/have your confirmation, I can think of & propose a PR to slightly adjust this.

**Comment by droidmonkey** [comment]
We are planning a ui change already to make it clearer. When you first unlock your database it will ask for windows hello pin to establish the encryption of your credentials in memory (initial). When you lock and unlock your database the memory stored credentials will be decrypted after successful windows hello auth and used to unlock your database (subsequent). If you close the database in keepassxc or keepassxc itself then we forget those stored credentials.

**Comment by keunes** [comment]
Ok, thanks. So it's the closing of the database that matters. I think because I didn't yet have the option 'Minimise instead of app exit' activated, the database was effectively closed each time I didn't intend to. Seems I now got it set up the way I want :)

Given that you're planning to change the UI, I'll hold off on the PR.
