### ISSUE TITLE
AutoType with xfreerdp swallows brackets

### ISSUE THREAD

**Issue by the-nic** [keepassxreboot/keepassxc#7976]
## Overview

When using auto-type with an `xfreerdp` window, brackets are not transferred. It is unclear for my whether this is an issue from freerdp or from AutoType. However, manually typing the bracket works.

## Steps to Reproduce

1. Have a username/password containing brackets `(` or `)`
2. Use auto type with a `xfreerdp` remote session (linux host, remote windows)
3. all chars are filled, except brackets  `(` or `)`

## Expected Behavior

All Characters are transferred.

## Actual Behavior

Brackets are missing

## Context

Using freerdp `2.3.2` on Linux connected to a Windows machine. I cant say who is to blame here. However, typing the characters using the keyboard works.

KeePassXC - Version 2.7.1
Revision: 5916a8f

Qt 5.15.3
Diagnosemodus ist deaktiviert.

Betriebssystem: KDE neon User - 5.24
CPU-Architektur: x86_64
Kernel: linux 5.13.0-40-generic

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux/Windows
Desktop Env: KDE
Windowing System: X11

**Comment by hifi** [comment]
So to be sure, do brackets work to a non-RDP window?

**Comment by droidmonkey** [comment]
Likely #7881. He is German on Linux.

**Comment by the-nic** [comment]
I have a german layout (variant dead grave acute) and yes the brackets work for other windows
