### ISSUE TITLE
Launch on system startup even when option is unchecked

### ISSUE THREAD

**Issue by qingxiang-jia** [keepassxreboot/keepassxc#7979]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
Even if I uncheck "Automatically launch KeePassXC at system startup", it still runs when system starts up.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Install the latest 2.7.1-1 on Arch [link](https://archlinux.org/packages/community/x86_64/keepassxc/)
2. Open the app and in Settings, uncheck "Automatically launch KeePassXC at system startup"
3. Reboot or just logout, and login.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
It won't start up with the system.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
It starts up with the system.

## Context
[NOTE]: # ( Give us any additional information you may have. )
I am running Arch with KDE (I don't have other desktop environments so I can't check its behavior for others).
I don't have the KDE autostart on for KeepassXC in case you wonder that's the culprit.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.1
Revision: 5916a8f

Qt 5.15.3
Debugging mode is disabled.

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 5.17.5-arch1-1

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.19.1

[NOTE]: # ( Pick choices based on your environment )
Operating System: Arch Linux
Desktop Env: KDE
Windowing System: X11

**Comment by droidmonkey** [comment]
Does the check box keep reappearing as checked?

**Comment by qingxiang-jia** [comment]
Hi @droidmonkey , no, it stays as unchecked. But what's interesting is, if I allow running of multiple instances of keepassxc, and turned on auto start in keepassxc, I will see two instances of it running.

**Comment by qingxiang-jia** [comment]
By checking the PPID (parent process ID) of the running keepassxc (when auto start is disabled), it turns out to be ksmserver. It's the KDE process that's responsible for auto start applications. So I guess it seems to be a KDE specific problem. But the weird thing is, I don't have keepassxc in the KDE auto start list. Shall I close this issue?

**Comment by michaelk83** [comment]
KSM will relaunch on startup stuff that was open when you logged out. Try closing keepass before logging out.

**Comment by droidmonkey** [comment]
Yah if the checkbox is unchecked that means you "added" it to startup somewhere else. That checkbox is a dynamic check so if it's unchecked it's not our method of starting on log in.
