### ISSUE TITLE
Global AutoType not working anymore inside KeePassXC itself

### ISSUE THREAD

**Issue by aforrerX** [keepassxreboot/keepassxc#7980]
## Overview
I have two different databases of which I normally use the global AutoType function to open the other database. After updating to the latest version, this does not work anymore. 

## Steps to Reproduce
1. have two databases: one unlocked, one locked
2. setup global autotype for the locked database in the unlocked database 
3. apply autotype on the locked database tab

## Expected Behavior
password is entered

## Actual Behavior
nothing happens --> I guess since I switch database "tabs", KeePassXC does not realize that the other database is unlocked and can be used for gloabl autotype (which it did in the previous version)

## Context

KeePassXC - Version 2.7.1
Revision: 5916a8f

Qt 5.15.3
Debugging mode is disabled.

Operating system: Windows 10 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.19044

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 2.18.1

**Comment by phoerious** [comment]
This is intentional and has been disabled for a very long time already. Your previous version must have been extremely old. Use AutoOpen, kdbx:// URLs, or KeeShare instead.

**Comment by aforrerX** [comment]
Okey, my bad. Thank for the notice and yes, I had an older version.
