### ISSUE TITLE
Allow clicking and dragging entry URLs into browsers / other applications

### ISSUE THREAD

**Issue by LoganDark** [keepassxreboot/keepassxc#7981]
It's not easy to open a URL in a non-default browser (or incognito window) because clicking and dragging a link just selects it. :/

I can right-click it and copy it and then paste it, but not drag.

Windows 10 Home 2004 build 19041.928 (x64) KeePassXC 2.7.1 (Dark theme)

**Comment by LoganDark** [comment]
I think I accidentally created this without using the template (how?), could you assign the correct label please?

**Comment by droidmonkey** [comment]
You can't right click and copy or press Ctrl÷U to copy the url?

**Comment by LoganDark** [comment]
> You can't right click and copy or press Ctrl÷U to copy the url?

I explicitly mentioned that in my issue, I'd prefer not to have to do it though since it's slower / less convenient than just dragging. Plus it overwrites my clipboard, which is mildly annoying.

from the issue description:

> I can right-click it and copy it and then paste it, but not drag.

I have seen #1987 but it seems to be mainly for the username/password fields in the table and not the URL. By the way, how did you end up with a non-draggable URL?

**Comment by LoganDark** [comment]
If I double-click slightly to the right of the URL, then it'll allow me to select the whole thing and then I can drag the *selection* into a browser. This is slightly finicky but it's still easier than using the clipboard.

Will close if this feature is deemed not important since I have a "good enough" workaround.

**Comment by droidmonkey** [comment]
If anything this is a Qt limitation. I'll play around with the settings.

**Comment by droidmonkey** [comment]
Looks like the only way you can drag information is to select the text first. Your workaround to click and select is the way to do it. We won't be able to support any other way. FWIW you can click and select at any point in the label (red square), the right hand side shows a hand cursor but does not activate the link:

![image](https://user-images.githubusercontent.com/2809491/166070386-901503a8-b574-446b-8516-ffe70021e67b.png)
