### ISSUE TITLE
copying from protected additional attribute leads to pasting of `●●●●●●`

### ISSUE THREAD

**Issue by zocker-160** [keepassxreboot/keepassxc#7982]
## Steps to Reproduce
![Peek 2022-04-29 13-56](https://user-images.githubusercontent.com/36563538/165939806-72f014b1-0509-4eae-aad8-1fb9dd764ecc.gif)

## Expected Behavior
It should copy the actual content of the entry just like it does for passwords.

## Actual Behavior
It copies the `●●●●●●` instead of the actual content of the entry.

## Context
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.1
Revision: 5916a8f

Operating System: Linux
Desktop Env: KDE
Windowing System: X11

**Comment by WhyNotHugo** [comment]
Thanks!
