### ISSUE TITLE
Double click on item's username or password open item for editing

### ISSUE THREAD

**Issue by miheishe** [keepassxreboot/keepassxc#7985]
## Overview
When you open database, and want to copy username or password of any item I usually double click on it.

## Steps to Reproduce
1. Open a database
2. Choose item
3. Double click on item's username or password

## Expected Behavior
Copy to the clipboard username or password (in case of field)

## Actual Behavior
Open item for editing

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.1
Revision: 5916a8f

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows and macOS

**Comment by droidmonkey** [comment]
Enable it in application security settings
