### ISSUE TITLE
Secret Service: Storing a secret does not trigger unlock

### ISSUE THREAD

**Issue by maximilianovermeyer** [keepassxreboot/keepassxc#7989]
## Overview
There is no prompt to unlock my database if I try to save a secret and it is locked.

## Steps to Reproduce
1. Enable KeePassXC Freedesktop.org Secret Service integration
2. Expose a group of a database to Secret Service
3. Restart KeePassXC and **do not unlock** the database
4. Add a secret e.g. by `secret-tool store --label='Desmond' species moonbear`

## Expected Behavior
KeePassXC prompts me to unlock my databases or the caller gets a feedback that saving the credentials failed.

## Actual Behavior
There is no feedback, the secret is just not saved.

## Context
The current flag "Prompt to unlock database _before searching_" works as advertised. A similar behavior would be great for saving, maybe just drop the "before searching" and use the same flag?

KeePassXC - Version 2.7.1
Revision: 5916a8f

Qt 5.15.3
Debugging mode is disabled.

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 5.17.5-arch1-1

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.19.1

Operating System: Linux
Desktop Env: Gnome
Windowing System: X11

**Comment by Aetf** [comment]
KPXC currently indeed doesn't prompt to unlock the database in this case. However it does reply with an error over the DBus. It's the secret-tool that not showing anything in the failed case.

It should be easy to add this behavior, as creating items in the spec allows returning a prompt object. So this will always work and there is no need to use a hack like in "unlock before searching".
