### ISSUE TITLE
keepassxc.ini in .config and another one in .cache?

### ISSUE THREAD

**Issue by T200proX7** [keepassxreboot/keepassxc#7990]
I am using KeePassXC 2.7.1

I have a keepassxc.ini in `./config/keepassxc/`. This file includes several settings of the application.
I have another keepassxc.ini in `./cache/keepassxc/` that includes `GroupSplitterState` and so on...

My question is, its a bug that some things are saved in the `.cache` dir instead of the `.config`? 

The problem is always when I empty the `.cache` directory, then I lose my settings regarding column width.

**Comment by droidmonkey** [comment]
Local vs Sharable configs. The user guide tells you how to set a different path for the local (cache) config file.

**Comment by T200proX7** [comment]
Thank you.

**Comment by buhtz** [comment]
Do I understand that correct that there is a local and a shareable config file?

Do they have the same content?

How does KeePassXC react if the content is different? Which file has priority?

Why should a user need two config files?

**Comment by droidmonkey** [comment]
Local = settings that are computer or OS specific
Sharable = all other settings

Sharable is not a good term, should have chosen syncable or roaming

**Comment by buhtz** [comment]
Do they have the same content?

Why should a user need two config files?

**Comment by phoerious** [comment]
They don't. The files have the same semantics as %AppData% and %LocalAppData% on Windows.
