### ISSUE TITLE
Feature request: TOTP support

### ISSUE THREAD

**Issue by erikvanoosten** [keepassxreboot/keepassxc#80]
It would be amazing if KeepassXR could support Timed One Time Passwords. Currently I am using Google's Authenticator which means that loosing my phone results in loosing access to many services.

Storage of the TOTP information should be compatible with the [Keepass OTP plugin](https://bitbucket.org/devinmartin/keeotp/wiki/Home). This format is also understood by KeePass2Android.

TOTP is described by [rfc6238](http://tools.ietf.org/html/rfc6238). It relies on a shared secret. Often this comes in the form of a QR code. In most cases you can also get a base32 encoded key as well.

KeepassXR could continuously show the generated password and copy it the clipboard when clicked.

**Comment by TheZ3ro** [comment]
I was looking to this feature some time ago but I've preferred to do other thing.
I would add that there are 2 opened PR to KeePassX for support to TOTP

https://github.com/keepassx/keepassx/pull/176 and https://github.com/keepassx/keepassx/pull/113

Also should be good to add support for HOTP described by [rfc4226](https://tools.ietf.org/html/rfc4226)

**Comment by RealOrangeOne** [comment]
Any update on progress on this? Would be really nice to have so I dont have to use Keepass2 anymore!

**Comment by TheZ3ro** [comment]
@RealOrangeOne I will look into this once v2.1.0 is released :wink:

**Comment by qazip** [comment]
If I understand, you want keepassx to be able to store/create TOTP right? What I want is the ability to lock my DB with TOTP. Is there a feature request for that already?

**Comment by rigrig** [comment]
@qazip there is, see #798

**Comment by phoerious** [comment]
You can't. TOTP is incompatible with offline databases.

**Comment by gsantner** [comment]
How can a TOTP entry be added? I have latest keepassxc installed, there is no "OTP" special option in `Add new entry` and the 2-3 OTP actions are all grayed out. 

Video: <https://raw.githubusercontent.com/gsantner/gh_tmp/master/simplescreenrecorder-2018-02-22_19.14.12.webm>

**Comment by phoerious** [comment]
You find the TOTP option when you right-click on an existing entry.
