### ISSUE TITLE
German translation incomplete

### ISSUE THREAD

**Issue by r0ckarong** [keepassxreboot/keepassxc#800]
The current 2.2.0 release has a variety of untranslated strings in the German version.

## Expected Behavior
All strings should be translated to German.

## Current Behavior
Various strings are untranslated and are displayed in English original.

## Possible Solution
Translate strings

## Steps to Reproduce (for bugs)
Use the app in various places.

## Context

![screen shot 2017-07-20 at 14 17 29](https://user-images.githubusercontent.com/4920542/28417071-f2ba062c-6d56-11e7-915d-3c28fc5b607f.png)
![screen shot 2017-07-20 at 14 17 40](https://user-images.githubusercontent.com/4920542/28417068-f2b71b4c-6d56-11e7-8d27-8840d4600747.png)
![screen shot 2017-07-20 at 14 17 52](https://user-images.githubusercontent.com/4920542/28417070-f2b860ce-6d56-11e7-95ed-41af9d644613.png)
![screen shot 2017-07-20 at 14 18 08](https://user-images.githubusercontent.com/4920542/28417072-f2bd5b88-6d56-11e7-8605-6e11e606123d.png)
![screen shot 2017-07-20 at 14 18 12](https://user-images.githubusercontent.com/4920542/28417069-f2b7a60c-6d56-11e7-9205-8367c49254e2.png)
![screen shot 2017-07-20 at 14 18 32](https://user-images.githubusercontent.com/4920542/28417073-f2beb60e-6d56-11e7-9d7b-ffdaf323828b.png)
![screen shot 2017-07-20 at 14 18 39](https://user-images.githubusercontent.com/4920542/28417074-f2d089c4-6d56-11e7-8dc3-29eddd0b4ca3.png)
![screen shot 2017-07-20 at 14 19 03](https://user-images.githubusercontent.com/4920542/28417076-f2d38a98-6d56-11e7-8e0e-6c08a9f4640a.png)
![screen shot 2017-07-20 at 14 19 09](https://user-images.githubusercontent.com/4920542/28417075-f2d0f47c-6d56-11e7-85da-f292537ef9c5.png)
![screen shot 2017-07-20 at 14 19 16](https://user-images.githubusercontent.com/4920542/28417077-f2d4b102-6d56-11e7-8672-6ad83c3b309d.png)
![screen shot 2017-07-20 at 14 19 20](https://user-images.githubusercontent.com/4920542/28417078-f2db2e24-6d56-11e7-967f-5ec2d8df1116.png)

**Comment by phoerious** [comment]
The German translation is complete. Version 2.2.1 will ship the updated translation files: https://www.transifex.com/keepassxc/keepassxc/language/de/
