### ISSUE TITLE
Auto-typed username is missing the first character when starting with capital E

### ISSUE THREAD

**Issue by eitch** [keepassxreboot/keepassxc#8001]
## Overview
A username starting with a capital E does not properly auto-type in a virtualbox Windows 10 environment.

## Steps to Reproduce
1. Have a username start with a capital E, e.g. E456456
2. Perform autotype into notepad++ in a virtualbox Windows 10 environment

## Expected Behavior
The entire username should be auto typed.

## Actual Behavior
The username is missing the first character

## Context
- Host: Pop!_OS 21.10
- Target Virtualbox Windows 10 VM

KeePassXC - Version 2.7.1
Revision: 5916a8f
Distribution: AppImage

Qt 5.15.2
Debugging mode is disabled.

Operating system: Pop!_OS 21.10
CPU architecture: x86_64
Kernel: linux 5.16.15-76051615-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.12.1

**Comment by droidmonkey** [comment]
Use the virtual keyboard mode

**Comment by droidmonkey** [comment]
Add a longer start delay.

**Comment by eitch** [comment]
@droidmonkey I tried that. No change. I changed all those settings, i even added an additional character before the first character and it didn't work. Only once i set the first character to be lower case did it work... but that is not really the solution...

**Comment by michaelk83** [comment]
> Target Virtualbox Windows 10 VM

Are you using the Virtual Keyboard mode to autotype? #7507

**Comment by eitch** [comment]
I don't have this option, so i'll say no. My host system ist PopOS!

**Comment by droidmonkey** [comment]
Are you using a non-us keyboard layout?

**Comment by eitch** [comment]
Yes, a CH keyboard

**Comment by droidmonkey** [comment]
This is most likely #7881. Please test with a us keyboard layout to confirm

**Comment by eitch** [comment]
Yes, it seems to be the issue. Thanks.
