### ISSUE TITLE
Auto-Type with Strg+Alt+A not working

### ISSUE THREAD

**Issue by Turbotomate** [keepassxreboot/keepassxc#8002]
## Overview
Auto-Type was suddenly not possible anymore. When looking into the settings, i saw my combination "Strg+Alt+A" but the field was in red color (like when trying to set "Strg+Alt+M"). When trying to assign the keys again, it does'nt accept "Strg+Alt+A". Other key combinations (like "Strg+Alt+S") work flawless.

## Steps to Reproduce
1. Set "Strg+Alt+A" as a key combination for Auto-Type

## Expected Behavior
"Strg+Alt+A" works as an Auto-Type key combination.

## Actual Behavior
"Strg+Alt+A" does not work as an Auto-Type key combination.

## Context
I think the problem ocurred after the update from 2.7.0 to 2.7.1. I never had problem with this exact key combination in the past.

KeePassXC - 2.7.1
Revision: 5916a8f

KeePassXC - Version 2.7.1
Revision: 5916a8f

Qt 5.15.3
Diagnosemodus ist deaktiviert.

Betriebssystem: Windows 10 Version 2009
CPU-Architektur: x86_64
Kernel: winnt 10.0.19044

Aktivierte Erweiterungen:
- Auto-Type
- Browser-Integration
- SSH-Agent
- KeeShare
- YubiKey
- Schnelle Entsperrung

Kryptographische Bibliotheken:
- Botan 2.18.1

Operating System: Windows 10 Pro 21H2

**Comment by droidmonkey** [comment]
#7970
