### ISSUE TITLE
Password Group View hidden and cant be enabled again

### ISSUE THREAD

**Issue by bremade** [keepassxreboot/keepassxc#8012]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
Hello there i accidently clicked somewhere in my keepassxc window and since then im not able to see the groups view on the left of the window. I was trying to follow the documentation and enable it again through the view tab, but there is no option for that.
Is there any possibility to get this group view back?

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
? Cant reproduce. Cant even get to the default.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
View Setting has option to enable/disable group view.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
No option can be found to enable group view again.
Only has
- Theme
- Always on Top
- Show Preview Panel
- Show toolbar
- Hide Usernames/Passwords

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.1
Revision: 2.7.1

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows

**Comment by droidmonkey** [comment]
Drag the pane back out from the far left. When you hover near the left side of the window you should see the cursor change to a resize indicator.

**Comment by bremade** [comment]
worked. Thank you

**Comment by Nexus3932** [comment]
![image](https://github.com/keepassxreboot/keepassxc/assets/135124495/b9fab861-78cd-4945-92aa-1a87943c59ea)
It's helpful for me,thank you.

**Comment by xianoio** [comment]
A neat solution for this would be adding an arrow to collapse/expand the group section.

**Comment by droidmonkey** [comment]
Technically that exists already it's just not that visibld
