### ISSUE TITLE
Unable to start KeePassXC in Win 10 LTSB 2015 - Application Error

### ISSUE THREAD

**Issue by kmccullor** [keepassxreboot/keepassxc#8015]
The exception Breakpoint
A breakpoint has been reached.
(0x80000003) occurred in the application at location 
0x00007FF6B068F385.

This began happening in my Virtual Machine (VMWare 6.1.32) using GuestOS Windows 10 LTSB 2015 after the KeePassXC 2.7.0 update and is still an issue in 2.7.1.

I am unable to start KeePassXC in this environment.
![Capture](https://user-images.githubusercontent.com/44376550/166950913-03a04069-b172-4a6f-9204-bc75f03a067f.PNG)

**Comment by droidmonkey** [comment]
This seems to be a common error thrown when the system has corrupted or outdated packages. Try performing an `sfc /scannow` or installing the latest MSVC runtime libraries.

**Comment by kmccullor** [comment]
I have updated my libraries (https://docs.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170), ran sfc command, and reinstalled KeePassXC (2.7.1), but I am still getting this error.

**Comment by droidmonkey** [comment]
Unfortunately I don't have any other idea here

**Comment by jeffstagg** [comment]
Just wanted to chime in and say I'm having the same issue. This is on a fresh windows 10 guest install, running in a virtualbox VM. I've not run into this with prior versions in the last several years. Nothing showing up in the event log, but still digging. So far the thing @kmccullor and I have in common is they're both in VM's.

**Comment by jeffstagg** [comment]
Update: Removed KeepassXC from system, installed version 2.6.6. Ran and opened fine. Uninstalled, and installed 2.7.0. Got the error above. Happens immediately upon opening. Looking at the additions in 2.7.0, there's no way for me to know which update is causing the issue. If I get some time later this week, I'll try grabbing source from 2.6 and merging items little by little. I'm wondering if it's an issue with the quick unlock via VM since it happens before you get to open a database.

**Comment by droidmonkey** [comment]
It's most definitely related to the switch to visual studio builds. Try the legacy windows installer/portable.

**Comment by jeffstagg** [comment]
Portable installer worked just fine for me. Thanks again for updating us!

**Comment by edleyhoyler** [comment]
Same mistake:

Windows 10 LTSB 2015 update 27/09/2023 on Virtualbox 6.1.46.
Solved by installing the latest version KeePassXC-2.7.6-Win64-LegacyWindows.msi
The legacy version solved all the problems.
