### ISSUE TITLE
Move socket into separate directory for sandbox friendliness

### ISSUE THREAD

**Issue by WhyNotHugo** [keepassxreboot/keepassxc#8018]
I'm trying to set up the browser plugin to talk to a locally running KeePassXC instance. I run the browser in a local sandbox so that it doesn't have unrestricted access to the entire system using Firejail (though the topic described here probably affects any sandboxing mechanism).

From what I understand, communication happens via a socket named `org.keepassxc.KeePassXC.BrowserServer` placed directly in `$XDG_RUNTIME_DIR`.

If I configure the browser's sandbox to have access to this file, it will only work if the file exists _before_ the browser is started. If the file does not exist when the browser is started, there is nothing to mount inside its filesystem namespace. Exposing individual files to sandboxes is tricky, and especially sockets. Usually, sockets are placed inside a dedicated directory, since exposing _that_ directory to the sandbox is less problematic.

A common workaround seems to have been to grant the browser access to the entirety of `$XDG_RUNTIME_DIR`, but this exposes a huge attack surface to the browser, granting it access to lot of very sensitive sockets.

## Expected Behavior

I can configure a sandboxed browser to talk to KeePassXC.

## Current Behavior

There's no obvious way to connect the browser plugin to keepass while keeping the browser sandboxed.

## Possible Solution

Move the socket into `$XDG_RUNTIME_DIR/org.keepassxc.KeePassXC.BrowserServer/sock`. This means that the `$XDG_RUNTIME_DIR/org.keepassxc.KeePassXC.BrowserServer/` directory can be exposed to browser sandboxes, and the plugin would be able to talk to keepass regardless of the order in which applications were started.

This directory can be created by either `keepass-proxy` itself, or by the sandbox running the browser (e.g.: Firejail, Flatpak); it doesn't matter which. That's what makes the change work; whichever of both processes run first can create the directory.

## Steps to Reproduce (for bugs)

Run Firefox with Firejail and try to set up the extension.

## Debug info

KeePassXC 2.71.
KeePassXC-Browser 1.7.12
Operating system: Linux
Browser: Firefox (but probably affects all browsers)

**Comment by WhyNotHugo** [comment]
This is obviously a breaking change, so it's probably ideal for the plugin to fall-back to searching in the current location too, for backwards compatibility.

**Comment by varjolintu** [comment]
Moved this to the KeePassXC side.

**Comment by droidmonkey** [comment]
This was requested before, it might be a duplicate

**Comment by WhyNotHugo** [comment]
Oh, i didn't check the issues here (only for the extension itself).

I don't see any issues mentioning this issue / change specifically.

There's a bunch of issues on the [firejail](https://github.com/netblue30/firejail) issue tracker, but they generally converge on "loosen the sandbox and allow access to all of `$XDG_RUNTIME_DIR`", which really compromise a lot on security. Moving the socket into a dedicated directory allows keeping the sandbox nice and tight.

**Comment by droidmonkey** [comment]
It's fine this is a well presented request so if I find the other I will close that one. Either way, I do like the idea of isolating the socket more. We could create our own symlink to maintain backwards compatibility.

**Comment by varjolintu** [comment]
Also the socket location needs to be changed for the Safari extension because macOS sandbox requires it. So this feature would be very welcome.

**Comment by WhyNotHugo** [comment]
> Also the socket location needs to be changed for the Safari extension because macOS sandbox requires it. So this feature would be very welcome.

What are the requirements on macOS? Does it need a specific location, or just a dedicated directory?

> We could create our own symlink to maintain backwards compatibility.

Sure; given that the old path is currently just used by unsandboxed applications, following the link should not be an issue.

**Comment by varjolintu** [comment]
> What are the requirements on macOS? Does it need a specific location, or just a dedicated directory?

It needs to placed inside a path that is defined in a Group Policy. It should remain the same because it exists under the current user's home.

**Comment by rusty-snake** [comment]
> This was requested before

Here: https://github.com/keepassxreboot/keepassxc/discussions/6741#discussioncomment-1136457

**Comment by rusty-snake** [comment]
> A common workaround seems to have been to grant the browser access to the entirety of $XDG_RUNTIME_DIR, but this exposes a huge attack surface to the browser, granting it access to lot of very sensitive sockets.

Secure workaround: https://github.com/keepassxreboot/keepassxc/discussions/6741#discussioncomment-1154242

**Comment by WhyNotHugo** [comment]
Ah, great find! I will give it a shot, but sounds like it should work.

The workaround mostly configures everything to use the socket in a different location, so I think it kinda validates that this change to the default would be a sensible one.

**Comment by WhyNotHugo** [comment]
See https://github.com/keepassxreboot/keepassxc/pull/8030

**Comment by WhyNotHugo** [comment]
@varjolintu Where would the socket need to be moved for macOS?

**Comment by varjolintu** [comment]
@WhyNotHugo The path needed for Safari support is `~/Library/Group Containers/KeePassXC/org.keepassxc.KeePassXC.BrowserServer`.

**Comment by WhyNotHugo** [comment]
@varjolintu Do you want to open a separate ticket for the macOS/Safari change?

**Comment by varjolintu** [comment]
@WhyNotHugo Not yet. All Safari-related changes will eventually go to the same PR. And it's still WIP.
