### ISSUE TITLE
Allow turning off "focus after allow/deny dialog"

### ISSUE THREAD

**Issue by r0ckarong** [keepassxreboot/keepassxc#802]
When KeepassHTTP is enabled the user will be prompted for confirmation of credentials use. The options there are "Allow" and "Deny". Whenever such a dialog appears and the user clicks either of the options, the focus is brought to the KeepassXC window regardless of it's location. 

This totally breaks workflows because when a mismatch happens or one simply does not want to insert credentials (again), the current window (or workspace) is moved out of view to focus on the KPXC window.

## Expected Behavior
The confirmation dialog should close and disappear without changing application focus or rather change the application focus back to the app where the confirmation request originated from.

## Current Behavior
The confirmation dialog will terminate and send user window focus to the KPXC app window even if that is located on a different workspace or monitor.

## Possible Solution
?

## Steps to Reproduce (for bugs)
-- KeepassHTTP must be enabled, browser extension installed, db unlocked etc. --
1. Open website with credential fields to which you have stored credentials
2. Allow or Deny credentials request
3. KeepassXC window is focues

## Context
It breaks all of my credentials workflows. The only "good" choice is to tick the "Remember choice" box and "Allow/Deny" the request forever because that seems to simply return to the application. 

This can't be right though, because there are plenty of scenarios where I would not want to permanently allow supplying credentials.

## Debug Info
KeePassXC - Version 2.2.0
Revision: caa49a8ef3ee28ed478192389b21d61107b3b8e0

Libraries:
- Qt 5.9.0
- libgcrypt 1.7.7

Operating system: macOS Sierra (10.12)
CPU architecture: x86_64
Kernel: darwin 16.7.0

Enabled extensions:
- KeePassHTTP
- Auto-Type
- YubiKey

**Comment by droidmonkey** [comment]
This has happened to me as well... I get into a tug of war with keepassxc...

**Comment by droidmonkey** [comment]
This was corrected in 2.4.0
