### ISSUE TITLE
Disable record/screenshot protection

### ISSUE THREAD

**Issue by Gomido** [keepassxreboot/keepassxc#8024]
## Summary
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
Recently, Keepas has been blocking external recording and screenshot programs. There is no option to disable it. 
I suggest adding an option in the settings that allows you to disable this lock and allow you to record bases. It is enough to mark the option as dangerous, similar to those with integration in the browser, by default, leave it turned on. The irritated person could turn it off and be aware that, for example, during a stream, someone might see his password.

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )
Screen form PC – https://i.imgur.com/oK2jxup.png
Stream on Discord and photo ( – There is a keepass window on the screen, a big black box on the stream – https://i.imgur.com/sNz3ta8.jpeg

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
People use programs like Nvidia shadowplay to record the desktop or gameplay, streaming the desktop for friends, etc. Often after starting the PC, the replays in the background starts automatically, but opening the base turns it off and forces it to be manually turned on later. We regularly forget to turn it on after unlocking the base. A few minutes later, we copy the password / add a new one, and the replays are turned off again. The database prompts you to enter a password (autocomplete) and replays are turned off again. This is irritating. Similarly, with screenshots, it is often black through Keepass instead of taking a normal screenshot.

**Comment by droidmonkey** [comment]
Read the user guide. 

https://keepassxc.org/docs/KeePassXC_UserGuide.html#_screenshot_security
