### ISSUE TITLE
Merge conflict

### ISSUE THREAD

**Issue by thomase1993** [keepassxreboot/keepassxc#8025]
Hi,

I found that I have merge conflict if I use `.\keepassxc-cli.exe merge -s --key-file x db1.kdbx db2.kdbx`: 
Entry of X [...] contains conflicting changes - conflict resolution may lose data!

I found that only by accident because the user interface told me that my database wasn't changed but i knew I added a new password.

One db is on the nextcloud folder and one is local. How can I resolve the conflict?

**Comment by droidmonkey** [comment]
You can ignore this, it is a bad error message that only indicates a date time mismatch. There is another issue tracking this warning message.
