### ISSUE TITLE
Windows Hello Quick Unlock - multiple databases in once

### ISSUE THREAD

**Issue by Stephan-P** [keepassxreboot/keepassxc#8027]
I've got two databases (personal & work), each with their own main password.
With Quick Unlock enabled, Windows Hello can be very handy to quickly open a locked database.
Unfortunately, I have to do this twice, for each database seperately, while it's the same Windows Hello procedure.

If multiple databases got locked, say through a timeout, lock screen, sleep mode or manually, would it be possible to Quick unlock them all in one go using Windows Hello? IOW, a single Windows Hello credentials confirmation applies as an unlock to all locked databases.

**Comment by droidmonkey** [comment]
Sure that is possible to code, but that brings about significant challenges with user intent. You may want that behavior, but not the next person. Not sure how to do that without a complete ui rewrite of the unlock process.

**Comment by Stephan-P** [comment]
No hurry, maybe you'll come up with an elegant solution at a later stage.
Otherwise I could always reconsider separating my databases and merge Personal and Work together again.

**Comment by droidmonkey** [comment]
We have heard of people using keeshare to import their work passwords into their personal database. It keeps the two separate but still allows access to work data by only unlocking their store. You could also setup auto open of your work db from your personal db so you only have to unlock your personal and your work will automatically unlock as well.

**Comment by Stephan-P** [comment]
Another suggestion related to this.
Could we do without the "Ok" confirmation after Windows Hello has successfully recognized me?

**Comment by droidmonkey** [comment]
If that is on the windows hello dialog, no. That is windows not keepassxc

**Comment by Stephan-P** [comment]
You're right. That's in the Windows Hello dialogue. Too bad.

**Comment by droidmonkey** [comment]
We will not implement this specifically. This capability already exists through AutoOpen (see user guide). You unlock the main database and it subsequently unlocks the autoopen databases.
