### ISSUE TITLE
"Search all open databases" logic?

### ISSUE THREAD

**Issue by Gittyperson** [keepassxreboot/keepassxc#8031]
Using the Global Auto-Type shortcut. This is about the "Search all open databases" setting in the appearing pop-up window.

Its description implies that the currently open database is always being searched, whether ticked or unticked. But it is not.

## Actual Behavior

1. If Auto-Type results are present in the pop-up window (e.g. two results), the setting is unchecked. Typing will only search within those two results which is of no use, since we are looking for other results/entries. "Search all open databases" has to be enabled manually, which does not make sense. We are still searching in the current database, not another one.

2. If Auto-Type results are NOT present in the pop-up window, the setting is checked automatically and now we can search within our current database for the desired Auto-type entry. However, the search will also include all open databases. The logic is broken, even with security implications since we are forced to search all open databases to get desired results from one database.

## Expected Behavior

1. If Auto-Type results are present (e.g. two results) in the pop-up window, the setting should be unchecked but the currently open database should be fully searchable, and not limited to the currently displayed results.

2. If Auto-Type results are NOT present in the pop-up window, the setting should be **unchecked** and again, the currently open database should be fully searchable.

KeePassXC 2.7.1
Operating System: Windows 10

Thanks

**Comment by droidmonkey** [comment]
You are coming at this from the wrong angle. When, for example, only two results are shown then that means you have defined window title associations or enabled the title/url matching options and they have a match.

We show those matches as a default because that is usually the entry you want to type with that window. These matches come from all unlocked databases, not just the current visible one. 

As an alternative option, you can search all unlocked databases for the entry you want to use. Also, if no entries match the current window then we automatically enable database searching (otherwise you'd be staring at an empty list).

Working as designed and it won't change.

**Comment by Gittyperson** [comment]
Ok, thanks for replying. Not insisting, but I'll just note:

> ...When only two results are shown then that means... ...they have a match.
> 

It doesn't always mean that. Some times the results are not a correct match. Websites often change their titles/URLs, add new or use multiple ones etc. In some cases, it's even impossible to define correct Auto-Type associations. When not using the URL, multiple websites can share the same association.

This new feature is about quickly finding the correct match. Just saying that it's not intuitive or does what it describes it does. Perhaps you could consider an option for having that setting always ticked, whether results are displayed or not. Or just have it remember its previous status.

**Comment by droidmonkey** [comment]
The matching is totally up to you. I personally disable the match title/url settings and rely on defined window associations. We support wild cards in the window title which covers a lot of cases. If you haven't already, take a read of the User Guide for more details.
