### ISSUE TITLE
KeepassXC Not Remembering Database

### ISSUE THREAD

**Issue by ourichermath** [keepassxreboot/keepassxc#8032]
## Overview
KeepassXC 2.7.1 is no longer remembering my last open database (nor the window/column sizes/positions when I do open that database).  "Remember previously used databases" and its two sub-options ("Load previously open databases on startup" and "Remember database key files and security dongles") are all turned on.

## Steps to Reproduce
1.  Be signed into a KPXC database, then either shut down/restart the machine or manually shut down KPXC (edit -- the problem is also there when simply shutting down KPXC and restarting just it).
2.   Turn on the computer and have KPXC either autostart (if that's turned on) or manually start it (if not) via the menus or command line.
3.   Instead of getting a window asking to sign in to the last open database, get a "Welcome to KeePassXC 2.7.1 window asking to either "Create new database" or "Open existing database."
4. Navigate to my database, choose it and sign in.
5. The KPXC window is small and all the database columns on it are shrunken down to their minimum.  Resize.
6. Repeat.

## Expected Behavior
KPXC should remember the last opened database, ask me to sign in instead of asking me to select the database, and it should remember windows sizes/positions and column sizes.

## Actual Behavior
KPXC doesn't remember the last opened database, asks me to select it again and after signing in doesn't remember window sizes/positions or column sizes.  Oddly, it DOES remember the settings.

## Context
AFAIK, this version was working yesterday.  BUT, I did a fresh install of Fedora last night and copied all of my home directory (including all the dot folders/files) over to the new installation.  Even though I had just installed KPXC last night, I removed it via the terminal (sudo dnf remove keepassxc) and installed it again (sudo dnf install keepassxc).  The installation went fine, but the problem continued.

I deleted the keepassxc folder and it's ini file from the .cache folder and set the KPXC_CONFIG_LOCAL environment variable in /etc/environment with:

KPXC_CONFIG_LOCAL=/home/dave/.cache

After restarting the computer and KPXC, that folder was recreated in the .cache folder and looks fine (to me).

I turned off Automatically Launch KeepassXC at System Startup, made sure the .desktop file was gone from .config/autostart, deleted my Favorites entry for it, rebooted and manually started it from the menu entry under All Applications.  The problem is still there.

My system information is:

[KeePassXC - Version 2.7.1
Revision: 5916a8f

Qt 5.15.2
Debugging mode is disabled.

Operating system: Fedora Linux 35 (Workstation Edition)
CPU architecture: x86_64
Kernel: linux 5.17.5-200.fc35.x86_64

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.18.2

Operating System: Linux Fedora
Desktop Env: KDE Plasma
Windowing System: Wayland

Operating System: Fedora Linux 35
KDE Plasma Version: 5.24.4
KDE Frameworks Version: 5.91.0
Qt Version: 5.15.2
Kernel Version: 5.17.5-200.fc35.x86_64 (64-bit)
Graphics Platform: Wayland
Processors: 12 × AMD Ryzen 5 5600X 6-Core Processor
Memory: 15.6 GiB of RAM
Graphics Processor: AMD Radeon RX 6800 XT

**Comment by ourichermath** [comment]
I just noticed that if I start KPXC from the terminal, it complains about Qt:

"Qt: Session management error: networkIdsList argument is NULL"

**Comment by droidmonkey** [comment]
When you use the env var you need to specify the file name as well. Add `/keepassxc.ini` to the end.

**Comment by ourichermath** [comment]
So, not just the location of the cache, but the location of KPXC's part of it?  i.e.:

KPXC_CONFIG_LOCAL=/home/dave/.cache/keepassxc.ini

?  Or, would it include a folder name?  i.e.:

KPXC_CONFIG_LOCAL=/home/dave/.cache/keepassxc/keepassxc.ini

?  That's how it's structured in ~/.config.  Of course, I swear I saw those things in the ~/.cache folder earlier.  But, now I don't.

**Comment by droidmonkey** [comment]
Technically you don't need to specify this at all because the default location is `~/.cache/keepassxc/keepassxc.ini`

Just delete your env var definition and everything will work....

**Comment by ourichermath** [comment]
The problem was that it wasn't working.  In an attempt to get it to work, I added the env var definition.  But, since I didn't check that the non-env-def version worked once I'd delete the old KPXC stuff in .cache, I'll do that and see if it shakes something loose.

I'll be back. :)

**Comment by ourichermath** [comment]
That got it.  Or at least close enough that the difference I think I'm seeing could be mere delusions on my part.  I removed the "KPXC_CONFIG_LOCAL=" from /etc/environment and let the ~/.cache repopulate with the keepassxc/keepassxc.ini file after a reboot.  Now, KPXC sort of remembers my last database.  Down at the bottom of the "Welcome to KeePassXC 2.7.1" window, the Recent Databases section is now populated with my database.  So, all I have to do is double-click on that, sign in, and KPXC comes up properly (windows and columns and all).  The only difference is that I THOUGHT it used to start up right in the password entry screen and I didn't have to double-click on my database.  But, again, I could be imagining things.

Thanks.  I'll close this now.

EDIT:  and let me summarize what I think happened:  I'm guessing the keepassxc.ini file under ~/.cache got corrupted.  If I had deleted it first instead of first adding an environment variable, then I'd bet after a reboot things would have been fine.  Instead, I messed things up by doing the env var first.

**Comment by droidmonkey** [comment]
When you exit keepassxc just close the window / quit. If you close the database (so it shows the welcome screen) then exit keepassxc then it won't re-open that database. Just leave everything open, quit, restart keepassxc... everything will be as you saw it.
