### ISSUE TITLE
Browser access request prompt is not a popup-dialog window

### ISSUE THREAD

**Issue by WhyNotHugo** [keepassxreboot/keepassxc#8033]
## Overview

When using a tiling compositor, the "Browser Access Request" prompt is not treated as a popup / dialog window, but rather as a normal window.

This makes it get tiled as other top-level windows. E.g.: If I have my browser taking up all the screen, the Browser Access Request opens up as a huge window taking up half the screen.

## Steps to Reproduce

I can reproduce this on swaywm. I expect that the same issue is reproducible on i3wm, but don't have an X11 setup to confirm this.

1. Run KeePassXC and a browser with the plugin installed
3. Attempt to auto-fill somewhere (make sure the entry has not been previously authorised).

## Expected Behavior

A reasonably sized prompt should show up.

## Actual Behavior

The prompt shows up as a regular window which gets tiled to occupy a huge part of the screen.

## Context

KeePassXC - 2.7.1

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: swaywm
Windowing System: Wayland

## Extra notes

The popup shown with the "Show OTP" menu option works fine. It would seem the properties used to declare that one as a "small floating popup" work fine, so should work okay for this other popup too.

**Comment by droidmonkey** [comment]
Does the Auto-Type selection dialog do the same? The TOTP dialog, Auto-Type dialog, and Browser Confirmation dialog are all QDialog decedents. The only difference I can spot between the TOTP compared to the others is that the others are set to be "Always on Top".

**Comment by WhyNotHugo** [comment]
When KeePassXC is locked, if I click on the browser plugin button, and click "Reopen database" I get a popup to provide credentials. That one works properly.

> Does the Auto-Type selection dialog do the same?

Does this work on Linux/Wayland? I can't find how to trigger this.

> The TOTP dialog

This one works perfect.

> The only difference I can spot between the TOTP compared to the others is that the others are set to be "Always on Top".

AFAIK, the concept of a client declaring itself "always on top" is not supported on Wayland. This is mostly reserved for privileged clients. Not sure what Qt does in this case.

**Comment by WhyNotHugo** [comment]
I used `gammaray` to debug this a bit more. It was tricky due to all the 1px wide controls, but I managed.

I see only two difference between windows that render as floating popups vs window that render as regular desktop windows, the `flags` attribute (sorry for using screenshots, gammaray won't let me copy-paste):

![image](https://user-images.githubusercontent.com/730811/180642122-32bdea32-10f0-4d6c-a828-605e06439d52.png)

![image](https://user-images.githubusercontent.com/730811/180642127-ed039c44-5d2c-4686-8d6b-d9548fc5aea9.png)

I don't think this flag could be the cause of this issue.

The only other difference is are `visibility` and `windowState` properties.

![image](https://user-images.githubusercontent.com/730811/180642150-4a3641e0-825d-40f7-ae0b-4dfc003ab04e.png)

![image](https://user-images.githubusercontent.com/730811/180642152-0076d322-383f-494b-99e5-9a4b52ebdd8a.png)

I suspect one of the latter two is the curlpit here.

**Comment by droidmonkey** [comment]
Yah that's likely how Qt is dealing with the always on top hint in the tiling window system.... time for another bug report to them?

**Comment by WhyNotHugo** [comment]
When I trigger a "unlock database" from the browser extension, that shows a pop-up correctly prompting me for the passphrase.

But the next window (the one where I confirm granting the browser access to the credentials) renders as a non-pop-up (and gets tiled).

I don't think this is a Qt bug, maybe there's a difference in how each window is created on the keepass side? Are both created as always on top?

**Comment by droidmonkey** [comment]
The DatabaseOpenDialog which shows that first window is set to be always on top on Linux: https://github.com/keepassxreboot/keepassxc/blob/develop/src/gui/DatabaseOpenDialog.cpp#L39-L42

The BrowserAccessConfirmDialog is also set to be always on top on all platforms. https://github.com/keepassxreboot/keepassxc/blob/develop/src/browser/BrowserAccessControlDialog.cpp#L31

**Comment by WhyNotHugo** [comment]
I see `DatabaseOpenDialog` has `setWindowFlags(Qt::Dialog);`, whereas `BrowserAccessControlDialog` does not. Lemme see if that's the cause.

**Comment by WhyNotHugo** [comment]
No, that doesn't seem to be it.

**Comment by WhyNotHugo** [comment]
What parent is each one defining? (sorry, my understanding of C++ isn't quite enough to figure that out).

Do they have different parents?

**Comment by droidmonkey** [comment]
It should be the MainWindow, but need to look at where these are being instantiated to figure that out. 

Based on the Qt docs, if a QDialog has a parent that just means it is centered over that parent's window. Lacking a parent it's placed at the discretion of the window manager.

**Comment by WhyNotHugo** [comment]
The creation of `DatabaseOpenDialog` seems to explicitly pass a parent: https://github.com/keepassxreboot/keepassxc/blob/develop/src/gui/DatabaseTabWidget.cpp#L43

But `BrowserAccessControlDialog` does not: https://github.com/keepassxreboot/keepassxc/blob/develop/src/browser/BrowserService.cpp#L422

I'm not totally familiar with the syntax of these constructors; they both take a `parent` argument, but one of these calls doesn't specify one. Does that make it implicitly `null`, or am I misreading this?

**Comment by droidmonkey** [comment]
Correct it is implicitly `nullptr` if nothing is passed. That might be the difference!

**Comment by WhyNotHugo** [comment]
A popup/modal dialog MUST have a parent defined, otherwise it won't render as a popup but as a top-level window (which is the issue at hand).

I can't find the source for this rule right now, but I'm pretty sure that passing a parent should fix the issue at hand.

**Comment by WhyNotHugo** [comment]
I've no idea how to pass the right parent in that context.

**Comment by WhyNotHugo** [comment]
Can confirm that https://github.com/keepassxreboot/keepassxc/pull/9652 fixes the issue for both the "database unlock" and "access request" dialogs.
