### ISSUE TITLE
Column sorting is not saved after showing expired entries 

### ISSUE THREAD

**Issue by syakovyn** [keepassxreboot/keepassxc#8036]
## Overview
I sort entries by Title. However, it is not kept after relaunching the app.

Before restarting the app:
<img width="749" alt="image" src="https://user-images.githubusercontent.com/417162/167806012-b86e6116-416c-4c0c-a077-3325750a005f.png">

After restarting the app:
<img width="732" alt="image" src="https://user-images.githubusercontent.com/417162/167803247-2a243eba-90dc-4f45-ac0e-3d342b93b00a.png">

## Steps to Reproduce
1. Start the app
2. Open a group with entries.
3. Click on a column header to sort by that column.
4. Lock the database and exit or just immediately exit.
5. Open the app again. Go to the same group.

## Expected Behavior
Entries are sorted.

## Actual Behavior
Entries are not sorted.

## Context
Checked the suggestion from https://github.com/keepassxreboot/keepassxc/issues/7686#issuecomment-1079905231 for `~/Library/Caches/KeePassXC/keepassxc.ini` as I'm on Mac. But, it is not applicable as it is not on a RAM disk.
Tried removing `keepassxc.ini` but that didn't help either.

KeePassXC - Version 2.7.1
Revision: 5916a8f

Qt 5.15.2
Debugging mode is disabled.

Operating system: macOS 12.3
CPU architecture: arm64
Kernel: darwin 21.4.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 2.19.1

**Comment by droidmonkey** [comment]
Delete the cache ini and reopen keepassxc, sometimes it gets corrupted.

**Comment by ba32107** [comment]
I have the same problem, on Ubuntu. I tried removing the cache ini, but it didn't help.

Steps I followed:
 1. KeePassXC open, sort order is messed up
 2. Sorted the columns
 3. Made a dummy change, so the DB is saved
 4. Deleted the cache ini
 5. Closed & reopened KeePassXC
 6. Expired entry virtual group shows
 7. When leaving the virtual group, order is messed up

If I take care of the expired entries (step 6 never happens), then the order is correct. So, I'm pretty sure the problem is related to the expired entry group.

**Comment by sandwm** [comment]
I can confirm that not showing the expired / about to expire entries works around the problem:  
Tools -> Settings -> General -> disable "On database unlock, show entries that ..."

**Comment by droidmonkey** [comment]
I am fixing this with my tag enhancement PR.

**Comment by user23498723452** [comment]
> I can confirm that not showing the expired / about to expire entries works around the problem: Tools -> Settings -> General -> disable "On database unlock, show entries that ..."

This does not work for me to fix the issue.  Column sorting is ignored,  as is "last folder selected" - which should be a default feature.
