### ISSUE TITLE
Automatically fit columns to window

### ISSUE THREAD

**Issue by Offerel** [keepassxreboot/keepassxc#8037]
## Summary
Currently we can choose from the menu, after right click the column headers in the entry list, to fit the columns to the window. This the window resizes, the process has to be started again. It would be nice to have an option, where "Fit to window" automatically is recalled, then window is resized/maximized/minimized and so on.

## Context
I have often to resize the window or maximize/minimize it or move the window from one monito to another. Sometimes i miss some columns, before i remember that i have to resize the columns first, to show them.

**Comment by droidmonkey** [comment]
Also described in #7945

**Comment by Offerel** [comment]
Ok, then i close this one and subscribe to the other. Sorry, havent seen the other one.
