### ISSUE TITLE
Set minimum entropy for Passwords

### ISSUE THREAD

**Issue by us4r01d** [keepassxreboot/keepassxc#8038]
I would like to have an option to set a minimum Password Entropy for new generated Passwords. The Password Generator could then also choose the minimum password length by itself.

e.g. i want a password with an entropy of at least 200 with upper/lower case letters, numbers and special characters. The generator then selects by itself. a password length of e.g. 32 characters and outputs a password with an entropy of at least 200.

**Comment by droidmonkey** [comment]
Been discussed before. This also overlaps with the request for password profiles planned for 2.8.0.
