### ISSUE TITLE
Accidental exit prevention

### ISSUE THREAD

**Issue by sengsational** [keepassxreboot/keepassxc#8039]
## Summary
Add an application setting that will issue an "are you sure" dialog before program exit.

## Context
Very often I close KeePassXC when I don't want to.  Maybe it's because I'm overly dim, but here's one scenario (there are others) that causes an unwanted program exit.
* Credentials are not populated in the browser because of a URL variation > URL captured to system clipboard
* In KeepPassXC (Windows), the site name is entered into the search box > edit entry > Browser Integration > Add > (system clip board pasted) > OK

The filtered list, with just one or a few entries is left and the user goes back to the web browser and allows keepassxc-browser to populate the credentials.  Later, when work in the web browser is done, the user sees the filtered list and "doesn't want a filtered list" clicks the Windows "x", which closes the program without warning.  Of course the correct thing to do is to click the button to clear the search, and in fact, if the user waits long enough, the search seems to clear itself.  But what has happened to me many times is, without thinking, I close KeePassXC by mistake.  If there were a warning, I wouldn't have to do a forehead slap and restart the program.

## Proposal
Upon request to close the application, a dialog would include buttons that would offer the user to CLOSE the application, MINIMIZE the application window, or CANCEL and do nothing.

**Comment by droidmonkey** [comment]
You can enable "minimize instead of close" in application settings.

**Comment by sengsational** [comment]
That works!  Thanks.  That setting got past me.
