### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by 31337-4554551n** [keepassxreboot/keepassxc#804]
## Expected Behavior

There to be a dark theme option
## Current Behavior

There is no such option
## Possible Solution

Create such an option
(alternatively/preferably create an official apt repo instead(as well as) of snaps so it can use the system themes)
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

To make it easier on the eyes. As there issues with secure auto type, I keep the manager open and use it manually
## Debug Info

KeePassXC - Version 2.2.0
Revision: 9a7e6850d6b79c47c2d46d99fdaf433c2ff13716

Libraries:
- Qt 5.7.1
- libgcrypt 1.7.6-beta

Operating system: Ubuntu Core 16
CPU architecture: x86_64
Kernel: linux 4.8.0-58-generic

Enabled extensions:
- KeePassHTTP
- Auto-Type
- YubiKey

**Comment by phoerious** [comment]
This one is unlikely to be implemented, but I'll keep it open for now.

**Comment by TheZ3ro** [comment]
KeePassXC use the system theme, if your theme is light KeePassXC will be light. 

I personally don't really like custom theme since they don't respect the desktop design

**Comment by 31337-4554551n** [comment]
It is nice that it works off the system theme. However there is no official apt repo, so to get it working officially on ubuntu you need to use snaps, which don't respect system themes. It would be nice to have this option for people having to work with snaps.

**Comment by ccoenen** [comment]
If snaps don't respect the system, this is something that should be raised with ubuntu.

**Comment by Zerqz** [comment]
On Linux the colour theme usually changes KeepassXC. For me on KDE it does anyway.

**Comment by arigit** [comment]
If you are running Fedora 26, you can install the adwaita-dark QT theme

sudo dnf install adwaita-qt5

If after that keepassxc doesn't pick up the dark theme, you can adjust your launcher:

keepassx -style adwaita-dark

The blend / integration on  GNOME with adwaita-dark is really neat.

**Comment by TheZ3ro** [comment]
Closing since KeePassXC will automatically get the system theme

**Comment by droidmonkey** [comment]
@solikeumyeah that is a totally different issue, Mojave dark theme only works if the app is compiled under mojave.

**Comment by NikkyAI** [comment]
is windows being considered? in windows even when the system theme is configured as using black theme,
most apps do nto pick up on it and the old color and theme options got removed

**Comment by Danny3** [comment]
I've been using KeepassX on Kubuntu for some time (now version 18.10).
Everything was ok with it, but today I found out about this fork, which I tried it for a few minutes until I got disappointed and frustrated that it keeps showing a white themed when i have everything configured for a dark theme.
I don't understand why KeepassXC is called and improved version of KeepassX, when KeepassX is the one where the dark themes work as expected.
I installed both KeepassX and KeepassXC from Discover and indeed KeepassXC is the snap version because that's the only one available.

**Comment by Danny3** [comment]
In that case it's a shame that qt5 is not as developed or good as qt4.
Unfortunately I don't have the time or the will to theme a program properly for my desktop env as in the end all will be in vain since one day I'll have to reinstall / upgrade the OS and all my tweaks will be lost.
From what I saw, pretty much all the programs that I have installed follow my dark theme preference, even the ones that are built with GTK I think.
In any case I'm staying with the other version until the issues are solved in Qt, KDE, here, etc.
Thanks anyway for the reply!

**Comment by droidmonkey** [comment]
It's quite simple actually, just install qt5ct and set the following environment variable in your profile: QT_QPA_PLATFORMTHEME=qt5ct.

**Comment by ccoenen** [comment]
This program is barely ever visible in a regular (i.e. auto type) workflow. This is just not important. If I had to choose[1] what the dev team works on and what is included in the program, I'd HAPPILY take security or stability or compatibility or anything else over "theming".

I am *glad* the devs don't add things like that, bloating this program with stuff that is better solved at a higher level. Concluding based on one factor that you don't like, that something is not "as developed" is pretty superficial.

[1] Hint: I can't and I don't. I'm just a regular user.

**Comment by kuon** [comment]
I suggest you look into https://github.com/tsujan/Kvantum/tree/master/Kvantum which works fine with keepassxc.

Just ensure your keepassxc is started with the QT_STYLE_OVERRIDE=kvantum environment variable.

**Comment by mendhak** [comment]
Future searchers who ended up here like me, have a look at:
https://www.linuxuprising.com/2018/05/get-qt5-apps-to-use-native-gtk-style-in.html

    sudo apt install qt5-style-plugins
    echo "export QT_QPA_PLATFORMTHEME=gtk2" >> ~/.profile

Then login again or reboot. Relaunch keepassxc and it should be dark.

**Comment by jeffmcneill** [comment]
~~~
sudo apt install qt5ct
~~~

Restart/Relogin

Then set preferences under *Menu > Preferences > Qt5 Preferences > Appearance*:

- Style = gtk2
- Standard dialogs = GTK2
- Palette = Default

**Comment by s4dic** [comment]
> If you are running Fedora 26, you can install the adwaita-dark QT theme
> 
> sudo dnf install adwaita-qt5
> 
> If after that keepassxc doesn't pick up the dark theme, you can adjust your launcher:
> 
> keepassx -style adwaita-dark
> 
> The blend / integration on GNOME with adwaita-dark is really neat.

works with ununtu :)

**Comment by sam1902** [comment]
> > If you are running Fedora 26, you can install the adwaita-dark QT theme
> > sudo dnf install adwaita-qt5
> > If after that keepassxc doesn't pick up the dark theme, you can adjust your launcher:
> > keepassx -style adwaita-dark
> > The blend / integration on GNOME with adwaita-dark is really neat.
> 
> works with ubuntu :)

And Debian, and PureOS for that matter

**Comment by phoerious** [comment]
KeePassXC 2.6.1 has its own dark theme.

**Comment by DanielMzLz** [comment]
> KeePassXC 2.6.0 has its own dark theme.

For some reason it seems to have broken system themes though :/
Used to have work with Kvantum's (KDE) set theme but now it overrides to use its own. Is there a way to change this?

**Comment by droidmonkey** [comment]
Use classic mode

**Comment by DanielMzLz** [comment]
> There is a bug with that we fixed in upcoming 2.6.1

I didn't expect such a fast reply wow! Thank you, your software is amazing :)
