### ISSUE TITLE
Edit multiple entries in batch

### ISSUE THREAD

**Issue by Pysis868** [keepassxreboot/keepassxc#8040]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
To update general information in common with multiple selected entries at once.

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )
To enable non-unique features such as Browser Integration's Hide entry or Skip Auto-Submit data flags.

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
More conveniently/efficiently cleaning my database.
This may be similar to #4533, but that solution my have been too specific?

**Comment by droidmonkey** [comment]
Duplicate request #1314
