### ISSUE TITLE
Request to make KeePssXC support Flatpak versions of browsers?

### ISSUE THREAD

**Issue by linlinxza** [keepassxreboot/keepassxc#8043]
## Summary
I was wondering if supporting Flatpak versions of web browsers is possible.

## Examples
From what I get, flatpak-spawn can be used to open apps on the host. Maybe what could be added is a checkbox for Flatpak version support?

Then the native host can run a command like this?

flatpak-spawn --host /usr/bin/flatpak run --branch=stable --arch=x86_64 --command=keepassxc-proxy org.keepassxc.KeePassXC "$@"

## Context
Why does it matter? I am trying to move away from external PPAs that could potentially break my system.

**Comment by droidmonkey** [comment]
It's not possible without flatpak adding a portal or similar specifically for native messaging. This is not a keepassxc problem to solve.
