### ISSUE TITLE
Network disk synchronization is not timely problem

### ISSUE THREAD

**Issue by OR120** [keepassxreboot/keepassxc#8044]
Keepassxc on the computer directly opens the file in the network disk webdav,
The mobile phone is synchronized with keepassDX+ network disk.
The problem is that after the entry is added on the computer, the mobile phone is not synchronized in time.
Then the mobile terminal adds an entry and synchronizes again.
The result is that the added entries on the computer are lost.
How to solve this problem. This problem has been around for several years

**Comment by droidmonkey** [comment]
Don't use webdav, use a modern cloud hosting solution or your own using nextcloud or syncthing
