### ISSUE TITLE
KeePassXC 2.6.6 crashes when fourth letter is tried to be entered in the search window- the sequence is: "cyfr" 

### ISSUE THREAD

**Issue by Yarrroslav** [keepassxreboot/keepassxc#8045]
## Overview
KeePassXC 2.6.6 crashes when fourth letter is tried to be entered in the search window - the sequence is: "cyfr"

## Steps to Reproduce
THE SEARCH WINDOW: Entering "cyf" and any other tried sequence of even more letters - works. 
Entering "cyfr" causes crash of the application. 

## Expected Behavior
Not to crash, when entering the sequence of any characters into the search window

## Actual Behavior
It crashes. Tried 5 times. 
Other sequences of characters I tried - do not cause this. 

## Context
Any.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - KeePassXC - Wersja 2.6.6 
Revision: 9c108b9
Qt 5.15.2
Tryb debugowania jest wyłączony.

[NOTE]: 
Operating System: Windows
System operacyjny: Windows 10 Version 2009
Architektura procesora: x86_64
Jądro: winnt 10.0.19044

**Comment by droidmonkey** [comment]
Update to 2.7.1 and try again

**Comment by Yarrroslav** [comment]
Updated.
The same happens.
The window as below appears:
[image: image.png]



czw., 12 maj 2022 o 11:54 Jonathan White ***@***.***>
napisał(a):
