### ISSUE TITLE
Delete favicon not possible anymore

### ISSUE THREAD

**Issue by simonschaufi** [keepassxreboot/keepassxc#8046]
## Overview

In previous versions it was possible to delete favicons again, but now it is gone. I have some duplicate favicons which I would like to delete.

KeePassXC - Version 2.7.1
Revision: 5916a8f

**Comment by droidmonkey** [comment]
You can remove unused icons from Database Settings -> Maintenance

**Comment by simonschaufi** [comment]
ok, thank you for the info.
