### ISSUE TITLE
Unable to name sharing container when exporting a group

### ISSUE THREAD

**Issue by Engrammae** [keepassxreboot/keepassxc#8048]
## Overview
After specifying a path to save the sharing container in order to export a group a different path is displayed. Thus I can't specify the directory of my choice. After typing in a password and hitting ok no container is created under the given path.

## Steps to Reproduce
1.  Go settings and allow _export_ and _import_ in the KeeShare category
2.  Edit a group and select _export_ as type in the KeeShare category
3.  Click on browse to specify a path, select a sudirectory of $HOME, type in a container name _demo-test_,  press enter or click save 
4. Specify a password
5. Finish the export by hitting _OK_

## Expected Behavior
1. The path I selected is displayed after saving the path.
2. The created container holds the path and name as specified

## Actual Behavior
1. Regardless of the path specified the selected path shown before defining a password is _/run/user/1000/doc/some-numbers/demo-test.kdbx_ 
![image](https://user-images.githubusercontent.com/74217235/168080170-475e52d3-0a08-4300-a0fb-1073b93f62d2.png)

2.  Sometimes a container is created in the directory _/run/user/1000/doc/some-numbers/demo-test.kdbx_, sometimes in the specified directory. However it has a different name then.
3. The export path is displayed: 
![image](https://user-images.githubusercontent.com/74217235/168077122-96d52f99-449a-4ee1-9ddd-4f467faa7464.png)

## Context
Till a few days ago I used the an old version (2.4.3) of keepassxc kept in the official directory of the official Ubuntu repository 20.04.. Then i purged the _.deb_ package and autocleaned. After that I installed the snap. Don't know whether it's related though!

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.1
Revision: 1563

[NOTE]: # ( Pick choices based on your environment )
Operating System: Ubuntu 20.04.4
Desktop Env: Gnome 3.36.8
Windowing System: X11

## Workaround
Create an empty file and select that path. Then the export works, but the output shown in the picture stays the same

**Comment by droidmonkey** [comment]
This is expected behavior for snaps because your files are actually going through a portal which is why you see the different path.
