### ISSUE TITLE
Make User presence check with Windows Hello optional/configurable

### ISSUE THREAD

**Issue by Sebi2020** [keepassxreboot/keepassxc#8051]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
Currently the Windows Hello check is enforced (since the new release of Keepass XC). It would be nice if the user would have the option to disable this.

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )
N/A

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )

I use a security key for my Keepass XC database. So there is always a presence check included. You have to know your master password + have to provide the security token.

If you use a security token you have to dig into multiple dialogs before you can open the database. This is really annoying. Password + Security Key + Windows Hello PIN / Fingerprint. Therefore I think this should be an optional feature. Not a required one.

**Comment by droidmonkey** [comment]
Disable it in the application security settings

**Comment by Animadei** [comment]
> Disable it in the application security settings

Tools -> Settings -> Security -> Convenience -> Enable database quick unlock (Touch ID / Windows Hello)

Which option allows enabling quick unlock with Hardware Key only because since Windows Hello entering user login password + touching the hardware key is getting real old real fast and nobody has time for this junky junk solution when touching the hardware key is sufficient to prove user presence.

**Comment by Fufu-btw** [comment]
Hi, 
I've tried to do this version 2.7.4, but the option "Enable database quick unlock" is not in the path that @Animadei mentionned. 
Should i modify my keepassxc.ini in appdata or may i find this option in another path ?

**Comment by droidmonkey** [comment]
If you don't see the checkbox in the settings then that means your system is saying windows hello or touchid is not available and quick unlock will not be an option.
