### ISSUE TITLE
Auto-Type convert all letters in password to upper case when used in Microsoft Remote Desktop

### ISSUE THREAD

**Issue by bw7715** [keepassxreboot/keepassxc#8052]
## Overview
When I try paste my password in Remote Desktop Application all letters are converted to upper case.
E.g.
my password: 'abc'
pasted password: 'ABC'

## Steps to Reproduce
1. Start Microsoft Remote Desktop
2. Click 'Saved PCs' -> ... -> Start in this window
3. Click on password field after 'Unlock the PC' message
4. Go to KeePassXC
5. Right-Click -> Perform Auto-Type -> {PASSWORD}
6. Perform Auto-Type into the previously active window? Click 'Yes'

## Expected Behavior
The pasted password should be identical to the one saved.

## Actual Behavior
All letters in pasted password all capital.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.1
Revision: 5916a8f

Qt 5.15.3
Debugging mode is disabled.

Operating system: Windows 10 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.19044

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 2.18.1

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 10

**Comment by droidmonkey** [comment]
You might have caps lock turned on in the remote pc or you need to use virtual keyboard typing. Read the user guide for more info on virtual mode typing.
