### ISSUE TITLE
KeePassXC saving issues, major problem

### ISSUE THREAD

**Issue by Kobi-Blade** [keepassxreboot/keepassxc#8053]
## Overview
Ever since the latest update, KeePassXC is having issues saving changes to my database, to the point I lose entire new entries. I pretty much just lost access to one of my accounts cause KeePassXC no longer has the TOTP entry I setup the other day.

## Steps to Reproduce
1.  Make changes to database (new entries, totp codes, new passwords).
2.  Get surprised as you try to access that data later and it's gone from database.

## Expected Behavior
I expect KeePassXC to properly save the database with all the details without losing data.

## Actual Behavior
KeePassXC is not saving the database properly and is missing details (whole entries, passwords and more concerning TOTP entries), this does not affect older entries however as this issue is related to the latest update and the way KeePassXC saves new entries.

## Context
KeePassXC - Version 2.7.1
Revision: 5916a8f

Qt 5.15.3
Debugging mode is disabled.

Operating system: Windows 10 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.19044

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 2.18.1

**Comment by droidmonkey** [comment]
> this does not affect older entries however as this issue is related to the latest update and the way KeePassXC saves new entries.

That is not how the program works at all. Every entry is saved the same and to the same file. The age of the entry is not relevant. 

Ensure you don't have a cloud sync that is overwriting your database file back to an older version erroneously. You should also enable backups.

**Comment by Kobi-Blade** [comment]
> > this does not affect older entries however as this issue is related to the latest update and the way KeePassXC saves new entries.
> 
> That is not how the program works at all. Every entry is saved the same and to the same file. The age of the entry is not relevant.
> 
> Ensure you don't have a cloud sync that is overwriting your database file back to an older version erroneously. You should also enable backups.

There's nothing overwritting the base besides KeePassXC, I can only tell what the issue is not what is causing it.

Fact remains a few days ago I lost an entire new entry (which I had to recover through mail), and today I lost a OTP code (making me lose entire access to an account), to say I'm frustrated is to put it lighty.

None of this was happening before the 1.7.1 update (which I only updated recently and was when the issues started).

**Comment by droidmonkey** [comment]
Are you sure you saved? Not too be flippant but specific entries and attributes just don't go missing, we'd have quite a few angry users including myself. Run a few tests and see if it continues to happen.

**Comment by Kobi-Blade** [comment]
> Are you sure you saved? Not too be flippant but specific entries and attributes just don't go missing, we'd have quite a few angry users including myself. Run a few tests and see if it continues to happen.

I'm 100% sure I saved, and I have auto saves enabled as well.

**Comment by droidmonkey** [comment]
Do you save to your hard drive, usb stick, network share? Are you using normal saves or the alternative ones (temp file and direct write)? Do you have files in the directory with your database that have your databases name with a funny extension?

**Comment by Kobi-Blade** [comment]
> Do you save to your hard drive, usb stick, network share? Are you using normal saves or the alternative ones (temp file and direct write)? Do you have files in the directory with your database that have your databases name with a funny extension?

Is on hard drive, normal saves, and no funny extensions, plus was working fine before update.

**Comment by droidmonkey** [comment]
You can downgrade your install. Have you tested making a series of changes again to see if they save properly? Have you looked in the history of entries you thought you configured to see if it's saved there?

**Comment by Kobi-Blade** [comment]
> You can downgrade your install. Have you tested making a series of changes again to see if they save properly? Have you looked in the history of entries you thought you configured to see if it's saved there?

I rather not make changes to avoid losing another account, the history has no records of OTP, and I'm going to downgrade KeePassXC to avoid further issues.

**Comment by droidmonkey** [comment]
You should retain backups of your database. There is absolutely no harm in copying the database file and running tests on the copy. Closing this since there is not much we can do here.

**Comment by dariopuerot** [comment]
I am having the same kind of problem.

Sometimes the database does not save and cannot be closed.

In Spanish it shows this warning:
"Fallo al escribir la base de datos: Guardado de la base de datos actualmente en proceso."

When this message shows a backup cannot be saved, neither.

I do not know what triggers this.

I am using keepass2android with the same database, and share it via Onedrive.

DEBUG INFO
KeePassXC - Version 2.7.1
Revision: 5916a8f

Qt 5.15.3
Debugging mode is disabled.

Operating system: Windows 10 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.19044

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 2.18.1

**Comment by droidmonkey** [comment]
Use an alternative saving method, you can set this up in application settings. It is also covered in the user guide.

**Comment by dariopuerot** [comment]
thank you very much.

When searching for a solution in the internet I was directed to this case
and not to the user guide.

Kind regards

Darío Puertas
_________________________________________________________________
Darío Puertas Otones :: ***@***.*** :: +34 655 048 676 :: skype:
dariopuertasotones

**Comment by Kobi-Blade** [comment]
You issue is related to OneDrive and is covered in user guide, my issue is with KeePassXC itself, I haven't had the problem since I rolled back.
