### ISSUE TITLE
No Recent databases list

### ISSUE THREAD

**Issue by ghost** [keepassxreboot/keepassxc#8054]
## Overview
Recent databases opening doesn't work - there are no items in the Recent list to select.

## Steps to Reproduce
1. Open a database. Actually _the_ database, since I have only one. This bug is about me having to always go through the Open dialog box, which is stressful for a mostly keyboard user like me.
2. Save the database. I can make a trivial change before saving, or not. The behavior after this doesn't change.  
3. Click on the File menu in the main menu bar.

## Expected Behavior
I expected the database which I have just closed to appear in the Recent databases submenu, and in a list widget in the main KP panel. 

## Actual Behavior
The submenu which opens from the Recent databases menu is empty, and there is no Recent databases list in the main panel at all.

## Context
It is possible this is because I have Spotlight (the looking glass thing) completely disabled. I read somewhere that the index Spotlight creates is used for the Recent files lists. On the other hand, I have a Recent item in many other apps I use and it works.

## Platform versions
KeePassXC: 2.7.1
Operating System: macOS
Desktop Env: Big Sur

**Comment by droidmonkey** [comment]
Do you have the application setting to remember recently opened databases enabled?

**Comment by ghost** [comment]
I see no such setting in the Preferences. Maybe that is the real bug?

**Comment by phoerious** [comment]
Settings -> Remember previously used databases.

**Comment by ghost** [comment]
Now I see it, thank you. I think one reason why I missed it is the unfamiliar dark background style. Can it be changed?

**Comment by droidmonkey** [comment]
What do you mean? Just enable it.
