### ISSUE TITLE
A random new database is automatically being created each time an edit is applied

### ISSUE THREAD

**Issue by genericbar** [keepassxreboot/keepassxc#8056]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
Main database file is being randomly duplicated each time an edit is done. This is also applying the latest changes to this new random file instead of the original main database file, effectively making outdated.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. This a tough one as it started doing this out of nowhere, even after downloading a new installation package from the website., so no idea how to provide clear steps for this - sorry!

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
For any changes to be applied to the currently opened file (eg: test.kdbx) instead of creating a new random file (eg: test.kdbx.mAQiFB).

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Main database file is being randomly duplicated each time an edit is done. This is also applying the latest changes to this new random file instead of the original main database file, effectively making outdated.

## Context
[NOTE]: # ( Give us any additional information you may have. )
![signal-2022-05-14-220105_001](https://user-images.githubusercontent.com/23086343/168448549-aa1b2f20-62a1-4b7a-bafa-1992d43c1808.png)

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.1 x64 Portable
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 10

**Comment by droidmonkey** [comment]
That means your actual database file cannot be overwritten. Check your file permissions. Where are you trying to save this to? Cloud storage, usb drive, network drive, hard drive? 

You can try enabling the alternative saving methods in the application settings.

**Comment by genericbar** [comment]
File permissions are fine and being saved to the local storage. I've compared the settings and permission of this machine to a different one with the same settings and permissions, and I'm not getting this issue there.

Enabling the alternative method worked for saving the changes to the same database file. However, in the process of trying this, I've realised that the `keepassxc.ini` and the `keepassxc_local.ini` files in the config folder are suffering from the same duplication issue, simply from running the program, so each time I re-open the app all settings are forgotten, including the alternative method. Please see screenshot below for reference:

![image](https://user-images.githubusercontent.com/23086343/168486517-9a852f8a-66a1-47ea-bbcf-b82fd9462c73.png)

**Comment by droidmonkey** [comment]
You must have some very strange issue with your file system. This isn't a problem with our program, if anything it would be an issue with qt file handling. Nothing we can fix here, recommend deleting the entire portable install and try again

**Comment by genericbar** [comment]
I've done so and the issue still persists, but this behaviour is only happening with KXC and no other program.

**Comment by droidmonkey** [comment]
The files shown are based on qt's QSaveFile strategy which creates a temporary file and then deletes the original and moves the temporary one in its place. You are not going to see this in any other program unless they do this method.
