### ISSUE TITLE
Add ability to sync group structure with KeeShare

### ISSUE THREAD

**Issue by rodrigovda** [keepassxreboot/keepassxc#8058]
## Summary
The "Keeshare" functionality is a potentially very useful one, but although you made clear why folder structure isn't preserved, the use case you describe for KeeShare isn't what a lot of us need:

https://github.com/keepassxreboot/keepassxc/issues/3045

I want to implement in my company some hierarchical security structures.

[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )

## Examples
For instance:
Alice's division have their own entries: Banking, Computer credentials, online accounts (each is a different sub-group).
Bob's division have their own entries: TeamViewer credentials, Anydesk Credentials, Computer credentials
Charlie (me) is the company's IT specialist in charge of all the security of the company, so he has it's entries but it mut have access to all (or some) of Alice's & Bob's credentials too.
 let's say this are two entries in Alice's db:
Group=root\\"Remote Control"\TeamViewer
Title=Maria-PC
Username=884555884
Password=**********

Group=root\\"Remote Control"\Anydesk
Title=Maria-PC
Username=474555844
Password=**********

Notice how, if you don't see the group they're in, you don't know what they're for.

So as of how KeeShare works now, Charlie opens his db and sees how Alice just added this two new entries, they're both in the root folder, and now he doesn't know what they're for, and even if he knows they're for remote control he doesn't know which software should he use.

Besides this, even if he figured out that one is for TeamViewer and the other is for Anydesk, each time a new entry is added, he MUST manually reorganize the new entries himself, which is annoying to do for every single small account.

This also happens the other way around: Charlie has just made a new entry for someone in Alice's division:

Group=root\\"Alice's division (synced)"\server\\"SMB credentials"
Title=John
Username=JohnDoe
Password=**********

Now when Alice enter's her db, she sees that the new entry is in her root folder, and has to both guess what that entry is for and manually put it in the correct group.

For this kind of usage, it makes sense to let KeeShare preserve group structure, so they don't have to keep manually organizing all entries. It should work more as a "db mirror".

I know that your philosophy is to let anyone order the entries as they please, but in a lot of cases it's more valuable to **not waste time** and just agree to some specific common structure or to abide by someone else's criteria.

By refusing to enable group structure syncing YOU are enfonrcing everyone to use KeeShare the way YOU want it, not the way THEY need it.

**Comment by rodrigovda** [comment]
I am sorry I just realize that the issue I mentioned is still open, shoul I have just posted this there insted of opening a new one?

**Comment by rodrigovda** [comment]
Apparently KeePass has already a plulgin that does this:
https://github.com/Angelelz/KeePassMasterSlaveSync

**Comment by droidmonkey** [comment]
I recommend you use auto open. The only difference between keeshare with group structure (which is being worked by me) and auto open is that auto open has databases in multiple tabs. Still will work great with browser extension and Auto-Type though.
