### ISSUE TITLE
TOTP available in Auto-Type sequence

### ISSUE THREAD

**Issue by Slethen** [keepassxreboot/keepassxc#806]
When using the Auto-Type having your TOTP key as an option in a custom sequence would make the functionality feel more complete.

Operating system: Fedora
CPU architecture: 86_64
Kernel: 4.11

**Comment by phoerious** [comment]
You can do that already. Just add {TOTP} to your autotype sequence.

**Comment by Slethen** [comment]
Ohh no sorry about that! Great work though awesome feature
