### ISSUE TITLE
Column Sort Needs Case-Insensitive Options

### ISSUE THREAD

**Issue by drankinatty** [keepassxreboot/keepassxc#8062]
## Summary
keepassxc on openSUSE ver. 2.66

The column-sort by Title is case-sensitive (or locale sensitive) and sorts Titles beginning with CAPITAL letter before those with lowercase. This results in listing being hard to read and cumbersome to find if you can't recall if you capitalized the first letter of the title or not.

I have used keepassx since kde3 and keepassxc starting recently. I have hundreds of entries in roughly 20 folders. Having the entries display in a natural-sort the way many filemanagers do would be a welcomed feature

## Examples

Currently the sort is:

```none
  A
  B
  ...
  Z
  a
  b
  ...
  z
```

## Context
As explained above with hundreds of entries having Titles that begin with a capital letter sort first before all Titles that begin in lowercase make finding Titles difficult when I don't remember whether I named the Title starting with UPPERCASE or lowercase. When the titles in UPPERCASE extend beyond the visible portion of the window, I had no idea of the case-insensitive sort happening until I clicked on a folder with less than a full-screen of UPPERCASE title. (the light-bulb went on explaining why I had had difficulty finding entries I knew were in the keepassx database)

Would be a great addition and shouldn't be too much trouble to add (I hope)

**Comment by droidmonkey** [comment]
#7813, we already do sort using natural order.

**Comment by drankinatty** [comment]
Thanks. I guess openSuSE is still packaging 2.6.6 before the change. Never fails.
