### ISSUE TITLE
KeeShare certificate panel not showing

### ISSUE THREAD

**Issue by PoisonFrog** [keepassxreboot/keepassxc#8063]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
In the application settings some elements of the KeeShare window are not showing. Only the boxes to allow import, export, show warning and errors and the personal certificate boxes for signer and fingerprint are showing. All the rest that should be there is non-existent. 

I'm using KeePassXC 2.7.1 from the Arch Linux repositories.

**Comment by droidmonkey** [comment]
That was removed from the program. It was not providing any value.

**Comment by PoisonFrog** [comment]
> That was removed from the program. It was not providing any value.

Okay but what is the point of the certificate then? I have a personal certificate with a fingerprint and when I click "Generate" it replaces it. Does it go anywhere? And if it does, where can I see it? Or do the "Generate" button just replace the personal certificate?

**Comment by droidmonkey** [comment]
There is no point to any of it. The personal cert is just there for backwards compatibility with previous versions of KeePassXC.
