### ISSUE TITLE
multi monitor mac os (m1 mbp) has fairly minor display arrangement issues

### ISSUE THREAD

**Issue by jdix531** [keepassxreboot/keepassxc#8065]
## Overview
[NOTE]: # ( Give a BRIEF summary about your problem )
multi monitor mac os (m1 mbp) has fairly minor display arrangement issues

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
Have a multi-monitor (mine are both external, though I think this works with just one external)
Have a main display and keepassxc on another non-main display
"maximize" or "full-stretch" (both have issues) keepassxc
right click on an entry in a database
the "pop up" task menu shows up on the main display instead of where the cursor is like you would expect

Additionally, if you "full-stretch" by double-clicking the menu bar it seems keepassxc has 2 incorrect behaviors:
it moves to the main display
it doesn't always do a full-stretch width-wise (seems to always do full-height however)

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
these issues shouldn't exist - right-click menu should be where the mouse is and full-stretch should be on the correct screen and fully-stretched in all directions as it is on other operating systems

## Context
[NOTE]: # ( Give us any additional information you may have. )
This doesn't occur this way on other operating systems (windows x64/arm, linux x64 at least).

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.1
Revision: ??

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS - m1 mbp (has mobile device management from work, but I don't think it is in play here, fairly liberal)

**Comment by droidmonkey** [comment]
This is a qt bug, and a duplicate issue report.

**Comment by jdix531** [comment]
FYI this seems to be fixed now (for me at least!). Not sure where something was changed as it seemed to happen between keepassxc releases. I noticed after mac update.
