### ISSUE TITLE
Quick unlock not enabled on MacOS

### ISSUE THREAD

**Issue by bekelchik** [keepassxreboot/keepassxc#8067]
Worked on 2.7.0, stopped working on 2.7.1. 

Don't see any related settings under Security or elsewhere.

MacOS Monterey, version 12.3.1. TouchID is enabled.

**Comment by phoerious** [comment]
Works perfectly fine here. There is a quick unlock setting in the global security settings (first checkbox).

**Comment by droidmonkey** [comment]
Nothing was changed between those two versions for quick unlock on macos

**Comment by bekelchik** [comment]
started working after macOS patch update ¯\_(ツ)_/¯
