### ISSUE TITLE
Column: User not shown while password is plain shown

### ISSUE THREAD

**Issue by leomayer** [keepassxreboot/keepassxc#8069]
Don't know what kind of settings I need to apply but currently 

- the user name is hidden like a password
- the password is shown like a user

Since I didn't find any kind of settings for which a hide/show would apply I open this ticket.

![Bildschirmfoto vom 2022-05-19 13-55-52](https://user-images.githubusercontent.com/2641128/169288280-cacf0a80-dc31-452c-ad09-43d1e6091770.png)

**Comment by droidmonkey** [comment]
View-> Hide usernames and View -> Hide passwords
