### ISSUE TITLE
Massrename on Title of multiple selected entries (edit common Prefix / Suffix)

### ISSUE THREAD

**Issue by Tormen** [keepassxreboot/keepassxc#8070]
## Summary
Select multiple entries. Right click. Chose Mass-rename Title: 
  * feature detects if there is a common PREFIX and allows to EDIT it (if no common prefix is detected the field is empty and a common Prefix can be added)
  * And maybe same for suffix ?
 
## Examples
Instead of Folders to group items I just decided to PREFIX the Title for all entries of a folder...

## Context
See Example.

Maybe you think this is too niche ... people will never need / use this... 
OR 
You think ah, this is a neat idea.

I am fine with either reaction :D

**Comment by droidmonkey** [comment]
Duplicate request. Search for select multiple entries and edit.

**Comment by Tormen** [comment]
Duplicate to https://github.com/keepassxreboot/keepassxc/issues/1314

**Comment by Tormen** [comment]
Thanks a lot @droidmonkey for quick feedback and spotting the duplicate!

My focus is Prefix + Suffix, so I missed that. Maybe my described idea how this could be implemented could still be interesting ?

```
feature detects if there is a common PREFIX and allows to EDIT it 
( if no common prefix is detected the field is empty 
  and a common Prefix can be added to all selected entries )
```

At least I linked the issues and mentioned this on both sides. As the duplicate does not mention prefix yet.

**Comment by droidmonkey** [comment]
That is too specific of a criteria. We don't care what data is entered in for the attribute fields (aside for some minor sanity checks on the url field). We don't want to go down the road of being "aware" of potential special patterns in user data. 

If you don't want to use groups I recommend using tags. Then you can sort/filter entries that way.

**Comment by Tormen** [comment]
Hmmm I see. Yes makes sense!

Thanks again for this awesome piece of software !!!!!!!!!!!!!!!
