### ISSUE TITLE
KeeepassXC doesn't work anymore with Vorta and Pika Backup

### ISSUE THREAD

**Issue by carobinario** [keepassxreboot/keepassxc#8072]
## Overview
KeepassXc 2.7.1 can't store anymore Vorta and Pika Backup (two backup apps based on Borg 1.2 as backend)

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Set KeepasXC as Secret Storage Service
2. Open Vorta (0.8.3 or 0.8.4) or Pika Backup (0.4)
3. Try to add a new repository

## Expected Behavior
Backup

## Actual Behavior
Errors storing / reading password

## Context
[NOTE]: # ( Give us any additional information you may have. )

I haven't any issue with KeepassXC 2.6.6. After updating to 2.7.0 and 2.7.1, [Vorta](https://vorta.borgbase.com/) can't anymore store password when I initialize a new repository. I opened a issue report on [Vorta issue tracker](https://github.com/borgbase/vorta/issues/1260). After some test with developing team, they says 

_This error is either an issue of KeePassXC or secretstorage but not a bug of vorta._ 

Also, I have issues with the new version of [Pika Backup ](https://apps.gnome.org/app/org.gnome.World.PikaBackup/).

After a[ bug report](https://gitlab.gnome.org/World/pika-backup/-/issues/216), developer replied: 

_Pika 0.4 uses the now 'correct way' to do local password storage in Flatpaks. This method does not use Secret Service directly.
My guess is that the secret portal (org.freedesktop.portal.Secret) is not working on your system_

In KeepassXC I tried to uncheck "Confirm when passwords are retrieved by clients" as suggested #7653: nothing has changed.

## Operating System
Operating System: openSUSE Tumbleweed 20220518
KDE Plasma Version: 5.24.5
KDE Frameworks Version: 5.94.0
Qt Version: 5.15.2
Kernel Version: 5.17.7-1-default (64-bit)
Graphics Platform: X11
Processors: 4 × Intel® Core™ i5-6600 CPU @ 3.30GHz
Memory: 15.3 GiB of RAM
Graphics Processor: Mesa Intel® HD Graphics 530

**Comment by droidmonkey** [comment]
I sincerely doubt this is on us, we follow the secret storage api and it works with hundreds of other products. How do you have keepassxc installed?

This is especially true with pike backup, that product was updated and is now broken. That is not related to us.

**Comment by carobinario** [comment]
Hi,
KeepassXC is installed from official Opensuse Tumbleweed repo. Vorta is installed from official Opensuse Tumbleweed repo (I also tried Flatpak from Flathub an master: same issue). Pika Backup is installed from Flathub).

**Comment by droidmonkey** [comment]
Closing as this is not on us at this time.
