### ISSUE TITLE
Password generator is a

### ISSUE THREAD

**Issue by PaS3** [keepassxreboot/keepassxc#8073]
## Overview
Password generator does not exclude repeating characters integers etc. sometimes.

## Steps to Reproduce
1.  Generate password using password generator and look for duplicates.

## Expected Behavior
1.  Generate password using password generator and look for duplicates.
2.  Then replace a duplicate with a new random character integer etc.
3.  Check if new replacement is again a duplicate or continue replacement.

## Actual Behavior
Here a some generated passwords and duplicates in bold : 
1.  UQ**JJ**E2zrGmUkBlen
2.  iHGpNy**77**a4XWi75z
3.  **F**N1IoRxmj**F**zYZ9Q1

## Context
Know attacks on repeating characters have been known and these passwords are used internally on files and externally on web sites.

KeePassXC - 2.3.4
Revision: ?
Debian 10 (buster) Debian 4.19 - Does Debian 11 come with new version?

 
Operating System: Linux Debian 10 (buster) Debian 4.19 - 
Does Debian 11 come with new version?

Desktop Env:  KDE  Plasmashell 
Windowing System:  KWin X11

**Comment by droidmonkey** [comment]
It's a random password generator, if you don't like the result generate another password. Length is far more important than anything else. 

You also need to update your keepassxc, we are on version 2.7.1. Use the appimage, snap, flatpak, or ppa.

**Comment by phoerious** [comment]
Replacing duplicate characters with non-duplicates makes the password less random. Don't do it, unless perhaps you generate very short PIN-like passwords (and even then only if there more than three repetitions in a row).
