### ISSUE TITLE
OTP  password for database file

### ISSUE THREAD

**Issue by PaS3** [keepassxreboot/keepassxc#8074]
## Summary
OTP password functionality for a database file

## Examples
Built in OTP  password private key and public key QR generator  to scan out with an OTP app such as DUO, google Authenticator on a smartphone.
Built in lock for a database file with OTP, known-password and key file.

 (Microsoft/RSA authenticator may be different length and not compatible with most OTP) 

OTP is a bit broken with lack of alpha numeric pair. (not compatible with anyone, anything. Do not use!)
 
## Context
3 important factors are something you know, something you have (OTP authenticator app on iphone), and something you are in a separate disconnected fashion. 
A user can have all 3 features by unlocking iphone with something they are - bio-metrics and using something they have from an OTP authenticator, and finally the password they know.

**Comment by droidmonkey** [comment]
You cannot use timed one time password for an offline file. You can use hashed one time password but that requires a separate file from the database. We are not going to implement that.
