### ISSUE TITLE
Having a problem with Keypass XC not copying correct password instead copies url.

### ISSUE THREAD

**Issue by Hecval01** [keepassxreboot/keepassxc#8075]
This all happened after updating to the latest update, can I get some help with this issue I don't want to loose any of my entries. Please help.

**Comment by Hecval01** [comment]
Sorry for the miss spell should be KeepassXC

**Comment by droidmonkey** [comment]
Duplicate report and will be fixed in 2.7.2. Easy fix is to make sure the URL is not selected after clicking it, use Auto-Type, or use the browser extension.

**Comment by Hecval01** [comment]
Thank you very much. I am looking forward to the fix.
