### ISSUE TITLE
Autotype removes periods from user name

### ISSUE THREAD

**Issue by josephj11** [keepassxreboot/keepassxc#8076]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
Autotype gets the right entry, but my user name gets edited

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Create an entry with a user name containing periods
2. Set it up using default pattern of user name tab password
3. Trigger autotype by selecting one of several matches found

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
User name autotyped should be josephj@main.nc.us

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
User name autotyped as josephj@mainncus

## Context
[NOTE]: # ( Give us any additional information you may have. )
www.gemini.com pattern is Gemini - Sign In*
Browser Vivaldi on kubuntu 18.04

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.1
Revision: 5916a8f

Qt 5.9.5
Debugging mode is disabled.

Operating system: Ubuntu 18.04.6 LTS
CPU architecture: x86_64
Kernel: linux 4.15.0-177-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.12.1

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: KDE
Windowing System: X11

**Comment by droidmonkey** [comment]
What keyboard layout are you using?

**Comment by josephj11** [comment]
Not sure, but Settings->Keyboard->Hardware says Generic | Generic 101-key PC and in the Layouts section, Configure Layouts is not enabled. I do have a couple of advanced settings like a disabled CapsLock key which defaults to Hyper and Shift+CapsLock works. My numeric keypad has Unicode additions (arrows and math operators; math operators on default level). I don't do much with keyboard layouts, so I'm not very familiar with them.

**Comment by droidmonkey** [comment]
So are you using a US english layout than?

Does this happen if you try to Auto-Type into a simple notepad / text editor?

**Comment by josephj11** [comment]
Yes. My locale is the default EN-US and I don't modify the keyboard.

Works fine in kate and in konsole, but not on Gemini.com site - all three tested using the Keepassxc perform autotype context menu option as the others do not match the window filter.

Since you just have to see what it types and the actual login doesn't have to succeed or even get started by pressing Enter, you should be able to recreate this on the Gemini site. https://exchange.gemini.com/signin

Used Brave browser and the same happens using Vivaldi (both chromium-based). Worked correctly in Firefox.

**Comment by droidmonkey** [comment]
This definitely isn't a keepassxc bug then. You can try to slow down typing by adding a {DELAY=500} to the beginning of the sequence or set it slower globally in the Auto-Type application settings.

**Comment by droidmonkey** [comment]
I cannot replicate on Windows using Edge
