### ISSUE TITLE
Autotype behavior differs: keyboard shortcut vs. 'request global auto-type' feature in right click context menu

### ISSUE THREAD

**Issue by tx3eh8IUD1** [keepassxreboot/keepassxc#8077]
## Overview
[NOTE]: 
The KeePassXC login button does not appear in the email field for komoot.com **(Note: this may actually be a separate bug - but I thought the proper autotype behavior would help me fix this for all webpages, not just the one I mention here)**
For such entries, I try to login via autotype instead. In KeePass, I was used to the software finding and typing entries directly, and only giving me a menu to find entries if more than one "hit" based on URL is found. 
Keepassxc unfortunately makes this process much more complex, by always providing a selection.
I am surprised that the global autotype menu with login entries looks different when triggering it via shortcut then when I do it from the context menu of the login field

Shortcut: I get all entries from database, no pre-selection based on URL to site title seems to happen -> so I have to search for komoot in the search field
Right click context menu: I get only the two appropriate komoot logings - quite helpful - but unfortunately three clicks away so much more complex than using a keyboard shortcut

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. When using Auto-Type shortcut (as specified in Settings -> General->Auto-Type) I get all logins, no pre-selection based on currently active webpage in firefox (unexpected behavior)
2. When using right click in login field -> KeePassXC-Browser -> Request Global Auto-Type I get only the two matching logins ( expected behavior)
 ![image](https://user-images.githubusercontent.com/6958661/169694366-37635b2a-877a-4f7e-8441-ac4a5559864c.png)

## Expected Behavior
I expect the autotype window to show only those entries where the URL or entry title matches the currently active page in firefox

## Actual Behavior
When using the keyboard shortcut, I see all entries from the database, because the URL is not pre-filled in the search box

## Context
KeePassXC - 2.7.1
Revision: 5916a8f

Operating System: Windows
Browser: Firefox

**Comment by droidmonkey** [comment]
Need more than that

**Comment by tx3eh8IUD1** [comment]
Sorry- submitted earlier than I wanted to - edited the entry

**Comment by droidmonkey** [comment]
You are mixing the browser plugin with pure autotype. Pure autotype (the global shortcut) uses the browser window title to try and match an entry. The browser plugin added the ability to launch pure autotype and prefill a search with the current url. You can setup a keyboard shortcut in the browser extension settings for the autotype from the browser. You can also setup window title associations to use 'pure autotype', please read the user guide for instructions.

**Comment by tx3eh8IUD1** [comment]
OK auto-submit works well - thanks for the tip to check browser plugin settings more thoroughly.
