### ISSUE TITLE
Lock database after global user inactivity

### ISSUE THREAD

**Issue by guanmengxu** [keepassxreboot/keepassxc#8079]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
Lock database after global user inactivity

![image](https://user-images.githubusercontent.com/49642766/169747082-e62b341a-33e2-4ae8-8409-36433bcb63e1.png)

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
I'm still using my computer,but the keepassXC locked，I have set the after idle time  to lock。I want lock the database when i don't use my computer . when i'm using my computer, the database will not lock all the time.

**Comment by droidmonkey** [comment]
Duplicate request
