### ISSUE TITLE
Search results should be listed by title match, not alphabetically

### ISSUE THREAD

**Issue by TempSpas** [keepassxreboot/keepassxc#808]
Currently, upon entering a search term, results are displayed by default in alphabetical order by Group. This can be changed to be alphabetical by Title, Username, or URL, but as far as I can tell it cannot be change to anything else. This should not be how search results are displayed. They should be displayed by Title match relevance.

## Expected Behavior

For example, I have my email saved in the database with the title corresponding to the email provider. This email is also used to log in to certain sites, so naturally it is saved as the username elsewhere in the database. When I hit Command-F and search for the email provider's title, I expect that to be the first result.

## Current Behavior

However, it is not the first result. Above it are the all of the other entries containing the email that are in Groups higher alphabetically.

This makes very little sense for the search function, and renders it somewhat useless, as I have to sift through all of the preceding results whose titles do not contain my search term in order to get to the one that does.

**Comment by TempSpas** [comment]
This issue is related to #184 but not quite the same thing, as giving Titles precedence over Groups means little if the search is indexing every field and then displaying the results alphabetically, regardless of which category is chosen.

**Comment by phoerious** [comment]
I don't think, this will be implemented. The search function is a simple entry filter, not a ranking search engine. I suggest you give your email provider a more specific title, so you can filter for that.
