### ISSUE TITLE
Cannot fully replace Steam Mobile Authenticator - Steam Mobile Authenticator is NOT JUST TOTP

### ISSUE THREAD

**Issue by LoganDark** [keepassxreboot/keepassxc#8080]
## Overview
Steam Mobile Authenticator is not only TOTP. Steam will require other stupid shit. KeePassXC does not support this and therefore still cannot be used for Steam 2FA.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Enable Steam Guard Mobile Authenticator, transfer key to KeePassXC, yadda yadda.
2. Try to change your email address.

## Expected Behavior
TOTP

## Actual Behavior
> Please launch the Steam Mobile app on your mobile device, and then select the Confirmations menu option. Confirm the account recovery action in the app, and then press the "Continue" button below.
> For security, verify that the code in the box below matches the code we display on the confirmations page.
> \<code>
> Waiting for you to confirm using the Steam app...

What.

What the hell is this shit. This is absolutely fucking stupid.

KeePassXC unfortunately needs to support this fucking bullshit before it can serve as 2FA for my Steam account.

Forced to disable 2FA just to change my email.

## Context
KeePassXC - Version 2.7.1
Revision: 5916a8f

Qt 5.15.3
Debugging mode is disabled.

Operating system: Windows 10 Version 2004
CPU architecture: x86_64
Kernel: winnt 10.0.19041

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 2.18.1

P.S. feel free to edit the cursing out of my issue if it's inappropriate, I'm too pissed to do it myself.

**Comment by phoerious** [comment]
Thanks for letting us know, but there is nothing we can do here.

**Comment by ArtyIF** [comment]
Steam recently updated the way Steam Guard works. It now sends notifications to your phone app instead of asking a TOTP code by default.

Also, my phone got smashed today, I unlinked Guard and tried linking it again, this time with KeePassXC, but now it just tells you to do it in the app. So I don't think it's possible to use KPXC with Steam anymore.

**Comment by droidmonkey** [comment]
This would be a feature I'd be happy to remove. It complicates our implementation of TOTP and I doubt many folks even use it. @phoerious 2.8.0 removal?

**Comment by phoerious** [comment]
If Steam doesn't use TOTP anymore, sure.

**Comment by LoganDark** [comment]
> If Steam doesn't use TOTP anymore, sure.

it does:

![image](https://github.com/keepassxreboot/keepassxc/assets/4723091/baeca959-6935-461b-b52d-2e9ce1a911e8)

and KeePassXC-generated codes still work.

Keep the feature
