### ISSUE TITLE
No way to manage favicons

### ISSUE THREAD

**Issue by NineSeven8** [keepassxreboot/keepassxc#8083]
## Overview
The feature to manage icons on any entry is not present anymore, they were in previous versions.
There is currently no way to delete a favicon from the database

## Steps to Reproduce
Fresh install keepassxc and add a favicon, no way to delete it.

## Expected Behavior
As previous versions, or windows version, you have the ability to delete a favicon

## Actual Behavior
No button to delete

## Context

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC 2.7.1.1 (ARCH)
Also not available on the arch linux flatpak

[NOTE]: # ( Pick choices based on your environment )
Operating System: Arch Linux
Desktop Env: XFCE

**Comment by droidmonkey** [comment]
Database menu-> database settings-> maintenance 

Documented in the user guide if you need more assistance

**Comment by NineSeven8** [comment]
Thank you for clarifying that Droidmonkey, I'm sorry I didn't read the guide, I guess I have an older version for windows then.
