### ISSUE TITLE
Browser auto fill not working if keepass tab not focused

### ISSUE THREAD

**Issue by SynapseScribe** [keepassxreboot/keepassxc#8087]
## Steps to Reproduce
1. have more keepass dbs open, already unlocked
2. Password field not detected in any website unless the tab with the db that holds the password is focused

Running on windows 11
keepassXC v2.7.1 Revision: 5916a8f
Brave Browser 1.39.111 (Chromium: 102.0.5005.61)
keepassXC-Browser extension 1.7.12

**Comment by droidmonkey** [comment]
You must be referring to the browser extension in this case. You need to enable "Search all opened databases" in the browser extension settings. 

![image](https://user-images.githubusercontent.com/2809491/170718479-7e2719cf-6500-4e06-872d-1c452d7e3222.png)

**Comment by fusionneur** [comment]
Seems to work for 2 out of 3 websites i tested. Maybe this options should be checked by default..
