### ISSUE TITLE
unlock all dbs at once with pin

### ISSUE THREAD

**Issue by SynapseScribe** [keepassxreboot/keepassxc#8088]
please add possibility to unlock multiple dbs at once with the PIN (after their passwords were already entered)
It takes too much time to unlock all of them each time, writing same pin so many times

My suggestion would be to add a button (similar to "Lock all databases") in the toolbar to unlock all databases (those that have already the password entered) with the pin, all at once.

**Comment by droidmonkey** [comment]
If you want one database to unlock all databases use Auto Open. https://keepassxc.org/docs/KeePassXC_UserGuide.html#_automatic_database_opening

**Comment by SynapseScribe** [comment]
why so complicated though..

**Comment by droidmonkey** [comment]
Each database is unique to each other, if you want to break that then use Auto Open.

**Comment by SynapseScribe** [comment]
This doesn't help though.. it still asks me to enter the pin multiple times. Naturally, the PIN should be entered only once

**Comment by droidmonkey** [comment]
I don't know what you are referring to regarding the pin, windows hello?

**Comment by SynapseScribe** [comment]
yes, windows pin

**Comment by droidmonkey** [comment]
If you use auto open you only need to enter your pin on your main db you unlock manually. You can also just disable that feature in the application security settings.

**Comment by michaelk83** [comment]
#8027

**Comment by SynapseScribe** [comment]
> If you use auto open you only need to enter your pin on your main db you unlock manually. You can also just disable that feature in the application security settings.

I set up AutoOpen yesterday, but after entering PIN for the main db, another windows hello security window appears requiring me to enter PIN again to unlock the second db as well.

I use windows hello pin because the PIN is shorter than the db password and disabling it won't help in this case.

**Comment by droidmonkey** [comment]
Interesting, might have a bug then

**Comment by droidmonkey** [comment]
Nope could not reproduce, the auto open databases do not prompt for windows hello.

**Comment by SynapseScribe** [comment]
i have quick unlock (windows hello) activated in the settings. Maybe it was a missunderstanding.. What i mean, is that it asks multiple times for the windows PIN, when naturally should be asked only once

**Comment by SynapseScribe** [comment]
That's strange... today all my dbs opened by entering pin only one time..
