### ISSUE TITLE
unable to open database using snap release

### ISSUE THREAD

**Issue by rhetr** [keepassxreboot/keepassxc#809]
I installed keepassxc using `sudo snap install keepassxc` but am unable to open my existing keepass2 database located in my Dropbox folder.

## Expected Behavior
I should be able to open and modify my existing key database

## Current Behavior
I am unable to do so and instead see "unable to open database. permission denied"

## Steps to Reproduce (for bugs)
1. `snap run keepassxc`
2. 'open new database'
3. manually input database located in Dropbox folder and 'open'

Operating system: Ubuntu 16.04.2
CPU architecture: x64
Kernel: 4.4.0-83-generic

**Comment by droidmonkey** [comment]
Mount the dropbox folder in your home directory and it should work.

**Comment by rhetr** [comment]
that isn't ideal for me. is it possible to expose access to the specific folder somehow? in flatpak you can `--filesystem=` to enable access.

**Comment by droidmonkey** [comment]
No. You have to use the standard build instead of snap.
