### ISSUE TITLE
KeePassXC disappears from alt-tab window switcher

### ISSUE THREAD

**Issue by anton-tsyganenko** [keepassxreboot/keepassxc#8090]
I'm using KeePassXC 2.7.1 on Fedora 36 with Gnome 42.1.

After I start KeePassXC, optionaly do some actions in it (such as unlocking DB and copying password) and then switch to another window, I can't switch back to KeePassXC using window switcher (alt-tab or super-tab), because it is not there. The window itself is present and accessible throw activities overview. But after a while (not sure when exactly) it appears in the switcher.

https://user-images.githubusercontent.com/4764069/170834806-5a3546f4-4993-4c3e-9639-112b27e4b814.mp4

**Comment by droidmonkey** [comment]
This is a gnome bug: https://github.com/keepassxreboot/keepassxc/issues/6423
