### ISSUE TITLE
Sync Databases with/without TOTP/Password

### ISSUE THREAD

**Issue by Serpens66** [keepassxreboot/keepassxc#8092]
## Summary
I'm looking for an easy way to create and maintain 2 different databases for the same websites, one with passwords and one with TOTP, without updating each of them manually all the time. I already tested with KeeShare.

## Current Problem 
Additional information from the entries like url, username and other attributes like email, mobile number and so on do matter for both, the password and the TOTP database. If I change this information, there seems to be currently no way to sync this to the other database, without also syncing TOTP/passwords.

## Best final solution I can think of:
Best case would be if both databases contain and sync all information except password (only in password-database) and TOTP (only in TOTP database). 
Maybe simply add customization for what to sync/what to not sync.

If there is already a solution for this, let me know, I found none via search or in documentaion.

**Comment by droidmonkey** [comment]
This isn't a feature we would ever support. If you desire a dedicated TOTP database, separate from your passwords, then that is a completely distinct database with distinct entries. Your TOTP database should have the minimum amount of information necessary to provide the TOTP codes for the sites that need them.

**Comment by Serpens66** [comment]
strange reasoning...

## Other idea:
The main reason for the recommendation to store TOTP in a separated database than the passwords is, that one don't want the TOTP unlocked all the time, only when really needed. So you could simply add a second unlock step for TOTP that can be locked easily afterwards, without locking the passwords.
If you think that this is also too bad security, than you should have never implemented TOTP in the first place.

I'm just looking for Quality of life improvements that even add extra security over the current default behavior.

edit:
still thank you for KeePassXC and your work and your response :)

**Comment by droidmonkey** [comment]
I don't understand what you are trying to do with syncing between two databases? Sync means the data appears exactly on both databases. Syncing while withholding specific data (in this case TOTP settings) doesn't make sense. The TOTP standalone database entries only need: TOTP settings, Title, URL (for browser), window association (for Auto-Type).

A second tier of database unlock also makes little sense. Once the credentials are provided they decrypt everything in the database. Adding a special case, secondary encryption, for TOTP secrets breaks compatibility with other programs and doesn't add additional protection over a separate dedicated database.
