### ISSUE TITLE
Support for multiple user creds per entry

### ISSUE THREAD

**Issue by nlguerra2003** [keepassxreboot/keepassxc#8093]
## Summary
I'd like to be able to get some support for several credentials/users per entry, making it a lot easier to integrate with system/app usernames and passwords.

## Examples
Perhaps using a "add user/credentials" button when editing an entry?
Also, it'd be quite cool if it's integrated with the "Copy password" option from the contextual menu, making me able to choose what password to copy.

This way, I don't have to make a whole group with --let's say-- "UBUNTU" and then putting in it an entry for each user, but instead making a lot more generic group "VMs", making an "UBUNTU" entry, and then configuring it all to have all the users in it.

## Context
As a hobbyist sysadmin I got some virtual machines and authenticated programs, all of them with their own root and user credentials, and using the password for root and the "Additional attributes" for other users is messing me up.

**Comment by droidmonkey** [comment]
That would break a whole lot of functionality and doesn't align with keepass specs. We align with one entry, one credential. You are welcome to add additional credentials using the advanced attributes but we won't official support that.

**Comment by fernvenue** [comment]
@nlguerra2003 Hi, I had a similar problem with you, I also needed to add multiple usernames to one entry.

And just like @droidmonkey said:

> You are welcome to add additional credentials using the advanced attributes but we won't official support that.

I just solved this with additional credentials, and achieves richer customization as described in the [KeePassXC Wiki](https://github.com/keepassxreboot/keepassxc/wiki/Autotype-Custom-Sequence#custom-entry-attributes).

Hope this can help you a little bit :)
