### ISSUE TITLE
Unlocking via dbus openDatabase fails

### ISSUE THREAD

**Issue by tukanos** [keepassxreboot/keepassxc#8095]
## Overview
KeePassXC does not open via dbus (qdbus)

## Steps to Reproduce
1. Change to the directory where the test.kdbx resides
2. run `qdbus org.keepassxc.KeePassXC.MainWindow /keepassxc org.keepassxc.MainWindow.openDatabase test.kdbx passwd`

## Expected Behavior
Be able to open keepass.kdbx database

## Actual Behavior
Nothing happens after I press return, I return back to the shell.

## Context
I have tried to debug it via dbus-send:
`dbus-send --session --print-reply --dest=org.keepassxc.KeePassXC.MainWindow --type=method_call /keepassxc org.keepassxc.MainWindow.openDatabase string:test.kdbx string:passwd`
Which gives:
`method return time=1653916646.121816 sender=:1.170 -> destination=:1.227 serial=83 reply_serial=2`   So the method replies but I don't see anything.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - KeePassXC 2.6.6
Revision: 9c108b9

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: Gnome (GNOME Shell 42.1)
Windowing System: X11

**Comment by droidmonkey** [comment]
You need to update to 2.7.2, also the dbus command is actually org.keepassxc.KeePassXC.MainWindow.openDatabase

**Comment by tukanos** [comment]
@droidmonkey Thank you for your reply.  I have figured it out by digging through the source code and commits.  It was my error, I was unlocking password database with wrong password.

By version *2.7.2* you mean to compile it from source?  The latest on [projects download pages](https://keepassxc.org/download/) is *2.7.1*.  I have been successful with 2.6.6.

For future reference:

a)  I have checked the methods that are returned from the command: 
`qdbus org.keepassxc.KeePassXC.MainWindow /keepassxc`

```
method void org.keepassxc.MainWindow.appExit()
method void org.keepassxc.MainWindow.closeAllDatabases()
method void org.keepassxc.MainWindow.lockAllDatabases()
method void org.keepassxc.MainWindow.openDatabase(QString fileName)
method void org.keepassxc.MainWindow.openDatabase(QString fileName, QString pw)
method void org.keepassxc.MainWindow.openDatabase(QString fileName, QString pw, QString keyFile)
signal void org.freedesktop.DBus.Properties.PropertiesChanged(QString interface_name, QVariantMap changed_properties, QStringList invalidated_properties)
method QDBusVariant org.freedesktop.DBus.Properties.Get(QString interface_name, QString property_name)
method QVariantMap org.freedesktop.DBus.Properties.GetAll(QString interface_name)
method void org.freedesktop.DBus.Properties.Set(QString interface_name, QString property_name, QDBusVariant value)
method QString org.freedesktop.DBus.Introspectable.Introspect()
method QString org.freedesktop.DBus.Peer.GetMachineId()
method void org.freedesktop.DBus.Peer.Ping()
```
From the `method void org.keepassxc.MainWindow.openDatabase(QString fileName, QString pw)` I have taken the command.  That command was correct as I was reply from `dbus-send`.  The [wiki](https://github.com/keepassxreboot/keepassxc/wiki/Using-DBus-with-KeePassXC) is incorrect.  I see you were talking abou it [here](https://github.com/keepassxreboot/keepassxc/issues/5355).

b)  The DBus commits for KeePassXC. The main patch for the [dbus support](https://github.com/keepassxreboot/keepassxc/pull/283/commits/e560650bf3d5d6d7649b3e107a4c8488e36c0be0) with the [PR](https://github.com/keepassxreboot/keepassxc/issues/687)

c) The correct command, `qdbus` or `gdbus` both work, with which I have unlocked my KeePassXC:

`qdbus org.keepassxc.KeePassXC.MainWindow /keepassxc org.keepassxc.MainWindow.openDatabase <file_with_path.kdbx> <password>`

`gdbus call --session --dest org.keepassxc.KeePassXC.MainWindow --object-path /keepassxc --method org.keepassxc.MainWindow.openDatabase <file_with_path.kdbx> <password>`

**Comment by droidmonkey** [comment]
It was changed in 2.7.0

**Comment by tukanos** [comment]
> It was changed in 2.7.0

I see.  I'll use adjust my automation scripts to work with both versions.  Thank you for the information.

In the end I hope to use [Open database for ssh-agent from cli](https://github.com/keepassxreboot/keepassxc/issues/2340) in the future or maybe I'll stick with DBus when [yubikey unlocking is added](https://github.com/keepassxreboot/keepassxc/issues/8017).
