### ISSUE TITLE
url can use Regular Expression

### ISSUE THREAD

**Issue by guanmengxu** [keepassxreboot/keepassxc#8097]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )
Some websites have many Second-level domain，such as mail.163.com,www.163.com,yeah.net。
when i use url 163.com in the item，It can't match mail.163.com。keepass can return the related one.
I need one item can mach more websites, thank you. 
## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )

**Comment by droidmonkey** [comment]
As long as all sites are using https, 163.com will match with mail.163.com and every other sub domain. There is already a request for limited wildcard usage in urls, but that is not implemented.

**Comment by soheyldev** [comment]
Dear Jonathan,
I used site that changes URL with pattern over the time. For example over the month URL changes like this: _sample1.sample1_, _sample2.sample1_, _sample3.sample1_ , _sample1.sample2_. How can I use regex inside the URL and define pattern?

**Comment by droidmonkey** [comment]
@soheyldev see here: https://keepassxc.org/docs/KeePassXC_UserGuide#_advanced_usage

**Comment by soheyldev** [comment]
Thanks.
I think It doesn't support pattern like below example.

URL:
https://example1.com
https://example2.com
https://example3.com
https://example1.uk
https://example2.uk
https://example3.uk

pattern:
https://example*.*

I have one username and password for all of them.
I want to use regex inside _label_ and _TLD_ of URL.

**Comment by droidmonkey** [comment]
Use the additional urls feature
