### ISSUE TITLE
keepassxc-2.7.1 segfaults when being used as secret service

### ISSUE THREAD

**Issue by g-regex** [keepassxreboot/keepassxc#8098]
## Overview
This problem has occurred specifically when using with nheko-0.9.3, but it seems to be on the keepassxc side. When starting nheko (matrix chat client) and thereby trying to connect to keepassxc-2.7.1 as a secret service, keepassxc segfaults (no further error messages). If the database is still locked, one is first asked to unlock them and then keepassxc segfaults. With keepassxc-2.6.6 (same nheko version) the secret service integration was working, when the database was unlocked. When the database was locked, keepassxc seems to return invalid keys.

## Steps to Reproduce
1. Start keepassxc-2.7.1
2. Optional: Unlock database
3. Start nheko-0.9.3
4. Observe segfault

## Expected Behavior
keepassxc does not segfault and sends the correct keys to the requesting application.

## Actual Behavior
keepassxc segfaults.

## Context
The described behaviour was observed on a Gentoo system with 5.15.41 kernel with the following installed dependencies (manually reformatted output of `equery g keepassxc`:

```
dependency graph for app-admin/keepassxc-2.7.1-r1
   --  app-crypt/argon2-20190702-r1  (app-crypt/argon2) amd64
   --  dev-libs/botan-2.19.1  (dev-libs/botan) amd64
   --  dev-qt/qtconcurrent-5.15.3  (dev-qt/qtconcurrent) amd64
   --  dev-qt/qtcore-5.15.3  (dev-qt/qtcore) amd64
   --  dev-qt/qtdbus-5.15.3  (dev-qt/qtdbus) amd64
   --  dev-qt/qtgui-5.15.3  (dev-qt/qtgui) amd64
   --  dev-qt/qtnetwork-5.15.3  (dev-qt/qtnetwork) amd64
   --  dev-qt/qtsvg-5.15.3  (dev-qt/qtsvg) amd64
   --  dev-qt/qtwidgets-5.15.3  (dev-qt/qtwidgets) amd64
   --  dev-qt/qtx11extras-5.15.3  (dev-qt/qtx11extras) amd64
   --  media-gfx/qrencode-4.1.1  (media-gfx/qrencode) amd64
   --  sys-libs/readline-8.1_p2  (sys-libs/readline) amd64
   --  sys-libs/zlib-1.2.11-r4  (sys-libs/zlib) amd64
   --  x11-libs/libX11-1.7.5  (x11-libs/libX11) amd64
   --  x11-libs/libXtst-1.2.3-r2  (x11-libs/libXtst) amd64
   --  dev-libs/libusb-1.0.24-r2  (dev-libs/libusb) amd64
   --  sys-apps/pcsc-lite-1.9.7  (sys-apps/pcsc-lite) amd64
   --  dev-qt/linguist-tools-5.15.3  (dev-qt/linguist-tools) amd64
   --  dev-qt/qttest-5.15.3  (dev-qt/qttest) amd64
   --  dev-ruby/asciidoctor-2.0.15  (dev-ruby/asciidoctor) amd64
   --  dev-util/ninja-1.10.2-r1  (dev-util/ninja) amd64
   --  dev-util/cmake-3.22.4  (>=dev-util/cmake-3.20.5) amd64
```

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.1
Revision: Gentoo ebuild 2.7.1-r1

[NOTE]: # ( Pick choices based on your environment )
Operating System: Gentoo Linux 5.15.41
Windowing System: X11

**Comment by droidmonkey** [comment]
Duplicate. Empty your recycle bin.
