### ISSUE TITLE
Deleting items from Recycle Bin via search causes segfault

### ISSUE THREAD

**Issue by ProactiveServices** [keepassxreboot/keepassxc#8099]
## Overview
With the Recycle Bin search enabled, if an entry is displayed from a search and then deleted, a segfault occurs. Deleting the entry by navigating to the Recycle Bin works.

## Steps to Reproduce
1. Create a database with a Recycle Bin and set it to be searchable
2. Create and delete an entry
3. Search for the entry and delete it from the search results
4. Accept the confirmation prompt

## Expected Behavior
Item is deleted.

## Actual Behavior
Segmentation fault

KeePassXC - Version 2.7.1
Revision: 5916a8f

## Context
Qt 5.12.8
Debugging mode is disabled.

Operating system: Ubuntu 20.04.4 LTS
CPU architecture: x86_64
Kernel: linux 5.4.0-113-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.12.1

Operating System: Linux
Desktop Env: KDE
Windowing System: X11

Thank you for such useful and (almost always!) reliable software.

**Comment by droidmonkey** [comment]
Figured it out and posted a fix PR. Nice find!
