### ISSUE TITLE
An entry cannot match HTTP and HTTPS at the same time

### ISSUE THREAD

**Issue by guanmengxu** [keepassxreboot/keepassxc#8100]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
such as url"163.com" in the item can‘t auto fill website https://www.163.com
url "https://163.com" can't match http://163.com
I think Host can be matched without protocol.
I use Keepass url“163.com” can be auto fill https://www.163.com and http://mail.163.com
## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. 
2. 
3. 

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.1
KeePassXC-Browser - 1.7.12
Operating system: Win64
Browser: Chrome/Chromium 94.0.4606.81

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 10
Desktop Env: Gnome/KDE/XFCE/Mate/Cinnamon
Windowing System: X11/Wayland

**Comment by droidmonkey** [comment]
This is a by-design security feature. You can add both if you want to, use the browser page when editing an entry to add additional urls.
