### ISSUE TITLE
Auto-Type: "Home"- and "End" keys not working anymore

### ISSUE THREAD

**Issue by pho3nixx** [keepassxreboot/keepassxc#8102]
## Overview
In former versions, when pressing the global Auto-Type shortcut and multiple entires match, you could quickly navigate in the appearing selection popup window with the "Home" and "End" keys. This is no longer possible in at least 2.7.1.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. define global Auto-Type shortcut
2. have at least two entries matching the current window
3. press Auto-Type shortcut
4. a popup window appears to select the entry to be used

## Expected Behavior
Navigation in the popup window should also allow "Home" and "End" keys

## Actual Behavior
Navigation is only possible with "Page up"/"Page down", but not "Home" or "End"

KeePassXC - Version 2.7.1
Revision: 5916a8f

Qt 5.12.8
Debugging mode is disabled.

Operating system: Ubuntu 20.04.4 LTS
CPU architecture: x86_64
Kernel: linux 5.13.0-44-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.12.1

Operating System: Ubuntu 20.04.4 LTS
Desktop Env: Gnome
Windowing System: X11

**Comment by droidmonkey** [comment]
Home and End are keys used by the search text edit. Make sure you have the list of choices focused and try again. We won't support home and end for the selection list when the search field has focus.

**Comment by pho3nixx** [comment]
Ok, with this explanation of the search input field, the behavior makes total sense. I was just used the popup without search field from older versions.
As I prefer to navigate around by keyboard, focusing the choices list would mean touching the mouse and click it or pressing Shift+Tab twice. That breaks my for-years-spinally-trained behavior pattern, but I guess I'll try to work around that by using the search input field now ;-)
Thanks for the quick reply and keep up the excellent work! Closing the issue now.
