### ISSUE TITLE
"Enter Password" field allows undo and reveal password after clearing it

### ISSUE THREAD

**Issue by gheja** [keepassxreboot/keepassxc#8104]
## Overview

When looking at a closed database the "Enter Password" field supports undo (Ctrl-Z on Windows) which works even after deleting the contents of the field manually, the "reveal password" button works too.

So a partially written or just unsubmitted password can be revealed.

This works even if changing windows between entry and undo.

## Steps to Reproduce
1. Get a locked database
2. Enter a password or random characters
3. Delete all the characters
4. Switch windows
5. Come back to the KeepassXC window
6. Use ctrl-Z then "reveal password" button

## Expected Behavior
I think the field should lose undo if the entire password gets deleted or the window loses focus.

## Actual Behavior
See Overview.

## Context
n/a

KeePassXC - Version 2.6.6
Revision: 9c108b9

Operating System: Windows 10
Desktop Env: Windows
Windowing System: Windows

**Comment by droidmonkey** [comment]
Not sure we can do much about that, I belive that is a standard windows (or qt) feature.

**Comment by maclovin** [comment]
I think theres a way replacing ctrl-z behavior on form, I mean, create a shortcut command that will avoid the default OS behavior.

**Comment by sandr01d** [comment]
I think this might be related:

https://bugreports.qt.io/browse/QTBUG-103934

 There is also a workaround mentioned.

**Comment by pcolby** [comment]
I'd say the "bug" here, is that while Qt prevents undo when `QLineEdit::echoMode()` is one of the password-hide options, it doesn't clear the undo history when switching back to `QLineEdit::Normal` (ie "reveal" mode in KeePassXC).

Looking at the relevant Qt code, it should be easy for the internal `QWidgetLineControl::setEchoMode()` to also invoke `QWidgetLineControl::clearUndo()` when switching back to `QLineEdit::Normal`. Of course, that would be an internal Qt change, not something KeePassXC can do directly.

I've made that suggestion at https://bugreports.qt.io/browse/QTBUG-105382

**Comment by droidmonkey** [comment]
Agreed, this isn't something we can fix.
