### ISSUE TITLE
Add URL to Auto type

### ISSUE THREAD

**Issue by kamax82** [keepassxreboot/keepassxc#8107]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
Can you add URL on the auto type window? 
![2 copy](https://user-images.githubusercontent.com/45204932/171905619-3f7a5a48-a174-4908-91b8-9b7d1c997708.jpg)

If this already done how to activate it?

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )

**Comment by droidmonkey** [comment]
#1416
