### ISSUE TITLE
[Feature] Dual Password

### ISSUE THREAD

**Issue by Redsandro** [keepassxreboot/keepassxc#8108]
## Summary

I'd like to _mark specific entries_ to be available with a second password as well.

Everyone has different levels of trust for different websites/services. For example, you may want to protect your bank credentials with more vigor than the login credentials to your rss news aggregator.

Similarly, you may trust some devices more than others. Android devices have contact with a broad variety of apps and sites and have a wide attack surface. You may want to login to your rss news aggregator on every device, but only do banking on that trusted laptop you carefully keep away from your kids.

I'd like to _mark specific entries_ to be available with a second password as well, so that I can open these entries without having to enter the primary password to open the whole database.

Technically this second password should be available when entering the primary password, so when you toggle entries to be available, they will automatically be encrypted with the second password as well, so they can be available without the primary password.

## Context

This feature matters to me because I use a separate database to use with Keepass2Android so I don't have to enter the password for the main database. But there are passwords I use on Android as well as my desktop. So for a part I have to maintain two databases. It would be convenient if both levels of trust could be within one database.

**Comment by droidmonkey** [comment]
Unfortunately this is not possible with the kdbx (keepass) specification. It certainly won't work between apps (desktop vs mobile). However, you can achieve the desired effect using KeeShare. Setup your mobile shared database as a separate database, then setup a KeeShare import from that db to your main one. Then you only need to unlock your main one and it will import the latest version of your mobile one.
