### ISSUE TITLE
copying password instead of username

### ISSUE THREAD

**Issue by samuelb-uca** [keepassxreboot/keepassxc#8110]
## Overview
When copying username in General panel, password (which is hidden) is copied instead

## Steps to Reproduce
1. connect to database
2. click on any row
3. select Username on the Panel below
4. Ctrl-C
5. Ctrl-V

## Expected Behavior
Should put the username in clipboard

## Actual Behavior
Password in clipboard

## Context 
Version 2.3.4
Révision : 6fe821c
- Qt 5.11.3, libgcrypt 1.8.4
- extensions: Auto-Type, Browser Integration, Legacy Browser Integration (KeePassHTTP), SSH Agent, YubiKey

Debian GNU/Linux 10 (buster), x86_64, linux 4.19.0-20-amd64 with KDE

**Comment by droidmonkey** [comment]
Your keepassxc is very old and this was fixed a long time ago. Use CTRL+B to copy username if you don't want to update.
