### ISSUE TITLE
Temp keyfiles

### ISSUE THREAD

**Issue by peter233** [keepassxreboot/keepassxc#8113]
## Summary
Ability to create the temp or expireble keyfiles for a database.

## Examples
A attacker getting a copy of the database and keyfile. Keyfile expiring in 4h and needs to be refreshed. (Temp keyfile should not be enough to change the master password)
Owner blocks in the time the access for the device/or generally for the new keyfile.
Resulting in a useless database for the attacker.

**Comment by droidmonkey** [comment]
This won't work with kdbx standard, and even if it did you wouldn't want to use it. Imagine living your database forever because you forgot to refresh a key every 4 hours. 

Use a strong password, Yubikey or OnlyKey to protect your database from theft.
