### ISSUE TITLE
Wait for AutoOpen databases to unlock before reading for Secret Service

### ISSUE THREAD

**Issue by dancojocaru2000** [keepassxreboot/keepassxc#8115]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
When using a master database to autounlock other databases, read requests for the Secret Service don't work properly.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Create a master database with an AutoOpen entry for another database 
2. Create database that holds Secret Service data
3. Configure Secret Service to use data from a group in the 2nd database
4. Lock all databases or close and reopen KeePassXC
5. Open an application requesting data via Secret Service

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
After all databases are unlocked, the secret from the proper database is offered to the requesting application.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
After first database unlocks but before all the others unlock, a "Create a new database" popup appears.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.1
Revision: 5916a8f

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: XFCE
Windowing System: X11

**Comment by droidmonkey** [comment]
Please test using the latest snapshot build, we just merged a bunch of fixes related to this.

**Comment by dancojocaru2000** [comment]
Hmm.

The AutoOpen issue seems to be solved. I seem to have another issue with Geary (which makes requests through `goa-daemon`): it shows the unlock database prompt only for database 2 (not with tabs with the master database in there too), and if I cancel it then it doesn't make any more requests. I'll have to investigate why that's the case, but for now I think those fixes seem to work?

---

While we're here, any idea when those fixes will land in a release?

**Comment by droidmonkey** [comment]
2.7.2

**Comment by drujd** [comment]
I am running 2.7.4 and am still suffering from this exact issue. Maybe this should be reopened? Or should I create a new issue?

Operating System: Arch Linux
Desktop Env: KDE Plasma
Windowing System: X11
