### ISSUE TITLE
Program Crashes When Deleting a History Entry of an Entry

### ISSUE THREAD

**Issue by kaemitsu** [keepassxreboot/keepassxc#812]
## Issue Description
When on an entry's history section, deleting a history entry from the list by pressing the `Delete` button, followed by `Apply`, and then `OK`; unexpectedly closes the program. And if the program was launched from the terminal, after the program unexpectedly closes, displays the following error message: `Segmentation fault`.

## Expected Behavior

The program should not crash or unexpectedly closed when deleting a history entry of an entry.

## Current Behavior

As explained earlier, the program crashes when deleting a history entry of an entry; by pressing in this exact order, the following buttons: `Delete`, `Apply`, and `OK`. E.g.:
![3 - 1](https://user-images.githubusercontent.com/30067080/28496074-c8804cb0-6f2f-11e7-885c-6767755a89e1.gif)

## Steps to Reproduce

1. Open the program as usual: by the use of the program's icon.
2. Select an entry, press `Ctrl+E` or the `View/Edit entry` context menu item.
3. Go to the entry's history section, and select an existing history entry.
4. Delete the entry by pressing, in this exact order, the following buttons: `Delete`, `Apply`, and `OK`.

## Context

Take advantage of all the features KeePassXC has to offer, without any misbehavior.

## Debug Info

KeePassXC - Version 2.2.0
Revisions: caa49a8ef3ee28ed478192389b21d61107b3b8e0 and 1edabc4b3c76ca72633334cdf73a42c4fda3a3ce

Libraries:
- Qt 5.9.1
- libgcrypt 1.7.8

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 4.4.52-1-lts

Enabled extensions:
- KeePassHTTP
- Auto-Type
- YubiKey

**Comment by louib** [comment]
This was fixed by #814
