### ISSUE TITLE
"Unlock Database" button doesn't always bring up Windows Hello PIN input dialog

### ISSUE THREAD

**Issue by Pinacolada64** [keepassxreboot/keepassxc#8120]
## Overview
This is on an already-opened database. Usually the computer has come out of hibernation, if that's of any relevance.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Open KeePassXC
2. Click "Unlock Database"

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
The Windows Hello dialog box to enter my PIN should appear, instead of getting a spinning busy cursor.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Occasionally after clicking "Unlock database," the Windows 10 "spinning busy cursor" will spin until I click the close button to close KeePassXC.
Then the Windows Hello PIN entry dialog will come up.
I close that and reload KeePassXC (no point in entering a PIN for KeePass at this point).
This never seems to happen twice in a row. I've tried multiple times in a row of locking the database, unlocking it, entering the PIN, then re-locking the database to see if there's any reproducible pattern, but so far I can't discern any.
Maybe I should put the laptop to sleep and see if this behavior only happens right after the wake-up event.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.1
Revision: 5916a8f

Qt 5.15.3
Debugging mode is disabled.

Operating system: Windows 10 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.19043

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 2.18.1

[NOTE]: # ( Pick choices based on your environment )
Edition	Windows 10 Home
Version	21H1
Installed on	‎10/‎20/‎2020
OS build	19043.1706
Experience	Windows Feature Experience Pack 120.2212.4170.0

**Comment by droidmonkey** [comment]
Do you have KeePassXC as Always On Top?

**Comment by Pinacolada64** [comment]
> Do you have KeePassXC as Always On Top?

No. I don't even see that as an option in KeePassXC's UI or security settings. Am I looking in the wrong place?

I've seen window menu extensions that graphics card drivers provide, but I don't have anything like that set up.

**Comment by droidmonkey** [comment]
It's in the view menu. Does the prompt show at all? Might be stuck in the background.

**Comment by Pinacolada64** [comment]
> It's in the view menu. Does the prompt show at all? Might be stuck in the background.

Found "Always On Top," thanks. No, it's not enabled, never has been, forgot to mention that.

The Windows Hello prompt does seem to be stuck in the background, Normally Alt-Tab-ing shows the window titled "Windows Security" in the window list. I'm pretty sure when Windows Hello _doesn't_ show up, it's not in the window list, as that's one of the first things I thought of, to see if I could force it into the foreground. I'll check on this the next time it happens.

**Comment by droidmonkey** [comment]
It might be at the _end_ of the window list when alt tabbing. This could be a timing issue, we currently wait 500 msec before issuing a foreground request on the windows hello prompt window. It might not be showing up until after that time expires. Do you have a slower computer?

**Comment by Pinacolada64** [comment]
Hmm, interesting.

> Do you have a slower computer?

Don't know if it's considered fast these days. The CPU info:

Intel(R) Core(TM) i3-1005G1 CPU @ 1.20GHz   1.19 GHz

**Comment by jookk** [comment]
> 

N4020, 4gb ram. So yes.

**Comment by firoball** [comment]
Hello,
I'm still facing this issue with V2.7.4.
It seems to happen only when the system is not rebooted for several weeks (only sleep mode used).
Neither is "Always on top" enabled nor can I locate the PIN prompt minimized or in background.
My system CPU is pretty old.

In case you want a new issue to be opened, please let me know. 
Thanks a lot.

Prozessor	Intel(R) Core(TM) i5-2400 CPU @ 3.10GHz   3.30 GHz
Installierter RAM	16,0 GB
Systemtyp	64-Bit-Betriebssystem, x64-basierter Prozessor
Stift- und Toucheingabe	Für diese Anzeige ist keine Stift- oder Toucheingabe verfügbar.

Edition	Windows 10 Home
Version	22H2
Installiert am	‎04.‎11.‎2020
Betriebssystembuild	19045.2486
Leistung	Windows Feature Experience Pack 120.2212.4190.0

KeePassXC info:

KeePassXC - Version 2.7.4
Revision: 63b2394

Qt 5.15.6
Diagnosemodus ist deaktiviert.

Betriebssystem: Windows 10 Version 2009
CPU-Architektur: x86_64
Kernel: winnt 10.0.19045

Aktivierte Erweiterungen:
- Auto-Type
- Browser-Integration
- SSH-Agent
- KeeShare
- YubiKey
- Schnelle Entsperrung

Kryptographische Bibliotheken:
- Botan 2.19.1

**Comment by droidmonkey** [comment]
@firoball there is nothing we can do to solve your problem since it is only happening to you. You would have to run a debugger and figure out what is going on. Please do not open an issue for this. 

> nor can I locate the PIN prompt minimized or in background

This would mean that windows hello isn't even working or enabled.

**Comment by JohnLGalt** [comment]
In addition to my reports on the seemingly similar issue where the interface is completely unresponsive when waking the computer from sleep / hibernation, I've had **this happen to me once or twice in the last year**, so I didn't think anything of it.

And this was on Snapshot builds, as I use those exclusively on my desktop for testing back and forth.

It's as if Windows really wanted to load Hello (which I use with facial recog), but never seemed to get around to doing it, from my recollection.

Since it happened only twice that I remember, I never bothered reporting, assuming it was an app on my end causing the hangup.

**Comment by firoball** [comment]
I am not sure if it is exactly the same behaviour.
In my case the UI is responsive, cursor is showing spinning wheel, though.
The PIN entry won't show up, and closing the UI is not possible either. Also saving the database is not working anymore in this state. 
In the end I need to do the task manager move. After restarting KeePassXC everything works again as it should.

**Comment by JohnLGalt** [comment]
Yes, that (exactly) is what happened to me **twice** in one entire year, as I said in my post.

The other issue I reference is the one I actually reported on, which I said was seemingly similar. This exact issue, as you describe, happened twice but I never reported because it only happened twice.

**Comment by firoball** [comment]
Just for completeness: The last official release (2.75) fixed this issue for me.
