### ISSUE TITLE
Auto-Type usage inside KeePassXC application not working any more since 2.7

### ISSUE THREAD

**Issue by tibeer** [keepassxreboot/keepassxc#8121]
## Overview
Since KeePassXC Version 2.7 and later was released, I cannot use Auto-Type inside KeePassXC any more.
Use-Case: Multiple Databases, one database holds the password for the other.

## Steps to Reproduce
1. Have two databases opened in tabs
2. One database is unlocked and holds the password for the second database
3. The entry from the first database is configured to autofill depending on the window title (//seond.*KeePassXC//)

## Expected Behavior
In Version 2.6 this was working fine.

## Actual Behavior
When hitting the keyboard combination to open the autotype dialog nothing happens. I guess this is due to the new improved auto-type features.

## Context
I don't know if this is a common use case. I have different Databases with different storage locations. I only "remember" the password for my primary database which holds the password for another. This one again holds the password for another, so a bit of cascadation. (Private DB -> Personal Work DB -> Generic Work DB)

KeePassXC - Version 2.7.1
Revision: 5916a8f

Qt 5.15.2
Diagnosemodus ist deaktiviert.

Betriebssystem: macOS 12.4
CPU-Architektur: arm64
Kernel: darwin 21.5.0

Aktivierte Erweiterungen:
- Auto-Type
- Browser-Integration
- SSH-Agent
- KeeShare
- YubiKey
- Schnelle Entsperrung

Kryptographische Bibliotheken:
- Botan 2.19.1

Operating System: Windows 10 and macOS 12.4
Desktop Env: -/-
Windowing System: -/-

**Comment by droidmonkey** [comment]
Use auto open or kdbx:// url to click open a database. Read the user guide for more information.

**Comment by tibeer** [comment]
Thanks!
