### ISSUE TITLE
Allow group level attibutes

### ISSUE THREAD

**Issue by dnai05** [keepassxreboot/keepassxc#8122]
## Summary
I love the way you can add attributes to an entry. I have found however, I am using the same attributes on multiple entries. It would be nice if I could add an attribute at a group or global level and reference that in any entry.

## Examples
1. Add ability to enter attributes at top Group level (root level)
2. Able to access these attributes using for example "{GS:xx}"

## Context
I have been using attributes as a way to reduce the length of a URL cmd. For a project, I need to open particular sites in Microsoft Edge rather than the default browser. So rather than typing in the full path for each entry I add an attribute (e.g. msedge) which I can add to the command e.g. cmd://"{S:msedge}" <URL of site>. It would be much more efficient if I could enter the attribute **once** and use it anywhere in the database.

**Comment by droidmonkey** [comment]
That is not, unfortunately, available per the kdbx specification. We cannot just implement it because it breaks our compatibility with other keepass applications. I am fairly certain something like this won't be implemented as a result.

**Comment by michaelk83** [comment]
#863 and #5502 would more or less cover this.
