### ISSUE TITLE
Root tree as tags.

### ISSUE THREAD

**Issue by Vladimir-Kondratiev** [keepassxreboot/keepassxc#8124]
## Summary
1) problem: one entry can have many logical groups  (for example multi account where one login/pass for many services like google: email account can be as cloud account at the same time. If I make 2 groups "email" and "cloud"=> I will have 2 entry with the same data (i need to sync them also... somehow to make pass valid).

2) problem: tags can solve this problem, but it will eliminate benefits of "root tree" (Tags don't have manual drug&drop order).

3. Solution: make "root tree" where each "group" is a tag (so "Database Tags" and "root tree" will be merged). Manual drug&drop order will will be preserved. Each 1 entry can belong to many "groups"="tags".

**Comment by droidmonkey** [comment]
Sorry but this won't be implemented it is not in alignment with kdbx standard and doesn't make much sense.

**Comment by Vladimir-Kondratiev** [comment]
Its lame excuse for open source. I am joking. Thanks for your response anyway.

**Comment by droidmonkey** [comment]
Open source doesn't mean free for all. Every feature requires significant effort to code, test, and maintain.
