### ISSUE TITLE
Additional attributes as columns

### ISSUE THREAD

**Issue by BaumiCoder** [keepassxreboot/keepassxc#8126]
## Summary
I have some Additional attributes in my database and I want to see them in table of entries as colums.

## Examples
(see Context underneath)

## Context
For online shops I want to see my preferred payment method at this shop directly. In Keepass2 I use columns for this.

**Comment by droidmonkey** [comment]
Duplicate request

**Comment by fnordiff** [comment]
https://github.com/keepassxreboot/keepassxc/issues/1493
