### ISSUE TITLE
URL copied in clipboard instead of password

### ISSUE THREAD

**Issue by bdvore** [keepassxreboot/keepassxc#8127]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
Hello,
The "copy password to clipboard" button sometimes copy the url into the clipboard instead of the password.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Open a database and select en entry
2. The preview panel is open and shows the url. Click on the url (the browser opens).
3. Give the focus back to KeePassXC. The url is highlighted in the preview panel with a dashed frame.
4. Click on the "copy password to clipboard" button in the menu bar (or just type "control c")
5. Paste the clipboard content in another app and you'll get the url

Note: Clicking on the entry in the entry list removes the focus from the url in the preview panel and fixes the issue for the next "copy password to clipboard" action.

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.1
Revision: 5916a8f

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: Cinnamon
Windowing System: x11

**Comment by droidmonkey** [comment]
Fixed for next release
