### ISSUE TITLE
Termius TOTP is 30 seconds slower than normal on KeePassXC.

### ISSUE THREAD

**Issue by fernvenue** [keepassxreboot/keepassxc#8132]
## Overview
When I enabled 2FA for my [Termius](https://termius.com) account, it told me that I had entered the wrong code. When I tried to use iCloud keychain, I found that actually KeePassXC gave me the correct but old code, Termius TOTP was 30 seconds slower than normal on KeePassXC because I could get the same code from KeePassXC 30 seconds after getting the code from iCloud keychain.

So is that something wrong with Termius or KeePassXC? Any way to make it 30 seconds quick?
By the way, any other TOTP on KeePassXC just works fine.

## Steps to Reproduce
1. Just add the TOTP to KeePassXC.
2. Enter the TOTP code from KeePassXC to Termius.

## Expected Behavior
KeePassXC should give me the correct and real time based TOTP code for Termius.

## Actual Behavior
KeePassXC gives me the correct code, but the code is 30 seconds slower than normal.

## Context
KeePassXC - 2.7.1
Revision: 5916a8f
Operating System: Windows 10 LTSC 2021 with 21H2

**Comment by droidmonkey** [comment]
Sync your computers time
