### ISSUE TITLE
{CLEARFIELD} only deletes one character, not the entire field contents

### ISSUE THREAD

**Issue by quinncomendant** [keepassxreboot/keepassxc#8133]
## Overview
`{CLEARFIELD}` only deletes one character on macOS.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Create an entry with this autotype sequence for www.remitly.com:
```
{CLEARFIELD}{USERNAME}{TAB}{PASSWORD}
```
3. Open [Remitley's login page](https://www.remitly.com/us/en/users/login) and enter `test@example.com` in the email address field, leave the cursor (`|`) after the last `m`, like this:
```
[test@example.com|                   ]
[                                    ]
```
5. Invoke the autotype sequence for Remitly to auto-enter the email address and password.

## Expected Behavior
The `{CLEARFIELD}` autotype keyword should completely erase the contents of the email address field, then insert the email address. The resulting contents of the fields should be:
```
[test@example.com                    ]
[••••••••••••••••••••••••••          ]
```

## Actual Behavior
Instead of erasing the entire field, `{CLEARFIELD}` just erases one character, making the resulting text in the fields this:
```
[test@example.cotest@example.com     ]
[••••••••••••••••••••••••••          ]
```

## Context
This happens for many websites, not just Remitly.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.1
Revision: 5916a8f

Qt 5.15.2
Debugging mode is disabled.

Operating system: macOS 12.4
CPU architecture: arm64
Kernel: darwin 21.5.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 2.19.1

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS 12.4
Browser: Edge

**Comment by droidmonkey** [comment]
Already fixed for next release

**Comment by quinncomendant** [comment]
Oh, great, thanks.

I searched open issues before reporting this, but didn't find a duplicate. I presume it was closed? It would be better to leave issues open until the fix is released.
