### ISSUE TITLE
google drive sync

### ISSUE THREAD

**Issue by thexmeta** [keepassxreboot/keepassxc#8136]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
Please add a feature for two-way sync with google drive database with merging.

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )
keepass native app and keepass2android has a plugin for this. Please add this feature for this. the only feature is this i cant use efficiently keepassxc.

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
The feature is so important for me because the password database i m using for my pc and android device is same. so i need this so much

**Comment by droidmonkey** [comment]
This will not be implemented. Plenty of discussions about it on here. Please search.
