### ISSUE TITLE
Enable ARM support on the PPA

### ISSUE THREAD

**Issue by cobalt2727** [keepassxreboot/keepassxc#8137]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
Could someone with access to the PPA open up https://launchpad.net/~phoerious/+archive/ubuntu/keepassxc/+edit and check a few boxes to enable builds for more architectures than x86?

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )
![image](https://user-images.githubusercontent.com/60624944/173167066-64a2294f-3f27-4f9c-8c4b-d067be16fad5.png)

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
Support for devices from manufacturers like Raspberry Pi, Radxa, Odroid, Pine64, Nvidia's Jetson product line, etc

**Comment by cobalt2727** [comment]
@phoerious

**Comment by cobalt2727** [comment]
@phoerious hi, sorry for the ping again, but unless something goes wrong this really should just be a setting change away...

**Comment by phoerious** [comment]
Done. Let's see.

**Comment by phoerious** [comment]
I bumped the ppa version number to force a rebuild: https://launchpad.net/~phoerious/+archive/ubuntu/keepassxc/+packages

**Comment by phoerious** [comment]
Bionic doesn't build due to missing dependencies.

EDIT: nvm, that's our own Botan. I can rebuild that as well.

**Comment by cobalt2727** [comment]
Thank you!
