### ISSUE TITLE
Autofill on websites that share credentials

### ISSUE THREAD

**Issue by WhyNotHugo** [keepassxreboot/keepassxc#8139]
## Summary

> [Shared Credentials](https://github.com/apple/password-manager-resources#shared-credentials): Groups of websites known to use the same credential backend, which can be used to enhance suggested credentials to sign in to websites.

How about using this data for autofill. Maybe ship the JSON file during the build/packaging process?

**Comment by droidmonkey** [comment]
There are very few sites on that list and the vast majority are cross country variations. I don't see the cost/benefit here, it would take a lot of effort to integrate this in a meaningful way. We already support multiple urls per entry, users can just use that feature.

**Comment by WhyNotHugo** [comment]
> I don't see the cost/benefit here, it would take a lot of effort to integrate this in a meaningful way. We already support multiple urls per entry, users can just use that feature.

The issue with the current implementation is that each single user has to maintain their own database of websites. Even if I do a lot of work and make a good list of webistes, every single other user has to re-do the work. Shipping a website as part of KP means having _one_ database of these.
