### ISSUE TITLE
Unable to set backup direcotry

### ISSUE THREAD

**Issue by 226cenk** [keepassxreboot/keepassxc#8140]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Open KeepassXC applicatoin
2. Go to settings by hitting the cog on the toolbar
3. Go to the 'General tab'

## Expected Behavior
Be able to set the backup directory

## Actual Behavior
There is just a radio button to enable. Doesn't seem to do anything.

## Context
[NOTE]: # ( Give us any additional information you may have. )
We were all able to set the backup directory before some update or something. Now, the option seems to be gone/missing.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.6.6
Revision: sudo apt install keepassxc

[NOTE]: # ( Pick choices based on your environment )
Operating System: Ubuntu 22.04
Desktop Env: Gnome/Cinnamon
Windowing System: X11/Wayland
https://imgur.com/a/SsnFdNP

**Comment by droidmonkey** [comment]
Update to 2.7.2
