### ISSUE TITLE
Windows Hello will Unlock Database when Pressing "Cancel"

### ISSUE THREAD

**Issue by trytodupe** [keepassxreboot/keepassxc#8141]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
title

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Enable database quick unlock
2. While Database locked, click on Unlock
3. Press "Cancel" in the Windows Hello window

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Database shouldn't be unlocked when pressing "Cancel" on the Windows Hello window

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Database will be unlocked after pressing "Cancel" on the Windows Hello window

## Context
[NOTE]: # ( Give us any additional information you may have. )
I have no password required when unlocking database, all i have is just a key file
I only have pin for Windows Hello

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.1
Revision: 5916a8f

Qt 5.15.3
Debugging mode is disabled.

Operating system: Windows 10 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.22621

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 2.18.1

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 11 22621.1

**Comment by droidmonkey** [comment]
The only thing you canceled was enabling quick unlock for that session. Windows hello doesn't unlock your database.

**Comment by trytodupe** [comment]
so then whats the point of enableing database quick unlock?

**Comment by droidmonkey** [comment]
You can read about it in our user guide: https://keepassxc.org/docs/KeePassXC_UserGuide.html#_quick_unlock

The general sequence is:

1. Open database 
2. Provide your credentials
3. Unlock your database 
4. If successful, ask windows hello for an encryption key to encrypt your credentials for future use (this is what you canceled)
5. Lock database
6. Quick unlock... ask windows hello for the encryption key again, decrypt your stored credentials, use them to unlock your database

**Comment by trytodupe** [comment]
ohh i thought the first windows hello is for unlocking database as well cuz ive never seen the Quick Unlock screen before
