### ISSUE TITLE
KeePass closes upon Windows pin entry following Windows hibernation

### ISSUE THREAD

**Issue by r4b8iiiiiit** [keepassxreboot/keepassxc#8142]
## Overview
# KeePass closes upon Windows pin entry following Windows hibernation

## Steps to Reproduce
1.  Open KeePassXC and login to database.
2.  Put computer in hibernation mode.
3. Turn computer back on and log in.
4. KeePass will ask for password for database login, followed by Windows Pin.
5. Upon entering of pin, KeePass will close entirely.

## Expected Behavior
KeePass should open the database after Windows Pin Entry

## Actual Behavior
KeePass closes upon Windows Pin entry

KeePassXC - Version 2.7.1
Revision: 5916a8f

Operating System: Windows 11

**Comment by droidmonkey** [comment]
Same as #7977
