### ISSUE TITLE
Attachments corrupted (need more information)

### ISSUE THREAD

**Issue by Fred-IV** [keepassxreboot/keepassxc#8143]
I am going to have to go back to 1password.
I've been using and liking KeePassXC for a while, and now I discover more than half of my attachments in my database are corrupted.
This is unacceptable.
Most of my screenshots of ID, receipts, etc are all blown away.
Here's an attachment of an ID card that is destroyed. More than half of my images are like this. I have lost a lot.
Do not trust this garbage. Software bugs are one thing, but data corruption is not acceptable.

![id](https://user-images.githubusercontent.com/66499758/173251740-6a4d7aaf-251b-4461-a5fc-46a92a009f95.jpg)

**Comment by droidmonkey** [comment]
Need to know a little more about this please. Did you use any other keepass programs (mobile, web, etc) to open your database? Did you attempt to edit the attachments after adding them to entries? 

We have never had reports of attachment corruption, so if there is a problem we would like to fix it.

This image appears to be made using a flatbed scanner. The manner in which it is corrupted appears to me like it was always corrupted. When something encrypted gets corrupted it is totally destroyed. This is cut off at a distinct point making me believe it was an error during transmission from the scanner.

Here is a better visualization of the image as a whole showing the cutoff point:

![image](https://user-images.githubusercontent.com/2809491/173253256-b0f47cde-ad20-4e2e-bf46-c666ae7c858d.png)

**Comment by Fred-IV** [comment]
Nope, again,  more than half are corrupted. From many sources, iPhone cam, scanner, screenshots, etc. The images were verified and fine when I put them in. I only just discovered that many are destroyed.
I am in the process of going back to 1password.
They have never been edited.
Also, they are not all corrupted in the same spot.

**Comment by phoerious** [comment]
Not very helpful. If this is indeed an issue with KeePassXC, we would like to fix it, but we definitely need more info. Like this, we have to assume something else outside our control went wrong.
