### ISSUE TITLE
在浏览器中使用密码生成器后会导致程序卡死

### ISSUE THREAD

**Issue by OR120** [keepassxreboot/keepassxc#8149]
## Overview
先打开程序的某个网站的编辑页面，再在浏览器中使用密码生成器后会导致程序卡死
![图片](https://user-images.githubusercontent.com/45073607/173503485-c94c5c9b-9a1f-4806-84e7-b6362cf1f64e.png)

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 版本 2.7.1
修订版本：5916a8f

Qt 5.15.3
已禁用调试模式。

操作系统：Windows 10 Version 2009
CPU 架构：x86_64
内核：winnt 10.0.22000

已启用的扩展：
- 自动输入
- 浏览器集成
- SSH 代理
- KeeShare
- YubiKey
- 快速解锁

密码学公共库：
- Botan 2.18.1

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows
Windowing System: windows 11 stable稳定版
![图片](https://user-images.githubusercontent.com/45073607/173504764-28420684-db9c-46ba-9a77-8f72b1a141dd.png)

**Comment by droidmonkey** [comment]
It doesn't freeze, the generator will pop up (I just used this yesterday) you need to close the generator to use keepassxc again. There is another issue tracking a potential problem if you use the X button to close the generator.
