### ISSUE TITLE
Would KeepassXC's implementation of YubiKey work with a generic U2F/FIDO key?

### ISSUE THREAD

**Issue by leonyu** [keepassxreboot/keepassxc#815]
Would KeepassXC's implementation of YubiKey work with a generic U2F/FIDO key?

I am considering buying a generic U2F/FIDO key ($10-20), but don't want to shell out the money for a premium YubiKey ($40). 

If this is the case, it might be good to document it as such to promote its usage.

**Comment by phoerious** [comment]
No, your Yubikey needs to support HMAC-SHA1.

**Comment by AzureRaptor** [comment]
How difficult would it be to add support for FIDO U2F?  There are a great many hardware devices out there now that support this.

Is there any genuine security reasoning, such as for TOTP, not to support this?

**Comment by phoerious** [comment]
TOTP and U2F are inherently incompatible with offline databases. See also https://keepassxc.org/docs#faq-yubikey-why-hmac-sha1

**Comment by AzureRaptor** [comment]
Thank you for linking me to that FAQ entry; I'm sorry I missed it.

I did some more detailed digging (again, sorry I missed this the first time - not sure how ;), and [this thread](https://github.com/keepassxreboot/keepassxc/pull/127#issuecomment-310997339) goes into much more detail.  I'm _starting_ to understand the issue(s).  I'm still not sure why KpXC can't keep track of the same counter (c) as the given hardware token, given U2F is an open standard, but I guess that just means I've got a _lot_ more reading about crypto ahead of me.  ;}  Thank you for your patience.  You guys are awesome!

**Comment by phoerious** [comment]
KeePassXC can do whatever it want, but KeePassXC is also not the authenticating component. That's the crypto container and the container can do nothing, because it is just a file. Therefore it can't keep track of counters. KeePassXC is just the client.

**Comment by leonyu** [comment]
I did some digging awhile back after I posted the question. Based on my understanding, U2F keys simply a physical private/public key authenticator. It cannot be used to store arbitrary payload. 

A full YubiKey is also a [OpenPGP card](https://en.wikipedia.org/wiki/OpenPGP_card) which can be used to store arbitrary secret and has the ability to use the secret for signing and keygen. This secure storage and keygen feature is what's used to implement the challenge response. So theoretically, a generic OpenPGP card could be made to work.

**Comment by phoerious** [comment]
We don't use OpenGPG, we use HMAC-SHA1. PGP encryption would be possible too, but would require some refactoring, since then encryption is done outside KeePassXC.

**Comment by bgmnt** [comment]
According to this discussion, I understand, that asking for support support of FIDO2/Webauthn devices like the one from [solokeys](https://solokeys.com/) is also nonsense, since Keepass can not use them for technical reasons. Right? (So I would not bother someone here with a new feature request.) Sorry nondev hier.

**Comment by phoerious** [comment]
Yes.
