### ISSUE TITLE
Force to use Windows Hello

### ISSUE THREAD

**Issue by wulfsch** [keepassxreboot/keepassxc#8150]
Hello everyone,

First of all: Thank you for adding Windows Hello for Quick Unlock. The only issue I have is that at first, I was quite confused when I discovered that on opening a database, one can simply "cancel" the Windows Hello Dialog window and get in anyway. I know that Windows Hello is only used for Quick Unlock after opening the database for the first time - still, I would find it really nice if one is forced to use Windows Hello when you open the database for the first time as well. As long as this is not the case, it would be nice to have at least some kind of hint on the opening screen so that other users don't have to share the same confusion as I did when I discovered this.

**Comment by phoerious** [comment]
The first prompt is only for activating Hello for subsequent unlocks. There is no way to "force" users to use Windows Hello.
