### ISSUE TITLE
Steam TOTP

### ISSUE THREAD

**Issue by FrostKiwi** [keepassxreboot/keepassxc#8151]
## Summary
Apps like FreeOTP, FreeOTPPlus, andOTP, Kee Vault, Aegis, etc. support the output of Steam's TOTP format, which is a 5 digit code with Letters.
I would like to finally ditch FreeOTP+ on my phone, because it's the only TOTP that KeePassXC doesn't support.

## Examples
Here is what it looks like in FreeOTP+ (Webcam photo, since FreeOTP+ blocks Screenshots)
![image](https://user-images.githubusercontent.com/60887273/173517963-b9dc3ed2-738d-4a4f-a335-29a54038f995.png)

## Context
It would be really pleasant, if KeePassXC could cover such a widely used service like Steam.

**Comment by droidmonkey** [comment]
We already do

**Comment by FrostKiwi** [comment]
Ohh, then I must have misconfigured something, sorry.
