### ISSUE TITLE
Browser search suggestions from KeePassXC URLs

### ISSUE THREAD

**Issue by lionkmp** [keepassxreboot/keepassxc#8152]
## Summary

KeepPassXC is the best collection of our most important websites.  Especially those where we have a login. The browser URL bar "autocomplete search" could offer URLs stored in KeePassXC.

This would provide secure way to access URLs without typos in secure environments, where browser is configured not to remember URLs or after that data is cleared or if certain URLs are always opened in private window.

## Examples

Would appear similar to bookmark search-results, that display with a star icon, just another icon.

Keep up the good work! Thank you!

**Comment by droidmonkey** [comment]
#6889
