### ISSUE TITLE
List All Entries by Modification Date

### ISSUE THREAD

**Issue by twt2** [keepassxreboot/keepassxc#8154]
Suggestion: Add a report of KeePass database entries sorted by modification date/time.

Background: I keep the hoary old KeePass2 (mono application)* installed for one feature -- it has a report showing the entries sorted by modification date & time. 

Menu: Find --> Last Modified Entries...

This is very useful when I make a change to the database on my Android phone or somewhere, and DropBox decides there's a conflict. Then I have two or more files to examine and I want to be certain which conflicted copy(ies) have the most recent changes.

I see KeePassXC** has a menu item: Database --> Database Reports...

When I choose Database Reports on my current system*, I see four "reports." "Statistics," "Browser Statistics," "Health Check," and "HIBP.

Is there an straightforward way for me to add my own report showing the entire database sorted by modification time? 

Maybe such a report is already possible using the current interface, but if so, I have not discovered it. 

I know I could export the data to CSV and sort in a spreadsheet, but I'd rather not create a bunch of insecure files to do this.

*Keepass2 version 2.47 installed from Ubuntu repositories

**KeePassXC version 2.7.1 on Ubuntu 21.10

**Comment by droidmonkey** [comment]
Search for `*` then sort by modified column

**Comment by droidmonkey** [comment]
BTW there are other requests open here asking for Global database changes report and merge reports. So those are where we will put our effort at some point.

**Comment by twt2** [comment]
I should have thought of searching for * . Thank you for the tip!
