### ISSUE TITLE
KeeShare PrivateKey sometimes being written to keepassxc.ini

### ISSUE THREAD

**Issue by thedewi** [keepassxreboot/keepassxc#8155]
Sometimes KeePass 2.7.1 writes my KeeShare private key to keepassxc.ini.

It doesn't need to be in there, and probably shouldn't be saved in plain text. I keep reverting the change and KeeShare continues to work fine. This only happens sometimes.

I share my database and keepassxc.ini between machines, and my key is different between machines, so I am getting sync conflicts.

**Comment by thedewi** [comment]
Here is an example with my key replaced with `$CENSORED`.

```
[KeeShare]
Own="<?xml version=\"1.0\"?><KeeShare><PrivateKey>$CENSORED</PrivateKey><PublicKey><Signer>dewi</Signer><Key>$CENSORED</Key></PublicKey></KeeShare>\n"
```

Also of note: the private key string is exactly the same as the public key string. This doesn't seem right.

**Comment by phoerious** [comment]
Don't worry about the key. Signing KeeShare containers is deprecated anyway, since it offers no real benefit, but makes everything more complicated. I do agree that this should probably be in the local INI file, not in the shared one, but it doesn't really matter, since the keys don't matter.

**Comment by droidmonkey** [comment]
The key is meaningless and is only there for backwards compatibility with prior versions of KeePassXC. Please ignore. It will be entirely removed in 2.8.0.
