### ISSUE TITLE
KeepassXC hangs when trying to copy value from Advanced tab

### ISSUE THREAD

**Issue by vampyren** [keepassxreboot/keepassxc#8156]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1.  double click / click on the fields "Advanced --> attributes"
2. 
3. 

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Copy the content of the field

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
The whole app hangs for about 10-15 second

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.1
Revision: 5916a8f

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 11 x64

![image](https://user-images.githubusercontent.com/4087127/173764182-08f8504c-f151-4bdd-919c-fe3f9e7f29d6.png)

**Comment by droidmonkey** [comment]
Cannot replicate at all

**Comment by vampyren** [comment]
I pretty much could do it each time but just now when i try it dont work. I'm puzzled myself. 
Another thing i learn is that double clicking the field in Advanced actually copies the data! 
In General it does the same but it select the text. Not very consistent. 
I let you know if i learn to reproduce the hang. Cheers.
