### ISSUE TITLE
Keepassxc requests access to the network

### ISSUE THREAD

**Issue by Eyion** [keepassxreboot/keepassxc#8157]
## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
All the programs in my computer need my approval to connect to the Internet, because I have made Settings in the firewall, today I found that KeePassXC sent a request to the firewall to connect to the Internet, the connection address is 20.205.243.168:443, who can tell me what is going on?

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.1

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 10 Enterprise LTSC
Operating System Version:1809(64bit)

![image](https://user-images.githubusercontent.com/26318038/174220911-40f10af5-cc3a-4427-9d6b-b9f1e71b32dc.png)

**Comment by droidmonkey** [comment]
Update check... disable it in settings.
