### ISSUE TITLE
[Quick win] Ability to copy the entry path inside the database group structure

### ISSUE THREAD

**Issue by Freeedim** [keepassxreboot/keepassxc#8158]
## Summary
When documenting where to find credentials in a database having many groups and subgroups, it would be very convenient to be able to copy an entry's path in order to paste it in the manual I am writing.

This could be by making the path displayed in the lower overview panel selectable, or in the right-click menu on an entry.

Or, why not, a place holder for autotype could exist for that like {ENTRY_PATH}

## Context
I need to document where to find various credentials in a large and complex database to new colleagues.

I use Debian Testing with KeePassXC from the repos (only 2.6.6 at the time) KDE Plasma with Qt look and feel, X11 session.

**Comment by droidmonkey** [comment]
This was implemented in 2.7.0

**Comment by thomas-mc-work** [comment]
I'm on 2.7.1 and can't find a way to achieve this. A simple right click -> copy isn't possible:

![keepassxc](https://user-images.githubusercontent.com/6542498/176871371-304253f0-1a0c-4cc8-95d3-6417ad313804.png)

**Comment by droidmonkey** [comment]
Select the text first....
