### ISSUE TITLE
Keepassxc windows 11 not opening from sd card

### ISSUE THREAD

**Issue by spillaip** [keepassxreboot/keepassxc#8159]
Have installed keeppassxc ver 2.7.  Tried to open file from sd card, but it is showing header id error.  The same file from the harddisk works fine.

Same file works fine from sd card in windows 10, Fedora 35.

**Comment by droidmonkey** [comment]
This isn't something we would be doing? There is no distinction for files between windows versions or cross platform.

**Comment by droidmonkey** [comment]
The only thought I have is if you formatted the sdcard as ext3 or ext4 then you'd need the right software on windows 11 to read the files.

**Comment by spillaip** [comment]
Reading the file from the sd card is not the issue.  I am able to view
other files, read/write to the sd card using other programs.  KeepassXC
tries to read, but has some issues with it.  Having said that, if I copy
the file to the hard drive, then the file is opened without any issue.
This indicates, keepassxc has an issue reading from micro sd card.  Request
you to investigate.

Thank you
PB Suresh
Clinical Psychologist | Neuroeconomist | Life Coach | Technology Enthusiast
