### ISSUE TITLE
AutoType broken on Linux since 2.7.0 (and still on the latest snapshot build 213927)

### ISSUE THREAD

**Issue by silentcreek** [keepassxreboot/keepassxc#8161]
## Overview
I upgraded my OpenSUSE Leap desktop from 15.3 to 15.4 recently which also entailed an upgrade of KeePassXC 2.6.4 to 2.7.1. With the new release, I found that any time I try to use AutoType, my X11 would crash. As soon as I trigger AutoType on any of my stored credentials, my screen goes to a virtual console briefly and then back to the login screen. In the system journal I also see lots of applications complaining: "The X11 connection broke (error 1). Did the X11 server die?"

After reading that KeePassXC 2.7.0 has refactored code for AutoType on X11, I tried the latest snapshot build 213937 (dated June 14), but that doesn't fix the issue, unfortunately. Reverting to 2.6.6 fixes the issue.

## Steps to Reproduce
1. Install KeePassXC 2.7.0+ on OpenSUSE Leap 15.4
2. Open your database and try AutoType on any entry with any application in the background (browser, editor, etc.)

## Expected Behavior
Username/password entered to last opened window.

## Actual Behavior
X11 session crashed and login screen comes up again.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.1
Revision: 213937
(affects 2.7.0 as well)

[NOTE]:
Operating System: Linux (OpenSUSE Leap 15.4)
Desktop Env: KDE
Windowing System: X11

**Comment by silentcreek** [comment]
Two more notes:
1) It doesn't matter if you use the keyboard shortcut to trigger AutoType or the mouse in the GUI. The result is the same (X11 session gone).
2) I originally used the rpm package by my distribution. But the other builds I tested (2.6.6, 2.7.0, 2.7.1-213937 snapshot), were the AppImage builds found on keepassxc.org.

**Comment by michaelk83** [comment]
Same as https://github.com/keepassxreboot/keepassxc/issues/7797#issuecomment-1110963952

**Comment by droidmonkey** [comment]
This is an X11 bug that we are triggering with our keyboard mapping for auto-type. You will have to use a different keyboard mapping to avoid triggering it for now.

**Comment by silentcreek** [comment]
> This is an X11 bug that we are triggering with our keyboard mapping for auto-type. You will have to use a different keyboard mapping to avoid triggering it for now.

Thanks, but could you elaborate a bit more? The mentioned bug #7797 doesn't mention keyboard mapping and a quick search through recent issues didn't bring up anything either. By keyboard mapping, you mean the chosen locale for the keyboard (which is German, in my case)? Or is there a setting within KeePassXC that I can alter? Is this bug reported upstream?

**Comment by droidmonkey** [comment]
Reporting this is like yelling at a brick wall. It's not worth our time. We are going to investigate if it's possible to avoid triggering the bug in some way without removing the enhancements we have.
