### ISSUE TITLE
Remember last column sorted on AutoType

### ISSUE THREAD

**Issue by BanCrash** [keepassxreboot/keepassxc#8163]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
Remember last sorted column on AutoType.

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )
After sorting by title, on the next launch of AutoType it will be sorted by title again:
![image](https://user-images.githubusercontent.com/11770760/174124845-067135fd-4dd6-49f8-891f-6a072ce7d683.png)

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
If this is added, when I sort by Title on AutoType, after closing it and opening it again it will be sorted again by Title instead of reseting the sort to Global field.

Sometimes I have to sort by title in AutoType because Global have a confussing order to me in some cases.

I search on issues and discussions and I didn't found anyone asking about this so I think this is not duplicated.

**Comment by droidmonkey** [comment]
#1684

**Comment by BanCrash** [comment]
> #1684

Oops, I searched for AutoType, sorry!
