### ISSUE TITLE
copy to clipboard is not working on Linux Mint

### ISSUE THREAD

**Issue by hellaconf** [keepassxreboot/keepassxc#8164]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. use ctrl-c to attempt to copy password to clipboard
2. click the copy password option after ctrl-c did not work
3. 

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
The password to be copied to the clipboard

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
no indication that the password is copied and when trying to paste there is no text saved to the clipboard 

## Context
[NOTE]: # ( Give us any additional information you may have. )
was working fine, until i reconnected the drive holding the db

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.4.3
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux Mint
Desktop Env: Cinnamon
Windowing System: X11/Wayland

**Comment by droidmonkey** [comment]
You are wayyy behind in versions. Also clipboard on Wayland is spotty and likely a qwayland bug.

**Comment by hellaconf** [comment]
Thank you very much, I apologize for my ignorance.
