### ISSUE TITLE
Add shortcut key to copy password in Auto-Type

### ISSUE THREAD

**Issue by mkd808f** [keepassxreboot/keepassxc#8166]
## Summary
I hope there will be a shortcut key for copy password in Auto-Type like Ctrl +1 for {USERNAME}.
It would be better if there could be an option for shortcut keys.

## Examples
[IMG_20220618_192932](https://user-images.githubusercontent.com/90968481/174435688-b8317a38-ca1c-4ecb-8354-8cb000d864cb.jpg)
I just want simple things like this.Sorry for my poor image editing.

## Context
There's something wrong when I use Auto-Type with extended ascii characters,but copying them and then pasting is fine.So I want a shorcut key for copy password in Auto-Type.
Sorry for my poor English.

**Comment by droidmonkey** [comment]
It's a bug that is fixed for upcoming 2.7.2

**Comment by Parollel** [comment]
Thank you for your fast reply.

**Comment by mkd808f** [comment]
> It's a bug that is fixed for upcoming 2.7.2

Alright.Thank you.
