### ISSUE TITLE
Clipboard not cleared for Phone Link app

### ISSUE THREAD

**Issue by Acrosicious** [keepassxreboot/keepassxc#8172]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
When your phone is connected to Windows via the [Windows Phone Link App](https://support.microsoft.com/en-us/phone-link) and clipboard share is enabled, the clipboard contend copied from Keepass is also displayed on the Android keyboard. After the `Security_ClearClipboardTimeout` the clipboard content on Windows is cleared, but remains available on Android.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Copy password in Keepass.
2. Enter a textfield on Android phone connected via Phone Link.
3. Password is shown in clear text at the top of the android keyboard forever.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
I would expect / wish for either:
1. Password to be cleared in a way, that it does not remain in the clipboard on Android (and Windows).
2. Password not transferred over Phone Link to Android at all. (Without changing how Phone Link works. I think it should work without using the workaround of disabling clipboard transfer completely.)

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Copied password is shown in Android even after Keepass clears the clipboard.

## Context
[NOTE]: # ( Give us any additional information you may have. )
When copying a single space on Windows, this gets transferred to Android via the phone link app.
Thus, I assume a possible first fix could be, to pass new clipboard content, instead of an empty string [here](https://github.com/keepassxreboot/keepassxc/blob/439c155552f6508ae26a7a43f9361fc0ee23a307/src/gui/Clipboard.cpp#L100): 

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.1

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 11 + Android 10

**Comment by droidmonkey** [comment]
We have no control over what phone link app is doing. We already set the sensitive flag on clipboard entries. So if it's not respecting that flag then there is nothing we can do about it.

**Comment by droidmonkey** [comment]
Here is where that is done: https://github.com/keepassxreboot/keepassxc/blob/develop/src/gui/Clipboard.cpp#L65
