### ISSUE TITLE
Keepassxc-cli 'show' command won't reveal passwords even provided the master password

### ISSUE THREAD

**Issue by gnrlus** [keepassxreboot/keepassxc#8173]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )

Keepassxc-cli 'show' command won't reveal passwords even provided the master password, thus the only way to get it is export the entire database. Since I'm already supplying the master password what is the point in preventing me from reading my passwords using the 'show' command? That just makes it harder for me to get them. Someone else with the master password can simply export them.

Therefore, I suggest that 'show' should reveal passwords.

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )

i.e. I'd like to be able to do this and not have to export the entire database:
keepassxc-cli show [database.kdbx] group/entry | grep "Password"
Enter password to unlock [file.kdbx]:
Password: 123passwordABC

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )

I run scripts to manage data which access data from other databases and I'm considering storing some of that data in KeepassXC because it's a fine database and it may work well to have all my OpSec-related database entries along with my credentials in the same database. But I need to be able to query it. Exporting can be done as a work-around but I feel this should just be changed. If the database gets large exporting could take awhile too.

And if I'm just trying to recover a password from the command line I don't want to have to comb through the whole database- even with search tools it can be a pain to find what I'm looking for.

Thanks! :)

**Comment by droidmonkey** [comment]
https://github.com/keepassxreboot/keepassxc/blob/develop/docs/man/keepassxc-cli.1.adoc#L255-L256

Use the `-s` command line switch. 

You should use `-help` to see your options.
