### ISSUE TITLE
Insufficient space for saving results in truncated and corrupted file

### ISSUE THREAD

**Issue by bgardner-noggin** [keepassxreboot/keepassxc#8176]
## Summary
I have a keepass file stored on a network share. This network share ran out of space. I modified an entry in my keepass file and saved.

Keepass gave no indication that there was anything wrong until I attempted to open the file at a later date. At which point it could not be opened as the file was truncated and thus corrupted.

I had a backup, so only my last day of changes was lost.

Ideally, keepassxc would prevent itself from overwriting the existing file if there is insufficient space or failing that, indicate that the save did not succeed.

This was running KeepassXC on linux

**Comment by droidmonkey** [comment]
Are your saving settings set to direct write? And we rely on the operating system (via qt) to tell us when writing failed. If that doesn't happen there is really no way to know. Running out of space on the drive would prevent safe saves from working.

**Comment by michaelk83** [comment]
> If that doesn't happen there is really no way to know.

#7226 should catch this, when it's implemented.

**Comment by bgardner-noggin** [comment]
My save settings are the defaults. ie I do not have _Use alternative saving method_ checked

It looks like 7226 would prevent this from happening silently.

**Comment by droidmonkey** [comment]
Sounds like the writing succeeded to the device but the device failed to complete the write. That's the only explanation I can come up with.

**Comment by bgardner-noggin** [comment]
Most likely what occurred is that the file operation on my side failed silently. I've since added space to the device so I don't have an easy way to test this.

It appears that 7226 will resolve this. So I'll close this issue. Thanks.
