### ISSUE TITLE
Make it possible to remove a space (or add your own mask) for OTP

### ISSUE THREAD

**Issue by valsaven** [keepassxreboot/keepassxc#8177]
## Summary
If you copy the code, it will be with a whitespace. This is often very annoying and you have to manually delete it.

## Examples
![image](https://user-images.githubusercontent.com/16094011/174796439-4cd02e9d-b573-49f5-978f-a5f5062a77c7.png)

## Context
The OTP field is not always detected correctly by the browser, and sometimes you have to insert it manually.

**Comment by droidmonkey** [comment]
We offer many ways to copy totp or use autotype. This display is meant for hand writing the code. Read the user guide for more on the other ways to copy totp.
