### ISSUE TITLE
.kdbx database file not accepted if hidden (Linux, v.2.7.1) 

### ISSUE THREAD

**Issue by raphaeltrevizani** [keepassxreboot/keepassxc#8179]
## Overview
My .kdbx database is hidden (starts with a .) on Linux, but KeepassXC no longer reads the file or accepts it on the dialog created by clicking on the 'Open existing database' box.

## Steps to Reproduce
1. Add a dot '.' as first character of the database file (.kdbx) 
2. Try to open this file as your existing database.

## Expected Behavior
A hidden file should be read as any other file.

## Actual Behavior
The file does not show up on the dialog box.

**Comment by droidmonkey** [comment]
I assume you are using the snap version. Snaps cannot read hidden files. Switch to flatpak or appimage. Although there is no reason to hide your database file.
