### ISSUE TITLE
Merge does not work as expected

### ISSUE THREAD

**Issue by mcqj** [keepassxreboot/keepassxc#818]
# Merge results in a duplicate of every entry

## Expected Behavior
Expect that when merging two databases that the resultant database would have a single entry if the  entries in both databses are exactly the same

## Current Behavior
Every entry from each database appears in the resultant merged database, meaning that most entries which are identical end up being duplicated in the resultant database.

## Steps to Reproduce (for bugs)
1. Open one database.
2. Merge it with a second almost identical database.

## Debug Info
KeePassXC - Version 2.2.0
Revision: caa49a8ef3ee28ed478192389b21d61107b3b8e0

Libraries:
- Qt 5.9.0
- libgcrypt 1.7.7

Operating system: macOS Sierra (10.12)
CPU architecture: x86_64
Kernel: darwin 16.6.0

Enabled extensions:
- KeePassHTTP
- Auto-Type
- YubiKey

**Comment by louib** [comment]
@mcqj  by exactly the same you mean they have the same name and reside in the same group? Right now we only match entries based on their underlying identifiers (UUID). So unless the database was the same one to begin with, new entries will be created even if the names match.

Can you tell me what was your use case exactly?

@keepassxreboot/core-developers This is somewhat related to https://github.com/keepassxreboot/keepassxc/pull/807. I think matching the entries by name could make sense in the context of a merge, but a sync should look for UUIDs instead. This might be an argument to separate the sync and merge functionalities.

**Comment by TheZ3ro** [comment]
@louib Sync should be a different thing then merge, see #90

**Comment by droidmonkey** [comment]
Concur with separation

**Comment by mcqj** [comment]
@louib They are the same name and the same group.
To explain the use case:- I use multiple machines and copy the database back and forward between them. Normally, any time I make a change on a machine, I'll just copy the database to my other machines and I try not to make modifications on two machines before I've updated them all. However, occasionally I end up updating entries on two machines. If I try to merge, I get all of the duplicates as described. So, the databases have started out as identical and I've maybe modified one entry on each, no changes to groups. Both machines are running OSX Sierra.

**Comment by ericblank** [comment]
I'd like to, for example, merge my lastpass database with my keepass DB, ignoring matching entries, and maybe putting mismatches into a folder to manually update.
