### ISSUE TITLE
{PICKCHARS} pastes password chars with tabulators between each character

### ISSUE THREAD

**Issue by JakubChromiak** [keepassxreboot/keepassxc#8180]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
When autotyping a password with PICKCHARS placeholder, after each character there is additional tab char after each password char

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Save a password with custom autotype formula {DELAY 500}{PICKCHARS}{ENTER}
2.  Try to autotype password

## Expected Behavior
Only characters from password are pasted

## Actual Behavior
After each password character there is tab character

## Context
In many places, masked passwords automatically move a cursor to next bracket to enter passwords' character. Putting additional tab character between passwords character defeats the point of using PICKCHARS placeholder.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.1
Revision: 5916a8f
Distribution: Snap

Qt 5.15.3
Debugging mode is disabled.

Operating system: Ubuntu Core 20
CPU architecture: x86_64
Kernel: linux 5.15.0-39-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.12.1

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: Gnome
Windowing System: X11

**Comment by droidmonkey** [comment]
Uncheck the box that says "type tab between each character" in the pickchars dialog.
