### ISSUE TITLE
KeePassXC is crashing my desktop when autotype is used. 

### ISSUE THREAD

**Issue by purevw** [keepassxreboot/keepassxc#8181]
When I first choose autotype, nothing happens. If I expand the autotype menu and choose to fill both fields, I am prompted if I want to enter the data into the previous open window. Upon selecting yes, the desktop and / or xserver crashes and takes me back to user login. I recently upgraded to openSUSE 15-4 and this may be a security related issue because of newer policies in the OS (speculation). This behavior was not present in openSUSE 15.3

System: openSUSE Linux 15.4 
KeePassXC 2.7.1

**Comment by droidmonkey** [comment]
We are inadvertently triggering an X11 bug that causes it to crash. @hifi

**Comment by droidmonkey** [comment]
#8161 and #7797

**Comment by purevw** [comment]
X was upgraded in openSUSE 15.4 today and the problem is resolved.
