### ISSUE TITLE
Minimize window on startup does not work

### ISSUE THREAD

**Issue by bjwest** [keepassxreboot/keepassxc#8183]
## Overview
KeepassXC does not start minimized when the "Minimize window at application startup" box is checked in settings.

## Steps to Reproduce
1.  Check "Minimize window at application startup" box in settings and click "OK"
2. Exit app
3. Restart app

## Expected Behavior
KeepassXC starts minimized to system tray.

## Actual Behavior
KeepassXC window opens on desktop.

## Context
This has been an ongoing issue for quite some time now.  Both X and Wayland.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.1
Revision: 5916a8f

Qt 5.15.4
Debugging mode is disabled.

Operating system: KDE neon User - 5.25
CPU architecture: x86_64
Kernel: linux 5.13.0-35-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.12.1

Operating System: Linux
Desktop Env: KDE
Windowing System: X11/Wayland

**Comment by bjwest** [comment]
New info on this issue.  It seems to not obey the minimize on start setting when started at boot up.  If started manually after the system is up and running, it does start minimized.

**Comment by droidmonkey** [comment]
Then that means you are starting keepassxc twice on login. Once with our autostart and another with your desktop environment.  Make sure you don't have it set to load all apps you had open on logout. This was the exact problem another user had.
