### ISSUE TITLE
Support for a backup Yubikey

### ISSUE THREAD

**Issue by johnvirg** [keepassxreboot/keepassxc#8185]
I use a Yubikey to support challenge-response on a KeePassXC database. Yubikey recommends having a backup key in case your primary gets lost. This has happened to me twice. If you lose the Yubikey there is no way to decrypt your database - game over. I can't set up a second Yubikey with the same challenge-response secret key because XC wants the Yubikey serial number to match. I would like to be able to use a backup Yubikey without being tied to the serial number, or for the XC database settings to support multiple serial numbers with either the same or different secret keys in that case. Until this is an option, I can't use the challenge-response safely because the risk of losing the key is too high to lose my entire database. Thank you.

**Comment by droidmonkey** [comment]
We don't care what the serial number is. We only remember the serial number of the key used to open the currently unlocked database. Once locked the serial number is not relevant.

What is relevant is that the keys have the same exact secret key loaded on them.
