### ISSUE TITLE
Rotate functionality

### ISSUE THREAD

**Issue by wibed** [keepassxreboot/keepassxc#8186]
## Summary
A cli option to rotate all or a selection of passwords inside the database. 

## Examples
a temporary entry containing the old password, and  a new entry containing a new password. 
to facilitate rotation.

## Context
this functionality may seem trivial even unusable at first but could, accessible by the browser api,  automatically connect to a service/site/anything using the old password, changing it to the new and mark the entry as "rotated".

**Comment by droidmonkey** [comment]
This doesn't make sense and would be impossible to implement correctly. There is already a request to support a change password workflow for the gui.
