### ISSUE TITLE
Copy entire entry contents into clipboard

### ISSUE THREAD

**Issue by MountainX** [keepassxreboot/keepassxc#8187]
## Summary

Provide a single command, ideally with a shortcut key, to copy all the data of an entry into the system clipboard as text.

## Examples

We have Ctrl+B to copy the username, Ctrl+C to copy the password, Ctrl+U to copy the URL. I often want all of those copied as one entry to my system clipboard.

## Context

General use case is sharing a complete single entry that's stored in KeePassXC. Since there is no built-in password sharing afaik, our team has a way to share single entries when needed. (Note that a central shared password database doesn't fit our use-case for multiple reasons.)

When I need to send credentials to a co-worker we gpg encrypt the contents and then send the encrypted text via a secure channel (double encryption during transit). Currently, I have to copy the username, password, url, notes separately into one encrypted message, then share it. I want a single command to copy everything in the entry to my clipboard. Then I can paste that into a single secure message.

Another use case is when I want to send some credentials to my mobile device. I want to paste the entire contents of an entry into an encrypted secure chat message to myself. 

I needed the credentials for an account on my Roku the other day and the best way to take those credentials to the Roku was on my mobile device. I did not have a convenient way to get all the contents from my KeePassXC entry except to copy it piece by piece. In this case, I the entry had username, password and some notes.

**Comment by droidmonkey** [comment]
For now, recommend using Auto-Type, it'll type the username and password by default. Then if you have notes you can copy those separately.

**Comment by MountainX** [comment]
> For now, recommend using Auto-Type,

Thanks, but that seems to offer very little help. To share an entry I have to copy:

- title
- username
- password
- url
- notes
- TOTP secret key

Autotype allows getting username & password together, but I don't see a way to make it type all the other fields. Therefore, it doesn't make much difference in the amount of effort required.

**Comment by droidmonkey** [comment]
Read the user guide, it can type anything

**Comment by MountainX** [comment]
> it can type anything

Thanks. What's the placeholder for TOTP **secret key**? I don't see that mentioned in the User Guide. I only see:

    {TOTP} | Current TOTP value (if configured)

**Comment by droidmonkey** [comment]
You'll have to use `{S:otp}`
