### ISSUE TITLE
Missing tray icon on KDE

### ISSUE THREAD

**Issue by marcoszy** [keepassxreboot/keepassxc#8188]
## Expected Behavior

A little tray icon be displayed

## Current Behavior

No tray icon

## Steps to Reproduce (for bugs)

I am running KDE on Kubuntu. KeepPassXC is working well, but the tray icon is not displayed. There is a "blank" area where the icon must be. I can click on it, use it, etc. Just the icon itself is not displayed.

## Debug info

KeePassXC - 2.7.1
KeePassXC-Browser - 1.7.12
Operating system: Linux - Kubuntu
Browser: Firefox (non snap)

Thanks in advance for any help.

**Comment by droidmonkey** [comment]
This sounds like a KDE bug, we just tell Qt to display an icon and that's pretty much it. Nothing for us to do here to fix it.

**Comment by michaelk83** [comment]
Might be a path or permission problem?

**Comment by marcoszy** [comment]
Well, I will try to look around for more informations.
