### ISSUE TITLE
Add a synchronization function.

### ISSUE THREAD

**Issue by louib** [keepassxreboot/keepassxc#819]
Currently, the `merge` function tries to match the entries using the UUIDs, and tries to match the groups using the name. My proposition is to split the merge function into a merge and a sync function.

The sync function would, among other things:
* Match and update groups using UUIDs;
* Match and update entries using UUIDs;
* Handle moved groups;
* Handle moved entries;
* Handle deleted objects (groups and entries)

The merge function would:
* Match and update groups using the names (current behaviour);
* Match and update entries using the titles (we currently use the UUIDs, thus the current merge is in part a sync function)

This would solve https://github.com/keepassxreboot/keepassxc/issues/818 and would constitute a starting point for https://github.com/keepassxreboot/keepassxc/issues/90.

Some of the work for the sync is in https://github.com/keepassxreboot/keepassxc/pull/807, but If that sounds good, I'll move the new sync stuff in a new `synchronize` function.

@keepassxreboot/core-developers I'd like your opinion on that feature.

**Comment by thomas-mc-work** [comment]
Maybe with [passman for nextcloud](https://apps.nextcloud.com/apps/passman) as server.
