### ISSUE TITLE
KeePassXC immediately crashes on startup on clean Kubuntu 22.04 install

### ISSUE THREAD

**Issue by Reonu** [keepassxreboot/keepassxc#8193]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
I installed the app from the official repositories via Discover. It immediately crashes on startup. I never get to see the window, I just see the icon in the taskbar for a few seconds.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Install the app via the store on a clean Kubuntu 22.04 install
2. Open the app
3. Crash

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
It
should not crash?

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
it kinda crashes 

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC -2.6.6
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: Kubuntu 22.04
Desktop Env: KDE
Windowing System: X11

**Comment by droidmonkey** [comment]
Upgrade to 2.7.1, recommend flatpak or appimage.
