### ISSUE TITLE
by using the "autotype "options the current linux session is terminated

### ISSUE THREAD

**Issue by 99anton** [keepassxreboot/keepassxc#8195]
## Overview
Since updating of keepassxc version 7.2.1 all "autotype" options of keepassxc don't work anymore.
Every time "autotype" is used the current user session is terminated and the login screen of the operating system appears.

## Steps to Reproduce

1. open the login page of an application
2. select one of the "autotype options" in keepassxc
3. the user session is terminated
4. the login screen appears

## Expected Behavior
user login for the selected application

## Actual Behavior
termination of the linux user session

## Context
In this situation I can only use the "copy user name" and "copy password" options.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.1
Revision: n.a.

[NOTE]: # 
Operating System:Linux opensuse leap 15.4
Desktop Env: KDE
Windowing System: X11

**Comment by droidmonkey** [comment]
Duplicate report. Unfortunately there is a bug in X11 that is being triggered by our Auto-Type implementation. Reverting the implementation changes will reduce functionality and we are still trying to figure out what we can do to avoid triggering the bug.
