### ISSUE TITLE
Keepassxc not working with Brave browser

### ISSUE THREAD

**Issue by Harpper** [keepassxreboot/keepassxc#8196]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
Keepassxc does not enter logins or passwords on the last two versions of Brave browser

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Login to Keepassxc
2. Go to login page for web page in Brave 1.40.107
3. keepassxc icons next to login are greyed out or absent

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Expect keepassxc icons to be green and enter login info

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
well nothing happens
.....message appears  Error  not connected to keepassxc

## Context
[NOTE]: # ( Give us any additional information you may have. )
Only happens in Brave when using Firefox 101.0.1 it works fine.
Browser integration for Brave is enabled in keepassxc and extension for keepassxc is enabled

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.1
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux Mint
Desktop Env: Cinnamon
Windowing System: X11

**Comment by janechicken** [comment]
RTFM

**Comment by droidmonkey** [comment]
Please check out our user guide and then our browser troubleshooting guide.

**Comment by Harpper** [comment]
I read the FM and I am still not getting anywhere. I have used Keepassxc on Brave for over a year it only stopped working in the last two weeks without any settings being changed

Sorry missed step on using reload button..fixed
