### ISSUE TITLE
KeepassXC sometimes hides the "Remember" option

### ISSUE THREAD

**Issue by piramiday** [keepassxreboot/keepassxc#8199]
## Overview
For at least a website that I routinely use, the KeepassXC window pops up every single time asking for authorization and does not let me see/check the "Remember" option like I did for countless other entries.

## Steps to Reproduce
This happens for a specific site in my entries, for some reason.
I tried with a new entry and it does show the "Remember" option correctly.

... any suggestion?

## Expected Behavior

![2](https://user-images.githubusercontent.com/48775554/175996827-9231ce50-8eac-459f-855d-1454ba07abb9.png)

## Actual Behavior
![1](https://user-images.githubusercontent.com/48775554/175996807-ba618821-0868-46c3-9e48-e09dc3d7dfc8.png)

## Context
The user/pass combo in this instance is for HTTP auth.
Still, another entry in my database behaves exactly the same, yet it does remember my "Allow" choice.

## Debug info
```
KeePassXC - Version 2.7.1
Revision: 5916a8f

Qt 5.12.8
Debugging mode is disabled.
```

**Comment by droidmonkey** [comment]
We hide that button if the site is using http auth. This is because that is handled differently from form fill.

m_ui->rememberDecisionCheckBox->setVisible(!httpAuth);

**Comment by piramiday** [comment]
does it have to be like this? I don't see any reason for HTTP auth to be overzealous, at least from an end-user's perspective.

also, as I mentioned another site is nearly identical to the one having this issue, and the former works like a charm.

**Comment by droidmonkey** [comment]
@varjolintu can you expand on this?

**Comment by piramiday** [comment]
as a further step, since I luckily control the website in question, I have modified one webpage to temporarily host a mockup of an HTML login form with the sole purpose of tricking KeepassXC into showing me the "Remember" option.
the trick worked -- I was able to check "Remember" and make KeepassXC store my setting, having now a new `Property` for the entry in question:
```
KeePassXC-Browser Settings = {"Allow": ["www.whatever.com"], "Deny": [], "Realm": []}
```
which of course was not there before.
this website is now showing **exactly the same properties and settings** as another one of my websites.
still, while I never see the HTTP basic auth dialog for my other website, this one keeps showing me the same "allow selected" dialog.
**any suggestion on how to achieve the same behavior?**

of course my original question still stands, that is, I believe this to be a bug that made me bang my head against the wall for quite some time.
thanks for the help and any explanations you might want to throw my way!

**Comment by varjolintu** [comment]
IIRC the reason why HTTP Auth hides the remember option is because with a single entry that is remembered, it's impossible to show the default auth dialog, and the credentials are always entered automatically. So there's a possibility to discard the KeePassXC's credentials for the site and use the default login dialog instead. So it's just an extra confirmation where you can still revert the credential fill.
Of course this doesn't happen with multiple HTTP Auth credentials. There you have an option behind the extension popup to show the default login dialog. This could be improved in a way that HTTP Auth credentials are remembered, but even single one's are not filled without user interaction with the popup. But I'm not sure if that behaviour is something users want.

**Comment by piramiday** [comment]
I understand that, as it is, the autocompletion of an http auth dialog is very stealthy to the user.
still, couldn't you communicate this somehow? maybe changing the KeepassXC-Browser icon in the toolbar with some color?

it makes sense to me that if I have a single website with a single entry in my database, then KeepassXC fills that up without asking.

with respect to my other message: https://github.com/keepassxreboot/keepassxc/issues/8199#issuecomment-1168826863
any suggestion? thank you.
