### ISSUE TITLE
Start minimized & unlock last used database on autotype

### ISSUE THREAD

**Issue by PhoenixIV** [keepassxreboot/keepassxc#8200]
I am using Windows 10

I am basically looking for https://github.com/keepassxreboot/keepassxc/issues/10 , just with the addition that it should also offer me to unlock my database when it has not been opened before.

1. Start windows
2. KeePassXC is starting silently in the background
3. Open Website / Application with login screen
4. Press global autotype hotkey
5. Prompt to unlock database from last session

**Comment by droidmonkey** [comment]
That is not a feature we will support. You need to have the database file at least "loaded up" ready to unlock.

**Comment by PhoenixIV** [comment]
That's what I want. To load it up. But locked.

I do not see why you would want the app to be able to start minimized but then nothing happens when you use the global autotype trigger. Why start it minimized in the first place, then?

**Comment by droidmonkey** [comment]
That is not a default setting, so that's technically not what "we" want, but is an option for the end user. You can choose to remember last used (what is loaded on last close) databases, in which case they will be already loaded up ready to unlock when you start keepassxc.

**Comment by PhoenixIV** [comment]
These are my settings:
- Start with system
- Start minimized
- Remember last used database
- Open last used database on start

This is my result:
- App starts minimized
- Upon opening I have to choose which database to load

Expected result:
- Last used database is loaded, but locked

**Comment by PhoenixIV** [comment]
Update: The behaviour I just described seems to be a fluke. Now it works just as I expected. 🤨
