### ISSUE TITLE
MS authenticator

### ISSUE THREAD

**Issue by janechicken** [keepassxreboot/keepassxc#8201]
## Summary
I want to add TOTP to my MS account but they use their own system instead of TOTP, is there a way to use MS auth on keepassxc

## Examples
If you were to scan the QR code Microsoft gives with zbar tools, it does not show any TOTP code only a link for MS authenticator

**Comment by droidmonkey** [comment]
Not possible, it is proprietary

**Comment by tilt-me** [comment]
Just yesterday I added a MFA to my Microsoft account via KeePassXC, following this guide:
https://blogs.it.ox.ac.uk/nexus/2022/06/24/keepassmfa/

**Comment by droidmonkey** [comment]
When you click "I want to use a different authenticator app" you are no longer using Microsoft authenticator.

**Comment by tilt-me** [comment]
Ok, but @ThatOneOcto was asking to add TOTP to their MS account, and Microsoft was showing only its (proprietary) Authenticator option.
MFA is becoming mandatory for Microsoft, but if you don't take action, when you login Microsoft will only show its Authenticator App option to fulfill the MFA requirement.
Only if you visit https://mysignins.microsoft.com/security-info you will find other auth options (‘I want to use a different authenticator app’), with a standard TOTP implementation (usable on KeepassXC and friends).

**Comment by janechicken** [comment]
@tilt-me thank you for informing me of this

**Comment by droidmonkey** [comment]
Sorry I read MFA as Microsoft Authenticator instead of Multi Factor Authentication. Got Microsoft on the brain I guess...

**Comment by JohnLGalt** [comment]
> Sorry I read MFA as Microsoft Authenticator instead of Multi Factor Authentication. Got Microsoft on the brain I guess...

Don't feel badly about this, in reading this thread just now, I did the **same** - and I have all my Microsoft accounts protected via TOTP in KPXC _**already**_ (along with the M$ Authenticator and physical keys, but I've had the TOTPs in KPXC since I started using KPXC over original KeePass some 2+ years ago).

**Comment by RoestVrijStaal** [comment]
For the other confused souls like me who ended up here with their favorite internet search machine: 

Apparently Microsoft does some A/B-testing, as in first demanding to setup and use the MS Authenticator bloat with their own proprietary 2FA-method, before you could setup and use the standarized (RFC62338) TOTP method described earlier by @tilt-me for KeePassXC 

You could unbloat your phone after setting up standarized TOTP in KeePassXC. 

But if you're lucky, you get the 'I want to use a different authenticator app' in the very beginning.
