### ISSUE TITLE
[MSVC] KeePassXC failed to Setup with CMake Errors

### ISSUE THREAD

**Issue by Apriltanq** [keepassxreboot/keepassxc#8203]
Hi, all
KeePassXC failed to Setup with CMake errors on MSVC. Could you help look?
 **Steps to Reproduce**
1. Open a VS x64 command
2. git clone https://github.com/Microsoft/vcpkg F:\gitP\Microsoft\vcpkg
3. cd F:\gitP\Microsoft\vcpkg
4. bootstrap-vcpkg.bat 2>&1
5. vcpkg.exe install --recurse botan zlib minizip libqrencode readline --triplet x64-windows --clean-after-build 2>&1
6. git clone https://github.com/keepassxreboot/keepassxc F:\gitP\keepassxreboot\keepassxc
7. cd F:\gitP\keepassxreboot\keepassxc
8. mkdir build_amd64
9. cd build_amd64
10. set PATH=F:\tools\qt5\qt\5_15_2\msvc2019_64\bin;%PATH%
11. gem install asciidoctor 2>&1
12. cmake -G "Visual Studio 16 2019" -A x64 -DCMAKE_SYSTEM_VERSION=10.0.22000.0 -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=F:\gitP\Microsoft\vcpkg\scripts\buildsystems\vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows .. 2>&1

**Error log**
[configure.log](https://github.com/keepassxreboot/keepassxc/files/8998221/configure.log)

**Expected Behavior**
It should work fine.

 **Actual Behavior**
ARGON2_LIBRARIES
    linked by target "keepassx_core" in directory F:/gitP/keepassxreboot/keepassxc/src

CMake Error in src/CMakeLists.txt:
  Found relative path while evaluating include directories of "zxcvbn":

    "ARGON2_INCLUDE_DIR-NOTFOUND"

CMake Error in src/CMakeLists.txt:
  Found relative path while evaluating include directories of "zxcvbn":

    "ARGON2_INCLUDE_DIR-NOTFOUND"

CMake Error in src/CMakeLists.txt:
  Found relative path while evaluating include directories of "zxcvbn":

    "ARGON2_INCLUDE_DIR-NOTFOUND"

CMake Error in src/CMakeLists.txt:
  Found relative path while evaluating include directories of "zxcvbn":

    "ARGON2_INCLUDE_DIR-NOTFOUND"

CMake Error in src/CMakeLists.txt:
  Found relative path while evaluating include directories of "zxcvbn":

    "ARGON2_INCLUDE_DIR-NOTFOUND"

CMake Error in src/CMakeLists.txt:
  Found relative path while evaluating include directories of "autotype":

    "ARGON2_INCLUDE_DIR-NOTFOUND"

CMake Error in src/CMakeLists.txt:
  Found relative path while evaluating include directories of "autotype":

    "ARGON2_INCLUDE_DIR-NOTFOUND"

CMake Error in src/CMakeLists.txt:
  Found relative path while evaluating include directories of "autotype":

    "ARGON2_INCLUDE_DIR-NOTFOUND"

CMake Error in src/CMakeLists.txt:
  Found relative path while evaluating include directories of "autotype":

    "ARGON2_INCLUDE_DIR-NOTFOUND"

CMake Error in src/CMakeLists.txt:
  Found relative path while evaluating include directories of "autotype":

    "ARGON2_INCLUDE_DIR-NOTFOUND"

CMake Error in src/CMakeLists.txt:
  Found relative path while evaluating include directories of
  "keepassx_core":

    "ARGON2_INCLUDE_DIR-NOTFOUND"

CMake Error in src/CMakeLists.txt:
  Found relative path while evaluating include directories of
  "keepassx_core":

    "ARGON2_INCLUDE_DIR-NOTFOUND"

CMake Error in src/CMakeLists.txt:
  Found relative path while evaluating include directories of
  "keepassx_core":

    "ARGON2_INCLUDE_DIR-NOTFOUND"

CMake Error in src/CMakeLists.txt:
  Found relative path while evaluating include directories of
  "keepassx_core":

    "ARGON2_INCLUDE_DIR-NOTFOUND"

CMake Error in src/CMakeLists.txt:
  Found relative path while evaluating include directories of
  "keepassx_core":

    "ARGON2_INCLUDE_DIR-NOTFOUND"

CMake Error in src/CMakeLists.txt:
  Found relative path while evaluating include directories of "KeePassXC":

    "ARGON2_INCLUDE_DIR-NOTFOUND"

CMake Error in src/CMakeLists.txt:
  Found relative path while evaluating include directories of "KeePassXC":

    "ARGON2_INCLUDE_DIR-NOTFOUND"

CMake Error in src/CMakeLists.txt:
  Found relative path while evaluating include directories of "KeePassXC":

    "ARGON2_INCLUDE_DIR-NOTFOUND"

CMake Error in src/CMakeLists.txt:
  Found relative path while evaluating include directories of "KeePassXC":

    "ARGON2_INCLUDE_DIR-NOTFOUND"

CMake Error in src/CMakeLists.txt:
  Found relative path while evaluating include directories of "KeePassXC":

    "ARGON2_INCLUDE_DIR-NOTFOUND"

CMake Error in src/autotype/windows/CMakeLists.txt:
  Found relative path while evaluating include directories of
  "keepassxc-autotype-windows":

    "ARGON2_INCLUDE_DIR-NOTFOUND"

CMake Error in src/autotype/windows/CMakeLists.txt:
  Found relative path while evaluating include directories of
  "keepassxc-autotype-windows":

    "ARGON2_INCLUDE_DIR-NOTFOUND"

CMake Error in src/autotype/windows/CMakeLists.txt:
  Found relative path while evaluating include directories of
  "keepassxc-autotype-windows":

    "ARGON2_INCLUDE_DIR-NOTFOUND"

CMake Error in src/autotype/windows/CMakeLists.txt:
  Found relative path while evaluating include directories of
  "keepassxc-autotype-windows":

    "ARGON2_INCLUDE_DIR-NOTFOUND"

CMake Error in src/autotype/windows/CMakeLists.txt:
  Found relative path while evaluating include directories of
  "keepassxc-autotype-windows":

    "ARGON2_INCLUDE_DIR-NOTFOUND"

CMake Error in src/autotype/test/CMakeLists.txt:
  Found relative path while evaluating include directories of
  "keepassxc-autotype-test":

    "ARGON2_INCLUDE_DIR-NOTFOUND"

CMake Error in src/autotype/test/CMakeLists.txt:
  Found relative path while evaluating include directories of
  "keepassxc-autotype-test":

    "ARGON2_INCLUDE_DIR-NOTFOUND"

CMake Error in src/autotype/test/CMakeLists.txt:
  Found relative path while evaluating include directories of
  "keepassxc-autotype-test":

    "ARGON2_INCLUDE_DIR-NOTFOUND"

CMake Error in src/autotype/test/CMakeLists.txt:
  Found relative path while evaluating include directories of
  "keepassxc-autotype-test":

    "ARGON2_INCLUDE_DIR-NOTFOUND"

CMake Error in src/autotype/test/CMakeLists.txt:
  Found relative path while evaluating include directories of
  "keepassxc-autotype-test":

    "ARGON2_INCLUDE_DIR-NOTFOUND"

CMake Error in src/cli/CMakeLists.txt:
  Found relative path while evaluating include directories of "cli":

    "ARGON2_INCLUDE_DIR-NOTFOUND"

CMake Error in src/cli/CMakeLists.txt:
  Found relative path while evaluating include directories of "cli":

    "ARGON2_INCLUDE_DIR-NOTFOUND"

CMake Error in src/cli/CMakeLists.txt:
  Found relative path while evaluating include directories of "cli":

    "ARGON2_INCLUDE_DIR-NOTFOUND"

CMake Error in src/cli/CMakeLists.txt:
  Found relative path while evaluating include directories of "cli":

    "ARGON2_INCLUDE_DIR-NOTFOUND"

CMake Error in src/cli/CMakeLists.txt:
  Found relative path while evaluating include directories of "cli":

    "ARGON2_INCLUDE_DIR-NOTFOUND"

CMake Error in src/cli/CMakeLists.txt:
  Found relative path while evaluating include directories of
  "keepassxc-cli":

    "ARGON2_INCLUDE_DIR-NOTFOUND"

CMake Error in src/cli/CMakeLists.txt:
  Found relative path while evaluating include directories of
  "keepassxc-cli":

    "ARGON2_INCLUDE_DIR-NOTFOUND"

CMake Error in src/cli/CMakeLists.txt:
  Found relative path while evaluating include directories of
  "keepassxc-cli":

    "ARGON2_INCLUDE_DIR-NOTFOUND"

CMake Error in src/cli/CMakeLists.txt:
  Found relative path while evaluating include directories of
  "keepassxc-cli":

    "ARGON2_INCLUDE_DIR-NOTFOUND"

CMake Error in src/cli/CMakeLists.txt:
  Found relative path while evaluating include directories of
  "keepassxc-cli":

    "ARGON2_INCLUDE_DIR-NOTFOUND"

CMake Error in src/qrcode/CMakeLists.txt:
  Found relative path while evaluating include directories of "qrcode":

    "ARGON2_INCLUDE_DIR-NOTFOUND"

CMake Error in src/qrcode/CMakeLists.txt:
  Found relative path while evaluating include directories of "qrcode":

    "ARGON2_INCLUDE_DIR-NOTFOUND"

CMake Error in src/qrcode/CMakeLists.txt:
  Found relative path while evaluating include directories of "qrcode":

    "ARGON2_INCLUDE_DIR-NOTFOUND"

CMake Error in src/qrcode/CMakeLists.txt:
  Found relative path while evaluating include directories of "qrcode":

    "ARGON2_INCLUDE_DIR-NOTFOUND"

CMake Error in src/qrcode/CMakeLists.txt:
  Found relative path while evaluating include directories of "qrcode":

    "ARGON2_INCLUDE_DIR-NOTFOUND"

CMake Error in tests/CMakeLists.txt:
  Found relative path while evaluating include directories of "testsupport":

    "ARGON2_INCLUDE_DIR-NOTFOUND"

CMake Error in tests/CMakeLists.txt:
  Found relative path while evaluating include directories of "testsupport":

    "ARGON2_INCLUDE_DIR-NOTFOUND"

CMake Error in tests/CMakeLists.txt:
  Found relative path while evaluating include directories of "testsupport":

    "ARGON2_INCLUDE_DIR-NOTFOUND"

CMake Error in tests/CMakeLists.txt:
  Found relative path while evaluating include directories of "testsupport":

    "ARGON2_INCLUDE_DIR-NOTFOUND"

CMake Error in tests/CMakeLists.txt:
  Found relative path while evaluating include directories of "testsupport":

    "ARGON2_INCLUDE_DIR-NOTFOUND"

CMake Error in tests/CMakeLists.txt:
  Found relative path while evaluating include directories of "testgroup":

    "ARGON2_INCLUDE_DIR-NOTFOUND"

CMake Error in tests/CMakeLists.txt:
  Found relative path while evaluating include directories of "testgroup":

    "ARGON2_INCLUDE_DIR-NOTFOUND"

CMake Error in tests/CMakeLists.txt:
  Found relative path while evaluating include directories of "testgroup":

    "ARGON2_INCLUDE_DIR-NOTFOUND"

CMake Error in tests/CMakeLists.txt:
  Found relative path while evaluating include directories of "testgroup":

    "ARGON2_INCLUDE_DIR-NOTFOUND"

CMake Error in tests/CMakeLists.txt:
  Found relative path while evaluating include directories of "testgroup":

    "ARGON2_INCLUDE_DIR-NOTFOUND"

CMake Error in tests/CMakeLists.txt:
  Found relative path while evaluating include directories of "testkdbx2":

    "ARGON2_INCLUDE_DIR-NOTFOUND"

CMake Error in tests/CMakeLists.txt:
  Found relative path while evaluating include directories of "testkdbx2":

    "ARGON2_INCLUDE_DIR-NOTFOUND"

CMake Error in tests/CMakeLists.txt:
  Found relative path while evaluating include directories of "testkdbx2":

    "ARGON2_INCLUDE_DIR-NOTFOUND"

CMake Error in tests/CMakeLists.txt:
  Found relative path while evaluating include directories of "testkdbx2":

    "ARGON2_INCLUDE_DIR-NOTFOUND"

CMake Error in tests/CMakeLists.txt:
  Found relative path while evaluating include directories of "testkdbx2":

    "ARGON2_INCLUDE_DIR-NOTFOUND"

CMake Error in tests/CMakeLists.txt:
  Found relative path while evaluating include directories of "testkdbx3":

    "ARGON2_INCLUDE_DIR-NOTFOUND"

CMake Error in tests/CMakeLists.txt:
  Found relative path while evaluating include directories of "testkdbx3":

    "ARGON2_INCLUDE_DIR-NOTFOUND"

CMake Error in tests/CMakeLists.txt:
  Found relative path while evaluating include directories of "testkdbx3":

    "ARGON2_INCLUDE_DIR-NOTFOUND"

CMake Error in tests/CMakeLists.txt:
  Found relative path while evaluating include directories of "testkdbx3":

    "ARGON2_INCLUDE_DIR-NOTFOUND"

CMake Error in tests/CMakeLists.txt:
  Found relative path while evaluating include directories of "testkdbx3":

    "ARGON2_INCLUDE_DIR-NOTFOUND"

CMake Error in tests/CMakeLists.txt:
  Found relative path while evaluating include directories of "testkdbx4":

    "ARGON2_INCLUDE_DIR-NOTFOUND"

CMake Error in tests/CMakeLists.txt:
  Found relative path while evaluating include directories of "testkdbx4":

    "ARGON2_INCLUDE_DIR-NOTFOUND"

CMake Error in tests/CMakeLists.txt:
  Found relative path while evaluating include directories of "testkdbx4":

    "ARGON2_INCLUDE_DIR-NOTFOUND"

CMake Error in tests/CMakeLists.txt:
  Found relative path while evaluating include directories of "testkdbx4":

    "ARGON2_INCLUDE_DIR-NOTFOUND"

CMake Error in tests/CMakeLists.txt:
  Found relative path while evaluating include directories of "testkdbx4":

    "ARGON2_INCLUDE_DIR-NOTFOUND"

CMake Error in tests/CMakeLists.txt:
  Found relative path while evaluating include directories of "testkeys":

    "ARGON2_INCLUDE_DIR-NOTFOUND"

CMake Error in tests/CMakeLists.txt:
  Found relative path while evaluating include directories of "testkeys":

    "ARGON2_INCLUDE_DIR-NOTFOUND"

CMake Error in tests/CMakeLists.txt:
  Found relative path while evaluating include directories of "testkeys":

    "ARGON2_INCLUDE_DIR-NOTFOUND"

CMake Error in tests/CMakeLists.txt:
  Found relative path while evaluating include directories of "testkeys":

    "ARGON2_INCLUDE_DIR-NOTFOUND"

CMake Error in tests/CMakeLists.txt:
  Found relative path while evaluating include directories of "testkeys":

    "ARGON2_INCLUDE_DIR-NOTFOUND"

CMake Error in tests/CMakeLists.txt:
  Found relative path while evaluating include directories of
  "testgroupmodel":

    "ARGON2_INCLUDE_DIR-NOTFOUND"

CMake Error in tests/CMakeLists.txt:
  Found relative path while evaluating include directories of
  "testgroupmodel":

    "ARGON2_INCLUDE_DIR-NOTFOUND"

CMake Error in tests/CMakeLists.txt:
  Found relative path while evaluating include directories of
  "testgroupmodel":

    "ARGON2_INCLUDE_DIR-NOTFOUND"

CMake Error in tests/CMakeLists.txt:
  Found relative path while evaluating include directories of
  "testgroupmodel":

    "ARGON2_INCLUDE_DIR-NOTFOUND"

CMake Error in tests/CMakeLists.txt:
  Found relative path while evaluating include directories of
  "testgroupmodel":

    "ARGON2_INCLUDE_DIR-NOTFOUND"

CMake Error in tests/CMakeLists.txt:
  Found relative path while evaluating include directories of
  "testentrymodel":

    "ARGON2_INCLUDE_DIR-NOTFOUND"

CMake Error in tests/CMakeLists.txt:
  Found relative path while evaluating include directories of
  "testentrymodel":

    "ARGON2_INCLUDE_DIR-NOTFOUND"

CMake Error in tests/CMakeLists.txt:
  Found relative path while evaluating include directories of
  "testentrymodel":

    "ARGON2_INCLUDE_DIR-NOTFOUND"

CMake Error in tests/CMakeLists.txt:
  Found relative path while evaluating include directories of
  "testentrymodel":

    "ARGON2_INCLUDE_DIR-NOTFOUND"

CMake Error in tests/CMakeLists.txt:
  Found relative path while evaluating include directories of
  "testentrymodel":

    "ARGON2_INCLUDE_DIR-NOTFOUND"

CMake Error in tests/CMakeLists.txt:
  Found relative path while evaluating include directories of
  "testcryptohash":

    "ARGON2_INCLUDE_DIR-NOTFOUND"

CMake Error in tests/CMakeLists.txt:
  Found relative path while evaluating include directories of
  "testcryptohash":

    "ARGON2_INCLUDE_DIR-NOTFOUND"

CMake Error in tests/CMakeLists.txt:
  Found relative path while evaluating include directories of
  "testcryptohash":

    "ARGON2_INCLUDE_DIR-NOTFOUND"

CMake Error in tests/CMakeLists.txt:
  Found relative path while evaluating include directories of
  "testcryptohash":

    "ARGON2_INCLUDE_DIR-NOTFOUND"

CMake Error in tests/CMakeLists.txt:
  Found relative path while evaluating include directories of
  "testcryptohash":

    "ARGON2_INCLUDE_DIR-NOTFOUND"

CMake Error in tests/CMakeLists.txt:
  Found relative path while evaluating include directories of
  "testsymmetriccipher":

    "ARGON2_INCLUDE_DIR-NOTFOUND"

CMake Error in tests/CMakeLists.txt:
  Found relative path while evaluating include directories of
  "testsymmetriccipher":

    "ARGON2_INCLUDE_DIR-NOTFOUND"

CMake Error in tests/CMakeLists.txt:
  Found relative path while evaluating include directories of
  "testsymmetriccipher":

    "ARGON2_INCLUDE_DIR-NOTFOUND"

CMake Error in tests/CMakeLists.txt:
  Found relative path while evaluating include directories of
  "testsymmetriccipher":

    "ARGON2_INCLUDE_DIR-NOTFOUND"

CMake Error in tests/CMakeLists.txt:
  Found relative path while evaluating include directories of
  "testsymmetriccipher":

    "ARGON2_INCLUDE_DIR-NOTFOUND"

CMake Error in tests/CMakeLists.txt:
  Found relative path while evaluating include directories of
  "testhashedblockstream":

    "ARGON2_INCLUDE_DIR-NOTFOUND"

CMake Error in tests/CMakeLists.txt:
  Found relative path while evaluating include directories of
  "testhashedblockstream":

    "ARGON2_INCLUDE_DIR-NOTFOUND"

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 861fe2e5a9ec1025f89591b14017fc3880fb3733

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows Server 2019
Windows version: 1809
OS build: 17763.2686

**Comment by phoerious** [comment]
Please follow our build set up guide: https://github.com/keepassxreboot/keepassxc/wiki/Set-up-Build-Environment-on-Windows

**Comment by Apriltanq** [comment]
Got it, I have followed the step to set up, it worked fine, thanks.
