### ISSUE TITLE
Clipboard not cleared if you right click and copy the password in the "General" tab.

### ISSUE THREAD

**Issue by hamishmb** [keepassxreboot/keepassxc#8207]
## Overview
The clipboard is not cleared if you right click and copy the password in the "General" tab.

## Steps to Reproduce
1. Create and save a password.
2. Copy it by right clicking the password in the "General" tab.
3. Observe that the clipboard is never cleared.

## Expected Behavior
Clipboard is cleared after a short delay like when other ways of copying the password are used.

## Actual Behavior
Clipboard is not cleared.

## Context
OS: Linux Mint 20.3 Cinnamon.
Using Flatpak package.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows/Linux/macOS
Desktop Env: Gnome/KDE/XFCE/Mate/Cinnamon
Windowing System: X11/Wayland

**Comment by droidmonkey** [comment]
That method is not capturable since it is handled by the OS. If you want clipboard clearing use the toolbar buttons or keyboard shortcuts when on the main window view.
