### ISSUE TITLE
KeePassXC-Browser 1.8.0 (Addon for Firefox): No more detection of KeePassXC running after starting KeePassXC

### ISSUE THREAD

**Issue by dark-rider** [keepassxreboot/keepassxc#8208]
Hello,

for some days, most probably since build 1.8.0 of the browser addon for Firefox (current build 101.0.1, current Windows 10), the addon does no more automatically detect KeePassXC to be running after you start KeePassXC when the login page is already opened within Firefox, but shows an error message (in German: "Die Nachrichtenverschlüsselung ist fehlgeschlagen. Läuft KeePassXC?").

You now have to manually use the button "reload" underneath the error message within the addon to connect the addon to KeePassXC, and then reload the website to login via KeePassXC and addon.

Could this be corrected?

**Comment by Harpper** [comment]
work around. I disabled extension and reenabled then refreshed web page. I was shut down when I reported same problem with Brave bbrowser

**Comment by droidmonkey** [comment]
You need to refresh the connection if it is not established. There is no other workaround at this time. There is a request for auto connection, but has not been successfully implemented yet. Also, please report extension issue over on the keepassxc-browser issue tracker.

**Comment by dark-rider** [comment]
I would not have reported if it hadn't worked before build 1.8.0.

"Also, please report extension issue over on the keepassxc-browser issue tracker."
-> OK, I will do so in the future. But where to find? Is this the correct place:
https://github.com/keepassxreboot/keepassxc-browser/issues (What is keepassxreboot)?

**Comment by droidmonkey** [comment]
Yes that is the correct place
