### ISSUE TITLE
Some favicon fails to download: select2: Function not implemented

### ISSUE THREAD

**Issue by lerignoux** [keepassxreboot/keepassxc#8209]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

when downloading some favicon, the request fails and favicon is not downloaded.
I could not find a given rule.

It fails for instance on me for url https://gensdeconfiance.com

## Steps to Reproduce
1. add an entry with url https://gensdeconfiance.com
2. right click on entry
3. download favicon
4. download should fail with the following log line:
```
Sandbox: seccomp sandbox violation: pid 16267, tid 16286, syscall 270, args 14 140600783833360 0 0 0 0.
select2: Function not implemented
```

## Expected Behavior
Favicon should be properly downloaded

## Actual Behavior
download fails and icon is not set

## Context
I am running it from China (with a proxy), there may be network interference

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.1
Revision: 5916a8f

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: Cinnamon
Windowing System: X11

I would be happy to try to debug and try to provide a fix if someone has an hint where this could be coming from

**Comment by droidmonkey** [comment]
This isn't on us, you must be running keepassxc in a sandbox or firejail environment. This isn't an error message we would provide.
