### ISSUE TITLE
Can not save the attachment (when using snap)

### ISSUE THREAD

**Issue by hojjatabdollahi** [keepassxreboot/keepassxc#8210]
## Overview
I can successfully add an attachment to an entry but I can not save (or open) it afterwards. 
When I press the save button, the "open file dialog" pops up instead of "open directory dialog". 
Therefore I can not choose a directory to save the file into.
I use the snap version and I guess it's an issue with Snap or Qt or xdgportal (or maybe Ubuntu 20.04 doesn't have the latest of something).
I am reporting it here maybe you guys know how to fix this. 
Thanks.

## Steps to Reproduce
1- Create a new db.
2- Create a new entry.
3- Go to advanced tab and add an attachment.
4- try to save that attachment to a directory.

## Expected Behavior
Show "choose **directory** dialog box"

## Actual Behavior
Shows "choose **file** dialog box".

## Context
I'm using this as a snap package and it could be an issue with Snap and Qt.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.1
Revision: 5916a8f
Distribution: Snap

[NOTE]: # ( Pick choices based on your environment )
Operating System: Ubuntu Core 20
Desktop Env: Gnome
Windowing System: X11

**Comment by droidmonkey** [comment]
We definitely request for a directory: https://github.com/keepassxreboot/keepassxc/blob/develop/src/gui/entry/EntryAttachmentsWidget.cpp#L213

This appears to be an xdg portal issue on the surface. We do recommend using our flatpak or appimage over snap.

**Comment by hojjatabdollahi** [comment]
That's correct. The .appimage version works perfectly. I did some more research and it looks like QFileDialog and certain Qt versions and some certain Snap don't work together. 
https://forum.snapcraft.io/t/qt-file-dialog-open-folder-and-kde-neon-extension/20876
https://forum.snapcraft.io/t/wrong-file-path-of-opened-files-in-snap-apps/22982/6

**Comment by droidmonkey** [comment]
Closing this as it is not something we can control. We are already using the core20 version of the kde-neon extension. 

> Since “Portal support depends on the version of xdg-desktop-portal in the host system” (https://snapcraft.io/docs/xdg-desktop-portals 2) and Ubuntu does not update the xdg-desktop-portal package (https://answers.launchpad.net/ubuntu/+source/xdg-desktop-portal/+question/696656 1) this works only correctly on ubuntu 20.10 and newer.

Fwiw, this highlights the significant disadvantage of using Debian, Ubuntu, and Mint. You are stuck in the past along with its bugs.
