### ISSUE TITLE
Just wanted to confirm whether below features available or not with MAC operating system.

### ISSUE THREAD

**Issue by savidudu** [keepassxreboot/keepassxc#8211]
Flexible Database Management (If yes) How exactly it will work, I am not seeing much information for MAC
Encrypted Database  (If yes) How exactly it will work, I am not seeing much information for MAC
TOTP option for 2-factor authentication (If yes) How exactly it will work, I am not seeing much information for MAC
Supports static keys (Yubikey,Onlykey etc) I believe this is supported with MAC
Password Generator & Passphrase Generator I believe this is supported with MAC
Browser Integration 
OpenSSH Integration
Screenshot Security
Quick Unlock
Exporting Database in MAC and Linux

If any other feature is important and not listed then please highlight.
If this is not the right place , Please help me with the correct forum.

**Comment by michaelk83** [comment]
Most of the features are cross-platform. AFAIK, all of this should work on macOS. I'm not sure what you mean by "Flexible Database Management".

Please refer to the user guide: https://keepassxc.org/docs/KeePassXC_UserGuide.html

**Comment by savidudu** [comment]
Flexible Database Management- I mean creating and modifying database, Database backups and restore
importing databases.

Is there any Architecture Diagram or something similar is available ?

Thanks

**Comment by michaelk83** [comment]
Yes, that should all work. No architecture diagram that I'm aware of. Most of the features are platform-agnostic. There are a few exceptions where the platform limitations prevent it, or require a platform-specific implementation. (For example, Quick Unlock is not implemented on Linux yet.)

**Comment by phoerious** [comment]
All features are supported on all platforms unless stated otherwise.

**Comment by savidudu** [comment]
Can the deployment be centralized or automated from workspace 1 ?

Also, Please help me to know whether any Ports are associated or not ?

Is there any Telemetry Data Collected, Will any Sensitive and Personal Information will collected by the application ?

Thanks

**Comment by phoerious** [comment]
We offer no deployment options, that's up to the administrator, but central deployment is not a problem. KeePassXC is not a server that needs ports and we don't collect any data. See https://keepassxc.org/privacy/
