### ISSUE TITLE
Upgrade security level to access bank credentials

### ISSUE THREAD

**Issue by KIMWW** [keepassxreboot/keepassxc#8215]
## Summary
Would it be possible to create a second level of check to access specific entries like for those of bank credentials?
Or just to retype the master password to have access to such sensitive data.

**Comment by phoerious** [comment]
There is no way to achieve that other than encrypting the values with yet another key, but I don't really see the value of that. Better create a separate database if you don't want to have those in your main database.

**Comment by droidmonkey** [comment]
Yes, best option if you are concerned is to make a different database for those credentials. We won't be implementing a secondary unlock feature because that greatly complicates all of our other features (have to wait for unlock to proceed).
