### ISSUE TITLE
Windows 11 UAC not opening.

### ISSUE THREAD

**Issue by redtrillix** [keepassxreboot/keepassxc#8219]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Open KeePassXC
2. Use quick-unlock to open database.
3. UAC hangs and doesn't open until you close or restart KeePassXC.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
KeePass is suppose to unlock after using quick-unlock.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
UAC hangs and doesn't open until you close or restart KeePassXC.

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.1
Revision: 5916a8f

Qt 5.15.3
Debugging mode is disabled.

Operating system: Windows 10 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.25140

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 2.18.1

[NOTE]: # ( Pick choices based on your environment )
Edition:	Windows 11 Pro Insider Preview
Version:	22H2
Installed on:	‎21/‎06/‎2022
OS build:	25140.1000
Experience:	Windows Feature Experience Pack 1000.25140.1000.0

**Comment by droidmonkey** [comment]
Does the UAC prompt open at all? If so then this is #8120.

**Comment by redtrillix** [comment]
Yes sorry, I tried searching for the issue but had no results. 

Thank you very much.
