### ISSUE TITLE
Data loss on Cloud sync

### ISSUE THREAD

**Issue by jeroen7s** [keepassxreboot/keepassxc#822]
i've had 2 computers both with edited/added entries, which were not synced up yet, causing a conflict and loss of data, 
which is why you shouldn't let external programs handle syncing encrypted files that change
## Expected Behavior
the 2 changed databases should merge, but merging is impossible because Cloud Service handles syncing

## Current Behavior
last edited vault will be used, all changes in other vault are lost

## Possible Solution
Implementing sync functionality in Keepass

## Steps to Reproduce (for bugs) 
1. Have 2 Devices, devA and devB
2. have them sync a vault using cloud service
3. disconnect them from the internet
4. add entries on devA
5. add other entries on devB
6. reconnect to internet and let them sync
7. vaultB will be used, changes in vaultA will be dropped as the last change was on vaultB

## Context
got this issue when i disabled dropbox autolaunching on 1 of my PC's, and made changes to it before it was synced up, which caused the issue

**Comment by droidmonkey** [comment]
I am not sure how this is a bug against keepassxc.

**Comment by jeroen7s** [comment]
it's not directly a bug with keepass, but it's an issue you run into when you recommend letting external programs to do syncing, from the website:
"Cloud synchronization with Dropbox, Google Drive, OneDrive, Nextcloud etc. can be easily accomplished by simply storing your KeePassXC database inside your shared cloud folder and letting your desktop synchronization client do the rest. We prefer this approach, because it is simple, not tied to a specific cloud provider and keeps the complexity of our code low."
just thought i should put this risk when doing that somewhere, not sure if a "bug report" was the correct thing. but at least now it's documented somewhere.

**Comment by phoerious** [comment]
We assume your cloud sync is always online. If you happen to be offline for some time, you should first give it the chance to sync your changes. But that is not a problem with only KeePassXC. You will run into this with any file. But in most cases, Dropbox should create conflict files to avoid data loss. You probably have some yourself. The are copies of the file with a time stamp in the name.

**Comment by droidmonkey** [comment]
Right, Dropbox won't merge your dually changed pdf, docx, and other files. Its not a version control system.

**Comment by madhadron** [comment]
Note that "always online" doesn't matter here, as syncs are eventually consistent databases. Manually merging conflict files is not a solution.
