### ISSUE TITLE
Create a sub database/Section under the main database with restricted access for another user.

### ISSUE THREAD

**Issue by Jalfreziboy** [keepassxreboot/keepassxc#8220]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )

My wife and I currently use Keepass for our password manager. My wife's database is a sub section of my database so I can maintain both. My wife accesses a separate database which is populated and updated from my database using a keepass plugin so I only have to update her data in my my database and it is copied across to her database, therefore I only have to enter/update information once and my wife only gets access to her passwords and not mine.

I would like to migrate to KeepassXC in order to use a Cloud as my database repository but obviously I cannot use the keepass plugin to populate a second database. Would it be possible to create a sub database or section in the main KeepassXC database that another user (my wife) could access without getting access tom my passwords?

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
 I  have to update data in my and my wife's database , therefore I only have to enter/update information once and my wife only gets access to her passwords and not mine.

**Comment by phoerious** [comment]
Use KeeShare.

**Comment by Jalfreziboy** [comment]
Thank you
