### ISSUE TITLE
Can't save database when Yubikey was previously detached

### ISSUE THREAD

**Issue by lusitania** [keepassxreboot/keepassxc#8221]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
Recently I'm getting the error message
> Writing the database failed: Database file has unmerged changes.

when I'm changing a record in the background while my Yubikey was detached and issue a manual save after I've re-attached the dongle.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Pull dongle off.
2. Select a site for which you have a record but need an "Additional URL" for auto-fill to work.
3. Add the additonal URL and visit the page.
4. Trigger auto-fill and allow/grant access.
5. Go back to KeePassXC, note the * in the database name. Put dongle back in.
6. Save database (ctrl-s), note message "Writing the database failed: Database file has unmerged changes."
7. Call "Merge From Database...". Note message "Successfully merged the database files.".
8. Save database (ctrl-s), note message "Writing the database failed: Database file has unmerged changes."

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Database is saved successfully after merge.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Error message is shown.

## Context
[NOTE]: # ( Give us any additional information you may have. )

KeePassXC - Version 2.7.1
Revision: 5916a8f

Qt 5.15.3
Debugging mode is disabled.

Operating system: Windows 10 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.19044

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 2.18.1

**Comment by droidmonkey** [comment]
I cannot reproduce this at all, please provide more information on where you database is stored. I don't think this has anything to do with Yubikey nor your steps 2 -> 5 (ie, any database change would start this).

**Comment by lusitania** [comment]
Hm that's strange. I'm syncing my database with Google Drive. Let me try to reproduce the case myself.

**Comment by droidmonkey** [comment]
Try setting alternative save method using temporary file moved into place (this is in the application settings). This error message "Database file has unmerged changes" only appears when the underlying file has a different hash value then the currently open file and a merge operation has not occurred:

// Fail-safe check to make sure we don't overwrite underlying file changes
// that have not yet triggered a file reload/merge operation.
