### ISSUE TITLE
Yubikey usage

### ISSUE THREAD

**Issue by sergey-kirsanov** [keepassxreboot/keepassxc#8222]
Hello,

I think, that it is better to do not always ask for master password and Yubikey both the same time to open database.

Let's imaging another way of working. Yubikey should not be simply second factor I think, but should work as follows.

1. Master password is always opens database even if Yubikey is missing (lost, for example).
2. Yubikey opens database without any additional input if for example, during last hour machine was active and not locked and master password was provided no more than one hour ago. After one hour you will ask for master password again and start counting this time again.

What do you think? Could be this behavior implemented as an option to what you provide now?

**Comment by droidmonkey** [comment]
We cannot do this as it is incompatible with keepass format. If you want something like this you need two database files:

1. Database 1 is opened by yubikey only and has a keeshare setup in the root group that opens database 2 via password. (Can also use auto open, read the user guide)
2. Database 2 is your actual database that is protected by only a secure password.
