### ISSUE TITLE
Bad passwords finder tool

### ISSUE THREAD

**Issue by sergey-kirsanov** [keepassxreboot/keepassxc#8223]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
I want to have small tool which finds bad passwords for me and groups them together like a grid view.
Bad passwords are passwords:
1. With bad usual password security level as in passwords generators like 12345, qwerty
2. Duplicated passwords.
3. Passwords having same sub-strings like test123, 123test, xyztest
4. ....some other criteria

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )
I need just a grid with such passwords maybe with grouping by criteria from summary (1, 2 or 3) and then with sorting by password field.

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
I've migrated from Apple Keychain and just because most of passwords were added into it on the run and not always key generator was proposed then I mostly used two or three passwords with some combinations.

Now, I need to have proper tool to check how much such password I have and then to take the action like:

1. RIght click password entry and choose - Open URL
2. Enter old user name and password using KeePassXC
3. Navigate to some page which provides an ability to change the password.
4. Generate new password using KeePassXC generator.
5. Put it both on the site and into KeePassXC.
6. Grid will filter out this record then and I am finished with solving bad password issue for it. I am normally safe because we have record's history.

**Comment by droidmonkey** [comment]
Database menu -> Database reports
