### ISSUE TITLE
Option to disable automatic update

### ISSUE THREAD

**Issue by NickETH** [keepassxreboot/keepassxc#8226]
Hi Devs,
please implement an option to disable automatic updates.
This features is a real good thing for the average user in a single user environment.

But it makes managing this software with a deployment system in a bigger environment a night mare.

Does not matter how you implement it, but it must at least override the setting from the GUI.

Thank you.

Nick

**Comment by droidmonkey** [comment]
Duplicate request #7573

**Comment by NickETH** [comment]
Hi Jonathan,
request #7573 is in no way a solution to this problem.
Copying a default config.ini to each user can be used to set default values, not more.
And it is extremly elaborate zu implement.
But in a centralized deployment, certain options need to be locked.
So i tested the possibility to redirect the config file by an env.var.
Does not work either, because we would have to put it in ready only directory.
And then no other options can be changed.

This is a common behaviour, that thousands of software-products allover the world on all platforms support.
You find that also in lot of OS products, like Notepad++, Firefox, Chrome aso.

So, please consider to implement a layered option input.

That would make deployment of this great product a lot easier.

Thnx.
Nick

**Comment by droidmonkey** [comment]
Uh it's a workaround/option not a solution. The request is still open for implementation. We are not an enterprise focused application, so this isn't the top of our priority list. 

Note: I do find it important to support enterprise deployments, but it's a lot of work to implement a robust and easily managed solution.

**Comment by NickETH** [comment]
Completeley understand that.
It is always about priorities, is'n it?
Just looked at the code in Config.cpp.
What about a layered aproach with 2 or tree config files?
First, read a default.ini
Then the config.ini from actual location with all the user based settings.
And at the the end, read a locked.ini with the settings, the user can not override.
In Config::createConfigFromFile if i am getting that right?

**Comment by droidmonkey** [comment]
That's a good idea, I'll see what I can do
