### ISSUE TITLE
Can't generate a keyfile

### ISSUE THREAD

**Issue by jeanmarie18** [keepassxreboot/keepassxc#8230]
# problem
I want to generate a keyfile:
- I press "Generate"
- Then give a name to my keyfile
- A window appears saying: "Function not implemented":
![image](https://user-images.githubusercontent.com/43229928/177008189-b7dce307-6845-4553-b634-da869181a219.png)

# tried
I installed (but to no avail) the following packages, because they were not found when typing ` ldd /snap/keepassxc/1563/usr/bin/keepassxc`:
- libqrencode-dev
- libbotan-2-12
- libminizip1

# environment:
   - KeepassXC version is 2.7.1 revision 1563 (snap install)
   - My OS is "Ubuntu 20.04.4 LTS"

**Comment by droidmonkey** [comment]
This is a bug with snaps on ubuntu. You'll need to use our flatpak or appimage instead.
