### ISSUE TITLE
Is QuickUnlock (Touch Id) working or planned for keepassxc-cli?

### ISSUE THREAD

**Issue by pe-st** [keepassxreboot/keepassxc#8232]
## Summary

I would like to use QuickUnlock (Touch ID) to comfortable use keepassxc-cli from scripts that need username/password

In the FAQ and the keepassxc-cli man page I couldn't find any mention of this feature, and having the database open in GUI application (where Touch ID works), I couldn't find a way to not type my long password on the command line

When using a script multiple times, I'd like to retrieve username/password from a KDBX entry using keepassxc-cli instead of typing the password for every script run. To make this usable, I'd like to give my long kdbx password only the first time and then using QuickUnlock.

Was this just never implemented? Would it be possible at all (maybe the OS doesn't allow to access Touch ID from CLI, I'm not an expert here...)?

**Comment by droidmonkey** [comment]
Not planned and I am not sure of you can invoke touch id without a gui.

**Comment by pe-st** [comment]
> Not planned and I am not sure of you can invoke touch id without a gui.

Thx for the quick answer!

**Comment by jmanteau** [comment]
I would be interest in this one as Mac built-in security command does not offer that and it would be quite nice to allow for better security when selecting password in CLI.

**Comment by droidmonkey** [comment]
We are not going to implement a quick unlock for the CLI.

**Comment by Tyrael** [comment]
I really liked this feature while using 1password-cli, I really wished if it would be available :(
Is this a design decision or just a resource constraint? (eg. would it be considered for inclusion if somebody creates a PR for it)
