### ISSUE TITLE
Copy password from auto type dialog not possible

### ISSUE THREAD

**Issue by eikowagenknecht** [keepassxreboot/keepassxc#8233]
## Overview

- When right clicking an entry in the auto type dialog, the option "Copy password" is always *inactive* (greyed out).
- The option "Copy TOTP" instead is always *active* even though no TOTP is saved for that entry.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Open autotype dialog
2. Rightclick entry

## Expected Behavior

- "Copy password" should be *active*
- "Copy TOTP" should be *inactive* when no TOTP is saved for the entry

## Actual Behavior
See above

## Context
I need to copy the password from that dialog manually into gpg pinentry window because that is running with admin priveleges (and thus KeepassXC can't type there).

KeePassXC - Version 2.7.1
Revision: 5916a8f

Qt 5.15.3
Diagnosemodus ist deaktiviert.

Betriebssystem: Windows 10 Version 2009
CPU-Architektur: x86_64
Kernel: winnt 10.0.19044

Aktivierte Erweiterungen:
- Auto-Type
- Browser-Integration
- SSH-Agent
- KeeShare
- YubiKey
- Schnelle Entsperrung

Kryptographische Bibliotheken:
- Botan 2.18.1

Operating System: Windows

**Comment by droidmonkey** [comment]
Fixed for 2.7.2 already
