### ISSUE TITLE
Windows: Auto type into elevated window fails without notice

### ISSUE THREAD

**Issue by eikowagenknecht** [keepassxreboot/keepassxc#8234]
## Overview
Autotyping into a program that is run with elevated rights fails without notice. I run VS Code as admin and since can't type into it with KeepassXC (or Keepass for that matter) any more.

Probably this is not possible because of some system rights, but it would be nice if the user got a message saying that the last active window runs with elevated rights and thus autotype couldn't be performed instead of just failing silently. That cost me some hours to figure out.

Using KeepassXC in admin mode as well is a workaround.

## Steps to Reproduce
1. Start a program with admin privileges
2. Start KeepassXC without admin privileges
3. Try to autotype into the program

## Context
KeePassXC - Version 2.7.1
Revision: 5916a8f

Qt 5.15.3
Diagnosemodus ist deaktiviert.

Betriebssystem: Windows 10 Version 2009
CPU-Architektur: x86_64
Kernel: winnt 10.0.19044

Aktivierte Erweiterungen:
- Auto-Type
- Browser-Integration
- SSH-Agent
- KeeShare
- YubiKey
- Schnelle Entsperrung

Kryptographische Bibliotheken:
- Botan 2.18.1

Operating System: Windows

**Comment by droidmonkey** [comment]
We can't determine if the window is inaccessible to us so no warning can be issued. We just issue keyboard typing to a window using the windows event system.
