### ISSUE TITLE
Inefficient use of space (notes section)

### ISSUE THREAD

**Issue by Lrapava** [keepassxreboot/keepassxc#8236]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
Inefficient use of space in the bottom panel

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Create new entry
2. In notes section paste some long dummy text
3. Increase the height of the bottom panel beyond some critical point

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
The height of the "Notes" section should increase as the height of the bottom panel is being increased, filling all the empty space with text

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
"Notes" section won't extend all the way to the bottom of the panel, leaving a bunch of empty space (resulting in inefficient use of space)

## Screeshots:
![Screenshot_20220704_214413](https://user-images.githubusercontent.com/46052668/177200177-9918ce38-e6a9-4f75-aeb3-f3862d7badfa.png)
![Screenshot_20220704_214437](https://user-images.githubusercontent.com/46052668/177200188-c977b035-c0ce-40a3-9d46-35f5e08d362a.png)
![Screenshot_20220704_215037](https://user-images.githubusercontent.com/46052668/177200677-266a1cc4-e8d4-49f6-bb27-dcdb77471727.png)

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.1 (flatpak)
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: KDE
Windowing System: Wayland

**Comment by droidmonkey** [comment]
Already fixed for 2.7.2
