### ISSUE TITLE
System Error: VCRUNTIME140_1.dll was not found 

### ISSUE THREAD

**Issue by xrbtw** [keepassxreboot/keepassxc#8240]
Just reinstalled Windows 10. And whenever I try and open it I get the error "System Error: VCRUNTIME140_1.dll was not found." I have already tried downloading this: https://docs.microsoft.com/en-US/cpp/windows/latest-supported-vc-redist?view=msvc-170#visual-studio-2015-2017-2019-and-2022 and still doesn't work.

**Comment by droidmonkey** [comment]
You probably need to reboot, that is the correct download. If it still doesn't work you can install the legacy windows version of keepassxc from our downloads page.

**Comment by xrbtw** [comment]
Worked thanks
