### ISSUE TITLE
Update all favicons

### ISSUE THREAD

**Issue by lamejack** [keepassxreboot/keepassxc#8244]
## Summary
Sometimes websites change their favicons (new logo, better image quality), that's why it would be great to have an option to update all favicons in your database by one click. 

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )
Just add an update button in a favicon menu.

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
Now if I know that a website changed its favicon I need to open up a specific entry and update it manually.

**Comment by droidmonkey** [comment]
Search for *, select all entries, right click, download favicon.

**Comment by dioni21** [comment]
Can we close this now?

**Comment by droidmonkey** [comment]
Yes this is already a possible feature.
