### ISSUE TITLE
Make tags searchable in the autotype popup

### ISSUE THREAD

**Issue by MysticalMount** [keepassxreboot/keepassxc#8246]
## Summary
Ive got a fair few entries, and while I know you can limit search Ive not found this to be a great solution.  Tags is a great way to find what you want quicker, but the auto-type pop-up seems to ignore them.

I use browser integration for almost everything - but for VPN login which requires a TOTP I still require auto-type - problem is all of the entries appear except just the ones I actually want to use auto-type on.  It often picks up the window title, which I want to ignore primarily because my VPN window doesnt have a Window title (presumably for security).

Ive tried to limit this using the group settings for disabling auto-type, but even when disabled at root and every child group inheriting that setting, every single auto-type entry still appears in the pop-up, and still works.

Limiting search does work, but then that affects my main search within the application, which isnt desirable.

Searching for tags in the auto-type box would help narrow down the entries we want to find using specific searchable tags from the auto-type pop-up.

**Comment by droidmonkey** [comment]
Use `tag:[tag name]` to search for tags. Example: `tag:important`
