### ISSUE TITLE
Highlight search results in Notes

### ISSUE THREAD

**Issue by Massimo-B** [keepassxreboot/keepassxc#8247]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
When doing a universal search please highlight the found results in the Notes field.

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
I finally migrated my encrypted VIM text file to KeepassXC. Usually I use attributes, but for some lazy parts I just copied text parts into the Notes field. With the editor I was able to search in the text. Now on KeepassXC there is no context menu on the Notes field providing a search, only Copy and Select All.
However it would help when doing a universal search (on all fields) using the search bar, if you highlight the found results in large Notes entries.

**Comment by droidmonkey** [comment]
We won't implement this because it is incredibly hard to do. There is very little gain and a lot of work. Recommend migrating your data out of notes so you can use Auto-Type and other features effectively.

**Comment by Massimo-B** [comment]
Ok. Is that really a lot of work? You already search for Notes: content, would highlighting be much more effort?

**Comment by droidmonkey** [comment]
Search is done on the data plane, highlighting is presentation layer and involves a lot of plumbing and html tag injection and user expectations. Why highlight just notes? How about title and username and and .... it spirals from there. Search is meant to find an entry that contains the data and provide that list of entries to the user. It is not meant to bring you exactly to the data element that is contained in that entry. That is the line we currently have drawn.
