### ISSUE TITLE
Scaling Issue

### ISSUE THREAD

**Issue by BlackForest909** [keepassxreboot/keepassxc#8249]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
I get a scaling bug where the software appears to be scaled to 125% but all inputs are still expected at their original location. This also causes autotyping to fail and not successfully log in (for an unknown reason as I tried autotyping into notepad with no issue).
Only restarting the software fixes the issue

![KeePassXC_Bug](https://user-images.githubusercontent.com/108793799/177514427-4bbccfa7-990c-4635-949a-882bd8f0190a.png)

## Context
[NOTE]: # ( Give us any additional information you may have. )
Almost certain this has to do with my Monitor Setup, I have a 14'' laptop and two 24'' monitors. Laptop is scaled to 125%, monitors to 100%.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Have keepass running (doesn't seem to matter if open or minimized)
2. Disconnect Laptop from Monitors (I use a docking station and need to disconnect fairly regularly)
   Note: at this stage everything is fine and works
3. Reconnect Laptop to Monitors.
4. The scaling goes weird and keepass becomes unusable.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.1
Revision: 5916a8f

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 10

**Comment by phoerious** [comment]
If anything, this is a Qt bug that we cannot solve. Qt has a history of having problems with scaled resolutions.
