### ISSUE TITLE
Incorrect icon in subfolders when creating a new entry

### ISSUE THREAD

**Issue by komandar** [keepassxreboot/keepassxc#8252]
## Overview
If you create a subfolder in an existing group and add a new entry to it, the entry does not get the icon of the parent folder but always the default "Key" icon.

## Steps to Reproduce
1. Create subfolder in root folder
2. Add a new test entry in the subfolder

## Expected Behavior
Test entry should have the parent icon.

## Actual Behavior
Test entry has the default "Key" Icon.

## Context
KeePassXC - Version 2.7.1
Revision: 5916a8f

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: Gnome
Windowing System: X11

**Comment by droidmonkey** [comment]
If the subfolder has the default folder icon than it won't give that to an entry. Also make sure you have the setting enabled in application settings to assign the folder icon to new entries.

**Comment by komandar** [comment]
Thanks for your fast reply.
Yes, the option is already enabled for me.

But I see what you mean.
But shouldn't (from a logical point of view) a new entry in a subfolder where the "Default Folder Icon" is used also use the "Default Folder Icon" of the subfolder for new entries?

Even setting the folder icon for the corresponding subfolder manually afterwards does not cause the icon for new entries to be set correctly. That means, the "Folder-Icon" can never be used for new entries by default.

**Comment by droidmonkey** [comment]
You can use the "Also apply to child entries" option on the icon settings page of the folder. This  is just a carry over from keepass original and keepassx which also don't set the default folder icon on new entries. 

Since we aren't going to change this behavior I am closing this issue.
