### ISSUE TITLE
Auto typing does not work in "detailed" URL

### ISSUE THREAD

**Issue by pietryna** [keepassxreboot/keepassxc#8253]
## Overview
I have saved password for https://login.mercedes-benz.com/ portal but most of redirects to this login page contains some data which extends URL (e.g. https://login.mercedes-benz.com/?instance=default&resumePath=%252Fas%252FO3sJO%252Fresume%252Fa[...]). Autotype does not work correctly.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Get redirected to https://login.mercedes-benz.com/?instance=default&resumePath=%252Fas%252FO3sJO%252Fresume%252Fa[...]
2. Nothing happens

## Expected Behavior
Password is typed following non standard autotype sequence {USERNAME}{ENTER}{PASSWORD}{ENTER} saved in DB.

## Actual Behavior
Nothing happens

## Context
When I place saved URL directly into the browser, fields are detected and login/pass are typed correctly. Once redirected from any other Daimler app it looks like page is not recognized despite full domain is the same. 
Issue started do occur since domain change from https://login.daimler.com to https://login.mercedes-benz.com. I've cloned DB entry and replaced URL. Portal behind the domain did not change, at least from user perspective. Redirect URL has been prepared basing on the same principles as now.

KeePassXC - 2.7.1
Revision: 5916a8f
KeePassXC-Browser - 1.8.0
Operating system: Win64
Browser: Mozilla Firefox 102.0

**Comment by droidmonkey** [comment]
Don't rely on urls for Auto-Type, it uses window title detection and matching primarily. Read the user guide for info on how to setup Auto-Type successfully.
