### ISSUE TITLE
When KeePassXC locks the database the "Input Password field" loses focus

### ISSUE THREAD

**Issue by spi43984** [keepassxreboot/keepassxc#8257]
## Overview
When KeePassXC locks the database the "Input Password field" loses focus.

## Steps to Reproduce
1. Wait until KeePassXC locks the database (not important if KeePassXC is the top window or in the background).
2. If KeePassXC is not the top window, switch to it by Alt-TAB or other means (like wmctrl).
3. KeePassXC is brought to top and in earlier versions one could start typing the DB password.
4. But "Input Password field" has no focus so you can't start typing the DB password - you need to select it first by TAB or mouse.

## Expected Behavior
As soon the locked window is brought to focus I'd expect the "Input Password field" to have focus so the DB password could be entered immediately.

## Actual Behavior
see steps to reproduce

As I open two databases (daisy chained) most time the tab of the first DB gets the focus.

## Context
Usually I switch by a hotkey to KeePassXC which finds the right window by `wmctrl -l -x | gawk '{print $1, $3}' | grep "keepassxc.KeePassXC" | cut -f1 -d' ')` and switches to it by `wmctrl -i -a <windows-ID from prev command>`.

KeePassXC - Version 2.7.1
Revision: 5916a8f

Operating System: Linux
Desktop Env: Gnome
Windowing System: X11

**Comment by droidmonkey** [comment]
I cannot replicate this at all. Most likely induced by something local to your configuration and not related to KeePassXC specifically.

**Comment by spi43984** [comment]
Might be. Difficult to say. What I tried are the KeePass-AppImages in the versions 2.6.6 and 2.7.1 - my local installed one is the Debian deb package version 2.7.1 as well (from http://ppa.launchpad.net/phoerious/keepassxc/ubuntu).

With the KeePass 2.6.6 as AppImage I don't see this behavior. But I also do see it with the AppImage version 2.7.1. But it only happens when I have two databases opened and locked.

For whatever reason when I switch by Alt-Tab to the KeePass window very often the database tab gets the focus, not the password entry field.

Quickly checked AppImage 2.7.0 - shows same behavior as 2.7.1.

**Comment by droidmonkey** [comment]
Good info I'll take another look

**Comment by spi43984** [comment]
Is there anything else I can do for troubleshooting? I've been using version 2.6.6 for almost two week now and haven't had any issues.

**Comment by spi43984** [comment]
I'm still facing the issue. Had to disable the AutoOpen daisy chain function to open the second database to get rid of it.

**Comment by droidmonkey** [comment]
Cannot reproduce at all, sorry
