### ISSUE TITLE
1Password.opvault [1PW 7] - Import - Filepicker - „Open” greyed out - Import not possible

### ISSUE THREAD

**Issue by nodevnul** [keepassxreboot/keepassxc#8258]
## Overview
1Password 7 1Password.opvault folder cannot be chosen to import

## Steps to Reproduce
1. Created 1Password.opvault folder through sync folder in 1PW7
2. Launch KeePassXC with default start screen (no database)
3. Choose „Import from 1Password”
4. Navigate to path where the 1Password.opvault folder resides
5. Click on the file picker entry
6. „Open” greyed out

## Expected Behavior
„Open” not greyed out - Import should work as stated in Userguide

## Actual Behavior
1Password.opvault folder cannot be imported.

## Context
KeePassXC - Version 2.7.1
Revision: 5916a8f

Qt 5.15.2
Diagnosemodus ist deaktiviert.

Betriebssystem: macOS 12.4
CPU-Architektur: arm64
Kernel: darwin 21.5.0

Aktivierte Erweiterungen:
- Auto-Type
- Browser-Integration
- SSH-Agent
- KeeShare
- YubiKey
- Schnelle Entsperrung

Kryptographische Bibliotheken:
- Botan 2.19.1

**Comment by droidmonkey** [comment]
You need to rename the .opvault folder to something else before it will work. This is a macOS limitation.
