### ISSUE TITLE
Contextual search fails to find something that the main search does (and should) find

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [keepassxreboot/keepassxc#8260]
## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1.  Have an entry the title of which is 'Box.net' and that has this URL field: 'https://account.box.com/'
2.  Try successfully to find the entry using the main search and the search string 'box'.
3.  Go to https://account.box.com/login. Press shortcut hotkey. Enter 'box'. 

## Expected Behavior
All and only that which is found by the main search should be be found by the contextual search; and, in this case, both searches should find the box.net entry via the string 'box'.

## Actual Behavior
The main search finds the entry via the string `box'. The contextual search does not.

## Context
I have not tried to reproduce the problem with a new database containing only a box.net entry.

KeePassXC - Version 2.7.1
Revision: 5916a8f

Qt 5.15.3
Debugging mode is disabled.

Operating system: Windows 10 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.19044

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 2.18.1

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows

**Comment by droidmonkey** [comment]
What do you mean by contextual search? Please provide a screenshot.

**Comment by LinuxOnTheDesktop** [comment]
I mean the search box that pops up under the following circumstance. A webpage with a fillable field is visible. One presses the shortcut key for KeePassXC. A KeePassXC window pops up listing possible candidate auto-fills and that same window contains a search box.

I tried and failed to provide a screenshot. Exiting KeePassXC and then running `"C:\<installpathtoexecuteable>\KeePassXC.exe" --allow-screencapture` from CMD (see [here](https://github.com/keepassxreboot/keepassxc/issues/7580#issuecomment-1131295253)) produced an instance of KeePassXC but not one that had a tray icon or a window.

**Comment by droidmonkey** [comment]
That searches the entries visible in the view. If you want to search all database entries, make sure you check the box in the dialog. Read the user guide for more information.

**Comment by LinuxOnTheDesktop** [comment]
Sorry, but, 1) To which box do you refer? Presumably not one that is labelled 'Search all open databases'. That box is greyed-out for me. For, I have only one database.

Again, I'm sorry, but: 2) The user guide is large; which part I should read is not obvious.

So far as I can tell the following needs saying too. 3) On the face of it, the need to search all database entries merely pushes the problem back a stage. For now the question is: why did the program fail to make visible the entry that contains the string 'box', given that all of the following obtains? i) I have typed that string into the search. ii) The URL that the browser displays contains the word 'box'. iii) The relevant database entry contains 'box' both in its title and in its URL field.

**Comment by droidmonkey** [comment]
If the box is grayed out that means you are already searching all databases. Have you disabled autotype for the entry you are looking for at the parent group?

**Comment by LinuxOnTheDesktop** [comment]
Group Auto-Type setting was: `Inherit from parent group (Enable).`

_Yet_, within the entry itself, 'Enable Auto-Type for this entry' was . . disabled. I do not remember disabling it! Auto-type now works for the relevant webpage - and works directly, without showing the search box. (Or rather autotype would work properly - fully - on the page, were the site not to have one page for the username and another page; but that is another kettle of fish).

So, unless the entry's autotype flag was disabled by a bug - which does seem unlikely - then I fear that I have wasted your time.

**Comment by droidmonkey** [comment]
No problem glad it's a simple matter to fix.
