### ISSUE TITLE
Global Autotype invokes logoff session on OpenSUSE Leap 15.4, KeepassXC 2.7.1 and KDE Plasma 5.24.4

### ISSUE THREAD

**Issue by klawdhfzasjhaa** [keepassxreboot/keepassxc#8261]
After upgrading to OpenSUSE Leap 15.4, KeepassXC is behaving strangely.
When pressing the shortcut for Autotype (e.g. CTRL + ALT + P), I am logged off from the Plasma Session. If there are two or more matching entries, I can choose one of them, which also results in a logoff.

Have already reinstalled KeepassXC and deleted the config file. No luck.

Is there anything, I can do to solve this?

**Comment by droidmonkey** [comment]
This is because we inadvertently cause a crash in older X11 systems with our Auto-Type. This came about when trying to fix international keyboard layout support. See #7797
