### ISSUE TITLE
FIngerprint open

### ISSUE THREAD

**Issue by jjo21631** [keepassxreboot/keepassxc#8263]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
Fingerprint open of a locked database should not need ENTER KEY or click on Unlock Database to unlock open locked database. Would be helpful to allow reading of fingerprint on that dialog. Also would be nice to allow pin entry from this dialog as well.

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
Save time to unlock a database, simply for convenience. Either accept entry or wait for click/enter and provide an entry dialog as is currently the practice.

**Comment by droidmonkey** [comment]
This is not something we can do as it requires in invoking operating system dialogs. We decided to not auto prompt since that is rather hostile to user in a multi application environment. The user must explicitly request an unlock first.
