### ISSUE TITLE
Add open in private browser option to context menu

### ISSUE THREAD

**Issue by madeinoz67** [keepassxreboot/keepassxc#8264]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
Currently for any entry with a URL file the only option is to open which will open to a standard browser window, I'd like to see the addition option in the right-click context menu of opening the entry into a Private browser window of the default browser

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )

Screenshot showing current implementation in Keepass 2.5x that include option for opening in different browsers

![image](https://user-images.githubusercontent.com/4160293/178629527-2053fd5b-a952-4c52-983c-9c456110aee1.png)

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )

Standard browser is logged into corporate network with SSO of current user, however when performing a lot of Administration work in consoles that require elevated privilege, i.e. admin accounts that must be used in Private windows.

**Comment by droidmonkey** [comment]
Duplicate request to allowing an alternative browser. #4495
