### ISSUE TITLE
Generated password backup

### ISSUE THREAD

**Issue by NicoPy** [keepassxreboot/keepassxc#8267]
## Summary
Save generated passwords in a folder

## Context
With KeePass 2 (the original software) and the Kee Firefox extension, when generating a new password from Firefox, this password is saved in a folder (Kee generated password backup).
This is very useful in some situations :
- Generate a password
- Register on a website with this password
- For some reason, the website credentials are not saved in the database
- Time elapses and clipboard content is erased
Then, you are registered with a password you don't know and you can't recover.

Saving the generated passwords in a dedicated folder (like Keepass 2 does) would be useful in this situation. 
I was regularly using this feature when using Keepass 2.

**Comment by droidmonkey** [comment]
We already support this through our browser extension. You must create a new entry yourself and save the generated password if you do not use the browser extension. The stand alone password generator is not tied to any database and cannot create entries. Your workflow is largely covered by the request for a password change workflow.

**Comment by NicoPy** [comment]
I use the browser extension.
The passwords generated with the browser extension are not saved anywhere. Or I have not found where they are saved.
