### ISSUE TITLE
Include Help menu (with search area) for macOS

### ISSUE THREAD

**Issue by jsoref** [keepassxreboot/keepassxc#827]
## Expected Behavior
There should be a help menu with a search box for searching for menuitems

## Current Behavior
There's no help menu, and no search

## Steps to Reproduce (for bugs)
1. Open KeePassXC
2. Look at menubar

## Debug Info
KeePassXC - Version 2.2.0
Revision: caa49a8ef3ee28ed478192389b21d61107b3b8e0

Libraries:
- Qt 5.9.0
- libgcrypt 1.7.7

Operating system: macOS Sierra (10.12)
CPU architecture: x86_64
Kernel: darwin 16.6.0

Enabled extensions:
- KeePassHTTP
- Auto-Type
- YubiKey

**Comment by droidmonkey** [comment]
Can you provide a screenshot example of what you are looking for? We don't have that many menu items, a search box doesn't not seem very useful.

**Comment by jsoref** [comment]
https://www.drupal.org/files/mac-osx-help.png

**Comment by droidmonkey** [comment]
Yah... that seems like a ton of work for very little gain. Sorry but I don't see this feature being implemented.

**Comment by phoerious** [comment]
AFAIK, Qt should add such a search bar automatically, at least if the application language is English.

**Comment by jsoref** [comment]
https://stackoverflow.com/questions/6673612/qt-on-mac-how-to-access-search-in-help-menu
It seems you might need a help book (and then it might magically work)?

**Comment by phoerious** [comment]
I don't think so. Help Book is probably the end user documentation. A menu search is probably provided directly by Qt if the menu has a special help role or something. In Qt there's a lot of magic like that going on macOS.

**Comment by droidmonkey** [comment]
Excuse my continued ignorance of built in Mac "features"

**Comment by weslly** [comment]
Qt automatically adds it but since there's only the "About KeepassXC" submenu and its menu role standard location is under the application menu, the "Help" doesn't appear.

We should add at least one extra submenu to "Help" to get it back, maybe a link to the documentation.

**Comment by phoerious** [comment]
I would assume there is some menu role we can set for the about menu.

**Comment by jsoref** [comment]
The about menu belongs where it is...
