### ISSUE TITLE
To display Secret Questions in a list during auto-type

### ISSUE THREAD

**Issue by dnai05** [keepassxreboot/keepassxc#8274]
## Summary
This is probably a big ask but you never know if you don't ask :-). I have come across several cases when I have been asked to enter the answer to a secret question during the login process. It would be very useful if KP showed me a list of secret questions I have saved that I could choose from during auto-type.

Maybe this becomes an attribute type of [List] which could be used in a template  (#863)?  Then it could be used for any attribute with multiple values.

## Examples
Username (as saved for this entry)
Password (as saved for this entry)
Secret Question (if this is a [List] attribute then KP would show them in a list). Let's say the secret question is "What car". When KP gets to this field it would show all the questions for the entry, e.g.

Please choose the [attribute name] (e.g. secret question)
* What school?
* What pet?
* What car?

I then choose the question matching the one on screen so KP can update the field appropriately.

## Context
Usually occurs for banking or investor sites.

**Comment by michaelk83** [comment]
For now, you can add the questions as custom attributes, and define custom auto-type sequences to type them in, via the Window Associations settings: https://keepassxc.org/docs/KeePassXC_UserGuide.html#_configure_auto_type_sequences

> Leave the window title blank to offer additional default Auto-Type sequences, such as custom attributes.

(May work with a non-blank window title as well.) Then when you perform the auto-type, it should give you a list of the custom sequences to choose from. Though it would be nice to have more native support for security questions as part of #863 .

**Comment by droidmonkey** [comment]
We won't explicitly support this as a feature, it is very niche. As @michaelk83 stated above, you can add multiple sequences to a window match by keeping the title blank, then just add sequences like `{S:first car}` to type advanced attributes.
