### ISSUE TITLE
Application freezing for period of time on merge

### ISSUE THREAD

**Issue by succeedmr123** [keepassxreboot/keepassxc#8275]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

Freezing after successful merging in-mem database with on-disk db.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1.  work in unstable internet connectivity
2. have database merge detect message requester appear and accept merge
3. watch keepssXC freeze after merge (afterwards seen db was merged successfully)

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

Rock-solid merge function, never to freeze regardless of any real-world factors (filesystem, connectivity conditions, does not matter the app does not freeze/lock)

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

As said, it freeze / locks-up  upon merge detect /approve requester

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )

KeePassXC - Version 2.7.1
Revision: 5916a8f

[NOTE]: # ( Pick choices based on your environment )

Desktop Env: KDE Plasma
Windowing System: X11

Qt 5.15.3
Debugging mode is disabled.

Operating system: Ubuntu 22.04 LTS
CPU architecture: x86_64

**Comment by droidmonkey** [comment]
Does it really 'freeze' or does the entry list and group list just get disabled like it always does when a save is happening?

**Comment by carestad** [comment]
I am seeing this too. It happens only in the flatpak version of the app, so I have to have the AppImage version to do the merge. The whole UI freezes up and it is rendered unusable when this happens.

Personally I am using the latest 2.7.4 version from flathub.

This can also happen sometimes when storing new entries to the DB via the browser extension.

**Comment by droidmonkey** [comment]
This is not reproducible
