### ISSUE TITLE
keepassxc-cli cannot open database

### ISSUE THREAD

**Issue by ghost** [keepassxreboot/keepassxc#8279]
When I type 
`
keepassxc-cli show -s xxxxx.kdbx xxxx
`
It says
`
Enter password to unlock xxxx.kdbx:
`
After I type the password I get
`
Error while reading the database: Not a KeePass database.
`
I am using artix and keepassxc version 2.7.1 and also can confirm kdbx 4 database can open in keepassxc just fine with all entries listed.

EDIT: yeah sorry I am an idiot fixed the issue

**Comment by droidmonkey** [comment]
This error message is unambiguous. It means the file you are loading doesn't even have the kdbx magic numbers at the very beginning of the file. The same code is used to open databases in gui and cli. You need to figure out what is going on with your files, but this isn't a code problem.

**Comment by michaelk83** [comment]
@droidmonkey is the password needed to check the file signature? If not, then that error should preferably be shown before asking for the password.

**Comment by droidmonkey** [comment]
We don't touch the file until we derive the key. I have wanted to make a header checker function that would do something like that but right now our internal api doesn't support it.
