### ISSUE TITLE
When i open KeyPassXC it disables my Nvidea GeForce Experience Instant Replay

### ISSUE THREAD

**Issue by exitss** [keepassxreboot/keepassxc#8280]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1.  Enable Nvidia GeForce Experience Instant Replay
2.  Open up KeyPassXC
3.  Watch as the Nvidia GeForce Experience Instant Replay gets disabled

## Expected Behaviour
[NOTE]: # ( Tell us what you expected to happen )

Have a setting to disable it turning off Nvidia GeForce Experience Instant Replay

## Actual Behaviour
[NOTE]: # ( Tell us what actually happens )

 it turns off Nvidia GeForce Experience Instant Replay

## Context
[NOTE]: # ( Give us any additional information you may have. )

It is very annoying

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows

**Comment by droidmonkey** [comment]
We don't disable Nvidia instant replay. You can try disabling screenshot protection, but that shouldn't have anything to do with Nvidia instant replay since it's applied to OUR application. 

https://keepassxc.org/docs/KeePassXC_UserGuide.html#_screenshot_security

**Comment by exitss** [comment]
disabling screenshot protection worked. Thanks
