### ISSUE TITLE
Show BIO first for unlock window if applicable

### ISSUE THREAD

**Issue by QuAzI** [keepassxreboot/keepassxc#8281]
According to #3337 actual behavior on tray click if fingerprint enabled: dialog with two [BIO] and [cancel] buttons shown.

But there is no sense to show BIO button and then ask BIO. Just ask BIO (second step) on tray click if applicable. And user can cancel it through closing the window.

**Comment by droidmonkey** [comment]
Discussed previously, we won't do auto biometrics since it does invoke OS features and we are in a multiple app environment. I would maybe consider it if the database unlock floating dialog is invoked and there is only one database open.
