### ISSUE TITLE
Crash when changing password of a database with capslock enabled.

### ISSUE THREAD

**Issue by espinosaivan** [keepassxreboot/keepassxc#8282]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. 
2. 
3. 

## Expected Behavior
[NOTE]: # Want the program dont crashes when changing passwords.

## Actual Behavior
[NOTE]: # If you open a database, and click on menu 'Database' (Sorry i've it in spanish) and click on 'Database security', if you press the 'change password' button with capslock key enabled the program crashes. It don't crash with capslock disabled.

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC -  Versión 2.7.1
Revision:  5916a8f

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows
Desktop Env: 
Windowing System: 

![imagen](https://user-images.githubusercontent.com/74259034/179734625-a3a6f15d-e20b-4b4f-ac86-77418ea25646.png)

**Comment by droidmonkey** [comment]
I do not get a crash on the latest develop branch. Can you try loading a snapshot (https://snapshot.keepassxc.org) to see if it still happens? If it doesn't then this is already (inadvertently) fixed.

**Comment by espinosaivan** [comment]
Truly, it works with the last snapshot. Please excuse me.

**Comment by droidmonkey** [comment]
Great! Marking as fixed for 2.7.2
