### ISSUE TITLE
Have current TOTP code reachable from within the edit UI

### ISSUE THREAD

**Issue by garymoon** [keepassxreboot/keepassxc#8285]
## Summary
In the edit entry view I can view all the items for the entry except any TOTP codes, which I have to exit the editor and click the clock icon to retrieve.

## Context
If I'm in the editor and typing credentials into another window or machine, it would be nice to not have to exit and have extra clicks to get the TOTP code.

Thank you for KeePassXC! :blue_heart:

**Comment by droidmonkey** [comment]
Entry menu -> TOTP
