### ISSUE TITLE
KeepassXC should also look into `$XDG_DATA_{DIRS,HOME}` to get the wordlists

### ISSUE THREAD

**Issue by tobiasBora** [keepassxreboot/keepassxc#8289]
## Overview

NOTE: Since I wrote the first version of this issue, I understood the problem more clearly and I'm therefore editing it to clarify the situation. The old issue is still written below with strike, to skip the discussion of the old problem, directly move to https://github.com/keepassxreboot/keepassxc/issues/8289#issuecomment-1192562841.

For now, KeepassXC searchs for the list of dictionaries in the share folder where it has been installed. However, KeepassXC should also look for the list of dictionaries in the following environment variables:
- `$XDG_DATA_DIRS`: system wide, multiple paths separated with colons, defaults to `/usr/local/share/:/usr/share/`
- `$XDG_DATA_HOME`: per user, a single folder is specified, defaults to `$HOME/.local/share`

Note that one still want to look into the folder where KeepassXC was installed, and one want to ensure that the same file is not included multiple times.

The reasons are multiple: in some OS or package managers (for instance on the linux distribution NixOs or using the nix package manager on a regular distribution), the folder where programs are installed are read-only and separated for each program for various reasons (security, purity, per-user installation, to allow installation of multiple versions of the same program, to easily remove a program…). Therefore it is impossible to modify them later (and add dictionaries). All the `share` folders are however linked to the same path (for instance in NixOs it's in `/run/current-system/sw/share`) and these folders are typically put into the `$XDG_DATA_DIRS` (for programs installed on the whole system) or into `$XDG_DATA_HOME` (for programs installed for a single user) following the famous [XDG specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html).

## Steps to Reproduce:

1. Create a dictionary file and put it, say, in `/tmp/myshare/keepassxc/wordlists/myfile.wordlist`.
2. Update the `$XDG_DATA_DIRS` accordingly:
```
export XDG_DATA_DIRS=/tmp/myshare/keepassxc/wordlists/:$XDG_DATA_DIRS
```
3. Start KeepassXC: the new dictionary is not taken into account.

## ~~Old Overview~~

~~I created a list of words in a file `/run/current-system/sw/share/keepassxc/wordlists/french_frequent_no_derivations_11508_words.txt` (it's where NixOs puts the `share` folder). Unfortunately, even after restarting KeePassXC, I can't see any way to use this file:~~

![image](https://user-images.githubusercontent.com/2164118/180010540-7e17f501-42e3-4d95-bb52-62881470eefe.png)

## ~~Old Steps to Reproduce~~

~~1. Create a file containing some words, like:~~
```
accorder
abolition
abuser
accepter
abomination
abattoir
```
3. ~~Put this file in your share folder like `/usr/share/keepassxc/wordlists/myfile.txt`~~
4.~~ Restart KeePassXC~~

## ~~Old Expected Behavior~~

~~I expect to have a way to specify that I should use this file~~

## ~~Old Actual Behavior~~

~~I can't see any way to specify this file.~~

## Context

I'm running NixOs, I have installed this file using:
```
{ pkgs, config, ...}:
let
  # I made that dict by selecting non derivative (only infinitive, singular, as far as I could)
  # french words that are "frequent" in the sense that they appear enough times (not that much)
  # in a list of files I downloaded
  keepassxc_french_dict = pkgs.stdenv.mkDerivation {
    name = "keepassxc_french_dict";
    src = ./french_frequent_no_derivations_11508_words.txt;
    unpackPhase = ''
      cp $src french_frequent_no_derivations_11508_words.txt
    '';
    buildPhase = "";
    installPhase = ''
      mkdir -p $out/share/keepassxc/wordlists/
      cp french_frequent_no_derivations_11508_words.txt $out/share/keepassxc/wordlists/
    '';
  };
in
{
  environment.systemPackages = with pkgs; [
    keepassxc
    keepassxc_french_dict
  ];
}
```
and the file appears to be present next to the list of word used by KeepassXC:
```
$ ls /run/current-system/sw/share/keepassxc/wordlists
eff_large.wordlist  french_frequent_no_derivations_11508_words.txt
```

KeePassXC - ~~2.6.6~~ 2.7.1
Revision: ~~2.6.6~~ 2.7.1

Operating System: Linux (NixOs)
Desktop Env: KDE Plasma
Windowing System: X11

**Comment by tobiasBora** [comment]
~~Argh, actually I'm realizing that it's implemented only in 2.7.0 https://github.com/keepassxreboot/keepassxc/issues/989#issuecomment-1073954070 I'll try to upgrade~~

**Comment by tobiasBora** [comment]
Actually, I tried in 2.7.1 and the problem is not fully solved: I do have a droplist that appears, but there is only the eff_large.wordlist file that appears. I tried to rename it to .wordlist instead of .txt, no change:

![image](https://user-images.githubusercontent.com/2164118/180027862-72999b63-cb15-4e4b-9f2e-4c65d95e0297.png)

Could you please reopen or let me know if I'm doing something wrong?

Note that if I manually select the file, then it works correctly. But I'd prefer to have it displayed directly as a system-installed dictionary.

**Comment by droidmonkey** [comment]
Move the file into the system directory if you want to use it that way

**Comment by tobiasBora** [comment]
What do you mean? `/usr/share` does not exist in NixOs (to preserve purity) and `/run/current-system/sw/share/` replaces it. So it is already in the system directory (and `eff_large.wordlist` is already in this directory so it indicates that this folder is the good one I guess).

**Comment by droidmonkey** [comment]
Dunno what to say, you'll have to stick with our supported way to add new lists through the gui.

**Comment by tobiasBora** [comment]
Well the FAQ documents that I can add new lists through the system folder, so this should be considered as a supported way I guess no? If not, then we should change the FAQ, otherwise we need to figure out what's going wrong. In any case I guess it makes sense to reopen this issue until this is fixed.

**Comment by droidmonkey** [comment]
We just dump the contents of the wordlist directory into that gui element. We don't support nixOS so you will need to contact those maintainers to see if they made customization to our code in this area. They do modify the code before they package the program so it'll work on this special os. 

https://github.com/keepassxreboot/keepassxc/blob/develop/src/gui/PasswordGeneratorWidget.cpp#L101-L105

**Comment by tobiasBora** [comment]
Well, NixOs does not do anything fancy, the full derivation is given [here](https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/misc/keepassx/community.nix). Any idea if keepassxc provides some methods to debug this? Like is there a way to get the path where it looks for the wordlist?

**Comment by droidmonkey** [comment]
It is clearly finding the eff wordlist, do a search for your file system for that wordlist file name.... maybe it is actually pulling from a local store or some other area? You can also build a debug version and run this through GDB. You can also use strace to see which files are being opened. I have no idea about nixOS so I really can't help you here.

I just dumped another file in my wordlists directory on Windows and it worked just fine. So there is nothing for us to fix here, you most likely are not putting the file in the correct directory that the running keepassxc instance is looking for.

**Comment by tobiasBora** [comment]
Hum, so the share folder is like:
```
[leo@bestos:/run/current-system/sw/share/keepassxc/wordlists]$ ls -al
total 34
dr-xr-xr-x 2 root root   4 janv.  1  1970 .
dr-xr-xr-x 3 root root   6 janv.  1  1970 ..
lrwxrwxrwx 1 root root 104 janv.  1  1970 eff_large.wordlist -> /nix/store/2i6wqwgs2agy2d5lyl0d0fbgadsp396y-keepassxc-2.7.1/share/keepassxc/wordlists/eff_large.wordlist
lrwxrwxrwx 1 root root 143 janv.  1  1970 french_frequent_no_derivations_11508_words.wordlist -> /nix/store/py0njcgci2kf5qq8xl2fzs35ba43rldd-keepassxc_french_dict/share/keepassxc/wordlists/french_frequent_no_derivations_11508_words.wordlist
```
so I guess that Keepassxc gets the path in `/nix/store/` instead of `/run`. I asked in https://discourse.nixos.org/t/proper-way-to-access-share-folder/20495 what is the proper way to handle this kind of issues.

**Comment by tobiasBora** [comment]
As an additional remark, I saw that the `XDG_DATA_DIR` is supposed to contain this kind of `share` folder ([source](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html)), potentially multiple of them separated with colons:

>  If $XDG_DATA_DIRS is either not set or empty, a value equal to /usr/local/share/:/usr/share/ should be used. 

 and NixOs does follow this convention. Obviously, KeepassXC is not following this convention as the `data_dir` is a single folder:

https://github.com/keepassxreboot/keepassxc/blob/7811f10dba8a43d2b440ee193d14db55c9d72e31/src/core/Resources.cpp#L105-L106

https://github.com/keepassxreboot/keepassxc/blob/7811f10dba8a43d2b440ee193d14db55c9d72e31/src/core/Resources.cpp#L124-L129

so I guess a proper way to solve the problem I'm mentioning here would be to also consider the `XDG_DATA_DIRS`.

Note that the current `KEEPASSX_DATA_DIR` should also be kept (maybe even before all other options) in case the program is installed for a single user but not globally.

**Comment by tobiasBora** [comment]
So people confirmed [here](https://discourse.nixos.org/t/proper-way-to-access-share-folder/20495/3) that the best approach would be to use both the [XDG basedir spec](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) (XDG data files paths) in addition to the installation directory (which is the one currently used by KeepassXC). Note that this also provides a solution for user dictionaries as XDG proposes `$XDG_DATA_HOME` (single directory that defaults to `$HOME/.local/share`) for user-specific configuration and `$XDG_DATA_DIRS` for system-wide data (that contains a list of files separated with colons, defaulting to `/usr/local/share/:/usr/share/`).

Would it be possible to re-open this issue until KeepassXC also reads configuration appropriately?

**EDIT** I also modified the issue accordingly.

**Comment by droidmonkey** [comment]
We already use the XDG home directory by virtue of calling qt functions to find local config directories. Using the xdg system directories might be useful, BUT you are looking at this from the wrong end. When you install something on nixOS like you did it clearly placed it in some other location and created a fake symlink folder structure in the 'standard' directories. Does the running keepassxc instance even have the ability to see files stored in another programs actual storage location? I assume this is done for security and containment reasons so most likely not.

At the end of the day, I don't understand why you can't just use the built in user defined wordlist feature? It works and it solves your problem.
