### ISSUE TITLE
Copy to New

### ISSUE THREAD

**Issue by KitchM** [keepassxreboot/keepassxc#8290]
## Overview
I was able to select a number of entries in one group.  I could not export them.

## Steps to Reproduce
1. Select entries in a group.
2. Go to Database>Export>CVS
3. It wants to export the whole thing.

## Expected Behavior
Should allow an export of selected entries.

## Actual Behavior
It warned of database exportation.

## Context
Unknown

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.6.6
Revision: 9c108b9

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux - Debian Bullseye
Desktop Env: XFCE 4.16
Windowing System: X11

**Comment by droidmonkey** [comment]
Duplicate request
