### ISSUE TITLE
Search entries in all (installed) keyboard layouts

### ISSUE THREAD

**Issue by WofWca** [keepassxreboot/keepassxc#8292]
## Summary
If you forget to switch keyboard layout to the right one before searching for entries, it wouldn't find what you want. Would be cool if there was an option (defaulting to `true`) so it does.

There is third-party software that would help with this (just to be clear what I mean): https://github.com/BladeMight/Mahou

## Examples
If my keyboard layout is Russian and I want to search for "twitter" and I forget to switch it to English, I would type "ецшееук" instead, which is gibberish, but in "English" layout it would still be "twitter", so it must return the "Twitter" entry.

## Context
I'm using more than one keyboard layout.

If someone knows a library that does this, I would like to see if I can implement this. Apparently Yandex Browser does such thing, based on its the Wikipedia page.

Related: #3157

**Comment by droidmonkey** [comment]
This isn't for our program to solve. You decide which keyboard layout you are using, not us

**Comment by WofWca** [comment]
In case I wasn't clear – I'm not suggesting that it's supposed to try to switch keyboard layout to the "right" one. It's supposed to search for entries in all the layouts I have.
