### ISSUE TITLE
UI issues when the window is narrow

### ISSUE THREAD

**Issue by WhyNotHugo** [keepassxreboot/keepassxc#8293]
## Overview

When the window is too narrow (e.g.: 50% of the screen on a laptop when using keepassxc side-to-side with something else), the buttons on the right of input fields are out-of-screen and unreachable:

![2022-07-21T21:07:03,694961457+02:00](https://user-images.githubusercontent.com/730811/180296539-3bc1dfa6-0115-48b4-8fd8-08b3a0f83629.png)

Wider window for reference:

![2022-07-21T21:07:08,030263291+02:00](https://user-images.githubusercontent.com/730811/180296697-ea91fd0a-9436-4188-95f3-ab7080e85109.png)

## Expected Behavior

Buttons should render, there's plenty of space.

## Actual Behavior

My guess is that the input fields have a minimum width or something, so extend out-of-window.

## Context

```
KeePassXC - Version 2.7.1
Revision: 5916a8f

Qt 5.15.5
Debugging mode is disabled.

Operating system: Arch Linux ARM
CPU architecture: arm64
Kernel: linux 5.17.0-rc7-asahi-next-20220310-5-2-ARCH

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.19.2
```

Desktop Env: swaywm
Windowing System: Wayland

**Comment by droidmonkey** [comment]
This is likely a qwayland or Sway bug, not us. Our window renders perfectly fine in narrow width on every operating system I've used.

**Comment by WhyNotHugo** [comment]
I can't imagine it being a sway bug. The content fits the region perfectly. Qt is rather buggy on Linux, and especially so on Wayland, so it might be a QtWayland.

Can I help debug this somehow?

**Comment by droidmonkey** [comment]
I don't even know where to start debugging this. It certainly is not our program. It looks like the real width of the window is not being recognized by the  compositor or qwayland and it thinks the window is still full width.

**Comment by droidmonkey** [comment]
I don't even know where to start debugging this. It certainly is not our program. It looks like the real width of the window is not being recognized by the  compositor or qwayland and it thinks the window is still full width.

**Comment by droidmonkey** [comment]
I don't even know where to start debugging this. It certainly is not our program. It looks like the real width of the window is not being recognized by the  compositor or qwayland and it thinks the window is still full width.

**Comment by droidmonkey** [comment]
I don't even know where to start debugging this. It certainly is not our program. It looks like the real width of the window is not being recognized by the  compositor or qwayland and it thinks the window is still full width.

**Comment by WhyNotHugo** [comment]
Oh, I experimented a bit with a floating window with compositor-rendered borders:

https://user-images.githubusercontent.com/730811/180327748-8a7a4e33-19c0-487a-99a6-ad6691ae7a54.mp4

It looks like, at a certain point, KeePassXC is rendering wider than the requested size. In my original scenario, the overflow was invisible.

If I recall correctly, rendering a window larger than the area requested by the compositor is a protocol violation, although one that results in rendering like this, rather than a hard crash (at least for now).

**Comment by WhyNotHugo** [comment]
Huh, Firefox won't play the screen recording, but VLC will. o.O

**Comment by WhyNotHugo** [comment]
My suspicion is that this is a QtWayland bug. I'm guessing that Qt is passing the wrong window size to KPXC, and KPXC just renders a surface that side, which is bigger what the compositor requested (so get cropped or renders out-of-bounds on floating windows).

I'm not proficient enough with Qt/CPP to actually confirm this tho. Do you have any suggestions on how to just print to stdout the "reported window size"?

**Comment by droidmonkey** [comment]
You could use a tool called GammaRay to see the inner qt workings. Closing this though since it's definitely not us.

**Comment by WhyNotHugo** [comment]
I'll give GammaRay a shot. Thanks!

**Comment by WhyNotHugo** [comment]
Oh, that was easier than expected. So apparently when resizing the window, Qt reports the correct height only if height >= 800, and the width is likewise only passed correctly if width >= 500.

At these "magic numbers" it just ... stops? I can't imagine what's happening under the hook, but I'll report upsteam; clearly not a KPXC issue.

**Comment by droidmonkey** [comment]
https://bugreports.qt.io

**Comment by WhyNotHugo** [comment]
Reported upstream as https://bugreports.qt.io/browse/QTWEBSITE-1061.

I found quite a few issues related to window sizes and alike, but none of them seemed to be exactly this case.

**Comment by davidedmundson** [comment]
>At these "magic numbers" it just ... stops? I can't imagine what's happening under the hook, but I'll report upsteam; clearly not a KPXC issue.

Following up, that Qt bug report was closed upstream as not being invalid.

These magic numbers come from keepassxc's minimum size hint.

It seems an overly large minimum. I doubt that was the original intention. I would suggest authors here reduce that to something much more minimal and use a regular `resize(500,800)` on startup for a default size hints.

**Comment by WhyNotHugo** [comment]
> I would suggest authors here reduce that to something much more minimal and use a regular resize(500,800) on startup for a default size hints.

Clients can't just resize themselves at any time, it has to be in reaction to a user-initiated action. This is a departure from the X11 philosophy where any client application could basically start moving all the windows around and doing whatever.

You can call Qt's function to resize a window, but I'm not sure how it's implemented for the Wayland backend. From [`xdg_toplevel::resize`](https://wayland.app/protocols/xdg-shell#xdg_toplevel:request:resize):

> This request must be used in response to some sort of user action like a button press, key press, or touch down event. The passed serial is used to determine the type of interactive resize (touch, pointer, etc).

The serial is not even optional, so I'm not sure how the function would be called. It's definitely worth a try, but I wouldn't be surprised if it doesn't work.

**Comment by davidedmundson** [comment]
>Clients can't just resize themselves at any time,

1) resize before first mapping is just setting the default size, not resizing
2) clients absolutely can resize whenever, you need to read wl_surface and see it comes from the buffer size.

xdg_toplevel::resize is about interactive resizing which is where a user drags things. That can't be started without input but that's not relevant here.

**Comment by WhyNotHugo** [comment]
I think you're right, it's perfectly possible for a client to resize before being mapped. Sorry, it's been a while since I've written any `xdg_toplevel` clients.

> clients absolutely can resize whenever, you need to read wl_surface and see it comes from the buffer size.

IIRC, you usually want to call [xdg_surface::set_window_geometry](https://wayland.app/protocols/xdg-shell#xdg_surface:request:set_window_geometry) and use whatever [xdg_toplevel::configure](https://wayland.app/protocols/xdg-shell#xdg_toplevel:event:configure) returns as your new maximum size.

You can't just send a surface of any size and expect the window to grow to that size, since the new size may be larger that what is allowed/possible.

**Comment by WhyNotHugo** [comment]
Doesn't Qt have a "set_preferred_size" call that abstracts this away?
