### ISSUE TITLE
make install DESTDIR directory seems broken

### ISSUE THREAD

**Issue by jdix531** [keepassxreboot/keepassxc#8294]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
Hi, My problem is that when going through the install process for linux I believe the directory linking is incorrect.

I used to install with no special dir using checkinstall but it seems like that isn't recommended for all cases and for me I liked the idea of installing to ~/.local directory. When I set this as mentioned in the build guide `make DESTDIR=~/.local install` in the docs rather than ~/.local/bin/keepassxc the location ends up being ~/.local/usr/local/bin/keepassxc which I don't think is how other apps handle installing there. From what I've seen it is usually ~/.local/[bin/share/lib]. I'm thinking there's a prefix not being supplanted by DESTDIR during install.

If this is expected that's cool but a tip to manage applications installing a bit differently would be appreciated. I was thinking of installing under `DESTDIR=~/.local/keepassxc` then linking all the files to ~/.local/[bin/share/lib] as needed.

Thoughts?

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Follow the linux build process setting DESTDIR during installation

## Context
[NOTE]: # ( Give us any additional information you may have. )

Here's the script I was running to test around with:

```bash
git clone https://github.com/keepassxreboot/keepassxc.git --single-branch --branch develop &>/dev/null
cd keepassxc
mkdir build
cd build
echo "running make commands"
cmake -DWITH_XC_ALL=ON -DCMAKE_BUILD_TYPE=Release -DWITH_TESTS=ON -DWITH_GUI_TESTS=ON ..
make -j8 &>/dev/null
make DESTDIR=~/.local install
```

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.1-snapshot
Revision: dab6d9408e7e37ec86cf679efd86116994ffd201

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: KDE (Kubuntu)
Windowing System: X11

**Comment by droidmonkey** [comment]
Use `-DCMAKE_INSTALL_PREFIX=~/.local`
