### ISSUE TITLE
Auto-Type does not send keystrokes to certain applications

### ISSUE THREAD

**Issue by wesnm** [keepassxreboot/keepassxc#8296]
## Overview
I have encountered two applications that Auto-Type will not send keystrokes to --  Amazon Workspaces and TigerVNC Viewer. **Keepass** is able to send keystrokes to both applications.

## Steps to Reproduce
1. Open either  application (for VNC make a full connection).
2. Select an auto-type to perform.
3. Within the timeout window, activate the application and input field.

## Expected Behavior
KeepassXC should send keystrokes to the application.

## Actual Behavior
No keystrokes appear in the target applicatiion.

## Context
KeePassXC - Version 2.7.1
Revision: 5916a8f

Qt 5.15.3
Debugging mode is disabled.

Operating system: Windows 10 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.19044

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 2.18.1

**Comment by droidmonkey** [comment]
Use virtual typing mode, read the user guide information

**Comment by wesnm** [comment]
Thank you, this works. Perhaps it could be made more useful by adding an option for an entry to use virtual typing mode for all auto-types, instead of just the custom autotype.
