### ISSUE TITLE
Autotype issue Veracrypt

### ISSUE THREAD

**Issue by funnym0nk3y** [keepassxreboot/keepassxc#8297]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
I'm not sure if this is an actual issue with keepassxc or with my configuration. 

For me the autotype filter does not correctly include sequences for a specific window. 

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Create an entry for a veracrypt password called ABC123
2. Assign a special window called veracrypt to the autotype section with a different pattern. 
3. Create a veracrypt volume with the same filename as the title. 
4. Mount that volume
5. Press autotype shortcut

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
I'd expect to see that specially created autotype sequence/entry, which is found if searched in the global database. 

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
But only the general inherited sequence is shown. I tried every possible widnow title. 

## Context
[NOTE]: # ( Give us any additional information you may have. )
I'd like to show some screenshots but can't figure out how to make keepassxc not to disappear. 

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.1
Revision: 5916a8f

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows

**Comment by droidmonkey** [comment]
Please read the user guide. It tells you how to allow screenshots and properly setup Auto-Type.
