### ISSUE TITLE
secret key with `====` not producing valid codes for TOTP

### ISSUE THREAD

**Issue by DanManN** [keepassxreboot/keepassxc#8300]
I setup an OTP key on the FreeOTP+ android app using a qr code and exported it to a text file. The key (deactivated now) looks something like this:
`HBRTOZDDGY4DGZLBGRSDQNRRGE2TANBXHE4TQNBVME4TQNBZGNSA%3D%3D%3D%3D`

When importing into keepassxc, the key was not accepted and produced the error: `You have entered an invalid secret key. The key must be in Base32 format.
Example: JBSWY3DPEHPK3PXP`. I figured the `%3D`s at the end were the problem and substituted them with `=`. This was accepted without error but would not produce valid codes.

Am I doing something wrong or is this a bug? To be clear, the secret key entry works in FreeOTP+ and the app reported standard settings for the entry otherwise: SHA-1, 6-digit, 30sec.

**Comment by droidmonkey** [comment]
Sync your system time to a valid time source. Also make sure you are using the latest version of keepassxc.

**Comment by DanManN** [comment]
Here is the version and other debug info:
```
KeePassXC - Version 2.7.1
Revision: 5916a8f

Qt 5.15.5
Debugging mode is disabled.

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 5.18.13-arch1-1

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.19.2
```

And looks like time sources are properly synced:
```
● systemd-timesyncd.service - Network Time Synchronization
     Loaded: loaded (/usr/lib/systemd/system/systemd-timesyncd.service; enabled; preset: enabled)
     Active: active (running) since Sun 2022-07-24 17:32:05 EDT; 3h 25min ago
       Docs: man:systemd-timesyncd.service(8)
   Main PID: 534 (systemd-timesyn)
     Status: "Contacted time server 45.79.111.114:123 (2.arch.pool.ntp.org)."
      Tasks: 2 (limit: 38262)
     Memory: 2.0M
     CGroup: /system.slice/systemd-timesyncd.service
             └─534 /usr/lib/systemd/systemd-timesyncd
```

**Comment by droidmonkey** [comment]
If the Base32 is accepted it is very unlikely to be a code bug. The single most prevalent error with TOTP (99.9%) is system time being off. Make sure you actually sync the time using `timedatectl` (https://linuxhint.com/sync-time-ntp-server-linux/)

**Comment by DanManN** [comment]
Looks like time sync is correct:
```
               Local time: Mon 2022-07-25 09:34:56 EDT
           Universal time: Mon 2022-07-25 13:34:56 UTC
                 RTC time: Mon 2022-07-25 13:34:56
                Time zone: America/New_York (EDT, -0400)
System clock synchronized: yes
              NTP service: active
          RTC in local TZ: no
```
I should note also, other totp entries I added to keepassxc are working fine. It is just this one that is causing problems.

**Comment by droidmonkey** [comment]
That would indicate that the secret you are extracting from FreeOTP is not actually the secret. Re register your OTP account and use the provided secret from the vendor.

**Comment by DanManN** [comment]
I tried that. The secret key was in a similar format and still didn't work. Perhaps the default algorithm settings are the problem? How would I know which settings to try?

**Comment by droidmonkey** [comment]
Have no idea, what service / website are you getting this secret key from?

**Comment by DanManN** [comment]
Ok so I just realized its an HOTP secret not a TOTP secret. Does keepassxc support those?

**Comment by DanManN** [comment]
Ok this is basically a duplicate of https://github.com/keepassxreboot/keepassxc/issues/4371 now.
