### ISSUE TITLE
[FR] Allow optionally use of single click in Auto-Type select screen

### ISSUE THREAD

**Issue by Offerel** [keepassxreboot/keepassxc#8301]
## Summary
If the Auto-Type select screen is open, for selecting one of the entries to insert in to a Credential field, currently I have to double click the entry to start the sequence. In some cases, this can lead to additional click which causes trouble with the underlying window. To prevent that, it would be better to start a sequence with a single click from within the AutoType select dialog.

## Context
Sometimes I trigger not only 2 click, and instead of this accidentally additional click, which can interact with the underlying window. On the other side, sometimes I have to use the standard Keepass 2 application on Windows, where the single click is the standard for this window. To not confuse other user which get used to the current behaviour, the single click should be a optional thing somewhere in the settings.

**Comment by droidmonkey** [comment]
We recommend you not use your mouse at all for this dialog. It is laced with very helpful keyboard shortcuts. We purposefully removed single click action for two reasons: 1) it conflicts with the advanced usage of this upgraded dialog, 2) most end users don't expect a single click to be their "last chance" which is not good for a dialog like this. 

We have decided to not support single click even with an option. Recommend using keyboard shortcuts, I never click in this dialog. 

Enter -> type selected line
Up/down arrow -> choose line item
Ctrl+1 -> type {username}
Ctrl+2 -> type {password}
Ctrl+3 -> type {totp}
