### ISSUE TITLE
Password strength indicator column causes hangs/freezes for extremely long passwords

### ISSUE THREAD

**Issue by jkhsjdhjs** [keepassxreboot/keepassxc#8303]
## Overview
[TIP]: # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
KeePassXC offers a password strength column, which, when enabled, rates the strength of a password with a green, yellow or red square.
This indicator causes KeePassXC to freeze/hang when calculating the strength of extremely long passwords (5000+ characters).

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Create a new database
2. Make sure the password strength indicator column is enabled
3. Create a new entry and fill in more than 5000 arbitrary characters
4. Click OK. KeePassXC should hang because the View that would be shown next would be the list of entries, thus it is calculating the password strength.
5. Wait and lock the database (or kill KeePassXC, depending on the length it may hang for several minutes)
6. Unlock the database. KeePassXC should hang again for the same reason.

## Context
[NOTE]: # ( Give us any additional information you may have. )
Of course no sane person would use passwords that long, but I'm using the SecretService integration and some applications just store data that long (or even longer) in the password field.
Thus, whenever an entry of the SecretService group with a long password value would be displayed as part of the search results, KeePassXC hangs.

As a workaround I disabled searching the SecretService group.
Other workarounds are to disable the password strength indicator or to move the problematic entry to the recycling bin (as this group also isn't searched).

## System Information
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.1
Revision: 5916a8f

Qt 5.15.5
Debugging mode is disabled.

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 5.18.14-arch1-1

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.19.2

**Comment by droidmonkey** [comment]
Fixed for 2.7.2. For now, go to the advanced tab when editing entry and disable reports for the entries with very long passwords. 

https://github.com/keepassxreboot/keepassxc/pull/7748

**Comment by jkhsjdhjs** [comment]
Ah, I see. Thanks!
