### ISSUE TITLE
Small indicator of truncation of a shown password

### ISSUE THREAD

**Issue by ahreurink** [keepassxreboot/keepassxc#8304]
## Summary
When selecting a password from the home UI the password can be shown using the eye symbol. If the password does not fit the space up untill "Expriration" it is truncated. 

## Examples
A small indicator of truncation, such as three dots.

## Context
I have had the situation where copy pasting the password was not possible. Because the password was auto generated I did not realize it was being truncated and it cost a while to figure it out. I imagine more people have this issue.

Note: If anyone can tell me how to screenshot KeepassXC I can upload an example.

**Comment by droidmonkey** [comment]
This was discussed before and we can't do it for a variety of reasons. But if you are copying the password just use the keyboard shortcut or toolbar icon. Ctrl+C when the entry is selected.

**Comment by ahreurink** [comment]
Hey Jonathan thank you for the followup. I didn't see that, sorry.

**Comment by smithtim** [comment]
I hit this same issue.  Only the first part of the password was shown, with no indication that it had been truncated.

@droidmonkey, you mentioned that this was discussed before.  Where was the previous discussion?

**Comment by droidmonkey** [comment]
Update to 2.7.4 and you'll get a nice scrollbar for your super long password

**Comment by smithtim** [comment]
That worked, thanks!
