### ISSUE TITLE
--silent option for CLI

### ISSUE THREAD

**Issue by rfc1459** [keepassxreboot/keepassxc#831]
When using `keepassxc-cli show` the password prompt for the database is sent to stdout. This makes integrating keepass-cli into scripts problematic.

## Expected Behavior
The database password prompt should be sent to stderr or directly to the invoking pty, while only the entry itself is sent to stdout.

## Current Behavior
The database password prompt _and_ the entry are sent to stdout.

## Possible Solution
keepassxc-cli should send the database password prompt either on stderr or on the invoking pty, leaving stdout for the requested entry

## Steps to Reproduce (for bugs)
1. `keepassxc-cli $db $entry 2>/dev/null`
2. `keepassxc-cli $db $entry >/dev/null`

Step 1 prints both the database password prompt and the entry, step 2 prints nothing.

## Debug Info
KeePassXC - Version 2.2.0
Revision: caa49a8ef3ee28ed478192389b21d61107b3b8e0

Libraries:
- Qt 5.5.1
- libgcrypt 1.6.5

Enabled extensions:
- KeePassHTTP
- Auto-Type
- YubiKey

**Comment by louib** [comment]
@rfc1459 what about an option to hide the prompt? `-h`, `--hide-prompt` maybe.

**Comment by rfc1459** [comment]
That would be fine (I already print my own prompt in the scripts since my workaround for this issue is a rather crude `keepassxc-cli show $k $e | tail -n 1`).

**Comment by louib** [comment]
@rfc1459 the `--quiet` option was merged into develop. You can go ahead and give it a try!
