### ISSUE TITLE
Copy specific attributes by double clicking - no longer possible

### ISSUE THREAD

**Issue by MrStrenggeheim** [keepassxreboot/keepassxc#8314]
## Summary
In the newest version of KeePassXC it's no longer possible to double click any attribute (eg password or username) to copy it.
Instead it just opens the edit window for this entry. (which only occured when double cklicking on the name of the entry)

## Context
I loved, that there were two shortcuts (one with keyboard and one with mouse).

Was there a reason for removing this feature?
I would love to have it back.

**Comment by droidmonkey** [comment]
Go to application settings, security page, turn it back on in there under convenience.
