### ISSUE TITLE
keepassxc 2.7.1 Notes field is not scaling any more with preview panels sizes

### ISSUE THREAD

**Issue by slartibart70** [keepassxreboot/keepassxc#8315]
Have an entry with lots of notes text
open View > Show preview panel
click on the entry with notes

Notes are displayed and scollable in the notes field.
But, resizing the preview panel does not scale the notes field according to the height of the preview panel as it did before

This is even more of a problem when using the new theme, in classic theme we still see where the borders of the notes field are

**Comment by slartibart70** [comment]
to be more exact:

the notes field does scale a bit (e.g. making it smaller when the panel shrinks and vice versa)
But, it's limited in max size which is annoying

**Comment by droidmonkey** [comment]
Already fixed for 2.7.2
