### ISSUE TITLE
Import/export passwords in keepass format for all browsers

### ISSUE THREAD

**Issue by ghost** [keepassxreboot/keepassxc#8316]
## Overview
1. Importing and exporting browser passwords must have a universal and encrypted password pattern. There is a technical discussion about Mozilla Firefox using the encryption format here: [Encryption of passwords imported into a file](https://connect.mozilla.org/t5/ideas/encryption-of-passwords-imported-into-a-file/idi-p/5389).  - reference here: https://github.com/privacycg/proposals/issues/33
2. The problem with passwords today is that every browser implements the way to import and export passwords.
3. I argue that to have good security/privacy of user data we have to have a universal standard in importing/exporting passwords.
4. As a matter of technological, individual, philosophical and rational freedom
5. I believe that for this to be done, we have to adopt the standard of open solutions with MIT/GPL open licenses, etc.
6. Keepass is an open source solution for managing passwords, it would be nice to have the same file format for all web browsers.
7. When I refer to a universal standard for importing/exporting passwords, I say that it would be interesting, as I said before, to adopt the keepass open format for this.
8. Keepass has been around for a long time and is a well-established, popular solution known all over the world.
9. Adopting the Keepass format for importing/exporting passwords gives people more freedom. Well, Keepass software is licensed under the GPL - the same license as Linux. Which, in theory, will always be available openly.
10. It's 2022, and the bookmarks format is the same as it was in 1999. So why don't we have the same Keepass format for importing/exporting passwords in all browsers? - reference here [Netscape bookmarks](http://fileformats.archiveteam.org/wiki/Netscape_bookmarks)

## Steps to Reproduce
1. I would like to know if this idea is good or bad
2. My goal is to help this communities: PrivacyCG, Solid, W3C, WIGC, WebAuthn, KeepPass, Browsers(Brave, Vivaldi, Opera, Mozilla Firefox, Libre Wolf, Google Chrome etc)

## Expected Behavior
1. Import/export passwords in keepass format for all browsers
2. I would like the Keepass community to help me, give me strength, an incentive *I made a proposal for format Keepass to be adopted by all browsers*

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

## Context
1. https://github.com/privacycg/proposals/issues/33
13. https://connect.mozilla.org/t5/ideas/encryption-of-passwords-imported-into-a-file/idi-p/5389

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows

**Comment by droidmonkey** [comment]
Recommend to not waste your time. This is never going to happen, and frankly there is absolutely no incentive to browser programmers to incorporate the keepass format.

**Comment by ghost** [comment]
@droidmonkey Hi! How are you? So... I liked your comment... but I'll leave a note that I forgot to comment!

#### 1. comment
- The main objective of having a universal password import and export format for all browsers is to make life easier for users. 
- This reminds me of some historical facts - for example, lisp had several versions - programmers made commonlisp - which had features common to different implementations of lisp. 
- This case that I mentioned historically also happened with markdown - there are several formats of markdown - they even created a universal format called common-markdown. 
- As you can see, I mentioned 2 historical facts of a universal format that occurred as lisp/markdown - I could mention opendoc - which is the universal open text format that was created because there were proprietary formats that you would hardly be able to open your file without having to use proprietary software.
- by which I mean there is a possibility to have a universal password format - if browsers want to have better compatibility for other browsers. The argument I use here is the same for lisp/common-markdown or for opendoc/bookmark-format.

#### 2. So, in summary, my arguments are these 4:
1) greater compatibility for importing/exporting passwords in different browsers as there is universal and open Keepass format
2) ensure the password is always read without proprietary software - as long as it is in an open Keepass format
3) makes the user's life easier - no matter the browser - the password will always be read/imported/exported to any browser
4) it better integrates keepass together with the different existing browser communities - which reinforces the free software idea "foss - free and open/libre software"


#### 3. Summarizing my arguments on a technical level
1. Comparative argument and historical evidence: I talked about lisp/common-markdown/open doc to prove the importance of a keepass format as a universal password format for different browsers. I talk about that, talking about how common-lisp / common-markdown and opendoc are universal and historically important formats. I talk about how and why they became universal formats - this same reason I mentioned could be used in keepass.
2. cause and consequence argument: I spoke of the causes and consequences of having a universal file format through a comparison and historical evidence to confirm this. I mentioned the benefits and also the problems involved in this implementation.
3. argument from authority: I talked about universal formats like common-lisp/common-markdown to be my basis for argumentative authority - I said they both did this for the same reasons I presented earlier.
