### ISSUE TITLE
Default to copy when moving password outside its database

### ISSUE THREAD

**Issue by NicoHood** [keepassxreboot/keepassxc#8317]
## Summary
I keep a 2nd database with a subset of my passwords, that I use for mobile only. I drag and drop them to the other database. I must make sure to hit CTRL in order to copy, not move the entry. As windows handels copying files to usb sticks, I suggest also defaulting to copy (instead of move) when crossing database borders

**Comment by droidmonkey** [comment]
#172 covers this. The unfortunate thing with switching the default drag/drop behavior is that half the people want the current behavior and half want yours. IMO moving the entry is the correct and expected default behavior. It is also consistent with dragging to a group in the same database.
