### ISSUE TITLE
Snap package won't open remote database on Ubuntu 22.04

### ISSUE THREAD

**Issue by NicolasGoeddel** [keepassxreboot/keepassxc#8319]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

After a fresh snap install I can not open the database on my remote Nextcloud account. With the DEB package it works flawlessly.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Create fresh user account on Ubuntu 22.04
2. `sudo snap install keepassxc`
3. Connect Nextcloud account using the Ubuntu account manager (not the nextcloud desktop client)
4. Start Keepassxc, open database and choose the database in the Nextcloud folder
5. Wait for minutes and some more minutes and finally kill the process because it does not react anymore.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
After choosing the database it should ask immediately for the password and open it.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
The application just freezes.
The only output it gave, was this:
```
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
Qt: Session management error: Could not open network socket
```

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.1

Betriebssystem: Ubuntu 22.04 LTS
CPU-Architektur: x86_64
Kernel: linux 5.15.0-41-generic

Aktivierte Erweiterungen:
- Auto-Type
- Browser-Integration
- SSH-Agent
- KeeShare
- YubiKey
- Secret-Service-Integration

Kryptographische Bibliotheken:
- Botan 2.19.1

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: Gnome
Windowing System: Wayland

**Comment by droidmonkey** [comment]
You need to give the snap proper permission ls to access remote storage. We won't be making any more improvements to the snap interface, we recommend using flatpak.

**Comment by NicolasGoeddel** [comment]
> You need to give the snap proper permission ls to access remote storage. We won't be making any more improvements to the snap interface, we recommend using flatpak.

That's okay. I also do not like snap very much. However I am going with the DEB package for now.
