### ISSUE TITLE
More than one OTP

### ISSUE THREAD

**Issue by andusvan** [keepassxreboot/keepassxc#832]
Possibility to create OTPs like password entries.

## Expected Behavior

We are using keepassxc to store the Password of our customers in a secure way.
Many of our customers are using one-time-passwords (OPTs) for their logins and
we are currently generating these on your mobile phones.
It would be nice, if we could store and generate the OTPs like the other passwords
(in the list) and generate on showing the entry.

## Current Behavior

Only one (global) OTP possible.

**Comment by phoerious** [comment]
I'm not sure I understand what it is that you want. You can store as many OTP seeds as you want.

**Comment by andusvan** [comment]
Ok, my fault. I did not realize, that the OTPs are stored with the currently selected entry.
But the implementation here is a little bit confusing. Why "hiding" the OTPs in the sub menu of the entry and not showing it in the entries data like the other passwords?
This would be much clearer and user friendly... 
Or is there a special reason for this?

**Comment by phoerious** [comment]
The seeds are store as advanced string fields. The OTPs themselves are generated on the fly when you click that menu entry (because that's how OTPs work).

**Comment by andusvan** [comment]
Ok I understand that and I'm familiar with TOPTs. But why can't I see in the detailed entry view, that the entry has OTP data stored?
In my workflow I switch constantly between different entries to get passwords and possibly additional information from the comment section. It would be perfect, if I open an entry to see the currently generated OTP password like any other password too...
If it's not possible to show the OTP password directly, it would be nice have a button there to open the generator (if it has OTP configured)...

Ever thought about a "read-only" view of the password without the possibility to (accidently) change the values?

BTW: Because I am constantly switching between entry, if would nice to have an option to always show the tree, but that maybe another issue for the wishlist...

**Comment by phoerious** [comment]
If you click on "Advanced", you will see entries "TOTP Seed" and "TOTP Settings".

**Comment by andusvan** [comment]
No, I want the current OTP password itself or a button to generate it.
Why doing 2-3 additional clicks, if it could be shown directly?

**Comment by phoerious** [comment]
I don't understand what you want. Where do you want a button? On the entry edit screen? Well, that's for editing the entry, not for showing passwords. Besides, you shouldn't store the OTP secret in the same database as the password, otherwise you are not doing 2FA anymore.

**Comment by TheZ3ro** [comment]
I think @andusvan want to see the current OTP token in the main window.

This can be an addition to the preview panel issue.

**Comment by phoerious** [comment]
An OTP can be shown in the (not yet existing) preview panel. But without such a panel, it doesn't really make sense to show it anywhere.

**Comment by andusvan** [comment]
Yeah, but I'm using the edit screen to show the entry because there isn't a special screen for only showing the entry. And I must use the screen to show any additional data from the comment section.
And this is the reason that I want a button on this screen.

Regarding the "2-factor authentication": Is the OTP secret not stored in the same database? Where is it stored? If I am looking at it strictly: isn't combining an OTP and a normal password in one program violating 2FA?

**Comment by andusvan** [comment]
Ok, I read the request for the "preview pane". If the OTP would be shown in the preview pane, it would be perfect!
I'm closing the issue, because we have more then one OTP already (sorry for that) and the preview pane would solve it. I will add a comment to the preview pane issue...
Thanks!
