### ISSUE TITLE
option for Grouped characters in Generator

### ISSUE THREAD

**Issue by DriesMoo** [keepassxreboot/keepassxc#8320]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
Have the option for the generator to automatic split up pw in set groups. Random or on a set amount

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )
 A option that allows for grouping.
 So a number selection
 And a box to input the seperator 
 random option: A range (group Length: 3-8 for example (which would make groups between 3-8 characters length) 
 

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )

It makes reading pw easier for like shared stuff like netflix. or wifi pw etc.

**Comment by droidmonkey** [comment]
Use the passphrase generator
