### ISSUE TITLE
Browser Integration Linux Brave Nightly doesn't work

### ISSUE THREAD

**Issue by lts20050703** [keepassxreboot/keepassxc#8322]
## Overview
Browser Integration Linux Brave Nightly doesn't work because KeePassXC **DOES NOT** put `org.keepassxc.keepassxc_browser.json` inside `~/.config/BraveSoftware/Brave-Browser-`**`Nightly`**`/NativeMessagingHosts/`

## Steps to Reproduce
1. Go to Browser Intergration 
2. Enable for Brave
3. Navigate to `~/.config/BraveSoftware/Brave-Browser/NativeMessagingHosts/` to observe that KeePassXC put `org.keepassxc.keepassxc_browser.json` in there
4. Navigate to `~/.config/BraveSoftware/Brave-Browser-`**`Nightly`**`/NativeMessagingHosts/` to observe that KeePassXC **DID NOT** put `org.keepassxc.keepassxc_browser.json` in there

## Expected Behavior
KeePassXC detect that I'm using Brave Nightly and put `org.keepassxc.keepassxc_browser.json` inside `~/.config/BraveSoftware/Brave-Browser-`**`Nightly`**`/NativeMessagingHosts/`

## Actual Behavior
KeePassXC put `org.keepassxc.keepassxc_browser.json` inside `~/.config/BraveSoftware/Brave-Browser/NativeMessagingHosts/`

## Context
KeePassXC - 2.7.1
KeePassXC-Browser - 1.8.1
Browser: Brave Version 1.44.8 Chromium: 104.0.5112.69 (Official Build) nightly (64-bit)

Operating System: Linux x86_64 (KDE Neon)
Desktop Env: KDE
Windowing System: X11

**Comment by droidmonkey** [comment]
You need to use the custom browser option for nightly builds. We do not support nightly builds, they break things all the time.
