### ISSUE TITLE
QR code is not recognized by Yubico Authenticator

### ISSUE THREAD

**Issue by thyxNY** [keepassxreboot/keepassxc#8326]
## Summary
QR code is not recognized by Yubico Authenticator

Yubico Authenticator can recognize code from websites or images displayed on the screen. But Yubico Authenticator can't recognize code from Keepassxc (TOTP -> Show QR Code).

Maybe this image is too small?

--

KeePassXC - Version 2.7.1
Revision: 5916a8f

Qt 5.15.3
Debugging mode is disabled.

Operating system: Windows 10 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.19044

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 2.18.1

**Comment by droidmonkey** [comment]
You can resize the QR code box if you need to, but the size is not relevant. The QR code is the otpauth url string, which is what every website uses and works fine with other apps like Google authenticator and andOTP.

**Comment by droidmonkey** [comment]
I just tested yubico authenticator and keepassxc totp qr code and it worked flawlessly.

**Comment by thyxNY** [comment]
I didn't know that I can resize this window with qr code. But even if this image is much bigger my yubico authenticator can recognize this qr code :-(

**Comment by phoerious** [comment]
Did you dial in the correct settings, i.e. number of digits etc.?

**Comment by thyxNY** [comment]
Yubico authenticator can recognize QR codes from websites or photos. Yes, I can write to yubico authenticator TOTP code and it works correctly, yubico authenticator identifies QR from websites and pictures but can't recognize code from KeepassXC->TOTP->Show QR Code.
