### ISSUE TITLE
firefox cannot connect to keepassxc

### ISSUE THREAD

**Issue by joy4eg** [keepassxreboot/keepassxc#8328]
## Overview
After some updates, keepassxc browser extension suddenly stopped working.
Did a quick [research](https://github.com/keepassxreboot/keepassxc-browser/wiki/Troubleshooting-guide), and it turns out that extension tries to load `libcrypto.so.1.1` library which is not available by default (and not listed as dependency as well).

## OS/Versions
- Fedora 36 (x86_64)
- KDE, Xorg.
- Firefox 103
- KeePassXC 2.7.1
- KeePassXC-Browser: 1.8.1

## Fix
Install `libcrypto.so.1.1` manually via the package manager (`sudo dnf install openssl1.1`)

Not sure about is it the right place to post that kind of issues or not. Anyway, having additional information (for instance, in README) somewhere would be nice.

**Comment by droidmonkey** [comment]
Please raise a bug with Fedora maintainers, we don't manage dependencies in their package system.
