### ISSUE TITLE
Double-click to copy a protected advanced attribute copies ●●●●●●

### ISSUE THREAD

**Issue by whisdol** [keepassxreboot/keepassxc#8329]
## Overview
Double clicking a hidden, protected advanced attribute from the database view copies "●●●●●●" to the clipboard instead of the actual value.

## Steps to Reproduce
1. Create a new entry with an advanced attribute, check the `Protected` box
2. View the entry in the database view
4. From the `Advanced` tab, double-click the hidden value to copy
5. Paste into a text field

## Expected Behavior
The value of the attribute is pasted into the text field

## Actual Behavior
The string "●●●●●●" (six dots) is pasted into the text field

## Context
Workaround: Show the protected attribute first by clicking the `eye`-icon

KeePassXC - Version 2.7.1
Revision: 5916a8f

Operating System: Windows 11 (also tested on macOS)

Qt 5.15.3
Debugging mode is disabled.

Operating system: Windows 10 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.22000

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 2.18.1

**Comment by droidmonkey** [comment]
Fixed in upcoming 2.7.2
