### ISSUE TITLE
Dead keys not working in GNU/Linux

### ISSUE THREAD

**Issue by otyu** [keepassxreboot/keepassxc#833]
On GNU/Linux (debian 9 stretch, running X11), it is impossible to input text using dead keys, such as the characters `â`, `^` and so on.

## Expected Behavior

Dead keys and their compose rules should work according to the appropriate compose file (e.g. `$HOME/.XCompose`), i.e. typing `^`+`a` should input `â` and so on.

## Current Behavior

Dead keys produce no effect, e.g. typing `^`+`a` produces `a` instead of `â`, `^`+`^` produces nothing instead of `^`; typing `^`+`(space)` produces ` ` instead of `^`.

## Steps to Reproduce (for bugs)

This bug happens to me in the following environments

- Using a keyboard layout with dead keys and ibus 1.5.14 as input method, compose rules set in `$HOME/.XCompose`
- Using the same keyboard layout, but with the ibus daemon turned off.

## Context

Remark: This problem is NOT present while using keepassx 2.0.3 (which uses Qt 4.8.7) nor any other gtk programs. Therefore, it is probably an incompatibility with Qt5 and some input configuration or composing rule (not ibus, since the problem persists without it).

Possibly related upstream qt bugs:
- [QTBUG-28183: Dead keys aren't working on Qt5](https://bugreports.qt.io/browse/QTBUG-28183)
- [QTBUG-32461: The 'compose' platform input plugin doesn't detect locale aliases](https://bugreports.qt.io/browse/QTBUG-32461)
- [QTBUG-56452: Some compose key sequences do not work with the "compose" input method plugin](https://bugreports.qt.io/browse/QTBUG-56452)
- [QTBUG-49438: Dead keys don't work on Qt5.5.1](https://bugreports.qt.io/browse/QTBUG-49438)
- [QTBUG-42181: Use libxkbcommon compose key API in QComposeInputContext plugin.](https://bugreports.qt.io/browse/QTBUG-42181)
- [QTBUG-54792: Compose key support missing in QtWayland](https://bugreports.qt.io/browse/QTBUG-54792)

## Debug Info

KeePassXC - Version 2.2.0
Libraries:
- Qt 5.9.0
- libgcrypt 1.6.1

Operating system: Debian GNU/Linux 9 (stretch)
CPU architecture: x86_64
Kernel: linux 4.12.4

Enabled extensions:
- KeePassHTTP
- Auto-Type
- YubiKey

**Comment by phoerious** [comment]
This is definitely a Qt bug or a configuration bug on your system. We can't really do anything about it.
