### ISSUE TITLE
Gnome Drive Integration Write Fails

### ISSUE THREAD

**Issue by rrowlands** [keepassxreboot/keepassxc#8330]
## Overview 
When using a database located on Google Drive via the Gnome integration, writing to an entry produces error message "Writing the database failed: input/output error'.

## Steps to Reproduce
1. On Ubuntu 20.04.4 LTS, connect to Google Drive using the Gnome integration
2. In Keepassxc v2.7.1 (installed via snap) open a database file from Other Locations -> Networks -> Drive.
3. Attempt to edit an entry

## Context
Database file is located at:
/run/user/1000/gvfs/google-drive:host=gmail.com...<bunch of random characters>

Not sure if I do not have some prerequisite software installed? Here is the output from my console which has booted Keepass:

```
[error] cannot open locale definition file `en': No such file or directory
Qt: Session management error: None of the authentication protocols specified are supported
QFSFileEngine::open: No file name specified
  OpenType support missing for "Saab", script 13
QFSFileEngine::open: No file name specified
QFSFileEngine::open: No file name specified
QFSFileEngine::open: No file name specified
```

I also get "Unable to open file" if I close the database and attempt to open the same, previously opened database again.

Related tickets:
- https://github.com/keepassxreboot/keepassxc/issues/1937
- https://github.com/keepassxreboot/keepassxc/issues/803

Notice that in my scenario the database is not opening in read-only mode anymore.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.1
Revision: 5916a8f
Distribution: Snap

Qt 5.15.3
Debugging mode is disabled.

Operating system: Ubuntu Core 20
CPU architecture: x86_64
Kernel: linux 5.17.5-76051705-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.12.1

**Comment by droidmonkey** [comment]
Use direct write saves, please read the user guide on alternative saving methods.

**Comment by rrowlands** [comment]
@droidmonkey Fixed my issue! Here's $10.

![image](https://user-images.githubusercontent.com/1326328/184909157-dd731ecf-5b9c-4959-89bd-36207a5cc779.png)
