### ISSUE TITLE
Browser Integration not working for Steam Deck browsers (discover store)

### ISSUE THREAD

**Issue by godSaysHODL** [keepassxreboot/keepassxc#8331]
## Overview
Cannot get browser integration working on browsers in Steam Deck OS (arch + KDE plasma fork)

## Steps to Reproduce
1. install browser from Discover store
2. enabled browser integration in KeepassXC app (from discover store).
3. install plugin and attempt to connect. 

## Expected Behavior
Database should connect

## Actual Behavior
failed to connect

## Context
I even did manual entry of the browser config folder. still doesn't work

[NOTE]:
KeePassXC - Version 2.7.1
Revision: 5916a8f
Distribution: Flatpak

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux SteamOS 3
Desktop Env: Gnome/KDE Plasma

**Comment by droidmonkey** [comment]
We don't support the steam OS so unlikely to be able to resolve this. What browser are you trying to use?

**Comment by godSaysHODL** [comment]
I used brave browser. I got it working by following this [guide](https://github.com/keepassxreboot/keepassxc-browser/issues/1631#issuecomment-1153736766), with a few modifications for Brave browser's flatpak.

**Comment by droidmonkey** [comment]
We don't support browsers running in a container (flatpak or snap) but great you got it working. The xdg folks are finishing a native messaging portal for snaps and flatpak (which is what you implemented as work around) to use so this will be a non issue in the future.

**Comment by Knochi** [comment]
Hello,

>The xdg folks are finishing a native messaging portal for snaps and flatpak (which is what you implemented as work around) to use so this will be a non issue in the future

message from the future (2+ years), seems like flatpak or snap is still an issue.
What happend to that?
