### ISSUE TITLE
Button "Copy Password" not working after URL clicks 

### ISSUE THREAD

**Issue by lammermann** [keepassxreboot/keepassxc#8333]
## Overview
Button "Copy password" not working after URL clicks

## Steps to Reproduce
1. Click on URL -> browser opens with the page from url
2. Switch to KeePassXC, Click on Button "Copy username to clipboard"
3. Switch to browser, CRTL-V -> user copied to browser
4. Switch to KeePassXC, Click on Button "Copy password to clipboard"
5. Switch to browser, CRTL-V -> URL copied but password expected

## Expected Behavior
Button "Copy password to clipboard" from KeePassXC is expected to get password, not URL.

## Context
This is most likely closely connected to #7799 as it seems that button is triggering the same action as crtl-c instead of calling an action that copies the password 

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.1
Qt 5.15.3
Debugging mode is disabled.
Operating system: Linux
Desktop Env: XFCE+i3
Windowing System: X11

**Comment by droidmonkey** [comment]
Fixed in upcoming 2.7.2

**Comment by lammermann** [comment]
Great. Thanks for this really useful tool
