### ISSUE TITLE
Getting error writing database failed, access denied after saving changes

### ISSUE THREAD

**Issue by brmb** [keepassxreboot/keepassxc#8334]
## Overview
KeepasXC 2.7.1 started returning such error when I tried saving passwords/notes modification:
```
Writing the database failed: Cannot open destination file: Access is denied.
Backup database located at C:/Users/lukas/AppData/Local/Temp/KeePassXC.XXXXXX
```

I had `Backup database file before saving` and `Use alternative saving method (_Temporary file moved into place_)` enabled.

If I disabled `Use alternative saving method (_Temporary file moved into place_)` option, I get such error:

```
KeePassXC has failed to save the database multiple times.
This is likely caused by file sync services holding a lock on the save file.
Disable safe saves and try again?
```

Obviously, if I disable it, the story starts all over again.

If I use `Directly write to database file (dangerous)`, I get such error:
`Writing the database failed: Access is denied.`

So obviously KeePassXC does not have access to overwrite the existing file. Nothing has altered from my end regarding permissions. 

There are no OS customizations in place, no external anti-virus software or anything additional to default Windows security. Tried excluding directories from Windows Virus Scanner but it did not help.

Thing is, I saw a lot of issues like this here, but a lack of ownership from product owners to try and suggest a few things from OS level. Most likely this could be Windows permissions related, strangely it was working before 🤔 

## Steps to Reproduce
1. Edit password/notes.
2. Save it.

## Expected Behavior
Expected to get saved flawlessly.

## Actual Behavior
Returns errors described above.

KeePassXC - Version 2.7.1
Revision: 5916a8f

Operating System: Windows
Windowing System: 10

**Comment by droidmonkey** [comment]
> Nothing has altered from my end regarding permissions.

Impossible. The error returned is from the operating system. You either do not have permission to write to the database file anymore OR it is being held open by another process. You can solve the second with a reboot. You solve the first by adjusting your file permissions. 

> but a lack of ownership from product owners to try and suggest a few things from OS level

We don't control your operating environment. If it is obvious what is happening we usually provide a tech tip. Otherwise it is on you to resolve. If there is a bonefide fault with the program (in your case it seems to be working as designed) then there is nothing we can do.

**Comment by SynapseScribe** [comment]
i get access denied error sometimes, randomly on windows 11 25H2. it's definetely not a permission issue, but something else
