### ISSUE TITLE
Implement bridge API

### ISSUE THREAD

**Issue by vitonsky** [keepassxreboot/keepassxc#8338]
I need to use passwords from keepassxc DB to launch some applications. Could you implement bridge SDK or at least API and docs how it to use?

I await something like with browser extension:
- my thirdparty program send auth request to keepassxc
- i will approve request and authorize thirdparty application
- application will send request to send data by title or by URL
- keepassxc will send this data for authorized applications
- application will use this credentials to run some another program, and then remove from own memory

Maybe you have docs for exists API for browsers extension?

**Comment by droidmonkey** [comment]
The browser integration api is documented over in that repository. We also support secret service via freedesktop.org dbus interface. There are several projects out there that can speak the browser api on various languages for integration.
