### ISSUE TITLE
Add context menu item to move groups up and down

### ISSUE THREAD

**Issue by p2635** [keepassxreboot/keepassxc#834]
Can we add a simple entry to the context menu to move entries up and down?

## Current Behavior
We can drag entries into the right ordering/positioning but it depends on mouse accuracy.

## Possible Solution
New right click entries:
1. Move entry up
2. Move entry down

**Comment by droidmonkey** [comment]
As opposed to sorting based on a column?

**Comment by p2635** [comment]
I was referring more to the Entry Groups (the folders on the left side) rather than the entries themselves.

But yeah sorting would also be good for normal entries!

**Comment by dschrempf** [comment]
Hello,

I agree; in my opinion, a button or function to sort the entries alphabetically is even more important.

**Comment by droidmonkey** [comment]
Closed in favor of #2044
