### ISSUE TITLE
Just One Keyboard Key To Copy Username And Password

### ISSUE THREAD

**Issue by wh81752** [keepassxreboot/keepassxc#8340]
## Summary
I use CTRL-C and CTRL-B for copying password and username exclusively. It forces me to switch the context four times, i.e. `browser --> keepassxc (username) --> browser --> keepassxc (password) --> browser.
`
This could be shortened down to two
`browser --> keepassxc (username & password) --> browser
`
if there would be a "super"-keystroke allowing me to copy username and password together. Then I would navigate to the browser and use CTRL-C and CTRL-B for copying password and username respecitvely.

## Context
It matters not only for me but I guess especially for olderly people where "context switches" are more than problematic. Driven away from the current context by popping-up or popping-down windows is anoying and confusing.

Of course: The feature requested above will not solve this problem, but reduce it to the minimum necessary.

**Comment by droidmonkey** [comment]
Please take a read of our user guide. You should be using our browser extension and reduce this to zero keys or Auto-Type (which can also be requested from the browser extension) and then one key press will fill the form for you as well.
