### ISSUE TITLE
KPXC not applying system theme

### ISSUE THREAD

**Issue by itsCryne** [keepassxreboot/keepassxc#8342]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
Despite the Theme being set to `Automatic` and the system theme being `Dark` KPXC displays its light theme.

https://i.imgur.com/oty1Ewf.png
https://i.imgur.com/S573cX7.png

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Set your system theme to a dark theme
2. Set KPXCs theme to "Automatic"
3. (Just to be sure it does in fact keep the light theme) restart KPXC

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
KPXC shoud use its dark theme

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
KPXC uses its light theme

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
```
KeePassXC - Version 2.7.1
Revision: 5916a8f

Qt 5.15.3
Debugging mode is disabled.

Operating system: Pop!_OS 22.04 LTS
CPU architecture: x86_64
Kernel: linux 5.18.10-76051810-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.19.1
```

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: Gnome
Windowing System: X11

**Comment by droidmonkey** [comment]
Gnome bug, they don't follow their own standards https://github.com/keepassxreboot/keepassxc/issues/7817#issuecomment-1092210362
