### ISSUE TITLE
Can't copy and paste at all

### ISSUE THREAD

**Issue by vbnmvhnhjk** [keepassxreboot/keepassxc#8343]
## Overview
Copy and paste is broken -- from passwords to notes. Nothing copies to the clipboard.

## Steps to Reproduce
1. Try to copy a password.
2. Try to paste it.
3. Cry.

## Context
I believe this is related to a bug in Qtile. The only similar post I could find about it is here: https://github.com/qtile/qtile/issues/1542. The bug exists regardless of the version of Keepassxc I've tried, and exists across different package types, eg. deb, flatpak, appimage.

I found that page because I opened Keepassxc in a terminal and the error code thrown when copying is "QXcbClipboard::setMimeData: Cannot set X11 selection owner"

[NOTE]: # ( Paste debug info from Help → About here )
I can't paste in debug info because copy and paste is broken, but I'm using 2.7.1 flatpak version.

[NOTE]: # 
Operating System: Linux PopOS
Desktop Env: Gnome
Windowing System: X11

**Comment by droidmonkey** [comment]
This is not a bug with our program. You need to fix your desktop environment somehow.

**Comment by vbnmvhnhjk** [comment]
I've tried. And it only affects Keepassxc. Any advice where to start?

**Comment by droidmonkey** [comment]
It's a Qt specific issue so you need to do a proper test with other Qt based software. Restart your computer. Reinstall your OS. I have nothing else to give you, seems to be a bad interaction between X11 and Qt.

**Comment by vbnmvhnhjk** [comment]
OK thanks, appreciate the reply anyway.

**Comment by vbnmvhnhjk** [comment]
For those that come across this issue, I believe it's caused by PopOS's desktop extensions, such as Pop Shell, Pop Cosmic, and Pop Workspaces. The only way I could get copy and paste working again was to disable all of them and then logout and back in. I tried enabling each one by one but it only seemed to work when all were disabled.

**Comment by droidmonkey** [comment]
Recommend submitting a bug report to Pop in this case.

**Comment by LecrisUT** [comment]
It is not a strictly PopOS issue, I have got this issue for a while on Fedora 36 KDE. Recently I got some kde/qt updates and I'm now on Qt 5.15.5 and I cannot reproduce this issue anymore, unless this issue only appears after a long time use.

**Comment by droidmonkey** [comment]
It's definitely not with our program.

**Comment by LecrisUT** [comment]
Not saying it is, I'm just giving more context and information to anyone else who sees this issue.

**Comment by vbnmvhnhjk** [comment]
Yes I discovered the issue came back despite disabling the Pop extensions, so I removed Pop and installed Ubuntu. So far, so good. But it sounds like because this is a QT issue it depends on the version of QT provided by your system's repos.

**Comment by glow12121** [comment]
I have the same issue on Fedora Gnome. Occasionally I cannot copy things from KeePassXC.

**Comment by Mammutor** [comment]
I have the same problem, but it seems to just be with copying by ctrl+c, but not via the copy button. i think it is something with flatpack

**Comment by Susurrus** [comment]
I have this same issue on Fedora 42 Gnome. I have extensions disabled. Copying via CTRL+C doesn't work but using the right-click menu does work. App installed from RPM, so not a Flatpak problem here.

**Comment by droidmonkey** [comment]
You may have to install `wl-clipboard`
