### ISSUE TITLE
KeePassXC ignore Windows Security

### ISSUE THREAD

**Issue by Celystelliana** [keepassxreboot/keepassxc#8344]
## Overview

Hello teams KeePassXC,
This is my first time using KeePassXC and I fell in love with it right away. After a while I noticed a problem from login database, KeePassXC ignore Windows Security.

## Steps to Reproduce
1. Open KeePassXC portable.
2. Successful database login.
3. Windows Security pop up.
4. Don't type password and click Cancel.
5. KeePassXC still log in to database.

## Expected Behavior
KeePassXC refused login request, user need to type password as required by Windows Security

## Actual Behavior
KeePassXC ignore Windows Security and login to database as long as user type correctly password of database.

## Context
This is my first day I used KeePassXC.  My system don't support Windows Hello touch id and face recognition, I only uses pin. I download KeePassXC portable from KeePassXC.org

[NOTE]:
KeePassXC-2.7.1-Win64 - portable

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows
CPU: x86_64
Windowing System: Windows 11 version 21H2 build 22000.832

**Comment by droidmonkey** [comment]
If you press cancel that just means we will not allow quick unlock after you lock your database. In other words you will be required to enter your full password again. Please read the user guide for more information on quick unlock.

**Comment by Celystelliana** [comment]
You right, I misunderstood this feature. Thanks
