### ISSUE TITLE
autotype induces xfce4-notifyd crash

### ISSUE THREAD

**Issue by jonleivent** [keepassxreboot/keepassxc#8345]
Using keepassxc 2.7.1 on Debian 10, the autotype (Ctrl-Shift-V) induces a fatal xfce4-notifyd crash that kicks the user out to the login window.  The problem does not occur using keepassxc 2.6.2.  From journalctl, the crash message is:
```
xfce4-notifyd: Fatal IO error 11 (Resource temporarily unavailable) on X server :0.
```
I can reliably reproduce the crash in a vm, if you have suggestions on ways to debug this further.

**Comment by droidmonkey** [comment]
Your X11 needs to be updated. There is a critical flaw that we inadvertently trigger. This is covered in another issue ticket.

**Comment by jonleivent** [comment]
> Your X11 needs to be updated. There is a critical flaw that we inadvertently trigger. This is covered in another issue ticket.

X11 updated to what version?  I am on 1:7.7+19, which is the most recent available on Debian 10.  What other ticket covers this issue?

**Comment by droidmonkey** [comment]
#8161 #7797 #8181
