### ISSUE TITLE
Cannot create new KeeShare database using relative paths

### ISSUE THREAD

**Issue by pelzvieh** [keepassxreboot/keepassxc#8348]
## Overview

For keeshare it is possible to manually give relative paths as described in issue #2799. Previously, this used to work, now messages are appearing, "export container cannot be saved". Here, the relative paths are starting with ".." which should indicate the parent of the directory with the database itself.

## Steps to Reproduce
1. Setup keeshare for a database
2. Create a group and configure keeshare for that group.
3. Do not use file selection dialogue to select a path, but enter a relative path manually. Start with ../ to specify a path within the parent of the directory where the database itself resides.
4. Select type "synchronize"
5. Create a new password entry for that group
6. Save the container

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
A keeshare container is created and updated at the location manually given in the keeshare setup, relative to the database.

## Actual Behavior
The keeshare container is not updated, but a red error message appears for some seconds.

## Context
KeePassXC - 2.7.1
Revision: 5916a8f

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS

**Comment by droidmonkey** [comment]
I cannot replicate this at all, double check your relative paths.

**Comment by droidmonkey** [comment]
You can use an existing database with Keeshare from a relative path, but it will not create a new share when a relative path is specified.

**Comment by pelzvieh** [comment]
It might have been caused by the share database having a wrong suffix. For whatever reasons it used to be called thing.share.kdbx.share, which is now no longer selectable, but would be created as thing.share.kdbx. Adding ".share" to this name again causes the described behaviour even with absolute paths, whereas ../somewhere/thing.share.kdbx is indeed working fine.
