### ISSUE TITLE
[Feature Request]Add a {WAIT} keyword to be able to wait for one second (or so) for a second page to load.

### ISSUE THREAD

**Issue by sebma** [keepassxreboot/keepassxc#8349]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
Hi,
Can you please add a {WAIT} keyword to be able to wait for one second (or so) for a second page to load ?

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )
The site https://sso.redhat.com login needs {USERNAME}{ENTER} then it loads (within 1s) another page asking for the {PASSWORD}{ENTER}, the autotype sequence would be something like : 
`{USERNAME}{ENTER}1{WAIT}{PASSWORD}{ENTER}`

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
Some other sites that have the same behaviour that https://sso.redhat.com has would be also be handled.

**Comment by droidmonkey** [comment]
Use {DELAY 1000}, check out the user guide for all available sequence strings

**Comment by sebma** [comment]
@droidmonkey Awesome, thanks. 

I just check the user guide like you wrote, the `Configure Auto-Type Sequences` documentation is here : https://keepassxc.org/docs/KeePassXC_UserGuide.html#_configure_auto_type_sequences
