### ISSUE TITLE
Auto-Suggest previously used custom fields names

### ISSUE THREAD

**Issue by ccoenen** [keepassxreboot/keepassxc#8350]
## Summary
When adding a new custom field, I would like it to suggest field names (this one is not about auto-completing values!) that I already used elsewhere.

## Examples
When adding a new entry to my database, I oftentimes create one of these custom fields, too: email address, secret answers to secret questions (when I can't avoid them I fill them with junk), secret recovery codes, internal account ids ... and so on.

## Context
I would like those custom field names to be consistent across my whole database, so It would be great if I didn't have to look the exact spelling up in other entries.

## Similar examples *within KeePassXC*
This could work somewhat like the username suggestion:

![grafik](https://user-images.githubusercontent.com/124909/184109217-91bbd940-58a9-429d-a194-0b9164bf1187.png)

When you start typing some value into the username field, it suggests existing values. (again: for custom fields, this is not about values, but about field names, for consistency!)

So if it just did a very similar thing in this instance, this request would be resolved:
![adding "E-Mail" to custom fields](https://user-images.githubusercontent.com/124909/184109673-39ad1542-9643-466d-aa57-9846d2e28920.png)

**Comment by droidmonkey** [comment]
#5502

**Comment by ccoenen** [comment]
thanks for the link! I was not finding the correct issues, because I was convinced they were called "custom fields" sorry for the noise :-)
