### ISSUE TITLE
Customize Edit-Interface to include specific custom fields

### ISSUE THREAD

**Issue by ccoenen** [keepassxreboot/keepassxc#8351]
## Summary
I use custom fields on my password entries. Most often, I put "email" into its own custom field, and not in the username field (I then reference it as `{S:email}` in username). I would like to be able to configure KeePassXC to add input elements to the regular password edit screen, which will internally then be stored in custom fields.

## Examples
This example screen has an added "E-Mail" field (which is just the name I personally give it, in germany that's the canonical way to spell email).

![Example-Input-Screen](https://user-images.githubusercontent.com/124909/184108484-a027b010-ad73-4a22-92ee-17d759bd4e80.png)

## Closing clarification
I want to stress that this is **not** about adding a specific single email field to this form. This is just an example for "any user should be able to add their own most-used custom fields here in some way shape or form". For me *personally* that would be `E-Mail`. You do you.

**Comment by droidmonkey** [comment]
Covered by #8228

**Comment by ccoenen** [comment]
thanks for the link! I was not finding the correct issues, because I was convinced they were called "custom fields" sorry for the noise :-)
