### ISSUE TITLE
Tab navigation doesn't respect removed panels by the user

### ISSUE THREAD

**Issue by Inkrementator** [keepassxreboot/keepassxc#8352]
## Overview
Using tab to switch focus between elements of the GUI doesn't work as expected if I remove the database tags pane. Pressing <tab> in the group pane moves focus somewhere I can't see, presumable the now invisible database tags pane. Similarly, pressing <Shift+Tab> in the Database-Entry List also moves focus off-screen.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Click on one of the database groups to move focus there
2. Press <tab> to verify that focus is moved to database pane, pressing tab again moves to database entries.
3. Remove database tags pane by dragging the upper border of it as far down as possible.
4. Click on one of the database groups to move focus there
5. Press <tab> once. Now it is not visible, where the focus is.
6. Press <tab> again to move to database entries.

## Expected Behavior
Pressing tab once from database group pane while database tags pane is removed should move focus directly to database entries.  Step 5. should not happen.

## Actual Behavior
Pressing tab once from database group pane moves focus to invisible location, presumably to the nonexistant database tags. Pressing again allows to go to database entries.

## Context
KeePassXC - Version 2.7.1
Revision: 5916a8f

Operating System: Linux
Desktop Env: i3
Windowing System: X11

**Comment by droidmonkey** [comment]
I have fixed this for 2.7.2, will be in upcoming PR
