### ISSUE TITLE
Hardware key dropdown box in unlock UI has extraneous info for Yubikey, which hides relevant info (change from 2.6.x)

### ISSUE THREAD

**Issue by akda5id** [keepassxreboot/keepassxc#8355]
## Overview
On OS X, in 2.7.1 the dropdown for hardware key now shows: `(USB) YubiKey 4/5 - OTP, U2F and CCID v5.4.3 [8dig serial] C` with the remainder cut off

In 2.6.2 it showed: `YubiKey [8 dig serial] Challenge Response - Slot 1 - Press`

Yes, if you click to open the dropdown, you do see more, but it is not visible at a glance, and is challenging to use.

I feel this is a fairly major UI regression, the relevant pieces of info needed to use a hardware key are in my view, in order of importance:
1. What key will be used
2. What slot on that key will be used
3. Type of authentication (iffy, as keepassxc only uses challenge response?)
4. All the rest (is any of that useful?)

## Steps to Reproduce
1. Plug in Yubikey hardware key
2. Open KeePassXC
3. Open database
4. If necessary click refresh to load info about hardware keys
5. Observe the info presented in the box

## Expected Behavior
See the relevant info, at minimum.

## Actual Behavior
See a bunch of tech gibberish that is of no relevance to the operation

## Context
I would have included UI screenshots, but the window isn't visible to the default OS X screen shot tool, which is a nice security feature. If there is an easy way to disable that, let me know, happy to add screenshots.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.1
Revision: 5916a8f
Vs
KeePassXC - Version 2.6.2
Revision: e9b9582

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS

**Comment by droidmonkey** [comment]
I agree, this was somewhat of a regression introduced when we added NFC support. We pull the name of the key from the Yubikey library now which contains all their gibberish. Easy fix.
