### ISSUE TITLE
A way to change the alphabetical order

### ISSUE THREAD

**Issue by Mi1an** [keepassxreboot/keepassxc#8356]
## Summary
I would like to have an option to change the alphabetical order.

## Examples
For example I have these 10 records:
MyDomainAccount [Web] | 1
MyDomainAccount [Web] | 10
MyDomainAccount [Web] | 2
MyDomainAccount [Web] | 3
MyDomainAccount [Web] | 4
MyDomainAccount [Web] | 5
MyDomainAccount [Web] | 6
MyDomainAccount [Web] | 7
MyDomainAccount [Web] | 8
MyDomainAccount [Web] | 9

## Context
As you can see from the Example upper the number 10 is not sorted after the number 9. That's bothering me.
For example in Total Commander there is a such an option to change this display behaviour.

**Comment by droidmonkey** [comment]
Please provide all your system and keepassxc details from Help -> About

**Comment by Mi1an** [comment]
I am sending the requested info:
KeePassXC - Version 2.7.1
Revision: 5916a8f

Qt 5.15.3
Debugging mode is disabled.

Operating system: Windows 10 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.19044

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 2.18.1
