### ISSUE TITLE
Autotype on MacOS fails when using multiple monitors

### ISSUE THREAD

**Issue by baszoetekouw** [keepassxreboot/keepassxc#8357]
## Overview
I'm using autotype to enter password in terminals (iTerm2).  This works well, except if there are multiple terminals open on different monitors.  In that case, KeepassXC will always autotype in a terminal on the primary screen, even if the autotype was initiated from a terminal on another monitor.

This is incredibly annoying; it has caused me to accidentally autotype a password to IRC three times already in the past week.

## Steps to Reproduce
1. (not sure if this is necessary) set "displays have separate spaces" in Control panel/Mission control and logout/login
1. connect an external monitor to your macbook and set it to extended display (not mirroring)
1. open two terminals; put ons on each screen
1. autotype something from the terminal on the secondary screen; autotype will occur on the other terminal

## Expected Behavior
Password should be autotyped in the terminal from which it was initiated.

## Actual Behavior
Password is autotyped in the wrong windows

## Context
Screencast to demonstrate the issue: https://drive.google.com/file/d/10wUixnAauhl-VpIjMBsEZ6slHuQrPX81/view?usp=sharing

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.1
Revision: 5916a8f

Qt 5.15.2
Debugging mode is disabled.

Operating system: macOS 12.5
CPU architecture: x86_64
Kernel: darwin 21.6.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 2.19.1

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS

**Comment by droidmonkey** [comment]
If you uncheck the displays have separate spaces setting, does this still happen?

**Comment by baszoetekouw** [comment]
I've just checked: without the "displays have separate spaces" settings, everything works fine.  That is perhaps unsurprising, as macOS seems to treat the entire area spanning two monitors as a single space then.

**Comment by droidmonkey** [comment]
The way auto-type works when using the global shortcut is that is raises the window ID of the window that triggered the Auto-Type. This may be a unique circumstance with iTerm2 and how its windows behave across the spaces. Can you test with any other app if the behavior is the same?

**Comment by baszoetekouw** [comment]
Indeed, autotype works perfectly with other apps (notably TextEdit and VSCode).

In the process of filing a bug again iTerm2, I reset my current terminals, and now that problem seems to have gone away.  Not exactly sure what was the matter, but probably some transient weirdness.

Thanks for your help!

**Comment by baszoetekouw** [comment]
For future reference: the issue turned out to be related to a too-low initial autotype delay.  If the delay is too low (<200ms on my laptop), apparently iTerm doesn't have enough time to activate the correct window (in particular if it has terminals open in multiple windows/Spaces) when it is focussed again by KeeepassXC after initiating autotype..  

Setting the initial autotype delay to 350ms solved all issues for me.
