### ISSUE TITLE
Make the Mac application delete entries at just pressing "delete" or CMD + "delete"

### ISSUE THREAD

**Issue by j-lakeman** [keepassxreboot/keepassxc#8358]
## Summary
When deleting an entry, one has to press _function + delete_ on macOS, which is an unconvenient key combo to press.
I suggest using just _delete_ or _command + delete_ instead.
## Examples
<img width="237" alt="grafik" src="https://user-images.githubusercontent.com/101660243/184339885-759f57e3-a162-4cd5-9e4e-32570cbc7b01.png">

## Context
Improving usability

**Comment by droidmonkey** [comment]
See https://github.com/keepassxreboot/keepassxc/issues/6153

Check your settings to make sure your delete key is actually functioning the way you think it should. 

The fact that you have a function key means you are using a keyboard without a dedicated delete key...

**Comment by j-lakeman** [comment]
> See #6153
> 
> Check your settings to make sure your delete key is actually functioning the way you think it should.
> 
> The fact that you have a function key means you are using a keyboard without a dedicated delete key...

Please see this: https://osxdaily.com/2013/04/26/delete-key-mac-forward-del/
I have the exact keymap shown there and it does have a dedicated delete key

**Comment by phoerious** [comment]
I guess the correct shortcut should be Cmd+Backspace, which is also used by Finder.

**Comment by droidmonkey** [comment]
Yah so the Mac keyboard physical Delete key is really the Backspace key. To issue an actual delete key you need to press Fn + Delete. Our program is correct, the keyboard is janky. Adding a shortcut on macs for Backspace and/or Cmd+Backspace would be good. I don't see how Fn + Delete is any more cumbersome than Cmd + Delete though...

**Comment by j-lakeman** [comment]
> Yah so the Mac keyboard physical Delete key is really the Backspace key. To issue an actual delete key you need to press Fn + Delete. Our program is correct, the keyboard is janky. Adding a shortcut on macs for Backspace and/or Cmd+Backspace would be good. I don't see how Fn + Delete is any more cumbersome than Cmd + Delete though...

That's right.
_Fn + Delete_ is more cumbersome, because _Fn_ is at the bottom left, whereas _delete_ on the top right of the keyboard. There are two _command_ keys, one at the bottom left and one on the right.
