### ISSUE TITLE
UX improvements to New Database flow

### ISSUE THREAD

**Issue by jsha** [keepassxreboot/keepassxc#836]
When you create a new database, you get a screen like this:

![screenshot from 2017-07-31 17-23-08](https://user-images.githubusercontent.com/220205/28803952-f1efd228-7614-11e7-983a-ed549feda198.png)

Some possible improvements:
 - Like in #835, I think "Change master key" is confusing for two reasons: "master key" is less common usage than "master password," and when creating a new database you're not "changing" a key or password, you are creating one. For instance, this might be better as "Set master password"
 - Key file and challenge response are somewhat unintuitive. They should have a link to help text, or possibly a tool tip?

Thanks for listening!

**Comment by jsha** [comment]
Hi! Did this get fixed?

**Comment by droidmonkey** [comment]
See #1952

**Comment by jsha** [comment]
Excellent, thank you so much!
