### ISSUE TITLE
Unlock with Hradware Key on macOS does not work

### ISSUE THREAD

**Issue by zekroTJA** [keepassxreboot/keepassxc#8362]
## Overview

I have a KeepassXC (KDBX 4) password database secured with a Master Key as well as a Hardware Token (YubiKey 5 NFC with Challenge-Response). When unlocking it on my MacBook Air M1 2020, after pressing the button  on the Key, I recieve an error `HMAC mismatch`. I need to day that I am using the UbiKey via USB A through a USB-C dongle (ISY IHU-5200), but logging in to web pages with the key using challenge-response works fine and also the Yubico Manager works as expected. Also, using the same Dongle setup on my Windows 10 machine, everything works fine as well.

## Steps to Reproduce

1. Plug in the YubiKey to the Dongle
2. Open KeepassXC
3. Open the Database
4. Enter Master Passowrd
5. Chose the YubiKey Slot as Hardware Key
6. Click on `Unlock`
7. Press the key on the hardware key

## Expected Behavior

The database should unlock as expected.

## Actual Behavior

The Database does not unlock with the error `HMAC mismatch`.

## Context

I am using KeepassXC Version 2.7.1 on macOS 12.4 (MacBook Air M1). As Hardware Key I am using a YubiKey 5 NFC (Firmware 5.4.3) via a ISY IHU-5200 USB-C dongle. 

KeePassXC - Version 2.7.1
Revision: 5916a8f

Qt 5.15.2
Debugging mode is disabled.

Operating system: macOS 12.4
CPU architecture: x86_64
Kernel: darwin 21.5.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 2.19.1

Operating System: macOS 12.4

**Comment by droidmonkey** [comment]
Just to be sure, are you sure you are choosing the correct slot to use? There are two. If you see the hardware key in the list, there is absolutely no difference in the code to do challenge response between windows and Mac. 

Also make sure you are typing the password correctly.

**Comment by zekroTJA** [comment]
Yep, I have chosen slot 1 as same as I do when unlocking on other machines. Also, I verified multiple times that my master password is correct. I have also tested with multiple other USB-A to USB-C adapters and it didn't work on any of them. I have also tested with the native Apple Silicon version as same as with the Intel Version.

When I get the repo running on my mac, Ill try to debug through the challenge response procedure. Maybe that gives some further hints. ^^

**Comment by zekroTJA** [comment]
Okay, I just noticed that when I create a database on my mac and lock it with a hardware key, then I can open it without any issue. Also when edited on Windows, the file still works on mac.

It might have something to do how the file was originally created. I used the original Keepass 2 to create the database using the KDBX 3 format. Later, I switched to KeepassXC and KDBX 4 to lock it with a hardware key.

Now, I tried to reconstruct this scenario.
1. Create a database using the current version of Keepass 2
2. Store some values in it
3. Open it with KeepassXC
4. Switch database format to KDBX4
5. Save the database
6. Add hardware security key
7. Save the database
8. Put it on my mac
9. Open it with KeepassXC

But I could not reproduce the problem. So, now, I've just exported my old database to a CSV and imported into a new, fresh database and everything works fine now. Might really have been a weird issue with the format of the file.

**Comment by droidmonkey** [comment]
The file itself likely became corrupt then, weird. Glad you are back on track though.
