### ISSUE TITLE
Trivial Bypass for Windows Security popup

### ISSUE THREAD

**Issue by alec-zaiane** [keepassxreboot/keepassxc#8365]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
When unlocking a database, after typing in the database password, a windows security/windows hello window will popup asking for the user password/pin. **if the user closes the security popup without entering their password, the database will still unlock**
Tested in both Windows 10 and 11

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. On Windows, get in a situation where the windows security popup asks for verification (PIN in my case)
2. Press escape on the keyboard or click cancel
3. KeePassXC will act as if you had entered the correct pin 

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
KeePassXC should not unlock the database

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
KeePassXC does unlock the database

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.1
Revision: 5916a8f

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows
Desktop Env: N/a
Windowing System: N/a

**Comment by michaelk83** [comment]
https://github.com/keepassxreboot/keepassxc/issues/8344#issuecomment-1209581282 , among others.

@droidmonkey This has been said before, but is worth repeating: if QuickUnlock was opt-in, and this first popup was triggered by the user explicitly enabling it, then this common confusion could be avoided.

**Comment by alec-zaiane** [comment]
Thanks for the link, I tried looking for similar issues before posting, but evidently not hard enough.

Should this issue be closed?

**Comment by droidmonkey** [comment]
I am planning a UI change to make quick unlock more explicit, but I don't think it will prevent this confusion (it'll still be on by default). I wish the windows hello api allowed for straight encrypt and decrypt operations instead of only signing. Windows hello is actually meant for authentication and not directly for encryption. You wouldn't need the prompt to encrypt due to using Public key. We always use the private key, hence the prompt for initial encrypt.

**Comment by foxydevloper** [comment]
It keeps asking for a pin every time I enter my password to unlock my database, but it doesn't save it for quick unlock. Why does it keep asking if it's not even going to allow me to use quick unlock next time? Does quick unlock even work with PIN or no?

**Comment by droidmonkey** [comment]
Quick unlock only applies to the current application session. If you exit KeePassXC or _close_ your database then you need to setup Quick Unlock again.

**Comment by JohnLGalt** [comment]
And if your database locks automatically, then it needs to be unlocked again.

It's the same with Windows. If you lock Windows, you need to enter your PIN to unlock.

**Comment by foxydevloper** [comment]
> Quick unlock only applies to the current application session. If you exit KeePassXC or _close_ your database then you need to setup Quick Unlock again.

Oh! I see, so in order to use it properly I need to change settings to make it minimize to system tray. I got it working now, thanks.
