### ISSUE TITLE
Change kde plasma dark theme right click menu.

### ISSUE THREAD

**Issue by tazihad** [keepassxreboot/keepassxc#8366]
## Summary
I am using keepassxc Dark mode in KDE Plasma desktop. The right click menu is hard to distinguish. So, requesting to add some shadow. Or change the theme little bit. So, we can distinguish from right click menu and app.

![Screenshot_20220815_074743](https://user-images.githubusercontent.com/19417232/184564831-bb6e37f6-0a50-4835-9963-db911a73f465.png)

It may be different in different monitor. But in my laptop lcd panel. It's hard to distinguish.

**Comment by droidmonkey** [comment]
That menu color is chosen by Qt, we don't have control over it. We also can't put shadows around windows, that is the responsibility of your compositor. It actually looks like you are missing window edges in general,  this isn't a keepassxc issue though.
