### ISSUE TITLE
No longer button to remove custom icons

### ISSUE THREAD

**Issue by MaxBMic** [keepassxreboot/keepassxc#8370]
Hello everyone,

I use custom icons for my entries, and I can't delete my icons anymore. 
I don't have the delete button. I had it in previous versions of Keepass.

![Capture d’écran du 2022-08-15 14-58-29](https://user-images.githubusercontent.com/74116540/184639427-63aa2895-4a19-495b-8f32-4238917151c3.png)

How to remove custom icons ?

**My Keepass information :** 

KeePassXC - Version 2.7.1
Revision: 5916a8f

Qt 5.15.5
Debugging mode is disabled.

Operating system: Fedora Linux 36 (Workstation Edition)
CPU architecture: x86_64
Kernel: linux 5.18.16-200.fc36.x86_64

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.19.1

Thank you :-)

**Comment by droidmonkey** [comment]
Database menu -> Database settings-> Maintenance

**Comment by MaxBMic** [comment]
Thank you droidmonkey

it was very simple !
