### ISSUE TITLE
Dual monitor setup distorted tray icon on inactive screen (macOS)

### ISSUE THREAD

**Issue by mietzen** [keepassxreboot/keepassxc#8372]
## Overview
The tray icon of the inactive screen is distorted:
![image](https://user-images.githubusercontent.com/31704359/184842681-0cf64f10-d96e-4f26-8d02-a228c980fdc4.png)

## Steps to Reproduce
1. Use a MacBook Pro with an external 4K Monitor as secondary screen 
2. Launch KeePassXC

## Expected Behavior
Tray icon is not distorted.

## Actual Behavior
The tray icon of the inactive screen is distorted.

## Context
Monitor Config: MacBook Pro 14 Inch (Scaling: default) + LG Ultrafine Ergo 27" 4K (Scaling: 3008x1692)

KeePassXC - 2.7.1
Revision: 5916a8f

Operating System: macOS 12.5

**Comment by phoerious** [comment]
It's an upstream Qt bug. https://bugreports.qt.io/browse/QTBUG-88600

**Comment by mietzen** [comment]
When will KeepassXC updated it's QT dependency, since the QT Bug is fixed in 5.12.11?
My version was build with QT 5.15.2 so upgrading to the latest bugfix version should not be a problem.

**Comment by droidmonkey** [comment]
Qt no longer releases bug fix versions for their LTS until 1 year has passed........

**Comment by mietzen** [comment]
That means it won't ever be fixed? Or ever be fixed until updating to QT6.x?

**Comment by droidmonkey** [comment]
Actually looks like it's released now so the next keepassxc release will have the fix in it. @phoerious make sure you update your qt version on the build Mac.

**Comment by phoerious** [comment]
It's supposedly fixed in 5.12. The latest Homebrew has is 5.15.5. I will have to check if the patch was merged into that version. Last time it wasn't.
