### ISSUE TITLE
URLs in notes preview are not clickable

### ISSUE THREAD

**Issue by vphantom** [keepassxreboot/keepassxc#8374]
## Overview

I think that v2.5.0 gained this ability via #3596 (issue #3511). However I'm running the AppImage for v2.5.4 and hyperlinks in notes are not clickable. I don't see any configuration setting which could enable this.

## Steps to Reproduce

1. Create a new entry
2. Write a URL in the notes area, or several
3. Save the entry

## Expected Behavior

Hyperlinks recognized and behaving like the main URL: blue, underlined, clickable, with a context menu (right click) option to copy.

## Actual Behavior

After saving, the note preview is 100% plain text.

KeePassXC - Version 2.5.4
Revision: dcca5aa
Distribution: AppImage

Qt 5.12.7
Debugging mode is disabled.

Operating system: Debian GNU/Linux 10 (buster)
CPU architecture: x86_64
Kernel: linux 4.16.0-0.bpo.2-amd64

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.1

Operating System: Linux
Desktop Env: XFCE
Windowing System: X11

**Comment by vphantom** [comment]
FYI I upgraded to v2.7.1 (whoa the color scheme! the icons! 😱) and links in notes are still not clickable here. I don't really know what else to try.

**Comment by droidmonkey** [comment]
This was explicitly reverted in 2.5.1 because it broke a lot of people's notes: https://github.com/keepassxreboot/keepassxc/pull/3727

**Comment by vphantom** [comment]
I see; thanks for clarifying. So notes will eventually gain the ability to be opt into rich text mode, but the plain notes we have now must remain plain. I like that… except the part about waiting few more years. 😉 I wish I knew C++. There's lots of stuff I keep in encrypted Markdown files which I'll bring into KeepassXC when that will happen.

Note to future readers: #1057 seems to be the one tracking this.
