### ISSUE TITLE
Merging database overwites whole entry. Not attributes

### ISSUE THREAD

**Issue by tribela** [keepassxreboot/keepassxc#8376]
Steps to reproduce:

1. Create some entry with id/pw
2. Sync
3. Add TOTP to the entry on PC A
4. Add some other attribute like memo on PC B
5. Now syncing is conflict
6. Merge database
7. Attributes written on step 3 is gone. Only step 4 remains

Expected behaviour:

Merge each attributes on same entry. Not overwrite with newest atomic entry

**Comment by droidmonkey** [comment]
Kdbx standard is merge at the entry level. The latest modified version of the entry wins. Older versions are stored in history.
