### ISSUE TITLE
Database Credentials Authentication with 'OR' logic 

### ISSUE THREAD

**Issue by murder** [keepassxreboot/keepassxc#8377]
## Summary
Currently, whenever you want to set up the database security to access it (set a password, key file or even challenge-response like yubi's) they follow the 'AND' logic for authentication, which means, if I set a password, a key file and a challenge-response, it will request all of them together to be used in order to access the database.
What I propose is that we can use the 'OR' logic, which you can configure for example: a password, a key file and a challenge-response, and just one of them is enough to access the database, or in the future two of them is enough (configurable)

## Examples
- Include a checkbox to use 'OR'
- Select this 'OR' checkbox which will enable OR logic
- Set a password
- Set a key file
- Set a Challenge-response
- Close the database and reopen
-- Use the password and it opens;
-- Or use the Challenge-Response and it opens;
-- Or use the Key File and it opens.

## Context
Easier conciliation between Keepass databases (KeePassXC and KeepassDC for Android)

**Comment by droidmonkey** [comment]
This is not part of the kdbx standard and we will not support it. If you want to use tiered access controls you must use auto open.
