### ISSUE TITLE
UX improvements for "New key association request"

### ISSUE THREAD

**Issue by jsha** [keepassxreboot/keepassxc#838]
When you install chromeIPass (or Passifox, but I haven't tested), and hit "Connect," you get this dialog box:

![screenshot from 2017-07-31 17-44-11](https://user-images.githubusercontent.com/220205/28804420-edab24a8-7617-11e7-9d19-128c53942e00.png)

Issues:
 - The title extends beyond the space available and is cut off
 - The help icon ("?") doesn't work (for me, on Windows 11, KeePassXC 2.2.0)
 - The text says "for the above key," but there is no key described above.
 - The text should describe what an association request is for, and why the user should choose a name. It could even suggest a default name, like "browser", or "chrome" (possibly based on User-Agent?)

**Comment by duk3luk3** [comment]
* It should allow to choose which database(s) to add the key to

**Comment by LinuxOnTheDesktop** [comment]
> The text should describe what an association request is for, and why the user should choose a name.

I agree with this. However: does my version of KeePassXC (2.3.4) already include any changes made as a result of this ticket? For I still find the window - shown below - unclear.

![image](https://user-images.githubusercontent.com/47056543/52243142-ab137b00-28d0-11e9-9d10-c677322a8f93.png)

The text in the window does not really make it clear what is being done or indeed what the user is being asked to name.

Thanks.

**Comment by droidmonkey** [comment]
Since this issue is still open that means we have not merged the changes into any branch. I am marking it for 2.4.1.

**Comment by LinuxOnTheDesktop** [comment]
@droidmonkey

Ah yes, that makes sense. Thank you for explaining. I am glad an improvement is in the works.

**Comment by outdooracorn** [comment]
I agree with this issue, adding my two cents about @jsha's last bullet point:

It isn't clear to me if this was a name for the DB to be stored in the extension OR a name for the extension to be stored in the DB. 

The title of the popup started with `KeePassXC:` which lead me to beleive it was a name for the extension to be stored in the DB. However, under `KeePassXC-Browser` -> `Settings` -> `Conencted Databases` it says `The following KeePassXC databases are connected to KeePassXC-Browser.` with the name I entered previously listed as the identifier. This leads me to beleive it is a name for the DB in the extention. 😕 Which is it?

**Comment by droidmonkey** [comment]
For now, don't think too hard about it and give it a nice name like "laptop-chrome" and move on with what you were doing. :grin:
