### ISSUE TITLE
Autotype with no results: Allow searching and selecting an entry

### ISSUE THREAD

**Issue by benzkji** [keepassxreboot/keepassxc#8380]
## Summary

If no results for the current window are found, the auto type dialog shows "Couldn't find an entry that matches the window title: Windowtitle XY", and leaves us there with no options. Instead, a more advanced filtering would be nice, at least a search field, for quick selection of the needed entry.

## Context
Having more context in entry titles means that sometimes, window titles cannot match entry titles (having many logins for different google accounts, for example: "Google for client XY", "Google Private", etc). It could already help to fall back to URLs, if no matching title is found, but search would be really nice.

An alternate approach could be: Select the needed password entry in KeepassXC, then push a button/shortcut, to trigger autotype for this entry, in the previously selected window.

**Comment by droidmonkey** [comment]
Update to 2.7.1

**Comment by benzkji** [comment]
sorry, not up to date with ubuntu LTS!
