### ISSUE TITLE
Toolbar icon "Open URL"

### ISSUE THREAD

**Issue by Korezze** [keepassxreboot/keepassxc#8381]
## Summary
Hello,
Would it be possible to integrate an "Open URL" icon in the toolbar (in addition to "Copy URL" icon) ?
Thanks

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )

**Comment by droidmonkey** [comment]
Keyboard shortcut is Ctrl + Shift + U, or double click the url in the entry view or click the url in the preview pane.  We won't be adding any more icons to the toolbar.
