### ISSUE TITLE
Auto-Type changes X11 keyboard layout of other devices

### ISSUE THREAD

**Issue by matzebond** [keepassxreboot/keepassxc#8383]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

I use a non-standard layout and have configured my yubikey to use the us layout to work correctly.
When I use KeePassXCs Auto-Type feature (which works perfectly fine) the yubikey switches to the layout my keyboard uses.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. insert yubikey, it uses the us-layout as configured
2. trigger Auto-Type, works perfectly
3. trigger yubikey, does not use the us-layout anymore

### Workaround
`sudo udevadm trigger --subsystem-match=input --action=change` 
to reset the layout of the yubikey

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
yubikey should always use the us-layout

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
yubikey should uses the de-neo layout after triggering Auto-Type

## Context
[NOTE]: # ( Give us any additional information you may have. )

localectl
```       
   System Locale: LANG=en_US.UTF-8
       VC Keymap: neo
      X11 Layout: de
       X11 Model: pc105
     X11 Variant: neo
```
/etc/X11/xorg.conf.d/20-yubikey.conf
```
Section "InputClass"
  Identifier      "yubikey"
  MatchIsKeyboard "on"
  MatchVendor     "Yubico"
  Driver          "evdev"
  Option          "XkbRules" "evdev"
  Option          "XkbModel" "pc105"
  Option          "XkbLayout" "us"
  Option          "XkbVariant" "basic"
EndSection

```

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.1
Revision: 5916a8f

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: None/i3
Windowing System: X11

**Comment by droidmonkey** [comment]
You should file an issue with Yubikey. This isn't on us if they cannot retain the configured / desired layout. They are likely seeing a layout change and adjusting accordingly, in essence ignoring your preferences.

**Comment by matzebond** [comment]
A layout change on which level? I am not very knowledgeable about how X11 handles this, but it seems to me that in X keyboard devices can have their own layout and KeepassXC should probably only change its own layout.

**Comment by droidmonkey** [comment]
We use the current layout in use by the system. We do use some backend X11 features to help build a keymap to handle keys in the current layout, but we don't change the layout. This may be where things go awry with your setup with yubikey: https://github.com/keepassxreboot/keepassxc/blob/develop/src/autotype/xcb/AutoTypeXCB.cpp#L307-L309

My recommendation to you is to setup your yubikey to just use your common keyboard layout instead of trying to force it to the us layout.

**Comment by matzebond** [comment]
Thank you for the explanation and the tips. I am currently using `sudo udevadm trigger --subsystem-match=input --action=change` to get the YubiKey back to the us layout.
