### ISSUE TITLE
Mark entry as deactivated

### ISSUE THREAD

**Issue by Robert941** [keepassxreboot/keepassxc#8385]
**Summary**
Have the ability to mark an entry as deactivated.

**Details**
When an online account is closed or deleted...
 - Have a toggle to mark the entry as deactivated
 - Apply a timestamp to the date of deactivation
 - Have the ability to sort by this attribute
 - Have the ability to collapse all deactivated entries

**Comment by droidmonkey** [comment]
Just edit the entry and check the expiration field, it will be expired instantly.
