### ISSUE TITLE
copy password button copies url instead

### ISSUE THREAD

**Issue by egpatton** [keepassxreboot/keepassxc#8387]
Hi, for many years I've been using KeePassXC by selecting the desired entry, and then clicking on the 'copy password' button at the top of the app to then paste that password into web pages.  In recent versions of KeePassXC (currently using v2.7.1 on macOS 12.5), when I click on 'copy password', the URL gets copied into the clipboard rather than the password.  Any thoughts?

apologies if this issue has been previously reported, but if it was I was unable to locate it.

**Comment by droidmonkey** [comment]
Fixed for 2.7.2
