### ISSUE TITLE
Error while reading the database: Not a KeePass database.

### ISSUE THREAD

**Issue by TimeCrunch101** [keepassxreboot/keepassxc#8388]
## Overview
I did a big stupid and accidently deleted my KeePassXC Database (using shift delete). I have a backup database from 2 days ago so I'm not freaking out too much. However, there were some entries made recently that I would really like to have back. I used a tool called Disk Drill to recover the database from the shift delete. But unfortunately, I'm getting the error listed in the title of this post.

## Steps to Reproduce
1. Shift delete your DB
2. Use Disk Drill to recover DB
3. Panic when your DB doesn't open

## Expected Behavior
DB opens

## Actual Behavior
DB doesn't open. Receive error "Error while reading the database: Not a KeePass database". Also tried opening and getting DB info with the cli feature but it reports the same error as well.

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.1
Revision: 5916a8f

Qt 5.15.3
Debugging mode is disabled.

Operating system: Windows 10 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.22000

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 2.18.1

Operating System: Windows 11
Desktop Env: 
Windowing System:

**Comment by droidmonkey** [comment]
Your database is lost forever, nothing we can do about it unfortunately. When you fully delete a file the OS will instantly start overwriting that portion of the hard drive. Disk recovery programs are a joke, they may be ok for images and text files but encrypted data doesn't allow for missing information.
