### ISSUE TITLE
Setting to disable the Auto Type warning message box

### ISSUE THREAD

**Issue by rpgdev** [keepassxreboot/keepassxc#8389]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
We need a way to disable the Auto Type warning message, I understand why it was added and that's great, however, as it is implemented right now the warning message gets in the way of everyone who actually wants to use the Auto Type hotkey.. kind of defeating the point of a hotkey in the first place.

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )
1. Hit the autotype hotkey on any of your entries.
2. See the message box that appears each and every time.

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
It gets in the way of the autotype hotkey being useful. Changing the hotkey to ctrl+shift+v should've been more than enough to avoid accidental pastes but ok, we can have the warning message, but at least give us the option to disable it in order to preserve the utility of the hotkey since this kind of breaks it/defeats the purpose of it.
Genesis issue: https://github.com/keepassxreboot/keepassxc/issues/2665

**Comment by droidmonkey** [comment]
There already is a setting... disable "Always ask before performing Auto-Type" in the Auto-Type settings page.

**Comment by rpgdev** [comment]
I looked for it and didn't see it. Maybe I missed there was a tab there. Thanks.
