### ISSUE TITLE
Allow multiple instances

### ISSUE THREAD

**Issue by maevic** [keepassxreboot/keepassxc#839]
It would be nice to have an option or a command line switch to allow multiple instances. As I see it from #510 a single instance is forced.

I very much prefer having two instances running rather than two tabs in the same instance. Image a private kdbx file and one for work where one regularly have to copy a few entries from work to private or vice versa. It is more convenient to just alt-tab between the two instances than to use the mouse every time to change the tabs. Also it is more obvious which instance have the focus.

Anyway thank you very much for your effort!

**Comment by TheZ3ro** [comment]
This is already possible with the `develop` branch since #791.

This will be available in the next version
