### ISSUE TITLE
Manage database from the browser extensions

### ISSUE THREAD

**Issue by dnet890** [keepassxreboot/keepassxc#8390]
## Summary
Like Bitwarden and Lastpass, it will be great if we can manage our database easily from the browser extensions (Chrome, Edge/Firefox)

## Examples
Bitwarden and Lastpass browser extensions allow the user to manage database (i.e: create new entries, manage passwords etc). So, it will be great KeepassXC can do the same

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? to improve extensions capabilities.

**Comment by varjolintu** [comment]
There's already a feature request for creating new entries from the extension https://github.com/keepassxreboot/keepassxc-browser/issues/1234.

Managing the database directly from the extension is probably not going to happen. The whole idea is that only credentials relevant to the current site are used. Access to the whole database is a bit too risky.

**Comment by droidmonkey** [comment]
We will not allow this, it breaks our security model.
