### ISSUE TITLE
Password entry field registers incorrect characters with non-standard keyboard

### ISSUE THREAD

**Issue by LiamK** [keepassxreboot/keepassxc#8395]
## Overview

# Entering password results in incorrect characters when using U.S. International Keyboard.

## Steps to Reproduce
1. Keyboard Preference set to U.S. International - PC
2. Start KeepassXC
3. Enter password containing a special character, e.g. the apostrophe: ', or probably other accented chars.

## Expected Behavior
# Expected to be able to access the database

## Actual Behavior
# Access denied

## Context
The U.S. International keyboard features dead keys used to type accented characters.  For example,
' + 'e' to create the character é.  When entering characters in the password entry field, if character echoing is turned *off* (the password is not shown) an incorrect character is entered, which can
be verified by clicking the eye (the view password icon).
If character echoing is *on* then the dead key doesn't work, so that's not correct behaviour either.

# Workaround

Turn on character echoing and type carefully

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.1
Revision: 5916a8f
Qt 5.15.2
Debugging mode is disabled.
Operating system: macOS 11.6
CPU architecture: x86_64
Kernel: darwin 20.6.0

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS Big Sur

**Comment by droidmonkey** [comment]
This is a qt bug, nothing we can do to fix it unfortunately. If the password is visible then everything should work normally. We have not heard of it failing when the password is visible.

**Comment by LeanderBlume** [comment]
Looks like [this](https://bugreports.qt.io/browse/QTBUG-84664) bug. If it is, it should be fixed in Qt 6.2, so you "just" have to upgrade to that version ;) But I'm sure that's not so simple.
