### ISSUE TITLE
Ignore PINs in Weak Passwords filter

### ISSUE THREAD

**Issue by ericzolf** [keepassxreboot/keepassxc#8397]
## Summary
As the subject says, add a new filter for weak passwords, without PINs.

## Examples
In the section Database Tags, have a new filter

- All
- Expired
- Weak Passwords
- Weak Passwords (no PINs)

## Context

I appreciate the help the filter gives me, I'm just going through those weak passwords, but there are a lot of places where passwords can't be made stronger, and this applies mostly to PINs for credit cards and the same. So not having them would simplify review a lot.

**Comment by droidmonkey** [comment]
Open the entry for editing, go to advanced,  check the box next to exclude from reports, save.  😁

**Comment by ericzolf** [comment]
I had hoped for something more "holistic", but fair enough.
