### ISSUE TITLE
KeePassXC 2.7.1 window does not appear over AnyDesk connection

### ISSUE THREAD

**Issue by wonderfjord** [keepassxreboot/keepassxc#8398]
## Overview
Hello there!
Downloaded 2.7.1 and verified the download.
Installed it on a new Win 10 Pro 21H2 system that never had KeePassXC on it before.
While being at the machine - KeyPassXC window appears
Over Remote Desktop - KeyPassXC window appears
Over AnyDesk - KeePassXC window disappears completely, does not react to any inputs, just as if it's not even there.

Let's say Computer A has the KPXC 2.7.1 installed on it and Computer B can connect to Computer A via RDP.
So if I connect to Computer A via AnyDesk, the KPXC window disappears.
But if I connect to Computer B via AnyDesk and then RDP to Computer A, then KPXC appears again.
Same thing happens to Computer B - I can RDP to it from Computer A and everything is fine. But connecting to it directly via AnyDesk causes KeePassXC window to disappear.

## Steps to Reproduce
1. Install 2.7.1 on Win 10 21H2
2. Launch it while at the machine or via Microsoft Remote Desktop - no issues.
3. Not connect to the computer over AnyDesk 6.5.1 and the window of KeyPassXC 2.7.1 just disappears - as if it's not even there. 

## Expected Behavior
I expected the app to open the main window to be visible, regardless of how I'm connected to the machine.

## Actual Behavior
Specifically over AnyDesk: KeyPassXC can be opened and can be closed from the Task Bar, but no window ever becomes active or receives user input. Just a black square when hovering over the icon in the task bar:
![kpxc](https://user-images.githubusercontent.com/111681053/185784857-26a71af1-599b-44df-8858-9440c15722dd.png)

But if I connect to the same machine over Remote Desktop, then the main window is RIGHT BACK WHERE IT WAS.

## Context

1. While over AnyDesk, ran WinLister to see what windows exist:
![kpxc2](https://user-images.githubusercontent.com/111681053/185784878-c408adc1-edf1-4363-a795-19aaa17eedd5.png)
but neither one can be Switched To to be Shown
2. Saw from an earlier/older thread on here that VC++ redistributables could be causing some issues. Went to the link here https://docs.microsoft.com/en-US/cpp/windows/latest-supported-vc-redist?view=msvc-170#visual-studio-2015-2017-2019-and-2022 
and got the 2015-2017-2019-2022 install files and installed them on the system. 
Also got the VC 2012 and VC 2013 install files, but since they were already installed on the system, I just ran a Repair process on them.
Re-booted after the install
3. Tried to open KPXC again - same problem. 
5. Uninstalled KPXC and removed all KeePass entries from the Registry and rebooted
6. Reinstalled KPXC again, unchecked "Launch at login" and "Launch KeePassXC after install". Launched it manually - same issue. 
7. Looked at Event Viewer for any errors - no errors or warnings related to KeePass. 
8. Went to check the LOCAL and ROAMING **keepassxc.ini** files for KeePass in AppData. Here they are. 
Deleted them while KeePass was not running, then re-opened. This did not resolve the issue.

AppData/LOCAL:

> [General]
> LastOpenedDatabases=@Invalid()
> 
> [GUI]
> MainWindowGeometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\xff\xff\xff\xff\xff\xff\xff\xf8\0\0\n\0\0\0\x5x\0\0\x3p\0\0\x1\x90\0\0\x6\x8f\0\0\x3\xe7\0\0\0\0\x2\0\0\0\n\0\0\0\0\0\0\0\0\x17\0\0\t\xff\0\0\x5w)
> MainWindowState=@ByteArray(\0\0\0\xff\0\0\0\0\xfd\0\0\0\0\0\0\n\0\0\0\x4\xf8\0\0\0\x4\0\0\0\x4\0\0\0\b\0\0\0\b\xfc\0\0\0\x1\0\0\0\x2\0\0\0\x1\0\0\0\xe\0t\0o\0o\0l\0\x42\0\x61\0r\x1\0\0\0\0\xff\xff\xff\xff\0\0\0\0\0\0\0\0)
> SplitterState=@Invalid()
> PreviewSplitterState=@Invalid()
> GroupSplitterState=@Invalid()
> ListViewState=@ByteArray()
> SearchViewState=@ByteArray()

AppData/ROAMING:

> [General]
> ConfigVersion=2
> UpdateCheckMessageShown=true
> 
> [PasswordGenerator]
> AdditionalChars=
> ExcludedChars=
> 
> [GUI]
> CheckForUpdates=false

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.1
Revision: 5916a8f

Qt 5.15.3
Debugging mode is disabled.

Operating system: Windows 10 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.19044

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 2.18.1

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 10 Pro 21H2

**Comment by silentbrains** [comment]
Possibly this: [Screenshot Security](https://keepassxc.org/docs/KeePassXC_UserGuide.html#_screenshot_security)

**Comment by droidmonkey** [comment]
That's exactly it..

**Comment by wonderfjord** [comment]
Thank you @silentbrains and thank you @droidmonkey!!!

1. ### Can this also be a tic-box option in the Settings under Security?
Because the command-line tag work-around is fine for Windows shortcuts, but command-line tag solution is bloody awful for Mac users, since we don't even deal with shortcuts and would have to open the app thru Terminal every time. Yes, it's not that hard, but I would never expect non-techie end-users to be able to do this on their own.

2. This is a great security feature and **I now understand why it's turned on by default.**
However when the user (e.g. myself) is unaware of its existence, there's no way to find this out on your own. The fact it behaves like a bug, rather than a feature, leads one down the path of reinstalling the app, rather than running it with a command line tag. **If I didn't create this bug report, I would have never known how to resolve this.** THANK YOU @silentbrains!

I understand that creating a ton of options during the installation process is bad UI design. **However, perhaps this is a checkbox that should, just maybe, exist during the installation process?** Simply because this creates a Catch-22, where in order to fix the issue, one must be aware it's a deliberate feature of the app, and there's no info provided to the end user beforehand.

3. Finding out about the feature - In the User Guide, this is only mentioned as "Screencapture", but this is an aspect of Remote access due to that nature of the remote access apps utilizing Screencapture as a method of displaying the screen. Without @silentbrains pointing this out, there would be absolutely no way of knowing that the culprit is the Screen Capture section of the User Guide. Perhaps adding a couple of lines about Remote Access apps and Screen *Sharing*?

**Comment by silentbrains** [comment]
It does seem to be an obscure feature, the only reason I know about it is because it pops up here occasionally.

**Comment by wonderfjord** [comment]
Why it exists makes a lot of sense - if only it was less obscure and controllable from within the Settings.

**Comment by droidmonkey** [comment]
Improvement of this is tracked in #7580

**Comment by utzer** [comment]
> That's exactly it..

What?

**Comment by krupy24** [comment]
<img width="621" height="665" alt="Image" src="https://github.com/user-attachments/assets/93f0b5a7-5360-476a-8a4d-2c5ed75b17fd" />
