### ISSUE TITLE
Add an Entropy meter for passwords

### ISSUE THREAD

**Issue by TheZ3ro** [keepassxreboot/keepassxc#84]
This is a PR from KeePassX https://github.com/keepassx/keepassx/pull/44

It will be nice if the entropy mater can be based on [ZXCVBN](https://github.com/tsyrogit/zxcvbn-c) (https://blogs.dropbox.com/tech/2012/04/zxcvbn-realistic-password-strength-estimation/)

**Comment by droidmonkey** [comment]
This would be nice to combine with the stand alone password generator feature request.

**Comment by TheZ3ro** [comment]
Exactly, I was working on that

**Comment by droidmonkey** [comment]
Oh great, can you add yourself as assigned if not already :wink:
