### ISSUE TITLE
Can't select Hebrew from the language settings

### ISSUE THREAD

**Issue by avma** [keepassxreboot/keepassxc#8404]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # (Give a BRIEF summary about your problem)
After recently upgrading to Linux mint Cinnamon 21 and reinstalling keepassxc' I can't select Hebrew from the language settings. I'm sure it is there as I used it before (also I'm translating and marinating the translation for a while now). 
furthermore, I've set my system locale to he_IL utf8 and set KPCX language to 'system default' (which is Hebrew) but still Hebrew is not available.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. go to Tools-->Settings-->General-->Language, then look in the drop-down box
2. 
3. 

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
See Hebrew or עברית and be able to switch into that

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
NO HEBREW

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.6
Revision: 9c108b9

[NOTE]: # ( Pick choices based on your environment )
Qt 5.15.3
Debugging mode is disabled.
Operating system: Linux Mint 21
CPU architecture: x86_64
Kernel: linux 5.15.0-46-generic
Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration
Cryptographic libraries:
- libgcrypt 1.9.4

**Comment by droidmonkey** [comment]
You are on an old version of keepassxc, update to 2 7.1

**Comment by avma** [comment]
oops, thought the package on linux mints distro are more recent but looks they are lagging a bit.
I'll build from source then.
