### ISSUE TITLE
Auto-type not working for terminal in Ubuntu 22.04.1

### ISSUE THREAD

**Issue by guidanoli** [keepassxreboot/keepassxc#8405]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

I recently upgraded my Ubuntu from 20.04 to 22.04.1 and the Auto-type feature no longer works for the terminal.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Open the terminal and have it selected
2. Select an entry on KeepassXC and trigger the Auto-type command (Ctrl+Shift+V)

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
I expected it to hover over to the terminal and type the username and password.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
It changed context to the terminal but nothing was typed.

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.1
Revision: 5916a8f

Qt 5.15.3
Debugging mode is disabled.

Operating system: Ubuntu 22.04.1 LTS
CPU architecture: x86_64
Kernel: linux 5.15.0-46-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.12.1

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: Gnome
Windowing System: X11

**Comment by droidmonkey** [comment]
Did the terminals window title change? Can you use the global Auto-Type shortcut instead?

**Comment by guidanoli** [comment]
> Did the terminals window title change?

No, it's the same.

> Can you use the global Auto-Type shortcut instead?

I am avoiding global shortcuts for security reasons.

**Comment by guidanoli** [comment]
You can easily reproduce this bug on a fresh Ubuntu 22.04.1 installation (or virtual machine).

**Comment by droidmonkey** [comment]
We just lower our window and start typing through X11. I know you wrote X11 in the debug info, but are you sure you aren't running Wayland and KeePassXC through XWayland? I doubt this is an actual bug in our program. We know nothing about the window we are typing into and don't have any special code regarding that type of scenario.

Why do you think global shortcuts pose a security risk? We ask for your confirmation by default before typing anything.

**Comment by guidanoli** [comment]
Apparently, I am using Wayland according to [this](https://unix.stackexchange.com/a/355476) procedure. :-)

**Comment by droidmonkey** [comment]
Well that would certainly be why the typing doesn't work. You'll either have to go full X11 or use copy/paste.

**Comment by guidanoli** [comment]
Thanks! I found out that one can switch between Wayland and Xorg on the log-in screen.

**Comment by igorpupkinable** [comment]
Documentation [says](https://keepassxc.org/docs/KeePassXC_UserGuide.html#_auto_type):

> Auto-Type will be disabled when run with a Wayland compositor on Linux. To use Auto-Type in this environment, you must set QT_QPA_PLATFORM=xcb or start KeePassXC with the -platform xcb command-line flag.

I have tried both options with no luck.
Am I missing anything or this approach still not working in Wayland?

I used the following commands to execute KeePassXC by tweaking _Exec_ entry in _/var/lib/snapd/desktop/applications/keepassxc_keepassxc.desktop_:
- `env BAMF_DESKTOP_FILE_HINT=/var/lib/snapd/desktop/applications/keepassxc_keepassxc.desktop /snap/bin/keepassxc -platform xcb %f`
- `env BAMF_DESKTOP_FILE_HINT=/var/lib/snapd/desktop/applications/keepassxc_keepassxc.desktop QT_QPA_PLATFORM=xcb /snap/bin/keepassxc %f`

**Comment by igorpupkinable** [comment]
I guess the warning explains it if run from terminal directly:
```
~$ QT_QPA_PLATFORM=xcb /snap/bin/keepassxc
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
```

**Comment by igorpupkinable** [comment]
https://github.com/keepassxreboot/keepassxc/issues/2281
