### ISSUE TITLE
Error starting KeePassXC after windows update

### ISSUE THREAD

**Issue by frenciszak** [keepassxreboot/keepassxc#8406]
After windows update the following error occurs on trying to run KeePassXC 
_The code execution could not proceed because VCRUNTIME140_1.dll_

System Windows 10

**Comment by frenciszak** [comment]
Microsoft as usual - update seems to remove C++ Redistr [download link](https://docs.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170)

**Comment by JohnLGalt** [comment]
Do you know which update caused this to be removed, as that makes no sense for them to do so....
