### ISSUE TITLE
Add 'Has Custom Auto-type option enabled' to context menu/UI so I can see which entries

### ISSUE THREAD

**Issue by ghost** [keepassxreboot/keepassxc#8409]
## Summary
I don't or am not able to custom autotype every entry so my DB is about 40/60 custom/not-custom-probably-won't-work Auto-Type. Being able to quickly see which keys have a custom Auto-Type enabled or not and then being able to ctrl-shift-V rather than having to 'go into' the entry to see this. Having an indicator would be helpful. 

## Examples
Here is something like I am thinking of
![image](https://user-images.githubusercontent.com/56930329/186637562-d690f0bc-839b-4d5e-88c6-b1fd439e7ee3.png)

## Context
Saves me having to go 'into' each entry to see if I have already configured a custom (and so working) AT entry or not.

How you indicate that in the UX (i.e. what icon to use, I have no preference).

**Comment by droidmonkey** [comment]
That information is shown in the preview pane for the entry when it's selected. I don't understand your use case though, I recommend using the global autotype shortcut instead for a better workflow.
