### ISSUE TITLE
How to resolve file conflict in large databases?

### ISSUE THREAD

**Issue by C0rn3j** [keepassxreboot/keepassxc#841]
My Nextcloud folder went out of sync, making me add/change entries on 2 PCs, and when it synced again I ended up with two database files.

Is there a way to view history of all entries sorted by date, so I can easily see which changes were made in each database file? If not, I'd welcome that feature.

There are hundreds of entries so manually looking throughout the database is not an option.

**Comment by phoerious** [comment]
You can use the merge feature to automatically merge in changes. But do it on a copy to be on the safe side.

**Comment by C0rn3j** [comment]
Thanks, used the merge feature, hope everything is okay.

Would still prefer to do this manually and actually be sure that I'm adding stuff correctly via a history log.

For example if I changed the notes of a single entry on both machines I think I'd lost something in the process?

**Comment by louib** [comment]
@C0rn3j Unfortunately, yes. Right now the merge functionality uses the entry modification date and keeps the newest version of the entry. So if you modified an entry in both database, There a possibility that you lost some of the changes. I'll open an issue for that.

**Comment by jeroen7s** [comment]
@louib doesn't keepassXC add the older version of the password in the history of the entry?

**Comment by louib** [comment]
@jeroen7s I don't think so. Right now the only mode available is `KeepNewer`, and the behavior is to replace the existing entry when it's older than the other entry.

```c++
case KeepNewer:
    if (timeExisting < timeOther) {
        // only if other entry is newer, replace existing one
        removeEntry(existingEntry);
        addEntry(otherEntry->clone(Entry::CloneNoFlags));
    }
```

**Comment by nirfse** [comment]
It'd be nice to have a changelog after merging is finished, at least in a dialog window with new keys paths. Thus, one could have an option to manually check merged keys. At the moment, merging is absolutely blind.

**Comment by droidmonkey** [comment]
The  code that louib mentions above was changed in 2.2.2 to include merging history.

**Comment by droidmonkey** [comment]
This is covered by #1152, closing in favor of that one.
