### ISSUE TITLE
ungoogled-chromium (flatpak): no DB connection

### ISSUE THREAD

**Issue by chymian** [keepassxreboot/keepassxc#8410]
## Overview
keepassxc does not work together with ungoogled-chromium, flatpak installation.
this feels/behave similiar to [Tor Integration Not Working - Database Connection #7319 ](https://github.com/keepassxreboot/keepassxc/issues/7319)
ungoogled-chromium is only available for debian as flatpak. no debs build on OBS any longer.
since it's a flatpak installation, I dare to open another ticket, even so, it might be the same pblm?

## Steps to Reproduce
1. `flatpak install com.github.Eloston.UngoogledChromium`
2. install the web-store extension and follow the setup-procedure: https://github.com/NeverDecaf/chromium-web-store
3. install keepassxc extension from the web-store into the browser
4. setup keepassxc: allow chromium & setup advanced config-path:
  `./.var/app/com.github.Eloston.UngoogledChromium/config/chromium/NativeMessagingHosts/`

## Expected Behavior
like FF or with the regular deb-install of chromium the extension should be able to connect to keepassxc-DB.

## Actual Behavior
starts with the message: `Cannot connect to KeePassXC. Check that browser integration is enabled in KeePassXC settings.`
clicking on reload gives: `Key exchange was not successful.`

## Context
on my quest to get a more secure browser up and running, I have the same behavior with the tor-browser: https://github.com/keepassxreboot/keepassxc/issues/7319#issuecomment-1227081108

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.2
Revision: e9b9582

Qt 5.15.2
Debugging mode is disabled.

Operating system: Debian GNU/Linux 11 (bullseye)
CPU architecture: x86_64
Kernel: linux 5.15.39-3-pve

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (only unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.8

[NOTE]: # ( Pick choices based on your environment )
Operating System: debian bullseye
Desktop Env: KDE
Windowing System: X11
ungoogled chromium: Version 104.0.5112.102 (Official Build, ungoogled-chromium) (64-Bit)
flatpak:
ungoogled-chromium                       com.github.Eloston.UngoogledChromium           104.0.5112.102    stable    system

**Comment by droidmonkey** [comment]
We cannot talk to a flatpak until the owner of that Flatpak enabled the (now experimental) native messaging portal. This bug should be filed with ungoogled chromium team, not us. 

You are also using a very outdated version of keepassxc.

**Comment by chymian** [comment]
> We cannot talk to a flatpak until the owner of that Flatpak enabled the (now experimental) native messaging portal. This bug should be filed with ungoogled chromium team, not us.

ok, I open a issue with them.

> You are also using a very outdated version of keepassxc.

that's the only one in bullseye (incl. backports) which I had to use, to get SecretService up and running. 
which did not work with the snap, I was using before.
should that work with the keepassxc-flatpak or appimage? any success stories?

**Comment by chymian** [comment]
the bug with ungoogled-chromium is here: https://github.com/ungoogled-software/ungoogled-chromium-debian/issues/308

**Comment by chymian** [comment]
work-around:
for reference: there is no official deb of ungooled-chromium at the time of writing, but a supported fork from @berkley4:

https://github.com/berkley4/ungoogled-chromium-debian/

which means manual updating, but at least it works with keepassxc.

**Comment by droidmonkey** [comment]
We offer numerous ways to get the latest version of KeePassXC.  I do recommend the flatpak, but you can also download our appimage or use a distro ppa.

**Comment by chymian** [comment]
> > You are also using a very outdated version of keepassxc.
> 
> that's the only one in bullseye (incl. backports) which I had to use, to get SecretService up and running. which did not work with the snap, I was using before. should that work with the keepassxc-flatpak or appimage? any success stories?

to answer my own question: the flatpack does not support secret service ATOW. 
it works with the appimage.
