### ISSUE TITLE
Unable to open attachments of type TXT "Cannot open file"

### ISSUE THREAD

**Issue by trallnag** [keepassxreboot/keepassxc#8411]
## Overview

I'm unable to open attachments of type TXT. Double clicking on an attachment in the advanced tab shows the following error:

```
Unable to open attachment:
Cannot open file "recovery-codes.txt"
```

## Steps to Reproduce

1. Add a TXT file as an attachment to an entry.
2. Try to open it.

## Expected Behavior

File should open. For example in Notepad.

## Actual Behavior

File does not open. Error is shown.

## Context

Debug info:

```
KeePassXC - Version 2.7.1
Revision: 5916a8f

Qt 5.15.3
Debugging mode is disabled.

Operating system: Windows 10 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.22000

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 2.18.1
```

Operating System: Windows 11

**Comment by droidmonkey** [comment]
I cannot replicate on Windows 11. Make sure you have a program associated with TXT files.

**Comment by trallnag** [comment]
@droidmonkey, that was indeed the problem. Assumed a basic file type like TXT already has a default in W11. Thanks for the hint
