### ISSUE TITLE
Copy password in global auto input is not available

### ISSUE THREAD

**Issue by BrsyRockSs** [keepassxreboot/keepassxc#8418]
## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Opens the global auto-type shortcut dialog box
2. Right click any item
3. Copy password is gray and unavailable

---
Many applications do not support analog input and can only use the method of copying passwords. I checked the update log and found no relevant updates. It may be that I missed something. I hope you can help me solve my problems

os:win10 21h2

**Comment by droidmonkey** [comment]
That means your entry doesn't have a password.

**Comment by BrsyRockSs** [comment]
> That means your entry doesn't have a password.

I can use the old version normally. The problem occurred only after I updated the version a few days ago. I just created a new database, and the problem can still be reproduced. Please look at the picture.
Only the copy password is not available. The input sequence can read the password normally. The entry itself also has a password
---
![photo_2022-08-30_10-02-26](https://user-images.githubusercontent.com/46119880/187332174-71a78ee4-d733-4f4a-874a-5db41e588271.jpg)
![photo_2022-08-30_10-02-38](https://user-images.githubusercontent.com/46119880/187332183-2b65d037-f233-48cf-aab7-328f196c0904.jpg)

**Comment by droidmonkey** [comment]
Update to 2.7.1

**Comment by BrsyRockSs** [comment]
> Update to 2.7.1

My current version is 2.7.1

I went to test again. This problem occurs in the global input box of the new version of 2.7.0 and 2.7.1.

2.6.6 no problem

**Comment by droidmonkey** [comment]
Oops this hasn't been released yet, but it was fixed: https://github.com/keepassxreboot/keepassxc/pull/7987

**Comment by BrsyRockSs** [comment]
> Oops this hasn't been released yet, but it was fixed: #7987

I'm glad this bug has been fixed. Thank you for your answer
