### ISSUE TITLE
[Windows/Debian] CSV export doubles doublequote character in password field

### ISSUE THREAD

**Issue by Stormrice** [keepassxreboot/keepassxc#8421]
## Overview
When I export my database to CSV format, from KeePassXC 2.7.1 (Windows 10) or from KeePassXC 2.6.2+dfsg.1-1 (Debian 11), the entries containing doublequote character (") in the password field are doubled.

## Steps to Reproduce
1. Create an empty database
2. Create an entry with a password containing at least one doublequote char (like TE"ST for example)
3. Export to CSV format

## Expected Behavior
The CSV entry should contain only one doublequote char by doublequote char in KeePassXC.

## Actual Behavior
The CSV entry contains 2 doublequote chars by doublequote char in KeePassXC
-> TE""ST

## Context
Windows 10:
KeePassXC - 2.7.1
Revision: 5916a8f

Debian 11:
KeePassXC - 2.6.2
Revision: e9b9582

Thank you

**Comment by Stormrice** [comment]
Same behavior for at least one other field: Title

**Comment by michaelk83** [comment]
Sounds like just standard CSV escaping. Though it should also end up quoted, I think. `tes"t` -> `"tes""t"`.

**Comment by droidmonkey** [comment]
That is CSV escaping.
