### ISSUE TITLE
Get the access to Database with only password without Windows Hello/Security PIN

### ISSUE THREAD

**Issue by sunnamed434** [keepassxreboot/keepassxc#8422]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
After I wrote my password to database, Keepass asking me to write the PIN I can just click "Cancel" or close the menu and it gives me the access to actual database with my passwords.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Open Keepass
2. Write Database password
3. Close the menu with asking PIN

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
It should ask me to re enter the password, because this I wrote nothing and this password is wrong actually.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
I can close the menu with the PIN, and it opens for me the access to database with passwords.

## Context
![image](https://user-images.githubusercontent.com/65300126/187235999-d99ec72b-3547-4384-b7b2-777c67252b99.png)

[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.1
Revision: 5916a8f

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows

**Comment by phoerious** [comment]
The PIN is used for setting up quick unlock. If you don't enter the correct PIN, quick unlock will not be used. The UX is quirky, but it's working as intended.
