### ISSUE TITLE
Allow multiple URLs

### ISSUE THREAD

**Issue by juandavidg890121** [keepassxreboot/keepassxc#8423]
## Summary
Allow the ability to add multiple URLs to an Entry, so that in some cases the same user/pass is used in multiple places (usually for development)

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )
In the URL section, you could add more than one element if you want
![image](https://user-images.githubusercontent.com/36093711/187244008-77bd77c5-dc0f-4e6b-9c75-03b8d4d97a9f.png)

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
There are both personal and work URLs where the same user/pass combination is used in more than one place (where security elements of not using the same credentials are irrelevant)

**Comment by droidmonkey** [comment]
Already possible, go to the browser integration tab when editing entry.
