### ISSUE TITLE
Allow Password settings to be saved against individual entry.

### ISSUE THREAD

**Issue by dnai05** [keepassxreboot/keepassxc#8424]
## Summary
i have recently come across a couple of sites that have restrictions on what special characters are allowed in a password. Rather than having to remember these restrictions in the future it would be nice to have them saved against the entry.

Examples
1. Alinta Energy
The value you entered for "Password" contains forbidden characters. Please remove any of the following characters to continue:  <  >  *  ?  &  %  !  #  "  ;  \  =  +  ..  :  (  )  
2. MyGov
Your password can have any of the following characters: ! @ # $ % ^ & *

At present the options you choose on Generate Password page are saved as the new default.

## Suggestion
1. Add option to save settings for special characters against an individual entry.  Maybe a tick box on Character Types panel like 'Save custom character settings'. You could even name these custom settings so they could be used elsewhere.
- OR -
2. Completely change how Generate Password settings are saved. You start with a default "template" and you have the option to save selected settings as a custom "template" that is linked to the entry. You would also need the option to remove a custom template and return to the default template. And if templates are named you could add the option to select a previously saved template.

**Comment by dnai05** [comment]
Also noted #2628

**Comment by droidmonkey** [comment]
The solution we are interested in is in the linked issue above.
