### ISSUE TITLE
Provide view/report of changed entries

### ISSUE THREAD

**Issue by dnai05** [keepassxreboot/keepassxc#8426]
## Summary
I have been making some changes recently and wondered if there was a view or report that would show all changes made between dates/N days ago?

##Solution
I imagine the report would look something like the Entry History page but it would show all entries in the database in the selected date range.

Last Modified               | Entry Title | Age             | Difference
29/08/2022 11:00 AM | My Bank   | 1 hour         | Notes, Password

**Comment by michaelk83** [comment]
You should search previous issues. #7176
