### ISSUE TITLE
Program hangs when merging with nextcloud-hosted databasee

### ISSUE THREAD

**Issue by andreareina** [keepassxreboot/keepassxc#8427]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
Program hangs when merging with a database file on a nextcloud instance accessed via a davsfs mount.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Mount nextcloud account via Pop!OS 22.04 LTS/GNOME Settings -> Online Accounts
2. Try to merge local database file with davsfs-mounted remote database file

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Merge completes, doesn't hang

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
KeepassXC becomes unresponsive and has to be `kill`ed

## Context
[NOTE]: # ( Give us any additional information you may have. )
Merging with a local database file works.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.1
Revision: 5916a8f
Distribution: Flatpak

Qt 5.15.5
Debugging mode is disabled.

Operating system: KDE Flatpak runtime
CPU architecture: x86_64
Kernel: linux 5.18.10-76051810-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey

Cryptographic libraries:
- Botan 2.19.1

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux, Pop!OS 22.04
Desktop Env: Gnome
Windowing System: X11

**Comment by droidmonkey** [comment]
Make sure you have direct write saves enabled

**Comment by andreareina** [comment]
Same behavior whether I set `Directly write to database file` or `Temporary file moved into place`. Actually the hang happens just trying to open the remote database file...

**Comment by droidmonkey** [comment]
Check your davfs configuration, you likely cannot access the file at all. In other words, this doesn't appear to be a problem on our side... we are getting stuck in a load loop / delay on the davsfs side. So this could possibly be a Qt bug, but not in our code.

**Comment by andreareina** [comment]
I'm able to copy remote to local, merge, then copy local to remote. Any ideas how I can continue to investigate?

**Comment by droidmonkey** [comment]
Try using our appimage instead of flatpak 
This might also be a bug in the flatpak portal.
