### ISSUE TITLE
DIGEST file ending not intuitive naming for a human

### ISSUE THREAD

**Issue by Avispa** [keepassxreboot/keepassxc#8432]
## Overview
*.DIGEST file ending is not intuitive to a human. Is this a Mac/OSX thing?

## Expected Behavior
md5 checksum -> *.md5
sha(1) checkums -> *.sha
sha256 checkums -> *.sha256

## Actual Behavior
Having a file without a header and random numbers called "*.DIGEST".

## Context
I actually did a quick internet search if this is the new hip/woke/sexy hashing algorithm but nothing turned up.

So I ended up iterating through _md5_, _sha1_ and _sha256_ to look for a match with the "DIGEST-Hash" file. Which on _Windows_ is a bit more cumbersome than on _Linux_. Nevertheless it could be avoided at all with a helpful file name 

YES, it is explained on a sub-page of keypassxc.org somewhere and therefore mentioned that "DIGEST" is actually sha2.
 _BUT_ lets say for 1/4 of the users there wouldn't even be the need to dig through the webpage or search the internet for an explanation on how to use an arbitrary file if it would be named self-explanatory OR would have at least a header. (Though I don't know how the latter plays along with sha2sum and other programs.)

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows

**Comment by droidmonkey** [comment]
Didn't you read the page on exactly how to verify the file? 

https://keepassxc.org/verifying-signatures/

At the bottom under Basic Integrity Check

**Comment by Avispa** [comment]
I understand that this is probably yours/somebodies free time project and that there are at this point in time about 500 issues. However, if I took the time -- also in my free time -- to give, I would say, profound and detailed criticism (for improvement) I would at least expect you to (speed) read everything. Your answer implies you didn't even read/comprehend the title not to mention the post. So I don't know how/what to respond to your post in a polite manner ... 

Maybe: _Try again?_

**Comment by droidmonkey** [comment]
Yah, we spent the time to write out a detailed step-by-step way to verify the downloads. If you read that and follow the instructions, it is irrelevant what the extension of the file is.
