### ISSUE TITLE
KPH: and other Placeholders/Options as autocomplete / InfoListing

### ISSUE THREAD

**Issue by xstable** [keepassxreboot/keepassxc#8434]
## Summary
Keepassxc has many features, but many of them are not intuitive notable by using it. 
For Example the KPH: Feature: 

![image](https://user-images.githubusercontent.com/1778068/187857139-aa734eae-2f7b-4d8a-882a-0a6c9e3eb34b.png)

Or in the URL-Field... Awesome features... running stuff in CLI (on Linux) by using `cmd://` or Placeholders for username, passwort, or additional settings...  
![image](https://user-images.githubusercontent.com/1778068/187857710-c56cb3e7-4c3c-49b0-af1c-add1444c6b48.png)

All Awesome Stuff, but who knows??!

I wish, that there is at least something like an (?) Icon, that show you, what entries are possible. 
Much better would be to have something like an auto-complete-field, or Dropdown-Select field, which shows the possible values.

Not only in the "Advanced" Tab, but only for visualizing purposes what I mean:

![image](https://user-images.githubusercontent.com/1778068/187858258-24055c93-2eb1-40a4-88c1-7fb151c21c5f.png)

BTW: Would be nice to be able to re-sort the additional Properties, after created. 
Currently if you want to change the order, you need to remove them, and add them in the right direction again:

![image](https://user-images.githubusercontent.com/1778068/187859392-5cf66c26-cafc-4b5c-ab10-d666cf50ecc6.png)

**Comment by phoerious** [comment]
The entire system for custom strings needs to be redone. This is known to us and will happen at some point, so I'm closing this.
