### ISSUE TITLE
Autotype seems to stutter/is slow when entering credentials into the appropriate fields

### ISSUE THREAD

**Issue by MrDoodlezz** [keepassxreboot/keepassxc#8438]
## Overview
After the corresponding database entry for Autotype has been selected and confirmed, the individual characters of the entries are sometimes (apparently website-dependent?) entered very slowly into the fields compared to before, despite the standard Autotype sequence.

## Steps to Reproduce
1. Open the website you want to login.
2. Start the Autotype feature (I use the universal shortcut).
3. Select and confirm the entry.
4. Watch and wait for the login details to be entered and automatically confirmed.

## Expected Behavior
I expect the **quick** entry, confirmation as before.

## Actual Behavior
The login data is entered too **slowly** for my needs.

## Context
A week or two ago, I got a newer device from the same company.
The device is managed via Jamf, I have admin rights, though slightly limited.
I don't think the KeePassXC version has changed between the exchange and it worked fine with the previous device.

KeePassXC - Version 2.7.1
Revision: 5916a8f

Qt 5.15.2
Diagnosemodus ist deaktiviert.

Betriebssystem: macOS 12.5
CPU-Architektur: x86_64
Kernel: darwin 21.6.0

Aktivierte Erweiterungen:
- Auto-Type
- Browser-Integration
- SSH-Agent
- KeeShare
- YubiKey
- Schnelle Entsperrung

Kryptographische Bibliotheken:
- Botan 2.19.1

**Comment by droidmonkey** [comment]
What is the website(s)? Browser? 

Have you checked the Auto-Type settings to make sure you delay between keys hasn't been greatly increased by accident?

**Comment by MrDoodlezz** [comment]
Basically, with any website – it doesn't matter whether it's internal or external, like Github – there's no noticeable difference for me.

For a very few entries I added additional delay.

I have also thought about the possibility of other apps interfering. Here are a few apps that I or the administration have installed that are almost always running in the background (some of them also use shortcuts, although they don't interfere):

Amphetamine.app
DeepL.app _(uses shortcuts)_
GlobalProtect.app
Google Chrome.app
Jamf Connect.app
KeePassXC.app _(well, obviously 😅)_
Microsoft Defender.app
Microsoft Excel.app
Microsoft Outlook.app
Microsoft Teams.app
Spectacle.app _(uses shortcuts)_

I also use quite a few extensions for Chrome. Simply deactivating them has made no difference.
[HTTPS Everywhere](https://chrome.google.com/webstore/detail/https-everywhere/gcbommkclmclpchllfjekcdonpmejbdp)
[KeePassXC-Browser](https://chrome.google.com/webstore/detail/keepassxc-browser/oboonakemofpalcgghocfoadofidjkkk)
[Neat URL](https://chrome.google.com/webstore/detail/neat-url/jchobbjgibcahbheicfocecmhocglkco)
[Tab Groups Extension](https://chrome.google.com/webstore/detail/tab-groups-extension/nplimhmoanghlebhdiboeellhgmgommi)
[Tab to Window/Popup - Keyboard Shortcut](https://chrome.google.com/webstore/detail/tab-to-windowpopup-keyboa/adbkphmimfcaeonicpmamfddbbnphikh)
[Tampermonkey](https://chrome.google.com/webstore/detail/tampermonkey/dhdgffkkebhmkfjojejmpbldmpobfkfo)
[uBlock Origin](https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm)
[uMatrix](https://chrome.google.com/webstore/detail/umatrix/ogfcmafjalglgifnmanfmnieipoejdcf)
[Xinet CM](https://chrome.google.com/webstore/detail/xinet-cm/eheonhmffkmkgmbiachlhegkmbgojabn)

What's also strange is that it works better now and then - but I can't pinpoint the cause at the moment.

**Comment by MrDoodlezz** [comment]
Here's some basic specs about the MacBook itself, just in case:

macOS Version: 12.5.1 (21G83)
Model: MacBook Pro (16", 2021)
Chip: Apple M1 Pro
RAM: 32 GB

I guess with all these apps and extensions, it's hard to figure out for you. Anyway, I'll just wait and see, maybe with the next version of KeePassXC it will be better again or one day I'll find out myself what's blocking the flow here.

**Comment by droidmonkey** [comment]
There is nothing inherently wrong with our Auto-Type, it works flawlessly for everyone (except you in this case) so it is definitely something with your setup. We won't be making any changes or cannot possibly determine fault in this situation.

**Comment by MrDoodlezz** [comment]
While I would say that saying _Auto-Type works **flawlessly** for **everyone**_ is highly definitional and it seems a bit like looking the other way*, I understand the decision.

*Glancing at the list of other Auto-Type issues, for example #7722, for which I have since found and posted a workaround myself.

**Comment by droidmonkey** [comment]
I'm referring to the typing speed when I say it works flawlessly. There are a million edge cases on all the platforms.
