### ISSUE TITLE
Ability to fully customize auto-type list

### ISSUE THREAD

**Issue by ahmetsait** [keepassxreboot/keepassxc#8439]
## Summary
Currently KeePassXC (v2.7.1) allows users to change the default auto-type sequence for an entry and it also allows adding different auto-type sequences associated with different window titles. The `Perform Auto-Type` menu lists the default and some predefined common sequences for convenience such as `{USERNAME}`, `{PASSWORD}` and so on. It does _not_ list window specific auto-type sequences.

This issue proposes a more generalized auto-type list that can be edited by the user and conveniently access them via the `Perform Auto-Type` menu. Upon creating an entry, KeePassXC would initialize the list with the group default plus some predefined common sequences. The user can then select `Use custom Auto-Type list:` instead of the default `Inherit default Auto-Type list from the group` which enables the auto-type sequence list for editing.

Ideally we should merge window-specific sequences into this feature such that entries in this list can have a window title associated, in which case the `Perform Auto-Type` action would choose the first sequence that matches the active window title, or simply the first sequence if no title matches.

## Context
I often miss this feature because window-title specific sequences are very fragile and I never managed to make them work so I currently workaround this by cloning entries with reference. Also some properties like TOTP doesn't support `{REF}` so it's not a perfect solution.

**Comment by droidmonkey** [comment]
> It does not list window specific auto-type sequences.

That is because you should be using the global Auto-Type shortcut to invoke the sequence for the focused window.

Please read the user guide for more information. We won't be making more changes to the "entry level" auto-type menu.
