### ISSUE TITLE
File operations (saving) block UI

### ISSUE THREAD

**Issue by duk3luk3** [keepassxreboot/keepassxc#844]
When opening or saving a database, the KeePassXC UI locks up.

## Expected Behavior

* I would like to be able to continue to use KeePassXC while saving is in progress, e.g. to search for entries.
* KeePassXC should stay responsive when opening a database

## Current Behavior

If the database file is on a slow filesystem (such as a CIFS mount on the other side of the world), KeePassXC locks up until the save operation is complete.

## Possible Solution

File operations should be done in a non-blocking way.

## Steps to Reproduce (for bugs)

1. Put a database file on a mount in a slow remote location
2. Open the database file (issue is most visible when using the Database -> Recent Databases menu, as the menu will be stuck open while the file is loading)

## Context

Whenever I switch to the KeePassXC application to look up an entry and see that the database is dirty 
(has unsaved changes) I reflexively hit Ctrl-S to save the database.

So my workflow is:

* "I need to switch to KeePassXC to look up a password"
* "Oh, the database is dirty, better hit Ctrl-S"
* KeePassXC locks up while saving
* I have to wait for saving to complete before I can use the search function
* Unhappy me :(

## Debug Info
KeePassXC - Version 2.2.0
Revision: caa49a8ef3ee28ed478192389b21d61107b3b8e0

Libraries:
- Qt 5.9.1
- libgcrypt 1.8.0

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 4.12.3-1-ARCH

Enabled extensions:
- KeePassHTTP
- Auto-Type
- YubiKey

**Comment by phanimahesh** [comment]
Tip: https://github.com/nirs/slowfs will help in testing the effects of slow file systems on usability.

**Comment by droidmonkey** [comment]
Good catch!
