### ISSUE TITLE
KeePassXC 2.7.1 BAD Signature

### ISSUE THREAD

**Issue by Crafter863** [keepassxreboot/keepassxc#8440]
Having problem verifying after download. I have followed instructions on https://keepassxc.org/verifying-signatures/. This is the result I get:

gpg --verify keepassxc-2.7.1-src.tar.xz.sig keepassxc-2.7.1-8.src.tar.xz.rpm
gpg: Signature made Wed 06 Apr 2022 12:22:57 PM CDT
gpg:                using RSA key C1E4CBA3AD78D3AFD894F9E0B7A66F03B59076A8
gpg: BAD signature from "KeePassXC Release <release@keepassxc.org>" [unknown]

This is what I imported from the link noted above for the public key, which was:

gpg: key CFB4C2166397D0D2: "KeePassXC Release <release@keepassxc.org>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1

The results from gpg--list-keys:

gpg --list-keys CFB4C2166397D0D2
pub   rsa4096 2017-01-03 [SC]
      BF5A669F2272CF4324C1FDA8CFB4C2166397D0D2
uid           [ unknown] KeePassXC Release <release@keepassxc.org>
sub   rsa2048 2017-01-03 [S] [expires: 2024-12-04]
sub   rsa2048 2017-01-03 [S] [expires: 2024-12-04]

The above matches the information from the link given.

I am expecting gpg --verify to indicate GOOD signature from KeePassXC

Running a KVM machine, Linux Mint 20 is host, Rocky Linux 9.0 (Gnome) is guest I want to install KeePassXC into.

Thanks for any assistance.

**Comment by droidmonkey** [comment]
We don't sign the rpm release. You will have to download the corresponding source release from our releases page that is for that signature file.
