### ISSUE TITLE
how to fix  Cannot connect to KeePassXC. Check that browser integration is enabled in KeePassXC settings. keepass extension

### ISSUE THREAD

**Issue by justarandomusernamelol** [keepassxreboot/keepassxc#8442]
i am using librewolf and am getting this issue please help i have been trying to find a solution for over three hours

**Comment by droidmonkey** [comment]
Read the extension troubleshooting guide. Also search the browser extension repository, there are issues discussing how to get it to work.

**Comment by justarandomusernamelol** [comment]
yeah but am not getting what the troubleshooting guide is saying

**Comment by droidmonkey** [comment]
We don't directly support librewolf. You have to configure an additional browser in the advanced part of the browser integration settings.

**Comment by justarandomusernamelol** [comment]
wait now i understand this was a location but i dont find the native-messaging-hosts file or whaterver it is

**Comment by justarandomusernamelol** [comment]
~/.librewolf/native-messaging-hosts was a location but i cant find the native messaging hosts file in the librewolf folder

**Comment by justarandomusernamelol** [comment]
a

**Comment by justarandomusernamelol** [comment]
i added librewolf but its still giving me the error

**Comment by ks09271** [comment]
Wow, this is _really_ sophisticated support, nothing to add!  So best I'll do away with this stuff and try to find something with _a little_ bit better user support - should be easy. :-|
