### ISSUE TITLE
KeepassXC interacts with HDCP on Windows and causes Moonlight/GFE sessions to end abruptly

### ISSUE THREAD

**Issue by Espionage724** [keepassxreboot/keepassxc#8446]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Use Moonlight to connect to a Windows host PC ([tip to stream desktop](https://github.com/moonlight-stream/moonlight-docs/wiki/Setup-Guide#using-moonlight-to-stream-your-entire-desktop))
2. Open KeepassXC on the remote-controlled Windows host PC
3. Remote session though Moonlight is ended and can't be resumed until KeepassXC is closed

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
KeepassXC to open and allow interaction from GFE session

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
KeepassXC interacts with something to cause the GFE session to end and stay disabled until KeepassXC is closed. Moonlight hints at DRM-protected content running on the host PC, and HDCP has to be enabled for GFE to work at all.

## Context
[NOTE]: # ( Give us any additional information you may have. )
I have a Windows 10 PC with NVIDIA graphics. NVIDIA's software includes the ability to stream games and programs called GeForce Experience (GFE), but only officially to their Shield device(s). Moonlight is an open-source client that allows game/app streaming to other non-Shield devices. In my case, I use Moonlight from a Linux laptop to stream the Windows Explorer desktop from my Windows computer; basically like VNC or Teamviewer.

After setting the Windows computer up to be headless and ready for only remote-control interactions, I started a game up that required a Microsoft log-in. I thought no problem, opened up KeepassXC, and ran into this.

Steam Remote Play connects and works no problem while KeepassXC is open.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.1

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 10

**Comment by droidmonkey** [comment]
https://keepassxc.org/docs/KeePassXC_UserGuide.html#_screenshot_security

**Comment by Espionage724** [comment]
> https://keepassxc.org/docs/KeePassXC_UserGuide.html#_screenshot_security

Thanks, that fixed that perfectly.

I think that page should mention HDCP for search indexing as I couldn't find it when looking for "KeepassXC HDCP".
