### ISSUE TITLE
Do not resolve {PASSWORD} placeholder in entry view

### ISSUE THREAD

**Issue by andusvan** [keepassxreboot/keepassxc#845]
Make a new config option to separate the showing of password in the edit view
from the showing of passwords in the list (maybe preview pane too?).

It would be nice, if I see the passwords in the edit view directly but not in the list.
In the list we can show the placeholders as stored in the database.

**Reason:** In an unsafe environment (i.e. customer) an administrator of this customer could look
over my shoulder while I'm making support. It's ok, if he sees his own passwords, but if
I'm careless he might spot passwords from another customer and this is more likely to happen, if the
password are shown in the list in plaintext too...

**Comment by TheZ3ro** [comment]
For list do you mean the entry list? Passwords shouldn't be visible.

This is already part of what i was thinking about the preview panel

**Comment by andusvan** [comment]
Yes, the entry list.
Password are always visible there.
I'm using keepassxc 2.2.0 under Fedora 26 (64 Bit).
Is this a (compilation) bug?

**Comment by phoerious** [comment]
Please go to Tools->Settings->Security and make sure "Show passwords in cleartext by default" isn't checked.

**Comment by andusvan** [comment]
It isn't checked.
I mean the password is showed (replaced) in the URL.
In keepassx is showing the placeholder instead and want this (old) behavior in keepaasxc too (via an special option).

**Comment by phoerious** [comment]
I don't understand. Why do you have your password in the URL field?

**Comment by andusvan** [comment]
Because there is a bug?! :-)
Ok, I have the following entry:

Title: Firewall
Username: root
Password: test-123
URL: cmd://putty -ssh -l {USERNAME} -pw {PASSWORD} 10.11.12.250

Any my URL is shown as:
cmd://putty -ssh -l root -pw test-123 10.11.12.250

In the old keepassx (2.0.3) the URL is still shown as entred in the edit field.

**Comment by TheZ3ro** [comment]
Ohhh now i get it. The placeholder is resolved and so the password is visible. Makes sense.

**Comment by phoerious** [comment]
Right, they should be replaced with a constant number of asterisks.
But it's also worth noting that specifying passwords on the command line is bad practice.

**Comment by andusvan** [comment]
> But it's also worth noting that specifying passwords on the command line is bad practice.
But sometimes the only way. It depends on the program you use.
And a special problem we have to solve: The database must work with Windows and Linux, therefore we use "putty" here...
I have a idea how to solve this, but this will be another "wishlist" report... ;-)
