### ISSUE TITLE
Version 2.7.1 doesn't detect yubikey

### ISSUE THREAD

**Issue by jpengelbrecht** [keepassxreboot/keepassxc#8450]
## Overview
setting up a challenge response doesn't detect yubi key 5c nano.  Other applications read the yubi key correctly. 

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1.  go to database Database security
2. go to challenge response
3. select yubi key from list

## Expected Behavior
yubi  5c nano key should show

## Actual Behavior
it says no yubi key detected

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - KeypassXC 2.7.1

[NOTE]: # ( Pick choices based on your environment )
Operating System:  macOs 12.5.1 Monterey

**Comment by phoerious** [comment]
KeePassXC isn't supported on iOS, I suppose you mean macOS?

I cannot reproduce this at all with a YubiKey 5C. I suppose you hit the Refresh button already?

**Comment by droidmonkey** [comment]
Did you actually set one of the slots to do challenge response? You need to do that first in a yubikey configuration tool.
