### ISSUE TITLE
'segfault at 8 ip [. .] error 4 in libQt5XcbQpa.so.5.15.3' on shutdown of PC

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [keepassxreboot/keepassxc#8452]
## Overview
In the syslog, every shutdown (or perhaps only on some shutdowns and perhaps - I can check - with differing numbers, though the initial '8' is constant):

`segfault at 8 ip 00007f622e951581 sp 00007ffc37ee67a0 error 4 in libQt5XcbQpa.so.5.15.3[7f622e916000+d2000]`

No actual problem seems to be caused.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Have KeePassXC running.
2. Shutdown.
3. Reboot.
4. Look in syslog.

## Expected Behavior
No segfault.

## Actual Behavior
Segault but seemingly no adverse consequences.

## Context

KeePassXC - Version 2.6.6
Revision: 9c108b9

Qt 5.15.3
Debugging mode is disabled.

Operating system: Linux Mint 21
CPU architecture: x86_64
Kernel: linux 5.15.0-47-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- libgcrypt 1.9.4

Operating System: Linux
Desktop Env: Cinnamon
Windowing System: X11

**Comment by phoerious** [comment]
This is most likely a bug in your Linux distribution or Qt itself. I am afraid we cannot really help you with this.
