### ISSUE TITLE
Ability to sign git commits using SSH keys stored in KeePassXC 

### ISSUE THREAD

**Issue by mendhak** [keepassxreboot/keepassxc#8453]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )

For the users that use KeePassXC as their SSH agent, having it also sign git commits would be a useful feature to have.  This would likely be done via a `~/.gitconfig` entry pointing at the KeePassXC executable, something like

```
[gpg]
format = ssh

[gpg "ssh"]
  program = /usr/share/keepassxc
```

So the next time user does a git commit with signing, it invokes the keepassxc executable (or something similar) which uses the right SSH key, password, etc. and signs it. 

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )

KeePassXC has the ability to act as an SSH agent.   Recently, support for [signing git commits with SSH keys was introduced](https://blog.dbrgn.ch/2021/11/16/git-ssh-signatures/).  And also, Github.com has [added support for it](https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification#ssh-commit-verification).  I also see [1Password introduced such a feature](https://blog.1password.com/git-commit-signing/).

Though, I can appreciate that this is a very specific feature and makes a lot of assumptions about what KeePassXC should/shouldn't be doing.

**Comment by droidmonkey** [comment]
We do not act as an ssh-agent, we add/remove keys to an existing ssh-agent. You should add your signing key to your ssh-agent of choice using KeePassXC. Alternatively, this is what I do, point to an encrypted version of your signing key on disk and use KeePassXC to provide the unlock password.

https://docs.github.com/en/authentication/managing-commit-signature-verification/telling-git-about-your-signing-key#telling-git-about-your-ssh-key
