### ISSUE TITLE
I would like a way to cull my available icons

### ISSUE THREAD

**Issue by amandabee** [keepassxreboot/keepassxc#8456]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )

I have been using KeePass for ~8 years and in that time I've added quite a few custom icons that I'm not using any more. I don't see any way to delete those from the available options. 

I know I can remove them from individual entries, but they're still available in the list. 

Some of them look really bad, eg: 
![image](https://user-images.githubusercontent.com/150791/189423412-05c860c7-aa92-49f3-9b56-61e0bb1c23d1.png) and so I replaced them with a default, but they still show up as options: 

![image](https://user-images.githubusercontent.com/150791/189424482-6a0390b1-3420-4cb5-aea6-db6feaaddd9f.png)

Some logos are there multiple times (because I clicked "get favicon", I'm guessing) and a lot of them are either blurrry or just not particularly informative. 

![image](https://user-images.githubusercontent.com/150791/189422717-d55438d5-bbf9-40e4-b0c0-c2f396eba401.png)

## Context
It is a relatively low priority, as it doesn't interfere with functionality, but it is still kind of annoying to have to look at all these weird, blurry icons. There must be a way to go in an take them out of the options.

**Comment by droidmonkey** [comment]
Database menu -> Database settings -> maintenance tab

Also documented in the user guide
