### ISSUE TITLE
In AutoType window, the check box follows the default state option setting

### ISSUE THREAD

**Issue by manueltarouca** [keepassxreboot/keepassxc#8458]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
As a KeepassXC whenever I pop out the AutoType window, I would like to have the "_Search all open databases_" checkbox checked by default.
The default state of this checkbox should be configured in the **Security** tab of **Settings** under the **Convenience** section.

## Examples
I'm not able to screenshot the AutoType window.

## Context
Whenever I use the AutoType windows, I always have to check the checkbox in order to find relevant items. With this feature it would save some clicks and time. Also it's not possible to TAB throught the options, so I'm forced to use the mouse.

**Comment by droidmonkey** [comment]
It is checked if no window association matches are found. Either delete window associations or disable the match title / url settings in the Auto-Type settings. 

You can also use the Ctrl + F keyboard shortcut to check the box in case a match is found you don't want to use. 

Use the up down arrows to navigate the dialog. Tab should work as well, it does for me.
