### ISSUE TITLE
Impossible to open kdbx file from a usb drive

### ISSUE THREAD

**Issue by JavaLuigi** [keepassxreboot/keepassxc#846]
When I try to open a kdbx file as normal user from my usb stick I get an error message called: permission denied. Opening the same file from desktop everything is fine.

Environment:
Ubuntu 17.04
Keepass XC 2.2.0

**Comment by JoeArcher007** [comment]
What is the thumb drive formatted as?

When you copy other items, does this also appear to happen? (txt files, etc).

**Comment by JavaLuigi** [comment]
The usb drive is ntfs formatted and no with other files pdf, txt, html I have no such problem.

**Comment by droidmonkey** [comment]
If you are using the snap, you need to type in /media in the filename area before you'll see the usb drive. This is a snapd bug.

**Comment by JavaLuigi** [comment]
That's right! When I type in the complete path and filename this error occurs. Maybe I try to use another version as snapd.
