### ISSUE TITLE
Management of Hardware (or Software) Security Keys

### ISSUE THREAD

**Issue by chrenderle** [keepassxreboot/keepassxc#8461]
## Summary
Add the option to add hardware keys and connect entries with them so that you know which website is connected with which hardware key.

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )

## Context
I'm using hardware security keys (like Yubikeys) for most of the accounts where the website offers the possibility to do this. When using hardware security keys, it is recommended to have 2 keys registered with the websites so that if you lose one you have one backup key. Initially I started using only 1 key but now I have 2. I am currently in the process of registering the second key on all websites that are connected with the first one. Currently I write in the text description of an entry which keys I have connected with which website. But I would like that to be an integrated feature. Another cool idea would be to add a property to indicate whether a service offers 2fa. Currently I just write 2fa_todo in the description so that I can later add the 2fa when I have the time. It would be cool to have this shown with a nice icon or so in the group view (or what ever it is called when you open a group). Another idea would be that you could add several pins/passwords for the hardware security keys since on some (like Yubikeys) you can add pins for the usage of the key.

I will look into implementing this myself but since I'm not good at C++ I don't know if I will go through with it.

**Comment by droidmonkey** [comment]
Use tags
