### ISSUE TITLE
Setting up TOTP in editing mode discards changes

### ISSUE THREAD

**Issue by soxhi8** [keepassxreboot/keepassxc#8462]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
Setting up a TOTP for an entry, that is currently open in editing mode and has received changes, will reload the editing pane and discard all open changes.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Create a new entry and save it.
2. Enter editing mode for the new entry and enter some details. P.e. some notes or a url.
3. Go to Entries -> TOTP -> Set up TOTP
4. Add the TOTP.
5. The editing pane will be reloaded and discard open changes.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Open changes are kept.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Open changes are discarded.

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.1
Revision: 5916a8f

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows

**Comment by droidmonkey** [comment]
#6838

**Comment by soxhi8** [comment]
Thank you very much for the quick response. I missed the other issue during my search.
