### ISSUE TITLE
KeePassXC doesn't properly switch back from dark appearance on Linux

### ISSUE THREAD

**Issue by yderi** [keepassxreboot/keepassxc#8465]
## Overview
Switching back from black theme appeareance to light does not switch the Keepassxc GUI appearance.

## Steps to Reproduce
Linux Mate 22.04
1. Switch to "Yaru-Mate-light" theme(or any light theme)
2. Start the KeepassXC
3. Switch to the dark theme for example "Yaru-Mate-dark", at this step Keepassxc will successfully switch to the dark theme.
4. Switch back to the light theme for example "Yaru-Mate-Light", at this step only a windows title will switch to a light theme, the rest of the GUI remains in a dark theme(panel bar, groups, items, and so on.)

## Expected Behavior
Expected the whole application GUI will switch to the light theme accordingly.

## Actual Behavior
It remains in a dark theme and only restarting of application can fix it.

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.1
Revision: 5916a8f

Qt 5.15.3
Debugging mode is disabled.

Operating system: Ubuntu 22.04.1 LTS
CPU architecture: x86_64
Kernel: linux 5.15.0-47-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.19.1

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: Mate
Windowing System: X11

**Comment by droidmonkey** [comment]
Duplicate, https://github.com/keepassxreboot/keepassxc/issues/7817
