### ISSUE TITLE
Crash during unlock

### ISSUE THREAD

**Issue by mpas97** [keepassxreboot/keepassxc#8467]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
Crash when unlocking a DB using the snapshots builds. 
Not working with the newest (commit d181f80), nor with oldest available build from 2022-09-05 20:08 (commit bdeef63).
Not working with a new empty DB (pwd only) nor my personal DB (pwd + yubikey).

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Install snapshot on macOS 12.5.1 (x86_64)
2. Open existing DB

## Expected Behavior
It should open the DB normally.

## Actual Behavior
The app crashes:
```
Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000000
Exception Codes:       0x0000000000000001, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace SIGNAL, Code 11 Segmentation fault: 11
```

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - snapshot
Revision: bdeef63

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS 12.5.1 (x86_64)

Diagnostic report: [KeePassXC-2022-09-13-114738.txt](https://github.com/keepassxreboot/keepassxc/files/9555861/KeePassXC-2022-09-13-114738.txt)

**Comment by droidmonkey** [comment]
Just tested the latest snapshot on macOS and it didn't crash for me on unlock. Try reinstalling with all browsers closed.

**Comment by mpas97** [comment]
Also with no browser open during install and DB open, it crashes for me.

**Comment by droidmonkey** [comment]
Unfortunately your crash dump doesn't have the symbols for keepassxc in it. Need to check what's going on here.

**Comment by mpas97** [comment]
When I disable QuickUnlock, it doesn't crash.

**Comment by droidmonkey** [comment]
Ok that certainly narrows it, thank you

**Comment by droidmonkey** [comment]
Actually wait a sec, it is impossible to use TouchID/QuickUnlock on the snapshot build in macOS. The application must be signed to use it. Did you build and sign a snapshot yourself?

**Comment by mpas97** [comment]
I use the ones from https://snapshot.keepassxc.org. Nothing built/signed on my own. But if Apple kills something due to missing signature, this could explain the crash.

**Comment by droidmonkey** [comment]
Nah this is a bonefide crash, but you shouldn't be able to enable quickunlock at all which is interesting.

**Comment by mpas97** [comment]
See #8639

**Comment by droidmonkey** [comment]
This looks to be the same problem with the same crash point. Closing this in favor of the above.
