### ISSUE TITLE
Newlines missing when copy + pasting notes text

### ISSUE THREAD

**Issue by davidak** [keepassxreboot/keepassxc#8469]
## Overview

When i copy and paste text from notes, the newlines are gone.

Copy:

![Screenshot from 2022-09-14 00-34-15](https://user-images.githubusercontent.com/91113/190021124-ac29eb13-d243-47b9-99a7-9313cc1ee11c.png)

Paste here:

`This is a test entry`

Interesting is that you can still select a single word by double click on it.

## Steps to Reproduce
1. Create a note that includes newlines
2. Copy note text with <kbd>CTRL</kbd> + <kbd>C</kbd>
3. Paste Text anywhere

## Expected Behavior
Newlines should be copied. That actually works when you select the text and rightclick + "Copy".

## Actual Behavior
Newlines missing.

## Context

Might be related to https://github.com/keepassxreboot/keepassxc/issues/7243.

I think i don't had the issue in 2017.

KeePassXC - 2.7.1
Revision: REVISION

Operating System: NixOS 22.05.2711.294ef54a1e8 (GNU/Linux)
Desktop Env: Pantheon
Windowing System: X11

**Comment by fluks** [comment]
I could try to work on this part of the upcoming Hacktoberfest, so if I'm able to fix it, I will send a PR only in October :stuck_out_tongue:

I wasn't able to replicate on 2.6.6 which is in Ubuntu's packages, so it seems to be a later regression. I'll try to replicate in master.

**Comment by fluks** [comment]
Can't replicate this on develop branch.

**Comment by droidmonkey** [comment]
I can replicate it. Notepad properly handles the line separators but not more advanced IDE's:

![image](https://user-images.githubusercontent.com/2809491/193274314-f06f4091-df0e-4cb1-8a95-cc0d79fbaa71.png)

**Comment by fluks** [comment]
That's weird. I have normal "\n" or 0x0a newlines.

**Comment by jolyfra** [comment]
Verified on my Win10 with Version 2.7.1 Revision: 5916a8f, but not on previous version.

![download](https://user-images.githubusercontent.com/114915635/193558771-719c1a69-6f25-4dc0-b74d-68e74d1e85be.png)

This problem arrived with 2.7.x and the clipboard clearing countdown.
