### ISSUE TITLE
Give search field keyboard focus by default at startup

### ISSUE THREAD

**Issue by mxttie** [keepassxreboot/keepassxc#847]
When I start keepassxc, I either want to add a password, or look up one. Most often I want to look up a password. Hence, it would be handy if the search field has focus by default. Now I always have to press TAB twice.

## Expected Behavior
Startup Keepassxc and start typing to search

## Current Behavior
After starting Keepassxc I have to press TAB twice to enter the search field. 

## Possible Solution
Make the search field have keyboard focus after opening a database. Possibly make that focus optional in case some users do not want that behavior (although it is not clear which component currently has the focus, so I guess changing the default won't affect anyone).

thanks for considering!

**Comment by droidmonkey** [comment]
ctrl+f will focus the search field. There was a discussion on this in the past that resulted in the current behavior.

**Comment by mxttie** [comment]
I searched the issue tracker before posting my issue but didn't find any
discussion. Could you link to it so I better understand because I fail to
take advantage of the current behavior so I guess I'm missing something.
Thanks

**Comment by droidmonkey** [comment]
You are right, this feature may be very useful.

**Comment by Noettore** [comment]
I've submitted pull request #887 that should solve the issue.

**Comment by mxttie** [comment]
that's awesome, Noettore. I tested your PR briefly and it works excellent. It also focuses the search field after unlock :+1:

**Comment by mxttie** [comment]
i tested the updated PR, everything :ok_hand: :)

**Comment by ccoenen** [comment]
related to #401 thanks @Noettore  for the pr :)
