### ISSUE TITLE
Password entries ignore accents from keyboard input in linux-based GUI

### ISSUE THREAD

**Issue by rodrigovda** [keepassxreboot/keepassxc#8472]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
I have realized that when I need to input a database password that contains an accented character (such as `á ä à â`) in the gui, whenever password visibility is "hidden", the field ignores any accented input.

This makes it impossible to open databases with accented characters in the password field unless the password field is visible, and the same goes for typing a password entry.
I have checked that this issue doesn't happen on Windows, this is something Linux-related.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Set your keyboard layout to Spanish (es)
2. Open a "New Entry" or an already existing one
2. Select the password field while obfuscated (password not visible)
3. Try to write an accentuated character like `á`  by pressing the keys `´`+`a` (`'`+`a` in an English physical keyboard with the system set to (es) layout)

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
The password field recieves `á` as a character

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
The password field recieves `a` as a character instead

## Context
[NOTE]: # ( Give us any additional information you may have. )
When you write a password entry without hiding the password field, it works as intended. This is what happens when writing `á` (in a spanish keyboard, you first press the `´` key, and then you press the `a` key:
![Write_with_visible_password-1](https://user-images.githubusercontent.com/15835304/190342477-d8171c57-5837-49a9-a1e1-4be8f3e2eeb6.png)
![Write_with_visible_password-2](https://user-images.githubusercontent.com/15835304/190342487-0c3682c3-10db-4353-984a-3d8e2e3bd32c.png)

However, if the password field is obfuscated, when pressing any accented key, it is ignored, so the field when typing `´` + `a` only captures `a`:
![Write_without_visible_password-1](https://user-images.githubusercontent.com/15835304/190342887-5b37521c-8b69-48d4-88a6-8916f97b2877.png)
![Write_without_visible_password-2](https://user-images.githubusercontent.com/15835304/190343060-592e91f8-6751-4a5d-a55a-c8935ea38a8b.png)

Here's the Spanish keyboard layout. If you want to test this behavior. The `´` accent key is the one that in English keyboards is mapped to `'` (to the right of the `;` key).
![Screenshot from 2022-09-15 08-37-29](https://user-images.githubusercontent.com/15835304/190345298-cd0d5d00-fd14-48fe-b6d7-2912079a2378.png)

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.1
Revision: [5916a8f](https://github.com/keepassxreboot/keepassxc/commit/5916a8f8dd93eb6a5de544caedd7a9d8e9a3b1ee)

Operating System: Linux
Desktop Env: Gnome
Windowing System: Wayland

EDIT: format the bug report accordingly

**Comment by rodrigovda** [comment]
Just in case, to clarify: password fields always accept special characters when copied/pasted, the issue here is that hey ignore KEYBOARD accent inputs.

**Comment by rodrigovda** [comment]
I somehow failed to set a "bug" label, and now I am unable to assign it, I'm not used to github, my guess is that only authorized people can change labels to issues, I'm sorry for that and i would be appreciated if someone would add the "bug" label tothis issue.

**Comment by droidmonkey** [comment]
This is a qt bug, it is documented elsewhere on our issue board.

**Comment by rodrigovda** [comment]
Could you point to the relevant issue? I was not able to find it.

**Comment by droidmonkey** [comment]
There are a ton of closed issues on our board referencing this. Search for closed issues with the `qt` tag and text of "hidden".
