### ISSUE TITLE
ssh agent control order of keys

### ISSUE THREAD

**Issue by tlynchpin** [keepassxreboot/keepassxc#8474]
## Summary
Control the order of keys presented by ssh agent. 

This request is for features to get keys loaded in the desired order automatically at startup. 

## Examples
The agent tab on an entry could have a “rank” int that controls where it appears in the list of keys presented by the agent. 

## Context
Controlling the order of keys in ssh-agent is important for cases where the remote fails after n tries but the key in the agent is at >n position in the list. 

I can’t achieve this by manually adding keys from entries to the agent. It seems they always get the same order. I didn’t find documentation about this ordering. 

If I recall correctly, KeeAgent plugin allows manually changing order, keys are added initially in the byte order of the entries in the kdbx file. Then keys that are manually added are appended to the list. I think I was able to control loading at startup by changing order of entries in the kdbx.

**Comment by droidmonkey** [comment]
You need to use ~/.ssh/config file to specify the public key that should be used for a specific service. https://www.systutorials.com/how-to-choose-the-key-used-by-ssh-for-a-specific-host/

**Comment by tlynchpin** [comment]
Yes that is one way to do it. You are saying that user should take the public key from keepassxc and write them to files and write ssh_config. Please try it, on eg windows with several wsl linux virtual machines. This is not a great solution and controlling key order would solve many use cases.

At the very least, please document the ordering especially if there is any way to manipulate it.

Ultimately other agents support key ordering so please reconsider minimal feature parity here.

**Comment by droidmonkey** [comment]
I'm not sure how key ordering solves your problem. You can put some keys at the top but some still need to be at the end. Your solution is to either only load the keys you need when you need them or define keys per service as above.

**Comment by tlynchpin** [comment]
I’m here because I moved from keeagent plugin. I can control key order there.

I explain a case where server allows n authn attempts and key is at >n, login fails. Consider some other servers allow n+m attempts, so changing key order would allow all to work. 

I observe keepassxc has stable ordering: when a key is removed and added, it is in the same position. It seems there is no way to change the order without removing keys. Is that right?

**Comment by droidmonkey** [comment]
Well they are certainly loaded in a derministic order, based on the code that starts with the root group and goes down. So put the keys you want loaded first in your root group and put the others in groups under the root group.

Or place your entry view in natural sort order (click the column header until the arrow disappears). Then move the ssh entries in the order you want them to be loaded using the context menu or keyboard shortcuts.

**Comment by tlynchpin** [comment]
I can’t get this to work. I tested with 2.7.1 on windows. I am using “ssh-add -l” to check on both windows and wsl.

I made a test database with 4 entries, two with keys, keys as attachments, load/unload on open/close. I see two keys when the db is open, no keys when closed. I can reorder the entries, and after close and open I see the reorder persists. Nothing I’ve tried changes their order as shown in “ssh-add -l”. Does this work for you, what am I doing wrong?

**Comment by droidmonkey** [comment]
I looked into this some more and realized that there is no possible way to control the order of the keys in the agent.

https://datatracker.ietf.org/doc/html/draft-miller-ssh-agent-04#section-4.2

The keeagent plugin must have provided its own agent, adding keys to an external agent does not allow you to control the order they are presented in.
