### ISSUE TITLE
Merge entry with similar URL and same user

### ISSUE THREAD

**Issue by gagarine** [keepassxreboot/keepassxc#8483]
Often website may have different login domain. Especially the login page has a different domain than the "create an account" page. For this reason or other, you can end up with multiple entries for the same user and website.

It would be nice to be able to select multiple entries, do a right-click and "merge". The merge could only happen if part of the domain is similar, passwords are the same and user are the same. It should take the shortest ULR and put it has the main one and add the other in the "additional URLs" fields.

**Comment by droidmonkey** [comment]
#2202
