### ISSUE TITLE
Keepassxc co not minimise when using autofill

### ISSUE THREAD

**Issue by LHBL2003** [keepassxreboot/keepassxc#8484]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # When using multiple monitors, it is annoying that KeepassXC is minimised when using the auto-fill function.

## Examples
[NOTE]: # An application setting mit einer Checkbox
Checkbox: Do not minimise KeePassXC on Auto-Fill

## Context
[NOTE]: # KeePass does not minimise the window.
This is especially helpful when working via Remote Desktop and having to enter the same or different passwords several times in succession.

**Comment by droidmonkey** [comment]
Duplicate request
