### ISSUE TITLE
Cannot paste to KeePassXC entries

### ISSUE THREAD

**Issue by iyanmv** [keepassxreboot/keepassxc#8492]
## Overview
In wayland I cannot copy from the clipboard to KeePassXC. The other direction works, for example, if I copy the username, password or url I can paste those in any app (native wayland or xwayland) but not from any other app to KeePassXC. 

## Steps to Reproduce
1. Create an entry
2. Copy anything from any app
3. Try to paste that into the Notes field

## Expected Behavior
It should work as in X11. Other wayland apps can do copy/paste like this without issues, so it's not a qt5 bug as implied in #7902.

## Actual Behavior
Nothing can be pasted into KeePassXC

## Context
KeePassXC - Version 2.7.1
Revision: 5916a8f

Qt 5.15.6
Debugging mode is disabled.

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 5.19.9-arch1-1
Desktop Env: Plasma KDE
Windowing System: Wayland

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.19.2

**Comment by droidmonkey** [comment]
We don't control the flow of copy paste. So depending on how keepassxc is running (either under wayland or x11) this could be a qwayland bug of an xwayland bug.

**Comment by iyanmv** [comment]
But then, why is this the only app where I find this issue? As I said, I cannot observe this on any other qt app.

**Comment by droidmonkey** [comment]
KeePassXC is most likely running on X11, so you'll be going through xwayland for clipboard. The other qt apps are probably running on pure wayland. Just because you don't observe it doesn't mean the problem is with us. We literally have zero code that deals with clipboard pasting into keepassxc.

**Comment by iyanmv** [comment]
I think it's running as native wayland (I used [extramaus](https://wiki.archlinux.org/title/Wayland#Detect_Xwayland_applications_visually) to test this). I've tried all the possible combinations: xwayland to xwayland, xwayland to wayland, wayland to xwayland and wayland to wayland. But still, I only have this issue with KeePassXC. So I think something weird is happening.

I believe you when you say the bug is not here, but I would like to debug this and find what is going on so I can report it where it should.

**Comment by droidmonkey** [comment]
How are you running XC? Native, snap, flatpak, appimage? Do you have a firejail profile setup for XC?

**Comment by iyanmv** [comment]
[Native](https://archlinux.org/packages/community/x86_64/keepassxc/) and no firejail.

**Comment by iyanmv** [comment]
I realized one more weird thing about this issue. If I completely close KeePassXC (otherwise it's always on the tray) and I open again, pasting works as expected. It's only after a while that it stops working. I can replicate easily. Whenever pasting stops working, if I close and open it again, it just works again.

How could I further debug this?

**Comment by droidmonkey** [comment]
You can try inspecting the clipboard flow in Wayland. There is no entry point in keepassxc for pasting because it's all handled by Qt.

**Comment by LecrisUT** [comment]
A hint or helper to anyone encountering this. If you copy anything from keepassxc app itself to clean up the clipboard, this will make it possible to paste into the app again.

@droidmonkey keepassxc does control some clipboard functionality through the 10 second clipboard time-out, so couldn't it be related to that?

**Comment by droidmonkey** [comment]
We ask qt to put text on the clipboard. To clear it we tell qt to put a blank string on the clipboard. 

https://github.com/keepassxreboot/keepassxc/blob/develop/src/gui/Clipboard.cpp#L46-L87

**Comment by devurandom** [comment]
> A hint or helper to anyone encountering this. If you copy anything from keepassxc app itself to clean up the clipboard, this will make it possible to paste into the app again.

Surprisingly this indeed works. :astonished: 

```
Operating System: Fedora Linux 36
KDE Plasma Version: 5.25.5
KDE Frameworks Version: 5.98.0
Qt Version: 5.15.5
Kernel Version: 5.19.11-200.fc36.x86_64 (64-bit)
Graphics Platform: Wayland
Processors: 8 × 11th Gen Intel® Core™ i7-11370H @ 3.30GHz
Memory: 62.6 GiB of RAM
Graphics Processor: Mesa Intel® Xe Graphics
Manufacturer: TUXEDO
Product Name: TUXEDO InfinityBook Pro 14 Gen6
```

**Comment by voidpointertonull** [comment]
> A hint or helper to anyone encountering this. If you copy anything from keepassxc app itself to clean up the clipboard, this will make it possible to paste into the app again.

This is incredibly helpful, I've kept on restarting the program to be able to copy text into it as the first "managed" copying always broke that functionality. Thank you!

Noting for clarity that what works is "regular" copying, so selecting some piece of text somewhere and copying that, not pressing Ctrl-C on an entry which copies the password of the entry then clears the clipboard.

**Comment by droidmonkey** [comment]
This is likely related to certain desktop envs being completely inept at handling a BLANK clipboard entry. This same issue also causes the desktop to freeze when keepassxc is closed. It's been reported to them several times and they can't seem to bear a fix for it. We are shifting to using the `clear()` method from qt in 2.7.5 now that X11 fixed its broken implementation of that as well.

**Comment by LecrisUT** [comment]
If a fix is being planned, could we re-open this issue and link to a future PR that will fix it?

Maybe pin this also since every now and then there are people reporting this issue.

**Comment by SarenT** [comment]
I am having issues with this as well and the workaround does not work for me. I have found out that it is some applications, which can be an issue. e.g. I was not able to copy from Geany but copying to gedit first solved the problem. 🤷‍♂️ I suspect either the type of clipboard entry (e.g. clear text vs. objects) or permissions related to snap environment.

**Comment by evert** [comment]
Just sharing that this is still happening in 2025 and this workaround is godsend:

> A hint or helper to anyone encountering this. If you copy anything from keepassxc app itself to clean up the clipboard, this will make it possible to paste into the app again.
