### ISSUE TITLE
Auto-type non-functional on Ubuntu

### ISSUE THREAD

**Issue by jxosborne** [keepassxreboot/keepassxc#8493]
This is going to be a tricky one to figure out, I apologize.  I've installed keypassXC on a newly installed Ubuntu 22.04 LTS.  I've set my global hotkey, ALT+Z.  It just doesn't do anything in any program at all, I've cycled through a number of different hotkeys to see if that for some reason worked.

I can't find any log files relating to KeypassXC at all, nor do I see anything output to the console when I run it from a shell.

To add to this, I have an identical system right beside it and it's working as expected (ALT+Z)

Any idea what could be causing this? or even just where can I look to find some logs about what is happening?

Kindly appreciated.

Thanks.

**Comment by droidmonkey** [comment]
Don't use Wayland if you want to use Auto-Type. Before you login to the desktop, choose your environment as X11 driven.

**Comment by jxosborne** [comment]
Hm, never thought of that.  and sure enough the other machine returns X11 as Session Type.  Thanks for that.
