### ISSUE TITLE
press buttom clipboard password copy URL

### ISSUE THREAD

**Issue by iTytar** [keepassxreboot/keepassxc#8499]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. select account
2. press buttom copy password to clipboard
3. go to expernal application password field and try insert from clipboard 

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
password inserted

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
url inserted

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION 2.7.1
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows
Desktop Env: -
Windowing System: -

**Comment by droidmonkey** [comment]
Fixed for 2.7.2
