### ISSUE TITLE
Feature request: plugins support

### ISSUE THREAD

**Issue by soredake** [keepassxreboot/keepassxc#85]
## Expected Behavior
Having a plugin support to install the KeePassRPC (needed for https://github.com/luckyrat/KeeFox)

## Current Behavior
No plugin support.

## Possible Solution
Implementing plugin support.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

**Comment by droidmonkey** [comment]
Can you please format this issue in the template provided. If not, it will be closed as there is not nearly enough information to understand what is required.

**Comment by droidmonkey** [comment]
Plugins will not be added to this version of KeePass. Sorry about that.
