### ISSUE TITLE
Adding OTP delete unsaved changes

### ISSUE THREAD

**Issue by kamheric** [keepassxreboot/keepassxc#8502]
## Overview
Several times I **lost some changes** while editing entry and don't saving before adding OTP.

Creating new accout in some online service, adding additional attributes (at "advanced" tab) like recovery codes, and after that adding OTP -> delete all unsaved changes and stays only otp record, nor note, nor password, nor additional attribute records - non of all.

## Steps to Reproduce
1. create new entry
2. make some changes, like password, notes.
3. save changes
4. make new changes - add note, change password, add additional attributes, change icon
5. don't save!
6. add OTP (trow menu Entries -> TOTP -> Setup TOTP)
7. look for changes in step 4 : it's loss! 
8. save or not save - it does not matter. after opening entry again you can see history and two versions: first save (step 3), and version with OTP.

## Expected Behavior
Adding OTP codes without saving changes before does not delete those changes in entry. Or make saving version of entry before adding OTP automaticly without user bother.

## Actual Behavior
KeePassXC delete user changes without saving if adding OTP

## Context

KeePassXC - Version 2.7.1
Revision: 5916a8f

Qt 5.15.6
Debugging mode is disabled.

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 5.19.10-arch1-1

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.19.2

Operating System: Arch Linux
Desktop Env: Gnome
Windowing System: Wayland

**Comment by droidmonkey** [comment]
#6838
