### ISSUE TITLE
Store settings permanently instead of temporarily

### ISSUE THREAD

**Issue by toxpal** [keepassxreboot/keepassxc#8506]
Using Linux Manjaro (KDE) and because of the way KeePassXC stores its settings, I can't remove temporary files from my system because it resets all the customizations of KeePassXC.

In other words, once I remove temporary files from OS (using BleachBit, if it's important), KeePassXC is restored to default state. Right after startup, previously used database is forgotten, view options (displayed columns and their width, etc.) are restored to default state, etc.

The only settings not removed are from "Tools -> Settings" menu. How can I solve this? I really need to cleanup OS from time to time, but just removing temporary files instantly deletes most of KeePassXC settings. Needless to say, it's the only app which acts this way - all the other apps continue working perfectly after removing temporary files, just as it should be.

**Comment by droidmonkey** [comment]
You can change the path to the local configuration file, the one that stores ephemeral information, using a command line switch or environment variable: https://keepassxc.org/docs/KeePassXC_UserGuide.html#_command_line_options

Env var is KPXC_CONFIG_LOCAL

**Comment by toxpal** [comment]
Thanks for the info. While I can do it, how about "ordinary users"? I always thought that KeePassXC was designed for everyone, so why can't it store settings just like all other apps?
