### ISSUE TITLE
HMAC Mismatch - not able to open database(s) on Linux and Windows

### ISSUE THREAD

**Issue by legalmat** [keepassxreboot/keepassxc#8507]
## Steps to Reproduce
1. Starting current version of Keepassxc
2. Opening new (or memorized) database
3. Entering password given since the first creation of this database. Error occurs. Message is: "Error while reading the database: Invalid credentials were provided. Please try again.
If this reoccurs, your database file may be corrupt. (HMAC mismatch)"

## Expected Behavior
The database should open as normal. I have switched from windows back to my linux system after a longer time. 

## Actual Behavior
The database was created on windows 10. As I have made a backup mostly each month during the last 2 years naming it for the month. I have also used a copy of the database used on desktop that I have synced with my smartphone. After months I got my laptop back because the display was broken and when I have tried to open it, I have expected the database to open as usually. 3 months before it did. The time frame even is INSIDE the latest update (so it worked after the update and it didn't work after the same update version)
But MOST curios is, that the databases from the past, as well as the one used for syncing with the smartphone (where it gives the same error BTW but there I open from the cloud AND locally), give the same error.
I would have expected that only one of the databases gives the error and maybe mistyping the password, or when pasting it hidden characters or different charset might be the issue. But none of my tries have helped me to open this databases which simply stopped working. I then installed the edge version of windows 10 for developers in my virtualbox and installed keypassxc in there supposing that it might be a problem of the platform. But nothing. This is a fiasco.
Please help!

## Context
Tried several old saved databases (no, I didn't use the backup function) that are saved just through "save database as".
I have also tried to disable the kdwallet on my Manjaro. Am clueless now.
Even IF I had changed the password, without remembering, then the old version dating back to 2020 must have opened. Just my 50 cent.

Debug info:
KeePassXC - Version 2.7.1
Revision: 5916a8f

Qt 5.15.5
Debugging mode is disabled.

Operating system: Manjaro Linux
CPU architecture: x86_64
Kernel: linux 5.15.65-1-MANJARO

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.19.2

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 10 and Operating System: Manjaro Linux
Kernel: Linux 5.15.65-1-MANJARO
Architecture: x86-64
DISTRIB_RELEASE=22.0.0
DISTRIB_CODENAME=Sikaris
Desktop Env: KDE 
Windowing System:   Display: wayland server: X.org v: 1.21.1.4 with: Xwayland v: 22.1.3
    compositor: kwin_wayland driver: X: loaded: modesetting,nvidia

**Comment by droidmonkey** [comment]
Either the file(s) are corrupt or you are typing the wrong password. You did say it was 3 months since using the database. There is nothing we can do to help you, unfortunately.

**Comment by legalmat** [comment]
Sorry, but what kind of reaction is this?
I dont want to make anybody feel bad or give convictions.
I just wonder what could have happened, after you must have read, that even the older databases do not work.
Whether I have changed the password on the newest or not, whether the newest is corrupt or not. Why does the rest not open. They are the old databases.
Makes no sense to me to close this thread like this.
Understand please... This is not my fault, at least I cannot see it

**Comment by droidmonkey** [comment]
> But MOST curios is, that the databases from the past, as well as the one used for syncing with the smartphone (where it gives the same error BTW but there I open from the cloud AND locally), give the same error.

You are using the wrong password. No other reason for this behavior.

**Comment by michaelk83** [comment]
Might it have to do with that Qt bug that mishandles some characters when the password is hidden? #7291 #8395
Also, RAM issues have been suggested before for similar errors. Does any of the DBs open on a different device?

**Comment by m-piatkowski-dev** [comment]
Dear Devs I also had this error, I put good password and it is still saying
 "Error while reading the database: Invalid credentials were provided. Please try again.
If this reoccurs, your database file may be corrupt. (HMAC mismatch)"
And I had this issue 2 times in a row, I have created new database restart computer and after restart error ocured...system windows 8.1 ...any idea what is wrong ??

**Comment by legalmat** [comment]
> > But MOST curios is, that the databases from the past, as well as the one used for syncing with the smartphone (where it gives the same error BTW but there I open from the cloud AND locally), give the same error.
> 
> You are using the wrong password. No other reason for this behavior.

Hi, I have got what you said, no need to tell me twice, please. What I am wondering about is, that around 15 times I have saved it over the time of one and a half years or so. All kdbx files are single sole files and it is not only one file but many Then I didnt have a PC because the display was broken. So, I haven't used my PC. First thing was trying to read my passwords again.

Then please make me understand how 15 or more databases can get corrupted. Please, if I haven't changed my password they are corrupt, understand.
But even if I had changed my password, then it would only change on the last version, the last saved  .kdbx file.
How could I use a wrong password on the older backups, when I (maybe) have changed it only on the last used version?
For example I open a kdbx file from last year January and it gives the same error like the current database.
Wrong password as possible error makes no sense in my eyes.

Can you not look into the kdbx file somehow, when I send it to you?
It is a  very big problem for me. Especially that even no backup is opening.
And how can I drag a full debug report?
Shaka2u1u

**Comment by legalmat** [comment]
> Might it have to do with that Qt bug that mishandles some characters when the password is hidden? #7291 #8395 Also, RAM issues have been suggested before for similar errors. Does any of the DBs open on a different device?

I have also tested this password typing in clear text, copy and paste, pasted in a textfile, checked the charset and such things. Tried to import into keepass and no success.
But I will check the link you have given anyway.
My RAM is 32 GB so I dubt this is an issue.
I don't get your question at the end.
Kindly explain.

**Comment by michaelk83** [comment]
> My RAM is 32 GB so I dubt this is an issue.

It's not the size of the RAM that matters, but whether or not any of it is faulty (or there's a problem with the RAM controller, or motherboard, etc). If there are any errors, it can disrupt the decryption operation. The fact that your laptop came back from repair suggests there could be other hardware issues at fault. You can try running memtest to check for RAM errors.

> I don't get your question at the end.

If you copy the database to another computer or to your smartphone, does it open there? If so, that may also point to a hardware problem.

**Comment by droidmonkey** [comment]
> Can you not look into the kdbx file somehow, when I send it to you?

There is absolutely nothing we can do. The point of the file is to be completely inaccessible without the proper credentials.

**Comment by Walsonde** [comment]
Is the point of the file to be accessible with the correct credentials? If so, then your arrogant answers are disgusting! This bug is all over the internet and you simply choose to ignore it.

**Comment by droidmonkey** [comment]
You are absolutely correct, mistyping or forgetting your password is rampant! Every single one of these reports has been with the user except for a handful where ram defects or bad over clocking was the cause. Can you link to one of your findings that was validated to be corruption explicitly caused by the program?

**Comment by Walsonde** [comment]
Oooooh! That's intriguing. Tell me, how do I mistype a copypasted passphrase and how do I suddenly only after updating the app mistype the passphrase that I miraculously almost never mistyped before I updated the app? Or rather don't. The chances of you contributing something intelligent or at least useful seem to be quite low.
There are other password manager apps. After all a password manager is as safe as it's developers are decent people. So it can't be difficult finding a better one.

**Comment by droidmonkey** [comment]
Lol, I dunno I've been using KeePassXC for 6 years and run developer builds constantly and have never had a problem. We have at least a million people who use our software everywhere in the world on all sorts of platforms. If you can help us narrow down to a repeatable problem, then we can fix it. Otherwise... the problem is going to be on YOUR end. 
 
Have you tried downgrading the version and confirming you can open the database again? That would be an important piece of information.

**Comment by Walsonde** [comment]
ROFL! The flatpak version works perfectly, the distro specific version doesn't. But of course I always mistype my passphrase in distro specific software and never in flatpak apps. Bye!

**Comment by droidmonkey** [comment]
Might want to take it up with your distro packager, they may have missed a dependency.
