### ISSUE TITLE
The (linux) desktop icon is hard-coded

### ISSUE THREAD

**Issue by mrmeszaros** [keepassxreboot/keepassxc#851]
I installed an Icon theme (Numix) but the icon does not change.
This is due to the fact that the **Icon** line of the desktop entry snap package is hard-coded.

## Expected Behavior
The desktop icon should change, when the user changes the icon theme.  

## Current Behavior
The desktop icon remains the package provided, despite the theme changes.

## Possible Solution
1. Install the provided icon(s) to a freedesktop standard location.
    * the [Icon Theme Specification](https://specifications.freedesktop.org/icon-theme-spec/icon-theme-spec-latest.html) should be followed
    * as well as the [Icon Naming Specification](https://specifications.freedesktop.org/icon-naming-spec/latest/)
    * The name `keepassxc` seems to be ok, but location should be something like `~/.local/share/icons[/hicolor]` or `/usr/share/icons[/hicolor]`
2. After that, the icon can be referenced by name in the desktop file
    * It can change from `/snap/keepassxc/23/share/icons/hicolor/256x256/apps/keepassxc.png` to simply `keepassxc`

## Steps to Reproduce (for bugs)

1. Install the snap:
```
sudo snap install keepassxc
```
2. Install an icon theme (eg: Numix-Circle):
```
sudo add-apt-repository ppa:numix/ppa
sudo apt update
sudo apt install numix-icon-theme-circle
```
3. Change the icon theme - this can be done with eg the Unity Tweak Tool:
```
sudo apt install unity-tweak-tool
```
4. The desktop entry does not change icon (although the theme provides it!)

## Context
It is a minor tweak, but enables people to use the icon from their favorite icon theme.

## Debug Info

KeePassXC - 2.2.0
Revision: 23

Libraries:
- _None_

Operating system: Ubuntu 16.04
CPU architecture:  x86_64 (64-bit)
Kernel: Linux 4.10.0-30-generic

Enabled extensions:
- _None_

**Comment by droidmonkey** [comment]
This is how snaps work to my knowledge. All resources are placed in the folder you mention ```/snap/keepassxc/23/``` where 23 continually increases for each install of the snap.

**Comment by pgera** [comment]
The other issue is that the stock icon is really big (at least on ubuntu). In unity's HUD search, the icon is much bigger than everything else.

**Comment by matemeszaros** [comment]
It seems that themes are not yet supported by snaps.
See this forum post: https://forum.snapcraft.io/t/snaps-not-assuming-system-icon-themes/1767

So the issue will be resolvable when theme support will be implemented (~in a couple of months)
