### ISSUE TITLE
Path to DB is shown to anyone looking at the client

### ISSUE THREAD

**Issue by skossan** [keepassxreboot/keepassxc#8510]
## Overview
The location of my database is clearly shown in plain text when I am about to enter my password to unlock my database.
The location string is shown right under where it says _Unlock KeePassXC Database_

## Steps to Reproduce
See the previous point.

## Expected Behavior
I would assume this information would be hidden. It provides no benefit to show this information publicly to anyone looking at the computer screen. If someone gets unauthorized access to my machine they will instantly be able to find my database file.

This information is better shown in the settings menu.

## Additional info.
KeePassXC - 2.7.1
Operating System: Windows
Windowing System: 11

**Comment by michaelk83** [comment]
> It provides no benefit to show this information

Sometimes it's needed to identify which database file you're trying to open.

If someone wanted to find your database, they could simply run a search, starting from the most common locations (documents, downloads, network shares, KeePass folders), so there is no benefit to hiding this information. Even if they got the file, if you use a strong enough passphrase, your passwords would still be safe, so it doesn't matter (unless they just delete the file - it's always a good idea to keep backups).

Also, if someone gets unauthorized access to your machine, you could easily have bigger problems to worry about.

**Comment by droidmonkey** [comment]
Where your database file is stored is irrelevant. One with said access to your computer can also just search for kdbx files. Or more likely just dump all your files and walk away when done.
