### ISSUE TITLE
Session specific path / does not open previously opened database

### ISSUE THREAD

**Issue by Mijutra** [keepassxreboot/keepassxc#8511]
## Overview
When I open my database the path to the database is a session specific path (e.g. **/run/user/1000/doc/dfg34nb3/database.kdbx**).
So when I restart my computer the session specific path is not available anymore and KeePassXC tells me it can not find the previously opened database anymore.
Happens with local **_and_** cloud stored keepass files.

Did not happen with older versions or with 2.7.1 AppImage.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Open an existing database
2. Activate **Load previously open databases on startup** and **Automatically launch KeePassXC at system startup**.
3. Restart computer.
4. Wait till KeePassXC opens.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
KeePassXC finds previously opened database and asks for credentials

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
KeePassXC does not find previously opened database, because the path is **/run/user/doc/1000/dfg34nb3/database.kdbx** (see image for actual path). So I need to open the database by hand and the part **dfg34nb3** of the path changes to another ID like **lkj5n7** or something.
![image](https://user-images.githubusercontent.com/49234386/192558706-3fea81c6-be91-4d0b-8a3c-67f4490e78d5.png)

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.1
Revision: 5916a8f
Distribution: Snap

[NOTE]: # ( Pick choices based on your environment )
Operating System: Ubuntu Core 20
Desktop Env: Gnome
Windowing System: Wayland

**Comment by droidmonkey** [comment]
Nothing we can do about this, it's just the way snaps work. Use the flatpak or appimage for a better experience
