### ISSUE TITLE
Fastmail's Masked Email Integration

### ISSUE THREAD

**Issue by kbohinski** [keepassxreboot/keepassxc#8512]
## Summary
Integrate with Fastmail's Masked Email service for on the fly unique email address generation for new accounts
https://www.fastmail.com/developer/maskedemail/
https://www.fastmail.help/hc/en-us/articles/4951369076879-Partnering-with-Fastmail

## Examples
See existing integrations from Bitwarden and 1Password
https://www.fastmail.com/1password/
https://fastmail.blog/company/masked-email-now-in-more-places-with-bitwarden-integration/

**Comment by droidmonkey** [comment]
I have no interest in building this integration. We don't build in specific third party integrations for one (with exception to yubikey), and frankly there is no need. Just generate your fake email in their service and add it to your entry.
