### ISSUE TITLE
CANNOT use gdb to figure out why keepassxc keeps segfaulting

### ISSUE THREAD

**Issue by tedliosu** [keepassxreboot/keepassxc#8514]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1.  `./keepassxc`
     `Segmentation fault`
2. `gdb keepassxc`
```
GNU gdb (Ubuntu 10.2-0ubuntu1~20.04~1) 10.2
Copyright (C) 2021 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from keepassxc...
(No debugging symbols found in keepassxc)
(gdb) r
Starting program: /usr/bin/keepassxc 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff1fff700 (LWP 101632)]
[New Thread 0x7ffff17fe700 (LWP 101633)]
Cannot find user-level thread for LWP 101628: generic error
```

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Keepass doesn't keep randomly segfaulting and debugging keepassxc using gdb actually works

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Segfaulting keepass and debugging doesn't work either

## Context
[NOTE]: # ( Give us any additional information you may have. )
Just using keepassxc normally no specific context whatsoever.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.1
Revision: 5916a8f

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux (Ubuntu more specifically)
Desktop Env: XFCE, with QT installed from conda because conda took over my environment after I installed it 🙃
Windowing System: X11

**Comment by droidmonkey** [comment]
Recommend just using our flatpak or appimage distribution. Most likely due to your environment being screwed up by conda.

**Comment by michaelk83** [comment]
For debugging you'll need to use a [development snapshot](https://snapshot.keepassxc.org/).

**Comment by tedliosu** [comment]
> Recommend just using our flatpak or appimage distribution. Most likely due to your environment being screwed up by conda.

Yea I won't be surprised if it was the qt 5 conda package that's causing the segfaults; I'm currently launching keepassxc using the command `env LD_LIBRARY_PATH="" keepassxc` to "force-clear" any dynamic linking that's going on between the qt5 conda package libraries and keepassxc and currently I haven't experienced any segfaults **yet** if that's any helpful indication. 👀

**Comment by tedliosu** [comment]
> For debugging you'll need to use a [development snapshot](https://snapshot.keepassxc.org/).

Is using the Linux app image dev snapshot equivalent to using a deb-packaged dev snapshot of keepassxc for debugging purposes, esp. if I'm trying to figure out whether or not it's my conda environment that's causing the segfaults?

**Comment by droidmonkey** [comment]
No the appimage will use its own libraries it carries with it. You would also need debug versions of qt libraries to really know what's happening... and that would be conda versions of qt as well... better to just give up and move on.

**Comment by tedliosu** [comment]
> No the appimage will use its own libraries it carries with it. You would also need debug versions of qt libraries to really know what's happening... and that would be conda versions of qt as well... better to just give up and move on.


Alright then if debugging the issue is going to be much more work than just installing a differently-packaged "version" of keepassxc then I'm closing this issue with this comment; if anyone else with a similar setup as me runs into the same issue then try launching keepassxc with `env LD_LIBRARY_PATH="" keepassxc` *if* the issue stems from `LD_LIBRARY_PATH` causing the system dynamic linker to pick up the conda qt5 libraries instead of the system qt5 libraries like it was in my case; otherwise if that doesn't fix the problem then do what @droidmonkey said and install/use either the flatpak version or the app image version of keepassxc.

Thanks everyone for the advice and all 🙂
