### ISSUE TITLE
insert field reference (like KeePass)

### ISSUE THREAD

**Issue by www-wagner** [keepassxreboot/keepassxc#8518]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
It'd be great if we could insert references to another entries using GUI, like we can do in KeePass. A right-click menu option to add reference to another entry could be open a popup window, where we could choose the entry and the field we'd like to use.

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )
The pictures show how KeePass do this. But I think a right-click in the field where we want to insert the reference could be better than that.
![KeePass](https://user-images.githubusercontent.com/18124316/193056763-de4772c4-6ac8-4708-aa65-4c739d283629.png)
![KeePass](https://user-images.githubusercontent.com/18124316/193057749-20ed31a3-d707-499f-b8cf-3d3858766760.png)

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
My db has lots of references! But today KeePassXC only allows adding references when an entry is cloned. So when I have to reference an entry from a existing entry, I have some work to do:
1 - close current entry
2 - open the target entry
3 - copy the UUID (or another field) of the target entry
4 - open the first entry again
5 - write the syntax reference in the field and paste copied UUID (or another field)

**Comment by droidmonkey** [comment]
#433
