### ISSUE TITLE
Update Password Strength indicator's rating

### ISSUE THREAD

**Issue by Rex-0x7CB** [keepassxreboot/keepassxc#8519]
## Summary
Currently, Keepass-XC rates passwords as Poor (Entropy < 40 bits), Week (Entropy between 40 and 65 bits), Good (Entropy between 65 and 100 bits) and Excellent (Entropy > 100 bits). In my opinion this rating should be updated as the computing power has dramatically increased over the years. 
National Security Agency (NSA) announced their plan and timelines to transition the industry to a post-quantum world with [Commercial National Security Algorithm Suite 2.0](https://media.defense.gov/2022/Sep/07/2003071834/-1/-1/0/CSA_CNSA_2.0_ALGORITHMS_.PDF). Interesting, they do not consider AES with key length 128-bit to be secure anymore. The minimum key-length requirement for AES is 256 bit.
I was wondering if we should update the password-strength indicator as, in its current state, it could be misleading in the coming years. 

## Context
[NOTE]: National Security Agency (NSA) announced their plan and timelines to transition the industry to a post-quantum world with [Commercial National Security Algorithm Suite 2.0](https://media.defense.gov/2022/Sep/07/2003071834/-1/-1/0/CSA_CNSA_2.0_ALGORITHMS_.PDF).

**Comment by droidmonkey** [comment]
AES key length and password entropy are very different concepts.

Example passwords with their rating:

g^gm6QKl%HqRuaG = Good (15 chars, 92 bits)
c|;7o\d8#XO/'*Am*1` = Excellent (19 chars, 112 bits)
^p,JLR@!"4MP\95Av = Good (17 chars, 98 bits)
h2>'O/V3B:#z = Good (12 chars, 74 bits)
%B6N6Nu$xO2J = Weak (12 chars, 62 bits)
#Y:5*p_"U# = Good (10 chars, 65 bits)

I do think the "Good" rating needs to be raised to 75 bits. Excellent is impossible to reach without at least 16 chars and a lot of character groups included. @phoerious

**Comment by Rex-0x7CB** [comment]
> 

I understand that AES keys and passwords are completely different things but, what I had in my mind was this:
If there are computers powerful enough to brute-force small key-spaces, aren't they also powerful enough to brute-force low-entropy passwords? After all, the size of the key-space is the representation of entropy in the key, right?

I'm not a cryptographer, so maybe there is flaw in my logic. But, I just wanted to put it out there.

**Comment by droidmonkey** [comment]
NIST only changed their _minimum_ recommendation. There is no proof that 128-bit key space is _broken_. I am sure there might be a couple of super computers capable of brute forcing the key space owned by some countries.... but that is definitely not equating to broken. 

In my opinion, quantum computing is a huge farce and I doubt we will ever see them implemented in the theorized ways. There is a huge jump between "this might be possible someday" to "quantum computers will break 128-bit keys in 5 years". The latter is definitely not on the table right now or even the near future.
