### ISSUE TITLE
KeepassXC on MacOS High Sierra

### ISSUE THREAD

**Issue by akasaka99** [keepassxreboot/keepassxc#8522]
Hello, I am looking for KeepassXC on MacOS High Sierra (10.13) version, I can only see 10.15 on the side. I've see the latest version for Sierra was 2.5.3 so I imagine there's a last version for High Sierra too. Many thanks for help

**Comment by droidmonkey** [comment]
You can use macports, we don't provide a version for High Sierra.

**Comment by frazhome** [comment]
KeepassXC 2.7.1 is running on MacOS High Sierra (10.13)

outdated, but newer than 2.5.3

**Comment by WolfgangFahl** [comment]
IMHO the pointer to https://github.com/keepassxreboot/keepassxc/releases/tag/2.7.1 should be part of the official download page to make legacy installations possible. I'll try it and and report whether the dmg works.

**Comment by phoerious** [comment]
We do not support legacy systems. MacOS 10.13 has been EOL for almost two years.

**Comment by WolfgangFahl** [comment]
@phoerious still it would be nice to add the link for the people that do still run old computers that can't run newer OS versions. There is more than one End Of Live Definition of computers and software should: the users more often than not might have a different opinion then the providers.

**Comment by phoerious** [comment]
You should absolutely not run an operating system that is unsupported by the vendor.

**Comment by WolfgangFahl** [comment]
@phoerious thank your for this advice. I am never going to follow it. I have lots of old computers that just run fine and indeed sometimes i get rid of the software of the computer vendors os software e.g. replacing a Microsoft Windows with an Ubuntu to make sure i can actually use the device.

**Comment by phoerious** [comment]
You can absolutely choose a non-commercial vendor, but you should never run an EOL operating system. That applies to Ubuntu the same way it does to macOS.

**Comment by WolfgangFahl** [comment]
I'd love to have non EOL OS on my old machines. I see the responsibility to make this happen on the vendor side. They just need to make sure the newer OS still supports old hardare (as Ubuntu nicely does). Its not that coercion would work in this case because for the legal state of coercion you have to have a big threat and you have to be successful. Fortunately no violence is involved so all is good.

**Comment by phoerious** [comment]
You can install Linux on a Macbook if you choose so. If you choose to stick with Apple, however, you will have to follow their update life cycle. We will not start endorsing running operating systems past their expiry date.

**Comment by droidmonkey** [comment]
>  I see the responsibility to make this happen on the vendor side. 

They upheld that responsibility for the terms you agreed to when you purchased the hardware. In fact I believe Apple supported most hardware beyond their stated life cycle, this was true for iPhone as well.
