### ISSUE TITLE
Windows 10: Drag and Drop not working

### ISSUE THREAD

**Issue by medienhochdrei** [keepassxreboot/keepassxc#8529]
Hello all,

the documentation doesn't state how to reorder groups _(i.e. make group the child of another group)_ and/or entries _(change the parent group of entry)_. Drag/Drop doesn't seem to work at all. I have tried all combinations of Ctrl, Alt, Shift while dragging, but nothing happens. Is there a trick to it? Or is there a checkbox to enable drag and drop?

Any help would be appreciated. Thank you.

(I'm using KeePassXC 2.7.1 on Windows 10)

**Comment by droidmonkey** [comment]
It works fine for me. All you need to do is drag the group up and down and a line shows where it will be placed. Entries just drag on top of the desired group and let go. If you hold CTRL after dragging starts then a copy will be made.

**Comment by medienhochdrei** [comment]
Well, after a system restart it worked just fine.
Sorry for behaving like a noob. :)
