### ISSUE TITLE
make: Invalid argument @ rb_check_realpath_internal

### ISSUE THREAD

**Issue by hankster112** [keepassxreboot/keepassxc#8531]
## Overview
Build fails at 100% with above error.

## Steps to Reproduce
Build latest branch from master on Debian 11 with make

## Expected Behavior
keepassxc builds

## Actual Behavior
Build fails at 100% with below error:

Traceback (most recent call last):
        1: from <internal:gem_prelude>:1:in `<internal:gem_prelude>'
<internal:gem_prelude>:1:in `require': Invalid argument @ rb_check_realpath_internal - /usr/lib/ruby/vendor_ruby/rubygems.rb (Errno::EINVAL)
make[2]: *** [docs/CMakeFiles/manpages.dir/build.make:82: docs/keepassxc.1] Error 1
make[1]: *** [CMakeFiles/Makefile2:3088: docs/CMakeFiles/manpages.dir/all] Error 2
make: *** [Makefile:160: all] Error 2

Version is latest from master branch

[NOTE]: # ( Pick choices based on your environment )
Operating System: Debian 11
Desktop Env: KDE Plasma
Windowing System: X11

**Comment by droidmonkey** [comment]
Must be related to asciidoctor... nothing we can do about that since this is on your system. Use WITH_XC_DOCS=OFF to bypass this. You probably need to update your ruby installation.
