### ISSUE TITLE
Can you please provide updated Debian unstable/Sidux packages?

### ISSUE THREAD

**Issue by synaomen** [keepassxreboot/keepassxc#8534]
Upgrading to Debian unstable/Sidux fails due to changed dpkg compression. Up to now I have always managed with the Ubuntu packages, but unfortunately this is no longer possible. I still have v2.6.6 and would like to upgrade to v2.7.1.

**Reason:**
Debian dpkg uses gz, gzip and xz (to my knowledge) and Ubuntu has switched dpkg to zstd which is why the install/update fails with an error code.

**Error:**
`dpkg -i /var/cache/apt/archives/keepassxc_2.7.1-1ppa1~jammy1_amd64.deb`
`dpkg-deb: Fehler: Archiv »/var/cache/apt/archives/keepassxc_2.7.1-1ppa1~jammy1_amd64.deb« verwendet unbekannte Komprimierung für Element »control.tar.zst«, Abbruch`
`dpkg: Fehler beim Bearbeiten des Archivs /var/cache/apt/archives/keepassxc_2.7.1-1ppa1~jammy1_amd64.deb (--install):`
 `»dpkg-deb --control«-Unterprozess gab den Fehlerwert 2 zurück`
`Fehler traten auf beim Bearbeiten von:`
 `/var/cache/apt/archives/keepassxc_2.7.1-1ppa1~jammy1_amd64.deb`

**Comment by droidmonkey** [comment]
We don't maintain the Debian package but you may be able to get a newer one from OBS: https://build.opensuse.org/package/show/security:keepassxc/keepassxc

Or you can use the flatpak or appimage.
