### ISSUE TITLE
Enlarge notes area in preview pane

### ISSUE THREAD

**Issue by sam1946** [keepassxreboot/keepassxc#8537]
A small feature suggestion - but would be very useful!

In the preview panel, when the application is maximised in size, the visible notes area is small - 15 rows or so - before the scroll bar appears. I have a lot of text in the notes area.

Could the notes area be maximised to the rest of the preview pane area without there being unused screen space beneath? See image

Thank you in advance :)

![img](https://user-images.githubusercontent.com/92179151/193601202-78a3ab31-e6fb-4fc1-b7ba-553b3c5270a3.png)

**Comment by droidmonkey** [comment]
Already done for 2.7.2
