### ISSUE TITLE
Saving database to Google Drive volume fails

### ISSUE THREAD

**Issue by freeedrik** [keepassxreboot/keepassxc#8538]
## Overview
Saving database to a mounted Google Drive volume fails using Gnomes built in Google Drive client.

If safe saves is enables I get a and i/o error. 
If safe saves is not enabled the files is deleted instead.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1.  Mount your google drive using Gnomes built in client.
2.  Open a database on this mount
3.  Save database

## Expected Behavior
Database get saved.

## Actual Behavior
If safe saves is enables I get a and i/o error. 
If safe saves is not enabled the files is deleted instead.

## Context
KeePassXC - Version 2.6.6
Revision: 9c108b9

Qt 5.15.3
Debugging mode is disabled.

Operating system: Ubuntu 22.04.1 LTS
CPU architecture: x86_64
Kernel: linux 5.15.0-48-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- libgcrypt 1.9.4

Desktop Env: Gnome
Windowing System: X11

**Comment by droidmonkey** [comment]
Upgrade to 2.7.1 and use direct write saves.
