### ISSUE TITLE
Add configuration point for `KeeAgentSettings`

### ISSUE THREAD

**Issue by 1mm0rt41PC** [keepassxreboot/keepassxc#8539]
## Summary
The goal is to control the defaults values of `KeeAgentSettings` (https://github.com/keepassxreboot/keepassxc/blob/bc5d0df19ee8e7fdc2cfad549bbb68e699c37d69/src/sshagent/KeeAgentSettings.cpp#L72-L80).
These value are used if there is no attachement named `KeeAgent.settings`.

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )
Add new entries in the `keepassxc.ini` to define defaults values
```ini
[SSHAgent]
Enabled=true
UseOpenSSH=true
AllowUseOfSshKey=true
UseConfirmConstraintWhenAdding=true
UseLifetimeConstraintWhenAdding=false
LifetimeConstraintDuration=600
AddAtDatabaseOpen=true
RemoveAtDatabaseClose=true
```

## Context
I use the Windows ssh agent and my keys can be used without my consent and without my knowledge

**Comment by droidmonkey** [comment]
You control these settings when editing the entry that the ssh key is attached to

**Comment by 1mm0rt41PC** [comment]
Yes but if I want to configure all my ssh keys, I need to edit all entries, it should be easier to define a global value for all ssh keys with the possibility to override these parameters for each keys.

**Comment by droidmonkey** [comment]
These are database stored settings so at best default values should be configured in database settings, not application settings. However, considering you have to setup each key in the same dialog as these settings... I don't understand the problem.

Given the current situation, you'd have to go to each entry anyway to delete the custom settings that are stored in them to go back to default. Might as well just save all that coding and go and change your ssh entries as you see fit yourself.
