### ISSUE TITLE
Generate password hashes

### ISSUE THREAD

**Issue by codekandis** [keepassxreboot/keepassxc#8540]
## Summary

Create a simple dropdown with a list of several password hash algorithms. Once an algorithm is chosen the password hash should be shown and able to get copied to the clipboard.

## Context

I'm a developer. I generate and store passwords on a daily and regular basis. These passwords need to get stored in a hashed manner in databases and other applications. Every time I do this I need to get the hash of a newly generated password.

Currently I'm using a CLI tool. This needs additional clicks and typing.

One of the dangers ... Sometimes I accidentially pass a password as a single command instead of the user input of the CLI tool. For security reasons I need to edit the CLI history then to remove the password from it.

A feature like mentioned above would make it easier to get the mentioned password hashes instantly without the danger to unnecessarily pass the password around.

**Comment by lionkmp** [comment]
If you are using SALTED passwords, then you also need to copy the salt into KeePassXC password field, and maybe some separator character(s) - at that point the workflow is so cumbersome, that I'm not sure it has place in a simple end-user password manager. (But I may be underestimating the power of this idea... :) ) 

So far whenever I needed to generate a hashed password, the software that needed it had a **built in tool** for creating it and storing to the right file in the right format (e.g. htpasswd, dovecot, passwd, etc). So a tool for your own purpose doing the complete task could be more suitable - maybe.

**Comment by phoerious** [comment]
Yes. Simple, unsalted password hashes should not be used anywhere and there are way too many formats to store salted passwords. We also don't use most of the algorithms used for password hashing elsewhere, so this is definitely out of scope.
