### ISSUE TITLE
Password Generator puts space character in passwords

### ISSUE THREAD

**Issue by BrerRabbit999** [keepassxreboot/keepassxc#8541]
Release 2.7.1 in Ubuntu 22.04 KeepassXC put a space character in a new password, which the target website rejected.  I was using the default settings plus their list of special characters.  I did not see the space until I tried to type if character by character into their webpage. 

In order to generate an acceptable password I had to type a space character into the Do not include box, where it was invisible.

**Comment by droidmonkey** [comment]
Space is ascii character 32 which is not part of any character group: https://github.com/keepassxreboot/keepassxc/blob/develop/src/core/PasswordGenerator.cpp#L122

You must have added it yourself

**Comment by BrerRabbit999** [comment]
New information.  Their list of special characters has spaces between characters.  I assert that spaces in that list should be ignored by KeypassXC
<~ ` ! @ # $ % ^ & * ( ) _ - \ / |>

**Comment by droidmonkey** [comment]
Why would we ignore them? It is a totally valid character that people may want to include if they please.

**Comment by BrerRabbit999** [comment]
OK, since A. websites publish lists that separate valid characters with spaces, B. passwords (but maybe not passphrases) usually cannot contain spaces, C. I don.t want to get into ANSI character sets as variables,  perhaps KeypassXC could check the include list and if it sees CHRS$32 multiple times in the list, it could ask the user if it is intended to be an included character multiple times.

**Comment by BrerRabbit999** [comment]
There are lots of ways to implement that concept.  I leave it to you to find the best way.

**Comment by JohnLGalt** [comment]
> OK, since A. websites publish lists that separate valid characters with spaces, B. passwords (but maybe not passphrases) usually cannot contain spaces, C. I don.t want to get into ANSI character sets as variables, perhaps KeypassXC could check the include list and if it sees CHRS$32 multiple times in the list, it could ask the user if it is intended to be an included character multiple times.

If they did not want the spaces used to denote the acceptable character list to be included when generating passwords, first and foremost, the onus is on the website itself to specifically mention that space should not be used and is not acceptable.

Because not *all* websites block it, and not *all* passwords for different items block the usage of space as a character when making passwords. So, to have KeePassXC arbitrarily block it would be the worse scenario for functionality, IMO.

**Comment by droidmonkey** [comment]
I won't be doing anything about this to be honest
