### ISSUE TITLE
Previous entry's Notes do not clear when selecting subsequent entry with no Notes

### ISSUE THREAD

**Issue by ryehamstrawberry** [keepassxreboot/keepassxc#8543]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
Description: Previously selected entry's Notes don't clear when selecting subsequent entry with no Notes.
Screenshot: https://i.imgur.com/TJLiWva.png

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Select entry with Notes.
2. Select entry with no Notes.
3. See previous entry's Notes still displayed for entry with no Notes.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Notes field should display no input for entries with no saved Notes.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
After selecting an entry with saved Notes, any subsequent selection of an entry with no saved Notes will continue to display the Notes of the previous entry.

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.1-snapshot
Revision: b1f4e12

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows

**Comment by droidmonkey** [comment]
I fixed this problem, update your branch
