### ISSUE TITLE
Use Windows Hello for Initial Unlock

### ISSUE THREAD

**Issue by noenic** [keepassxreboot/keepassxc#8547]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )

I really like the fact that you can unlock the database with Windows Hello but it's a bit annoying to still need the master password when the app starts.

So I don't know if this is possible but :

Prompt the Windows Hello prompt UI when opening the Database from the CLI ( `KeePassXC.exe --pw-stdin database`) to unlock Quick Unlock 

OR 

Allow initial unlock to be done with Windows Hello

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )

Opening the Database from the command line, will prompt Windows Hello just like the GUI App

Or 

Store the master password somewhere safe and use Windows Hello to access and unlock the database

## Context

I don't know about the others, but my main use of KeePassXC is the web extension and I know that nobody has access to my computer but me, but having to put the master password every time I turn on my computer is a bit annoying especially when it's really long and complicated

It might be interesting to give the user the choice to lose some security for more ergonomics, I likes how dashlane asked every 14 days the masterpassword but doesn't ask me everytime.

On my IOS device I use KeePassium and the database can be open with FaceID even after closing the app

Maybe locking the App and let the database Open, to be able to use the web extension but lock the main App

**Comment by droidmonkey** [comment]
#7020
