### ISSUE TITLE
Bug regarding ALT key modifiers / window title with multiple tabs in GUI

### ISSUE THREAD

**Issue by fonic** [keepassxreboot/keepassxc#855]
## Current Behavior
When multiple tabs are displayed (i.e. multiple databases are open), ALT key modifiers are automatically assigned to the tabs, also the modifier character '&' is displayed in the window title.

I even at some point encountered the issue that the modifier character appeared in the filename when saving a new database, but I currently fail to reproduce this.

Screenshot:
![screenshot_20170808_092805](https://user-images.githubusercontent.com/14027079/29060932-17025786-7c1c-11e7-8a6e-6e3451fd2961.png)

## Expected Behavior

1. No ALT modifiers should be assigned to the tabs at all (see _'Possible Solution'_)

2. If the decision is to keep the modifiers, they should not show up in the window title

## Possible Solution
In my opinion, it doesn't make much sense to assign ALT modifiers to the tabs, as they would depend on database filenames. Instead, I'd like to suggest implementing **static global shortcuts** (e.g. _ALT + 1..9_) to switch between open tabs like Browser applications do (e.g. Firefox).

## Steps to Reproduce (for bugs)
1. Open multiple databases
2. At least once switch from one tab to another -> window title issue appears
3. Hold down ALT key -> tab modifiers become visible

## Debug Info
KeePassXC compiled from 'develop' branch as of 08/08/17

**Comment by phoerious** [comment]
It's a know KDE bug. We can't really do anything about it. If you add

.  [Development]
. AutoCheckAccelerators=false

To .config/kdeglobals, it will turn off automatic accelerators and get rid if the problem.
