### ISSUE TITLE
Notes field does not display all the information in the field.

### ISSUE THREAD

**Issue by Simva9** [keepassxreboot/keepassxc#8551]
## Overview
Notes field does not display all the information in the field.

## Steps to Reproduce
Display a database entry that has more than 15 lines in its notes field

## Actual Behavior
See screenshot 1.
The program fills half of the space available in the Notes box with information, and puts blank space below. This implies that this is the complete content of the Notes field.

See screenshot 2.
In fact, there is much more information in the Notes field that the program is not displaying.

The small, faint scroll bar on the right is not a strong enough visual clue that there is further information that the program is not displaying.

## Expected Behavior
Information in the notes field should be displayed all the way down to the bottom of the box.
There should be no blank space as there is now.

And ideally, the scrollbar should be thicker and darker to give a better visual clue.

KeePassXC - VERSION  2.7.1
Operating System: Windows 11
![Screenshot 1](https://user-images.githubusercontent.com/114251078/194319001-17ed74e8-3c33-42b3-a255-74bc871104dc.JPG)
![Screenshot 2](https://user-images.githubusercontent.com/114251078/194319004-f127478c-fa26-4e1f-acbc-074809a34492.JPG)

**Comment by droidmonkey** [comment]
Done for 2.7.2
