### ISSUE TITLE
UI resolution is not correct after wakeup from suspend mode

### ISSUE THREAD

**Issue by DeadOldMan** [keepassxreboot/keepassxc#8552]
How to reproduce:

1. Laptop with additional external display (different resolutions on both)
2. Laptop went into suspend mode
3. after wakeup the UI size is incorrect (it seems that the font and the icons are very large, but the window is in the old size)
4. the UI is not interacting any longer to Mouse action

I want to do a screenshot from this but keepassXC is hiding itsefl when i tried this.

**Comment by michaelk83** [comment]
https://keepassxc.org/docs/KeePassXC_UserGuide.html#_screenshot_security
Also paste the debug info from the About dialog.

Probably has to do with OS screen resizing when external monitor is "removed"/"added" during suspend and resume.

**Comment by DeadOldMan** [comment]
KeePassXC - Version 2.7.1
Revision: 5916a8f

Qt 5.15.3
Diagnosemodus ist deaktiviert.

Betriebssystem: Windows 10 Version 2009
CPU-Architektur: x86_64
Kernel: winnt 10.0.22621

Aktivierte Erweiterungen:
- Auto-Type
- Browser-Integration
- SSH-Agent
- KeeShare
- YubiKey
- Schnelle Entsperrung

Kryptographische Bibliotheken:
- Botan 2.18.1

![2022-10-06 (2)](https://user-images.githubusercontent.com/5906976/194362648-eebabcbf-7ee2-439e-ba94-833450d95664.png)

**Comment by droidmonkey** [comment]
Do the monitors use different ui scaling values? (Eg 100% and 150%)

**Comment by DeadOldMan** [comment]
@droidmonkey you are totaly right.
The latop internal monitor was set to 125% ui scaling and the external Monitor to 100%.
When i set both to 100% the ui from KeepassXC is correct after leaving the suspend mode.

**Comment by droidmonkey** [comment]
In this case you will need to set one of the Qt high dpi environment variables to properly detect the correct scaling to use since Qt can't seem to pick that up.

QT_SCREEN_SCALE_FACTORS or QT_SCALE_FACTOR_ROUNDING_POLICY

See https://keepassxc.org/docs/KeePassXC_UserGuide.html#_command_line_options

Unfortunately this isn't something we can fix, it is a Qt problem.
