### ISSUE TITLE
No way to change default entry listing order.

### ISSUE THREAD

**Issue by bjwest** [keepassxreboot/keepassxc#8555]
## Overview
When first opening a database, KeePassXC displays passwords titles in some seemingly random order.

## Steps to Reproduce
1.  Open KeePassXC and password database.
2.  Click on a group to view entries within that group.

## Expected Behavior
Entries within that group are in an order that easily allows selection of desired entry, such as alphabetical.

## Actual Behavior
Entries within grope are in some random order until 'Title' header is clicked to sort them in alphabetical order.

## Context
I'm assuming this is some sort of most frequently used order, but that is not what should be as the only, nor the default sort order.  Alphabetically should be the default, and any other sort should be allowable in the settings.  I'm reporting this as a bug, because this is a somewhat new issue, and I’m assuming was a mistake in programming.

KeePassXC - Version 2.7.1
Revision: 5916a8f

Qt 5.15.6
Debugging mode is disabled.

Operating system: KDE neon User - 5.25
CPU architecture: x86_64
Kernel: linux 5.15.0-48-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.12.1

Operating System: KDE neon 5.25
KDE Plasma Version: 5.25.5
KDE Frameworks Version: 5.98.0
Qt Version: 5.15.6

**Comment by droidmonkey** [comment]
Make sure you aren't clearing your ~/.cache folder. The default sorting order is by the order the entries are in the xml representation of your database, this is called "natural order". When you choose a column to sort by, that is saved when you exit the program.
