### ISSUE TITLE
[Bug] TOTP /2FA Code Lies to Me

### ISSUE THREAD

**Issue by ThisNekoGuy** [keepassxreboot/keepassxc#8556]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
OTP / 2FA keeps giving me wrong codes for anything I have set up with it; this didn't used to be the case, and I can only explain this as somehow KeePassXC being responsible for this because when I use KeePassDX (Android KeePass) I get a different code thanwhat KeePassXC tells me that actually works with the same database.

This is troublesome, since this makes accessing my accounts if I don't have access to my phone for some reason painfully difficult if not impossible.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Install KeePassXC (for Arch Linux)
2. Set up TOTP / 2FA for a site
3. Attempt to use the shown code(s)

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
TOPT / 2FA shouldn't lie to me about what the authentication code is.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
I consistently get incorrect authentication codes for TOTP / 2FA with KeePassXC despite this not being the case with the same database on a separate KeePass client.

## Context
[NOTE]: # ( Give us any additional information you may have. )
I don't know when this started occurring, so there's not a whole lot I can say about this besides examples of services I've attempted to use this with:
- Gitea
- Discord
- Minds

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.1
Revision: 5916a8f

Qt 5.15.6
Debugging mode is disabled.

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: [linux 5.17.2-256-tkg-pds](https://github.com/frogging-family/linux-tkg)

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.19.2

[NOTE]: # ( Pick choices based on your environment )
Operating System: Arch Linux
Desktop Env: KDE Plasma 5.25.5
Windowing System: X11

**Comment by droidmonkey** [comment]
Sync your computer time.

**Comment by ThisNekoGuy** [comment]
@droidmonkey My time is synced, what are you talking about?

**Comment by whonion** [comment]
> Sync your computer time.

Hmm, I think that this bug version 2.66 and more too. Thanks!

**Comment by Daniel6801** [comment]
I have the same issue and found out that I get the correct OTP password if I set the timezone to "UTC" in the windows clock settings. Looks like Keepass use the local time instead of UTC. I tested this with Version KeePassXC - Version 2.7.1
