### ISSUE TITLE
Standalone password generator

### ISSUE THREAD

**Issue by UltraBlackLinux** [keepassxreboot/keepassxc#8557]
## Summary
I would love to have the keepassxc as a standalone application

## Context
I recently switched from keepassxc to [pass](https://passwordstore.org), but I have been facing one problem ever since: There don't seem to exist any good password generators which generate actually secure passwords (Well, I don't mean all of them are bad, but in KeePassXC I can at least be sure that my passwords are secure because it tells me how secure they are.)

I tried to find something similar, but to no avail.

**Comment by droidmonkey** [comment]
We have one, click the dice icon in the toolbar

**Comment by UltraBlackLinux** [comment]
I don't need a fully fledged password manager around it. I would like to have a more light weight and still capable one

Keepass is 25 MB in Size, I don't use 99% of that

**Comment by droidmonkey** [comment]
Use the cli then: `keepassxc-cli generate [options]`

If you want to make a super lightweight generator just extract our password generator code and wrap it in a simple cli interface. You would still need to interface with an RNG or wrap /dev/urandom if you are Linux only.
