### ISSUE TITLE
Prevents Windows shutdown even if there are no unsaved changes

### ISSUE THREAD

**Issue by M-Pixel** [keepassxreboot/keepassxc#856]
I have auto-save enabled in KeePassXC.

## Expected Behavior
When I shut down my computer, the program will receive the termination signal and close.

## Current Behavior
When I shut down my computer, my OS informs me that KeePassXC is preventing the shutdown from completing.

## Steps to Reproduce (for bugs)
1. Open a database in KeePassXC in Windows 10
2. Turn on autosave if it is not already on
3. Shut down or reboot

## Debug Info
KeePassXC - 2.2.0
Revision: caa49a8ef3ee28ed478192389b21d61107b3b8e0

Libraries:
- Qt 5.9.0
- libgcrypt 1.7.7

Operating system: Windows 10 (10.0)
CPU architecture: x86_64
Kernel: winnt 10.0.15063

Enabled extensions:
- KeePassHTTP
- Auto-Type
- YubiKey

**Comment by droidmonkey** [comment]
I have not personally experienced this issue. Are you storing your database on a cloud service by chance?

**Comment by weslly** [comment]
I can reproduce it on macOS: 

![image](https://user-images.githubusercontent.com/107672/29107159-224aaa24-7caf-11e7-87f0-86d5e975c082.png)

Maybe related to #580?

**Comment by M-Pixel** [comment]
I suspect that it only occurs when a change or addition has been made. I can confirm that pressing the save button (which is redundant given the autosave option) does not free up the shutdown-blocking state, but closing the database does.

**Comment by MicahStevens** [comment]
I have this happen under KDE on Arch Linux. KDE will hang on shutdown stating that KeepassXC is preventing it from shutting down. If I issue a second shutdown command, it will shut down. This is KDE behavior, but I don't know why it's targeting KeepassXC. I can confirm this happens whether or not there are pending changes in KeepassXC.

**Comment by ipilcher** [comment]
Seeing this on Fedora 26 with Plasma.

**Comment by Chemrat** [comment]
Same on Gentoo & Plasma 5.11.4

This may happen if application ignores closeEvent for main window for no good reason

**Comment by yennor** [comment]
I've got the same issue using the plasma desktop in debian stable.
The message in .xsession-errors states:

ksmserver: Client  "/usr/bin/keepassxc"  ( 10c1bcb862000152058065200000015090010 ) canceled shutdown.

**Comment by PlqnK** [comment]
This bug is back for me since the 2.4.0 update!

**Comment by droidmonkey** [comment]
Please open a new issue with all of your system details from the KPXC About -> Debug page.
