### ISSUE TITLE
Make delete confirmation setting more obvious for users

### ISSUE THREAD

**Issue by TheMarkofCain** [keepassxreboot/keepassxc#8561]
Hi there!

I am a new user to KeePassXC and I have to say that I am absolutely LOVING IT!!! I love that it is open source and truly community run. It is my first password manager and I have to say that I feel so much better now that I have a password manager, I feel so much safer now that I use. it.

I have noticed that when I delete an entry (login and password) by clicking on the "Delete" button on the toolbar it deletes the entry straight away without any "Are you sure you want to delete this login and password?".  I think that it would be a good feature to add a challenge query to prevent people (me) from accidentally deleting an entry. This is particularly worrying as the Delete button is right next to the "Copy username to clipboard" button.

I know that they go to the Recycle Bin and are not immediately deleted but it really freaked me out the first time that it happened.

Thanks everyone!

**Comment by droidmonkey** [comment]
Glad you are enjoying the program and welcome! We already have that option, but I noted that it is a double negative option and its buried in the security settings. We can make that better:

![image](https://user-images.githubusercontent.com/2809491/194857557-e81c0746-e36e-4a50-ad95-b54dd71edd5e.png)

**Comment by TheMarkofCain** [comment]
Thank you for that! I have now updated my security settings from your recommendation, much appreciated!!! Maybe the "Move entries to recycle bin without confirmation" should be unselected by default?

As a side note, I have found it to be absolutely hilarious when I use the password generator to create a 17 character random password with all sorts of characters and it says that the password is only "Good". It always makes me chuckle to think that is only "Good" when there are people out there still using basic words for their passwords.

Thanks again!

**Comment by Ebermelho** [comment]
This option marked in red is not available in the KeePassXC 2.7.4 for the MacOs in any form. That is highly necessary.

Adding to the previous comments, my suggestions are: 
1. Move the Delete button away from more used buttons like change and copy username (maybe after the settings button). Or even give the option to remove it from the quick bar completely, making Delete a function accessible only by right mouse click and/or menu option (including mass delete with checkboxes and a list for selection).
2. In any case give it a more explicit and universally recognizable icon like the Trashcan.

Thank you all for contributing to this amazing project!

**Comment by pabloespejo** [comment]
> Thank you for that! I have now updated my security settings from your recommendation, much appreciated!!! Maybe the "Move entries to recycle bin without confirmation" should be unselected by default?
> 
> As a side note, I have found it to be absolutely hilarious when I use the password generator to create a 17 character random password with all sorts of characters and it says that the password is only "Good". It always makes me chuckle to think that is only "Good" when there are people out there still using basic words for their passwords.
> 
> Thanks again!

I agree **the option should be unselected by default.**

I deleted a register by mistake of my mouse, and luckily I noticed it.

And I also agree it is very difficult to find the option in the menu because it is in "Security" and also because of the text (in spanish says "Mover apuntes a la papelera de reciclaje sin confirmación" and should be something like "Do not show confirmation when you delete a register".

I think it would be a great idea to change this, that should be easy to change.

And of course, thank you for your excellent software, I Just donated 20 euros via Paypal.

It would be awesome to have also a cellular app for iOS / Android.

**Comment by droidmonkey** [comment]
We recommend StrongBox/KeePassium on iOS and KeePassDX on Android

**Comment by pabloespejo** [comment]
> We recommend StrongBox/KeePassium on iOS and KeePassDX on Android

Yes, in fact I already use Keepassium, but there was a KeepassXC option, I would use it.

Thanks for your answer.

**Comment by michaelk83** [comment]
@TheMarkofCain None of the discussed changes have been implemented yet, so this shouldn't be closed.

**Comment by ozinka** [comment]
Hi, I'm joining to this conversation and agree with topic starter. This option is not obious and I found it here only with googling. And yes, this option should be enabled by default. I've deleted a few records and my trash already contains records... anyway, on unintentional deletion it's not easy to restore.

**Comment by phoerious** [comment]
I don't think it should be enabled by default. Both macOS and many Linux desktops handle it this way, so it shouldn't be fully unexpected. I find the extra confirmation for an undoable action unnecessary.

**Comment by ozinka** [comment]
Probably, the main problem is that it's easy to mix buttons "add" and "delete". You cannot revert accident deletion (Ctrl+Z?), as DB is autosaved on any record operation (in my case). Buttons have the same color (absense of color). I can name dozen examples, where deletion by default has confirmation (and for Mac and Linux as well) and think it's best practice in UI deveopment. But taking into account that:
1. my problem is resolved - plus one exception to known default actions among hundreds of tools which I use
2. you insist on keeping that as is - it's your vision as author's
I'm not going to continue. That was just sharing my personal opinion, not a reason for disput.
BTW, thnx for the great tool.
