### ISSUE TITLE
Database unlocks successfully when you cancel Windows Hello Prompt

### ISSUE THREAD

**Issue by Mattizin** [keepassxreboot/keepassxc#8562]
## Overview
I'm using Windows Hello (Fingerprint) in addition with the Master Password and Key file to protect my Database.
Accidental, I clicked "Cancel" when the prompt appeared, and I was surprised the database still unlocked successfully.

## Steps to Reproduce
[NOTE]: # (Provide a simple set of steps to reproduce this bug. )
1. Open Locked Database (either Master password and then Windows Hello or only reopening with Windows Hello)
2. Don't execute the prompt, click "Cancel" button
3. Database unlocks successfully

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
When I don't execute the Windows Hello Prompt, the database should not be unlocked.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
The database unlockes successfully.

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.1
Revision: 5916a8f

Qt 5.15.3
Diagnosemodus ist deaktiviert.

Betriebssystem: Windows 10 Version 2009
CPU-Architektur: x86_64
Kernel: winnt 10.0.22000

Aktivierte Erweiterungen:
- Auto-Type
- Browser-Integration
- SSH-Agent
- KeeShare
- YubiKey
- Schnelle Entsperrung

Kryptographische Bibliotheken:
- Botan 2.18.1

[NOTE]: # ( Pick choices based on your environment )
Operating System:
Edition	Windows 11 Enterprise
Version	21H2
Build 22000.978
Windows Feature Experience Pack 1000.22000.978.0

**Comment by droidmonkey** [comment]
When unlocking for the first time, that just means you don't enable quick unlock. You already provided your credentials... so the database unlocks. 

> only reopening with Windows Hello

This is called quick unlock, guaranteed hitting cancel doesn't work in this scenario.
