### ISSUE TITLE
favicon "download" only pulls from root website

### ISSUE THREAD

**Issue by G2G2G2G** [keepassxreboot/keepassxc#8564]
Note these are two different favicons:
https://www.municipalonlinepayments.com/
and
https://www.municipalonlinepayments.com/rogerswaterutilitiesar/utilities

but it will only pull the first link's favicon

**Comment by phoerious** [comment]
This is because we are only  checking https://www.municipalonlinepayments.com/favicon.ico (which does not exist) and DuckDuckGo, which apparently retrieves the same icon for both.

**Comment by phoerious** [comment]
Actually, I just noticed there is also a pending PR, which wouldn't solve your particular issue, but might fix similar problems.
