### ISSUE TITLE
Saved profiles in Password Generator

### ISSUE THREAD

**Issue by Massimo-B** [keepassxreboot/keepassxc#8567]
Just like the current version of [Keepass2Android](https://github.com/PhilippC/keepass2android/), please provide a list of preconfigured and also custom saved profiles inside the Password Generator password tab.

I often need to create a list of passwords on different platforms following different password policies and lengths. Often I can't remember what special policy allows which characters and lengths, sometimes it's not even documented and only found by trial-and-error.

**Comment by droidmonkey** [comment]
Duplicate request

**Comment by Massimo-B** [comment]
Duplicate of #19.

**Comment by Massimo-B** [comment]
Duplicate of #2628.
