### ISSUE TITLE
Context menu shows the wrong key combination (ctrl-C does not copy password anymore)

### ISSUE THREAD

**Issue by Algorithman** [keepassxreboot/keepassxc#8572]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

Context-Menu still shows ctrl-c to copy password though it seems it's ctrl-shift-c now.
And please if you do such updates tell people that after the update (first run popup with the changes?)

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Right-click entry on the right panel
2. second option is copy password 

![image](https://user-images.githubusercontent.com/2128945/195375434-6691a84b-b2bb-46bb-83ad-1471b368f3e7.png)

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Context-Menu should tell the correct key combination to copy password?

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Ctrl-C copies the entry name

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.1
Revision: 5916a8f

Qt 5.15.3
Debugging mode is disabled.

Operating system: Windows 10 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.19044

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 2.18.1

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 10
Desktop Env: --
Windowing System: --

**Comment by droidmonkey** [comment]
No its still Ctrl+C. If you have text selected it will copy the text instead of the password.
