### ISSUE TITLE
keepassxc-cli search don't use group names

### ISSUE THREAD

**Issue by martin-v** [keepassxreboot/keepassxc#8574]
Foremost thanks for the great software :)

## Steps to Reproduce
1. Create DB -> `keepassxc-cli db-create -p test`
2.  Add a group `foo` -> `keepassxc-cli mkdir test foo`
3.  Add a entry `bar` in group `foo` -> `keepassxc-cli add test foo/bar -g`
4. Call `keepassxc-cli search test foo` , but the entry `foo/bar` is not found.
5. Call `keepassxc-cli clip -b test foo`, but the entry `foo/bar` is not found.
6. Check if `foo/bar` still exists `keepassxc-cli ls -Rf test`

## Expected Behavior
`search` and `clip -b` should find entries based on group names.

## Actual Behavior
If I'm looking for entries in a group by group name results are empty.

## Context
```
% keepassxc-cli --version
2.7.1
```
Operating System: Linux
Desktop Env: Gnome
Windowing System: Wayland

**Comment by martin-v** [comment]
my workaround
```sh
function keepass() {
	if [ "$1" = "search" ] ; then
		keepassxc-cli ls $KEEPASS_DB -fR | grep "${@:2}"
	else
		keepassxc-cli $1 $KEEPASS_DB "${@:2}"
	fi
}
```

**Comment by droidmonkey** [comment]
Search only finds entries. If you want to find groups or restrict your search to a group use the `g:` prefix in your search. So it would be `search "g:foo bar"`

**Comment by martin-v** [comment]
What is the reason behind this g prefix? In my opinion it just reduces usability, I don't care why it finds it, as long as it does.

Besides `g:foo` don't work for `-b`
```
% keepassxc-cli clip -b test g:foo
Using matching entry: g:foo
Entry g:foo not found.

% keepassxc-cli clip -b test "foo/bar"
Using matching entry: foo/bar
Entry's "Password" attribute copied to the clipboard!

% keepassxc-cli search test "foo/bar"
No results for that search term.
```
A bit inconsistent.

**Comment by droidmonkey** [comment]
You need to wrap your entire search in quotes

**Comment by martin-v** [comment]
That would be surprising unless IFS is set to any char in the string, e.g. `:`, which it [usually is not](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_06_05).

```
% keepassxc-cli clip -b test "g:foo"  
Using matching entry: g:foo
Entry g:foo not found.
```

**Comment by droidmonkey** [comment]
The -b option is meant to find an entry by title, but you can abuse the way its programmed to run any search. You need to wrap the whole search in quotes though:

`keepassxc-cli clip -b test.kdbx "bar g:foo"`

As long as the first word will match a title, you are golden. I agree that this behavior is somewhat inconsistent and assuming your intentions. @louib 

https://github.com/keepassxreboot/keepassxc/blob/develop/src/cli/Clip.cpp#L84
