### ISSUE TITLE
Passphrase entropy calculated too low!

### ISSUE THREAD

**Issue by koerli89** [keepassxreboot/keepassxc#8580]
I recently wanted to start using passphrases in some instances because obiously they are easier to memorize.
However, i was surprised by how little the entropy is.

I compared the entropy to a calculator which also uses [zxcvbn]:
Password: resample_carat_unjustly_karma_tyke
KeepassXC Entropy: 64,62
https://apps.cygnius.net/passtest/ Entropy: 111.632

Also the Entropy in KeepassXC (passPHRASE) does not change when letters for spacing are introduced.
I am no expert in passwords but "resample_carat_unjustly_karma_tyke" seems saver than "resamplecaratunjustlykarmatyke"

Indeed when i enter "resample_carat_unjustly_karma_tyke" in the "normal" passWORD field it shows the same Entropy as cygnius (111)

**Comment by droidmonkey** [comment]
See #861 and #867. There are plenty of other closed issues that have discussion about this as well.
