### ISSUE TITLE
Custom browser integration

### ISSUE THREAD

**Issue by Flashwalker** [keepassxreboot/keepassxc#8586]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
We want customizable browser integration.

Not only hard-coded brands like this:
![image](https://user-images.githubusercontent.com/2188215/196021142-46952778-5cbb-4225-bb78-d896f3cb8e0b.png)

But with ability to set integration for Chromium derivatives or Firefox derivatives, e.g. Ungoogled-Chromium or LibreWolw.

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )

**Comment by droidmonkey** [comment]
Already available under the advanced tab of that settings view. Make sure you are running version 2.7.1.

**Comment by Flashwalker** [comment]
> Already available under the advanced tab of that settings view. Make sure you are running version 2.7.1.

Okay, but I can specify the only one browser there, Chromium or Firefox (based) through the _Config Location_ field i guess?
But what if I want more than one...
And what should I enter in this field, the path to which file?

**Comment by droidmonkey** [comment]
You need to manually copy/move the native messaging configuration file to the respective browser's configuration location. We aren't going to make any more accommodations for custom browsers beyond what is there.

**Comment by Flashwalker** [comment]
> You need to manually copy/move the native messaging configuration file to the respective browser's configuration location. We aren't going to make any more accommodations for custom browsers beyond what is there.

ok, regarding Firefox browser type this location (as i can see in placeholder) is `~/.config/mozilla/native-messaging-hosts/`, is it?
(actually it doesn't exist by default)
And where is it for Chromium?

**Comment by droidmonkey** [comment]
You'll have to read the documentation for the browser and installation method you chose.
