### ISSUE TITLE
Wrong input of database password when using Chinese IME on macOS

### ISSUE THREAD

**Issue by y2-Whyto** [keepassxreboot/keepassxc#8588]
## Overview

On macOS, when inputting the main password of a database, if I enable Chinese IME, the input of the password seems not the letters I strike (wrong password).

Only if I change to English mode can I input the right string.

By the way, this issue doesn't occur on Windows and Linux as I remember.

## Steps to Reproduce

1. Open the interface of inputting the password of a database.
2. Ensure Chinese IME is enabled (for example, native Chinese Simplified IME on macOS).
3. Input the password (with letters in it) and press Return.

## Expected Behavior

The input of the ASCII password of the database should be raw characters, regardless of which IME the users use. 

## Actual Behavior

The password I strike seems processed by the IME first and then inputted.

## Context
The issue occurs when entering password for the database.

KeePassXC - VERSION 2.7.1
Revision: 5916a8f
Operating System：macOS 12.6
CPU Architecture：x86_64
Kernel：darwin 21.6.0

**Comment by droidmonkey** [comment]
Please file this big with Qt. We don't handle keyboard input into text input fields. https://bugreports.qt.io
