### ISSUE TITLE
Global Autotype Shortcut field turned red when Windows 10 wake from sleep

### ISSUE THREAD

**Issue by Rainrainraind** [keepassxreboot/keepassxc#8596]
The Global Autotype Shortcut field turned red when Windows 10 wake from sleep, have to always assign new key.

**Comment by droidmonkey** [comment]
This isn't something we can fix or control. Just choose a different key combo because the one you have chosen is not available or something.

**Comment by phoerious** [comment]
As I understood it, that was exactly the problem. Something blocks the shortcut after waking from standby. Not sure if it's our fault, though. I have never seen this before.
