### ISSUE TITLE
Support cleaning secrets from `clipcat` clipboard manager

### ISSUE THREAD

**Issue by zefr0x** [keepassxreboot/keepassxc#8599]
## Summary
As a linux tiling window manager user I use [clipcat](https://github.com/xrelkd/clipcat) as a clipboard manager. I think it's a great manager and it supports deleting history entries. For now I can see that [Klipper](https://userbase.kde.org/Klipper) is supported in KeePassXC for deleting entries after the time ends. I don't know how it was implemented for Klipper (mabey [Dbus](https://www.freedesktop.org/wiki/Software/dbus/)?), but I think that it is possible for Clipcat also.

## Context
I did a research and I tested a lot of clipboard managers, but I coudn't find any one that intergrates very well with workflow. Nearly all of them don't even have an interface for deleting history entries.
Klipper is a great cliboard manager and it works great with KeePassXC, but it doesn't come alone, it needs nearly 30 dependencies (even `kwin` is one of them).

**Comment by droidmonkey** [comment]
They don't seem to support a mime-type or standard way to say "DO NOT store this as a history" which is how it works with klipper. We don't remove the item from Klipper, we tell Klipper that the item is sensitive and don't store it.
