### ISSUE TITLE
Entries with references use window background color

### ISSUE THREAD

**Issue by NiceGuyIT** [keepassxreboot/keepassxc#860]
Note: _This is specific to Linux and possibly KDE._
When cloning an entry with "Replace username and password with references" selected, the username and password are replaced with references like `{REF:U@I:UID}`. This causes the color of that entry to use the window background instead of a more appropriate color like inactive text, negative text, etc. This makes the text unreadable with a dark scheme.

## Expected Behavior

The text should be readable.

## Current Behavior

The text is unreadable due to the color used. I know it's not really the color, rather the widget property used to style the item. I'm not a GUI programmer and don't know the proper terminology.

## Possible Solution

Style it with an appropriate color from the view color set.

## Steps to Reproduce (for bugs)

1. Use KDE on Linux.
2. Change the color scheme to a dark color scheme. System Settings -> Appearance -> Colors
3. Clone an entry and select the option to use references. OR add `{REF:U@I:UID}` to the username and reopen KeePassXC.
4. Notice the unreadable text.

## Context

I can't read entries with references.

## Debug Info

KeePassXC - Version 2.2.0 (2.2.0-15.1 from the openSUSE repository)
Revision: caa49a8ef3ee28ed478192389b21d61107b3b8e0

Libraries:
- Qt 5.6.1
- libgcrypt 1.6.1

Operating system: openSUSE Leap 42.2
CPU architecture: x86_64
Kernel: linux 4.4.74-18.20-default

Enabled extensions:
- KeePassHTTP
- Auto-Type
- YubiKey

## Screenshots
This is the Obsidian Coast scheme. The 3rd entry is highlighted.
![image](https://user-images.githubusercontent.com/7763429/29179777-8b00546e-7dc3-11e7-8bb2-9c2f2813fb26.png)

If I change the Window Background to green...
![image](https://user-images.githubusercontent.com/7763429/29179861-d75da35c-7dc3-11e7-99fb-93451a167678.png)

I get green text.
![image](https://user-images.githubusercontent.com/7763429/29179909-026776e0-7dc4-11e7-8d6e-7ddc190df1de.png)

## Other info
I have _Apply colors to non-Qt applications_ checked.

Here's the KDE version from KInfocenter.
- KDE Plasma Version: 5.8.6
- KDE Frameworks Version: 5.26.0

**Comment by szymonbultrowicz** [comment]
Any update to this issue? It also occurs on MacOS Mojave 10.14.3
![image](https://user-images.githubusercontent.com/9554528/52306641-c944ae00-2998-11e9-8365-773c3db1fedf.png)

**Comment by maniattico** [comment]
Same issue here in Manjaro Linux with KDE Plasma 5.14.5 and gnome 3.28.

![keepassxc](https://user-images.githubusercontent.com/34938251/53095123-45ec9600-351c-11e9-8330-0535bba4b83b.png)

**Comment by kingfame** [comment]
Any update? Since 2.4.0 will use dark mode when enabled in Mojave this is a huge problem, as 80% of my entries use references and they are not readable anymore:

![image](https://user-images.githubusercontent.com/16594046/55980663-3de7e180-5c95-11e9-8b8d-b468d560e93e.png)

**Comment by guixxx** [comment]
I'm still seeing this happening on KDE Plasma 15.5.5. I'm using the Breeze Transparent Dark theme:

![image](https://user-images.githubusercontent.com/27077338/58708395-0ee51680-838e-11e9-999a-77b4035b0b7f.png)

## Debug Info
KeePassXC - Version 2.4.1
Revision: 7bafe65

Qt 5.12.3
Debugging mode is disabled.

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 5.1.5-arch1-2-ARCH

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.4

**Comment by droidmonkey** [comment]
This fix was specific to macOS.

**Comment by guixxx** [comment]
Oh, my bad. Should I open a new issue then?

**Comment by droidmonkey** [comment]
Yes please. We need to have a more generic way of detecting "dark mode" across platforms.
