### ISSUE TITLE
Add new database report based on yubikey support

### ISSUE THREAD

**Issue by Daemonslayer2048** [keepassxreboot/keepassxc#8601]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )  
The idea here is to add the ability to run another report type (similar to `Health Check` and `HIBP`), that will parse over the yubico service support page. Yubico hosts a site that includes a list of applications that support a yubikey (and what yubikey is supported) and can be found here: `https://www.yubico.com/works-with-yubikey/catalog/?sort=popular` 
  
With a just a bit of snooping around there is an API endpoint that returns the catalog in JSON: `https://www.yubico.com/api/wwyk/all`, the API can be parsed with `jq` from shell to show that most (if not all entries) come with a setup link that the reports page could send the user to: `curl -s https://www.yubico.com/api/wwyk/all | jq '.partnerproducts | .[].recurring_links.partner_setup_link'`

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )
Warning: I am not a GIMP expert  

![Screenshot from 2022-10-17 17-37-51](https://user-images.githubusercontent.com/43078293/196304805-0c80fa76-c03f-4838-9554-72d5f522c732.png)

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
Yubikeys are becoming more and more popular and KeePassXC already supports hardware token auth for the database, so adding support links for yubikeys appears to make sense and would be another factor that may help users choose KeePassXC over other solutions.

**Comment by droidmonkey** [comment]
I don't understand how that benefits us? We aren't a party in the yubikey authentication outside of unlocking your database. Is that api public or fished out of the website? If it's not public and documented then this is definitely not being implemented.

**Comment by Daemonslayer2048** [comment]
I believe it benefits the project because much like the "have i been pwned" integration helps users find compromised passwords this would help users find applications that support hardware tokens. 
If I could get yubico to be open to it would you be more willing to implement this?

**Comment by droidmonkey** [comment]
I would rather just link to this site from our documentation

**Comment by Daemonslayer2048** [comment]
Well your project, your rules, I totally respect that. I would love to add yubicos page to the documentation if permissible.  
On another note I am a fan of the project so I certainly want to understand your reasoning, Is the main issue the extra work involved? Is there something to what I am asking that is a hard no/turn off?

**Comment by droidmonkey** [comment]
There is no reason to include this into the program, the API is not public and can change at any time, and this adds extra networking code and code in general that we would need to maintain.

**Comment by Daemonslayer2048** [comment]
Understandable. However you have no issue with adding extra documentation to the repo that may direct users to this site for more info correct? If so I would like to at least add that so users can find extra resources for improving their personal security.

**Comment by droidmonkey** [comment]
We could use some more documentation on yubikeys in general, so yah I welcome that quite a bit.

**Comment by Daemonslayer2048** [comment]
Okay fair enough. I will come up with something in the next few days.
