### ISSUE TITLE
Missing qt5 library in windows 10/11 msi installer

### ISSUE THREAD

**Issue by Eckaaaaaat** [keepassxreboot/keepassxc#8603]
After installing the windows 10/11 msi package of version 2.7.1 it failed to start because qt5 library was missing.
The portable version is working fine as well as legacy installer.

If qt5 is not included in the msi by intention, than it should be mentioned on dowload page (like MSVC Runtime requierement).

**Comment by droidmonkey** [comment]
There is nothing missing, reinstall the package.
