### ISSUE TITLE
Parent login for multiple entries

### ISSUE THREAD

**Issue by jerry-ne** [keepassxreboot/keepassxc#8604]
## Summary
Please add support to edit multiple entries (#1314) or make parent login for multiple entries.

## Context
When I change AD password I must go to change too many entries in my DB. Edit multiple entries or have central place (parent login) will be fine.

**Comment by michaelk83** [comment]
Please explain why you have multiple entries for a password. This is usually bad practice.

**Comment by jerry-ne** [comment]
Hello @michaelk83 I am using same password (Active Directory) for multiple entries because AD password is used for multiple company systems (LDAP auth). For example: wiki, email, etc. So each DB's entry for unique URL.
Yes, I can use in one DB entry multiple URLs, but some systems (entries) have unique notes, tags. From v2.7.0 there are tags. I am using tags in which system I have setup 2FA and which technology of 2FA I was used there. One completed setup 2FA is possible to generate 10 recovery keys... 
So have one entry and all URLs is not good choice. Just imagine 20 systems and all these system have 20*10 lines of recovery codes and different my own notes... to long informations for one entry.

**Comment by droidmonkey** [comment]
Use the entry clone feature. Read the user guide for more information and to know the entry reference syntax.
