### ISSUE TITLE
KeePassXC crashes almost immediately on Fedora 36

### ISSUE THREAD

**Issue by tromlet** [keepassxreboot/keepassxc#8605]
## Overview
New problem here - KeePass 2.7.1 crashes very shortly after it's opened on Fedora 36.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Open a password database.
2. Wait.

## Expected Behavior
I expect KeePassXC to stay open, running, and accessible for the duration of my session on the machine.

## Actual Behavior
KeePassXC crashes rather quickly after opening.

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.1
Revision: 5916a8f
Distribution: Flatpak

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux (Fedora 36, kernel-5.19.15-201.fc36.x86_64)
Desktop Env: Gnome
Windowing System: Wayland

**Comment by phoerious** [comment]
Sounds like your installation is corrupt. We need at least an error message or stack trace to debug this.
