### ISSUE TITLE
Entropy/password strength doesn't refresh when re-generating a passphrase-type password

### ISSUE THREAD

**Issue by siliconninja** [keepassxreboot/keepassxc#861]
When I create a passphrase, its entropy/password quality values are used for subsequent passphrases that I generate. This happens in the Password Generator menu and when generating a new password in an existing entry. This doesn't happen when I change the number of words, but does happen when I change the separator between words.

## Expected Behavior
The entropy/password quality bar should change on each subsequent passphrase generated when changing the separator between words or re-generating the same word length passphrase with the "Generate" button.

## Current Behavior
The entropy value is OK when I change the number of words, but does happen when I change the separator between words or re-generating the same word length passphrase with the "Generate" button.

## Possible Solution
It's possible this could be due to a class or method being used for the password generator and would be a fix for both the password generator tool (Tools-->Password Generator), the dice icon in the top toolbar, and when generating passwords in an entry by clicking the dice icon. Maybe an event listener needs to change.

## Steps to Reproduce (for bugs)
1. Open an existing password entry.
2. Click the "dice" icon and click on Passphrase.
3. Re-generate a passphrase by clicking on the "Generate" button. See that the entropy/password quality doesn't change.
4. Change the text in the "Word Separator" text field. See that the entropy/password quality doesn't change.

## Context
I want to find the entropy/strength of generated passphrases to be able to create stronger and easy to remember passwords.

## Debug Info
KeePassXC - Version 2.2.0
Revision: caa49a8ef3ee28ed478192389b21d61107b3b8e0

Libraries:
- Qt 5.9.1
- libgcrypt 1.8.0

Operating system: Antergos Linux
CPU architecture: x86_64
Kernel: linux 4.12.4-1-ARCH

Enabled extensions:
- KeePassHTTP
- Auto-Type
- YubiKey

**Comment by TheZ3ro** [comment]
That is the correct behavior.
Since you are using a Diceware passphrase the entropy is based only on the number of selected words from the wordlist.
It doesn't (really) depends on which are those words and on their separator 
(in reality it's more complex than this, but it's a good esteem)

**Comment by siliconninja** [comment]
That makes sense. Thanks for the explanation.
