### ISSUE TITLE
Wrong behaviour when double clicking a searched password for macOS

### ISSUE THREAD

**Issue by jarnaez728** [keepassxreboot/keepassxc#8610]
## Overview
When I use the search bar to find a password and I double click on the desired result, instead opening the window to edit that password, some unexpected behaviour happens like it doesn't open, three or four rows in the list are automatically selected or a strange movement in the list of passwords happen. After that, I double click again on the result and it works ok, opening the entry on edit mode.

## Steps to Reproduce
1. Open KeePassXC 
2. Use the search bar to find some element
3. Double click on one of the searched elements

## Expected Behavior
The item is opened in edit mode

## Actual Behavior
There are three possible behaviours:
* I see a strange movement in the list of keys
* Three or four keys are automatically selected
* Sometimes it works as expected, usually after it failed a first time.

## Context
It doesn't happen if you don't use the search bar and just browse your passwords.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Versión 2.7.1
Revisión: 5916a8f

Qt 5.15.2
Modo de depurado deshabilitado.

Sistema operativo: macOS 12.6
Arquitectura de CPU: x86_64
Núcleo: darwin 21.6.0

Extensiones habilitadas:
- Autoescritura
- Integración con navegadores
- Agente SSH
- KeeShare
- YubiKey
- Desbloqueo rápido

Librerías criptográficas:
- Botan 2.19.1

**Comment by droidmonkey** [comment]
Are you sure you don't have a key depressed like shift or cmd?

**Comment by jarnaez728** [comment]
100% sure :) I can try to make a video with fake passwords if it helps

**Comment by droidmonkey** [comment]
sure that would be helpful, I cannot reproduce this at all on Windows or Mac. Make sure you enable screenshots (see the user guide) or use a snapshot build: https://snapshot.keepassxc.org

**Comment by jarnaez728** [comment]
You can see a simple video here. I think the problem appears when you have several groups created:
https://1drv.ms/v/s!AmzgzdurEbPu5P8Ui9ECTIJHID-scg?e=fd2Plm

If I search something, after double click it goes to the group but doesn't open the edit mode. However if I doubleclick a password directly, it opens directly. I'm not be able to reproduce in this new BD the "multiselection", maybe because I have only a few passwords.

**Comment by droidmonkey** [comment]
Double clicking the group column cell navigates to the group. Make sure you double click the title column cell.

**Comment by jarnaez728** [comment]
Thanks @droidmonkey  and sorry for the bug. You are right, my mistake was that sometimes I clicked on the group, but I can tell that if you click on the group, sometimes you got the group with several items selected. You can see it here:
https://1drv.ms/v/s!AmzgzdurEbPu5YF0jRXEsmTFLxmF9g?e=syT0aR
In any case it doesn't bother me because I'll click in the name (and it works as expected)
