### ISSUE TITLE
Corrupt Database (HMAC mismatch)

### ISSUE THREAD

**Issue by arthur0828** [keepassxreboot/keepassxc#8613]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
Unable to open my database, I receive the Error - "Error while reading database... If this problem reoccurs then your database maybe corrupt (HMAC mismatch)"

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Local keepassxc database working as normal
2. Open a different keepassxc database from an external drive
3. Local keepassxc database is displays corrupt/HMAC mismatch and unable to open

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Flip between different databases locally or on external drive without issues. 

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Opened a keepassxc database on my external drive and worked normally. Attempted to open my local keepassxc db after and received the error

## Context
[NOTE]: # ( Give us any additional information you may have. )
I interchangeably use MacOS and windows

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.1
Revision: 5916a8f

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS

**Comment by droidmonkey** [comment]
Make sure you are using the right password for the respective database that is opened. There is nothing we can do beyond that.

**Comment by arthur0828** [comment]
I am absolutely sure that I use the correct password, I use it everyday. I read the previous issues people had with this and attempted to fix it with the recommendations but did not work. It seems then my db has been lost.

**Comment by droidmonkey** [comment]
Opening a second database should have nothing to do with the first. I do it all the time from all locations. Are you sure that was the only sequence you did?

**Comment by arthur0828** [comment]
I do it all the time as well. Yes I am certain that is the only sequence performed.

**Comment by phoerious** [comment]
Please check that you are not accidentally adding anything to the "key file" field, unless you are actually using a key file.
