### ISSUE TITLE
Support immediate expiration of entry

### ISSUE THREAD

**Issue by karstendf** [keepassxreboot/keepassxc#862]
Hi all,

## Context
I'm using keepassX(C) for storing TANs (one entry per TAN).
Once used, I want to set them to 'expired' with current date / time.

## Expected Behavior
I can think of two relatively simple options:
- hopefully simplest: Add "now" to entry expiration presets in 'Edit entry' mask
- more handy: Add 'Expire entry now' to entry context menu

(The luxury version which I'm not really suggesting here would be to have entries marked as TANs and auto-expire them once the password is copied. For reference, the original keepass2 has a very comprehensive TAN handling in place.)

## Current Behavior
In 'Edit entry' mask, I use expiration preset 'tomorrow', then change the date by one day backwards.
That's no big issue, but if it can be simplified with small effort, it may be worth while.

**Comment by droidmonkey** [comment]
TAN refers to Transaction Authentication Number, for future reference.

Why do you even need to keep the entries around? Wouldn't simply deleting them be good enough?

**Comment by karstendf** [comment]
good question - because I want to keep track of when they've been used.. sort of mimicking the behavior of keepass2

**Comment by TheZ3ro** [comment]
By default the expiration date is set to the creation date of an entry, this will always be less then the actual time so the entry will be expired.
Just edit a non-expired entry and enable the `Expires` check without changing the date.

If you have previously changed the expiration date this obviously don't works.
I think a `Now` preset won't hurt anyone

**Comment by karstendf** [comment]
> Just edit a non-expired entry and enable the Expires check without changing the date 

Yep, that works, but then the expiration date is equal to the creation date - which doesn't help much for tracking. I guess the history would still show when the entry was changed, however I was just looking for some convenience ;-)
Would be great if you could implement a `Now` preset!

**Comment by droidmonkey** [comment]
Prefer not to implement this, expiring an entry is simple with edit, uncheck/check expiration date, save.
