### ISSUE TITLE
Installation must be a program on local hard drive error

### ISSUE THREAD

**Issue by hj-collab** [keepassxreboot/keepassxc#8622]
Hi,

I am trying to install KeePassXC 2.7.1 on Windows 11 64bit via the msi file provided. I get the following error when choosing installation path - Installation must be a program on local hard drive error.

I am able to complete the installation this way.

msiexec /i "KeePassXC-v.msi" WIXUI_DONTVALIDATEPATH="1"

What could be the cause for the same?

**Comment by droidmonkey** [comment]
you cannot "install" a program on an external /removable hard drive. Use the portable version if that is what you want to do.

**Comment by hj-collab** [comment]
@droidmonkey I am installing it on C:\ProgramFiles\KeePassXC which is the default location and not an external hdd.

**Comment by droidmonkey** [comment]
I cannot speak to this, something is wrong with your system configuration. We don't control the actions of that part of the installer... it comes "as is"
