### ISSUE TITLE
libbotan-kpxc-2-12 for Ubuntu bionic (18.04) is missing critical files

### ISSUE THREAD

**Issue by tonyb78** [keepassxreboot/keepassxc#8623]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
keepassxc won't start:
keepassxc: error while loading shared libraries: libbotan-2.so.12: cannot open shared object file: No such file or directory

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Upgrade libbotan-kpxc-2-12 to 2.19.1-1ppa1~bionic1
2. Try to start keepassxc

## Context
[NOTE]: # ( Give us any additional information you may have. )

/etc/apt/sources.list.d/phoerious-ubuntu-keepassxc-bionic.list
deb http://ppa.launchpad.net/phoerious/keepassxc/ubuntu bionic main

Problem happens ever since the following upgrade:
2022-10-23 09:57:57 upgrade libbotan-kpxc-2-12:amd64 2.12.1-1ppa5-bionic1 2.19.1-1ppa1-bionic1

The problem is caused by:
libbotan-kpxc-2-12 seems to be missing libbotan-2.so.12:

dpkg -L libbotan-kpxc-2-12
/.
/usr
/usr/share
/usr/share/doc
/usr/share/doc/libbotan-kpxc-2-12
/usr/share/doc/libbotan-kpxc-2-12/changelog.Debian.gz
/usr/share/doc/libbotan-kpxc-2-12/copyright

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.1

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux Ubuntu 18.04.6 LTS
Desktop Env: Cinnamon
Windowing System: X11

**Comment by droidmonkey** [comment]
@phoerious

**Comment by phoerious** [comment]
This is going to be fixed with 2.7.3, which will be out today. You may downgrade to the previous Botan version in the meantime.

**Comment by phoerious** [comment]
Should be fixed as soon as the Bionic build on Launchpad is done and deployed: https://launchpad.net/~phoerious/+archive/ubuntu/keepassxc/+packages
