### ISSUE TITLE
Font size of master password smaller after update

### ISSUE THREAD

**Issue by sycam0r-e** [keepassxreboot/keepassxc#8624]
## Overview
I just updated to 2.7.3 pre-release. When unlocking a database, the font size of the database password is now smaller than with 2.7.2 stable. For me, it's just a tad to small. I am aware of #6822 but I did not change my system font size on my Mac in the meantime which leads me to think it might be a change in KeepassXC that led to the different password font size? I have no clue though so happy to learn! :)

## Steps to Reproduce
N/A

## Expected Behavior
N/A

## Actual Behavior
N/A

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.3
Revision: d8483d3

Qt 5.15.6
Debugging mode is disabled.

Operating system: macOS 12.6
CPU architecture: x86_64
Kernel: darwin 21.6.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 2.19.2

**Comment by droidmonkey** [comment]
We did not change the font size of the password.

**Comment by phoerious** [comment]
It's not smaller, but it's a proportional font now, not monospace anymore. I actually don't know why, maybe a side effect of some other change?

**Comment by phoerious** [comment]
@droidmonkey I don't think you fixed this one. This here is about the master password input field.

**Comment by droidmonkey** [comment]
>  is now smaller than with 2.7.2 stable

I don't see how that is possible since we did not change anything regarding font size between these versions. I just checked using GammaRay and the font size of the master password input is 9 point on Windows (same as always).

**Comment by phoerious** [comment]
I don't know either, but I noticed it, too. The master password field font is proportional all of a sudden, which at least looks smaller.

**Comment by droidmonkey** [comment]
Ahh ok that might be the problem.

**Comment by phoerious** [comment]
Seems to be a cross-platform issue. I saw it on macOS, but I also have it on Ubuntu at least.

**Comment by vedagel** [comment]
Can confirm on macOS 12.5.1 (21G83) using KeePassXC - Version 2.7.3

**Comment by phoerious** [comment]
Since this seems to be a thing on multiple platforms, I'm closing this one in favour of #8638.
