### ISSUE TITLE
Extra characters displayed in password preview

### ISSUE THREAD

**Issue by simondeziel** [keepassxreboot/keepassxc#8627]
## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Save a password with '&' in it
2. Select the password entry and click the shut eye to display the password
3. '&' is shown as '&amp;'

## Expected Behavior

'&' should be displayed properly.

## Actual Behavior

'&' is mangled in the "global" view but shown properly when going into the password entry itself.

## Context

$ snap list keepassxc
Name       Version  Rev   Tracking       Publisher       Notes
keepassxc  2.7.2    1627  latest/stable  keepassxreboot  -

**Comment by phoerious** [comment]
Good catch. This is a display issue in the preview panel.
