### ISSUE TITLE
KepassXC 2.7.3 says three days till expires.

### ISSUE THREAD

**Issue by SuperSentient** [keepassxreboot/keepassxc#8628]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
After I updated to KeepassXC 2.7.3 after opening my KDBX file it says 3 days till expires.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Open your KDBX file it will say three days till expire.
2. Same as above.
3.Same as above. 

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
For it just to open without any contradicting messages because when I check my KDBX I don't any group or entry about expiration.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
I don't know it hasn't been three days yet.

## Context
[NOTE]: # ( Give us any additional information you may have. )
This all started with version 2.7.3

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION 2.7.3
Revision: REVISION 2.7.2

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows/Linux/macOS
Desktop Env: Gnome/KDE/XFCE/Mate/Cinnamon
Windowing System: X11/Wayland

**Comment by droidmonkey** [comment]
#8626. You can disable showing expired entries in the application settings.

**Comment by SuperSentient** [comment]
> #8626. You can disable showing expired entries in the application settings.

Thanks. :+1:
