### ISSUE TITLE
“Check for Updates” says version 2.7.3 is available, but it isn't on the website

### ISSUE THREAD

**Issue by quinncomendant** [keepassxreboot/keepassxc#8629]
## Overview
If I do an update check, it reports version 2.7.3 is available:

![IMG_6121](https://user-images.githubusercontent.com/6884276/197425058-ba7e5adf-6a5d-4679-aff7-02b342622372.jpg)

However, the latest version on the website is version 2.7.1:

![Screen Shot 2022-10-23 at 19 05 52](https://user-images.githubusercontent.com/6884276/197425077-d70a6d99-02e1-4343-b8d7-533f9a87b9fb.png)

## Context
KeePassXC - Version 2.7.1
Revision: 5916a8f

Qt 5.15.2
Debugging mode is disabled.

Operating system: macOS 12.6
CPU architecture: arm64
Kernel: darwin 21.6.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 2.19.1

**Comment by droidmonkey** [comment]
Still working on the blog post please be patient
