### ISSUE TITLE
Multiple databases open - tab names eventually become identical

### ISSUE THREAD

**Issue by lyallp** [keepassxreboot/keepassxc#8630]
## Overview
Tab title for each open database becomes the same after entering the password for each database, making identification of each database difficult (work/home)

Awesome tool, never the less. Thanks contributors !

## Steps to Reproduce
1. Open multiple databases
2. Unlock each database
3. switch between database tabs
4. Notices the tab names have become the same (happens with 2 databases, not sure if more than 2)

## Expected Behavior
Tab titles do not change, so that each open database may be quickly identifid (eg, work, home)

## Actual Behavior
Tab titles change to be the same as the first opened database. (eg, "work, work" when I expect to see "work, home")

## Context
Windows 10 HP EliteBook Laptop

KeePassXC - Version 2.7.1
Revision: 5916a8f

Qt 5.15.3
Debugging mode is disabled.

Operating system: Windows 10 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.19044

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 2.18.1

Operating System: Windows
Desktop Env: 
Windowing System:

**Comment by phoerious** [comment]
The tab shows either the file name (if the database is locked) or the database title (if the database is unlocked). You can change the title in the database settings. By default it's "Passwords" which may not be very informative if you have multiple.
