### ISSUE TITLE
> and < characters in password modified after 2.7.3 update

### ISSUE THREAD

**Issue by ghost** [keepassxreboot/keepassxc#8631]
## Overview
Since update to 2.7.3 the > symbol is shown as `&gt;` in the entry overview.

## Steps to Reproduce
1. Create new entry with > as the password
2. Select the entry and view the password (single click to select, not double click) 
3. It shows `&gt;`

## Expected Behavior
To see the actual symbol used. Happens with < as well

## Actual Behavior
It displays `&gt;`

## Debug info
KeePassXC - Version 2.7.3
Revision: d8483d3

## system
Operating System: Ubuntu
Desktop Env: default Ubuntu
Windowing System: Wayland

**Comment by phoerious** [comment]
I don't think I understand what you mean. Can you be more specific what the issue is?

**Comment by ghost** [comment]
Lol... the Github mark up changes the symbols so what I've typed doesn't make any sense.

The issue is, if you go to an entry in the overview (single click it, not double click) and you then press the view button for the password, the symbols > and < are displayed as `&gt;`and `&lt;`

If I double click the entry and then view the password, it correctly displays the > and < characters. Is this the same issue as https://github.com/keepassxreboot/keepassxc/issues/8627?

**Comment by wisjan** [comment]
I is the same issue then #8627
`>` is shown as `&gt;`
`<` is shown as `&lt;`

**Comment by phoerious** [comment]
Ah, yes, that makes more sense. It's indeed the same issue.
