### ISSUE TITLE
Special characters are inserted in the password entry.

### ISSUE THREAD

**Issue by JohnJohnson0** [keepassxreboot/keepassxc#8635]
## Overview
I use KeePassXC with Win10 64 bit.
I have noticed that under certain conditions a special character is automatically inserted at the end of the password entry.

The behaviour always occurs when a special character is entered with the Alt Gr key (e.g. @), followed by digits entered via the numeric keypad and then another special character with Alt Gr (e.g. @).

If you enter @4@ as the password, for example, @4@♦ appears in the input field. The character ♦ was added by KeePassXC.

The special character added changes depending on which numbers are between the characters inserted with Alt Gr. For example, @5@ results in @5@♣

It is important that the numbers are entered using the numeric keypad.

The problem does not always occur, but always when KeePassXC has been restarted. If the effect does not occur, KeePassXC must be closed and restarted.

## Steps to Reproduce
[NOTE]: #
1. start KeePassXC
2. Enter @4@ (the 4 with the number pad) as the password to open a database.
3. After entering the last character, KeePassXC automatically changes the PW to @4@♦

## Expected Behavior
The password entered should not change.

## Actual Behavior
Currently KeePassXC change the password as described before.

[NOTE]: # 
KeePassXC - 2.7.3
Revision: d8483d3
But the problem has existed for several versions

[NOTE]: # 
Operating System: Windows 10, 64 bit

**Comment by michaelk83** [comment]
@droidmonkey if you're thinking this is a duplicate of #8627, this sounds like a different issue. Here the extra characters are supposedly in the input field. Possibly the Alt key is not being released properly?

@JohnJohnson0 can you confirm this is in the input *edit* field, *not* in the preview? See https://keepassxc.org/docs/KeePassXC_UserGuide.html#_screenshot_security for taking a screenshot.

Are you letting go of the Alt key before using the keypad? Alt + keypad would produce characters based on their ascii code.

**Comment by droidmonkey** [comment]
It's a duplicate of a qt bug when password is hidden from view and special characters are typed.

**Comment by JohnJohnson0** [comment]
I do not think it is a duplicate of the bug described.
The problem does not only occur when the password is invisible, but also when it is entered visibly.

What's the difference between edit and preview field?

![2022-10-24 16_37_22-Window](https://user-images.githubusercontent.com/116557411/197553216-f7d93627-26f6-4018-8f46-6310a4c0ea0e.png)

**Comment by droidmonkey** [comment]
This is a Qt problem or a Windows problem either way, we don't do anything special with the input field. We also do not recommend using special characters like that in your password.

**Comment by JohnJohnson0** [comment]
The special character I use is the @ sign. From my point of view, it is common to use this for a password. In no other program where we use passwords in this way could we observe this behavior. In the past, we used the original KeePass app - it didn't have this behaviour either.

**Comment by michaelk83** [comment]
> What's the difference between edit and preview field?

Preview pane is display-only, outside of the edit form. There was another recent bug that displayed extra characters there, but it was only a formatting issue.

> In the past, we used the original KeePass app - it didn't have this behaviour either.

Original KeePass doesn't use Qt.

This is almost certainly something to do with your keyboard layout / code page / etc, and as droidmonkey said, is either a bug in Qt, or is caused by Windows (or both).

Generally speaking, when you hold Alt and type a number on the keypad, that produces a character whose ascii code matches the number that you typed on the keypad. It's possible that in your case, either the system or Qt confuses the Alt Gr key with a regular Alt key, and mishandles the input. The diamonds symbol is ascii code 4, and clubs is ascii code 5, which fits your report.

**Comment by michaelk83** [comment]
Most likely the Alt Gr key is not being released properly (either by the user, the keyboard, or the system - might be an accessibility setting?). The keypad entry is then recorded as the start of an ascii code (the weird part is that it *also* types out the number; it should either be doing one or the other, not both). When you select the @ character, that terminates the ascii code entry, and produces that extra character.
