### ISSUE TITLE
clicking on URL link no longer opens link - 2.7.3

### ISSUE THREAD

**Issue by yamoho** [keepassxreboot/keepassxc#8636]
after upgrading from 2.7.1 to 2.7.3, clicking on URL link no longer opens the link as it used to do in older versions. M1 Macbook Pro, macOS 12.6

**Comment by DGlooking** [comment]
Same URL inactive problem with new version 2.7.3. Using Windows 11 and an Intel NUC

**Comment by phoerious** [comment]
Confirm. It's a problem only in the preview panel. Double clicking the cell in the URL column still works.

**Comment by thyxNY** [comment]
On Windows10 the same problem :-(

KeePassXC - Version 2.7.3
Revision: d8483d3

Qt 5.15.6
Debugging mode is disabled.

Operating system: Windows 10 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.19044

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 2.19.1

**Comment by MatthiasSeu** [comment]
Can also confirm the problem on kubuntu  22.04.1.
Connect between Browser and Databases established without any troubles, but no url link opens up anymore.
Saved credentials worked fine, also manual requested autotype feature worked.

**Comment by tndgpp** [comment]
Bug confirmed on Debian 11 (kernel 5.10.0-19-amd64), using KeepassXC 2.7.3 AppImage. Url links do not open.

**Comment by vedagel** [comment]
Can confirm on macOS 12.5.1 (21G83) using KeePassXC - Version 2.7.3
