### ISSUE TITLE
Allow the Search field to be moved

### ISSUE THREAD

**Issue by rcnino** [keepassxreboot/keepassxc#8637]
## Summary
Hiding the toolbar is a great way to declutter the interface. Every toolbar function is available in the menus except for search. The only way to access search when the toolbar is hidden is through the keyboard shortcut. The search field should have placement options separate from the toolbar.

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )
![image](https://user-images.githubusercontent.com/55499692/197605321-d40a3174-4593-47d4-b152-28695a21ad0f.png)
![image](https://user-images.githubusercontent.com/55499692/197598711-cd55a416-01a5-4600-89d1-1cd26784deb7.png)

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
The KeePassXC UI has a lot of visual padding. The toolbar has large icons, the status bar on the bottom cannot be hidden, column headers are thick, and the content has a ~10px border. While visually appealing, usable window space is compromised and we are given limited options to declutter the space. The toolbar in particular is especially large and each of it's options just make it larger. All of this combines to reduce visible content. Since all the toolbar buttons are available in menus, hiding it is a good way to recover some space. Unfortunately, the search field is sacrificed, which also sacrifices easy access to a key function.

**Comment by droidmonkey** [comment]
As you mentioned you can use keyboard shortcut to popup search, not sure why that is a problem. You hide toolbar but still mouse click menus and not use keyboard shortcuts?

**Comment by rcnino** [comment]
@droidmonkey a mouse click can be the more convenient way to use an application, and KeePassXC is no exception. Using Ctrl+F makes the entire toolbar visible, shifting the content within the main window (which is its own annoyance). 

Edit: I'm also finding that pressing Ctrl+F doesn't focus the search field so I can begin typing. I have to click the field anyway.

**Comment by Moini** [comment]
Why is the search field now hidden by default? That's the most important part of the whole interface... 

And 'Search' is not even in the menu? WTH... 'Decluttering' interfaces is some of the worst things one can do when not doing UX studies first. Designers live somewhere with their heads in their personal workflow bubble and do not think that other people could be using other features.

**Comment by droidmonkey** [comment]
The search field is absolutely not hidden by default

**Comment by Moini** [comment]
Maybe it's a version issue? I'm on 2.7.4 and the field only appears when I press Ctrl+F, and vanishes (along with password generator and settings buttons) when I click anywhere.

**Comment by droidmonkey** [comment]
![image](https://user-images.githubusercontent.com/2809491/221093170-969cf002-9607-41ed-96ee-ae3fe2c8cb3e.png)

You hid the toolbar at some point.

**Comment by Moini** [comment]
@droidmonkey Wish that was the case:
![grafik](https://user-images.githubusercontent.com/3240233/221249220-e247bc06-4dec-43d5-b75e-3c8b3eef8d85.png)

It looks like this since I updated my Linux Mint. That update also changed the theme, as well as it reset the option to preselect a database on startup.

**Comment by droidmonkey** [comment]
Ok you need to go to application settings, scroll to the bottom, select "icons only" for what is displayed in the toolbar.

**Comment by Moini** [comment]
Thank you. That works. What a relief!

It is still quite bad UX to just hide things when the bar becomes too long. 

There are a few ways to solve this:
* the bar needs some kind of indicator that things are hidden at its end, 
* or it needs to go into the second line. 
* Edit: and it could be moved before things that are available from the menu

Additionally, it needs to be available from the menu.

Hiding search isn't acceptable UX. And not having the text isn't exactly helpful to the less experienced users. Even when the text is below the icons, or there is only text, there is no search field.

**Comment by droidmonkey** [comment]
We are limited by what we can do by Qt. We've already greatly improved the overflow of the toolbar by allowing and showing search when the keyboard shortcut is used. There is also an overflow indicator on the toolbar, for some reason it wasnt rendering on your system.

**Comment by Moini** [comment]
Mmh, bummer. So then 'moving the search field a bit to the left' in exchange for things that are less important as well as 'add search to the menu' would still be viable?
Also let me know how I can help figure out why there's no overflow indicator.

**Comment by droidmonkey** [comment]
Are you using the dark theme or classic theme? If classic, switch to dark

**Comment by Moini** [comment]
Yep, system default is Mint Y. The other theme does have double downwards pointing arrows. But I guess that shouldn't depend upon the theme?

**Comment by droidmonkey** [comment]
It does depend, that means your system theme doesn't provide appropriate styling for this ui element. That isn't on us

**Comment by MarkFreemanBDO** [comment]
In 2.75, if the toolbar is visible, search is all the way to the right so it is not visible unless I maximize the application. However, if I press Ctrl-F (whether Show Toolbar is on or not), the toolbar appears and wraps to two lines with the Search textbox active. Maybe make the toolbar wrap all the time when visible?

**Comment by droidmonkey** [comment]
You really should read this entire thread where your question is very much answered.

**Comment by droidmonkey** [comment]
This won't be implemented, thank you for the suggestions though
