### ISSUE TITLE
Windows: seemingly needless reboot request upon updating

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [keepassxreboot/keepassxc#8640]
## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1.  Have KeePassXC running.
2. Run the MSI x64 installer for the latest build.
3. See that one is told one must reboot if one continues.
4. Abort.
5. Quit KeePassXC (the program, not the installer).
6. Re-run the installer.
7. See that one is not warned of the need for a reboot.

## Expected Behavior
If the circumstance that requires the reboot is that KeePassXC is running already, then why not prompt the user to terminate the running instance?

## Actual Behavior
See 3-7 above.

## Context
KeePassXC - Version 2.7.3
Revision: d8483d3

Qt 5.15.6
Debugging mode is disabled.

Operating system: Windows 10 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.19044

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 2.19.1

**Comment by droidmonkey** [comment]
We attempt to kill the running instance but sometimes that fails. You can usually ignore that prompt and the install will proceed. This is a limitation in the msi installer sequencing.

**Comment by LinuxOnTheDesktop** [comment]
Ah. So surely it would be kind to the user to say how things are, i.e, to say (though ideally you'd make the following text both pithier and more instructive) that a running instance of KeePassXC can make the installer request a reboot.
