### ISSUE TITLE
Microsoft Store install is broken

### ISSUE THREAD

**Issue by claudio4** [keepassxreboot/keepassxc#8641]
## Overview
The install of KeepassXC through the Microsoft store fails.

## Steps to Reproduce
1.  Go to the [official KeepassXC app in the Microsoft Store](https://apps.microsoft.com/store/detail/keepassxc/XP8K2L36VP0QMB).
2. Click the "Get in Store app"
3. Press install in the MS store app
4.  The install will fail with the error code 0x80190194.

## Expected Behavior
The app should install properly.

## Actual Behavior
The app does not install.

## Context
Operating System: Windows 11

It seems like the store is trying to download the app from https://kpxcstorage.blob.core.windows.net/store/KeePassXC-2.7.1-Win64.msi, but that URL returns a 404 error. So probably is an MS error, but maybe something can be done at KeePassXC side to fix it.

**Comment by droidmonkey** [comment]
They need to approve our update, it's currently in review.
