### ISSUE TITLE
REQUEST: Hide - Searches and Tags

### ISSUE THREAD

**Issue by 0pLuS0** [keepassxreboot/keepassxc#8642]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )

Please make an option so users can hide the Search and Tags.

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )

Here's a picture as an example with Search and Tags hidden.

![KeePassXC](https://user-images.githubusercontent.com/36190223/197666418-99cd76af-7e79-4c25-9520-815d0515f5da.jpg)

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )

This is purely cosmetic, but I find it takes up some UI space, and with it hidden, it allows someone with a larger database of entries to not have to scroll through them, possibly as much. Regardless, the idea is to free up some space. 

With the size of my entries which is small, I still had to make the UI bigger, so I didn't have to scroll through my entries, because Searches and Tags was taking up a little space at the bottom.

But it still would be nice to hide this feature if someone doesn't need it, just to clean up the UI too. I personally don't use Search and Tags.

THANKS for your consideration! :)

**Comment by droidmonkey** [comment]
Just drag the divider down to the bottom of the application window.

**Comment by 0pLuS0** [comment]
Sorry for being so stupid! LOL 

THANKS
