### ISSUE TITLE
Microsoft Store Error

### ISSUE THREAD

**Issue by sebastian600** [keepassxreboot/keepassxc#8651]
## Overview
Trying to install KeePassXC via the Microsoft Store gives error 0x80190194.

## Steps to Reproduce

1. Open https://apps.microsoft.com/store/detail/keepassxc/XP8K2L36VP0QMB
2. View in Store-App
3. Try to install

## Expected Behavior
Download and install KeePassXC

## Actual Behavior
Shows error code 0x80190194

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 10 22H2

**Comment by droidmonkey** [comment]
Still waiting for Microsoft to approve the updated software.

**Comment by AbelLykens** [comment]
```
Name      Id                      Version Source
--------------------------------------------------
KeePassXC XP8K2L36VP0QMB          Unknown msstore
KeePassXC KeePassXCTeam.KeePassXC 2.7.5   winget
```
There seems to be an official one now too.
