### ISSUE TITLE
Require password change on next use on bad passwords

### ISSUE THREAD

**Issue by leonbohmann** [keepassxreboot/keepassxc#8652]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
When I first imported my database from a csv-File I had a lot of bad passwords. Of course, I want to change all of them to a better one but I don't want to do them all at once.

I propose that we can flag individual entries as expired, other than having to open them one by one and checking the expired checkmark.

**Comment by droidmonkey** [comment]
I'm not sure how we would go about controlling this without being annoying to the end user. I suggest you instead create a "changeme" tag and apply it to the entries you want to update over time. You can also use the database report feature or the weal password search to find entries that need their password changed. As presented, this feature would not be implemented. Thank you though.
