### ISSUE TITLE
After updating to version 2.7.3 it does not work in the browser.

### ISSUE THREAD

**Issue by wiktoriano** [keepassxreboot/keepassxc#8653]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
After updating to version 2.7.3 it does not work in the browser.
1. The browser is connected to the base. There are no entries to display
2. In the Windows application, other passwords are previewed (adding "amp;" characters to the password), passwords while editing the entry are ok.
Full reinstallation did not help.

The case of adding characters "amp;"
Sometimes characters are in the middle of the password, but some old passwords are displayed correctly.
The newly created entry displays correctly
Old entries will be displayed correctly if you enable colored passwords

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. 
2. 
3. 

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.3
KeePassXC-Browser - 1.8.3
Operating system: Win64
Browser: Chrome/Chromium 106.0.0.0

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 10
Desktop Env: 
Windowing System:

**Comment by droidmonkey** [comment]
The second issue is corrected already for next release. The first issue, either restart browser and/or computer to make sure you are using the correct proxy application. Run through the browser troubleshooting guide as well

**Comment by Afx373** [comment]
... regarding first point of @wiktoriano: The same behaviour with me with the same versions.

**Comment by unterd0g** [comment]
Also experiencing the same issues, even after updating the browser extension in all browsers (i.e., Firefox and Chrome).
Uninstalling 2.7.3 and reverting to 2.7.1 immediately fixed the issue.

**Comment by phoerious** [comment]
See https://github.com/keepassxreboot/keepassxc/issues/8634#issuecomment-1290490385

**Comment by unterd0g** [comment]
Big thanks to @phoerious for mentioning #8634.
The issue appears to be with Microsoft Edge "Startup boost" feature (under "System and Performance") that is locking a running instance of the proxy. After manually killing the child process under Microsoft Edge and running the 2.7.3 setup once again things appear to be working.

**Comment by wiktoriano** [comment]
> mentioning "#8634."

Oh shit, traveler from netflix :P 
Sorry i had to, i just finished the season

**Comment by wiktoriano** [comment]
The other computer asked to close the keepass-proxy during installation, the application didn't kill the keepass-proxy automatically, so I did it manually. No problems so far, except for the added characters, but I have password coloring turned on.

**Comment by Marcehs** [comment]
For those that are reading this and are still having an issue with the browser extension not maintaining a connection to the database and/or pulling credentials properly after upgrading to 2.7.3.  I tried many other fixes and nothing worked.  I tried unticking the box in settings, browser integration, advanced "Update native messaging manifest files at startup" in the program (not the extension) and now it works just fine.  For reference, I'm running Firefox on Windows 11 22H2.  It worked just fine with said box ticked.  Immediately after upgrading to 2.7.3 it started having the issue.

**Comment by RainyCityCoder** [comment]
Had issues mirroring what others here report; inability of browser extension to connect with database after update. I tried fixing the issue via re-installs of KeePassXC and the extension, and nothing. I then installed KeePassXC 2.6.6 and that doesn't work either. For both versions, the extension's "Connect" button in the extension's "Settings" > "Connected Databases" screen simply isn't working for me.

**Comment by wiktoriano** [comment]
@RainyCityCoder kill keepassxc-proxy.exe and try to reconnect

**Comment by Afx373** [comment]
... nothing worked for me, so I uninstalled 2.7.3 and installed the previous version 2.7.1 and now the communication between application and browser extension works; OS: Win10 (20H2), Chromium-Browser 106.0.0.0, KeePassXC Browser extension 1.8.3.

**Comment by RainyCityCoder** [comment]
Ok I got it working with 2.6.6. Steps (as best I can remember): 
1) uninstall KeePassXC
2) restart
3) install KeePassXC 2.6.6 (`sudo snap install keepassxc --candidate`)
4) enable browser integration
5) run "KeePassXC-Browser Helper Script" under the " Snap Package" heading on this page: https://keepassxc.org/download/#linux
6) restart browser
7) connect extension to database
8) test

**Comment by Marcehs** [comment]
Started having issues again, uninstalled 2.7.3, restarted, installed 2.7.1, working just fine now.  Firefox, Windows 11 22H2, not using MS store version.
