### ISSUE TITLE
Setting a Custom Browser configuration location presents the org.keepassxc.keepassxc_browser.json file as the database

### ISSUE THREAD

**Issue by neildarlow** [keepassxreboot/keepassxc#8655]
## Overview
After updating to KeePassXC-2.7.3 it was necessary to set a Custom Browser configuration location for Firefox.
KeePassXC suggests ~/.config/mozilla/native-messaging-hosts which I had to change to ~/.mozilla/native-messaging-hosts.
On restarting KeePassXC my existing database (~/KeePassXC.kdbx) is replaced by the full path to org.keepassxc.keepassxc_browser.json.

## Steps to Reproduce
1. Update KeePassXC-2.7.1 to KeePassXC-2.7.3 (Flatpak version)
2. Note that KeePassXC cannot connect to your database
3. Set a Custom Browser configuration location to fix (2) - I used ~/.mozilla/native-messaging-hosts
4. Quit KeePassXC and launch it again
5. Your existing KeePassXC database choice has been replaced with the full path to org.keepassxc.keepassxc_browser.json
6. Clear the Recent Databases entry and open your existing database successfully
7. Close the database, Quit KeePassXC then launch it again
8. A tab is presented for your existing database and another tab for the org.keepassxc.kaapassxc_browser.json file in the configured Custom Browser configuration location directory

## Expected Behavior
Setting a Custom Browser configuration location should not affect any existing Database choice and should not present a configuration file as a Database.

## Actual Behavior
Setting a Custom Browser configuration of e.g. ~/.mozilla/native-messaging-hosts presents ~/.mozilla/native-messaging-hosts/org.keepassxc.keepassxc_browser.json as the previously selected database

## Context
fedora 37 Silverblue edition
Firefox-105.0.1 installed in base OS image as RPM

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.3
Revision: d8483d3
Distribution: Flatpak

Qt 5.15.6
Debugging mode is disabled.

Operating system: KDE Flatpak runtime
CPU architecture: x86_64
Kernel: linux 5.19.15-301.fc37.x86_64

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey

Cryptographic libraries:
- Botan 2.19.1
- 
[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: Gnome
Windowing System: Wayland

**Comment by droidmonkey** [comment]
I don't understand what is happening to you at all, screenshot please

**Comment by neildarlow** [comment]
OK, I can't reproduce entirely what I described earlier but there's enough to show something is amiss.

Context:
1) I have a KeePassXC database in my home directory named KeePassXC.kdbx
2) My Firefox installation puts the KeePassXC native-messaging configuration in .mozilla/native-messaging-hosts/

Screenshot 1: What KeePassXC has as default (non-custom) native-messaging configuration
![01-proposed-custom-browser-config-location](https://user-images.githubusercontent.com/6245505/197826073-ba683edd-dd04-4727-819c-8b511766bcf5.png)

Screenshot 2: Custom native-messaging directory required for Firefox to communicate with KeePassXC
![02-required-custom-browser-config-location](https://user-images.githubusercontent.com/6245505/197826399-09d68705-7ab4-4953-b76b-0e95c89cddeb.png)

Screenshot 3: No existing database (from recents) so Open existing database selected - Notice proposed database path!
![03-open-existing-database-clicked](https://user-images.githubusercontent.com/6245505/197826901-317a4e54-927c-4f01-a1f9-40863e5ead38.png)

Screenshot 4: Navigate away from the presented database path and select the existing database
![04-navigate-and-select-existing-database](https://user-images.githubusercontent.com/6245505/197827185-2257dbed-bfe0-494b-a8b5-a8be7877d60b.png)

**Comment by neildarlow** [comment]
And managed to recreate full problem. Manifested when Firefox launches KeePassXC during its startup.
![erroneous-keepassxc-database](https://user-images.githubusercontent.com/6245505/197842997-345701eb-1462-4893-979f-656604abb9fb.png)

**Comment by varjolintu** [comment]
@neildarlow Firefox launches KeePassXC..? This sounds like a bug in the Flatpak package. It should start the proxy instead and not the KeePassXC itself. Maybe the Custom Browser feature is not working properly with the Flatpak.

**Comment by neildarlow** [comment]
Maybe I'm confused by terminology here. How does the KeePassXC Proxy differ from the KeyPassXC you would launch from a Desktop or Panel launcher icon?

To me the visuals are the same. If I launch KeePassXC from the Desktop/Panel I am able to select a previously existing database from the recents and then enter the password to unlock it.

Similarly, if I start Firefox without having previously launched KeePassXC the effect is to present the same dialog to select the database and provide the password to unlock it.

If the second behaviour is incorrect then it is what the Flatpak version of KeePassXC has always done in all the time I have been using it.

**Comment by droidmonkey** [comment]
See https://github.com/flathub/org.keepassxc.KeePassXC/issues/94

**Comment by neildarlow** [comment]
Hi @droidmonkey,

Yes, I just saw that you had reported this. So, it has always exhibited this behaviour. The problems I describe in this issue have only shown themselves with KeePassXC-2.7.3 and the need for me to specify a Custom Browser Configuration location which, I believe, came about from a change in this release.

My question, I guess, is my bug report in any way valid? As a workaround I just have to make sure that I insert my YubiKey and launch KeePassXC to unlock the database before I start Firefox - which is a bit tedious.

**Comment by neildarlow** [comment]
Thank you for this @droidmonkey. The solution is very elegant and works well.
