### ISSUE TITLE
Password view showing incorrect when it has quote and ampersand

### ISSUE THREAD

**Issue by joechittick** [keepassxreboot/keepassxc#8657]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
Password view showing incorrect when it has quote and ampersand

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Password has a quote and ampersand in it
2. Click the button to view the password with the quote and ampersand

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
The password should show correctly. For example if the password is `12345"&6789`, it should show that, not `12345&quot;&amp;6789`

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
When previewing the password, instead of showing `"&`, it shows `&quot;&amp;`

## Context
[NOTE]: # ( Give us any additional information you may have. )
When opening up the record with the password, it does show correct. I only learned that after resetting my Firefox sync password and losing my data :(

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.3
Revision: d8483d3

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 10 21H2
Desktop Env: NA
Windowing System: NA

**Comment by joechittick** [comment]
This is also happening for `>`, it shows `&gt;`.

Possibly others, but I assume the issue is related.

**Comment by droidmonkey** [comment]
We have fixed this for the next release already, but your actions indicate you are using the application in a very awkward way.

> I only learned that after resetting my Firefox sync password and losing my data

You _should be_ using Auto-Type, browser integration, or worst case the copy to clipboard feature (Ctrl+C or toolbar icon). Manually copying the preview password is generally NOT recommended. It doesn't allow the clipboard clearing to work and display errors like this cause you to fail.

**Comment by joechittick** [comment]
I'm new to the software, which is great, so still learning all the best practices. Thanks!

**Comment by droidmonkey** [comment]
No worries, recommend reading our user guide: https://keepassxc.org/docs/KeePassXC_UserGuide.html
