### ISSUE TITLE
KeePassHTTP is not running error

### ISSUE THREAD

**Issue by chiefolaf** [keepassxreboot/keepassxc#866]
## Expected Behavior
Some sort of auto/one-click log in to a website.  Novice here, apologies.

## Current Behavior
When visiting a website I get the above error, despite enabling KeePassHTTP server in the KeePassXC options.
From KeepPassHttp's install it looks like that within KeePassXC, there should be an option 'tools -> keepasshttp options' but I don't see that.

## Possible Solution
Is it to do with where I store the 'KeePassHttp.plgx' file?  Their install instructions say it should be in /usr/lib/KeePass2, but this doesn't exist (and doesn't change anything if I create it).
Is this in turn to do with how .AppImage files work?  Not familiar enough with the filesystem layout yet.

## Context
New to KeepassXC, first time trying a password manager

## Debug Info
KeePassXC - Version 2.2.0
Libraries:
- Qt 5.9.0
- libgcrypt 1.6.1

Operating system: Ubuntu 16.04 LTS
CPU architecture: x86_64
Kernel: linux 4.4.0-21-generic

Enabled extensions:
- KeePassHTTP
- Auto-Type
- YubiKey

**Comment by phoerious** [comment]
You don't need the plgx file. That one is for KeePass2, not for KeePassXC. The only thing you need to do is enable it in the settings (Tools->Settings->Browser Integration).
If that isn't working, make sure the port configured in the KeePassXC and the browser plugin settings is the same and nothing else is running which blocks the port.

**Comment by chiefolaf** [comment]
Thanks for the quick reply - it's led to the problem.
I had that enabled, however FoxyProxy connecting to my VPN seems to interfere.  It's set up to also connect via localhost but on a different port.  Switching off the proxy and things work as they should.

Now to try and work out why that is... I know that's out with this forum but any pointers welcomed!

**Comment by phoerious** [comment]
KeePassXC exposes its HTTP API only over localhost. You cannot use it over any sort of non-local network, because that would allow an attacker to snoop your passwords
