### ISSUE TITLE
KeePassXC hangs forever if the last opened DB was on a network share and is currently offline.

### ISSUE THREAD

**Issue by alanalvarado** [keepassxreboot/keepassxc#8661]
## Overview
KeepassXC hangs forever if a network location with a previously opened DB is no longer available or offline.

## Steps to Reproduce
1. Open a database located in a network share
2. Close the DB and close keepassxc
3. turn off the computer containing the database or unmount the network location
4. Open keepassxc

## Expected Behavior
Simply forget the last database, or show it as currently offline.

## Actual Behavior
KeepassXC Hangs forever trying to find the offline database, and no matter if you try to open keepassxc by double clicking another database directly in the file explorer it hangs the same.
The only way to make keepassxc work again is to delete the preferences.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.3 but noticed it also in 2.7.1

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 11 22H2

**Comment by phoerious** [comment]
For POSIX file systems, this is somewhat of the expected behaviour at least if the share is still available but offline. For Windows shares, I believe there should be a timeout. Strange that it hangs forever.

**Comment by droidmonkey** [comment]
I would think this would be a Qt bug considering all file operations go through them. I could not replicate this at all, however:

![image](https://user-images.githubusercontent.com/2809491/203848536-9e70df62-fb43-4eba-ba9c-5265d7de9101.png)

I had disconnected my Z: network share before opening KeePassXC and it behaved as expected.
