### ISSUE TITLE
Change 'Entry(s)' text on the status bar

### ISSUE THREAD

**Issue by nvllz** [keepassxreboot/keepassxc#8662]
'Entry(s)' displayed on the status bar is gramatically incorrect. So let's make it either dynamic or static in other form:
- _0 entries_, _1 entry_, _2 entries_
- _Entries: 0_, _Entries: 1_, _Entries: 2_

With a dynamic style I mean 'if number is 1 display _entry_, else display _entries_'. Static style is all about displaying leading text before the number of entries always in plural form. Personally I think that in some languages it'd be easier to go with a static style.

**Comment by droidmonkey** [comment]
This is just a translation problem, will be fixed in transifex.
