### ISSUE TITLE
PGP signatures used to sign 2.7.3 don't match the published signatures

### ISSUE THREAD

**Issue by MaddyKakkouHeart** [keepassxreboot/keepassxc#8664]
## Summary
As the title implies, the Win64 MSI for 2.7.3 is signed by keys that are not published on the website.
https://keepassxc.org/keepassxc_master_signing_key.asc
https://keepassxc.org/verifying-signatures/

## Context
Security concerns

**Comment by phoerious** [comment]
The MSI is signed by a sub key of the published key. If you trust the main key, the sub key will also be trusted.
