### ISSUE TITLE
Password in previewpanel uses html encoding for angled brackets

### ISSUE THREAD

**Issue by hjtbuitenhuis** [keepassxreboot/keepassxc#8666]
## Overview
When viewing the password by clicking on the eye icon in the preview panel, the characters `<` and `>` get replaced with `&lt;` and `&gt;`, which is the html encoded form of those characters.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Create a password with characters `<` and `>` 
2. Click eye icon in preview pane
3. See that it shows the html encoding.

## Expected Behavior
The characters themselves ( `<` and `>`) should show.

## Actual Behavior
The html encoded characters are shown ( `&lt;` and `&gt;`)

## Context
Using version 2.7.3

KeePassXC - Version 2.7.3
Revision: d8483d3

Qt 5.15.6
Debugging mode is disabled.

Operating system: Windows 10 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.19044

Operating System: Windows

**Comment by phoerious** [comment]
Duplicate of #8627.
