### ISSUE TITLE
Edge Extention not working correctly after update to 2.7.3

### ISSUE THREAD

**Issue by MarioMan632** [keepassxreboot/keepassxc#8667]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Unlock Database
2. Normally issue starts right away but or after a short amount if inactivity

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
The extenton connects to the Database and allow autofill and dropdown selection of login for sites with multiple logins.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
After unlocking the database the extention shows it is connected to the Database and the icons on the login fields show green but when I click to autofill or show the dropdown of logins it goes grey and will not respond but the extention in the list still shows it is connected to the database. When I refresh the page the the icon goes green again but will repeat the same behavour. 
To fix this I have to reload the Extention as well as quit and reopen KeePassXC but this does not work most of the time and I have to do this multiple time to have it work for maybe a few logins or a few minuites. 

## Context
[NOTE]: # ( Give us any additional information you may have. )
Downgrading back to 2.7.1 causes the issue to not occur. 

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.3 
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 10 Pro 21H2

**Comment by phoerious** [comment]
See #8634.
