### ISSUE TITLE
flatpak: Enabling autolaunch does not work

### ISSUE THREAD

**Issue by andreashuber69** [keepassxreboot/keepassxc#8668]
## Overview
Checking **Automatically launch KeePassXC at system startup** writes a .desktop file in the wrong location. Consequently, the application does not launch automatically.

## Steps to Reproduce
1. Check **Automatically launch KeePassXC at system startup** in **Basic Settings** and click **OK**:
   ![Screenshot from 2022-10-26 10-57-44](https://user-images.githubusercontent.com/7470215/197984036-431835db-9bfe-4645-8d0e-37a615973f84.png)
2. Close the application, restart the system and login again.

## Expected Behavior
The application launches automatically after login. This could be achieved with an appropriate .desktop being created in *~/.config/autostart*.

## Actual Behavior
The application does not launch automatically after login. Apparently, enabling autolaunch creates the file *~/.var/app/org.keepassxc.KeePassXC/config/autostart/org.keepassxc.KeePassXC.desktop*, which does not trigger autolaunch on my machine.

[NOTE]: # ( Pick choices based on your environment )
Operating System: PureOS 10
Desktop Env: Gnome

**Comment by 6XGate** [comment]
A year later and it still doesn't work. But, if you are using GNOME and you have GNOME Tweaks installed; just add it via the Startup Applications.

**Comment by droidmonkey** [comment]
Open to a PR...

**Comment by michas79de** [comment]
> ## Overview
> 
> Checking **Automatically launch KeePassXC at system startup** writes a .desktop file in the wrong location. Consequently, the application does not launch automatically.
> ## Steps to Reproduce
> 
>     1. Check **Automatically launch KeePassXC at system startup** in **Basic Settings** and click **OK**:
>        ![Screenshot from 2022-10-26 10-57-44](https://user-images.githubusercontent.com/7470215/197984036-431835db-9bfe-4645-8d0e-37a615973f84.png)
> 
>     2. Close the application, restart the system and login again.
> 
> 
> ## Expected Behavior
> 
> The application launches automatically after login. This could be achieved with an appropriate .desktop being created in _~/.config/autostart_.
> ## Actual Behavior
> 
> The application does not launch automatically after login. Apparently, enabling autolaunch creates the file _~/.var/app/org.keepassxc.KeePassXC/config/autostart/org.keepassxc.KeePassXC.desktop_, which does not trigger autolaunch on my machine.
> 
> Operating System: PureOS 10 Desktop Env: Gnome

I have the same issue but on another system:

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.6
Revision: dd21def
Distribution: Flatpak

Qt 5.15.10
Diagnosemodus ist deaktiviert.

Betriebssystem: KDE Flatpak runtime
CPU-Architektur: x86_64
Kernel: linux 6.5.0-17-generic

Aktivierte Erweiterungen:
- Auto-Type
- Browser-Integration
- SSH-Agent
- KeeShare
- YubiKey
- Secret-Service-Integration

Kryptographische Bibliotheken:
- Botan 3.2.0


[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux Ubuntu 22.04.3 LTS
Desktop Env: Gnome 42.9
Windowing System: X11
