### ISSUE TITLE
Attachments won't open on AppImage

### ISSUE THREAD

**Issue by nohing** [keepassxreboot/keepassxc#8669]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

Hello!
Attachments do not work anymore with the new release KeePassXC 2.7.3
With the old KeePassXC 2.7.1 I added some attachments to some entries. But with the new release I cannot access to those attachments anymore, I cannot open them.
Can you fix it?

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

I expect that when I click open, the attachment opens

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

With the new release KeePassXC 2.7.3, when I try to open the attachment nothing happens, not even an error message, nothing.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.3
Revision: d8483d3
Distribution: AppImage

Qt 5.15.2
Debugging mode is disabled.

Operating system: Linux Mint 20.3
CPU architecture: x86_64
Kernel: linux 5.4.0-131-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.19.1

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: Cinnamon

**Comment by droidmonkey** [comment]
#8644 fixes this

**Comment by droidmonkey** [comment]
Actually this is not broken at all... make sure you have an appropriate application registered to open the attachment file type or save them to disk.

**Comment by nohing** [comment]
I don't understand... what should I do?

**Comment by nohing** [comment]
I have an appropriate application registered to open the attachments, because I do open them with KeePassXC 2.7.1, but the problem is that I can't open with KeePassXC 2.7.3

**Comment by droidmonkey** [comment]
I just opened attachments in 2.7.3, please provide a screenshot of where in the application you are encountering this issue

**Comment by nohing** [comment]
![Attachment_issue_KPXC_2_7_3](https://user-images.githubusercontent.com/36953233/198022202-fe1a9a53-484a-400c-9380-de68ffab27bf.png)

When I click Open, nothing happens.

**Comment by phoerious** [comment]
What happens if you create a text file on your hard disk and run
```xdg-open filename.txt```
?

**Comment by nohing** [comment]
It works, it opens the file.

**Comment by droidmonkey** [comment]
This might be an appimage specific problem

**Comment by nohing** [comment]
Is there a way to fix it?

**Comment by droidmonkey** [comment]
Try using out flatpak or ppa instead of appimage. Or downgrade back to 2.7.1.

**Comment by rislah** [comment]
same problem on flatpak

**Comment by droidmonkey** [comment]
Works fine on Flatpak:
![image](https://user-images.githubusercontent.com/2809491/198268990-d802569f-ec71-4db7-81ff-59c12c1e526d.png)

**Comment by rislah** [comment]
How can I help you debug this? It doesn't do anything for me, however xdg-open in terminal opens up editor no problem

**Comment by rislah** [comment]
Compiled from source has no problems. Everything works.

AppImage prints this to the terminal: `/usr/local/bin/emacs: symbol lookup error: /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0: undefined symbol: g_uri_ref`

Flatpak has no errors, but I'm guessing it's related to the above.

```
libglib2.0-0/unstable,now 2.74.1-1 amd64 [installed,automatic]
libglib2.0-bin/unstable,now 2.74.1-1 amd64 [installed,automatic]
libglib2.0-data/unstable,now 2.74.1-1 all [installed,automatic]
libglib2.0-dev-bin/unstable,now 2.74.1-1 amd64 [installed,automatic]
libglib2.0-dev/unstable,now 2.74.1-1 amd64 [installed,automatic]
```
```
lrwxrwxrwx 1 root root     19 Oct 25 22:38 /usr/lib/x86_64-linux-gnu/libgobject-2.0.so -> libgobject-2.0.so.0
lrwxrwxrwx 1 root root     26 Oct 25 22:38 /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0 -> libgobject-2.0.so.0.7400.1
-rw-r--r-- 1 root root 391384 Oct 25 22:38 /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.7400.1

```

**Comment by phoerious** [comment]
The error message indicates that you are trying to open a file in emacs, but Emacs crashes due to an incompatible dynamic library version. This is not an error in KeePassXC, but in your Emacs installation.

**Comment by rislah** [comment]
There is not any problems in my Emacs installation. When I compile KeePassXC myself, everything is OK.

**Comment by phoerious** [comment]
The error is thrown by your emacs, not by us. Try changing your file type association to a different editor.

**Comment by rislah** [comment]
```
XPCOMGlueLoad error for file /usr/lib/firefox/libmozgtk.so:
/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0: undefined symbol: g_uri_ref
Couldn't load XPCOM.
```

This is Firefox handling mimetype text/plain. It throws this error with every GTK applications.

No problem with xdg-open or KeePassXC compiled from src. Problem related to AppImage/Flatpak

**Comment by phoerious** [comment]
Alright, I can reproduce it with the AppImage, but the error is a missing  "x-scheme-handler/file". This is a bug either in Qt or the system MIME handling, nothing we can fix. As a workaround, you can add a file:// schema handler to ~/.config/mimeapps.list: https://bugs.kde.org/show_bug.cgi?id=442721

**Comment by mat-twg** [comment]
Attachments not opening in `2.7.5` on `ubuntu 22.04` (my old version `2.0.3` works fine, also `xdg-open` works fine)
