### ISSUE TITLE
Allow quick unlock by hardware key only

### ISSUE THREAD

**Issue by Animadei** [keepassxreboot/keepassxc#8670]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
Want a configurable feature to use either the Hardware Key XOR Windows Hello for the quick unlock feature.

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )
N/A

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
Requiring Windows Hello on top of a Hardware Key doesn't actually increase the system security but statistically significantly increases user stress levels after having to enter long Windows login passwords instead of using a single touch after every unlock.

**Comment by Animadei** [comment]
If the concern is that you no longer want to store data in unprotected user space memory then run CreateProcess() with CREATE_SECURE_PROCESS. This is pointless because unless the web browser's auto-fill is completely within a secure partition as well the system isn't secure. Malware can always wait until the database is unlocked to grab everything off the database in a split second. For now assume user space code running in non-admin mode won't be reading memory off of another process and make the user experience easier for everyone.

https://github.com/keepassxreboot/keepassxc/blob/e180980b90779459e64136dd215101396efb99e7/src/gui/DatabaseOpenWidget.cpp

**Comment by droidmonkey** [comment]
If you use hardware key then that is basically your quick unlock. Just add a shorter password as your PIN. You can disable quick unlock in settings.

**Comment by Animadei** [comment]
> If you use hardware key then that is basically your quick unlock. Just add a shorter password as your PIN. You can disable quick unlock in settings.

This suggestion reduces the security of the Windows machine for increasing the convenience of the password manager's quick unlock feature. Does that really make sense to you when you read it over? It doesn't to me. You've prematurely closed the issue without addressing the actual problem. The community deserves a better response.

**Comment by Animadei** [comment]
Related request:
https://github.com/keepassxreboot/keepassxc/issues/8051

**Comment by droidmonkey** [comment]
Not the password to your computer, the password for your database....

Pin password + Hardware key is extremely secure. You need your token (something you have) and you need a pin (something you know) and it doesn't require the quick unlock feature at all.

**Comment by Animadei** [comment]
> Not the password to your computer, the password for your database....
> 
> Pin password + Hardware key is extremely secure. You need your token (something you have) and you need a pin (something you know) and it doesn't require the quick unlock feature at all.

Please allow the PIN requirement to be removed for quick unlock. Want a hardware key tap.

Quick unlock won't even work without first logging in with the database password and hardware key tap anyway.

**Comment by Animadei** [comment]
It doesn't make sense we're using Windows Hello AND hardware key at the same time. Windows Hello uses the on-board TPM 2.0 and is fundamentally not any more secure than a hardware key. As far as anyone should be concerned the hardware key security is good enough. The button press indicates user presence and the same connected hardware key previously used to first co-unlock the database.

Side note: Intel's Boot Guard is broken anyway. If anyone wants to place the OS under an attacker controlled KVM then there's nothing Windows nor Linux can do to run without being monitored, and thus even the Windows user isolation mode remains broken as a consequence of not having an end-to-end security (https://twitter.com/_markel___/status/1578771873508519936). This should be eventually fixed.

**Comment by droidmonkey** [comment]
Disable quick unlock in the application security settings....
