### ISSUE TITLE
Copying passwords from main interface copies Ampersand (&) as &amp;

### ISSUE THREAD

**Issue by ramenspazz** [keepassxreboot/keepassxc#8671]
## Overview
copying passwords from the main interface results in Ampersands (&) being copied as ```&amp;```

## Steps to Reproduce
Update to the current version of KeePassXC (as of 26th of October, 2022).

## Expected Behavior
copying passwords from the main user interface results in the correct password copied

## Actual Behavior
copies Ampersand (&) as ```&amp;```

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.3
Revision: d8483d3

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux, Fedora 36
Desktop Env: Gnome
Windowing System: Wayland

**Comment by phoerious** [comment]
#8633
