### ISSUE TITLE
Usernames hidden by default : create setting option to disable this behavior

### ISSUE THREAD

**Issue by ramenspazz** [keepassxreboot/keepassxc#8672]
## Summary
Usernames hidden by default in 2.7.3 rev. d8483d3. Create a settings option for disabling this behavior, or it if already exists, move this item to the privacy settings tab.

## Context
Hiding usernames doesn't seem necessary and there appears to be no obvious way in settings to disable this behavior. Making this behavior optional makes more sense to me, therefore adding a new menu item in privacy to toggle this behavior should be implemented, or the current item controlling this added to the privacy tab in settings if it already exists.

**Comment by droidmonkey** [comment]
It is not the default. Go to View -> Hide usernames to unset this setting.
