### ISSUE TITLE
Ampersand in password is displayed in preview window as '&amp;' instead of '&'

### ISSUE THREAD

**Issue by AGatGitHub** [keepassxreboot/keepassxc#8673]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
See title

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Create an entry
2. Enter a password with an ampersand in it
3. Save the entry and click on the eye icon in the preview window to display the password
4. Password has a **& amp ;** string instead of **&**

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
See the password with the **&** in it

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
The password shows **& amp ;** instead of **&**

## Context
[NOTE]: # ( Give us any additional information you may have. )
By the way, if I type **& amp ;** without spaces between the characters, it is also changed to **&** in this GitHub post.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.3
Revision: d8483d3

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 10 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.19044

**Comment by phoerious** [comment]
#8633
