### ISSUE TITLE
Changing an expired password does not reset the expiry flag

### ISSUE THREAD

**Issue by sha-e-256** [keepassxreboot/keepassxc#8675]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
Changing a password that has expired does not reset the expiry flag; in other words, if a password expires on Oct 25, and I change it to a new password on Oct 26, the entry's "Expiration" date will still say Oct 25 and the entry will remain crossed out. This is confusing because it becomes easy to lose track of if you recently changed the password; in other words, it looks like I still need to change my password, even If I just recently changed it.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Set an expiry date in the "Edit entry" tab.
2. Allow the password to expire.
3. Change the password after the expiry date.
4. View the Expiration date of the password; in addition, the entry will still be crossed out. 

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
If I change the expired password, the expiry flag should clear and the entry shouldn't be crossed out. 

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
If I change the expired password, the entry is still crossed out and it seems like the password is still expired and needs to be changed.

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC : Version 2.7.3
Revision: d8483d3
Distribution: Flatpak

[NOTE]: # ( Pick choices based on your environment )
Operating System: Fedora Linux 36
Desktop Environment: GNOME Shell 42.5

**Comment by droidmonkey** [comment]
How do we know what to set the new expiration to? When you change the password you should set the new expiration. That is up to the user. 

Also #6456
