### ISSUE TITLE
Keypass 2.7.3 crashes after entering a password on a Mac

### ISSUE THREAD

**Issue by Spremse** [keepassxreboot/keepassxc#8678]
## Overview
Keypass 2.7.3 crashes after entering a password on a Mac (MacMini 12.6.1)

## Steps to Reproduce
[After updating to 2.7.3 on my Mac Mini (Monterey 12.6.1) Keypassxc crashes immediately after entering the password

KeePassXC - 2.7.3
Mac - MacMini with Monterey 12.6.1

**Comment by droidmonkey** [comment]
Disable quick unlock for now,  we have a fix for next version

**Comment by spolti** [comment]
just for info: this is the PR https://github.com/keepassxreboot/keepassxc/pull/8676

**Comment by spolti** [comment]
hi @droidmonkey thanks for providing the fix, one question do you know when the next release with the fix will be available?

Thanks.

**Comment by droidmonkey** [comment]
This weekend
