### ISSUE TITLE
[Feature Request] Make it harder to skip updates

### ISSUE THREAD

**Issue by jakubiakdev** [keepassxreboot/keepassxc#8681]
## Summary
Currently, it is way to easy to skip an update. When you are trying to log into a website - you don't want to be slowed down to wait for an update, but you probably want to login as fast as possible. This makes skipping important security updates way to easy, as you instinctively close any pop up to get to your "destination" - to enter the password to the website. Afterwards you may forget to update the installation, etc.

My proposition is by making the prompt to update appear on close - would solve this issue, as you're more likely to actually do something when there is nothing important in the way. It could be also delayed, but I think these are pretty primitive options so I would like to know what others think 

## Context
This design makes skipping updates way too easy resulting in outdated installations

**Comment by phoerious** [comment]
We cannot really force users to upgrade and security updates are very rare (we haven't had any so far). Therefore I don't think we will even try. But thanks for the suggestion.
