### ISSUE TITLE
expired signature on mac download

### ISSUE THREAD

**Issue by davidb44** [keepassxreboot/keepassxc#8682]
Can you fix this? Thank you.. 
https://keepassxc.org/download/

Expired signature
KeePassXC Release <[release@keepassxc.org](mailto:release@keepassxc.org)>
C1E4 CBA3 AD78 D3AF D894  F9E0 B7A6 6F03 B590 76A8

The key which was used to sign this message is expired.

You can try to refresh the key with ID C1E4 CBA3 AD78 D3AF D894  F9E0 B7A6 6F03 B590 76A8 in GPG Keychain and ask the sender why the key is expired.

## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. 
2. 
3. 

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows/Linux/macOS
Desktop Env: Gnome/KDE/XFCE/Mate/Cinnamon
Windowing System: X11/Wayland

**Comment by droidmonkey** [comment]
Refresh your key list
