### ISSUE TITLE
able to uncheck key file location

### ISSUE THREAD

**Issue by Hamybal** [keepassxreboot/keepassxc#8683]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )

I'm not completely seeing the use of a key file if it remembers its location.

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )

Could there be somewhere in the settings a checkbox to enable/disable seeing the file location.

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )

Well if somehow i got hacked and they can move around in my pc then i don't won't to hand my key file on a silver platter.

If this is is already feature than sorry but I've skimmed through the settings twice and i don't see that option with the latest version.
Thank you for your time, this program has really made it a lot easier to manage this all.

**Comment by droidmonkey** [comment]
It's at the top of the application settings. Uncheck "Remember key file locations"
