### ISSUE TITLE
2.7.3 Apple Silicon Crashing

### ISSUE THREAD

**Issue by zard2004** [keepassxreboot/keepassxc#8688]
I created a database from Apple Silicon version.  After closing it, relaunch KeepassXc 2.7.3, open database, provided password, Keepass 2.7.3 crashes.  Tried Intel version as well, same crash happens.

I created another database from Windows version, no issue to reopen.  With the same database, it still crashes with Silicon and Intel 2.7.3 version.

I am a new user, so don't have older to test.

**Comment by varjolintu** [comment]
Already fixed https://github.com/keepassxreboot/keepassxc/pull/8676.
