### ISSUE TITLE
New Versions not compatible with older OS verions

### ISSUE THREAD

**Issue by DriesMoo** [keepassxreboot/keepassxc#8689]
## Summary
[TIP]:  # Have the guarantee that newer releases of keepassXC don't let users with older OS get left behind security wise.

## Context
[NOTE]: #  I use MacOS Mojave 10.14.6 (due me running some older apps that don't get updated and several ui problems with newer versions) and updating would render keepassxc useless. I am slightly concerned that in the future users with older OS will run behind security wise.

**Comment by droidmonkey** [comment]
https://endoflife.date/macos

> users with older OS get left behind security wise

100% correct which is why you need to update your OS. The security issue is definitely NOT with keepassxc.

**Comment by DriesMoo** [comment]
Well sucks for us...
Not all 32 bit app are being updated

**Comment by droidmonkey** [comment]
That is because 32 bit apps should have stopped existing 5 years ago. We are finally seeing that happen now.

**Comment by phoerious** [comment]
The minimum supported version has been 10.15 since 2.7.0. The fact that 2.7.1 still used to work with older versions is purely coincidental.
