### ISSUE TITLE
[MacOS] do not quit keepassxc when the main windows is closed

### ISSUE THREAD

**Issue by gagarine** [keepassxreboot/keepassxc#869]
If I close the main keepassxc windowd, keepassxc quit.

This is a standard behaviour on Windows/Linux but not on Mac. The application should stay active and only the windows should be "hidden".

## Expected Behavior
1) Click on the x (close) button on the windows
2) the windows should close but the application should stay active.

## Current Behavior
1) Click on the x (close) button on the windows
2) The application quit.

**Comment by sainaen** [comment]
This a duplicate of #795 (see also #438, #498 and #583 for previous discussions.)
