### ISSUE TITLE
Clicking URLs does nothing in 2.7.3 AppImage

### ISSUE THREAD

**Issue by vphantom** [keepassxreboot/keepassxc#8690]
## Overview
Here's an odd one: since upgrading from 2.7.1 to 2.7.3 I must now copy URLs and paste them in a new browser tab manually; clicking them does nothing.

## Steps to Reproduce
1. Launch AppImage 2.7.3
2. Select an entry
3. Click the URL

## Expected Behavior
I expect my browser window to take focus and for a new tab to open the URL I clicked.

## Actual Behavior
Nothing happens.  I see nothing about it on the `stdout`/`stderr` either.

### Reproducing the issue with:
KeePassXC - Version 2.7.3
Revision: d8483d3
Distribution: AppImage

Qt 5.15.2
Debugging mode is disabled.

Operating system: Debian GNU/Linux 10 (buster)
CPU architecture: x86_64
Kernel: linux 4.16.0-0.bpo.2-amd64

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.19.1

### Getting normal behavior with:
KeePassXC - Version 2.7.1
Revision: 5916a8f
Distribution: AppImage

Qt 5.15.2
Debugging mode is disabled.

Operating system: Debian GNU/Linux 10 (buster)
CPU architecture: x86_64
Kernel: linux 4.16.0-0.bpo.2-amd64

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.12.1

Operating System: Linux
Desktop Env: XFCE
Windowing System: X11

**Comment by droidmonkey** [comment]
Already fixed for 2.7.4

**Comment by vphantom** [comment]
Yay! Thank you!
