### ISSUE TITLE
Screen scale & browser integration bug

### ISSUE THREAD

**Issue by sakurayz** [keepassxreboot/keepassxc#8693]
When the remote desktop is connected, the screen will be automatically scale and the DPI will change. Clicking the KeePassXC browser integration button does not respond. I think the problem is caused by automatic screen scaling and DPI changes.

**Comment by droidmonkey** [comment]
Screen scaling is controlled through qt environment variables. It has nothing to do with browser integration. There is a known bug with browser integration in 2.7.3 that is fixed for the next release.
