### ISSUE TITLE
Hardware security key is never detected.

### ISSUE THREAD

**Issue by viral32111** [keepassxreboot/keepassxc#8694]
## Overview
Yubikey 5 NFC & 5C NFC for challenge-response is never detected.

## Steps to Reproduce
1. Insert Yubikey.
2. Open KeePassXC, create a new database or open security settings for existing database.
3. Refresh hardware key dropdown under challenge-response.

## Expected Behavior
Yubikey should show as a hardware key.

## Actual Behavior
It always says `No hardware keys detected`.

## Context
Same result when running as either a standard user, or an administrator.
The Yubikeys show in Yubikey Manager, and they work fine in every other application.

KeePassXC - 2.7.3
Revision: d8483d3

Operating System: Windows 10 21H2

**Comment by droidmonkey** [comment]
Did you setup a slot for challenge response?

**Comment by viral32111** [comment]
Ah apparently I never did on these keys, woops.
