### ISSUE TITLE
KeePassXC-Browser continues to display version 2.7.1 after installing 2.7.3

### ISSUE THREAD

**Issue by shaneknysh** [keepassxreboot/keepassxc#8696]
## Overview
After installing the update (via msi) the Keepass app shows version 2.7.3 but the Keepass browser app still displays 

'You are using an old version of KeePassXC.
[Please download the latest version from keepassxc.org](https://keepassxc.org/download)."

Note: While creating this ticket I discovered that the debug info is still showing 2.7.1 even though the installer is 2.7.3

## Steps to Reproduce
1. start KeepassXC
2. start Firefox with KeepassXC-Browser extension installed
3. click on keepassxc extension

## Expected Behavior
no warning is displayed

## Actual Behavior
version warning is displayed

## Context
computer has been restarted since the installation completed

This might be the key (this is the information although the installer is KeePassXC-2.7.3-Win64.msi)
KeePassXC - Version 2.7.1
Revision: 5916a8f

Operating System: Windows 11
Desktop Env: n/a
Windowing System: n/a

**Comment by droidmonkey** [comment]
Close all browsers and keepassxc app and reinstall using the 2.7.3 msi.

**Comment by shaneknysh** [comment]
Already done this should I do it again?

**Comment by shaneknysh** [comment]
Already did this as part of installing. 

I've run the installer multiple times including uninstalling first and using geek uninstaller. Should I do these steps again and update or create a new ticket?

**Comment by droidmonkey** [comment]
Make sure you aren't running a portable version instead of the installed version. There is no reason why the 2.7.3 installer would install 2.7.1.

**Comment by shaneknysh** [comment]
Got 2.7.3 to install - had to add several extra steps to get the install to overwrite the 2.7.1 version beyond closing browsers.
