### ISSUE TITLE
Browser integration stopped to work after update to 2.7.3

### ISSUE THREAD

**Issue by radraw** [keepassxreboot/keepassxc#8698]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

After update to 2.7.3 using Ubuntu PPA on Ubuntu 22.04 KepassXC stopped to complete passwords in browser. Downgrading to Ubuntu's own (very old  2.6 version, becouse there is no previous version in the PPA) fixes the problem.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Upgrade KeepassXC to 2.7.3
2. Try to complete username/password clicking on the green KeepassXC icon at the form field 
3. 

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
The password should be completed

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Nothing happens

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.3
Revision:

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: Gnome
Windowing System: Wayland

**Comment by varjolintu** [comment]
Duplicate issue. Already fixed. Revert to 2.7.1 to get it to work.

**Comment by radraw** [comment]
Good news but It's not easy to revert since there is no previous version in the PPA repository.

**Comment by phoerious** [comment]
Update to 2.7.4.
