### ISSUE TITLE
HMAC error after updating from KeePassXC 2.7.1 to 2.7.3 and MacOS 10.14.6 to 11.7.1

### ISSUE THREAD

**Issue by dendrophil** [keepassxreboot/keepassxc#8699]
## Expected Behavior

My database should unlock.

### The following message appears:
_Error while reading the database: Invalid credentials were provided, please try again.
If this reoccurs, then your database file may be corrupt. (HMAC mismatch)_

## Steps to Reproduce

Update KeePassXC from 2.7.1 to 2.7.3
Update MacOS from (Mojave) 10.14.6 to Big Sur 11.7.1
Attempt to open your database.

## Context

Was prompted to update my MacOS after downloading KeePassXC 2.7.3, which could not run on MacOS 10.14.6.
Installed MacOS 11.7.1 and tried to open my KeyPass database file (a .kdbx file which I created in december 2020 with KeePassX - unaware at the time of the existence of new KeePassXC releases).

Upon doing so I can no longer log into my database. I have tried opening my database using the 2.7.1 release. This results in the same error. I have also tried using various older versions of my database file which I obtained from my backup hard drive, also resulting in the same message. Furthermore, upon trying my current and an older version of my database file with 2.7.3 and 2.7.1 on a Windows computer, this also resulted in the same message.

I do not use a key file. I have consulted [#3840](https://github.com/keepassxreboot/keepassxc/issues/3840) and [#3678](https://github.com/keepassxreboot/keepassxc/issues/3678). I am not technically experienced in using the Terminal or other 'behind the scenes' sort of operations on my Mac.

Whilst creating space on my hard drive for the MacOS update I deleted many cache files. I don't know if this could be in any way related to the current problem.

## Debug Info

KeePassXC - Version 2.7.3
Revision: d8483d3

Qt 5.15.6
Debugging mode is disabled.

Operating system: macOS 11.7
CPU architecture: x86_64
Kernel: darwin 20.6.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 2.19.2

## Operating system info
MacBook Pro (Retina, 13-inch, Mid 2014)
Processor 2,6 GHz Dual-Core Intel Core i5
Memory 8 GB 1600 MHz DDR3

**Comment by droidmonkey** [comment]
The only explanation is typing the wrong password. Especially if your backups also fail.

**Comment by dendrophil** [comment]
I fear it is that. I've reproduced the password from a piece of paper I keep - same as I know it in my head.
Thanks anyway @droidmonkey for the quick response.

**Comment by zeetabit** [comment]
It seems classic KeePassXC behaviour after long years.
I have the same issue for latest version, just upgraded, but `MacPass` opens it without any issues. So going back to old MacPass ¯\_(ツ)_/¯

I think it may be related somehow with touch ID unclock feature, maybe some some certificate is not valid anymore... but need to investigate source code :)

**Comment by zeetabit** [comment]
Resolved by removing all cache/configs/data, but it's strange :/
`rm -rf "/Users/zetabit/Library/Application Support/KeePassXC"`
`rm -f "/Users/zetabit/Library/Preferences/org.keepassxc.keepassxc.plist"`
`rm -rf "/Users/zetabit/Library/Caches/KeePassXC"`
