### ISSUE TITLE
Browser connection is broken

### ISSUE THREAD

**Issue by jo-so** [keepassxreboot/keepassxc#8702]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

Commit 69f05d4c26f5afb0feb0892cc71a4a2aaded9518 broke the browser connection

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Start KPXC and open the database
2. Open a website which requests credentials
3. the credential dialogue doesn't open

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

The credential dialogue should open

[NOTE]: # ( Paste debug info from Help → About here )

KeePassXC - Version 2.7.2-snapshot
Build Type: Snapshot
Revision: c5eaee

Qt 5.15.6
Debugging mode is enabled.

Operating system: Debian GNU/Linux bookworm/sid
CPU architecture: x86_64
Kernel: linux 6.0.0-2-amd64

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- Secret Service Integration

Cryptographic libraries:
- Botan 2.19.2

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: Awesome
Windowing System: X11

## Patch

``` diff
commit c30bef7b2d9afa8997e5ebef28cbcfbe2b677e6a (HEAD -> master)
Author: Jörg Sommer <joerg@jo-so.de>
Date:   Sat Oct 29 17:12:33 2022 +0200
 
    Browser: Fix socket cleanup
    
    69f05d4c26f5afb0feb0892cc71a4a2aaded9518 removed the file at the new
    location and not the legacy location.
    
    Remove the duplicate slash in the link destination
    
    ```
    % readlink /run/user/1000/org.keepassxc.KeePassXC.BrowserServer
    /run/user/1000/app/org.keepassxc.KeePassXC//org.keepassxc.KeePassXC.BrowserServer
    ```
 
diff --git a/src/browser/BrowserShared.cpp b/src/browser/BrowserShared.cpp
index f5978274..d6801ce8 100644
--- a/src/browser/BrowserShared.cpp
+++ b/src/browser/BrowserShared.cpp
@@ -38,14 +38,15 @@ namespace BrowserShared
 
         // Put the socket in a dedicated directory.
         // This directory will be easily mountable by sandbox containers.
-        QString subPath = path + "/app/org.keepassxc.KeePassXC/";
+        QString subPath = path + "/app/org.keepassxc.KeePassXC";
         QDir().mkpath(subPath);
 
         QString socketPath = subPath + serverName;
 #ifndef KEEPASSXC_DIST_FLATPAK
-        QFile::remove(socketPath);
+        const auto oldSocketPath = path + serverName;
+        QFile::remove(oldSocketPath);
         // Create a symlink at the legacy location for backwards compatibility.
-        QFile::link(socketPath, path + serverName);
+        QFile::link(socketPath, oldSocketPath);
 #endif
 
         return socketPath;
```

**Comment by ghost** [comment]
It looks like this is the master bug by which #8698 #8700 #8706 were closed as duplicates. I was watching one of those and it closed without linking to this master; I'm hoping that mentioning it here binds this bug number to the others.

**Comment by michaelk83** [comment]
@pootriarch The master one was #8634.
