### ISSUE TITLE
Different password between preview screen and edit screen 

### ISSUE THREAD

**Issue by Dick58** [keepassxreboot/keepassxc#8705]
## Overview
The programa show different password between preview screen and edit screen

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION: 2.7.3
Revision:  d8483d3

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS
Desktop Env: Mac
Windowing System: N/A

**Comment by phoerious** [comment]
#8633
