### ISSUE TITLE
Browser integration broken after upgrading from 2.7.1 to 2.7.3 (with AppImage and compiled from source under Linux)

### ISSUE THREAD

**Issue by botchedcode** [keepassxreboot/keepassxc#8706]
## Overview
With KeePassXC 2.7.3 the browser integration is broken. While the Auto-Type function works as expected in all of my browsers and the SSH agent functions works normally too, login fields on websites are no longer filled.

Neither clicking on the KeePassXC symbol in the username field nor filling in the context menu works. Just sometimes after starting the browser freshly it works once or in maximum two times and then the browser integration stops working. I always have to use the Auto-Type function to get the needed login credentials.

This problem occurs in both the 2.7.3 AppImage for Linux and the 2.7.3 release compiled from source. And it occurs equally in all of my browsers on all of my machines (see details below).

Additionally, in Firefox permanently the browser plugin loses the connection the KeePassXC, so I contantly have to click on the Reconnect button. That didn't happen until KeePassXC 2.7.1 either.

## Steps to Reproduce
1. Open KeePassXC database
2. Open browser (Chrome, Edge, Vivaldi, Firefox)
3. Load a website with a login field for which the credentials are stored in the opened KeePassXC database
4. click in the username field or click the KeePassXC icon in the username field or use the contect menu -> Fill Username and Password
5. hope, the needed credentials will be filled into username and password fields

## Expected Behavior
Normally the needed credentials are immediately filled into the username and password fields (which works perfectly until KeePassXC 2.7.1 on all the tested websites).

## Actual Behavior
The needed credentials are mostly never filled into the username and password field. The KeePassXC icon in the username field and the "Fill Username and Password" in the contect menu aren't working too. But the browser plugin is connected to the KeePassXC and the database is opened.

## Context
This problem occurs on all of my machines after upgrading from 2.7.1 to 2.7.3:

- 1 desktop PC and 1 notebook with Kubuntu Linux 22.04.1 LTS with KDE desktop
- 1 desktop PC with the newest stable Debian Linux 11 with KDE desktop
- 1 notebook with Debian Linux 11 with KDE desktop
- 1 virtual machine with Debian Linux 11 with KDE desktop

It happens on all of my browsers I'm using in parallel for some reasons:

- Vivaldi 5.5.2805.42 (with KeePassXC-Browser 1.8.3 extension)
- Google Chrome 107.0.5304.87 (with KeePassXC-Browser 1.8.3 extension)
- Microsoft Edge 107.0.1418.24 (with KeePassXC-Browser 1.8.3 extension)
- Firefox 106.0.2 (with KeePassXC-Browser 1.8.3 add-on)

It also happens whether I compile the application from source or use the appimage.

KeePassXC - Version 2.7.1
Revision: 5916a8f

Source: AppImage from KeePassXC website / source code from the .tar.xz from the github project page

Operating System: Linux (Debian GNU/Linux 11.5 / Kubuntu 22.04.1 LTS)
Desktop Env: KDE 5.24
Windowing System: X11 (Debian) / Wayland (Kubuntu)

**Comment by phoerious** [comment]
Already fixed in 2.7.4.
