### ISSUE TITLE
Password field in "password generator" window uses variable font

### ISSUE THREAD

**Issue by rextheleopard** [keepassxreboot/keepassxc#8709]
Windows 11 10.0.25231.1000 x64
KeepassXC 2.7.4 x64

Password field in "password generator" window uses variable font "Segoe UI". I think all password fields must use fixed fonts.

**Comment by Teknomancer** [comment]
This regression is also present on Linux.

Linux Mint 20.3 x86_64
KeepassXC 2.7.4 x64

**Comment by ritzmann** [comment]
Same thing on macOS 12.6.1, KeepassXC 2.7.4.

**Comment by phoerious** [comment]
This was introduced in 7e8a672de41bfc4f84f85bba68fadef117c360cc. The line for setting the font wasn't actually removed, but it also wasn't updated properly, so it now applies to the new parent widget and not the input field.
