### ISSUE TITLE
KeePassXC doesn´t open kdbx files from explorer

### ISSUE THREAD

**Issue by Vanerio** [keepassxreboot/keepassxc#8710]
## Steps to Reproduce
1. Double click a kdbx file in windows explorer.
2. KeePassXC opens, but not the file.

## Expected Behavior
File should be opened.

## Actual Behavior
File not opened.

## Context
It only happens since the last two updates.

Operating System: Windows 10

**Comment by droidmonkey** [comment]
Can't reproduce this at all. You might need to clear out your registry settings or something.

**Comment by Vanerio** [comment]
It started to happen to me since installing version 2.7.3.
I didn´t edit my registry.
KeePassXC don´t even open the kdbx file when dragging it to its desktop shortcut.

**Comment by michaelk83** [comment]
Just in case, check your file associations. Also make sure the file opens successfully via the Open Database function.
Might also try to delete the KeePassXC ini files - there were some previous issues where that helped (make a copy first).

**Comment by Vanerio** [comment]
> Just in case, check your file associations. Also make sure the file opens successfully via the Open Database function. Might also try to delete the KeePassXC ini files - there were some previous issues where that helped (make a copy first).

Thank you for your help Michael:
- My file association seems to be fine.
- Yes, kdbx files can be opened via Open Database function or drag&drop.
- Deleting ini file does not help.

**Comment by droidmonkey** [comment]
I just tested this, including dragging a file to the open application, and it worked fine. Without replicating this seems like a problem very local to you. Recommend a full uninstall and reinstall.

**Comment by Vanerio** [comment]
I actually said that dragging a file to the open app works fine.
What do not work is double clicking in explorer or dragging it to the **desktop shortcut**.

I have just tried a full uninstall and reinstall and unfortunatelly it didn´t work.
Please let me know if you need some more info.

**Comment by droidmonkey** [comment]
I also did the other methods you mentioned and it worked fine.

**Comment by Vanerio** [comment]
For me the only thing that opens is the app. I mean that when double cliking the file, the app opens, but not the file. So the filetype association is OK.
If there is something I can do to help you know what could be going on, please let me know.

**Comment by droidmonkey** [comment]
That doesn't mean the filetype association is ok. That means the filetype association doesn't include the path to the file you double clicked in the call to the application.

**Comment by Vanerio** [comment]
Thanks droidmonkey
It seems that you do not want more information provided and I can not be helped.
I will not make you lose more time here.

**Comment by droidmonkey** [comment]
I want to help but it is hard with limited information. Make sure this looks good in your registry:

![image](https://user-images.githubusercontent.com/2809491/198901312-bfc0ab31-69d0-49c5-9124-c535bbd97030.png)

and this as well:

![image](https://user-images.githubusercontent.com/2809491/198901367-23877472-892e-4db0-af01-a0717233cb2d.png)

**Comment by Vanerio** [comment]
Hi again droidmonkey
I had this like that, yes.
I even removed every registry entry containing "kdbx" or "keepass" and try again a new clean install. But it didn´t work.

But what it actually worked was installing KeePassXC 2.7.1. This version can open kdbx files for me from explorer.
So there must be something else going on, but I honestly don´t know how to help you or me.

**Comment by droidmonkey** [comment]
I am using 2.7.4 without issue. No one else has reported this as a problem. And there were no code changes around the opening of files like this. Unfortunately not much more I can say on this matter.

**Comment by Vanerio** [comment]
I understand.
Version **2.7.1** is the latest one that works for me.
If you can think of anything I can do to solve this or help you (now or in the future), please I will be happy to cooperate.
Thank you.

**Comment by jjsegers** [comment]
Hi there, 
I have exactly the same problem here.
The issue occurred with Windows 10 and remains also on Windows 11 22H2 (same machine) DELL XPS 15 7590

KeePassXC - Version 2.7.4
Revision: 63b2394

Qt 5.15.6
Debugging mode is disabled.

Operating system: Windows 10 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.22621

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 2.19.1

Re-.Install didn't help (did it several times...)

Any help would be appreciated

Thanks in advance
Joerg

**Comment by droidmonkey** [comment]
Unfortunately there is not much we can do. Our installer correctly placed the association in the registry. Try manually associating the files with keepassxc. Also make sure you don't have a lingering process stuck in the background.

**Comment by Vanerio** [comment]
> Hi there, I have exactly the same problem here. The issue occurred with Windows 10 and remains also on Windows 11 22H2 (same machine) DELL XPS 15 7590
> 
> KeePassXC - Version 2.7.4 Revision: [63b2394](https://github.com/keepassxreboot/keepassxc/commit/63b2394ed0598aea6b0f5ad16430ac93256c21bb)
> 
> Qt 5.15.6 Debugging mode is disabled.
> 
> Operating system: Windows 10 Version 2009 CPU architecture: x86_64 Kernel: winnt 10.0.22621
> 
> Enabled extensions:
> 
> * Auto-Type
> * Browser Integration
> * SSH Agent
> * KeeShare
> * YubiKey
> * Quick Unlock
> 
> Cryptographic libraries:
> 
> * Botan 2.19.1
> 
> Re-.Install didn't help (did it several times...)
> 
> Any help would be appreciated
> 
> Thanks in advance Joerg

Yes, still happening to me... The weird thing is that, as I said previosly, Version 2.7.1 works perfectly fine, so something must be going on.

**Comment by droidmonkey** [comment]
Do you use a unicode heavy language for windows?  This might fix the problem is so: #8782

**Comment by Vanerio** [comment]
Spanish (Spain), so me not really.

**Comment by Vanerio** [comment]
> Do you use a unicode heavy language for windows? This might fix the problem is so: #8782

Bingo!!! I checked again and although Spanish uses common characters, the folder in which I have my keepass file is named with a strange unicode symbol. Renaming the folder allows me to open the file correctly.
I don´t know if this is fixable (like previous releases), but at least I know I was not crazy and a potential solution! :)
Thank you!

**Comment by Vanerio** [comment]
Thank you very much!!!!! :)
All my previous issues has been solved with this new update!!!

**Comment by droidmonkey** [comment]
Hey that's great news!

**Comment by jjsegers** [comment]
Thanks a lot for this Update : )


Sent from Nine
________________________________
Von: Jonathan White ***@***.***>
Gesendet: Montag, 15. Mai 2023 15:17
An: keepassxreboot/keepassxc
Cc: jjsegers; Comment
Betreff: Re: [keepassxreboot/keepassxc] KeePassXC doesn´t open kdbx files from explorer (Issue #8710) 

Hey that's great news!

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you commented.Message ID: ***@***.***>

[ { ***@***.***": "http://schema.org", ***@***.***": "EmailMessage", "potentialAction": { ***@***.***": "ViewAction", "target": "https://github.com/keepassxreboot/keepassxc/issues/8710#issuecomment-1547845497", "url": "https://github.com/keepassxreboot/keepassxc/issues/8710#issuecomment-1547845497", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { ***@***.***": "Organization", "name": "GitHub", "url": "https://github.com" } } ]
