### ISSUE TITLE
Some characters in passwords show incorrectly in the entry

### ISSUE THREAD

**Issue by sn2b** [keepassxreboot/keepassxc#8718]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
Trying to read passwords in the UI with some special characters gives an incorrect password.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1.  Make a new entry
2. Type a character like `"` or `&` as password
3. Save and exit the new entry. In the entry, view your password.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Expect the password to show as was typed in. E.g. if I create the entry with a password `"`, I would expect the preview to be `"`.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
The password shows as `&quot;`.

## Context
[NOTE]: # ( Give us any additional information you may have. )
Copying and looking at the password while editing the entry works as expected.
Let me know if I can clarify anything

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.3
Revision: d8483d3

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS
Desktop Env: Gnome/KDE/XFCE/Mate/Cinnamon
Windowing System: X11/Wayland

**Comment by phoerious** [comment]
Update to 2.7.4.
