### ISSUE TITLE
Unlock Database dialog not disappearing on macOS 13 Ventura

### ISSUE THREAD

**Issue by akelsch** [keepassxreboot/keepassxc#8719]
## Overview
When triggering the "Unlock Database" dialog by clicking on a KeePassXC-Browser username field icon, the dialog will not disappear even after successfully unlocking the database. The dialog can only be closed by quitting KeePassXC or locking the database and triggering another unlock from the browser.

I think that this is not the fault of the browser extension, hence I am opening this issue here. It happened after updating to macOS 13 Ventura and KeePassXC 2.7.3.

## Steps to Reproduce
1. Make sure the database is locked
2. Trigger unlock with username field icon by KeePassXC-Browser extension
3. Unlock database with correct password

## Expected Behavior
The "Unlock Database" dialog should disappear after successfully unlocking the database.

## Actual Behavior
The "Unlock Database" dialog does not disappear after successfully unlocking the database.

## Context
KeePassXC - Version 2.7.4
Revision: 63b2394

Qt 5.15.6
Debugging mode is disabled.

Operating system: macOS 13.0
CPU architecture: arm64
Kernel: darwin 22.1.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 2.19.2

KeePassXC-Browser - 1.8.3
Browser: Microsoft Edge 107.0.1418.24

**Comment by caretakerscurse** [comment]
For what it's worth, I'm experiencing this same issue.

**Comment by droidmonkey** [comment]
I cannot replicate this

**Comment by sciencetaco** [comment]
I'm having the same issue as @akelsch. It began to occur after I upgraded to ventura from big sur. It's persisted through at least the last three releases of keepasscx.

**Comment by droidmonkey** [comment]
If someone can make a video of the behavior that would be very useful. Remember to disable screenshot security.

**Comment by sciencetaco** [comment]
This might be an issue specifically with Keepassxc-Broswer. I can only trigger it by unlocking the database via the browser plugin. 
To reproduce:
Have a locked database
Request unlock via Keepassxc-Browser
Unlock with touch id
Window called 'Unlock Database - KeePassXC' will remain after the unlock.

**Comment by droidmonkey** [comment]
That is how I tested, using the browser extension. However this is the same code path as Auto-Type so I would expect the same behavior their as well. 

I did not use quick unlock though, but it shouldn't make a difference from a window visibility perspective.

**Comment by sciencetaco** [comment]
I played around some more, I can only trigger this behavior via keepassxc-browser and firefox. If I use brave, it functions normally.

**Comment by sciencetaco** [comment]
https://user-images.githubusercontent.com/40842482/199298259-82647521-9024-4fa1-877a-5eedb9ce43ad.mp4

**Comment by droidmonkey** [comment]
Interesting, it also doesn't happen with Edge. However OP was using Edge per their report.

**Comment by nathanclayton** [comment]
> I played around some more, I can only trigger this behavior via keepassxc-browser and firefox. If I use brave, it functions normally.

This also occurs with Chrome (107.0.5304.87) and the keepassxc-browser extension.

**Comment by mikes625** [comment]
FWIW, I'm having the same issue when I unlock the database using the browser extension. Intel Mac OS 13.0, Firefox 106.0.3, KeePassXC 2.7.4.

**Comment by akelsch** [comment]
It looks exactly like the video @sciencetaco provided, just that I do not use fingerprint unlock but an ordinary password:

![Screenshot 2022-10-31 at 11 12 11](https://user-images.githubusercontent.com/28652314/199487329-cf3f9658-4cfd-46f4-8582-39d83e70a6e3.png)

@droidmonkey I can confirm that I was using Edge

**Comment by droidmonkey** [comment]
I'll check the code to see if there is a Mac specific edge case being triggered. I am confident that the browser used is irrelevant.

**Comment by josepmendoza** [comment]
I'm experiencing the same issue with same application versions on Firefox 106.0.6 with KeePassXC-Browser 1.8.3.1.

**Comment by droidmonkey** [comment]
This is definitely a unique behavior started with 13.0, but I cannot replicate it on my computer.

**Comment by mikes625** [comment]
@droidmonkey I'm curious what your settings are. Default?

**Comment by droidmonkey** [comment]
For macOS? Nearly default, no special extensions or anything.

**Comment by mikes625** [comment]
@droidmonkey Thanks. I meant your keepassxc settings.

**Comment by droidmonkey** [comment]
Yes they are default, there are no settings that impact the display of this dialog

**Comment by mikes625** [comment]
My workaround is to untick "Request to unlock the database if it is locked" and use "Toggle window" in the menubar instead of the browser plugin to unlock keepassxc.

**Comment by ioExpander** [comment]
Hi. I'm also getting this issue since my upgrade to Ventura on an M1 mac. I'm using the Chrome browser plugin. @mikes625 's workaround works ok, but is there a way I can help debug this issue? Maybe setup a VM to reproduce the issue ? 
I've been using this app for so long that my muscle memory always brings me back to the browser plugin and the window it creates cannot be closed easily. 🙏

**Comment by orbanbalage** [comment]
fwiw since I'm on `macOS Ventura 13.1 Beta (22C5050e)` the issue seems to have disappeared...

**Comment by opwvhk** [comment]
I have this issue as well, using Brave. It is indeed triggered by KeePassXC-Browser (KeePassXC itself works perfectly).

Context:
KeePassXC-Browser version 1.8.3.1
Brave version 1.46.133 (based on Chromium version 108.0.5359.71 (Official Build) (arm64)
macOS Venture 13.0.1

**Comment by moabits** [comment]
I can confirm that this bug is only related to unlocking the database via the browser plugin.

**Comment by sciencetaco** [comment]
> fwiw since I'm on `macOS Ventura 13.1 Beta (22C5050e)` the issue seems to have disappeared...

I've just installed 13.1 (22C65) and I can confirm I no longer get the 'stuck' window.

**Comment by droidmonkey** [comment]
I am going to consider this a macOS bug at this point and don't plan to make any code changes.

**Comment by mikes625** [comment]
Just updated to Ventura 13.1. This issue appears to be corrected.
