### ISSUE TITLE
Use "flat" panel with small border

### ISSUE THREAD

**Issue by gagarine** [keepassxreboot/keepassxc#872]
The panel look strange on macOS. Not sure about other platform. I think it should look like the macOS finder sidebar.

## Expected Behavior
Two screenshot of applications panel that look "correct". You can also look at Firefox side panel also.
![screen shot 2017-08-16 at 01 05 31](https://user-images.githubusercontent.com/164074/29340485-89f06a0e-821f-11e7-882e-9d51eedaf281.png)

![screen shot 2017-08-16 at 01 10 17](https://user-images.githubusercontent.com/164074/29340521-b66c00c0-821f-11e7-8a54-5dd989ae3252.png)

## Current Behavior
Keepassxc panel is different and not in a good way ;).
![screen shot 2017-08-16 at 01 06 01](https://user-images.githubusercontent.com/164074/29340524-bae7e646-821f-11e7-9da8-08cbbc85c68f.png)

Operating system: maOS

**Comment by adolfogc** [comment]
Here are some good examples (screenshots of MacPass): https://github.com/mstarke/MacPass/wiki/Screenshots

**Comment by TheZ3ro** [comment]
Unfortunately IDK if it is possible to have this native look on macOS since we are using Qt.

**Comment by phoerious** [comment]
It may be possible, but I suppose we need to use a different widget.

**Comment by droidmonkey** [comment]
This might be fixable with a macos specific stylesheet (yah I am still advocating style sheets!).

**Comment by phoerious** [comment]
I dunno. Stylsheets have the bad habit to look exactly like what they are: pretentious modifications in an attempt to make a GUI look like you want. It's hard and sometimes impossible to get native look and feel with stylesheets (at least until Qt implements full CSS3 or 4) and it breaks terribly as soon as the user has a non-standard theme.

**Comment by gagarine** [comment]
On macOS user don't care about QT theme...  What they want is macOS native look (technically it's a QT theme, but not in the user point of view).

Is their a bug on QT about that? I saw this exact same problem on different QT program.
