### ISSUE TITLE
Different look of KeePassXC using AppImage or compiled from source (Linux, KDE)

### ISSUE THREAD

**Issue by botchedcode** [keepassxreboot/keepassxc#8720]
## Overview
On all of my machines I'm using Debian Linux 11.5 with KDE 5.20 or Kubuntu 22.04.1 LTS with KDE 5.24, all identically configured with "Arc Dark" theme. All the KDE- and GTK-applications like Firefox, Thunderbird, Gnome etc. have the same look.

This also applies to KeePassXC, no matter which version. It looks very nice with "Arc Dark" colours and integrates perfectly in my desktops, so it looks like all the KDE- and GTK-applications do.

But only, if I compiled KeePassXC from the source code. If I start the AppImage it looks different - I would say it looks kinda wrong.

In KeePassXC I always have the Theme set to "Classic (platform-native".

## Steps to Reproduce
Situation 1:

- compile KeePassXC from source on KDE with a Plasma theme active which is not the normal / standard theme
- start KeePassXC
- see a perfect looking KeePassXC which looks exactly like any KDE- or GTK-app

Situation 2:

- download KeePassXC AppImage from website
- start the AppImage
- see a different look which differs from the KDE- and GTK-apps

## Expected Behavior
Don't know if this has technical reasons or is intended so, but personally I would expect that both versions compiled from source and the AppImage should look identical to KDE- and GTK-apps with the theme set to "Classic (platform-native)".

## Actual Behavior
It looks different depending on whether I start the compiled binary or the AppImage.

## Context
KeePassXC - Version 2.7.4
Revision: 63b2394

Qt 5.15.2
Debugging mode is disabled.

Operating system: Debian GNU/Linux 11 (bullseye)
CPU architecture: x86_64
Kernel: linux 5.19.9-cw

Operating System: Linux
Desktop Env: KDE
Windowing System: X11 (Debian) / Wayland (Kubuntu)

**Comment by michaelk83** [comment]
Please provide screenshots.
~~https://keepassxc.org/docs/KeePassXC_UserGuide.html#_screenshot_security~~ (edit: screenshot security is not relevant to Linux)

**Comment by botchedcode** [comment]
Sorry, had some trouble with adding pictures.... ;)

This here is what I expect:

![login-nice](https://user-images.githubusercontent.com/108232177/198998650-585e89a3-d631-4b8b-961f-63c7c9792318.jpg)
![password-nice](https://user-images.githubusercontent.com/108232177/198998663-888a93d9-3027-43a0-8a2c-7615159fd4e1.jpg)

**Comment by botchedcode** [comment]
And this is what I see when using the AppImage:

![login-bad](https://user-images.githubusercontent.com/108232177/198998740-148bfb1b-4588-4fc6-978f-5ee90f631358.jpg)
![password-bad](https://user-images.githubusercontent.com/108232177/198998765-ae25ad63-886d-4287-808c-e277f7d4ad85.jpg)

**Comment by botchedcode** [comment]
Do not want to show you KeePassXC window after logging in showing my data.... but anything is more "dark" with AppImage, it is not consistent at all and differs from all other applications. There are dark colours, so dark I can't find anywhere.

Only with the version compiled from source, the correct symbols and colours are used and anything is consistent and meets the look of the desktop.

**Comment by phoerious** [comment]
If you compile it from source, it will use your system's Qt distribution and its themes. The AppImage we distribute is compiled on an older Ubuntu version and cannot use the Qt themes on the system it's running on, hence its falling back to the Qt standard theme. This cannot be changed and we recommend you simply go with our custom light and dark themes.

**Comment by botchedcode** [comment]
Ok, this is a good point. So I will continue using KeePassXC compiled from source.

Thanks.
