### ISSUE TITLE
Open URL in D - Application Layout

### ISSUE THREAD

**Issue by Caddode** [keepassxreboot/keepassxc#8722]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
I cannot open anymore the URL in Window D. The URL is green an underline. One click no fuction. In the older version no problem here,

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Go to window D
2. Click on the URL
3. Nothing happen

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Open the URL in the standard browser as before

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.3
Revision: d8483d3

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 11

**Comment by droidmonkey** [comment]
Update to 2.7.4
