### ISSUE TITLE
Keepassxc-2.7.4 breaks browser integration on Arch Linux

### ISSUE THREAD

**Issue by cyberpunkrocker-zero** [keepassxreboot/keepassxc#8725]
## Overview
After updating keepassxc on Arch Linux from 2.7.1 to 2.7.4 the browser integration stopped working on both Brave and Firefox

## Actual Behavior
After the update the icon has a red-white cross. When clicked (on Brave), it gives an error:
```
KeePassXC-Browser has encountered an error:
Message encryption failed. Is KeePassXC running?
```
and after pressing 'Reload'
```
Key exchange was not succesful
```
Downgrading keepassxc back to 2.7.1 restores the functionality

## Context
I've gone through the keepassxc-browser troubleshooting guide, withou any luck

[NOTE]: # ( Paste debug info from Help → About here )
```
KeePassXC - Versio 2.7.4
Revisio: 63b2394
 
Qt 5.15.7
Virheenjäljitystila on pois päältä.

Käyttöjärjestelmä: Arch Linux
Suoritinarkkitehtuuri: x86_64
Ydin: linux 5.15.76-1-lts

Käytössä olevat laajennukset:
- Automaattisyöttö
- Selainintegraatio
- SSH-agentti
- KeeShare
- YubiKey
- Secret Service -integraatio

Kryptografiakirjastot:
- Botan 2.19.2
```

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: I3
Windowing System: X11

**Comment by droidmonkey** [comment]
Close everything down and clear out /run/user/1000/org.keepassxc.KeePassXC.BrowserServer and the subfolder /app. Try again.

**Comment by cyberpunkrocker-zero** [comment]
Used Brave on my laptop as a testbed: Initially the above did not work, but then, because I run ALL browsers in a firejail, I started Brave without the jail, and then it worked. So it is actually the default firejail settings for Brave and Firefox which prevents the keepassxc-2.7.4 from working.

What has changed so much between 2.7.1 and 2.7.4?

**Comment by droidmonkey** [comment]
You need to allow access to the org.keepassxc.KeePassXC.BrowserServer socket in /run/user/1000

**Comment by cyberpunkrocker-zero** [comment]
I already had
```
whitelist ${RUNUSER}/org.keepassxc.KeePassXC.BrowserServer
```
in brave.local, That worked with 2.7.1. What else do I need to do?

**Comment by cyberpunkrocker-zero** [comment]
Why did you close this issue? It's not solved yet!

**Comment by droidmonkey** [comment]
Add `whitelist ${RUNUSER}/app/org.keepassxc.KeePassXC/org.keepassxc.KeePassXC.BrowserServer`

**Comment by cyberpunkrocker-zero** [comment]
Unfortunately, still not working... I have to continue debugging some other time, can't do it now

**Comment by droidmonkey** [comment]
This is closed because it's not a problem with our program, but a firejail configuration issue on your end. We did change where the socket was stored to support Flatpak distribution. Since the original location is a symlink to the app folder location you need to whitelist both, but the proxy should only be pointing to the new location.

**Comment by rusty-snake** [comment]
See https://github.com/netblue30/firejail/discussions/5444#discussioncomment-4039950
