### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [keepassxreboot/keepassxc#8726]
[An extra null pointer check is not needed in functions](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for null before delete p?") like the following.
- [Config::createConfigFromFile](https://github.com/keepassxreboot/keepassxc/blob/b1e7c34b82452773e0a7291462fef60a40a4ea72/src/core/Config.cpp#L541 "Config::createConfigFromFile function")
- [TestGui::cleanup](https://github.com/keepassxreboot/keepassxc/blob/4c1e5ec74ce01de634d0948768d8157dc54d7da6/tests/gui/TestGui.cpp#L152 "TestGui::cleanup function")
- [TestGuiBrowser::cleanup](https://github.com/keepassxreboot/keepassxc/blob/a740fe128cab4a4ab63d05dd9cce34e9c5cc484f/tests/gui/TestGuiBrowser.cpp#L107 "TestGuiBrowser::cleanup function")

**Comment by elfring** [comment]
:thought_balloon: Would you become interested to [use a development tool like “clang-tidy” for corresponding source code adjustments](https://clang.llvm.org/extra/clang-tidy/checks/readability/delete-null-pointer.html "Deletion of unnecessary null pointer checks")?

**Comment by droidmonkey** [comment]
We already use that and we have a few open pull requests with other general formatting/style fixes. If you want to help please submit a PR with the fixes.
