### ISSUE TITLE
Keepassxc snap won't update to 2.7.4 while Chrome (Brave) browser extension enabled - Ubuntu 21.10

### ISSUE THREAD

**Issue by acesabe** [keepassxreboot/keepassxc#8734]
### As title suggests, notification indicates pending update to Keepassxc available and that you need to close Keepassxc to update.

![image](https://user-images.githubusercontent.com/1364486/199469767-8332a9e6-41b7-4ccf-9d82-a09f5ef61937.png)

## Outline of issue
Wether this can be reproduced on other similar setups is not clear at this point but I'm sharing/reporting this here in case there is any issue and in case this helps anyone else with the same issue.

## Expected Behavior
Snap will update automatically once Keepassxc is closed

## Actual Behavior
Snap will not update even though Keepassxc is closed and cannot be updated by running:

sudo snap refresh

No such issues with snap updates to Keepassxc with browser extension enabled previously.

## Workaround
Disable the browser extension then issue the above command (or wait intil auto update runs) which will then update Keepassxc

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - <=2.7.3

[NOTE]: # ( Pick choices based on your environment )
Operating System: Ubuntu 21.10
Desktop Env: Gnome
Windowing System: Wayland
Browser: Brave (not tested on Chrome or other browser)

**Comment by droidmonkey** [comment]
Unfortunately there is nothing we can do about that, this is happening outside our process. Looks like snap may have gotten smarter about pulling the plug on running instances.
