### ISSUE TITLE
Automatic theme detection not working with version 2.7.4-1

### ISSUE THREAD

**Issue by Weav3r** [keepassxreboot/keepassxc#8735]
## Overview
With the new update (2.7.4-1) Keepassxc does not apply the system theme when View->Theme is set to Automatic. The theme is set to light, however, Keepassxc used to apply the theme set with kvantum manager. This is obviously a non-critical bug and certainly does not impact performance in any way but I thought developers ought to know.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Upgrade to keepassxc 2.7.4-1
2. Launch Keepassxc (it opens with light theme)
3. Change theme in kvantum manager
4. Restart Keepassxc (still opens with light theme)

## Expected Behavior
Keepassxc theme pick up system-wide theme whether light or dark.

## Actual Behavior
Keepassxc theme does not apply system-wide theme whether light or dark.

KeePassXC - 2.7.4
Revision: 1

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux (Kernel 6.0.6-arch1-1)
Desktop Env: Awesome-wm (ArcoLinux)
Windowing System: X11

**Comment by droidmonkey** [comment]
Please ensure kvantum is actually following the specifications. 

https://github.com/keepassxreboot/keepassxc/issues/7817#issuecomment-1092210362

Similar problem with gnome that we fixed in 2.7.2 for them...

**Comment by Weav3r** [comment]
I don't know the specification of which you speak about (I have browsed the keepassxc wiki). After a brief search I haven't figured out how to replicate the test for kvantum from the linked comment. I will keep trying to get to the bottom of the issue. Thanks for the quick response.

**Comment by droidmonkey** [comment]
Recommend opening a bug report with them

**Comment by Weav3r** [comment]
All right, thanks.
