### ISSUE TITLE
The password font is too small for my 70 year old mother to see. 

### ISSUE THREAD

**Issue by Kream** [keepassxreboot/keepassxc#8736]
## Overview
The password font is too small for my 70 year old mother to see. I've been trying to get my mother to use secure passwords for her bank websites and a big point of friction is that the password (she sometimes has to type it in to change passwords or use it on a device she doesn't have the keypassxc database on) is too small for her to clearly see. She's using Windows 10 and while the rest of her apps are legible, KeypassXC (green key according to her) shows the passwords in too small of a font size for her. In every other way the app works great. 

## Expected Behavior
an option exists in keypassxc to increase the font size either everywhere or for each place where there is writing. 

## Actual Behavior
no option exists in keypassxc to increase the font size either everywhere or for each place where there is writing. 

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.1 
Revision: 5916a8f

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 10

**Comment by phoerious** [comment]
Why would the KeePassXC password font be too small if the rest of the system has sufficiently big fonts?

**Comment by Kream** [comment]
I don't know. But it's smaller and more importantly there's no way I can see where she can adjust it.

**Comment by jNullj** [comment]
How about adding a font size override option in settings?
here is a quick mockup
![image](https://user-images.githubusercontent.com/15849761/200121640-8941ba8b-54f3-4568-8890-f7ef4e6d66b5.png)
If you think its good i could code it in, seems simple.
by that logic you could argue that there should be a set of interface overide a user can pick, but i have no idea what would be important to give control over and what wont be...

**Comment by Jon-guy30** [comment]
For me personally the font is fine, I'm on Windows 8,1. I didn't even know there wasn't any way to change the font in the program. It seems like such a basic feature along with what kind of font one wants to use.

What does it even use by default? The system font?

**Comment by droidmonkey** [comment]
We use the system font and the system scaling. If it's too small in our program is likely to small every where else as well...

**Comment by Kream** [comment]
That's not true. She's using her laptop just fine. She's an editor and edits manuscripts using MS Word without any issues, she's quite familiar with changing font sizes. 

As far as I can see, KeypassXC's font is courier and I'd also like to change the font to a bolder one that's easier to read at small point sizes and / or to increase the size.

**Comment by droidmonkey** [comment]
MS Word can be zoomed in since it's a text editor. If she is on Windows 10/11 then the font is by default Segoe UI, 9 point. You can increase this font size: https://support.microsoft.com/en-us/windows/change-the-size-of-text-in-windows-1d5830c3-eee3-8eaa-836b-abcc37d99b9a#ID0EBD=Windows_11

**Comment by droidmonkey** [comment]
![image](https://user-images.githubusercontent.com/2809491/200184939-8b091f4b-c7e3-4355-8529-f418d1217077.png)


![image](https://user-images.githubusercontent.com/2809491/200184528-6f17c22b-0d84-41f2-b8b6-4719a9828a0f.png)

<img width="898" alt="image" src="https://user-images.githubusercontent.com/2809491/200184558-39125aca-3977-45e6-af01-0ebf2edd1856.png">


You need to restart KeePassXC after changing the text size setting in windows.

**Comment by tredondo** [comment]
This issue should be closed as a duplicate of #6822.

**Comment by droidmonkey** [comment]
It is closed..
