### ISSUE TITLE
Attachments and URLS won't open on AppImage KeePassXC-2.7.4

### ISSUE THREAD

**Issue by nohing** [keepassxreboot/keepassxc#8737]
Hello,
even new version KPXC_2.7.4 not working, as the previous version 2.7.3:
Attachments and URLS won't open on AppImage, I have to keep using older version 2.7.1
Any help?

**Comment by phoerious** [comment]
This is not a bug of ours. I just rebuilt the 2.7.1 AppImage and it has the same issue. Therefore, it must be something to do with Qt or the Ubuntu base image. Trying to open attachments prints the following errors to the console:

```
kf.service.services: KApplicationTrader: mimeType "x-scheme-handler/file" not found
```

I don't think we can fix this ourselves and simply have to hope that an update of the base image will some day fix it.

**Comment by nohing** [comment]
so the developers of KeePassXC should contact Linux developers and tell them about this issue, right?
