### ISSUE TITLE
Wrong plural i18n string in Service.cpp

### ISSUE THREAD

**Issue by meskobalazs** [keepassxreboot/keepassxc#874]
In the `keepassxc/src/http/Service.cpp` file, there is this line at 548:

`tr("Successfully removed %1 encryption-%2 from KeePassX/Http Settings.").arg(count).arg(count ? "keys" : "key")`

The string should use plurals correctly, as right now `key` or `keys` are hardcoded. I would do the fix myself, but I don't know Qt.

**Comment by phoerious** [comment]
There are more occurrences of problems like this. We need to fix them at some point.

**Comment by meskobalazs** [comment]
I am no expert on either C++ or Qt, but this should fix it.

**Comment by weslly** [comment]
Fixed at #875
