### ISSUE TITLE
Some display problems in Linux 

### ISSUE THREAD

**Issue by lgjint** [keepassxreboot/keepassxc#8744]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
Thanks for developing such a good software, but I found some small display problems, I hope you can fix these bugs.
1. In the database general settings, the input box height is less than the text height and the checkbox overlap.
<img width="952" alt="database setting" src="https://user-images.githubusercontent.com/78463565/199684795-e300b555-563f-4894-b8a2-a342080f7c58.png">
2. The complete set of options is not visible in the password generator.
<img width="955" alt="password generator" src="https://user-images.githubusercontent.com/78463565/199684828-223411d2-7017-4a0a-bcb0-e5fe3f602481.png">
3. The icons in the tray menu are blurry.
<img width="226" alt="tray icon" src="https://user-images.githubusercontent.com/78463565/199684893-df07b0b0-ab27-4605-a038-5ade056bedec.png">

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Database->Database settings->General
2. Tools->Password Generator
3. Enable tray icon->Right click tray icon

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
1. The input box height is larger than the text height and the checkbox can be displayed in full without overlap
2. The password generator can display the complete set of options.
3. The icons in the tray menu can be clearly.
## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Same as Overview part.

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.4
Revision: 63b2394

Qt 5.15.7
Debugging mode is disabled.

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 6.0.5-x64v2-xanmod1-1

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: KDE
Windowing System: X11

**Comment by droidmonkey** [comment]
Can't fix 3 that is a kde problem. For some reason  qt on Linux allows you to shrink the window beyond the minimum height which is why 1 and 2 happen.

**Comment by lgjint** [comment]
I see. Thank you for your answer!

**Comment by 4inchezz** [comment]
Hi, I have the same problem. Also using KDE.
A workaround would be to scale qt for keepass.
When I need to start keepassxc, I execute this command:
`Exec=env QT_SCALE_FACTOR=0.5 keepassxc %f`

I have replaced the keepassxc-command for the application with this string, now the UI looks fine for me.
