### ISSUE TITLE
SHA256 Hash Don't Match

### ISSUE THREAD

**Issue by apex2nine** [keepassxreboot/keepassxc#8746]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

Algorithm : SHA256
Hash      : CA614EAD325513480378F6B55A570C05ED0570E199FEA63230985E9B15B59EDE
Path      : C:\Users\tc27\Downloads\keepassXC\KeePassXC-2.7.4-Win64.msi

Algorithm : SHA256
Hash      : 4E707B6899587D07BBF43E9367FCA0166C7A4DB9D726CFA5198E993EC148240A
Path      : C:\Users\tc27\Downloads\keepassXC\KeePassXC-2.7.4-Win64.msi.DIGEST

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )

1. Powershell as Admin
2. Get-FileHash C:\Users\tc27\Downloads\keepassXC\KeePassXC-2.7.4-Win64.msi                                                           
3.  Get-FileHash C:\Users\tc27\Downloads\keepassXC\KeePassXC-2.7.4-Win64.msi.DIGEST

## Expected Behavior
Matching Hash

## Actual Behavior
Hash does not match

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION 2.7.4
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows

**Comment by droidmonkey** [comment]
Follow the directions here please: https://keepassxc.org/verifying-signatures/

**Comment by apex2nine** [comment]
Thanks and sorry for the firedrill. I got a TRUE value.
