### ISSUE TITLE
Flatpak tray icon stuck on Colorful in Fedora GNOME Wayland

### ISSUE THREAD

**Issue by benjamin051000** [keepassxreboot/keepassxc#8747]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
The Flatpak distribution only displays the colorful tray icon regardless of which option I select in the settings. 

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Install KPXC via Flatpak on GNOME Wayland
2. Enable tray icons via AppIndicator and KStatusNotifierItem Support Extension
3. Enable tray icon
4. change tray icon color to monochrome

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
The tray icon should change color

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Icon stays green

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.4
Revision: 63b2394
Distribution: Flatpak

[NOTE]: # ( Pick choices based on your environment )
Operating System: Fedora Linux
Desktop Env: Gnome
Windowing System: Wayland

**Comment by luzpaz** [comment]
Maybe a `Flatpak` github label is needed ?

**Comment by droidmonkey** [comment]
There is one...

**Comment by droidmonkey** [comment]
There is nothing here for us to fix, we just tell Qt what to set the icon to. If that doesn't work then that is a Qt to Wayland bug, not in KeePassXC. You also seem to be using a KDE notifier plugin for Gnome.
