### ISSUE TITLE
Copy password button while editing entry is inconsistent

### ISSUE THREAD

**Issue by felker** [keepassxreboot/keepassxc#8749]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Open an entry to edit
2. Copy something from the Notes field using Cmd+C (in my case, it was an email address). Paste in another window
3. Press the "Copy password to clipboard" button in the opened entry. The "Clearing the clipboard in 10 seconds" countdown starts
4. Paste somewhere using Cmd+V

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

Password is pasted.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

The previously copied text, not the password, is pasted. I am not sure what the behavior is after the "clearing countdown" is finished. 

## Context
[NOTE]: # ( Give us any additional information you may have. )

I am having a hard time consistently reproducing this, but hoping to hear if others have run into this. 
I use my KeePass database on 2x macOS systems, and in fact, it normally only happens on one of the systems. 

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.4
Revision: 63b2394

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS
Qt 5.15.6
Debugging mode is disabled.

CPU architecture: x86_64
Kernel: darwin 22.1.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 2.19.2

**Comment by droidmonkey** [comment]
If you have text selected it will copy the text. We can't distinguish between when the toolbar button is pushed or the keyboard shortcut is pushed because they are the same thing. 

This is discussed in various issues on the board here, mostly closed

**Comment by felker** [comment]
Oh wow, that solves quite the mystery for me. Thanks!
