### ISSUE TITLE
GUI does not render on virtual machines

### ISSUE THREAD

**Issue by viharm** [keepassxreboot/keepassxc#8750]
## Overview
When I launch the Windows app GUI, it does not render on virtual machines.

## Steps to Reproduce
1. Install KeePassXC on a Windows virtual machine like VMWare Horizon, Shadow or QEMU.
2. Launch the GUI using the appropriate shortcut

## Expected Behavior
The GUI window should render.

## Actual Behavior
The GUI window does not render.

## Context
I have tried this on two separate Windows deployment environments:
1. Shadow (https://shadow.tech), which probably uses QEMU
2. VMWare Horizon

I have also tried this with PortableApps.com as well as the Windows installed version.

Is there a way to launch the GUI from the command line, but enable some sort of launch debugging?

## Environment
Platform: VMWare Horizon & QEMU
Operating System: Windows
Desktop Env: N.A.
Windowing System: N.A.

**Comment by droidmonkey** [comment]
Read user guide on screenshot security. Although that shouldn't apply to a virtual machine unless you are viewing it using rdp.

**Comment by viharm** [comment]
It wasn't obvious that the screnshot security applied to virtual machines, but thanks for pointing this out. I've tried `--allow-screencapture` as per the user guide and it works.
