### ISSUE TITLE
Add "Tab-change" like hotkeys (ctrl+n for DB)

### ISSUE THREAD

**Issue by Underknowledge** [keepassxreboot/keepassxc#8755]
## Summary
Add keyboard sortcut to open/locked databases

## Examples
ctrl+1 to switch to the first tab, Ctrl+2 to switch to the second, and so on. Ctrl+9 switches to the last tab.

## Context
I use multiple databases, separated by topic I work on. 
Also I don't like to move my hands away from the keyboard :sweat_smile: 

Every Browser has the rather neat functionality to change tabs with the ctrl and a number
Could possible go into a setting 
 "Select Tab 1 to 8" Shortcut:  [Ctrl, Alt, "Ctrl+Alt", ...]

This way you can do 
`[Super+3]` Open KeepassXC in the foreground 
`[Ctrl+2]` Open the seccond DB 
`[Ctrl+f, keyword]` Search for pass
`[Ctrl+c]` Copy pass 
`[Alt+tab] `Open last active window 
`[Ctrl+Shift+v]` Pass in the copyed Pass 
`???`
`Success`

**Comment by droidmonkey** [comment]
These are already in place make sure you are using the latest version
