### ISSUE TITLE
[Feature Request] Printing

### ISSUE THREAD

**Issue by atypicalprogrammer** [keepassxreboot/keepassxc#876]
I was surprised to see that printing out a password list is not possible. Is this something being considered for a future release?

**Comment by phoerious** [comment]
We don't have any plans, but if you want to work on it, feel free to send a pull request.

**Comment by Udo017** [comment]
I wish a command to print out the password list too.

**Comment by TheZ3ro** [comment]
Someone said: "Why do you use an Encrypted password manager in a first place if you need to print out your passwords on paper?"

**Comment by magkopian** [comment]
@TheZ3ro Well, to be fair paper cannot be hacked without physical access.

**Comment by TheZ3ro** [comment]
@magkopian I don't think it's really safe printing all the passwords in your password manager

**Comment by Udo017** [comment]
The printed password list is a (second) backup for the case that my Computer crashed and the first backup is inaccessibly for different reasons (perhaps a virus on the backup media). I use the password manager because it is easier and faster to copy an paste (or auto fill) complex password then type it from a sheet of paper.

**Comment by magkopian** [comment]
@TheZ3ro I agree and personally I wouldn't do it, but I would understand if someone wanted to keep a printed emergency backup of their passwords inside a safe deposit box at a bank.

**Comment by TheZ3ro** [comment]
@magkopian and what happen if I need to change my passwords? I have to re-print all of them and store them again at a bank? Seems too crazy to me

**Comment by magkopian** [comment]
@TheZ3ro Yes, that basically relates to the second part of my response. I do agree, that keeping **all** of your password in a printed format shouldn't be a good idea.

**Comment by louib** [comment]
@atypicalprogrammer @Udo017 what about exporting to csv and then printing? would that not be sufficient for a paper backup? I guess we could add a CLI command for exporting to csv (or other formats) anyway.

**Comment by TheZ3ro** [comment]
You can already export as CSV, if you want you can print that

**Comment by magkopian** [comment]
To add on that, you can even open the CSV file in LibreOffice format the data a bit and print it from there. There is really no point for such a feature in my opinion.

**Comment by droidmonkey** [comment]
I agree and dont think this is necessary to add
 Printing is notoriously annoying especially multi platform.
