### ISSUE TITLE
Unlock Database unclosable greyed-out popup window remains open after unlocking database with fingerprint

### ISSUE THREAD

**Issue by orbanbalage** [keepassxreboot/keepassxc#8761]
## Steps to Reproduce
1. Not sure exactly, but it has to be a combination of the quick unlock feature and that the database gets locked when the session is locked
2.  Somehow under some circumstances the whole KeePassXC window is "covered" by the green "Unlock Database" button
3.  At the same time a Popup is also displayed with the same content
4.  If I unlock the database from the main window, the popup remains as a phantom...

## Expected Behavior
Popup disappears after unlocking the database

## Actual Behavior
Popup window remains open, all buttons are greyed out, and it doesn't react to Cmd+W or the red X (close) button.

## Context

```
KeePassXC - Version 2.7.4
Revision: 63b2394

Qt 5.15.6
Debugging mode is disabled.

Operating system: macOS 13.1
CPU architecture: x86_64
Kernel: darwin 22.2.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 2.19.2
```

**Comment by droidmonkey** [comment]
#8719
