### ISSUE TITLE
Calculated TOTP since updating from 2.7.2 to 2.7.4 wrong

### ISSUE THREAD

**Issue by anolting** [keepassxreboot/keepassxc#8764]
Hello

I have updated the windows version last week to 2.7.4. I have configured some TOTP.
Now I have a record with login data and TOTP which generates wrong tokens. I am not 100% sure, but I mean until today (11/07) it worked.
Cross checking with the linux version shows, that the linux version calculates correct tokens. Also checking with Aegis the token on Aegis is correct.

Removing the key and setting up the TOTP configuration again did not change.
If there is a way to debug this I will do.

Best Alex

**Comment by droidmonkey** [comment]
Sync your system time

**Comment by anolting** [comment]
Many thanks. Even that I have setup Windows to do every time after login a sync the Timer Service don't do this or is unable to receive the time.
