### ISSUE TITLE
second unlock-window does not minimize/hide on mac

### ISSUE THREAD

**Issue by dingu23** [keepassxreboot/keepassxc#8765]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
The settings are set to minimize KeepassXC after the password is entered. I use the quick log-in option with Touch ID. A second window always appears above the KeepassXC window. When I log in, the KeepassXC window minimizes, but the second window stays there. I can't close or hide it either.

Thanks a lot for your help!
Daniel

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. KeepassXC is open, but minimized
2. Activate KeepassXC via the browser integration
3. Insert password or Touch-Id
4. KeepassXC-window is automatically hidden
5. "Unlock database-window" is still open and can't be closed

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
in the past the additional "Unlock database" window has been minimized/hidden or closed automtically

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
The additional "Unlock database"-window is always there and cannot be closed

## Context
[NOTE]: # ( Give us any additional information you may have. )
The additional "Unlock database"-window appears grey and if you click on anything in that window, the normal KeepassXC-Window pops up.
When the additional "Unlock database"-window" is open, the menu-bar at the top shows the KeePassXC menu, but you cant access any of the menus.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.4
Revision: 63b2394

Qt 5.15.6
Debugging mode is disabled.

Operating system: macOS 13.0
CPU architecture: arm64
Kernel: darwin 22.1.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 2.19.2

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS
Desktop Env: Gnome/KDE/XFCE/Mate/Cinnamon
Windowing System: X11/Wayland

**Comment by droidmonkey** [comment]
#8719

**Comment by MarkWieczorek** [comment]
This problem persists:

https://github.com/keepassxreboot/keepassxc-browser/issues/1946
https://github.com/keepassxreboot/keepassxc/issues/9297

**Comment by aitorpazos** [comment]
This is still an issue for me in macOS Tahoe and it is a big UX issue.
More important than the fact that I get 2 KeepassXC windows open (annoying but not a dealbreaker) is the fact that the only one that accepts input for unlock is the window that sits in the background. Commonly, this window in the background is hidden by the second window which do not accepts input, making it hard to discover that there is actually a second window waiting for input behind.
