### ISSUE TITLE
Reset search field when opening a group

### ISSUE THREAD

**Issue by magenbrot** [keepassxreboot/keepassxc#877]
This is just a little cosmetic suggestion. I would like to have keepassxc to reset the search filed when I click on a group on the left side (and display the group content instead of the search result).

I think KeepassX has this feature and this is the only thing I am missing ;)

**Comment by droidmonkey** [comment]
This is done by design because if you are searching non-globally you select a group on the left while in the search to change your scope. To end a search simply press Escape.
