### ISSUE TITLE
Multiple 2fa/otp

### ISSUE THREAD

**Issue by akissz** [keepassxreboot/keepassxc#8771]
Please add multiple 2fa/otp options for multiple security keys. Some websites, not many, but some, have multiple security keys for use for different functions. It would be handy if the application had the option to have multiple security keys in one user. I know it is not as secure to have both in the same place but maybe there is a way like maybe the second security key can have a separate lock password or pin or something.

**Comment by droidmonkey** [comment]
We won't implement this since it is a usability nightmare with browser, autotype etc. You can create multiple entries for the same site that then works with all our features.
