### ISSUE TITLE
KeePassXC GUI not active when doing hotkeys with two consecutive login requirements

### ISSUE THREAD

**Issue by penalvch** [keepassxreboot/keepassxc#8772]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

What is expected to happen with Chrome as the active window and at the Amazon.com login signin page, is when one clicks the KPXC hotkey, chooses the username, clicks the 'Type Sequence' button, then the next site comes up asking for the password, click the KPXC hotkey, is that KPXC is the active window both times.

What happens intstead is that KPXC becomes the active window only on the username screen hotkey attempt, and is inactive on the password screen. This is a workflow breakdown is one is expecting KPXC to be the active window and when typing, it narrows the entries down to one that is applicable.

I tried taking a screenshot via Flameshot and default MacOS screenshot hotkeys of KPXC to better demonstrate the issue but KPXC doesn't show up (presuming some sort of built-in security feature).

![image](https://user-images.githubusercontent.com/115644052/200684105-8a27a653-0555-4e3b-a0dc-1ee6ac02da63.png)

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.4
Revision: 63b2394

Qt 5.15.6
Debugging mode is disabled.

Operating system: macOS 13.0
CPU architecture: arm64
Kernel: darwin 22.1.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 2.19.2

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS
Desktop Env: Default
Windowing System: Default

**Comment by droidmonkey** [comment]
This is a "security" feature of macOS. When a password field is selected it will prevent another window from stealing focus.

**Comment by penalvch** [comment]
Hey @droidmonkey, thanks for the quick response and root cause!

Is there any way for those who would like to disable this feature on a per-app or select circumstance basis?

I'm not ahead of this security feature details so wouldn't be able to confirm/deny, find relevant documentation quickly, go to Apple developer site and guess-around, etc.

Also, while this is not necessarily comparing apples-to-apples, 1Password doesn't have this problem.
