### ISSUE TITLE
OpenSSL library outdated

### ISSUE THREAD

**Issue by codeban** [keepassxreboot/keepassxc#8774]
Hello everyone,

Unfortunately, Microsoft Security warns me about an outdated OpenSSL library (version 3.0.5). Please update the OpenSSL library for Windows in the build process and deploy an update.

I used KeePassXC 2.7.4 which comes with OpenSSL Version 3.0.5 (libcrypto-3-x64.dll), currently OpenSSL 3.0.7 is available (https://www.openssl.org/source/).

I'd add a pull request, but the external library seems to be added at build time.

Thank you!

**Comment by phoerious** [comment]
Duplicate of #8728

**Comment by codeban** [comment]
Thank you! @phoerious
