### ISSUE TITLE
Crash when editing group after enabling browser integration

### ISSUE THREAD

**Issue by ghost** [keepassxreboot/keepassxc#8775]
## Overview
After enabling Browser Integration in settings, right clicking a group and clicking Edit group crashes KeepassXC.
The steps to reproduce the crash assumes that you don't have Browser Integration enabled to begin with.
If you already have it enabled, disable it and then restart KeepassXC.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Start KeepassXC
2. Go to Tools -> Settings -> Browser Integration, Enable browser integration, click OK
3. Open/unlock a database
4. Right click any group and click Edit group

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Expected to be able to edit my group settings

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
![err](https://user-images.githubusercontent.com/117838817/200865389-9be4cdb5-79ad-49c4-ab72-304f7fde6319.png)

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.4
Revision: 63b2394

Qt 5.15.6
Debugging mode is disabled.

Operating system: Windows 10 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.22621

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 2.19.1

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 11 Pro 22H2 Build 22621.819

**Comment by varjolintu** [comment]
Reproduced it. It happens because the UI is not initialized after the option has been enabled. The situation needs an extra check. Already working on it.

**Comment by varjolintu** [comment]
There's another bug that shows the Browser Integration page in the Group Edit even after it has been disabled.
