### ISSUE TITLE
Memory issue 500MB in locked state idea: Automatically close keepassxc when in idle

### ISSUE THREAD

**Issue by zDEFz** [keepassxreboot/keepassxc#8776]
## Summary
keepassxc (flatpak) takes 500MB in the **locked** state. That is not acceptable. Therefore, I'd like keepassxc to implement either to free memory or close as an optional trigger to setup. Or perhaps purging the memory?

## Context
Too high memory usage.

**Comment by phoerious** [comment]
500MB is very likely just virtual memory. The actual resident set size will be much smaller. We don't keep any expensive data structures in memory.
