### ISSUE TITLE
"&" character is rendering as "&amp;" in preview pane

### ISSUE THREAD

**Issue by cttechcorp** [keepassxreboot/keepassxc#8779]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
Password ending in ampersand characters are rendering with "&amp;" notation in the preview pane.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1.  Create password with "&" at the end.
2.  Look at the preview, unhide.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Password with & = Password with &

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Password with & = Password with &amp;

## Context
[NOTE]: # ( Give us any additional information you may have. )
**Seen in v2.7.3.   Does not affect v2.7.1.**    

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - v.2.7.3
Revision: d8483d3

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows
Desktop Env: Windows Explorer
Windowing System: Windows 11

**Comment by droidmonkey** [comment]
Update to 2 7.4
