### ISSUE TITLE
Allow AutoType for only username or password

### ISSUE THREAD

**Issue by peterjuras** [keepassxreboot/keepassxc#878]
## Expected Behavior

There should be **additional** AutoType features that only type the username or password of the entry with or without being followed by an `ENTER` key.

## Current Behavior

To insert only the username or password, the value needs to be copied into clipboard and then pasted manually, which offers less security than using AutoType.

It sometimes it possible to circumvent this by `SHIFT-Tabbing` to a previous selected element on a webpage and then running AutoType, but this is a huge security and should not be recommended.

## Context

More and more websites and large sign in providers like [Google](https://support.google.com/accounts/answer/7338427?visit_id=1-636265040261476592-1851929765&p=signin_newlook&rd=1), [Microsoft](https://mspoweruser.com/microsoft-testing-new-design-microsoft-account-login-pages-across-services/) and others are changing their authentication flows to first put in the username/email and then the password on a separate screen.

Additionally, a lot of websites require the user to enter the password for advanced features that should be secured through the password again (e.g. on GitHub adding additional collaborators to a repository).

What do you think of such a feature?

Possibly related to #491

**Comment by phoerious** [comment]
You can define custom Auto-Type sequences for every entry.

**Comment by peterjuras** [comment]
Thank you for the quick response and pointing me to the Auto-Type features for each entry!

The current implementation of this feature is not very helpful for my use case, because it requires me to tie the sequences to certain window titiles.

However, Google's sign in flow for example has the same window title for both username and password entry, which makes it hard to customize the login flow. It also takes a while to submit the username, which makes it hard to describe the flow in one sequence.

In general, I find the hard coding of window titles to *anything* questionable and not future proof. I believe the possibility to define keyboard shortcuts for various AutoType sequences to be more helpful and to have more general applicability.

**Comment by phoerious** [comment]
Implementing global hotkeys to work on all platforms is very tricky, so we won't add any additional stuff here in the near future and for automatic matching, window titles are the only thing we have. You can use the browser plugin, though, to match by URL. And if you really can't remember your Gmail address, you can also create two entries and select which one to use each time.

**Comment by peterjuras** [comment]
I'm not suggesting to create new global hotkeys, rather direct context options on an entry to autotype only username or password. If this is too specfiic, it could also autotype custom sequences that are specified for an entry.

Global AutoTyping doesn't work for me at all because I don't have a mapping of window titles in my entries and I won't even try to add some. Instead an entry form like it is proposed in #429 would be much more helpful and generally appllicable.

For this feature however, my proposal would be to add additional context entry to this menu:

![screen](http://i.imgur.com/TspfJ7V.png)

The added option could be either autotyping only username or password or one of the custom specified sequences of this entry.

**Comment by phoerious** [comment]
I don't really understand what your problem is. I use Auto-Type with a custom sequence for Google, too, and it works reasonably well. If you don't want to add custom mappings, its not a problem of Auto-Type.

**Comment by droidmonkey** [comment]
It would be neat to be able to choose the autotype sequence you want from the context menu though.

**Comment by moeffju** [comment]
Seconding this. Sometimes I just need the password, but copy-paste does not work, e.g. in the case of Steam for Mac. If I change the auto-type sequence, I might have to enter the username manually. If not, I must manually clear the field and use auto-type for both. It would be nice if I could just focus the password field, and choose something like “Auto-Type Password” in the KeepassXC context menu.

**Comment by TheZ3ro** [comment]
> It would be neat to be able to choose the autotype sequence you want from the context menu though.

This is possible with my recent PR #1390

**Comment by paddylandau** [comment]
I have recently moved over to KeepassXC, which is a superior product to KeePass2 on Linux, and this is one of the two features that I miss terribly. KeePass2 implements this easily: I can right-click an entry, and choose to perform the default autotype (Ctrl+Alt+V), or to select username only or password only. They're in the context menu along with Perform Auto-Type, and absolutely do **not** have to have global hotkeys.

I have several cases where I frequently need one or the other. An example is GoDaddy, where different products require different ways of entering the same information; sometimes Ctrl+Alt+V does the job, but many times I need just the username or just the password.

I am aware of PR #1390 but I can't figure out how it works. Do I have to assign multiple autotype sequences for each and every key where this is used?
