### ISSUE TITLE
Password is visible after search

### ISSUE THREAD

**Issue by kjonski** [keepassxreboot/keepassxc#8780]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
Password is visible after search in datatable

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1.  Search for password using field with magnifying glass

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Password should not be visible but username should

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Username is hidden/masked with dots and password is visible

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.1
Revision: 5916a8f

Qt 5.15.2
Debugging mode is disabled.

Operating system: macOS 13.0
CPU architecture: x86_64
Kernel: darwin 22.1.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 2.19.1

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows/Linux/macOS
Desktop Env: Gnome/KDE/XFCE/Mate/Cinnamon
Windowing System: X11/Wayland

**Comment by phoerious** [comment]
I think you are having trouble with your settings. Check the correct entries in the view menu.

**Comment by kjonski** [comment]
You are right - never used this View menu before and probably toggle option by mistake with keyboard shortcut (facepalm)
