### ISSUE TITLE
Unlock Database window does not auto-close on macOS 13

### ISSUE THREAD

**Issue by moabits** [keepassxreboot/keepassxc#8783]
I unlock my database with the fingerprint sensor on a MacBook Pro M1.
Since updating to macOS _Ventura_, the "Unlock Database" window does no longer auto-close after unlocking.
The buttons get disabled, but the window stays open. I also can not close it manually since the window controls are disabled.

**Comment by varjolintu** [comment]
Duplicate of: https://github.com/keepassxreboot/keepassxc/issues/8719
