### ISSUE TITLE
Window disappears after losing focus on Mac Catalina, Ventura

### ISSUE THREAD

**Issue by CanadianArtLee** [keepassxreboot/keepassxc#8785]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Open KeepassXC
2. Click on somewhere else (e.g. desktop) so that the window loses focus
3. Click back onto KeepassXC window

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Window should regain focus and functionality

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Window disappears
Process is still running but UI is no longer accessible
Menu is still accessible (via top of Mac) but none of the options bring up the UI
Only quit (if it works) or force quit + relaunch will allow regaining access to UI
**Reverting back to version 2.6.6 seems to fix the issue**

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.4, 2.7.3, 2.7.2, 2.7.1, 2.7.0
Revision: 

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS Catalina 10.15.7, macOS Ventura 13.0.1
Desktop Env: N/A
Windowing System: N/A

**Comment by vladoros** [comment]
https://github.com/keepassxreboot/keepassxc/issues/8785#issue-1445921857 
same steps on ventura

**Comment by CanadianArtLee** [comment]
I can confirm on my Ventura 13.0.1, the same thing happens. When I revert all the way back to version 2.6.6, the window works as expected again.

**Comment by vandr0iy** [comment]
One way I managed to pop the window back into the visibility on 2.7.6 was to change focus with ⌘+TAB, and then go to KeePassXC -> About KeePassXC on the system bar on the top. That pops up the info screen, with the actual window on the background. At that point -  just lock & unlock your currently open database (if there is any) - and then right click on the icon in the dock ->  Hide. This way the window is still accessible whenever you change focus to it.
