### ISSUE TITLE
Combined view at Entry Preview Panel

### ISSUE THREAD

**Issue by bnsonear** [keepassxreboot/keepassxc#8786]
## Summary
Present UI of "Entry Preview Panel" shows split view of Tabs.
User would switch between tabs to check information and cannot see the information together.
Combined view of "General" tab and "Advanced" tab would be helpful.

## Context
I utilize KeePass as a history note or log book for a website or a service with credentials.
Also, internal 'note' field has a limitation for a organized view of information and memo.
Adding information by "Add a new field (Additional Attributes)" provides much better organized view.

Several KeePass alternative app provide a combined view.
Combined view means that 'All of fields' (=attributes) is shown at once by just selecting an entry.
examples: [KeeWeb](https://github.com/keeweb/keeweb), [AuthPass](https://github.com/authpass/authpass)
However, they are unstable or lack of basic functionalities.

Adding an option for combined view at KeePassXC setting would be nice.
By activating that option, KeePassXC will shows all field at once by selecting an entry without switching between General tab and Advanced tab.

Thank you for considering my idea.

**Comment by droidmonkey** [comment]
#8228 will handle this
