### ISSUE TITLE
Support fields reference in URL

### ISSUE THREAD

**Issue by zephyros-dev** [keepassxreboot/keepassxc#8787]
## Expected Behavior

1. Create an entry with fields reference in the URL field of the entry. .e.g:
```
URL: https://subdomain.{REF:U@I:5dc735f8e1c1405q8c4e71e90b49ag06}
```
rendered to
```
URL: https://subdomain.example.com
```
The URL above is rendered in KeepassXC
2. When KeepassXC search for entry to be inserted in the site, it should be able to search for the site with the rendered URL

## Current Behavior

Currently, KeepassXC cannot match the entries with field reference in URL

## Debug info

KeePassXC - 2.7.4
KeePassXC-Browser - 1.8.3.1
Operating system: Win64
Browser: Mozilla Firefox 106.0

**Comment by varjolintu** [comment]
Related: https://github.com/keepassxreboot/keepassxc/issues/7380.

**Comment by varjolintu** [comment]
@zephyros-dev FYI, the correct way to reference an URL is `{REF:A@I:5dc735f8e1c1405q8c4e71e90b49ag06}`. So `A` instead of `U` (username).

The fix to the original bug is done.

**Comment by zephyros-dev** [comment]
> @zephyros-dev FYI, the correct way to reference an URL is `{REF:A@I:5dc735f8e1c1405q8c4e71e90b49ag06}`. So `A` instead of `U` (username).
> 
> The fix to the original bug is done.

Thank you for the prompt work. I used `A` instead of `U` fields since I intend on using the REF features like a key/value for arbitrary field rather than just for the URL, so `A` for public and `P` for private REF. This is a workaround since Keepass [does not allow referencing values from arbitrary custom value](https://keepass.info/help/base/fieldrefs.html) field AFAIK
> Referencing fields of other entries only works with standard fields, not with custom user strings

I thought that it would work regardless of which field is referenced from, but if URL rendering will only works when referenced from `U` field I think there should be a note for this in the User guide.
