### ISSUE TITLE
KeepassXC can not save a changed database to google drive

### ISSUE THREAD

**Issue by fischmir** [keepassxreboot/keepassxc#8790]
## Overview
After editing a database located on google drive, keepassXC creates a new file (extended with <(1)>) instead of changing the opened file. This applies NOT for the Owner of the file, but all others.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Open a shared(!) Database from google drive, so that the path looks something like 2. F:\.shortcut-targets-by-id\1OdfsdfmkccJuyfajsgjansgnasfgZrJKzesMh\strongbox    (ID changed)
3. Add a record

## Expected Behavior
1. I do not want another file to be created. Changes should be saved to the opened file.
2. I opened a file called    1Passwort

## Actual Behavior
1. An additional file is created
2. I opened a file called    1Passwort
3. Changes were saved into a new file     1Passwort (1)

## Context

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.4
Revision: 63b2394
h
[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows

**Comment by droidmonkey** [comment]
We don't add a (1) in any of our code so that must be happening on Google drives side. Make sure you  have permission to write to the file. You can enable direct write saves on the settings if this is going through some strange mount program. I have never seen that path you posted before.
