### ISSUE TITLE
using two databases

### ISSUE THREAD

**Issue by IT-Dino** [keepassxreboot/keepassxc#8792]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
create a database for users "admin" and "supervisor" 
create a database for user "personal"

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Display the entrie as admin/supervisor AND personal

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
random entry is displayed

## Context
[NOTE]: # ( Give us any additional information you may have. )
Brave 1.45.123 (not snap!)

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.4
Revision: 63b2394

[NOTE]: # ( Pick choices based on your environment )
Operating System: Ubuntu 22.04
Desktop Env: Gnome
Windowing System: X11

**Comment by varjolintu** [comment]
Not sure what the context is here. Could you provide some details?

I can only assume this related using multiple databases with the browser extension? If you wish to retrieve credentials from all connected databases that are open, you must enable the option `[ ] Search in all opened databases for matching credentials` in KeePassXC's Browser Integration settings page.

**Comment by droidmonkey** [comment]
Closing unless more info is supplied
