### ISSUE TITLE
Save attachment opens an "Open" dialog windown on Ubuntu 20.04

### ISSUE THREAD

**Issue by indeec05** [keepassxreboot/keepassxc#8793]
## Overview
Saving attachment dialog window do not provide a possibility to save file. Just "Open" button is accessible. When choose any file and click "Open" get an error: "Unable to save attachments: filename.cer - Not a directory".
That happens on Ubuntu 20.04.5 LTS with KeePassXC 2.7.4

## Steps to Reproduce
1. Create entry with attachment
2. Open advanced windows with attachments
3. Choose one and click "Save" button
4. Try to choose any directory or file and click "Open"

## Expected Behavior
"Save" button opens a save dialog window and provide possibility to save attachment.

## Actual Behavior
"Save" button opens an open dialog window and do not provide possibility to save attachment.

## Context
That happens with my old database which migrate form one device to another, but I dodn't meet any problems before. And I cant reproduce it at the moment on another device or OS.
KeePassXC - Version 2.7.4
Revision: 7729648
Distribution: Snap

Qt 5.15.5
Debugging mode is disabled.

Operating system: Ubuntu Core 20
CPU architecture: x86_64
Kernel: linux 5.15.0-52-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.12.1

Operating System: Linux
Desktop Env: Gnome
Windowing System: X11

**Comment by droidmonkey** [comment]
>  I cant reproduce it at the moment on another device or OS.

That is because it is a bug with Ubuntu 20 and snaps. You will have to use flatpak or appimage or ppa.
