### ISSUE TITLE
Modifier key sequences using CMD-key (#)not working on macOS

### ISSUE THREAD

**Issue by geopanther** [keepassxreboot/keepassxc#8794]
## Overview
I want to use a key combination to close the current tab in Google Chrome using the key combination command + W within an Auto-Type sequence.

## Steps to Reproduce
1. Open Chrome Browser on macOS (Big Sur 11.6.8) with at least on tab with a unique title which can be closed by KeePassXC
2. Open KeePassXC (2.7.1) and create a new entry with artificial username and password.
3. Add Auto-Type entry using the window title of the browser tab from 1. with a special Auto-Type sequence for that specific window.
4. Enter the Auto-Type sequence "#w" for key combination commad + W on macOS
5. Switch back to browser tab from 1. and use key combination "control + command + a" to invoke Auto-Type for this tab.

## Expected Behavior
Chrome will close the current tab as it would if manually typing command + w

## Actual Behavior
Chrome does not close the current tab.

## Context
I need this since an authentication process is automatically opening a browser tab which I want to close after authenticating.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.1
Revision: 5916a8f

Qt 5.15.2
Diagnosemodus ist deaktiviert.

Betriebssystem: macOS 11.6
CPU-Architektur: x86_64
Kernel: darwin 20.6.0

Aktivierte Erweiterungen:
- Auto-Type
- Browser-Integration
- SSH-Agent
- KeeShare
- YubiKey
- Schnelle Entsperrung

Kryptographische Bibliotheken:
- Botan 2.19.1

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS
Desktop Env: macOS GUI (Aqua?)
Windowing System: Aqua?

**Comment by droidmonkey** [comment]
You need to update to 2.7.4

**Comment by geopanther** [comment]
@droidmonkey: Thanks for your fast reply. I apologize, I did't do a search in the closed tickets of newer versions before. I found the duplicate to be #6463 merged with #8111.

**Comment by geopanther** [comment]
Duplicate of #6463
