### ISSUE TITLE
New installed Version 2.7.4 

### ISSUE THREAD

**Issue by abernhaut** [keepassxreboot/keepassxc#8795]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

A new installed KeePassXC Version 2.7.4  does not show the window after start KeePass.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1.  Install KeePassXC Version 2.7.4 on a PC where Keepass was never installed before.
2.  Open the new installed KeePass.
3.  The Windows of KeePass was not show.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Open KeePass to open an existing database or create a new database.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
he Windows of KeePass does not show.

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION 2.7.4 
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows/Linux/macOS
Desktop Env: Gnome/KDE/XFCE/Mate/Cinnamon
Windowing System: X11/Wayland

**Comment by droidmonkey** [comment]
https://keepassxc.org/docs/KeePassXC_UserGuide.html#_screenshot_security
