### ISSUE TITLE
Hiding unnecessary information (only show notes)

### ISSUE THREAD

**Issue by girl313** [keepassxreboot/keepassxc#8798]
Hi,

I love this app, I only use "Notes" to keep various information and it would be great for me to hide unnecessary information that I will never use.

https://i.imgur.com/Coz4oAz.png
(KeePassXC v2.7.4 Win64)

thanks

**Comment by droidmonkey** [comment]
Covered by the default entry layout request

**Comment by girl313** [comment]
can you send here "layout request" a link and unify the topics?

**Comment by droidmonkey** [comment]
If you search for those terms you'll find it... #8228
