### ISSUE TITLE
Invalid memory reference when unlocking with Windows Hello

### ISSUE THREAD

**Issue by daviewales** [keepassxreboot/keepassxc#8799]
## Overview

When trying to unlock KeePassXC with my fingerprint reader using Windows Hello, sometimes (not always), I get the following error:

![The instruction at 0x00007FF7E89E2691 referenced memory at 0xFFFFFFFFFFFFFFFF. The memory could not be read. Click OK to terminate the program.](https://user-images.githubusercontent.com/2499066/202057719-7372d902-2b99-4773-a113-e7121fd9cb39.png)

This occurs after the Windows Hello window appears, and I put my finger on the fingerprint reader.
Clicking OK terminates both Windows Hello and KeePassXC.

After restarting KeePassXC, I can get in with no error.

## Steps to Reproduce
Can't reliably reproduce.
Tends to happen after KeePassXC has been open for some time.

1. Click 'Unlock database' 
2. Put finger on fingerprint reader

## Expected Behavior

No error should occur, and database should unlock.

## Actual Behavior

Memory reference error occurs.

[NOTE]: # ( Paste debug info from Help → About here )

KeePassXC - Version 2.7.1
Revision: 5916a8f

Qt 5.15.3
Debugging mode is disabled.

Operating system: Windows 10 Version 2009  <-- NOTE: This is incorrect. I'm on Windows 11 21H2
CPU architecture: x86_64
Kernel: winnt 10.0.22000

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 2.18.1

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 11

**Comment by droidmonkey** [comment]
Update to 2.7.4

**Comment by kingp0dd** [comment]
Experiencing the same error after unlocking with Windows Hello

This happened thrice already after upgrading to KeepassXC v2.7.7
