### ISSUE TITLE
 Feature request: KeePassRPC support 

### ISSUE THREAD

**Issue by soredake** [keepassxreboot/keepassxc#88]
## Expected Behavior
Having a KeePassRPC support 

## Current Behavior
No support for KeePassRPC, http://keefox.org/news/detail/2010/03/24/keepassrpc-plugin/.

## Possible Solution
Implementing a support.

**Comment by evetek** [comment]
That would be awesome, since there is no support for Thunderbird at the moment.

**Comment by phoerious** [comment]
I removed the milestone for now since we are not sure if we actually want to our users to expose their passwords over a network protocol with questionable security record. The security of both KeePassHTTP and KeePassRPC is doubtable and in their current state we would prefer not to have them as part of the main KeePasssXC product.

This doesn't mean KeePassXC will never support it, it only means that at the moment we don't have immediate plans and an implementation needs further discussion.

**Comment by Ajedi32** [comment]
I'd love to see some form of native support for browser integration (whether that be with a HTTP or RPC protocol). It's extremely convenient and protects against one of the most common attacks against password-based logins on the web: phishing.

**Comment by vanous** [comment]
Thanks for all the work and thanks for the KeePassHTTP integration. Any chance to please add KeePassRPC and also only allow it as a build parameter? The KeeFox extension is superior to the PassIFox imho. I could finally leave mono behind on my linux desktop... (nothing against mono, but in this case...)

**Comment by phoerious** [comment]
We have an open pull requests for that. When comparing KeePassHTTP to KeepassRPC, I would probably prefer to have the latter, but neither the KeePassRPC protocol nor the pull requests have been reviewed deeply enough yet that we can just integrate and ship it.

KeePassHTTP itself already has quite a few flaws which are being discussed in #147 and which we are trying to work around as best we can.

**Comment by soredake** [comment]
@phoerious keefox might be rewrited to webextension (api compatible with chrome) https://github.com/luckyrat/KeeFox/issues/728#issuecomment-263219244

**Comment by Teyras** [comment]
Just for the record, the KeePassRPC protocol seems more complicated than KeePassHTTP and it uses some features that are not present in KeePassXC (e.g. password profiles, if I understand correctly). The only "documentation" I know of is the [source code](https://github.com/luckyrat/KeeFox/blob/master/KeePassRPC/KeePassRPCService.cs) - look for methods annotated with [JsonRpcMethod].

**Comment by phoerious** [comment]
Closing this in favor of #259 to keep things organized.

**Comment by ggeorgg** [comment]
In [this comment](https://github.com/keepassxreboot/keepassxc/issues/88#issuecomment-264462577 ) eversins mentioned the support of thunderbird. Can this be done now with the release of KeePassXC-Browser. I have tried to manually install the xpi-file to thunderbird, but it tells me "this add-on could not be installed becaused it seems broken"

**Comment by droidmonkey** [comment]
Maybe? I am not sure how much crossover Thunderbird has with Firefox in terms of plugin functionality. The browser plugin is very focused on filling in form fields on web pages.

**Comment by ggeorgg** [comment]
OK. I thought that Firefox and Thunderbird had a very similar code base and not that much effort needs to be taken to realize this. Actually I was thinking about to switch from Keepass to Keepassxc.
