### ISSUE TITLE
Configure Password, Key file and challenge-response are `or` logic.

### ISSUE THREAD

**Issue by RMTT** [keepassxreboot/keepassxc#8801]
## Summary
Configure Password, Key file and challenge-response are `or` logic.

## Context
Current keepassxc(2.7.4) support `Password` , `Key file` and `challenge-resposne` from hardware key, but only work as `and` logic, if the hardware key lost, then i cannot open the database again. So i think support `or` logic of those three ways is convenient.

**Comment by droidmonkey** [comment]
Unfortunate that is not how the keepass file is setup. Also that would make your hardware key worthless, your database is only as secure as the easiest form of access.

**Comment by karlkashofer** [comment]
Sorry to necropost, but i just got my new Yubikey and wanted to use it with KeepassXC and stumbled on this very same probem.
I would like to use the Yubikey or the Passphrase. So i basically do not want to enhance the security of my database by adding the Yubikey, but i want it to enhance my convenience, by not having to input my (very long) passphrase when i have the Yubikey plugged in. I still want to be able to access my database if the Yubikey is at home or elsewhere.
I am fully aware that then the database is only as safe as the weakest link in the chain. 

With the current setup i am afraid that losing the Yubikey will make my database inaccessible so now i chose not to use it for KeepassXC, leading to the same security as before (passphrase only).

I do think that an Option to "use any one of the methods" or "combine all methods" is understandable and consciously selectable by users able to handle a Yubikey.

If there are no clear technical reasons for "not planned" i would kindly ask if you could reconsider.

**Comment by michaelk83** [comment]
You can emulate that by having a _separate_ database that opens with only the YubiKey, which is set up to [auto-open](https://keepassxc.org/docs/KeePassXC_UserGuide#_automatic_database_opening) the main database.
