### ISSUE TITLE
Sync mismatch between desktop and mobile version

### ISSUE THREAD

**Issue by MoBa158** [keepassxreboot/keepassxc#8803]
Hello,
my KeePassXC database is located in my private cloud (Onedrive) so that I can use and access it from my laptop (OS: Windows) as well as from my mobile device (OS: Android).
When I add a new login entry in the desktop version I can also see this on my mobile phone.
However, if I add a new login entry on my mobile device, this doesn't appear in the desktop version at all - also not after a few hours or days.
I don't understand the reason for this as there is only one database file which is located in the cloud.
Did anyone face this issue already and can help how to solve this?
Thank you!

**Comment by droidmonkey** [comment]
Confirm the file is actually being synced properly from your mobile device. This isn't a problem with our program, check your mobile app directions as well.
