### ISSUE TITLE
Setup OTP via QR-Code image

### ISSUE THREAD

**Issue by darkdragon-001** [keepassxreboot/keepassxc#8807]
## Summary
Add an option to set up (T)OTP via QR-Code image.

## Examples
I imagine the following workflows:
- KeePassXC entry > paste QR code from clipboard
- KeePassXC entry > select QR code from file
- KeePassXC browser plugin > right click on image > set up OTP
- KeePassXC access camera (e.g. v4l2 or pipewire stream)

## Context
When one sets up 2FA on a service, one is usually presented with the QR code. There should be an easy way to add new QR codes on websites which don't display the secret directly.

**Comment by droidmonkey** [comment]
#4825
