### ISSUE TITLE
Secure QRcode generation to copy/transfer a password offline and across different devices

### ISSUE THREAD

**Issue by passthesh3ll** [keepassxreboot/keepassxc#8808]
## Summary
KeePassXC could offer a new way of copying a password (or a database field) by using QRcode. In this way it can be copied across devices, without sharing the full database with the other device and without using internet. KeePassXC shouldn't leave traces of the generated image in disk or in memory after the image is copied.

#### Additional advice
I also opened a similar feature request for the KeePassDX android app, so it should be useful if KeePassXC (its linux "counterpart") could also offer a feature to read a QRcode with a webcam, in order to be able to leave as less information as possible in the linux clipboard and in order to not use 3rd party qrcode reader software that could memorize the image with password.
An additional feature that adds a sort of PIN to the image (generating an encrypted image) could be a very interesting feature.

## Examples
You have a smartphone and a computer, a keepass database is stored in the computer and you don't want to share it with the smartphone (maybe because the smartphone has a TOTP database and you want to avoid to generate "a single point of failure"). So you can generate on-the-fly a qrcode with the password and decode it in the smartphone just by using the phone camera.

Another example could be if you have two offline machines and you do not want to share the database with all the machines in order to limit the attack surface but you have to share some passwords/secrets. Maybe two raspberry pi with camera modules or two laptops.

## Context
I have two encrypted databases, one for passwords and one for TOTP tokens, I keep both offline. I don't want to leave my two databases in the same device in order to reduce the risk in case of hacking of that device. And I also don't want to manually copy a lot of 25 characters random passwords using a smartphone keyboard. There are android apps that can automatically clear the clipboard or/and delete the qrcode history so the password copying can be kept a bit "secure", even if it's not the proper implementation of such a feature (secure qrcode password transfer)

**Comment by droidmonkey** [comment]
#675
