### ISSUE TITLE
Main dialog renders badly on hi-dpi displays

### ISSUE THREAD

**Issue by graemeg** [keepassxreboot/keepassxc#8809]
## Overview
Simply launching the application, the main window doesn't render correctly on a hi-dpi display, like it does on a 96dpi "standard" display.

## Steps to Reproduce
1. Use a 4K monitor and run Kubuntu
2. Open the KeePassXC application
3. Observe the bad rendering of widgets

## Expected Behavior
I expected all widgets to appear like they do on a standard monitor with 96dpi GUIs.

## Actual Behavior
Widgets are too small. Icons are too small.

## Context
Here is a screenshot
![image](https://user-images.githubusercontent.com/72053/202517582-273b55b3-f682-48fd-805e-62d27129eac8.png)

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.4
Revision: 63b2394

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux (Kubuntu 22.04.1 LTS)
Desktop Env: KDE
Windowing System: X11 (I assume - I don't know what Kubuntu 22.04.1 LTS defaults too)
KeePassXC shows that it's using Qt 5.15.3 in the "Debug Info" tab.
xwininfo shows my display is 3840x2160
$ xdpyinfo | grep dots
  resolution:    157x161 dots per inch

I did not adjust any display settings. I simply plugged in a 4K monitor and started up Kubuntu.

**Comment by JohnLGalt** [comment]
I wonder if it's a QT issue. 

See [#6262 ](https://github.com/keepassxreboot/keepassxc/issues/8638) and https://github.com/keepassxreboot/keepassxc/issues/8035, the latter which links to https://github.com/keepassxreboot/keepassxc/issues/6262 - pretty much always comes down to QT and environment variables needing to be set to override the High DPI settings of your DWM.

**Comment by droidmonkey** [comment]
First that is not our theme so you must have  'classic' mode enabled which we don't support (YMMV). Second, you likely need to set your Qt environment variables appropriately, read our user guide for more information.
