### ISSUE TITLE
Auto-Type: Window Title Drop-Down Box not showing any windows 

### ISSUE THREAD

**Issue by mr-jingles** [keepassxreboot/keepassxc#881]
## Expected Behavior
Drop-Down Box should be filled with list of currently open windows.

## Current Behavior
Drop-Down Box is empty

## Steps to Reproduce (for bugs)
Open Auto-Type Window for any Entry

## Debug Info
KeePassXC - Version 2.2.0
Revision: b2107b5e276481efc36f95c1af09cd76b9a67ba5

Libraries:
- Qt 5.5.1
- libgcrypt 1.6.5

OS: Ubuntu 16.04.3 LTS
CPU-Architecture: x86_64
Kernel: linux 4.4.0-89-generic

Enabled Modules:
- KeePassHTTP
- Auto-Type

**Comment by TheZ3ro** [comment]
Are you using Wayland?

**Comment by mr-jingles** [comment]
I am running x11

**Comment by mr-jingles** [comment]
and gdm3

**Comment by mr-jingles** [comment]
sudo apt-get install libqt5x11extras5-dev solved it!
