### ISSUE TITLE
HMAC mismatch when using the correct password

### ISSUE THREAD

**Issue by jigpu** [keepassxreboot/keepassxc#8810]
## Overview
KeePassXC seems to have recently developed a fault with opening my password database. A significant majority of the time, I get the "HMAC mismatch" error that one would expect from either an incorrect password or corrupt database. A small minority of the time I am granted access.

* The database should not be corrupt since I have restored earlier versions from a backup and see the same behavior.
* The password cannot be incorrect since I can eventually unlock the database if I simply press 'Enter' enough times. (Since the password box isn't cleared on error, pressing 'Enter' just retries the already-typed password)

## Steps to Reproduce
1. Open my database
2. Ensure the key file is set correctly
3. Type in the correct password
4. Press 'Enter'
5. **Probably receive an HMAC mismatch**
6. If the database isn't unlocked yet, GOTO 4
7. Be granted access

[example.webm](https://user-images.githubusercontent.com/600734/202552608-b710a709-0b4e-40e9-a6f0-e507372424c5.webm)

## Expected Behavior
Database should unlock on the first attempt with the correct password.

## Actual Behavior
Most of the time an HMAC mismatch error is generated. A small percentage of the time (less than ~10%) the database unlocks.

## Context
I have been able to reproduce this with a freshly generated database using default settings. In this case, however, the database unlocks successfully 90% of the time. If I re-lock and retry enough times though, I eventually hit an HMAC error that can be dismissed by pressing 'Enter' a second time. Increasing the unlock difficulty (via the 'Benchmark 1.0 s delay' option) seems like it has an effect on the HMAC error rate.

KeePassXC - Version 2.7.4
Revision: 63b2394

Qt 5.15.7
Debugging mode is disabled.

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 6.0.8-arch1-1

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.19.2

Desktop Environment: GNOME 43.1
Windowing System: X11

**Comment by phoerious** [comment]
The algorithm is deterministic, so you should be getting the same result every time. If not, you may want to check if your RAM is faulty.

**Comment by droidmonkey** [comment]
Either faulty ram or you are using non ascii characters in your password and they don't type out when the password is hidden. 

> Increasing the unlock difficulty (via the 'Benchmark 1.0 s delay' option) seems like it has an effect on the HMAC error rate.

100% sure you have faulty ram or you've way overclocked or under volted your cpu/ram.

**Comment by jigpu** [comment]
Issue has disappeared with no changes to the system.

I ran memtest86 out of an abundance of caution and completed 4 passes with zero errors. Now moving onto Prime95 to test the CPU. I would be a bit surprised if either CPU or RAM were the problem though since this system has shown no other signs of instability, is not overclocked or undervolted, and has sensible temperatures. Maybe a cosmic ray bitflip? But I was able to previously reproduce even after closing and re-opening the program...

* Not non-ascii since I could previously reproduce with just the password '1111' on a freshly-created database.
* Tried on a different machine and unable to reproduce.
* Tried a locally-compiled build of 63b2394 with ASAN enabled and see nothing out of the ordinary.
* Tried with UBSAN enabled and see nothing out of the ordinary.
* Tried with TSAN enabled and while it does detect multiple data races, none of them seem to be in the key generation code.

I'm at a loss :shrug:

**Comment by jigpu** [comment]
...And just as mysteriously the issue has reappeared. System previously passed 9 hours each of Prime95 and y-cruncher without failure. Obviously that doesn't _prove_ stability (its not something that _can_ be proven, afterall) but it does make it seem less likely.

**Comment by mdberryh** [comment]
I have this issue with KeePassXC 2.7.6, but I use nextcloud to sync the file to other machines. I have 3 machines, but one is consistently failing to read the Yubikey (which is a hardware key)... the other machines one ubuntu and one windows have no issues. I was able to fix it temporarily by telling nextcloud to not sync the file and delete it on the machine then resync, but it wasn't long before the same problem came up.

**Comment by Foul** [comment]
happened to me this evening !!! 1st time.. I haven't changed any of my habits
(KDE Neon / Plasma 6.0.2) 

KeepassXC 2.7.7

**Comment by Asuka-Tech** [comment]
this issue started happening for me too, my cpu and ram are completely fine , now the funny thing , i have no issues with the desktop installed version , only if i try to use the portable version , ive tested the portable version on usb stick or on the same ssd as the desktop version, but the issue keeps appearing , it became very rare that i can open my database on the portable , meanwhile the desktop version has no issues at all.

**Comment by necrorika** [comment]
Me too ! This is ridiculous!
Here's what I've done:

I tried unlocking for 2 minutes straight and got the same thing over and over.

I've verified my keyfile works - that's out of the equation. Computer can't be the problem -- I've tried 3 computers. I tried the same version I've been using (2.6.6) and the newest version (2.77) on each. The app on my phone never worked.

I've tried multiple backups of the database on all 3 systems, none work.

Slight OC on one system, none on the others. I haven't tried alternate apps compatible with the KeePass DB yet. Interestingly while it does it to every single previous database I have any new ones I create I can't seem to replicate it.

I think I got incredibly unlucky and screwed here, even after making many more precautions than I thought necessary through backups.

**Comment by droidmonkey** [comment]
@necrorika you are absolutely typing in the wrong password in your case. 

> The app on my phone never worked.

That isn't KeePassXC

> I've tried multiple backups of the database on all 3 systems, none work.

classic sign of wrong password

**Comment by necrorika** [comment]
> @necrorika you are absolutely typing in the wrong password in your case.
> 
> > The app on my phone never worked.
> 
> That isn't KeePassXC
> 
> > I've tried multiple backups of the database on all 3 systems, none work.
> 
> classic sign of wrong password

No, I know it's 1000% correct.

**Comment by droidmonkey** [comment]
I have 20 issues on this board with people saying the same thing. They all come back later and admit their mistake.

**Comment by necrorika** [comment]
> I have 20 issues on this board with people saying the same thing. They all come back later and admit their mistake.

That's great for you, however I won't. I know the password is correct.

**Comment by droidmonkey** [comment]
> I've verified my keyfile works - that's out of the equation.

How could you possibly verify this? Could also be your problem here.

**Comment by necrorika** [comment]
> > I've verified my keyfile works - that's out of the equation.
> 
> How could you possibly verify this? Could also be your problem here.

Other applications that use it still work with it. I've also got backups of that file that have only been touched by keepass... 
Even if it was that one file how could all the backups be bad too ? It's not possible... it can't be.. they were stored safely, different drives and computers and even offsite. 

I don't mean to come off rude, I know I did. However the password is definitely right, I've verified that with the copy of it I have of the password

**Comment by droidmonkey** [comment]
No worries, I am often rude / rude 'sounding' 😄 

The problem is that KeePass databases don't randomly "lock out" or become inaccessible. This is especially true for properly stored backups. There are only two main reasons for a total lockout, one is bad RAM which you excluded by trying multiple different computers. The other is incorrect credentials.

**Comment by necrorika** [comment]
> No worries, I am often rude / rude 'sounding' 😄
> 
> The problem is that KeePass databases don't randomly "lock out" or become inaccessible. This is especially true for properly stored backups. There are only two main reasons for a total lockout, one is bad RAM which you excluded by trying multiple different computers. The other is incorrect credentials.

I didn't think they would until this happened.

 I just don't understand what is wrong.. I hope it'll just start working again like with jigpu. In any case out of an abundance of absolute need for resolution and eliminating possible contaminates I'll change my ram back to 32gb tomorrow. 80gb of ram wouldn't cause a problem, right? It's been memtested with multiple passes and runs stable since installation. I believe KeePass was working fine even after I upgraded it. Also trying multiple computers should eliminate that but I guess I can give it a shot.

As for backups I do them manually with the databases since I don't trust software to do it .. so that should be out of the picture too 

Everything else has seemingly been eliminated besides something like corruption but unless it corrupted all database copies I had I don't see that possible.

**Comment by phoerious** [comment]
Once a file is corrupted, it stays corrupted. So if you saved it on a machine with bad RAM, the file itself will be corrupted and you cannot open it on other machines either.
If, on the other hand, you can be sure that the file is fine, it's the credentials that are wrong (could be you mistyping/misremembering, wrong keyboard layout, capslock etc.)
A third possibility is that the file got corrupted at rest somewhere (not KeePassXC's doing, perhaps bit rot on your hard drive). Try opening an older version from a backup.

**Comment by PaoloPelloni** [comment]
I had the same issue between KeepassXC on my desktop and any app on mobile with the error despite the password/keyfile would open on the desktop. 
I regenerated both the DB and the keyfile (which is now 128 bytes and not 64 anymore) ans solved it.

**Comment by necrorika** [comment]
> I had the same issue between KeepassXC on my desktop and any app on mobile with the error despite the password/keyfile would open on the desktop. I regenerated both the DB and the keyfile (which is now 128 bytes and not 64 anymore) ans solved it.

How do you regenerate? You don't mean making a new one right?

**Comment by PaoloPelloni** [comment]
> How do you regenerate? You don't mean making a new one right?

Yes I actually created a new one. I noticed that the older was half the size, so maybe the issue was an outdated keyfile.

**Comment by necrorika** [comment]
> > How do you regenerate? You don't mean making a new one right?
> 
> Yes I actually created a new one. I noticed that the older was half the size, so maybe the issue was an outdated keyfile.

ah, yeah, that doesn't fix the problem if you're just creating a new database. Since everything is still stuck in the old one

**Comment by max0wn** [comment]
I've been using KeePassXC for almost 2 years, but a couple of months ago I got the same error for one of my databases. There's a really simple password, so I couldn't just forget it. Didn't try to figure it out in detail, but decided to compare the headers of my well-working database and corrupted one via hex dumps. I'm not sure, but I have some suspicions about modifying a database's header when a user is trying to get access using a password. I really doubt that it's faulty RAM or something close to hardware. It's possible, but I don't think it can be if your laptop is without damage and other applications work well as usual.

**Comment by jthiart-senec** [comment]
I had this problem once when I switched between Windows 11, where the password was accepted, and Ubuntu, where "^G" was automatically converted to "Ĝ". Pasting my password into a text editor, I immediately noticed the mistake. Same thing could happen to any number of accented characters and other shortcuts, I guess. Depends on your OS settings.

**Comment by necrorika** [comment]
> I had this problem once when I switched between Windows 11, where the password was accepted, and Ubuntu, where "^G" was automatically converted to "Ĝ". Pasting my password into a text editor, I immediately noticed the mistake. Same thing could happen to any number of accented characters and other shortcuts, I guess. Depends on your OS settings.

yeah, I tried copy pasting the password and unfortunately same result, still have this problem.

**Comment by droidmonkey** [comment]
@necrorika make sure if you use a key file that you are still using it and the correct one.

**Comment by domoZAM** [comment]
> > I had this problem once when I switched between Windows 11, where the password was accepted, and Ubuntu, where "^G" was automatically converted to "Ĝ". Pasting my password into a text editor, I immediately noticed the mistake. Same thing could happen to any number of accented characters and other shortcuts, I guess. Depends on your OS settings.
> 
> yeah, I tried copy pasting the password and unfortunately same result, still have this problem.

Same for me: i used this DB for months, everyday without problems, with the same password (without key file) this morning i had the same problem! I restore differents backup (December, November) but the problem remain... My pc seems to work well with the others apps (i don't think to be a ram problem) but i cannot access to my DB in Keepassxc...

**Comment by Egduf** [comment]
I know this is a known issue, I can't say if it is XC issue but I only use XC.

Because of this issue, of the kdbx randomly corrupting, I make backup copies of my kdbx file. 

I found this thread in hopes that there was a fix by now because it just happened to me again and yes the password was correct . 

Luckily I had a fairly recent backup and of course the password is the same (backup) and yes the password was correct .

I don't know what really causes this issue but it seems to happen when I shut my computer down or to sleep while I still had the kdbx file open and so I try to make it a habit to close kdbx before shutting the computer down.

I hope that this issue gets fixed as it is scary to lose access to your passwords, and I still prefer keepassXC over the others.

**Comment by droidmonkey** [comment]
Do you have unsaved changes all the time? Enable auto save and/or delayed saving in database settings. Behavior becomes undefined during shutdown, no guarantee the OS doesn't just kill the app.

**Comment by BenniBenassi** [comment]
I thought I'd comment here. I used FTP to transfer the file over to the other computer and had the same issue. This modified the file to a different hash the reason why this happens is that the files were not transferred in binary, but in ASCII mode, which in turn modifies the file. Downloading the file direct from my nextcloud server via the web resolved this one.

**Comment by digitaltrailbuilder** [comment]
hola aqui Alejandro de chile saludos a los creadores de la aplicacion, acabo de formatear mi pc , tenia guardado siempre el archivo de base de datos.kdbx en OneDrive (anterior al formateo del pc, siempre estuvo sincronizado y siempre funcionaba) , pero al volver instalar la misma version kepassxc  2.7.10 despues del format de mi pc (tenia guardado el mismo archivo setup) me da error al ingresar al archivo de base de datos por primera vez con mi password maestra , la clave esta bien introducida , alguien puede saber que pasa? el error es 'Error al leer la base de datos: Se han proporcionado credenciales inválidas, inténtelo de nuevo.
Si ocurre nuevamente entonces su archivo de base de datos puede estar corrupto. (HMAC no coincidente)'

**Comment by droidmonkey** [comment]
@alejsondro, sigue probando tu contraseña maestra. Debes estar escribiéndola mal. Intenta revelarla mientras la escribes.

**Comment by digitaltrailbuilder** [comment]
@droidmonkey gracias por responder amigo , la clave maestra fue usada por 2 años y se cual es, creo que debe ser otro problema.

El archivo de base de datos siempre estuvo en una carpeta la cual estaba sincronizada con ONE drive, mientras agregaba nuevas contraseñas ala base de datos el archivo siempre estuvo sincronizado, no había problemas , al volver instalar Windows 11 (versión distinta ala anterior 'mas nueva') y OneDrive , mi base de datos apareció nuevamente en la misma carpeta junto con todos mis archivos de trabajo , pero al tratar de abrirla con la clave que corresponde me dice que no se puede con un mensaje rojo.

Nunca genere un archivo clave anteriormente porque no sabia, y solo usaba mi base de datos.

Si alguien sabe que puede ser lo agradecería, aunque si puedo crear una nueva base de datos y agregar las contraseñas nuevamente tengo miedo que después nuevamente pierda todo al usar un nuevo Windows, quizás puede ser que el archivo queda corrupto al tenerlo sincronizado no lose , el programa es muy bueno ya que lo sincronice con la extensión de brave y a todos mis sitios web keypass me recordaba mis claves y funcionaba muy bien.

No quiero dejar de usarlo pero nunca espere que no reconociera mi clave maestra , usando la misma versión y el mismo archivo de base de datos.

Saludos a todos.

**Comment by droidmonkey** [comment]
I dont know your situation,  but you need to do some checks on your side. Try restoring a previous version of the database file within onedrive. Also make sure you do not have anything filled into the key file box (it should be hidden). There is really nothing we can do to solve the problem, and I 100% am sure this was not caused by windows install.

**Comment by digitaltrailbuilder** [comment]
@droidmonkey quería consultarte si es mejor trabajar con un 'archivo clave' junto al archivo de base de datos, para así no tener errores futuros?

y lo otro es preguntarte si es mejor tener el archivo de base de datos guardado en un directorio que no este sincronizado , como por ejemplo una pendrive? para evitar este tipo de errores futuros cuando sea necesario cambiar windows e instalar nuevamente keypass ..... saludos y gracias por tu tiempo

**Comment by droidmonkey** [comment]
No, a key file would not measure anything better, it increases your chances is these problems.

No, do not store your database on a thumb drive, that absolutely increases the chance of actual corruption.
