### ISSUE TITLE
the subfolder in *.zip assets makes deployment complicated

### ISSUE THREAD

**Issue by Micke3rd** [keepassxreboot/keepassxc#8814]
Packed asset files don't contain the application files but a additional "KeePassXC-xxx-yyy" folder.
e.g. file _"KeePassXC-2.7.4-Win64.zip"_  contains the sub folder _"KeePassXC-2.7.4-Win64"_.

Therefore it's not possible to deploy (unzip) to a folder with a self-chosen name. After unzip'ing you have to move the application files to your folder, delete the redundant subfolder etc.
A script is not straightforward, because on every new version this subfolder has a changed name.

The alternative, just to use the folder as it is, won't be the typical use case. Because with every new version all app links are broken.

Request:
Please pack *.zip assets without the redundant subfolder

**Comment by michaelk83** [comment]
For a script, you can:
- Use the archive filename minus the `.zip` extension.
- Use a regular expression. The only change should be the version number.
- Look for the newest folder/file.
- If you expand the zip to some other empty folder, then look for the only folder that will be created there.

**Comment by droidmonkey** [comment]
The portable version is absolutely not meant for automated deployments. This is a problem with cpack and nothing we can do to fix it without breaking our automated build process.
