### ISSUE TITLE
Thunderbird password window unrecognized in Ubuntu 22.04

### ISSUE THREAD

**Issue by DiagonalArg** [keepassxreboot/keepassxc#8815]
Keepassxc; v.2.7.4
Ubuntu 22.04

Thunderbird password window is not recognized by keepassxc.

Neither a regexp like:

//Password Required.*Mozilla Thunderbird//

nor using the dropdown to find the window title is working (the title doesn't appear - that window is not recognized).

I always worked with keepassx.

![image](https://user-images.githubusercontent.com/5190243/202837876-963f2a2c-f2a5-4ba0-a189-93d202a8a4e7.png)

**Comment by droidmonkey** [comment]
Are you using wayland

**Comment by DiagonalArg** [comment]
> Are you using wayland

I am, indeed.  It's default in 22.04.  Is that a problem?  Is there a workaround?

**Comment by droidmonkey** [comment]
You cannot use wayland and autotype. There is no workaround.

**Comment by DiagonalArg** [comment]
@droidmonkey / Why is it working in my browser then?

**Comment by droidmonkey** [comment]
Your browser must be running under x11 via xwayland

**Comment by DiagonalArg** [comment]
@droidmonkey / thanks, that makes sense.

Should I be sticking with X permanently?  Or will keepassxc at some point be updated for wayland?  I'm wondering if when Wayland takes over, I'm going to have to consider alternatives.

**Comment by droidmonkey** [comment]
Wayland does not have the protocols required to support Auto-Type. There is a huge thread discussing this on the issue board.
