### ISSUE TITLE
Auto-type not working on Firefox on Fedora 37?

### ISSUE THREAD

**Issue by D10f** [keepassxreboot/keepassxc#8816]
## Overview
Auto-type does not work on Firefox running on Fedora 37.

## Steps to Reproduce
1. Install Fedora 37.
2. Install KeePassXC.
3. Attempt to use auto-type using assigned global keyboard shortcut (eg Ctrl+Shift+A).
4. Attempt to use auto-type using entry-level keyboard shortcut (Ctrl+Shift+V).

## Expected Behavior
Auto-type should work on all windows, including Firefox.

## Actual Behavior
Auto-type does not work on Firefox.

## Context
I recently switched to Fedora 37, and setup the system very similar to what I had previously running PopOS 22.04. There I could use KeePassXC on any browser and it would work fine, but not now in Fedora 37. At first I thought it was something with the imported profile but even on a clean Firefox install this doesn't work. Other browsers like Brave and even Librewolf, a fork of Firefox, work without any issues.

## Debug Info
KeePassXC - Version 2.7.4
Revision: 63b2394

Qt 5.15.7
Debugging mode is disabled.

Operating system: Fedora Linux 37 (Workstation Edition)
CPU architecture: x86_64
Kernel: linux 6.0.8-300.fc37.x86_64

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.19.1

## Additional Information
Operating System: Linux
Desktop Env: Gnome
Windowing System: Wayland

**Comment by droidmonkey** [comment]
Firefox is likely running under wayland, you must run everything under x11

**Comment by matnsc** [comment]
I have the same issue in Fedora 37 wayland session in all windows.
Any chance of Auto-Type working with Wayland in the future?
