### ISSUE TITLE
ssh keys stored in KeepassXC were not added on macos, unless keepassxc 2.7.1 used

### ISSUE THREAD

**Issue by hikarikumo** [keepassxreboot/keepassxc#8817]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
ssh keys stored in KeepassXC were not added on macos, unless keepassxc 2.7.1 used

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Install keepassxc 2.7.4 or 2.7.3
2. open keepassxc database with ssh-keys as attachments 
3. nothing in 'ssh-add -l'

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
expected to see ssh public keys on ssh-agent

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
no ssh-keys were added using keepassxc 2.7.4 or 2.7.3

## Context
[NOTE]: # ( Give us any additional information you may have. )
ssh keys stored in KeepassXC were not added on macos, unless keepassxc 2.7.1 used

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows/Linux/macOS
Desktop Env: Gnome/KDE/XFCE/Mate/Cinnamon
Windowing System: X11/Wayland

**Comment by droidmonkey** [comment]
Pretty sure ssh code wasn't touched after 2.7.1 besides a minor fix for windows specific builds. Make sure you are not running ssh agent in a separate environment.

**Comment by hikarikumo** [comment]
I was wrong blaming the version. 
In fact the ssh-keys were not added if KeepassXC was launched as common app. 
However, when I launch it directly using shell command:
`/Applications/KeePassXC.app/Contents/MacOS/KeePassXC`

I've got ssh-keys installed into ssh-agent.
What can be checked?

**Comment by droidmonkey** [comment]
You should define the ssh socket environment variable to point to the place where your ssh-add is looking.

**Comment by droidmonkey** [comment]
https://keepassxc.org/docs/KeePassXC_UserGuide.html#_setting_up_ssh_agent_integration

**Comment by hikarikumo** [comment]
I have checked the ssh socket availability from the scratch - it always showed like everything was correct

For example: 
Current successful state
╰─❯ ssh-add -l
3072 SHA256:6x3RZzb6nZLFnhLVttQmpAC2hsdghtLPbg7Urryqar4 hikari@MacBook-Air-Vladimir.local (RSA)
4096 SHA256:8WDoeE76RFRF7yJz90OU3TRnoG3htOOjI8xymEiHaeg vladimir@svetozar.space (RSA)
256 SHA256:FZsXGJMa2rV7qTXh056Fm/eRZCf6vUUHtQPw277bMFk vladimir.vasilenko@exness.com (ED25519)
3072 SHA256:gn5KakOCNzxWYBmOKKJFCSGf1o0zLwDiOCMEOLFM1GY vladimir.vasilenko@exness.com (RSA)
![image](https://user-images.githubusercontent.com/69415538/202858380-096cdbe4-824f-42d0-98ba-74528942b8c7.png)

Default launch:

╭─ ~                                                                                                                                                                                                                   venv-netdev-3.9
╰─❯ ssh-add -l
The agent has no identities.

![image](https://user-images.githubusercontent.com/69415538/202860814-fc27ba7b-2c2a-451f-9092-691c70270e95.png)

**Comment by droidmonkey** [comment]
Have you tried adding keys manually from the right click menu in keepassxc?

**Comment by hikarikumo** [comment]
I can try to override - but I don't know what are the correct parameters to insert there

**Comment by hikarikumo** [comment]
In case of KeepassXC launched at startup 
the SSH_AUTH_SOCK value is:
`/private/tmp/com.apple.launchd.MiBgJMtqkz/Listeners`
which shows OK - agent is connected, but no ssh keys added

in case KeepassXC launched from CLI: 
`/Applications/KeePassXC.app/Contents/MacOS/KeePassXC`
the SSH_AUTH_SOCK value is:
`/var/folders/kg/cjmc6pwd0hq0hwxkb25nvc3w0000gn/T//ssh-RwyhA1Mh0u9q/agent.854`
which shows OK and ssh-keys appears - but this value is dynamic and changes with every reboot

**Comment by droidmonkey** [comment]
Yah you need to fix how your ssh agent is launched because it is putting the socket in an isolated location specific to your terminal instance.

**Comment by hikarikumo** [comment]
Please give me a hint where I can change that
Thank you

**Comment by droidmonkey** [comment]
Bringing in @hifi

**Comment by hifi** [comment]
It looks like there's a separate process/program that's launched that overrides the default launchd controlled socket and you have two different agent implementations running.

On macOS the launchd controlled socket is the "correct" one from what I've gathered. If the number after the socket name is the PID of the secondary agent you should check what that process is and find out why it's being started.

**Comment by hikarikumo** [comment]
Hello @droidmonkey and @hifi !
Highly appreciate your replies. I've found second launch of ssh-agent because 'om my zsh' plugin ssh-agent was in enabled state.
Now everything is up and running.
Have a nice week!
Best regards
