### ISSUE TITLE
"Allow in background" Login items in macOS Ventura, change name

### ISSUE THREAD

**Issue by brainbaking** [keepassxreboot/keepassxc#8818]
## Overview

In the "Login Items" settings pane of System Preferences on macOS Ventura, there's a list of apps that you can allow or disallow to run in the background to perform tasks such as updates. There's one called "**Janek Bevendorff**" on my list. I had to search on the internet for this name to find out that it's one of the KeePass creators, and I _hope_ it's legit. 

I presume it is at least possible to change the name (and hopefully also the icon) there because it is very confusing and could lead to me blocking the app since it looks like something unauthorized is installed without my knowledge. See screenshot.

<img width="733" alt="Screenshot 2022-11-19 at 16 01 16" src="https://user-images.githubusercontent.com/304593/202857352-94154bce-de77-4b76-b4d2-1a4334dc76f8.png">

## Steps to Reproduce

Install KeePass on macOS Ventura and give it all the rights it requires to automatically search for updates.

## Expected Behavior

Find "KeePassXC" with the correct green key icon in the list of login items in the system preferences. 

## Actual Behavior

Find a suspicious item called "Janek Bevendorff" in the list without an icon.

[NOTE]: # ( Paste debug info from Help → About here )

KeePassXC - Version 2.7.1
Revision: 5916a8f

Qt 5.15.2
Debugging mode is disabled.

Operating system: macOS 13.0
CPU architecture: arm64
Kernel: darwin 22.1.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 2.19.1

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS Ventura

**Comment by brainbaking** [comment]
I have updated to KeePassXC 2.7.4 and the issue persists.
Thanks!

**Comment by droidmonkey** [comment]
> Find a suspicious item called "Janek Bevendorff" in the list without an icon.

Welcome to dumb Ventura where macOS can't figure out how to use the actual app name and icon unless it's installed by the store. There is nothing we can do to fix this at this time.

**Comment by brainbaking** [comment]
> > Find a suspicious item called "Janek Bevendorff" in the list without an icon.
> 
> Welcome to dumb Ventura where macOS can't figure out how to use the actual app name and icon unless it's installed by the store. There is nothing we can do to fix this at this time.

Thanks for your reply! Yeah I've had several issues with the new OS... 
"Unless it's installed by the store" is incorrect. I've installed Rectangle and Wireshark directly without the app store and both icons/names appear on the list correctly.

I do wonder where the current name comes from though.

**Comment by droidmonkey** [comment]
The only place I can find @phoerious name is in the embedded.provisionprofile file which I believe is generated when the application is signed.

![image](https://user-images.githubusercontent.com/2809491/202909368-a2c29c2a-348a-4bc5-8d17-28ec4e670472.png)

This might not be correctable unless @phoerious changes his signing key to use the KeePassXC Team name.

I still think this is a Ventura bug because they should be using the "Application Name" not the "Team Name"

**Comment by phoerious** [comment]
This is new in Ventura and affects many other apps besides KeePassXC. There are many other apps that are signed by individuals which show their personal names now (and no proper icon). The only way to rectify this is to somehow get an organisation certificate for KeePassXC instead of my personal developer ID. I also think Apple is to blame here by only showing the name without linking to the application itself.

**Comment by DJFriar** [comment]
I concur that his is more of an Apple side bug since why would any user need to know the Team Name? And the fact that some entries will say "2 Items" with no indication what they are (for example, Steam Deck and Camera Hub are both by Elgato but both show up as Corsair Memory, Inc.).

**Comment by nodeful** [comment]
Add this to your LaunchDaemon plist:
```
<key>AssociatedBundleIdentifiers</key>
<string>com.company.app</string>
```
the bundle id should point to your main app and then it will be picked up by the Login Items settings with proper name and icon.

**Comment by JensRantil** [comment]
FYI, I just had this happen to me in keepassxc 2.7.9 when I enabled "Automatically launch KeePassXC at system startup". I got a hickup when I saw this random name show up in my list of apps starting - and thought I actually had some kind of malware for a brief second. Not nice.
