### ISSUE TITLE
Yubi Key Support for version 2.7.4

### ISSUE THREAD

**Issue by sbuege** [keepassxreboot/keepassxc#8819]
## Summary
I'm using keepassxc under Linux Arch. The current  version is 2.7.4. I want to protect my database with a hardware token.
I'm using a YubiKey 5C NFC. 
When I try to create a new database and add a hardware it failed, because the Yubik is not detected.

**Comment by droidmonkey** [comment]
Make sure you have configured a slot for challenge response. If you are running the snap version you need to give the raw usb permission. Read our faq for more information. https://keepassxc.org/docs/#faq-yubikey-2fa
