### ISSUE TITLE
Auto-type for only password or user name individually

### ISSUE THREAD

**Issue by ygoe** [keepassxreboot/keepassxc#8820]
## Summary
Auto-type can only type the entry data following a fixed pattern. This pattern can be defined globally or per entry. (I guess that's true, coming from Keepass and just exploring KeepassXC.)

The problem is that this never responds to what an application or website wants to see right now. Traditionally, login forms could be filled out with the sequence "user name [tab] password [enter]". Modern login forms increasingly want only one of these. There's a form for only the user name. Or the e-mail address (even though you have a user name there). After submitting this, the app thinks about it and presents you a form that only wants the password. It's impossible to use global auto-type here. You have to open Keepass, locate the relevant entry and copy texts via clipboard (which is less secure).

Some login forms are even really nasty and show a name and password field, but as soon as you leave the name field, they take away the password field and change the form into a split fields form. This sucks. Typing blindly (or with a tool like Keepass) results in typing the password anywhere into nowhere.

## Examples
The auto-type selection dialog should offer the option what to type:

* The default sequence for this entry
* Only the user name
* Only the password
* Only the TOTP
* Only a custom field (like the e-mail address)

When invoking the auto-type again, a recently selected entry should still be active. Sometimes, login forms don't set a usable window title so automatic selection isn't always possible. This might especially be true on later stages of the multiform process.

## Context
Not unique, everybody has this problem.

**Comment by droidmonkey** [comment]
> It's impossible to use global auto-type here.

Not true. Please read our user guide to learn how to use all the features of our Auto-Type. 

Everything you mentioned here is possible with our interface. Make sure you are running version 2.7.4.
