### ISSUE TITLE
Support for multi password account in the interface

### ISSUE THREAD

**Issue by cain-dev** [keepassxreboot/keepassxc#8822]
## Summary
By default, there is only 1 password field per account on the interface. I think it would be a nice option to have multi password support.

## Examples
Instear of a field like we have now:
Password: [                                             ] [generate password] [show password]
 Just add a plus icon and a option to put more password fields, like:
Password: [                                             ] [generate password] [show password] **[add another password field]**
and then:
Password**1**: [                                             ] [generate password] [show password] **[add another password field]**
Password**2**: [                                             ] [generate password] [show password] **[add another password field]**

And on the top instead of:
[copy username] [copy password]

Change it to:
[copy username] **[copy password1] [copy password2]**
## Context
This feature matters for me 'cause i have to keep saving and copying extra notes or extra atributes when i try to log in in multiple passwords accounts.

**Comment by droidmonkey** [comment]
We won't support this, it overly complicated the user interface for an edge case. Either use advanced attributes or use cloned entries.
