### ISSUE TITLE
UI, Renaming button for attachments from preview is grey

### ISSUE THREAD

**Issue by Algoritter** [keepassxreboot/keepassxc#8823]
## Overview
Rename Button is not working for attachments from the preview.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Make new entry
2. Create a file on desktop with name: template.txt
3. Attach it and click ok.
4. From the Preview, left-click the documents once and try to rename the file by clicking the rename button.

## Hints
There are 3 buttons in the preview: rename open and safe.
There are 5 buttons in when the key is opened under tab advanced.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
The name highlights and I am able to give the file a new name.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
The button is greyed out. Nothing happens.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION 2.7.4

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 11 , 22H2

**Comment by droidmonkey** [comment]
I have a fix ready for pr
