### ISSUE TITLE
Please made a Dark Mode GUI für Mac

### ISSUE THREAD

**Issue by BinhDiez64** [keepassxreboot/keepassxc#8824]
Ich bin stark sehbehindert und komme mit dem weißen Hintergrund nicht mehr zurecht.
Bitte integrieren Sie den Dunkelmodus (dark mode) in keepassxc für Mac OSX.
Alles andere funktioniert sehr gut.

**Comment by phoerious** [comment]
We already have a dark mode. You can enable it under "View->Theme". By default, it will follow your system theme.

**Comment by BinhDiez64** [comment]
Thank you for the fast answer, after updating to the new version 274  I have also the dark mode.

—
Mit freundlichen Grüßen
Binh Diez

Diese Nachricht wurde diktiert. Fehler bitte ich zu entschuldigen.
________________________________
Von: Janek Bevendorff ***@***.***>
Gesendet: Monday, November 21, 2022 9:05:35 AM
An: keepassxreboot/keepassxc ***@***.***>
Cc: BinhDiez64 ***@***.***>; Author ***@***.***>
Betreff: Re: [keepassxreboot/keepassxc] Please made a Dark Mode GUI für Mac (Issue #8824)


Closed #8824<https://github.com/keepassxreboot/keepassxc/issues/8824> as not planned.
