### ISSUE TITLE
How do I use the dbus interface securely?

### ISSUE THREAD

**Issue by GenericNerdyUsername** [keepassxreboot/keepassxc#8826]
[Here,](https://github.com/keepassxreboot/keepassxc/wiki/Using-DBus-with-KeePassXC) it shows how to use dbus to unlock a database. Using this method, however, I can find the password sent using `dbus-monitor`. Am I doing something wrong? Or does KPXC not have support for encrypted dbus or some other (secure) method of opening a database for the GUI from the command line?

**Comment by droidmonkey** [comment]
No support, dbus is not a recommended way to unlock your database if you don't want your password to be accessible.

**Comment by GenericNerdyUsername** [comment]
Then how would I unlock the database in the gui from the command line?

**Comment by droidmonkey** [comment]
This is documented in the user guide.

**Comment by GenericNerdyUsername** [comment]
`keepassxc --pw-stdin db.kdbx` doesn't work if an instance is already running, if that's what you're talking about

**Comment by droidmonkey** [comment]
Make sure you are running 2.7.4

**Comment by GenericNerdyUsername** [comment]
```
KeePassXC - Version 2.7.4

Qt 5.15.7
Debugging mode is disabled.

Operating system: NixOS 22.11 (Raccoon)
CPU architecture: x86_64
Kernel: linux 6.0.9

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.19.2
```

`keepassxc --pw-stdin db.kdbx` gives `Another instance of KeePassXC is already running.`

Running multiple instances of kp isn't viable for my use case, as they interfere with each other trying to provide the `freedesktop.org secret service`.

**Comment by droidmonkey** [comment]
Hmmm good point we don't send the credentials to the running instance.

**Comment by GenericNerdyUsername** [comment]
Im not at all familiar with the codebase, how difficult would it be to add diffie hellman to the dbus interface for secrets? If that isn't feasible, whats the alternative?

**Comment by droidmonkey** [comment]
We use that for the secret service feature.
