### ISSUE TITLE
Load previously opened database only works after a 'proper' quitting of keepassxc

### ISSUE THREAD

**Issue by Leleat** [keepassxreboot/keepassxc#8827]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

On a fresh install of keepassxc (and my system) keepassxc doesn't seem to remember the opened database even though the setting is checked. I need use the 'quit' action in the menu bar at least once for keepassxc to properly open the database the subsequent times keepassxc is opened. (I am pretty sure I've run into this issue whenever I've reinstalled my system... and I always end up forgetting about how to 'fix' it 😅)

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Fresh install of keepassxc
2. Open a database
3. Restart your system
4. Open keepassxc

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

The previously opened database is immediately opened in keepassxc.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

You end up on the welcome screen with the database only listed in the `Recent Databases` list but not actually opened.

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.4
Revision: 63b2394
Distribution: Flatpak

[NOTE]: # ( Pick choices based on your environment )
Operating System: Fedora 37
Desktop Env: Gnome
Windowing System: Wayland

**Comment by droidmonkey** [comment]
This would imply your system is forcefully quiting  keepassxc when you do your reboot. (ie basically causing a crash)

**Comment by Leleat** [comment]
Hmm, I tried to reproduce this in a VM now and I can't... so I'll open a new issue if I have clear STR.
