### ISSUE TITLE
Font of "Enter Password:" field has changed in the 2.7.4 version

### ISSUE THREAD

**Issue by 0xShree** [keepassxreboot/keepassxc#8828]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
In the **lastest 2.7.4** version, the **Entry Password:** field font has changed. Below screenshots is comparison between **2.7.4 & 2.7.1**
I was adjusted to the previous font 👀and don't know whether it is intended

![ksnip_20221122-094405](https://user-images.githubusercontent.com/49250702/203221209-91da5654-f3a2-4508-bfd1-7cfbc77ae577.png)
**2.7.4**

![ksnip_20221122-094336](https://user-images.githubusercontent.com/49250702/203221213-29e4b335-70e4-42df-b5af-22d0a2bb8cf8.png)
**2.7.1**

## Context
KeePassXC - Version 2.7.4
Revision: 63b2394

Qt 5.15.7
Debugging mode is disabled.

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 6.0.9-arch1-1

**Comment by varjolintu** [comment]
Already fixed in: https://github.com/keepassxreboot/keepassxc/pull/8732

**Comment by 0xShree** [comment]
Oh okay thanks for the info
