### ISSUE TITLE
+ (plus) in auto-type is written out instead of making it shift

### ISSUE THREAD

**Issue by PhoenixIV** [keepassxreboot/keepassxc#8833]
I have an autotype sequence that is making use of
`{S:Custom field}+{TAB}`

**Expected result:**
Content is typed, then a "backwards field shift" (shift + tab) is performed

**Actual result:**
Content is typed, followed by the symbol "+" at the end of the field, then a forward shift (tab) is performed.

**Additional comment:**
I wonder if this might anyhow be related to https://github.com/keepassxreboot/keepassxc/issues/7610
as `^` (Ctrl) and `%` (Alt) are special commands for auto type as well: https://keepass.info/help/base/autotype.html

## Debug info:

KeePassXC - **Version 2.4.3**
Revision: 5d6ef0c

Qt 5.12.8
Debugging mode is disabled.

Operating system: **Linux Mint 20.2**
CPU architecture: x86_64
Kernel: linux 5.4.0-131-generic

Enabled extensions:
- Auto-Type
- Browser-Integration
- SSH-Agent
- KeeShare (only unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.5

**Comment by droidmonkey** [comment]
Update to 2.7.4 you are extremely out of date

**Comment by PhoenixIV** [comment]
I took it out of the official Mint Repo with that version as recent. I am not that deep into Linux yet tbh.

**Comment by droidmonkey** [comment]
https://keepassxc.org/download

You really should run the latest version of Mint if you are just starting.
