### ISSUE TITLE
CTRL+V discontinuous on Wayland KDE Plasma DE

### ISSUE THREAD

**Issue by gianlucavagnuzzi** [keepassxreboot/keepassxc#8836]
## Overview
This bug is discontinuous.

## Steps to Reproduce
1. open any record 
2. CTRL-V any caracter in any field

## Expected Behavior
paste clipboard content

## Actual Behavior
doesn't paste anything

## Context
if i lock and unlock db, then paste OK!

KeePassXC - VERSION 2.7.4
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: KDE Plasma
Windowing System: Wayland

**Comment by droidmonkey** [comment]
This is a qwayland bug, it has been posted before. There is nothing we can do to fix it.
