### ISSUE TITLE
Feature request: custom font size

### ISSUE THREAD

**Issue by miller7777777** [keepassxreboot/keepassxc#8837]
## Summary
Please, add an ability to change font size for notes. Thanks!

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )

**Comment by tredondo** [comment]
This is a duplicate of #6822, showing how much demand there is for increasing the font size.

**Comment by vkuznet** [comment]
+1
