### ISSUE TITLE
Intermittent incorrect font scaling in context submenus on multi-monitors w/ mixed scaling

### ISSUE THREAD

**Issue by bmcdonnell** [keepassxreboot/keepassxc#8838]
## Overview
In a multi display setup, with different scaling on some displays, some of the context sub-menus can enlarge their fonts are too big to fit in the allotted space.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Have at least 2 displays.
2. Set at least 1 display to a scaling that differs from the others (e.g. 100%, 200% as in screenshots below).
3. Open KeePassXC on the 100% display.
4. Open a database.
5. Right click an entry; mouse over to expand various context submenus. Observe incorrect scaling of submenu options (sometimes/often).
6. Move KeePassXC to the 200% display.
7. Right click an entry; mouse over to expand various context submenus. Observe consistently *correct* scaling of submenu options.

One display:

![image](https://user-images.githubusercontent.com/35789100/204023439-1cad14ff-6076-43bf-8bd1-0456cc4bd244.png)

The other display:

![image](https://user-images.githubusercontent.com/35789100/204023549-aab650a7-01fd-4cdd-8bbc-c996822fc4c7.png)

## Expected Behavior
Consistent physical font size of all options and sub options on all displays.

As from the 200% display:

![image](https://user-images.githubusercontent.com/35789100/204025140-eaae8d7a-def5-4c7a-9def-4cc1fe15cfdd.png)

![image](https://user-images.githubusercontent.com/35789100/204024478-073f73b5-30b9-4eaf-b197-d85e198d74cd.png)

![image](https://user-images.githubusercontent.com/35789100/204025270-90b0113d-2bbf-459d-8790-4d97adb9b315.png)

## Actual Behavior
Sub-options too big / don't fit (sometimes/often).

As from the 100% display:

![image](https://user-images.githubusercontent.com/35789100/204025480-45be497e-8a90-4185-b282-c9246a8ac098.png)

![image](https://user-images.githubusercontent.com/35789100/204025704-16a9026e-0b41-4c8d-9d4d-973540f0db4b.png)

![image](https://user-images.githubusercontent.com/35789100/204025773-ba798504-bed5-42ff-a70b-261203f53586.png)

## Context
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.4
Revision: 63b2394

Qt 5.15.6
Debugging mode is disabled.

Operating system: Windows 10 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.19045

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 2.19.1

**Comment by droidmonkey** [comment]
This would be a qt bug, we have no control over actual scaling of elements in menus. You can report this over at https://bugreports.qt.io

You can also try manually defining the scaling parameters using the qt high dpi environment variables. See our user guide for more information.

**Comment by bmcdonnell** [comment]
Reported here:
https://bugreports.qt.io/browse/QTBUG-108905
