### ISSUE TITLE
Weird blank character on additionnal urls

### ISSUE THREAD

**Issue by kud** [keepassxreboot/keepassxc#8845]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

A weird character appears on new url item in Browser integration

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Go to an entry
2. Go to Browser integration
3. Add a new entry

## Expected Behavior
No weird blank square

## Actual Behavior
A weird blank square appears

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.4
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS

**Comment by droidmonkey** [comment]
What language is your interface set to?

**Comment by kud** [comment]
@droidmonkey System default so en_GB.

I can't do any screenshot as the application is protected.

**Comment by droidmonkey** [comment]
I cannot reproduce this at all:
![image](https://user-images.githubusercontent.com/2809491/205445255-b7ed9fb0-a3c3-4644-900d-97ddd092bfbb.png)

This is in English (United Kingdom) language

**Comment by kud** [comment]
https://user-images.githubusercontent.com/655838/205445762-90fd7bef-9381-49d6-a650-ac02c65de291.mp4

**Comment by kud** [comment]
Here is a video of the bug.

**Comment by droidmonkey** [comment]
That isn't a character it is the edit view of the input. There is no bug here.
