### ISSUE TITLE
Can not create correct kbdx file in cloud storage

### ISSUE THREAD

**Issue by ZONGMENG-kaito** [keepassxreboot/keepassxc#8846]
## Overview
I am using keepassXC and the personal kbdx file is stored in the local google drive mount, but when I change the content of one item, google drive will get a new file with a random suffix

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. modify any item and observe the google drive

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Can have the latest merged personal kbdx file.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
It will create a new file for each time modification.

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.4
Revision: 63b2394

Qt 5.15.6
Debugging mode is disabled.

Operating system: macOS 13.0
CPU architecture: x86_64
Kernel: darwin 22.1.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 2.19.2

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS, Version 13.0 (22A380)
---
 Google Drive version: Google Drive
Version: 66.0.3.0 (Intel)
---
<img width="556" alt="Screenshot 2022-11-27 at 23 06 43" src="https://user-images.githubusercontent.com/119031446/204142318-39359c07-efdd-4a80-b0bd-b7b22265a57f.png">

**Comment by droidmonkey** [comment]
Go to application settings and setup one of the alternate saving methods. Read the user guide for more information.
