### ISSUE TITLE
Cannot open my database anymore on Mac

### ISSUE THREAD

**Issue by fernandodlcruz** [keepassxreboot/keepassxc#8847]
## Overview
I updated my keepass to the 2.7.4 version and cannot open my database anymore.

## Steps to Reproduce
1. Upgrade to version 2.7.4 
2. Open old database and key file

## Expected Behavior
To open the databse

## Actual Behavior
Throws an error message:

"WARNING: You are using an old key file format which KeePassXC may
stop supporting in the future.

Please consider generating a new key file.
Error while reading the database: Invalid credentials were provided, please try again.
If this reoccurs, then your database file may be corrupt."

## Context
Never updated the key file. Previous updates never asked to do that.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.4
Revision: 63b2394

Qt 5.15.6
Debugging mode is disabled.

Operating system: macOS 13.0
CPU architecture: x86_64
Kernel: darwin 22.1.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 2.19.2

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS
Desktop Env: Venture 13.0.1

**Comment by droidmonkey** [comment]
Either your key file is corrupt or you are typing the wrong password. 

Download any release version you want here: https://github.com/keepassxreboot/keepassxc/releases
