### ISSUE TITLE
check serial of hardware key

### ISSUE THREAD

**Issue by Subnum12** [keepassxreboot/keepassxc#8850]
Let's say you have multiple hardware keys with same single secret for encrypting the database. 

You will be able to open the database with all keys. However in difference to the documentation ([see FAQ](https://keepassxc.org/docs/#faq-yubikey-multiple-yubikeys)) you cannot really use multiple hardware keys. 

If you going to save a database and if that serial differs from the one initially used to setup the database file
you will get an error for invalid sn (for no reason).

I expect somehow you need to identify the key using for encryption the database file as there can be multiple keys available, may with different secret. I would prefer to remember the sn used to open a database instead of the sn used to setup a database. Actually there is no need at all to keep that information in database file.

**Comment by droidmonkey** [comment]
You cannot swap keys with an unlocked database, but you can use any valid key to unlock the database. This will not change otherwise you would risk inadvertently changing the key for the database. We have no way of telling if a key is a valid key to unlock a database without actually unlocking it.

**Comment by Subnum12** [comment]
No, I do not want to swap the key of course. As mentioned above all hardware keys have same secret. 
I want to remove the serial from the database file.

>We have no way of telling if a key is a valid key to unlock a database without actually unlocking it.

Exactly, so why not remember the hardware serial number of the key used to **unlock** the database instead  of saving the serial used to setup the database?

**Comment by droidmonkey** [comment]
The serial is not stored in the database. We so exactly as you describe, we remember the serial of the key used to unlock the database to prevent inadvertent key swaps or when more than one key is plugged in.
