### ISSUE TITLE
Ubuntu AppImage Remembers Key File History

### ISSUE THREAD

**Issue by ideregbi** [keepassxreboot/keepassxc#8851]
## Overview
Version 2.7.4 AppImage remember Key File location history. 

## Steps to Reproduce
1. Open database
2. Click "Browse" in the Key File field
3. Click the dropdown in "Look In:" file location
4. Dropdown lists directory and folder where Key File exists from previous use

## Expected Behavior
KeePassXC does not remember Key File location history

KeePassXC - 2.7.4 AppImage
Operating System: Linux
Desktop Env: Ubuntu 18.04

**Comment by droidmonkey** [comment]
We can't control that, it is a feature of your desktop environment.
