### ISSUE TITLE
Hardware key timeout when opening database made in KeePass2

### ISSUE THREAD

**Issue by LukaszRemkowicz** [keepassxreboot/keepassxc#8853]
## Overview
When importing DB created in keepas 2.52, and using yubikey with challenge-response, I'm getting error:
```Error while reading the database: Unable to issue challenge-response: USB: Hardware key timed out waiting for user interaction.```

## Steps to Reproduce
1.  Open existing db with extension kdbx
2.  Use Hardware key --> yubikey with challenge-response (pushing the key not required).
3.  Try to unclock db

## Expected Behavior
I expect to open my DB created in keepas ver. 2.52

## Actual Behavior
Getting error: 
```Error while reading the database: Unable to issue challenge-response: USB: Hardware key timed out waiting for user interaction.```

KeePassXC - Version 2.7.4
Revision: 63b2394

Qt 5.15.6
Debugging mode is disabled.

Operating system: Windows 10 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.19044

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 2.19.1

**Comment by droidmonkey** [comment]
That means the slot you selected requires user interaction (push). Although we recommend you remove the yubikey protection within keepass (since it's provided by a third party plugin) and then reapply it using keepassxc after your unlock the database.

**Comment by LukaszRemkowicz** [comment]
Thank you for response, I will do what you wrote. Anyway, my challenge-response is not set on finger push.
