### ISSUE TITLE
Right Click / Context Menu not working in 3rd Monitor

### ISSUE THREAD

**Issue by alpex8** [keepassxreboot/keepassxc#8854]
## Overview
[TIP]:  # No Context Menu is visible at certain screens
[NOTE]: # When keepassxc is running for some time with an open database the context menu is not rendered on all screens

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Setup a multi monitor (at least three) Gnome Linux Desktop
2. Use Wayland as Window System
3. Open a Keepass Database
4. Do some other stuff a the issue does not occur at the beginning
5. Move the Keepassxc Window around all Monitors and try to open the Context Menu by clicking the right mouse button

## Expected Behavior
[NOTE]: # The Context Menu should open

## Actual Behavior
[NOTE]: # The context menu is hidden, but it´s state is seems to be present as I need to 'close' it before I can perform further actions.

## Context
[NOTE]: # I´m using Manjaro with Gnome and Wayland

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.4
Revision: 63b2394

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: Gnome
Windowing System: Wayland

**Comment by droidmonkey** [comment]
Make sure you have properly set the qt high dpi variables (see our user guide) specifically the one that defines scaling per monitor. I am going to guess your third monitor is not the same scale / resolution as the other two. 

Fwiw, this is a qt problem and not a keepassxc problem

**Comment by alpex8** [comment]
Thanks for the hint. I´m going to try that out.

As of now I can say that both monitors are wired via Display Port, are the same type and model (Samsung LC27F398FWUXEN), are set to the same resolution, have the same display settings, and do not have scaling (gnome display settings) applied. 

btw: The third monitor is the main notebook screen which is not affected by the issue.

**Comment by droidmonkey** [comment]
There is also a qt bug when the window is dragged to edge between two monitors the right click menu won't work properly.

**Comment by q234rty** [comment]
I assume this is related to https://bugreports.qt.io/browse/QTBUG-85297 which has been fixed in https://invent.kde.org/qt/qt/qtwayland/-/commit/aed15df34710dd5f95f7993e1a1892ee41b5661b which is included in qt5-wayland-5.15.7+kde+r55 in manjaro testing, but hasn't hit manjaro stable yet?

**Comment by alpex8** [comment]
qt5-wayland 5.15.7+kde+r55-1 is available in manjaro stable. I updated yesterday. I´ll check that out, but anyway I think this issue is not related to keepassxc and I will close the issue.
