### ISSUE TITLE
2.7.3 and 2.7.4 completely ignore Qt/Window manager colour schema

### ISSUE THREAD

**Issue by e-pirate** [keepassxreboot/keepassxc#8855]
## Overview
After updating from 2.7.1-r1 to 2.7.3 and later 2.7.4 I found that keepassxc now ignores Qt/Window manager colour schema. Having dark brown for ages now I have to deal with very bright blazing keepassxc's window. Downgrading back to 2.7.1-r1 make keepassxc respect colour schema again. qbittorrent  build against same Qt 5.15.5 respects colour schema.

## Steps to Reproduce
Update from 2.7.1-r1 to 2.7.3 or 2.7.4

## Expected Behavior
keepassxc window have same colour schema as all other windows

## Actual Behavior
keepassxc window is white

## Context
Gentoo Linux actual, dev-qt/qtcore-5.15.5-r3, dark breeze window decoration with dark custom colour schema
Desktop Env: KDE

**Comment by e-pirate** [comment]
Now a bug. You now have to manually select schema and decoration under View menu point. Switching to "dark" make in work as expected.

**Comment by e-pirate** [comment]
Now a bug. You now have to manually select schema and decoration under View menu point. Switching to "dark" make in work as expected.

**Comment by j-lakeman** [comment]
I'm experiencing the same issue with Debian Linux. Except I'm using a shell extension to switch between light and dark mode depending on sunrise and -set. The “automatic” theme setting does not work reliably.
@e-pirate why did you close the issue?

**Comment by e-pirate** [comment]
@J-Lakeman Since I use "dark" all the time I just switched to dark manually and that kind of solved my case.

**Comment by droidmonkey** [comment]
If you are custom setting schema then you need to emit the appropriate dbus message so we can switch as well.

**Comment by j-lakeman** [comment]
What do you mean @droidmonkey?
The shell extension utilises GNOME's default light and dark mode. All default, nothing tweaked.

**Comment by droidmonkey** [comment]
Depends on how you trigger the transition between the two. There are specific dbus signals emitted by native gnome transition that we listen for. If it's not working for you in keepassxc then those signals are not being emitted.
