### ISSUE TITLE
Per-database lock timeout

### ISSUE THREAD

**Issue by e-pirate** [keepassxreboot/keepassxc#8856]
## Summary
It will be nice to have database-related lock time out. In my case I have two DBs: my private DB that I open occasionally and for a one-shot operation only (like login to my bank account) hardly needed to be open for the next use in less then 5 minute period - it should go locked back again ASAP in a short period of time. The second DB is for work staff and during 12-hour intensive duty shifts I use it constantly spending time again and again unlocking it after application wide 5-minute time out. Kind of opposite scenarios: one DB get unlocked for a single login/password and should be locked back shortly, the other one should remain open for constant use during hours and hours during shifts.

IMHO a new data base parameter should be introduced to be able to change default lock timeout in per-database manner. Default is to inherit from an application-wide value set under security parameters, but once defined in Data base -> Data base settings -> Security -> Timeout, keepassxc should respect this timeout over default. This will allow use of different data bases in different use scenarios.

**Comment by droidmonkey** [comment]
#2224

**Comment by e-pirate** [comment]
@droidmonkey it still unclear how to use this when it will be implemented, can you enplane, please?

**Comment by droidmonkey** [comment]
It will be as you describe, settings exposed in Database Settings view

**Comment by e-pirate** [comment]
Perfect! Target version is 2.8.0, right?

**Comment by droidmonkey** [comment]
That's the plan yes
