### ISSUE TITLE
KeePassXC browser selection for each entry

### ISSUE THREAD

**Issue by gh4wi** [keepassxreboot/keepassxc#8859]
I need a browser selection field added to the database, 
so that one could specify which browser to use for that entry.

Then just clicking on URL would open the specified browser
with the selected URL.

Browsers such as FireFox, Chromium, and Chrome are my primary browsers.
Please add this feature for Linux Mint and Windows 10/11,

**Comment by droidmonkey** [comment]
Use the cmd:// url syntax to launch the browser you would like. We are not going to add a feature to select a browser or a browser per entry.
