### ISSUE TITLE
[feature request] Autosave the DB when an entry is added or modified

### ISSUE THREAD

**Issue by gagarine** [keepassxreboot/keepassxc#886]
When the user add or modify an entry and click "OK" the database is modified but not saved.

## Expected Behavior
Would be nice to save the database directly.

## Current Behavior
The database is modified but not saved.

## Possible Solution
Change the button from "ok" to "save" or "add entry" and "save change"

## Context
This is more consistent with browser/mobile app.
No risk to forget to save, move to another device and don't have the information (in case you are syncronised your database on multiple devices)

## Debug Info
KeePassXC - Version 2.2.0
Revision: caa49a8ef3ee28ed478192389b21d61107b3b8e0

Libraries:
- Qt 5.9.0
- libgcrypt 1.7.7

Operating system: macOS Sierra (10.12)
CPU architecture: x86_64
Kernel: darwin 16.7.0

Enabled extensions:
- KeePassHTTP
- Auto-Type
- YubiKey

**Comment by droidmonkey** [comment]
This is a setting. Setting it on my default is not necessarily desirable due to negative interactions with cloud based storage solutions.

**Comment by gagarine** [comment]
Cool! I still think auto-save should be the default.

I'm using dropbox to store my DB and if I forgot to save then I get synchronization problems (luckely database merge work great). A couple of time I didn't have the password I just enter in keepassxr on my mobile phone because I forgot to save.
