### ISSUE TITLE
"Get Title" button

### ISSUE THREAD

**Issue by abvgdeyoj** [keepassxreboot/keepassxc#8860]
## Summary
The proposal is to allow a simple way for the title of the page at the specified URL to be automatically inserted into the "Title" field, in the same 2 ways "Download Favicon" can be invoked.

## Examples
Add a separate "Get Title" button, which will autofill the "Title" field.
Alternative: If the title is empty when "Download Favicon" is invoked, fetch and set the "Title" field.

**Comment by droidmonkey** [comment]
We have decided against parsing html, which would be required to pull out the title. If you use the browser extension, it has an option to create entries with the page title and favicon inserted from the get go.
