### ISSUE TITLE
Password signs indexing

### ISSUE THREAD

**Issue by sltu** [keepassxreboot/keepassxc#8861]
## Examples
![image](https://user-images.githubusercontent.com/111493050/205486884-cbc7be11-ae3a-4e1e-be8a-68ce44ccb7b6.png)

## Context
Password signs indexing will help in such situations as below.

![image](https://user-images.githubusercontent.com/111493050/205486550-72f12fbf-e61f-4e7a-bd41-69516370f5fe.png)

Thanks

**Comment by phoerious** [comment]
I will mark the day websites stop doing this stupid shit. You can use Auto-Type with `{PICKCHARS}` to fill this idiotic form (see our docs and #725).

**Comment by sakej** [comment]
Hi.
I have this set up as autotype rule
{USERNAME}{TAB}{ENTER}{DELAY 5000}{PICKCHARS:Password}{ENTER}
but what I get is pickchars window first instead of of showing up after delay.
Is there is any way for it to run after ?

**Comment by droidmonkey** [comment]
Not at this time, no. Split your auto type into two sequences and select the second pickchars sequence you are ready for that step

**Comment by sakej** [comment]
yeah i was thinking about this as a workaround if there is no way for changing this behavior, thanks for letting me know. cheers
