### ISSUE TITLE
argument -entry-url-open, search by UUID

### ISSUE THREAD

**Issue by spatnynick** [keepassxreboot/keepassxc#8865]
hi, is there an alternative for keepass2's argument -entry-url-open ?

Keepass2 has an argument -entry-url-open, so I can trigger a cmd:// or URL from external script based on UUID; has KeePassXC-cli also this possibility?
https://keepass.info/help/base/cmdline.html
/usr/bin/keepass -entry-url-open -uuid=UUID-of-the-entry

another question - KeepassXC (gui) can not search by UUID? I get no results

**Comment by droidmonkey** [comment]
No that is not possible and not something we will implement. Search by uuid is coming

**Comment by spatnynick** [comment]
ok thank you for the reply..
