### ISSUE TITLE
KeepassXC freezes when loading from a webdav connection

### ISSUE THREAD

**Issue by sammmsational** [keepassxreboot/keepassxc#8867]
## Overview
KeepassXC becomes unresponsive after opening a .kdbx file from a webdav connection in the file explorer.
This does not happen if you install KeepassXC with apt instead of snap.

## Steps to Reproduce
1. Download KeepassXC from the Snap Store
2. Add a webdav connection in your file explorer
3. Open a database in the cloud with KeepassXC 

## Expected Behavior
Database should open normally

## Actual Behavior
KeepassXC freezes and becomes unresponsive.

## Context

KeePassXC - Version 2.7.4
Revision: 7729648
Distro: Snap

Operating System: Linux
Desktop Env: Gnome
Windowing System: Wayland

**Comment by droidmonkey** [comment]
We don't support the snap distribution anymore thanks to problems like this. This problem is outside the control of our program. Use flatpak or the native install.
