### ISSUE TITLE
long passwords not readable due to horizontal scrollbar

### ISSUE THREAD

**Issue by JohaJung** [keepassxreboot/keepassxc#8868]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
When you have long passwords which do not fit into the given password field width, a vertical scrollbar appears.
This scrollbar however does not hide on un-hovering and I found no possibility to increase the height of the text field (increasing the height/width of the window or preview panel does not change the dimensions of the password field).

I attached a screenshot (with a dummy password, of course).

![grafik](https://user-images.githubusercontent.com/81969656/205743422-7f11d251-3867-41c5-85b8-40a3664ba832.png)

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Create an entry with a very long password.
2. Save this entry and select it in the list -> preview panel opens
3. Click the eye-button to show cleartext password.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
The password is readable. (Either the text field height increases or the scrollbar hides on un-hover)

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
A scrollbar appears and does not hide, making the password unreadable.

## Context
[NOTE]: # ( Give us any additional information you may have. )
This issue was not there before the last update a few weeks ago. I'm not sure anymore, but I think the scrollbar used to disappear after scrolling.
(I'm not sure which version I had before, installed keepassxc from the official Ubuntu PPA)

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.4
Revision: 63b2394

Qt 5.12.8
Diagnosemodus ist deaktiviert.

Betriebssystem: Ubuntu 20.04.5 LTS
CPU-Architektur: x86_64
Kernel: linux 5.4.0-135-generic

Aktivierte Erweiterungen:
- Auto-Type
- Browser-Integration
- SSH-Agent
- KeeShare
- YubiKey
- Secret-Service-Integration

Kryptographische Bibliotheken:
- Botan 2.12.1

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: KDE
Windowing System: X11

**Comment by droidmonkey** [comment]
You are using a custom theme, we don't support that. You will have to use our dark theme instead or fix your theme to properly provide vertical spacing.

**Comment by JohaJung** [comment]
Indeed I used the Classical (platform-native) theme. Thanks for helping out!
