### ISSUE TITLE
Database merging caused duplicate entries, the difference was only in a description field

### ISSUE THREAD

**Issue by slrslr** [keepassxreboot/keepassxc#8872]
## Overview
My KeePassXC 2.6.2 database already contained entries imported from .csv file produced by Firefox 9x.x.
Today i wanted to import latest version of my Firefox passwords from the .csv file.
To my surprise, it not allowed import into existing database, but created new DB. which i then tried to merge (Database/Merge from database) to old database.
Result is duplicate entries. Different seems to be in Notes and Modified fields (i do not know about the password field).

In my opinion i would like to have option to replace existing entries password field only if title and username fields match.

I am unable to find any option that would de-duplicate the database. But that is not a big problem, i have made a backup of my old db (i am unsure if KeePass suggested to make a backup before merging).

I would like to be able to import CSV into existing database.

My question is also, how do i properly update database without causing duplicates?

Thank you for your time, i am using KP for years and happy with it.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.2
Revision: e9b9582
Qt 5.15.2

[NOTE]: # ( Pick choices based on your environment )
Operating system: Linux
Desktop: KDE
Windowing System: X11

**Comment by droidmonkey** [comment]
Couple things here:

1. update to 2.7.4
2. Don't use csv as your "source of truth", always use the database itself
3. We don't merge based on title/username because there is no requirement for them to be unique. All keepass apps merge based on uuid which is unique and prevents data loss.
4. There is already a feature request to import into an existing database, so this is a duplicate.

**Comment by slrslr** [comment]
I wish you answered the question "how do i properly update database without causing duplicates?" I am unsure how to use yours mentioned "uuid". The Firefox .csv file that i want to import looks like this:
`"url","username","password","httpRealm","formActionOrigin","guid","timeCreated","timeLastUsed","timePasswordChanged"`
after imported it to a new DB and merged to current DB, it caused duplicates. Difference in DBs seems to be only in Notes and Modified fields (i do not know about the password field).

Btw. **workaround** to prevent duplicity one may try to sort items by Created or Modified time (eventually display such column right clicking on columns header) in old database and delete all the items with the same date (date of import/export possibly). Then merge new DB to old one (while there is no [feature to import csv to existing DB](https://github.com/keepassxreboot/keepassxc/issues/1832))

**Comment by droidmonkey** [comment]
There is only one answer: stop using Firefox password manager and keepassxc simultaneously. Pick one. Or choose one that will be read only for you.
