### ISSUE TITLE
Autotype does not work in 2.6.6 from debian repo

### ISSUE THREAD

**Issue by fds2610** [keepassxreboot/keepassxc#8874]
## Overview
Autotype does not work anymore

## Steps to Reproduce
1.  right-click on entry for context-menu
2.  select Autotype

## Expected Behavior
Username and Password shall be typed into previous window

## Actual Behavior
nothing happens

## Context
it worked until previous version

KeePassXC - Version 2.6.6
Revision: 9c108b9

Qt 5.15.6
Diagnosemodus ist deaktiviert.

Betriebssystem: Debian GNU/Linux bookworm/sid
CPU-Architektur: x86_64
Kernel: linux 6.0.0-5-amd64

Aktivierte Erweiterungen:
- Auto-Type
- Browser-Integration
- SSH-Agent
- KeeShare (bestätigtes und unbestätigtes Teilen)
- YubiKey
- Secret-Service-Integration

Kryptographische Bibliotheken:
- libgcrypt 1.10.1

unfortunately 2.6.6 is the latest version in debian repo.
but the functionality does work in 2.7.4 when I use the AppImage version - so maybe it is an installation issue ?

**Comment by droidmonkey** [comment]
You might be running wayland, in which case Auto-Type will not work. The appimage may be running under xwayland. You can force keepassxc to run under xwayland using `QT_QPA_PLATFORM=x11 keepassxc`
