### ISSUE TITLE
Verification checks failing for .zip download

### ISSUE THREAD

**Issue by Rowfloe** [keepassxreboot/keepassxc#8875]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
Verification checks failing

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. gpg --fetch-keys https://keepassxc.org/keepassxc_master_signing_key.asc
2. gpg --verify KeePassXC-*.sig
3. 
![image](https://user-images.githubusercontent.com/100158485/206570399-3c9195fe-b0f1-41de-ac20-0d64a4601bd7.png)

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
No 'bad signature' results to appear after downloading the windows .zip.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
![image](https://user-images.githubusercontent.com/100158485/206570504-51ac4ab5-d8f4-4f5b-8ffe-f91a337c9965.png)

## Context
[NOTE]: # ( Give us any additional information you may have. )
![image](https://user-images.githubusercontent.com/100158485/206570509-014ec5a2-0a82-4f26-aafe-1c70eaab3a79.png)

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - latest
Revision: latest
![image](https://user-images.githubusercontent.com/100158485/206570522-570acb3f-f681-46f3-a4b4-f04bc3befa08.png)

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows

![image](https://user-images.githubusercontent.com/100158485/206570536-6e06b16d-883c-441f-bf60-6ca9c181389d.png)

**Comment by droidmonkey** [comment]
You need to update your gpg4win. There was a bug that prevented updating a key that was fixed earlier this year.
