### ISSUE TITLE
Can't pipe password into keepassxc-cli

### ISSUE THREAD

**Issue by Christian-Nerd** [keepassxreboot/keepassxc#8878]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
When writing scripts for keepassxc-cli in order to actually script using it properly you need to be able to input the password into keepassxc-cli automatically, but with the most recent update of keepassxc at the time of writing piping the password seems to fail. I ran a script that worked before the most recent update that allowed me to grab an attribute from my database without opening the gui app. I ran this script again and it no longer works due to piping not working.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Make a database called for this example I use p.kdbx(no multi-factor authentication that makes things more complicated). 
2. Open your terminal and make a variable for your database password for this example let's use love
3. Make a script piping your password into the keepassxc-cli open command. 

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Given the steps I told you the result will end up with the database being automatically opened.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
This cannot work due the database saying it didn't get valid credentials. What happens is you get a prompt to enter your password you wait a bit and then it says the credentials are invalid.

## Context
[NOTE]: # ( Give us any additional information you may have. )
My system is mac os in case this might be a os issue. The terminal i'm using is iterm2 in case my terminal is being stupid, and the shell I use is bash.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.4
Revision: 63b2394

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS
Desktop Env: macOS desktop enviorment
Windowing System: X11

**Comment by Christian-Nerd** [comment]
Explain why more info is needed

**Comment by droidmonkey** [comment]
It needs to be replicated...

**Comment by droidmonkey** [comment]
Which I could not do, so this must be a problem on your end. Did you change your database's password? 

![Screenshot_20221210_095520_VNC Viewer.png](https://user-images.githubusercontent.com/2809491/206861400-c616af58-1a74-4688-8633-32d8ea181059.png)

> the database saying it didn't get valid credentials

This means piping works fine, but you gave it the wrong password...

**Comment by Christian-Nerd** [comment]
droidmonkey the computer says that my password isn’t a command and then it fails

**Comment by droidmonkey** [comment]
Did you use `echo "password"` ?
