### ISSUE TITLE
password update time

### ISSUE THREAD

**Issue by ethicnology** [keepassxreboot/keepassxc#8879]
## Summary
Last time update for password specific field 

## Examples
Sometimes I want to know the last time I changed the password for a specific entry
The expiration time should be based on the last password update

## Context
Using expiration time can drive you mad because each time you update the password you have to update the expiration time.
Expiration time should be setup (globally or per-entry) and then we shouldn't take care about it, he should be based on the last password update for the entry, with this each time I change my password, the expiration time should adapt.

If I don't use expiration time, I still want to know the last time I updated the current password.

**Comment by michaelk83** [comment]
See #2010. I think at the moment, the time of last password change is calculated from the entry's history.

**Comment by droidmonkey** [comment]
#4293
