### ISSUE TITLE
Icons suddently became so large

### ISSUE THREAD

**Issue by jtxnn678** [keepassxreboot/keepassxc#8882]
Icons suddently became so large, it was fine yesterday. I can't find anything in the settings that can trigger this...
Running on Manjaro KDE Plasma 5.26.4 (kernel 5.15.81)

![image](https://user-images.githubusercontent.com/97281488/206909365-fda62f97-21f6-46c3-8f07-e1d992c85789.png)

**Comment by droidmonkey** [comment]
You need to set your high dpi setting properly. See our user guide.

**Comment by jtxnn678** [comment]
I didn't change anything related to DPI or display, it was working properly. as you can see from the screenshot, there are large icon & small icon mixed together, how can this be a DPI related?

**Comment by droidmonkey** [comment]
There is something weird going on with your Qt, this isn't a KeePassXC code issue. Could be related to your Qt SVG plugin since all those icons that are rendered large are SVG's.

**Comment by jtxnn678** [comment]
yeah strange indeed, it was working fine but now all built-in icons of Keepass are large. Maybe I installed some packages that messed up something, never mind its not a big issue I will sort it out.
Thank you for take time to respond, KeepassXC is really a nice app that I can't live without. More power to you guys!

**Comment by droidmonkey** [comment]
Deepin packages have been known to screw up other Qt apps

**Comment by jtxnn678** [comment]
@droidmonkey Thank you Jonathan for the hint!
I found the culprit, after remove those unnecessary **deepin** package installed by **dtkcore**, Keepassxc is back to normal again!
![image](https://user-images.githubusercontent.com/97281488/207731966-410ea596-9d83-4edd-9c03-03c7da9b44b3.png)

**Comment by droidmonkey** [comment]
Not sure why these haven't been pulled from the repo, they are intrusive and ruin other apps.

**Comment by jtxnn678** [comment]
It's good that you had knowledge about that deepin caused this issue, it would take me forever to figure out if weren't you. thanks again.

**Comment by ghost** [comment]
Nope not the issue i meant i do not talk about an icon in or outside the program 
I talk about the program when i open it on screen before login the main program it fills my screen with at least 1 fifth on 1080p
When i open it on 1440p it is the nice small so it scales on the original 1440p not on the actual gaming 1080p
I hope a solution can be found as it is kinda weird 
I am just guessing but it is if it read somewhere that the monitor is 1440p and sets itself to that screen size so on the actual screensize it is huge

**Comment by thomas-mc-work** [comment]
Thank you guys for figuring that out! For me it was the package `libdtkcore5` on Ubuntu 24.04. Cheers!

**Comment by mick-t** [comment]
Similar issue here, removed `deepin-terminal` and Icons back to normal.
