### ISSUE TITLE
2.7.4 Windows Hello bypass

### ISSUE THREAD

**Issue by Shmuel90** [keepassxreboot/keepassxc#8883]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
When using KeePass 2.7.4 as well as with 2.7.1, on Windows 11, there exists a bypass in Windows Hello by simply pressing cancel when prompted for a pin.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Create a database in 2.7.x 
2. Ensure windows hello is enabled
3. Lock the database 
4. Enter password
5. Press cancel on windows hello prompt

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Should not let you in the database unless proper auth is is provided.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Upon pressing cancel on windows hello prompt, database is open provided the proper password.

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.4, 2.7.1
Revision: 63b2394

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows
Desktop Env: Windows
Windowing System: X11

**Comment by droidmonkey** [comment]
Try to unlock your database without the correct credentials... quick unlock is disabled if you dismiss the windows hello prompt. Has nothing to do with unlocking your database.
