### ISSUE TITLE
Wayland: Ctrl+C not working when editing an entry

### ISSUE THREAD

**Issue by janvlug** [keepassxreboot/keepassxc#8884]
## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Open an entry in the Edit entry mode
2. Press Ctrl+C (in the Entries|Copy Password menu shown with the shortcut Ctrl+C)

## Expected Behavior
Password copied to clipboard.

## Actual Behavior
The password is not copied to the clipboard.

KeePassXC - Version 2.7.4
Revision: 63b2394

Qt 5.15.7
Debugging mode is disabled.

Operating system: Fedora Linux 37 (Workstation Edition)

Operating System: Linux
Desktop Env: Gnome
Windowing System: Wayland

**Comment by nlutterman** [comment]
I'm experiencing this as well and trying to catch it in the act. It seems that clipboard actions into or out of KeePassXC fail after the application's been open for some time. 

I _suspect_ it might have to do with the timeout-based clipboard clearing feature.

Quitting and restarting the application fixes this issue for me.

**Comment by droidmonkey** [comment]
This is an issue with Wayland, and I suspect within qwayland.

**Comment by Man2Dev** [comment]
can confirm that the issue is not present in wayland fedora 37 with Plasma desktop envirment

**Comment by 3dde** [comment]
Somehow this issue has reappeared under Fedora 40 with Plasma 6 now. Didn't happen with Fedora 39 and Plasma 5...

**Comment by KeepHell** [comment]
Fedora 42, Gnome - same Issue, you have to rightclick and select Copy, Ctrl-C doesn't work.

**Comment by droidmonkey** [comment]
Install wl-clipboard

**Comment by mbevc1** [comment]
hm, I'm seeing issues copy/pasting from/to KeePassXC on Fedora 44 and Wayland. Is this a known issue and I need `wl-clipboard` to make it work?

**Comment by droidmonkey** [comment]
Give it a try

**Comment by mbevc1** [comment]
oh, seems it was already installed 😬
