### ISSUE TITLE
Ubuntu cant set backup file location

### ISSUE THREAD

**Issue by sk3nn1xxx** [keepassxreboot/keepassxc#8885]
I just installed keepassxc and tried to setup the backup but then i can just check the box but not specify where to save?
i just used apt to install keepassxc
![Screenshot from 2022-12-13 05-18-40](https://user-images.githubusercontent.com/62090337/207225553-be02c8d4-b686-4dfa-b866-17469e797d60.png)

**Comment by sk3nn1xxx** [comment]
now i installed it through snap and now i cant specify the custom config location for librewolf browser integration xD

**Comment by varjolintu** [comment]
Use AppImage or Flatpak instead?
