### ISSUE TITLE
Einträge in Listenansicht verschieben ist nicht mehr möglich

### ISSUE THREAD

**Issue by handy32** [keepassxreboot/keepassxc#8886]
in KeePassXC unter WINDOWS10 kann ich die Einträge in der Listenansicht nicht (mehr) nach oben/unten verschieben. Dafür gab es vor dem letzten Update zwar noch einen Menüeintrag ("Strg+Alt+Hoch" bzw. "Strg+Alt+Herunter"), der allerdings nicht funktionierte.

**Comment by droidmonkey** [comment]
Disable sorting entries by clicking the header row until the sort arrow disappears.
