### ISSUE TITLE
KeepassXC v2.7.4 Password Generator differs in Ubuntu /  Win11

### ISSUE THREAD

**Issue by JOOmsH** [keepassxreboot/keepassxc#8887]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )

I am using the same verion of KeePassXC on several os and realized that it offers different features depending on the os. I understand that some features depending on the os - like that you can do screenshots of KeePassXC in Linux but are unable to do the same in Windows. But it would be great if one version of keepassxc offers all tool related features like the password generator has the same functionality on all os :). 

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )

KeepassXC v2.7.4 at Ubuntu
![Screenshot from 2022-12-13 17-33-03](https://user-images.githubusercontent.com/52428904/207393210-5ffa10ca-e49f-4a30-a3fa-59fe50327c02.png)

KeepassXC v2.7.4 at Win11
![image](https://user-images.githubusercontent.com/52428904/207392962-420708d1-fb07-4992-bc51-d3169c1aa32b.png)

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )

I felt its kinda confusing. At least different version-numbers would help a bit :)

**Comment by droidmonkey** [comment]
Click the advanced button...
