### ISSUE TITLE
The attachment and TOTP icon in Classic theme are stretched

### ISSUE THREAD

**Issue by CrendKing** [keepassxreboot/keepassxc#8888]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

Only in the Classic theme, the "Has attachments" and "Has TOTP" icons in the list are stretched horizontally.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Switch to Classic (Platform-native) theme.
2. Create an entry with attachment and totp.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
The icons should look normal, exactly like in other themes

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Icons are stretched

## Context
[NOTE]: # ( Give us any additional information you may have. )
![Clipboard 1](https://user-images.githubusercontent.com/975235/207422923-5ca1069d-5713-4a8d-b3c1-c338d15afb79.jpg)

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.4

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 11 22H2

**Comment by droidmonkey** [comment]
We don't support classic theme
