### ISSUE TITLE
Keepassxc and PassIFox; Popup window to unlock database

### ISSUE THREAD

**Issue by dschrempf** [keepassxreboot/keepassxc#889]
I use Keepassxc in combination with PassIFox at work and leave my desk every once in a while. Then, the database is locked (after inactivity or lock screen, depends on configuation). When I come back, in Firefox I see `Keepass database is not open`. Instead, a popup window to unlock the database should appear.

**Comment by yan12125** [comment]
Maybe it's disabled? Try to check Preferences -> Browser Integration -> Request to unlock the database if it is locked.

**Comment by dschrempf** [comment]
Oh, mh, I didn't know that this function existed, but it is enabled. I
only see the PassIFox message. The reason may be that I am using a
tiling window manager, however, it should still work in this case.
However, a password popup like `pinentry` to unlock the database would
be the most straightforward.

**Comment by yan12125** [comment]
On my machine, if the option is enabled, KeePassXC window will be bring to front if it's locked. It works fine with openbox.

PS. I'm using my own fork of PassIFox, which is in turn based on projectgus's WebExtensions fork. (https://github.com/pfn/passifox/pull/595) I'm not sure whether it makes a difference or not.

**Comment by dschrempf** [comment]
Hm, it doen't work here, also it always asks me to update the entry whenever I click `sign in` or something equivalent. Is this normal?

**Comment by phoerious** [comment]
We probably won't fix any of those things anymore for KeePassHTTP, but this should be considered for the successor implementation keepassxc-browser.

Ping @varjolintu

**Comment by dschrempf** [comment]
It's good to here that a WebExtensions addon is being developed. Let me know if I should reopen an issue there. Thank you!

**Comment by varjolintu** [comment]
I'm not seeing the popup window either on my machine (macOS) when the database is locked. Not with chromeipass or keepassxc-browser. I wonder if this is Qt related issue? Is `activateWindow()` really working as it should?

**Comment by eleksis** [comment]
Can confirm, that minimizing to system tray is causing problems.
My setup: mint 18.1, kepassxc 2.2.2, firefox 56, keepasshttp-connector 1.0.3

**Comment by varjolintu** [comment]
I'm currently working on a PR that changes the behaviour with the new browser extension. Every time it requests a database unlock the same popup AutoType triggers will be used. This should allow to do the unlock even if KeePassXC is minimized to system tray.

**Comment by phoerious** [comment]
Unlocking from the tray already works, but it always brings the full main window to the front.
