### ISSUE TITLE
CSV files Not Available for Import

### ISSUE THREAD

**Issue by ghost** [keepassxreboot/keepassxc#8891]
I am not able to view, and import a csv file that was exported by the same version of KeepassXC that was used to export, and create the csv file.  The file shows up in the explorer area, but not in KeepassXC

**Comment by droidmonkey** [comment]
Did you use Database -> Import -> CSV?

I don't understand what you are saying

**Comment by ghost** [comment]
The following steps were taken in order to observe the problem reported:

1)  Export existing database to a csv file, and name the file with the date it was exported.
2)  Select Import File Option, and attempt to import the recently exported file that is named with the date it was created.

After the import file option no csv files are viewable even though there are more than one in the folder where they are saved.  Also, the Explorer tool in Pop!_OS is able to find this file after entering the file name, and displays a message indicating that the file is ready to install. This suggest the file was created properly, and that something is wrong with the CSV import tool.  I am running KeepassXC 2.6.6 which is the latest version available in the Pop!_OS repository  (flavor of Ubuntu).

**Comment by droidmonkey** [comment]
If you don't see the file in the file open dialog then you either did not use .csv extension, choose "all files", you are looking in the wrong folder,  or keepassxc doesn't have permission to read files in that folder. This isn't a problem with our program. 

Screenshots would be helpful

**Comment by ghost** [comment]
Hello Jonathan:

I just changed the file extension to .csv, and everything now works fine.  I didn't realize I had to change the extension in order to get things working, and question why the program doesn't affix a .csv extension during file export if it is required?  Also, question why there isn't an encryption option for the .csv file as well.

Randal

 ---- On Thu, 15 Dec 2022 13:11:37 -0800  Jonathan White  wrote ---

**Comment by droidmonkey** [comment]
We do affix the csv extension, not sure what's wrong with pop os file manager?

There is no such thing as an encrypted csv file.
