### ISSUE TITLE
set icon on multiple entries

### ISSUE THREAD

**Issue by SynapseScribe** [keepassxreboot/keepassxc#8895]
select with shift/ctrl multiple entries in same folder > right click > set icon

**Comment by droidmonkey** [comment]
Already possible. Make sure you are running the latest version.

**Comment by SynapseScribe** [comment]
i m not talking about downloading favicon, but rather choosing from one of the predefined ones

**Comment by droidmonkey** [comment]
Edit the group you are interested in, go to icons page, in lower right there is a drop down that let's you set the group icon to its entries. If you want to do this for a selection of entries, just temporarily move them into the group first.

**Comment by SynapseScribe** [comment]
i totally misslooked this feature. it works great. thank you!
