### ISSUE TITLE
New (badly needed) Feature Request

### ISSUE THREAD

**Issue by WayneDwayne** [keepassxreboot/keepassxc#8898]
** KeepassXC is lacking a SafeNotes feature to their password manager.  

## Examples

- Root
-   - SafeNotes
-       - Miscells (contain either single entries or multiple text entries, such as all my IP Cameras' device specs) in a text file or file similar to Wordpad so that special formatting, color, highlighting and fonts can be used and retained
- 

## Context
I am new to KeepassXC and came from Roboform. After I successfully setup KeePassXC, I noticed that one **critical feature is missing--**_Notes**_**, that are independent from the Notes field of a password entry.  This is a very helpful feature that I am surprise is missing from your software.  These notes can be associated with passwords and online accounts, but most that I had created were not.  

Example: I have a Safenote for my IP Cameras specs or computer specs.  I even had Safenotes for my many combination locks and even my home safe.  Is it possible to add this feature?

**Comment by droidmonkey** [comment]
#8228

**Comment by michaelk83** [comment]
For lock codes and the like you can use the standard password field.

**Comment by phoerious** [comment]
You can use any number of custom "advanced" string fields. They just don't show up in the main UI.

**Comment by JohnLGalt** [comment]
From the User Guide:

https://keepassxc.org/docs/KeePassXC_UserGuide.html#_advanced_entry_options

That should cover everything you need, @WayneDwayne
