### ISSUE TITLE
Prompt to unlock OneDrive Personal Vault

### ISSUE THREAD

**Issue by bye7** [keepassxreboot/keepassxc#8899]
Microsoft's cloud service "OneDrive" provides a protected folder "Personal Vault" that can only be accessed with a second step of identity verification (fingerprint, face, SMS code or other methods). 

I'd like to see KeePassXC to automatically prompt the second layer of identity verification `odopen://unlockVault/?accounttype=personal` when opening the database that is stored in the "Personal Vault" folder `%OneDrive%\Personal Vault`.

**Comment by droidmonkey** [comment]
There is no need at all to store your database in the personal vault on onedrive. The file is fully encrypted at all times. Technically onedrive should be prompting to unlock the personal drive when attempts to access it occur.

**Comment by bye7** [comment]
> There is no need at all to store your database in the personal vault on onedrive. The _file is fully encrypted_ at all times. Technically onedrive should be prompting to unlock the personal drive when attempts to access it occur.

With respect, I must disagree. Storing the database in OneDrive's Personal Vault provides additional benefits that can enhance the security rather than simply storing it in OneDrive.

One reason is that the Personal Vault provides an additional layer of security beyond simple encryption. For example, if someone gains access to your OneDrive account (either through your computer being left unattended or through some other means digitally), they may be able to view and potentially manipulate the files stored within it. However, if those files are stored in the Personal Vault, the attacker would also need to pass a second layer of identity verification before they could access the contents of the vault.

Another reason to store encrypted files in the Personal Vault is that it allows you to more easily manage and organize your sensitive files. The Personal Vault provides a secure, designated location for storing and accessing important or sensitive documents, making it easier to keep track of them and ensure that they are not accidentally shared with the wrong people.

Finally, storing encrypted files in the Personal Vault may also provide an additional level of peace of mind. While encryption is a powerful tool for protecting the confidentiality of your data, it is not foolproof and can potentially be compromised. Storing your encrypted files in the Personal Vault adds an additional layer of protection and can give you greater confidence that your sensitive data is secure.

**Comment by droidmonkey** [comment]
You do realize that the personal vault is just an encrypted file container that uses the same type of encryption that we use? The key is stored in windows credential store and unlocked using windows hello, actually very similar to how we implement quick unlock using windows hello. There is no additional protection granted to your database file by double encrypting it.

Either way, just unlock your personal vault prior to using it. We won't be implementing a layer of unlocking in our program.

**Comment by bye7** [comment]
From [Documentation and FAQ](https://keepassxc.org/docs/#faq-yubikey-2fa):
> Does KeePassXC support two-factor authentication (2FA) with YubiKeys or OnlyKeys?
>
> Yes and no. No, because technically speaking, KeePassXC is not a service and therefore does not use "**authentication**"...
___

I'm not aware of KeePassXC having similar implementation as OneDrive's personal vault:
- Two-step verification is required to gain access to Personal Vault (SMS/security code to your phone)
- BitLocker-encryption - On Windows 10 PCs, OneDrive syncs your Personal Vault files to a BitLocker-encrypted area of your local hard drive.

> ...just unlock your personal vault prior to using it...

I might end up just implementing the feature myself, it doesn't seem hard to add the feature, as you only have to open `odopen://unlockVault/?accounttype=personal` and OneDrive does the rest. In the meantime I'll continue to unlock the personal vault manually before opening keepassxc, it's such an inconvenience. I guess good security is inconvenient. Thanks.

**Comment by droidmonkey** [comment]
Authentication is meaningless to encryption. OneDrive just verifies who you are, THEN decrypts the files using bitlocker. Bitlocker uses a key stored in windows credential store (sometimes stored in a TPM chip) to perform the actual encryption/decryption. All the authentication kabuki dance is just to get to the point of using the key on your computer. 

All files stored in OneDrive are encrypted with their own key stored in Azure KeyVault. The only difference with personal vault files is an additional identity verification prior to access and.. when stored locally.. are encrypted using bitlocker or other os native methods.
