### ISSUE TITLE
Window is only shown when launching from Cygwin terminal [Windows 10]

### ISSUE THREAD

**Issue by max-kamps** [keepassxreboot/keepassxc#890]
As the title says, I can't get KeePass to display a window.
Running it from cmd or the explorer doesn't do anything (aside from exiting with return code 0).
When running from the Cygwin terminal it works just fine though. 

CLI is not affected by this. The `-g` login box still works without problems.

## Steps to Reproduce
I don't quite know. Maybe just installing Cygwin is the issue?

## Debug Info
KeePassXC - Version 2.2.0
Revision: caa49a8ef3ee28ed478192389b21d61107b3b8e0

Libraries:
- Qt 5.9.0
- libgcrypt 1.7.7

Operating system: Windows 10 (10.0)
CPU architecture: x86_64
Kernel: winnt 10.0.15063

Enabled extensions:
- KeePassHTTP
- Auto-Type
- YubiKey

## Additional Environment Info + Amazing Visual Aids

![keepassxc](https://user-images.githubusercontent.com/11182284/29591281-19d1b758-879e-11e7-8522-0c00f6ea231c.png)

**Comment by phoerious** [comment]
KeePassXC is not a console application. I'm not entirely sure if you are supposed to be able to open it that way. The Cygwin/MSys terminal works differently from the Windows cmd.exe.

**Comment by max-kamps** [comment]
Yeah, I have no idea why this works (or rather, why this doesn't work).

**Comment by droidmonkey** [comment]
Does it launch if you double click the exe? "You're using it wrong" comes to mind here.

**Comment by phoerious** [comment]
I'd assume that you just cannot start GUI applications that way on Windows. Other than *nix applications, they don't have an attached console.

**Comment by max-kamps** [comment]
Yeah, but it doesn't work by double-clicking either. That's the problem...

**Comment by phoerious** [comment]
Does this mean you can't start it at all?

**Comment by max-kamps** [comment]
Well, when I start it sometimes it shows up in the task manager very briefly, but quickly disappears. It never gets to the point where it would show a window. Once I launch it from Cygwin however, opening it by double clicking highlights the existing window like you would expect.

**Comment by phoerious** [comment]
Is it possible that you have enabled the options to minimize to the tray and minimize on startup?

**Comment by max-kamps** [comment]
No, I just have the default settings.
I tried enabling that and it worked like intended when launching from Cygwin (Showed a tray icon), but when launching by double clicking no tray icon appears and checking in the task manager doesn't show KeePass running.

**Comment by phoerious** [comment]
Have you compiled KeePassXC from sources or have you used our official packages?

**Comment by max-kamps** [comment]
It's the official package from the downloads section on keepassxc.org

**Comment by max-kamps** [comment]
I'm trying to compile it from source right now and maybe do some debugging. I've never done it on Windows though, let's see how it goes...

**Comment by droidmonkey** [comment]
Do you have an antivirus/malware program installed? I use keepassxc on win10 everyday so it's definitely something on your end.

**Comment by max-kamps** [comment]
Hmm, I was planning to debug the version I built from source, but that one works just fine...
I can't really tell why that would be, since the only thing I really changed is disabling YubiKey p
If something like this happens again, I'll come back, but for now you can probably close this issue for not being reproducible.

Thanks for your time though 😄

**Comment by devmattrick** [comment]
Hi there, I also am having this issue on Windows 10. I can't provide much information, as there are no error logs or anything that I can see. Reinstalling KeepassXC does not fix it, even when removing KeepassXC files in AppData.

I also can confirm that running it in Cygwin is the only way I can get it working (running the app by double clicking the .exe isn't working, running the .exe from cmd just exits immediately).

I'm happy to provide any information needed to help resolve this.

**Comment by max-kamps** [comment]
Now *this* is unexpected.

**Comment by droidmonkey** [comment]
The plot thickens! How about if you have any antivirus or application guard type programs installed and running? @phoerious I wonder if this is because of a latent single instance file, but on Windows it doesn't display a warning.

**Comment by devmattrick** [comment]
@droidmonkey nope, no antivirus running. I even have disabled Windows Defender, to no avail.

**Comment by phoerious** [comment]
Possibly a single-instance problem. The app doesn't have an associated terminal, so it won't print anything to STDOUT. I wonder, though, why it's working from the Cygwin terminal. It should either work everywhere or nowhere.

**Comment by droidmonkey** [comment]
Check to see if you have a c:\Users\[username]\AppData\Local\temp\keepassxc-[username].lock file present. If so delete it, then try running the exe as normal.

@phoerious we need to add in https://github.com/keepassxreboot/keepassxc/blob/develop/src/gui/Application.cpp#L129 that if the three attempts fails then we just launch the app as the new single instance (remove the existing lock file in the process).

**Comment by devmattrick** [comment]
@droidmonkey yep, that fixed it! Is it possible that a forced restart didn't allow the application to delete the lock file?

**Comment by droidmonkey** [comment]
Likely, we have an open issue already to fix this problem #893
