### ISSUE TITLE
Allow database unlocking using multiple hardware keys

### ISSUE THREAD

**Issue by imnotpoz** [keepassxreboot/keepassxc#8900]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
Allow the user to add multiple hardware keys and pick one of them to unlock the database.

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )
![image](https://user-images.githubusercontent.com/64381190/208269828-a37623f7-6bcd-477b-aa4e-ff8f92d3c0ed.png)
Many websites that allow hardware tokens allow adding several, not sure if that would be more complicated, or even possible in KeepassXC.

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
I want to lock my database with a hardware key, without the risk of being locked out of everything if I ever lose the key. Having a spare key laying around somewhere that still lets me access everything would remove that risk.

**Comment by droidmonkey** [comment]
Make a duplicate key, instructions are in our user guide. The kdbx standard does not allow for multiple keys, passwords, etc.
