### ISSUE TITLE
Your certificate is not up to date.

### ISSUE THREAD

**Issue by rw-django-fan-2020** [keepassxreboot/keepassxc#8901]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
Your certificate is not up to date.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1.1 execute: gpg --keyserver keys.openpgp.org --recv-keys CFB4C2166397D0D2
1.2 Ouput: gpg: Empfangen vom Schlüsselserver fehlgeschlagen: Zertifikat abgelaufen
2.1 execute: gpg --fetch-keys https://keepassxc.org/keepassxc_master_signing_key.asc
2.2 Output: gpg: fordere Schlüssel von https://keepassxc.org/keepassxc_master_signing_key.asc an
      gpg: WARNUNG: die URI https://keepassxc.org/keepassxc_master_signing_key.asc kann nicht geholt werden: Zertifikat abgelaufen

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

## Context
[NOTE]: # ( Give us any additional information you may have. )
The content of the files from "keys.openpgp.org" and https://keepassxc.org/keepassxc_master_signing_key.asc are not equal.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 10

**Comment by droidmonkey** [comment]
It is, you need to pull the latest one. Also there is a bug in older versions of gpg4win that made it impossible to pull a fresh cert once the existing one expired. Make sure you are running the latest version of gpg4win.
