### ISSUE TITLE
[BUG] "Entropy bar" don't show password entropy quality

### ISSUE THREAD

**Issue by waltermelow** [keepassxreboot/keepassxc#8904]
## Overview
[BUG] "Entropy bar" don't show password entropy quality

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Tools > Pasword Generator
2. Click tab "Passphrase"
3. Regenerate password

## Expected Behavior
"Entropy bar" show password entropy quality

## Actual Behavior
After last KeePassXC version, progress bar don't move

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.4
Revision: 63b2394

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows and macOS
Windowing System: Windows 10 and macOS Ventura

---

![2022-12-19_-_17 49 56 813_-_KeePassXC_-_KeePassXC](https://user-images.githubusercontent.com/196580/208479047-aea7e105-8099-470d-b3e5-cb0369d5a5ee.gif)

**Comment by droidmonkey** [comment]
Passphrase entropy is solely based on the number of words, the exact words chosen is meaningless.

**Comment by waltermelow** [comment]
In case, introduce/complete manually the password with another characters or another words, the progress bar **don't recalculate entropy**.

![2022-12-19_-_20 40 44 181_-_KeePassXC_-_KeePassXC](https://user-images.githubusercontent.com/196580/208506799-fe7c9732-5c0b-4307-af00-461f8dc20fe4.gif)

**Comment by droidmonkey** [comment]
When you do that, you change from passphrase to password. Take that over to the password tab to see your entropy.

**Comment by michaelk83** [comment]
@waltermelow See #867

**Comment by waltermelow** [comment]
> When you do that, you change from passphrase to password. Take that over to the password tab to see your entropy.

Sorry for returnig again, and @droidmonkey thanks for your time in the project!

However, i think that if the user insert a new word in de password input (user is manual compose a new _passphrase to password_), the entropy must be recalculated.

(this behaviour is correct implemented in release **before** KeePassXC 2.7.4)

**Comment by phoerious** [comment]
There is no way we can calculate the entropy accurately for a passphrase with custom words.

**Comment by droidmonkey** [comment]
> this behaviour is correct implemented in release before KeePassXC 2.7.4

This behavior has been the same for 5 years, that is not true
