### ISSUE TITLE
Share entry

### ISSUE THREAD

**Issue by comrade001** [keepassxreboot/keepassxc#8905]
## Summary
I would like to share one o more entries with my contacts. I don't know a button with shre icon to only export that entry.

Thanks

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )

## Context
I have a shared panel with my partners and it could be very usefull if we can share that entries between us.

**Comment by droidmonkey** [comment]
Use keeshare, check out our user guide for instructions
