### ISSUE TITLE
KeeShare is supposed to ignore structure but it doesn't

### ISSUE THREAD

**Issue by slalomsk8er** [keepassxreboot/keepassxc#8908]
I use KeeShare to keep the database on different machines in sync like this:

```
Client A <=[synchronizes with KeeShare]=> (Transfer container) <=[synchronizes with KeeShare]=> Client B
```
With KeeShare active on the root folder.

I noticed in the past that if I edit a entry it moves to the root folder on the remote machine.
If I understand the documentation and the [main issue](https://github.com/keepassxreboot/keepassxc/issues/3045) correctly, this is supposed to be the case only on first import.

After this I can manage the structure on both machines independently and only the content of the entry should update but it also syncs some structure or more precisely, removes it on the other machine (sync target).

Now I wanted to use auto AutoOpen but I need to keep a entry per PC because if I move the entry on the other machine into AutoOpen it is moved to the root folder on the machine where the entry originated and vice versa - this is very frustrating.

**Comment by droidmonkey** [comment]
We dont recommend you use keeshare on the root folder, that produces bugs, as you've witnessed.

**Comment by droidmonkey** [comment]
Also, I am closing this as duplicate to the other keeshare bugs. This will be a non-issue when I finish my refactor of this service.
