### ISSUE TITLE
KeepassXC crashes when editing tags

### ISSUE THREAD

**Issue by cldotdev** [keepassxreboot/keepassxc#8909]
## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Open KeePassXC.
2. Click add a new entry or edit the existing entry.
3. Add a tag, then click the close button of the tag.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

The tag should be removed as expected.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

The app crashes with an error:

![圖片](https://user-images.githubusercontent.com/2265716/208845785-e276a070-8e1f-4d60-8757-c9cef3d0fad1.png)

## Context
[NOTE]: # ( Give us any additional information you may have. )

Visual Studio JIT debugging reports Qt5Core.pdb not loaded:

![圖片](https://user-images.githubusercontent.com/2265716/208845921-5023bb37-4f60-439d-9483-b9c0cc77ce05.png)

[NOTE]: # ( Paste debug info from Help → About here )

The KeepassXC about info:

```
KeePassXC - Version 2.7.4
Revision: 63b2394

Qt 5.15.6
Debugging mode is disabled.

Operating system: Windows 10 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.22621

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 2.19.1
```

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 11 (Build 22621.963)

**Comment by droidmonkey** [comment]
Cannot reproduce this.

**Comment by hced** [comment]
Can confirm this happened for me as well, but it seems a rare case that's hard to reproduce as it only happened once.

I'm using KeePassXC 2.7.6 on Windows 11 Pro (v10.0.22621).

Steps leading up to the (single exception) was:
1. Right-click an item to bring up context menu, then click Tags (which for some reason can't be added in my case).
2. Double-click an item, then double-click in Tags input field.

Don't think step 1 is necessary.

The weird part is that I can't add tags. (Maybe that had something to do with the crash.)

**Comment by droidmonkey** [comment]
Do you have any tags with "weird" characters?

**Comment by hced** [comment]
> Do you have any tags with "weird" characters? 

I have not been able to add any tags yet; The Tags input field is visually present, but I can't click on it and enter any text.

**Comment by hced** [comment]
> Do you have any tags with "weird" characters?

Corrrection: I mentioned I couldn't enter tags but I can, in fact do that. For some reason I don't see a text cursor in text input fields on various locations in my Windows environment (unrelated to KeePassXC).

As for weird characters, no. The crash is seemingly random and not a big problem. For me, it would occur when clicking in the Tags input field, entering some valid characters, then clicking the delete/cross, I believe. Might even happen when just beginning entering characters, I'm not sure.

Sorry for reopening this issue. There is a rarely or 'randomly' recurring crash for sure, but not a big deal. If I can pinpoint exactly when it occurs, I'll post it here.

**Comment by droidmonkey** [comment]
Yes please post if you find a repeatable path for a crash. Random crashes are, unfortunately, unfixable.

**Comment by StoyanDimitrov** [comment]
[zzzzz.zip](https://github.com/user-attachments/files/23242815/zzzzz.zip)
STR:
1. unzip and open the attached kdbx, the password is `'',,..ppyyaaooeeuuii`
2. double click on the username `uaoe`
3. click on Tags field
4. wait 1-2 seconds
5. click on Notes field
4. wait 1-2 seconds
5. go to 3.
6. may need to repeat few times to crash the application.

Additional observation: when the mouse is over the Tags field and stays normal pointer and not change to I-shaped thing the application crashes. Otherwise the input accepts the focus. It doesn't matter if there are tags in the DB or not. 
Win10, app version 2.7.10, tested on [269998](https://snapshot.keepassxc.org/build-269998/) and it crashes too (but without the error message).

**Comment by droidmonkey** [comment]
@StoyanDimitrov cannot replicate this at all

**Comment by StoyanDimitrov** [comment]
https://github.com/user-attachments/assets/867dde66-5d15-4347-ba9c-72bc5d072346

Clicking on the area where the mouse pointer is default not the I-thing app crashes.

P.S.
I post this here because the error I receive looks the same but now I'm not so sure it's the same thing.

**Comment by droidmonkey** [comment]
I saw the same mouse pointer behavior but it did not crash no matter what

**Comment by StoyanDimitrov** [comment]
It's regional settings dependant. I changed something in my regional settings and now the app don't crash. Later I'll explore the cause.

Edit:
Win+R → `control` → Region → Formats → Format → `Bulgarian (Bulgaria)` → Apply → OK
Reopen KeePassXC and click on the odd area from the previous comment.

With `Swedish (Sweden)` and `Chinese (Traditional, Taiwan)` crashes too. At first glance there are single quotes in dates.

**Comment by droidmonkey** [comment]
Ok ill check that out.

**Comment by droidmonkey** [comment]
I still cannot replicate after setting region to Bulgaria, restarting keepassxc, and doing a dance with the tags field. I recommend resintalling keepassxc.
