### ISSUE TITLE
KeePassXC won't start when clicking on .app file, but launches fine via command line

### ISSUE THREAD

**Issue by sryze** [keepassxreboot/keepassxc#8910]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Download https://github.com/keepassxreboot/keepassxc/releases/download/2.7.4/KeePassXC-2.7.4-x86_64.dmg
2. Install into /Applications
3. Click on the app

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Expected KeePassXC to launch

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Getting a message box:
"KeePassXC is damaged and cannot be opened"
![Screen Shot 2022-12-21 at 6 39 37 PM](https://user-images.githubusercontent.com/4525736/208908472-37485a49-7d81-44df-8577-1519c77b0c20.png)

## Context
[NOTE]: # ( Give us any additional information you may have. )
This is the first time I install KeePassXC on this machine. In some existing issues it's mentioned that the error might be related to some keepass process running for browser integration, but I didn't set up browser integration yet and there is no keepass processes running. Also, when I run it from the terminal via `/Applications/KeePassXC.app/Contents/MacOS/KeePassXC`, there is no error.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.4
Revision: 63b2394

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS Catalina 15.7
Desktop Env: macOS
Windowing System: macOS

**Comment by droidmonkey** [comment]
Reinstall with your browsers closed
