### ISSUE TITLE
Program always minimized after start and not operable

### ISSUE THREAD

**Issue by jim-tonic** [keepassxreboot/keepassxc#8911]
Good noon!
I have big problems to get the version 2.7.4 for Windows 64 bit to start. The program installs without any problems.

However, on startup it remains small and minimized at the bottom of the taskbar. Have tried this several times now. Unistall / Install included. And restarting the PC. Also all known key combinations under Windows 10 do not help. The program remains permanently minimized.

What can I do? For comparison I tried the last released version 2.6.6 (32bit). This works immediately without problems. I do not understand. Possibly something to do with 32bit and 64bit? The PC system is Windows 10 Pro 64 bit and runs otherwise runs fine. Current Windows updates and patches inklusieve.

Who can tell me what I am doing wrong or what the problem is? Thanks in advance.

**Comment by droidmonkey** [comment]
https://keepassxc.org/docs/KeePassXC_UserGuide.html#_screenshot_security

**Comment by jim-tonic** [comment]
Thanks for the feedback. I am currently working remotely on the PC via TeamViewer. Is this perhaps a problem? The shortcut to maximize would be what combination? I have not found in the list...

**Comment by michaelk83** [comment]
It's not possible to work remotely with screenshot security enabled, since there is no way to record the window to show it on the remote client. Follow the instructions in the user guide to disable it.

@droidmonkey I think the user guide could use an update on this, since it's not clear that it affects remote desktop and virtual clients as well.

**Comment by jim-tonic** [comment]
OK. Thank you. Working in front of the PC directly - without TeamViewer - solved the problem. Perfect. Good to know... ;-)

**Comment by droidmonkey** [comment]
You can use team viewer, you just need to launch the program with the command line switch in the documentation I linked.

**Comment by jim-tonic** [comment]
Perfect. Working for me. Problem solved. Thanxxx.
