### ISSUE TITLE
2.7.4-win64 cannot find msvcp140.dll vcruntime140.dll vcruntime140_1.dll with latest VC++ redist

### ISSUE THREAD

**Issue by tonyjonespdx** [keepassxreboot/keepassxc#8915]
I just upgraded hardware and reinstalled Windows 10 Pro.  All updates loaded.  OS Build 19045.2364

If I install "KeePassXC-2.7.4-Win64"  it installs but fails to run because it cannot find "msvcp140.dll vcruntime140.dll vcruntime140_1.dll "

I've loaded the latest VC++ redist per  https://github.com/keepassxreboot/keepassxc/issues/7564

Rebooted.   Then reinstalled KeePassXC.   Keep getting the same error.

I see the DLLs in question in C:\Windows\SysWOW64

I see the same if I run the portable KeePassXC version.

What am I missing?

**Comment by droidmonkey** [comment]
Reboot again? This isn't on our end unfortunately. Try reinstalling the redistribution package.

**Comment by tonyjonespdx** [comment]
I have reinstalled the redistribution package.    Over and over.

**Comment by droidmonkey** [comment]
Make sure C:\Windows\SysWOW64 is on your system path.

**Comment by tonyjonespdx** [comment]
@droidmonkey thinking more this doesn't make sense as WOW64 is what enables 32bit apps to run on 64bit.  
Isn't this a native x86_64 installer?
Also, why would I need to update PATH.   I know how to do it but shouldn't the installer do this?

**Comment by tonyjonespdx** [comment]
Actually WOW64 clued me in.   It shouldn't even be there as that's for 32bit apps.    It would help if I installed the 64bit redistrib not the 32 bit :(    Sorry for the noise.

**Comment by nullx5** [comment]
![MSVCP140.dll](https://i.imgur.com/4iClUsq.png)

I have a recent installation of `windows 10 22H2` and I get the same error `MSVCP140.dll` for me it worked to install a previous version `2.6.6` 

https://github.com/keepassxreboot/keepassxc/releases/download/2.6.6/KeePassXC-2.6.6-Win64.msi

**Comment by phoerious** [comment]
You need to install the MSVC redistributable libraries that are linked on the download website.
