### ISSUE TITLE
macOS Signature Verification using GPG Keychain

### ISSUE THREAD

**Issue by diegotco** [keepassxreboot/keepassxc#8919]
## Overview
I already imported your public key in my GPG Keychain program. Then, when I try to verify the signature, it fails.

## Steps to Reproduce
Do this:
![image (71)](https://user-images.githubusercontent.com/22822405/209414680-17046cd2-a050-45dd-a91d-8247fa7ac332.png)

## Expected Behavior
I don't know what to expect.

## Actual Behavior
This is the error:
![image](https://user-images.githubusercontent.com/22822405/209414738-fc1c6b1e-ab40-45ca-9a23-a7ebf6386bee.png)

## Context
-I'm stuck with the step 2: "[Verify the PGP signature](https://keepassxc.org/verifying-signatures/#:~:text=Step%202%3A%20Verify%20the%20PGP%20signature)" since this code doesn't work on my terminal `gpg --verify KeePassXC-*.sig`
-Then, I have no idea how to verify the software signature.

**Comment by droidmonkey** [comment]
Did you download the .sig file and place it in the same directory as the .dmg?

**Comment by diegotco** [comment]
Hello, @droidmonkey I'm lost here. Where can I find that file? [here](https://keepassxc.org/verifying-signatures/#:~:text=Step%202%3A%20Verify%20the%20PGP%20signature)?

**Comment by droidmonkey** [comment]
Download the PGP Signature file that corresponds to the dmg you downloaded: https://keepassxc.org/download/#mac

**Comment by diegotco** [comment]
Wow, I didn't see it, now I got that file.

But I have another "concern" now. Here is the image
![image](https://user-images.githubusercontent.com/22822405/209418792-60a742e0-92a3-4896-ad69-edd73b4ff7a1.png)

Is everything ok?

**Comment by droidmonkey** [comment]
Yes

**Comment by diegotco** [comment]
Thank you very much @droidmonkey And so sorry for the false alarm.
