### ISSUE TITLE
Firefox browser integration is failing "Key exchange was not successful."

### ISSUE THREAD

**Issue by chelmi00** [keepassxreboot/keepassxc#8921]
## Overview
I have Firefox browser integration activated and it actually works on Firefox-esr, and on Microsoft Edge. However, I want to use Firefox's latest version, and it's integration fails to work.
Versions I am using:
Mozilla Firefox 102.6.0esr
Mozilla Firefox 108.0.1
KeePassXC 2.7.4

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Install keepassxc and Firefox's extension
2. Open extension with database openned
3. Click on reload

## Expected Behavior
A popup to connect the database with its name should appear

## Actual Behavior
"Cannot connect to KeePassXC. Check that browser integration is enabled in KeePassXC settings." changes into "Key exchange was not successful."

## Context
KeePassXC - 2.7.4
Revision: 63b2394

Operating System: Linux, Kubuntu - Ubuntu 22.04.1 LTS
Desktop Env: KDE
Windowing System: X11

#### Help → About info
KeePassXC - Version 2.7.4
Revision: 63b2394
Qt 5.15.3
Debugging mode is disabled.
Operating system: Ubuntu 22.04.1 LTS
CPU architecture: x86_64
Kernel: linux 5.15.0-56-generic
Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration
Cryptographic libraries:
- Botan 2.19.1

**Comment by droidmonkey** [comment]
If version 108.0.1 is a beta release or nightly then you will have to manually specify the location of the native messaging folder. Go to application settings in KeePassXC, Browser, then Advanced Tab.

**Comment by JohnLGalt** [comment]
It's not.

<img width="547" alt="Screenshot 2022-12-26 093221" src="https://user-images.githubusercontent.com/7432512/209559171-bc70122c-c48b-469d-9567-0e6d3f51e286.png">

**Comment by EvgenyM** [comment]
Similar issue observed.

@droidmonkey Could you please let me know what additional info do you need?

The software & tools I used:
KeePassXC ver. 2.7.4
KeePassXC Browser extension Version 1.8.6.1
Firefox 112.0.1 (64-bit)

![image](https://user-images.githubusercontent.com/718183/236236747-8a8c75ec-2948-46ea-a5e9-6820cebdbf6a.png)

**Comment by gutjuri** [comment]
Same issue here with Firefox 122.0 and KeePassXC 2.7.6.
