### ISSUE TITLE
`CTRL + ,` to quickly open settings in Linux

### ISSUE THREAD

**Issue by j-lakeman** [keepassxreboot/keepassxc#8923]
## Summary
KeepassXC on Linux should have the common key combo `CTRL + ,` to open settings.

## Examples
KeepassXC on macOS already has this key combo, but also heaps other common applications like VS Code, GNOME text editor, Signal and so on.

## Context
If one frequently has to open settings, this would come in real handy.

**Comment by droidmonkey** [comment]
That seems to be a macos specific key combo
