### ISSUE TITLE
Crash when editing entry in database reports

### ISSUE THREAD

**Issue by richgriswold** [keepassxreboot/keepassxc#8925]
KeePassXC running in Linux crashes under the following scenario:

1. Open database reports (Database > Database Reports...)
2. Select Health Check
3. Double click an entry to edit
4. Click Close in lower right corner
5. Delete the same entry that you were editing
6. Empty the recycle bin
7. Re-open database reports (the same entry you were editing will still be open)
8. Click OK
9. KeePassXC crashes

Environment:

- Debian 11
- KeePassXC 2.6.2
- Linux kernel 6.0.0-0.deb11.2-amd64

**Comment by varjolintu** [comment]
Plase re-test with 2.7.4.

**Comment by richgriswold** [comment]
I tested with the 2.7.4 AppImage, and the crash does not occur.  Thank you.
