### ISSUE TITLE
Attached files in "advanced" section cannot be saved

### ISSUE THREAD

**Issue by juengling** [keepassxreboot/keepassxc#8927]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
Attached files in the "advanced" section cannot be exported. 

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Open KeypassX, double click on a key, go to "advanced" (German: "Fortgeschritten")
2. Select an attachment
3. Click on "save" (or "store; German: Speichern)
4. Select a folder
5. Click on "open"

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
The selected file shall be stored into the selected folder.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
The folder is opened and shows the containing files. Selecting a file creates an error "not a directory".

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.4
Revision: 7729648
Distribution: Snap

[NOTE]: # ( Pick choices based on your environment )
Operating System: Ubuntu 20.04.5 LTS
Desktop Env: Unity

**Comment by droidmonkey** [comment]
We don't recommend using the snap, it's rather broken on different versions of Ubuntu... switch to the flatpak or appimage.

**Comment by ghost** [comment]
I have the same problems, Linux Mint and KPXC v2.7.4 AppImage, also open url (CTL+Shift+U) doesn't work.

**Comment by droidmonkey** [comment]
The appimage has problems as well, those are not related to keepassxc code, but integration with the Linux desktop env at the appimage level.

**Comment by droidmonkey** [comment]
Closing as we are not going to expend time to fix this, use the flatpak version.
