### ISSUE TITLE
Failed in installing

### ISSUE THREAD

**Issue by y-mk-yc** [keepassxreboot/keepassxc#8929]
![image](https://user-images.githubusercontent.com/74123687/209884539-acc2dd22-07c5-4d3f-8505-15e0e7edebf9.png)
I try to download installer and portable, but both failed in opening the software.

**Comment by droidmonkey** [comment]
What operating system are you running exactly?

**Comment by y-mk-yc** [comment]
Win10

**Comment by droidmonkey** [comment]
Exact version and 32 or 64 bit? Have you tried the legacy installer?
