### ISSUE TITLE
font bug

### ISSUE THREAD

**Issue by morytyann** [keepassxreboot/keepassxc#8931]
## Overview
in 2.7.x, type `Fab Jab Pab Vab Wab ` in search box, you can see the letter 'a' is too wide

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. open keepassxc version 2.7.x
2. type `Fab Jab Pab Vab Wab ` in search box

## Expected Behavior
regular letter spece  like when you type `Job` in search box

## Actual Behavior
the letter 'a' is too wide

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.4

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 11

**Comment by droidmonkey** [comment]
![image](https://user-images.githubusercontent.com/2809491/209944472-1f7c7c34-285f-4041-9382-973012074ed8.png)

Must be your computer not KeePassXC? We don't control font rendering.

**Comment by morytyann** [comment]
![image](https://user-images.githubusercontent.com/10665459/210472810-3ae7e731-2160-4920-86cb-be1460877876.png)
![image](https://user-images.githubusercontent.com/10665459/210474150-90b583f2-bc4f-4b59-8e31-04d207c11420.png)
Here are screenshots of the two versions.
Both of my computers have this problem ,but it works fine in my wife's laptop

**Comment by droidmonkey** [comment]
Look at the e's, they have the same problem. Are you running keepassxc in compatibility mode by chance? Does this happen to the 'legacy windows' version as well?

**Comment by morytyann** [comment]
> Look at the e's, they have the same problem. Are you running keepassxc in compatibility mode by chance? Does this happen to the 'legacy windows' version as well?

No, I've never run it in compatibility mode.
Yes, this happen to the 'legacy windows' version as well.

btw, I also installed it in a new virtual machine, and the problem still exists.
I change the language to english in virtual machine, and the problem gone...

**Comment by morytyann** [comment]
![image](https://user-images.githubusercontent.com/10665459/210515712-5e2de4ec-b394-49b4-badd-eea7c5235e2c.png)
when QT_SCALE_FACTOR not set to 1, the problem gone...
maybe this can help you to locate it.

**Comment by droidmonkey** [comment]
Not our problem, this would be a qt problem
