### ISSUE TITLE
Enable URL masking & username data encryption

### ISSUE THREAD

**Issue by vdbhb59** [keepassxreboot/keepassxc#8932]
## Summary
Based on the LastPass breaches and vault thefts, I realized that ideally the URL section as well as the username on the KeepassXC is not encrypted, but more plaintext. I am not aware if for an offline database (basically not cloud based) should have this, but I believe if this can be done, it would be really good, so that users get more safety.

Unless I have overlooked any setting, or otherwise, I would really like this feature to be made available, please.

## Examples
Unable to show any snapshot, as KeepassXC blacks out (the inbuilt security feature). But I believe, you get what I am trying to say here.

## Context
Given the LastPass recent double data breaches and vault thefts, this feature is a must have as per my understanding, even though the database is offline.
This is me playing a plain conjecture of the issue at large, and maybe KXC has something better up its sleeves?

**Comment by droidmonkey** [comment]
Everything is encrypted in a keepassxc database.
