### ISSUE TITLE
transfer keypass search term into Title of new entry

### ISSUE THREAD

**Issue by ghost** [keepassxreboot/keepassxc#8934]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
Prior to version 2.7.4, a search term was automatically transferred into the title of a new entry but this has now been removed?  How can I return that feature?  If I can't, can you please return that feature?

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Search for a record within KeypassXC.
2. If the search is not found then click add & that search term is transferred to the Title of the new entry.
3. Current version does not transfer the search term into the title of a new record.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Prior to version 2.7.4, a search term was automatically transferred into the title of a new entry.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
When performing a search & no record is found, clicking add a new record deletes the search term requiring it to be retyped.

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION 2.7.4
Revision: REVISION 63b2394

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS
Desktop Env: macOS
Windowing System:

**Comment by droidmonkey** [comment]
No this was explicitly removed. It made no sense since you can have advanced search terms and multiple users were confused by this. I can't imagine many scenarios where a search (usually a fragment of text) is what you actually want in your entry title.

**Comment by ghost** [comment]
While you cannot see any sense to this feature, others do and it was being used in this way.  I also noticed that you have removed search results for searches on parts of a tag.  So now tag searches containing "pest" do not display all results containing the word "pest", such as "pest control" and "pest treatment".  The previous search result methods were very convenient.  These new changes are not as user friendly and I cannot see the sense of your reasoning for removing them.

**Comment by droidmonkey** [comment]
Just add a * after the tag string like: `tag:pest*`

Tags search must default to exact match because of this very reason. Otherwise it would make tags rather useless at binning entries.

**Comment by ghost** [comment]
Thank you.
