### ISSUE TITLE
Importing another KeePassXC database into a specific folder (group)

### ISSUE THREAD

**Issue by markusd112** [keepassxreboot/keepassxc#8935]
I want to import another existing KeePassXC database file into my "master" KeePassXC database. All imported groups (folders) and items should be stored under a specific folder (group) in my master file.

When I use the "merge database" function, I cannot control, where the imported items and folders are stored: both databases are merged together.

It would be helpful to give the user the choice to merge the databases, or to import under a specified folder (group) in the destination database.

**Comment by droidmonkey** [comment]
Import the file to create a new database or open both existing databases. Drag the group or entries you want from the new/other to the main database, hover over the tab to switch. Drop the drag on top of the group you desire. 

This request is a duplicate as well.

**Comment by xxorax** [comment]
Combined with #1832 , it's a nightmare to import multiple groups and move them to the a right location :
* take times to drag & drop hover 100 folders
* impossible to move multiple groups at once

A copy paste feature in the context menu would be appropriated.
Thanks
