### ISSUE TITLE
Question - TOTP resource usage?

### ISSUE THREAD

**Issue by IceTrayz** [keepassxreboot/keepassxc#8936]
Sorry if this is a silly question but are the TOTP entries continuously generating codes or do they go into a sleep mode to save on resources as the clock icon doesn't show active/snooze state, If that made any sense?

Thanks

**Comment by droidmonkey** [comment]
Totp codes are calculated based on the secret code and current time value of your system. There is zero overhead involved. No resources at all are being consumed.
