### ISSUE TITLE
Yubikey stopped working after running apt autoremove

### ISSUE THREAD

**Issue by ovz93br43v7** [keepassxreboot/keepassxc#8937]
Hello,

I'm using KeepassXC 2.7.4 (ppa version) with a Yubikey 4.

After running `apt autoremove` some essential packages for the yubikey were automatically removed. (`libyubikey-udev:all`)

After getting some panic because my Keepass wasn't able to find the yubikey anymore, I solved that by reinstalling the lost packages. 

I don't know whether the Keepass Team can influence this behaviour?!? Because `apt` assumed these packages as "not needed anymore".

Thanks for this great piece of software!

**Comment by droidmonkey** [comment]
No we can't, those wouldn't be essential for us. You only need the udev package for keepassxc.
