### ISSUE TITLE
Using multiple Yubikeys with Keepass

### ISSUE THREAD

**Issue by marno2703** [keepassxreboot/keepassxc#8938]
## Overview
I'm using multiple Yubikeys with the same key for my database. Keepassxc doesn't open the database when the key changes. Seems like keepassxc checks the yubikey-serial.

## Steps to Reproduce
have two yubikeys configured with the same key, open the database with the key from yubikey 1.
let keepassxc run into timeout and lock the database.
try to open database with yubikey 2.

close the database.
open the database with yubikey 2.
let keepassxc run into timeout and lock the database.
try to open database with yubikey 1.

## Expected Behavior
keepassxc should open the locked database with every yubikey that offer the correct key.
(Perhaps make that configurable)

## Actual Behavior
keepassxc does not open a locked database with another yubikey then the one the database was initially opened.
The only way is to close the database and open it again with the other yubikey.

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.4
Revision: 63b2394

[NOTE]: # ( Pick choices based on your environment )
Betriebssystem: macOS 12.2
CPU-Architektur: arm64
Kernel: darwin 21.3.0

**Comment by droidmonkey** [comment]
I cannot replicate this at all.

![2022-12-30_15-00-53](https://user-images.githubusercontent.com/2809491/210107845-7ae0ad62-f256-4ed9-820d-1ed38d05f290.gif)

**Comment by silentbrains** [comment]
I wonder if it's in relation to Quickunlock. I was able to reproduce it this way: with two keys, only the key used to originally unlock the database is accepted when trying to unlock via Quickunlock.
(Note: I'm using a different OS (Windows 10))

![20221230-12_12_03](https://user-images.githubusercontent.com/13858149/210108690-7990c1c7-2fd8-4cb0-bb06-64504eab53ea.png)

**Comment by droidmonkey** [comment]
Correct, you cannot swap keys while still in "Quick Unlock" mode, hit cancel to do a full unlock. Also we don't recommend using the classic theme, it is rather terrible. Switch over to our Light Theme (View menu).
