### ISSUE TITLE
Setting the Pasteboard Type to a password type

### ISSUE THREAD

**Issue by gotjoshua** [keepassxreboot/keepassxc#894]
## Expected Behavior
When I choose copy password from a keepass entry, It should use a specific pasteboard type for passwords. I am not sure what the best choice is for this (if there is a meaningful convention). I would like to use flycut - which offers the possibility to filter based on pasteboard type, but keepass uses the same type as any normal text.

## Current Behavior
instead It uses the default pasteboard type: NSStringPboardType

## Possible Solution
possibly useful:
http://nspasteboard.org/
https://github.com/TermiT/Flycut/pull/117

## Debug Info
KeePassXC - Version 2.2.0
Revision: caa49a8ef3ee28ed478192389b21d61107b3b8e0

Libraries:
- Qt 5.9.0
- libgcrypt 1.7.7

Operating system: OS X El Capitan (10.11)
CPU architecture: x86_64
Kernel: darwin 15.6.0

Enabled extensions:
- KeePassHTTP
- Auto-Type
- YubiKey

**Comment by droidmonkey** [comment]
Is this a Mac specific thing?

**Comment by gotjoshua** [comment]
Could be... I'm not sure. I am on a mac and trying to run flycut (a mac
only app)...
I wonder if other platforms have something similar...

~
.:.joshua

“Our lives are not our own.
   We are bound to others, past and present,
     and by each crime and every kindness,
       we birth our future.”
           ― David Mitchell
<https://www.goodreads.com/author/show/6538289.David_Mitchell>, Cloud Atlas
<https://www.goodreads.com/work/quotes/1871423>

"Avoid the pursuit of happiness. Seek to define your mission and pursue
that."
   ― John Perry Barlow
<https://www.goodreads.com/author/show/273206.John_Perry_Barlow>

"Life is a series of gestures, into which we embed meaning..."
   ― *Joshua Gottdenker*

**Comment by carpeliam** [comment]
Was this released in v2.3.0? I've installed 2.3.1, and Flycut still reports passwords as `NSStringPboardType`.

**Comment by weslly** [comment]
@carpeliam [Flycut](https://github.com/TermiT/Flycut/pull/117) doesn't seem to support this feature yet.

**Comment by gotjoshua** [comment]
yeah, I uninstalled flycut for this reason - too insecure to have passwords stored free text in a clipboard stack...

**Comment by drorata** [comment]
It's not clear - is it a `keepersxc` issue or is it a problem with `flycut`? Was anyone able to find a solution for this?
