### ISSUE TITLE
FlatPak version requires KDE runtime on Gnome

### ISSUE THREAD

**Issue by mitohund** [keepassxreboot/keepassxc#8943]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
I would like to be able to install the FlatPak version of KeePassXC (only 16.8 MB in size) on Gnome without needing to install hundreds of MB of KDE dependencies.

I apologise if this is a naive expectation. I am new to FlatPak and only trying it out since I unfortunately ran into an issue with the AppImage.

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
Space is an issue on the affected system.

**Comment by droidmonkey** [comment]
Not possible. The kde package provides qt.

**Comment by michaelk83** [comment]
That said, you might be able to install qt without the rest of KDE?
(Though it may still be large: just the `libqt...` packages are over 250M on my system; all `*qt*` packages are almost 320M. But maybe not all of them are needed.)

**Comment by droidmonkey** [comment]
Is not actually kde, is the kde sdk which is qt

**Comment by mitohund** [comment]
Thank you, I understand. Are there other downsides to installing the KDE runtime aside from space - performance hit to the system, security attack surface, etc.?

**Comment by droidmonkey** [comment]
none at all, this is how flatpaks work which makes them 100x better than snaps. Any flatpak you install that needs Qt will use the same KDE runtime install which saves a ton of space and ensures the latest version is used.

**Comment by mitohund** [comment]
That sounds great. Is there a performance difference between running KeePassXC natively or as an AppImage under Gnome as opposed to Flatpak via KDE runtime on Gnome? It just feels so inefficient to run something on Gnome via a KDE runtime.

Sorry I keep asking questions. I would think this is the last one though. :-)

**Comment by droidmonkey** [comment]
They run the same, it's all native compiled code. You are overthinking this kde runtime thing. It really has nothing to do with kde, kde just happens to curate Qt open source.

**Comment by mitohund** [comment]
Alright, thank you for your patience and the explanation! I went ahead and installed the flatpak and it looks nicer than the Debian repo version.
