### ISSUE TITLE
QR code is stretched horizontally within its window

### ISSUE THREAD

**Issue by phallobst** [keepassxreboot/keepassxc#8944]
## Overview
Resizing the QR code display window horizontally distorts the QR code itself, i.e. it's not square anymore.

## Steps to Reproduce
1. Select "TOTP / Show QR Code" from the context menu of an entry.
2. Resize the window horizontally.

## Expected Behavior
The QR code should always be square, centered and as large as possible within the limits of its allocated window are. (If the window is resized _vertically_, the program behaves correctly.)

## Actual Behavior
The QR code is stretched horizontally, covering the whole width of the window. Scanning it with a smartphone camera will not work correctly.

## Context
KeePassXC - Version 2.7.4
Revision: 63b2394
Qt 5.15.3

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: Cinnamon
Windowing System: X11

**Comment by droidmonkey** [comment]
Cannot replicate on Windows so this must be a bug on macOS and Linux only...

**Comment by dmaslenko** [comment]
I was able to reproduce it on Linux:
![stratched-qr-code](https://user-images.githubusercontent.com/121412908/214191703-2b0e4fde-937c-43ef-8ce4-a3ee06394732.png)
At the same time the vertical window sizing does not change the QR code proportion.
Let me check what can we do to fix it...

**Comment by droidmonkey** [comment]
Does it need to be fixed? Just don't size the window in one dimension, use the corner resize. I tried to fix it and it seemed impossible no matter what I did.

**Comment by dmaslenko** [comment]
Right, let's have it as plan B.
For plan A I've got some result but need to find a solution to center the QR code to avoid much space on the right side:
![fixed-qr-code-not-centered](https://user-images.githubusercontent.com/121412908/214232987-7c630a41-0d45-479a-9543-cfbc92af5015.png)

**Comment by dmaslenko** [comment]
Now I have a pretty simple solution for this variant:
![fixed-qr-code-centered](https://user-images.githubusercontent.com/121412908/214470114-3fcdfc17-908d-4339-8608-908dbf8998fd.png)

```c++
    auto svgWidgetLayout = new QBoxLayout(QBoxLayout::LeftToRight);
    svgWidgetLayout->addWidget(m_totpSvgWidget, 0, Qt::AlignCenter);
    m_verticalLayout->addLayout(svgWidgetLayout);
```

Is it ok to have fixed size QR code or it should be resized to fill window as well?
It is possible but required recalculation and resizing on the fly that may impact on smooth rendering.
Let me know...

**Comment by droidmonkey** [comment]
The point of allowing the window to resize is so that the qr code resizes as well. If it stays a fixed size, then this didn't solve the problem.

**Comment by dmaslenko** [comment]
Sure, I will try...
