### ISSUE TITLE
Different second-level domains under the same first-level domain cannot match the same entry

### ISSUE THREAD

**Issue by LittleNewton** [keepassxreboot/keepassxc#8947]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Create a entry with URL likes `https://test-url.com`
2. Open URL `https://sec.test-url.com/`
3. The entry in step 1 **cannot match**

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Once I used BitWarden which was a good tool but cannot inject autofill in the web page. BitWarden's URL matching policy is very good. **Same domain name with different TCP/UDP port can be recognized as different hosts.** For example, `tomcat.com:1999` and `tomcat.com:1998` can match different entries.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
KeePassXC would recognize `tomcat.com` and `tomcat.com:xxx` as the same website and provide the same entry or provide two different entry for each of the two urls.

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.4
Revision: 63b2394

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 10

**Comment by droidmonkey** [comment]
Go to the browser settings tab when editing entry and add additional urls. Read the user guide for more info.
