### ISSUE TITLE
Windows Admin Center web auth and vPro web auth cannot be filled automatically

### ISSUE THREAD

**Issue by LittleNewton** [keepassxreboot/keepassxc#8948]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
![image](https://user-images.githubusercontent.com/17793356/210250678-4433520c-2eaa-4164-a260-df7f6ebbbc6f.png)

In some special webpage, the authentication need to fill a box like `MessageBox.show()` style. In this situation, it seems that KeePassXC cannot fill it up automatically. Example can be seen in this image.

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )

- Intel vPro
- Microsoft Windows Server's `Admin Center` app

both of them are very essential apps.

**Comment by droidmonkey** [comment]
Use auto type, read the user guide
