### ISSUE TITLE
New entry not possible if search is 'active'

### ISSUE THREAD

**Issue by Daniel-Krebs** [keepassxreboot/keepassxc#895]
When you searched via search bar, it's not possible to add new entries until you clear the search results (doesn't matter if you got any results). Is this somehow intended?

## Expected Behavior
Allow adding new entries even if a search is active.
 
## Current Behavior
"Add new entry" button is greyed out.

## Debug Info
KeePassXC - Version 2.2.0
Revision: caa49a8ef3ee28ed478192389b21d61107b3b8e0

Bibliotheken:
- Qt 5.7.1
- libgcrypt 1.7.8

Betriebssystem: Fedora 26 (Workstation Edition)
CPU-Architektur: x86_64
Kernel: linux 4.12.5-300.fc26.x86_64

Aktivierte Erweiterungen:
- KeePassHTTP
- Auto-Type
- YubiKey

**Comment by droidmonkey** [comment]
This is intentional. Press escape to cancel the search or hit the x button.

**Comment by Daniel-Krebs** [comment]
OK. May I ask why?

**Comment by droidmonkey** [comment]
I can't think of a specific one come to think of it besides group scope. I'll give this a looksie.

**Comment by spaetz** [comment]
Thanks for considering to "fix" this. Let me add that there is no issue with group scope. When searching you are still within a specific group and hitting the "add" button will lead to no surprises. As for the use case:
I often start searching for an entry on an open web site and noticing that there is none yet, I want to create a new one. Not being able to just hit "add" but having to clear the search before is an additional and IMHO unnecessary step.

**Comment by TheZ3ro** [comment]
> I often start searching for an entry on an open web site and noticing that there is none yet, I want to create a new one.

I was thinking about this when using keepassxc myself.

Creating a new entry while searching should set the new entry Title to the search text.

Ex: I search for `Github`, no entry available, I press Add Entry, the Title is automatically set to `Github`

**Comment by Daniel-Krebs** [comment]
That would be really convenient.
