### ISSUE TITLE
unknown software exception 0xc0000094

### ISSUE THREAD

**Issue by feofan69** [keepassxreboot/keepassxc#8950]
## Overview
Start of program with user right not possible. "Error Die Ausnahme "unknown software exceprtion" (0xc0000094) ist der Anwendung an der Stelle =x00007FF9A71C8C31 aufgetreten 

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
Start programm without admin rights. If I startprogramm as administrator then program working fine

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.4
Revision: 63b2394

Qt 5.15.6
Diagnosemodus ist deaktiviert.

Betriebssystem: Windows 10 Version 2009
CPU-Architektur: x86_64
Kernel: winnt 10.0.22000

Aktivierte Erweiterungen:
- Auto-Type
- Browser-Integration
- SSH-Agent
- KeeShare
- YubiKey
- Schnelle Entsperrung

Kryptographische Bibliotheken:
- Botan 2.19.1

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 11 V. 21H2 (Build 22000.1335)

**Comment by droidmonkey** [comment]
Unfortunately nothing we can do with the info provided. Try reinstalling and make sure you have the latest visual c++ redistribution package installed. Also make sure you don't have an antivirus program or similar blocking our application.
