### ISSUE TITLE
Delete Entry should have a warning toast message

### ISSUE THREAD

**Issue by JasonPWhite** [keepassxreboot/keepassxc#8951]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
For KeePassXC on mac, I suggest some sort of warning toast pop up or undo option. 

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )

----------------------------------------
|    You are about to delete this entry!     |
|                    Are you sure?                        |
|                                                                   |
|            YES                         NO                  |
----------------------------------------

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
Delete Entry icon is a loose canon.  I deleted an entry by mistake and there was no warning or undo.

**Comment by droidmonkey** [comment]
Enable it in the application settings. By default we don't ask because it actually places it in the database recycle bin. We by default ask before any permanent deletion.

**Comment by JasonPWhite** [comment]
Thanks for your quick response.

I looked in app setting but the option instruction was not intuitive for me.

I have now set it accordingly.

Kind regards,

Jason
