### ISSUE TITLE
Database encryption settings not translated

### ISSUE THREAD

**Issue by xesarni** [keepassxreboot/keepassxc#8952]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

KeePassXC displays some translated strings in English.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Change KeePassXC's language to Polish (100% on Transifex).
2. Check out these strings:

Argon2d (KDBX 4 – recommended)

Restore Entry(s)

Twofish 256-bit

AES 256-bit

ChaCha20 256-bit

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
The strings are translated on Transifex and should be in KeePassXC as well.

Argon2d (KDBX 4 – zalecany)

Przywróć wpisy

Twofish:  256-bitowy

AES 256-bitowy

ChaCha20 256-bitowy

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Strings mentioned above are hard-coded in English.

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.4
Revision: 63b2394

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 10 22H2

**Comment by droidmonkey** [comment]
That doesn't mean they were translated at the time of release. They will be in the next one.

**Comment by xesarni** [comment]
They were translated many months ago. Also providing complete QM translation file won't resolve this issue,

**Comment by droidmonkey** [comment]
I see what is happening, these strings are defined as global objects and they are instantiated before the localization is set for the application.

**Comment by xesarni** [comment]
https://github.com/keepassxreboot/keepassxc/pull/8954

But what about "Restore Entry(s)"?

**Comment by droidmonkey** [comment]
That just needs to be translated in transifex

**Comment by xesarni** [comment]
So this string is translated in the Recycle Bin as it should.

But it also appears (in English only) here and is broken because it obviously doesn't restore entries when the database is closed/locked:

![KPXC](https://user-images.githubusercontent.com/25767588/211012941-45922a43-1706-44ca-ac54-2fd395507756.png)

**Comment by droidmonkey** [comment]
That is a bug

**Comment by xesarni** [comment]
Should I create a separate issue for the "Restore Entry(s)" bug?

**Comment by droidmonkey** [comment]
I am adding this to my accessibility fixes PR now, no need for additional issue
