### ISSUE TITLE
Additional URLs with varying username

### ISSUE THREAD

**Issue by klitoskyriacou** [keepassxreboot/keepassxc#8958]
Currently, when multiple domains use the same username and password, we can specify "Additional URLs" in the "Browser Integration" tab. This is very useful as it allows us to keep only one set of username and password for all the URLs that use the same credentials. Unfortunately, it doesn't go far enough. In one set of URLs that use the same LDAP credentials, one site might use the username `joebloggs`, another site might use `DOMAIN\joebloggs`, and a third site might use `joebloggs@example.com`. All three use the same password, but different variations of username.

It would be great if you could support a way of specifying an alternative username together with alternative URLs.

**Comment by droidmonkey** [comment]
Use entry clones/references, read the user guide for more information
