### ISSUE TITLE
Can't import 1Password data

### ISSUE THREAD

**Issue by pb4072a** [keepassxreboot/keepassxc#8961]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Open KeepassXC on my Mac.
2. Click on "Import from 1Password."
3. Nothing happens.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
I expect the app to be able to import 1Password security data.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Nothing happens. I choose "Import from 1Password." The file exported from 1P shows up as gray and unusable.

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION 2.7.4
Revision: REVISION 63b2394

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS
Desktop Env: Gnome/KDE/XFCE/Mate/Cinnamon
Windowing System: X11/Wayland

**Comment by droidmonkey** [comment]
You need to have 1password still installed in order for the folder to be seen as a "file".

**Comment by pb4072a** [comment]
Thanks. It is still installed. The export file from 1Password is: 1PasswordExportxxx….csv.
Or
It’s: 1PasswordExportxxx….1pux.

Thanks,
Peter

**Comment by droidmonkey** [comment]
We don't support 1pux yet, that is still being worked on. If you want to import csv use the csv importer...

**Comment by pb4072a** [comment]
Thanks. I'll try that. And let you know.
Cheers.

**Comment by pb4072a** [comment]
OK. Cool. I've imported my .csv file. It appears all of my data is in there. Now, on the left screen of this app I see "Root," with a bunch of subentries. What in the world is that? This app is so secure that it won't let me create and send screenshots!

**Comment by droidmonkey** [comment]
Recommend reading our getting started guide (help menu)

**Comment by pb4072a** [comment]
Right. Thanks!
