### ISSUE TITLE
"Synchronized" should read "Synchronised earlier"

### ISSUE THREAD

**Issue by wintru** [keepassxreboot/keepassxc#8962]
## Overview
The message "Synchronized with ..." could be interpreted as an action that just has completed or as the current state. Even with the .kdbx not available the message gets displayed.

## Steps to Reproduce
1. Click on a KeeShare enabled group name of type "Synchronize" and with all messages enabled

## Expected Behavior
Example wordings, in order of amount of change:

Synchronized **earlier** with ...
KeeShare Type "Synchronize", Path ...
Synchronized with ... **on TIMESTAMP**

## Actual Behavior
The message "Synchronized with ..." pops up regardless of the actual state of synchronisation, which might have failed.

## Context
KeePassXC - Version 2.7.4
Revision: 63b2394

Qt 5.15.6
Debugging mode is disabled.

Operating system: Windows 10 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.19045

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 2.19.1

Operating System: Windows
Desktop Env: 
Windowing System:

**Comment by droidmonkey** [comment]
These will be completely changed when I finish refactoring keeshare. This work is tracked elsewhere on the issue board.
