### ISSUE TITLE
Add additional info to infobar on bottom

### ISSUE THREAD

**Issue by newhinton** [keepassxreboot/keepassxc#8965]
## Summary
Some applications put information on the bottom of the window.
Libreoffice as an example has a wordcount, and keepass currently shows the entries available in the current selection.

Maybe it would be useful to add (a bit) more information there, i think it could be useful to show the amount of expired entries in the current selection.

Eg.: 100 Entries / 5 Expired

## Context
This was just a quick idea i had while exploring the "show expired entries on unlock"-option (Or what else it is called in english)
Version: Keepass 2.7.4

**Comment by droidmonkey** [comment]
Not sure what else would be relevant there. Number of expired entries is rather specific and almost always going to be 0.
