### ISSUE TITLE
CLI open command doesn't keep the session open for piping further commands

### ISSUE THREAD

**Issue by mbeko** [keepassxreboot/keepassxc#8969]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
As [explained in this discussion](https://github.com/keepassxreboot/keepassxc/discussions/8231), I want to use multiple passwords from a database in a script at different moments without entering the database password every time.

I have been suggested to use `keepassxc-cli open` and write to its stdin and read from its stdout. This, however, doesn't work because piping to the stdin of the command causes it to terminate immediately in any case.

After discussing with @droidmonkey and @louib, I was asked to create an issue.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Create a database `Passwords.kdbx` with the password "correctpw" and one entry.
2. Pipe the correct password to the open command for this database:
    ```bash
    $ echo 'correctpw' | ./KeePassXC-2.7.4-x86_64.AppImage cli open Passwords.kdbx
    Enter password to unlock Passwords.kdbx: 
    Passwords> %
    $
    ```
    The commands terminates immediately – the percent sign is added by my shell to mark the end of stream.
4. Try the same with an incorrect password and observe the same effect:
    ```bash
    $ echo 'wrongpw' | ./KeePassXC-2.7.4-x86_64.AppImage cli open Passwords.kdbx
    Enter password to unlock Passwords.kdbx: 
    Error while reading the database: Invalid credentials were provided, please try again.
    If this reoccurs, then your database file may be corrupt. (HMAC mismatch)
    $
    ```

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
The interactive session stays open after having provided the correct password.

This way, I could open the database in the background with stdin and stdout connected to named pipes, so I can send commands like `show` and use the outputs in various places in my script. 

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
As shown in the steps to reproduce, the open command terminates immediately which doesn't allow sending further commands.

## Context
[NOTE]: # ( Give us any additional information you may have. )
I have seen #8878 which seems related, but the issue description wasn't entirely clear. 

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.4
Revision: 63b2394
Distribution: AppImage

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: XFCE
Windowing System: X11

**Comment by Juhaz** [comment]
There seems to be some misunderstanding here. keepassxc-cli in the example terminates because once the command being piped ends it's stdout - the stdin of the next command in pipeline - is closed and there is nothing to read any further input from so it's pointless to keep running. There isn't really anything that can or should be done to "fix" this on the keepassxc side.

If you do use named pipes like you said you intend to - and take pains to ensure the pipe keeps open, no direct redirects into the pipe, which again close it after the command completes - everything does work as expected.

This works for example:
```
#!/bin/sh

rm /tmp/test.db
printf 'pwd123\npwd123\n' | keepassxc-cli db-create /tmp/test.db -p
keepassxc-cli open /tmp/test.db < /tmp/kppipe &

echo "opening pipe..."
exec 3>/tmp/kppipe
sleep .1
echo pwd123 >&3
sleep .1

echo "adding entry"
echo add myentry -u user -p >&3
echo secure123 >&3
sleep .1

echo
echo "listing entries"
echo ls >&3
sleep .1

echo
echo "getting pwd for myentry"
echo show -s myentry>&3
echo exit >&3
exec 3>&-
sleep .1

echo "done."
```

Keep in mind though that it is really rather hard to communicate with interactive processes using simple shell commands (evidenced even in this trivial example by the sleeps which are in place as a naive attempt to ensure that the cli is ready to process further input - things can easily go wrong otherwise) and using something like `expect` that is designed to deal with this would be a very good idea.

**Comment by mbeko** [comment]
Thanks for the explanation. I wasn't aware that this is an issue out of KeePassXC's scope because the discussion with the maintainers seemed to indicate that opening and piping commands should work.

Without having experience with named pipes, I had made a quick experiment before I created the issue:
```shell
keepass_test() {
	mkfifo /tmp/in
	mkfifo /tmp/out

	keepassxc-cli open /tmp/Passwords.kdbx < /tmp/in > /tmp/out &
	printf 'correctpw' > /tmp/in
	printf 'ls' > /tmp/in
}
```
The job was still running in the background after calling the function, but the output file was empty. Now I added a `sleep` in between, the result is the same. Maybe it doesn't work because I use direct redirects into the pipe, but I won't dive deeper into that if it's generally difficult to do right.

Thank you for the recommendation of `expect`, I haven't heard of it before. I will look into it and let the maintainers decide how they want to proceed with the issue.

**Comment by droidmonkey** [comment]
So we were wrong. This isn't something keepassxc can handle because the termination is happening at the shell level. @Juhaz is correct.

I did some more reading, and there is a workaround/hack using `cat`: https://unix.stackexchange.com/a/348462
