### ISSUE TITLE
Key File field is auto-filled after update, very confusing

### ISSUE THREAD

**Issue by FlorinAndrei** [keepassxreboot/keepassxc#8970]
## Overview
Windows 10. Updated to the latest KeePassXC 2.7.4 via the regular MSI installer.
Tried to open my database. It failed. Tried many times. Failed many times. Panic kicked in. Did I forget my master password? OMG, I am so screwed!
Then I noticed the Key File field was filled in. I never use that. Deleted the heck out of it, tried again - IT WORKED!!!

## Steps to Reproduce
I have not tried to reproduce it, as I do not want to downgrade back to 2.7.1. But see the Overview above.

## Expected Behavior
If the Key File was empty before the update, it should stay empty after the update.

## Actual Behavior
The Key File field is filled in with some garbage when I launch the updated app.

## Context
Folks, please try to not give your users free heart attacks.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.4
Revision: 63b2394

Qt 5.15.6
Debugging mode is disabled.

Operating system: Windows 10 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.19044

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 2.19.1

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows

**Comment by droidmonkey** [comment]
You must have upgraded from a really old version that used to have checkboxes

**Comment by droidmonkey** [comment]
We have no such code that would randomly fill in the key field. You probably accidently typed your password into the key field the first time you tried to unlock your database.

**Comment by FlorinAndrei** [comment]
@droidmonkey No, I have not. BTW, this is not the first time I've noticed this issue.

**Comment by droidmonkey** [comment]
Recommend you clear out your local config file, it probably has junk in it. C:/users/yourusername/appdata/local/keepassxc/keepassxc.ini
