### ISSUE TITLE
Notes Entry -> Add Edit Toolbar

### ISSUE THREAD

**Issue by giwrgosmant** [keepassxreboot/keepassxc#8971]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
I don't know if it's possible but it will be nice if at Notes you could implement an edit toolbar with tools like bold or hyperlink, bulleted list etc.

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
I will be able to organize the Notes much better. I find it very useful.

**Comment by droidmonkey** [comment]
Notes are plaintext, we won't be changing that. We do plan to support markdown for notes, but adding a whole toolbar is out of scope for our application and we won't be doing that.
