### ISSUE TITLE
Can not use certain characters as password

### ISSUE THREAD

**Issue by HoffmannP** [keepassxreboot/keepassxc#8975]
## Overview
It is currently not possible to use ' and  ` as a password character if the password input field is not in "visible" mode

## Steps to Reproduce
Hit \`´-key, nothing happens (alternative \` + SPACE doesn't work either)

## Expected Behavior
As in previous versions one of the two ways as described above should input the character

## Actual Behavior
No character is added (for the alternative way a SPACE is inserted)

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.4
Revision: 63b2394
Qt 5.15.3
OS: Linux Mint 21.1
Cinnamon 5.6.5
X11: 11.0

**Comment by droidmonkey** [comment]
This is a qt bug.  #918
