### ISSUE TITLE
Silly big interface which i can not make smaller

### ISSUE THREAD

**Issue by ghost** [keepassxreboot/keepassxc#8979]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )

I run 2 x 1440p monitors in 1080p  as they simply are not big enough to show the icons large enough and make text large enough to read proper 

Somehow however i can not make the always on my screen visible keepassxc interface not smaller.... KIt simply takes about 1 fifth of my screen and i have not found any solution to make it smaller 
Why i do want it smaller and do not let it go into the taskbar is simple i use it like 20 times in 5 to 10 minutes 
Everything i do is password protected so in that respect it is simply a super tool
But i do not need a oversized main screen, if it is like a fifth of its current size it would be much easier to use for me.
But it simply won't go smaller i wonder what would happen if i buy even much better screens. Do not get me wrong i love this super password manager and i think it will be very hard to get me to no longer use it.
It is simply the best i ever used, so you developer and programmers again a big thanks for this super program.
I still am infecting people to start use keepassxc anyway i hope it is possible to make it so that i can make it smaller as it helps also hiding it from culpritts if it is smaller ;) 
Now they can not overlook it xD  
## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )

**Comment by droidmonkey** [comment]
https://github.com/keepassxreboot/keepassxc/issues/8882#issuecomment-1352326097 or #5961

**Comment by droidmonkey** [comment]
You need to set QT_SCALE_FACTOR=1 or uninstall deepin related software. The problem is with your environment variables and qt detection of your screen dpi not our program.
