### ISSUE TITLE
Need help Import from LastPass

### ISSUE THREAD

**Issue by frank71244** [keepassxreboot/keepassxc#898]
I exported the csv file in Windows and copies it to a usb drive

Now I am in Ubuntu trying to import it and no matter what I do and how I try to rearrange the fields i get the same error when I try to auto-fill

Coulndt find an entry that matches the window title.  

I need exact instructions as far as what i need to do with the import tool

**Comment by frank71244** [comment]
Just forget it, who the hell has time to waste farting around with your stupid software that cant even import a csv file correctly?  

What a joke.  In 3 years you couldnt get around to fixing it?  Retards

**Comment by phoerious** [comment]
Neither do I know from your description what your actual problem is, nor am I overly interested in finding out with your attitude. Was nice talking to you.

**Comment by droidmonkey** [comment]
LOL we need a hall of fame tag

**Comment by metbril** [comment]
He created a new Github account just for the purpose of creating this issue? WTF.

**Comment by bigalgeorge** [comment]
Well Im a retired programmer and this is an issue mainly to do with Lastpass export fields.
We do need to tweak the fields from Lastpass so they fit into Keepass but we also need to have the correct instructions to do so, as Lastpass surely wont change to fit.
A partial requirement is search and replace in .csv file thusly:
&lt; replace < 
&amp; replace & 
&gt; replace >
Also set up your fields like this:
https://imgur.com/J5T5Vsy
Hope this helps some as its not so intuitive and Lastpass has really dropped the ball lately its not reliable any more.
