### ISSUE TITLE
RFE: Must not contain double characters (no two consecutive characters can be the same)

### ISSUE THREAD

**Issue by rcpao** [keepassxreboot/keepassxc#8980]
## Summary
Add a checkbox option to Generate Password which "Must not contain double characters (no two consecutive characters can be the same)".   Or to be more flexible, add a number field specifying the maximum number of consecutive characters allowed.

## Examples
None

## Context
This is a requirement on a .gov website which took many iterations to finally generate a password which fit this requirement.

**Comment by droidmonkey** [comment]
These complexity rules are being removed (slowly), they definitely don't add to security. NIST has already abolished them, and the White House has ordered them removed via executive order. 

With all that said, this is a rather rare and dumb password requirement that we prefer not to support (via a checkbox). You should just insert a character manually to break up the double chars.
