### ISSUE TITLE
KeepassXC 2.7.4 doesn't close (Windows 10)

### ISSUE THREAD

**Issue by ghost** [keepassxreboot/keepassxc#8981]
Good day ladies and gentlemans,

KeepassXC 2.7.4. 
Windows 10

Suddenly my KeepassXC apps doesn't close, It freeze when I try to clic close Windows or exit from application Menu

The only workaround is killing the task from task manager. 

I tried the classic reboot my computer but without resolving 

I tried another classic , uninstall / reinstall KeepassXC apps, it's work temporaly, Closing work but the bug reappear with time.

Thanks in advance for your help

**Comment by droidmonkey** [comment]
Never seen that behavior on Windows. Antivirus or similar program cause disruption? Without any additional information there is not much we can do here. You can try using the "legacy windows" installer to isolate from windows runtime libraries.
