### ISSUE TITLE
Yubikey: different challenge per password

### ISSUE THREAD

**Issue by flekmatik** [keepassxreboot/keepassxc#8984]
## Summary
Currently if I'd sniff response from my Yubikey (and master password) I guess I could decrypt my whole database. I was thinking that if every saved password was encrypted with different challenge (eg. url/name of the entry) then only the actually read password would be leaked (which would happen anyway), all other passwords would stay secret. I'd have to touch my ubikey separately for every password trojan wants to read.

**Comment by droidmonkey** [comment]
We will not support this as it would completely break our application  / require a complete refactor. Additionally, it is of negligible value. If you want to keep some accounts more protected then place them in their own database.
