### ISSUE TITLE
Could not save the native messaging script file for custom.

### ISSUE THREAD

**Issue by KitchM** [keepassxreboot/keepassxc#8985]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
Saw this message pop up when attempting to change settings.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Change settings, before or after opening database
2. 
3. 

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Should have saved

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Gave message noted above.

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION 2.6.6
Revision: REVISION 9c108b9

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: XFCE
Windowing System: X11

**Comment by droidmonkey** [comment]
Clear your configuration in the advanced browser settings for the custom browser. You must have a permissions issue with writing to the location you defined.
