### ISSUE TITLE
Please add a setting for displaying the password in a monospaced font

### ISSUE THREAD

**Issue by aleksandr-shevchenko** [keepassxreboot/keepassxc#8988]
Please add a setting for displaying the password in a monospaced font, similar to the setting "use monospaced font for notes".
In password field in each entry, in password field in password generator, etc.
Thanks.

**Comment by droidmonkey** [comment]
It is displayed as monospace font. If it doesn't for you then you either don't have a monospace font on your computer or it is not properly configured.
