### ISSUE TITLE
Feature Request: Link entries

### ISSUE THREAD

**Issue by berniyh** [keepassxreboot/keepassxc#8989]
## Summary
KeePassXC makes it possible to share folders via KeeShare, which is great, because I only would want a portion of my database to be accessible e.g. from my phone.
To separate the sharing possibilities from the database structure, it would be great to be able to link an entry to another folder, which then could be used via KeeShare.
This would avoid creating a database structure that is suitable for sharing or (which would be an alternative approach) entry duplication.

## Examples
e.g. you could have the following structure
database
---- folder1
-------- entry1
-------- entry2
---- folder2
-------- entry1
-------- entry2
---- folder3
-------- entry1
-------- entry2
-------- entry3
---- shared (with KeeShare activated)
-------- link to /database/folder1/entry2
-------- link to /database/folder2/entry1
-------- link to /database/folder3
------------ link to /database/folder3/entry1
------------ link to /database/folder3/entry2
------------ link to /database/folder3/entry3

The entries in shared would then be updated if the corresponding origins are changed. Changes can also be merged back.

## Context
I have a relatively large, (subjectively) well-structured database, but I would like to share a subset of the entries with my phone.
So far, I'm duplicating entries, but that has of course downsides, as I have to update them manually.
It also makes it easier to track what is shared.
Apologies if this already possible and I just couldn't find out how.

**Comment by droidmonkey** [comment]
Use references / clones, check out the user guide.

**Comment by berniyh** [comment]
Ah, it's called cross-reference, thanks.
A little bit more complicated than I hoped, but it'll do.
