### ISSUE TITLE
AutoType appears to be missing despite being activated (Debian 9)

### ISSUE THREAD

**Issue by ccoenen** [keepassxreboot/keepassxc#899]
I do not have auto type settings anywhere in keepassxc. I compiled it myself with the instructions in the readme, and I also tried again, with explicit activation of auto type. I am unsure how to debug this. I believe that `autoType()->isAvailable()` equals `false` - but I don't know why.

The about box explicitly lists auto type as activated extension.

## Expected Behavior

AutoType Settings should be available, Global AutoType should work, Ctrl+V should work

## Current Behavior
No settings, and none of the auto type shortcuts work

## Possible Solution
nothing, so far.

## Steps to Reproduce (for bugs)
On my system, you'd just need to start keepassxc and go to settings - the tab for AutoType is missing.

## Debug Info
KeePassXC - Version 2.2.0
Revision: cd46a08f4a6b983ac7ee4052aadb6c2e9fe9713f

Bibliotheken:
- Qt 5.7.1
- libgcrypt 1.7.6-beta

Betriebssystem: Debian GNU/Linux 9 (stretch)
CPU-Architektur: x86_64
Kernel: linux 4.9.0-3-amd64

Aktivierte Erweiterungen:
- Auto-Type

**Comment by ccoenen** [comment]
It might also be worth noting, that auto type does work for keepassx 2.0.3-1 from debian packages. I do not believe I have any workarounds in place for it.

**Comment by ccoenen** [comment]
I was missing the `libqt5x11extras5-dev`. apparently auto type still shows up as loaded extension.

**Comment by phoerious** [comment]
The extension loads regardless of installed runtime dependencies.

**Comment by Jonny007-MKD** [comment]
I had the same issue with my own build, `libqt5x11extras5-dev` was missing. Compiling worked with `libqt5x11extras5` alone, though.

Errors like mentioned in https://github.com/keepassxreboot/keepassxc/issues/364#issuecomment-283686976 would be really helpful, @phoerious

**Comment by gehvaugeh** [comment]
Oh thanks, this helped, also needed to install libqt5x11extras5-dev now everything works fine :+1:
