### ISSUE TITLE
check active app while auto-typing

### ISSUE THREAD

**Issue by jonnytest1** [keepassxreboot/keepassxc#8990]
## Summary
the idea being that between every keystroke thats auto typed the program will check if the active app ist still the same and only continue typing if it is - i sometimes have this where a new ap gets focused and it just continues typing , if that would focus a chat window im pretty sure my passwrods would be leaked 🤔

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )

**Comment by droidmonkey** [comment]
We already do that, the window title is checked between every key strike
