### ISSUE TITLE
KeepassXC starts minimized with a back screen, not able to close the window when use right click.

### ISSUE THREAD

**Issue by DesertFox305** [keepassxreboot/keepassxc#8991]
## Overview
[TIP]:  # Had to reinstall Windows 10 on a computer from scratch. The current & Previous windows versions were 10.0.19045 Build 19045, before the windows installation KeepassXC 2.6.4 portable was running without any issues; after the windows installation, KPXC 2.6.4 (portable) and 2.7.4 (portable), when launched from the installation folder, does not open the window to login to the database.

![image](https://user-images.githubusercontent.com/122655289/212445869-1981c6b2-abe9-4476-951e-63e93dd542e7.png)

It does not matter if I try to move/maximize the window by using the shift-right click. It won't do anything. 
![image](https://user-images.githubusercontent.com/122655289/212446011-3cf533f0-fe5c-412e-99af-52118de1a322.png)

 Sometimes the application gets stuck in the taskbar, it won't even give me the option to close the application when right-click.
![image](https://user-images.githubusercontent.com/122655289/212446060-0b76f9a3-7848-4088-80b1-b891d75ac28a.png)

I do not  know what I did that it opened minimized in the system tray, and when I double clicked it, it opened a black window, and I  googled it (keepassxc black screen) I found the first result on the search where they were talking about screenshot and found the following option [.\KeePassXC.exe --allow-screencapture], and when using the argument --allow-screencapture IT WORKS.

![image](https://user-images.githubusercontent.com/122655289/212446334-8aafdec1-2858-461a-9423-721722426cfb.png)

I am not running on a remote desktop scenario, I am working from the console. 

So I created a shortcut on the desktop, but I would like to have the feature of protecting the data against screenshots. 

Here is some information about the computer:
![image](https://user-images.githubusercontent.com/122655289/212446401-be8e27c2-24a3-4e8f-bc51-d187571b7b18.png)

Display adapter & driver information:
Installed Drivers	C:\Windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_8684909811811a7a\igdumdim64.dll,C:\Windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_8684909811811a7a\igd10iumd64.dll,C:\Windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_8684909811811a7a\igd10iumd64.dll,C:\Windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_8684909811811a7a\igd12umd64.dll
![image](https://user-images.githubusercontent.com/122655289/212446509-77fa115f-4708-4b8a-9a18-81bea9d15a99.png)

it does not matter if I am running extended screens or only one screen (this computer has double screens)

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Download the portable version, 
2. extract it on the desktop 
3. execute the KeepassXC.exe directly from the folder or create a default shortcut on the desktop

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Open the application in a window. i.e.
![image](https://user-images.githubusercontent.com/122655289/212446659-0fa8a00f-219e-467d-96d5-74251767e2e5.png)

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
![image](https://user-images.githubusercontent.com/122655289/212445869-1981c6b2-abe9-4476-951e-63e93dd542e7.png)

## Context
[NOTE]: # ( Give us any additional information you may have. )
when added the argument **--allow-screencapture** to the shortcut it works.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.4
Revision: 63b2394

Qt 5.15.6
Debugging mode is disabled.

Operating system: Windows 10 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.19045

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 2.19.1

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 10 22H2

**Comment by droidmonkey** [comment]
This is possible if you have the Nvidia screen recorder program running (or similar program).

**Comment by DesertFox305** [comment]
There is not a recording application installed on the computer.

**Comment by droidmonkey** [comment]
Make sure you have the latest msvc runtime installed (link is on our downloads page). You can also try our legacy windows version which doesn't have this dependency.

**Comment by vielhuber** [comment]
`--allow-screencapture` helped me when using a remote control software.
