### ISSUE TITLE
2.74 update only offers repair and remove options.

### ISSUE THREAD

**Issue by eps-k** [keepassxreboot/keepassxc#8992]
As read in the title when trying to upgrade from 2.7.1 to 2.7.4 there is no option for update, only Change, Repair and Remove. The change option is greyed out.
![No update option](https://user-images.githubusercontent.com/46546527/212449418-9efd6eb6-36db-4abb-b853-49776a8ee144.JPG)

**Comment by droidmonkey** [comment]
Just remove and then run it again. Not sure what happened there but it thinks 2.7.4 is already installed.
