### ISSUE TITLE
Context menu submenus broken on Windows with per monitor DPI scaling settings

### ISSUE THREAD

**Issue by cypressious** [keepassxreboot/keepassxc#8993]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

The submenus of the context menu look broken when the window is on my secondary monitor.

![grafik](https://user-images.githubusercontent.com/1191816/212471594-a5eef1b3-bf0f-47f5-a36a-a937e59b428d.png)
![grafik](https://user-images.githubusercontent.com/1191816/212471599-0137fad9-ad02-4463-a1d5-fb4021aac9d3.png)

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Have two monitors, the main monitor set to 125% scaling and the secondary set to 100% scaling.
2. Open the app on the secondary monitor.
3. Open the context menu and then one of the submenus like TORP or Tags.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
The submenu looks normal.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
The submenu font is overly large and not all of the submenu items are reachable.

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.4
Revision: 63b2394

Qt 5.15.6
Debugging mode is disabled.

Operating system: Windows 10 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.19045

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 2.19.1

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows
Desktop Env: -
Windowing System: -

**Comment by droidmonkey** [comment]
Unfortunately not something we can fix, that is a qt problem.
