### ISSUE TITLE
Hangs on SAVE when Dropbox is temporarily busy with Mozilla Thunderbird

### ISSUE THREAD

**Issue by wolframklaeger** [keepassxreboot/keepassxc#8995]
I'm using latest KeepassXC on Windows 10. The database is stored in my Dropbox. Seems like my email client Thunderbird destroys save KeepassXC database / save as. 

The TB profile is shared on my Dropbox as well. As long as Thunderbird is active, Dropbox is permanently busy, saving one or two .lock files from TB. As soon as I quit TB, Dropbox calms down, and everything is fine.

BUT: If I forget, that I am "not allowed" to save my KeepassXC database as long as TB is running, KeepassXC hangs forever. On "save", "save as", I get the error message, "I am saving already" (which is a lie).

In this state, neither "close" or "quit" work. I have to kill it via Task Manager, relaunch KeepassXC. Then everything is fine again, except my last changes, which is not that funny.

Sorry in advance, maybe I'm too verbose for GitHub, but I tried my very best :)

**Comment by droidmonkey** [comment]
I am not clear how this is a KeePassXC bug? If you pause dropbox sync does KeePassXC successfully save the file while in this fail state?

**Comment by wolframklaeger** [comment]
I am clear about the fail, from my user perspective, as described.

First of all, I'd say, it's a Thunderbird "bug", insisting on this magic parent.lock file, that cannot be syncronized by Dropbox, since it's always "new". Pity, Mozilla knows everything about it and has not changed anything for years now ...

Second, it's obviously a "bug" of Dropbox as well. Same procedure. They know it, they insist, this file must be synced, like any other update, though there is nothing to update, since it's a dumb lock file. Good idea, exclude this file from sync? Nope. Their solution does not work, at least in this case.

Finally, it's obviously a KXC "bug" as well. Why does it even care about TB and DB, running on my system by accident. May be, DB behaves weird, sometimes. For whatever reason. 

KXC should IGNORE it anyway!

It should be ROBUST under any circumstances, when the currently open database cannot be saved under the designated path. Whether it's dropboxed, local or elsewhere in the metaverse.

If I tell KXC: save my stuff now, it should PROPERLY check, if it's possible. If yes, done. If no, let me know and offer a different location, i.e. "save as".

Maybe we both can agree, at least, KXC should NEVER HANG and force its user to kill it via Windows Task Manager. 

That's the big difference to TB and DB. They both work as usual (unfortunately :) )

**Comment by droidmonkey** [comment]
Have you tried using the alternative saving methods? https://keepassxc.org/docs/KeePassXC_UserGuide.html#_advanced_save_options

**Comment by wolframklaeger** [comment]
Thank you for reminding me. Checked. Funny enough, my setting is already "Temporary file moved into place".

**Comment by droidmonkey** [comment]
#8368 is highly related. Closing as this isn't specifically a KeePassXC issue.
