### ISSUE TITLE
Translation not used (Danish)

### ISSUE THREAD

**Issue by ERYpTION** [keepassxreboot/keepassxc#8996]
## Overview
In the main menu 'Save database as...' is not translated to Danish. As far as I can tell the string was translated in Transifex more than a year ago.

## Context
The string in Transifex is actually 'Save database as' (no '...' at the end) so at first I figured that perhaps the correct string was not available for translation. However, selecting other languages in the KeePassXC settings I see that 'Save database as...' is correctly  translated for those. 

KeePassXC - 2.7.4

**Comment by droidmonkey** [comment]
No it is not translated:
![image](https://user-images.githubusercontent.com/2809491/212759575-77d0151d-b221-40e3-853a-d6df0169a213.png)

**Comment by ERYpTION** [comment]
Apologies for bringing this up again but the translation is still missing from the latest release 2.7.4. It has been a couple of months so I assume it should have been added by now? Did I make a mistake in the translation? I am not sure what the purpose of the ampersand (&) in the string is and maybe I used it wrong in the translation?

**Comment by droidmonkey** [comment]
Translations don't update automatically

**Comment by ERYpTION** [comment]
Can you elaborate on that? Should I as a translator on transifex be doing anything more than adding translations to make sure they are added?

**Comment by michaelk83** [comment]
They'll be incorporated into the next release.

Btw, the `&` marks the keyboard accelerator shortcut. For example, `Sa&ve Database As...` means that function can be activated with `Alt+v`. In the UI you will see that as an underline under the v.

edit: That may be a bit more complicated for sub-menu items. For example, on Firefox, both the top-level `File` menu and `Edit > Find in Page...` both have accelerators on F. The `Edit` menu has it on E. So `Alt+F` opens the File menu, and `Alt+E,F` activates Find in Page.

**Comment by ERYpTION** [comment]
Then it is probably not correct placing the '&' where I did in the translation. I have now removed it. Not sure I understand the shortcut function since I dont see the underline anywhere in the UI?

**Comment by michaelk83** [comment]
You may need to hold down the Alt key to show the accelerators.

**Comment by ERYpTION** [comment]
Hmm .. just highlights Database in the menu. Im on Linux. Does that make a difference?

**Comment by droidmonkey** [comment]
Qt doesn't show the underlines for some reason
