### ISSUE TITLE
Prefer local DB if network DB is currently not available ( buffer DB )

### ISSUE THREAD

**Issue by elgatobavaria** [keepassxreboot/keepassxc#9000]
## Summary

If a database is loaded from the network, save it as a "local" database for the next start. At the next start if network db is available take this one ( and save as local ). If not available take the local one.

Background:
My database is stored on a NAS. But this is not running all day. If I now need the database once, the NAS must be started first. The same applies to access via VPN from the cell phone. I dont want to sync the keepass database to a cloudhoster.

If you have any questions dont hestitat to comment.

Best regards, Mathias

**Comment by droidmonkey** [comment]
We don't have any knowledge of where your file is stored besides the folder. It is up to you to manage sync of your database file. Use syncthing or commercial cloud service.
