### ISSUE TITLE
K2A, KeepassXC syncing issue while using a YubiKey as 2nd factor

### ISSUE THREAD

**Issue by bin101** [keepassxreboot/keepassxc#9001]
## Overview
First of all: I will make a copy of this in the Keepass2Android repo, as I am not sure which of the two applications is responsible for this problem.  (https://github.com/PhilippC/keepass2android/issues/2196)

I am using my Nexcloud to sync my db and I use the HMAC

## Steps to Reproduce
1. Open the database at a desktop via KeepassXC
2. remove YubiKey but keep db at desktop unlocked
3. Open db in K2A (Keepass2Android)
4. Add/Modify an entry in K2A and let in sync
5. Check if the entry is the same at KeepassXC

## Expected Behavior
KeepassXC should show  

## Actual Behavior
KeepassXC overwrite the db file with its latest version before the modification?

## Context
K2A version: 1.09d-r0
KeepassXC version: 2.7.4

K2A file handling settings:
![Screenshot_20230117-142615](https://user-images.githubusercontent.com/12427722/212911037-409c1cb1-0938-4d62-b8c9-41dea870ea85.png)

KeepassXC file handling settings:
![PXL_20230117_133057778](https://user-images.githubusercontent.com/12427722/212911923-c78b7cee-70df-49ff-b53a-8464f04794dd.jpg)

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.4
Revision: 63b2394

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS + Android

**Comment by droidmonkey** [comment]
You are being affected by #5290. Your best course of action is to get two yubikeys and make them identical or lock your database on desktop before removing your yubikey
