### ISSUE TITLE
Support MS Edge under Linux

### ISSUE THREAD

**Issue by gromeck** [keepassxreboot/keepassxc#9002]
Microsoft Released the Edge Browser for Linux. The extension KeepassXC-Extension is also available.
Please provide support for this new browser.

https://www.microsoft.com/en-us/edge?form=MA13FJ

Thanks a lot.

**Comment by thetuxinator** [comment]
As Edge is just another Chromium based Browser, it should just work. Have you tested it?

**Comment by droidmonkey** [comment]
We did you likely need to update keepassxc

**Comment by gromeck** [comment]
I've testet with:
- KeePassXC 2.6.2
- Microsoft Edge Version 109.0.1518.52 beta (64-Bit)
- KeePassXC-Browser Version1.8.4

In the Browser Integration of KeePassXC the option Edge is disabled/greyed out.
Even with enabled Chromium support the browser integration doesn't find KeePassXC.

**Comment by gromeck** [comment]
Now I updated to KeePassXC 2.7.4. Enabling of Edge is no longer greyed out and I enabled it.
But still the browser integration doesn't find KeePassXC.

**Comment by thetuxinator** [comment]
> Now I updated to KeePassXC 2.7.4. Enabling of Edge is no longer greyed out and I enabled it. But still the browser integration doesn't find KeePassXC.

I think you may mix something, i assume Microsoft Edge -> Old Edge without Chromium and the one you need (with Chromium) would be just to enable Chromium support.

**Comment by gromeck** [comment]
> I think you may mix something, i assume Microsoft Edge -> Old Edge without Chromium and the one you need (with Chromium) would be just to enable Chromium support.

As I stated before, the Chromium support is enabled, but the browser plugin can't connect/find the database.

**Comment by thetuxinator** [comment]
You clicked on "reconnect" etc?

**Comment by gromeck** [comment]
> You clicked on "reconnect" etc?

sure

The error message is "KeePassXC-Browser hat einen Fehler festgestellt: Schlüsselaustausch war nicht erfolgreich."
(sorry, german version: english would be "KeePassXC Browser encountered an error: Key exchange was not successful.").

**Comment by thetuxinator** [comment]
I talk/read German :D i had the same error already some times, what happen if you click multiple times on reconnect?

**Comment by gromeck** [comment]
after some clicks the error mesage is still the same, but the UI offers me a link to the Wiki ;-)

**Comment by thetuxinator** [comment]
Go to Einstellungen -> verbundene Datenbanken and check if there is an entry, if not click on verbinden if there is one, remove and click on verbinden ;-)

**Comment by gromeck** [comment]
I already tried this. There is no entry for a connected DB, and "verbinden" doesn't have any effect

**Comment by thetuxinator** [comment]
Does it work with Chromium/Chrome?

**Comment by gromeck** [comment]
Yes, it works with Chromium (Version 109.0.5414.74) and Firefox (Version 102.6.0esr).

**Comment by thetuxinator** [comment]
I am sorry, i don't think i can help any further, i have no Edge installed on my Linux (and i would never install any MS Software on my Linux but thats another Story) . I found https://www.initpals.com/linux/how-to-enable-keepassxc-plugin-for-microsoft-edge-browser-in-linux/ maybe thats helpfull to you

**Comment by gromeck** [comment]
Thanks a lot, this worked for me.
