### ISSUE TITLE
If selecting text in Notes - the copy password button does nothing

### ISSUE THREAD

**Issue by Flashwalker** [keepassxreboot/keepassxc#9003]
## Overview
When selecting text in a entry Notes - the copy password button does nothing but start the clearing timer. Password is not copied and window is not minimized

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Select an entry and when select some text in entry Notes.
2. Click the copy password button.
3. Check that password is not copied.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Password is copied and window is minimized

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Password is not copied and window is not minimized

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.4
Revision: - 63b2394

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: XFCE
Windowing System: X11

**Comment by droidmonkey** [comment]
This is a known problem and one we cannot solve without making the copy password keyboard shortcut something other than Ctrl+C. Just deselect the text to resume normal operation.

**Comment by Flashwalker** [comment]
okay.jpg
