### ISSUE TITLE
Keepass XC 4.7.4 Problem multiple user with YubiKey

### ISSUE THREAD

**Issue by macabros999** [keepassxreboot/keepassxc#9004]
Hi, 

have following problem with Keepass XC, since we use YubiKey as 2FA.

YubiKey is configured to tough it for auth to work (blue line in keepass).

when Keepass DB is open up on two PC's and one change something in the DB, in normal case the second one has to touch the YubiKey again to see the changes. If this was missed or sometimes keepass didn't show up the blue line on the second PC, a message will rise with "cancle, merge, overwrite". Whatever we click, the changes made on the first PC are lost.

Hope I found the right words to descripe the Problem.

BR

**Comment by droidmonkey** [comment]
You are being affected by #5290
