### ISSUE TITLE
Random names at the end of .kdbx

### ISSUE THREAD

**Issue by jimsmith** [keepassxreboot/keepassxc#9011]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1 . Launch KeePassXC
2. Open `.kdbx` file from google drive 
3. Save back to google drive
4. `.kdbx` file is not updated instead random file names at the end of .kdbx are generated and the final file is not updated.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
No random `.kdbx` filenames
Actual `.kdbx` file is updated in google drive.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
See steps to reproduce

## Context
[NOTE]: # ( Give us any additional information you may have. )
<img width="505" alt="image" src="https://user-images.githubusercontent.com/2676701/213462958-1a365434-f685-4b40-bc06-daca2d01782c.png">

Files in google drive:
![image](https://user-images.githubusercontent.com/2676701/213463187-00127711-b596-4470-bfe1-58624717120a.png)

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.4
Revision: 63b2394

Qt 5.15.6
Debugging mode is disabled.

Operating system: macOS 13.1
CPU architecture: x86_64
Kernel: darwin 22.2.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 2.19.2

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS Ventura 13.1

**Comment by droidmonkey** [comment]
Pick one of the alternate saving methods: https://keepassxc.org/docs/KeePassXC_UserGuide.html#_advanced_save_options
