### ISSUE TITLE
Verifying identity during unlocking of database easily bypassed

### ISSUE THREAD

**Issue by wassen1** [keepassxreboot/keepassxc#9012]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Unlock you database with your master password
2. When prompted for windows pin code or finger print just press cancel
3. Then you are in!

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
You should not pass the identity test that way.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
You easily bypass the identity test by pressing cancel

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION 2.7.4
Revision: REVISION 63b2394

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 11

**Comment by droidmonkey** [comment]
All that does is not enable quick unlock

**Comment by wassen1** [comment]
I’m not sure I understand your answer fully. Please elaborate a bit more to make it clear why Windows Hello is useful in combination with Keepassxc if you can just bypass it by pressing cancel.

**Comment by wassen1** [comment]
Ok! So it’s disabling the quick unlock function if you do as described.
