### ISSUE TITLE
Add CLI option to run without opening GUI.

### ISSUE THREAD

**Issue by imnotpoz** [keepassxreboot/keepassxc#9015]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
Provide a CLI option that when used runs keepassxc without the GUI

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
I autorun keepassxc, most of the time I have it hidden in my sys tray. It would be great for it to be able to stay in the tray instead of closing it each time.

**Comment by droidmonkey** [comment]
Use keepassxc-cli....

If you mean to start minimized, then you can set that in the application options. Otherwise you'll have to wait for #7033

**Comment by imnotpoz** [comment]
Thanks, didn't know you could do that
