### ISSUE TITLE
Cannot disable checkbox for "Update native messaging manifest files at startup"

### ISSUE THREAD

**Issue by ashleysommer** [keepassxreboot/keepassxc#9016]
## Overview
I fell like I'm missing something obvious. Forgive me if this is a trivial issue. The checkbox is greyed out for "Update native messaging manifest files at startup"
![image](https://user-images.githubusercontent.com/402468/213588507-13033ab4-6dd4-4be3-921f-ce70812f7bfe.png)

What is causing this to be greyed out? I need to disable this feature, but I cannot work out how to make the checkbox work.

## Context
Using the Flatpak distribution, on Ubuntu 22.04

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.4
Revision: 63b2394
Distribution: Flatpak

[NOTE]: # ( Pick choices based on your environment )
Operating System: Ubuntu 22.04
Desktop Env:  KDE Plasma 5.26
Windowing System: KWin X11

**Comment by droidmonkey** [comment]
This was a hold over from snaps, there is no reason for this setting to be blocked off for flatpaks.
