### ISSUE TITLE
how straight forward is calculating entropy

### ISSUE THREAD

**Issue by ajay-gh** [keepassxreboot/keepassxc#9019]
## Overview
Being well aware of issue #3785 and the responses, we observe the following behavior in KeepassXC v2.7.4 : when testing the entropy calculation against that of (for example) Firefox or GPGKeychain, KeepassXC is showing a significantly different behavior.

## Steps to Reproduce
1. open KeepassXC
2. create a new entry 
3. enter any password manually and watch what happens at the entropy meter with every char you add to the password string.

## Expected Behavior
While entropy calculations can vary slightly from one implementation to another, the general behavior should always be the same (??) , see example below

## Actual Behavior
Can only be shown by example, so let's take / enter the following string "abc,.," (abc-comma-dot-comma) and see what happens. In KeepassXC, when the last comma is entered, the meter (strength) does actually go down.
In FF and in in GPG the meter stays at the value shown for the string without that last char.

## expected behavior
intuitively one would expect that an extra char may not increase entropy (much or at all), but it should not (cannot ?) reduce entropy.

## Context
This could of course be a sign of a more precise "entropy algorithm" in KeepassXC. But is that really so ? If the answer is yes, this "issue" is simply an observation. If the answer is no or unknown, this may be a bug.

KeePassXC - v2.7.4
Revision: 63b2394

Operating System: macOS

**Comment by droidmonkey** [comment]
We use zxcvbn to give an _estimate_ of a realistic entropy given the fact that password crackers take advantage of human patterns and non-random behavior. A straight line calculation of entropy will never decrease because it assumes the choice of the next character is 100% random. That is a VERY BAD assumption for passwords.
