### ISSUE TITLE
Unplugging/replugging Yubikey before saving DB causes challenge response issue in save

### ISSUE THREAD

**Issue by kalegrill** [keepassxreboot/keepassxc#902]
## Expected Behavior
(1) Opening DB with yubikey, (2) removing yubikey, (3) editing DB, (4) inserting yubikey, and then (5) saving DB should "just work".

## Current Behavior
Following those steps results in error about challenge response missing.

A workaround is completing (4) as detailed above, then going to "change master key" and checking the checkbox for challenge response. Then the yubikey is active and the "change master key" window can be cancelled and DB saved.

## Context
I unplug the key a lot without saving (maybe not the best habit). Fortunately the workaround is quick and easy but may not be intuitive to others.

**Comment by droidmonkey** [comment]
This has been fixed in pr #880. It will be released under 2.2.1.
