### ISSUE TITLE
Perform Auto-Type Didn't Work in Dropbox Login Page

### ISSUE THREAD

**Issue by gracie95** [keepassxreboot/keepassxc#9026]
Steps to Reproduce
1. Access Dropbox login page
2. Use Perform Auto-Type to fill credentials.
3. See the result.

KeePassXC - Version 2.7.4
Revision: 63b2394

Qt 5.15.6
Debugging mode is disabled.

Operating system: Windows 10 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.22621

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 2.19.1

**Comment by droidmonkey** [comment]
Dropbox desktop client or webpage?

**Comment by gracie95** [comment]
Desktop Webpage

**Comment by droidmonkey** [comment]
What does that mean, in a web browser?

**Comment by droidmonkey** [comment]
This worked fine for me in both the desktop app and the webpage.

**Comment by gracie95** [comment]
My bad.
I unchecked the "enable auto-type....." that make didn't work.
