### ISSUE TITLE
Resolution issue

### ISSUE THREAD

**Issue by elsonem** [keepassxreboot/keepassxc#9028]
## Overview
My workstation is a notebook and I use it with a monitor (LG 34WK650 34"), keyboard, and mouse externals.
Every time I turn off the monitor and turn it back on, the application's resolution changes, as if the components and buttons inside the window get bigger and with that, the mouse click doesn't work in place.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. plug a monitor to the notebook
2. open the application for normal use
3. turn off the monitor
4. turn on 

## Expected Behavior
The application window should still have the same resolution

## Actual Behavior
The resolution of components changes.

## Context

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Versão 2.7.4
Revisão: 63b2394

Qt 5.15.6
Modo de debug desativado.

Sistema operacional: Windows 10 Version 2009
Arquitetura da CPU: x86_64
Kernel: winnt 10.0.22621

Extensões habilitadas:
- Auto-Digitar
- Integração com o Navegador
- Agente SSH
- KeeShare
- YubiKey
- Desbloqueio rápido

Bibliotecas de criptografia:
- Botan 2.19.1

**Comment by droidmonkey** [comment]
Check out the Qt environment variables in our documentation: https://keepassxc.org/docs/KeePassXC_UserGuide.html#_command_line_options

The problem is likely Qt cannot properly determine your monitor dpi. You'll need to specify it manually via environment variable.
