### ISSUE TITLE
 Auto-Type {CLEARFIELD} is not working on 2.7.4  (Repeat of #6463)

### ISSUE THREAD

**Issue by crchapma** [keepassxreboot/keepassxc#9029]
## Overview
{CLEARFIELD} on Mac is only deleting the last character not the whole field

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1.     Add Auto-Type-Sequenz with {CLEARFIELD}. E.g.: {CLEARFIELD}{USERNAME}{TAB}{PASSWORD}{ENTER}
2. Use Auto-Type

## Expected Behavior
Entire userfield is cleared and new user name input, then move to password field

## Actual Behavior
Deletes last character of current user name. Types new user name onto the end of the existing user name. Then moves to password field

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.4
Revision: 63b2394

Qt 5.15.6
Debugging mode is disabled.

Operating system: macOS 13.1
CPU architecture: arm64
Kernel: darwin 22.2.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 2.19.2

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS Ventura 13.1

**Comment by luddinho** [comment]
Unfortunately it seems that this issue is only fixed for Safari.
I have tested and can confirm that revision v2.7.5 works now as expected with Safari.

But did someone have tested this fix with a different browser e.g., Chrome, Edge, Opera etc… ?

This does not work for me with Edge nor with Opera browser.

**Comment by droidmonkey** [comment]
I tested it on Edge on mac
