### ISSUE TITLE
Direct QuickUnlock without prompting user to confirm unlocking attempt

### ISSUE THREAD

**Issue by zavjah** [keepassxreboot/keepassxc#9030]
As discussed with @phoerious and @droidmonkey in [#keepassxc:mozilla.org](https://matrix.to/#/!EcUZQSzumzSBRdQSRU:vi.fi/$MPt5JR8k7TxwW6LlLv4CBr8FvF6JFHD2cT9GqTufVKo?via=matrix.org&via=libera.chat&via=mozilla.org) today, I'd like to be directly prompted for my fingerprint when QuickUnlock is enabled and the application get the focus after the first lock.

As of now, once the user has unlocked the DB for the first time and has enabled QuickUnlock, every time the app is locked and is back in focus because the user wants to use it, user first must confirm that he/she want's to actually unlock before QuickUnlock modal is shown. 

![image](https://user-images.githubusercontent.com/37732361/214859846-fa89b479-fd82-44b7-b0b6-31d4ebfd4b56.png)

As most users will activate the application for exactly that reason rather than by accident, it should be either the standard behavior or at least an option for user to select that QuickUnlock is automatically triggered. In case the application is in focus by accident, user can still abort the QuickUnlock and thus return to the main screen. Even with more than one DB open, this could be applied for the last open DB ignoring all other open DBs.

**Comment by zavjah** [comment]
Hello @droidmonkey, release 2.7.5 is out and this feature seems not to be in it. Is that correct? 

Thx and cheers,
Zavjah

**Comment by droidmonkey** [comment]
The request is still open, we ended up not working on this one.

**Comment by foss-** [comment]
KeePassXC unlock dialog, which would be great to show right away (currently requires a press of a button to be opened):
![KeePassXC unlock dialog](https://github.com/keepassxreboot/keepassxc/assets/5708172/48ab2db3-3342-496f-85f8-b9a2dfa4f286)

1Password unlock dialog with option to enter Password:
![1P unlock dialog](https://github.com/keepassxreboot/keepassxc/assets/5708172/6e04ebf8-2710-4857-baef-c021748225f3)

Three things are interesting about the 1Password implementation:

1. their unlock dialog opens in active state right away, which makes a more seamless workflow
2. the unlock dialog allows, to switch to password
3. the wording in the dialog is less technical and more approachable

**Comment by zavjah** [comment]
AWESOME, thank you :-D

**Comment by phoerious** [comment]
This is only for the modal dialog at this point, not the main window.

**Comment by zavjah** [comment]
> This is only for the modal dialog at this point, not the main window.

What exactly is the modal?

**Comment by phoerious** [comment]
Mostly when you unlock your DB from the browser extension.

**Comment by zavjah** [comment]
OK, never using this. I was referring to the main window than, as stated in my initial post. 

Why is my suggestion closed, when what I requested is not implemented? or will it come, too, in next release?

**Comment by droidmonkey** [comment]
We will consider implementing it in a future version, but this is closed because we have implemented what we want to right now.

**Comment by zavjah** [comment]
Such a pity, I was really looking forward to this. It's quite annoying to must have click on unlock few dozen times a day although it's more than obvious that one wants to use the application 😔

**Comment by phoerious** [comment]
Usually, you can also just press enter.

**Comment by zavjah** [comment]
Hello @phoerious , yes, I am aware of that but it doesn't make a great difference, if user must click or press.
