### ISSUE TITLE
Quick unlock with apple watch not working

### ISSUE THREAD

**Issue by lucein1774** [keepassxreboot/keepassxc#9031]
I have been trying to use the unlock feature and can  not get it to work with my watch.  But only works with the touchID that is on the laptop and not my Watch. 
I never get any notification on my watch for an unlock request. 
Macbook Pro 16 with M1 (2021), Apple watch series 5.

TouchID is setup on the mac and can be used for other things. 
Apple watch can be used to unlock the Mac, Make purchases and other tasks on the Mac. 

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1.  Wearing the watch and making sure it is unlocked
2.  Open KeePassXC and unlock the database with the password
3. minimize KeePassXC to lock the DB.
4. restore window and click Unlock Database button. 
5. Dialog appears:  "KeePassXC"  is trying to authenticate 
6. Watch shows not notification
7. Dialog window will timeout if I don' unlock with TouchID on the laptop

## Expected Behavior
I expect after clicking the **Unlock Database** button that there would be a notification on my watch. Allowing me to approve the unlock and the application then would be unlocked.   i would also expect ti to would work with both TouchID and the apple watch to unlock the DB.  

## Actual Behavior
Database will only unlock via the keyed password or TouchID.  Apple watch never receives a notification to allow for an unlock

## Context
KeePassXC - Version 2.7.4
Revision: 63b2394

Qt 5.15.6
Debugging mode is disabled.

Operating system: macOS 12.6 (macbook pro - 16) 
CPU architecture: arm64
Kernel: darwin 21.6.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 2.19.2

Apple Watch 
- Model: A2093 
- Version: 9.2 (20S361)

**Comment by droidmonkey** [comment]
We can only support TouchID OR Watch. You will have to disable TouchID to allow Watch to provide authentication.

**Comment by lucein1774** [comment]
I also tried disabling TouchID as suggested. But no love, the watch gives me NO notification and the dialog eventually times out or I have to click the cancel button. 
Even though though TouchID is disabled on the computer.  KeePassWC shows an error when I click cancel that it:  Failed to authenticate with TouchID. 
I rebooted and confirmed TouchID is disabled. 
so if TouchID is disabled, then the watch should work.  But it doesn't and KeePassXC still thinks TouchID is enabled. 
please advise

**Comment by droidmonkey** [comment]
Strange, it worked for other users

**Comment by dancojocaru2000** [comment]
Oddly enough, for me both TouchID and Apple Watch work.
