### ISSUE TITLE
Quick unlock issue when TouchID was used before

### ISSUE THREAD

**Issue by GoTTi74** [keepassxreboot/keepassxc#9032]
## Overview
When I open a DB with my MacBook lid opened, TouchID is enabled. I can unlock the DB only when the TouchID is available (lid open). However, when the TouchID is unavailable (lid closed) and I press "Cancel" in the unlock screen nothing happens. In previous versions the "Cancel" button was working and I could enter the master password.

## Steps to Reproduce
_PreRequisites:_ 
- MacBook with TouchID
- External monitor, keyboard and input device (mouse, trackpad, etc.)

_Preferences / Security Settings_
- [X] "Enable database quick unlock"
- [X] "Lock database when session is locked or lid is closed"

_Steps:_
1. Open a DB with the lid opened
2. Lock the DB 
3. Close the lid
4. KeePassXC shows the (TouchID) unlock screen with "Unlock and Cancel" buttons.

## Actual Behavior
Pressing "Cancel" doesn't do anything (see screen recording)
Pressing "Unlock" certainly causes an error because the TouchID is disabled while the lid is closed.
https://user-images.githubusercontent.com/34171603/214972955-3e434cee-6f50-4d64-bdcc-f25b062ce5cd.mp4

The only workaround is to either close the DB and re-open it or to open the lid and unlock the DB

## Expected Behavior
When clicking "Cancel" the default "Unlock Database" screen should come up where you can enter the master password
**Note:** With previous versions the "Cancel" button did work as expected.

[NOTE]: #
KeePassXC - Version 2.7.4
Revision: 63b2394
macOS 12.6.2 (21G320)

**Comment by droidmonkey** [comment]
OK I see what is happening, simple logic error. If quick unlock becomes unavailable then the function that resets the view bails out too fast before actually resetting the view.
