### ISSUE TITLE
KeePassXC crashes after confirming database configuration

### ISSUE THREAD

**Issue by oliversalzburg** [keepassxreboot/keepassxc#9033]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
![image](https://user-images.githubusercontent.com/1658949/215087418-fab326f6-b1a8-469d-932b-d3adafa2e7ea.png)

I had the Database configuration page open, Browser integration tab. I assumed this would be where I can enable the database for a new browser.

After not finding what I need, I connected the database through the browser and then started using my database as usual.

I returned to KeePassXC hours later to find the settings still open. I clicked OK and KeePassXC crashed with the above error.

Sorry for not having a reproduction scenario. If this isn't actionable, please close.

KeePassXC - Version 2.7.4
Revision: 63b2394

Qt 5.15.6
Debugging mode is disabled.

Operating system: Windows 10 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.19045

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 2.19.1

**Comment by droidmonkey** [comment]
Same as #7660
