### ISSUE TITLE
Drop to background without lock/minimizing after copying of attributes

### ISSUE THREAD

**Issue by zavjah** [keepassxreboot/keepassxc#9035]
Hi there,

I've switched from KeePass to KeePassXC and I miss the possibility to define, that the app should only drop to background but not minimize, when I perform a simple copying of some entry attributes. This is different with AutoType, where it is good that the app is locked/minimized.

This is solved in KeePass with two option where those action are separated: drop to background and minimize:

![KeePass_MinimizeAfterCopyingAsOption](https://user-images.githubusercontent.com/37732361/215142910-60b44097-2c9b-4ecb-8ddb-796b48470f1b.jpg)

With these two option separated, I can define, that after copying the app drops to background but not minimizes and thus stay open.

In my opinion it is a nice comfort option to have. What do you all think?

Cheers,
Zavjah

**Comment by droidmonkey** [comment]
Feature already exists:
![image](https://user-images.githubusercontent.com/2809491/215206672-e4142d61-2d99-48f9-b793-2384b8b41fb3.png)

**Comment by zavjah** [comment]
> Feature already exists: ![image](https://user-images.githubusercontent.com/2809491/215206672-e4142d61-2d99-48f9-b793-2384b8b41fb3.png)

Hello @droidmonkey, you're totally right, I've overseen that. Awesome, one more thing that make's the app even greater. thx
