### ISSUE TITLE
Show entries of subgroups option

### ISSUE THREAD

**Issue by zavjah** [keepassxreboot/keepassxc#9036]
Hi all,

what do you think about the possibility to have an option that all entries of subgroubs are shown when main group is selected, like it is there in KeePass:

![KeePass_ShowEntriesOfSubgroups](https://user-images.githubusercontent.com/37732361/215143659-a69b1714-642b-49f7-92e9-4bdfa178cb5e.jpg)

Is this maybe something for the upcoming releases?

Cheers,
Zavjah

**Comment by droidmonkey** [comment]
We have decided to not support this feature. Use tags
