### ISSUE TITLE
Increase the dimensions of custom icons from 16x16 to 128x128

### ISSUE THREAD

**Issue by GUiHKX** [keepassxreboot/keepassxc#904]
What do you guys think about that? [KeePass does it by default](https://github.com/dlech/KeePass2.x/blob/2b20dccd497ccc4c0b5fb83553cac4886c11a076/KeePassLib/PwCustomIcon.cs#L43-L45). `16x16` icons look pixelated when viewing the database on [KeePass2Android](https://play.google.com/store/apps/details?id=keepass2android.keepass2android):

![screenshot_20170829-012816](https://user-images.githubusercontent.com/626206/29804593-fd559e8a-8c59-11e7-971a-b5ba7731faa6.png)

The first and penultimate icons are `16x16`, while all the others are `128x128`.

Thank you.

**Comment by TheZ3ro** [comment]
Have you used the favicon downloader to download those 2 icon?

**Comment by GUiHKX** [comment]
No, I've downloaded those logos in a higher resolution using Google Images, then I've added them using KPXC, but they were resized to `16x16`.

**Comment by droidmonkey** [comment]
That would be it. Good suggestion
