### ISSUE TITLE
Windows System Tray overflow menu does not "unexpand"

### ISSUE THREAD

**Issue by wesnm** [keepassxreboot/keepassxc#9043]
## Overview
Running Windows 10, with Keepassxc minimized to the system tray, in some situations the popup "overflow" menu does not close after Keepassxc is restored. Normally it seems to go away after a set time, but not always.

## Steps to Reproduce
1. Maximize the application.
2. Minimize the application to the system tray with the minimize button
3. Restore the application by clicking on the icon in the system tray.

## Expected Behavior
The application will be restored and the system tray overflow will disappear shortly after restoring application.

## Actual Behavior
The application is restored but the overflow menu will not disappear unless manually closed.

## Context

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.3
Revision: d8483d3

Qt 5.15.6
Debugging mode is disabled.

Operating system: Windows 10 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.19044

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 2.19.1

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows
Desktop Env: n/a
Windowing System: n/a

**Comment by droidmonkey** [comment]
We have no control over the overflow menu in the taskbar

**Comment by wesnm** [comment]
There is no signal at all between the window manager and the application? It seems odd that this only happens with keepassxc.

**Comment by droidmonkey** [comment]
You'll have to file a bug report with Qt, we don't handle the code that interfaces with the taskbar tray. I don't have this problem on Windows 11.

**Comment by wesnm** [comment]
Alright, thanks for pointing me in the right direction.
