### ISSUE TITLE
KeePassXC Snap Package Crashes When Saving to Network Share (Samba)

### ISSUE THREAD

**Issue by taydy00** [keepassxreboot/keepassxc#9049]
### Steps to reproduce:

- Install the KeePass XC Snap package under Ubuntu 22.04 (x86_64 system).
- Create a database file, save it to a local directory
- Move this database file to a Samba share that is mounted via your file explorer/fstab
- Close KeePassXC, then reopen
- Select the database from the Samba share when prompted to open. KeePassXC will now become unresponsive

### Expected behavior:
KeePassXC should be able to open, modify, and save KeePass 2 databases that are stored on a samba share mounted locally

### Observed behavior:
Upon selecting a KeePass 2 database stored on a Samba share, the KeePassXC Snap package immediately freezes and becomes unresponsive. The program does not appear to completely crash, as no crash dialog is generated by the system (a la "this program is not responding)". This is consistent across multiple machines and networks on Ubuntu 22.04 LTS.

### Notes:
This behavior is not present in the .deb package, and this .deb package allows me to continue to use KeePassXC with a database stored on a Samba share. I've tested this at home and at work, with multiple machines, networks, shares, firewalls, etc.

This is also my first time really submitting a bug report, so if I've formatted something wrong please let me know!

**Comment by droidmonkey** [comment]
We are not supporting the snap package anymore, specifically for reasons like this. Snaps are completely unreliabe. Use flatpak or appimage.

**Comment by taydy00** [comment]
Understood. Thank you!
