### ISSUE TITLE
Auto-save the previous password

### ISSUE THREAD

**Issue by wujastyk** [keepassxreboot/keepassxc#9050]
## Summary
When I update a password, I make a note in the text area about the old password, just for extra security.  Sometimes, when things go wrong, a company or service can ask you if you recall an old password.  Or sometimes, the new p/w doesn't take hold properly.

It would be great if KeePass could automatically add a note saying something like,

> `p/w before 01/01/2023: xxxyyyzzz`  

Or, if adding a date field is fiddly, just, 

> `Former p/w: xxxyyyzzz`

**Comment by droidmonkey** [comment]
We do that already in the entry history. See the user guide for more information.

**Comment by wujastyk** [comment]
Ooooh, I see now.  I was aware of history, but I'd never clicked on an entry and seen that the full saved data is there.  Thank you so much and sorry for wasting your time.
Dominik
