### ISSUE TITLE
Automatic entry does not copy-past "@" character with French keyboard

### ISSUE THREAD

**Issue by jibalamy** [keepassxreboot/keepassxc#9051]
Hi,
When using automatic entry (without browser integration), the "@" character is not copied as expected, but replaced by "à". 
I use a French keyboard, on which both characters are on the same key (you obtain "@" by combining that key with Alt-GR). I suspect there is a problem in the copy-paste system that may not take non-English keyboard into account.
Jiba

**Comment by droidmonkey** [comment]
What version of keepassxc?

**Comment by jibalamy** [comment]
I used 2.7.4

**Comment by droidmonkey** [comment]
This is a duplicate of #8966 and/or #7610
