### ISSUE TITLE
Start and quit after 2 seconds - WinPE

### ISSUE THREAD

**Issue by ds2k5** [keepassxreboot/keepassxc#9052]
Hi,
try to build a script for https://github.com/pebakery/pebakery

The GUI of KeePassXC is show for 2 seconds and close then.
How to find what is missing ?

Which DLLs are needed that I may not found.

Using Version 2.7.4 of KeePassXC

https://github.com/keepassxreboot/keepassxc/releases/download/2.7.4/KeePassXC-2.7.4-Win64.zip

tryed the portable apps Version too - same problem

https://portableapps.com/apps/utilities/keepassxc-portable

**Comment by droidmonkey** [comment]
Use a dependency tool to figure out what is used at runtime and compare to what you have. System Informer can do that for you. You might also want to use the legacy windows version from our downloads. That doesn't use msvc runtime.
