### ISSUE TITLE
Access date not updated

### ISSUE THREAD

**Issue by ja601** [keepassxreboot/keepassxc#9053]
It would be very useful to be able to order entries by access date (column Accessed). This way, commonly used entries would bubble up and be more easily accessible. Unfortunately, this does not work properly. 

Expected behavior: You open an entry, do something like copying the password or just looking a the detail window, the access date should update to now. It does not.

**Comment by droidmonkey** [comment]
This is by design. Changing the access date would trigger a save every time you did anything in the database. This is discussed in other issues. 

If you want access to common/important entries fast, use tags.

**Comment by ja601** [comment]
Ok, I understand the bad trade-off. Then it should be taken out since the way it is, is royally confusing. You access the entry but the access date show years ago.

This leaves the issue of how to best move the most used entries to the top of the heap?

**Comment by droidmonkey** [comment]
Use tags to tag entries you love. Access time is part of the kdbx standard, not even KeePass itself uses it.

**Comment by ja601** [comment]
Thanks for the tip. 👍
