### ISSUE TITLE
Scaling issues with Multiple Monitors w/diff resulitions

### ISSUE THREAD

**Issue by C-huc-k** [keepassxreboot/keepassxc#9054]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
On Windows 10, when working with multiple monitors that have same resolution but different scaling settings the UI can become unresponsive on some monitors. Moving the XC window to the laptop monitor (not the primary) allows expected behavior. 

In my case my laptop monitor is set to 250% scaling while the external monitors are set to 200%. The problem does not occur immediately but some undetermined (so far) series of minimizing and restoring triggers the issue.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Connect external monitors (my case uses two)
2. Set all monitors to the same resolution (3840x2160 in my case) 
3. Adjust scaling on external monitors to 200%, laptop monitor to 250%
4. Use the Keepass XC interface until problem manifests - typically happens after the first few interaction when logging into websites - i believe it is related to the minimize, restore, unlock interactions between the browser.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Clicking the buttons in the XC interface should do things.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
All but the top bar will not function appropriately when on the 200% scaling screens. It is as if the buttons clickable areas are not aligned with the controls on screen. Grabbing the top bar and dragging it to the 250% screen restores functionality. Moving back to the 200% does not break it again

## Context
[NOTE]: # ( Give us any additional information you may have. )
windows 10, minimize automatically, browser integrations active

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.4
Revision: 63b2394

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows

**Comment by droidmonkey** [comment]
You will need to manually set qt environment variables to set your scaling per monitor. Read the user guide for more information.
