### ISSUE TITLE
Favicon Autodownload on entry addition

### ISSUE THREAD

**Issue by Broeckelmann** [keepassxreboot/keepassxc#9055]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
Pretty simple request. I just would like a settings option that would auto-download the favicon, when one enters a url into the url-field on entry-addition.

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
Timesaving, instead of having to manually click download favicon, it would just do it automatically if one enters an url into the url field.

PS: Thank you guys for your work, this Password-Manager is the best by far 😄.

**Comment by droidmonkey** [comment]
This feature exists already when using the browser extension. We decided to NOT implement that if you are using the application directly. There is a button next to the url entry that downloads and sets the favicon you should use.

**Comment by Broeckelmann** [comment]
Oh, I did not see that button. Thanks 👍🏻.

**Comment by Chealer** [comment]
Thanks @Broeckelmann for this report and thanks @droidmonkey for the tip.
Is there a reason why this ticket is closed?

**Comment by Chealer** [comment]
This is nearly a duplicate of #8057, which requests an option to automate this. That ticket is however currently closed as supposedly completed, even though I am experiencing the issue with the latest version (2.7.4).

**Comment by droidmonkey** [comment]
Closed completed means nothing. Github mobile app does that automatically which is super annoying. If a Pull Request is not associated with an issue then NO WORK has been done on it.
