### ISSUE TITLE
Selection window

### ISSUE THREAD

**Issue by privatier51** [keepassxreboot/keepassxc#9056]
In the current setup, when clicking on an entry, a window pops up, with from top to bottom New/Edit/Clone/Delete Entry, followed by Copy/ Password. (Sorry cannot add a screenshot.) Since username and password are the entries accessed most of the time, they should be at the top of the list. 
Thus the proposed list would have the following sequence: 
    Copy Username
    Copy Password
    Copy Attribute
    New Entry
    Edit Entry
    Clone Entry
    Delete Entry
    TOTP
    Open URL
    Perform Autotype

**Comment by droidmonkey** [comment]
That is the order. Update your keepassxc if you aren't seeing it.

**Comment by privatier51** [comment]
Thanks for your quick answer. 
My Mint20 installs version 2.4.3 from Ubuntu, and not the latest one 2.6.6, where this was apparently changed.

**Comment by droidmonkey** [comment]
The latest is 2.7.4
