### ISSUE TITLE
Attachments and URL's still cannot open from AppImage

### ISSUE THREAD

**Issue by nohing** [keepassxreboot/keepassxc#9064]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
It's not possible to open attachments and URL's from the AppImage of KeePassXC 2.7.4 and 2.7.3.
It works only with 2.7.1
When will this bug be fixed?

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. 
2. 
3. 

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION 2.7.4
Revision: REVISION 63b2394

KeePassXC - VERSION 2.7.3
Revision: REVISION d8483d3

[NOTE]: # ( Pick choices based on your environment )
Operating System: LinuxS
Desktop Env: Cinnamon
Windowing System: X11/Wayland

**Comment by droidmonkey** [comment]
2.7.5 and this is tracked elsewhere
