### ISSUE TITLE
No Directory-Sturcture in exported (KeeShare) files

### ISSUE THREAD

**Issue by xstable** [keepassxreboot/keepassxc#9065]
## Overview
I do have exported a give Directory of my `Main-Keepass` File: `Familie`.

If I do import this Keepass-File as another Keywallet, the whole Directory-Structure are lost: 
In the Image below, you see the File-Structure from the original Keepass-File, that should appear in the "Familie"-Wallet too. 
But there is only one main-directory, and all Keys lay inside this Root-Directory:

![image](https://user-images.githubusercontent.com/1778068/216779668-625abe17-c99c-4f08-8056-0c7e3caa687f.png)

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. create A Keepassfile
2. create Directory-Structure with some Sub-Directories and put Keys in it
3. Set Keeshare to a Directory (I've choosed "Syncronize" in the TYPE-Selection
4. Open this Keepass-File (you've shared via Keeshare) as new Wallet in Keepass

## Expected Behavior
Directory-Sturcture should be the same as in the Main-File, which do the keesharing

## Actual Behavior
see Screenshot above

## Context

KeePassXC - Version 2.7.4
Revision: 63b2394

Qt 5.15.7
Diagnosemodus ist deaktiviert.

Betriebssystem: Manjaro Linux
CPU-Architektur: x86_64
Kernel: linux 5.15.81-1-MANJARO

Aktivierte Erweiterungen:
- Auto-Type
- Browser-Integration
- SSH-Agent
- KeeShare
- YubiKey
- Secret-Service-Integration

Kryptographische Bibliotheken:
- Botan 2.19.3

Operating System: Linux
Desktop Env: KDE
Windowing System: X11

**Comment by xstable** [comment]
Additional Infos: 

If I add a directory in the "shared" file, it appears in the Main-File: 
![image](https://user-images.githubusercontent.com/1778068/216780139-fe222dcb-e2ec-4780-8754-c9ad176beb72.png)


# BUT
If I do add - in MAIN-File >>  directory `Test 123` - an **additional key** into this directory... and save it, the `Test 123` disappear *again* in the shared file!

![image](https://user-images.githubusercontent.com/1778068/216780332-64e49579-292c-431a-9064-60da5e892d66.png)


BTW: Same happens, if you create a brand new Keepass (e.g. in another Keepass-Application. If it has a Directory-Structure and you create an Directory `importedFromOtherKeepass`, go to Settings and activate Keeshare-Sync with that file.... if you save anything in the file, that does this import, the "imported" File will be flatten and all directories are removed.

**Comment by droidmonkey** [comment]
#3045
