### ISSUE TITLE
#improvement Make ESC work as "cancel" in the auto-type selection window

### ISSUE THREAD

**Issue by Tormen** [keepassxreboot/keepassxc#907]
The ESC key does not work in the Auto-Type selection window.
(cursor lets you select an entry, Enter lets you use it for auto-type, Esc should cancel, no ?)

Why is that important to me ?

I actually often need to "look something up" using the auto-type shortcut, but then don't actually want to auto-type, so a simple way to escape the auto-type selection windows would be great :))

## Expected Behavior
ESC should cancel

## Current Behavior
ESC does nothing

## Debug Info
KeePassXC - Version 2.2.0
Revision: caa49a8ef3ee28ed478192389b21d61107b3b8e0

Libraries:
- Qt 5.9.1
- libgcrypt 1.8.0

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 4.12.8-2-ARCH

Enabled extensions:
- KeePassHTTP
- Auto-Type
- YubiKey

**Comment by Tormen** [comment]
... I think in one case this actually worked for me today, but in 99% of the cases ESC does NOT work

**Comment by TheZ3ro** [comment]
Nice suggestion

**Comment by ccoenen** [comment]
@Tormen as a quick workaround: My Cancel-Button has a keyboard shortcut, in case of german translation this is Alt+A, as indicated by the underlined character on the button. (but I would also like to have ESC close the auto-type-selection-window! This is just a temporary suggestion ;-) ).

**Comment by Tormen** [comment]
@ccoenen : Thanks. The letter "C" gets underlined for me. But Alt+C is /not/ working.

But there is a work-around that is working: "TAB" (puts the focus on the Cancel button) + "space" activates it.
