### ISSUE TITLE
Number of entries not updated when switching between databases

### ISSUE THREAD

**Issue by TomasRiker** [keepassxreboot/keepassxc#9071]
## Overview
When switching between databases, the number of entries shown in the bottom right corner of the application window isn't updated.

## Steps to Reproduce
1. Open two databases with 1 and 2 entries.
2. Switch to the first database. Observe how in the bottom right corner of the application window, it says "1 entry".
3. Switch to the second database. Observe how in the bottom right corner of the application window, it still says "1 entry", even though the active database has 2 entries.

KeePassXC - Version 2.7.4
Revision: 63b2394
Operating System: Windows/Linux/macOS

**Comment by droidmonkey** [comment]
Good catch!
