### ISSUE TITLE
Minimize window after unlocking *all* databases

### ISSUE THREAD

**Issue by TomasRiker** [keepassxreboot/keepassxc#9076]
The feature "Minimize window after unlocking database" currently minimizes the window after unlocking the **first** database. As a result, when working with multiple databases (e.g. a private one and a shared one), this feature isn't very useful. I propose that after a database has been unlocked, the application automatically switches to the next database so that it can be unlocked, too. Only after unlocking the last database, the window should be minimized.

**Comment by droidmonkey** [comment]
I recommend you look into using auto open, check out the user guide. I could imagine this workflow to be rather undesirable for most, you are actually asking for two changes here.

**Comment by TomasRiker** [comment]
That works perfectly, thank you! I think this should be closed.
