### ISSUE TITLE
Global Auto-Type shortcut

### ISSUE THREAD

**Issue by prs22sg** [keepassxreboot/keepassxc#9079]
When defining a Global Auto-Type shortcut, the shortcut seems to expire and will no longer work.  If you access the Auto-Type tab under "Application Settings" the Auto-Type shortcut field is RED.  You then have to define another shortcut.  This seems to happen randomly.

If this is not a bug, can it be made to keep the Auto-Type shortcut until the user defines a new one.

**Comment by droidmonkey** [comment]
You might be choosing a global shortcut that some other program is registering. Your only choice is to choose another one. We do not "forget" the global shortcut. If you hover over the red background shortcut it should give you the error message in a tool tip.

**Comment by some-user123** [comment]
I just experienced the same issue. My shortcut worked fine. Till I restarted KeePassXC. Now it's not working anymore. The shortcut has a red background in the settings. Choosing another shortcut works. Choosing my old one isn't possible.

Is another instance of KeePassXC blocking this shortcut? I didn't do anything between stopping and starting KeePassXC...

**Comment by prs22sg** [comment]
This is an issue I can not repeat because it happens randomly.  I've tried so many different Global Auto-Type Short Cuts but for some reason the Short Cut eventually becomes unavailable and you have to choose another.

**Comment by andrewakl** [comment]
I'm using KeePassXC v2.7.4 and am also experiencing this issue (on Windows 10 Home; version 21H2).  Whatever keyboard shortcut I choose works fine, and then it suddenly stops working and the `Global Auto-Type shortcut` field turns red.  Choosing a different shortcut works fine, but then that too becomes invalid after a while.

I installed https://github.com/ITachiLab/hotkey-detective/releases to help me identify if any other app has registered the shortcut that KeePassXC is complaining about.  That Hotkey Detective app doesn't say that the shortcut I want to use in KeePassXC is registered by any program.

**Comment by droidmonkey** [comment]
What does the tooltip say when you hover over the red input field?

**Comment by andrewakl** [comment]
I will update this issue with what the tooltip says the next time I encounter the problem.
Thanks.

**Comment by andrewakl** [comment]
It's happened again.  When I hover over the red field, I don't see any tooltip.  Please see screenshot:
![60pCgsbZv2](https://user-images.githubusercontent.com/59714327/235268649-a5488b84-35cd-4b95-8ee3-58c928aa8bc7.gif)

**Comment by zcm** [comment]
I just had this exact issue myself on version 2.7.1 on Windows 11 (10.0.22621.1555). I noticed that there were multiple hung KeePassXC processes in the background in Task Manager. I closed the instance I had open and then killed all the zombie background KeePassXC processes. This fixed it for me - after I restarted I was able to use/change the shortcut again.

I also noticed that while the processes were haunting my system, KeePassXC-Browser would not work, alternating between complaints about being unable to connect and unsuccessful key exchange.

I don't know what causes it to hang on close, but my guess is that the other processes fail to release the hotkey lock. New instances are therefore unable to bind it again. It'd be nice if KeePassXC noticed them on startup and offered to kill them for you to prevent this from happening. Something like "It appears another instance of KeePassXC did not shut down correctly and is stuck. This can interfere with features like Global Auto-Type and browser integration. Would you like to kill it?"

The only change I made from my normal workflow is that (while presumably closed) I moved my database from a fully-local file in my home directory (C:\Users\Zack) to my Syncthing folder (C:\Users\Zack\Sync) and reopened it. That's when I noticed the weirdness start happening.

Hope this helps others frustrated by this issue, and maybe we can get this one reopened.

**Comment by Olfi01** [comment]
I also encountered this issue today. No error tooltip, just red background, won't let me choose my old shortcut but several others. Neither a reboot nor killing all KeePassXC processes were able to do anything about it.
