### ISSUE TITLE
KeePassXC fails to build on macOS

### ISSUE THREAD

**Issue by mbrockman1** [keepassxreboot/keepassxc#908]
Summary:
I am following the install directions(https://github.com/keepassxreboot/keepassxc/wiki/Building-KeePassXC) to a tee. and I am getting this error: https://pastebin.com/bbiT7dsB

I have brew installed all the dependencies:

`michael@newton:~/GitHub/keepassxc/build# brew install qt libgcrypt make cmake zlib
Warning: qt 5.9.1 is already installed
Warning: libgcrypt 1.8.1 is already installed
Warning: make 4.2.1_1 is already installed
Warning: cmake 3.9.1 is already installed
Warning: zlib 1.2.11 is already installed`

## Debug Info
KeePassXC - develop

Operating system: macOS 10.13
CPU architecture: Intel
Kernel: Darwin

**Comment by weslly** [comment]
Probably a bug with Qt 5.9.1: https://bugreports.qt.io/browse/QTBUG-61840

**Comment by rockihack** [comment]
No it's not a qt bug. The definition of Q_REQUIRED_RESULT has changed in 5.9.1.
It's working fine with clang, if you move Q_REQUIRED_RESULT to the beginning of the line.
See: https://github.com/rockihack/keepassx/commit/b50dcac48208c24b3d022b5cd53acf2b0e6a483d

**Comment by weslly** [comment]
@rockihack could you submit a PR with your fix?

**Comment by r0ckarong** [comment]
This still applies to Release 2.2.1
