### ISSUE TITLE
Auto Login

### ISSUE THREAD

**Issue by prs22sg** [keepassxreboot/keepassxc#9080]
This is not a bug report just a suggestion.  It would be nice if KeepassXC could record the login process for websites.  Then when the Title or URL of the website is clicked on, it would auto login to that site.

**Comment by droidmonkey** [comment]
We offer that as part of the extension (it's called auto fill) and is insecure (can be abused by malicious site code). Otherwise we will not implement any non-user triggered automation from the application side, that would violate our security paradigm.

**Comment by prs22sg** [comment]
Thank you for the response.  I can not say I understand how a malicious website could abuse a feature of external software but wouldn't the same apply or even worse to a browser extension.
