### ISSUE TITLE
Sync loop when keeshare active on Syncronize 

### ISSUE THREAD

**Issue by alejandracios** [keepassxreboot/keepassxc#9081]
Hi,
I have an issue when syncing a DB using Keeshare (Syncronize) 
I have DB1 / Group A shared to a DB2(Container)
DB3 is also synced with DB2

When make a modificatin on DB1 or DB3, replicate on the other DB which is good. But then the change on the other DB also triggers a change on the other and so on. I.e 
DB1 change entry xxxxx -> DB3 update xxxxxx -> triggers update on DB1, etc. 

I have to unflag auto save as the only way to interrup the cycle is to close one of the DBs for a while. 
Automatically reload looks like does not works when Keeshare is active. 
If you change any other entry (not shared) and hit save will trigger the loop once again (if both DBs open) 

I have other shared DBs but not using Syncronize option and does not have any trouble. 

I'm kind of new using KeepassXC and Keeshare so probably is not an issue but somehting wrong on my side. Please let me know if there is somethign wrong. 

Thanks!!!

**Comment by droidmonkey** [comment]
Duplicate. For now you need to setup your syncs to avoid loops like this.
