### ISSUE TITLE
Question [I am afraid that I forget whether there is somewhere else that I can ask this]: no 'browser integration field'

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [keepassxreboot/keepassxc#9082]
I read in [the user guide](https://keepassxc.org/docs/KeePassXC_UserGuide.html) that, via the 'browser integration' field, one can add some additional URL(s) for a database entry. I can see no such field. I see:

![image](https://user-images.githubusercontent.com/47056543/217338155-4fd35eb0-8391-4db7-a9a9-6861bf92576c.png)

![image](https://user-images.githubusercontent.com/47056543/217338102-088b0c09-3d17-4759-a329-ff1eb5dead62.png)

KeePassXC 2.6.6
Linux Mint 21.1 Cinnamon

**Comment by droidmonkey** [comment]
You need to enable browser integration then, in the application settings.
