### ISSUE TITLE
User Defined Auto-type Sequence

### ISSUE THREAD

**Issue by prs22sg** [keepassxreboot/keepassxc#9083]
Bug 1:

When a very long Auto-type sequence is defined and the user clicks the "Autotype Tab" on the main window, it causes the entire main window to move to the left covering the Groups.  When this happens there is no way to move the main window back to the right.  

When displaying a User Defined Default Sequence, it needs to be truncated or another method needs to be used when displaying them.

Bug 2:

When a very long Auto-type sequence is defined and the user chooses "Perform Auto-Type" the popup menu item will stretch across the screen.

This also needs to be truncated

**Comment by droidmonkey** [comment]
Screenshots please, and what version of keepassxc are you using and what operating system

**Comment by prs22sg** [comment]
Hi Droidmonkey,  

The information is as follows:

KeepassXC v2.7.4
Windows 11 Home v22H2

How to recreate the problem:

Under "Use Custom Auto-Type Sequence" paste the following:

{TAB}{TAB}{TAB}{TAB}{TAB}{TAB}{TAB}{TAB}{SPACE}{DELAY 600}{TAB}{SPACE}{DELAY 2000}{TAB}{TAB}{USERNAME}{TAB}{ENTER}{DELAY 2000}{TAB}{TAB}{TAB}{TAB}{SPACE}{TAB}{SPACE}{TAB}{PASSWORD}{TAB}{TAB}{TAB}{SPACE}{TAB}{TAB}{ENTER}

Now on the Main screen click the "Autotype" tab.  The entire main window shifts to the left covering a large portion of the group names.  When this happens, you can not drag the main window back into position.

Also, if chooses "Perform Auto-Type" the popup menu will stretch across the entire screen due to the length of the string.

Thank you for your quick responses.

**Comment by droidmonkey** [comment]
Easy fix, just made the field word wrapped, will post PR shortly

![image](https://user-images.githubusercontent.com/2809491/217688401-98472475-c2f4-4bf8-ba49-93d826158b3a.png)

**Comment by prs22sg** [comment]
Thank you Droidmonkey
