### ISSUE TITLE
The attachment cannot be open

### ISSUE THREAD

**Issue by Ziemowit** [keepassxreboot/keepassxc#9084]
## Overview

The attachment cannot be open. After clicking on "Open" button literally nothing happens.    

![Screenshot from 2023-02-08 09-07-21](https://user-images.githubusercontent.com/912250/217471005-62df5425-a569-4af9-8968-2c4a0e8e4963.png)

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Add new entry 
2. Add and attachment with simple file "test.txt" with "Hello world" text inside
3. Try to open it

## Expected Behavior
The file should be opened

## Actual Behavior
Nothing happens

## Context

1. keepassxc 2.7.4 working as snap - Revision 1645
2. Ubuntu Ubuntu 22.04.1 LTS 64bit
3. Gnome 42.5
4. Windowing System: Wayland

**Comment by droidmonkey** [comment]
Please switch to flatpak, we don't officially support the snap for this reason
