### ISSUE TITLE
Ability to create pronounceable passwords in the password generator

### ISSUE THREAD

**Issue by avara-zen** [keepassxreboot/keepassxc#9085]
## Summary
Please add the ability to create pronounceable passwords in the password generator.

## Examples
Something like this — https://sourceforge.net/projects/pronouncepwgen/
The generator settings can also be made similar

Passwords might look like:
Ya1Po7Pho0
Phe1PheXe8
AyZu1O6No5
Fe5Fo1HoMo4
Ga5PheDuSi7
Shwu0Wuck7
A0Ta5FyHe2
VeWi3Gu9Wa9
Ro5GheO5Si0
Mey1Che8Fo2
Bo?BoFe9Xa;KaCe@
Wy#Du8A7JeDyShu'
Gli[Pha]Thu8She@
Gha7Te9Di2ThePho(

Not all of them are easy to pronounce. But if several are generated at once, then you can always choose the right one from them.

## Context
Some passwords need to be remembered (for many reasons). It is long and inconvenient to create manually, and they also turn out to be weak. And why, if a program could do it.

**P.S.**
I want to thank you for a great app! I'm trying to switch to it with KeePass, but I encounter some (generally small) obstacles. I hope that your application will continue to develop actively. Thanks!

**Comment by droidmonkey** [comment]
We are not implementing any more password generation types, plus these passwords are definitely not memorable and they do lower entropy because they are essentially words. Use the passphrase generator if you need to memorize your password.

**Comment by avara-zen** [comment]
Thanks for the quick response.

It doesn't look like you actually counted their entropy.
Most passwords generated in this way have sufficient entropy. And passwords with the highest degree of entropy are not always needed. It is often quite average, especially taking into account the advantages of memorability and ease of input. The application is used not only while sitting at a computer or laptop, having KeePass at hand. Normal users have to enter passwords in other places (for example, a smartphone, someone else's computer, etc.). Passwords from the phrase generator are really remembered better. But it is extremely inconvenient to enter them, for example, on on-screen keyboards. And even on full-size keyboards, when there is no KeePass nearby and it is impossible to copy the password through the clipboard, you have to enter a long phrase blindly, because passwords are always closed in the input fields. And the function to enable password display is not everywhere (and I don't want to do it when people are around). And instead of correcting a typo, the probability of which is very high when entering a long phrase, we have to type it in its entirety again. And if it's a mobile phone, then the process turns into a nightmare.

I really started to like KeePassXC. It doesn't have any significant advantages compared to KeePass (at the moment), only small ones, because of which I want to switch to it. But there are also small disadvantages. It is completely incomprehensible to be so categorical in a question that does not violate the architecture of the application. 

I understand that there are more important improvements, bug fixes are also more important. And the fact that the application is free, and you have a huge gratitude and respect for the time and effort spent. 

But why not put the request in a low priority plan? 
How much do I need to donate in order for the feature to be included in the development plan? I'm willing to pay for an app that helps solve my problems.

**Comment by droidmonkey** [comment]
You are not the first to request this. Your sample passwords do indeed have higher entropy, but, the standard pronounacable password has very low entropy since at its core it is based on a single or double word with simple replacements that any password hashing tool tries by default.
