### ISSUE TITLE
Autotype in RealVNC or RoyalTSX is typing AAA or aaaaaa symbols only  (Mac M1)

### ISSUE THREAD

**Issue by dimavrn** [keepassxreboot/keepassxc#9086]
Hi!
Autotype in RealVNC or RoyalTSX is typing AAA or aaaaaa symbols only .
But in RDP Microsoft client it also typing AAA and after i changed keyboard type in settings to UNICODE from SCANCODE
It works like a charm.

Enyone knows how to fix that in Apps like VNC clients or RoyalTSX or something else?
In Windows i use Keepass and it works fine.

**Comment by droidmonkey** [comment]
You will have to use the virtual keyboard option in windows (see our user guide). MacOS virtual keyboard support is coming in 2.7.5.
