### ISSUE TITLE
"Repeat" field does not match? I'm just throwing away all your changes!

### ISSUE THREAD

**Issue by ccoenen** [keepassxreboot/keepassxc#909]
If password and repeat don't match, you can click `OK` but all your changes won't get saved.

## Expected Behavior

I can think of two possible fixes, but there may be better ways.

- `OK` could be disabled as long as some basic requirements are not met
- pushing `OK` could also just yield a warning message, that password/repeat don't match

## Current Behavior

Pushing OK will close the editor, but the changes are lost.

## Steps to Reproduce (for bugs)

1. have a database open
2. edit an existing entry's title
3. make sure password and repeat *do not match*
4. click `OK`
5. look at the list, the _old_ entry is still there. Your changes are lost

## Debug Info

KeePassXC - Version 2.2.0
Revision: 5e309feaebf37afa5278f424056e0bbc034a20a8

Bibliotheken:
- Qt 5.7.1
- libgcrypt 1.7.6-beta

Betriebssystem: Debian GNU/Linux 9 (stretch)
CPU-Architektur: x86_64
Kernel: linux 4.9.0-3-amd64

Aktivierte Erweiterungen:
- Auto-Type

**Comment by droidmonkey** [comment]
Wow thats crazy

**Comment by ccoenen** [comment]
I confirm that the fix is exactly what I was hoping for. Thanks!
