### ISSUE TITLE
Get field reference quickly

### ISSUE THREAD

**Issue by aetonsi** [keepassxreboot/keepassxc#9092]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
Hello
i'd like to propose the addition of a quick way to get a field cross reference (i mean the string `{REF:U@I:xxxxxxxxxxxxxxxxxxxxxxxxxxx}`) for use in another entry.
At the moment (correct me if i'm wrong), the only way to setup precise references (by uuid) is to manually write the string "{REF:..." after manually retrieving the `uuid` in the Properties pane of the desired entry... it's a bit unpractical.

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )
A simple way to implement this feature would be adding a "Copy Field Reference" in the entry context menu, after the entry "Copy Attribute"; clicking a sub entry would simply generate the desired string and copy it to the clipboard:
![image](https://user-images.githubusercontent.com/18366087/217791621-89120541-7cbf-46f8-a194-cb2a8162fa80.png)

Another possibility would be to give some sort of way to get a reference to another entry when editing an entry. For example, right clicking a text field, selecting "Insert field reference" from the context menu (which at the moment contains Undo/Redo/Cut/Copy/Paste/Delete/Select all), which in turn opens a popup to search and select the desired entry with a combobox to select the field. This is way too complicated IMO.

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
This feature might be very useful to anyone needing references more or less frequently, which i admit it's probably a small portion of users. But it should be pretty easy to implement (AFAIK), non breaking, and non invasive.

---

Thank you for your time

**Comment by droidmonkey** [comment]
#433 captures this request. We would not put this as a first-class feature on the context menu for several reasons, including it is an advanced use case. We already support cloning an entry which let's you choose to reference the username and password of the original. That dialog can be expanded to include other fields.
