### ISSUE TITLE
Using punctuated characters as master password does not log in, in GNOME 43

### ISSUE THREAD

**Issue by logisin** [keepassxreboot/keepassxc#9093]
I have set a password using Keepass(not keepassxc) which includes punctuated characters. When I try to log in my password database using my master master password in keepassxc it does not send the right characters. If I press the eye icon to reveal what has been typed it shows the simple version of the character not the punctuated one. This does not happen with KDE. It happens only in GNOME 43 with and without Wayland enabled. I use the latest version of keepassxc.

**Comment by droidmonkey** [comment]
You need to have the password visible to use them correctly. This is a qt bug we have no control over.
