### ISSUE TITLE
kdbx db loading - renaming  

### ISSUE THREAD

**Issue by KIOSKPORT** [keepassxreboot/keepassxc#9094]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

after one! irregular closing of KEEPASS (non ending action without popup/dialogue, manually terminated clicking window X ):  

a currently selected database [ X222etc.KDBX ] with shown correct db name in window is "renamed" [ X2etc.KDBX ] after opening, name is one of an earlier version sitting in the same directory, more in detail: the first name in the list of KDBX in the file directory; 
data/content nevertheless probably not changed/altered in teh kdbx ..
the menu control "formerly used db" shows the correct name, clicking brings the same effect as mentioned... 

assumption: the shorter / first db name seems to be "frozen" in the background/cache e.g. the reading of the kdbx file list is somewhat corrupted....

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. multiple reproductions by openings 
2. 
3. 

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

## Context
[NOTE]: # ( Give us any additional information you may have. )

a/ behavior remains the same after Updating to vs. 2.7.4 of KEEPASSXC
b/ behavior remains the same afte De-Install and Re-Install the app 

[NOTE]: # ( Paste debug info from Help → About here )

KeePassXC - VERSION 2.7.4
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows10

**Comment by droidmonkey** [comment]
Database -> Database settings -> change the database name
