### ISSUE TITLE
Find and Replace particular Strings from an entry | Search should work for Placeholder and field references | Quick look view of fields inside the entry if references and placeholders are used | Delete History for all the entries

### ISSUE THREAD

**Issue by solifice** [keepassxreboot/keepassxc#9099]
I have been using KeepassXC from a very long time. And I am very grateful to have this tool. UI is amazing with the dark theme and the other stuff.

I have some very good ideas that can make it more robust in terms of advanced usage. Recently I learned about the feature that Keepass and KeepassXC both supports the placeholders and the field references. I have lot of entries which are having referenced from parent entry. I don't prefer to use UUID when referencing any field because it makes very difficult for me find the particular entry with UUID. So, what I have done I have created global entries and a separate group. And I am referencing them in other entries of the other groups using the Title. Title I have made like constants in a program. And easy to understand which entry field it is calling.

3 Problems arises for me which makes it difficult to use.

1st Problem :- If I change the Title of referenced entry then, I need to change the REF statement everywhere in the database. Simple resolution for this can be that there should be a find and replace tool. So if I search for the entries having their fields and custom fields with {REF:U@T:USER_NAME} I can simply select the USER_NAME and replace it with FULL_NAME for all the entries. This feature will not only help in this case, but it can also help in a normal entry if some one wants to change the Phone number for all the entries with the custom field.

2nd Problem :- Whenever I open the entry which is using reference field and placeholder then there is no way of looking the details. To look for details we need to copy the fields or custom fields value to a notepad and check whether I have referenced it correctly or not. I would like to request add a quick look box at the right side of the field or custom field that will show the output of the REF statement. So if some one is typing the REF statement, he/she can see that is it getting referenced or not.

3rd Problem :- This problem is less to me but still noticeable every now and then. For all the entries I have to delete the history one by one which is very annoying. If possible please add an option in database settings to delete history for all the entries at once. Also if above two problems are fixed this is also needed.

**Comment by droidmonkey** [comment]
1) #1314
2) #433
3) #7779

**Comment by solifice** [comment]
I hope you have gone through the scenario. I will wait for Keepass 2.8.0. Thanks a lot for this wonderful tool. ❤️

Since my issue is a duplicate you might like to close it.
