### ISSUE TITLE
Touch requirement (settings) gone after Yubikey Windows authentication setup

### ISSUE THREAD

**Issue by ausername3948576** [keepassxreboot/keepassxc#9102]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
Keepass XC 2.7.4 with Yubikey no more touch required after Yubikey login for Windows setup

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Settings - Security, there the setting "enable database quick unlock (Touch ID/Windows Hello) option is gone.
2. On another machine (where no Yubikey login for Windows was ever setup) with the same 2.7.4 version the option is still there (on that machine i don't have it active, but it is available)
3. Reinstalling Keepass XC 2.7.4 does not bring the setting back

I was not using this setting but noticed its behaviour after the Yubikey login for Windows setup and think it's related

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
The requirement to open the database by touching the Yubikey should still be there, now it seems unsafe (it still has to be in the computer to open, but the lack of the touch is unsafe)
Also installation of the Keepass XC 2.4.7 software should be the same no matter on what system it is installed and the installation of other software should not interfere.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
After  setup Yubikey Windows authentication using their instructions; https://support.yubico.com/hc/en-us/articles/360013708460-Yubico-Login-for-Windows-Configuration-Guide the touch requirement to open my Keepass database is gone, it simply opens after entering the password (with the Yubikey in the computer)

## Context
[NOTE]: # ( Give us any additional information you may have. )
On both systems the software is 2.4.7 with the same Revison 63b2394

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.4
Revision: 63b2394

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows
Desktop Env: 
Windowing System: 11
![enable database quick unlock (Touch ID - Windows Hello)](https://user-images.githubusercontent.com/125142391/218267715-de096f5c-26d0-44f3-a028-53ddf4ffbc31.jpg)
![missing after Yubikey Windows setup](https://user-images.githubusercontent.com/125142391/218267810-1fddc800-7e9d-431e-8e01-c852e98d63e5.jpg)

**Comment by droidmonkey** [comment]
That means you have not setup Windows Hello on the computer that is missing the setting. Touching the yubikey is a function of the yuibkey slot configuration, not keepassxc.
