### ISSUE TITLE
KeepassXC does not see Yubikey Nano

### ISSUE THREAD

**Issue by Hubert-Mach** [keepassxreboot/keepassxc#9105]
## Overview
KeepassXC does not detect Yubikey NANO (firmware 5.4.3)

## Steps to Reproduce
1. Insert Yubikey Nano to USB port
2. Run Yubikey manager to test if it is detected - should be detected
3. Run KeepassXC and try to open db - refresh Hardware key -> result no keys detected

## Expected Behavior
Key should be available on the list

## Actual Behavior
As described, there is no key available to be chosen - either run as standard or privileged user.
Another yubikey 5 NFC is detected with no problems.
Enabled interfaces are the same for both.
5 NFC firmware 5.1.2
5 NANO firmware 5.4.3

## Context
HW key was used to encrypt db. Now I am unable to decrypt it as hw key is not detected.

[NOTE]: # 
KeePassXC - Version 2.7.1
Revision: 5916a8f

[NOTE]: # 
Operating System: Windows 10

**Comment by droidmonkey** [comment]
You need to configure a slot for challenge response.

**Comment by droidmonkey** [comment]
Update to 2.7.4. If keepassxc still doesn't see the key then that means you did not successfully configure the slot for challenge response.

**Comment by Hubert-Mach** [comment]
2.7.4 did not see it either.
Configured second slot for challenge-reposnse as first was already configured (for initial encryption of db) and now key is seen.
Swapped slots and key is also seen. Sadly am unable to decrypt db.
Many thanks for help!

**Comment by droidmonkey** [comment]
I do recommend printing out the secret key csv file after configuring the slot. Then you can reconfigure that key or a new key with the same secret.
