### ISSUE TITLE
Shortcut for Copy Attribute - Title

### ISSUE THREAD

**Issue by neta540** [keepassxreboot/keepassxc#9109]
I would love to have a keybinding to copy the title of the selected entry copied to the clipboard, since I am using titles a lot. 
I suppose that's not a difficult task?

Thank you all for a great piece of software. 

![copy title](https://user-images.githubusercontent.com/19378426/218622938-1ea3b697-2613-4bcb-a3c9-396b298490f2.png)

**Comment by droidmonkey** [comment]
Can you explain this use case further? `since I am using titles a lot`

**Comment by neta540** [comment]
I have a list of pre-generated, unused email aliases. Whenever I sign up to a website, I choose one of the unused email aliases to sign up with to register to the website. The email address is the entry title, and username is the destination mail. I'd like be able to copy the title quickly when I sign up, and after signing up to copy the username, so I will log to the correct mailbox, to complete the sign up (if necessary). I can't use URL field as it is filled with the website address. Using the password field is a secret, that shouldn't be used in this case.

**Comment by droidmonkey** [comment]
I guess it could be set to Ctrl + i. Ctrl + T is taken by TOTP which is the far more frequent use.

**Comment by neta540** [comment]
Excellent! That would be useful. Thank you!

**Comment by michaelk83** [comment]
This could really benefit from custom shortcut mappings, and maybe from custom entry templates.
But in the meantime, to make this more useful to a wider audience, how about 1-2 "copy field" shortcuts, where you can customize which field they copy (including custom fields)?
