### ISSUE TITLE
Export custom fields and attach to csv or html

### ISSUE THREAD

**Issue by drainnoff** [keepassxreboot/keepassxc#9110]
## Summary
Currently, when using Database -> Export -> CSV File or HTML File, the generated file does not contain any additional attributes or attachments. Without that information the records are incomplete.

Attributes can be exported in two columns per attribute, name, and data, and attachments can be exported in two other columns per file, name, and data as base64

Custom icons can also be exported as base64, but this part is not as important as the previous one.

## Examples
![imagen](https://user-images.githubusercontent.com/48261461/218698702-c6a413bd-f202-4053-aace-dfbb04834077.png)

## Context
I store information about servers in additional fields such as serial number, model, location, etc.

In the attachments I store imported files, such as X509 certificates, vpn configuration files, etc.

**Comment by droidmonkey** [comment]
HTML file shows all additional attributes. Your method for attachments would only work with one file per entry. Either way it is unlikely we would support that, you will need to save the attachment from the entry. This is a duplicate request.
