### ISSUE TITLE
Auto scan for yubikey on unlock dialog focus

### ISSUE THREAD

**Issue by tdenta** [keepassxreboot/keepassxc#9114]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
On the locked screen, it would be very handy and time saving if keepassxc could:

1. Automatically run a yubikey refresh scan when the keepassxc window comes into focus (i.e. on the foreground)
2. If there is only one yubikey available/listed, there is little doubt that this is the one to be used: would it be possible to auto-select it?
3. The user would only have to input his/her password and hit enter to unlock, provided the yubikey is plugged in beforehand. Three mouse-clicks eliminated.
4. This behavior would not be incompatible with yubikey "auto-remember" as it would eventually provide the same feature (i.e. if the previously used yubikey is still plugged in, keepassxc would still auto-select it).

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )
No UI redesign would be required.

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
My yubikey is on my keychain, and I need to unplug it/replug it many times.
My keepassxc is configured to lock when my MacOS session is locked.

Those two things are causing a huge amount of database unlocks and it would be very nice to save a few clicks.
Maybe, there are faster possibilities through CLI?

**Comment by droidmonkey** [comment]
We won't auto select a yubikey if we don't have record of you using it to unlock your database. That would cause massive issues if your yuibkey wasn't actually used to secure your database. I am not against re-polling for the key if the database is known to use it and there is not a valid key already displayed and the window comes in focus.

**Comment by jimmiedave** [comment]
Came here to look for/add request for the same features. I _love_ that I can use my Yubikey with this. I _hate_ the constant fumbling around rather than just find and select it when it's plugged in.

It strikes me that you could have a "find and use first Yubikey" preference that's opt-in so you don't cause issues for folks with Yubikeys that don't have their KP database tied to them.

I have work and personal Yubikeys, both on my keyring, and I would gladly turn on such a preference - though I can see the case for turning it off by someone in the same situation who confuses two keys regularly.

**Comment by tdenta** [comment]
I can only support what @jimmiedave wrote. I understand the point of not selecting automatically the yubikey because it could be used for other purposes ... nevertheless, I suppose a setting in the form of a checkbox, explicitely allowing this behavior, would make sense for everyone (per database setting).

I have the issue that I have several different yubikeys to unlock the same database, and remembering the last used yubikey causes the unlock process to fail when I use another one, because re-polling isn't automatic.
Also, even if I was to use the same yubikey all day, not re-polling means keepassxc has no idea wether the key is actually still plugged in or not - and it can be unplugged an replugged regularly if it's attached to a keychain.

**Comment by jimmiedave** [comment]
I'm very, _very_ appreciative of the work on this feature! Works great!

Thanks so much!
