### ISSUE TITLE
On-screen widget like 1Password mini

### ISSUE THREAD

**Issue by MrChocolatine** [keepassxreboot/keepassxc#9116]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )

Hello.

I searched for similar requests before posting but I didn't find anything, sorry if it is a duplicate.

I wanted to know if you would consider (or already declined?) adding something similar to this feature from 1Password:
https://blog.1password.com/1password-7-3-for-our-life-in-miniature/

They call it "1Password mini".
Some kind of modal that would appear after a keyboard shortcut:

At my company we can only use this password manager and, I must say, I find this feature really handy.
I know that, in comparison to KeePassXC, the browser extension already returns a list of credentials associated with any website. 

But this feature/modal can be displayed from anywhere, even from softwares (which don't include any browser extension, obviously), and letting us quickly search and edit any entries.

See this video that showcases this feature from 1Password (from an old version, but the logic stays the same):
https://youtu.be/XZNUfowj6zc?t=128

Thank you again for maintaining this awesome software, keep up the good work :v: .

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )

![opm7 3-mini](https://user-images.githubusercontent.com/47531779/218868140-0414e231-b70b-40ad-a7da-fe92f29fcd12.png)

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )

This feature/modal is handy, it can be displayed from anywhere, even from softwares (which don't include any browser extension, obviously), and could let us quickly search and edit any entries.

**Comment by droidmonkey** [comment]
This would be #99 and also our existing auto type capability.

**Comment by MrChocolatine** [comment]
> our existing auto type capability.

Auto-typing? Kind of, it is half of the feature I tried to describe.

Thanks for the link to #99 , I will track this issue then.
