### ISSUE TITLE
Separate Option to remove the recent database history

### ISSUE THREAD

**Issue by Viduraje** [keepassxreboot/keepassxc#9118]
Currently, anyone can see the recent database history in database > recent databases.  If we're to disable it, the "Load previously open databases on startup" is greyed out. 

Requesting separation of "Load previously open databases on startup" as a standalone option.

To complete the target of the secrecy, it would be nice to blank out the location of database in opening screen too.

**Comment by droidmonkey** [comment]
You can't have both no history and load previous databases, that makes no sense.
