### ISSUE TITLE
Search should ignore usernames

### ISSUE THREAD

**Issue by mpkuti** [keepassxreboot/keepassxc#9119]
## Summary
The search tool should search first from the entry **titles**. Searching **usernames** should be optional, or have lower importance (bottom of results for example), or disabled.

## Examples
**Search:** `gmail`
**Results:** All entries, which have `gmail` in the **title** or in the **username** or anywhere.
**Expected results:** All entries, which have `gmail` in the **title**.

## Context
Searching words included in any of my email addresses result tens or hundreds of unwanted entries.

**Comment by droidmonkey** [comment]
Not going to implement this, in fact there is a large focal request to search EVERYTHING by default. Use the search parameters to scope your search: `t:gmail` will only search for Gmail in the title.
