### ISSUE TITLE
KeePassXC freezes KDE Plasma panel on exit

### ISSUE THREAD

**Issue by riomccloud** [keepassxreboot/keepassxc#9121]
I'm using Arch Linux with KDE Plasma 5.26.5. When I close KeePassXC 2.7.4 - Flatpak version - (with it configured to be immediately closed, without going to the tray), my bottom panel freezes for ~2-3 seconds. First time I thought it was a KDE bug, but I noticed it always & only happens with KeePassXC. IDK if it happens with other DEs, distros or package types.

**Edit:** It does not freeze the panel when exiting the application via the Database > Exit menu.

## Steps to Reproduce
1. Open KeePassXC Flatpak in Arch Linux
2. Close it
3. That's it

## Expected Behavior
Just not freeze.

## Actual Behavior
It freezes for ~2-3 seconds.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.4
Revision: 63b2394

Operating System: Arch Linux
Desktop Env: KDE
Windowing System: X11

**Comment by michaelk83** [comment]
May not be unique to KeePassXC, and may be related to how the clipboard is cleared:
https://bugs.kde.org/show_bug.cgi?id=432810
https://github.com/keepassxreboot/keepassxc/issues/6101#issuecomment-1376237763
https://github.com/keepassxreboot/keepassxc/issues/6101#issuecomment-1376948784

**Comment by ghost** [comment]
Have the same issue on Devuan Unstable (KeePassXC 2.7.4)

**Comment by droidmonkey** [comment]
This is a duplicate
