### ISSUE TITLE
Add the ability to batch edit entries

### ISSUE THREAD

**Issue by elpocoburrito** [keepassxreboot/keepassxc#9123]
## Summary
In Keepass 2 (The other tool) there is a feature which allows selecting multiple entries and changing one or multiple of their fields at once, which is extremely useful.

## Example
For example, if I have entries for 20 web cameras and they all share the same username and password, with only their URL differing (lets imagine their username/password is manage at a central location in the real world, so changing it there will also change it for all the cameras, thus needing to change all their entries at once).
If I want to set/modify all their credentials for every entry, I need to do so one by one in current KeepassXC.
Yes, I could create a single entry then point all their username/pasword to that entry using a reference, thats possible, but even then I would need to set the reference one by one initially.

To get around this issue, being able to select all the entries via Ctrl+A or Shift+Click, right clicking and selecting "Edit entries (Batch)", and then inputting the username and password (or a reference) and finally clicking "OK" would be awesome and save alot of time.

Here is an example from Keepass 2 that serves what I need perfectly (Data in screenshot is obviously not sensitive)
![image](https://user-images.githubusercontent.com/13389884/219135415-3318892e-b26c-4559-898c-3d9c245638f7.png)

**Comment by droidmonkey** [comment]
Duplicate request
