### ISSUE TITLE
Provide password generator profiles, possibly saving those in the database

### ISSUE THREAD

**Issue by sjvudp** [keepassxreboot/keepassxc#9124]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
(Initially I was considering whether to piggyback on issue 2628, but then decided to start a new one, so here it is)

One of the Features I liked in KeePass v2 is the "Password Generator Profiles": You can define rules how to generate a password and save those rules.

In contrast in KeePassXC you *cannot* save different password generator settings, and as you know, there is a multitude of password requirements out here, so one rule cannot fit all, unfortunately.

Next thing I realized in a negative way was the fact that KeePass stores the password generator profiles somewhere *outside* of the database, so when you move your database to a different PC you don't have access to your password generator profiles, or (maybe even worse) they may be different or even tampered.

So I think when KeePassXC implements password generator profiles, it should invent some mechanism to store those in the database.

So back to issue 2628: One might store the equivalent of the password generator profile with the entry, or just the profile name.
Trying to derive the rules from the current password will cause a loss of entropy, however (the KeePass v2 docs point that out already).

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )
I think an example is not needed here.

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
Different systems have different requirements, and it may take some extra time to set up the individual requirements for the password generator prior to generating a new password.

**Comment by droidmonkey** [comment]
Duplicate request, we intend to store the password profiles in the database when this is implemented

**Comment by 4lex11s** [comment]
FYI, duplicate of https://github.com/keepassxreboot/keepassxc/issues/2628

**Comment by sjvudp** [comment]
"Deriving the password from an existing entry" causes the entropy to be reduced on the long run, unless the password-generating ruleset is stored with the entry (which is not AFAIK).
See https://keepass.info/help/base/pwgenerator.html for a discussion of the issue.
