### ISSUE TITLE
The database is not reload from the record view window, and the changes overwrite the database on disk (data is lost)

### ISSUE THREAD

**Issue by Perlover** [keepassxreboot/keepassxc#9127]
## Overview

If you open a record for viewing and stay in the record viewing window, and at this moment the file is changed from the outside, then despite the settings to re-read the database, it is not re-read. Moreover, if you edit the record at this moment and save the database, it will overwrite the database that was changed from the outside.

## Steps to Reproduce

1. Open database from Google Drive / Dropbox directory for example
2. Click by some records and don't close view/editing view
3. In that time to change database from other device and to wait synchronization for new file from Google Drive / Dropbox
4. Press OK in KeepassXC in view/editing view of record.
5. Now you will see that changed were not made and file was not reloaded from disk
6. If we will edit record between steps 2-4 then after press OK in step 4 - our old database (from memory) will be saved and changes were made at another device will be lost.

## Expected Behavior

Or re-read the database at the moment when we edit / view any record in it, which is wrong (when editing, changes may disappear). Or, when saving (after editing), check the database on disk and do automatic merging with the version of the database that is on disk. It seems to me that version 2.6 worked like that. But I don't see that in version 2.7 there was a setting to enable automatic database merging. Perhaps I'm confused that it used to work like this before - at least that's how keepass2android works.

## Actual Behavior

To see _Overview_ sction above

## Context

KeePassXC v2.7.4 compiled from sources
Operating System: Linux Mint 20.3 (It's based on Ubuntu 20.04)
Desktop Env: Cinnamon

**Comment by droidmonkey** [comment]
#8545
