### ISSUE TITLE
Pasting text does not work

### ISSUE THREAD

**Issue by jnyheim** [keepassxreboot/keepassxc#9129]
## Overview
Pasting text does not work, no option to paste is given after copying Eg. notes or recovery codes int an entry

## Steps to Reproduce
1.  Copy any text by [CTRL] + C or Right click copy
2.  paste into text field by [CTRL] + V or Right click paste

## Expected Behavior
That the text is pasted into enrty

## Actual Behavior
nothing happends

## Context
I assume this is a bug because it is not a problem on windows or macos

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.4
Revision: 63b2394

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: KDE Plasma
Windowing System: Wayland

**Comment by droidmonkey** [comment]
This is a qwayland bug and it's been reported to qt already
