### ISSUE TITLE
Standard folder icon for entries exception

### ISSUE THREAD

**Issue by Offerel** [keepassxreboot/keepassxc#9131]
## Overview
Setting a icon for a entry is essential for me. Normally I use the setting "Use group icon on entry creation", which is fine so far. However, at least in my eyes, this doesn't make sense for the standard folder icon, since a folder is indicating a folder. It would be better to use the key icon here, like in other KeePass applications as exception. I don't know if this is a bug or a feature request. Feel free to change this to a FR. Ohh and don't get me wrong, I really like the option "Use group icon on entry creation" and use it for every other folder.

## Steps to Reproduce
1. Create a folder with the standard folder icon
2. Make sure that "Use group icon on entry creation" is enabled
3. Create a new entry in the above folder
4. The folder icon is selected as entry icon

## Expected Behavior
If the standard folder icon is used for a folder, use the standard "key icon" instead for entries.

## Actual Behavior
Actually the folder icon is used for entries.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.4

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows/Linux
Desktop Env: Gnome/KDE/XFCE/Mate/Cinnamon
Windowing System: X11

**Comment by droidmonkey** [comment]
https://github.com/keepassxreboot/keepassxc/issues/7321#issuecomment-1019324689

**Comment by Offerel** [comment]
Ohh... hmmm for some unknown reason, the top folder icon was the open folder icon. My fault... many thx for pointing me to the right solution.
