### ISSUE TITLE
Certain characters (^¨`´) can't be entered in the password field while unlocking a KeePassXC database unless "Toggle Password" is on

### ISSUE THREAD

**Issue by aurando** [keepassxreboot/keepassxc#9132]
## Overview
When unlocking a KeePassXC database, certain characters can't be entered in the password field unless "Toggle Password" (show password) is on. The keyboard used is MacBook Air M2 2022 Scandinavian layout.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Open a database.
2. Begin unlocking the database by typing the password in the "Enter Password:" field.
3. When entering characters ¨ ^ ´ or ` pressing ^¨ key, Shift + ^¨ key, `´key or Shift + `´ key on the keyboard (left to the backspace and enter keys), no obscured password character "●" is entered.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
When entering the password, the characters mentioned above should appear as "●" in the password field even when the password is obscured (default setting, "Toggle Password" off).

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
No "●" character appears while trying to input the characters mentioned above unless "Toggle Password" is turned on, and the password is visible.

## Context
MacBook Air M2 2022, Scandinavian keyboard

KeePassXC - Version 2.7.4
Revision: 63b2394

Qt 5.15.6
Debugging mode is disabled.

Operating system: macOS 13.2
CPU architecture: arm64
Kernel: darwin 22.3.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 2.19.2

**Comment by droidmonkey** [comment]
This is a qt bug
