### ISSUE TITLE
Feature request: generate random usernames with DuckDuckGo.com email addresses (@duck.com)

### ISSUE THREAD

**Issue by e2jk** [keepassxreboot/keepassxc#9133]
## Summary
It would be great if, upon creating a new entry, a new, random/private email address from DuckDuckGo's `@duck.com` 's email service could be generated.
This new, random address would then be used as the email address for the new service we're creating the password entry for.

## Examples
With this feature, Service A would have something like skjf78ls@duck.com as username, while Service B would have a completely unrelated username like dldihekg@duck.com as username. Both email addresses would transparently for the user forward through DuckDuckGo's email service to your master email address (that you have configured previously, outside of keepassxc)

## Context
This would have various benefits:
- Random, different email addresses for each new account, increasing our users' resiliency if one of the external services is breached
- When receiving emails from the websites, tracking codes are automatically removed by DuckDuckGo, meaning improved privacy "just" by using our favorite password manager

Announcement of that new feature: https://www.spreadprivacy.com/protect-your-inbox-with-duckduckgo-email-protection/

Other password managers are starting to implement this feature. One example is Bitwarden (in addition to DuckDuckGo they also offer).
If useful, their help page also explains how to retrieve one's own DuckDuckGo API key, basically:
- Open your browser's Developer tools (often with the F12 keyboard key) and go to the Network tab
- Navigate to the [DuckDuckGo email autofill](https://duckduckgo.com/email/settings/autofill) page
- Click the "Generate Private Duck Address" button
- Select the line that was just added in the developer tools for the API POST request, and locate the API authorization item.

The API Key is the value after "authorization: Bearer"

Example from my own browser (sorry, UI in French, but the HTTP request headers are the same in English):
![image](https://user-images.githubusercontent.com/229379/219873879-48a0372c-4865-457a-bba4-cba64150ef6a.png)

Source : https://bitwarden.com/help/generator/

Edit : Somehow when creating the ticket, I wasn't proposed with the ability to choose a template. reformatting to use the Feature Request template.

**Comment by e2jk** [comment]
Can be interesting to review together with this other feature request, #9134 "Propose a username using "plus" email addresses"

**Comment by droidmonkey** [comment]
We will not be implementing this feature. Thank you for the submission though.
