### ISSUE TITLE
Feature Request: Option to prevent search from returning to the top of the list after editing an entry.

### ISSUE THREAD

**Issue by ghost** [keepassxreboot/keepassxc#9139]
## Summary
Every time you edit an entry from a search, it returns to the top of the search list. This can be very aggravating for those using the search to organize/update their databases, which I presume most people do.

## Examples
Editing my database from a search, 3 pages down, going 1 by 1, makes it a chore to go back to my previous position and continue down the list after I edit an entry.

## Context
The current functionality is very cumbersome, as least in my usage case.

**Comment by droidmonkey** [comment]
I actually just fixed this as part of #9070

**Comment by ghost** [comment]
> I actually just fixed this as part of #9070

Ty!
