### ISSUE TITLE
Synchronization issue with Google Drive

### ISSUE THREAD

**Issue by non4coder** [keepassxreboot/keepassxc#9140]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

- For years, I have been using KeePassXC on my MacBook and KeePass2Android on my mobile phone without any issues. 
- I synchronize my kdbx database file between my MacBook and Android phone using Google Drive, with Drive for Desktop installed on my MacBook.
- I created a dedicated folder on Google Drive named "KeePass" where I placed my kdbx database. 
- However, in the past few months, I have encountered problems while synchronizing my kdbx database file.
- On my MacBook, I can only view one kdbx database in my Google Drive folder, even when I use the Command+Shift+Dot shortcut to display hidden files. 
- Nevertheless, when I access Google Drive through web browser and navigate to my KeePass folder, I can see additional files, which appear to be backup files. 
- I am experiencing an issue with the synchronization of my KeePassXC private kdbx database with Google Drive on my MacBook. 

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )

1. Whenever I add a new entry or update an existing one, I can see that the synchronisation is in progress in Google Drive for Desktop on my MacBook. 
2. However, upon checking Google Drive in my web browser, I noticed that my private.kdbx file was last modified on 1 Feb 2023 instead of the current date of 19 Feb 2023. 
3. It appears that only backup files have been added and private.kdbx is not updated, as indicated by the timestamps.
4. This has resulted in my inability to view the latest changes to my KeePass2Android on my mobile phone, which I made on my MacBook.

To resolve this, I had to copy the private.kdbx file to my MacBook and then delete and recreate the KeePass folder. Afterward, I added the copied private kdbx file to the new KeePass folder, allowing me to have the same version of my private.kdbx on my MacBook and Android phone.

It's also worth noting that I cannot see a cloud icon on my private.kdbx file in Finder, which is quite puzzling.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

I would expect, that my kdbx database is synchronized through Google Drive, so I have the same version on my MacBook and mobile phone (Android).

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

I don't have the same version on my MacBook and mobile phone (Android).

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS and Android

**Comment by droidmonkey** [comment]
You need to reinstall or log out / log in again to Google drive on your MacBook. This is definitely not a keepassxc issue.

**Comment by non4coder** [comment]
> You need to reinstall or log out / log in again to Google drive on your MacBook. This is definitely not a keepassxc issue.

Thanks for replying. I will have a try to log out/log in to Google Drive and will leave a comment if it works.

**Comment by non4coder** [comment]
It seems log out and log in again to Google Drive has solved my problem.
