### ISSUE TITLE
2.8.0-snapshot 225896 When you write anything in the search field of the program it crashes unexpectedly

### ISSUE THREAD

**Issue by ssirec** [keepassxreboot/keepassxc#9144]
## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. open a database in KeePassXC
2. type any letter
3. the program crashes

## Expected Behavior
it should search normally

## Actual Behavior
when any key is pressed in search field the program immediately shuts down

## Context
Windows 11 Home 22H2 22621.1265

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.8.0-snapshot
Build Type: Snapshot
Revision: 8dec687

Qt 5.15.6
Debugging mode is disabled.

Operating system: Windows 10 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.22621

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 2.19.1

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 11
Desktop Env: HOME
Windowing System: 22H2

**Comment by droidmonkey** [comment]
Does this happen to you with the latest release as well?

**Comment by ssirec** [comment]
build-225896/ | 2023-02-19 18:30 is already the latest Snapshot Build
https://snapshot.keepassxc.org/build-225896

**Comment by ssirec** [comment]
I've switched back to main channel v2.7.4 and it works fine

**Comment by JohnLGalt** [comment]
I'm using the same version on Windows 11 22H2 (Build 22621.1265). No issues searching anything here.

```
KeePassXC - Version 2.8.0-snapshot
Build Type: Snapshot
Revision: 8dec687

Qt 5.15.6
Debugging mode is disabled.

Operating system: Windows 10 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.22621

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 2.19.1

```

 I also know that recently, 2 different repositories that house Microsoft VisualC++ Runtime module installers have been updates - last week the one from Tech Power Up, and today by developer abbodi. I used the one at TPU to update the runtimes on my system a few days ago. Not sure if that may be a factor or not, but it is rare for both TPU and abbodi to release a new version within a week of each other.

Link to abbodi's git: https://github.com/abbodi1406/vcredist/releases/tag/v0.66.0


Additionally, I don't have the snapshot installed, but run it in portable mode from a folder on my data drive.
