### ISSUE TITLE
Turn search reset off by default

### ISSUE THREAD

**Issue by WhyNotHugo** [keepassxreboot/keepassxc#9145]
## Overview

If I use the search function to find an item, after a short while (a minute?) the undone and results are unfiltered (e.g.: as if I'd never done the search).

## Steps to Reproduce
1. Search for anything that filters out some entries.
2. Wait.
3. Search is undone.

## Expected Behavior

The application should retain it's state and not reset.

## Actual Behavior

The application loses it's state after a short while. I always feel like I have to "rush" for it to not lose what I'm doing.

## Context

The behavior is much on iPhone (and I think Android?), where the OS kills applications in the background after a while, which results in applications losing their state. This is a bug due to a technical limitation, not an actual feature, but KPXC seems to do the same on Linux desktop.

```
KeePassXC - Version 2.7.4
Revision: 63b2394

Qt 5.15.8
Debugging mode is disabled.

Operating system: Linux 6.1.12-0-edge
CPU architecture: x86_64
Kernel: linux 6.1.12-0-edge

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.19.3
```

**Comment by droidmonkey** [comment]
You can disable that in settings, security tab

**Comment by WhyNotHugo** [comment]
Would you consider changing the default for this to disable this anti-feature? It really provides a terrible experience to new users.

What kind of "Security" does this provide?

**Comment by WhyNotHugo** [comment]
Sorry, perhaps I should clarify where this request comes from: I always talk a lot about how people should use password managers rather than reuse passwords, and people around me keep asking me for suggestions on a password manager.

I personally use KPXC, but find it very hard to recommend to others because it has dozens of tiny little "features" like this that regular people just consider bugs. So I don't mean to be hostile in my tone for asking for a change here; I actually want KPXC to provide a better experience for regular users. And I find it hard to understand how getting rid of the current search provides any form of security.

**Comment by droidmonkey** [comment]
#2953 has more haters. I agree off by default would be more user friendly. It isn't a security feature but more of a convienece feature. When you come back to the program after a long while (5min) you typically don't care about the entry you last searched for.

**Comment by WhyNotHugo** [comment]
Moving the setting from "Security" to "General" might also be a good idea (in particular, for users who are wary of fiddling with security-related settings, this would signal that it's safe to touch this one).

However, given that the setting itself is called `Config::Security_ClearSearch`, I'm not sure what you think of the inconsistency between the name and the section in the UI.

**Comment by droidmonkey** [comment]
Just a convenient place to put the setting ui with the spin boxes and other timeouts

**Comment by Chealer** [comment]
Thank you very much @WhyNotHugo for both reporting **and** fixing this!

I agree the setting has nothing to do with security. It also isn't a timeout. It's unlikely someone would understand this setting's effect with its current label and location. It should be moved out of there. Ideally, it should be removed at least from the GUI (who would want such a weird behavior) or renamed and moved to some Advanced tab.

@WhyNotHugo would you please retitle this to something like:

> Search query disappears ("Clear search query after" enabled by default)

I'm so glad to see simply upgrading sufficed to fix this! Have a virtual beer of your taste!
