### ISSUE TITLE
Weird UI on MacOs after last update

### ISSUE THREAD

**Issue by vlebert** [keepassxreboot/keepassxc#9150]
## Overview

After last MacOS update 13.2.1 (22D68), UI seems odd on buttons : 
- Available buttons are grayed
- disabled buttons are not

In other words, contrast in inversed

video: https://share.cleanshot.com/CFTVlQ2B

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - v2.724
Revision: 63b2394

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS

**Comment by vlebert** [comment]
Actually, only dark theme is affected. 
Maybe the MacOs update just switched my app to dark theme I am not sure...

**Comment by droidmonkey** [comment]
Restart keepassxc. You might need to reinstall, make sure all browsers are closed. That isn't normal behavior.
