### ISSUE TITLE
KeePassXC causes Apps to freeze (Linux Gnome Wyland)

### ISSUE THREAD

**Issue by Maximus1996** [keepassxreboot/keepassxc#9151]
## Overview
Hello,
I am using Keepassxc on Opensuse Tumbleweed with Gnome Wayland. Recently Keepassxc has started to make every App where "pasting" is possible (Gedit, Firefox, Gedit etc.) to freeze as soon as a password is copied.
The problem doesn´t happen when logging in with X11

## Steps to Reproduce
1. Open Terminal/Firefox/Gedit
2. Open Keepassxc and copy a passowrd
3. Terminal/Firefox/Gedit is frozen

## Expected Behavior
Possibility to continue using the apps and paste the password.

## Actual Behavior
App with possibility of "pasting" is frozen.

## Context
Opensuse Tumbleweed with Gnome Wyland

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.4
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: Gnome
Windowing System: Wayland

**Comment by droidmonkey** [comment]
#9148 addresses this, and if it doesn't then it is not a keepassxc bug.
