### ISSUE TITLE
Print Notes (HTML)

### ISSUE THREAD

**Issue by thyxNY** [keepassxreboot/keepassxc#9155]
Hi,
I have a lot of notes in keepassxc database. I wanted to print my database but after printing it is not readable.

For example oryginal notes:

UN head António Guterres has condemned Russia's invasion of Ukraine as an "affront" to the world's collective conscience at a meeting of the General Assembly nearly one year on. The meeting was debating a motion backed by Ukraine and its allies demanding Russia pull out immediately and unconditionally. Ukraine hopes that by supporting the motion countries will show solidarity. The Kremlin has accused the West of wanting to defeat Russia at any cost. Vasily Nebenzya, the Kremlin's ambassador to the UN, said the US and its allies were prepared to plunge the entire world into war. Russian President Vladimir Putin sent up to 200,000 soldiers into Ukraine on 24 February 2022 in the biggest European invasion since the end of World War Two. The devastating war that ensued has left at least 7,199 civilians dead and thousands of others injured, according to a UN estimate, but that number is likely to be much higher. The mayor of the Ukrainian city of Mariupol, where mass executions are alleged to have taken place, estimated in April that 21,000 people had died there alone. Russia and Ukraine have each seen at least 100,000 of their soldiers killed or injured, according to the US military. More than 13 million people were made refugees abroad or displaced inside Ukraine.

AAAAAAAAAA BBBBBBBBBB CCCCCCCCCC DDDDDDDDDD EEEEEEEEEE FFFFFFFFFF GGGGGGGGGG HHHHHHHHHH IIIIIIIIII JJJJJJJJJJ KKKKKKKKKK LLLLLLLLLL MMMMMMMMMM NNNNNNNNNN OOOOOOOOOO PPPPPPPPPP QQQQQQQQQQ RRRRRRRRRR SSSSSSSSSS TTTTTTTTTT UUUUUUUUUU WWWWWWWWWW XXXXXXXXXX YYYYYYYYYY XXXXXXXXXX AAAAAAAAAA BBBBBBBBBB CCCCCCCCCC DDDDDDDDDD EEEEEEEEEE FFFFFFFFFF GGGGGGGGGG HHHHHHHHHH IIIIIIIIII JJJJJJJJJJ KKKKKKKKKK LLLLLLLLLL MMMMMMMMMM NNNNNNNNNN OOOOOOOOOO PPPPPPPPPP QQQQQQQQQQ RRRRRRRRRR SSSSSSSSSS TTTTTTTTTT UUUUUUUUUU WWWWWWWWWW XXXXXXXXXX YYYYYYYYYY XXXXXXXXXX

After exporting to HTML and printing in Firefox (page A4):
[firefox.pdf](https://github.com/keepassxreboot/keepassxc/files/10811355/firefox.pdf)
and chrome:
[chrome.pdf](https://github.com/keepassxreboot/keepassxc/files/10811356/chrome.pdf)

Is it possible to little correct export to HTML to more friendly to print?

KeePassXC - Version 2.7.4
Revision: 63b2394

Qt 5.15.6
Debugging mode is disabled.

Operating system: Windows 10 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.19045

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 2.19.1

**Comment by droidmonkey** [comment]
Fixed by #8987

**Comment by thyxNY** [comment]
Looks great! Is version 2.7.5 planned to deploy? Or in 2.8.0? When will be next release?

**Comment by droidmonkey** [comment]
Yes we plan to deploy 2.7.5, buttoning up some important features.
