### ISSUE TITLE
Don't allow showing the Group column outside of a search

### ISSUE THREAD

**Issue by clocklikewoz** [keepassxreboot/keepassxc#9157]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
Showing groups in the entry list does not persist when changing group.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Right click the entry bar (above the actual entry list, can show and sort by Title, Username, URL, etc.)
2. Click "Group" to activate it
3. The group for each entry is now shown
4. Change group via side pane
5. "Group" is no longer shown for each entry in the entry panel

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Showing "Group" should still be shown upon changing groups.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Changing groups no longer shows the "groups" of the entries.
Searching via tags or keywords in the search bar causes the groups to reappear in the entry panel.

## Context
[NOTE]: # ( Give us any additional information you may have. )
I can understand why they don't show if you directly choose a group since they're all the same, but it's inconsistent to have them show up only sometimes. At least for me the group shows up at the very beginning of a line by default, and for it to appear and disappear depending on how I search for entries messes with the alignment. I feel that the group should show at all times if you have chosen for it to be in the list of information shown in the entry panel

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.4
Revision: 63b2394

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: i3
Windowing System: X11

**Comment by droidmonkey** [comment]
I am not sure why it is even possible to show the group column outside of a search, I think that is a bug. When you search a new layout of the columns is presented, this layout includes the group column (since searched entries can come from any group). There is zero reason to show the group column outside of search.
