### ISSUE TITLE
Change default setting: enable "Don't mark the database as modified for non-data changes (e.g. expanding groups)" by default

### ISSUE THREAD

**Issue by macau23** [keepassxreboot/keepassxc#916]
It's very confusing for a new user that they are constantly asked if they want to save their changes, even when they haven't made any.

Yes as non-newbies we know the intricacies of why this is needed, but the default setting should not lead to confusion, and I think that changing the default would be a benefit.

**Comment by droidmonkey** [comment]
For this and other "hidden features for newbies" we should ask on first launch what their preference is. And remind them they can change the in settings

**Comment by macau23** [comment]
I don't know - it seems a very complicated question to present to a new user.

I think their expectation would be that if they add or edit or delete something, then they should be prompted to save their changes.

What is the intent of saving non-data changes? Is it to remember where in the gui they were?

Maybe the default should be to _not_ remember where in the gui they were, but to allow an option to auto-save their place. That way the default would be sensible, but it wouldn't break for those of us that have their keepassxc vaults in version control.

**Comment by leonyu** [comment]
How would this effect file sync applications?

**Comment by droidmonkey** [comment]
Im ok with changing the default since it is rather annoying.
