### ISSUE TITLE
Trouble with shared database in portable version

### ISSUE THREAD

**Issue by hacori** [keepassxreboot/keepassxc#9167]
Hello

I have recently switched from Keepass to KeePassXC and migrated the database. I downloaded the portable version to a Synology NAS which I open from my desktop PC as well as from my laptop.
At the first start of KeePassXC on the second computer, I needed to configure some settings again. So they are obviously stored in the local profile path of Windows and not in the common path (NAS). This had never been the case with Keepass.

Opening the database works. However, on the Laptop there always pops up a message with the request 'please confirm that it's you'. I then have to put my finger on the fingerprint reader (it's obviously using Windows Hello). On the PC, I haven't configured Windows Hello and no message pops up.

The problem I have concerns the connection to the Firefox and Chrome plugins. This doesn't work on the PC anymore. The plugin shows the message 'Die Nachrichtenverschlüsselung ist fehlgeschlagen. Läuft KeePassXC?' / 'Message encryption was not successfull. Is KeePassXC running?'. When I click on the 'Neu laden' / 'Reload' button, it shows 'Schlüsselaustausch war nicht erfolgreich' / 'Key exchange was not successful.
Of course, I never open KeePassXC on both computers at the same time, because I can imagine, there might be issues if I would do that, 

I had set the browser plugin connection first on the laptop. Later, I set it on the PC. I don't remember, if the mentioned error appeared after that on the laptop and I needed to re-established the connections there (delete existing keys and create new ones). If it wasn't on the laptop, I did that once on the PC already.

Just in case it is relevant: On both computers I use a standard user account (same user name). I have a separate admin account on them.

## Expected Behavior
Using the portable version, the browser plugin connection should be successful no matter on which computer the database is accessed from, as long as the names and keys are correct/identical.

## Actual Behavior
The browser plugin connection doesn't work on both (more then one) computers - at least with the portable version.

## Context
I found this issue from a few years ago:
https://github.com/keepassxreboot/keepassxc-browser/issues/698
There's the question: "Where does your registry path point?" with the explanation "I mean the third checkbox from the bottom in KeePassXC's Browser Integration settings, Advanced tab."
I can't see any registry path on that advanced tab. I suppose, this is related to the full installation version.
The option 'Native-Messaging-Manifest beim Start aktualisieren' / 'Renew native-message-manifest on start' is turned on. The other options apart from the one concerning KPH are not activated.

In the browser-integration settings of the database there is an option to renew the ID of the database root group. Can that ID somehow be related to the problem?

## Debug-Info
KeePassXC - Version 2.7.4
Revision: 63b2394
Qt 5.15.6

Operating System:
Windows 10
Version 22H2 - Debug-Info shows Version 2009
Build 19045.2486

**Comment by droidmonkey** [comment]
> as long as the names and keys are correct/identical.

You need to use a unique name for the connection on each computer and for each browser.

**Comment by hacori** [comment]
> > as long as the names and keys are correct/identical.
> 
> You need to use a unique name for the connection on each computer and for each browser.

@droidmonkey: This was a misunderstanding. Of course, I have a seperate name per computer.
With 'identical' I mean between KeePassXC and the plugin on the computer.

Can you reopen the case?

**Comment by droidmonkey** [comment]
I don't see a case here, you haven't provided enough information regarding the errors you have seen to assist. Make sure you have followed our getting started guide and browser troubleshooting guide wiki.

**Comment by droidmonkey** [comment]
Do you use Firefox on one computer and chrome on another? Have you checked the checkbox in the browser integration settings for both of those browsers?

**Comment by hacori** [comment]
In the meantime I have configured Windows Hello (PIN) on the PC and restarted it. Before that, I only had a passwort. Now, the KeePassXP browser extensions are working correctly. I don't understand why this is a requirement, but I can accept it.

**Comment by droidmonkey** [comment]
It isn't a requirement, you might have needed to restart your browser.
