### ISSUE TITLE
Cannot open database when file is hidden (e.g. .passwords.kdbx)

### ISSUE THREAD

**Issue by aucuparia** [keepassxreboot/keepassxc#917]
## Expected Behavior
I should be able to open a database named `.passwords.kdbx`.

## Current Behavior
I am not able to open a database named `.passwords.kdbx` (a notification in red is shown that reads `Unable to open the database. Permission denied`). I am able to open a database named `passwords.kdbx` (which has exactly the same permissions and ownership). 

## Possible Solution
I do not know.

## Steps to Reproduce (for bugs)
1. Install Ubuntu 16.04.3 (LTS)
2. Update packages and reboot
3. Install KeepassXC 2.2.0 using Snap (`sudo snap install keepassxc`)
4. Open KeepassXC, create a database and save it to `passwords.kdbx`
5. Close KeepassXC
6. Copy database to `.passwords.kdbx` (`cp -a passwords.kdbx .passwords.kdbx`)
7. Open KeepassXC and attempt to open `.passwords.kdbx` (in the file selection dialog window, right-click and select `Show hidden files` to show hidden files)

## Context
I want to save my database with a filename that will be hidden by the file explorer so as not to clutter my home directory with it.

## Debug Info
KeePassXC - Version 2.2.0
Revision: 9a7e6850d6b79c47c2d46d99fdaf433c2ff13716

Libraries:
- Qt 5.7.1
- libgcrypt 1.7.6-beta

Operating system: Ubuntu Core 16
CPU architecture: x86_64
Kernel: linux 4.10.0-33-generic

Enabled extensions:
- KeePassHTTP
- Auto-Type
- YubiKey

**Comment by droidmonkey** [comment]
Does it not open or is it just hidden from view?

**Comment by aucuparia** [comment]
It does not open. I updated the description a bit. Here's a screenshot of the error message.
![error](https://user-images.githubusercontent.com/17837210/29925528-d7786cd4-8e60-11e7-970b-89768b99ee2d.png)

**Comment by TheZ3ro** [comment]
Where is placed the file? Snap have permission to only access some specific folders (like `~`) and I think they probably can't access hidden files.

**Comment by droidmonkey** [comment]
Ironically I found the answer through Google right back to our repo!

https://github.com/keepassxreboot/keepassxc/issues/669#issuecomment-311054064

This is a snap issue that is out of our control at this time.

**Comment by TheZ3ro** [comment]
This deserve the "hall of fame" tag as well :smile:

**Comment by bojanpotocnik** [comment]
Any updates on this? It seems like snap added an interface which allows access to dot-files with https://github.com/snapcore/snapd/pull/5845, but KeepassXC does not support it.

```plain
~$ snap connections keepassxc
Interface              Plug                       Slot                            Notes
content[gtk-3-themes]  keepassxc:gtk-3-themes     gtk-common-themes:gtk-3-themes  -
content[icon-themes]   keepassxc:icon-themes      gtk-common-themes:icon-themes   -
content[sound-themes]  keepassxc:sound-themes     gtk-common-themes:sound-themes  -
desktop                keepassxc:desktop          :desktop                        -
desktop-legacy         keepassxc:desktop-legacy   :desktop-legacy                 -
gsettings              keepassxc:gsettings        :gsettings                      -
home                   keepassxc:home             :home                           -
network                keepassxc:network          :network                        -
network-bind           keepassxc:network-bind     :network-bind                   -
opengl                 keepassxc:opengl           :opengl                         -
raw-usb                keepassxc:raw-usb          -                               -
removable-media        keepassxc:removable-media  -                               -
unity7                 keepassxc:unity7           :unity7                         -
wayland                keepassxc:wayland          :wayland                        -
x11                    keepassxc:x11              :x11                            -

~$ sudo snap connect keepassxc:personal-files
error: snap "keepassxc" has no plug named "personal-files"
```

**Comment by droidmonkey** [comment]
Doesn't help us: https://snapcraft.io/docs/personal-files-interface

> The personal-files interface is typically used to provide **read-only access** to top-level hidden data directories within a user’s real home directory
