### ISSUE TITLE
Auto-type window name mismatch

### ISSUE THREAD

**Issue by savchenko** [keepassxreboot/keepassxc#9172]
## Overview
Auto-type picks-up irrelevant entries and misses matching windows titles.

## Steps to Reproduce
1. Trigger auto-type
2. Observe incorrect suggestion(s) and absence of correct ones

## Expected Behaviour
1. It works.

## Actual Behaviour
2. Auto-type dialogue populated with wrong entries.

## Context
I believe this might be caused by duplicated and/or similar entries in the "Window associations", especially when `&mdash;` and `-` are the only characters that differ ~~(relates to https://github.com/keepassxreboot/keepassxc/issues/5735)~~

Keeping only one association per record resolves the problem.

KeePassXC - Version 2.7.4
Revision: 63b2394
Operating System: Windows 10 21H2
Desktop Env: default, NT
Windowing System: DWM

**Comment by droidmonkey** [comment]
I don't understand how this is different than your other issue you linked and how this is a bug in keepassxc. Your window associations are defined by you, not us.

**Comment by savchenko** [comment]
### Example

There is a record for PiHole web interface. It has the following associations:

```
Pi-hole - dns.local — Mozilla Firefox
Pi-hole - dns.local - Mozilla Firefox
Pi-hole - dns.local
Pi-hole - dns.local — Mozilla Firefox
```

Opening PiHole UI and triggering the auto-type does not bring-up the valid record despite the 100% window title match.

However, once the only association left is `Pi-hole - dns.local — Mozilla Firefox`, then it all works again.

There are other similar inconsistencies where seemingly benign records are shown for irrelevant windows with only a faint partial match. `XXXXXXX XXXXXXX - XXXX — Mozilla Firefox` would be one of such patterns.

Can it be due to the lengthy history of this particular database? Is there a "garbage collection" to perform at some point?..

**Comment by droidmonkey** [comment]
Do you have "match url in window title" enabled in the application autotype settings? That will cause seemingly unrelated entries to match if the url matches even a little

**Comment by savchenko** [comment]
You mean _"Use entry URL to match windows for global Auto-Type"_? Yes, had it switched on.
Turned off, will keep an eye on the behaviour for some time.
