### ISSUE TITLE
KeepassXC is not hidden in virtual meetings (tested Google Meet and Microsoft Teams)

### ISSUE THREAD

**Issue by sylann** [keepassxreboot/keepassxc#9175]
## Overview

I was sharing my whole screen in a meeting on Microsoft Teams (web application), and the window of KeepassXC was fully visible to others.

Later, I tested again but with Google Meet (again, the web application) and the window was also entirely visible.

Further details:
- I did not start the application with special options to allow screen recoding to include the window.
- Screen captures do not see the app (as expected).

## Steps to Reproduce

1. Open the app
2. Start a meeting, on any of the aforementioned web applications
3. Share your screen
4. Join with another device and see the app is visible

## Expected Behavior

KeepassXC should not be visible in virtual meetings (on any kind of screen recording). Right?

## Actual Behavior

KeepassXC is visible in virtual meetings (at least on meet.google.com and teams.microsoft.com)

## Context

KeePassXC - Version 2.7.4
Revision: 63b2394

Qt 5.15.6
Debugging mode is disabled.

Operating system: macOS 12.6
CPU architecture: x86_64
Kernel: darwin 21.6.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 2.19.2

**Comment by droidmonkey** [comment]
Not sure we can do anything at all about this. We already tell the operating system to exclude our window from screen recordings. 

https://github.com/keepassxreboot/keepassxc/blob/develop/src/gui/osutils/macutils/AppKitImpl.mm#L227

**Comment by adudek16** [comment]
IMHO, if you share your screen, then that is on you to make sure to close it or move it to another screen.  That is the point of screen share, to share your screen which is all open windows. 
Teams and (I think) meet have options to share specific Apps (open windows) or specific open windows.

**Comment by sylann** [comment]
> Not sure we can do anything at all about this. We already tell the operating system to exclude our window from screen recordings.
> 
> https://github.com/keepassxreboot/keepassxc/blob/develop/src/gui/osutils/macutils/AppKitImpl.mm#L227

Do you mean it could be a problem in the implementation of both those web applications? Or maybe something wrong on MacOS?

I've been told the problem does not happen on windows but I can't confirm.

Anyway, I am only reporting this in case it is not the expected behaviour.
I can only say it was surprising to me and everyone else who has seen the window.

**Comment by droidmonkey** [comment]
It is a problem with macOS and not unique to KeePassXC. I found a discussion about this same thing regarding electron itself which offers an api to hide the window from screenshare and people were running into this same problem. MacOS offers no other api to hide windows.

**Comment by lyallp** [comment]
I am the exact opposite, KeePassXC 2.7.4 IS hidden in TEAMS shared desktop under Windows 10 (corporate install)

It would be nice if there was an option which allowed me to show KeePassXC in a shared screen (maybe even pop up a query dialog if a screen share is in progress) - the reason I ask for this is for training purposes, showing people how to use KeePassXC... or showing team members where things are in a Team KeePassXC database.

**Comment by droidmonkey** [comment]
You'll like this feature then in 2.7.5: https://github.com/keepassxreboot/keepassxc/pull/8841

**Comment by pixeldoc2000** [comment]
@lyallp 
> It would be nice if there was an option which allowed me to show KeePassXC in a shared screen (maybe even pop up a query dialog if a screen share is in progress) - the reason I ask for this is for training purposes, showing people how to use KeePassXC... or showing team members where things are in a Team KeePassXC database.

Try to run KeepassXC with `--allow-screencapture` parameter like `keepassxc.exe --allow-screencapture`, this should do the trick.

**Comment by droidmonkey** [comment]
Closing this as it's not a keepassxc issue.

**Comment by lyallp** [comment]
Awesome, thanks for that.
I gather an upcoming feature is a more comprehensive way of allowing Teams, screen capture, etc to work :)
