### ISSUE TITLE
Problems with QT_SCALE_FACTOR=1.25

### ISSUE THREAD

**Issue by slartibart70** [keepassxreboot/keepassxc#9179]
Two problems when starting keepassxc in wayland with this option:
``` 
QT_SCALE_FACTOR=1.25 keepassxc
```

1) Menus behave strangely, like clicking on the help menu with the mouse and trying to select an entry:
- the neighboring menu appears instead, you have to move the mouse a great distance to the right to select entries of the help menu

2) context menus on an keepass entry behave strangely
- right click on an entry and try to select TOTP or Tags flyout-submenu... this is nearly impossible

3) Copy an entry between two databases
select an entry in database1 with the mouse and drag it to the destination database. This 'move' operation works ok
But when i want to create a copy, i need to press 'Ctrl' additionally on the keyboard. This never gives me a copy (and the 'subicons' near the mouse pointer are also not drawn correctly)

This all works with scale-factor 1

**Comment by droidmonkey** [comment]
This would be a qt problem, please report over at https://bugreports.qt.io

In general, Linux does not support fractional scaling. So 1 or 2 is fine, but not 1.25 or 1.5.
