### ISSUE TITLE
Missing number option in Passphrase Generator 

### ISSUE THREAD

**Issue by pacihak** [keepassxreboot/keepassxc#9180]
![KeepassXC_request](https://user-images.githubusercontent.com/22632076/221889001-fc1bc9df-2658-4d66-9bc2-8ecaf7eda2e2.png)

## Summary
Passphrase Generator cannot add any number required by web services.

## Examples
Password-With-Number9
online generator https://password.garden

## Context
Passphrase is secure, easy to read and remember, but this missing feature unnecessarily slows down using it.

**Comment by droidmonkey** [comment]
Add it manually, we are not adding this as it drives up complexity for no reason. This has been discussed in the past.
