### ISSUE TITLE
Add secret service dbus to snap configuration file

### ISSUE THREAD

**Issue by piorkov** [keepassxreboot/keepassxc#9185]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Try enabling Secret Service Integration in KeepassXC
2. Try using some program that uses a secret from the Secret Service
3. Watch the logs in journalctrl

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Secret Service Integration functionality works 

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
In the logs (jurnalctl) I observe an errors like:
`apparmor="DENIED" operation="dbus_bind"  bus="session" name="org.freedesktop.secrets" mask="bind" pid=8199 label="snap.keepassxc.keepassxc"`
`apparmor="DENIED" operation="dbus_method_call"  bus="session" path="/org/freedesktop/secrets" interface="org.freedesktop.DBus.Properties" member="GetAll" name=":1.14" mask="receive" pid=6690 label="snap.keepassxc.keepassxc" peer_pid=2925 peer_label="unconfined`
`apparmor="DENIED" operation="dbus_method_call"  bus="session" path="/org/freedesktop/secrets" interface="org.freedesktop.Secret.Service" member="SearchItems" name=":1.14" mask="receive" pid=12905 label="snap.keepassxc.keepassxc" peer_pid=2925 peer_label="unconfined"`
`apparmor="DENIED" operation="dbus_method_call"  bus="session" path="/org/freedesktop/secrets/prompt/4a938800484d488c824e643bb7de31b0" interface="org.freedesktop.Secret.Prompt" member="Prompt" name=":1.14" mask="receive" pid=12905 label="snap.keepassxc.keepassxc" peer_pid=2925 peer_label="unconfined"`
`apparmor="DENIED" operation="dbus_method_call"  bus="session" path="/org/freedesktop/secrets/aliases/default" interface="org.freedesktop.Secret.Collection" member="CreateItem" name=":1.14" mask="receive" pid=12905 label="snap.keepassxc.keepassxc" peer_pid=2925 peer_label="unconfined"`
## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.4
Revision: 7729648
Distribution: Snap

Qt 5.15.5
Debugging mode is disabled.

Operating system: Ubuntu Core 20
CPU architecture: x86_64
Kernel: linux 5.19.0-32-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.12.1

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: Gnome
Windowing System: X11

Workaround:
Add:
`
dbus (bind)  bus=session  name=org.freedesktop.secrets,  
dbus (send, receive) interface=org.freedesktop.Secret.Service bus=session,
dbus (send, receive) interface=org.freedesktop.Secret.Prompt bus=session, 
dbus (send, receive) interface=org.freedesktop.Secret.Collection bus=session,
dbus (send, receive) interface=org.freedesktop.DBus.Properties member=GetAll bus=session,
`

to file: /var/lib/snapd/apparmor/profiles/snap.keepassxc.keepassxc

**Comment by droidmonkey** [comment]
We don't support the snap build anymore, switch to flatpak where this was recently enabled.

**Comment by piorkov** [comment]
@droidmonkey thanks for replying.

It may be useful to inform that there is no further support for snap distribution on the project website, in the download section.

**Comment by droidmonkey** [comment]
This might be an easy add though. I'll reopen.

https://github.com/keepassxreboot/keepassxc/blob/develop/snap/snapcraft.yaml#L24

**Comment by JGCarroll** [comment]
You can add the Password Manager Service interface (https://snapcraft.io/docs/password-manager-service-interface) to the three app definitions in `snapcraft.yaml`; the user will still need to give explicit permission either via the GUI or `sudo snap connect keepassxc:password-manager-service` in the terminal (Unless a store override was requested).

The DBus approach in 41b14b0ad08ddd1ecd7373bb7336db5933623218 will likely be rejected when the revision is uploaded for review, and I'm not sure would have the intended effect anyway.

You can see the equivilent of the workaround in the original post; directly in the snapd source relating to that interface:
https://github.com/snapcore/snapd/blob/master/interfaces/builtin/password_manager_service.go#L54

**Comment by droidmonkey** [comment]
Interesting, thanks for pointing out that interface. I wasn't aware of that, and I had my doubts about the dbus add I did. Doesn't really matter at this point since the damn snap won't compile with kde-neon and core22.
