### ISSUE TITLE
Windows 10 2.7.4 does not show 'Entries->Move Up/Down' whereas Linux version does

### ISSUE THREAD

**Issue by lyallp** [keepassxreboot/keepassxc#9186]
## Overview
KeePassXC 2.7.4 on Linux (Gentoo) has the ability to re-order entries in groups using Entries->Move Up and Entries->Move Down.

> KeePassXC - Version 2.7.4
Revision: 63b2394

Qt 5.15.8
Debugging mode is disabled.

Operating system: Gentoo Linux
CPU architecture: x86_64
Kernel: linux 6.1.12-gentoo

Enabled extensions:
- Auto-Type
- SSH Agent
- Secret Service Integration

Cryptographic libraries:
- Botan 2.19.3

I understand this re-orders entries in the database so that they will, in a compatible manner, display in the desired order.

However, KeePassXC 2.7.4 on Windows 10

> KeePassXC - Version 2.7.4
Revision: 63b2394

Qt 5.15.6
Debugging mode is disabled.

Operating system: Windows 10 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.19044

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 2.19.1

## Steps to Reproduce

1. on Linux, open database
2. Choose an entry
3. Move it into a known position, not alphabetical
4. save database
5. Open exact same database on Window
6. Locate entry
7. No option in 'Entries' menu to move the entry.

## Expected Behavior
Expect 'Entries' menu to contain elements for 'Move Up' and 'Move Down' on Windows version

## Context
Exact same database, on Linux and Windows.
Entries do show on windows, generally, in the order set in Linux

Operating System:Windows 10 version 21h2  and Linux - Gentoo Linux Lyalls-PC 6.1.12-gentoo #1 SMP PREEMPT_DYNAMIC x86_64 Intel Core i7-7700 @ 3.60Ghz
Desktop Env: Fluxbox on Linux
Windowing System: X11 on Linux

**Comment by droidmonkey** [comment]
Click the header of any column in the entry view until the sort arrow disappears. You can't move entries when they are sorted.
