### ISSUE TITLE
Multiple Autotype settings per entry

### ISSUE THREAD

**Issue by lyallp** [keepassxreboot/keepassxc#9188]
## Summary
Ability to have multiple named auto-type strings per entry

## Examples

For example Microsoft SQL Server Management Studio has a server/user/password/remember password.

Sometimes I simply want to use a different user on the same server, so only want the user/password auto-typed.
Other times, I want to type the server name, as well as the user/password

I have no idea how this would be implemented, as the auto-type sub-menu is already 5 entries long , maybe
* Named auto-type-string1
* Named auto-type-string2
* user
* user{enter}
* password
* password{enter}

## Context
Purely convenience.

**Comment by droidmonkey** [comment]
You would do this by defining multiple auto-type sequences for the window title and selecting the one you want to use from the global auto-type selection dialog. We will not support adding more choices to the entry level auto-type drop down. Please read our user guide section for more information: https://keepassxc.org/docs/KeePassXC_UserGuide.html#_configure_auto_type_sequences

**Comment by lyallp** [comment]
Sure, that would work, problem is I work in an azure environment with ridiculous levels of remote desktop, so a sequence based on window tittle wont work, cos all the window titles are "Remote Desktop"

**Comment by droidmonkey** [comment]
The autotype selection dialog has a robust search. Give your entries unique enough names and you'll have no problems.

**Comment by lyallp** [comment]
autotype selection? 
Right click the entry -> autotype -> select entry (full string, user, user<CR>,password,password<CR>)

What is this selection dialog? Where is this search?

When entering passwords in a remote desktop application, the window title is always 'remote desktop', so I have to rely on the 'last window selected mechanism.

Applications within the 'remote desktop' may have different entry mechanisms for the same credential, and as such, that is why I wanted to be able to select an Autotype by name. Case and point, remote desktop remembers username, so only requires password, but applications within the remote desktop require both.

My use case is I want the autotype to go to the last selected window, I get no choice. I tried creating multiple entries, with window titles that don't match the last selected window and the default is applied to the last selected window.

**Comment by droidmonkey** [comment]
Please read the user guide I linked, also make sure you are using version 2.7.4

**Comment by lyallp** [comment]
please read my problem... ALL my interactions are through one window title - remote desktop.
I have over a dozen individual logins within that remote desktop, many of which have multiple input streams.
I am using 2.7.4
