### ISSUE TITLE
YubiKey not found after unlocking OS

### ISSUE THREAD

**Issue by mitohund** [keepassxreboot/keepassxc#9189]
## Overview
KeePassXC can't find my YubiKey when my OS is locked and then re-logged in. Restarting KeePassXC fixes this. Could this be related to Flatpak?

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Launch KeePassXC, YubiKey is found, unlock KeePassXC
2. Lock OS (Super + L)
3. Log into OS
4. KeePassXC cannot find YubiKey anymore
5. restart KeePassXC, YubiKey is found again

## Expected Behavior
I would like to be able to log into my system and unlock the running instance of KeePassXC instead of having to restart it.

## Actual Behavior
KeePassXC does not find YubiKey after re-logging in. Has to be restarted.

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.4
Revision: 63b2394
Distribution: Flatpak

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux Debian Sid / Unstable
Desktop Env: Gnome
Windowing System: Wayland

**Comment by droidmonkey** [comment]
If you unplug and plug the yubikey, does that fix it as well?

**Comment by mitohund** [comment]
No, it doesn't. The hardware key dropdown menu stays grey and unselectable.

**Comment by droidmonkey** [comment]
Then this is a flatpak problem and not much we can do about it. Please file a bug with the flatpak development team.

**Comment by lhhel9l3** [comment]
@mitohund did you file a bug with flatpak team? Can you link it here?

I ran into this issue as well. The problem can be reproduced by unplugging/plugging in the yubikey while the kdbx is open in keepassxc flatpak. After that, it is not possible to save changes to the kdbx, as there is an error about the yubikey not being connected. The flatpak app can be restarted as a workaround.

**Comment by mitohund** [comment]
@lhhel9l3 no, I didn't. I think I switched to the AppImage version first - but that caused some issues with AppImage Launcher, which I use. A while later, the Debian package was updated, so I switched to that. Unfortunately, Debian is again quite far behind (currently 2.7.4 instead of 2.7.6).
