### ISSUE TITLE
Password preview text is partially cut off

### ISSUE THREAD

**Issue by deron-dev** [keepassxreboot/keepassxc#9190]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

When I unhide a password in the preview pane, the top of the text is cut off.

![image](https://user-images.githubusercontent.com/24536673/222216809-98e940d0-48ef-4f65-8204-c123a33c54b1.png)

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Create an entry with a password
2. In the "General" section of preview pane for that entry, press the eye icon to unhide the password

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

The password is shown without some portion of the top hidden.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

The bottom of the password text is shown without the top of the text.

## Context
[NOTE]: # ( Give us any additional information you may have. )

### System Info
```
OS: Manjaro Linux x86_64 
Kernel: 6.1.12-1-MANJARO 
DE: Xfce 4.18 
WM: Xfwm4 
WM Theme: Matcha-dark-azul 
Theme: Matcha-dark-azul [GTK2/3] 
Icons: Papirus-Maia [GTK2], Adwaita [GTK3] 
```

### KeePassXC Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
```
KeePassXC - Version 2.7.4
Revision: 63b2394

Qt 5.15.8
Debugging mode is disabled.

Operating system: Manjaro Linux
CPU architecture: x86_64
Kernel: linux 6.1.12-1-MANJARO

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.19.3
```

### Environment Overview
[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: XFCE
Windowing System: X11

## Thanks Devs & Other Contributors!

I'm quite happy to have such a robust FOSS password storage solution. Thanks to everyone who has put effort into the project!

**Comment by droidmonkey** [comment]
Hmmm this was fixed already. Try resizing your preview panel, this seems to be a qt bug and not a keepassxc bug.

**Comment by deron-dev** [comment]
Resizing produced the same issue, but changing the theme to "Classic (Platform-native)" (View > Theme) fixes the issue.

**Comment by 31SFX4** [comment]
I have the same issue. Resizing doesn't change anything, and changing the theme also doesn't help. The Box is just too small.

That's on Kubuntu 22.04 LTS and KeepassXC 2.7.4

Here's a screenshot

![IMG_20230514_144445Z](https://github.com/keepassxreboot/keepassxc/assets/4404285/ba9d027d-2368-4254-9f32-174afe642305)

**Comment by droidmonkey** [comment]
Unfortunately, I cannot replicate this at all. I am not going to make any changes to this view at this time as it will most likely break every other platform.
