### ISSUE TITLE
After unlocking Macbook Pro KeepassXC left pane shows weird characters instead of group names

### ISSUE THREAD

**Issue by gopipalamalai** [keepassxreboot/keepassxc#9197]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Start Keepassxc on Macbook pro 14-inch 2021 (macOS ventura 13.2.1)with LG UHD display connected with Apple magic keyboard and trackpad. This problem started after i upgraded to macos ventura yesterday. Before that I was on 12.x of macos.
2. From the root of your DB uncollapse all the folders/groups in left pane.
3. Lock the macbook  till it goes to sleep
4. Unlock macbook and type in the name of any of your account
5. Gibberish characters are displayed in the left pane and search box.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
No gibberish characters are printed,

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
gibberish characters are printed and cant read group/folder names.

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.4
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS ventura 13.2.1
Macbook pro 14-inch 2021 with LG UHD display connected with Apple magic keyboard and trackpad.

![image](https://user-images.githubusercontent.com/55415440/222823566-0a02f2e0-9fff-40e4-ab00-b778f4759303.png)

**Comment by droidmonkey** [comment]
Reinstall KeePassXC. This was reported as a qt bug and not our program specifically.

**Comment by gopipalamalai** [comment]
I reinstalled and still seeing the issue .

**Comment by droidmonkey** [comment]
Unfortunately this isn't our bug, there isn't anything we can do about it.

**Comment by michaelk83** [comment]
https://github.com/keepassxreboot/keepassxc/issues/8758#issuecomment-1306028198
My impression from the discussion there is that you may need to downgrade Qt.
