### ISSUE TITLE
Entries (sometimes) get a folder/directory icon in root folder of databases created by KeePass

### ISSUE THREAD

**Issue by Chealer** [keepassxreboot/keepassxc#9201]
## Overview
When you create an entry without explicitly setting an icon, KeePassXC uses a default icon for the entry which is either the directory's icon, or a yellow key if the directory doesn't have one.

The fallback to the yellow key icon does not happen in the root folder of my database. Instead, KeePassXC displays the same icon it uses for the root folder, which is - confusingly - a folder icon.

## Steps to Reproduce
0. If necessary, create an affected database. A default database created by KeePass 2.61 suffices.
1. Open an affected database, where the root folder still has its default icon
2. Enter the root folder
3. Create an entry
4. Set a dummy name (let the icon unchanged).
5. Activate the OK button

## Expected Behavior
The entry should have the default entry icon (a key).

## Actual Behavior
The entry has the folder's icon (a yellow folder/directory icon):
<img width="957" height="644" alt="Image" src="https://github.com/user-attachments/assets/3cdccd8e-a668-4170-9eb6-a1596bdd5f6b" />

## Context
This issue is known, as reported in tickets #7321 and #9131. I do not know the precise conditions to reproduce, but:

- This does not happen with a database created by KeePassXC (>= 2.7.4).
- This happened with a database created on 2019-12-22 by a version of KeePass downloaded during Q4 2019.

KeePassXC - Version 2.7.4
Revision: 63b2394

Qt 5.15.6
Debugging mode is disabled.

Operating system: Windows 10 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.22621

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 2.19.1

[🅭🄍](https://www.philippecloutier.com/Common+infrastructure+licensing#its)

**Comment by droidmonkey** [comment]
You need to choose the correct folder icon, it's the closed folder. This isn't our convention, comes from keepass. 

https://github.com/keepassxreboot/keepassxc/issues/7321#issuecomment-1019324689

**Comment by Chealer** [comment]
Thanks @droidmonkey 

I confirm that the following procedure works around (with virtually no penalty):
- Secondary-click the root folder
- Choose "Edit Group..."
- Switch to the _Icon_ tab
- Change the icon selected in the top rectangle from the open folder to the one immediately to its left, i.e. the yellow closed folder  (Confusingly, the radio box can stay on "Use default icon".)
- Activate the _OK_ button

This procedure only needs to be executed **once** per affected database.

**Comment by Chealer** [comment]
@droidmonkey are you saying this only affects databases created by [KeePass](https://keepass.info/)? And if so, are you at least 98% confident that is correct?

**Comment by droidmonkey** [comment]
This isn't a bug. KeePass defines the closed folder icon as the default folder icon, same as us. At some point you must have changed to the open folder icon, which doesn't have an exception applied to it.

**Comment by Chealer** [comment]
I will take that as a no.

> This isn't a bug.

I'm a senior software developer. When I'm not sure a ticket reports a bug, I make that clear. I'm sorry I cannot give complete reproduction instructions at this time, but I'm afraid this ticket does report a bug.

> KeePass defines the closed folder icon as the default folder icon, same as us. At some point you must have changed to the open folder icon, which doesn't have an exception applied to it.

I do not remember everything I did on KeePassXC, but there is not a 1% chance I would have changed the root folder's icon (in particular to choose a different folder icon). Thanks anyway, but we wouldn't all be experiencing this if that was the explanation. In any case, there is no need to fix this by working on the import process. I recommend simply adopting the vision described in #9131. Either:

- consider all fallback icons as such
- remove the open folder icon
- or allow setting no icon when none is necessary/applicable. This would have the added benefits of:
   - allowing the icon to behave contextually, as expected
   - and of making the fallback(s) more prominent (they are currently towards the end)

**Comment by droidmonkey** [comment]
OK, so it looks like KeePass switched over to using the OPEN folder icon at some point, but only for the ROOT folder. I suppose it would make sense to not inherit _any_ folder looking icon onto an entry.

![image](https://user-images.githubusercontent.com/2809491/223009973-195f0fb7-4fe9-4e39-8588-ca0a85438a6b.png)

Sorry about the confusion on this one

**Comment by Chealer** [comment]
Thank you for the fix Jonathan, but since this is an ITS, a ticket’s title should describe the issue, not just a possible solution.

I confirm this works in KeePassXC >= 2.7.5. It turns out this reproduced with a default database created by KeePass (still with 2.61).
