### ISSUE TITLE
Video Recording even though the database is only minimized

### ISSUE THREAD

**Issue by D1visionbyZero** [keepassxreboot/keepassxc#9203]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
You can't make a video recording even though the database is only minimized.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1.  Start Nvidia Shadoplay
2.  Start the recording
3. Recording will stop directly

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Recording should work

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
it's stopped

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows
Desktop Env: Gnome/KDE/XFCE/Mate/Cinnamon
Windowing System: X11

**Comment by droidmonkey** [comment]
Unfortunately nothing we can do about that since that behavior is with the Nvidia software. You'll have to start keepassxc with the allow screencapture flag set or quit the program.
