### ISSUE TITLE
Document Password Generator for Browser Extensions

### ISSUE THREAD

**Issue by varijkapil13** [keepassxreboot/keepassxc#9204]
Hi, 
I was wondering if it would be possible to allow/add password generation for the auto type browser extensions? 
The Browser Extensions already ask to save/update the password on a the website if it detects a password on the website, so it might also be possible to suggest a new password and directly save in the database. Similar to what other password managers also do.

Why this would be helpful?
This would make the user experience much better, in that, that the user do not have to 
 - go to the KeePassXC window 
 - generate a password
 - copy it and enter it on the website
 - optionally save it in the KeePassXC database (sometimes the popup to save the password goes away too quickly when there is redirect on the window)

Additionally, it would also be helpful to have some (maybe stripped down) password generating options directly in the browser.

Thanks!

**Comment by droidmonkey** [comment]
We already offer that. Right click the password field in the browser and select password generator from the KeePassXC sub menu.  Recommend you increase the number of redirects allowed before the new credential banner is hidden. This is done in the extension settings.

**Comment by varijkapil13** [comment]
Ah thanks! do you have a link to the documentation for this? I couldn't find it in the docs..

**Comment by droidmonkey** [comment]
I don't believe it has documentation at this point. Would welcome a submission.

**Comment by varijkapil13** [comment]
What would be a good place to document this? I can submit a PR for this

**Comment by droidmonkey** [comment]
In this section: https://keepassxc.org/docs/KeePassXC_UserGuide.html#_using_the_browser_extension

Which is in this file: https://github.com/keepassxreboot/keepassxc/blob/develop/docs/topics/BrowserPlugin.adoc
