### ISSUE TITLE
Support XF86Copy, XF86Cut, and XF86Paste keys

### ISSUE THREAD

**Issue by triallax** [keepassxreboot/keepassxc#9207]
## Summary
Support XF86Copy, XF86Cut, and XF86Paste keys for copying, cutting, and pasting respectively.

## Context
See https://whynothugo.nl/journal/2022/11/04/copying-with-super-c/. For now, I use this workaround in my Sway config:

```
for_window [app_id="^org.keepassxc.KeePassXC$"] {
    bindsym $mod+x exec wtype -M ctrl -P x
    bindsym $mod+c exec wtype -M ctrl -P c
    bindsym $mod+v exec wtype -M ctrl -P v
}
```

Also, some keyboards have dedicated keys for these keycodes, and people who own such keyboards and use these keys will also benefit.

**Comment by droidmonkey** [comment]
You'll have to submit this through Qt, we don't control the interaction with these keys at the program level. This is likely a missing thing in qwayland. https://bugreports.qt.io

**Comment by triallax** [comment]
Indeed, I found [this upstream ticket](https://bugreports.qt.io/browse/QTBUG-93269). Thanks and sorry for the noise.
