### ISSUE TITLE
HMAC mismatch

### ISSUE THREAD

**Issue by Johnnii360** [keepassxreboot/keepassxc#9208]
## Overview
Unlock my database with my new Yubikey 5 Nano doesn't work. I configed it correctly like in the video and a Challenge-Response Test in the YubiKey Personalization Tool work properly. But KeePassXC don't want to work properly. Every time I want to unlock the database I get a weird password with some c's at the start (cccccc).

## Steps to Reproduce
1. Config the key
2. Set it in KeePassXC
3. Try to unlock

## Expected Behavior
Just unlock the DB.

## Actual Behavior
HMAC mismatch.

## Context
KeePassXC is installed via Ubuntu Repository.

KeePassXC - Version 2.7.4
Revision: 63b2394

Qt 5.15.3
Diagnose is deactivated.

OS: Ubuntu 22.04.2 LTS
CPU-Arc: x86_64
Kernel: linux 5.15.0-67-generic

Active Plugins:
- Auto-Type
- Browser-Integration
- SSH-Agent
- KeeShare
- YubiKey
- Secret-Service-Integration

Kryptographische Bibliotheken:
- Botan 2.19.1

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: Gnome
Windowing System: X11

And no my system isn't overclocked and the RAM is 100% ok (Kingston never fails!).

**Comment by droidmonkey** [comment]
If you are getting a weird password then you aren't using challenge response, sounds like you are using the press to type feature instead

**Comment by Johnnii360** [comment]
In the YubiKey Tool press button was disabled. With it enabled it even fails.

Here some screenshots:
![Bildschirmfoto vom 2023-03-07 13-49-31](https://user-images.githubusercontent.com/15824634/223430169-679d488e-9c6f-4ae5-a30d-810f8f9686fd.png)
![Bildschirmfoto vom 2023-03-07 13-49-55](https://user-images.githubusercontent.com/15824634/223430194-871a9d62-481f-422d-8704-81ec886b9950.png)
![Bildschirmfoto vom 2023-03-07 13-50-03](https://user-images.githubusercontent.com/15824634/223430206-b7b23338-6553-41db-a329-9424d5655cd6.png)

**Comment by Johnnii360** [comment]
Ah okay I get it now! You have to disable the set password first on a existing database. Maybe you should add this to your FAQs. Now it works. :)
