### ISSUE TITLE
Recently used databases not available with roaming profiles (Windows/Linux)

### ISSUE THREAD

**Issue by klada** [keepassxreboot/keepassxc#9209]
## Overview

KeepassXC stores a list of recently used databases. However this does not work in enterprise environments (such as AD domains with roaming profiles).

The reason for this is that KeepassXC stores the `keepassxc.ini`, which contains the list of recently used databases, in the wrong place for both Linux and Windows systems.

* In Windows systems the file is stored in `%APPDATA%\Local\KeepassXC\` instead of `%APPDATA%\Roaming` so it won't be available on other machines and might be deleted after log-off (depending on group policy).
* The same applies to Linux. The file is stored in `$XDG_CACHE_HOME/keepassxc` which, according to the XDG Base Directory Specification, should only be used for non-essential files such as caches. In environments with user home directories on network shares `$XDG_CACHE_HOME` may even point to volatile storage.

## Suggested fix

Do not store recently used databases in `QStandardPaths::GenericCacheLocation` (Linux) `QStandardPaths::AppLocalDataLocation` (Windows).

## Steps to Reproduce

1. Open KeepassXC
2. Open a database and close it again
3. Close KeepassXC
4. Open KeepassXC again -> the last database is present in *Recently used databases*
5. Log off (`%LOCALAPPDATA%` and/or  `$XDG_CACHE_HOME` may be deleted)
6. Log on again after a while
7. Open KeepassXC

## Expected Behavior

After the steps above the list of *Recently used databases* should contain the database from step 2

## Actual Behavior

After the steps above the list of *Recently used databases* is empty (because the ini file is gone)

## Context

* KeePassXC 2.7.4 (Windows/Linux)
* Windows:
  * Domain environment with roaming profiles
* Linux:
  * User home directory in network storage with `$XDG_CACHE_HOME` in local (volatile) storage

**Comment by droidmonkey** [comment]
Use the command line option or environment variable to place your local config file wherever you like: https://keepassxc.org/docs/KeePassXC_UserGuide.html#_command_line_options

The reason it is this way is to allow people to sync their settings without bringing in machine specific settings.
