### ISSUE TITLE
TOTP or HTOP 2FA to unlock database

### ISSUE THREAD

**Issue by jbtrystram** [keepassxreboot/keepassxc#921]
I wonder if it's possible to be able to unlock database with 2FA, other than yubikey. Supporting TOTfree OTP 2FAP or HOTP protocol would allow to use an app on a smartphone to provide a temporary token, thus removing the need to have additional hardware, such as a yubikey.

If I understand correctly, it would requires keepassXC to compute the token to validate it, am I right ?
Is this a feasible approach or it's too complex ? The algorithm in itself doesn't seems very complex.

## Expected Behavior
After typing the password a popup would ak me for the 2FA token. Or maybe i should type the token after my password (concatenate them)

## Possible Solution
If I understand correctly, keepassXC would run the algorithm locally. Maybe using HOTP is simpler since it is based on a counter and not time. However, where do we store the counter ? Another point is that TOTP is safer as tokens are only valid for an short period of time.
Both algorithms work the same, only the counter differ. A shared secret is needed between the token generator (app on my phone) and the server (keepassXC). How this secret is stored ? I think it can't be stored in the database as it is encrypted, but educate me here if I am wrong. Yubikey is supported and I suppose there is a similar problem right ? 

TOTP spec is here : http://www.ietf.org/rfc/rfc6238.txt
HOTP : http://www.ietf.org/rfc/rfc4226.txt

## Context
With 2FA i can bear a simpler password since the one time token provide good additional security.
This ahortens the time spent typing my password :)

Anyhow and whatever you decide to do with this suggestion, i want to thank you for your work as keepassXC is a great app and you are doing an awesome work here :)

**Comment by jbtrystram** [comment]
my bad, I only searched in open issues when I wrote this ! 
https://github.com/keepassxreboot/keepassxc/issues/798 and https://github.com/keepassxreboot/keepassxc/issues/80

is the problem is that the secret needs to be stored somewhere ?

**Comment by droidmonkey** [comment]
Correct, the seed needs to be accessible. you have an open secret at that point and thus no protection.

**Comment by jbtrystram** [comment]
Make sense . Lost bit of time but learned a bit today ! Sorry for the duplicate
