### ISSUE TITLE
Improvement to delete button

### ISSUE THREAD

**Issue by Ebermelho** [keepassxreboot/keepassxc#9210]
Hello,
in first place thank you all for you effort in developing and improving this amazing product.

I would like to suggest a little improvement in regards to the delete button:
1. Make the toolbar customizable (allowing us to show only the icons we want and also move them to other positions)
2. There is an option "Movable toolbar" but it appears to have no functionality on the KeepassXC 2.7.4 for MacOS.
3. If this is not possible in the short time, at least move the delete button away from more constantly used functions like change and copy username (maybe after the settings button) so it cannot be pressed by mistake.
4. Give the delete button a more expressive and recognized icon, like a Trashcan.

Just a side information: It seems I cannot capture the screen of KeePassXC on when taking screenshots.
Is that a bug or a feature?

Thanks again and have a nice day
E.Bermelho

**Comment by droidmonkey** [comment]
Delete button icon improved in #11047
