### ISSUE TITLE
It cannot open databases in hidden files

### ISSUE THREAD

**Issue by Dapid** [keepassxreboot/keepassxc#9213]
## Overview
My database is stores in a hidden file in Linux. Keepass can read it without a problem, but KeePassXC doesn't.

## Steps to Reproduce
1. Copy any kdbx to a hidden file
2. Navigate to the folder, it doesn't appear and not even typing the name works.

## Expected Behavior
I'd expect to be able to read it, at least writing the name.

## Actual Behavior
It only recognises visible files. There is no option to show hidden files in the menu either. 

## Debug info
KeePassXC - VERSION
Revision: REVISION

KeePassXC - Version 2.7.4
Revision: 63b2394

Qt 5.15.8
Debugging mode is disabled.

Operating system: Fedora Linux 37 (Thirty Seven)
CPU architecture: x86_64
Kernel: linux 6.1.14-200.fc37.x86_64

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.19.1

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: LXQt
Windowing System: X11

**Comment by droidmonkey** [comment]
Are you running the snap version of keepassxc? That is a limitation of snaps if so. Use fletpak.

**Comment by Dapid** [comment]
No, the one from the repo.

**Comment by droidmonkey** [comment]
And pressing Ctrl + H in the file open dialog doesn't display the hidden files?

**Comment by Dapid** [comment]
That does work, thank you.

I guess the problem is with the component that makes the dialogue, not keepasxc.

**Comment by Dapid** [comment]
For future people encountering this issue:

* The one from Flatpak (at least on my box) is using the dialogue from Gnome (`xdg-desktop-portal-gnome`)
* The one from the repos seems to be using an embedded picker, since the process is just `keepassxc`.

**Comment by droidmonkey** [comment]
That must be the qt native dialog then

**Comment by regexgit** [comment]
Yes it's OK for Flatpak but I confirm the problem also for Appimage: Ctrl + H  doesn't display the hidden files.

I use this palliative: launch once with command line:
`KeePassXC-2.7.6-x86_64.AppImage --keyfile .foo.kdbx.key .foo.kdbx`

After that, the files are saved and visible in the selection list history

**Comment by chadeldridge** [comment]
If you are using the Flatpak version and Ctrl + H does not work, right click on any file or directory. There should be a "Show hidden files" option in the menu. This just worked for me but unfortunately you have to do this every time you open the "Select files" window.

I'm using the Flatpak install:
KeePassXC - Version 2.7.9
Revision: 8f6dd13
Distribution: AppImage

Qt 5.15.2
Debugging mode is disabled.

Operating system: Linux Mint 22.1
CPU architecture: x86_64
Kernel: linux 6.12.12-x64v3-xanmod1

Enabled extensions:
- Auto-Type
- Browser Integration
- Passkeys
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.19.1
