### ISSUE TITLE
Passwords openly shown in search result

### ISSUE THREAD

**Issue by SpiderD555** [keepassxreboot/keepassxc#9214]
## Overview
passwords should not be shown by default when displaying search results.

## Steps to Reproduce
1. Type something in search field  - for example "bank"

## Expected Behavior
Login field can be openly displayed in the search result
Password is hidden in the search result

## Actual Behavior
Login is hidden
Password is shown in the search result

## Context
I don't think passwords should be shown by default when displaying search results.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.6.6
Revision: 9c108b9

Operating System: Linux Mint 21.1
Desktop Env: Cinnamon
Windowing System: X11

**Comment by varjolintu** [comment]
In the password column? I cannot reproduce it with 2.7.4.

**Comment by SpiderD555** [comment]
I guess that is an issue with 2.6.6 version packed into Ubuntu Linux. I made a bug report for that:
https://bugs.launchpad.net/ubuntu/+source/keepassxc/+bug/2009745

**Comment by droidmonkey** [comment]
View -> Hide Passwords
