### ISSUE TITLE
Windows 10 via Parsec: v2.7.0-2.7.4 draws to an invisible window, but v2.6.6 draws just fine

### ISSUE THREAD

**Issue by danbrakeley** [keepassxreboot/keepassxc#9215]
## Overview

On my work PC, I am unable to see the KeePassXC window when I try running v2.7.0, v2.7.1, v2.7.2, v2.7.3, or v2.7.4. Running v2.6.6 works fine.

Note that when running v2.7.x (and experiencing this issue), the app icon in the taskbar appears as normal, and KeePassXC shows up in Task Manager and WinLister as if it was working fine. However, if I hover my mouse over the taskbar icon, which normally renders a small view of the running app, instead the small view that pops up is entirely black.

The machine in question is running Windows 10 Enterprise, Version 21H2 (OS Build 19044.2604), and is accessed via Parsec (I only have remote access, as the machine is housed at my employer thousands of miles away from me).

Note that on my personal PC, KeePassXC works fine on all versions.

## Steps to Reproduce
1. Connect to my work machine via Parsec
2. Log into Windows
3. Download/install/run KeePassXC-2.7.4-Win64.msi
4. Launch KeePassXC

## Expected Behavior
KeePassXC runs normally.

## Actual Behavior
KeePassXC's window is not visible.

- An outline of where the window would draw blinks into existence for a frame or two as the app starts up, but then immediately disappears.
- Hovering over the taskbar icon for KeePassXC renders a preview of the app that is all black.

## Context

Operating System: Windows 10, Version 21H2 (OS Build 19044.2604)
Video card: NVIDIA GeForce RTX 3080
Driver Version: 517.66
Parsec Build: 150-86h

Note that I cannot see any part of KeePassXC when this issue occurs, so I've made screenshots of what I do see, and the information (including version) that WinLister shows:

### v2.7.4
![image](https://user-images.githubusercontent.com/6772870/223813595-f9715a42-3bd9-404a-b468-fc70ad5e6c7f.png)
![image](https://user-images.githubusercontent.com/6772870/223813631-ebb2b249-3e6f-4a40-aa53-227917c90cb0.png)

### v2.7.0
![image](https://user-images.githubusercontent.com/6772870/223813709-84e51323-9380-4a27-9cac-de325eb99dd6.png)
![image](https://user-images.githubusercontent.com/6772870/223813744-b8d1ae9a-2648-4b9b-b464-4f598f0d9414.png)

### v2.6.6
![image](https://user-images.githubusercontent.com/6772870/223818250-4483e608-4ff4-4e85-905e-b99ea721c932.png)

**Comment by MojoMatt** [comment]
Similar issue same version numbers of keepassxc on windows 11 h2,  winth intel iris video HW. Using teamviewer "webclient in chrome" further, the local desktop user confirms that when the teamviewer user is not signed into the remote computer, the keepassxc window starts and behaves normally. While the Window is visible to the desktop and local user, and a teamviewer session is begun from a remote user, the Keepassxc window becomes hidden and cannot be restored.  Another note if the  New Desktop switching feature is used ( a taskbar icon of a set of black and white squares placed on the windows taskbar by defaults) then then the reveal shows that the program is running however it cannot be restored to the active desktop wheras other running programs still exhibit normal window behavior even with the  teamviewer session running. thanks

**Comment by danbrakeley** [comment]
@MojoMatt Thanks for this! I want to make sure I get all the details correct, can you respond if each of the following details are correct?

So you are seeing the same behavior I documented above, but
1. instead of Windows 10 and Parsec, you are using Windows 11 and TeamViewer?
2. when someone was at the local machine, they could see the KeePassXC v2.7.x window, until a remote user connected, at which point the KeePassXC window disappeared for both the local and remote users?
3. and your problem went away if you reverted back to v2.6.6?

**Comment by MojoMatt** [comment]
On 3/8/2023 12:32 PM, Dan Brakeley wrote:
>
> @MojoMatt <https://github.com/MojoMatt> Thanks for this! I want to 
> make sure I get all the details correct, can you respond if each of 
> the following details are correct?
>
> So you are seeing the same behavior I documented above, but
>
>  1. instead of Windows 10 and Parsec, you are using Windows 11 and
>     TeamViewer?**** yes thats correct
>

>  1. when someone was at the local machine, they could see the
>     KeePassXC v2.7.x window, until a remote user connected, at which
>     point the KeePassXC window disappeared for both the local and
>     remote users?
>
YES thats correct

and your problem went away if you reverted back to v2.6.6?

NO, no alternate version has been tried.  the version in discussion in 
my case is 
https://apps.microsoft.com/store/detail/keepassxc/XP8K2L36VP0QMB     
which is 2.7.4

**Comment by danbrakeley** [comment]
@MojoMatt It might be interesting to uninstall that version and manually download and install 2.6.6 (which can be [found here](https://github.com/keepassxreboot/keepassxc/releases/tag/2.6.6))

**Comment by danbrakeley** [comment]
Ha, I was looking through the 2.7.0 release notes, and saw this: https://github.com/keepassxreboot/keepassxc/pull/6030

**Comment by danbrakeley** [comment]
Lol, yup, that was it.

Well, @MojoMatt, if you pass `--allow-screencapture` to the exe when you run it, then this problem goes away. I did it by copying the KeePassXC shortcut onto my desktop, right-clicking the shortcut, going to properties, and adding ` --allow-screencapture` to the end of the "Target" field, like this:

`"C:\Program Files\KeePassXC\KeePassXC.exe" --allow-screencapture`

So then I wonder if there is way to allow this to be an in-app setting, and to disable it when you don't have a database open? That would let me get into the GUI and change the setting. I suppose it doesn't help someone who doesn't know the setting is there, and then opens a database, and suddenly the window disappears.

Well, I'm fine with just having to make my own shortcut for use on my work machine.

I'm going to close this issue.

**Comment by droidmonkey** [comment]
https://github.com/keepassxreboot/keepassxc/pull/8841

**Comment by danbrakeley** [comment]
Although the problem with that fix is that if you only have something like Parsec, then you'd never see the UI at all, so you couldn't enable that checkbox.

**Comment by droidmonkey** [comment]
Kind of by design but I get the point. That is why the command line flag exists.

**Comment by danbrakeley** [comment]
Yeah, that's why I'd love for it to only enable itself when a database is open. But the current solution is simpler and has less room for future bugs, which is probably better for overall security.
