### ISSUE TITLE
KeeShare stop creating new certificates

### ISSUE THREAD

**Issue by StayPirate** [keepassxreboot/keepassxc#9216]
Even tough KeeShare singed containers have been [deprecated](https://github.com/keepassxreboot/keepassxc/commit/12990e59ada1628a3a491afef045902ef254e38f) since `v2.7.0`, whenever I enable KeeShare on an updated KPXC a new certificate is created.

![image](https://user-images.githubusercontent.com/37073343/223971345-bd55f29b-c0e0-44fd-8393-61fd32d8c48a.png)

AFAIU this is done only for backwards compatibility, and the certificate is not used at all. Unfortunately, the private and public keys are stored in plaintext in the `keepassxc.ini` config file, under the `[KeeShare]` stanza. For me this is an unpleasant behavior, since it (in theory) prevent me to store the `keepassxc.ini` config file publicly within my [dotfiles repository](https://github.com/StayPirate/dotfiles).

With that in mind I have some questions:

* Is this generated certificate **NOT** actually used by KPXC?
  * If yes, can KPXC avoid to create a new certificate when KeeShare is enabled? 
* If the Personal Certificate UI panel was missed during the deprecation of signed containers, can it now be removed?
* Can KPXC avoid to store the certificate's keys in the `keepassxc.ini` configuration file in order to make it more suitable for dotfiles management?
  * They can be stored in a dedicated file
  * Or they could not be stored at all if KPXC doesn't use them and the user doesn't need backward compatibility with signed containers

**Comment by droidmonkey** [comment]
A key has to be generated for backwards compatibility, there was no way around it. It literally means nothing, just random bytes, just ignore it.
