### ISSUE TITLE
Database file has no extension (kdbx)

### ISSUE THREAD

**Issue by aritorhamo** [keepassxreboot/keepassxc#9217]
## Overview
My KeePassXC database file has no file extension. When I create a new database file (Save as...), it doesn't get an extension either. According to the user guide there should be an extension, so I wonder whether this a symptom of a problem and should I be worried. 

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1.  Select "Save database as..." or "Save database backup..." on the menu.
2.  Give name for the database and click "Save".

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Database is saved with the extension kdbx. 

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Database is saved, but has no extension.

## Context
[NOTE]: # ( Give us any additional information you may have. )
- When I choose in the settings "Backup database file before saving", the created file gets the extension (old).kdbx. 
- I have known about this behaviour for a few months now, but don't know whether it was that way from the beginning (I started to use KeePassXC perhaps a year a go).
- I haven't noticed anything else being wrong with the program, but I'm a little worried, because the user guide says that the database file is supposed to have an extension.
 
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.4
Revision: 63b2394

Qt 5.15.3
Debugging mode is disabled.

Operating system: Linux Mint 21.1
CPU architecture: x86_64
Kernel: linux 5.15.0-67-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.19.1

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: Cinnamon
Windowing System: X11 (to my knowing; System Report says this: Display: x11 server: X.Org v: 1.21.1.3 driver: X)

**Comment by droidmonkey** [comment]
Extensions don't mean anything, especially on Linux. They are just nice to have. However, it should be added to the file name. This is likely something dumb with Linux Mint and qt.

**Comment by aritorhamo** [comment]
I actually knew that in Linux files often don't have extensions, and wouldn't have reacted to this otherwise, but the fact that the back-up file is saved with an extension while other saves aren't made me think that something might be wrong. I'm glad to hear that you think there probably isn't anything wrong. Thanks for helping.

**Comment by droidmonkey** [comment]
`My KeePassXC database file has no file extension.`

Ah I missed this detail, so there is no bug here because we are actually being consistent with your current database file. 

With 2.7.x you can specify exactly what your backup file(s) "look like" 

![image](https://user-images.githubusercontent.com/2809491/224524511-56b6ff52-dbd7-4047-8747-3d7bf734dba2.png)

**Comment by aritorhamo** [comment]
Thanks for the additional information droidmonkey. Good to know.
