### ISSUE TITLE
Window size and click geometry frequently gets out of sync in Win10. Suspect DPI issue.

### ISSUE THREAD

**Issue by thedewi** [keepassxreboot/keepassxc#9219]
## Overview
Often the main window appears with content much smaller than the window

## Steps to Reproduce
1. In Win10 on a laptop with various display DPIs, open the main window.

## Expected Behavior
1. That the contents fit the window
2. That clicks are mapped to coordinates consistent with what's on the screen
3. That menus open adjacent to the parent 

## Actual Behavior
Window size and click geometry are completely out of whack so nothing is clickable.

See video: https://user-images.githubusercontent.com/4726656/224216523-0d5e7b0f-9801-4051-86b7-bdf9011a5b4f.mp4

## Context
I suspect this is happening so frequently because my laptop moves between monitors with different DPIs, while keepass is in the tray.

Actively moving the foreground keepass window between monitors with different DPIs causes it to re-evaluate and fix the issues.

Operating System: Windows 10

**Comment by droidmonkey** [comment]
This is 100% a qt problem, the question is... is there anything we can do at our level to fix or prevent this? I'm pretty sure the answer is no. We shouldn't have to do anything either, that is why we are using a ui framework like qt.

**Comment by michaelk83** [comment]
See environment variables at https://keepassxc.org/docs/KeePassXC_UserGuide.html#_command_line_options
There may be more supported by Qt, not listed there.

**Comment by thedewi** [comment]
I'm happy to say I haven't seen this issue in a while. Not sure if an update has bumped the Qt version or if something else has changed on my systems. I think this can probably be closed?
