### ISSUE TITLE
On KDE Wayland, pasting into the application sometimes breaks.

### ISSUE THREAD

**Issue by Naxdy** [keepassxreboot/keepassxc#9221]
## Overview
On KDE Wayland, pasting into the KeepassXC window will break occasionally. Meaning that while the clipboard still works on other apps (both native Wayland and XWayland), pasting into KeepassXC will no longer work. Copying out of KeepassXC still works however, and KeepassXC is still capable of clearing the clipboard.

Restarting the application will resolve the issue.

## Steps to Reproduce
Unclear currently. Will update as soon as info is available.

## Expected Behavior
Pasting into KeepassXC always works

## Actual Behavior
Pasting into KeepassXC sometimes doesn't work, and the application needs to be restarted to make it work again.

## Context
Could potentially be connected to the browser extension (Firefox).

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.4
Revision: 63b2394

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux (Gentoo)
Desktop Env: KDE
Windowing System: Wayland

**Comment by droidmonkey** [comment]
PR is in to fix this
