### ISSUE TITLE
Screenshot security locks remote control software

### ISSUE THREAD

**Issue by jNullj** [keepassxreboot/keepassxc#9224]
## Overview
When using steam remote play/chrome remote desktop if i open keepassxc i get locked out and not able to click anything in the remote desktop.
I understand it is intended to hide keepassxc but user can not close the app remotely and can not interact with anything until physical access to the desktop is restored, i doubt this is intended.
Did not test with rdp with remmina yet

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Connect to remote computer with keepassxc installed using chrome remote desktop or steam remote play
2. Open keepassxc
3. No way to use the desktop remotely

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Remote desktop staying functional while keepassxc is hidden and not accessible remotely.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Remote connection to desktop is locked, focus can not be chanced from keepassxc and user can't close the app.

## Context
[NOTE]: # ( Give us any additional information you may have. )
N/A

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.4
Revision: can't check rn, i belive its at the release tag with commit 63b2394

[NOTE]: # ( Pick choices based on your environment )
For the remote desktop running keepassxc:
Operating System: Windows 10
Desktop Env: N/A
Windowing System: N/A

**Comment by droidmonkey** [comment]
Nothing we can do to prevent that as it's the behavior of the software you are using, not keepassxc. You'll have to launch keepassxc with the `--allow-screencapture` flag

**Comment by carlosm2** [comment]
in macOS (OSX) you have to change to open terminal,
move to Applications `cd /Applications` then execute with this args:
`open -n ./KeePassXC.app --args allow-screencapture`
