### ISSUE TITLE
Database does not lock with TOTP dialog open

### ISSUE THREAD

**Issue by t4777sd** [keepassxreboot/keepassxc#923]
## Expected Behavior
For security I think keepass should still lock even if the TOTP is open. Oftentimes someone would copy it without closing (the same way they would copy a password without locking) and when this occurs keepass stays open forever without locking

## Current Behavior
If TOTP password is visible then keepass will not lock

## Possible Solution
Lock keepass even if TOTP is shown

## Steps to Reproduce (for bugs)
1. View a TOTP password
2. Wait for the lock time and see it does not lock

## Context
Many times I do not close the TOTP password because in order to copy it I focus on a new window and thus forget about keepass. The problem is that it leaves KeePass open in the background unlocked for anyone to steal passwords.

## Debug Info
KeePassXC - Version 2.2.0
Revision: 9a7e6850d6b79c47c2d46d99fdaf433c2ff13716

**Comment by TheZ3ro** [comment]
This is a duplicate of #721 AFAICS

**Comment by droidmonkey** [comment]
Similar but not the same.

**Comment by TheZ3ro** [comment]
It's the same because every dialog will prevent every type of database locking (by timing or by session lock) https://github.com/keepassxreboot/keepassxc/issues/721#issuecomment-312345312

**Comment by droidmonkey** [comment]
I see, also a pending save causes the database lock to be held up. It would be a nice security setting to "auto-save on database lock"
