### ISSUE TITLE
Adding attributes to search

### ISSUE THREAD

**Issue by Alerymin** [keepassxreboot/keepassxc#9234]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )

The goal would be to be able to search something written in an attribute, of course only unprotected ones

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )

I have an account, when I login i use the name "username", but there is also my email address "address@email.com" linked to this account.
My email address got leaked and I need to find all my accounts using this address.
When I search for this email address, I won't find this account because the email address is set as attribute and not as main login

So I want to see this account when searching for this address

**Comment by droidmonkey** [comment]
https://keepassxc.org/docs/KeePassXC_UserGuide.html#_searching_the_database

Use the `attr:` prefix
