### ISSUE TITLE
App crashes when auto locking while new entry is being created

### ISSUE THREAD

**Issue by eljenso** [keepassxreboot/keepassxc#9235]
## Overview
While adding a new entry, I got distracted and after a few minutes I got the message below.
The app crashed and all data entered for the new entry are lost.

![image](https://user-images.githubusercontent.com/2805194/224647039-08e8db94-ccf1-4241-bbb7-621368261242.png)

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Enable "Lock databases after inactivity of"
    - Set it to a few seconds for easy testing
3. Go to "Add entry" screen, but don't save/cancel it
    - No need to fill anything in

## Expected Behavior
Not sure, to be honest. Maybe show the user a dialog that there are unsaved changes?
But no data should be lost.

## Actual Behavior
App crashes and the data for the new entry is lost.

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.4
Revision: 63b2394

Qt 5.15.6
Debugging mode is disabled.

Operating system: Windows 10 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.19045

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 2.19.1

**Comment by varjolintu** [comment]
Already fixed in: #9230.
