### ISSUE TITLE
[Windows] Teams/Outlook SSO windows cannot be autotyped

### ISSUE THREAD

**Issue by GravlLift** [keepassxreboot/keepassxc#9237]
When using an SSO provider (my employer in this case) to log into "Microsoft Teams (work or school)" or Outlook, autotype is unavailable when the SSO window appears. The global autotype shortcut will still apparently function, as if the vault is locked when the key combo is pressed, KeePassXC will prompt for authentication to unlock. Following said lock, however (or if the vault was already unlocked), no Auto-Type selection window will appear, and nothing is entered into the window. 

Autotype functions in all other contexts without issue. I'm able to reproduce this consistently on my Windows 11 machine, but my MacOS laptop suffers from no such issues, autotyping into these SSO windows just fine.

Copying and pasting credentials is the only workaround at the moment. Following a successful login, both Outlook and Teams are authenticated (presumably Windows is sharing auth tokens between the two).

I can't really show the employer's login page, but the border of the window looks like this: 
![image](https://user-images.githubusercontent.com/27774026/224711185-14fef731-7df8-45cd-9ad1-e92083591911.png)

**Comment by droidmonkey** [comment]
Make sure you don't have a window hidden behind, this might be an always on top type window. Also make sure you are using latest version of keepassxc.

**Comment by GravlLift** [comment]
@droidmonkey, confirmed, I'm running version 2.7.4, and I've explicitly clicked on and brought the window to focus without remedying the issue.

**Comment by droidmonkey** [comment]
Does the autotype selection dialog appear? There is a known issue with these Microsoft dialogs that the username or password field becomes unfocused as you toggle between windows. That's not a keepassxc issue though.

**Comment by GravlLift** [comment]
@droidmonkey The autotype selection dialog does not appear. If the vault is locked when the global hotkey is pressed, the unlock/auth window will appear to open the vault, but then there will be nothing further shown.

**Comment by droidmonkey** [comment]
Do you have "Always ask before performing Auto-Type" setting enabled in application settings-> Auto-Type tab? If not, enable that and you'll see a selection dialog.

What I think is happening is you have that setting disabled (unchecked), you have one entry setup to interact with this window, keepassxc auto chooses this entry and then interacts with the window but the focus is broken so it looks like nothing is happening.

**Comment by GravlLift** [comment]
Always ask before performing Auto-Type is and has been checked this whole time. I'd screenshot the setting, but it looks like KeePassXC wisely hides itself during screenshots.

I'm reasonably certain this is an actual bug and not a configuration issue, as I am able to successfully use autotype via the hotkey and selection window in other applications on this computer, including non-browser use. It's only these two Microsoft applications where issues are occurring. 

Is there any sort of application log I can paste here or anything like that?

**Comment by droidmonkey** [comment]
The window has no connection to the functionality of the Auto-Type selection dialog. Logically this scenario makes no sense given my understanding of the code I wrote 🤔

I can test this on my own computer this week.

**Comment by droidmonkey** [comment]
Closing this as nothing will be changed on our end here

**Comment by GravlLift** [comment]
@droidmonkey, I figured out some more info on this one: It seems to have been specifically my hotkey combination that was causing the issue. I had global autotype set to `Shift` + `Alt` + `R`, which I guess gets absorbed by this window and not passed to KeePassXC. Setting the key to `Ctrl` + `Alt` + `A` instead makes the functionality work as intended. 🤷
