### ISSUE TITLE
Feature request: UI improvements

### ISSUE THREAD

**Issue by thomas-mc-work** [keepassxreboot/keepassxc#924]
I just came across [this new password manager tool](https://github.com/kun-zhou/lockit) via [reddit](https://www.reddit.com/r/opensource/comments/6x3upa/shameless_plug_for_a_new_password_manager_with/), including [an introduction video](https://www.youtube.com/watch?v=TZxJ-n1rRZs). I saw some nice ideas which could be possibly adapted by keepassxc:

- smart lists: dynmically created lists based on e.g. favorite items, tags
- 3 pane view: like in any e-mail client:
    - left: general structure
    - middle: items within the selected node
    - right: details of the selected item
- I like the item categories: `login`, `secure note`, `credit card`, `bank account` and `software licence`
- ability to add tags and then filter by them

Also it would be nice to allow the generation of new passwords from the main view, without the need to open a database.

Maybe it's worth to have a look at these features/ideas. What do you think?

**Comment by droidmonkey** [comment]
The password generator works without an active database.

**Comment by ccoenen** [comment]
* 3-pane view is what KeePass (the original windows program) is doing. And something similar is being worked on here: https://github.com/keepassxreboot/keepassxc/pull/879
* You can choose directories as you see fit - this is the closest thing to categories, just more powerful.
* KeePass on Windows has tags, and they can also be searched there. I would assume that this is going to be implemented at some point down the line.

There is currently no smart view (neither KeePass nor KeePassXC), but I'd argue that the quick search / filter serve a pretty similar purpose.

**Comment by thomas-mc-work** [comment]
Alright, that's ok for me so far.

**Comment by ccoenen** [comment]
Hi! This ticket is currently closed, I doubt the devs will see your comment in here. If you have an issue or a suggestion, It's probably a good idea to create a new ticket for it.
