### ISSUE TITLE
Tag menu is impossible to close in native wayland mode

### ISSUE THREAD

**Issue by bbhtt** [keepassxreboot/keepassxc#9240]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Use the flatpak in native wayland mode ie. `flatpak run --nosocket=x11 --env=QT_QPA_PLATFORM=wayland org.keepassxc.KeePassXC`
2. Open an entry
3.  Try to add a tag from the drop down menu
4. The tag menu cannot be closed and the tag doesn't apply

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

The tag menu should be closed after selecting the tag

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

It flickers on click and stays open making it impossible to interact with "Cancel"/"Ok"/"Apply" or other parts of the application.

## Context
[NOTE]: # ( Give us any additional information you may have. )

Started happening recently, probably a QT issue in the KDE runtime.

Works fine when using `xcb` ie. `flatpak run --env=QT_QPA_PLATFORM=xcb org.keepassxc.KeePassXC`, probably also in xwayland.

Screencast:

[Screencast from 2023-03-14 16-59-41.webm](https://user-images.githubusercontent.com/62639087/224989405-a828db62-7694-4c84-b3eb-9cb37a06a553.webm)

[NOTE]: # ( Paste debug info from Help → About here )

```
KeePassXC - Version 2.7.4
Revision: 63b2394
Distribution: Flatpak

Qt 5.15.8
Debugging mode is disabled.

Operating system: KDE Flatpak runtime
CPU architecture: x86_64
Kernel: linux 6.2.5-arch1-1

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.19.1
```

[NOTE]: # ( Pick choices based on your environment )
Operating System: Arch Linux
Desktop Env: GNOME
Windowing System: Wayland

**Comment by droidmonkey** [comment]
That is a standard qt completion menu... but the tags interface is entirely custom. I am hesitant to blame qt but it's only happening in your configuration which is interesting.

**Comment by bbhtt** [comment]
This seems to be fixed right now on the latest runtime and app combo. If someone can confirm also, I'll close.

Right not this is printed on terminal when the menu is opened:

```
qt.qpa.wayland: setGrabPopup called with a parent, QtWaylandClient::QWaylandXdgSurface(0x561327469290) which does not match the current topmost grabbing popup, QtWaylandClient::QWaylandXdgSurface(0x56132788eb00) According to the xdg-shell protocol, this is not allowed. The wayland QPA plugin is currently handling it by setting the parent to the topmost grabbing popup. Note, however, that this may cause positioning errors and popups closing unxpectedly because xdg-shell mandate that child popups close before parents
```

which seems to be a Qt bug https://bugreports.qt.io/browse/QTBUG-81952 that was fixed but not sure why it's back. I don't see any issues though.

**Comment by droidmonkey** [comment]
I don't think anyone else had or noticed this issue
