### ISSUE TITLE
Apple Keychain integration

### ISSUE THREAD

**Issue by watjurk** [keepassxreboot/keepassxc#9241]
## Summary
In short I'd like for keepassxc to sync it's database with apple keychain.
Note that I'm using a macbook as my primary computer.

### Example 1 (keepassxc -> keychain):
1. I'd add a password via the keepassxc interface
2. keepassxc syncs this password with my keychain
3. I'm able to use this synced password on my iphone

### Example 2 (keychain -> keepassxc):
1. I'd add a password via the keychain interface
2. keepassxc syncs itself periodically with keychain
3. I'm able to use this synced password on my mac

## Context
Keeping keychain and keepassxc in sync is tedious.
I need them both because I'm using safari on my phone and google chrome on my macbook.
In safari passwords are provided via keychain and in chrome I'm using the keepassxc browser extension.

**Comment by droidmonkey** [comment]
You should use keepassium or strongbox on your phone. We won't add this integration, it really doesn't make any sense for us. You either use keepassxc and keepass databases or you use apple keychain. You shouldn't be using both.
