### ISSUE TITLE
keepassxc-cli: Read password from stdin

### ISSUE THREAD

**Issue by Macic-Dev** [keepassxreboot/keepassxc#9243]
## Summary
KeepassXC has a `--pw-stdin` option which allows for the database password be read from the standard input, whereas the CLI does not.

## Examples
It would be nice if we could do something like `echo password | keepassxc-cli ls Database.kdbx --pw-stdin`.

## Context
This feature would be useful for scripts interacting with KeePassXC.

**Comment by varjolintu** [comment]
https://github.com/keepassxreboot/keepassxc/issues/8878#issuecomment-1345559749

**Comment by Macic-Dev** [comment]
I already tried `echo password | keepassxc-cli ls Database.kdbx`. It ignores stdin and prompts for a password anyway. Is this a bug?

**Comment by droidmonkey** [comment]
You forgot the \n

**Comment by Macic-Dev** [comment]
The `echo` command already adds a trailing newline. Still, doing `echo -e "password\n" | keepassxc-cli ls Database.kdbx` doesn't work either. I have also tried using `printf` instead of `echo`, but to no avail.

**Comment by droidmonkey** [comment]
Please provide the debug info found in the keepassxc gui about dialog. Help -> About

**Comment by Macic-Dev** [comment]
```
KeePassXC - Version 2.7.4
Revision: 63b2394

Qt 5.15.8
Debugging mode is disabled.

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 6.2.6-arch1-1

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.19.3
```

**Comment by droidmonkey** [comment]
Strange.  Which shell are you using, bash?

**Comment by Macic-Dev** [comment]
Yes, I am using Bash. Here's the output of `bash --version` if it helps:

```
bash --version
GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

**Comment by dzintars** [comment]
As I got there, will leave similar context. I have fresh system. No desktop/window manager. Just plain TTY. I need to clone private Git repo over SSH. My SSH key and other secrets are in the KeePassXC. So... I need to "load" secret database, load the SSH key into agent, etc. I also need to use `secret-tool lookup attr value` to read some secrets into ENV.
And I can't figure out, how could I script `keepassxc-cli open mydb.kdbx -y 2:659649856` for all that.

**Comment by droidmonkey** [comment]
This is not replicable at all on Bash for me. Unfortunately there is nothing here we can fix without reproduction.
