### ISSUE TITLE
Autotype: Make search in all open databases by default a configuration option

### ISSUE THREAD

**Issue by newhinton** [keepassxreboot/keepassxc#9245]
## Summary

When autotype cannot find the correct entry immediately, the user has the choice of searching for an entry. However, the default is to only search "found" entries.

Usually i want to search everything, specifically because nothing was found.
If there are multiple results, it is easy to navigate to them via arrow-keys, but if there are many entries (lets say more than 5) a search is nessessary anyway. Imho in that case, there is no difference between searching the open database, or the current result, because the user has to specifically search anyway. (Drawback: in some circumstances this will increase the amounts of results, and therefore increases the number of "characters" typed in the search to get the desired result)

So my suggestion is to remove the checkbox, and always search in all opened databases.

Alternatives would be to remember the state of the checkbox, or make it configurable, or invert the default.

**Comment by droidmonkey** [comment]
We went back and forth on this very subject when developing the new select dialog. It was originally coded the way you are requesting, but we found that it didn't produce the user experience most people would expect.

**Comment by newhinton** [comment]
Yes i think you are right, this was a mistake on my part. I had one entry misconfigured to always show up. 

Since keepass xc does not actually limit results if no entry was found and therefore works as i wanted, i will close this issue as user-error on my part. Sorry!

**Comment by bullette007** [comment]
I still think it would be nice to have this configurable in the options - as it is for browser integration.

I have multiple databases (e.g., one for work, one for private stuff and one for OTPs) that I often have opened simultaneously and when I do Strg + Alt + A for AutoType, the checkbox to search in all opened databases is mostly unchecked (even if I checked it before) and I have to take my hands off the keyboard to check the box before I can search the entry.

**Comment by droidmonkey** [comment]
Ctrl + F

If the auto type selection is showing only a few items that means you have a match to the window title. I generally don't recommend enabling "match by entry title/url" but that could be why you get a lot of unexpected matches.
