### ISSUE TITLE
Save custom Auto-Type Sequence to use

### ISSUE THREAD

**Issue by aldomach** [keepassxreboot/keepassxc#9246]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
Add the ability to save custom auto-write sequences and retrieve them from the "Auto Type" view

Every time I want to write a new sequence I have to go to my personal blog and copy the ones I use, such as the following.
In the app there is no way to make this easy, such as options to click on a list to add and be able to drag and place to our liking.

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )

For all google accounts and other similar ones like banks I have to use this one.
{CLEARFIELD}{USERNAME}{ENTER}{DELAY 2500}{CLEARFIELD}{PASSWORD}{ENTER}

{CLEARFIELD}{USERNAME}{ENTER}{DELAY 3000}{TAB}{TAB}{CLEARFIELD}{PASSWORD}{ENTER} 

**2FA - TOTP**
Username and Password on one page, TOTP on the next.
{CLEARFIELD}{USERNAME}{TAB}{CLEARFIELD}{PASSWORD}{ENTER}{DELAY 3000}{CLEARFIELD}{TOTP}{ENTER}

**With custom field**
{CLEARFIELD}{S:DNI}{TAB}{CLEARFIELD}{USERNAME}{TAB}{CLEARFIELD}{PASSWORD}{ENTER}

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )

It is very difficult to write the sequence as it currently is, there is no way to click on each option to write its corresponding expression {...} and every time I have to create a new one, I have to look for an old entry, to copy sequence

**Comment by aldomach** [comment]
I see that this was proposed in https://github.com/keepassxreboot/keepassxc/issues/6635

**Comment by droidmonkey** [comment]
Yes this is a duplicate. You could also create an entry that has all your favorite sequences in the notes that you can copy/paste from.
