### ISSUE TITLE
Copying strings from KeePassXC and pasting them in other apps, prefixed with 3 extra bytes (UTF8 BOM) ?

### ISSUE THREAD

**Issue by Rogier-E** [keepassxreboot/keepassxc#9249]
## Overview
When copying text (username, password, notes) from KeePassXC and pasting it in UltraEdit, it seems to contain 3 extra bytes in front: EF BB BF also known as the UTF-8 byte order mark.

Initially I wondered if this is a bug in UltraEdit but it occurs ONLY when copying text from KeePassXC.

## Steps to Reproduce
1. Select something in KeePassXC (a username, a password, or select some text in an entry's notes) and press ⌘C to copy.
2. Switch to UltraEdit and paste it there in a new or existing text document.
3. Everything seems all right, but there are actually 3 extra hidden bytes in front of the inserted text. This is visible if your switch to Hex Mode or save the file and check its size.

## Expected Behavior
I'd expect it to copy the selected contents without the 3 extra bytes.

## Actual Behavior
It prepends 3 extra bytes. Also occurs in the middle of a file. For example if you have a dummy file containing "abcdef" (6 bytes) and select "xyz" from KeePassXC and insert that between abc and def, the resulting is 12 bytes instead of 9, containing in hex:
`61 62 63 EF BB BF 78 79 7A 64 65 66` (note the 3 undesired EF BB BF bytes)

(FYI: UltraEdit always uses utf-8 encoding for all text files by default) 

## Context
I've also been in touch with UltraEdit on this issue. But since KeePassXC is the *only* source that causes this if I copy anything from it, I very much wonder if KeePassXC somehow uses a special internal storage format for the clipboard data. Unlike clipboard contents from any other source, is it possible KeePassXC somehow specifies a special encoding format that causes other software such as UltraEdit to have the UTF-8 B.O.M. prefix?

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.4
Revision: 63b2394
It happens with the latest UltraEdit for macOS as well as earlier versions

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS 10.15 Catalina

**Comment by droidmonkey** [comment]
UTF-8 does not have a BOM. UTF-16 does. UTF-8 does have a "this is a UTF-8 stream" marker which are the bytes you see. This would be a bug in UltraEdit since they should just consume those bytes and move to the next position in the stream.

You are likely not copying UTF-8 text elsewhere, or the other app isn't explicitly saying it is UTF-8, or both. We use Qt for all clipboard operations and we do not inject these bytes ourselves.

Closing this issue since it is not specifically a keepassxc induced problem.

**Comment by Rogier-E** [comment]
> UTF-8 does not have a BOM. UTF-16 does. UTF-8 does have a "this is a UTF-8 stream" marker

Thanks, TIL and of course that makes sense (since there is no variable byte order in UTF-8).

> which are the bytes you see. This would be a bug in UltraEdit since they should just consume those bytes and move to the next position in the stream.

I'll feedback this to the UltraEdit developers.
 
> You are likely not copying UTF-8 text elsewhere, or the other app isn't explicitly saying it is UTF-8, or both. We use Qt for all clipboard operations and we do not inject these bytes ourselves.
> 
> Closing this issue since it is not specifically a keepassxc induced problem.

All clear 👍 Still not sure why this only happens with KeePassXC and not with other apps that also use Qt (likely also for clipboard) but either way the above explanation makes sense. Hopefully the UltraEdit devs can look into this.
