### ISSUE TITLE
Add an option to flatten the output of `ls`

### ISSUE THREAD

**Issue by louib** [keepassxreboot/keepassxc#925]
This option would change the output from, for example
```
dir1/
  dir2/
    entry1
    entry2
```

To
```
dir1/dir2/entry1
dir1/dir2/entry1
```

## Possible Solution
We could add a `-f`, `--flatten` option to the `ls` command for that purpose.

**Comment by fredericschulz** [comment]
As there already is a commit for this issue is it practically closed? Or does it have to be reviewed first?

**Comment by droidmonkey** [comment]
There was #2370 but it needed a lot of work. Looking for a new PR for this issue.

**Comment by fredericschulz** [comment]
I'm sorry I'm still new. So can you just create a pull request for this commit or is there anything to be done in the code?

**Comment by droidmonkey** [comment]
A pill request is new code that needs to be merged. So the code needs writing first
