### ISSUE TITLE
feature: keep file modification date

### ISSUE THREAD

**Issue by chaserene** [keepassxreboot/keepassxc#9250]
## Summary
a per-database and/or global option to preserve the modification date of the password database file when it's saved.

## Context
if we assume frequent usage, this would make it harder to identify a password database among a set of files.

**Comment by droidmonkey** [comment]
Incorrect. It is trivial to identify the password database and we will not implement this. The first two bytes of the file are unique to kdbx files. There is absolutely zero reason to obfuscate your database file.

**Comment by chaserene** [comment]
I'm aware of the unique header, that's why I wrote "harder", not "impossible". checking the initial bytes of all files against a specific pattern requires more sophistication and computation than listing all ordered by their modification dates.

> There is absolutely zero reason to obfuscate your database file.

there is one: to reduce the chances of a wrench attack.

**Comment by nvllz** [comment]
Well... this is really interesting. Nowadays, most operating systems aim for easier file availability. "Recent files" are listed all over the OS, and there are still people who share their PCs. I can see them using this feature, even though it has nothing to do with real security. Think about it this way.

**Comment by droidmonkey** [comment]
File modification date doesn't factor into recently used files
