### ISSUE TITLE
Icons displayed incorrectly after installation.

### ISSUE THREAD

**Issue by Auronius** [keepassxreboot/keepassxc#9253]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
I have installed **KeePassXC 2.7.4** on my [Linux Mint 20.3](https://www.linuxmint.com/edition.php?id=294) computer from the [Ubuntu PPA repository](https://launchpad.net/~phoerious/+archive/ubuntu/keepassxc/). The installation finished successfully.
But, when I launched the application, I have noticed, that the icons displayed **incorrectly** in main program window, and in settings window. Many icons are absent.
![KeePassXC_No_icons_1](https://user-images.githubusercontent.com/13540006/226101052-ea05f520-d0c5-4cb9-8f9f-aec17e9c8566.png)
![KeePassXC_No_icons_2](https://user-images.githubusercontent.com/13540006/226101056-8db461c4-26b1-48a0-8d04-bcb06db0c0c8.png)
![KeePassXC_No_icons_3](https://user-images.githubusercontent.com/13540006/226101057-3a42c77c-63b9-4041-a5d9-6a0aff43fcae.png)

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Install KeePass XC on Linux Mint 20.x computer using Ubuntu PPA repository.
2. Run KeePassXC for the first time.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Icons should display correctly.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Icons do not display correctly, many of them do not display at all

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.4
Revision: 63b2394
![KeePassXC_Debug_Info](https://user-images.githubusercontent.com/13540006/226101249-e900ef7b-688c-4594-8ce7-b5f06c21b560.png)

[NOTE]: # ( Pick choices based on your environment )
Operating System: **Linux Mint 20.3 Una**
Desktop Env: **Xfce 4.16.0**
Windowing System: **Display: x11 server: X.Org 1.20.13 driver: nvidia**

P.s. Yes, I know, that I do not use the latest Linux Mint, but I do not want to change it, because it works great on my old PC. Also for now I do not have time to test a new version.

**Comment by droidmonkey** [comment]
https://github.com/keepassxreboot/keepassxc/issues/4963#issuecomment-655584345
