### ISSUE TITLE
Autotype types wrong passwords if I use Latvian keyboard layout.

### ISSUE THREAD

**Issue by Auronius** [keepassxreboot/keepassxc#9254]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
I have installed KeePassXC 2.7.4 on my [Linux Mint 20.3](https://www.linuxmint.com/edition.php?id=294) computer from the [Ubuntu PPA repository](https://launchpad.net/~phoerious/+archive/ubuntu/keepassxc/). The installation finished successfully.
I live in Latvia, so I use **Latvian (apostrophe)** keyboard layout. It is inconvenient for me to switch between English (US) layout and Latvian (apostrophe) layout, so I have chosen to keep only Latvian layout.
All applications work great with Latvian layout, except KeePassXC Autotype.
When I try to autotype Username and Password, using Latvian (apostrophe) keyboard layout, KeePassXC autotypes wrong passwords, with extra **"** symbols, which are absent in the original password.
![AutotypesWrongPassword](https://user-images.githubusercontent.com/13540006/226102002-610b8c04-586a-4cbb-88e7-e3dedcfd1c65.png)
The same thing happens, when I choose Latvian (tilda) keyboard variant, the only difference is, that I have extra **~** symbols instead of **"** symbols.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Create a database entry
2. Launch URL
3. Make sure, that you have active Latvian (apostrophe) keyboard layout!
4. Perform standard autotype
  ![Autotype2](https://user-images.githubusercontent.com/13540006/226102123-591e3c65-1265-43fb-9c4d-75a23cae0c3f.png)
5. If you have a browser extension, which allows you to see passwords as clear text, no asterisks, you will see, that the password has been auto-typed incorrectly with extra **"** symbols, which are absent in the original password.
 

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Passwords should be auto-typed correctly without any extra symbols.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
When I try to autotype Username and Password, using Latvian (apostrophe) keyboard layout, KeePassXC autotypes wrong passwords, with extra **"** symbols, which are absent in the original password.

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.4
Revision: https://github.com/keepassxreboot/keepassxc/commit/63b2394ed0598aea6b0f5ad16430ac93256c21bb
![KeePassXC_Debug_Info](https://user-images.githubusercontent.com/13540006/226102400-8b868103-432e-4111-b676-d605466a7936.png)

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux Mint 20.3 Una
Desktop Env: Xfce 4.16.0
Windowing System: Display: x11 server: X.Org 1.20.13 driver: nvidia

P.s. Yes, I know, that I do not use the latest Linux Mint, but I do not want to change it, because it works great on my old PC. Also for now I do not have time to test a new version.

**Comment by droidmonkey** [comment]
This is brought up a lot on our issue board. 

https://github.com/keepassxreboot/keepassxc/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature%3A+Auto-Type%22

Here is a potential solution for you, although will have to modify it for your Latvian keyboard. 

https://github.com/keepassxreboot/keepassxc/issues/324#issuecomment-1147947200
