### ISSUE TITLE
KPXC doesn't honor ConfirmAccessItem in [FdoSecrets] when it cannot find the executable path

### ISSUE THREAD

**Issue by StayPirate** [keepassxreboot/keepassxc#9255]
I initially reported this issue to https://github.com/flathub/org.keepassxc.KeePassXC/issues/109, but maybe this place is more appropriate as the behave seems to be related to KPXC in general and not to its flatpaked version.

---

The problem of fingerprinting short-live processes was lengthy discussed https://github.com/keepassxreboot/keepassxc/issues/7571 and https://github.com/keepassxreboot/keepassxc/issues/6458. The quickest workaround is to set `ConfirmAccessItem=false` under `[FdoSecrets]` to revert to 2.6.x behavior.

KPXC does not honor the `ConfirmAccessItem` option and keep showing the following dialog every time Nextcloud-client starts, even though I have `ConfirmAccessItem=false`

![image](https://user-images.githubusercontent.com/37073343/224490294-c96ce29c-6108-4880-9ced-0e5e1ee2775d.png)

Please note that I'm using KPXC installed via flatpak and nextcloud-client too. My best guess is that KPXC has no visibility over the nextcloud binary because it's from another flatpak container.

### Acceptance criteria

When `ConfirmAccessItem` is set to `false` KPXC shouldn't show the "Requesting access" dialog, regardless if it can access the client binary or not.

**Comment by StayPirate** [comment]
> When ConfirmAccessItem is set to false KPXC shouldn't show the "Requesting access" dialog, regardless if it can access the client binary or not.

Can this be consider a bug?

**Comment by nivekuil** [comment]
I think this checkbox is just broken in general. I see the same behavior with the Arch Linux packaged version. Also https://github.com/keepassxreboot/keepassxc/issues/7623#issuecomment-1493301378

**Comment by izbushka** [comment]
Same for me, looks like this checkbox does not work at all regardless of the "executable path".

**Comment by StayPirate** [comment]
@droidmonkey it seems that multiple users are affected by this bug, which makes me understand that the issue is not related to my setup. Might you share your point of view on this? Thanks

**Comment by izbushka** [comment]
Looks like [this patch](https://github.com/keepassxreboot/keepassxc/issues/7571#issuecomment-1663497558) fixes `ConfirmAccessItem` setting
