### ISSUE TITLE
Settings Location

### ISSUE THREAD

**Issue by Kyshman** [keepassxreboot/keepassxc#9258]
@phoerious you had mentioned this a while back...

              Starting with 2.6, the Windows settings have migrated to `%AppData%\KeePassXC` and `%LocalAppData%` only contains things like the window geometry etc. On Linux, this will be in `~/.cache/KeePassXC`, on macOS it's `~/Library/Caches/KeePassXC`..

_Originally posted by @phoerious in https://github.com/keepassxreboot/keepassxc/issues/891#issuecomment-629626034_

Coincidentally I reformatted my machines and while doing piecemeal recovery from a Time Machine backup on macOS I discovered that by default it seems stuff in ~/Library/Caches (at least in 12.6.3 (Monterey)) is left out during Time Machine backups.

Looks like it might not be so safe to have settings there

**Comment by phoerious** [comment]
The stuff written to that folder is only what would be written to %LocalAppData% on Windows. The main settings are in ~/Library/Application Support.

**Comment by droidmonkey** [comment]
Nothing of importance is written to the local settings. Window size and position, last used directory, last open databases, and a couple of other similar settings. If you want to change the location for backup purposes, then you can do that. Please read the user guide for the command line flag / env var.
