### ISSUE TITLE
Deal with clipboard managers' history

### ISSUE THREAD

**Issue by louib** [keepassxreboot/keepassxc#926]
I was browsing through pass' codebase, and stumbled upon [this](https://git.zx2c4.com/password-store/tree/src/password-store.sh#n171).

I was wondering if that's something the cli `clip` command should handle if possible. Maybe we should check for each command used for the different OSes and see if they write history and if we can clear it.

## Expected Behavior
If possible, the password should not be written to a history file after being sent to the system's clipboard.

## Current Behavior
good question.

**Comment by TheZ3ro** [comment]
Seems nice, and also needed in the main program. We had some issue with klipper history before

**Comment by quinncomendant** [comment]
There are so many clipboard manager on macOS it would be hard to make a special case for all of them. It would be better to delegate the responsibility of excluding keepassxc from clippings that are saved to the clipboard manager. I use LaunchBar, and this is how it does it:

![screen shot 2017-09-14 at 16 33 34](https://user-images.githubusercontent.com/6884276/30426669-80238102-996a-11e7-9361-946863bfce68.png)

I also wouldn't want keepassxc to clear my entire clipboard history, as appears to occur in the example you linked (`org.kde.klipper.klipper.clearClipboardHistory `).

**Comment by droidmonkey** [comment]
We have three methods of passing credentials around.... AutoType, Clipboard, and KeePassXC-Browser

**Comment by phoerious** [comment]
This is unpractical. Every application provides its own right-click context menus. Some don't even use the operating system's API for it, so we couldn't even hack ourselves into it without providing a separate hack for each application on each platform (which would mean that we'd need to modify third-party binary executable BTW, which is an absolute no go). As droidmonkey said, we provide three methods. Use one of them.

**Comment by irgendsontyp** [comment]
Just curious: Why did you close this issue?

**Comment by droidmonkey** [comment]
Duplicate of others and too broad
