### ISSUE TITLE
Remove keepassxc from snap store if unmaintained

### ISSUE THREAD

**Issue by philh7456** [keepassxreboot/keepassxc#9261]
If the snap version is no longer maintained as per this comment, (https://github.com/keepassxreboot/keepassxc/issues/9185#issuecomment-1449086197) please remove the snap version from the store and the links on the download page and announce on the blog. Otherwise you are leaving people potentially open to future security issues.

**Comment by droidmonkey** [comment]
Unsupported. Not unmaintained.
