### ISSUE TITLE
Flatpak changelog

### ISSUE THREAD

**Issue by Hasshu** [keepassxreboot/keepassxc#9262]
There were a couple updates for the KeePassXC Flatpak within the last month, but no associated changelogs, so I had to look through the recent [commits](/flathub/org.keepassxc.KeePassXC/commits/master) to figure out what was changed. (Oddly enough, both of those are marked as unverified.)

Could you provide a separate changelog (e.g., via the [blog](https://keepassxc.org/blog/)) for the updates exclusive to the Flatpak version?

**Comment by droidmonkey** [comment]
Nothing was changed in KeePassXC code, these are just packaging changes.
