### ISSUE TITLE
Hide password visibility from KeeShare group

### ISSUE THREAD

**Issue by Mike-FUT** [keepassxreboot/keepassxc#9263]
## Summary
When sharing folders via KeeShare it is possible to display the password used for sharing the database.
Add option or better HKLM level registry key to prevent the password from unhiding.

## Context
What I'm requesting here is purely security by obscurity which I totally understand. Still there's a valid cause.
We want to switch to KeePassXC from our current web based password solution and we need to be able to share passwords between groups of people - for example purchasing department.
Since users are users and they thend to select weak master passwords no matter how much you train them we wand to add Yubikey as "second factor" (well, kind of). That secures the main database in an acceptable way.
For sharing folders we would automatically create the passwords and we (IT dept) will never tell the users about them so they can't start writing them down or whatever.
But still they can be simply displayed and it would be great to add an option to prevent that.

Now I'm totally aware it will not add any actual security but it still does add some security because it reduces the chances that users will accidentally stumble upon the passwords for shared databases.

**Comment by droidmonkey** [comment]
You are choosing the wrong tool for your use case. KeePass, and by extension KeePassXC, are full-trust, full-access password manager if you know the database credentials. We will never pivot from that model. Recommend reconsidering a proper enterprise credentialing solution if you don't want to live in that model. As such, we won't be implementing this feature. Sorry about that. 

With that said, the keeshare settings are pretty obfuscated as it is, and unlikely naive users will discover them through normal use. Even if we did hide the password you still have access to all the entries in that database and they can export them to CSV, change them, delete them, and all sorts of havoc.
