### ISSUE TITLE
Application ignores the cursor theme

### ISSUE THREAD

**Issue by KRC2000** [keepassxreboot/keepassxc#9264]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
When mouse position is inside the window - pointer theme changes. Just migrated to Linux Mint Cinnamon from Linux Mint Xfce, it worked correctly on xfce version
![Screenshot from 2023-03-22 15-49-51](https://user-images.githubusercontent.com/47914319/226925689-335a1175-8f60-41b5-b4df-8c27d738756b.png)
![Screenshot from 2023-03-22 15-50-17](https://user-images.githubusercontent.com/47914319/226925714-c444e199-a1f3-455e-b3ec-ccfa5d4662f3.png)

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Install app using apt(2.6.6) or download and run appimage(2.7.4) 
2. Run the app

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Mouse pointer theme doesn't change

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Pointer theme changes to the default while pointer is inside keepassxc window

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.6.6 / 2.7.4
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: Cinnamon
Windowing System: X11

**Comment by droidmonkey** [comment]
This isn't our bug. See #9239

**Comment by xcpn** [comment]
I had the same problem and finally solved it.

Run this in the terminal and logout to see the changes: `sudo sh -c 'echo "export XCURSOR_SIZE=48" > /etc/profile.d/qt_mouse_pointer_size.sh'`

GNOME uses the cursor from the Adwaita theme with a size of 24 globally, if the cursor size changes for you but it's not the same globally, set it to the one your DE uses found in the 'interface' page via dconf.

- Debian 12
- GNOME 43
- Wayland
- QT5
