### ISSUE TITLE
Allow More Control of Entry Order

### ISSUE THREAD

**Issue by The00Dustin** [keepassxreboot/keepassxc#9265]
## Summary
Ideally, I would like to be able to arrange the order of entries to my preference (in the DB).  Alternatively, at the very least, I would like to be able to sort my entries by multiple columns (i.e. title then username).

## Examples
Here are examples from KeePass 2:
1. I can change the entry order when no sort is defined (this saves in the DB):
![image](https://user-images.githubusercontent.com/91274634/226963252-f15497d7-917a-436e-80d1-3f7d03f2237a.png)
3. I can turn off sorting after turning it on (using the "No Sort" option):
![image](https://user-images.githubusercontent.com/91274634/226963478-13962975-87b0-4fdc-a185-910f462fe448.png)

I don't have a sample image for sorting by multiple columns because KeePass doesn't do this.  In other applications, I think it is often achieved by holding a modifier key while clicking on the second column. However, since KeePass already has my preferred functionality, possibly including the storing it in the database, it seems feasible that would be easier to implement.

## Context
Prior to migrating to KeePassXC because I switched to Apple, I was using KeePass 2.0.  There, it was possible to manually adjust the order of entries within a group and remove sorting to use that order.  I especially liked that feature as it would maintain my entry sorting across multiple instances and allow me to sort slightly different than the computer might decide to (i.e. A=a vs A-Za-z).  However, I also have several entries where I want the same title and different usernames (such as entries for a local application).  I sort my groups by title, but then the usernames end up sorted randomly.  Sorting by username and then re-sorting by title leads to the same issue, presumably because the DB order is still used even though it can't be manipulated.

**Comment by The00Dustin** [comment]
I found https://github.com/keepassxreboot/keepassxc/issues/2295 which says it was merged in 2020, but as far as I can tell, I don't have functionality like this in 2.7.4 for Apple Silicon.

**Comment by The00Dustin** [comment]
If figured it out after going to #4357 from #2295, and it's simple enough, just not what I'm used to in terms of sort UX (where ascending and descending always switch back and forth vs having a third state available).  I'm leaving this open for a maintainer to close in case adding the functionality to menu items seem desirable.

**Comment by droidmonkey** [comment]
We won't support complex sorting schemes, that would be a very niche use case and a lot of code. The sorting and entry movement feature needs to be documented. I'll add that to your other request.

**Comment by droidmonkey** [comment]
We won't support complex sorting schemes, that would be a very niche use case and a lot of code. The sorting and entry movement feature needs to be documented. I'll add that to your other request.

**Comment by marcodome** [comment]
> If figured it out after going to #4357 from #2295, and it's simple enough, just not what I'm used to in terms of sort UX (where ascending and descending always switch back and forth vs having a third state available). I'm leaving this open for a maintainer to close in case adding the functionality to menu items seem desirable.

The (very simple) work-around I'm using is to move all the group entries to a temp folder and then re-insert the entries in the original group one by one, in the order I want...

**Comment by The00Dustin** [comment]
> > If figured it out after going to #4357 from #2295, and it's simple enough, just not what I'm used to in terms of sort UX (where ascending and descending always switch back and forth vs having a third state available). I'm leaving this open for a maintainer to close in case adding the functionality to menu items seem desirable.
> 
> The (very simple) work-around I'm using is to move all the group entries to a temp folder and then re-insert the entries in the original group one by one, in the order I want...

That is a useful tip.  My problem was I didn't know how to get them back into natural order, so this wouldn't have changed anything there, but thanks nonetheless.
