### ISSUE TITLE
Save Remains Disabled After Manual Ordering Changes

### ISSUE THREAD

**Issue by The00Dustin** [keepassxreboot/keepassxc#9266]
## Overview
When I disable sorting and move entries, the save button remains disabled.  If I lock and unlock the database after moving entries when no other changes were made to allow a save, the changes I made are lost.

## Steps to Reproduce
1. Unlock a database containing at least two entries in the same group
2. Disable sort (click on sorted column so it is neither ascending or descending)
3. Manually change the order of the items
4. Lock the database
5. Unlock the database
6. Witness that the change made in (3) has reverted

## Expected Behavior
When I move an entry, the software should recognize that the database has changed and behave accordingly (enable save button, show asterisk next to file name, prompt to save at lock timeout).

## Actual Behavior
The software isn't recognizing the change in entry order as a change to the database.

## Context
As a workaround, I can create and delete a new entry to enable saving.  If I move entries and then do this to save, the changes will not be lost, confirming the database was changed by moving entries even though the software isn't recognizing that.

macO Monterrey:
KeePassXC - Version 2.7.4
Revision: 63b2394

Qt 5.15.6
Debugging mode is disabled.

Operating system: macOS 12.6
CPU architecture: arm64
Kernel: darwin 21.6.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 2.19.2

Windows 10:
KeePassXC - Version 2.7.4
Revision: 63b2394

Qt 5.15.6
Debugging mode is disabled.

Operating system: Windows 10 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.19044

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 2.19.1

**Comment by droidmonkey** [comment]
In addition, custom entry sorting feature needs to be documented in the user guide.

**Comment by droidmonkey** [comment]
In addition, custom entry sorting feature needs to be documented in the user guide.

**Comment by droidmonkey** [comment]
This will be fixed in 2.7.6 and is covered by #9501
