### ISSUE TITLE
drug and drop of entries between folders does not work

### ISSUE THREAD

**Issue by amavlyanov** [keepassxreboot/keepassxc#9269]
## Overview

After Fedora 37 -> 38 upgrade I'm unable to move entries between folders inside the KeePassXC

## Context

Operating System: Fedora Linux 38
Desktop Env: Gnome 44
Windowing System: X11 and Wayland

1. Fedora 38 RPM

    ```text
    KeePassXC - Version 2.7.4
    Revision: 63b2394
    
    Qt 5.15.8
    Debugging mode is disabled.
    
    Operating system: Fedora Linux 38 (Workstation Edition Prerelease)
    CPU architecture: x86_64
    Kernel: linux 6.2.7-300.fc38.x86_64
    
    Enabled extensions:
      - Auto-Type
      - Browser Integration
      - SSH Agent
      - KeeShare
      - YubiKey
      - Secret Service Integration
    
    Cryptographic libraries:
      - Botan 2.19.3
    ```

1. Fedora 38 + flatpak

    ```text
    KeePassXC - Version 2.7.4
    Revision: 63b2394
    Distribution: Flatpak
    
    Qt 5.15.8
    Debugging mode is disabled.
    
    Operating system: KDE Flatpak runtime
    CPU architecture: x86_64
    Kernel: linux 6.2.7-300.fc38.x86_64
    
    Enabled extensions:
      - Auto-Type
      - Browser Integration
      - SSH Agent
      - KeeShare
      - YubiKey
      - Secret Service Integration
    
    Cryptographic libraries:
      - Botan 2.19.1
    ```

**Comment by droidmonkey** [comment]
This was a bug that was supposedly fixed back in Fedora 31 https://github.com/keepassxreboot/keepassxc/issues/3930#issuecomment-558188575

Either way this isn't a keepassxc bug, it is either a Qt (qwayland) or Gnome bug.

**Comment by ailin-nemui** [comment]
@droidmonkey 

The Qt bug is closed since 2020, and I have the same issue with KeepassXC 2.7.4 and Qt  5.15.8

Drag and drop doesn't work even with https://github.com/keepassxreboot/keepassxc/issues/3930#issuecomment-568012940 (`keepassxc -platform xcb `)

 
But on Scribus for example, drag and drop works without issues (which is using the same Qt version)

**Comment by droidmonkey** [comment]
Don't know what to say about this, it works everywhere except specific wayland instances. That is definitely not on the keepassxc side. Also scribus drag/drop is probably for text and not list items. 

Your platform command line attributes may not work with snaps and flatpak.

**Comment by amavlyanov** [comment]
Fedora maintainers confirmed the problem and have told in the bt that the fix will be released "in a few days" (https://bugzilla.redhat.com/show_bug.cgi?id=2186217#c5)

**Comment by Germano0** [comment]
yo, Fedora package maintainer here. Disabling [xcb patch](https://src.fedoraproject.org/rpms/keepassxc/blob/rawhide/f/xcb.patch) fixed the problem on F38
