### ISSUE TITLE
Copy entries between databases

### ISSUE THREAD

**Issue by fernando-mc** [keepassxreboot/keepassxc#927]
I'm unable to copy entries with drag and drop. Instead the entries are moved from one database to another.

## Expected Behavior

I expected to be able to drag entries from one database to another and have the entries copied to the new database and not deleted from the only one.

## Current Behavior

It appears these entries are removed from the first database and added to the second. 

## Possible Solution

Don't have the default remove these entries from an existing database.

## Steps to Reproduce (for bugs)

Not sure if this is a bug or expected functionality but here are the reproduction steps:
1) Open database 1
2) Open database 2
3) Drag highlighted entries from database 1 to the tab within the keepassxc window for db 2
4) Results as described above.

## Context

I can't use this feature because I want to copy entries over, not move them.

## Debug Info

KeePassXC - 2.2.0
Revision: caa49a8ef3ee28ed478192389b21d61107b3b8e0

Libraries:
- Qt 5.9.0
- libgcrypt 1.7.7

Operating system: Windows 10 (10.0)
CPU architecture: x86_64
Kernel: winnt 10.0.15063

Enabled extensions:
- KeePassHTTP
- Auto-Type
- YubiKey

**Comment by fernando-mc** [comment]
Found a hack for this to avoid dev work if you don't want to prioritize.

Step 1 - Move the entries over as described and save the database they're going to
Step 2 - Move them back to the other DB and close the one you moved them to without saving.

Cheers!

**Comment by droidmonkey** [comment]
Supporting right click drag where it presents you with a choice of move, copy, etc would be more elegant. Move on left click drag may not be the desired default option, but it should be doable one way.

**Comment by fernando-mc** [comment]
@frostasm Holding control while I drag it works! Not sure why the _L is included in that gif though. Thanks!

**Comment by frostasm** [comment]
@fernando-mc screenkey app distinguishes between the left and right keys, so the "Control_L" should be read as "Left Contol" :)

**Comment by magkopian** [comment]
On pretty much any file manager, when a file is being dragged and dropped between two directories that belong to different partitions, the result is that the file is being copied instead of being moved.

Of course KeePassXC is not a file manager, but since its tree like group structure resembles that of a file system, I believe that this would be what the default behavior a user would expect. Drag and drop inside the same database should move the entry and copy it when it happens between databases, at least that's my personal opinion.

**Comment by droidmonkey** [comment]
I concur with @magkopian

**Comment by cheesedasher** [comment]
Thank you that worked! However with MacOS use left ALT rather than CTRL. Icon will change to a green + symbol.

**Comment by SynapseScribe** [comment]
it seems that drag-drop moves entries from one db to another. wasn't it supposed to copy?

**Comment by droidmonkey** [comment]
You need to hold CTRL (or ALT on macOS) after dragging and until you drop. Then a copy will be made.

**Comment by dmgeurts** [comment]
Pressing cmd/alt on a Mac doesn't seem to work as a modifier to copy instead of move.

**Comment by hsudbrock** [comment]
Just in case someone stumbles over this as I did: On a Gnome-based Linux system, I also had to use "Alt" instead of "Ctrl".

**Comment by pkoevesdi** [comment]
I have version 2.7.4 on Ubuntu 23.04 and there neither Alt, nor Ctrl, nor Shift nor any combination of them works under Wayland. There I am only able to move, not copy. If I switch over to Xserver, it works with Crl + drop.
So, I'd suggest to reopen this issue.

**Comment by droidmonkey** [comment]
That would be a qt bug (qwayland) not our bug.

**Comment by pkoevesdi** [comment]
What makes You so sure? Everything else works in Wayland. Is there a similar use case oder test that I can perform to see if that works. I would say, it is somewhere between them, and KeepassXC is supposed to work in wayland, isn't it? So, it should take more action than just say "it's waylands fault, we don't care".

**Comment by droidmonkey** [comment]
There are absolutely no code differences on our side between X11 and Wayland, especially as it applies to drag/drop. Qt is responsible for interfacing with Wayland and handles the majority of drag/drop actions. That is why I am so sure.

**Comment by pkoevesdi** [comment]
Is there some other drag/drop action on ubuntu or a different software that's supposed to work the same way, that i could countercheck if that works?

**Comment by droidmonkey** [comment]
I do not know, you would have to find one that is built on top of Qt and is using the Wayland compositor and not being sneaky and using xwayland.

**Comment by droidmonkey** [comment]
@pkoevesdi I just tested this under Wayland in both Flatpak and native builds and it worked fine. Hold down ALT _before_ dragging, keep it held, then drop on a group. A copy is made.

**Comment by pkoevesdi** [comment]
Ah, thank You, pressing `Alt` _before_ was the solution I missed out. Good that we talked, now we have this solution in this thread.

**Comment by clonejo** [comment]
Alt does work on Sway (Wayland), but there is no visual indication at all. I recall there was a little plus on the cursor before.

**Comment by droidmonkey** [comment]
The cursor change would be a qt or qwayland issue

**Comment by codingthat** [comment]
On systems where it does work, one major downside to the current implementation is that it creates a new history entry with the current date/time.  So (especially when done in bulk) the "last modified" field becomes useless.  Is there some way to do it without that occurring?  Or reverse this effect afterwards?  This happens both in "copy" and in "move" mode.

**Comment by droidmonkey** [comment]
It is being addressed now actually

**Comment by codingthat** [comment]
Thanks, @droidmonkey !  As in, for the next release?

**Comment by droidmonkey** [comment]
Possibly https://github.com/keepassxreboot/keepassxc/pull/10481
