### ISSUE TITLE
scroll-to-top of notes behaviour under X11

### ISSUE THREAD

**Issue by bahbarnett** [keepassxreboot/keepassxc#9270]
Using 2.6.2, Debian package, compiled from source.

I have large note entry fields.  Several pages worth of scroll, at times.   Whenever I deactivate, then activate keepassxc's window, it immediately scrolls back to the top of the notes field.   I suspect there is some behaviour with QT activate, and the entire window being re-drawn, but other fields do not do this.  For example, the list of entries does not scroll-to-top when the window is selected.

EG, open keepassxc, view an entry with the notes pane visible.  Scroll down.  Now, select something else (konsole?  xterm?  anything.)  When you re-select keepassxc's window, even by the title bar, the notes pane will scroll to top.

I understand this may be desired behaviour, but if so, could someone point me to where this may be happening?  I'm not very QT knowledgeable, and my google-fu has not turned up and idea as to what is triggering this directly.

I searched where activatewindow was happening, also for instances of verticalscrollbar being set to 0, but nada.

**Comment by droidmonkey** [comment]
We are on version 2.7.4 and the notes field in the preview pane has received several updates.
