### ISSUE TITLE
Can't save Secret Service Integration access to entry 

### ISSUE THREAD

**Issue by niko-lay** [keepassxreboot/keepassxc#9271]
## Overview
I'm just updated kubuntu from 20.04 to 22.04 and keepassxc from 2.6.6 to 2.7.4 and faced an issue with saving permanent access to SSI item. On old version I just saw 2 system notification like "skypeforlinux used item xxx" , but on new new version I se request to provide access to entry on each app launch

## Steps to Reproduce
1. Configure one DB to be a SSI in KPXC setting 
2. Open SSI client application, skype for example
3. allow access to SSI entry and mark  "remember" checkbox
4. Close skype
5. open skype again

## Expected Behavior
only system notification about skype access to a SSI entry

## Actual Behavior
Each time I see request to provide access to entry. Also pressed "allow selected" and "allow all & future", the behaviour is same

![Screenshot_20230327_012406](https://user-images.githubusercontent.com/5228230/227813030-0ce7e067-4647-40b0-8630-a41d9e4ae546.png)
![Screenshot_20230327_012410](https://user-images.githubusercontent.com/5228230/227813033-26a441c5-a8ce-49d7-9f31-b0082a748df4.png)

## Context

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.4
Revision: 2.7.4-1ppa2~jammy1

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: KDE (Kubuntu 22.04)
Windowing System: X11

**Comment by droidmonkey** [comment]
Disable the access request dialog in the fdo secrets portion of the application settings.

**Comment by niko-lay** [comment]
disabled "confirm when password are retrieved by clients" in KPXC settings and this helpers.
