### ISSUE TITLE
Mass edit password

### ISSUE THREAD

**Issue by ZeGuigui** [keepassxreboot/keepassxc#9272]
## Summary
In an enterprise context, many URL can share the same (ldap) password. When I change my password I have to manually edit a bunch of entries. Can you add an option to mass modify the password?

## Examples
Add a "change password" in context menu when multiple entries are selected

## Context
Sometimes it is not easy to add a reference to a primary entry (which solves the problem) because most of the URL are collected through browser plugin

**Comment by droidmonkey** [comment]
Use references, as you mentioned. This is a duplicate of another request that ask for editing multiple entries at once. 

https://keepassxc.org/docs/KeePassXC_UserGuide.html#_entry_cross_reference

**Comment by ZeGuigui** [comment]
Sorry I did not find the existing feature request.
Is it possible to use references for TOTP?

**Comment by droidmonkey** [comment]
No, that is not possible

#1314 is the issue to track for this

**Comment by CattusAter** [comment]
Mass editing is needed! Links don't work when integrated with the browser! Regular KeePass has this feature, and any application that has an account storage feature is usually supported.
