### ISSUE TITLE
Integration with some linux terminal like tilix or terminator

### ISSUE THREAD

**Issue by balucio** [keepassxreboot/keepassxc#9273]
## Summary
Linux terminal integration as plugin for some terminal

## Examples
In my Org we use Bitbucket as git server.  In shared environments store the git password is not an options. Is it possible to directly integrate KeePassXC in terminal, for example as terminal plugin, to easily put the password or copy it on terminal?

## Context
Reduce time to open the interface, looking for correct password, copy and paste it.

**Comment by droidmonkey** [comment]
We have a cli. You can also use autotype for this purpose. We won't make an explicit integration with a terminal.
