### ISSUE TITLE
Yubikey manual recovery

### ISSUE THREAD

**Issue by LecrisUT** [keepassxreboot/keepassxc#9274]
## Summary
The current documented recovery method for a broken yubikey is to program another yubikey with the same secret. The issue is that this not allow for emergency recovery, e.g. if you are on vacation and you cannot access your backups. We should document a way to recover the database manually.

## Context
KeepassDX (or rather the accompanying app) has an experimental emulated key functionality. It would be nice to have an equivalent backed in the KeepassXC app. Or alternatively, simply documenting how to manually input challenge-response would be appreciated.

**Comment by droidmonkey** [comment]
You carry your response secret around with you (or it's at least accessible somehow wherever you are)? That kind of defeats the point of the yubikey, but I get what you are saying here. We do have a recovery utility that was coded for us... there is a feature request to bake that into the program itself #1734.

https://github.com/keepassxreboot/keepassxc/blob/develop/utils/keepassxc-cr-recovery/README.md
