### ISSUE TITLE
Download  - Verification - Windows - not correct?

### ISSUE THREAD

**Issue by Anja001** [keepassxreboot/keepassxc#9277]
## Overview
Download  MSI Installer (64-bit, Windows 10/11)
Verification is not as described

## Steps to Reproduce
1. Download MSI Installer (64-bit, Windows 10/11) https://keepassxc.org/download/#windows 
2. install KeePassXC-2.7.4-Win64.msi
3. Compare Verifying Releases — Windows at https://keepassxc.org/verifying-signatures/  
I should see the following dialog with DroidMonkey Apps, LLC as the verified publisher   

But the described dialog did not appear

## Expected Behavior
    => The described dialog will appear

Operating System: Windows 10 Pro

My Question: Did you change the Software and did not actualise the verification notes?

Thanks and kind regards, Anja

**Comment by droidmonkey** [comment]
It appears midway through before the install actually starts.
