### ISSUE TITLE
URL-Scheme-Override

### ISSUE THREAD

**Issue by Ich-h4lt** [keepassxreboot/keepassxc#928]
## Expected Behavior
make urls like putty://  ssh:// work

## Current Behavior
only cmd:// is possible

## Possible Solution
make an override from putty://SERVER to cmd://putty -ssh -l {USERNAME} {SERVER}
this should be done by the user to provide the ability to connect other programms

**Comment by Ich-h4lt** [comment]
Just a link from the normal keepass http://keepass.info/help/base/autourl.html
It's a great feature i would like to see... no one else?

**Comment by droidmonkey** [comment]
I like it, is on the wish list

**Comment by bakemonoru** [comment]
+1 request, i like it

**Comment by pmorch** [comment]
@droidmonkey : You closed this issue on April 18, but I can't seem to find a commit in the git log that corresponds to a fix to this issue. Was it indeed closed because the issue has been fixed? And which commit fixed it? Or why else was it closed?

**Comment by droidmonkey** [comment]
Weird, must have done this by accident

**Comment by droidmonkey** [comment]
Fixed by #3153
