### ISSUE TITLE
Snap package has invisible tray icon

### ISSUE THREAD

**Issue by Scarabytes** [keepassxreboot/keepassxc#9281]
## Overview
KeepassXC installed via snap has no visible tray icon.

## Steps to Reproduce
1. Install KeepassXC via snap on Kubuntu 22.10
2. Enable minimizing to system tray
3. Minimize the window

## Expected Behavior
I expect the system tray button to have an icon representing the current database state

## Actual Behavior
The system tray button is there but has no icon
![grafik](https://user-images.githubusercontent.com/39307101/229276083-15369d0a-6919-4104-9984-2b905a7369a7.png)

## Context
I saw the old issue (451) about this that said to have the problem solved in 2.2.0, but it apparently is back in 2.7.4 or earlier.

Installing via apt works just fine for the icon, however I need to install via snap to get the browser extension to work properly -- or at least I didn't find any other way to do so.

Regarding the question about the existence of the image files in the other issue: They do seem to exist (as svgs now instead of pngs) in the snap folder structure.
```
/snap/keepassxc/1645/usr/share/icons/hicolor/256x256/apps/keepassxc.png
/snap/keepassxc/1645/usr/share/icons/hicolor/scalable/apps
/snap/keepassxc/1645/usr/share/icons/hicolor/scalable/mimetypes
/snap/keepassxc/1645/usr/share/icons/hicolor/scalable/apps/keepassxc-locked.svg
/snap/keepassxc/1645/usr/share/icons/hicolor/scalable/apps/keepassxc-monochrome-dark-locked.svg
/snap/keepassxc/1645/usr/share/icons/hicolor/scalable/apps/keepassxc-monochrome-dark.svg
/snap/keepassxc/1645/usr/share/icons/hicolor/scalable/apps/keepassxc-monochrome-light-locked.svg
/snap/keepassxc/1645/usr/share/icons/hicolor/scalable/apps/keepassxc-monochrome-light.svg
/snap/keepassxc/1645/usr/share/icons/hicolor/scalable/apps/keepassxc-unlocked.svg
/snap/keepassxc/1645/usr/share/icons/hicolor/scalable/apps/keepassxc.svg
/snap/keepassxc/1645/usr/share/icons/hicolor/scalable/mimetypes/application-x-keepassxc.svg
```
As I don't have much experience with snap, I have no idea why they seemingly aren't found or how to debug where the program actually looks for them.

Please let me know if you need further information. :)

## System details
```
KeePassXC - Version 2.7.4
Revision: 7729648
Distribution: Snap
Qt 5.15.5
OS: Ubuntu Core 20
Architecture: x86_64
Kernel: linux 5.19.0-38-generic
Enabled extensions:
- Auto-Type
- Browser-Integration
- SSH-Agent
- KeeShare
- YubiKey
- Secret-Service-Integration
Cryptographic libraries:
- Botan 2.12.1
```

Operating System: Linux (Kubuntu 22.10, newly installed)
Desktop Env: KDE
Windowing System: X11

**Comment by droidmonkey** [comment]
Switch to flatpak. There is nothing we can do to solve this issue.
