### ISSUE TITLE
Focus of the window for auto-type gets lost

### ISSUE THREAD

**Issue by PlutoEventHorizon** [keepassxreboot/keepassxc#9284]
## Overview

When using Auto-Type for (e.g. Thunderbird) the focus gets lost. The password will not entered in the field.

## Steps to Reproduce

1. I want to login and using Auto-Type
2. Pressing the global shortcut for Auto-Type
3. Selecting the database entry and press Enter
4. sometimes the focus of the input field gets lost
5. Password will not entered into the input field, the input field is greyed (lost focus)

## Expected Behavior

The focus is not lost. After selecting the database entry and pressing the Enter key, the password is entered in the input field.

## Context
 Nothing to add.

KeePassXC - Version 2.7.4
Revision: 63b2394

Operating System: Linux
Desktop Env: XFCE
Windowing System: X11

**Comment by droidmonkey** [comment]
Not something we can fix, that is a problem with Thunderbird itself. You can add a delay to the start of the Auto-Type sequence so you can regain focus. You might also be able to press Tab or Shift+TAB to regain focus through the Auto-Type sequence.
