### ISSUE TITLE
Documentation for Autotype

### ISSUE THREAD

**Issue by Densaugeo** [keepassxreboot/keepassxc#9285]
## Summary

I can't figure out how to use autotype, and the only documentation I can find is at https://keepassxc.org/docs/ . It says:

~~~
Q: Is Auto-Type supported on macOS, Windows and Linux?
A: Yes, Auto-Type works on all three supported platforms.
~~~

That's it.

I'd like to have documentation for:
- What is required to set autotype up. Some forum posts suggest you need a browser extension, others say you need to configure window names in the autotype configuration for an entry. I've tried messing with window names  but couldn't figure out what I was doing. I'd prefer not to install browser extensions if I don't have to (and in either case whether or not they are required should be documented).
- If window names are important, what is the matching syntax? Is there a wildcard character? Do window names have to be a full match or is a partial match acceptable? Can window name matching be bypassed and just use the most recently opened window?
- How to trigger autotype. There's a tab to configure autotype in the lower pane of the main screen, but no obvious way to trigger it.
- Keyboard shortcuts. Forum posts I found suggest ctrl+shift+A is used for autotype, but it only causes the window to flicker and doesn't type anything. There's also a ctrl+shift+V shortcut which opens a dialogue asking to confirm autotype, but after confirming nothing happens.

## Context

I'm trying to autotype username/password into web pages. Nothing special about the accounts, but I am on Linux under Wayland if that matters.

**Comment by droidmonkey** [comment]
You skipped right over the documentation....

https://keepassxc.org/docs/KeePassXC_UserGuide.html#_auto_type

Also in the help menu of the application.  There is also a question mark on the Auto-Type setup area when editing an entry to open this document. 


However, Auto-Type does not work under wayland.
