### ISSUE TITLE
Copy & Paste Suddenly stopped working 

### ISSUE THREAD

**Issue by laymonk** [keepassxreboot/keepassxc#9287]
## Overview

No recent updates or changes.  Just cannot get copy and paste to work now, on 2 different windows 10 installations.  

First, I discovered it was working intermittently ... then it completely stops. 

Even within KeypassXC itself, you cannot copy text from any field and paste into any field

## Steps to Reproduce
1.   Just lunch keypassxc 
2.  try to copy any string (password, username, url) ... and paste anywhere (within keypassxc or into any other app in the system) 
3. 

## Expected Behavior
Copied text can be pasted anywhere with either ctrl+v or menu choice to paste

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Nothing happens ... so, copy never put copied text in clipboard

## Context
[NOTE]: # ( Give us any additional information you may have. )

Unable to copy debug info to the clipboard ... part of the bug, probably ... and on 2 different windows 10 systems. 

KeePassXC - 2.7.4
Revision: 63b2394
Operating System: Windows 10

**Comment by droidmonkey** [comment]
Restart your computer, this isn't a bug normally seen on windows. Also, KeePassXC doesn't control standard clipboard operations so there is no reason you wouldn't be able to copy from the about screen. There must be something external to keepassxc causing this.

**Comment by laymonk** [comment]
Well, other applications on the system are working consistently.

This problem developed simuletnuously in 2 different windows 10
installations.  In both, it was happening intermittently.  Now, one is
still intermittent but the other just would not copy and paste anymore.

I am suspecting keepassxc because other applications are not being affected.  In the meantime, I am trying to troubleshoot the clipboard apps/services in windows 10 too ... just decided to inform you as well.

**Comment by laymonk** [comment]
Well, other applications on the system are working consistently.

This problem developed simuletnuously in 2 different windows 10 installations.  In both, it was happening intermittently.  Now, one is still intermittent but the other just would not copy and paste anymore.  

I am suspecting keepassxc because other applications are not being affected.  In the meantime, I am trying to troubleshoot the clipboard apps/services in windows 10 too ... just decided to inform you as well.

**Comment by droidmonkey** [comment]
Without any further information I cannot do anything about this report. Closing this unless you have a definitive reason for why it would be happening.

**Comment by ScottishRob** [comment]
Same problem for me.  KeePass works fine, KeepassXC does not paste anything, even into Notepad

**Comment by TwizzyDizzy** [comment]
Hi folks,

how would I go about collecting debug information about this issue? I recently got hit, but I'm on Linux.

Cheers
Thomas
