### ISSUE TITLE
KeePassXC screen freeze after 5-10 min of being open (Windows 10)

### ISSUE THREAD

**Issue by Tim00n** [keepassxreboot/keepassxc#9288]
1. Open the app 
2. Enter master password
3. App is idle and not in active use for 5-10 min.
4. Completely frozen und unresponsive screen 
5. Quit button won't work (CTRL+Q)
6. Task must be killed manually

**Comment by droidmonkey** [comment]
Possibly related to this: https://github.com/keepassxreboot/keepassxc/pull/9230

Otherwise reinstall, this is definitely not an issue for anyone else

**Comment by Tim00n** [comment]
It should be unrelated to #7660 because #9288 doesn't even give an error feedback. It just freezes. I did reinstall and still run into the same issues.  Why was this preemptively closed?

**Comment by droidmonkey** [comment]
Because it's unique to your system. Without any additional information it is impossible to diagnose.
