### ISSUE TITLE
keepassxc fails to open file via ftp

### ISSUE THREAD

**Issue by droidus** [keepassxreboot/keepassxc#9289]
## Overview
Upon attempting to open/load a keepass file on a ftp share (after credentials were entered), nothing happens (no password prompt to access vault). 

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Click Open
2. Go to FTP share drive where keepass vault file is
3.  Select appropriate keepass vault file
4. Click Open

## Expected Behavior
Should be prompted for vault password file

## Actual Behavior
Nothing. 

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.4
Revision: 7729648
Distribution: Snap

Qt 5.15.5
Debugging mode is disabled.

Operating system: Ubuntu Core 20
CPU architecture: x86_64
Kernel: linux 5.4.0-146-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.12.1

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: KDE
Windowing System: ?

**Comment by droidmonkey** [comment]
Switch to flatpak

**Comment by DuaneKaufman** [comment]
Hello,
I have just installed KeepassXC via flatpak on Debian Linux, but cannot open a database file stored via ftp.
![image](https://github.com/keepassxreboot/keepassxc/assets/5613504/c592e47c-6248-405c-9310-bcdf34828966)

When I try to open a database via the ftp:/<databaseserver/databasepath>, KeepassXC asks for the ftp user and password, but then complains that it cannot open the database file - it is looking for it in my _home_ directory though.
![image](https://github.com/keepassxreboot/keepassxc/assets/5613504/ddadf022-267f-4d0a-afbf-03adfcd78b70)

Does KeepassXC support storing database files on an ftp server?

Sincerely,
Duane Kaufman

**Comment by droidmonkey** [comment]
See https://github.com/keepassxreboot/keepassxc/pull/7222
