### ISSUE TITLE
Cancel Windows Hello confirmation for next unlock

### ISSUE THREAD

**Issue by gracie95** [keepassxreboot/keepassxc#9292]
## Overview
On fresh opening, you must input Windows Hello credential to unlock. But, still the same database, the next unlock you don't need to confirm again just press cancel while Windows Hello confirmation appear.

https://user-images.githubusercontent.com/107738923/229844592-36c640f0-6c5e-44f5-9cd0-72fb2d188ce0.mp4

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Open a database through Windows Hello confirmation
2. Lock again the database 
3. Unlock again, but just press cancel button on the Windows Hello confirmation
4. The database was opened.
## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
It should ask again if computer was locked or database was locked by owner. It could be access by others without knowing.
## Context
KeePassXC - Version 2.7.4
Revision: 63b2394
Qt 5.15.6
Debugging mode is disabled.
Operating system: Windows 10 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.22621
Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock
Cryptographic libraries:
- Botan 2.19.1

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 11

**Comment by droidmonkey** [comment]
You just canceled being able to use quick unlock.
