### ISSUE TITLE
Autocomplete usernames option not available anymore

### ISSUE THREAD

**Issue by ptitpied** [keepassxreboot/keepassxc#9293]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

According to this [link](https://github.com/keepassxreboot/keepassxc/pull/3300), a feature request has been created in 2019 to autocomplete username during creation entry phase.
It works well for the existing entries but does not update any new username on the drop down list.

After short check, the option to enable/disable this feature is not anymore available on the setting properties of Keepassxc.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1.  Open KeepassXC
2.  Click on "setting" button
3.  Go to **Entry Management**
4.  The line `Autocomplete username on typing`  is not available anymore

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

Thanks to this feature, after creating a new username, it should be suggestion for any new entry creation.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
The drop down list is not anymore update.

## Context
[NOTE]: # ( Give us any additional information you may have. )
Just have a look on the pull  #3300 and you will see what is going wrong (crystal clear)

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.4

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS

**Comment by varjolintu** [comment]
For me the autocomplete works with both new and existing entries. There's even a small down arrow at the right side of the username field which shows all usernames used on other entries.

**Comment by droidmonkey** [comment]
works fine for me. The usernames list is updated when the database is saved.

**Comment by ptitpied** [comment]
ok, interesting.
And have you still the dropbox option "Autocomplete username on typing" on the setting properties?

**Comment by ptitpied** [comment]
@droidmonkey, please do NOT close the issue so fast.
I've a problem with new username that is not populated on the drop list.

So please take time to investigate properly or let me know what do you need exactly?

**Comment by droidmonkey** [comment]
How can I investigate it when it works? The setting you mentioned was never merged into the code base, that is just an example image from the original PR submission.

**Comment by ptitpied** [comment]
@droidmonkey 
OK understood. After deeper analysis, you are right the list is well updated.
However the drop down list is limited to 10 suggestions, that's why I didn't see my new username as I've already reached the limit.

How could you fix that?
Or maybe better : Sort by last one username used, what do you think?

**Comment by droidmonkey** [comment]
It is the 10 MOST USED usernames. We aren't going to change that behavior
