### ISSUE TITLE
Hardware key removed from database by itself.

### ISSUE THREAD

**Issue by jarppu** [keepassxreboot/keepassxc#9294]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
I noticed a bug with keepassxc. I've been using a keepassxc database with yubikey hardware key.  Today I opened the database normally using my master password + yubikey. Then I did some edits to the database(added notes) and then I made copy of the database. I tried to open this copied database but it wouldn't open. After some troubleshooting I tried to open the database without the yubikey. And it opened! So somehow keepassxc removed the hardware key from the database by itself.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1.  Open database with yubikey
2.  Make changes
3.  Make a copy of the database
4. Try to open the database with yubikey

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Keepassxc database should still require hardware key to open

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Hardware key no longer needed to open database / Cannot open the database with hardware key

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.4
Revision: 63b2394

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 10

**Comment by droidmonkey** [comment]
> then I made copy of the database

How did you do this? File copy? Save As?

**Comment by jarppu** [comment]
File copy. Ctrl+c, ctrl+v in windows explorer.

**Comment by droidmonkey** [comment]
there is no way that removed the hardware key. You must have copied a database backup that didn't have the hardware key setup to begin with.

**Comment by jarppu** [comment]
Maybe the copying didn't cause it. Perhaps making the changes(I added some notes) caused it.

**Comment by droidmonkey** [comment]
No way that caused it either. You would have had to go to the database security settings and removed the hardware key.
