### ISSUE TITLE
New entry title not filled after search

### ISSUE THREAD

**Issue by Allain18** [keepassxreboot/keepassxc#9295]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
When searching for an entry and creating a new one, the title field is left empty. On 2.73 and earlier, the title field was filled with the search.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Search for an entry not existing
2. Press the "Add new entry" button

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
The title field is already filled with the search

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
The title field is empty

## Context
[NOTE]: # ( Give us any additional information you may have. )
It was working on 2.7.3 and before

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.4
Révision : 63b2394

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 10

**Comment by droidmonkey** [comment]
This feature was removed on purpose.
