### ISSUE TITLE
Extra "Unlock Database" dialog won't go away

### ISSUE THREAD

**Issue by the8tre** [keepassxreboot/keepassxc#9297]
## Overview
When triggering database opening from the browser extension an "Unlock Database" dialog shows up in addition of the main database window. Upon unlock the extra dialog remains with greyed out content and can't be closed.

## Steps to Reproduce
1. Make sure KeePassXC database is locked and UI is minimized (tray icon)
2. From the browser extension hit "Reopen database"
<img width="350" alt="Capture d’écran 2023-04-05 à 11 22 13" src="https://user-images.githubusercontent.com/7083377/230039145-21decf3e-9364-4004-ba51-b938d0e4145a.png">

4. The main app window shows up + an extra "Unlock Database" dialog
<img width="1068" alt="unlock database window" src="https://user-images.githubusercontent.com/7083377/230035926-dcfbc9b1-7a8a-41a4-88e6-e189dcd14cec.png">

5. Unlock the database
6. The database is properly unlocked but the extra window remains on top and can't be closed
<img width="969" alt="unlock database dialog stuck" src="https://user-images.githubusercontent.com/7083377/230036296-bd87b62c-0f92-4364-8ee0-5f3d611116b6.png">

## Expected Behavior
Either the extra "Unlock Database" dialog shouldn't show up or it should go away once unlock is performed

## Actual Behavior
The extra dialog remains on top of other windows and can't be closed. This dialog doesn't show up when hitting "Toggle Window" from the systray icon.

## Context
KeePassXC configured with the following settings:
:ballot_box_with_check: Minimize instead of app exit
:ballot_box_with_check: Show a system tray icon

Application
```
KeePassXC - Version 2.7.4
Revision: 63b2394

Qt 5.15.6
Debugging mode is disabled.

Operating system: macOS 13.0
CPU architecture: arm64
Kernel: darwin 22.1.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 2.19.2
```
Browser extension
```
KeePassXC - 2.7.4
KeePassXC-Browser - 1.8.6
Operating system: MacIntel
Browser: Chrome/Chromium 109.0.0.0
```
Operating System: macOS Ventura 13.0.1

**Comment by droidmonkey** [comment]
#8719. Update to macos 13.1 fixes it

**Comment by MarkWieczorek** [comment]
This problem persists with macos 13.4.1

**Comment by takedawilliam** [comment]
This problem persists on MacOS 13.5.1, KeePassXC version 2.7.6
