### ISSUE TITLE
When selecting any new item in the treeview, search should be emptied

### ISSUE THREAD

**Issue by treuss** [keepassxreboot/keepassxc#930]
## Expected Behavior
After selecting a node in the treeview, the contents of node should be listed. Any previously endered search terms should be cleared.

## Current Behavior
Currently, if you used the search function and select a new group in the treeview, the content pane still shows the results of the previous search. In order to see the actual contents of the group, you have to manually clear the search field.

## Steps to Reproduce (for bugs)
1. Enter a search term and get a list of search results
2. Click on any new node in the treeview
3. Still find the old results in the content pane

Operating system: Ubuntu 17.04
CPU architecture: Intel(R) Core(TM) i7-4600U CPU @ 2.10GHz, amd64
Kernel: 4.10.0-33-generic

**Comment by TheZ3ro** [comment]
This is expected behavior. In search mode selecting a group will limit the search to that group. If you want to end the search, press ESC or delete the search field

**Comment by treuss** [comment]
This would be the expected behavior, indeed, @TheZ3ro .
What actually happens is, that you receive a result set including any finding of the database. I.e. you see the exact same result set for any random group you select.

**Comment by droidmonkey** [comment]
If you want scoped search, hit the drop down icon next to the search icon and select "search in selected group". Its off by default due to feedback from others.
