### ISSUE TITLE
KeePassXC 2.7.4 segmentation fault only in QEMU-KVM ArchLinux when saving a database

### ISSUE THREAD

**Issue by paulmoncarm** [keepassxreboot/keepassxc#9302]
## Overview
I am using ArchLinux in QEMU-KVM virtualized environment. When I try to save a database (it does not matter how much groups/entries it has - even one is enough) KeePassXC crashes with a segmentation fault. I tried to make a coredump and a backtrace through GNU Debugger (gdb) and it gave me millions of repeating lines (unique ones are below). Software versions are the latest (QEMU 7.2.1, KeePassXC 2.7.4) and everything is up to date.

If there is a possibility that this bug can be resolved by giving to developers any kind of additional information (coredump/backtrace/strace log from software at your taste) I can provide that, just tell me please what would you need.

```
Thread 1 "keepassxc" received signal SIGSEGV, Segmentation fault.
#0  0x00007f7d4e2ad25b in  () at /usr/lib/libc.so.6
#1  0x00007f7d4e2ae8ed in malloc () at /usr/lib/libc.so.6
#2  0x00007f7d4e921122 in QListData::detach(int) () at /usr/lib/libQt5Core.so.5
#3  0x0000560fe4b7c44d in  ()
#4  0x0000560fe4c5f9a2 in  ()
#5  0x0000560fe4b7a15c in  ()
#6  0x0000560fe4c5f7fd in  ()
```

The last two lines repeats endlessly in backtrace generated by gdb.

Unfortunately, it is not possible for me to try another version of KeePassXC easily (only by compiling it).

## Steps to Reproduce
1. Open KeePassXC in up-to-date ArchLinux running inside a QEMU-KVM Q35 (7.2) environment
2. Try to add one entry
3. Save database one or multiple times

## Expected Behavior
Segmentation fault does not occur

## Actual Behavior
Segmentation fault occurs

## Context
Host OS: 64bit ArchLinux up-to-date
Hypervisor: QEMU-KVM Q35
Virtualized environment: 64bit ArchLinux up-to-date with installed from official repositories KeePassXC

The problem **does not occur** in host OS, however it is impossible for me to use KeePassXC in a hypervisor because of restrictions at my work.
Also the problem **does not occur** with a 2.6.6 version of KeePassXC.

## KeePassXC - Help - About - Debug

KeePassXC - 2.7.4
Revision: 63b2394

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 6.1.22-1-lts

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.19.3

Operating System: Linux
Desktop Env: Mate
Windowing System: X11

**Comment by phoerious** [comment]
The stack trace is not very helpful. Can you try that with a snapshot build? Those have debug symbols enabled. https://snapshot.keepassxc.org/

**Comment by paulmoncarm** [comment]
It gave even less information. Maybe I am doing something wrong?
I have executed KeePassXC from an AppImage file, attached gdb to it and it crashed, leaving me with that backtrace.

```
Thread 1 "keepassxc" received signal SIGSEGV, Segmentation fault.
0x00007f32f00ae8e8 in ?? ()
(gdb) bt
#0  0x00007f32f00ae8e8 in ?? ()
#1  0x0000000000000000 in ?? ()
```

**Comment by paulmoncarm** [comment]
I am possibly did a not very smart thing forgotting to mention that the issue does not occur with KeePassXC 2.6.6 with the very same conditions.

**Comment by droidmonkey** [comment]
This looks like a qt problem. How are you running 2.6.6? Appimage, snap, native? I recommend using flatpak.

**Comment by paulmoncarm** [comment]
> This looks like a qt problem. How are you running 2.6.6? Appimage, snap, native? I recommend using flatpak.

The 2.6.6 is run from AppImage (segmentation fault does not occur), the 2.7.4 is tried to run from official ArchLinux repositories and from AppImage (segmentation fault occur on both variants).

It is not possible to run from flatpak at my workspace.
