### ISSUE TITLE
KeePassXC Only Minimizes To System Tray - Also, Can't Move To Other Desktop

### ISSUE THREAD

**Issue by 0pLuS0** [keepassxreboot/keepassxc#9303]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

When I open KeePassXC I see an entry for it in tint2, but if I click on it there in tint2 it just minimizes to the system tray, instead of minimizing on tint2, and it also minimizes to the system tray if I try to move it to another desktop.

I can't remember if this is normal, or it will minimize to panels in Linux as well? I thought it did this before and the only time it minimized is when I closed it, I thought there use to be an option to minimize when clicking close?

I also thought in the past with older versions, I could drag it in the tint2 panel from one desktop to another.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Open KeePassXC
2. With it open on the desktop it shows in the tint2 panel
3. I click on KeePassXC in the tint2 panel and it disappeaers off the desktop and minimizes to the system tray.
4. With KeePassXC open on the desktop and appearing in tint2, I click on it in tint2 and try to drag to another desktop and it disappears and minimizes to the system tray.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

When apps are open on the desktop, I can click them in tint2 and they minimize to tint2, then click them again, and they reopen on the desktop, and I can drag them to other desktops, I thought KeePassXC also acted this way, and it was the behaviour I was expecting.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

I open KeePassXC, click on it in the tint2 panel and it minimizes to the system tray, instead of tint2, or if I click on it and try and move it to another desktop it also minimizes to the system tray.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.4
Revision: 63b2394

[NOTE]: # ( Pick choices based on your environment )
Operating System:  Slackware 15.0
Desktop Env: Openbox 3.6.1
Windowing System: X11

**Comment by droidmonkey** [comment]
Go to application settings and disable minimize to system tray.

**Comment by 0pLuS0** [comment]
> Go to application settings and disable minimize to system tray.

I don't have that option.

![KeePassXC](https://user-images.githubusercontent.com/36190223/230517065-f0e3e89e-1c6d-4e59-bf9f-e9677c23ec48.jpg)

**Comment by droidmonkey** [comment]
Scroll down to the bottom. Are you running a self compiled version? You have no features enabled.

**Comment by 0pLuS0** [comment]
OH I'm an idiot, forgot to scroll down.... LOL

SORRY for the post...

I'll go bang my head now! :face_with_spiral_eyes: 

THANKS
