### ISSUE TITLE
Password Generator Template/Pattern

### ISSUE THREAD

**Issue by nosacs** [keepassxreboot/keepassxc#9304]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
The original KeePass for Windows allowed the user to specify a template or pattern for the password generated.

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )
a template specified as:  ullds
would result in a password with: 
(1) UPPERCASE ALPHA
(2) lowercase alpha
(3) lowercase alpha
(4) number
(5) special character (ie: $,&,#, etc...)

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
In my job there are certain applications that require some characters while others are not allowed and some can only occur one time.

**Comment by droidmonkey** [comment]
Duplicate request to password profiles.
