### ISSUE TITLE
Chrome extensions from Github isn't work while integrate

### ISSUE THREAD

**Issue by gracie95** [keepassxreboot/keepassxc#9306]
## Overview
Downloaded exts from GitHub repo cannot integrate with KeePassXC app. Tried in Brave Browser.

## Steps to Reproduce
1. Download exts from GitHub. Make sure dev mode in browser has activated.
2. Drag exts file (.zip) to extension menu.
3. Now, try connect by pressing **Reload** button on extension.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
The confirmation window should appear when connecting

## Actual Behavior
**Cannot connect to KeePassXC. Check that browser integration is enabled in KeePassXC settings.** 
Message from exts.

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.4
Revision: 63b2394

Qt 5.15.6
Debugging mode is disabled.

Operating system: Windows 10 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.22621

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 2.19.1

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 11

**Comment by droidmonkey** [comment]
You need to add the extension ID manually to the native messaging file if you don't use the one from the store.
