### ISSUE TITLE
Database reverting to previous master password

### ISSUE THREAD

**Issue by Darklesss** [keepassxreboot/keepassxc#9308]
## Overview
I use KeepassXC (v. 2.7.4) with the Keeshare feature, storing the database on my home PC and the export file on my Nextcloud hosted on Linode so I can access it from my work machines, phone, etc. I changed my database master password a few months ago to be a bit stronger.  After working fine for a while it's recently started randomly reverting to the old master password on various devices.

## Steps to Reproduce
1. Open KeepassXC and unlock database
2. Change master password
3. Update master password to the new one on other devices accessing the export file
4. Use normally on multiple devices until it stops working on one

## Expected Behavior
While using one of my devices that rely on the export file on Nextcloud, I expected the database to open with the new password (as it had been doing for several weeks).

## Actual Behavior
The database did not accept the new password. If I try the old password instead, it is accepted. I can change the password back to the new one, though, after logging in with the old one first.

## Context
This has now happened on three different devices running Windows, Linux, and Android (respectively). These issues aren't contemporaneous: when it happens to a given device I can still get into the database on other devices using the correct (new) password. It seems to me that the old master password is stored somewhere rather than being purged (as I would have expected and desired), and individual apps are randomly reverting to the old one. It happened last night on my Android phone, which is using KeePassDroid (i.e., not your software), so the issue seems to be with the export file, not the apps.

**Comment by droidmonkey** [comment]
You have a file sync issue. Correct that and your problems will be solved.
