### ISSUE TITLE
Allow editing of custom tags

### ISSUE THREAD

**Issue by Eyion** [keepassxreboot/keepassxc#9309]
Under the URL of each entry, there is a tag, but it cannot be edited and can only be selected (tags set and migrated in other programs).
Didn't I find the ability to edit tags? Please guide me.

**Comment by droidmonkey** [comment]
Just type out a new one and remove the old one. You need to edit the entry though, not the preview pane.

**Comment by Eyion** [comment]
However, when entering through the input method, only English is supported as a label, not Chinese.It means you can't enter Chinese in the label bar.

**Comment by droidmonkey** [comment]
worked fine for me:

![image](https://user-images.githubusercontent.com/2809491/231326543-d37536e3-cd13-43ac-8425-b3a2cd8a61a1.png)

**Comment by Ardenet** [comment]
I am sorry to reopen this issue, but I am indeed troubled by the inability to input Chinese.

I have used different IM software, including the system Chinese input method software developed by Microsoft, but still cannot input Chinese (which means I cannot input Chinese by typing keyboard letters and then converting them through input method software). However, if I paste the text that needs to be added through the "clipboard", it is true that Chinese can appear in this textbox

This is a example:
![recording](https://github.com/keepassxreboot/keepassxc/assets/69284622/55411b91-f089-4b1e-bd2e-c1214b3522e4)

@droidmonkey I would like to know where I made a mistake, or how you input Chinese. If you could provide me with some guidance, I would greatly appreciate it. Thank you.

**Comment by droidmonkey** [comment]
#7488
