### ISSUE TITLE
Can't select mounted folders for new DB place

### ISSUE THREAD

**Issue by Nihisil** [keepassxreboot/keepassxc#931]
## Expected Behavior

I can choose folder in the any place on my file system for create/open DB.

## Current Behavior

I can only choose `/home/` folder.

## Steps to Reproduce (for bugs)

1. Ubuntu 16.04
2. Package installed with snap
3. Click on the `create new db` button
![img-2017-09-09-13-34-58](https://user-images.githubusercontent.com/475367/30237390-b4ce5004-9563-11e7-90bf-109430eaf70d.png)

## Context
I have mounted /data/ HDD and I wanted to store my db there (because Dropbox is storing on this drive), but I wasn't able to accomplish it.

## Debug Info
KeePassXC - Version 2.2.0
Revision: 9a7e6850d6b79c47c2d46d99fdaf433c2ff13716

Libraries:
- Qt 5.7.1
- libgcrypt 1.7.6-beta

Operating system: Ubuntu Core 16
CPU architecture: x86_64
Kernel: linux 4.10.0-33-generic

Enabled extensions:
- KeePassHTTP
- Auto-Type
- YubiKey

**Comment by droidmonkey** [comment]
This is a snapd bug discussed elsewhere in our issue list.
