### ISSUE TITLE
Brand new Auto-Type

### ISSUE THREAD

**Issue by ghost** [keepassxreboot/keepassxc#9310]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
Auto-Type is good, but it could be better, instead of simulating the keyboard it could just copy and paste the attributes.
This way everything will work much faster, especially for longer passwords.

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )
Maybe something like this
Copy and Paste {USERNAME}{TAB} Copy and Paste {PASSWORD}{ENTER}

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
Because I have long passwords and I use Auto-Type a lot, and simulating the keyboard takes more time than copy-paste, if this feature were added, it would make the Auto-Type feature more efficient.

**Comment by phoerious** [comment]
You cannot simply issue copy/paste from one app into another. Besides, it doesn't work all the time and leaks things to the clipboard. If you need copy/paste, you can always copy with Ctrl+B, Ctrl+C.
