### ISSUE TITLE
Please change link on the site for MSVC Support Libraries

### ISSUE THREAD

**Issue by peter-lisov** [keepassxreboot/keepassxc#9311]
When I download KeePassXC from page: https://keepassxc.org/download/#windows in Windows 11, KeePassXC won't start because MSVC libraries not installed.
There are link to MSVC Support Libraries on the same page, but libraries for arm64, not for x64.
Links on that page below:
https://github.com/keepassxreboot/keepassxc/releases/download//2.7.4/KeePassXC-2.7.4-Win64.msi (For x64)
https://aka.ms/vs/17/release/vc_redist.arm64.exe (For arm64 on samepage)

**Comment by phoerious** [comment]
Thanks. That was supposed to be amd64 (i.e., x64), not arm64.
