### ISSUE TITLE
Unsupported key derivation function on Raspbian

### ISSUE THREAD

**Issue by alensiljak** [keepassxreboot/keepassxc#9312]
## Overview
One of my kdbx databases won't open on Raspbian. It opens in KeePass2. See Context section for details.
Let me know, please, which additional parameters would you like me to add.

## Steps to Reproduce
1. Install `keepassxc` onn a 64-bit Raspbian OS: `sudo apt install keepassxc`.
2. Get a copy of a .kdbx file with Argon2id KDF.
3. Try to open by typing in the password.

## Expected Behavior
The database should open.

## Actual Behavior
Getting "Error while reading the database: Unsupported key derivation function (KDF) or invalid parameters" and the database doesn't open.

## Context
Running the (currently) latest 64-bit Raspbian OS on a Raspberry Pi 3. KeePassXC installed through apt.
Opening the same file with KeePass2 works. KeePass2 also installed via apt.
The kdbx file is using ChaCha20 with 256-bit key and Argon2id key derivation function. 
The file is protected by a password only.

KeePassXC - Version 2.6.2
Revision: e9b9582

Qt 5.15.2
Debugging mode is disabled.

Operating system: Debian GNU/Linux 11 (bullseye)
CPU architecture: arm64
Kernel: linux 6.1.21-v8+

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (only unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.8

Operating System: RaspbianOS 64-bit
Desktop Env: XFCE (I guess), the default
Windowing System: X11

**Comment by droidmonkey** [comment]
You need to update to 2.7.4

**Comment by alensiljak** [comment]
Oh, ok, thanks! So it's a Debian/Raspbian-caused problem, since this is the latest packaged version. My oversight.
