### ISSUE TITLE
Password export wizard to export certain entries directly into a password protected file

### ISSUE THREAD

**Issue by SarenT** [keepassxreboot/keepassxc#9313]
## Summary
Exporting passwords with a shared common password, to share with others is tedious.

1. I need to generate a new database with a shared password (also in my database, pasted during database generation process),
2. then clone the passwords I would like to share in the old database, 
3. and finally drag and drop them in the new database (tab).
This process could be automated very easily with a unique export function.

1. File > Export > Part of the database with Password protection
2. A wizard pops up...
3. Select in a tree view passwords to export (multiple selection)
4. Select master password also in a fresh tree view (single selection)
5. Save as new password database file...

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
This feature matters a lot in smaller organizations like research groups, startups, friends/family, where common accounts can be shared in a decentralized way. It does not require servers to host the passwords etc. Others usually have a shared password for the level of secrecy of the shared password. E.g. level 1 shared PW, level 2 shared PW etc. If the account is critical, we export it with the highest level master PW (separate than personal master PW). Every member has only the levels of master PWs they have access to. I can elaborate more on this. But even in simplest circumstances, this would be useful as pointed above.

**Comment by droidmonkey** [comment]
Captured in #1940. For now we recommend using separate databases that you can auto open, or use keeshare to embed an external database as a group. See the user guide for more info.
