### ISSUE TITLE
Incorrect AutoType behavior

### ISSUE THREAD

**Issue by amandrichenko** [keepassxreboot/keepassxc#9318]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
I've tried to put some of my env variables into KeePassXC db to be able to quickly Auto-Type them into different config files. But it seems to doesn't work every time the same - sometimes Auto-Type skips {ENTER} command and leave two values on the same line, or even mix field values

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Create entry with any title and all other fields empty
2. Go to "Advanced" tab
3. Add additional attributes: POSTGRES_VERSION, DB_HOST, DB_USER, DB_PASSWORD, DB_NAME, DB_PORT, DB_SCHEMA with some values. 
4. Additional attribute DB_PASSWORD set as "protected"
5. Go to "Auto-Type" tab
6. Set "Use custom Auto-Type sequence:"
7. +3 RDS postgres config for bbbbbbbb 12-04-2023{ENTER}POSTGRES_VERSION={S:POSTGRES_VERSION}{ENTER}DB_HOST={S:DB_HOST}{ENTER}DB_USER={S:DB_USER}{ENTER}DB_PASSWORD={S:DB_PASSWORD}{ENTER}DB_NAME={S:DB_NAME}{ENTER}DB_PORT={S:DB_PORT}{ENTER}DB_SCHEMA={S:DB_SCHEMA}{ENTER}
8. Save entry with "OK"
9. Open some project in Webstorm IDE
10. Click somewhere in .env file
11. Alt-tab to KeePassXC
12. Click on created entry
13. Hover "Perform Auto-Type" and choose recently created sequence
14. On "Perform Auto-Type into the previously active window?" answer "Yes"

## Expected Behavior
Every env field=value starts from a new line. For example:

# RDS postgres config for bbbbbbbb 12-04-2023
POSTGRES_VERSION=14.2-alpine
DB_HOST=dev-tennants.xxxxxxxxxxxx.eu-central-1.rds.amazonaws.com
DB_USER=aaaaa
DB_PASSWORD=cccccccccccc
DB_NAME=sssssss
DB_PORT=5432
DB_SCHEMA=test_bbbbbbbbbbb

## Actual Behavior
1. Every time unpredictable result - Auto-Type skips one or two {ENTER} when type, but it may happen in different places, not constantly in one. 
2. Instead of actual DB_NAME I see beginning of the DB_HOST entry till first full stop
3. For example 
# RDS postgres config for bbbbbbbb 12-04-2023
POSTGRES_VERSION=14.2-alpine
DB_HOST=dev-tennants.xxxxxxxxxxxx.eu-central-1.rds.amazonaws.com
DB_USER=aaaaaDB_PASSWORD=cccccccccccc
DB_NAME=dev-tennants.DB_PORT=5432
DB_SCHEMA=test_bbbbbbbbbbb

## Context
[NOTE]: # ( Give us any additional information you may have. )
I've experimented with adding {DELAY 500} right after/before {ENTER} command. Also tried {DELAY 1000} - it doesn't work((

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.4
Revision: 63b2394

Qt 5.15.6
Debugging mode is disabled.

Operating system: macOS 13.3
CPU architecture: x86_64
Kernel: darwin 22.4.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 2.19.2

[NOTE]: # ( Pick choices based on your environment )
Operating System: macOS 13.3.1 (22E261)
Desktop Env: Gnome/KDE/XFCE/Mate/Cinnamon
Windowing System: X11/Wayland

**Comment by droidmonkey** [comment]
What application are you typing into?

This is also a very... unique... use of Auto-Type and not what it is intended for.

**Comment by amandrichenko** [comment]
> What application are you typing into?

I've tried type into JetBrains WebStorm:
```
WebStorm 2023.1
Build #WS-231.8109.174, built on March 28, 2023
```

> This is also a very... unique... use of Auto-Type and not what it is intended for.

Yep, probably you're right, its weird, but I thought that "Auto-Type" will type any string I compose into any place where I'm able to copy/paste

**Comment by droidmonkey** [comment]
Guaranteed you are running into auto complete or  some other ide shenanigans as Auto-Type is doing its thing. If you can replicate this behavior in the plain old notes app, I'll reopen.
