### ISSUE TITLE
Tabs (both locked and unlocked) show .kdbx file name

### ISSUE THREAD

**Issue by mvh0518** [keepassxreboot/keepassxc#9319]
## Summary
Please show .kdbx names in tab titles for unlocked files.

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )
I'd like to see tab titles with open kdbx look like this:
First,kdbx [Unlocked] x

My model is tabs titles with locked kdbx, which look like this:
Second.kdbx [Locked] x

Mousing over the tab titles almost gives the right info (I don't really want *full* pathnames)
Again, tab titles for locked tabs looks pretty good to me.
## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
Today, at least with my settings, the tab titles for all unlocked .kdbx all are the same. It looks like this:
KeePass database x
I keep two kdbx files, one controlled by me and one controlled by my wife.
The reason is that I'm the computer security geek and the financial manager.
Informally, I have read/write permission to my file and only read access to her's.
Many KeepassXC features work well with 2 open files; I have no complaints there.
But when I must manually manipulate or search in the individual kdbx files it would be very convenient to see the 
kdbx file name in the tab title.

**Comment by droidmonkey** [comment]
Change the database name in the database settings. That is what is put on the unlocked database tab title.
