### ISSUE TITLE
[SOLVED] v2.2.0 Linux : Why the key file must necessarily be in /home ?

### ISSUE THREAD

**Issue by jmsauret** [keepassxreboot/keepassxc#932]
KeePassXC can't find a key file apart from /home. A Database is regularly modified, but key file is only read, never written, so KeePassXC doesn't need rights to write/modify this key file.
I can't put my key file on an external storage like an USB drive, i have to put my key file in "/home", the same partition where is stored the database. Not a good idea.

KeePassXC - VERSION 2.2.0
Operating system: Linux Debian/Ubuntu
CPU architecture: amd64

**Comment by droidmonkey** [comment]
If you are using the snap file this is a limitation from snaps.

**Comment by louib** [comment]
@jmsauret AFAIK the key files are opened read only. Did you have errors about trying to open the key file without write permissions, or were you just not able to select it when browsing for it?

**Comment by jmsauret** [comment]
Thanks @droidmonkey and @louib : fuc***g snaps limitations ! I also noticed that in snap package "open URL" (CTRL + U ) doesn' t work. So i uninstalled snap package and installed **keepassxc_2.2.0-1_amd64_oldstable_jessie.deb** (with libyubikey0 and libykpers-1-1 dependencies) and now i can put key file in a USB drive and "open URL"  works.
